### ISSUE TITLE
TinyMCE formatting improvements

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1]
- [x] Quip/Ulysses-like links — https://cloudup.com/cgXAgatVlps — a UI affordance showing the boundaries of the element, allowing you to know when the caret is inside the element vs. outside.
- [x] Same as the above but for `code` blocks (through button or backticks).
- [ ] Spurious markup on blockquote when replacing content. ([Ticket](https://core.trac.wordpress.org/ticket/31523).)
- [x] Option to strip all attributes on paste, except when pasting internally. (Added by @iseulde.)
- [ ] Fix some contenteditable=false bugs: tinymce/tinymce#3325. (Added by @iseulde.)
- [ ] Make sure we have good test coverage for pasting from Google Docs. https://github.com/tinymce/tinymce/blob/4.5.3/tests/plugins/paste.js#L217 (Added by @iseulde.)

https://core.trac.wordpress.org/component/TinyMCE
https://core.trac.wordpress.org/query?status=!closed&keywords=~upstream&component=TinyMCE

**Comment by iseulde** [comment]
- [ ] Option to strip all attributes on paste, except when pasting internally.

**Comment by iseulde** [comment]
We'll also add an `upstream` tag for core tickets.

**Comment by Afraithe** [comment]
Just wanted to notify, work has started (in internal review actually) for 
"Option to strip all attributes on paste, except when pasting internally."

So we are adding a flag so you can see if the paste was internal or external, bit of trickery to get this working, especially with IE since they do not have the new clipboard api.

**Comment by androb** [comment]
We have fixed number 4 above

From Spocke:
> We added that internal flag now to the paste events. This is available in the latest nightly here is a demo of that: http://fiddle.tinymce.com/ZJfaab

Ref Slack message: https://wordpress.slack.com/archives/core-tinymce/p1487683374000080

**Comment by Afraithe** [comment]
2 above was also taken care of during the quip style stuff, or was that not the same intended issue?

Currently working on 3 and 5

**Comment by jasmussen** [comment]
> 2 above was also taken care of during the quip style stuff, or was that not the same intended issue?

Call it the "code boundaries" counterpart to the "link boundaries" task :) So yeah, if there's an extra arrow key stuff outside `<code>` blocks, then that counts. 

Feel free to check the box :)

**Comment by Afraithe** [comment]
Ok, that is taken care off, but there could be other inline boundry elements we might want to look at extending this functionality to, CITE comes to mind, and im sure there are more.

**Comment by jasmussen** [comment]
Revisiting this one, it looks like it might be closable. Are items 3 5 and 6 in this one addressed or ticketed elsewhere?

**Comment by Afraithe** [comment]
All these items are completed, except for the google docs, like to have a more detailed ticket if we are to put some work into that, what specifically isn't working at the moment and needs to be tested.

Suggest closing, and opening new specific tickets of there are items remaining on these or new things.
