### ISSUE TITLE
Text to Visual issues

### ISSUE THREAD

**Issue by hyptx** [WordPress/gutenberg#10006]
**Describe the bug**

When you switch from code view to visual view, the editor wraps every individual list item into an OL or UL. Thus breaking the elements. If you stay in code edit view you can update the post or preview it and the lists look great. As soon as you switch to visual it ruins it.

**To Reproduce**
1. Create an ordered or unordered list in the text editor
2. Switch to visual editor and update

**Comment by arunsathiya** [comment]
I just wanted to note that I tested this and I am not able to reproduce this at my end. When I create a `List` block, add items, toggle to `Code editor` and come back to `Visual editor` the list items show up as expected - they are not broken. [Video](https://cloudup.com/c9m56mXVLmD) showing this behaviour. Do you have screenshots that indicate this behaviour, @hyptx?

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.8.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.13.6

**Comment by adamleone** [comment]
Hello! 

I also wasn't able to replicate the issue. I experienced the same behaviour as @arunsathiya

**Comment by ellatrix** [comment]
I wasn't able to reproduce either. If you still have this issue, please reopen and add clear steps to reproduce the issue.

If I create a list in the text editor, then switch to the visual editor, I get a correct list inside the classic block.
