### ISSUE TITLE
Custom slug/permalink is changed after an update of the post

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#10004]
**Describe the bug**
When you save a post that has a custom slug, the slug is reset to to sanitized version from the title when you save the post.

**To Reproduce**
1. Change the slug of a page using Quick Edit
2. Open the page, do some changes in the content
3. Save your changes
4. See the page: the URL doesn't contain the custom slug you set previously

**Expected behavior**
The custom slug should be kep.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OX X 10.13.6
 - Browser: Firefox 62

**Additional context**
- Gutenberg 3.8

**Comment by designsimply** [comment]
Thank you for reporting this! I think it can be consolidated with #7002. Please let me know if you disagree and we can re-open here.

**Comment by benoitchantre** [comment]
@designsimply I'm not sure it's a duplicate, but they are related. #7002 describes a temporary wrong value for the slug when you reset it, until you save the post. This one is about an unwanted change of the slug by Gutenberg when you save the post (the custom slug is replaced by the default generated from the title).

**Comment by designsimply** [comment]
Okay. Notes for testing:

* Check to see if you can save a custom slug when not using Quick Edit.
* Test all sorts of ways of changing the slug using Quick Edit and make sure they work when the editor is opened.

**Comment by benoitchantre** [comment]
@designsimply It seems that this issue was caused by Polylang Pro.

**Comment by earnjam** [comment]
Closing as an issue with the plugin and not Gutenberg.

**Comment by bplus78** [comment]
Dear Team,

I got exactly the same issue.

From the quick editor the slug can be correctly edited, but when i use the Guttenberg editor, he change automatically the slug by a old article.

This bug kill actually a big parts of my SEO ! 

Furthermore, you seems to have the same issue with SEO pluggin in Guttenberg editor.

Can you check ASAP quickly please ?

Thanks in advance

Best Regards

Robert

**Comment by SargentoKero** [comment]
Same error here, i have yoast seo pro if you need to know.

**Comment by atkoehler** [comment]
> Closing as an issue with the plugin and not Gutenberg.

@earnjam Also have this issue still, when author edits a page they must submit for review (rather than update) which is a separate issue. However, upon submitting for review the permalink URL is changed to the default value rather than the previously set value when the page was published.

This is an issue with Gutenberg not a plugin.

**Comment by earnjam** [comment]
@atkoehler By default the `author` role cannot edit pages. They can, however, publish and edit their own posts. If your `author` role is submitting page edits for review, then something is manipulating the user role capabilities. 

The `contributor` role cannot publish anything, but can submit posts for review. You are correct it appears to wipe the saved custom slug when submitted for review. That is a separate issue from the one originally described here, so I've created a new issue to track that in #13857.

**Comment by basilkhuder** [comment]
> > Closing as an issue with the plugin and not Gutenberg.
> 
> @earnjam Also have this issue still, when author edits a page they must submit for review (rather than update) which is a separate issue. However, upon submitting for review the permalink URL is changed to the default value rather than the previously set value when the page was published.
> 
> This is an issue with Gutenberg not a plugin.

I'm also having this issue - and all of my debugging attempts have led me to believe it's Gutenberg.  Anybody else having this issue?

**Comment by sim1-81** [comment]
i also have this issue for my custom post type
