### ISSUE TITLE
Offer a way to start with empty post or with the demo content

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1000]
Right now, by default, we load our demo content when you access Gutenberg. We should figure out how to start a new post with an empty page. Some ideas:

- querystring argument `new=true` to avoid loading demo content or opposite (qs for loading demo).
- adding a button to load demo content, or a submenu in the sidebar for Gutenberg for starting fresh.

**Comment by youknowriad** [comment]
Or maybe use a site option to load the demo only the first time we access gutenberg

**Comment by mtias** [comment]
I think accessing the demo at any time is invaluable for developing (and user testing), so I think we should always keep it at hand.

**Comment by youknowriad** [comment]
In this case, maybe we should do both:

 - Using a site option to show the demo for new users only once
 - Have querystring argument to force the demo

**Comment by jasmussen** [comment]
I like the query string, as I can just bookmark or for testing.

**Comment by mtias** [comment]
Well, if we use qs we can just add two sub-menus:

![image](https://cloud.githubusercontent.com/assets/548849/26728894/0e184e54-47ac-11e7-9285-0190cbf76146.png)
