### ISSUE TITLE
canInsertBlockType returns true when the parentClientId is not nestable

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#10013]
**Describe the bug**
When using `canInsertBlockType` and passing a blockName (doesn't matter which) and as parentClientId a non-nestable block clientId (the id of a "core/paragraph" for example) it returns true.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call `canInsertBlockType` using a CLIENTID of a block that can't contain innerBlocks `wp.data.select("core/editor").canInsertBlockType("core/paragraph", CLIENTID)`
2. Ir returns true.

**Expected behavior**
If the block can not be inserted, because it is a non-nestable block type, I think it should return false.

**Versions:**
 - WordPress 4.9.8
 - Gutenberg 3.9.0-rc.1

**Comment by youknowriad** [comment]
There's no declarative way to know whether a block is using `InnerBlocks` or no. Selectors can't know if a block is a container block or not which means they can't return different values based on this information.

There's a possibility though, if we find that a block has no block settings (only set in InnerBlocks) it probably means that it has no inner blocks. Worth testing.

**Comment by jordesign** [comment]
Hey @garciaalvaro  - just looping back to this to see if it is still an issue for you?

**Comment by jordesign** [comment]
As I haven't heard back further - I'll close this issue for now.
