### ISSUE TITLE
Paste Markdown from Firefox does not parse into blocks

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#10010]
**Describe the bug**

Using Firefox, if you copy markdown and paste into Gutenberg it will not parse into individual blocks. It is inserted as a single HTML block. The same markdown content when pasted using Chrome will be converted into individual blocks.

**To Reproduce**
1. Copy any markdown text, simplest use case is two paragraphs.
2. Open Gutenberg and paste in the text
3. The text is inserted as one block, not individual blocks

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Firefox 
 - Version: 63

**Additional context**
- Gutenberg 3.8.0

**Comment by arunsathiya** [comment]
Noting that this works as expected for me. When pasting markdown on Gutenberg editor, on Firefox Quantum, the markdown is parsed into individual blocks.

<img width="538" alt="screen shot 2018-09-18 at 22 54 04" src="https://user-images.githubusercontent.com/18581859/45705005-03eaad00-bb96-11e8-9a36-e023c4337a5c.png">

Video showing that behaviour: https://cloudup.com/cYvdkAOlHJw

Same case on Google Chrome as well.

---

- Tested on Gutenberg 3.8.0 with Firefox Quantum 61.0.2 (64-bit) on macOS 10.13.6
- Tested on Gutenberg 3.8.0 with Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.13.6

**Comment by mkaz** [comment]
Hi @arunsathiya - I appreciate you testing it out.

Can you try with a new version of Firebox, it is possible something changed in the beta which is causing this not to work. I tested on the latest Firefox v62 and on the beta Firefox v63.0b7 both of which do not work for me. 

![2018-09-18 15 49 43](https://user-images.githubusercontent.com/45363/45720853-ab49ee80-bb5a-11e8-833e-8bb4841441a3.gif)

**Comment by arunsathiya** [comment]
Hi @mkaz! I didn't notice v63 earlier. :) 

I tested this time with Firefox v63 and it seems to work as expected. You can notice that markdown is parsed as individual blocks, as expected. [Video](https://cloudup.com/cxm9GqTxZqI). 

<img width="759" alt="screen shot 2018-09-19 at 20 24 57" src="https://user-images.githubusercontent.com/18581859/45761602-31912e00-bc4a-11e8-89d7-2fc347af3d7d.png">

**Comment by mkaz** [comment]
@arunsathiya - So strange.

ok, I tried it on my linux laptop, using the same site, same user, and same Firefox version, and it did work.

Cleared cache, tried again on my OSX desktop, using same version of Firefox and OS as you, and it still does not work.  

Console log complains about a couple deprecated things, but looks to be unrelated and the same for both, no other errors.

**Comment by mkaz** [comment]
Closing, since it can't be reproduced. 

It can be reopened if it surfaces for more than just one browser on one computer.

**Comment by AdrienM76** [comment]
I can confirm this is still a problem on Firefox-dev 65.0b9 on MacOS 10.14.2.

I was able to generate blocks one time by 1st pasting into classic editor, re-opening, switching to Gutenberg and converting to blocks, but the md was not parsed completely. I still had to do some surgery.

The behavior is very consistent as it fails every time.

Note, I can type markdown (tables, italics and references do not work regardless) but I can't paste it and have it recognized as anything but plain text.

**Comment by go2tom42** [comment]
> I can confirm this is still a problem on Firefox-dev 65.0b9 on MacOS 10.14.2.

I also have this issue

**Comment by skorasaurus** [comment]
This maybe specific to OS X? 

I'm unable to replicate this bug on Ubuntu 16.04; markdown pasting in firefox (68.0.0) works as expected.
