### ISSUE TITLE
href-attribute not saved on a element, in a registerBlockType()

### ISSUE THREAD

**Issue by puggan** [WordPress/gutenberg#10012]
**Describe the bug**
I used wp.blocks.registerBlockType() to create a block.
In the save part, i use an a-element with an href tag.
When saving the page, the href-tag gets removed.
So when i try to edit the page next time, it gives me a validation error, 
as it dosn't have its href attribute.

**To Reproduce**
1. Add a blocktype, for exemple: https://pastebin.com/cKAtUGf3
2. Add block to page
3. Save page
4. Edit page again.
5. Read the validation-error

**Expected behavior**
The href to be saved when the page saves.

**Screenshots**
Before save:
![screenshot from 2018-09-18 19-45-29](https://user-images.githubusercontent.com/866668/45706049-87e36b80-bb7b-11e8-884c-d8163d9c225c.png)
On next edit:
![screenshot from 2018-09-18 19-45-43](https://user-images.githubusercontent.com/866668/45706050-8a45c580-bb7b-11e8-872b-f166b790af2c.png)
Converted to html:
![screenshot from 2018-09-18 19-45-53](https://user-images.githubusercontent.com/866668/45706054-8c0f8900-bb7b-11e8-9680-0f3d3f692af5.png)
Console.log:
![screenshot from 2018-09-18 19-46-04](https://user-images.githubusercontent.com/866668/45706055-8e71e300-bb7b-11e8-83ff-47ec201fabc8.png)
```
Expected:
<div class="wp-block-spiro-box box box-gold"><a href="/test"><h3>Test</h3><p>test</p></a></div>
Actual:
<div class="wp-block-spiro-box box box-gold"><a><h3>Test</h3><p>test</p></a></div>
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 62.0

**Additional context**
- Guttenberg 3.8.0
- Wordpress 4.9.8

**Comment by youknowriad** [comment]
Everything seems fine for, I wonder if it's not a backend filter remoing the href for some reason. Did you do any progress?

**Comment by puggan** [comment]
If it was a beckend change, then changing the 
I don't have that code left in the site, as we gotten the the jsx-converter working.

But I think the problem was around
```
onChange: function(data) {
props.setAttributes({boxurl: data});
```
data wasn't a string or something like that.

**Comment by youknowriad** [comment]
Thanks for the heads up, closing for now as it seems fixed.
