### ISSUE TITLE
Not compatible with Independent Publisher theme

### ISSUE THREAD

**Issue by 321clic** [WordPress/gutenberg#10016]
**Describe the bug**
Format defined in the editor is not respected on the post preview.
e.g. no line feed/carriage return/line break/line spacing/paragraph. 
all the text is one word after the other.

**To Reproduce**
Activate Independent Publisher theme
Write some blocks 
Save
Preview

**Expected behavior**
I expect the text in the post preview is in the same format as in the Gutemberg editor (with line spacing, carriage return and so on)

**Screenshots**

Gutemberg Editor:
![screencapture-321clic-wordpress-wp-admin-post-php-2018-09-18-21_52_35](https://user-images.githubusercontent.com/43388274/45712688-3e038100-bb8d-11e8-8923-24c96decf66f.png)

Post Preview:
![screencapture-321clic-2018-09-18-21_53_36](https://user-images.githubusercontent.com/43388274/45712786-7c00a500-bb8d-11e8-83eb-6ca545b1585e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 65.0.3325.181 (Build ufficiale) (a 64 bit)

**Smartphone (please complete the following information):**
 - Device:  iPhone6
 - OS:  iOS 11.4.1
 - Browser: Preview From Wordpress APP
 - Version latest

**Additional context**
- Please add the version of Gutenberg you are using in the description.
I am using a wordpress.com site, no self hosting.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by pento** [comment]
Thank you for the bug report, @321clic!

I see that your site is on WordPress.com, I'm able to reproduce this same behaviour with the Independent Publisher theme there, as well as with other themes.

This appears to be an issue that only occurs on WordPress.com, so I've reported it internally there, too.

**Comment by 321clic** [comment]
Hi,
as specified in my bug report, this happens on my wordpress.com blog.
Same behaviour as me has been confirmed by a previous answer from Gary
Pendergast.
Please check if it happens also to you on wordpress.com, not on a local
install.
I believe that most of us are not using a self-hosted installation.

Thanks for your support,
Monia



Il giorno mer 19 set 2018 alle ore 17:25 Arun Sathiya <
notifications@github.com> ha scritto:

**Comment by arunsathiya** [comment]
I should have been more clear. :) I tested on my WordPress.com site as well, and tested against multiple themes. I am still not able to reproduce the issue that you and Gary referenced. 

I have added notes to the internal report as well. 👍🏽

**Comment by youknowriad** [comment]
Closing as WP.com issue
