### ISSUE TITLE
Link Dialog: "Add Link" doesn't reposition when changing between selected links

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#10015]
**Describe the bug**

If a link is selected, and then the user selects another link directly, the position of the "Add Link" popover does not update.

**To Reproduce**

1. Navigate to Posts > Add New
2. Insert a new paragraph block
3. Add some text, with at least two links
4. Click the first link
5. Click the second link
6. Note that the popover hasn't repositioned from the location of the first link

**Expected behavior**

The popover should reposition when changing the selected link.

**Screenshots**

In the video below, note that positioning works correctly when I first unselect the link and select the other, but not when clicking directly between the two links.

![link-selection](https://user-images.githubusercontent.com/1779930/45711117-8f444e00-bb56-11e8-9d38-a6328b0543ed.gif)

**Desktop (please complete the following information):**

Chrome Version 69.0.3497.92 (Official Build) (64-bit)
macOS High Sierra 10.13.6 (17G65)

**Comment by designsimply** [comment]
Closing in favor of #7992.
