### ISSUE TITLE
Embed Block: handle click events

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1002]
Should we catch all click events occuring within the iframe/embed content and disable them in the editor context? That could be an easy way of not needing an overlay but preventing video from playing, tweets from navigating away, etc.

**Comment by aduth** [comment]
Not easily: https://stackoverflow.com/questions/2381336/detect-click-into-iframe-using-javascript

**Comment by mtias** [comment]
Right, the implementation can still be through an overlay, just not a visible one.

**Comment by westonruter** [comment]
Using `pointer-events:none` with `tabindex=-1` seems to work without having to add an overlay: https://jsfiddle.net/westonruter/11279unb/

**Comment by iseulde** [comment]
@westonruter Nice! Do you need the `tabIndex`? Seems to work fine here without.

**Comment by westonruter** [comment]
@iseulde yes, the `tabIndex` is needed as otherwise you can tab into the `iframe` window.

**Comment by iseulde** [comment]
That's okay, right?

**Comment by westonruter** [comment]
I thought the goal was to prevent a user from interacting with an `iframe`? If they can tab inside of an `iframe`, then this wouldn't happen:

> preventing video from playing, tweets from navigating away, etc.

**Comment by iseulde** [comment]
Well, we'd prevent it as long as the block is not selected. If the block is selected, they can interact with it? (Same as core now.) So we take `pointer-events: none` away for `.is-selected`. Tabbing wouldn't matter for this.

**Comment by iseulde** [comment]
@westonruter Like this? https://github.com/WordPress/gutenberg/pull/1028/commits/79495e03949b7b3272ba022562ae6d1e2ae9997c

**Comment by westonruter** [comment]
OK, I didn't realize that the `iframe` should be able to be interacted with if the block is selected.

**Comment by jasmussen** [comment]
Just cross referencing this with #483

**Comment by mtias** [comment]
Let's just keep one. Closing in favor of #483.
