### ISSUE TITLE
Scrollbar flickers in code editor when editor is larger than screen

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#10026]
If you use the code editor to edit a post that is vertically larger than the browser, each key press results in the scroll bar flickering. I've tried to show this here:

https://cloudup.com/cHXBC5WI62n

I've tested this in Chrome and Safari. It doesn't happen in the visual editor. It's possible this is just one of those browser things, but I don't recall seeing it in other editors and so I wonder if something is happening with the height that is triggering the scrollbar to appear and disappear.

**To Reproduce**
1. Create a post with a single paragraph that is taller than the browser.
2. Switch to code editor
3. Scroll to bottom of code editor and start typing. Note that scrollbar flickers

Note this is on MacOS with `Show scroll bars` set to `automatically based on mouse or trackpad`. The problem also occurs when it is set to `when scrolling`, but disappears when set to `always`.

**Expected behavior**
No flickering.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 69.0.3497.92 & Safari 12

**Comment by ellatrix** [comment]
@johngodley Are you still experiencing this issue? Tested with Chrome on MacOS and I can't reproduce the problem.

**Comment by johngodley** [comment]
Nope, not seeing any flickering with the latest build. Closing as fixed!
