### ISSUE TITLE
How do I add a custom input to an existing panel in the sidebar?

### ISSUE THREAD

**Issue by stefanwebicon** [WordPress/gutenberg#10023]
Hi,

Please tell me how I would add an custom input to an existing panel, for example beneath "Stick to the Front Page" checkbox. Thank you.

**Comment by stefanwebicon** [comment]
Hi, has anyone succeed with this issue? Thank you!

**Comment by youknowriad** [comment]
Hi there! this tutorial should help

https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/plugin-sidebar-0/

Not that the tutorial is using the Sidebar Slot, while in your use-case you should prefer the `PluginPostStatusInfo` shown here https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-edit-post/#pluginpoststatusinfo
