### ISSUE TITLE
Image Gallery does not show modal image/image gallery

### ISSUE THREAD

**Issue by mjrouleau** [WordPress/gutenberg#10039]
With the standard editor on WordPress.com, when I click on an image from a gallery, I access a viewer that allows me to navigate from one image to the next without leaving the viewer.

With Gutenberg, when I click an image from an image gallery, I have to navigate back to the page each time I want to see the next image. I feel this is a GREAT LOSS in usability.

**Comment by tofumatt** [comment]
This is advocating for galleries to include, I assume, JS that causes the clicked image to appear in a JS modal on top of all other page content.

I think this is a worthwhile addition; the current gallery frontend implies to me that I can click each image, and the link to the individual file page is pretty underwhelming.

**Comment by anevins12** [comment]
I don't think this accessibility label is correct. This is an issue for all users and does not discriminate.

**Comment by tofumatt** [comment]
Yes, but the modal we may want to implement will have accessibility concerns.

- Matt (Sent from mobile)

**Comment by tecnogaming** [comment]
I also lost the galleries when switching to gutenberg.  In fact, I lost so many things that I'm thinking going back to classic editor and never look back.  Gutenberg is a good idea but there are so many steps backward in functionality that is shocking.

**Comment by anevins12** [comment]
Thanks for the feedback @tecnogaming , I think you would benefit from a review on WordPress.org: https://wordpress.org/support/plugin/gutenberg/reviews#new-post

**Comment by mtias** [comment]
Thanks for reporting your issue. Closing here as it should get solved on the Jetpack plugin: https://github.com/Automattic/jetpack/issues/10246
