### ISSUE TITLE
Pressing return in the title field just adds a space

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1003]
![let me write already](https://cloud.githubusercontent.com/assets/191598/26731920/ad22b68e-4783-11e7-8f3e-853156528350.gif)

If I'm writing a new post, and hit return while in the title field, it just adds spaces. I kind of expected that it would create a new text block and let me start writing.

**Comment by aduth** [comment]
@iseulde Should this have been fixed by #913?

**Comment by iseulde** [comment]
I messed up: #1010. :/
