### ISSUE TITLE
What is the recommended theme for Gutenberg and how to use it in Mobile browsers?

### ISSUE THREAD

**Issue by daniyaree** [WordPress/gutenberg#10038]
I have been trying Gutenberg with vanilla install of latest stable WP. Can you please point me to a guide / doc / tutorial that says
1) What theme to be activated to get exact things as shown in Gutenberg in Published page ? Using just default themes as in latest WP does NOT show stuffs in Published page as shown in Gutenberg. For example, fonts are different, 2 block side by side in Gutenberg - one goes somewhat down in Published page. Any working demo site that solves this things and what theme this demo site uses ?
2) Majority of end users are mobile users. How this Gutenberg can be used easily in mobile ? What will happen to bicolumn or tricolumn text paragraphs in Published pages in mobile displays ?

**Comment by daniyaree** [comment]
Gutenberg shows. But the output or Published Page does not give intended looks in the default theme of latest stable WP.

**Comment by tofumatt** [comment]
Gutenberg is not an exact "What you see is what you get" (WYSIWYG) editor; the intent is not to render a 1:1 copy of how a theme will render a page inside the editor. @karmatosed explained this really well at WordCamp London in 2017, but I couldn't find the video 😢

Gutenberg is designed to work on mobile browsers; your page content on mobile is largely up to your theme to render.

It's up to your theme to accommodate the output of your page for mobile browsers, but any output that is created by Gutenberg is designed to be responsive.

**Comment by daniyaree** [comment]
But finally a reader will see what is shown in a webpage in a theme. And not what I see in Gutenberg. Thus to save me double work, Gutenberg should either "detect" the theme and behave accordingly OR Gutenberg should open in-page and let me do the content creation. Otherwise how is it "Gutenberg" ? In Gutenberg machines you used to get exactly what typefaces you saw and what you laid out on printed paper. If writing is not front-end how is the hassles saved ? Also, 
- I do not find how I can create Excerpts in Gutenberg. Is it hiding somewhere there or is there any separate github issue for it ?
- the formatter bar B (bold) etc appearing below my last or latest line constantly hinders and impedes as if someone is writing another chunk of last line 
- on pressing Enter, as in this github text box, I go to the immediate next line, in Gutenberg it is double space, thus poem lines cannot be created.

 Many thanks.
