### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by photogenicworld** [WordPress/gutenberg#10030]
**Describe the bug**
Featured image doesn't show in preview

**To Reproduce**
1. Set a Featured image in Gutenberg
2. Click Preview

**Expected behavior**
Featured image appears in preview

**Actual behaviour**
Featured image does not appear

**Comment by tofumatt** [comment]
Tested this and it does appear when set in the Classic Editor but not in Gutenberg.

**Comment by designsimply** [comment]
Thanks for the report! Closing as a duplicate of #9151.
