### ISSUE TITLE
No Media Files When Trying to Edit Image Block

### ISSUE THREAD

**Issue by markolbert** [WordPress/gutenberg#10048]
Gutenberg is no longer able to "see" the contents of my media folders when I try to specify an image for an image block. When I click on the Media Library button in the image block, the image selector comes up, but no images are shown when I click a folder that I know contains images. 

I confirmed the presence of images in the media folders I check by going through the Media -> Library interface from the main dashboard menu. The files are there, they just don't show up from within gutenberg.

I confirmed this behavior in both an existing post and a brand new one.

I am running WP 4.9.8 in multisite mode, with Gutenberg 3.8.0.

**Comment by designsimply** [comment]
> when I click a folder that I know contains images

How are you making folders for your images? If you are using a [plugin](https://wordpress.org/plugins/) for that, can you please link to which plugin in a reply?

**Comment by markolbert** [comment]
Good question, I should've provided that information.

I have Media Library Folders Pro, from MaxFoundry, installed. I've used it to create a couple of folders that contain images.

I checked both those folders and the older folders created by WordPress (e.g., the year/month based ones), and none of them display images when I try to add an image within Gutenberg.

**Comment by youknowriad** [comment]
Thanks for the issue, now that WordPress 5.0 is out I suggest reaching out to the plugin authors if you're still experiencing the issue. Gutenberg doesn't do anything special when it comes to media handling.
