### ISSUE TITLE
Inserter popover gets cutoff

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1004]
<img width="737" alt="screen shot 2017-06-02 at 11 09 52 am" src="https://cloud.githubusercontent.com/assets/191598/26731998/052e5e96-4784-11e7-97a2-3e4467500fde.png">

I think the popover needs to be more aware of its surroundings, and adapt so its always in view.

**Comment by aduth** [comment]
Much more obvious an issue now that we have a standalone "New Post" screen.

**Comment by mehigh** [comment]
This can work if the JS would take into consideration the height of the .editor-visual-editor when adding the balloon - and when there isn't enough room to switch it to the bottom instead.

<img width="850" alt="is-bottom-class-used-helps" src="https://user-images.githubusercontent.com/367593/27177057-66cd34a6-51c5-11e7-82ba-304c8e2f7ba4.png">
