### ISSUE TITLE
Image galery types

### ISSUE THREAD

**Issue by mjrouleau** [WordPress/gutenberg#10040]
With the standard editor on WordPress.com, we can choose from a number of layouts for image galleries. (Square thumbnails, circles, mosaics, etc)

With Gutenberg, when can only choose the number of columns.

I feel this is an important feature loss.

**Comment by tofumatt** [comment]
Thanks for the feature request! Right now we're focused on fixing bugs with Gutenberg and improving its API for plugin developers. I think a more customisable gallery block would be a great third-party addition, possibly even one that WordPress.com (which is a different editor) might want to implement as a block.

I don't think we'll be implementing that in Gutenberg in the near future though, so I'm going to close this as something we won't fix, but it would be totally possible to implement as a block–it's just up to a plugin developer to ship something like this 😄
