### ISSUE TITLE
Not able to turn off "Likes" and "Share" functions on posts and pages

### ISSUE THREAD

**Issue by SAYYEYE** [WordPress/gutenberg#10049]
**Describe the bug**
I'm not able to turn off "likes" and "share" functions on WordPress.com's pages and post while in the editor. 

**To Reproduce**
1. Go to 'a page or post.'
2. Check off 'Show likes' button and 'Show sharing buttons.'
3. Scroll up to 'Update draft'
4. Click on "Preview."
4. See error; users are still able to like and share Pages and Posts that were marked otherwise not to. 

**Expected behavior**
Users should not be able to like or share Pages and Posts that were marked otherwise not to

**Screenshots**

**Desktop (please complete the following information):**
 - OS X 10.12.6
 - Chrome
 - Chrome 69 on macOS (Sierra)

**Smartphone (please complete the following information):**
 - Device: iPhone6 Plus
 - Browser: Safari

**Additional context**
- I'm using the new Gutenberg offered for testing on my Admin page.

**Comment by designsimply** [comment]
I added the `Needs Testing` label and wanted to note that we should check whether this problem only appears in the Preview or if it also happens when the post is published.

**Comment by SAYYEYE** [comment]
Thank you. This occurs in Preview and Published mode. 

Best,
Yegide Matthews

**Comment by ellatrix** [comment]
Hi @SAYYEYE. This is the bug tracker for the block editor's core. The sharing buttons are an extension by WordPress.com and JetPack. Please contact their support for help. Thanks!
