### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use object of type WP_Block_Parser_Block as array

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#10047]
`gutenberg_render_block()` no longer works since 3.8.0

`Fatal error: Uncaught Error: Cannot use object of type WP_Block_Parser_Block as array`

```
/**
 * Renders a single block into a HTML string.
 *
 * @since 1.9.0
 *
 * @param  array $block A single parsed block object.
 * @return string String of rendered HTML.
 */
function gutenberg_render_block( $block ) {
	$block_name  = isset( $block['blockName'] ) ? $block['blockName'] : null;
	$attributes  = is_array( $block['attrs'] ) ? $block['attrs'] : array();
	$raw_content = isset( $block['innerHTML'] ) ? $block['innerHTML'] : null;
	if ( $block_name ) {
		$block_type = WP_Block_Type_Registry::get_instance()->get_registered( $block_name );
		if ( null !== $block_type && $block_type->is_dynamic() ) {
			return $block_type->render( $attributes );
		}
	}
	if ( $raw_content ) {
		return $raw_content;
	}
	return '';
}
```

I think it should be `$block_name  = isset( $block->blockName ) ? $block->blockName : null;` etc. now.

Also, it has no handling for `innerBlocks`.

How to parse blocks (`gutenberg_parse_blocks( $post->post_content )`) and then render them manually one by one?

**Comment by raquelmsmith** [comment]
We are also experiencing this issue. Any help would be appreciated.

**Comment by raquelmsmith** [comment]
@manake The issue here is that `gutenberg_render_block` now (not sure when this changed) returns an array of objects, not an array of arrays. 

So `$block['blockName']` needs to be `$block->blockName`. `$block['attrs']` is now also an object, so accessing the attributes looks like `$block->attrs->myAttr`.

**Comment by manake** [comment]
Yes, I think the
```
if ( $raw_content ) {
	return $raw_content;
}
```
part also needs an update by now.

For anyone solving/commenting here's what I was trying to do:
1. Extract all blocks using `gutenberg_parse_blocks( $post->post_content )`.
2. Use `foreach` to remove the very first block but only if its `blockName === 'something/something`.
3. Render all other blocks.
4. (So `apply_filters( 'the_content', $post->post_content )` is not an option for me.)
