### ISSUE TITLE
Inputs within blocks can't be focused immediately

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1005]
![give me that input](https://cloud.githubusercontent.com/assets/191598/26732097/6c9fa634-4784-11e7-98c1-65f2de9b9933.gif)

I have an empty embed block. I want to paste a URL in, but when I click on the input the first time it selects the block — not the input. I have to click a second time to focus the input so I can paste my URL.

**Comment by iseulde** [comment]
#1024 fixes this too.
