### ISSUE TITLE
Copy article bug from IE browser

### ISSUE THREAD

**Issue by xiaoma0105** [WordPress/gutenberg#10056]
更新3.8.0后，从ie复制文章到wordpress，会把页面里的css或JavaScript代码也显示出来

**Comment by designsimply** [comment]
Because this is an international project, we use English. I have translated using https://translate.google.com/. 

> After updating 3.8.0, copying articles from IE to wordpress will also display the css or JavaScript code on the page.

**Comment by designsimply** [comment]
Note: I wonder if this is the same behavior as https://github.com/WordPress/gutenberg/issues/9719.

**Comment by designsimply** [comment]
This should have been fixed by https://github.com/WordPress/gutenberg/pull/10019. Thank you for reporting this issue, and if you have upgraded to the latest version of WordPress and you are still seeing the problem happen, please reply here to let me know!
