### ISSUE TITLE
Avoid use of `glob()` when loading PHP files

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10052]
Use of `glob()` isn't reliable across distros, and also has some negative performance implications.

Instead of:

```
foreach ( glob( dirname( __FILE__ ) . '/../block-library/*/index.php' )
```

We should `require_once` each file individually, e.g.:

```
require_once dirname( dirname( __FILE__ ) ) . '/packages/block-library/src/archives/index.php';
```

It looks like there aren't that many files in the first place:

```
$ ls packages/block-library/src/*/index.php | wc -l
6
```

From https://github.com/WordPress/gutenberg/pull/9946#issuecomment-422832164

**Comment by pento** [comment]
Yah, this was just a developer convenience thing.

It'll need to be changed for merge at the absolute latest, but I think it's safe to change anytime, really. We're not going to be making massive changes to the block library between now and then.
