### ISSUE TITLE
Invalid block ellipsis menu clashes with contextual toolbar menu

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#10069]
If you trigger an invalid error in a classic block you get an overlapping ellipsis menu:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/45821292-b6c72200-bce0-11e8-91dc-1887d91b28ba.jpg)

This seems to be because the classic block's dropdown menu is in the same position as the invalid block warning. As far as I can tell all other blocks have a dropdown menu elsewhere.

This is the code responsible for the extra dropdown menu:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-list/block.js#L516

`{ shouldShowContextualToolbar && <BlockContextualToolbar /> }`

The following code fixes the problem, but removes the dropdown entirely and so probably isn't a good solution. I'm unsure what the correct behaviour should be:

`{ shouldShowContextualToolbar && isValid && <BlockContextualToolbar /> }`

There may be other blocks that use the contextual toolbar and could also suffer the same problem.

**To Reproduce**
1. Add a classic block
2. Pick 'edit as HTML' on the block
2. Copy the SVG from https://raw.githubusercontent.com/WordPress/gutenberg/master/docs/final-g-wapuu-black.svg and paste it into the block
3. Switch block back to visual editor
4. Note the block shows an invalid warning
5. Click in the top right corner to expose the block's normal dropdown menu, as well as the invalid block warning menu

**Expected behavior**
No overlapping menus

**Comment by mtias** [comment]
This is no longer an issue with the toolbar placement:

![image](https://user-images.githubusercontent.com/548849/48326082-5d131200-e616-11e8-804b-021b435e421f.png)
