### ISSUE TITLE
How to deal with custom post content for qTranslate?

### ISSUE THREAD

**Issue by herrvigg** [WordPress/gutenberg#10078]
hello,

we are trying to support Gutenberg with **qTranslate-X**. This project has 100.000+ installations but it's been abandoned. We are reviving it in a new repo as [qTranslate-XT](https://github.com/qTranslate/qtranslate-xt) (temporary name). Now Gutenberg is essential for the future of this plugin!

# Our need

Basically what we want is to **patch the post content on top of the Gutenberg blocks** to handle multiple fragments of the post content in different languages. It cannot be handled by Gutenberg blocks. Or at least they have not been designed for this. More details are given below.

If you look at the workflow of the [editor](https://wordpress.org/gutenberg/handbook/packages/packages-editor/), we want to add some custom functionality between the saved data and the parser, and the other way around.

To be clear i put it here in the **red boxes** on this figure:

![image](https://user-images.githubusercontent.com/19155375/45837008-97df8480-bd0e-11e8-9087-643e587ef8ed.png)

# How to?

The idea is to intercept the moment when the edited post is sent to the REST API for UPDATE (PUT on /wp/v2/posts/[id]) and either change the content client-side or add extra fields to recompose the post server-side.

The problem we face is that Gutenberg does not allow us to deal easily with the internal state and we lack some event mechanism to change how the data is processed. Disclaimer : I'm new to React and Redux so it's not a very easy thing to grasp. Also, being able to deal with a real post update and the autosave is a challenge.

However i've spent quite some time analyzing the internal code of Gutenberg. Here are some options i have considered:

### Hooks
It seems no hook currently supports this on the client-side. The available possibilities are very limited, and it's mostly for blocks. The core of Gutenberg is React and Redux so better to go this way.

### Custom reducer on editor's store (Redux):
What looks the most promising would be to interact with this ([editor/src/store/effects/posts.js](https://github.com/WordPress/gutenberg/blob/cbee072d55a82b1b5d270636f685f081ccba23b3/packages/editor/src/store/effects/posts.js)):
```
dispatch( {
		...updatePost( toSend ),
		optimist: { id: POST_UPDATE_TRANSACTION_ID },
	} );
```

This triggers the UPDATE_POST action. What i'd like to do here is either to add some fields to the data being sent or change the whole content just before it is sent. There is apparently a way to _register new reducers_ but it concerns a different store. So that doesn't look good. It may be possible to _replace the default reducer_ with a _composed one_, but how to access the original reducer?? How can i then deal with both the update and autosave?

### Create a specific store and reducer
That looks very complicated if i still want to guarantee the usual workflow. How can this live together with the default store? It will most likely be completely unmaintainable.

### Middleware (REST)
The idea here would be to patch the data being sent to the REST API. But i don't know to relate it to the post update specifically. The problem is that it's completely asynchronous and i'm only interested in the the UPDATE_POST action (including autosave). And the action is not even provided to the middleware.

### Custom "hidden" block
This doesn't look as a good solution, as this info should not be accessible to the user. Also, we want to be on top of the blocks content (see details below), but maybe a specific block could carry specific information. However it would need to be completely hidden and not editable by the user. Gutenberg Blocks are not likely to be designed for this.

### Meta-fields
I have made some experiments trying to add some meta fields carrying custom information (a bit like ACF if you want). This actually kind of works! But there are several problems. First, i don't really know how to force those to be sent without being handled by the writer. Then i don't want to save those, it's only to carry for transactional data so it's kind of a hack. Also it would be a very fragile solution prone to many bugs if the meta fields are removed for some reason, either by some plugins or the user.

# Technical details about qTranslate

The main idea of qTranslate is that the multi-lingual content is embedded in the same post. There are specific blocks like this: `[:en]English content[:fr]Contenu en francais[:it]Contenuto in italiano[:]` which have nothing to do with Gutenberg blocks so far. In our framework Gutenberg is meant to be edit a given language, which is a fragment of the post content. Essentially we want to embed Gutenberg inside our own qTranslate blocks!

```
[:en]
<!-- wp:paragraph -->
<p>A first paragraph in english</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A second paragraph in english</p>
<!-- /wp:paragraph -->

[:fr]

<!-- wp:paragraph -->
<p>Premier paragraphe en francais</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Second paragraphe en francais</p>
<!-- /wp:paragraph -->
[:]
```

Since the whole content exists in multiple versions we want the possibility to edit the content in Gutenberg for a given language. With the classic editor all the switch logic of was made client-side with TinyMCE, by editing one language at a time and sending a form with all the fragments separately, recomposed by the server before the post is being saved.

Later on, we might develop features to handle multi-lingual Gutenberg blocks, i.e. natively by Gutenberg, but this is not our main need for the moment.

So, how can Gutenberg give the flexibility we need here?

**Comment by youknowriad** [comment]
Hi and sorry for the late response, this is indeed a technical challenge as Gutenberg interacts with the REST API directly and doesn't expect post_content not being the "source of truth".

I feel like the best bet at the moment is trying to use a wp.apiFetch middleware to update the post_content property properly upon fetch and save.

I'd like to know if you made progress since the opening of the issue?

**Comment by herrvigg** [comment]
Well it's still very experimental but i have an initial piece working based on wp.apiFetch. It looks like this:

```
    wp.apiFetch.use((options, next) => {
        if (options.path) {
            const post = wp.data.select('core/editor').getCurrentPost();
            if ((options.path.startsWith('/wp/v2/posts/' + post.id) && options.method == 'PUT') ||
                (options.path.startsWith('/wp/v2/posts/' + post.id + '/autosaves') && options.method == 'POST')) {
post);
                if (! post.hasOwnProperty('qtx_editor_lang')) {
                    return next(options);
                }
                const newOptions = {
                    ...options,
                    data: {
                        ...options.data,
                        'qtx_editor_lang': post.qtx_editor_lang
                    }
                };
                const result = next(newOptions);
                return result;
            }
        }
        return next(options);
```

If `wp.apiFetch` is here to stay, this could work. The field called `qtx_editor_lang` is custom data that is necessary to give extra context to the post, initially set from the server side. I don't know if there are better ways to do that.

**Comment by gziolo** [comment]
> If `wp.apiFetch` is here to stay, this could work. The field called `qtx_editor_lang` is custom data that is necessary to give extra context to the post, initially set from the server side. I don't know if there are better ways to do that.

It looks like a good approach. We use similar `apiFetch` middlewares in Gutenberg:
- https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/user-locale.js
- https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/http-v1.js

I will close this issue as it seems to be resolved. Let us know if you need more info.
