### ISSUE TITLE
Cannot use cover image or gallery blocks with roles such as author in a single install or editor/admin in multisite

### ISSUE THREAD

**Issue by miguelurtado** [WordPress/gutenberg#10076]
**Describe the bug**
The blocks Cover and Galerry Images only work with editor and administrator role. In multisite only work with super administrator.

**To Reproduce**
1. Go to admin posts with author role and create new post.
2. Click on new block > select Cover Image > configure the block > save the post.
3. Open the post in front end view
4. Update (F5) the post edit page.
5. See error (image print)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3810528/45833359-e115e100-bcda-11e8-9f37-e475bec0e487.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 69.0.3497.100

**Comment by designsimply** [comment]
Tested and confirmed using the author role on a site running WordPress 4.9.8 and Gutenberg 3.9.0-rc.2 tested with Firefox 62.0 on macOS 10.13.6.

API request for the media during editing:

`http://alittletestblog.com/wp-json/wp/v2/media/14063?context=edit`

API response: 

`{"code":"rest_forbidden_context","message":"Sorry, you are not allowed to edit this post.","data":{"status":403}}`

![screen shot 2018-09-20 at 5 49 48 pm](https://user-images.githubusercontent.com/1119271/45852665-2ef01080-bcfe-11e8-8b8c-7dad7448a07c.png)

![screen shot 2018-09-20 at 5 52 51 pm](https://user-images.githubusercontent.com/1119271/45852668-31eb0100-bcfe-11e8-98e0-b5a4a34f525c.png)

**Comment by miguelurtado** [comment]
Hello @aduth 
Thanks for reply, this related of unfiltered_html capacity.

**Comment by mtias** [comment]
This should be addressed with https://core.trac.wordpress.org/changeset/43781
