### ISSUE TITLE
Callback to execute on block insertion

### ISSUE THREAD

**Issue by narendraj9** [WordPress/gutenberg#10082]
I want a block's attributes to be initialized during insertion of the block in editor. I couldn't find a callback that can accomplish that. Is there is a callback already?

**Comment by aduth** [comment]
Can you elaborate on your use case? For most blocks you shouldn't want or need to respond to specific points in time of an editor lifecycle, but rather represent its editable form as a function of attributes at any given point in time.

That being said, a block's `edit` can be defined as a component class (`wp.element.Component`), meaning you can leverage component lifecycle of mounting like `constructor` and/or `componentDidMount`.

https://reactjs.org/docs/react-component.html#the-component-lifecycle

Preemptively closing, but can be reopened if provided solutions are not sufficient given more context on the use-case.

**Comment by aduth** [comment]
>What I would like to do now is re-compute the attributes of my block before the post is published to make sure that the attributes are in sync with contents of the rest of the blocks.

I would suggest always deriving the value of your attributes upon any change in the system.

**Comment by Tofandel** [comment]
What about initializing props with values that change depending on some factors (and thus cannot be provided with default), that seems like a valid use case.

Is it possible to provide a callback 'created' in the registerBlockType arguments, like save or edit?

**Comment by aduth** [comment]
> What about initializing props with values that change depending on some factors (and thus cannot be provided with default), that seems like a valid use case.

Can you share a specific example?

It would be fine to update attributes after the block is mounted. In fact, if I recall correctly the core embed block already works this way. One challenge you may face here is related to the creation of undo levels when updating attributes, which is tracked for improvements at #8119.

**Comment by Tofandel** [comment]
If I have a block that needs a unique identifier for example, and want the user to be able to change it but not necessarily,  
then I'd have to init the attribute with some generated random chars

**Comment by oxyc** [comment]
I just had a use case, where I want all Media & Text blocks to have the imageFill enabled by default. I solved it with:

```js
import { createHigherOrderComponent } from '@wordpress/compose';
import { addFilter } from '@wordpress/hooks';

const withForcedImageFill = createHigherOrderComponent(BlockListBlock => {
  return (props) => {
    if (props.name === 'core/media-text' && !props.attributes.mediaType) {
      props.attributes.imageFill = true;
    }
    return <BlockListBlock { ...props } />;
  };
}, 'withForcedImageFill' );

addFilter('editor.BlockListBlock', 'sage/with-forced-image-fill', withForcedImageFill);
```

But this relies on the fact that mediaType is not set on initial insertion, the same would not work on other blocks.
