### ISSUE TITLE
Clunky UX when publishing hides categories.

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#10083]
When I publish a new post, the categories are suddenly hidden, and replaced with an "are you sure" message with a ton of whitespace below. Pre-Gutenberg, I would often add my categories after publishing, realizing I had forgotten one or two.

**Describe the solution you'd like**
Instead of hiding the categories/tags with an "are you sure" message, leave the categories/tags in view so they can be selected without explicitly refreshing the page.

**Comment by youknowriad** [comment]
Thanks for raising those concerns, the prepublish sidebar has been introduced for several reasons:

 - Avoid unexpected publish by making it two steps
 - Add a prepublish are for plugins to extend. (think SEO checks, validation...)

That said as of #9760, you'd be able to opt-out of the pre-publish panel.
