### ISSUE TITLE
Need a way of rescue from "broken" block when the template of blocks is locked

### ISSUE THREAD

**Issue by macemmek** [WordPress/gutenberg#10092]
**Problem**
I have a locked template of blocks for the post type.
When I edit the post and make something bad, i.e. change block's HTML, the prompt "This block has been modified externally" appears.
From this point, I cannot do much to fix it. Normally, I would remove the block and add a fresh one but I'm locked.
Only when I exit and go back, I am able to reset the template, what removes all the content anyway.
I think that regular users will be confused.

**Idea of solution**
I would like to be able to reset the template from edit post level without exiting the broken, locked post.
Ideally, the reset wouldn't destroy the "valid" blocks.

**Comment by designsimply** [comment]
Apologies for the delay in reply! I looked for similar issues and found https://github.com/WordPress/gutenberg/issues/13413 which I think covers your case and also has some recent discussion and I would like to close this issue in favor of that one.

@macemmek if you disagree and think #10092 should remain open separately, would you please reply back here to let me know? Thank you!

**Comment by designsimply** [comment]
Closing with a note that this issue can be re-opened later if needed. 

We are working to prioritize new development for this repository and [move help requests to the appropriate support forums](https://github.com/WordPress/gutenberg/issues/new?template=Custom.md). Thank you for your understanding!
