### ISSUE TITLE
RichText : postmeta data can't be json or json like data

### ISSUE THREAD

**Issue by kahenvay** [WordPress/gutenberg#10100]
**Describe the bug**

If you try to save (update) a post whith a RIchText field that has JSON-like data, the post will show an update error. It will still save some other PlainText fields (nearly none, sometimes none, seems to be fields after RichText field with JSON-like date), but won't save other RichText fields. Worse is if you remove the fields without removing the JSON-like data in the DB, nothing will save anymore, not even a simple input fields. The field with the JSON-like data can be saved at will though.

**To Reproduce**
1. Add attributes to block with source meta and a meta key.
2. Add some PlainText fields, RichText fields
3. Enter a JSON-like text in a RichText field ex: ["test"]
4. Update
5. Try to change a field PlainText field "under" this RichText, or any other RichText field.
6. See error

**Expected behavior**

Field to simply save as string or stringified data.

**Screenshots**
![screen shot 2018-09-21 at 19 15 42](https://user-images.githubusercontent.com/8895202/45899009-a2b01d00-bdd3-11e8-887e-8bbf9adc5b53.png)
![screen shot 2018-09-21 at 19 19 11](https://user-images.githubusercontent.com/8895202/45899010-a2b01d00-bdd3-11e8-946b-773974c1681a.png)
![screen shot 2018-09-21 at 19 20 43](https://user-images.githubusercontent.com/8895202/45899011-a2b01d00-bdd3-11e8-8f9f-fe3acf63d33c.png)
<img width="1283" alt="screen shot 2018-09-21 at 19 19 53" src="https://user-images.githubusercontent.com/8895202/45899012-a348b380-bdd3-11e8-9294-2a8c21844809.png">

**Desktop (please complete the following information):**
 - OS: iOS 10.13.5
 - Browser : Chrome
 - Version 69

**Additional context**
Gutenberg version 3.9

I was originally trying to save RichText value as a stringified JSON (well it actually works... it just makes other fields crash). 

`const handleMainDescriptionChange = (content) => {
			setAttributes({
				tdy_se_main_description: JSON.stringify(content)
			})
		}`

`     <RichText label="Text" help="Enter some text" value={ utils.tryParseJson(tdy_se_main_description) } placeholder="Primary description about the event..." onChange={ handleMainDescriptionChange } />`

I couldn't find how to save the value of a RichText and this seemed the best option (maybe not, if anyone would like to enlighten me :)). After banging my head all day, I tried saving a simple text that was JSON-like without stringifying anything. 

`const handleMainDescriptionChange = (content) => {
			setAttributes({
				tdy_se_main_description: content[0]
			})
		}`

`     <RichText label="Text" help="Enter some text" value={ tdy_se_main_description } placeholder="Primary description about the event..." onChange={ handleMainDescriptionChange } />`

(I know that content[0] isn't the right way to do it, and I'd only get the first line but I just wanted to test a simple string)

And voila, Error!

I hope I'm not just being silly, but if I am, I welcome anyone to show me what I'm doing wrong :).

**Comment by dongusta** [comment]
I would like to know the answer to this too. The same problem happens when saving the info you want into a JSON string (stringify) and updating `{ meta }` using dispatch. Other options result in a 500 (Internal Server Error)

**Comment by designsimply** [comment]
@kahenvay and @dongusta, I don't know the answer to your question as I mainly work in testing, however, I noticed that https://core.trac.wordpress.org/ticket/43392 is a discussion about how to save post_meta via Gutenberg using the REST API and it talks about a use case where they want to save JSON objects as meta data and I was wondering if the discussion there is relevant or helpful for your case at all?

**Comment by youknowriad** [comment]
Yes, this is more a Core issue, let's close in favor of this trac ticket.
