### ISSUE TITLE
Gutenberg 3.9: Uncaught TypeError: Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by mhair** [WordPress/gutenberg#10102]
**Describe the bug**

**To Reproduce**
1. Update plugin to Gutenberg 3.9
2. Refresh browser (Vanilla TwentySeventeen). No other plugins
3. See Error: Uncaught TypeError: Cannot read property 'uid' of undefined, line 69 of client-assets.php
4. Offending line: var userId = window.userSettings.uid;

**Expected behavior**
NOT to see that.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by mhair** [comment]
Correction to #2 above: Vanilla TwentySeventeen with child theme from Zac Gordon's course "Theming with Gutenberg", child theme is "2.2 Enqueuing CSS & JS"

**Comment by RolfBanziger** [comment]
I can confirm i have the same issue with Gutenberg v3.9.0. The JS error is caused by lib/client-assets.php, line 258ff. 
Changing line 264 to the following seems to fix this issue without any side effects.
				'	var userId = "";//window.userSettings.uid;',

**Comment by ryancwalsh** [comment]
I had this error just now until I upgraded my Gutenberg plugin to Version 4.2.0. Thanks.
