### ISSUE TITLE
Opened pre-3.9 post - Unexpected Error 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#10111]
**Describe the bug**
After upgrading to 3.9 I needed to edit an older post and got the Unexpected Error box. I copied the error:  (see below) 
I tried to "Copy Post" but there was nothing loaded in my clipboard
I used the "Attempt to Recover" all posts appeared except one WordPress embed. It would only show a paragraph block with the URL link. 

**To Reproduce**
I was not able to reproduce it. As I seems to have made additional changes to my workspace. I get a ton of Block Violation error message now, when [opening an older post](https://gutenbergtimes.com/update-86-gutenberg-blocks-themes-wordpress-site/) (Lots of embeds) 

http://recordit.co/02Nh6Eclvc

(never mind the first error message (only one bable-polyfill allowe) I already [created the issue](https://github.com/Yoast/wordpress-seo/issues/11078) for YoastSEO 

**Desktop (please complete the following information):**
 - OS: MAC 10.13.6
 - Browser firefox Developer
 - Version 63.0b6

**Additional context**
this.wp.editor</eu</<@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1537619774:50:290606
yh@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:96:396
lg@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
mg@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
gc@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
vb@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
ub@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
zd@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449
ra@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319
enqueueSetState@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231
q.prototype.setState@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:428
value/this.unsubscribe<@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:11035
r/</<@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:5846
r/<@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:5817
h@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:18725
e/<@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:6969
tryCatch@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:20850
invoke@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:22166
defineIteratorMethods/</t[n]@https://gutenbergtimes.com/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:21095
r@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:14756
c@https://gutenbergtimes.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1537619774:1:14958
F/</<@https://gutenbergtimes.com/wp-content/plugins/wordpress-seo/js/dist/commons-821.min.js?ver=8.2.1:6:66640
F/<@https://gutenbergtimes.com/wp-content/plugins/wordpress-seo/js/dist/commons-821.min.js?ver=8.2.1:6:66508
l@https://gutenbergtimes.com/wp-content/plugins/wordpress-seo/js/dist/commons-821.min.js?ver=8.2.1:6:26006

**Comment by bph** [comment]
Let me know if this is all related of if things need to be separate out into different issues. It was definitely wonky... 🤖👽

**Comment by designsimply** [comment]
I tried testing with the following steps:

1. Install Gutenberg 3.7.
1. Copy the content from https://gutenbergtimes.com/update-86-gutenberg-blocks-themes-wordpress-site/ into a draft using 3.7 and save the draft.
1. Upgrade to Gutenberg 3.9.
1. Open the post again for editing.

<strong>Result:</strong> the post opened normally in Gutenberg 3.9 in my test.

If you can think of better testing steps, let me know. My test may not have been the best because of how I copied the content straight from the web. Some of the embeds showed up as Custom HTML blocks when I did it that way and I am not sure why ([screenshot](https://user-images.githubusercontent.com/1119271/45976156-30be1a80-c003-11e8-94d3-5ddd8e7edcb2.png)). Maybe it would be better to include links for all of the embeds that a tester could use in a test post made with 3.7 or 3.8 and then check the post again after upgrading to 3.9?

I will leave the `Needs Testing` label for now to see if we can get some better ideas for steps to reproduce and also see if we can get some additional testing help.

**Comment by bph** [comment]
Hmm. I tried on the same blog, I tried on different sites, with different older pages and post. I was not able to reproduce it again. After upgrading to the next version, I watch for it. For now, I am closing this issues. @designsimply Thanks for the sanity check:-)

**Comment by designsimply** [comment]
Thank you for testing and for the follow-up! It's good to note error like this even if they go away because the are a good record and may become helpful in the future if the same problem comes up again. 🙂

**Comment by bph** [comment]
Experienced it today again. It was caused by a 3rd party block library plugin. I will connect with the plugin author.
