### ISSUE TITLE
Template block placeholders overlapping in 3.9 (input fields don't resize to placeholder text)

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#10119]
## Description
I've added a block template to an existing post type. The blocks, which I've filled in with placeholder text in the template,  overlap in the editor because the input fields don't resize.

The problem also appears when I use my [block-based portfolio plugin](https://github.com/wp-fangirl/block-portfolio) to create the template, and it didn't prior to Gutenberg 3.9.

## To Reproduce
1. Create a block template with placeholders--long ones, in the case of paragraphs. If you don't want to go through this whole process, you can install [Block-Basted Portfolio] (https://github.com/wp-fangirl/block-portfolio) or use [this code](https://gist.github.com/wpfangirl/b6f6921b22dc9daabb13496ab45c74ab) to add the template to an existing portfolio post type. (Not trying to plug my own stuff here, but I don't know of too many example block templates.)
2. Create a new entry for the post type that uses your block template
3. See error

## Expected behavior
When I first created the block template (in Gutenberg 3.8), the input fields for paragraphs expanded to fit the placeholder content, so none of the placeholder blocks overlapped.

### Before 3.9
![screenshot-1](https://user-images.githubusercontent.com/14795150/45926743-fc037380-bedb-11e8-9f6e-649940834800.png)
### After 3.9
![screenshot_2018-09-23 edit portfolio item block-based portfolio wordpress](https://user-images.githubusercontent.com/14795150/45926629-2e13d600-beda-11e8-9d27-31e35cea6689.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browsers: Firefox Developer Edition 63, Chrome 69, Microsoft Edge 42

## Smartphone (please complete the following information):
- Don't own one, so I can't check

**Additional context**
- Gutenberg 3.9.0

**Comment by youknowriad** [comment]
I just tried the exact same template above and the issue seems fixed to me. Thanks.
