### ISSUE TITLE
Quote not displaying right

### ISSUE THREAD

**Issue by Clothesandfors** [WordPress/gutenberg#10112]
Quote is not displaying how it should. Can't see quotation marks and it also blocks part of actual quote.  Please fix or help. 
<img width="753" alt="screen shot 2018-09-22 at 1 14 11 pm" src="https://user-images.githubusercontent.com/43502446/45920423-78a93a00-be69-11e8-835c-5a9ae28f146d.png">
<img width="730" alt="screen shot 2018-09-22 at 1 14 05 pm" src="https://user-images.githubusercontent.com/43502446/45920425-7e9f1b00-be69-11e8-9b5d-1f1c8cdbccd1.png">

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Add a block quote and select the "Large" block style.
1. Publish the post and view it on the front end.

<strong>Result:</strong> quotes worked normally and looked good both in the editor and on the front end when I viewed the published post.

I tested with the Twenty Seventeen theme using WordPress 4.9.8 and Gutenberg 3.9.0 using Firefox 62.0 on macOS 10.13.6.

![screen shot 2018-09-24 at 2 15 26 pm](https://user-images.githubusercontent.com/1119271/45976708-bf7f6700-c004-11e8-8e95-e97da071400f.png)

![screen shot 2018-09-24 at 2 15 29 pm](https://user-images.githubusercontent.com/1119271/45976715-c3ab8480-c004-11e8-8fd9-60b802b59464.png)

The problem may be specific to your theme. May I ask what theme you are using or if you are able to provide a link to a post or page showing the problem in action?
