### ISSUE TITLE
is-video class in the editor, is-type-video class in front-end

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#10121]
**Describe the bug**
When using Youtube block I see `is-video` class in the editor, `is-type-video` class in front-end.

**Expected behavior**
Should both classes be `is-type-video` so that styling can be done with the same class in the editor and in the front-end? Or what is the reason for different classes?

**Comment by chrisvanpatten** [comment]
This definitely strikes me as a bug, but it could also be that changing the class in the editor would have triggered an error, so perhaps it wasn't changed for that reason? Flagging for feedback!

**Comment by mcsf** [comment]
From what I could track down, `is-video` was added in #1554, and then consistent `is-type-` classes in #4118. I guess they happened without mutual knowledge…?

Anyway, this is worth fixing, probably by extending the editor classes with `is-type-*` and deprecating `is-video`.

**Comment by nfmohit-wpmudev** [comment]
Submitted a PR addressing this issue in #10411
