### ISSUE TITLE
Blank page when editing page - problem with Yoast ?

### ISSUE THREAD

**Issue by oliviercay** [WordPress/gutenberg#10124]
**Describe the bug**
I can edit a page from the admin page list. But when I am on this page and try to edit it (click on the edit button) I got a blank page.

**To Reproduce**
1. Update plugin from 3.6.1 to Gutenberg 3.9
2. Click on the edit button 
3. The page got blank
TypeError: wp.api.models.Page is not a constructor
/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:110
    at wp-seo-replacevar-plugin-821.min.js?ver=8.2.1:1
    at index.js?ver=1537625906:1
    at Array.forEach (<anonymous>)
    at index.js?ver=1537625906:1
    at h (index.js?ver=1537625906:1)
    at lodash.min.59550321.js:49
    at index.js?ver=1537625906:50
    at index.js?ver=1537625906:12
    at dispatch (index.js?ver=1537625906:50)
    at Array.map (<anonymous>)
bg @ react-dom.min.82e21c65.js:110

Uncaught (in promise) TypeError: wp.api.models.Page is not a constructor
/wp-content/plugins/wordpress-seo/js/dist/wp-seo-replacevar-plugin-821.min.js?ver=8.2.1:1
    at wp-seo-replacevar-plugin-821.min.js?ver=8.2.1:1
    at index.js?ver=1537625906:1
    at Array.forEach (<anonymous>)
    at index.js?ver=1537625906:1
    at h (index.js?ver=1537625906:1)
    at lodash.min.59550321.js:49
    at index.js?ver=1537625906:50
    at index.js?ver=1537625906:12
    at dispatch (index.js?ver=1537625906:50)
    at Array.map (<anonymous>)

**Expected behavior**
Edit the page

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 
 - Browser : Chrome

**Comment by designsimply** [comment]
I will test this. May I ask what makes you think it may be a problem with Yoast?

**Comment by designsimply** [comment]
Nevermind 🙂 that was a dumb question as I missed the 2nd error somehow. Sorry about that!

> Uncaught (in promise) TypeError: wp.api.models.Page is not a constructor
/wp-content/plugins/wordpress-seo/js/dist/wp-seo-replacevar-plugin-821.min.js?ver=8.2.1:1

I tested using WordPress 4.9.8 and Gutenberg 3.9.0 and Yoast 8.2.1 and by going to WP Admin > Posts and hovering over a title and clicking the "Edit" link that appeared below it and I didn't see a blank page or the `wp.api.models.Page is not a constructor` error in the console.

Do my testing steps above sound correct?

Is there any content specific to your page that you think I could try adding in a test to try to trigger the problem? For example, one problem in the past was a conflict with categories and the editor would go blank but only if the categories panel was opened.

Do you have any additional plugins installed that you think could be causing interference? Could you list your active plugins?

Just to make sure it has been tried, can you clear your local browser cache as a basic troubleshooting step if you haven't already? It may not help in this case, but might be worth a try.

Since this could turn out to be an issue with a third-party plugin (Yoast), I will note that I may recommend reporting it in their GitHub issues. I tried searching for "Uncaught (in promise) TypeError: wp.api.models.Page is not a constructor " at https://github.com/Yoast/wordpress-seo/issues?utf8=%E2%9C%93&q=Uncaught+%28in+promise%29+TypeError%3A+wp.api.models.Page+is+not+a+constructor just now and didn't find that it was already reported. I also know that 8.3 should be coming out very soon, and if you wanted to try testing the latest release candidate for Yoast SEO you can get 8.3-RC2 at https://github.com/Yoast/wordpress-seo/releases

**Comment by designsimply** [comment]
Are you using WordPress multisite?

**Comment by lkraav** [comment]
3.9.0: I'm seeing the same JS error intermittently white screen of death on me. Reload has been successful every single time. Seems like some kind of a race condition.

**Comment by oliviercay** [comment]
Sorry for the late answer.

I am using now Yoast SEO 8.3 and there is no problem anymore.

**Comment by lkraav** [comment]
> I am using now Yoast SEO 8.3 and there is no problem anymore.

I'm also on Yoast SEO (Premium) 8.3, and I still get occasional WSOD.

**Comment by lkraav** [comment]
@Clorith not looking much "fixed" to me. WSOD happening on every other editor load, see below:

```
16:55:40.587 Unhandled promise rejection TypeError: "wp.api.models.Page is not a constructor"
	subscribeToGutenberg /wp-content/plugins/wordpress-seo-premium/js/dist/wp-seo-replacevar-plugin-830.min.js?ver=8.3:1:10511
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5846
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5817
	h /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:18725
	Hr /wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:49:109
	default /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:18569
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30835
	dispatch /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:68756
	default /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:18562
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30835
	dispatch /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:68756
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30883
	actions /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:7821
	value /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:11877
	t /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:288804
	yh /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:97:111
	lg /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
	mg /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
	gc /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
	vb /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
	ub /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
	zd /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449
	ra /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319
	enqueueSetState /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231
	setState /wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:428
	unsubscribe /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:11035
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5846
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5817
	h /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:18725
	e /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:6969
	tryCatch /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:20850
	invoke /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:22166
	n /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:21095
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:14756
	c /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:14958
	j /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29352
	j /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29220
	f /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:1:20743
 wp-polyfill-ecmascript.min.2ae96136.js:2:29718

16:55:40.521 TypeError: "wp.api.models.Page is not a constructor"
	subscribeToGutenberg /wp-content/plugins/wordpress-seo-premium/js/dist/wp-seo-replacevar-plugin-830.min.js?ver=8.3:1:10511
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5846
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5817
	h /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:18725
	Hr /wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:49:109
	default /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:18569
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30835
	dispatch /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:68756
	default /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:18562
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30835
	dispatch /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:68756
	exports /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:12:30883
	actions /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:7821
	value /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:11877
	t /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537593544:50:288804
	yh /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:97:111
	lg /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
	mg /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
	gc /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
	vb /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
	ub /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
	zd /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449
	ra /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319
	enqueueSetState /wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231
	setState /wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:428
	unsubscribe /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:11035
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5846
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:5817
	h /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:18725
	e /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:6969
	tryCatch /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:20850
	invoke /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:22166
	n /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:3:21095
	r /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:14756
	c /wp-content/plugins/gutenberg/build/data/index.js?ver=1537593544:1:14958
	j /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29352
	j /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29220
	f /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js:1:20743
 react-dom.min.82e21c65.js:110:57
```

**Comment by lkraav** [comment]
@oliviercay mind re-opening this issue for time being? Some diagnosis work is already been done, so doesn't make much sense to repeat it in another issue.

**Comment by oliviercay** [comment]
ok

**Comment by swissspidy** [comment]
Is this still happening with Yoast SEO 9.0?

**Comment by lkraav** [comment]
> Is this still happening with Yoast SEO 9.0?

I will have more insight on this by tomorrow.

**Comment by lkraav** [comment]
@swissspidy still happens on 9.0.2, here's the sentry event traceback:

https://sentry.io/share/issue/88054e26f70840e5bb339ccce66544e7/

**Comment by swissspidy** [comment]
@lkraav That link 404s for me unfortunately 😕

**Comment by lkraav** [comment]
@swissspidy oops maybe due to merging some of the duplicate events there.

https://sentry.io/share/issue/8dfb7deed9b9435a9bd31dc52ffe5cc7/ should work now.

**Comment by lkraav** [comment]
@swissspidy I'm still getting this all the time w/ 4.2 + 9.1.

It seems to be some kind of a race condition or a caching thing somewhere. It can whitescreen 10 reloads in a row, then complete loading the editor on 11th try.

Majority of the samples, reload no 2 has managed to complete editor load. Yet, not always. Confusing as hell.

**Comment by designsimply** [comment]
I have been testing on and off with WordPress 4.9.8 Gutenberg 4.5.1 and Yoast SEO 9.2.1 using Firefox 63.0.3 on macOS 10.13.6 and haven't ever run into the problem where I see a whitescreen intermittently. 

@lkraav have any other plugins in the mix which could be potentially problematic?

I know we've been asking you to re-test a few times already, but is there any chance this is solved for you with the latest versions (currently Gutenberg 4.5.1 and Yoast SEO 9.2.1)? (Checking just in case!)

**Comment by lkraav** [comment]
I'm super crammed w/ some stuff, but if someone could point out a PHP / JS breakpoint line no I could set the debugger to, that would help.

**Comment by mondrey** [comment]
@lkraav 

I'm getting the blank page with the same errors in console when editing any page which has been assigned with a parent page.

Editing any page with a parent page assigned gives a blank page.
Reloading displays it correctly without errors.

WordPress version: 5.0 RC3-43967
Yoast SEO version: 9.2.1
Theme: Twenty Seventeen Version: 1.8

No other plugins active.

**Comment by lkraav** [comment]
That's a great finding. I also edit a lot of child pages, of which some have Private parents, with the help of https://github.com/sillybean/inclusive-parents

**Comment by designsimply** [comment]
@lkraav I found this issue filed at `wordpress-seo` as well and tested and left notes at https://github.com/Yoast/wordpress-seo/issues/11767#issuecomment-444962733

**Comment by designsimply** [comment]
I am going to close this issue in favor of https://github.com/Yoast/wordpress-seo/issues/11767 since the error is only happening with the Yoast SEO plugin and the error reported above ( https://sentry.io/share/issue/8dfb7deed9b9435a9bd31dc52ffe5cc7/ ) also references code from that plugin.

> I'll keep an eye out for this pattern and report back soon.

Would you mind reporting any new findings at https://github.com/Yoast/wordpress-seo/issues/11767 ?

**Comment by alexbricepalo** [comment]
Still happening with yoast 14.3 and wordpress 5.4.2

**Comment by lkraav** [comment]
We OTOH haven't seen this problem occur for a long time.

**Comment by Shubalto13** [comment]
Happening on 14.4.1 with WordPress 5.4.1

**Comment by swissspidy** [comment]
@Shubalto13 Issues with my.yoast.com should be reported to Yoast support

**Comment by sKopheK** [comment]
hi, happened to me as well out of blue after a common update of a post. getting blank page when editing for most of my posts.
WordPress 5.8.1
Yoast 17.4

**Comment by swissspidy** [comment]
Reach out to Yoast SEO support please.
