### ISSUE TITLE
Blank screen on Multisites (After version 3.7.0

### ISSUE THREAD

**Issue by meepingblog** [WordPress/gutenberg#10132]
After version 3.7.0, the new Gutenberg screen shows up blank. This is present in updates 3.8.0-3.9.0. Reverting to version 3.7.0 resolves the issue. Wordpress is the latest stable release.

**Comment by meepingblog** [comment]
I'm using a bunch of plugins from iThemes Security to Code Snippets to Media Cloud, etc. However, I made a test site with all of the plugins I have installed with the exception of activating Askimet and Yoast (latest version) and I can safely say the blank screen disappears and I'm able to use Gutenberg again.

**Comment by meepingblog** [comment]
Activating Yoast doesn't give me the blank screen either. The only thing I can think of is that it is happening in the main domain as this is a subdomain of the main domain (also the subdomain is not using SSL)

**Comment by designsimply** [comment]
Would you be able to check the console panel in your browser's web developer tools to see if any error show up there at the time you see the blank screen? 

Also, on the main site, if you temporarily deactivate iThemes Security then clear browser cache while leaving all other plugins the same, does the problem still occur?

**Comment by meepingblog** [comment]
Console panel reveals quite a few errors

`post-new.php:161 Uncaught TypeError: Cannot read property 'setCategories' of undefined
    at post-new.php:161
(anonymous) @ post-new.php:161
index.js:12 Uncaught TypeError: Cannot read property 'normalizeIconObject' of undefined
    at index.js:12
    at index.js:12
    at lodash.min.59550321.js:46
    at mt (lodash.min.59550321.js:27)
    at An.forOwn (lodash.min.59550321.js:112)
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:12
(anonymous) @ index.js:12
(anonymous) @ lodash.min.59550321.js:46
mt @ lodash.min.59550321.js:27
An.forOwn @ lodash.min.59550321.js:112
(anonymous) @ index.js:12
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
index.js:12 Uncaught TypeError: Object(...) is not a function
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
(anonymous) @ index.js:12
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
wp-seo-structured-data-blocks-821.min.js:1 Uncaught TypeError: Cannot read property 'Content' of undefined
    at Object.1434 (wp-seo-structured-data-blocks-821.min.js:1)
    at e (commons-821.min.js:1)
    at Object.1433 (wp-seo-structured-data-blocks-821.min.js:1)
    at e (commons-821.min.js:1)
    at Object.1432 (wp-seo-structured-data-blocks-821.min.js:1)
    at e (commons-821.min.js:1)
    at Object.1431 (wp-seo-structured-data-blocks-821.min.js:1)
    at e (commons-821.min.js:1)
    at window.yoastWebpackJsonp (commons-821.min.js:1)
    at wp-seo-structured-data-blocks-821.min.js:1
1434 @ wp-seo-structured-data-blocks-821.min.js:1
e @ commons-821.min.js:1
1433 @ wp-seo-structured-data-blocks-821.min.js:1
e @ commons-821.min.js:1
1432 @ wp-seo-structured-data-blocks-821.min.js:1
e @ commons-821.min.js:1
1431 @ wp-seo-structured-data-blocks-821.min.js:1
e @ commons-821.min.js:1
window.yoastWebpackJsonp @ commons-821.min.js:1
(anonymous) @ wp-seo-structured-data-blocks-821.min.js:1
index.js:12 Uncaught TypeError: Cannot read property 'serialize' of undefined
    at index.js:12
    at d (index.js:12)
    at Pt (index.js:12)
    at Object.getEditedPostAttribute (index.js:1)
    at e.value (wp-seo-post-scraper-821.min.js:1)
    at e.value (wp-seo-post-scraper-821.min.js:1)
    at e.value (wp-seo-post-scraper-821.min.js:1)
    at e.value (wp-seo-post-scraper-821.min.js:1)
    at t.value (wp-seo-post-scraper-821.min.js:1)
    at t.value (wp-seo-post-scraper-821.min.js:1)
(anonymous) @ index.js:12
d @ index.js:12
Pt @ index.js:12
(anonymous) @ index.js:1
value @ wp-seo-post-scraper-821.min.js:1
value @ wp-seo-post-scraper-821.min.js:1
value @ wp-seo-post-scraper-821.min.js:1
value @ wp-seo-post-scraper-821.min.js:1
value @ wp-seo-post-scraper-821.min.js:1
value @ wp-seo-post-scraper-821.min.js:1
t @ wp-seo-post-scraper-821.min.js:1
C @ wp-seo-post-scraper-821.min.js:1
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.8:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.8:2
ready @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.8:2
K @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.8:2
index.js:12 Uncaught TypeError: Cannot read property 'registerCoreBlocks' of undefined
    at Object.Fn (index.js:12)
    at HTMLDocument.<anonymous> (post-new.php:2149)
Fn @ index.js:12
(anonymous) @ post-new.php:2149`

**Comment by designsimply** [comment]
Thanks for checking that. I know there was a past conflict related to the categories panel and Yoast. Can you confirm that you have updated to the latest version for all of your installed plugins? And more specifically, which version of Yoast SEO are you currently running?

**Comment by meepingblog** [comment]
Disabling iThemes Security does not fix the issue.
I can confirm everything is updated and I am running Version: 8.2.1. Activating Yoast on the non-ssl test site (along with all the plugins) seems to be free of the blank screen issue?

**Comment by designsimply** [comment]
And the non-ssl test site also multisite and it's in a subfolder on the same domain?

I am not sure why the conflict would trigger on one site and not another! Maybe it has to do with the content, or a different plugin conflict—are both sites running the exact same versions of all plugins? Any chance  you're able to test 8.3-RC2 on your main site? Or is that something you don't want to do for a production site?

**Comment by meepingblog** [comment]
The non-ssl subdomain site is running on the same domain as a subsite of the main one. The error doesn't seem to be triggered despite running the exact same plugins. I'm willing to test the 8.3-RC2 plugin on my production site. Where do I grab it from?

**Comment by meepingblog** [comment]
Disabling all the plugins makes the issue disappear on the main site. I have 22 plugins so I guess I'll start testing each one.

**Comment by meepingblog** [comment]
The culprit is code snippets. Disabling it makes the blank screen go away (with or without Yoast) and disabling individual snippets doesn't fix the issue either.

**Comment by designsimply** [comment]
Great sleuthing! To confirm, https://wordpress.org/plugins/code-snippets/ is the plugin you're having trouble with? I noticed it was updated to version 2.12.0 2 days ago. Do you happen to know if you had updated to the latest version when you were seeing the problem happening on the SSL site?

I installed Code Snippets 2.12.0 on my test site and I was still able to publish Gutenberg posts normally. Do you think the problem is with the plugin itself or do you think the problem could be with specific snippets being used?

**Comment by designsimply** [comment]
Wait! I didn't test with multisite but I can do that to help confirm. Might take me a bit of time to set that up though. The end goal will be to test, confirm, and report the issue to the plugin developers once we can get good steps to reproduce nailed down.

**Comment by meepingblog** [comment]
I am running version Version 2.12.0  and I can confirm this doesn't happen on a normal install. It happens on a multi-site installation, in my case on the main domain which uses the HTTPS protocol. If I test it on the subsite (same installation) that uses the HTTP protocol, the issue is absent.

**Comment by madcoffee** [comment]
My WP (v 4.9.8) also is on Multisite and I tried testing the demo but I just get a blank.

Console Error shows:
```
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,underscore,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-cor&load[]=e,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:9 JQMIGRATE: Migrate is installed, version 1.4.1
wp-polyfill-ecmascript.min.2ae96136.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js?ver=1539011850:50 Uncaught ReferenceError: regeneratorRuntime is not defined
    at index.js?ver=1539011850:50
    at Object.<anonymous> (index.js?ver=1539011850:50)
    at n (index.js?ver=1539011850:1)
    at index.js?ver=1539011850:1
    at index.js?ver=1539011850:1
index.js?ver=1539011850:12 Uncaught TypeError: Object(...) is not a function
    at Object.216 (index.js?ver=1539011850:12)
    at n (index.js?ver=1539011850:1)
    at wp.blockLibrary.0 (index.js?ver=1539011850:1)
    at index.js?ver=1539011850:1
index.js?ver=1539011850:12 Uncaught TypeError: Cannot read property 'getBlockSelectionStart' of undefined
    at index.js?ver=1539011850:12
    at Ge (index.js?ver=1539011850:12)
    at Array.INIT (index.js?ver=1539011850:12)
    at Object.dispatch (index.js?ver=1539011850:1)
    at Object.217 (index.js?ver=1539011850:12)
    at n (index.js?ver=1539011850:1)
    at wp.editPost.0 (index.js?ver=1539011850:1)
    at index.js?ver=1539011850:1
post-new.php?gutenberg-demo:2367 Uncaught TypeError: Cannot read property 'initializeEditor' of undefined
    at HTMLDocument.<anonymous> (post-new.php?gutenberg-demo:2367)

```
Active Plugins:

- Akismet Anti-Spam
- Cookie Notice
- Jetpack by WordPress.com
- WooCommerce
- Gutenberg
