### ISSUE TITLE
Some images don't load in Gutenburg

### ISSUE THREAD

**Issue by TheAutoReporter** [WordPress/gutenberg#10144]
**Describe the bug**
4/6 of my photos do not show up on the reader side of my website: 
https://www.theautoreporter.com/alfa-romeo-stelvio-crowned-run-to-the-sun-winner/ 

**To Reproduce**
1. Go to https://www.theautoreporter.com/alfa-romeo-stelvio-crowned-run-to-the-sun-winner/
2. Scroll through site to see lack of pictures in some areas. Can see the pinterest link, but not the image. 

**Expected behavior**
I expect to see my images (as I see them clear as day on the backend/editor side). 

**Desktop (please complete the following information):**
PC on chrome and Edge, 

**Smartphone (please complete the following information):**
samsung phone on chrome and edge.

**Comment by TheAutoReporter** [comment]
Down to 2/6 images that don't load. :/

**Comment by Soean** [comment]
I don't see any problems. Maybe you have a cache or internet connection problem?

**Comment by TheAutoReporter** [comment]
It's good to know that others can see all the images. I've had some readers email me that they cannot see images. For me (in two browsers) I still cannot see the image for the Mustang Bullitt (Coupe heading) - see image. 

![images](https://user-images.githubusercontent.com/43553512/45978725-dd979800-c001-11e8-87da-57d1eb0333a9.jpg)

I'll work on my cache to see if there's something I can do from that end. I don't think its internet problems, as I've tried this from multiple browsers on multiple devices and using work wifi and cellphone network (no wifi).

**Comment by TheAutoReporter** [comment]
Down to 1 of 6 that don't load! :/ Still don't really know why what I've fiddled with works only sometimes (reinserting photo blocks...).

**Comment by TheAutoReporter** [comment]
Purged my cache, and went back to 2 images not loading. The one circled in the image above and another that section that has a left-justified image in the first content section. :(

**Comment by Soean** [comment]
You are hosting your images on a CDN, maybe they have problems? I don't think its Gutenberg specific.

**Comment by TheAutoReporter** [comment]
No CDN. :/

**Comment by TheAutoReporter** [comment]
Ah, gotcha. :) I'm not IT (but editorial in charge of all), so I didn't realize that i was hosting images on wp.com's CDN instead of my own hosting platform. :/ I'll have to go fix that. :) Any advice on how to rectify this would be greatly appreciated! 

Thanks for the help!

**Comment by designsimply** [comment]
I tested https://www.theautoreporter.com/alfa-romeo-stelvio-crowned-run-to-the-sun-winner/ and can confirm that I can see images loading there.

![screen shot 2018-09-24 at 4 31 54 pm](https://user-images.githubusercontent.com/1119271/45982806-7b499200-c017-11e8-881d-9c8aa768fc8b.png)

I right-clicked on the image in the screenshot and selected the "Open Image in New Tab" option and this is the url: https://www.theautoreporter.com/wp-content/uploads/2018/09/2018_Run-to-the-Sun_Alfa-Romeo-Stelvio-Quadrifoglio_196.jpg

I can see that image is being served on your site and is working for me. Are you still having trouble? I am going to close this issue as it appears to be unrelated to Gutenberg but we can still continue the conversation if needed.
