### ISSUE TITLE
"Classic" block name doesn't make a lot of sense

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#10159]
The name "Classic" only makes sense to someone that has been using WordPress for a number of years and they're accustomed to the current editor.
However, for new users the name "classic" doesn't mean anything.
If I install WordPress in 2020 and I'm new to WP, then Gutenberg is "classic" for me.
It would make a lot more sense to call the block something like "Rich Text" or something else... The name "classic" is relevant to one's experiences and also has a time factor attached. A song released in 1980 is a classic now, but I doubt they'd call it a "classic" in 1980. And it certainly is not a classic to someone that listens to it for the 1st time.

**Comment by pento** [comment]
Thank you for the feedback, @aristath!

The Classic Block is really only intended to be used by folks who are familiar with the classic editor, or are loading posts that were created in the classic editor.

Like you said, it won't really be a relevant name to people installing WordPress in 2020, and I hope it will have been long deprecated by then. For now, however, it's important that the many millions of WordPress sites have access to it, allowing them to continue using the classic editing experience that they're familiar with.

**Comment by aristath** [comment]
The thing is that the "classic" block is more than just a fallback...
Gutenberg blocks are a nice concept when creating a page, but they become really, **really** annoying when writing a long blog post, editing text etc.
Take for example cut-pasting 2½ paragraphs. It's doable in the classic editor, but impossible when using blocks. When I want to write a blog post I have to either write my post initially in a plain text editor outside of WordPress, edit and finalize it there and move to Gutenberg only after it's finished, OR I have to use the classic block and convert to blocks once finished editing.
There's lots of things that are easier to do in a plain text editor than in blocks, so I think that the classic block is an inevitable necessity for some workflows. If it gets deprecated we'll just have to install a 3rd-party block just to be able to efficiently write blog posts... and that's definitely not "democratizing publishing".
