### ISSUE TITLE
Inserted Galleries gets broken

### ISSUE THREAD

**Issue by tecnogaming** [WordPress/gutenberg#10167]
Inserting a gallery,  saving the post without posting and later editing the post on another PC turns all galleries into "unrecognized blocks".

Gutenberg ask to convert to HTML (Which if selected turns the block into broken with an error) or convert to block who then turns the gallery into nothing, with "UL dots in it".

This is so easily reproducible that I'm shocked that this pass as a beta test.   There is no way that I can later "edit" an article created by one of my readers as galleries GETS BROKEN after I try to edit the article. This should not be happening.

**Comment by tecnogaming** [comment]
This is happening,  ALL THE TIME.  Can somebody please DO something?.  I happily will give access to my site so you can take a look at what is happening.

![screenshot_2018-09-27_20-02-21](https://user-images.githubusercontent.com/6232299/46179169-662b6800-c290-11e8-9442-6ab630084a0c.jpg)

**Comment by tecnogaming** [comment]
I am forced to redo each gallery on my posts as all posts written by someone else that I edit end up with this broken galleries.  Gutenberg is completely unusable if I need to endure this all the time.

**Comment by mizzxtc** [comment]
Has this been figured out yet? I don't want to have to re-do every single post in gutenberg- I don't want to have to re-do every single post period!!!!

**Comment by youknowriad** [comment]
I can't reproduce this issue. If it's still a problem for you, please share the HTML content of your post, this will help us debug it.

**Comment by mizzxtc** [comment]
Are you kidding me?A freeking YEAR later!!! HAHAHAHA

**Comment by youknowriad** [comment]
If you think you can help us get quicker with issue triage, we'd appreciate the help. WordPress is an open-source and any help would be valuable.

**Comment by mizzxtc** [comment]
HonestlyIf I could remember I’d help bu a year later theres not a chance of that!  I settled it by shutting off Gutenberg and getting a new website designed!
