### ISSUE TITLE
Debounce RangeControl when used with SSR

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#10168]
If you hold down the slider on a `RangeControl` and move your mouse, it will kick off dozens of HTTP requests to re-render the block preview.

That should be debounced to avoid unnecessary requests and the visually jarring refreshes.

**To Reproduce**

1. Insert an SSR block like Latest Posts or Latest Comments
2. Click on the Number of Posts slider, hold the button down
3. Move your mouse side to side

**Expected behavior**

The change handler should only be triggered once the user has stopped moving their mouse, or a certain number of milliseconds has passed since the previous trigger.

Gutenberg 3.9.0
Firefox 63

**Comment by aduth** [comment]
While this specific use-case was not mentioned, I think it's best to consolidate this under the umbrella of #7320.
