### ISSUE TITLE
Make All Components Package Elements Consistenly Filterable

### ISSUE THREAD

**Issue by mikeselander** [WordPress/gutenberg#10177]
### Is your feature request related to a problem? Please describe.
Certain Components and features within Gutenberg are exported as filterable objects, but the list of filterable elements is very small and largely unusable for customizing functionality.

In WordPress core, more often than not, any serious customization will run into functionality that _should_ have been filtered but no one thought to add it at the time. This is the cause of piles of hackarounds on client sites and codebases. We should avoid this in Gutenberg and use filters in a reliable and consistent manner across the codebase.

**_Real world example:_**
I have a client requirement to prevent all users within Gutenberg from uploading new media files in the editor in order to integrate a 3rd-party DAM. I have found that `MediaUpload` (oddly named for what it actually does, as an aside) is filterable, but neither `FormFileUpload`, `Dropzone`, nor `MediaPlaceholder` are filterable. This means that I can remove the one element that I need to keep and cannot touch the elements that I need to modify the behavior of.

As far as I can tell, this leaves me with duplicating and adjusting the edit view of each of the file-related blocks which is frankly quite a horrible idea and un-maintainable. 

### Describe the solution you'd like
I propose that all elements in the Components package be exported `withFilters` to make them reliably over-writable. This sets a clear expectation and a level of consistency that all components are modifiable at the same level and that a plugin or theme can hook in and make changes that are needed.

If this proposal is agreeable and it would move it forward faster, I am happy to write a Pull Request that does just that.

**Comment by joemcgill** [comment]
https://wordpress.slack.com/archives/C02QB2JS7/p1537970273000200

**Comment by joemcgill** [comment]
It looks like there was [some conversation about this](https://wordpress.slack.com/archives/C02QB2JS7/p1537970273000200) in Slack, which seemed to indicate that @mtias and @youknowriad had concerns with making UI filterable from the outset, which I sympathize with.

However, as a developer who is often tasked with customizing the editing experience for clients, it's not currently clear to me how I should be approaching these types of issues when they arise without a consistent API for modifying/extending components used in the editor. What is the suggested method?

**Comment by kadamwhite** [comment]
Thank you for the input. I'm curious what your thoughts would be about specifically adding a filter for the three elements mentioned in the PR description (the placeholder, dropzone, and file uploader) with the intention of addressing the immediate extensibility roadblock we're repeatedly encountering. This would be a smaller and more contained PR which would impact fewer elements, and we'd still like to try to solve this problem for initial release if possible. If we're past a cutoff on making that sort of changes I understand, but I'd like to keep moving forward on this if possible :)

**Comment by gziolo** [comment]
> Thank you for the input. I'm curious what your thoughts would be about specifically adding a filter for the three elements mentioned in the PR description (the placeholder, dropzone, and file uploader) with the intention of addressing the immediate extensibility roadblock we're repeatedly encountering.

Yes, this is a good compromise. As explained earlier, let's make sure that those filters aren't included inside `@wordpress/components` package. Instead, let's follow the previously used approach for media related components and wrap them with filters and expose from `@wordpress/editor`:
- `<MediaUpload />` -  https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/media-upload
- `<PostFeaturedImage />` - https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/post-featured-image

We are preparing for 4.1 release this week which is UI freeze focused. 4.2 is going to be focused on API freeze, so let's make sure it's ready early next week if we want to have it included.
