### ISSUE TITLE
"Most used" Tags cloud-list is missing in Gutenberg

### ISSUE THREAD

**Issue by Xoliul** [WordPress/gutenberg#10176]
I really liked the Tag list of "most used Tags" in the classic editor. I have a hard time remembering what tags are used, and we all know using the same tags often makes the most sense

It would be nice to just get something similar to what we had before: a list or overview of often used tags with more than one or two usages.

**Comment by designsimply** [comment]
Thank you for the feedback! This has been requested at https://github.com/WordPress/gutenberg/issues/8867 and so I'll close this issue in favor of that one.
