### ISSUE TITLE
How to add image using Richtext content?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#10187]
Here is screenshot -https://goo.gl/rvx4Jw

![2018-09-26_14-37-24](https://user-images.githubusercontent.com/1119271/46099538-013f1780-c195-11e8-9d50-b6f3319899a7.png)

Can we add media inserter option for rich text element?

**Comment by designsimply** [comment]
Is there something more specific that you are missing compared to clicking the block inserter and then clicking on the media you'd like to add such as "Image" or "Gallery"?

**Comment by prajaktagadhave** [comment]
I am using the Richtext for text block which created custom. I just want a image control for rich text like Bold, italic, link etc..

Is it possible to add image control through which we can insert image to a selected block of rich text?

**Comment by mcsf** [comment]
RichText elements support inline images. See the top-level block inserter as shown in the screenshots below:

<img width="798" alt="screenshot 2018-11-26 at 15 20 23" src="https://user-images.githubusercontent.com/150562/49023360-f7369680-f18e-11e8-8557-864df525a3f5.png">
<img width="750" alt="screenshot 2018-11-26 at 15 20 36" src="https://user-images.githubusercontent.com/150562/49023363-f7cf2d00-f18e-11e8-9ba7-545e5048e969.png">
