### ISSUE TITLE
Clicking enter when non-textual blocks are selected creates a new paragraph even if not allowed.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#10186]
Related https://github.com/WordPress/gutenberg/pull/10136#pullrequestreview-158137812

Create a container block where the paragraph block is not allowed 

```js
wp.blocks.registerBlockType('test/container', {
	title: 'container',
	category: 'common',
	description: 'container',
	icon: 'yes',

	edit() {
		return wp.element.createElement(wp.editor.InnerBlocks, {
			allowedBlocks: ['core/image', 'core/gallery']
		});
	},

	save() {
		return wp.element.createElement(wp.editor.InnerBlocks.Content);
	},
})
``` 

 - Add an image block inside this container
 - Select the image placeholder and hit enter
 - A new paragraph block is inserted even if not allowed

**Comment by aduth** [comment]
Related: #7301, #7265
