### ISSUE TITLE
Post never appears as set to publish "immediately"

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#10182]
**Describe the bug**
A post is never set to be published "immediately" because `select( 'core/editor' ).getEditedPostAttribute( 'date' )` always returns a truthy value.

**To Reproduce**
1. Open a new post ("Add New")
2. Ensure the sidebar is open
3. Note the "Publish" date is expanded, even though the publishing date is now/in the past

**Expected behavior**
It reads "Publish: Immediately". The code for this component provides that option, but its condition is never met: https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-schedule/label.js#L12

**Screenshots**
![2018-09-26 02 06 20](https://user-images.githubusercontent.com/90871/46051348-dcb15400-c130-11e8-823c-e460143b6ab3.gif)

**Comment by nosolosw** [comment]
@tofumatt I've consolidated https://github.com/WordPress/gutenberg/issues/9030 in https://github.com/WordPress/gutenberg/issues/10930 Do you still the patch you mentioned available? I can take a look at this if your hands are full.

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/11013 fixes https://github.com/WordPress/gutenberg/issues/10930 and https://github.com/WordPress/gutenberg/issues/9030

This issue is no longer happenning, so I'm closing it.
