### ISSUE TITLE
On multilang sites, when adding an internal link and search for other posts on link box, only posts from main language appear

### ISSUE THREAD

**Issue by danielbento** [WordPress/gutenberg#10199]
**Describe the bug**
While using Gutenberg with Multilang plugin WPML, when including a link to some text or image and search for other posts on the same language to link, the only options that appear are the posts/pages on the main language of site, not on the same language. 

**To Reproduce**
1. Go to a post in a multilang site and add an internal link to any post or page on both languages
2. Write a post name and wait for search results
3. See error
Only results from the main language appear

**Expected behavior**
You should see only post from the current language

**Comment by youknowriad** [comment]
Thanks for the report.

It looks like WPML is not compatible with Gutenberg at the moment, I suggest reaching out to the plugin authors to see if they have any plans to add compatibility and if they have trouble with it, we'd be happy to help.

**Comment by youknowriad** [comment]
It looks like WPML released an update with Full Gutenberg support. Let them know if you're still experiencing issues. Thanks.
