### ISSUE TITLE
Adding theme support for editor styles without enqueuing a style causes display issues

### ISSUE THREAD

**Issue by davidwolfpaw** [WordPress/gutenberg#10193]
**Describe the bug**
To be clear, I know that I'm `doing_it_wrong()` by using `add_theme_support( 'editor-styles' );` without enqueuing an editor stylesheet. However I see it as a possibility that this could happen on a site using Gutenberg, and graceful fallback would be useful.

For instance, adding the enqueue could be forgotten. Or the enqueued stylesheet path is incorrect. Or the enqueued stylesheet path is correct but for whatever reason the file can't load.

The issue is that when you do the above, placeholders and active block styles are removed. This makes it difficult to see what to do on a post, especially if it is using a post template with multiple blocks pre-created.

I would argue that this could accidentally occur under a variety of circumstances and if there is a workaround that can be introduced, it would help an end user experience, regardless of helping me save face for making this mistake during a live Gutenberg demo 😅

**To Reproduce**
1. Add `add_theme_support( 'editor-styles' );` to an active theme, but do not enqueue an editor stylesheet
2. View a post in Gutenberg.
3. Note the lack of placeholders and active block styles.

**Screenshots**
Post displaying placeholders and active/hover block states
![Post displaying placeholders and active/hover block states](https://user-images.githubusercontent.com/1971070/46082192-83ffac80-c16c-11e8-904c-716b9daa1b45.jpg)
Post without editor stylesheet displaying no placeholders or active block state
![Post without editor stylesheet displaying no placeholders or active block state](https://user-images.githubusercontent.com/1971070/46082193-83ffac80-c16c-11e8-87c2-b966b18700af.jpg)

Book CPT Template without issue
![Book CPT Template without issue](https://user-images.githubusercontent.com/1971070/46082139-616d9380-c16c-11e8-8b23-458e85987b7c.jpg)
Book CPT Template with issue
![Book CPT Template with issue](https://user-images.githubusercontent.com/1971070/46082140-616d9380-c16c-11e8-919b-6708551776db.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS v10.13.6
 - Browser Chrome, Safari, and Firefox Tested
 - Gutenberg v3.9.0, WP v4.9.8

**Comment by designsimply** [comment]
Wanted to add a quick note to say I tested with the Twenty Seventeen and it may not have been a good choice for this case. I have also left the label as `[Type] Enhancement` since it is asking for a fallback solution for the case where someone does `add_theme_support( 'editor-styles' );` without enqueuing an editor stylesheet.

**Comment by youknowriad** [comment]
We did a lot of improvements to the editor styles and now there's a "reset" that is always loaded to default to browser defaults where there's no editor styles That way for theme authors, the frontend matches the editor whether they load editor styles or not.
