### ISSUE TITLE
Gallery Image Block stacks images on iphone 6

### ISSUE THREAD

**Issue by roadrunner13** [WordPress/gutenberg#10192]
Hi,

I created a gallery image block on Gutenberg 3.9.0 Wordpress 4.9.8 of about 30 pictures or so, each picture linked to their respective attachment pages. It looks fine on any pc browser when I preview it or when updated, but when I see it on an iphone 6 OS Version 10.3.1 all the images get stacked (screenshot attached.) Right now I have the gallery with 1 column, I tried with 2 or 3 columns and I get the same problem. It looks fine if I do individual images though. I'm using Woocommerce Storefront theme and I'm not using any image gallery plugin other than what Gutenberg comes with, this page is separate from my shop page, it is just an image gallery page. Thank you.

Aldo
![img_1694](https://user-images.githubusercontent.com/43608936/46082000-f02de080-c16b-11e8-941a-9906f3a8d25c.PNG)

**Comment by designsimply** [comment]
Thank you for the details! This issue was also reported at #10150 so I'm closing this issue in favor of that one and we can follow along there.
