### ISSUE TITLE
Image Size Not Adjusting

### ISSUE THREAD

**Issue by kb61401** [WordPress/gutenberg#10206]
**Describe the bug**
Image size settings not working correctly. After uploading an inline image and selecting between 25%, 50%, 75%, and 100% for size, only 25% actually changes the size. If you select 50%, 75%, or 100%, the numbers change in the dimensions, but the image doesn't actually change visually or in the preview. Gutenberg 3.9.0.

**Expected behavior**
Only the 25% option works as expected.

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Browser: Chrome
 - Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by designsimply** [comment]
May I ask the starting dimensions of the image? The 25% option means that the image will size to 25% of its original size and if the image is much larger than the space allotted then it won't be noticeable in the edit view.

**Comment by kb61401** [comment]
Hi Sheri,
The original image is 1024 x 633.

**Comment by designsimply** [comment]
Wait! I tested an image block before, not an inline image in a paragraph block. I just tested again with an inline image though, and I don't see options in the sidebar to change the image dimensions for an inline image. 

<img width="1281" alt="screen shot 2018-09-27 at 5 27 00 pm" src="https://user-images.githubusercontent.com/1119271/46175818-4178c580-c27b-11e8-9e55-ee27df17d91b.png">
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15138&action=edit using Chrome 69.0.3497.92 on macOS 10.13.6.</sup>

Can you confirm exactly which kinds of blocks you are testing or provide a short list of testing steps or perhaps a screenshot?

**Comment by kb61401** [comment]
Sorry, I wasn't very clear. I was using an image block. I am able to change
the percentage to 25% successfully. However, there is no change to the
actual size of the image when I select 50% or 75%, even though the numbers
change in the side bar. When I select 50% or 75% the numbers change in the
size bar, but the image doesn't change size in the visual editor or in the
preview, instead it stays at 100% size.

**Comment by talldan** [comment]
Hi @kb61401. At 75% and 100% width, the image is too wide to display at its full size in the editor, so the image is resized to take up only as much width as the editor allows. Depending on your theme the same may also be happening when viewing the post.

Are you looking to have you image take up as much width as possible? There is support for what we call 'wide' images in gutenberg, as shown in this example post here:
https://frontenberg.tomjn.com/

Is that the kind of thing you're looking for?

**Comment by kb61401** [comment]
Got it. That makes sense. The full size image is currently 1476 x 912. I
was trying to make it somewhere between the full size and 25%. The 25%
option is too small.

Thank you for your help.

**Comment by talldan** [comment]
Glad to have helped!
