### ISSUE TITLE
Add Screen Options equivalent

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#10210]
Surfacing this one back up as a compatibility and enhancement task. This would be the best way to provide access for _custom fields_ given we are lacking a proper API support for them. This is meant to be a quick implementation using our core APIs: plugin menu, and modal.

![screen](https://user-images.githubusercontent.com/548849/46142930-cd2d2a80-c258-11e8-972c-e37ce8d95707.png)

The options modal would combine current screen options, the tips, and the publish flow setting. It would absorb some items from the main toolbar, so that it'd end up looking like this:

![menu](https://user-images.githubusercontent.com/548849/46143078-2d23d100-c259-11e8-83b3-0c4b084a5df4.png)

**Comment by danielbachhuber** [comment]
Once this lands, we should make sure to address #3228 (even if it's just to close the issue because Custom Fields have returned).

**Comment by bkjproductions** [comment]
I would like to understand this better. Would there be a *list* of Custom Fields (key/value for each) in this Options modal? 
Or is the purpose of the Options modal simply to show a checkbox/button to then allow another section of the interface to show the Custom Fields (key/value for each) at the bottom of the page like it does in the Classic Editor?

**Comment by youknowriad** [comment]
> Or is the purpose of the Options modal simply to show a checkbox/button to then allow another section of the interface to show the Custom Fields (key/value for each) at the bottom of the page like it does in the Classic Editor?

More the second point but this is tracked in #3228
