### ISSUE TITLE
is it possible to add Custom attribute in link?

### ISSUE THREAD

**Issue by nitishkaila** [WordPress/gutenberg#10226]
Currently Gutenberg is not providing any type of functionality to add custom html attribute into the link/anchor tag. Also not option to track click event for current flow.

**Comment by Soean** [comment]
Hey @nitishkaila,
can you provide an example usage with code?

**Comment by nitishkaila** [comment]
Hi @Soean,

I want to add a custom attribute in the link for core/paragraph and core/list block. is there any hook or possibility to add a custom attribute in the link for existing core block?

**Comment by encipherdesign** [comment]
@Soean / @wordpress

there should be an easy way to add valid html attributes to links which would improve accessibility, usability and security. https://www.w3schools.com/tags/tag_a.asp

this could be included [in the link **options dialog?**] to make adding valid links easier without using the code-mode or additional content filters:

`<a href="<url>" title="<link title/default_to_link_label>" rel="<nofollow,noopener _[stop using _blank]_ >" item-prop="url" data-<variable>="<string_value>" tabindex="1" ><link_label></a>`

parsing/filtering the_content() leads to performance/maintenance issues as it adds one more function that _should be taken care of on entry_, [without a developer needed to create custom filters for a client]. 

these options are basic options available in CKEditor : 

![link-type](https://user-images.githubusercontent.com/4871682/46249868-4eb1c380-c3e5-11e8-971c-4348d8aca988.jpg)
![link_attr](https://user-images.githubusercontent.com/4871682/46249869-4eb1c380-c3e5-11e8-95a9-1e4c2af28ede.jpg)

### feature request?
these options should be native on any legit cms.

**Comment by nitishkaila** [comment]
Hi @encipherdesign,

This is CKEditor but I need to add attribute in the Gutenberg link. I have also concern about link click event. Many site has track the google event when click on the link. So I think this is limitation of Gutenberg link which we not add other attribute or not track the click event.

**Comment by nitishkaila** [comment]
Hi @Soean 

All most site has used google analytics event by clicking on button or link. We can embed this think underneath link box. So normal user can easily add the google tracking event or something else without help of developer.

thanks

**Comment by youknowriad** [comment]
Attributes is something very developper related, I don't think we should expose any attribute without explanation. For example we don't say "target" we say "open in a new tab". 

That said, it is still possible to add any custom attribute to link by switching back and forth to the HTML mode of the block. It is also possible to build custom toolbar buttons to allow advanced use-cases using the Format API.

I'm closing this for now. Thanks for your input.
