### ISSUE TITLE
Closing quote replaced with &#8221; when quoting "http://"

### ISSUE THREAD

**Issue by mnelson4** [WordPress/gutenberg#10238]
**Describe the bug**
If a paragraph contains "http://", the closing quote gets replaced with an HTML-encoded &#8221;

**To Reproduce**
1. Create a new post. Add the following paragraph to it:
> Here is how you start a URL: "http://" or "https://".
1. View the preview or publish it
2. You'll see
> Here is how you start a URL: "http://&#8221; or "https://&#8221;.

**Expected behavior**
No HTML encoded HTML entities should be visible.

**Screenshots**
Editor: 
![screenshot-cmljnelson wordpress com-2018 09 28-12-54-59](https://user-images.githubusercontent.com/1766382/46230553-cddbc480-c31d-11e8-987f-ef4c8efd1dc9.png)
Front-end: 
![screenshot-cmljnelson wordpress com-2018 09 28-12-55-30](https://user-images.githubusercontent.com/1766382/46230563-d7652c80-c31d-11e8-80af-ecc9983a3698.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox
 - Version 63.0b9 (64-bit)

**Additional context**
Active theme: Rebalance

**Comment by saulirajala** [comment]
I was not able to replicate the issue. I tested with Safari 12.0 & Chrome 69.0.3497.100 on MacOS 10.13.6 with fresh WordPress install (runs in docker setup of Gutenberg) and Twentyseventeen theme & Rebalance-theme. In all cases, quotes seemed to work fine:
<img width="675" alt="nayttokuva 2018-10-6 kello 22 20 18" src="https://user-images.githubusercontent.com/5536354/46575023-0f234280-c9b6-11e8-8725-346d0f4ae157.png">

**Comment by mnelson4** [comment]
My apologies, I was originally reproducing this issue on a wordpress**.com** site. When I re-tested from a self-hosted site, I'm not reproducing. So wordpress.com must be running something else that was causing the issue...

**Comment by mnelson4** [comment]
Yeah, I just confirmed it's definetely a wordpress.com issue only. I'm also reproducing it with their Calypso editor.
thanks and my apologies @saulirajala !
