### ISSUE TITLE
While dragging a block, upwards scrolling of the page is hindered by notice message

### ISSUE THREAD

**Issue by TheMangoTrain** [WordPress/gutenberg#10239]
**Description**
Using Gutenberg 3.9.0

While dragging a block on a very long page, upwards scrolling of the page is hindered by notice messages inside the Gutenberg editor. I have to manually press "x" on the notice message to be able to drag blocks upwards on a long page. The presence of the notice message doesn't allow for scrolling to trigger when the dragging-cursor enters the same region.

**To Reproduce**
1. Start with a test page, filled with enough random blocks and content so that there's lots of scrolling needed.
2. Scroll down to the bottom of the page in the Gutenberg editor window; for convenience make sure there's a small block there.
3. Invoke a notice message to appear. The easiest is just pressing "Update" (in the case of updating a published page).
4. The notice message appears, e.g. "Post updated! View post". It's a colored bar at the top of the editor window, with an "x" to close it.
5. Try dragging a block upwards to a much higher spot on the page. The notice message doesn't allow for page scrolling to be triggered. You have to stop your train of thought, let go of the block you carefully selected (especially if it's within nested block), manually close the notice message then start the block dragging process over again.

**Expected behavior**
Many people would perhaps expect or desire for drag-induced page scrolling to act normally even with a notice bar in the way. Maybe the notice bar can fade-out slightly when a dragging-cursor enters the region. In any case, it is annoying to have to mentally stop what you're doing (dragging a block) to deal with a notice bar (which 99% of the time is just an affirmation message).

**Desktop:**
 - OS: Macos 10.13.6
 - Browser: Chrome
 - Version: 62.0

Using Gutenberg 3.9.0

**Comment by shoelaced** [comment]
I came to post that drag-scroll didn't work at all but discovered it does when I manually closed the notice as described above. What I would add is that it would be helpful if dragging over the top toolbar would also scroll the page, because as it currently works, you have to drag exactly over the tiny area right on the bottom edge of the top toolbar in order to get it to scroll.

**Comment by youknowriad** [comment]
I just tested this again and a few things have changed:

 - These notices are used less (we use snackbars as alternatives)
 - I didn't reproduce the issue with or without the notice

That said, I think drag and drop is still not great, it's hard to get the page to scroll. I think these should be addressed with rethinking how drag and drop works (efforts like #16457)
