### ISSUE TITLE
Gutenberg 3.9.0 breaks type declaration on `script_loader_src` filter.

### ISSUE THREAD

**Issue by NathanDJohnson** [WordPress/gutenberg#10237]
**Describe the bug**
Gutenberg 3.9.0 breaks type declaration on `script_loader_src` filter.

**To Reproduce**
1. Install Gutenberg plugin
2. Create plugin with the following code:
    `add_filter( 'script_loader_src', function( string $src ) { return $src;  } );`
3. Attempt to edit any page with Gutenberg

**Expected behavior**
Without Gutenberg and with previous versions of Gutenberg, the above code works.

**Comment by johnbillion** [comment]
This _may_ have been introduced in 6d7b5a7. The `$src` parameter for a script should either be a string or boolean `false`, not `null`.

**Comment by youknowriad** [comment]
Is this still an issue? 

In any case, I'd suggest open a trac ticket instead as the PHP code moved to Core.

Thanks.
