### ISSUE TITLE
Preview doesn't mirror what's in the editor

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#10245]
**Describe the bug**
After having used HTML5 &lt;mark&gt; to highlight passages using `<mark style="background-color: orange;"></mark>` around one of the passages, the preview in the editor shows the colors properly. When I click 'Preview', the preview page doesn't reflect the style= color selection.

**To Reproduce**
1. Create some text in a block
2. Add `<mark style="background-color: orange;">text here</mark>` via HTML
3. Switch to the visual editor which now shows the highlight as orange
4. Click Preview button and notice it shows yellow

**Expected behavior**
If the style tag information can be previewed correctly in the editor, the actual preview page should also reflect that same appearance. I can't tell you if this affects the actual published page because I haven't yet published this article.

**Screenshots**

Visual Editor Window:
![editorshowsorange](https://user-images.githubusercontent.com/16678592/46243042-39f11380-c384-11e8-8520-e8753844931b.png)

Preview Page:
![previewyellow](https://user-images.githubusercontent.com/16678592/46243046-3c536d80-c384-11e8-95e3-55a54ee28197.png)

**Workaround**

Use `<span style="background-color: orange;">text here</span>` instead of HTML5 `<mark>`

**Desktop (please complete the following information):**
 - OS: MacOS X High Sierra
 - Browser: Firefox Quantum
 - Version: 61

**Smartphone (please complete the following information):**
 - Device: Untested

**Additional context**
None

**Comment by designsimply** [comment]
I am adding the `Needs Testing` label for further review, and may I also ask for you to note what theme you are using so that information is on file here in case it is relevant?

**Comment by commorancy** [comment]
The theme I am using is The Journalist 1.3. I know, it's really old. However, I've made enough customizations and inline CSS adjustments to this theme that it'll be difficult to upgrade to a new theme without re-editing a substantial number of articles. I'm pretty sure it's not the theme. If _span_ works without issue, then so should _mark_. It seems the Wordpress HTML validator may be stripping out the style= for mark during the preview or published article screens. I don't think the theme has any control over HTML validation.

**Comment by fabiankaegy** [comment]
Testing on Clean WordPress 4.9.8, Gutenberg 3.9.0, Twenty Seventeen 1.7 I am not able to reproduce the issue. Works as expected. The style attribute doesn't get stripped away and the <mark> gets the color applied.

**Comment by ellatrix** [comment]
Same here, I'm not able to reproduce the issue. It sounds like your theme's CSS is overwriting the styling.
