### ISSUE TITLE
Support highlighting of text with HTML5 mark

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#10243]
**Is your feature request related to a problem? Please describe.**

I'm trying to highlight a relevant passage of text like using a highlighter marker. This is useful when pasting in quotes and highlighting a relevant portion.

**Describe the solution you'd like**

Since you're adding cool new features, let's add in support for the HTML5 mark tag. Basically, this adds the ability to highlight text as if using a highlighter marker. I'd like a new highlighter tool in the toolbar.

- Click the 'Highlighter' icon
- Choose a background text color
- Wrap mark around the text with the chosen color
- Done

**Describe alternatives you've considered**

Manual HTML markup with a span using inline CSS via background-color set around the text.

**Comment by designsimply** [comment]
In the current roadmap, the focus is moving very soon to an emphasis on bug fixing and launching as opposed to adding new features. Because of this, I am going to move this one to the Ideas project. This means it will be closed for now and reopened as needed when it can be reviewed in more detail in the next phase for the project. 

I love that you've added the suggestion and that you have made other contributions in testing/but reporting! Thank you!

**Comment by desrosj** [comment]
I wanted to reopen this for reconsideration.

I came across [Trac-38115](https://core.trac.wordpress.org/ticket/38115) while triaging and I think there is a very valid use case for this.

**Comment by coreymckrill** [comment]
Seems like this could manifest as an inline `Background color` and would be a natural compliment to the `Text color` rich text option.

**Comment by mtias** [comment]
@ellatrix curious what you currently think of this and whether it should be left for plugin territory.

**Comment by mkaz** [comment]
I'd like to see an inline background color, it would be a nice to be able to do a highlight. Right now there is an inline text color, it seems like adding a background in the same would be :+1: 

![image](https://user-images.githubusercontent.com/45363/133820167-d2a482fb-c50f-4e0b-98a2-136af5e2f95a.png)

**Comment by mtias** [comment]
Work in progress: https://github.com/WordPress/gutenberg/pull/34680

**Comment by bph** [comment]
closed as completed with #34680

https://user-images.githubusercontent.com/39980/177147980-e8ede4e7-9aae-4b59-84da-87b4c27e5c93.mp4
