### ISSUE TITLE
General Takeaway Feedback

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#10248]
After having used Gutenberg for writing a full article, here is some general feedback.

While I initially liked the idea of moveable blocks, what I've come to find is that it actually makes writing unnecessarily more complicated for a number of reasons. The first problem is that blocks get easily lost. When you click the up or down arrow, the movement of the screen means you lose visual track of which paragraph you just moved and where it stopped. So now, I'm confused as to where it landed and which paragraph it actually was. This is partly because the screen moves in an unpredictable way when a block moves. After a move, the block that moved needs to flash or change color and slowly fade so you can easily see which one moved. As it is now, it's disconcerting. 

I might also suggest labeling each block with a unique identifier, perhaps by number. This number should remain static even if the blocks move. This way you can always identify a specific block by its identifier. This also gives you a point of reference to the original block order in case you need to go back to it.

There are also a number of goofyisms that are a bit trying. For example, this is the second problem, when you edit HTML in a paragraph block, when switching back to visual editing, the block sometimes says, "This block was modified externally" and then forces a conversion to HTML or Blocks. Sometimes it doesn't do this and the HTML edit works fine. It's random when this happens after editing the HTML directly. Once it's converted the block to HTML, no longer can you visually edit the block or see a the block visually in the editor. This is frustrating. I have to then redo the block over and try again.

There's no way to create a Featured Image in Gutenberg. This forced me to go into the older new editor and add it there. When I did that, it corrupted parts of the Gutenberg created article. Specifically, it corrupted the quote block types,. So, depending on the blocks used, the other editors don't support editing all of Gutenberg's features. If you've used Gutenberg on an article, you're pretty much stuck with Gutenberg on that article. There's no easy conversion back to the other editors. This means a Gutenberg edited article needs to be identified in the 'All Articles' area. It should also warn the user if they try to edit the article in an editor other than Gutenberg.

Another oddity is that the categories are not sorted. It's not a huge problem, but it does make setting the categories more difficult.

Clicking the _Edit This_ link, Wordpress leads to the old editor, not Gutenberg. The edit button needs to become editor aware and take you to the proper editor whenever it's clicked.

It's unnecessarily difficult to drag select text in blocks in Gutenberg. When you drag the mouse, the screen zooms away from you selecting not only everything in the block but many other blocks above or below. It would be great if a context menu could be added that would allow you to select all of the text in a single block rather than having to drag select (which doesn't really work well).

As a follow-on to the above drag select problem, when an image block overlaps onto a paragraph block, it becomes almost impossible to select text in that paragraph block.

Clicking the + to add a new block just above another block doesn't work about 80% of the time. You click it and nothing happens except the current block's toolbar appears.

When I first attempted to publish my Gutenberg edited article, a red banner appeared that said, "Publishing failed". There was no explanation for the failure. I tried about 3 times successively to the same failure result. Then, after clicking Preview button, it miraculously published.. again with no explanation.

**Comment by designsimply** [comment]
Thank you for the feedback. Some of the issues you have noted are filed as bugs or feature requests already. I am adding the `Needs Testing` label and noting that it would be nice to go through and check each item to note the relevant report already on file or request that a new issue is created if one is missing.

**Comment by youknowriad** [comment]
Thanks for the feedback, most of these have corresponding issues. 

I'm going to close this issue right now as it's very hard to work with for the contributors and prefer smaller actionable issues.

If there's something in this feedback that's not tracked in an issue, please feel free to open a new one.
