### ISSUE TITLE
Core blocks default styles

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#10249]
It seems either removing or adding the following [theme support method](
https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#default-block-styles) has no effect in the end.
`add_theme_support( 'wp-block-styles' );`

The default core block styles are loading anyway!

**Comment by mtias** [comment]
`wp-block-styles` controls certain cosmetic styles for the blocks (like the left border on a quote) when loaded on the front. If you still see a left-border on the quote block on the front-end, please reopen.

**Comment by mahdiyazdani** [comment]
@mtias 

Please do NOT close this until we get a confirmation from the devs regarding this bug.
I understand that you are facing with 1000+ issues but closing them without even checking on your end will help no one.

![](https://i.gyazo.com/ac1eaeaeb527e85519539b41d88fb816.png)

**Comment by leodluz** [comment]
The same issue here. Guteberg default styles is not loading.
