### ISSUE TITLE
"Warning: Invalid argument supplied for foreach () - line 36" is displayed and it can not be activated

### ISSUE THREAD

**Issue by nukaga** [WordPress/gutenberg#10246]
**Describe the bug**
Warning: Invalid argument supplied for foreach() in /home/users/0/XXX/web/wp-content/plugins/gutenberg/lib/load.php on line 36

There are sites that have the same error.
[Google search results in Japanese](https://www.google.co.jp/search?ei=b0KvW5jeMIGl8QXj0JSYCQ&q=gutenberg%2Flib%2Fload.php+on+line+36&oq=gutenberg%2Flib%2Fload.php+on+line+36&gs_l=psy-ab.3...375.17424.0.18755.2.2.0.0.0.0.0.0..0.0....0...1c.2.64.psy-ab..2.0.0....0.FVWnRbaPMDc)

Gutenberg 3.9.0
WordPress 4.9.8

Network activating this plugin and viewing any URL, both Dashboard and user facing Pages, generate this error that shows up in the browser.
This will restore the site if you disable the plugin Gutenberg.

**Desktop (please complete the following information):**
 - OS:Mac OS 10.9.5
 - Browser chrome
 - Version 69.0.3497.100

**Additional context**
It looks like the same bug as # 9213, but it will not occur even if it is multi-site. It is occurring now.

**Comment by danielbachhuber** [comment]
Hi @nukaga,

Thanks for the report! This issue will be resolved with Gutenberg 4.0 is released. It was fixed with #10147
