### ISSUE TITLE
Don't Go Overboard With "Distraction-Free

### ISSUE THREAD

**Issue by alaJoAnn** [WordPress/gutenberg#10259]

**Comment by alaJoAnn** [comment]
Please stop burying every edit action behind a vague-looking icon or hamburger menu. At the minimum, this doubles the number of clicks required to do anything. Too often, a guess-and-peck search is required to find the action, in the first place. This is not user-friendly. It is anything but distraction-free. It slows and interrupts the creative process. The human brain works much faster than the Gutenberg user interface allows.

I see this design trend throughout the Internet. It is a mistake. The motto ought to be "mobile first, AND finish the job for large screens."

**Comment by designsimply** [comment]
I appreciate this feedback. This is something I know that the design and development teams have in mind already and I know that it has come up in user testing and various configurations have been user tested along the way and adjustments may still be under consideration for fine-tuning this sort of thing.

I am going to close this issue and also say that your feedback has been noted. If you would like to continue the discussion here, including one or two very specific examples would be nice to have. Thank you!
