### ISSUE TITLE
Gallery-block: adds images even though upload fails

### ISSUE THREAD

**Issue by saulirajala** [WordPress/gutenberg#10251]
**Describe the bug**
Issue happens when one uploads from computer for example four images: File size of two images are too large, but the other two images are ok. So the result is that two images are uploaded to media library, but two are not. 

Yet Gallery -block seems to assume that there are four images in the gallery and "replicates" the two images that were uploaded to media library (see screenshot 1). After reload of the page, gallery-block has two broken images (screenshot 2) and there are errors in console of browser:
`GET blob:http://gutenberg.test/88f7c6cd-fe07-475a-8f87-af7bda580c3f net::ERR_FILE_NOT_FOUND`
`GET blob:http://gutenberg.test/2ce3c7bb-aa28-4187-811e-95e3cbfd3815 net::ERR_FILE_NOT_FOUND`

**To Reproduce**
1. Add Gallery-block
2. Click Upload -button
3. Choose two images with too large image size and two ok images
4. See how gallery "replicates" the images, that were ok
5. Reload site
6. Gallery has now two broken images and two ok-images

**Expected behavior**
Only the images that were actually uploaded to media library, should be added to gallery-block.

**Screenshots**
Screenshot 1:
![nayttokuva 2018-09-29 kello 22 23 39](https://user-images.githubusercontent.com/5536354/46249823-4d5db680-c438-11e8-8b33-cf180441de29.png)

Screenshot 2:
![after_reload](https://user-images.githubusercontent.com/5536354/46249825-52226a80-c438-11e8-8a3b-5436b35dc64d.png)

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- Gutenberg version 3.9.0 (current master)

**Comment by ChrissiePollock** [comment]
I tested this in Firefox using a local environment. I downloaded four images from https://unsplash.com/s/photos/large. Their sizes were: 3.1 MB, 2.1 MB, 3.9 MB and 5.6 MB.
![bernard-hermant-CLKGGwIBTaY-unsplash](https://user-images.githubusercontent.com/2545184/68091641-acfe7080-fe47-11e9-8e0e-e534c6e439d3.jpg)
![tobias-fischer-ljp-ewA23lc-unsplash](https://user-images.githubusercontent.com/2545184/68091642-ad970700-fe47-11e9-8d5b-b94ab9e35efd.jpg)
![ferdinand-stohr-7F3jUAyqTBg-unsplash](https://user-images.githubusercontent.com/2545184/68091643-ad970700-fe47-11e9-8e15-cab178a373d2.jpg)
![timj-EJ4qfFp1g8Q-unsplash](https://user-images.githubusercontent.com/2545184/68091644-ad970700-fe47-11e9-8108-d9a1c8b38e12.jpg)

I did not get the same error message as described in the initial post, but I still had errors.

At first it looked like me images were adding:

![Screen%20Shot%202019-11-03%20at%2014 33 18](https://user-images.githubusercontent.com/2545184/68091694-6f4e1780-fe48-11e9-8fa4-2e944a48523c.png)

Then I was shown an error:

![Screen%20Shot%202019-11-03%20at%2014 33 53](https://user-images.githubusercontent.com/2545184/68091700-9278c700-fe48-11e9-9dd3-3ca02cdc8a99.png)

On Preview, only two images appeared:

<img width="696" alt="Screen%20Shot%202019-11-03%20at%2014 47 21" src="https://user-images.githubusercontent.com/2545184/68091727-f602f480-fe48-11e9-841f-a215544c9787.png">

It was not obvious from the error message that the images were too large.

**Comment by adamziel** [comment]
A similar problem occurs when you save the post while some of the images are still being uploaded.

**Comment by aaronrobertshaw** [comment]
With all the recent work done around [refactoring the Gallery to use nested blocks](https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note/), now is as good a time as any to see if this is still an issue.

### Original gallery

Using the original gallery and setting a `4Mb` upload limit, I was not able to replicate the issues described here. 

I tried initially with my own images where multiple images were over the limit and some under. Only those under the upload limit were added to the gallery and an error message for the others was displayed. So for me, the original issue described is no longer a problem.

Following that, I tested with the images supplied by @ChrissiePollock. The gallery returned an appropriate error message and only displayed the valid images.

No errors were thrown when attempting to save while images were still uploading either. 

At this stage, the original gallery is looking good.

### Refactored Gallery (using nested inner image blocks)

After turning on the [refactored gallery block experiment](http://localhost:4759/wp-admin/admin.php?page=gutenberg-experiments) and repeating the tests I did experience one problem though.

<img width="411" alt="Screen Shot 2021-08-26 at 5 27 49 pm" src="https://user-images.githubusercontent.com/60436221/130920074-9efcf1c5-d1e6-4136-b4e9-b6009e326451.png">

There was no error displayed when attempting to upload an image over the size limit. The image block continues to display the loading spinner, as does the gallery's image size control. I left the editor open for several minutes and didn't see any errors or timeout messages appear.

https://user-images.githubusercontent.com/60436221/130920499-c04f8631-b832-437a-84bb-4684f026ccae.mp4

There is a [project board](https://github.com/WordPress/gutenberg/projects/56) tracking issues and follow up tasks for the gallery. I'll add this issue there.
