### ISSUE TITLE
Create table block results in page refresh/redirect

### ISSUE THREAD

**Issue by ChemicalSailor** [WordPress/gutenberg#10254]
Testing with a vanilla installation and safari v12 (desktop). Create a new post, insert a table block and click create. Table is inserted, then the page refreshes losing modifications. Sometimes it redirects back to edit.php instead.

**Comment by designsimply** [comment]
Thank you for the report! I have tested and confirmed that I am redirected to the Posts list after I hit the "Create" button while adding a table block using Safari 12.0 on macOS 10.13.6. I tested with both Gutenberg 3.9.0 as well as Gutenberg 4.0-rc.1 on WordPress 4.9.8.
