### ISSUE TITLE
Respect `SCRIPT_DEBUG` in released plugin versions

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1026]
When we release plugin versions, we should allow people to debug our JavaScript using the [`SCRIPT_DEBUG` constant](https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG).  This constant is defined and used by core, but it's [nice to support it in plugins also](https://pippinsplugins.com/use-script_debug-enable-non-minified-asset-files/).

This is currently working for vendor JavaScript code like React and Moment.js, since we load the minified or non-minified versions of these files based on the value of this constant.  However, it's not working for our own JavaScript code because we always [build to](https://github.com/WordPress/gutenberg/blob/fc5cc79b1959f50fec6207661f12818400857eda/webpack.config.js#L110-L112) and [load from](https://github.com/WordPress/gutenberg/blob/fc5cc79b1959f50fec6207661f12818400857eda/lib/client-assets.php#L138) the same set of files, regardless of whether they are minified or not.

This means that currently:

- During plugin development, the version of JS and CSS that will be loaded is the last one built, whether minified or not.
- Release versions of the plugin will always use the minified files, because they were the last version built.

The behavior during plugin development is probably what we want; however, we should bundle both the development (unminified) and production (minified) versions of our JS and CSS with the plugin, like we do for vendor files.

In order to achieve this we'll need to add a `npm run build-dev` command that writes to a separate set of files, and modify the plugin logic for **release mode only** to load either of these sets of files based on `SCRIPT_DEBUG`.

This will also give us a way to allow users to enable the Save button themselves during early releases: just enable `SCRIPT_DEBUG` on their WP install.  See #748.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518715885000497)._

**Comment by jeffpaul** [comment]
Closing this per today's Gutenberg bug scrub given lack of request to support this and not wanting to have to ship unminified versions of JavaScript.
