### ISSUE TITLE
svg with MediaUpload?

### ISSUE THREAD

**Issue by braco** [WordPress/gutenberg#10263]
It doesn't seem possible to upload or manage SVG files with MediaUpload. Is this true?

**Comment by braco** [comment]
I guess this needed to be enabled in WP via:

```
function cc_mime_types($mimes) {
	$mimes['svg'] = 'image/svg+xml';
	return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');
```

**Comment by designsimply** [comment]
Thanks for finding the solution and noting it! I also noticed some disclaimers about using that kind of code when I searched online:

<blockquote>The reason SVG is not part of WordPress core yet is that there are security concerns to be addressed. You can follow the active discussion about SVGs in WordPress core (#24251) which was started back in 2013.  SVG is an XML file, which by itself opens it up to different vulnerabilities of which normal image formats aren’t affected. These include XML external entity attacks (XXE), bomb nested entities, and XSS attacks.</blockquote>

<blockquote>Don’t go and just download the first free SVG plugin you see or copy paste this code and think your good to go.</blockquote>

— Source: https://kinsta.com/blog/wordpress-svg/
