### ISSUE TITLE
Add the core/template block to reusable blocks that only has a single block

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#10271]
**Is your feature request related to a problem? Please describe.**
When you create a reusable block that consists of multiple reusable blocks you get the added enormous benefit of being able to add (or remove) blocks when you edit them. If you create a reusable block from a single block you are forever stuck with just a single block. 

**Describe the solution you'd like**
I want to be able to add more blocks when I edit a reusable block that only consists of one block.

**Describe alternatives you've considered**
This would kind of be dealt with if it was possible to edit reusable blocks like regulat cpts but even if that becomes possible that would mean a bunch of extra steps to do this.

**Comment by slimmilkduds** [comment]
Another approach could be to add a transform block option so you convert from a reusable block to a reusable template

**Comment by noisysocks** [comment]
Interesting idea. I guess my only fear is that it might complicate the basic use-case which is to take a single block and make it reusable.

> This would kind of be dealt with if it was possible to edit reusable blocks like regulat cpts but even if that becomes possible that would mean a bunch of extra steps to do this.

This is possible as of Gutenberg 4.1, see https://github.com/WordPress/gutenberg/pull/10751.

**Comment by slimmilkduds** [comment]
I agree that it might complicate the basic use case. An option to convert a reusable block to a reusable template however might get rid of that problem. Anyhow, since you note, 4.1 at least allows a work around for this.

**Comment by mapk** [comment]
It appears this is all possible now. I can edit a reusable block, add other blocks, and save it again. Closing this issue.
