### ISSUE TITLE
Reusable Block Editor Interface

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#10275]
**Is your feature request related to a problem? Please describe.**
Currently, when you bulk manage reusable blocks, you can click a block to "edit" it. Upon reaching the edit screen, you see a blank screen with only a post management widget (with publish, time, etc options). Why is there not a block editor here? This is extremely confusing and seems to make reusable blocks meaningless? Is there something I'm missing here?

**Describe the solution you'd like**
Editing a reusable block should allow you to actually edit the block and it's content.

**Describe alternatives you've considered**
It seems to be that this is just an interface for deleting reusable blocks, which seems unnecessary without the ability to edit the block itself and its content.

**Comment by slimmilkduds** [comment]
I agree with you 100%

Here's an older issue about this: https://github.com/WordPress/gutenberg/issues/9964

**Comment by mrpritchett** [comment]
And another one in a similar vein: https://github.com/WordPress/gutenberg/issues/8403

**Comment by bph** [comment]
This is great thinking @mrpritchett Thank you. 
There are also additional thoughts on this topic on the issue https://github.com/WordPress/gutenberg/issues/8403

**Comment by chrisvanpatten** [comment]
Thanks for the idea @mrpritchett! As noted we have a ticket over at #9964 about this, and I'm hopeful we will make progress on this soon. To keep things consolidated I'll close this as a duplicate but definitely suggest commenting on the other ticket!
