### ISSUE TITLE
Defer fetching non-hierarchical terms in FlatTermSelector

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10274]
Currently, `FlatTermSelector` fetches _all_ of its potential terms immediately on `componentDidMount`:

https://github.com/WordPress/gutenberg/blob/4ebd53cba1042fded4362724b55bb4c252d61357/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L63

On a site with a large number of tags, this can cause the component to immediately crash: https://github.com/WordPress/gutenberg/issues/6694#issuecomment-425763571

The Classic Editor waits until the user has entered search input before making an AJAX request. This helps with the performance implications because the request is only ever fetching a subset of terms. We should take the same approach in Gutenberg.

**Comment by davisshaver** [comment]
Loading the most-used tags at first might be a nice UX too, in lieu of an empty input field.

**Comment by aduth** [comment]
Discussed in Slack ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C02QB2JS7/p1539608797000100

It's my understand that we  could simply remove the line referenced in the original comment without other impact on existing behavior†.

† Existing behavior to verify:

- Existing assigned tags are loaded and displayed on load
- Requests (and subsequent result) is shown on input in the field
