### ISSUE TITLE
Pull data for custom taxonomy

### ISSUE THREAD

**Issue by ovidiul** [WordPress/gutenberg#10277]
I have registered a custom taxonomy term for images called copyright. I have created a block that hooks into the image component, and modifies the edit/save return to add that copyright as a new block, code below:

```
function modifyBlockEdit( BlockEdit ) {
    return (props) => {
        if ('core/image' === props.name) {
            const { attributes: { copyright }, setAttributes } = props;
            return (
                <Fragment>
                    <div>
                        <BlockEdit { ...props } />
                        <RichText
                            tagName="figcopyright"
                            placeholder={ __( 'Write copyright…', 'o1-blocks-modules' ) }
                            value={ copyright || [] }
                            onChange={ ( value ) => { setAttributes( { copyright: value } ) } }
                            />
                        </div>
                </Fragment>
            );
        }
        return (
            <Fragment>
                <BlockEdit { ...props } />
            </Fragment>
        );
    };
}```

My question is  how to i put the initial taxonomy value inside ?

Hopefully somebody can point me in the right direction. Thanks

**Comment by youknowriad** [comment]
Hi there! thanks for the issue. This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

That said, note that the `save` function is a synchronous function so you can't use data there that is not coming from the block attributes. 

For the `edit` function, you can load data using API requests, the data module... 

See the documentation of the data module for instance https://developer.wordpress.org/block-editor/packages/packages-data/

This [blog post](https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/) might come handy as well.


Thank you!
