### ISSUE TITLE
Property for child blocks like "layout"

### ISSUE THREAD

**Issue by RanzigeMilch** [WordPress/gutenberg#10285]
Hi all,

first i have to say i missed the updates of Gutenberg from 3.0.x to 3.9.x. What happened to the layout property of InnerBlocks? This property was the only possibility to know if a block is a InnerBlock or not.

Im wrapping all blocks as default into a box/container markup. That was no problem with the "blocks.registerBlockType" and "blocks.getSaveElement" filter. With the "blocks.BlockEdit" filter i could add some container features like max-width or background-color and spacing.

But inside a column i do not want a block to be wrapped. The block needs to now itself if it is inside another block or not. That was no problem with the layout property (I also used it to add custom column classes - i wrote some custom bootstrap / flexbox columns).

To build a container / section or transparent block as wrapper is not a solution. The user is not able to decide if he needs it or not. 

Is there an existing possibility to get the "parent"-information of a nested block (i was not able to find one)? If not, that would be a necessary feature to be more flexible in templating without overburdening the editor.

**Comment by youknowriad** [comment]
You can use the data module (`withSelect`) https://wordpress.org/gutenberg/handbook/packages/packages-data/ and this selector https://wordpress.org/gutenberg/handbook/data/data-core-editor/#getblockrootclientid to retrieve the parent block of any block (by passing the clientId argument). You access the `clientId` from the props passed to the `edit` function of the block.

I hope this helps.
