### ISSUE TITLE
Question: Changing font in Gutenberg?

### ISSUE THREAD

**Issue by YanaSSS** [WordPress/gutenberg#10302]
I cannot find where I can change my font in Gutenberg

**Comment by mcsf** [comment]
Font sizes and colors are customizable in Gutenberg. However, font faces currently aren't, as they are still expected to be provided by the theme. Indeed, phase 1 of Gutenberg concerns the editing experience of the post content. (That said, fonts are "customizable" if you edit the post's HTML, in the same way as in the classic editor.)

Richer styling abilities, including around fonts, are expected in phase 2.
