### ISSUE TITLE
Pasting with an indented unordered list is amazingly buggy

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10303]
See GIF for multiple behavioral issues:

![buggyindentedlist](https://user-images.githubusercontent.com/36432/46411727-61701500-c6d1-11e8-9822-c3b2a6605383.gif)

**Desktop:**
 - OS: Mac 10.13.6
 - Browser: FF Quantum
 - Version: 62.0.2

**Comment by mtias** [comment]
See https://github.com/WordPress/gutenberg/issues/6555 and https://github.com/WordPress/gutenberg/issues/5727

**Comment by mcsf** [comment]
The issues you mention are actionable, @mtias.

@danielbachhuber, not sure what time you have, but taking your report and clearly identifying its issues would be very helpful.

**Comment by danielbachhuber** [comment]
> taking your report and clearly identifying its issues would be very helpful.

I don't have the bandwidth this week to track down the specific technical defects. The GIF I shared seems fairly obvious though.

**Comment by chrisvanpatten** [comment]
@danielbachhuber I could try to look into this a bit; but out of curiosity what was your paste source? Were you pasting from within Gutenberg?

**Comment by danielbachhuber** [comment]
> what was your paste source? Were you pasting from within Gutenberg?

A GitHub Gist.

**Comment by chrisvanpatten** [comment]
Okay so the issues particularly seem from pasting an ordered list into another ordered list but only if you paste into an indented level.

Test case:

1. Copy the list from this rendered markdown: https://gist.github.com/chrisvanpatten/069aeaeca2a6de74c83ee9743e9a1dc4
2. Note that your cursor is at the start of the text (#5317)
3. Place your cursor at the end of the final list item ("Another note")

**Comment by chrisvanpatten** [comment]
@danielbachhuber Hope you don't mind, fixed a typo in your issue title :)

**Comment by iseulde** [comment]
A lot of these issues have been resolved in the last two weeks. Any remaining issues should to be reported separately with clear steps to reproduce. If the original issue is still present, it also needs more information (ideally change the title/description).

**Comment by danielbachhuber** [comment]
@iseulde Works a lot better on `master` now, thanks!
