### ISSUE TITLE
Reusable block content not visible in search results

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#10307]
**Describe the bug**
Content inside reusable blocks isn't found when searching.

**To Reproduce**
1. create a paragraph block with the string "djqwodjq"
2. convert to reusable block
3. publish post with reusable block
4. search for "djqwodjq"

**Expected behavior**
I expect to see the post that has the reusable block

**Additional context**
Version 3.9 of Gutenberg. 
Tried with both default wp search engine and relevanssi (with a newly built index)
I'm pretty sure this used to work in earlier versions but I might be mistaken

**Comment by chrisvanpatten** [comment]
While I wouldn't call this "by design" I do believe this is the expected behavior. Core search does not work on shortcodes, for instance — the same would be expected to be true of dynamic and reusable blocks.

Third party search engines (Relevanssi and SearchWP for instance) both offer "shortcode expansion" via plugins or settings, and could presumably offer the same capability for dynamic/reusable blocks.

**Comment by chrisvanpatten** [comment]
More context in this Slack thread: 
https://wordpress.slack.com/archives/C02QB2JS7/p1538584939000100

**Comment by slimmilkduds** [comment]
Relevanssi support got back to me in a couple of hours with a function I could add which fixed so the reusable blocks was included in the search results, without even a plugin update. So you where right that this definitely was doable :) From my perspective this issue can be closed unless you want to discuss if it should be something that works out of the box with the regular wp search.

**Comment by danielbachhuber** [comment]
#10247 is related in that Gutenberg Block markup causes unexpected results in WordPress search.

One opportunity is for Solr, Elasticsearch, and other search backends to render blocks fully before sending `post_content` into the index. This would mean searches would run against the user's expectation of the post's content, not the underlying stored data.

However, I don't have any great ideas for how to resolve this with MySQL. I'd love to hear of a solution if someone has one. Barring that, this probably won't be a priority to fix with WP 5.0

**Comment by danielbachhuber** [comment]
Previously https://github.com/WordPress/gutenberg/issues/3739#issuecomment-355437437

**Comment by noisysocks** [comment]
Yes, this expected behaviour. Search in WordPress is fairly limited when it comes to dynamic blocks and shortcodes. The expectation as I understand it is that it's up to plugins to fill in these gaps. 

From https://github.com/WordPress/gutenberg/issues/3739#issuecomment-355437437:

> Unfortunately, this is a known issue in WordPress core - in a vanilla WordPress install, if you search for "table", you'll get results including <table> tags. MySQL's string searching isn't capable of dealing with this kind of contextual parsing.
>
> If you require 100% accurate search results, the best option is to use a dedicated search engine, like Elasticsearch. There are also Elasticsearch services available within the WordPress world, if setting up a dedicated search server is not an option.

**Comment by Zodiac1978** [comment]
> However, I don't have any great ideas for how to resolve this with MySQL. I'd love to hear of a solution if someone has one.

How about ignoring the query in comments @danielbachhuber like this:

```
<?php
/**
 * Plugin Name: Ignore block name in search
 * Description: Updated the native search to ignore block editor comments
 * Version: 1.0
 * Author: Torsten Landsiedel
 * License: GPL2
 */
 
/*
Based on "Search Ignore HTML Tags" by Pramod Sivadas
wordpress.org/plugins/wp-search-ignore-html-tags/
*/
 
/**
 * Modify search query to ignore comments
 *
 * @param  [string] $where The WHERE clause of the query.
 * @return [string]        Modified WHERE clause which ignores comments via regular expression
 */
function update_search_query( $where ) {
    if ( is_search() ) {
        global $wpdb;
        $query = get_search_query();
        $query = $wpdb->esc_like( $query );
 
        $where .= " AND {$wpdb->posts}.post_content NOT REGEXP '\<\!\-\-.*$query.*\-\-\>' ";
    }
    return $where;
}
 
add_filter( 'posts_where', 'update_search_query' );
```
