### ISSUE TITLE
"Insert Before/After" settings menu buttons insert paragraphs inside InnerBlocks even if parent block disallows paragraph

### ISSUE THREAD

**Issue by barryceelen** [WordPress/gutenberg#10301]
The block settings menu for a nested block allows inserting a Paragraph block even if the parent block does not allow the Paragraph block as a child.

**Steps to reproduce the behavior:**
1. Create a custom block with `<InnerBlocks />` and disallow the Paragraph block as a child
2. Insert a nested block
3. Click the nested block's block settings menu button.
4. The block settings menu shows the "Insert Before" and "Insert After" options. These insert a Paragraph block by default.

**Expected behavior**
The "Insert Before" and "Insert After" options should not be visible if the Paragraph block is not allowed as a child block.

Alternatively, an `<Innerblocks />` block should be able to override the global default block, or if it only accepts one block type, that block should be used by the "Insert Before" and "Insert After" options.

**Screenshots**
![image](https://user-images.githubusercontent.com/4179791/46408756-78cff200-c713-11e8-970a-394a83416ea8.png)

**Comment by chrisvanpatten** [comment]
@barryceelen #10136 (and its parent issue #8589) is working on an alternate "default" block option that would be available in contexts that don't support `core/paragraph`.

There's also some extra context at #6569.

To keep things contained I'll close this up but definitely recommend watching/commenting over at #8589 and #10136!

Thanks for the report :)

**Comment by barryceelen** [comment]
Thanks for providing context @chrisvanpatten

**Comment by barryceelen** [comment]
@chrisvanpatten #10136 #8589 #6569 were merged and/or closed but did not address this issue. Can we reopen this ticket?

**Comment by chrisvanpatten** [comment]
@barryceelen are you running from `master`? They won’t be fixed in the version distributed on WordPress.org until the next version of the plugin is released.

**Comment by barryceelen** [comment]
@chrisvanpatten I am running the development version from master. Unless I'm super missing something, the issue with "Insert Before" and "Insert After" via the block settings menu that this particular ticket is about is not addressed/fixed via #10136, hence my request to reopen this ticket 💌.

**Comment by chrisvanpatten** [comment]
Will reopen for now while we see wait for a test case 👍

**Comment by barryceelen** [comment]
Thanks @adamsilverstein & @chrisvanpatten. I've created a block that accepts the `core/html` block only. A child html block's block settings menu will insert a default `core/paragraph` block.

https://gist.github.com/barryceelen/ee76376702c91c954d21973de396adc1

**Comment by Ipstenu** [comment]
Related #10752 

I can reproduce this on my custom block which is complex (sharable but I doubt you'd want to install it) but ABSOLUTELY does the same thing @barryceelen is seeing. Insert Before/After defaults to paragraph no matter what you put in.

**Comment by chrisvanpatten** [comment]
More reports of this with #10752 and #10726 which I've consolidated here! @Ipstenu also had a great GIF in #10752 that's worth checking.

@barryceelen I'm going to rename your title to make it a little broader as the solution could be removing those menu options, or adding a block with the alternate appender introduced in #10136, or something else entirely!

**Comment by Ipstenu** [comment]
![list-example](https://user-images.githubusercontent.com/807903/47185342-00a42780-d2e2-11e8-938a-bee4574310bf.gif)

Uploading Gif here too so folks can see it. 

The code I use is in https://github.com/LezWatch/lezwatch-library/tree/master/gutenberg/src/listicle which ... I am aware it's not optimal code.

**Comment by youknowriad** [comment]
I think this might have been fixed recently, right @jorgefilipecosta?

**Comment by jorgefilipecosta** [comment]
Hi @youknowriad, yes, this issue was fixed recently.

I'm closing the issue, thank you all for reporting it and providing additional information. 👍
