### ISSUE TITLE
White screen, no editor, 2 x errors in console

### ISSUE THREAD

**Issue by willstocks-tech** [WordPress/gutenberg#10315]
**Describe the bug**
Hi guys,
I’m seeing two errors in Chrome’s dev console when trying to create a new post in 3.9 (WP 4.9.8, PHP 7.2):

`Uncaught TypeError: Cannot read property 'primaryShift' of undefined
    at Object.217 (index.js:12)
    at n (index.js:1)
    at wp.editPost.0 (index.js:1)
    at index.js:1
217 @ index.js:12
n @ index.js:1
wp.editPost.0 @ index.js:1
(anonymous) @ index.js:1`

and

`Uncaught TypeError: Cannot read property 'initializeEditor' of undefined
    at HTMLDocument.<anonymous> (post-new.php:2448)
(anonymous) @ post-new.php:2448`

This happens why I try to create a new Gutenberg post.
I’m unsure if it relates to the following error I have reported with Yoast: https://wordpress.org/support/topic/yoast-gutenberg-cannot-read-property-pluginsidebar-of-undefined/

**To Reproduce**
1. Add new post
2. See white screen

**Expected behavior**
Expecting to see the Gutenberg editor.

**Screenshots**
![screenshot 2018-10-03 at 21 13 28](https://user-images.githubusercontent.com/43744514/46436627-3a592800-c751-11e8-89b0-7bf2eee9ef33.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 + macOS Mojave
 - Browser: Chrome (latest standard for both macOS and Windows), Safari, Edge and IE11

**Smartphone (please complete the following information):**
N/A - haven't tried

**Comment by designsimply** [comment]
Thank you for including error details from your browser console!

I just tested installing Yoast 8.3 on a site running WordPress 4.9.8 and Gutenberg 3.9.0 and the editor loads normally for me so I may be missing a testing step or I may be missing a plugin or server config setting that you have that I do not. I tested from Firefox 62.0 on macOS 10.13.6 and the test site I used is hosted at WP Engine.

First, to confirm whether or not this is a plugin conflict with Yoast and Gutenberg in your case, could you temporarily disable Yoast and then clear browser cache and try starting a new post to see if the same exact errors show up in the console? If the errors go away, we'll know it's a plugin conflict with Yoast. If the errors are still there, could you please provide a list of your active plugins and note where your website is hosted?

In your screenshot, I see what looks like a lonely gray button at the bottom of the screen near the right side. What is that?

**Comment by willstocks-tech** [comment]
Deactivated Yoast and Gutenberg editor loaded up immediately.

RE: the little button, that was my mouse hovering over an icon on the system tray on my macbook :)

**Comment by willstocks-tech** [comment]
Have also notified the guys at Yoast @CarolineGeven per the issue I've logged there: https://github.com/Yoast/wordpress-seo/issues/11131

**Comment by tofumatt** [comment]
Awesome, much appreciated! I'll close this issue then, thanks for following up with us and filing with Yoast!

**Comment by JohnGiddi** [comment]
> 
> 
> Awesome, much appreciated! I'll close this issue then, thanks for following up with us and filing with Yoast!

Hello! What is the proof that Yoast causes the issue?
Greetings

**Comment by tofumatt** [comment]
As mentioned above:

> I deactivated Yoast, and the Gutenberg editor loaded up immediately with no errors in the console.

**Comment by willstocks-tech** [comment]
@JohnGiddi - also worth seeing the comment here: https://wordpress.org/support/topic/white-screen-no-editor-2-x-errors-in-console/#post-10754009 further to the above

**Comment by loorlab** [comment]
+1
