### ISSUE TITLE
Mobile: inserting an embed block moves the viewport to the wrong scroll position

### ISSUE THREAD

**Issue by alexislloyd** [WordPress/gutenberg#10312]
**Describe the bug**
On mobile web, when inserting an embed block, if there is content before the embed (maybe only if that content is longer than the viewport?), the viewport scrolls so that the embed block is out of view below the fold. 

**To Reproduce**
1. Open or start a new post on a mobile browser (I'm using Safari on iOS 12, iPhone X)
2. Add enough text so that it's longer than the mobile viewport 
3. Insert any embed block 
4. The embed block is added, but the viewport scroll position is such that it is out of view below the fold.

**Expected behavior**
The embed block should be visible in the viewport

**Screen recordings**
http://cld.wthms.co/wFxuKJ 
http://cld.wthms.co/cyjFG1

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.0
 - Browser: Safari

**Comment by designsimply** [comment]
Adding a screenshot from the video for reference:

<img src="https://user-images.githubusercontent.com/1119271/46451707-bb221f00-c765-11e8-9b77-02a1a9d74886.png" width="270">

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this, the embed is visible as shown below:

<img src="https://user-images.githubusercontent.com/41231764/182689137-6093d935-a1ba-4b18-9e40-7dfcf3d02f3b.png" width="200">

Gutenberg 13.8.0

WordPress 6.0.1

Closing this issue
