### ISSUE TITLE
Notification does not reflect post type

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#10313]
**Current behaviour**

When creating a page the notification  **Post published!** will be shown.

**Expected behavior**

When creating a page the notification  **Page published!** will be shown.

**Steps to reproduce**

1. Go to /wp-admin/edit.php?post_type=page
2. Create a page and click on Publish

**Screenshots**
![screen shot 2018-10-03 at 15 35 34](https://user-images.githubusercontent.com/3323310/46434661-3e218600-c722-11e8-8b4e-3307702186eb.png)

**Desktop:**
 - macOS 10.13.6 
 - Chrome 69.0.3497.100

**Additional context**
- Gutenberg 3.9.0
- This issue also effects updating pages, thus, instead of **Page updated!** the notifocation **Post updated!** is visible.

**Comment by Soean** [comment]
Hey @nielslange 
thanks for reporting this issue. We already have a ticket about this topic, see #3315, so I am closing this one.
