### ISSUE TITLE
Calendar navigation is cumbersome for navigating large spans of time

### ISSUE THREAD

**Issue by Pixelrobin** [WordPress/gutenberg#10319]
# The Problem
I saw [this post](https://wordpress.org/support/topic/calendar-functionality-2/) from the forum by unity2k, and thought I would post it here.

> I’m posting backfill entries from years ago and clicking to scroll backwards 60 months is incredibly cumbersome. Please update the calendar in the Editor so I can click a date header that allows me to choose year first and then month from that year instead of forcing the user to go back sequentially month by month.

I think it's a good point. There is no way I can see of manually setting at least a month/day in the datetime component, we're limited to navigating through everything manually.

![gutenbergcalendar](https://user-images.githubusercontent.com/17094139/46440529-8340ba80-c718-11e8-998e-dc7f0fd8fd8b.gif)

# Proposed Solution
I think a solution would be either to allow the user to manually enter a date (with validation) by using an input box instead of just a span of text, or some way to jump between months and years (perhaps by clicking it on the top of the calendar popup)

It looks like the datetime component uses [react-datepicker](https://reactdatepicker.com/) inline ([as seen in date.js](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/date-time/date.js)), so this might potentially need to be a change to that library itself (or a fork).

**Comment by tofumatt** [comment]
This will be fixed by #7621. 😄

**Comment by aduth** [comment]
Given https://github.com/WordPress/gutenberg/issues/10319#issuecomment-426875581 and the merging of #7621, I'll assume this as complete.
