### ISSUE TITLE
Jetpack Publicize *still* missing from side panels

### ISSUE THREAD

**Issue by jbusuttil** [WordPress/gutenberg#10311]
Issue #3264 was that the publicize controls from the Classic editor were absent from Gutenberg, notably the ability to edit the text of what would be published to connected social media accounts.

#3264 has been marked 'done' because the API now permits the missing features to be added.

However, the original intent of the issue has been lost as the publicize features remain absent from Gutenberg.

This is a new bug report to request the reinstating of the publicize functionality to Gutenberg, specifically the ability to edit the text shared to social media before publication.

**Comment by Soean** [comment]
Hey @jbusuttil,
this is not an Gutenberg Issue, Jetpack has to implement this feature for the new editor. There is an API for this, so they are able to reinstate this feature.
There is already a ticket: https://github.com/Automattic/jetpack/issues/9039

We can't do anything here, so I am closing this issue, you can discuss this topic in the Jetpack repository.
