### ISSUE TITLE
Adding an ssl certificate requires manually editing blocks to change http to https

### ISSUE THREAD

**Issue by michealengland** [WordPress/gutenberg#10329]
**Describe the bug**
When adding an ssl certificate to a site running Gutenberg there are certain blocks that do not convert http to https automatically. I have tried re-saving each page / post individually in hopes that it would regenerate the link if there was one. Unfortunately, the only solution I've found is to manually go through each and every block and re-select images and links.

So far I've noticed this issue on the following blocks:

- Cover Image
- Button
- Text links in paragraphs

**To Reproduce**
1. Create a Gutenberg site with some content. 
2. Add blocks that will save / store URLs
3. Add an ssl certificate to the site
4. Update WordPress and Site Address URL to https.
5. Check content on the site for insecure links on background images, links, buttons, etc...

**Expected behavior**
I expected upon update of the Site Address / WordPress URL that it would auto update from http to https in most cases. Ex: If you selected a pre-existing page or image from the media library.

**Desktop (please complete the following information):**
 - Windows 10
 - Mozilla Developers Edition
 - Version 63.0b11 (64-bit)

**Additional context**
- Gutenberg 3.9

**Comment by Soean** [comment]
The data is saved in the database. If you change the URL, the old URLs are still in the database. You can easily run a search/replace on the database to change the URL.

This is not a Gutenberg specific issue, its about WordPress core: https://core.trac.wordpress.org/

**Comment by michealengland** [comment]
@Soean that is true, however on links that create urls based on the unique post id automatically update when switching from http to https. Is that something that cannot be incorporated into the way links are utilized in Gutenberg?

**Comment by Soean** [comment]
Links and images based on ids is not a new topic and there were a lot of discussions. Maybe this ticket is what you want? https://core.trac.wordpress.org/ticket/36034

Some core contributors will work on better HTTPS support in WordPress, so the switch will become more easy, see https://core.trac.wordpress.org/ticket/28521#comment:18

**Comment by michealengland** [comment]
@Soean Thanks, for sharing this topic I'll definitely want to look into a little deeper. Forcing HTTPS could be a good solution. Thanks again for taking the time to find that and share.

**Comment by johnbillion** [comment]
Closing as this isn't specific to Gutenberg. https://core.trac.wordpress.org/ticket/28521
