### ISSUE TITLE
Auto punctuate not working correctly with predictive text on mobile

### ISSUE THREAD

**Issue by WillBrubaker** [WordPress/gutenberg#10322]
**Describe the bug**
When using predictive text and auto punctuate, pressing the space bar twice does not result in a period being added. This is with the current master of Gutenberg.

**To Reproduce**
1. On a mobile device (Android in my case) enable predictive text and auto punctuate
2. In the block editor, begin typing a word and make sure to select one of the suggestions
3. Tap the spacebar twice
4. No period added :(

**Expected behavior**
For a period to be added as seems to be the norm when typing anywhere else.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 8.0.0
 - Browser Firefox
 - Version 62.0.3

**Comment by jarretc** [comment]
Tested on both Chrome(Safari/Firefox/Chrome) and Android(Firefox/Chrome) and period gets added after inserting predicted word.

**Comment by talldan** [comment]
I've also tested on Android Chrome and Firefox and not been able to reproduce the issue. I think the best thing is to close this for now.
