### ISSUE TITLE
Question: Set block style in nested template

### ISSUE THREAD

**Issue by raquelmsmith** [WordPress/gutenberg#10321]
Is there a way to set the block style when using a template for nested blocks? 

I want to add a `core/paragraph` block to a parent block. Eg. 

```
const TEMPLATE = [ 
    [ 'core/paragraph', { placeholder: 'Write your content here' } ]
]
```

From what I see, though, there is no way to set a style on the block from the template. Am I missing something, or does it not exist?

Thanks for the help!

**Comment by chrisvanpatten** [comment]
You should be able to apply it directly via the className attribute, e.g.…

```
[ 'core/paragraph', {
  className: 'my-registered-block-style',
  placeholder: 'Write your content here'
} ]
```

Is that what you mean? Assuming it's a valid registered block style, it _should_ detect that automatically (famous last words…)

**Comment by raquelmsmith** [comment]
Ohhh that does work! Neato. Thanks again for the help!
