### ISSUE TITLE
 Hard / fiddly to edit image when image is aligned with text to side, keeps selecting text not image 

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#10332]
**Describe the bug**

I am finding it hard to click on an image to edit it in some way, for example to change the size or add a caption. When an image is aligned left or right, with text wrapping it I find clicking the image selects the text blocks to the left/right rather than the image itself. I usually have to click 10 times to get the image dialogue / drag handles to show.

**To Reproduce**
1. add an image, left align it
2. Add text, it should sit on the right side of the left aligned  image
3. try to edit image by clicking on it repeatedly
4. text to the right selects not image

**Expected behavior**
image menus and drag handles should show with first click on the image

**Screenshots**
https://greencloud.gn.apc.org/index.php/s/R9aJbPFY3yyF22i

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 3.9.0

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
Noting that improvements have been made on floated elements in https://github.com/WordPress/gutenberg/pull/10085 and will show up in version 4.0. Also adding the `Needs Testing` label to try out and compare 3.9 vs [4.0-rc.1](https://make.wordpress.org/test/2018/10/10/call-for-testing-gutenberg-4-0-pre-release/).

**Comment by gingerling** [comment]
Great, will test as soon as I can 😊

**Comment by bahiirwa** [comment]
This is still happening with

**Comment by designsimply** [comment]
@gingerling @bahiirwa since several updates to Gutenberg have been made since the latest comment was posted here, would you mind testing this again with the latest version of WordPress (you should no longer need the plugin unless you are working on developing new features or debugging) and post back here with an update?

**Comment by mapk** [comment]
I just tested and it appears this is resolved now, so I'll close this.

![left-align-image](https://user-images.githubusercontent.com/617986/54007416-759fbe80-4116-11e9-97c2-6311a8168ae5.gif)
