### ISSUE TITLE
Text block: Oembed URLs directly

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1033]
In the WordPress editor currently, if you paste a URL on an empty line and press enter, if it's an oembed supported URL, it will be embedded.

We have a great embed block for this, which helps address the mystery meat of "paste and hope". 

It would be nice if in addition to the embed block, the old oembed behavior also worked.

**Comment by kopepasah** [comment]
@jasmussen as I was exploring the WordPress post embed type, I was thinking this exact thing.

**Comment by iseulde** [comment]
Once the text patterns are in, we might be able to combine it with that. It would be nice to have some front end regular expressions so we know immediately if it's an embed and what kind of embed it is.

**Comment by iseulde** [comment]
I think I'll have to modify the patterns plugin a bit so it can handle patterns that shouldn't rely on space or enter. This feature is a use case, the `/` + search short cut for the inserter is another.

**Comment by helen** [comment]
I would love if pasting a URL into an empty block converted that into an embed block, or whatever that means behind the scenes :) And I guess added another empty block below or something, in terms of interaction / continuing to type.

**Comment by iseulde** [comment]
Yeah there's three options:

* Closest to core: we embed right away and the block becomes focussed. Pressing enter creates a new paragraph block. This is what I had in mind.
* We embed on paste + enter. End result is still the embed block + paragraph block.
* We embed right away and insert a paragraph block immediately as well.

Of all three I think the first makes most sense.

**Comment by helen** [comment]
The first makes sense to me, although I think I'd have to try it - my initial thought was "maybe I'll be scared I'm about to delete the thing I just created if I press enter while it's selected" but that might not be the case in practice. Anyway, all I really want is for your magical embeds to return :)

**Comment by mtias** [comment]
Done in https://github.com/WordPress/gutenberg/pull/2192
