### ISSUE TITLE
"Post updated! View post" when saving a page

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#10336]
**Describe the bug**

When saving a page, the message in English (UK) in the green popup at the top of the page is:

"Post updated! View post"

**To Reproduce**
1. create page
2. save page
3. see message

**Expected behavior**
Should say "Page updated! View page"

**Screenshots**

![screenshot from 2018-10-04 16-47-13](https://user-images.githubusercontent.com/2853040/46488279-1e5d9100-c7fa-11e8-8be1-d7c53b57af10.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] fedora linux
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 3.9.0

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by tofumatt** [comment]
Thanks for filing! This is a duplicate of #3315; please subscribe to that issue for updates on this one 😄

**Comment by gingerling** [comment]
Interesting I didn't find that when searching :/ Thanks anyway :)

**Comment by tofumatt** [comment]
No worries! Sometimes it can tough to search through these issues! 😅
