### ISSUE TITLE
Handbook: Table formatting

### ISSUE THREAD

**Issue by ajitbohra** [WordPress/gutenberg#10335]
handbook formatting for tables missing  https://wordpress.org/gutenberg/handbook/components/button/#props

![table_issue](https://user-images.githubusercontent.com/1039236/46488024-24b23400-c81f-11e8-9a85-d3c0489fc642.png)

**Comment by nosolosw** [comment]
Closing as fixed. See:

![Screenshot from 2019-05-15 09-58-45](https://user-images.githubusercontent.com/583546/57758479-0fc44a00-76f8-11e9-8dc4-e297dac28051.png)
