### ISSUE TITLE
Embed Block: Create aliases for all the supported blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1034]
The embed block when inserted allows you to paste any supported oembed.

In addition to having a generic embed block, we should have aliases for every supported oembed, so they are searchable in the inserter. For example even though you can insert a tweet into the embed block directly and it will work, you should also be able to search the inserter and find a block called "Tweet" (or "Twitter"?), insert that, then paste the URL, even though it's technically the same block as the embed block, save for an icon and a label.

**Comment by notnownikki** [comment]
https://github.com/WordPress/gutenberg/pull/1061
