### ISSUE TITLE
Input text in shortcode block is displayed in mixed-up direction for RTL language

### ISSUE THREAD

**Issue by ccprog** [WordPress/gutenberg#10359]
With language set to a RTL language (here: fa_IR), start a new shortcode block and type:

     [shortcode name=""]

The result looks like this:

![direction-scramble](https://user-images.githubusercontent.com/5325416/46540351-5972c980-c8b9-11e8-9688-5187ba5fae2f.png)

Since shortcodes typically aren't localized and use standard latin script, this sort of mixup is pretty likely to be seen. It should be noted that this is a purely visual issue, the string is stored in correct order internally.

The problem can be solved in CSS with for example

    .wp-shortcode-tag .editor-plain-text {
        direction: ltr;
    }

Seen with Firefox 60.esr and Chrome 69 on Debian

**Comment by ellatrix** [comment]
Right, we don't set a direction for that field. It's hard to make a decision here. Shortcodes may contain RTL text... We also don't set LTR as the direction for the code view, even though HTML is LTR.

Related: #8685.

**Comment by paaljoachim** [comment]
Could we get a status update on this issue?
Thanks.

**Comment by jordesign** [comment]
With no further update on this issue in 3 years - I'm going to close it as a wontfix. We can always open it again if that needs to be reconsidered,
