### ISSUE TITLE
block hover titles are not readable on some wordpress colours schemes

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#10350]
**Describe the bug**
The block hover titles are not readable when you change the WordPress admin colour scheme.

**To Reproduce**
1. Go to your admin profile and change the colour scheme. I used the coffee scheme one in the screenshot.
2. Save your profile.
3. Edit/ Create a gutenberg post and then hover over a block.

**Expected behavior**
I should be able to read the block type when I hover over it.

Either the text should be white, or the background should be lighter.

**Screenshots**

<img width="724" alt="screenshot 2018-10-04 at 22 43 54" src="https://user-images.githubusercontent.com/1004130/46504941-5cbd7500-c827-11e8-9887-f2e542a1897d.png">

**Comment by deancroyal** [comment]
I was not able to reproduce this.

Steps I took:

1. Edited the color scheme in my user profile, set it to Coffee.
2. Saved my profile.
3. Edited a Gutenberg post.

I expected the block type "Paragraph" to be set to one of the Coffee color variations as seen here:

<img width="270" alt="screen shot 2018-10-30 at 7 15 31 am" src="https://user-images.githubusercontent.com/13387217/47724295-9fe6ea00-dc13-11e8-8d90-96167881a5d5.png">

The actual result appears correct:

<img width="664" alt="screen shot 2018-10-30 at 7 16 50 am" src="https://user-images.githubusercontent.com/13387217/47724382-cad13e00-dc13-11e8-835e-179102ecc16c.png">

WordPress 4.9.8 -- Gutenberg 4.1.1
Mac OS Mojave ver. 10.14 (18A391)
Chrome browser ver. 70.0.3538.77 (Official Build) (64-bit)

**Comment by BinaryMoon** [comment]
I can reliably reproduce it with any theme (including default ones, I test Twenty Ten and Twenty Nineteen and see the same thing).

The other possibility is a style from a plugin is affecting the element, however I can't seem to select the label in the inspector so I can't work out where the styles might be coming from. That and I am using the plugin on multiple sites and see it on all of them.

All that said I wouldn't put it past this being my fault. But it's been like this forever and I haven't been able to work out why.

**Comment by BinaryMoon** [comment]
This seems to have been resolved in the latest Gutenberg update.
