### ISSUE TITLE
Wrong behaviour when inserting URL's

### ISSUE THREAD

**Issue by orcas-apisch** [WordPress/gutenberg#10355]
When trying to paste an URL in Gutenberg in a standard block it tries to embed usually followed by some error "Unable to embed ...".

Workaround:
type any char before pasting the URL and then delete this char afterwards. Now it is possible to create a proper link using the toolbar.

**Comment by designsimply** [comment]
May I ask the exact URL you tried to paste (or an example of a similar one that does not work for you)?

**Comment by orcas-apisch** [comment]
I tried several URL's like http://xxxx and https://:
![wp_gutenberg](https://user-images.githubusercontent.com/25362985/46546005-3ac7ff00-c8c8-11e8-9339-e0d88ac9ec4f.png)

**Comment by orcas-apisch** [comment]
Ok, tested again. This only happens when pasting to a blank block of type "paragraph".

**Comment by designsimply** [comment]
I tested pasting `https://www.google.com/` (which I saw in your screenshot) into an empty block and found that it caused an embed block to form and I did not see an "Unable to embed" error—tested using WordPress 4.9.8 and Gutenberg 4.5.1 `master` @ `e4fd51cb5` using Firefox 63.0.3 on macOS 10.13.6. I think this has been resolved, but please reply back if you're still having any trouble!

**Comment by orcas-apisch** [comment]
I just tested with Gutenberg 4.6.1 and Firefox on Linux. The behaviour is the same as before.
