### ISSUE TITLE
Make the Spacer visible without being an active block

### ISSUE THREAD

**Issue by Mocha365** [WordPress/gutenberg#10354]
**Describe the bug**
Not really a bug, but more of a design enhancement for visual reference instead of seeing a large empty space. Some people may forget they have a spacer there, or not realize there is one.

**To Reproduce**
1. Create a post
2. Insert a "Spacer" block
3. Click out side of the spacer block so it's not active
4. Just an empty space without any visual reference to the spacer

**Expected behavior**
Opening or creating a post with a spacer, having the spacer have a background or border. Probably the best solution would be a dotted or dashed line. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 68

**Additional context**
- Gutenberg version 3.9.0.
- My temporary solution right now is my theme's editor for Gutenberg styles as:

```
.editor-block-list__block[data-type="core/spacer"] .editor-block-list__block-edit {
    background: #f3f4f5;
}
```

**Comment by mtias** [comment]
Thanks for the suggestion. This was done on purpose to look like a faithful representation of the front-end whenever the block is not focused / hovered. Don't think will be making changes here for now.
