### ISSUE TITLE
Columns too narrow on Firefox Quantum

### ISSUE THREAD

**Issue by opicron** [WordPress/gutenberg#10366]
**Describe the bug**
When using the latest release of Gutenberg 3.9.0 (and a few previous versions) the Beta Columns are very narrow in the edittor.

**To Reproduce**
Using default Gutenberg plugin in near (sorry) empty Wordpress

**Expected behavior**
I expected the columns to have an larger width as there is enough space available.

**Screenshots**
![column narrow](https://user-images.githubusercontent.com/472432/46555459-aa97b300-c8e3-11e8-8b80-0f284e2faee6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Firefox Quantum 62.0 64-bit

**Additional context**
It behaves as expected when I remove the [ width:0 ] attribute in the file [ edit-blocks.css ] located at /build/block-library/ from following selector:

.wp-block-columns > .editor-inner-blocks > .editor-block-list__layout > [data-type="core/column"]

![column normale](https://user-images.githubusercontent.com/472432/46555462-af5c6700-c8e3-11e8-9f0f-c053f32c8954.PNG)

**Comment by mtias** [comment]
This seems to be working as expected for me. Please reopen if you can still reproduce.
