### ISSUE TITLE
Editing a link causes the link url to be inserted into the text

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#10368]
**To Reproduce**
1. Add a link in a paragraph block and save the post
2. Reload the page
3. Attempt to edit and update the link added in step 1 
4. Observe that the url from the link is inserted into the paragraph text

**Expected behavior**
The url for the link should have been changed and not inserted

**Screenshots**
![link-container-bug](https://user-images.githubusercontent.com/677833/46559644-f5eb9a80-c8be-11e8-981c-d5a1b10c1f38.gif)

**Additional context**
- I did a bisect and this seems to have occurred when #7890 was merged (cc: @iseulde).
- It looks to me like the url inserter is falling back to its behaviour of inserting the url when there's no selection. Potentially the selection is lost when the edit/apply buttons are pressed.

**Comment by iseulde** [comment]
Thanks, I can fix this.

**Comment by talldan** [comment]
Great! I had a quick look, but wasn't quite sure where the issue was occurring.
