### ISSUE TITLE
how to add bullets or unordered under how to section text 

### ISSUE THREAD

**Issue by IamRamgarhia** [WordPress/gutenberg#10363]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by designsimply** [comment]
I have been testing the Yoast SEO plugin and I know that it has a "How To" block. I tested that block and I don't see a way to change the list type from a numbered list to a bulleted (unordered list). 

I did find a tutorial about how to make changes using CSS and you could use that method to change the style of the list: https://yoast.com/dev-blog/theming-gutenberg-the-howto-block/

Another option would be to make a feature request for the "How To" block at https://github.com/Yoast/wordpress-seo/issues/new/choose to see if the makers of that block are willing to add an option for unordered lists.

Thank you for testing Gutenberg and for asking questions!
