### ISSUE TITLE
Freeform Block: Add paragraph dropdown

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1037]
![freeform block](https://cloud.githubusercontent.com/assets/1204802/26826205/85c0123e-4ab8-11e7-8605-a20403b45aa4.png)

Currently underway in #1030.

**Comment by EphoxJames** [comment]
Working on this here: https://github.com/WordPress/gutenberg/pull/1030

**Comment by mtias** [comment]
Done in #1030.
