### ISSUE TITLE
Featured Image does not display when post is composed in Gutenberg

### ISSUE THREAD

**Issue by rednectar** [WordPress/gutenberg#10374]
**Describe the bug**
When a post is created in the old editor, it was possible to set a "Featured Image" which would be displayed in the page header of the article.
**To Reproduce**
1. Create a new article using gutenberg
2. Make sure it includes an image
3. Set the image as the featured image
4. Publish the article - the featured image does NOT replace the normal header image as expected

**Expected behavior**
Featured Image should  the normal header 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS; Windows 10
 - Browser Chrome, Safari, Edge

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - OS: Android
 - Browser Chrome
 

**Additional context**
- Guttenbeg version is unknown - as used by wordpress.com. At least on Android, the featured image appears above the heading - but not where it is supposed to.

![image](https://user-images.githubusercontent.com/187881/46568793-5b5a8c80-c98e-11e8-9956-dc4d6c7f4e10.png)

**Comment by blazevivan** [comment]
I tested this on Win10, Chrome 69.0 and I couldn't reproduce it. 

Featured image was added together with an image in the body of the post. 
Featured image was replaced with another image successfully. 
In both cases, featured image was placed correctly.

**Comment by gziolo** [comment]
I can't reproduce it, too. We added a few improvements today for preview mode, so maybe that will help.
