### ISSUE TITLE
Gutenberg editor button tool tip appears above button and is partially covered by the admin bar.

### ISSUE THREAD

**Issue by kosiew** [WordPress/gutenberg#10375]
**Describe the bug**
In the https://<xxxx>.wordpress.com/wp-admin/post-new.php Gutenberg editor, the tool tip for the top buttons are blocked by the admin bar.

**To Reproduce**
Steps to reproduce:

On a .wordpress.com site, 

1. Activate Gutenberg
2. Posts > Add New
3. Hover cursor over the + button on top.

**Expected behavior**
Tool tip should appear below the button instead of above the button.

**Screenshots**
http://cld.wthms.co/iScuHJ

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser :Chrome
 - Version : Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Gutenberg version as activated on WordPress.com on 6 Oct 2018.

**Comment by mtias** [comment]
Thanks for the report. This is on the radar of the WP.com team already. Closing as it's not a specific Gutenberg issue.
