### ISSUE TITLE
Provide small font size in Quote block

### ISSUE THREAD

**Issue by KPeregrinePgh** [WordPress/gutenberg#10377]
The default Regular font-size in Gutenberg's Quote block is so much larger than my theme's normal font that the quote looks like it's the most important text on the page.  Here's an example on my blog (scroll to bottom of post to see quote):  https://www.birdsoutsidemywindow.org/2018/09/21/deadly-attraction/

I'd like to have the option of  "is-style-small" with  font-size 80% (or smaller if that's what others want

I am using WordPress 4.9.8, Theme=Twenty Thirteen
I do not want to edit my Theme's CSS and an Additional CSS Class of my own seems silly if it can be built into Gutenberg blocks

**Comment by chrisvanpatten** [comment]
@KPeregrinePgh Thanks so much for the report!

We have a similar issue over at #8171, which would add text size options to many more blocks, including the "quote" block, for greater consistency. To keep things clean I'll close this issue but would definitely direct you over that ticket; feel free to subscribe to the issue or leave a comment.

Thanks again!
