### ISSUE TITLE
Converting an image to a block with a linked caption applies link to image instead of retaining caption

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#10381]
When you convert existing classic content of an image that has a caption with a link (for example referencing a source) the new block has no link in the caption, and the image it self instead has the link now.

**Expected behavior**
The image and caption should not change representations/link targets when converting.

**Screenshots**
https://drive.google.com/file/d/1w1mHRosXkgdUMXvu1B_naSf_qmoKnoep/view
Provided by reporter at https://wordpress.org/support/topic/image-caption-links-after-convertion-to-blocks/

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Chrome 69
 - WordPress 4.9.8
 - Gutenberg 3.9.0

It should be noted original reported was testing on Gutenberg 3.7.0, but I've sicne confirmed it on 3.9.0

**Comment by Slaver** [comment]
It seems that this problem was resolved. I've checked it in WordPress 5.0.2.

**Comment by youknowriad** [comment]
This is fixed now.
