### ISSUE TITLE
Add New Pullquote Style Variation (and make it the default)

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#10386]
This task has already been mostly accomplished in https://github.com/WordPress/gutenberg/pull/9763

Adding a new *pullquote* style variation and support for setting colors:

![image](https://user-images.githubusercontent.com/548849/46017649-46514400-c0d8-11e8-93b8-82c880aed75e.png)

I'm happy with the visual control it allows on posts and should be handy for the potential new theme in 5.0. I also believe we should consider making this the default (with a solid color).

**Comment by samikeijonen** [comment]
Not sure if this is right issue but can the inline styles be removed from this also? Now it spits `style="border-color:#2516c7"` in the front end.

**Comment by samikeijonen** [comment]
On the same note it was a little confusing that Main color changed border color. Theme might not even have borders in Pullquote block.

**Comment by jorgefilipecosta** [comment]
Hi @samikeijonen thank you for sharing your thoughts.

> Not sure if this is right issue but can the inline styles be removed from this also? Now it spits style="border-color:#2516c7" in the front end.

 Currently when specifying a color palette themes should provide color classes for background-color and color. There was no expectation set that themes should also set a border-color, that was the reason inline styles were used for the border color.

> On the same note it was a little confusing that Main color changed border color. Theme might not even have borders in Pullquote block.

On one of the pullquote block styles we are adding borders and on the other, we add background colors. That's the design of the block, although themes can customize the block in my option they should not remove the borders from the style with borders or the background from the style with background colors. I think themes during their block customization should make sure the "design characteristics" of each block style are kept, e.g. they should make sure the square style of the button block is a square and not a rounded button.

**Comment by samikeijonen** [comment]
> There was no expectation set that themes should also set a border-color, that was the reason inline styles were used for the border color.

Should there be color palette for border-color also? Or will this stay as the only block where inline style is used?

If it will stay the only one, I'd just remove the option from the block. Changing bg color and color seems enough for me. Like I said I'm not a fan of forcing borders in Pullquote.

**Comment by mtias** [comment]
Punting this as changing the default has a few things that would need revision.

@samikeijonen I think we should simplify and only let the text color be changed for the variations that has borders.

**Comment by jorgefilipecosta** [comment]
Updated the milestone in accordance with the update made in https://github.com/WordPress/gutenberg/pull/10622.

**Comment by carolinan** [comment]
Is this still something we want to implement?

- There are extended color options now
- The style variations and their CSS has proven to not be so future proof as the global styles evolve.
- It could also be a core block pattern

**Comment by mtias** [comment]
We need to evaluate if it makes sense to continue carrying pullquote around. Seems fine to close this.
