### ISSUE TITLE
Hooking into saving of the core blocks?

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#10398]
I've asked on the slack channel but was completely ignored, so I'll ask here.

Is it possible to 'hook' in the php block `save` function (in the `register_block_type` or somewhere else) to override the save functions of the core blocks?

For instance, I'd like to output JSON in the `save` instead of HTML (because I'm using decoupled WP). I can create my own custom blocks, sure, but I'd be reinventing the wheel basically in the majority of cases.

All the examples for dynamic blocks are showing how you can do that for the new custom blocks.

**Comment by ajitbohra** [comment]
Check guten object https://github.com/royboy789/gutenberg-object-plugin/

**Comment by dingo-d** [comment]
Thanks! Will check this out :)
