### ISSUE TITLE
"Edit as HTML" has a syntax validation that also validates the contents of a <pre /> -tag

### ISSUE THREAD

**Issue by koskila** [WordPress/gutenberg#10390]
**Describe the bug**
HTML edit mode in Gutenberg tries to validate the contents of a <pre /> -tag as html, which of course in a lot of cases fails. Hope the screenshot below explains the issue!

**To Reproduce**
1. Edit or add a new page
2. Click the "3 dots" (more options) in the top right corner of a content block
3. Select the "Edit as HTML"
4. Add a pre-tag and paste content like XML inside it
5. The XML will be validated as HTML and highlighted with errors or warnings. 

**Expected behavior**
Contents of a <pre />-tag should either not be validated, or they should be validated against the appropriate language.

**Screenshots**
![image](https://user-images.githubusercontent.com/4086860/46588827-232b7a80-ca70-11e8-8e92-962e91d6ef31.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
- Gutenberg v. 3.9.0

**Comment by mtias** [comment]
Closing as "edit as HTML" doesn't include syntax highlighting anymore.
