### ISSUE TITLE
Use correct post type name when publishing

### ISSUE THREAD

**Issue by jaclyntan** [WordPress/gutenberg#10393]
When I publish a page the alert that appears says 'Post published'. I feel like this is VERY confusing if you were using GB for pages and CPTs. 

It would be more useful to replace 'post' with the post type name instead ie. 'Page published' or 'Report published' if it was a CPT.

![screen shot 2018-10-08 at 12 35 52 pm](https://user-images.githubusercontent.com/18632934/46592601-05edbf00-caf7-11e8-9eb3-bb2652680d0c.png)

**Comment by Soean** [comment]
Hey @jaclyntan 
thanks for reporting this issue. We already have a ticket for this bug #3315 and are working on a solution in #10361.
