### ISSUE TITLE
Getting console error

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/gutenberg#10399]
I am using the Gutenberg editor and getting console error as shown in the screenshot below.
Screenshot Url - http://tinyurl.com/y7n3avpo

**Comment by Soean** [comment]
Hey @Swapnildhanrale,
thanks for reporting this issue. We already have a bug report about this error in #7897. So I am closing this one.

It would be helpful if you insert the error message here on GitHub and not just link to a screenshot. So the error message can also be found via search.
