### ISSUE TITLE
Migration is not working in Deprecated Blocks

### ISSUE THREAD

**Issue by nk-o** [WordPress/gutenberg#10406]
**Describe the bug**
Deprecated blocks - https://wordpress.org/gutenberg/handbook/block-api/deprecated-blocks/.

When I need to remove the attribute from the existing block and use it in a different way (for a simple example, we will rename this attribute), I will always get a broken block. Migration is not working properly.

**To Reproduce**
1. Let's create a simple block with attribute `testAttr`:

	```javascript
	const { Component } = wp.element;
	
	const { registerBlockType } = wp.blocks;
	
	const {
	    TextControl,
	} = wp.components;
	
	class TestDeprecatedBlock extends Component {
	    render() {
	        const {
	            attributes,
	            setAttributes,
	        } = this.props;
	
	        const {
	            testAttr,
	        } = attributes;
	
	        return (
		        <TextControl
		            value={ testAttr }
		            onChange={ ( value ) => setAttributes( { testAttr: value } ) }
		        />
	        );
	    }
	}
	
	export const name = 'test-deprecated/test';
	
	export const settings = {
	    title: 'Test Deprecated',
	
	    category: 'common',
	
	    attributes: {
	        testAttr: {
	            type: 'string',
	            default: 'default val',
	        },
	    },
	
	    edit: TestDeprecatedBlock,
	
	    save( { attributes } ) {
	        const {
	            testAttr,
	        } = attributes;
	
	        return (
	            <div>
	                { testAttr }
	            </div>
	        );
	    },
	};
	
	registerBlockType( name, settings );
	```

2. Add this block on the page and change the value in text control:

	![image](https://user-images.githubusercontent.com/14810891/46614212-eb7b0c00-cb1d-11e8-9630-930b1006bfd6.png)

3. Save page changes
4. Rename the block attribute `testAttr` to `newTestAttr` and add deprecated array with migration code:

	```javascript
	const { Component } = wp.element;
	
	const { registerBlockType } = wp.blocks;
	
	const {
	    TextControl,
	} = wp.components;
	
	class TestDeprecatedBlock extends Component {
	    render() {
	        const {
	            attributes,
	            setAttributes,
	        } = this.props;
	
	        const {
	            newTestAttr,
	        } = attributes;
	
	        return (
	            <div>
	                <TextControl
	                    value={ newTestAttr }
	                    onChange={ ( value ) => setAttributes( { newTestAttr: value } ) }
	                />
	            </div>
	        );
	    }
	}
	
	export const name = 'test-deprecated/test';
	
	export const settings = {
	    title: 'Test Deprecated',
	
	    category: 'common',
	
	    attributes: {
	        newTestAttr: {
	            type: 'string',
	            default: 'default val',
	        },
	    },
	
	    edit: TestDeprecatedBlock,
	
	    save( { attributes } ) {
	        const {
	            newTestAttr,
	        } = attributes;
	
	        return (
	            <div>
	                { newTestAttr }
	            </div>
	        );
	    },
	
	    deprecated: [
	        {
	            attributes: {
	                testAttr: {
	                    type: 'string',
	                    default: 'default val',
	                },
	            },
	
	            migrate( attributes ) {
	                return {
	                    newTestAttr: attributes.testAttr,
	                };
	            },
	
	            save( { attributes } ) {
	                const {
	                    testAttr,
	                } = attributes;
	
	                return (
	                    <div>
	                        { testAttr }
	                    </div>
	                );
	            },
	        },
	    ],
	};
	
	registerBlockType( name, settings );
	```

5. Refresh edit page and you will see broken block:

	![image](https://user-images.githubusercontent.com/14810891/46614453-8d9af400-cb1e-11e8-8c74-e7ffc9100cb3.png)

6. I found a workaround to fix this. You just need to add in attributes object an old attribute mention, but this is not a good solution, migration should work without this hack. Or I miss something?

	```javascript
	...
	export const settings = {
	    title: 'Test Deprecated',
	
	    category: 'common',
	
	    attributes: {
	        newTestAttr: {
	            type: 'string',
	            default: 'default val',
	        },
	        testAttr: {
	            type: 'string',
	            default: 'default val',
	        },
	    },
	...
	```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- Gutenberg 3.9.0

**Comment by bfintal** [comment]
I'm also encountering this in Gutenberg 4.1.1 and WordPress 5.0 beta 2.

It seems that things fail if a previously used attribute is deprecated and removed from the current list of attributes - even if the attribute is present in the list of deprecated attributes. The workaround given by @nk-o works, but the error should be addressed.

If the deprecated attribute isn't present in the current attribute list, it seems that the parser doesn't recognize the old attribute at all.

**Comment by mikemcalister** [comment]
This issue still exists in WordPress 5.0.1. You cannot deprecate an attribute without keeping it in the original attributes array. This causes unnecessary markup in the original attributes array. 

The only way I've found to get around this as @nk-o suggests, add a new attribute in place of the old one and keep them both in the original attributes array.

**Comment by atimmer** [comment]
I can confirm this is still an issue with WordPress 5.0.3 and the latest Gutenberg `master` as of writing this.

**Comment by youknowriad** [comment]
This seems fixed for me, I'm not able to reproduce with the exact same example shared above.
