### ISSUE TITLE
Getting design issue in setting popup

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/gutenberg#10401]
As shown in the screenshot below.
Screenshot Url - http://tinyurl.com/y9rgay2q

**Comment by Soean** [comment]
Hey @Swapnildhanrale,
you can simply drag&drop images into the textarea in GitHub, so you don't have to upload and link them on an external service.

To reproduce this issue, which OS, Browser and Gutenberg version are you using?

**Comment by Swapnildhanrale** [comment]
Gutenberg version - 3.9.0
Browser Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
Windows
Hope this helpful

**Comment by draganescu** [comment]
hey there @Swapnildhanrale we went through testing this in a recent triage session and none of use could reproduce using the latest Gutenberg version so I will close this issue considering it does not happen today.

Let know if you still encounter it after upgraded to the current editor version.
