### ISSUE TITLE
Could use a spell check

### ISSUE THREAD

**Issue by k3dao8118** [WordPress/gutenberg#10403]
If there is a spell check - I couldn't find it!

**Comment by Soean** [comment]
No there is no spell check in Gutenberg. You OS or browser should be able to provide this feature.

**Comment by designsimply** [comment]
Closing as won't fix for now based on the last reply.

Thank you for raising the suggestion though and for testing Gutenberg at this stage!

**Comment by MatildaMarseillaise** [comment]
Did they end up adding a spell check? With Gutenburg merging words when pasted from Word, I could really do with a spell check to pick up those that I miss!

**Comment by Soean** [comment]
@MatildaMarseillaise  Not yet, see #6727
