### ISSUE TITLE
"Updating failed" and comments appearing when pasting from Word

### ISSUE THREAD

**Issue by eshannon3** [WordPress/gutenberg#10414]
**Describe the bug**
When pasting text from Word, an HTML comment appears along with an "Updating failed" message and I am unable to publish or save a draft.

**To Reproduce**
1. Create a new post
2. Paste text from a MS Word document

(Optionally, type a post title before pasting the text - it doesn't change the outcome)

**Expected behavior**
I expected Gutenberg to parse the pasted text and create applicable blocks. What happens instead: Gutenberg parses at least part of the pasted text - a comment containing MS formatting appears in a block. I cannot scroll past the formatting comment fast enough to see whether the actual content has pasted, and a pink bar saying "Updating failed" appears across the screen. If I click the "Publish..." button the pink message is replaced with "Publishing failed." If I click "Save Draft" I receive a (checkmark) Saved message, but when I click Publish (twice) I receive an "Updating" failed message. If I click "All Posts" I get a dialog asking if I want to save changes, and the post does not exist in the All Posts screen.

I have deactivated all plugins except Gutenberg, and I have removed all themes except Twenty Sixteen, which is active, so it is not a plugin or theme conflict.

**Screenshots**
![update-failed](https://user-images.githubusercontent.com/14299392/46634092-67bd2180-cb15-11e8-9b3f-ce3a775d1c9f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100

**Additional context**
- Gutenberg 3.9.0 with WP 4.9.8
The Word doc I am trying to paste from:
[Equity Dispute Resolution Process.docx](https://github.com/WordPress/gutenberg/files/2457934/Equity.Dispute.Resolution.Process.docx)

**Comment by eshannon3** [comment]
I don't have any other plugins (security or otherwise) installed on this site. It is hosted at Pagely; I have not personally made any server setup changes. If I just create a Gutenberg post and type in content, there are no 500 errors - it's only when I paste from MS Word documents.

**Comment by Kiwiindo** [comment]
I have suddenly started getting failure to save errors, which seemed to be after I pasted from Word without pasting as plain text! Once this error occurs even a new post will not save without failure to save errors? I tried deactivating plugins in mass but still locked out by errors? Even a new post with "Trial" typed into the heading creats the save error immediately at autosave!

**Comment by Kiwiindo** [comment]
> I have suddenly started getting failure to save errors, which seemed to be after I pasted from Word without pasting as plain text! Once this error occurs even a new post will not save without failure to save errors? I tried deactivating plugins in mass but still locked out by errors? Even a new post with "Trial" typed into the heading creats the save error immediately at autosave!

I found my cause was actually the plugin Distributor - its now disabled and everything working fine!

**Comment by freddiemixell** [comment]
I've testing this in Gutenberg 4.1.1 and the MS document creates blocks for the entire document. This issue was probably fixed somewhere in between 3.9.0 and 4.1.1. 

@eshannon3 could you test this with 4.1.1 and see if the issue is still present for you?

**Comment by eshannon3** [comment]
@freddiemixell After updating to Gutenberg 4.1.1, I was able to paste the Word doc contents. As soon as I pasted, Chrome console showed a yellow message

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/notoserif/v6/ga6Kaw1J5X9T9RW6j9bNfFImajC7.woff2

I waited a couple of seconds and hit Publish, then got the same "Updating failed" message and started getting 500 autosave errors.

POST http://{site_url}/wp-json/wp/v2/posts/2161/autosaves 500 (Internal Server Error)

Clicking "Publish" again refreshes the "Updating failed" message. Clicking over to the All Posts screen triggers the "are you sure" warning; when I go back into the edit screen for the post, only the title has saved - the pasted Word doc text hasn't been saved.

**Comment by cf512** [comment]
I ran into this same issue (unrelated to pasting from Word) and found that it was happening due to protocol. The wp-admin update call was attempting over http and failing because the wp-admin login session was https. Changing the SSL settings to the following in WP Engine's User Portal fixed the issue:

**WordPress admin pages***
[ ] WP-Login — HTTPS only
[ ] WP-Admin — HTTPS only

**Unconfigured pages**
[√] Allow HTTPS and HTTP
[  ] HTTP only

_*loads over https already via other settings and home/site URLs_

**Comment by designsimply** [comment]
Thanks @cf512 !! @eshannon3 I did notice that in the last API error you noted it's using HTTP. Can you check with Pagely to see if they have a similar HTTP/HTTPS option to the one mentioned at https://github.com/WordPress/gutenberg/issues/10414#issuecomment-447495771?

> it's only when I paste from MS Word documents

Strange! (Out of curiosity) does the content you are pasting from Word have images or media or any kind of embed included? If you open a new Word document and do not make any formatting and copy and paste just a small bit of text only, does the problem still happen?

**Comment by eshannon3** [comment]
Hi @designsimply - now using WP 5.0.1, I pasted from the same Word doc attached to the original issue above. (No images or media, just formatted text. Most of my content consists of complex lists and some headings.)

This time, I was able to paste the text. I waited briefly to make sure all the parsing was complete and tried to publish. I got a 500 error again:

api-fetch.min.js?ver=2.2.5:1 POST http://{site-url}/wp-json/wp/v2/acadp/690?_locale=user 500 (Internal Server Error)

I will check with Pagely to see if they have a http/https setting.

**Comment by eshannon3** [comment]
Resolved! Pagely does not have the same type of toggles as WP-Engine, but they were able to confirm it was a server configuration issue, and they resolved the problem. I am now able to paste from Word and publish with no 500 errors or "updating failed" messages.

**Comment by eshannon3** [comment]
They said they're not entirely sure; they ran their automation tools to make sure everything was configured as expected, and that fixed the problem. Sorry they and I can't be of more help to future users with this issue.

**Comment by designsimply** [comment]
Aha! A mystery. Well, no worries at all and I'm so glad it got sorted however it did! 🙂

Thank you for following up here @eshannon3; it is appreciated.
