### ISSUE TITLE
Option to move an article to the trash

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#10417]
**Is your feature request related to a problem? Please describe.**
It would be a great thing if you could move an article to the trash. For example in this menu: http://prntscr.com/l3rofe

**Describe the solution you'd like**
Simply an option to move the item to the trash.

**Describe alternatives you've considered**
Place somewhere in the main menu, but that doesn't have to be.

**Comment by mtias** [comment]
There is a button for this action in the document panel here:

![image](https://user-images.githubusercontent.com/548849/46637430-75e26080-cb5c-11e8-847f-33cfee012bf2.png)
