### ISSUE TITLE
Run test suite against WordPress 5.0 build instead of trunk

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10412]
Now that the core development focus has switched to the `5.0` branch instead of `trunk`, we should make sure the PHPUnit and e2e test suites run against the `5.0` codebase accordingly.

However, with this being said, we may not be currently running the test suite against `trunk`. If this is truly the case, then we should get this configured.

Related 9c75e470b702cb5ab5840210d1b925d9a11bceda 0c12b15c3769fd8e303048ffe4ac785c338c236e

**Comment by danielbachhuber** [comment]
> Won't it happen automatically as soon as new Docker images are going to be published? I also think it has to happen after 5.0 is out and the new plugin's version is released which has a minimum version of WordPress set to 5.0.

Well, yes. The idea a couple of months ago was to run the tests against the `5.0` branch so there weren't any surprises upon release.

**Comment by gziolo** [comment]
@youknowriad did that last Friday on WordPress RC branch. This is short summary shared on Slack (https://wordpress.slack.com/archives/C02QB2JS7/p15439257511970):

> The different behavior I found:
> 
> - Post formats not supported in Twenty nineteen breaking two tests
> - The custom font sizes of Twenty nineteen breaking one test
> - Core has a different implementation of `wp.hooks` breaking two tests. (There’s a ticket to align the implementations I think)
> 
> All of the tests were green otherwise.
> I expect there will be no difference post 5.0 because we’ll probably update the minimum version in the plugins e2e tests and fix all of these.

**Comment by youknowriad** [comment]
Closing as this is done.

**Comment by danielbachhuber** [comment]
@youknowriad It's not done though. I've created a new issue #12839

**Comment by youknowriad** [comment]
So the issue was about running the test suite against 5.0 which is done but yeah if want to run against trunk that's not done, that was never the case actually.
