### ISSUE TITLE
Links: Select text then paste link to make a link

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1041]
In the current editor, if you select some text, then paste a link, a link is made:

![paste to link](https://cloud.githubusercontent.com/assets/1204802/26826859/e1c42eb0-4aba-11e7-914d-5e60d906012a.gif)

We should port this to the new editor.

**Comment by Afraithe** [comment]
I believe this is controlled by the paste plugin in tinymce, if that isn't on, it would not work.

**Comment by jasmussen** [comment]
Can we borrow that plugin for the Editable component? CC @iseulde

**Comment by 00travelgirl00** [comment]
Or can we built this directly in the Gutenberg Editor?
