### ISSUE TITLE
On slow connections, Save/Publish during autosave is tricky

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#10421]
Gutenberg 3.9

During autosave, Publish is unavailable; no big deal on fast connections. But on slower connections, the autosave may take several seconds, maybe 4 seconds (+/-). If it's autosaving every 10 seconds and I can't hit Publish during an autosave, then 40%+ of the time the button is unavailable.

That's kinda problematic. Until I learned the hard way, I hit Publish (during an autosave), assumed it saved, and navigated away only to find I lost the post. 

I'd expect Publish should remain available at all times. Or make autosave less frequent.

**Comment by karmatosed** [comment]
> That's kinda problematic. Until I learned the hard way, I hit Publish (during an autosave), assumed it saved, and navigated away only to find I lost the post.

Just to confirm, how does having publish available solve this? Shouldn't in this case publish not be available and it show a state of saving?

**Comment by karmatosed** [comment]
I am having a hard time replicating this even with throttling, I would love to learn more to work out a solution.
