### ISSUE TITLE
Allow drag and drop in the featured image box

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#10426]
When I am writing a post there's a featured image box in the document settings. It has a dotted outline and looks like I can drag and drop an image onto it to set the featured image, but I can't.

I would like to be able to drag images onto this box to set the featured image for the post.

<img width="426" alt="screenshot 2018-10-09 at 09 18 17" src="https://user-images.githubusercontent.com/1004130/46655825-8d453c00-cba4-11e8-8c92-8c8cd271f290.png">

**Comment by emaildano** [comment]
I agree with this. I've received feedback from clients before on this after the release of 5.0. Visually it doesn't match what the intended result is. In my opinion, click to upload is fine but it should be a standard button. Drag to upload is better but maybe it was considered and there's a reason it's not available yet. However, if you're using Gutenberg as your editor and not classic the JS lib for drag and drop uploads is already loaded.

Ref:
- https://wordpress.slack.com/archives/C02S78ZAL/p1561035316275400

**Comment by emaildano** [comment]
For reference, I've created a ticket on Trac. Gutenberg is apart from Core at the moment but soon (hopefully) will be a full fledged part of Core.

https://core.trac.wordpress.org/ticket/47579#ticket

**Comment by phpbits** [comment]
@BinaryMoon Thanks again for suggesting this feature to EditorsKit plugin. Drag and Drop featured image upload is now available starting version 1.13. Requires Gutenberg plugin though, the filter is only available in there. 👍 Here's the plugin link : [https://wordpress.org/plugins/block-options/](https://wordpress.org/plugins/block-options/)

![Screen Capture on 2019-09-08 at 18-57-21](https://user-images.githubusercontent.com/3365507/64505763-9506e680-d307-11e9-90b5-b5b64d4a08ac.gif)

**Comment by BinaryMoon** [comment]
This is awesome @phpbits. I woud love to see something like this in core!

**Comment by youknowriad** [comment]
Can we just add that to the plugin directly @phpbits

**Comment by phpbits** [comment]
@youknowriad Sure! I guess I'm late :) @epiqueras already created the PR.
