### ISSUE TITLE
User flow and meaning of 'manage reusable blocks' unclear

### ISSUE THREAD

**Issue by boemedia** [WordPress/gutenberg#10435]
When I go to manage reusable blocks from the Gutenberg editor, I have no idea where I end up. Apparently in the WP-admin, but there's no link to this page in the menu. Whether I have or don't have reusable blocks, I'm left without a clue what to do next or how to go back to the post I was editing. "Manage" could mean different things here and should be explained.

See this screen recording: 
[https://cl.ly/63448deb7e95](https://cl.ly/63448deb7e95)

**Expected behaviour**
Two things:
I expected the page I'm sent to, to be accessible from the menu in WP-admin, maybe as a sub in the Gutenberg menu item, but it wasn't there. 
But the behaviour I actually expected, was a place where I could edit the content of one of the reusable blocks, without looking for a post that contained the reusable block. After that, I'd expect to be able to go back to the post I was editing. 

Tested on desktop in Gutenberg 3.9 via Local by Flywheel on Macbook and Firefox (62.0.3)

**Comment by slimmilkduds** [comment]
#9964 is very much related to this

**Comment by boemedia** [comment]
In a way it is, but that ticket only seems to address what happens after the click. My concern is the confusion of what expectations people have when clicking manage reusable blocks as well.

**Comment by tofumatt** [comment]
Related: #10009, at least tangentially.

**Comment by noisysocks** [comment]
> I expected the page I'm sent to, to be accessible from the menu in WP-admin, maybe as a sub in the Gutenberg menu item, but it wasn't there.

I'd be OK with adding _Blocks_ or _Reusable Blocks_ to the WP Admin menu. Underneath _Posts_, maybe? 

> But the behaviour I actually expected, was a place where I could edit the content of one of the reusable blocks, without looking for a post that contained the reusable block. After that, I'd expect to be able to go back to the post I was editing.

This was ticketed as https://github.com/WordPress/gutenberg/issues/9964 and done in https://github.com/WordPress/gutenberg/pull/10751.

**Comment by kjellr** [comment]
> I'd be OK with adding _Blocks_ or _Reusable Blocks_ to the WP Admin menu. Underneath _Posts_, maybe?

I agree this should live somewhere. I don't think "Posts" makes sense, since these could theoretically be used across Pages too. Perhaps it would make sense for this to live under Settings?  cc-ing @melchoyce, who's a little more familiar with the information architecture for WP-Admin than I am. 

Also, since this won't house _all_ blocks that are available — just reusable blocks — we should be sure to call this item "Reusable Blocks".

**Comment by melchoyce** [comment]
My first instinct was also under Posts, but I talked myself out of that immediately because, well, pages. Second thought was maybe this should live under Tools?

**Comment by kjellr** [comment]
Tools was my second thought too. 😄 If it lived under there, I'd suggest calling it "Manage Reusable Blocks" or something.

**Comment by karmatosed** [comment]
I am removing the 'User Experience (UX)' label as part of a label cleanup. It's not being used anymore consistently so let's try and keep to 'needs design' and 'needs design feedback'. If we find a need for another label we can consider it but having those 2 should cover this.

**Comment by noisysocks** [comment]
@melchoyce has been exploring adding a _Blocks_ menu with a _Reusable_ item underneath it to the WP Admin sidebar. That would nicely address this issue.

**Comment by karmatosed** [comment]
I think that the work @melchoyce is doing might mean this can be closed as coming into wp-admin will be some management of reusable blocks, what does everyone think? cc @noisysocks

**Comment by karmatosed** [comment]
Closing this to focus on the new block flow and there are also some plans on managing under options. Overall, the agreement is to improve this so let's do that.
