### ISSUE TITLE
Is there an Upload Component

### ISSUE THREAD

**Issue by squibbleFish** [WordPress/gutenberg#10449]
Currently in Gutenberg, I noticed that we have an Add Media component, which allows us to upload media to wp-uploads. This is awesome, but I am wondering if there is another component that gives me the `file` input type. To help explain, I have a custom block that will allow for a file of JSON data to be uploaded and accepted via the rest api. We then parse and sanitize the data set in the server and store the JSON via post meta. Is there a component I am missing. Part of my reasoning for this question is, I want to use `wp.apiFetch` to send the data, but I can not send `new formData()` using that method. It appears that `apiFetch` sanitizes that data, so I am stuck using the native `fetch` api. Any help is appreciated.

**Comment by Soean** [comment]
So you want to upload and parse a file and not store the file on the server?

**Comment by squibbleFish** [comment]
@Soean That's correct. We are not storing the file, just parsing the data on the server and storing it in postmeta

**Comment by squibbleFish** [comment]
Let me give this a shot! Thanks 😄

**Comment by earnjam** [comment]
This seems to have been answered and there haven't been any updates for over 4 months, so I'm going to close this issue. Please feel free to comment and let us know if it is not resolved.
