### ISSUE TITLE
Classic blocks are appended and prepended when using the WordPress Exporter and Importer

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#10445]
When exporting content, and then importing it Gutenberg adds a Classic Block to the start and end of your content because of the `<!--[CDATA[` start and `]]>` end.

This means all your content receives an empty Classic Block, the end block even has printable output in it (the first one has a HTML comment start, and thus does not get output).

I'm uncertain if this is because the importer/exporter is in dire need of some love, but this behavior isn't present in the classic editor, or is at least hidden there as they are markup that wouldn't be rendered previously.

![image](https://user-images.githubusercontent.com/468735/46686141-a7f4d080-cbf7-11e8-9bd7-aaef97527bb5.png)
A snippet of the end block that's added

The markup is simply just `<p>]]&gt;</p>`, so it doesn't actually have a block denotation, which means the Classic Block is correct to display, except there was never any content here to begin with before exporting.

**Desktop (please complete the following information):**
 - WordPress 4.9.8
 - Gutenberg 3.9.0

**Comment by draganescu** [comment]
I tested this and as of Version 5.4 I could not reproduce the issue. Will close, but we can reopen if I didn't test correctly: 

- export WP content
- delete all content
- import exported content
- no empty Classic blocks
