### ISSUE TITLE
Using multi select in a drop down?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1044]
Are there plans on adding multi select to WordPress?

Multiple Selection
A selection dropdown can allow multiple selections
https://semantic-ui.com/modules/dropdown.html

EDIT:
An example from the above site:
![screen shot 2017-06-07 at 11 04 33](https://user-images.githubusercontent.com/5323259/26870726-320d474c-4b71-11e7-8000-4f019147db20.png)

Existing trac issue: 
https://core.trac.wordpress.org/ticket/31696

**Comment by youknowriad** [comment]
We already added the `FormTokenField` component here (currently used in the Tags selector). Is this what the issue is about?

**Comment by mtias** [comment]
Going to close as we don't have any immediate need for such a component, so it's unlikely to be built unless someone else wants to contribute it.

**Comment by rmorse** [comment]
I decided to make one by adapating `FormTokenField` if anyone needs it:
https://github.com/rmorse/wp-token-multiselect-control

**Comment by paaljoachim** [comment]
Query Block - more advanced / multi select query options
https://github.com/WordPress/gutenberg/issues/30706
