### ISSUE TITLE
Help notice displayed on Privacy Policy page missing in Gutenberg

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#10448]
**Describe the bug**
Original Core Trac Ticket - https://core.trac.wordpress.org/ticket/45057
> When a page is set to be the Privacy Policy page a help notice containing a link to the Privacy Policy guide is displayed in the editor.
> 
> When viewing this page in the Gutenberg editor the notice is missing leaving the only reference to the guide found in the Privacy Settings.
> 
> It would be nice to have this notice supported as part of 5.0.

**To Reproduce**
1. Install Clean WP
2. Enable Gutenberg
3. Navigate to Settings > Privacy and Create Privacy Page
4. Edit Privacy Page in Classic Editor to see the notice.
5. Switch to Gutenberg and note the lack of notice.

**Expected behavior**
The Privacy Policy guide notice should be displayed on the Privacy Policy page irrelevant of editor (Classic & Gutenberg) being used. 

**Screenshots**
<img width="944" alt="screen shot 2018-10-06 at 1 42 24 am" src="https://user-images.githubusercontent.com/8726005/46692292-c76e0800-cbbb-11e8-8108-3d084a205d2a.png">
Classic Editor w/ Privacy Policy notice

<img width="963" alt="screen shot 2018-10-06 at 1 43 02 am" src="https://user-images.githubusercontent.com/8726005/46692307-cc32bc00-cbbb-11e8-95ce-a106725efbb6.png">
Gutenberg Editor w/o notice

**Browser Information is Irrelevant**

Related - #6388

**Comment by audrasjb** [comment]
Hi, 

Nice catch @garrett-eclipse :)
Here is a prototype of what should be done for this specific page.
- I just added a `.is-warning` notice with the text currently used in Classic Editor.
- Sorry, my WordPress instance was localized in fr_FR, but I guess it should be enough to see the desired result.

Technical issues that should be solved:
- We need to check if we are in the privacy policy page (the ID of the page is stored under `wp_page_for_privacy_policy` item in `wp_option` table) to append the notice.
- We need to get the URL of the privacy policy page to append it in the notice.

![privacy-policy-gutenberg](https://user-images.githubusercontent.com/1590998/46730389-4b8dc180-cc88-11e8-98ad-b237ef97dc6c.png)

Cheers,
Jb

**Comment by garrett-eclipse** [comment]
Thanks @audrasjb 

Other technical requirements, if the PHP admin_notice isn't just surfaced via Gutenberg and is instead rebuilt, that should be noted;
- There needs to be a check for `current_user_can( 'manage_privacy_options' )`
- The URL can be found under `tools.php?wp-privacy-policy-guide=1` but will need to be run through `admin_url()` or similar.
- The translatable text along with the accessibility text should match existing to avoid requiring additional translations.

For reference here's the PHP notice code;
https://github.com/WordPress/WordPress/blob/f7ba175491b725a5f3d636072c8b432774d38ae3/wp-admin/includes/misc.php#L1590-L1632

**Comment by gziolo** [comment]
@aduth is working on Notices implementation in Gutenberg, related PR #9617.

**Comment by garrett-eclipse** [comment]
Looks like PR #9617 got merged 🎉

Does that mean existing notices simply work so there's nothing more needed? Or what are the next steps to re-introducing the Privacy Policy guide notice?

Thank you

**Comment by aduth** [comment]
#9617 will not have done anything so far as reintegrating notices from classic editors. It is a refactoring of the JavaScript APIs for creating notices.

**Comment by garrett-eclipse** [comment]
Thanks for clarifying @aduth 
So there's still some work to be done to integrate PHP notices into the new notices API component.

**Comment by desrosj** [comment]
I opened #11999 to move the notice to a new action hook so that it is actually output. This will allow the work in #11604 to pass the notice into the Notices API.
