### ISSUE TITLE
How to use Gutenberg Editor in Your react App

### ISSUE THREAD

**Issue by techsaqib** [WordPress/gutenberg#10446]
Hi , i want to use gutenberg editor as like developer use wp_editor  in there plugin and theme , please tell me the way to call the editor

**Comment by tofumatt** [comment]
You might want to have a look at how the Drupal folks are using Gutenberg or looking through our code for our usage of `initializeEditor()` to get a sense of how to integrate the editor into your own app.

While being CMS-agnostic is a design goal of Gutenberg, we don't currently provide (to my knowledge) detailed documentation on integrating the editor into your own environment. As our focus is on making the editor great in WordPress at the moment, we probably can't provide those docs right now.
