### ISSUE TITLE
 Justified Text

### ISSUE THREAD

**Issue by Th14go** [WordPress/gutenberg#10450]
Good afternoon, would it be possible to add the justified text option in the editor shortcut? Today is only possible with HTML.

https://imgur.com/a/hgTSYF8

**Comment by tofumatt** [comment]
The justification button was removed in the Classic Editor in WordPress 4.7, and appears intentionally removed in Gutenberg as well. You can follow #8433 and #8450 for updates on allowing justification to be manually added, but I don't think we'll be adding the button back right now. Sorry about that!

**Comment by Th14go** [comment]
@tofumatt  I understood, okay, no problem if you are not planning to add it, I still use the manual rs Thanks.
