### ISSUE TITLE
Press This quoted content is partially lost when converting to blocks

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#10456]
When viewing content from a press This post of an image or similar, the content is made as an image, linked to the original source, with a blockquote including an excerpt of any text from the page you are pressing on.

When converting to blocks, the excerpt is converted to a blockquote block, but the media item is stripped out.

The classic data from Press This:

```
<blockquote><a href="http://io9.gizmodo.com/saturn-dominates-dione-in-this-striking-new-photo-from-1729602344"><img class="alignnone size-full" src="https://www.clorith.net/wp-content/uploads/2015/12/1423360911693531534.png" alt="" /></a>Saturn’s satellite Dione is less than half the size of our moon, and it orbits a planet which features a radius nine times that of Earth. It’s a stark contrast in size that’s beautifully conveyed in a picture recently captured by the Cassini space probe.</blockquote>
Source: <em><a href="http://io9.gizmodo.com/saturn-dominates-dione-in-this-striking-new-photo-from-1729602344">Saturn Dominates Dione in this Striking New Photo From NASA</a></em>
```

**Screencap**
![press-this-loss](https://user-images.githubusercontent.com/468735/46698040-54de4600-cc16-11e8-9796-e48533c3ae00.gif)

**Versions**
 - WordPress 4.9.8
 - Gutenberg 3.9.0

**Comment by mtias** [comment]
This particular issue is constrained by the Quote block not supporting other blocks within. It should be turned into an InnerBlocks area with support for paragraph, list, image, and maybe a few others. The main blocker has been UI polish on nested structures, which is almost there.
