### ISSUE TITLE
How to remove breadcrumb in Gutenberg?

### ISSUE THREAD

**Issue by Axbel** [WordPress/gutenberg#10452]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by Soean** [comment]
Hey @Axbel,
which breadcrumb do you mean?

**Comment by Soean** [comment]
I have never seen this option. Maybe its an option from your theme. Which one are you using?

**Comment by Axbel** [comment]
Grimag.

**Comment by youknowriad** [comment]
WordPress 5.0 is out, I suggest reaching out to the theme authors to see if they have plans to bring more Gutenberg compatibility options. Thanks.
