### ISSUE TITLE
Colored text: How to colored words in a sentence in Gutenberg?

### ISSUE THREAD

**Issue by Axbel** [WordPress/gutenberg#10451]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by Soean** [comment]
Its not possible yet, but we already have an open issue about this topic: #6080
