### ISSUE TITLE
Divide Title From Content

### ISSUE THREAD

**Issue by HowdyMcGee** [WordPress/gutenberg#10464]
**Is your feature request related to a problem? Please describe.**
Right now the post title appears to be part of the content when it may or may not be. It's up to the theme developer to make that decision and it may not be clear to the end user. 

**Describe the solution you'd like**
I would like to see the post title block styled a bit different to make it clear that it's a separate part of the actual post content. Maybe a divider or dim background color, something to separate it and make a clear distinction between a Header 1 directly after the post title and the post title itself.

**Describe alternatives you've considered**
The alternative is to have theme developers or plugins provide additional styling to make a clear distinction where the post title is and the content starts.

![example](https://user-images.githubusercontent.com/2173515/46709488-a16f5480-cc09-11e8-8715-ea395b677525.jpg)

**Comment by ZebulanStanphill** [comment]
>I would like to see the post title **block** styled a bit different to make it clear that it's a separate part of the actual post content.

I think this is part of the problem. The post title "block" isn't even a block, though the UI makes it look similar to one. I think it would help if the title was styled differently somehow to make it clearer that it is not a block.

**Comment by karmatosed** [comment]
Right now let's keep the block as it is for phase 1. This absolutely could be something focused on in later phases.
