### ISSUE TITLE
Issue with Cover block (or any background image) on Multisite

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#10469]
**Describe the bug**
If a site admin (not Super Admin) uses Gutenberg and tries to upload a background image to Cover block or any other blocks with background (custom), the background is stripped away and the block breaks on the backend.

However, still works for Super Admin. Tried with fresh Network without any plugin apart from Gutenberg.

Video in the bottom.

**To Reproduce**
1. Make a MS setup with a subsite.
2. Make a new user and set him as Admin for the subsite.
3. Open Gutenberg and add Cover block with a background.
4. See it in the frontend. Refresh and see it on the backend.

**Screenshots**
Video of the issue as an admin:

https://drive.google.com/file/d/1G-1SqJMUH-CaDyiZ1uIapAl8DA5LaFnw/view?usp=sharing

**Desktop (please complete the following information):**
 - Latest MacOS
 - Firefox, Safari and Chrome

Let me know if any more info is needed. Tried in many different places on many different Multisites.

**Comment by Soean** [comment]
Hey @HardeepAsrani,
thanks for reporting this problem. 
We already have an open issue about this, see #2539. We are working on a solution, which should solve this issue in one of the next versions.
