### ISSUE TITLE
Classic block partially overlaps the in-between lines inserter

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#10471]
**Describe the bug**

Noticed when testing #10443 and mentioned in the following comment https://github.com/WordPress/gutenberg/pull/10443#issuecomment-428492999.

**To Reproduce**
1. Create a new post.
1. Add Classic block.
1. Click on the previous block.
1. Try to use in-between line inserter on the top edge of the Classic block.
1. Inserter icon is partially hidden under Classic block's toolbar.

**Expected behavior**

It's always possible to use in-between lines inserter with Classic block.

**Screenshots**

![Screen Shot 2019-04-23 at 14 22 14](https://user-images.githubusercontent.com/699132/56580902-10bffb00-65d4-11e9-999b-45a9a3a46544.png)

**Additional context**
- `master` branch aftr 5.5 release

**Comment by gziolo** [comment]
There is no corresponding PR, moving to 4.2.

**Comment by afercia** [comment]
Related: https://github.com/WordPress/gutenberg/issues/11345

**Comment by gziolo** [comment]
It's better but it still needs some design tweaks:

![Screen Shot 2019-04-23 at 14 22 14](https://user-images.githubusercontent.com/699132/56580613-41ebfb80-65d3-11e9-871a-680d168c6e7d.png)

**Comment by afercia** [comment]
This still happens on current master 5.6.1, just tested again:

hover:

<img width="750" alt="hover" src="https://user-images.githubusercontent.com/1682452/57177703-387e5100-6e67-11e9-9347-5fd64faa7be2.png">

focus:

<img width="750" alt="focus" src="https://user-images.githubusercontent.com/1682452/57177704-3c11d800-6e67-11e9-90b3-39e0d9b5a605.png">

As it was originally reported almost 7 months ago, I'd like to propose to not consider this "Priority Low" any longer.

**Comment by enriquesanchez** [comment]
Given all the recent improvements and updates to the sibling inserter (#18941, #19456, #19596 and #11969), I believe this issue can be closed now.

<img width="776" alt="Screen Shot 2020-03-16 at 13 46 31" src="https://user-images.githubusercontent.com/3276087/76794525-cff14780-678c-11ea-88f1-99e3ecd9fbc3.png">

-----------------

<img width="802" alt="Screen Shot 2020-03-16 at 13 49 20" src="https://user-images.githubusercontent.com/3276087/76794630-062ec700-678d-11ea-977d-9f2dc09bbc51.png">
