### ISSUE TITLE
Add dotted lines to the blocks (ui improvement)

### ISSUE THREAD

**Issue by remediosaraya** [WordPress/gutenberg#10488]
**Problem**
I find that new users or even users with previous experience with WordPress (include builders) find hard understand and get familiar with the block concept. Change between blocks, use nesting blocks, columns, find if a block is full with or boxed and where exactly touch to modify content even with the line as soon is active (:hover) is kind of tricky.  Usually require on new users more than one time or click to get on the right place. Also on the mobile view with less space on the screen and no :hover selector seems to be complicate.

<img width="723" alt="screen shot 2018-10-10 at 1 57 46 pm" src="https://user-images.githubusercontent.com/4819636/46762564-9dd4df80-cc94-11e8-84f1-31998ad8c99f.png">

Similar problems have been mentioned before, but my suggestion is more UI general on Gutenberg:
https://github.com/WordPress/gutenberg/issues/9628 (tools for selecting child/parent blocks)
https://github.com/WordPress/gutenberg/issues/6459. (Show block breadcrumbs for selected block)

**Solution**
Add a single line to the css: .edit-post-visual-editor .editor-block-list__block { border: dashed 1px #ccc;}provides a visual stimulus that reinforces the cognitive performance, so that the user understands a little better each block, its differences, properties and even in the future how to apply new parameters to the CSS model box or advanced functions. This feature could be activated or deactivated on the general configuration (maybe using a icon), so users who are more familiar with the experience and do not require this feature, could precind from its use (@melchoyce mentioned that this work is suggested on phase 2). On the other hand in the mobile interface it reinforces the separation of blocks or identification of them even without having the hover property of the selectors.

**Screenshots with dashed lines**
<img width="579" alt="screen shot 2018-10-10 at 1 27 18 pm" src="https://user-images.githubusercontent.com/4819636/46763334-c1008e80-cc96-11e8-98c8-876770a2967d.png">
<img width="1664" alt="screen shot 2018-10-10 at 1 20 45 pm" src="https://user-images.githubusercontent.com/4819636/46763342-c2ca5200-cc96-11e8-82d0-1779d485202d.png">
<img width="1594" alt="screen shot 2018-10-10 at 1 35 41 pm" src="https://user-images.githubusercontent.com/4819636/46763350-c65dd900-cc96-11e8-9bd1-582d8a1bf827.png">

**Comment by karmatosed** [comment]
I think better visibility and outlines on blocks is something which could be considered in phase 2. I have some concerns though over using dotted lines being a problem as a visual pattern and for some causing line movement. Let's label this for the future and take from there.

**Comment by karmatosed** [comment]
For now, I am going to close this up. We have a few issues around making the nested blocks more discoverable and I think in phase two that will improve. After that we can look at what could be next.

I personally think still the above would be a difficult visual pattern but exploring alternatives would be great.
