### ISSUE TITLE
Jumping to newly inserted block is broken for images

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1048]
Select a block area further down in the layout.
Scroll further up the page.
Click to insert a new block.
(New wanted action) The page jumps to where I have inserted the new block. Showing me what I have inserted.

**Comment by youknowriad** [comment]
This is already working as intended for me. Which block are you trying to insert? Do you have any JS error or something? Need more details here

**Comment by paaljoachim** [comment]
I am testing: https://testgutenberg.wpkonsulterna.se/wp-admin/admin.php?page=gutenberg

Perhaps it is not updated to the newest version.

**Comment by youknowriad** [comment]
mmm Weird, it's working for me there. Did you actually insert the block (clicking on any block) or did you just toggled the inserter?

**Comment by jasmussen** [comment]
Interesting, could it be a browser/platform issue? Like Riad, for me it's working well in both Firefox, Chrome and Safari.

**Comment by paaljoachim** [comment]
This is what I am doing:

![insert-image](https://user-images.githubusercontent.com/5323259/26874757-10223dd2-4b7f-11e7-9c76-6083150a98f8.gif)

I have no idea why it is not jumping to where I inserted the image, but have to scroll to it.

**Comment by jasmussen** [comment]
Interesting indeed. Which browser/platform is this?

**Comment by paaljoachim** [comment]
On my Macbook Pro running OSX 10.11.6 and Chrome.

**Comment by youknowriad** [comment]
Oh! there's probably a bug for the Image Block because we show the modal directly.

**Comment by aduth** [comment]
Related: #621, https://github.com/WordPress/gutenberg/pull/565#issuecomment-300143320

Specifically the second comment notes that the scroll that coincides with inserting some blocks is a behavior of TinyMCE, hence why it doesn't apply to images. (But that we'd want to make this consistent)
