### ISSUE TITLE
Editor wouldn't open

### ISSUE THREAD

**Issue by ITpedia-NL** [WordPress/gutenberg#10487]
**Describe the bug**
Release 3.9 does not open. Screen turns blank. 

**To Reproduce**
1. Go to 'Posts'
2. Click on 'Post to edit'

**Expected behavior**
I want to open the editor

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser chrome
 - Version 69.0.3497.100 (Officiële build) (64-bits)

**Comment by marcin-gryszkalis** [comment]
Check console (F12) for errors and paste them here.

**Comment by ITpedia-NL** [comment]
JQMIGRATE: Migrate is installed, version 1.4.1
post.php?post=10615&action=edit:212 Uncaught TypeError: wp.components.unstable__setSiteURL is not a function
    at post.php?post=10615&action=edit:212
index.js:2 Uncaught TypeError: Cannot read property 'parse' of undefined
    at Object.<anonymous> (index.js:2)
    at r (index.js:1)
    at index.js:1
    at index.js:1
post.php?post=10615&action=edit:240 Uncaught TypeError: Cannot read property 'setCategories' of undefined
    at post.php?post=10615&action=edit:240
index.js:12 Uncaught TypeError: Cannot read property 'normalizeIconObject' of undefined
    at index.js:12
    at index.js:12
    at lodash.min.59550321.js:46
    at mt (lodash.min.59550321.js:27)
    at An.forOwn (lodash.min.59550321.js:112)
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
index.js:12 Uncaught TypeError: Object(...) is not a function
    at Object.<anonymous> (index.js:12)
    at n (index.js:1)
    at index.js:1
    at index.js:1
wp-seo-structured-data-blocks-840.min.js:1 Uncaught TypeError: Cannot read property 'Content' of undefined
    at Object.1623 (wp-seo-structured-data-blocks-840.min.js:1)
    at t (commons-840.min.js:1)
    at Object.1622 (wp-seo-structured-data-blocks-840.min.js:1)
    at t (commons-840.min.js:1)
    at Object.1621 (wp-seo-structured-data-blocks-840.min.js:1)
    at t (commons-840.min.js:1)
    at Object.1620 (wp-seo-structured-data-blocks-840.min.js:1)
    at t (commons-840.min.js:1)
    at window.yoastWebpackJsonp (commons-840.min.js:1)
    at wp-seo-structured-data-blocks-840.min.js:1
index.js:12 Uncaught TypeError: Cannot read property 'serialize' of undefined
    at index.js:12
    at d (index.js:12)
    at Ct (index.js:12)
    at Object.getEditedPostAttribute (index.js:1)
    at e.value (wp-seo-post-scraper-840.min.js:1)
    at e.value (wp-seo-post-scraper-840.min.js:1)
    at e.value (wp-seo-post-scraper-840.min.js:1)
    at e.value (wp-seo-post-scraper-840.min.js:1)
    at t.value (wp-seo-post-scraper-840.min.js:1)
    at t.value (wp-seo-post-scraper-840.min.js:1)
index.js:12 Uncaught TypeError: Cannot read property 'registerCoreBlocks' of undefined
    at Object.Dn (index.js:12)
    at HTMLDocument.<anonymous> (post.php?post=10615&action=edit:2186)
common.js:263 Uncaught ReferenceError: $st is not defined
    at common.js:263
(anonymous) @ common.js:263

**Comment by ITpedia-NL** [comment]
I don't know much of this, but it got me thinking. I do use a modified child theme...
Wim.

**Comment by designsimply** [comment]
Thank you for checking for error messages in the browser console panel. The errors in your reply

> Uncaught TypeError: wp.components.unstable__setSiteURL is not a function
> Uncaught TypeError: Cannot read property 'parse' of undefined
> Uncaught TypeError: Cannot read property 'normalizeIconObject' of undefined
> Uncaught TypeError: Object(...) is not a function
> Uncaught TypeError: Cannot read property 'Content' of undefined

were also reported at https://github.com/WordPress/gutenberg/issues/9845#issuecomment-420883106 and they mentioned that clearing browser cache and cookies solved the problem in that case. Can you try clearing your browser cache and cookies as a troubleshooting step to see if that helps in your case?

If you are still having trouble after that, can you please try disabling the Yoast SEO plugin (it looks like you have version 8.4) and try clearing cache again (even if you already tried that before) and check to see if the problem goes away?

**Comment by designsimply** [comment]
@ITpedia-NL there have been several updates since you first reported this issue. May ask if the problem still happens for you if you update all plugins to the latest versions? 

If you're still having trouble after updating, could you list your active plugins and also check the console output again to see if it has changed?

**Comment by designsimply** [comment]
Closing for now and noting to please re-open if you are able to provide the details requested!

**Comment by designsimply** [comment]
@disu the errors you mentioned are different compared to the ones noted earlier on this issue. Please ask for help at https://wordpress.org/support/forum/how-to-and-troubleshooting/ first if you are in need of troubleshooting including how to temporarily disable plugins in order to rule out a plugin conflict. If you find what you think is a bug, please create a separate issue with the guidance of the support team.
