### ISSUE TITLE
Translator comment needed for 'View'

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10499]
In https://plugins.trac.wordpress.org/browser/gutenberg/trunk/languages/gutenberg-translations.php#L989 we as translators need to know if it means 'to view' or 'a view', in short, we need a translator comment. Thank you.

**Comment by Soean** [comment]
https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/header/writing-menu/index.js#L16

![bildschirmfoto 2018-10-11 um 16 51 40](https://user-images.githubusercontent.com/695201/46812944-12337f80-cd76-11e8-9276-b53e40ac43ad.png)

**Comment by Presskopp** [comment]
maybe: translate as a noun
