### ISSUE TITLE
Post Categories listed in alphabetical order

### ISSUE THREAD

**Issue by carmemias** [WordPress/gutenberg#10497]
It'd be useful if the Post Edit screen listed the post categories in alphabetical order, just as it is done in the Classic Editor. 

At the moment Gutenberg orders them by when they were published, and it can take a long time to read through long lists...

Thanks!

**Comment by Soean** [comment]
I can't reproduce the issue, the order is alphabetical not by ID. Tested mit 4.0 rc-1.
![bildschirmfoto 2018-10-11 um 15 47 04](https://user-images.githubusercontent.com/695201/46808632-127b4d00-cd6d-11e8-90c7-b5b505210bbc.png)

**Comment by mtias** [comment]
This was changed for 4.0, so it might have been tested in 3.9 or previous version.
