### ISSUE TITLE
Clicking enter multiple times creates a new block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1049]
I am testing: https://testgutenberg.wpkonsulterna.se/wp-admin/admin.php?page=gutenberg

The issue:
A text block.
Another block below it.
A user wants more space below the block. He/she might go into and click multiple times just below the text to create some space to the next block.
Suddenly a new block is created. It feels kinda strange that clicking multiple times inside a text block automatically creates a new block. It is better to keep it clean. To add a block one clicks the +Insert button.

The question is then how can we easily add more space between the blocks in the layout?
Should there be a spacer block to where the user can define or drag the top and bottom edges to make more or less space?

**Comment by jasmussen** [comment]
The current behavior in master is currently that single enter is a paragraph linebreak, double enter creates a new text block. Though per recent discussions, including some in #898, this behavior is possibly going to be adjusted in the near future.

Regardless of how enter works in the Text/Paragraph block, the Freeform block is likely the block you want to use if you want multiple linebreaks like this.

**Comment by paaljoachim** [comment]
The freeform block looks identical to the text block. I see not clear difference between them.

**Comment by jasmussen** [comment]
The freeform block is still in a state of flux with many features being added to it. See also #1037 and #1038. But they are subtly different, both visually and mechanically.

Freeform:

![screen shot 2017-06-07 at 12 31 01](https://user-images.githubusercontent.com/1204802/26874268-4bb9f9fe-4b7d-11e7-9146-21578f793973.png)

Text:

![screen shot 2017-06-07 at 12 31 13](https://user-images.githubusercontent.com/1204802/26874270-4ec45162-4b7d-11e7-8631-e710bf6a5cd2.png)

Mechanically they are also different in that the freeform block accepts multiple linebreaks. In fact right now there's now way to break out of the block, without tabbing and creating a new block below it. This is intended, insofar as the freeform block is to play the role of the "old editor" in block form.

**Comment by mtias** [comment]
Creating a new block when pressing multiple enters is the designed behaviour.
