### ISSUE TITLE
Backwards compatibility with traditional admin notices

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#10491]
Following #4811, if a plugin or theme is trying to show a message on the post edit screen, it will be hidden. Plugins may be trying to add important messages, ones that only appear on the new/edit post screen. Gutenberg should attempt to render these messages, perhaps by automatically upgrading them to [notice components](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/notice), rather than hiding them.

**To Reproduce**
1. Render an admin notice, e.g.
    ```php
    add_action(
    	'admin_notices',
    	function() {
    		echo '<div class="updated success"><p>Sample Message</p></div>';
    	}
    );
    ```
2. Navigate to the new/edit posts screen with Gutenberg active

**Expected behavior**

I should see the above "Sample Message", ideally with some indicator of success.

**Additional context**

Related: #3395, amongst others.

**Comment by danielbachhuber** [comment]
#6388 is the canonical issue for this. Closing in favor of that.

**Comment by collimarco** [comment]
This still doesn't work... admin notices are not shown in Gutenberg.

Moreover the linked issue has been closed as completed, but the bug is still present.

Please fix this, so that `admin_notices` works as expected...
