### ISSUE TITLE
Documentation on i18n translations integration missing

### ISSUE THREAD

**Issue by michakrapp** [WordPress/gutenberg#10498]
Currently there is an important piece missing in the documentation - the way how to integrate the translation strings for the used wp.i18n-functions in the blocks.

An example I have found (with the help of @Soean) in the i18n block example by @swissspidy 
https://github.com/swissspidy/gutenberg-i18n-block/

**Comment by swissspidy** [comment]
Worth keeping in mind that there will be some changes on this front with 5.0 and how language packs are installed etc.

See https://core.trac.wordpress.org/ticket/45103 for example.
