### ISSUE TITLE
Manage columns according to responsiveness

### ISSUE THREAD

**Issue by legraxieux53** [WordPress/gutenberg#10506]
I am frustrated with the use of Gutenberg's column module. 

I would like to set the width of the columns according to the width of the screen.

 Which is not the case. I propose that the user decides on the width of each column for each type of screen (pc, tablet, mobile, wide screen, etc.) like twitter bootstrap.

Thank you for considering this request.

**Comment by designsimply** [comment]
Thank you for testing Gutenberg at this stage and for posting feedback. I'm sorry that the columns block is frustrating you at this point! There have been similar issues reported already and I would like to close this one in favor of #6048 and note that there is an update in progress at #10541.
