### ISSUE TITLE
Blue circle hover effects on top of arrows

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1051]
I am testing: https://testgutenberg.wpkonsulterna.se/wp-admin/admin.php?page=gutenberg

I believe this is already a part of an existing issue but I can not locate it right now.

Initially hovering over the left arrow beside the text block the up arrow is barely seen greyed out and the down arrow is obvious to notice.
I click to move the block one step down.
I click to move it up again.
This time there is a blue circle around the greyed out up button.

![screen shot 2017-06-07 at 12 15 42](https://user-images.githubusercontent.com/5323259/26873731-2c19466a-4b7b-11e7-85e1-12090be6d78e.png)

To me the blue circle feels out of place. The up arrow is already greyed out showing that one can not move it further up. Hmm hovering over the down arrow the blue circle is now also visible. Instead of having a blue circle what about just having the arrows turn blue?

![blue-arrow](https://user-images.githubusercontent.com/5323259/26873923-d9a7dcec-4b7b-11e7-8e36-8fb428135c58.jpg)

As one hovers over the arrows one can see a more subtile change.

**Comment by jasmussen** [comment]
The blue circle is the focus highlight. I agree that it should show up only when you are using keyboard input, and not on button press. Though whether this is a bug or not, is part of a larger discussion that is ongoing in https://github.com/WordPress/gutenberg/issues/904#issue-231312517. For that reason, I'm closing this one. But thank you for reporting it as an issue.

**Comment by afercia** [comment]
This is also because the up arrow in this case is not really "disabled", it just _looks_ disabled. Adding a _disabled_ attribute when it's... disabled, would make it not focusable -> no focus style. If I remember correctly, this is already mentioned in another issue.

**Comment by jasmussen** [comment]
Was the disabled aspect not fixed in #228 ? @iseulde any insights? Thank you.

**Comment by iseulde** [comment]
@jasmussen I'm not sure what you're asking. The ticket you're linking was a prototype ticket.

**Comment by jasmussen** [comment]
Argh, I'm having a case of the mondays. Nevermind me. I could just swear we had a ticket somewhere for actually adding a disabled attribute to the up/down arrows when they are at the top or bottom of the block list.

**Comment by aduth** [comment]
#984 was somewhat related, though to labeling the buttons, not applying the `disabled` attribute.
