### ISSUE TITLE
new post will not save

### ISSUE THREAD

**Issue by evbaker** [WordPress/gutenberg#10522]

**Comment by evbaker** [comment]
Post is constantly attempting to save and images are not downloading as they normally would with the classic editor

**Comment by designsimply** [comment]
I cannot see the same problem happen in my own testing so I would like to try to get more information about your case. 

Is the post you are trying to edit being saved as pending or is it a draft? (See #10486)

May I ask what browser and browser version you are using?

If possible, are you able to check the Network and Console panels in your browser developer tools to see if any errors show up there at the time you open a post and see the problem with saving? It sounds a little like something in your web server setup may be blocking API calls and seeing any errors being generated may help with diagnosing the problem.

**Comment by designsimply** [comment]
More information is needed to help diagnose this problem. If you are able to update to the latest version of Gutenberg or test with WordPrress 5.0-RC, please make a note of the version you are testing with and re-open the issue. Thank you!
