### ISSUE TITLE
Show Style Variations on the Sidebar

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#10520]
Style variations are very neat and we are adding a few more in 4.0 and 4.1. We currently show them in the block switcher, which is great, but it seems we should also show them on a panel in the sidebar called "Styles" for maximum discoverability.

This would be _in addition_ to the block switching mechanism not as a replacement. The code should be reused entirely, except for the hover previews maybe.

## Mockups

Note that these mockups are not pixel precise.

Variations in the sidebar:

![just-sidebar](https://user-images.githubusercontent.com/1204802/46815193-b7505700-cd7a-11e8-9717-64bf1f80aae3.png)

If you were to open both at the same time, just to make it clear both interfaces are available:

![both-showing](https://user-images.githubusercontent.com/1204802/46815228-c931fa00-cd7a-11e8-9194-01f666b6b22b.png)

**Comment by chrisvanpatten** [comment]
YES YES YES.

I even built my own component to do exactly this: https://github.com/tomodomoco/gutenberg-controls#radioimagecontrol

I am very all in for this ❤️

**Comment by mtias** [comment]
@jasmussen I think we should just call it styles, and it should probably be collapsed by default.

**Comment by jasmussen** [comment]
Yep, "styles" and collapsed by default works for me. I would suggest this can be done in implementation.

**Comment by 0aveRyan** [comment]
Much less overhead/technical know-how needed to register custom style vs. custom block. Surfacing Styles in sidebar should help increase usage and simultaneously reduce similar-but-different custom blocks in 3rd party plugins. See this as a huge win for devs + users alike 🙌
