### ISSUE TITLE
Deciding on the size of the image to be inserted?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1052]
Selecting and adding an image. 

Today we have the following options:

![screen shot 2017-06-07 at 12 48 56](https://user-images.githubusercontent.com/5323259/26874905-c9828656-4b7f-11e7-8e4f-45b515b1dd5a.png)

What happens with selecting the size or link to? This is likely already answered in another issue.

**Comment by jasmussen** [comment]
Some of this question is answered by what we're lovingly calling "the inspector" (see work in progress here https://github.com/WordPress/gutenberg/pull/1050#issue-234159222 and also #672 ). But keeping this one open as a ticket for the image inspector settings.

**Comment by mtias** [comment]
This will be done with https://github.com/WordPress/gutenberg/issues/1727
