### ISSUE TITLE
MSEdge: Block toolbar overlay block contents

### ISSUE THREAD

**Issue by brbrr** [WordPress/gutenberg#10533]
**Describe the bug**
Block toolbar appears _on top_ of the block contents when editing a post in MSEdge

**To Reproduce**
1. Start new post `wp-admin/post-new.php`
2. add a `Heading` block
3. force toolbar to show-up
4. See it appears over the block

**Expected behavior**
A toolbar appears above the block frame

**Screenshots**
<img width="509" alt="header block" src="https://user-images.githubusercontent.com/5654161/46828554-27bf9e00-cda4-11e8-8b03-bb095ce504ad.png">

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser MSEdge
 - Version 41.16299.492.0

**Additional context**
Gutenberg v3.9

**Comment by blazevivan** [comment]
Tested this on Win 10, MSEdge Version 42.17134.1.0

The editor is not loading at all: 

https://cld.wthms.co/KDXUQx

The same is on 2 different sites.

The following is console error: http://cld.wthms.co/6dM0EE

The same link (https://trainingchaosivan.wordpress.com/wp-admin/post-new.php) loads Gutenberg in Chrome.

**Comment by mcmwebsol** [comment]
I tested this on Windows 10, Microsoft Edge version 42.17134.1.0 using WordPress 5.0 beta and it seems fine.

**Comment by youknowriad** [comment]
I can't reproduce this. It seems fixed.
