### ISSUE TITLE
Allow Classic Block to be default block

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#10546]
There is some discussion around what kind of accessibility standards Gutenberg needs to meet to be recommended to users of various assistive technologies (#10537), and what the fallbacks would be for them were Gutenberg not considered accessible enough to be responsibly recommended for (some) users.

The community sentiment seems to indicate that the Classic Editor is, while not the ideal fallback (creating a lesser experience for users of assistive technology isn't great), an accessible editing experience. I pointed out that the Classic Editor plugin could be a good alternative for users with accessibility needs for the first few releases of WordPress with Gutenberg, but it was pointed out here: https://github.com/WordPress/gutenberg/issues/10318#issuecomment-429109127 by @joedolson that there's a permissions issue there: **what happens if you require the Classic Editing Experience™ but can't install plugins?**

Having worked in government myself for years and heard from educators with locked-down installs–two areas where accessibility is not only important but often enforced by law–asking users to install the Classic Editor plugin might be unworkable. Using the Classic Editor Plugin was originally proposed in a "try callout" suggestion (https://core.trac.wordpress.org/ticket/44671#comment:9), but I think we can't rely on it being the solution.

Instead, we should provide the ability to enable the Classic block as the default block (for users of assistive technology). Enabling this will allow users to be slowly migrated to Gutenberg but not have to worry about the accessibility of all blocks involved.

(That said, if the [blocks/editing experience making up the Classic Editor experience](
https://github.com/WordPress/gutenberg/issues/10318#issuecomment-429058380) are not found to have accessibility issues, I'm not sure this would be needed.)

**Comment by tofumatt** [comment]
FYI: I have no idea what the UX/UI of setting this block would be.

**Comment by f7375189** [comment]
> There is some discussion ... community sentiment seems to indicate ... a lesser experience ... heard from educators ... might be unworkable ... should provide the ability ... to be slowly migrated ... I have no idea ...

WordPress is committed to [being as inclusive and accessible as possible](https://wordpress.org/about/accessibility/).

WordPress needs to have an independent accessibility lead who knows what accessibility means and who is committed to the topic. Draw your own conclusions.

**Comment by tofumatt** [comment]
Having explored this further: mainly testing Gutenberg more thoroughly myself for major accessibility blockers in the main writing flow, knowing UI freeze is soon with more forward-looking accessibility features like date/colour pickers landing, and hearing from @mtias of the accessibility issues with the Classic Editor itself, I don't think this is worth doing specifically for Accessibility or for the merge.

A default block change might be neat in the future (mainly for "better" paragraph blocks provided by third-parties), but this isn't required to merge.
