### ISSUE TITLE
Allow direct transform between Quote and Pullquote 

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#10548]
Transforms being an important bridge between blocks, we should make it easier to bump from Quote to Pullquote (and vice-versa), especially since there is currently no direct path from Paragraph to Pullquote (only to Quote).

I'm fine not adding Paragraph `->` Pullquote if we're concerned about overcrowding the block switcher, as long as we have Paragraph `->` Quote `->` Pullquote.

Marking as bug, as we should address this soon.

**Comment by dlaub3** [comment]
I'll work on this for my first issue.

**Comment by dlaub3** [comment]
@mcsf Where are a block's transformation options set? I've looked through the code base and have the general idea. But I  can't find anything specifying the transformations for a given block.

**Comment by Soean** [comment]
You add this to the settings of the block. See for example the cover Image block: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/cover-image/index.js#L78

**Comment by mcsf** [comment]
@dlaub3: thanks for looking at this! Soean beat me to the answer.

The transformation API currently lacks documentation, but a lot can be learnt by example. Looking at `transforms:` in the index files for Cover Image, Quote, etc. should help you get started.

**Comment by iseulde** [comment]
@mcsf Just an idea: conversions such as "Paragraph -> Quote -> Pullquote" could be detected automatically and applied in a row. There should be no need to provide all these. Anyway, this is out of scope of this issue. :)

**Comment by mcsf** [comment]
Yeah. I believe we chatted about this long ago. I could see it as part of refractors in 5.1. :)

@dlaub3: let me know if you need anything else, and how soon you’re planning on tackling this!

**Comment by dlaub3** [comment]
I'll be able to work on this tomorrow evening. If that's not soon enough
someone else may work on it and I'll find another issue.

**Comment by mcsf** [comment]
@dlaub3: Even though this got addressed separately, thank you for your involvement. I'll keep an eye out for things that can be labeled `Good First Issue`. :)
