### ISSUE TITLE
Block: Cover Image text alignment class not applied for "center" option

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#10558]
**But description**

Cover Image block applies the `has-left-content` and `has-right-content` class, but not `has-center-content` when a text alignment option is selected.

I understand that default Cover Image styles applies `text-align: center;`, so, that's why it was decided to omit the `has-center-content` class application.

However, the problem occurs when a theme decides to change the default Cover Image text align styles to `text-align: inherit;` for example. In that case there is currently no way of applying center text alignment on Cover Image block.

**Expected behavior**

`has-center-content` class is applied with "center" text align option.

**Additional context**

- Gutenberg version 4.0.0-rc.1

**Comment by jorgefilipecosta** [comment]
The issue is not reproducible after the merge of nesting in the cover block.
