### ISSUE TITLE
highlighting bold/italic/links text doesn't invert text color with dark-editor-style

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#10550]
**Describe the bug**
Selecting for example a paragraph that is bold/italic/link almost makes the text invisible

**To Reproduce**
1. create paragraph
2. select some text and make it bold

**Screenshots**
<img width="348" alt="screen shot 2018-10-12 at 13 57 21" src="https://user-images.githubusercontent.com/40266703/46867904-cdb3ec80-ce26-11e8-81ee-2486a1da09e6.png">

**Desktop (please complete the following information):**
 - chrome
- GB RC 4.0

**Comment by designsimply** [comment]
Noting that testing steps to add dark editor style support are in #9683.

**Comment by slimmilkduds** [comment]
I'm not sure I'm doing something wrong, I always though that I had dark-editor-style activated but now I'm not so sure since I can't tell the difference after de-activating it. This is how I set it up:

function navi_gutenberg_styles() {
         wp_enqueue_style( 'navi-gutenberg', get_theme_file_uri( '/style-editor.css' ), false, '1.0', 'all' );
}
add_action( 'enqueue_block_editor_assets', 'navi_gutenberg_styles' );

add_theme_support( 'editor-styles' );
add_theme_support( 'dark-editor-style' );

**Comment by slimmilkduds** [comment]
I've also tried this with the same result:

function mytheme_block_editor_styles() {
    wp_enqueue_style( 'mytheme-block-editor-styles', get_theme_file_uri( '/style-editor.css' ), false, '1.0', 'all' );
}

add_action( 'enqueue_block_editor_assets', 'mytheme_block_editor_styles' );


add_theme_support( 'editor-styles' );
add_theme_support( 'dark-editor-style' );

The style-editor.css works in both cases but I get no visual change whit add_theme_support( 'dark-editor-style' );

**Comment by slimmilkduds** [comment]
Oh wait, it's actually working. But the problem in the ticket title still exists, this is a comparison between selecting bold and non-bold text

<img width="309" alt="screen shot 2018-10-16 at 08 31 11 1" src="https://user-images.githubusercontent.com/40266703/46996774-1d8ffd80-d11e-11e8-809c-fd3d6c706c05.png">

<img width="321" alt="screen shot 2018-10-16 at 08 31 03" src="https://user-images.githubusercontent.com/40266703/46996783-2385de80-d11e-11e8-89ab-c6073d0fc4b8.png">

**Comment by slimmilkduds** [comment]
This has been fixed in 4.1 rc 2 (or 1). Thanks!
