### ISSUE TITLE
Custom block implementing <InnerBlocks /> loses data on page refresh (but works great on initial save).

### ISSUE THREAD

**Issue by persianturtle** [WordPress/gutenberg#10567]
**Describe the bug**
With the following custom block:

```
registerBlockType("my-plugin/my-block", {
  title: "my-block",
  icon: "schedule",
  category: "common",
  edit: ({ className }) => (
    <section className={className}>
      <InnerBlocks
        template={[
          [
            "core/columns",
            {},
            [
              [
                "core/column",
                {},
                [["core/heading", { placeholder: "Enter title...", level: 1 }]]
              ],
              [
                "core/column",
                {},
                [["core/paragraph", { placeholder: "Enter side content..." }]]
              ]
            ]
          ]
        ]}
        templateLock="all"
      />
    </section>
  ),
  save: ({ className }) => (
    <section className={className}>
      <InnerBlocks.Content />
    </section>
  )
});
```

New columns are not able to be added, but new blocks within columns are--and this is desirable. However, when creating multiple blocks within a column, only the first one remains after reloading the editor.

**To Reproduce**
1. Implement custom block and use it in the editor.
2. Click on the right column, and add several blocks, including `core/list` blocks.
3. Click save, and notice that everything is working great.
4. Refresh the editor, and notice blocks in the right column are missing. The published page still has all the data, but saving the editor after refreshing causes the additional right column blocks to be lost.

**Expected behavior**
I expect that after refreshing the editor, all of the blocks persist in each column.

**Additional context**
- Gutenberg version: 3.9.0

**Comment by youknowriad** [comment]
In your `edit` function, you're using `templateLock="all"` which means everything is locked there, so when reloading the `InnerBlocks` component uses the provided template as prop instead of the saved blocks.

Consider removing this lock.
