### ISSUE TITLE
Clarify Status of Columns for Release

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#10560]
As made clear on #9156, there are a number of problems with the columns block. As the targeted release date quickly approaches, I find the continued inclusion of the columns block (even with the "Beta" label) quite confusing.

Will that block be included in the first release of Gutenberg with WordPress? If so, I worry that it over-promises and under-delivers, giving people the wrong impression of the quality and reliability of the new editor. I can't think of a single feature in WordPress that was released in such a problematic beta state.

On the other hand, a columns block will be incredibly useful and is a great example of the advantages of block-based editing.

Either the columns block should get pulled or it should be considered a blocker and significantly improved before release.

**Comment by mtias** [comment]
> I would like to see variable column widths in 5.0; is there a chance that will be included?

Likely not. We are trying the mechanism in https://github.com/WordPress/gutenberg/pull/9416 which should be included in 5.0, but with a more constrained scope. If it works well we can add this in a minor release later on.

> Either the columns block should get pulled or it should be considered a blocker and significantly improved before release.

This is very fuzzy to plan around. What specifically needs to be improved? There are many features we can add to it, but they are not crucial for a first version. The main focus is on fixing any outstanding bugs and clarifying the selection of parent / child combinations: https://github.com/WordPress/gutenberg/issues/9628

**Comment by mrwweb** [comment]
> What specifically needs to be improved?

#9156 has a good list. Highlights:

> Overall, this block just feels confusing across the board, and I'm not sure that putting a "beta" flag in the title helps a great deal, particularly when the entire software is still in some form of beta or another.

> Selecting elements (especially the RIGHT element) is very confusing.

> Column block followed by another column block creates overlap.

I haven't tested the very latest release, but in the 3.9.0 plugin release, there were overlapping outlines, I struggled to click in the right place to add content to the 2nd column, and I don't see a button to add another block below the first one in a column. 

I'm not really clear what the intended featureset of the columns block is intended to be. **It's extremely hard to give good feedback without understanding the intended features.** (Maybe that could be added to all the Block Audits?) but I think it needs to not have any major usability problems of the types mentioned if it's going to be included.

**Comment by mtias** [comment]
Further improvements have landed in #11659 and #11904. @mrwweb would you mind testing with latest master to see how it feels?

> I'm not really clear what the intended featureset of the columns block is intended to be.

Columns was originally not planned for 5.0, it was used to refine the hidden architecture around nested blocks. In the process — and the delaying of launching phase 1 — it continued to evolve and people started using them for cool integrations to the point that it became almost an expected feature.

For 5.0, the *Columns Block* needs to:
- Support adding blocks inside different columns.
- Support adding new columns.
- Integrate with "block navigator" for selecting single columns and the wrapper.
- Support adding classes to the wrappers.
- Be decently responsive on mobile.
- Have columns of equal widths (in the future it should be resizable / configurable).
- Not have major usability problems (like not being able to select a block, or breaking the editor layout).

**Comment by mrwweb** [comment]
Haven't been able to test this yet @mtias. Will it be on beta5?

**Comment by jasmussen** [comment]
> Will it be on beta5?

That branch was merged into Gutenberf 4.4 which will form the basis for beta 5, yes.

**Comment by mtias** [comment]
Yes, it was included in beta 5.

**Comment by mtias** [comment]
Closing this, consolidating in #11159. The main fix discussed there is ready but won't be landing until 5.0.1.
