### ISSUE TITLE
Opening inspector for ListBlock throws error

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1056]
You get an error and a blank page trying to open inspector for the ListBlock. Sounds like a nested `<li>` issue.

**Comment by aduth** [comment]
Seems an issue with how we output attributes in Block Inspector currently:

https://github.com/WordPress/gutenberg/blob/321a8e8/editor/sidebar/block-inspector/index.js#L40-L42

Will be fixed by #1050 (cc @youknowriad)

**Comment by aduth** [comment]
Fixed by #1050
