### ISSUE TITLE
Block: Separator style class

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#10569]
**Bug description**

Not sure why the "Short line" Separator block style produces `is-style-default` CSS class:

**Expected behavior**

Should produce `is-style-short` CSS class instead.
A theme can style the separator (`<hr>` tag) full width by default actually.

**Screenshots**

![Separator block style CSS class](http://easycaptures.com/fs/uploaded/1285/8485008198.png)

**Additional context**

Gutenberg version 4.0.0-rc.1

**Comment by aduth** [comment]
cc @youknowriad re: #7362

Was it intentionally named `"default"`?

Regardless, this seems like it would be a breaking change for existing blocks to change without [deprecation](https://wordpress.org/gutenberg/handbook/block-api/deprecated-blocks/), and it's not obvious that we support migrations of styles.

**Comment by youknowriad** [comment]
There was no particular reason for it to be named "default" aside from being the style that was already there for the separator. and yes there's no way to ensure style backward compatibility right now.

So I'm in the fence, I mean I can see the reasoning and we could argue that we're still early that we can afford to break compatibilty but in the other hand it's just a className, is it worth breaking backward compatibility?.

**Comment by webmandesign** [comment]
Thanks for the input guys.

In my opinion, as the class is obviously wrong, confusing, it should be updated. _(There is maybe possibility of something similar being applied in other blocks?)_

I was actually pretty confused as theme developer about how the block is rendered and styled:
Without applying any custom block styles in my theme, the "Short Line" and "Wide Line" separators were actually the same. And when I dug deeper, I've spotted this "default" class which actually does not really tell me I should expect the "Short Line" styling as selected in Gutenberg editor by default.

And like I've mentioned, the "default" can and will mean something different in every theme.

**Comment by SnazzySnail8** [comment]
Hey guys, 
I'm a wordpress user and currently the "Short Line" and "Wide Line" separators are displaying as the same Full Width separator on my site. Regardless of naming convention, it is a bug if it is not displaying as the names suggest. 
Thanks!

**Comment by mapk** [comment]
@webmandesign Thanks for finding this problem!

In light of the discussion in the PR, I'm going to close this issue and reference the _flipped_ solution provided by the issue #13660.
