### ISSUE TITLE
Blockquote from old post gets an empty line at the top

### ISSUE THREAD

**Issue by AlexisWilke** [WordPress/gutenberg#10587]
**Describe the bug**
While editing an old post with Gutenberg installed (i.e. no conversion of the old post to Gutenberg), it adds an empty line at the start of each `<blockquote>` tag.

The page itself is fine either way so there are no worries on that end. This is only a _bad_ visual effect effect while editing.

**To Reproduce**
1. Create a post without Gutenberg active
2. Put some text "La la la..."
3. Add a `<blockquote>` with a quote (a single paragraph in my case)
4. Put some text after "End End End"
5. Save
6. Install/Activate Gutenberg
7. Edit that post
8. Look at the \<blockquote> and see the empty line

* Note: it may not be required to edit a prior Gutenberg post to see the effect.

**Expected behavior**
Do not add that empty line. (It is confusing)

Someone who wants to add a line before can click at the start of the line and hit enter to add an empty if necessary.

**Screenshots**

![image](https://user-images.githubusercontent.com/1028617/46911459-5f982400-cf11-11e8-99ac-e05617a017b5.png)

This screenshot shows the empty line at the beginning of each blockquote.

**Desktop (please complete the following information):**
 - OS: Ubutun 16.04
 - Browser: Seamonkey (like Firefox)
 - Version: 2,49.4

**Smartphone (please complete the following information):**
n/a

**Additional context**
- Gutenberg 3.9.0
- Here is the HTML and as we can see an empty `<p>` tag is added at the start of each `<blockquote>`

    `<p>... For example, it could change:</p>`
    `<blockquote>`
    `<p>&nbsp;</p>`
    `<p style="padding-left: 30px;">"I drive the car"</p>`
    `</blockquote>`
    `<p>into</p>`
    `<blockquote>`
    `<p>&nbsp;</p>`
    `<p style="padding-left: 30px;">"I love to drive the nice blue car"</p>`
    `</blockquote>`
    `<p>This makes the content length longer and it's...</p>`

**Comment by GlennMartin1** [comment]
This bug appears a few different ways.

My pages had lots of layout Shortcodes that cannot by converted by Gutenberg, so many times I'd copy sections of content from a Classic block into a new Gutenberg block (just converting blocks manually).

Anyway, in doing that, quotes would always add unnecessary preceding spaces. 

It's a pain, but I couldn't sort through 1200 open issues to see if it's already reported.

Just saying, you'll discover this same bug in a variety of ways.

**Comment by jorgefilipecosta** [comment]
Hi @AlexisWilke, @GlennMartin1 thank you for reporting this issue. I tried to replicate the problem in the last version of Gutenberg and the problem seems fixed.
If you are still able to reproduce the problem, feel free to reopen the issue.
