### ISSUE TITLE
Multi-select: Backspace and delete should delete blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1058]
From https://github.com/WordPress/gutenberg/pull/1039#issuecomment-306802393:

> delete and backspace still thinks you've selected text, and deletes it (which of course you have, I know). It seems like it'd be nice that backspace and delete buttons both do the same as the trash button, when you've multi selected. Doesn't it?

So the behavior would be this:

- Select across blocks
- Press backspace, or delete
- Blocks disappear

**Comment by iseulde** [comment]
See #2103.

**Comment by youknowriad** [comment]
closed by #2103
