### ISSUE TITLE
Normal font size don't have a number associated to it.

### ISSUE THREAD

**Issue by robertdall** [WordPress/gutenberg#10585]
**Describe the bug**
In the paragraph block, you have _text setting_ sidebar settings within that you can select the font size. From small up to huge. The middle setting and the default setting is _normal_ There is no font size associate to what "normal" is. The number box is empty, see screenshot.

What is normal? Normal font size for a paragraph block in WordPress is set as the font size with in the theme. The theme could make 36px the normal. This should be shown as a number within size box associated with your theme.

Having an empty field for normal does that means that you can't change number for normal since their is no number in the number box?

If our theme's normal is 36px Does that mean large is also normal or will large become a font size that is larger then normal?

Normal as a font size should have a number associated with it.

Also on an accessibility front if you have screen reader reading to you and it says "normal" which out a number associated to it then how would the user know what normal is if the screen reader doesn't read it out.

**To Reproduce**
1. Add text to paragraph block
2. Click on text settings
3. Scroll font size to small and see the font size
4. See that normal isn't showing the font size.

**Expected behavior**
Normal as a font size should have a number associated and that number should come from the theme.

**Screenshots**
<img width="280" alt="screen shot 2018-10-13 at 10 16 43 am" src="https://user-images.githubusercontent.com/1909677/46908109-93a02480-ced2-11e8-996b-3ff4dbd91b58.png">

**Additional context**
- Gutenberg 4.0.0-rc.1

**Comment by joyously** [comment]
I think there should _never_ be any numbers associated with fonts, since the theme can use any kind of CSS to represent normal and small and large. 
If blocks use class names for changing the font size, then the theme can just style those.

**Comment by chrisvanpatten** [comment]
I agree 100% with @joyously. The theme should just register the names of the sizes and the CSS classes. There could be a “custom” option that applies a specific px size (the same way it works for colours) but by default we should let the theme handle the defined sizes. This also makes it possible to support relative units, non-px values, etc without confusion.

**Comment by aduth** [comment]
To previous comments, this is working as expected in that named sizes are not explicitly associated with a fixed value (and can change over time as the user switches themes). The pixel value acts as an override to this behavior.

**Comment by aduth** [comment]
Related: #10387

**Comment by chrisvanpatten** [comment]
@aduth Oh interesting — maybe this is a docs issue then?

**Comment by aduth** [comment]
@chrisvanpatten Perhaps. Where would it be documented? I see it as documentation of the specific built-in blocks' behaviors, which we don't have (but could be good as a user guide).

**Comment by chrisvanpatten** [comment]
@aduth well right now we document the use of a pixel value here: https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md#block-font-sizes

That implies an association between the named value and pixel value.

But it sounds like maybe the pixel value isn't necessary?

**Comment by chrisvanpatten** [comment]
I see… the size attribute in editor-font-sizes is used to generate the preview in the dropdown, but isn't applied inline. I have some ideas around this I'll explore in a PR at some point.
