### ISSUE TITLE
Get MediaUpload contents after upload

### ISSUE THREAD

**Issue by braco** [WordPress/gutenberg#10596]
Currently, there's no way to get source in MediaUpload (for example SVG):

```
<MediaUpload
    type="image"
    allowedTypes={['image/svg+xml']}
    onSelect={() => // GET SOURCE/CONTENTS OF SVG FILE HERE?
    }
/>		
```

This is a big problem since await/async components are not respected by Gutenberg, which means you can't manually fetch the source in the component.

SVG is a special case: it's incredibly common, and there aren't adequate alternatives for inline SVG. Even changing the fill color is a huge pain without being able to inline the content.

**Comment by braco** [comment]
Hacky solution for now:
```
						<MediaUpload
							type="image"
							allowedTypes={['image/svg+xml']}
							onSelect={({ url, name, alt, id }) =>
								fetch(url)
								.then(r => r.text())
								.then(iconSrc => 
									setAttributes({
										iconSrc,
									})	
								)
							}
```

**Comment by youknowriad** [comment]
> This is a big problem since await/async components are not respected by Gutenberg,

This is not a Gutenberg problem, if you want to use async/await in your components you can if your setup allows it.

> Hacky solution for now:

This seems like a decent solution for me.

I'm closing the issue, let me know if you need further help.
