### ISSUE TITLE
Bug: Keyboard shortcut: Removing embeds always removes the previous block

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#10592]
**Describe the bug**: When removing an embed using the `Option+Command+Backspace` keyboard shortcut, the previous block is removed as well, independent of whether it's an embed block or a different block.

**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Create two paragraph blocks.
- Create an embed block between the two.
- Click on the embed block and use `Option+Command+Backspace` to remove that block. 

**Expected behavior**: Removes only the embed block.

**What happens instead**: Removes the previous block as well, independent of whether the previous block is an embed block or a different block.

- [Video indicating this behaviour with the previous block being a paragraph block](https://cloudup.com/czEVIlDOQmf).
- [Video indicating this behaviour with the previous block being an embed block](https://cloudup.com/cNFAxbiomIr).
- [Video indicating this behaviour with the previous two blocks being embed blocks](https://cloudup.com/c_TShb8uZPU). Notice only that second and third ones are removed. The first block is unaffected.

**Extra notes**: Removing the block using the `Remove block` function in the gear menu works as expected.

**Desktop (please complete the following information):**
 - OS: macOS 10.14 - Mac OS Mojave 
 - Browser: Vivaldi 2.0.1309.37 (Stable channel) (64-bit)

**Comment by rossanafmenezes** [comment]
Tried this also using MAC OS Mojave. The Option+Command+Backspace removed only the embedded block on Chrome, Firefox and Safari using Premium, Free and Personal plans. What I noticed here is that the embed video (Youtube in my case) never works on the first time. I had to add the youtube link twice for it to go through. @arunsathiya  have you tried other browsers and had this issue or only with the Vivaldi Browser?

**Comment by arunsathiya** [comment]
@rossanafmenezes Can you test the same on Gutenberg on a local/WordPress.org install instead, please? 

I was able to reproduce this earlier on Vivaldi, but it does not seem to be the case on Vivaldi, Google Chrome and other browsers at the moment, with multiple themes, including `twentyseventeen`. That said, closing this report for now. // cc @designsimply as you had added `Needs testing` tag. 

>What I noticed here is that the embed video (Youtube in my case) never works on the first time. I had to add the youtube link twice for it to go through

I am unable to reproduce this. From what I see, there are [no similar reports either](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+YouTube+twice+is%3Aopen). Do you see this happening for specific browsers? What happens on Gutenberg on a local/WordPress.org install?
