### ISSUE TITLE
In date selection, please make a select to choose the year of the entry

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#10600]
Sometimes, you have very old entries, and you have to go to every month to get an old year. It should be easier if you could select the year in the calendar of the entry.

**Comment by Soean** [comment]
Hey @davidperezgar 
this feature was merged into master, 2 days ago in #7621 
It will be included in Gutenberg 4.1

**Comment by davidperezgar** [comment]
Nice to hear! Thanks!!!
