### ISSUE TITLE
FocusableIframe doesn't work on the frontend

### ISSUE THREAD

**Issue by andreyc0d3r** [WordPress/gutenberg#10608]
**Describe the bug**
FocusableIframe won't render on the frontend. Works fine in the backend.

**To Reproduce**
1. create a simple 'iframe' block (registerBlockType)
2. Once the block is live everything works fine
3. Replace 'iframe' with FocusableIframe
Backend still works, frontend doesn't show anyting, no errors either.

**Expected behavior**
We should see an iframe

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Gutenberg 3.9

**Comment by mahdiyazdani** [comment]
Same here, tested with GB 3.9 - WP 4.9.8

**Comment by youknowriad** [comment]
you can't use a react component (with lifecycle hooks) in the `save` function. The `save` function is only used to serialize the HTML of the block into post_content.

If you want to use `FocusableIframe` on the frontend, you'd likely need to `render` a wp.element/react application on the frontend instead.
