### ISSUE TITLE
custom block for gutenberg update block vanish old changes

### ISSUE THREAD

**Issue by manjeet-webkul** [WordPress/gutenberg#10607]
I created a plugin for custom block(Editable Text) of gutenberg, after sometime i updated my plugin, new changes working properly, but in my old blog, some changes has been fanish( eg:- tag classes removed )..... pls suggest me what can i do for it???

**Comment by earnjam** [comment]
@manjeet-webkul Did you ever resolve this issue? I'm not sure I understand the question.
