### ISSUE TITLE
Ctrl Alt Backspace and Linux

### ISSUE THREAD

**Issue by tradesouthwest** [WordPress/gutenberg#10604]
**Describe the bug**
Ctrl + Alt + Backspace is reserved in Linux for restart. Gutenburg uses this for Remove Block.

**To Reproduce**
1. Go to 'Three Dots'
2. Use kybrd shortcut to 'Remove Block'

**Expected behavior**
Remove block

**Screenshots**
 [google screenshot of issue](https://drive.google.com/file/d/1cAyU9Bl2PhLO5Au4awC0w0_eNocS0IZ8/view)

**Desktop (please complete the following information):**
 - OS: Linux (any brand) Mint - Apache LAMP
 - Browser all
 - Version WP 4.9.

**Additional context**

**Comment by pcfreak30** [comment]
See #10603

**Comment by ZebulanStanphill** [comment]
@pcfreak30 @tradesouthwest This was already fixed in 4.0, which currently has a release candidate available and should be released soon. See #10008.

https://make.wordpress.org/core/2018/10/11/whats-new-in-gutenberg-11th-october/

**Comment by Soean** [comment]
Should be fixed in the next release, so I am closing this ticket. You can reopen it, if it still exists in in 4.0
