### ISSUE TITLE
Don't focus title of demo content (don't focus when title exists)

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#10601]
See: 
https://github.com/WordPress/gutenberg/pull/9608#issuecomment-429647815

We should avoid focusing the title of the demo content as it skips over part of the content, which is something we should avoid on the demo page (which serves to intro users to Gutenberg content).

**Comment by aduth** [comment]
Is this really relevant for merge if the demo post is not intended to persist into the merge?

**Comment by tofumatt** [comment]
Oh wait, is that the case? There won't be a demo post for NUX?

If there's no demo post in WordPress 5.0 then this isn't relevant. We can just close it.

**Comment by aduth** [comment]
>There won't be a demo post for NUX?

This is my understanding, and has been reiterated throughout development (e.g. https://github.com/WordPress/gutenberg/pull/8551#issuecomment-410656582).

Unless there's a last-minute decision to the contrary, I'll assume it's not meant to be included in 5.0.

**Comment by tofumatt** [comment]
I'm gonna use the "I'm kinda new here" excuse despite working on Gutenberg since April.

That makes sense, but I just wasn't sure. Figured I'd track in case it's staying, which it seems it very clearly isn't. (Closed!) Thanks! 👍

**Comment by tofumatt** [comment]
lol and I hit the wrong button and reopened. Closing 4 realz now.
