### ISSUE TITLE
Delete Block Keyboard Shortcut can log you out of PC session

### ISSUE THREAD

**Issue by pcfreak30** [WordPress/gutenberg#10603]
**Describe the bug**
The shortcut to delete a block is mapped to logging out of a computer session in many linux distributions and the Os may intercept it or can cause unintended accidents if you are not focused on the right UI element

**To Reproduce**
1. Try to delete a block via keyboard shortcut, and potentially get logged out

**Expected behavior**
Delete the block only

**Desktop (please complete the following information):**
 - OS: Release Linux Mint 18.2 Sonya 64-bit, Kernel Linux 4.15.0-29-generic x86_64, MATE 1.18.0
 - Browser Version: 69.0.3497.100 (Official Build) (64-bit)
 - Version: 69.0.3497.100

**Comment by tradesouthwest** [comment]
I tested this as well, pcfreak30, and I can not figure out why any programmer would use a OS command for (anything). Hope they have some kybrd shortys left. Ctrl + Alt + Backspace is not a good choice IMHO.

**Comment by ZebulanStanphill** [comment]
@pcfreak30 @tradesouthwest This was already fixed in 4.0, which currently has a release candidate available and should be released soon. See #10008.

https://make.wordpress.org/core/2018/10/11/whats-new-in-gutenberg-11th-october/

**Comment by Soean** [comment]
Should be fixed in the next release, so I am closing this ticket.
