### ISSUE TITLE
Translate message displayed at preview

### ISSUE THREAD

**Issue by tmatsuur** [WordPress/gutenberg#10609]
The message to be displayed is not translated When the preview button is pressed.

/packages/editor/src/components/post-preview-button/index.js : 93-94
`<p>Please wait&hellip;</p>
<p>Generating preview.</p>`

The time to display the message is short, but I think that it is better to translate it in each language.

**Comment by Soean** [comment]
Hey @tmatsuur 
thanks for reporting this issue. We already have an open ticket about the missing translation #7725, so I am closing this ticket.

**Comment by tmatsuur** [comment]
Thank you for your comment. 
It seems that confirmation was not enough.
