### ISSUE TITLE
Paragraph Block - Saves extra HTML when Grammarly chrome application is on.

### ISSUE THREAD

**Issue by vrundakansara** [WordPress/gutenberg#10610]
**Describe the bug**
An extra HTML appears in the frontend when one adds a paragraph and simultaneously Grammarly chrome extension is enabled.

**To Reproduce**
1. Add Grammarly extension to Chrome Browser - https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en
2. Click on Paragraph Block and add some content and use Grammarly to spell check the content.
3. Save and see the frontend page.
4. See error while inspecting the element in Chrome development tool

**Expected behavior**
It is expected that the extra Grammarly HTML should be stripped.

**Screenshots**
Here is a screenshot of the saved Grammarly HTML - http://bsf.io/jxvcd

**Desktop**
 - OS: Windows 8.1 Pro
 - Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
 - Browser Extensions - Grammarly

**Comment by youknowriad** [comment]
Unfortunately this isn't immediately actionable within Gutenberg, I suggest raising this issue to the Grammarly extension authors.
