### ISSUE TITLE
(Safari) Caret erroneously present during cursor-based multi-select

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#10617]
**Describe the bug**
When multi-select mode is triggered using the cursor (i.e. clicking and dragging across blocks), the caret is left active in the selected region (typically, the caret is placed wherever the mouse button was released).

This becomes a problem when the user expects certain multi-select-specific keyboard interactions — <kbd>Backspace</kbd> to delete the selected blocks, _copy_ actions, etc. — which are then missing.

So far, I have not experienced this in Firefox nor Chrome, only Safari.

**Expected behavior**
After multi-selecting a group of blocks with the mouse, I should be able to press <kbd>Backspace</kbd> to delete them.

**Screenshots**
![safari-cursor-multiselect](https://user-images.githubusercontent.com/150562/46955614-41563380-d08b-11e8-9bd0-ea9fe9b90ea7.gif)

**Desktop (please complete the following information):**
 - macOS, latest
 - Safari, latest

**Comment by iseulde** [comment]
Cannot reproduce any longer. Perhaps fixed by #13697?

**Comment by mcsf** [comment]
I can still repro, but in much stricter circumstances. It seems to be a thing of certain motion heuristics in Safari. I need to drag-to-select fairly quickly and vertically from one textual block to the previous block.

Here is a [screencast](https://cloudup.com/cmL99HbrXQW), shot in video for greater precision.

Given how much harder it seems to trigger, and depending on your own judgment, I wouldn't oppose to closing this issue.

**Comment by iseulde** [comment]
👍 I'll have another look when there is time.

**Comment by mcsf** [comment]
Thanks, though we can consider it low priority.

**Comment by mcsf** [comment]
I can't really repro this one, I think it's fair to close. These selection actions feel much more solid nowadays.
