### ISSUE TITLE
Date: Mark getSettings as experimental

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#10627]
As discussed in [7669](https://github.com/WordPress/gutenberg/pull/7996/files#r224152849) `getSettings()` in `wp-date` should be marked as experimental

**Comment by aduth** [comment]
Note that renaming a publicly exposed function is considered a breaking change and thus is subject to a deprecation migration period.

https://wordpress.org/gutenberg/handbook/reference/deprecated/
