### ISSUE TITLE
Make it easier for a contributor to determine what failed their build

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10625]
Currently, it can be a bit difficult to determine why a build failed:

![image](https://user-images.githubusercontent.com/36432/46967489-849dab80-d065-11e8-8d50-d5e5a15d1167.png)

![image](https://user-images.githubusercontent.com/36432/46967374-338db780-d065-11e8-9e70-751ccb7b9932.png)

A couple of enhancements we could make:

1. More clearly summarize build failures at the end of each job.
2. In the Travis environment variables, document which tests are running so there's some simple reference of what might've failed.

From https://wordpress.slack.com/archives/C02RQC26G/p1539620166000100

**Comment by talldan** [comment]
One idea I had is that when a job fails, documentation about the specific test failure could be posted in the PR. 

E.g. If one of the E2E test jobs fails, post a link to details about how to debug/fix e2e test issues.

I haven't looked into the implementation details. I'd imagine the travis job would have to send a request or trigger a github webhook when failing.

**Comment by aduth** [comment]
Doing a bit of triage today in the [Project Management Automation project board](https://github.com/WordPress/gutenberg/projects/24).

>One idea I had is that when a job fails, documentation about the specific test failure could be posted in the PR.

While the original issue here was deemed closed by #15229, worth noting that there is still an idea card in the project board which encompasses a similar sort of automation enhancement:

>Automatically comment when someone's pull request has a build failure occur (or try a restart automatically with exponential backoff). The comment should include a link to "next steps"  instructions, ideally specific to the sort of job which failed (end-to-end test, linting, etc).

https://github.com/WordPress/gutenberg/projects/24#card-17442118
