### ISSUE TITLE
Embeds: Alignment issues for WP and Embed blocks

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#10633]
When adding a WP or Embed block, you can select an alignment option. These options unfortunately do nothing except add a class to the wrapping div. This is fine for most blocks, but since the WP and Embed blocks use iframes to add the content, it doesn't really help them. Choosing Left, Right or Center does not align the embed block at all. Choosing Wide or Full only works when "Automatically scale content" is selected, but because of this #10419 you can't currently use this option.

**To Reproduce**
1. Add a WP block
2. Select an alignment option

**Expected behavior**
All alignments should actually work

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and Firefox
 - Version: Latest

**Additional context**
- WP 4.9.8 and 5.1-alpha-20181012.162003
- Gutenberg 4.1.0-alpha-0ea7c43

**Comment by GlennMartin1** [comment]
+1

It would be very helpful to be able to center embeds.

**Comment by youknowriad** [comment]
Is this still an issue? There has been a lot of improvements to the Embed blocks since.

**Comment by GlennMartin1** [comment]
@youknowriad It's resolved for me - thanks!

**Comment by youknowriad** [comment]
Thanks for testing @GlennMartin1
