### ISSUE TITLE
'delete' key does not remove text within block

### ISSUE THREAD

**Issue by dariaknl** [WordPress/gutenberg#10643]
**Describe the bug**
Removing content within Paragraph block with `delete` key does not remove it.

**To Reproduce**
1. Go to edit post.
2. Add Paragraph block.
3. Add text to this block.
<img width="631" alt="screen shot 2018-10-16 at 07 44 20" src="https://user-images.githubusercontent.com/19681708/46995062-5c6e8500-d117-11e8-9c73-3bcd8c4661b3.png">

4. Click to Update your post.
5. Go to edit this post.
6. Select your text and press `delete`. 
7. See that the text is removed but "Update" button is still not active.
<img width="918" alt="screen shot 2018-10-16 at 07 47 12" src="https://user-images.githubusercontent.com/19681708/46995159-c1c27600-d117-11e8-94d1-1cfaac8e61a0.png">

8. Click somewhere outside of Paragraph block so that "Update" button becomes active.
9. Click to Update your post.
10. Reload the page.
11. See that the text is presented:
<img width="612" alt="screen shot 2018-10-16 at 07 49 06" src="https://user-images.githubusercontent.com/19681708/46995214-fa624f80-d117-11e8-84f6-bebd88fad2f8.png">
12. If you repeat the same steps but using `backspace` key, the text is really removed.

**Expected behavior**
Text is expected to be removed when using `delete` key.

**Desktop (please complete the following information):**
 - Mac keyboard and HP Pro book
 - Browser Chrome (but the issue is not browser specific)

**Additional context**
- Gutenberg 3.9.0

**Comment by dariaknl** [comment]
The issue seems to be fixed in 4.4. Can you please confirm?

**Comment by arunsathiya** [comment]
I can confirm that I am not able to reproduce this anymore on Gutenberg 4.5.1. 👍🏽

- The update button is available after making edits to text. 
- Refreshing the page after an update shows the updated version.
