### ISSUE TITLE
Remove all PHP code from the Gutenberg plugin

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10656]
After WP 5.0 is released and the Gutenberg plugin's minimum-supported version is 5.0, we should remove all PHP code from the plugin. This includes, but isn't limited to:

* [ ] `WP_Block_Type_Registry`, `WP_Block_Type`
* [ ] `WP_REST_Autosaves_Controller`
* [ ] `WP_REST_Block_Renderer_Controller`, `WP_REST_Blocks_Controller`
* [ ] `WP_REST_Post_Search_Handler`, `WP_REST_Search_Controller`, `WP_REST_Search_Handler`.
* [ ] `lib/rest-api.php`

We need to keep this PHP code in Gutenberg in the interim, so it's still possible to install Gutenberg on a `4.9.x` installation.

**Comment by altrovideo** [comment]
`Fatal` error: Cannot declare class WP_REST_Search_Controller`
This forced me to remove Gutenberg , wp-admin couldn't be accessed

**Comment by altrovideo** [comment]
Fatal error: Cannot declare class WP_REST_Search_Controller, because the name is already in use in /var/www/mywordpress/wp-content/plugins/gutenberg/lib/class-wp-rest-search-controller.php on line 0

**Comment by danielbachhuber** [comment]
@altrovideo Are you running the `5.0` branch? If so, you'll need to wait for Gutenberg 4.1 to land as it has the code that conditionally loads these classes #10531

**Comment by altrovideo** [comment]
Yes I'm running WP 5.0 nightly build, I'll wait for 4.1, Thanks @danielbachhuber

**Comment by danielbachhuber** [comment]
Closing in favor of #11015
