### ISSUE TITLE
Permalinks: post always stay /?p... even if I change the slug

### ISSUE THREAD

**Issue by Wundertastisch** [WordPress/gutenberg#10653]
**Describe the bug**
I just created and scheduled my first post with gutenberg. While it does show the appropriate slug in the title area. It still uses the link /?p... when clicking on it. And it also says 'The post address will be: .../?p... when I schedule it. If I go to the post overview and click quick edit it shows the slug I entered but leads to /?p... when I click it. If I try to visit the page with the slug I entered I get a 404 error message.

**Steps to reproduce the behavior:**
1. Create a new post.
2. Fill it with some content.
3. Schedule it.
4. In the window at the right it says 'The post address will be: .../?p...' instead of the slug I entered.

**Expected behavior**
What should happen is that it shows me the slug I choose in 'The post address will be:' and I don't get a 404 message, when trying to open the appropriate page as long as I'm logged in.

**Screenshots**
![gutenberg_errorm](https://user-images.githubusercontent.com/44205430/47028891-961cab80-d16a-11e8-8844-ad200fb30363.jpg)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra Version 10.13.6
 - Browser: Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version 3.9.0

**Comment by arunsathiya** [comment]
Can confirm this is the behaviour as well. 

<img width="1144" alt="screenshot 2018-10-17 at 21 12 47" src="https://user-images.githubusercontent.com/18581859/47098765-7a400500-d251-11e8-81da-5db36d7bd5e2.png">

The permalink settings:

<img width="609" alt="screenshot 2018-10-17 at 21 12 56" src="https://user-images.githubusercontent.com/18581859/47098775-7f9d4f80-d251-11e8-94be-69d751da546b.png">

 --- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.9.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave

**Comment by designsimply** [comment]
Ace. Thanks for testing and finding the other issue @arunsathiya! And thank you for reporting the issue @Wundertastisch.

Closing and consolidating to #10223.
