### ISSUE TITLE
Unnecessary statement in function gutenberg_editor_scripts_and_styles

### ISSUE THREAD

**Issue by tmatsuur** [WordPress/gutenberg#10671]
Variable acquired by function was not used, so I will report it.

lib/client-assets.php: 1445
`$file     = get_theme_file_path( $style );`

**Comment by designsimply** [comment]
I don't know enough to know whether that variable is used for extensibility or not. Apologies if this is an obvious question, but would you mind explaining for me how you know for sure the variable would never be used?

**Comment by tmatsuur** [comment]
I do not deny the possibility of using this variable in future versions.

The reason for deciding this variable to be unused is shown below.

1. variable $file is not global declared.

2. variable $file is not referenced in the function nor in the file.

3. I often store it in a variable to check the return value of a function during development. Again in this case, I guessed the programmer forgot to delete it.

The following excerpt is from line 1511 of version 4.1.1:
`$file     = get_theme_file_path( $style );`

line 1513:
`'css'     => file_get_contents( get_theme_file_path( $style ) ),`

**Comment by youknowriad** [comment]
Seems like this is already fixed.  Thanks
