### ISSUE TITLE
Users can create reusable 'column' block.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#10679]
**Describe the bug**
Since #10545 was merged it's now easy for a user to select a column in a columns block. It's also really easy to turn that selected column into a reusable block. 

That reusable block can't really be used anywhere, which perhaps makes it worthless, but also it causes layout issues with the columns (see screenshot).

I'm not sure if this has always been possible or if it's a regression. If the former, I wonder if we need a `supports.reusable` setting in the block api to prevent this?

**To Reproduce**
1. Add a new columns block
2. Add some content to the columns
3. Open the block navigation popover
4. Select one of the 'column' blocks
5. Using the more menu, add the column to reusable blocks
6. Observe that the columns don't maintain their width (see screenshot)

**Expected behavior**
Either a) the column should not be allowed to be added as a reusable block, or b) the columns should maintain their widths

**Screenshots**
![screen shot 2018-10-17 at 4 10 35 pm](https://user-images.githubusercontent.com/677833/47071949-7d260000-d227-11e8-840f-624c00fe3b1f.png)

**Additional context**
- Gutenberg 4.1

**Comment by slimmilkduds** [comment]
The ability to place columns in reusable blocks is far from useless. You can setup complete complex layouts this way using reusable blocks. The only thing that makes that not work right now is that nested blocks arent preserved when converting reusable blocks to regular blocks but there’s tickets for that.

**Comment by slimmilkduds** [comment]
Deleted my comment since I misread ”column” as ”columns”, sorry!

**Comment by mtias** [comment]
Makes sense to disable this for "column".

**Comment by chrisvanpatten** [comment]
Should it be tied to `supports.inserter`? I'm typically all for more granularity so that doesn't proclude a `supports.reusable` but it seems safe to assume if you don't support an _inserter_ context, you shouldn't support _reusable_ either.

**Comment by noisysocks** [comment]
Disabling _Add to Reusable Blocks_ when `supports.inserter` is truthy sounds 👌 to me.

**Comment by noisysocks** [comment]
Related: https://github.com/WordPress/gutenberg/pull/10493

**Comment by noisysocks** [comment]
We talked about adding `supports.reusable` once but decided against it in https://github.com/WordPress/gutenberg/pull/5970.

I'd be 👌 with adding `supports.reusable` and making `core/column` and `core/freeform` have `supports.reusable: false`. It's more clear now than in April when I opened the aforementioned PR that there is a need for such a property:

1. To disable converting Column blocks to reusable
2. To disable converting Classic blocks to reusable, see https://github.com/WordPress/gutenberg/issues/5941
3. To fulfil a need expressed by third party plugin developers, see https://github.com/WordPress/gutenberg/issues/4722

**Comment by ZebulanStanphill** [comment]
> Disabling _Add to Reusable Blocks_ when `supports.inserter` is truthy sounds ok_hand to me.

I think you mean falsy?

Anyway, I would prefer a separate `supports.reusable` flag, given the desire to make Classic blocks unable to be saved as reusable blocks.

**Comment by noisysocks** [comment]
> I think you mean falsy?

Yes, I do 🙂

**Comment by mtias** [comment]
Let's add this, but I'm not sure about the support name.
