### ISSUE TITLE
Latest Posts block: missing class "has-dates" on the front-end

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#10691]
Gutenberg version: **4.0.0**
WordPress version: 4.9.8

The class `has-dates` is missing from the block front-end code (parent `<ul>` element) when "Display post date" is active on the block settings.

![display-post-date](https://user-images.githubusercontent.com/1451087/47100421-d1bc8180-d20d-11e8-92e5-c59121f281ae.png)

![class-has-dates-missing-front-end-code](https://user-images.githubusercontent.com/1451087/47100458-e1d46100-d20d-11e8-8668-42f5ad356d1c.png)

Should be:

````html
<ul class="wp-block-latest-posts has-dates">
    <li>
    	<a>...</a>
    	<time>...</time>
    </li>
</ul>
`````

The `has-dates` class is added to the Latests Comments block when the option to display dates is activated, so this block should add it too.

**Comment by designsimply** [comment]
Adding the `Needs Design Feedback` to get a green light or counterpoint for whether or not `has-dates` class should be added to the Latest Posts block in order to be consistent with the Latest Comments block.

**Comment by karmatosed** [comment]
I don't see an issue with showing it if people use it in themes.

**Comment by youknowriad** [comment]
Removing the milestone as this is not really a regression in 4.1 RC
