### ISSUE TITLE
Custom classes do not persist in the Archives block

### ISSUE THREAD

**Issue by mikedance** [WordPress/gutenberg#10700]
**Describe the bug**
Users can add custom classes with the Archives block, but these classes will eventually disappear when the post is returned to and saved later.

**To Reproduce**
1. Create a new post
2. Add an Archives block with the custom class "myclass"
3. Save post
4. In same tab, go to post on frontend to verify "myclass" has been added
5. Click "Edit Post" in toolbar to reload edit screen
6. Re-save post
7. Go to post on frontend: "myclass" is no longer present

**Expected behavior**
Additional CSS classes should stay saved. The issue appears to be that when reloading the edit screen, Gutenberg doesn't notice the custom class should be there, so the "Additional CSS class" field is empty. Therefore, when you save again, WordPress assumes you removed the class, and gets rid of it.

**Comment by Soean** [comment]
Have you testet with Gutenberg 4.0? We fixed this issue in #9995

**Comment by mikedance** [comment]
Fixed, thanks
