### ISSUE TITLE
Not Working Ever Since After Choosing Featured Image 

### ISSUE THREAD

**Issue by dogecoin2018** [WordPress/gutenberg#10715]
**Describe the bug**
Always getting this error every time:

- Opening/Selecting an Category for a post
- Choosing Featured Image

The workaround I do before to make Gutenberg work temporarily was to flush all of the browser local storage and cookies, then re-login. Creating post works and I can edit post, but still the error will show once I do the list above. I always use the classic editor just to apply the category and featured image.

After the update last month, the error becomes permanent - this is after I choose a features image for my post, the error shows up. Even clicking the Add New or Editing a post for the first-time, the error still showing up.

**To Reproduce**
1. Clicking "Add New"
2. Selecting Featured Image or Selecting a Category of a post
3. Error shows "The Editor has encountered an unexpected error."

**Expected behavior**
No error should pop up after doing the above list.

**Screenshots**
http://d.gaming.ph/47Wslc

![gutenberg-report](https://user-images.githubusercontent.com/1119271/47303375-f4b9ad80-d5e0-11e8-9de1-a1eaf47acfd4.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 69.0.3497.100 (Official Build) (64-bit

**Additional context**
Currently using version 4.0.0. I am also using keycdn.com as my CDN and server is nginx. I've also tried removing all the plugins to see if its a conflict, but nothing works.

**Comment by dogecoin2018** [comment]
Here is the complete error message:

TypeError: Cannot read property 'show_ui' of undefined
    at https://gamingph.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1539827003:50:247839
    at i (https://gamingph.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:636)
    at An.filter (https://gamingph.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:53498)
    at https://gamingph.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1539827003:50:247804
    at yh (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:95:430)
    at lg (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)

**Comment by designsimply** [comment]
Thank you for testing Gutenberg at this stage and for including the error message from your browser console!

I tested adding a featured image and a new category just now with WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 and both worked in my test.

I searched this repository for "TypeError: Cannot read property 'show_ui' of undefined" and found several results:
https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=is%3Aissue+%22TypeError%3A+Cannot+read+property+%27show_ui%27+of+undefined%22+

Are you able to try either of the following solutions which others have tested and found to help them when they saw the same error?

1. https://github.com/WordPress/gutenberg/issues/9912#issuecomment-423099220
1. https://github.com/WordPress/gutenberg/issues/10162#issuecomment-424759622

**Comment by dogecoin2018** [comment]
Awesome! @designsimply the solution for 2. #10162 , works! Thank you so much!

I was using this nginx rules before..
try_files $uri $uri/ /index.php?args;

then change to, but still doesn't work..
try_files $uri $uri/ /index.php?$is_args$args;

finally! it works on this rules..
try_files $uri $uri /index.php?args;

**Comment by gziolo** [comment]
I read that issue was resolved, thanks for reporting back 👍
