### ISSUE TITLE
Ability to choose wich types uses gutenberg

### ISSUE THREAD

**Issue by Xiytiifu** [WordPress/gutenberg#10718]
On 100% of my websites, i use Visual Composer to build pages for my clients. I don't use it on posts because it's not necessary. I tried Gutenberg on one of my site but it has broke visual composer loading on pages.

I would like to use Gutenberg and visual composer together : VC for advanced build of the site (me) & Gutenberg for writting fancy pretty posts (me & my client)
So, i would like to have the ability to choose on wich type of post i want gutenberg activated (like VC into options page) to prevent incompatibility ...

The only alternative with my actual workflow is : not using Gutenberg ... so :(

**Comment by ajitbohra** [comment]
Gutenberg Ramp plugin adds a settings screen where you can enable Gutenberg selectively (for specific post types). For even greater control, you can specify Gutenberg loading behavior in code. Ramp works with both the plugin version of Gutenberg, and the core version, providing a seamless transition.

https://wordpress.org/plugins/gutenberg-ramp/

**Comment by Xiytiifu** [comment]
🤨🧐 Plugin + plugin + plugin + plugin + plugin ..... why do not include the feature natively ?
Gutenberg option page is completely empty ...
