### ISSUE TITLE
Missing inline formatting is a Gutenberg killer!

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#10728]
**Is your feature request related to a problem? Please describe.**
I use regularly inline formatting - for single words and even characters in paragraphs and lists - like: 
**Text-Color**, Background-Color, Underline, Font-Family, Font-Size, **Justify**, ...
Inserting: special characters, unformatted text, **Nonbreaking space**, Subscript, Superscript …
Until now I can do this with TinyMCE (Classic Editor) and the help of plugins like TinyMCE Advanced (more than 2 Million users!)

But in Gutenberg there are no such inline formatting possibilities and the toolbar is not extensible by TinyMCE Advanced and other plugins. And font size and colour for a whole block (and only paragraph!) is no sufficient replacement for real inline formatting within a block!

To be honest, without real inline formatting I can't even imagine to use Gutenberg!

And at least more than 2 Million TinyMCE Advanced users have the same problem ...

**Describe the solution you'd like**
1.) Bring back inline formatting from TinyMCE
2.) Make a reduced/full inline formatting set optional => for those, who (don't) like/need real inline formatting.
3.) Make toolbar extensible for plugins

**Describe alternatives you've considered**
a) never ever update to WordPress 5.0
b) use Classic Editor for the rest of my life
c) use Gutenberg, but only classic block (crazy!!!)

**Comment by Soean** [comment]
Related #4658 `TinyMCE Custom Buttons and Extensibility`

**Comment by iseulde** [comment]
This is being worked on, see #4658.

**Comment by Misiu** [comment]
@ellatrix if I understand correctly Justify can be added back as a plugin using Format API - https://github.com/WordPress/gutenberg/pull/10209?

**Comment by phpbits** [comment]
@burnuser @Misiu You can use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I've added the missing Classic Editor formats to Gutenberg block editor. Thanks!

**Comment by Soean** [comment]
Gutenberg now also includes inline text color.

**Comment by Misiu** [comment]
@Soean but does it includes `justify`?

**Comment by phpbits** [comment]
@Misiu With EditorsKit plugin, yes.
