### ISSUE TITLE
Datepicker: Start of week not respected

### ISSUE THREAD

**Issue by Drivingralle** [WordPress/gutenberg#10729]
**Describe the bug**
The datepicker to pick the publish date doesn't respect the start_of_week option as set in Settings->General.

**To Reproduce**
1. Visit Settings->General
2. Set Start of Week day to monday
3. Create new post or edit an existing post
4. Click the publishing data/time link to open date-picker

**Expected behavior**
I have setup my site to use Monday as first day of the week as usal in Germany. While publishing a post I got quite confused as the calender was off from what I expect in localiced software.

I find this behavior unactable. 

**Screenshots**
https://cloudup.com/iyeGcMuRcJ2
https://cloudup.com/iH4W5f5jS6T

**Desktop (please complete the following information):**
 - OS: macOS X latest
 - Browser: firefox, chrome
 - Versions: latest

**Additional context**
- Gutenberg 4.0.0

**Comment by Soean** [comment]
Hey @Drivingralle 
thanks for reporting this issue. We already have a ticket about this problem see #9109. So I am closing this one.

**Comment by Drivingralle** [comment]
Interesting. My search for issues about it didn't bring it up
