### ISSUE TITLE
blocks in "Manage Reusable Blocks" opening empty

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#10725]
**Describe the bug**
The option "Manage Reusable Blocks" leads to a listing of all saved reusable blocks. => OK
Blocks can be deleted (send to trash bin) => OK
Quick Edit works also => OK
But click on such a block opens an empty "edit post" screen without title/blockname and content. => ?

**Expected behavior**
Make selected reusable block editable OR remove edit link!

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox + Chrome
 - Gutenberg 4.0 (but problem exists already before)

**Comment by chrisvanpatten** [comment]
Thanks @slimmilkduds, I’m going to close this in favour of #9964 since we already have that ticket open. Let’s keep the discussion consolidated there. Cheers!
