### ISSUE TITLE
Suggestion: User Selectable Editor Modes

### ISSUE THREAD

**Issue by dmccan** [WordPress/gutenberg#10736]
I'd like to suggest that Gutenberg have 3 editor modes:

-Modern:  Current Gutenberg
-Accessible:  Optimized for accessibility
-Custom:  Allow developers to customize the editor page and create custom editor layouts using (added) built-in option settings. 

Instead of trying to have one mode to suite everyone, program in flexibility.  Thank you for your consideration,

David

**Comment by designsimply** [comment]
Thank you for the feedback and for taking time to consider and test Gutenberg at this stage.

All modes should be accessible, and you can read a bit more about the work that has been done about that so far at https://make.wordpress.org/core/2018/10/18/regarding-accessibility-in-gutenberg/

In Phase 1, all of the mechanisms necessary to make the editor into a block editor are going into place first. Customization is planned for Phase 2.

Developers may already make some modifications to the editor page such as [applying styles with stylesheets](https://wordpress.org/gutenberg/handbook/blocks/applying-styles-with-stylesheets/) and adding [templates](https://wordpress.org/gutenberg/handbook/templates/) and more customization features are expected to be added.
