### ISSUE TITLE
"Import from JSON" not translated in reusable blocks management

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10738]
Hello,

like mentioned on slack, the string "Import from JSON" is not taking it's translation, which is already there.

https://wordpress.slack.com/archives/C02QB2JS7/p1539868976000100

![image](https://user-images.githubusercontent.com/18373563/47158919-f9cee200-d2ec-11e8-80bc-c7908e8d2a68.png)

**Comment by youknowriad** [comment]
We should load the locals in this page similarly to how we do in the Gutenberg page.
