### ISSUE TITLE
Handbook: Block Grammar Page Needs updating

### ISSUE THREAD

**Issue by mrmadhat** [WordPress/gutenberg#10734]
**Describe the bug**
When viewing the [Block Grammar](https://wordpress.org/gutenberg/handbook/language/grammar/) page on wordpress.org the style tags are being stripped resulting in css being output onto the page.

The page is also very difficult to understand and doesn't give any supporting content to explain what the writer is trying to explain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://wordpress.org/gutenberg/handbook/language/grammar/
2. See css at top of page

**Screenshots**

![Image of css output on page](https://i.imgur.com/PgrI1EN.png)

**Comment by mtias** [comment]
This has been updated (still doesn't look great, but loads correctly).
