### ISSUE TITLE
Enhancement: Image to be retained on changing back to "Cover image" block from "Image" block

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#10747]
## Behaviour when changing the block from `Cover image` -> `Heading`  -> `Cover image`

- When I add a cover image with a text on it, change this block type to `Heading` and change it back to `Cover image` block type, the image is seen to have disappeared. 

<img width="659" alt="screenshot 2018-10-18 at 21 47 53" src="https://user-images.githubusercontent.com/18581859/47168903-bd68a980-d31f-11e8-84ff-9f2babf2a6b2.png">
<sup>Image showing a Cover image block with an image and text on it</sup> 

<img width="665" alt="screenshot 2018-10-18 at 21 49 10" src="https://user-images.githubusercontent.com/18581859/47168872-ac1f9d00-d31f-11e8-971a-5ba9d5087f06.png">
<sup>On changing the block back to Cover image type, the image and the text are seen to be lost</sup> 

## Behaviour when changing the block from `Cover image` -> `Image`  -> `Cover image`

The situation explained earlier is not the same case when I change the `Cover image` block to `Image` block first, and then change it back to `Cover image`. It can be noticed that the text on this block is retained as well, as a caption! I think this would be the behaviour users would hope to see on the previous point as well.

<img width="639" alt="screenshot 2018-10-18 at 21 48 20" src="https://user-images.githubusercontent.com/18581859/47169028-16384200-d320-11e8-9abd-4ea9234f76a1.png">
<sup>The image exists as an Image block with the previous text as a caption</sup> 

## Describe the solution you'd like

When I change the `Image` block (which was previously a `Cover image` block) back to `Cover image` block, the image is to be retained.

**Comment by johngodley** [comment]
The current behaviour seems to make sense to me. Block conversions are generally one way and data can be lost along the way. There is no image associated with a heading, so when you convert a cover image to a heading the image information will be lost. Converting a cover image to an image retains the image data.

**Comment by mtias** [comment]
Yes, this is expected behaviour. There might be improvement to make, but would need to be handled on a case by case basis.
