### ISSUE TITLE
Residual border line after hover on paragraph block (Safari)

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#10741]
**Describe the bug**
After hovering over multiple paragraphs the block border lines seems to stay around for a while longer than they intuitively should

- I tried to reproduce in Google & Firefox, and it seems to be Safari only. 
- I also added other blocks, Twitter embed and image block and did not see any residues there. It appears to be isolated to the paragraph block 

**To Reproduce**
1. Use Safari Browser
2. Add a few paragraph block
3. Select one and then hover over the others with the mouse.
4. See block border residue on all touched paragraphs. 

**Expected behavior**
Expectation is that the block borders stay hidden until they are needed and disappear all at the same time. 

**Screenshots**
This issues was first reported by @JJJ [ on Twitter.](https://twitter.com/JJJ/status/1052687993239203840) with Theme Twenty-Nineteen.
I tested it with Twenty-Seventeen. The 'artifacts' were there, but not as dramatic as in Twenty-Nineteen Theme. 
Here is a video: 
http://recordit.co/r4WeRSmLPw 

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Browser : Safari v 12

**Additional context**
Gutenberg 4.0 
Not sure if this is a theme issue or a Gutenberg issue. (sorry)

**Comment by chrisvanpatten** [comment]
I have this issue as well with Safari but I think unfortunately it’s just a quirk in the way Safari draws to the screen. It’s something I’ve run into on other projects as well.

**Comment by tofumatt** [comment]
The fix in #10892 caused #11125, so reopening this as I'm going to revert #10892.

**Comment by jasmussen** [comment]
So, this is interesting. Even though the fix has been reverted, I'm no longer seeing the residual outlines in Safari in master at all. Can anyone else confirm?

**Comment by bph** [comment]
Just tried to reproduce it and it seems, this issue is resolved. Closing it.
