### ISSUE TITLE
Docs: add_theme_support( 'responsive-embeds' )

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#10759]
`add_theme_support( 'responsive-embeds' );` was added in #10477.
We should add it to the [docs](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md), see also https://github.com/WordPress/gutenberg/pull/10477#issuecomment-428854033

**Comment by desrosj** [comment]
Thanks, @Soean! 

Related: https://core.trac.wordpress.org/ticket/45125

**Comment by Soean** [comment]
Docs were added in #11011
