### ISSUE TITLE
Enhancement: Publish prompts on page editor refer to "post" while it should be "page"

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#10750]
## Pre-publish prompt 

🚨 Starting at a page editor, on clicking the `Publish` button at the top right, one can notice this text `Double-check your settings, then use the button to publish your post.` as a pre-publish prompt. This can be improved to `Double-check your settings, then use the button to publish your page.`

![screen shot 2018-10-18 at 21 58 46](https://user-images.githubusercontent.com/18581859/47169801-189b9b80-d322-11e8-9f3a-652e7fbea528.png)

## Result post publish/update

🚨 On a similar note, after publishing the page, it can be noticed that the result reads `Post published! View post` which can be updated to `Page published! View page`

✅ It can also be noticed that the `View page` button on the right is as expected. 

![screen shot 2018-10-18 at 22 03 03](https://user-images.githubusercontent.com/18581859/47169847-2e10c580-d322-11e8-903b-3b76bba30935.png)

🚨 Same can be said for updates made to a page.

![screen shot 2018-10-18 at 22 08 06](https://user-images.githubusercontent.com/18581859/47169909-58fb1980-d322-11e8-9a4e-423ce45e1c42.png)

**Comment by GlennMartin1** [comment]
Set to be fixed in upcoming 4.1 release.

**Comment by Soean** [comment]
The pre-publish prompt `Double-check your settings, then use the button to publish your post.` still is an issue in 4.1.

**Comment by danielbachhuber** [comment]
> The pre-publish prompt `Double-check your settings, then use the button to publish your post.` still is an issue in 4.1.

We may want to re-evaluate `Double-check your settings, then use the button to publish your post.` as a string, as every custom post type will need to define it. Doing so seems less than ideal.

**Comment by bobbingwide** [comment]
Meanwhile, in the Tips it's the other way around. I'm editing a post and the tips talk about page. 

You’ll find more settings for your page and blocks in the sidebar. Click “Settings” to open it.

Click “Preview” to load a preview of this page, so you can make sure you’re happy with your blocks.

**Comment by swissspidy** [comment]
> Doing so seems less than ideal.

Agreed. What about something more general like `Double-check your settings, then use the button to publish your content.`?

**Comment by sarahmonster** [comment]
Making that string a bit more vague might be the right call here. There's definitely an opportunity to reduce awkwardness. We probably don't need to tell people to use a button (or if we do, we should consider improving the interface so it's more clear!)

We'll also need to reconsider: `Your post will be published at the specified date and time.` which suffers from the same issue.

What about instead:

`Double-check your settings before publishing.`
and 
`Your work will be published at the specified date and time.`

**Comment by kristastevens** [comment]
Hello! Answering the copy review bat signal...

Since this phrase is used in multiple context, I agree that a more generic approach would be best. I love what @sarahmonster proposes above: 

` Double-check your settings before publishing.`
and
`Your work will be published at the specified date and time.`
