### ISSUE TITLE
4.0.0 Not compatible with Yoast 8.4

### ISSUE THREAD

**Issue by yrslvkzk** [WordPress/gutenberg#10757]
**Description:** 
Updated plugin to 4.0.0
Updated Yoast to latest 8.4
Using OceanWP template 
Tested with all other plugins switched off  
Can not create or edit existing Gutenberg posts. 

Console shows following error: 
react-dom.min.82e21c65.js:110 ReferenceError: YoastSEO is not defined
    at f (wp-seo-post-scraper-840.min.js?ver=8.4:1)
    at o (wp-seo-post-scraper-840.min.js?ver=8.4:1)
    at t.value (wp-seo-post-scraper-840.min.js?ver=8.4:1)
    at Xf (react-dom.min.82e21c65.js:91)
    at yh (react-dom.min.82e21c65.js:102)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)

**To Reproduce**

1. Click on 'Edit post of Create new post'
2. See error

**Expected behavior**
A gutenberg window for post editing should appear.

**Screenshots**
https://prnt.sc/l7p868

![download 3](https://user-images.githubusercontent.com/1119271/47185892-07379c80-d2ec-11e8-8a2e-fd0b8199a055.png)

**Desktop (please complete the following information):**
 - OS: [] Linux Mint 18
 - Browser [] Chrome 69.0.3497.100 

**Smartphone (please complete the following information):**
None

**Additional context**
- Gutenberg 4.0.0

**Comment by designsimply** [comment]
Thank you for testing with Gutenberg at this stage!

I tested with WordPress 4.9.8, Gutenberg 4.0, Yoast SEO 8.4, and OceanWP 1.5.28 just now and I am able to create and publish new posts as well as edit and update existing posts without any problems. I used Firefox 62.0.3 and Chrome 69.0.3497.92 on macOS 10.13.6 in my testing.

I searched for "ReferenceError: YoastSEO is not defined" online and found a similar-sounding issue at https://github.com/Yoast/wordpress-seo/issues/10986 except they also noted several other console errors in addition to the one you've posted. Would it be possible for you to double check the console by clearing your browser cache then opening the console panel in your browser's developer tools and trying to create a new post again? If you get any additional errors besides "ReferenceError: YoastSEO is not defined" could you note them in a reply here?

If no additional errors show up, consider trying out the solution posted at https://github.com/Yoast/wordpress-seo/issues/10986#issuecomment-425080340 which says to try the Healthcheck plugin to see if it flags any missing pieces such as php-json modules.

**Comment by omarreiss** [comment]
We haven't been able to reproduce this issue on the Yoast side. Closing this for now. We can alway reopen when more information is provided.
