### ISSUE TITLE
Block Options insert doesn't honour allowedBlocks 

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#10752]
I set a custom block to ONLY allow a specific kind of block on insert.

`
allowedBlocks={ [
	[ 'library/listitem' ]
] }
`

This lets me add a block below and only adds the block I've permitted. Awesome. However if I then use the Block Options (the ... on the top of the block), it adds a paragraph every time. I can change this by using the slash command `/listitem` -- which properly is my only option, but it seems illogical that it doesn't honour my default.

![list-example](https://user-images.githubusercontent.com/807903/47173672-85cc1400-d2c3-11e8-89ef-9bf45db6171b.gif)

Using WP 4.9.8, Gutenberg 4.0

**Comment by chrisvanpatten** [comment]
There are a few issues about this (as you saw!) also including #10726 so I'm going to try to consolidate everything into #10301 to keep things cleaner :) Thanks for the gif, I'll link over to that in the other ticket.
