### ISSUE TITLE
back-compat of add_editor_style() and other similar functions

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#10766]
It seems there are several places where themes or plugins need to check which editor is being used. 
Could those checks be absorbed into existing core functions so it is more invisible? (like every plugin checking and every theme checking adds more code) etc.
Can we make the existing functions more smart to do it for them?

* add_editor_style
* TinyMCE buttons
* metabox functions?
_probably others_

**Comment by danielbachhuber** [comment]
Hi @joyously:

> Can we make the existing functions more smart to do it for them?

I'm not sure I follow. Can you describe what you mean in this case?

Generally, on the topic of backwards compatibility, we're trying to make the transition experience _as invisible as possible_. However, some existing Classic Editor features don't have exact parity in Gutenberg, so it's not possible to enable the feature automatically, so some intervention will be needed on behalf of the developer.

Previously #7913

**Comment by danielbachhuber** [comment]
Closing per https://github.com/WordPress/gutenberg/issues/7913#issuecomment-404475535
