### ISSUE TITLE
Docs: Section specifically for theme authors

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#10764]
There needs to be a list of CSS classes to style.
There needs to be better explanation of styling the content while in the editor.
There needs to be any new theme_support explanations.
There needs to be a list of filters or actions that no longer apply.

**Comment by chrisvanpatten** [comment]
Another related request over at #10800!

**Comment by joyously** [comment]
1. https://developer.wordpress.org/themes/

**Comment by skorasaurus** [comment]
Related to 1. [These are some of the classes](https://codex.wordpress.org/CSS#WordPress_Generated_Classes) that wordpress generates from (aligncenter, alignone, etc). At least [some of these are listed](https://developer.wordpress.org/themes/functionality/media/images/#alignments) within the Theme Handbook; I do not know whether all of the classes are llisted within the theme handbook.

**Comment by mtias** [comment]
The current place for theme related support is https://developer.wordpress.org/block-editor/how-to-guides/themes/. Further improvements should be submitted against it.
