### ISSUE TITLE
RichText: deprecate RichText.isEmpty

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#10763]
Since our new RichText value is just a string, we should probably get rid of this API altogether and do a simpler check. This also involves looking to see if we can return an empty string for empty multiline values, instead of e.g. `<p></p>`, see https://github.com/WordPress/gutenberg/pull/10678#discussion_r226456573.

**Comment by mtias** [comment]
Wouldn't controlling the interface give us more flexibility going forward?

**Comment by mtias** [comment]
> Do we plan on ever switching away from HTML again?
Who knows! :)

**Comment by ellatrix** [comment]
Let's close this for now.
