### ISSUE TITLE
Allow Media Upload To Alternate Sources on a Block-by-Block Basis

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#10768]
We are utilizing the https://github.com/Automattic/media-explorer functionality inside of the Classic Media Library, which allows us to select Media from a different source other than the default Media Library. 

In order for us to also allow uploading of content to these separate repositories -- along with just selecting media previously uploaded as is the default behaviour in Media Explorer (in this following example, the HWDSB.tv source is a whitelisted integration with Vimeo Pro for video hosting) -- we created a separate Media Library button (Upload External Media) to circumvent the default, where anything that you drag and drop into the editor gets uploaded to the default Media Library location. 

![2018-10-18_18-39-35](https://user-images.githubusercontent.com/480667/47188867-da917e00-d307-11e8-973b-50ec28f74690.gif)

In Gutenberg, given that a unified Media Library is being replaced by separate blocks, there's an opportunity to create separate upload paths on a block-by-block basis. So instead of what we see below, where despite the fact that I have selected a custom block (in this case HWDSB.tv), when I drag a video into the block, the default behaviour in the editor takes over and uploads the video to the default Media Library, rather than up to my selected video repo (in this case Vimeo).

Our work around has been to instruct our users to avoid drag and drop in the block, and to instead utilize the Upload tab in the Media Explorer modal accessed by the button in the block, which allows us to redirect uploads to our own custom path.

![2018-10-18_18-40-33](https://user-images.githubusercontent.com/480667/47188990-728f6780-d308-11e8-9ea0-d554457d3f96.gif)

In order to preserve intuitive functionality for users, I understand that if I drag a video, without first selecting a block, that the current behaviour makes the most sense for the majority of situations; but offering an option to unhook that behaviour once a block is selected, opens up the door to alternate media storage integrations that shouldn't impact current behaviour.

Alternatively, allowing sites to unhook the default drag-and-drop functionality all together, to then select different default blocks for different media types when content is dragged into the editor, would push this idea further (for example PDF, DOCX, PPTX = Default Media Block; Video = Jetpack Video Block; Image = CloudUp Block etc.).

**Comment by youknowriad** [comment]
Hi There! and sorry for the late response. In Gutenberg we have the `editor.MediaUpload` that allows to extend the regular MediaUpload button. In theory, you should be able to add buttons, replace the existing one...

Did you try that?

**Comment by youknowriad** [comment]
Closing as replied.
