### ISSUE TITLE
Explode Blocks, aka Show borders

### ISSUE THREAD

**Issue by simbalion** [WordPress/gutenberg#10767]
**Is your feature request related to a problem? Please describe.**
The most frustrating issue I've found while using the Gutenberg editor is trying to select specific blocks. Especially when blocks are inside other blocks. The borders are invisible, and on some system it can be very difficult to mouse over the precise 1 pixel area necessary to access the tools or borders.

Keyboard navigation is sort of a work-around, but not ideal, not visual.

**Describe the solution you'd like**
An 'explode blocks' toggle. When clicked, all of the blocks gain a 1 or 2 em margin, and all of their borders and controls become visible. 

Obviously this would interfere with WYSIWYG, but the issue I've described is so troublesome that it needs a solution. Being able to toggle this option, espcially with a shortcut, would speed up content editing and reduce frustrating mistakes such as accidentally deleting the wrong blocks.

**Comment by designsimply** [comment]
Similar to your request, #10760 suggests adding shading to the space between columns as a potential solution for the same problem. Some recent updates have been made to the Columns block in #10541 which will be coming in version 4.1, but I am not sure if those updates completely address the problem you've described. There's certainly a balance to be made here. I am going to add the `Needs Design Feedback` label to try to get some explanation about the design decisions that have been made so far with regard to block borders and visibility.

**Comment by simbalion** [comment]
Columns is not the only application, there is also placing image blocks inside paragraph blocks to in-line them.

**Comment by jasmussen** [comment]
If we reopen #9628, can we close this in favor of that? I agree it would be nice to explore a way to make it easier to select parent and nested blocks especially.

**Comment by karmatosed** [comment]
@jasmussen I agree let's do that and reopen #9628.
