### ISSUE TITLE
Initial welcome tooltip covers the Title field

### ISSUE THREAD

**Issue by scottbuscemi** [WordPress/gutenberg#10773]
**Describe the bug**
When a user first installs Gutenberg and creates a post/page for the first time, the initial welcome tooltip covers the Title field. This may create an initial negative reaction, causing confusion about whether the "Write Your Story" prompt should include a title at the top or if titles were removed completely alongside the introduction of Gutenberg.

**To Reproduce**
1. Install, activate Gutenberg on a fresh install
2. Create a new page/post

**Expected behavior**
Tooltips should not cover the core part of the editing page.

**Screenshots**
![screen shot 2018-10-18 at 8 50 34 pm](https://user-images.githubusercontent.com/4336848/47196877-c786aa00-d317-11e8-8038-7b6d37808e2b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
Latest nightly version of Gutenberg.

**Comment by jasmussen** [comment]
Thanks for the ticket!

There are a number of tickets in the [NUX](https://github.com/WordPress/gutenberg/labels/NUX) (New User eXperience) label that cover improvements to tip, notably #9242, which I've just added to the next milestone, will effectively render this a non-issue. As such I'm closing this in favor of #9242.
