### ISSUE TITLE
Remove text domains from dynamic core blocks

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#10788]
The PHP files from the dynamic blocks will still be maintained in this repo, but they'll be translated in Core, so no longer need the `'gutenberg'` translation domain.

**Comment by swissspidy** [comment]
Why are they still being maintained here? If it's for pre-5.0 compat then users on 4.9 won't have the 5.0 core translations.

**Comment by pento** [comment]
They're maintained here because they're part of the `block-library` package. It's a little bit weird, but we can make do until we figure out how to merge everything back into a monorepo.

**Comment by mtias** [comment]
@pento when should this happen?

**Comment by pento** [comment]
@mtias: It needs to happen before RC, for translations.
