### ISSUE TITLE
Create a documentation for the syntax of the HTML blocks

### ISSUE THREAD

**Issue by ecorica** [WordPress/gutenberg#10800]
**Is your feature request related to a problem? Please describe.**
No repository exists for the syntaxes of html blocks. For example for an image:

```
<!-- wp:image {"id":94973} -->
<figure class="wp-block-image"><img src="/content/uploads/2011/07/img-2.jpg" alt="" class="wp-image-94973"/></figure>
<!-- /wp:image -->

```
There is no repository which shows how the various possibilities of stylizing the HTML, by adding a legend for example.

**Describe the solution you'd like**
Create a documentation that can help.

**Comment by chrisvanpatten** [comment]
Thanks for the report @ecorica! We have a similar ticket just opened about documentation for theming, #10764, so I'll close this so we can merge into that ticket.

Thanks!
