### ISSUE TITLE
editing reusable block leads to nothing

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10809]
when on _wp-admin/edit.php?post_type=wp_block_

![image](https://user-images.githubusercontent.com/18373563/47233294-843d4180-d3d2-11e8-9e3d-44dd9d82d11b.png)

clicking on the name of a block it leads to nothing (all grey space)

example: wp-admin/post.php?post=30&action=edit

**Comment by chrisvanpatten** [comment]
Thanks @Presskopp — currently this is intentional but over at #9964 we're discussing making it possible to edit individual reusable blocks.

Since this is covered by that ticket I'll close this up but definitely encourage you to follow along and share your thoughts over there!
