### ISSUE TITLE
Latest Posts - Order not work on frontend

### ISSUE THREAD

**Issue by MichaelRise** [WordPress/gutenberg#10801]
When I add "Latest Post" block and set "Order by" then all works fine.
When I go to my page then the list has another posts.
Posts order not work on frontend.

Wordpress 4.9.8
Gutenberg 4.0

**Screenshots**
![gutenberg-backend](https://user-images.githubusercontent.com/9420574/47224603-36b5da00-d3bc-11e8-81f1-7b6e64bb40ee.png)
![gutenberg-frontend](https://user-images.githubusercontent.com/9420574/47224604-36b5da00-d3bc-11e8-9c04-e1f26cb75b48.png)

**Comment by designsimply** [comment]
Thank you for testing Gutenberg and for including screenshots!

I tested with WordPress 4.9.8 and Gutenberg 4.0 as well as [4.1.0-rc.2](https://make.wordpress.org/test/2018/10/19/call-for-testing-gutenberg-4-1-pre-release/) using Firefox 62.0.3 on macOS 10.13.6 and I found that posts listed in the Latest Posts block set to "Order by" = "Oldest to Newest" worked correctly for me in my testing (screenshots: [1](https://user-images.githubusercontent.com/1119271/47317381-a6b7a080-d606-11e8-98e7-d4e3af925532.png), [2](https://user-images.githubusercontent.com/1119271/47317382-a6b7a080-d606-11e8-9b9a-495e31fa536b.png)). I used the Twenty Seventeen theme for my test.

May I ask what theme you are using and whether you have any plugins installed which may be interfering with the Latest Posts display on the front end? 

If you're not sure if one of the plugins could be the source of a conflict or not, would you mind listing your active plugins for reference?

**Comment by designsimply** [comment]
From your second screenshot, are those all private posts or drafts or CPTs by chance? The naming makes them look like test posts which doesn't match with the kinds of titles I noticed in the first screenshot showing the editor.
