### ISSUE TITLE
Multi select should show a toolbar to do things common to the selected blocks

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#1080]
Ok, that issue title probably isn't the clearest ever written! Here's what I'm thinking...

When I'm in a text block, I can use the toolbar to set the alignment, text style, etc. When I select text inside the block, I can still do that. When I select two text blocks, I lose that ability. If I have, say, 5  paragraphs of text that I decide I want to center align, I have to do it 5 times.

Would it be possible to show a toolbar that contains controls that apply to all selected blocks? Or if all selected blocks are of the same type, just show the full toolbar?

**Comment by jasmussen** [comment]
There are a couple of challenges here, one being that you can select across multiple very different block types. It doesn't make sense to select across a gallery, a full width image, and a text block, and offer you a list making option. Another being that it can affect nested blocks, which will become a challenge later on. 

That's not to say it's not possible to create s "smart" toolbar that knows what blocks are selected, just that it's probably difficult.

**Comment by notnownikki** [comment]
I thought it might be tricky :) But I think it's something we should look at, if we go down the road of splitting text blocks when you start new paragraphs, it's going to be a poor UX to have to click in every single one to change your document's alignment.

**Comment by jasmussen** [comment]
It seems like an optimization that can potentially be explored down the road once all the basics are implemented, and in a solid place.

**Comment by mtias** [comment]
Going to close this for now. I only see it as being feasible when you only select across text blocks, in which case opening a specific enhancement for that case would be preferable.
