### ISSUE TITLE
Image embeds on Classic block: Bottom half image doesn't appear

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#10806]
## Description 

When trying to embed an image link from image hosting services supported by [WordPress embeds](https://codex.wordpress.org/Embeds), on a `Classic` block, the bottom half of the image is cut off. Tested with Instagram and Imgur and this is the case with the both.

## Steps to reproduce 

- On a Gutenberg post editor, add a `Classic` block
- Click on it and paste a Instagram/Imgur link
- Click on `Enter` to see the embed render

## What is expected 

The full image is shown

## What happens instead 

Only half of the image is shown

<img width="652" alt="screenshot 2018-10-19 at 22 03 35" src="https://user-images.githubusercontent.com/18581859/47232041-45b48080-d3ec-11e8-978a-c81625440da1.png">
<sup>Image indicating an Instagram embed on a classic block</sup> 
<img width="654" alt="screenshot 2018-10-19 at 22 07 47" src="https://user-images.githubusercontent.com/18581859/47232043-45b48080-d3ec-11e8-9851-bea6127fb6fe.png">
<sup>Image indicating an Instagram embed on a classic block with content above and below it</sup> 
<img width="515" alt="screenshot 2018-10-19 at 22 10 55" src="https://user-images.githubusercontent.com/18581859/47232045-45b48080-d3ec-11e8-8152-93531bd66275.png">
<sup>Image indicating that the bottom half of the content on Instagram and Imgur embeds are clipped out, on the classic block</sup> 

--- 

WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 70.0.3538.67 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 with Firefox 62.0.3 on macOS 10.13.6.

![screen shot 2018-10-22 at 2 51 18 pm](https://user-images.githubusercontent.com/1119271/47318771-2eeb7500-d60a-11e8-99ce-8e9665d0c3e4.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15261&action=edit running WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 using Firefox 62.0.3 on macOS 10.13.6.</sup>

**Comment by jorgefilipecosta** [comment]
I was able to verify that the problem is still happening.
