### ISSUE TITLE
Placement of title

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1081]
I am looking at: https://testgutenberg.wpkonsulterna.se/wp-admin/admin.php?page=gutenberg

![screen shot 2017-06-08 at 17 03 43](https://user-images.githubusercontent.com/5323259/26935529-7f350b12-4c6c-11e7-9787-8ef59bfedd62.png)

Look at the placement of the title. It looks like it is a part of the layout of the page.

What if we moved it up top something like this:

![gutenberg-title-area](https://user-images.githubusercontent.com/5323259/26935753-0fd54448-4c6d-11e7-946e-de201fcbdbb1.jpg)

We could for instance add some initial words that says add a block to begin creating your layout. The words go away after the first block has been added.

![gutenberg-add-first-block](https://user-images.githubusercontent.com/5323259/26935905-81904ab0-4c6d-11e7-8bf7-5e69b8514ffe.jpg)

**Comment by jasmussen** [comment]
Thanks for contributing and mocking up! Always good with perspectives. 

I responded indirectly to part of this in another ticket, https://github.com/WordPress/gutenberg/issues/1082#issuecomment-307313339. But I do think that the post title is part of the post, and should be in the layout area. 

More discussion in Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1496993101684003

Perhaps worth opening a ticket for making the post/page title an _actual_ block, so you can delete it if you want?
