### ISSUE TITLE
Category Widget: `aligncenter` class on front-end by default; can't be removed

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#10816]
**Describe the bug**
When you add a new Category Widget block, it applies the `aligncenter` class to the published version of the block, but not in the editor. There doesn't seem to be a way to toggle the `aligncenter` class off, since it's technically not "on".

The other 'list' widgets (Archive and Latest Posts) don't seem to have this issue.

**To Reproduce**
1. Add a new Category Widget block to a post or page
2. View in the editor and note the default alignment settings (nothing selected) and the alignment (should be aligned left).
3. Publish the post or page and view on the front-end.
4. Note that the widget has the `aligncenter` class and is applying the appropriate styles.
5. Go to the editor to toggle the class off. It can't be toggled off because it's not on. 

**Expected behavior**

That the block would have no default alignment, or if it did, that that alignment would be selected in the toolbar, so it could be turned off.

**Screenshots**

Block when you first add to editor (and when you return to it after publishing):

![image](https://user-images.githubusercontent.com/177561/47241270-f47e9f80-d39f-11e8-9065-22ed5c123301.png)

Block on front-end: 
![image](https://user-images.githubusercontent.com/177561/47241306-0fe9aa80-d3a0-11e8-911e-1b700657a39f.png)

**Comment by davidakennedy** [comment]
Wanted to say that I reproduced this as well while testing Twenty Fourteen with @laurelfulford.

**Comment by swissspidy** [comment]
This was fixed in #9829.

Please try this again in Gutenberg 4.1 RC (see https://make.wordpress.org/core/2018/10/19/whats-new-in-gutenberg-19th-october/) to see if this now works for you.

**Comment by mtias** [comment]
Closing this, but please reopen if it persists!

**Comment by laurelfulford** [comment]
Sorry I got back to this so late! I can confirm it works as expected in the 4.1 RC -- thanks!
