### ISSUE TITLE
Replace the fullscreen "exit" icon with a back arrow

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#10813]
A while ago (#9838), we replaced the `x` icon in full screen mode with an exit icon:

![45769856-cece7100-bc0e-11e8-9571-4fb25e87c45c](https://user-images.githubusercontent.com/1202812/47239154-7d9ed200-d3b2-11e8-89b3-d961adef3ea8.png)

The exit icon makes sense if you're familiar with it already, but I've heard from a few people that the icon is a little unclear — mostly due to the fact that it's relatively obscure, compared to other alternatives (close icon, back icon, etc.). 

For that reason, it might make sense to just switch this to a back arrow instead. A back arrow makes general sense in this context, and the icon will be more widely understood. That seems like a win here. 

![image](https://user-images.githubusercontent.com/1202812/47239129-71b31000-d3b2-11e8-9ebf-61613a62d1ab.png)

(via [Material Icons](https://material.io/tools/icons/?icon=keyboard_arrow_left&style=baseline))

(cc @alexislloyd)

**Comment by karmatosed** [comment]
I personally like this but let's consider how we slip under UI freeze, even if we can. cc @mtias and @jasmussen.

**Comment by jasmussen** [comment]
I dig it. Though I have a personal preference for the arrow with a stem, but that opinion isn't _strong_. 

To get this in after the UI freeze, I would suggest that the change needs to be _really OMG important_, or _fix a bug_. I'm not sure this classifies as either, given it's an icon change to a non-default interface mode. I also think it would be a nice quick win once phase 2 gets underway. But that's just my opinion.

**Comment by nerrad** [comment]
Personally, I've found the behaviour of this link very disjointing from muscle memory patterns.  Even though I know _what_ this link does, I find the fact that it leads to the post list table to be jarring.  I repeatedly expect it to exit full screen mode.  

I _do understand_ however that if someone has full screen mode as the default for their editor instance, that they will land on here from the post lists table so in that context it makes sense.  However I find that its more jarring when enabling full screen for the first time.

I propose making this more context aware, which means:

* Show an "x" (or some other appropriate "close" icon) when enabling full screen for the first time. You can keep the back icon in place for jumping to the post list from this context (which helps train that as being the action to get from the full screen editor to the admin interface).
* Show the "back" icon when arriving in the editor from the post lists table context.

**Comment by afercia** [comment]
If the link to the posts list is going to stay, from an accessibility perspective the "back" icon would be better and the aria-label / tooltip should just be "Back". See https://www.w3.org/TR/WCAG21/#label-in-name

However, I'd consider to review the overall functionality shortly after 5.0. There are many places in core where a link points to the edit post page. Just search for all the occurrences of `get_edit_post_link()` and where it’s used. For example: the Recent Drafts widget in the Dashboard. Or the edit comment page. Or the edit post link in the toolbar in the frontend. Not to mention plugins that link to the edit post page for their own purposes.

When full screen mode is on and users come from one of these places, why they should be brought back to the posts list?

**Comment by nerrad** [comment]
Some other considerations (brought up in [slack chat](https://wordpress.slack.com/archives/C02QB2JS7/p1542988592225300):

- Have the default mode for the editor as full screen and switch this to a "close" indicator that doesn't change the default mode but temporarily switches the editor to non full screen for that session (@youknowriad's suggestion)
- Remember that the editor is potentially the destination from a variety of external links.  Coming into the editor from those contexts when its in full screen mode can result in a jarring experience when clicking something looking like a back arrow (see @afercia's comments above).
- IMO I think any "back", "next" navigation should be left explicitly to the browser, having an alternative action serving the same purpose is a potentially confusing (especially when behaviour differs).

I realize this link was put in place partially because general navigation is hidden in full screen mode but I don't think the current implementation is a good long term solution.

**Comment by kjellr** [comment]
👋 I opened a quick PR to keep this moving along: #13403 

I'm also up for exploring @youknowriad's suggestion above:

> Have the default mode for the editor as full screen and switch this to a "close" indicator that doesn't change the default mode but temporarily switches the editor to non full screen for that session

That seems reasonable to me, and might be a good solution too.

**Comment by jasmussen** [comment]
> Have the default mode for the editor as full screen and switch this to a "close" indicator that doesn't change the default mode but temporarily switches the editor to non full screen for that session

This seems overly complex to me, with complex rules for when and when not to. I'm not sure as a user I'd know what was going on here. I'm sorry I missed the chat where this was suggested, and it's not the end of the world if it has to be this way, but it doesn't feel like a win. 

If the problem we're trying to solve is the following:

> When full screen mode is on and users come from one of these places, why they should be brought back to the posts list?

... then as a strawman argument, can't we do a `history.back()` instead?

**Comment by kjellr** [comment]
> then as a strawman argument, can't we do a history.back() instead?

That seems reasonable to me too. 😄 It would probably end up being a bit more expected than the current behavior.

**Comment by gziolo** [comment]
Icon (dashicon) and label were updated in #13403. Should we close this issue or do you want iterate on it?

**Comment by kjellr** [comment]
Let's close for now. 👍 This ticket was opened purely to adjust the icon. Discussion around the function of that button can be handled in a separate ticket if needed.
