### ISSUE TITLE
Editor package: error while trying to install new package version (4.0.3)

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#10814]
**Describe the bug**

I'm unable to install new package versions released on 18th of October due to an npm error:

```
$ npm install @wordpress/editor@latest
...
npm ERR! Could not install from "node_modules/@wordpress/editor/node_modules/@wordpress/autop" as it does not contain a package.json file.
```

Similar errors are can be observed while trying to update other packages released on that day.

/cc @gziolo @pento

**Comment by pento** [comment]
After the release failed, the two packages I'm aware of that have errors like this (`editor` and `block-library`) were the ones I had to run `npm publish` on.

**Comment by gziolo** [comment]
New version of packages was published and both packages mentioned look good now:
* https://unpkg.com/@wordpress/block-library@2.1.3/package.json
* https://unpkg.com/@wordpress/editor@5.0.0/package.json

I will double check the rest tomorrow and close this issue.

**Comment by swissspidy** [comment]
With the a package.json file like this: https://github.com/swissspidy/simple-google-ads/blob/64bc0190e20bb8994e9385d2596284fe0af6cf3b/package.json

I am still unable to run `npm install`. The error I'm still getting is this:

```
$ npm install --cache /tmp/empty-cache
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/@wordpress/a11y" as it does not contain a package.json file.
```

https://unpkg.com/@wordpress/a11y@2.0.2/package.json looks ok though, so no idea what's wrong.

`yarn install` on the other hand worked just fine...

**Comment by gziolo** [comment]
@swissspidy I think you need to use all the latest versions of packages, in particular editor had major version increment because we removed some unused selector.

**Comment by swissspidy** [comment]
Removed the editor dependency now (was actually unused) and made sure all dependencies are on the latest version. Works now!

**Comment by vindl** [comment]
Just wanted to confirm that the update resolved the issue for me too. Thank you for fixing it! ⭐️
