### ISSUE TITLE
New Date Picker seems messed in 4.1

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#10825]
**Describe the bug**
Testing 4.1, the new date picker component seems not working perfectly. It looks messed.

**Screenshots**
![screen recording 2018-10-20 at 01 34 pm](https://user-images.githubusercontent.com/5817882/47253507-44776800-d46d-11e8-8144-98afad2712ea.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.2
 - Browser Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)
* Same issue one safari as well.

**Comment by SchneiderSam** [comment]
Me too. Same Bug.
