### ISSUE TITLE
Empty post placeholder

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#1082]
Now that we have a direct "New post" link, should we add a global placeholder "Start writing"(or similar)?

I wonder if we should automatically add an empty text block (with this placeholder) to all new posts.

**Comment by paaljoachim** [comment]
I am thinking something like this:

We can move the title to the top and for instance add some initial words that says add a block to begin creating your layout. The words go away after the first block has been added. 

![gutenberg-add-first-block](https://user-images.githubusercontent.com/5323259/26935905-81904ab0-4c6d-11e7-8bf7-5e69b8514ffe.jpg)

**Comment by mtias** [comment]
@youknowriad yes, let's get an empty text block there. The placeholder should be the default for the block (i.e. if the default was an image, it'd be the image placeholder, etc.) We'll see if #798 pans out.

**Comment by jasmussen** [comment]
Here's what I've been imagining it:

![empty post](https://user-images.githubusercontent.com/1204802/26964674-f3ab8558-4cf2-11e7-983c-078067d5602f.png)

Not sure about the "(optional)" part —  perhaps that's premature. The idea is that we are also looking to retire post formats, and you might have a post format that doesn't include a title. But this is probably better solved by making the post title an _actual_ block that you can remove, _down the road_.

Below that, like Matías says, is a text block. Or the default block you decided in #798.

By the way I appreciate your mockups, @paaljoachim, it's good to have a diversity of ideas here!

**Comment by aduth** [comment]
@paulwilde For constructiveness' sake, can you elaborate on your reaction to @paaljoachim's comment?

**Comment by paulwilde** [comment]
@aduth I'm just not a huge fan of the placement of the title in the toolbar. It has the disadvantage of not being able to support multi-line so you need to scroll throug should the title be longer than the input field width. Also they would need to be a lot of considerations on its placement on mobile also, which currently isn't a concern (I believe?).

**Comment by paaljoachim** [comment]
@paulwilde That is a very valid point! One that I did not think about.
For responsiveness and a possible long title it would likely be better to keep it where it is today.

**Comment by youknowriad** [comment]
I'm starting to think about the technical details of the first version of this. We have several options:

**Append an empty block in the block list when initializing the editor**

Pros: 
 - Simplicity
Cons: 
 - If we save a post without any change, we would have an empty text block in it.
 - If we delete the text block placeholder, we won't have any block in the page

**During the render, fallback to a empty text block if the block list is empty**

Pros:
 - If we delete all blocks, the placeholder block will show up
 - The post would contain no block unless we effectively type something into this placeholder block

Cons:
 - A bit complex since the `VisualEditorBlock` component is really tied to the fact that the block being rendered is in the state. Even if we try to drop this constraint, the behaviour between the placeholder block and a regular block is slightly different (updating means inserting, removing do nothing, merging with blocks don't exist, splitting means creating two blocks...)

Thoughts on this @aduth

**Comment by mtias** [comment]
> If we save a post without any change, we would have an empty text block in it.

This is ok and speaks to the ability of saving "ready made templates" as page content (think the About page that already comes with WordPress, or the hello-world post).

This should also be a configurable setting in PHP for plugins, etc.

**Comment by jasmussen** [comment]
I've been having some thoughts here also, which tie into the default block also. 

The idea is, essentially, to show a "fake" block at the bottom, with a writing prompt inside (like "Write your story"). It's just a big button, but if you click it, it becomes your default text block. Then on the right side there's a small dropdown that lets you select what this default text block is. Defaults to single p text, but you could potentially pick freeform, or even let a markdown block register itself here.

The inserter plus would sit below this.

I'm still thinking about this and want to provide a mock-up, but this is the general idea.
