### ISSUE TITLE
gutenberg fails to update or publish

### ISSUE THREAD

**Issue by ericscottdouglas** [WordPress/gutenberg#10839]
**Describe the bug**
A pink banner that says "updating failed" shows up when I start a new post in gutenberg mode.  This does not happen when I start a new post in regular editor mode.  It did not happen when I was using the gutenberg plugin with version 3.9.8 of wordpress.  I do not use CloudFlare.

**To Reproduce**
1. Go to 'new post'
2. Click on 'title'
3. Type something

**Expected behavior**
no error message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: vista
 - Browser firefox
 - Version old

**Comment by slimmilkduds** [comment]
You wouldn’t happen to use the plugin Press Permit?

**Comment by ericscottdouglas** [comment]
Hi,No, but I do use JSON Content Importer.  I'm also about to install Jetpack, which I hope will not make things worse.Eric

**Comment by ericscottdouglas** [comment]
Hi,
I think I may have fixed it by changing my permalink setting.
Eric

**Comment by designsimply** [comment]
Great to hear you think you've fixed the problem! I'll close this issue for now. If you see the problem happen again and you are able to double check the console and network panels in your web browser's web development tools, it would be helpful if you could find a relevant error message from there at the time you type something in the title and see the "updating failed" error. It would also be helpful to know the exact version of the Firefox browser you are using for reference (in case it's relevant).
