### ISSUE TITLE
Resolve block Convert to HTML doesn't create the After Conversion HTML

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#10848]
**Describe the bug**
Resolve block Convert to HTML doesn't create the HTML it says it will. 

**To Reproduce**
1. Using the Classic editor create the post used in #5467
2. Edit using Gutenberg
3. Select the second block which says "This block contains unexpected or invalid content."
4. Choose Resolve
5. Choose Convert to HTML
6. Save
7. Go to 3.

**Expected behavior**
Step 5. Convert to HTML should do what it says it will do.

**Screenshots**
Step 3. Aside. Why are there two More options vertical ellipses? 
![image](https://user-images.githubusercontent.com/2474435/47264947-20249580-d518-11e8-8253-6a63e1fa2fcd.png)

Step 4. The After Conversion HTML looks good
![image](https://user-images.githubusercontent.com/2474435/47265444-db046180-d51f-11e8-8c17-ef92583b0f17.png)

Step 5. The HTML hasn't changed.
![image](https://user-images.githubusercontent.com/2474435/47264960-67128b00-d518-11e8-8c9d-f5bb17588e24.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
This is a follow on to #5467. Note the Goto in the Steps.

**Comment by johngodley** [comment]
You need to press the button under the conversion you want to use.

The HTML on the right (where the difference is shown) will be used if you press the button on the right - 'convert to blocks'.

In step 5 you say you are pressing 'convert to HTML', the button on the left. This is doing the job, but as the block is already HTML then no difference is shown.

I think this can probably be marked as finished, as the 'convert to HTML' button is working. However, I don't think it makes sense to have it as an option for an HTML block and I've tracked that separately in #10889

**Comment by johngodley** [comment]
You need to press the button under the conversion you want to use.

The HTML on the right (where the difference is shown) will be used if you press the button on the right - 'convert to blocks'.

In step 5 you say you are pressing 'convert to HTML', the button on the left. This is doing the job, but as the block is already HTML then no difference is shown.

I think this can probably be marked as finished, as the 'convert to HTML' button is working. However, I don't think it makes sense to have it as an option for an HTML block and I've tracked that separately in #10889

**Comment by johngodley** [comment]
You need to press the button under the conversion you want to use.

The HTML on the right (where the difference is shown) will be used if you press the button on the right - 'convert to blocks'.

In step 5 you say you are pressing 'convert to HTML', the button on the left. This is doing the job, but as the block is already HTML then no difference is shown.

I think this can probably be marked as finished, as the 'convert to HTML' button is working. However, I don't think it makes sense to have it as an option for an HTML block and I've tracked that separately in #10889

**Comment by johngodley** [comment]
You need to press the button under the conversion you want to use.

The HTML on the right (where the difference is shown) will be used if you press the button on the right - 'convert to blocks'.

In step 5 you say you are pressing 'convert to HTML', the button on the left. This is doing the job, but as the block is already HTML then no difference is shown.

I think this can probably be marked as finished, as the 'convert to HTML' button is working. However, I don't think it makes sense to have it as an option for an HTML block and I've tracked that separately in #10889

**Comment by cbrady77586** [comment]
Started seeing the error "This block contains unexpected or invalid content. Resolve." tonight. Most recent instance was a newly created page that contained a Gravity Form block. After saving document and looking at it, went back to edit. Error was there. When looking to resolve the issue, I see that paragraph tags now surround the shortcode.

![image](https://user-images.githubusercontent.com/5313121/47334813-e5247e00-d64d-11e8-95f5-6981297ffb8a.png)


Earlier instances this evening were related to a different Gutenberg block being used at the top of my home page.

![image](https://user-images.githubusercontent.com/5313121/47334897-3f254380-d64e-11e8-8556-07e5c01b5664.png)

**Comment by johngodley** [comment]
@cbrady77586 I dont think your comment is related to the original report? If it's a seperate thing can you create a new issue with a full description of what you expected to happen?

Closing this issue as mentioned above.

**Comment by bobbingwide** [comment]
> You need to press the button under the conversion you want to use.
>
I did. I wanted an HTML block with the fixes applied.

> The HTML on the right (where the difference is shown) will be used if you press the button on the right - 'convert to blocks'.
> 
That’s not at all obvious.
> In step 5 you say you are pressing 'convert to HTML', the button on the left. This is doing the job, but as the block is already HTML then no difference is shown.
>
Perhaps convert to HTML should convert to blocks then merge them back into a single HTML block. If this is not possible then maybe convert to Classic would be the way to go.

**Comment by bobbingwide** [comment]
I now have a better understanding of what the dialog was trying to tell me. The problem with converting to blocks is that it does not retain any custom attributes on the tags. e.g. for `p class="fred"` I'd lose the class if I converted to blocks.

**Comment by johngodley** [comment]
Yep, you could lose information when converting to blocks, which is what the diff attempts to show. The idea being if you invalidate a normal block you can convert to HTML or attempt to convert to new blocks.

Converting HTML to HTML won't change anything as it's already HTML, and #10889 will look at that case. 

Additionally #10551 could remove the problem entirely by allowing the custom HTML block to contain invalid HTML, preventing the 'invalid content' message, and meaning you don't have the option to convert HTML to HTML (also fixing #10889). It would also remove the wonky preview shown in your original screenshot (where the bullet points overlap the borders).
