### ISSUE TITLE
Gutenberg fatal error when activating

### ISSUE THREAD

**Issue by dgroddick** [WordPress/gutenberg#10842]
Gutenberg 4.0.0 fails to activate with Fatal Error on WordPress 5.0-alpha-43773 

```
Plugin could not be activated because it triggered a fatal error.
Fatal error: Cannot declare class WP_REST_Autosaves_Controller, because the name is already in use in /wp-content/plugins/gutenberg/lib/class-wp-rest-autosaves-controller.php on line 0
```

All other installed plugins work fine. Using a child theme of TwentyNineteen. Same set of plugins and theme on Wordpress 4.9.8 doesn't have the same issue.

Installed on Ubuntu 18.04 with PHP 7.2

**Comment by youknowriad** [comment]
This is already fixed in Gutenberg master. It will come in the next release probably.

**Comment by youknowriad** [comment]
Related #10822
