### ISSUE TITLE
Can't select parent block if it's an inner block

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#10851]
This is a usability issue.

When a parent block (which uses the innerBlocks component) is added in another parent block (for example columns) it's difficult to select the nested parent block.

![untitled-1](https://user-images.githubusercontent.com/3076742/47265545-2889ca00-d532-11e8-9e6a-be5cb71cc7ce.jpg)

In the screenshot above, I've added a parent block named "Animation block" into a column. The "Animation block" supports inner blocks and has inspector settings but I can't select it while it's in the column. I can only select the nested paragraph block or the parent column block. To select the Animation block, I have to find a very narrow (1px) space between the paragraph block and column parent block. 

I think there should be an easy way to select parent blocks in these situations. Maybe it would help to have an option in the "more options" dropdown to select "Parent block" if the block is nested.

I'm using **Gutenberg 4.0.0**.

**Comment by mtias** [comment]
> I think there should be an easy way to select parent blocks in these situations. Maybe it would help to have an option in the "more options" dropdown to select "Parent block" if the block is nested.

In 4.1 there will be a "block path" selection mechanism that will let you select across all levels of nesting:

![screenshot-2018-10-19-at-15 26 04 1](https://user-images.githubusercontent.com/548849/47357677-bd71fc00-d6c7-11e8-9717-c90af50ae889.png)
