### ISSUE TITLE
Table Block, block toolbar wording of first item tooltip misleading

### ISSUE THREAD

**Issue by berlindave** [WordPress/gutenberg#10852]
**Describe the bug**
Toolbar of table block, first item shows "Change block type" intstead of e. g. "Change block style".

**To Reproduce**
1. Create a table block (e. g. 5 rows, 4 cols)
2. Fill table cells with content
3. On block toolbar klick first item: tooltip says "Change block type"

**Expected behavior**
You'd expect that you can change the block type. Instead you can change Block Style. 

**Screenshots**
Tooltip:
![screenshot-1](https://user-images.githubusercontent.com/16339038/47265695-4f450200-d52c-11e8-8cb0-e7c577d4b702.png)

After klick:
![screenshot-2](https://user-images.githubusercontent.com/16339038/47265697-53711f80-d52c-11e8-9cd0-2a80af0d2e6e.png)

**Additional context**
WP 4.9.8, Gutenberg 4.1.0-rc.1, Theme Twenty Seventeen

**Comment by desrosj** [comment]
This was discussed in today's bug scrub: https://wordpress.slack.com/archives/C02RQBWTW/p1540493661000100

This UI usually changes both type and style, but more often only changes type. It seems the only blocks currently, by default, that can only change style are tables and buttons.

Possible actions:
- Change to 'Change block' as tooltip
- Change to 'Change block type or style'
- Leave until phase 2.

I have milestoned this for phase 2, but if someone feels strongly and a PR is created in time, it can be added prior to WordPress 5.0.

**Comment by kristastevens** [comment]
From a copy perspective, I think 'Change block type or style' is clear.

**Comment by mapk** [comment]
The text suggested by @kristastevens looks good. I've created a PR for this, #14470.
