### ISSUE TITLE
Pasting a list from word adds <br> to the item lines

### ISSUE THREAD

**Issue by mjaragon** [WordPress/gutenberg#10865]
**Describe the bug**
When pasting an unordered list from MS-Word (in windows 10), a `<br>` is inserted after the first word.
If I write the text in word directly as a list, I can paste it without any issue
But if I first write the text in different lines and then change the lines into a bullet list, it doesn't paste correctly

**To Reproduce**
1. Write three lines in MS-Word (under Windows)
2. Change the lines into a bullet list
3. Copy and past the list into a post (it looks fine in the visual editor)
4. Check the HTML, the first space in each line has a line break inserted

**Expected behavior**
The unordered list should be pasted with each line as it is entered in Word (no extra lines)

**Screenshots**
![1-plain-text-in-ms-word](https://user-images.githubusercontent.com/30312698/47267639-0d758500-d547-11e8-938f-f69842f61155.PNG)
![2-convert-to-bullet-list](https://user-images.githubusercontent.com/30312698/47267640-11a1a280-d547-11e8-8dd8-8c4ecb6a4a3f.PNG)
![3a-copy-bullet-list](https://user-images.githubusercontent.com/30312698/47267641-15352980-d547-11e8-87b5-47377fb843b0.PNG)
![3b-paste-in-gutenberg-post](https://user-images.githubusercontent.com/30312698/47267643-18301a00-d547-11e8-87d6-2db3b4294667.PNG)
![4a-check-html](https://user-images.githubusercontent.com/30312698/47267677-6ba26800-d547-11e8-8f91-21f308d87072.PNG)
![4b-line-break-in-preview](https://user-images.githubusercontent.com/30312698/47267678-6d6c2b80-d547-11e8-87e0-5461c2bea5bd.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome (Version 69.0.3497.100) & Firefox (Version: 62.0.3)
 - (could not reproduce in mac OS)

**Additional context**
- Gutenberg Version 4.1.0-rc.1

**Comment by ellatrix** [comment]
Hi! Thanks for the report. Could you please share the information that was logged in the browser console when you paste the text in WordPress?
