### ISSUE TITLE
Poorly timed Finished writing NUX Tip 

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#10878]
**Describe the bug**
When I add a new post I don't expect the Finished writing tip to appear immediately.

**To Reproduce**
1. Edit an existing post
2. Choose More > Show Tips
3. Click on the "See next tip" link three times
4. Wonder what happened to the 4th tip ( the one after Click "Preview" ... )
5. Click on New > Post in the top admin bar
6. See the "Finished writing" tip appear before you've done anything.

**Expected behavior**
Step 4. Don't display "See next tip" when there isn't one
Step 6. Don't display the "Finished writing?" tip as the first tip for "Add New".

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/47269539-3140c700-d557-11e8-8bc9-f061f2d5037d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version: 70.0.3538.67 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
