### ISSUE TITLE
"Please wait... Generating preview." not translatable

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10874]
![image](https://user-images.githubusercontent.com/18373563/47268974-c2b03900-d557-11e8-8c09-3d7aadd6ddd9.png)

`this.previewWindow.document.write('\n\t\t\t<div class="editor-post-preview-button__interstitial-message">\n\t\t\t\t<p>Please wait…</p>\n\t\t\t\t<p>Generating preview.</p>`

**Comment by swissspidy** [comment]
Related: #7922.

**Comment by ocean90** [comment]
Duplicate of #7725.
