### ISSUE TITLE
JS Warnings when changing the publish date

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#10876]
**Describe the bug**
Not sure this is already tracked. If it's a known issue, of course do feel free to close.

On current master:
- create a post
- click the Publish date button and observe your browser's dev tools console
- as soon as the date picker opens, I'm getting this JS Warning:

`Warning: Failed prop type: DayPickerSingleDateController: unknown props found: block`

**Comment by desrosj** [comment]
@afercia I am unable to reproduce this. Can you give me more details about which WP version, Gutenberg version, and date format the site has selected?

**Comment by afercia** [comment]
@desrosj this was tested on WP trunk and Gutenberg master 5 days ago, default date format `F j, Y g:i a`. Cannot reproduce now, however I'm not sure `DayPickerSingleDateController` has a `block` prop, see https://github.com/airbnb/react-dates/blob/60025377603ac1bb042b525d499ea0d5dc814e89/src/components/DayPickerSingleDateController.jsx

I see this props is passed to the component though: https://github.com/WordPress/gutenberg/blob/a696e508ad5d3566b447fc48f355e91953a17c4a/packages/components/src/date-time/date.js#L44-L45

**Comment by Ferdev** [comment]
we're also seeing this issue in https://github.com/woocommerce/woocommerce-bookings
We're just [using](https://github.com/woocommerce/woocommerce-bookings/blob/develop/assets/js/components/datepicker-popover-month/index.js#L49) the `DatePicker` class from `@wordpress/components`, and we get the warning whenever we run the plugin under WordPress 5.0.3 (it does work in 5.0.2 and previous versions).

As @afercia pointed out, I don't think `DayPickerSingleDateController` has a `block` property, but it does have a `blocked` property I think... Maybe it was just typo.

We'd appreciate any info you could give us, thanks!

Steps to reproduce the issue:

1. WordPress 5.0.3 fresh install
2. Install & activate the [WooCommerce plugin](https://github.com/woocommerce/woocommerce).
3. Install & activate the [WooCommerce Bookings plugin](https://github.com/woocommerce/woocommerce-bookings).
4. Execute `npm run start` on the WooCommerce Bookings plugin folder
5. In the Admin, go to Bookings->Calendar an click on the month name on the calendar's title.
6. The error should pop up in the browser's dev console.

**Comment by afercia** [comment]
Yep, I still see it on current master 16b94bb47abb2fd12c0a788b25bbe4e9740eebb7 when opening the Publish date picker.

**Comment by bor0** [comment]
I can't reproduce this on WordPress 5.2.2.

**Comment by gziolo** [comment]
I'm seeing this React deprecations listed:
![Screen Shot 2019-10-21 at 11 15 10](https://user-images.githubusercontent.com/699132/67192566-187e2200-f3f4-11e9-98fe-85f6981e150e.png)

**Comment by glendaviesnz** [comment]
I am not seeing any console errors with the date picker in WordPress 5.3 with Gutenberg 7.0.0

![date-picker](https://user-images.githubusercontent.com/3629020/69842401-ff587300-12c7-11ea-8ba5-91dc1811a80e.gif)

**Comment by afercia** [comment]
Looks like the `block` property was removed in #12933 thus fixing this issue.
