### ISSUE TITLE
Don't show 'convert to HTML' on a HTML block

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#10889]
If you trigger the invalid block warning on an HTML block you are shown these options:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47282408-06965300-d5d7-11e8-88ff-9b9e32b4ad15.jpg)

The 'convert to HTML' option doesn't make sense as the block is already HTML. Selecting this option has no outward effect.

It would be better if the option wasn't shown for HTML blocks.

## Test Case

1. Create custom HTML block
2. Enter this as the HTML:

```html
<p>Here's a list inside a paragraph
    <ul>
        <li>One</li>
        <li>Two</li>
    </ul> which is probably bad HTML
</p>
```
3. Save the post and reload

**Comment by johngodley** [comment]
Note this may not be applicable if #10551 or something achieving that is added

**Comment by bobbingwide** [comment]
Please revisit the original issue #10848 where I have added a comment.

**Comment by skorasaurus** [comment]
This is still reproducible in Gutenberg 9.8.0 
![Selection_035](https://user-images.githubusercontent.com/955351/105390567-2e762600-5be7-11eb-90b5-4023ebc886d5.jpg)

**Comment by TheSimArchitect** [comment]
It would be nice to be able to turn that validation off for the block, permanently.

**Comment by jordesign** [comment]
I'm no longer able to recreate this in WordPress 6.2.2 - so I'll close this as resolved
