### ISSUE TITLE
Table Block: Alignment Does Not Display In Published Post But Shows In The Editor

### ISSUE THREAD

**Issue by katinthehatsite** [WordPress/gutenberg#10899]
When I add a table block and use alignment option, and then attempt to add another block after e.g. a text block, instead of going on a new line, the new block goes on the side by the table block in the editor (which makes sense when you use alignment option). However, when I view it in the published or preview modes, the new block is shown on a new line instead of being aligned. 

**To Reproduce**
1. Add the table block:
<img width="709" alt="screen shot 2018-10-22 at 9 54 02 am" src="https://user-images.githubusercontent.com/25575134/47296508-6e9d6700-d5e0-11e8-9016-a9c5f9410f73.png">

2. Set the table block to align left:

<img width="504" alt="screen shot 2018-10-22 at 9 59 53 am" src="https://user-images.githubusercontent.com/25575134/47296768-482bfb80-d5e1-11e8-9a25-f91c4f31930d.png">

3. Add a block after the table block. I used a text block in my testing.

What I see in the editor is that the next block is nested on the same level as the table block which makes sense when you use alignment:

<img width="866" alt="screen shot 2018-10-22 at 10 01 57 am" src="https://user-images.githubusercontent.com/25575134/47296923-ba044500-d5e1-11e8-9927-f6af197597b7.png">

But when I use the "preview" mode, the blocks do not show alignment and are displayed on separate lines:

<img width="848" alt="screen shot 2018-10-22 at 10 04 31 am" src="https://user-images.githubusercontent.com/25575134/47296990-e5872f80-d5e1-11e8-9ed1-79fac2ec1dc4.png">

I would expect consistency between the editor display and the preview mode/published post, however, there is a discrepancy between the editor and the published/preview modes.

**Comment by designsimply** [comment]
Thank you for the report! I think this would be a good one to test in a few different themes to see if it is theme-dependent. May I ask what theme you are using for reference?

**Comment by carladoria** [comment]
I was able to reproduce this with Veni theme:
![gutenberg1](https://user-images.githubusercontent.com/23703267/47586264-b815eb00-d92d-11e8-9d9f-3ac55d2b02c6.jpeg)
![gutenberg 2](https://user-images.githubusercontent.com/23703267/47586267-bb10db80-d92d-11e8-80e2-3896c9ad2ca2.jpeg)

**Comment by katinthehatsite** [comment]
The original report comes from P2 theme.

**Comment by youknowriad** [comment]
I tested on some Twenty* themes and I don't reproduce. I think this is a theme related issue where some themes force a "non-floated" table element. Supporting alignment classNames has always been a theme responsibility. I'd suggest opening issues in the theme trackers.
