### ISSUE TITLE
Options modal doesn't fit in mobile viewport

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#10894]
When on a mobile viewport this is how the options modal (`editor bar > general settings > options`) looks like - note how the close button at the top right is out of the viewport:

![options-panel-mobile](https://user-images.githubusercontent.com/583546/47290040-df9f4780-d5fd-11e8-8a4e-296ba46af2df.png)

**Comment by nosolosw** [comment]
cc @jasmussen @karmatosed

**Comment by karmatosed** [comment]
Is it possible to make it full screen with the close button showing like this:

![options](https://user-images.githubusercontent.com/253067/47313395-c2d33600-d636-11e8-8b16-a99e26a0a615.png)

This is based on the sidebar pattern we have for now.
