### ISSUE TITLE
Media & Text: Can't resize image with unified Toolbar

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#10895]
**Describe the bug**
If I activate the unified toolbar, I am not able to resize the image in the new `Media & Text` block.

**Comment by designsimply** [comment]
Tested and confirmed with WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 that I cannot see a drag handle to resize an image in the Media & Text block when the Unified Toolbar is active.

![screen shot 2018-10-22 at 7 10 39 am](https://user-images.githubusercontent.com/1119271/47294365-1a878800-d5ca-11e8-8c04-509678d84ee3.png)

![screen shot 2018-10-22 at 7 10 19 am](https://user-images.githubusercontent.com/1119271/47294366-1a878800-d5ca-11e8-97ee-d6deb3d6aaad.png)

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @Soean!
