### ISSUE TITLE
Content of block switcher popover can overflow

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#10905]
**Describe the bug**
Depending on the height of the screen, the content of the popover for switching blocks can overflow.

**To Reproduce**
1. Open editor
2. Reduce width and height of window
3. Create a quote block
4. Open the block switcher and scroll
5. See error

**Screenshots**
![kapture](https://user-images.githubusercontent.com/617637/47306420-afbb6880-d62c-11e8-8e8d-15c39ad8e813.gif)

**Desktop**
 - OS: macOS 10.14
 - Browser Chrome
 - Version 70

**Comment by timelsass** [comment]
ran into this today.  It's also not the height of the screen only, but content:
![image](https://user-images.githubusercontent.com/11907254/59080530-3587dd80-88b7-11e9-9b68-f394a8246d5e.png)

**Comment by ellatrix** [comment]
Is this still an issue in `master`?
