### ISSUE TITLE
Use `cmd+shift+k` to remove a link

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#10915]
### Problem

The current keyboard shortcut for removing a link is `control+alt+s`, which is cumbersome, difficult to remember, and unintuitive.

### Proposed Solution

The shortcut to add a link is `command+k`, so it seems like it'd be more intuitive if removing a link was `command+shift+k`.

**Comment by mtias** [comment]
cc @iseulde @talldan for thoughts.

**Comment by iseulde** [comment]
Sounds good to me. Can be added with the format api.

**Comment by talldan** [comment]
Yep, Ctrl+Alt+S always struck me as unusual too. Cmd+Shift+K should be alright - I couldn't see any browser shortcuts it clashes with. 

We'd want to use Ctrl+Shift+K on windows. When testing in IE11, Ctrl+Shift+K seems to open a new tab (which is odd and undocumented). In Firefox on Windows it opens the console, so we'd be overriding both of those behaviours.

I've been keeping track of those things in a spreadsheet:
https://docs.google.com/spreadsheets/d/1nK1frKawxV7aboWOJbbslbIqBGoLY7gqKvfwqENj2yE/edit?usp=sharing

**Comment by iseulde** [comment]
Added in #10209.

**Comment by iandunn** [comment]
Thanks!

**Comment by talldan** [comment]
Looks like we didn't update docs or keyboard shortcuts modal though. I'll reopen this until that's done.

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/11321 updates the docs and modal. Is there any other place where this should be updated?

**Comment by talldan** [comment]
Nice one @nosolosw! That's all that was needed.
