### ISSUE TITLE
How to add colours to the new columns? 

### ISSUE THREAD

**Issue by klihelp** [WordPress/gutenberg#10910]
Is there a way to register support for columns background colours?
Of course it's eg. paragraphs children can have it's own colours.

**Comment by mtias** [comment]
There's currently no way (though you can add classes to the single "column" block within columns and use that mechanism). The ability to add support for background colors is likely coming in the future, but didn't want to overcomplicate the block just yet. See also https://github.com/WordPress/gutenberg/issues/4900

If there is enough weight to it we might be able to add it sooner.

**Comment by klihelp** [comment]
Thanks, I have wrapped the columns block within a container block, which have the colours and , as an extra, the width settings.
