### ISSUE TITLE
Gutenberg adds block wrappers to oEmbeds that make get_media_embedded_in_content perform sub-optimally

### ISSUE THREAD

**Issue by wmelton** [WordPress/gutenberg#10923]
**Describe the bug**
In versions prior to Gutenberg, if you embedded a video into a post, you could use `get_media_embedded_in_content()` to get the HTML of the embed and then strip it out of `the_content()` if you had a specific place to play the video in the theme. 

Now this leaves a large white gap where the video should have been in the body of the post. This appears to be due to the fact that Gutenberg adds wrapper elements (`<figure></figure>)`that did not appear in previous versions that are not accessible using existing `shortcode` tags for `video` or `embed`. 

Realistically, video post types need a function that can also grab the default `<figure class="wp-embed-block"></figure>` and strip it out of `the_content()` if the post type has its own way of displaying video posts.

**To Reproduce**
1. Embed a oEmbed video
2. Grab the video out of `the_content()` for insertion into the theme.
3. Remove the html from `the_content()` using str_replace (or similar)
4. <figure></figure> embed block element still inserted in to `the_content()` causing ugly styling issues.

**Expected behavior**
get_media_embedded_in_content() should also return any Gutenberg wrapper elements (preferably as an array value so you can still get access to the true iframe/embed/etc.)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chome
 - Version: Latest

**Additional context**
- Gutenberg Version 4.0.0

**Comment by youknowriad** [comment]
Hi @wmelton thanks for opening the issue and sorry for the late response.

Did you try using the `render_block` filter to solve your issue. It seems like you can target specific blocks and act on their content as needed.

https://developer.wordpress.org/reference/hooks/render_block/

**Comment by wmelton** [comment]
@youknowriad I have not tried that approach, and admittedly was not aware that it was an option. Will give it a try.

**Comment by youknowriad** [comment]
I'm closing this issue as it was replied. Thanks.
