### ISSUE TITLE
Request: Select a Custom Template / Post Format with Pre-Determined Blocks in "Posts"

### ISSUE THREAD

**Issue by SolespireMarcus** [WordPress/gutenberg#10926]
I envision a dropdown on the right-side panel of the Gutenberg editor, prompting users the ability to select a template (ie. "House" or "Apartment", as labelled by the admin) that would load a pre-determined set of blocks to use – a customized post format if you will. Such an ability would eliminate the necessary need for registering Custom Post Types in some instances, where Categories for Posts would assume greater power.

This would greatly enhance Gutenberg as a utility for WordPress Posts.

**Comment by mtias** [comment]
Yes, indeed. This will be one of the main focuses for *phase 2* of the project. Some more background in https://github.com/WordPress/gutenberg/issues/3588#issuecomment-427664137

This could be done now with a plugin, if people want to explore it.

**Comment by illycz** [comment]
> This could be done now with a plugin, if people want to explore it.

Which plugin please? Thanks
