### ISSUE TITLE
No crop button on Image block

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#10928]
I cannot find a Crop button when using the Image block. I think that there should be one.
![image](https://user-images.githubusercontent.com/25369857/47336810-0787bd00-d689-11e8-8bdc-304238cc0145.png)

**Comment by mtias** [comment]
You can access cropping in the "edit image" panel:

![image](https://user-images.githubusercontent.com/548849/47358032-d6c77800-d6c8-11e8-870c-0952d3d0c11e.png)

There was also this old proposal but it's not currently planned to be implemented: https://github.com/WordPress/gutenberg/issues/648

I'd love to see a further exploration there for 5.1 or 5.2.
