### ISSUE TITLE
Adjusting the new Block Navigation.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#10931]
The Block Navigation was merged through this PR:
https://github.com/WordPress/gutenberg/pull/10545

Multiple suggestions were added at the bottom of the PR.

I also linked in #7115 Insert Summary feature is somewhat similar to the Block Navigation.

**Comment by mtias** [comment]
@paaljoachim would you mind making a specific issue for any tangible improvements that could be made? It's easier to track, label, and assign to potential milestones that way. Thanks!
