### ISSUE TITLE
Deselecting image block when media library message visible should bring back the image.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#10933]
I added the comment to this PR: https://github.com/WordPress/gutenberg/pull/9264#issuecomment-432120502

I was told this: 
"Thanks for the comment @paaljoachim. This PR didn't change that functionality, it's worked the same way in the audio block since before this change, so I think you'd need to create a new issue to cover any changes you think need to be made."

**Is your feature request related to a problem? Please describe.**
Adding an image (or other content) through the URL then clicking the pencil/edit button and then deselecting the image block the media upload screen is still seen. Deselecting the image block should then remove the media upload message and show the image.

Step by step.
1. Add image or other content where the Upload, Media library and Insert from URL message is seen.
<img width="635" alt="screen shot 2018-10-23 at 10 31 26" src="https://user-images.githubusercontent.com/5323259/47347150-f0f45c80-d6ae-11e8-9d62-b1164e69e179.png">

2. See that the content has been added.
<img width="660" alt="screen shot 2018-10-23 at 10 33 02" src="https://user-images.githubusercontent.com/5323259/47347202-0cf7fe00-d6af-11e8-9632-d97028bdc372.png">

3. Click edit/pencil icon. Then Deselect the block. 
<img width="608" alt="screen shot 2018-10-23 at 10 34 23" src="https://user-images.githubusercontent.com/5323259/47347321-4466aa80-d6af-11e8-93be-c4e5949b39bb.png">

It should now revert to the content last selected in the block. If no content has been selected then let the upload, media library, Insert form URL message be seen.

**Comment by talldan** [comment]
Just adding a note that the same UI trait is also apparent in other media blocks (media, video).

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 with Firefox 63.0 on macOS 10.13.6 that attempting to edit an image that has been inserted by URL results in the image getting removed and the placeholder reappearing. ([47s](https://cloudup.com/cPaya4cpKdl))

**Comment by talldan** [comment]
I'm unsure that this is actually a bug. Fixing this could result in a user not being able drag and drop to replace the image (since when the user clicks away to choose a file the placeholder would lose focus and the block would switch back to displaying the image).

Having said that, I think the experience of displaying the placeholder when clicking the edit button is a bit clunky—it'd be cleaner to display the URL Popover (like the user sees when they click Insert From URL initially) when the edit toolbar button is clicked.

**Comment by designsimply** [comment]
> the experience of displaying the placeholder when clicking the edit button is a bit clunky—it'd be cleaner to display the URL Popover

Would the popover be pre-filled with the previous URL in that case?

Example use case: I want to grab the URL of an image I've inserted by URL. I click the image then click the pencil icon hoping to copy the URL.

**Comment by talldan** [comment]
@designsimply - Yep, that's how I'd imagine it working.

**Comment by designsimply** [comment]
Re-tested and confirmed with 5.2-alpha-44784 but I also noticed the link popover is filled if you click on "Insert from URL" again.

![9s](https://user-images.githubusercontent.com/1119271/53659038-b16aed80-3c17-11e9-9e09-4f7b44a06319.gif)

Adding the `Good First Issue` label to suggest that the "Insert from URL" popover should appear automatically if a URL can be detected when the pencil icon for an image block is clicked.

**Comment by youknowriad** [comment]
I think the flow have been updated with the thumbnail of the image visible on the placeholder now. I think we can close the issue now?

**Comment by paaljoachim** [comment]
Yes. I agree.
