### ISSUE TITLE
Add "select all" keyboard shortcut for current block

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/gutenberg#10935]
**Problem**
Currently `Ctrl+A` selects all the text in the post, which is what you would expect from a 'select all' command. The issue I'm finding is that the block layout makes me think that 'select all' should actually just select all the text in the current block.

**Possible solution**
We can't change the current behaviour of `Ctrl+A` as that is a standard behaviour on all platforms, but it would be great if we could have a modifier for the keyboard shortcut that highlights all the content of the current block. Something like `Ctrl+Shift+A` or `Ctrl+Alt+A` - that would be a logical change and I think it would be a welcome addition.

**Comment by mtias** [comment]
> Currently Ctrl+A selects all the text in the post, which is what you would expect from a 'select all' command. The issue I'm finding is that the block layout makes me think that 'select all' should actually just select all the text in the current block.

If you are in a text based block Ctrl+A selects the block content only — subsequent Ctrl+A selects the whole post. It depends on where you have the focus at the time of doing it:

![image](https://user-images.githubusercontent.com/548849/47357977-ac75ba80-d6c8-11e8-960a-44cf2bb56428.png)

**Comment by hlashbrooke** [comment]
Ah I see - in that case, I think this is a bug, so I'll report the details here.

When I first press `Ctrl+A` it does exactly as you describe - it selects the block content only, and then a subsequent `Ctrl+A` selects the entire post content. The issue is that anytime that I hit `Ctrl+A` after that, it will select the entire post content no matter what kind of block I'm in or where my focus is at the time. The only way to get back to the original functionality of selecting the block content only is to refresh the page completely, and then the same issue happens again after doing it for the first time.

I'm testing this with WordPress 4.9.8 and Gutenberg 4.0.
