### ISSUE TITLE
Extending the featured image to be able to use a video

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1094]
It would be nice to include any visual media element as a featured image. Meaning one could add a video, a gif, a png etc.

**Comment by mtias** [comment]
This would be more appropriate as a core ticket since it affects more than just the editor.

**Comment by paaljoachim** [comment]
Thanks Matias.
Trac ticket: https://core.trac.wordpress.org/ticket/41127

**Comment by porg** [comment]
## Please re-open!
- It's a basic CMS need.
- In WP Core there are two tickets
  - [#41127 Extending the featured image to be able to use a video](https://core.trac.wordpress.org/ticket/41127)
    - Closed as dupe of the next one
  - [#43117 Featured image -> Featured media](https://core.trac.wordpress.org/ticket/43117)
    - which then was also closed as a **wontfix**
- So has this endeavor ended completely? Given up? If so the issues here/there should at least state a reason why.
