### ISSUE TITLE
Error displayed for meta box of custom post type

### ISSUE THREAD

**Issue by webzunft** [WordPress/gutenberg#10947]
**Describe the bug**

Error message showing in a meta box of my custom post type. See image.

<img width="635" alt="block-error" src="https://user-images.githubusercontent.com/2728720/47358162-43db0d80-d6c9-11e8-9672-8ea6bff9697d.png">

**To Reproduce**
1. Install and activate https://wordpress.org/plugins/advanced-ads/
2. Go to Advanced Ads > Ads to the ad edit page
3. Disable the Wizard

**Expected behavior**

I would expect Gutenberg not to show this for custom post types.

**Additional context**

Using WordPress 5.0-alpha-43788

**Comment by designsimply** [comment]
@webzunft could you explain in more detail on the ticket how the meta box is being added instead of just referencing installing the plugin? Code examples seem like they would make this issue easier to help with as well as make the help request more complete.

Just to make sure, may I also ask if you have already reviewed the meta box documentation available at https://wordpress.org/gutenberg/handbook/extensibility/meta-box/ ?

**Comment by webzunft** [comment]
@designsimply thanks for your reply. I will review it. Just one question ahead: what is the desired behavior of meta boxes on custom post type edit pages?
Btw., I even have this warning now no the _Dashboard_ page and our widget there.

**Comment by designsimply** [comment]
For some reason 🙂 I got the impression you were the plugin author!

I've noticed a newer issue at #11058 which mentions the same error and also has a code example and I'd like to consolidate to that one. It does look like something fishy is going on and it seems to me meta boxes on CPTs should work but that the issue in this case may not be limited to CPTs anyway. Let's continue over in #11058.

**Comment by webzunft** [comment]
Yes, I am the plugin author. Is there subtle criticism here?
Happy to see that the dashboard-issue was reported and acknowledged now, no need to have two tickets about it. The meta box on custom post types will hopefully be resolved as well.
Thanks!

**Comment by designsimply** [comment]
Not at all. My apologies if it seemed that way. 😞
