### ISSUE TITLE
Reusable blocks not showing up on frontend

### ISSUE THREAD

**Issue by annestk** [WordPress/gutenberg#10942]
**Describe the bug**
Using 4.1 RC2, reusable blocks has completely disappeared from the front end of my site, while working normally in the editor.
I have a variety of blocks saved as reusable blocks, and none of them are showing up.

**To Reproduce**
1. Add a reusable block to the content of a post
2. Preview/publish and view the live post
3. The reusable block is not shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 69
- Version 4.1RC2, WP 4.9.8

**Comment by slimmilkduds** [comment]
I can’t reproduce this problem, works fine for me with 4.1 rc2. I also can’t offer any help unfortunatly.

**Comment by annestk** [comment]
Hmm - it was happening on two sites of mine, so I thought it was the update. But I'll do some further testing to find out if it's a conflict of some sort or the steps to reproduce should be more detailed.
Thanks for testing/trying!

**Comment by bph** [comment]
@annestk I actually see this, too. 
none of my previously created reusable blocks show on the front end, although they display nicely in the editor. (Cover image and a Custom block) 
I even created a new reusable block, but that didn't make any difference. 
I am using  Gutenberg 4 RC2 on WP 4.9.8
Google Chrome 69 MacOS 10.13.6

**Comment by designsimply** [comment]
I also cannot reproduce the problem. I tested with WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 using Firefox 62.0.3 and Chrome 69.0.3497.92 on macOS 10.13.6 as well as Chrome 70 on Windows 10. I tried with a paragraph block (new), a paragraph block (previously saved), and a cover image block (previously saved). I used the [Twenty Nineteen theme](https://github.com/WordPress/twentynineteen/) (which is currently under development).

What type of block are you using for the reusable block?

What theme are you using?

(Long shot) do you see anything fishy in the browser console when you load the published post on the front end?

@bph @slimmilkduds what OS did you test with?

**Comment by bph** [comment]
Here are the screenshots: 
The reusable block is a modified horizontal line, that is supposed to show above the heading "Using Gutenberg" 

<img width="814" alt="screen shot 2018-10-23 at 10 42 42 pm" src="https://user-images.githubusercontent.com/39980/47402828-1e73f100-d715-11e8-83a5-8b03d1d066b9.png">

**Comment by bph** [comment]
Testing it now in isolation not other blocks around, and removed plugins, common demoninator between the two sites is Jetpack

**Comment by bph** [comment]
So, I took the time to test this on a different site, and was able to reproduce it. There is nothing in the browser console. Then I started deactivating plugins. It's seem that Jetpack is the culprit on the last site. @annestk do you have Jetpack installed on your sites, too? Could you test using reusable blocks once Jetpack is deactivated?

**Comment by bph** [comment]
more testing on a different site, where Jetpack wasn't activated, confirms the Yoast 'interference'.

**Comment by designsimply** [comment]
Since #11050 will fix the issue, I commented at https://github.com/Yoast/wordpress-seo/issues/11402#issuecomment-433067770 to let them know.

/hat tip @annestk and @bph for the nice sleuthing here! Really nice work.

**Comment by wolffe** [comment]
I also have this issue, with no Jetpack and no other plugins installed. WordPress 5.2.2 with core Gutenberg (not the plugin).

**Comment by designsimply** [comment]
@wolffe since there have been several updates since this issue was originally reported, please create a new issue and include your steps to reproduce the problem, that note about not having any plugins at all installed, and please also mention your OS and browser version for reference.

**Comment by wolffe** [comment]
Even with the latest update, the reusable blocks are not there. I need to use a URL to get to them, but they are not visible by default.

**Comment by wolffe** [comment]
Also, I am using the latest version of Chrome on Windows 10 (again, latest version and completely unrelated to the plugin - the OS has no influence over a plugin or a theme).

**Comment by designsimply** [comment]
Hi @wolffe, I followed the test instructions above and reusable blocks are working in my tests. If you are seeing something different, please open a new issue and please include the exact steps to reproduce the problem. Thank you!

<img width="1281" alt="Screen Shot 2019-08-16 at Aug 16 4 30 12 PM" src="https://user-images.githubusercontent.com/1119271/63201653-6fa5f600-c043-11e9-921a-ebacf9e84506.png">

<img width="1281" alt="Screen Shot 2019-08-16 at Aug 16 4 30 21 PM" src="https://user-images.githubusercontent.com/1119271/63201651-6d439c00-c043-11e9-817b-73524266a24a.png">

<sup>Tested with WordPress 5.2.2 (no plugins) using Chrome 76.0.3809.87 on macOS 10.14.6.</sup>

**Comment by wolffe** [comment]
Yeah, but not like that. They don't appear in the menu. I see them in the editor, but not in the menu.

**Comment by designsimply** [comment]
That is a separate issue. Please go to https://github.com/WordPress/gutenberg/issues/new/choose and please include the exact steps to reproduce the problem.

**Comment by MEGACreative** [comment]
If anyone is still having the issue of Reusable Gutenberg Blocks not rendering on the front end of a WordPress site, but working normally in the editor, I found a solution for me. The filter 'the_content' wasn't being applied in my custom theme.  If your blocks aren't showing in any portion of your site make sure you've applied the proper filters to your front-end display code.  Hope this helps save some time!
