### ISSUE TITLE
Unified toolbar mode hides document settings and general menu

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#10959]
When the "Unified toolbar" mode is activated, the document settings and the general menu are stretched wide to the point they are sent beyond the viewport.

Admin user screenshot:

![unified-toolbar-quote-admin](https://user-images.githubusercontent.com/583546/47375930-b4962000-d6f1-11e8-8168-8ac595c9bb6a.png)

Contributor user screenshot:

![unified-toolbar-quote-contributor](https://user-images.githubusercontent.com/583546/47375977-d394b200-d6f1-11e8-997d-32395e061afb.png)

**Comment by nosolosw** [comment]
cc @jasmussen @karmatosed

**Comment by jasmussen** [comment]
I'm going to fix this one, good ticket, thank you.

I would note that I feel like a key ingredient in fixing this, is to fix #4287 that is, either rewrite the document outline button, or merge it with the block navigation tool. This should free up a precious 52 pixels horizontally, which is a lot when real estate is premium.

For now I'm going to tighten up the margins a bit, and increase the breakpoint that makes the unified toolbar stack below the editor bar.

**Comment by jasmussen** [comment]
CC: @mtias @alexislloyd
