### ISSUE TITLE
opposite of allowed_block_types filter

### ISSUE THREAD

**Issue by ihdk** [WordPress/gutenberg#10951]
Hello,
I'd like to define blocks which are hidden from inserter. We can do that using allowed_block_types filter, where are defined blocks which are **visible in inserter**.

Is there a filter opposite to allowed_block_types? Filter where I can define exactly which blocks **are not visible in inserter**.

Alternative may be use of allowed_block_types filter if I loop through all blocks and remove unwanted blocks - I am not sure now, if there is a function to get all available blocks and loop through them in php, something like javascript wp.blocks.getBlockTypes().
Anyway this loop through all blocks may be useless if there could be opposite of allowed_block_types filter where could be defined blocks hidden in inserter.

Thanks, Ivan.

**Comment by swissspidy** [comment]
See #2685, #9855, as well as https://github.com/WordPress/gutenberg/blob/377c222ebaecdab3771dfd3e66f940aa1fe94954/docs/extensibility/extending-blocks.md#removing-blocks

**Comment by ihdk** [comment]
Thanks for response and sorry if I was not so clear with my questions.
I am aware of the ability to deregister block, but I would not like to definitely deregister block (block is as template for page). I just want to make this block hidden from inserter so user cannot add this block manually - as I said, block is available in editor as template right when editor loads.
So I'd not deregister the block, just hide it from inserter using some opposite filter to allowed_block_types.

**Comment by ihdk** [comment]
great, thank you to point me to right direction! it was exactly what I was looking for and I found solution in the commit related to issue with column https://github.com/WordPress/gutenberg/commit/5bae40e1d2c52c5a2703081a9f55c2360d5c52d5
It's a pity that something like that isn't mentioned in docs for `supports` parameter of `registerBlockType` function.
Anyway, thanks again for your help!
Ivan.
