### ISSUE TITLE
[4.1-RC2] BUG: Background color breaks mid-paragraph using nbsp

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#10954]
**Describe the bug**
In 4.1-RC2, the background color breaks mid-paragraph when using nbsp.

**To Reproduce**
Create two paragraphs in one block with a non-breaking space between.
Choose a background color.
Save. Note that on front-end, only first section has background color.

**Expected behavior**
Non-breaking spaces should not break the background formatting.

**Screenshots**
BACK-END:
![image](https://user-images.githubusercontent.com/30901407/47366411-a1606180-d6ab-11e8-9629-cd439d3ed14a.png)

Front-end In 4.0.0:
![image](https://user-images.githubusercontent.com/30901407/47366282-5fcfb680-d6ab-11e8-8ac4-7af0d1239412.png)

Front-end in 4.1-RC-2
![image](https://user-images.githubusercontent.com/30901407/47366378-91488200-d6ab-11e8-85c3-77bd4ed2bf9f.png)

**Comment by brentswisher** [comment]
Looked into this a little bit, it is a bigger issue than just background color. If a paragraph block has two consecutive line breaks (Shift+Enter):
- In the editor, it remains one paragraph block
- On the front end, it splits into two paragraphs. 

Editor Source:
![devtools_-_localhost_8888_wp-admin_post_php_post_5_action_edit_and_edit_post_ _gutenberg_dev_ _wordpress](https://user-images.githubusercontent.com/6653970/47446298-f32ae980-d788-11e8-8e8a-d4bb5994d0fe.png)

Front End Source:
![devtools_-_localhost_8888__p_5_and_background_test_ _gutenberg_dev](https://user-images.githubusercontent.com/6653970/47446317-fa51f780-d788-11e8-9bc8-b06647832bac.png)

When this split occurs, the second paragraph does not receive the classes or styles of the original block, so no styling is applied, this includes background, color, alignment, font-size etc. One line break doesn't cause any issues.

**Comment by desrosj** [comment]
I am able to reproduce this in the 5.0 Beta 1 release with the Gutenberg plugin inactive.

**Comment by antpb** [comment]
@youknowriad is this another one that will be solved with #11050 ? seems similar

**Comment by GlennMartin1** [comment]
Yes! 4.1.1 fixed this. Thanks all.
