### ISSUE TITLE
Archives and Categories blocks: Split dropdown forms into separate blocks

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#10965]
## The issue
The Archives and Categories blocks have a toggle to make them show archives/categories using a dropdown select, rather than a list. I think this is rather odd; it completely changes the appearance and even functionality of the block. To me, it feels like a Paragraph block having a toggle to use `<h1>`-`<h6>` tags rather than `<p>`s. If a Paragraph and Heading should be separate blocks, then so should a list of category links and a dropdown to jump to a category.

## Proposed solution
I think the Archives and Categories blocks should each be split into 2 blocks: the list form and the dropdown form. Of course, there should be transforms between the two forms. The dropdown forms could be called "Archive Dropdown" and "Category Dropdown", while the other forms could simply remain "Archives" and "Categories", or else be renamed something like "Archive List" and "Category List".

**Comment by karmatosed** [comment]
I think having this as an option is fine for now. We can always of course review but I'd want some solid testing feedback as to if this is an issue. Let's close and review if we get feedback.
