### ISSUE TITLE
Reconsider server-side block code loading

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1097]
Currently we load server-side code for our blocks by [requiring each relevant file](https://github.com/WordPress/gutenberg/blob/630ff857a59524713137bc7a07740548a4264d3d/gutenberg.php#L18) and [registering blocks immediately](https://github.com/WordPress/gutenberg/blob/630ff857a59524713137bc7a07740548a4264d3d/lib/blocks/latest-posts.php#L58).

The first part is fine; the second should potentially be done on `init` instead, if only to set an example for block implementers.  (We can guarantee that `register_block_type` will be defined when we call it; other plugins won't be able to, and so should probably wait until `init`.)

The initialization was partly done this way [in the original PR that added this code](https://github.com/WordPress/gutenberg/pull/870/files#diff-1334f2cb73e38f2f89d2aaf763f07ed9R134), but if we want to do this, then it should probably be done with a single callback for each block instead.

**Comment by danielbachhuber** [comment]
@nylen What actionable steps are remaining with this issue?

**Comment by nylen** [comment]
Move server-side block registration to the `init` action.  Otherwise, plugins will copy [this pattern](https://github.com/WordPress/gutenberg/blob/v2.1.0/blocks/library/latest-posts/index.php#L68) and experience failures if they are loaded before the Gutenberg plugin.

**Comment by youknowriad** [comment]
I think this has been done with the new registration API (see https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/#enqueuing-block-scripts)

Can you confirm @aduth?

**Comment by aduth** [comment]
The latest posts block example should probably be updated to the recommended pattern.

**Comment by aduth** [comment]
Related: #2751
