### ISSUE TITLE
Remove text-align: center for blockquote

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#10970]
Replace `text-align: center;` for `blockquote` with a CSS class.

I would like to style `text-align: initial;` and `text-align: center;` differently and I can't if there's no CSS class.

**Comment by designsimply** [comment]
I don't know the reasoning for why it is setup the way it is, however, I checked and found that the classic editor also uses a `text-align` rule for the `blockquote` tag. 

Would it work for you to use CSS attribute selectors in this case? For example:

`.wp-block-quote[style*="center"] p { 
	color: red; 
}`

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by manake** [comment]
This solution is unsafe/uncertain but it could work.

The best would be probably if the editor wasn't adding any inline styles, only CSS classes.

**Comment by designsimply** [comment]
I think it's pretty standard to use `text-align: center` though, so I am not sure it's a good solution to ask for that to be changed. Let's try checking with our designers to get feedback on that suggestion though.

**Comment by manake** [comment]
From my perspective of a person who customizes WordPress for end clients (and who is an end user of WordPress) this would be the best:

```
add_theme_support( 'wp-block-styles', array(
	'core/blockquote',
	'core/gallery',
	'core/columns'
) );
```

and inside `core/blockquote` stylesheet there could be `.is-centered` or `.wp-block-blockquote--centered`.

With this I would have the best/fastest customizability and this would be future-proof and never break.

**Comment by colorful-tones** [comment]
Just want to drop a note that [the Pull Request](https://github.com/WordPress/gutenberg/pull/11646) I have in for #11609 addresses that lack of class assignment. Also, has better support for theme developers to override or enhance center aligned blockquotes.

I agree that setting inline `style="text-align: center;"` is not ideal and we should be using a class. Targeting attribute selectors, especially `[style]` is more of a absolute, last resort CSS trick (borderline hack). I would advise against it.

**Comment by gziolo** [comment]
Implemented in https://github.com/WordPress/gutenberg/pull/16779
