### ISSUE TITLE
Improve ColorPicker Accessibility

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#10975]
We made our own color picker, based on `react-color`, but with better accessibility. See: #10564

There are a few things we could do to improve the ColorPicker's accessibility:

1. change the RGB/HSL labels to full names (see: 
https://github.com/WordPress/gutenberg/pull/10564#issuecomment-430710369)
2. It's possible there are Safari + VoiceOver bugs (
https://github.com/WordPress/gutenberg/pull/10564#issuecomment-431299020); investigate them and fix if needed

**Comment by aldavigdis** [comment]
This looks like a low-hanging fruit. Going to start with the first bit. The 2nd one may be a WAI-ARIA issue, but that remains to be seen.

**Comment by skorasaurus** [comment]
closing this since both of the changes recommended by @tofumatt have been implemented.
