### ISSUE TITLE
How Can I add "Extra Attribute" in <img> tag of Core/image block?

### ISSUE THREAD

**Issue by jankimoradiya** [WordPress/gutenberg#10988]
I want to add my custom attribute in `<img>` tag. I want same like below example where **data-custom-attribute="test"** is myy custom attribute which i want to add.
Example:
`<figure><img src="" alt="" srcset="" class="" data-custom-attribute="test"> </figure>`

Is it possible to do in core/image block?
Can you please guide me?

Thank in advance.

**Comment by earnjam** [comment]
@jankimoradiya you should be able to use block filters to accomplish this. Check out this doc in the handbook for more information: https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/
