### ISSUE TITLE
Mobile test failures don't show at the end

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#10986]
This is all I get: `npm ERR! Test failed.  See above for more details.`.

Then I have to scroll over *all* other unit tests (a lot!) to see what's happening. I also have to do it slowly, it's easy to pass them and get disorientated if you ran the tests a few times in a row.

cc @hypest

**Comment by hypest** [comment]
For context, the mobile tests were made to be run in parallel as per https://github.com/WordPress/gutenberg/pull/9883#discussion_r218084845.

Is there a way to have them parallel but still stop the whole process on error?

**Comment by iseulde** [comment]
Maybe eslint is run like this? It will stop everything on error.

**Comment by gziolo** [comment]
It's no longer an issue since mobile tests were removed from Gutenberg repository.
