### ISSUE TITLE
Text overflow in `More` Blocks with translation.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#10995]
**Describe the bug**

**To Reproduce**
1. Install Japanese Translation.
2. Add a “More” block.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/1908815/47423908-4456cf80-d7c1-11e8-8aa4-1b9bc08952ad.png)

**Expected behavior**
![expect](https://user-images.githubusercontent.com/1908815/47424100-ce9f3380-d7c1-11e8-8e08-314e321837df.png)

All the text with translated is displayed.

**Desktop (please complete the following information):**
 - OS X 10.13
 - Chrome
 - Version 69.

**Additional context**
- Gutenberg 4.0.0
- WordPress 4.9.8
- Twenty Seventeen.
- No other plugins.

**Comment by torounit** [comment]
Size attribute in input, too small in japanese character. '続きを読む' ( In Japanese, it means 'Readme' ) has 5 length. but, To display everything, need size="9" .

**Comment by Soean** [comment]
Hey @torounit
thanks for reporting this issue. We already have a ticket about this issue, see #8750, so I am closing this one.
