### ISSUE TITLE
Permalink edit field is too small for long domains

### ISSUE THREAD

**Issue by AndB-GitHub** [WordPress/gutenberg#10996]
have a look at this screenshot

![permalink ui too small](https://user-images.githubusercontent.com/38046064/47424804-d8587500-d788-11e8-8e5c-4ee4560dce69.jpg)

The edit field is too small

**Comment by karmatosed** [comment]
If there was a way to check if an input box was under a certain width and then force it to go to the next line, I think this would be a good solution. If that's not case maybe we could explore putting the URL and save on a different line to the title Permalink. I would love to have a more adaptive solution though if possible.

**Comment by karmatosed** [comment]
As the permalink is now in the sidebar, for now closing this as it seems to grow to me where it is. However, if in testing of the latest PR with a long URL you do not get enough space let's reopen. The solution is to have that text box potentially wrap.

**Comment by karmatosed** [comment]
[ edit ] in testing this is still an issue, I thought it wasn't. Let's get this wrapping around when longer if possible. I am removing design feedback as this is my suggestion:

![1](https://user-images.githubusercontent.com/253067/47903349-7cbe7380-de7b-11e8-8b1d-1ba55d2625b2.png)

This design though is a sticky plaster not a longer term solution. We should iterate and review this going forward.

**Comment by DeveloperWil** [comment]
Hovering over the block title to change the permalink is very unintuitive.  Pretty much all of my clients when I created a staging site with Gutenberg installed asked me why the new editor doesn't allow them to edit the permalink.

They didn't realize the needed to hover over the block title.  It's not very obvious.  I had to Google it myself when I first used the new editor.

Bring back the old static permalink at the top of the page or have some option to display/hide it in the UI

**Comment by georgestephanis** [comment]
It gets even worse on smaller screens.

<img width="610" alt="screen shot 2018-11-13 at 12 10 54 pm" src="https://user-images.githubusercontent.com/941023/48433719-75318100-e73d-11e8-816b-52764b004050.png">

**Comment by georgestephanis** [comment]
I wonder if the easiest answer would be to right-align the permalink and just cut off the path leading to the input field more willingly to avoid shrinking the field.

**Comment by earnjam** [comment]
One thing to keep in mind here is a permalink structure that doesn't have `postname` last. Probably rare, but still possible.

Example of that on an iPhone 5 sized screen
![image](https://user-images.githubusercontent.com/4267290/48443588-a58a1700-e75f-11e8-8273-2b96750c24b5.png)

I wonder if on smaller screens we could only show the input field to edit the slug when editing, then go back to the full permalink on save.

**Comment by earnjam** [comment]
Along the lines of what @georgestephanis suggested, we could solve the original issue reported here with a larger or fixed min-width on the input field (currently 10%) and a `justify-content: flex-end` on the container span for the full permalink. 

![image](https://user-images.githubusercontent.com/4267290/48443847-5db7bf80-e760-11e8-831c-aeedd36b4d28.png)

Not positive about IE support for `justify-content` though, so would have to test that a bit.

**Comment by DeveloperWil** [comment]
Should the permalink be in the document properties area?  It's not content so shouldn't really be in the block content area.

**Comment by mtias** [comment]
> Should the permalink be in the document properties area? It's not content so shouldn't really be in the block content area.

Should be closed after #11874

**Comment by mtias** [comment]
Not wanting to remove this UI just yet, but it should be gone soon. Closing as the alternative placement in the document is in place.
