### ISSUE TITLE
Couleurs (dans paragraphes et titres)

### ISSUE THREAD

**Issue by lecerese** [WordPress/gutenberg#11008]
Bonjour

1/ Impossible de mettre les titres en couleurs

2/ Dans les paragraphes (blocs textes), impossible de mettre seulement quelques mots en couleurs. Tout le bloc est sélectionné automatiquement.

Ces deux options manquent.
Pour l'instant, Gutemberg... je n'apprécie pas vraiment.

Merci
Sandrine

**Comment by Soean** [comment]
Bonjour @lecerese 
WordPress est un projet international. Pourriez-vous décrire le problème en anglais ?
WordPress is an international project. Could you please describe the problem in English?

**Comment by designsimply** [comment]
For now I have translated with https://translate.google.com/

> 1 / Can not put titles in colors
> 
> 2 / In paragraphs (text blocks), it is impossible to put only a few words in color. All the block is selected automatically.

**Comment by designsimply** [comment]
The plugin [Advanced Rich Text Tools](https://wordpress.org/plugins/advanced-rich-text-tools/) will now add inline text and background color controls.

**Comment by spounky** [comment]
could you complete your plugin with the border of block, the thickness of the border, the color of the border, the possibility of rounded corners, the shadows and the settings on them?
