### ISSUE TITLE
Quote Block-Paragraph Block structure loses spacing on rendering

### ISSUE THREAD

**Issue by ChipNowacek** [WordPress/gutenberg#11014]
**Describe the bug**
Quote block followed by paragraph block loses space in render

**To Reproduce**
Place quote block before a paragraph block and press "Preview"

**Expected behavior**
The space between the blocks should be maintained.

**Screenshots**
![screen shot 2018-10-24 at 11 18 48 am](https://user-images.githubusercontent.com/3668197/47441722-c245b700-d77e-11e8-8998-788cd1c5b2b5.png)
![screen shot 2018-10-24 at 11 19 20 am](https://user-images.githubusercontent.com/3668197/47441814-06d15280-d77f-11e8-8e96-30fc3a50e4b5.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Safari 12.0 and Chrome 70.0.3538.67

**Smartphone (please complete the following information):**
not applicable

**Additional context**
Using Gutenberg 4.0.0

**Comment by arunsathiya** [comment]
From what I see, different themes respond to this differently. I am able to see spacing between the quote block and the paragraph block on Twenty Sixteen and Twenty Fifteen but not on Twenty Seventeen theme.

### Editor view

<img width="382" alt="screenshot 2018-10-24 at 21 18 47" src="https://user-images.githubusercontent.com/18581859/47443779-b8e63a00-d7d2-11e8-8ef8-f776b029caa1.png">

### Twenty Seventeen 

<img width="360" alt="screenshot 2018-10-24 at 21 19 41" src="https://user-images.githubusercontent.com/18581859/47443796-bdaaee00-d7d2-11e8-9318-14188d9f35e3.png">
<sup>Image indicating the spacing between quote block and paragraph block on the Twenty Seventeen theme</sup> 

### Twenty Sixteen 

<img width="376" alt="screenshot 2018-10-24 at 21 19 32" src="https://user-images.githubusercontent.com/18581859/47443806-c26fa200-d7d2-11e8-8101-891fe0b6ec76.png">
<sup>Image indicating the spacing between quote block and paragraph block on the Twenty Sixteen theme</sup> 

### Twenty Fifteen 

<img width="375" alt="screenshot 2018-10-24 at 21 19 55" src="https://user-images.githubusercontent.com/18581859/47443809-c56a9280-d7d2-11e8-920e-6d886bc55d6d.png">
<sup>Image indicating the spacing between quote block and paragraph block on the Twenty Fifteen theme</sup>

**Comment by ChipNowacek** [comment]
I am indeed using Twenty Seventeen. Would you recommend I open an issue with them?

**Comment by youknowriad** [comment]
I think the last versions of all these themes (in the 5.0 branch) have editor styles support for Gutenberg which means this issue might be obsolete. I'd consider checking the 5.0 branch first.

**Comment by ChipNowacek** [comment]
Thanks. I'll see if I can figure out how to do that.

**Comment by ChipNowacek** [comment]
Weird. I'm still seeing it.
Gutenberg 4.1.1
OS X 10.13.6
Safari 12.0
Chrome 70
Twenty Seventeen 1.7

**Comment by youknowriad** [comment]
@ChipNowacek The new version of Twenty Seventeen with the fix is not released yet. It's in the 5.0 branch of WordPress.

**Comment by ChipNowacek** [comment]
Thanks everyone.

**Comment by ChipNowacek** [comment]
Would it be helpful for me to close the issue?

**Comment by youknowriad** [comment]
Yes, let's close for now. Thanks
