### ISSUE TITLE
More detailed list inside the Block Navigation

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11010]
Looking at the Block Navigation of the page I was working on right now looks like this:
![screen shot 2018-10-24 at 15 51 32](https://user-images.githubusercontent.com/5323259/47435493-0481ef00-d7a5-11e8-9c51-521043613eef.png)

What about just using the icon and then showing some of the text in the beginning of the paragraph?
Or having in one way or another some more details inside the list.

**Comment by paaljoachim** [comment]
I should take a closer look at:
https://github.com/sortabrilliant/guidepost

**Comment by sarahmonster** [comment]
Yes please! This would make a big difference in the overall usefulness of this feature. I'd ❤️ to see a PR for this, but I'm adding the accessibility bat-signal first to be sure that wouldn't cause any potential accessibility snafus. 🦇

**Comment by afercia** [comment]
Discussed during today's accessibility bug scrub, definitely agree the list of blocks would need some more context. We wouldn't recommend to remove the textual indication of the block type though.

There are plans to review this feature and maybe consolidate Block Navigation and Document Outline. The UI could just provide more horizontal space to display the block type and some text from the block.

**Comment by gziolo** [comment]
> There are plans to review this feature and maybe consolidate Block Navigation and Document Outline. The UI could just provide more horizontal space to display the block type and some text from the block.

Related PR from @youknowriad: #14956. It looks like the idea is to have one icon and both features located in tabs.

**Comment by Mahjouba91** [comment]
Hey, This is definitely a must have in my opinion. I hope this is an achievable piece.

**Comment by paaljoachim** [comment]
An improved list view is coming into place, so that I am closing this issue.
