### ISSUE TITLE
YouTube block adds space above video with "Automatically scale content" on

### ISSUE THREAD

**Issue by caimin-j** [WordPress/gutenberg#11020]
Using Gutenberg v4.0-rc.1

**Describe the bug**
When embedding a YouTube video using the YouTube block, an unwanted space appears above the video if *Automatically scale content* is toggled on in the block settings.

**To Reproduce**

1. Add a YouTube block.
2. Paste in a YouTube video URL
3. Click Embed
4. Make sure *Automatically scale content* is on (this seems to be the default).
5. Preview and see the space above the video

**Expected behavior**
That videos appear without unwanted space above them, as with the Video block.

**Screenshots**
In the screenshot below, the YouTube block is immediately under a Paragraph block; there are no empty blocks or anything else in-between in Gutenberg.

<img width="438" alt="video test caimin mystagingwebsite com at pressable 2018-10-24 19-48-11" src="https://user-images.githubusercontent.com/37620825/47450551-d4971380-d7c5-11e8-9a8a-05ba09528ee7.png">

**Desktop (please complete the following information):**
 - Mac
 - Chrome
 - 70.0.3538.67

Tested with two different themes.

**Comment by chrisvanpatten** [comment]
@caimin-j What theme are you using, and do you have a link we can check out?

**Comment by Soean** [comment]
Should be fixed in Gutenberg 4.1.
Please reopen, if you still can reproduce it.
