### ISSUE TITLE
Post title height in Safari 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1102]
I see there's some JS calculation to add inline styles to the post title, and looks like the calculation in Safari applies a height with a greater value than in other browsers. Not sure why. Haven't tested in IE/Edge.

Chrome:

![screen shot 2017-06-10 at 12 15 58](https://user-images.githubusercontent.com/1682452/27002019-5c749086-4dd7-11e7-8243-6b50f6eb9d5c.png)

Safari:

![screen shot 2017-06-10 at 12 18 31](https://user-images.githubusercontent.com/1682452/27002020-6243dd14-4dd7-11e7-9b93-23306f9c2cc9.png)

**Comment by aduth** [comment]
Noting that under the hood we use [`react-autosize-textarea`](https://www.npmjs.com/package/react-autosize-textarea), which itself uses [`autosize`](https://www.npmjs.com/package/autosize) as a base. Not clear whether this is an issue of one or the other of these dependencies, or in our own usage.

**Comment by mtias** [comment]
I haven't been able to reproduce after the line-height fix we did for the title. If it's still happening for you, please reopen.
