### ISSUE TITLE
Cover image bold text is same weight as normal text

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11021]
When you edit the title of a cover image you are presented with a floating toolbar:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47450137-5b46f300-d7bc-11e8-8361-5cfff0cc8e02.jpg)

Making the text bold doesn't change the weight of the font. You can check this by selecting a word and making it bold. It looks the same as the rest of the text:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47450182-77e32b00-d7bc-11e8-8bc1-ee65e143c0a0.jpg)

The DOM appears correct, but the `strong` tag has a weight of 300, which appears to be the weight of normal text.

![devtools_-_latest_local_wp-admin_post_php_post_227_action_edit](https://user-images.githubusercontent.com/1277682/47450210-8c272800-d7bc-11e8-9aac-b72c22ce99bf.jpg)

**To Reproduce**
1. Create a cover image block
2. Set the text to 'some title'
3. Highlight 'some' and click the bold format button
4. Note that the weight doesn't change

**Expected behavior**
The selected text to appear bold

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

Gutenberg 4.1

**Comment by Soean** [comment]
We already have a ticket about this issue, see #8202. So I am closing this one here.
