### ISSUE TITLE
Custom Block Help Request: FAQ (Ability to create multiple questions in one block)

### ISSUE THREAD

**Issue by blindstuff** [WordPress/gutenberg#11026]
I'm trying to create a block to manage FAQ's, where the user can add as many questions as desired in a single block.

I've received the design but I've so far been unable to find a data storage strategy using attributes that solves this issue.

In short, I'm attempting to mimic the [YOAST SEO FAQ block](https://yoast.com/app/uploads/2018/09/yoast-seo-content-blocks-faq-screen.png)'s functionality but with less features and our own design.

My initial approach was to store an array with the data in the block attributes as follows (questions in this version are stored in pair due to design, but I also attempted it without pairs):

```
questions: {
	type: 'array',
	source: 'children',
	default: [{
			one: {
				question: 'Why is ***** rebranding?',
				answer: 'We are ***** organization.'
			},
			two: {
				question: 'What is ****? ',
				answer: 'We are **** organization.'
			}
		},
		{
			one: {
				question: 'Why **** mean?',
				answer: 'The **** experience.'
			},
			two: {
				question: '',
				answer: ''
			}
		}
	]
}
```

Then displaying in the editor (and similarly in save) as:

```
<div class="container w-container">
	{questions.map(function(pair, index){
		return <div class="container-questions">
				<div class="question-block">
					<RichText
						tagName="h4"
						placeholder='Question'
						keepPlaceholderOnFocus="true"
						onChange={onChangeQuestions}
						value={pair.one.question}
					  />
					<h4>{pair.one.question}</h4>
					<p>{pair.one.answer}</p>
				</div>
				<div class="question-block">
					<h4>{pair.two.question}</h4>
					<p>{pair.two.answer}</p>
				</div>
			</div>;
	})}
</div>
```

My issue with this approach is that i'm unable to save the complex data structure in the attributes.

Is there anything in particular that I'm doing wrong or is this strategy not viable with Gutenberg, if so, any alternate recommendations?

**Comment by blindstuff** [comment]
I hadn't been able to work on till recently. Progressed but i'm getting another odd error now.

Updated code:

```
attributes: { // Necessary for saving block content.
	title: {
		type: 'array',
		source: 'children',
		selector: 'h3',
		default: 'Frequently Asked Questions'
	},
	questions: {
		type: 'array',
		source: 'children',
		default: [
			{
				one:{
					question:'Why is th******* rebranding?',
					answer: 'We are a ******organization.'},
				two:{
					question:'What is going on? ',
					answer: 'We are a ********organization.'
				}
			}
		]
	}
},
```

In edit:

```
const onChangeQuestions = (index,pair,value) => {
	if(pair === 'one'){
		var newQuestions = props.attributes.questions;
		newQuestions[index].one.question = value;
		setAttributes( {newQuestions} )
	}else if(pair === 'two'){
		var newQuestions = props.attributes.questions;
		newQuestions[index].two.question = value;
		setAttributes( {newQuestions} )
	}
};
```
```
{questions.map(function(pair, index){
	return <div class="container-questions">
			<div class="question-block">
				<RichText
					tagName="h4"
					placeholder='Question 1'
					keepPlaceholderOnFocus="true"
					onChange={ value => onChangeQuestions (index, 'one', value)}
					value={pair.one.question}
				  />										
				<p>{pair.one.answer}</p>
			</div>
			<div class="question-block">
				<RichText
					tagName="h4"
					placeholder='Question 2'
					keepPlaceholderOnFocus="true"
					onChange={ value => onChangeQuestions (index, 'two', value)}
					value={pair.two.question}
				  />
				<p>{pair.two.answer}</p>
			</div>
		</div>;
})}
```

In Save:
```
{questions.map(function(pair, index){
	return <div class="container-questions">
			<div class="question-block">
				<h4>{pair.one.question}</h4>
				<p>{pair.one.answer}</p>
			</div>
			<div class="question-block">
				<h4>{pair.two.question}</h4>
				<p>{pair.two.answer}</p>
			</div>
		</div>;
})}
```

This works correctly while editing and displays correctly on site. However, as soon as I re-enter the editor the content of the attributes for the questions is off. I've placed some console.logs throughout the code and can see that the data in that field is different while editing than when reloading. It seems to be something odd during serialization? It seems to be saving the Markup instead of the object.

[Odd data seen here](https://imgur.com/a/dZl770T)

Am I just pursuing the wrong strategy here?

**Comment by talldan** [comment]
This is very late, so likely not an issue any more, but I'll answer anyway 😄 

The first thing I noticed is that the block output has `.container.w-container` classes applied to two separate elements. The selector used to source the block attributes for the questions is `selector: '.container.w-container'`, and that will select the first element, which only contains the title. The selector for a query should be able to select the individual correct element (like `.container-questions` is).

The functionality of the query is to then find repeated elements (e.g questions and answers) and map them into an array, so unique classnames on questions `q1`, `q2` won't work, they should be generic (`.q`, `.a`).

The query would have to be defined like this:
```jsx
questions: {
    type: 'array',
    source: 'query',
    selector: '.container-questions',
    query: {
        question:{
            type: 'string',
            source: 'text',
            selector: 'h4.q'
        },
        answer:{
            type: 'string',
            source: 'text',
            selector: 'p.a'
        },
    }
}
```

Which would create an array of the block's content:
```js
[
  {
     question: 'Why is the company rebranding?',
     answer: 'We are a reinvented organization.'
  },
  {
    question: 'What is going on?',
    answer: 'We are a modernizing the organization.'
  }
]
```

**Comment by blindstuff** [comment]
Thank you for the response. I can't honestly remember how this was solved, but we got it done.
