### ISSUE TITLE
Block: Media & Text image vertical alignment is wrong

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#11024]
## Description

In my theme the image is getting outside the block box at the bottom.

## To reproduce

Set image, set text. Set block background color. See the image getting outside the block box at the bottom.

## Expected behavior

Image is not getting outside the block box.

## Screenshots

![Media & Text block image getting out of the block box bottom edge](http://easycaptures.com/fs/uploaded/1297/5441669140.jpg)

## Additional context

Gutenberg v4.1.0-rc.1

**Comment by jorgefilipecosta** [comment]
Hi @webmandesign, thank you for reporting this issue.
Could you share in what theme you are testing the block on?
It happens in the editor or also on the frontend?

**Comment by webmandesign** [comment]
@jorgefilipecosta Well, I'm testing in my [Reykjavik theme](https://wordpress.org/themes/reykjavik/), but I'm working on a theme update that works with Gutenberg as the currently available version throws PHP error with Gutenberg. If you want to test, you can download the master code from https://github.com/webmandesign/reykjavik though.

But anyway, the image position should definitely not be compensated with negative bottom margin. Especially because that also depends on font size and line height. Forcing `vertical-align` on the image should fix the issue perfectly fine.

The issue doesn't happen in the editor as I don't provide editor styles in the theme yet.
