### ISSUE TITLE
enqueue_block_editor_assets hook is enqueing styles before Doctype

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11035]
**Describe the bug**
The `enqueue_block_editor_assets` no longer works correctly. When trying to use it to enqueue some styles in the head, when in the Editor, it adds the styles before the `<!DOCTYPE html>` declaration.

![screenshot_893](https://user-images.githubusercontent.com/2078245/47474926-15923500-d865-11e8-80c8-93773032da12.png)

**To Reproduce**
Try adding some simple code like this to your theme and once in the editor, view the page source and see where the css is added

```
function ephemeris_block_editor_styles() {
	$styles = '';

	// Remove max-width on Full blocks
	$styles .= 'body.gutenberg-editor-page .edit-post-visual-editor .editor-block-list__block[data-align="full"] {max-width: none;}';

	// Output our styles into the <head>
	echo '<style type="text/css">' . $styles . '</style>';
}
add_action( 'enqueue_block_editor_assets', 'ephemeris_block_editor_styles' );
```
**Expected behavior**
CSS should be added to the `<head>`

**Desktop (please complete the following information):**
- OS: macOS Sierra 10.12.6
- Browser: Firefox Quantum 63.0 (64-bit)
- Version: WP 5.0 Beta 1

**Comment by ocean90** [comment]
Hmm, this sounds like `_doing_it_wrong()`. `enqueue_block_editor_assets` should only be used to _enqueue_ assets.

`enqueue_block_editor_assets` is now called in
https://github.com/WordPress/wordpress-develop/blob/9673e83/src/wp-admin/edit-form-blocks.php#L346-L356

**Comment by maddisondesigns** [comment]
@ocean90 I'm only using the hook that was told to use on a another issue here, and it was working fine with 4.9.8 & the Gutenberg plugin.

If there's another hook that I should be using though, then just let me know. I need to be able to enqueue a separate stylesheet, plus add dynamic styles into the `<head>`.

**Comment by ocean90** [comment]
That would be a proper use case for [`wp_add_inline_style()`](https://developer.wordpress.org/reference/functions/wp_add_inline_style/). Use the handle of your separate stylesheet for `$handle` and `$data` is your dynamic CSS.

**Comment by designsimply** [comment]
Closing based on the recommendation to use `wp_add_inline_style()` for this use case. Thank you!
