### ISSUE TITLE
Panel (sidebar) toggle icons misaligned in Safari

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1103]
Looks like Safari doesn't like space-between when used on button elements that contain SVGs. The toggle icons should be aligned on the right, and they're on Chrome:

<img width="291" alt="screen shot 2017-06-10 at 12 38 39" src="https://user-images.githubusercontent.com/1682452/27002166-00eda650-4dda-11e7-81d2-08163d694531.png">

but not in Safari (v. 10.1.1):

<img width="296" alt="screen shot 2017-06-10 at 12 38 24" src="https://user-images.githubusercontent.com/1682452/27002172-1b826cda-4dda-11e7-93a3-43205ccdefa8.png">

`margin-left: auto` seems to fix this, even if it shouldn't be necessary. Worth noting seems everything works correctly in Safari Technology Preview Release 30 (Safari 10.2, WebKit 12604.1.22).

**Comment by aduth** [comment]
Likely culprit: https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers
