### ISSUE TITLE
Inline image block: can't select the image after toggling the “Drop Cap” option.

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#11030]
**Describe the bug**
When the “Drop Cap” option is activated, any inline images added to the text can't be selected anymore. To be able to select the image, the block in which the image was inserted needs to be removed and added again.

**To Reproduce**
1. Insert a Paragraph block and add some text to it.
2. Now, place the cursor on any point of the text and add an Inline Image block. Click on the image to check that it can be selected.
3. Activate the Drop Cap option in the block settings.
4. The image immediately looses the selection and can't be selected again.

**Expected behavior**
We should be able to select the inline image after the Drop Cap option is activated.

**Screenshots**

![inline-image-drop-cap-bug](https://user-images.githubusercontent.com/1451087/47465036-9697f080-d7c1-11e8-86bb-d0306a3072c9.gif)

**Desktop:**
 - MacOS X 10.12
 - Chrome 69

**Additional context**
 - 5.0-beta1-43823
 - Twenty Seventeen.
 - No other plugins.

**Comment by Smith-erin** [comment]
I was able to reproduce this.

OS X 10.14
Chrome 69
5.0-beta1-43832
Twenty Seventeen
No other plugins

**Comment by NickPax** [comment]
Thank you @pagelab. The animated gif really helped me.
