### ISSUE TITLE
Cannot save drafts or publish posts.

### ISSUE THREAD

**Issue by rolandixor** [WordPress/gutenberg#11033]
What it says on the tin. I can't really provide any other useful info other than... it doesn't work. The editor has a sweet interface, but it's pointless because you can't save a thing.

**Comment by rolandixor** [comment]
I searched for similar issues and found out it was due to a security plugin blocking the REST API.

**Comment by designsimply** [comment]
Nice find and thank you for the follow-up!! May I ask which plugin was the source of the trouble? Maybe we can reach out and let them know what the problem was. 🙂

**Comment by rolandixor** [comment]
Hi, the plugin in question is "WP Cerber"
