### ISSUE TITLE
Classic Editor buttons are all italicised

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11034]
**Describe the bug**
All the buttons on the Classic Editor toolbar are italicised.

![screenshot_886](https://user-images.githubusercontent.com/2078245/47472768-98ae8d80-d85b-11e8-8aee-7767dff6cb06.png)

![screenshot_887](https://user-images.githubusercontent.com/2078245/47473015-897c0f80-d85c-11e8-9863-411f0a6ae340.png)

**To Reproduce**
1. Edit a page
2. Insert a Classic Editor Block

**Expected behavior**
Toolbar buttons shouldn't be in italics

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox Quantum 63.0 (64-bit)
 - Version: WP 5.0 Beta 1
- Theme: Twenty Seventeen

**Comment by mcsf** [comment]
Thanks for the report. From my testing, this is specific to Twenty Seventeen — more specifically, the version in WP 5.0 Beta 1.

See: [Twenty Seventeen: Update theme to add Gutenberg styles and support](https://core.trac.wordpress.org/ticket/45045). I suggest taking it up in the ticket or in #core-themes.

**Comment by designsimply** [comment]
Adding a link to the comment for reference: https://core.trac.wordpress.org/ticket/45045#comment:35

Thanks for reporting there!
