### ISSUE TITLE
Editor: Missing Core styles in PostVisibility component

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#11049]
**Describe the bug**
When rendering the `PostVisibility` component from the `@wordpress/editor` package outside of Core, there are some styling issues caused by the lack of the Core styles.

**To Reproduce**
* Load Gutenberg without Core styles by adding the following snippet into gutenberg.php:
```php
function remove_default_stylesheets() {
  wp_deregister_style('wp-admin');
}
add_action('admin_init','remove_default_stylesheets');
```
* Go to the Gutenberg editor
* Open the Post Visibility dialog on the sidebar

**Expected behavior**
The Post Visibility dialog should looks like when the Core styles are present (see screenshots below).

**Screenshots**
With Core styles
<img width="272" alt="screen shot 2018-10-24 at 12 56 11" src="https://user-images.githubusercontent.com/1233880/47492655-cc82b680-d84d-11e8-9480-d3532ed91189.png">

Without Core styles
<img width="272" alt="screen shot 2018-10-24 at 12 56 18" src="https://user-images.githubusercontent.com/1233880/47492682-d3a9c480-d84d-11e8-8bde-cbb5a6a3ffb9.png">

**Additional context**
Issue found while integrating Gutenberg into Calypso (Automattic/wp-calypso#27697, Automattic/wp-calypso#28069)

**Comment by draganescu** [comment]
I tested this and the problem is visible in both places where post visibility is used:

- in the document tab when clicking visibility status
- in the publish pane, on the visibility accordion panel.

**Comment by carolinan** [comment]
Is this still valid?
When I deregister the styles as mentioned above, I see the following:
![Post visibility screen ](https://user-images.githubusercontent.com/7422055/177974543-6cd1f76f-8dbf-498c-ac19-23abf7cd703a.png)

**Comment by mmtr** [comment]
Looks like this was solved by https://github.com/WordPress/gutenberg/pull/22596, so we can close this one out!
