### ISSUE TITLE
Themes should specify alignwide content width

### ISSUE THREAD

**Issue by markfinst** [WordPress/gutenberg#11042]
WordPress requires themes to specify `$content_width`, which is used for various optimizations, such as `sizes` attribute for responsive images or videos, for example if content-width is 600px:

```html
<img sizes="(max-width: 600px) 100vw, 600px" srset="..." />
```

Then Gutenberg comes in with classes `alignwide` and `alignfull`. For "full" you just need:

```html
<img sizes="100vw" srset="..." />
```

But we do not know max-width of `alignwide`, so we can't do optimization like:

```html
<img sizes="(max-width: {wide_width} ) 100vw, {wide_width}" srset="..." />
```

## Proposal

Instead of just 

```
add_theme_support( 'align-wide' );
```

recommend theme developers to specify the second parameter which is `max-width` of the "wide" container:

```
add_theme_support( 'align-wide' , 1200);
```

which can be retrieved by:

```
get_theme_support( 'align-wide' );
// get_theme_support( 'editor-color-palette' ) - used by gutenberg colorpicker
```

([link existing align-wide docs](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#opt-in-features)):

**Comment by salcode** [comment]
This seems like a reasonable idea for an enhancement. This could be added in a backwards-compatible way.

I suggest tagging this as `[Type] Enhancement`

**Comment by kimcoleman** [comment]
A possible alternative would be to add a new default image size for "wide", just like those that exist for Thumbnail, Medium, Large and Full. This image size could be filtered by themes just like other default image sizes, and pull in as the "max-width" attribute for ```wp_image_add_srcset_and_sizes```

https://developer.wordpress.org/reference/functions/wp_image_add_srcset_and_sizes/

**Comment by mtias** [comment]
Closing as this is largely absorbed in `theme.json` now.
