### ISSUE TITLE
inline-image block causes issue if post has any image.

### ISSUE THREAD

**Issue by mlbd** [WordPress/gutenberg#11053]
**Describe the bug**
I post has any image already and then if I tried to add inline-image block from editor add-block ( not top one ) then add block box doesn't despair but it should be.

**To Reproduce**
1. First add block that contain image like cover block or image block
2. Click top add block and select paragraph block
3. Now click add block from editor ( not top one )
4. Click inline-image block

**Expected behavior**
After select inline-image it should despair the add block box but instead of hide it overlap into media upload popup.

**Screenshots**
![inline-image block issue](https://raw.githubusercontent.com/mlbd/panaroma/master/Untitled%20Project.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 70.0.3538.77
 - WordPress 5.0 Beta 1

**Comment by simison** [comment]
The inline image block is buggy even if the post does not have image previously.

The whole media component crashed:

<img width="2255" alt="screenshot 2018-12-06 at 12 45 38" src="https://user-images.githubusercontent.com/87168/49579739-d112b280-f955-11e8-9eb2-1ece717baf89.png">

> Warning: React does not recognize the `formatType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formattype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Block picker stayed hovering just like it does in @mlbd 's screencast:

<img width="1491" alt="screenshot 2018-12-06 at 12 44 05" src="https://user-images.githubusercontent.com/87168/49579740-d112b280-f955-11e8-84d7-6d9cc528766b.png">

Firefox.
Using current `master` Gutenberg and WP 4.9
TwentyNineteen theme.

**Comment by iseulde** [comment]
I'm not able to reproduce in Gutenberg `master`.
