### ISSUE TITLE
Dashboard widget error message: What to do?

### ISSUE THREAD

**Issue by pixelbart** [WordPress/gutenberg#11058]
Hello everybody,

I'm trying to make my plugin compatible and receive the message directly in the dashboard. The widget is not intended for the editor and should only be displayed in the dashboard. So how can I disable the message?

Message: _This meta box, from the Helpful plugin, isn't compatible with the block editor._

In Codex and otherwise, I have found no information. I also have the following, packed into the callback arguments:

``
wp_add_dashboard_widget(  
  'helpful_widget',  
  _x( 'Helpful', 'headline dashboard widget', 'helpful' ),  
  array( $this, 'widget_callback'),  
  null,  
  array( '__block_editor_compatible_meta_box' => false )  
);``

Any ideas?

**Comment by mrwweb** [comment]
See this message on Dashboard widgets from Yoast, Modern Tribe (The Events Calendar), and WP Help plugin

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.1.1 using Firefox 63.0 on macOS 10.13.6 by installing Helpful 2.4.4 plugin from https://wordpress.org/plugins/helpful/ and checking the WP Admin > Dashboard page and I see the Helpful panel there without any error:

![screen shot 2018-10-25 at 4 37 16 pm](https://user-images.githubusercontent.com/1119271/47534478-ba683e80-d874-11e8-8b39-17c588929d7f.png)
<sup>Seen at http://alittletestblog.com/wp-admin/index.php running WordPress 4.9.8 and Gutenberg 4.1.1 using Firefox 63.0 on macOS 10.13.6.</sup>

Am I looking at the right thing? Do you happen to be testing with WP 5.0 beta and not with the Gutenberg plugin? May I ask your WP and Gutenberg plugin version numbers?

**Comment by mrwweb** [comment]
> Do you happen to be testing with WP 5.0 beta and not with the Gutenberg plugin?

@designsimply Yes. Testing 5.0-beta1

**Comment by designsimply** [comment]
Okay! This may be different then and I'm still working out when to report issues here versus https://core.trac.wordpress.org/

**Comment by pixelbart** [comment]
> > Do you happen to be testing with WP 5.0 beta and not with the Gutenberg plugin?
> 
> @designsimply Yes. Testing 5.0-beta1

this ... excuse me for not mentioning that! I just received the email from WordPress.org to take care of my plugins. Then i downloaded the developer version and saw the messages.

Unfortunately, I could not find anything about it on the internet or in the codex.

Thank you for your efforts! :)

**Comment by designsimply** [comment]
Closing this in favor of the Trac ticket for WP 5.0 which is being worked on already at https://core.trac.wordpress.org/ticket/45172

Thank you for testing, for updating plugins, and for reporting the issue!
