### ISSUE TITLE
Color Options

### ISSUE THREAD

**Issue by riemerta6** [WordPress/gutenberg#11059]
In the very least, we need the option to add theme support for colors in more areas such as, Heading block, Column block, List block, and Cover text. I know that issues have been closed on this before related to Heading block, but I think this is a necessity especially with the introduction of the Media & Text block. For instance, if I add a Heading block in the text area of a Media & Text block that has a background color I can't change the Heading color without added a css class (not intuitive for most basic users).

Here's what I think makes the most sense (open to other ideas of course):
- Heading block: Text color
- Column block: Background color for wrapper, Background color for individual columns (less important)
- List block: Text color
- Cover block: Text color

**Comment by designsimply** [comment]
Hi! Thanks for posting. There's an open issue for this already at #8171 and I noticed it doesn't mention the Columns or Cover blocks specifically. Would you be able to add those as suggestions in the comments on that issue? That way we can consolidate this request and keep the discussion about it in one place for now (we can split it out later on a per block basis if needed).
