### ISSUE TITLE
Need to change document title with js code dynamically when user is editing the post

### ISSUE THREAD

**Issue by InoPlugs** [WordPress/gutenberg#11064]
Hi,

I need to modify the content of posttitle while user is editing the post with js depending on user input.

I'm talking about:

```
<div class="editor-post-title">
        <div class="editor-post-title__block">
            <div>
               <label for="post-title-1" class="screen-reader-text">Add title</label>
              <textarea id="post-title-1" class="editor-post-title__input" placeholder="Add title" rows="1" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 95px;">My title 2 new</textarea>
          </div>
      </div>
</div>

```
which is before

`<div class="editor-block-list__layout">`

We have hidden the complete Gutenberg editor with CSS because we allow the user to switch between a layout builder covering the complete screen or Gutenberg. We added a post title field at top of our screen which we want to copy to the Gutenberg textarea so user has the same title in both editors.

I can read blocks, add and modify blocks within "editor-block-list__layout" and also save the post with js, but I did not find a way to access the textaerea class="editor-post-title__input".

Modifying with the .val attribute of the textarea shows the modified content, but when clicking into it is reset to the old value.

-----

Is there a way to get the post content as it is saved to db post_content field ?  

When user clicks a button to change the editors I need to get this with js to add it to our elements ( without the need to save the post and reload it from backend)

-----

How can I get the objects for publish button, save draft, .... and do they have callbacks when finished with saveing ?

-----
Thanks for help in advance :)

-----

Would be great if you could add some code snippets for that to your documentation.

-----
Gutenberg 4.1.0
WP 5.1-alpha-43678
Theme: Enfold 4.5  (I'm working in core development)

**Comment by youknowriad** [comment]
yes, you should be able to retrieve the post content, update the post title, manipulate any post related data with ease. To do so, you should use the data module.

I wrote a blog post here that might help https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/
