### ISSUE TITLE
Metaboxes overlap the content of the editor

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [WordPress/gutenberg#11060]
**Describe the bug**
When the content is taller than the viewport, there are conflicts with meta boxes. They are not initially visible, however they appear once you start scrolling and hide the content that is displayed behind them.

If I remove the following declaration, the issue disappears:

```css
.editor-writing-flow {
    display: flex;
    flex-direction: column;
    height: 100%;
}
```

**To Reproduce**
The issue happens on a private website and cannot be publicly reproduced. 1517500-zen

1. Open the edit screen of a post/page that has content, which is at least twice as tall as the viewport.
2. Scroll down
3. See error

**Expected behavior**
No overlap

**Screenshots**

![image](https://user-images.githubusercontent.com/5311119/47501595-2f804780-d866-11e8-9d48-7c4ba6e0ca13.png)

In this case I have collapsed the metaboxes in order to make it visible that the content continues beneath them.

Deactivating Yoast SEO / Monarch separately does not change this behavior.

**Desktop:**
 - OS: MacOS 10.14
 - Browser Google Chrome
 - Version 70

**Additional context**
- Gutenberg 4.1.0 (latest atm)

**Comment by designsimply** [comment]
I tested using the steps provided with WordPress 4.9.8, Gutenberg 4.1.1, and Yoast 9.0.2 using Chrome 69.0.3497.92 on macOS 10.13.6 and I didn't see a problem with the meta boxes overlapping. 

After that, I checked for the latest version of Yoast and noticed the [changelog](https://yoast.com/wordpress/plugins/seo/change-log/) for 9.0.2 says:

> Fixes a bug where the Gutenberg (v4.1) editor was partially hidden behind the metabox.

If you haven't already, please try upgrading to Yoast 9.0.2.

**Comment by RadoslavGeorgiev** [comment]
I updated Yoast SEO to 9.0.2, but it did not fix it.

As mentioned in the initial report, the culprit cannot be Yoast SEO because even when I deactivate it, other meta boxes are getting in the way. 

Is there anything else I could report that could be helpful?

**Comment by designsimply** [comment]
> Is there anything else I could report that could be helpful?

Yes! Since the steps to reproduce didn't help me to see the problem happen when I tried testing, can you think of anything else in the steps I could try differently? Is it possible the conflict lies with the theme? As a basic troubleshooting step (and so we know this has been checked since it's a rather odd display issue kind of thing) could you try clearing browser cache and checking it again to see if that makes the problem go away? I tested with Chrome and didn't see the problem happen. I see you are also using Chrome, but is the problem also present for you in other browsers? (this could help rule out a browser-specific issue) Last thing I can think of 🙂 can you check your web developer tools console panel at the time you load the editor and see the problem happen and check to see if any errors or warnings show up there?

**Comment by RadoslavGeorgiev** [comment]
@designsimply I started recreating the environment and I only needed the Divi theme in order to get to the same broken state.

I will work on reporting this to Elegant Themes.

Thank you for the help and ideas ;)

**Comment by dynamicdriverepo** [comment]
So I'm having the exact same issue. Tried switching between two different themes from different vendors- same issue. Did you ever resolve this?

**Comment by RadoslavGeorgiev** [comment]
@dynamicdriverepo this was a client-reported issue. We found the culprit and let our client report this to Elegant Themes, but we never received a status update, so we do not even know if the bug reached Elegant themes.

**Comment by dynamicdriverepo** [comment]
Ok thanks. Strange, for me unfortunately, even switching to the default Wordpress 2019 theme has the same issue for me.

**Comment by dynamicdriverepo** [comment]
I think I found the culprit, which happened to be a plugin actually, Sassy Social Share to be exact.

For anyone running into this problem in the future, I advise to try first disabling all plugins to see if that fixes the issue.

**Comment by dbmpls** [comment]
@paddylandau make sure you checkout the new ticket here: https://github.com/WordPress/gutenberg/issues/17406 with a solution posted
