### ISSUE TITLE
Rich text toolbar bold/italic behaves differently to keyboard shortcut

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11065]
The behaviour of the rich text formatting tools is different depending if you use the toolbar or keyboard shortcuts.

If you place the caret on a word in a paragraph and press the bold button it does nothing. If you press `cmd+b` it highlights the word and makes it bold. The same occurs for italic.

**To Reproduce**
1. Create a paragraph block
2. Enter some words
3. Place the caret in a word
4. Click the bold button in the rich text toolbar, note how nothing changes
5. Press `cmd+b` and note how the word is highlight and becomes bold

Maybe related to #11062.

**Expected behavior**
I like how `cmd+b` highlights the word and would expect the toolbar button to do the same.

Additionally, placing the caret at the end of a word and before a space and then pressing `cmd+b` should highlight the previous word. Currently it highlights the space.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by iseulde** [comment]
This was normalised in #10209. Whether the current behaviour for an uncollapsed selection inside a word is right, I don't know, but it can be discussed in a separate issue. Looking at the old editor, it would make the word bold if the caret is inside the word, and insert a placeholder if the caret is at the edges of the word.
