### ISSUE TITLE
Missing spaces in editor after using repeated use of bold format shortcut key

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11062]
This is a bit of an odd one but I’ve found that repeated use of the bold format shortcut key (cmd+b) can remove spaces in the editor.

It’s probably best explained with screenshots. I’ll show the browser along with the DOM and `innerHTML` contents.

Here’s a cover image block with the text set to ‘some title’:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47506762-ac142580-d868-11e8-97bb-aa1529111201.jpg)

Placing the caret after the 'e', but before the space, and pressing `cmd+b` highlights part of the space and adds a `&#65279;` to the DOM:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47506810-cb12b780-d868-11e8-9d6d-e2b89216255c.jpg)
![devtools_-_latest_local_wp-admin_post_php_post_227_action_edit](https://user-images.githubusercontent.com/1277682/47506919-001f0a00-d869-11e8-9dd1-7f152dc18902.jpg)
`some<span id="_mce_caret" data-mce-bogus="1" data-mce-type="format-caret"><strong data-mce-selected="inline-boundary">﻿</strong></span> title`

Now place the caret in the word 'title' and press `cmd+b`. It should highlight the whole word and make it bold:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47507027-4aa08680-d869-11e8-9b0d-a042411400aa.jpg)
![devtools_-_latest_local_wp-admin_post_php_post_227_action_edit](https://user-images.githubusercontent.com/1277682/47507064-5be99300-d869-11e8-913b-a9b6fbdbb448.jpg)
`some <strong data-mce-selected="inline-boundary">title</strong>`

Now put the caret back to after the 'e' and press `cmd+b`. The space is highlighted again:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47507200-a408b580-d869-11e8-9d36-3fd36f07c277.jpg)
![devtools_-_latest_local_wp-admin_post_php_post_227_action_edit](https://user-images.githubusercontent.com/1277682/47507183-9bb07a80-d869-11e8-9a12-480d48ac9f3e.jpg)
`some<span id="_mce_caret" data-mce-bogus="1" data-mce-type="format-caret"><strong data-mce-selected="inline-boundary">﻿</strong></span> <strong>title</strong>`

Then press `cmd+b` a second time to remove the bold. Notice how the space between 'some' and 'title' has now disappeared:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47507244-c39fde00-d869-11e8-9f39-d71b0de04306.jpg)

![devtools_-_latest_local_wp-admin_post_php_post_227_action_edit](https://user-images.githubusercontent.com/1277682/47507276-d1556380-d869-11e8-9c79-8b59ea86c390.jpg)
`some<span id="_mce_caret" data-mce-bogus="1" data-mce-type="format-caret">﻿</span> <strong>title</strong>`

If you save and reload the page the text is restored with a space.

Note this doesn't happen if you click the bold toolbar button.

**Expected behavior**
Pressing `cmd+b` to bold a word makes sense.

Pressing `cmd+b` on a space to then highlight part of the space isn't expected. On Github's markdown editor doing the same makes the previous word bold.

I would also expect the `cmd+b` to behave the same as clicking the bold button

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70

Gutenberg master

**Comment by chrisvanpatten** [comment]
This is interesting — it looks like a variant of #8114 which I closed this week because I wasn't able to reproduce it.

Any chance the cover block needs some kind of RichText update to align with the recent changes? That's my only idea so far…

**Comment by johngodley** [comment]
Ah yes, that sounds like the same problem. I'll try a few other blocks and see if it's specific to the cover block.

**Comment by johngodley** [comment]
Confirmed same problem with paragraph and quote using the above steps.

**Comment by chrisvanpatten** [comment]
@johngodley I think what I might have missed in my testing this week is the formatting at the edge of the word, which makes sense why the space would be mangled — the code is trying to combine adjacent matching formats, and for some reason is missing the space in that process.

**Comment by iseulde** [comment]
@johngodley Could you update this issue for 4.2? I think some behaviours described here have changed.

**Comment by johngodley** [comment]
Yep, the behaviour has changed and the problem no longer exists. Closing this as fixed.

**Comment by iseulde** [comment]
Thanks!!

**Comment by ElYi** [comment]
I'm finding this behaviour worse than ever. If I change anything in a Block it removes a bunch of word spaces in the editor. Adding a link does it. Anything. I took to doing as much editing in word as possible. This might make things even worse when  trying to edit anything.  Am about to ditch Gutenberg entirely.
