### ISSUE TITLE
Archives block: add a CSS class when “Display as dropdown” is active.

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#11075]
**Describe the bug**
When the “Display as dropdown” option is activated on the Archives block, no CSS class is added in the block's HTML code.

**To Reproduce**
1. Insert an Archives block.
2. Activate the “Display as dropdown” option in the block's settings.
3. Inspect the element and see that there's no CSS class marking the use of the option. 

**Expected behavior**
A `wp-block-archives-dropdown` CSS class should be added when the block is in dropdown mode, like the Categories block already does (`wp-block-categories-dropdown`).

**Screenshots**

![image](https://user-images.githubusercontent.com/1451087/47518810-4ae95380-d862-11e8-8940-efa7fb689f36.png)

**Desktop:**
 - MacOS X 10.12
 - Chrome 69

**Additional context**
 - WordPress 5.0-beta1-43823
 - Twenty Seventeen.
 - No other plugins.

**Comment by pagelab** [comment]
The `wp-block-archives__dropdown` class should also be added to the `select` element, in the blocks's HTML on the block editor:

![image](https://user-images.githubusercontent.com/1451087/47521016-35772800-d868-11e8-9214-790e5d5d7bb1.png)

**Comment by Soean** [comment]
Why do you need it, if you have the class in the wrapper?

**Comment by pagelab** [comment]
There's no dropdown class in the wrapper `div` (front-end) nor in the `select` element (editor) for the Archives block, so both are needed.

Besides that, the Categories block has a dropdown class both in the front-end and in the editor. So consistency is an issue here.

**Comment by Soean** [comment]
You are right, we need to add a class to the div. Have you seen my PR #11077 which adds a wrapper class? My question was referring to this PR. If we merge this PR, why would we need to add this class also to the select element?

**Comment by pagelab** [comment]
> If we merge this PR, why would we need to add this class also to the select element?

Just in the editor. On the front-end the class is already present in the wrapper `div`, so a class in the `select` is not necessary.
