### ISSUE TITLE
Improve display of shortcode block in columns

### ISSUE THREAD

**Issue by billerickson** [WordPress/gutenberg#11079]
**Describe the bug**
The shortcode block label is floated to the left of the textarea. While this works well in larger contexts, inside the columns block this shrinks the texarea down to one character per line:

**To Reproduce**
1. Add the Columns block and set it to 3 columns
2. Add the Shortcode block to each column.

**Expected behavior**
The textarea should be larger and more usable. Float the label above the textarea and make them both full width.

**Screenshots**
<img width="660" alt="screen shot 2018-10-25 at 1 55 17 pm" src="https://user-images.githubusercontent.com/685131/47523813-90a41d00-d85e-11e8-8318-38d550c86ac5.png">

**Comment by arunsathiya** [comment]
Can reproduce this as well on Gutenberg 4.1.1 with WordPress 4.9.8 on Google Chrome Version 70.0.3538.67 (Official Build) (64-bit). macOS 10.14 - Mac OS Mojave.

## 3 shortcode blocks inside the columns block

<img width="680" alt="screenshot 2018-10-26 at 16 42 01" src="https://user-images.githubusercontent.com/18581859/47563112-53af5780-d93e-11e8-803e-8f87ce6cc74b.png">
<sup>Image indicating how the shortcode block content region is small when the shortcode label is on the left</sup> 

## On adding more text

<img width="697" alt="screenshot 2018-10-26 at 16 42 19" src="https://user-images.githubusercontent.com/18581859/47563111-53af5780-d93e-11e8-95a2-8a3d6e50daa2.png">
<sup>Another image indicating how the shortcode block content region is small when the shortcode label is on the left</sup> 

## Suggested format

I am going to take a stab at submitting a PR for this to bring it in the format shown below.

<img width="663" alt="screenshot 2018-10-26 at 16 41 26" src="https://user-images.githubusercontent.com/18581859/47563113-53af5780-d93e-11e8-8a1b-5dc462588fbf.png">
<sup>Image indicating the shortcode label at the top of the content, as opposed to being on the left</sup>

**Comment by bobbingwide** [comment]
With Gutenberg 5.5.0 I now get 
![image](https://user-images.githubusercontent.com/2474435/56493051-ac267280-64e5-11e9-913d-eb4ddf99202a.png)

This is a new problem. #15032

**Comment by ThornedRose** [comment]
I'm on Wordpress 5.2, and I still have the OP's behaviour with shortcodes (7 months after it was posted!). 

Adding `.wp-block-shortcode label { display: none; }` mostly works but as the shortcodes themselves are quite long, it still looks bizzare. Nor is this a solution to pass onto the non-profit clients I am doing this website for :(

**Comment by talldan** [comment]
This does look a bit better now:
<img width="542" alt="Screenshot 2020-02-20 at 2 03 53 pm" src="https://user-images.githubusercontent.com/677833/74905731-e7395100-53e9-11ea-9c41-28b398e7d5b4.png">

The text area is wider and is properly multiline now. But I still feel there's room for improvement, i.e. making the text area take up the full-width.

Not sure this can be labelled a bug given the original issue has been improved considerably, so I'll label it an enhancement.

**Comment by mapk** [comment]
I agree with @talldan here. The alignment issues have been resolved, but it would be good to set the textarea width to 100%.

**Currently**

![Screen Shot 2020-03-03 at 9 24 42 AM](https://user-images.githubusercontent.com/617986/75802028-e8934380-5d30-11ea-8107-907bab322654.png)

**Width at 100%**

![Screen Shot 2020-03-03 at 9 25 55 AM](https://user-images.githubusercontent.com/617986/75802095-01035e00-5d31-11ea-8249-33ded0514b65.png)
