### ISSUE TITLE
can't post automatically on facebook

### ISSUE THREAD

**Issue by BSCBBALL** [WordPress/gutenberg#11074]
hi, with the new update/gutenberg editor, I am not able to post a post on wordpress automatically on facebook as I did before. what can I do? thanks for your help! leo

**Comment by BSCBBALL** [comment]
Hey Soean, I am not sure, I think it is Jetpack. But isn't there a automatic connection possible through the settings?

**Comment by youknowriad** [comment]
Jetpack adds Publicize support for Gutenberg in its 6.8 version, let's close this issue.
