### ISSUE TITLE
Semantics of output HTML for Cover Image BLock

### ISSUE THREAD

**Issue by joedolson** [WordPress/gutenberg#11083]
The output of the cover image block is a div with a background image wrapping a paragraph containing the cover text. 

I think we need to consider whether or not this text represents a heading in usage. Visually, it functions like a heading, and I think it's likely people will use it as a heading. It should certainly be *possible* for it to be marked up as a heading. 

If this has previously been considered, I couldn't find the record of it.

**Comment by mor10** [comment]
Agree. In the particular screenshot above, the text is likely not a heading, but in other examples, including the prototype where the cover image and text were displayed at the top of a view, it would be used as a heading. There should be a way of indicating whether the text is descriptive, a quote, heading, or something else. I've already seen people use this feature for all three situations.

**Comment by mtias** [comment]
The consideration here was to allow any kind of block to be added as a nested block.

**Comment by joedolson** [comment]
Are you saying that it's possible to insert a heading block inside a cover block? 

How does that work? I've spent the last 15 minutes exploring, trying to see how I would do something like that, but I can't find anything.

**Comment by samikeijonen** [comment]
> Are you saying that it's possible to insert a heading block inside a cover block?

It's not possible (yet). Originally the text was hardcoded `h2` which was may or may not been correct heading level.

**Comment by samikeijonen** [comment]
I was thinking the same issue for the Media and Text block.

**Comment by mtias** [comment]
> Are you saying that it's possible to insert a heading block inside a cover block?

No, it was tried but was not merged: https://github.com/WordPress/gutenberg/pull/5452

Still consider it to be the right solution.

**Comment by joedolson** [comment]
That does seem like a viable solution, although it looks like it hasn't had any action in some time; is there any ongoing work on that?

**Comment by mtias** [comment]
It was reverted because the UI of nested blocks was a bit overwhelming at the time. It's much better now, but it's a significant change. It's something we can bring back in a future release.

**Comment by mapk** [comment]
This should be fixed with #13822. Now you can add nested blocks inside the Cover block.
