### ISSUE TITLE
Components: Missing Core styles in CheckboxControl

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#11089]
**Describe the bug**
When rendering the `CheckboxControl` component from the `@wordpress/components` package outside of Core, there are some styling issues caused by the lack of the Core styles.

**To Reproduce**
* Load Gutenberg without Core styles by adding the following snippet into gutenberg.php:
```php
function remove_default_stylesheets() {
  wp_deregister_style('wp-admin');
}
add_action('admin_init', 'remove_default_stylesheets');
```
* Go to the Gutenberg editor
* Check the Discussion settings on the sidebar

**Expected behavior**
As `@wordpress/components` pretends to work standalone, I expect the checkboxes to look like when the Core styles are present (see screenshots below).

**Screenshots**
With Core styles
<img width="272" alt="screen shot 2018-10-26 at 10 03 37" src="https://user-images.githubusercontent.com/1233880/47553182-acfb9480-d906-11e8-9444-145d7e18c9a8.png">

Without Core styles
<img width="275" alt="screen shot 2018-10-26 at 10 03 31" src="https://user-images.githubusercontent.com/1233880/47553193-b422a280-d906-11e8-9e86-227ee44a6b82.png">

**Additional context**
Issue found while integrating Gutenberg into Calypso (Automattic/wp-calypso#28101)

**Comment by youknowriad** [comment]
I think the screenshots are outdated but the checkboxes are still showing in a different style.

**Comment by jffng** [comment]
I tested out rendering a `CheckboxControl` component in the Gutenberg playground and applying the missing Core styles directly in the component scss: 

![Screen Recording 2019-07-09 at 02 24 PM](https://user-images.githubusercontent.com/5375500/60913422-601ddb00-a255-11e9-9262-19a1a2e3c214.gif)

However the way that checkbox inputs are styled today requires the Dashicon icon font to display its checked state. I think there are two options to achieve correct styling behavior for this component outside of wp-admin:

1. Build the `@wordpress/component` styles with the icon font (feels redundant given there's already a `Dashicon` and `Icon` component)
2. Alter the `CheckboxControl` component to accept an `Icon` or `Dashicon` component

Are there simpler approaches?

**Comment by youknowriad** [comment]
@jffng Can we replace it with the SVG instead, since @wordpress/components already contains those?

So probably something more like option 2 but built-in in the component (not a new prop or something).

**Comment by jffng** [comment]
Attempted a patch (#16551) that places a SVG component inside the label, to maintain expected behavior of the input.
