### ISSUE TITLE
Cover image rich text toolbar sporadically disappears

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11087]
This is kind of a niche bug, but if you have a cover image block followed by a gallery block, and the cover image has the extra class `alignright` set, then the cover image rich text toolbar becomes very twitchy and loses focus, disappears, and selects both blocks.

Here you can see I am clicking between the bold and italic buttons and occassionally focus is lost, the toolbar disappears, and both the blocks are highlighted. Clicking back in the text restores the toolbar and the process is repeated.

![flicker](https://user-images.githubusercontent.com/1277682/47550707-f7294980-d8f7-11e8-88d5-d07684a831a7.gif)

I haven't been able to narrow down what the trigger is, and the number of clicks change. It only happens when the extra `alignright` is added, and a gallery block follows it (I haven't tested other blocks)

1. Create a cover image block, set an image, and set a title
2. Set the custom class name for the block as `alignright`
3. Add a gallery block after, but don't add any images
4. Click on the cover block title and the rich text toolbar appears
5. Click between the bold and italic buttons and after a few clicks the toolbar disappears and the two blocks are selected

Or copy/paste this:

```html
<!-- wp:cover {"url":"http://latest.local/wp-content/uploads/2018/09/favicon.png","align":"center","id":144,"dimRatio":0,"className":"alignright"} -->
<div class="wp-block-cover aligncenter alignright" style="background-image:url(http://latest.local/wp-content/uploads/2018/09/favicon.png)"><p class="wp-block-cover-text">word</p></div>
<!-- /wp:cover -->

<!-- wp:gallery -->
<ul class="wp-block-gallery columns-0 is-cropped"></ul>
<!-- /wp:gallery -->
```
**Expected behavior**
The toolbar not to disappear.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

Gutenberg 4.1.1

**Comment by mtias** [comment]
@jasmussen I  think you looked at this before, as part of the issues with floats.

**Comment by jasmussen** [comment]
Yeah this is sort of an issue with multi-selections. Basically while you're dragging to select text inside the floated element, it is interpreted as invoking multi select. @iseulde do you have thoughts here?
