### ISSUE TITLE
Revisions button when there are no revisions

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1108]
The revisions link introduced in #910 works great when there are revisions: it's a link and points to the Revisions screen.

However, when there are no revisions:

<img width="295" alt="screen shot 2017-06-10 at 15 00 27" src="https://user-images.githubusercontent.com/1682452/27002992-cd98342c-4dee-11e7-912c-aa384a762e8a.png">

it's a button, it's focusable and actionable, but it doesn't do anything. Not completely sure abot what to do here. The ARIA Authoring Practices allow disabled controls (or, in this case, a control that doesn't do anything) to still be focusable when this helps discoverability. See https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls

On the other hand, the fact it's reported as "button" when there are no revisions, and then reported as "link" when there are revisions, could be potentially confusing.

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/1179
