### ISSUE TITLE
Documentation on columns

### ISSUE THREAD

**Issue by boutzamat** [WordPress/gutenberg#11097]
Hi. 

Is there any documentation on how to make blocks that can contain blocks? For example create a custom "column" block?

**Comment by jankimoradiya** [comment]
Hi @boutzamat,

Gutenberg is already provide "Column Beta" block for column structure in a page. 

Can you please give an example what type of custom block you want to create?

**Comment by boutzamat** [comment]
> Hi @boutzamat,
> 
> Gutenberg is already provide "Column Beta" block for column structure in a page.
> 
> Can you please give an example what type of custom block you want to create?

Hello.

Yes it does. But i am looking to build a Bootstrap version of columns, so each column can have its own attributes (width, class etc.)

So basically, i would use the column block as a template for my bootstrap addon plugin for Gutenberg.

**Comment by boutzamat** [comment]
> @boutzamat Have you seen the InnerBlocks component?
> https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks

Nope, i have not. I will check it out. Thanks :)

**Comment by designsimply** [comment]
Thanks for linking to the documentation @Soean !

@boutzamat if you're looking for custom code help after reviewing the documentation, please post at https://wordpress.org/support/plugin/gutenberg/

**Comment by chrisvanpatten** [comment]
@boutzamat You're also welcome to look at our custom columns block. It uses classes for the Gridlex framework but could be updated for Bootstrap: https://github.com/tomodomoco/gutenberg-block-columns

**Comment by designsimply** [comment]
Found out a little more. Templates will allow to bootstrap a block with some attributes already set so it may solve this problem for you (note that the columns block doesn't have a width attribute), see https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks#template
