### ISSUE TITLE
Link popover moves sideways following the caret

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#11092]
**Describe the bug**
The link popover moves horizontally with the caret.

**To Reproduce**
1. Add a link to a paragraph (with some reasonably long text)
2. Use the left and right cursor keys to move the caret within the link text
3. Observe that the popover moves from left to right, following the caret

**Expected behavior**
The popover should be positioned at the middle bottom of the formatted text

**Screenshots**
![sideways-move](https://user-images.githubusercontent.com/677833/47554605-409b8800-d93c-11e8-9577-278ef024caef.gif)
**Additional context**
- 4.1
- The desired behaviour was discussed on this issue -https://github.com/WordPress/gutenberg/issues/8266#issuecomment-431301854
- Fixing related issue #11091 could help with this (as it would be possible to use the inline boundary to position the popover)

**Comment by mtias** [comment]
This is a regression, it was fixed before.
