### ISSUE TITLE
Improve the UI to edit the gallery block

### ISSUE THREAD

**Issue by jaclyntan** [WordPress/gutenberg#11094]
Hello. I've been using the gallery block for one of my projects and I find the UI very unintuitive. The controls for the block is spread across at least three (or more?!) different component areas on the page which makes editing it really convoluted and confusing, so much so I had to google how to edit the gallery block and also how to edit the columns. 
![screen shot 2018-10-26 at 4 46 01 pm](https://user-images.githubusercontent.com/18632934/47555833-6e360080-d93f-11e8-866d-f0c40c5f0d42.png)

I feel like there should at least be a "Edit Gallery" button next to the Upload an image button on the gallery block, but also would loveto see a reiterated version of this block with less areas to have to sift through.  I'm not sure how feasible it is to chop and change the UI now though, since it seems like these different areas have their own concepts and contexts going on.

**Comment by karmatosed** [comment]
Thanks for reporting this. I agree we can and should increase discoverability of how you edit a gallery. I am not sure I agree that it should be right beside the upload. This would be something worth exploring so going to mark as 'needs design' and milestone to 5.0.2 for now.

**Comment by simison** [comment]
>I am not sure I agree that it should be right beside the upload.

Noting that https://github.com/WordPress/gutenberg/pull/12367 is relevant here.

**Comment by mapk** [comment]
Because this is really about the general UI of Gutenberg and doesn't include any immediate tasks, I'm going to close this. If anyone feels differently, let's open an issue with specific tasks.
