### ISSUE TITLE
Existing tags sometimes missing in the sidebar 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1110]
To reproduce:
- open in Gutenberg an existing post that's already using some tags
- open the sidebar and open the Categories & Tags 
- depending on the cases, some tags may appear correctly, others not

<img width="301" alt="screen shot 2017-06-10 at 15 17 31" src="https://user-images.githubusercontent.com/1682452/27003089-de7811ac-4df0-11e7-982e-0675f6361c95.png">

I get this warning in the console:
Encountered two children with the same key, `token-`. Child keys must be unique; when two children share a key, only the first child will be used.

In my case, the tags are:
`alignment, captions, content, css, image, markup`
and their slugs are:
`alignment-2, captions-2, content-2, css, image, markup-2`

**Comment by youknowriad** [comment]
Does's this PR solve this issue #1093?

**Comment by jasmussen** [comment]
This seems to be an issue also for categories.

**Comment by youknowriad** [comment]
Can't recall which PR but this is fixed for me

**Comment by afercia** [comment]
@youknowriad maybe #1490 ?

I see the PR mentioned an issue that, as far as I know, is still to address: "For the categories selector, we'd have to rewrite completely (maybe with virtual scroll, something like Calypso) to load paginated categories". Don't think there's an issue about that, do you want me to create one?
