### ISSUE TITLE
Disappearing drop cap causes jumpy behaviour

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11119]
When switching between editing and writing a paragraph with a drop cap, the drop cap disappears and reappears. This makes things jump around awkwardly:

![2018-10-26 15 17 06](https://user-images.githubusercontent.com/376315/47572189-4d1ae300-d932-11e8-9f96-33d81ee79d07.gif)

When duplicating a block with a drop cap especially, it feels as though it hasn't duplicated properly:

![2018-10-26 15 17 24](https://user-images.githubusercontent.com/376315/47572190-4d1ae300-d932-11e8-9f28-33512074bbc9.gif)

The end result is, as a new user, feeling that something has gone wrong, or the drop cap has disappeared. I'm assuming that this was an intentional design decision, to make it easier to edit the text, but it might be a worthwhile improvement to see if we can avoid the jumpiness—perhaps by leaving a placeholder space or a slightly greyed-out version of the drop cap to show that it's still there, whilst still allowing the first letter to remain clearly part of the main text for editing purposes?

**Comment by iseulde** [comment]
This is a limitation we have with browsers. We cannot leave the drop cap while the user is editing text. See https://github.com/WordPress/gutenberg/pull/1189#discussion_r122184815.
