### ISSUE TITLE
Toolbars overlap for aligned button block

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#1111]
<img width="334" alt="screenshot 2017-06-10 15 23 58" src="https://user-images.githubusercontent.com/4710635/27003119-2cc98fa2-4df1-11e7-8b8e-98ae5f9a974c.png">

**Comment by georgeolaru** [comment]
That seems to be already reported and it's a work in progress until the #1168 issue is closed.

**Comment by jasmussen** [comment]
I agree especially with the link dialog. We might want to rethink that. Perhaps a separate link button at the block level, just like we have an edit button for images?

With regards to the inline toolbar —  what if we showed that one only when you click the input field, and hide the block level ones when you do that?
