### ISSUE TITLE
Still seeing Gutenberg after deactivating it, because of Gutenberg Ramp

### ISSUE THREAD

**Issue by daveloodts** [WordPress/gutenberg#11118]
I disable Gutenberg and i'm still able the make posts and pages in Gutenberg style.
The reason is that the plugin Gutenberg Ramp probably forget to check if Gutenberg is active, it overrules that.
Don't know if this is an issue, but probably no normal expected behavouir.

**Comment by youknowriad** [comment]
How did you disable Gutenberg? if it comes from Gutenberg Ramp, it's probably better to check with them directly?

**Comment by designsimply** [comment]
Would you mind also listing which versions of things (WP and Ramp) you are using at the moment?
