### ISSUE TITLE
Format API: where to put new toolbar buttons?

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#11114]
Currently we only fill in toolbar buttons with the names `bold`, `italic`, `link` and `strikethrough`. This is only meant to be a temporary solution to ensure that the core buttons are displayed first and ordered correctly.

https://github.com/WordPress/gutenberg/blob/25bc46a9135cbeb805fefa3325382d01ce4bd938/packages/editor/src/components/rich-text/index.js#L926

https://github.com/WordPress/gutenberg/blob/25bc46a9135cbeb805fefa3325382d01ce4bd938/packages/editor/src/components/rich-text/format-toolbar/index.js#L9-L15

This results in toolbar buttons rendered by plugins not being displayed.

Possible solutions:

* We add a filter to the array of format strings, allowing the plugin author to add their toolbar button to the toolbar. It also allows other plugins to change the order of buttons.

Pro: high configurability for any party.
Con: toolbar may get overcrowded, and aside from rendering the button, you also need to add a filter to make it appear in the toolbar.

* We just push any non core button to the end of the toolbar.

Pro: core buttons will always keep their place and order.
Cons: toolbar may get overcrowded, cannot change order of plugin buttons

Unsure why we would want this tbh.

* We see the toolbar as a "sacred" place for easy access to format buttons, and have the core ones there as a default. New buttons appear in the inspector. If the user chooses, they could move the button to the main toolbar (if they use it a lot).

Pros: main toolbar cannot get overcrowded, high configurability for the user.
Cons: ?

Any other solutions?

**Comment by iseulde** [comment]
Cc @jasmussen for thoughts.

**Comment by jasmussen** [comment]
Good ticket, thanks for the ping.

> We just push any non core button to the end of the toolbar.

and

> We see the toolbar as a "sacred" place for easy access to format buttons, and have the core ones there as a default. New buttons appear in the inspector. If the user chooses, they could move the button to the main toolbar (if they use it a lot).

These seem slightly related.

As you note, the big challenge here is ensuring this works on mobile. We have made a few strides here insofar as _toolbar segments_ like text align can collapse on mobile. But this is not yet a bulletproof solution, as we have very few smarts associated with this. But based on this, and your ideas suggested above, could the following work?

> If a plugin adds a single button to the text formatting toolbar, it shows up in a new segment to the right of the core inline formatting tools. I.e. `[Inline tools] [Plugin button]`
> If a plugin adds more than a single button, or multiple plugins add buttons, this extra segment is collapsed into a dropdown. I..e `[Inline tools] [More icon ▼]`

The collapsing would leverage Riads new mechanism for collapsing segments.

**Comment by jasmussen** [comment]
I would suggest that it would not be _two_ additional segments, just a single one. If that single plugin added segment contains both block and inline level tools, then that'd be... well not fine, but better than two segments.
