### ISSUE TITLE
Local dev environment - Use unminified version of react

### ISSUE THREAD

**Issue by mrmadhat** [WordPress/gutenberg#11126]
**Is your feature request related to a problem? Please describe.**
When running the local development environment via `./bin/setup-local-env.sh` wordpress uses the minified version of react so errors display the following 

"Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Describe the solution you'd like**
When using the local dev environment it should use the unminified version of React

**Comment by nerrad** [comment]
I can confirm that with `SCRIPT_DEBUG` set to true all the scripts in `wp-includes/script-loader.php::wp_default_packages_vendor` are not concatenated but are loading `*.min` (in WP 5.0b3).  It looks like `wp_scripts_get_suffix( 'dev' );` ends up always returning the `.min` suffix.

**Comment by nerrad** [comment]
Looks to be related maybe? https://core.trac.wordpress.org/ticket/45156

**Comment by mrmadhat** [comment]
I'm not sure if it is related, if you install the Gutenberg plugin on a normal wp install the non minified version is available.

Here's an example where I've used `import` incorrectly on a site running using vvv that shows the correct errors:

![image](https://user-images.githubusercontent.com/19492281/48122565-c3dba880-e26f-11e8-83de-0f90f062eb3c.png)

**Comment by nerrad** [comment]
Things are working okay for me against 5.0.3 now.

**Comment by gziolo** [comment]
This means we can close this one, thanks for checking @nerrad 🙇
