### ISSUE TITLE
CSV Table Import

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#11121]
Would it be possible to add CSV tables to the Gutenberg table? Or any other way to convert existing tables into blocks faster?

**Comment by Soean** [comment]
You can paste from different sources, see https://github.com/WordPress/gutenberg/blob/81d5569428ef12a01adb352e2461ba0ace4b6a5e/packages/blocks/src/api/raw-handling/readme.md

**Comment by designsimply** [comment]
Tables as in the table block? (If not, I mislabeled then unmislabeled earlier—sorry about that!)

Could you add some testing steps that will help illustrate how converting existing tables into blocks is slow?

**Comment by SchneiderSam** [comment]
Everything's fine, it's working perfectly. Awesome!
