### ISSUE TITLE
Missing translation strings code on script in function gutenberg_replace_default_add_new_button file gutenberg.php

### ISSUE THREAD

**Issue by luciano-croce** [WordPress/gutenberg#11120]
**Describe the bug** -- _Updated 2018-10-28_

_The behavior description:_
- **Missing** the **translation string code**, in script of function "gutenberg_replace_default_add_new_button" in file gutenberg.php:461.
- The **translation strings code**, in script of function "gutenberg_replace_default_add_new_button" in file gutenberg.php:312 and gutenberg.php:462 are **shared**.

> This **Bug** _and this patch (for now)_ are **related to Gutenberg Plugin** and **not to WordPress** because the code in question has not yet been imported in core.

**To Reproduce**

_Steps to reproduce the behavior:_
- The **string "Gutenberg"** in file gutenberg.php:461 is **not translatable**.
- The **strings** gutenberg.php:312 and gutenberg.php:462 **share same translation**, **but** in most cases **is preferable separate translations**.

**Expected behavior**

_Steps to fix the behavior:_
- **Add missed translation code string** `<?php echo esc_js( __( 'Gutenberg', 'gutenberg' ) ); ?>` on script in function gutenberg_replace_default_add_new_button file gutenberg.php:461
- **Separate translation of shared strings** on script in function gutenberg_replace_default_add_new_button file gutenberg.php:312 and gutenberg.php:462

**Screenshots**

- https://github.com/luciano-croce/gutenberg-translation-patch/blob/master/screenshot-1.png
- https://github.com/luciano-croce/gutenberg-translation-patch/blob/master/screenshot-2.png
- https://github.com/luciano-croce/gutenberg-translation-patch/blob/master/screenshot-3.png
- https://github.com/luciano-croce/gutenberg-translation-patch/blob/master/screenshot-4.png

> The menu shown in the screenshots is added by the Gutenberg Plugin and not by the WordPress Core.

**Additional context**
- My **patch as plugin** https://github.com/luciano-croce/gutenberg-translation-patch/
- Gutenberg 4.1.1
- WordPress 5.0-beta1

> The **patch** is **translated in 28 languages** and more **others 11 in becoming** (help me in your lang).

**Desktop (please complete the following information):**
 - OS: [All]
 - Browser [All]
 - Version [All]

**Smartphone (please complete the following information):**
 - Device: [All]
 - OS: [All]
 - Browser [All]
 - Version [All]

**Comment by designsimply** [comment]
Adding the screenshots from above inline for easy access and viewing: 

![screenshot-1](https://user-images.githubusercontent.com/1119271/47584262-053a9280-d917-11e8-9ff8-867ee7748f20.png)

![screenshot-2](https://user-images.githubusercontent.com/1119271/47584266-08ce1980-d917-11e8-84ed-f996d0e54198.png)

![screenshot-3](https://user-images.githubusercontent.com/1119271/47584269-0bc90a00-d917-11e8-8b4f-34b7f332c834.png)

![screenshot-4](https://user-images.githubusercontent.com/1119271/47584272-0e2b6400-d917-11e8-9d57-20b51a2b2ba8.png)

**Comment by designsimply** [comment]
Thanks for reporting this!

Added the `Needs Testing` label and noting that this issue probably should move to https://core.trac.wordpress.org/ because those are screenshots of the Posts page and not of Gutenberg directly.

**Comment by luciano-croce** [comment]
@designsimply

It's just the opposite: are Gutenberg screenshots and not of the WordPress core. The patch is for a script of gutenberg.php file not present on core of EP 4.9+ and 5.0+

Thanks!

**Comment by swissspidy** [comment]
> Add missed translation code string

Agreed, "Gutenberg" is not translatable there. Instead of "Gutenberg" I'd use "Block Editor" though.

> Separate translation of shared strings

We could add a context there, but I'm not sure if it's really needed. And "Classic Edit" doesn't sound that well IMHO.

**Comment by luciano-croce** [comment]
Hi @swissspidy 

The strings gutenberg.php:312 and gutenberg.php:462 share same translation but the context is not the same.

The most common translation of this string, I have valuated 23 languages is Classic Editor, but is not appropriate.

gutenberg.php:312 -> in Add Menu -> Classic Editor OK

gutenberg.php:462 -> as Edit Action Link -> Classic Editor NOT OK - Instead is more appropriate Classic Edit

Read all the details that I explained better on my GitHub https://github.com/luciano-croce/gutenberg-translation-patch/blob/master/README.md

By.

**Comment by ocean90** [comment]
Thanks for raising this issue. I'm going to close this as _wontfix_ though:

* Gutenberg is only codename which doesn't need to be translatable.
* The string `Classic Editor` in those two places is fine as they are about the same editor/context, both are opening the previous editor.

There's also no core ticket needed as the dropdown doesn't exist in core. It's currently only part of the plugin and will probably be removed soon-ish.

**Comment by luciano-croce** [comment]
Hi @ocean90 

Thanks for the review and the informations.
This patch is written with the intent of being helpful.

Thanks!

**Comment by luciano-croce** [comment]
WordPress 5.0-beta5

Gutenberg (codename) is official the new Block Editor of WordPress

> Block Editor
> 
> The block editor has been updated to match the Gutenberg 4.4+ release,

Read more here: https://wordpress.org/news/2018/11/wordpress-5-0-beta-5/

P.S. I think (with a lot of humility) that the translation imported in core of WordPress as Gutenberg is inconsistent!
