### ISSUE TITLE
Refactor the effects into async actions with controls

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#11124]
Now that we have controls and actions as generators, we should refactor all of our current effects to use this pattern instead.

A small technical requirement to make it possible is the possibility to pass the "registry" object to the controls.

**Comment by paaljoachim** [comment]
Is this issue still relevant @youknowriad ?

**Comment by youknowriad** [comment]
Actually, we've refactored all of these now. So we should be good, there's some remaining cleanup that I'll take care of.
