### ISSUE TITLE
Safari: Caret invisible when RichText field is empty.

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#11125]
**Describe the bug**

In Safari, the blinking caret becomes invisible whenever an empty RichText component is focused. The screencast below shows the example of pressing Enter to start a new Paragraph, but this affects other blocks (e.g. Quote), and the issue is also present when starting in a Paragraph with content and pressing <kbd>backspace</kbd> to delete all its contents.

**Screenshots**

![safari-missing-caret](https://user-images.githubusercontent.com/150562/47579169-2618dd00-d943-11e8-84ff-abafac1f1328.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**
- Firefox and Chrome not affected.

**Comment by arunsathiya** [comment]
From what I see at my end on Safari, I see the caret appear just fine on a fresh `paragraph` block, on using `Enter` key. 

The same is the case when I erase the full content on a `paragraph` block using the `Backspace` key (I am erasing the content either by selecting in full/using `Shift`+`Backspace`). [A video indicating this behaviour](https://cloudup.com/cJzrRtRMljU).

Tested on Safari for macOS 10.14 - Mac OS Mojave. Gutenberg 4.1.1 using WordPress 4.9.8.

**Comment by mcsf** [comment]
@arunsathiya, have you checked in `master`? I'm at a54896121a115ad143fd9b6ac331ca8eedf212af

**Comment by arunsathiya** [comment]
@mcsf My bad, I didn't realise this was in `master`. I am able to reproduce the error as well. 👍🏽:)

**Comment by iseulde** [comment]
@mcsf Untested, but this might be 249cc3b71c2165c5f373ed26eda5b1dafc87ceff.

**Comment by iseulde** [comment]
Confirmed.

**Comment by iseulde** [comment]
Cc @jasmussen

**Comment by mcsf** [comment]
Thanks for the quick response!
