### ISSUE TITLE
Embeds inside alignfull/alignwide

### ISSUE THREAD

**Issue by tomusborne** [WordPress/gutenberg#11139]
If an embed (YouTube for example) is inside a block set to `alignwide` or `alignfull`, it doesn't span the entire width.

Typically, I would say this is a theme issue. However, Gutenberg adds this CSS for images by default:

    .wp-block-image.alignfull img, 
    .wp-block-image.alignwide img {
        width: 100%;
    }

So I figured it could just be changed to:

    .wp-block-image.alignfull img, 
    .wp-block-image.alignwide img,
    .wp-block-embed.alignfull iframe,
    .wp-block-embed.alignwide iframe {
        width: 100%;
    }

It may be something better suited inside themes themselves, but thought I'd bring it up.

**Comment by youknowriad** [comment]
I just tested with the twentynineteen theme, it works well for me. Maybe a theme related issue?
