### ISSUE TITLE
Use of custom InspectorControls settings when block is rendered on frontend

### ISSUE THREAD

**Issue by atulshrma91** [WordPress/gutenberg#11142]
Blocks are modified using `editor.BlockEdit` filter in order to add settings  in InspectorControls side panel. These settings are used to hide or show block according to user category.

`blocks.getBlockAttributes`  allow me to get the values i saved with the block but it is doesn't effect the rendering of the block

Can you please tell me which hook/filter we use to get the settings we saved when block is rendered on frontend. 

<img width="1098" alt="screen shot 2018-10-27 at 11 47 31 am" src="https://user-images.githubusercontent.com/17331167/47600407-37fb8e00-d9de-11e8-812a-76f649016aea.png">
<img width="1060" alt="screen shot 2018-10-27 at 11 48 04 am" src="https://user-images.githubusercontent.com/17331167/47600409-434eb980-d9de-11e8-9bb8-9b1d8e379d61.png">

**Comment by atulshrma91** [comment]
we can get gutenberg block and attributes values saved on frontend by using wp filter "the_content"

**Comment by designsimply** [comment]
@atulshrma91 do you still need help with this? Your latest reply seems to answer the original question.

**Comment by atulshrma91** [comment]
Thank you for the follow up.  "the_content" filter solved the issue.
