### ISSUE TITLE
Building fails on Windows

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#11144]
This has been happening for a while, error messages:
```
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! gutenberg@4.1.0 mobile-submodule-update: `git submodule update --init --recursive`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the gutenberg@4.1.0 mobile-submodule-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!    [...]\AppData\Roaming\npm-cache\_logs\2018-10-27T09_52_58_906Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! gutenberg@4.1.0 preinstall: `npm run mobile-submodule-update`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the gutenberg@4.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

It is triggered by these two lines in package.json:
```
"preinstall": "npm run mobile-submodule-update",
"postinstall": " npm run mobile-install && npm run check-licenses && npm run build:packages",
```
Removing them allows `npm install` to finish successfully. 

The problem now is worse as Gutenberg gets build every time WP gets build, and Gutenberg's `package.json` is freshly downloaded from Github (there is no chance to remove the above lines). 

I'm not sure if the `mobile` submodule is meant to be built or to be run on Windows (Gutenberg seems to be working properly without it), but this currently prevents building of WP 5.0.

**Comment by afercia** [comment]
Related: https://github.com/WordPress/gutenberg/issues/10172 😬

**Comment by karmatosed** [comment]
I also get this or something similar in mac which means I can't run npm install right now. Interestingly I am getting this despite having 4 times now deleted and got a fresh copy from the repo, so there are no changes (see error). I also ran git to see if had any local and didn't.

`
> gutenberg@4.2.0-rc.1 preinstall /Users/tammielister/.Trash/gutenberg
> npm run mobile-submodule-update


> gutenberg@4.2.0-rc.1 mobile-submodule-update /Users/tammielister/.Trash/gutenberg
> git submodule update --init --recursive

error: Your local changes to the following files would be overwritten by checkout:
	block-library/freeform/index.js
	block-library/html/index.js
	gutenberg.php
	packages/block-library/src/audio/index.js
	packages/block-library/src/button/index.js
	packages/block-library/src/categories/index.js
	packages/block-library/src/code/index.js
	packages/block-library/src/cover-image/index.js
	packages/block-library/src/file/index.js
	packages/block-library/src/gallery/index.js
	packages/block-library/src/heading/index.js
	packages/block-library/src/image/index.js
	packages/block-library/src/list/index.js
	packages/block-library/src/more/index.js
	packages/block-library/src/paragraph/index.js
	packages/block-library/src/preformatted/index.js
	packages/block-library/src/pullquote/index.js
	packages/block-library/src/quote/index.js
	packages/block-library/src/spacer/index.js
	packages/block-library/src/verse/index.js
	packages/block-library/src/video/index.js
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'ade4815308263449ac50e78d83818f8afbac0bc5' in submodule path 'gutenberg-mobile/gutenberg'
Failed to recurse into submodule path 'gutenberg-mobile'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@4.2.0-rc.1 mobile-submodule-update: `git submodule update --init --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gutenberg@4.2.0-rc.1 mobile-submodule-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tammielister/.npm/_logs/2018-10-31T13_14_32_418Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@4.2.0-rc.1 preinstall: `npm run mobile-submodule-update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gutenberg@4.2.0-rc.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tammielister/.npm/_logs/2018-10-31T13_14_32_438Z-debug.log`

**Comment by gziolo** [comment]
There is no git submodule anymore. This issue can be closed.
