### ISSUE TITLE
Meta box not displaying anymore.

### ISSUE THREAD

**Issue by plainviewp1206** [WordPress/gutenberg#11143]
**Describe the bug**
My plugin's meta box no longer appears in GB. It used to, several months ago, but not anymore.

**To Reproduce**
Install Broadcast (https://wordpress.org/plugins/threewp-broadcast/) on a multisite.
Edit a post or page.

**Expected behavior**
The Broadcast meta box should appear in the sidebar as usual.
It appears gladly in the normal editor without problems.

**Additional context**
5.0-beta1-43823.

I tested Broadcast together with GB _many_ months ago and the meta box appeared without problems.

Have you guys changed anything that requires me to make changes to my meta box registration code?
From what I've gathered looking at the code, GB does not call the **add_meta_boxes** action. That's where I add the meta box for the post type:

`add_meta_box(`
	`'threewp_broadcast',`
	`// Meta box title`
	`__( 'Broadcast', 'threewp-broadcast' ),`
	`[ $this, 'threewp_broadcast_add_meta_box' ],`
	`$post_type,`
	`'side',`
	`'low'`
`);`

I’ve read https://wordpress.org/gutenberg/handbook/extensibility/meta-box/ and it didn’t tell me anything other than how to disable GB.

I also created a support request for this bug: https://wordpress.org/support/topic/how-to-enable-meta-boxes

**Comment by youknowriad** [comment]
Thanks for the report, this is bug in the beta1, it's tracked here https://core.trac.wordpress.org/ticket/45172

**Comment by masterdam79** [comment]
Even though https://core.trac.wordpress.org/ticket/45172 seems fixed, this is not working for broadcast with the newest MSWP+Broadcast plugin, also not after a reload after publishing..
