### ISSUE TITLE
Expose the blocks navigation menu keyboard shortcut

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#11150]
Splitting this out from #10545 see #5694 

The new "blocks navigation menu" button in the top bar should visually expose the associated keyboard shortcut (on mac OS it's `Control Option o`) in its tooltip for better discoverability...

<img width="291" alt="screen shot 2018-10-27 at 14 40 32" src="https://user-images.githubusercontent.com/1682452/47604230-b95f1a80-d9f6-11e8-871e-5ca1b43fb384.png">

...in the same way other keyboard shortcuts are already exposed in the tooltips, e.g.:

<img width="271" alt="screen shot 2018-10-27 at 14 40 28" src="https://user-images.githubusercontent.com/1682452/47604234-cb40bd80-d9f6-11e8-9e53-231c0c12e331.png">

<img width="379" alt="screen shot 2018-10-27 at 14 56 44" src="https://user-images.githubusercontent.com/1682452/47604335-96ce0100-d9f8-11e8-8c5d-101e958ca9c2.png">

/Cc @tofumatt

**Comment by tofumatt** [comment]
Agreed; this would be an easy win for WordPress 5.0. 👍
