### ISSUE TITLE
Dismissible notices: text overlaps the “dismiss” icon (x) on mobile view.

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#11156]
**Describe the bug**
The text from dismissible notices overlaps the “dismiss” icon when seen on mobile.

**To Reproduce**
1. Publish a new post using the block editor to trigger a dismissible notice.
2. Inspect the notice and add more text to it.
3. Resize the window to see the text overlaping the “x” icon.

**Expected behavior**
The notice's text shouldn't overlap the “x” icon.

**Screenshots**

![screen-recording-2018-10-23-15-18-17](https://user-images.githubusercontent.com/1451087/47607998-d77c4900-d9fd-11e8-8b70-329095464fa4.gif)

**Solution**
Change the `.components-notice.is-dismissible` specificity to overwrite the `.edit-post-layout .components-notice-list .components-notice` right padding.

![screen-recording-2018-10-27-15-19-07](https://user-images.githubusercontent.com/1451087/47608006-f5e24480-d9fd-11e8-9119-21cb06895095.gif)

**Desktop:**
 - MacOS X 10.12
 - Chrome 69

**Additional context**
 - Gutenberg 4.1.1
 - WordPress 5.0-beta1-43832
 - Twenty Seventeen.
 - No other plugins.

**Comment by ianbelanger79** [comment]
This issue was fixed before the 4.2 release

**Comment by swissspidy** [comment]
Re-opening because #11823 is still open and I am still experiencing this WordPress 5.0 RC:

<img width="1241" alt="screenshot 2018-11-29 at 16 57 17" src="https://user-images.githubusercontent.com/841956/49234311-197f1d00-f3f8-11e8-9298-2ba02c785210.png">

**Comment by gziolo** [comment]
Fixed by @Naerriel in #13371.
