### ISSUE TITLE
In a post, "update" button is not reset after update is done

### ISSUE THREAD

**Issue by welsungen** [WordPress/gutenberg#11151]
**Describe the bug**
When you edit a post and you want to "update" it, the update works but after it worked, the button remains "updating" and it's impossible to update yor post again, you're forced to reload the entire page. The extension (like yoast) present on your post get blocked and no update is done.

**To Reproduce**
1. Go to any post
2. Click on "update" or "save" (french : "mise à jour")

![update](https://user-images.githubusercontent.com/44526159/47604749-1b6f4e00-d9fe-11e8-9886-b7895e4b5d09.JPG)

**Comment by danielbachhuber** [comment]
Hi @welsungen,

Thanks for the report. If you disable Yoast SEO, does the problem still occur? And, generally, can you perform the troubleshooting step of disabling each plugin on your site one by one to see if the problem might be caused by one of them?

**Comment by welsungen** [comment]
That's what I've done. Disabling Yoast didn't solve the issue

**Comment by danielbachhuber** [comment]
@welsungen Have you disabled the other plugins you're running to see if one of them may be impacting usage?

**Comment by welsungen** [comment]
Or seems now that the problem is fixed > after I updated Yoast, no more bug

**Comment by danielbachhuber** [comment]
Glad it's sorted out!
