### ISSUE TITLE
Backspacing from first block moves cursor to weird nothing block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11167]
**Describe the bug**
See Title

**To Reproduce**
1. Make a post with at least two blocks and nothing in the first block.
1. Backspace from first block
1. First block is deleted. Cursor moves to weird location between title and first block. Typing has no effect outside of TAB key.

**Expected behavior**
Backspace does nothing.

**Screenshots**

![backspace-into-nothingness](https://user-images.githubusercontent.com/1238696/47610203-56748000-da04-11e8-8951-29f2574b85a6.gif)

**Desktop (please complete the following information):**
 - Win 10
 - Firefox 63
 - WordPress 5.0-beta1-43823, Twenty Nineteen, no plugins

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by dbullock** [comment]
Im able to reproduce this using Firefox .. Gutenberg Version 4.1.1 .. and WP 5.0-beta1-43832

**Comment by Smith-erin** [comment]
I could not reproduce this bug, using: 
OSX 10.14, 
Chrome 69, 
WordPress 5.0-beta1-43832, Twenty Nineteen, no plugins
(used Fn+delete to replicate backspace.

**Comment by iseulde** [comment]
Duplicate of #9400.
