### ISSUE TITLE
core/paragraph loses focus after modification with blocks.getSaveElement-filter while auto-save

### ISSUE THREAD

**Issue by examizer** [WordPress/gutenberg#11166]
**Describe the bug**
core/paragraph loses focus after modification with blocks.getSaveElement-filter. Occurs when post is automatically saved. After this first save I can only enter one single character in the paragraph block and then the focus is lost again.

**To Reproduce**
Use WordPress 4.9.8, Gutenberg Version 4.1.1
Create plugin:
```
wp.hooks.addFilter(
        'blocks.getSaveElement',
        'slug/do-some-stuff', DoSomeStuff);

function DoSomeStuff(element, blockType, attributes) {
    if (blockType.name === 'core/paragraph') {
        var OldEditFunction = blockType.edit;
        blockType.edit = function (props) {
          return el(OldEditFunction, Object.assign(props, {key: 'original'}));
        }
    }
    return element;
}
```

Create new post. Type some text. Wait for auto save of post.

Also does not work when changing
`return el(OldEditFunction, Object.assign(props, {key: 'original'}));`
to
`return OldEditFunction(props);`

This does not occur while changing the save function with the same method above.

**Expected behavior**
Keep focus on paragraph object after custom modification.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 69.0.3497.100 (Offizieller Build) (64-Bit)

**Comment by youknowriad** [comment]
There's an error in the code above, your use the "edit" function in the "save" filter. I think it's probably related.
