### ISSUE TITLE
First two keystrokes not captured by editor following bullet shortcut in first block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11164]
**Describe the bug**
At least in Firefox, when using the list bullet shortcut (- + `SPACE`) in the 1st block/paragraph, the next two keystrokes are ignored.

**To Reproduce**

1. Make a bulleted list using the typed "shortcut" of a hyphen and space.
1. Next two characters are not captured by editor.

In the example below, I type:
- -`SPACE`List
- -`SPACE`list

Result is:

- ist <= "`SHIFT`L" ignored
- st <= "li" ignored

**Expected behavior**
The editor reflects the words I type...

**Screenshots**

![missing-keystrokes](https://user-images.githubusercontent.com/1238696/47610063-f16b5b00-da00-11e8-9289-6da0e1ad1d96.gif)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Firefox 63
- WordPress 5.0-beta1-43823, Twenty Nineteen, no plugins

**Comment by ideadude** [comment]
**I could not recreate this in Chrome.**

* OS: Mac OSX 10.13.6
* Browser: Chrome 69.0.3497.100
* WordPress  5.0-beta1-43832, Gutenberg 4.1.1 from wp.org, Twenty Nineteen, no plugins

**Comment by ideadude** [comment]
I was able to recreate in Firefox version 61.0.2

Note: It only happened for me when I was trying this on a completely empty post, i.e. the first block.

If I had other blocks above or below, it did not happen.

**Comment by earnjam** [comment]
This is still occurring on WordPress beta 3, but it seems to be resolved in Gutenberg `master` now, so I'm going to close. 

But in a related note, it does appear that #3033 has been reintroduced.
