### ISSUE TITLE
Javascript blocking error in post edit page

### ISSUE THREAD

**Issue by monguz-it** [WordPress/gutenberg#11171]
**Describe the bug**
In post listing page (/wp-admin/edit.php) I have a non-blocking Javascript error.
In post edit page (/wp-admin/post.php) I see a white page even if HTML is present and I have many blocking Javascript errors.

**To Reproduce**
1. Go to 'All posts' page
2. Click on 'Add new' on the left or on top, or 'Edit' for a post

**Expected behavior**
Post new/edit page is blank.

**Screenshots**
List page detail
![error list](https://user-images.githubusercontent.com/15815197/47614874-3518a000-daa7-11e8-91c3-bfb477f3b256.png)
New/edit page
![error edit](https://user-images.githubusercontent.com/15815197/47614878-39dd5400-daa7-11e8-8114-b23dbf86f5d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser Chrome
 - Version 70.0.3538.77

**Additional context**
- I am using Wordpress in Italian 
- Maybe the problem started when I uninstalled Yoast SEO
- The problem occurs also disabling Wordpress plugins and Chrome extensions

**Comment by danielbachhuber** [comment]
Hi @monguz-it,

It appears the source of the error is this `defer` statement in the middle of your script tag:

![image](https://user-images.githubusercontent.com/36432/47717386-d9fbc000-dc02-11e8-83c3-e44499584833.png)

The `defer` statement is not present in the Gutenberg source code, so it's likely some third-party system that's adding it. I'd recommend reviewing the settings for any caching plugins or CDN systems (e.g. CloudFlare) you might be using.

**Comment by monguz-it** [comment]
Hi @danielbachhuber 
thank you for hinting me.
I had added this code in my functions.php
```
function defer_parsing_of_js ( $url ) {
	if ( FALSE === strpos( $url, '.js' ) ) return $url;
	if ( strpos( $url, 'jquery.js' ) ) return $url;
	return "$url' defer ";
}
add_filter( 'clean_url', 'defer_parsing_of_js', 11, 1 );
```
Thanks again

**Comment by danielbachhuber** [comment]
Glad you got it sorted out :)
