### ISSUE TITLE
Cursor positioning lost after pasting a link onto text selection following CTRL + SHIFT selection

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11178]
**Describe the bug**
When selecting text, I expect the right arrow key to take me to the end of the selection. After pasting a link on top of a text selection made with CTRL + SHIFT, the right arrow key deselects text and the text cursor is placed at the _start_ of the selection.

**To Reproduce**
1. Type out anchor text
2. Use CTRL + SHIFT to select the text (selecting text in either direction triggers the bug)
3. Paste a link onto the selection that is on the clipboard already
4. Hit right arrow key
5. Text is deselected and the cursor is positioned at the **beginning** of the selection

**Expected behavior**
Cursor goes to the end of the selection

**Screenshots**
![link-selection-bug](https://user-images.githubusercontent.com/1238696/47618068-ec072280-da8b-11e8-8899-5836fc0cf948.gif)

**Desktop (please complete the following information):**
 - Win 10
 - Firefox 63
 - WP 5.0-beta1-43823, Twenty Nineteen, no plugins

**Comment by earnjam** [comment]
Possibly related to #5317
