### ISSUE TITLE
api-fetch errors on 204 response by default

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#11179]
**Describe the bug**
api-fetch throws an error because it forces a JSON response body even though the server indicates there is no response body.

**To Reproduce**
1. Make an `apiFetch` request to an endpoint that returns 204 No Content.
2. Error thrown.
**Expected behavior**
The request to succeed and return an empty response body.

```
[Warning] Error: [object Object] (dashboard.js, line 128726)
castError — cast-error.js:10
(anonymous function) — runtime.js:38
promiseReactionJob
```

**Workaround**
Pass `parse: false` to the `apiFetch` call.

**Proposed Change**
```js
const parseResponse = ( response ) => {
	if ( parse ) {
		if ( response.status === 204 ) {
			return null;
		}
		
		return response.json ? response.json() : Promise.reject( response );
	}
		
	return response;
};
```
**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari ( any )
 - Version 12.0 (any)

**Additional context**
- `@wordpress/data` v2.1.4

**Comment by youknowriad** [comment]
Sounds like a legit proposal for me. Up of a PR?

**Comment by TimothyBJacobs** [comment]
Sure, will work on a PR today.

**Comment by TimothyBJacobs** [comment]
Opened a PR. I'm not sure if the unit test is correct. I verified that it fails before the change, and passes after, but I haven't done Jest tests before so I might be missing something.
