### ISSUE TITLE
Paragraphs should be converted to headings using existing keyboard shortcuts

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#11173]
**Describe the bug**
Keyboard and formatting shortcuts that exist in the "classic" editor that convert paragraphs to headings should also apply to the paragraph block.

**To Reproduce**
1. Create a paragraph block
2. Press `ALT` + `SHIFT` + a number 1-6

or

1. Create a paragraph block
2. Start typing a number of hashes before the paragraph content
3. Press enter/return

**Expected behavior**
The paragraph block should be converted to a heading block with the heading level matching the number of the key pressed or the number of hashes that preface the paragraph

**Additional context**
- Gutenberg 4.1.1
- Keyboard and formatting shortcuts: https://codex.wordpress.org/Keyboard_Shortcuts

**Comment by rleeson** [comment]
Confirmed functionality does not meet the Keyboard Shortcuts outlined in the WordPress Codex.  

Note, implementation requires transforming from the Paragraph block type to the Heading block type.

**Confirmed with**
- Gutenberg 4.1.1 (only enabled plugin)
- WordPress 4.9.8

**Comment by cameronjonesweb** [comment]
Latest version has added the hashes markdown shortcut

**Comment by afercia** [comment]
This was recently reported also on Trac, see: https://core.trac.wordpress.org/ticket/51089

The accessibility team discussed this issue during the latest weekly meeting on Slack and agreed implementing the keyboard shortcuts to change heading levels that are available in the Classic Editor would be a good improvement, also considering feature parity. To recap:
```
control option 1 --> <h1> heading
control option 2 --> <h2> heading
control option 3 --> <h3> heading
control option 4 --> <h4> heading
control option 5 --> <h5> heading
control option 6 --> <h6> heading
control option 7 --> paragraph element
```

Regarding screen readers, worth reminding all the keyboard shortcuts that use control + option as modifier don't work with VoiceOver on masOS, as they conflict with native VoiceOver shortcuts. See https://core.trac.wordpress.org/ticket/39271,  https://github.com/WordPress/gutenberg/issues/11154 and the related https://github.com/WordPress/gutenberg/issues/3218 which is the only way to solve conflicts.

**Comment by mtias** [comment]
@ellatrix we discussed this before and I remembered you had some concerns. What do you think of supporting them?

**Comment by ellatrix** [comment]
ALT+SHIFT is not a good combo as it can produce input. CTRL+OPTION seems ok, if it doesn't clash with browser shortcuts.

**Comment by aristath** [comment]
> ALT+SHIFT is not a good combo as it can produce input. CTRL+OPTION seems ok, if it doesn't clash with browser shortcuts.

+1 on that. Alt+Shift is used by many to switch keyboard locales
