### ISSUE TITLE
Video Block - UI Improvement Suggestion #8423

### ISSUE THREAD

**Issue by ImpactMedia** [WordPress/gutenberg#11177]
**Describe the bug**
When using the video block the instruction is not clear for users when trying to add videos from URL's.

**To Reproduce**
1. Go to 'Add video block'
2. Click on 'Insert from URL'
3.  'Paste a YouTube / Vimeo or other video URL
4. See error - No video in supported format and MIME type found.

**Expected behavior**
Should have allowed the video to be inserted / embedded.

**Screenshots**
<img width="626" alt="screen shot 2018-10-28 at 14 41 24" src="https://user-images.githubusercontent.com/639342/47617676-78800800-dac1-11e8-9b21-efad783e7a08.png">
<img width="311" alt="screen shot 2018-10-28 at 14 59 23" src="https://user-images.githubusercontent.com/639342/47617729-1542a580-dac2-11e8-8f59-795d855e0ff6.png">

**Desktop (please complete the following information):**
 - OS: Sierra 10.12.6
 - Browser Firefox 
 - Version 63

**Additional context**
- Improvement should be made to potential wording on the video block that instructs users that if they would like to use YouTube, Vimeo or other Video from a URL - that they should use the Embed option.

Alternatively change wording to help users understand what type of file this feature is used for i.e. the url of the actual video file not just the page with video already embedded.

- Using Gutenberg via WordPress 5.0-beta1-43832

**Comment by Soean** [comment]
Hey @ImpactMedia 
thanks for reporting this issue. We already have a ticket about this UX problem, see #6824
I am closing this one, we can discuss a solution in the other ticket.
