### ISSUE TITLE
IE11: Large images that are left/right/center aligned break out of their figure container

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#11183]
**Describe the bug**

Large images that are aligned left, right, or center break out of their `figure` container in IE11, and extend off  the page. 

**To Reproduce**
1. Upload a large image (I used 1600px wide or more)
2. Set it to align left or right.
3. View the front end page in IE11.

**Screenshots**

<img width="1291" alt="screen shot 2018-10-28 at 10 07 11 pm" src="https://user-images.githubusercontent.com/1202812/47625826-e813e880-dafd-11e8-92f9-1fa4cead2f69.png">

_For comparison, here's a screenshot of the same page, taken in Safari 12.0:_

<img width="1245" alt="screen shot 2018-10-28 at 10 07 28 pm" src="https://user-images.githubusercontent.com/1202812/47625827-eb0ed900-dafd-11e8-8c40-151770f11103.png">

**Additional Context**

Originally reported over in the Twenty Nineteen repo (https://github.com/WordPress/twentynineteen/issues/264), but I was able to reproduce it in other themes.

**Comment by skirridsystems** [comment]
Is there any progress with this? It's affecting quite a few of my sites and IE11 is not yet a deprecated browser.

**Comment by skirridsystems** [comment]
Just to add it appears to affect only images with the .aligncenter class, not .alignleft or .alignright.

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
