### ISSUE TITLE
How to delete Gutenberg - I can't do this

### ISSUE THREAD

**Issue by conniegee** [WordPress/gutenberg#11182]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by GlennMartin1** [comment]
Unless you're using WordPress 5 beta, Gutenberg is a plugin that can be deactivated or deleted from the plugins page.

**Comment by danielbachhuber** [comment]
Hope your question was answered here, @conniegee. Feel free to comment if you have additional follow-up details.
