### ISSUE TITLE
Pasting only table from Google Docs doesn't work

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#11193]
**Describe the bug**
When pasting **only** table from Google Docs, it shows up plain text in Gutenberg. It works if you paste it with some text for example.

**To Reproduce**
1. Create heading and table in Google Docs.
2. Paste *only* the table in Gutenberg, I get text only.
3. Paste heading and table, and both works.

**Expected behavior**
Pasting only the table should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sierra 10.12.6
 - Browser: chrome 70.0.3538.77

**Comment by iseulde** [comment]
Does this work elsewhere? What is logged in the console?

**Comment by jasmussen** [comment]
Was about to ask similar to Ella, that this very much relies on what your operating system copies. If a table isn't actually copied, then there's nothing WE can do.

Outside of sharing what you saw in the JavaScript console, can you try copying the table, only the table, from Google Docs into another rich text editor, such as Word or Apple Pages or something like that? If it doesn't work there either, I don't know that we can do anything.

**Comment by iseulde** [comment]
Just looked around a bit, and what Google Docs gives us is just the `tr` tags without any `table` wrapper. We could detect the missing wrapper, and wrap it ourselves. Worth noting that any other editor I've tested doesn't handle this, so do I get bonus points? :)

**Comment by iseulde** [comment]
Confirmed it works from Chrome. Safari and Chrome give different output. I'll attempt to fix both at some point.

**Comment by samikeijonen** [comment]
@iseulde Did you had time to check this out?
