### ISSUE TITLE
Editor: Eliminate or refactor store notices constants

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#11202]
Previously: https://github.com/WordPress/gutenberg/pull/9617#discussion_r227247616

We now inconsistently use constants for referencing notices by ID in the editor module. The primary need for them is in dismissal upon the start of a new save (e.g. autosave notice, previous save success/error notice).

We should consider one of:

- Reintroduce consistency, either eliminating all instances of constant references to notice IDs in favor of strings (yes, magic strings), or reintroducing ([introducing?](https://github.com/WordPress/gutenberg/pull/9617#discussion_r228626263)) constant reference use.
- Implement a better system to express and track notices which ought to be dismissed in response to particular actions, like "on next save". See https://github.com/WordPress/gutenberg/pull/9617#discussion_r228624906

In #9617, it was chosen to not use the constant to avoid a dependency between the component and the store, though this is loosely held.

**Comment by paaljoachim** [comment]
Should this issue be closed?

@gziolo

**Comment by gziolo** [comment]
There are still 2 places where we use constants so I would say this issue is close to ready but not done yet.
