### ISSUE TITLE
Self referencing reusable block creates infinite loop that crashes WordPress

### ISSUE THREAD

**Issue by danielpunkass** [WordPress/gutenberg#11206]
This is a little nefarious but probably a scenario that should be protected against all the same: if a reusable block is edited such that it includes a reference to itself, any attempts to edit or render that post will result in a crash of WordPress due to exhausting usable memory in PHP.

1. Create a new post in Gutenberg.
2. Create a new paragraph "Bad Block" and save it as a reusable block.
3. Contrive to edit the block directly by changing the URL to point at the newly created block post. For example if you are editing post 123, then the new reusable block was probably assigned ID 124, so change the editor URL to point at it.
4. Within the editor for the reusable block, add a new "Classic" block, switch it to edit HTML source, and set the content to:

`<!-- wp:block {"ref":124} /-->`

Where "124" is whatever the actual block's ID is.

5. Save changes. You'll see an error reported, but the post will have actually been updated.
6. Navigate back to editing post 123, where you had originally added the reusable block.

Result: Crash in PHP with errors like:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/wp-content/plugins/gutenberg/lib/blocks.php on line 105
> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/wp-includes/plugin.php on line 453

Expected behavior: the block rendering code should detect attempts to recursive include content and avoid crashing WordPress.

 - OS: macOS 10.14
 - Browser Safari
 - Version Version 12.0 (14606.1.36.1.9)

**Comment by talldan** [comment]
Can confirm I was able to reproduce this.

**Comment by jorgefilipecosta** [comment]
Removing from the  WordPress 5.0 RC as the remaining issue is not possible to trigger o the UI without more complex steps.

**Comment by jorgefilipecosta** [comment]
I guess we can close the issue, as I don't think more could be done to avoid the problem, and the UI already forbids the possibility of a user doing it.

**Comment by ElementMedia** [comment]
Managing blocks by getting to the wp_block post type page (edit.php?post_type=wp_block) this way you can still reference a reusable block into a reusable block.
