### ISSUE TITLE
Gutenberg can not save post when ModSecurity firewall is enabled

### ISSUE THREAD

**Issue by elliason** [WordPress/gutenberg#11204]
**Describe the bug**
While having ModSecurity firewall turned on ( with default OVH web hosting settings ) I am not able to update post. Instead the firewall blocks the request and returns 400 error. This is not happening while using the classic editor, only in Gutenberg. It also works fine after disabling the firewall.

**To Reproduce**
1. Go to any post
2. Click on 'update'
3. See error (400 Bad Request)

**Expected behavior**
It should save/update the post without any error. The firewall should be enabled to protect from DDoS or SQL injections. Turning of firewall protection just to enable post saving is not really a good solution.

**Additional context**
- Gutenberg 4.1.1 
- Wordpress 4.9.8

**Comment by earnjam** [comment]
Thanks for reporting @elliason!

We're tracking this issue in #10075
