### ISSUE TITLE
Enzyme and React 16 workarounds

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#11214]
This issue is to document the workarounds that we have in place to work with some of React 16 features that aren't supported by Enzyme yet. For reference, https://github.com/airbnb/enzyme/issues/1553 is where the enzyme project is tracking their support of React 16 features.

At the time of creating this issue, we're still using enzyme 3.3.0 and enzyme-adapter-react-16 1.1.1 but the latest releases are `3.7.0` and `1.6.0`. Some of the issues may have been fixed.

- [ ] Mock for forwardRef in [Button](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/__mocks__/index.js).
- [ ] BlockContros's [skipped test](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-controls/test/index.js#L30).
- [ ] Only supports the legacy context API.

**Comment by aduth** [comment]
cc @gziolo with consideration of progress in airbnb/enzyme#1553 and airbnb/enzyme#1604 , the current workarounds might no longer be necessary given our recent upgrade to `enzyme` and `enzyme-adapter-react` in #13922 . (There's also been another release of `enzyme-adapter-react` since then).

I'll poke around a bit to get a better sense of where things stand.

**Comment by gziolo** [comment]
Nice work @aduth. I wasn't sure whether we want to fix those workarounds with the updated `Enzyme` API or replace them with React test utils. The approach you took is probably better as it is less work :) We have over 80 test suites using `enzyme` so I bet we are in a position where we will have to support it for quite some time knowing that they will always be a few weeks or even months behind React releases. I hope that at some point we will build our own abstractions which will allow to replace `shallow`, `mount` and `render` easily. We are not there yet.
