### ISSUE TITLE
Be able to make line breaks in list block

### ISSUE THREAD

**Issue by scottyg7** [WordPress/gutenberg#11215]
When making lists, I often break up the content within an item with a line break (Shift+Enter). This helps make the item more readable and is appropriate for items that have longer text. 

Just as we can do in a paragraph block, I'd like to be able to use SHIFT+ENTER to create a line break that doesn't result in a new block.

**Comment by strarsis** [comment]
What about making the list nestable for _textual_ blocks?

**Comment by GaryJones** [comment]
Likewise, multiple paragraphs in a list suggest that paragraph blocks should be nestable inside list blocks.

**Comment by youknowriad** [comment]
Looks like this is a highly asked for feature. @iseulde Any technical challenge to support this?

**Comment by iseulde** [comment]
No

**Comment by haemeulrich** [comment]
Tonight we had WordPress Meetup. Nobody really believed that Shift-Enter didn't work.

**Comment by iseulde** [comment]
Looking now.

**Comment by chrilleferna** [comment]
@haemeulrich "_Nobody really believed that Shift-Enter didn't work._" Well, I not only belive it, I know it does not work.

**Comment by rogerlos** [comment]
Shift-enter has been used since the neolithic to mean "do not break me out of the element I'm in" in the context of editors. Wish this had been something gutenberg folks were aware of, I'm having to install third-party blocks just to make simple tasks non-nightmares for my clients. Sigh.

**Comment by iseulde** [comment]
It will be fixed in the next Gutenberg release.

**Comment by chrilleferna** [comment]
Great, and while you fix that, maybe you could also fix another minor thing: to underline you have to use ctrl-u on OSX, while it ought to be cmd-u (ctr-u is for Linux and Windows)

**Comment by iseulde** [comment]
@chrilleferna That's already fixed in #13117.
