### ISSUE TITLE
Post Title and H1 font-size differ slightly

### ISSUE THREAD

**Issue by spencerbaynton** [WordPress/gutenberg#11223]
In pull request #5631 the typographic scale for headings was set to a major third scale with the values rounded to 2 decimal places. The post title's `font-size` was intended to "[Match h1 heading.](https://github.com/WordPress/gutenberg/blob/6321a997615c9560c98f24d69739ddaa82cf8e26/packages/editor/src/components/post-title/style.scss#L31)" However, the post title `font-size` was not rounded. The [post title's font-size](https://github.com/WordPress/gutenberg/blob/6321a997615c9560c98f24d69739ddaa82cf8e26/packages/editor/src/components/post-title/style.scss#L32) should be `2.44em` instead of `2.441em`.

**Comment by ellatrix** [comment]
Cc @jasmussen, as it's about your PR. :)

**Comment by jasmussen** [comment]
Great ticket, I'll get this fixed. Have a bit on my table, but assigning myself, and will probably do next week.
