### ISSUE TITLE
Embed block followed by another block, won't let you scroll

### ISSUE THREAD

**Issue by correliebre** [WordPress/gutenberg#11221]
**Describe the bug**
When adding an embed block with Instagram or Twitter links and selecting the alignment menu on top of the block, it won't let you scroll down to edit any block underneath it, unless you unselect the alignment menu on top of the embed block with the link. 

**To Reproduce**
1. On a page/post add a new embed block and paste an Instagram link
2. Add a second text block underneath the first one, with any text.
3. Select the alignment menu on top of the block with the Instagram embed. 
4. Try scrolling down and editing any of the text blocks underneath the block with the Instagram embed. It won't let you do it, and will scroll back up. 

**Expected behavior**
Like any other block, when selecting the alignment menu on top of the block, it will still let you scroll down and edit other blocks.

**Screenshots**
Screencast for the issue with Instagram:

![instagramissue](https://user-images.githubusercontent.com/25516017/47677751-55735800-db96-11e8-909a-9019fb7e0de6.gif)

Screencast for the issue with Twitter:

![twitterissue](https://user-images.githubusercontent.com/25516017/47678029-28737500-db97-11e8-84fd-3b45e3ae86c9.gif)

Screencast for the expected behaviour on both:

![ScreencastText](https://cdn-std.dprcdn.net/files/acc_652292/bp6G59)

**Desktop:**
 - OS: Mojave 10.14
 - Browser: Firefox
 - Version: 62.0.3

**Additional context**
- Gutenberg 4.1.1
- It was the only plugin activated besides Jetpack
- Tried it with Spotify link, since the embed is shorter, there was no issue. ![Screencast3](https://cdn-std.dprcdn.net/files/acc_652292/APgXkQ)
- Tried it with Facebook link, confirmed [this issue](https://github.com/WordPress/gutenberg/issues/8360).

**Comment by earnjam** [comment]
I'm able to recreate with Firefox 63, OS X, Latest from WP 5.0 branch. 

It requires the embed block be selected. Then scroll down. Then when you try to hover over any blocks below the embed block, it jumps down.

**Comment by youknowriad** [comment]
This seems fixed for me, I can't reproduce anymore.
