### ISSUE TITLE
Is there a way to hide a richtext field if not in focus?

### ISSUE THREAD

**Issue by rogerlos** [WordPress/gutenberg#11233]
I've tried everything logical, which I know is not the way with react, but...

I have a custom block with an optional field. If the block is in focus, show the field. If the block is not in focus and the field is empty, hide it from view. This is in the "main" editor, not in the inspector. I assumed this would be something done in the "save" function, but my efforts there are without fruit.

(I also could not get the chain of dependencies for npm to work on my dev machine, so doing this in ES5.)

```Javascript
wp.blocks.registerBlockType( 'sweetrelease/ofdeath', {
    ...
    save : function( props ) {
        return wp.element.createElement( 
            'div', 
            {},
            reaper( props )
        )
    }
} );

function reaper( props ) {
    if ( ! props.attributes.scythe ) return null;
    return wp.element.createElement( 
        RichText.Content,
        {
            value : props.attributes.scythe
        }
    );
}
```
Obviously there's a matching `edit` rendering of the field. The above never returns `null`, even if `scythe` is empty.

This would seem to be a kind of obvious thing to be able to do, but I'm just not making it happen. There is a placeholder on the field. 

My understanding, having read all of the documention and many, many issues here, and the various tutorials on the web, is that, when in the editor and out of focus a block will render using the `save` rendering, which makes sense in that it helps ensure that the gutenberg editor looks as much like the rendered page on the public side as possible.

Having written that I now have a gnawing suspicion this is just not the case. Is that a misunderstanding? If so, yikes.

I'm about to cook up some sort of gnarly jQuery selector to test the placeholder data attribute, and hope my user doesn't have 632 instances of for jQuery to sort through...

_I would check the documentation, but it is pretty awful at the moment--I mean that in the nicest way possible, but it is always outdated and, for example, the code on https://wordpress.org/gutenberg/handbook/block-api/rich-text-api/ is missing the `props` attribute on `save` method on the ES5 example, without which it doesn't work. A lot of the rest of it is very cryptic and clearly written by folks very familiar with react and not particularly friendly to people who are not going to use npm. Anyway._

Halp.

**Comment by iseulde** [comment]
You can use `isSelected`. See https://wordpress.org/gutenberg/handbook/block-api/block-edit-save/#isselected. See e.g. the image block code in core.
