### ISSUE TITLE
AJAX post but only got a 500 error - 5.0 Beta1

### ISSUE THREAD

**Issue by foreverpinetree** [WordPress/gutenberg#11236]
Just tesed with wp5.0-Beta1. My theme includes a page builder, it disables Gutenberg (use 'use_block_editor_for_post' filter) for some specified pages. It needs to connect the backend via AJAX when editing these pages, but everytime I opened the builder and only got a 500 error. 

Error logs:
`POST http://localhost/xampp/test/wp5.0/wp-admin/admin-ajax.php 500 (Internal Server Error)`

`[30-Oct-2018 08:57:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_block_editor() on null in D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\script-loader.php:2194
Stack trace:
#0 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\class-wp-hook.php(286): wp_common_block_scripts_and_styles('')
#1 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#3 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\script-loader.php(2040): do_action('wp_enqueue_scri...')
#4 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\class-wp-hook.php(286): wp_enqueue_scripts('')
#5 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#7 D:\xampp\htdocs\xampp\test\wp5.0\wp-includes\general-template.php(2614): do_action('wp_head')`

**Comment by designsimply** [comment]
Noting that if this problem happens only with WP 5.0 betas and not with the standalone Gutenberg plugin, then we will want to report the issue at https://core.trac.wordpress.org/

Before we do that, would it be possible for you to provide some better testing steps including some basic code snippets that show the problem a bit better?

**Comment by foreverpinetree** [comment]
I will report to there and provide more info, thank you. I close this issue.
