### ISSUE TITLE
Empty paragraph block renders without opening <p> tag/invalid html

### ISSUE THREAD

**Issue by knutsp** [WordPress/gutenberg#11238]
**Describe the bug**
Empty paragraph block gives a stray </p> tag

**To Reproduce**
1. Go to 'Add new post'
2. Add a title and press enter
3. Write some text as first block + enter
4. Write some text as second block + enter
5. Write some text as third block
6. Place cursor in second block and delete all text by backspace
7. Publish post
8. Show post
9 Show html source in browser
10. Scroll down to see paragraph-1 text and paragraph-3 text
11. Observe `</p>` on a line between paragraphs

**Expected behavior**
No extra `</p>`, nothing or empty line

**Desktop**
 - OS: Windows 10
 - Firefox
 - Version 62

**Additional context**
- WordPress 5.0 beta2.

**Comment by earnjam** [comment]
I'm not seeing any invalid markup. 

Tested using your steps as best I could tell:

![image](https://user-images.githubusercontent.com/4267290/47730984-a4be9480-dc39-11e8-86fc-91b146948e0a.png)

![image](https://user-images.githubusercontent.com/4267290/47730916-86f12f80-dc39-11e8-93f3-3873d284bc55.png)

I think we lost some information in your post. Can you update and put the markup you are seeing inside backticks or else use a screenshot?

**Comment by knutsp** [comment]
This what I get:
![11238-gutenberg](https://user-images.githubusercontent.com/1531128/47776692-47871980-dcf3-11e8-888b-2998a5546a16.png)
![11238-html](https://user-images.githubusercontent.com/1531128/47776691-47871980-dcf3-11e8-8bf6-9687b2bcc5e3.png)
No plugins except WP Beta Tester and Advanced Automatic Updates

**Comment by earnjam** [comment]
Ah, you're right. I see the same thing now in Firefox. I was testing in Chrome before. 

Seems to only be Paragraph tags. I tried with other empty text blocks and none of them had invalid markup. 

<img src="https://user-images.githubusercontent.com/4267290/47780652-3083ff80-dcd2-11e8-80b1-6ad2a0758e54.png" width="400" />

**Comment by earnjam** [comment]
Actually, now I see it in Chrome too. 🤔 

Content is saved correctly in the database. 
![image](https://user-images.githubusercontent.com/4267290/47780894-c15adb00-dcd2-11e8-9b39-fe5accebf0d2.png)

It's just dropping the opening `<p>` when rendering on the front-end.

**Comment by youknowriad** [comment]
I'm not able to reproduce this issue anymore. Thanks
