### ISSUE TITLE
Mouse hovering mostly ignored when the domain is dotless.

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#11248]
**Describe the bug**
In my local development environments, with a domain name that is "dotless", mouse movement / hovering appears to be ignored. This prevents certain functionality from working as expected. 
Originally raised as https://github.com/bobbingwide/oik-block/issues/29

**To Reproduce**
1. Create a local site with a dotless domain, not `localhost`. e.g. `https://qw`
2. Open a post with multiple blocks.
3. Move the mouse over the blocks.
4. The only control that appears is the "Insert block" button, between blocks.
5. Change the domain to a dotted one, e.g. `https://q.w`, and login again
6. Open the same post and move the mouse.
7. Notice the feedback when hovering... Move block icons, block border and hint all appear.

**Expected behavior**
Hovering should take effect regardless of the domain name.

**Screenshots**
From the original issue
Step 4. only Insert block is shown
![image](https://user-images.githubusercontent.com/2474435/47722799-1a7f2c00-dc4b-11e8-86c0-48477d814ff5.png)

Step 7.Move block icons, a blue border and block hint all appear with a dotted domain.
![image](https://user-images.githubusercontent.com/2474435/47376232-02a72580-d6ea-11e8-9925-f0e649a9c0d5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.77 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
- Found in Gutenberg 4.0.0, reproduced with 4.1.1
- Workaround is to ensure there's a dot in the domain name,

**Comment by bobbingwide** [comment]
Ah! I tried another browser ( Firefox ) and eventually noticed that this behaviour appears to be related to Spotlight mode.  The action of switching domains and logging in again must have reset something.

Now I can see that this was introduced in 3.7.  Mentioned in WP Tavern ( https://wptavern.com/gutenberg-3-7-released-introduces-spotlight-mode ) this is an experimental attempt at introducing a Distraction Free Writing mode. 

IMHO the experiment failed.

**Comment by earnjam** [comment]
I was just going to ask if you were in Spotlight Mode. Thanks for following up!

**Comment by bobbingwide** [comment]
Was thinking of changing the title to "Bamboozled by Spotlight Mode".

**Comment by earnjam** [comment]
I can reopen if you'd like to start discussion about it, but I think it might be better to open a different ticket specific to issues with Spotlight Mode and then just reference this one as an example.
