### ISSUE TITLE
Using Persistence Plugin only on some of the keys throws error next time on store registration/store subscription

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#11240]
**Describe the bug**
Using the persist property to save to local storage some of the state properties will save those keys to the local storage. Next time the store is created (on a page refresh) the initial state will be created only with the persisted values, and will throw undefined Uncaught TypeError on selectors that use the non-persisted values.

**To Reproduce**
Take this example store:
````javascript
const DEFAULT_STATE = {
	persisted_elements: [],
	non_persisted_elements: [],
};

const reducer = function() {
	return function(state = DEFAULT_STATE, action) {
		switch (action.type) {
                // ...
		}
		return state;
	};
};

const selectors = function() {
	return {
		getNonPersistedElements(state) {
			return state.non_persisted_elements;
		},
	};
};

const actions = function() {
	return {
        // ...
	};
};

const store = registerStore("test", {
	reducer: reducer(),
	actions: actions(),
	selectors: selectors(),
	controls: {},
	resolvers: {},
	persist: ["persisted_elements"]
});
````
If I have a component subscribed (using `withSelect`) to `getNonPersistedElements()`, on page load the state will only be `{ persisted_elements: [] }`. It will throw an error as the object property non_persisted_elements is undefined at that point.

**Expected behavior**
Expected to have merged `DEFAULT_STATE` and persisted one on store registration.

**Versions**
- Gutenberg 4.1.1
- WordPress 4.9.8

Thanks.

**Comment by youknowriad** [comment]
Hi There!

I think you should use `combineReducers` to combine your persisted and unpersisted state trees. This allows your default values to be separate and applied separately.

**Comment by alvaro0555** [comment]
@youknowriad Thanks for the tip!
Will check it and come back if I find any problem with it.
