### ISSUE TITLE
Designer & Developer Handbook

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#11251]
This is a tracking ticket for the Designer & Developer Handbook. The goal is to use this ticket to get us to…

1. Consolidate discussion
2. Consolidate GitHub issues related to the dev documentation into this ticket
3. Map PRs to sections of the dev handbook outline

## Outline

1. Building blocks and plugins
    1. Tutorials
        1. Build your first block (#6185)
        2. Build your first plugin sidebar
        3. Extend a block
        4. Extend the editor
    2. Developer Reference
        1. Blocks API
            1. `registerBlockType`
            2. `attributes`
            3. `edit` and `save` (#4070)
        2. Plugins API
        3. Components (#7327)
        4. Registered scripts
        5. Block filters
        6. Editor filters & slotfills
        7. Parsing and rendering blocks with PHP functions (#6358)
    3. Designer Reference
        1. Human Interface Guidelines
        2. Preparing block icons
2. Theming for the new editor
    1. Theme support list
    2. Block HTML & CSS reference (classes to target)
    3. Editor styles
    4. Block style variations
3. Backwards compatibility
    1. Meta boxes
        1. No server side validation or `add_settings_error` (#3964)
    2. Important deprecations/changes from 4.x (#4186)
4. Resources
    1. Articles
    2. Meetups
    3. Talks

**Comment by 0aveRyan** [comment]
@chrisvanpatten took a second pass on the outline

1. Technical Introduction
    1. How It Works
    2. Production Dependencies
    3. Build Process Dependencies
    4. Best Practices
2. Building Themes
    1. Theme Support
    2. Frontend CSS
    3. Admin Editor CSS
    4. Block Style Variations
    5. Preparing Dark Themes
    6. CSS Reference
3. Building Plugins
    1. Custom Block Styles
    2. Custom Blocks
    3. Extending Blocks
    4. Block Categories
    5. Editor Plugins
4. Developer Reference
    1. Blocks API
    2. Plugins API
    3. Template API
    4. Using Higher-Order Components
    5. Interacting with the Data Store
    6. Block Filters
    7. Editor Filters
    8. Parsing Blocks in PHP
5. Design Reference
    1. Human Interface Guidelines
    2. Preparing Block Icons
6. Backwards Compatibility
    1. Meta Boxes
    2. Deprecations
7. Resources
    1. Articles
    2. Meetups
    3. Talks
    4. Open-Source Examples

**Comment by 0aveRyan** [comment]
@chrisvanpatten in my last meeting of the day and then I'll dive in on that

**Comment by chrisvanpatten** [comment]
@0aveRyan awesome thanks! don't worry about updating the manifests; I'm working on a script to do that automatically.

**Comment by skorasaurus** [comment]
Although there was a merge at https://github.com/WordPress/gutenberg/pull/11817; [this outline](https://github.com/WordPress/gutenberg/issues/11251#issuecomment-438723771) isn't visible at https://wordpress.org/gutenberg/handbook/designers-developers/ 
Is it intended to be ?

**Comment by nosolosw** [comment]
Is this still relevant now that the handbook has been reorganized and migrated to https://developer.wordpress.org/block-editor/ ?

**Comment by chrisvanpatten** [comment]
Let’s close it; I think we’ve accomplished the changes we set out to make. Thanks everyone for your amazing help!

🚀
