### ISSUE TITLE
Media & Text Block: Applies 'wide' alignment, even in themes that don't support it

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#11259]
**Describe the bug**
When you add a Media & Text block to a post, using a theme that doesn't support the wide alignments, it still adds the the `.alignwide` class on the front end, and the `data-align="wide"` attribute to the editor. 

**To Reproduce**
1. Start with a theme without wide alignment support (I was using the version of Twenty Seventeen in the 5.0 branch, or Beta 1).
2. Create a post, and add a "Media & Text" block.
3. Inspect the block in the editor and note the `data-align="wide"` attribute.
4. Publish the post. Inspect the block to see the `.alignwide` class.

**Expected behavior**
That the block would not automatically add these alignments, at least in themes that don't support them. If a theme supports them, it does make sense as a default because this block benefits from some extra space.

**Screenshots**
In the editor (RC 4.1.1):

![image](https://user-images.githubusercontent.com/177561/47741324-40023a80-dc37-11e8-8b8c-903b93b1e984.png)

On the front-end (RC 4.1.1):

![image](https://user-images.githubusercontent.com/177561/47741351-501a1a00-dc37-11e8-9758-54f84c1c6dd3.png)

**Additional context**
I can recreate this in Gutenberg 4.1.1 and WordPress 5.0 beta.

Using the the master branch of the Gutenberg repo (latest commit 9d46788), I can also recreate the issue; in that case, updates to the editor also style the block as 'wide' in the editor (which is the only reason I noticed this!):

![image](https://user-images.githubusercontent.com/177561/47741451-8bb4e400-dc37-11e8-831e-fd9c077b9d10.png)

**Comment by dashkevych** [comment]
I can also recreate this issue when the theme does not have `add_theme_support( 'align-wide' )`.

**Comment by designsimply** [comment]
Closing in order to consolidate with #4342. @laurelfulford, if you feel strongly that the two should remain open separately, please reply and let me know and I will re-open.
