### ISSUE TITLE
Min-width needed on table columns

### ISSUE THREAD

**Issue by CodeProKid** [WordPress/gutenberg#11266]
**Describe the bug**
Hi there, I was trying to add a table of data with three columns. The first two columns contain just a word or two, and the third column contains a full sentence or two, this has caused the first two columns to collapse to the point where they just have two or three letters stacked on top of each other.

Things look OK on the front end of the site, but it's borderline un-usable on the backend. (see screenshot below)

The only way to fix this is to switch to "fixed width" but then you can't adjust the width of the columns. Seems like that feature is being worked on in #9801 

**To Reproduce**
1. Create a new post
2. Create a new Table block with three columns and a few rows
3. Just put a few characters in the first two columns, and then put a few sentences in the third column

**Expected behavior**
I expect the columns with only a few characters to collapse to a certain point, the characters shouldn't start stacking on top one another.

**Screenshots**
![screen shot 2018-10-29 at 8 07 40 pm](https://user-images.githubusercontent.com/3899467/47746399-9bd6be80-dc4b-11e8-9620-efaf45f29afe.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.5
 - Browser: Chrome 70.0.3538.67
 - Plugin Version: 4.1.1
 - WordPress Version: 4.9.8

**Comment by AndreKelling** [comment]
same here.
looks weird for the editors.
might be easy to fix with a min-width CSS rule for table columns.

![table_column_width_issue](https://user-images.githubusercontent.com/15000189/48545577-835ed900-e8c6-11e8-89b3-6559bf2d6a84.jpg)

**Comment by MarkRH** [comment]
Hmmm.. WP 5.0 with its built-in Gutenberg still has this problem.  Since Gutenberg is baked into WP now, is this still the appropriate place to post issues?

**Comment by MarkRH** [comment]
Looking at the CSS, it seems this is causing it in my case (with TwentyTwelve theme) on the front-end:
```css
.wp-block-table td, .wp-block-table th {
	padding: .5em;
	border: 1px solid currentColor;
	word-break: break-all;
}
```
This is located in **/wp-includes/css/dist/block-library/theme.min.css?ver=5.0**
Setting `word-break` to `normal` or `unset` fixes it.

Before:
![image](https://user-images.githubusercontent.com/8035962/49677706-d7805780-fa45-11e8-864d-84f8240df619.png)
 After:
![image](https://user-images.githubusercontent.com/8035962/49677737-fa127080-fa45-11e8-9e0f-f2553855e0a8.png)

**Comment by youknowriad** [comment]
It seems like the word-break issue for me is now fixed. Let me know if you're still experiencing issues.
