### ISSUE TITLE
Cover Block: Align full jumps left

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#11269]
**Describe the bug**
When in editor, a cover block that is supposed to be aligned full, moves to the left but doesn't go full screen. seems a regression from previous version. (using 5.0 Beta 2)
It is displayed ok on the front end. 
**To Reproduce**
1. Add a cover block
2. use the align full button 
3. see the cover image go to the left edge of the admin window and only fill half of the screen. The right half is missing. 
**Expected behavior**
The cover image expand over the full screen. 

**Screenshots**
I have a video: http://recordit.co/gw397W5bxA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: desktop
 - OS: MacOS 10.13.6
 - Browser Chrome
 - Version 70.0.3538.77

**Comment by earnjam** [comment]
I wasn't able to recreate in Chrome on OS X with latest from core 5.0 branch, or with latest from Gutenberg `master`.  

Do you have any other plugins active? What theme? Is it possible there are some editor styles stepping on the CSS for it?

**Comment by bph** [comment]
I can confirm that it's not happening using Gutenberg master. Closing issue as resolved
