### ISSUE TITLE
When using arrow keys to move cursor within/between Paragraph blocks, the block controls disappear until the block is hovered/tapped again

### ISSUE THREAD

**Issue by benlk** [WordPress/gutenberg#11265]
**Describe the bug**
Using WordPress 5.0-beta2's version of Gutenberg, and using 4.9.8's Gutenberg plugin version 4.1.1, when I use arrow keys to move within a Paragraph block, or move from Paragraph block to Paragraph block, the buttons that appeared at the top of the Paragraph block disappear.

If I'm on a device with a mouse, I have to jiggle the mouse over the block to retrieve those buttons.

If I'm on a device with a touchscreen, I have to tap the block to retrieve the buttons.

**To Reproduce**
1. Create a number of multiline Paragraph blocks.
2. Using the arrow keys, move the cursor within a paragraph block.

**Expected behavior**
I expected the Paragraph formatting controls to remain visible while I'm editing a Paragraph block. And generally, I expect block controls to remain visible when I'm interacting with a block.

By "block controls" I mean everything in the block that is not the text content:

<img width="456" alt="screen shot 2018-10-30 at 4 11 24 pm" src="https://user-images.githubusercontent.com/1754187/47747326-7f904d00-dc5e-11e8-8155-44655332f139.png">

- the grab handle for moving the block up and down
- the buttons for moving the block up and down
- the block type choice button
- the text alignment controls
- the bold/italic/link/strike controls
- the three-dot menu
- the outline around the active block

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome, with and without touch emulation enabled
 - Version: 69

**Smartphone (please complete the following information):**
 - Device: Touchscreen computer
 - OS: OSX
 - Browser: Chrome
 - Version: 69

**Additional context**
- Gutenberg version: WordPress 5.0-beta2's version of Gutenberg
- Gutenberg version: Gutenberg 4.1.1 on WordPress 4.9.8

**Comment by earnjam** [comment]
For better or for worse, this is actually by design. I think the idea is to get the controls out of the way. 

You can make them stay by using the Unified Toolbar setting, which will fix them to the top of the editor at all times. 

![image](https://user-images.githubusercontent.com/4267290/47751985-a607b580-dc69-11e8-92d7-f96723d70229.png)

**Comment by benlk** [comment]
"to get them out of the way" seems like an option that would only be enabled on Fullscreen Mode, under the "work without distraction" premise that believes that all UI is distraction.

At least let "fade out block controls" be an option in the "view" settings, rather than a default.

Reasons I object to having the tools disappear:
- It's really distracting to have the tools keep disappearing. The disappearance is something moving onscreen when I didn't tell that thing to move. The only things that should be moving are things that are trying to draw my attention or things that are moving as a result of user input (the cursor and the mouse).
- I'd like to know what the options are for formatting without having to remove my hands from the keyboard to touch the screen or jiggle the mouse.
- The idea of hiding UI from the user on the grounds that the UI, which does not overlap the currently-active block, is in the way of the user using the currently-active block, doesn't pass the laugh test. The present blocks' UI prevents me from clicking on other blocks, sure, but that's an argument that favors solutions that don't remove UI, such as:
    - a control to explicitly defocus the present block or dismiss its UI until the block is reentered
    - additional white-space between blocks to account for their UI when they are open and the Unified Toolbar is not in place

**Comment by aduth** [comment]
>I'd like to know what the options are for formatting without having to remove my hands from the keyboard to touch the screen or jiggle the mouse.

Pressing <kbd>Escape</kbd> will cause the toolbar to become shown.

Pressing <kbd>Alt+F10</kbd> will move focus into the toolbar, regardless of whether it is shown or not.

**Comment by benlk** [comment]
Can we get that list of keyboard shortcuts documented somewhere that is linkable? I see no references to keyboard shortcuts on https://wordpress.org/support/article/wordpress-editor/

**Comment by benlk** [comment]
****
