### ISSUE TITLE
Checked inputs blue themselves

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#11261]
Checked input boxes have blue checks on top of blue backgrounds.

**To Reproduce in WordPress Admin**
1. Login as a user with Contributor or higher capabilities
2. Visit WordPress admin
3. Create a new Post
4. Check the "Stick to Front Page" checkbox
5. Blue background with blue check
6. This cascades across all Gutenberg-area checkboxes

**Expected behavior**
The check should probably be white. (It's also a bit off-center.)

**Screenshots**
<img width="280" alt="screen shot 2018-10-30 at 1 56 10 pm" src="https://user-images.githubusercontent.com/88951/47742867-97120a80-dc4b-11e8-9bab-a38a450a6a70.png">

![blue](https://user-images.githubusercontent.com/88951/47742800-747ff180-dc4b-11e8-9211-61788e200b18.png)

**Desktop**
 - OS: macOS 10.14.1
 - Browser Safari & Chrome
 - Latest stable versions of everything

**Additional context**
- Latest Gutenberg
- Latest WordPress 5.0 branch

**Comment by ocean90** [comment]
This only happens in core without the plugin activated. The color and position of the checkmark gets overridden by https://github.com/WordPress/wordpress-develop/blob/6b366c6620fdd5960cedcdf80955966a715efa82/src/wp-admin/css/forms.css#L132-L136

This is related to #11089.
