### ISSUE TITLE
Gallery: Use columns for the items

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1127]
Current state of the gallery:

![current](https://user-images.githubusercontent.com/1204802/27010773-ed817758-4eac-11e7-9b65-c7bf7bbd16d5.png)

Let's try replacing these floats with `column-count` and `column-gap`, which are sufficiently supported for us (IE11+): https://caniuse.com/#search=column

Here's how that looks with a column count of 2:

![wishlist](https://user-images.githubusercontent.com/1204802/27010779-11580bf6-4ead-11e7-8464-0624867939a2.png)

We could default to 3 columns, but then let that number be configurable in the post-settings inspector.

**Comment by mtias** [comment]
Done in #1135.
