### ISSUE TITLE
Inline code with backticks stays within the code tag when closing

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#11276]
**Describe the bug**
Adding inline code tags using the backtick shortcuts keeps the cursor within the code formatting and forces you to navigate out of it to write normal text. 

**To Reproduce**
1. Type a backtick in a paragraph block (`)
2. Write some "code"
3. Add another backtick to close the inline code formatting
4. Continue typing. The cursor is still inside the code formatting and it shouldn't be

**Expected behavior**
After the backtick that closes the code tag is added, the cursor should automatically be outside the code tag as it is in the classic editor

**Screencast**
https://youtu.be/-pAGqeNckf8

**Additional context**
- Gutenberg 4.1.1

**Comment by iseulde** [comment]
Yes, we should fix this. Thanks for the report.

**Comment by swissspidy** [comment]
This is what I'm seeing right now with WordPress 5.0 RC 1:

![screen recording 2018-11-29 at 18 09 39](https://user-images.githubusercontent.com/841956/49239216-72ec4980-f402-11e8-9f10-6b0a90434b66.gif)


The cursor position is off, and the backticks are only converted when pressing backspace.

**Comment by pauljacobson** [comment]
I noticed this too. This issue also applies to some closing HTML tags. Here's a demo of the Markdown issue:

![markdown_backticks_formatting_gutenberg](https://user-images.githubusercontent.com/2912202/50556038-c17c5480-0cdc-11e9-97b3-5a938d6a6fb4.gif)

**Comment by phpbits** [comment]
@ellatrix Can this fix be called via API? I'm having the similar issue when adding custom markdown :

![Screen Capture on 2019-05-26 at 12-45-50](https://user-images.githubusercontent.com/3365507/58377485-65c8a580-7fb4-11e9-87ab-f85c6a16b03c.gif)


Thanks!

**Comment by phpbits** [comment]
@ellatrix Just figure it out :) Driving me crazy but really glad to have it figure out. Thanks!

**Comment by richrd** [comment]
@phpbits how did you solve your issue?
