### ISSUE TITLE
Can no longer edit Slug for Pages on the main Pages screen

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11277]
**Describe the bug**
On the main Pages screen (where you view your list of Pages), you can click the _Quick Edit_ link to edit some of the page details. One of those items that you could edit was the page slug. In WP 5.0 beta 2 you can no longer do this for Pages, but you can still do it for Posts.

Pages screen
![screenshot_911](https://user-images.githubusercontent.com/2078245/47763477-fbe56780-dd14-11e8-8d67-f43379b7e210.png)

Posts screen
![screenshot_912](https://user-images.githubusercontent.com/2078245/47763483-00aa1b80-dd15-11e8-81b0-97ea85d54a39.png)

**To Reproduce**
1. Go to /wp-admin/edit.php?post_type=page
2. Click on the _Quick Edit_ link under a Page title
3. Try to change the Slug

**Expected behavior**
The _Quick Edit_ option should allow me to change the Page slug

**Desktop (please complete the following information):**
- OS: macOS Sierra 10.12.6
- Browser: Firefox Quantum 63.0 (64-bit)
- Version: WP 5.0 Beta 2

**Comment by pento** [comment]
This is fixed in core, now. https://core.trac.wordpress.org/changeset/43855
