### ISSUE TITLE
Reusable Block: Export link missing

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#11275]
**Describe the bug**
5.0 Beta 2 seems to have lost the export link for Reusable block export. 

**To Reproduce**
1. Make a block a reusable block
2. Select "Manage All Reusable Blocks
3. Hover over one of the block titles
5. Look for link "Export as JSON"

**Expected behavior**
On Custom Post Type list view to see next to edit and Trash a link "Export as JSON" 
<img width="223" alt="screen shot 2018-10-31 at 10 38 22" src="https://user-images.githubusercontent.com/39980/47757819-921a7e80-dc7e-11e8-8280-f8d0ed69645f.png">

**Screenshots**
![screen shot 2018-10-30 at 7 53 18 pm](https://user-images.githubusercontent.com/39980/47757831-a0689a80-dc7e-11e8-85d0-b3d60ac5f75d.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Browser Chrome
 - Version 69.0.3497.100

**Comment by pento** [comment]
Ah, I skipped merging that function, I missed that it handled the `wp_block` actions as well as the "Edit in the classic editor" action on other post types.

**Comment by noisysocks** [comment]
I've moved this to Trac since it's a bug in Core and not the plugin:

https://core.trac.wordpress.org/ticket/45247
