### ISSUE TITLE
Convert a classic post with a non-ascii named image to Gutenberg block, breaks the image

### ISSUE THREAD

**Issue by iamgabrielma** [WordPress/gutenberg#11284]
**Describe the bug**
Originally discovered when testing [this other issue](https://github.com/WordPress/gutenberg/issues/10381) .

By creating a post via the classic editor, adding an image with a non-ascii name (in this case `img-nön-ñàsc'íi-แปลภาษา`), and then switching this to Gutenberg editor by clicking on "convert to block" breaks the image.

Also in the front-end seems that the div for the image is not generated: 
<img width="1278" alt="screen shot 2018-10-31 at 13 35 55" src="https://user-images.githubusercontent.com/3812076/47770430-faff0680-dd11-11e8-8ead-30a7858a2b7e.png">

**To Reproduce**
1. Go to Posts , create a new post using the classic editor.
2. Add an image with non-ascii characters, for example `img-nön-ñàsc'íi-แปลภาษา.png`
3. Save the post
4. Go back to your posts, click on the post you're going to edit, select the block and click on "convert to block"
5. See how the image breaks

**Expected behavior**

The image to keep showing up in both the editor and the post

**Screenshots**

<img width="939" alt="screen shot 2018-10-31 at 13 28 28" src="https://user-images.githubusercontent.com/3812076/47770165-ec641f80-dd10-11e8-92c1-f8251c59d363.png">

- WordPress 4.9.8
- Gutenberg 4.1.1

**Comment by johngodley** [comment]
I wasn't able to reproduce this using 4.2.0 RC 1 so it's possible it may have been fixed. Can you try with 4.2?

**Comment by iamgabrielma** [comment]
> I wasn't able to reproduce this using 4.2.0 RC 1 so it's possible it may have been fixed. Can you try with 4.2?

I'm getting a bunch of unrelated errors due to the testing environment and how files are built, will re-test as soon as a new version is deployed in the repo :)

**Comment by youknowriad** [comment]
I'm not able to reproduce this issue. I used the same image name here. please reopen if you still experience the issue.
