### ISSUE TITLE
Gallery: Use stock alignments toolbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1128]
Current toolbar looks like this:

![current](https://user-images.githubusercontent.com/1204802/27010788-44d332b2-4ead-11e7-9396-e96258b32569.png)

We should remove the leftmost button from the control group.

Also, currently the buttons apply the alignments as CSS classes to the `figure` itself. It should be applying the alignments as `data-align`. Let's also be sure to support both `align-wide` and `align-full-width`.

**Comment by mtias** [comment]
Done in #1135.
