### ISSUE TITLE
Only meta boxes visible for some templates.

### ISSUE THREAD

**Issue by luglio7** [WordPress/gutenberg#11289]
Sometimes all I need is hiding the editor and display only the meta boxes since not every post / page in my theme is a collection of blocks (for instance Gutenberg is completely useless for full screen pages with only an image / video displayed and some minimal data).

Are there some php/js filters to hide the blocks editor or i need to code a plugin for that ?

**Comment by ocean90** [comment]
Hello @luglio7, yes there are a few filters that you can use. There was a recent blog post on make/core which covers this: https://make.wordpress.org/core/2018/10/30/block-editor-filters/.

**Comment by luglio7** [comment]
The filter works ok but i need to reload the editor page to make the filter work. Very poor ux
