### ISSUE TITLE
Multiple editor widths

### ISSUE THREAD

**Issue by sebrosen** [WordPress/gutenberg#11288]
I'm trying to define multiple widths for the Gutenberg editor depending on the post/page template. I have a full-width page template and would like the editing experience to be as close to the live page.

Now the issue is that I can only seem to define one width for the editor using the .wp-block class. I'm following this method: https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor

```
.wp-block {
    max-width: 720px;
}
```

I've tried adding a selector in front of the .wp-block class, for example:

```
.wp-block {
    max-width: 720px;
}
.page-template-fullwidth .wp-block {
    max-width:1080px;
}
```

But unfortunately that doesn't work. It seems like the only possible way to change the width is by only using .wp-block

Any ideas on how to implement multiple different editor widths?

Thank you!

**Comment by manake** [comment]
I have the same question. Does anyone know?

**Comment by designsimply** [comment]
I posted an explanation of the current situation and a workaround code example at https://github.com/WordPress/gutenberg/issues/12874#issuecomment-452929053. Please have a look!
