### ISSUE TITLE
Add block transform to sidebar block icon

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#11292]
This request comes most recently from @JJJ in a post written as a test exploration. It has come up in the past though during the block transformation discussions. The block icon in the sidebar has no transformations:

![1](https://user-images.githubusercontent.com/253067/47779577-4c4ace00-dcf1-11e8-9db7-bac905de391e.png)

![2](https://user-images.githubusercontent.com/253067/47779602-671d4280-dcf1-11e8-83cf-67cca49d1064.png)

Potentially by bringing in this more unification happens, however we do end up with a modal complexity in the sidebar and also 2 elements on the same interface doing the same thing. What do people think?

**Comment by ZebulanStanphill** [comment]
How would this affect accessibility? Would it add a redundant control that got in the way of users trying to access other options?

**Comment by mapk** [comment]
I'm not in favor of this idea. I feel like the sidebar includes settings and info pertaining to that specific block. If I want to transform a block, I would go directly to the block itself to make that happen in context to the content on the page.

I'm going to close this, but if I missed anything, please let me know.
