### ISSUE TITLE
Fatal error when publishing a blog post - didi-lite theme

### ISSUE THREAD

**Issue by gena3004** [WordPress/gutenberg#11302]
Using Gutenberg to create a blog post results in a fatal error. 
1. Gutenberg fails to publish a blog post and end up 'hanging'
2. However, the article seems to be partially published, as it can be reached from this page (second article from above): http://www.genialcontent.com/blog/ 
3. But as soon as you click on the article's individual url you get a new page with this error message:
_Fatal error: Call to undefined function lite_continue_reading_link() in /home/ge00002/www/wp-content/themes/didi-lite/functions.php on line 294_

**Comment by earnjam** [comment]
This is a problem in the theme's functions.php file. 

```php
function didi_lite_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= didi-lite_continue_reading_link();
	}
	return $output;
}
```

It should be `didi_lite_continue_reading_link()`

You should report this to the support forum for the theme.

**Comment by gena3004** [comment]
Thank you! I will report it there then
