### ISSUE TITLE
GET requests are not localized

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#11327]
**Describe the bug**
Following up to #10811. `GET` requests are not localized because they don't pass `Accept: application/json` to the server.

Because of the difficulties of determining when a REST request is occurring early enough to support locale switching, the decision was made to use `wp_is_json_request()` which checks for the `content-type` and `accept` headers to determine if this is a JSON request. 

**To Reproduce**
1. Enable a language for your user in Admin → Profile.
2. Load Gutenberg on a post.
3. Observe that the response for the taxonomies endpoint does not return results in the desired language despite `&_locale=user` being included in the URL.

**Expected behavior**
The results to be returned in the user's locale.

**Screenshots**
![user locale](https://user-images.githubusercontent.com/3460448/47812873-dca00780-dd1f-11e8-86fa-18c14714df60.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0

**Additional context**
I'm having trouble getting the labels to be replaced in the UI. As you can see from the screenshot, the hierarchical panel seems to pull the new labels, but the flat panel seems to keep the same labels which were set when preloading? I have verified that the strings for both taxonomies are untranslated in the developer tools.

**Suggested Solution**
Add an `Accept: application/json` header in the `userLocaleMiddleware()` or in the `raw` handler the like `content-type` is. Happy to PR either.

**Comment by aduth** [comment]
>or in the `raw` handler the like `content-type` is.

This makes sense to me. 👍
