### ISSUE TITLE
Allow initialState in withState to be a function

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#11325]
A common pattern is to set the initial state for a component based off of a prop value.

**Describe the solution you'd like**
Be able to pass a function to `withState()` that is called with the component's props to determine the initial state.

**Describe alternatives you've considered**
Using a default value in the component itself.

Happy to submit a PR.

**Comment by tofumatt** [comment]
Sorry, I don't follow, why would you set internal component state based on a prop value? Why not just use the prop value in the component? Could you show a code example of what you're looking for?

**Comment by youknowriad** [comment]
Not sure if it's a good idea to set the initial state according to a prop value. Because the prop value can change later and the initial state won't change in that case.

**Comment by designsimply** [comment]
@TimothyBJacobs I'm going to close this issue for now and note that we can re-open if you find a good code example to illustrate.

**Comment by TimothyBJacobs** [comment]
Sorry, yep. Fine to close with me.
