### ISSUE TITLE
Some toolbar buttons go missing after a block conversion or when switching back from the code editor

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#11339]
I tested with WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and found that when I convert from another block type to a paragraph block or if I switch to the code editor and back some of the writing formatters disappear until I click into the content area again. 

Steps to reproduce:

1. Add a list block.
1. Convert the list block to a paragraph block.

or:

1. Add a paragraph block and write a sentence.
1. In the block toolbar, go to More options > Edit as HTML.
1. In the block toolbar, go to More options > Edit visually.

**Result**: the toolbar buttons for bold, italic, link, and strikethrough go missing until I re-focus onto the content of the block. I expected that all the buttons would still be there even if I change the block type or switch to code editing and back. ([33s](https://cloudup.com/cpsFpcdPerT))

![screen shot 2018-10-31 at 6 01 04 pm](https://user-images.githubusercontent.com/1119271/47825457-9d7db080-dd37-11e8-990b-c2ced9a3e281.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15419&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment]
Re-tested and confirmed using WordPress 4.9.8 and Gutenberg 4.6.1 `master` @ `874321773`. ([19s](https://cloudup.com/cuwYldMyzOq))

**Comment by youknowriad** [comment]
This seems like the correct behavior to me because in all these cases, the caret is not inside the RichText which means we don't really know where to apply the bold/italic/link format.

**Comment by draganescu** [comment]
I tested this with WordPress 5.8 RC2 and Gutenberg 11 and the behavior looks normal since the  focus remains on the button for "options". Since the buttons appear back on focusing the _editable text_ it is expected. Otherwise, consider the bold button still available, what would it act on? Closing for now.

**Comment by abegit** [comment]
I noticed this too in WordPress 5.8.2 (unsure which Gutenberg version)

It happened while I had a 3-column block layout with 1 List Block inside each column.
The lists blocks each had 1-bullet point, and two or three children each. 

A quick workaround for people getting this:

Click on the options ( ⋮ ), then choose "Edit as HTML"
then click the options ( ⋮ ) again, and choose "Edit Visually"

The block probably needs re-initializing to make the text editor options re-appear.
🤷🏻‍♂️
