### ISSUE TITLE
CSS Issues in editor when embedding Instagram

### ISSUE THREAD

**Issue by dankargo** [WordPress/gutenberg#11337]
Sorry I can't quite work out how best to describe this but a few of my website team started reporting this after the latest Gutenberg update was installed.   It's pretty much impossible to carry on writing beyond the embed when this occurs as the editor is not scrollable.   

As you can see, the blocks end up sitting underneath the other meta boxes and the icons on the far right become mis-aligned.

![screenshot 2018-10-31 at 21 51 10](https://user-images.githubusercontent.com/42091466/47821327-39b7af80-dd58-11e8-813d-d8cc74414f31.jpg)
![untitled](https://user-images.githubusercontent.com/42091466/47821328-39b7af80-dd58-11e8-8ef0-14f9cbb71acc.jpg)

**Comment by earnjam** [comment]
Is this in Firefox? 
Sounds kinda like #11221

**Comment by dankargo** [comment]
Sorry I should have said, its in both Safari & Chrome

**Comment by earnjam** [comment]
I'm not able to recreate this issue with latest from `master` branch, or with version 4.1.1.  

Which version of Gutenberg are you using?

What other plugins do you have active? I see a bunch of meta boxes there. 

I tested with Yoast SEO so I'd have a metabox at the bottom, but didn't get any overlap. 
![image](https://user-images.githubusercontent.com/4267290/47858375-5092ec00-ddc2-11e8-97ce-873188be51e2.png)

I also noticed the "Media Settings" section in your screenshot with a toggle to "automatically scale content". Where is that coming from? I don't have that in my vanilla install.

**Comment by designsimply** [comment]
I tested adding an instagram embed to the bottom of a new Gutenberg demo post (so there was content for scrolling) with WordPress 4.9.8 and Gutenberg 4.5.1 and Yoast SEO 9.2.1 (for the meta boxes) and I found that I was able to scroll to the end of the content including the whole embed.

<img src="https://user-images.githubusercontent.com/1119271/49258963-97412980-f3f4-11e8-830e-24dc37c73758.png" width="400">
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=243&action=edit running WordPress 4.9.8 and Gutenberg 4.5.1 using Chrome 70.0.3538.110 on macOS 10.13.6.</sup>

> I also noticed the "Media Settings" section in your screenshot with a toggle to "automatically scale content". Where is that coming from? I don't have that in my vanilla install.

I'm curious about this as well.

@dankargo I also noticed in your screenshots that you had several plugin updates pending. Based on what I see here, a plugin conflict is a likely culprit. It's also possible one of the updates from the plugins will solve the problem. Please try updating your plugins to the latest versions to take advantage of any fixes and then re-open this issue if you're still having trouble after that. If you are still having trouble, it would be good to list your active plugins for reference.
