### ISSUE TITLE
Introduce a new 'wordpress/gutenberg-code-review' GitHub team

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#11331]
If you'd like to receive a ping when there's a pull request ready for code review, please comment here and we'll add you to the team.

For those approving pull requests, the expectations are:

1. TBD
2. TBD
3. TBD

Please also review https://github.com/WordPress/gutenberg/blob/master/docs/reference/repository-management.md#pull-requests

**Comment by desrosj** [comment]
🖐

**Comment by chrisvanpatten** [comment]
👍

**Comment by ajitbohra** [comment]
:hand:

**Comment by danielbachhuber** [comment]
Closing in favor of #13441
