### ISSUE TITLE
Sibling Inserter: caret is misplaced below the search field in Firefox

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#11346]
Steps to reproduce:

1. Using Firefox, add at least one block.
1. Unselect the block by clicking somewhere in the white space on the page.
1. Click on the "Add block" icon (sibling inserter).
1. Click on the search field at the top to give it focus (if it isn't already focused).
1. Note the placement of the caret.

<strong>Result:</strong> I expected the blinking caret to appear inside search box, but the caret is offset (below the search field) when using Firefox.

![misplaced-caret-for-sibling-inserter-in-firefox](https://user-images.githubusercontent.com/1119271/47828697-c73fd300-dd49-11e8-847a-1723ac6148db.gif)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15430&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

**Comment by jorgefilipecosta** [comment]
Hi @designsimply, than you for reporting this issue! I'm not being able to reproduce this issue anymore (tested on firefox as the issue referred that browser), It was probably solved as a side effect of other change. If you are still able to reproduce the problem, feel free to comment/reopen the issue.

**Comment by designsimply** [comment]
👍 tested and confirmed using WordPress 5.2.1 (no active plugins) using Firefox 67.0 on macOS 10.14.5 that the cursor in the block search isn't offset any more.
