### ISSUE TITLE
Gutenberg breaks Thickbox tb_show() iframe

### ISSUE THREAD

**Issue by cwdgservices** [WordPress/gutenberg#11341]
We use an onclick function in our calendar plugin to create a ThickBox popup to the create an event post.  The function now returns a blank gray screen rather than returning the post page.

I am currently using the newest version of both gutenberg and wordpress.

This is the easiest way to replicate.  Create a and enqueue a javascript file with the following. This will open the popup background but does not create the iframe.  If gutenberg is removed everything works fine. It should return the create new page screen but does not.

`var url = "post-new.php?post_type=page&KeepThis=true&TB_iframe=true&add modal=true";
tb_show("Add New Event", url);`

**Comment by designsimply** [comment]
> I am currently using the newest version of both Gutenberg and WordPress.

The newest stable or are you testing beta versions? For reference, the latest stable versions are WordPress 4.9.8 and Gutenberg 4.1.1.

Is your calendar plugin in the https://wordpress.org/plugins/ directory or available to download for testing? (asking just in case)

When you see the problem happen, do any specific errors appear in the Console panel in your browser's Developer Tools?

**Comment by cwdgservices** [comment]
I am running the newest stable versions.  The plugin is not available through wordpress it is a premium plugin.  There are 0 errors in the console.  

After testing a bunch more I found that if I add supports=> array('editor') to the post type it works.  This error occurs only if you disable the editor.

**Comment by vaibhav11dev** [comment]
Hi,

When you have used classic editor then classic editor enqueues thickbox style and script but when you have to use Gutenberg then Gutenberg not enqueue thickbox style and script so you have a need to enqueue thickbox style and script when Gutenberg load. 

In your case when plugin load enqueue thnickbox style and script like this:
```
add_action( 'admin_enqueue_scripts', array( &$this, 'thickbox' ) );
		public function thickbox() {
			add_thickbox();
		}
```
I hope this it's help you.
Thank you

**Comment by youknowriad** [comment]
Looks like this has a good reply. Thanks @vaibhav11dev
