### ISSUE TITLE
Add Menu Button to Gutenberg

### ISSUE THREAD

**Issue by rahulraykor** [WordPress/gutenberg#11351]
In TinyMCE I have created a MCE Button which was displaying menus dynamically. (e.g if user is not logged in then login menu, and if user is logged in then menus as provided by rest api.)

How can I create such plugin in gutenberg?

Attached screenshot for my requirement.

![current](https://user-images.githubusercontent.com/44062085/47838386-3dd5e280-ddd5-11e8-90bf-485ef6d688a8.PNG)

**Before Login:**
![beforelogin](https://user-images.githubusercontent.com/44062085/47838384-3dd5e280-ddd5-11e8-932c-60ee71bdbc98.png)

**After Login:**
![afterlogin](https://user-images.githubusercontent.com/44062085/47838383-3d3d4c00-ddd5-11e8-98dd-16be6ab40221.png)

**Comment by rahulraykor** [comment]
Can anybody please guide me with this?

**Comment by designsimply** [comment]
I noticed that Gutenberg 2.9 added support for pinning plugin items in the main editor header and I think that could work as a better solution for your case. See https://github.com/WordPress/gutenberg/pull/6442 for the original mockups and to see the details of the original implementation. I don't know of a tutorial explaining how to do it, but I do know that the `Jetpack` and `Yoast SEO` plugins have pinned menu items and you might consider looking at those plugins for inspiration.

**Comment by designsimply** [comment]
Closing in favor to ask you to check out #6442 and to please post to https://wordpress.org/support/forum/wp-advanced/ or at https://wordpress.stackexchange.com/ if you find you are still wanting help with advice and direction for the specifics.
