### ISSUE TITLE
List indent works funny 

### ISSUE THREAD

**Issue by GutenDev** [WordPress/gutenberg#11353]
**Describe the bug**
The texts get merged together when hit return key on the indented list. 

**To Reproduce**
1. Take a paragraph block
2. Start creating a list
3. Indent an item of the list
4. Hit Return key
5. Indent the second item too. 
6. Hit Return
6. The texts are merged; 

**Expected behavior**
Should show the list with indented texts. 

**Screenshots**
![gb_list_bug](https://user-images.githubusercontent.com/44389517/47837754-61019180-ddd7-11e8-846d-1ad640866c72.gif)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser [Google chrome
 - Version 70.0.3538.77

**Additional context**
- Gutenberg 4.1.1

**Comment by earnjam** [comment]
I was able to replicate this using Gutenberg v4.1.1, but it looks like it's been fixed in `master`. 

@GutenDev can you test against the latest code from this repo and confirm?

**Comment by earnjam** [comment]
Or actually, you can also use the `v4.2.0-rc.1` tag. Looks like it's fixed there too.

**Comment by GutenDev** [comment]
Hello @earnjam : tried on 4.1.1; same thing: 
![gb4111](https://user-images.githubusercontent.com/44389517/47848900-09285200-ddfa-11e8-94fd-d56c18dffa80.gif)
Fixed on v4.2.0-rc.1 ; we can close this :)
