### ISSUE TITLE
Paragraph with starting 1. (e. g. for dates) not possible

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#11358]
**Describe the bug**
I tried to begin a new paragraph with the current date in German format (1. November 2018). What happens is that as soon as you write `1. ` it will switch the block to a list block with an ordered list and you can’t get it working to be a paragraph with a starting string like `1.`.

In the screenshot following below I also started by writing 01. November 2018 and tried to remove the leading zero (which is usually only used in programming contexts but not written by humans) but that didn’t work either.

**To Reproduce**
1. Add a new block.
2. Write `1.` following by a space.

**Expected behavior**
You should be able to press `CTRL + Z` or `⌘ + Z` to switch back to the paragraph mode while the `1. ` is still visible as regular text instead of being bound to an ordered list.

**Screenshots**
![date-not-as-list](https://user-images.githubusercontent.com/1018979/47849562-63152180-ddd2-11e8-9874-bde465e88fd8.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Safari
 - Version: 12.0 (14606.1.36.1.9)

**Additional context**
- Gutenberg version 4.1.1

**Comment by GlennMartin1** [comment]
Interesting that you bring this up.

Just yesterday I realized I cannot start a paragraph with an asterisk (it creates a bullet point. Turning off the bullet point removes the asterisk. 

My recommendation:
Google Docs and Microsoft Word also auto-insert numbering and bullet points, but if you press backspace immediately after it auto-inserts, it reverts to plain text.

**Comment by ocean90** [comment]
Confirmed in latest master and Chrome. ⌘ + Z is actually working, it reverts the block type but also removes the focus of the block. Once you focus and press a key it transforms the block back to a list.

cc: @iseulde

**Comment by iseulde** [comment]
Yes, I'm aware of this issue. I'll think about a fix. Thanks!
