### ISSUE TITLE
Option to disable color unselections

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#11361]
**Is your feature request related to a problem?**
Currently it seems that there is no easy way of disabling color unselections on a color palette in order to achieve something like this:
![deepinscreenshot_select-area_20181101011250](https://user-images.githubusercontent.com/9055437/47855554-97e2a200-dded-11e8-8b1d-9cfdf5e47899.png)

**Describe the solution you'd like**
Maybe have a prop passed to the `ColorPalette` component  that rejects undefined values (returns the current color value) and also hides the clear button.

**Describe alternatives you've considered**
I have managed to solve the issue by keeping track of current color and also hiding the clear button using CSS but I was hoping for a more standardized approach.

**Comment by designsimply** [comment]
To clarify, you are adding a "Custom Hover" color option to a custom block and would like to prevent anyone from deselecting a color in that case only?

**Comment by amyriounis** [comment]
I would like to have the option to disallow color unselections for a color palette.

**Comment by amyriounis** [comment]
no longer relevant.
