### ISSUE TITLE
Overlying autocomplete placeholder to suggested block icons.

### ISSUE THREAD

**Issue by mayukojpn** [WordPress/gutenberg#11371]
**Describe the bug**
A localized string of a placeholder "Add text or type / to add content" for auto complete field will overlie suggested block icons.

**To Reproduce**
1. Switch site language to Japanese
2. Open Gutenberg Editor
3. Add focus on the bottom of blocks
4. Remove focus
5. Placeholder text will appear on over suggested block icons
6. You might need to adjust window width to see the error

**Expected behavior**
Placeholder should change line and avoid overlying icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/1886443/47865508-c12c1e00-de3f-11e8-9a58-7af984abac3d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- I'm using Gutenberg Version 4.2.0-rc.1

**Comment by designsimply** [comment]
Tested and confirmed that if the placeholder text in a default block is very long, the shortcut inserters on the right will overlap the text. Noting the default text for reference:

> Add text or type / to add content

![screen shot 2018-11-07 at 11 03 43 am](https://user-images.githubusercontent.com/1119271/48150892-27200780-e27d-11e8-9924-3810331606f7.png)
<sup>Seen at alittletestblog.com/wp-admin/post-new.php running WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by talldan** [comment]
The selected blocks have been removed, so this is no longer an issue. Closing.
