### ISSUE TITLE
Using "Keywords" to keep the native block name

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#11370]
Hello,
I'm using WordPress in French but read lots of articles and Tutorials about Gutenberg project in English where Blocks name are the native (English) block name.

When we're using a WordPress in another language than english, it is not easy to find the block as the english name isn't show (it has been translated)

My idea is to automaticcaly add the native name of the block in the `keywords` params of `registerBlockType()`

**Comment by atachibana** [comment]
Also the Slash function has some difficulties for non English user. See #10961.
Incremental search of Slash function is effective and fancy, but not for non-English, especially CJK user.

For example, Japanese user have to type a series of keys to select the Image block (=画像 block)

Japanese off -> `/` -> Japanese on -> `が`,`ぞ`,`う` (`Kana` stands only for a sound) -> `Space` n-times to select `画像` ('Kanji' stands for both meaning and pronunciation) from candidate -> `Enter` 

Keeping native block name is good idea.

**Comment by swissspidy** [comment]
Related discussion: #6633.

**Comment by gziolo** [comment]
#13848 has landed which removes the limit of 3 keywords altogether. Now, the question is how to solve this particular issue. What if we take also the machine-generated name used in the process of the registration, apply some sanitization and include it as a keyword? E.g.:

`core/paragraph` -> `paragraph`
`core/latest-posts` -> `latest posts`
`core-embed/slideshare` -> `slideshare`

**Comment by youknowriad** [comment]
I'd prefer if we start with keywords added manually instead. Some plugins might generate random names for blocks (dynamically) and these names serve as identifiers which means we shouldn't assume they are meaningful.

**Comment by gziolo** [comment]
Adding non-translatable keywords is also an option. We can start with it.

**Comment by mcsf** [comment]
> Adding non-translatable keywords is also an option. We can start with it.

I agree, this seems smaller and more predictable. Riad makes a good point about issues in automated generation of keywords.

**Comment by swissspidy** [comment]
> Adding non-translatable keywords is also an option. We can start with it.

That sounds very dangerous as it might not work for all locales. Keywords simply being a comma separated list (as proposed #6633) is way better as it's more universally applicable.

**Comment by mcsf** [comment]
If #6633 yields a PR, feel free to close this one in favour of it, @swissspidy.

**Comment by gziolo** [comment]
Let's close this issue in favor of #6633.
