### ISSUE TITLE
Page break block preview could better represent its frontend appearance

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11383]
This is what a page break looks like in the editor:

*Selected:*
<img width="690" alt="screenshot 2018-08-14 13 54 00" src="https://user-images.githubusercontent.com/376315/44093084-614ecefa-9fca-11e8-8315-1b7917045ced.png">

*Unselected:*
<img width="655" alt="screenshot 2018-08-14 13 54 06" src="https://user-images.githubusercontent.com/376315/44093097-6b152fba-9fca-11e8-9fba-b31ef21c256a.png">

And this is what it looks like on the frontend, in a few different themes:

**Gutenberg starter theme:**
<img width="636" alt="screenshot 2018-08-20 11 56 52" src="https://user-images.githubusercontent.com/376315/44336958-fba53200-a470-11e8-8826-5787e8ec67ad.png">

**Atomic Blocks**
<img width="624" alt="screenshot 2018-08-20 11 55 06" src="https://user-images.githubusercontent.com/376315/44336970-0233a980-a471-11e8-89ea-c52c8324ea06.png">

**twentyseventeen:**
<img width="551" alt="screenshot 2018-08-20 11 52 18" src="https://user-images.githubusercontent.com/376315/44336981-0d86d500-a471-11e8-8061-10038edd56be.png">

**twentyten:**
<img width="512" alt="screenshot 2018-08-20 11 57 17" src="https://user-images.githubusercontent.com/376315/44336990-14ade300-a471-11e8-9a06-632b11ef28be.png">

In order to follow the design principle of having the editor appearance mimic, as closely as possible, the frontend appearance ("Your block when unselected should preview its contents"), it might be good if we could display it more akin to "Pages: 1 2 3" as seen in the frontend.

**Comment by paaljoachim** [comment]
Hello again Sarah. Should we just close this issue?
