### ISSUE TITLE
Custom Block Works fine in WP4.9.8 and Gutenberg 4.1 but Kills Editor in WP5.0

### ISSUE THREAD

**Issue by spwarner** [WordPress/gutenberg#11385]
I've developed a custom block for my plugin. It works great in WP4.9.8 with recent versions of the Gutenberg plugin (just tested v4.1 and no issue), but when I try using the plugin on WP 5.0 (beta 1 or 2) the editor refuses to load - the page loads with code 200 and has what appears to be normal HTML, but it just shows a white screen with 11 JS errors. If I remove the block from the plugin code, the editor loads fine so it's directly related to the custom block, but I don't have enough JS experience to be able to figure out what the issue is.

1. Install "Conference Scheduler" from the WP Plugins directory and activate.
2. Create a new post with the block editor (or edit an existing one)

**Expected behavior**
The editor should load and the Conference Scheduler block should be available

** Listed JS Errors **
[Error] TypeError: undefined is not an object (evaluating 'xe.parse')
	(anonymous function) (blocks.min.js:2:121545)
	r (blocks.min.js:1:149)
	(anonymous function) (blocks.min.js:1:945)
	Global Code (blocks.min.js:1:955)
[Error] TypeError: undefined is not an object (evaluating 'wp.blocks.setCategories')
	Global Code (post.php:92)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (api-fetch.min.js:1:3675)
	(anonymous function) (api-fetch.min.js:1:4521)
	r (api-fetch.min.js:1:151)
	(anonymous function) (api-fetch.min.js:1:947)
	Global Code (api-fetch.min.js:1:957)
[Error] TypeError: undefined is not an object (evaluating 'wp.apiFetch.use')
	Global Code (post.php:102)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (core-data.min.js:1:5301)
	n (core-data.min.js:1:151)
	(anonymous function) (core-data.min.js:1:947)
	Global Code (core-data.min.js:1:957)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (notices.min.js:1:4338)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:1564)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:1408)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:946)
	Global Code (notices.min.js:1:956)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (editor.min.js:55:49641)
	(anonymous function) (editor.min.js:55:50571)
	n (editor.min.js:1:149)
	(anonymous function) (editor.min.js:1:945)
	Global Code (editor.min.js:1:955)
[Error] TypeError: undefined is not an object (evaluating 'wp.blocks.registerBlockType')
	(anonymous function) (conference-scheduler.build.js:18:30151)
	n (conference-scheduler.build.js:1:162)
	(anonymous function) (conference-scheduler.build.js:18:33666)
	n (conference-scheduler.build.js:1:162)
	(anonymous function) (conference-scheduler.build.js:1:573)
	Global Code (conference-scheduler.build.js:1:582)
[Error] TypeError: Object($.withColors) is not a function. (In 'Object($.withColors)("backgroundColor",{textColor:"color"})', 'Object($.withColors)' is an instance of Object)
	(anonymous function) (block-library.min.js:12:10162)
	n (block-library.min.js:1:155)
	(anonymous function) (block-library.min.js:1:951)
	Global Code (block-library.min.js:1:961)
[Error] TypeError: undefined is not an object (evaluating 'Object(u.select)("core/editor").getBlockSelectionStart')
	(anonymous function) (edit-post.min.js:12:18900)
	Fe (edit-post.min.js:12:16827)
	INIT (edit-post.min.js:12:18849)
	(anonymous function) (edit-post.min.js:12:67036)
	(anonymous function) (edit-post.min.js:12:19856)
	n (edit-post.min.js:1:151)
	(anonymous function) (edit-post.min.js:1:947)
	Global Code (edit-post.min.js:1:957)
[Error] TypeError: undefined is not an object (evaluating 'wp.editPost.initializeEditor')
	(anonymous function) (post.php:1628)

** Tested in Safari 12 and Chrome 70 on Mac OS 10.12 - same results

**Comment by spwarner** [comment]
Just noticed that I'm getting JS errors on every page of the WP admin because of this - only 7 vs the 11 on when the editor is active. The errors are:

[Error] TypeError: undefined is not an object (evaluating 'xe.parse')
	(anonymous function) (blocks.min.js:2:121545)
	r (blocks.min.js:1:149)
	(anonymous function) (blocks.min.js:1:945)
	Global Code (blocks.min.js:1:955)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (api-fetch.min.js:1:3675)
	(anonymous function) (api-fetch.min.js:1:4521)
	r (api-fetch.min.js:1:151)
	(anonymous function) (api-fetch.min.js:1:947)
	Global Code (api-fetch.min.js:1:957)
[Error] TypeError: undefined is not an object (evaluating 'wp.apiFetch.use')
	Global Code (options-general.php:91)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (core-data.min.js:1:5301)
	n (core-data.min.js:1:151)
	(anonymous function) (core-data.min.js:1:947)
	Global Code (core-data.min.js:1:957)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (notices.min.js:1:4338)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:1564)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:1408)
	r (notices.min.js:1:150)
	(anonymous function) (notices.min.js:1:946)
	Global Code (notices.min.js:1:956)
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (editor.min.js:55:49641)
	(anonymous function) (editor.min.js:55:50571)
	n (editor.min.js:1:149)
	(anonymous function) (editor.min.js:1:945)
	Global Code (editor.min.js:1:955)
[Error] TypeError: undefined is not an object (evaluating 'wp.blocks.registerBlockType')
	(anonymous function) (conference-scheduler.build.js:18:30151)
	n (conference-scheduler.build.js:1:162)
	(anonymous function) (conference-scheduler.build.js:18:33666)
	n (conference-scheduler.build.js:1:162)
	(anonymous function) (conference-scheduler.build.js:1:573)
	Global Code (conference-scheduler.build.js:1:582)

**Comment by seankwilliams** [comment]
If it helps reproduce, the first two steps of https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/ (through "Registering the Block") replicate a very similar error, albeit it seems wp-blocks is crashing a bit eralier than the stack trace above. Here's my JavaScript error log:

```
TypeError: xe is undefined[Learn More] blocks.min.js:2:121434
307
https://prismtechstudios.com/wp-includes/js/dist/blocks.min.js:2:121434
r
https://prismtechstudios.com/wp-includes/js/dist/blocks.min.js:1:139
this.wp.blocks<
https://prismtechstudios.com/wp-includes/js/dist/blocks.min.js:1:943
<anonymous>
https://prismtechstudios.com/wp-includes/js/dist/blocks.min.js:1:36
TypeError: wp.blocks is undefined[Learn More] post.php:102:1
TypeError: wp.blocks is undefined[Learn More] modern-footnotes.gutenberg.js:2:5
TypeError: i is undefined[Learn More] editor.min.js:55:129213
TypeError: Object(...) is not a function[Learn More] block-library.min.js:12:10141
window.controllers/Controllers is deprecated. Do not use it for UA detection. ace.js:1:18418
TypeError: s is undefined[Learn More] edit-post.min.js:12:63440 
```

**Comment by spwarner** [comment]
I did use the Handbook as reference when building the block, so this makes a lot of sense.

**Comment by spwarner** [comment]
I upgraded to WP5.0b3 and this issue seems to be resolved. I'll keep monitoring it going forward.
