### ISSUE TITLE
Custom Fields option displays when ACF is enabled

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#11386]
**Describe the bug**
When the Advanced Custom Fields plugin is enabled, the Custom Fields option displays but does not do anything.

**To Reproduce**
1. Install and activate Advanced Custom Fields
2. Set up an ACF Field Group
2. Create a new post
3. Click _Show more tools & options_
4. Select _Options_

**Expected behavior**
The Field Group that you set up should be the only option underneath _Advanced Panels_.

**Actual behaviour**
Both the Field Group and _Custom Fields_ appears underneath _Advanced Panels_.

**Additional context**
See https://github.com/WordPress/gutenberg/issues/3228 and https://github.com/WordPress/gutenberg/pull/11084 for background on _Custom Fields_ in Gutenberg.

This happens because ACF hides the _Custom Fields_ meta box by removing `postcustom` from the list of registered meta boxes. The Classic editor will not show the _Custom Fields_ meta box when `postcustom` is not registered. Gutenberg, conversely, will show _Custom Fields_ whenever the current post type supports `custom-fields`.

**Comment by elliotcondon** [comment]
Hi @designsimply 

Thanks for the screenshots - very clear.

Yes, we provide a setting to remove the "Default custom fields metabox" like so:
https://github.com/AdvancedCustomFields/acf/blob/a0c931588e7ed60b09f566249d820ab055fb89a2/includes/forms/form-post.php#L149-L151

It will be important to note that we run this code during the "add_meta_boxes" action with a priority of 10. Perhaps this is "after" WP has localized data for Gutenberg?

**Comment by pento** [comment]
The more accurate test would be for `hasCustomFieldsSupport` to be set based on whether the `postcustom` meta box is registered or not.

https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/options-modal/meta-boxes-section.js#L47

Core and `gutenberg_collect_meta_box_data() both do a `post_type_supports( $post_type, 'custom-fields' )` before registering it, so that ensures the current check still happens. We'll need to shuffle a few things around to ensure the check happens after `add_meta_boxes`, but I don't think there are any critical issues there.

**Comment by noisysocks** [comment]
> The more accurate test would be for hasCustomFieldsSupport to be set based on whether the postcustom meta box is registered or not.

This won't work because because we don't register the `postcustom` meta box when the _Custom Fields_ option is turned off.

https://github.com/WordPress/gutenberg/blob/dd015c994306c59687b54d28738330d36178c286/lib/meta-box-partial-page.php#L125-L128

**Comment by noisysocks** [comment]
Let me clarify some stuff so that we're all on the same page.

Before https://github.com/WordPress/gutenberg/pull/11084:
- Gutenberg would always prevent `postcustom` from being registered.
- The Custom Fields meta box would appear if `postcustom` is registered. (In other words: never.)
- The Custom Fields option would appear underneath _Advanced Panels_ if `postcustom` is registered. (In other words: never.)

After https://github.com/WordPress/gutenberg/pull/11084:
- Gutenberg will prevent `postcustom` from being registered iff the `enable_custom_fields` user meta is set. This means that we're not initialising meta boxes or their assets for a default Gutenberg installation which is the case that we want to optimise for, see https://github.com/WordPress/gutenberg/pull/10676#issuecomment-430967687.
- The Custom Fields meta box would appear if `postcustom` is registered. (In other words: when they're enabled.)
- The Custom Fields option would appear underneath _Advanced Panels_ if the current post type supports `custom_fields`. (In other words: for posts and pages.)

ACF removes the WordPress Custom Fields meta box by calling `remove_meta_box`, which is fine, except that we no longer look at that setting when determining if the Custom Fields option should appear underneath _Advanced Panels_.

One potential fix would be for ACF to call `remove_post_type_support( 'post', 'custom_fields' );` in addition to `remove_meta_box` here:

https://github.com/AdvancedCustomFields/acf/blob/a0c931588e7ed60b09f566249d820ab055fb89a2/includes/forms/form-post.php#L149-L151

> Okay, how about we register the postcustom meta box all the time, but switch the __back_compat_meta_box flag based on whether we intend for it to be shown in the block editor or not? This flag would correspond to the inverse of whether the Custom Fields option is switched off.
>
> If a plugin then removes the postcustom meta box, we remove the Custom Fields option entirely.

This could work, though we'd have to change how meta boxes are initialised because right now `__back_compat_meta_box` is not exposed to the Gutenberg frontend.

Gutenberg only knows whether a meta box is registered or not. There's currently no way for the server to express "I know about this meta box, but I didn't render it" which is what is needed in the case that Custom Fields is registered (i.e. ACF is disabled) but disabled (i.e. `enable_custom_fields is off).
