### ISSUE TITLE
Code block should show invisible characters

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11380]
In order to make it easier for people to write code in the code block and see what they're doing, it would be nice to show invisible characters (spaces, tabs, returns, etc) in a subtle way, like (most) code editors do. 

Additionally, it would be good if we could allow people (especially WordPress people) to type tabs into the field, but I suspect this would cause some accessibility headaches and thus totally isn't worth it.

**Comment by paaljoachim** [comment]
Hey Sarah.

It looks like this issue got forgotten about.
What should we do with it?

Have a great day!

**Comment by holzee** [comment]
Needed for code blocks. Would love to have invisible characters in paragraph blocks too. Would be helpful for editing ! (Non-breaking spaces i.e.).

**Comment by mtias** [comment]
For code blocks, this will probably be part of syntax highlighting (https://github.com/WordPress/gutenberg/issues/5614, https://github.com/WordPress/gutenberg/issues/10423) more than a change on the block itself. Not planning on adding this for paragraph, but could be a cool plugin.
