### ISSUE TITLE
Example in Readme on creating blocks does not work

### ISSUE THREAD

**Issue by larsemil** [WordPress/gutenberg#11390]
**Describe the bug**
I am trying to make a simple block for Gutenberg. Doing this I am following the steps outlined [here](https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/).
After doing the first page, and activating the plugin it does show up as a block in Gutenberg. 
But an error in the console is shown and Gutenberg crashes. 
The error is:
`Unhandled promise rejection TypeError: "l is undefined"`
and 
`Unhandled promise rejection TypeError: "w is undefined"`

And ultimatly Gutenberg crashes with: `The editor has encountered an unexpected error.`

**To Reproduce**
Create a plugin with following content: 

***file.php***
```
<?php
/**
 * @package Testplugin
 */
/*
Plugin Name: Testplugin
Plugin URI: testplugin
Description: Testplugin

*/


add_action('init', function() {
   /*wp_register_script(
       'gutenberg-latest-posts-with-thumbs',
       plugins_url('assets/main.js',__FILE__),
       array('wp-blocks', 'wp-element')

   );
   register_block_type(
       'gutenberg-latest-posts-with-thumbs/posts',
       array(
           'editor_script' => 'gutenberg-latest-posts-with-thumbs'
       )
   );
*/
    wp_register_script(
        'gutenberg-boilerplate-es5-step01',
        plugins_url( 'assets/main.js', __FILE__ ),
        array( 'wp-blocks', 'wp-element' )
    );

    register_block_type( 'gutenberg-boilerplate-es5/hello-world-step-01', array(
        'editor_script' => 'gutenberg-boilerplate-es5-step01',
    ) );

});
```
and create a file **assets/main.js** (create the folder!)
```
var el = wp.element.createElement,
  registerBlockType = wp.blocks.registerBlockType,
  blockStyle = { backgroundColor: '#900', color: '#fff', padding: '20px' };

registerBlockType( 'gutenberg-boilerplate-es5/hello-world-step-01', {
  title: 'Hello World (Step 1)',

  icon: 'universal-access-alt',

  category: 'layout',

  edit: function() {
    return el( 'p', { style: blockStyle }, 'Hello editor.' );
  },

  save: function() {
    return el( 'p', { style: blockStyle }, 'Hello saved content.' );
  },
} );
```

**Expected behavior**
I expect the block to show up, with no errors. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 62.0.3

**Additional context**
I am using WordPress 5.0 beta 2.

**Comment by kkarpieszuk** [comment]
Update: there is also error in Chrome. To encounter it:
- insert my registered block (it will be inserted correctly)
- switch from Chrome window to another one with ctrl+tab and switch back. 

You will see same error in browser window, but in console the error is different (attached log from Chrome)
[localhost-1542317783793.log](https://github.com/WordPress/gutenberg/files/2587135/localhost-1542317783793.log)

**Comment by kkarpieszuk** [comment]
@larsemil are you able to edit the ticket title? Now it doesn't sound as serious as it is. I propose 

> "The editor has encountered an unexpected error" when registering new blocks

**Comment by kkarpieszuk** [comment]
@danielbachhuber @designsimply is there a chance this will be handled? I am really stuck, I don't know whether the documentation is wrong or something: you simply cannot create custom blocks now, according to Gutenberg handbook

**Comment by larsemil** [comment]
I am pretty sure the official documentation and tools are not up to date to the RAPID speed that GutenBerg is being developed in right now. I will sit tight fore a while and I am sure this will pan out. 

If i would need to build a block now, I would look how its made in the WordPress Core blocks.

**Comment by nosolosw** [comment]
Tutorials have been rewritten/updated in the past months and the example mentioned is working. Thanks for reporting!

**Comment by kkarpieszuk** [comment]
thank you very much!
