### ISSUE TITLE
Unified toolbar + sidebar obscures permalink on small screen

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11398]
If you have the unified toolbar option enabled, the sidebar opened, and try to edit the post permalink a blank toolbar can obscur the permalink field.

Here's a post with the unified toolbar, the sidebar, and the caret is focussed in the post title so the permalink area appears:

![edit_post_ _wordpress_latest_ _wordpress_and_new_issue_ _wordpress_gutenberg](https://user-images.githubusercontent.com/1277682/47910898-1aba3a00-de8c-11e8-9140-9e3c51a3dd45.jpg)

Here I reduce the window width below 1080 (seems to be the break point) and a blank section appears that obscures the title:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47910932-345b8180-de8c-11e8-819c-5ddb9c5266f5.jpg)

**Expected behavior**
The empty bar to not appear (if possible), or the permalink to drop down.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Gutenberg: 4.2

**Comment by designsimply** [comment]
Tested and confirmed from an iPad Mini that the unified toolbar placeholder obscures the permalink options for a saved post (in landscape mode but portrait mode does not have the unified toolbar option).

![img_0006](https://user-images.githubusercontent.com/1119271/47935147-05024000-de9f-11e8-9873-99d1a400388b.PNG)

<img src="https://user-images.githubusercontent.com/1119271/47935154-07649a00-de9f-11e8-9ae6-301e06622111.PNG" width="440">

Screenshots comparing when the title has focus to when a block has focus:

<img alt="screen shot 2018-11-02 at 12 40 20 pm" src="https://user-images.githubusercontent.com/1119271/47934552-24986900-de9d-11e8-847c-068488b90d62.png" width="300"> <img alt="screen shot 2018-11-02 at 12 40 57 pm" src="https://user-images.githubusercontent.com/1119271/47934558-2bbf7700-de9d-11e8-930f-d041b83922b1.png" width="300">

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15471&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

**Comment by mtias** [comment]
With the permalink available on the document panel, I think we can close this. In the future, the permalink will be removed from the title as well.
