### ISSUE TITLE
In Editor Inserter Menu, please capitalize 'Page break'

### ISSUE THREAD

**Issue by shinyabw** [WordPress/gutenberg#11402]
**Describe the bug**

In 'Layout Elements' of Editor Inserter Menu, please fix **Page break** to **Page Break**. Since **Lates Posts** is spelled both words capitlized, **Page Break** should follow the same style.

**To Reproduce**
1. Go to 'Layout Elements of Editor Inserter Menu'
2. See error

**Expected behavior**

**Page break** should be spelled as **Page Break**.

**Screenshots**

![page-break](https://user-images.githubusercontent.com/36391308/47913717-757d8100-dee0-11e8-89de-1b9799cf8787.jpg)

**Desktop (please complete the following information):**
 - OS: [Mac 10.13.6]
 - Browser [Firefox]
 - Version [63.0.1]

**Additional context**
- 4.2.0-rc.1
- WP.org shinyab

**Comment by Soean** [comment]
Hey @shinyabw 
it's already fixes in #11384, so it should be included in Gutenberg 4.3.

**Comment by shinyabw** [comment]
Hi @Soean. Yes, I see that. Thank you!
