### ISSUE TITLE
Categories and tags missing

### ISSUE THREAD

**Issue by davidkingham** [WordPress/gutenberg#11417]
The categories and tags are completely missing from posts in gutenberg. I have disabled all plugins besides gutenberg and have turned off any rerouting in cloudflare so all my A records are DNS only. There are no errors in the console, just messages. What else can I try?

![image](https://user-images.githubusercontent.com/35718296/47926155-80ef8e80-de85-11e8-8b04-bcac588b5b5a.png)

![image](https://user-images.githubusercontent.com/35718296/47926105-5e5d7580-de85-11e8-9ba9-bf6ad16f90b0.png)

 - OS: Windows 10
 - Browser: chrome/firefox
- Gutenberg 4.1.1

**Comment by mtias** [comment]
That panel looks like a page, not a post?

**Comment by davidkingham** [comment]
Sorry, it is a page, but the problem still remains that those are missing due to gutenberg

**Comment by designsimply** [comment]
I tested creating a new post using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6 just now and I found that I can see Categories and Tags in the settings sidebar:

![screen shot 2018-11-02 at 2 03 10 pm](https://user-images.githubusercontent.com/1119271/47937964-1c91f680-dea8-11e8-849b-9b98cfc9a6f6.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

@davidkingham if you are using custom code to add category taxonomies as @ocean90 suggested, then ignore this comment and please do include code examples if possible. 🙂

**Comment by youknowriad** [comment]
Are you "admin" on your website? we recently fixed a bug related to taxonomies for contributors.

**Comment by davidkingham** [comment]
I realized that categories are not a default option in wordpress for pages.
I have a plugin that reveals them but does not work in gutenberg. This can
be closed.

**Comment by tejashweta** [comment]
I am not able to see Category and Tag in My Admin. Please help

![image](https://user-images.githubusercontent.com/13874662/74607597-33da0f00-5100-11ea-9255-d7c2c361c29c.png)
