### ISSUE TITLE
Post edit screen is nothing but white, completely blank

### ISSUE THREAD

**Issue by cjontheschuylkill** [WordPress/gutenberg#11412]
**Describe the bug**
Installed Gutenberg 4.1.1 into WordPress 4.9.8. As others have reported elsewhere, when trying to edit a post, I get a plain white screen (a completely blank browser tab). 

**To Reproduce**
Click on "Edit Post" on the Posts page. 

**Expected behavior**
I should be presented with some form of an editing screen. Instead, it is completely blank -- no sidebar, graphics, or anything of any kind. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6
 - Browser Firefox 63.0.1 and Chrome 70.0.3538.77 both display this behavior for me.

**Additional context**
I have read and executed previous suggestions to clear my caches or to flush the rewrite rules. These have made no difference for me. Deactivating Gutenberg returns me to normal editing. Activating or deactivating the Classic Editor plugin doesn't seem to matter; the Gutenberg editor doesn't work either way. If there is a plugin conflict, I am not getting an error code to help me isolate it.

**Comment by GlennMartin1** [comment]
I rarely have this happen, though it sporadically occurs (guessing maybe once every 20 editor loads).
I've never been able to create reproducible steps.
It's always worked to Refresh the page in the browser.
This has been for the past several months, always running most up-to-date plugin version.

Not much help - but.......

**Comment by cjontheschuylkill** [comment]
Thanks. I've tried to refresh, it doesn't make any difference. That it behaves this way in both browsers I use makes me feel like it has to be a conflict within WP itself.

**Comment by designsimply** [comment]
@cjontheschuylkill thanks for writing in! You mentioned that you're not getting an error code. May I double check with you that you were looking at the Console panel in your browser's developer tools and that it was open at the time you tried to load (or reload) a post? 

Would it be possible to get a list of your active plugins for reference?

Could you talk a little more about your web server setup? Are you using nginx or Apache or something else? Have you made modifications to any of the configuration files or do you have any tools such as ModSecurity which could be blocking the WordPress API?

**Comment by cjontheschuylkill** [comment]
designsimply, thanks for the response and the guidance. I'm not a developer or coder and haven't run through these problems in a while, so what I meant was that it wasn't throwing a code at me. Given your advice, I turned on the console and think probably the problem is somehow a missing file or a script problem, as I get this:

JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542
Loading failed for the <script> with source “http://hoxsie.org/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js”. post.php:86:1
ReferenceError: regeneratorRuntime is not defined[Learn More] index.js:1:2710
TypeError: wp.apiFetch is undefined[Learn More] post.php:118:1
ReferenceError: regeneratorRuntime is not defined[Learn More] index.js:1:12796
ReferenceError: regeneratorRuntime is not defined[Learn More] index.js:1:5651
ReferenceError: regeneratorRuntime is not defined[Learn More] index.js:50:59817
TypeError: Object(...) is not a function[Learn More] index.js:12:7994
TypeError: Object(...)(...) is undefined[Learn More] index.js:12:18179
TypeError: wp.editPost is undefined[Learn More]

Does it look to you like that initial script is failing to load, and that could be my problem? 

As for the web server setup, I'm using a stock installation on Arvixe, meaning I have no idea. It's Apache 2.2.31, and I don't believe I have added any security (other than through WP plugins) that would be a problem. I've tried turning off all the plugins (not removing them, just deactivating) and that hasn't made a difference.

**Comment by MKretsche** [comment]
Hello,
By activating Gutenberg the already setup pages have been deleted / deactivated / no longer availabel through browser. By deactivating, the pages where available again. 
Is it possible to activate Gutenberg without this effect? How can I start with Gutenberg on runnig pages?
Regards, M Kretsche

**Comment by designsimply** [comment]
> Loading failed for the <script> with source “.../wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js”. post.php:86:1

This is helpful. In my experience, this error happened when one of the web hosts I was testing on had a `mod_security` rule blocking that `wp-polyfill-ecmascript.min.2ae96136.js` file. However, an update was made in #11216 to try to avoid that problem and it was included in version 4.3.

I can't be sure without confirmation from you, but I think this issue has been resolved. May I ask that you please update to the latest version of Gutenberg (currently 4.5.1) and try testing again and re-open this issue if you're still having any trouble?

**Comment by designsimply** [comment]
> By activating Gutenberg the already setup pages have been deleted / deactivated / no longer available through browser. By deactivating, the pages where available again.

@MKretsche this sounds like a separate case and my first guess would be to try to rule out the theme as a problem. Can you please try temporarily switching to the default theme (Twenty Seventeen) and check to see if the problem goes away? If it does, please report the problem to the theme author. If the problem persists, please open a new issue here and include information such as the versions of WordPress, Gutenberg, OS, and browser you are using and a list of your active plugins for reference. Thank you!

**Comment by cjontheschuylkill** [comment]
> > Loading failed for the <script> with source “.../wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js”. post.php:86:1
> 
> This is helpful. In my experience, this error happened when one of the web hosts I was testing on had a `mod_security` rule blocking that `wp-polyfill-ecmascript.min.2ae96136.js` file. However, an update was made in #11216 to try to avoid that problem and it was included in version 4.3.
> 
> I can't be sure without confirmation from you, but I think this issue has been resolved. May I ask that you please update to the latest version of Gutenberg (currently 4.5.1) and try testing again and re-open this issue if you're still having any trouble?

THANKS! I did update (today it's 4.6.0 -- moving fast!), and as of now it is working.

**Comment by deepaksyal** [comment]
Please check your console there is an error $ is not a function in your gutenberg_integration.bundle.js file.

Just put your code in :

jQuery(document).ready(function ($) {
    // Your code here
});

Because jQuery provides the global jQuery object (which is present on your page). You can do the following to "get" $ back.

**Comment by lordspace** [comment]
I am experiencing the same problem at the moment on a fresh WP install with WooCommerce + 2020 theme installed.
The only thing that fixed it was this is to disable the block editor.
I suspect the block editor wasn't fully tested with the very latest php version.

`add_filter('use_block_editor_for_post', '__return_false');`

here's a video:
https://www.loom.com/share/646416518d774db3acb74be0bcba396a?from_recorder=1

> qs_error: Wed, 21 Oct 2020 13:14:48 +0000 [id:2dd26d369ebf20625e28147bb0a4a327bff3c8c3/127.0.0.1] object(Error)#4 (7) {
>   ["message":protected]=>
>   string(51) "Call to undefined function wp_get_ready_cron_jobs()"
>   ["string":"Error":private]=>
>   string(0) ""
>   ["code":protected]=>
>   int(0)
>   ["file":protected]=>
>   string(116) "/wpdemo.net/htdocs/wp-cron.php"
>   ["line":protected]=>
>   int(79)
>   ["trace":"Error":private]=>
>   array(0) {
>   }
>   ["previous":"Error":private]=>
>   NULL
> }
> 
> 
> 
>  php -v
> PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
> 
> 
>  wp --info
> OS:     Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
> Shell:  /bin/bash
> PHP binary:     /usr/bin/php7.4
> PHP version:    7.4.3
> php.ini used:   /etc/php/7.4/cli/php.ini
> WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
> WP-CLI vendor dir:      phar://wp-cli.phar/vendor
> WP_CLI phar path:       /wpdemo.net
> WP-CLI packages dir:
> WP-CLI global config:
> WP-CLI project config:
> WP-CLI version: 2.4.0

**Comment by MKretsche** [comment]
Hello,

 

thank you for the given information.

 

Meanwhile everything looks as if no problem occurs anymore.

 

Greetings

Meinhard

 
 

Gesendet: Mittwoch, 21. Oktober 2020 um 15:51 Uhr
Von: "Svetoslav Marinov" <notifications@github.com>
An: "WordPress/gutenberg" <gutenberg@noreply.github.com>
Cc: "MKretsche" <kraetzschmer@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Post edit screen is nothing but white, completely blank (#11412)


 

I am experiencing the same problem at the moment on a fresh WP install with WooCommerce + 2020 theme installed.
The only thing that fixed it was this is to disable the block editor.
I suspect the block editor wasn't fully tested with the very latest php version.

add_filter('use_block_editor_for_post', '__return_false');

here's a video:
https://www.loom.com/share/646416518d774db3acb74be0bcba396a?from_recorder=1


qs_error: Wed, 21 Oct 2020 13:14:48 +0000 [id:2dd26d369ebf20625e28147bb0a4a327bff3c8c3/127.0.0.1] object(Error)#4 (7) {
["message":protected]=>
string(51) "Call to undefined function wp_get_ready_cron_jobs()"
["string":"Error":private]=>
string(0) ""
["code":protected]=>
int(0)
["file":protected]=>
string(116) "/wpdemo.net/htdocs/wp-cron.php"
["line":protected]=>
int(79)
["trace":"Error":private]=>
array(0) {
}
["previous":"Error":private]=>
NULL
}

php -v
PHP 7.4.3 (cli) (built: Oct 6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

wp --info
OS: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
Shell: /bin/bash
PHP binary: /usr/bin/php7.4
PHP version: 7.4.3
php.ini used: /etc/php/7.4/cli/php.ini
WP-CLI root dir: phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir: phar://wp-cli.phar/vendor
WP_CLI phar path: /wpdemo.net
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

**Comment by lordspace** [comment]
Thanks for checking this.  I decided to turn off the plugins and see if there's a chance for a WooCommerce bug and submitted a bug report there too
https://github.com/woocommerce/woocommerce/issues/28051
