### ISSUE TITLE
Extra history entries created when calling setAttributes()

### ISSUE THREAD

**Issue by meatwad5675** [WordPress/gutenberg#11414]
**Describe the bug**
I'm working on a custom block with an editor panel with some inputs that trigger calls to setAttributes when changed.  When calling setAttributes() from my custom component, redux dev tools shows the UPDATE_BLOCK_ATTRIBUTES and EDIT_POST actions being called, each of which is adding an entry to the editor.past slice of the state.  This is quickly followed by some post update related actions and then DIRTY_ARTIFICIALLY, which also adds an entry to the editor.past slice of state.  So a single call to setAttributes() is resulting three undo-able steps, only one of which actually effects an attribute.

**To Reproduce**
My work isn't publicly accessable, and I haven't tried to create a vanilla custom block to replicate.

**Expected behavior**
I expected a single call to setAttributes() to result in a single history entry.

**Screenshots**
https://goo.gl/D2Rzfu

*Note on that screen capture that there were 3 separate clicks on the undo button.

**Desktop (please complete the following information):**
 - Mac OS 10.12.6
 - Chrome
 - 69.0.3497.100

**Comment by designsimply** [comment]
Adding a screenshot pulled from the video in case it's helpful:

![screen shot 2018-11-02 at 4 48 40 pm](https://user-images.githubusercontent.com/1119271/47944117-4c98c400-debf-11e8-9a0f-a9497f6a8edb.png)

(Asking just in case) @meatwad5675 can you think of a way to trigger this problem without using a custom block so it's something that could be tested more easily? If not, no worries, I may not be fully understanding the complexity of it.

**Comment by youknowriad** [comment]
I think `DIRTY_ARTIFICIALLY` has been removed and this issue seems fixed now.
