### ISSUE TITLE
Overlap text and quick blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11425]
**Describe the bug**
Add image. Align it left. Quick block text is seen below text.

**To Reproduce**
1. Add image block and image.
2. Align it left.
3. Notice the quick blocks are seen below the text on the right when selecting the block.

**Expected behavior**
I did not expect to see the I call them quick blocks below the text.

**Screenshots**
![screen shot 2018-11-02 at 17 31 01](https://user-images.githubusercontent.com/5323259/47928163-b4eaa400-dec5-11e8-8159-cdf086e81ebf.png)

**Desktop (please complete the following information):**
 - OS: OS 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg version 4.1.1

**Comment by designsimply** [comment]
Tested and confirmed and noting that I only see the default block text "Add text or type / to add content" overlap with the default block placeholder if it is unselected and the mouse is also hovering over the same empty block. ([19s](https://cloudup.com/cv3v7bmU_84))

<sup>Tested using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 with Firefox 63.0 on macOS 10.13.6.</sup>

This feels like a bit of an edge case to me so I'm going to add the `Needs Design Feedback` label to check in about that.

**Comment by Zodiac1978** [comment]
This is a general problem and especially for translated text which is (in German) mostly longer than in English (assume a factor if 1.5):
![bildschirmfoto 2018-11-16 um 10 55 33](https://user-images.githubusercontent.com/870475/48615032-08fa8b80-e990-11e8-9234-a501d42eaed0.png)

**Comment by jasmussen** [comment]
Good ticket. Created a fix in https://github.com/WordPress/gutenberg/pull/12536.
