### ISSUE TITLE
Aligning image left and quote beside it. Quote lines shows up under image.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11421]
**Describe the bug**
The quote black vertical line shows up below image.

**To Reproduce**
1. Add an image block with an image. Align it left.
2. Add an quote block with a long quote in it.
3. The quote should show up on the right.
4. The line shows up under the image beside the quotation.

**Expected behavior**
I expected the quote vertical line to show up beside the quote to the right of the image.

**Screenshots**
![screen shot 2018-11-02 at 17 18 49](https://user-images.githubusercontent.com/5323259/47927500-c3d05700-dec3-11e8-8384-1c656908fbf4.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser Chrome with Desktop server
 - Gutenberg version 4.1.1

**Comment by youknowriad** [comment]
Floating in general in the web is weird and that's just a consequence of it. Not sure we can do much about it.

**Comment by designsimply** [comment]
Tested and confirmed that an image block floated left next to a quote block results a little bit of overlap for the black line on the left of quote blocks in the editor view.

![screen shot 2018-11-07 at 3 34 37 pm](https://user-images.githubusercontent.com/1119271/48165474-f2bf4200-e2a2-11e8-969e-c1996d377d35.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15622&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 .</sup>

Note: there is some work in progress at #11357 relating to floats that may be relevant.

**Comment by jasmussen** [comment]
This is not an issue with Gutenberg specifically, this is an issue with HTML and floats in general, as demonstrated by this codepen: https://codepen.io/joen/pen/PxZgGM?editors=1100

For that reason, I'm going to close it as a quirk of how floats behave. It's a frustrating quirk, but it is nonetheless not Gutenberg specific.
