### ISSUE TITLE
Image & Audio: Auto switch to Embed for embeddable URLs

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#11427]
**Description**
The PR #11410 switches the Video block to Embed, if the user tries to add a embeddable URL like YouTube or Vimeo.
We should also add this feature to the Image block if the user tries to add a URL like Instagram and to the Audio block if the user tries to add a URL like SoundCloud.

**Comment by alexislloyd** [comment]
This seems like a good user flow to me — aligns to user expectations and creates a consistent experience across blocks.
