### ISSUE TITLE
Components: Improve Popover computations

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#11430]
The following comments should be resolved or addressed:

- [x] 1.

> What about:
> 
> > Where are we canceling this timeout if the component is unmounted?

https://github.com/WordPress/gutenberg/pull/6799#discussion_r200995990

**Edit:** Addressed in #8218

---

- [ ] 2.

> This is treating the symptom, not the cause, and the comment reads as such.
> 
> The real cause is a combination of:
> 
> * When initially mounted, the popover doesn't have a Slot context in which to render. When this becomes available, it re-renders the content into the slot (an unmount and remount operation).
> * When initially mounted, the container has a style of `visibility: hidden`, so focusing would not select the container.

https://github.com/WordPress/gutenberg/pull/6799#discussion_r206211471

---

- [ ] 3.

> Related to [earlier comment](https://github.com/WordPress/gutenberg/pull/6799/files#r206211471), we shouldn't need to check this here. If the component causes `Popover#focus` to be called during its `componentDidMount`, we should be able to assume that the `ref.current` is assigned.

https://github.com/WordPress/gutenberg/pull/6799#discussion_r206268120

---

- [x] 4.

> It took me more than a minute to grasp why this condition is here. It seems obvious in retrospect, but a comment would have been nice.

https://github.com/WordPress/gutenberg/pull/6799#discussion_r230457616

**Comment by youknowriad** [comment]
Closing this issue as the Popover component changed a lot, most of these are not relevant anymore.

**Comment by aduth** [comment]
I updated the original comment. Only the last is invalid. The second and third are still problems.

**Comment by ciampo** [comment]
Regarding points no. 2 and 3 from the issue's description, it looks like the main issue being discussed was around focus management (and in particular, moving the focus to the first tabbable element inside the popover).

It looks like thie feature is now achieved through the [`useDialog` hook](https://github.com/WordPress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/compose/src/hooks/use-dialog/index.js), which internally relies on the [`useFocusOnMount` utility hook](https://github.com/WordPress/gutenberg/blob/0fda589889b37f9a495949ccd68cce4d61875117/packages/compose/src/hooks/use-focus-on-mount/index.js#L28).

I believe we can close this issue  (of course, @aduth, feel free to reply in case you think I missed something!)
