### ISSUE TITLE
Classic Editor Block WPLINK plugin is not working as expected

### ISSUE THREAD

**Issue by turtlepod** [WordPress/gutenberg#11432]
**Describe the bug**
Classic Editor Block WPLINK plugin is not working (Gutenberg Version 4.1.1/WordPress 4.9.8
)

**To Reproduce**

1. Create classic editor block
2. Create link (using advance option/gear icon)

Video: https://drive.google.com/file/d/1al5ZWiauy0Dwa9XtjKXQx01XMa7kHHD4/view?usp=sharing

**Expected behavior**
not broken

**Screenshots**
Video: https://drive.google.com/file/d/1al5ZWiauy0Dwa9XtjKXQx01XMa7kHHD4/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 70

**Comment by designsimply** [comment]
Thanks for reporting this and for testing with the latest plugin version! We are already tracking this issue at https://github.com/WordPress/gutenberg/issues/7932 so I am closing this one as a duplicate and will make a note there.
