### ISSUE TITLE
To add a block after the last used block(s)

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11445]
**Is your feature request related to a problem? Please describe.**
I am on the second to last block. A paragraph block aligned to the left. 
There is an image beside it aligned to the left.

![screen shot 2018-11-03 at 12 26 15](https://user-images.githubusercontent.com/5323259/47951650-e7e37500-df63-11e8-8f0a-18d95d2e797b.png)

I have tried multiple times to just click below the last block expecting that a paragraph block would show up. That does not happen.

So I click below the last block and very cleverly done the cursor goes to after the last word in the last paragraph block. There I can click enter and do so. A block shows up just below the words to the right of the image. Which can be a good or bad thing depending on if one wants to continue with more text beside the image. BUT I want to add text below the image. I can continue to click enter a few more times so that a new block is added below the image. But then I get all the extra paragraph areas to the right of the image that I do not need.

![last-block](https://user-images.githubusercontent.com/5323259/47951726-ed8d8a80-df64-11e8-8eb7-b7a78e7e422d.gif)

**Describe the solution you'd like**
I would like to have a simple way to add a block below the text AND image. 

Perhaps just as simple as adding the inserter at the bottom like so:

![inserter-after-last-block](https://user-images.githubusercontent.com/5323259/47951782-c71c1f00-df65-11e8-9501-c2324eac05d0.jpg)

Or clicking into the empty area after a block could also bring up the quick add block bar (do not remember what it is called again.) Instead of adding the focus to the last block.

![click-below-last-block](https://user-images.githubusercontent.com/5323259/47951887-68f03b80-df67-11e8-8677-dd72773ffac3.jpg)

If I want to add additional text beside the image then I can click into the last paragraph block after the last word and click enter to add another block just below and beside the image.

![screen shot 2018-11-03 at 12 44 18](https://user-images.githubusercontent.com/5323259/47951833-9e485980-df66-11e8-9969-da2accd9ac61.png)

There is no intuitive way to add another block at the end after all blocks that are used in the layout.
Atleast not that I am noticing at present.

**Comment by ocean90** [comment]
Related: #11329

**Comment by paaljoachim** [comment]
What about a large clickable hot spot below the last block to automatically have the inserter show up?
As there are clickable hot spots today that are very subduded/sublime. Not easy to grasp.
https://github.com/WordPress/gutenberg/issues/11468

**Comment by paaljoachim** [comment]
I will close this issue, as I believe along the line that it has been taken care of.
