### ISSUE TITLE
Audio controls not visible on the frontend - bug-

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11447]
**Describe the bug**
I made a page with various paragraph, image and audio blocks.
The audio controls are not showing up on the frontend.

**To Reproduce**
1. In this case I added the audio controls, just below some paragraph blocks
2. Then saved and checked the frontend.
3. No audio controls seen.

**Expected behavior**
I expected to see the audio controls.

**Screenshots**

![screen shot 2018-11-03 at 13 14 11](https://user-images.githubusercontent.com/5323259/47952079-69d69c80-df6a-11e8-814c-69c52f32462a.png)

-----

![screen shot 2018-11-03 at 13 17 06](https://user-images.githubusercontent.com/5323259/47952111-e10c3080-df6a-11e8-9bd1-ef5f62883f8d.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg version 4.1.1

**Extra:**
I changed to file instead of audio.

![screen shot 2018-11-03 at 13 38 13](https://user-images.githubusercontent.com/5323259/47952320-bb345b00-df6d-11e8-80d4-fd53925ae60c.png)

It now shows up on the frontend. I am able to click the download button and play the audio mp3 file.

![screen shot 2018-11-03 at 13 38 54](https://user-images.githubusercontent.com/5323259/47952330-d3a47580-df6d-11e8-9023-6b1f8d75b25f.png)

**Comment by BE-Webdesign** [comment]
I am having a hard time duplicating, is the theme you are using available on `.org` repository, or publicly available? It appears as though the correct markup is on the front end, which leads me to believe maybe this is a styling issue somehow in the active theme?

**Comment by paaljoachim** [comment]
I just tested Twenty Seventeen and notice the audio controls showing up there.
So this seems to be a theme issue.

I added an issue to the Beans Framework repository. I am using a child theme from http://getbeans.io/
(It is not located on the .org repository.)

I will close this issue for now and if needed reopen it again.
