### ISSUE TITLE
Viewing backend <-> frontend. Image too close to another image.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11448]
**Describe the bug**
Here is the backend of the page that I am creating:

![screen shot 2018-11-03 at 13 21 13](https://user-images.githubusercontent.com/5323259/47952158-5bd54b80-df6b-11e8-847b-e7a8c2e4d0b8.png)

Here is the frontend:

![screen shot 2018-11-03 at 13 21 48](https://user-images.githubusercontent.com/5323259/47952167-70194880-df6b-11e8-957d-80c8f3d67f99.png)

Even though I added a block with an image in it below the Polly Higgins image. The second image is nudging it self upward to the empty area that was beside the Polly image and just below the text. So it gets pulled together.

**To Reproduce**
1. Add an image. Then add some text.
2. Align image to the left. Then align text to the left.

![screen shot 2018-11-03 at 13 26 01](https://user-images.githubusercontent.com/5323259/47952214-077e9b80-df6c-11e8-88b4-afa01389e3cc.png)

3. Go into the text box and click enter a few times to move below the image.
4. Add something there. I added an audio block. One can also add another image.
4. Save and view the page. See if the image/audio etc has moved upward to just below the existing text to the right of the image.

**Expected behavior**
I expected to see the second image below the Polly Higgins image. Not up beside it.

Btw I went ahead and added a spacer block to push the image further down. So that it does not sit up to the Polly image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg version 4.1.1

**Additional context**
In relation to alignment of text and image: https://github.com/WordPress/gutenberg/issues/11445

**Comment by youknowriad** [comment]
Thanks for the report.

I don't see any issue from the screenshots, that's just how float positionning works . If there's enough place, you image or any other block will show up next to the floated item. The difference is that the available width in the frontend and the backend is not the same (The theme editor styles could align the widths).

I suggest adding a custom className to your second image and apply

```css
.my-image {
   clear: both;
}
```

**Comment by youknowriad** [comment]
Closing, let me know if you need more help.

**Comment by paaljoachim** [comment]
Thanks Riad!
