### ISSUE TITLE
Impossible to drag multiple blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11444]
**Describe the bug**
I've just spent 15 minutes trying to select and drag multiple blocks at once and I'm finding it virutally impossible. Not only is there no drag handle available when multiple blocks are selected, you can't drag from any other part of the block as it simply seems to select more blocks.

Moving multiple blocks, one at a time, within a long page, takes a ridiclous amount of time, and moving multiple blocks at once, seems impossible.

Vid: https://cl.ly/448aeb8e8c22

**To Reproduce**
1. Add Heading block
2. Add Meda & Text block (and insert content within it)
3. Select the two new blocks you just added
4. Try and move them to another location in your page

**Expected behavior**
When multiple blocks are selected, the drag handle should be displayed so that it's easier to move them.

**Desktop (please complete the following information):**
- OS: MacOS Sierra 10.12.6
- Browser: Firefox Quantum 62.0.2 (64-bit)
- WP 5.0-beta2-43859
- TwentyNineteen

**Comment by ocean90** [comment]
You already reported this in #7283. 🙂

**Comment by maddisondesigns** [comment]
Uugh! What an idiot. Sorry about that. Thanks for pointing that out.
