### ISSUE TITLE
Add multi-selection toolbar and inspector controls support

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11446]
**Is your feature request related to a problem? Please describe.**
It is not possible to select multiple blocks to change from heading to paragraph.
(It would also be good to multi select and change alignment or make other general changes to multiple blocks at the same time. Alignment, bold etc.)

![screen shot 2018-11-03 at 13 02 57](https://user-images.githubusercontent.com/5323259/47951990-cdf86100-df68-11e8-902a-647bd961553a.png)

**Describe the solution you'd like**
I did pasted in lots of links and noticed that all of them have become headings.
I want to select all of them and change from header to paragraph. That means having a way to select multiple blocks and having all of them switch to another block type.

**Describe alternatives you've considered**
I will have to manually go and change each block from heading to paragraph.

**Comment by ocean90** [comment]
Related: #3535, #7635

**Comment by mtias** [comment]
Also related #6128.

**Comment by mtias** [comment]
Some of these interactions already work:

* Select multiple image blocks -> transform to Gallery.
* Select multiple paragraphs -> transform to List block.

**Comment by mtias** [comment]
Closing this as it has remained not very actionable. Specific transforms should be suggested on their own issues.
