### ISSUE TITLE
Editor not loading - failed to load resources 

### ISSUE THREAD

**Issue by blazevivan** [WordPress/gutenberg#11453]
**Describe the bug**
Installed the Gutenberg. 
Tried to start a new page. 
Editor failed to load. 
Video cap: https://cld.wthms.co/o4duFx
Console output:  http://cld.wthms.co/Cr8qjG
Error: `GET http://onyxstorestage01.blog/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js 404 (Not Found)`
Server PHP version 5.6

**To Reproduce**
1. Go to Page
2. Click on a New page
3. Scroll down to Gutenberg and open the editor

**Expected behavior**
Editor to be opened

**Desktop (please complete the following information):**
 - OS: Windows 10 - 1803
 - Browser tested on: Chrome, Firefox, IE
 - Version latest on all browsers

**Comment by ocean90** [comment]
Can you check your logs to see if it's related to #10075?

**Comment by blazevivan** [comment]
It was a server side issue. ModSecurity rule was triggered against mine domain and since it was white-listed it start working.

**Comment by blazevivan** [comment]
Problem solved, can be closed.
