### ISSUE TITLE
wp.element is intercepting calls to ReactDOM on non-Gutenberg pages

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#11455]
**Describe the bug**
When calling to ReactDom on non Gutenberg pages (like a sub menu page built out by `add_submenu_page`, I am enqueueing a script that is importing React and ReactDom for inclusion via Webpack. All of that is working. However, on `ReactDOM.render`, I'm getting the error `wp.element is undefined`. Why is WP intercepting this at all? Our team has looked into it and cannot figure out why WP would be doing this at all.

**To Reproduce**
1. Create a page in the admin that is not an editor page.
2. Enqueue a script using react and react dom to render something
3. Look at the console on that page in the admin
4. Weep

**Expected behavior**
WP should not be intercepting calls to React or React DOM functionality anywhere but Gutenberg editor specific cases.

**Screenshots**
![screen shot 2018-11-03 at 11 03 47 am](https://user-images.githubusercontent.com/3329081/47953758-2bd07d00-df58-11e8-89f6-62d9ff6c531f.png)

![screen shot 2018-11-03 at 11 04 27 am](https://user-images.githubusercontent.com/3329081/47953762-430f6a80-df58-11e8-949b-79fb285d2061.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: FireFox latest

**Comment by youknowriad** [comment]
How did you configure babel? You're probably using `wp.element` as a pragma

**Comment by mrpritchett** [comment]
Yes, I have the following:
```
    [
      '@babel/plugin-transform-react-jsx',
      { pragma: 'ReactDOM.render' }
    ],```

**Comment by BE-Webdesign** [comment]
If you get rid of that pragma value it should go back to the default `React.createElement`. When babel compiles your code it is compiling the JS to use wp.element.createElement, so if it is not loaded that is why you are getting the error on another page.

**Comment by mrpritchett** [comment]
Getting rid of that has no effect unforunately. 
I assume that I just needed to remove that line, stop yarn and restart it?

Working with our team more on Monday to hopefully come up with a solution.

**Comment by youknowriad** [comment]
What he just said, if you don't want to use `wp.element` set the pragma to `React.createElement`

**Comment by youknowriad** [comment]
I'm closing this issue for now. Keep us updated but hopefully, this should fix it.

**Comment by mrpritchett** [comment]
This ended up being the pragma. There are two possible solutions for anyone else who encounters this: 

1) Remove that pragma for wp.element.
2) Add a .babelrc file in the directory of the file where you need to override the pragma (as we need the other pragma in certain cases) and add your own pragma override for that file/dir.
