### ISSUE TITLE
Selecting size of embeded video

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11450]
**Is your feature request related to a problem? Please describe.**
It is a layout issue.
The following screenshots shows centering a video and how small it is on the page.

![screen shot 2018-11-03 at 13 44 02](https://user-images.githubusercontent.com/5323259/47952385-cb990580-df6e-11e8-80f8-aa8a60a2236a.png)

**Describe the solution you'd like**

It would be nice to select how large the embed should be. Such as small, medium or large. Similar to an image. As the embed can be very small.

**Describe alternatives you've considered**
I am thinking that I could use iframe code to decide the size of the embed by going to Youtube to get the code to where I can select the size of it.

**Comment by ocean90** [comment]
Note that the width of the embed depends on the [`$content_width` variable](https://codex.wordpress.org/Content_Width). Does your theme already support [responsive embeds](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#responsive-embedded-content)?

**Comment by youknowriad** [comment]
Thanks for the report, this looks like a Beans Framework issue, let's close in favor of the corresponding issue.
