### ISSUE TITLE
Use "homepage" instead of "home page"

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#11458]
We usually use "homepage", not "home page" in strings

https://github.com/WordPress/gutenberg/blob/db728b7/packages/block-library/src/more/index.js#L28

> Want to show only an excerpt of this post on your home page? Use this block to define where you want the separation.

Also I find this sentence a bit 'unpolished'. I'd expect more st. like

> Do you want to show only an excerpt of this post on your homepage? Then use this block to define where the separation should take place.

related: https://core.trac.wordpress.org/ticket/42468

**Comment by swissspidy** [comment]
For reference, the core handbook glossary: https://make.wordpress.org/core/handbook/best-practices/spelling/

**Comment by benhuberman** [comment]
> We usually use "homepage", not "home page" in strings

That's a good catch -- it would need to be applied to a couple more instances in #10919. cc @alexislloyd.
