### ISSUE TITLE
Selection stuck when selecting video embed then another video embed

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11452]
**Describe the bug**
In Gutenberg:
I selected a video embed. I notice the toolbar on the top left.

Then further down on the page select another video embed (click video not the block) the toolbar is not seen on the second video but stays on the first video embed.

**To Reproduce**
1. Add two video embeds.
2. Click on the first video embed.
3. Scroll down to second video embed and click the video. 
4. No toolbar is seen on the second video embed.

**Expected behavior**
Clicking the contents inside a block the toolbar should reflect that the block is selected. It does so for images, but not for video embeds. As clicking the video embed the block is not selected.

**Video**
![video-embed-select-block](https://user-images.githubusercontent.com/5323259/47952759-a6a79100-df74-11e8-8be8-c1fef2c5e826.gif)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg version 4.1.1

**Comment by ocean90** [comment]
Thanks for the report. This is already being tracked at #10632.
