### ISSUE TITLE
Making the WordPress Widgets available as Blocks

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#11462]
Hello,
For years WP and Widgets exists, lots of plugins  create Widgets. 
Why are they not transformed as Gutenberg Blocks?
Or 
Why not creating a Widget bllock which can  embed Widget area?

**Comment by GlennMartin1** [comment]
The native WordPress widgets are already blocks in the new Editor. 

Third party widgets needs their code rewritten to become blocks. Many third-party widgets already have been converted into blocks. That's the work of the widget producer, not of WordPress core. 

In Phase 2, WordPress will introduce the blocks to the widget areas. 

Good stuff.

**Comment by ocean90** [comment]
As mentioned above, this will be explored in phase 2. See #4770 for some discussion around this.

**Comment by NickCa12** [comment]
> The native WordPress widgets are already blocks in the new Editor.
> 
> Third party widgets needs their code rewritten to become blocks. Many third-party widgets already have been converted into blocks. That's the work of the widget producer, not of WordPress core.
> 
> In Phase 2, WordPress will introduce the blocks to the widget areas.
> 
> Good stuff.

How can a third party widget plugin become blocks? Can you name some third party widgets who have become blocks?
I am interested in making widgets which can be included into blocks just the like the native ones in Wordpress. Is there any guide to do that?

**Comment by AshiqKiron** [comment]
Any idea how to convert my old widgets to gutenberg blocks ?
