### ISSUE TITLE
Gutenberg with WPML Multilanguage plugin: Gutenberg is not respecting the current language, only the primary language defined on Wordpress

### ISSUE THREAD

**Issue by danielbento** [WordPress/gutenberg#11461]
I'm not sure if the problem stands on WPML or Gutenberg.

Gutenberg is not respecting the current language, only the primary language defined on Wordpress

Two main things are happening:
1. When I add a new internal link and the URL box appear, it only shows to me the main language articles and not the current language.
For example, my blog has 2 main languages: PT and EN. The primary language is EN. So, when I try to add a new link in the PT version, the only options suggesting on the URL search box is EN.

2. Every time I save an article, it changes the category to the same one in the primary language. Again, in my blog, when I save a PT article, the category is changed to the EN category. Then I can change it back again in the Quick Edit Box.

**Comment by youknowriad** [comment]
Closing as duplicate of #10199 to consolidate all WPML conflicts issues
