### ISSUE TITLE
Document States - clickable hot spots

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11468]
I will be looking at current and possibly new document states (this might be the wrong word to use) to help the user interact with the layout section of Gutenberg.

**Current Document States.**

Cursor blinks in the Add title block.

<img width="1204" alt="screen shot 2018-11-04 at 12 06 05" src="https://user-images.githubusercontent.com/5323259/47963277-090e9900-e02a-11e8-97fd-b3d6712f44ee.png">

![clickable-area-gutenberg](https://user-images.githubusercontent.com/5323259/47963402-3d835480-e02c-11e8-9d96-090c698e4627.jpg)

Clicking in the blue area removes the blinking cursor from Add title block.

Clicking in the red area makes "Write your story" block active and cursor blinks inside of the block.

<img width="744" alt="screen shot 2018-11-04 at 12 24 02" src="https://user-images.githubusercontent.com/5323259/47963423-889d6780-e02c-11e8-89bf-80e2732b2b05.png">

Suggested additions:
- Click once to remove blinking cursor from Add title (last active block). Click again to return it. On/Off. 

Current:
![clickable-area-gutenberg-2](https://user-images.githubusercontent.com/5323259/47963619-08c4cc80-e02f-11e8-89b3-daac7356f1c1.jpg)

Suggested adjustments:
- Make the blue area just below the block also deselect the block.

---

How can we easily hide the WP sidebar and the right document setting? To fully see the layout without clicking to do a preview and go outside of Gutenberg.
In Photoshop we have the Tab key to hide toolbars and panels.

--

Hover a block in the layout shows the blue outline/boundaries of the block and could as well show other things associated with the block that can be manipulated such as movers and drag handles. As well as showing the toolbar belonging to the block.

--

Clicking into a block shows which actions can be done when interacting with the block.

I will think more about this issue. 
There is a lot more then can be added.

https://github.com/WordPress/gutenberg/issues/11424

**Comment by karmatosed** [comment]
I think we need to be careful adding hot spots like this. I would like to work backwards, what is the problem being seen in testing for example? 

With all this in mind let's close this and consider after 5.0 if this is an issue and people are reporting. Then we can iterate.

**Comment by paaljoachim** [comment]
Hot spots already exist as seen from my example of when the block is active and not. It is very subtile but it is there.

 "I would like to work backwards, what is the problem being seen in testing for example?"

The problem is when is a block deselected and when is it not? The user can do random clicking and suddenly notice the block is deselected and other random clicks it is not. This creates a subtile difference. Like a fly in the room buzzing. One can notice it is there but do not pay much attention to it as one just gets used to having it in the room. The block deselect or not is a minor nuisance that can instead be looked at as a feature to be utilised better then what it is a present.
