### ISSUE TITLE
Impossible to click the "Open in New Tab"

### ISSUE THREAD

**Issue by psaikali** [WordPress/gutenberg#11485]
I noticed a weird bug with the "Open in New Tab" setting for links.

Sometimes I can click it, sometimes I can't. 

Usually, it's impossible to click it if my mouse pointer is above another block of content placed below the current block (with the link I'm editing). If I slightly move my pointer so that it does not overlay another block, the click does work fine and the toggle setting is changed.
Otherwise, the click event closes the link tooltip and the block below "receives the click", resulting in (unwanted) text selection.

I'm using Safari 12.0 with Gutenberg 4.1.1

![screen recording 2018-11-05 at 10 04 am](https://user-images.githubusercontent.com/1606655/47993067-dd091b80-e0ee-11e8-89b4-0dec570767e0.gif)

or

![screen recording 2018-11-05 at 11 40 am](https://user-images.githubusercontent.com/1606655/47993365-94059700-e0ef-11e8-8285-074292143e54.gif)

**Comment by designsimply** [comment]
Thank you for reporting this! I'm closing it as a duplicate of #11186 and noting your animated gifs there (which are awesome).

Possibly related: #11087

**Comment by designsimply** [comment]
Aha! Thanks @johngodley 🙂
