### ISSUE TITLE
Format API - Provide a way for some attributes to be removed (or not included) in the saved format.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#11484]
**Is your feature request related to a problem? Please describe.**
This request originates from working on #1838

Currently, in the classic editor, when a user creates a link with an invalid URL, an extra attribute `data-wp-url-error="true"` is added to the outputted `<a>` tag. This is used as a selector to add a border around the formatting, indicating there's an error:
**Classic editor**
![screen shot 2018-11-05 at 4 53 14 pm](https://user-images.githubusercontent.com/677833/47987855-90880500-e11b-11e8-92b5-dabbbc10e6e4.png)

**HTML**
![screen shot 2018-11-05 at 4 57 22 pm](https://user-images.githubusercontent.com/677833/47987971-ea88ca80-e11b-11e8-8b24-64f6e3d25f5f.png)

**CSS**
![screen shot 2018-11-05 at 4 49 21 pm](https://user-images.githubusercontent.com/677833/47987651-03dd4700-e11b-11e8-8171-369ca05a8afe.png)

Most importantly, the `data-wp-url-error` attribute is not included in the post content:
![screen shot 2018-11-05 at 4 59 55 pm](https://user-images.githubusercontent.com/677833/47988104-44899000-e11c-11e8-8974-9eb34d7a59d9.png)

In Gutenberg, the Format API supports adding an additional attribute like `data-wp-url-error`, but the attribute will always be saved to the post content (even in the classic block). Having a way to mark this attribute as something that shouldn't be included in the post content would enable the same sort of behaviour as the classic editor's link validation.

**Describe the solution you'd like**
There are lots of options. When declaring a format, an additional property could be used to details attributes that aren't saved:
```javascript
{
    name,
    title: __( 'Link' ),
    match: {
        tagName: 'a',
    },
    attributes: {
        url: 'href',
        target: 'target',
    },
    strippedAttributes: [
        'data-wp-url-error'
    ],
    // ...
```
Alternatively, any attribute beginning with 'data-wp' could be removed, or this could be something configurable at a higher level.

**Describe alternatives you've considered**
The format api could have an entirely different way to specify things like errors that are stored separately from attributes. To allow styling, class names could be added to the formatting tags, but only on the editor side.

**Comment by iseulde** [comment]
Could we not prevent invalid link from being added? Once an invalid link is added, how is the border applied on a new parse, if the attribute is gone?

**Comment by talldan** [comment]
> Could we not prevent invalid link from being added?

I don't think it's feasible that we could write validation to adequately check all types of href values, there are a huge number of variations—different protocols, schemes, forms that could be considered valid use cases. The only option would be to massively restrict the types of hrefs that can be used.

> Once an invalid link is added, how is the border applied on a new parse, if the attribute is gone?

I did wonder about that, for example when loading a post into the editor that has an invalid link. The value would have to be revalidated. I think I see where the issues with this lie with this, it looks like the formatting would have to be re-applied. Using an attribute possibly isn't the best idea, it would need to be something that validates during parsing?

Over here, https://github.com/WordPress/gutenberg/pull/11286#issuecomment-436449971, @chrisvanpatten mentioned that the error is really metadata, and so potentially a similar use-case to the annotations api. I haven't looked too much into that, so I'm not sure if there are similarities.

**Comment by iseulde** [comment]
> Over here, #11286 (comment), @chrisvanpatten mentioned that the error is really metadata, and so potentially a similar use-case to the annotations api. I haven't looked too much into that, so I'm not sure if there are similarities.

Maybe. For annotations it's the entire format. For links it would be just an attribute.

> I think I see where the issues with this lie with this, it looks like the formatting would have to be re-applied. Using an attribute possibly isn't the best idea then, instead would we need validation to occur during parsing?

I'm just trying to figure out if it can't be done in a way that is currently possible, before introducing new APIs that might not even solve the issue entirely. So apologies to be a bit pushing back here. Why can't it just be saved with all the rest? I guess you don't want the attribute on the front-end?

Maybe we need to make it so you can have an additional attribute set that sources from `href`, checks if it's valid and returns boolean:

```js
url: 'href',
isValid: ( { href } ) => isValidURL( href ),
```

**Comment by talldan** [comment]
> Maybe we need to make it so you can have an additional attribute set that sources from href, checks if it's valid and returns boolean

That seems like something that could work - how would the isValid attribute then affect the resulting format?

**Comment by talldan** [comment]
I've assigned this to the 'WordPress 5.0.x Follow Ups' milestone as the issue it blocks (https://github.com/WordPress/gutenberg/issues/11793) is also in that milestone.

**Comment by talldan** [comment]
Closing as a stale issue.
