### ISSUE TITLE
Importing .scss file doesn't work when it isn't in the same directory as file which imports it

### ISSUE THREAD

**Issue by marecar3** [WordPress/gutenberg#11487]
For some reason, [this line of code](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/primitives/svg/index.native.js) isn't working as expected. Style object (map) is always empty. 

As I have investigated so far, .scss couldn't be imported from other directory and reason why that isn't possible is still unclear. 

Quick fix for this would be to move a .scss file into the same directory where index.native.js is.

**Comment by designsimply** [comment]
Noting the line from `/packages/components/src/primitives/svg/index.native.js` for reference:

`import styles from '../../dashicon/style.scss';`

I am not sure how to check this myself (I'm still learning how to trace back through code like this). Would it be possible to get some more specific testing steps so I can help test? I can see that the `style.scss` file has rules about dashicons to use the current fill color and no outline but I am not sure where to look for those things in the interface.

```
svg.dashicon {
	fill: currentColor;
	outline: none;
}
```

Thank you for testing and reporting issues!

**Comment by marecar3** [comment]
Hey @designsimply,
You can take a look at this example here: https://github.com/WordPress/gutenberg/pull/9294#discussion_r215695160

But generally, problem is that the current line of code `import styles from '../../dashicon/style.scss';` will won't work and if we move the `.scss` file to be in the same directory as `/packages/components/src/primitives/svg/index.native.js` is and change the path to `import styles from './dashicon/style.scss';` then it will work.

This needs to be tested against gutenberg-mobile which can be run on iOS or Android device.

**Comment by koke** [comment]
I'm not sure what's going on there, but I'm wondering if we need to import that file at all. Probably @hypest or @mzorz  know more about this.

**Comment by hypest** [comment]
As @koke mentioned, in this particular case the style file doesn't seem to be needed at all anyway, since there is no Dashicons usage.

Does the issue happen in some other occasion @marecar3? If so, you'll probably want to have a look at [sass-transformer.js](https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/sass-transformer.js) to see if something goes wrong with the path resolutions.

**Comment by ellatrix** [comment]
Is this still an issue?

**Comment by marecar3** [comment]
@ellatrix thanks for asking, I will close this one as it's not relevant anymore.
