### ISSUE TITLE
Button with icon

### ISSUE THREAD

**Issue by tt33tt** [WordPress/gutenberg#11507]
Hi all,

I would like to add an icon to my button in Gutenberg e.g. ein PDF-Icon before an PDF-Download-Button.
There are plugins like https://wordpress.org/support/plugin/shortcodes-ultimate/ or https://wordpress.org/plugins/forget-about-shortcode-buttons/ which already developed this function.
I suggest to develop that for Gutenberg buttons, too.

Greetings

**Comment by tofumatt** [comment]
I think that's a good feature for a third-party button block, but I don't think it's something we should support in the default button block.

You might want to look through the plugin gallery to see if any of the third-party block plugins supply this feature for now 😄

**Comment by strarsis** [comment]
@tt33tt, @tofumatt: Have you found a nice plugin for a button with icon?
