### ISSUE TITLE
Error when pressing enter on the second line of content with formats

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#11508]
**Describe the bug**
Pressing enter on the middle of the content in a nonfirst paragraph of content in a quote with a custom format e.g.: bold errors in the console instead of creating a new line.
**To Reproduce**
1. Create a new post.
2. Add a quote block.
3. Write 'aaaaa' as the first line of content and 'bbbbbb' as the second line of content.
4. Make the second line ( 'bbbbbb' ) bold.
5. Put the cursor in the middle of the line and press enter.
6. Verify a new line is not created and the following error appears on the console:
```
react-dom.min.82e21c65.js:144 Uncaught TypeError: Cannot read property 'slice' of undefined
    at normalise-formats.js:21
    at Array.forEach (<anonymous>)
    at normaliseFormats (normalise-formats.js:17)

```
**Expected behavior**
A new line is created.

**Screenshots**
![nov-05-2018 19-57-48](https://user-images.githubusercontent.com/11271197/48023530-fc776700-e135-11e8-954b-c81af5a040e7.gif)

**Comment by LZL0** [comment]
This should be in 4.3

**Comment by iseulde** [comment]
Done in #11859.

**Comment by jorgefilipecosta** [comment]
Thank you @iseulde!
