### ISSUE TITLE
Permalink edit section inherits styles brought in from `add_theme_support( 'editor-styles' )`

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#11503]
**Describe the bug**
The permalink link area can inherit link styles set in a theme's classic editor styles, when they're pulled into to the new editor using `add_theme_support( 'editor-styles' )`.

A more specific selector, and some proactive styles should help fix, though it looks like it could be easy to end up with some redundant CSS. 

This issue is similar to #11132; @afercia spotted it when reviewing changes to Twenty Seventeen, here: https://core.trac.wordpress.org/ticket/45246#comment:4

**To Reproduce**
1. Start with a theme that uses `add_theme_support( 'editor-styles' )` to pull classic editor styles into Gutenberg. Any of the older default themes (Ten thru Seventeen) from the WordPress 5.0 beta will work.
2. Open an existing page or post.
3. Click on the post title to view the permalink.

**Expected behavior**
That this space would use the same fonts, colours, and styles of other Gutenberg elements.

**Actual behavior**
This space can inherit colours (on both the link and button), and font family, as well as odd things it doesn't set, like borders (Twenty Fifteen) or box-shadows (Twenty Seventeen).

**Screenshots**
All default themes exhibit some level of issue:

Twenty Seventeen: inherits colour and box shadow (for underline)
![twenty-seventeen-permalinks](https://user-images.githubusercontent.com/177561/48012631-509f2e80-e0d7-11e8-8686-a18fb404394b.png)

Twenty Sixteen: inherits colour
![twenty-sixteen-permalinks](https://user-images.githubusercontent.com/177561/48012635-5432b580-e0d7-11e8-8ac0-ebf82bdb6e25.png)

Twenty Fifteen: inherits colour and bottom border (for underline)
![twenty-fifteen-permalinks](https://user-images.githubusercontent.com/177561/48012643-5a289680-e0d7-11e8-806f-aba0bf539297.png)

Twenty Fourteen: inherits colour on link and button
![twenty-fourteen-permalinks](https://user-images.githubusercontent.com/177561/48012654-5eed4a80-e0d7-11e8-9a67-d4fce67a462a.png)

Twenty Thirteen: inherits colour on link and button
![twenty-thirteen-permalinks](https://user-images.githubusercontent.com/177561/48012666-644a9500-e0d7-11e8-9858-4853367d4c14.png)

Twenty Twelve: inherits colour on link
![twenty-twelve-permalinks](https://user-images.githubusercontent.com/177561/48012673-690f4900-e0d7-11e8-918a-83d91e1c3a34.png)

Twenty Eleven: inherits colour, font styles
![twenty-eleven-permalinks](https://user-images.githubusercontent.com/177561/48012682-6d3b6680-e0d7-11e8-9f42-26116aeaa644.png)

Twenty Ten: inherits colour on link and button, and font family
![tweny-ten-permalinks](https://user-images.githubusercontent.com/177561/48012686-70ceed80-e0d7-11e8-9252-58e978db5fe8.png)

**Additional context**
Can recreate with the Gutenberg 4.2 RC, and the current version in the repo as of commit c8b4679.

**Comment by youknowriad** [comment]
We have a new panel for permalinks now #11874. We didn't remove this UI yet because we're passed UI freeze but it should be considered deprecated. I'm considering this as a wont fix.
