### ISSUE TITLE
Embed: PollDaddy changed to Crowdsignal

### ISSUE THREAD

**Issue by kristarella** [WordPress/gutenberg#11517]
**Describe the bug**
PollDaddy embed should be renamed to Crowdsignal.

**To Reproduce**
1. Go to editor
2. Click on add block
3. Scroll down to Embeds > PollDaddy
4. It's called PollDaddy, but service is now called Crowdsignal

**Expected behavior**
Needs to be changed to CrowdSignal

polldaddy.com now redirects to https://crowdsignal.com/

**Comment by geekpulp** [comment]
I suspect this is more difficult than it appears on the surface (and my newbie skills allow) but I’m willing to give it a try. Wish me luck.

**Comment by gziolo** [comment]
Resolved with #12854 🎉
