### ISSUE TITLE
Reusable Block: "Save" button inaccessible with any device 

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#11519]
**Describe the bug**
When turning a `Column` block into a `Reusable` block, the `Save` button is virtually inaccessible using mouse, touch, or keyboard.

**To Reproduce**
1. Create a `Column` block.
2. Add stuff inside the columns.
3. Turn `Column` block into a `Reusable` block.
4. Try clicking the `Save` button.

**Expected behavior**
`Save` button should be immediately available by mouse, touch, or keyboard.

**Screenshots**
Video demo of the bug: https://cloudup.com/c1rhJUKO0NG

**Desktop:**
 - OS: Tested on MacOS and Windows
 - Browser: Tested in Chrome and Firefox
 - Version: WordPress 5.0 Beta 3

**Comment by designsimply** [comment]
Adding a screenshot from the video demo for reference:

![screen shot 2018-11-05 at 7 36 27 pm](https://user-images.githubusercontent.com/1119271/48039505-3e9ea980-e132-11e8-8bdc-48c122681eb1.png)

**Comment by slimmilkduds** [comment]
I can confirm this issue.

**Comment by designsimply** [comment]
Ace. Ditto. Just tested with WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 and was able to see that the Save button is almost impossible to click when trying to make a columns block into a reusable block. ([22s](https://cloudup.com/ccXz6Wq39yU))

Thanks for testing @slimmilkduds !!

**Comment by mtias** [comment]
This should no longer be happening after https://github.com/WordPress/gutenberg/pull/11904 and https://github.com/WordPress/gutenberg/pull/11659

![image](https://user-images.githubusercontent.com/548849/48811776-fe345380-ed0d-11e8-8905-d304a24ad856.png)
