### ISSUE TITLE
Make Classic Editor for certain pages permanent

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#11536]
**Is your feature request related to a problem? Please describe.**
The Classic Editor Plugin works, but when using the "classic optional" option it would be very important to make permanent some selected pages/posts editable only by Classic Editor (because of special formatting issues, needed but Gutenberg incompatible Plugins, and so on.)

**Describe the solution you'd like**
Having an additional option to tell Classic Editor Plugin / Gutenberg which pages/posts are never subject to Gutenberg editing.

**Describe alternatives you've considered**
Deactivate Gutenberg completely.

**Comment by designsimply** [comment]
May I also ask for examples of the kinds of selected posts/pages that have special formatting needs so that they are documented here?

Would it be possible to use the classic block for any of those cases?

**Comment by designsimply** [comment]
Thank you for noting these examples. 

Were you able to check to see if the [Gutenberg Ramp](https://wordpress.org/plugins/gutenberg-ramp/) plugin that @annestk suggested solves the problem for you?

**Comment by burnuser** [comment]
https://de.wordpress.org/plugins/disable-gutenberg/ can do this, but Classic Editor is the "official" recommended (and as such most installed) plugin and I think that the "deactivate Gutenberg for certain pages" option should be a standard feature for all users.

**Comment by designsimply** [comment]
Closing and noting that the answer provided was that some options will be added to the Classic Editor plugin itself and if those future updates are not sufficient then it is recommended that you use a different plugin or a plugin add-on to restrict certain types of content to always use the Classic Editor.

Thank you for asking about this!
