### ISSUE TITLE
Better add_theme_support( 'wp-block-styles' )

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#11548]
This would be awesome to have:

```
add_theme_support( 'wp-block-styles', array(
	'core/blockquote',
	'core/columns',
	'core/gallery',
	'core/image'
	etc.
) );
```

Many of the default styles are good but some I would like to dequeue and I can't.

What is the official/recommended method of doing that correctly?

**Comment by mtias** [comment]
This is not feasible at the moment since the CSS bundles are generated for all available core blocks at build time. Take a look at the larger project here #20331 for an overview of how the project aims to be able to manage default styles in a more granular way.
