### ISSUE TITLE
Non-uniform behaviour of Text formatting shortcuts

### ISSUE THREAD

**Issue by tybor** [WordPress/gutenberg#11544]
**Describe the bug**
Monospaced and strikethrough shortcuts behave differently than bold or italics. Ideally all text formatting shortcuts shall behave in the same manner. Monospace and strikethrough instead require the user to type the part that shall be monospaced, stop typing, select the freshly typed text that shall be monospaced, use the shortcut. This breaks the workflow. The same does not hold for bold, italic and underline.

**To Reproduce**
1. in the editor hit Ctrl-B and type "some text"
2. then hit Alt-Shift-X and type "print('Hello Dolly!');"

**Expected behavior**
The expected code should be `<strong>some text <code>print('Hello Dolly!');</code></strong>` 
Currently one gets `<strong>some text print('Hello Dolly!');</strong>` 

**Screenshots**
Not applicable

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version 63.0.1

**Additional context**
- Gutenberg  4.1.1

**Comment by iseulde** [comment]
Duplicated of #11065. This will be fixed in 4.2.

**Comment by tybor** [comment]
> Duplicated of #11065. This will be fixed in 4.2.

Thanks. 
I'm sorry for the duplicate, I did looked for something similar, obviously failing... :)

**Comment by tybor** [comment]
@iseulde I want to test the development version. git cloning the repo into wordpress/wp-content/plugins is enough or there's a specific way to do this?

**Comment by iseulde** [comment]
Have a look at https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md to run the dev version.
