### ISSUE TITLE
Markdown ignores empty table cells

### ISSUE THREAD

**Issue by gektor-de** [WordPress/gutenberg#11547]
## Description
When pasting markdown tables with empty cells, those cells are being ignored.

**To Reproduce**
1. Go to https://www.tablesgenerator.com/markdown_tables
2. Generate a table or use the following example:

```
|   |      | Text  |       |      |
|---|------|-------|-------|------|
|   |      |       |       | Text |
|   | Text |       |       |      |
|   |      | Text1 | Text2 |      |
```
This should render to:

|   |      | Text  |       |      |
|---|------|-------|-------|------|
|   |      |       |       | Text |
|   | Text |       |       |      |
|   |      | Text1 | Text2 |      |

3. Copy and paste to an empty Gutenberg page or post
4. See error:
![image](https://user-images.githubusercontent.com/7830085/48072954-f1781180-e1dd-11e8-8ace-2afc6adde0db.png)

## Expected behavior
Tables should be parsed from markdown correctly, as they do for example in github or gitlab environments.

**Desktop**
 - Browser: Tested in latest Chrome and Firefox

**Additional context**
 - Gutenberg Version: 4.1.1

**Comment by designsimply** [comment]
Tested and confirmed the results of the test based on the steps provided using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 with Firefox 63.0 on macOS 10.13.6. 

I also tested the table example on a few different markdown preview sites such as https://dillinger.io/ and https://markdown-it.github.io/ and https://markdownlivepreview.com/ and found that the table was process correctly in 2 of the 3.

**Comment by GlennMartin1** [comment]
This bug makes the Table block unusable at this point.

I have Google Sheets tables that include occasional blank cells, and pasting it makes a mess.

**Comment by imsimond** [comment]
I'm seeing the same problem when copying an HTML table containing empty `<td></td>` cells from a web page into a Gutenberg block. See also #8953

Original HTML markup of a simple page:

![markup](https://user-images.githubusercontent.com/663859/50825977-5a8d1a00-1332-11e9-9cbc-684942df2711.png)

Renders successfully in browser (here, Chrome 71 on Mac):

![table_with_a_blank_cell](https://user-images.githubusercontent.com/663859/50825995-6bd62680-1332-11e9-84ad-54b8cc8b7077.png)

Copied and pasted into Gutenberg (here, WP 5.0.2):

![g-visual](https://user-images.githubusercontent.com/663859/50826026-87413180-1332-11e9-8cfc-4a799aa37d02.png)

'Edit as HTML' view within Gutenberg shows the empty cell has been removed:

![g-codeview](https://user-images.githubusercontent.com/663859/50826076-a4760000-1332-11e9-93d3-6b2d696aaec4.png)

Verified in both Chrome and Firefox.
