### ISSUE TITLE
Taxonomy terms capabilities (4.2 rc1)

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#11546]
Hi. https://github.com/WordPress/gutenberg/pull/11395 was suppose to fix https://github.com/WordPress/gutenberg/issues/11335 but in my case it has not. I use custom user roles and custom taxonomies and I can not access taxonomy terms for non-admin users. It works fine in 4.1 rc 2. Does anyone know which capability is needed for a user role to see taxonomy terms?

**Comment by danielbachhuber** [comment]
> Does anyone know which capability is needed for a user role to see taxonomy terms?

Yes, they'll need the `assign_terms` capability, per https://core.trac.wordpress.org/changeset/43443

**Comment by slimmilkduds** [comment]
Hmm, that doesn’t work for me unfortunatly.

**Comment by slimmilkduds** [comment]
I actually need to give them the manage_terms capability, which is not great. I have no doubts assign_terms work for core wp-roles but it does not for custom roles after 4.1 rc 1 (atleast for me)

**Comment by slimmilkduds** [comment]
Ignore me, sorry! I updated from 4.2 rc2 to 4.2.0 and it works as expected 🤐
