### ISSUE TITLE
Gallery: Transforming from [gallery] should fall back to Shortcode block.

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#11551]
Quoting @danielbachhuber in https://github.com/WordPress/gutenberg/pull/3852#issuecomment-406067989:

> For [the 5.0 milestone], a standalone `[gallery]` shortcode would convert to a Shortcode Block. A `[gallery ids="1,2,3"]` shortcode would convert to a Gallery Block.

> Ultimately, it doesn't appear we've yet come to a "good" option, only varying degrees of worse options. I don't think this UX is important enough to try to rush a decision on. Plus, we still have aspects like #5972 to deal with.

**Comment by danielbachhuber** [comment]
> Transforming from [gallery] should fall back to Shortcode block.

Is this _all_ instances of `[gallery]`, or only instances without attributes (e.g. `[gallery]`, but not `[gallery ids="1,2,3"]`)?

At this point, because of #5972, I think we might as well not convert `[gallery ...]` to a Shortcode Block at all.

**Comment by mcsf** [comment]
I understood it to be: `[gallery ids=…]` would yield a Gallery, and `[gallery]` a Shortcode.

> I think we might as well not convert `[gallery ...]` to a Shortcode Block at all.

Did you mean Gallery?

**Comment by mcsf** [comment]
The only glitch is that the transformation API for shortcodes is different from the other ones (`block`, `raw`, `files`) in that it doesn't allow the consumer to provide a function that ultimately decides to call `createBlock` with whatever block type — essential to distinguish `createBlock( 'core/gallery' )` from `createBlock( 'core/shortcode' )`.

@iseulde, do you remember if there was a motivation to keep the API for shortcodes different? Also, am I right in thinking that we currently can't proceed without tweaking the API?

**Comment by danielbachhuber** [comment]
> > I think we might as well not convert `[gallery ...]` to a Shortcode Block at all.
> 
> Did you mean Gallery?

Yes, sorry. I've updated my comment.

**Comment by simison** [comment]
If the core gallery could define `isMatch` where it checks for `ids` in shortcode transform, this problem would get solved.

That said, using `isMatch` is broken currently for shortcode transforms. https://github.com/WordPress/gutenberg/issues/10674 :-(

**Comment by mcsf** [comment]
Yes, shortcodes are handled in a pretty different way. I can't tell for sure if `isMatch` would be the best interface for them, but it's worth checking, so thanks for opening that issue.

**Comment by simison** [comment]
Yup, suppose an alternative approach could be to define specific attributes as required with a possible list of accepted values.

**Comment by christinablust** [comment]
The specific issue I'm running into frequently on client sites (that led me to this ticket) is galleries using the `[gallery id="7772"]` syntax, where previously the gallery would go pull all photos attached to post id 7772. Currently "Convert to blocks" makes this an empty gallery, which is very problematic and loses a key piece of information (the other ID). 

It would be much better to convert that use case to a shortcode and leave as is. Like mentioned up thread, some sort of conditional determination based on which attributes are used with `[gallery]` would be helpful here.

**Comment by mcsf** [comment]
There's a fix in #25144, if you'd like to test and review.
