### ISSUE TITLE
No inserter (+) between two successive Columns blocks

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11559]
If you have two successive Columns blocks, it's not possible to add a new block between the two Columns blocks with the inserter. 

The inserter (+) does not display.

Just to be clear, I'm referring to the ColumnS (plural) block, not the Column (singular).

The only way to insert a block between two Columns blocks is to move a block up/down to that position. 

Gutenberg 4.2

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 and found that I could insert a new block between two successive Columns blocks using the inserter but that it's pretty darn tricky and the inserter only appears if you hover over the exact right spot. ([24s](https://cloudup.com/cFG938vGuYh))

**Comment by designsimply** [comment]
Semi-related: #8406 (that one is for Column singular not Columns plural)

**Comment by mtias** [comment]
This has been improved with the most recent updates to columns:

![image](https://user-images.githubusercontent.com/548849/48811565-27081900-ed0d-11e8-8395-2157bed463be.png)
