### ISSUE TITLE
Post set to publish immediately shows a "Schedule" button instead of "Publish" button

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#11554]
<del>Possibly a regression caused by #11489? I'm not sure.</del>

This is a regression caused by a1b647dccabc.

If I create a new post on master that's set to publish immediately, the "schedule" text and not the "publish" text appears for me:

<img width="840" alt="screenshot 2018-11-06 21 46 16" src="https://user-images.githubusercontent.com/90871/48095754-6ca4ec00-e20d-11e8-9935-376742241eee.png">

**Comment by tofumatt** [comment]
For what it's worth I think I saw this go away after an autosave, but only if I never manually saved a draft.

So that's super-weird.

**Comment by youknowriad** [comment]
Maybe related to #11418

**Comment by tofumatt** [comment]
Confirmed; https://github.com/WordPress/gutenberg/commit/a1b647dccabc1f12a2aec8c0352e44c5c468fc8e is the cause of this one.
