### ISSUE TITLE
Always show icon in block toolbar

### ISSUE THREAD

**Issue by alexislloyd** [WordPress/gutenberg#11552]
Currently, blocks that don't have transformations or styles registered don't show the block icon in the left side of the block toolbar when the block is selected (for example, the columns block). As a user, the toolbar icon has become one of the key ways I identify a block type when it's selected, and it appears to be an error when it's not present. I would propose that the block icon always be shown in the toolbar for a consistent user experience.

**Comment by chrisvanpatten** [comment]
YES! I would loooove this. I agree completely; I'm always thrown off a bit when a block doesn't have the icon visible.

**Comment by karmatosed** [comment]
Great addition, let's get it in! I'll label to get developed.

**Comment by chrisvanpatten** [comment]
I have about a million things on my plate including some high priority docs stuff (so if someone else has time please feel free to take over) but if possible I'll try to get a PR up this week!

**Comment by jasmussen** [comment]
I'm a fan. One thing to explore in the implementation is the visual styling of the block icon, when no transformations are registered — the subtext being that it's not clickable (clicking it doesn't do anything). 

Perhaps it is sufficient that there simply isn't a dropdown arrow indicator, but an additional idea to explore if that is insufficient, is to show the icon in a lighter shade of gray to indicate that it's decorative/disabled.

**Comment by alexislloyd** [comment]
That's a good point @jasmussen. I think the hover effect (swapping to the transform icon) should be disabled for blocks that don't have transformations, and no dropdown arrow as you mentioned. I think that might be sufficient, but if it ends up being confusing, your suggestion of a "greyed out" state could be an additional layer of cueing.

**Comment by youknowriad** [comment]
For consistency and clearness, would it be clearer if it behave similarly (animation and dropdown) and when you open a dropdown, show a generic message: "No style variations or transformations available for this block".

The message is not ideal but this way, we won't confuse this icon with other icons in the toolbar.

**Comment by jasmussen** [comment]
> For consistency and clearness, would it be clearer if it behave similarly (animation and dropdown) and when you open a dropdown, show a generic message: "No style variations or transformations available for this block".

I would prefer we avoid this unless absolutely necessary. The reason being to avoid "mystery meat transformations". Right now the dropdown clearly indicates: _this block has transformations_, and the absence of such a dropdown indicates similarly: _this block does not transform_. The icon can be there as a lock type identifier, but the lack of the dropdown arrow, hopefully, will indicate there are no transforms to be found.

**Comment by jasmussen** [comment]
I think that's a solid observation, Riad. But I think reducing the opacity to indicate disabledness might be the way to go here.
