### ISSUE TITLE
UX: tip dot overlays menu flyout

### ISSUE THREAD

**Issue by drawcard** [WordPress/gutenberg#11563]
**Describe the bug**
The tip dot z-index is too high and overlaps menu item flyout

**To Reproduce**
Nil

**Expected behavior**
The tip dot should sit below the menu item flyout

**Screenshots**
![image](https://user-images.githubusercontent.com/1435638/48111882-96105700-e2a3-11e8-97ec-a10eb7514b0f.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.0
 - Browser: Chrome 70.0.3538.77

Relevant code: https://github.com/WordPress/gutenberg/blob/25bc46a9135cbeb805fefa3325382d01ce4bd938/assets/stylesheets/_z-index.scss#L91-L92

**Comment by drawcard** [comment]
To me I find it a bit confusing, I would expect that all tips (including the dot and dialog box) sit below any critical UI that flies out above it like a menu flyout.

In fact I discovered this randomly by firing up a new post in a fresh install of WP5, and then making a decision to do something elsewhere in WP - wherein I noticed the flyout was obscured by the dot / dialog box. It felt a bit broken / jarring to me, and not what I expected.

**Comment by designsimply** [comment]
Thanks for posting a specific use case. Always helpful to have that. It would be cool to get some additional input so I’ll leave this open for feedback for now.

**Comment by melchoyce** [comment]
Yeah, weird z-index issue. I agree that the navigation menus should be higher than the tips — the tips are part of the page, and the page appears underneath the menu. Having the tips appear over the menu makes for a weird sandwich.

**Comment by drawcard** [comment]
Yep I think dropping the tip's z-index down 1 unit below the menu system would do the trick. 

I also wonder if other menu overlays are affected (eg 3rd party plugin menu dropdowns potentially placed in the top admin bar). This was just a blank WP5 setup I was testing out.

**Comment by Naerriel** [comment]
Z-index goes currently like this:
admin menu < admin bar < nux dot tip

We want to keep admin menu below admin bar, because admin bar's submenus should be on top of menu:
![image](https://user-images.githubusercontent.com/13454526/51298445-e125b380-1a24-11e9-9f79-38bf5f4633dc.png)
 
Also we want to keep admin bar's z-index below nux dot tip, because it's often placed on admin bar:
![image](https://user-images.githubusercontent.com/13454526/51298526-2d70f380-1a25-11e9-94ab-784ed08f3ced.png)

With those dependencies it seems impossible to achieve:
admin menu > nux dot tip,
nux dot tip > admin bar,
admin bar > admin menu,
but maybe there is a workaround.

What do you think about that?

**Comment by mapk** [comment]
When changing `.components-popover:not(.is-mobile).is-bottom` from `z-index: 99990` to `z-index: 100` it seems to work just fine. However there's now a problem with the "Content Structure" toolbar popover. It normally extends further over the wp-admin navigation, so in this case part of it gets lost.

If we make this change, we'd also need to update that popover to position within Gutenberg only.

**Example at `z-index: 100`**

![popover](https://user-images.githubusercontent.com/617986/55661002-18069c80-57be-11e9-8367-88b1c6f76892.gif)

**Comment by mapk** [comment]
I'm closing this due to the new tip explorations here: https://github.com/WordPress/gutenberg/issues/16592

Tips are being completely redesigned and these popovers will become obsolete.
