### ISSUE TITLE
Annoying Scroll behavior in Gutenberg

### ISSUE THREAD

**Issue by hansschuijff** [WordPress/gutenberg#11578]
**Describe the bug**

I found Gutenberg introduces three partly overlapping scroll-able areas, of which two are new. One area is the page as a whole. The new ones are the sidebar and the content (block) area, within that page area. 

I like that I can scroll the sidebar separate from the part in which the blocks live, but now I have a new problem, since the not all the scroll-area’s are contained by the height of my viewport. The page as a whole and the sidebar are contained by the viewport, but the contentblock area lives in the page-length instead.

That is a problem, since now, if I wan’t to go to the end of my content (or see the meta-blocks below it), I now have to scroll twice in two separate area’s before I see that part of the page.

First I go all the way down in the contentblock-area, and than the part that isn’t yet shown (because it is below the viewport), becomes only visible when I also scroll the page as a whole.

I find that not that confusing, less user friendly and at the least not very inefficient. Probably it will end up being annoying.

Thanks for all the good in Gutenberg, but can you change this problem?

**To Reproduce**
1. Write some content longer than the viewport in an install that has lots of wordpress menu-items so the side-menu is longer than the viewport.
2. Try scrolling to the bottom of the content-area
3. And find that you now first have to go to the side and scroll the page as a whole too to see the bottom part of the content. Probably you also see tree scrollbars, what is a lot too and sometimes a bit confusing at start.

**Expected behavior**
I would like to scroll down in the content part of the page and get to the bottom in that way.

**Screenshots**
![image](https://user-images.githubusercontent.com/21155718/48132946-69edd980-e295-11e8-8ee0-7144daa0efe6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer
 - Version 64.0b5 (64bits)

**Additional context**
- Gutenberg version 4.2.0.
- Wordpress version 4.9.8
- php version 7.2.11

/wordpress.

**Comment by hansschuijff** [comment]
The screenshot is the result of scrolling all the way to the bottom. You can see that the scroll indicator itself in the content-area isn't even visible anymore and the bottom will show only after scrolling with the most right scrollbar. There is still a lot below the fold.

**Comment by designsimply** [comment]
Thank you for the report! Closing as a duplicate in favor of #11185.
