### ISSUE TITLE
Extensibility: Add a way to register More Menu item which uses callback

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#11570]
Reported on Slack by justinbusa (https://wordpress.slack.com/archives/C02QB2JS7/p1541524004751500):

> Can someone point me in the right direction? Since the `editPost.MoreMenu.tools` filter was removed (#10194), what’s the best way to add a menu item to the more menu that does something when clicked? I don’t need a sidebar (found the tutorial for that), just a click event. I’ve dug through the source and am coming up empty handed. Thanks! :smiley:

Another similar report by marctison75 (https://wordpress.slack.com/archives/C02QB2JS7/p1540388930000100):

> Is there a way to add a more menu item similar to `<PluginSidebarMoreMenuItem/>` which opens a `Modal` instead of a `<PluginSidebar/>` ? I want to open a modal similar to the Keyboard Shortcuts and Options menu items.

As a first iteration, we can offer `PluginMoreMenuItem` which takes `onClick` callback and inserts menu items inside `Plugins` group. it would allow to handle `Modal` as well. It might require some code though.

**Comment by gziolo** [comment]
There is #12309 opened which will provide the initial implementation.

I will provide an example of how to handle `Modal` once the PR lands.

**Comment by afercia** [comment]
> Is there a way to add a more menu item similar to <PluginSidebarMoreMenuItem/> which opens a Modal instead of a <PluginSidebar/> ? I want to open a modal similar to the Keyboard Shortcuts and Options menu items.

Worth reminding that opening a modal from a menu item breaks the modal interaction pattern: when the modal closes, focus should be moved back to the invoking context, i.e. the button that opened the modal. But at that point, the menu is closed so the "invoking button" is not in the DOM any longer. This was noted for the Keyboard Shortcuts modal and I think we have an issue for that? @tofumatt
