### ISSUE TITLE
Link without href attribute shows undefined as URL

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#11574]
**Describe the bug**

I pasted some content into the editor where a link had an empty `href` attribute. After pasting, the attribute was completely removed. So the markup is like `<a>Foo</a>`.

When now clicking on that link, it shows `undefined` as the URL instead of some error message or similar.

**To Reproduce**
1. Edit paragraph block in HTML mode and enter something like `<a>Foo</a>`
2. Switch back to visual mode and click on the link.
3. Notice `undefined` URL

**Expected behavior**

**Screenshots**
<img width="265" alt="screenshot 2018-11-07 at 12 05 51" src="https://user-images.githubusercontent.com/841956/48128162-e678bc00-e285-11e8-9357-8e48655da0b2.png">

**Desktop:**
Chrome 70 on macOS

**Additional context**
Gutenberg 4.1.1 on WordPress 4.9.8

**Comment by desrosj** [comment]
I can also reproduce this running WP 5.0-Beta3 without the plugin.
