### ISSUE TITLE
Insert Link: Pasting text removes link

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#11571]
**Describe the bug**

When pasting text in the middle of a link, the link is partially removed.

This makes it impossible to quickly change the link text via copy/paste.

**To Reproduce**
1. Write something like `ABCD` and add a link to it.
2. Paste some letters like `XYZ` into the middle of the link
3. You'll end up with `ABXYZCD`, where `AB` and `CD` are still links, XYZ however is no link.

**Expected behavior**

Pasting the text does not partially remove the link.

**Screenshots**

Here's a gif showing the problem:
![linky linky](https://user-images.githubusercontent.com/841956/48124653-20919000-e27d-11e8-8d4b-abed9df78e28.gif)

**Desktop (please complete the following information):**

Chrome 70 on macOS.

**Additional context**
Gutenberg 4.1.1 on WordPress 4.9.8

**Comment by designsimply** [comment]
Good find. Testing note: let's check a couple different browsers for this one.

**Comment by sourourn** [comment]
Was able to reproduce this issue on Firefox (61.0.2)
Gutenberg version: 4.5.1
WordPress version: 4.9.8

**Comment by dromero20** [comment]
I tested this out by reproducing the steps and I can confirm it's happening. One quick note: it only happens when you're pasting something in the middle of the link, if you writing something "manually", the link doesn't break.

Tested in Firefox 63.0.1 (64-bit).
Gutenberg: 4.5.1
WordPress: 4.9.8
