### ISSUE TITLE
Title height doesn't change on sidebar open/close

### ISSUE THREAD

**Issue by NewJenk** [WordPress/gutenberg#11580]
**Describe the bug**
When the sidebar opens/closes the title doesn't change height, so it's clipped.

**To Reproduce**
1. Add a new post
2. Give the post a long(ish) title
3. Open the settings
4. Height doesn't change, resulting in the text clipping

**Expected behavior**
For the title textarea to maintain the height of the content

**Video**
https://www.useloom.com/share/2cd852433b374d11b5c5818b44b394c0

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Chrome
 - Version: Latest

**Additional context**
- Gutenberg 4.2

**Comment by designsimply** [comment]
Aha! This has a report already at #6897 but we are in need of better testing steps for that case! I will add your steps to the other issue.
