### ISSUE TITLE
New Gutenberg Update 4.2.0 broke Open Graph for Facebook, Google+ and Twitter Card Tags

### ISSUE THREAD

**Issue by halleeb** [WordPress/gutenberg#11591]
**Describe the bug**
Gutenberg updated today, and now the information put into Open Graph for Facebook, Google+ and Twitter Card Tags disappears as if never entered.

**Expected behavior**

I expect the preview of the blog and the image I selected be what shows up on social media sharing. Now it defaults to my blog header and the first few lines of the blog post.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - I am using Firefox, but the problem persists in Chrome

**Additional context**
- Please add the version of Gutenberg you are using in the description.
4.2.0
Open Graph for Facebook, Google+ and Twitter Card Tags has worked through all Gutenberg updates until now.

**Comment by ellatrix** [comment]
Sounds like an extension issue. Please contact the author of the plugin responsible for adding the meta boxes.
