### ISSUE TITLE
Navigation between blocks with arrow keys broken on iOS

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#11593]
**Describe the bug**

Testing out frontenberg with Gutenberg v4.1 in an Apple store, I noticed, it's not possible to use the up and down arrow keys to navigate between 2 adjacent blocks, a tap on the block is required to start typing

**To Reproduce**
1. Use an iOS device with a physical keyboard, e.g. an iPad Pro with smart keyboard running iOS 12 in safari
2. Tap on a paragraph block and type
3. Use the arrow keys to navigate to another block
4. The user is unable to navigate to text in other blocks using the arrow keys as they would on a laptop or desktop device

**Expected behavior**

I expected the arrow key behaviour to match that experienced in chrome or firefox on a desktop OS such as MacOS or Windows

**Comment by tomjn** [comment]
This also happens in the iOS simulator in mobile safari, I've uploaded a video taken with my phone demonstrating:

https://www.youtube.com/watch?v=CtekhvouP60

**Comment by youknowriad** [comment]
Anyone with an iOS phone can test if this is still valid? @gziolo @jasmussen?

**Comment by tomjn** [comment]
I tried this recently on an iPad in the Apple store with the same issues.
It’s on my todo list to test with the new iPadOS

**Comment by noisysocks** [comment]
I was able to navigate between blocks using the keyboard on my iPhone with a bluetooth keyboard connected.

https://cloudup.com/cE5xx54ntMT
