### ISSUE TITLE
Overlapping controls on the Classic Text block

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#11592]
**Describe the bug**
My site has a snippet of code that adds a code button to the classic editor toolbar. In Gutenberg this makes the toolbar wide enough that the "more" button that shows the kitchen sink is now underneath the 3 dot button:

<img width="226" alt="screenshot 2018-11-07 at 15 47 26" src="https://user-images.githubusercontent.com/58855/48142306-77f72680-e2a4-11e8-8c6d-2e5974a62c7a.png">

![classic-block-more-overlap](https://user-images.githubusercontent.com/58855/48142545-ecca6080-e2a4-11e8-82cd-ab6b99b9cbe5.gif)

Tested on Gutenberg v4.2

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - Browser Firefox 
 - Version v63

**Comment by azaozz** [comment]
Not seeing this any more, possibly fixed elsewhere. The toolbar buttons wrap around before reaching the "More options" button even when more buttons are added by a plugin:

![toolbar](https://user-images.githubusercontent.com/743931/52412422-657ccb00-2ae7-11e9-9870-f62c318eaf37.png)

Closing as "worksforme" for now. If that still happens feel free to reopen with a way to consistently reproduce.
