### ISSUE TITLE
Editor ignores capabilities/user access on categories, pages and posts

### ISSUE THREAD

**Issue by TIIUNDER** [WordPress/gutenberg#11596]
**Describe the bug**
I'm using the User Access Manager Plugin to adjust the user access rights using categories. For that I also set user groups for the categories. In the classic editor the categories are filtered correctly. I see the categories which I have access to only. Gutenberg just shows all categories. I think the Gutenberg editor ignores the get_terms filter.

**To Reproduce**
1. Install [User Access manager](https://de.wordpress.org/plugins/user-access-manager/)
2. Create two user groups
3. Assign 1st user group to category
4. Create test user with 2nd user group and editor role
5. Login as test user
6. Create new post with classic editor - You don't see categories of other user groups
7. Create new post with Gutenberg editor - You still see categories of other user groups

I tried to debug it and the get_terms filter seems to give the correct categories, but the editor just doesn't use them and gets all categories.

**Expected behavior**
Categories of other user groups should be hidden. The Gutenberg editor should use the categories of the get_terms filter.

**Additional context**
- Version used: Gutenberg 4.20
- Link to User Access Manager: https://de.wordpress.org/plugins/user-access-manager
- Support Ticket for User Access Manager: https://wordpress.org/support/topic/categories-not-hidden-in-gutenberg-editor/

**Comment by TIIUNDER** [comment]
Additional info: I noticed the categories are loaded via the REST API of WordPress. Maybe there should be a cross check or something.

**Comment by TIIUNDER** [comment]
Same problem for parent posts/pages. Gutenberg doesn't check if the user has backend access to the other pages or posts.

**Comment by designsimply** [comment]
I would like to help test this. I installed the User Access Manager plugin and tried to add a user group and "assign 1st user group to category" but I am not sure how to do that step. Here is what I see:

![screen shot 2018-11-12 at 4 33 10 pm](https://user-images.githubusercontent.com/1119271/48381330-a9069b00-e698-11e8-9e6d-0e06ea6c0ec1.png)

Is there something else I need to change in the settings first? Can you check to make sure the testing steps are complete or help me if I'm missing something obvious in the steps?

**Comment by TIIUNDER** [comment]
You have to create a new user group, for example test, like this:

![screenshot_2018-11-13_11 17 01](https://user-images.githubusercontent.com/1225378/48406812-b160e380-e735-11e8-8296-36c238e21247.png)

After that you can assign the category (in the category menu) to the new user group by creating or updating one.

![screenshot_2018-11-13_11 18 23](https://user-images.githubusercontent.com/1225378/48406883-e3724580-e735-11e8-8234-747fe59cb2ea.png)

At the moment I' also discussing with the author of the plugin here: https://github.com/GM-Alex/user-access-manager/issues/261

Looks like the problem doesn't appear on a blank Wordpress setup.

**Comment by designsimply** [comment]
I followed the steps and categories assigned to a specific group were only visible if I was logged in as a group member. I did notice that you had "Read Access" set to "All users" in your example test group screenshot, and to restrict the category from being visible I think you need to set "Read Access" to "Only group users" for it to work the way you've described.

![screen shot 2018-11-13 at 7 37 06 pm](https://user-images.githubusercontent.com/1119271/48456273-a8930080-e77b-11e8-97a8-2e9d22148b7f.png)

I also noticed that this was tested and confirmed by the plugin author at https://github.com/GM-Alex/user-access-manager/issues/261#issuecomment-438200277 and I think for this case the plugin GitHub is the right place for continuing the discussion if needed.
