### ISSUE TITLE
Renaming functions in 4.2 is causing fatals

### ISSUE THREAD

**Issue by joemcgill** [WordPress/gutenberg#11598]
**Describe the bug**
In https://github.com/WordPress/gutenberg/pull/10826, several functions were renamed for compatibility reasons in order to avoid redeclaring functions in WP 5.0. However, the result is that anyone who is using the current stable version of WordPress and wanting to stay on the latest stable version of Gutenberg will experience fatals when upgrading to 4.2.

For example, I'm working on a project that used `get_autosave_newer_than_post_save()`. Use of this function worked with Gutenberg 4.1 and will work once I've upgraded WordPress to 5.0. However, in the intermediary time, I am either blocked from using newer releases of Gutenberg, or I have to write my own compatibility shim that checks for `get_autosave_newer_than_post_save()` and falls back to `gutenberg_get_autosave_newer_than_post_save()`. 

It's a relatively easy thing to fix on my end, but it would be much better for Gutenberg to take on this compatibility burden, IMO, rather than leaving that burden to various developers that want to stay on the latest stable version of Gutenberg, but may not be able to upgrade to WordPress 5.0 for a variety of reasons.

**To Reproduce**
1. Install Gutenberg 4.1 on WordPress 4.9.8
1. Create a function in a plugin that calls `get_autosave_newer_than_post_save()`
2. Upgrade Gutenberg to 4.2
4. See fatal error

**Expected behavior**
Upgrading Gutenberg should not cause fatals without deprecation warnings and should handle backcompat on behalf of integrators.

**Comment by danielbachhuber** [comment]
Yes, let's add a compatibility shim in the plugin. Thanks for the report.

**Comment by youknowriad** [comment]
The shim was not possible to add at the time we did the change because Gutenberg function were loaded before the Core functions in some cases if I remember properly. cc @mcsf 

I'm moving this out of 4.3 for now, let's try to clear the 4.3 milestone for a release.

**Comment by mcsf** [comment]
> I'm moving this out of 4.3 for now, let's try to clear the 4.3 milestone for a release.

@joemcgill: I agree this is an annoying situation. Thanks for the patience there.

**Comment by youknowriad** [comment]
This issue will fix itself once we release 5.0 and remove all these functions from Gutenberg. Sorry for the temporary breakage.
