### ISSUE TITLE
Right-align border for right-aligned quotes

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11609]
To improve the consistency of alignments and to avoid creating potentially-awkward rivers inside the quote block, I'd recommend adjusting the positioning of the hard left border on the quote block when the alignment is changed, so it would be to the right on a right-aligned quote, and either removed or maybe at the top of a centre-aligned block.

**Left-aligned**

<img width="532" alt="screenshot 2018-11-08 01 07 40" src="https://user-images.githubusercontent.com/376315/48171247-01354a00-e2f3-11e8-9216-4aa6e1f3e97d.png">

Suggestion is to remain as-is, since the alignment here is consistent with the text.

**Centre-aligned**

<img width="537" alt="screenshot 2018-11-08 01 07 29" src="https://user-images.githubusercontent.com/376315/48171230-e95dc600-e2f2-11e8-9379-042d58b60b03.png">

Suggestion:
<img width="594" alt="screenshot 2018-11-08 01 08 57" src="https://user-images.githubusercontent.com/376315/48171241-f975a580-e2f2-11e8-9d6e-2a709e294f39.png">

**Right-aligned**
<img width="543" alt="screenshot 2018-11-08 01 07 50" src="https://user-images.githubusercontent.com/376315/48171280-2629bd00-e2f3-11e8-91f4-f01ac9960b9b.png">

Suggestion:
<img width="582" alt="screenshot 2018-11-08 01 08 17" src="https://user-images.githubusercontent.com/376315/48171274-1dd18200-e2f3-11e8-9049-17c312bcbc65.png">

**Comment by colorful-tones** [comment]
I'm going to take a pass at updating the CSS around this now. (via @10up).

**Comment by colorful-tones** [comment]
Currently the Quote block is not using `className` on `<blockquote>`, which is problematic for adding the proposed variations mentioned above.

Currently, when alignment is switched it is just setting a `style` property on the element: `<blockquote style="text-align: left;"></blockquote>`

Whereas, we would want to leverage a `class` property instead: `<blockquote class="blockquote-left">`.

I'll continue to try and work up a PR, but I'm newer to React/Gutenberg. So somebody might beat me to it. Feel free!

**Comment by colorful-tones** [comment]
@sarahmonster I would love your feedback on the styling enhancements in submitted PR. Note: I went in a little different direction for center aligned quotes. Thanks!

**Comment by colorful-tones** [comment]
Tagging #10970 as they are related.
