### ISSUE TITLE
Refactor `getCurrentRichTextSelection` to use blockSelection start&end blocks

### ISSUE THREAD

**Issue by atimmer** [WordPress/gutenberg#11615]
Spinning out from #7718.

For `getCurrentRichTextSelection`, [@youknowriad mentioned that we could reuse the block selection already present in `blockSelection`](
https://github.com/WordPress/gutenberg/pull/7718#discussion_r231199584). This issue tracks that.

**Comment by ellatrix** [comment]
@atimmer How is this different form #11616?

**Comment by atimmer** [comment]
It was different back when my PR still contained a global state for RichText selection. I had created two issues to track different issues:

* This one: About refactoring the global state I introduced to be inside the `blockSelection`.
* #11616: To drop the local state still present in RichText.

#14640 seems to do both in one fell swoop, so I'll close this issue.

**Comment by ellatrix** [comment]
Thanks!
