### ISSUE TITLE
Remove local `RichText` state in favor of global selection state

### ISSUE THREAD

**Issue by atimmer** [WordPress/gutenberg#11616]
Spinning out from #7718.

[@iseulde mentioned that we can drop the local state of `RichText` in favor of the global state introduced in #7718](
https://github.com/WordPress/gutenberg/pull/7718#discussion_r231450971). This does require some investigation, because the local state in the `RichText` instances only track their own state. But if they use the global state the all track the state of the last `RichText` that had a selection change. I don't know what consequences this has.

**Comment by iseulde** [comment]
Yes, we definitely want to do this. It will also be useful to reset selecting after undoing changes. Related: #12002.

**Comment by ellatrix** [comment]
@atimmer If you're interested, I made a PR: #14640.
