### ISSUE TITLE
Not possible to undo a block style

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#11613]
**Is your feature request related to a problem? Please describe.**

If a block only has a single block style, it's not possible to remove that block style after you've selected it. You always need to add some sort of "default" style as well.

For example, I added a new "Pretitle" style for paragraphs like so:

```js
registerBlockStyle( 'core/paragraph', {
	name: 'pretitle',
	label: 'Pretitle',
} );
```

When I now write some text, everything works as usual. Once I choose the "Pretitle" stye, it will be styled a bit differently. But after that, there's no way for me to undo this selection.

I tried things like clicking on the selected style again in the hopes that this would remove the style again, but with no lock.

That means I need to register a default style that I can switch back to:

```js
registerBlockStyle( 'core/paragraph', {
	name: 'default',
	label: 'Default',
} );
```

This second style would not be styled by me or anything because it should keep the default styles of the editor/theme.

**Describe the solution you'd like**

If I add a style variant to a block which hasn't had one before, a default style option could be added automatically in the background.

Alternatively there could be a "Reset style" button or something that would restore the default block style.

**Comment by swissspidy** [comment]
> I agree this could be improved and I like this solution.

Added a PR in #12519.

**Comment by annestk** [comment]
Temporary workaround for anyone experiencing this issue: Removing _is-style-something_ from the input field at _Block Settings > Advanced > Additional CSS Class_ will reset the block style

**Comment by nickfmc** [comment]
Also worth noting you can only use 1 class name when registering a style for the default to clear.  if you use the below code you will get is-style-my-button 

```
wp.blocks.registerBlockStyle("core/button", {
        name: "my-button",
        label: "myButton"
      }); 
```

However if you used the below code even though your classes would be applied as is-style-my-button and u-block , the next time you click on a style it would append another is-style-my-button to the classes.  so you end up with ( is-style-my-button u-block is-style-my-button) Not sure if you should be able to register a style with multiple classes to me it seams to make sense for a lot of people.

```
wp.blocks.registerBlockStyle("core/button", {
        name: "my-button u-block",
        label: "myButton"
      }); 
```
