### ISSUE TITLE
Soft line breaks are not replaced by space

### ISSUE THREAD

**Issue by Haldaug** [WordPress/gutenberg#11626]
**Describe the bug**
Text pasted from other sources such as word or PDFs sometimes contain soft line breaks. When any operation is done on the text, such as using backspace or applying bold, the soft line breaks are removed fully and not replaced with normal spaces.

This bug appeared with the previous version of Gutenberg and persisted in the current: 4.2.0

This is possibly related to this bug: https://github.com/WordPress/gutenberg/issues/11588

**To Reproduce**
1. Paste text containing soft line breaks
2. Edit the pasted text
3. All instances of soft line breaks are now deleted

**Expected behavior**
I expect the soft line breaks to be converted to regular spaces, not removed entirely.

**Screenshots**
Notice that all the soft line breaks are removed, resulting in merged words:
![soft-linebreak-bug](https://user-images.githubusercontent.com/3501914/48202724-f8ca2700-e365-11e8-91f3-ecc69a33a23e.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera, Chrome
 - Version: Opera: 56.0.3051.52, Chrome: 70.0.3538.77

**Additional context**
- Please add the version of Gutenberg you are using in the description.

**Comment by Siguardius** [comment]
This is exactly the issue I'm having in #11588. I'm surprised it wasn't fixed already since there was 2 or 3 updates available since I first found out about it.

**Comment by designsimply** [comment]
Closing in favor of #11588 and I will test and add notes to that issue. Thank you for the report and confirmation comment!
