### ISSUE TITLE
InnerBlocks shows inline-image block, when not allowed

### ISSUE THREAD

**Issue by harmwinnemuller** [WordPress/gutenberg#11621]
**Describe the bug**
When a new block is inserted with the 'InnerBlock' component, and 'allowedBlocks' is used, the 'Inline-Image' block still shows, even when it's not allowed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Gutenberg text-editor
2. Add a block which uses InnerBlocks (with specific blocks inside)
3. Add an InnerBlock
4. You can now see 'inline-image', even if it should not appear.
5. Save the post and reload the page, now the 'inline-image' option is gone.

**Expected behaviour**
The 'allowedBlocks' should appear, but if 'inline-image' is not allowed, it should not appear.

**Screenshots**
Before saving the post:
<img width="806" alt="screenshot 2018-11-08 at 11 07 33" src="https://user-images.githubusercontent.com/42736463/48198415-16dd5a80-e359-11e8-91a0-6117fa275ef9.png">

After saving the post and reloading the page:
<img width="763" alt="screenshot 2018-11-08 at 11 07 57" src="https://user-images.githubusercontent.com/42736463/48198433-2bb9ee00-e359-11e8-985b-e8624ed96d26.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: Chrome version 70.0.3538.77 (Official Build) (64-bit)

**Additional context**
Gutenberg 4.2.0

**Comment by designsimply** [comment]
(Out of curiosity) how do you know when the inline images are and aren't supposed to appear. Is that something you see by reading the code or that you know from elsewhere? (Note: I don't know how to look that up in the code but would like to learn!)

**Comment by designsimply** [comment]
I tested using the Media & Text block with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6 and found that I was able to insert an inline image into an inner block ([10s](https://cloudup.com/c9x2tbZPKeJ)), however, now I am thinking that the following means that you are using custom code:

> When a new block is inserted with the 'InnerBlock' component, and 'allowedBlocks' is used

Are you able to provide a code example for how  you've used `allowedBlocks` in your case?

**Comment by harmwinnemuller** [comment]
Yes it's when I build a custom block with InnerBlocks. I use 'allowedBlocks inside the edit function: '<InnerBlocks allowedBlocks={ [ 'core/paragraph' ] }/>' .
But when I use the insert block function it will also show the inline-image block:
<img width="412" alt="screenshot 2018-11-14 at 16 00 27" src="https://user-images.githubusercontent.com/42736463/48490781-75f21200-e826-11e8-842c-3b3b17ee1117.png">

**Comment by harmwinnemuller** [comment]
I am not able to reproduce this issue on the current version of Gutenberg. So it seems fixed, as I have not seen other people having this issue. Therefor I will close this issue, thanks for your help anyway!
