### ISSUE TITLE
Gallery and Media & Text blocks not responsive

### ISSUE THREAD

**Issue by robjaykes** [WordPress/gutenberg#11639]
A media gallery of two images, for example, side by side, is not responsive. Neither is media and text displayed side by side using the Media & Text block.

Shouldn't these be responsive as a given?

I would like to see responsive elements added as core. It's crazy that this is not the case.

I am using Genesis and the Foodie Pro theme. Using [one-half-first] etc. code which is perfectly responsive.

**Comment by mtias** [comment]
Both blocks are responsive. Gallery stacks in different ways based on how many items are present. For "Media & Text" block see https://github.com/WordPress/gutenberg/issues/10798

**Comment by robjaykes** [comment]
A gallery of two images (placed by Gutenberg side by side), is not responsive. Unless I'm missing something glaringly obvious (but then that misses the point of what Gutenberg is intended to do - make everything obvious).

#10798 highlights the issue with a response being that columns got responsive, which is great but media cannot be inserted into a column block.
