### ISSUE TITLE
List duplicating content

### ISSUE THREAD

**Issue by josephahaden** [WordPress/gutenberg#11634]
**Describe the bug**
If you have formatted text starting a list item and it's selected, then pressing delete in a non-list block to move it into a list block above duplicates the content.

**To Reproduce**
1. Create a list block
2. Create a paragraph block with formatted text
3. Place cursor at the beginning of the text, so that the formatted text is still highlighted.
4. Press the Delete key
5. Content is duplicated (it also doesn't join the list block)

**Expected behavior**
The paragraph block would merge with the list block as a new item. No content would be duplicated.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave v10.14.1
 - Browser: Chrome
 - Version: 70.0.3538.77

**Comment by swissspidy** [comment]
Possibly related: #11568

**Comment by designsimply** [comment]
Aha, also, can you confirm the Gutenberg version you tested with?

**Comment by josephahaden** [comment]
I also can't replicate it now, so whatever was wrong seems to be fixed. :)

**Comment by mcsf** [comment]
Thanks for the report! Closing as solved.
