### ISSUE TITLE
Editor: Initialize blocks state by `RESET_BLOCKS`

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#11641]
Currently, blocks state is "reset" in response to two separate actions `RESET_BLOCKS` and `SETUP_EDITOR_STATE`.

https://github.com/WordPress/gutenberg/blob/005c79019685b03d99fc5609318887fb0eba34d7/packages/editor/src/store/reducer.js#L292-L293

https://github.com/WordPress/gutenberg/blob/005c79019685b03d99fc5609318887fb0eba34d7/packages/editor/src/store/reducer.js#L395-L396

If possible, we should seek to refactor the `SETUP_EDITOR` effect handler to dispatch `resetBlocks` directly such that it would only be necessary to cover the `RESET_BLOCKS` action type from the reducer.

**Comment by paaljoachim** [comment]
I see one closed PR and one merged PR.

Should this issue be closed?

@WordPress/gutenberg-core

**Comment by talldan** [comment]
It's very low priority, but can stay open.

**Comment by t-hamano** [comment]
Does anyone know if this issue can be closed? Currently, it looks like there is only `RESET_BLOCKS`:

https://github.com/WordPress/gutenberg/blob/c3ca59b70c9807e78b45d22d0714be777da507fd/packages/block-editor/src/store/reducer.js#L600-L602

**Comment by youknowriad** [comment]
I think we can close it.
