### ISSUE TITLE
Create integration with Post Settings for third-party plugin metaboxes

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1164]
As mentioned in #952 by @jasmussen:

> We should absolutely look at making the new Post Settings pluggable, so that you can add javascript metaboxes to the sidebar. Perhaps it's time to open a ticket for that.

This would extend to new metaboxes as well as adding to existing metaboxes.

Has anyone worked/thought on this yet? At the rate that Gutenberg is progressing, this might be good to spend some time on, so we can communicate the new way of building metaboxes to plugin developers before launch. That way they can integrate well and make use of the new functionality out of the gate, making it more likely users will respond even more positively to the new editor.

The first question I think people will have is which of the current hooks/filters used in the post edit screen and metaboxes will be dropped and which ones still supported?

**Comment by youknowriad** [comment]
The [proposed decorator pattern](https://github.com/WordPress/gutenberg/pull/1023) could theoretically be applied to any component we want to be extensible. This could be one way to solve this.

Also, we may want to add a [Slot](https://github.com/WordPress/gutenberg/pull/507) to add extra panels.

**Comment by hedgefield** [comment]
#1352 seems a better place to discuss this now.
