### ISSUE TITLE
Quote block: Using cite elements in quoted content causes block to become invalid.

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#11652]
## The issue
If you insert a `<cite>` element into the quoted content of a Quote block, the block becomes invalid.

## Reproduction steps
1. Insert a Quote block.
1. Add some content to the quoted content area (not the citation).
1. In the block toolbar, open the <kbd><samp>More Options</samp></kbd> (ellipsis) menu and choose <kbd><samp>Edit as HTML</samp></kbd>.
1. Add something like `<cite>Book Title</cite>` to the quoted content (in the `<p>` element).
1. Try switching back to edit the block visually.
1. Notice that the block becomes invalid.

Alternatively, just paste this into your post while using the <samp>Code Editor</samp>:
```html
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>blah<cite>book title</cite>blah</p></blockquote>
<!-- /wp:quote -->
```

## Suggested fix
Currently, the citation of the Quote block is simply a `<cite>` following the last `<p>`. I think that instead, the citation should be a `<cite>` nested in a `<footer>` after the last `<p>`. This would allow `<cite>` tags to be used outside of the citation of the Quote block, for use cases such as marking a book or game title. This would also be more semantically correct. Please check out the following:
- https://www.w3.org/TR/html52/grouping-content.html#the-blockquote-element (Specifically example 15.)
- https://www.w3.org/TR/html52/textlevel-semantics.html#the-cite-element

**Comment by mcsf** [comment]
Thanks for the feedback. I think this is worth cross-linking with #11440 as another data point, but it's not something we should look at individually. Technically speaking, we're dealing with a block that was explicitly manipulated with new markup, which is something blocks aren't meant to know how to deal with, and that's exactly what the _Convert to HTML_ is there for.

Finally, we have previously discussed what the standard markup for Quote _should_ be; there was a lot of back-and-forth there until we came to the current shape, and at this stage of 5.0 we are not reopening that discussion.
