### ISSUE TITLE
Gallery: Flash of white when image is uploaded

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#11650]
**Describe the bug**
After the Gallery block finishes uploading an image, it swaps the temporary `blob:` image with the real `http://` image. This causes a flash of white on slow to medium connections while the new image loads.

**To Reproduce**
1. Simulate a Fast 3G connection
2. Insert a Gallery block
3. Upload a few images

**Expected behavior**
I'd expect the images to appear with some indication that they are loading (seperate issue: https://github.com/WordPress/gutenberg/issues/8810), and then for the temporary image to be seamlessly replaced with the real image.

**Actual behaviour**
There is a flash of white while the temporary image is swapped out with the real image.

**Screenshots**
![gallery](https://user-images.githubusercontent.com/612155/48234776-24edb280-e40f-11e8-9b5e-a6811c045940.gif)

**Additional context**
We can do this by loading the real image using `new Image()` _before_ inserting it into the DOM.

**Comment by mapk** [comment]
It appears this has been resolved and now displays a "spinner" component while the images load properly.
