### ISSUE TITLE
Deleting an Additional CSS Class attribute leaves an empty className attribute in the HTML comment code

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#11664]
**Describe the bug**
When you delete an Additional CSS Class, it leaves an empty className attribute in the HTML comment code.

**To Reproduce**
1. Insert a heading block and type some text
2. In the Advanced panel, set an Additional CSS class
3. Empty the Additional CSS class field
4. Switch to Code Editor.

```
<!-- wp:heading {"className":""} -->
<h2>Heading</h2>
<!-- /wp:heading -->
```

**Desktop:**
 - OS: Windows 10, Mac OS
 - Browser; Chrome, Safari Firefox, Edge

**Additional context**
Gutenberg 4.2.0

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.3 that adding and removing an "Additional CSS Class" to the heading block results in a leftover empty className field in the block's HTML comment. ([23s](https://cloudup.com/c-Jom9V5dWN))

![empty-classname-in-comment](https://user-images.githubusercontent.com/1119271/48377007-d5ff8180-e689-11e8-9c0e-76b8eaffe58d.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15720&action=edit running WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by gziolo** [comment]
`className` is set to an empty string in this place:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/hooks/custom-class-name.js#L63-L70
