### ISSUE TITLE
Copy paste a heading adds a HTML id attribute to the pasted one

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#11662]
**Describe the bug**
When you copy paste a heading, the pasted one gets an HTML id attribute starting with "mce_".

**To Reproduce**
1. Insert a heading block and type some text
2. With the mouse, select the heading and copy it
3. Paste it below
4. Switch to the Code Editor: the second heading has an unwanted id attribute

```
<!-- wp:heading -->
<h2>Heading</h2>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 id="mce_1">Heading</h2>
<!-- /wp:heading -->
```

**Desktop:**
 - OS: Windows 10, Mac OS
 - Browser: Chrome, Safari Firefox, Edge

**Additional context**
- Gutenberg 4.2.0

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.3 that copying and pasting a heading within the editor results in an extra `id="mce_1"`. ([14s](https://cloudup.com/cyTaQd1o5TR))

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by skorasaurus** [comment]
Hi, I'm not able to reproduce this with your instructions; this appears to have been fixed. If you are still experiencing this, please reopen this. 

Thank you again for reporting.
