### ISSUE TITLE
 Deleting an HTML Anchor attribute leaves an empty HTML id attribute

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#11663]
**Describe the bug**
When you delete a HTML Anchor attribute, it leaves an empty HTML id attribute in the HTML code which is unvalidated markup (W3C validator).

**To Reproduce**
1. Insert a heading block and type some text
2. In the Advanced panel, set an HTML Anchor attribute  
3. Empty the HTML Anchor field
4. Switch to Code Editor. 
````
<!-- wp:heading -->
<h2 id="">Heading</h2>
<!-- /wp:heading -->
````

**Desktop (please complete the following information):**
 - OS: Windows 10, Mac OS
 - Browser: Chrome, Safari Firefox, Edge

**Additional context**
Gutenberg 4.2.0

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.3 that adding then removing an "HTML Anchor" leaves an empty `id` attribute which is invalid HTML ([W3C ref](https://www.w3.org/TR/html4/types.html#type-id)). ([20s](https://cloudup.com/cci92WVxYpf))

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>
