### ISSUE TITLE
"Convert to blocks" does not preserve center-alignment

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11676]
**Describe the bug**
In a Classic Block, a paragraph with center alignment becomes left aligned when converted to blocks.

**To Reproduce**
1. Create a Classic block with a center-aligned paragraph.
2. Convert to Blocks.
3. The resulting Paragraph Block is left-aligned.

**Expected behavior**
Center-alignment should follow through a "Convert to Blocks"

**Comment by designsimply** [comment]
Tested and confirmed that `<p style="text-align: center;">centered paragraph</p>` becomes `<p>centered paragraph</p>` after using "Convert to Blocks" on a classic block.

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by GlennMartin1** [comment]
Issue persists in Gutenberg 5.3.

**Comment by aduth** [comment]
Implementation notes:

The paragraph defines itself as being transformed from a raw paragraph tag here:

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/paragraph/transforms.js

The "raw handling" procedure is used to convert HTML to blocks:

https://github.com/WordPress/gutenberg/tree/master/packages/blocks/src/api/raw-handling

It includes some ability to define in a `transforms` `schema` the allowed `attributes`. However, it seems to lack the functionality to describe how those attributes should be mapped to an equivalent block attribute. This may need to be implemented as an enhancement to Raw Handling (to be able to associate the `style="text-align: center;"` to the paragraph block's `align` attribute).

**Comment by marcuswisecaesar** [comment]
Played into a ticket wherein a user was asking if any progress had been made for a fix regarding this?

2209584-zd

**Comment by selectedselections** [comment]
Another user is asking for a fix on this issue here: 2283034-zd
