### ISSUE TITLE
Standard features in Wordpress disappeared in Gutenberg

### ISSUE THREAD

**Issue by FNVTUDelft** [WordPress/gutenberg#11670]
When writing an article in Wordpress (the standard version) much more options were possible then in Gutenberg:

CONS
- The feature "read more" is totally gone (you have to add it in the HTML, which is difficult to find)
- It is not possible to modify the size of an image. In the standard version you had the choice in different sizes: 150x150 pixels to full image. In Gutenberg I was only able to add an image which covers the full page.
- It is not possible to add a featured image. The option to add it is gone.
- Where are the often used tags? Seems to be totally missing!

PRO
- It was very easy to add footnotes.

**Comment by Soean** [comment]
- There is a `More` block for this feature
- You can change the image size in the sidebar: thumbnail, Medium, Full
- It possible to set an featured image 
- Correct, see #8867
