### ISSUE TITLE
Media & Text block not display correctly on front end

### ISSUE THREAD

**Issue by dking3876** [WordPress/gutenberg#11680]
**Describe the bug**
The media and text block has option for image either left or right (while left is default). Switching this to image right in the edit page works and saves, however does not translate to the front end where the image is always displayed on the left. 
**To Reproduce**
1. Go to page or post and add media & text block under layout elements
2. Click on '....' add an image and text. change image to the right side. and save
3. view post or page
4. See the media item is displayed on the left regardless of backend option.

**Expected behavior**

the media item should be left or right depending on choice not always left
**Screenshots**

![image show right](https://user-images.githubusercontent.com/10117938/48275403-64b69900-e413-11e8-8107-1642ffc70f67.png)
![image display left](https://user-images.githubusercontent.com/10117938/48275416-697b4d00-e413-11e8-9e76-9d74e499d929.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 7 and 10
 - Browser [e.g. chrome, safari] chrome, firefox

**Additional context**
using wordpress beta 5.0beta-3

**Comment by GlennMartin1** [comment]
Duplicate.

This is already fixed in https://github.com/WordPress/gutenberg/pull/11534, coming soon in 4.3.

**Comment by designsimply** [comment]
Thanks! Closing with a nod to #11534.
