### ISSUE TITLE
Classic block removing paragraph end tag on save

### ISSUE THREAD

**Issue by kfts** [WordPress/gutenberg#11697]
**Describe the bug**
The end paragraph tag is missing in the post contents sent to the rest API save call from the classic block if that paragraph contains a line break and the starting p tag has an attribute.

**To Reproduce**
1. Create new post in Gutenberg
2. Add Classic Block and switch to Edit as HTML
3. Add 
&lt;p class="classy"&gt;Here
is a paragraph&lt;/p&gt;
4. Publish Post
5. See Request Payload in debugger or look at post in database. content property is:

"&lt;p class="classy"&gt;Here↵is a paragraph"

**Expected behavior**
end tags to remain

**Screenshots**
![image](https://user-images.githubusercontent.com/17014086/48284695-1ebafe80-e42e-11e8-952a-188288c96314.png)

**Desktop:**
 - OS: Windows 10 64 bit
 - Browser Chrome
 - Version 70.0.3538.67

**Additional context**
- Replicated on both Gutenberg plugin 4.4.0 running on WordPress 4.9.8 and WordPress 5.0 beta 3

**Comment by kfts** [comment]
Sorry, that's Gutenberg plugin version 4.2.0

**Comment by designsimply** [comment]
Tested and confirmed by checking the post content in phpMyAdmin after entering the following HTML in "Edit as HTML" mode in a classic block:

```
<p class="classy">This
is my paragraph with a line break in it.</p>
```

![screen shot 2018-11-12 at 11 49 06 am](https://user-images.githubusercontent.com/1119271/48368922-48646780-e672-11e8-9b4f-42ffd5816662.png)

![screen shot 2018-11-12 at 11 55 26 am](https://user-images.githubusercontent.com/1119271/48368904-400c2c80-e672-11e8-9495-2a24537e759d.png)

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>

@kfts I checked the database directly in my case, but could you tell me exactly how to get to the same Request Payload from your screenshot? I would like to learn that. 🙂 It looks like the Network panel in Chrome's web developer tools to me, but I wasn't sure what to filter for or when to check that (would it be right after saving in the editor itself?).

**Comment by designsimply** [comment]
Cool. Spotted it! ([screenshot](https://user-images.githubusercontent.com/1119271/48521351-60ceb080-e831-11e8-97fb-46f9de6e8b64.png)) Thanks for the tip. 😁

**Comment by youknowriad** [comment]
I was not able to reproduce the issue. I think it's probably fixed.
