### ISSUE TITLE
Quick Toolbar: Position sticky toolbar is broken when post settings is open

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1170]
Steps to reproduce:

- Have post settings closed, scroll a long block, verify the quick toolbar follows you down the page
- Open post settings, note that the quick toolbar no longer follows you down the page

`position: sticky;` breaks if a parent has `overflow: hidden`, or a `transform` applied. I could swear this was working a few revisions ago.

**Comment by EphoxJames** [comment]
Uh, It looks like you broke it. 
https://github.com/WordPress/gutenberg/commit/6991910962d60afb48ff52d611850c0b17a637cd

Specifically if I turn off these two rules it works:
```
.editor-layout.is-sidebar-opened {
	overflow: hidden;

	@include break-small() {
		overflow: auto;
	}
}
```

It seems the reason we've only just noticed it is that the menu defaults to open now on desktop when it defaulted to closed before.
https://github.com/WordPress/gutenberg/commit/5f51d0f8c9c189e86819e45248babae385cdb649

**Comment by jasmussen** [comment]
Great catch, thank you. I'll fix as soon as I can.
