### ISSUE TITLE
Broken styles for single-column columns block

### ISSUE THREAD

**Issue by carrieforde** [WordPress/gutenberg#11703]
If a user manually enters `1` for a single column child in the columns block, the block inherits styling for the two-column block.

One of two things need to happen here:
1. Users shouldn't be able to enter `1` if the slider doesn't support it.
1. A style needs to be added for the single column block.

Here is an example of the code produced on the frontend:
![HMTL output + related styles from the block-library stylesheet](http://files.carrieforde.co/images/2018/gutenberg-issue/single-column-styles.png)

**Comment by youknowriad** [comment]
Right now, it's not possible to enter "1" in the columns count, it automatically reverts to 2. This means this issue is fixed.
