### ISSUE TITLE
"Save Failed" "Update Failed" "Publish Failed"

### ISSUE THREAD

**Issue by diveyez** [WordPress/gutenberg#11709]
Wordpress Version: Current
Webserver: Nginx w/ letsencrypt https enabled

------

In order to reproduce, simply attempt to use the gutenberg editor, with SSL/HTTPS active, without editing the General Settings and changing the URL's to https://

------
Upon install it failed horribly, after reviewing the posts on github from others,
I can confirm SSL/HTTPS is breaking this if, in General the URL's are not updated to https://

**Comment by aeriform** [comment]
I have the current WordPress version on Nginx with letsencrypt and https

"Save Failed" "Update Failed" and "Publish Failed" also fail for me except my URL's in the General options are updated to https.

**Comment by youknowriad** [comment]
It looks like the REST API doesn't work properly in the regular nginx config. see similar issues https://github.com/WordPress/gutenberg/issues/12696#issuecomment-449117695 for solutions.
