### ISSUE TITLE
Gallery offers only upload an image option

### ISSUE THREAD

**Issue by bahiirwa** [WordPress/gutenberg#11717]
When one converts an image block to gallery block, or inserts a gallery block adds a image, the next option to add another image is only to upload from computer. No options comes for the media library as the case is for the inserting the gallery block for the firs time.

**To Reproduce**
1. Insert gallery block into post (or convert image block to gallery block.)
2. Insert one image for the new gallery block.
3. Try to add another image

Only one option is present - upload an image. The other option to add from media library is missing. I would love to add images from the media library and not duplicate my media uploads for existing media.

![screenshot 2018-11-10 20 18 41](https://user-images.githubusercontent.com/7713923/48304166-13e39500-e526-11e8-967f-e613c6b4f7aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 

**Gutenberg
Version: 4.2.2

**Comment by ocean90** [comment]
Thanks for your report! This issue is already being tracked at #8309.
