### ISSUE TITLE
Blocks Navigation menu: use links not buttons

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#11711]
For the same reason the "Content structure" menu (also known as "Document outline") is going to use in-page links, see #7142 and #10815, also the Blocks Navigation menu should use links.

Right now, the Blocks navigation buttons are used fot content navigation. They're emulating the hyperlinks behaviour "by moving keyboard (and viewport) focus to the relevant area, but the behaviour may be unpredictable to blind users".

**Comment by paaljoachim** [comment]
I see multiple PRs that have been closed and two merged.
I will close this issue. If I am mistaken then please reopen.

@joedolson Joe I am pinging you to Andrea's issue as you will have seen. Just to be sure that I am doing this correctly.

**Comment by joedolson** [comment]
It looks like the outline navigation is now using links, but it took me a while to figure that out, since they're only active when focused. The flow using the mouse is not functional. I would expect these to be available both using the mouse and the keyboard.

**Comment by paaljoachim** [comment]
Should we reopen this issue?

**Comment by joedolson** [comment]
Yes, this should probably be re-opened. The problem was solved, but the implementation is buggy.
