### ISSUE TITLE
Caption on resized Images does not display correctly

### ISSUE THREAD

**Issue by drniles99** [WordPress/gutenberg#11719]
When you insert an image into a post, the caption that you enter displays correctly for a full sized image however if you reduce the size of the image and then enter a caption and save the post, the caption on the image shifts to the left and the text appears vertically on the screen page.

**Comment by drniles99** [comment]
Hi Arun,

Thanks for the quick reply.

I tried creating a test post following your suggestion:

  *   I imported an image
  *   I added a caption
  *   I resized the image using only the tool on the side of the image
  *   and it looked like this in the editor

[cid:be35e805-c172-4030-95b6-53fd93e07ef2]

I then displayed the post and it looks like this:
[cid:0169f333-ed1d-46ad-92eb-5cc1dcc0fe90]

I am not sure what I am doing wrong.

This is a test site and I can give you access to it if that would help.
You can see the issue here:  http://sunsetbaytechnologies.com/bobsells/test-of-caption/

Thanks

Dave

David Niles
Sunsetbay Technologies
Email:  drniles99@hotmail.com
Phone:  613-834-2006
Mobile: 613-852-0757

________________________________

**Comment by arunsathiya** [comment]
@drniles99 It appears the images you were trying to show us are not attached. Can you try logging into this GitHub issue on a browser to upload the images? It's possible that GitHub is not handling images from email replies properly.

But, I had a look at your test site, and this is how the [page you had shared](http://sunsetbaytechnologies.com/bobsells/test-of-caption/) currently looks. 

<img width="707" alt="screenshot 2018-11-11 at 18 06 09" src="https://user-images.githubusercontent.com/18581859/48313014-bd855d80-e5dc-11e8-924a-73aaa4deedaf.png">

**Comment by drniles99** [comment]
Yes,

So you can see the issue/problem.

I did exactly as you instructed and the result is not good.

I attached my images again, but not in the body of the email this time.

You should see what the editor shows, which would be correct and then what wordpress displays, which is not good.

Thanks

Dave

David Niles
Sunsetbay Technologies
Email:  drniles99@hotmail.com
Phone:  613-834-2006
Mobile: 613-852-0757

________________________________

**Comment by paaljoachim** [comment]
Hey @drniles99 
Can you retest with the current version of the Gutenberg plugin 8.3 and let us know how it works for you today? Thanks.

**Comment by paaljoachim** [comment]
Hi

I made a newer issue in 2019 https://github.com/WordPress/gutenberg/issues/17162
which is being tracked in the WordPress 5.7 Github Project board here:
https://github.com/WordPress/gutenberg/projects/52

I will go ahead and close this issue and we will keep the other issue open. 
We hope that a rework of the Image block will soon happen, as there are multiple errors going on.
