### ISSUE TITLE
Bug when entering Vietnamese

### ISSUE THREAD

**Issue by hoanghoa12345** [WordPress/gutenberg#11712]
Version Gutenberg: 4.2.0 
**Describe the bug**
When I type in Vietnamese, some words get stuck together even though I type the space.

**To Reproduce**
1. Go to  post editor
2. I type "bạn thiết"
4. See error: The word immediately turns into "bạnthiết", it auto delete my space.

**Expected behavior**
Fix Vietnamese input and more language...
**Screenshots**
![image](https://user-images.githubusercontent.com/44923253/48301663-f0b7e600-e523-11e8-9c43-0598706c1f08.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 70.x.x

**Comment by swissspidy** [comment]
> Please add the version of Gutenberg you are using in the description.

It would be great if you could let us know which version of Gutenberg and WordPress you are using.

**Comment by hoanghoa12345** [comment]
Thank you for comment! This version Gutenberg is 4.2.0

**Comment by designsimply** [comment]
I tried testing this with WordPress 4.9.8 and Gutenberg 4.2 using Firefox 63.0.1 on macOS 10.13.6 but I was unable to see the problem. However, I am not sure my test is good even after changing the site language to "Tiếng Việt" and my keyboard layout to "Vietnamese" ([27s](https://cloudup.com/cb1v9NQmcQF)). Is there a better way I can do this test?

**Comment by hoanghoa12345** [comment]
I'm using Windows 10 and Chrome version 70. I think it is possible that the font error because Gutenberg automatically remove the space between some Vietnamese words. I use Unikey to typing Vietnamese. This error appears when I edit on Gutenberg. It seems a bit confusing, if the problem does not resolve I will close this post on GitHub.

**Comment by designsimply** [comment]
There is another issue about missing spaces between words at #11853 but it is not exactly the same, so I think we need more testing for this issue and I'll check with the i18n community contributors to see if we can find testing help.
