### ISSUE TITLE
Hyperlink is not showing when changing colour of block

### ISSUE THREAD

**Issue by Sixtina1990** [WordPress/gutenberg#11728]
**Describe the bug**
When you enter a paragraph block and add a link, then change the colour it doesn't show was a hyperlink anymore in a different colour but the same colour as the rest of the text

**To Reproduce**
1. Go to add a paragraph block
2. Add hyperlink in the text
3. Change colour to grey for example

**Expected behavior**
I expect the words where the hyperlink has been added to display in a different colour. Attached is a screenshot where you can see on the top where I didn't change the colour the hyperlink shows, and where I changed the colour it does not show it even though there is a link.  

**Screenshots**
Attachee
<img width="814" alt="screenshot 2018-11-11 at 09 24 18" src="https://user-images.githubusercontent.com/42411182/48311909-a0319e80-e59e-11e8-8c7a-43a8905224cb.png">

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: Safari
 - Version 12.0

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 12.0.1
 - Browser Safari
 - Version  don't know 

**Additional context**
- version of Gutenberg : not sure where to see this information

**Comment by ocean90** [comment]
Thanks for your report! What you're seeing is by design, see #4711 and #10171 for some background. You can adjust this in CSS with the `p.has-text-color a` selector.

**Comment by Sixtina1990** [comment]
Thank you for the answer and resolution @ocean90 :) I wrote in the comments in the other ticket #10171 but got no response. I tried to copy paste the text in my CSS field but got errors. No one has responded to me yet. Would you be able to give me step by step instructions on where to click and what exactly to insert. That would be great help. Thank you so much. :)

**Comment by ocean90** [comment]
@Sixtina1990 The CSS could look like this:

```css
p.has-text-color a {
   color: orange;
}
```

**Comment by Sixtina1990** [comment]
@ocean90 Thank you so much. I just copied it and it works :) You are the best! Have a good day.
