### ISSUE TITLE
Formatting Shortcuts Impact Entire Paragraph When Cursor Is At Start of Paragraph

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11724]
**Describe the bug**
When my cursor is at the start of a paragraph (no text selected), the **_entire paragraph_** is formatted.

**To Reproduce**
1. Make a paragraph block
1. Put cursor at beginning of paragraph
1. Press `CTRL` + `B` or `CTRL` + `I`

**Result:** Entire paragraph is bolded or italicized.

**Expected behavior**
The format is turned on and applied to any new text I type but not any existing text. (This is the behavior when the cursor is anywhere else.)

**Screenshots**
![formatting-shortcuts-entire-paragraph](https://user-images.githubusercontent.com/1238696/48306956-aae52880-e4f7-11e8-81a0-5233c822d819.gif)

In the GIF:
1.  `CTRL` + `B`
2. `CTRL` + `I`

**Desktop (please complete the following information):**
Win 10, Firefox 63 and Chrome 70, WP 5.0-beta3, no plugins

**Comment by designsimply** [comment]
Tested and confirmed with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6 that writing formatters affect the whole paragraph when the caret is in the first position. ([25s](https://cloudup.com/cC-TvAGYZOe))

**Comment by iseulde** [comment]
Fixed by #13697.
