### ISSUE TITLE
How to make any past dates unselectable in DatePicker component?

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#11733]
Will there be any property that can be added to the [DatePicker](https://wordpress.org/gutenberg/handbook/components/date-time/) component and display future dates only?

**Comment by swissspidy** [comment]
I don't think it's possible at the moment, but perhaps it's worth considering

What's your use case for this?

**Comment by mahdiyazdani** [comment]
@swissspidy Thanks for your reply.
I am trying to create a countdown component.

**Comment by youknowriad** [comment]
I'd just suggest going with third-party components for these use-cases. WordPress can't add and maintain all kind of props and components if they're not used in WordPress itself.

**Comment by mahdiyazdani** [comment]
@youknowriad Thanks for your input.
Do you have any preference on this?

**Comment by youknowriad** [comment]
I personally never had such a use-case so I can't give an advice here.

**Comment by mahdiyazdani** [comment]
@youknowriad Still, I believe having this will be useful in post/page schedule also.

**Comment by swissspidy** [comment]
@mahdiyazdani There are many scenarios where people want to change a post's date to the past. There's no reason to disallow that.

**Comment by designsimply** [comment]
Closing this issue with a note to say that the ability to restrict the DatePicker component to future dates only is not something that will be added to the core project and that creating or using a third-party plugin for this use case is the preferred route.
