### ISSUE TITLE
Can’t reorder gallery images on touchscreen 

### ISSUE THREAD

**Issue by johnridesabike** [WordPress/gutenberg#11738]
**Describe the bug**
Drag-and-drop doesn’t seem to work on the edit view for galleries while using a touchscreen. The only way to rearrange the images is to remove and re-add them in a new order. 

**To Reproduce**
1. Go to a Gutenberg post.
2. Insert a gallery and add images.
3. Tap the pencil icon to edit. 
4. Try to drag and drop them. 

**Expected behavior**
The images to rearrange.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 12.1
 - Browser: Safari
 - Version 12

**Additional context**
Sometimes (but not always) it seems that trying to drag the images will scroll the Gutenberg screen in the background. 
Having buttons to rearrange them too would be a suitable fallback.

**Comment by designsimply** [comment]
Tested and confirmed using Safari iOS 12.0.1 on iPad Mini that I cannot drag and drop to rearrange images in a gallery from the "Edit Gallery" modal when Gutenberg is active.

![img_0008](https://user-images.githubusercontent.com/1119271/48362566-2a423b80-e661-11e8-9a1d-05dad156c969.PNG)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15674&action=edit running WordPress 4.9.8 and Gutenberg 4.3 using Safari iOS 12.0.1 on iPad Mini.</sup>

In contrast, if I deactivate Gutenberg and try again, I am able to drag and drop to rearrange images as expected.

![img_0009](https://user-images.githubusercontent.com/1119271/48362903-eb60b580-e661-11e8-8398-a5caa34f8650.PNG)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15675&action=edit running WordPress 4.9.8 using Safari iOS 12.0.1 on iPad Mini.</sup>

**Comment by designsimply** [comment]
Added the `WordPress 5.0.x Follow Ups` milestone for consideration since it was added in #12965.

**Comment by talldan** [comment]
There are now mover buttons on the gallery block images that appear when an individual image is selected, so this is resolved.
![Screen Shot 2020-02-07 at 2 45 53 pm](https://user-images.githubusercontent.com/677833/74007197-b2280a00-49b8-11ea-8cdb-7fb60f2269fc.png)
