### ISSUE TITLE
Showing custom CSS in the Styles preview area

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11735]
**Is your feature request related to a problem? Please describe.**
For a few blocks we have the Styles area showing for example various button, Seperator etc style.
These seem like default CSS showing up in the Styles preview area. It in a sense gives the impression that one can just add the block CSS and create a new styling that will show up in the Styles area.

Example of the Styles area in the Seperator block:
![screen shot 2018-11-11 at 16 31 57](https://user-images.githubusercontent.com/5323259/48314896-392cdd80-e5d0-11e8-9e53-3031a504491b.png)

I believe that there are variants of this same issue.

Having a simple way to add CSS and have it preview up in the Styles area would be awesome.

**Comment by jwold** [comment]
Wanted to make sure I understand the need here. Are you suggesting:

1. If I see a dot block separator, I should expect to see that on the frontend?
or
2. Are you suggesting to add a CSS style field in the sidebar?
or
3. Are you suggesting to add some "styling" options in the sidebar, such as color, size, space, etc?

**Comment by paaljoachim** [comment]
(I apologise for my lack of correct words.)

Default styling here is:
Short Line, Wide Line and Dots.

Clicking the Advanced one will see the CSS:
is-style-default
is-style-wide
is-style-dots

Lets say that I wanted to add a custom style something like this wireframe:

![custom-style-gutenberg](https://user-images.githubusercontent.com/5323259/48320173-c6932080-e616-11e8-8712-305070818716.jpg)

One clicks custom and then clicks the Advanced section and fills in the CSS one chooses to use.
It could start with a suggestion like this:

![is-style-gutenberg](https://user-images.githubusercontent.com/5323259/48320207-1eca2280-e617-11e8-9235-68c8b6d55e87.jpg)

One fills in with the word thick.
![is-style-thick-gutenberg](https://user-images.githubusercontent.com/5323259/48320228-5042ee00-e617-11e8-968f-b99fb6800cf3.jpg)

One then goes to the style.css or similar fills in the CSS:
```
.is-style-thick {
	color: red;
        height: 15px;
	width: 250px;
        margin: auto;
}
```

Then goes back to the Gutenberg editor. The custom style preview box which was earlier empty now shows the CSS used. Something like this:

![style-thick-preview](https://user-images.githubusercontent.com/5323259/48320313-a95f5180-e618-11e8-9a49-7554b9bd7497.jpg)

**Comment by mtias** [comment]
I think this is very close to the proposal in #7551. Closing to consolidate.
