### ISSUE TITLE
Cannot Add 2nd Inline Format When Type (Nested Bold & Italic While Typing)

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11743]
**To Reproduce**
1. Start typing.
2. Enable italic via `CTRL` + `I` or clicking the italic button
3. Type a bit in italic
4. Attempt to enable bold with `CTRL` + `B` or clicking the button
5. Continue typing.

The exact buggy behavior seems to differ between browsers.

**In Chrome,** the current style (italic) is closed and the new one (bold) is started so you get italic text followed by bold text but not bold italic text.

**In Firefox,** the current style (italic) simply continues, ignoring the new one (bold), so you get only italic text. (Pictured below)

_Notes:_
1. Attempting to record a GIF of this behavior with LiceCAP sometimes made it work, but not always (see below).
2. Steps 2 and 4 above can be reversed and show the same issue.

**Expected behavior**
It is already possible to nest bold and italic if all the words are written and then formatted via text selection. I should be able to produce the same result as I write.

**Screenshots**
Firefox:
![nested-bold-italic](https://user-images.githubusercontent.com/1238696/48318559-86508580-e5b7-11e8-9fe6-4cfb6cdf8354.gif)

**Desktop (please complete the following information):**
Win 10, Firefox 63 and Chrome 70 (behavior varies, see above), WP 5.0-beta3, Twenty Nineteen, no plugins.

**Comment by designsimply** [comment]
I tested and confirmed with a few different browsers and had some varying results.

In Firefox, pressing "Bold" works but italics stops and I'm moved to the next line:

![italic-and-bold-wp4 9 8-g4 3 0-rc 1-firefox63-macos](https://user-images.githubusercontent.com/1119271/48352262-8b5e1500-e649-11e8-8833-4b49c7685b28.gif)

In Chrome and Safari, I see the same result as you, bold does not work if I'm already within an inline boundary for italics:

![italic-and-bold-wp4 9 8-g4 3 0-rc 1-chrome-70-macos](https://user-images.githubusercontent.com/1119271/48352316-af215b00-e649-11e8-9efb-e33f8246f21c.gif)

([Safari gif](https://user-images.githubusercontent.com/1119271/48352612-5ef6c880-e64a-11e8-8a50-9e40c458f38a.gif))

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3.0-rc.1 on macOS 10.13.6. Note: I also tested with master `992a43cdd` and saw the same result (i.e. [Chrome+master](https://user-images.githubusercontent.com/1119271/48352812-fd832980-e64a-11e8-8f35-f6b2c1be9b29.gif)).</sup>
