### ISSUE TITLE
Can't Select Bold/Italic and Type with Format from Start of List Item

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11741]
**Describe the bug**
It's current impossible to select an inline format (bold and italic tests) from the start of any list item (empty or not) except the first and then type with that format.

**To Reproduce**
1. Make a list block.
1. Type in the first item
1. Start a second list item
1. Click the "Bold" format or press `CTRL` + `B` (also works for Italic button / `CTRL` + `I`)
1. Type

**Result:** Text is unformatted (not bold in this example).

**Expected behavior**
I should be able to format the beginning of a list item. This is common especially for a pattern like this:

- **Topic 1:** This is the first topic.
- **Topic 2:** This is different from the first topic.

**Screenshots**
![demonstrating the steps to reproduce above](https://user-images.githubusercontent.com/1238696/48317538-cb20f000-e5a8-11e8-9909-24c6ae411704.gif)

**Desktop (please complete the following information):**
Win 10, Firefox 63 and Chrome 70, WP 5.0-beta3, no plugins, Twenty Nineteen

**Comment by designsimply** [comment]
Tested and confirmed that the writing formatters such as bold, italic, and strikethrough are unresponsive if the caret is in the first position for any list item except the first list item. If the caret is in the first position for the first list item, the formatters affect the entire list. ([1m23s](https://cloudup.com/c89z5yDVZi1))

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>
