### ISSUE TITLE
Media and Text block alignment inconsistency

### ISSUE THREAD

**Issue by timelsass** [WordPress/gutenberg#11745]
**Describe the bug**
Editor displays media and text block like:
![media-text-block-editor](https://user-images.githubusercontent.com/11907254/48325304-ee788900-e602-11e8-9a61-eaf7d16a50be.png)

and frontend displays it as:
![media-text-block-front-end](https://user-images.githubusercontent.com/11907254/48325306-f1737980-e602-11e8-9628-8b92ac9737fa.png)

**To Reproduce**
1. Add a media and text block to a page.
2. I only added text and no media to the block.  Alignment in the editor shows the text on the left.
3. Save and publish - view frontend of site.
-- The result is that the frontend displays the text block to the right.

**Expected behavior**
I believe the editor should match the frontend, so the block position should be on the left/right depending on the user's selection - regardless of the user adding media to the column.

**Additional context**
- gutenberg 4.2.0-rc.1

**Comment by youknowriad** [comment]
I can't reproduce personally, Maybe a theme issue?

**Comment by timelsass** [comment]
It's possible, I am testing on twentyninteen master.  I just went to try and replicate the issue, and it appeared to be working at first glance and position was correct.  I think it happens after initially publishing the content, and then changing it after.

further steps to replicate:

1. I published the block with no media added on the left, and text added to heading/paragraph on the right in the editor.
2. Front end was matching.
3. I went back into the editor, and change the alignment to text/heading on the left and empty media block on the right.
4. Saved and published.
5. Front end still has the text/heading column on the right instead of the left as shown in the editor.

**Comment by designsimply** [comment]
I tested and was unable to replicate the problem using WordPress 4.9.8 and Gutenberg 4.6 `master` @ `4178f2da4` with Firefox 63.0.3 on macOS 10.13.6—the updates for alignment I make to the Media & Text block in the editor match with what I see on the front end. ([1m9s](https://cloudup.com/cOOQsDPGKnh))

1. Go to Posts > Add New.
1. Add a Media & Text block.
1. Add some text and leave the media side blank.
1. Preview the post.
1. Edit the block alignment to "Show media on right."
1. Publish and view the post.

@timelsass if you're still having trouble after updating to the latest version (4.6 as of this writing), please have a look at my testing steps and let me know if anything is different compared to your steps. It's also worth noting recent updates have been made to how data is saved on preview so it would be good to pay attention to whether preview is explicitly clicked or not during your steps and what buttons you click exactly and when (i.e. was your step 1 a published post or just a draft? did you ever click preview during your testing steps?).
