### ISSUE TITLE
Support full block alignment width for reusable blocks

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#11755]
When you set a full width block to be reusable it forces it to be set into the standard editor width. 

It would be ideal if it kept the block alignment width to correctly represent how it'll look on the front-end.

**Comment by brettsmason** [comment]
@paulwilde This sounds like the same issue I reported in #8288.
Could you confirm that's the case?

**Comment by paulwilde** [comment]
This is indeed a duplicate. I’ll close it as such.
