### ISSUE TITLE
How to trigger a rerender of innerblocks when parent attribute is changed

### ISSUE THREAD

**Issue by s-ferdie** [WordPress/gutenberg#11776]
Parent
```
<InnerBlocks template={['myblock/child', { parentAttr }] } />
```
Update parent attributes that is passed down to the innerblock template
```
setAttributes( {
  parentAttr: 'New value',
} );
```
However, when I update the parentAttr inside the parent block, it doesn't update or triggers a rerender of the child block save method. The parentAttr remains the old value.

Child
```
save: ( {attributes} ) => {
	const { parentAttr } = props.attributes; // is never updated from the parent block it keeps it's initial value
	return <div className={parentAttr}></div>;
},
```

Is there a way to rerender innerblocks or force an update?

**Comment by youknowriad** [comment]
You can use the `clientId` prop in your inner block with `withSelect` in the `edit` function of your child block to retrieve attributes of the parent block. But you can't use parent attributes in `save` functions.

**Comment by jiteshdhamaniya** [comment]
**I tried with setAttiributes too but it does not seem to rerender. can you help what mistake I am making? **
