### ISSUE TITLE
Backend performance slow on certain block(s)....

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11770]
**Describe the bug**
Generally I have fast performance, except on pages like these:
https://www.disciples-fellowship.org/messages-2018/
https://www.disciples-fellowship.org/messages-2017/

These pages have about 40 Columns blocks, and about 40 Audio blocks. 

Column 1 has a Paragraph block; Column 2 has an Audio block. This is repeated through about 40 occurrences.

I assume it's either the Columns or Audio. I have not researched which one makes the slow performance.

**To Reproduce**
1. Create a page with many Columns blocks
2. Create a page with many Audio blocks.
3. backend performance is really bad....

Been experiencing this since these pages were created (about 3.0 (+/-) to the current 4.3).

**Comment by lkraav** [comment]
@dmsnell I have "performance-problem" content and staging site access I can share to demonstrate reproduction. What's a private medium we can exchange access credentials on?

**Comment by GlennMartin1** [comment]
Thanks for your patience.

In my case, yes, the page renders fine. The issue is slow response when typing, focus changes, etc...

For example, if I create type into a paragraph block, it may not show on the screen until I wait a second or two.

Same thing when I click on another block; it doesn't get focus for a second or two, and it feels like it didn't get the mouse click - until suddenly I see it catch up.

That general slowness is in many operations - but again, only on these two pages. Otherwise, I have no performance problems elsewhere on any Gutenberg site.

I have not done any timing. It's not super L-O-N-G, but it's it's easily long enough to notice and get confused why nothing is immediately appearing as I try to interact with a page.

My theme is Storefront (by WooCommerce).

The active plugins are 11 popular ones:
- Akismet Anti-Spam
- Contact Form 7
- Google Analytics Dashboard
- Gutenberg
- ManageWP - Worker
- Print Post and Page
- Storefront Blog Customiser
- Storefront Footer Bar
- Storefront Powerpack
- WooCommerce Helper
- Yoast SEO

I could create a staging site and give credentials, if that would be helpful.

I have not copied the post to another install. All my installs are on the same setup (WP-Engine), and my site otherwise is very fast.
