### ISSUE TITLE
Save reusable blocks on "Save"

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11784]
Saving a post/page should also first save edited reusable blocks. 

To reproduce:
1. On a page/post, edit a reusable block.
2. Forget to hit "save" on the reusable block. 
3. Save the page/post.
4. Note that the reusable block edit is lost.

It seems expected behavior is that the edited reusable block would be automatically saved in the page/post Save. 

Using 4.3.0.

**Comment by molszewska** [comment]
I couldn't see the option to edit the reusable block. However, while creating a new reusable block, I didn't save its title and I published the page - the block was preserved.

**Comment by sourourn** [comment]
Same for me ^. There was no option to edit the re-usable block once it was added. The edit button is greyed out. 
![Screen Shot on 2019-05-12 at 10-56-39](https://user-images.githubusercontent.com/39188945/57580029-01322480-74a5-11e9-86ee-8a7bfdc089e9.png)

WordPress Version 5.2
Browser: Firefox 61.0.2
Mac OS

**Comment by mlbrgl** [comment]
On 5.2.2, I am seeing both behaviours described:

- @GlennMartin1: on **editing** a previously added reusable block + save post
Result: reusable block edits are lost

- @molszewska: on **creating** a new reusable block + save post
Result: reusable block edits are preserved, title is lost (defaults to "Untitled Reusable Block")

In both cases, the reusable block "Save" button is bypassed. In both cases, the expected result is that reusable blocks edits are preserved (including their respective title).

**Comment by skorasaurus** [comment]
I can confirm @GlennMartin1 's bug on Gutenberg 7.5.0 (WP 5.3.2); the 'needs testing' label can be removed.

**Comment by noisysocks** [comment]
Yes, this is a flaw in the current design of Reusable Blocks.

I'd like to see this issue addressed by incorporating Reusable Blocks into the "Update Design" flow being worked on in https://github.com/WordPress/gutenberg/issues/20421.
