### ISSUE TITLE
Title Readability in other language. (in my case, Korean)

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#11786]
I can't speak English well. Please understand me. 

![cap 2018-11-13 00-47-16-547](https://user-images.githubusercontent.com/44285360/48383430-0ea26800-e729-11e8-9a61-3228d233c30f.png)
I just wrote any words~~

In this picture, ① is English and  ② is Korean. The important thing is... ② is one word. in that picture, starbucks is in next line because starbucks is a long word. but that '한국어능력시험' and '실전모의고사토목' is a long word too but it is not on the next line. It makes my blogs look bad... bad readability... Please fix it.

**Comment by designsimply** [comment]
@jasmussen would `word-break: keep-all;` fix this or would that possibly present other unforeseen problems? ([41s](https://cloudup.com/c-ptlkPJDBE))

**Comment by MYIG** [comment]
um... I don't know about it well because I am not a developer. but I think it is kinda problem about another language. English has no problem with it. I think it is problem about wordpress. Fix it please...

**Comment by jasmussen** [comment]
Good question, Sheri. I'm going to ask @kjellr and @MichaelArestad here. I'm pretty sure we added the break-all for a reason back in the day, but perhaps with their vast CSS knowledge they can shed some light?

**Comment by kjellr** [comment]
Yes, I believe `word-break: keep-all;` is what we want to use here. That's what we added to paragraph text in Twenty Nineteen after a similar issue arose. 

The [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Values) notes that when specifying `keep all` there, "Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as for normal." So adding that generally keeps the same behavior we have, but with improved treatment of words in those languages. 

I'm not 100% sure if we should remove the existing `word-wrap: break-all` rule, or just add the `word-break: keep-all;` rule in addition. Browser stylesheets tend to include that or the equivalent `overflow-wrap: break-all` rule on textareas by default, so in my testing at least, it works either way.

**Comment by jasmussen** [comment]
I tried submitting a fix based on suggestions here in https://github.com/WordPress/gutenberg/pull/11907. Hope it fixes it!
