### ISSUE TITLE
reposition of in-between inserter and make it optional

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#11798]
The flashing in-between inserter is not only very irritating, but covers in Gutenberg 4.3 also a part of the paragraph text!
Imagine using Gutenberg for real editing of real (longer) texts:
You have to scroll and read the text ... and the mouse is sliding over it ...
And according to mouse position again and again a (+) Symbol is flashing in the middle of your sight!
And this damn symbol covers a portion of the text too and make it unreadable!

So, please:
1.) If you want to keep this damned (+) between blocks ... give it a position between blocks (whithout covering any content!!!) ... or move it to the left side of the block ...
2.) Make this damned (+) not flashing but (optional) permanent
3.) Make the flashing or the whole (+) between blocks optional (allow to turn it off for real work!)

**Comment by burnuser** [comment]
By the way: Moving the (+) to the left side of the block (above the moving handle) would resolve the problem with classic block where the (+) is not visible at all ...
https://github.com/WordPress/gutenberg/issues/10471

**Comment by designsimply** [comment]
I am including a screenshot for reference showing how a tooltip for the sibling inserter that says "Add block" appears when you hover the mouse over the (+) for a few moments:

![screen shot 2018-11-13 at 11 34 46 am](https://user-images.githubusercontent.com/1119271/48434948-64cad780-e738-11e8-85a8-df22af5b14e3.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15741&action=edit running WordPress 4.9.8 and Gutenberg 4.3 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by burnuser** [comment]
In an earlier Gutenberg version I think the (+) was grey coloured and less obtrusive. Now it flashes in bright blue (like the block identifier on the right side and the block frame too).
I'm not an epileptic or have a dyslexia problem, but in general I think and feel, that there are to much bright flashing interface elements in Gutenberg if editing (reading + follow with mouse pointer) existing texts. (And that is a very common task!)

My suggestions:
a) use more grey (like in classic block) instead of bright blue for all interface elements
b) make all these flashing optional or permanent visible (and/or use a position outside the content)
c) in general: support the content, don't outshine it => keep the whole interface as unobtrusive background ...

**Comment by ZebulanStanphill** [comment]
I made #13571, which proposes an overhaul to the sibling inserter that would get rid of the flashing and change it so that it appeared below the selected block.

**Comment by enriquesanchez** [comment]
Given all the recent improvements and updates to the sibling inserter (#18941, #19456, #19596 and #11969), I believe this issue can be closed now.

Please feel free to reopen on create a new one if necessary.
