### ISSUE TITLE
Improve the Link Popover invalid link appearance

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#11796]
**Description**
Related #11793, #1838.

This issue originates from the PR #11286 where there was some discussion about improving the appearance of invalid links in the URL Popover.

Currently an invalid link is indicated using a red text color (and a screenreader message using `speak()`). Visually, the error state is too subtle and does not adequately convey to the user that there's an issue:
![screen shot 2018-11-09 at 6 40 06 pm](https://user-images.githubusercontent.com/677833/48257987-0b6c5b00-e44f-11e8-9df9-ad7d4f2987b9.png)

#11286 did explore adding an error message to the popover, but was ultimately not included and needs some further design exploration to ensure the popover isn't too busy:
![screen shot 2018-10-31 at 3 51 15 pm](https://user-images.githubusercontent.com/677833/47773403-e37d4900-dd24-11e8-885e-cfb1c8f88132.png)

Relevant comments on the PR:
https://github.com/WordPress/gutenberg/pull/11286#issuecomment-434592716
https://github.com/WordPress/gutenberg/pull/11286#issuecomment-435172870
https://github.com/WordPress/gutenberg/pull/11286#issuecomment-435187711

**Comment by afercia** [comment]
I'd kindly ask to set on this issue the same milestone that was set on #1838 as the original issue isn't fully solved. Note: the proposed text can be way shorter. Thank you.

**Comment by talldan** [comment]
I've added it to that milestone. This still really needs some design input. Unfortunately I'll be afk for a couple of weeks from tomorrow, so can't help push this forwards any further.

**Comment by melchoyce** [comment]
@afercia re your comment in #1838:

> There's also an assertive aria-live message as audible feedback, see:
speak( editor.translate( 'Warning: the link has been inserted but may have errors. Please test it.' ), 'assertive' );
>
> ...
> 
> In this case Chrome doesn't say anything useful. I'd say the visual feedback is not so useful for all users, not just assistive technologies users. 
> 
> It would be great to implement some validation/feedback mechanism to have feature parity with the current editor.

Is this what you're thinking:

![image](https://user-images.githubusercontent.com/2846578/48638930-06079700-e9a0-11e8-9502-eda70a25079b.png)

Or, like in Dan's image, do we need additional visual text present explaining what's wrong with the link? I couldn't tell if you were saying we just need to add the `aria` message, or if we need additional visual feedback.

**Comment by talldan** [comment]
This is fairly outdated now and the UI has changed considerably, so closing.
