### ISSUE TITLE
Block Alignment controls not working on initial render of InnerBlock first child

### ISSUE THREAD

**Issue by leeshadle** [WordPress/gutenberg#11794]
The block alignment controls are not working on the initial render of an InnerBlock first child that supports block alignment.  However, after deselecting the same block and reselecting it, block alignment controls work again.

For example, if I use a ['core/button'] block as the first child of an InnerBlock, when the ['core/button'] block is initially rendered the block alignment controls do not work properly.  However, they work again after deselecting and then reselecting the Button block.

Below is a screenshot of the block alignment controls on initial render.  When block alignment center is selected, data-align should equal "center", not "right".

<img width="471" alt="screen shot 2018-11-12 at 9 15 37 pm" src="https://user-images.githubusercontent.com/557884/48392461-5e007e00-e6c0-11e8-9672-0d983ec9cc26.png">

**Comment by draganescu** [comment]
From my testing @leeshadle the behaviour seems to be correct. Here is what I did:

- in an empty post 
- I added a columns block
- in the left column I added a button block
- right after adding I used the align centre button
- it worked as expected

<img width="703" alt="Screenshot 2019-07-25 at 09 08 13" src="https://user-images.githubusercontent.com/107534/61849996-c5133b00-aebb-11e9-9ec8-2b0c02ef20b8.png">
