### ISSUE TITLE
lockPostSaving not working as expected

### ISSUE THREAD

**Issue by tihomirselak** [WordPress/gutenberg#11809]
**Describe the bug**
when you dispatch lockPostSaving action on data store
wp.data.dispatch('core/editor').lockPostSaving('lockName');
and when check with
wp.data.dispatch('core/editor').lockPostSaving('lockName');
it returns true but update button only looks disabled, you can still click on it and it saves normally

**To Reproduce**
1. dispatch action command 'wp.data.dispatch('core/editor').lockPostSaving('lockName');'
2. Click on 'Update'

**Expected behavior**
Update button should not do any action,

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Chrome
 - Version 70

**Additional context**
- Gutenberg 4.3

**Comment by swissspidy** [comment]
Looking at https://github.com/WordPress/gutenberg/blob/fc034921667ee95e4befe1edd89ae69a4bd646bf/packages/editor/src/components/post-publish-button/index.js it indeed seems like this will only set `aria-disabled` to `true` but not affect the `onClick` handlers.

**Comment by ocean90** [comment]
Related PR with a fix: #11760
