### ISSUE TITLE
Documentation on incompatibilities with React and best practices to avoid them

### ISSUE THREAD

**Issue by roborourke** [WordPress/gutenberg#11805]
**Is your feature request related to a problem? Please describe.**

In #6441 I found that the way React output certain attribute names, specifically those relating to SVG attributes was inconsistent and proprietary. The Gutenberg serialiser wasn't compatible so my blocks would fail validation.

This is fine because the problem can be solved elsewhere, however it would be useful to come up a description of and best practices for handling the known differences between React and `@wordpress/element`.

**Describe the solution you'd like**

The solution is a page of documentation that outlines the key differences to look out for and best practices for avoiding them.

**Comment by paaljoachim** [comment]
Is this issue still relevant?

**Comment by roborourke** [comment]
Possibly not. I think there’s better / proper SVG support baked in now. I’ll close it out, can always be reopened if someone comes across it again.
