### ISSUE TITLE
Media library modal doesn’t update selected gallery images after single image was replaced

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#11801]
**Describe the bug**

I created a custom block based on the code of the gallery block. For each image, I added an edit button via 

```
<MediaUpload
	onSelect={ ( img ) => this.onEditImage(img, index) }
	type="image"
	value={ img.id }
	render={ ( { open } ) => (
		<IconButton
			className="edit-button"
			label={ 'Bild bearbeiten' }
			icon="edit"
			onClick={ open }
		/>
	) }
/>
```

and that `onEditImage` method:

```
onEditImage( image, index ) {
	let alt = image.alt,
		id = image.id,
		url = image.url,
		images = this.props.attributes.images;

	this.props.setAttributes(images[index].alt = alt);
	this.props.setAttributes(images[index].id = id);
	this.props.setAttributes(images[index].url = url);
}
```

Replacing an image with another via the button works fine, however, after clicking the Edit gallery button, the replaced image does not appear but the original one.

This is my edit gallery button:

```
<MediaUpload
	onSelect={ this.onSelectImages }
	allowedTypes={ ALLOWED_MEDIA_TYPES }
	multiple
	gallery
	value={ images.map( ( img ) => img.id ) }
	render={ ( { open } ) => (
		<IconButton
			className="components-toolbar__control"
			label={ __( 'Edit Gallery' ) }
			icon="edit"
			onClick={ open }
		/>
	) }
/>
```

In the post request I can see that the old image ID is passed, but if I `console.log` the `images` before the edit gallery button, I get the correct object with the new image.

**To Reproduce**
1. Modify the core gallery button’s `edit.js`: Add the edit button inside the `li` of the images (https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/edit.js#L252) and the `onEditImage` method before the `render` method (https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/edit.js#L160)
2. Create a gallery.
3. Use one of the edit buttons to replace an image.
4. Everything seems to work.
5. Use the edit gallery button to edit the gallery.
6. See that the new image does not appear but the old one is there.

After updating the post, it works.

**Expected behavior**

The replaced image should appear in the edit gallery modal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 65.0a1 (2018-11-11) (64-Bit)

**Additional context**
- Gutenberg 4.3.0

**Comment by youknowriad** [comment]
Hi There! this seems like it was fixed already. Let me know if it's not the case for you
