### ISSUE TITLE
Unable to save post if WooCommerce plugin is enabed

### ISSUE THREAD

**Issue by andreagrillo** [WordPress/gutenberg#11800]
**Describe the bug**
From Gutenberg 4.2.0 or greater it's not possible to save a post if WooCommerce plugin is enabled. Works fine with Gutenberg before 4.2.0. I have recorded a video for you, please look here: https://www.screencast.com/t/p2J1FQDIaeu 

**To Reproduce**
1. Go to plugins and enable  the latest version of Gutenberg 
2. Click on Posts > Add New and try to publish it. All working fine.
3. Go to plugins, add and enable WooCommerce.
4. Click on Posts > Add New and try to publish it. All working fine.
5. See error: Unable to publish the new post.

**Expected behavior**
It's strange because working fine with Gutenberg 4.1.1 (look the video attached).

**Screenshots**
![gutenberg_issue](https://user-images.githubusercontent.com/14902963/48401950-a2c0ff00-e72a-11e8-9b29-d6fc93db0a66.png)
https://prnt.sc/lhpveo

**Screencast**
https://www.screencast.com/t/p2J1FQDIaeu 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 
 - Version 64.0b8 (64-bit) - Developers edition

**Additional context**
- Tested with Gutenberg 4.3.0

I have found this error in debug.log file:

```
[12-Nov-2018 16:33:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function is_user_logged_in() in /srv/www/wc_3_5/public_html/wp-includes/l10n.php:137
Stack trace:
#0 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(1051): determine_locale()
#1 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(1013): _get_path_to_translation_from_lang_dir('woocommerce')
#2 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(983): _get_path_to_translation('woocommerce')
#3 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(1081): _load_textdomain_just_in_time('woocommerce')
#4 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(170): get_translations_for_domain('woocommerce')
#5 /srv/www/wc_3_5/public_html/wp-includes/l10n.php(250): translate('WooCommerce', 'woocommerce')
#6 /srv/www/wc_3_5/public_html/wp-content/plugins/woocommerce/includes/class-wc-privacy.php(31): __('WooCommerce', 'woocommerce')
#7 /srv/www/wc_3_5/public_html/wp-content/plugins/woocommerce/includes/class-wc-privacy.php(353): WC_Privacy->__construct()
#8 /srv/www/wc_3_5/public_html/wp-content/plug in /srv/www/wc_3_5/public_html/wp-includes/l10n.php on line 137
```
The problem disappear If you open the file woocommerce/includes/class-wc-privacy.php and add return false in class constructor method: 
![gutenberg_temporary_fix](https://user-images.githubusercontent.com/14902963/48401978-b9ffec80-e72a-11e8-946b-608f22f79474.png)
http://prntscr.com/lhpyjv 

Thanks for your time! 
I'm ready to help if needed. 
Have a nice day
AG

**Comment by swissspidy** [comment]
Does this still happen with WordPress 5.0 Beta 4?

**Comment by andreagrillo** [comment]
Hi @swissspidy,

I have tested it yesterday with WordPress 5.0 Beta 3. I have update WordPress to 5.0-beta4 and the problem disappears.

Thanks for your fast reply.
AG

**Comment by swissspidy** [comment]
Awesome, great to hear!

I'm therefore closing this issue for now.
