### ISSUE TITLE
Exit Code Editor button is hidden when notices show up

### ISSUE THREAD

**Issue by Rahmon** [WordPress/gutenberg#11807]
**Describe the bug**
Exit Code Editor button is hidden when notices show up. This bug occurs only in desktop.

**To Reproduce**
1. Switch to Code Editor.
2. Make some change and update.
3. The notice show up and Exit Code Editor button get hidden. 

**Expected behavior**
Exit Code Editor button always visible while Code Editor mode is enabled.

**Screenshots**
Desktop:
![desktop](https://user-images.githubusercontent.com/6010232/48407812-dbf37200-e71e-11e8-8cdf-cf631263bcd8.gif)

Mobile (works as expected):
![mobile](https://user-images.githubusercontent.com/6010232/48407848-f0d00580-e71e-11e8-9cb0-e8fa2df70876.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 70

**Comment by aduth** [comment]
@youknowriad While I think it's fair to say that #15594 would resolve this as far as the immediate issue of the save confirmation blocking the button, it would still remain an issue for any other notice which occupies this space.

I think it would be good to have a similar treatment to pushing down content in the code editor as @jasmussen had previously implemented for the visual editor in #13614.

**Comment by youknowriad** [comment]
> I think it would be good to have a similar treatment to pushing down content in the code editor as @jasmussen had previously implemented for the visual editor in #13614.

This is already implemented but not for all the notices. I think once the more temporary notices become snackbar notices, this could be considered to be applied to all the remaining notices.
