### ISSUE TITLE
Conversion support when copy/pasting Markdown into the editor.

### ISSUE THREAD

**Issue by kopepasah** [WordPress/gutenberg#1180]
During last weeks #core-editor Dev chat there was a little discussion about Markdown and even mention of having a Markdown block. In addition, #71 mentions adding keyboard support for some "Markdown-esque shortcuts/syntactic sugar".

However, I believe support for Markdown should go beyond just one block, especially in the case writers copy/pasting Markdown into the editor (no to mention copy/pasting from other editors, like Word).

So, for example, if a writer pastes the following into the editor:

```
## Super Cool h2
```

would be cool if the editor converted this to:

```
<!-- wp:core/heading -->
<h2>Super cool h2.</h2>
<!-- /wp:core/heading -->
```

**Comment by kopepasah** [comment]
Also, when typing Markdown into the text portion of the Editor, it is converted from:

```
## There is something funny.

- Hello there my friend.
- Lots of love.

### Heading 3
```

to

```
<!-- wp:core/freeform -->
## There is something funny. - Hello there my friend. - Lots of love. ### Heading 3
<!-- /wp:core/freeform -->
```

Which causes the Markdown module in Jetpack to output everything as an `h2`.

**Comment by aduth** [comment]
Related: [Formatting shortcuts](https://codex.wordpress.org/Keyboard_Shortcuts#Formatting_Shortcuts)

**Comment by jasmussen** [comment]
Also related: 

- The Newline is the Commandline #834 
- Keyboard Support: #71

**Comment by mtias** [comment]
This has been mostly implemented. If there are remaining items to handle, let's open individual issues.
