### ISSUE TITLE
Auto remove empty blocks

### ISSUE THREAD

**Issue by kopepasah** [WordPress/gutenberg#1181]
As mentioned in #1171, it is quite easy to create a bunch of empty blocks when typing and it would be nice to remove a block if it is empty, either on `focusout` or save/publish.

Considerations:

- When a block loses focus, the user may not want the block to be removed.

**Comment by aduth** [comment]
Another consideration: From a data / attributes perspective, what does it mean to say that a block is "empty"?

**Comment by jasmussen** [comment]
I'm reluctant on this one, in part because the user might _want_ that extra space that an empty `p` provides. Worth thinking about, in context of the influx of feedback we'll probably get soon.

**Comment by kristarella** [comment]
> I'm reluctant on this one, in part because the user might want that extra space that an empty p provides. Worth thinking about, in context of the influx of feedback we'll probably get soon.

I agree that someone might want to add an empty block. Maybe there could be a "space" block in the Layout Blocks, or an option on the Separator Block to hide the line?

The other thing to consider if empty blocks were to be removed, when would it happen? Presumably there will be autosave and it would be terrible to do it then. Perhaps on publish?

**Comment by aaronjorbin** [comment]
Even if not automatic, there should be a way to remove an empty block.  If there is a way right now, it's not obvious to me.

**Comment by aduth** [comment]
@aaronjorbin See also #130, #1251

It is currently possible in text blocks by pressing backspace in an empty text block, as long as it's not the first. Or by selecting but not focusing the editable field and pressing backspace (a little bit of a challenge, have to click at the border).

**Comment by jasmussen** [comment]
In addition to making a trash button, should we make the clickable border area bigger?

**Comment by kopepasah** [comment]
I still believe empty block should be removed. If a user wants an empty space, this should be explicit in a block (agree that separator block might be a good option). 

In regards to removing empty blocks, I think this should be an explicit action by the user (clicking a button, for example), rather than an implicit action on save (or other). There might be many cases when a user might add some empty blocks (like image blocks) for a different person to add content later.

**Comment by jasmussen** [comment]
`wpautop` could be seen as precedent for "cleaning up" empty blocks on save. But I agree this feels unpredictable. Not sure what the best approach is, I think I still lean towards letting a user insert empty blocks if they want. (Even though removing them on save would solve some other reports)

> I still believe empty block should be removed. If a user wants an empty space, this should be explicit in a block (agree that separator block might be a good option).

We have a ticket for multiple styles of the separator block #728, one of them could be just space? That said, I still think this would be discoverable. Peope like their linebreaks, it's what works for creating space in any other editor.

**Comment by jasmussen** [comment]
What if, like also discussed in #1171, we embraced writing prompts even more? Here's a full sequence of mockups:

![prompts placeholders hover](https://user-images.githubusercontent.com/1204802/27385130-da6cf3d0-5691-11e7-98d7-e4f15b9e2108.png)
![prompts placeholders](https://user-images.githubusercontent.com/1204802/27385134-dbbd5568-5691-11e7-9e01-44c20d9745d5.png)
![prompts placeholders continue writing](https://user-images.githubusercontent.com/1204802/27385138-dcf23d5e-5691-11e7-8f30-6d606b95458c.png)
![prompts placeholders continue writing hover](https://user-images.githubusercontent.com/1204802/27385141-df5af54a-5691-11e7-9c6d-b4f2b8332fc1.png)
![prompts placeholders write in between](https://user-images.githubusercontent.com/1204802/27385142-e0b8bdd2-5691-11e7-8226-3eccc681e365.png)
![prompts placeholders write inbetween hover](https://user-images.githubusercontent.com/1204802/27385147-e262fab2-5691-11e7-8490-babe68b51d64.png)

**Comment by saracannon** [comment]
The placeholder text is an interesting idea. It will definitely prompt a user to delete if it's empty because the words are not part of their post. When you hover there also be a trash can icon to the right?

**Comment by jasmussen** [comment]
Yep, the trash can will be there on hover.

**Comment by paaljoachim** [comment]
It would give the user better control to have just the title. Then the user clicks the inserter to add a text box OR there could be one text box available on a new page. 

Having a write or continue writing seems confusing. As it automatically inserts a text box without my knowledge or it wanting to do so. Clicking write and suddenly there is another text box below that again. It kinda seems like a bug and not intended. Having a Write or Continue Writing is assuming that the user wants to add another text box, but that might not be the case.

![text-flow-gutenberg](https://user-images.githubusercontent.com/5323259/27503173-dee6adfe-5847-11e7-96c4-3c56ede9bfc6.gif)

- Clicking twice creates another text box.
- Clicking Write or Continue Writing adds another text box.
Both of these takes away the control the user has over their own layout.

**Comment by jasmussen** [comment]
@paaljoachim 

To be clear, the placeholder is just a an indicator, it isn't actually a textfield until you create it. It's necessary for you to be able to quickly get writing again after inserting an image as the last block. Without it you'd have to click "insert > Text", which gets tired quick.

@mtias had some ideas for how to improve this, though. For example we can show it when you're done typing.

**Comment by paaljoachim** [comment]
So what I am understanding here is the importance of having a quick way to add more text without having to insert -> Text. Do we need a quick bar or some other visible way to add text and other most used blocks? 
There can also be shortcuts for adding the most used blocks. That could perhaps be listed beside the block inside the inserter. Just like a bunch of other programs. I can create a new issue for block shortcuts.

![gutenberg-quickbar](https://user-images.githubusercontent.com/5323259/27511408-5477a646-58f1-11e7-950a-ceed0c5ba61e.jpg)

I am not sure what I think of the above wireframe I just made. Visually it might just be too much. As we should have as little as possible cluttering the layout screen.

**Comment by karmatosed** [comment]
Some apt user feedback from tests:

"I found the Write placeholder initially helpful before I added my first block. After I'd added a block I found it unhelpful & actually confusing. I wasn't sure where clicking the + icon would add the new block"

"I unintentionally created 3 extra blank blocks before properly adding the image blog"

Empty-blockitis is a frequent test result.

**Comment by jasmussen** [comment]
I'm not convinced empty blocks is a problem. They can be a nice way to add linebreaks. But the "Write..." prompt makes it worse, I admit.

What if the write prompt was only visible if you hovered or clicked the block?

**Comment by mtias** [comment]
Let's see how the latest changes help with this before trying something else here.

**Comment by youknowriad** [comment]
Should we consider this as resolved with the current placeholders showing exactly the empty paragraphs?

**Comment by jasmussen** [comment]
I think so, yes. We can always reopen if we need to.
