### ISSUE TITLE
Plugin compatibility question about footnotes plugin

### ISSUE THREAD

**Issue by AdmPolli** [WordPress/gutenberg#11818]
Is it possible to integrate functions like in the footnotes-plugin into the new editor?
https://de.wordpress.org/plugins/footnotes/
I also use wordpress for scientific publications. Above all, it is of advantage in times of "fake news" to have the possibility to use academically correct sources by using footnotes in an easy way.

**Comment by youknowriad** [comment]
It is possible to build such features using the format API. You should check this plugin https://wordpress.org/plugins/advanced-rich-text-tools/ It uses the format API.

The docs for the format API are not polished yet but they are being worked on. Thanks.
