### ISSUE TITLE
(Firefox) Misplaced caret when selecting a RichText element

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#11812]
## Describe the bug

Caret is erroneously positioned at the start of a RichText element when selecting a block in Firefox.

## To Reproduce

1. Start with a post (I'm using a [sizable post provided here](https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030)).
2. Make sure no blocks are selected.
3. Click on the end of a textful RichText element, or click in the middle of the text.
4. **Observed:** Caret is positioned at the start of the element.

## Expected behavior

Caret should be placed where I clicked.

## Screenshots

![richtext-caret-firefox](https://user-images.githubusercontent.com/150562/48416451-276e4600-e748-11e8-9a25-4757c5c02f9e.gif)

## Desktop (please complete the following information):

 - OS: macOS
 - Browser: Firefox Developer Edition

**Comment by nosolosw** [comment]
I can repro this in Ubuntu Linux, Firefox 63.

It looks like this happens only the _first_ time a block is selected. If I repeat the steps outlined by @mcsf the caret ends up in the proper position second and subsequent times.

**Comment by nosolosw** [comment]
In my testing, step 2 above (making sure no block is selected) isn't necessary, I can always repro the _first_ time a block is selected.

**Comment by nosolosw** [comment]
This is what I know so far. When this bug is reproduced:

* [`createRecord`](https://github.com/WordPress/gutenberg/blob/093e6fdc111d164afe2254cc0e548900acc4322f/packages/editor/src/components/rich-text/index.js#L239) returns 0 as the `start` and `end` positions. 
* `window.getSelection()` returns 0 as its `anchorOfftset` and `focusOffset`. Accordingly, `getAnchorAt( 0 )` returns also 0 for `startOffset` and `endOffset`.

The offset values for selection/range are properly set when the behavior is correct.

Checked [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection) and [canisue](https://caniuse.com/#search=getselection) for compatibility issues but didn't find any.

**Comment by nosolosw** [comment]
No, it hasn't solved this.

**Comment by nosolosw** [comment]
I'm struggling to find a minimal reproducible case to report to bugzilla.

Searching in the database I've found this one: [getSelection() returns wrong anchorNode/anchorOffset when selection contains nested different contenteditable context](https://bugzilla.mozilla.org/show_bug.cgi?id=1417535). It points to [this jsfiddle](https://jsfiddle.net/varoot/gt0xm5mn/) to play with the testcase.

**Comment by iseulde** [comment]
I can look into this issue, but it seems slightly less pressing atm?

**Comment by mcsf** [comment]
I'm sure other issues are more pressing, but this one is nevertheless a pretty bad experience.

**Comment by mcsf** [comment]
Since this is a browser issue and we need to really focus on our priorities, punting to _Follow-Ups_.

**Comment by danielbachhuber** [comment]
I've run into this issue too on the latest master. Here's a GIF of my experience:

![clicktarget](https://user-images.githubusercontent.com/36432/48777837-85d77f00-ec88-11e8-9577-cf866e5d10b1.gif)

**Comment by mcsf** [comment]
Just for the record, I can still repro this, but I've also noticed that the caret only gets misplaced (at the beginning of the element) if that RichText element has never been focused before. Once a RichText element `A` has been focused, then placing the caret in some other field/block, then placing it back on `A` will result in the caret being properly placed.
