### ISSUE TITLE
 When use IME, The conversion of the first character is automatically determined.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#11813]
**Describe the bug**
Related #11795 
When use IME, The conversion of the first character is automatically determined. 

This problem occurs in the component using `<RichText>` .

**To Reproduce**
1. Create new post.
2. Input text.
3. Delete text.
4. Re-Input Text.

**Screenshots**

![output](https://user-images.githubusercontent.com/1908815/48420064-ddfc1600-e79c-11e8-88ca-fb7e423d3cdd.gif)

**Desktop (please complete the following information):**
 - OS: OS X 10.14.1
 - Browser Chrome
 - Version 70

**Comment by torounit** [comment]
This issue occur after https://github.com/WordPress/gutenberg/commit/4741104c2e035a6b80ab7e01031a9d4086b3f75d

**Comment by miminari** [comment]
I'm afraid that it may be quite troublesome in Japanese and the other non-latin languages.
It occurs in my environment.

* OS: OS X 10.12.6
* Browser: Chrome ( Version 70.0.3538.77 )
* IME: Google IME or OS Default

**Comment by atachibana** [comment]
I verified it on Windows 10, and Chrome caused the same issue for both Google IME and MS IME.
Edge was OK for both IMEs.

Windows 10 Pro Japanese
Google IME and/or MS-IME
Chrome 70.0.3538.77
Edge 42.17134.1.0

**Comment by waviaei** [comment]
I find it unstable -- I was able to reproduce yesterday, but not today. But #11795 , I can always reproduce, and I guess it is related.

- OS: macOS High Sierra
- Browser Firefox
- Version 63.0.1

I use 5.0-beta4-43896.
Only plugin activated is the Beta Tester.

**Comment by iseulde** [comment]
@torounit Would you be able to test #11908 to see if the issue still occurs? It's just an attempt, but maybe it works. Thanks a lot!

**Comment by iseulde** [comment]
@torounit Updated the branch. The first commit only wouldn't work properly.

**Comment by iseulde** [comment]
[gutenberg.zip](https://github.com/WordPress/gutenberg/files/2585346/gutenberg.zip)

The plugin zip if it makes testing easier.

**Comment by mongonta0716** [comment]
I am testing it easily on Windows 10.

Japanese can now be entered, but after fixing the sentence, pressing BS-Key will cause the block to disappear.

Blocks disappear only in Firefox and Chrome.
Edge has no problem.
In Edge, pressing BS-Key will only delete one character.

**Comment by iseulde** [comment]
Fixed by #11908.
