### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined Gutenberg 4.3.0

### ISSUE THREAD

**Issue by MertcanGokgoz** [WordPress/gutenberg#11830]
**Describe the bug**

It gives an error and does not open the page

**To Reproduce**

1. Go to posts and create new post
2. White screeen with wordpress posts area(wp-admin/post-new.php) and it gives an error 

**Expected behavior**
normal editor func

**Screenshots**
![installed-plugins](https://vgy.me/tRWCp9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 70.0.3538.102

**Additional context**

Plugins

![installed-plugins](https://vgy.me/0LAXzi.png)

```
Redis Extension: 4.1.1
CloudFlare: Yes
Predis Client: 1.1.1
PHP Version: 7.2
Multisite: No
```

**Comment by designsimply** [comment]
Are those plugins all active? I noticed there's one called "Disable REST API" and Gutenberg does require the REST API to be enabled. Can you try deactivating and deleting the "Disable REST API" plugin as a first troubleshooting step? You may need to clear cache after making the change. If that doesn't help, try temporarily deactivating the Shield Security plugin as a next step.

I am noting the errors from the first screenshot in plain text for reference:

> Uncaught TypeError: Object(…) is not a function
> TypeError: Cannot read property 'length' of undefined
> Uncaught (in promise) TypeError: Cannot read property 'length' of undefined"

**Comment by MertcanGokgoz** [comment]
@designsimply I tried 2 times, the problem doesn't change. I have this problem only when adding new content

sometimes it gives error when adding links.(existing content)

**Comment by designsimply** [comment]
It's possible that one of your other plugins has a conflict. In my experience, plugin conflicts are a good thing to check first but it's also possible a web server configuration could be a conflict. Is there any chance you are able to test with all other plugins turned off temporarily as a more involved troubleshooting step?

**Comment by MertcanGokgoz** [comment]
Gutenberg 4.2.0 works like a charm but in 4.3.0 (with same configuration & plugins)  throws error. Problem may in changes.

**Comment by thatwpdeveloper** [comment]
I am facing the same issue. Blank WP 5.2.2 install.

Try to add Columns Block with 2 children. After that, in each children, insert a default button. After that, try to navigate through the items in the block by using the up and down keys. It will trigger the error when going from up to down.
