### ISSUE TITLE
RichText: warn when using inline tagName

### ISSUE THREAD

**Issue by p2er** [WordPress/gutenberg#11839]
**Describe the bug**
Create a RichText node in edit function. Fill with text content. Remove text with backspace key (selecting the text and deleting it all together does not cause this issue).  

**To Reproduce**
0. Create Richtext, e.g.
```
<RichText
	tagName={ 'span' }
	value={ citation }
	placeholder={ __( 'Write citation…' ) }
	onChange={
		( nextCitation ) => setAttributes( {
			citation: nextCitation,
		} )
	}
/>
```
1. Enter content into rich text field
2. Safe Document
3. Reload
4. Click into text
5. Delete text by hitting backspace multiple times
6. Last digit can not be removed

Error occurs:
`index.js?ver=1542114671:1 The given range isn't in document.`

**Expected behavior**
Text should be cleared if user tries to delete content letter by letter with backspace.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: all

**Additional context**
- Gutenberg Version 4.3.0
- Wordpress Version 4.9.8

**Comment by p2er** [comment]
I was able to narrow down the problem. In the current quote/pullquote implementation the richtext is only rendered if isSelected is true or richtext is not empty `{ ( ! RichText.isEmpty( citation ) || isSelected ) && (...) }`
The problem occurs If this code is removed.

**Comment by ktmn** [comment]
```
<RichText
	tagName={ 'span' }
```

Does it also happen with div? Inline elements and richtext/tinymce don't work well together.

**Comment by iseulde** [comment]
Sounds like we'll have to start warning on the use of RichText with inline elements.

**Comment by vicolaspetru** [comment]
So, is there a way to fix this bug? I have the same problem with when delete text by hitting backspace multiple times. :(

**Comment by iseulde** [comment]
@vicolaspetru you shouldn't use RichText with tagName=span.
