### ISSUE TITLE
"Start writing or type / to choose a block" bleeds into symbols

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#11837]
We thought about translating it shorter but it's a general issue:

![image](https://user-images.githubusercontent.com/18373563/48467742-14ac4d80-e7ea-11e8-949a-40031cec7c20.png)

**Comment by designsimply** [comment]
Thanks for the report! Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/11425.
