### ISSUE TITLE
Consider adding a sibling inserter (+) button below the last current block

### ISSUE THREAD

**Issue by RobStino** [WordPress/gutenberg#11832]
**Describe the bug**
When typing away in a paragraph block the UI no longer presents the inline `+` button to the left. This button is available in other circumstances, but not when the most recent, or bottom, block is a paragraph block. This presents an inconsistent experience and mean the user has to click elsewhere (out of the natural top-down flow) to add a new block.

Recording of the experience -> https://d.pr/v/RX7SaO

**To Reproduce**
1. Create new post
2. Start typing (add paragraph block)
3. Note that the left/inline `+` button doesn't appear when hovering below the current paragraph block

**Expected behavior**
Expected the inline `+` button to appear when hovering below the current paragraph block.

**Screenshots**
https://d.pr/v/RX7SaO

**Desktop (please complete the following information):**
 - OS: MacOS (10.14.1)
 - Browser: Chrome (70.0.3538.77)

**Additional context**
- Gutenberg Version: 4.3.0

**Comment by designsimply** [comment]
Noting some related issues:

* #7271
* #8363

**Comment by ocean90** [comment]
Some duplicates: #11445, #10519, #11329

**Comment by RobStino** [comment]
@designsimply @ocean90 Thanks for linking to the duplicates. I did look through the existing issues, but didn't spot them.
Happy to close this one if appropriate.

**Comment by mtias** [comment]
@RobStino if you want to add your thoughts to https://github.com/WordPress/gutenberg/issues/10519 that'd be ace! Then we can consolidate the improvements to be made.
