### ISSUE TITLE
Setting the paragraph's font size to blank using the input element of type "number", results the paragraph does not exist in the post

### ISSUE THREAD

**Issue by thingsym** [WordPress/gutenberg#11836]
**Describe the bug**

When editing a Paragraph block setting a font size and then the paragraph does not exist in the post.

The editor display of Gutenberg has the correct behavior.

But the paragraph HTML tag has not been generated in the post.
Or stylesheet font size setting is 0.

**To Reproduce**

1. Select a paragraph block and input text.
2. Set font size to **1** using up button in the input element of type "number".
3. Set font size to **blank** using down button in the input element of type "number".
4. Note empty font size input.
5. Push Preview, Publish or Update button.
6. View Post.
7. The paragraph does not exist.

**Generated code (switch the Code Editor)**

```
<!-- wp:paragraph {"customFontSize":0} -->
<p style="font-size:0">paragraph's font size error paragraph's font size error</p>
<!-- /wp:paragraph -->
```

**Screenshots**

![paragraph-issue](https://user-images.githubusercontent.com/1084604/48463834-c7979e00-e820-11e8-86c4-c42dde528510.gif)

**Expected behavior**

- The behavior should match Normal font size.
- The Paragraph should be displayed in the post with Normal font size.
- Font Size should be Normal if input element is blank.

**Desktop (please complete the following information):**

- macOS Sierra
- Browser Chrome
- Version 70.0.3538.77

**Additional context**

- WordPress version 5.0-beta4
- Gutenberg version 4.3.0

**Comment by designsimply** [comment]
Possibly a regression of #9191.

**Comment by bdbch** [comment]
Did you check your browsers inspector if the element is there? Usually a 0px font-size on any element causes the text to disappear which makes sense if you consider 0px being 0px on your screen. :)

**Comment by ellatrix** [comment]
I'm still getting `style="font-size:0"`.

**Comment by thehenrybyrd** [comment]
Ran into this today in #2181592-zen (internal reference) and reproduced on my own site.

Reducing the size to 0 (blank box) shows the font at a normal size in editor, but still gives font-size=0 when published.

Backend GIF (Calypso):
![fontsize](https://user-images.githubusercontent.com/15107387/61291209-83f19b80-a7d6-11e9-9dc5-c705b40f7958.gif)

And here's what it looks like when published:
<img width="683" alt="Screen Shot 2019-07-16 at 2 28 17 PM" src="https://user-images.githubusercontent.com/15107387/61291244-a8e60e80-a7d6-11e9-8363-cd40e85dd6dd.png">

<img width="439" alt="Screen Shot 2019-07-16 at 2 28 04 PM" src="https://user-images.githubusercontent.com/15107387/61291251-ad122c00-a7d6-11e9-8a63-297e86e6322a.png">

We should either show '0' in the font-size box when reducing from '1', and show the font disappearing entirely (perhaps with some message that font-size is 0), or perhaps not allow font size to be 0.

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7 beta 3.
Changing to font size 1 and then blank. Then previewing I am seeing the font size as default/normal size.

I believe this issue has been fixed. If I am mistaken then we can of course reopen the issue.
Thanks!
