### ISSUE TITLE
block_enqueue_script action does not exist

### ISSUE THREAD

**Issue by selul** [WordPress/gutenberg#1184]
I tried to follow the [README](https://github.com/WordPress/gutenberg/blob/master/blocks/README.md#getting-started) for building a block in a separate plugin but it seems the `block_enqueue_scripts` action hook does not exists and the js file responsible for the block is not being loaded. 

Would be a good idea to load it using a `admin_enqueue_script` until this hook will be added ?

**Comment by youknowriad** [comment]
It's awesome that you're trying to build a blocks plugin 👍. Your feedback will be very useful.
Since we're close the first Gutenberg plugin release, we should add the `block_enqueue_scripts ` the hook soon.

For now, I think using `admin_enqueue_script` is fine (Just make sure to tweak the priority to load it after Gutenberg scripts).

Also, note that the Blocks API is not frozen yet and is subject to change.

**Comment by selul** [comment]
@youknowriad thanks for your feedback.

I tried to add the hook into the `gutenberg_scripts_and_styles` function for the moment and i've have sent a PR in case is useful.

**Comment by aduth** [comment]
I'm wondering if we need a separate action, or if it's sufficient to merely hook `admin_enqueue_scripts`, so long as the script you're enqueueing correctly depends upon block scripts.

**Comment by westonruter** [comment]
I think the need for this would be eliminated by #1217 and being able to define assets when you call `register_block_type`.

**Comment by georgestephanis** [comment]
Just generally the entire `blocks/README.md` needs some love -- the JS code is throwing errors too.

**Comment by georgestephanis** [comment]
Also, it's probably better to change it to be enqueued in the footer as if it's in the header I've hit a race condition where registerBlockType isn't defined yet.

Maybe I should just sort this out and then submit a PR for fixing the docs.  Will give it a go, but don't let me (supposedly) working on this prevent anyone else from taking up the mantle.

**Comment by ahmadawais** [comment]
I ended up here with the same question. Where are we at with the custom block at the moment. Since points raised by @georgestephanis are in-fact roadblocks for any extension whatsoever!

**Comment by ahmadawais** [comment]
`wp.blocks` gets undefined as soon as the `block.js` file gets enqueued.

**Comment by georgestephanis** [comment]
Here's what I'm working off of, @ahmadawais -- https://github.com/georgestephanis/gutenberg-tweaks/ -- I'm just trying to sort out how to get anything working third-party.  If you'd like to collaborate on getting something functional, I'd be delighted to add you and we can collab on Slack.

**Comment by ahmadawais** [comment]
@georgestephanis Sure thing, bit away for the moment, but that's exactly what I have had been looking into. `I'm just trying to sort out how to get anything working third-party.` 

It's `mrahmadawais` on slack!

**Comment by ahmadawais** [comment]
@georgestephanis I have created a sample GitHub repo for experimental 3rd party blocks https://github.com/ahmadawais/Gutenberg-Blocks

**Comment by westonruter** [comment]
The hooks have been implemented in #1717.

**Comment by aduth** [comment]
Also #1794 for updated docs.
