### ISSUE TITLE
Gallery should be nested image blocks

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#11849]
The gallery block, should be a series of nested image blocks. This makes the implementation clearer and easy to manage.

**Comment by designsimply** [comment]
I am not sure nested image blocks make sense. Could you explain a bit more about why you think a gallery as nested image blocks makes the implementation easier to manage from your point of view? I'm also interested in whether you're coming from an end user perspective or a developer perspective (both are good perspectives, I want to know which you're thinking of and specifics around use cases and whys).

**Comment by karmatosed** [comment]
I don't see how nested blocks helps this, happy to be given more insight though. For now closing this but we can always reopen.
