### ISSUE TITLE
Add permalinks to the document sidebar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#11858]
The current problem is permalinks aren't that discoverable. This has been reported in feedback. Right now, the title on select show the permalink. In phase 2 this likely won't be a case moving into everything being a block, so changing now is important.

@melchoyce worked on a suggested design for this which adds to the document settings (note this adds doesn't remove from title for now):

![link-settings](https://user-images.githubusercontent.com/253067/48484767-ebea7f00-e80e-11e8-91b3-be231314fe18.png)

- On select of title won't be changing, it will still show permalink.
- Publishing flow will still show permalink.
- This is a new panel to be added to document settings.

This ideally would be added before 5.0 as really could help people now. It is based on the existing pattern in the publishing flow, which means it should be easier to implement.

One feature that may want to be added is the ability to copy the link from here easily.

As time is of the essence having this move into a PR would be great to get a feel of this.

**Comment by gziolo** [comment]
What about custom post types? Should it be included, too? I'm asking because it contains distinction for page and post.

**Comment by jorgefilipecosta** [comment]
> What about custom post types? Should it be included, too? I'm asking because it contains distinction between page and post.

My plan is to use the singular CPT label, so it will "Post Link", "Page Link", "Book Link", "Movie Link" etc...

**Comment by mtias** [comment]
Yes, should use the provided and localized CPT label.

**Comment by alexislloyd** [comment]
I really like this solution as it makes the permalink settings more discoverable. The "preview" link below the field also clearly shows the output of the setting for users.

**Comment by jwold** [comment]
Love this proposed change. Permalinks have been a bit hard for me to work with. 

What happens when I click “permalink settings”?
