### ISSUE TITLE
spaces between words are lost when OK post is edited

### ISSUE THREAD

**Issue by RDHeath** [WordPress/gutenberg#11853]
**Describe the bug**
In ver. 4.3.0 I find myself having to correct missing spaces between words when published version has got those spaces.
**To Reproduce**
1. Go to 'edit post'
2. Click on 'a text block'

**Expected behavior**
The spell checker will find double words but not notice some lost spaces after punctuation. The double words are spaced in the online post. 
i have had this happen copy and pasting into Gutenburg to get text and image blocks, so thought I had missed these but now find the regenerate upon editing a post.

**Screenshots**
![image](https://user-images.githubusercontent.com/45037081/48483375-2fdb8500-e80b-11e8-8bb9-30046a184420.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Chrome
 - V 70.0.3538.77 (Official Build) (64-bit)

**Additional context**
In ver. 4.3.0

**Comment by designsimply** [comment]
Thanks for reporting this! 

I tried testing using Chrome 70 on Windows 10 but I'm having some trouble replicating the problem. Here's what I did:

1. Type the two paragraphs from your screenshot into an online Word document (Office 365).
1. Copy the content.
1. Go to Posts > Add New (still in Chrome 70 on Win10).
1. Paste the content using `Ctrl+V`.
1. View the preview.
1. Close and re-open the post.
1. Publish the post.
1. View the post on the front-end.

The spaces never collapsed in my testing. I do think there's an issue here—I am just not sure how to replicate it yet. Is there anything you can see that's missing from my testing to help me trigger the problem on my side?

Was the content in the screenshot  you included originally copied and pasted from elsewhere?

What else can I try and can anyone else who sees this confirm they are also seeing the same problem?

**Comment by mcmwebsol** [comment]
I was able to reproduce this in both Chrome 70.0.3538.77 and Firefox 63.0.1 on Windows 10 when pasting from Libre Office.

**Comment by designsimply** [comment]
I noticed the missing spaces match up with the line breaks in the Received HTML.

![screen shot 2018-11-14 at 2 32 14 pm](https://user-images.githubusercontent.com/1119271/48513934-679df900-e81a-11e8-9915-4bc0ddf78272.png)

**Comment by iseulde** [comment]
Sounds like a duplicated of #11588.
