### ISSUE TITLE
URLInput component needs a custom 'placeholder' attribute

### ISSUE THREAD

**Issue by r-a-y** [WordPress/gutenberg#11852]
**Editor's Update 2019-12-05 (by @aduth):** A `placeholder` prop now exists for `URLInput` as of #17846, but is not yet documented. The task should now reflect the need for documentation.

--- 

**Describe the bug**
Similar to other block components like `RichText`, the `URLInput` block needs to have a configurable `placeholder` attribute so custom blocks can set a different value other than the default `Paste URL or type to search`

It currently does not allow for one:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/url-input/index.js#L243

**Additional context**
- Tested on Gutenberg 4.3.0

I also encountered other bugs with `URLInput` that I'll file new issues for.

**Comment by gziolo** [comment]
Placeholder for `URLInput` is hardcoded as of today:
https://github.com/WordPress/gutenberg/blob/392df98bfeedfe8615657448f62439c888649444/packages/block-editor/src/components/url-input/index.js#L244

Please note that this component was moved to `@wordpress/block-editor` package.

**Comment by luckyape** [comment]
the hard coded placeholder provides a challenging user experience for `disableSuggestions: true`

**Comment by HardeepAsrani** [comment]
Yea, it's weird to have the "or search" option when there's a prop to disable suggestions. I can take over this if an affirmative decision is made. :)

**Comment by aduth** [comment]
`URLInput` now has a `placeholder` prop as of #17846

It does not yet appear to be documented, so this issue should remain open until that is resolved.

**Comment by PypWalters** [comment]
I believe this ticket can be closed now that https://github.com/WordPress/gutenberg/pull/36799 has been merged.
