### ISSUE TITLE
HTML Block Button "Convert to html"

### ISSUE THREAD

**Issue by qwertzuiop8** [WordPress/gutenberg#11860]
**Describe the bug**
If I go to a saved site for editing I can see the content in blocks. But the Button "Convert to html" and the Button "Resolve" don't work.

**To Reproduce**
1. Go to Edit Page
2. Scroll down to a block with the content "This block contains unexpected or invalid content"
3. Click on the "convert to html" Button
4. The button don't work.

**Expected behavior**
I like to use the "Convert to html" button.

**Screenshots**
![converttohtml](https://user-images.githubusercontent.com/45037503/48485452-2a853700-e819-11e8-84b6-e43d66a3ee53.PNG)

**Desktop (please complete the following information):**
 - Browser: chrome, firefox
 - Version newest

**Additional context**
- Gutenberg Version 4.3.0

**Comment by mtias** [comment]
Thanks for the report. This was fixed in https://github.com/WordPress/gutenberg/pull/11768 and will be going out tomorrow.
