### ISSUE TITLE
Equation block please~ and... classic block error.

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#11868]
My English is bad. Please understand me,

There are some equation plugins in wordpress. but I think they don't work with gutenberg. Can you add one?

I installed the equation plugin but it doesn't work with gutenburg. So I tried to use classic block. But I know it has an error...

![cap 2018-11-15 00-59-02-880](https://user-images.githubusercontent.com/44285360/48494813-f5f19980-e871-11e8-8f89-2d8b49972b8f.png)
it says 'this block has an error so it can't Preview.

![cap 2018-11-15 00-59-44-796](https://user-images.githubusercontent.com/44285360/48494868-0dc91d80-e872-11e8-8619-a47d46028d55.png)
hmm... just my classic editor's error?

Sorry to say about classic here. But it is an error... right? I just tried to say about equation block but I know there is a error... Please add equation block and fix that error.

**Comment by Soean** [comment]
What is an equation plugin? Do you have a link to that plugin?

**Comment by MYIG** [comment]
https://wordpress.org/plugins/equation-editor/
I installed this. but I think there is no plugin compatible with gutenberg.

and There is a still problem in classic block and editor after deleting that plugin... hmm...

**Comment by swissspidy** [comment]
> I installed this. but I think there is no plugin compatible with gutenberg.

It's up to plugin developers to support the new editor. I don't think equations are big enough of a use case to add a default block to Gutenberg for it. Thus, I suggest contacting the plugin developer to ask for Gutenberg support.

**Comment by Soean** [comment]
There is already an Gutenberg support forum thread for this plugin: https://wordpress.org/support/topic/gutenberg-33/
Opened 2 month ago, no answer yet.

**Comment by Soean** [comment]
In the reviews: https://wordpress.org/support/topic/great-plugin-but-121/#post-10799195
> Hi Chaoswolf,
>
>Thanks for your review. I will make it compatible for gutenberg.
>
>Thanks

He is working on it, so I think we can close this issue here.
