### ISSUE TITLE
How to override options of Gutenberg core components?

### ISSUE THREAD

**Issue by geertvansoest** [WordPress/gutenberg#11862]
Hi there,

I just found out Gutenberg and I think it's amazing. Despite that, I'm challenging some issues at implementing it in a WordPress website I'm currently developing.

At this website, I want to use some core components, and also create some custom components. I want to restrict the core components a bit, for example our client should not be able to customize the font sizes at the paragraph component. And at the columns component, he should be able to only add max. 3 columns (the max. is 6 by default). 

For now, I did some attempts for disabling / removing the font size block at the paragraphs component.
- I did experimenting a lot using the API's as shown on https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks.
- I did some testing with the solution as is given in https://github.com/WordPress/gutenberg/issues/6225, which looks a lot like the API editor.BlockEdit (https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#editor-blockedit). But I didn't found out how I can remove some elements. Seems like the BlockEdit API only can add new one.
- Someone else tried also tried to remove the font size block using an theme support hook (https://github.com/WordPress/gutenberg/issues/10972), but that won't work too. 

The main question is; is it possible to override the attributes/edit form for core components anyhow? 

Thanks in advance!

Kind regard,
Geert

**Comment by gziolo** [comment]
> I just found out Gutenberg and I think it's amazing. Despite that, I'm challenging some issues at implementing it in a WordPress website I'm currently developing.

Thanks, let me answer in the issue @designsimply linked.
