### ISSUE TITLE
Classic block image "Edit" button tooltip incorrect

### ISSUE THREAD

**Issue by timelsass** [WordPress/gutenberg#11875]
**Describe the bug**
Edit|button displays for image edit button tooltips.

**To Reproduce**
1. Open gutenberg editor.  
2. Add a classic block.
3. Add an image to tinymce.

The result is the tooltip read "Edit|Button".

or in console: `tinymce.activeEditor.selection.editor.buttons.wp_view_edit.tooltip` 

**Expected behavior**
The tooltip should read as "Edit"

**Screenshots**
![edit-button](https://user-images.githubusercontent.com/11907254/48506255-032d6a80-e817-11e8-889a-3341522e837b.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- chrome
- Version 69.0.3497.92 (Official Build) (64-bit)

**Additional context**
- Gutenberg v4.3.0

**Comment by melchoyce** [comment]
Looks like this is fixed in 5.8.0: 
![image](https://user-images.githubusercontent.com/2846578/59311817-b3edd200-8c5f-11e9-92bb-0b58eb74f9cd.png)
