### ISSUE TITLE
URLInput component onChange handler fires too frequently

### ISSUE THREAD

**Issue by r-a-y** [WordPress/gutenberg#11871]
**Describe the bug**
When attempting to use the `URLInput` component inline inside a custom block, the `onChange` handler fires too frequently.

**To Reproduce**
Steps to reproduce the behavior with the following code in the `edit()` method for rendering a block:

```
wp.element.createElement( wp.editor.URLInput, {
	className: props.className,
	value: props.attributes.link, // link is my custom attribute value
	onChange: function( url, post ) {
		console.log( url );
		//props.setAttributes( { link: url } );
	}
} )
```

View attached captured GIF below:

![urlinput](https://user-images.githubusercontent.com/505921/48487216-7209c400-e815-11e8-9895-a8f5b1aff5be.gif)

In the GIF, I'm attempting to type the phrase `https://`.  As you can see in the browser's console, the onChange handler is firing for every typed character.  Should probably use some time of timeout or add an attribute that will allow a custom timeout to occur here:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/url-input/index.js#L130

Also notice that the input textfield is blank and not being updated with the latest value.

In the meantime, I've coded my own URLInput component to workaround this problem and because the current URLInput component is heavily tied to post search for suggestions.

**Additional context**
- Gutenberg 4.3.0

**Comment by youknowriad** [comment]
It's a controlled React component which means it triggers its onChange callback on each character. If you want to delay this, you can do it on your own by wrapping your `onChange` handler in `lodash.debouce` for instance.
