### ISSUE TITLE
About article edit screen breaks

### ISSUE THREAD

**Issue by ryo2mattock** [WordPress/gutenberg#11889]
Hi,pls help me about this issue.
Thanks

** Describe the bug **
Copy past articles on the edit screen. And when you paste it into a new article the article edit screen breaks.

**Screenshots**
https://hunters2fg.tinytake.com/sf/MzA4MjE1NF85MjQwNDg4

![15-11-2018-11-42-11](https://user-images.githubusercontent.com/1119271/48563334-518f4780-e8b1-11e8-8446-316d7fd997e1.png)

** Desktop (please complete the following information): **
  - OS: win10
  - Browser chrome
  - Version Version: 70.0.3538.102 (Official Build) (64 bit)

** Additional context **
- Gutenberg ver 4.3.0

**Comment by youknowriad** [comment]
There has been a lot of updates since Gutenberg 4.3.0, do you still see the issue with WordPress 5.0?
Also, can you try disabling your plugins (meta boxes) to see if it has any impact?

**Comment by designsimply** [comment]
More information is needed to proceed. Please update to the latest version of WordPress and temporarily disable all plugins and test again. If the problem persists, please re-open this issue and provide as much relevant detail as possible about the articles you are copying and pasting. It is often very helpful to have a short list of testing steps to help us reproduce the problem so please include those if possible.
