### ISSUE TITLE
make RichText formattingControls prop filterable

### ISSUE THREAD

**Issue by junixdev** [WordPress/gutenberg#11887]
**Is your feature request related to a problem? Please describe.**
Currently we are able to register custom format types for RichText, and it can be used in all blocks that uses RichText when applying it via the keyboard shortcut. The issue is that the button can only be added on custom blocks that we set it to, and it is currently impossible to set it to core blocks.

This is actually related to my question here https://github.com/WordPress/gutenberg/issues/11516.

**Describe the solution you'd like**
The best solution that I can think of is to add a line in the RichText component file to make the `formattingControls` prop filterable. It would also be good if we can have an additional prop in the component for the name of the block (like `blockName` for example) that's currently importing the RichText component, and have that available as an argument in the filter.

**Describe alternatives you've considered**
Alternative solution is to add the filter on each core blocks that uses the RichText component, but this will mean though all of those blocks will need to add `formattingControls` attribute for the RichText component in its render callback.

**Comment by jkohlbach** [comment]
@pento sorry to drag you in on this, but we're getting smashed with requests for us to add our editor buttons to core blocks like the paragraph block. This issue is stopping us from doing that.

Seems like it might have been an oversight in the 5.0 release (ie. being able to register custom format types but not being able to add the button to core blocks so it can actually be used...)?

Any chance we can get this included in a patch so we, and other plugin devs like us, can add buttons to these core blocks?

Thanks for your consideration...

**Comment by talldan** [comment]
Hi @junixdev & @jkohlbach.

I've had a test of this and managed to register a custom formatting control and get the button to appear. There's one little detail that might be catching you out - when you declare the `ToolbarButton` component in your custom format you must not specify a `name` prop. Not specifying a `name` prop ensures your button is rendered in a general purpose toolbar`Slot` for extending the toolbar which is outside the restrictions imposed by `formattingControls`. Here's the example code for my custom superscript format:

```jsx
import { __ } from '@wordpress/i18n';
import { Fragment } from '@wordpress/element';
import { toggleFormat } from '@wordpress/rich-text';
import { RichTextToolbarButton, RichTextShortcut } from '@wordpress/editor';

const name = 'core/superscript';

export const superscript = {
	name,
	title: __( 'Superscript' ),
	tagName: 'sup',
	className: null,
	edit( { isActive, value, onChange } ) {
		const onToggle = () => onChange( toggleFormat( value, { type: name } ) );

		return (
			<Fragment>
				<RichTextShortcut
					type="access"
					character="n"
					onUse={ onToggle }
				/>
				<RichTextToolbarButton
					icon="arrow-up"
					title={ __( 'Superscript' ) }
					onClick={ onToggle }
					isActive={ isActive }
					shortcutType="access"
					shortcutCharacter="n"
				/>
			</Fragment>
		);
	},
};
```

Here's a video of it in use:

![formatting](https://user-images.githubusercontent.com/677833/49785517-c85a1c00-fd5b-11e8-9789-225702a4646e.gif)

If it's ok with you I'll close this issue as resolved. Feel free to reply if you have any further questions.
