### ISSUE TITLE
Can't create a new list item if an inline code tag is on the end of an item

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#11892]
**Describe the bug**
If you have a list block and one of list items ends in inline code, you can't create a new list item under it by pressing enter/return.

**To Reproduce**
1. Create a list block
2. Add some inline code to the end of the list item `like this`
3. Press enter

**Expected behavior**
A new list item should be created after the item with the inline code at the end. If the list item ends in something else such as a full stop after the `code`, it works as expected, as does pressing return anywhere else in that list item

**Additional context**
- Gutenberg 4.2.0
- Related: #11606
- Possibly related: #11276

**Comment by danielbachhuber** [comment]
I've seen this issue recently with `<a>` links too.

**Comment by cameronjonesweb** [comment]
Appears to be fixed in 4.4.0
