### ISSUE TITLE
Inserter: Constantly jumping when many child blocks are registered

### ISSUE THREAD

**Issue by tyxla** [WordPress/gutenberg#11905]
**Describe the bug**
Inserter is constantly jumping up and down when there are enough child blocks registered for the child block list to be scrollable.

**To Reproduce**
* Register a custom block X.
* Register 10 child blocks of that block X.
* Insert the custom block X.
* Attempt to insert a child block in it.
* See the inserter jumping.

or use https://github.com/Automattic/jetpack/pull/10599 that we used to reproduce the issue.

**Expected behavior**
I expected the inserter block list to stay still.

**Video**
I've recorded a quick video that demonstrates the problem:
https://cloudup.com/icgUFy5So7P

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1 (18B75)
 - Browser: Chrome 
 - Version: 70.0.3538.102

**Additional context**
- Used a development version of Gutenberg at [this revision](https://github.com/WordPress/gutenberg/tree/4cc3ac01e449b69af594517d9a8b6d0b20b57daa).

**Comment by youknowriad** [comment]
We did fix something in that vein lately, I wonder how it behaves in master.

**Comment by tyxla** [comment]
Nice 👍 Just tested with the latest master and it's resolved. Thanks!

Closing.
