### ISSUE TITLE
Block Toolbars no longer reliably display when selecting block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11906]
**Describe the bug**
Just tried to edit a page and when I click on a block, the block toolbar no longer displays. If I keep clicking around, sometimes it shows, and then when it does, it remains displayed even when I click on another block.

Vid: https://cl.ly/cee1a4845875

A screenshot from a completely different site running the same version of WP and a different theme, showing the same issue

![screenshot_939](https://user-images.githubusercontent.com/2078245/48549045-cea6d500-e922-11e8-84a6-bdda4c683453.png)

**To Reproduce**
1. Edit existing page
2. Click on a block to select it
3. See the toolbar doesn't appear

**Expected behavior**
When I click on a block, the toolbar should display every single time

**Desktop (please complete the following information):**
- macOS Sierra 10.12.6
- Firefox Quantum 63.0.1 (64-bit)
- WP 5.0-beta4-43896
- TwentyNineteen

**Comment by La-Geek** [comment]
I can confirm this (windows 10, chrome, theme twentynighteen, WP (5.0-beta5-43907)).
When you click (where ever) into a block, it should display the toolbar. The block paragraph does only react, when you click on the text.

**Comment by maddisondesigns** [comment]
WP 5.0-RC1-43944 and still no Block Toolbars when I click on a block

**Comment by maddisondesigns** [comment]
Another issue that this causes is that you can no longer edit Video blocks (e.g change the layout) because clicking on the edge of the block doesn't show the toolbar, and clicking in the middle of the block simply starts plying back the video.

**Comment by maddisondesigns** [comment]
5.0.3 and you still can't reliably select blocks

**Comment by youknowriad** [comment]
Is this still an issue? I've not experienced this for a long time.

**Comment by maddisondesigns** [comment]
This seems to be more reliable now and I can't replicate it so I'll close this
