### ISSUE TITLE
Add Tests: Transform embeddable URLs in Audio/Video/Image to Embed Block

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#11901]
**Description**
In #11472 and #11410 we added the transformation to embed block if the user tires to insert  embeddable URLs in Audio/Video/Image blocks. Examples: youtube, soundcloud or instagram.
We should add E2E tests to verify the functionality.

See: https://github.com/WordPress/gutenberg/pull/11472#pullrequestreview-175095136

**Comment by draganescu** [comment]
I'll take a stab at this as a first attempt to get used to e2e tests :)

**Comment by draganescu** [comment]
Hey @Soean I've added the PR #13997 with three new tests for the transforms.
