### ISSUE TITLE
Improve 'upload_files' capability checks in the editor

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#11910]
Previous work to verify 'upload_files' capability when displaying upload UI in media blocks was done by @imath for #3672 in #4155.

I found new ways to trigger upload UI which should be fixed.

### Select Poster Image

1. Add a Video block.
2. Insert a video from url.
3. Click on `Select Poster Image`.
4. Media upload modal will show up.

![screen shot 2018-11-15 at 11 47 54](https://user-images.githubusercontent.com/699132/48548846-5a424680-e8ce-11e8-92ed-890b775de235.png)

### Drag & Drop file

1. Drag & Drop file to the editor from a folder.
2. It will create a File block with a strange error.
3. Click Edit icon and Media upload modal will show up.

![screen shot 2018-11-15 at 11 51 24](https://user-images.githubusercontent.com/699132/48548847-5a424680-e8ce-11e8-9768-c10e1252b15b.png)

### Drag & Drop image

1. Drag & Drop image to the editor from a folder.
2. It will create an Image block. It probably will be broken.
3. Click Edit icon and Media upload modal will show up.

![screen shot 2018-11-15 at 11 52 00](https://user-images.githubusercontent.com/699132/48548848-5a424680-e8ce-11e8-9960-d40df45efadb.png)

**Comment by imath** [comment]
Thanks for adding this issue as a follow-up of #4155. I've just started working on these forgotten cases. I will try to post a PR asap.
