### ISSUE TITLE
"Updating failed." after Autosave. Update button does not work too.

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/gutenberg#11913]
**Describe the bug**
Yesterday I edited a post. Today I open the tab in my browser and see "Updating failed". I can't use "Update" as this ends in an infinite loop.

Not sure why it happens, but maybe the nonce is expired.

**To Reproduce**
I am not sure, but maybe waiting for the login cookie to expire will trigger this.

**Expected behavior**
If the autosave fails because of the expired login cookie, I expect the "Update"-button to work after I re-logged in.

**Screenshots**
<img width="804" alt="bildschirmfoto 2018-11-15 um 13 29 51" src="https://user-images.githubusercontent.com/870475/48553092-de9ac680-e8da-11e8-9622-964473061fa1.png">
![gutenberg-save](https://user-images.githubusercontent.com/870475/48553096-e490a780-e8da-11e8-92a0-416defb50dd6.gif)

**Desktop (please complete the following information):**
 - OS: 10.13.6 (17G3025)
 - Browser Firefox Quantum 63.0.1 (64-Bit)

**Additional context**
WordPress 5.0-beta4-43896

**Comment by designsimply** [comment]
This sounds similar to #9260 to me. I will try to do the same test again where I open a post today, leave it open, and then try editing it tomorrow. I will test with WP5.0-beta4 (bleeding edge nightly), 4.3 today, and 4.4 when it comes out.

@Zodiac1978 any chance you can check the Network panel in your browser tools to see if you see the same failed API as shown in https://github.com/WordPress/gutenberg/issues/9260#issuecomment-421126579 ? My goal with that is to try to check whether it is a regression of #9620 appearing in the plugin and/or WP5.0-betas.

**Comment by Zodiac1978** [comment]
@designsimply You can see the error in the first screenshot. As there is a 403 Forbidden I also think this is an expired nonce. As I closed the tab meanwhile I will need to test this again which needs time ;)

**Comment by overcatbe** [comment]
clear browser cache - often, and use stuff like wp sweep - a lot.
it's all javascript now and this stuff is imho not ready for production as of now, BUT the 2 tools mentioned help.

**Comment by designsimply** [comment]
@Zodiac1978 I see the console error but was wondering if there was any more specific information about the API call in question in the Network panel separate from the Console panel. Though, I am not sure sure whether that's necessary! Apologies for not getting to this earlier. I am starting a new test right now using WordPress 4.9.8 and Gutenberg 4.5 and also with WordPress 5.0-beta5-43909 and I will let you know what I find.

**Comment by maddisondesigns** [comment]
I just updated a site from 4.9.8 to RC3 and opened up a page to edit it and a couple of seconds later I start seeing the "Updating failed" message

**Comment by maddisondesigns** [comment]
Having the same issue after updating to 5.0

**Comment by adamsilverstein** [comment]
@tobinfekkes can you provide a screenshot of the console/network request/response when the update fails? Anything notable about your hosting configuration, or anything that might block the WP REST API?

**Comment by tobinfekkes** [comment]
Thanks for asking, Adam.

Here's some screenshots of the Ajax requests. Couple things that stick out to me, or are worth mentioning:

1: I guess it shouldn't matter, but WP is not in the root directory of the site. It's in public_html/wp/. Thought maybe the .htaccess was getting involved, but nothing looks fishy there. Just the standard stuff.
 
2: I don't have SSL installed on the domain, perhaps WP 5.0/REST requires/expects that? Hence the 404? The site works fine, apart from Chrome warning me of an insecure site.

3: In the image below, the response header is "Wed, 11 Jan 1984". Is there a date/time setting waaay off? And if so, does that even matter?

4: Hosting environment is my VPS, and this domain is an "Addon Domain" in cPanel. I have a few other domains, but they're not on 5.0 yet. This was the first fresh domain post-5.0 release.

5. Saving of all other non-Gute forms works just fine; Settings, Appearance, Users, etc.

![image](https://user-images.githubusercontent.com/6226162/50254145-d8987980-03a1-11e9-84c6-3fa4026d69f8.png)

![2018-12-19 15_19_16-window](https://user-images.githubusercontent.com/6226162/50254414-c834ce80-03a2-11e9-94ab-b069b236c02a.jpg)

![2018-12-19 15_17_35-window](https://user-images.githubusercontent.com/6226162/50254517-25c91b00-03a3-11e9-836a-b1c747f2ebca.jpg)

**Comment by designsimply** [comment]
Thank you for the note @tahirakbar1!

**Comment by designsimply** [comment]
@tobinfekkes for your case, if you are still experiencing the same issue after updating to the latest version of WordPress and removing the Gutenberg plugin, can you report the errors you're seeing to https://wordpress.org/support/forum/how-to-and-troubleshooting/ and please ask for help troubleshooting to find out if your REST API is in proper working order for a site hosted in a subdirectory such as `wp` like yours is? For example, normally you should be able to go to `example.com/wp-json` and see a response as a basic confirmation that the API is working properly and in your case I think that you would need to go to `example.com/wp/wp-json` but I see in your screenshot that your requests are going to `http://atforksend.com/wp/index.php/wp-json` which could mean there's something funny going on with the server configuration in your case but I tried checking the site just now and I saw "Error establishing a database connection" at http://atforksend.com/wp/ so it's possible that site has been taken down or not maintained and it would be good to have a check on it and more troubleshooting before continuing. Also, your case does appear to have a different error on a different file compared to the original issue posted here so opening a new issue after you find out more information through troubleshooting would be the correct route. If you feel you don't need help with troubleshooting and would like to continue here, can you please open a separate issue for your case and copy over the information including the latest version of WordPress you've tested with? Thank you!

**Comment by designsimply** [comment]
Can anyone else confirm if they are still seeing the "Updating Failed" error with the "Unhandled promise rejection" for `wp-polyfill.min.js` showing in the console when trying to edit a post left open for a long time even after the #11347 update which went into effect in Gutenberg 4.3?

**Comment by youknowriad** [comment]
Closing this as there's doesn't seem to be any actionable item left. If you find ways to reproduce the issue, please open another issue.
