### ISSUE TITLE
gutenberg_warn_classic_about_blocks: tedious dialog with only one working option!

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#11917]
**Describe the bug**
When using the Classic editor to edit a post that contains Gutenberg blocks the warning dialog is
very annoying after Update, especially since the only button that works is the Continue to Classic editor button. 

**To Reproduce**
1. Activate Gutenberg and the Classic editor
2. List posts
3. Choose Classic Editor to edit a post created using Gutenberg. e.g. Hello World!
4. See the warning dialog
5. Click on Edit in Gutenberg
6. See the warning dialog
7. Click on Continue to Classic Editor
8. Update
9. See the warning dialog.
10. Go to 5.

**Expected behavior**
- The dialog should only appear for the first attempt to edit the post.
- The Edit in Gutenberg button should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/48558404-1e64ac80-e8e1-11e8-836a-f6571cec95a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge, in this example, but problem noted on Safari on iPad

**Additional context**
- WordPress 5.0-beta4 used to create the Hello World post
- Classic editor 0.5
- Gutenberg 4.1.0 and above.
- Note: 4.0.0 doesn't work with 5.0-beta4

**Comment by bobbingwide** [comment]
This has now been superseded by the updates to the Classic Editor plugin. Users of Classic Editor v0.5 will need to update to v1.3 or higher.

**Comment by gziolo** [comment]
`gutenberg_warn_classic_about_blocks` is no longer part of Gutenberg plugin.
