### ISSUE TITLE
Title for the section still renders when editor panels are removed from UI

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#11923]
Discovered when working on #11802.

When you remove all panels programmatically, the section title in the Options dialog is still there.

![screen shot 2018-11-13 at 09 59 42](https://user-images.githubusercontent.com/699132/48402494-0dbf0580-e72c-11e8-9cc0-c70093c620f5.png)

You can reproduce by pasting the following code and executing in JS console:

```js
wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-category' ) ;
wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-post_tag' );
wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'featured-image' );
wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'post-excerpt' );
wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'discussion-panel' );
```

and opening Options modal from the More Menu.

@noisysocks shared some ideas how this could be fixed:

> It's a shame that there's no way to ask React if `props.children` will render as empty...
> 
> I had a similar problem with `<MetaBoxSection>` and ending up having to add logic to the section rather than keeping it in each option.
> 
> I'm struggling to think of a nice way around this. Perhaps need to bite the bullet and move away from having `<OptionsModal>` implemented with nested components. Instead, we can have a function generate the _options data_ which a dumb `<OptionModal>` component then renders a UI for.

**Comment by gziolo** [comment]
It looks like it is also the case for `Advanced Panels`, noticed in the screenshot shared by @imath  in #12394:

 ![with](https://user-images.githubusercontent.com/1834524/49177978-d9179480-f34e-11e8-8221-f91c9edab4ef.png)

**Comment by paaljoachim** [comment]
Is this issue still valid @gziolo Greg?

**Comment by gziolo** [comment]
@ntsekouras, is it something that can be closed after the most recent refactoring applied in #28329?

**Comment by ntsekouras** [comment]
Problem is still there 😞 - I hadn't checked that.

**Comment by Mamaduka** [comment]
I can confirm this is still an issue in 6.0.


## Snippet for testing.

```js
const panels = ['post-link', 'template', 'taxonomy-panel-category', 'taxonomy-panel-post_tag', 'featured-image', 'post-excerpt', 'discussion-panel', 'page-attributes'];

panels.forEach( (panel) => wp.data.dispatch('core/edit-post').removeEditorPanel(panel) );
```

## Screenshot

![CleanShot 2022-06-29 at 10 06 39](https://user-images.githubusercontent.com/240569/176363596-12ca6db6-127b-40ea-9ea5-19fcc11eb94c.png)

**Comment by Mamaduka** [comment]
Removing the "Good First Issue" label, as we found out that this isn't an easy fix 😅

**Comment by fabiankaegy** [comment]
Following up from the comment here: https://github.com/WordPress/gutenberg/pull/29207/files#r581002056

I think this should now be possible using the CSS `:has` selector. `has` has shipped in most browsers. And even for the ones that don't this doesn't cause more harm. It at least solves the issue for a good majority of users.

**Comment by ntsekouras** [comment]
It seems the css solution [has been implemented](https://github.com/WordPress/gutenberg/blob/trunk/packages/preferences/src/components/preferences-modal-section/style.scss#L26) already, so I'm closing this issue.
