### ISSUE TITLE
v4.3.0 - remove_post_type_support( $post_type, 'title' ) removes permalink field

### ISSUE THREAD

**Issue by Jonnyauk** [WordPress/gutenberg#11929]
**Describe the bug**
We develop very bespoke, advanced themes for WordPress and often dev our own metaboxes or ACF Pro to create unique header options. 

We sometimes create a bespoke 'title' field along ith other associated title options and on 'post update' save this data as post title. We want to keep all our 'title' options together!

**To Reproduce**
1. Add code to theme functions.php:

`// Remove title tag
function mytheme_remove_title_tag() { remove_post_type_support( 'page', 'title' ); }
add_action( 'init', 'custom_remove_title_tag' );`

2. Visit editor page
3. Title removed (cool!) - but permalink field also removed - can't be edited ;(

**Expected behavior**
Should be able to remove title, but still maintain permalink field

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version Version 70.0.3538.102 (Official Build) (64-bit)
- WordPress 4.9.8
- Guttenberg 4.3.0

**Comment by youknowriad** [comment]
Thanks for the issue, as of #11874 we now have a new panel for the permalink, which solves this.

**Comment by Jonnyauk** [comment]
Wow - that's fast fixing - AWESOME!!!! 

I'm really glad to hear that permalink field has moved - felt like legacy code/UI caused it to be bundled below the title 'block' anyway (yea, I know it's not a 'block' but you know that I mean!!)
