### ISSUE TITLE
Consider having a "pressed" or "active" state on buttons that trigger popovers

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#11937]
Right now focus switches to the popover (or sidebar) and the item that opened it is only indicated by an arrow (in the case of dropdown menus).

Would be good to consider a visual display that more clearly communicates something is toggled, without messing with focus flow.

**Comment by youknowriad** [comment]
Is this something that you still consider? Should we just close to issue in favor of all the redesigns in #18667
