### ISSUE TITLE
Make the link anchor also retrieve the title of the post/page

### ISSUE THREAD

**Issue by brazenvoid** [WordPress/gutenberg#11930]
The linker in current WP gets the title of the searched and selected post/page automatically rather than making the user get it manually himself.

We have recently shifted to Gutenburg and have been crying tears of blood due to this. There are many other quibbles but I guess I can deal with them. We usually release about 15 posts every week. 

Now we have to source the post link from the post/page itself or its excerpt to preserve its title. Otherwise, it is such a hassle to form the title from its URL. 

Imagine the scenario that you have just released 6 or so posts and updating the table of contents and other sources within the site. Now one will have to open a new tab with the site and copy+paste post title links because the link block doesn't do this.

### Solution

Perhaps when no text is selected, the link should instead add the title as the label.

**Comment by mostafaabd** [comment]
@designsimply hi, i test it in Gutenberg 4.5.1, and  WordPress 4.9.8, but there is no issue its display title of post not link like this [video](https://cloudup.com/c-EcPS-454i) .

**Comment by Arbigaus** [comment]
There's some preview to fix it?
Thanks.

**Comment by yodiyo** [comment]
This is still an issue. It is making more work to add internal links to pages.
