### ISSUE TITLE
[4.3] crash paragraph block with image.....

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11935]
### Describe the bug
Paste a link into a paragraph that contains an image. Then try to paste the link onto that image. The paragraph block will crash.

### To Reproduce
1. have a URL link on the clipboard
2. insert a left/right image into a paragraph block.
3. paste the link (CTRL-V) onto some of the paragraph text 
4. click the image (for focus), and try to paste the link (CTRL-V) onto the image
5. the paragraph block will break

### Expected behavior
- the paragraph block should not break.
- the image should inherit the link (separate issue: https://github.com/WordPress/gutenberg/issues/11934)

**Comment by La-Geek** [comment]
I wanted to test this issue. But how do you insert an image into a block paragraph?
Or did you mean the block classic?

**Comment by GlennMartin1** [comment]
Not the Classic block. 

I'm trying to say that you right/left align an image in (or around/over) a paragraph block.

**Comment by La-Geek** [comment]
To verify: You meant the block image?

**Comment by GlennMartin1** [comment]
Your terminology wins. Yes, the image block.

**Comment by La-Geek** [comment]
Good Catch.
I am confirming the issue.

![link_paragraph_image_issue](https://user-images.githubusercontent.com/1585416/48664775-20c33400-eaa4-11e8-8fa8-dd009bb4652c.gif)

**Comment by GlennMartin1** [comment]
It appears this is no longer an issue in Gutenberg 5.3.
