### ISSUE TITLE
[4.3] pasting link onto an image doesn't work

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11934]
### Describe the bug
Pasting a link onto an image that has focus does not add that link to the image.

(in Gutenberg if you have text highlighted, you can paste a link directly to the text. This doesn't work with images. It does work in the Classic Editor).

### To Reproduce
1. Have a link on the clipboard.
2. Add an image to Gutenberg.
3. Click on the image to give it focus.
4. Paste (in Windows, CTRL-V).
5. Note that the image does not get the link.

### Expected behavior
- The "Link to" should become "Custom URL"
- The "Link URL" should become whatever the clipboard contents were.

**Comment by designsimply** [comment]
Testing note: check to see if this is a regression for the plugin or not.

**Comment by La-Geek** [comment]
Imho, if this would be a function of the block image, there would exist an icon "insert link" in the visual editor mode.

However: this is a missing feature, I do agree with @GlennMartin1

**Comment by GlennMartin1** [comment]
This issue persists in Gutenberg 5.3.

**Comment by noisysocks** [comment]
Confirmed that the classic editor has this functionality and that latest Gutenberg does not.

**Comment by jordesign** [comment]
Confirming this issue still exists in WP6.3 - but closing as a duplicate of this one:
https://github.com/WordPress/gutenberg/issues/35839
