### ISSUE TITLE
4.4.0: new permalink editor brings confusion when editing Front Page

### ISSUE THREAD

**Issue by lkraav** [WordPress/gutenberg#11943]
**Describe the bug**
#11874 brought new sidebar permalink editor section.

This has usability problems when editing Front Page (and probably other special pages):

1. can't edit Page URL (can't tell you're supposed to be able to, until you edit some other non-special page)
2. editor should say something about why Page URL box is missing
3. clicking Title block only shows a huge unexpected button "Change Permalinks", with no edit control - I can't screenshot this, because the whole element disappears as soon as browser window loses focus for screenshot tools.

**To Reproduce**
1. Edit your assigned Front Page
2. Click on Title block
3. Unfold Permalinks document settings section

**Expected behavior**
* Page slug should be editable, no matter the configuration
* Special page assignment info should be display "This is your configured Front / Shop / Blog page"
* Avoid low use-case distraction of inviting people to system management Permalinks screen from an everyday use content editor screen

**Screenshots**
![image](https://user-images.githubusercontent.com/147228/48583479-e89ae480-e92f-11e8-923c-580e30b2e2c6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 64beta

**Comment by designsimply** [comment]
Closing in favor of #12498 because it has a pull request associated.
