### ISSUE TITLE
Permalink in sidebar: Permalink Settings link

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#11945]
**Describe the bug**
The `Permalink Settings` in the sidebar should only be visible, if the user can open the settings page and change it. Maybe we should only show it if the user has enabled plain permalinks?

<img width="284" alt="bildschirmfoto 2018-11-15 um 23 17 02" src="https://user-images.githubusercontent.com/695201/48585331-9ad0ad00-e92c-11e8-8009-20c4eabaefcd.png">

**Comment by rpkoller** [comment]
Why display the setting at all? The permalink isn't a setting you change on a regular basis, it is set once properly.

**Comment by swissspidy** [comment]
For reference, the link to the permalink settings when editing the slug in the title "block" is only shown when using plain permalinks.

Also, this should only be shown if one has the capability to do so.

**Comment by burnuser** [comment]
I assist rpkoller: Please do not show a direct link to the permalink settings in the editor!
The editor is used for content and options according to a certain post/page.
The permalink settings are used for the whole site. And linking to it from the editor suggests, that there are some options for the actual edited post/page which can be adjusted. And than people would maybe insert rubbish in "Custom" permalinks settings ...

**Comment by rpkoller** [comment]
@swissspidy hm are you sure about that it is only shown when using plain permalinks? (using Gutenberg 4.4.0)

![bildschirmfoto 2018-11-16 um 14 42 44](https://user-images.githubusercontent.com/1665422/48624933-0eff6500-e9ae-11e8-88f2-afaacb654f0e.png)

**Comment by burnuser** [comment]
"Plain" or not, I think permalink settings should never be linked from the Editor!

**Comment by swissspidy** [comment]
@rpkoller I was referring to the link in the title block, not the sidebar. The "Edit" button you see in thte title block in your screenshot only toggles the input field, it doesn't lead to the settings page.

**Comment by pratikthink** [comment]
permalink settings is removed in #12121

**Comment by Soean** [comment]
The link was removed, so I close this issue.

**Comment by burnuser** [comment]
Please reopen!
It is not resolved completely!

Clicking on pagetitle on the Homepage presents still a button for "Change Permalinks" on the same position of the "Edit" button on regular posts/pages. But of course with a completely different effect if used!

![grafik](https://user-images.githubusercontent.com/32030147/49326306-7beb3100-f550-11e8-9813-c3ee4053f0b5.png)

A very confusing and error-prone behaviour of Gutenberg!

**Comment by swissspidy** [comment]
But that‘s unrelated to what has been discussed here. Would you mind opening a new issue for that? Thanks!
