### ISSUE TITLE
:root selector should be accounted for in editor-styles wrap

### ISSUE THREAD

**Issue by timelsass** [WordPress/gutenberg#11955]
**Describe the bug**
`:root` selector should be respected in the editor wrap process.

- The `:root` selector for all intents and purposes is the root of the document, so in HTML - the `html` tag.
- The caveat is that the `:root` selector does have a higher level of specificity than the `html` selector.
- Many themes do use popular CSS frameworks which make use the `:root` selector,  twbs/bootstrap as an example: https://github.com/twbs/bootstrap/blob/e57a2f244ba8446fffe71847e6a58b18f7b2d541/scss/_root.scss
- As css-variables have become more widely supported, I've begun shipping themes with support for them and polyfilling for legacy/non-supported browsers.  The typical approach for most is to apply css vars on `:root` as per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).

**To Reproduce**
1. Add editor style with something like: `:root { background: red !important; }`.
2. View a post/page in Gutenberg editor that has this enqueued via add_editor_style() and declares [`theme_support` for `editor-styles`](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#editor-styles).

The result is that the background of `.editor-styles-wrapper` is not red since `.editor-styles-wrapper:root` is not a valid selector.

**Expected behavior**
I would expect that the `:root` selector is treated in a special context - where they are not just discarded from the styles, and are given their original specificity intended as `:root` but passed on the `.editor-styles-wrapper` element according to [current W3C Selectors Level 3 specs](https://www.w3.org/TR/selectors-3/).  This would allow for properties to be inherited and applied correctly in the Gutenberg wrap styles generated.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- chrome
- Version 70.0.3538.77 (Official Build) (64-bit)

**Additional context**
- Gutenberg v4.4.0
- replicated on current master
- WordPress 4.9.8

**Comment by m-e-h** [comment]
You and I seem to be on the same page with this CSS stuff @timelsass :smiley:

I'm going to go ahead and close https://github.com/WordPress/gutenberg/pull/11512 as yours appears to be more thorough with the tests.

**Comment by timelsass** [comment]
@m-e-h - I asked for someone to review and consider this for 5.0wp release in slack #core-editor , but the request was ignored.  It seems like most issue/bugs are being labeled as "enhancements" so they can be pushed off to another release.  I've gone ahead and added an implementation of this for my projects/needs, so I'm not pressing the issue anymore, and it's apparently not a bug, just an enhancement to the real world.  Feel free to reopen and pursue this is if you think anyone cares.

**Comment by m-e-h** [comment]
Yep @timelsass , seems to be a tough time to get an issue deemed worthy. 

On this issue, I've actually been thinking lately that I might prefer `:root` to not get mapped to the wrapper.

The issue with the current  "editor-styles" thing, I've realized, is that it actually breaks the `:root` selector somehow when it spits out the styles inline. 

I've opted to compile styles with my own postcss plugin and use `enqueue_block_editor_assets`, for now. 
I'm not seeing much upside to using the "editor-styles" thing at this time.

**Comment by chrisvanpatten** [comment]
@timelsass Sorry for the delay to be clear we do care, we're just frozen right now in terms of new enhancements and all of us, volunteers and full timers alike, are bogged down in fixing critical issues before 5.0 is released.

As @m-e-h pointed out though I'm not sure `:root` is good to map because the `:root` has special properties that aren't really duplicated by mapping to a normal class. I think this is a case where mapping would actually cause more problems than it would solve.
