### ISSUE TITLE
White bleeds in to editor from bottom

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#11959]
**Describe the bug**
With dark-editor-style active I get this white bleed when I scroll from the bottom of the editor, this is not a new bug but has been present for months (I had just assumed it was due to a metabox from a plugin, but disabling that gave the same result). In full screen mode this issue does not occur.

**To Reproduce**
1. activate dark-editor-style
2. add a bunch of blocks so the editor gets a scroll bar 
3. scroll down to bottom
4. scroll up

**Expected behavior**
No "bleeding".

**Screenshots**
This gif illustrates the issue. It also shows how the problem disappears when entering full screen mode. There's no errors in the console. If I change the color of the right sidebar to black it will show that it also gets the white bleeding

![nov-16-2018 09-04-20](https://user-images.githubusercontent.com/40266703/48606118-017eb680-e97f-11e8-9860-9d6c3706c781.gif)

**Desktop (please complete the following information):**
 - OS: centOs 7 and macOS (whatever the latest version is called)
- browser: chrome 70.0.3538.102

**Additional context**
- GB 4.4 (and back to when dark-editor-style was implemented I believe)

**Comment by jasmussen** [comment]
Thanks for the ticket.

I can't reproduce, though:

![dark-editor-style](https://user-images.githubusercontent.com/1204802/48613098-16f9dd80-e98b-11e8-9b50-53c48e85f867.gif)

This is TwentyNineteen modified to have a dark editor style. Here's the pertinent stuff in functions.php:

```
		// Add support for editor styles.
		add_theme_support( 'editor-styles' );
		add_theme_support( 'dark-editor-style' );
```

And here's the pertinent stuff from the editor.scss file:

```
body {
	background: #333;

	p {
		color: white;
	}
}
```

The above gets recompiled from SCSS to CSS and looks like this:

```
body {
  background: #333;
}

body p {
  color: white;
}
```

But it still works.

Tested with fullscreen and without, with metaboxes on and without.

Can you share a snippet of your editor style? Perhaps you are targeting an old selector with the background color?

**Comment by slimmilkduds** [comment]
Hi! Thanks for looking at this. I've tried this with and without metaboxes and I get the same error.

I haven't touched / created an scss file, only using regular css.

This is how I set the background: 

```
body.gutenberg-editor-page {
        background: #2e2e2e;
      }
```

going just:
 
```
body {
  background: #2e2e2e;
}
```

doesn't work for me and leaves the background white which might be part of this problem?

You asked in slack about fullscreen and other editor settings. When in full screen this issue goes away. The other settings has no effect.

**Comment by jasmussen** [comment]
Thanks for the added context.

```
body.gutenberg-editor-page {
background: #2e2e2e;
}
```

Even this is working for me, and there's still no white. However per recent changes to editor styles even this should not be necessary.

It's important to note that you have to actually add the following to the editor style file, to test:

```
body {
  background: #2e2e2e;
}
```

It is not enough to test just in the inspector. Gutenberg now rewrites your editor style on the fly, to match. So when you paste that in your editor style, Gutenberg actually rewrites it to this:

```
.editor-styles-wrapper {
    background: #2e2e2e;
}
```

Note that you should _not_ target the .editor-styles-wrapper in your editor style, you should let Gutenberg handle that. Gutenberg automatically does the transcoding of `body` into `.editor-styles-wrapper`.

**Comment by slimmilkduds** [comment]
Hmm, yeah I did add it to the editor-style.css and not the console, I wonder what I’ve messed up to not get that to work hehe

**Comment by jasmussen** [comment]
How are you adding your editor style? You should add it like this:

```
		// Enqueue editor styles.
		add_editor_style( 'style-editor.css' );
```

**Comment by slimmilkduds** [comment]
Interesting, I'm doing this:
```
function theme_block_editor_styles() {
    wp_enqueue_style( 'theme-block-editor-styles', get_theme_file_uri( '/style-editor.css' ), false, '1.0', 'all' );
}

add_action( 'enqueue_block_editor_assets', 'theme_block_editor_styles' );
```

Replacing it with: 
`		add_editor_style( 'style-editor.css' );
`
doesn't work either, I'm probably missing some obvious stuff I should also add but I suck at this :)

**Comment by jasmussen** [comment]
No worries, I think we're close. Can you try this?

```
function theme_block_editor_styles() {
	// Add support for editor styles.
	add_theme_support( 'editor-styles' );

	// Enqueue editor styles.
	add_editor_style( get_theme_file_uri( '/style-editor.css' ) );
}

add_action( 'after_setup_theme', 'theme_block_editor_styles' );
```

**Comment by slimmilkduds** [comment]
You are a saviour! Not only did that fix this specific issue, it also solved like 5 other smaller things that I  couldn't get to work as expected in the editor style sheet :)

**Comment by jasmussen** [comment]
Hooray!

Riad is the real hero here. He wrote the style stuff.
