### ISSUE TITLE
Required option on fields

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#11967]
Hi,

I have added a select field using `<SelectControl>` now I want to make that select field required. Without selecting, the user cannot save/update the page.

Is this possible ??

**Comment by swissspidy** [comment]
There's a `lockPostSaving` action one can use to prevent users from saving.

See #10649 for an example.

**Comment by designsimply** [comment]
Closing since an answer was provided and there have been no further replies since.
