### ISSUE TITLE
Embed: Flickr images are square and pixelated

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#11962]
Example URL: https://www.flickr.com/photos/mathiasappel/32344659441

The embed is detected to be square, and loaded in low resolution. 

![screenshot 2018-11-16 at 10 21 58](https://user-images.githubusercontent.com/1204802/48612511-7e169280-e989-11e8-9ed9-a48a4605bc9e.png)

The front-end view looks right:

![screenshot 2018-11-16 at 10 22 47](https://user-images.githubusercontent.com/1204802/48612545-94bce980-e989-11e8-908f-25401a43c229.png)

Marking as low priority. Good to fix, but hasn't been reported yet, so usage might be low. It also works fine in the published version.

**Comment by drzraf** [comment]
Out of curiosity, do you have _true_ fullwidth/responsive support for Flickr embeds?

**Comment by skorasaurus** [comment]
For clarity and anyone trying to debug this; this pixelation only occurs if you are embedding a single photo from an album. 

On Gutenberg 9.1: 

For example, the url is 
https://www.flickr.com/photos/9021833@N06/5109163319/in/album-72157603562092796/
(in that url: 9021833@N06 is the user name; 
5109163319 is the image; 
album-72157603562092796/ is the album

If you embed an album (which will only load one image but there's arrow links to view other images in that gallery); the image isn't pixelated.

**Comment by mashikag** [comment]
I have created a PR for this issue, [https://github.com/WordPress/gutenberg/pull/40187](https://github.com/WordPress/gutenberg/pull/40187).

**Comment by mashikag** [comment]
@ntsekouras I believe this issue can be closed now too, that [the fix](https://github.com/WordPress/gutenberg/pull/40187) was merged? 😀

**Comment by ntsekouras** [comment]
Resolved by: https://github.com/WordPress/gutenberg/pull/40187
