### ISSUE TITLE
RichText: incorrect caret position after deleting selected word

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#11964]
**Describe the bug**

Splitting this out from #11564.

From @dd32:

>  If I select a word (either by highlight, or double click) and then backspace it (But NOT when placing the cursor after the word and backspacing it), the DOM would read word1 word2 (two spaces) but the UI would show the cursor directly before word2 such like this: word1 |word2, typing would then eat that second space and result with word1 word4word3 instead of the expected word1 word4 word3.
>
> Testing in Firefox 63.0.3 caused the same carrot positioning, but the space would re-appear once the word started being typed.

**Comment by swissspidy** [comment]
I'm glad this is being tracked. Every time I delete some text or undo some changes, the caret position is messed up and ends up being at the end or beginning of the text. Very frustrating.

So thanks for working on fixing this!
