### ISSUE TITLE
White Screen on install on FlyWheel (host)

### ISSUE THREAD

**Issue by jakilevy** [WordPress/gutenberg#1196]
from a friend who doesn't use gitHub and just tried installing - 

I am Using Local by Flywheel with PHP 7.0.3 and ngix I get it to install but I’m not seeing anything…the area is white. Not sure if I need to install differently or if I am missing something

**Comment by youknowriad** [comment]
How did you install the plugin? Did you install the npm dependencies and built the JS/css assets https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#installing--building-the-plugin ?

**Comment by eviolini** [comment]
sorry, no, I'll redo using those instructions, thanks

**Comment by youknowriad** [comment]
You're welcome. Closing for now, let me know if you have any trouble following the instructions.

**Comment by aduth** [comment]
I expect we should also upload zip files on the Releases tab once the beta plugin is made available.

https://github.com/WordPress/gutenberg/releases

**Comment by eviolini** [comment]
@youknowriad I'm running into an error. Using MAMP on MacOS I have the cloned repository in `wp-content/plugins` and when I type `run npm dev` I get `cross-env BABEL_ENV=default webpack --watch` in the npm error log. I'm on node 7.9.0.

**Comment by aduth** [comment]
@eviolini Did you first enter `npm install` before running `npm run dev`? The documentation is not entirely clear here, but it would be required to install dependencies first.

If you're still running into issues, can you clarify whether you're running Windows, Mac, or other?

**Comment by eviolini** [comment]
That worked and now I have Webpack is watching the files. I activated the plugin and all is good, thanks for the quick response.
