### ISSUE TITLE
Pasting text into empty paragraph sets cursor to start of text

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#11974]
If you paste text into an empty paragraph the cursor is set to the start of the text.

Before, with cursor at start:
<img width="284" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48621329-15d0ac80-e99b-11e8-8137-22fb875dede3.png">

After pasting, with cursor still at start
<img width="289" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48621350-2da83080-e99b-11e8-88fd-d6ed4d7fed3e.png">

The cursor is placed correctly when pasting elsewhere, such as at the end of existing text:

<img width="216" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48621381-46b0e180-e99b-11e8-8b1c-6826fd806e5e.png">

**To Reproduce**
1. Create a paragraph
2. Copy and paste some text into the empty paragraph
3. Note the cursor is at the start not the end

**Expected behavior**
Cursor to be after the text

Chrome, MacOS

**Comment by mrwweb** [comment]
I think this is a duplicate of #5317. Can you confirm, @johngodley?

**Comment by johngodley** [comment]
Yes, that's it - I looked back through, but not far enough. Closing this issue, thanks!
