### ISSUE TITLE
URL to Classic Editor plugin should be translatable

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#11983]
**Describe the bug**
In /gutenberg/tags/4.4.0/gutenberg.php there's a link to the Classic Editor plugin. It should be translatable, so that I can point to the Swedish version in the Swedish translation.

```
// Translators: link is for Classic Editor plugin.
--
__( 'The Block Editor requires JavaScript. Please try the <a href="%s">Classic Editor plugin</a>.', 'gutenberg' ),
'https://wordpress.org/plugins/classic-editor/'
);

```

**Comment by swissspidy** [comment]
Also, the translators comment could be change do something more like `translators: %s: https://wordpress.org/plugins/classic-editor/` in the same process. That's how we usually do it in core.

**Comment by mostafaabd** [comment]
Hi, Hi I'm a new contributer here , can you assign it to me

**Comment by swissspidy** [comment]
@mostafaabd Hi and thanks for showing initiative! There's no need to really assign issues. Everyone can just submit a pull request for issues like this.

In fact, there's currently already an open pull request (#11992) that aims to address this issue.

**Comment by mostafaabd** [comment]
@swissspidy Thanks, this is my first time, but i think this issue related to po file,, this file need to be updated, so this string will included into po file, but there is no docs to update po file.

**Comment by swissspidy** [comment]
@mostafaabd There's no need to deal with PO files at all. As soon as a string is made translatable and the code is updated in WordPress, users can translate it on translate.wordpress.org. Your WordPress site will then download the translations automatically from there.
