### ISSUE TITLE
Typo: superfluous word in block description "Media & Text"

### ISSUE THREAD

**Issue by pixolin** [WordPress/gutenberg#11986]
**Describe the bug**
Block description for "Media & Text" seems to contain a superfluous word "media".

**To Reproduce**
1. Add Block Media & Text
2. Carefully read block description
3. Wonder why the word "media" was used twice

**Expected behavior**
Text should read: 
`Set media and words side-by-side for a richer layout.`

**Screenshots**
<img width="291" alt="screenshot_364" src="https://user-images.githubusercontent.com/1968542/48629986-56d8b900-e9bb-11e8-89dc-2bae1c22d92b.png">

**Additional context**
WordPress 5.0-beta5-43907

**Comment by designsimply** [comment]
Good catch! This was also noted at https://github.com/WordPress/gutenberg/issues/10919#issuecomment-433291426 with the following suggested description for the Media & Text block:

> Set media and words side-by-side for a richer layout.

**Comment by antpb** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/10971
