### ISSUE TITLE
Permalink settings - unsufficient buttontext/info/usability

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#11980]
**Is your feature request related to a problem? Please describe.**
As the permalink settings are actual referenced in Gutenberg I see a long standing problem with the permalink settings Page and the "Save changes" button which has in fact two completely different functions
A) Save the chosen options of permalink settings (expected)
B) Use the permalink settings = update all permalinks (not so obvious)

After site-migration or other tasks like some Search&Replace operations in the database you have to update alls permalinks (case B) using the existing settings of A (NO changes on setting page to Save!)

So you have to click on "Save changes" - without any changes on the settings! - to update all permalinks.

**Describe the solution you'd like**
I see 3 possibilities:
1.) Change Buttontext to "Save changes & Update all Permalinks"
2.) Place a hint beside the "Save changes" button which explains what the button really does.
3.) Add a second button "Update all Permalinks" which can be used separately without "Save changes".

**Comment by swissspidy** [comment]
The permalink settings page is part of WordPress and not touched by the Gutenberg block editor.

You'd have to create a ticket at https://core.trac.wordpress.org/ for this request.

There's already lots of help text on that page though, so I don't think there's really anything else that could be added.

Also, it's a deliberate design decision by WordPress to use absolute URLs in the database. See https://make.wordpress.org/core/handbook/contribute/design-decisions/#absolute-versus-relative-urls. That means you have to do some search-replace operation when migrating sites or changing permalink structures.
