### ISSUE TITLE
Button color settings overridden in Twenty-* themes.

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#11998]
**Describe the bug**
As mentioned in https://github.com/WordPress/gutenberg/issues/11779#issuecomment-438753222
The Twenty-* themes are overriding the core button styles such as `.wp-block-button__link:not(.has-background)`. But they're doing it with an equally specific selector that also overrides the "utility" class applied for the color `.has-pale-pink-background-color`.

By relying on `:not()` to allow for color overrides, we're assuming everyone else will, as well.
Using `:not()` to style a button wouldn't be my first instinct.
Also discussed here https://github.com/WordPress/gutenberg/issues/11677

**To Reproduce**
1. Add a button in Twenty Seventeen or Twenty Sixteen from the WP 5.0 Branch.
2. Color the background and text color of the button.
3. Check it out on the front end.

**Additional context**
- Gutenberg v4.4

**Comment by designsimply** [comment]
Testing note: check to see if it happens in the plugin independently of WP5.0-betas.

**Comment by m-e-h** [comment]
This only happens when a theme explicitly sets the `color` or `background` on `.wp-block-button__link`. 

So it would only be a problem for the betas of the Twenty-* themes since the previous versions don't have any Gutenberg styles.

**Comment by m-e-h** [comment]
This can probably be closed with the fix in https://github.com/WordPress/gutenberg/pull/12005
But the default themes are still going to have to adjust their CSS to allow for the Button Color settings to take affect.

**Comment by youknowriad** [comment]
Thanks @m-e-h Awesome work.
