### ISSUE TITLE
Video Block: Update Poster Image UI

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#11991]
Based on some work on #7673 and #9457, I want to propose an updated UI for the Poster Image feature in the Video Block:

![video block - poster image](https://user-images.githubusercontent.com/2846578/48637450-c179fc80-e99b-11e8-8d56-06576f46023e.png)

This would:
- Split it out into its own sidebar panel
- Show a preview of the selected image
- Change the "replace" button styling into link styling and simplify the label
- Right align the "remove" link and simplify the label

**Comment by Soean** [comment]
@melchoyce If we change this UI, we should also change it for the featured image.

**Comment by afercia** [comment]
We've discussed a bit this issue during today's accessibility bug scrub but haven't came to a conclusion. We'll look a bit better next week, thanks 🙂

**Comment by afercia** [comment]
Discussed during today's accessibility bug scrub and we'd recommend a consistent pattern with the featured image as @Soean pointed out.

Also to consider the position of the buttons: ideally they should be close to each other for the "proximity of controls" principle, see https://core.trac.wordpress.org/ticket/40822

Lastly, preferably use more explicit buttons text to describe what the buttons do.
> The buttons should probably also be updated to "Replace Poster Image" and "Remove Poster Image"

**Comment by melchoyce** [comment]
Let's go with the existing pattern, and consider exploring a redesign of the pattern at a future time.

**Comment by Soean** [comment]
We go with the existing pattern, so I am closing this issue.
