### ISSUE TITLE
editor-styles-wrapper effecting previews in the components panel

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#11997]
![button-preview](https://user-images.githubusercontent.com/3585901/48642780-d2cb0500-e9ab-11e8-9e6f-0379a3f13ccf.png)

**To Reproduce**
1.Create a button in Twenty Seventeen from the WP 5.0 Branch
2. Checkout the button preview

**Cause**
This: https://github.com/WordPress/WordPress/blob/5.0-branch/wp-content/themes/twentyseventeen/assets/css/editor-blocks.css#L724

And this: https://github.com/WordPress/WordPress/blob/5.0-branch/wp-content/themes/twentyseventeen/assets/css/editor-style.css#L27

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Browser Firefox

**Additional context**
- Gutenberg 4.4

**Comment by m-e-h** [comment]
Twenty Sixteen too.
![twentysixteen](https://user-images.githubusercontent.com/3585901/48643253-428dbf80-e9ad-11e8-8b93-31dccdb83e35.png)
Also because of `body` margins.

**Comment by designsimply** [comment]
Noting to test these but also I think theme-specific issues should go to each theme's respective repository. I'll look into it!

**Comment by m-e-h** [comment]
Here you can see the issue as I toggle the  `body` margins on the `.editor-styles-wrapper`
![button-wrapper](https://user-images.githubusercontent.com/3585901/48789387-e7184600-ecba-11e8-9450-3a466df9140d.gif)

**Comment by m-e-h** [comment]
Not exclusive to buttons https://github.com/WordPress/gutenberg/issues/12066#issuecomment-440060106

**Comment by jasmussen** [comment]
Thanks for the ticket, but can you help me understand exactly what the issue is? I realize there's additional margin on items in the preview, and prior to the pullquote gap I just fixed, there was a white gap in the right side. However the presence of the editor style wrapper in the preview is intentional, insofar as the items in the preview _should_ inherit styles that the theme provides. The bug is not obvious to me (though forgive me if it should be, I've just had a sick kid for the past week so I'm slightly zombified).

**Comment by jasmussen** [comment]
Thank you for the clarification. I didn't mean for you to stop beating that drum, I think it's an important one, and with your clarifications even more-so. 

I suppose in light of that additional information, I still think that we should consider editor styles to b in their infancy and be be mindful with how far we're trying to go with them. However the purpose of doing this is exactly so tickets like yours can be raised and addressed as we continue to refine and improve the situation.

For example, I think Shadow DOM has huge potential here. Sadly it's not widely supported: https://caniuse.com/#feat=shadowdom

Element queries, similarly, will go a long way, but those are also not well supported and the polyfill isn't compatible with react and modern JS frameworks.

Finally, CSS `display: contents;` can probably go farther than any single other thing in improving the situation. https://css-tricks.com/get-ready-for-display-contents/

**Comment by jasmussen** [comment]
Submitted #12212 to potentially fix this.
