### ISSUE TITLE
Permalinks: Don't show the sidebar panel for CPTs that aren't viewable.

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#12008]
When a CPT isn't viewable (that is, it was registered with `publicly_queryable` set to `false`), the permalink sidebar panel shouldn't be shown.

This matches the behaviour in the `PostTitle` component.

https://github.com/WordPress/gutenberg/blob/cdeb4098607e8d5f1dc439e6527191359f1a1852/packages/editor/src/components/post-title/index.js#L143

A side effect of it being shown is that it causes a JS error.

![image](https://user-images.githubusercontent.com/352291/48654260-71646e00-ea5f-11e8-9042-f3453b90baae.png)

**Comment by danieliser** [comment]
Glad someone tracked it down, this has been driving me crazy all day as we had previously worked out support for the new editor in our CPTs and its now showing this same error.

**Comment by burnuser** [comment]
Easy solution: The Permalink sidebar panel should never be shown!
The editor is used for content and options according to a certain post/page.
The permalink settings are used for the whole site. And linking to it from the editor suggests, that there are some options for the actual edited post/page which can be adjusted. And than people would maybe insert plaintext rubbish in "Custom" permalinks settings and destroy their site!
The whole with Gutenberg 4.4 new included permalink sidebar panel should be removed!

**Comment by earnjam** [comment]
This is resolved in `master` (tested at f91e66ca2), so I'm going to go ahead and close this.  

CPTs with `'public' => false` or `'publicly_queryable' => false` both hide the permalink area in the title and sidebar.

**Comment by earnjam** [comment]
Whoops, hadn't refreshed the page.
