### ISSUE TITLE
Unregistering a block type causes blocks that convert to it to break the editor.

### ISSUE THREAD

**Issue by brianpiccione** [WordPress/gutenberg#12001]
**Describe the bug**
I have a number of blocks I don't want users to touch and so I've been unregistering them. I recently ran into an issue where that process actually breaks the editor. Specifically, it looks like when you unregister a block type that another block could convert to, the editor breaks. For example, I unregistered core/quote and then adding a UL/OL block to the content broke the editor because that block lists core/quote as one of the options it can convert to.

**To Reproduce**
Unregister core/quote. Try to add UL/OL block to editor -> editor breaks.

**Expected behavior**
Maybe, there should simply be a conditional in the "converts to" option in a block to check if its been unregistered? Not too sure here

**Screenshots**

**Desktop (please complete the following information):**
- Mac OS
- Chrome (but happens on all browsers)

**Additional context**
- Gutenberg 4.4

**Comment by La-Geek** [comment]
Is there possibly a causal relationship with #10554?
