### ISSUE TITLE
[4.4] tables block buggy...

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#12018]
### Describe the bug

A whole range of table bugs:

- Tables blocks do not correctly allow pasting of tables with empty cells (see: https://github.com/WordPress/gutenberg/issues/11547)
- Tables blocks do not allow selection of multiple cells (such as selecting a section to make formatting changes); If I want to make the text bold-face, I'd have to independently select text in each cell.
- down arrow doesn't do anything (should move down a block)
- up arrow doesn't move up (instead, it moves left, only every-other-time)
- left arrow button only works in empty cells
- pasting text copied from once into another cell creates an extra space above the pasted text (see: https://github.com/WordPress/gutenberg/issues/9504#issuecomment-436216728)
- table captions don't work (see: https://github.com/WordPress/gutenberg/issues/11589)
- cannot paste a range of cells into table; pasting only works if it's creating a brand-new table
- cannot paste a table from Google Docs (see: https://github.com/WordPress/gutenberg/issues/11193)

More related topics here: is:issue is:open table label:"[Block] Table"

**Comment by youknowriad** [comment]
Can you split this issue into smaller ones please if not existing, this doesn't really help moving things forward. Also worth noting that in the classic editor inserting tables is not possible unless you use a plugin or HTML, so I don't think this issue is very critical for the release.
