### ISSUE TITLE
Group heading / titles

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#12019]
This is related to (now deprecated) subheading-block discussion.

A title plus a short description (e.g. `<p>` element as subheading) should be 
grouped together so it can be styles with CSS (like a white border around it).

Currently the heading Gutenblock is not nestable and using a 
section element (not core) would be far too complicated.

Is there a "right" way for grouping heading elements (e.g. `<h1>` and `<h2>`) and 
other textual elements like paragraphs (`<p>`) together in Gutenberg in an for the user intuitive way?

**Comment by designsimply** [comment]
Any chance you can provide a code example showing your end goal? Would it be something like this?

```
<div style="border: 1px solid white">
<h2>Heading</h2>
<p>Description that goes with the heading just prior.</p>
</div>
```

In order to do something like that, you will want to use a Custom HTML block.

**Comment by strarsis** [comment]
@designsimply: I would prefer to not using a custom HTML block, 
the block should represent that this is a group of elements represting a heading 
and the user should be able to easily edit it.

**Comment by designsimply** [comment]
For now, I really think custom HTML code such as what you described is best added using the Custom HTML block. There are some proposals already filed which may be exactly what you're looking for but they are not ready yet. For example, a section or container block: https://github.com/WordPress/gutenberg/issues/4900

I found a possible alternate which is to use a columns block with an additional CSS class like this:

![screen shot 2018-12-03 at 5 28 16 pm](https://user-images.githubusercontent.com/1119271/49410174-ef439d00-f720-11e8-99cc-823e72fdbe19.png)

Then to style it with a border, you would do something like this in Customize > Additional CSS:

```
.my-custom-class {
	border: 1px solid red;
}
```

The only problem I found with this method is that the width of the inner columns didn't expand. It can be worked around with more CSS but the Custom HTML block is really the better choice in this case (and until more complex blocks like what you're describing are added in the future)."

I will close this issue in favor of #4900 and with the workaround to use Custom HTML in the mean time. Sorry I didn't have something better for you already!

**Comment by strarsis** [comment]
So when the subheading isn't really semantically a heading (doesn't belong into the document outline), one can just use a paragraph block and a block style, e.g. `subheading` from the theme to make it look like a subheading.
For grouping title and extra stuff, the Gutenberg core `group` block can now be used.
