### ISSUE TITLE
Feedback: Paragraph Blocks & Basic Editor

### ISSUE THREAD

**Issue by dajaridi** [WordPress/gutenberg#12010]
I have used gutenberg for a few hours and have decided to unistall it. 

1. **Why is every paragraph a separate block?** Surely a block of text be able to have paragraphs, not every paragraph be a block. I must be missing something, but try and copy a full page of text that has paragraphs.

2. **Why is the editor remained so basic?** The first plugin I have installed for around 10 years now is TinyMCE Advanced. (It shouldn't need to be a plugin, it should be part of the WP install.)

Please make sure gutenberg is not hard coded and remains as a plugin so it can be deleted in future WP updates. It  would be a PITA to have to add another plugin to remove gutenberg.

FYI I will return to SiteOrigin and TinyMCE.

**Comment by overcatbe** [comment]
luckily SiteOrigin DOES have a Gutenberg block, which works JUST fine :D 
Also, try the Atomic Blocks plugin (and theme) - they are wonderful.

**Comment by annezazu** [comment]
@dajaridi Hope this finds you well! I'm going through older issues when I noticed yours. I'm curious what you make of the experience now whether through using the latest version of WordPress (5.6.1 as of tomorrow) that includes updates to the core editor through Gutenberg releases or through using the latest version of Gutenberg (9.8.3). 

I'm going to add the needs more information label either way which will kick off an automatic process to close this issue in time if we don't  hear back. If you'd rather not re-open this issue to share updated feedback, you can always ping me in WordPress.org slack with feedback at @annezazu :)

**Comment by dajaridi** [comment]
> luckily SiteOrigin DOES have a Gutenberg block, which works JUST fine :D
> Also, try the Atomic Blocks plugin (and theme) - they are wonderful.

Thanks Overcatbe, I will look into Atomic.

**Comment by dajaridi** [comment]
> @dajaridi Hope this finds you well! I'm going through older issues when I noticed yours. I'm curious what you make of the experience now whether through using the latest version of WordPress (5.6.1 as of tomorrow) that includes updates to the core editor through Gutenberg releases or through using the latest version of Gutenberg (9.8.3).
> 
> I'm going to add the needs more information label either way which will kick off an automatic process to close this issue in time if we don't hear back. If you'd rather not re-open this issue to share updated feedback, you can always ping me in WordPress.org slack with feedback at @annezazu :)

Hi Annezezu. Thanks for asking. I have been using the old,  Tiny MCE renamed as Advanced Editor Tools  for most of my projects when I just want a simple blog site. 

I have used SiteOrigin when wanting to make more complex pages, usually the home page, columns, sliders ads etc...

Curiously, your post was made here just as I am just about to start a new project, (actually transferring an older HTML site to WP), and was just thinking I should give Guttenberg a go. I'll also try overcatbe's suggestion of Atomic blocks and theme. One thing I don't like about Gutenberg is how large it is and how much screen space it takes up. I'm more of a "more is more" when onscreen, rather than scrolling up and down searching for stuff. But I'll learn.

So all is not lost. Guttenberg seems to have come a long way, but this time the first plugin I won't install is Classic Editor. Thanks again for enquiring!

**Comment by annezazu** [comment]
Whew, right back at you. I feel so fortunate to have not gotten sick. What a wild time! Thanks for responding btw and for sharing extra context around what you're using now for your sites. I'm curious how you find the experience of just using the WordPress editor (without installing Gutenberg). Generally speaking, Gutenberg right now definitely still has some more experimental projects in it like the Widgets Editor being revamped to include blocks: https://github.com/WordPress/gutenberg/projects/27 I imagine you'll get the benefits of the improvements just in using 5.6.1 without needing to install Gutenberg unless you want to test out the more recent features :) 

> One thing I don't like about Gutenberg is how large it is and how much screen space it takes up

In case you're talking about how the editor looks, here's a quick video with some helpful settings you can adjust to ideally have the creating experience you want:

https://user-images.githubusercontent.com/26996883/106779134-eeaa3800-6603-11eb-9ba4-73498cc5ac71.mov

Either way, I'd love to hear how it all comes along. As mentioned you can find me in WordPress.org slack as @annezazu! Happy WordPress-ing.
