### ISSUE TITLE
Need to get HTML as saved in DB with js in frontend

### ISSUE THREAD

**Issue by InoPlugs** [WordPress/gutenberg#12014]
Hi,

Sounds easy, but I could not find a solution up to now - and nothing in the docu how to get it.

I need to scan the blocks with js and want the HTML of the blocks as placed in db field post_content.

Should be something like this:

```

var blocks = wp.data.select( 'core/editor' ).getBlocks();
var html = '';

jQuery.each( blocks, function( index, block ){
       html +=  block.getHTML() + '<br />';
}

........

```

Thanks for your help.

**Comment by swissspidy** [comment]
Are you trying to do this in the front end or inside the editor?

What exactly do you want to achieve?

**Comment by InoPlugs** [comment]
@swissspidy 

Thanks for your quick reply.

I'm core developper for Enfold theme and we try to integrate our layout builder in the editor.

In backend user has a button to switch to our advanced layout builder - the block editor is hidden with CSS.

When switching we want to copy the content of already entered blocks into a text area of our builder using javascript. We would need the HTML you store in the post_content field of the post in database - something like:

```

<!-- wp:heading {"level":1,"align":"left","className":"my-class"} -->
<h1 style="text-align:left" id="my-point" class="my-class">My first heading</h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This is my content</p>
<!-- /wp:paragraph -->

<!-- wp:shortcode -->
[av_heading i='1' av_uid='av-vsub']inside Text[/av_heading]
<!-- /wp:shortcode -->
```

We could do it with savePost() function and loading with ajax from the server, but this solution does not make me happy. 

There must be a way to do it with js.

Thanks in advance.

-----------
WP 5.0-beta-3

**Comment by youknowriad** [comment]
If it's outside the gutenberg context, you need to use the REST API to fetch the saved raw HTML.

If it's in the gutenberg context, you could do `wp.data.select( 'core/editor' ).getEditedPostContent()`

I hope this helps.
