### ISSUE TITLE
Prevent post saving until title, content, or excerpt non-empty

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#1201]
__Steps to reproduce:__

1. Navigate to Gutenberg > New Post

__Expected result:__

I should not have the option to save the post.

__Actual result:__

I have the option to save the post. When I try to save the post, the request fails:

```
{"code":"empty_content","message":"Content, title, and excerpt are empty.","data":{"status":400}}
```

We should validate that one of title, content, or excerpt is not empty before allowing the post to be saved.

See also: https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/edited-post-has-content.js

**Comment by theMikeD** [comment]
I don't suppose there is a way for me to hook into this somehow to prevent the save button from being active until arbitrary event x has occurred? For example I'd like to force the user to write a manual excerpt.
