### ISSUE TITLE
List block: pasting text in empty indented line unindents the line

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#12016]
## The issue
In the List block, if you create a list item, indent it, and then paste some text into it, the list item will be unindented for some reason. This is very annoying when you're trying to make detailed, nested lists, such as an outline or table of contents.

## Steps to reproduce
1. Insert a List block.
2. Create a list item below the initial one.
3. Indent the list item using the <kbd><samp>Indent list item</samp></kbd> button in the toolbar. (Speaking of which, I wish there were keyboard shortcuts for this... #9611)
4. Copy some text from somewhere and paste it in the list item.
5. Notice how for some reason the list item is unindented.

Tested in Firefox Developer Edition 64.0b10 on Antergos Linux.

**Comment by La-Geek** [comment]
_**Confirmed.**_ Windows 10 64bit, Chrome, WP Beta 5.0-beta5-43907, Theme Twenty Nineteen
_**As second bug**_: You can't insert a linebreak (STRG+enter) in a list item

![copy_and_paste_in_lists](https://user-images.githubusercontent.com/1585416/48663381-a092d380-ea8f-11e8-86ec-df0541654183.gif)

**Comment by iseulde** [comment]
Should be fixed after #12089.
