### ISSUE TITLE
wp.media change between GB plugin v4.4.0 and WP 5.0 beta 43907?

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg#12025]
Has there been a change to the wp.media JavaScript object between WP 4.9.8 with Gutenberg plugin 4.4.0 and WP 5.0 beta? I've got a gallery plugin that I wrote that uses the following:

 - wp.media
 - wp.media.frames.file_frame
 - wp.media.controller.Library

Now that I've updated to using the nightly build for the 5.0 beta, my plugin throws 'TypeError: "t is undefined"'. I don't think I'm doing anything untoward, and this JavaScript is neither uglified nor mangled, and it doesn't include a variable named 't'.

Sorry this is rather oblique insofar as a bug report, but does anyone have any ideas where to start looking for the issue?

**Comment by designsimply** [comment]
Any chance you can check to see if the same error happens for you with WP4.9.8 and the Gutenberg nightly build? (Or is your plugin available online for testing?) This could help rule out a core issue that isn't related to Gutenberg.

I checked the deprecations page in the Gutenberg handbook at https://wordpress.org/gutenberg/handbook/reference/deprecated/ and didn't find any `wp.media` things you've listed mentioned there.

Does the error show up on page load or for some other specific action?

And, just to make sure, do you have any other plugins active which could be causing the trouble?

**Comment by maxxwv** [comment]
All plugins are deactivated except mine. Unfortunately, it's proprietary code so it's not available to the public. I'll try building GB from the repo and see if that crashes it, too - hadn't thought to try that.

The error shows up on page load when selecting a CPT record in the admin back-end. I'll ask my manager on Monday if I can maybe invite a couple people to the repo for troubleshooting and investigation if I can't figure it out in the meantime.

I'll let you know about the nightly build with 4.9.8 - thanks!

**Comment by maxxwv** [comment]
Latest version of WP 5.0 beta (5.0-RC1-43944) is working as expected, so this can be closed for now.

**Comment by designsimply** [comment]
🎉 Thank you for testing again and for the follow-up notes!
