### ISSUE TITLE
Can't delete tag in Posts with large number of tags

### ISSUE THREAD

**Issue by mtibesar** [WordPress/gutenberg#12020]
Reference this page with a lot of tags: 

https://tibesar.com/2011/06/23/loraine-elizabeth-reisdorf-tibesars-90th-birthday/

On posts with large number of tags, I am unable to delete the "featured" tag.

When I click on the "X" next to the tag the Tags Window jumps up to the top or jumps down to the bottom. The "featured" tag remains and repeated attempts to delete the tag fail.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] chrome, safari and firefox
 - Version [e.g. 22] Latest versions of these browsers and macOS

**Additional context**
- Using Gutenberg 4.4

**Comment by mtibesar** [comment]
I did some testing. 

I discovered that on the rows with two tags I can't delete either of the two tags. On rows with a single tag I can delete the tag.

For example:

Tag1 X   Tag2 X
Tag3 X
Tag4 X

In this example I can't delete Tag1 and I can't delete Tag2.

However, I can delete Tag3 and Tag4.

**Comment by mtibesar** [comment]
I was able to eventually deleted Tag2 by going to Admin -- Posts -- Tags and deleting all the featured tags there.

**Comment by youknowriad** [comment]
> On posts with large number of tags, I am unable to delete the "featured" tag.

How many tags are you using on that post? This will help us reproduce and potentially fix the issue.
