### ISSUE TITLE
List block doesn't save indentation

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#12027]
**Describe the bug**
When I update the content with list block, the block is saved fine and show up in the front end, but any indentation is ignored. When I refresh the editor, the indentation is gone!

**To Reproduce**
1. Add list bloc with some list items.
2. Indent some of the list items, they will indent fine.
3. Click "update" and go to the front end, the list block is there but with no indentation.
4. Go back to the editor and refresh the page, the list block is there but with no indentation.

**Expected behavior**
The list block should save indentation.

**Screenshots**
![list-block-bug](https://user-images.githubusercontent.com/3824596/48670785-6c1e2680-eb26-11e8-8fca-2c6af50c581d.gif)

**Desktop**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: 70.0.3538.102

**Additional context**
- WordPress v4.9.8
- Gutenberg plugin v4.4.0

**Comment by earnjam** [comment]
I've confirmed this in the latest from `master`. It has the proper `<ul></ul>` tags to make it appear indented on the visual editor, but switching to edit with HTML, or previewing the post strips those out. 

![list-indent](https://user-images.githubusercontent.com/4267290/48671337-64458e80-eaf4-11e8-9037-5355e8fbd719.gif)

**Comment by earnjam** [comment]
Looks like it doesn't save because the post is not considered dirty on indentation-only changes to the list block. 

The required `<ul></ul>` tags _are_ present on the page to show the indentation when in the visual editor, but it appears they aren't getting added to the markup. Switch to the HTML edit mode of the block and they are _not_ present.

**Comment by iseulde** [comment]
This happens because the DOM is updated by TinyMCE command, but we're not updating the internal value.
