### ISSUE TITLE
Convert to blocks does not handle invalid lists and HTML without block equivalent

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#12029]
## How to reproduce 

* Create a new post, go to code editor mode, and paste [this content](https://github.com/WordPress/gutenberg/files/1527889/post.html.txt).
* Change to visual mode. The content should be fully renderer in one block - the classic block.
* Check the document stats: it's 10.605 words long.
* Convert it to blocks. [This](https://github.com/WordPress/gutenberg/files/2594485/demo-converted.html.txt) is the resulting content.
* Check the document stats: it's 8.269 words long.

Observe that one of the last sections was entirely gone (anything following the "Una panorámica general de las herramientas"). I expected no content was lost.

Note that the post has some really bad-formatted HTML and I don't expect Gutenberg to fix that.

## Data

| | | |
| --- | --- | --- |
| Original post in classic | [HTML](https://github.com/WordPress/gutenberg/files/2599794/post-classic-editor.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2599776/post-classic-editor.txt) |
| Post converted to blocks 489eb79^1 | [HTML](https://github.com/WordPress/gutenberg/files/2599795/post-gutenberg-converted-before-489eb79.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2599775/post-gutenberg-converted-before-489eb79.txt) | 
| Post converted to blocks at 489eb79 |  [HTML](https://github.com/WordPress/gutenberg/files/2600052/post-gutenberg-converted-at-489eb79.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2600050/post-gutenberg-converted-at-489eb79.txt) |

**Comment by nosolosw** [comment]
Bisected from v4.0.0-rc.1 to current master: it looks like this may have started happening in 489eb79.

Before that commit, Gutenberg reported 9.981 words after converting the old post to blocks (less than 10.605 in the original) but I couldn't find noticeable content loss.

**Comment by iseulde** [comment]
@nosolosw Do you see which section of the content is lacking words? Could you post the post processed HTML?

**Comment by nosolosw** [comment]
[This](https://github.com/WordPress/gutenberg/files/2594485/demo-converted.html.txt) is the resulting post after conversion. The contents after "Una panorámica general de las herramientas" are lost, I haven't found any other issue.

**Comment by iseulde** [comment]
> I haven't found any other issue.

Seems weird that there's a 2000 word difference and there's no other noticeable issue?

**Comment by catehstn** [comment]
@designsimply can you please take a look at this and see if you can repro?

**Comment by nosolosw** [comment]
I've tried to diff the original content (within the classic block) and the content converted to blocks. I couldn't get all content once it's converted to blocks (when copied Gutenberg gives the HTML content, not the visual content) so I wasn't able to compare.

I've also tried some random things in the original before converting (removing some tags, ids, etc) in case I was lucky and would find the minimal test case - but I wasn't.

**Comment by nosolosw** [comment]
I wanted to also note that the content in the classic block within Gutenberg is the same content I have when opening the post with the classic editor.

**Comment by nosolosw** [comment]
[This is the post content](https://github.com/WordPress/gutenberg/files/2599724/post-converted-before-489eb79.txt) after conversion, but before 489eb79.

**Comment by nosolosw** [comment]
Updated issue description with all data (HTML and Visual).

**Comment by youknowriad** [comment]
Converting to blocks is a destructive operations that can be undone, It'd be good to optimize this further but I don't think it's blocking.

Worth considering a confirmation message to clarify this for the user.

**Comment by iseulde** [comment]
Related #11244, cc @jorgefilipecosta

**Comment by iseulde** [comment]
Another issue seems to be that there's a few invalid lists in your original content:

```
<ol>
<ol>
<ol>
<ol>
...
```

I'm not sure what we're supposed to do with this.

**Comment by nosolosw** [comment]
Tested current `master` and the conversion is almost perfect now, which is impressive taking into account the amount of crazy HTML that post has.

I only found a few cases were converting was lousy, one was a bad formatted list with several nested levels, the others can be replicated by this test case: 

* Create a new post with an classic block
* Select the classic block, "Edit as HTML" and paste this:

```
<p>Intro to consecutive UL lists:</p>
<ul>
<li>First</li>
</ul>
<ul>
<li>Second</li>
</ul>
<ul>
<li>Third</li>
</ul>
<p>Closing.</p>
```
* Convert to blocks

The second and third UL lists would be missing.

**Comment by nosolosw** [comment]
Actually, there is already an issue for that https://github.com/WordPress/gutenberg/issues/7702

**Comment by iseulde** [comment]
> I only found a few cases were converting was lousy, one was a bad formatted list with several nested levels

Could you report this case as well?

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/12156 fixes both #7702 and the bad formatted list with several nested levels I've mentioned [above](https://github.com/WordPress/gutenberg/issues/12029#issuecomment-440403496).

With #12156 in, convert to blocks not only preserves all content of the original post, but it fixes crazy bad formatted HTML. This is stellar work! :star2:

**Comment by iseulde** [comment]
Awesome! I've seen some places where we can do better. Seeing some occurrences of `<b>something</b>` as HTML blocks, which is there because it's not known as parsing content to us. Perhaps we should extend our list for block conversion.

**Comment by iseulde** [comment]
Anyway, lower priority for now.

**Comment by designsimply** [comment]
Tested and confirmed with current master (`bd897f6cb`) that pasting the content provided in HTML, switching to visual, then converting to blocks results in the same number of words, 10605, before and after the conversion. ([screenshot 1](https://user-images.githubusercontent.com/1119271/48961978-cbb96f00-ef36-11e8-88bf-3de704b8d24d.png)), [screenshot 2](https://user-images.githubusercontent.com/1119271/48961982-d8d65e00-ef36-11e8-9ad0-247ddfb08d33.png)) 👍
