### ISSUE TITLE
(Safari) Post Publish Panel: "Copy Link" wrongly copies block content if one is selected

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#12032]
**Describe the bug**

See steps to reproduce.
Appears similar to #4268, fixed by #4271. /cc @iseulde 

**To Reproduce**

1. Write a post, and publish or schedule it.
2. Click on any block to make sure one is selected.
3. The post-publish panel should appear. Under _What's Next_, click _Copy Link_.
4. Inspect clipboard content, notice it corresponds to the selected block (`<!-- my/block ...`).

**Expected behavior**

The post permalink should've been copied instead.

**Desktop**
 - OS: macOS Mojave
 - Browser: Safari

**Comment by earnjam** [comment]
This is only happening in Safari for me. Firefox and Chrome are both copying the URL as expected.

**Comment by mcsf** [comment]
I can't reproduce this one anymore. I'm closing, but reopen if you can.
