### ISSUE TITLE
Paragraph: Misplaced caret when clicking on a Drop Cap-enabled paragraph

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#12034]
**Describe the bug**

Paragraph's "drop cap" feature is only previewed when a block isn't selected (due to poor handling of some browsers when typing in a text field with a drop cap). Thus, when such a block is selected, the drop cap recedes, changing the composition of the text.

Clicking on a block to select it results in the caret being placed where the click happened, and not at the intended text offset.

**To Reproduce**

See screencast.

**Screenshots**
![drop-cap-caret-misplaced](https://user-images.githubusercontent.com/150562/48673731-616e8c00-eb3c-11e8-9874-2ef31205f9bc.gif)

**Comment by mcsf** [comment]
@iseulde: I haven't bisected, but I suspect this is a recent regression stemming from RichText changes. If this is a quick fix, it's worth getting in soon. Otherwise, we can punt.

**Comment by iseulde** [comment]
I think this has always been an issue?

**Comment by mcsf** [comment]
Self-closing as duplicate of #11119.
