### ISSUE TITLE
Sidebar permalink panel: improve the URL field label

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12033]
Splitting this out from #11874.

I'd tend to think the input field label `URL` is a bit confusing, as users might think they have to fill the field with a complete URL starting with `http(s)`.

<img width="302" alt="screenshot 2018-11-18 at 14 27 02" src="https://user-images.githubusercontent.com/1682452/48673098-31c08380-eb3e-11e8-8521-af490802d42c.png">

I've read https://github.com/WordPress/gutenberg/issues/11858#issuecomment-438921521 and it makes perfectly sense to avoid technical terms. However, the label could be improved a bit. Also noting Squarespace does use some form of "URL" label but it also expands it adding "slug":

<img width="552" alt="screenshot 2018-11-18 at 13 55 29" src="https://user-images.githubusercontent.com/1682452/48672843-36d00380-eb3b-11e8-8780-4f569a7c3420.png">

Other mentioned platforms use some form of "URL" as well, but at least they make it visually clear it's about the last part of the URL:

<img width="481" alt="screenshot 2018-11-18 at 15 07 48" src="https://user-images.githubusercontent.com/1682452/48673729-c201c700-eb44-11e8-8a54-ee6197c15a12.png">

<img width="241" alt="screenshot 2018-11-18 at 15 12 35" src="https://user-images.githubusercontent.com/1682452/48673730-c201c700-eb44-11e8-9545-478974bac201.png">

Personally, I have no strong opinions on which the best wording would be, but I'd suggest to consider a more meaningful one.

**Comment by afercia** [comment]
Not sure if it can help, but worth considering the explanation of what a "permalink" is in WordPress in the Help page linked from the Classic Editor help tab:
https://codex.wordpress.org/Posts_Add_New_Screen

**Comment by timwright12** [comment]
@afercia I updated it to "URL Slug" just so we have an open PR. Happy to update it, but I think that actually works pretty well.
