### ISSUE TITLE
Document structure: Headings, Paragraphs, and Blocks counts are wrong

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12042]
Tested on latest master 4.4.0:

- create a new post
- enter a title
- click in the default empty block
- the "Content Structure" button gets enabled
- click on the button to reveal the panel with the Headings, Paragraphs, and Blocks counts
- I get the following counts:
  - 1 heading
  - 4 paragraphs
  - 8 blocks
- also, the "Document Outline" title is visible, even if there's no headings hierarchy to show

<img width="1079" alt="4 4 0" src="https://user-images.githubusercontent.com/1682452/48677032-53862e80-eb6f-11e8-9c31-6874fa8fc35d.png">

Tried to save as draft, refresh the page, navigate away and edit the post again: the counts are always showing 4 paragraphs and 8 blocks which I don't have in my post.

I'm not sure when this started but I seem to recall it worked correctly at some point. I've randomly tried  older versions of Gutenberg and in 2.9.0 the counts look correct:

<img width="1074" alt="2 9 0" src="https://user-images.githubusercontent.com/1682452/48677063-d0190d00-eb6f-11e8-9724-57013fdbca02.png">

**Comment by earnjam** [comment]
I haven't been able to recreate this yet 🤔 

I initially tried in `master`, but I also tried with the `v4.4.0` tag. I tried on WP 4.9.8 or WP 5.0 beta 5.

**Comment by afercia** [comment]
Will double check on a second machine because I've been noticing strange behaviors when trying to reproduce consistently.

**Comment by afercia** [comment]
Tested on a second machine
- WP trunk also known as 5.1 alpha
- Gutenberg 4.4.0 latest master

The counts are different but still wrong: 
- 0 headings
- 5 paragraphs
- 5 blocks

My test post has definitely just the title and the default empty block:

![screenshot 145](https://user-images.githubusercontent.com/1682452/48693952-4acb4200-ebdb-11e8-950c-70bde27d49af.png)


No JS errors, just a few warnings related to deprecations.

**Comment by afercia** [comment]
After further investigation, it appears this has to do with reusable blocks. In the screenshot below, that's what `state.editor.present.blocks.byClientId` in `getGlobalBlockCount()` shows to me:

![screenshot 2018-11-19 at 09 30 27](https://user-images.githubusercontent.com/1682452/48695724-2faf0100-ebe0-11e8-9dbd-9ecba84338dc.png)

One of the empty blocks listed there is the default block in this post. All the other ones are reusable blocks _not used_ in this post but returned and counted anyways. 

I've also tried to delete all my reusable blocks and after that the count was correct. As soon as I've created a new reusable block in another post, then edited again this post, the count was `2`.

This also explains why on the other machine I get a different count: it actually depends on the amount of reusable blocks saved in your database.

When testing, please make sure you have some reusable blocks.

**Comment by earnjam** [comment]
This was fixed by #11787

**Comment by afercia** [comment]
Ah I see. Merged 5 hours ago 🙂 👍 Thanks.
