### ISSUE TITLE
Activating Gutenberg along with WPML and Yoest SEO makes snippet preview for Yoest disappear!

### ISSUE THREAD

**Issue by rastezzy** [WordPress/gutenberg#12045]
Hi,
I've been doing multiple testing on my own theme Zoner and WordPress Core themes trying to figure out what does stop Yeost snippet preview/content optimization from disappearing from all the posts and pages.

Just somehow disabling either Gutenburg or WPML plugins helps my see my snippet preview/content optimization for Yoest on pages and posts normally. 

I've opened a ticket at WPML and someone from the support team is working with me on the problem, so I thought I'd give Gutenburg's team a heads up about the issue also.

Regards

**Comment by designsimply** [comment]
Can you confirm steps to reproduce the problem with Gutenberg? Here's my assumption:

1. Install WordPress 4.9.8.
1. Install Gutenberg 4.4.
1. Activate the latest default theme, Twenty Seventeen.
1. Note whether Gutenberg works normally.
1. Install Yoast SEO 9.1.
1. Open the Gutenberg demo post (or another Gutenberg post with content).
1. Scroll to the end of the post and verify that the "Snippet Preview" section appears normally and can be modified.

**Result:** the snipped preview section appears normally and can be modified using the Yoast SEO meta box.

![screen shot 2018-11-19 at 1 35 59 pm](https://user-images.githubusercontent.com/1119271/48733522-1f0e8300-ec00-11e8-8f16-f9922f45d6f1.png)
<sup>Tested with WordPress 4.9.8 and Gutenberg 4.4 `2be9a298b` and Twenty Seventeen 1.7 using Firefox 63.0.1 on macOS 10.13.6.</sup>

If I got any of the steps wrong or if I have misunderstood where the conflict is, let me know a corrected list of testing steps and I can try it again!

Can you also please note the WordPress version, Gutenberg plugin version, and theme versions you used for testing?

**Comment by designsimply** [comment]
Closing and asking if you can please re-open the issue with notes about what versions you are testing with and if you can spot anything I need to change in my testing steps. Thank you!
