### ISSUE TITLE
Inline image goes at top of the classic block

### ISSUE THREAD

**Issue by Shofol** [WordPress/gutenberg#12041]
**Bug Description:**
The inline image goes at the start after uploading in a classic block.

**To Reproduce**
1. Go to an old post made on the classic editor.
2. Click on 'Insert Media'
3. Scroll down to 'See your image placed on where you wanted'
4. The image is set at the top of the block

**Expected behavior**
The image should be added at the place where the cursor was placed to upload the media

**Screenshots**
![wordpress error](https://user-images.githubusercontent.com/30428153/48676487-e0da7a80-eb91-11e8-9062-82d6b1b2e827.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome  
 - Chrome Version 70.0.3538.102 (Official Build) (64-bit) 

**Additional context**
- Gutenberg Wordpress Free Version.

**Comment by Soean** [comment]
Hey  @Shofol,
thanks for reporting this issue. We already have an open issue about this topic, see #10509. So I am closing this as a duplicate.
