### ISSUE TITLE
ToggleControl visually broken when wrapped in `Disabled` component

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#12049]
`ToggleControl` is visually broken by having a thick rectangular border around it when wrapped in `Disabled` component.

<img width="221" alt="screenshot 2018-11-19 at 10 03 32" src="https://user-images.githubusercontent.com/87168/48693677-e6ac7c00-ebe2-11e8-8599-3a84b6c75be6.png">

**To Reproduce**

1. Use Gutenberg 4.4.0 or [current](https://github.com/WordPress/gutenberg/commit/78a736462f8d1d70b838125b493918d472353384) `master`.

1. Create a block:
    ```jsx
    import { registerBlockType } from '@wordpress/blocks';
    import { Disabled, ToggleControl } from '@wordpress/components';
    import { Fragment } from '@wordpress/element';
    import { InspectorControls } from '@wordpress/editor';

    const toggles = (
      <Fragment>
        <Disabled>
          <ToggleControl label="This is disabled" />
        </Disabled>
        <ToggleControl label="This is not disabled" />
      </Fragment>
    );

    registerBlockType( 'demo/toggle-control', {
      title: 'Toggle Control demo',
      category: 'layout',
      edit: () => (
        <Fragment>
          <InspectorControls>{ toggles }</InspectorControls>
          { toggles }
        </Fragment>
      ),
      save: () => null,
    } );
    ```

1. Insert block in the editor
Observe how disabled toggle has funky borders around it in both sidebar inspector as well at the block content area.
    

**Expected behavior**

✔︎ No funkiness.

**Desktop:**
 - OS: MacOS
 - Browser Firefox
 - Version 63

**Comment by catehstn** [comment]
This is not great, @jasmussen can you take a look when you have a minute? I'm hoping this will be some straight forward CSS <3

**Comment by jasmussen** [comment]
Sure I'll take a look.

**Comment by jasmussen** [comment]
Submitted #12091 to fix this.
