### ISSUE TITLE
Editor Store: refreshPost() returns cached post

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#12055]
**Describe the bug**
Contrarily to what its name suggests, `refreshPost` doesn't actually refetch post data from the network. Found here: https://github.com/Automattic/wp-calypso/issues/28664

**To Reproduce**
1. Edit a post
2. Open your browser console's 'Network' tab, and clear it
3. In the browser console, enter `wp.data.dispatch( 'core/editor' ).refreshPost()`
4. Go back to the 'Network' tab. Note that no network request has been fired.

**Reason**
This is happening because of `apiFetch`'s [`preloading` middleware](https://github.com/WordPress/gutenberg/blob/b198e5c4791b2282332def0de89841cd64d75f8e/packages/api-fetch/src/middlewares/preloading.js), which is used to preload and cache data for some REST API routes -- among them, posts. Specifically, try commenting out https://github.com/WordPress/gutenberg/blob/b198e5c4791b2282332def0de89841cd64d75f8e/lib/client-assets.php#L1075-L1079 and running through the above steps again -- verify that `refreshPost` then actually fires a network request.

**Additional context**
- Using Gutenberg 4.4.0.
- This is sort of a follow-up to #11879, related to work on Jetpack's Publicize Gutenberg extension (which is mostly happening in the Automattic/wp-calypso repo)

/cc @tyxla

**Comment by ockham** [comment]
I'm not sure about the best way to fix this yet. Maybe just an additional argument to `apiFetch` to bypass caching?

**Comment by tyxla** [comment]
I confirm I can reproduce this 👍 

It's unexpected that we can't trigger a refresh of post by dispatching the corresponding action, so this feels like a bug.

**Comment by youknowriad** [comment]
> I'm not sure about the best way to fix this yet. Maybe just an additional argument to apiFetch to bypass caching?

Seems reasonable enough for me 👍

**Comment by ockham** [comment]
Fix in #12058

**Comment by ockham** [comment]
Alternative fix in #12060
