### ISSUE TITLE
gap in border of style preview of pullquote

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#12066]
![image](https://user-images.githubusercontent.com/18373563/48712363-d8c02080-ec0d-11e8-835e-e1c308a2bf10.png)

Seing that under Windows10x64, Chrome, WP 5.0 beta 43907 and Twentyseventeen Theme. It is not there with the Twentynineteen theme.

After reporting it on slack here the answer of joen :

> Second is the issue with the white cutoff happening on the right side of the variation buttons. This appears to be a Windows specific issue. Feel free to ticket this particular issue, and CC me (@jasmussen on Github)

Well, here I am with the ticket.

**Comment by designsimply** [comment]
Tested and confirmed that I can see the gap on the right for style variations of the pullquote block using WordPress 5.0-beta5-43908 with Twenty Seventeen on both Mac and Windows (tested Chrome 70 on Win10 and Chrome 70.0.3538.77, Firefox 63.0.1, Safari 12.1 on macOS 10.13.6).

![bs_win10_chrome_70 0](https://user-images.githubusercontent.com/1119271/48738136-41f36400-ec0d-11e8-8b64-9c73c7c01f70.jpg)
<sup>Seen at https://madefortesting.com/wp-admin/post.php?post=698&action=edit running WordPress 5.0-beta5-43908 and Twenty Seventeen 1.7 using Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

I cannot cannot see the problem when testing with the plugin (master `1e5f88595`) and WordPress 4.9.8 ([screenshot](https://user-images.githubusercontent.com/1119271/48738113-2ee09400-ec0d-11e8-808f-c296e4e45def.png)).

**Comment by jasmussen** [comment]
Created #12090 to fix this. Thanks for the report, the TwentySeventeen issue was the key to discovering this.

**Comment by m-e-h** [comment]
@jasmussen pretty sure this was partially related to https://github.com/WordPress/gutenberg/issues/11997#issuecomment-439727067 and the `.editor-styles-wrapper` in the components-panel.
Looks exactly the same for the pullquote.

![button-wrapper](https://user-images.githubusercontent.com/3585901/48789538-4c6c3700-ecbb-11e8-9c8e-2937022b0976.gif)
