### ISSUE TITLE
Editor: Improve `edits` reducer's unsetting of merged values

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#12065]
Related: https://github.com/WordPress/gutenberg/pull/10827#discussion_r234624848

While handling of nested values (i.e. meta) was improved in #10827, it left a remaining edge case where updated values may be needlessly left in `edits` state if not all meta values can be considered as updated to their canonical form.

We should consider improving the reducer such that in the handling of `UPDATE_POST`, if the key for which updates are received is one of the file's `EDIT_MERGE_PROPERTIES` properties, it should individually unset values from the received canonical value which align, removing the top-level key if all values are the same.

**Comment by paaljoachim** [comment]
This issue is not really old and I see a PR has been merged.
I will go ahead and close this issue.
@gziolo (I am pinging you in here Greg.)
