### ISSUE TITLE
Reusable Blocks: Incorrect label appears in block breadcrumb component

### ISSUE THREAD

**Issue by holtjohnson** [WordPress/gutenberg#12079]
When I hover over a reusable block before I click on it shows the label in the top right corner to be "Reusable Block" as expected. When I'm editing the reusable block and hover over a block inside the reusable block the label in the top right corner shows "Reusable Template" as the parent when I would expect "Reusable Block". I'm a site developer working to understand exactly how Gutenberg is put together and works. When using Gutenberg I've started to use the hover labels in the top right to tell me where I am and is incredibly helpful when working with block nesting (inner blocks). If this is intentional and part of how reusable blocks work could you link me to the documentation? If this is only a labeling mistake, would you mind mending it? It would help with clarity for me during this change of editor.

Thanks for your work!

## To Reproduce
1. Create a post using Gutenberg.
2. Insert a reusable block.
3. Hover over the reusable block and observe the label in the top right corner.
4. Click on the reusable block.
5. Click on the "edit" button in the top right.
6. Hover over one of the blocks inside the reusable block and observe the label in the top right corner.

## Expected behavior
I was expecting the labels to both use "Reusable Block".

## Screenshots
![48733424-49643e80-ec08-11e8-9225-e840897d3cd6](https://user-images.githubusercontent.com/1328245/50237301-2309fe00-0382-11e9-8ff2-392cda9238ca.png)
![48733431-4bc69880-ec08-11e8-9932-58c56b5a535b](https://user-images.githubusercontent.com/1328245/50237315-28674880-0382-11e9-8df9-402308ee1f0d.png)

## Desktop
 - Gutenberg: v4.4.0
 - OS: macOS v10.13.5
 - Browser: Firefox
 - Version: 63.0.3

**Comment by designsimply** [comment]
I tried testing exactly with the steps you provided (maybe too exactly!) and I found that if I create a reusable block, open a new post, add the reusable block, it is still correctly labeled "Reusable Block." I noticed that in your screenshot you've inserted a group of blocks—looks like it's some headings and paragraphs and social media icons—which I think may actually be a template and so it may be labeled correctly. Can you walk me through how to create the exact same reusable block (or group of blocks) that you have in your screenshot? Was that technically created as a template?

**Comment by holtjohnson** [comment]
Thanks for your quick reply and following what I asked. I followed my steps exactly as well and didn't see what I was getting at. I guess I assumed someone would figure out the finer details from the images. I wasn't expecting someone to follow them exactly, I must have assumed too much.

No templates are used or in effect. The exact steps are:

1. Create a post using Gutenberg.
2. Add two paragraph blocks and fill them both with "Hello World".
3. Select both paragraph blocks and add/create a reusable block out of the two selected blocks.
4. Hover over one of the blocks inside the reusable block and observe the label in the top right corner.

**Comment by holtjohnson** [comment]
Also I'm seeing the inaccurate label "Reusable Template" when I use the block navigation as well. I see it when I have selected a block within a reusable block and then click the "Block Navigation" button. In this image I've selected a Heading Block inside a reusable block and then clicked the "Block Navigation" button.
![screen shot 2018-11-28 at 10 56 34](https://user-images.githubusercontent.com/1328245/49168123-7695a880-f2fc-11e8-9b0d-5a7c1424cbfc.png)

**Comment by noisysocks** [comment]
There has been some changes to the interface here but a similar bug still exists.

Now, if you select multiple blocks,  turn them into a Reusable Block, edit that Reusable Block, and select one of the inner blocks, you'll see an empty label in the status bar navigator:

<img width="1167" alt="Screen Shot 2020-04-20 at 14 47 59" src="https://user-images.githubusercontent.com/612155/79715123-29154380-8316-11ea-8c58-f755241ed96a.png">

Instead of `Document → ` it should say `Document → Reusable Block → Paragraph`.
