### ISSUE TITLE
the_editor_content hook seems not to be there

### ISSUE THREAD

**Issue by kivig2** [WordPress/gutenberg#12081]
Hi, 
imagery gone in Gutenberg editor, still there in Classic. URLs are dynamic via "internal" (not for user) short-codes and it seems "the_editor_content" hook used for them isn't there for Gutenberg.
Something else should be used instead?
Thanks.

**Comment by designsimply** [comment]
@kivig2 can you tell me a bit more about your setup? Are you using the Gutenberg plugin with WP 4.9.8 or WordPress 5.0 beta or WordPress.com?

> imagery gone in Gutenberg editor, still there in Classic

Do you mean you cannot upload images?

> URLs are dynamic via "internal" (not for user) short-codes

Are you talking about the permalink shown above the title or maybe the one in the post settings sidebar (or both)?

> it seems "the_editor_content" hook used for them isn't there for Gutenberg

Can you help me with a good set of steps for testing this? (I can help test but am not a developer. I can follow instructions if you walk me through! If no, no worries and I can tag this issue for a technical review which we'll need to wait for.)

**Comment by kivig2** [comment]
WP 4.9.8 with Gutenberg plugin.
For domain/directory independence all the local URLs in both existing and new content are replaced with short-codes upon save and restored into currently appropriate URLs on load/view/edit.

For editor this is done via "the_editor_content" hook (and "content_save_pre" hook accordingly), which was working fine.
In Gutenberg editor those URLs (looking at "view page source") still contain short-codes instead of domain/path, suggesting "the_editor_content" hook isn't there for Gutenberg editor.

Perhaps there are some new hooks for Gutenberg or other plans regarding pre/post filtering? Or it might be a bug?

As for replicating:
`
function content_load ($content) {
	$content = str_replace('[home]', 'not-home', $content);
	return $content;
}
add_filter('the_editor_content','content_load',2);
`
This, as a part of any plugin, for classical editor replaces all instances of "[home]" before the post is shown to a user. It doesn't for Gutenberg.

**Comment by kivig2** [comment]
Tested with WP 5.0 - behaves exactly the same.
It seems there is no the_editor_content filter hook.

**Comment by PabloMoratinos** [comment]
Hi all, here i've the same problem with a plugin that uses this hook.
the_editor_content hook runs with the classic editor in WP 5.0.1 but not with the block editor

**Comment by danielbachhuber** [comment]
Oh. If you're just adding the value when a new post is created, you can use `default_content`:

```php
add_filter( 'default_content', function() {
	return 'My custom default content';
});
```
![image](https://user-images.githubusercontent.com/36432/50035708-909be000-ffb8-11e8-8d5a-9568974b8550.png)

See https://github.com/danielbachhuber/gutenberg-migration-guide#actions--filters

**Comment by danielbachhuber** [comment]
We'll still need to document how to perform the equivalent of `the_editor_content` though.

**Comment by PabloMoratinos** [comment]
Thank you very much @danielbachhuber

**Comment by kivig2** [comment]
Hi, unfortunately default_content doesn't help in my case:
`function guid_load ($content) {
	$hmo = get_option('siteurl');
	if(strrpos($content, $hmo)=== false)
	{
	$content = $hmo.$content;
	}
	return $content;
}
function content_save ($content) {
	$hmo = get_option('siteurl');
	$content = str_replace('href=\"'.$hmo, 'href=\"[home]', $content);
	$content = str_replace('src=\"'.$hmo, 'src=\"[home]', $content);
	return $content;
}
function content_load ($content) {
	$hmo = get_option('siteurl');
	$content = str_replace('[home]', $hmo, $content);
	return $content;
}
function handle_upload_filter ($file) {
	$hmo = get_option('siteurl');
	$file['url'] = str_replace($hmo, '', $file['url']);
	return $file;
}
function load_guid_complete ($guid) {
	$hmo = get_option('siteurl');
	if(strrpos($guid, $hmo)=== false)
	{
	$guid = $hmo.$guid;
	}
	return $guid;
}

add_filter('content_save_pre','content_save',99);
add_filter('the_editor_content','content_load',1);
add_filter('the_content_rss','content_load',1);
add_filter('the_content_feed','content_load',1);
add_filter('gettext','content_load',1);
add_filter('wp_get_attachment_url','guid_load',1);
add_filter('default_content','content_load',1);
`

**Comment by kivig2** [comment]
Ok, it seems I've found two solutions. The question is which one is more appropriate, if any:

A:
function act_the_post( $post_object ) {
$post_object->post_content = content_load($post_object->post_content);
}
add_action( 'the_post', 'act_the_post' );

B:
function rest_prepare_filter( $response, $post, $request )
{
	if( in_array( 'content', $response->data) )
		$response->data['content']['raw'] = content_load( $response->data['content']['raw'] );
	return $response;
}
add_filter( "rest_prepare_post", 'rest_prepare_filter' , 10, 3 );
add_filter( "rest_prepare_page", 'rest_prepare_filter' , 10, 3 );

**Comment by danielbachhuber** [comment]
@kivig2 I think option B is better, as it's a bit more precise. Option A will apply in many more areas, which could cause unexpected results.

**Comment by designsimply** [comment]
I am removing the `[Type] Help Request` and `Needs Technical Feedback` labels since a few code examples have been noted and adding the `[Type] Documentation` label because there is a request in the discussion earlier asking for better documentation on how to move from using `the_editor_content` and `content_save_pre` to filtering REST API requests and responses instead.
