### ISSUE TITLE
Custom Field Suite WYSIWYGが保存されない

### ISSUE THREAD

**Issue by TKMS-a** [WordPress/gutenberg#12086]
固定ページにCustom Field Suiteを使っていますが、

WYSIWYGに記入したテキスト、ショートコードが保存されません。
更新をクリックすると消えます。

UPDATE: translated with https://translate.google.com/

> I use Custom Field Suite for fixed pages,
> 
> Texts and short codes entered in WYSIWYG are not saved.
> Click Update to disappear.

**Comment by designsimply** [comment]
Thank you for reporting the conflict. I checked at WordPress.org and found that support for Custom Field Suite is not available there: https://wordpress.org/support/topic/support-not-available/

It's possible you may be able to ask for help at https://github.com/mgibbs189/custom-field-suite/issues and the best way to do that will be to include exact steps to reproduce the problem and also included notes about the versions of WordPress and Gutenberg you are testing with. If you would like to go over those things here, I would be happy to help test at that point.

**Comment by designsimply** [comment]
Closing but also repeating the offer to help report the issue to the plugin developer if some more detailed testing steps can be provided. Thank you!
