### ISSUE TITLE
【BUG】Update failed error for published articles (conflict with the WPJAM BASIC plugin)

### ISSUE THREAD

**Issue by a506488043** [WordPress/gutenberg#12087]
![image](https://user-images.githubusercontent.com/16434125/48748687-a3b9d980-ecb2-11e8-9e43-4627e1b160fd.png)

**Comment by designsimply** [comment]
Hello! The first thing you will want to check is to confirm that you have a working JSON API for your site. You can do this by adding `wp-json` to the end of your domain, e.g. https://example.org/wp-json/ and you should see a lot of text and no error. If the API is not working you will need to find out why and get it turned on.

If you have confirmed your API is working, the next thing you can check is whether you have a plugin or a web server configuration which is causing a conflict. If possible, please check the console panel in your web browser tools and either copy and paste the errors you find in a reply here or post a screenshot showing them.

Please confirm your WordPress and Gutenberg plugin versions for reference.

**Comment by a506488043** [comment]
Conflict with the WPJAM BASIC plugin

**Comment by jayhill90** [comment]
Seems that this can by marked as closed as @a506488043 found it was a conflict with one of their plugins.

**Comment by designsimply** [comment]
Thanks @jayhill90!
