### ISSUE TITLE
Blocks: Make it easier to create text blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1209]
Following #1195, and expanding on what we discussed here: https://github.com/WordPress/gutenberg/issues/1082#issuecomment-308725257, let's discuss how to make it easier to create text blocks.

Currently, if you are just writing, you are creating text blocks along the way just by pressing enter. But if you insert an image at the end of your blocks, suddenly you have to click Insert > Text, in order to continue typing. That's fiddly.

Should we give "text" blocks special treatment compared to other blocks in the inserter? Here's an idea for doing that. Here's a fresh post with a writing prompt:

![neutral](https://user-images.githubusercontent.com/1204802/27219686-e254e624-5282-11e7-927e-af6e13c140a2.png)

The writing prompt above looks like a text block, but it's more like a text block _placeholder_. Here's what happens when you hover:

![hover](https://user-images.githubusercontent.com/1204802/27220363-2d605d4a-5285-11e7-8d28-07cc4c92ced9.png)

The placeholder is essentially a glorified shortcut to inserting text at the bottom of the block list. 

**Note: the dotted outline is an additional experiment for these mockups to _always_ show a faint outline on blocks on hover, not just the left side.**

Like the bottommost inserter, this text block placeholder would always sit at the end of the block list, ready for you to create more text:

![with text](https://user-images.githubusercontent.com/1204802/27220576-eb5c0d62-5285-11e7-87f7-03ffe45d148b.png)

As it stands, the above concept is only slightly different from what is in master, in that it always has sits at the bottom. But theoretically we could augment it in the future, to for example provide a neat oembed, or shortcode, or even commandline interface (see #834 ). That is —  we could make it so it wasn't an _actual_ text block on click, until we actually detect what's being written.

Any thoughts?

**Comment by jasmussen** [comment]
CC: @youknowriad

**Comment by youknowriad** [comment]
Looks good to me, maybe we should change the text of this placeholder if the post is empty.

**Comment by jasmussen** [comment]
Yes that's good. I know John Maeda had some thoughts on maybe having multiple writing prompts. I'll chat with him and hear his ideas.
