### ISSUE TITLE
More options in classic block HTML mode obscures some content

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12112]
A bit of an edge case here, but if you have a classic block with content that fills the width of the block, and then switch to HTML mode, the 'more options' menu can obscure the content:

<img width="646" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48778635-ae359c80-eccd-11e8-9a8d-29acbff46591.png">

**To Reproduce**
1. Create classic block
2. Switch block to HTML mode
3. Type a long line (without spaces) that wraps
4. Note the 'more options' button overlaps the content

Mac & Chrome

**Comment by designsimply** [comment]
Tested and confirmed using Chrome 70.0.3538.77 and Firefox 63.0.1 on macOS 10.13.6 with the following sample content.

```
nospacesatallmakesthingshardtoreadbutitsokayandwewilljustkeepgoingbecauseitistimetotestallthethings
```

**Comment by ghost** [comment]
<img width="717" alt="Screenshot 2023-03-05 at 10 34 16 PM" src="https://user-images.githubusercontent.com/118618474/222987277-bfbd13c8-b61d-4777-9b21-f48d6a3b4cff.png">

I think this is no longer a problem. If it is, feel free to reopen this issue.
