### ISSUE TITLE
Latest Posts Widget Block throwing PHP warning

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#12119]
When the Latest Posts Widget Block is used, I am seeing a PHP warning in the editor for each instance of the block:

```Notice: Undefined index: categories in /srv/www/wordpress-develop/public_html/build/wp-content/plugins/gutenberg/packages/block-library/src/latest-posts/index.php on line 22```

This same error will also show on the frontend, if the Category of the block is set to "All".

**To Reproduce**
1. Create a post
2. Add the Latest Posts Widget Block
3. Set the category to "All"
4. See warning

**Expected behavior**
There shouldn't be any warnings

**Screenshots**
![latest-posts-block-undefined](https://user-images.githubusercontent.com/34601694/48784237-415fd980-ecb0-11e8-9dbf-aff7bfd28eed.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102

**Additional context**
- Most recent version of GB Master, with all commits as of writing this
- GB Nightly build `https://builds.danielbachhuber.com/gutenberg-nightly.zip`does not throw any warnings

**Comment by dd32** [comment]
Duplicated with WordPress 4.9.8 + Gutenberg 4.5.

4.9.8 has this as `$attributes`:
```
wp-content/plugins/gutenberg/packages/block-library/src/latest-posts/index.php:16:
array (size=6)
  'postsToShow' => int 5
  'displayPostDate' => boolean false
  'postLayout' => string 'list' (length=4)
  'columns' => int 3
  'order' => string 'desc' (length=4)
  'orderBy' => string 'date' (length=4)
```

Where as 5.0 `$attributes` has this:
```
wp-includes/blocks/latest-posts.php:16:
array (size=9)
  'categories' => null
  'className' => null
  'postsToShow' => int 5
  'displayPostDate' => boolean true
  'postLayout' => string 'list' (length=4)
  'columns' => int 3
  'align' => null
  'order' => string 'desc' (length=4)
  'orderBy' => string 'date' (length=4)
```
