### ISSUE TITLE
Tables block - BUG: Arrow keys not working as expected...

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#12114]
### Describe the bug
**In the Tables block:**
- DOWN arrow doesn't do anything (should move down a block)
- UP arrow doesn't move up (instead, it moves left, only every-other-time)
- LEFT arrow button only works in empty cells

Gutenberg 4.4

**Comment by designsimply** [comment]
I tested with Gutenberg `master` using Firefox 63.0.1 on macOS 10.13.6 and found slightly different behavior:

* Left or down key traverses table cells across rows and then to the previous row.
* Right or down arrow key traverses table cells across rows and then to the next row.
* Up and down arrow keys require two key presses for empty cells.

Video: [1m25s](https://cloudup.com/cQLGUaVaIZo)
<sup>Tested with WordPress 4.9.8 and Gutenberg 4.4 `5a8c012de` using Firefox 63.0.1 on macOS 10.13.6.</sup>

Noting: would be nice to have additional testers make a note in the comments of their browser version if they try from another browser.

**Comment by GlennMartin1** [comment]
Testing in Windows with Chrome 70.0.3538.102

**Revision to original post:**

**RIGHT:**
- after mouse clicking in an empty cell, RIGHT does nothing.
- except, works normally IF there is content in the cells, or IF you first navigate LEFT then RIGHT

**LEFT:**
- works normally

**DOWN:**
- doesn't do anything in an empty cell
- except, if there's content in the cell, then DOWN moves RIGHT

**UP:** 
- works normally in cells with content,
- except require two key presses for empty cells

**Comment by GlennMartin1** [comment]
This is clearly a bug (not enhancement) - and the BUG label should be applied.

**Comment by designsimply** [comment]
To try to help explain (this is my hunch), I bet it's considered an enhancement because it's not something that was explicitly added and then broke—I think it's that it wasn't expected to work at all before and so adding a way for it to work is an improvement not fixing something that exists that's broken. It really can be a fine line sometimes though!

**Comment by GlennMartin1** [comment]
As of Gutenberg 5.3, behavior is far better; this issue is no longer current.
