### ISSUE TITLE
I want a feature that block option is follow the letter.

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#12111]
um... i don't know how to say it in english. my bad skill... anyway i will show you.

![cap 2018-11-18 15-32-12-112](https://user-images.githubusercontent.com/44285360/48778030-866b2680-ed17-11e8-83a5-f85888b20d7b.png)
That block option is on the block.

![cap 2018-11-18 15-32-15-243](https://user-images.githubusercontent.com/44285360/48778032-866b2680-ed17-11e8-8f93-5dad55b76f5a.png)
I feel so uncomfortable when I use long long block. I should go up then use option then go down again and again... Please make this option.

![cap 2018-11-18 15-32-15-2434](https://user-images.githubusercontent.com/44285360/48778274-1610d500-ed18-11e8-897e-b0655b485e5b.png)
like this ^.^ when i drag some part, block option appear above that line.

**Comment by designsimply** [comment]
This option is available for you! Please go to the More menu at the top right and select "Unified Toolbar" and the toolbar will remain at the top.

![screen shot 2018-11-20 at 8 53 41 am](https://user-images.githubusercontent.com/1119271/48785407-e1facd00-eca1-11e8-8164-65aa12d57839.png)

**Comment by MYIG** [comment]
i don't want top... just on the text...
it is good option too i think. no?

**Comment by chrisvanpatten** [comment]
@MYIG We had looked at that as an idea but found it was a little more confusing for users who are more familiar with WordPress. It might be something we can try again during Phase 2 :)

**Comment by MYIG** [comment]
um.. I didn't use medium yet. but I think it is goodㅎㅎ
anyway if you think about it once, then I feel betterㅎㅎ I hope it someday. not default, just one of optionㅎㅎ

**Comment by designsimply** [comment]
Thanks @chrisvanpatten! Here is a screenshot from Notion for reference.

![screen shot 2018-11-20 at 9 42 35 am](https://user-images.githubusercontent.com/1119271/48789005-3c4b5c00-eca9-11e8-8ecc-65d72956c6c6.png)

**Comment by myig123** [comment]
Wowww that is what i want correctly.
You are so clever!

**Comment by designsimply** [comment]
Thanks to Chris for pointing me in the right direction! 

Note: this may be something the designers and developers recommend making as a third-party plugin or if it's something they would like to re-consider for Phase 2, and we can wait for their reply to see about that. 🙂

**Comment by karmatosed** [comment]
I think for now this would be a plugin, but that doesn't mean a plugin can't become proposed as a core solution if enough people use it.
