### ISSUE TITLE
Documentation: Document usage of `core` entities (`getEntityRecords`, etc)

### ISSUE THREAD

**Issue by Novalis80** [WordPress/gutenberg#12120]
I read the docs for "getEntityRecords" and i have no clue what that is nor what is available:
```
state: State tree
kind: Entity kind
name: Entity name
key: Record’s key 
```
So if anybody can shed some light on the issue i would be grateful.

My specific task is to get all posts of a certain category into a custom block. I guess this is the method that will get the job done?!

**Comment by designsimply** [comment]
I'm moving this out of `[Type] Help Request` and making it into `[Type] Documentation`.

@Novalis80 I found an article with several examples that use `getEntityRecords` and I don't see one that specifically mentions categories but does this comment asking about tags which might help:

https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/#comment-1077

**Comment by buhlahkay** [comment]
Would love some more documentation on [Entities](https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core/) in general.

**Comment by aduth** [comment]
> My specific task is to get all posts of a certain category into a custom block. I guess this is the method that will get the job done?!

Responding to this specific request, you can achieve this by the following:

```js
wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { categories: [ /* ... */ ] } )
```

...where the first two arguments correspond to retrieving entities of a particular post type ([source](https://github.com/WordPress/gutenberg/blob/48e06dedd24b43f81760f1dc88354c80169701e6/packages/core-data/src/entities.js#L15-L17)) and the last is an object of query arguments to include in the request.

I agree there should be better documentation here.

**Comment by aduth** [comment]
#15200 is a first pass here, which will include formatted documentation in the `@wordpress/core-data` README. This will simply be adapted directly from the JSDoc of the actions and selectors. As noted there, a next step will be to include useful [`@example` tags](http://usejsdoc.org/tags-example.html).

**Comment by towfiqi** [comment]
@aduth This only works in the editor page. I am building a custom plugin with React that doesnt invlove gutenberg. I am trying to fetch latest posts , but in my Custom Plugin admin page, when I console log `wp.data.select( 'core' )`, I get undefined, which works fine in editor pages. 

Is this restricted to only on editor pages? How do I use it for another custom page? Do I have to use the rest api?

**Comment by aduth** [comment]
@towfiqi If you rely on data from a particular module, you must ensure that your script defines that module as a dependency, using the `$deps` argument of [`wp_register_script`](https://developer.wordpress.org/reference/functions/wp_register_script/) or [`wp_enqueue_script`](https://developer.wordpress.org/reference/functions/wp_enqueue_script/).

In your case, `core` is the `core-data` module, so your enqueue should look similar to:

```php
wp_enqueue_script( 'my-script', 'my-src.js', array( 'wp-core-data' ) );
```

[All packages](https://github.com/WordPress/gutenberg/tree/master/packages) are registered in WordPress with the `wp-` prefix. Most other data stores just use the same name as their package. `'core'` is the one exception here (as `'core-data'`).

**Comment by towfiqi** [comment]
I was trying ` array( 'wp-core' ) ` before. Now it works!! Thanks :)

**Comment by makkabi** [comment]
The documentation and event the source code says that getEntityRecords accepts four arguments, the first beeing a 'State Tree' object. But every example I see just uses three arguments, like this:
`wp.data.select("core").getEntityRecords('postType', 'post', { per_page: -1 })`
What am I missing? How can this even work, when the first argument is supposed to be an object?

**Comment by Lovor01** [comment]
> 
> 
> The documentation and event the source code says that getEntityRecords accepts four arguments, the first beeing a 'State Tree' object. But every example I see just uses three arguments, like this:
> `wp.data.select("core").getEntityRecords('postType', 'post', { per_page: -1 })`
> What am I missing? How can this even work, when the first argument is supposed to be an object?

I am late for an answer, but as I understood from reading, useSelect or withSelect inject first argument, i.e. state

**Comment by skorasaurus** [comment]
For anyone else still trying to figure this out and what are some basic questions (what is an entity? what are entityrecords? ) https://github.com/WordPress/gutenberg/pull/37615 answers some of these questions; Here is the [The most recent published version ](https://github.com/WordPress/gutenberg/blob/bd06705979ad63ace26d15de47144c253c3b0fc8/docs/getting-started/data.md).

**Comment by DaisyOlsen** [comment]
It looks like this documentation does exist
