### ISSUE TITLE
Use filter on parsed result of blocks in place of regular expression

### ISSUE THREAD

**Issue by antpb** [WordPress/gutenberg#12134]
In https://github.com/WordPress/gutenberg/pull/11973 there was talk of needing a way to parse the results of a block instead of using regular expression. 

@aduth mentioned: https://github.com/WordPress/gutenberg/pull/11973#discussion_r235037412

> Since this doesn't exist as an option today anyways (requires filter on this value), we probably can't do anything of this sort right now.

@dmsnell mentioned https://github.com/WordPress/gutenberg/pull/11973#discussion_r235106159

> if we hook into the block-level filter (the design of which I favor in #10108) then we can track the parse through the blocks and then prime the cache on the do_blocks filter which occurs after parsing and rendering is complete.

> that is, we could imagine something like this…

```
function _gutenberg_cache_images_meta( $html, $block ) {
	if ( $block['blockName'] === 'core/image' ) {
		$this->add_image( $block['attrs']['id'] );
	}

	return $html;
}
add_filter( 'rendered_block', '_gutenberg_cache_images_meta', 3 );

function _gutenberg_prime_cache() {
	if ( empty( $this->images ) ) {
		return;
	}

	// whatever command does all images in one go
	_prime_post_caches( $this->images, false, true, true, true, false, false );
}
add_filter( 'do_blocks', '_gutenberg_prime_cache' );
```

> and this because we know that the final do_blocks filter runs after block-level processing.

As work is completing in https://github.com/WordPress/gutenberg/pull/11973, I am creating this issue to kick off discussion around adding a filter to parse block content.

**Comment by paaljoachim** [comment]
Hey Anthony

Is this issue still relevant?

**Comment by jordesign** [comment]
As there's been no reply or movement on this in 2 and a bit years - I'm going to close it. Feel free to re-open if needed,
