### ISSUE TITLE
Gutenberg is not good with korean... irritating bug.

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#12138]
it is hard to explain because it is about Korean. My bad English skill... but it makes me angry many times too.

for example, 강 is made of ㄱ, ㅏ, ㅇ. so when I press backspace, it deleted 강 -> 가 -> ㅏ -> blank until I use spacebar.

![48777359-b9141f80-ed15-11e8-8e8c-10de23cfd0e5](https://user-images.githubusercontent.com/44285360/48808540-8ba29280-ed64-11e8-814a-37b6e258e1a8.png)
when it is like that,
![48777369-bf0a0080-ed15-11e8-85c9-a84993cb8452](https://user-images.githubusercontent.com/44285360/48808541-8c3b2900-ed64-11e8-85c2-cbf9acf7cfc7.png)
it is no problem to use it. but...

![48777522-1b6d2000-ed16-11e8-8221-184bb5c3ec9d](https://user-images.githubusercontent.com/44285360/48808543-8c3b2900-ed64-11e8-97e8-b5f4c33aecb8.png)
when letter is like that,

![48777548-2b84ff80-ed16-11e8-9404-627efa71fa77](https://user-images.githubusercontent.com/44285360/48808544-8c3b2900-ed64-11e8-97cc-298d049046bc.png)
it becomes like that... hmm...

![48777838-05139400-ed17-11e8-8c3c-da6ceeb2c575](https://user-images.githubusercontent.com/44285360/48808545-8c3b2900-ed64-11e8-9756-3e9d12174829.gif)
가나다라마바사 -> 가나다라마바 -> 가나다라마 -> 가나다라 .... it is normal but
가나다라마바사 -> 가나다라마바ㅅ -> 가나다라마ㅅ ->가나다라ㅅ it becomes that... please fix it. very very irritating to use it...

**Comment by designsimply** [comment]
Thank you for filing a separate issue for this! I asked in our #core-i18n Slack channel for testing help to see if someone can have a look who is more familiar with Korean. In the mean time, may I please ask what version of the Gutenberg plugin you are currently using and if you haven't already updated to 4.5.1 if you could make that update and try testing again?

**Comment by designsimply** [comment]
Yay! I will look at #11956 now.
