### ISSUE TITLE
Testing: Create automated tests for image sizes

### ISSUE THREAD

**Issue by antpb** [WordPress/gutenberg#12136]
As mentioned by @aduth in https://github.com/WordPress/gutenberg/pull/11973#issuecomment-440422544 we need automated tests for image sizes. 

Creating this issue as work completes there so we do not lose track of the need for tests.

I believe https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/adding-inline-tokens.test.js is a good starting point and has a similar flow. It should be used as an example when working on new tests related to Image block.

**Comment by Suriteka** [comment]
Hi everyone ! 👋

I've added a pull-request to test image size as you can see #15207 
This is my first pull-request, made during the WordCamp Paris

If there is something wrong in my code, just tell me and I'll fix it ❤️ !

Thanks a lot to @youknowriad for helping me introduce and help the community !

**Comment by paaljoachim** [comment]
I see a merged PR for this issue, and will go ahead and close it. Please reopen if I am mistaken.
