### ISSUE TITLE
Translator Comments 

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#12139]
**Describe the bug**
While translating the latest strings from Gutenberg 4.5 I found that there's a case where the translator comment in the code isn't parsed properly so doesn't appear on translate.wordpress.org.

This may be related to #9464 but doesn't seem to be an exact match.

Code - https://plugins.trac.wordpress.org/browser/gutenberg/trunk/lib/client-assets.php#L1215
Translate Row - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6925481&filters%5Btranslation_id%5D=59162362

I feel the issue is probably the translator comment in the code has text in the comment string prior to 'Translators:' prefix. May just need the comment split into two with the 'Translators:' comment in it's own comment block.

**To Reproduce**
1. Go to translate.wordpress.org, specifically this example;
https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6925481&filters%5Btranslation_id%5D=59162362
2. Note there's no translator comment on the row
3. Open the reference;
https://plugins.trac.wordpress.org/browser/gutenberg/trunk/lib/client-assets.php#L1215
4. Note there's a translator comment in the code.

**Expected behavior**
The translators comment should appear in translate.wordpress.org similar to the other one for Noto Serif font;
![screen shot 2018-11-20 at 3 33 33 pm](https://user-images.githubusercontent.com/8726005/48809491-b1cf2080-ecd9-11e8-93da-f946971ff02e.png)

**Screenshots**
Here's the translator row which is missing the comment;
![screen shot 2018-11-20 at 3 34 21 pm](https://user-images.githubusercontent.com/8726005/48809528-cdd2c200-ecd9-11e8-916d-8471ca6fadf6.png)

Here's the code which shows the comment;
![screen shot 2018-11-20 at 3 34 31 pm](https://user-images.githubusercontent.com/8726005/48809537-d62afd00-ecd9-11e8-8f66-18b21fd1e95f.png)

**Additional context**
Gutenberg Version - 4.5

**Comment by swissspidy** [comment]
> May just need the comment split into two with the 'Translators:' comment in it's own comment block.

Yep that‘s it. Translator comments need to be in a standalone comment.
