### ISSUE TITLE
Nagging "Post reverted to draft" bug

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#12147]
**Describe the bug**
Notification "Post reverted to draft" is displayed constantly whilst editing a post.

![xivrrxum5x](https://user-images.githubusercontent.com/2296425/48816502-878f6880-ed96-11e8-84dd-e3c5df9cf32f.gif)
Video with play controls: http://recordit.co/XiVrRXUM5x

**Additional context**
- Gutenberg plugin version 4.5.0

**Comment by pento** [comment]
Thanks @elliotcondon, I can reproduce this bug by enabling the ACF plugin, and adding a field group with a text field in it.

**Comment by noisysocks** [comment]
It looks like this is a regression introduced by https://github.com/WordPress/gutenberg/pull/12097.

**Comment by noisysocks** [comment]
I ran a `git bisect` and it looks like this is a regression introduced by #11409.
