### ISSUE TITLE
Changing list type does not mark content as unsaved

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#12141]
When changing the type of list a block is (between unordered and numbered), it's not registered as a change unless you also add a new list item after the fact.

I made an unordered list, saved it, went to preview and wasn't happy with it, it made more sense to be numbered.
Returned to the editor, changed it to be a numbered list, but the update button remained grayed out, as "no changes" had happened yet.

Adding a new list item, and then removing it, triggered the "updates have happened" mechanic, and I was then able to save the changes.

- OS: Windows 10
- Browser: Chrome 70
- WordPress 5.0-beta5 / WordPress 4.9.8 & Gutenberg 4.5.0

**Comment by iseulde** [comment]
Duplicated of #12027.
