### ISSUE TITLE
Converting blocks between text and list has extra values and does not convert back to text correctly

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#1214]
Converting from text, to list, and back again, gives unexpected results.

![conversaion](https://user-images.githubusercontent.com/3314354/27234244-3e1b3374-52b4-11e7-82d3-3fd1be469a3d.gif)

I would expect a list of three items (one for each word), and convert back to each word on its own line.

Logging the values sent to the transform functions, I see this:

From text to list:

`["I", Object, "like", Object, "cake", "", ""]`

From the resulting list to the text:

`[Object, Object, Object, Object, Object, Object, Object]`

**Comment by youknowriad** [comment]
Probably introduced when we moved to single p text blocks
