### ISSUE TITLE
Cannot read property 'InspectorControls' of undefined

### ISSUE THREAD

**Issue by alpezed** [WordPress/gutenberg#12152]
Hi, Can you help me please to fix about this issues https://alpezed.tinytake.com/sf/MzA5ODg1OV85Mjg5ODM0, after updating the plugin to 4.5.0 i have encountered this issues in all of my gutenberg blocks.

**Comment by ravishakya** [comment]
I had the same error. 
When u enqueue your scripts you will need to add dependencies like this

```	
wp_enqueue_script(
		'megablocks_cgb-block-js',
		plugins_url( '/dist/blocks.build.js', dirname( __FILE__ ) ),
		array( 'wp-blocks', 'wp-i18n', 'wp-element' , 'wp-components' , 'wp-editor' ) // Dependencies
	);
````

In your case `"wp-editor"` will be needed.

**Comment by alpezed** [comment]
Hi @ravishakya Thank you so much it's working now.
