### ISSUE TITLE
JS error when editing block

### ISSUE THREAD

**Issue by mcook504** [WordPress/gutenberg#12165]
**Describe the bug**
This bug is specific to the paragraph block. When I add a new paragraph block, I am unable to select/edit another block. The paragraph block I just created is permanently selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version: 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
Below is the error report copied from WordPress:

Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (../wp-content/plugins/gutenberg/vendor/react-dom.60482cc7.js:49:15)
    at scheduleWork (../wp-content/plugins/gutenberg/vendor/react-dom.60482cc7.js:18530:5)
    at Object.enqueueForceUpdate (../wp-content/plugins/gutenberg/vendor/react-dom.60482cc7.js:12476:5)
    at t.Component.forceUpdate (../wp-content/plugins/gutenberg/vendor/react.226e7acf.js:478:16)
    at ../wp-content/plugins/gutenberg/build/components/index.js?ver=1542757131:19:107497
    at arrayEach (../wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:508:11)
    at forEach (../wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:9334:14)
    at t.value (../wp-content/plugins/gutenberg/build/components/index.js?ver=1542757131:19:107468)
    at t.value (../wp-content/plugins/gutenberg/build/components/index.js?ver=1542757131:19:106985)
    at t.value (../wp-content/plugins/gutenberg/build/components/index.js?ver=1542757131:19:108106)

**Console Error Info**
From console error log:

react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Connect(o)

componentWillUpdate: Please update the following components to use componentDidUpdate instead: t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: Connect(o)

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: Button, Button__BaseButton, Collapsible__Content, Collapsible__StyledContainer, Collapsible__StyledContainerTopLevel, Collapsible__StyledHeadingLevel, Collapsible__StyledIconsButton, ModeSwitcher__Switcher, ModeSwitcher__SwitcherButton, SectionTitle__StyledTitle, SectionTitle__StyledTitleContainer, SnippetPreviewSection__Section, SnippetPreview__BaseTitle, SnippetPreview__BaseUrl, SnippetPreview__BaseUrlOverflowContainer, SnippetPreview__DesktopDescription, SnippetPreview__MobileContainer, SnippetPreview__MobileDescription, SnippetPreview__MobilePartContainer, SnippetPreview__Separator, SnippetPreview__Title, SnippetPreview__TitleBounded, SnippetPreview__TitleUnboundedMobile, StyledSection__StyledSectionBase, SvgIcon__StyledSvg, edit__PinnedPluginIcon, t

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Button, Button__BaseButton, Collapsible__Content, Collapsible__StyledContainer, Collapsible__StyledContainerTopLevel, Collapsible__StyledHeadingLevel, Collapsible__StyledIconsButton, Connect(P), Connect(o), Connect(t), ModeSwitcher__Switcher, ModeSwitcher__SwitcherButton, SectionTitle__StyledTitle, SectionTitle__StyledTitleContainer, SnippetPreviewSection__Section, SnippetPreview__BaseTitle, SnippetPreview__BaseUrl, SnippetPreview__BaseUrlOverflowContainer, SnippetPreview__DesktopDescription, SnippetPreview__MobileContainer, SnippetPreview__MobileDescription, SnippetPreview__MobilePartContainer, SnippetPreview__Separator, SnippetPreview__Title, SnippetPreview__TitleBounded, SnippetPreview__TitleUnboundedMobile, StyledSection__StyledSectionBase, SvgIcon__StyledSvg, edit__PinnedPluginIcon, t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: Button, Button__BaseButton, Collapsible__Content, Collapsible__StyledContainer, Collapsible__StyledContainerTopLevel, Collapsible__StyledHeadingLevel, Collapsible__StyledIconsButton, Connect(P), Connect(o), Connect(t), ModeSwitcher__Switcher, ModeSwitcher__SwitcherButton, SectionTitle__StyledTitle, SectionTitle__StyledTitleContainer, SnippetPreviewSection__Section, SnippetPreview__BaseTitle, SnippetPreview__BaseUrl, SnippetPreview__BaseUrlOverflowContainer, SnippetPreview__DesktopDescription, SnippetPreview__MobileContainer, SnippetPreview__MobileDescription, SnippetPreview__MobilePartContainer, SnippetPreview__Separator, SnippetPreview__Title, SnippetPreview__TitleBounded, SnippetPreview__TitleUnboundedMobile, StyledSection__StyledSectionBase, SvgIcon__StyledSvg, edit__PinnedPluginIcon, n, t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillMount: Please update the following components to use componentDidMount instead: SnippetPreview, SvgIcon__StyledSvg

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: SnippetPreview, SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500
react-dom.60482cc7.js:500 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

Please update the following components: SnippetPreview, SvgIcon__StyledSvg

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ react-dom.60482cc7.js:500

**Comment by youknowriad** [comment]
This is an incompatibility with the Yoast plugin and it's fixed in #12161 Thanks
