### ISSUE TITLE
Inconsitency to core: theme support feature 'editor-styles' <-> 'editor-style'

### ISSUE THREAD

**Issue by j-hoffmann** [WordPress/gutenberg#12169]
**Describe the bug**
When Gutenberg is collecting the styles to be loaded into the editor, theme support for the feature `editor-styles` determines whether styles from the global variable `$editor_styles` are loaded in `lib/client-assets.php`:

    if ( $editor_styles && current_theme_supports( 'editor-styles' ) ) ...

When using the core function `add_editor_style()` to add stylesheets to the `$editor_styles` global, the function sets theme support for the feature `editor-style` (note, this time without "s" at the end):

    function add_editor_style( $stylesheet = 'editor-style.css' ) {
	add_theme_support( 'editor-style' );
    [...]
    }

The problem is, stylesheets added via `add_editor_style()` will not get loaded in Gutenberg unless separately setting support for `editor-styles` (with "s" at the end):

    add_theme_support( 'editor-styles' );

**To Reproduce**
1. Include a stylesheet via  `add_editor_style()`
2. It will be loaded in classic editor but not in Gutenberg
3. Apply `add_theme_support( 'editor-styles' );`
4. Now the stylesheet also applies to Gutenberg

**Expected behavior**
`add_editor_style()` should be enough to apply the stylesheet in both editors, so Gutenberg should be checking `current_theme_supports( 'editor-style' )`.

**Desktop**
 - OS: Windows 10
 - Browser Firefox 63

**Additional context**
 - WordPress 4.9.8
 - Gutenberg 4.5.1

**Comment by mkaz** [comment]
From @joyously in Slack

> I'm not sure when this change crept into the Gutenberg doc (Theme section), but it is incorrect. This part https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#editor-styles acknowledges that the new way is a little different, and has `add_theme_support('editor-styles');`. Then this part https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#enqueuing-the-editor-style incorrectly associates the new loading and parsing with the old `add_editor_style( 'style-editor.css' );`. The old one uses `add_theme_support('editor-style');`. Note that the old one is still available for the old editor and it is singular. The new one for the new editor is plural.

Comments added to commit here: https://github.com/WordPress/gutenberg/commit/e4fd51cb535e8300b415973d7022b16c742c0d40#diff-c14ad3a4c41ef0d7bf709f5ebe52ba64

**Comment by mkaz** [comment]
Closed in: https://github.com/WordPress/gutenberg/pull/14917
