### ISSUE TITLE
Fail to Edit Image In Classic Editor Block

### ISSUE THREAD

**Issue by turtlepod** [WordPress/gutenberg#12160]
**Describe the bug**
Cannot edit image size in classic editor block

**To Reproduce**
1. Crete Classic Editor Block
2. Add Image
3. Edit and change the size
4. No change in image

**Expected behavior**
Image will update to new selected size.

**Why this is important**
Because when gutenberg active all **previous** content will be added in classic editor. Classic editor need to work flawlessly.

**Screenshots**
https://drive.google.com/file/d/1AKG4lm8Otq6uBGJhPgeIbF1QvyAUMARU/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: win10pro
 - Browser chrome 70
- Gutenberg 4.5.0
- WP 4.9.8

cc @mtias 
previous closed issue https://github.com/WordPress/gutenberg/issues/11433

**Comment by designsimply** [comment]
Thanks @turtlepod! I think you're right that #11433 should remain open and so I re-tested, confirmed, re-opened and left a comment there. I think it may have been closed by mistake.
