### ISSUE TITLE
Publishing: pre-publish toolbar is visible underneath Publishing options panel

### ISSUE THREAD

**Issue by keoshi** [WordPress/gutenberg#12175]
**Describe the bug**
When clicking “Publish…” I can still see the “Preview” button underneath the panel that slides in.

This particular scenario appears to be happening because the Yoast button bumps the entire top row to the left, but given enough plugins/integrations with the Gutenberg editor, that bar would grow unwieldily, and I could see something like this happening:

<img width="581" alt="screenshot 2018-11-21 at 12 36 11" src="https://user-images.githubusercontent.com/390760/48843401-d89b5e80-ed8e-11e8-9b5a-996c0d973e85.png">

**To Reproduce**
1. Install Yoast and Jetpack.
2. Configure social sharing in Jetpack.
3. Go to the Editor and hit “Publish...”.
4. See bug.

**Expected behavior**
That the pre-publishing tool bar under the panel that slides in is not visible at all.

**Screenshots**

![jp-testing-publish](https://user-images.githubusercontent.com/390760/48843406-dd601280-ed8e-11e8-8431-b00bc76453a2.gif)

**Desktop (please complete the following information):**
 - MacOS 10.14 (18A391)
 - Chrome 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version 4.5.1

**Comment by paaljoachim** [comment]
I believe this issue can now be closed.
