### ISSUE TITLE
IE 11: tabbing through the Blocks UI requires to tab twice through the whole UI

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12181]
Tested on latest master 4.5.1. Windows 10, Internet Explorer 11.

It's a bit difficult to describe so I've made a GIF (700 KB, sorry). I'm using a testing tool to highlight with a red outline the elements that receive focus.

Basically, when tabbing through the Blocks UI, something wrong happens and users are forced to go through the whole UI twice. The latest data I can point to (October 2017) show that the majority of screen reader users (24.7%) still use JAWS with Internet Explorer (see https://webaim.org/projects/screenreadersurvey7/#browsercombos) so this problem is of great importance for accessibility. I'd say that having to tab twice through each block is less than ideal for all keyboard users.

GIF:

![ie11 tabbing twice](https://user-images.githubusercontent.com/1682452/48851899-7cdfce00-edac-11e8-9fdb-b3785f2562a5.gif)

At a first glance, the first time focus goes to the block content, the actual focused element is the content _wrapper_. The second time, it's the editable field.

**Comment by afercia** [comment]
Note: I don't remember this happening with previous versions so it appears to be a regression. Can't point to a specific version that introduced this behavior so I haven't labelled this issue as "regression".

**Comment by jasmussen** [comment]
It's worth noting that the issue that causes this is identical to the issue that causes https://github.com/WordPress/gutenberg/issues/12113 (and the root is https://github.com/WordPress/gutenberg/pull/10723). Not to say this is necessarily a duplicate, just that the fix will close both tickets.

**Comment by afercia** [comment]
Thanks @jasmussen (had the same impression but wasn't sure)

**Comment by afercia** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/12206
