### ISSUE TITLE
IE 11: the "Enter – create a new paragraph – just write" flow doesn't work

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12180]
Testing in latest master 4.5.1
Windows 10, IE 11

- create a new post
- enter a title
- press Enter
- focus is apparently moved to the default empty block:

![screenshot 147](https://user-images.githubusercontent.com/1682452/48850752-96334b00-eda9-11e8-8cf7-abb354026ac4.png)

- notice there's no visible caret
- try to type something: nothing happens
- expected: caret to be in the editable field and typing to work

Now, there's the need to press the Tab key to actually move focus to the editable area:

![screenshot 148](https://user-images.githubusercontent.com/1682452/48850811-b6fba080-eda9-11e8-9a54-1860c57fbef3.png)

- notice the focused element is now the actual editable field 
- the caret appears initially misplaced below the editable field (tried both in Twenty Nineteen and Twenty Seventeen)
- start typing: characters are entered in the field as expected

This happens with all the following added blocks, making the writing experience with the keyboard less than ideal.

**Comment by swissspidy** [comment]
Duplicate of https://github.com/WordPress/gutenberg/issues/12113?

**Comment by afercia** [comment]
Yeo, seems so. Closing and adding the details there. Thanks.
