### ISSUE TITLE
InnerBlocks throwing TypeError on 4.5.1

### ISSUE THREAD

**Issue by lkhedlund** [WordPress/gutenberg#12184]
**Describe the bug**
After updating to **4.5.1**, all of our blocks using `InspectorControls` and `InnerBlocks` are broken. I didn't see any deprecation warnings or mentions of these being moved in either the ["What's New" post ](https://make.wordpress.org/core/2018/11/20/whats-new-in-gutenberg-20th-november/) or the Changelog.
```
Uncaught TypeError: Cannot read property 'InnerBlocks' of undefined
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at blocks.build.js?ver=1:1
    at blocks.build.js?ver=1:1
blocks.build.js?ver=1:1 Uncaught TypeError: Cannot read property 'InspectorControls' of undefined
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at Object.<anonymous> (blocks.build.js?ver=1:1)
    at t (blocks.build.js?ver=1:1)
    at blocks.build.js?ver=1:1
    at blocks.build.js?ver=1:1
```

The error seems to be targeting the `wp.editor` imports: `...t,p=wp.editor.InspectorControls,...`, which have been fine up until now. Here are my imports, which is the default for how **Create Guten Blocks** (@ahmadawais) imports everything:
```javscript
const { __ } = wp.i18n; // Import __() from wp.i18n
const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks
const { RichText, InnerBlocks } = wp.editor;
```
I don't think this is a CGB error, though, because it was fine until 4.5.1. A timely fix would be much appreciated, as _ALL_ of our client sites are broken.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102 (Official Build)

**Comment by youknowriad** [comment]
See https://github.com/WordPress/gutenberg/issues/12173#issuecomment-440708158 Thanks
