### ISSUE TITLE
Broken Github-link when trying to edit Documentation

### ISSUE THREAD

**Issue by crilleengvall** [WordPress/gutenberg#12197]
**Describe the bug**
Hi!
I'm trying to learn how to develop blocks with Gutenberg. I'm using the Developer handbook: 
https://wordpress.org/gutenberg/handbook/readme/. I sometimes come across stuff I can update the documentation with that I think would help others in the same position as me. 

The handbook seems to be able to give us that opportunity since there is a Link to the github repo with the title "Edit".  However when following that link i got a 404.

**To Reproduce**
1. Go to https://wordpress.org/gutenberg/handbook/blocks/introducing-attributes-and-editable-fields/
2. Click on 'Edit' just below 'Introducing attributes and Editable fields'
3. I get redirected to the 404 page of github.

**Expected behavior**
I would like to be able to edit the page and send a pull request.

**Screenshots**
![screenshot 2018-11-21 at 20 17 17](https://user-images.githubusercontent.com/623720/48863921-58dfb500-edcb-11e8-8f11-61c8da669687.png)

**Comment by pdaalder** [comment]
Is this still happening on your end? I've tried to reproduce this behaviour but everything seems to work for me.

**Comment by crilleengvall** [comment]
@pdaalder it's working now!
