### ISSUE TITLE
One reusable block fails validation, none show up anymore

### ISSUE THREAD

**Issue by ThomasBerends** [WordPress/gutenberg#12204]
**Describe the bug**
If any of your reusable blocks fails validation, none of them will be displayed. We’ve had one block fail validation, and therefore no blocks showed up anymore.

**To Reproduce**
1. Create multiple reusable blocks, including at least one custom one
2. Change one of the custom blocks so it fails validation
3. Try to add a reusable block on another page/post. None of them show up (except for reusable blocks on the same page/post)

**Expected behavior**
Only the block that failed validation should be hidden in the list of reusable blocks.

**Desktop (please complete the following information):**
 - OS: Windows/OSX
 - Browser: Chrome (likely others too)
 - Version: Latest

**Additional context**
Gutenberg plugin version 4.5.1

**Comment by youknowriad** [comment]
I don't reproduce this anymore.
