### ISSUE TITLE
Image caption too long for block after resizing the image

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#12203]
**Describe the bug**
I am use image blog and after write caption so see issue

**To Reproduce**

1. First add image
2. Click on Insert from URL
3. Write a caption

**Screenshots**

![imagecaption](https://user-images.githubusercontent.com/45058029/48883319-41451280-ee45-11e8-9d08-2fd8c502d109.gif)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 69.0.3497.81

**Additional context**

- Gutenberg: latest from master
- WordPress: 5.0 beta 3

**Comment by swissspidy** [comment]
Related: #12210

**Comment by skorasaurus** [comment]
Thanks for reporting. 

I'm not able to reproduce this bug using the newest version of Gutenberg 9.6rc1 (I've checked this in chrome and firefox). 
A video example is below; the first image was uploaded locally; the 2nd was inserted by an URL
https://f002.backblazeb2.com/file/cpl-public/tech-devel/2020-12-17-gutenberg.ogv
Please reopen this issue if this is still affecting you.
