### ISSUE TITLE
Unable to save changes to posts ,Firefox browser is used

### ISSUE THREAD

**Issue by anmol257** [WordPress/gutenberg#12208]

**Comment by designsimply** [comment]
Sorry to hear about the trouble! An "Updating failed" error can be caused by something local to your web server blocking your site's API or it can be caused by an incompatible server configuration or a plugin conflict.

First, check to make sure your site's API is working properly. You can do that by adding `wp-json` to the end of your site URL—if you get back an error, you will need to investigate why the API is not working for your site. Otherwise, you should just see a whole lot of text.

Next, check the console panel in your browser's web development tools at the time you see the "Updating failed" error appear. Sometimes an error will appear there that can help pinpoint the problem. If you spot an error, copy it into a reply here or take a screenshot and drop it into a reply.

**Comment by anmol257** [comment]
![image](https://user-images.githubusercontent.com/45257813/48976926-275e3680-f0b6-11e8-86b4-c293a750a688.png)
Screeenshoot after adding wp-json

**Comment by anmol257** [comment]
Web Console -

_

> JQMIGRATE: Migrate is installed, version 1.4.1 _static:9:542
> Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data. rest-proxy:6:4259
> Unhandled promise rejection undefined
> _static:788:29718
> Unhandled promise rejection undefined _static:788:29718
> Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data. rest-proxy:6:4259
> Unhandled promise rejection undefined

_

**Comment by dcleek** [comment]
I have a similar issue. Neither Auto-Save or Publish work. I get "Updating failed" and "Publishing failed." I also cannot preview Gutenberg created posts/pages. I get the logo animation, but nothing loads.

Adding wp-json works correctly. Here are the console messages when on the page:

Unhandled promise rejection Error: "[object Response]"
	r http://myhousechurch.org/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1544023174:1:3322
	r http://myhousechurch.org/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1544023174:1:3280
	j http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:2:29352
	j http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:2:29220
	f http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:1:20743
 wp-polyfill.min.2ae96136.js:2:29718

Unhandled promise rejection Error: "[object Object]"
	r http://myhousechurch.org/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1544023174:1:3322
	r http://myhousechurch.org/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1544023174:1:3280
	j http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:2:29352
	j http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:2:29220
	f http://myhousechurch.org/wp-content/plugins/gutenberg/vendor/wp-polyfill.min.2ae96136.js:1:20743
 wp-polyfill.min.2ae96136.js:2:29718

Source map error: request failed with status 404
Resource URL: https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js
Source Map URL: tcc_l.combined.1.0.6.min.js.map[Learn More] 

When I hit Publish, I get a duplicate "[object Object]" message.

Thank you for any help you can provide!

**Comment by dcleek** [comment]
Update: adding wp-json to the end of the URL works, but when I add a trailing slash, I receive a 500 error.

**Comment by anmol257** [comment]
its solved.Thanks

**Comment by designsimply** [comment]
@anmol257 how did you solve this?

**Comment by anmol257** [comment]
It got solved automatically.

**Comment by eduardoarandah** [comment]
Go to: /wp-json

If giving error, go to permalinks and click save
wp-admin/options-permalink.php

Test /wp-json again
