### ISSUE TITLE
Provide instructions for building / installing.

### ISSUE THREAD

**Issue by collinanderson** [WordPress/gutenberg#1220]
I symlinked the github repo to my plugins directory but I'm getting a bunch of 404's for the components/build directory. I don't use the php command-line stuff much so it would be nice to have instructions for how to install it. I assume there's some sort of build command that needs to be run but have no idea what it is.

Also, it would be great to have some sort of message rather than just a big blank screen if someone does what I just did.
![image](https://user-images.githubusercontent.com/129234/27248496-45b42582-52d2-11e7-9307-cf8ba04f45d3.png)

**Comment by collinanderson** [comment]
I see now it's under "contributing", even though I just want to try it out at this point.

**Comment by BE-Webdesign** [comment]
Hi @collinanderson!

> I see now it's under "contributing", even though I just want to try it out at this point.

I am glad you want to try it out. It is a pretty neat project. Below is a link to the package put out on the WordPress.org plugin repository. This already has all of the necessary bundling steps done for you. So if you are looking for a fast way to get Gutenberg up and running, check out the link below:

https://wordpress.org/plugins/gutenberg/

If you want to contribute towards the development of Gutenberg, you will need to follow the steps in the CONTRIBUTING.md, to make sure that the version you are testing against matches the most recent changes in this git repo. The repository docs should probably be updated to point at the plugin repository.

**Comment by aduth** [comment]
Closing as resolved by...

- Encouraging [plugin](https://wordpress.org/plugins/gutenberg/) for basic user testing
- Following [CONTRIBUTING.md](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md) for development environment setup

**Comment by collinanderson** [comment]
Thanks!
