### ISSUE TITLE
Hide WordPress logo animation for preview

### ISSUE THREAD

**Issue by ducfather** [WordPress/gutenberg#12216]
Since the update to 4.1.0 #11022 there is now a WordPress logo animation appearing after hitting the preview button. 

Is there any way to hide/change/remove this animation?
Maybe you could provide a filter to alter the animation.

I tried to access the CSS properties from within my own plugin, but to no avail.

**Comment by greatislander** [comment]
It may also be worth considering a reduced-motion alternative to respond to https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by noisysocks** [comment]
I've written a proposal for a filter which would let one customise this UI in https://github.com/WordPress/gutenberg/issues/12238.

**Comment by ducfather** [comment]
Thanks a lot!
But is there a way to work around this before the filter is released?
I can't access the .editor-post-preview-button__interstitial-message class from any css-file and !important is also not working.
