### ISSUE TITLE
Is there a way to get a list of all available blocks from outside the post editor?

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#12219]
I am trying to get a list of the blocks available, both core and plugin blocks, from outside the Gutenberg editor. I thought there would be some kind of Rest route to retrieve this information. But it seems, from what I could search through the repository, that core blocks are registered directly from a list in the block-library package and then plugin ones are registered by their own script using the registerBlockType hook. So this information is not saved on the database.

Is there any way to get this list using the Rest API or maybe through PHP?

Thanks.

**Comment by swissspidy** [comment]
You can use `$block_types = WP_Block_Type_Registry::get_instance()->get_all_registered();` to get all blocks that have been registered via PHP.

It's obviously not possible on the server side to get information about registered blocks on the client side.

**Comment by alvaro0555** [comment]
Thanks for the quick response. The returned list is for blocks which render server side data, as latest posts, etc. So there is no way to get this information from outside the post editor of each post type. I was thinking that somehow triggering the registerBlockType hook for each post type, could give such a list, but Im not sure if this could even be possible nor where to start. I will have to rethink the design.

Thanks again.

**Comment by swissspidy** [comment]
Closing for now. Feel free to re-open if you have any follow-up questions related to that.

**Comment by markhowellsmead** [comment]
For extra clarification of @swissspidy's comment: many non-dynamic blocks (e.g. `core-embed/youtube`) are only registered in JavaScript and therefore can, apparently, not be accessed in PHP using `WP_Block_Type_Registry::get_instance()->get_all_registered();`. To deregister these, you need to use `wp.blocks.unregisterBlockType` in JavaScript.

**Comment by boospot** [comment]
To fetch the list of all registered blocks in the JS, we can do something like this:
`wp.blocks.getBlockTypes()`

you may try this in browser console.

Also, to get a list of blocks for a particular namespace, you may use something like this:

`wp.blocks.getBlockTypes().filter((block) => { return block.name.indexOf('core') !== -1});`
(This will list all blocks with namespace 'core'

**Comment by markhowellsmead** [comment]
@boospot That only works in the post editor. The issue asks how to get the list of blocks from _outside_ the post editor.

**Comment by boospot** [comment]
> @boospot That only works in the post editor. The issue asks how to get the list of blocks from _outside_ the post editor.

You are right.
My mistake. i did not understand question properly.
should i delete the comment?

**Comment by markhowellsmead** [comment]
No, I don't think that's necessary :)
