### ISSUE TITLE
Paginated content

### ISSUE THREAD

**Issue by Rahe** [WordPress/gutenberg#12218]
**Describe the bug**
When I have a dynamic bloc with a render_callback function and a paginated content (<--nextpage-->) the dynamic block are not rendered.

**To Reproduce**
1. Go in admin
2. Add an content
3. Add content :
```html
<!-- wp:heading -->
<h2>Test</h2>
<!-- /wp:heading -->

<!-- wp:nextpage -->
<!--nextpage-->
<!-- /wp:nextpage -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>TEST</p><cite>ETSTTSTT</cite></blockquote>
<!-- /wp:quote -->

<!-- wp:latest-posts /-->
```
4. Go to front office, load the page 2

**Expected behavior**
I expect that the dynamic block is rendered on page 2, but this is not the case.

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser Chrome
 - Version 70.0.3538.77

**Additional context**
- Version 4.5.1, but appears since 4.4.0 works fine in 4.3.0

**Comment by youknowriad** [comment]
I suspect this being a parsing issue where the parsed string passed to `do_blocks` or something is starting with `<!-- /wp:nextpage -->` causing the issue.

cc @dmsnell @pento 

Maybe we should just trim `<!-- wp:nextpage -->` and  `<!-- /wp:nextpage -->` from the strings?

**Comment by dmsnell** [comment]
If you plug in the example content into the [parser explorer](https://dmsnell.github.io/peg-parser-explorer/) (you can load the spec grammar by clicking on "fetch") then you will see that it does what it's supposed to do and parse the document into a list of blocks.

@rahe can you share more code? which block type had a registered render callback? what actually rendered? what did you expect to render? without seeing the HTML you are talking about it's hard for me to understand exactly what you are seeing.

my guess is that w have some different code path for following pages in multi-page documents that skips the block processing altogether. @aduth I'm not sure who to ping but I think we only run content through `do_blocks` on the first page of a multi-page document.

check out the rendered HTML for page two of my test document…
<img width="362" alt="screen shot 2018-11-22 at 8 47 34 am" src="https://user-images.githubusercontent.com/5431237/48912603-4dc06f80-ee33-11e8-99ec-1d43903207f8.png">

I'm not sure where even to begin, but I can try and look into this. seems like a critical priority. cc: @mtias

**Comment by dmsnell** [comment]
**Update**

It seems like my assessment was wrong about not processing the successive pages. Instead, what's happening is that we're sending an invalid document to `do_blocks()` and that fails in the default parser in a different way than the spec parser.

Once WordPress strips out `<!--nexpage-->` it passes a document to `do_blocks()` that starts with `<!-- /wp:nextpage -->` which is invalid. The default parser fails and [closes out the rest](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/block-serialization-default-parser/parser.php#L312) of the document.

I'll try and make at least one attempt at a quick-and-minimal fix from inside `do_blocks()`, but we know that the real fix is to update the default parser so that it's actually a PEG and conforms to the same failure modes as the spec parser.

**Comment by mcsf** [comment]
> Once WordPress strips out `<!--nexpage-->` it passes a document to `do_blocks()` that starts with `<!-- /wp:nextpage -->` which is invalid. The default parser fails and [closes out the rest](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/block-serialization-default-parser/parser.php#L312) of the document.

Was starting to look at this and getting at the same conclusion. Looking forward for a quick patch. <3

**Comment by azaozz** [comment]
> Once WordPress strips out  it passes a document to do_blocks() that starts with  which is invalid. The default parser fails and closes out the rest of the document.

Heh, got there too few min ago... Parallel work :)

A very crude fix is 
```
	
	if ( strpos( $content, '<!-- /wp:nextpage -->' ) === 0 ) {
		$content = preg_replace( '@^<!-- /wp:nextpage -->\s*@', '', $content );
	}

	if ( strpos( $content, '<!-- wp:nextpage -->' ) === strlen( $content  ) - 20 ) {
		$content = preg_replace( '@\s*<!-- wp:nextpage -->$@', '', $content );
	}
```

in `do_blocks()` before `$blocks = parse_blocks( $content );`

**Comment by mtias** [comment]
Cross-referencing ticket in core: https://core.trac.wordpress.org/ticket/45401

**Comment by youknowriad** [comment]
I'm closing as this has been fixed upstream
