### ISSUE TITLE
Caption text is very long for gallery blog, so scroll issue  see this

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#12210]
**Describe the bug**
First add gallery blog and caption write blog, caption text is very long so see isssue.

**To Reproduce**

1. Click on gallery blog
2. Write caption....
3. See error

**Screenshots**
![scrollissue](https://user-images.githubusercontent.com/45058029/48895557-5df44100-ee6b-11e8-9e04-715960976c87.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 69.0.3497.81

**Additional context**

- Gutenberg: latest from master
- WordPress: 5.0 beta 3

**Comment by utsavtilava** [comment]
**Above issue will fixed if we add wordbreak breakall from below css code.**

.entry .entry-content .wp-block-audio figcaption, .entry .entry-content .wp-block-video figcaption, .entry .entry-content .wp-block-image figcaption, .entry .entry-content .wp-block-gallery .blocks-gallery-image figcaption, .entry .entry-content .wp-block-gallery .blocks-gallery-item figcaption {
font-size: 0.71111em;
 font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0.5rem;
    text-align: center;
    **word-break: break-all;**
}

**Comment by karmatosed** [comment]
I think this might be fixed now.

![image](https://user-images.githubusercontent.com/253067/61488897-468d3980-a9a1-11e9-8a5a-685ee36aa464.png)

If you are on the latest version of Gutenberg still getting this problem please report back and I will reopen.
