### ISSUE TITLE
Media & Text Block Defaults to Large text

### ISSUE THREAD

**Issue by benhuson** [WordPress/gutenberg#12229]
When creating a new Media & Text block instance, the text size for the first text area defaults to "Large".

Is there any particular why this should default to large rather than "Normal" size text which is what I was expecting?

When using a this block I would likely want to write normal size text, or perhaps insert a proper Heading followed by 'normal' paragraph text.

Defaulting to large paragraph text seems an odd choice or very opinionated about how you may want to use this block?

**Comment by bph** [comment]
It does seems to be a deliberate choice of the developer. 
Here is the video http://recordit.co/YlMJmfTz3c

I agree with @benhuson - it's an odd choice, and I would also prefer a 'normal' size text

Not difference between Chrome or Firefox. 
use OS X 10.13.6

**Comment by jorgefilipecosta** [comment]
Hi @benhuson, @bph, @christophhapple, this was a deliberate choice to respect the proposed design for the block. I am adding the needs design feedback so feedback on this issue could be provided.

**Comment by richtabor** [comment]
Hey team, we chatted about this in today's Gutenberg triage meeting and came to the conclusion that the current Media & Text block edit flow is acceptable, as is.

Rationale:
1. Provides a starting point that sets itself apart from a simple columns/group block
2. Provides a mechanisms for adding a "heading" (without an actual `H`, as we cannot provide a proper heading level that accounts for all other headings on the page).
