### ISSUE TITLE
Button preview is offscreen on a large button

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12224]
When changing the style on a large button the preview doesn't take into account the screen size.

Here is a big button:

<img width="598" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48905343-38f6d280-ee59-11e8-967a-31bd49b692af.png">

Clicking the button style button (top left corner of the toolbar) and then hovering over a style results in this:

<img width="755" alt="edit_post_ _wordpress_latest_ _wordpress_and_gutenberg_ _master__origin_master__8595_commits_" src="https://user-images.githubusercontent.com/1277682/48905396-62aff980-ee59-11e8-9c3a-f32d978d6811.png">

You can see that the preview area is offscreen.

**To Reproduce**
1. Create a button
2. Enter a substantial amount of text into the button
3. Click button style in the block toolbar
4. Hover over a style and note the preview is offscreen

**Expected behavior**
Preview to be onscreen!

**Comment by youknowriad** [comment]
closed by #12205
