### ISSUE TITLE
wp.i18n.esc_html__() version? XSS?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12220]
Is `wp.i18n.esc_html__()` version planned?
How to achieve this?
Is this necessary or some escaping is already happening?

**Comment by swissspidy** [comment]
This is not really needed in a React / JavaScript context as all the strings would be escaped anyway (unless you use something `dangerouslySetInnerHTML`)

**Comment by manake** [comment]
Nice.

1. What does it mean "unless you use something `dangerouslySetInnerHTML`"?
2. Does it mean that in JavaScript context writing `__('Some string with <a href="https://example.com/">a link</a> in it,', 'text-domain');` would not create a link? Ok, that makes sense. Perhaps `wp.i18n.sprintf` should be used to create text with links then (I didn't try this yet).

**Comment by swissspidy** [comment]
> Does it mean that in JavaScript context writing `__('Some string with <a href="https://example.com/">a link</a> in it', 'text-domain');` would not create a link? 

Correct. `sprintf` won't help you there. You'd need to use `dangerouslySetInnerHTML` to directly write HTML. Otherwise `<` and `>` get escaped.

See also #9846 for a discussion about this.
