### ISSUE TITLE
Add filter for customising the WordPress logo animation for preview

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#12238]
In https://github.com/WordPress/gutenberg/pull/10896, we added an animated WordPress logo to indicate that the post preview was loading.

<img width="569" alt="screen shot 2018-11-23 at 08 45 12" src="https://user-images.githubusercontent.com/612155/48922866-ad834d00-eefd-11e8-9a30-137a1be73793.png">

There's [been](https://github.com/WordPress/gutenberg/pull/10896#issuecomment-436125262) [repeated](https://github.com/WordPress/gutenberg/pull/10896#issuecomment-440783452) [requests](https://github.com/WordPress/gutenberg/issues/12216) for the ability to customise this logo using e.g. a filter.

Such a filter could wrap around the [`.editor-post-preview-button__interstitial-message` component](https://github.com/WordPress/gutenberg/blob/017f31bd092001be5e8f2afe282d8b34883d8cbd/packages/editor/src/components/post-preview-button/index.js#L18-L24), allowing developers to completely swap out the _Generating preview…_ UI:

```js
wp.hooks.addFilter( 'editor.interstitialMessage', function() {
    return wp.element.createElement( 'div', { className: 'my-custom-message' },
        wp.element.createElement( 'p', null, 'Post preview is being generated! 💃' )
    );
} );
```

**Comment by vs999** [comment]
Where should I put this code?
I tried in the functions.php of my theme but it broke my site.
thanks
