### ISSUE TITLE
Props: How do we best give credit to contributors?

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1223]
There have been a great deal of contributors to this project, not only those who have committed valuable code, but even folks who gave valuable input in discussions on tickets, or provided mockups. Some mockups might not even have been used, but they will still have informed the directions later taken.

What's the best way to ensure these contributors are rewarded with props? Do we create a new "CONTRIBUTORS.md" document listing out these? Is there a more manual way we can do it?

**Comment by nb** [comment]
Here is an interesting approach: https://github.com/kentcdodds/all-contributors

**Comment by ntwb** [comment]
Yay, Gutenberg is now in the plugin repo 🎉 

What did stand out to me though was only having two listed contributors in the `readme.txt`

A bit more sleuthing and I see that [5 contributors were removed](https://plugins.trac.wordpress.org/changeset/1680320) from the `readme.txt`, though I don't think the `readme.txt` file is in this repo here on GitHub

I also couldn't find any discussion here on GitHub or in #core-editor on Slack on why they were removed, @mtias as you made the commit linked above can you shed any light on the decision to remove those contributors from the readme please?

**Comment by jasmussen** [comment]
Thanks @ntwb. Some of the discussion was in-person at WCEU, and it was a crazy few days. Sorry for the lack of context.

The gist is that many, _many_, have contributed to this plugin, including yourself. And you all deserve credit. People who user tested, provided feedback, mockups, all deserve credit. But the "Plugin Authors" isn't really a scalable field to provide this. We looked at creating a new .org user, "Team Gutenberg", to assign this as the user, so that we could provide props in the README or here on GitHub (as discussed in this ticket), but as it came together we were looking at only tiny window of time before the plugin was presented on stage, so we decided to postpone this. 

But it is a priority for us to ensure that everyone get the credit they deserve, and _not only_ those who committed code.

**Comment by jasmussen** [comment]
Alternately, we _do_ use the plugin authors field. But we want to make sure that everyone participating in for example [this discussion](https://github.com/WordPress/gutenberg/issues/650) show up there. I feel like that might get unwieldy quick...

**Comment by aaronjorbin** [comment]
A `contributing.md` file makes the most sense to me.  I think it would also be valuable to start collecting the wordpress.org usernames of the contributors so that they are given props on any commits to core that take place due to this project and can appear on the WordPress credits screen.

**Comment by jasmussen** [comment]
I've bookmarked a bunch of things and discussions from the past 6 months, so I have a lot of notes on who deserve props that haven't committed code. If anyone has the energy to get this started, I'd love to commit to the branch these extra contributors.

It begs one question, though —  should we list a reason why a person shows up on the contributors list? Especially if they haven't committed code? I'm leaning towards no, just from an egalitarian point of view, but thought it worth asking.

**Comment by ntwb** [comment]
From the handbook: https://make.wordpress.org/core/handbook/best-practices/commit-messages/#props
> _"Props should be given to all those who contributed to the final commit, whether through patches, refreshed patches, code suggested otherwise, design, writing, user testing, or other significant investments of time and effort."_

There's a few more guidelines/tips via the link above that are worth a read.

There's no need to give a reason why someone gets props 💐

**Comment by karmatosed** [comment]
>  I have a lot of notes on who deserve props that haven't committed code.

This makes me so happy! Its really important we don't just give code committed props. We have had such awesome contributions for design and usability testing.

**Comment by jasmussen** [comment]
Took a first stab in https://github.com/WordPress/gutenberg/pull/1330
