### ISSUE TITLE
Gallery Block Missing Back and Forward Arrows

### ISSUE THREAD

**Issue by roadrunner13** [WordPress/gutenberg#12230]
Hi, I just started using Jetpack and the carousel image gallery option, I also use Woocommerce and the Storefront theme. The gallery shows up fine, I click any image and the slideshow shows up, but there are no back and forward arrows. I deactivated Gutenberg and the arrows appeared. Thank you!

Aldo

**Comment by nosolosw** [comment]
cc @simison for Jetpack visibility.

**Comment by simison** [comment]
@jeherve this has already been fixed, right?

@nosolosw this is a Jetpack issue and can be closed in Gutenberg repo.

@roadrunner13 thanks for the report!
