### ISSUE TITLE
First load of previously classic page in Gutenberg fails to convert to blocks

### ISSUE THREAD

**Issue by justdave** [WordPress/gutenberg#12237]
**Describe the bug**
When updating pages on a site that's been around for a while after installing Gutenberg, the first load of any given page fails to convert to blocks, states that it's invalid and gives me the option to convert to HTML.  If I convert to HTML and then immediately ask it to convert to blocks, it works just fine.

**To Reproduce**
1. Edit a page that's never been edited in Gutenberg yet
2. Observe warning that it failed to convert with option to Leave as HTML
3. Click Leave as HTML
4. Click the three-dots menu and choose Convert to Blocks
5. Observe that page converted just fine.

**Expected behavior**
Since "Convert to blocks" from the menu works, it ought to just do it on the first try instead of telling me the block type is invalid.

**Screenshots**
At Step 2 from above:
<img width="660" alt="screen shot 2018-11-22 at 4 14 03 pm" src="https://user-images.githubusercontent.com/307334/48922171-d6aacb80-ee72-11e8-8952-8ff658b63cea.png">

After Step 3 from above:
<img width="664" alt="screen shot 2018-11-22 at 4 14 10 pm" src="https://user-images.githubusercontent.com/307334/48922173-d90d2580-ee72-11e8-9078-62677d2fab63.png">

At Step 5 from above:
<img width="673" alt="screen shot 2018-11-22 at 4 14 20 pm" src="https://user-images.githubusercontent.com/307334/48922175-dc081600-ee72-11e8-8028-4401380644a6.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X Mojave 10.14.1
 - Browser: Firefox Developer Edition 64.0b11 (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**
- Please add the version of Gutenberg you are using in the description.
  Gutenberg version: 4.5.1

**Comment by jorgefilipecosta** [comment]
Hi @justdave thank you for reporting this issue! I'm not able to reproduce it would it be possible to retest it in the last version of Gutenberg, and provide a list of the plugins you are using (or at least the ones that may impact this)? It would also be beneficial if you could give a sample of post_content where this problem happens. Thank you in advance for the help!
