### ISSUE TITLE
Problem with admin_notice

### ISSUE THREAD

**Issue by NicolasKulka** [WordPress/gutenberg#12243]
**Describe the bug**
The admin_notices in the admin goes over the editor

**To Reproduce**
Edit pages

Screenshot
![problem_admin_notice](https://user-images.githubusercontent.com/8568332/48939540-dcf18400-ef14-11e8-98a2-35eed1e1cb2d.png)

**Comment by nickcernis** [comment]
This is particularly noticeable for notices that aren't dismissible: 

<img width="1415" alt="edit_post_ _wp_beta_ _wordpress" src="https://user-images.githubusercontent.com/647669/48868716-eb3b8500-edda-11e8-9f2a-8d6a4c6e3d55.png">

**Comment by nerrad** [comment]
related https://github.com/WordPress/gutenberg/pull/11604

**Comment by noisysocks** [comment]
Is it possible to make all notices dismissible?

Otherwise, I think we'll need some design direction here. Perhaps the notices could appear in an invisible scrollable container?

**Comment by nerrad** [comment]
> Is it possible to make all notices dismissible?

There's some discussion around this in the pull I linked to (#11604).  In particular, this comment: https://github.com/WordPress/gutenberg/pull/11604#issuecomment-439495990

**Comment by noisysocks** [comment]
Thanks for the pointer @nerrad!

I'll look into implementing what @aduth describes in https://github.com/WordPress/gutenberg/pull/11604#issuecomment-439495990.

I'm unsure if it's too great of a change to be making while we're in the RC phase of 5.0, though. How do we feel about putting `overflow: scroll; max-height: 25%` on `.components-notice-list` as an interim fix?

![overflow](https://user-images.githubusercontent.com/612155/48993625-fef83a00-f192-11e8-9667-8d184af4ee84.gif)

cc. @jasmussen

**Comment by noisysocks** [comment]
I guess it doesn't really solve anything e.g. one can't click on the title field 🙂 — will keep looking into making non-dismissible notices push down the editor.

**Comment by aduth** [comment]
A continuation of the design explorations can be found at the addressing pull request #12301

**Comment by kriskarkoski** [comment]
Confirmed this on my test site running Gutenberg 4.5.1 while testing a user report
