### ISSUE TITLE
HTML block with classic toolbar

### ISSUE THREAD

**Issue by knutsp** [WordPress/gutenberg#12244]
**Is your feature request related to a problem? Please describe.**
When coming from WordPress 4.9.8 til 5.0, previously using the text (not visual) editor, now using the HTML block as replacement, the toolbar with formatting buttons  a are gone. This is a regression for those users.

See https://core.trac.wordpress.org/ticket/45375#comment:25

**Describe the solution you'd like**
Add all the toolbar buttons from the classic editor, text tab, to the HTML block.
Allow registering new buttons as before.

**Describe alternatives you've considered**
1. Install and activate Classic Editor plugin. As this is probably phased out in 2022, it doesn't represent a permanent solution.
2. Develop a new block, "HTML with classic toolbars". Ensuring users don't face regression is, however, a core responsibility.

**Comment by youknowriad** [comment]
Some context here https://github.com/WordPress/gutenberg/issues/9807#issuecomment-420576376

I think the second option you propose is better, whether it's going to be done in Core or in a plugin remains to be seen.
