### ISSUE TITLE
Does RichText's value type is string since 4.5.1?

### ISSUE THREAD

**Issue by AndreKelling** [WordPress/gutenberg#12253]
I created a custom block containing the RichText Component.
It's value was set to array type.

Since recently (4.5.1 update), there went up problems with creating new custom blocks.
Saving does not properly works anymore.
Content just disappeared.
In the documentation it's declared as string: https://wordpress.org/gutenberg/handbook/block-api/rich-text-api/ (since 4.5.1 **?**)

Old existing custom blocks still worked fine with an array inside the RichText component.
So when already having array inside and array is the value type then array is used.

### Code Example
This an extracted part of the block creation code, just with the RichText component. Compiled through babel with `babel-plugin-transform-react-jsx`

```
( function( wp ) {
	var registerBlockType = wp.blocks.registerBlockType;

	var el = wp.element.createElement;

	var __ = wp.i18n.__;

        const { RichText } = wp.editor;

	registerBlockType( 'ajk/toggle-card', {
        title: __( 'Toggle Card'),
        description: __( 'Block showing a toggle card.' ),
        keywords: [__( 'toggle card' ) ],
        icon: {
            foreground: '#004784',
            src: 'nametag'
        },
        category: 'formatting',
        attributes: {
            textContent: {
                type: 'array',
            },
        },
        edit: ( props ) => {
            const {
                className,
                attributes: {
                    textContent,
                },
                setAttributes,
            } = props;

            const onChangeText = ( value ) => {
                setAttributes( { textContent: value } );
            };

            return (
                <div className={ className }>
                    <label>{ __( 'Text') }</label>
                     <RichText
                                tagName="div"
                                placeholder={ __( 'Write text content') }
                                value={ textContent }
                                onChange={ onChangeText }
                      />
                </div>
            );
        },
        save: ( props ) => {
            return null // See PHP side. This block is rendered on PHP.
        }
	} );
} )(
	window.wp
);
```
### Editor example
This is when i enter following and switch to code view in the editor: 
this is some text with **bold font**

 **new created blocks in editor code view**
`
`
_This does not save properly if the attribute textContent is set to array._

 **prior created blocks in editor code view**
`<!-- wp:ajk/toggle-card { "textContent":["this is some text with ",{"type":"strong","props":{"children":["bold font"]}} } /-->`
_This does not save properly if the attribute textContent is set to string._

### Fazit

I do need to transform all value types from array to string and can simplify my dynamic rendering process and remove my crafted [richtext renderer](https://gist.github.com/AndreKelling/ac4d8be7111d27aaf236460dc5b1800e). Array's are way better to work with than super long strings with markup inside. Had some time to re-copy-and-saving existing blocks with the new string type set...

**Comment by designsimply** [comment]
(Asking just in case) are you able to provide a code sample that shows a simple version of how you are creating your custom block?

**Comment by AndreKelling** [comment]
@designsimply sure, updated my post with examples.

**Comment by iseulde** [comment]
Also noting that this is the case since 3.9, not 4.5.1.

**Comment by AndreKelling** [comment]
@iseulde 
not really a problem.
just asked me why i went with array type...
thought it might be a kind of a breaking change.

thanks for clearing this out!
