### ISSUE TITLE
Dragging a reusable multi column block into itself, the block is messed up or removed.

### ISSUE THREAD

**Issue by Fujix1** [WordPress/gutenberg#12255]
When I drag a reusable block with a multi column block into itself, the block is messes up or removed.
This issue is similar to https://github.com/WordPress/gutenberg/issues/9303
but it's not for a reusable block.

**To Reproduce**
1. Insert a multi column block.
2. Put any blocks in each column.
3. Register the multi column block to a reusable block.
4. Drag the block into itself.

**Expected behavior**
When a multi column block is in a reusable block, it should be locked and not accept dragging.

**Screenshots**
![b234deccc35b30ced3f11fbf9f324666](https://user-images.githubusercontent.com/13434151/48956005-e7069780-ef93-11e8-93c0-ad24ec54b611.gif)

![8cf9e0a37c8dc836350351948807379f](https://user-images.githubusercontent.com/13434151/48956017-eff76900-ef93-11e8-805c-36fcafffec2a.gif)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.102, Firefox 63.0.3 

Gutenberg version 4.5.1 and the Test Gutenberg web site.

**Comment by talldan** [comment]
I gave this a test as there were some recent fixes to drag & drop in relation to columns. 

Unfortunately it still seems like an issue. 

What's unusual is that the user can't edit a reusable block normally without clicking the 'Edit' button, but can still modify it by dragging a block into the reusable block. That seems inconsistent.

**Comment by talldan** [comment]
Looks like I forgot to remove the `Needs Testing` label last time. I've just retested this and it still seems to be an issue:
![reusable-inception](https://user-images.githubusercontent.com/677833/70686987-c5846500-1ce8-11ea-898e-ca287750dae3.gif)

On some of the dropzones there didn't seem to be any effect though.

I think ideally the dropzones would be disabled unless the reusable block is being edited.

The second thing is that a user shouldn't be able to drop a block on itself, and I think in that case those dropzones within the block being dragged would ideally be disabled as targets.

**Comment by noisysocks** [comment]
> I think ideally the dropzones would be disabled unless the reusable block is being edited.
>
> The second thing is that a user shouldn't be able to drop a block on itself, and I think in that case those dropzones within the block being dragged would ideally be disabled as targets.

Agreed.
