### ISSUE TITLE
Make published changelogs more of a summary than literal changelog

### ISSUE THREAD

**Issue by jwflory** [WordPress/gutenberg#12257]
# Summary

Published changelogs in plugin page on WordPress.com are extremely detailed and difficult to understand if not a core developer; suggest taking a different approach to writing release changelogs

# Background

I usually take care to read the changelogs of plugins I use before I update them. This is one way I learn about new features in a plugin that I could take advantage of it, discover an annoying UX bug I found was resolved, or to be on top of changes in my environment.

The Gutenberg changelogs are extremely detailed, but read more like a line-by-line summary of what changed exactly since the previous update. Usually the list is long and I don't understand the meaning for most of the bullets. I don't always read them fully because they don't feel like they were written for someone like me to understand.

# Details

Better grouping of related items into categories would help (e.g. bug fixes, enhancements / features, etc.). Personally, I love how Yoast SEO [writes their changelogs](https://wordpress.org/plugins/wordpress-seo/#developers). They're always easy for me to understand and sometimes I discover new features to take advantage of because they are detailed in the changelog.

# Outcome

Easier for everyday site owners to understand changes without knowing jargon, better understanding / communication to users of what's changed and what changes will be noticed first by a user

**Comment by youknowriad** [comment]
Thanks for the suggestion, we started doing a more organized changelog https://wordpress.org/plugins/gutenberg/#developers

**Comment by jwflory** [comment]
@youknowriad Yay, thanks! I noticed this for the last couple of updates. The extra effort on the changelog is appreciated! :smile:
