### ISSUE TITLE
Width of captions in centered 1-col gallery with small images

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#12251]
**Describe the bug**
When adding a centered gallery with a single column and small images, the caption for the images extends to the full width of the post. However, I would expect the caption to only extend to the width of each image.

This is a follow up on #9531 and the corresponding solution in  #11040.

**To Reproduce**
1. Create a new post.
2. Add a new gallery with some small images.
3. Configure the gallery to be centered and display the images in a single column without cropping.
4. The gradient of the captions extends over the sides of each image (cf. Screenshot 1). However, as each image has a different width, this behavior is somewhat unexpected.

**Expected behavior**
I personally would expect the gradient of the caption to only extend over the width of the corresponding image (cf. Screenshot 2).

**Screenshots**
![example](https://user-images.githubusercontent.com/996503/48950566-e3dfbd00-ef3b-11e8-94ac-01f5344f4dd9.png)
Screenshot 1 (current - unexpected - behavior)

![example1](https://user-images.githubusercontent.com/996503/48950700-594b8d80-ef3c-11e8-87d8-14f0ca505816.png)
Screenshot 2 (expected behavior)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox 63.0.3 64 bit
 - Version: Gutenberg 4.5.1

**Comment by SeniorSpielbergo** [comment]
@designsimply If you need any further information on this, please just let me know.

**Comment by youknowriad** [comment]
In my testing, the images are scaled as well to take the same width, so this doesn't happen anymore. Maybe a theme issue or an issue that was already fixed.
