### ISSUE TITLE
Difficulty selecting columns block that is in use

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12267]
**Describe the bug**
I added two images to the columns block to avoid the grey gradient in the gallery.
It is easy to select the contents (image blocks) inside the column but it is very difficult to figure out where to click to select the parent column.

**To Reproduce**
1. Add two image blocks inside a column.
2. Figure out where to click to be able to select the column.

**Expected behavior**
Having a clear method on how to select the parent block. Something that can be used for all parent blocks. Either an icon to click or a larger area to click to select the parent block. Keeping a consistent method to select inner and outer blocks.

**Desktop (please complete the following information):**
 - Mac 10.13.6
 - Browser Chrome in Desktop Server
 - Gutenberg version: 4.5.1

**Comment by spencerfinnell** [comment]
The current accepted/expected behavior is to use the document block navigator in the toolbar. 

https://github.com/WordPress/gutenberg/issues/10851

Related: https://github.com/WordPress/gutenberg/issues/9628

**Comment by designsimply** [comment]
Closing as a duplicate in favor of #9628 which has a ton of discussion ongoing for this topic.
