### ISSUE TITLE
Clicking top area of Paragraph block allows multiple "+" to exist

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#12264]
**Describe the bug**
It's possible to click on a Paragraph block in the top 10 pixels or so, where it has focus but doesn't open up the toolbar. That shows 1 "+" button. Moving the mouse to hover over a new block will show a second one.

**To Reproduce**
1. Compose a new post
2. Create some paragraphs
3. Click the top few pixels of one of them
4. Hover over some other one

**Expected behavior**
The inline "+" button feels like the kind of UI element that is intended to only be visible at one place at any one time. Seeing multiple of them feels wrong, as if I broke the editor.

**Screenshots**
<img width="699" alt="screen shot 2018-11-23 at 11 38 56 pm" src="https://user-images.githubusercontent.com/88951/48964976-7eaabc80-ef79-11e8-9efb-3b41bdb029ef.png">

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: latest

**Additional context**
- WordPress 5.0 RC 1

**Comment by markjaquith** [comment]
I can reproduce this issue. I agree that it feels weird that the first "+" gets "stuck" on.

**Comment by jorgefilipecosta** [comment]
I was able to verify the issue in my tests too.

**Comment by youknowriad** [comment]
It seems like this is fixed. I was not able to reproduce with the last version.
