### ISSUE TITLE
Custom numeric CSS variables are always appended with px

### ISSUE THREAD

**Issue by kenzap** [WordPress/gutenberg#12263]
**Describe the bug**
There are certain cases when a CSS variable should be passed over inline HTML. For example, for custom hover colors or widths adjustments. In the example below we use **--testval** variable.
<img width="479" alt="screen shot 2018-11-24 at 12 10 47 pm" src="https://user-images.githubusercontent.com/7790165/48964812-2b208900-efe2-11e8-9558-c912957e1f5a.png">
Whenever the variable is passed and it does not contain characters like "#" or "px" the "px" is still appended automatically.
<img width="374" alt="screen shot 2018-11-24 at 12 22 19 pm" src="https://user-images.githubusercontent.com/7790165/48964867-a7679c00-efe3-11e8-9212-1e26f4328761.png">
This is convenient when we adjust width, paddings, margins but is not applicable when we use such CSS functions as **calc** where clean value is required. 

**To Reproduce**
1. Create any element with custom variable.
2. Pass any numeric variable and check inline HTML results.

**Expected behavior**
The expected behavior is not to have any px appended to custom variables

**Screenshots**
<img width="374" alt="screen shot 2018-11-24 at 12 22 19 pm" src="https://user-images.githubusercontent.com/7790165/48964867-a7679c00-efe3-11e8-9212-1e26f4328761.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
- Gutenberg version: 4.5.1

**Comment by youknowriad** [comment]
Hi @kenzap and sorry for the late response.

This seems like a React issue but there's a simple workaround here, you can use a string variable instead of number.  in your code, you can just write. `iconSize.toString()`
