### ISSUE TITLE
Changing the view to `Top Toolbar` messes up with a block's button state

### ISSUE THREAD

**Issue by acosmin** [WordPress/gutenberg#12274]
**Describe the bug**
Gutenberg v4.5.1 - Changing the view to `Top Toolbar` messes up with a block's button state.

**To Reproduce**
1. Create a paragraph (the same with any block)
2. Change text alignment
3. Select `Top Toolbar` in `View`
4. Now try and change the alignment and it will not change the button's state, it seems messed up. Check the screenshot.

**Expected behavior**
When you click on an alignment button, it should change said button's state and display the correct alignment.

**Screenshots**
![Iscreenshot](https://giant.gfycat.com/NecessaryQueasyAsianporcupine.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102

**Comment by designsimply** [comment]
Nice find. And what an odd bug!

Tested and confirmed that if an block with alignment options in the toolbar is active during the switch to Top Toolbar mode then the alignment buttons will not work properly (they're one step behind) until the block is unfocused then refocused again.

Video: [52s](https://cloudup.com/cvzr9MhNMbq)
<sup>Tested with both WordPress 4.9.8 and Gutenberg 4.5.1 and `master` @ `e4fd51cb5` using Firefox 63.0.3 on macOS 10.13.6. Checked both with a paragraph block and an image block.</sup>

**Comment by youknowriad** [comment]
I can't reproduce this anymore.
