### ISSUE TITLE
Increasing pixel size maintains ratio but other dimension doesn't increase.

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#12277]
**Describe the bug**
Increasing one dimension of an image increases both width and height proportionally. If the feature is going to be included in 5.0 (which I'd rather not, but I doubt that's changing), then the other dimension should update itself.

In reproducing this bug, one quickly runs into #12168 as well.

**To Reproduce**
1. Insert an image.
1. Select a image size (at the moment I _also_ had to set the image size to 100% for the pixel-sizing to work at all)
2. Increase its size via the width or height pixels settings
3. The image increases in size, but the other pixel dimension does not change.

**Expected behavior**
Width/height pixel settings remain proportional at all times.

**Screenshots**

When increasing width, the height does not proportionally increase. When increasing height afterwards, it doesn't impact the image.
![image-pixel-ratio-bug](https://user-images.githubusercontent.com/1238696/48973407-58c1fe00-eff3-11e8-9694-ffd1a65b3f28.gif)

**Desktop (please complete the following information):**
 Win 10, WP 5.0-RC1, Firefox 63.0.3, no plugins, Twenty Nineteen

**Comment by paaljoachim** [comment]
I checked out this issue with Twenty Twenty One. 
Image size: Medium
100%
Then began nudging the Width and Height pixels.
Caption moved as the image moved.

I will go ahead and close this issue. Please reopen if it is a mistake.
