### ISSUE TITLE
Undo – Redo: some embed types create an undo level

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12273]
Tested on latest master 4.5.1. Similar UI behavior as #12272 but I guess the root cause is different.

- open an existing post that contains a Twitter embed
- wait for the tweet content to render
- notice the Undo button in the top left is now active, indicating there's an undo step in the history:

![screenshot 2018-11-24 at 17 37 47](https://user-images.githubusercontent.com/1682452/48970760-781b5400-f010-11e8-8b1e-ca8ddd5fb43e.png)

- click Undo, then click Redo: of course nothing happens

Expected: the undo step to not be created.

Worth noting not all embed types seem to trigger this behavior. I've tried with the same Vimeo video used in the demo content and the extraneous undo step wasn't created.

Embeds used for testing:
```
https://twitter.com/nacin/status/319508408669708289
https://vimeo.com/22439234
```

**Comment by aduth** [comment]
Related: #8119

**Comment by paaljoachim** [comment]
I just tested with WordPress 5.7 beta 3.
Twenty Twenty One.

I am able to add a Tweet and undo two steps so it is removed. Then redo two steps to bring it back.
It works fine.

Closing this issue. If I am mistaken it can of course be reopened.
