### ISSUE TITLE
Undo – Redo: activating the main inserter creates an Undo level

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12271]
Tested on latest master 4.5.1 

- create a new post
- don't enter any content
- click the main inserter button in the top left: the inserter opens
- the Undo button is now active indicating there's an undo step in the history
- click the Undo button: of course, nothing happens

Expected: an Undo step to not be created

<img width="1014" alt="screenshot 2018-11-24 at 17 06 12" src="https://user-images.githubusercontent.com/1682452/48970459-98491400-f00c-11e8-99e4-17379bc47783.png">

**Comment by aduth** [comment]
I expect this could be resolved as a side-effect of #7119

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce this issue.


https://user-images.githubusercontent.com/240569/122398609-184c7600-cf8b-11eb-93be-42143acc6acc.mp4
