### ISSUE TITLE
Undo – Redo: existing reusable blocks create an undo level

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12272]
Tested on latest master 4.5.1 

- open an existing post that contains reusable blocks
- the reusable blocks take a few moments to fetch content and render, this is expected
- when they're fully rendered, the Undo button is active indicating there's an undo step in the history:

![screenshot 2018-11-24 at 17 08 39](https://user-images.githubusercontent.com/1682452/48970499-2a511c80-f00d-11e8-9448-238548b1ac73.png)

- click the Undo button
- the reusable blocks content disappears and a message "Block has been deleted or is unavailable" is shown:

![screenshot 2018-11-24 at 17 08 49](https://user-images.githubusercontent.com/1682452/48970528-6d12f480-f00d-11e8-88eb-2883b4c35630.png)

- click the Redo button: the reusable blocks content gets restored

Expected: the Undo step to not be created and the reusable blocks content to not disappear

**Comment by aduth** [comment]
Related: #8119
