### ISSUE TITLE
Plugin / Theme menus overlay text editor with Chromium

### ISSUE THREAD

**Issue by justcallmejoe** [WordPress/gutenberg#12270]
**Describe the bug**
Having a longer post when scrolling down some plugin / theme menus
overlay the editing area. The text is not visible, though editable, but
of course these menus are very disturbing ;)

With Firefox (v63.0) it works. I see this behaviour only with Chromium (v70.0).

The browser console shows no error messages.

**To Reproduce**
1. Open post
2. Scroll down half page

**Expected behavior**
I expect that these menus are attached to the bottom of the
page not overlaying the text editor.

**Screenshots**
I attached a screenshot showing the menu overlaying the text editor.

![wp-gutenberg-plugin-menu-bug](https://user-images.githubusercontent.com/45314540/48970055-bf511700-f007-11e8-919a-c47c0ba6d4b9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.4, 64 Bit
 - Browser: Chromium
 - Version:  70.0.3538.77

**Additional context**
- Gutenberg 4.5.1
- Theme: Customizr

**Comment by designsimply** [comment]
I tested just now using WordPress 4.9.8, Gutenberg 4.5.1, Yoast SEO 9.2.1, and the Customizr 4.1.22 theme with Chrome 70.0.3538.110 on macOS 10.13.6 and I was unable to see the problem with scrolling shown in your screenshot.

Testing note: would also be good for a tester to download and test with Chromium too.

Based on what I can see in your screenshot, it looks like there could be a conflict with one of your other plugins or it's possibly a browser issue (I tested with Chrome not Chromium on a first pass). Note: I also didn't install the Nimble Builder plugin recommended in an admin notice by the Customizr theme. It does look like you may have several more plugins installed. To narrow down the source of the problem, the recommended troubleshooting steps at this point would be to temporarily deactivate all plugins except Gutenberg and the ones that add the meta boxes below the content area and check to see if the problem still happens (you may need to clear local cache). If the problem goes away, turn on each plugin one by one and check the content area again until you see the problem reappear.

**Comment by designsimply** [comment]
I downloaded and installed Chromium 72.0.3623.0 on macOS 10.13.6 and also installed the Nimble Builder 1.3.0 plugin and tested again and still couldn't see the problem showing in your screenshot where the meta boxes added by some plugins overlap content at the bottom of a post in Gutenberg. I tested with WordPress 4.9.8 and Gutenberg 4.5.1.

Can you try the option to temporarily deactivate all plugins except Gutenberg and add each one back one at a time until you find the source of the problem?

**Comment by justcallmejoe** [comment]
Thanks for your quick response and help. I tracked it down to the plugin "Disable Comments". Once this is disabled, everything works as expected.

I use the plugin to disable comments completely on all post types. As well the plugin hides all comment-related fields from the edit page. I think that's where something goes wrong.

So most probably this is a "Disable Comments" issue and with Gutenberg everything is fine. I'll open an issue there. Feel free to close this one here if you think so.

**Comment by justcallmejoe** [comment]
Just opened the issue: https://github.com/solarissmoke/disable-comments/issues/55

**Comment by justcallmejoe** [comment]
From the referenced issue above I learned that this is a bug in Gutenberg, which was fixed in the current WordPress RC but isn't backported yet into the plugin. So I think we can close this issue here.
