### ISSUE TITLE
The first run through of using reusable blocks.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12286]
This is my first run on using reusable blocks.

The test case:
I have made a column with three images in it. I would like to use a similar column layout with three images on other pages as well.

Clicking the 3 dots to see what is hidden inside the drop down. I then find the Reusable blocks link and select it.
![screen shot 2018-11-25 at 11 39 11](https://user-images.githubusercontent.com/5323259/48978122-eca0d200-f0a6-11e8-859d-9a7043c4fb95.png)

Here I can give the reusable block a name. If I change my mind...where is the cancel button? 
What if I have already made it into a reusable block but had forgotten? It would be nice with a drop down showing my existing reusable blocks. So that I at the same time can also see if I have already earlier saved it there.
![screen shot 2018-11-25 at 11 39 38](https://user-images.githubusercontent.com/5323259/48978138-0e01be00-f0a7-11e8-8afd-0d053b083f10.png)

(I copied the column just to be sure that I did not ruin it by making it into a reusable block.)

Two notifications on the top take a bit much space..

![screen shot 2018-11-25 at 11 44 27](https://user-images.githubusercontent.com/5323259/48978171-a1d38a00-f0a7-11e8-8dd2-3e8d85ed1c94.png)

Here is the new reusable block. What about a link beside edit that I could click to get a list of my reusable blocks?
![screen shot 2018-11-25 at 11 46 22](https://user-images.githubusercontent.com/5323259/48978178-c62f6680-f0a7-11e8-99d2-21a7d5595a89.png)

I went to a new page to add the reusable block.

This looks really nice and clear! Easy to understand.
![screen shot 2018-11-25 at 11 49 14](https://user-images.githubusercontent.com/5323259/48978207-33db9280-f0a8-11e8-87ae-253f05742d5a.png)

-----

NB! 

I clicked edit to edit the new reusable block. Changed an image and clicked to save. It then updated the existing reusable block. Here a message should come up alerting the user that by changing this block all instances of using the same reusable block will also be changed. 

Additional thoughts... A clear message on what will happen on editing a reusable block.
Direct message for the user: Changing this reusable block will change this block on all pages and posts it has been used. Click yes to make the change. Click no to make the selected reusable block into a regular column block that will not affect any other pages or posts.

-----

On managing Reusable blocks. I noticed someone else also mention this in another issue.

![screen shot 2018-11-25 at 12 05 18](https://user-images.githubusercontent.com/5323259/48978338-903fb180-f0aa-11e8-9042-82f28e6bd3e5.png)

Here it wants to leave the page.

Another suggestion on this would be to select a reusable block and see the list of reusable blocks in the sidebar. One could also there manage the blocks.

**Comment by paaljoachim** [comment]
https://github.com/WordPress/gutenberg/issues/8403

**Comment by designsimply** [comment]
Thank you for the feedback. To summarize the reusable block UI suggestions:

1. Add a cancel option before saving.
1. Add a way to get to the list of reusable blocks directly from the reusable block UI.
1. Add a Reusable Block menu option in the left sidebar.
1. When saving, add an alert notifying the user they are changing all instances.

**Comment by paaljoachim** [comment]
Hey Sheri.

You got it!

5. (I will mention this anyway even though it should be covered by 2 and 3.) Do not exit the site to manage the Reusable blocks as these should be easy to access in the Reusable block settings in the sidebar and in a drop down (sidebar seems like the most natural option).

**Comment by youknowriad** [comment]
Do we have issues for each one of these items? I feel it's easier if tracked separately.

**Comment by paaljoachim** [comment]
I was just thinking about that today! Thanks for the reminder!

**Comment by paaljoachim** [comment]
Splitting up this issue into smaller issues:

Can't cancel creation of Resuable Block
https://github.com/WordPress/gutenberg/issues/12940#event-2122043608

Find a better place for the "Manage All Reusable Blocks" link
https://github.com/WordPress/gutenberg/issues/13390

Better warning message when removing a reusable block
https://github.com/WordPress/gutenberg/issues/13702

Alert message when editing a reusable block. 
https://github.com/WordPress/gutenberg/issues/13704

**Comment by youknowriad** [comment]
Thanks @paaljoachim That's great 👍
