### ISSUE TITLE
Adding a link brings up embed box - not able to easily add a link any longer

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12281]
**Describe the bug**
Adding just a standard link to another site etc with no text around it brings up the embed dialog box.

![adding-a-link-gutenberg](https://user-images.githubusercontent.com/5323259/48977050-f0c2f480-f092-11e8-8af1-53563071da21.gif)

It makes adding just a link not that easy any longer.

**To Reproduce**
1. Add a link to another page, site etc.
2. Notice the embed box shows up.

**Expected behavior**
That I can just paste inn a standard link and that it shows up like a regular link.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg version: 4.5.1 |

**Comment by swissspidy** [comment]
This should be fixed in Gutenberg 4.6, see https://github.com/WordPress/gutenberg/pull/12095.

**Comment by paaljoachim** [comment]
Glad to hear! I guess we can just close this issue then....
