### ISSUE TITLE
Is it possible to create a partially editable post where some blocks are read-only?

### ISSUE THREAD

**Issue by shuvyA** [WordPress/gutenberg#12280]
Hello.

Is it possible to create a post (or custom post) in which some blocks are read-only and some can be edited by an end-user (I'm not referring to editing via the management interface).
The editing will be in Gutenberg's interface.
Or is the correct way to do a partially editable post is only by adding custom fields to the post?
Thanks!

**Comment by designsimply** [comment]
To clarify, do you mean that you want to code a custom block that is read-only for all users on the site? May I ask for a specific use case where you would want to do that (because I am curious and also to document the help request a bit better)?

**Comment by jorgefilipecosta** [comment]
Hi @shuvyA,
If I got the things right, the objective is to have a post that starts with some blocks and some zones are editable by the user while other zones are not editable?
That is possible to achieve using InnerBlocks and locking https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks#templatelock.
You may create a block that contains an InnerBlocks area and set "templateLock" "all" on the area that should be read-only, on the writable area you may place the blocks directly on the template of CPT or set them inside an InnerBlocks area without locking. Another option even more straightforward way to achieve the same effect is to have the read-only block as a simple block without edit controls that prints the HTML of the area on the edit and save.
I hope this answers your question and I'm closing the issue for now. If you need any more information or you find a blocker during the implementation feel free to reopen the issue.
It would be nice if you could provide your specific use case as @designsimply requested so we can improve the documentation. Thank you in advance!
