### ISSUE TITLE
Drag inner blocks?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12285]
**Is your feature request related to a problem? Please describe.**
I added a column block. Then added a quote in the 2nd cell. I would like to drag the inner block quote over to the left cell.

![screen shot 2018-11-25 at 11 15 00](https://user-images.githubusercontent.com/5323259/48977903-e6f5bd00-f0a3-11e8-9992-4d143d00368f.png)

![screen shot 2018-11-25 at 11 15 18](https://user-images.githubusercontent.com/5323259/48977905-eb21da80-f0a3-11e8-95d1-3bbf77b655ad.png)

**Describe the solution you'd like**
I would like to be able to drag inner blocks to rearrange the layout of a column and other container like blocks.

**Describe alternatives you've considered**
Copy the quote to the other cell I want it in. It becomes cumbersome if a lot of content inside a container, column etc.

Gutenberg version: 4.5.1.
Chrome and Desktop Server.

**Comment by ktmn** [comment]
Seems to be `core/columns` specific, I can drag and drop things fine (if you consider laggy fine) in my custom nested blocks.

**Comment by GlennMartin1** [comment]
This should be fixed in https://github.com/WordPress/gutenberg/pull/12159, not released in the plugin (but I think it is in the WP 5 beta).

**Comment by paaljoachim** [comment]
I am glad to hear that it has been fixed. Yeah. I did not notice it in the latest version of the plugin.
