### ISSUE TITLE
Block mover not actionable when the theme content is left aligned

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12290]
Noticed in Twenty Nineteen, see https://github.com/WordPress/twentynineteen/issues/665 and https://github.com/WordPress/twentynineteen/pull/614

The "block mover" position in Gutenberg makes the assumption the post content is centered. 

Normally, the block mover is positioned vertically on the left of the block. Instead, when a block is set to "wide" or "full" alignment, the block mover is positioned horizontally "inline" with the block toolbar.

With a "full" alignment, there is space on the left for the block mover unless the theme changes the toolbar position: Twenty Nineteen does change the toolbar position and this is tracked in https://github.com/WordPress/twentynineteen/issues/665. Themes should just not change the toolbar position: problem solved.

However, the real problem in Gutenberg is with the "wide" alignment. When the post content is left aligned, there's really no space to display the block mover:

![screenshot 2018-11-25 at 13 36 49](https://user-images.githubusercontent.com/1682452/48980812-233e1300-f0ce-11e8-809c-21f8a7b95e5b.jpg)

I'd tend to think this should be better handled in Gutenberg itself, as mentioned at some point in https://github.com/WordPress/twentynineteen/pull/614

**Comment by youknowriad** [comment]
I think that issue is fixed. I can access the movers properly in wide aligned images in TwentyNineteen.
