### ISSUE TITLE
Drop cap block OR image block needs buffer

### ISSUE THREAD

**Issue by MaricaCB** [WordPress/gutenberg#12298]
**Describe the bug**
When adding an image block immediately after a paragraph block that contains a drop cap, the drop caps appears to rest on top of the image rather than have space between

![screen shot 2018-11-25 at 5 25 05 pm](https://user-images.githubusercontent.com/45342346/48986259-5a192680-f0d8-11e8-85b1-91ff71a52890.jpg)

**Comment by johngodley** [comment]
This may be fixed by #12177

**Comment by designsimply** [comment]
Tested and confirmed with #12177 that the paragraph container encompasses the drop cap and that also solves the problem stated here where a short paragraph with a drop cap doesn't have any space between itself and the next adjacent block. 

![Uploading Screen Shot 2018-11-26 at 4.08.58 PM.png…]()
<sup>Seen at http://localhost:8888/wp-admin/post.php?post=26&action=edit running WordPress 4.9.8 and Gutenberg `d0628fbe9` (#12177) using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by annezazu** [comment]
<img width="725" alt="Screen Shot 2021-02-02 at 7 42 42 PM" src="https://user-images.githubusercontent.com/26996883/106690339-d9df8d00-658e-11eb-9e4e-a1a46e2e5e4b.png">

To be safe, confirmed this isn't an issue in Gutenberg 9.8.3 :) Closing this on out!
