### ISSUE TITLE
Leave Page Alert

### ISSUE THREAD

**Issue by riemerta6** [WordPress/gutenberg#12300]
**Describe the bug**
Every time I go to leave a page that has a meta field updated (I'm using Advanced Custom Fields), I get this message: **This page is asking you to confirm that you want to leave - data you have entered may not be saved.**

I saw that this issue has been closed in #3306 and #3356, but I am still receiving this error after the latest update. The content saves so I usually ignore the message but I fear that this could confuse less experienced users.

**To Reproduce**
1. Go to Edit Page
2. Update meta field or Custom Field
3. Leave Page - Alert pops up

**Comment by youknowriad** [comment]
I just tried this and I confirm the message but in my testing it's not Gutenberg triggering this message but it's coming from ACF. I suggest creating a ticket in the ACF repository to check for Gutenberg compatibility.

Thanks

**Comment by riemerta6** [comment]
For anyone that finds this thread, upgrading to version3 of the ACF Pro beta fixed this problem for me.
