### ISSUE TITLE
Use allowedBlocks option in Page template

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#12308]
Would it be possibly to add the possibility to set an array of allowed blocks in the register_post_type arguments as it is in the InnerBlocks component?

Right now, if the Page `template_lock` is set to `false` then any block type can be inserted. The way to avoid this is to create a container block with InnerBlocks, set the allowedBlocks there, set the page `template_lock` to `all` and the page `template` to this container block. The problem here is that the page template will change when new blocks are added inside the container, which will trigger a "Template not valid" notice.

Thanks.

**Comment by swissspidy** [comment]
Why not use the `allowed_block_types` filter? It's very easy to whitelist blocks for a certain post type with it (not so much to blacklist).

See https://github.com/WordPress/gutenberg/pull/6208 for an example.

**Comment by alvaro0555** [comment]
Exactly what I was looking for, this solves my specific issue. Thank you very much @swissspidy 

But still I can see a case where the issue would still appear. Lets say I need root level blocks to be of a specific type: columns, for example. The root level should only allow columns type. However columns contain InnerBlocks which then allows other types of blocks. In this case the filter would only let columns be added (just tested it).
In this case the only way around is the container block.

**Comment by designsimply** [comment]
@alvaro0555 would you mind opening a separate feature request for the case where you want to only allow columns blocks at the root level while still allowing other types of blocks as inner blocks inside the columns blocks and maybe include the sample code you tested if possible?
