### ISSUE TITLE
Latest Posts block “align center” has no effect in admin

### ISSUE THREAD

**Issue by nickcernis** [WordPress/gutenberg#12306]
**Describe the bug**
Clicking the “align center” button on the Latest Posts block does not add the `data-align="center"` attribute to the `wp-block` div.

- Gutenberg 4.5.1.
- WordPress 5.0-RC1-43944 (tested with and without Gutenberg 4.5.1 active).
- Twenty Nine 1.0 (also tested with other themes).

**To reproduce**
1. Add a Latest Posts block.
2. Click on Align Center.
3. Inspect the `wp-block` div.

**Expected behavior**
The `wp-block` div includes a `data-align="center"` attribute.

**Screenshots**
![align-center-latest-posts](https://user-images.githubusercontent.com/647669/49006562-ad878500-f169-11e8-931c-4c6063f960fd.gif)

**Desktop**
 - OS: macOS 10.14.1
 - Browser: Chrome 70.0.3538.102 

**Notes**
Latests Posts content is centered on the front end; it's only the back end where no change takes effect.

**Comment by designsimply** [comment]
Tested and confirmed that no alignment changes happen to the block markup in the editor when you press the "Align center" button on the Latest Posts block but that an `aligncenter` class is added to the `<ul>` container element for Latest Posts on the front end. Tested with WordPress 4.9.8 and Gutenberg `ef596ca85` (>4.5.1) and the Twenty Nineteen theme using Firefox 63.0.3 on macOS 10.13.6.
