### ISSUE TITLE
In your plugin, the bug 

### ISSUE THREAD

**Issue by dimitrisindaryov** [WordPress/gutenberg#12303]
In your plugin, the bug with markup and sentences are not fully written down (see screenshot)
![2018-11-26_11-23-05](https://user-images.githubusercontent.com/45352132/49001495-e1fd4000-f16d-11e8-96bb-6c33983f5f01.png)

**Comment by youknowriad** [comment]
How did you end up with this? Did you touch the HTML by hand? Anything particular here?

**Comment by dimitrisindaryov** [comment]
I tried through html. Corrected everything. There was a problem. The text of the rules is html - the sentences are not listed (see screenshot).
![2018-11-26_12-17-18](https://user-images.githubusercontent.com/45352132/49004539-833bc480-f175-11e8-9a3e-79affda6262c.png)

**Comment by youknowriad** [comment]
Unfortunately, I'm not certain how to reproduce the error. It would be good to know how this came up in the first place?

**Comment by dimitrisindaryov** [comment]
I have the theme Azalea by Just Good Themes. Maybe there is a problem in it?

**Comment by dimitrisindaryov** [comment]
I didn't understand your question.

**Comment by youknowriad** [comment]
How did you end up with `wp:paragraph -->` In your post? Did you convert an existing post? Did you touch the HTML by hand? ... When did it appear?

**Comment by dimitrisindaryov** [comment]
Problems arise when the text is divided into blocks. In the first case, my text was divided into two blocks. And for some reason wp: paragraph ->
I moved the text into one block and the problem disappeared.

**Comment by dimitrisindaryov** [comment]
If you tell me how and what to do, then I can do it.

**Comment by dimitrisindaryov** [comment]
Fix this problem urgently. It occurs when the text is divided into blocks.

**Comment by youknowriad** [comment]
Before splitting the post into blocks, can you go into the Code editor (click the three dots at the top right, and select "code editor") and then copy the whole post HTML and paste it here. Thanks.

**Comment by dimitrisindaryov** [comment]
<p><em>Патриарх говорит</em>:&nbsp;<br>Я много раз задавал себе вопрос, что такое антихрист. С ним мы связываем представление о конце человеческой цивилизации. Антихрист — это персонифицированное зло. Если антихрист будет править миром, то это означает, что зло получило д<em>об</em>ровольную поддержку абсолютного большинства людей.&nbsp;Комментарий: Сколько же было предтеч антихриста. Например, римский император Нерон. Он погиб ужасным образом. Антихрист - историческая личность. Обличать антихриста будут два великих пророка. Это Енох и Илия. Антихрист будет получать силу от отца своего лукавого диавола. С антихристом будет и лжепророк, который будет проповедовать во имя антихристово. Антихрист будет осуждён Господом Иисусом Христом и скинут вместе с диаволом и лжепророком в огненное озеро.</p>

**Comment by dimitrisindaryov** [comment]
This is the text of my publication.☝

**Comment by youknowriad** [comment]
I don't reproduce any issue with this text. But this doesn't look like HTML to me. Is this the whole HTML of your post?

**Comment by dimitrisindaryov** [comment]
[Новый текстовый документ.txt](https://github.com/WordPress/gutenberg/files/2615149/default.txt)

**Comment by dimitrisindaryov** [comment]
Here is the problem text.☝

**Comment by youknowriad** [comment]
This text is already splitted into blocks and I don't see any issue in it? Can you provide the text you had before splitting into blocks?

**Comment by dimitrisindaryov** [comment]
I copied my copyright text from here. https://vk.com/wall-154211304?q=Патриарх%20говорит%20об%20антихристе&w=wall-154211304_4670

**Comment by dimitrisindaryov** [comment]
I turn to the classic editor. Have a good test!

**Comment by designsimply** [comment]
I tried the following test:

1. Deactivate Gutenberg.
1. Go to Settings and change the Site Language to "Русский".
1. Go to https://vk.com/wall-154211304?q=%D0%9F%D0%B0%D1%82%D1%80%D0%B8%D0%B0%D1%80%D1%85%20%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B8%D1%82%20%D0%BE%D0%B1%20%D0%B0%D0%BD%D1%82%D0%B8%D1%85%D1%80%D0%B8%D1%81%D1%82%D0%B5&w=wall-154211304_4670 and copy the text.
1. Go to Posts > Add New and Paste the text. 
1. Give the post a title and publish it.
1. Activate Gutenberg and open the same post again for editing.
1. Click the three dots at the top right of the classic block and select "Convert to Blocks".
1. Check for any instances of `wp:paragraph -->` in the converted content.

Result: no instances of `wp:paragraph -->` appear.

<img width="1280" alt="screen shot 2018-11-27 at 1 10 49 pm" src="https://user-images.githubusercontent.com/1119271/49109099-1a248180-f247-11e8-8975-7feccef39dbd.png">
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=147&action=edit running WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6.</sup>

If you can find something different in my steps compared to yours, please tell me new steps!

**Comment by designsimply** [comment]
@dimitrisindaryov thank you for your report earlier and sorry we were unable to see the same problem you found in our own testing. I see that you have switched to using the classic editor, but I would still like to help if you are interested in trying Gutenberg again! If you are, please look at the steps in my last reply and let me know if any steps are wrong. In the mean time, I will close this issue until a time more information can be provided.
