### ISSUE TITLE
Display a "Convert to blocks" notice on Classic block

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#12307]
**Why**
When you're on a post which was written in the classic editor, it'll be loaded in a classic block. To get the full power of Gutenberg, you, of course, need to convert that classic block. How you do that is not immediately clear. The convert to blocks link is slightly hidden under the more menu:

<img width="420" alt="screen shot 2018-11-26 at 11 12 14" src="https://user-images.githubusercontent.com/487629/49007696-5fc04c00-f16c-11e8-94da-c32518aa6cc6.png">

**Solution**
Wouldn't it be good if we showed a notice in the sidebar telling you as much? Adding a button here that does the conversion would also much improve the discoverability of the convert to blocks functionality.

![classic-block-notice](https://user-images.githubusercontent.com/487629/49008161-74511400-f16d-11e8-899b-081fedc27fba.jpg)

**Comment by karmatosed** [comment]
I agree that increasing discoverability of this would be beneficial. That said, I am not sure adding an interaction pattern of having a message in the sidebar is the way forward. Let's explore after 5.0. I am going to mark this as 'needs design' so that can happen.

**Comment by torres126** [comment]
I quite like what Calypso did in Automattic/wp-calypso#29790 with this. It might not fit in exactly with Gutenberg's style, but something similar may be another alternative.

![50572090-c90d2d80-0db0-11e9-98dc-279521e569e5](https://user-images.githubusercontent.com/43215253/52014326-24792b00-24d7-11e9-9adc-09dbf44e9105.png)

**Comment by sarahmonster** [comment]
It sounds as though this is the same issue as presented in #11718—or at least that it might be solved by the same solution.

**Comment by youknowriad** [comment]
Closing as duplicate.
