### ISSUE TITLE
Applied formats should produce optimized HTML

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#12314]
**Describe the behavior**
When you apply multiple formats to the text when using `RichText`. It doesn't always produce optimal HTML code. In many cases the order of application matters producing different HTML. In the case I recorded, it produces two links instead of one.

**To Reproduce**
1. Create a new post.
2. Type a few words in a paragraph.
3. Apply `bold` to one of the words.
4. Apply `italics` to the part of the bolded word.
5. Apply `link` to the full bolded word.
6. You should see something like the following when checking HTML source:
```html
<p>My <strong><a href="http://localhost:8888/?page_id=2">te</a><em><a href="http://localhost:8888/?page_id=2">xt</a></em></strong> to test</p>
```

**Expected behavior**
Wrap text with only one link in all cases, no matter in what order formats get applied. The HTML should look like:

```html
<p>My <a href="http://localhost:8888/?page_id=2"><strong>te<em>xt</em></strong></a> to test</p>
```

**Screenshots**
![rich text formats](https://user-images.githubusercontent.com/699132/49016302-fa795480-f185-11e8-808e-d78f4e19daa8.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70

**Comment by gziolo** [comment]
@iseulde, any thought on this one?

**Comment by iseulde** [comment]
I thought this has already been reported once. Until now I considered this low priority. I can work on this for whatever milestone needed.
