### ISSUE TITLE
anoying scrolling for no real reason

### ISSUE THREAD

**Issue by jodumont** [WordPress/gutenberg#12321]
I don't know if I'm alone to consider this a loosing my time and/or a lack of non-sense but
it is possible to make this bar sticky

![image](https://user-images.githubusercontent.com/5204724/49024572-1850b480-f19a-11e8-8bcc-b188b4a07c23.png)

let's say I have a text with a 200 lines a have continuously to scroll up to access it

I understand the block concept and where Gutenberg want to bring user but just because of this I went back to the old editor

**Comment by designsimply** [comment]
I tested just now using WordPress 4.9.8 and Gutenberg 4.5.1 with Firefox 63.0.3 on macOS 10.13.6 and the toolbar in the classic block stayed stuck to to the top of my screen when scrolling:

![12321](https://user-images.githubusercontent.com/1119271/49033594-d9f0d080-f16c-11e8-9809-7d71fa0247b5.gif)

May I ask what versions of WordPress, Gutenberg, OS, and browser you are using?

**Comment by jodumont** [comment]
Hi thanks for your reply;
I was really surprise the teams didn't think about this

so the issue appear on both browser
WordPress 4.9.8
Gutenberg 4.5.1
Ubuntu 18.04 LTS (up to date)
Firefox 63.0.3 (64-bit), the only plugin is shaarli
Google Chrome Version 70.0.3538.110 (not chromium), the only plugin is lastpass
both of them run with Do Not Track, nothing else really special I could think right now

**Comment by jodumont** [comment]
this morning I updated to Gutenberg Version 4.6.1 and it works as expected :)
notice: I still have the same OS with the same FF and Chrome with the same plugins
