### ISSUE TITLE
Block Editor: All references to blocks should be accounted for in history

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#12327]
Right now, if we edit blocks, the history (undo/redo) is kept in the redux store using the `withHistory` higher-order reducer. But only the `blocks` substate is kept in the history while the block selection is not. Which means if we trigger undo/redo we can potentially end up with a state tree where the blockSelection points to a non-existing block. (For example a block that was removed by undoing a change).

We should explore whether moving the block selection reducer inside the `withHistory` Higher-order reducer could solve these issues and which side-effects it would have on the undo/redo behavior.

Related #12214

**Comment by aduth** [comment]
Am I correct in thinking that this could apply to _any_ state which holds a reference to a block's `clientId`?

This would include:

- `blockSelection`
- `blocksMode`
- `insertionPoint` (?)
   - It holds `rootClientId`, which can technically become removed by Undo history
- `reusableBlocks`
   - Value is `{ clientId, title }` pair
   - Ideally we'd opt for removing this state instead (#7119)
- `blockListSettings`

**Comment by youknowriad** [comment]
Am I correct in thinking that this could apply to any state which holds a reference to a block's clientId?

Yes, 👍

**Comment by aduth** [comment]
I think it's more accurate to consider this a bug. The issue has manifested itself in a few forms:

https://github.com/WordPress/gutenberg/pull/15543#issuecomment-491933684

>>click the "More" button and the editor crashes
>
>I think the issue here is that wp.data.select('core/block-editor').getSelectedBlockClientIds() still returns the previously selected block, even though it has been deleted.

#12002

>The expected result is that the focus was returned to the previous block.

**Comment by ellatrix** [comment]
@youknowriad Is this still relevant after #17824?

**Comment by youknowriad** [comment]
Maybe not, I was only aware of the selection. I think we can close and reopen specific issues if needed.
