### ISSUE TITLE
Not possible to embed Cloudup links

### ISSUE THREAD

**Issue by iamgabrielma** [WordPress/gutenberg#1233]
When pasting a Cloudup URL into the embed content block in a post, does not work and displays the message `Sorry, we could not embed that content.`

**Steps to reproduce:**
1 - Go to your Dashboard > Gutenberg > New post
2 - Click on the "+" add content button > Scroll down to "Embed" type of content > Click on "Cloudup"
3 - Paste a Cloudup URL and click `Embed`. Example URL: https://cloudup.com/cPWc0cgxWpy

[Image of the issue]( https://cloudup.com/cPWc0cgxWpy)

**Comment by jasmussen** [comment]
Thought it was a bug, then relabelled because I realize this probably has to do with what oembeds WordPress supports. Which means it might be an upstream issue?

**Comment by aduth** [comment]
Cloudup is a supported oEmbed in core:

https://github.com/WordPress/WordPress/blob/3a19079/wp-includes/class-oembed.php#L96

I was able to verify this in my testing. Looking at the response received from the oEmbed proxy endpoint, it returns a valid result:

```json
{
   "version":"1.0",
   "type":"photo",
   "title":"Screen Shot",
   "url":"https:\/\/cldup.com\/uKKtVAFSle-900x900.png",
   "provider_name":"Cloudup",
   "provider_url":"https:\/\/cloudup.com",
   "width":900,
   "height":346,
   "thumbnail_url":"https:\/\/cldup.com\/uKKtVAFSle-1200x1200.png",
   "thumbnail_width":1200,
   "thumbnail_height":462,
   "author_name":"Gabriel Maldonado"
}
```

However, looking at the implementation of the Embed block, it checks for the presence of an `html` property in the oEmbed response payload, which is not the case here as can be seen above.

https://github.com/WordPress/gutenberg/blob/5eceb50/blocks/library/embed/index.js#L128

We should consider enhancing the Embed block to render supported `type` properties like `photo` in this example.

Related: #816, cc @notnownikki 

Aside: Cloudup is also registered as a standalone embed block variant:

https://github.com/WordPress/gutenberg/blob/5eceb50/blocks/library/embed/index.js#L204

**Comment by notnownikki** [comment]
Ok I'll take a look at this and make a list of any other content types we might have to extend things for.

**Comment by notnownikki** [comment]
Fix for photo embeds is up for review here https://github.com/WordPress/gutenberg/pull/1334

**Comment by aduth** [comment]
Fixed by #1334

**Comment by swissspidy** [comment]
There are also other types like `video`. Do these work?

**Comment by aduth** [comment]
Per 2.3.4.2 of the [oEmbed spec](http://oembed.com/), the `video` type _must_ specify an `html` value, which is already supported by the embed block:

https://github.com/WordPress/gutenberg/blob/af63d4eaceb8d6b0cc3c235da3b7fa30ac57dcfe/blocks/library/embed/index.js#L99-L100

The `link` type could probably use better support though, since it mentions that it can omit both `url` and `html` properties. It's not clear to me what we'd expect to be shown for these types.
