### ISSUE TITLE
Reusable blocks: Trashed blocks appear in editor and frontend

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#12339]
Reusable blocks that have been trashed should no longer appear in posts and pages that use it.

#### Steps to reproduce

1. Create a new post
1. Insert a block
1. Convert the block to a reusable block
1. Go to _Manage All Reusable Blocks_
1. Trash the reusable block you created
1. Go back to the post you created. Note that the reusable block still appears
1. Preview the post. Note that the reusable block still appears

#### Expected result

The trashed reusable block should appear as _Missing or deleted_ in the editor, and not render at all in the frontend.

#### Actual result

The reusable block appears in both the editor and frontend.

**Comment by GlennMartin1** [comment]
I think it's been this way since the beginning.

To actually remove the reusable block, it's got to be removed from the trash (empty trash).

Perhaps I should have reported this before - I quit reporting since hundreds of other reported bugs are not being addressed, either.

**Comment by noisysocks** [comment]
Yes this is an oversight from when the feature was implemented in https://github.com/WordPress/gutenberg/pull/9588. I don't think the current behaviour is desirable. 

Please keep submitting detailed bug reports—they are very useful even if some reports get lost in the chaos 🙂
