### ISSUE TITLE
Confirm navigation when user has unsaved changes

### ISSUE THREAD

**Issue by Kluny** [WordPress/gutenberg#1234]
In the TinyMCE editor, if I hit backspace when the field is not in focus, I get an "are you sure you want to leave this page?" warning. In Gutenberg, the backspace button takes you back, and all post data is lost.

Using WordPress.org install on PHP 7 with WP 4.8.

**Comment by BE-Webdesign** [comment]
Hi @Kluny,

Thank you for the report!
