### ISSUE TITLE
Get generated unique Block ID

### ISSUE THREAD

**Issue by AdsonCicilioti** [WordPress/gutenberg#12349]
I've seen issues #9959 e #5384, but the solutions covered are solved manually, and that's not what I want/need. I'm creating a custom block and it will have predefined and dynamic styles, generated by the user's choices in the editor.

But if the user add a new block of the same type will have problems because the styles of the first will conflict with the others, because I do not have any unique identification that differs from each other.

I do not want to let the user hostage of a class or anchors (id) custom. Via PHP, I need to know how to get the unique ID of each Block for both Frontend and Backend.

I find that question pertinent. And you?

**Comment by swissspidy** [comment]
Is it a dynamic block that will be rendered purely in PHP (`save() { return null; }` in JS), or are you saving HTML to the database?

For the former, you could just generate unique ID in PHP.

For the latter, you could use the `withInstanceId` HOC for example: https://github.com/WordPress/gutenberg/tree/master/packages/compose/src/with-instance-id

**Comment by AdsonCicilioti** [comment]
I'm using the Lazy Blocks plugin, and my temporary solution is use php `$uid = uniqid( 'grid-mix-' );` on frontend html.
I Don't known how this plugin works, but i believe that save in database as html.
For now my solution works fine,

I need to dig deeper and know if I need to relate the unique id of the block in the frontend with those of the backend.

**Comment by danieliser** [comment]
Why do all these get closed. If every block is given a unique ID in the editor already, why the hell can't we simply pass that as part of the parsed block array?

I can't believe 6 years later we still don't have unique ids available in PHP.

@designsimply - this was never added, and should not be marked completed/closed.

**Comment by swissspidy** [comment]
@danieliser It seems like your use case is different than the one from OP 5 years ago. They asked a question, got a reply & then closed the issue as the situation was resolved for them. I'd suggest opening a new issue with your suggestion.

FWIW, blocks in the editor only have a _client_ ID for the life time of the editor, there is no persistently stored ID for a block.

I'm sure if you open a new issue and explain your use case then you'll get some meaningful answers. But not in an old issue like this one.

**Comment by danieliser** [comment]
@swissspidy - Odd, could have sworn the block ID was passed in raw attributes, before parsing. Will open a new issue thanks.
