### ISSUE TITLE
SVG and ForeignObject

### ISSUE THREAD

**Issue by quentincl** [WordPress/gutenberg#12353]
**Describe the bug**
I'm testing Gutenberg to check if my website would display correctly after Wordpress 5.0
I noticed that Gutenberg can't manage ForeignObject in SVG.
I have a simple `<h3>` tag into my foreign object but with Gutenberg this text does not render in the svg image. It's rendered next to it, as if i'm not using foreign object and just put text next to my svg image.

**To Reproduce**
Just try this example with Gutenberg : 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

This will not been displayed as intended.

**Expected behavior**
I expect to see the same result as this example.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

**Screenshots**
So my svg is a simple speech bubble, with foreign object to put a text inside.

Screenshots of how it actually renders

![capture](https://user-images.githubusercontent.com/45388674/49077634-0a537000-f23c-11e8-8278-0b9fff28a480.PNG)

Screenshots of how it renders with gutenberg

![capture2](https://user-images.githubusercontent.com/45388674/49077639-0fb0ba80-f23c-11e8-8022-cb8c94d561c6.PNG)

**Additional context**
- Version of Gutenberg : 4.5.1

**Comment by johngodley** [comment]
Can you provide more details about what you've created in Gutenberg?

I've just entered the HTML from the mozilla site into a Custom HTML block and it works fine, displaying the text inside the SVG.

**Comment by quentincl** [comment]
So i did more testing, and i misunderstood the problem.

When i convert the block from the classic editor to gutenberg editor, the `svg` tag does not close.
I've entered the correct html and it works fine.

So it's a different problem.

I'm not sure why it didn't works when i was testing with the mozilla site example.
Probably because my other `svg` tag wasn't closed.

Sorry for the time you've spend, thanks for the quick answer !
