### ISSUE TITLE
First welcome tip obscures the UI element that it references

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#12358]
**Describe the bug**

The welcome tip that appears the first time a user interacts with Gutenberg obscures the UI element that it references. This is a poor first experience for new users.

Tested with WordPress 5.0 RC.

**To Reproduce**

1. Ensure the localStorage in your browser is clear for your domain, so that tips appear (related: #8052).
2. Open the block editor.
3. Follow the instruction on the first welcome tip: `Click the “+” (“Add block”) button to add a new block.`
4. Observe that the block insertion UI is obscured by the tip.

**Expected behavior**

The welcome tip should not obscure the UI that it's referencing.

**Screenshots**

<img width="564" alt="" src="https://user-images.githubusercontent.com/208434/49085796-c451d880-f24a-11e8-8368-a0a6ea0dbb40.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 70

**Comment by mtias** [comment]
Related: #9242

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
