### ISSUE TITLE
Second welcome tip instructs the user to open a control that's already open

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#12359]
**Describe the bug**

The second welcome tip instructs the user to open the `Settings` panel. This panel is already open, and following the instruction causes it to close.

Tested with WordPress 5.0 RC.

**To Reproduce**

1. Ensure the localStorage in your browser is clear for your domain, so that tips appear (related: #8052).
2. Open the block editor.
3. Follow the instruction on the second welcome tip: `Click “Settings” to open it.`
4. Observe that the settings panel is now closed, because it was already open.

**Expected behavior**

The initial settings panel state and the information on the corresponding welcome tip should match.

**Screenshots**

<img width="555" alt="" src="https://user-images.githubusercontent.com/208434/49086021-5fe34900-f24b-11e8-9d5b-e9ab28877309.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 70

**Comment by johnbillion** [comment]
Addendum: This tip also references a control called `Settings`, which is in fact represented in the UI by a cog icon.

**Comment by youknowriad** [comment]
closed by #12911
