### ISSUE TITLE
Do not replace the post editing screen and make it an editor only

### ISSUE THREAD

**Issue by Blackbam** [WordPress/gutenberg#12362]
**Is your feature request related to a problem? Please describe.**
From a review:

> The idea of Gutenberg basically is great: Providing a standardized block building interface will greatly improve layouting possibilities and compatibility in WordPress. Developers can share their custom blocks and clients finally do not have to use clumsy shortcodes for layouting. To be honest – the time for this has come.
> 
> However we think that the Gutenberg project has made a fatally wrong decision regarding its implementation which is also the root cause of most of the bad feedbacks: Gutenberg is designed to replace the post editing screen. In short: Do not do this. Rewrite part of this project!
> 
> Gutenberg should be an editor – maybe even a page builder. But you should keep the editing screen as it is – including all the meta boxes, the post update box, the category selection boxes.
> 
> Changing this would give the following tremendous advantages:
> 
> Perfect Backwards compatibility of existing projects
> 
> It would be easy to switch between Gutenberg and TinyMCE per page
> 
> Not one single existing plugin is broken except for the ones which directly involve TinyMCE specific JavaScript
> 
> Please reconsider the implementation of Gutenberg and think of creating the project this way! It would save 15% of the whole web and countless unecessary development hours!

**Describe the solution you'd like**
Make it an editor which is being put into the post editing screen instead of an editor which replaces the post editing screen. 

In detail this means:
 - remove the publish meta box, the category and the tag meta box out of the editor
 - remove custom meta boxes out of the editor and leave them as is

Additional advantage: You even could have multiple Gutenbergs within meta boxes. This would be really nice for advanced themes.

**Describe alternatives you've considered**
In my opinion there is no good alternative to this. I do not know why you have put those meta boxes inside of the editor anyway.

**Comment by talldan** [comment]
I'm going to close this as a stale issue since there's been no discussion for a few years.
