### ISSUE TITLE
Latest Posts - displays by category in editor but not when published

### ISSUE THREAD

**Issue by pebblecoder5** [WordPress/gutenberg#12369]
**Describe the bug**
Creating a Latest Posts by Category block displays the correct posts in the editor but not on the website

Gutenberg 4.5.1.
WordPress 4.9.8
HitMag (also tested with Twenty Sixteen)

**To reproduce**

Add a Latest Posts block.
Under Latest Post Settings select category

**Expected behavior**
The block displays the latest posts within just the category

**Screenshots**
What it looks like in editor
![vcy-rally-draft](https://user-images.githubusercontent.com/12863686/49101422-c95b5b80-f23b-11e8-8eff-418debb832e4.PNG)
What it looks like published
![vcy-rally-full](https://user-images.githubusercontent.com/12863686/49101427-ceb8a600-f23b-11e8-9349-2b7268fe191d.PNG)

**Desktop**

OS: Windows 10 Home
Browser: Chrome 70.0.3538.102

**Comment by ianbelanger79** [comment]
I can confirm that this issue exists in 5.0-RC1-43944. It seems that the Latest Posts Widget Block always shows the latest posts from any category on the front end, no matter what category is set to show in the editor.

**Comment by designsimply** [comment]
Tested with WordPress 4.9.8 and Gutenberg `ef596ca85` and could not reproduce. Looks like it was fixed earlier today in https://github.com/WordPress/gutenberg/pull/12246.
