### ISSUE TITLE
Add settings to the WordPress admin in order to enable / disable it on a a per post / page / post-type basis

### ISSUE THREAD

**Issue by Blackbam** [WordPress/gutenberg#12361]
**Is your feature request related to a problem? Please describe.**
Depending on a post type we need an editor with layouting possibilities, with simple text writing possibilities, a WYSIWYG editor or no editor at all.

**Describe the solution you'd like**
Within an admin settings screen (e.g. Settings -> Writing) there should be a possibility to enable / disable Gutenberg on a post type basis.

Within the post edit screen there should be a possibility to disable the editor on a per post basis.

**Describe alternatives you've considered**
At least provide functions for this and show them within the WordPress codex.

**Comment by designsimply** [comment]
This is something optionally provided as a plugin. Please see https://wordpress.org/plugins/gutenberg-ramp/.
