### ISSUE TITLE
Protecting open e-mail addresses added to a block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12377]
**Is your feature request related to a problem? Please describe.**
Receiving spam through open e-mails addresses added to a web site.

**Describe the solution you'd like**
Pasting a regular e-mail address into a heading, paragraph block or other blocks should make it so that e-mail spam harvester bots are not able to grab the e-mail addresses.

**Describe alternatives you've considered**
Instead of adding the regular e-mail address like so: name@domain.com I have added a contact form, but for many cases the clients would instead like to just show the e-mail address openly. I have on occasion shown the e-mail address like so: name---ATT--domain.com, and I have seen a few other variants on different web pages. It does not look professional when adjusting the e-mail address so that it looks different then what it should. The option is then to either find a solution perhaps plugin, add some code or have to accept that one will receive spam from e-mail harvesters.
It would be really good to see e-mail addresses automatically protected through Gutenberg.

**Comment by swissspidy** [comment]
There‘s no 100% protection against bot like these. Bots are getting smarter and they can easily deal with such obfuscated email addresses. Nowadays it should be accepted that email addresses can and will get into the wrong hands. The best protection is a good spam filter.

Any such method added to the editor would just give a false sense of security. That‘s why I think this is definitely plugin territorry.

Just my 2 cents of course :-)

**Comment by paaljoachim** [comment]
Alrighty! Good points!
I am still hoping that Gutenberg can add something to make it a little harder for e-mail harvesters to gather e-mail addresses.

**Comment by markjaquith** [comment]
This is something that can (and is) handled by plugins. Definitely doesn't belong as a function of the editor.

Any way you can obfuscate it but a human can still read it, a computer can read it. This wasn't practically true in the early 2000s, but now it's easy for a bot to run JS and parse images and combine `foo AT bar DOT com` and probably anything else you can think of. Spammers gonna spam, unfortunately.

Recommend close.
