### ISSUE TITLE
Webpack-dev-server and Gutenberg (with hot loading)

### ISSUE THREAD

**Issue by espenjanson** [WordPress/gutenberg#12373]
**Describe the bug**
The save function does not work when I am running development server using webpack-dev-server and browsersync (with hot loading). Wordpress is running on localhost:3000 where the the rest api is also being called from. Webpack-dev-server is running on localhost:8080. Everything works great until I try to save content - any content - when it just doesn't save. Nothing is written to the database. It works after building the bundle (production mode). Response on the network request is 200 (?)

In the posts table of the database, the post is saved with a comment delimiter for each block but the content for each block is empty. I can see in the network request that the save function does not return anything. It seems to me that the serializer thinks that my blocks should be empty elements (if I interpret the / correctly, as start delimiters have no slash in the beginning but end blocks do, I figure that this is similar to `<element></element> = <element />`)

If i save three blocks (that are supposed to have some content inside), this is exactly what gets sent to the database in the request body as content, and then written to the database:

```
<!-- wp:mona/monas-first-block /-->

<!-- wp:mona/monas-first-block /-->

<!-- wp:mona/monas-first-block /-->
```

My editor is just a simple input field that sets the attributes:

```
<input onChange={handleChange} value={content} type="text" />

  attributes: {
    content: {
      type: "string",
      source: "text",
      selector: "p"
    }
  }

```
Save function returns a p with content inside.

_**Not really important though since I know that it is working as soon as I build.**_

**To Reproduce**
1. Install webpack-dev-server and set up a proxy to your local wordpress site using browser sync webpack plugin
2. Create a new block
3. Everything works fine in the editor and saving content to post meta works
4. Trying to save the block "normally" using the save function
5. Nothing happens

**Expected behavior**
Block should be saved.

UPDATE:

Getting a little bit closer to isolating the issue, I notice that when I build, it seems that the editor expects the content of the block to equal whatever is declared in the save function, and throws an error if I true to look at blocks saved in development:

`Block validation: Expected {type: "StartTag", tagName: "div", attributes: Array(1), selfClosing: false}, instead saw end of content.

Block validation: Block validation failed for `mona/monas-first-block` ({name: "mona/monas-first-block", attributes: {…}, category: "common", icon: {…}, title: "Monas first block", …}).

Expected:

<div class="wp-block-mona-monas-first-block">hello</div>

Actual:

`

This does not happen in development, which means that the editor script is not even reading what the save function returns. However, I am getting logs from the save function, so it is being called.

UPDATE 2:

Okay so I finally realized where the error lies. It is somewhere in the webpack production vs development setting. When I set the mode variable to production, everything works fine even with the dev server running.

Any ideas of what could be causing this in webpack?

**Comment by swashata** [comment]
I have faced similar problems. I was using react-hot-loader exported edit component.

I thought it was because of the proxy created by rhl.

I will do some more debugging and will try to find out if there's a way around it.

**Comment by espenjanson** [comment]
It could be rhl itself too since it is being bypassed when mode is production nowadays. Thanks for trying! 👍

**Comment by gziolo** [comment]
@espenjanson did you solve your issue? I'm not using hot module reloading in my workflow so I'm not familiar with the issue. I'll close this issue. If there is something actionable, would you mind opening PR with the fix proposed? We can continue the discussion in this issue as this might be helpful for others who use similar workflow to what you shared.

**Comment by strarsis** [comment]
As Gutenberg uses React components, Hot Reloading would be a very logical and nice idea.
Tools like browsersync wouldn't work (without extending them) because Gutenberg downloads the style files via HTTP on serverside and then parses, remaps and injects the styles using some specific JavaScript. Hot reloading would solve all the issues and would even allow developing/adjusting Gutenberg blocks in the editor in realtime.

**Comment by solutions4theweb** [comment]
Hot loading does work with gulp + browsersync + webpack.
This is essentially my watch task in `gulpfile.babel.js`:

```
export const watch = () => {
  build();
  browserSync.init({
    open: false,
    injectChanges: true,
    proxy: "http://localhost:8081",
    port: 3000,
    ghostMode: false,
    middleware: [
      webpackDevMiddleware(scriptsBundler, {
        publicPath: scriptsConfig.output.publicPath
      }),
      webpackHotMiddleware(scriptsBundler)
    ]
  });
  gulp.watch("src/**/*.scss", series(bootstrap, buildStyles, streamStyles));
};
```

where `scriptsBundler = webpack(scriptsConfig);`
`scriptsConfig` is just a webpack config exported from a webpack config file.
