### ISSUE TITLE
In debug mode, few warnings display 

### ISSUE THREAD

**Issue by pmbaldha** [WordPress/gutenberg#1237]
If we enable debug mode,  There are some errors displays:

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/utils/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 51

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/date/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 57

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/i18n/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 89

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/element/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 95

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/components/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 101

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/blocks/build/index.js in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 107

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/components/build/style.css in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 115

Warning: filemtime(): stat failed for G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master/blocks/build/style.css in G:\xampp\htdocs\et\wp-content\plugins\gutenberg-master\lib\client-assets.php on line 121

**Comment by Soean** [comment]
Hi pmbaldha,
did you run npm as mentioned here? https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md

If you just want to test the plugin, you can run the version from the plugin repository: https://wordpress.org/plugins/gutenberg/

**Comment by mrwweb** [comment]
@Soean I'm seeing these errors when running the plugin.

**Comment by youknowriad** [comment]
Is this still an issue?

**Comment by jahvi** [comment]
Can confirm this is still an issue, steps to replicate:

1. Clone repo into `plugins` directory.
2. Run `npm install` in cloned repo.
3. Set `WP_DEBUG` to `true`.
4. Warnings mentioned show up in the admin area.

**Comment by jahvi** [comment]
Neverming running `npm run build` fixes the issue

**Comment by youknowriad** [comment]
Thanks, let's close this issue.
