### ISSUE TITLE
Plaintext editor converts two trailing spaces to a dot, why? 

### ISSUE THREAD

**Issue by willdelphia** [WordPress/gutenberg#12389]
I have been testing Gutenberg and have created a few custom block types. 

I was pleased to discover the PlainText editor (the one used in the HTML block type) but discovered that when you are typing and you hit the space bar twice it adds a period. (It seems to only happen when the two spaces in question trail some non-space characters). What is the rationale behind this behavior. I would think that is someone is writing HTML there might be cases where they want to indent with spaces or use two spaces elsewhere and adding random periods to the code seems like it would result in bad results for user experience, or would result in extra periods being added to peoples markup. 

Would it be possible to turn this behavior off somehow?

**Comment by designsimply** [comment]
Out of curiosity, does that happen only in your custom blocks or does it happen in the core Custom HTML block for you as well?

The behavior you're describing sounds to me like something the OS is doing. Are you using macOS by chance? Can you try opening your keyboard settings and uncheck the option for "Add period with double-space" to see if that makes a difference for you? See https://discussions.apple.com/thread/7783094

**Comment by willdelphia** [comment]
Wow. I feel like an idiot. It was mac os! 

Case closed.

**Comment by designsimply** [comment]
Thanks for confirming! And please don't feel that way because I'm sure you won't be the only one with the same question and it's nice to have it documented. 🙂
