### ISSUE TITLE
Lists: Allow inline images

### ISSUE THREAD

**Issue by v18** [WordPress/gutenberg#12396]
I'd like to add images within a list block.

I was able to add images to a list in the classic editor by typing **Shift+Enter** when on a list item(on a Mac) to get a newline. On that newline, I'd add my image using the media button or by copying+pasting.

When I use **Shift-Enter** in Gutenberg, I get a new item for the list. Instead, what I expected to see is a newline inside the same list.

And, I notice that I am not able to add images in a list at all, unless I use HTML mode :(

**A Gutenberg example, here's what happens when I use shift+enter:**

![gutenberg-shift-enter](https://user-images.githubusercontent.com/11487924/49179665-c38b7600-f320-11e8-800a-a30abbd95835.gif)

**Classic editor - I click shift+enter and add an image inline:**

![add-image-in-list-classic-editor](https://user-images.githubusercontent.com/11487924/49179678-cc7c4780-f320-11e8-96c8-c337f96f468e.gif)

**Comment by mrwweb** [comment]
Noting that the `SHIFT` + `ENTER` bug is already being tracked here: #11215

**Comment by v18** [comment]
Ooh, thanks!

**Comment by iseulde** [comment]
You can insert inline images with the inserter.

<img width="388" alt="screen shot 2018-11-29 at 14 00 17" src="https://user-images.githubusercontent.com/4710635/49223482-2e9b8200-f3df-11e8-9f2f-2ae067f00086.png">

**Comment by v18** [comment]
@iseulde thanks for the note. I tried to add an image to a list using the inserter, but I didn't figure out how to do that. Can you spell it out for me a bit more?

I tried all the different buttons around the list block, but didn't see the inserter:
<img width="712" alt="screen shot 2018-11-29 at 9 50 32 am" src="https://user-images.githubusercontent.com/11487924/49229919-8674c180-f3bc-11e8-9185-a87e3f5f0608.png">

**Comment by iseulde** [comment]
When you have the caret blinking inside the list blocks, you can user the inserter (+) in the top toolbar on the left. There you will find a button to insert an inline image in the "inline elements" section, after "most used".

**Comment by v18** [comment]
@iseulde thanks for the instructions. I had a chance to try it, but when I user the inserter, a new image gets inserted _after_ the list block, not within the list block. Here's a gif to demonstrate:

![add-image-to-list](https://user-images.githubusercontent.com/11487924/50859164-9a6af600-1360-11e9-9c5f-3273c4a6ed8f.gif)

I expected the image block to be right next to the second item on the list because that's where my cursor was.

**Comment by iseulde** [comment]
You need the "inline image" one, not "image". It's under "inline elements".

**Comment by v18** [comment]
@iseulde YAS, thank you for walking me through this 🙏🙏🙏

![add-image-to-list-success](https://user-images.githubusercontent.com/11487924/50981216-7d513700-14c8-11e9-82b7-a4e9b8ed1379.gif)

🎉

**Comment by ercancoban** [comment]
But the bove shown method only places the image just after the chosen line:
1. item image
2. item

But how will it be possible to locate the image between two list items such as:
1. item
image
2. item

any idea?

**Comment by v18** [comment]
@ercancoban - it's not possible to do that right now within Gutenberg (but you can do it if you go to HTML mode). There's another issue tracking newlines within lists: https://github.com/WordPress/gutenberg/issues/11215
