### ISSUE TITLE
Edit as HTML should indent my code

### ISSUE THREAD

**Issue by v18** [WordPress/gutenberg#12397]
When I click on 'Edit as HTML' when on a Gutenberg list block, I see this:

```
<ol><li>Apples</li><li>Oranges</li><li>Limes</li><li>Lemons</li></ol>
```

It's be better if the HTML was neatly spaced + indented, like so:

```
<ol>
  <li>Apples</li>
  <li>Oranges</li>
  <li>Limes</li>
  <li>Lemons</li>
</ol>
```

Some images to compare:

Gutenberg visual:

<img width="255" alt="classic-list-html" src="https://user-images.githubusercontent.com/11487924/49179810-1d8c3b80-f321-11e8-8b16-e0a7408b959d.png">
<img width="640" alt="gutenberg-list-html" src="https://user-images.githubusercontent.com/11487924/49179812-1d8c3b80-f321-11e8-8166-a9c3b40312ba.png">
<img width="151" alt="gutenberg-list-visual" src="https://user-images.githubusercontent.com/11487924/49179813-1e24d200-f321-11e8-91b1-10c2f1917f1d.png">

**Comment by iseulde** [comment]
The HTML "beautifier" was intentionally removed. Cc @aduth
Note that this is a general issue for all blocks, not just lists.

**Comment by aduth** [comment]
Previously: #7892

It should be noted that there could be different behaviors between what's presented for editing in "Edit as HTML" and what's actually saved as markup of the post.

**Comment by ali1234** [comment]
That bug seems to indicate that the editor is supposed to preserve whitespace? Because for me it does not. It always runs everything into a single line.

**Comment by mtias** [comment]
Going to close this. Once better async load is present there's a willingness to add some more syntax highlighting to HTML editing.

**Comment by mikegwhit** [comment]
Bump, this is what I came here for.. it's pretty unthinkable that this hasn't been addressed?  Can I help submit a PR or similar?  Has anything been drafted for how to address this technically?  It sounds like there must be a hook when switching the edit mode to HTML at which point HTML can be beautified if it hasn't.  Then thereafter HTML can be preserved as developer left it, or minified if developer makes no edits to HTML.  It sounds like technically it may be hard to preserve an "edit version" of a post vs. a minified "publish version" of a post, however.

I had to go to a third-party website to beautify my table's HTML which was wild.  I am just getting back into WordPress after some years of hiatus.

I cannot imagine in the scheme of things whitespace in blocks that users edit is going to have a giant hit on performance when compared to the UX tradeoff currently experienced.

CC @mtias

**Comment by mtias** [comment]
There are a few mixed things here: how code is stored and how code is presented. For code presentation the best solution was using a proper editor that handled lines and some level code highlight. For saving code the decision was not to touch the source as per #7892. It's certainly possible to beautify on render and not commit unless there are changes. If someone wants to explore that we can look into it.
