### ISSUE TITLE
Links to the user and developer handbook on Gutenberg's Documentation index page are broken

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#12399]
**Describe the bug**

Links to the User Handbook and Developer handbook are broken on the [handbook's index page](https://wordpress.org/gutenberg/handbook/readme/). 

While on [handbook's index page](https://wordpress.org/gutenberg/handbook/readme/):

**Expected behavior**
click on the User Handbook link - https://wordpress.org/gutenberg/handbook/users/readme/ 
and user is redirected to https://wordpress.org/gutenberg/handbook/readme/  

click on the Developer handbook - https://wordpress.org/gutenberg/handbook/designers-developers/readme/
and user is redirected to https://wordpress.org/gutenberg/handbook/readme/

**Comment by chrisvanpatten** [comment]
Have to guess this is related to the coaching issue mentioned in Slack today. Seems our changes to the manifest aren’t being picked up by the auto syncing.

**Comment by chrisvanpatten** [comment]
Brought this up in today’s #meta chat; awaiting more info from that team.

**Comment by chrisvanpatten** [comment]
#12411 partially addresses this, although we also now have a bunch of 404s we need to clean up.

**Comment by greatislander** [comment]
The link to the Users Handbook is still broken as of this morning, which seems like a critical issue to fix before Thursday: https://wordpress.org/gutenberg/handbook/users/

**Comment by chrisvanpatten** [comment]
@greatislander The users handbook link will be removed, hopefully in #12585. We aren't going to store the users handbook on GitHub for the moment, it will be stored inside of HelpHub on WordPress.org once that's live, hopefully in the next few days. Once it's live we will link to it again in the handbook; we're just not sure yet what the final URL for HelpHub will be so we can't link to it quite yet.

**Comment by chrisvanpatten** [comment]
Would recommend following the #docs channel in WP Slack for more up-to-date info on this :)

**Comment by chrisvanpatten** [comment]
These 404s should be largely resolved now, so I'm going to close this out. If we find specific issues we can get PRs opened to resolve them! Thanks for the report <3
