### ISSUE TITLE
Columns Block Editor -- Cannot change columns amount value to equal 1 with the setting slider or the up/down arrows

### ISSUE THREAD

**Issue by kelsS** [WordPress/gutenberg#12400]
**Describe the bug**
When editing the settings of the Columns block, you cannot adjust the columns number to equal the value "1" column with the slider dial UI and you cannot not set the value to "1" with the up/down arrows next to the numerical value field. The only way to change the columns block to be 1 column is to type in the number 1 into the value field.

**To Reproduce**
1. Edit a page and add the "Columns Block"
2. Click on the "Block" settings for "Columns" in the right sidebar
3. Attempt to slide the value slider dial to the left to equal "1"
5. Attempt to change the column value to "1" with the up/down UI next to the value field
4. See error, that the value will only go down to 2, which means you cannot create 2 columns with those UI elements

**Expected behavior**
Expected to be able to set the columns value setting to equal 1 column with all the UI options available under Block -- Columns settings

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.1
 - Browser: Chrome
 - Version: 70

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Version: 4.5.1

- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
Out of curiosity, what is the use case for wanting to add just a single column to a columns block?

Tested and confirmed that I cannot set the number of columns in Settings > Block > Columns to "1" using the up/down arrows in the number field using WordPress 4.9.8 and Gutenberg 4.5.1 `master` @ `e4fd51cb5` with Firefox 63.0.3 on macOS 10.13.6.

Note: I found that I can set the number of columns to "1" if I type in the number manually.

This may be by design, so I'll label this with `Needs Decision`.

**Comment by kelsS** [comment]
Hi designsimply,

Thanks for the reply. I was trying to create a single full width column to test out different layout capabilities of the new editor. Similar to how you can create a single column and multiple columns with SiteOrigin Page Builder and Elementor.

Is there another way to create a full width single column for content? Is there a single column block that I just overlooked?

**Comment by designsimply** [comment]
Cool, thank you for the explanation! There isn't another way to create a full-width single column currently that I know of, but there's a request at https://github.com/WordPress/gutenberg/issues/4900 for a section block which sounds like it may be what you are looking for.

I will leave this open to ask whether the columns block is intentionally limited to 2+ columns intentionally or if it should be considered a bug.

**Comment by kelsS** [comment]
Thanks for looking into it! :)

**Comment by realworldev** [comment]
See also https://github.com/WordPress/gutenberg/issues/10791

**Comment by gziolo** [comment]
I think this is expected behavior. Columns block should have at least 2 columns. There is now Group block which can be used instead.
