### ISSUE TITLE
After saving, ability to save isn't available until you exit a block

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1240]
The "saved" update status persists after clicking I've edited content, therefore I don't have an easy indicator that I have content that can be saved.

![gutenburg-save mov](https://user-images.githubusercontent.com/622599/27264921-8b5afcdc-5458-11e7-958e-9589fcb8ad21.gif)

**Comment by BE-Webdesign** [comment]
Here is some context: https://github.com/WordPress/gutenberg/pull/1166#issuecomment-308671092

**Comment by annaephox** [comment]
Hey @karmatosed @mtias are you happy with the fix for this? Thanks

**Comment by aduth** [comment]
Closing this in favor of technical proposal in #2758
