### ISSUE TITLE
Not all editor text is translated

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#12407]
**Not all editor text is translated**
Some of the text in the sidebar and top buttons is translated and some of it is not. And the prompt to "Start writing" is translated on a new post and not on an old post.

**To Reproduce**
1. Using WP 4.9.8 and GB 4.5.1
2. Activate the Pig Latin plugin
3. Open the editor
4. See some text is mangled by the plugin, but some text (in sidebar and buttons) is not and should be.

**Expected behavior**
All text that is output by the editor should be affected by the Pig Latin plugin, although since it is done in javascript, I actually expected that none would be affected. This also brings up the question of whether a PHP plugin like Pig Latin will be able to filter translations for javascript in the new scheme.

**Screenshots**
![editay ostpay local current wp ordpr -5731](https://user-images.githubusercontent.com/7957680/49192157-7e2a7100-f33f-11e8-8545-60b31361cb6a.jpg)

![editay ostpay local current wp ordpr -4546](https://user-images.githubusercontent.com/7957680/49192079-1bd17080-f33f-11e8-851b-03f31d86b0ad.jpg)

**Comment by swissspidy** [comment]
Related: #12517, https://core.trac.wordpress.org/ticket/45425

**Comment by mtias** [comment]
@swissspidy unsure if there is anything pending here?

**Comment by swissspidy** [comment]
I think this can be closed
