### ISSUE TITLE
Gallery doesn't update

### ISSUE THREAD

**Issue by vrundakansara** [WordPress/gutenberg#12410]
**Bug Description**
In the Gallery Block, when I update pictures of gallery the second time, they do not get updated in the list of images in Media Uploader.

Here is a video showing the issue - https://youtu.be/ZbQLjFj-tvI

**To Reproduce**
1. Add few images to gallery
2. Edit the gallery and some more.
3. Now try adding some more, the images added in step 2 disappears.

**Expected behavior**
Everytime update the media gallery, all the images should retain.

**Video**
https://youtu.be/ZbQLjFj-tvI

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome Latest
 - Version: WP 5.0 RC

**Comment by designsimply** [comment]
Thank you for the report! We are tracking this issue at https://github.com/WordPress/gutenberg/issues/9073.
