### ISSUE TITLE
Preview Button Publishes/Updates Custom Fields

### ISSUE THREAD

**Issue by Kevinlearynet** [WordPress/gutenberg#12419]
**Describe the bug**
The "Preview" button inside of the Gutenberg editor will publish/update custom field values publicly, rather than isolate them to the draft preview.

**To Reproduce**
1. Change the value of a custom field for a published post
2. Click the "Preview" button
3. Open an Incognito window with the public post URL (not the preview URL)
4. You will see the new custom field value is publicly published

**Expected behavior**
When I click "Preview" changes to custom field values should only appear when the preview URL is viewed. The public, live post should not reflect these changes until the "Update" button is pressed. 

**Desktop:**
 - Mac Sierra 10.12.6
 - Google Chrome 70.0.3538.102

**Additional context**
- Gutenberg Version 4.5.1
- This was originally filed as an issue with ACF, and upon further investigation with Elliot we determined that it is in fact a Gutenberg related issue: https://github.com/elliotcondon/acf/issues/730#issuecomment-442629260

**Comment by Soean** [comment]
>this alters the behavior for the preview button only and reintroduces the current (unfortunate) core behavior of saving metabox meta to the original post for previews. (see https://core.trac.wordpress.org/ticket/20299 -we can resolve this when we introduce meta revisioning to core)

source: https://github.com/WordPress/gutenberg/pull/11409#issuecomment-435412160
