### ISSUE TITLE
Hello Dolly isn't visible on gutenburg page

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1241]
<img width="433" alt="screen shot 2017-06-18 at 6 54 01 pm" src="https://user-images.githubusercontent.com/622599/27264883-8d1dcb22-5457-11e7-9e3b-c1d549e6c39b.png">

The page thus lacks symbolism towards the hope and enthusiasm of an entire generation

**Comment by aduth** [comment]
Context: https://github.com/WordPress/gutenberg/pull/1050#issuecomment-307555378

**Comment by jasmussen** [comment]
I think it may be time to retire that area for Hello Dolly. I want to thank the plugin for its service, and bid it farewell. 💓

Opened #1352 to further discuss which areas of the editor should be be available to plugins.

**Comment by aaronjorbin** [comment]
@jasmussen I have to disagree.  It's very confusing for something to work on all pages in WordPress, but for it to be completely broken on one page. 

Hello Dolly has served as the first introduction to plugin development for many in WordPress.  

What is the benefit to breaking it, which is how Gutenberg currently works?

**Comment by jasmussen** [comment]
I hope I didn't come off as dismissive or sarcastic in my closing this ticket, that was certainly not my intention. Just clarifying that, and wanted to also note that I'm glad this came up, and 

And no, there is no specific _benefit_ that I can point to, for breaking this change, and would point out that it's a side effect. The thing is, Gutenberg is not only a total redesign for the editor page layout, but also an all-JS application, and so <a href="https://wordpress.slack.com/archives/C02QB2JS7/p1492292520727834">backwards compatibility</a> is something we should evaluate on a case by case basis, primarily to make sure that the areas we make pluggable are indeed ones we want future plugins to use. 

In #1352 we are looking at how plugins that add metaboxes, but are written in PHP, can plug into the new editor in a transitional capacity, and what other areas we need to open up. 

> Hello Dolly has served as the first introduction to plugin development for many in WordPress.

I understand that, and in fact I would hope that for Gutenberg we can provide a new "Hello World" _block_ to serve the same purpose for the editor. Perhaps it could indeed be a "Hello Dolly" block?
