### ISSUE TITLE
Paragraph block: Pasted text shown in browser console

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#12413]
**Describe the bug**
I am use Paragraph block, paste the text in block, see issue

**To Reproduce**

1. First Open Your Console
2. add Paragraph block
3. Paste text in block

**Screenshots**

![issue](https://user-images.githubusercontent.com/45058029/49215694-5c88c280-f3ef-11e8-86bd-a6ca592151c0.gif)

**Editro.js**

![issue](https://user-images.githubusercontent.com/45058029/49216168-67902280-f3f0-11e8-8ac6-47b1ef79226d.png)

**Desktop (please complete the following information):**

OS: Linux
Browser Chrome
Version 69.0.3497.81

**Additional context**

Gutenberg: latest from master
WordPress: 5.0-RC1-43946

**Comment by swissspidy** [comment]
Hi there!

What you see in the console are not errors but instead useful debug information when pasting text.
