### ISSUE TITLE
Remove gutenberg_filter_oembed_result() function

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#12428]
Most of the functionality of `gutenberg_filter_oembed_result()` has been ported to WordPress 5.0 already a while back, see https://core.trac.wordpress.org/ticket/45142.

Only support for classic embeds is currently lacking (see https://core.trac.wordpress.org/ticket/45447), although it doesn't seem to work in Gutenberg either.

**Comment by paaljoachim** [comment]
Is this issue still relevant?

**Comment by swissspidy** [comment]
Looks like the function has been removed a long time ago.
