### ISSUE TITLE
Column Block only shows as a single Column

### ISSUE THREAD

**Issue by BabyTommy** [WordPress/gutenberg#12427]
**Describe the bug**
No issues prior, and no settings changed but suddenly, all instances of the coloumns block apear as only a single coloumn throughout my site, even though in the editor they are set to 2 and apear correctly.

This bug is effcting my entire site... 20+ pages and posts... if you'd like to see for yourself it's (warning: This site is ADULT) http://babytommy.me

I believe what is happening is that it's stacking the columns like it's ment to on mobile, only on desktop.

How it's ment to look (In Editor)
![b0f8e5adda26c7990b25f4e7a0187ddf](https://user-images.githubusercontent.com/43724054/49232107-3b25d780-f3eb-11e8-9488-e7e1e01b9e8f.png)

How it looks on all browsers
![65d21f8ef77723005692933f72ff2275](https://user-images.githubusercontent.com/43724054/49232086-319c6f80-f3eb-11e8-87ba-5d10f83d8e18.png)

**To Reproduce**
simply add a 2 coloumn block in

**Expected behavior**
It was working correctly yesturday, and was showing 2 coloumns

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser All

**Additional context**
- Please add the version of Gutenberg you are using in the description.
4.5.1
I have just checked this issue on defferant themes and it persists, not it's not a themeing problem
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by BabyTommy** [comment]
Found the problem... it seams there's a conflict with my galler addon

**Comment by designsimply** [comment]
Aha! I was just reviewing this and about to ask if the theme could have had any recent updates. Thank you for the follow-up and may I ask which gallery add-on was the source of the trouble for reference?

**Comment by BabyTommy** [comment]
> 
> 
> Aha! I was just reviewing this and about to ask if the theme could have had any recent updates. Thank you for the follow-up and may I ask which gallery add-on was the source of the trouble for reference?

NextGEN Gallery
