### ISSUE TITLE
RangeControl: add tick marks to the track when snapping is enabled

### ISSUE THREAD

**Issue by davewhitley** [WordPress/gutenberg#12429]
**Is your feature request related to a problem? Please describe.**
The default styling of the track of the RangeControl can be misleading. It looks like a continuous slider, but the slider actually has discrete steps that it "snaps" to.

**Describe the solution you'd like**
Adding a visual indication, like tick marks, would set the expectation that there are steps on the track. This tick mark would be an option in the component.

![artboard](https://user-images.githubusercontent.com/618551/49233098-da7ea680-f3ba-11e8-8d9a-be919923715a.png)

**Comment by marekhrabe** [comment]
This looks like a good idea! I'm not sure about the particular style - isn't it too subtle? On my low-brightness display (saving energy! 😅), it's barely noticeable.

**Comment by karmatosed** [comment]
I like the little tips, let's start with those and take from there.

**Comment by Mamaduka** [comment]
I think we can close this one as PR #19916 introduced a similar feature.
