### ISSUE TITLE
Text block: Failures when using shift+enter for adding line breaks

### ISSUE THREAD

**Issue by westonruter** [WordPress/gutenberg#1243]
TinyMCE in WordPress presently requires that you use shift+enter to add a single line as opposed to adding a paragraph. Having this engrained into my muscle memory (though I realize a simple `enter` creates a single line break now, I was trying the same in the Text block only to encounter a couple issues:

1) When typing `First<shift+enter>second<shift+enter>third` there are three lines appearing in the block as expected, but the up arrow only allows me to to go up to the second line; it does not allow be to go up to the first line.

2) When switching to the Text tab, every line other than the first is lost:

```html
<!-- wp:core/text -->
<p>First</p>
<!-- /wp:core/text -->
```

**Comment by youknowriad** [comment]
The current text block is meant to contain only a single `p`. We probably should catch `shift+enter` and avoid creating new `p`s
