### ISSUE TITLE
RangeControl: input field should be focused when thumb is pressed

### ISSUE THREAD

**Issue by drw158** [WordPress/gutenberg#12433]
**Is your feature request related to a problem? Please describe.**
When the thumb of the range control is clicked, the user can use the arrow keys to move left/right. The input field should also be focused, allowing the user to type in a number.

**Describe the solution you'd like**
After clicking on the thumb (the circle), the user should be able to use the arrow keys or type in a number. This means that both the thumb and the input field would be selected, and the user can choose either to use arrow keys, or type in a number.

![artboard copy 2](https://user-images.githubusercontent.com/618551/49236332-83c89b00-f3c1-11e8-97b6-a40ad92a3e35.png)

**Comment by chrisvanpatten** [comment]
(There's an accessibility factor to consider here too since it's dealing with keyboard interaction and focus.)

**Comment by afercia** [comment]
Focus can't be on two inputs at the same time. To make things a bit more complicated, the visible `<label>` element is associated to the `range` (click on it, range get focused) while the input has only an `aria-label` attribute. I'd lean towards closing this issue, as there's now #14166 which aims for an overall audit the RanceControl component. Please do feel free to join the conversation there.
