### ISSUE TITLE
RangeControl: add solid color to left side of track

### ISSUE THREAD

**Issue by davewhitley** [WordPress/gutenberg#12432]
**Is your feature request related to a problem? Please describe.**
The current range slider design is not ideal, because it can be difficult to see where the thumb is at a glance. The component is also limited because in the future you may need to have 2 thumbs and adjust the min and max range.

![screen shot 2018-11-29 at 9 36 30 am](https://user-images.githubusercontent.com/618551/49234326-73aebc80-f3bd-11e8-86d2-6ef9e3cc95d8.png)

**Describe the solution you'd like**
The left side of the track should be colored.

![artboard](https://user-images.githubusercontent.com/618551/49234518-c9836480-f3bd-11e8-9dfb-7cbf6610b9c7.png)

Better yet, it should be colored blue to distinguish itself from a disabled state in the future (not sure if there is a disabled state currently).

![artboard copy](https://user-images.githubusercontent.com/618551/49234566-e881f680-f3bd-11e8-890f-8665ba9119fa.png)

**Comment by paaljoachim** [comment]
I just checked and the left side of the Columns slider has a blue color.
I believe we can close this issue. If that is a mistake then please reopen.
