### ISSUE TITLE
Unexpected block validation error with unescaped ampersands

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#12448]
**Describe the bug**
I have a block with a save function identical to the HTML block. When the block contains one **unescaped** ampersand and one **escaped** ampersand, validation fails after updating and refreshing. 

This is a simple description to illustrate the issue. Since people will likely paste into this block, we could very well end up with a mix of escaped and unescaped ampersands.

I've used the HTML block to demonstrate this since the issue happens there too. The issue does not occur if both ampersands are unescaped...

![screenshot](https://duaw26jehqd4r.cloudfront.net/items/0H1M3f1i2k3B2f1F0Q0s/Image%202018-11-29%20at%202.19.20%20PM.png?X-CloudApp-Visitor-Id=3060697&v=d177020c)

This is the result after updating and refreshing...

![screenshot](https://duaw26jehqd4r.cloudfront.net/items/1e2z071C3C182X2V0x0H/Image%202018-11-29%20at%202.32.15%20PM.png?X-CloudApp-Visitor-Id=3060697&v=bfa5f249)

**To Reproduce**
1. Add an HTML block.
2. Add a **h2** tag with an unescaped ampersand.
3. Add a **p** tag with an escaped ampersand.
4. Update and refresh the page.

**Expected behavior**
The block should be valid.

**Desktop:**
 - OS: OSX 10.14 
 - Browser: Chrome
 - Version: 70.0.3538.102 

**Additional context**
- WordPress 5.0 RC1

**Comment by fastlinemedia** [comment]
Is there anything I can do to help move this forward? I know everyone is super busy :) 

For my use case, I'd be fine with overwriting with the expected markup. We want raw HTML without any kind of validation issues for this block. It's very similar to the HTML block. 

It looks like #12708, #10444, #8166, and others might be working towards addressing this but it would be nice if the user didn't have to worry about that. They just want the block to work without a scary warning :)

FYI, the markup in my example above saves/validates fine on the first try but breaks once the page is reloaded.

Thanks!

**Comment by fastlinemedia** [comment]
Following up with an example that was sent in to us. Notice the use of `&` and `&amp;` in the screenshot below. When those are present together in a block like the HTML block, you get the invalid content error...

![screenshot](https://duaw26jehqd4r.cloudfront.net/items/0W3n2J3X2b3b1a2G213G/Screen%20Shot%202019-01-07%20at%205.37.45%20PM.png?X-CloudApp-Visitor-Id=3060697&v=49db9ac2)

**Comment by aduth** [comment]
I have a pretty good sense of what's going on here. It's an issue within [`IdentityEntityParser`](https://github.com/WordPress/gutenberg/blob/17481452f981effd758751c08250f2b819c00042/packages/blocks/src/api/validation.js#L156-L176) implementation in the validator, where it's attempting to evaluate as an entity the following string:

```
'& Test</h2>\n<p>Test &amp'
```

(The segment of text between an opening `&` and terminating `;`)

Note that this only seems to affect strings where there's a plain ampersand and at some point later in the same markup string an encoded entity.
