### ISSUE TITLE
Saving Meta Data Via Sidebar

### ISSUE THREAD

**Issue by squibbleFish** [WordPress/gutenberg#12445]
Looked in a few places for this and only saw something similar in #7535 . 

While the UI is working as expected, I keep hitting an issue where on save and publish, I'm getting an error from the API response saying `code: "rest_invalid_param", message: "meta.section_nav is not of type array.", data: {status: 400}`

I've registered my meta for a single field called `section_nav`. Now obviously, I can set different meta fields for each one, but I'm really hoping to just send a single object and store that properly. The best way for me to do this I guess, would be to watch for the save or publish and just stringify the whole thing since `register_post_meta` doesn't allow for `object` as the `type`. Is there a way to do this? I was noticing that there is a `isSavingPost`, but from what I can see, I don't believe this would actually allow me to stringify the meta before the request is sent. Looking for something similar to the `save_post` action or a clean way to save my meta object in one single meta field.

**Comment by squibbleFish** [comment]
Looks like I may have figured out an interesting workaround where in the `withDispatch` call, I can just `JSON.stringify` the object after doing a quick merge of the object. From there in `withSelect` I need to `JSON.parse` the object so it can be passed in back to my `props` in my component. With that said, would still be awesome to know if this could be done prior to the save event.

**Comment by youknowriad** [comment]
Sorry for the late response @squibbleFish, yes we recommend a similar workaround for advanced meta fields (see https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-attributes/#considerations ) 

I remember seeing a Core Trac issue to allow JSON or object types in meta.
