### ISSUE TITLE
Adding a new tag without using the "enter" or "return" key doesn't add it to post like classic editor does

### ISSUE THREAD

**Issue by alisterscott** [WordPress/gutenberg#12450]
**Describe the bug**

In the classic editor if you add a new tag to a post and don't hit return or add it still saves it against the new post:

![classic editor](https://user-images.githubusercontent.com/128826/49269697-f9139900-f4b1-11e8-855c-6270a092ed56.gif)

In Gutenberg any tag entered without enter or return is discarded

**To Reproduce**
1. Go to Gutenberg editor
2. Open document settings and tags
3. Enter a new tag text "example" don't hit enter or return key
4. Publish
5. View resulting post

**Expected behavior**

Post should be tagged as per classic editor

**Screenshots**

![g editor](https://user-images.githubusercontent.com/128826/49269747-47c13300-f4b2-11e8-83f5-cca5ed672586.gif)

**Desktop (please complete the following information):**

Chrome 70 on macOS Mojave

**Comment by swissspidy** [comment]
> In the classic editor if you add a new tag to a post and don't hit return or add it still saves it against the new post:

Honestly I did not know about this and it feels more like a bug than anything else to me.

**Comment by alisterscott** [comment]
> If someone adds some text there and forgets about it, they might add a new tag by accident.

The difference is wp-admin has a "Add" button whereas the Gutenberg UI assumes the user is going to know to hit enter or return to add the tag, and won't warn them if they don't.

**Comment by alisterscott** [comment]
Using the tab key after entering a new tag doesn't add the tag either:

![tag tab](https://user-images.githubusercontent.com/128826/49356864-e64ecd80-f718-11e8-8103-1f079b66869b.gif)

**Comment by gziolo** [comment]
In my opinion, it's won't fix as you get visual indicators that posts should be updated once a new tag is added. It won't let you leave the page without confirming that you have unsaved changes:

![Screen Shot 2019-05-23 at 14 17 38](https://user-images.githubusercontent.com/699132/58252126-a7174600-7d65-11e9-9663-9423a1aaa75c.png)
