### ISSUE TITLE
[localization feature] Chinese users need "text-indent:2em" style in some paragraph

### ISSUE THREAD

**Issue by conanliuhuan** [WordPress/gutenberg#12451]
**Describe the solution you'd like**
Chinese users need "text-indent:2em" style in some paragraph, paragraph block need an option to enable this feature.
Most Chinese paragraphs has this style, but not all. If once enabled, keep it be a default option when type the ENTER button.

**Describe alternatives you've considered**
I've tried to add a special class to the paragraph, for example: "text-indent-2em", then I add a custom style:
.text-indent-2em {text-indent:2em;}
This alternative need I copy the class and paste it to every paragraph when I use the ENTER button while I am writting a article. **If once enabled, It's BEST to keep it be a default option when type the ENTER button**

**Comment by swissspidy** [comment]
We could probably add a text indention attribute to the paragraph block since we also have drop caps already. But perhaps it could also be plugin territory.

**Comment by conanliuhuan** [comment]
> We could probably add a text indention attribute to the paragraph block since we also have drop caps already. But perhaps it could also be plugin territory.

I am developing a WordPress theme, is there any way to extend the current paragraph block with that option? I can't find any solution on the gutenberg handbook.

**Comment by kjellr** [comment]
I do think this could be an option. Here's a quick mockup: 

![Frame 2](https://user-images.githubusercontent.com/1202812/56601001-0697ff80-65c8-11e9-97bf-ef8348942182.png)

![Frame 2 1](https://user-images.githubusercontent.com/1202812/56601000-0697ff80-65c8-11e9-8149-8a407ef09d21.png)

One question though — do we want to allow users to indent _and_ add a drop cap? Or should it be one or the other?

**Comment by karmatosed** [comment]
> One question though — do we want to allow users to indent and add a drop cap? Or should it be one or the other?

For me, if you have indent you should allow drop cap also. I can't see it being the most common use case but it shouldn't block.

**Comment by mapk** [comment]
When using Google docs, I've had to add the indent myself. But as I create a new paragraph, the indent was automatically applied. If I didn't want it, I just removed the indent in the margin setting ruler. Here's an example of my experience.

![indent](https://user-images.githubusercontent.com/617986/61313364-2564f700-a7af-11e9-9c88-67f4cf0a5705.gif)

I wonder if we could do something similar. If the user adds an indent to their first paragraph, the next one created will also have an indent.

**Comment by mapk** [comment]
After discussing this in the [Design Team slack today](https://wordpress.slack.com/archives/C02S78ZAL/p1579627877061200), we felt this setting would align better in the Document setting sidebar or in the Options popover. 

This is because we feel if the user wants this setting, it would be applied to all Paragraph blocks in the document and so shouldn't be an individual block setting.

**Comment by ibdz** [comment]
https://github.com/WordPress/gutenberg/issues/12451#issuecomment-485890302
This mockup from @kjellr looks good to me.

I think this setting should be an individual block setting to get along with Drop Cap setting that applies to an individual block. In some Asian language, an indentation may need for some paragraph, not every single paragraph.

Applying the first-line indentation for all Paragraph blocks might lead to the complexity of turning off in some Paragraph block. However, it is possible to add a first-line indent option for all Paragraph blocks setting in Global Styles.

**Comment by MichaelArestad** [comment]
> This mockup from @kjellr looks good to me.

I agree. I think we could move forward with that.

> One question though — do we want to allow users to indent and add a drop cap? Or should it be one or the other?

It's unlikely folks would need both, but might be the simplest to implement so lets go forward with that.

> I wonder if we could do something similar. If the user adds an indent to their first paragraph, the next one created will also have an indent.

Super clever. If easy to do, I think that's a great idea. I don't think it's a blocker.


I think we can say this is ready to be implemented based on what I see. Nice work.

**Comment by jordesign** [comment]
Closing this issue as a duplicate - in favour of https://github.com/WordPress/gutenberg/issues/37462
