### ISSUE TITLE
Gutenberg: Display of the drop cap is blocking some texts...

### ISSUE THREAD

**Issue by blessedOn** [WordPress/gutenberg#12468]
**Describe the bug**

I have noticed that after using the “Gutenberg: Display of the drop cap”, Some letters appear a bit larger and are actually blocking texts below or to the top of them. See the link attached. I am using Gutenberg Version 4.5.1

**To Reproduce**
1. Go to 'https://fr.kongotimes.info/2018/11/25/jean-lucien-bussa-hier-opposant-aujourdhui-fcc-ou-est-le-serieux/'
2. See error on the introduction of the article with the "J" letter appearing really larger and blocking some texts bellow it.
3. Same error was also reproduce  in wordpress.org/gutenberg/ demo. Check this link: https://imgur.com/Td4eo39

**Expected behavior**

I expected it to be displayed properly without blocking texts below it. We have countless page with similar bug from Gutenberg. 

FURTHERMORE, the effect can be reproduced in wordpress.org/gutenberg/ demo with Google Chrome. Firefox seems to work fine.

**Screenshots**

1. Check this link: https://imgur.com/Td4eo39

![td4eo39](https://user-images.githubusercontent.com/1119271/49296913-b1235080-f476-11e8-914a-b4752facfe5e.png)

**Desktop (please complete the following information):**

 - OS: macOS Mojave, version 10.14.1
 - Browser tested on: Chrome, Safari and Firefox. 
 - Version: the latest versions of the above browsers.

**Smartphone (please complete the following information):**

 - Device: Samsung S8
 - OS: Oreo (Android 8.0.0). Release on 30/10/2018
 - Browser: chrome
 - Version: latest version

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.6 using Chrome 70.0.3538.110 and Safari 12.0.1 on macOS 10.13.6.

![screen shot 2018-11-30 at 8 09 59 am](https://user-images.githubusercontent.com/1119271/49297179-648c4500-f477-11e8-9053-b7a20be4e70b.png)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=247&action=edit running WordPress 4.9.8 and Gutenberg 4.6 using Chrome 70.0.3538.110 on macOS 10.13.6.</sup>

I did not see the same problem in Firefox ([screenshot](https://user-images.githubusercontent.com/1119271/49297444-0449d300-f478-11e8-9384-0d07bd51a5db.png)).

**Comment by blessedOn** [comment]
@designsimply

I have tested this myself, as I said on my ticket; on chrome, safari and firefox. Only in Firefox seems to work fine, and not on Chrome and Safari. It is obviously a bug in Gutenberg that should be addressed and fix.

@herbie888, from Support » Plugin: Gutenberg » on wordpress.org, in his reply to my ticket said that _**the effect can be reproduced in wordpress.org/gutenberg/ demo with Google Chrome. Firefox seems to work fine.**_ Again, you can clearly understand that this is a bug in Gutenberg.  

It should be displaying/working fine in all browsers.

**Comment by karmatosed** [comment]
This looks like it's only a few letters such as 'J' and 'Q'. For example:

![2018-11-30 at 16 38](https://user-images.githubusercontent.com/253067/49302262-89f07180-f4be-11e8-9619-41483970515e.png)

![2018-11-30 at 16 39](https://user-images.githubusercontent.com/253067/49302291-9aa0e780-f4be-11e8-9594-0346c6d9373c.png)

**Comment by blessedOn** [comment]
Hi @karmatosed

It is also happening with French accented letters like: À l'école-French or Élevé. The "À" with accent is even blocking some texts from the article title. Try it and you'll see the results. Put that "À" or "É" with accent at the beginning of the paragraph and apply drop cap.

**Comment by thehenrybyrd** [comment]
Ran into this while testing something else - I was able to reproduce with Q, Ą, and Á. 
Á takes too much space up top. This is from within the editor.

![aqA](https://user-images.githubusercontent.com/15107387/57226962-dbc29800-7018-11e9-8ac4-337153c757fc.png)

It looks a _little_ better when published (different font), but really still needs more space:
<img width="560" alt="Screen Shot 2019-05-06 at 4 05 52 PM" src="https://user-images.githubusercontent.com/15107387/57226986-ef6dfe80-7018-11e9-816a-7fb466a76566.png">

Tested in Chrome with WordPress 5.1.1.

**Comment by blessedOn** [comment]
Hi there

Is this issue I reported for several months ago resolved? I read your
replies but I do not see any indications that confirm that the matter has
been resolved.

Le lun. 6 mai 2019 à 14:08, thehenrybyrd <notifications@github.com> a
écrit :

**Comment by designsimply** [comment]
@blessedOn it has not been resolved yet. I will add the `Good First Issue` label to see if it helps surface someone who would like to work on it, however, I should also note that issues are often worked on in terms of severity and project planning and if an issue doesn't fit into those areas then it could take some time before it is resolved.

**Comment by jorgefilipecosta** [comment]
This issue was fixed and should not be happening on the last WordPress release.
