### ISSUE TITLE
Export BlockEditContextProvider to wp global to make it avaliable to embedded components

### ISSUE THREAD

**Issue by JasonHoffmann** [WordPress/gutenberg#12476]
**Is your feature request related to a problem? Please describe.**
It may be useful for developers creating custom blocks to have access to the BlockEditContextProvider created here https://github.com/WordPress/gutenberg/blob/ce8f61d187f44ef71f3292a56c3cd35584c822dc/packages/editor/src/components/block-edit/context.js. This stores useful information about the block, most importantly the clientId, which is available in an edit component, but needs to be passed down to each child component through props without access to the Context.

As an example, you may have an edit component like this (pseudo-code):

```
import TextFieldComponent from './textfield';

class SampleEdit extends Component {
	render() {
		return(
			<TextFieldComponent
				content={ this.props.attributes.content }
				clientId={ this.props.clientId }

			/>
		)
	}
}
```

Then our TextFieldComponent would look like this:
```
class TextFieldComponent extends Component {
	render() {
		...do something with, for instance, this.props.clientId
	}
}
```

In this example I would need access to the clientId in the nested component to, for instance, automatically grab attributes or select various kinds of data with `wp.data`. In the current model, I need to always pass down the clientId, or other data from the Context API, as props. This makes the components far less shareable and resuable. It would be nice if the BlockEdit Context Consumer was made available so I could instead do something like:

```
const { BlockEditContextProvider } = wp.element;

class TextFieldComponent extends Component {
	render() {
		<BlockEditContextProvider>
			{ ( context ) => (
				...do something with context.clientId
			) }
		</BlockEditContextProvider>
	}
}
```

Making it much easier to pull and manipulate the context of the current block, even for components that are nested underneath the `Edit` component. The idea would be to make it easier to understand your current block context from _any_ component, which would allow for very reusable components that can be shared across blocks and projects. It would allow developers to take advantage of the Context API currently used internally inside of Gutenberg. 

**Describe the solution you'd like**
I think all that would need to happen is for the `BlockEditContextProvider` to be exposed to a wp global like `wp.element`.

**Describe alternatives you've considered**
The only alternative is to create a second context inside of the main Edit component and then use that inside of all of the nested components. However, this is basically just duplicating context and can be a bit redudant. In the above example, the Edit component would look like:

```
const { createContent } = wp.element;
export const Context = createContext({
	clientId: '
});

import TextFieldComponent from './textfield';

class SampleEdit extends Component {
	render() {
		return(
			<Context.Provider value={{ clientId: this.props.clientId } }>
				<TextFieldComponent
					content={ props.attributes.content }
					clientId={ props.clientId }
				/>
			</Context.Provider>
		)
	}
}
```

And then the nested blocks would each have to import that newly created context and use the Consumer.

I'm not sure if this has been considered, or if there is something more complicated that I'm missing, but I didn't see any issues about it and I think exposing the `BlockEditContextProvider` to custom blocks outside of core would empower a lot of developers.

**Comment by lassemt** [comment]
Thanks for creating a issue on this. I find it a bit weird that this isn't implemented already.

I believe all that is needed for this to work is to add `export * from './block-edit/context';` (not tested) to [this file](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/index.js) for `BlockEditContextProvider ` to be available in wp.editor. Then `withBlockEditContext` and  `ifBlockEditSelected` also will be available.

Looking at how BlockEdit context is already used in gutenberg I can tell using the Higher Order Component `withBlockEditContext` is the preferred way (I might be wrong). So here is an example on how BlockEdit context can be implemented if `withBlockEditContext` will be available:
```
const { Component } = wp.element;
const { compose } = wp.compose;
const { withBlockEditContext } = wp.editor;

class TextFieldComponent extends Component {
  constructor() {
    super( ...arguments );
  }

  render() {
    // Yay, clientId is available
    const { clientId } = this.props;
  }
}

TextFieldComponent = compose(
  withBlockEditContext( ( context ) => pick( context, [ 'clientId' ] ) )
)(TextFieldComponent);

export default TextFieldComponent;
```

 Currently as temporarily solution, I pass down the clientId to the component.

**Comment by youknowriad** [comment]
I think we shouldn't rush exposing these yet as the content of this context and HoC might change as we improve the editor. For now I'm considering these implementation details.

that said, it's very easy to create your own context and your own consumer using the `clientId` prop passed to the `edit` function of your blocks.
