### ISSUE TITLE
[Convert to Blocks] not working - Updating custom blocks

### ISSUE THREAD

**Issue by spwebguy** [WordPress/gutenberg#12475]
Hi everyone,

I've been creating a few simple blocks (plugin development). It all works fine, I can use my blocks, edit them, preview them.

My issue is that whenever I change something in the code, say the **save()** function in the block registration, it will throw an error, as you can see on this first screenshot.
![1](https://user-images.githubusercontent.com/8936613/49302269-8d83f880-f4be-11e8-869d-8455b8aa73d0.png)

I understand this happens because the block's structure changed, which makes perfect sense. But when I click *Resolve*, and pick *Convert to Blocks* (second screenshot), it all becomes HTML.

![2](https://user-images.githubusercontent.com/8936613/49302314-ae4c4e00-f4be-11e8-8ceb-b2191b4d05d6.png)

I'm a plugin developer and currently buliding a few blocks, I wondered how in the future I could update my block plugins (including changes to the **edit()** and **save()** functions) without breaking my users' pages.

I've tried searching for this but couldn't find anything. I hope it's clear, I'm not a native English speaker.

Thank you all for your amazing work on Gutenberg. I think it takes WordPress (and website editing in general) to a whole new level.

**Comment by designsimply** [comment]
To summarize: you are trying to create a custom block, update the code, and have "Resolve" + "Convert to Blocks" work to convert back into your custom block and that's not working. Is this correct?

Or is the problem more that you want to avoid the error throwing at all when there's a structure change?

**Comment by designsimply** [comment]
Related: #10444

**Comment by spwebguy** [comment]
Thanks for answering! 

I'd like my users to not have to insert the block again after an update. If _Convert to Blocks_ worked it'd be fine. In this precise case I was adding a new CSS class to an element in the **save()** function. It *invalidated* my block.

**No error** would be nice too. When I update my PHP plugins I always make sure it's compatible and that I'm using the same *keys*/data from the previous version. If I had a new setting for example, I'd make sure it has a default value and that it won't interfere with existing content when people update.

I'd like to do the same with blocks. Currently whatever I change in the code *invalidates* the blocks. 

Let's say I have a card block, I want to add a small text at the bottom of the card. I would add an attribute for it. Users making the update can choose to add some text in the field. If they don't, nothing will be added to the card on the front end. If they do, it will show up. I think there shouldn't need to be an error in this case, as updating the blocks will never cause any issue, because I only added a field/attribute for them to use, the rest is all the same, it can't break.

Same goes for CSS classes. Adding a CSS class to an element in the render function shouldn't *invalidate* a block. In fact nothing should _invalidate_ a block. It's just like ordinary plugins, if the devs are careful and take compatibility into account, everything will work when an update is done.

I don't know if what I say makes sense, I don't want to come here and pretend I have a solution and that the current way of doing things isn't good. I'm just thinking about how I will update my plugins in the future. I don't want to break my users' sites. I want them to click Update and worry about nothing.

Maybe I'm missing something, but for now I don't know how this is possible. If I release an update, I have to re-build my blocks... 

Any help or suggestion is very appreciated! Thank you for your time!

**Comment by designsimply** [comment]
Apologies for not circling back to this sooner. I re-visited this today and found a relevant discussion at https://github.com/WordPress/gutenberg/issues/12162 and am hoping you can hop into that issue as it has a bit more attention and discussion in it so far. It appears you are not the only one facing this problem and I think adding a note in your words about your use case to https://github.com/WordPress/gutenberg/issues/12162 would be helpful or let me know here if you feel your issue should remain open independently and I will re-open.

Thank you for your notes and for using Gutenberg and asking questions about making the block development process go more smoothly!
