### ISSUE TITLE
2 gutenburg / wordpress.com faults

### ISSUE THREAD

**Issue by guylancaster999** [WordPress/gutenberg#12474]
1. inserting a media image (wordpress.com,new Gutenburg editor) in a <table> based, layout sent it somewhere strange on the page, about a week ago
2 Classic editor worked and then it ended up with a writer helper at the bottom but no way to save. I fixed it by leaving Gutenburg! Today

Windows 10
Chrome
chorltonwanderers.wordpress.com is the site

I do not require a fix as i have a workaround for both

**Comment by designsimply** [comment]
> inserting a media image (wordpress.com,new Gutenburg editor) in a table based, layout sent it somewhere strange on the page

If you were using the classic block, there was a problem reported where inserted media was getting added to the top of the post unexpectedly reported in #10509 and fixed in #12415. That fix won't show up on WordPress.com immediately and will likely get added to WordPress.com within a few weeks.

Note: the classic block is available in the block editor and is different from switching back to the classic editor and it's good to be aware of that difference in the case of this bug report.

**Comment by guylancaster999** [comment]
Hi

I had lots of

<tr><td><img........><?td>
<td>Text....</td>
</tr>


I add added an img from the media library and it didn’t drop it in the right place.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by designsimply** [comment]
> Classic editor worked and then it ended up with a writer helper at the bottom but no way to save. 

I tried testing by enabling Gutenberg on a WordPress.com site and then opening an existing draft with the "Classic Editor" link below the post on the WP Admin > Posts page. From there, I was able to see a Writing Helper section below the post and I tested the "Save Draft" as well as the "Publish" buttons in the Publish panel at top right and both worked normally in my test.

Can you please write a short list of steps to reproduce this problem on your blog and report them to https://wordpress.com/help/contact ?

**Comment by guylancaster999** [comment]
Ok


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by designsimply** [comment]
> I had lots of
> 
> <tr><td><img........><?td>
> <td>Text....</td>
> </tr>
> 
> I add added an img from the media library and it didn’t drop it in the right place.

Aha, I see. So I think your testing steps would be something like this:

1. Enable Gutenberg.
1. Go to Posts > Add New.
1. Add a table block.
1. Try dragging and dropping an image into a cell in the table.

I found that images may be added to a table by using the "Inline Image" block, see https://github.com/WordPress/gutenberg/issues/9514

That should help with adding images inside a table. For the missing save button, please do report that to WordPress.com support and give them as much information as possible. Thank you!
