### ISSUE TITLE
Autosave: Also save tags and categories

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#12472]
Related to https://github.com/Automattic/wp-calypso/issues/28771

## Context

The original issue reported this:

- Create a new post.
- Add some categories and tags.
- Modify title or content to trigger the autosave.
- Wait for the autosave to complete.
- Open the preview of the post.
- The preview doesn't contain the categories and tags we set earlier.

The reason is that the [autosave doesn't save categories and tags](https://codex.wordpress.org/Revisions#Revision_Storage_Method).

Although, in our initial investigation, this issue only occurred on WP.com, but didn't on WP.org.
It took me a while to figure why.

`PostPreviewButton` under certain conditions performs a full save when opening the Preview:

https://github.com/WordPress/gutenberg/blob/a92216bb6f46a99712aef6124e5cf1a2ea6384a2/packages/editor/src/components/post-preview-button/index.js#L141-L154

On my WP.com site, `isAutosaveable` was always false, and therefore the button early-returned before performing the save.
On the WP.org one, instead, it was always true.

This is because of the `forceIsAutosaveable` prop, set from the parent component:

https://github.com/WordPress/gutenberg/blob/a92216bb6f46a99712aef6124e5cf1a2ea6384a2/packages/edit-post/src/components/header/index.js#L54-L57

And now it became obvious: my WP.org site has meta boxes, while my WP.com one doesn't.

## Doubts and Questions

At first I wanted to propose to perform a full save on Preview in any case, in order to view the correct category, tags, and possibly many more post attributes.
Though, this would be ill-advised, because we don't really want to stealth-save a published post with changes that might not be final yet.

Then I wondered if it was just enough to drop the `isAutosaveable` check, and always perform either a full save on drafts, or an autosave on published.
This would solve the issue for drafts, but not at all for published.

So, assuming I'm not the only one bothered by this issue (well, me and Calypso e2e tests 😄), I'm wondering if it could make sense to extend autosave to also save categories, tags, and possibly other post attributes that might be very obviously missing from the preview.

**Comment by designsimply** [comment]
Noting that #7767 sounds similar and was marked as invalid. For me, it would be nice to clarify the expected behaviors around autosaves and previews for both drafts and published posts:

1. Should an autosave of a draft also save all meta data? (#7767)
1. Clicking Preview for a draft should save all post details, including meta (resolved in #12047).
1. What should happen to the meta data for an autosave of a modified published post? 
1. What should happen to the meta data when Preview is clicked for a modified published post?
1. What is "all meta data"? (title, categories, tags, featured images, custom fields, third-party meta box content?)

Related:

* #7502 - only save metaboxes when it's not an autosave
* #7767 - autosaved preview does not show featured images, categories, or tags (closed as invalid)
* #7927 - "Save Draft" does not save multiple title changes
* #9151 - cannot preview featured image changes (worked on in #12037, #12047, #12097)

**Comment by designsimply** [comment]
cc @adamsilverstein @youknowriad

**Comment by paaljoachim** [comment]
I just tested with Twenty Twenty One theme.
WordPress 5.7 beta version.
On the WordPress Beta Tester plugin is activated.

Followed the testing procedure as mentioned by @Copons 

Create a new post.
Add some categories and tags.
Modify title or content to trigger the autosave.
Wait for the autosave to complete.
Open the preview of the post.
The preview doesn't contain the categories and tags we set earlier.


The preview shows categories and tags that I set.
The following screenshot is a preview based only on Autosave function.

![Screen Shot 2021-02-08 at 20 32 17](https://user-images.githubusercontent.com/5323259/107271617-caf45100-6a4c-11eb-8071-f1d7e6ac068d.png)

It shows the category Books and News. The tags In the sun, Night and Weather.
These were added to the post.

Based on my findings I will go ahead and close this issue. @Copons or anyone else please reopen if there are other concerns that I have missed. I do believe all the issues/PR's @designsimply linked to have either been closed or merged
