### ISSUE TITLE
Explicitly selecting the default style variations from the block styles selector adds the style className (it shouldn't add it)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12496]
**Describe the bug**
I have three Quote blocks. Two are styled as 'Regular' and one is styled as 'Large'.

One of the regular Blocks has an Additional CSS Class as `is-style-default` and the other one doesn't. I never added this class to the block. Why does one block have it and one block doesn't?

![gutenberg_inconsistentclasses](https://user-images.githubusercontent.com/2078245/49325051-b45e2f80-f58f-11e8-836b-446a97b8d668.gif)

On the front-end, the same thing happens. One Blockquote has that class and one doesn't.

![screenshot_258](https://user-images.githubusercontent.com/2078245/49325229-0a80a200-f593-11e8-8805-8773f4f23e54.png)

**To Reproduce**
1. Add Multiple Quote Blocks
2. Check whether Additional CSS Classes are added

**Expected behavior**
Two identical blocks, styled the same, should produce identical code on the front-end, and should display identically in the editor.

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3 (64-bit)
- WP 5.0-RC2-43958
- TwentyNineteen

**Comment by STHLMWebDesign** [comment]
For me, .`is-style-default` is only applied if I switch to the large quote and then switch back to the normal sized quote.

**Comment by maddisondesigns** [comment]
It should either apply this style by default then, or simply remove it when you switch back. Having one with and one without is inconsistent and is likely to cause inconsistent styling on blockquotes on the front-end if someone actually creates styles for the `is-style-default` class.

**Comment by youknowriad** [comment]
Confirmed the issue, it happens everytime you explicitely switch to a style variations marked as `isDefault`. These styles shouldn't be added in that case.

**Comment by youknowriad** [comment]
@adamziel If I'm not mistaken you fixed this recently right?

**Comment by adamziel** [comment]
@youknowriad that's right! In https://github.com/WordPress/gutenberg/pull/22266
