### ISSUE TITLE
RTL style sheets responds with 404

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#12497]
**Describe the bug**
When I select an RTL language, the following styles responds with 404 Not found:
wp-includes/css/dist/block-library/style.min-rtl.css?ver=5.0-RC2-43958
wp-includes/css/dist/block-library/theme.min-rtl.css?ver=5.0-RC2-43958

The actual files in the folder are:
wp-includes\css\dist\block-library\style-rtl.min.css
_Not: style.min-rtl.css_
wp-includes\css\dist\block-library\theme-rtl.min.css
_Not theme.min-rtl.css_

**To Reproduce**
1. Go to Settings, General, Site Language  and select an RTL language, for example arabic.
2. View your site.
3. View console errors.

**Expected behavior**
I expect the style sheets to load correctly.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 70.0.3538.110 

**Additional context**
Version:   WordPress 5.0-RC2-43958
This happens regardless of which theme that is active.
It does not affect the editor, only the front.

**Comment by ocean90** [comment]
Closing as it's a bug in core, see https://core.trac.wordpress.org/ticket/45547.
