### ISSUE TITLE
Blob URL is copied during file upload

### ISSUE THREAD

**Issue by kristarella** [WordPress/gutenberg#12493]
**Describe the bug**
When uploading a file it is easy to copy the temporary path of the file as it is being uploaded. Users may inadvertently link to this file (in other parts of the document) instead of the final file URL.

**To Reproduce**
1. Editing a post or page add a File block
2. Upload a large file
3. Click the Copy URL button 
4. Paste the clipboard somewhere to see what the URL you copied is
5. It's a problem if it starts with `blob:`

If your internet is too fast and your files upload before you can copy the URL you can throttle your speed in Chrome to see this better:
https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions

**Expected behavior**
Copy URL button should copy final file URL to clipboard. Ideally the button should be hidden until that URL is available.

**Screenshots**
GIF recordings (they start with demonstrating similar issues with image block, file block is towards the end)

On WordPress.com:

![gute-file-url](https://user-images.githubusercontent.com/2031017/49324112-d8177a80-f57b-11e8-8e60-2a63cdf90b35.gif)

On WordPress.org:

![gute-file-url-atomic](https://user-images.githubusercontent.com/2031017/49324113-dcdc2e80-f57b-11e8-9bfd-ba0f6e03a695.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 70.0.3538.102

**Additional context**
- Gutenberg version 4.6.1

**Comment by Morgunov-Vitaly** [comment]
I've met the similar issue when uploading video file to the Video block. 
After post publishing - video doesn't play. And it has a URL with "blob": <video controls src="blob:https://..."></video>

**Comment by swissspidy** [comment]
@Morgunov-Vitaly Would you mind creating a new issue for this? Thanks.
