### ISSUE TITLE
editor.BlockListBlock not updating on attribute change.

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#12494]
Hi,

`editor.BlockListBlock` filter is having issue after 4.6.1 updates. It's not updating when there are attribute changes. Is this intentional? If so, do you have any actions that I can use to trigger update on specific attributes. Thanks!

**Comment by youknowriad** [comment]
Can you share how you use this filter? For info #11899 is not included in 4.6.1

**Comment by phpbits** [comment]
@youknowriad I have dropdown option that set's attribute to `wp-block editor-block-list__block`. It's adding 'data-customAttributes' to that div. It's updating before but after 4.6.1 it's only updating the value after save then refresh or select dropdown value then highlights the block content. It doesn't update the changes live anymore.

**Comment by youknowriad** [comment]
Can you share a snippet of your code?

**Comment by phpbits** [comment]
@youknowriad Here's a sample of my code. Let me know your thoughts. Thanks!

```
const withCustomSettings = createHigherOrderComponent(BlockListBlock => {
	return props => {
		const allowedBlocks = [ 'core/paragraph', 'core/heading', 'core/cover', 'core/pullquote', 'core/quote', 'core/button' ];
		let wrapperProps 	= props.wrapperProps;
		let customData 	 	= {};
		let attributes 		= wp.data.select( 'core/editor' ).getBlockAttributes( props.clientId );
		
		if( allowedBlocks.includes( wp.data.select( 'core/editor' ).getBlockName( props.clientId ) ) ){
			if( attributes.customAttr ){
				customData = Object.assign( customData, { 'data-custom-attributes': 1 } );
			}
			
			wrapperProps = {
				...wrapperProps,
				style: applyStyle( attributes ),
				...customData,
			};
		}

		return <BlockListBlock {...props} wrapperProps={wrapperProps} />;
	};
}, 'withCustomSettings');
```

**Comment by youknowriad** [comment]
I think the issue is that you're not using `withSelect` to wrap your component, which means your filter won't get called when the data module values change. I think this was broken anyway, it's just "luck" that it worked as you expected before.

**Comment by phpbits** [comment]
@youknowriad I see. Would you mind letting me know the correct implementation of `withSelect` with my code above? Thanks!

**Comment by phpbits** [comment]
@youknowriad Figured it out :) Seems like I need to create separate function to use `withSelect`. I used this https://github.com/WordPress/gutenberg/blob/459984e0988d7fc0d4dd4e6696ae42f25d9bbbec/packages/edit-post/src/hooks/validate-multiple-use/index.js as reference to create `enhance` :) Thanks!

**Comment by youknowriad** [comment]
Glad you fixed it 👍
