### ISSUE TITLE
"Change Permalinks" instead of "Edit" button on Homepage

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#12498]
Test with Gutenberg 4.6.1 on WP 4.9.8:

On regular posts/pages a click on pagetitle allows editing the permalink of the actual post/page:

![grafik](https://user-images.githubusercontent.com/32030147/49326414-5a8b4480-f552-11e8-9a0e-a1c726296438.png)

But clicking on pagetitle on the Homepage presents a button for "Change Permalinks" at the same position as the "Edit" button on regular posts/pages. But of course with a completely different effect if used!

![grafik](https://user-images.githubusercontent.com/32030147/49326474-e7ce9900-f552-11e8-93d1-72dea9f83c8b.png)

A very confusing and error-prone behaviour of Gutenberg!
(Think of a WordPress beginner who wants to edit the link of the Homepage with this button and uses the "Custom" permalinks setting instead ... and the inserting of the plain linktext in it ...)

**Comment by jorgefilipecosta** [comment]
Hi @mapk, @kjellr, @karmatosed any insights about how we can make the user experience better when the user is editing the homepage and goes to the permalink region?

**Comment by kjellr** [comment]
Oh wow, I don't think I've ever realized Gutenberg did that. As a short term solution, I'd be up for removing the "Change Permalinks" button entirely in this area (as was started in #12500, I think). We already don't show it in the sidebar Permalink panel.

**Comment by mapk** [comment]
I would agree that "Change Permalinks" doesn't make sense in context here, and takes the user to a completely different page. I'm also in favor of just removing that button.

Eventually, when we get to a proper Title block, this whole section in the block will probably get iterated upon. So until then, let's just drop the button completely.

Thanks for the ping, @jorgefilipecosta!
