### ISSUE TITLE
Issues saving background images as editor (and admin) roles on multisite

### ISSUE THREAD

**Issue by carrieforde** [WordPress/gutenberg#12495]
**Describe the bug**
I created and deployed a `Hero CTA` as part of a custom block plugin my company is using on our multisite network. Issues arose when my colleagues with editor status were unable to edit the blocks because the block appeared to be "broken" for them in the edit screen. In a peculiar twist, I was able to resolve the issue, as a Super Admin, but simply resaving the post. I had trouble locking this issue down because it didn't occur to me it was an access issue until I downgraded a colleague from Super Admin to admin for a specific site. When we went to "fix" the issue for one of the marketers, he realized he was having the same issue as them with his reduced access level.

So while we have a workaround for super admins to resave these posts, it's actually making it nearly impossible for the marketing team to edit these banners.

I've tested this with images using `img` tags (both core and custom), and have found teh issue to be limited to blocks using background images--including the cover block.

To confirm it's limited to multisite, I have added the same blocks to a single site (using the same themes, etc), worked with them as an editor, and everything worked as expected.

**To Reproduce**
1. Spin up a multisite & single site installation of WordPress
1. Add an editor role to each instance
1. Add a `core/cover` block to both instances
1. Publish the post on each instance
1. Try editing the post on each instance

The `cover` block _should_ break on the multisite instance.

**Expected behavior**
Editors should be able to save images of all types (`img` and `background-image`) on both single site and multisite instances of WordPress.

**Screenshots**
![example of broken validation](http://files.carrieforde.co/images/2018/bgImage-issue.png)

**Additional context**
- 4.6.1

**Comment by pento** [comment]
It looks like this was related to the old issue of KSES not being aware of the new attributes that the block editor stored in `post_content`.

On single sites, the behaviour described would apply to Author users and below. On multisite, the behaviour would apply to Admin users and below. This was fixed before WP 5.0 was released.
