### ISSUE TITLE
Icons: New icon for paragraph and preformatted

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1249]
Right now we use the same text icon for text, freeform and preformatted:

![screen shot 2017-06-19 at 10 34 57](https://user-images.githubusercontent.com/1204802/27276287-07e86b7c-54db-11e7-8347-0c92d646742c.png)

We should consider renaming Text to "Paragraph", and give it a paragraph icon, like the early mockups:

![screen shot 2017-06-19 at 10 36 17](https://user-images.githubusercontent.com/1204802/27276315-24c629b4-54db-11e7-8aa1-9416cb710c9e.png)

We should also give preformatted a new icon. Maybe one of these? https://developer.wordpress.org/resource/dashicons/#media-code —  CC: @field2 for input.

**Comment by buzztone** [comment]
I feel this issue would be significantly improved by finding more appropriate icons for freeform and preformatted blocks. They definitely need to be different.

**Comment by buzztone** [comment]
I don't feel Paragraph is a suitable name for the Text block.

When I Insert a Text block, I get a series of options in the first drop-down menu that are not paragraphs.

![2017-06-21_01a](https://user-images.githubusercontent.com/1927585/27381382-fdf731ec-56c5-11e7-9fd4-f9749b945ccd.png)

I see Paragraph as 1 of the options in that list though it is the default option & not listed.

A related issue that occurs to me is how does a user change from a Quote back to Paragraph? Perhaps it makes sense to add Paragraph as the default selection option in the first drop-down menu.

**Comment by youknowriad** [comment]
> When I Insert a Text block, I get a series of options in the first drop-down menu that are not paragraphs.

FWIW Te first drop-down menu in the block toolbar is what we call the "Block Switcher". It's a menu to switch to another block. Thus, it's not really options for the current block.

**Comment by jasmussen** [comment]
Yep, that's the switcher component. But I think it might be worth revisiting #493. Going to mock up a thing there.

**Comment by buzztone** [comment]
> Thus, it's not really options for the current block.

Interesting - I'm still a new user at this stage & I was sure the Block Switcher was a drop-down list of options available for the Block type I'd selected.

For me this interpretation was confirmed by the items shown being all html text formatting tags.

**Comment by buzztone** [comment]
> The first drop-down menu in the block toolbar is what we call the "Block Switcher".

Could be helpful for new contributors to add diagram showing terms used by the development team to describe the UI at http://gutenberg-devdoc.surge.sh

**Comment by jasmussen** [comment]
Great point. Will do that.

**Comment by jasmussen** [comment]
Closing as fixed!
