### ISSUE TITLE
Gutenberg with Yoast SEO bugs down my site

### ISSUE THREAD

**Issue by marcusblogger** [WordPress/gutenberg#12508]
**Describe the bug**
After downloading the Gutenberg editor, my site all of a sudden slowed down and would not load my pages within the WP dashboard. I did troubleshoot mode to confirm having Gutenberg and Yoast SEO was the issue. So now I have to go back to using the Classic Editor. Any insight on this? Can't use Gutenberg anymore until compatible with Yoast.

**Comment by GlennMartin1** [comment]
Using 4.6.0 or 4.6.1?

What version of Yoast?

**Comment by designsimply** [comment]
I tested WordPress 4.9.8 and Gutenberg 4.6.1 and Yoast SEO 9.2.1 together just now and I was able to load pages within the dashboard without any problems.

Just to make sure, can you confirm you've updated to Gutenberg 4.6.1? 

If you're already using the latest version of both Gutenberg and Yoast SEO, the source of the trouble in your case could be due to a different plugin conflict or some other reason we're not thinking of yet. You can check for conflicts with other plugins by temporarily deactivating all other plugins except Gutenberg and Yoast SEO and then checking dashboard pages again to see if they are still loading slowly for you or not. If they aren't, then turn each plugin back on one at a time and re-test until you find the source of the trouble.

**Comment by marcusblogger** [comment]
So I dug into Troubleshoot mode again via Health Check plugin and realized my posts in the dashboard open in 3 seconds with no plugins installed vs 9 seconds when I install Gutenberg. So does this boil down to the fact that my theme - Premium Theme: Voyager EvaThemes - is not Gutenberg compatible?

**Comment by marcusblogger** [comment]
Ok, not the theme after all. I used the standard Twenty Seventeen free theme. My posts open in the dashboard within 2-3 seconds. I then download only Gutenberg and the posts take 8-10 seconds to load. I then add Yoast SEO and my posts take over 25 seconds on average to load. 

So just downloading Gutenberg is slowing my internal dashboard significantly and then Yoast SEO and Gutenberg installed together creates very slow posts dashboard to work within.

I use Google Chrome, I again am Using latest version of Wordpress 4.9.8 And Yoast Version: 9.2.1

Gutenberg is a great platform if it wasn't creating these load issues. Any thoughts?

**Comment by GlennMartin1** [comment]
@marcusblogger

What version of Gutenberg?

**Comment by designsimply** [comment]
Thank you for the follow-up information so far. Let's look into Gutenberg performance first.

> In Health Check Troubleshoot mode with nothing installed, I used the standard Twenty Seventeen free theme. My posts open in the dashboard within 2-3 seconds. I then download only Gutenberg and the posts take 8-10 seconds to load.

How you are calculating this (for example, are you using devtools in your browser by chance), and if the load time is 8-10 seconds for every single post or if it varies quite a bit?

May I please also know a little more about the kinds of content you are working with? Are they very long posts with mainly text or are there a lot of media embeds or images or galleries? I'd like to test with testing posts I make but also simulate longer, more similar content such as what you're using. You can get more information about your content by opening a couple of your posts and clicking the (i) at the top. It should tell you how many words and how many blocks. Can you post that info for a couple of the posts where you're having problems with slower loading?

Thanks for reporting this btw!

**Comment by marcusblogger** [comment]
> How you are calculating this (for example, are you using devtools in your browser by chance), and if the load time is 8-10 seconds for every single post or if it varies quite a bit?

Calculating with my Iphone timer app. My posts open in the dashboard right away with nothing installed - I then install just Gutenberg and slows the load time big time. 

My posts are generally long 2000-4000+ word posts with lots of images as it is a sports/travel blog. The site is https://nomadicsportsfan.com/

Let me know what else you might need to help resolve these issues so that I can use Gutenberg again which I really liked working out of @designsimply

**Comment by designsimply** [comment]
Thank you for the extra information. I found that you have opened a duplicate issue at #12627 and also left a comment at https://github.com/WordPress/gutenberg/issues/11782#issuecomment-444655971 and I would like to close that discussion and continue here (and eventually try to consolidate to one open issue when possible).

One thing I think that would help would be to provide sample post content that could be used for testing. I looked around on your site and I think this would be a good example case: https://nomadicsportsfan.com/west-coast-road-trip-seattle-to-la/

The next step will be to wait for testing from someone who can copy (or re-create) a similar post and try testing under similar conditions as you've described.

**Comment by designsimply** [comment]
Labeled as a duplicate because of #11782 which has work ongoing—and it's worth noting that this is something being actively worked on by developers.

**Comment by marcusblogger** [comment]
@designsimply Thanks Sheri. I look forward to the feedback form whoever tests with the content from that post.

As far as the screenshot I included in the other thread, here it is:

> I'm quite interested in seeing that screenshot but it looks like it didn't get linked properly somehow. Can you try uploading it again in a new comment?
![screen shot 2018-12-05 at 2 39 12 pm](https://user-images.githubusercontent.com/45521788/49564602-f9100080-f8d8-11e8-9d1e-68f35483a22e.png)
This is with Gutenberg. Tons of Javascript errors as you see. I then deactivate Gutenberg and it shows no errors in that box. Any troubleshooting for me to do here?

Furthermore, as detailed in other thread, the links do not work for me after embedding with Gutenberg, and then switching to Classic Editor. As you see in this post: https://nomadicsportsfan.com/staples-center-lakers-game-trip-ultimate-guide/
I link to my LA Coliseum post towards the beginning of the post and it just shows the URL with no ability to click. 

Same with spacing issue after switching back to Classic Editor- you will notice a bunch of lines without spacing in between which was present with Gutenberg installed. 

YoastSEO issue: pages that open in 8 secs with Gutenberg only open in 30+ seconds after adding YoastSEO.

Any ballpark insight on developer updates in the works would be helpful for me to decide whether to make overhaul changes with Classic Editor or just deal with issues in short term with Gutenberg for time being.

Thanks for your willingness to respond and to try to help.

**Comment by aduth** [comment]
Related: #12642

This should be fixed primarily by a combination of #12161, #12741. These are available now in Gutenberg 4.7 , and will be slated for inclusion in WordPress 5.0.2 .
