### ISSUE TITLE
Post title: Hovering should show block 

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1250]
This is probably dependant on #1210, but we should treat the post title as a block, even if it isn't a block. 

That is, hovering the title should show the hover style, even if movers won't show up. That is, in the current design, only a left border shows up. In the potential future design, a 1px border (2px on the left) might show up: https://github.com/WordPress/gutenberg/pull/1210#issuecomment-309365293

**Comment by aduth** [comment]
Will this cause confusion around: "Looks like a block, but doesn't act like a block" ?

**Comment by jasmussen** [comment]
> Will this cause confusion around: "Looks like a block, but doesn't act like a block" ?

Well it is a block, it just can't be moved. Which, sure, might cause confusion, but it still feels like the right path forward, so I think this would be a bridge we should cross when we come to it.
