### ISSUE TITLE
Heading Block Hyperlink does not generate href [mailto:] for Email

### ISSUE THREAD

**Issue by ratneshsonar** [WordPress/gutenberg#12507]
**Is your feature request related to a problem? Please describe.**
In Heading Block When I use  hyperlink button to generate href code for email it does not work. 

**Describe the solution you'd like**
Hyperlink button should auto generate code for email like classic editor.

**Screenshot**
Classic Editor detects WEB URL, Email ID and provide code accordingly.

![wordpress](https://user-images.githubusercontent.com/5754380/49331801-da53f600-f5c8-11e8-9fc6-bf0fec8e36fa.gif)

In Gutenberg Paragraph Block easily generate code for email but the Heading Block does not generate code for email

![gutenberg](https://user-images.githubusercontent.com/5754380/49331809-eb9d0280-f5c8-11e8-8ba8-631758752c87.gif)

**System Details**
Desktop
OS: Windows 10
Browser Chrome
Version 72.0.3622.0

**Additional context**

Gutenberg: latest from master
WordPress: 4.9.8

**Comment by desrosj** [comment]
I am not seeing the paragraph block recognize emails.

Here is what I am seeing for behavior in my testing:

**Classic Editor, clicking link on an email address**
![classic-editor-on-email](https://user-images.githubusercontent.com/359867/58812286-86fe4700-85ef-11e9-930e-2767395497fb.gif)

**Block editor, clicking link on an email address**
![block-editor-on-email](https://user-images.githubusercontent.com/359867/58814104-27a23600-85f3-11e9-95c3-7e6c0dfa1fcd.gif)

There was also an inconsistency for this behavior in the Classic Editor that was reported in [Trac-36840](https://core.trac.wordpress.org/ticket/36840). If this is re-implemented in the block editor, this should be taken into account.

When entering an email into the URL field, it does not prepend `mailto:`, causing an incorrect link to be created.

![entering-email-classic](https://user-images.githubusercontent.com/359867/58815694-14449a00-85f6-11e9-85d9-7c038d033038.gif)

**Comment by Zodiac1978** [comment]
I think this is solved by #9774

**Comment by aduth** [comment]
> I think this is solved by issue #9774 and PR #12507 (in Gutenberg 5.5)

The pull request is #14857, but yes, I believe you're correct. The underlying format behavior is consistent between paragraphs and headings, so I expect it should have the same behavior.
