### ISSUE TITLE
Make the Gallery block not use <ul> tags

### ISSUE THREAD

**Issue by STHLMWebDesign** [WordPress/gutenberg#12509]
Does the gallery block have to use `<ul>` and `<li>` elements? It's not correct, a picture gallery is not an unordered list. Plus it creates possible styling conflicts. Gutenberg styles actual unordered lists without any CSS classes. So there is a likely scenario where theme author could style unordered lists by target the parent post container `.post-content ul` in that case this CSS styling risks being passed along to `ul.wp-block-gallery`

I suppose a quick fix would be to make Gutenberg apply a CSS class to both unordered and ordered lists for theme authors to target, but I still have to point out that an image gallery is not an unordered list.

**Comment by swissspidy** [comment]
A gallery is a list of pictures, So I can understand where this is coming from.

The change was made in #3441 to fix #2900, which suggested this change.

> I suppose a quick fix would be to make Gutenberg apply a CSS class to both unordered and ordered lists for theme authors to target

Related: #12420

**Comment by youknowriad** [comment]
As discussed in the previous issue and suggested by the a11y team, the decision for now is to keep the Gallery as a list of images, we can still revisit in the future if needed.
