### ISSUE TITLE
"&amp;nbsp;" is converted to "&nbsp;" when using the link UI

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#12512]
## The issue
When trying to add a link to this string of raw text: `&amp;nbsp;`, the text is converted into `&nbsp;`.

## Reproduction steps
1. Edit a Paragraph block as HTML.
2. Replace the content between the `<p>` tags with the following: `&amp;nbsp;`.
3. Switch back to editing the block visually.
4. Select the entire string of text.
5. Click the Link button in the block toolbar.
6. Enter `#` as the URL and press <kbd>Enter</kbd>.
7. Edit the block as HTML.
8. Notice that the content has been modified and is now `<a href="#">&nbsp;</a>`.

## Expected behavior
After adding a link, the content between the `<p>` tags should be `<a href="#">&amp;nbsp;</a>`.

## Environment
- OS: Antergos Linux
- Browser: Firefox Developer Edition 64.0b14 (also tested in Dissenter Browser 0.68, a browser based on Chromium 76)
- WordPress: 4.9.8 (also tested in 5.2.3)
- Gutenberg: 4.6.1 (also tested in 6.6.0)

**Comment by kcalkmc** [comment]
Testing using WP 5.0, Windows 7, Chrome.
Duplicated reported issue, 

![wp-issue-12512](https://user-images.githubusercontent.com/9540372/49701316-e2bcba00-fbe2-11e8-9aa8-5bd56b2dfdac.png)

**Comment by ZebulanStanphill** [comment]
This has been fixed as of Gutenberg 6.9.0, presumably because of #17994.
