### ISSUE TITLE
To use external Gutenberg Typography?

### ISSUE THREAD

**Issue by AntonNews** [WordPress/gutenberg#12514]
Hi! 
I'm an editor and developer of a small newspaper website. We need to use this typography:
[(https://github.com/typograf)]

I was able to use it to the old TinyMCE editor as an additional plugin. But I don't understand how to use it in Gutenberg. Learning the API does not give me such information. Perhaps someone can give me some answers? 

Sorry for the bad English, I'm from Russia.

**Comment by designsimply** [comment]
Is `[(https://github.com/typograf)]` a custom shortcode? Can you link to the plugin you are using for that?

> I was able to use it to the old TinyMCE editor as an additional plugin.

It is possible the plugin you are using has not yet been updated to work with Gutenberg, and if that's the case then a good step may be to ask them if they are able to update it.

Alternately, if you would like to ask for help in your own language, you may post in Russian at https://ru.wordpress.org/support/ which is a very active forum and has some wonderful contributors!

**Comment by youknowriad** [comment]
Hi there! thanks for the issue. This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
