### ISSUE TITLE
Preformatted block: theme.scss wrong selector

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12520]
While in the editor the Preformatted block is rendered in a container element with a CSS class `wp-block-preformatted` which wraps a `<pre>` element, in the front-end the `<pre>` element itself has the class `wp-block-preformatted`:

`<pre class="wp-block-preformatted">`

However, the `theme.scss` file assumes the markup used in the editor:

https://github.com/WordPress/gutenberg/blob/68367b4b9c869900eca07b9a9b3750ee52915c46/packages/block-library/src/preformatted/theme.scss#L1-L7

This must be changed removing the nested `pre` element selector, pretty much like what is done for the Code block.

**Comment by m-e-h** [comment]
I commented the PR for this but I'm going to put it here as a reminder cause it looks like the same approach should probably be taken for the Code Block as well. And probably in other blocks where the HTML structure of the editor doesn't match up with the front-end.

The editor.css should inherit the properties rather than rewriting them.
```
.wp-block-preformatted { 
	font-family: $editor-html-font; 
	font-size: $text-editor-font-size; 
	color: $dark-gray-800; 
} 

// in editor.css 
pre { 
	font-family: inherit; 
	font-size: inherit; 
	color: inherit; 
}
```
and 
```
.wp-block-code {
	font-family: $editor-html-font;
	font-size: $text-editor-font-size;
	color: $dark-gray-800;
	padding: 0.8em 1em;
	border: 1px solid $light-gray-500;
	border-radius: 4px;
}

// in editor.css
.editor-plain-text {
	font-family: inherit;
	font-size: inherit;
	color: inherit;

	&:focus {
		box-shadow: none;
	}
}
```

**Comment by gziolo** [comment]
> I'm so sorry for dragging this. It's been more than a month and I couldn't find a time so I think it's only fair to let someone else do this. My apologies.

@zzap is no longer working on this issue, so someone else can take it over and continue based on the work done in #12533.

**Comment by youknowriad** [comment]
Looks like there's no theme styles for this block anymore.
