### ISSUE TITLE
Table block: the RichText within the table cells shouldn't have role=textbox and aria-multiline=true

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12525]
For all the usages of the RichText component within the various blocks, Gutenberg uses a `role=textbox` and an `aria-multiline=true` attribute to make the editable field perceived by assistive technologies as equivalent of a `<textarea>` element.

The only exception used to be the Table block: a specific exception was coded a while ago:

https://github.com/WordPress/gutenberg/blob/68367b4b9c869900eca07b9a9b3750ee52915c46/packages/editor/src/components/rich-text/tinymce.js#L356-L364

The rationale behind this exception is:
- all the other blocks editable areas need to be communicated to assistive technologies like a textarea (some doubts were expressed about the List block)
- instead, the Table block needs to keep the table native semantic, and the table cells need to be communicated as editable cells

This worked but the Table block and RichText have seen some refactoring over time and now seems it doesn't work any longer:

![screenshot 2018-12-02 at 17 00 32](https://user-images.githubusercontent.com/1682452/49341918-39ab1800-f654-11e8-92e3-651cc05e0d12.png)

As a consequence, screen readers announce a textarea within a table cell, which is potentially confusing for users:

![screenshot 2018-12-02 at 16 32 54](https://user-images.githubusercontent.com/1682452/49341945-724af180-f654-11e8-944e-cd19bcc855e2.png)

**Comment by iseulde** [comment]
Current behaviour seems fine to me? What do you want to change? You _are_ in a text area in a table cell.

**Comment by iseulde** [comment]
Before the whole table was an editable field, so that makes sense to me.

Currently each cell is a editable field, not the whole table, so it _is_ the same as placing a text area in each cell. They are no different from any other editable field, e.g. a caption. Both are text boxes and multiline.

**Comment by afercia** [comment]
From a semantic perspective and considering how screen readers announce the current semantic, it's not the same thing.

I'm just asking to restore the previous semantics, when the table cells were announced as editable _table cells_. Instead, now screen readers will announce a textarea within a table cell, which is potentially greatly confusing for users. 

This was the only reason why that exception was introduced. Can we please restore a similar behavior? 🙂

**Comment by iseulde** [comment]
But they _are_ text areas in a table cell?

What can we change?

**Comment by iseulde** [comment]
Atm, we cannot have `<td contenteditable>` as there are wrapping elements which would be invalid HTML.

**Comment by iseulde** [comment]
So if we remove the attributes, rows and columns and current position is announced, and that's currently not the case?

> we should not set the role="textbox" on blocks that are completely different from inputs or textareas

The current implementation is the same as putting a text area element inside a table cell, so I don't really get what's different about it.

**Comment by alexstine** [comment]
Is this one still relevant?

```
Body cell text  edit  multi line  ﻿
blank
Body cell text  edit  multi line  column 2  ﻿
Body cell text  edit  multi line  row 2  ﻿
Body cell text  edit  multi line  column 1  ﻿
```

Seems like the table info is still read. Not sure if that would be the case for Voiceover or not, but works well enough for NVDA. 👍

**Comment by Mamaduka** [comment]
@afercia, can we close this issue?

**Comment by afercia** [comment]
> [@afercia](https://github.com/afercia), can we close this issue?

This issue is from 2018, long time has passed since then. I see that on Octobre 2020 https://github.com/WordPress/gutenberg/pull/26582 added some `aria-label` attributes to the `RichText` components used inside the table cella. That is the reason why they are now announced with some meaningful labeling.

https://github.com/WordPress/gutenberg/blob/ed4c2d30cd0ce54c5324353c6e6c13751cf2a17d/packages/block-library/src/table/edit.js#L78-L82

so that for example the editable div element inside a normal table cell is announced as `Body cell text`. Testing with Safari and VoiceOver:

![Image](https://github.com/user-attachments/assets/ed9af921-514a-47d5-ab77-c8b2e0ff74cf)

it announces `Body cell text, edit text`. Noting that without the aria-labels added in https://github.com/WordPress/gutenberg/pull/26582 the cells would have been announced as `edit text`, thus loosing any reference to the table semantics, which was the whole point of this issue.

While the added labeling helps I would argue the _role_ is still wrong but I'm fine with closing this issue as there's now at least some feedback provided to users that they are inside a table cell.
