### ISSUE TITLE
HTML Comments from ServerSideRender is wrapped in p-tags

### ISSUE THREAD

**Issue by Horttcore** [WordPress/gutenberg#12528]
**Describe the bug**
ServerSideRender output with html comments in it breaks frontend
Comments are wrapper in p-tags

**To Reproduce**
```<ServerSideRender block="foo/bar" />```
```register_block_type( 'diez/news-slider', [
		'render_callback' => function(){
			return '<div class="my-test">foo</div><!-- html comment ->;
		},
	] );
```

**Expected behavior**
Comments shouldn't be wrapped in p-tags

**Screenshots**
![image](https://user-images.githubusercontent.com/503252/49344671-fa43f200-f67a-11e8-9de4-6a1e2d515206.png)

**Comment by brandonpayton** [comment]
I created a server-side rendered block with the sample content and am not able to reproduce this.

The screenshot doesn't match the content in the reproduction instructions. Could this be a separate issue?

**Comment by Horttcore** [comment]
@brandonpayton: I'll create a gist one moment please

**Comment by Horttcore** [comment]
@brandonpayton Bug disappeared after update to latest nightly build. Issue is closed.
