### ISSUE TITLE
Plugin: Add a link to GitHub issues

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#1253]
Not all users may have heard where to report problems and send feedback. A feedback/report button somewhere in the interface would help them do that.

**Comment by jasmussen** [comment]
Let's also add a link to the new CONTRIBUTORS.md file, with a big area explaining this is where you should look for who contributed.

**Comment by jasmussen** [comment]
I read the initial ticket as referring to the plugin directory, https://wordpress.org/plugins/gutenberg/ (where incidentally my comment has been addressed). I also added a pinned topic to the forum:  
https://wordpress.org/support/plugin/gutenberg

But now I'm thinking you may have interpreted the ticket better than I did 😉

**Comment by jwold** [comment]
> @jwold yes, exactly that.

Awesome! The design uses a dashicon and the same font size as others, so this should be a pretty straightforward PR. 

The only other thing to figure out then is where to link it to. 

We could do: https://github.com/WordPress/gutenberg

Or we could link to another readme specifically walking them through the steps to opening an issue.

Thoughts?

**Comment by youknowriad** [comment]
we could link to the [new issue](https://github.com/WordPress/gutenberg/issues/new) and add an issue template.

**Comment by jwold** [comment]
> we could link to the new issue and add an issue template.

I like that. 

@karmatosed do you think this is the best approach? I just read what you posted on testing: https://make.wordpress.org/test/2017/06/27/call-for-testing-gutenberg/. Would you prefer the feedback go to a new Github issue or somewhere else?

**Comment by mtias** [comment]
@karmatosed how has the feedback item been doing? Should we just stick with that?

**Comment by karmatosed** [comment]
@matias, yes lets close this for now.
