### ISSUE TITLE
5.0 Welcome Screen Incorrectly States "Trust that your editor looks like your website"

### ISSUE THREAD

**Issue by brianhogg** [WordPress/gutenberg#12538]
**Describe the bug**
Welcome screen for WordPress 5.0 states "Trust that your editor looks like your website" which is not true for many themes without Gutenberg support and editor styles. This should be removed or reworded.

**To Reproduce**
1. Install 5.0 RC2
2. Scroll down a bit past the first hero image

**Expected behavior**
Welcome screen avoids making claims that aren't true depending on the user's theme.

**Screenshots**
<img width="262" alt="screenshot 2018-12-03 06 31 59" src="https://user-images.githubusercontent.com/627497/49371365-42880200-f6c5-11e8-91c5-4a91afad0cd5.png">

**Comment by mtias** [comment]
This should be handled in trac as it cannot be modified here from the plugin.

**Comment by swissspidy** [comment]
What Matias says.

I think one can argue about the truthfulness of this sentence.

In any case, we should be in **string freeze** now in core, which means we try to avoid minor changes like this.

**Comment by brianhogg** [comment]
No problem, trac ticket created here:

https://core.trac.wordpress.org/ticket/45470

I don't think it's a minor change. It's the first impression people are getting of the new editor, we shouldn't be making statements that aren't true for the majority of themes.

**Comment by swissspidy** [comment]
@brianhogg Thanks for creating the Trac ticket. Please note that with "minor changes" I referred to changing a single string in the about being a relatively minor change which causes lots of troubles for polyglots.

**Comment by mtias** [comment]
Thanks!
