### ISSUE TITLE
Preview page ignore page template until page isn't updated

### ISSUE THREAD

**Issue by Dark-Kun** [WordPress/gutenberg#12545]
The bug is pretty simple to reproduce : 

- Go to a page;
- Update the page template
- Before saving, go to preview
- The page is always with the older template

**Comment by swissspidy** [comment]
You should have been shown some content to fill out when creating this issue. These help us better identify the problem.

Most importantly, which version of WordPress and Gutenberg are you using?

Related: #11409

**Comment by swissspidy** [comment]
@Dark-Kun Thanks for the GIF! Which version of WordPress and Gutenberg are you using on that site?

**Comment by Dark-Kun** [comment]
> @Dark-Kun Thanks for the GIF! Which version of WordPress and Gutenberg are you using on that site?

I'm using WordPress 4.9.8 with Gutenberg 4.6.1

**Comment by waviaei** [comment]
I see the similar issue. I think it is same or related, so I report it to here.

1. Add new posts
2. write a title
3 write a paragraph
4. publish
5. add another paragpraph
6. click preview button => preview gets generated, but you don't see the pargraph added at step 5.
7. add some extra text to existing paragrah created at 3.
8. click preview button => preview gets generated, but you don't see the text added at 7, nor the paragraph created at 5.
9. add an image
10. click preview button => preview gets generated, but you don't see the image added in 9. Nor the text added at 7, nor the paragraph created at 5.
11. hit Update button => the post is updated with the all changes I made at steps 5, 7, and 9.

I use: 5.0-RC2-43958
Plugin activated: beta tester

**Comment by designsimply** [comment]
Closing in favor of #12617.

**Comment by designsimply** [comment]
@Dark-Kun I noticed in the gif you included showing the problem that there was an error showing in the console at the bottom right. If you try again and it's still there, can you copy the first line of that error message and paste it into a reply on this issue for reference?
