### ISSUE TITLE
Dispatching editPost action does not save/update existing meta value

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#12544]
**Describe the bug**
Register the following meta:
````
function qqq_register_meta() {
	register_post_meta( 'post', 'test_meta', array(
		'show_in_rest' => true,
		'single'       => true,
	) );
}
add_action( 'init', 'qqq_register_meta' );
````
In a new post editor page, try to update the meta from the console:
````
wp.data.dispatch("core/editor").editPost({meta:{test_meta:"a_value"}});
````
Then publish the post. This will save the meta with no problem (notice the post was new so there was no value assigned to the meta key).

Refresh the just published post editor page from the browser and call editPost again with a different value:
````
wp.data.dispatch("core/editor").editPost({meta:{test_meta:"a_different_value"}});
````
Publish the changes.

The meta does not update and still has the previous value.

Thanks.

**Version**
- WordPress 4.9.8
- Gutenberg 4.6.1

**Comment by swissspidy** [comment]
I think this was fixed in #12331.

Can you try this with the current master build of Gutenberg?

See also #12289 (of which this one is probably a duplicate).

**Comment by alvaro0555** [comment]
Could you point me on how to zip the production version of the branch so I can test?
I tried also merging the meta returned by `getEditedPostAttribute` to the meta object, but the issue is still the same (I thought that was fixed in https://github.com/WordPress/gutenberg/pull/12331).

**Comment by swissspidy** [comment]
You can run `npm run build` and afterwards `npm run package-plugin` to generate a `gutenberg.zip` file that you can upload to your site.

This might take a while, so I went ahead and built a ZIP for you: [gutenberg.zip](https://github.com/WordPress/gutenberg/files/2639731/gutenberg.zip)

**Comment by alvaro0555** [comment]
Thanks, I tested with the zip you sent and the behaviour is the same.

**Comment by alvaro0555** [comment]
Seems like it works right, not sure if the issue was related to the server. I'll close the issue and comment again if I figure out what was causing the problem. Thanks.

**Comment by minimal2** [comment]
I noticed that when custom fields are displayed they overwrite dispatched meta value. 

Tested on WordPress 5.2.2

**Comment by isaquemelo** [comment]
Solved after disabling the custom fields display.

**Comment by mikebhart** [comment]
Disabling the custom fields from been shown solves this problem.
