### ISSUE TITLE
Gutenberg Installation Error - Bad Zip/Code

### ISSUE THREAD

**Issue by thejazzchef** [WordPress/gutenberg#12546]
Installation failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

**Comment by swissspidy** [comment]
Where did you obtain that ZIP file?

Where did you try to upload it?

**Comment by designsimply** [comment]
Try downloading it again. If the error persists, it's possible there's not enough storage space on your web server to be able to unzip and upload the contents of the file. You can test this by trying to upload a smaller zip file, such as a zipped image or small plugin. If the error doesn't happen with a smaller file, check with your web host for help finding out if you need to increase the amount of space available on your web hosting account.

I will close this issue for now and ask you to please re-open if you find that you have enough storage space and are still having trouble.
