### ISSUE TITLE
Corrections to "Start writing or type / to choose a block" 

### ISSUE THREAD

**Issue by bitcoinappdev** [WordPress/gutenberg#12557]
In Gutenberg 4.6.1, when creating a new post, I see the following text:

> Start writing or type / to choose a block

I didn't understand that it meant the "/" symbol at first. Once I figured that out, I was thinking it should read:

> Start writing or type "/" to choose a block

But then maybe people might type a quote, and then a slash, and then a quote. So I revised it to:

> Start writing or type the "/" symbol to choose a block

and then realized it needs a period at the end of the sentence. So, how's this?

> Start writing or type the "/" symbol to choose a block.

Would that be an okay change to put in a PR? Or do you prefer this more concise version:

> Start writing or type "/" to choose a block.

I believe making the prompt grammatically correct with the end punctuation, and the clarity about typing a slash symbol, are both good. What do you think?

**Comment by designsimply** [comment]
Noting this was recently discussed at https://github.com/WordPress/gutenberg/pull/9314#issuecomment-418078580.

Also see https://github.com/WordPress/gutenberg/pull/11560#issuecomment-436737875.

**Comment by benhuberman** [comment]
> Start writing or type the "/" symbol to choose a block.

Looks fine to me -- another option, in case bold styles are possible in UI copy, would be:

> Start writing or type the **/** symbol to choose a block.

It would make the quotes unnecessary, which is nice. But again, this depends on the availability (and other usage) of bold in these contexts.

**Comment by bitcoinappdev** [comment]
I like that, with the bold slash.

**Comment by mrwweb** [comment]
I prefer the suggestion on #9214 to format the `/` to look like a key (probably using a `kbd` element).

But going further, placeholders are generally problematic for usability and long term it would be good to consider a more substantial rethink to the empty block and discoverability issue this text tries to solve

**Comment by gziolo** [comment]
@mapk @karmatosed - let's decide whether this should be updated. It's possible to replace this text with PHP filter as of today so it isn't such a big issue.

**Comment by mapk** [comment]
While I agree it's not crystal clear, the forward slash `/` is meant as a power user feature so I don't think it needs further attention right now. 

As for leaving off a period, that seems to follow the Title placeholder text implementation as well. I'm okay with leaving it out.

I can see using `kbd` tags to help it further. If someone wants to explore that in a PR, great.

**Comment by triplegem** [comment]
When I first read this text, I thought the language was intended (in a fun way) to include people's preferred ways of thinking about how they blog: "writing" versus "typing." When I read it again, I realized that couldn't be true because of the rest of the sentence, but it took me several seconds to work out the meaning.

I read the other threads noted in this issue and didn't see the following option, which is my preference:

`Start writing, or type / to choose a block`

**Comment by mtias** [comment]
There's a new simplified prompt now.
