### ISSUE TITLE
 Possible limit on count of Custom Post Types, allowed to display Taxonomies in Gutenberg editor

### ISSUE THREAD

**Issue by IguanaRemoteRepo** [WordPress/gutenberg#12558]
**The long story**

I wonder if there is a limit on count of Custom Post Types, allowed to display Taxonomies ( e.g. Categories and Tags) in Document UI in Gutenberg. 

I have several CPT properly declared in functions.php and tested to work as expected. They, and their respective Taxonomies args (for Categories and Tags) have ‘view_in_rest’ => true in functions.php. As result of it: in Gutenberg Editor, on the right side, I am able to have given CPT Categories and Tags listed and available to be selected by User. 

When User is asking to add a new article with one of 4 first (as the order of coding in functions.php) Custom Post Types in Gutenberg Editor, the respective Taxonomies (Categories and Tags) show up as expected. 

If I shuffle order of CPT declarations in functions.php, put them in a different order, as if it was a deck of cards, first 4 always behave as expected. From 5th and on - will not feature the a/m Taxonomies. 

I can create new CPT in front of older (as the order of code in functions.php) and new ones will feature Taxonomies, while the older will cease from it. 

When I inspect “data” in Response returned by REST API,  all of declared in functions.php CPT (and respective Taxonomies) are always listed there with all of their properties. 

**Steps to Reproduce** 

1. Add CPT (custom post type)
2. Add taxonomies, e.g. Categories and Tags
3. Not to forget to use in functions.php view_in_rest => true
4. In admin menu go to CPT and select to Add an article, using the Gutenberg editor
5. The categories and tags show 
6. Repeat steps 1,2,3 some five times
7. Attempt to repeat steps 4,5 with all of created in step 6 CPT

**Expected Behaviour**
1. The Categories and Tags will show up regardless of selected CPT, to work with.

**Existing Observation**

1. Only first four (as in functions.php) CPT will behave as expected

**Core question**

1. Is there a hardcoded or configurable limit somewhere?  What did I miss? Hope above explanation makes senses. Thank you!

**Comment by boyanraichev** [comment]
I have the same issue. I have 13 custom post types. Some of them have 1 or more custom taxonomies attached, other have none - a total of 13 taxonomies. All taxonomies are properly registered and have their menu pages, but only the first 9 taxonomies show up in Gutenberg. I can change the order of the registration, add or remove taxonomies, and I always get the first 9 only to show up.

I tried removing all plugins, re-installing WP, etc., but I still get the same issue.

**Comment by boyanraichev** [comment]
This commit fixes the problem [https://github.com/WordPress/gutenberg/commit/a897e056d3165b409bd2a588a16c21d2e9b8a5bd](url)

**Comment by youknowriad** [comment]
This was fixed and merged a long time ago.
