### ISSUE TITLE
Update RichText `onSetup` docblock

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12562]
The RichText `onSetup` docblock should be updated after recent changes:

https://github.com/WordPress/gutenberg/blob/652a662a8aba2b621978871e56706990d5deb653/packages/editor/src/components/rich-text/index.js#L136-L146

- it won't use an `onSetup` function passed via props any longer
- not sure it's setting up any event handler any longer
- it's only setting this.editor to the editor instance

**Comment by iseulde** [comment]
Yes, this should be updated. This method will also go away once we update list operations.
