### ISSUE TITLE
Adhere to WordPress core glossary

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#12579]
In a number of places, documentation uses the term "backwards compatibility" instead of "backward compatibility", which is the officially recommended spelling according to https://make.wordpress.org/core/handbook/glossary/ and https://make.wordpress.org/core/handbook/best-practices/spelling/

Situation is probably similar for other words too.

**Comment by HardeepAsrani** [comment]
I'm wondering if the file names should also be changed, such as? https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/backwards-compatibility/README.md And some are probably indexed by search engines.
