### ISSUE TITLE
No way to assign a custom post type to a category. 'show_in_rest' is enabled.

### ISSUE THREAD

**Issue by tijmensmit** [WordPress/gutenberg#12572]
Unless I made a mistake in my plugin, simply setting [show_in_rest](https://plugins.trac.wordpress.org/browser/wp-store-locator/tags/2.2.18/inc/class-post-types.php#L50)  to true doesn't seem to include the option to assign the posts to a category.

Gutenberg is used, and everything else work fine, but there's no way to assign the posts to a category. The 'Store Categories' page does show up, and I can create a new category there but there's simply no way to assign posts to it.

I tested this on a clean WP 5 RC 2 install and with only the WPSL plugin active.

Is there more required then just setting 'show_in_rest' to true to make the categories show up, or is it supposed to work?

**Comment by swissspidy** [comment]
You need `'show_in_rest' => true` for the category as well, after that it will work.

FWIW `floatval( $wp_version ) >= 5` is not really the best way to compare versions. You should use `version_compare` instead.
