### ISSUE TITLE
Make empty fields visible

### ISSUE THREAD

**Issue by 00travelgirl00** [WordPress/gutenberg#1258]
When a field has no content is pretty hard to see, that there is a content field. Only when you hover over the field becomes slightly visible. 
I suggest to add a light grey border to an empty field, so users don't forget about them. 

![empty_fields](https://user-images.githubusercontent.com/21318377/27282725-8040ae3e-54f1-11e7-9074-d1c0dddc2717.gif)

**Comment by jasmussen** [comment]
I'm going to close this in favor of #1171. But feel free to post the cool GIF there!
