### ISSUE TITLE
RichText: Add a method to manage focus

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12587]
Looks like with the removal of `unstableOnSetup` in https://github.com/WordPress/gutenberg/pull/10744 there isn't a built-in way to manage focus on the RichText editable area any longer.

Managing focus is essential in some flows, especially for custom block types with multiple RichText instances. While the removal of `unstableOnSetup` was expected to happen without notice, a new, alternative, method was expected as well. 

Other editors expose a `focus` method: for example, Draft.js explains very well why this is needed, see https://draftjs.org/docs/advanced-topics-managing-focus

Discussed a bit this issue with our technical team at Yoast and we'd tend to think that also all use-cases that were offered by a reference to TinyMCE would need to be offered by the wrapper, `RichText` in this case.

**Comment by iseulde** [comment]
What's the difference with #9740?

**Comment by afercia** [comment]
The difference is I forgot #9740 existed 🙂
