### ISSUE TITLE
Select control multiple value not working on front end

### ISSUE THREAD

**Issue by alpezed** [WordPress/gutenberg#12588]
Hi, I created a dynamic block for posts and have an option to exclude multiple categories and this code below works for me on backend but the array of selected categories not render on front end view.

`<SelectControl
	multiple
	label={ __( 'Exclude Category(s)' ) }
	options={ map( categoriesList, ( category ) => ( {
		value: category.id,
		label: category.name
	} ) ) }
	value={ exclude_categories }
	onChange={ ( value ) => setAttributes( { exclude_categories: value } ) }
/>`

Here's my php array code 
`'exclude_categories' => array(
	'type' => 'text', // this tyle is dynamic call so text is 'string', i tried array but not working also
	'title' => esc_html__( 'Exclude Category(s)', 'better' ),
	'description' => esc_html__( 'Select categories that you do not want to show.', 'better' ),
	'group' => esc_html__( 'Exclude', 'better' ),
),`

Here's the result on front end
https://www.screencast.com/t/M4qhA968EA

Thanks.

**Comment by swissspidy** [comment]
Can you please give us a bit more context? Where's your PHP code from? How did you define the `exclude_categories` attribute when registering your block? What is the contents of `value` when you change the selection (e.g. `console.log( value )` in your `onChange` handler)?

**Comment by alpezed** [comment]
`exclude_categories` is a dynamic attributes inside the `register_block_type` function and the value get on the `onChange` handler is the array of category id https://www.screencast.com/t/Tw4ltxvE5WL.

**Comment by swissspidy** [comment]
How did you define the `exclude_categories` attribute when calling `registerBlockType`? Gutenberg can't store attributes it doesn't know about.

What does the block look like in `post_content` in the database?

What does your `register_block_type()` function look like?

**Comment by alpezed** [comment]
Here's my `registerBlockType` look like:
registerBlockType( 'bb-gutennberg/bb-post-grid', {
	title: __( 'AB Post Grid', 'bb-gutennberg' ),
	description: __( 'Add a grid or list of customizable posts to your page.', 'bb-gutennberg' ),
	icon: 'grid-view',
	category: 'bb-gutennberg',
	keywords: [
		__( 'post', 'bb-gutennberg' ),
		__( 'grid', 'bb-gutennberg' ),
	],

	getEditWrapperProps( attributes ) {
		const { align } = attributes;
		if ( -1 !== validAlignments.indexOf( align ) ) {
			return { 'data-align': align };
		}
	},

	edit,

	// Render via PHP
	save() {
		return null;
	},
} );

and my php `register_block_type` look like
`register_block_type( 'bb-gutenberg/bb-post-grid', array(
	'attributes' => array(
		'exclude_categories' => array(
			'type' => 'string',
			'default' => '',
		),
		....
	),
	'render_callback' => 'bb_blocks_render_block_posts',
) );`

**Comment by swissspidy** [comment]
@alpezed Since you closed the issue, how did you get it to werk in the end? This information might be helpful for others.

**Comment by alpezed** [comment]
@swissspidy  After reviewing my plugin code i noticed that the issue is not from gutenberg but in my plugin, all value of shortcode is output as string:

```
register_block_type( 'better-gutenberg/' . strtolower( $shortcode_name ), array(
                'attributes' => $atts,
                'render_callback' => array( $shortcode, 'render_shortcode' )
            ) );
```

```
public function render_shortcode( $atts, $content = '' ) {
		$shortcode = $this->shortcode_name();
		$att_map = '';

		foreach ( $atts as $key => $value ) {
			if ( !is_array( $value ) ) {
				$att_map .= "$key=\"$value\" ";
			}
		}

		if ( ! empty( $content ) ) {
			return do_shortcode( '[' . $shortcode . ' ' . $att_map . ']' . $content . '[/' . $shortcode . ']' );
		} else {
			return do_shortcode( '[' . $shortcode . ' ' . $att_map . ' ]' );
		}
	}
```

After adding else statement like the code below is fixed the issue:
```
if ( !is_array( $value ) ) {
				$att_map .= "$key=\"$value\" ";
			} else {
				$arr_val = implode( ',', $value );
				$att_map .= "$key=\"$arr_val\" ";
			}
```
