### ISSUE TITLE
Codepen shortcode is not render

### ISSUE THREAD

**Issue by fellyph** [WordPress/gutenberg#12584]
Steps to reproduce:
1 - I've created a codepen code
2 - created a embed shortcode
3 - included the shortcode on the shortcode block
4 - I got a alert the shortcode is not valid
![image](https://user-images.githubusercontent.com/330792/49438570-ab9b7280-f7b6-11e8-8a9e-43ab9404e4ea.png)
5 - on the post I just see the text from the shortcode

shortcode:
[codepen_embed height="265" theme_id="0" slug_hash="dQLKpV" default_tab="js,result" user="fellyph"]See the Pen <a href="https://codepen.io/fellyph/pen/dQLKpV/">Ciclo de vida componente com contador</a> by Fellyph Cintra (<a href="https://codepen.io/fellyph">@fellyph</a>) on <a href="https://codepen.io">CodePen</a>.[/codepen_embed]

My environment: 
- WordPress 4.9.8
- Gutenberg Versão 4.6.1

**Comment by swissspidy** [comment]
Which plugin are you using that adds a `codepen_embed` shortcode? Jetpack maybe? This is not a shortcode that is available by default in WordPress.

Couldn't you just insert `https://codepen.io/fellyph/pen/dQLKpV/` on a new line so WordPress can try to embed it automatically?

There shouldn't be a need for this shortcode.

**Comment by benlk** [comment]
Have you enabled the [Codepen Shortcode plugin](https://wordpress.org/plugins/codepen-embedded-pen-shortcode/) that [Codepen says is required](https://blog.codepen.io/documentation/features/wordpress-plugin/)?

**Comment by fellyph** [comment]
Hi Guys, 
I used before, the link to embed it. I just change to embed block and works fine now.

Thanks,
Fellyph
