### ISSUE TITLE
Reusable block not editable

### ISSUE THREAD

**Issue by hellerbenjamin** [WordPress/gutenberg#12596]
**Describe the bug**
When editing a reusable block from a page or post, adding new blocks is impossible because the menu that pops up quickly closes and focus shifts back to the reusable block title. 

**To Reproduce**
1. Create reusable block
2. Insert reusable block on page or post
3. Click the edit button next to reusable block's name.
4. Attempt to add a block inside the reusable block using the plus button.

**Expected behavior**
The menu should stay open until a block is selected.

**Screenshots**
Here is a screencast showing the issue: https://www.dropbox.com/s/7o33s00o6k1qlrc/gutenberg-reusable-issue.mp4?dl=0

**Desktop (please complete the following information):**
 Linux Mint 18.3
 Firefox 63, also happens in Chrome.
 

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Gutenberg 4.6.1
WP 4.9.8 vanilla install 2017 theme.

**Comment by mapk** [comment]
I tested with a similar result. The block inserter would close fairly quickly. There were a couple times that I would click another block, but the other block would not be inserted.

My experience:

![reusable-inserter](https://user-images.githubusercontent.com/617986/50719585-3a6c0b00-1053-11e9-92a8-48393da5add7.gif)

**Comment by strarsis** [comment]
I can use the edit button for editing the name/title of that reusable block, 
the content is not editable. It would be nice if it could be editable in place.

**Comment by moosekid** [comment]
My current workaround for this is to use the / to select the block instead of the plus button. It seems to be consistent in letting me add new blocks that way.
