### ISSUE TITLE
Inserter: Show text prompt at the end of the post also

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1259]
Right now we have a "Write your story..." prompt at the start of an empty post, which when clicked creates a text block and lets you write:

![screen shot 2017-06-19 at 13 48 34](https://user-images.githubusercontent.com/1204802/27283750-0fce1efc-54f6-11e7-89ec-87357b6c7c57.png)

Let's have one at the end of the post also:

![screen shot 2017-06-19 at 13 49 41](https://user-images.githubusercontent.com/1204802/27283782-39b076a2-54f6-11e7-8355-c1effddf55e0.png)

Hover:

![screen shot 2017-06-19 at 13 49 48](https://user-images.githubusercontent.com/1204802/27283786-3c7fed9a-54f6-11e7-9bd5-7fd616b44c70.png)

**Comment by aduth** [comment]
Was this closed by #1210 ?

cc @youknowriad

**Comment by youknowriad** [comment]
Because it was done there?

**Comment by aduth** [comment]
That's the question 😛  Wondering if this issue should be closed.

**Comment by youknowriad** [comment]
@aduth I edited my message while you were answering :)
