### ISSUE TITLE
Document the wp_editor hooks support

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#12593]
I've been asked whether Gutenberg supports the `wp_tiny_mce_init`/`after_wp_tiny_mce` hooks in the classic block editor.

I personally don't really know how these filters worked and are expected to work in the Gutenberg editor. I'm creating this issue to see whether people have valid use-cases about these and how/if they should be translated to Gutenberg?

cc @azaozz @iseulde

**Comment by bupotalovo** [comment]
![after_wp_tiny_mce](https://user-images.githubusercontent.com/45487182/49462832-60558400-f7f7-11e8-8699-254841bf874a.png)

**Comment by azaozz** [comment]
No, these actions are not fired for the Classic Block TinyMCE instance. They are part of the way TinyMCE was loaded and initialized from the `wp_editor()` function (that also contains quicktags.js, the Visual and Text tabs, and the rest of the HTML surrounding the editor).

In Gutenberg's Classic Block TinyMCE is used similarly to the way it is used in the Text widget: only the TinyMCE scripts and a basic configuration is added from PHP and the rest (including initialization) is controlled from JS.

It may be possible to fire these actions in the footer after edit-form-blocks.php but the timing will be off.

**Comment by youknowriad** [comment]
I guess it also won't work properly if people render things in these actions. Maybe this should be just made a "Documentation" issue that these actions are not supported in Gutenberg.

**Comment by azaozz** [comment]
Re: https://github.com/WordPress/gutenberg/issues/12593#issuecomment-444198238 I can guarantee that TinyMCE Advanced works in the Classic Block without the `after_wp_tiny_mce` action :)

**Comment by mtias** [comment]
@youknowriad is there anything actionable pending here?

**Comment by youknowriad** [comment]
Potentially some migration guides but it's very unclear without use-cases. So let's just close for now.
