### ISSUE TITLE
Categories list incomplete Only around 100 categories on 2504 total appear in search. 

### ISSUE THREAD

**Issue by db123809** [WordPress/gutenberg#12602]
**Describe the bug**
In Gutenberg 4.6.1 on Wordpress 4.9.8

My website has 2,504 items in Categories on 2 hierarchical levels like:  

category a
-- subcategory a 1
-- subcategory a 2
-- subcategory a 3
... 

When I try to get any category beyond number 1-100 in my list, most of my category don't appear and search can find only categories number 1-100 

POSSIBLE SOLUTION: I checked the js queries and I see that Gutenberg queries my categories in a serie of 100s items batches, but doesn't sum them all in a single list: it just show the last batch it called. Maybe the problem is that gutenberg calls 25 batches of 100 elements and displays the last one instead of adding them up in a single big list. I wonder if this apply to tags as well, but I just have too few to experience the same problem. 

**To Reproduce**
Create a new post 
Search a category like 'Siberia' and nothing is found 
Scroll the list and read a short list of around 100 items, which don't cover my list of categories 

**Expected behavior**
Search 'Siberia' and find it right away 

**Screenshots**
The list ends at the 100th element instead of 2504th 

![schermata 2018-12-05 alle 03 03 25](https://user-images.githubusercontent.com/45613384/49485238-73d60e80-f83a-11e8-8759-32566174e425.png)

Nothing returns when I search 
![schermata 2018-12-05 alle 03 03 41](https://user-images.githubusercontent.com/45613384/49485386-17272380-f83b-11e8-9769-c4a634daf8a8.png)

**Desktop (please complete the following information):**
In Gutenberg 4.6.1 
on Wordpress 4.9.8
Chrome 71.0.3578.80 (Official Build) beta (64 bit)
Mac Book Air 
MacOs Mojave 10.14.1 

**Additional context**
In Gutenberg 4.6.1

**Comment by db123809** [comment]
If I try this 

https://example.com/wp-json/wp/v2/categories?per_page=100&pages=26&orderby=count&order=desc

I get the complete list of my categories.

**Comment by db123809** [comment]
I just discovered that Gutenberg doesn't handle correctly my nested category structure It's just max 3 level (parent, child, child). If I present a single level list, it shows the first 100. Otherwise it just doesn't show anything at all.

**Comment by db123809** [comment]
Thank you

**Comment by db123809** [comment]
Just made more experiments. The hierarchy problem seems just being generated by the fact that just the first 100 elements are taken, in alphabetical order. If parent and children are in the list, the hierarchy is correctly presented - which is pretty unlikely in a large collection.

**Comment by PACMAN49** [comment]
i'm facing the same issue where i have a hierarchy of more than 100 category.
I m using wordpress 5.1 & gutemberg

**Comment by aduth** [comment]
It's not clear to me: Would increasing the number of results fetched per request help resolve this (as described in #10881) ?

Or is there still an issue with how categories are presented even when they've all been fetched?

**Comment by designsimply** [comment]
<blockquote>To Reproduce
Create a new post
Search a category like 'Siberia' and nothing is found
Scroll the list and read a short list of around 100 items, which don't cover my list of categories</blockquote>

This happens to me all the time. I don't think increasing the number of results fetched per request would help in the case of the original reporter who has 2500+ categories. I thought of some possible solutions that might help if they are feasible and don't cost too much overhead to apply:

* Fetch the first 100 most-used categories first.
* Fetch the first 100 most recently-used categories first.
* Do some combination of the previous two things.
* Fetch the first 100 categories (in whatever way is fastest) but then also search the rest of the categories if no matches are found. ← (this one might be too costly)

**Comment by enriquesanchez** [comment]
I'm doing cleanup and triage and noticing this issue has not had activity for a while.

@db123809 are you still having issues with this?

**Comment by karmatosed** [comment]
For now, I am closing this issue. That doesn't mean it can't reopen once we get some feedback though.

**Comment by bonakor** [comment]
I have the same issue

**Comment by TwinDigitalNL** [comment]
Currently i have the same issue, only the first 100 of the categories are shown, and searching in anything outside those 100 is not possible. Result is 30 missing categories. Is there any fix for this?
