### ISSUE TITLE
Editor: Toolbar interferes with wide alignment drag handle

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#12601]
**Steps to Reproduce:**

Prerequisite: Activate a theme which supports wide alignment (e.g. Twentynineteen)

1. Navigate to Posts > Add New
2. (If not already, deactivate the Menu > "Top Toolbar" option)
3. Insert an image block
4. Choose an image
5. Change alignment to Wide or Full
6. Insert at least one other block
7. Try to drag the wide image block to rearrange

**Expected result:**

Drag and drop works. The block should either not become selected upon click on the drag handle, or the selection should only occur after mouseup.

**Actual result:**

When mousedown occurs on the drag handle, the appearance of the Toolbar conflicts with the drag action and terminates it prematurely.

**Workarounds:**

1. Use "Top Toolbar" mode (found under Menu)
2. Rearrange block using the "Move Up" and "Move Down" options

**Comment by designsimply** [comment]
Previously: #7914

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.6.1 `master` @ `46f789a5c` on Firefox 63.0.3 on macOS 10.13.6.

**Comment by lumpysimon** [comment]
I'm seeing this in 5.0-RC3-43969 in Chrome 70, MacOS 10.13. 

I would describe it as a bug, not an enhancement, as most users (myself included) would not know to switch to Top Toolbar mode.

**Comment by aduth** [comment]
I can no longer reproduce this. In wide alignment, the drag handle is shown to the left of the toolbar and no longer overlaps when the viewport is wide enough. On smaller viewports, there is no drag handle option.
