### ISSUE TITLE
Media & Text: Drag handles jump to 100% on resize

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#12600]
**Describe the bug**

Using WP 5.0 RC3, the drag handles of the Media + Text block do not function correctly. The image size jumps to 100% when you drag on the handle for the first time. From there, it's impossible to adjust the size further. (Luckily, you can still hit `undo` to reset the change). 

(I've also seen instances where the drag handles are totally unresponsive with existing Media + Text blocks, but I can't pin down the steps to see that)

**To Reproduce**

1. Add a Media & Text block
2. Add an image
3. Attempt to resize

**Screenshots**

![100](https://user-images.githubusercontent.com/1202812/49471047-d945e300-f7d9-11e8-8551-7d3d34f914b3.gif)

**Tested In**
MacOS 10.14.1, Safari 12.0.1
MacOS 10.14.1, Chrome 70.0.3538.110 

WordPress 5.0-RC3-43966
(Seems to work fine with 4.9.8 and Gutenberg 4.6.1)

Tested with Twenty Nineteen, Twenty Seventeen, and the Gutenberg Starter Theme

**Comment by jorgefilipecosta** [comment]
This issue happens because of a missing dependency on core code. It will get solved when the patch available in https://core.trac.wordpress.org/ticket/45442 is merged.

**Comment by JQOz** [comment]
Hi, i have the same problem. 

ist this bug already fixed or do we have to wait for the next update?
_(I'm using WP v5.01 on MAMP MacOs10.12.06-safari-12.01 )_

Thanks

**Comment by designsimply** [comment]
Thanks @JQOz! Someone started a new issue at #12833, let's continue the discussion there.
