### ISSUE TITLE
Jquery is not firing on edit screen

### ISSUE THREAD

**Issue by alpezed** [WordPress/gutenberg#12603]
Hi, I've created a posts block with masonry effects using `isotope` and animation on scroll using `waypoint` js and another option slider carousel using `swiper` js and works fine on the front end page but doesn't trigger when editing at all.

I am using `ServerSideRender`
```
<ServerSideRender
     block="better-gutenberg/posts"
     attributes={ attributes }
 />
```

and the scripts inside `enqueue_block_editor_assets` hook:

wp_enqueue_script( 'waypoints' );
wp_enqueue_script( 'isotope.pkgd' );
wp_enqueue_script( 'masonry.pkgd' );
wp_enqueue_script( 'swiper' );
wp_enqueue_script( 'better.posts' );

and my scripts are inside document ready like jQuery(document).ready(function($){ ... }); 
I'm guessing "document" needs to be something else.

Here's the screenshot on:

**edit screen** https://www.screencast.com/t/5txXMjEJC
**font end** https://www.screencast.com/t/DZjqEME3J

Hope someone can help this issue. Thanks

**Comment by lievikoff** [comment]
You need to find an event when the block is loaded or to use setTimeout.

**Comment by designsimply** [comment]
@alpezed I am closing this issue because it appears an answer was provided, however, if you are still having trouble would you please leave a new comment mentioning any details you've tried regarding @lievikoff's suggestion so that I can re-open the issue for you if you still need help?

**Comment by alpezed** [comment]
Hi, still can't figure out this issues, do i need to run my main scripts like jQuery(document).ready(function($){ ... }); i side live cycle event like componentDidMount? Or is there any event to run the scripts because have a lot of scripts for this block.

**Comment by marcus-hiles** [comment]
@alpezed  is it possible to demonstrate ur issue on any of the online editors like jsfiddle or any of your choosing?

**Comment by aduth** [comment]
Can you show whether there are any errors in the "Console" tab of your Developer Tools window when trying to preview the block in the editor?

The way `ServerSideRender` works using an `iframe`, I expect it should have no issue working with jQuery. Perhaps there is an issue with the script being enqueued correctly (are you sure your scripts [define `jquery` in `$deps` when registered](https://developer.wordpress.org/reference/functions/wp_register_script/#parameters)?) or with how the scripts are generated to be included in the `ServerSideRender` preview.

**Comment by alpezed** [comment]
Hi @aduth  If you can see this screenshot https://www.screencast.com/t/5txXMjEJC there is no error in the Console of Developer Tools

Yes my scripts define jquery in $deps when registered and i tried also to define those scripts on my blocks.build.js like the screenshot https://www.screencast.com/t/pvIpMf9gyV but still not works. 

My Posts Block is using ServerSideRender with a template options dropdown like MASONRY, CAROUSEL and TILT but the layout on editor is not behave like what it looks like on frontend.

edit screen https://www.screencast.com/t/5txXMjEJC
font end https://www.screencast.com/t/DZjqEME3J

**Comment by designsimply** [comment]
@alpezed I looked at your example at https://www.screencast.com/t/pvIpMf9gyV and I noticed it doesn't match up with the example at https://developer.wordpress.org/reference/functions/wp_register_script/#parameters and I noticed your example doesn't use `$deps`. Would you mind please trying with `$deps` as shown at https://developer.wordpress.org/reference/functions/wp_register_script/#parameters and please ask for help in the support forums and include your code example, the link to the `wp_register_script` documentation, and note what changes you have tried already? That is because the GitHub repository is for reporting bugs and it appears you haven't explored all troubleshooting options yet to rule out a problem with your implementation. Apologies for not being able to help more directly at this time. If you do that first and it's still not working, please reply back here with an updated code example. 

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

**Comment by alpezed** [comment]
Hi, The example i sent has already `$deps` and this are the lists of `$deps` `array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-plugins', 'wp-components', 'wp-edit-post', 'wp-api', 'jquery', 'imagesLoaded', 'swiper', 'waypoints', 'isotope-packery', 'isotope-masonry', 'better.posts' )` and you can see 'waypoints, isotope-packery, etc...' has already registred also like the code below:
wp_register_script( 'swiper', BetterCore()->assets_url . 'libs/swiper/js/swiper.min.js', array( 'jquery' ), '3.4.2', true );
		```
wp_register_script( 'waypoints', BetterCore()->assets_url . 'libs/waypoints/jquery.waypoints.min.js', array( 'jquery' ), '4.0.1', true );
		wp_register_script( 'isotope-masonry', BetterCore()->assets_url . 'libs/isotope/isotope.pkgd.min.js', array( 'jquery' ), '3.0.1', true );
		wp_register_script( 'isotope-packery', BetterCore()->assets_url . 'libs/isotope/packery-mode.pkgd.min.js', array( 'jquery', 'imagesloaded', 'isotope-masonry' ), '4.2.2', true );
		wp_register_script( 'better.posts', BetterCore()->assets_url . 'shortcodes/posts/better-posts.js', array( 'jquery', 'imagesloaded' ), '1.0.0', true );
```

**Comment by coderaaron** [comment]
I’m pretty sure there is an easier/better way to do this, but to trigger the Slick Slider jQuery on my ServerSideRender block I use [custom events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events).

- in `edit.js` (or your block’s `edit` function):
```
constructor() {
	…
	this.customEvent = new Event( 'gutenbergSlick' );
}
…
render() {
	…
	document.dispatchEvent( this.customEvent );
	return (<ServerSideRender
		block="slick-carousel”
		attributes={ this.props.attributes }
	/>);
}
```
- in the PHP file that registers my blocks: 
```
wp_enqueue_script(
	'slick-carousel',
	plugin_dir_url( __FILE__ ) . ‘assets/slick/slick.js’,
	array( 'jquery' ),
	filemtime( plugin_dir_url( __FILE__ ) . ‘assets/slick/slick.js’ ),
	true
);
wp_enqueue_script(
	'carousel-frontend’,
	plugin_dir_url( __FILE__ ) . 'assets/slick/frontend.js',
	array( 'slick-carousel' ),
	filemtime( plugin_dir_url( __FILE__ ) . 'assets/slick/frontend.js' ),
	true
);
```
- in my `frontend.js`:
```
jQuery( document ).ready( function() {
	createSlider();
} );

document.addEventListener( 'gutenbergSlick', function( e ) {
	window.setTimeout( createSlider, 1000 );
}, false );

const createSlider = function() {
	jQuery( '#carousel' ).slick( {
		…
	} );
};
```

I hope that helps

**Comment by alpezed** [comment]
Hi @coderaaron , Thank you for your great answer but i still have a problem because it is not working after updating the field or options and it only works after page reload.
