### ISSUE TITLE
autop not adding a trailing </p> when text is followed by a div

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12610]
If you have this content:

```html
Testing freeform block with some
<div class="wp-some-class">content</div>
```

[autop](https://github.com/WordPress/gutenberg/tree/master/packages/autop) converts it to this, with a missing `</p>`:

```html
<p>Testing freeform block with some
<div class="wp-some-class">content</div>
```

When it should be this with a trailing `</p>`
```html
<p>Testing freeform block with some</p>
<div class="wp-some-class">content</div>
```

**To Reproduce**
Add this unit test to the [autop](https://github.com/WordPress/gutenberg/blob/master/packages/autop/src/test/index.test.js) unit tests:

```js
test( 'that autop correctly adds start and end tag when followed by a div', () => {
	const content = 'Testing freeform block with some\n<div class="wp-some-class">content</div>';
	const expected = '<p>Testing freeform block with some</p>\n<div class="wp-some-class">content</div>';

	expect( autop( content ).trim() ).toBe( expected );
} );
```

**Comment by johngodley** [comment]
[This line](https://github.com/WordPress/gutenberg/blob/master/packages/autop/src/index.js#L241) removes the trailing `</p>` because it follows the `</div>`.

I'm not yet sure what the difference is between the JS and PHP version, which it models:

https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/formatting.php#L439

**Comment by johngodley** [comment]
Found the problem in #12614 - a missing backslash is causing [this expression](https://github.com/WordPress/gutenberg/blob/master/packages/autop/src/index.js#L164) to never match:

```js
	// Add a double line break above block-level opening tags.
	text = text.replace( new RegExp( '(<' + allBlocks + '[\s\/>])', 'g' ), '\n\n$1' );
```

This means that the `<div>` is not split off from the paragraph, and then the subsequent code removes the trailing `</p>`

**Comment by aduth** [comment]
Just to verify, I ran the test case through the PHP implementation as well, to verify that a discrepancy exists (it does):

```
$ wp shell
wp> wpautop('Testing freeform block with some\n<div class="wp-some-class">content</div>');
=> string(83) "<p>Testing freeform block with some\n</p>
<div class="wp-some-class">content</div>
"
```
