### ISSUE TITLE
Post format does not work, displays all formats

### ISSUE THREAD

**Issue by murshed** [WordPress/gutenberg#12612]
**Describe the bug**
I am using [FlatPro](https://www.themeum.com/product/flat-theme-free-responsive-multipurpose-wordpress-theme/) theme by Themeum. The post format select option lists all post formats and does not work while editing the post. There are no Console error.

Please help.

**Expected Behavior**
Gutenberg should list only those post formats which are defined in theme support.

**Screenshots**

Here is the screenshot link: 
- [https://i.gyazo.com/f1f349672d953e50db8cf0959c2c5297.png](https://i.gyazo.com/f1f349672d953e50db8cf0959c2c5297.png)
<img src="https://i.gyazo.com/f1f349672d953e50db8cf0959c2c5297.png"/>

- [FlatPro Console Screenshot](https://i.gyazo.com/f1f349672d953e50db8cf0959c2c5297.png)
<img src="https://i.gyazo.com/f1f349672d953e50db8cf0959c2c5297.png"/>

- [Post Format Screenshot](https://i.imgur.com/Itx7BiM.png)
<img src="https://i.imgur.com/Itx7BiM.png"/>

- <img src="https://i.imgur.com/Itx7BiM.png"/>

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS ]

**Comment by swissspidy** [comment]
Sounds like a duplicate of #12571.

**Comment by murshed** [comment]
> Sounds like a duplicate of #12571.

Thanks a lot. I'll follow that.

**Comment by designsimply** [comment]
Closing as a duplicate of #12571. Thanks @swissspidy!

**Comment by murshed** [comment]
We have solved this issue.

Add this code to the post-meta.js on the theme **/flatpro/js/admin/post-meta.js**

`jQuery(document).ready(function($){ 'use strict';
	/* Select Post Format */ 
	$(document).on('change', 'select[id*="post-format"]', function(){ 
		for (var i =0; i < $( '.editor-post-format select option').length; i++) {
			var formate = $( '.editor-post-format select option:eq('+i+')' ).attr('value');	
			$('div[id^=post-meta-'+formate+']').hide();
		}
		var formate = $( '.editor-post-format select' ).attr('value');
		$('div[id^=post-meta-'+formate+']').show();
	});
	/* End. */ 

	$(window).load(function(){
		for (var i =0; i < $( '.editor-post-format select option').length; i++ ) {
			var formate = $( '.editor-post-format select option:eq('+i+')' ).attr('value');	
			$('div[id^=post-meta-'+formate+']').hide();
		}
		var formate = $( '.editor-post-format select' ).attr('value');
		$('div[id^=post-meta-'+formate+']').show();
	});
	/* End on load. */ 
	
});`
