### ISSUE TITLE
Allow themes to dequeue the default editor font (Noto Serif)

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/gutenberg#12611]
**Background and problem**

The idea is that themes optimize user experience by styling the editor to match the frontend of the site. See [Twenty Nineteen](https://github.com/WordPress/twentynineteen) as an example. In the editor, the theme sets the same font as it uses on the frontend. This and most themes won't need the default editor font. Loading it is not needed.

**Proposed solution**

It would make sense to enable themes to easily dequeue the Noto Serif google font that is loaded in the editor. However, I am not sure if it is possible.

The editor is already loading a large amount of stuff (scripts and styles) to edit a post (> 3 Mb). I think that every bit that we can remove is a win.

**Comment by rilwis** [comment]
I've just noticed this issue when the Noto serif is always loaded on the frontend of my site. After looking at the issues above, I still don't understand:

- Why Noto serif is needed?
- Why shouldn't it be replaced with a serif font stack?
- Why can't we remove it on the frontend?

**Comment by aristath** [comment]
Closing this one as Noto Serif was removed.
