### ISSUE TITLE
Undoing list block creation causes loss of keyboard focus

### ISSUE THREAD

**Issue by brianhogg** [WordPress/gutenberg#12618]
**Describe the bug**
If you type - (dash) then space, the paragraph block converts into a list item block. But if you then Cmd+Z to undo (ie. you just want a dash not a special bullet block) you lose keyboard focus and have to mouse into the block.

**To Reproduce**
1. Create a new paragraph block
2. Type - then a space
3. Press Cmd+Z (OSX)
4. See keyboard focus is lost and you can no longer type in the reverted paragraph block

**Expected behavior**
Keyboard cursor remains in the paragraph block

**Desktop (please complete the following information):**
 - OS: MacOSX 10.13.6
 - Browser: Chrome
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by jorgefilipecosta** [comment]
Hi @brianhogg, @designsimply thank you for reporting and testing this issue. I think this is a general RichText problem of focus not being managed and is covered in https://github.com/WordPress/gutenberg/issues/9740. I'm going to close this issue for now so we can converge in the other issue which is more general.
