### ISSUE TITLE
Possibility to remove subheadings like h5 or h6 from the classic block

### ISSUE THREAD

**Issue by damircalusic** [WordPress/gutenberg#12622]
I build websites where my clients don't need subheadings like h5 or h6. It is a little bit frustrating that I cannot remove these from the list of options.

We need the possibilty to remove subheadings like it is possible withe the Classic Editor. The sooner the better. A filter function could be a solution if someone else does not have an better idea.

**Comment by designsimply** [comment]
Adding a screenshot for reference.

![screen shot 2018-12-05 at 12 49 13 pm](https://user-images.githubusercontent.com/1119271/49540029-47e37900-f88c-11e8-9d28-b5a1f2c15de9.png)
<sup>Tested using WordPress 5.0-RC3-43967 on Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment]
This is already possible with the [Advanced TinyMCE Configuration](https://wordpress.org/plugins/advanced-tinymce-configuration/) plugin.

I tested it just now with WordPress 5.0-RC3-43967 and was able to update the `block_formats` like so:

![screen shot 2018-12-05 at 1 01 15 pm](https://user-images.githubusercontent.com/1119271/49540722-03f17380-f88e-11e8-89db-e02f7c459792.png)
<sup>Tested using WordPress 5.0-RC3-43967 on Firefox 63.0.3 on macOS 10.13.6.</sup>

Here is what I updated in Settings > TinyMCE Config (after installing the plugin) to get that result:

![screen shot 2018-12-05 at 1 03 18 pm](https://user-images.githubusercontent.com/1119271/49540821-3e5b1080-f88e-11e8-8c63-34bf4cbadf05.png)

**Comment by damircalusic** [comment]
It does not work sorry... I see you have the real TinyTMCE in your screenshot... I am referreing to the Gutenberg Block as you can see on my printscreen.

So this case cannot be closed and should be reopen.

<img width="1299" alt="gutenberg" src="https://user-images.githubusercontent.com/6456244/49569984-bf211780-f935-11e8-9d2a-22c0e86bdb7a.PNG">

**Comment by designsimply** [comment]
Apologies for the mixup! I see now that my plugin workaround suggestion was for the classic block and you were asking about the paragraph block. I believe modifying the interface like you are suggesting should also be done in a plugin though.
