### ISSUE TITLE
NUX: Make disabling tips instance specific.

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#12633]
**Is your feature request related to a problem? Please describe.**
If I disable tips in the Block Editor, I don't want that to hide tips for all other apps in my WordPress install.

**Describe the solution you'd like**
Something like `context` that would function similarly to the `notices` package. `areTipsEnabled`, `enableTips` and `disableTips` would all take an optional `context` parameter that defaults to `global`. Perhaps that'd include modifying the `<DotTip />` component to include a `context` prop, it could be inferred from the `tipId` but that is almost certainly not correct for "shared spaces" like the editor.

Alternately, the context could be set for the entire page load and would just effect the reducer ( which would in turn mean they are persisted differently in `localStorage`. Like `wp.nux.setContext()`.

For clarity, I mean a reducer shape something like this.

```
{
  "preferences": {
    "areTipsEnabled": ["global", "my-app"]
  }
}
```

Or if was important to distinguish the `null` state.

```
{
  "preferences": {
    "areTipsEnabled": {
      "global": true,
      "my-app": false
    }
  }
}
```

**Describe alternatives you've considered**
Heavily monkey patching `isTipVisible()`. #12632 would alleviate this need a bit since it'd be less likely that users would completely disable tips.

**Comment by designsimply** [comment]
Would adding the ability to disable tips in one context area over another also cover the case you raised in #12632? Why is a separate issue needed for that case? Can that one be consolidated into this issue?

**Comment by noisysocks** [comment]
Closing this out as `DotTip` is deprecated as of #18981. The Welcome Guide which has replaced tips uses `isFeatureActive` instead of `areTipsEnabled`.
