### ISSUE TITLE
how could I add ID for different block or elements in block?

### ISSUE THREAD

**Issue by najarrajan1** [WordPress/gutenberg#12634]
I added 2 different button in 2 separate blocks, how could I add ID

`<div class="wp-block-button btn-1"><a class="wp-block-button__link has-background has-alert-background-color" href="#">watch now</a></div>`
`<div class="wp-block-button btn-1"><a class="wp-block-button__link has-background has-alert-background-color" href="#">call now</a></div>`

**Comment by swissspidy** [comment]
You could use the `withInstanceId` HOC: https://github.com/WordPress/gutenberg/blob/e95026cee0d66b98d8b4e958cfacf8fe9a9e8b2d/packages/compose/src/with-instance-id/README.md

**Comment by heldervilela** [comment]
It is also possible to use the `const { clientId } = this.props;` prop inside the **edit()** or **save()** method

**Comment by najarrajan1** [comment]
Thankyou for your reply.
But how and where I use it?

**Comment by najarrajan1** [comment]
Thankyou both of you for replies. In which file to make change so that in every block element there will be unique ID as said in 'withInstanceId'?

**Comment by danielbachhuber** [comment]
@najarrajan1 What are you using the ID for?

It would be a lot of work to register an ID field for each core block. If you only need the ID for the frontend, you might consider filtering at the PHP level using the `do_block` filter.

**Comment by bupotalovo** [comment]
@najarrajan1 With any other page builders you can configure ID and class for rows, sections, elements, etc., maybe you are looking for this?

With Gutenberg you can only configure class via `Block Settings > Advanced > Additional CSS Class`, but no ID. If you manually add `id="my-id"` via `Edit as HTML` the button block will break with a `This block contains unexpected or invalid content.` message.

**Comment by najarrajan1** [comment]
> @najarrajan1 With any other page builders you can configure ID and class for rows, sections, elements, etc., maybe you are looking for this?
> 
> With Gutenberg you can only configure class via `Block Settings > Advanced > Additional CSS Class`, but no ID. If you manually add `id="my-id"` via `Edit as HTML` the button block will break with a `This block contains unexpected or invalid content.` message.

@bupotalovo , yes like that. but not on each elements, but if I want to add ID like in above two buttons that I have posted.

Yes I found to add the class. Just looking for, If I need to add ID for those two 'button' on different block may it be possible to add.

**Comment by bupotalovo** [comment]
> If I need to add ID for those two 'button' on different block may it be possible to add.

Adding an ID as in the other page builders is not possible with any Gutenberg core block.

You have to be/hire a programmer and write own blocks, or intercept block output or similar, as advised by the other guys.

**Comment by najarrajan1** [comment]
thankyou bupotalovo.

**Comment by swissspidy** [comment]
Closing this for now then.

Feel free to reopen if you have any follow-up questions about this.

**Comment by wdburgdorf** [comment]
> Adding an ID as in the other page builders is not possible with any Gutenberg core block.

Is anyone else seeing the problem here? Are the Gutenberg developers aware of the issue, and someone working to fix it?

**Comment by senti-matteo** [comment]
> > L'aggiunta di un ID come negli altri costruttori di pagine non è possibile con alcun blocco di base Gutenberg.
> 
> C'è qualcun altro che vede il problema? Gli sviluppatori di Gutenberg sono a conoscenza del problema e qualcuno che lavora per risolverlo?

You can add an ID value whit the "HTML Anchor” field.
