### ISSUE TITLE
Does Gutenberg allows 2/3 innerblock in same block?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#12637]
Can it be possible to allow two innerblock in same block?
For eg. - 

`<div className ="content">
    Inner block content 1
	<div className = "abc" >
		<InnerBlocks templateLock={false} />
	</div>
	Inner block content 2
	<div className ="xyz">
		<InnerBlocks templateLock={false} />
	</div>
</div>`

Here is screenshot - https://cl.ly/bbcd4d44ceba

Need Help!

**Comment by mtias** [comment]
Hi there. You'd need to have individual blocks for "abc" and "xyz" with each containing their own `InnerBlock` area. That's the way Columns → Column → ChildBlocks work if you want to check it out.
