### ISSUE TITLE
NUX: Customize aria-label

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#12631]
**Is your feature request related to a problem? Please describe.**
In `master` the NUX `<DotTip>` component has an `aria-label` set to "Editor Tips". This only makes sense when using the `nux` package in the editor.

**Describe the solution you'd like**
Allow overriding the `aria-label` or use a more generic message like "Interface Tips" or something.

**Comment by designsimply** [comment]
May I make the argument that, even if `<DotTip>` were to be used outside of editing posts, that you would still be editing and the "Editor Tips" label may still apply? Or if I'm thinking of it wrong 🤔 could you tell me a specific use case where you would definitely not want the label to say "Editor Tips" (or maybe a slight change to "Editing Tips")?

**Comment by TimothyBJacobs** [comment]
Yep. It has nothing to do with editing or content at all. It's a completely separate admin experience. Imagine a `<DotTip>` being used in the General Settings page for instance. It'd make no sense to reference the editor or even editing in that context.

**Comment by noisysocks** [comment]
Closing this out as tips have been removed in #18041 and `DotTip` has been deprecated in #18981.
