### ISSUE TITLE
Only 10 taxonomies with 'show_in_rest' available in the editor's sidebar

### ISSUE THREAD

**Issue by VadymPogorelov** [WordPress/gutenberg#12649]
**Describe the bug**
I have 10+ custom post types with 1-5 taxonomies in each.
When I open Gutenberg to edit some of my post types - the taxonomy selector is not appear.
All taxonomies have flag 'show_in_rest', but Gutenberg see only first 10 from them:
AJAX response contain all taxonomies, but `wp.data.select('core').getTaxonomies()` return only first 10!
https://www.screencast.com/t/W6x0tjgsjsp

As you can see on the screenshot above - taxonomies after 'cpt_cars_labels' are not available in the array.
And when I edititng custom post type 'Dishes' - selector of the taxonomy 'Dishes Group' is not available.
https://www.screencast.com/t/ZodY7Pz5Hlh

**Comment by danielbachhuber** [comment]
Hi @VadymPogorelov,

Thanks for the report! 

I tried reproducing this issue locally against WordPress 5.0 with the following code snippet:

```
add_action( 'init', function() {
	for ( $i=0; $i < 15; $i++ ) {
		register_taxonomy( 'taxonomy-' . $i, 'post', array(
			'label' => 'taxonomy-' . $i,
			'show_in_rest' => true,
		) );
	}
});
```

However, all taxonomies appear in the sidebar as expected:

![image](https://user-images.githubusercontent.com/36432/49611244-ce17c200-f955-11e8-9e48-172b9e2d217b.png)

A few follow-up questions:
* Can you share which versions of WordPress and/or Gutenberg the plugin you're running?
* Are you running any other plugins that might be having a negative impact?
* To confirm, each taxonomy is correctly registered to the appropriate post types?
* Have you customized the capabilities associated with each taxonomy, by chance?

**Comment by realworldev** [comment]
@danielbachhuber Your code snippet does not match the description, try with this snippet:
```
add_action( 'init', function() {
	for ( $j=0; $j < 12; $j++ ) {
		register_post_type( 'cpt_' . $j, array(
			'label' => 'cpt ' . $j,
			'show_in_rest' => true,
			'public' => true,
		) );
		for ( $i=0; $i < 4; $i++ ) {
			register_taxonomy( 'taxonomy_' . $j . '_' . $i, 'cpt_' . $j, array(
				'label' => 'taxonomy ' . $j . ' ' .$i,
				'show_in_rest' => true,
			) );
		}
	}
});
```
Gutenberg

- cpt 0 = 4 taxonomies
- cpt 1 = 4 taxonomies
- cpt 2 = **0** taxonomies
- cpt 3 = **0** taxonomies
- cpt 4 = **0** ...

Classic Editor

- cpt 0 = 4 taxonomies
- cpt 1 = 4 taxonomies
- cpt 2 = 4 taxonomies
- cpt 3 = 4 taxonomies
- cpt 4 = 4 ...

**Comment by danielbachhuber** [comment]
Thanks @realworldev. I can reproduce the issue with the code snippet you provided using WordPress 5.0 and the Gutenberg plugin at b7e343d

![image](https://user-images.githubusercontent.com/36432/49768158-4bae3b80-fc90-11e8-9df4-c65ab0b8f63b.png)

![image](https://user-images.githubusercontent.com/36432/49768180-5c5eb180-fc90-11e8-9a10-7cbba1eeb54b.png)

I've filed this against the `WordPress 5.0.x Follow Ups` milestone. The underlying issue seems to be that `wp.data.select('core').getTaxonomies()` does in fact only include 10 items:

![image](https://user-images.githubusercontent.com/36432/49768286-b1022c80-fc90-11e8-88bd-1fedec935b63.png)

**Comment by VadymPogorelov** [comment]
This bug is found on WordPress 4.9.8 + plugin Gutenberg (latest version).
 On WordPress 5.0 (plugin Gutenberg is deactivated and used core blocks editor) - everything is OK

**Comment by castilloedwin** [comment]
Thanks a lot, I was becoming a crazy man. In this version, there's to put "show_in_rest" in the taxonomies.
