### ISSUE TITLE
Performance: Reduced responsiveness when using Annotations API

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#12642]
**Describe the bug**

Since Yoast SEO 9.2 we have implemented the annotations API support.
This results in reduced responsiveness when typing, at least in two situations:

- When typing really fast
- When moving the cursor while typing

Which suggests that the problem is only amplified by doing faster or more actions together.

Events that are used (extracted from profiling in the browser):
Mouse movement: `Gutenberg/editor/index.js: stopTypingOnMouseMove`
Fast typing: `Gutenberg/editor/index.js: key: "render"`

Maybe related:
When using Yoast SEO 9.1 (no annotations API) the following [issue](https://github.com/Yoast/wordpress-seo/issues/11766) manifests itself after ~26 items in the How-To block instead of ~15

**To Reproduce**
1. Type really fast (button-bash) - in gradual amounts the text is starting to stagger more and eventually just does not update until you stop typing

Or
1. Type with one hand and keep moving the mouse with the other
2. The text will not be updated until after the mouse has stopped moving

**Expected behavior**
I expect the text to be updated and rendered whenever I type.

**Screenshots**

When moving the mouse while typing, these are the performance tab results:
<img width="1275" alt="typing-while-mouse-movement" src="https://user-images.githubusercontent.com/2005352/49579233-fc909f80-f94b-11e8-8122-0302e677cdfb.png">

When typing very quickly, these are the performance tab results:
<img width="1275" alt="very-quick-typing" src="https://user-images.githubusercontent.com/2005352/49579266-0d411580-f94c-11e8-8f2a-0144083a1588.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 71

**Additional context**
- Gutenberg 4.6.1
- [Yoast SEO 9.1](https://github.com/Yoast/wordpress-seo/releases/download/9.1/wordpress-seo.zip)
- [Yoast SEO 9.2](https://github.com/Yoast/wordpress-seo/releases/download/9.2/wordpress-seo.zip)

Related issue on Yoast SEO: https://github.com/Yoast/wordpress-seo/issues/11772

**Comment by atimmer** [comment]
This is most probably fixed by https://github.com/WordPress/gutenberg/pull/12186.

**Comment by aduth** [comment]
Considering as fixed by #12161, #12741. Please reopen if it remains an issue.
