### ISSUE TITLE
Bad sidebar style (no spacing)

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12652]
I really don't know why do I see things like this by default in Gutenberg (I don't load any custom admin styles whatsoever):

<img src="https://i.imgur.com/oSSavGE.png">

The following should be removed to fix this, I don't know why it's even there?

```
.components-base-control .components-base-control__help {
    font-style: italic;
    margin-bottom: 0;
    margin-top: -8px;
}
```

/wp-content/plugins/gutenberg/build/components/style.css

Then the style is fixed.

**Comment by geekpulp** [comment]
@manake Is the intention to create space below each of the descriptions that are in italics? or that and remove the italics style too? I’m new to contributing to any project but I think I can do either of those if you can confirm which it is?

Thanks!

**Comment by manake** [comment]
Italic is OK in my opinion because it doesn't violate any rule.

But spacing could be increased because it violates proximity rule.
