### ISSUE TITLE
Sometimes preview results in a 404

### ISSUE THREAD

**Issue by withinboredom** [WordPress/gutenberg#12650]
**Describe the bug**
Sometimes when previewing a post, a 404 not found is returned instead of the preview. I cannot reliably reproduce.

**To Reproduce**
1. Go to create a new post
2. Write some content
2. Click on preview
4. See 404 error

**Expected behavior**
A preview of a post

**Desktop (please complete the following information):**
 - OS: Linux and OSX
 - Browser: Chrome
 - Version 71

**Comment by designsimply** [comment]
I have heard of this happening when editing with WordPress.com via Jetpack when you aren't logged in on the `wp-admin` side, but I haven't ever seen a 404 returned for a preview when testing with a self-hosted WordPress site. I tested Previews several times today for other issues and also tried replicating the problem using the steps provided but never could get a 404 to trigger. In my testing, I used WordPress 5.0.1 and Gutenberg 4.7.0 as well as 4.7.0 `master` @ `ddac4f3cf` with Firefox 63.0.3 on macOS 10.13.6.

@withinboredom I would like to close this issue for now with a note that I would very much like to help with it after more information about your setup or more reliable steps to reproduce the problem have been provided.
