### ISSUE TITLE
How to remove gutenberg CSS

### ISSUE THREAD

**Issue by evemilano** [WordPress/gutenberg#12659]
Hello, I'm testing two ways to remove Gutenberg, the https://wordpress.org/support/plugin/disable-gutenberg/ plugin and the `add_filter('use_block_editor_for_post', '__return_false');` code.

Both of them remove the Gut interface but NOT the CSS /wp-includes/css/dist/block-library/style.css

How can I remove that CSS, or better to TOTALLY remove gutenberg?

**Comment by designsimply** [comment]
You can hide all functionality available in the new Gutenberg block editor by installing the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin.

**Comment by designsimply** [comment]
I realized I answered quickly before and I'm not sure if the Classic Editor plugin removes the CSS you're referring to. If it does not then I am not sure you can completely remove Gutenberg, however, I do think the Classic Editor is the best choice for your case. I also noticed that the plugin page says that it includes several filters that let other plugins control the settings, which may be helpful to you.

**Comment by bsudeep** [comment]
@evemilano I think what you are looking for is...

```
add_action( 'wp_print_styles', 'wps_deregister_styles', 100 );
function wps_deregister_styles() {
    wp_dequeue_style( 'wp-block-library' );
    wp_deregister_style( 'wp-block-library' );
}
```

Found it here:
https://stackoverflow.com/questions/52277629/remove-gutenberg-css

**Comment by designsimply** [comment]
Thank you @bsudeep !
