### ISSUE TITLE
Content from classic editor shows broken icons

### ISSUE THREAD

**Issue by fabiofiss** [WordPress/gutenberg#12651]
**Describe the bug**
Broken icons in classic editor block.
![gutenberg](https://user-images.githubusercontent.com/7153391/49605791-7f6f2580-f95f-11e8-955e-7849a892f886.png)

**To Reproduce**
I had the classic editor enabled before updating to 5.0
After updating to WordPress 5.0, I deactivated the classic editor.
Now, I see the older content in blocks. However, the icons on that new block are not appearing.

**Environment** 
Desktop
Testing on Chrome, on macOS.

**Comment by designsimply** [comment]
Just to make sure, have you tried clearing browser cache as a troubleshooting step for this? 

I tried testing just now but couldn't replicate the problem. I installed WP 4.9.8 and Classic Editor 1.1. Then I used the Dashboard > Updates page to upgrade to WP 5.0. I opened an older post and saw the classic block with working icons.

What are the language settings on your computer and have you modified the system fonts in any way? (I'm not sure this is relevant but asking just in case.)

**Comment by designsimply** [comment]
I re-tested and cannot replicate the problem, though I may not be testing under the same conditions as you and need more information. 

If you're still having trouble, please clear browser cache and if that doesn't solve the problem for you then please re-open this issue with any information you can provide about your local setup—especially and browser or system font customizations you can think of. Thank you!

**Comment by alinacsava** [comment]
For anyone who encountered this issue:

For me it was caused by the editor styles I added, because it assigned the sans-serif font I was using to everything, including the toolbar.

I hope this helps.
