### ISSUE TITLE
Where is gutenberg_parse_blocks() in WordPress 5.0?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12653]
Where is `gutenberg_parse_blocks()` in WordPress 5.0?

**Comment by manake** [comment]
Ok, I found it, it's `parse_blocks()` now.

This will probably break compatibility for many people since all functions were renamed (if anyone is wondering).

**Comment by LZL0** [comment]
great news

**Comment by danielbachhuber** [comment]
> This will probably break compatibility for many people since all functions were renamed (if anyone is wondering).

Yep, this is a known issue that's not going to be fixed. See #11598

**Comment by axelpale** [comment]
But where was it in WordPress 4.x? Where is `parse_blocks()` in 5.x?

After some `find` commands:

    ./wp-content/plugins/gutenberg/lib/blocks.php

After an update to 5.x I had to reinstall [gutenberg plugin](https://wordpress.org/plugins/gutenberg/) to fix an issue relating to `gutenberg_parse_blocks` - `parse_blocks` incompatibility.
