### ISSUE TITLE
Code editor adds <br> to style

### ISSUE THREAD

**Issue by vladaman** [WordPress/gutenberg#12668]
When using new Code Editor, it adds <br> tags into style tag.

![screenshot from 2018-12-07 08-40-45](https://user-images.githubusercontent.com/907206/49634038-d88c9700-f9fb-11e8-91ab-62a55c127561.png)

**Comment by UserBOE** [comment]
Yes, having the exact same issue on my site. It's really screwing up pages and posts.

**Comment by TimothyBJacobs** [comment]
Have you tried putting your styles inside the Custom HTML block?

**Comment by youknowriad** [comment]
I confirm the issue but I noticed that I had the same issue with the classic editor too. And yes using the custom HTML block seems like a good workaround (I confirmed it works)

**Comment by youknowriad** [comment]
So this looks like a duplicate of #9056 though

**Comment by josefanderson215** [comment]
remove_filter('the_content', 'wpautop');
