### ISSUE TITLE
Block editor (Gutenberg) returns blank page when creating new post.

### ISSUE THREAD

**Issue by musacco** [WordPress/gutenberg#12662]
**Describe the bug:**

Block editor (Gutenberg) returns blank page when creating new posts.

**To Reproduce:**

Go to > Posts > Add new

**Expected behavior:**

Do not see the blank page.

Desktop (please complete the following information):

OS Windows 10 Pro - Version 1803 (build SO 17134.407) - x64 bit

Browser Google Chrome Version 71.0.3578.80 - x64 bit

Browser Chrome Version 63.0.3 - x64 bit

**Additional context:**

The problem occurs both with the classic editor installed and also with the classic editor uninstalled.

The problem also occurs after all the WordPress caches and all browser caches have been emptied.

**Comment by GlennMartin1** [comment]
What version of WordPress?

What's your theme? Is it up-to-date?

**Comment by musacco** [comment]
Upgraded from WordPress version 4.9.8 to the latest WordPress version 5.0.0

The theme is the latest version of Flatsome version 3.7.1 by UX Themes

**Comment by danielbachhuber** [comment]
Hi @musacco,

Thanks for the report.

A couple of follow-up questions:
*  Can you open the Developer Tools in your browser to see if there are any JavaScript errors to report?
* What plugins are you using? Have you tried deactivating them one by one to see if one of the plugins may be the cause of the issue?

**Comment by musacco** [comment]
Hi, for me the problem is solved with the last two update of the WordPress Classic Editor.

Thanks in advance for the support.
