### ISSUE TITLE
Twitter embed fails with trailing slash on URL

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#12664]
**Describe the bug**
Attempting to embed a Tweet with a URL containing a trailing slash causes the embed to fail. While Twitter seems to default to no-slash it does not redirect a URL with a trailing slash to the no-slash version.

**To Reproduce**
1. Go to 'wp-admin/post-new.php'
2. Paste a Twitter single-Tweet URL with a trailing slash on its own or in the embed or Twitter blocks
3. See embed error and URL displays on the front-end instead of embed

**Expected behavior**
The Tweet to embed the same as with no trailing slash

**Screenshots**
<img width="639" alt="screen shot 2018-12-06 at 7 43 55 pm" src="https://user-images.githubusercontent.com/1900444/49620591-93328000-f98f-11e8-99c6-b950dd338d87.png">

**Desktop (please complete the following information):**
 - OS: OS X 10
 - Chrome
 - Version 70.0.3538.11

**Additional context**
- WordPress 5.0. No plugins.

**Comment by gziolo** [comment]
Initial exploration was executed by @alpinealex in #12739. It wasn't finished and this issue can be taken over by someone else. This is the latest recommendation from @notnownikki how to fix this bug:

> I'd rather this removed the trailing slash if the embed failed, just so we can support embed URLs that do end with a trailing slash. That should be easy enough to do in `componentDidUpdate` (of `edit` component).

**Comment by gbroques** [comment]
@gziolo I can take this over.

**Comment by gziolo** [comment]
@gbroques, thank you 👍

**Comment by gbroques** [comment]
@gziolo I believe I fixed the issue as @notnownikki suggested, but ran into some issues running the e2e tests locally.

> Error: The constant 'SCRIPT_DEBUG' is not defined in the 'wp-config.php' file.

I'm using the built-in [local environment](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#local-environment) as suggested by the [End to end testing](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#end-to-end-testing) section in the docs.

**OS:** Ubuntu 16.04
Docker version 18.09.3, build 774a1f4
docker-compose version 1.22.0, build f46880fe
**Node version:** v10.15.3

**Comment by notnownikki** [comment]
Hey folks, I can take a look at this fix tomorrow. If you're having trouble
getting e2e tests to run or pass locally, I'm happy to help out there 🙂

**Comment by gbroques** [comment]
Another contributor can pick this issue up and use my PR #14600 as a starting place.

It looks like all that's needed is a fix to the e2e tests. Read the PR comments for @notnownikki's suggestion.

Hope this helps! :)
