### ISSUE TITLE
Opposite direction typing while using Yoast How-To Block

### ISSUE THREAD

**Issue by masterimmu** [WordPress/gutenberg#12669]
**Description**
I am trying to write how-to post in gutenberg editor using Yoast How-To block, After starting typing in block, charterers are being typed in opposite direction eg, if i type "start" it is printing "trats"

**To Reproduce**
1. Go to 'WordPress Dashboard->New Post.'
2. Click on 'Add Block->Yoast How-To Block'
3. Scroll down to 'Yoast Block-> Start typing in **Enter step title**'

**Expected behavior**
Should be type in proper direction. eg like "start"

**Screenshots**
![two](https://user-images.githubusercontent.com/45683351/49636618-2c0adf00-fa14-11e8-99e7-6e6432571c5f.png)

**Desktop :**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Mozila Firefox]
 - Version [e.g. 63.0.3]

**Additional context**
- Integrated In Wordpress 5.0.
- From the dashboard of [Wordpress Blog](https://startonlinebusiness.in/)

**Comment by arhue** [comment]
This happens to me on any block of text.

**Comment by kcalkmc** [comment]
Tested using Windows 7., Chrome, Worked fine in that environment.
Not able to duplicate. 
It would good to have someone test with Firefox and Windows. In the meantime, recommend reporting issue to Yoast Plugin Support (https://github.com/Yoast/wordpress-seo/issues)

**Comment by arhue** [comment]
@kcalkmc I think this specifically happens when you use Asia/Kolkata timezone and upgrade from WP 4.9.x. I had this issue. Changing timezones and changing it back to Asia/Kolkata fixed the issue for me. I had this issue for all blocks except the main heading block, not just Yoast. The OP in this thread is from India as well so I presume he's on the same timezone.

I tried with Chrome/Firefox and Linux so this doesn't appear to be a client side issue. I'll try to reproduce this on a test env if I get some time.

**Comment by designsimply** [comment]
@arhue thank you for the extra details. Do these testing steps sound right?

1. Install WP 4.9.x. 
1. Set timezone to Asia/Kolkata on the Settings > General page.
1. Upgrade to WP 5.0.
1. Open any block (e.g. a paragraph block).
1. Start typing and check to see if the characters appear in the correct order.

Note: consider changing step 2 click "Save Changes" without making a change to the timezone.

<blockquote>Changing timezones and changing it back to Asia/Kolkata fixed the issue for me</blockquote>

I wonder if this triggers an update of something else such as a language setting. May I ask, in your case, did you have an RTL language selected at some point before you upgraded to 5.0 or do you recall if you only ever used English on the site where you saw the problem happen?

**Comment by arhue** [comment]
@designsimply 

> Do these testing steps sound right?

Yes, that sounds about right.

> I wonder if this triggers an update of something else such as a language setting. May I ask, in your case, did you have an RTL language selected at some point before you upgraded to 5.0 or do you recall if you only ever used English on the site where you saw the problem happen?

Nope. Had selected "English(UK)" as the language throughout.

**Comment by masterimmu** [comment]
@kcalkmc Issue already reported to [Yoast support](https://wordpress.org/support/topic/opposite-direction-typing-while-using-yoast-how-to-block/)
@arhue mentioned in reply 
> Changing timezone to a US timezone and back to Asia/Kolkata timezone fixed the issue for me.

**To obtain more information I did following testings**

**Test-1.** I checked my current time zone 
**Result:** it was "**UTC +0**" which was "**Asia/Kolkata**" before the update to WP 5.0. **How did it change?**

**Test-2.** Then I tried to reproduce the error by changing timezone to RTL language countries i.e "Riyadh" (Saudi).  
**Result:** Error reappeared. But gone immediately after page refresh.

**Test-3.** Then I tried 15-20 times to regenerate error by changing and without changing timezone.
**Result:** Error appeared in both cases, sometimes even without changing timezone.

**Test-4.** Then I exercised Yoast block in a random way, ie adding steps, speedy typing, speedy input step change etc
**Result:** The error is not in the whole block, If the error is in step one, step two works fine. It means in my case error is input tag specific.

**Test-5.** So I checked console output in firefox debugging mode.  I took the screenshot of the console in both cases [with error](https://startonlinebusiness.in/wp-content/uploads/2018/12/console-with-error.png) and [without error](https://startonlinebusiness.in/wp-content/uploads/2018/12/console-without-error.png).
**Result:** error appeared in console related to javascripts . 

**My Conclusion:**

In my case it is possible that the error is with javascripts being used by text editors integrated in gutenberg/plugin blocks (based on result of Test-5)
for example: tynymce.min.js ,editor.min.js

this issue needs to be addressed by js expert.

for further testing and error reproducing refer Test-2,3 & 4.

@swissspidy @designsimply 
thanks for support.

**Comment by designsimply** [comment]
Thanks for the additional info!

**Comment by aduth** [comment]
> @arhue thank you for the extra details. Do these testing steps sound right?
> 
> 1. Install WP 4.9.x.
> 2. Set timezone to Asia/Kolkata on the Settings > General page.
> 3. Upgrade to WP 5.0.
> 4. Open any block (e.g. a paragraph block).
> 5. Start typing and check to see if the characters appear in the correct order.

I've run through these steps and have not been able to reproduce. The RichText component which powers text interactions has been largely rewritten between WordPress versions 5.1 and 5.2, and it's quite likely to have resolved (or at least impacted) this behavior.

Issues specific to plugins should be reported to their respective issue trackers. Noting that this has been resolved upstream, there does not appear to be an actionable task here.
