### ISSUE TITLE
Video embeds and full-width / align-wide properties

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#12676]
**Describe the bug**

I don't seem to be able to align-wide or full-width embedded videos using the default Twenty Nineteen theme.

**To Reproduce**

1. Add some fake paragraph.
2. Add some video from vimeo, from example, https://vimeo.com/268831999
3. Choose align-wide or full-width for the video

On the front-end, I expected the video to take the width I assigned in the editor. It looks like it is first assigned that width and then it's scaled back.

Tested on latest versions of both Firefox and Chrome.

**Comment by nosolosw** [comment]
Not sure if this is a known issue and what is causing it, so tagging @notnownikki and @allancole in case it sparks any thoughts.

**Comment by notnownikki** [comment]
tagging @jasmussen as he knows many things about aligns!

**Comment by jasmussen** [comment]
Do you have additional steps? I can't reproduce:

![screenshot 2018-12-07 at 13 05 01](https://user-images.githubusercontent.com/1204802/49646863-c7a24c80-fa20-11e8-9094-c067cab3ea58.png)

![screenshot 2018-12-07 at 13 05 07](https://user-images.githubusercontent.com/1204802/49646867-c8d37980-fa20-11e8-962e-3b1d7fca844d.png)

**Comment by nosolosw** [comment]
mmm, not really. Would it be useful if I share a specific post where this happens (sharing the GIF doesn't really let you catch how the video is scaled down)? See http://nosolosoftware.com/the-worlds-of-ursula-k-le-guin/  Just set the video as full-width.

**Comment by jasmussen** [comment]
I see it, yes. That looks like Jetpack is making the video responsive when it's already responsive. Can you try turning off the jetpack responsive video module and see if that fixes it?

**Comment by nosolosw** [comment]
This is a Jetpack issue that is being tracked at https://github.com/Automattic/jetpack/issues/10678
