### ISSUE TITLE
Undefined index notice in wp-includes/l10n.php on line 915

### ISSUE THREAD

**Issue by jodumont** [WordPress/gutenberg#12670]
upgrade wordpress to wordpress 5
goto edit a page
this message will appear in loop
` Notice: Undefined index: path in .../public_html/wp-includes/l10n.php on line 915`

before wordpress 5, I had the gutenberg extension on everything was working fine

WordPress Address (URL) and Site Address (URL) are the same
Site language is : EN_US
permalink is : /%postname%/

actives plugins
- Yoast SEO
- Super Progressive Web Apps
- Cookie Notice
- W3 Total Cache

**Comment by swissspidy** [comment]
This is already being worked on in https://core.trac.wordpress.org/ticket/45256 as it's a core issue, not a JavaScript issue here in the editor. Please follow that ticket for updates.

**Comment by jodumont** [comment]
@swissspidy thanks for the following but; I don't understand why you are closing an issue when It is not fixed.
if I active the classic editor I don't have this error so it is related to gutenberg.

**Comment by tditlu** [comment]
https://core.trac.wordpress.org/ticket/46387#ticket

**Comment by souare** [comment]
> https://core.trac.wordpress.org/ticket/46387#ticket

it corrected my problem and thanks for the help.
