### ISSUE TITLE
Annoying Scroll behavior in Gutenberg

### ISSUE THREAD

**Issue by skiokko** [WordPress/gutenberg#12679]
Hi guys,

It's incredible that after months of alerts about this big bug on the V5 this issue is still present. 
Seriously, this is not professional.

Thank you

**Comment by designsimply** [comment]
Can you provide any additional details by chance? I'm not sure what scrolling behavior you're referring to and it's possible it's something happening only for a specific set of circumstances or in a specific environment. Would also be possible for you to make a note of your OS, browser, WordPress, and Gutenberg plugin (if you have the plugin) version numbers for reference?

I know there's already an issue on file where there's trouble scrolling when there are a lot of extra menu items added by plugins in the left sidebar and there are also meta boxes involved. Is this also what is happening in your case?
https://github.com/WordPress/gutenberg/issues/11185

**Comment by skiokko** [comment]
Hi, sure. 

It's the same of this:

https://github.com/WordPress/gutenberg/issues/11578

And this:

https://github.com/WordPress/gutenberg/issues/11185

**Comment by designsimply** [comment]
Thanks. I appreciate the feedback as I work to help clarify and sort issues. Since #11185 is open and has ongoing work in #12644, I am closing this issue in favor of those.
