### ISSUE TITLE
Classic block is broken when used in columns

### ISSUE THREAD

**Issue by AlexeySvidentsov** [WordPress/gutenberg#12674]
**Describe the bug**
Its impossible to color Heading through heading block. So i need to use Classic block. But when i use Classic in columns it added correctly but when i refresh dashboard - Editor become unable to edit.

i've got "This block contains unexpected or invalid content." error message

**To Reproduce**
1. Add columns block
2. Inside column add Classic block and add some content to it
3. Update post
4. Refresh page (F5, CTRL + R)

**Expected behavior**
I expected to see Editor that i can edit as usual, and to to convert to html and edit as plain text

**Screenshots**
https://www.screencast.com/t/vcAL42Elccb

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.110

**Additional context**
Wordpress 5.0

**Comment by designsimply** [comment]
Thanks for reporting this issue! It's queued for testing, and in the mean time I thought you might want to check out this plugin which will let you add colors for headings: https://wordpress.org/plugins/advanced-rich-text-tools/

**Comment by starxedsteph** [comment]
I tested adding a classic block inside of a column and was able to replicate the error described.  

I followed the steps to reproduce listed by @AlexeySvidentsov 

1. Add columns block
2. Inside column add Classic block and add some content to it
3. Update post
4. Refresh page (F5, CTRL + R)

After which I get the following error:
<img width="923" alt="screen shot 2018-12-09 at 12 53 40 pm" src="https://user-images.githubusercontent.com/11230557/49701391-7f666400-fbb1-11e8-84b7-4f817b780c58.png">

I also encountered some further errors in testing that I don't believe would be an issue if the original problem is resolved.

I noticed that the error box has an option to convert the block back to the classic editor when clicking the toggle as shown below:
<img width="964" alt="screen shot 2018-12-09 at 12 38 55 pm" src="https://user-images.githubusercontent.com/11230557/49701626-f4d33400-fbb3-11e8-9f38-13740a34d7fa.png">

This works but changes the column widths in the editor only:
<img width="974" alt="screen shot 2018-12-09 at 12 39 02 pm" src="https://user-images.githubusercontent.com/11230557/49701630-01f02300-fbb4-11e8-9091-8435f4da7adc.png">

If you continue to refresh and edit it in this way, the editor removes the second column as well as any content in the column which is visible on the front end.
<img width="916" alt="screen shot 2018-12-09 at 12 50 03 pm" src="https://user-images.githubusercontent.com/11230557/49701639-20eeb500-fbb4-11e8-976d-f0f994323668.png">

Tested in Chrome 70.0.3538.110 macOS Mojave 10.14.1

**Comment by R2116** [comment]
Still present with Gutenberg plugin v 5.0.0. Maybe the JS errors from the console help?
I set up a new WordPress, no plugins besides Gutenberg, no themes besides Twentynineteen.
Same way of reproducing: Creating 2 columns, inserting a Classic Block, Saving, refresh/ switch to Code-Editor and back
![image](https://user-images.githubusercontent.com/15418932/52527586-74bc6e00-2ccb-11e9-92dc-e9c5c3d23ff4.png)

**Comment by talldan** [comment]
Noting these related issues: #14323, #14025, #13187, closing this but keeping #13187 open as it has the most discussion around how to solve the issue
