### ISSUE TITLE
Disabling inline image block

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#12680]
**Is your feature request related to a problem? Please describe.**
The inline block is registered as a paragraph and therefor it cannot be de-registered/black listed. 

**Describe the solution you'd like**
I’d like to be able to black list that block

**Describe alternatives you've considered**
Removing the entire block. It’s pretty confusing and buggy. And from what I can tell you can the same things with a paragraph + an image block that you float. But this alernative feels a bit too aggressive.

**Comment by HarwinBorger** [comment]
I would like to have this feature to block inline-images as well

**Comment by v18** [comment]
I've used the inline image block to add images to lists, like this: https://github.com/WordPress/gutenberg/issues/12396#issuecomment-453152979

**Comment by TeemuSuoranta** [comment]
There should be a way to disable inline image block as there can be post types where no images are allowed. Currently I can restrict the block types on post type with the filter `allowed_block_types` but can't disable inline image block for the post type as long as there is paragraph block.

**Comment by zkingdesign** [comment]
Has someone found a solution to this? I'd really want to remove the 'inline image' block.

**Comment by raphaelportmann** [comment]
Inline images are not standalone blocks but a format type for the RichText Component (which is used for example in the paragraph block).
To disable usage of the inline image format you can use the following code to unregister them from:
`wp.richText.unregisterFormatType('core/image')`

**Comment by erikjoling** [comment]
I can confirm this works (Gutenberg v6.6). Thanks for sharing @raphaelportmann

**Comment by paaljoachim** [comment]
Based on the reply from @raphaelportmann it seems that we can go ahead and close this issue. Please let me know.
@mkaz Marcus do we need to add additional information into the documentation?

**Comment by paaljoachim** [comment]
I will go ahead and close the issue as a solution has been found. Please reopen if I am mistaken.
