### ISSUE TITLE
Right-clicking on the slash inserter menu causes it to dance around the page

### ISSUE THREAD

**Issue by timwright12** [WordPress/gutenberg#12682]
**Describe the bug**
When you right click on the slash inserter menu the menu moves around the page. found this while inspecting an element to run an accessibility test.

**To Reproduce**
1. Create a new post
2. Click in a empty block
3. Type / to open the slash inserted menu
4. Right click anywhere inside the menu

**Expected behavior**
I expect the menu to stay still and not dance around the page.

**Screenshots**
![gutenberg_slash_bug mov](https://user-images.githubusercontent.com/459581/49656793-3032fe80-fa0c-11e8-854b-2475671c1952.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - Browser Chrome
 - Version 70.0.3538.110

**Additional context**
- Gutenberg version: WordPress 5.0 release

**Comment by psdtomanythings** [comment]
Didn't knew that Gutenberg had dancing capabilities too.

**Comment by tellthemachines** [comment]
Closing this issue as I can no longer reproduce it on latest master with latest Chrome, MacOS 10.15.3. Feel free to reopen if the behaviour persists.
