### ISSUE TITLE
Columns pushed to left side by default - No longer fill page width

### ISSUE THREAD

**Issue by mikeh000** [WordPress/gutenberg#12681]
Fresh WP 5.0 Installation

Adding a column block pushes both columns up against each other, all the way to the left. Used to be in previous versions of Gutenberg and all other page builders that columns were equal in width and filled the page content width.

Screencast of unexpected behavior: https://www.screencast.com/t/SYx24Fz3Q
Screencast of how it used to work and expected behavior: https://www.screencast.com/t/2at0xka7FhX

**Comment by GlennMartin1** [comment]
Same here after upgrading to WP 5.0.

This issue is a regression from Wordpress 4.9.8 with Gutenberg 4.6.1.

_(just to clarify: this is a problem only in the editor, not on the front-end)._

**Comment by starxedsteph** [comment]
I tested this on WP 5.0 with and without Gutenberg plugin Version 4.6.1 enabled. I can confirm this happens in WP 5.0 without the plugin enabled.  This is an issue in the editor only and appears identical on the front end with or without the plugin activated as @GlennMartin1 noted.

I've included screenshots below.

<img width="1516" alt="screen shot 2018-12-09 at 11 45 50 am" src="https://user-images.githubusercontent.com/11230557/49700768-bc7a2880-fba8-11e8-9cf1-4ec8800c22df.png">


<img width="1516" alt="screen shot 2018-12-09 at 11 43 13 am" src="https://user-images.githubusercontent.com/11230557/49700775-c308a000-fba8-11e8-831b-e598f883625f.png">


<img width="1455" alt="screen shot 2018-12-09 at 11 44 36 am" src="https://user-images.githubusercontent.com/11230557/49700777-cac84480-fba8-11e8-9bd3-5a0267aaf302.png">


I'd also like to note that this is less apparent with larger blocks of text which fill the columns and force them into the expected view.
<img width="1512" alt="screen shot 2018-12-09 at 11 56 10 am" src="https://user-images.githubusercontent.com/11230557/49700833-95702680-fba9-11e8-9bab-72252049cf2b.png">


Tested in Chrome 70.0.3538.110 macOS Mojave 10.14.1

**Comment by designsimply** [comment]
Thank you for the screencast and screenshots!

**Comment by afercia** [comment]
I think this is already reported in https://github.com/WordPress/gutenberg/issues/11159 and addressed in https://core.trac.wordpress.org/ticket/45442 ?

**Comment by youknowriad** [comment]
I think this is fixed now. The columns block have received a lot of updates in the last releases.
