### ISSUE TITLE
Gutenberg Editor is missing

### ISSUE THREAD

**Issue by maxholgasson** [WordPress/gutenberg#12691]
After updating to 5.0 from the latest wp my Gutenberg Editor is missing. I used the plugin earlier. The pages created with that editor seem to work fine in frontend. In backend only Visual and Text editor is available

**Comment by swissspidy** [comment]
Have you installed the Classic Editor plugin by chance?

**Comment by maxholgasson** [comment]
No, that's not installed. I just figured out that the Gutenberg Editor is showing up when installing another templete like 2019. I dont understand why the backend isnt working anymore but works still on the frontend

**Comment by swissspidy** [comment]
Can you perhaps show some screenshots of the broken editor in the backend? Which theme were you using before?

**Comment by maxholgasson** [comment]
Sure, looks like this.
<img width="835" alt="bildschirmfoto 2018-12-08 um 03 46 05" src="https://user-images.githubusercontent.com/4289347/49681045-de39b980-fa9b-11e8-92f5-9ae02253436a.png">

I'm using this theme without any changes and a child-theme with my custom mods. I also disabled the child-theme but still no gutenberg editor visible

**Comment by swissspidy** [comment]
Good to know this was the cause. And yeah it‘s certainly not ideal :( I‘m sure they are working on compatibility in the long run.
