### ISSUE TITLE
Could not find link options in Image Block

### ISSUE THREAD

**Issue by databell** [WordPress/gutenberg#12705]
When I go to Add an Image Block, I do not see any option to link it.

**To Reproduce**
1. Go to Add a Block and select Image
2. Upload or Select your image.
3. Select how to float it in the icon editor above the image when you select it.
4. There's no link icon to select, so no way to link out.

**Expected behavior**
There should be a link icon just like there is in a paragraph block.
**Desktop (please complete the following information):**
 - MacOS 10.14.1
 - Firefox
 - 63.0.3

**Comment by swissspidy** [comment]
Do you see the link settings in the block sidebar? See screenshot:

<img width="297" alt="screenshot 2018-12-08 at 15 00 25" src="https://user-images.githubusercontent.com/841956/49690653-0f48d700-fafa-11e8-8c96-0f12d94ac5a4.png">

**Comment by designsimply** [comment]
You can find that in Settings > Block > Link Settings:

<img width="1280" alt="screen shot 2018-12-08 at 3 01 58 pm" src="https://user-images.githubusercontent.com/1119271/49690665-52a34580-fafa-11e8-9a34-89d181ed6dbc.png">

**Comment by databell** [comment]
I finally did, but I should be more prominent and easier to use. If I have to spend time search for something that simple, then something is not quite right here.

**Comment by databell** [comment]
Exactly my thought.

**Comment by designsimply** [comment]
Closing as the root issue was resolved by showing where an image can be linked.
