### ISSUE TITLE
Editor background doesn't extend to bottom of the page

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1270]
With a Twitter embed as my first block of the page, the white editor background cuts off:

<img width="1163" alt="screen shot 2017-06-19 at 12 21 30 pm" src="https://user-images.githubusercontent.com/2846578/27295187-f5ebe3cc-54e9-11e7-840f-ef78d5e87380.png">

Looks like it cuts off at the bottom of my viewport, and does not continue past the height of my browser viewport.

**Comment by youknowriad** [comment]
Thanks for the report. Which browser are you using? I can't reproduce on Firefox/Chrome MacOS

**Comment by melchoyce** [comment]
I'm in Chrome 59.0.3071.104 on Mac 10.12.5.

**Comment by melchoyce** [comment]
Looks like the first block doesn't matter; I always see the grey once the post exceeds my viewport height.

**Comment by melchoyce** [comment]
@youknowriad determined this was an [Admin Color Schemes](https://wordpress.org/plugins/admin-color-schemes/) bug, so I'm closing.
