### ISSUE TITLE
I activated Gutenberg plugin and now I can't use

### ISSUE THREAD

**Issue by originalcaroline** [WordPress/gutenberg#12704]
**Describe the bug**
I had originally clicked to use the demo a couple weeks ago and I was creating new posts/editing old posts with the new Gutenberg set up. But yesterday, I went into my plugins and noticed that the Gutenberg plugin wasn't actually activated, which I found strange because I had already been using it. So I went to activate it. Now, when I go to create new posts/edit existing posts, it's the Classic editor, even though I activated the Gutenberg plugin . . . 

So I tried deactivating, and activating again. Same thing, no Gutenberg editor is showing up when I go to edit posts. 

Not sure how to go back to use it, which sucks cause I really like it! 

I'm using Chrome on an Acer Chromebook laptop. And I guess it's the latest version of Gutenberg, whatever version that would be.

**Comment by swissspidy** [comment]
What version of WordPress are you using? If you're running WordPress 5.0, you don't have to use the Gutenberg plugin anymore. If you updated to 5.0, the plugin will be deactivated automatically.

Tip: To find out the version of the Gutenberg plugin you're using, head to the Plugins screen to find out.

**Comment by originalcaroline** [comment]
I believe I did update to Wordpress 5.0 but I thought the whole thing was that updating to Wordpress 5.0 would allow you to edit using Gutenberg no matter what. The version of Gutenberg I have installed is 4.6.1. So how can I go back to using Gutenberg if I've already updated to the latest version of Wordpress?

**Comment by swissspidy** [comment]
Yeah if you're on WordPress 5.0 you don't necessarily need the Gutenberg plugin.

Since you see the Classic Editor though, this might be caused by some other plugin or theme.

Does this still happen when you temporarily disable all plugins and switch to a default theme like Twenty Seventeen or Twenty Nineteen?

**Comment by originalcaroline** [comment]
Interesting, it worked when I deactivated all plugins. So I'll just have to go through each one to see what the culprit is. Thank you so much though!

**Comment by designsimply** [comment]
It would be great to document the conflict once you figure out which one was causing the trouble.

**Comment by originalcaroline** [comment]
I figured it out! The culprit is the PublishPress plugin. Not compatible with Gutenberg.
