### ISSUE TITLE
.wp-block-cover.alignleft/.alignright need a wrapper 'div'

### ISSUE THREAD

**Issue by AbmSourav** [WordPress/gutenberg#12709]
![capture](https://user-images.githubusercontent.com/39233955/49695175-18e94200-fbc1-11e8-82dd-0f71c9ee1363.PNG)
**"wp-block-cover  Align left/Align right" is going out of the main container** 
If I add a cover image with "align left/align right" then it breaks the theme grid layout and goes outside of the main container.

**Solution Proposal** 
A wrapper "div" can solve this problem. By holding The cover image and the very next content of the cover image. When it is Align left/ Align Right.

Please tell me if it has other solutions.

**Comment by kcalkmc** [comment]
Tested WP 5.0, Windows 7, Chrome, Twenty Nineteen theme, multiple tests.
Left/right justifying the Cover image does not break the boundaries of the theme (background color added to highlight) as shown in the sample image. It does change the size and places it with a modest padding.

<div class="wp-block-cover has-background-dim alignright" style="background-image:url(https://wicked-lizard.jurassic.ninja/wp-content/uploads/2018/12/wordcamp-us-2018-vendors3.png)"><p class="wp-block-cover-text">Title is here</p></div>
 
Looks like issue was corrected, 

![wp-issue-12709](https://user-images.githubusercontent.com/9540372/49702666-9aa59380-fbf2-11e8-8750-d686d714a97b.png)

**Comment by AbmSourav** [comment]
first of all, Align left works for twentynineteen because the main content area starts from left.

But if you apply Align right it goes to right side. In a smaller display you can consider it. But just imagine, how its gonna looks like on a larger retina display...

Try to see it from an users angel, an user not gonna identify that it's going out of the content or not. They only see what they can feel. And it feels like it is breaking the design. 

Twentynineteen is not the ony theme. Other theme has multiple columns layout. On those themes it will create more problems.

**Comment by youknowriad** [comment]
I don't think there's anything actionable here. align right floats the image to the right. That's the expected behavior. Whether it goes to the right of the window or inside a container (limit), that's the responsibility of the theme.
