### ISSUE TITLE
Implement term pages and 'system pages' in WordPress

### ISSUE THREAD

**Issue by atimmer** [WordPress/gutenberg#12707]
WordPress has traditionally had only a simple textarea to change the description of a category or tag. For a long time Yoast SEO has had a feature that replaced this simple textarea with a TinyMCE editor instance. The reason for this is that term pages are very often of incredible SEO value.

The most obvious example of this is for webshops, where it is very hard to rank for a specific product like a bag, unless someone is searching for that specific brand of bag. What most webshops do instead is rank for the category of thing. So they rank for the word bag instead. This is then done by the `Bag` category and that lists all the bags available on the site.

This has been fairly awkward to use because the user has no control over the placement of the description on the term page. So other than adding a description and hoping the theme puts it somewhere useful, there is no other way for a user to exert control over their term pages.

With Phase 2 this can be improved. The first step is to add the block editor to the the term edit screen. The second step is adding a `Posts for Term` block, that lists all the posts in the term. This combination allows the user to customize their term pages the way they want.

Expanding on this, the same logic applies to what I call 'system pages'. Pages that are automatically generated with fixed content, but have to be on the site: The homepage, author pages, etc. All these pages have a fixed block: `All Posts`, `Posts for Author`, etc. The homepage one allows us to drop the weird homepage setting. If the user doesn't want a post overview on their homepage they can remove the `All Posts` block. If we allow the `Posts for Term` and `Posts for Author` block on any page, the homepage can also be customized with these block options.

@youknowriad @alexislloyd: Phase 2 leads
@omarreiss, @jono-alderson: You probably have ideas about this.

**Comment by benoitchantre** [comment]
Will that cover also custom post type archives? It’s not rare to need an introduction before the posts.

**Comment by atimmer** [comment]
@benoitchantre I would think so as these have the same semantics.

**Comment by youknowriad** [comment]
I would think that the solution that we come up with here should apply to any dynamic page from the WordPress template hierarchy.

I do think though that this is something that will come a bit later in the phase2 timeline. I expect initial focus would be around: "Widget blocks", "Menu block", and then maybe templates for static pages and then templates for dynamic pages.

**Comment by benoitchantre** [comment]
Thank you for your inputs. What would be your recommendation for theme authors as a temporary solution: a widget area before the posts, a `textarea` control in the customiser or something else?

**Comment by oxyc** [comment]
When WordPress is used to build anything other than a blog, category pages and archive pages are very important for SEO value in my experience. Unlike a photo blog where everyone knows what the _"Landscape"_ category is about, on a company website users might actually look for information when they click on _"Recipes"_ or the _"Trådlös"_ IKEA category. And if not the user, Google is very interested as I might just search for _"IKEA Trådlös"_. These pages a great for highlighting featured content with _Cover images_ and other _Media and text_ content.

Having these fundamental differences also makes things very difficult for designers who have to understand when a particular page is in fact a _page_ and when it's a _category page_ or an _archive page_. As the rules change, whatever cover image they used on the front page won't exist anymore on an archive page.

**Comment by ghost** [comment]
@atimmer With the new templating possibilities in FSE, is this issue still relevant or can it be closed?

**Comment by youknowriad** [comment]
Yeah, I think this can be considered solved with block themes and site editor. Maybe we still need to provide some options in the "new template" dropdown but the crux of the issue is fixed.
