### ISSUE TITLE
Post title line-height seems high

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1271]
Current line-height is 1.8, which feels very high:

<img width="677" alt="screen shot 2017-06-19 at 12 14 34 pm" src="https://user-images.githubusercontent.com/2846578/27295277-5538c7dc-54ea-11e7-8d30-321deef225b2.png">

What about something more like 1.4?

<img width="684" alt="screen shot 2017-06-19 at 12 26 08 pm" src="https://user-images.githubusercontent.com/2846578/27295329-8184482a-54ea-11e7-833e-f15ce4038e21.png">

**Comment by georgeolaru** [comment]
Nice detail @melchoyce — definitely better! It can be even lower as long as the ascenders and descenders don’t collide.

@jasmussen I know it might not be related specifically to this issue but are there any plans for an  Editor Style support, as it is included currently in the TinyMCE editor? In this case, the line height will be better set by the theme, according to the font used.

**Comment by jasmussen** [comment]
> I know it might not be related specifically to this issue but are there any plans for an Editor Style support, as it is included currently in the TinyMCE editor? In this case, the line height will be better set by the theme, according to the font used.

Yes, tracked partially in #422. I know @mtias also has some ideas for a superior replacement that would essentially be like a live preview.

**Comment by aduth** [comment]
Closed by #1306
