### ISSUE TITLE
Converting meta boxes not associated with specific Gutenberg block

### ISSUE THREAD

**Issue by daext** [WordPress/gutenberg#12710]
On multiple plugins we have to convert meta boxes used to store meta data to Gutenberg, but these meta data should not be associated with specific Gutenberg blocks.

I posted the question with details and a screenshot in the forums and would be great if you can share your opinion on this. The Gutenberg handbook doesn't provide an official solution and we have to decide how to proceed.

**Should we really create an alternative Gutenberg general setting like is doing Yoast SEO?**

**Is this a recommended solution or a hack?**

[https://wordpress.org/support/topic/convert-meta-boxes-used-to-store-meta-data-to-gutenberg/](https://wordpress.org/support/topic/convert-meta-boxes-used-to-store-meta-data-to-gutenberg/)

I think that this is a common problem and a solution should be documented.

Thank you.

**Comment by swissspidy** [comment]
You could totally create a block that functions like a meta box, can only be used once, and stores data in post meta. However, in your case it probably makes most sense to use the plugin sidebar feature.

See https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-plugins/.

**Comment by daext** [comment]
Thank you very much, would you mind to add a reference so I can understand what you mean and study this part:

> You could totally create a block that functions like a meta box, can only be used once, and stores data in post meta.

We need a block that is not added in the content because for the meta data we use in many plugin there is no association between the block we need and the content and would not make sense for the plugin users to add a block in the content for these meta data.

**Comment by swissspidy** [comment]
What I meant with that is that you can create blocks that won't be visible in the post content in the front end. Again, for your use case the plugins API is better suited.

**Comment by daext** [comment]
Perfect. Thank you.
