### ISSUE TITLE
h1 - h2 - h3 Colors Option

### ISSUE THREAD

**Issue by mmhalat** [WordPress/gutenberg#12711]
Hi there,

am i give spesific color h1-h2-h3 tag? or not? if i dont why this is very basic feature for editor.
or h1,h2,h3 background color like paragraph. why i dont add this?

Thanks.

**Comment by bupotalovo** [comment]
@mmhalat Yes, these basic (actually required for proper backwards compatibility) features are missing. Similar problem exists e.g. for single words in a paragraph or for lines / words etc. within list block...

You have to install another [extra plugin](https://wordpress.org/plugins/advanced-rich-text-tools/) to get those features back. Wondering why this is not in 5.0 core? Plugin author is in core and Gutenberg team…

This gets asked a lot, a few examples:

- https://github.com/WordPress/gutenberg/issues/5105
- https://github.com/WordPress/gutenberg/issues/6080
- https://github.com/WordPress/gutenberg/issues/7131
- https://github.com/WordPress/gutenberg/issues/8844
- https://github.com/WordPress/gutenberg/issues/9826
- https://github.com/WordPress/gutenberg/issues/9868
- https://github.com/WordPress/gutenberg/issues/12248
- https://github.com/WordPress/gutenberg/issues/12282
- https://github.com/Automattic/wp-calypso/issues/29264
- ...

**Comment by mmhalat** [comment]
Thanks for your reply my friend.

I dont want to install other plugin just this feature. This is very basic thing. 
Maybe some wordpress developer see that topic :) Just we hope that 😆

**Comment by designsimply** [comment]
Thank you for the suggestion. There is already an issue open for this at #6012 so let's consolidate there.
