### ISSUE TITLE
Gutenberg just trashed a complete article

### ISSUE THREAD

**Issue by kaffeeringe** [WordPress/gutenberg#12727]
I have always loved about Wordpress, that no matter what happend to my browser or my internet connection: the content I produce is save. My old CMS used to trash content, when it figured something harmful in a text...

Today I wrote the first article after upgrading to Wordpress 5.0 and it simply trashed my article:

1. I started writing.
2. I took a break for dinner and left the browser open.
3. I finished the article and clicked on "preview"
4. The preview took ages to be build - I closed that tab and saw, the edit tab was still saving. A simple text of maybe 12 paragraphs and 2 headings.
5. I opened a new tab with the list of blog posts and found the article in the trash. 
6. I restored the article.
7. It was empty.
8. I looked into the database. No old revisions. 

This is the one thing that should never ever happen!

**Comment by designsimply** [comment]
I agree that shouldn't happen. I will try to see what I can do to figure out to get a post to break in the same way. In the mean time, did this happen only the one time or has it happened more than once?

**Comment by kaffeeringe** [comment]
It hasn't happen again. But I am only working on my third blogpost.

**Comment by designsimply** [comment]
Hey! I haven't seen any new reports of this and haven't seen it happen in my own testing, so I would like to close this issue and ask that you either reply again here or start a new issue if it happens again. Thank you for the original report and thank you doubly if you can confirm whether this is a continued problem so we can re-open it at that time!
