### ISSUE TITLE
incorrect display of permalink address in editor

### ISSUE THREAD

**Issue by Dedi-Data** [WordPress/gutenberg#12729]
Hi,

I am not sure that this problem is related to Gutenberg or not,
Because it is related to edit/create posts , ...
I created a ticket here as usual:
https://core.trac.wordpress.org/ticket/45556

Regards

**Comment by desrosj** [comment]
Adding more details:

**To Reproduce**
Steps to reproduce the behavior:
1. Assign a RTL language as the site's default.
2. Edit a post.
3. Click the post title.
4. Observe the permalink field above and in the side panels.

**Screenshots**
![direction](https://user-images.githubusercontent.com/359867/50045749-905a1e00-0066-11e9-8e3d-45f8100328b5.jpg)

![direction2](https://user-images.githubusercontent.com/359867/50045752-93550e80-0066-11e9-8b2c-58bfc5d9f954.jpg)

**Comment by apermo** [comment]
I think my issue is the same problem as this one. If not please notifiy me.

Umlaute are displayed wrong before being saved. Same for - and space should not be doubled.

Before publishing:
![image](https://user-images.githubusercontent.com/4695889/51259525-a4b67100-19ac-11e9-88e6-768cf4c3eb0e.png)

Once its published the URL ist displayed correctly

![image](https://user-images.githubusercontent.com/4695889/51259634-d62f3c80-19ac-11e9-9a6c-30a99a4d8e8c.png)

**Comment by Dedi-Data** [comment]
@apermo This is another issue
