### ISSUE TITLE
Still no support for pages? 

### ISSUE THREAD

**Issue by webdados** [WordPress/gutenberg#1272]
When clicking the Gutenberg link on a page we're taken to a blank content editor that, after saved, becomes a post.

![image](https://user-images.githubusercontent.com/6853605/27298330-1a42e6b8-5520-11e7-90d2-f03af059aa5c.png)

![image](https://user-images.githubusercontent.com/6853605/27298351-2b60fa8e-5520-11e7-8df2-ad099bfcc5ea.png)

**Comment by westonruter** [comment]
No, pages aren't supported. In the immediate term, the quick edit link should be limited to posts. 

To support pages and other custom post types, the following places will need to be reworked (at least):

* https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L318-L324
* https://github.com/WordPress/gutenberg/blob/cab871366f20330f54365323f790b27141209691/editor/effects.js#L46
* https://github.com/WordPress/gutenberg/blob/cab871366f20330f54365323f790b27141209691/editor/effects.js#L82

**Comment by webdados** [comment]
I also recommend mentioning the non-page compatibility on WordPress.org description, because the third paragraph may lead to confusion:

> The new post and page building experience will make writing rich posts effortless, making it easy to do what today might take shortcodes, custom HTML, or “mystery meat” embed discovery.

**Comment by westonruter** [comment]
Hopefully the page editing support can be added in short order and that won't be necessary.

**Comment by mtias** [comment]
Let's try to get this before the next release (this Friday).

**Comment by GaryJones** [comment]
Potentially related: #1356
