### ISSUE TITLE
Overlay panels for editing html

### ISSUE THREAD

**Issue by irishetcher** [WordPress/gutenberg#12733]
Having a workspace that is big enough to work on HTML/code has always been absent from WordPress. On top of this the right tools to go along with this have also been missing, an editor that matches that of a good IDE. 

I hear mention from Matt and Joen that there there will be code mirror 6 for this.  I also see that Yoast is using an overlay for Snippet preview. I suggest that an overlay would be useful for the Edit as HTML view.
![gutenberg-overlay-editor](https://user-images.githubusercontent.com/6097298/49702178-6b405800-fbed-11e8-8e6a-b7662791e8eb.jpg)

**Comment by designsimply** [comment]
Thank you for the suggestion! I am closing this issue and putting it in the Ideas project where it will be reviewed and considered and may be re-opened at a later date if approved.
