### ISSUE TITLE
Is it possible to group multiple checkboxes?

### ISSUE THREAD

**Issue by pryley** [WordPress/gutenberg#12732]
I am building a custom block based on a shortcode. I have a use-case where I am using checkboxes that toggle their value in an attribute option array when checked (similar to using a multi-Select element). I need them grouped visually.

Is this possible to do and if so, how?

## Individual checkboxes:
<img width="772" alt="edit page site-reviews wordpress 2018-12-09 23-10-26" src="https://user-images.githubusercontent.com/134939/49701657-486f6d00-fc08-11e8-8568-7f7babb386b2.png">

## Grouped checkboxes:
<img width="771" alt="edit page site-reviews wordpress 2018-12-09 23-13-55" src="https://user-images.githubusercontent.com/134939/49701658-532a0200-fc08-11e8-911f-5087c96120f5.png">

**Comment by pryley** [comment]
The only way I can figure out to do this it is by writing the BaseControl and CheckboxControl components manually, something like this: 
```js
el( 'div',
    { className: 'components-base-control' },
    el( 'div',
        { className: 'components-base-control__field' },
        el( 'input', {
            id: 'inspector-checkbox-control-hide-0',
            type: 'checkbox',
            value: '1',
            onChange: toggleHide.bind( props, 'if_empty' ),
            className: 'components-checkbox-control__input',
        }),
        el( 'label', {
            className: 'components-checkbox-control__label',
            htmlFor: 'inspector-checkbox-control-hide-0',
        }, __('Hide if empty'))
    ),
    el( 'div',
        { className: 'components-base-control__field' },
        el( 'input', {
            id: 'inspector-checkbox-control-hide-1',
            type: 'checkbox',
            value: '1',
            onChange: toggleHide.bind( props, 'bars' ),
            className: 'components-checkbox-control__input',
        }),
        el( 'label', {
            className: 'components-checkbox-control__label',
            htmlFor: 'inspector-checkbox-control-hide-1',
        }, __('Hide the bars'))
    )
    // ...
)
```

The only problem is that I don't know how to get the instance ID so am having to create my own ID.

There must be a simpler (more concise) way to do this...

**Comment by designsimply** [comment]
Based on the screenshots, it looks like you're trying to reduce the vertical spacing between the checkboxes, is that right? 

I am new to JavaScript, so I don't know if there's a better way to do the BaseControl and CheckboxControl components, but I was wondering if you could resolve the problem using CSS in your custom block?
