### ISSUE TITLE
How can I get the ID of the page being edited from within the render_callback function?

### ISSUE THREAD

**Issue by pryley** [WordPress/gutenberg#12744]
How can I get the ID of the page being edited from within the `render_callback` function?

Normally I would just use `$postId = filter_input( INPUT_GET, 'post' );` or `get_post()` ... However, the problem is that when editing the page, it calls the render_callback method TWICE when it is loaded and the second (last) request is from the REST API so none of those methods above work.**

The **first** time it is called, it returns the $_GET request of the page load along with the block attributes:

```
[2018-12-09 21:38:09|Blocks/SummaryBlock.php:52] DEBUG: Array
(
    [0] => Array
        (
            [post] => 643
            [action] => edit
            [classic-editor__forget] => 
        )
    [1] => Array
        (
            [title] => Hello
            [assigned_to] => post_id
            [type] => 
            [category] => 
            [hide] => 
        )
)
```

The **second** time it is called it returns the REST request along with the block attributes:

```
[2018-12-09 21:38:10|Blocks/SummaryBlock.php:52] DEBUG: Array
(
    [0] => Array
        (
            [context] => edit
            [attributes] => Array
                (
                    [title] => Hello
                    [type] => 
                    [category] => 
                    [assigned_to] => post_id
                    [hide] => 
                )

            [_locale] => user
        )
    [1] => Array
        (
            [title] => Hello
            [type] => 
            [category] => 
            [assigned_to] => post_id
            [hide] => 
        )
)
```
Obviously the second time it is called it overwrites the previous $_GET request (as it happens last).

So it seems there is no way to get the ID of the page being edited?

1. The block uses ServerSideRender:

```js
el( ServerSideRender,
    {
        block: 'my-block/summary',
        attributes: props.attributes,
    }
)
```

2. The `render_callback` method renders a shortcode.

3. The shortcode uses an attribute whose value can either be a post ID or “post_id”. If the value is “post_id”, then it automatically uses the post ID of the current page. However, this doesn’t work in the editor unless I can get the ID of the page being edited.

**Comment by pryley** [comment]
The workaround I am using is to pass the post_id of the page along with the attributes:

`props.attributes.post_id = jQuery('#post_ID').val();`

**Comment by noisysocks** [comment]
Hi @pryley! Try something like this:

```php
function my_render_callback( $attributes, $content ) {
	global $post;
	echo $post->ID;
}
```
