### ISSUE TITLE
WP Code Block: not displaying number 0 within [0]

### ISSUE THREAD

**Issue by sumnermic** [WordPress/gutenberg#12749]
**Describe the bug**
The code block does not display the number 0 within square brackets [], e.g. 
`$custom_logo[0]` outputs as `$custom_logo[]`

**To Reproduce**
1. Click on 'code block'
2. Type in e.g. `[0]`
3. Preview/publish post. It will not output the `0`, hence `[]`

**Expected behavior**
To output the `0` between `[]`, so `[0]`.

**Screenshots**
![image](https://i.ibb.co/8KVp1gY/Screenshot-2018-12-09-at-23-27-39.png)

**Desktop (please complete the following information):**
 - OS: `macOS`
 - Browser `Chrome`
 - Version `70.0.3538.110`

**Additional context**
From WordPress 5.0

**Comment by crischogoldpilz** [comment]
Same or similar here: Content inside square brackets is not shown in preview mode using the code block of Gutenberg:
I used several code examples for a contact form in a code block. Some show up, some not.
Example that shows up: `<label> Name  [text* your-name] </label>` 
Example that doesn't work: `<label> Calculate 
[quiz quiz-11 "3+3?|6" "7*3?|21" "8-2?|6" "10:5?|3"] 
</label>`
Workaround: Using the html code `&#91;` to replace the opening bracket works one time. But after saving the post a second time, the html code is replaced by a bracket again, and the content doesn't show up again.
WP Version is 5.0.3.

This is my first comment here, hopse that the coded parts show up.

**Comment by swissspidy** [comment]
Both examples work fine here using WordPress 5.1.

Can you please test this using the latest version of WordPress and after disabling all plugins and when using a default theme like Twenty Nineteen?

Thanks.

**Comment by crischogoldpilz** [comment]
You are right. Thank you. I tested it. In my case it is plugin related. Jetpack activating/deactivating turns this problem on and off. With Jetpack deactivated, there is no problem.
