### ISSUE TITLE
Wrapper div from RawHTML not stripped for shortcode blocks

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#12756]
**Describe the bug**

A few releases back, the result of a shorcode was directly rendered without a wrapping div. Now there is a `<div class="">` wrapped around in the frontend, what makes it hard to – in my example – make specific blocks wider than the normal content width. In the `RawHTML` core it sasy that the `div` is stripped by the serializer if no additional props are present. As far as I see, it seems that there are no additional props?

I tried to fix that for me via adding wide align to the shortcode block in the `blocks.registerBlockType` filter, but after reloading a wide aligned shortcode in the editor, it says that the `alignwide` class is unexpected.

**To Reproduce**
1. Insert a shortcode.
2. Save the content.
3. Go to the frontend and inspect the source code.
4. See `div` around shortcode.

**Expected behavior**

The shortcode’s content should be output without a wrapper div.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 65.0a1 (2018-12-08) (64-Bit)

**Additional context**
- Gutenberg version contained in WordPress 5.0

**Comment by draganescu** [comment]
hi @florianbrinkmann ,

It would be very useful if you'd tell us which shortcode you used. Is it one of the built in ones, or a shortcode provided by a theme or plugin?

I have tested with an embed and an image caption shortcode and none of them had the `div` wrapper.

**Comment by florianbrinkmann** [comment]
Hey @draganescu,

it was a plugin shortcode. Just gave it a try and there is no wrapper anymore, so it seems a release fixed it.

Best,
Florian
