### ISSUE TITLE
Viewing the HTML for an Image Block with alignment shows the block container HTML

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12750]
**Describe the bug**
I couldn't think of a better way to describe it in the title, so feel free to change that if need be.

When you view the HTML for an image block that has no alignment, all you see is the `<figure>` tag.

![screenshot_1004](https://user-images.githubusercontent.com/2078245/49708993-4ba93e00-fc86-11e8-9871-021c8b21a624.png)

When you view the HTML for an image block WITH alignment, you see the `<figure>` tag and also the enclosing `wp-block` div. This means that it's really easily to break the block. For example, if someone was to edit the html and remove the `wp-block-image` class, it immediately breaks the block.

![screenshot_1005](https://user-images.githubusercontent.com/2078245/49709072-afcc0200-fc86-11e8-99e5-865cedf7e9d3.png)

**To Reproduce**
1. Insert Image block and add image to it
2. Right align image block
3. Select the block, click the 'More Options' toolbar icon and click 'Edit as HTML'
4. View the html that's displayed and see that it's different to an image block that isn't aligned

**Expected behavior**
Aligned Image blocks shouldn't show the containing `wp-block-image` div.

**Desktop (please complete the following information):**
 - macOS Sierra
 - Firefox Quantum 63.0.3
 - WP 5.0

**Comment by talldan** [comment]
This was tested during our core editor triage (https://wordpress.slack.com/archives/C02QB2JS7/p1564037097209900 - slack link requires a slack account).

It still seems to be an issue. Seems fairly minor, but it is an inconsistency that might be good to solve.

**Comment by youknowriad** [comment]
I don't think there's any bug here. It just shows the fact that the markup generated for an image with alignment (left, right, center) and the other ones are different.  (these alignments require an extra div)
