### ISSUE TITLE
Action post_submitbox_misc_actions is not working anymore

### ISSUE THREAD

**Issue by momala454** [WordPress/gutenberg#12764]
**Describe the bug**
Hello, i was using the action post_submitbox_misc_actions to modify the area around the "publish" button (so the right part) of the page to create/edit a post, but this action is now never called anymore.

**To Reproduce**
Create or modify a post, the action is not called

**Expected behavior**
the action should be called so i can modify the area to add a button by example

wordpress 5.0

**Comment by momala454** [comment]
thanks but how can i write in php ? as i need to do some handling in php to display specific text on the interface
and of course that should be only visible for users with publishing permissions

**Comment by swissspidy** [comment]
You could write some logic in PHP and make that available to the JavaScript component via inline JS or via the REST API.

**Comment by MGParisi** [comment]
This appears to have broken mt site as well.  A working solution to this would help.

**Comment by momala454** [comment]
bump please

**Comment by Blackbam** [comment]
Destroyed also some of my Plugins - does anybody know a fix for this?

**Comment by swissspidy** [comment]
As mentioned in https://github.com/WordPress/gutenberg/issues/12764#issuecomment-445998137, the `<PluginPostStatusInfo>` component might be a good fit for this.

There's also `PluginPrePublishPanel`, depending on your needs.

Check the examples at https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-edit-post/

**Comment by youknowriad** [comment]
This has a solid answer. Closing.

**Comment by youknowriad** [comment]
There's also a tutorial to show how to create this kind of plugins https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/
