### ISSUE TITLE
When replacing current image with differant image, have to do it twice.

### ISSUE THREAD

**Issue by boblmckee** [WordPress/gutenberg#12769]
When updating/replacing image already on page by clicking the Edit pencil and selecting Replace then selecting new image, nothing changes. I have to do it twice in order for it to replace original image.

**Comment by molszewska** [comment]
Tried to reproduce the same issue on my end (Simple site) and it seems to work!

**Comment by sourourn** [comment]
Tested this on my site, I was not able to replicate this issue - the image got replaced immediately.

WordPress Version 5.2
Browser: Firefox 61.0.2

**Comment by youknowriad** [comment]
Thanks for the tests, let's reopen the issue if we have more details about how to reproduce it.
