### ISSUE TITLE
The visual editor is not available

### ISSUE THREAD

**Issue by Gmulti** [WordPress/gutenberg#12760]
**Describe the bug**
The visual editor + code editor is not available.
However, the box at the user profile level is not checked.
Any ideas?

**To Reproduce**
No ideas... I didn't do anything special.

**Screenshots**
<img width="289" alt="capture d ecran 2018-12-10 a 12 32 24" src="https://user-images.githubusercontent.com/5682535/49730901-01ba5b00-fc7a-11e8-97da-ce0db715386f.png">
<img width="634" alt="capture d ecran 2018-12-10 a 12 49 36" src="https://user-images.githubusercontent.com/5682535/49730925-126ad100-fc7a-11e8-8cc1-dfdac5855f3c.png">

**Comment by torres126** [comment]
Unless I'm missing something, when on https://wordpress.org/gutenberg, I see the same issue as you and can't switch to the Visual or Code Editor. That's on a Mac OS X 10.6.8 using Chrome 49. When I'm on my Samsung Galaxy Tab S2, this isn't an issue and I can switch to the Visual or Code Editor just fine.

As such, I'm guessing that this is related to the device being used then.

**Comment by designsimply** [comment]
If you haven't already, can you try clearing your browser cache and cookies and check to see if that makes a difference?

<blockquote>That's on a Mac OS X 10.6.8 using Chrome 49. When I'm on my Samsung Galaxy Tab S2, this isn't an issue and I can switch to the Visual or Code Editor just fine.</blockquote>

Strange! Do you have any browser extensions installed by chance? @torres126, for your case, are you really using Chrome 49? The latest version of Chrome is 71.

**Comment by ElYi** [comment]
My Edge is 42.17134.1.0
My Chrome is 71.0.3578.80 (Official Build) (64-bit)

**Comment by torres126** [comment]
My only browser extention is a tool for screenshots and a VPN (which I wasn't using). And yup, Chrome 49 is really outdated, but unfortunately my computer doesn't support updating it.

(I'll try cache & cookies tonight)

**Comment by Gmulti** [comment]
Whether it is on Chrome (latest version) or Firefox, it doesn't work.
If I'm ever on macOS High Sierra.
But it seems strange to me that it comes from a "customer" environment because I only have one site that causes me this error...
I use WP 5.0 (but it still didn't work with the plugin)

It's a custom theme, but everything works locally, it's really only on the production that it doesn't work.

**Comment by torres126** [comment]
Just to note, clearing cache and cookies fixes the issue for me. 👍

**Comment by Gmulti** [comment]
Nothing changes, all administrators have the same problem.
Is there not a value / option in the database that I could check to understand what is happening?
Where in Gutenberg can the code / visual editor be disabled?

**Comment by jrsconfitto** [comment]
I'm seeing the same thing. I created [a support forum post][sp] last week.

I see this problem and also see an inability to create a block on my posts, similar to issue #12927 that I also just discovered and commented on. *Is anyone else unable to create a block when they no longer have access to the visual + code editor?*

[sp]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/

**Comment by designsimply** [comment]
@torres126, ace! Thanks for following up!

@Gmulti @jrsconfitto there is a lot of very good detail posted in https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/ and I think we should continue the conversation there.

https://github.com/WordPress/gutenberg/issues/12927 does appear to be a duplicate and I would like to see if we can consolidate these two reports into one and wondering if you might add any new details to the other issue?

All of the related issues I'm seeing to seem to indicate this problem may be caused by some sort of server config conflict but I am not sure what it could be yet!
