### ISSUE TITLE
Select text twice in order to change style

### ISSUE THREAD

**Issue by boblmckee** [WordPress/gutenberg#12770]
Select text, scroll to top and select a new text style (bold, H2, etc.) then text gets deselected. Must go back and select text again, and apply style for second time.

**Comment by youknowriad** [comment]
I can't reproduce personally, maybe a conflict with a browser extension or another plugin?

**Comment by designsimply** [comment]
I tested with WordPress 5.0.2 and no active plugins with Firefox 63.0.3 on macOS 10.13.6 using the steps provided and was unable to reproduce the problem. I tested both with a long paragraph block and with a classic block, and I tried from Fullscreen Mode and Top Toolbar and without. The part about needing to scroll up is strange. The toolbar should stay fixed to the top of the screen when you scroll either in the paragraph block or the classic block.

Please check to make sure you have updated to the latest stable version of WordPress and also deactivate all plugins. If the problem persists, please re-open this issue and note the version of WP you tested with, your OS and browser versions, and also note whether you are using a paragraph block or a classic block or some other block and which editing mode you are using (i.e. Fullscreen Mode, Top Toolbar, neither).
