### ISSUE TITLE
Button to Code editor

### ISSUE THREAD

**Issue by boblmckee** [WordPress/gutenberg#12771]
I use the Code editor a lot. I would prefer it to still be a button to toggle between visual and code.

**Comment by swissspidy** [comment]
Hi there

If you click on the three dots in the upper right corner, a new menu opens which contains some useful options — including links to switch between the visual and code editor.

See this screenshot for an example:

<img width="327" alt="screenshot 2018-12-11 at 09 46 20" src="https://user-images.githubusercontent.com/841956/49788480-beb7c080-fd29-11e8-8d0b-6e6d4292d0a0.png">
