### ISSUE TITLE
Get list of registered blocks

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12775]
I have the same question as #12219 but I'm interested in how to list all registered blocks in Chrome's Console (JavaScript)?

The documentation list is not up-to-date here: https://codex.wordpress.org/Gutenberg

**Comment by swissspidy** [comment]
It'd be easier to keep similar questions in one place, but have you tried the `getBlockTypes` function from the `@wordpress/blocks` package?

It uses the data package internally, so this would be equal to running `wp.data.select( 'core/blocks' ).getBlockTypes()` in the Chrome dev tools. This gives you a list of all registered block types, from both core and plugins.

Please note that for up-to-date Gutenberg documentation I would advise against using the Codex. Try the Gutenberg Handbook instead: https://wordpress.org/gutenberg/handbook/

**Comment by manake** [comment]
Awesome. Thank you.

**Comment by boospot** [comment]
To fetch the list of all registered blocks in the JS, we can do something like this:
`wp.blocks.getBlockTypes()`

you may try this in browser console.

Also, to get a list of blocks for a particular namespace, you may use something like this:

`wp.blocks.getBlockTypes().filter((block) => { return block.name.indexOf('core') !== -1});`
(This will list all blocks with namespace 'core')

**Comment by mvaleno** [comment]
How do you expose this method to the console? If I try the above I get undefined for: getBlockTypes()

**Comment by swissspidy** [comment]
It‘s wp.blocks.getBlockTypes(), not just getBlockTypes()

I recommend checking the block editor handbook for details & the forums for further help.

**Comment by mvaleno** [comment]
I did use  wp.blocks.getBlockTypes(), the console gave undefined on the method part .getBlockTypes().

I will look into documentation.  Thank you!

**Comment by swissspidy** [comment]
Works like a charm in latest WP version:

<img width="1728" alt="Screenshot 2022-04-13 at 10 38 30" src="https://user-images.githubusercontent.com/841956/163135954-00798790-c7fc-4ad1-8468-05450fd8f7d8.png">

**Comment by isuke01** [comment]
@swissspidy Any idea how to make it work inside edit hook?
If you do` import { getBlockTypes } from ''@wordpress/blocks`
And then call it. it just return blocks that ware registered up to this point, which make it a bit useless e.g if I'd like to do filter for `templateLock` Since here I'd like to have list of all blocks.
