### ISSUE TITLE
Parameters to reusable block

### ISSUE THREAD

**Issue by leifnel** [WordPress/gutenberg#12777]
I may not understand the flexibility of reusable blocks, but it appears one reusable block always render the same html whereever it is used.

Is it possible to have a reusable block with a shortcode, eg [somecode category=$kat .. many other options] and then define $kat somewhere previous to the block, 

Example: Show posts with category 7 on one page,category 9 on another.

**Comment by swissspidy** [comment]
> I may not understand the flexibility of reusable blocks, but it appears one reusable block always render the same html whereever it is used.

Yes, that's intended use case :-)

What you are imaging can certainly be achieved, but not with reusable blocks — or at least not out-of-the-box.

Instead, this sounds like a perfect opportunity to create your own block. This block could be as simple as containing a single input field to choose the category.

On the front end, you'd then display all posts within that category 

The [Designer & Developer Handbook](https://wordpress.org/gutenberg/handbook/designers-developers/) contains lots of information about how to create your own blocks.

**Comment by aduth** [comment]
Closing, as it appears the question has been addressed.
