### ISSUE TITLE
Quote: Content not being output

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1277]
What I see in Gutenberg:

<img width="717" alt="screen shot 2017-06-19 at 3 33 27 pm" src="https://user-images.githubusercontent.com/2846578/27302372-d3aa7ec0-5504-11e7-987a-dd48815a8432.png">

What I see on my site:

<img width="769" alt="screen shot 2017-06-19 at 3 33 35 pm" src="https://user-images.githubusercontent.com/2846578/27302375-d83bbd1e-5504-11e7-93ef-fef2681171b0.png">

The entire block HTML being output:

```
<blockquote class="blocks-quote-style-1">
<footer>Julie Zhuo, <a href="https://medium.com/the-year-of-the-looking-glass/no-no-no-97cfd94321c8">No No No</a></footer>
</blockquote>
```

Is this a theme compatibility issue?

**Comment by youknowriad** [comment]
This doesn't look like a theme issue, The content is not included in the markup. 
Not certain but #1260 is more likely to close this.

**Comment by melchoyce** [comment]
I think I figured it out! The quote I pasted in was inheriting some extra markup (spans with font/color styles attached). When I repasted from a clean source, the quote showed up.

**Comment by kopepasah** [comment]
@melchoyce are you happy closing out this bug or do you feel it needs more attention?

**Comment by melchoyce** [comment]
It still feels like a bug, if a minor one.

**Comment by youknowriad** [comment]
I think it's kind of duplicate to the pasting issues #1442

**Comment by kopepasah** [comment]
@melchoyce I am going to close this in favor of #1442. If you feel 1442 does not fix this issue or it still exists once 1442 is merged, let's reopen.
