### ISSUE TITLE
Can't set the URL in a Button Block to open in new tab

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12783]
**Describe the bug**
URL's in Button Blocks should have the option to open in a new tab, just like URL's added to links in Paragraph Blocks.

**To Reproduce**
1. Add Button Block
2. Add URL and try to get it to open in a new browser window/tab

**Expected behavior**
All URL fields in Gutenberg should have the option to be opened in a new tab.

**Desktop (please complete the following information):**
 - macOS Sierra
 - Firefox Quantum 63.0.3
 - WP 5.0

**Comment by soup-bowl** [comment]
I tried editing it in HTML mode to add the `target="_blank"`, but once back to block mode it detects it as invalid, and converts it to a HTML block instead.

**Comment by annestk** [comment]
Adding that this has also been suggested in #8000

**Comment by cameronjonesweb** [comment]
I'm finding I'm needing this more and more often as I use the block editor. At the very least, it would be good if the block would at least not be invalidated by adding the attributes via the code editor

**Comment by designsimply** [comment]
Thanks @annestk! Closing in favor of #8000.
