### ISSUE TITLE
Shortcode not saving when the commands have syntax errors

### ISSUE THREAD

**Issue by clive-verrall** [WordPress/gutenberg#12782]
**Describe the bug**
Creating a new page using Gutenberg editor, when I try to save a short code for the CoconutTickets plugin it underlines the short code with red syntax errors and it won't save. The editor displays "update failed" error banner in red. The contents of the square brackets are correct and relate to an installed and working plugin for Coconut Tickets. The contents of a short code string should not need to pass a grammar or syntax check.

**To Reproduce**
1. Create a new page
2. Insert a new short code such as [coconuttickets] that causes the syntax highlighter to underline the short code in red
3. Click the editor update button
4. See error banner message display "update failed" with no errors in the JS console

**Expected behavior**
The editor should save the short code text regardless of what is inside the square brackets. It can't possibly know what is valid.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Chromium
 - Version 70.0.3538.110 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Additional context**
- Using WordPress 5.0 official release downloaded 10th December 2018

**Comment by swissspidy** [comment]
Are you perhaps using a plugin like Jetpack? Core doesn't do spell checking by default, so there wouldn't be any underlines. Unless the browser itself adds them of course.

Can you please add some screenshots so we can clarify this? A gif/video would also greatly help if possible.

Are you using the shortcode block to insert that shortcode? That would be the correct way to do it.

Also, do you see any errors in the Network tab in the developer tools?

**Comment by clive-verrall** [comment]
I'm not using JetPack,  I have very few plugins activated. Please see the screenshot. There is a WP Baker page builder installed but it claims to be compatible with Gutenberg.

You raise a good point about the spell checker not being part of Gutenberg. This has got me wondering if it just a general problem saving the short code and nothing to do with the red underlining. However, I am still unable to save my own short code for Coconut Tickets.

I am saving this in a short code block as the screenshots should illustrate.

On the network tab or the developer console I can see 400 errors (see screen shot).

Thanks for looking into this.

![screenshot from 2018-12-11 18-47-31](https://user-images.githubusercontent.com/29688899/49798654-5e4e7080-fd75-11e8-8cc3-928cbc00b487.png)


![screenshot from 2018-12-11 18-37-01](https://user-images.githubusercontent.com/29688899/49798078-fd726880-fd73-11e8-87e9-f822bb95ce62.png)
![screenshot from 2018-12-11 18-36-12](https://user-images.githubusercontent.com/29688899/49798080-fe0aff00-fd73-11e8-83a8-00feb64567e1.png)
![screenshot from 2018-12-11 18-35-18](https://user-images.githubusercontent.com/29688899/49798081-fe0aff00-fd73-11e8-9a7b-8205fc66a01a.png)
![screenshot from 2018-12-11 18-41-38](https://user-images.githubusercontent.com/29688899/49798250-6e198500-fd74-11e8-949b-fa9b84e490e7.png)

**Comment by skorasaurus** [comment]
I've encountered the same error before and the code in my shortcode was not correct. Double-check whether your shortcode works in the classic editor by installing the classic-editor plugin. 
(see https://github.com/WordPress/gutenberg/issues/9285#issuecomment-420341556)

**Comment by designsimply** [comment]
I tested with WordPress 5.0.2 and Coconut Tickets 1.1 and found that if I add `[coconuttickets]` to a post and click "Publish" it results in a "Publishing failed" error. However, the post does get saved and when I refresh the same post, or close and re-open the post, this is what I see:

> ReferenceError: jQuery is not defined
>  post.php:5:2

![screen shot 2018-12-20 at 2 46 56 pm](https://user-images.githubusercontent.com/1119271/50312608-1e1e7a80-0466-11e9-86be-85b96d1561d6.png)
<sup>Seen at https://testingallthetime.com/wp-admin/post.php?post=272&action=edit running WordPress 5.0.2 and no active plugins using Firefox 63.0.3 on macOS 10.13.6.</sup>

I agree this is a compatibility problem with the plugin and recommend contacting the plugin author to see if they are able to update to be compatible with the latest version of WordPress (5.0.2 at this time).

**Comment by clive-verrall** [comment]
I found a solution. The render function for the Coconut Tickets plugin (that I wrote) was somehow not wrapped by an ob_start() ... return ob_get_clean() statement block. Have put this in there are now no errors being displayed when saving the shortcode in the Gutenberg editor. I have released an updated version of the plugin to the official repo.
