### ISSUE TITLE
Copy Paste Handler Issue

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#12780]
**Describe the bug**
Copying & pasting from a `<input type="text" />` element produces different results to a `<input type="email" />` element.

The value copied from an email input (and also a number input) contains the full block HTML, not the input's value. Issue is demonstrated in the following screen recording.

![wbjglpucyf](https://user-images.githubusercontent.com/2296425/49773808-97bbb780-fd46-11e8-9052-4948acdcd802.gif)

**To Reproduce**
1. Add the following JS to register the block
2. Enter values into both the text and email inputs
3. Copy and paste the values into the provided textarea

```js
	var el = wp.element.createElement,
    	registerBlockType = wp.blocks.registerBlockType;
	
	registerBlockType( 'test/test-copy-paste', {
	    title: 'Test Copy & Paste',
	    icon: 'universal-access-alt',
	    category: 'layout',
	    edit: function( props ) {
	        return el(
	            'div',
	            {
	                className: 'test',
	            },
	            el(
		            'input',
		            {
		               	type: 'text',
		                placeholder: 'text',
		                style: { width: '45%' }
		            }
		        ),
	            el(
		            'input',
		            {
		                type: 'email',
		                placeholder: 'email',
		                style: { width: '45%' }
		            }
		        ),
		        el(
		            'textarea',
		            {
		                placeholder: 'textarea',
		                style: { width: '100%' }
		            }
		        ),
	        );
	    },
	    save: function( props ) {
	        return el(
	            'p',
	            {},
	            'This is a test.'
	        );
	    }
	});
```

**Expected behavior**
The value copied from any input/textarea should match the behavior of the "text" input.

**Additional context**
- WordPress 5.0

**Comment by grappler** [comment]
This is still an issue with WP 5.4. This https://github.com/WordPress/gutenberg/pull/21162 should fix this issue.
