### ISSUE TITLE
Ability to edit link attributes in buttons

### ISSUE THREAD

**Issue by SmozyAble** [WordPress/gutenberg#12789]
Give the ability to add parameters to links from buttons (class = "wp-block-button__link"):

1. Adding "opening in a new window" as in the usual links;
2. Adding the "nofollow, noopener, dofollow" and other SEO parameters to the link in button.

**Comment by swissspidy** [comment]
> Adding "opening in a new window" as in the usual links;

See #12783 for that.

**Comment by youknowriad** [comment]
1- is already possible 
2- is tracked #13542

Thanks.
