### ISSUE TITLE
Clarify the 'Hide the teaser' option in the more block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12785]
**Describe the bug**
The More Block provides a toggle switch to _Hide the teaser before the "More" tag_.

Presumably, this should hide the excerpt on the archive page, rather than show it, but at the moment, the switch doesn't do anything.

Toggled on:
![screenshot_1012](https://user-images.githubusercontent.com/2078245/49783913-981c7880-fd6f-11e8-9dd4-bda8a9ffdd44.png)

Toggled off:
![screenshot_1011](https://user-images.githubusercontent.com/2078245/49783918-9c489600-fd6f-11e8-9bf4-137b39020172.png)

Instead of fixing this switch, it should just be removed altogether, as it's counterintuitive to the functionality of the whole block. The point of the More Block (like the More Tab in the Classic Editor), is to specify the position where the excerpt should stop (on archive pages).

If you don't want any excerpt to display, then you would simply insert the More tag at the very top of your Post. There is no need for this toggle switch and it's just a confusing option.

**To Reproduce**
1. Edit a Post
2. Insert a More Block where you want the excerpt to stop
3. Toggle the 'Hide the Teaser' switch to on
4. View your blog page and see that the excerpt still appears

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3
- WP 5.0

**Comment by swissspidy** [comment]
> Presumably, this should hide the excerpt on the archive page, rather than show it, but at the moment, the switch doesn't do anything.

No. This option hides the excerpt when viewing the _single post_.

So if your post content looks like this:

```
Foo

[more block]

Bar
```

In the archive page you'll see `Foo (read more)`, and on the single post page you should just see `Bar`

**Comment by maddisondesigns** [comment]
Ahh ok. Thanks for clarifying this.

This functionality seems kinda weird though. The 'More tag' has always related to how the content displays on the archive page, and nothing to do with how it displays on the Single Post page. Even the description for this block, specifically mentions the archives page, yet this option affects how it displays on the Single Post page. If you want a Custom Excerpt (that doesn't display on the Single Post), there's already a specific field for that functionality.

**Comment by swissspidy** [comment]
> This functionality seems kinda weird though. The 'More tag' has always related to how the content displays on the archive page, and nothing to do with how it displays on the Single Post page.

The behavior of that teaser toggle is exactly the same as before in WordPress core. You can look for `noteaser` in `get_the_content()` to see how it works.

Sounds like the wording is inaccurate then.

**Comment by maddisondesigns** [comment]
Fair enough. Thanks for pointing that out. In twelve years of using WordPress I don't think I've ever seen a theme that actually strips that teaser.

It might be worth making that toggle switch wording a little clearer, as it's a bit confusing as to what it's supposed to do. Maybe something like _'Hide the teaser before the "More" tag on Single Post pages'_

**Comment by afercia** [comment]
Yep the wording is slightly 😆confusing. See also https://github.com/WordPress/gutenberg/issues/8974#issuecomment-435575054

**Comment by ntsekouras** [comment]
This has been resolved here: https://github.com/WordPress/gutenberg/pull/13630
