### ISSUE TITLE
Remove reusable block removes complete block from editor

### ISSUE THREAD

**Issue by Stojdza** [WordPress/gutenberg#12791]
Remove reusable block removes complete block from editor.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post
2. Create Paragraph block
3. Select More options -> Add to Reusable Blocks -> Save
4. Select More options -> Remove from Reusable Blocks -> Confirm

#### What I expected
That block is not Reusable Block anymore and it should stay in Editor

#### What happened instead
Complete block is removed from Editor
NOTE: From confirmation window is clear that block will be deleted. but from More options menu it looks like that block will only be removed from reusable blocks. 

#### Browser / OS version
Chrome 70 / macOS High Sierra 10.13.3

#### Screenshot / Video
<img width="773" alt="screen shot 2018-10-10 at 14 23 47" src="https://user-images.githubusercontent.com/7116222/46747640-20b86300-ccb2-11e8-9280-b5e2c1c5b55c.png">
<img width="861" alt="screen shot 2018-10-10 at 14 23 55" src="https://user-images.githubusercontent.com/7116222/46747647-244bea00-ccb2-11e8-8a35-fd3585384d5b.png">

**Comment by swissspidy** [comment]
> That block is not Reusable Block anymore and it should stay in Editor

Note that this is what the "Convert to Regular Block" option is for.

Perhaps we can change the labels to make this more clear.

**Comment by melchoyce** [comment]
I ran into this as well and was super confused. Honestly, I wonder if we shouldn't have this option in the menu at all — maybe it should only live within the Reusable Blocks screen.

**Comment by swissspidy** [comment]
> maybe it should only live within the Reusable Blocks screen.

Sounds like a good thing to explore.

I wonder what happens when you do that by the way. Will the block be silently removed from all posts it's being used in? Does the Reusable Blocks screen show which posts are using the block? (A often requested feature for attachments, by the way)

**Comment by melchoyce** [comment]
> I wonder what happens when you do that by the way. Will the block be silently removed from all posts it's being used in? 

We'll definitely need some good copy in an "are you sure?" prompt when deleting reusable blocks.

> Does the Reusable Blocks screen show which posts are using the block? (A often requested feature for attachments, by the way)

I think that would be great, personally.

**Comment by melchoyce** [comment]
I recently did it again — I selected "Remove from reusable blocks" thinking it would detach this instance from my reusable block, which is how I expect it to work. Then it deleted all instances of the reusable block 😩 I still think you should only be able to delete all instances from the reusable block management screen, not directly from the editor, and that "remove from reusable blocks" in the block dropdown should detach the instance.

**Comment by auntieC** [comment]
I had the same issue, lost two days worth of work. The ability to delete block entirely should not reside within the post editor at all.

**Comment by mapk** [comment]
The recommended action seems to be:

**1. Hide the "Remove from reusable blocks" action item from the popover block menu.**

![Screen Shot 2019-12-27 at 3 36 03 PM](https://user-images.githubusercontent.com/617986/71535901-b55eaf00-28be-11ea-97e1-b33fec31335d.png)


**2. Only allow that option in the reusable block management screen.**

![Screen Shot 2019-12-27 at 3 37 52 PM](https://user-images.githubusercontent.com/617986/71535920-f060e280-28be-11ea-9edb-38707f9e94ae.png)

**3. Require a second notification before trashing the reusable block with some options.**

![dialog-delete-reusable-block](https://user-images.githubusercontent.com/617986/71536119-d4f6d700-28c0-11ea-8d13-ad50c730b478.png)

**Comment by ibdz** [comment]
From this week [design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1583860899282000), we came up with the idea of replacing "Remove from Reusable Blocks" with "Manage Reusable Block" instead and rearrange/grouping actions of managing Reusable block into the same section.

![More options](https://user-images.githubusercontent.com/426383/76423762-d7ee6780-63d9-11ea-9cd2-f16ea2355a62.png)

For a quick fix, it can be just a link to "Manage All Reusable Blocks" screen.

----
A further idea for "Manage Reusable Block" is showing a modal popup as same as "Block Manager" from tools & options.

Here is the proposal for managing selected Reusable Block modal showing all post instances that will be affected by the action:

![Manage Selected Reusable Block v1](https://user-images.githubusercontent.com/426383/76424633-16d0ed00-63db-11ea-98a5-f0f9ce11be9d.png)

**Comment by karmatosed** [comment]
I really like the idea of a quick fix. Let's see about moving this to development, thanks.

**Comment by wallstead** [comment]
I see this issue has been sitting a while. If there is still interest I'd like to take on dev for this as my first issue.

**Comment by mapk** [comment]
@wallstead, that would be great! It looks like we've got the "Convert to blocks" as a button in the toolbar now, so all we need here is to swap the "Remove from Reusable blocks" button to one that says, "Manage Reusable blocks" and it should take the user to the Reusable blocks manage screen. This will require a notification if there are unsaved changes so the user doesn't lose any changes.

![Frame 1](https://user-images.githubusercontent.com/617986/98858953-4cb8ec00-2416-11eb-94bf-0fce3ff54ac2.png)

**Comment by wallstead** [comment]
@mapk Great! I'll start work on this today.

**Comment by Two-Motion** [comment]
This is a problem for me as well. Not getting confused by what "remove from reusable block" means, but the fact that I might accidentally click it. I work with reusable blocks all the time across many pages. It's an accident just waiting to happen and no way to fix it when it does. Even a simple "Are you sure you want to delete this block?" would be really great.

**Comment by wallstead** [comment]
I just submitted the above pull request, it's my first ever so please let me know if I need to do anything else other than keep checking in here!

**Comment by KennySing** [comment]
So how do i detach a single instance of a reusable block from its global "symbol". 

For example

Page 1
- Reusable Block 1

Page 2
- Reusable Block 1

Page 3
- Reusable Block 1 (i want to convert this into a static version of Reusable Block 1)

**Comment by talldan** [comment]
@KennySing There's a button on the toolbar of the reusable block:
<img width="175" alt="Screenshot 2021-06-17 at 1 01 20 pm" src="https://user-images.githubusercontent.com/677833/122334351-2fc83680-cf6c-11eb-9979-71fa35b297e5.png">
