### ISSUE TITLE
Parent editor-style.css not loaded in Classic block when child theme used

### ISSUE THREAD

**Issue by superpoincare** [WordPress/gutenberg#12798]
**Describe the bug**
If I create a simple child theme and use the classic editor, parent editor-style.css from the parent root directory is not loaded, only the child editor-style.css is loaded (inline). However, if I activate parent theme, then the parent editor-style.css is loaded correctly (inline). 

**To Reproduce**
1. Create a child theme as described in Wordpress docs. In addition to functions.php and style.css, also create an editor-style.css file with some styles. 
2. Add a new post.
3. Add a title and create a classic editor block
4. Parent styles not loaded as can be seen by styling. 

**Expected behavior**
Both parent editor-style.css and child editor-style.css loaded.

**Desktop (please complete the following information):**
 - OS: Windows 8.1 
 - Browser: Chrome
 - Version: 71

**Comment by swissspidy** [comment]
Core ticket for that: https://core.trac.wordpress.org/ticket/45551

**Comment by vijayaraghavanramanan** [comment]
Any update on this?

**Comment by jordesign** [comment]
Hi @superpoincare - just checking in to see if this is still an issue for you when you test it?

**Comment by jordesign** [comment]
With no further activity in the last 2 weeks - I'm going to close this issue. If it proves to still be in place - please feel free to re-open with further testing instructions.
