### ISSUE TITLE
Paragraph block: Insert link without selected text

### ISSUE THREAD

**Issue by Stojdza** [WordPress/gutenberg#12790]
When I select nothing, just put cursor somewhere in a text, and add a link, complete link is inserted into text

1. Go to wpcalypso.wordpress.com/block-editor/post
2. Add Paragraph block 
3. Enter some text and put cursor somewhere in the text (do not select any text)
4. Insert link
5. Complete link is added

**Expected behavior**
Link should not be added (as in Classic Editor)

**Screenshots**
https://cloudup.com/cWyVOE8zOsC

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.3
 - Browser: Chrome
 - Version: 70

**Comment by heldervilela** [comment]
In terms of usability, this is correct behaviour rather than doing nothing.
And the classic editor has the same behaviour.

**Screenshots**
https://helder.d.pr/t0nm7D

**Comment by swissspidy** [comment]
Not adding a link to the content after you clicked on the button and entered a URL would be really weird and doesn't make sense to me.

**Comment by Stojdza** [comment]
Steps for editor in Calypso
- Deactivate Gutenberg
- Start new post at https://wordpress.com/post/
- Put the cursor in text and insert link (without any text selected)

Result: Nothing happens

![dec-11-2018 17-16-41](https://user-images.githubusercontent.com/7116222/49814365-ca2adc00-fd69-11e8-9042-4cab9edc5e58.gif)


This confused me, I don't know which one is correct behavior.

**Comment by swissspidy** [comment]
That looks more like a [Calypso](https://github.com/Automattic/wp-calypso) issue than a Gutenberg one then 🤔

**Comment by youknowriad** [comment]
Closing as Gutenberg is following the classic editor behavior at the moment. It's fine to consider an improvement if there's more feedback suggesting an alternative approach.
