### ISSUE TITLE
Menu Overlap When Embed Block is Initial Block

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#1279]
If you don't add any text, and instead insert an embed block as the first object, subsequently clicking on the + button renders the menu under the top bar, obscuring the first few options: 

![2017-06-19_16-28-41](https://user-images.githubusercontent.com/480667/27304742-0f2eeffa-550d-11e7-8566-516fd99afb8d.png)

This is with the plugin version in the repo version 0.1.0

**Comment by aduth** [comment]
Related: #1193

This is an issue with the existing implementation detecting boundary collisions to flip the inserter. Currently it detects if it exceeds the top of the entire _page_ (above admin bar), when it should be detecting against the bottom of the editor bar.

https://github.com/WordPress/gutenberg/blob/cab8713/components/popover/index.js#L51
