### ISSUE TITLE
What are the differences between the Classic Editor and the Classic Block?

### ISSUE THREAD

**Issue by AngoraSpace** [WordPress/gutenberg#12792]
After I explore all of the blocks on WordPress 5, there’s a classic editor inside Gutenberg block formatting options.
https://i.postimg.cc/vTwv4pPy/IMG-20181211-113321.jpg

I think it’s still the same feature like classic editor on WordPress 4 and previous version. 
https://i.postimg.cc/ncZkpfjY/IMG-20181211-113344.jpg

But why official WordPress suggest user (who complain about Gutenberg) to install classic editor plugin than suggest them to use classic editor inside Gutenberg block?

**Comment by swissspidy** [comment]
The `Classic` block and the `Classic Editor` are two different things.

The new UI is a drastic change from the one you'll have with the Classic Editor. If you update, old content not containing any blocks will be shown in the Classic block, which is very limited in functionality and does not affect the rest of the UI. This Classic block then allows you to split the content up into individual blocks.

If you're having issue with compatibility between Gutenberg and some other plugins, it's not enough to just use the Classic block. In these cases, you'll need to continue to use the Classic Editor with its different UI.

**Comment by suhashininithy** [comment]
Hi., 

How can a add my own button over the gutenberg editor toolbar like this http://prntscr.com/lv878w ?

**Comment by swissspidy** [comment]
@suhashininithy Can you please open a new issue for your (unrelated) question? Thanks.

**Comment by suhashininithy** [comment]
Hi., 

Yes , i did . But no one respond my question :(

**Comment by swissspidy** [comment]
That was 2 hours ago. On a weekend. Please just be patient, we‘re all volunteers here. Amd hojacking other issues certainly doesn‘t help get feedback faster 😉

**Comment by IgalNeeman** [comment]
[my website ](www.getstudy.co.il )look like this , how can i use 'classic editor' without plugin?
