### ISSUE TITLE
Reusing core blocks in custom block

### ISSUE THREAD

**Issue by gregbia** [WordPress/gutenberg#12805]
Is there a recommended way to include core blocks when building custom blocks? For example I am creating a custom block for team members, with team member image, name, and description. Rather than write code for the paragraph I would like to use the core paragraph blocks with all its options.

I know this can be achieved using InnerBlocks but it crowds the UI, as each block has its own toolbar.

**Comment by swissspidy** [comment]
So you want to use the core paragraph block with all its options but not with its toolbar, which contains all of these options? 🤔 

Seems weird to me, but there's actually a similar request here: #12779.

For your use case I'd probably use the individual components like `<RichText>` to really tailor the UI for the user to make the UX as good as possible.

**Comment by designsimply** [comment]
Closing and acknowledging the suggestion to use individual components like `<RichText>` for a case like this.

@gregbia if you are looking for more detailed help with custom code, please consider posting your question to https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/ and if you can include a code example as part of your help request that should help make it more actionable as a general rule. If not, just explain as much detail as you can about what you're trying to do base on the direction given and what you have tried already if anything.
