### ISSUE TITLE
Embed blocks break when re-editing

### ISSUE THREAD

**Issue by Erdyke** [WordPress/gutenberg#12806]
**Describe the bug**
Add an embedded video block (Youtube) after text block.  Save and visit page.  Things look good.  Go back and re-edit page, blocks are all merged and embedded video no longer exist.  The embed link is left over but the actual separate embed block is gone.  All blocks have merged together.  So far only tested on POST (blog) type.  If you go back to visit the page, the embedded video is still broken.

**Expected behavior**
I would expect the embed blocks to remain isolated blocks and continue to function as embedded video.

**Screenshots**
![screenshot from 2018-12-11 17-50-34](https://user-images.githubusercontent.com/13955499/49835547-8b972080-fd6d-11e8-80e1-d124560acdc7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - Browser: chrome
 - Version: Version 71.0.3578.80 (Official Build) (64-bit)
-WP: V5.0

**Comment by swissspidy** [comment]
Just to confirm: you added some paragraphs and and embed block, and the content ends up being in a classic block instead?

Does this still happen with all plugins disabled and when using one of the default themes?
