### ISSUE TITLE
Subdirectory not included in REST API root URL when using apiFetch()

### ISSUE THREAD

**Issue by barrykooij** [WordPress/gutenberg#12801]
**Describe the bug**
The `path` parameter of `apiFetch` function should append given value to _REST API root URL for the current site_ When installing WordPress in a subdirectory, the subdirectory is not added. So running `apiFetch('/wp/v2/posts')` on `https://www.mywebsite.com/wordpress/` calls the following URL `https://www.mywebsite.com/wp/v2/posts` instead of `https://www.mywebsite.com/wordpress/wp/v2/posts`.

**To Reproduce**
1. Install WordPress in a subdirectory.
2. Run custom Gutenberg block that has an `apiFetch` call.
3. Get 404

**Expected behavior**
`apiFetch` function to include subdirectory in REST API root URL.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Additional context**
- I'm using the Gutenberg version that is shipped with WordPress 5.0

**Comment by TimothyBJacobs** [comment]
What does `get_rest_url()` return in your site? I believe `apiFetch` bases its `path` off of that URL, https://github.com/WordPress/wordpress-develop/blob/5.0/src/wp-includes/script-loader.php#L513

**Comment by barrykooij** [comment]
`get_rest_url` result: `string 'http://lnmp.n5/beta5/wp-json/' (length=29)`

Subdirectory is included.

**Comment by TimothyBJacobs** [comment]
Are you sure your custom block is using the `wp.apiFetch` script and not an included version in a webpack bundle or something?

The behavior of just appending the `path` argument to the URL seems like native `fetch` behavior when doing `fetch( '/wp/v2/posts' )`, as if the `createRootURLMiddleware` isn't being run at all. The URL would also need the rest base, `wp-json` prepended as well so it seems like the WP code isn't running.

**Comment by talentedaamer** [comment]
Thanks @TimothyBJacobs using `const apiFetch = wp.apiFetch;` fixed the issue.

**Comment by tellthemachines** [comment]
Hi @barrykooij , I'm closing this issue as it has been inactive for some time. Please feel free to reopen if this is still a problem for you.
