### ISSUE TITLE
Lack of consistency between text blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12802]
The settings for Paragraph, heading, quote, pullquote and list blocks are not consistent with each other.

Current Paragraph Block. Which is the block that will likely be most used. 
![paragraph block gutenberg](https://user-images.githubusercontent.com/5323259/49801531-ba4fcf80-fd4a-11e8-9c3f-3cd4e282311c.png)

<hr>

Current Heading Block.
Text alignment is missing from the toolbar but is instead in the right settings sidebar.  H is in toolbar and in the right sidebar. It would be good to keep the consistency and have alignment in the toolbar. H could perhaps be a drop down in the toolbar. (I believe this has been much discussed.)

Missing: No setting to change background or text color.

![heading block gutenberg](https://user-images.githubusercontent.com/5323259/49801534-bd4ac000-fd4a-11e8-8ae4-a13214fae49f.png)

<hr>

Current Quote Block:
Block Styles/Styles show up on clicking Change Block Styles and in the right sidebar settings section.

Missing: No settings to change background or text color.

![quote block gutenberg](https://user-images.githubusercontent.com/5323259/49814934-eed38380-fd6a-11e8-8e75-057d5d86e8d7.png)

Current Pullquote Block:
Block Styles/Styles show up on clicking Change Block Styles and in the right sidebar settings section.
There is a Main Color and Text Color sections.

![pullquote block gutenberg](https://user-images.githubusercontent.com/5323259/49801941-e0c23a80-fd4b-11e8-9230-48f7b8b94087.png)

<hr>

Current List Block:
Change to unordered or ordered list through the toolbar. This seems like a style to me...
Left or right indent.

Missing: No settings to change background or text color.

![list block gutenberg](https://user-images.githubusercontent.com/5323259/49801556-d489ad80-fd4a-11e8-8e5b-ae000c71799c.png)

All text blocks should contain an option to change background and text color.

There are also options that the TinyMCE toolbar (classic editor) once had that are gone in Gutenberg. Should we figure out a way to return the missing toolbar icons?

There are also additional options they should contain located in this plugin: 
https://wordpress.org/plugins/advanced-rich-text-tools/

Gutenberg version included in WordPress 5.0.

There are many similar issues: https://github.com/WordPress/gutenberg/issues/6012

**Comment by swissspidy** [comment]
I think we have individual issues for most of these things already.

> Current Heading Block.
> Text alignment is missing from the toolbar but is instead in the right settings sidebar. H is in toolbar and in the right sidebar. It would be good to keep the consistency and have alignment in the toolbar.

There's #12781 for that already.

> Current Quote Block:
> Block Styles/Styles show up on clicking Change Block Styles and in the right sidebar settings section.
> Missing: No settings to change background or text color.
> All text blocks should contain an option to change background and text color.

See #8171 for that.

> There are also options that the TinyMCE toolbar (classic editor) once had that are gone in Gutenberg. Should we figure out a way to return the missing toolbar icons?

I think they weren't added on purpose. It's totally fine for people to install plugins like Advanced Rich Text Tools for less common things if they need them.

**Comment by paaljoachim** [comment]
This issue raises my main point of lack of color setting in various text blocks: https://github.com/WordPress/gutenberg/issues/8171

So I will close this issue.
