### ISSUE TITLE
Impossible to style Gutenberg with Google Fonts because...

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12808]
It's impossible to style Gutenberg with Google Fonts because:
1. I open post editing screen.
2. JavaScript sets `height: 100px;` for the post title.
3. Google Font loads.
4. JavaScript doesn't update `height` to the new one.

**Comment by manake** [comment]
Is there some way to trigger refresh of the editor (the title)?

**Comment by youknowriad** [comment]
Is this still happening? I can't reproduce personally. Mind sharing a screenshot to explain better?
