### ISSUE TITLE
Language error

### ISSUE THREAD

**Issue by almendron** [WordPress/gutenberg#12818]
General Settings > Site Language = Spanish

Profile> Language = Spanish

PHP version: 7.2.4

Clean installation in local [(wampserver)]

Plugins: none

Template: Twenty Nineteen Version: 1.0

**and Gutenberg Editor: error. In English.**

[Image 1](https://www.almendron.com/compartir/gutenberg/gutenberg-1.jpg) - [Image 2](https://www.almendron.com/compartir/gutenberg/gutenberg-2.jpg) - [Image 3](https://almendron.com/compartir/gutenberg/gutenberg-4.jpg)

More tests in local:
Three sites
Same language options (Spanish)
Error. Editor in English

**Comment by swissspidy** [comment]
If you go to Dashboard -> Updates, are the translations up-to-date?

Have you perhaps installed WordPress in a sub directory?

**Comment by almendron** [comment]
If you go to Dashboard -> Updates, are the translations up-to-date? No
Have you perhaps installed WordPress in a sub directory? No

Work in local (wampserver). Four sites. Each of them in your folder (Inside the folder "www")

**Comment by swissspidy** [comment]
> If you go to Dashboard -> Updates, are the translations up-to-date? No

Well, have you tried updating the translations then? 🙂 There should be a big button to do so at the bottom of the page.

Feel free to share a screenshot of that page if you're note sure.

> Have you perhaps installed WordPress in a sub directory? No

So the URL for your site is something like `myawesomewebsite.local`?

**Comment by almendron** [comment]
Change of language, for example to French, but Gutemberg does not change. Continues to appear in English

**Comment by swissspidy** [comment]
Again, please try to update the translations.

Which files are in the `wp-content/languages` folder?

**Comment by almendron** [comment]
URL: http://localhost/limpia/

[See Image updates](https://almendron.com/compartir/gutenberg/gutenberg-5.jpg)

[See Folder languages](https://almendron.com/compartir/gutenberg/gutenberg-6.jpg)

**Comment by almendron** [comment]
WordPress version: 5.0

**Comment by almendron** [comment]
Updated to 5.0.1
The problem has not been resolved

**Comment by swissspidy** [comment]
Since you installed WordPress in the limpia sub directory, the reason for the missing translations is likely https://core.trac.wordpress.org/ticket/45528.

This will probably fixed in 5.0.2.

Please follow that ticket for updates.

I‘m closing this one here in favor of the ticket.
