### ISSUE TITLE
Unwanted div in paragraph created by pressing enter in More block

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#12813]
**Describe the bug**
If you insert blocks using the keyboard and you press enter to create a block from More block then you get an unwanted div in the new paragraph block. This block fails validation when the post is re-edited.

**To Reproduce**
1. Add new post. Ensure you're in Visual editor
2. Type title: e.g. Tab slash mo enter 
3. Press Tab
4. Type `/mo` and press Enter
5. The More block is created with the cursor after READ MORE
6. Press Enter
7. Type _something_
8. Switch to code editor.
9. See the unwanted `div`.
10. Publish, view then Edit the post
11. See `This block contains unexpected or invalid content`.

**Expected behavior**
The paragraph block should not contain a `div` tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/49874711-1a13ac80-fe17-11e8-8350-c120e7bfa4c0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
- Problem created with WordPress 5.0 and no plugins. 
- Reproduced with 4.9.8 and Gutenberg 4.6.1
- Workaround. Don't press Enter in the More block.

Note: The HTML created when you first press enter is.
```
<!-- wp:paragraph -->
<p><div><br></div></p>
<!-- /wp:paragraph -->
```
Typing _something_ replaces the `<br>` only.

**Comment by molszewska** [comment]
I've just tested it on my site twice, and the div doesn't seem to be created anymore: https://cld.wthms.co/QW19Eo

**Comment by youknowriad** [comment]
Closing as fixed. Thanks for the tests.

**Comment by sourourn** [comment]
Also tested this on my site, I was not able to replicate this issue - no unwanted div was added.

Here is a screenshot: https://cld.wthms.co/NJACQJ

WordPress Version 5.2
Browser: Firefox 61.0.2
Mac OS
