### ISSUE TITLE
Can't insert images in text/freeform block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1281]
When you have your cursor inside the freeform or text block, you can't insert an image. There's no icon in the menu that appears at the top of the block, and when you select _Image_  from the Insert menu at the top of the page, it simply inserts a new image below the current block.

This makes impossible to add an image with text flowing around it, or as an example, to insert a small icon in your text. This means that you can't do something like this...

![gutenberg-inlineimages](https://user-images.githubusercontent.com/2078245/28992706-362fd638-79e7-11e7-8f3c-c779edead4ed.png)

**Comment by westonruter** [comment]
This perhaps depends on the UI being built for nested blocks? cf. #219 #428

**Comment by maddisondesigns** [comment]
As I've mentioned in ticket #219, the ability to create multi-column layouts is a must-have. As too though, is the ability to add images into a standard text block. The screenshot I referenced above is a classic example. People need the ability to be able to add images inline with their text. The above example wouldn't work if you can only add an image as a separate block.

**Comment by jasmussen** [comment]
Closing in favor of #2043.
