### ISSUE TITLE
Link Title Tags removed

### ISSUE THREAD

**Issue by swsche** [WordPress/gutenberg#12823]
After the update to Wordpress 5 and using the gutenberg editor, all title tags on links where removed. The problem don't appears in the classic editor.

**Comment by swissspidy** [comment]
You mean the title attribute on `<a>` elements is being removed everywhere in the content?

Did this happen everywhere automatically or after converting content to blocks?

**Comment by MARICEL30** [comment]
I got the same problem, just updated to 5 and can't add more than one link.

**Comment by designsimply** [comment]
@MARICEL30 your issue sounds different than the one originally posted here. Can you please ask for help at https://wordpress.org/support/forum/how-to-and-troubleshooting/ and make sure to mention your steps for reproducing the problem, whether you see any errors when trying to add more than one link, and any details regarding your theme or plugins you think may be relevant.

**Comment by designsimply** [comment]
I tested with the following steps.

1. Go to a site running WordPress 4.9.8.
1. Add a few posts with links that have title tags, example: `<a title="WordPress.org" href="https://wordpress.org/">WordPress.org</a>`
1. Update to WordPress 5.0.2.
1. Open the post for editing.
1. Click the more menu on the block and go to "Edit as HTML".
1. Check to see if the `title` attribute is still present in the HTML for the link.
1. Try clicking More > Convert to Blocks then save and check again. 

Result: in my case, the title attribute was always there after upgrading from WordPress 4.9.8 to WordPress 5.0.2 when you look in the HTML.

![screen shot 2018-12-20 at 4 36 02 pm](https://user-images.githubusercontent.com/1119271/50316834-a1939800-0475-11e9-94eb-76ad00c26405.png)
<sup>Tested with WordPress 5.0.2 and no active plugins using Firefox 63.0.3 on macOS 10.13.6.</sup>

Please try testing with all plugins turned off. If you're still having trouble, please re-open this issue and note any differences if you compare my testing steps above to your steps.
