### ISSUE TITLE
wordpress Gutenberg

### ISSUE THREAD

**Issue by jo1166** [WordPress/gutenberg#12838]
HI I couldnt update Gutenberg on wordpress today - I only started using it. Is it going to be safe and will it be fixed soon.

A bit worried so feedback and answers welcomed

**Comment by GlennMartin1** [comment]
What version of WordPress are you using?

If you're using the latest version (WordPress 5.0.1), there is nothing to install. The new editor is already present.

If you're not using WordPress 5+, you'll need to provide more information of what you're doing and what's happening.

**Comment by designsimply** [comment]
Please uninstall the Gutenberg plugin and upgrade to WordPress 5.0.1+ and if you are still having trouble after that, please re-open this issue and let us know as much detail as possible about what part of the update process is not working for you so we can help!
