### ISSUE TITLE
Right-aligning image at bottom of content breaks position of insert menu

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1283]
When I right-align an image that is in the last content block, the insert menu moves to a weird position on the page, between the content and the right-hand sidebar panels.

https://cl.ly/1i2f132T230w

**Comment by jasmussen** [comment]
Thanks for the report!

**Comment by youknowriad** [comment]
I think this is already fixed in master (when we added the "write" placeholder)
