### ISSUE TITLE
Column Block CSS Media Query

### ISSUE THREAD

**Issue by sylvia8308** [WordPress/gutenberg#12842]
**Describe the bug**

Is there any chance you could remove the media query - @media (min-width:600px)? It is preventing me from over riding the margins with the custom css feature and I have to go directly into the files. And of course when the WordPress updates it wipes our my edits. (If you need to target something for less than 600px you could write css specific to that.)

**To Reproduce**

Column block css files located here:

`/wp-includes/css/dist/block-library/style.css`

```
  @media (min-width: 600px) {
    .wp-block-column:nth-child(odd) {
      margin-right: 32px; }
    .wp-block-column:nth-child(even) {
      margin-left: 32px; }
    .wp-block-column:not(:first-child) {
      margin-left: 32px; }
    .wp-block-column:not(:last-child) {
      margin-right: 32px; } }
}
```

`style.min.css`

```
@media (min-width:600px){.wp-block-column:nth-child(odd){margin-right:32px}.wp-block-column:nth-child(even){margin-left:32px}.wp-block-column:not(:first-child){margin-left:32px}.wp-block-column:not(:last-child){margin-right:32px}}
```

**Expected behavior**

I expect to be able to that my custom css code will be able to override the default code so I can set the design how it needs to be set for a specific website design
 

**Desktop (please complete the following information):**

Not applicable

**Smartphone (please complete the following information):**

Not applicable 
**Additional context**
- Please add the version of Gutenberg you are using in the description.

Installed with WordPress 5.0.1 issue existed with 5.0 as well.

- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
It is still possible to override those styles by adding specificity to your custom CSS. There's nothing stopping you from using `!important` or using the same specificity as the original Gutenberg block.

Thanks.

**Comment by dmarman** [comment]
Why the first column has to render without margins? I have 3 columns and the first one is doing weird stuff..

<img width="974" alt="screen shot 2018-12-29 at 15 48 03" src="https://user-images.githubusercontent.com/19510612/50539483-536f4a80-0b81-11e9-8d62-de314e8e0881.png">
<img width="482" alt="screen shot 2018-12-29 at 15 48 18" src="https://user-images.githubusercontent.com/19510612/50539485-579b6800-0b81-11e9-8dfb-9a4ba8dbe837.png">
<img width="424" alt="screen shot 2018-12-29 at 15 48 34" src="https://user-images.githubusercontent.com/19510612/50539487-59fdc200-0b81-11e9-8a05-60086a4f7266.png">
