### ISSUE TITLE
Save option in Browser Dialogue Reload warning

### ISSUE THREAD

**Issue by irishetcher** [WordPress/gutenberg#12846]
This something that applies to WordPress in general but is more prominent when using the new block editor. If for whatever reason you go to leave the editing environment, viewing revisions, changing editor etc. the browser will pop up a dialogue -> leave site? Changes that you made may not be saved. 
Cancel or Leave.

This is very irritating because you have to cancel the dialogue and then Update. A save option in the dialogue that autoupdated everything would be useful. 

If I am wrong about this please explain the rational.

**Comment by swissspidy** [comment]
As you said, the _browser_ will show you this "Are you sure?" dialog. A website does not have any control over these dialogs except for the message being shown, thus making it impossible to add a save option to it. At least that was the case when I last checked it.

**Comment by youknowriad** [comment]
yes, I think that's not possible at the moment. I'm closing the issue as unfortunately, we can't do anything about it.
