### ISSUE TITLE
Can't insert Image block after an existing image block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1286]
If I try to insert an image block after an existing image block, the new image appears in the same image block that was already on the page. This means that I can't move either image to a new position in the page properly.

https://cl.ly/0w2p1o21300m

**Comment by youknowriad** [comment]
Did you try clicking on the the small image to select it?
I don't think we can do a lot here since that's how float positioning works. The white space around the floating elements is considered as part of the next non-floated image.

**Comment by jasmussen** [comment]
Seems to be related to pasting, see also #1294

**Comment by jasmussen** [comment]
Closing this in favor of #2459
