### ISSUE TITLE
MenuItemsChoice component does not have correct margins by default

### ISSUE THREAD

**Issue by dsifford** [WordPress/gutenberg#12863]
**Describe the bug**

The `MenuItemsChoice` component appears to depend on external stylesheets in order for the selected and nonselected items to line up correctly.

Here's what it looks like in the `MoreMenu` (implemented in `ModeSwitcher` in `./packages/edit-post/src/components/header/mode-switcher/index.js`)

![image](https://user-images.githubusercontent.com/5240018/49976949-32b4bd00-ff12-11e8-8491-78da54e1371c.png)

And here's what it looks like somewhere I'm trying to use it...

![image](https://user-images.githubusercontent.com/5240018/49976963-42cc9c80-ff12-11e8-9e4c-907cf56cbc37.png)

**To Reproduce**
1. Render a `MenuItemsChoice` somewhere else in the editor page.
2. See incorrect styles.

**Expected behavior**
The padding/margins should be equivalent to how it looks everywhere else.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser [e.g. chrome, safari]: Chrome 72

**Additional context**
- Gutenberg v4.7.0

**Comment by paaljoachim** [comment]
Hey @dsifford Derek!

Is this issue still relevant?
A lot of things have happened since this issue was created.
I will go ahead and close it. If I am mistaken then please reopen.
