### ISSUE TITLE
Custom blocks  - php render issue

### ISSUE THREAD

**Issue by crerem** [WordPress/gutenberg#12867]
**Describe the bug**
If you are using server rendering for a custom block and if you are using the get_the_excerpt function on the php rendering then the wpautop filter is applied  and the html output stops looking right.

**To Reproduce**
1. use php rendering on save

```
save: function( props ) {
    // Rendering in PHP
      return;

},

```
and php callback 
```
register_block_type( 'my-plugin/latest-post', array(
    'render_callback' => 'my_plugin_render_block_latest_post',
) );

```
2. In php function have something like 

```
foreach ( $recent_posts as $post ) {
        
		$post_id  = $post['ID'];
		$markup  .= get_the_excerpt($post_id).sprintf(
			'<li>
                            
                        <a href="%1$s">%2$s</a>
line1 

line2
</li>',
			esc_url( get_permalink( $post_id ) ),
			esc_html( get_the_title( $post_id ) )
		);
	}
$markup.='</ul>';

```

3. <p> and <br> tags are added to the output
https://prnt.sc/luhguk

**Expected behavior**
I think the html should not be altered and displayed as it is.  Just like a php function returns in case of shortcodes.

**Screenshots**
https://prnt.sc/luhguk

**Desktop (please complete the following information):**
 Windows,Chrome but will apply on any OS& browser

**Additional context**
wordpress 5.0.0.

**Comment by jankimoradiya** [comment]
Hello @crerem,

Hope you are doing well...!!! :)

I have checked above example in my system and it gives same html which described by you in above screenshot.

I have solved it also, Please use following code in php function:

```
foreach ( $recent_posts as $post ) {
        
		$post_id  = $post['ID'];
		$markup  .= get_the_excerpt($post_id).sprintf(
			'<li>
                            
                        <a href="%1$s">%2$s</a>'.
__("line1"). 

__("line2")
.'</li>',
			esc_url( get_permalink( $post_id ) ),
			esc_html( get_the_title( $post_id ) )
		);
	}
$markup.='</ul>';
```

Thank you

**Comment by crerem** [comment]
Hi,
I don't understand the answer - maybe you could rephrase.

I think i reported a bug - Gutenberg should NOT add any <br> or <p> tags on the html output. It should have the same behavior like on shortcodes.  Otherwise it will be impossible to create dynamic custom blocks.

thank you

**Comment by crerem** [comment]
Hi,
I understand now, and you are right. However...
Same thing happens if i have something like this in the php function


  ```
      ob_start();  
        while ($recent_posts->have_posts()): $recent_posts->the_post();
          
                    get_template_part('templates/blog_unit');
             
            }
        endwhile;

        $templates = ob_get_contents();
        ob_end_clean(); 
```
and in blog_unit file we do not use php strings but html  with inline php code like 
```
<div class="blog-unit-wrapper">
    <div class="blog_unit  col-md-12" data-link="<?php print esc_url($link);?>"> 
   
   <?php  echo get_the_excerpt($post_id); ?>
```

Would be more "natural" to not have wpautop filter applied for generated code ? 
I understand that this is not considered a bug. Is this correct ? 

Thank you for your answers.

**Comment by spencerfinnell** [comment]
This is likely the same bug as:

https://github.com/WordPress/gutenberg/issues/12530
https://github.com/WordPress/gutenberg/issues/9056

**Comment by youknowriad** [comment]
Closing as duplicate
