### ISSUE TITLE
`render block` filter doesn't seem to affect the classic block type

### ISSUE THREAD

**Issue by zandergrin** [WordPress/gutenberg#12862]
**Description**
`render block` filter doesn't seem to affect the classic block type

I am using the following code to wrap various core blocks in some divs to suit my theme.
```
add_filter( 'render_block', function( $block_content, $block ) {
    if ( 
        'core/paragraph' === $block['blockName'] || 
        'core/table' === $block['blockName'] || 
        'core/quote' === $block['blockName']  
      ) {
        $block_content = '<div class="div-class">' .  $block_content . "</div>";
    }
    return $block_content;
}, 10, 2 );
```

adding ` 'core/freeform' === $block['blockName']` or  `  'core/classic' === $block['blockName']` doesn't work.

**Comment by swissspidy** [comment]
Have you tried debugging the variable value? IIRC the block name is null for the classic block.

**Comment by zandergrin** [comment]
sorry - wouldn't know how to do that I'm afraid. 

If I'm honest finding a definitive list of all the blocks that exist, let alone the names to use and the list of categories has been pretty tricky!

I've been pulling them out of the index.js for each file. From what I can tell from [this file](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/classic/index.js) 
it seems to be core/freeform (line 13)

**Comment by designsimply** [comment]
I usually look at https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src to see a list of blocks and at https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/embed/core-embeds.js for a list of types of embeds. I don't know the answer to the problem fully, so I will also add the `Needs Technical Feedback` label.

**Comment by designsimply** [comment]
> You are correct - it's block name is NULL. It should have a block name though right? All the others do. does that qualify as a bug or something?

I don't think it's a bug per se but I also am not sure why it's null. If you feel it's something that should be checked into further, would you mind please opening a new enhancement request for that separately?

Since you mentioned the block name is null and since swissspidy mentioned a possible solution for targeting it, I believe the original question has been answered and would like to close this issue in that case. If it's not though, please let me know and I will re-open the issue for you. Thank you!

**Comment by ShiarOs** [comment]
> **Description**
> `render block` filter doesn't seem to affect the classic block type
> 
> I am using the following code to wrap various core blocks in some divs to suit my theme.
> 
> ```
> add_filter( 'render_block', function( $block_content, $block ) {
>     if ( 
>         'core/paragraph' === $block['blockName'] || 
>         'core/table' === $block['blockName'] || 
>         'core/quote' === $block['blockName']  
>       ) {
>         $block_content = '<div class="div-class">' .  $block_content . "</div>";
>     }
>     return $block_content;
> }, 10, 2 );
> ```
> 
> adding ` 'core/freeform' === $block['blockName']` or ` 'core/classic' === $block['blockName']` doesn't work.

you can try this code 

`add_filter( 'render_block', function( $block_content, $block ) {
// Target core/* and core-embed/* blocks.
if ( preg_match( '~^core/|core-freeform/~', $block['blockName'] ) ) {
$block_content = sprintf( '<div class="some__class">%s</div>', $block_content );
}
return $block_content;
}, PHP_INT_MAX - 1, 2 );`

**Comment by ShiarOs** [comment]
This is works 💯 
`function add_div_to_block_content( $block_content, $block ) {
    // Target core/* and core-embed/* blocks.
    if($block = 'core/freeform'){
       $block_content = sprintf( '<div class="some_class">%s</div>', $block_content );
    }
    return $block_content;
}

add_filter( 'render_block', add_div_to_block_content, PHP_INT_MAX - 1, 2 );`
