### ISSUE TITLE
text styling reverts to object when backspaced

### ISSUE THREAD

**Issue by drbe4t** [WordPress/gutenberg#12875]
I am currently working on a blog post about tips on the new editor when I would backspace I would get this [Object]..[object] thing happen. I thought it was wierd and then i realized it happened if I had a styled text. 
![issue-animated image small](https://user-images.githubusercontent.com/10386515/50007095-ffebe280-ff6c-11e8-80b8-dbb55559e486.gif)

I'm using firefox.

**Comment by ellatrix** [comment]
I can't reproduce this issue. Is it still present in the latest Gutenberg Plugin release?

**Comment by youknowriad** [comment]
can't reproduce either.
