### ISSUE TITLE
Can't insert links

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1287]
The add link icon doesn't work. After selecting a word, and then clicking the link icon, it simply adds <a> tags around the word and doesn't display the inline link field where you enter the url.

If you look at the page in text mode, you can see the empty <a> tags around the text

https://cl.ly/1y1C1n423X2k

In visual mode, after clicking on the empty link that was created, you can see the blank inline link toolbar that displays, but there's no input field so you still can't add a link.

https://cl.ly/2p0A472A2a3h

**Comment by jasmussen** [comment]
Thanks for the report. Closing as duplicates of #702 and #761.
