### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mejta** [WordPress/gutenberg#12870]
**Is your feature request related to a problem? Please describe.**
I write all my code in TypeScript and I have a problem with missing typing for Gutenberg and wp API. I have to define all typing by myself.

**Describe the solution you'd like**
It would be great to add typing to the DefinitelyTyped project (https://github.com/DefinitelyTyped/DefinitelyTyped)

**Describe alternatives you've considered**
At the moment I'm creating typings by hand :(

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31388

**Comment by youknowriad** [comment]
To be completely honest, this is very low priority for us. I understand the frustractions, but such definitions requires a good amount of time to maintain and that's not something that has an impact on our roadmap.

**Comment by chapterjason** [comment]
@mejta could you share your actual types?

**Comment by mejta** [comment]
@chapterjason It's very rough and definitely not complete, just for my project:

https://github.com/mejta/DefinitelyTyped/tree/master/types/wordpress__blocks
https://github.com/mejta/DefinitelyTyped/tree/master/types/wordpress__components
https://github.com/mejta/DefinitelyTyped/tree/master/types/wordpress__data
https://github.com/mejta/DefinitelyTyped/tree/master/types/wordpress__editor

I also stopped creating new types as it is too time consuming :(

**Comment by dsifford** [comment]
@chapterjason See also: https://github.com/WordPress/gutenberg/pull/14308#issuecomment-481466355

**Comment by youknowriad** [comment]
This was discussed several times. I'm going to close this in favor of #15027 (See the related discussions)

**Comment by aduth** [comment]
Note that WordPress NPM packages will now ship with first-party TypeScript types as of the changes in #18942.
