### ISSUE TITLE
Editor text size

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12887]
1. Why https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/ has `'name' => __( 'small', 'themeLangDomain' ),` instead of `'name' => __( 'Small', 'themeLangDomain' ),`. It displays incorrectly (with lowercase "s") in the admin that way.

2. How to make the "Normal" size reset the selection? It's not explained in the handbook.

**Comment by swissspidy** [comment]
What do you mean with "displays incorrectly"? Do you have a screenshot perhaps? `Small` or `small` should not make a difference as it's just different capitalization.

**Comment by manake** [comment]
I mean:
1. Select paragraph
2. In the sidebar see drop-down that says "small" (looks broken, why lowercase). It should say "Small".

**Comment by afercia** [comment]
I guess `theme-support.md` needs to be updated? Also, not sure `shortName` is still used. /Cc @chrisvanpatten

**Comment by chrisvanpatten** [comment]
Just noticing this, yeah it looks like a small typo. I'll add to the docs label so we can triage.

**Comment by mkaz** [comment]
Closing, this was fixed in https://github.com/WordPress/gutenberg/pull/13082
