### ISSUE TITLE
Allow validation to fail during development

### ISSUE THREAD

**Issue by colinduwe** [WordPress/gutenberg#12883]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by colinduwe** [comment]
**Is your feature request related to a problem? Please describe.**
It would speed custom block development if the block rendered even if it failed validation.

**Describe the solution you'd like**
If DEBUG_SCRIPT is true and the block being developed has isDev prop set true the block is rendered as returned by .save(), perhaps with a exclamation point or some other indicator that validation failed so data loss may have happened.

**Comment by youknowriad** [comment]
While I agree that it's frustrating while developing, I'd still be against disabling it because it may cause actual bugs to go unnoticed.

Thinking we should close this issue for now.

**Comment by aduth** [comment]
Let's at least consolidate this to #7604.
