### ISSUE TITLE
Remove option to use classic editor (unless classic editor plugin enabled)

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#12888]
**Describe the bug**
After upgrading to WordPress 5.0 and installing the plugin, I am presented with the option to edit content in the classic editor even though I don't have the classic editor plugin installed.

![](https://cl.ly/3bfd36108377/Image%2525202018-12-14%252520at%25252011.05.10%252520AM.png)

![](https://cl.ly/9a45ef57175e/Image%2525202018-12-14%252520at%25252012.21.38%252520PM.png)

Related: https://github.com/WordPress/gutenberg/issues/11015

**Comment by designsimply** [comment]
Tested and confirmed that I see the option to edit content in the classic editor withe the Gutenberg 4.7.0 plugin installed on WordPress 5.0.1. 

If I click the "Classic Editor" link on the Posts or Pages screen and then click Continue, I see a blank screen and the following error in the console:

> TypeError: window._wpLoadBlockEditor is undefined
> post.php:1731:1

![screen shot 2018-12-16 at 2 02 39 pm](https://user-images.githubusercontent.com/1119271/50058832-455e0a80-013b-11e9-8135-85603a912b3d.png)
<sup>Seen at https://testingallthetime.com/wp-admin/post.php?post=47&action=edit&classic-editor running WordPress 5.0.1 and Gutenberg 4.7.0 using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by nfmohit-wpmudev** [comment]
Submitted #13217 addressing this issue.

**Comment by aduth** [comment]
This code should probably be removed altogether.

I'd started down this path on Friday, but there's a fair bit of the metabox code which makes assumption about `?classic-editor`. In fact, most of this code ought to probably also be removed, with an assumption that it be provided already through WP 5.0+ (set as a new minimum required version for the Gutenberg plugin).

**Comment by youknowriad** [comment]
I think this one done recently right @aduth ?

**Comment by aduth** [comment]
It's partially resolved by #13459, with final pieces slated to be removed by #13544 (approved).

I'll add a closing reference accordingly.
