### ISSUE TITLE
WordPress 5.0.1 mistakenly merges blocks intended to be kept separate

### ISSUE THREAD

**Issue by nicopujol** [WordPress/gutenberg#12894]
**Describe the bug**
Since WordPress 5.0, if we create 2 consecutive text blocks, save, exit the post, then come back in, the separately created blocks are now merged into one. This defeats the point of blocks and makes it impossible to later on insert an image block in between or move one block up or down. 

**To Reproduce**
1. Create a new post
2. Create a text block, enter "test 1"
3. Create another text block underneath, enter "test 2"
4. Save the draft
5. Exit the draft
6. Reopen the post. The two blocks are now merged.

**Expected behavior**
No merging please. Separately created blocks should remain separate. 

**Screenshots**
Upon request. I think you should be able to reproduce from the above. 

**Desktop (please complete the following information):**
 - OS: Win 10-64
 - Browser Chrome 70

**Additional context**
We were Gutenberg early users and had the plugin on. Now WordPress 5.0.1, no classic editor no gutenberg plugin, since it is part of core.

Thanks

**Comment by karmatosed** [comment]
I am currently unable to replicate this. If you are able to we can reopen this, but for now closing.
