### ISSUE TITLE
Add option to save block content as meta data

### ISSUE THREAD

**Issue by ajien** [WordPress/gutenberg#12895]
It would be nice to have the ability to save a block's content as a custom field. There should be an option in the inspector to specify the meta key. Multiple blocks can have the same meta key, and the values will be saved in an array. This would be helpful in cases where, for example, you would only like to pull all the text contents (from several paragraph blocks spread across the page) and not include images (or any other type of blocks) that have been inserted somewhere in between the paragraph blocks. This option should be available for core blocks and custom blocks.

I know it is possible to create custom blocks and save/retrieve attributes from meta, but what I am looking for is an ability to arbitrarily tell core blocks and custom blocks to save its contents to post_meta. For example, let's say I am building a new plugin that works like WooCommerce, where I was able to assign a block template for the CPT. In the template, I have several blocks of images (a main image and some extra images), as well as several paragraph blocks (a short description, a long description, etc) and a few other blocks for other type of information (price, shipping details, etc). I don't want to create new custom blocks when there already exists core blocks that I only need to extend to allow me to save the contents as custom fields. I also do not want every single block to be saved as custom field, but I want to be able to decide which paragraph block should be saved as short description, long description, etc. I also want to be able to choose from the image blocks one that I want to designate as main product image.

I guess if a javascript equivalent of add_post_meta/update_post_meta/delete_post_meta exist, this would be an easy fix.

Related to this feature would be the ability to pull existing post meta as block content.

**Comment by youknowriad** [comment]
That's what plugins like Gutenberg Custom Fields do, basically create custom blocks saving to meta on the fly.

> I guess if a javascript equivalent of add_post_meta/update_post_meta/delete_post_meta exist, this would be an easy fix.

This already exists, you can call `wp.data.dispatch( 'core/editor' ).editPost( { meta: { [key]: value } )`

**Comment by designsimply** [comment]
Closing since it appears an answer was provided. Thank you!
