### ISSUE TITLE
Spelling and Grammar check

### ISSUE THREAD

**Issue by PlanetPlayStation** [WordPress/gutenberg#12893]
**Is your feature request related to a problem? Please describe.**
It is so frustrating to be forced to use the right click method (browser spellcheck) when finishing up a document. Seems that if each block has "bold, Italic, insert link, strikethrough" that it could simply include the classic editors form of spell and grammar check.

**Describe the solution you'd like**
I would like the traditional spelling and grammar check that was in the classic editor to be placed on teh options bar for each block. You could even include it in the 3 dot drop down as an option there although I see more people needing spelling and grammar check more so than strikethrough. Maybe push strikethrough to the 3 dot drop down menu and place the traditional spelling and grammar check option right next to the insert hyperlink option. 

**Describe alternatives you've considered**
The ONLY alternative there is that I know of is to use the right click option on a word that has the red squigglies under it and hope my browsers spell check can be right. I've had several instances where my browser had no suggestion to a particular word. Also there isnt an option for grammar check in my browser meaning if I type a word correctly but grammatically it doesn't make sense in the sentence then you will never know because the browser simply sees it as a correctly spelled word.

**Comment by swissspidy** [comment]
WordPress doesn‘t have any built-in spell checking by default, neither in Gutenberg or the Classic Editor. Are you using any plugins for that?

**Comment by Soean** [comment]
Maybe you are using the Jetpack with the Proofreading feature? https://jetpack.com/support/spelling-and-grammar/

**Comment by PlanetPlayStation** [comment]
I was using just the classic editor that came generic with wordpress. I never added a plugin for a spelling or grammar check. It was in the top box above the text where there was bold, underline, where where you could select heading 1-6 and the last was preformatted. It was like a 2 layer box of different things you could do editing wise and spelling and grammar check was one of them. It looked like the one in MS Word that had the check mark with ABC by it.

**Comment by PlanetPlayStation** [comment]
This is what I would love to see added or someone to tell me how to add this to my block editor. When you click on a block you get the first picture. I would love to see it added somewhere in this area so that I can assure myself and my guys writing for me have a proper way to not only spellcheck but grammar check as well. The second image is from the Wordpress default as when I signed up and started using WP this was what I got without anything being added as a plugin or anything. Hope this clears this up. And if you know of a way to get this on  the block editor either through a separate plugin or whatever please let me know.
![wordpress how it came](https://user-images.githubusercontent.com/45861459/50050312-adb9d700-00bc-11e9-9cc4-bbf9cec75624.png)
![wordpress with block editor](https://user-images.githubusercontent.com/45861459/50050313-b14d5e00-00bc-11e9-94f0-7a6d0925c4d7.png)

**Comment by swissspidy** [comment]
Yup that's the button added by [Jetpack](https://github.com/Automattic/jetpack).

Your screenshots are from WordPress.com and their [Calypso](https://github.com/Automattic/wp-calypso) interface. Please follow https://github.com/Automattic/wp-calypso/issues/28550 for updates on spellcheck integration in Calypso with the new Gutenberg editor.
