### ISSUE TITLE
Eliminate redundant instructions with blank blocks -- 'Start writing or type / to choose a block'

### ISSUE THREAD

**Issue by markarms** [WordPress/gutenberg#12896]
It's visually distracting to see every paragraph break / unused block [repeating the same instructions](https://markarmsdotcom.files.wordpress.com/2018/12/Screen-Shot-2018-12-14-at-8.43.35-PM.png) -- we should hide repeat instructions when more than one block is created with nothing inside.

**Comment by alexcroox** [comment]
Did you find a solution to this?

**Comment by kjellr** [comment]
Thanks, @markarms! I'm going to close this issue as a duplicate of https://github.com/WordPress/gutenberg/issues/12896 since that one has a bit more detail and a screenshot. We'll still track this issue, and you can follow along there. 👍 

Thanks!
