### ISSUE TITLE
So many embed blocks o my..

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1289]
Having a video, audio and image block as pillars for embeds would be great. 
Having an embed for a lot of sites that a person might use does not seem logical to me. It really crowds up the Block space.

When the user needs to embed a video they can pick video embed. Then add the url to whichever site they are taking it from. The block should then just recognize the url and insert the correct code to get it to work. If for whatever reason it does not work then a generic message can show up saying the site is not supported or something similar.

**Comment by jasmussen** [comment]
We are discussing how to add tabs to the inserter in https://github.com/WordPress/gutenberg/issues/983#issuecomment-309577472 (though perhaps we should open a separate issue for it, what do you think @jwold?)

However the individual aliases for embeds are not going away. They are intentionally there to surface the embed features, and solve one of the key goals of the editor focus:

> The editor will endeavour to create a new page and post building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML, or “mystery meat” embed discovery.

The "mystery meat" discovery is this. Very few people know how much WordPress supports out of the box. By putting explicit block links in the inserter we fix this.
