### ISSUE TITLE
Add Editor toolbar button

### ISSUE THREAD

**Issue by suhashininithy** [WordPress/gutenberg#12898]
Hi., 

How can a add my own button over the gutenberg editor toolbar like this http://prntscr.com/lv878w ?

![download-issue-12898](https://user-images.githubusercontent.com/1119271/52599805-e523d600-2e16-11e9-8d78-48cc55fad520.png)

**Comment by designsimply** [comment]
Closing with the note that adding a button like that is not done through an officially supported API and adding that a good place to continue when asking for help with custom code questions such as this one would be at https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/
