### ISSUE TITLE
Unable to select fullwidth YouTube video block using mouse

### ISSUE THREAD

**Issue by benlk** [WordPress/gutenberg#12892]
**Describe the bug**
With a fullwidth YouTube block, I'm unable to use the mouse to select the block in order to access its properties, its grab handle, or its button bar.

You'd think that clicking the "YouTube" text here would select the block, or clicking inside the blue outline would select the block.

<img width="473" alt="screen shot 2018-12-14 at 4 59 56 pm" src="https://user-images.githubusercontent.com/1754187/50029777-e6c15100-ffc1-11e8-9faf-14e6401ed827.png">

Clicking on the video doesn't select the block; it only interacts with the video's controls.

The only way I'm able to get the UI for the block to appear is if I use the arrow keys to navigate into it from an adjacent block.

**To Reproduce**

Using WordPress 5.0.1, with or without the Gutenberg plugin active, with the [Largo theme, version 0.6.1](https://github.com/INN/largo/releases/tag/v0.6.1), or with the latest version of Twenty Nineteen.

1. Create a YouTube block and set it to full width.
2. Click on any other block
3. Try to select the YouTube block using the mouse

**Expected behavior**
The block should be selected/activated when:
- Clicking within the outline
- Clicking on the "YouTube" tag that appears when the block is hovered 

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Firefox 64, 64-bit

**Comment by draganescu** [comment]
Howdy @benlk ,

I have tested this and it worked as expected. I will close this but feel free to let us know if you can still reproduce the issue using an updated version of Gutenberg.

Thank you.
