### ISSUE TITLE
Auto focus the editor?

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#129]
Auto focussing the editor may help make clear that the text is editable. This is currently done in the single instance TinyMCE prototype.

https://wordpress.github.io/gutenberg/tinymce-single/

**Comment by iseulde** [comment]
See https://docs.google.com/document/d/1fPkjVOkveDEfuaTWQNImM3IZUcgHPBbcdheezHeBivw/edit

**Comment by jasmussen** [comment]
It may be too early to optimize this far, when it's still mostly the prototype that's being tested. I wouldn't think it unlikely that some of these aspects change once the surrounding admin chrome arrives. At that point you will have intentionally navigated to a "Write New" page, and you'll see publish buttons around the editor. Perhaps this puts people in a better mindspace.

Let's definitely keep the ticket open as something to explore later on, if it remains an issue.

**Comment by mtias** [comment]
Going through some of these open questions, let's close for now until we start refining a single prototype / direction.
