### ISSUE TITLE
Missing .is-dark-theme for Media & Text text blocks move control

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#12908]
**Describe the bug**

The paragraph sub-blocks in the Media & Text block seem to be missing the .is-dark-theme styling for the move up and down controls.

**To Reproduce**
1. Add a Media & Text block to a dark theme.
2. Add an image.
3. Add more than one paragraph to the text sub-block. You need to add more than one paragraph.
4. Hover over one of the paragraphs. The move up and down control on the upper left display using default styling, not the the dark theme styling found when a paragraph is included in the top level block portion.

**Expected behavior**

The controls are still functional, and display the up and down carets when you hover, but otherwise are just white blobs.

The move control should be the same in all blocks, including the blocks in the Media & Text block.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] - WP 5.0.1

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by jorgefilipecosta** [comment]
I'm able to reproduce this problem. It is not exclusive of Media & Text, for example, if we add multiple paragraphs in a column the same problem happens there. I think it happens in all InnerBlocks contexts.

**Comment by youknowriad** [comment]
Now all movers have backgrounds (dark mode or not), which means this issue is closed
