### ISSUE TITLE
Better handling of older WP versions

### ISSUE THREAD

**Issue by ruucm** [WordPress/gutenberg#1290]
It emits PHP error like below.

`Fatal error: Uncaught Error: Call to undefined function wp_add_inline_script() in /var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php:60 Stack trace: #0 /var/www/html/wp-includes/plugin.php(525): gutenberg_register_scripts_and_styles('') #1 /var/www/html/wp-settings.php(392): do_action('init') #2 /var/www/html/wp-config.php(92): require_once('/var/www/html/w...') #3 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #4 /var/www/html/wp-admin/admin.php(31): require_once('/var/www/html/w...') #5 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...') #6 {main} thrown in /var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php on line 60`

WordPress 4.4.10 / Gutenberg Version 0.1.0

**Comment by Soean** [comment]
Hey ruucm,
thanks for your issue report. The Gutenberg Editor is a Feature Plugin for the WordPress Core. The Plugin is just for testing and will be merged in WordPress 5 or later. So there will be no endeavor for supporting old WordPress versions.

As mentioned on the plugin repository the minimal required WP version is 4.8
https://wordpress.org/plugins/gutenberg/

**Comment by jasmussen** [comment]
Closing as resolved. Thanks @Soean!

**Comment by ruucm** [comment]
Thanks for a kind reply @Soean

**Comment by nylen** [comment]
This is not that difficult to fix (check WP version on init and show an admin notice if WP is too old).
