### ISSUE TITLE
wp.blocks.unregisterBlockStyle() does not appear to be working

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#12915]
**Describe the bug**
When using `wp.blocks.unregisterBlockStyle()`, the specified block style variation is not unregistered.

**To Reproduce**
1. call `wp.blocks.unregisterBlockStyle( 'core/quote', 'large' );` or similar.
2. Block style variation is still available in the editor.

**Expected behavior**
Specified block style should be removed.

WP 5.0.1

**Comment by mor10** [comment]
see https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/

Also, the example in documentation doesn't work because the `fancy-quote` style doesn't exist. Should be updated.

**Comment by espenjanson** [comment]
You need to do this as well:

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#hiding-blocks-from-the-inserter

**Comment by espenjanson** [comment]
But docs are not clear, agreed!

**Comment by mor10** [comment]
"Not clear" is an understatement.

**Comment by espenjanson** [comment]
I think that goes for 98% of the docs

**Comment by mor10** [comment]
Wait, this doesn't make any sense. You use the `enqueue_block_editor_assets` hook to register / unregister blocks and variations (https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#using-a-blacklist), but to remove them from display, you have to use the `allowed_block_types` hook? What's the point of unregistering them then?

**Comment by reactforwordpress** [comment]
Guessing here but wouldn’t a simple hide from inserted mean that you could still use registered blocks in transforms etc?

**Comment by swissspidy** [comment]
How are you calling `wp.blocks.unregisterBlockStyle( 'core/quote', 'large' )`? In the developer console or in a JS file added with `wp_enqueue_script()`?

**Comment by espenjanson** [comment]
@swissspidy Since the only way I (and mor10) can get it to work is the solution I suggested, I think the downvote is uncalled for. Unregistering blocks doesn't work using only js.

**Comment by swissspidy** [comment]
@espenjanson Hiding blocks from the inserter is something different than removing block _styles_, isn't it?

I was asking about the enqueueing because there can be race conditions when not adding `wp-edit-post` as a dependency. See the discussion at https://github.com/WordPress/gutenberg/pull/12613#pullrequestreview-184781846 about this.

**Comment by espenjanson** [comment]
@swissspidy Well I think the ends justify the means here, I think we both understand what he was trying to achieve. Don't you? With all these issues, us developers are currently relying on workarounds like mine until you fix all these issues and update the documentation.

**Comment by mor10** [comment]
@swissspidy I'm calling `wp.blocks.unregisterBlockStyle( 'core/quote', 'large' )` from a JS file using `wp_enqueue_script()` hooked at `enqueue_block_editor_assets`. This has no effect on the editor and the block style remains in place.

**Comment by ocean90** [comment]
See https://github.com/WordPress/gutenberg/issues/11338#issuecomment-441451465 and #11392

**Comment by mor10** [comment]
Documentation definitely needed.
