### ISSUE TITLE
Need ability to add images to list block

### ISSUE THREAD

**Issue by koolkatwebdesigns** [WordPress/gutenberg#12919]
I would be nice to have the list block include images with in the flow of the list via the visual editor. The idea is that you could have something like the following
1. some text
   image
2. some more text
    image 2

While the above can be accomplished with the HTML editor, this is not very user friendly.

Preferred solution
The ability the drag or upload an image into the list

HTML works but is not a good solution for an end-user.

**Comment by youknowriad** [comment]
I was able to add an inline image into the list block using the inserter. We can't easily add `<br />` though inside a list item without going to the HTML mode. This is tracked here https://github.com/WordPress/gutenberg/issues/11215

Let's close this as a duplicate.
