### ISSUE TITLE
Pasting from Word into Quote Block copies Word's HTML

### ISSUE THREAD

**Issue by koolkatwebdesigns** [WordPress/gutenberg#12920]
**Describe the bug**
![screenshot 2018-12-15 15 36 56](https://user-images.githubusercontent.com/3653239/50048383-5cd7bd80-007f-11e9-896b-1436d010258c.png)

**To Reproduce**
1. Edit  a post or page 
2. Insert  quote block
3. Paste some text from Word
4. Notice the result as in the attached screenshot

**Expected behavior**
Text from Word should paste in as it does in a paragraph block

**Screenshots**
This is attached

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.1
 - Browser Chrome 71.0.3578.98 

**Notes 
It works fine if "paste and match style" is used but this is not user friendly

**Additional context**
Running WordPress 5.0.1 with Gutenberg in core.

**Comment by gregrickaby** [comment]
Confirmed. I came here to open this very same issue.

- Mac OS 10.14
- Chrome 71
- WordPress 5.03

![screenshot](https://dl.dropbox.com/s/bxr0872fqeqix7b/Kapture%202019-01-14%20at%207.07.40.gif?dl=0)

**Comment by mwidmann** [comment]
I found a way to fix this for custom Blocks using a RichText Component, but I have no clue at the moment, why this solves the issue. I'll put it here for reference, so maybe it helps figuring out the issue.

adding the following code to the <RichText /> Element fixes the issue with pasting from word:

```html
<RichText
    ...other attributes you might have
    unstableOnSplit={(before, after, ...blocks) => {
      /* does nothing... */
    }}
/>
```

It doesn't have to do anything.... it is enough that this attribute is on the element and the junk from Word is removed.

**Comment by littlebirdweb** [comment]
I've encountered this bug but had some success in dealing with it by copying and pasting the text from Word into a Paragraph block then converting the block to a quote block. This seems to  strip away all the Word formatting junk and leave you with the HTML you need for a blockquote.

**Comment by mcsf** [comment]
Could you share the output from your browser's console as you perform the paste? Thanks.

**Comment by johnridesabike** [comment]
I’ve observed this same bug occur when pasting from Word into an image caption.

**Comment by youknowriad** [comment]
Closing as stale. Let's reopen if we find ways/steps to reproduce this.

**Comment by maggie-drupal** [comment]
We notice this also in Drupal Gutenberg.
It happens on: Quote, Verse, Content in Columns, Table and PullQuote.
The issue must be reopened
