### ISSUE TITLE
Korean Bug again...

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#12926]
![ezgif-2-3ec592111ecc](https://user-images.githubusercontent.com/44285360/50053658-3a779a00-017c-11e9-9aa9-0094f0efbd18.gif)
It is very annoying bug... Gutenberg is not good with korean really... Please fix it.

And... I want #11956 will be better too. I know you work so hard but Please care it too...

**Comment by studio-jt** [comment]
We noticed the same bug on WP 5.0.3 . Hope you will find a fix soon. It makes the block editor very unpleasant to use for Korean users.

**Comment by cheonmux** [comment]
I have a same problem.

**Comment by youknowriad** [comment]
Which version are you trying? is it the last Gutenberg plugin release (5.3) ?

**Comment by cheonmux** [comment]
@youknowriad Hi, I don't know which Gutenberg version do i use exactly. i just use latest Wordpress 5.1.1 Version.

**Comment by youknowriad** [comment]
Thanks for the precisions @cheonmux, WP 5.1.1 is based on Gutenberg 4.7. I'm asking cause this might have been fixed in the meantime in the recent versions of the plugin which will come soon in WP 5.2

**Comment by studio-jt** [comment]
@youknowriad  @MYIG  I confirm the bug has been fixed on WP 5.2 . No more weird behavior when typing in Korean. Thank you

**Comment by youknowriad** [comment]
Awesome thanks for the update @studio-jt
