### ISSUE TITLE
Adding a number greater than 100 or less than 1 breaks the Latest Comments block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12922]
**Describe the bug**
If you manually add a number that's greater than 100 or less than 1 into the _Number of Comments_ field, the block breaks.

![screenshot_260](https://user-images.githubusercontent.com/2078245/50050833-4bafaf00-015a-11e9-9e08-ca0646c95979.png)

**To Reproduce**
1. Add Latest Comments block
2. Enter `101`, `0` or `-1` into the _Number of Comments_ field
3. See block break

**Expected behavior**
The _Number of Comments_ input field should default back to either 100 or 1 when a number greater than or less than either of those numbers are entered. 

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3
- WP 5.0.1

**Comment by swissspidy** [comment]
Noticed the same in https://github.com/WordPress/gutenberg/issues/10791#issuecomment-447396495

It‘s a general bug with the RangeControl component as it doesn‘t enforce min/max when typing a number
