### ISSUE TITLE
No active indication of selected white colour in colour palette 

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#12923]
When a colour option is selected, the background of the option turns white and there is a box shadow of the background of the colour. This is fine for dark colours, but for lighter colours the difference to how the option normally looks is almost indiscernable, and for a white colour there is no difference. In the screenshot below, the second option (#fff) is selected for the text colour but you wouldn't be able to tell without looking at the DOM.
![image](https://user-images.githubusercontent.com/12673074/50051504-32f5c800-015f-11e9-9f95-b6b2577c2a27.png)

As there is no colour that will work for all colours, I suggest that the active option is styled the same as when focused (an outline) and/or when hovered (20% larger).

**Comment by priyankabehera** [comment]
Hi @jorgefilipecosta , 
I have checked the color setting in the latest WordPress 5.0.2 and the white color is not in the default listed color. So design is not needed anymore.
![12923](https://user-images.githubusercontent.com/28857864/50757817-763ae680-1286-11e9-9254-b0db745c8c2e.png)

**Comment by jorgefilipecosta** [comment]
Hi @cameronjonesweb and @priyankabehera thank you both for analyzing this issue.
Although white is not a default color a theme may have white as part of its color palette so we should still try to address this problem.
cc @jasmussen has he may have some insights of a possible design solution for this problem.

**Comment by jasmussen** [comment]
Created a fix in #13274. Now there's a permanent border color change on a swatch that's selected, white or not, and in addition there's a checkmark overlay. 

Good ticket, good discussion, thanks everyone. I would advise against the use of thumbs down, though, even if it's meant as kind disagreement — it is too easy to mis-interpret as negativity where none is intended.
