### ISSUE TITLE
Obstructive User Interface: Relocate popup block toolbar from Upper Left to Lower Right

### ISSUE THREAD

**Issue by seanbebliss** [WordPress/gutenberg#12935]
Obstructive User Interface
There is a little toolbar for editing style (with Bold, Italic, etc.) Each time you click on a block this pops up in the upper left corner of the blocks which obstructs the content we are dealing with (the lines we just wrote above the current block). As writers we often look back the previous sentence. It's a natural part of ensuring that what you're writing stays on track. But now I don't know where my track is, unless I click back to the previous block just to see what it says. It's like tripping as you try to walk with your shoelaces tied together.

I propose that little pop-up be relocated to the lower right corner of the current block. This allows us to always and immediately see what we're working on, at just a glace. While solving that problem it also provides an added bonus of efficiency for users as the button bar is now closer to the active-cursor-areas in the editor. Thus the two most clicked areas (the most recent text written + the style buttons) are now closer together and nothing is obstructing something else out of step.

**To Reproduce**
1. Go to your active block on the editor and click on the text of your most recent sentence.
3. See editor style button toolbar pop up. 
4. See the button toolbar blocking the bottom sentence in the block above your active block.

**Expected behavior**
Pool your skills and knowledge to improve UI.

**Screenshots**
![toolbar move](https://user-images.githubusercontent.com/8000668/50063795-83613a00-01e0-11e9-9357-b139248c3d4d.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Additional context**
- WordPress 5.0.1

**Comment by swissspidy** [comment]
Your suggestion is interesting, but I think that position would be way too odd for it to be usable.

IMO in this case the preferred route is to enable the "Top Toolbar" via the options menu in the top right corner:

<img width="304" alt="screenshot 2018-12-17 at 10 51 25" src="https://user-images.githubusercontent.com/841956/50079498-0dfa6700-01ea-11e9-8668-63a6a8a2a4c0.png">

<img width="731" alt="screenshot 2018-12-17 at 10 53 10" src="https://user-images.githubusercontent.com/841956/50079497-0dfa6700-01ea-11e9-8282-9dc9de1394da.png">

**Comment by seanbebliss** [comment]
Okay. I can use that if I must, but I would really like to try the lower
left pop out idea too.

Is there some bit of admin CSS I can apply to manifest that change?

**Comment by StaggerLeee** [comment]
It is irritating somehow. Allways was.
After more careful thinking it is easy to realize 90% of those toolbar buttons are used like once a month, once a year.

But, do not have any suggestion.

**Comment by afercia** [comment]
Just to note that, as accessibility team, we've asked a few times to have _at least an user option_ to place the block toolbar after the block itself. That would help keyboard accessibility as the DOM order would match the logical order "write content > apply formatting".

Worth also noting the toolbar at the bottom is already what Gutenberg uses in the mobile view:

<img width="437" alt="screenshot 2018-12-26 at 16 52 00" src="https://user-images.githubusercontent.com/1682452/50450531-02681800-092f-11e9-9a44-23262daee7bd.png">

(though in this case DOM order and visual order mismatch)

**Comment by mapk** [comment]
Moving the block toolbar could present other issues right now. I'm closing this in favor of the existing solution of moving the toolbar to the top of the editor as [mentioned in this comment](https://github.com/WordPress/gutenberg/issues/12935#issuecomment-447785449).

If this problem becomes a larger issue, we can look at this in the future again.
