### ISSUE TITLE
Wordpress - Gutenberg - registerpost - conflict

### ISSUE THREAD

**Issue by TiveNation** [WordPress/gutenberg#12934]
Does anybody know or have encoutered same issue.

When you have named your post type and taxonomy same. U cannot use 'show_in_rest' => true,  on both of them.. So u must choose one, wich is obv... post type.

But doing that, you will lose taxonomy when editing that post type. (not shure when editing any other).

This is the error from "Network":
![image](https://user-images.githubusercontent.com/45925669/50060812-7c670700-01a1-11e9-9ad8-429f430ce91b.png)
code: "rest_invalid_param"

Caused when:
// POST PORTFOLIO
function kyre_registerpost_portfolio() {
     
    $labels = array(
        'name'               => 'Portfolio',
        'singular_name'      => 'Portfolio',
        'menu_name'          => 'Portfolio',
        'add_new'            => 'Lisa projekt',
    );
 
    $args = array(
        'labels'             => $labels,// (labels for admin panel)
        'public'             => true,
        'menu_position'      => 25,
        'menu_icon'          => 'dashicons-admin-page',
        'supports'           => array(
            'title',
            'editor',
            'excerpt',
            'thumbnail'),
        'taxonomies' => array(
            'portfolio', 'teenused', 'harud', 'partnerid', 'teenusegrupid'),
        'show_in_rest' => true,

    );
     
    register_post_type('portfolio', $args );
}
add_action( 'init', 'kyre_registerpost_portfolio' );

//CAT. PORTFOLIO
function kyre_registertax_portfolio() {
  // create a new taxonomy
  register_taxonomy(
    'portfolio',
    'portfolio',
    array(
      'label' => __( 'Cat. Projektid' ),
      'labels' => 
        array( 
        'add_new_item' => 'siit_ei_lisa! (automaatne)',
        ),
      'hierarchical' => 'true',
      'rewrite' => array( 'slug' => 'portfolio' ),
      **'show_in_rest' => true,**
    )
  );
}
add_action( 'init', 'kyre_registertax_portfolio' );

**Comment by swissspidy** [comment]
Closing as this is indeed an issue with `rest_base`.
