### ISSUE TITLE
Do not require brackets to be used in the shortcode block

### ISSUE THREAD

**Issue by Orrison** [WordPress/gutenberg#12939]
Since we now have an entirely separate block for shortcodes why do we continue to require brackets to be used for shortcodes within that block?

It should be optional, if the end user finds it visually nicer to include the brackets that is fine. But since shortcodes are the only thing that should be input in a shortcode block it seems natural that simply typing the shortcode name and arguments within the block should work as well.

Right now it just outputs what is written in it as text.

**Comment by swissspidy** [comment]
In the long term, shortcodes should be replaced by blocks. Why now change the expected formats of shortcodes and teach people new formats? What if people write nested shortcodes in that field?

We'd have to save them with the added brackets anyway for backward compatibility. So I don't see any value in changing this in the UI only.

**Comment by Orrison** [comment]
Hmm okay, that makes sense.

I guess it leads back into #10790 and https://github.com/WordPress/gutenberg/issues/7357#issuecomment-431314136 where some input validation would be awesome in this blocks field.

It can be embarrassing accidentally not adding the brackets and all of a sudden text is output onto your site rather than the expected shortcode. So some helper to the end user letting them know they need to add a shortcode/the brackets can be helpful.

If y'all feel this isn't worth the time since you are hoping to phase out shortcodes anyways I can understand, but if that isn't going to be happening in the near future some additional UX would be great.

Appreciate all you do!

**Comment by aduth** [comment]
Thanks for the report. I'm inclined to close this in favor of #10790, i.e. feedback improvements for shortcode validity within the block. I expect that the block will always continue to require the brackets, unless design revisions are made to indicate that the text field of the block is intended to be the segment of text between the brackets (not currently the case).
