### ISSUE TITLE
Editor doesn't consistently show content (or editor tools/panels)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1293]
On a number of occasions I've tried to edit existing (Gutenberg) content, and I simply get a blank page.

https://cl.ly/340F1b3O3k1v

**Comment by youknowriad** [comment]
Could this be related and fixed by #1245

**Comment by jasmussen** [comment]
It looks like the same issue I get when I insert the freeform block, open the "More" ellipsis, then click outside the block to deselect it.

**Comment by aduth** [comment]
Closing as duplicate of #1235. Please reopen with additional information if it's not the same.
