### ISSUE TITLE
Enabling and disabling align-wide doesn't refresh the blocks

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12948]
**To Reproduce**
1. In functions.php add `add_theme_support( 'align-wide' );`
2. Create a new post with a full wide image and save it.
3. In functions.php remove `add_theme_support( 'align-wide' );`
4. Open the post editing screen and see that the image is still full wide.

**Comment by designsimply** [comment]
The clear steps here are great! I think this can be consolidated with #12333 so I have copied the steps into that issue for reference. Thank you!
