### ISSUE TITLE
Text Block: You can paste multiple paragraphs in

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1294]
As reported in https://github.com/WordPress/gutenberg/issues/1291#issuecomment-309706150, with screenshot https://cl.ly/011C0a450G2P, you can copy and paste arbitrary content into the basic text block.

Since it's only for single paragraphs, this appears to be a bug. 

Possibly related to #495

**Comment by aduth** [comment]
Can you clarify if this is for the freeform block or the text block? Seems to be the latter.

**Comment by jasmussen** [comment]
Nope, this is for the plain Text block. Here it is with textexpanded text:

![screen shot 2017-06-20 at 16 46 56](https://user-images.githubusercontent.com/1204802/27339445-27982270-55d8-11e7-9ee5-4fb60945ce45.png)

Here's the freeform block:

![screen shot 2017-06-20 at 16 47 15](https://user-images.githubusercontent.com/1204802/27339453-2bc0f994-55d8-11e7-87c2-99391157f9cf.png)

**Comment by iseulde** [comment]
First, we'll need this for sure: #1331.

So then there are a few option for this one:

* We build it in the parser. Pasted content is parsed, and it is all inserted correctly as text blocks (paragraphs). 😃
* We build it in the parser, but _only_ for pasted content. This means that parser for pasted content will do an extra effort to convert legacy (and pasted) content. 😃
* We paste it as inline content. 🙁
* We create a freeform block. ☹️

My favourites are one and two. :) See also #1133. cc @dmsnell

**Comment by dmsnell** [comment]
intercepting the paste is something I think we'll have to be aware of for all block types. what does it mean to paste formatted text into the embed URL input?

in this case, we could parse it as HTML with JS then split by top-level `p` tags and create separate blocks for each one

**Comment by iseulde** [comment]
Yeah, so we'd prefer to go for parsing paste content only (second option)? Sounds good to me too.

> intercepting the paste is something I think we'll have to be aware of for all block types. what does it mean to paste formatted text into the embed URL input?

In #1331, if the block does not have an `onSplit` prop, it will be pasted as inline content. So if you pasted paragraphs in a button, it will all be just text.

**Comment by iseulde** [comment]
Fixed in #1331.
