### ISSUE TITLE
Default values should be serialized and sent across Block Renderer to the front end.

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#12951]
**Is your feature request related to a problem? Please describe.**
Creating defaults is something that I love about the Gutenberg attribute definitions. Declaring them with a block that uses serversiderender allows those defaults to be seen in the editor, but not on the front end. Why wouldn't we want to use custom-built defaults on the front end? 

**Describe the solution you'd like**
Let default values be serialized and sent to the front end for server-side rendered blocks.

**Comment by jorgefilipecosta** [comment]
This issue gets solved as soon as Server-side awareness of block types is implemented  https://github.com/WordPress/gutenberg/issues/2751. The implementation will allow the front end to know the default values of the attributes.

**Comment by skorasaurus** [comment]
Is this now unblocked because of https://github.com/WordPress/gutenberg/pull/21065 ?

**Comment by jorgefilipecosta** [comment]
Closing this issue, as now we have a mechanism for server-side awareness of blocks and API's to retrieve metadata like default attributes on the server.
