### ISSUE TITLE
On Page load, Classic Block look empty

### ISSUE THREAD

**Issue by PierreBoislard3** [WordPress/gutenberg#12958]
**Describe the bug**
When i load a page or a post that use a classic block, the classic block don't render the text and look empty so i can't edit it. To be able to see the content i need to go on "More options" and click on "Edit as HTML" and the click back to "Edit Visually".

**To Reproduce**
1. Go on a page where you used classic block
![screen shot 2018-12-17 at 3 19 00 pm](https://user-images.githubusercontent.com/8480097/50113170-292b9d80-020f-11e9-9ff7-412b69205033.png)
The block appear but not the content. (No error in the console).

2. Click on 'More Options' and then on 'Edit as HTML'. The content will then appear
![screen shot 2018-12-17 at 3 26 31 pm](https://user-images.githubusercontent.com/8480097/50113534-2bdac280-0210-11e9-962d-21dcfc977d72.png)

3. Switch it back to "Edit Visally".
![screen shot 2018-12-17 at 3 24 09 pm](https://user-images.githubusercontent.com/8480097/50113421-db636500-020f-11e9-8dee-9e84562401b0.png)

4. Now the content load find and every thing is save correctly and render correctly in the front end. But if you refresh the page, the classic block will look empty again (put will still work in the front end).

**Expected behavior**
When the page load we should be able to see the content en edit it right away.

**Desktop (please complete the following information):**
 - OS: MacOS HighSierra
 - Browser : Chrome
 - Version: 70.0.3538.110

**Comment by designsimply** [comment]
I've tried testing a few different times from different browsers. I tested with WordPress 5.0.1 and Gutenberg 4.7.0 and also without Gutenberg activated on 5.0.1 using Firefox 63.0.3 on macOS 10.13.6 and Chrome 70.0.3538.110 on macOS 10.13.6.

May I ask for more information about your setup and the type of content you're working with?

First, can you confirm what version of WordPress you are testing with and confirm you are not using the Gutenberg plugin? You no longer need the plugin unless you are doing development work or testing.

Does this happen for every post or page or just some of them (if it's just some of them then we could look to see if something in the content is triggering the problem)?

Is the classic block the only block on the page where this problem happens?

Can you test with all plugins temporarily deactivated to rule out a plugin conflict?

When you first load a post or page with a classic block on it, are you able to see any errors in the console panel of your browser's web developer tools?

**Comment by designsimply** [comment]
#12678 appears to be the same issue. Let's continue the discussion there.
