### ISSUE TITLE
Quote block: the "Large" option on the left in the styles panel does not show a preview

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#12956]
Steps to reproduce:

1. Add a quote block.
1. Click the icon to "Change block type".
1. Check to see if the "Large" block style variation shows any preview.

<strong>Result:</strong> the "Large" block style variation for the quote block doesn't seem to show a preview for the selector—the preview on the right of it shows normally when you click on "Large" though.

![screen shot 2018-12-17 at 12 11 18 pm](https://user-images.githubusercontent.com/1119271/50109493-389ded00-01f5-11e9-881e-727c68acb0e3.png)
<sup>Tested with WordPress 5.0.1 and Gutenberg 4.7.0 `master` @ `ddac4f3cf` using Firefox 63.0.3 on macOS 10.13.6.</sup>

/hat tip @andreilupu for the original report in the 4.7 call for testing at https://make.wordpress.org/test/2018/12/12/call-for-testing-gutenberg-4-7/#comment-1140

**Comment by mapk** [comment]
@laurelfulford noticed this problem recently due to a Twenty Nineteen theme Trac ticket. It's due to the larger amount of margin-top the quote uses. The margin pushes the quote out of view from the smaller preview window.

We need a way for the preview to ignore the margin or maybe force the margins to be less in the preview window.

**Comment by Presskopp** [comment]
for reference, here the trac ticket:
https://core.trac.wordpress.org/ticket/45385

**Comment by skorasaurus** [comment]
Looks good to me now on Gutenberg 9.4.1 
![Selection_026](https://user-images.githubusercontent.com/955351/100013521-f8612500-2da2-11eb-93fe-e09652821c9f.jpg)

Reopen if you're still able to reproduce :)
