### ISSUE TITLE
Gutenberg produce BROKEN html output

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#12953]
How text looks in gutenberg editor:

https://i.imgur.com/ppbPMg7.png

![ppbpmg7](https://user-images.githubusercontent.com/1119271/50106483-2f108700-01ed-11e9-9e63-99a08c629ee2.png)

How output result looks:
https://i.imgur.com/YO3NGYT.png

![yo3ngyt](https://user-images.githubusercontent.com/1119271/50106488-32a40e00-01ed-11e9-8cf3-42b45b76831c.png)

Part of the text are gone
closing "strong" tag also is gone, producing WRONG html markup

Please fix it.

Wordpress 5.0.1

**Comment by EldarAgalarov** [comment]
How to reproduce:
Put h2 block with text: Пирамида распределения мировых богатств
Put paragraph block with text: По данным исследовательского отчета «Global Wealth Report 2018» от швейцарской компании «Credit Suisse», мировое благосостояние оценивается в $ 317 трлн. Эта сумма складывается из материальных (недвижимость, автомобили и другое ценное имущество) и финансовых (ценные бумаги, депозиты, пенсионные накопления и т.д.) активов за вычетом кредитов и долгов. Количество взрослого трудоспособного населения в мире составляет 5 млрд.

And what you see on output? only h2 but not paragraph block!

Next, add paragraph block above h2 block with text: Сегодня в мире живет более 7 млрд человек. Одни живут богато и роскошно, вторые — представители среднего класса, а третьи живут бедно и убого. Распределение богатства в мире не в пользу большинства населения. Почти все мировые ресурсы принадлежат небольшой части жителей планеты Земля. Справедливо ли подобное распределение ресурсов?

Now last paragraph is shown but it's WRONG - part of words and punctuation are lost!

**Comment by designsimply** [comment]
Aha! Thank you for the extra information, I was just about to ask about how this content was first created and to clarify about the screenshots.

I was trying to see in the first screenshots and I noticed this:

![screen shot 2018-12-17 at 11 39 08 am](https://user-images.githubusercontent.com/1119271/50107934-33d73a00-01f1-11e9-842a-9cbf4dcaceab.png)

became this:

![screen shot 2018-12-17 at 11 40 41 am](https://user-images.githubusercontent.com/1119271/50107942-39348480-01f1-11e9-9fc8-045a4cdb90fb.png)

And I saw the the ending `strong` tag was missing for the part of the text that begins with "63.91%".

However, trying with the example text you provided is much better and I will add the `Needs Testing` tag for that so we can look in more detail.

Can you tell also tell me a little more  took to get to this point? Did you write it with Gutenberg directly? Did you write it before upgrading to 5.0.1 and then press the "Convert to Blocks" button? Or did you copy the content from elsewhere such as a word processor or a different post or even another web page?

**Comment by designsimply** [comment]
I am not sure yet if it's relevant, but may I also ask if you have any plugins installed which modify content in any way? It's possible to have a plugin conflict, and we should test from our side first without plugins but it's also a good idea to make a note of them if you have any.

**Comment by EldarAgalarov** [comment]
I'm wrinig in with Gutenberg directly, without content conversion from classic editor into blocks

**Comment by EldarAgalarov** [comment]
I disabled all plugins and it not helped. In general i'm using WPML and Yoast SEO now.

**Comment by EldarAgalarov** [comment]
This issue related with https://github.com/WordPress/gutenberg/issues/13404

**Comment by designsimply** [comment]
Thank you so much for the follow-ups! I researched this and found that #13404 was closed as a duplicate of #12672 and there is a request in that issue to re-open the case at https://core.trac.wordpress.org/ and I wanted to leave a note here with the status that I found.

**Comment by SergeyBiryukov** [comment]
Tracked this down to an issue with `WP_Block_Parser`, let's continue the discussion in #13655.
