### ISSUE TITLE
Update block programmatically?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12960]
Is there a way to update a block programmatically?

This is related to this problem #12333

I want to trigger "remove `data-align="full"`" on page load to fix that bug.

If someone could post a list of all methods/operations that we can do (if any) programmatically that would be useful to have.

**Comment by swissspidy** [comment]
So you want to update the block markup in PHP, right? You could use the `render_block` filter to remove  `data-align="full"` for a specific block.

**Comment by manake** [comment]
Ok, I was thinking incorrectly about this issue. I was trying to disable wide alignments before the block's HTML is generated. That's not the right way of doing this. Never mind.

`render_block` is a good solution. Thank you.
