### ISSUE TITLE
Something happened in my website

### ISSUE THREAD

**Issue by leocheungcn** [WordPress/gutenberg#12964]
When i use the block editor,it can not save&publish…  also can not pick the date…show "Invalid date"
Here is the error information:
> TypeError: `month` must be a valid moment object
>     at t.default (https://website/wp-includes/js/dist/components.min.js?ver=7.0.3:19:51903)
>     at new t (https://website/wp-includes/js/dist/components.min.js?ver=7.0.3:12:100038)
>     at zf (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258)
>     at Mf (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:87:4)
>     at ph (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474)
>     at eg (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307)
>     at fg (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168)
>     at wc (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237)
>     at fa (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115)
>     at ng (https://website/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:149:69)

**Comment by swissspidy** [comment]
Hi there

Does this still happen with WordPress 5.0.1 and all plugins disabled and when using a default theme like Twenty Nineteen?

**Comment by leocheungcn** [comment]
@swissspidy Thank you for your help,i think i find out the problem…There is one plugin i used to link an APP,it reset API…

**Comment by swissspidy** [comment]
Great to hear you were able to resolve the issue!
