### ISSUE TITLE
If you enter a letter after changing to <strong>, the cursor will move to an inappropriate position.

### ISSUE THREAD

**Issue by blvtomoya** [WordPress/gutenberg#12966]
If you enter a letter after changing to <strong>, the cursor will move to an inappropriate position.

1. Enter the text.
2. Press the "B" button to make the letters <strong>.
3. Continue input
4. The cursor moves to the beginning of the <strong> created sentence.

[![Image from Gyazo](https://i.gyazo.com/51401d27ae24190cba6d34b46cb57c93.gif)](https://gyazo.com/51401d27ae24190cba6d34b46cb57c93)

**Desktop :**
 - OS: [macOS Mojave]
 - Browser [Safari]
 - Version [12.0.2 (14606.3.4)]

**WordPress :**
 - Version [5.0.1]
 - Site language [Japanese]
I do not use the Gutenberg plugin.

**Comment by iseulde** [comment]
Is this still an issue in the latest master, after #13697?

**Comment by iseulde** [comment]
Is this still an issue in Gutenberg 5.1?

**Comment by ellatrix** [comment]
Closing as there is no feedback.
