### ISSUE TITLE
Flashing background when typing inside an inline text boundaries

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#12978]
**To Reproduce**
1. Create a post with the following content

```
<!-- wp:paragraph -->
<p>some <em>italic</em> text</p>
<!-- /wp:paragraph -->
```

2. Put the caret inside the "italic" text
3. Start typing
4. Notice that the background of the inline boundaries is flashing

![flash](https://user-images.githubusercontent.com/1270189/50568497-9ce9a200-0d07-11e9-8ea5-10300d366e50.gif)

**Comment by Naerriel** [comment]
@youknowriad 
Unfortunately, I cannot reproduce this bug. Can you, please, tell me what is the block type you are experiencing the issue with?
Can you include a gif?

**Comment by youknowriad** [comment]
In my testing I'm just using the regular paragraph block and typing in an italic text. Unfortunately, I can't record a screenshot as the flashing won't be noticeable in the recording. It's very quick. (The gray background behind the italic text is flashing)

**Comment by iseulde** [comment]
I'm aware since a while of this issue, but didn't think it was a huge deal. The problem is the same as #11322: our rich text state is currently not away of the boundaries, so the attribute is remove, then reapplied by TinyMCE. Fixing #11322 would fix this, so I'm inclined to close this as a duplicate.

**Comment by youknowriad** [comment]
#11322 is a PR. Can we keep this issue to track the corresponding PR?

**Comment by iseulde** [comment]
Sure!

**Comment by m** [comment]
Any progress here?

**Comment by iseulde** [comment]
@m Working on it. I'll see if I can make any quick fix to avoid the flickering
