### ISSUE TITLE
Inline boundaries don't work properly when using multiple inline formats

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#12973]
**Describe the bug**

I have the following content in my post

```
<!-- wp:paragraph -->
<p><em>italic <code>code</code></em></p>
<!-- /wp:paragraph -->
```

Notice that it's impossible to move the caret after the `code` element, but before still inside the `em` to continue typing italic text.

**Expected behavior**
I expected the first right arrow key presse to go out of the code element but stay inside the `em` and the second one to go out of the `em`

**Comment by iseulde** [comment]
I wonder if this is an issue in TinyMCE inline mode as well. In any case, this will be resolved by #11322. Seems like I should prioritise that PR soon.
