### ISSUE TITLE
Gutenberg editor isn't translated when base url doesn't point at wordpress

### ISSUE THREAD

**Issue by wojciechmisztal** [WordPress/gutenberg#12979]
**Describe the bug**
Gutenberg editor isn't translated when base url doesn't point at wordpress, for example, when wordpress is in "example.com/wordpress_path/" instead of "example.com/"

**To Reproduce**
1. Create a wordpress website with wordpress outside of a root of an url
2. Change your language to other than English
3. Open editor
4. See that most (but not all) texts are not translated

**Expected behavior**
Translated texts.

**Screenshots**
Example with address where wordpress is in a subfolder (address: lp5.wp/offersite/), note that some texts (like the name of the category "Obrazek wyróżniający") in document options are translated, but for example all of the block options are not:
![image](https://user-images.githubusercontent.com/40260080/50157795-9d7b4500-02d2-11e9-86e0-df23df54f677.png)

Example with address where wordpress is in a root directory (address: lp5new.wp/), everything works:
![image](https://user-images.githubusercontent.com/40260080/50157749-8c323880-02d2-11e9-9379-392d9a06267f.png)

**Desktop (please complete the following information):**
I've checked it on Ubuntu, Arch Linux and Windows with both Chrome 71 and Firefox 64

**Additional context**
- Wordpress 5.0.1, fresh installation

**Comment by swissspidy** [comment]
This will be fixed in WordPress 5.0.2, see https://core.trac.wordpress.org/ticket/45528

You can test the current Release Candidate for that version here: https://make.wordpress.org/core/2018/12/18/wordpress-5-0-2-rc2/
