### ISSUE TITLE
Metabox placement

### ISSUE THREAD

**Issue by daviedR** [WordPress/gutenberg#12977]
Horrible placement of metabox. Users have to scroll to the end of the editor just to make a simple change on the metabox.

**Suggestion:**

It would be great if there is a floating bar on the bottom of the screen (or somewhere) where user can see all the available metaboxes as a tabs navigation. e.g. Yoast SEO, Custom Fields, etc. When clicking a tab, the floating bar would expand a panel (with a maximum height, some % of the screen height), and the selected metabox content would be displayed there. When clicking back on the editor, the floating bar collapse.

**Comment by StaggerLeee** [comment]
Gutenberg Demo Page is unnaturally long. Maybe this is your problem. Majority of Posts in real life are not so long.

Just take a look to (majority) of Make WP Core Posts: https://make.wordpress.org/core/

**Comment by rogerlos** [comment]
Just FYI, in my world (that of paying clients who use WordPress as a CMS), the Demo Page is of average length. Not all WordPress users type short "blog" style posts.

**Comment by StaggerLeee** [comment]
Lenght or height ?

**Comment by mtias** [comment]
The general recommended way to build extra functionality is using the Plugin API and add a toggleable sidebar, largely to avoid these kind of issues. There's also the option of rendering meta boxes in the sidebar if you so choose. The placement at the bottom is not ideal but exists for backwards-compatibility reasons.
