### ISSUE TITLE
Remove the text of the only item in a list block removes the list block entirely

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#12975]
**Steps to reproduce**

1. Create a list block
2. Type some text
3. Select all the text
4. Hit backspace

**Expected behavior**
I expect the content of the list item to be removed but I expect to still be in a list block unless I hit `backspace` once more.

**Comment by swissspidy** [comment]
Related: #12787, #12398, #8804, #8803

**Comment by iseulde** [comment]
I'll look into it.

**Comment by iseulde** [comment]
I cannot reproduce this issue after #13697. Could you confirm?

**Comment by youknowriad** [comment]
Works great now, thanks
