### ISSUE TITLE
 The comment delimiter link in Developer's Handbook doesn't exist.

### ISSUE THREAD

**Issue by andreilupu** [WordPress/gutenberg#12988]
**Describe the bug**
The link for the `comment delimiter` doesn't work in https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-attributes/.

**Comment by swissspidy** [comment]
Hmm https://wordpress.org/gutenberg/handbook/designers-developers/key-concepts/#delimiters-and-parsing-expression-grammar might be the correct one for that.
