### ISSUE TITLE
Can't pass className to core/column in template

### ISSUE THREAD

**Issue by Naxulanth** [WordPress/gutenberg#12999]
The className doesn't append to the column when passed as an attribute in a template.

    const TEMPLATE = [['core/columns', {columns: 3},
    [
        ['core/column', {className: 'test'}, [
        ]],
        ['core/column', {}, [
        ]],
        ['core/column', {}, [
        ]],
    ]]]

I am able to pass different attributes to different components, (placeholder to paragraph for instance) but can't get it to work with column.

**Comment by murphy46** [comment]
Were you able to figure out a fix for this? I'm running into the same issue. I can name core/columns (plural) but not core/column

**Comment by Naxulanth** [comment]
Unfortunately not, I looped around the issue by writing my own "block" component which accepts the parameters I initally wanted to pass to the column. 

You can hide the block component from the inserter by using 

`
	supports: {
		html: false,
		inserter: false
	}
`
in your block component if you don't want it to be used by itself.

**Comment by zkingdesign** [comment]
In case anyone else runs into this issue here's the solution:
```    
wp.blocks.registerBlockVariation (
        'core/columns', {
            name: 'section-intro',
            title: 'Section Intro',
            icon: 'portfolio',
            scope: ['inserter'],
            attributes: {
                className: 'section-intro',
            },
            innerBlocks: [
                ['core/column', {}, [
                    ['core/heading',
                        {
                            level: 3,
                            content: 'Some Title',
                            className: 'h2'
                        }
                    ],
                ]],
                ['core/column', {}, [
                    ['core/button',
                        {
                            content: 'View All',
                            className: ''
                        }
                    ],
                ]],
            ],
        }
    );
```
