### ISSUE TITLE
Extra Strong Tags Added To Bold Text

### ISSUE THREAD

**Issue by codingsince007** [WordPress/gutenberg#12991]
When copying text from a well formatted Word document and pasting into a Page visual view in WP 5.0.1 and then viewing in Code view there is extra tags added to bolded headings. This has happened on two separate pages I have created.

As an example here is part of the extraneous code that is added via WP;
```
<p><strong>S</strong><strong>H</strong><strong>A</strong><strong>RING INFORMATION WITH ADVERTISERS </strong><strong>OR </strong><strong>OTHER THIRD </strong><strong>P</strong><strong>A</strong><strong>R</strong><strong>T</strong><strong>I</strong><strong>E</strong><strong>S</strong></p>
```

It should say;

```
SHARING INFORMATION WITH ADVERTISERS OR OTHER THIRD PARTIES
```

For some reason extra Strong tags are being added between most of the characters.

Reproduce this behavior by:
1. Take an existing Word Doc and copy all the text, be sure you have enough content like a Privacy Policy from a website or Terms and Conditions.
2. Create a new page in WP 5.01. 
3. Paste the contents of the word doc into the newly create page. 
4. Save the draft.
5. Preview or Publish the page. 
6. Open developer tools and view the code blocks or view the page in code view to see the different sections that have extra added tags.

I was expecting the code to be clean and concise but it looks very sloppy once the page was created.

![guttenberg code view](https://user-images.githubusercontent.com/30187521/50172519-e4f5d700-02ba-11e9-82d7-2f3782d60e2c.PNG)

![guttenberg code view2](https://user-images.githubusercontent.com/30187521/50172516-e45d4080-02ba-11e9-98a1-54986f2dda0a.PNG)

![extra strong tags added to code](https://user-images.githubusercontent.com/30187521/50172517-e45d4080-02ba-11e9-8988-42c0e8ba84f6.PNG)

Desktop:
Windows 10 64bit , Opera version 56.0.3051.116

WordPress 5.0.1

**Comment by iseulde** [comment]
This is a paste issue. Changed labels.

**Comment by iseulde** [comment]
@codingsince007 Could you share what's been logged in the browser console after you paste into Gutenberg? Does this work correctly in other editors such as [TinyMCE](https://www.tiny.cloud)?

**Comment by youknowriad** [comment]
This works as expected from me, let's reopen if we have more details.
