### ISSUE TITLE
Gutenberg translation broken only in multisites

### ISSUE THREAD

**Issue by edemir206** [WordPress/gutenberg#12994]
**Describe the bug**
When using multisite (folders) the translation works ok only in main site, in children sites the translation is not fully working.

**To Reproduce**
1. Install WP multisite (Folder) 
2. Create new site
3. Change new site language to Portugues or Spanish
4. Go to gutenberg Editor and see missing translations.

**Expected behavior**
The translations are missing

**Screenshots**

1) Main site gutenberg screenshot:

![image](https://user-images.githubusercontent.com/1863099/50181003-5604b100-02f2-11e9-8c95-171e27c79c58.png)

2) Subsite gutenberg screenshot

![image](https://user-images.githubusercontent.com/1863099/50180563-1ab5b280-02f1-11e9-95e5-d70bafa29cb5.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: Chrome, Safari, Firefox.
 - Version Any

**Additional context**
- Using Wordpress Version 5.0.1

**Comment by daskel** [comment]
The same problem with russian lang https://github.com/WordPress/gutenberg/issues/13007

**Comment by swissspidy** [comment]
@edemir206 Can you please give WordPress 5.0.2 a try?

You can test the current Release Candidate for that version here: https://make.wordpress.org/core/2018/12/18/wordpress-5-0-2-rc2

**Comment by edemir206** [comment]
Tested 5.0.2 RC2 and problem confirmed as SOLVED.
