### ISSUE TITLE
Pasting a New York Times URL results in an embed that is partially displayed

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#13000]
**Describe the bug**

When I paste `https://www.nytimes.com/2018/12/18/technology/walt-mossberg-quit-facebook.html` into a new post, WordPress attempts to use oEmbed to display the article, but instead just shows a partial thumbnail.

If I inspect with developer tools and remove the `height: auto;` that NYT delivers with the iFrame via `article.story .media .image img`, then I do see that other content is available, it's just not being displayed.

**To Reproduce**
1. Create a new post
2. Paste `https://www.nytimes.com/2018/12/18/technology/walt-mossberg-quit-facebook.html` into the first (or any) paragraph block.

**Expected behavior**

To be honest, I would expect that a pasted NYT URL does *not* embed automatically, but I'm probably in the minority.

The real expectation is probably that the embedded content appears in full.

**Screenshots**

![auto-embed-nyt](https://user-images.githubusercontent.com/286171/50195145-bc89cf00-02f2-11e9-9e7f-9f697d6184a4.gif)

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - Browser Chrome (latest)

**Additional context**
Using WordPress 5.0.1

**Comment by Sergiono** [comment]
I have the same problem

**Comment by iandunn** [comment]
Related https://github.com/WordPress/gutenberg/issues/15102

**Comment by jeremyfelt** [comment]
This has changed somewhat in that the (non-WordPress) NY Times URL is detected as a WordPress embed block and results in the following code:

```
<!-- wp:core-embed/wordpress {"url":"https://www.nytimes.com/2018/12/18/technology/walt-mossberg-quit-facebook.html","type":"wp-embed","providerNameSlug":"the-new-york-times","className":""} -->
<figure class="wp-block-embed-wordpress wp-block-embed is-type-wp-embed is-provider-the-new-york-times"><div class="wp-block-embed__wrapper">
https://www.nytimes.com/2018/12/18/technology/walt-mossberg-quit-facebook.html
</div></figure>
<!-- /wp:core-embed/wordpress -->
```

The display itself still appears broken as originally reported.

**Comment by youknowriad** [comment]
I think this should probably be raised as a Core ticket instead as the embed HTML is not generated by Gutenberg itself but by the Oembed REST API.

**Comment by paaljoachim** [comment]
https://core.trac.wordpress.org/ticket/49185#ticket

**Comment by youknowriad** [comment]
Thanks @paaljoachim

**Comment by westonruter** [comment]
I think the underlying issue is captured in https://core.trac.wordpress.org/ticket/49173

In particular, the Kses call in `wp_filter_oembed_result()` is stripping the `style` attribute from the `iframe`.

**Comment by paaljoachim** [comment]
It would be great to get some movement on this issu

@desaiuditd has merged one issue in that we are now able to use a transform of an existing embed to a paragraph block (text link). We are working on another option to also convert existing embeds here: https://github.com/WordPress/gutenberg/issues/21789

But this issue we are talking about here is different.
@desaiuditd is this issue something you can take a closer look at?

**Comment by jeremyfelt** [comment]
Closing this because I'm pretty sure it's now https://core.trac.wordpress.org/ticket/49185
