### ISSUE TITLE
Pasting a WordPress.org Theme Handbook URL embeds as a single link

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#13001]
**Describe the bug**

When I paste https://developer.wordpress.org/themes/functionality/sidebars/ into a new post, WordPress attempts to use oEmbed to display the handbook page, but instead just shows a link to "Sidebar"

**To Reproduce**
1. Create a new post
2. Paste https://developer.wordpress.org/themes/functionality/sidebars/ into the first (or any) paragraph block.

**Expected behavior**

I would expect just the link to appear. Others might expect more of a styled blurb about the sidebars page on the theme handbook.

(It's also entirely possible that this is a https://meta.trac.wordpress.org/ bug instead)

**Screenshots**

![post-about-sidebars](https://user-images.githubusercontent.com/286171/50195369-957fcd00-02f3-11e9-86e2-75e94c70fb46.gif)

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - Browser Chrome (latest)

**Additional context**

WordPress 5.0.1

**Comment by dd32** [comment]
Just noting that I've created https://meta.trac.wordpress.org/ticket/4013 to track getting embed functionality for WordPress.org handbooks added.

I think I've seen similar behaviour from attempting to embed non-embeddable resources though too.

**Comment by DrewAPicture** [comment]
For what it's worth, I saw this same odd behavior just today when trying to embed something from the Gutenberg handbook, except the embed markup included only the title and a gigantic GitHub Octocat. 😉

**Comment by swissspidy** [comment]
I'm closing this for now as it's an issue with the handbook site, not the embed functionality in Gutenberg.
