### ISSUE TITLE
Toolbar flickering/jumping

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1300]
I just noticed this on Safari 11 on a Mac. Don't know if it happens in other browsers as well.

When selecting a block, e.g. when jumping from one block to another, the toolbar seems to change its vertical position a few times, making it flicker.

Demo: https://cloudup.com/c0Sc-3kivm7

**Comment by aduth** [comment]
Seems to be having trouble with the animation:

https://github.com/WordPress/gutenberg/blob/d80189e/editor/assets/stylesheets/_animations.scss#L6-L15

**Comment by karmatosed** [comment]
I am not seeing this on the latest version 1.0.0. If it can be replicated then please reopen, until then lets close.
