### ISSUE TITLE
Any use of window.confirm() causes browser tab to crash in Safari

### ISSUE THREAD

**Issue by clifgriffin** [WordPress/gutenberg#13019]
**Describe the bug**
Any JavaScript call to `window.confirm()` results in Safari browser tab hanging and crashing.

I've tested in Chrome, Firefox, and Safari. Only Safari exhibits this behavior.

**To Reproduce**
1. Open a post or page for editing in Gutenberg. 
2. Open up the Developer Tools and click on Console
3. Type `window.confirm('Foo?') and press <Enter>
4. Observe that browser tab has now crashed. 

**Expected behavior**
I expect to see a browser dialog with the word "Foo?" and the buttons "Cancel" and "OK". 

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - Browser: Safari
 - Version 12.0.1

**Additional context**
This was discovered in WordPress 5.0.1.

**Comment by swissspidy** [comment]
Works absolutely fin in Safari 12.0.2 on macOS 10.14.2:

<img width="1146" alt="screenshot 2018-12-19 at 17 41 58" src="https://user-images.githubusercontent.com/841956/50234204-6a5db200-03b5-11e9-9174-a0d92594f6c4.png">

Does this still happen after updating your system and disabling all plugins?

**Comment by clifgriffin** [comment]
At the time I only had a couple of plugins activated. I deactivated them, re-tested and it worked.

Then I reactivated them, re-tested...and it still worked.

A classic phantom bug. 👎 

Sorry for the false alarm. Closing.
