### ISSUE TITLE
Inconsistency with Dragging to Select Text 

### ISSUE THREAD

**Issue by markarms** [WordPress/gutenberg#13026]
**Is your feature request related to a problem? Please describe.**

My biggest difficulty with Gutenberg is that selecting and manipulating text is awkward -- I see different behaviors depending on where my mouse is located when I start to drag and select text on the screen. See the attached video -- different behaviors occur when: 

-My mouse is hovering over the title or a blank block. 
-My mouse is hovering over the left margin. 
-My mouse is inside a block with text. 

Video: https://markarmsdotcom.files.wordpress.com/2018/12/dragging-and-selecting-480.mov

So, when I drag to select text, it ends up selecting all of the blocks (not the text), or just the text, or nothing at all. All the while, this mouse movement is triggering the appearance of block outlines and the "add block" symbol both on the left of every block and in the center between each block. 

**Describe the solution you'd like**

Right now it feels like I'm trying to manipulate text behind a thin layer of glass -- the blocks are constantly asserting themselves as the FOREMOST experience inside the editor. I would like to find a way for text manipulation, selection, and editing to become the FOREGROUND experience for all mouse movement inside the WordPress Editor. Let's assume by default that all mouse movement and behavior is related to text, UNTIL the user triggers an action that introduces blocks and block manipulation.

**Comment by designsimply** [comment]
Thank you for asking about this! I would like to close in favor of #3629 which discusses cross-block selection and the issues you've raised and includes some notes about related design decisions as well as some of the technical implications about making a change. 

If you think this issue should remain separate, please do re-open it with a note!

**Comment by markarms** [comment]
Thank you @designsimply! I will stand down for now in favor of following #3629, but may reopen in the future.

**Comment by markarms** [comment]
Upon further reflection I think what I'm suggesting here is slightly different than issue #3629 so I'd like to re-open it. Thanks again @designsimply!

**Comment by jasmussen** [comment]
Good ticket, this is definitely something to fix. 

But this ticket is more about a bug in the current implementation, where if you _make a selection that starts outside of the actual editing canvas, you are selecting HTML that has nothing to do with the editor_. The obvious solution is to make sure that any drag action that happens inside the editing canvas invokes block selection, regardless of how that block selection might change depending on #3629.

**Comment by bozzmedia** [comment]
Has there been any progress on this or #3629? This problem continues to hamper my editing within Gutenberg. Lots of clicking 3-4 times to select the right text. Quite frustrating when trying to get a lot of content editing done, especially in 2 column layouts.

**Comment by designsimply** [comment]
Hi @bozzmedia. Thanks for chiming in and I'm sorry to hear you are frustrated! Progress for issues in this project are almost always noted at the bottom of the issue. Since nothing is showing up on this one, there hasn't been any attention to it. #3629, however, does seem to have some new work added but it is a draft format, which means developers are trying out some things and haven't settled on a solution yet.

**Comment by mtias** [comment]
Cross block text selection has been merged in #38892.
