### ISSUE TITLE
Hate Gutemberg

### ISSUE THREAD

**Issue by Ucanspam** [WordPress/gutenberg#13022]
I just discovered Gutemberg and I hate it.
It gives me 2 times more work than usual because I have to click back and forth to open or display options on my right sidebar. All the options I use to click doesn't appear as fast as they use to be. 
Okay I'm maybe not use yet to this nicer design, but really it gives me headaches to find quickly what I need to check or uncheck.
I don't find the interface so user friendly.
What a pity!
I gonna take it off for sure

**Comment by Soean** [comment]
Thanks for your feedback. Later today we release WordPress 5.0.2 with a lot of performance improvements, maybe they will give you a better writing experience.

GitHub is only for reproducible issues or feature request. You can leave feedback in the support forum https://wordpress.org/support/plugin/gutenberg

The project is called `Gutenberg` with a `n`.

**Comment by StaggerLeee** [comment]
I hate it too. For short time using it, it gave me Gutenberg sindrome. I keep clicking on the front-end trying to invoke Inserter. :)

It means it is really good and special.
