### ISSUE TITLE
Tests: Activate more popular plugins in the e2e test run on Travis

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#13038]
In #12578 we updated our setup for e2e tests on Travis. We activate 3 popular plugins which integrate with Gutenberg. We want to have more plugins to be able to discover any potential breaking changes as soon as possible. The idea is to have them activated to ensure that Gutenberg itself works when they all are active. We can add some very basic e2e tests for each plugin to the suite but this should be handled and maintained by each the plugin authors'.

Initially we wanted to enable `AMP` and `Yoast SEO` plugins but they introduce changes which interfere with our test suite. We didn't investigate it further to discover whethere the issue is on the tests side or the plugin side. We would love to get your help discover.

This is how you can enabled Yoast SEO in the e2e test run:

```diff
diff --git a/bin/install-wordpress.sh b/bin/install-wordpress.sh
index 40eec0810..55b93f5ad 100755
--- a/bin/install-wordpress.sh
+++ b/bin/install-wordpress.sh
@@ -96,6 +96,7 @@ if [ "$POPULAR_PLUGINS" == "true" ]; then
 	docker-compose $DOCKER_COMPOSE_FILE_OPTIONS run --rm -u 33 $CLI plugin install advanced-custom-fields --activate --quiet
 	docker-compose $DOCKER_COMPOSE_FILE_OPTIONS run --rm -u 33 $CLI plugin install jetpack --activate --quiet
 	docker-compose $DOCKER_COMPOSE_FILE_OPTIONS run --rm -u 33 $CLI plugin install wpforms-lite --activate --quiet
+	docker-compose $DOCKER_COMPOSE_FILE_OPTIONS run --rm -u 33 $CLI plugin install wordpress-seo --activate --quiet
 fi
 
 # Install a dummy favicon to avoid 404 errors.
```

If you want to test it with another plugin, you just need to replace `wordpress-seo` with your plugin name. e.g. `amp`.

**Comment by gziolo** [comment]
@atimmer @moorscode - can you help investigate with Yoast SEO?

@miina @westonruter - for amp plugin?

With the patch applied, this is how you run end-to-end tests in the browser:

```bash
PUPPETEER_HEADLESS=false PUPPETEER_SLOWMO=100 npm run test-e2e
```

**Comment by miina** [comment]
@gziolo Thanks so much for doing this.
Definitely can help investigating for AMP plugin but probably will get to this next week.

**Comment by dariaknl** [comment]
@gziolo I have looked into this issue using wordpress-seo plugin. Your test is failing with:
```
    Expected: "Hello World! And more."
    Received: "Hello World!"

      107 | 		// Title in preview should match updated input.
      108 | 		previewTitle = await previewPage.$eval( '.entry-title', ( node ) => node.textContent );
    > 109 | 		expect( previewTitle ).toBe( 'Hello World! And more.' );
```

- once the post has been published it does not get updated title in preview if you change the title.
Indeed the test succeeds with wordpress-seo disabled. 

But I tried the same test with built-in Advanced Panels “Custom Fields” enabled and wordpress-seo disabled. I get the same result - the test fails, updated title is not shown in preview. So it seems that the issue is related more to the problem with metabox in general. 

I tested with: WP 5.0.3 and Gutenberg 4.8.0 and 4.9.0.

Can be related to https://github.com/WordPress/gutenberg/issues/12617#issuecomment-456357335

**Comment by gziolo** [comment]
@dariaknl thanks for sharing this finding. I really appreciate your help with discovering what might be the reason we can't easily enable more popular plugins. I know there are some issues with the preview mode but this one is something which can be reproduced with the steps you shared. I also raised it on WordPress.org Slack in `#core-editor` channel:
https://wordpress.slack.com/archives/C02QB2JS7/p1548834996561400
