### ISSUE TITLE
Theme Based Columns

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#13037]
Currently i am creating a theme. My theme has 2 layouts, one has right sidebar and another has left sidebar. I want to use the column block but when i put two columns they appear both equal in size. I dont want that, What I want is one column 75% and another column 25%.

My question is can we define our custom colunm of 75% and 25% ?? 

if not then will this feature be included in upcoming updates??

Why not define our own column size by hook

eg. `add_column_block( 2 , 75% , 25%  );`

if i want three column then 

`add_column_block( 3 , 25% , 50% , 25%  );` where 3 is number of columns and 25% and 50% are column sizes

**Comment by youknowriad** [comment]
The last version of the columns block allows setting different sizes for each column, so that should be possible now.
