### ISSUE TITLE
Underlining text using the keyboard shortcut does not work consistently in major browsers

### ISSUE THREAD

**Issue by anmol257** [WordPress/gutenberg#13034]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by anmol257** [comment]
There is no option to underline text including heading. Clt + u opens source. So In order to underline every time I have to use HTML coding. Kindly provide a button for it within Gutenberg in order to improve convenience.

**Comment by swissspidy** [comment]
Previously: #7162, #12814, #10728.

---- 

In Chrome on macOS Ctrl + U works fine, bot in Firefox it does nothing.

**Comment by afercia** [comment]
On macOS the dedicated shortcut is Cmd + U, as listed in the Keyboard Shortcuts modal:

<img width="476" alt="screenshot 2018-12-26 at 17 03 19" src="https://user-images.githubusercontent.com/1682452/50450784-56bfc780-0930-11e9-9678-50bae3f4c575.png">

However, in Chrome it doesn't do anything, in Firefox it opens the view source. In the Classic Editor, it works. I'd call this a bug.

**Comment by talldan** [comment]
It seems like it must be a regression since it's been audited in the past as working:
https://github.com/WordPress/gutenberg/issues/71#issuecomment-408916912

**Comment by iseulde** [comment]
This no longer works since #12249 and is now not included in Gutenberg 5.1.

**Comment by afercia** [comment]
Underline has just been restored in https://github.com/WordPress/gutenberg/pull/14008

However, I'd recommend to review the keyboard shortcuts for the most common formatting. Some of these shortcuts use only one modifier key and still conflict with native browsers shortcuts, preventing access to browsers features.

Also, they're inconsistent with each other and very difficult to remember, for example:
```
- primary + b (bold)
- primary + i (italic)
- access  + x (code)
- access  + d (strikethrough) 
- primary + u (underline)
```
Image and Link are special cases, but I'd consider to make the formatting ones above use the same modifiers. Please let me know if I should create a new issue.

**Comment by iseulde** [comment]
@afercia Yes, please create a new issue. Also with detailed information about which formatting shortcuts are conflicting with the OS/browser.

**Comment by afercia** [comment]
> with detailed information about which formatting shortcuts are conflicting with the OS/browser.

I'm afraid that would be a bit too much for me :) no bandwidth to test all supported browsers in at least the 3 major desktop operating systems.

**Comment by afercia** [comment]
Created https://github.com/WordPress/gutenberg/issues/14031. I guess this one can be closed now? Please do feel free to reopen if I'm missing something.

**Comment by drewclifton** [comment]
Underline via `cmd+u` not working for me today on 5.1.1 (Chrome)

**Comment by iamkingsleyf** [comment]
still not working

**Comment by supernovia** [comment]
Just noting this isn't working in Chrome current on Mac current with command + U.

**Comment by supernovia** [comment]
Re-opening; Command+U in Chrome on current mac still does not work. On Firefox, it opens a new tab with View Source.

**Comment by supernovia** [comment]
https://github.com/WordPress/gutenberg/issues/14031 -  linking to the proper issue
