### ISSUE TITLE
Import from WordPress XML file strips paragraphs

### ISSUE THREAD

**Issue by eriktdesign** [WordPress/gutenberg#13049]
**Describe the bug**
When importing from a WordPress generated XML file, paragraph tags are not correctly added to posts.

**To Reproduce**
1. Export some posts from a WordPress website. Mine happened to be created on the classic editor.
2. Import the posts into a fresh install of WP 5.0.x
3. Posts are imported as "classic editor" blocks with single `<br/>` tags. 

**Expected behavior**
Paragraph tags should be added (just like wpautop does on the current site)

**Screenshots**
Here are links to an example.
Original site (correctly shows paragraphs): https://stpeterslutheran.org/2018/10/campers-camels-and-calculations/
Imported Site (paragraphs missing): https://whatwhen.blog/2018/10/campers-camels-and-calculations/

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 71

**Additional context**
- Please add the version of Gutenberg you are using in the description.
WP 5.0.2

**Comment by jasenwyatt** [comment]
Noticed the same thing happening.  

Very similar steps to reproduce:
1. Exported posts from a WordPress.com website.
2. Import the posts into a fresh install of WP 5.0.x
3. Posts are imported as a single `<p>` with `<br/>` tags.

**Comment by justinferrell** [comment]
Seeing this issue on a production website running 5.1

**Comment by webchris** [comment]
Just tried with 5.1.1 and same issue.

**Comment by lindatmuller** [comment]
Same problem here. WordPress 5.1.1 running GeneratePress theme. Exported into new install. All posts show no paragraphs - just one long block of text.

**Comment by astavelopment** [comment]
Same here, I tried importing posts from a different installation to a new 5.1.1 installation and all posts got paragraphs stripped off + embeds and image captions got broken and display parts of code with square brackets or the embed links instead of the actual way they are suppose to appear on the classic version editor.

**Comment by talldan** [comment]
Hi @eriktdesign. This issue was discussed during a triage session in slack. Two of us weren't able to reproduce the issue (https://wordpress.slack.com/archives/C02QB2JS7/p1582175807161800). 

It'd be good to understand if this is something you're still experiencing in more recent versions of WordPress.

During testing I observed this:
- The export process strips paragraphs from classic editor content
- After re-importing the content and previewing, the paragraphs were restored in the previewed post.
- In the block editor, the 'Convert To Blocks' option successfully creates paragraph blocks from the imported content.

This may be something that's theme dependent. I tested using Twenty Twenty as my theme.

As the issue couldn't be reproduced I'll close it, but if it's something you're still experiencing please do reply and I can investigate further.

**Comment by jaredlt** [comment]
@talldan I have just experienced this issue.

Export from Wordpress 4.9.15 to 5.4.2

Export XML

```xml
		<content:encoded><![CDATA[<span class="fontstyle0">TASK PR London has been appointed to manage all UK press and publicity for luxury womenswear brand Kaya Turello.</span>

<span class="fontstyle0">Introducing the 21st Century power dressing brand, with the vision to create designs that empower professional women. Created for businesswomen, Kaya Turello’s contemporary capsule collection embraces individuality, through timeless tailoring and bold colourways. </span><span class="fontstyle0">The collection is made up of five versatile power suit jackets, that can easily be mixed-and-matched with tailored separates from the brand, allowing you to create the ultimate ‘Power Suit’.</span>

<span class="fontstyle0">As a brand Kaya Turello believes that the classic blazer jacket is the key staple for any professional woman’s wardrobe, acting as an amour and elevating one’s confidence to the world. Designed in London each piece from the Kaya Turello collection is a timeless investment piece, for the </span><span class="fontstyle0">office and beyond. Featuring the perfect LBD and short suits, the collection covers all basis with some striking transitional after-hours looks for a modern power dresser.</span>

<span class="fontstyle0">Having spent almost 10 years in the City founder and designer Kaya Turello understands the importance of a professional image when </span><span class="fontstyle0">building a career, established to help professional women look and feel fashionable whilst maintaining a confident aesthetic.</span>]]></content:encoded>
```

NB. This wraps each line with a `<p>` tag in the original site which you can see here: https://www.taskpr.com/news/new-client-announcement-kaya-turello/

```html
<p><span class="fontstyle0">TASK PR London has been appointed to manage all UK press and publicity for luxury womenswear brand Kaya Turello.</span></p>
<p><span class="fontstyle0">Introducing the 21st Century power dressing brand, with the vision to create designs that empower professional women. Created for businesswomen, Kaya Turello’s contemporary capsule collection embraces individuality, through timeless tailoring and bold colourways.&nbsp;</span><span class="fontstyle0">The collection is made up of five versatile power suit jackets, that can easily be mixed-and-matched with tailored separates from the brand, allowing you to create the ultimate ‘Power Suit’.</span></p>
<p><span class="fontstyle0">As a brand Kaya Turello believes that the classic blazer jacket is the key staple for any professional woman’s wardrobe, acting as an amour and elevating one’s confidence to the world. Designed in London each piece from the Kaya Turello collection is a timeless investment piece, for the&nbsp;</span><span class="fontstyle0">office and beyond. Featuring the perfect LBD and short suits, the collection covers all basis with some striking transitional after-hours looks for a modern power dresser.</span></p>
<p><span class="fontstyle0">Having spent almost 10 years in the City founder and designer Kaya Turello understands the importance of a professional image when&nbsp;</span><span class="fontstyle0">building a career, established to help professional&nbsp;women look and feel fashionable whilst maintaining a confident aesthetic.</span></p>
```

But on the new site, once imported, it shows like this:

```html
<p><span class="fontstyle0">TASK PR London has been appointed to manage all UK press and publicity for luxury womenswear brand Kaya Turello.</span><br>
<span class="fontstyle0">Introducing the 21st Century power dressing brand, with the vision to create designs that empower professional women. Created for businesswomen, Kaya Turello’s contemporary capsule collection embraces individuality, through timeless tailoring and bold colourways.&nbsp;</span><span class="fontstyle0">The collection is made up of five versatile power suit jackets, that can easily be mixed-and-matched with tailored separates from the brand, allowing you to create the ultimate ‘Power Suit’.</span><br>
<span class="fontstyle0">As a brand Kaya Turello believes that the classic blazer jacket is the key staple for any professional woman’s wardrobe, acting as an amour and elevating one’s confidence to the world. Designed in London each piece from the Kaya Turello collection is a timeless investment piece, for the&nbsp;</span><span class="fontstyle0">office and beyond. Featuring the perfect LBD and short suits, the collection covers all basis with some striking transitional after-hours looks for a modern power dresser.</span><br>
<span class="fontstyle0">Having spent almost 10 years in the City founder and designer Kaya Turello understands the importance of a professional image when&nbsp;</span><span class="fontstyle0">building a career, established to help professional&nbsp;women look and feel fashionable whilst maintaining a confident aesthetic.</span></p>
```

When I view the post within Gutenberg it shows as a "classic editor" block but there is no space (no paragraphs), just single line breaks.

If you need more info or I can help debug further in any way please just let me know.

If you know of a workaround I can use in the meantime that would also be great :)

**Comment by Blogthetech** [comment]
_Some fix everyone_

Permanently trash the imported posts without paragraphs.

Install and activate classic editor (No setting required after activation)

Re-import the posts again and you won't experience any paragraph loss.

This is what I did after experiencing this issue using the WordPress export/import.

Good Luck.
