### ISSUE TITLE
Tags suggestions: consider to don't save new tags when tabbing away from the input field

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1304]
Currently, new tags get added when tabbing away from the Tags field in the sidebar. This is not necessarily what users want, as tabbing away from a form field is the standard way to navigate content for users that use the keyboard.

To reproduce:
- focus the Tags input field in the sidebar
- type some non-existing tag name
- press the Tab key to navigate away from the input field
- at this point, the new tag gets saved
- check in the Posts > Tags admin screen the new tag is listed

The current behavior in core is different: tags and new tags get added just when explicitly saving (there's a button for this reason). When tabbing away, the only things that happen is `wp.a11y.speak` sends an audible message to the aria-live regions.

**Comment by afercia** [comment]
Worth noting, when using a keyboard there's the concrete risk to create tons of new, unwanted, tags.

**Comment by youknowriad** [comment]
We're already aware of this, some context here https://github.com/WordPress/gutenberg/pull/970#discussion_r119617545

The current Rest API is not very handy for this use-case.

**Comment by afercia** [comment]
Relevant core ticket: https://core.trac.wordpress.org/ticket/42234
worth noting that change broke the normal interaction when pressing Enter and a better solution should be investigated.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518716089000412)._

**Comment by karmatosed** [comment]
I think design feedback for this is that whatever core does on this we should for tags. It's at least a solid starting point to have same behaviour.

**Comment by danielbachhuber** [comment]
@afercia Was this fixed by #6622 and can be closed?

**Comment by afercia** [comment]
@danielbachhuber yes.
