### ISSUE TITLE
Tests: Enable a disabled fragile link e2e test

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#13044]
In #13043 `allows autocomplete suggestions to be selected with the mouse` test from links spec was disabled because it was failing too often on Travis. 

When it fails, this is what is printed on the console:

> FAIL test/e2e/specs/links.test.js (57.317s)
>   ● Links › allows autocomplete suggestions to be selected with the mouse
>     expect(received).not.toBeNull()
>     Received: null
>       300 | 		// Expect that clicking on the autocomplete suggestion doesn't dismiss the link popover.
>       301 | 		await firstSuggestion.click();
>     > 302 | 		expect( await page.$( '.editor-url-popover' ) ).not.toBeNull();
>           | 		                                                    ^
>       303 | 
>       304 | 		// Expect the url input value to have been updated with the post url.
>       305 | 		const inputValue = await page.evaluate( () => document.querySelector( '.editor-url-input input[aria-label="URL"]' ).value );
>       at Object.toBeNull (test/e2e/specs/links.test.js:302:55)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:288:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
>       at asyncGeneratorStep (test/e2e/specs/links.test.js:15:103)
>       at _next (test/e2e/specs/links.test.js:17:194)

In my tests, it didn't regress. It would be nice to discover why this test doesn't work as intended with Puppeteer.

/cc @talldan

**Comment by talldan** [comment]
I had a look at it last week, but haven't been able to understand what's causing it. As you say, the feature seems to be working ok, and the test logic looks ok to me. 

I'll take a look again next week.

**Comment by talldan** [comment]
I've been testing on CI since I haven't been able reproduce locally, and I've only managed to make the e2e tests with plugins fail so far, so it could be that a plugin is causing an actual issue. Next step, try to determine if that's actually the case and which plugin it might be.

**Comment by gziolo** [comment]
It was disabled again in #15059.
