### ISSUE TITLE
Wrong caption alignment in core/embed

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#13050]
<img src="https://i.imgur.com/Jj3j6dT.jpg">

By default caption is centered for `core/embed`. It should be styled differently by default?

**Comment by manake** [comment]
Same with `core/image`.

**Comment by paaljoachim** [comment]
A possible regression of center embed alignment in Gutenberg version 4.8?

Selecting to align embed center does not center on the frontend:

![screen shot 2019-01-22 at 12 00 58](https://user-images.githubusercontent.com/5323259/51531404-a4e7be00-1e3d-11e9-8fb4-c6e94ec6a844.png)

Only the caption is center aligned.

--- Temporary solution that worked for my site. --

/* Center align embed. */
.wp-block-embed {
   width: 50%;
    margin: 0 auto; 
}

---

Testing
LEFT alignment on the frontend:

![screen shot 2019-01-22 at 12 06 50](https://user-images.githubusercontent.com/5323259/51531616-40792e80-1e3e-11e9-9bb0-950aa0abf35d.png)

---

Testing
RIGHT alignment on the frontend:

![screen shot 2019-01-22 at 12 08 05](https://user-images.githubusercontent.com/5323259/51531676-69012880-1e3e-11e9-8a1f-3eed5a40583c.png)

**Comment by paaljoachim** [comment]
Issue has been fixed for embed of video (not for images).
An update to Gutenberg version 4.9. It has improved a lot:

![screen shot 2019-02-06 at 00 47 08](https://user-images.githubusercontent.com/5323259/52311941-0e70dc00-29a9-11e9-9a87-a84ae9743adf.png)

![screen shot 2019-02-06 at 00 47 59](https://user-images.githubusercontent.com/5323259/52311959-192b7100-29a9-11e9-979e-4aa33c98db4c.png)

![screen shot 2019-02-06 at 00 48 33](https://user-images.githubusercontent.com/5323259/52311963-1cbef800-29a9-11e9-956c-a8ba7e0c2426.png)
