### ISSUE TITLE
Adding SVG image as Featured Image

### ISSUE THREAD

**Issue by hogash** [WordPress/gutenberg#13057]
When adding an SVG image as Featured image, the image is displayed over the options.

Screenshot: https://d.pr/i/BpX0cA .

Because getting the width/height of an svg is not easy with JS, i would propose a simple solution, move the empty `div` (that would hold the padding bottom ratio), after the image tag eg: https://d.pr/i/hKMQnR . 

And add the following CSS which would only target svg based images:
```
.components-responsive-wrapper img[src$=".svg"] + div {
  padding-bottom: 100%;
}
```

**Comment by designsimply** [comment]
This was reported in #5477 and has some code review already in #5577 that could be picked up again. Can you have a look there to see if you have anything to add to the code review?
