### ISSUE TITLE
Quote block citation field traps cursor

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#13054]
When adding a quote you can't escape the citation section, hitting return to create a new block just adds newlines inside the citation field, you need to step in with the mouse cursor to click a new block underneath it.

I also attempted to navigate out of it by hitting ESC to cancel any selection (that felt like a natural way to leave a boundary and return to normal behavior), and using the keyboard arrow keys to try and leave the field, which was also not an option.

The citation field likely does not need newline support, and if it does supporting shirt+return for a line break makes more sense than to hijack the return key altogether in this section.

** Versions **
Windows 10
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
WordPress 5.0.2

**Comment by Clorith** [comment]
Oh wow... tab key starts some odd interaction scenarios.

When I hit tab to leave the field, it does leave the field. I can then tab backwards into it (takes a double tab as you have to go back an extra step to pass the new block button that comes up) arrow keys now let you leave the citation field, but only after tabbing out of the field once first.

**Comment by afercia** [comment]
> hitting return to create a new block just adds newlines inside the citation field

Just to note there are other blocks where the "press Enter > create new block" paradigm doesn't work. To me, this contributes to a confusing user experience. Users can't understand why it works on some blocks and it doesn't on other blocks.

If Gutenberg considers this paradigm a good user experiences (I'm not saying it necessarily is), then I'd tend to think it should work consistently across all the blocks with an editable area.

**Comment by mtias** [comment]
This is addressed in the new quote with nested blocks. We are also considering adding a button to add the quote source instead of the placeholder.
