### ISSUE TITLE
New Post: Loads Blank Page after updating wordpress to 5.0.2

### ISSUE THREAD

**Issue by ronknight** [WordPress/gutenberg#13051]
After updating Wordpress to 5.0.2. New post links renders blank page when clicked.

![capture](https://user-images.githubusercontent.com/7566286/50304130-ff0ef100-0443-11e9-8d6f-df31fe95fefb.PNG)

More technical details below:

Wordpress Theme used: Twenty Nineteen.
Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Wordpress Version: 5.0.2 Multisite
New post link: https://pinoyitsolution.com/wp-admin/post-new.php#/

**Comment by ronknight** [comment]
Windows version: Windows 10

WordPress Environment
--
Home URL: | [?] | http://pinoyitsolution.com
Site URL: | [?] | https://pinoyitsolution.com
WP Content Path: | [?] | /home/pinoyits/public_html/wp-content
WP Path: | [?] | /home/pinoyits/public_html/
WP Version: | [?] | 5.0.2
WP Multisite: | [?] |  
PHP Memory Limit: | [?] | 256 MB
WP Debug Mode: | [?] | –
Language: | [?] | en_US

Server Environment
--
Server Info: | [?] | Apache
PHP Version: | [?] | 5.6.39. WordPress recommendation: 7.2 
PHP Post Max Size: | [?] | 200 MB
PHP Time Limit: | [?] | 180
PHP Max Input Vars: | [?] | 1700
SUHOSIN Installed: | [?] | –
ZipArchive: | [?] |  
MySQL Version: | [?] | 5.6.41
Max Upload Size: | [?] | 1 MB
DOMDocument: | [?] |  
WP Remote Get: | [?] |  
WP Remote Post: | [?] |  
GD Library: | [?] | bundled (2.1.0 compatible)

**Comment by scottbuscemi** [comment]
Any other plugins installed?

**Comment by designsimply** [comment]
I tested with a brand new Multisite install using WordPress 5.0.2 and no active plugins and posts loaded normally in my test.

Please try testing with all plugins temporarily deactivated if you haven't already.

It would be helpful if you could include any errors you see in the console panel in your browser's web developer tools if you can see any problems showing up there.

**Comment by ronknight** [comment]
Here are the errors I get from the console.
```
Uncaught TypeError: Cannot read property 'then' of undefined
    at post-new.php:6190
product-category-block.js?ver=1.2.0:69 wp.date.getSettings is deprecated and will be removed from Gutenberg in 4.4. Please use wp.date.__experimentalGetSettings instead. Note: Unstable APIs are strongly discouraged to be used, and are subject to removal without notice.
Na.version @ product-category-block.js?ver=1.2.0:69
index.js?ver=1545157696:2 The block "yoast/how-to-block" must have a registered category.
q @ index.js?ver=1545157696:2
index.js?ver=1545157696:2 The block "yoast/faq-block" must have a registered category.
q @ index.js?ver=1545157696:2
fusion-builder.js?ver=1.7.1:1 Uncaught TypeError: Cannot read property 'replace' of undefined
    at fusionBuilderGetContent (fusion-builder.js?ver=1.7.1:1)
    at Object.captureEditor (fusion-builder.js?ver=1.7.1:1)
    at n.initialize (fusion-builder.js?ver=1.7.1:1)
    at n.e.View (backbone.min.js:1)
    at n.constructor (wp-backbone.min.js:1)
    at new n (backbone.min.js:1)
    at HTMLDocument.<anonymous> (fusion-builder.js?ver=1.7.1:1)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)

```
I apologize, I forgot to disable all the plugins. It was resolved after I disabled everything.

**Comment by norbertoaquinos** [comment]
there's any solution for this problem yet? .. please help!

**Comment by ronknight** [comment]
>           there's any solution for this problem yet? .. please help!

I got mine working by disabling all plugins. This might be due to conflicting plugins. Or you can try selecting the classic editor as default editor on settings.
