### ISSUE TITLE
Disable return key

### ISSUE THREAD

**Issue by crstnio** [WordPress/gutenberg#13065]
I have disabled all core blocks by using the `allowed_block_types` filter.

But pressing return inserts a paragraph even if it's disabled.
Is there a filter/action to disable this?

Reason: I plan to create custom ACF blocks (with the upcoming ACF 5.8) that will _render_ only necessary information for a static React app through the REST API. And I have no use for the core blocks.

**Comment by youknowriad** [comment]
Are you hitting "Enter" inside ACF blocks and it's creating paragraphs? In which block you're having the issue?

**Comment by cardiv** [comment]
I do not hit enter inside any block. This is default Gutenberg behavior. Hit enter and the "Type / to ..." appears. But typing normal text inserts a paragraph, even if it is disabled.

**Comment by youknowriad** [comment]
So you're trying to disable the "paragraph" block which is the default block and disabling the default block is not possible at the moment. What behavior do you want to see when loading a post with no default block?

**Comment by cardiv** [comment]
A possible solution could be to prevent typing text that does not start with a slash, if the paragraph/default block is disabled. I would not remove this slash-search. It is quite intuitive.

For now, I disabled the Gutenberg editor unless more documentation and ACF 5.8 (for easy custom blocks) is available.

**Comment by youknowriad** [comment]
I think this was fixed recently. Right @jorgefilipecosta ?

**Comment by jorgefilipecosta** [comment]
Hi as @youknowriad referred now if a block is not allowed pressing enter should not insert it, so this problem should be fixed on the last version of Gutenberg.
If that's not the case feel free to reopen the issue.
Thank you for reporting this problem.
