### ISSUE TITLE
Is there are way to run a custom setup callback on block?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#13069]
```
class Something extends wp.element.Component {
	constructor(props) {
		super(props);
	}

	componentDidMount() {
		// I would like to run $('.test').isotope() here.
		// Is it possible?
	}

	componentWillUnmount() { }

	render() {

		// Note that running the callback would modify this DIV and append
		// more elements inside.
		return el('div', { className: 'test' }, 'Test');
	}
}
```

The handbook doesn't include this information but I think it should as without custom callbacks the usability is limited.

Is there a way to initialize for example `isotope()` like that?

**Comment by swissspidy** [comment]
Sounds like more of a general React question that might be answered by articles like https://stackoverflow.com/questions/25135261/react-js-and-isotope-js.

**Comment by manake** [comment]
Ok, I'll close this and see if that will work.

So far this is over-complicated to use some new API like `ReactDOM.findDOMNode(this)` but maybe it'll work.
