### ISSUE TITLE
Restricted Content Issue in 5.0.2

### ISSUE THREAD

**Issue by KendallRogersD1** [WordPress/gutenberg#13066]
Hey guys,
When I try to scroll down to the restricted content area, usually i have options for "premium monthly subscription" and "premium annual subscription" and instead, I get this weird situation. Thoughts?
[]
<img width="293" alt="screen shot 2018-12-21 at 12 22 20 pm" src="https://user-images.githubusercontent.com/42068351/50359933-0dccd500-0524-11e9-8398-9b1f962e5b99.png">
(url)

**Comment by swissspidy** [comment]
Have you contacted the developers of Restrict Content Pro? Sounds like a bug in that plugin.

**Comment by youknowriad** [comment]
Thanks for the report, I suggest reaching out to the plugin authors as this seems like a styling issue on their end.
