### ISSUE TITLE
Block names with underscore

### ISSUE THREAD

**Issue by janeschindler** [WordPress/gutenberg#13074]
**Is your feature request related to a problem? Please describe.**
I've twice accidentally tried to make block names with underscores (like "object_nav"). This causes the entire block not to be recognized by templates.

**Describe the solution you'd like**
Either block names should be able to have underscores in them, or it should be documented in register block and template functions that this isn't allowed. I can imagine it's obvious to some people, but apparently not to me.

**Describe alternatives you've considered**
I just did trial and error until i managed to try a new name. That took several hours.

**Comment by swissspidy** [comment]
Can confirm this, although it's quite easy to find out when using `register_block_type()` in PHP.

The regex used there is `/^[a-z0-9-]+\/[a-z0-9-]+$/`. So if you register a block type with a name like `foo/bar_baz` you'll get a `_doing_it_wrong` warning:

```
Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type
```

**Comment by janeschindler** [comment]
That would have been helpful – I just searched my php logs and never got anything like that. Instead I got a javascript error (I was including this block via a JS template) that just said the block was undefined and had no attributes.

**Comment by youknowriad** [comment]
Closing as it has a reply, I just tried in JS as well and the message is also clear.

**Comment by juanRabaa** [comment]
The message isn't clear at all because:
1- It doesn't tells you which block is causing the problem (could print the name that's failing)
2- The message is implying that the name doesn't have a `prefix/`, but it does.

I had to go into the `WP_Block_Type_Registry::register` and print the failed block name, and then guess that it was the underscore.

**Comment by swissspidy** [comment]
Since `WP_Block_Type_Registry` resides in core, feel free to open a ticket on core trac with your suggestions

**Comment by skorasaurus** [comment]
I created a trac ticket to address this - https://core.trac.wordpress.org/ticket/56627
