### ISSUE TITLE
Google Trends embed graphs (Javascript) not working in WordPress 5.0.2

### ISSUE THREAD

**Issue by freshmaker1033** [WordPress/gutenberg#13070]
Hi,

I recently updated to WordPress 5.0.2 and now Google Trends embed graphs are not showing up in any of my published Posts. I have been embedding Google Trends in all my Posts and didn't have an issue until the update. Google Trends embed uses Javascript code.

Essentially, when I create a new Post, the embed script appears in the Code Editor, but nothing appears when I publish. It's a blank space. Obviously the new version of WordPress is not processing Javascript correctly in line with pre-Gutenberg versions.

Is there a way to fix this without going into every individual Post? I have thousands of Posts and it would take too long to manually fix everything. Thank you.

**Comment by swissspidy** [comment]
Can you please share such an embed code here?

Are you using the code block to embed it?

**Comment by freshmaker1033** [comment]
Thanks for the quick reply. Below is an example of the embed code and its URL. I would assume it's a code block

  <script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1671_RC04/embed_loader.js"></script>
  <script type="text/javascript">
    trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"hong kong","geo":"HK","time":"today 12-m"}],"category":0,"property":""}, {"exploreQuery":"geo=HK&q=hong%20kong&date=today 12-m","guestPath":"https://trends.google.com:443/trends/embed/"});
  </script>

Here's the URL: https://trends.google.com/trends/explore?geo=HK&q=hong%20kong

**Comment by freshmaker1033** [comment]
Yes, the code can be added to a custom block but that's not the issue. WordPress 5.0.2 is not recognizing the embed code in previous Posts. 

The issue is that I have already been using and adding the embed code in pre-Gutenberg versions of Wordpress (3.0, 4.0). Now the graphs associated with this code have disappeared with version 5.0 even though the embed code is still present in all my published Posts (which number more than 1,000s). 

This is a serious issue since it renders all embed features worthless. Is there a way for the new version of Wordpress to recognize embed code that worked fine in previous versions? Thank you.

**Comment by designsimply** [comment]
I tested and was unable to reproduce the problem using the following steps:

1. Install WordPress 4.9.8.
1. Go to Posts > Add New and add a title.
1. Go to https://trends.google.com/trends/ and enter a search term.
1. Click the embed option and copy the HTML provided.
1. Paste the HTML into the Text tab of the post body.
1. Publish the post.
1. Upgrade to WordPress 5.0.2. 
1. Check the post and note whether or not the embedded Google Trends graphs work as expected.

<strong>Result:</strong> all Google Trends graphs trends I tested worked normally after adding them using WordPress 4.9.8 and then upgrading to 5.0.2.

Tested with WordPress 4.9.8 upgraded to WordPress 5.0.2 with no active plugins and the Twenty Nineteen 1.1 theme.

Your testing steps may be a bit different compared to mine. Could you check them and add any steps that might be missing? Also, please note your theme and theme version for reference. If you able to temporarily switch to the default theme to see if that resolves the problem, please do so. If possible, please check for errors in the console in your browser's web developer tools and either provide a screenshot or a copy of any errors showing for a post that displays this problem on the front end (alternately, you could provide a link to a post where I can see the problem in action and I could take a closer look).

**Comment by swissspidy** [comment]
@designsimply Perhaps an issue with block conversion?

**Comment by designsimply** [comment]
> Perhaps an issue with block conversion?

I don't think block conversion is expected to work for all custom code snippets, this one being an example.

I am more concerned with the report from the user that Google Trends graphs added pre-Gutenberg disappeared for 1,000s of their previously published posts.

**Comment by designsimply** [comment]
@freshmaker1033 just dropping by to note that I've tested and am wanting to sync back up to check in with you to see how it's going.

**Comment by youknowriad** [comment]
Closing as stale, let's reopen if there's are reproducible steps/actionable items.

**Comment by spektacle** [comment]
I'm having this issue with WordPress 5.2.2

**Comment by TNHSAesop** [comment]
I had this issue too and I noticed that when you copy/paste the embed code there is an ember loader is initialized with every copy of the embed code. This initializer only needs to be called once, so removing the initializer from subsequent embeds fixed the issue for me.  

![image](https://user-images.githubusercontent.com/43328274/180314918-4d3492bf-ed16-4515-9f98-060329f197c4.png)


You can see this in action here:
https://tortoiseandharesoftware.com/blog/current-state-of-demand-for-it-services/
