### ISSUE TITLE
Write new text in multiple formats

### ISSUE THREAD

**Issue by Tug** [WordPress/gutenberg#13087]
**Describe the bug**
It's currently not possible to write bold and italic text (or any other combination).

**To Reproduce**
1. Go to the editor in visual mode
2. Create an empty paragraph block
3. **See the block toolbar is not visible yet (1)**
4. Write something so the block toolbar becomes visible
3. Select `bold` and `italic` and start typing again
4. Notice **you're typic in italic, not bold italic (2)**
5. Notice **nor bold nor italic is marked as active (3)** while you write in italic
6. Write a word in bold at the end of your text then place your cursor at the beginning of the bold text.
7. Start typing in the current format, notice **bold is selected even though you're typing without formatting (4)**
8. **Click on bold to start typing in bold and notice the formatting on the bold word you added is removed (5)**

**Expected behavior**
You should be typing in bold italic and both format should be selected while you type.
Imo, we should probably use the previous character's format to determine the active format.

**Screenshots**
![image](https://user-images.githubusercontent.com/230230/50400291-d9f0ea00-0785-11e9-947a-52a510ed127e.png)

**Desktop:**
 - OS: macos
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
- See the mobile effort to address those problems: https://github.com/WordPress/gutenberg/pull/12249
cc @hypest @gziolo

**Comment by gziolo** [comment]
It's a known issue. It duplicates #13087. Does this issue is also transferred to the mobile app? It would be nice to identify whether it is related to TinyMCE or the way we manage the internal representation of rich text component.

Let's discuss in #13087. I'm closing this one.

**Comment by koke** [comment]
I assume you meant #11091?

**Comment by gziolo** [comment]
Yes, I updated my comment.
