### ISSUE TITLE
Pass props to blocks via allowedBlocks

### ISSUE THREAD

**Issue by bologer** [WordPress/gutenberg#13097]
I've checked these issues:  #9032, #9032 but did not find any real usage of what I had on my mind.

I would like to achieve the following with `InnerBlocks` (or maybe someone can suggest any better solution):
 
I have a single full with layout where I should be able to choose only two type of blocks. Now I can do it with `allowedBlocks` prop, which is fine.

Let's imagine I have chosen these two blocks only: `['core/freeform', 'core/html']` this is what I get so far (according to [docs](https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks#allowedblocks)): 

```js
const ALLOWED_BLOCKS = [ 'core/freeform', 'core/html' ];
...
<InnerBlocks
    allowedBlocks={ ALLOWED_BLOCKS }
/>
```

![image](https://user-images.githubusercontent.com/9879933/50424648-d766c100-0867-11e9-86dc-a03acd4f510b.png)

After I've chose e.g. `core/html` I would like to get its content. I've tried to find out any possible way to pass props via `allowedBlocks` but it seems that it is not possible, because it only accepts array of string, meaning only block names. 

I would like to pass callback function via something like `onChange`, so I can record content of the block in `attributes` inside `edit()`. 

Is there any possible way to achieve this so far?

I expected something like the following: 

```js 
const ALLOWED_BLOCKS = [
    ['core/freeform', {placeholder: 'Some placeholder', onChange: onContentChange}], 
    'core/html'
];
```  

but the first block is just being ignored as it only accepts string value.

**Comment by youknowriad** [comment]
You can use a `template` (see the columns block for instance), to bootstrap with a given set of attributes, and if you want to get changes to attributes of the inner blocks, you can use the `clientId` prop you receive in the `edit` function of your parent block and find the children of this block using the selectors and `withSelect` (See the docs of the data module).

**Comment by bologer** [comment]
@youknowriad thank you, but template would prerender blocks. I would like to allow user to choose blocks from the allowed list and then pass to such block props.

Is there any way?

**Comment by youknowriad** [comment]
Is the allowed blocks not enough for this?

**Comment by youknowriad** [comment]
In this example I'm retrieving the children of the current blocks in its edit function, and the `edit` function will rerender each time their value changes. I hope this helps. (I haven't tried it, I might have a typo or something)

```js
edit: wp.data.withSelect(( select, { clientId }) => {
  childrenBlocks: select( 'core/editor' ).getBlock( clientId ).innerBlocks,
})( { childrenBlocks } => {
 // Do something with the children attributes
} )
```

**Comment by bologer** [comment]
@youknowriad wow, this is nice, thanks for the snippet.
