### ISSUE TITLE
Not possible to delete an image

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#131]
I tried deleting an image by pressing delete/backspace, but this doesn't work.

**Comment by Lewiscowles1986** [comment]
Is this part of fulfilling #71 (Epic)

**Comment by mapk** [comment]
Seems you got this working, @iseulde on the /tinymce-single prototype. Should we close it?

**Comment by iseulde** [comment]
Yep, this has always worked there, does not work in the UI one though.

**Comment by jasmussen** [comment]
Closing for now.
