### ISSUE TITLE
One should be able to Change Block Type from file, embed etc blocks to other blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13108]
One can change block types between blocks by clicking the change block type icon.
Like so:

<img width="511" alt="screen shot 2018-12-27 at 13 08 04" src="https://user-images.githubusercontent.com/5323259/50479762-7a3e4d00-09d8-11e9-9d36-5684e05cd9c6.png">

One can not change the block type after having selected the File Block:
<img width="665" alt="screen shot 2018-12-27 at 13 09 51" src="https://user-images.githubusercontent.com/5323259/50479828-ca1d1400-09d8-11e9-9da6-98476551baa2.png">

One can not change the block type after having selected an Embed block:
<img width="676" alt="screen shot 2018-12-27 at 13 13 35" src="https://user-images.githubusercontent.com/5323259/50479915-4f082d80-09d9-11e9-93b4-8524ea4cc543.png">

There are likely also other blocks one can not use the change block type icon to switch to another block. There should be a bigger leniency to easily switch a block to another kind of block. 

Similar:
https://github.com/WordPress/gutenberg/issues/6363

**Comment by paaljoachim** [comment]
Lets say I uploaded an audio or video file using the File block. I should be able to switch from File block to a video or audio block.

Another example. Adding the separator. I should be able to switch to divider instead.

**Comment by mcsf** [comment]
> Lets say I uploaded an audio or video file using the File block. I should be able to switch from File block to a video or audio block.

This is possible already. I just tested by uploading an MP3 file into a new Audio block, then converting to File, then back to Audio.

> Another example. Adding the separator. I should be able to switch to divider instead.
> 
> There are likely also other examples.

These would be separate issues, which may or may no longer apply.

> One can not change the block type after having selected an Embed block:
> 
> There are likely also other blocks one can not use the change block type icon to switch to another block. There should be a bigger leniency to easily switch a block to another kind of block.

Trying to intelligently automate conversions between embeds and regular blocks is something that I'd recommend against, as it seems like investing in something too brittle. 

Thanks for the report. Closing this issue.

**Comment by paaljoachim** [comment]
Thanks for checking in with the issue Miguel! @mcsf
