### ISSUE TITLE
Please provide better ways to feature content from different post types + pages

### ISSUE THREAD

**Issue by nmschaller** [WordPress/gutenberg#13109]
Hi Gutenberg developers,

Thanks a lot for providing a solution to create pages in Wordpress core without using a pagebuilder; I appreciate that. There are some things I hope I'll be able to do with Gutenberg in the future. Here's one example.

On the IDEO website, they feature content from all parts of their website, nicely formatted in a unified way and indicating the source of the content, for example "course" or "blog". 
https://www.ideo.com/eu
Then they make some content stand out:
Homepage with a "big question" standing out: https://www.ideo.com/eu
Leading to a page featuring all content and services around that big question: https://www.ideo.com/question/how-can-design-help-organizations-be-more-creatively-competitive

With Twenty Nineteen and Gutenberg, I was hoping to be able to create pages with featured content from different sources like Wordpress posts + pages, Jetpack portfolio, WooCommerce products and LearnDash courses and display them on the homepage in a unified way. But they all look different. I'd wish for one block that is able to pull content from different custom post types and display the featured image, the title and text up until "more" in a unified way, plus indicating the source.

The only unified way to display content that I can think of right now would be the o-embed function.

Thanks a lot for considering a new feature.

Nicole

**Comment by swissspidy** [comment]
> I was hoping to be able to create pages with featured content from different sources like Wordpress posts + pages, Jetpack portfolio, WooCommerce products and LearnDash courses and display them on the homepage in a unified way.

What would such a unified be?

Some post types don't even have titles or text content. Some post types are not even exposed via the REST API. How would WordPress know what kind of data is associated with a Jetpack portfolio item or a WooCommerce product? The plugins would need to tell the system this in some way.

It's certainly possible to create your own "Single Post" block to display a post with a type of your choice, but the presentation logic would be up to you to implement.

In the meantime, oEmbed isn't a bad choice. Many plugins already modify the embeds so that their content looks nice in them.

**Comment by nmschaller** [comment]
Hi Pascal,

As a Wordpress user, I don't know the technical specifics under the hood.

What I see is websites like the above-mentioned IDEO that feature content from different sources in a way that is formatted the same, no matter where it is coming from.

And there are some theme and plugin providers who think in the same direction:

Organic themes has the Block theme with "widgets" that need to be edited in the customizer, but the result looks nice. See "content slideshow widget" for an example.
https://organicthemes.com/demo/?demo=block-theme

And here's a plugin that features content from posts and pages:
https://wordpress.org/plugins/content-views-query-and-display-post-page/

Wouldn't it be cool to have a "featured content" Gutenberg block in the core that offers this?

As for title and content of custom post types, all plugins I am working have it. And plugins like Yoast SEO don't seem to have a problem detecting them.

Nicole

**Comment by Vixxd** [comment]
> > I was hoping to be able to create pages with featured content from different sources like Wordpress posts + pages, Jetpack portfolio, WooCommerce products and LearnDash courses and display them on the homepage in a unified way.
> 
> What would such a unified be?
> 
> Some post types don't even have titles or text content. Some post types are not even exposed via the REST API. How would WordPress know what kind of data is associated with a Jetpack portfolio item or a WooCommerce product? The plugins would need to tell the system this in some way.

There already was a shortcode for Jetpack Portfolio types - https://en.support.wordpress.com/portfolios/portfolio-shortcode/

I previously shortcodes ultimate '[custom gallery](https://getshortcodes.com/shortcodes/custom_gallery/)' shortcodes to show a row of projects, and then a row of blog posts, just by specifying the type (post or portfolio). 

I'm finding it really hard to find something Gutenberg compatible that does the same thing, and that the Wordpress Gutenberg editor won't allow me to do this as I would for posts.

**Comment by aduth** [comment]
>But they all look different.

Can you clarify what specific arrangement of content you produced where you're seeing it as appearing disjointed?

>I'd wish for one block that is able to pull content from different custom pot types and display the featured image, the title and text up until "more" in a unified way, plus indicating the source.

Is the idea here a new block, which behaves similar to the "Latest Posts" block, but allows the user to manage the specific content (pages, etc) shown in the block, and includes more customization options for how it be shown?

Certainly this is something which a plugin like Jetpack (or another plugin which provides its own custom blocks) could provide, but I could see some value in it being offered by default as well.

**Comment by draganescu** [comment]
> > I'd wish for one block that is able to pull content from different custom pot types and display the featured image, the title and text up until "more" in a unified way, plus indicating the source.

@aduth this very close to the `Query` block ideas that spawned along with the advancing of full site editing isn't it?

**Comment by aduth** [comment]
> > > I'd wish for one block that is able to pull content from different custom pot types and display the featured image, the title and text up until "more" in a unified way, plus indicating the source.
> 
> @aduth this very close to the `Query` block ideas that spawned along with the advancing of full site editing isn't it?

Hi @draganescu , I'm not personally very familiar with the work going on with Query block ideas or if it relates. Am I correct that this is in reference to ideas being explored by the developers of the Newspack plugin? https://github.com/Automattic/newspack-blocks/pull/176 @georgeh would likely know better than I about how this sort of approach could benefit the core implementation or serve the purposes of the original request.

**Comment by mtias** [comment]
The new QueryLoop block allows displaying any post type from the site in various ways and should cover this use case!
