### ISSUE TITLE
Backspace is not working with Rich Text.

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#13100]
Hello,

Backspace does not delete entire word. 

Here is example- https://youtu.be/ZDSO2la12E8

After delete the entire word onchange event also not working.

Here is my code for Prefix - https://goo.gl/kRvYwK
```
<RichText
	                tagName="span"
	                value={ attributes.prefixTitle }
	                placeholder={ __( "Write a Prefix" ) }
	                className='uagb-ifb-title-prefix'
	                multiline={ false }
	                onChange={ ( value ) => {	 
	                		console.log('here')               		
	                		setAttributes( { prefixTitle: value } ) 
	                		console.log(value)
	                	}	
	                }            	
	                onMerge = { props.mergeBlocks }
	                unstableOnSplit = {
						props.insertBlocksAfter ?
							( before, after, ...blocks ) => {
								setAttributes( { content: before } )
								props.insertBlocksAfter( [
									...blocks,
									createBlock( "core/paragraph", { content: after } ),
								] )
							} :
							undefined
					}
					onRemove={ () => props.onReplace( [] ) }
	            />
```

![2018-12-26_16-02-50](https://user-images.githubusercontent.com/1119271/50796049-8609f900-128d-11e9-8f26-a026e61c3410.png)

Can you please let me know whats wrong with this?

**Comment by youknowriad** [comment]
Because of a TinyMCE limitation, RichText can't be used with inline elements, change "span" to "div" and let me know if it works better.

**Comment by designsimply** [comment]
@prajaktagadhave I am closing this issue because a solution was provided. If you find the solution does not work for you, please re-open this issue and mention what you have tested and any new information which may be relevant to helping you reach your goal. Thank you!

**Comment by prajaktagadhave** [comment]
Yes, This issue is resolved by replacing <span> with <div> tag. Thank you for solution.
