### ISSUE TITLE
Menu block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13111]
I have begun thinking of how a possible Menu Block could look like.

![menu-gutenberg-suggestion](https://user-images.githubusercontent.com/5323259/50481706-47e61d00-09e3-11e9-8aae-71a5d722e457.jpg)

Toolbar:
I added alignment options to align menu left, center or right.
Then icons for adding pages, posts, categories (taxonomies) and custom links.
Click the icons to open a modul/dialog box then click the menu items one wants to add. Rearrange them as boxes (similar to the existing solution) inside the blocks, by visually dragging the menu links to order them into the correct parent and child menu item relationship.

I am trying to keep most of the interaction directly inside the block layout area. As it shows right away what it looks like. It is the area with the biggest space available. The sidebar settings can easily be overlooked by many.

https://make.wordpress.org/design/2018/12/18/exploring-a-nav-block-at-wordcamp-us/

For administrating where on which page etc a specific menu is to be seen then a conditional block would help. https://github.com/WordPress/gutenberg/issues/6866
As one would then just place the menu block inside the conditional block (perhaps even add conditional logic to the container block.)

**Comment by youknowriad** [comment]
Would you mind adding your thoughts here #1466 to avoid duplicates? Thanks.

**Comment by paaljoachim** [comment]
Thanks Riad!
