### ISSUE TITLE
The sharing module (JetPack) is not updated

### ISSUE THREAD

**Issue by almendron** [WordPress/gutenberg#13112]
The sharing module (JetPack) is not updated.

1) “_wpas_mess” is a function of JetPack (modules/publicize/publicize.php)
Add a record in the postmeta table where “meta_key” = “_wpas_mess”. Therefore, we can use:
`<?php` update_post_meta( $post_id, $meta_key, $meta_value, $prev_value ); `?>`

2) WordPress 5.0.2 and Classic Editor:

`<?php` update_post_meta( $post_id, '_wpas_mess', $meta_value, $prev_value ); `?>`

It works perfectly

3) The same function with Gutenberg Editor: It does not work.

The postmeta table is updated correctly: [see image 1](https://almendron.com/compartir/gutenberg/compartir-1.png).

However, the values do not appear in the editor: [see image 2](https://almendron.com/compartir/gutenberg/compartir-2.png). The words “Periodismo” y “España” are missing.

**Comment by youknowriad** [comment]
I know JetPack did work on Publicize compatibility with WordPress 5.0. It might work differently though, I suggest you ask in the JetPack Github/forums.

Thanks.
