### ISSUE TITLE
Plugin functions vs core functions

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#13114]
There are some PHP functions in this plugin, e.g. [gutenberg_parse_blocks()](https://github.com/WordPress/gutenberg/blob/7ea50218a1de9cd00aceb0a58b4c879719f26d9b/lib/blocks.php#L60) that have been replaced in core without the `gutenberg_` prefix. For plugins using these functions directly, should the `gutenberg_` variant be used first if it exists? Asked another way, as development on the block editor continues in this plugin, might these functions get updated in the Gutenberg plugin, and therefore, developers using these functions externally should prefer the `gutenberg_` version if it exists? e.g.

```php
if ( function_exists( 'gutenberg_parse_blocks' ) ) {
	$blocks = gutenberg_parse_blocks( $content ); // Gutenberg plugin.
} elseif ( function_exists( 'parse_blocks' ) ) {
	$blocks = parse_blocks( $content ); // WordPress 5.0+.
}
```

Or, might the core variant get updated without that change trickling down to this plugin?

**Comment by youknowriad** [comment]
In the upcoming versions of the plugin, we will drop support for WP versions prior to 5.0 which means these functions will be removed from the plugin.

If you want to support old versions of the plugin, you might still want to check for existence of these functions otherwise, just use the prefix-less functions.

Thanks.

**Comment by StaggerLeee** [comment]
Maybe biggest mistake so far to remove "gutenberg_" addition. It was very, very unique and would make searching on Google for snippets, solutions and tweaks lighting fast.
