### ISSUE TITLE
Best way to migrate Meta

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#13115]
I have a plugin that creates a post meta field. This field, if entered late can be missed during the post transition hooks where other actions in my code fire. Until now I've been able to access the `$_POST` global but that isn't working in the new editor.

I've therefore been looking at creating a 'Gutenberg' way of rendering my post meta input area that was previously in a meta box. A block seems an irrational way of doing it as blocks seems more purposed for content creation and this is not content.

So, Im trying a sidebar and it's working okay but for one issue. Sidebars can be 'pinned' and 'pinnable'. In order for my new sidebar to be visible it must be pinned, which means it must also be pinnable based on my analysis of the current code.

The downside here is that if I click the star and unpin my sidebar, once I leave it, there is no way to get it back.

Has this been noted until now or consider? Or am I missing an easy way to pin it without make it unpinnable?

**Comment by youknowriad** [comment]
> Has this been noted until now or consider? Or am I missing an easy way to pin it without make it unpinnable?

The idea is that plugins can be pinned by default, but we allow the user to control the UI. Imagine a user installing 10 plugins making them selves unpinnable. The editor would become unusable at this point, that's why it's always possible to unpin a plugin.

**Comment by mattyrob** [comment]
@youknowriad 

Thanks for the answer - as a follow up then, once the user has uncluttered their screen and hidden these plugins - how do they then restore them? (That was the area of greater concern for me).

**Comment by youknowriad** [comment]
@mattyrob you can register a menu item in the more menu item. (That's what Yoast do for instance). See https://github.com/WordPress/gutenberg/tree/master/packages/edit-post#pluginsidebarmoremenuitem

I hope this helps.

**Comment by mattyrob** [comment]
@youknowriad

Thanks for the link and tip. I’ll have a look at that.
