### ISSUE TITLE
Table content disappeared after reopening saved post draft

### ISSUE THREAD

**Issue by vesaraiskila** [WordPress/gutenberg#13121]
**Describe the bug**
Tables with formatted text in HTML block had all their text disappeared when reopening saved post draft

**To Reproduce**
1. Create an HTML block.

2. Insert a table as follows (which Gutenberg accepts):
<table class="wp-block-table"><tbody><tr><td><span style="font-size: 11pt;">

</span></td></tr></tbody></table>

3. Add HTML formatted text between the <span> and </span> tags, eg.:

<p><br>Maan korkeimman neuvoston päätöslauselma</p>

etc.
4. Preview, save, preview... ascertaining that all seems to be OK.
5. Save the post draft and exit.
6. Reopen the draft for editing.

**Expected behavior**
The text should exist in the tables as it was when previewed and saved.

**Observed behavior**
The content in all the tables in the post draft had cleared. Only the HTML tags, shown above, marking the tables remained.

**Screenshots**
![image](https://user-images.githubusercontent.com/46203937/50496871-e69e6800-0a3b-11e9-8de3-5426a02b50e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Opera
 - Version: 57.0.3098.106

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- Didn't find a way to check Gutenberg version

**Comment by vesaraiskila** [comment]
Steps shown visually, as they don't appear to be displayed properly above:

![image](https://user-images.githubusercontent.com/46203937/50497174-19496000-0a3e-11e9-8644-87deeddd34f8.png)

**Comment by vesaraiskila** [comment]
Just reproduced this: I restored the HTML formatted text from backups into the tables, previewed, saved, exited the post draft, reopened the post draft, and the tables' content had disappeared in the editor.

However, if one opens the Versions view, the content is there - it is just not available in the editor:

![image](https://user-images.githubusercontent.com/46203937/50497575-975b3600-0a41-11e9-9377-b8256ffbd2ab.png)

**Comment by vesaraiskila** [comment]
After I reported this, I have reproduced the bug several times. In the most disasterous case, when reopening a published post for re-editing, not only is the entire content of the table lost apart from the heading, but also all the blocks under the table are missing. (Therefore, I no longer dare to edit and re-save the published document.) Please see the screenshots below:

![disappeared_table_and_blocks](https://user-images.githubusercontent.com/46203937/53301258-355c5880-3859-11e9-8b18-643f1ceab797.jpg)

![only_heading_remained](https://user-images.githubusercontent.com/46203937/53301260-3e4d2a00-3859-11e9-9a8c-367c97178b2b.jpg)

![how_it_should_look](https://user-images.githubusercontent.com/46203937/53301261-43aa7480-3859-11e9-8d70-56d2c5b7ac66.jpg)

**Comment by vesaraiskila** [comment]
Additional information: when opening the published post, the faulty version (as described above) generated upon opening is automatically saved. Obviously, I do not want to restore that version. However, the "Restore this version" button is disabled for all the previous versions, so I cannot restore an intact version and continue editing the published post.

**Comment by vesaraiskila** [comment]
Pascal (or others), any comments on this bug and when it could be resolved? To me, it is a very serious one, as it seems to be connected to possible "show-stopper" results in terms of re-editing published posts.

**Comment by swissspidy** [comment]
Does this still happen with the latest version of the Gutenberg plugin and all other plugins disabled?

**Comment by vesaraiskila** [comment]
Hi,

Thanks for looking into this. I'll return to this a bit later after making
some checkups.

BR,
Vesa

ti 12. maalisk. 2019 klo 11.56 Pascal Birchler (notifications@github.com)
kirjoitti:

**Comment by vesaraiskila** [comment]
> Does this still happen with the latest version of the Gutenberg plugin and all other plugins disabled?

I don't know how to check Gutenberg version; I haven't installed it as a plugin. It came with an earlier WordPress update. My current WordPress version is 5.1.1.

Anyway, I reopened the published post for editing, and there was the error "This block contains unexpected or invalid content" in place of the table containg the list of sources for the article, and everything under the table was missing. I obviously exited the post without changes. Note: I didn't disable all the other plugins for this quick checkup.

**Comment by youknowriad** [comment]
The issue here is that you're using Gutenberg delimitters (blocks) inside a block that doesn't support nested blocks. (custom HTML block). I think this is not something we want to support, just remove the comments around the paragraph tag and it should work as expected.

Thanks.
