### ISSUE TITLE
Inserter: Categories get in the way when less than ~6 block types are present

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#13123]
When the available blocks are restricted via the `allowed_block_types` filter, the accordion UI of categories is not needed, and makes the user do perform unnecessary clicks in order to access the desired block.

If there are only 4 block types, for example, then it's simpler to just show all 4, rather than having to click through the categories to find them. Removing the categories would also be less cluttered, since the blocks wouldn't listed under multiple categories (e.g., `Common Blocks` and `Most Used`).

<img width="435" alt="screen shot 2018-12-27 at 5 21 44 pm" src="https://user-images.githubusercontent.com/484068/50499129-eaaa9580-09fb-11e9-9fcf-58b2b14e29b7.png">

**Comment by gchtr** [comment]
I’d like to add to this that it’s also really cluttered when **only one block** is available. In that case I would even go so far and skip the inserter popup and directly insert the block. The only available option is displayed multiple times. As a user, I’d first have to think about what I should do, even though I can only do one thing here: select the Logo block.

![](https://user-images.githubusercontent.com/2084481/57452058-29324580-7263-11e9-8a1f-85ea6ac28914.png)

**Comment by youknowriad** [comment]
I think this is mostly addressed with the redesign of the inserter. The panels have been removed. Thanks. Let's continue discussing tweaks and improvements in #21080
