### ISSUE TITLE
"editor-block-toolbar" hides the "editor-block-mover"

### ISSUE THREAD

**Issue by JQOz** [WordPress/gutenberg#13138]
Hi,

as i click on the "editor-block-mover", "editor-block-toolbar" appears over the mover icon. This is a new installed Wordpress(vers 5.02). I installed Gutenberg as plugin, the result is the same. This must be a Bug or am i doing something wrong?

Thanks
![bildschirmfoto 2018-12-30 um 12 33 06](https://user-images.githubusercontent.com/19261428/50546862-1e213600-0c2f-11e9-8334-f8ba01777b18.png)

**Comment by JQOz** [comment]
it is because of the wp version 5. On wp 4.9 or earlier, editor-block-mover stays on left and there is no issue with block-toolbar. With wp 5, they moved the block-mover to top, so toolbar hides the mover.

This is a huge Bug, why they did not see this before release the WP5. Who will fix this?

**Comment by youknowriad** [comment]
This is not the case anymore. The block movers have been redesigned recently.
