### ISSUE TITLE
Repeated images when converting Classic posts to Block format

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#13137]
**Describe the bug**
Images with captions/links are duplicated when the 'Convert to Blocks' option is selected.

**To Reproduce**
Using the classic editor create a post with an image with a link and a caption.
Edit the post in Gutenburg 
Select 'Convert to Blocks'
Observe all the images are included twice.

**Expected behavior**
Only one copy of each image should appear.

**Before Conversion**
![image](https://user-images.githubusercontent.com/5794634/50540214-581d0a00-0b53-11e9-9f5e-d036010a249f.png)

**After conversion**
![image](https://user-images.githubusercontent.com/5794634/50540226-8995d580-0b53-11e9-9c7c-09ec25bd9e98.png)

**Gutenberg 4.7.1**

**Comment by swissspidy** [comment]
We're already tracking this in #11136.
