### ISSUE TITLE
Can't have a paragraph block start with an asterisk and a space editing visually

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#13134]
If you start a paragraph with an asterisk and a space, the paragraph will be converted to an unordered list (expected behaviour). However when I undo using `ctrl` + `Z` or the undo button, the list is turned back to a paragraph but also removes the space after the asterisk. I would expect the undo to just undo the block conversion, not remove the space. This happens regardless of whether or not there is more text after the asterisk.

Thankfully, as a workaround, adding in the space by editing as HTML works and the space persists after swapping back to editing the block visually.

**Comment by youknowriad** [comment]
@iseulde I know there have been some work to make undo capable of fixing this issue. Did we merge that yet?

**Comment by talldan** [comment]
Duplicate issue here: https://github.com/WordPress/gutenberg/issues/13284

> Describe the bug
> Putting a dash+space in the beginning of a paragraph line converts the block into a list, and forcing it back to a paragraph erases the dash.
> 
> While it is visually quite understandable (although not universally welcome) that the list was automatically created, it takes some time for a new user to understand that it is not a formatting option but a change of paragraph type, turning into frantic clicking in attempts to deactivate the list type button that looks to be at fault.
> 
> Changing the block back to paragraph erases the dash. Although I've found a workaround of forcing a dash there by copy/paste, a user won't be able/agree to.
> 
> "But why would anyone ever do that?" - because sometimes you need to write:
> "A heading font statement or a quote or an image"
> " - an explanation in other font"

**Comment by iseulde** [comment]
Lost track of this issue.

**Comment by iseulde** [comment]
This is fixed by #13917, which is ready for review.
