### ISSUE TITLE
I´m getting this error while define style attribute in block save function

### ISSUE THREAD

**Issue by Migg88** [WordPress/gutenberg#13131]
![image](https://user-images.githubusercontent.com/28748931/50529010-d9c35800-0abf-11e9-8be5-f4c3f6f929ee.png)

**Comment by swissspidy** [comment]
Showing your code would help a lot :-)

At first glance it looks like your wrongly setting `null` as a background image.

**Comment by Migg88** [comment]
This is my code, now is workin because i set the attribute like this "backgroundImage: 'url(' + imageObject.sizes.full.url + ')'"  but if  i add an extra style attribute in save function i get the same error.

`import './style.scss';
import './editor.scss';

const ALLOWED_MEDIA_TYPES = [ 'image' ];
const { __ } = wp.i18n; // Import __() from wp.i18n
const { 
	registerBlockType, 
} = wp.blocks; // Import registerBlockType() from wp.blocks
const {
	RichText,
	InspectorControls,
	InnerBlocks, 
	MediaUpload,
} = wp.editor;
const {
    Toolbar,
    Button,
    Tooltip,
    PanelBody,
    PanelRow,
    FormToggle,
} = wp.components;

registerBlockType( 'cgb/block-full-height-container', {
	// Block name. Block names must be string that contains a namespace prefix. Example: my-plugin/my-custom-block.
	title: __( 'full-height-container' ), // Block title.
	icon: 'welcome-widgets-menus', // Block icon from Dashicons → https://developer.wordpress.org/resource/dashicons/.
	category: 'layout', // Block category — Group blocks together based on common traits E.g. common, formatting, layout widgets, embed.
	keywords: [
		__( 'full-height-container' ),
		__( 'create-guten-block' ),
	],
	attributes: {
		backgroundImage: {
			type: 'string'
		}
	},

	edit: function( props ) {

		const {
            setAttributes,
            attributes,
            className
        } = props;

        const { backgroundImage } = props.attributes;

		function onImageSelect(imageObject) {
            setAttributes({
                backgroundImage: 'url(' + imageObject.sizes.full.url + ')'
            })
        }

		return ([
			<InspectorControls>
            	<PanelBody 
            		title={__('Ajustes del Contenedor')}
            	>
            	<PanelRow>
            		<label>
            			Imagen de fondo
            		</label>
            		<MediaUpload
			            onSelect={ onImageSelect }
			            type="image"
			            value={backgroundImage}
			            render={({ open }) => (
			                <button onClick={open}>
			                    Subir Imagen
			                </button>
			            )}
			        />
            	</PanelRow>
            	</PanelBody>  
            </InspectorControls>,
			<div
				className={ props.className }
				style={{
                    backgroundImage: backgroundImage,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    color: 'white',
                }}
			>
				<InnerBlocks />
			</div>
		]);
	},

	save: function( props ) {
		const { backgroundImage } = props.attributes;
		return (
			<div
				style={{
					backgroundImage: backgroundImage
				}}
				className={ props.className }
			>
				<InnerBlocks.Content />
			</div>
		);
	},
} );
`

**Comment by designsimply** [comment]
@Migg88 I am closing this issue since you mentioned you were able to get your code to work. If you're still interested in discussing the problem when you add an extra style attribute in the save function, please provide the sample code that does not work (e.g. what you used instead of `backgroundImage: 'url(' + imageObject.sizes.full.url + ')'`) and re-open this issue. Thank you!
