### ISSUE TITLE
No way to set a post as "Sticky"?

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1313]
Noticed while posting #1312 

In the Post Visibility panel there's no option to set a post as "Sticky":

<img width="299" alt="screen shot 2017-06-20 at 17 48 41" src="https://user-images.githubusercontent.com/1682452/27343752-2826195c-55e4-11e7-971f-2572f745f160.png">

In the current Publish box there's a checkbox `Stick this post to the front page` that appears only when visibility is set to "Public".

Personally, I've always found the "Sticky" setting not so logically related to visibility. It is more related to the ordering. Maybe worth considering to improve things compared to the current WordPress implementation, put "Sticky" somewhere else, and have a cleaner UI. However, I couldn't find a "Sticky" option in the current Gutenberg UI.

**Comment by youknowriad** [comment]
Calypso could be a good inspiration here, maybe.

**Comment by afercia** [comment]
> Calypso could be a good inspiration here, maybe.

For reference:

<img width="301" alt="screen shot 2017-06-20 at 20 25 19" src="https://user-images.githubusercontent.com/1682452/27349149-ab546984-55f6-11e7-9970-8c45c671ea87.png">

**Comment by iseulde** [comment]
Sounds like a good first ticket.

**Comment by mtias** [comment]
We add a little bookmark icon to the canvas when this is toggled in Calypso, which helps a lot with scanning when editing posts.
