### ISSUE TITLE
Image Upload from the Image block fails to import the image title

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#13136]
Titles are not taken from the metadata for Images imported by clicking on 'Upload' button in the Image block. The title is set to the file name.

Note: I cross-checked the image files have the required metadata.

**To Reproduce**

1. Create an image with full metadata (Title & caption etc).
2. Import using the 'Upload' button in the image block.
3. Check the title in the media browser.

**Expected behavior**
The title field should be populated with the metadata title, *not* the file name.

**Gutenberg 4.7.1**

Edit: add Gutenberg version.

**Comment by designsimply** [comment]
I tested and confirmed the pull request for this issue and left notes at https://github.com/WordPress/gutenberg/pull/13193#issuecomment-456676642.

Looks great!
