### ISSUE TITLE
Clarification needed for I18N package

### ISSUE THREAD

**Issue by dsifford** [WordPress/gutenberg#13132]
In the README.md file of the i18n package, it states very bluntly the following...

> Note that you will not need to specify domain for the strings.

What does this even mean? Plugin authors don't need to specify textdomain in javascript file i18n functions? Can someone clarify this?

![image](https://user-images.githubusercontent.com/5240018/50529946-e7c8a700-0ac6-11e9-92fe-2465c05761a1.png)

**Comment by swissspidy** [comment]
Ugh yeah that is totally wrong. Will update the docs.

**Comment by youknowriad** [comment]
This is fixed I think
