### ISSUE TITLE
Undo(restoring) a deleted long title doesn't show up entirely in the title box

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#13135]
**Describe the bug**

**To Reproduce**
1. Create a post or a page (no need for publishing it)
2. Add a long title like "A very long title to be added to this post so please work after undoing ?"
3. Delete it and hit the undo button on your keyboard
4. It should be something like this:
https://monosnap.com/file/jMaq4tAcZYIeLGuqt3z9WixGuYWcgf

**Expected behavior**
I expected to see he entire title as I typed it initially

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - 71.0.3578.98

**Comment by ehti** [comment]
Heya @Robertght,

Are you still able to reproduce this?

We tested this today in core editor triage today, but nobody was able to replicate it. There also appears to be a duplicate in #12075 so I'm gonna close this issue/thread in favor of that.

Thanks!
