### ISSUE TITLE
Bug with WooCommerce Store

### ISSUE THREAD

**Issue by westsyde** [WordPress/gutenberg#13147]
**Describe the bug**
When you create content on the main woocommerce store page even on a fresh install extra paragraph tags are created which alters the page layout.. You can only see them from the source. You don't see them in the editor.
1. Go to woocommerce store page
2. Create content with a mix of headers and paragraphs.
3. Save page and go to the preview and view source.

**Expected behavior**
4. You will see 1-2 extra paragraph tag sets for each one you created.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 - the latest]
 - Browsers tested Chrome, Edge, IE and Firefox]
 - Versions = All the latest

**Smartphone (please complete the following information):**
 - Device: Note 8 is also showing the same issue

**Additional context**
- The version of Gutenberg is the latest as per WP v5.0.2
The issue is consistent across every test I ran.  It's always only the store page main content area with extra paragraph tags.
It's got to be either Gutenberg and or woocommerce related.. I suspect one conflicts with the other.

I also linked to the GeneratePress site forum where i discussed this issue over the last couple of days.

https://generatepress.com/forums/topic/potential-store-page-bug/

**Comment by swissspidy** [comment]
Have you reported this to WooCommerce as well already? When it only happens with a WooCommerce page it's highly likely that it's an issue with that plugin :-)

**Comment by westsyde** [comment]
I have via twitter and in the WooCommerce free support forum but not on GitHub. I've yet to hear back.
I'll go do that now. Cheers.

**Comment by youknowriad** [comment]
Looks they're working on a fix.
