### ISSUE TITLE
YouTube Embed Shows Error Message But Actually Works

### ISSUE THREAD

**Issue by roundhill** [WordPress/gutenberg#1314]
I was trying out Gutenberg (it's so cool! 🎉) and noticed an issue when trying to embed a YouTube video.

**To Reproduce**
1. Start a new post
2. Select `+` and then `YouTube` in the Embeds section.
3. Insert a YouTube url, I used `https://www.youtube.com/watch?v=pdZQ98mWeto`
4. You'll see this message `Sorry, we could not embed that content.`:
<img width="613" alt="screen shot 2017-06-20 at 9 38 58 am" src="https://user-images.githubusercontent.com/789137/27344815-81c03cba-559c-11e7-9719-824b9db4f75b.png">
5. Publish the post. You'll see the video in the post just fine!

**Comment by aduth** [comment]
This would occur if there was an error in retrieving the embed result.

https://github.com/WordPress/gutenberg/blob/8fd70f4/blocks/library/embed/index.js#L144

Can you look at your network tab and see what response you're receiving for the embed request?

It may be a 404 if you're running a version of WordPress that does not include the [oEmbed proxy endpoint](https://github.com/WordPress/WordPress/blob/06fa4161aa74619239cf27017d124081c825684a/wp-includes/class-wp-oembed-controller.php#L56-L95) (>= WordPress 4.8).

**Comment by roundhill** [comment]
I think you're exactly right @aduth:

```
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
    }
}
```

**Comment by aduth** [comment]
Which version of WordPress are you running?

**Comment by roundhill** [comment]
> Which version of WordPress are you running?

Version 4.8: http://11f5306f.ngrok.io

**Comment by aduth** [comment]
Your site is not serving the REST API: http://11f5306f.ngrok.io/wp-json

Is this disabled, by you or your host?

**Comment by youknowriad** [comment]
(Try enabling permalinks if they're not already enabled)

**Comment by roundhill** [comment]
> (Try enabling permalinks if they're not already enabled)

This was the issue, the site had them set to `plain`. 👍

**Comment by youknowriad** [comment]
@roundhill Depending on the web server, this isn't required. AFAIK this is more an issue in the web server breaking the REST API. It's not specific to Gutenberg.

**Comment by roundhill** [comment]
> It's not specific to Gutenberg.

Agreed, will close here and check if there's an issue on the REST API.
