### ISSUE TITLE
how add  gutenberg to new custom post type

### ISSUE THREAD

**Issue by masami6871** [WordPress/gutenberg#13141]
hi.  i created a new custom post type -for example : " Portfolio "

and  when i want  to  leave a post , i don't show gutenberg editor and  i saw old wordpress  editor .  
how can i  active gutenberg  for  my custom type ?  
![1](https://user-images.githubusercontent.com/29583593/50549671-36687380-0c76-11e9-930e-3b176a7546c3.jpg)

**Comment by gregbia** [comment]
When registering a new post type, you need to add REST support.

Add this to your custom post type arguments passed to register_post_type:

`'show_in_rest'       => true,`

**Comment by masami6871** [comment]
> When registering a new post type, you need to add REST support.
> 
> Add this to your custom post type arguments passed to register_post_type:
> 
> `'show_in_rest' => true,`

thank you dear .  i do that.
