### ISSUE TITLE
Subdirectories are not watched in dev environment for Linux OS

### ISSUE THREAD

**Issue by Rahmon** [WordPress/gutenberg#13140]
**Describe the bug**
The recursive option in `fs.watch` is [only supported on macOS and Windows](https://nodejs.org/api/fs.html#fs_caveats). So on Linux the subdirectories aren't watched when i run `npm run dev`.

https://github.com/WordPress/gutenberg/blob/84e1e8031cb54b322f01adde9d560112290c6909/bin/packages/watch.js#L36

**To Reproduce**
1. On Linux OS clone the project.
2. Run `npm i` and `npm run dev`.
3. Make some change in file: packages/block-library/src/paragraph/index.js
4. Change isn't watched (nothing happens)

**Expected behavior**
"watch" to work on Linux too.. :disappointed: .

**Possible solution**
I've used [node-watch](https://github.com/yuanchuan/node-watch) package.

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Version 4.7.1

**Comment by gziolo** [comment]
It was fixed in #13448.
