### ISSUE TITLE
keepPlaceholderOnFocus for Paragraph and Heading when used in a Template

### ISSUE THREAD

**Issue by floriandagge** [WordPress/gutenberg#13151]
**Use Case**
I created a custom block for Gutenberg which makes use of "InnerBlock".
I also added a template in the same step, including some options like "placeholder".
The option "placeholder" itself works fine, but "keepPlaceholderOnFocus" doesn't seem to work in this scenario, as placeholder is removed when focusing the element.

**Possible solution**
It should be possible to use the option "keepPlaceholderOnFocus" in scenarios like this.

**Comment by youknowriad** [comment]
`keepPlaceholderOnFocus` is a RichText prop, I'm not sure I understand how you'd want to use it in this context? Can you share an example of code?

**Comment by youknowriad** [comment]
Closing as stale. Let's reopen if we can make it actionable.

**Comment by floriandagge** [comment]
Sorry for the late answer. Following code example:

```
    blocks.registerBlockType('sbt/milestone', {
        title: 'Milestone Slider Element',
        description: 'Element von Meilenstein Slider',
        icon: 'editor-contract',
        category: 'layout',
        parent: ['sbt/milestones'],
        
        edit: function (props) {
            return (
                el('li', { className: props.className },
                    el(InnerBlocks, {
                        className: 'milestone',
                        template: [
                            ['core/columns', {templateLock: 'all'}, [
                                ['core/column', {templateLock: 'all'}, [
                                    ['core/heading', {
                                        'placeholder': 'Ueberschrift',
					'keepPlaceholderOnFocus': true,
                                        'level': 2,
                                        'align': 'right'
                                    }],
                                    ['core/paragraph', {
                                        'placeholder': 'Beschreibung',
                                        'align': 'right'
                                    }]
                                ]],
                                ['core/column', {templateLock: 'all'}, [
                                    ['core/image', []]
                                ]]
                            ]]
                        ],
                    templateLock: 'all'
                    })
                )
            )
        },
        
        save: function (props) {
            return (
                el('li', { className: 'slider-block' }, 
                    el(InnerBlocks.Content)
                )
            )
        }
    })
```
Focus on placeholder on "core/heading" isn't working, when using in this combination.

**Comment by youknowriad** [comment]
@floriandagge Where is this code example coming from. `keepPlaceholderOnFocus` is not an attribute of the heading or paragraph blocks, you can't use this in a template like you're doing here.

**Comment by floriandagge** [comment]
@youknowriad oh, I'm sorry, I don't know where it was coming from initially. I just double-checked the source, and I'm not sure why I didn't recognize that the whole attribute is not existing in the two blocks. Sorry for that! However, as you can see, it would be very good to implement this attribute. Do you think this can be added?

**Comment by youknowriad** [comment]
The problem is it's a design decision and attributes are meant to be used for things that persist that are meaningful for the content. I feel like adding this would be too much complexity for a small gain.

An alternative would be to build an alternative block but I can see how this is also too much for such a small change.
