### ISSUE TITLE
Page Parent Selector Missing Unique className

### ISSUE THREAD

**Issue by mikeselander** [WordPress/gutenberg#13165]
**Describe the bug**
Most selector fields in the Document Sidebar have unique classes that can be used to target them with CSS, but the Page Parent selector does not have any such class. For consistency this element should have a class like the others.

**To Reproduce**
1. Navigate to any page
2. Inspect the elements within the Page Attributes section
3. Observe that the Page Order Base Control element has a unique class of `editor-page-attributes__order`, but the Page Parent element does not.

**Additional context**
This is a very minor nit, but comes from a unique client requirement that I have to target. Targeting this element currently requires a really awful selector of `.components-panel__body .components-base-control:not([class*="editor-"])` but could be dramatically easier with this change.

**Comment by youknowriad** [comment]
Can I ask why do you want to target this selector?

**Comment by mikeselander** [comment]
Sure thing - as a warning though, this is a hack driven by a legacy codebase that we're moving from using a _very_ legacy version of Gutenberg. I don't expect that anyone else will have this need but I feel like it's still a general improvement to be consistent with CSS classes across similar components. This issue and the associated PR are driven more by a desire for consistency then this specific hacky need.

We have a need to hide the Page Parent selector in lieu of a custom implementation that our client wrote. The client has been pinned at G'berg 2.8 since May of last year and 2.8 didn't have a page parent selector, so the client wrote their own. However, they also added custom logic that updates some other data stores within the editor when a page parent is updated so I can't just use the core selector (which I'd rather do). I'd prefer to write some logic to hook on top of the core page parent updating but we don't have the budget to do that at this time.

**Comment by youknowriad** [comment]
Gotcha, notice that you can disable Gutenberg panels without CSS with official APIs. By dispatching this action https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-edit-post/#toggleeditorpanelenabled

We can add CSS classNames but we don't guarantee that these don't change over time, CSS and DOM are not part of the official API.
