### ISSUE TITLE
Cannot align two images in Gutenberg

### ISSUE THREAD

**Issue by FayeWilliams** [WordPress/gutenberg#13175]
Using Gutenberg I cannot add two images next to each other that align correctly. Most of my posts have two pin images at the bottom. In Gutenberg, the closest I can get is this (I've drawn lines as the white image is more difficult to see):

![screen shot 2019-01-03 at 15 13 09](https://user-images.githubusercontent.com/6819240/50645262-02899880-0f6b-11e9-8937-56b1aeca7943.jpg)

I cannot use a gallery as I cannot set the width to be medium (200px) for the images.

How can I align these correctly? It seems to be impossible to do what I want to do.

In the classic editor they line up perfectly.

I can create an HTML block to align them, but I don't really want to have to do this for every post.

**Comment by swissspidy** [comment]
Have you tried a paragraph block with inline images? Or a columns block perhaps?

**Comment by FayeWilliams** [comment]
1) I can't see any way to insert an image in a paragraph block. Either it turns into an image block as soon as I click the image icon on the block border, or I start typing (to get a paragraph) and then there is no obvious way to add an image. I could be missing the obvious here?

2) I can't see any way to add a columns block (screenshot below) again - I might be missing the obvious?

![screen shot 2019-01-03 at 16 59 56](https://user-images.githubusercontent.com/6819240/50650682-14723800-0f79-11e9-8dee-b31ed7099bef.png)

**Comment by FayeWilliams** [comment]
1) Can you please screenshot where the "+" button is? I don't have one on the top/right and cannot see anywhere to add a column.

2) The align menu which you have in the screenshot is the one that makes them misaligned - that is why I opened this thread. They appear correct in the editor, but on the web page they present with one dropped image (as shown in my original screenshot above).

**Comment by youknowriad** [comment]
Sure.

<img width="1276" alt="capture d ecran 2019-01-04 a 11 36 22 am" src="https://user-images.githubusercontent.com/272444/50684275-2b666800-1015-11e9-9907-1a62d0d235fe.png">

**Comment by FayeWilliams** [comment]
Thank you. I've tried columns, but cannot close the gap. 
Align image leaves them misaligned.

How can I align these images correctly in Gutenberg? It doesn't seem possible to do something that was simple in the classic editor.

![screen shot 2019-01-04 at 10 41 33](https://user-images.githubusercontent.com/6819240/50684546-d7a45080-100d-11e9-87b3-5a858d049743.jpg)

**Comment by youknowriad** [comment]
The Classic editor uses "float alignments", the exact same thing can be done using the toolbar I showed you before, you just need to ensure both images are left aligned and that their size is adjusted properly.

**Comment by FayeWilliams** [comment]
That's my point, aligning left doesn't work.

This is both images aligned left. It displays correctly in the editor, but not on the post.

You can see it here:
https://simpledays.co.uk/overwhelmed-by-clutter/

![screen shot 2019-01-04 at 11 47 29](https://user-images.githubusercontent.com/6819240/50686790-ad0ac580-1016-11e9-8fb1-e403a01a0028.jpg)

**Comment by youknowriad** [comment]
The issue seems to be coming from this CSS selector:

```
.entry-content > [class*="wp-block-"]:not(:last-child)
```

I think it's a theme issue.

**Comment by FayeWilliams** [comment]
It is a theme issue :-)
Corrected with some custom CSS. Thank you!
