### ISSUE TITLE
Post date should not be updated when post is set "pending review"

### ISSUE THREAD

**Issue by davisshaver** [WordPress/gutenberg#13176]
A newsroom user reported the following:

> Can we make the default publish date “immediately” like it was before the site update? Still having some issues with accidentally backdating, taking too long to change the date/time when publishing breaking news, etc.

After investigation, I described the issue as seen above: The post date should not be set when post is "pending review". The newsroom user agreed with this assessment.

> Publishing a post from draft is immediately but the other statuses we use regularly (pending, proofed, reserve) the post date gets set

Here is a GIF demonstrating this behavior, which I believe constitutes a "bug" since the behavior is different than what happened in the same situation pre-Gutenberg.

![2019-01-03 10-42-42 2019-01-03 10_43_21](https://user-images.githubusercontent.com/1636964/50646757-e246e300-0f44-11e9-8e8d-d60d931aa8a1.gif)

This issue seems related to https://github.com/WordPress/gutenberg/issues/7195 and solution https://github.com/WordPress/gutenberg/pull/9967. cc @kadamwhite  @earnjam @tofumatt who participated on the original thread.

**Comment by earnjam** [comment]
Ah, that's because it's only looking at status of `draft` or `auto-draft`. We'll need to account for `pending` also.
