### ISSUE TITLE
gallery block's alignwide class is not removable after saving

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#13170]
**Describe the bug**
When "Wide width" is selected and saved for the gallery block, unselecting it doesn't remove the `alignwide` class in the editor or on the front-end.

**To Reproduce**
1. Select "Wide width" for a gallery block and save the post.
2. Refresh the edit post screen and remove the "Wide width" selection for the block. Save post.
3. Check out your gallery block on the front-end and the editor. The `alignwide` class remains.

**Expected behavior**
`alignwide` shouldn't be present when Wide width isn't selected.

**Screenshots**
![align-gallery](https://user-images.githubusercontent.com/3585901/50614744-dbba5c00-0eaf-11e9-9f4b-1903a385f10c.gif)

Related question: Why are we even adding these classes in the editor? https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/edit.js#L264

Shouldn't we be relying on `[data-align="wide"]` for these styles?
 
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chrome, firefox
 - Version: latest

**Additional context**
- Tested and got the same result in WP 5.0.2 and the master branch of this repo.

**Comment by m-e-h** [comment]
Thanks for checking it out @jorgefilipecosta !

I'm using TwentyNineteen v1.1 without any plugins active.

You're correct that during the block manipulation a class is being added in the class name inserter. The thing is that I'm not adding it. It's getting added when I update the post.

Here's a screencast of what I'm seeing https://drive.google.com/file/d/1WkwPtsA3c28OCz3n5WVRy-UmepivJRUA/view

**Comment by m-e-h** [comment]
Here's another gif showing how the classes add up as alignments are changed. 

![galalignclasses](https://user-images.githubusercontent.com/3585901/50702823-180cca00-1020-11e9-89d4-032381fdf640.gif)

You probably won't be able to repeat it unless you refresh screen after each update.

**Comment by talldan** [comment]
This one no longer seems to be an issue. I'll close, but @m-e-h, let me know if you're still experiencing this and I can reopen.
