### ISSUE TITLE
Gutenberg doesn't know how to chnage color of words highlighted in paragraph. Is that true?

### ISSUE THREAD

**Issue by dameer** [WordPress/gutenberg#13172]
For the sake of God, how one is supposed to highlight and change the color of a single or multiple words in paragraph block?
You can change background color, you can change the color of entire text. Cool.

My client asked me how to and I was stunned coz it looks like there's no other way but to edit paragraph as HTML and use SPAN with a chunk of an inline style.

**Comment by Soean** [comment]
The initial Issue for this feature is #6080

**Comment by xpurichan** [comment]
We had another request for this feature in 1771212-zen. The user is on our free plan, so it isn't possible to install a plugin for this. In the meantime I invited the user to use our Classic block to manage the color.
