### ISSUE TITLE
Autosaving duplicate content issue when using certain language

### ISSUE THREAD

**Issue by cqwt** [WordPress/gutenberg#13185]
**Describe the bug**
When using a language which needs to select correct character after input the phonetic alphabet (like chinese), if autosave is triggered while the input is waiting for selection, it will display duplicate content in gutenberg editor after autosave is complete.

Sorry, I can't describe this issue in English very clearly, please see the screenshot gif. 

I only test under Chinese, but I think any language needs select character after input may have same issue.

The duplicate content does not save into draft, if you refresh the page, it will show only one copy of the content.

**To Reproduce**
1. Type some content in Chinese.
2. Do not press Enter/Return to confirm the input.
3. Wait for autosave.
4. See error. It will display duplicate content, which is the content you are typing but have not confirm yet.

**Expected behavior**
I can't remember how this work in classic editor, but I expect after autosaving, editor will keep what I was typing, and won't display duplicate content. 

**Screenshots**
![autosave duplicate content issue when using certain language](https://user-images.githubusercontent.com/1461441/50689762-eae30a80-1065-11e9-93eb-c9f428e11cf6.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2, Windows 10 (version unknown)
 - Browser: chrome 71.0.3578.98 64bit
 - Version: 5.0.2 (native gutenberg, not plugin)

**Comment by paaljoachim** [comment]
Hi @cqwt Chen

I noticed your issue happen to not receive any comments. Is it still relevant?

**Comment by cqwt** [comment]
Hi @paaljoachim ,

this issue is already solved, thanks.
