### ISSUE TITLE
Block validation failed for `core/list`

### ISSUE THREAD

**Issue by BrElio** [WordPress/gutenberg#13191]
Every time I am working with the new editor this error pops out:

**Block validation: Block validation failed for `core/list`**

1. Create a new post
2. Click on "Start writing or type..."
3. Error appears in console

Screenshot:
![image](https://user-images.githubusercontent.com/33754253/50695411-dcccc400-103c-11e9-8884-4e3d8f1a0239.png)

- WordPress 5.0.2
- Twenty Sixteen
- No Plugins installed

 - OS: Mac OS Mojave
 - Browser chrome
 - Version 71

**Comment by BrElio** [comment]
It also happens opening a post and clicking on the plus sign to add a new block and scrolling the blocks list.

**Comment by youknowriad** [comment]
I was not able to reproduce with WordPress 5.0.3. Maybe this is fixed? Otherwise, please provide more instructions.

**Comment by youknowriad** [comment]
Also, this could be related to some old reusable blocks you have, check those (or remove them to try).

**Comment by BrElio** [comment]
I had a reusable block as you said! I have removed it and the issue seems resolved.
Thanks
