### ISSUE TITLE
How to import Gutenberg from the NPM command line? (As a module)

### ISSUE THREAD

**Issue by gilcarvalhoTI** [WordPress/gutenberg#13196]
How to import Gutenberg from the NPM command line? (As a module)

**Comment by swissspidy** [comment]
What part do you want to import exactly? What are you trying to achieve?

**Comment by youknowriad** [comment]
If you're trying to import the whole editor as a npm package, that's not possible at the moment (or at least not easily). Gutenberg does provide the building tools to do it though  (The `edit-post` module could be considered just one implementation of a post editor you could get inspiration from).

Also, there's some on going work making this kind of usage easier (see #13088)
