### ISSUE TITLE
Ad images not showing 

### ISSUE THREAD

**Issue by marichmond** [WordPress/gutenberg#13197]
I created an image gallery from my ShareASale site. When I post the code they gave me into the custom html widget space, the images are not loading. I reached out to ShareASale support and they checked the code and opened it correctly on their end. When I work in the Manage Widget in Live View mode, I can see the imaged, but then when I go to the actual live site they aren't loading. I tried it on my computer and phone and both aren't working. 
I know nothing about code...I just started my Wordpress website in August, so any help is appreciated. Here is the code that I am having problems with : 

```html
<div class="shrsl_ShareASale_productShowCaseTarget_29976"></div>
<script type="text/javascript"  src="https://showcase.shareasale.com/shareASale_liveWidget_loader.js?dt=01042019150655"></script>
<script type="text/javascript">shrsl_ShareASale_liveWid_Init(29976, 1912395, 'shrsl_ShareASale_liveWid_square250_populate');</script>
```

**Comment by youknowriad** [comment]
Do you use an adblocker?

I just tried it and it works properly for me.

Also if you're not admin for your WordPress website you might not be able to paste any random scripts for security reasons.
