### ISSUE TITLE
Headings not showing

### ISSUE THREAD

**Issue by TheOwlLady** [WordPress/gutenberg#13209]
I have set up text in line with images and have a heading for each one.  The headings do not show up 
This is a screen shot from the editor![image](https://user-images.githubusercontent.com/46400759/50725934-c160c800-10d3-11e9-810a-b79c696f676a.png)
This image shows no headings when brought up in both chrome and bing
![image](https://user-images.githubusercontent.com/46400759/50726217-ece5b180-10d7-11e9-82a4-80bdbe5185ac.png)

go to http://highcountryaudubon.org
Click on education
Click on grants and scholarships
click on "previous Sue Wells ............."
See missing headers.
 The page doesn't show up at all on my phone using safari.

Using Windows 10
on  a laptop
chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ocean90** [comment]
You have some inline CSS which sets the color for headings to `#ffffff` which makes them invisible on white background.

<img width="355" alt="css" src="https://user-images.githubusercontent.com/617637/50739084-3539c800-11db-11e9-97ef-ae0437f5f4a4.png">

**Comment by TheOwlLady** [comment]
That was easy.  Thank you.
