### ISSUE TITLE
Research Synthesis Step 3: Compiling results

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#13216]
_Note: this is to discuss and reference methodology for compiling and communicating results of our sitebuilding study. This isn't 100% set in stone just yet and will be tweaked as we finalise details._

Want to get involved? No prior research experience is necessary, and [we'd ❤️ your help!](https://make.wordpress.org/design/2019/01/05/sitebuilding-research-whats-next/?preview=true)

-----

## Deliverables:

- Key takeways (no more than ten)
- Recommendations (to inform product decisions)
- A mental model of sitebuilding for each identified segment
- A customer journey for each identified segment

The above will be compiled into a single report—either as a PDF or a single-page site (more accessible) of no longer than 10-15 pages.

### Executive summary

Basically a one-page tl:dr;

### Background information

Who we talked to, when, what we talked about, who did the talking, what we were trying to learn, goals of the research, etc.

### Key findings

A short list of the most important findings of the study.

### Recommendations

Actionable product recommendations that can be used to guide phase two.

### Theme exploration

For themes identified in analysis, define and name each theme. Give some description about what you've learnt, stories and quotes within that theme, any contradictions within that theme, and explain what makes it interesting and relevant to the project.

### Mental model & customer journey

These will be visual tools that can be used to refer back when making product decisions and to inform an understanding of the entirety of the customer experience.

**Comment by karmatosed** [comment]
I am closing this as it's complete now.
