### ISSUE TITLE
Youtube embed videos not responsive in mobile layout

### ISSUE THREAD

**Issue by slowaways** [WordPress/gutenberg#13212]
**Describe the bug**
After a YouTube embed is inserted, the youtube video have a giant width when displayed in mobile layout.

**To Reproduce**
1. Go to Gutenberg editor
2. Paste a link of youtube to create a embed
3. Go to the link post in mobile
4. See a giant youtube video

**Expected behavior**
Youtube embed responsive

**Screenshots**
![photo_2019-01-05_16-00-54](https://user-images.githubusercontent.com/9668277/50728211-08b37c80-1105-11e9-870c-61566bb66fff.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 71

**Smartphone (please complete the following information):**
 - Device: ASUS Zenfone 3 Zoom
 - OS: Android 8.0.0
 - Browser Chrome
 - Version 71

**Additional context**
- Gutenberg Wordpress 5.0.2 version

**Comment by ocean90** [comment]
What theme are you using? Does it opt-in to [responsive embeds](https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#responsive-embedded-content)?

**Comment by slowaways** [comment]
`add_theme_support( 'responsive-embeds' );`
Where do I have to add this code? functions.php?

**Comment by slowaways** [comment]
Add add_theme_support( 'responsive-embeds' ); to my theme now it's responsive!!!
This should be set by default.
