### ISSUE TITLE
Permalinks with RTL on them, displaying their codes instead of the characters

### ISSUE THREAD

**Issue by mlaetitia** [WordPress/gutenberg#13229]
When publishing a post with a non-standard ASCII char (for instance, using RTL) the permalink appears with the character code instead of the character itself

**To Reproduce**
1. Go to a wp site and create a new post with an arabic title (which creates an arabic permalink). I use this to copy the text: https://translate.google.com/#view=home&op=translate&sl=auto&tl=ar&text=hello%20world
2. Publish the post with Gutenberg active
3. On the permalink field, see the codes there: http://cld.wthms.co/5sjUvt
4. Activate the Classic Editor plugin and head to the exact same post - the permalink appears with the characters instead: http://cld.wthms.co/rKe1Y8

**Expected behavior**
I expected the characters to appear as the title show them (as they'll appear in the URL).

**Screenshots**
Codes appearing with Gutenberg active: http://cld.wthms.co/5sjUvt

![screen shot on 2019-01-07 at 17_10_23](https://user-images.githubusercontent.com/1119271/50796937-69bb8b80-1290-11e9-8222-64437fdfa617.png)

Chars appearing correctly with Classic Editor: http://cld.wthms.co/rKe1Y8

![screen shot on 2019-01-07 at 17_11_39](https://user-images.githubusercontent.com/1119271/50796957-72ac5d00-1290-11e9-87e0-e05fd2997feb.png)

**Desktop (please complete the following information):**
 - OS MAC Os
 - Firefox

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 5.0.3 and no active plugins using Firefox 64.0.2 on macOS 10.13.6.

![screen shot 2019-01-11 at 5 19 08 pm](https://user-images.githubusercontent.com/1119271/51066016-2da46580-15c5-11e9-9f0f-3a9a1624fec0.png)
![screen shot 2019-01-11 at 5 19 45 pm](https://user-images.githubusercontent.com/1119271/51066015-2da46580-15c5-11e9-90a5-96eb4714c2d5.png)

**Comment by ramiy** [comment]
Please read #13616 :

> This bug was **fixed in WordPress over 9 years ago** by applying `editable_slug` filter on all permalinks displayed on screen. For more information see track tickets [10966](https://core.trac.wordpress.org/ticket/10966) and [16999](https://core.trac.wordpress.org/ticket/16999).
