### ISSUE TITLE
How to install Gutenberg 4.8 in my WordPress CMS

### ISSUE THREAD

**Issue by alexvornoffice** [WordPress/gutenberg#13223]
I have downloaded the zip file, now what? Where is installation instruction?

**Comment by youknowriad** [comment]
You just upload the zip to your plugins page like any other plugin.

Otherwise, The 4.8 is going to be released to the WordPress repository in some minutes, you would be able to download it directly from there.

**Comment by alexvornoffice** [comment]
Thanks for reply but why no instruction in the readme file?

**Comment by youknowriad** [comment]
Because this is the same as any WordPress plugin. there's nothing specific to Gutenberg here.

**Comment by youknowriad** [comment]
There are already docs for this here https://codex.wordpress.org/Managing_Plugins

**Comment by youknowriad** [comment]
Oh got it. Let me know if it works for you now.

**Comment by alexvornoffice** [comment]
I created a patch please accept my pull request  :D - https://github.com/WordPress/gutenberg/pull/13226
