### ISSUE TITLE
Add character count to Content structure

### ISSUE THREAD

**Issue by TeemuSuoranta** [WordPress/gutenberg#13225]
**Is your feature request related to a problem? Please describe.**
Copywriters work often character counts instead of word counts and finding out the character count can be important part of writing process. Also SEO people often are interested the character count instead of word count because the amount of text matters to search engines.

So there are use cases and processes that would benefit from simple character count display.

**Describe the solution you'd like**
The content structure now:
![screenshot 2019-01-07 at 14 09 45](https://user-images.githubusercontent.com/9577084/50767556-fc0a6200-1285-11e9-83df-49b63f482de1.png)

This could simply have additional number for character count here.

**Describe alternatives you've considered**
This is a feature that I wouldn't want to build myself or would hardly trust any 3rd party plugin to get the feature right and future proof. At the moment I can create this custom for client with PHP as an admin column but that is not very user friendly place for it. This would be optimal for Gutenberg itself to handle.

**Extending this feature**
If the character count would be fetchable for plugins they could display notifications etc based on characted count (for example blog could set its recommended length for writers and these writers be prompted if the article is too long or short).

**Comment by TeemuSuoranta** [comment]
The character count has been at least in some past mock-ups but has been dropped in some point. See: https://github.com/WordPress/gutenberg/issues/1557

**Comment by kjellr** [comment]
Just noting that there's a PR to add character count here: https://github.com/WordPress/gutenberg/pull/14589

Since that's almost ready to land and already has design approval, I'll remove `Needs Design Approval` from this ticket. 👍

**Comment by grappler** [comment]
Is this fixed in https://github.com/WordPress/gutenberg/pull/24823?

**Comment by TeemuSuoranta** [comment]
Thanks for notifying! This feature is implemented in WP 5.6 so I'll close this issue.
