### ISSUE TITLE
Typing in tables is very slow

### ISSUE THREAD

**Issue by Peterselie2** [WordPress/gutenberg#13238]
**Describe the bug**
I'm working with wordpress 5.0.2, I've added a table on a page, 
the table has 14 columns and about 24 rows. 
When I type in a table field it takes about 15 seconds for my text to appear, 
when I click to select a table-field it takes about 5 seconds for it to be selected.  

**To Reproduce**
1. Go to a page / Add a new page 
2. Click on the plus icon for Add block 
3. Under 'Formatting' click to add a table 
3.1 Add 14 columns and 24 rows
4. Start typing in the first table-item, press tab to jump to the next item, after about 10 fields the editor slows down to a crawl, taking ~ 15 seconds to update

**Expected behavior**
I expect text to appear as I type and I expect a field to become selected as I click on it. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows NT 10.0
 - Browser: Chrome
 - Version: 71

**Smartphone (please complete the following information):**
- not tested

**Additional context**
- Please add the version of Gutenberg you are using in the description. 
      I'm using the Gutenberg version that comes with wordpress 5.0.2,

**Comment by youknowriad** [comment]
I personally couldn't reproduce the slowness using the table block, there might be another factor causing this. Can you try to reproduce with a new blank post and see if you still notice the same? Can you try disabling plugins (think Yoast...)?

**Comment by Peterselie2** [comment]
> I personally couldn't reproduce the slowness using the table block, there might be another factor causing this. Can you try to reproduce with a new blank post and see if you still notice the same? Can you try disabling plugins (think Yoast...)?

After disabling Yoast (Version 9.4) there's indeed a noticable increase in speed, I guess this issue can be closed here.

**Comment by youknowriad** [comment]
Thanks for the update.
