### ISSUE TITLE
Better organize existing Markdown documentation

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1323]
We have multiple Markdown documentation files within the Gutenberg repository that are currently not so easy to find:  https://github.com/WordPress/gutenberg/search?l=Markdown

Potential ways to improve this:

- Build a table of contents into the main readme, or other ways of pointing to these documents.
- Integrate more of our existing documentation into http://gutenberg-devdoc.surge.sh/ (and prominently link to this site from our main readme).

**Comment by youknowriad** [comment]
I've already included most of them in http://gutenberg-devdoc.surge.sh/ but we should definitely link to the site from the README 👍 

We should also add more documentation to our components, we have only one component documented right now.

**Comment by mtias** [comment]
This will be linked from a canonical page under .org website.
