### ISSUE TITLE
Full width Section with background for columns

### ISSUE THREAD

**Issue by JQOz** [WordPress/gutenberg#13239]
Hi,

has anyone idea how to add full width Section with background for columns or other elements(for paragraphs etc.)

Like the page in screenshot. I mean colored sections.

Thanks

![sections](https://user-images.githubusercontent.com/19261428/50836461-88d22000-1359-11e9-849e-7349a03d49d5.png)

**Comment by youknowriad** [comment]
Definitely, this is something we'd probably address using the planned Section block.

Closing this as a duplicate of #4900 

Thanks.
