### ISSUE TITLE
Old and new posts get "Updating failed" on a ~16-th update.

### ISSUE THREAD

**Issue by kivig2** [WordPress/gutenberg#13235]
**Describe the bug**
Updating a post ~16 times results in "Updating failed" for each particular post. Browser change or a restart doesn't affect anything. Other posts remain updateable until the threshold is reached.

**To Reproduce**
1. Add a new or open existing post
2. Enter title
3. Publish
4. Press update many times.
5. "Updating failed", console: 500 - internal server.

At first I thought it has something to do with how fast the button is pressed as it seems not to get disabled when it greys out, resulting in what looks like two updates semi-simultaneously on double click (or close to it) (which might be a separate bug), but after a bit of testing it seems to be related purely to total manual update count.

**Desktop:**
 - Ubuntu 18
 - Chrome 71, Firefox 64
 - Php 7.2
 - Apache 2.4
 - Wordpress 5.02

**Comment by kivig2** [comment]
Disabling revisions has no effect.

**Comment by swissspidy** [comment]
If you turn on error display in PHP, do you see any errors in the REST API responses when getting the 500 errors?

Does this still happen with all plugins disabled?

**Comment by kivig2** [comment]
It seemed impossible given the nature of particular plugin, but it indeed is a plugin fault. Sorry.
