### ISSUE TITLE
Floating boxes (Yoast, Likes & Shares, etc..) blocking gutenberg blocks

### ISSUE THREAD

**Issue by paulmil11** [WordPress/gutenberg#13233]
**Describe the bug**

**To Reproduce**
1. Open new post or existing post
2. Write long enough such that Yoast blocks the Gutenberg blocks

**Expected behavior**
I would expect Yoast to stay docked to the bottom

*Screenshots**
![image](https://user-images.githubusercontent.com/46465406/50801402-849ef780-12b2-11e9-850c-3699ffb87779.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 71

**Comment by youknowriad** [comment]
This could be related to PHP warnings/notices appearing on the page (but hidden by other elements). This is not the only reason though. The fact is your browser is in "quirks mode" making the CSS behave weirdly.

See the discussion in this thread for more details. https://github.com/WordPress/gutenberg/issues/11378

Thanks.
