### ISSUE TITLE
When a quotation ends with styled text, smart endquotes are backwards on the front end. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#13240]
**Describe the bug**
When quoted text (inside of a paragraph block, or elsewhere) contains styled text immediately preceding the closing quotation mark, that mark incorrectly appears as an opening quotation mark (a `&lsquo;` instead of a `&rsquo;`.

I'm not sure if there's anything we can do about this, as it appears to have been a problem with the Classic editor as well, but it seems like it's worth logging somewhere. This is a problem on the front end only, as the editor doesn't use smart quotes. 

**To Reproduce**
1. Insert some text contained within quotation marks. For example: "This is a quote"
2. Make the last word or two italic, bold, linked, or strike-through. 
3. Publish, and view the behavior of smart quotes on the front end. 

**Expected behavior**
The ending quotation mark should appear as an end-quote (`rsquo;`), facing to the left. 

**Screenshots**

In these screenshots, the first example ("Here is a quote") shows the correct behavior, while all the others are incorrect. 

_Twenty Nineteen:_
<img width="393" alt="screen shot 2019-01-08 at 9 50 34 am" src="https://user-images.githubusercontent.com/1202812/50837966-eef37e80-132a-11e9-9575-356e7985506d.png">

_Twenty Seventeen:_
<img width="344" alt="screen shot 2019-01-08 at 9 51 02 am" src="https://user-images.githubusercontent.com/1202812/50837977-f4e95f80-132a-11e9-9558-dc21b0ee9c63.png">

_Gutenberg Starter Theme:_ 
<img width="368" alt="screen shot 2019-01-08 at 9 50 54 am" src="https://user-images.githubusercontent.com/1202812/50837986-f9157d00-132a-11e9-9212-53b9874f23cd.png">

**Comment by iseulde** [comment]
This is a long standing issue in WordPress Core. I think there are multiple open issues about it. Example: https://core.trac.wordpress.org/ticket/40148. Since this is an issue with wptexturize, I'm going the close the issue. However, it could be fixed in RichText if we at some point "texturize" in RichText directly.
