### ISSUE TITLE
Searching for and adding existing categories is case-sensitive

### ISSUE THREAD

**Issue by xpurichan** [WordPress/gutenberg#13250]
**Describe the bug**
We can only search for and add existing categories to blog posts if we use lowercase letters, uppercase letters (even when they're a part of the original category name) yield no results.

**To Reproduce**
1. Setup at minimum 8 categories on your website (this is what makes the search feature appear in the blog post editor): https://wordpress.com/settings/taxonomies/category/
2. Create or edit an existing blog post
3. Since you have at least 8 categories we will see a search bar available to search for and add categories to this blog post. [Screenshot](https://user-images.githubusercontent.com/33190975/50862376-19602e80-1361-11e9-9ed1-269bf49b1eb1.jpg)
4. Search for an existing category, like "festival" in my example. The category will appear, as expected. [Screenshot](https://user-images.githubusercontent.com/33190975/50862457-4ca2bd80-1361-11e9-9e5f-7a127ee450fa.jpg)
5. However, if we search for the same category by entering "Festival" (capital "F") then it will not appear from my list. [Screenshot](https://user-images.githubusercontent.com/33190975/50862543-807de300-1361-11e9-926b-eacf69d5270c.jpg)

**Expected behavior**
In Calypso this behavior did not exist, we could search for use categories by upper or lower case letters regardless of the case used on the original category. 

We should be able to type any variant of the category to find and use it from our category list. For example, if the category name is "Festival" then I should be able to find and add it by entering any version:
festival, Festival, FESTIVAL, fEsTiVaL.

Currently we can only enter the all-lowercase version of the word "festival" to get the result. This is confusing to our users, especially when their actual category name has a capital letter (like "Festival") already in it.

**Screenshots**
Screenshots are inline, above.

**Extra information:**
This only occurs with categories in Gutenberg, I could not replicate the problem with tags.

**Additional context**
This problem was originally reported and confirmed on 9351413-hc. The behavior was replicated and tests were compared to Calypso on my own test site.

**Comment by designsimply** [comment]
Thank you for the report! I tested with WordPress 5.0.3 and confirmed that searching for categories in anything other than all lowercase does not work.

![13250-25s](https://user-images.githubusercontent.com/1119271/50944587-45a5a900-144e-11e9-90a6-9a0551bdca95.gif)

**Comment by slowaways** [comment]
Confirmed!

![ezgif-4-6f1ae1230ea2](https://user-images.githubusercontent.com/9668277/51002843-62f07b00-1513-11e9-867c-e5a83d7dc218.gif)

Only works if the characters are lowercase.
...
Please, add support to accented words too.
Ex.:
Searching "educacao" can return "educação"
In English it is not necessary, but it is very useful for languages that have words with accents such as Portuguese for example.

**Comment by minamoto19** [comment]
Hello.

The same issue occurs with tags and any accented string.
In a big website makes gutenberg complete unproductive tool.

Can you please point to search function that returns the list of taxonomies to help identify and fix the issue?

Kind Regards

**Comment by slowaways** [comment]
This Issue should be treated with priority!

**Comment by Robertght** [comment]
Found a case here (#11707861-hc) and confirmed it's doing this.

**Comment by gziolo** [comment]
Does #14786 fixes the issue?
