### ISSUE TITLE
Facing an issue in the new editor

### ISSUE THREAD

**Issue by sncdk** [WordPress/gutenberg#13259]
Only one single post opens in any of the post that I try to edit. 
Also, if I try to opting **New Post** the layout looks blank, but the permalink shown is of the same old post that opens for other posts.  And then I can find no option to publish or update the post.
 
![image](https://user-images.githubusercontent.com/46528381/50902810-ef326d80-1441-11e9-9415-c15519eb2c4a.png)

Attaching image for reference.
Permalink in this is shown of some old post.

**Comment by youknowriad** [comment]
Can you add more details about your setup, screenshots? errors on the console?
Did you try disabling other plugins to see if it's a conflict?

**Comment by sncdk** [comment]
> Can you add more details about your setup, screenshots? errors on the console?
> Did you try disabling other plugins to see if it's a conflict?

I have added the screenshot of the page in my same comment

**Comment by youknowriad** [comment]
Yes, this permalink there is really weird. It seems like the backend is always intializing the post with this permalink.

Do you have instructions to reproduce the issue, as I can't reproduce it by default. Also trying to disable your plugins may find a conflict with another one.

**Comment by sncdk** [comment]
what can I do in this case?
please help
I am not able to publish any new post nor update any old post

**Comment by sncdk** [comment]
> Yes, this permalink there is really weird. It seems like the backend is always intializing the post with this permalink.
> 
> Do you have instructions to reproduce the issue, as I can't reproduce it by default. Also trying to disable your plugins may find a conflict with another one.

what can I do in this case?
please help
I am not able to publish any new post nor update any old post

**Comment by youknowriad** [comment]
If it's urgent, try installing the "classic editor plugin" and use the classic editor for your post. By ideally, you should try to debug and see what's causing this. Did you try to disable your plugins one by one as I suggested?

**Comment by sncdk** [comment]
> If it's urgent, try installing the "classic editor plugin" and use the classic editor for your post. By ideally, you should try to debug and see what's causing this. Did you try to disable your plugins one by one as I suggested?

k,
will try disabling the plugins 
get back to you with the status.

**Comment by sncdk** [comment]
> If it's urgent, try installing the "classic editor plugin" and use the classic editor for your post. By ideally, you should try to debug and see what's causing this. Did you try to disable your plugins one by one as I suggested?

Yes its done.

Thanks a lot for your instant help.

**Comment by youknowriad** [comment]
Cool feel free to add hints if you found a conflicting plugin. Thanks.
