### ISSUE TITLE
Three Column Blocks

### ISSUE THREAD

**Issue by VinceGledhill** [WordPress/gutenberg#13260]
I am trying to list items in a three column block.  It will look so neat on my site.

The solution I would like is to choose how many columns I would like in my column block.  I don't see why it should be so difficult to implement in gutenberg core, given css grid.

**Describe alternatives you've considered**
Hand coding with css grid, and advanced custom fields, but it's a lot of work for simply adding one section with three columns in it.  Also considered elementor, but don't want the overhead.

**Comment by youknowriad** [comment]
It's already possible to choose how many columns to show in the columns block, you should try to select the container of the columns and check the inspector (sidebar) and you'll see the columns count control.

Try clicking between the columns to select the wrapper.

**Comment by VinceGledhill** [comment]
Thanks mate, I will give it a go.

**Comment by jorgefilipecosta** [comment]
Closing the issue as it looks like we already have a solution. If more information is needed feel free to reopen.
