### ISSUE TITLE
Freeform Block: Rename to "Classic Text" and move away from "Common" category

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1326]
Extracting from #645. The "Freeform" has caused some confusion, as being compared to the plain text block. 

Let's rename it to "Classic Text", and remove it from the set of "Common" blocks. 

See also #1249, and #1325.

**Comment by buzztone** [comment]
Is it possible to add a hover tool-tip to this particular label to help deal with the current confusion:

_Generic fallback block to handle unknown block types for users transitioning to the Gutenberg editor_

**Comment by jasmussen** [comment]
Optional (encouraged) tooltips for blocks (all blocks) seems like a good idea 👍
