### ISSUE TITLE
JavaScript Documentation Audit

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#13268]
I'm going to create this here initially, since the updates will likely come from the Gutenberg Project team, but the changes themselves are elsewhere across the WordPress Universe.

@aduth mentioned needing an audit of documentation spots with older references on how to use JavaScript within WordPress that probably could use updating post 5.0 launch.

Here are the main pages I found:

### Plugin Developer Handbook
- [JavaScript](https://developer.wordpress.org/plugins/javascript/)
- [jQuery](https://developer.wordpress.org/plugins/javascript/jquery/)
- [AJAX](https://developer.wordpress.org/plugins/javascript/ajax/)

### Theme Developer Handbook
- [JavaScript Best Practices](https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/)
- [Including CSS & JavaScript](https://developer.wordpress.org/themes/basics/including-css-javascript/)
- [The Customizer JavaScript API](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/)

### REST API Handbook
- [Client Libraries](https://developer.wordpress.org/rest-api/using-the-rest-api/client-libraries/)
- [Backbone JavaScript Client](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/)

**Comment by paaljoachim** [comment]
It looks like this issue got forgotten about.

**Comment by mkaz** [comment]
I'm going to close as I'm not sure updating all JavaScript documentation across the numerous projects is really a block editor issue.

Reviewing, it does not look like anything in the documents listed above conflict with the block editor, they are mostly outdated, but also just different ways to do things in WordPress.
