### ISSUE TITLE
List Block: Allow inline newline

### ISSUE THREAD

**Issue by v18** [WordPress/gutenberg#13279]
**Describe the bug**
When hitting `shift+enter` while inside a list block, a new list item is created. Instead, I expect a new line to be created within the same list item.

Here's a gif showing current behaviour:

![add-newline-inside-list](https://user-images.githubusercontent.com/11487924/50981807-c8b81500-14c9-11e9-99e4-680d3101189e.gif)

I was expecting to see something like this:

<img width="469" alt="newline-inside-list" src="https://user-images.githubusercontent.com/11487924/50981854-e2f1f300-14c9-11e9-8d53-34b1624ab26e.png">

This is possible to do with the paragraph block. Here's a gif showing that:

![newline-in-a-paragraph](https://user-images.githubusercontent.com/11487924/50981930-0f0d7400-14ca-11e9-81fa-20e7bd563fc8.gif)

**To Reproduce**
1. Create new list block with a few items
2. With the cursor at the end of one of the list items, hit `shift+enter`
3. See a new list item was created. Expected a new line instead.

**Comment by swissspidy** [comment]
Thanks for your report, we're already tracking this in #11215.
