### ISSUE TITLE
Button block styles throw Uncaught TypeError

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#13276]
**Describe the bug**
The button block produces the following js error when a style is added and the block is removed

> Uncaught TypeError: Cannot read property 'name' of null
>     at editor.min.js?ver=9.0.7:55

**To Reproduce**
1. Add the button block
2. In the block inspector choose a button style from the Styles panel.
3. Do not click outside of the button block. While the button block is focused/active, remove it. Use the "more options" toolbar menu and select "Remove block". 
4. See the console error

The error doesn't show if you click outside the button block before removing it. 

**Desktop (please complete the following information):**
 - Mac
 - Browser Chrome Version 71.0.3578.9

**Additional context**
- WordPress 5.0

**Comment by designsimply** [comment]
I couldn't see the problem when testing with WordPress 5.0.3 using Chrome 71.0.3578.98 on macOS 10.13.6.

![13276-10s](https://user-images.githubusercontent.com/1119271/50996651-b8129980-14df-11e9-99cb-df1985a8ec4f.gif)

I see that you mentioned you are using WP 5.0. May I ask that you update to the latest version and reply back here if you're still having trouble?

Also, if spot that I've missed something in my testing steps, let me know and I will re-open. Thank you!

**Comment by virgiliud** [comment]
@designsimply I tested on 5.0.3 as well and am getting the same error. You must select the button styles form the block's control panel, not toolbar.

**Comment by designsimply** [comment]
Aha! Thanks for catching that. I didn't realize you meant the settings sidebar when you said block inspector. I re-tested and can confirm the issue now.

![13276-14s](https://user-images.githubusercontent.com/1119271/51065829-3183b800-15c4-11e9-8b90-2a4c7414598c.gif)

<sup>Tested with WordPress 5.0.3 and no active plugins with Firefox 64.0.2 on macOS 10.13.6.</sup>

**Comment by youknowriad** [comment]
This looks like it was fixed for me.
