### ISSUE TITLE
How can I resize the Gutenberg block in case I want to design my page whether website page or landing page?

### ISSUE THREAD

**Issue by CoderGeek700** [WordPress/gutenberg#13277]
How can I resize the Gutenberg block in case I want to design my page whether website page or landing page?

I found difficulty to resize the bock because I am expecting to be like the page builder platform ...

please help us to improve this feature. Further when I complete design my block page in Gutenberg I found in preview mode different design and it should be align with editor. Otherwise that will be very very difficult to Wordpress Users to design their pages. I hope if you could apply like Elementor platform.

**Comment by designsimply** [comment]
If you are asking how to resize the main column width of the editor, you may do that by following the instruction at https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#changing-the-width-of-the-editor (make sure you have also [opted in to editor styles](https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#editor-styles)).

If that is not what you meant, please reply with a note and I will re-open this issue. Thanks!
