### ISSUE TITLE
Why Gutenberg Page Editor Not Aligin With Preview Page !!!

### ISSUE THREAD

**Issue by CoderGeek700** [WordPress/gutenberg#13278]
Why Gutenberg Page Editor Not Aligin With Preview Page !!!

Any user expecting to see his preview page as similar with Gutenberg Editor but in fact it's different !

I hope from WordPress team to put more efforts in that area because it's critical for any user want to design his page professionally 

Please let us know once that feature will apply in next version of wordpress.

LOVE WORDPRESS

**Comment by swissspidy** [comment]
Hi there

Could you please let us know what exactly is not OK with the preview? Are you saying the changes you made aren't reflected in the front end when you click Preview? Or is there a layout/styling issue?

**Comment by CoderGeek700** [comment]
Hi swissspidy, 

Thanks for the prompt feedback,

I am saying the layout styling issue

because if I design any shape in Gutenberg Editor mode that will not show me in the preview mode as identical place of my shape which is very important thing for any user who wants to build his landing page or home page 

I believe Gutenberg will be robust in future if he apply all the features that other page builder platform such as: Elementor , Beaver Builder , Divi Builder & Thrive Architect

I believe Gutenberg can handle all these small things features because why we need to use these software while WordPress ( Number one source of Content Page builder )

I can see WordPress now shifting to improve their styling features not like in the past which let the page builders platform take their market and get all the advantages 

In my opinion, the main goal of WordPress to make the user have good experience to put his content easier and to design it professionally.

**Comment by youknowriad** [comment]
I'm going to close this issue right as there's no actionable items here. Yes Gutenberg is meant to be WYSIWYG but the theme is also responsible in applying the editor styles to make it happen 100%.

If there's any particular point we should improve, please open separate issues.
