### ISSUE TITLE
The text in Cover

### ISSUE THREAD

**Issue by iamtomblack** [WordPress/gutenberg#13285]
The default color of the Title in "Cover" is white,while I have a White-Style picture.That's display unfriendly.

**Comment by designsimply** [comment]
A request for the option to change text color for all text-based blocks, including the Cover block, is being tracked at #8171. Thank you for the request @iamtomblack !

**Comment by iamtomblack** [comment]
Today I have found another problem，after I embeded a sound player，in Firefox、Edge，It works fine，but in Chrome and Opera，it doesn’t work。
[cid:image003.png@01D4AA92.99BF8680]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Sheri Bigelow <notifications@github.com>
发送时间: Saturday, January 12, 2019 5:09:21 AM
收件人: WordPress/gutenberg
抄送: iamtomblack; Mention
主题: Re: [WordPress/gutenberg] The text in Cover (#13285)


A request for the option to change text color for all text-based blocks, including the Cover block, is being tracked at #8171<https://github.com/WordPress/gutenberg/issues/8171>. Thank you for the request @iamtomblack<https://github.com/iamtomblack> !

―

**Comment by designsimply** [comment]
@iamtomblack will you please create a separate issue for the sound player embed and include a short list of steps to replicate the problem and also mention which version of WordPress you are testing with? Thank you!
