### ISSUE TITLE
How to change color for specific words inside body content in Gutenberg !!!

### ISSUE THREAD

**Issue by CoderGeek700** [WordPress/gutenberg#13286]
How to change color for specific words inside body content in Gutenberg !!

the only option appear to change the color for whole block which is fine but when I was trying to change specific words in body content then I face difficulty as user of WordPress.

Please let us know if you could tackle that issue and make it one of the option to be easier to them

**Comment by talldan** [comment]
Hi - this isn't supported normally within the editor, but there is a plugin that adds this and other useful functionality:
https://wordpress.org/plugins/advanced-rich-text-tools/

**Comment by CoderGeek700** [comment]
Thanks Daniel Richards 

Really you help me a lot. That's amazing plugin.
