### ISSUE TITLE
font-size is not reflected in my OceanWP theme by using Gutenberg ! 

### ISSUE THREAD

**Issue by CoderGeek700** [WordPress/gutenberg#13287]
font-size is not reflected in my OceanWP theme by using Gutenberg ! 

I was trying to increase the font-size in my header by customize it through HTML Gutenberg but I found it's not update it in the preview mode?

Kindly update it in the next version of WordPress...

LOVE WordPress

**Comment by youknowriad** [comment]
Hi there!

This seems like a theme bug to me, is theme forcing the font size (using !important or similar)?

Thanks.

**Comment by youknowriad** [comment]
Closing as stale, let's reopen if there's are reproducible steps.
