### ISSUE TITLE
How can i build an frontend app with React using WordPress Components?

### ISSUE THREAD

**Issue by lievikoff** [WordPress/gutenberg#13283]
I am building a plugin that has datepickers, switchers, the wp editor at frontend. I can make such app in pure React JS. What would the best way to make it in scope of WordPress? Should i use the react wrapper in wp.element instead of connecting React JS as a package? How can i reuse styled WordPress components in frontend? What is the new way of using php function wp_editor()?

**Comment by youknowriad** [comment]
Regarding `wp_editor. There's no way to use Gutenberg this way at the moment, but you can build alternative editors using the reusable components from Gutenberg (The edit-post could be considered just one implementation of a post editor to take inspiration from).

Also, there's some on going work making this kind of usage easier (see #13088 )

Thanks for your questions.
