### ISSUE TITLE
Support <!--noteaser-->

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1329]
`get_the_content()` looks for `<!--noteaser-->` in the post content to see if the teaser before a `<!--more-->` should be displayed or not.

This probably needs to be supported as well to maintain BC. It has been in WordPress for many years.

[The Codex says](https://codex.wordpress.org/Customizing_the_Read_More#Read_More_Techniques) that `<!--noteaser-->` needs to immediately follow `<!--more-->` in the post content, otherwise it would not work. However, looking at `get_the_content()` doesn't validate this. It's a simple `strpos()` search. This means `<!--noteaser-->` can be anywhere. Of course there are no tests in WordPress for that...

See #983.

**Comment by swissspidy** [comment]
Perhaps this could be integrated as an on attribute in the `More` block? This would just require a way to set this attribute for existing content, i.e. remove `<!--noteaser-->` from the content if available and set the attribute.

**Comment by mtias** [comment]
Done.
