### ISSUE TITLE
HTML-tags of newly registered formats disappear when pasting

### ISSUE THREAD

**Issue by websupporter** [WordPress/gutenberg#13292]
**Describe the bug**
I registered a new format type. Lets say: `<span class="great-class">`. When I copy a text now into the Component, the `span.great-class` tags get removed:

```
Received HTML:
df df <span class="great-class">df</span> df df. editor.min.js:55:146144
Received plain text:
df df df df df. editor.min.js:55:146187
Processed inline HTML:
df df df df df. blocks.min.js:2:115611
```

**To Reproduce**

```
const {createElement} = window.wp.element;
const {registerFormatType, toggleFormat} = window.wp.richText;
const {RichTextToolbarButton} = window.wp.editor;

registerFormatType('some/type', {
    title: 'Title',
    tagName: 'span',
    className: 'great-class',
    edit({ isActive, value, onChange}) {
        const onClick = () => {
            onChange(toggleFormat(value, { type: 'some/type' }));
        };

        return (
            createElement(RichTextToolbarButton, {
                icon: 'admin-home',
                title: 'Title',
                onClick,
                isActive,
                shortcutType: 'primary',
                shortcutCharacter: '8',
            })
        )
    }
});
```
1. Add this script
2. Add a text in a RichText component
3. Select a part of the text and click the new button in the toolbar
4. Copy all the text in the clipboard
5. Paste the text in a RichText component

**Expected behavior**
The new format should survive the copy/pasting

**Screenshots**
https://www.youtube.com/watch?v=9SiyAROa1Iw

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04
 - Browser Firefox

**Comment by websupporter** [comment]
I suspect, this could be fixed with by expanding the list returned by `getPhrasingContentSchema()` with the types we get from  `wp.data.select('core/rich-text').getFormatTypes()`

https://github.com/WordPress/gutenberg/blob/a92216bb6f46a99712aef6124e5cf1a2ea6384a2/packages/blocks/src/api/raw-handling/phrasing-content.js#L35

**Comment by skorasaurus** [comment]
Thanks for reporting; I'm not able to reproduce this using your example; nor in my custom example of a custom richtext format. 

Looks like this was fixed a while back in https://github.com/WordPress/gutenberg/pull/27967 (ref https://github.com/WordPress/gutenberg/issues/16240)

**Comment by websupporter** [comment]
Amazing. Thanks for following up @skorasaurus
