### ISSUE TITLE
Instagram & Soundcloud embeds not responsive

### ISSUE THREAD

**Issue by markman641** [WordPress/gutenberg#13295]
Hello, I noticed today that embeds are not responsive for Instagram & Soundcloud embeds.
The width is too wide and breaks my responsive website. Embedding the direct code from Instagram works fine, but the built in embed where you just paste the link causes overflow

there may be more embeds that aren't working but these are the two that I noticed.

**Comment by designsimply** [comment]
Themes must opt-in to responsive embeds. Please make sure you have followed the instructions at https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#responsive-embedded-content

If you have already done that and it is still not working, please reply back here and let me know and I can re-open! Please include details about your theme (i.e. is it avail. for download/testing?).

**Comment by designsimply** [comment]
It's possible it's a conflict from the theme for the Gutenberg editor only. Let us know what you find!

**Comment by markman641** [comment]
I have updated my theme and there are still issues.
I have narrowed down the issue to the cause:

When I embed Instagram, by default there is "no alignment", and either my theme or gutenberg aligns that embed too far over to the right and therefore overflows. I set it to align center and the instagram issue went away. Still a strange bug that only started with gutenberg. Definitely would like a fix for this so it doesn't keep happening if someone forgets to align center.

I'm pretty sure Soundcloud embeds have never worked on my theme, so I suppose that has nothing to do with Gutenberg

**Comment by notnownikki** [comment]
I've double checked the responsiveness of Soundcloud and Instagram on the latest Gutenberg code with the Twentynineteen theme, and all seems fine, so this would seem to be specific to the Steam theme. However, that theme isn't listed as WordPress 5.0 compatible, so there's probably more work the theme authors need to do for it to be able to use Gutenberg's responsive styles and alignments properly. I can't find anything in the industrial themes portal about 5.0 or Gutenberg, but if you can forward this ticket to them I'm sure we can point them in the right direction.

**Comment by designsimply** [comment]
Thank you for checking that @notnownikki !

@markman641, I am closing with a note to please check with the theme author since the issue appears to be related to how Gutenberg styles are different and the theme may need to adjust for that. Please point them to https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#responsive-embedded-content in case the Handbook content about responsive embeds is helpful. Thank you!
