### ISSUE TITLE
Improve Parser backward compatibility

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#13310]
**Describe the bug**

The regular expression that the PHP parser uses the `(?<name>pattern)` syntax to create named subpatterns. This syntax was [introduced in PHP 5.2.2](https://secure.php.net/manual/en/regexp.reference.subpatterns.php).

https://github.com/WordPress/gutenberg/blob/ddac4f3cf8fd311169c7e125411343a437bdbb5a/packages/block-serialization-default-parser/parser.php#L376-L382

Strictly speaking, however, the syntax was introduced in PCRE 7.0, which is the default version of PCRE built into PHP 5.2.2, but some Linux distros (Centos 5 is a known example) use an older PCRE. In the case of Centos 5, they use PCRE 6.6.

In core (as well as in other places in Gutenberg), we've avoided this problem by using the older `(?P<name>pattern)` syntax.

I'd like to get this fixed in WordPress 5.1.

Ref: https://core.trac.wordpress.org/ticket/45644

**Comment by mcsf** [comment]
Thanks for surfacing and providing context.
