### ISSUE TITLE
Improve how to select a parent block that has nested blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#13319]
**PROBLEM**
When block nest inside each other, the parent block becomes difficult to select.

![parent-clicking-2](https://user-images.githubusercontent.com/617986/51138792-e6052000-17f6-11e9-9807-a83bd2fc39c2.gif)

**SOLUTION**
Design a solution that allows easier selecting of the parent block.
Ideas:
1. When a block becomes a parent block with nested blocks inside, does it increase visually with padding?
2. Use a double-click method that allows one to click down into or up out of nested blocks.
3. Other ideas?

**Comment by paaljoachim** [comment]
I would suggest to create a thin outline of the block that is active. Then a very thin outline of the parent block. It will then show the relation between the two. Labels should also be clickable.
For instance a label that says Column (parent) -> Paragraph (child). Click the Column word to select the parent column. Click Paragraph word to select the child block.  

Btw we can also use various border colors for standard blocks, global and reusable to create a visual difference between them. One would then associate a color with a type of block.

I have some ideas here: https://github.com/WordPress/gutenberg/issues/12515

**Comment by mapk** [comment]
Looks like this is a duplicate of #9628. I'm closing this one.
