### ISSUE TITLE
Image title attribute

### ISSUE THREAD

**Issue by Markmcl** [WordPress/gutenberg#13311]
The ability to enter or edit an Image Title Attribute is missing in the Gutenberg image block.

Do not confuse this with either the Image Title or Alternative Text.
This problem is well described at https://wordpress.org/support/topic/gutenberg-image-block-missing-image-title-attribute-field/

**Comment by Soean** [comment]
We already have an open issue about this missing feature #11054, so I am ging to close this one as a duplicate.

**Comment by Markmcl** [comment]
I disagree, the only place " Image Title Attribute" is mentioned, (pardon me if I have misread, but I don't think I have) in #11054 is in the second last para from bmeachamand  and perhaps the last para and are clearly not what the rest of the posts on that page are about.

That issue is clearly entitled "Image block: allow for editing image title " and I say in my second line above "Do not confuse this with either the Image Title or Alternative Text." which is what the other issue is about.
Could you please change this back to "open"
My issue is to restate it
"**The ability to enter or edit an Image Title Attribute** is missing in the Gutenberg image block."

**Comment by Markmcl** [comment]
yes, & your link led to some interesting reading at https://inclusive-components.design/tooltips-toggletips/
which makes me think perhaps Title Attributes should be left when you think about the associated accessibility problems.
Care is needed and attention paid to his conclusions and checklist at the end of the article if they were to be implemented.

I have always set title attributes on menu items to give a tooltip on hover without thinking about accessibility and was  worried tooltips would not be available when menus are converted to blocks, but when you read that article perhaps they just are not needed.

**Comment by FinnJackson** [comment]
Please restore 'Image Title Attribute' in the Gutenberg editor
