### ISSUE TITLE
Meta box falls over editor (IE11)

### ISSUE THREAD

**Issue by jeffreyvr** [WordPress/gutenberg#13328]
**Describe the bug**
When editing a long post, the meta boxes are positioned over the content in IE11. 

**To Reproduce**
1. Create a new post with a large amount text
2. Have at least one meta box at the bottom of your screen
3. Scroll down

**Expected behavior**
The meta boxes should be at the bottom of the page, not positioned over the content.

**Screenshots**
![schermafbeelding 2019-01-15 om 12 13 57](https://user-images.githubusercontent.com/9550079/51177360-abb38580-18bf-11e9-806f-bbdf61c8b3cb.png)
Using the classic editor block

![schermafbeelding 2019-01-15 om 12 14 55](https://user-images.githubusercontent.com/9550079/51177388-b9690b00-18bf-11e9-977e-c17e657efd9e.png)
Using normal paragraph blocks.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser internet explorer
 - Version 11

**Additional context**
- WordPress version 5.0.3
- Working as expected in other browser (google chrome, safari, firefox)

**Comment by youknowriad** [comment]
This could be related to PHP warnings/notices appearing on the page (but hidden by other elements). This is not the only reason though. The fact is your browser is in "quirks mode" making the CSS behave weirdly.

See the discussion in this thread for more details. https://github.com/WordPress/gutenberg/issues/11378

Thanks.
