### ISSUE TITLE
Permalink is uneditable for custom post types

### ISSUE THREAD

**Issue by andyicelab** [WordPress/gutenberg#13336]
**Describe the bug**
Permalinks for custom post types should be editable by hovering over the `title` block or by using the document menu.

**To Reproduce**
1. Register a custom post type.
2. Enable the Gutenberg editor by setting `show_in_rest` to `true`.
3. Ensure the editor is supported by adding `editor` to the `supports` array.
4. Ensure the `Permalink` option is ticked in the `Options` menu.
5. Create a post.

**Expected behavior**
The permalink should be editable, however no option to edit is available.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 71.0.3578.98

**Additional context**
- Tested on WordPress 5.0.0. through to 5.0.3.

**Comment by swissspidy** [comment]
Can you please share the code you are using to register the custom post type? Post types would need to be public in order to even have permalinks.

**Comment by andyicelab** [comment]
Thanks @swissspidy! That was the issue. I had `public` set to `true` but `publicly_queryable` set to `false`. Adjusting that value enabled the permalink configuration controls.
