### ISSUE TITLE
Media & Text Block - Float Text around image

### ISSUE THREAD

**Issue by landwire** [WordPress/gutenberg#13340]
**Describe the solution you'd like**
I would like to have the option to let the text float around the image on the media & text block.

**Comment by getdave** [comment]
@landwire Thanks for your idea. The first question that came to my mind was can this not be solved using the standard paragraph block and inserting an image into that?

**Comment by skorasaurus** [comment]
@getdave 
That's what we've done so far: applying the align left or right to the image; and it's worked for us;.

**Comment by paaljoachim** [comment]
I am doing a status update to how the Media & Text block works today.

With using the Vertical Alignment to align top it looks like this.

<img width="1000" alt="Screen Shot 2021-02-08 at 20 53 05" src="https://user-images.githubusercontent.com/5323259/107273771-cd0bdf00-6a4f-11eb-8fef-990d7787d503.png">

Wrapping the text below the image or above if using a Vertical Alignment to Align to middle seems interesting.
I am not sure if we should do so with this block, but it could help with the design in being able to wrap text around the image.

@jasmussen and @ItsJonQ

**Comment by jasmussen** [comment]
Good thoughts on this thread. My instinct is also that a floated image and a paragraph, perhaps inside a group if you need to, is a good solution to this. If I missed something here, we can always reopen if new information comes to light!
