### ISSUE TITLE
Reduce color palette options for button block

### ISSUE THREAD

**Issue by billerickson** [WordPress/gutenberg#13341]
I'd love the ability to restrict the button block's color options for background color / text color to a subset of the editor-color-palette.

We typically have 6-10 colors in our editor-color-palette, but want 2-3 button variations.

Is it possible to reduce the color options on a per-block-type basis?

**Comment by samhermes** [comment]
Would love to see this as well, for the same reason.

**Comment by buhlahkay** [comment]
Would like to see this on all blocks as @billerickson mentions. Or even the ability to remove the "Color Settings" tab completely from certain blocks.

**Comment by carasmo** [comment]
There ought to be some kind of filter(s) to allow background colors for certain blocks and not allow them for others as well as what Mr. Erickson wrote.

**Comment by reedcodes** [comment]
We have a similar situation. Two main brand colors, four secondary, five tertiary. We only want to use five colors on the buttons, two on the alerts, eight on the callouts, etc.

**Comment by youknowriad** [comment]
We're working on a way to control the presets per block in #20588

**Comment by mtias** [comment]
This is now possible via `theme.json`, closing as done.

**Comment by ellenbauer** [comment]
Could someone kindly hint me to how I can get this done via theme.json. Is there another ticket or other form of documentation already available? That would be awesome, thanks so much.

**Comment by carasmo** [comment]
theme.json is supported in 5.8, set to be released in about 6-7 days. I'm testing the [5.8 release](https://wordpress.org/news/2021/07/wordpress-5-8-release-candidate-2/). I made a theme.json file with my text editor, then I copied out the code from the [settings section in the docs](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/theme-json.md#settings). This goes in the root of your theme. 

Change the dropCap section to false. 

theme.json

    {
	"version": 1,
	"settings": {
		"color": {
			"custom": true,
			"customDuotone": true,
			"customGradient": true,
			"duotone": [],
			"gradients": [],
			"link": false,
			"palette": []
		},
		"custom": {},
		"layout": {
			"contentSize": "800px",
			"wideSize": "1000px"
		},
		"spacing": {
			"customMargin": false,
			"customPadding": false,
			"units": [ "px", "em", "rem", "vh", "vw" ]
		},
		"typography": {
			"customFontSize": true,
			"customLineHeight": false,
			"dropCap": true,
			"fontSizes": []
		},
		"blocks": {
			"core/paragraph": {
				"color": {},
				"custom": {},
				"layout": {},
				"spacing": {},
				"typography": {}
			},
			"core/heading": {},
			"etc": {}
		}
	  }
    }

**Comment by mtias** [comment]
@ellenbauer sure thing! You can set a custom color palette just for the button block like this:

```json
{
  "settings": {
    "core/button": {
      "color": {
        "palette": []
      }
    }
  } 
}
```

**Comment by oandregal** [comment]
Added this as an example at https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings-examples

**Comment by ellenbauer** [comment]
Awesome, thank you so much @mtias for pointing me into the right direction. That is such a helpful add-on to be able to customize the color palette per block.
Also thank you @nosolosw for updating the documentation.

**Comment by mtias** [comment]
Agreed! It's a large part of what makes the addition of theme.json worth it, since it scales to any block, including third-party ones as long as it uses the block supports APIs, and should offer a lot of flexibility for site maintainers and themes.
