### ISSUE TITLE
Feature: a blank normal paragraph should be convertible to separator

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#13346]
![screenshot 2019-01-16 at 18 20 01](https://user-images.githubusercontent.com/4389/51269832-61afca00-19bb-11e9-9234-ac7ba5192546.png)

If the paragraph is blank, it should be possible to convert it to a separator block.

Maybe in context to #8970.

**Comment by swissspidy** [comment]
@youknowriad What about adding a transform without context awareness in the meantime?

**Comment by youknowriad** [comment]
Maybe, it does feel weird to transform a paragraph with content to a separator, why not any block in that case because, you'd just lose the content and get a new different block?

**Comment by ghost** [comment]
The paragraph block is now the entry for any block, so you can just type something like `/sep` to enter the separator. Also, the toolbar doesn't show unless there's content in the paragraph block. So closing this one for now. :)
