### ISSUE TITLE
how to disable author selection?

### ISSUE THREAD

**Issue by mustafauysal** [WordPress/gutenberg#13356]
Hi, 

What is the right way to disable author selection?

<img width="409" alt="screen shot 2019-01-17 at 14 10 14" src="https://user-images.githubusercontent.com/1421387/51314831-ccb3dc00-1a61-11e9-99b0-079ab7ebf6ec.png">

The select box for the author is available when the REST API grabs all users and, this is a problematic situation for collaborative websites on a large scale. 

(This is a chronic problem indeed, but we were able to replace author meta boxes with something like autocomplete boxes on the classic editor before.)

Populating users for the reproduce:

```
wp user generate --role=author --count=20000
```

Something like [authors-autocomplete-meta-box](https://github.com/bamadesigner/authors-autocomplete-meta-box) can be workaround for choosing the author

**Comment by Soean** [comment]
There is an open pull request to solve the problem with a large number of users: https://github.com/WordPress/gutenberg/pull/7385

**Comment by mustafauysal** [comment]
@Soean thanks for referencing #7385

I'm not sure it's the proper way but removing the `users` endpoint helps anyway. 
```
add_filter( 'rest_endpoints', function ( $endpoints ) {
	if ( isset( $endpoints['/wp/v2/users'] ) ) {
		unset( $endpoints['/wp/v2/users'] );
	}

	return $endpoints;
} );
```
(for the people who want to disable author selection)


closing the issue, eyes on #7385
