### ISSUE TITLE
Component panel titles are hard to click

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#1335]
I think because the sidebar UI visually resembles an old-school accordion, I'm conditioned to think the entire rectangle area (used to roll open a panel) should be clickable.

Currently, the component panel titles are only as tall as the text, and do not fill the padded area.

I propose we bulk-up the `.components-icon-button` to cover the padded area. This would result in no visual changes, but increase the targetable area of each title button by `15px` in each direction.

Going to try to submit a pull-request for this shortly.

**Comment by jasmussen** [comment]
🌟🌟

Great ticket, great suggestion.

**Comment by JJJ** [comment]
Really sorry for the PR noise. :speaking:

**Comment by jwold** [comment]
This is great, adding the padding around will increase the click targets. Didn't even realize this was a problem until it was called out, but now I can't unsee it :)
