### ISSUE TITLE
Code examples in the Gutenberg Developer Handbook

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#13365]
Is there any reason why some code examples in the developer handbook are available in ES5 and ES6 and others just in ES5? Personally, I think ALL code examples should be in ES5 and ES6.

**Comment by youknowriad** [comment]
Thanks for raising this.

Ideally, all code examples should be in both, If you want to add the missing ones, please open PRs. This would be greatly appreciated.

I'm going to close this issue as it's a generic issue.
