### ISSUE TITLE
Two column blocks doesn't appear

### ISSUE THREAD

**Issue by Auto-Reverse** [WordPress/gutenberg#13360]
Hello everyone!

I have just published my first post with Gutenberg. I am using Wordpress 5.03 fr on a Valenti theme.
Yesterday, everything was working perfectly. Today, my column blocks doesn't appear normaly: When reading the post, we can see that there is a diference beetwen right columns and left columns, but thay don't appear as they should. Anyone has ever encountered this problem?

This is the post:
https://www.auto-reverse.com/la-land-rover-s2-est-une-legende/

I have been trying it on Chrome, Firefox and Edge, on Windows 10 and Chrome and Safari on Mac OS with the same problem...

**Comment by garywoodfine** [comment]
Got the same issue!
a few days ago the post that was using wp-block-columns was working fine. However, it seems the block is now no longer working. When in the editor it appears to indicate that it should be working.

The user experience in using the block is quite a terrible one if I'm honest

**Comment by amylarose** [comment]
I am having the same issue. I tried deactivating plugins to no effect.  My columns were working prior to updating to the new wordpress vers. 5.0.3 that includes Gutenberg sans having to use the plugin, however now they will not display properly. I tried re-adding the content and creating new columns but this did not work either. I am OSx El Capitan, browser Chrome and Firefox.

See the issue at www.festiVOL.com/festiVOL-certified

Any help is much appreciated!

**Comment by Soean** [comment]
@amylarose You site is including some styles which should only be loading in the editor like `wp-nux-css` or `wp-editor-css`, not in the frontend.

**Comment by amylarose** [comment]
@Soren - I am afraid I am not well versed enough to understand what I
should do about this. Do I just add these styles in the Editor in CSS
Stylesheet?  Where do I remove them from the frontend? I am very new to
website building and the site I have shared was originally created for me,
although I have made some changes to it.  Thank you for your help!

@GlennMartin - you nailed it!!! I was indeed using the WooCommerce Blocks
and they did indeed need an update, and upon updating, my columns are
aligned. Thank you for figuring this out for me - I may never have landed
on the answer on my own :)

**Comment by Soean** [comment]
Looks like WooCommerce blocks was the problem. The linked URLs look good, so I close this issue. If you have still a problem with this issue, feel free to reopen it or comment here.

**Comment by GlennMartin1** [comment]
Here's some context: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/345

**Comment by amylarose** [comment]
Excellent - I so appreciate it!
