### ISSUE TITLE
Image quality varies

### ISSUE THREAD

**Issue by svnsbck** [WordPress/gutenberg#13379]
I experience different image qualities in editor and published post. `Alignwide` images are sharp in the editor and merely upscaled in the browser, hence blurry. I noticed that images in the editor have an added `&zoom=2` in the editor but not on post, hence I guess the blurriness.

Steps to reproduce: add an image in alignwide in editor.

The above behaviour would be in Gutenberg on wp.com.

**Comment by swissspidy** [comment]
> I noticed that images in the editor have an added `&zoom=2` in the editor but not on post, hence I guess the blurriness.

That is not something WordPress/Gutenberg adds by default, so I believe this is a WordPress.com-specific issue that should be reported to them.
