### ISSUE TITLE
One web portal with Gutenberg Tweaks & Snippets & Tips

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#13372]
I would like to suggest to you core developers to register one official website with snippets and tutorials for Gutenberg.
I know it is not conventional, but not it is Gutenberg either.

Something like WP Tavern portal, but this time only for Gutenberg related things. People can send own code snippets, tips. You can verify code and publish it. You too can publish snippets, tweaks.

You can give Publisher role to some well known WP developers.

Not so conventional, as I said. But not is Gutenberg either.

Additional you can ofer monthly, or yearly, only Posts tables export from database. For developers who like to make own collection of snippets, tutorials and mix your and own. Not for public view and Google Ads, but internal and private use. This one is dependent of GDPR, so do not know exactly.

And try to stay away from News in Portal. 
Many developers would turn to this portal for inspiration, learning. Just to read it.

I know there will be websites like this, but if it officially comes from you it would be revolutionary.

**Comment by Soean** [comment]
The block editor is now a part of WordPress Core and the Gutenberg Plugin in an official project. We don't need a new portal, we already have some good sites:

We have the Gutenberg [handbook](https://wordpress.org/gutenberg/handbook) with a growing [tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/) section.
We also have the [plugin](https://developer.wordpress.org/plugins/) and [theme](https://developer.wordpress.org/themes/) developer handbook, where we should add content about the new features.

What we need is more and better documentation, examples & tutorials and some design tweaks for the representation and navigation, not a new portal.
