### ISSUE TITLE
Switching From Classic to Gutenberg Changes Status From "Private" to "Public"

### ISSUE THREAD

**Issue by sdixon194** [WordPress/gutenberg#13374]
**Describe the bug**

When editing a post in the classic editor, scheduling the post and changing the visibility settings to "Admins and Editors", this status is changed to "Private" when switching to Gutenberg and making a change. 

**To Reproduce**

1. Create a post using the classic editor.
2. Set to Admins & Editors
3. Schedule the post
4. Switch to the new block editor
5. Make any changes and update the post
6. The status changes from "private" to "public"

**Expected behavior**

The post to stay "Private"

**Screenshots**

Screenshare shared by user: http://cld.wthms.co/poeblz

**Additional context**

Potentially related: https://github.com/WordPress/gutenberg/issues/9396

**Comment by pauljacobson** [comment]
To add to this, the issue seems to occur on both a free site, and a site on a WordPress.com Personal plan on WordPress.com.

Our reference over at WordPress.com is 1724358-zen.

**Comment by separatelyunited** [comment]
Just checking in on this one as we have not been able to give any update to the user.

**Comment by jburciaga0** [comment]
Checking in here again. I have let the user who originally reported this know that the best thing to do would be to switch back to the Classic editor in the meantime while a fix is worked on here.

**Comment by jorgefilipecosta** [comment]
I was able to verify the problem in the last version of Gutenberg 5.8. I'm adding the Hight priority label, as this problem may make users unintentionally expose data.
