### ISSUE TITLE
Enter key in Gutenberg editor don't create <CR>

### ISSUE THREAD

**Issue by sdugoten** [WordPress/gutenberg#13381]
Basically, in the classic editor when you press enter key when you are editing a post, you will see a new line is created in the output.  Using the Gutenberg editor, no matter how many enter key you press in the edit post page, the output don't show any new line created.

You can visually see there is "enter key" press when you are editing page.
 
![8kiseg](https://user-images.githubusercontent.com/7108552/51437029-ef98f700-1cd2-11e9-91f0-6ed931046785.jpg)

When you actually view the page, there is no enter key inbetween those 2 words

 
![3pepje](https://user-images.githubusercontent.com/7108552/51437031-fde71300-1cd2-11e9-9001-53be7d73027d.jpg)

**Comment by paaljoachim** [comment]
Hi @sdugoten 

Thank you for creating this issue!
Some time has passed.
Is this issue still valid?

**Comment by jordesign** [comment]
As there's been no follow up here in over 2 years - I'm going to close this issue. If the issue _is_ still present in newer versions of WordPress - please feel free to reopen.
