### ISSUE TITLE
Blog overview looks weird because of more tag Gutenberg

### ISSUE THREAD

**Issue by Schanulleke** [WordPress/gutenberg#13392]
Hi,

I'm new here with a question about the more tag in Gutenberg, I found a thread about text alignment for the more tag, but nothing about the problem I have.

In the classic editor the more tag was part of the paragraph. Now, I get automatically a white line, and I don't really like it. What can I do to get the more tag into the 1st paragraph (how it was in the classic editor)?

In my css and php-files I can't find anything. 

I have a work-around. I put in the html of the 1st paragraph this: 

This works, although I get an error about unexpected content. But I don't like error messages for the long term. I'd rather had a more elegant solution ;-) 

Anybody here? Thanks in advance. Jessie

**Comment by youknowriad** [comment]
A solution for this is to use the "classic" block for the paragraph containing the more tag.

Feedback noted though and if comes up more regularly we could consider adding a "more" shortcut to the paragraph block.

Thanks.
