### ISSUE TITLE
Update `node.patch` and `openssl.patch` patch files

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#13393]
**Describe the bug**

Currently two patch files are used to facilitate custom build jobs on Travis CI:
• https://github.com/WordPress/gutenberg/blob/master/bin/patches/node.patch
• https://github.com/WordPress/gutenberg/blob/master/bin/patches/openssl.patch

These two files require updating as they are currently only _just_ applying cleanly:

```shell
===> Applying patch file from /home/travis/build/WordPress/gutenberg/bin/patches/node.patch ...
patching file ext/dom/node.c
Hunk #1 succeeded at 1950 (offset 55 lines).
patching file ext/dom/documenttype.c
Hunk #1 succeeded at 215 (offset 10 lines).
patching file ext/simplexml/simplexml.c
Hunk #1 succeeded at 1343 (offset -74 lines).
===> Applying patch file from /home/travis/build/WordPress/gutenberg/bin/patches/openssl.patch ...
patching file ext/openssl/xp_ssl.c
Hunk #1 succeeded at 332 (offset 4 lines).
Hunk #2 succeeded at 354 (offset 4 lines).
Hunk #3 succeeded at 583 (offset -50 lines).
Hunk #4 succeeded at 819 (offset -98 lines).

```

**To Reproduce**

The patches are applied during the execution of the [`install-php-phpunit.sh`](https://github.com/WordPress/gutenberg/blob/master/bin/install-php-phpunit.sh) script.

**Expected behavior**

By updating the patches to apply _cleanly_ and removing the `Hunk #xyz ...` warnings it will remove the potential for the `install-php-phpunit.sh` script to fail if the patches continue to diverge from the current code.

**Comment by gziolo** [comment]
@notnownikki, can you explain how those 2 files were originally added so we could have a better idea how to resolve this issue?

**Comment by notnownikki** [comment]
These shouldn't be diverging now, as these are only used to build php 5.3/5.2 and there will be no further php 5.3 or 5.2 releases, and haven't been since 2014. They were originally compiled from various bug reports where people were trying to build these versions on Ubuntu Trusty, if I remember correctly. Likely, they haven't been applying _cleanly_ since we first started using them, but they applied and worked so I probably didn't pay too much attention, again because there will never be another 5.3 or 5.2 release of PHP.

I did try to find the original bug reports that the patches were compiled from, but frustratingly I only found github issues where people were trying to use phpbrew on Ubuntu and couldn't build 5.3/5.2, and commenters pointed them to this repo to show them how we'd got it working :grin:

**Comment by ntwb** [comment]
FYI: This was more about refreshing the patch, rather than any update to functionality supplied by the patch, primarily so that the patches would apply cleanly and thus avoiding `Hunk #4 succeeded at 819 (offset -98 lines).` issues before they got further out of date and would no longer apply at all.

Though, now that WordPress core has stopped testing PHP 5.2 & 5.3 on Travis CI we could also drop testing Gutenberg on PHP 5.2 and 5.3 also.

**Comment by gziolo** [comment]
> Though, now that WordPress core has stopped testing PHP 5.2 & 5.3 on Travis CI we could also drop testing Gutenberg on PHP 5.2 and 5.3 also.

I share the same sentiment :) Should we close this issue and open a follow-up where we bump minimum version to PHP 5.6 and remove all logic related to previous versions altogether?

Are there any `phpcs` rule updates ready as well? /cc @pento

**Comment by notnownikki** [comment]
> FYI: This was more about refreshing the patch [...] before they got further out of date and would no longer apply at all.

Yes, although the code they're patching will never, ever be updated. I think we're pretty sure at this point that PHP 5.3 isn't going to get any more releases :)

> Though, now that WordPress core has stopped testing PHP 5.2 & 5.3 on Travis CI we could also drop testing Gutenberg on PHP 5.2 and 5.3 also.

:100: yes, I'd do a little dance of happiness if this happened. I can prepare a PR that removes all the build logic and jobs in anticipation!

**Comment by gziolo** [comment]
WordPress no longer supports PHP 5.2 nor 5.3.

**Comment by gziolo** [comment]
Opened an issue to remove support for PHP 5.2 and 5.3: #15796.
