### ISSUE TITLE
Thumbs in gallery not linking to full images

### ISSUE THREAD

**Issue by srikat** [WordPress/gutenberg#13398]
Hello,

I added a gallery with the thumbs linking to their corresponding images.

In the front end, thumbs are linking to corresponding `large` size images, but not the full resolution ones.

Ex.:

```
<a href="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg"><img src="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg" alt="" data-id="56" data-link="https://demo2.ebadvisormarketing.com/homepage-gutenberg/rawpixel-760037-unsplash/" class="wp-image-56" srcset="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg 1024w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-300x200.jpg 300w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-768x512.jpg 768w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1200x800.jpg 1200w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-600x400.jpg 600w" sizes="(max-width: 1024px) 100vw, 1024px"></a>
```

Shouldn't the default behaviour be that to link to full sized images?

If it is not, is there a way to edit this behaviour so the gallery images link to full images?

Running WP 5.0.3.

**Comment by asadkn** [comment]
I can confirm this is an issue with the latest release. It's quite important for the images to link to full media. 'large' isn't large enough.

**Comment by ejimford** [comment]
I can also confirm this is an issue, too.  Gallery is not linking to the full size images.

**Comment by jorgefilipecosta** [comment]
Thank you all for reporting and testing this issue.
A fix was proposed in https://github.com/WordPress/gutenberg/pull/16011.
