### ISSUE TITLE
Make TinyMCE single instance prototype up-to-date with main prototype

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#134]
- [x] Add image animations.
- [x] Matching layout.
- [x] Show block UI on focus, hide on type.
- [x] Move inline toolbar next to block toolbar.
- [x] Add insert block UI.

**Comment by Afraithe** [comment]
Might be able to borrow the "hack" Spocke made on our prototype for the block insertion for a quick win there?
