### ISSUE TITLE
blocks.php - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#13404]
I'm getting following error after upgrading to WP 5.0.3:

Invalid argument supplied for foreach() in /wp-includes/blocks.php on line 183\n

As a result - output HTML is corrupted, some letters and words disappear in HTML resulting output.

Code statement which generating error:

`	foreach ( $block['innerContent'] as $chunk ) {
		$block_content .= is_string( $chunk ) ? $chunk : render_block( $block['innerBlocks'][ $index++ ] );
	}`

I'm using PHP 7.2.13 and MariaDB 10.3.8. Disabling all plugins and using default WP 5.0 theme - not helped at all.

**Comment by EldarAgalarov** [comment]
I tested it on PHP 5.6.39 and PHP 7.1.25 - all works fine. Bug appears on PHP 7.2.13 only.

**Comment by youknowriad** [comment]
Duplicate of #12672
