### ISSUE TITLE
List Block: Consider graying out indentation buttons when they will have no effect. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#13402]
When you're editing a list block item that's already positioned all the way to the left, clicking the "Outdent List Item" button has no effect. We should consider graying out the left indent button to show that it's disabled. 

![artboard](https://user-images.githubusercontent.com/1202812/51484093-a8f5dc00-1d68-11e9-9e5c-f41fb853d06d.png)

**Comment by iseulde** [comment]
I agree.

**Comment by sarahmonster** [comment]
💯💯💯

Would this make for a good first issue from a development perspective?

**Comment by melchoyce** [comment]
Let's do it!
