### ISSUE TITLE
Integrating an existing component library into Gutenberg

### ISSUE THREAD

**Issue by risker** [WordPress/gutenberg#13401]
Hey all,

I'm in the process of building out a WYSIWYG editor based on Gutenberg and a custom component library written in React.

Mostly, I've got it working. However, a problem I haven't been able to solve is conflicting HTML structure and styling in the editor.

For example, let's take two components that should go hand-in-hand - `Grid` and `GridColumn`.

The components are meant to be used in a structure like this:
```
<Grid>
    <GridColumn>
        any content
    <GridColumn>
    <GridColumn>
        any content
    <GridColumn>
</Grid>
```

and that generates HTML like this:
```
<div class="grid">
    <div class="grid__column>
        any content
    <div>
    <div class="grid__column>
        any content
    <div>
</div>
```

It's important to note here that `.grid` is styled with flexbox & it's children are flex items.

In Gutenberg, I've got this partially working with `<InnerBlocks />`. That is, it works but the styles are broken, since `<InnerBlocks />` inserts a bunch of HTML that the existing component has not considered (and should not consider, in my opinion).

The HTML in Gutenberg looks like this:

![image](https://user-images.githubusercontent.com/1892091/51481053-6d283a00-1d9b-11e9-94aa-a71ecb397955.png)

Since my divs with class `grid__column` are not direct children of my div with class `grid`, my flexbox styles break.

I've investigated two core blocks that offer a similar experience (just to see if it should be possible to workaround this):
1. core/columns - works with InnerBlocks & templates, but has the same issue - lots of divs in the middle.
2. core/table - works with custom logic. The HTML is correctly nested. But it is not possible to add multiple InnerBlocks for every GridColumn.

Another idea I had was to add some additional classes to `editor-block-list__layout` (I would want to add `grid`) & `editor-block-list__block` (I would want to add `grid__column`) elements - but looks like this is not possible at the moment. I _could_ try to parse the library styles automatically and make `.grid` styles apply to `.editor-block-list__layout`, but there's no way I can apply `.grid__column` styles to `.editor-block-list__block` since there's no parent selector in CSS.

-----------------------------

So, my question - any tips on how I could make this work?

**Comment by risker** [comment]
I don't want to sound blunt, but is there a chance someone can take a look at this issue in the near future? I've got a project standing by for nearly two months now because of this issue. Any timeline would be helpful so I could update my client.

I could take some time to help implement the necessary fixes in Gutenberg, but would still need somebody to tell me what the expected technical behaviour is here. Am I trying to do the impossible or can this be improved somehow?

**Comment by talldan** [comment]
This is now being addressed with the experimental lightBlockWrapper feature. Here's an example PR for the navigation block, where the inner blocks are `li` tags and the `<InnerBlocks>` component renders as a `ul`:
https://github.com/WordPress/gutenberg/pull/20729

`InnerBlocks` now has some experimental props that allow adding classes and using different HTML tags:
https://github.com/WordPress/gutenberg/pull/20729/files#diff-2e071f8429cd2c500b830947ffde4239R296-R300

Wrapping elements around a block can be removed using the light block wrapper supports property:
https://github.com/WordPress/gutenberg/pull/20729/files#diff-fdd974a8b850f44c6676ce91baef62f8R29

... along with a `Block` component that supports different primitive tags for the block itself:
https://github.com/WordPress/gutenberg/pull/20729/files#diff-2e071f8429cd2c500b830947ffde4239R196

These are still experimental features, so they may change, but I think there's a good path forwards now, so will close this issue.
