### ISSUE TITLE
Post tags: Choose from the most used tags

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1341]
Not sure if this has already been discussed, just thought to report it. Currently, when adding tags to a post it is also possible to choose them from a list of "most used tags":

![screen shot 2017-06-21 at 17 28 12](https://user-images.githubusercontent.com/1682452/27393167-d1ea3904-56a8-11e7-9b41-2782505c1052.png)

this is basically the tag cloud and I guess users are used to it. Not sure if there are plans to support it in Gutenberg.

**Comment by karmatosed** [comment]
I wonder how used this is currently? Is there a strong user case for adding this in? I know the case of 'it exists in current WordPress', but I also wonder how useful it really is? I'm happy to be wrong.

**Comment by karmatosed** [comment]
For now, closing this as feel it doesn't come into v1 and we don't have evidence right now of the user case. I am not saying we can't iterate, we totally can. However for now lets try and focus on what we are shipping in Gutenberg v1.

**Comment by donnchawp** [comment]
Just raising my hand here to say I use this every time I post to my photoblog as I post photos from the same location, and generally the same things (landscapes, or street photography, in my local area/city) so it's a huge time saver being able to click those tags to add them.

Same reasoning applies to categories. I miss the "most used categories" for the same reason even though I use more tags nowadays.

**Comment by gracie** [comment]
This was also requested in #1595600-zen. I know this is closed but we can't +1 the ideas board.

**Comment by mahnunchik** [comment]
Any news?
