### ISSUE TITLE
How to change post_content HTML as per the deprecated block?

### ISSUE THREAD

**Issue by vrundakansara** [WordPress/gutenberg#13417]
I am using a custom block which has a font awesome icon tag like this

`<span class="fa fa-star"></span>`

I want to replace this with an svg. I have moved the block to "deprecated" block and things work fine when I edit and update the page.

But, the pages that already have this icon tag are not changed unless I edit and update them.

How do I achieve this?

Help is much appreciated.

Regards,
Vrunda Kansara

**Comment by swissspidy** [comment]
> But, the pages that already have this icon tag are not changed unless I edit and update them.

> How do I achieve this?

I suppose this is the answer: you would have to update them.

**Comment by youknowriad** [comment]
Closing, the more global discussion about these flows is discussed here #7604
