### ISSUE TITLE
Classic Block - Add/Remove in Gallery does not save

### ISSUE THREAD

**Issue by scooterodell** [WordPress/gutenberg#13424]
**Describe the bug**
When editing an existing gallery in a classic block, if you add or remove an image, it does not save to the gallery.

*Note: Removing images _sometimes_ works. In my own testing, removing images worked 25% of the time. Adding images never worked.

**To Reproduce**
1. Go to a page or post with an existing gallery in a classic block
2. Click on the edit pencil when hovering over the gallery
3. Add or remove an image, then click "Update Gallery"

**Expected behavior**
Added and removed images should be reflected in the gallery upon update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.14.2
 - Browser: Chrome
 - Version: 71.0.3578.98 64-bit

**Additional context**
- WordPress 5.0.3

**Comment by jarretc** [comment]
Confirmed during triage that this is reproduceable. Happens only in the Classic block using Gutenburg, regular Classic Editor works.

JS error in console upon updating gallery is below

```
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at wp-tinymce.js?ver=4940-20190515:3
    at Object.map (wp-tinymce.js?ver=4940-20190515:3)
    at Object.select (wp-tinymce.js?ver=4940-20190515:3)
    at mce-view.min.js?ver=5.2.3:1
    at Function.s.findKey (underscore.min.js?ver=1.8.3:1)
    at Function.s.find.s.detect (underscore.min.js?ver=1.8.3:1)
    at N.d.update (mce-view.min.js?ver=5.2.3:1)
    at mce-view.min.js?ver=5.2.3:1
    at N.d.<anonymous> (mce-view.min.js?ver=5.2.3:1)
    at s (backbone.min.js?ver=1.2.3:1)
```

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on Wordpress 5.4.2 and Gutenberg 8.4.0-rc.1:

![gallery](https://user-images.githubusercontent.com/3629020/85961365-1433eb00-b9fe-11ea-882b-61090244b561.gif)

@scooterodell - are you still able to replicate this?

**Comment by scooterodell** [comment]
@glendaviesnz yes, I am still getting this behavior. Currently on 5.4.2.


![gallery-image-issue](https://user-images.githubusercontent.com/5489423/86309309-6a18b680-bbe9-11ea-8dd0-42e4d5e409d8.gif)

**Comment by talldan** [comment]
This seems to have been resolved, so closing the issue.
