### ISSUE TITLE
Can't install deasync 0.1.13 with the latest nodejs 11.7.0 version

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#13437]
**Describe the bug**
When I upgraded my environment to nodejs 11.7.0 deasync 0.1.13 install sent me a error when I tried to build Gutenberg.

**To Reproduce**

1. Upgrade to nodejs 11.7.0
2. Go to Gutenberg project folder in a terminal
3. Type npm install command

**Expected behavior**
As deasync is needed for building Gutenberg project, I updated deasync version to its lastest one in package.json and everything is ok.

**Screenshots**

![image](https://user-images.githubusercontent.com/1003778/51600116-8e0a9f80-1f01-11e9-8420-c11cb1ec22f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - nodejs 11.7.0 managed with chocolatey 0.10.11

**Comment by gziolo** [comment]
Can you open PR which updates `deasync` to the latest version?
