### ISSUE TITLE
add a field to editor-color-palette to concise if color is a foreground or a background color

### ISSUE THREAD

**Issue by kuchenundkakao** [WordPress/gutenberg#13438]
The possibility to set my own editor color palette is an awesome option. However, i would like to go further. A lot of times, i want my users to be able to choose between several background-colors like blue, green and red, but i want them to only be able to use white and black as background-colors.

With the current add_theme_support('editor-color-palette' i can only add colors to a global color palette like this:

```
array(
				'name' => __( 'red', 'themeLangDomain' ),
				'slug' => 'red',
				'color' => '#FF0000',
			),
```

I propose to add a field to this array like

```
array(
				'name' => __( 'red', 'themeLangDomain' ),
				'slug' => 'red',
				'color' => '#FF0000',
                                'field' => 'background' //choose between 'background', 'foreground','both', default 'both'
			),
```

and use it in the Gutenberg Block Registration like this:

```
<PanelColorSettings
						title={ __( 'Color Settings' ) }
						initialOpen={ true }
						colorSettings={ [
							{
								value: backgroundColorHeader.color,
								onChange: setBackgroundColorHeader,
								label: __( 'Background Color' ),
                                                                colorField: {'background'}
							},
							{
								value: textColorHeader.color,
								onChange: setTextColorHeader,
								label: __( 'Font Color' ),
                                                                colorField: {'foreground'}
                            },
```

What do you think?

**Comment by gziolo** [comment]
@jorgefilipecosta, you might be the best equipped to respond to this proposal.

**Comment by jorgefilipecosta** [comment]
Hi @kuchenundkakao, thank you for bringing this. I think this proposal is good and was something we already considered during the color discussions.
We could call the new property contexts, and it would be able to identify one or multiple contexts where the color appears:
```
array(
				'name' => __( 'red', 'themeLangDomain' ),
				'slug' => 'red',
				'color' => '#FF0000',
                'contexts' => array( 'background', 'color' ),
			),
array(
				'name' => __( 'black', 'themeLangDomain' ),
				'slug' => 'block',
				'color' => '#000000',
                'contexts' => array( 'background', 'border' ),
			),
```

But we need to take into account the multiple specific palettes needed:
- We have blocks that need to specify a custom color palette e.g.: table, independently of theme options.
- We have requested from plugins to be able to change/filter the color palette of specific color blocks, regardless of what the theme sets.
- And we have this need for the themes to specify a color palette in particular block usages, e.g., background, foreground, etc...


I think during the next more significant set of improvements to colors, all these needs should be analyzed and some tradeoffs made.

**Comment by landwire** [comment]
This issue has been open more than 2 years. Is there any movement on this? Is there any way to define different background and foreground colours?

**Comment by jorgefilipecosta** [comment]
This issue is being discussed in https://github.com/WordPress/gutenberg/issues/25613 and there are new insights there. I'm closing this issue in favor of the other one so we don't have two issues for the same task.
