### ISSUE TITLE
Button block: Rethink the toolbar overlapping issue

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#1344]
When inserting a new button block, there are two toolbars that appear and are overlapping one another.

![screen shot 2017-06-21 at 9 47 16 am](https://user-images.githubusercontent.com/617986/27396218-401a7d36-5667-11e7-8b70-8967d671ac49.png)

Is there another way to display these so this doesn't happen?  This ticket probably relates to #1168

**Comment by youknowriad** [comment]
Duplicate of #1111 ?

**Comment by mapk** [comment]
Repeat of #1111
