### ISSUE TITLE
Color picker changes position unexpectedly when hovered

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13445]
Seems to me this depends on the actual screen size and available space so to clarify:
- I'm testing on a macBook Pro 15''
- using Chrome 71

Steps to reproduce:
- select a paragraph
- make sure in the inspector the "Text Settings" panel is open (it is by default)
- expand the "Color Settings" panel
- click the "Custom color picker" button
- the color picker opens upwards
- hover the color picker with your mouse
- the color picker changes position and now it's open downwards without an apparent reason for this to happen

To reproduce the bug using a machine with a different screen size, maybe one option is playing with the zoom level to make the picker open upwards initially.

I've made a GIF:

![up down](https://user-images.githubusercontent.com/1682452/51624240-afd44880-1f3a-11e9-85a7-199c531f0330.gif)

**Comment by afercia** [comment]
Very likely related to the CSS applied on the toggle button when hovered: `transform: scale(1.2);`

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @afercia. We are now using a text button for the custom color and I'm not able to reproduce this problem anymore. If in your tests the problem is still happening feel free top comment/reopen the issue, and I will look further into the problem.

**Comment by afercia** [comment]
Correct: this is old stuff, thanks @jorgefilipecosta
