### ISSUE TITLE
Render InnerBlocks without containers (in the Editor)

### ISSUE THREAD

**Issue by mathishuettl** [WordPress/gutenberg#13447]
Hello Community,

is it possible to render the InnerBlocks inside the edit() without all the containers wrapped arround? In the Image I have attached you can see how many divs, etc there are arround the acctual container I want.

In the parentBlock in the render() I have the following:

```
<div class={ !fullWidth ? "container" : "container-fluid" }>
    <InnerBlocks allowedBlocks={ ALLOWED_BLOCKS } />
</div>

```

The childBlock looks like that:
```
<div class={ "col-md-" + columnSize } style={ { backgroundColor: backgroundColor } }>
    <h1>Size: { columnSize }</h1>
</div>
```

so the output I want is (as example)

```
<div class='container'>
    <div class='col-md-6' style='background-color: black'>
        <h1>Size: 6</h1>
    </div>
</div>
```

![image1](https://user-images.githubusercontent.com/9340538/51625117-a8ae3a00-1f3c-11e9-82ce-6021ddfeb5a9.PNG)

**Comment by mcsf** [comment]
Hello,

Inner blocks are expected to behave and feel as regular blocks, with some caveats (restrictions can be applied, e.g. which block types are allowed for children). So, in terms of editing interface, and thus the DOM, the structure will be roughly the same as for top-level blocks. This is unlikely to change.

However, this doesn't mean the actual output—what gets serialised and shown on the front-end—will carry those containers. For instance, with the Columns block:

```html
<div class="wp-block-columns has-2-columns">
  <div class="wp-block-column">
    <p>A</p>
  </div>
  <div class="wp-block-column">
    <p>B</p>
  </div>
</div>
```

**Comment by designsimply** [comment]
I'm interested in circling back to this to try to try to help make the issue actionable and to see if I can summarize. I see that this was the original question:

<blockquote>is it possible to render the InnerBlocks inside the edit() without all the containers wrapped arround?</blockquote>

My understanding from @mcsf's reply is that the answer is no for the editor but that you can still get a clean output for the front-end such as the example given for the Columns block.

@mathishuettl is this also your interpretation and does this give you the answer you need in order for you to reach your goal for what you are working on?

**Comment by youknowriad** [comment]
Closing as already answered. Thanks all.
