### ISSUE TITLE
Fix wording for the color picker saturation

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13444]
In the color picker, there's a visually hidden descriptive text that says:

`Use your arrow keys to change the base color. Move up to lighten the color, down to darken, left to increase saturation, and right to decrease saturation.`

https://github.com/WordPress/gutenberg/blob/0f5891556e8e3ec3e41fcc318533bba87983338b/packages/components/src/color-picker/saturation.js#L177-L179

Hosever, left _decreases_ saturation, while right _increases_ it. The text should be amended accordingly.

<img width="262" alt="screenshot 2019-01-23 at 17 56 19" src="https://user-images.githubusercontent.com/1682452/51623360-d09b9e80-1f38-11e9-8f02-0dda31f71a7f.png">

**Comment by jorgefilipecosta** [comment]
Fixed in: https://github.com/WordPress/gutenberg/pull/13479
