### ISSUE TITLE
Add categories to Prepublish panel if default is Uncategorized.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13464]
The prepublish panel does not mention category because the post by default has one category uncategorized. It would be good to check to see if another category has been added that is not uncategorized. If not then add category to the prepublish panel.

![screen shot 2019-01-24 at 01 37 40](https://user-images.githubusercontent.com/5323259/51647317-8c31f200-1f7c-11e9-860a-ca37d4c1bab8.png)

**Comment by paaljoachim** [comment]
This issue is still relevant but I will close it anyway.

**Comment by grappler** [comment]
This was fixed with https://github.com/WordPress/gutenberg/pull/37703
