### ISSUE TITLE
 Block validation Failed due to Strong tags after migration.

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#13477]
**Describe the bug**
We have a block and its working fine. After migration, we get block validation error - https://monosnap.com/file/r7ac07klzkDiqhJBVLOqbj8zvPwpbu

Can you please provide me way to get ride of this error?

**Comment by youknowriad** [comment]
This documentation should help you solve the issue https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/
