### ISSUE TITLE
Sandbox embedded previews

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#1348]
At the moment, we're just injecting embedded content previews into the main editor document. We need to move over to using sandboxed iframes for this.

It's not as simple as it sounds, as we need to resize the iframe to show the full content of the preview and Calypso has a resizing iframe that attempts to do that, but some sites, like Tumblr, start resizing the content to fit the container, while the iframe is also resizing, and it all messes up.

Calypso has extra code to properly calculate the size of embedded content in the editor, which we should look at, and replace the current implementation of HtmlEmbed.

**Comment by youknowriad** [comment]
Closed in #1392
