### ISSUE TITLE
Toggle blocks borders

### ISSUE THREAD

**Issue by catkit** [WordPress/gutenberg#13482]
**Is your feature request related to a problem? Please describe.**
It's too hard to select blocks inside other blocks.
**Describe the solution you'd like**
I know you are working at making this task easier and I love the mockup here:
https://codepen.io/kjellr/pen/jdEJQb?editors=0110
And I think the block navigation is a great help, but I fancy it would be nice to have a simple toggle button to turn blocks borders on / off so we can easily preview the document structure.

**Comment by paaljoachim** [comment]
@kjellr

**Comment by cecoates** [comment]
I'd like this as well.

Example use case:

11996977-hc

I was helping a user arrange image blocks within a column. Especially once you get into the 3+ column range, finding the right spots to click becomes essentially impossible.

That means when you're trying to hover around and select the "main" block to adjust the settings (such as change the number of columns) you kind of end up just clicking around randomly until you get it.

I'd like the option to *always* have borders, personally. The editor isn't meant to resemble the finished page/post anyway, so IMO seeing the borders of the blocks would increase usability drastically.

Here's a GIF I made for a user showing them how to add columns blocks, and even from that you can see how I randomly click around trying to find the block's "edge".

![Peek 2019-04-10 17-26](https://user-images.githubusercontent.com/10121835/55919859-1de4ef00-5bbd-11e9-9421-3bbbfc8a9b35.gif)

**Comment by skorasaurus** [comment]
This would be nice to experience in core. 

In the meantime, you can enable this within the [block-options aka editors' kit plugin ](https://wordpress.org/plugins/block-options/)
https://github.com/phpbits/block-options/

(To enable block borders, install the block-options plugin, then while in a post, click the upper right hand three colon and toggle the block guide lines.

![image](https://user-images.githubusercontent.com/955351/79594929-f36d2200-80ab-11ea-8b6e-520ec8c870ac.png)

**Comment by mtias** [comment]
The new block list view and block type button include outline highlights on hover / focus. An option for this is currently not being considered, but it might come in the future.
