### ISSUE TITLE
Toolbar appears when shift is pressed in Safari on macOS

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#1349]
Safari 10.1.1 (current latest stable) on macOS. `master` branch at c67326c.

Every time the <kbd>shift</kbd> key is pressed, the toolbar appears. So... every time you go to capitalize a letter, the toolbar is flickering (#1300) in and out.

**Comment by GaryJones** [comment]
Confirmed - I can replicate this. It actually seems to be any modifier key - <kbd>cmd</kbd>, <kbd>alt</kbd>, and <kbd>ctrl</kbd> also bring up the toolbar, until the next non-modifier key is pressed.

**Comment by mtias** [comment]
@youknowriad mind looking at this one? Sounds related to when we did https://github.com/WordPress/gutenberg/commit/1b0b7ffae2b359cca057ff0c6cd4a6447fbe7aca
