### ISSUE TITLE
Unable to change colour when choosing blog "list"

### ISSUE THREAD

**Issue by CzPete** [WordPress/gutenberg#13518]
I would like you to reactivate issue #9016. I keep running into this over and over. People have different reasons for having different color backgrounds/fonts for their paragraphs. Most of the same reasons apply to lists. It seems really strange that you would close an issue just because you don't agree with your customers. Let them decide!

It seems really strange that paragraph supports the background/foreground color and list, which is not that much different from paragraph, does not! Why would you not want to support it? Just because YOU don't see how it's useful? Clearly, people are asking for it. It does not seem so difficult, so please add it to WP. As for the other blocks, leave it for now, unless somebody asks for it there too. Again, thinking that it might also be useful for other blocks (it might) should not stop you from implementing it at least for lists.

As for the HTML workaround, it's actually not that easy. When you choose a background color for a paragraph, there is some padding added around the paragraph (at least in Hestia theme). It's not that easy to add the same padding around a list. Yes, I can do it, but then, I can also code my entire website by myself without using WP.

So please reactivate this issue or better yet, fix it!

Thank you.

**Comment by Soean** [comment]
Hey @CzPete,
why are you opening a new issue? #9016 is still open, what is the difference to this issue?

There is also a more general ticket: #8171 `Consider adding color and text size customizations to all text-based blocks.`
Also #12802 `Lack of consistency between text blocks`

**Comment by CzPete** [comment]
Hi @Soean, my bad. I thought that #9016 was closed. I think I got mixed up with the other issues that were duped to it and marked as closed. It won't happen again - I hope :-)
