### ISSUE TITLE
Post Settings: Let users configure metaboxes (Screen Options)

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1351]
![screen shot 2017-06-22 at 08 42 25](https://user-images.githubusercontent.com/1204802/27420567-c4ba8350-5726-11e7-8695-80ad4b96c4f4.png)

The settings icon in that screenshot above is intended to be a replacement for the old screen options:

![screen shot 2017-06-22 at 08 43 04](https://user-images.githubusercontent.com/1204802/27420584-d1ceac1a-5726-11e7-884c-2f8f40637ada.png)

![screen shot 2017-06-22 at 08 43 13](https://user-images.githubusercontent.com/1204802/27420589-da88296c-5726-11e7-83ca-28136aab4f12.png)

Since distraction free is built in (toggle post settings off), and it probably doesn't make sense to configure amount of columns (breaks responsive), what should be ported is the ability to hide metaboxes. 

Blocked on #450

**Comment by afercia** [comment]
Worth considering plugins can currently add their own stuff in the Screen Options, for example:

![screen shot 2017-06-22 at 11 00 13](https://user-images.githubusercontent.com/1682452/27425925-537b9f1c-573a-11e7-8261-350d2e6a7145.png)

**Comment by StaggerLeee** [comment]
Now when you are re-doing everything make a very small and quick change inside Screen Options.
Mark all labels for disabled Metaboxes in red color.

- Will mean as visual help a lot for advanced users when there are many Metaboxes.
- More important will mean alot for Users beginners who are to much curious, click happy, and disable something they should not disable.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518714643000058)._

**Comment by jasmussen** [comment]
Lots of things have changed since this ticket was opened in June 2017. 

In the light of those changes, including the new native extensibility of Gutenberg being developed, I'm going to close this ticket as _Maybe Later_.

It is important to remember that tickets can always be re-opened, or created anew as use cases appear that warrant. Or someone can submit a PR that addresses the same issue a ticket was meant to initially solve.

**Comment by afercia** [comment]
I think this should be considered in the context of https://github.com/WordPress/gutenberg/issues/1316 as the effort for documenting removed actions and filters should be extended to the ones that won't work any longer simply because they don't have any effect in Gutenberg or there's no UI for them.

**Comment by MakeWebsites** [comment]
Hi. I miss the "Author" screen option. Is there any way I could incorporate additional screen options to Gutenberg?

**Comment by jasmussen** [comment]
Hi @MakeWebsites, you can change the author in the post settings sidebar:

<img width="343" alt="screen shot 2018-03-23 at 11 13 15" src="https://user-images.githubusercontent.com/1204802/37823908-3dd265aa-2e8b-11e8-830e-66205619ba78.png">

Does that work for you?

**Comment by MakeWebsites** [comment]
Thanks!

 

De: Joen Asmussen [mailto:notifications@github.com] 
Enviado el: viernes, 23 de marzo de 2018 10:14
Para: WordPress/gutenberg <gutenberg@noreply.github.com>
CC: Make-Websites <we@make-websites.co.uk>; Mention <mention@noreply.github.com>
Asunto: Re: [WordPress/gutenberg] Post Settings: Let users configure metaboxes (Screen Options) (#1351)

 

Hi @MakeWebsites <https://github.com/makewebsites> , you can change the author in the post settings sidebar:

 <https://user-images.githubusercontent.com/1204802/37823908-3dd265aa-2e8b-11e8-830e-66205619ba78.png> 

Does that work for you?

**Comment by MakeWebsites** [comment]
I just started to use Gutenberg (sorry!)

 

De: Joen Asmussen [mailto:notifications@github.com] 
Enviado el: viernes, 23 de marzo de 2018 10:14
Para: WordPress/gutenberg <gutenberg@noreply.github.com>
CC: Make-Websites <we@make-websites.co.uk>; Mention <mention@noreply.github.com>
Asunto: Re: [WordPress/gutenberg] Post Settings: Let users configure metaboxes (Screen Options) (#1351)

 

Hi @MakeWebsites <https://github.com/makewebsites> , you can change the author in the post settings sidebar:

 <https://user-images.githubusercontent.com/1204802/37823908-3dd265aa-2e8b-11e8-830e-66205619ba78.png> 

Does that work for you?

**Comment by jasmussen** [comment]
No worries!
