### ISSUE TITLE
List of Custom Taxonomies Not Visible in CPT Edit Screen

### ISSUE THREAD

**Issue by fourthfloor** [WordPress/gutenberg#13517]
**Describe the bug**
Upon creating a new taxonomy "event_types" (with show in rest, public and hierarchical set as 'true'), properly associated with the custom post type "events", there is an area within the Create New Event page that is designated for Event Types, but it has none of the existing taxonomy that was created as listed there. 

_Wordpress Version: 5.0.3_

**To Reproduce**
This is within my Theme's functions file: 
```
function cptui_register_my_cpts() {
	$labels = array(
		"name" => __( "Events", "commonthreadsquiltguild" ),
		"singular_name" => __( "Event", "commonthreadsquiltguild" ),
		"all_items" => __( "All Guild Events", "commonthreadsquiltguild" ),
		"add_new" => __( "Add New Event", "commonthreadsquiltguild" ),
		"add_new_item" => __( "Add New Event", "commonthreadsquiltguild" ),
		"edit_item" => __( "Edit Event", "commonthreadsquiltguild" ),
		"new_item" => __( "New Event", "commonthreadsquiltguild" ),
		"view_item" => __( "View Event", "commonthreadsquiltguild" ),
		"view_items" => __( "View Events", "commonthreadsquiltguild" ),
		"search_items" => __( "Search Events", "commonthreadsquiltguild" ),
		"not_found" => __( "No events found", "commonthreadsquiltguild" ),
		"not_found_in_trash" => __( "No events in the trash", "commonthreadsquiltguild" ),
		"parent_item_colon" => __( "Parent Event:", "commonthreadsquiltguild" ),
		"archives" => __( "All Guild Events", "commonthreadsquiltguild" ),
		"parent_item_colon" => __( "Parent Event:", "commonthreadsquiltguild" ),
	);
	$args = array(
		"label" => __( "Events", "commonthreadsquiltguild" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"delete_with_user" => false,
		"show_in_rest" => true,
		"rest_base" => "events",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "events", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title", "editor", "excerpt", "trackbacks", "comments" ),
		"taxonomies" => array( "event_types" ),
	);
	register_post_type( "events", $args );
}

function cptui_register_my_taxes() {
	$labels = array(
		"name" => __( "Event Types", "commonthreadsquiltguild" ),
		"singular_name" => __( "Event Type", "commonthreadsquiltguild" ),
		"menu_name" => __( "Event Types", "commonthreadsquiltguild" ),
	);
	$args = array(
		"label" => __( "Event Types", "commonthreadsquiltguild" ),
		"labels" => $labels,
		"public" => true,
		"publicly_queryable" => true,
		"hierarchical" => true,
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => array( "slug" => "event", "with_front" => true ),
		"show_admin_column" => true,
		"show_in_rest" => true,
		"rest_base" => "types",
		"rest_controller_class" => "WP_REST_Terms_Controller",
		"show_in_quick_edit" => true,
		);
	register_taxonomy( "event_types", array( "events" ), $args );
}
add_action( 'init', 'cptui_register_my_cpts' );
add_action( 'init', 'cptui_register_my_taxes' );
```

1. Add the above code to the functions.php file.
2. Add an item to the taxonomy list via the Event Types interface.
3. Note the empty list within the .
4. Attempt to add one of the created Event Types by typing it in manually.
5. Note the error: `Failed to load resource: the server responded with a status of 400 (Bad Request), referencing /wp-json/wp/v2/types?_locale`
 This error ONLY happens when trying to add an existing event type, otherwise you'll see the screenshot of it successfully showing one item.

**Expected behavior**
It should accurately show the existing taxonomies associated with the custom post type.

**Screenshots**
![screen shot 2019-01-25 at 6 54 10 pm](https://user-images.githubusercontent.com/4682143/51779081-2b68fd80-20d3-11e9-8fc3-70cd93ee522f.png)
![screen shot 2019-01-25 at 6 55 55 pm](https://user-images.githubusercontent.com/4682143/51779082-2efc8480-20d3-11e9-905e-d316eec4b86e.png)
![screen shot 2019-01-25 at 6 56 01 pm](https://user-images.githubusercontent.com/4682143/51779084-30c64800-20d3-11e9-9592-f5b2a26d287d.png)
![screen shot 2019-01-25 at 6 56 11 pm](https://user-images.githubusercontent.com/4682143/51779086-3328a200-20d3-11e9-90e3-386cdf8e36e0.png)
![screen shot 2019-01-25 at 6 56 24 pm](https://user-images.githubusercontent.com/4682143/51779089-34f26580-20d3-11e9-9601-342b65b00659.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Safari 
 - Version: 12.0.2

**Additional context**
- No plugins were used for this. I used the default theme of twentynineteen to ensure there was no issue with theme incompatibility.
- Web Hosting is MediaTemple: Dedicated Virtual Server.

**Comment by fourthfloor** [comment]
Additional Note:
No issues viewing & setting the custom taxonomy via the Quick Edit option:
![screen shot 2019-01-25 at 7 03 24 pm](https://user-images.githubusercontent.com/4682143/51779211-f4dfb280-20d3-11e9-8891-f1fe358c43b0.png)

**Comment by pause13th** [comment]
Hi there, was looking into this issue too

Apparently in order to add the custom taxonomy to the 'Document Panel', just add 'show_in_rest'

`$args = array(
		// 'public'                     => true,
		// 'show_ui'                    => true,
		// 'show_admin_column'          => true,
		// 'show_in_nav_menus'          => false,
		'show_in_rest'               => true,
		// 'show_tagcloud'              => true,
		'hierarchical'          => false,
		'labels'                => $labels,
		'show_ui'               => true,
		'show_admin_column'     => true,
		'update_count_callback' => '_update_post_term_count',
		'query_var'             => true,
		'rewrite'               => array( 'slug' => 'project-tag' ),
	);
	register_taxonomy( 'project-tag', array('project'), $args );`

My guess its gutenberg are using rest API to pull in the custom taxonomy

**Comment by strarsis** [comment]
Yes, setting the taxonomy setting `show_in_rest` to `true` makes the taxonomy selection appear in Gutenberg editor.
However, the taxonomy selection field stays grey/disabled and a JavaScript error occurs:
````
Warning: Can't perform a React state update on an unmounted component.
````

**Comment by skorasaurus** [comment]
I came across this while troubleshooting some taxonomy issues with a custom post type that I have. 

The cause of this is that the rest_base parameter for registering the custom taxonomy is incorrect. In the code above, it is incorrectly set as "types". 
If you remove that line and rely on the default parameter for [rest_base](https://developer.wordpress.org/reference/functions/register_taxonomy/#parameters) ; of `$taxonomy`; Any terms that you make with the custom taxonomy will display within the block editor. 

In the image below, I created a couple event types and they're listed in the custom post type's sidebar. 
![image](https://user-images.githubusercontent.com/955351/192341870-f3296a61-ae38-430c-9db7-3739b5b0881b.png)

Please reopen if there's a condition that you need to change the rest_base parameter from the default. 

(Used gutenberg 14.1.1; wordpress 6.0.2)....
