### ISSUE TITLE
Set order for new rich text button

### ISSUE THREAD

**Issue by m-radzikowski** [WordPress/gutenberg#13528]
**Is your feature request related to a problem? Please describe.**
When adding new button to rich text editor, it is put always at the end. In the order of addition. This would allow to add button in any place on the toolbar.
Currently I'm unable to add a new button between "italic" and "link" buttons.

**Describe the solution you'd like**
New property for `RichTextToolbarButton` / `ToolbarButton` that would allow to set ordinal number for button, or "weight".

**Comment by azaozz** [comment]
Ran into this too. It is a pretty minor issue but still "nice to fix" eventually :)

Seems easier/most straightforward thing would be to have a filterable array of the buttons names (`core/bold`, `core/link`, etc.) that can be sorted independently of loading order (similarly to how the PHP filter `mce_buttons` works for the Classic editor). Then the same approach can be used in other sortable/re-orderable places like in the inspector, plugins added menu items, etc.

**Comment by ellatrix** [comment]
This is sort of fixed with #14233: added controls are now listed alphabetically in the dropdown.

**Comment by grillonbleu** [comment]
Could this suggestion be reconsidered? Rich text buttons are changing position depending on the locale. It would make more sense to order by importance. Furthermore, related buttons end up shuffled among existing ones.

**Comment by t-hamano** [comment]
> Rich text buttons are changing position depending on the locale.

I think this is a problem: the title order is not necessarily a meaningful order.

| English | Deutsch | Japanese |
|--------|--------|--------|
| <img width="154" height="340" alt="Image" src="https://github.com/user-attachments/assets/15abff6e-a401-41e3-a08b-3389cd056614" /> | <img width="157" height="340" alt="Image" src="https://github.com/user-attachments/assets/a813e840-00e4-4cc1-8aef-c69158995b28" /> | <img width="170" height="340" alt="Image" src="https://github.com/user-attachments/assets/14eeb39e-8170-40d8-82db-06192a01b144" /> |
