### ISSUE TITLE
PHP Fatal error: get_current_screen() in Gutenberg 4.9

### ISSUE THREAD

**Issue by ancom32** [WordPress/gutenberg#13529]
Hi,

I updated Gutenberg to version 4.9 and I got an error in php error log. Gutenberg 4.8 worked great but when I installed 4.9, it didn't work anymore. My WordPress version is 5.0.3

This is the error in php_errorlog:

PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /wp-content/plugins/gutenberg/lib/client-assets.php:1338
Stack trace:
/wp-includes/class-wp-hook.php(286): gutenberg_editor_scripts_and_styles('')
/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
/wp-includes/script-loader.php(2231): do_action('wp_enqueue_scri...')
/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
/wp-includes/general-template.php(2614): do_action('wp_head')
/wp-content/themes/Frontenberg-master/header.php(7): wp_head()
/wp-content/plugins/gutenberg/lib/client-assets.php on line 1338

Do you have any idea? I don’t know if I am the only person having this issue with Gutenberg 4.9.

Thanks.

**Comment by youknowriad** [comment]
Hi there!

Seems like a frontendberg issue as `get_current_screen` is not defined in the frontend by default. you might need (or frontenberg) to import these functions properly to make it work on the frontend.

**Comment by tomjn** [comment]
For reference, this is the code at fault:

```php
	$current_screen  = get_current_screen();
	$core_meta_boxes = array();
	// Make sure the current screen is set as well as the normal core metaboxes.
	if ( isset( $current_screen->id ) && isset( $wp_meta_boxes[ $current_screen->id ]['normal']['core'] ) ) {
		$core_meta_boxes = $wp_meta_boxes[ $current_screen->id ]['normal']['core'];
	}
	// Check if the Custom Fields meta box has been removed at some point.
	if ( ! isset( $core_meta_boxes['postcustom'] ) || ! $core_meta_boxes['postcustom'] ) {
		unset( $editor_settings['enableCustomFields'] );
	}
```

The whole point of this is to remove `enableCustomFields` from a settings array if it's been removed elsewhere. Instead, this could have been implemented as a filter, which would have made things more extensible too:

```php
function gutenberg_check_custom_fields_removal( $edit_settings ) {
	global $wp_meta_boxes;
	$current_screen  = get_current_screen();
	$core_meta_boxes = array();
	// Make sure the current screen is set as well as the normal core metaboxes.
	if ( isset( $current_screen->id ) && isset( $wp_meta_boxes[ $current_screen->id ]['normal']['core'] ) ) {
		$core_meta_boxes = $wp_meta_boxes[ $current_screen->id ]['normal']['core'];
	}
	// Check if the Custom Fields meta box has been removed at some point.
	if ( ! isset( $core_meta_boxes['postcustom'] ) || ! $core_meta_boxes['postcustom'] ) {
		unset( $editor_settings['enableCustomFields'] );
	}
	return $editor_settings;
}
```

I'm hesitant to start including admin files in frontenberg, as it's particularly bad practice and has security implications. But in this case and a lot of cases, there are solutions other than just requiring admin pages, that enable new things and make the editor bootstrapping more extendable, and easier to debug.

With the above change, I could have just unhooked a filter, and everything would be fine. In fact it would help me as I could add a filter that forced the contents of `$edit_settings`.

These issues are opportunities to improve the bootstrapping process and make it more pluggable

/cc @youknowriad

**Comment by tomjn** [comment]
In future, it would be better to suggest mocking the function or polyfilling. I've pushed a hotfix in the form of:

```php
if ( !function_exists('get_current_screen') ) {
        function get_current_screen() { return ''; }
}
```
