### ISSUE TITLE
Method getEntityRecords always returns up to 10 records

### ISSUE THREAD

**Issue by PiotrSzlagura** [WordPress/gutenberg#13533]
Hello, I am trying to create custom gutenberg block with page selector.

I have following code:

```js
edit: withSelect(select => ({
  posts: select("core").getEntityRecords(
    "postType",
    "page",
    {},
    { per_page: 100 }
  )
})
```

But even though I passed custom query params in last parameter, I still get only 10 pages. (I have about 15 pages available right now). How can I get all pages using `withSelect`?

**Comment by youknowriad** [comment]
I think it should be:

```
 posts: select("core").getEntityRecords(
    "postType",
    "page",
    { per_page: 100 }
  )
```

You have one extra argument in your function call.

**Comment by PiotrSzlagura** [comment]
You're right, thank you very much!
