### ISSUE TITLE
Confusing multiple inserters interface

### ISSUE THREAD

**Issue by hegerpkd** [WordPress/gutenberg#13558]
**Describe the bug**
I believe this results in confusing UX. Not sure if you consider this a bug, I would definitely do.
When creating a blocktype that has `InnerBlocks`, the inserter interface is two-fold. There is an "inner" inserter at the bottom of the new parent blocktype (visible and very prominent), and a main inserter on the side (barely noticable compared to the other and only appears on hover). I think this is confusing because the inserter at the bottom is way more prominent and suggests adding something new below, while the plus icon on the side would more naturally suggest changing the existing block. This results in the main inserter getting a kind of hidden position.

I am using the latest Wordpress core without the gutenberg plugin.

**To Reproduce**
1. Create a new blocktype
2. Add InnerBlocks
3. Add a template
4. See "error"

**Expected behavior**
I think we have 2 main ways of solutions for this issue. 
* to rethink how the main inserter is positioned
* introduce settings to add a permanent main inserter to the bottom of the content editor
* introduce settings to change the InnerBlock inserter and how it looks

**Screenshots**
Interface when template is added
![interface](https://user-images.githubusercontent.com/14338789/51898824-acf9ad80-23a9-11e9-848b-25380718c4ed.PNG)

Interface with no template
![interface2](https://user-images.githubusercontent.com/14338789/51898825-acf9ad80-23a9-11e9-913c-45ab1d363bf7.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 71

**Comment by youknowriad** [comment]
The UI changed a lot since the creation of this issue. I think it might not be relevant anymore. Can you clarify whether this is still an issue or not?

**Comment by karmatosed** [comment]
For now, closing this as there are some explorations iterating this experience. We can always reopen.
