### ISSUE TITLE
"Post Settings" button label

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#1356]
(Apologies if this has been previously discussed - I couldn't find any discussion.)

![Screenshot showing button label as Post Settings when showing image block properties](https://user-images.githubusercontent.com/88371/27428969-93f41974-573b-11e7-9587-72c106ba6afc.png)

The properties inspector for a block only appears when the Post Settings toggle button has been enabled - that's fine. But that means that the label of "Post Settings" doesn't make total sense - the screenshot above is really showing the immediate "settings" / "properties" of an image block, not the Post as a whole.

Something a bit more generic, like "Properties", or "Inspector" would make more sense for either context, and would then also apply without amendment when the editor is used for Pages or custom post types.

A few mockups:

- **Button label as _Properties_ for image block**

    ![Mockup showing button label as Properties for image block](https://user-images.githubusercontent.com/88371/27429195-478be3c2-573c-11e7-9fd5-7c47c98bc125.png)

- **Button label as _Properties_ for Post Settings**

    ![Mockup showing button label as Properties for Post Settings](https://user-images.githubusercontent.com/88371/27429335-b0a9419c-573c-11e7-9858-2b61f9e52017.png)

- **Button label as _Inspector_ for image block**

    ![Mockup showing button label as Inspector for image block](https://user-images.githubusercontent.com/88371/27429212-53535528-573c-11e7-9afa-6c8a1a2ed968.png)

- **Button label as _Inspector_ for Post Settings**

    ![Mockup showing button label as Inspector for Post Settings](https://user-images.githubusercontent.com/88371/27429281-8d53b254-573c-11e7-99b1-761c844e62fd.png)

There also comes the simplified ubiquitous language benefit to Users of being able to reference this thing called the "Inspector" in support queries and tutorials, in a similar way to understanding what the "Customizer" is, irrespective of whether the panel shows the Post Settings or some block settings (properties).

Discussion in https://github.com/WordPress/gutenberg/issues/1100#issuecomment-310336762 explains how developers may visualise the topological implementation as being the block properties panel appearing as a modal over the top of the Post Settings, but that's not how a User (who doesn't know the code) will experience it.

**Comment by mtias** [comment]
Yes, this was discussed, and I believe I suggested using "Inspector" or "Block settings" at the time. I think @jasmussen has specific concerns with dynamically changing it based on what was selected, though.

**Comment by GaryJones** [comment]
I would also have concerns about changing the button label dynamically, hence this proposal of choosing a static generic name, whatever contents are shown in the panel.

**Comment by buzztone** [comment]
As a new Gutenberg Editor user I definitely find "Post Settings" as the button label confusing.

For me "Inspector" conveys clearly what I see when I toggle this button. I have a clear mental image that it's letting me see the options available for the selected block in maximum detail.

**Comment by jasmussen** [comment]
For what it's worth, "Post Settings" has worked well on WordPress.com for about 4 months now. I think it's a good label because it contains exactly that, settings for the post that you're viewing.

**Comment by GaryJones** [comment]
> I think it's a good label because it contains exactly that, settings for the post that you're viewing.

For me, I think the _smell_ that "Post Settings" for the button label is not a good name comes from the fact there are duplicate instances at the top:

![screenshot 2017-06-22 17 09 10](https://user-images.githubusercontent.com/88371/27444228-978ff706-576d-11e7-9ace-01ff1d1a8c74.png)

If it was so good, why would the second instance (grey background) be needed? In this case, I think the second instance is correct, as would, for instance "Post -> Image", as it identifies exactly what the settings apply to - the post in general, or the image block.

That makes the ideal button label be one level of abstractness up, to represent the ability to toggle on this side panel or not - and not for what that side panel may or may not contain.

**Comment by westonruter** [comment]
I'll note that “Post Settings” doesn't facilitate translations if to support multiple post types the underlying string is `%s Settings` into which the post's `singular_label` is supplied.  See https://core.trac.wordpress.org/ticket/20005

**Comment by buzztone** [comment]
> For what it's worth, "Post Settings" has worked well on WordPress.com for about 4 months now. I think it's a good label because it contains exactly that, settings for the post that you're viewing.

I'm really surprised that has worked well on WordPress.com. I would have thought that novice users would find the label confusing, especially if "Post Settings" is also used on Pages.

> Also, I strongly feel like we shouldn't dynamically change the label.

I think there is a general consensus among current participants in this conversation that the label should not change. Rather the proposal I understand is to change to another single unchanging label with works well with all block types.

**Comment by jasmussen** [comment]
>  especially if "Post Settings" is also used on Pages.

When editing pages, the label is "Page Settings".

**Comment by buzztone** [comment]
>When editing pages, the label is "Page Settings".

Surely that's dynamically changing the label & at least potentially confusing for brand new users who don't understand yet the difference between a Page & a Post.

I'd be interested to hear from WordPress.com Happiness Engineers if new users have problems understanding the terms Post & Page.

**Comment by jasmussen** [comment]
@buzztone 

I would call that _statically_ changing the label. [Eventually, not now] you click Pages -> Add New, and you are editing a page where the label says "Page Settings" and does so always. If you instead clicked Posts -> Add New, you'd get "Post Settings", which does not change so long as you are editing the post. 

While I think "Post Settings" is descriptive for the sidebar toggle and works well, it is not the hill I will die on. I'm not immune to being convinced of other labels.

@GaryJones 

> If it was so good, why would the second instance (grey background) be needed? In this case, I think the second instance is correct, as would, for instance "Post -> Image", as it identifies exactly what the settings apply to - the post in general, or the image block.

The sidebar heading is for mobile, where the label on the button itself gets hidden.

**Comment by GaryJones** [comment]
@buzztone

> Surely that's dynamically changing the label

This is a different type of dynamic label - it's changing based on the post type (so stays the same in the editor view i.e. Post Settings vs Page Settings), and is not dependent on whether a block is selected or not (i.e. Post/Page Settings vs Block Settings).

It's still susceptible to some long Custom Post Type name in something like German blowing up the length of the button in a way that isn't catered for. That wouldn't happen if this button was named for what it was - a way to toggle the side panel, irrespective of what the contents of the panel were.

**Comment by buzztone** [comment]
>That wouldn't happen if this button was named for what it was - **a way to toggle the side panel, irrespective of what the contents of the panel were**.

@GaryJones that's what appeals to me about your suggestion. You see this button in terms of this action. I think that's a view than many new users may take. The Publish/Update button beside it is clearly an action. Inspector or perhaps even Inspect works well if you think of the button in this way.

Post Settings or Page Settings (or even Properties) by contrast describes this button in terms of the viewable/editable settings shown when pressed. I can certainly see many users, particular existing WP users, being comfortable with this approach. 

But it does seem to me carry a lot of cognitive overhead for brand new users. Ultimately user testing of new users will show if they understand what this button is for and click on it.

**Comment by jasmussen** [comment]
In the native WordPress app, this panel is called "Settings":

![screenshot_20170623-154628](https://user-images.githubusercontent.com/1204802/27485082-a8d735e2-582b-11e7-9b0d-9fbc2f30eed6.png)

Do you think people would grok this? 

To me it feels like the "Post" aspect adds context.

**Comment by GaryJones** [comment]
> To me it feels like the "Post" aspect adds context.

But, for the WordPress app, that only shows the post settings, right? It doesn't also toggle the appearance of block settings as well?

**Comment by jasmussen** [comment]
Right. So instead of having both a "Post Settings" and a "Block Settings" label, there's just "Settings".

The reason I come back to "Post Settings" (for posts) and "Page Settings" for pages (and so on for CPTs), is that I feel it's the one that best answers the question a novice user who accidentally dismissed the sidebar might ask: "where did my tags go"? I don't feel like any of the other labels suggested in this discussion answers this as well. 

But again, I'm empathetic to the label being hard to translate —  both length wise and wrt plurality etc., and I'm certainly open to a better suggestion. Naming things is hard.

**Comment by GaryJones** [comment]
I agree, that for a question of "where did my tags go?", that "Post Settings" et al makes more sense than Inspector.

Likewise, screen info and help do describe what contents the User can expect to see in there.

![Screenshot of Screen Info and Help tabs](https://user-images.githubusercontent.com/88371/27506797-caa06cce-58b8-11e7-831f-7f19a26a5400.png)

That brings us back to the original problem - does "Post Settings" still make sense when a block's advanced properties are showing?

**Comment by jasmussen** [comment]
> That brings us back to the original problem - does "Post Settings" still make sense when a block's advanced properties are showing?

I think it does. The blocks are part of your post, so it makes sense that post settings hold block settings also. I understand that we are discussing semantics here, and like I said I'm okay with finding a new name —  I'm not necessarily arguing for "Post Settings" and "Page Settings" and "[CPT] Settings" as the best name. I just don't feel like we've found any alternatives that are universally better. "Settings" is perhaps fine too, but "Inspector", as much as I love both the concept and the feature, seems too techy.

**Comment by youknowriad** [comment]
Just an idea, I'm not sure it's worth it but Maybe we should drop the label in favour of an arrow icon (open/close sidebar)

**Comment by GaryJones** [comment]
> Maybe we should drop the label in favour of an arrow icon 

Screen reader users will still need some verbal clue what it relates to, and new users need to be able to reference it in their questions.

**Comment by GaryJones** [comment]
My argument of a better button title is one of theoretical purity, but that should always be trumped by catering to what users need first.

I'm in agreement with @jasmussen's viewpoint - "Post Settings" et al may not be perfect, but I'm struggling to think of a better one that conveys exactly what we mean, for everyone.

As the OP, I'm closing this one out. This can at least act is the discussion that I originally couldn't find. Feel free to make further suggestions, that account for the above viewpoints.

**Comment by jasmussen** [comment]
This was a good discussion, thank you. It's good to have this avenue explored, and as we continue to work on this we can revisit if need be.
