### ISSUE TITLE
Rich text: Allow for multiline = false

### ISSUE THREAD

**Issue by enejb** [WordPress/gutenberg#13570]
**Is your feature request related to a problem? Please describe.**

Currently the `<RichText />` component allows for for the user to enter multiple lines. 
It would be great if there was a way to limit the that. 
This would allow for blocks to be build that would allows the user the user to enter rich text but only in a single line. 

The current usecase for that is the following Contact Info component that I am building.
![screen shot 2018-12-18 at 3 50 48 pm](https://user-images.githubusercontent.com/115071/51935474-d53dd800-23ba-11e9-8dd4-f27a31d14c88.png)
 I want to be able to let the user bold or italicize part of the address for example.

**Describe the solution you'd like**
Allow us to pass `multiple={false}` as a paramter to richtext.

**Describe alternatives you've considered**
The current solution that doesn't quite work as expected that I got working is to use 
```
<RichText 
    unstableOnSplit={ () => false } 
/>
```

**Comment by AlchemyUnited** [comment]
@azaozz - That thread ends with "looks like it's been fixed". But in the case of multiline the README sez

multiline: Boolean | String
Optional. By default, a line break will be inserted on Enter. If the editable field can contain multiple paragraphs, this property can be set to create new paragraphs on Enter.

I've glanced though the code and null or bool (e.g. false) are overridden by a default of (I believe) div. 

Perhaps a quick update of the README while this is sorted out. It cost me at least 60 - 90 minutes trying different things, checking my code, search for other sources for an answer, etc. Me thinks me and @enejb are not alone. That kinda negative scale is "bad for the brand." ;)

**Comment by AlchemyUnited** [comment]
@enejb - I'm sure you already know but that workaround doesn't work for shift+return. Which in a way maybe it's a bad thing, at least sometimes. But in terms of a couple disable of multiline, it doesn't appear to be a solution with complete coverage.

**Comment by AlchemyUnited** [comment]
Also, it looks like 

unstableOnSplit={ () => null }

unstableOnSplit={ () => true }

are the same as 

unstableOnSplit={ () => false }

Not sure if that really helps. Simply noting for completeness :)

**Comment by ellatrix** [comment]
Why not use `<input>`? I assume you also don't want to allow formatting?

**Comment by AlchemyUnited** [comment]
@ellatrix - In my case I do want to allow for formatting. For example, a heading might need a word in bold, or italic. Same for a sub-headline. But I might not want those as multi-line.

**Comment by ellatrix** [comment]
I don't follow. You're using headings in the form? In the case of headings, it should be ok to allow line breaks, just as the core headings allow it.

**Comment by chrisvanpatten** [comment]
I'm also interested in this functionality. We have cases where we want to allow controlled input for a single line of text (no line breaks or split paragraphs), with basic formatting — almost like `<TextControl>` + inline formatting. It'd be great to see that become possible.

Our example is that we have a custom image block, and supports an optional caption. In our system, we don't want to allow multiple paragraphs for a caption — just a single line of text, but it can be formatted (bold/italics/link) within that line of text — so enter or shift+enter should not have any functionality.

**Comment by timotheemoulin** [comment]
I would also like to use `RichText` to display the field as it will be rendered in the frontend (Hx title) but I need to avoid any new line to keep the frontend render consistent.

**Comment by chris-monahan** [comment]
This is marked as closed but I'm not sure what the resolution is? My testing just now shows `multiline=false` not working and the linked pull says it introduces an `Editable` component that has formatting disabled but is multiline/has a number of benefits from RichText. I think that my use case is exactly the opposite however; I want to enforce a single line input while still allowing the user to add occasional inline styles. I'm wondering what the resolution of this is for my use case or whether I'm doing something wrong here?

**Comment by erdembircan** [comment]
Using `disableLineBreaks` property instead of `multiline` solved the issue for me.

**Comment by ellatrix** [comment]
Yes `disableLineBreaks` is the correct prop.

**Comment by bikramchettri** [comment]
> Using `disableLineBreaks` property instead of `multiline` solved the issue for me.

Thanks
