### ISSUE TITLE
Bug in "Store Post Meta with a Block" tutorial's sample code, cannot edit meta data

### ISSUE THREAD

**Issue by JordanMG** [WordPress/gutenberg#13580]
In the ["Meta Block" tutorial](https://github.com/WordPress/gutenberg/edit/master/docs/designers-developers/developers/tutorials/metabox/meta-block-3-add.md), a sample plugin is provided to demonstrate how to create a block that uses Post Meta data.

The sample plugin does save the Post Meta data, but only once. You cannot edit the Post Meta data after this.

To reproduce:
1. Create a plugin using the provided code.
2. Insert the meta block and type something into the field.
3. Save the post draft or publish the post.
4. Change the contents of the meta block, save the draft or publish again.
5. Reload the editor. You will now see the new data that you entered is gone, the original data that you provided is still there.

I am trying to learn how to create a Gutenberg Block that uses Post Meta data and this has been very frustrating for me as I cannot figure out how to solve the problem on my own.

**Comment by youknowriad** [comment]
cc @mkaz @ajitbohra

**Comment by JordanMG** [comment]
On a hunch, I tested this on a new dev install and on my production site and the code suddenly worked as expected.

The first dev install, where this happened, was already plain vanilla, so I cannot explain what was wrong but I don't think the sample code is as fault.

Sorry for the confusion.

**Comment by mkaz** [comment]
@JordanMG glad to know it is working for you now. Let us know if you run into issues again.
