### ISSUE TITLE
Copying images from MS Word.

### ISSUE THREAD

**Issue by dexter-pl** [WordPress/gutenberg#13586]
Hi,

I write my documents with images in MS Word.

When I first copied all the text with images in Word and pasted into Gutenberg, all images converted to separate blocks with the image upload button, which is fine.
This was the first time. Now when I copy a document from Word to Gutenberg it doesn't seem to work, the images are just avoided.
It's even different when I copy a single image directly from Word. It copies not as a block when I can upload an image but as a block with the image already uploaded.
It would be great if I can copy all the document and all images were uploaded into Gutenberg.

**Comment by murshed** [comment]
You have to upload the image via media.

**Comment by dexter-pl** [comment]
I created a new document in Word and copied all the text with images from the old one. Now it creates the upload blocks where I can upload images.

The question is. Why I can copy directly from Word an image and it pastes a block and uploads the image automatically, but when I copy images with text it created upload blocks without uploading images.

I'm happy how it works now, but I think it would be better with an automatic upload.

**Comment by iseulde** [comment]
Hi @dexter-pl! Unfortunately, this is a limitation with MS Word. We don't have access to the images. I don't think any web editor will be able to paste the images from Word in a safe way. Let me know if you find an editor that does.
