### ISSUE TITLE
Multiple empty blocks create visual noise and make hard to edit a post

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#13599]
![screenshot 2019-01-30 at 14 43 26](https://user-images.githubusercontent.com/4389/51988903-c5e38b00-249d-11e9-8775-a55365ff45f8.png)

Multiple empty blocks add extensive visual noise to the interface. 

I understand they are there for a reason and we discussed this before, bu I'm wondering if we can find a better way to handle these scenarios.

Brainstorming possible ideas:

1. Show the text only on the first block of a type that gets added.
2. Show the text only when the post is empty and created for the first time.
3. Show the text only for the first three blocks, then stop.
4. Show the text only for the first 1 minute, then stop.
5. Show the text only until the person uses any block inserter for the first time (as it's a signal they understood how it works).

### Sidenote

This might also be related with the behaviour of stripping empty spaces when rendering — which is currently circumventable by adding a single space in an empty block (good workaround, still a workaround).

**Comment by kjellr** [comment]
I opened a related issue a while back that proposed a different solution: Keep the paragraph block's placeholder text as is, but show it on hover + select: 

![](https://user-images.githubusercontent.com/1202812/45772965-1658fb00-bc17-11e8-8336-006b0e2a6be0.gif)

More details here: https://github.com/WordPress/gutenberg/issues/10051

**Comment by sarahmonster** [comment]
@kjellr's solution seems like a good approach here in terms of both reducing unneccesary noise and bringing the unselected block appearance into closer alignment with the actual front-end output of the site.

**Comment by mapk** [comment]
I agree with Kjell's solution as well. I'm removing the "Needs Design Feedback" label.

**Comment by towfiqi** [comment]
Whats even worse is, you cannot remove them right away. You have to click and type something first on each of them to make the toolbar appear and then select the remove option.

**Comment by mapk** [comment]
I came across another solution, I _think_ implemented by @phpbits. 

When hitting enter multiple times (ie. 3 times) the interface asks you if you'd like to convert these to a Spacer block. If a setting exists that automatically makes this change every time for you, that would be wonderful.

**Comment by phpbits** [comment]
I've implemented the work around via [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. Here's the preview : https://twitter.com/phpbits/status/1181065985123446784 . Thanks!

**Comment by folletto** [comment]
While I like that idea, and I'd +1 the inclusion, I don't think it's really solving the issue mentioned, just making it a bit less visible. 

So +1 to that, and let's still find a solution for the duplication. Showing the text only when the block is active it would help :)

**Comment by mapk** [comment]
Good point. When I click `Enter` multiple times in Google Docs, I don't see placeholder text, and this feels like I should have a similar experience.

**Comment by mapk** [comment]
related: https://github.com/WordPress/gutenberg/issues/17366
