### ISSUE TITLE
api-fetch not prepending the REST API root URL 

### ISSUE THREAD

**Issue by andreasciamanna** [WordPress/gutenberg#13591]
I'm a bit stuck when dealing with `@wordpress/api-fetch`.

It might be I'm not using it as intended, and I'd like to get some lead here after searching for a solution with no success.

I have a script (bundled with WebPack) like the following:

```javascript
import apiFetch from '@wordpress/api-fetch';

apiFetch({
	path: '/wp-json/wp/v2/posts'
})
	.then(posts => {
		console.log(posts);
	});
``` 
(as described in [the documentation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-api-fetch/#usage))

`@wordpress/api-fetch` is installed in the `devDependencies`, of course.

The transpiled script is enqueued at `admin_enqueue_scripts` with `wp-api-fetch` as a dependency.

When it runs, I get `http://my-domain.tld/wp/v2/posts?_locale=user 404 (Not Found)` followed by the expected invalid JSON response error.

When I do that:
```javascript
import apiFetch from '@wordpress/api-fetch';

apiFetch({
	url: 'http://my-domain.tld/wp-json/wp/v2/posts'
})
	.then(posts => {
		console.log(posts);
	});
``` 

I get the expected response with no errors.
I can also use `path: 'http://my-domain.tld/wp-json/wp/v2/posts'` and it will still work.

I suspect this might be similar to 12801, but I don't know what else I can do to troubleshoot the issue.

I wonder if I'm missing some other dependency or, as I wrote above, I'm just not using the library as it's intended to be used.

**Comment by andreasciamanna** [comment]
Also, I'm not sure if I should have posted here or [here](https://wordpress.stackexchange.com/), sorry.

**Comment by youknowriad** [comment]
Questions belong more to the forums and the stock exchange.

But I can try to answer quickly.

Are you defining `@wordpress/api-fetch` as an external dependency. Otherwise you'd be used your own bundled version which is not bootstrapped properly. An alternative would be to just use `wp.apiFetch` global instead of importing.

**Comment by andreasciamanna** [comment]
`wp.apiFetch` did the trick!

I don't need to import or even install `@wordpress/api-fetch` at this point.

Thanks!
