### ISSUE TITLE
List block: deleting an empty bulled folds the previous one too

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#13596]
![gif - list block delete bullet](https://user-images.githubusercontent.com/4389/51987633-dcd4ae00-249a-11e9-8ab6-1355c0c858dd.gif)

Deleting an empty row in a bullet list collapses the following bullet too (deletes 2 bullets instead of just one).

To reproduce:

1. Make a bullet list
2. Delete a bullet

The deletion should just delete the current bullet point.

**Comment by iseulde** [comment]
I cannot reproduce this issue. Would it be possible to provide detailed steps to reproduce from a frosh post?

**Comment by folletto** [comment]
I'm not sure I can add more detail than that: it's literally every time there's a list and a blank line gets deleted. 

Happens on my personal site running 5.0.3 as well as WordPress·com's WP Admin.
Maybe was fixed in the meantime by something not directly related?

**Comment by iseulde** [comment]
Yeah, maybe the list rework's fixed it (#12667). I cannot reproduce any longer with master.

**Comment by youknowriad** [comment]
Yes, it seems fixed for me.
