### ISSUE TITLE
MSEdge: Blocks which add media throwing an error

### ISSUE THREAD

**Issue by JessBoctor** [WordPress/gutenberg#13607]
**Describe the bug**

When in Microsoft Edge and a user tries to add a block which uses the media library, the following error appears before they can upload or add any media: `Object doesn't support property or method 'has'`

**To Reproduce**
1. Open Microsoft Edge
2. Log into WordPress.com
3. Go to 'Add' new post
4. Try to add an `audio` block
5. See the error.

**Expected behavior**

The block would show the option to add media and allow access to the media library or uploader

**Screenshots**

![image](https://user-images.githubusercontent.com/12505355/52006717-accce100-2481-11e9-84ec-29d05f8ff239.png)

**Desktop (please complete the following information):**
 - Browser Microsoft Edge

**Comment by jorgefilipecosta** [comment]
Hi @JessBoctor thank you for reporting this issue. I moved the issue to https://github.com/Automattic/wp-calypso/issues/30545, so people working on WordPress.com can investigate this issue. I will close this issue, for now, updates should be posted on the new issue created.
