### ISSUE TITLE
List block: p to list to p breaks the p in multiple blocks

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#13600]
![gif - list block split in p](https://user-images.githubusercontent.com/4389/51989547-36d77280-249f-11e9-91b8-dccb66d4a6cb.gif)

When a paragraph block is converted to a list block and back, each item in the list is split into multiple paragraph blocks instead of reverting to the initial state.

1. (Optional) make a paragraph with multiple list items (separated by &lt;br&gt;), convert to list.
2. Convert the list back to paragraphs

Note: the transformation isn't wrong by itself. It follows a certain logic to have the list split in this way. Yet, it also felt odd the first time I saw it happening. So take this more of a discussion:

* to clarify what should be the intended behaviour
* if we can do something to make it less odd

**Comment by karmatosed** [comment]
I absolutely agree this really can break the flow when happens.

**Comment by youknowriad** [comment]
What's the alternative here? I agree that it's bad especially when it happens when you click "backspace" but as a transform, it does feel normal to me?

**Comment by folletto** [comment]
The simpler alternative is the reverse transform in the gif above at the beginning (p to list): convert to a single p block with <br>s.

**Comment by youknowriad** [comment]
I'll add the current transform is optimized for the fact that you can multi-select the paragraphs and transform them back to the list block.

**Comment by mcsf** [comment]
I think there's value in the current transformation to multiple paragraphs, but I sympathise with the issue. I wonder if we could instead solve this by having multi-selection support to transform multiple paragraphs into one multi-line paragraph.

**Comment by mcsf** [comment]
> If we don't want to convert to a single block, maybe we can consider pre-selecting all the blocks when switched, so it's possible to switch back and feels they are "one thing"?

Maybe? I'm not sure it's a pattern we'd like to introduce. That's also what the Undo button is for, and its existence has in general justified allowing transformations to be asymmetric.

**Comment by folletto** [comment]
I feel it's a sensible pattern tho as it would keep the reference on what changed, and would support visually what got converted.

Are there downsides?

**Comment by mcsf** [comment]
> Are there downsides?

No argument comes to mind. I've labeled this so we can find it once new work around multi-selection is done.

**Comment by ellatrix** [comment]
There could be two transforms: transform to one paragraph per list or one paragraph per list item.
