### ISSUE TITLE
Improve the Block Validation and Deprecation flows

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#13611]
**Is your feature request related to a problem? Please describe.**
Even a tiny edit in the block's save method results in a block error.

During validation, the block's HTML structure is checked. It makes blocks really sensitive and susceptible to block errors when something in the block gets updated, e.g. when a new feature is added.

**Describe the solution you'd like**
 I would like to propose to change this methodology. Instead of checking the expected output HTML, just run the validation thru the attribute parameters.

Old validation rules:
- Try and parse the attributes from the saved HTML, if we can't get them, fail it.
- Render the output using those attributes, if the output doesn't match the saved HTML, fail it.

New validation rule:
- Try and parse the attributes from the saved HTML, if we can't get them, fail it.

It doesn't matter when the actual output HTML is a little bit different, as long as the attributes CAN be parsed, the output should be assumed to be good. If the attributes cannot be parsed, then that's the only time the block should be deprecated.

Inspired by @fklein-lu's comment in https://github.com/WordPress/gutenberg/issues/12708#issuecomment-453420414

**Describe alternatives you've considered**
- Lots of deprecated code - some of my blocks already have 5 deprecations
- Testing against a lot of old saved block outputs - you'll have to test vs multiple outputs of old block versions with different attribute values

**Comment by HardeepAsrani** [comment]
As someone who made a 600 lines long deprecation method (even if it was just a copy and paste from edit function) because we removed a single CSS class, this issue is a light of hope. 😭

**Comment by youknowriad** [comment]
I had a discussion about this with @joemcgill and this proposal as it stands won't work. For example

```
<!-- wp:heading -->
<h2>This is a heading</h2>
<p>This is a paragraph that will be removed without notice for the user</p>
<!-- /wp:heading -->
```

This block would be considered valid.

**Comment by youknowriad** [comment]
Actually, there's already a better issue with more context, add your thoughts there if needed #7604 I'm interested in improving these flows but this is a hard problem and I haven't seen good proposals so far.
