### ISSUE TITLE
Page jumps back to top after inserting media

### ISSUE THREAD

**Issue by TeamKinetic** [WordPress/gutenberg#13619]
**Describe the bug**
When using Guttenberg and the media icon to insert some media, once inserted the page view jumps back to the top of the post.

**To Reproduce**
1. Go to any post and edit it
2. Click on 'ADD MEDIA' icon, upload a new image to your media folder and then insert that image
3. See error

**Expected behavior**
I expect the screen to stay at the position I inserted the media

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 71.0.3578.98

WORDPRESS 5.03

**Comment by tellthemachines** [comment]
Hi there,
I'm having trouble reproducing this issue. Is the media icon you refer to the image block, or the "add media" button in the classic editor block? It would be great if you could upload a screenshot or a short video showing the problem. Thanks!
