### ISSUE TITLE
After updating to wordpress 5.0.3: 403 forbidden after saving page

### ISSUE THREAD

**Issue by mlonline** [WordPress/gutenberg#13626]
After updating to wordpress 5.0.3, saving the page (home page) in the new Gutenberg editor results in confirmation 'Page updated.' but on top the updating button keeps beeing disabled and the saving message keeps blinking.

In the development console I am seeing:

![image](https://user-images.githubusercontent.com/22023643/52085164-0a594e80-25a4-11e9-9a1e-bf182d31bfe1.png)

What could be the reason for that behavior?

**Comment by mlonline** [comment]
Thanks for your reply. I am indeed using both of those plugins and will check further there why this issue occurs.

**Comment by mlonline** [comment]
After updating both of those plugin to the newest version the issue is resolved. Thanks!

**Comment by jayhill90** [comment]
No problem! It is always good practice to do some troubleshooting to isolate the issue further. I’m glad that helped sort things out.

**Comment by janar-rahumeel** [comment]
Could be also WAF rule related issue. Please check the WAF rules and exclude any what gives false positive.
