### ISSUE TITLE
How to get Editor State

### ISSUE THREAD

**Issue by fallinthehole** [WordPress/gutenberg#13632]
Hello!  I have a pretty easy goal - i have parent component which has `<InnerBlocks/>`. Each inner block has index when i inspecting him via React dev tools. I want to get index of each inner block component by using method from gutenberg documentation: https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-editor/#getblockindex

Each time it's returning `-1`. One of required arguments is `editor state`. So question is - how can i get this `editor state`. It should be obvious but seems like i missed something. 

Thanks for help, appreciate your attention a lot!

**Comment by jayhill90** [comment]
https://github.com/WordPress/gutenberg/pull/4105 may contain the information you're looking for.

**Comment by youknowriad** [comment]
Hi there! thanks for the issue. This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

That said, you probably want to use the `withSelect` higher order component (it will automatically pass the state value, you should only pass the remaining arguments).

See the documentation of the data module https://developer.wordpress.org/block-editor/packages/packages-data/

This [blog post](https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/) might come handy as well.

Thank you!
