### ISSUE TITLE
Allow media metadata to be set when uploading from block editor

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#13642]
**Is your feature request related to a problem? Please describe.**
When uploading an image in the media manager, you can set the title, default caption, and description. When uploading an image via the block editor, you cannot set these fields - the caption you set in the editor is only displayed under the image in that post, and not saved to the underlying media object. This discourages reuse of images across posts and pages and makes it harder to search for images using the media manager.

**Describe the solution you'd like**
I would like to be able to set the title, shared caption and description from the block editor, and have those changes reflected in the media post object the image is associated with.

**Describe alternatives you've considered**
Avoiding to add images through the image block, instead clicking the media manager button and uploading it, setting the caption then selecting it for use in the post. Extra clicks, unintuitive, and most users will ignore this small extra step.

**Comment by jeherve** [comment]
I also discovered this problem, after realizing that using `wp_get_attachment_metadata()` to fetch an image's caption was not reliable when using the gallery block (see https://github.com/Automattic/jetpack/issues/11594 for more information).

I understand that it can be handy for an author to set different captions for the same image on different posts, but on the other end it now makes it more difficult for third-parties to get an image's caption. Is there a quick way to get the caption from an image in a block, short of using `parse_blocks` and manually going through the block's content?

**Comment by youknowriad** [comment]
@jeherve you can parse blocks at the moment but this will only give you the attributes saved in the comment, not the ones sources from the content.

To be able to parse these attributes as well we need:

 - Server-side awareness of the registered blocks
 - PHP parsers for the different type of sourced attributes

Both of these are something we want to get into at some point, but not in the short term.

**Comment by mapk** [comment]
We talked about this in [today's triage in slack](https://wordpress.slack.com/archives/C02S78ZAL/p1571760412304600). It's a tough decision, but in relation to @youknowriad's comments and the fact that the Media Library is probably the best area to manage media, the Design Team is suggesting we close this issue for now.
