### ISSUE TITLE
What's the correct way to get list of all posts?

### ISSUE THREAD

**Issue by justanotherco** [WordPress/gutenberg#13640]
I looked everywhere and can't find the official/recommended way to have a select component in the InspectorControls that has a list of all posts.

I can create a select element, but how can I get an array of all posts on the site to populate it?

**Comment by youknowriad** [comment]
Hi there! thanks for the issue. This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

That said, the canonical way is to use the data module and the `getEntityRecords` selector. See the documentation of the data module for instance https://developer.wordpress.org/block-editor/packages/packages-data/

This [blog post](https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/) might come handy as well.


Thank you!
