### ISSUE TITLE
leading space after past from word

### ISSUE THREAD

**Issue by Alexufo** [WordPress/gutenberg#13647]
**Describe the bug**
Past text from attachment [КОВДА. ЗА ЗА1.docx](https://github.com/WordPress/gutenberg/files/2826040/1.docx)
 to block editor. 

You will see leading space on every line.

 

**Desktop (please complete the following information):**
 - win10
 - Opera 57

**Comment by youknowriad** [comment]
Just tried, and it works as expected for me.

<img width="498" alt="capture d ecran 2019-02-04 a 4 34 48 pm" src="https://user-images.githubusercontent.com/272444/52218373-d2e7ec00-289a-11e9-9431-efa73f5cd140.png">

What do you expect to be different (see screenshot)?

**Comment by Alexufo** [comment]
After pasting I remove leading spaces. The spaces don't present on original document. 

![wf2](https://user-images.githubusercontent.com/1562329/52232950-e90f9f80-28ce-11e9-81b5-48d7212b43bc.gif)

**Comment by youknowriad** [comment]
Thanks for the screenshot @Alexufo I was probably using another docx reader (not MS word in Windows)
