### ISSUE TITLE
Redesign failure

### ISSUE THREAD

**Issue by indig0F10w** [WordPress/gutenberg#13646]
Gutenberg is the worst redesign to ever be encountered in software products. I mean, you even topped Reddits redesign fail, that is some epic achievment. But at least they give you the option to stay on old design which is 100% more user friendly.

Some of the problems:
- you made inserting files harder
- block options popup covers content
- almost impossible to make a list with file links
- options all over the screen instead on one convenient toolbar like it was
- slow AF
- usability is dead
- unable to turn off failed "Gutenberg hints and tips" tutorial, always shows on login
- released Failberg with thousands of bugs, do you want to be Windows 10 of web desing?

**Comment by youknowriad** [comment]
Thanks for the feedback and I'm sorry Gutenberg didn't work so well for you.

Would you mind spitting this into discrete actionable issues (if not already existing?). As it's it stand it's very hard to do anything tangible here.
