### ISSUE TITLE
Make the modal title styling consistent

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13650]
The modal title has the following default styling:

<img width="710" alt="screenshot 2019-02-04 at 09 28 36" src="https://user-images.githubusercontent.com/1682452/52198614-b3819c80-2863-11e9-96b0-501852083a31.png">

The keyboard shortcut modal wraps the title in a `<span>` element, which is then styled with a bigger font size and bold font weight:

<img width="540" alt="screenshot 2019-02-04 at 09 29 20" src="https://user-images.githubusercontent.com/1682452/52198666-ddd35a00-2863-11e9-9051-6ecddb6ad835.png">

https://github.com/WordPress/gutenberg/blob/ee2d5c7a0d9462ee8162e851d298ea0349787327/packages/edit-post/src/components/keyboard-shortcut-help-modal/index.js#L72-L75

If the styling with the bigger font size and bold font weight is preferred, I'd suggest to make it the default in the Modal component instead of overriding it on a case by case basis. This way, all the modals (even the ones added by plugins) will have the same styling.

**Comment by kjellr** [comment]
Agreed, the larger font size and bold text seem reasonable to use in all modals by default.
