### ISSUE TITLE
`Default` style variation label to match the `is-style-default` class name

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#13660]
**Problem**

The style variation for the separator block has the class `is-style-default` in the code, but reflects the style variant as "Short line". Thanks to @webmandesign for this find! While the issue #10569 and PR #10570 suggest a change from `default` to `short` to match the name, it seems to lock in themes to use a 'short' line as their default. I believe @jasmussen explained it well in the PR review in #10570.

**Solution**

Any block with style variations should reflect the word "Default" in the style variation preview as shown below.

<img width="496" alt="default" src="https://user-images.githubusercontent.com/617986/52247816-3aed0100-28a0-11e9-8207-d225c34f9944.png">

This should apply to:

* Separator block
* Blockquote block
* Pullquote block
* Table block
* Button block

cc @jasmussen & @kjellr Does this sound right?

**Comment by kjellr** [comment]
Sounds good! I opened #13670 13670 to take care of this.
