### ISSUE TITLE
Alternative for wp_get_attachment_image_attributes hook?

### ISSUE THREAD

**Issue by ihdk** [WordPress/gutenberg#13661]
Hello, I've read another issues related to `wp_get_attachment_image_attributes` hook, but can't find an clear answer.
Currently, `wp_get_attachment_image_attributes` hook cannot be used for images inserted in Gutenberg editor, for example Gallery Block or Image block...
Is there another alternative which replaced the `wp_get_attachment_image_attributes` hook? So can I modify (or add) new attributes for <img/> tag like it was possible using `wp_get_attachment_image_attributes` hook for images shown via gallery shortcode for example?

What i simply need, is add attribute for <img/> tag which store sizes of original image shown using gallery block.

Thanks, Ivan.

**Comment by danielbachhuber** [comment]
Hi @ihdk,

There isn't an equivalent to `wp_get_attachment_image_attributes` right now, to my knowledge. 

Could you change your underlying implementation somewhat? What if you were to parse `the_content` on render, query for the original image sizes, and then enrich your markup on display?

**Comment by ihdk** [comment]
Hi @danielbachhuber , thanks for your response. I'll take a look at your recommendation closer to see what can be done.
Thanks again, Ivan.

**Comment by danielbachhuber** [comment]
Sounds good! Feel free to follow-up if you run into specific questions. Also, if you find any place where the documentation could be improved, please create a new issue.
