### ISSUE TITLE
Updated category selection fails to update permalink 

### ISSUE THREAD

**Issue by alexander-morris** [WordPress/gutenberg#13676]
**Describe the bug**
The new editor no longer has the ability to specify a particular permalink category. There used to be a heart icon in the UI next to the categories, but now the permalink seems to just reflect a the first category selected, and does not update when the category selection is changed.

**To Reproduce**
We currently use the format ```/%year%/%monthnum%/%category%/%postname%/``` for our permalinks, and it seems that once the category is set for a post, the permalink category remains the same even when the category is changed. In the event that there is more than one category, the permalink seems to reflect the first one alphabetically.

**Expected behavior**
The new editor needs some way to edit the permalink category directly, rather than implicitly. 

**Screenshots**
The new version looks like this:
![new](https://user-images.githubusercontent.com/37120777/52289431-a3d18900-2933-11e9-8a7c-75780fd6cf2f.png)

While the old one worked like this: 
![old](https://user-images.githubusercontent.com/37120777/52289433-a3d18900-2933-11e9-8460-597f8c15b578.png)

Furthermore, in the new editor it doesn't seem to update the permalink, even after the category in the link has been removed and the post has been updated:
![new-issue](https://user-images.githubusercontent.com/37120777/52289554-e2674380-2933-11e9-9874-7395037d275b.png)

**Comment by jonathanstegall** [comment]
I've seen this bug while using the [WP Category Permalink](https://wordpress.org/plugins/wp-category-permalink/) plugin (which I depend on for the task mentioned in the issue).

The plugin was updated 4 months ago to fix a deprecated warning in PHP 7.2, but there's a [sticky post](https://wordpress.org/support/topic/about-the-support-of-this-plugin/) from 11 months ago that indicates no willingness to maintain the plugin beyond merging pull requests ([this](https://github.com/jordymeow/wp-category-permalink) is the GitHub repo).

It'd be great to see the functionality from this plugin in Gutenberg; it's one of the main reasons I'm sticking with the Classic Editor plugin as long as possible, but I thought it might be helpful to provide that context.

**Comment by jorgefilipecosta** [comment]
Thank you all for your insights. It seems this issue does not involve a feature that is part of the core editor (the feature is provided by a plugin) so I guess we should close the issue. There is a PR open on the plugin repository that may address the issue https://github.com/jordymeow/wp-category-permalink/pull/5.
