### ISSUE TITLE
Nested button alignment and focus problems

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#13681]
Conditions to reproduce:

1. Add a button block inside another block (e.g. media and text or columns).
2. Align the button left or right using the toolbar actions
3. Un focus the button block
4. Attempt to focus the button block again and notice that there's no blue border when you hover and you can only focus by clicking directly on the button itself.
5. Notice the button seems to break outside of the containing blocks wrapper when aligned right as well.

It's easier to describe with a gif :)

![gif](https://cldup.com/F4xHCMwHsv.gif)

**Comment by draganescu** [comment]
Howdy @jameskoster Indeed this bug still exists, and it looks like the problem is that the parent block collapses because of the alignment (which is a float). 

The outline doesn't exist anymore, but we still have the border with the label that should appear on hover and it doesn't.

**Comment by mtias** [comment]
@draganescu @jameskoster Is this still the case after the latest design work?

**Comment by jameskoster** [comment]
The original issues no longer exist as far as I can tell.
