### ISSUE TITLE
Post visibility and publish date toggle buttons misplaced in IE11

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1368]
In the Publish box, the visibility and publish date toggle buttons are misplaced _when their related "popover" is open_:

![screenshot 107](https://user-images.githubusercontent.com/1682452/27435307-1187b9fc-575c-11e7-9d5a-6a4bc319c425.png)

![screenshot 108](https://user-images.githubusercontent.com/1682452/27435308-1189526c-575c-11e7-9da9-c7b5088cc4bd.png)

**Comment by mtias** [comment]
Is this still reproducible?

**Comment by afercia** [comment]
Can't reproduce any longer, see screenshot below: IE11 and latest master:

![screenshot 11](https://user-images.githubusercontent.com/1682452/33018148-84946b56-cdf5-11e7-9b8c-9204f467db8a.png)

**Comment by mtias** [comment]
Thanks for checking!
