### ISSUE TITLE
Reuseable Block Settings

### ISSUE THREAD

**Issue by canadabri** [WordPress/gutenberg#13680]
The reuseable blocks are great, but because it is a single block that is used in its entirety on the website, it is limited to a single content item.

It would be helpful to also have reuseable block settings so that blocks can be styled once, and that style applied to a new block that is opened from a reusable block settings selection.  Then you just update to what content applies and a new block gets added.  Change the settings, and they all get updated with the new look.

This will help website owners have site content that is styled consistently throughout.

This idea came to me as I was adding post grids for my various categories and the styling options included the background color, read more button settings, header text size, color etc.   Re-doing the post grid for many categories could have been faster, and more consistent if the style could have been set once then reused.

**Comment by youknowriad** [comment]
Thanks for the issue.

If I'm not mistaken you're asking for something similar to #8403 so I'm closing as a duplicate.
