### ISSUE TITLE
how to use a reusable block in a template_

### ISSUE THREAD

**Issue by derridHeidegger** [WordPress/gutenberg#13686]
hi
i have a post template that looks like this:
`<?php
function my_add_template_to_posts() {
  $post_type_object = get_post_type_object( 'post' );
  $post_type_object->template = array(
    array( 'core/paragraph', array(
          'placeholder' => __('Start writing your post'),
      ) ),

  );
  //$post_type_object->template_lock = 'insert';
}
add_action( 'init', 'my_add_template_to_posts' );`

what should i do inorder to use here a reusable block? like social share? or whatever other reusable block i have?

**Comment by youknowriad** [comment]
Did you try something like?

```php
array( 'core/block' => array( 'ref' => $id_of_reusable_block ) )
```

**Comment by derridHeidegger** [comment]
hi thanks for the answer
i have tried it and got the error: TypeError: e[Symbol.iterator] is not a function
is the id the post id? maybe i am wrong here?

**Comment by youknowriad** [comment]
@derridHeidegger I'm not certain if it's the post id, probably not. Try to insert the reusable block in a post and check the output.

Also opening for more testing.

**Comment by derridHeidegger** [comment]
i took the id of the generated block and still get the error

**Comment by derridHeidegger** [comment]
anyone?

**Comment by youknowriad** [comment]
Oh sorry, I had an error in the code I shared. Here's the correct template format:

```
array( 'core/block', array( 'ref' => $id_of_reusable_block ) )
```

**Comment by derridHeidegger** [comment]
that is working thanks
