### ISSUE TITLE
Alignment class is undefined

### ISSUE THREAD

**Issue by thejaydip** [WordPress/gutenberg#13696]
**Describe the bug**
Create new gallery with Gallery block and see inspect elements in your browser and see the issue (alignment class is undefined), please see below attached image for more information.

**To Reproduce**

1. Click on Gallery block
2. Create new gallery
3. Inspect Elements of new created gallery in your browser

![gallery-block](https://user-images.githubusercontent.com/46511743/52340815-c8faf000-2a36-11e9-8704-93f060559fa1.png)

**Desktop (please complete the following information):**
OS: Linux
Browser Chrome
Version 70.0.3538.77
Additional context

**Gutenberg: latest from master**
WordPress: 5.0.3

**Comment by thejaydip** [comment]
Above issue will fixed if we replace below code in block-library.js ( Go to line no. 5127).

className: "".concat(className, " align").concat( align !== undefined ? align : 'center', " columns-").concat(columns, " ").concat(imageCrop ? 'is-cropped' : '')

**Comment by Jackie6** [comment]
Hi @thejaydip  I cannot reproduce the bug. There is no alignment class in the wp-block-library if the align button is not pressed.
![image](https://user-images.githubusercontent.com/24849874/54859177-82104380-4ce0-11e9-8bdd-5961c20c3e45.png)

**Comment by nicolad** [comment]
Please take a look at the PR with fix: https://github.com/WordPress/gutenberg/pull/14603

**Comment by gziolo** [comment]
I can't reproduce as well:

![Screen Shot 2019-03-25 at 07 48 47](https://user-images.githubusercontent.com/699132/54900138-784e3200-4ed2-11e9-8c3e-c3d0cab9bcbf.png)
