### ISSUE TITLE
Column block can be moved in itself

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/gutenberg#13701]
**Describe the bug**
I moved accidentally the column block in itself. The editor crashes an error message I can't fully read because it redirects me to "about:blank".

**To Reproduce**
1. Add column block
2. Do not add any blocks to the columns
3. Move the column block in one of the column spaces
4. BOOM.

**Expected behavior**
I should not be able to move the column block in itself.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Firefox
 - Version 65

**Additional context**
WordPress 5.0.3

**Comment by Naerriel** [comment]
I can't reproduce this bug neither on Chrome nor on Firefox.

Is this what you mean by moving the column block in itself?
![image](https://user-images.githubusercontent.com/13454526/52495548-4bb7b280-2bd1-11e9-816d-4d0a5897b89e.png)

**Desktop**
- OS: Ubuntu 16.04.4
- Browsers: Firefox 64 and Chromium 71.

Can somebody with macOS confirm, please?

**Comment by Zodiac1978** [comment]
It looks like there have to be a block before. Here you can see the bug in action:
![column-bug](https://user-images.githubusercontent.com/870475/52497012-3fcdef80-2bd5-11e9-90e6-b96439ca521f.gif)

**Comment by Naerriel** [comment]
Thank you, I was able to reproduce the issue.
I will see what can be done. :smile:
