### ISSUE TITLE
Alert message when editing a reusable block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13704]
Below content has been edited.

We need an alert/warning message when we edit an reusable block.

After having converted a block into a reusable block when sees a notification telling the user that the block has been updated.
![reusable-block-being-edited](https://user-images.githubusercontent.com/5323259/52418665-ce1b7600-2aee-11e9-95c9-603451f12111.jpg)

Before clicking Edit
![screen shot 2019-02-07 at 15 17 53](https://user-images.githubusercontent.com/5323259/52419149-d2945e80-2aef-11e9-864d-6ee828914a7d.png)

Having clicked edit
![screen shot 2019-02-07 at 15 18 10](https://user-images.githubusercontent.com/5323259/52419159-daec9980-2aef-11e9-8171-de38e8603a5d.png)

Clicking save
![screen shot 2019-02-07 at 15 46 33](https://user-images.githubusercontent.com/5323259/52419204-f061c380-2aef-11e9-8934-11d8d3053734.png)

We need an alert message saying something like:
Editing a reusable block will affect all instances of the block on all pages it is used.
Do you want to continue editing? 
With options Yes - No - Convert into regular block.

Here is one suggestion using the default notification system:
![warning-notification-gutenberg-editing-reusable-block](https://user-images.githubusercontent.com/5323259/52419813-26ec0e00-2af1-11e9-8417-10847ada82fc.jpg)

**Comment by alexislloyd** [comment]
I think this could be a good opportunity for using Material-style "snackbar" messaging. It provides a nice balance of giving the user a notification without adding too much additional friction to the editing experience. Especially when you think of this as something that, in the future, could be used whenever a user edits site-wide blocks like a navigation menu or header, we would want to be careful about doing something that adds another click to each of those edits. 

Here's a quick mockup of this at the bottom of the screen: 

![image](https://user-images.githubusercontent.com/3238155/53752753-6eaa4f00-3e7d-11e9-95ef-f9ab80729da7.png)

**Comment by youknowriad** [comment]
Agreed, Snackbar seems like a good pattern for a lot of our notices. Other notices should stay as they are I'd say like: autosave notices, the template synchronization (the notices shown when you load the page and you need to make a decision based on them) but for most of the other notices, Snackbar makes sense.

Let's close and consolidate with #13905
