### ISSUE TITLE
Content sometimes not saved upon hitting save

### ISSUE THREAD

**Issue by apermo** [WordPress/gutenberg#13729]
**Describe the bug**
Occasionally content from within the editor is not saved.

Some of my editors reported this to me, so it's not just a single user issue.

Sometimes when the editors hit "save", the UI reports back that it's successfully saved, but when reloading the site, or viewing it in the frontend, it will show the old/former content.

Applies to Headline and the content itself

**To Reproduce**
Sadly not easily no idea yet, will update once I figure out

**Expected behavior**
At least give a proper error message if saving failed.

**Desktop (please complete the following information):**
Multiple

**Comment by apermo** [comment]
I'm trying to gather more information from my editors.

**Comment by youknowriad** [comment]
Closing at the moment, let's reopen if we have steps to reproduce.
