### ISSUE TITLE
getColorClassName is not returning the expected value

### ISSUE THREAD

**Issue by alantucker** [WordPress/gutenberg#13720]
Not sure if this is an error on my part or a bug but when using getColorClassName is not returning the expected value.

`const overlayColorClass = getColorClassName(
      "background-color",
      overlayColor
    );`

The output should be **has-primary-background-color** but I am getting **has-0073-a-8-background-color**

Any help would be greatly appreciated.

**Comment by swissspidy** [comment]
What's the value of `overlayColor`? It should be an object. Looks like you're passing a hex color instead of the color slug.

This might help: https://javascriptforwp.com/forums/topic/how-to-get-a-color-class-name/

**Comment by alantucker** [comment]
Hi

Thanks for the reply, these sholuld help...

https://gist.github.com/alantucker/8db9630441148cab7432f66eabf44ac9

https://gist.github.com/alantucker/2e534a54065f2e079ce53094c2dfc2c1

Thanks again

**Comment by swissspidy** [comment]
Please have a look at what `getColorClassName()` actually does:

https://github.com/WordPress/gutenberg/blob/3111e48392b4d6d01a681bc149be7526bdb3e44a/packages/editor/src/components/colors/utils.js#L45-L59

It basically does concatenate the two strings you pass, while the `colorSlug` needs to be something like `primary` or `green`, not a color value.

The important question is: Where did you define that `primary` ==== `#0073a8`? Did you set this color in your theme?

**Comment by alantucker** [comment]
Hi

No custom colours have been defined in my plugin. I am using the default colour from PanelColorSettings

`
              <PanelColorSettings
                title={__("Overlay Color Settings", "awesome-blocks")}
                initialOpen={true}
                colorSettings={[
                  {
                    value: overlayColor,
                    onChange: overlayColor => {
                      setAttributes({ overlayColor });
                    },
                    label: __("Overlay Color")
                  }
                ]}
              />
`

The following outputs **has-0073-a-8-background-color**

`const overlayColorClass = getColorClassName(
      "background-color",
      overlayColor
    );`
`console.log(overlayColorClass);`

Where the following outputs **#0073a8**

`console.log(overlayColor);`

How do I get the `colorSlug` ?

Thanks for the help

**Comment by perryjr84** [comment]
Plus one for me having same issue....if i find a solution I'll try to remember to let you know. Not finding much docs or example though

**Comment by alantucker** [comment]
I ended up making it inline but did some test dev using the following which worked but I am not sure if its the best way...

[https://javascriptforwp.com/forums/topic/how-to-get-a-color-class-name/#post-84683](https://javascriptforwp.com/forums/topic/how-to-get-a-color-class-name/#post-84683)

Thanks
Alan
