### ISSUE TITLE
Multiple spaces are rendered as one unless "&nbsp;" is used

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#13727]
**Describe the bug**
Multiple spaces are being rendered as one in the drontend unless "&nbsp;" is used

**To Reproduce**
1. Create a paragraph
2. Add multiple spaces between two words
3. See that it displays ok in the backend but not in the frontend

**Expected behavior**
The frontend should look the same as the backend.

**Screenshots**
Backend:
![image](https://user-images.githubusercontent.com/1785641/52404951-34ab8e80-2b05-11e9-9618-fa4b97984a8f.png)
The HTML in the backend:
![image](https://user-images.githubusercontent.com/1785641/52405064-6f152b80-2b05-11e9-8372-4fefdf340053.png)

Frontend:
![image](https://user-images.githubusercontent.com/1785641/52404999-44c36e00-2b05-11e9-8fdf-5e1e9ead396c.png)

**Versions:**
 - WP: 5.0.3
 -  Theme: Twenty Seventeen
 - Broswer: Chrome

**Comment by youknowriad** [comment]
Isn't this the regular behavior in HTML? 

cc @iseulde I think you worked on something like that recently.

**Comment by iseulde** [comment]
Yes, this is normal behaviour. You have to insert something other than normal spaces to space out the content because spaces (along with newlines and tabs) are used in HTML to format the markup. On a Mac they can be inserted with option+space.

**Comment by iseulde** [comment]
Also, if you're looking to space things out like that, I'd recommend using the table or preformatted (not code!) block instead.

**Comment by grappler** [comment]
The classic editor was able to convert the spaces to non-breaking spaces without any issue.

![image](https://user-images.githubusercontent.com/1785641/55687640-98b8ca80-596f-11e9-92e3-3654ed3f32e9.png)

![image](https://user-images.githubusercontent.com/1785641/55687647-a53d2300-596f-11e9-9df3-66fcf773d995.png)

![image](https://user-images.githubusercontent.com/1785641/55687657-c271f180-596f-11e9-9776-2ec3177437c9.png)

**Comment by ellatrix** [comment]
@grappler Yes, which caused other bugs where non breaking spaces were inserted by the browser in random locations. I could look into adding this behaviour on serialisation (done by us instead of the browser) if this is a highly requested feature.
