### ISSUE TITLE
Module build failed: SyntaxError:

### ISSUE THREAD

**Issue by chiraggmodi** [WordPress/gutenberg#13726]
I am trying to copy heading block from gutenberg core to my theme, but i am getting 
`Module build failed: SyntaxError: Unexpected token (102:6)`
to this URL

```
 transform( node ) {
  101 |                                         return createBlock( 'core/heading', {
> 102 |                                                 ...getBlockAttributes(
      |                                                 ^
  103 |                                                         'core/heading',
  104 |                                                         node.outerHTML
  105 |                                                 ),
```

**Comment by youknowriad** [comment]
Gutenberg source uses some babel plugins to transform the code. If you want to copy the code as is, you need a similar setup to build the JavaScript files. 

If you're new to JavaScript build tools, you might want to read some docs before.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/javascript/versions-and-building/

Thanks.
