### ISSUE TITLE
Make the padding between blocks clickable to select the blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#13723]
Extracting from / inpsired by #13695. 

In between every block, the sibling inserter (a.k.a. "inbetweenserter" or "appender") sits. This is full-wide, and takes up the full padding between two blocks, even though only the button in the center is clickable. This is because when you hover the area between the full blocks, we surface the plus in the middle to indicate where to click. 

But this also means clicking this padding in between blocks doesn't do anything, because the big bar intended to capture the hover also captures that click. Here's a GIF that explains what's going on:

![padding](https://user-images.githubusercontent.com/1204802/52403694-9b11bc00-2ac7-11e9-88af-9f8c64a9c082.gif)

The transparent blue is the hoverable area that shows the plus in the middle.

The coral is the full block, including the 14px padding that surrounds every block.

Can we make it so clicking this padding even above and below blocks selects the parent block, AND surfaces the sibling inserter? I.e. could we propogate the click through this appender to select the block below?

**Comment by m-e-h** [comment]
I've struggled trying to select `hr` blocks . I think this would help.

**Comment by talldan** [comment]
Related - https://github.com/WordPress/gutenberg/issues/12163.

It seems as though it used to be possible to click that region.

**Comment by gziolo** [comment]
It would also help to solve #12577.

**Comment by gziolo** [comment]
@jasmussen, I don't think this is constrained on the technical considerations. It's all pure design decision. I personally would be fine with having two DOM elements on top of each other. One which exists only to trigger the hover effect but propagates clicks to the layer below. The second which is the inserter button or a bit wider area to make it easier to click.

**Comment by jasmussen** [comment]
> It's all pure design decision. I personally would be fine with having two DOM elements on top of each other. One which exists only to trigger the hover effect but propagates clicks to the layer below. The second which is the inserter button or a bit wider area to make it easier to click.

I'm having a bit of difficulty parsing this, can you elaborate? Reading this it seems like you are describing what is in place already today. We have a containing div that spans the width of the main column, called `block-editor-block-list__insertion-point-inserter`. This div exists to show the plus button in the center, and that plus button is called `block-editor-inserter`. The "only" piece missing here is the code to propogate clicks on `block-editor-block-list__insertion-point-inserter` to whatever is below it. Do you have a simple fix for it? I'd approve in a heartbeat!

**Comment by gziolo** [comment]
> The "only" piece missing here is the code to propogate clicks on `block-editor-block-list__insertion-point-inserter` to whatever is below it. Do you have a simple fix for it? I'd approve in a heartbeat!

Yes, exactly. We only miss that part :)

**Comment by aduth** [comment]
> Related - #12163.
> 
> It seems as though it used to be possible to click that region.

Is it duplicate?

**Comment by gziolo** [comment]
Yes, it’s duplicate. One of them should be closed.

**Comment by aduth** [comment]
For additional context, I'm copying @ktmn's comment from the now-closed #12163 :

> **Describe the bug**
> You can no longer activate a block when clicking in the green area indicated on the image:
> 
> ![](https://user-images.githubusercontent.com/1204802/48617788-b0c78780-e997-11e8-8f32-d41258c36305.png)
> 
> Video of current Frontenberg (Gutenberg 4.5.0):
> 
> ![cantselect](https://user-images.githubusercontent.com/6892634/48832493-ee565700-ed81-11e8-964c-770d7c4dbb47.gif)
> 
> Can only select a paragraph by clicking on the rich text directly.
> 
> Video of Gutenberg 4.1.1:
> 
> ![canselect](https://user-images.githubusercontent.com/6892634/48832500-f31b0b00-ed81-11e8-9d1e-38b587030c3b.gif)
> 
> Could select the paragraph by clicking whereever the blue border hover effect appears.
> 
> In some nested block scenarios there is very little area available to click to select a "parent" block:
> 
> ![](https://camo.githubusercontent.com/3899fcfc5e42c7d2d70222c96da19a49447025bd/68747470733a2f2f692e696d6775722e636f6d2f356a6330447a792e706e67)
> 
> forcing the use of Block Navigation item in the top toolbar, which is somewhat cumbersome for a simple goal.
> 
> **Additional context**
> 
> Likely a regression of #11018
> 
> More info at [#11357 (comment)](https://github.com/WordPress/gutenberg/pull/11357#issuecomment-439538510)

**Comment by youknowriad** [comment]
I think this is addressed now. Let me know if you think otherwise.
