### ISSUE TITLE
Can't scroll the sidebar when its height exceed the display height

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1373]
The sidebar uses a fixed positioning, this makes impossible to scroll it when there are multiple meta boxes open (also: plugin can add more meta boxes):

![screen shot 2017-06-22 at 15 55 44](https://user-images.githubusercontent.com/1682452/27438498-b9d89d34-5765-11e7-9d1e-0de98d5b7adb.png)

Of course this depends on the display size, 15'' retina here.

**Comment by youknowriad** [comment]
closed in #1377
