### ISSUE TITLE
Using styled-components in the save() function

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#13743]
Hi,  

I am trying to use [styled-components ](https://www.npmjs.com/package/styled-components) and other react components on the save() function, but it is not working, the styled-component works just fine on the editor ( edit function ), here is my code for the block: 
```
const { __ } = wp.i18n;  
const { registerBlockType } = wp.blocks;

import styled from 'styled-components';


registerBlockType( 'gutenword-blocks/posts', {
    title: 'Styled Div',
    icon: 'admin-page',
    category: 'layout',


    edit: function( props ) {
        const StyledDiv = styled.div`
            height: 300px;
            width: 300px;
            background: red;
        `;
        return <StyledDiv></StyledDiv>;
    },

    save() {
        const StyledDiv = styled.div`
            height: 300px;
            width: 300px;
            background: red;
        `;
        return <StyledDiv></StyledDiv>;
       
    },
} );
```

**Expected behavior**
The block when added should show red square on the editor screen and on the front-end 

**Current behavior**
The red square is showing only on the editor and nothing is showing on the frontend 

I read this post here 
https://github.com/WordPress/gutenberg/issues/11714

[roborourke](/roborourke) Has suggested to load react on the front end too and use `ReactDOM.render()` on the blocks, and I didn't understand how to do that

**Comment by youknowriad** [comment]
Hi there!

The save function is only a serialization of the block in post_content, it doesn't actually support using components with lifecycle etc... These are not rendered as React components in the frontend.

If that's the intentation, you'd have to mount/render a wp.element/React application on your own in the frontend with a custom script.
