### ISSUE TITLE
Search block: add filters to make it possible enchance the block

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#13747]
**Is your feature request related to a problem? Please describe.**

If a plugin is enhancing search feature, users might expect those enhancements to apply to core search block.

If plugin simply needs to add additional search inputs (and hence block args) below the actual search term, it should be possible via filters both at the backend and in the editor UI.

A plugin could completely overwrite the core search block, but I'm not sure how nicely that would play if multiple plugins would try to do the same. Overwriting also generally results in more duplicated code because plugin developers would need to implement basic features like search term input and submit button.

**Describe the solution you'd like**

Both backend rendering and editor UI would need filters (or React portals similar to sidebar slots?) to be able to add their own controls in the block:

- https://github.com/WordPress/gutenberg/blob/dc7013ed9e7a4f9534d3acd2e36d2ec8a8be3bab/packages/block-library/src/search/index.php
- https://github.com/WordPress/gutenberg/blob/dc7013ed9e7a4f9534d3acd2e36d2ec8a8be3bab/packages/block-library/src/search/edit.js

I'd imagine similar needs for blocks like comments block so perhaps there's a change to create some generic Block-Slot mechanism?

**Describe alternatives you've considered**
Without filters to extend the core block, each plugin would have their own search block.

cc @gibrown

**Comment by youknowriad** [comment]
There are already filters to extend the block `registerBlockType` filter. At first sight, it does seem like all what's needed here is possible. 

Noting that it was argued that the hooks/filters API is not the best API for JS extensibility and we'd want to limit its usage.

**Comment by simison** [comment]
>There are already filters to extend the block `registerBlockType` filter. At first sight, it does seem like all what's needed here is possible.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#blocks-registerblocktype

Wouldn't that require overriding the whole `edit` for the block? I'd expect to have filters that extend edit's output, not filters that extend the block settings per se. Unless I'm missing something?

**Comment by simison** [comment]
>Noting that it was argued that the hooks/filters API is not the best API for JS extensibility and we'd want to limit its usage.

Yep, I could see that. I'm not very familiar with React portals but I'd imagine it could be useful here instead of filters.

**Comment by youknowriad** [comment]
> Wouldn't that require overriding the whole `edit` for the block? I'd expect to have filters that extend edit's output, not filters that extend the block settings per se. Unless I'm missing something?

You can use the existing edit function inside the newly provided edit function.

**Comment by simison** [comment]
Gotcha, I think I'll go experimenting a bit and get back here if we hit a wall. :-)

Thanks @youknowriad !
