### ISSUE TITLE
Image block doesn't update target href if default target is changed by a hook

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#13749]
**Describe the bug**
When you hook into e.g. `registerBlockType` and change the `linkDestination.default` setting for the `core/image` block to e.g. `media` (the default is `none`), the new target is shown by default in the drop-down select box when an image is added, as expected, but the `href` property linking to the image is not set. This means when you save the post, the image doesn't actually link anywhere even though the Target select box shows `media`.

The problem is that the `onSetLinkDestination` callback is not triggered for the currently selected link target when an image is chosen from the media library or uploaded, only when the select box's selected option is explicitly changed by the user.

**To Reproduce**
Enqueue the following JavaScript on the `enqueue_block_editor_assets` PHP hook:

```javascript
function modifyImageLinkDestinationDefault( settings, name ) {
    // Link target to override core default.
    var target = "media";

    if ( name == "core/image" ) {
        // Set image block default destination.
        settings.attributes.linkDestination.default = target;
    } else if ( name == "core/gallery" ) {
        // Set gallery block default destination.
        settings.attributes.linkTo.default = target;
    }

    return settings;
}

// Add settings filter to block registration.
wp.hooks.addFilter(
    "blocks.registerBlockType",
    "my-plugin/modify-image-link-destination-default",
    modifyImageLinkDestinationDefault
);
```

You can use this PHP code to enqueue the script:

```php
wp_enqueue_script(
	'modify-image-link-destination-default',
	'/path/to/plugin/js/index.js',
	array(
		'wp-hooks',
	)
);
```

**Expected behavior**
The image should link to its media file if the media target is set as default, even if the user does not explicitly set this using the select menu.

**Additional context**
Using whatever version of Gutenberg that came bundled with WordPress 5.0.2.

**Comment by youknowriad** [comment]
I guess that's because the code setting the link property is only run when we change the value of the dropdown and not when we select a new image.

**Comment by SeanDS** [comment]
Thanks, that's what I meant by "only when the select box's selected option is explicitly changed by the user."

So would the fix here be to trigger `onSetLinkDestination` after an image is selected? Seems easy enough to do - I could have a shot...

**Comment by SeanDS** [comment]
Update: I mistakenly said this also affects `core/gallery`, but it doesn't. Only `core/image`.

**Comment by SeanDS** [comment]
I made a pull request: #13797.

**Comment by SeanDS** [comment]
The motivation for this plugin has disappeared now that #25578 is merged.
