### ISSUE TITLE
Testing: Transition away from ESLint valid-jsdoc rule

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#13741]
Related: https://github.com/eslint/eslint/pull/11145
Related: https://eslint.org/blog/2018/11/jsdoc-end-of-life

Per the above links, ESLint is undergoing a deprecation of built-in support for JSDoc. As such, we should consider preemptively switching to another plugin, such as [`eslint-plugin-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc). As a side-effect, this could greatly expand the specific enforcement we'd like to see, in order to more closely align with [JavaScript Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/). 

I came across the discovery of the deprecation as a result of its buggy behavior ([example](https://user-images.githubusercontent.com/1779930/52428916-f85e3b00-2ad0-11e9-8d3d-627293f9f132.png)), which can be further motivation for expediting a transition.

**Comment by aduth** [comment]
Perhaps of interest to you @nosolosw , given your work at #13329.

**Comment by nosolosw** [comment]
Just noting that as doctrine will be no longer developed, we also need to update `docs/tool`, which is used to create [this handbook section](https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/).
