### ISSUE TITLE
Clicking "Enter" at the beginning of text bumps it down, but loses the block styling

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#13740]
**Problem**

After styling a block of text (ie. changing background color, text color, etc.), when I place my cursor at the beginning of the text and click "Enter", the text moves down to a new block, but all the styling of that block doesn't follow, but remains above.

Example:

![enter](https://user-images.githubusercontent.com/617986/52426155-4adc2f00-2ab2-11e9-986d-0a74cb4af826.gif)

**Solution**

I expected the entire block to move down allowing room for a new block above. So in the case of the example above, the whole green block would bump down.

**Comment by youknowriad** [comment]
Seems legit to me 👍

**Comment by Jackie6** [comment]
I think we can fix the issue by modifying the `splitBlock( before, after, ...blocks )` function. If the after has some content and the "ENTER" is pressed, the new block should keep the same styling as the current as. If the after has no content, a default block should be inserted after the current one. 
![yPyTTA3q7J](https://user-images.githubusercontent.com/24849874/54455755-f96b3380-4732-11e9-969e-3ddcf03ec806.gif)
I have created a pull request to fix this issue.

**Comment by ellatrix** [comment]
This will be fixed by #14765 now as well.
