### ISSUE TITLE
Component URLInput not honouring className prop

### ISSUE THREAD

**Issue by dribba** [WordPress/gutenberg#13754]
**Describe the bug**
According to [README.md](https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/url-input#example-1), we should be able to pass a `className` prop (I assume to the `<input`?) into `URLInput`, after an attempt to use it and not being able to find the class applied to any element, I had a look at `index.js` where I don't see the `className` prop used at all.

**To Reproduce**
1. Create a custom block type as in the example passing a custom `className`:
```javascript
<URLInput
    className="custom-url-input"
    value={ attributes.url }
    onChange={ ( url, post ) => setAttributes( { url, text: (post && post.title) || 'Click here' } ) }
/>
```

**Expected behavior**
The `className` passed to be applied to one of the rendered elements.

**Screenshots**

**Desktop**
 - OS: macOS
 - Browser: Firefox
 - Version: 64

**Additional context**
- Default shipped with WordPress 5.0.3

**Comment by youknowriad** [comment]
Marked as a minor enhancement but the inconsistency with the docs is a bug in the docs right now.
