### ISSUE TITLE
Inserter: Cursor is focused outside of search box in Firefox

### ISSUE THREAD

**Issue by vbaimas** [WordPress/gutenberg#13751]
**Describe the bug**
 When the user clicks to 'Search for a block', then the cursor is focused outside of the search box.

**To Reproduce**
1. Go to 'block'
2. Click on 'Add Block'
3. Click to 'Search for a block'
4. See the .gif below

**Expected behavior**
The cursor should appear inside the input field.

**Screenshots**

[<a href="https://cl.ly/f31388dd9775" target="_blank"><img src="https://duaw26jehqd4r.cloudfront.net/items/3I2t142W1w3V3N1V2c2n/Screen%20Recording%202019-02-07%20at%2010.26%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>](url)

**Desktop : **
 - Browser [firefox 65, chrome, safari]

**Bug :**
 - Browser [firefox 65]

**Comment by youknowriad** [comment]
I can't reproduce personally, I wonder if it's a browser issue?

**Comment by vbaimas** [comment]
@youknowriad I noticed that this is happening only firefox 65 version. I update the opened issue.

**Comment by youknowriad** [comment]
It doesn't happen for me in firefox developper edition (66 beta) but I confirm that it happens in firefox 65. It might be a browser issue they'll fix in soon.

**Comment by codebykat** [comment]
Noting it's only with the inserter at the top of the block; the one on the left is correct. See https://github.com/WordPress/gutenberg/issues/14157 for a few more screenshots.

**Comment by gziolo** [comment]
It works properly in Firefox 66:

![inserter](https://user-images.githubusercontent.com/699132/55862328-8b226100-5b78-11e9-9338-25b5abb2e65f.gif)

It seems like it was indeed the bug in the browser.
