### ISSUE TITLE
The block must have a registered category.

### ISSUE THREAD

**Issue by chiraggmodi** [WordPress/gutenberg#13760]
i have created a custom block, but it showing be error that `The block "mansi-caterers/heading" must have a registered category.`
here is my code for block registered

```
import { omit } from 'lodash';
import { __ } from '@wordpress/i18n';
import {
	registerBlockType
} from '@wordpress/blocks';
import { RichText } from '@wordpress/editor';
import {
	Path,
	SVG,
} from '@wordpress/components';

import edit from './edit';
export function getLevelFromHeadingNodeName( nodeName ) {
	return Number( nodeName.substr( 1 ) );
}

const schema = {
	content: {
		type: 'string',
		source: 'html',
		selector: 'h1,h2,h3,h4,h5,h6',
		default: '',
	},
	level: {
		type: 'number',
		default: 2,
	},
	align: {
		type: 'string',
	},
	placeholder: {
		type: 'string',
	},
};


console.log(wp.blocks.getCategories());

registerBlockType( 'mansi-caterers/heading', {
	title: __( 'Custom Heading' ),
	description: __( 'Introduce new sections and organize content to help visitors (and search engines) understand the structure of your content.' ),
	icon: <SVG xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><Path d="M5 4v3h5.5v12h3V7H19V4z" /><Path fill="none" d="M0 0h24v24H0V0z" /></SVG>,
	category: 'mansi-caterers',

	keywords: [ __( 'title' ), __( 'subtitle' ) ],

	// supports,

	attributes: schema,

	edit,

	save( { attributes } ) {
		const { align, level, content } = attributes;
		const tagName = 'h' + level;

		return (
			<RichText.Content
				tagName={ tagName }
				style={ { textAlign: align } }
				value={ content }
			/>
		);
	},

});
```

also here is error from console.

![screenshot_1](https://user-images.githubusercontent.com/10358945/52462265-543fc700-2b98-11e9-822e-49f0b4335fc7.png)

**Comment by youknowriad** [comment]
Seems weird, I know `console.log` could be defered sometime, try `console.log(JSON.stringify(wp.blocks.getCategories()));` instead?

**Comment by chiraggmodi** [comment]
have tried that as well, result is same.
![screenshot_3](https://user-images.githubusercontent.com/10358945/52470809-2d43be00-2bb5-11e9-84f8-38a8cfcd0700.png)

**Comment by chiraggmodi** [comment]
have tried that as well, result is same.
![screenshot_3](https://user-images.githubusercontent.com/10358945/52470809-2d43be00-2bb5-11e9-84f8-38a8cfcd0700.png)

**Comment by youknowriad** [comment]
Weird. can you replace `registerBlockType` by `wp.blocks.registerBlockType` instead?

**Comment by chiraggmodi** [comment]
ya this is working, or if I change all import statement to `const { registerBlockType } = wp.blocks;` this.
then it is working fine. any idea what causing this issue?

**Comment by youknowriad** [comment]
Yes, you're bundling a second version of the blocks package in your code. If you want to use the "import" syntax, you'd have to configure your build tool (webpack maybe) and define those modules as externals pointing to the global variable.

**Comment by chiraggmodi** [comment]
ok, so do you any example file for webpack bundle to this?

**Comment by youknowriad** [comment]
See https://github.com/WordPress/gutenberg/blob/master/webpack.config.js#L79

**Comment by ckmahoney** [comment]
> Yes, you're bundling a second version of the blocks package in your code. If you want to use the "import" syntax, you'd have to configure your build tool (webpack maybe) and define those modules as externals pointing to the global variable.

We have been seeing this same error message for a few weeks. For block registration we do not import `registerBlockType` but instead read the method from global `wp.blocks`. 

<img width="912" alt="Screen Shot 2020-02-12 at 1 08 12 PM" src="https://user-images.githubusercontent.com/26120849/74363625-eaed2800-4d98-11ea-91ed-3e0da1b738f4.png">

```
// BigImage.js
import { edit, save } from './BigImage.fn';
console.log('BigImage registration' );
console.log('typeof wp.blocks.registerBlockType', typeof wp.blocks.registerBlockType);
wp.blocks.registerBlockType( 'adw-events/big-image', {
  edit,
  save,
  title: 'Big Image',
  icon: 'image',
  category: 'adw-events',
  attributes: {
		image: {
  	  type: 'object', 
      default: {}
	  },
		title: { 
      type: 'text',
      default: 'Why Brandweek?'
    }
  },
} );
```

Between the JS and screenshot we can see that `wp.blocks.registerBlockType` is indeed a function at runtime when the blocks are trying to be registered. 

Calling `wp.blocks.registerBlockType( blockData  )` seems to trigger the error message "The block namespace/blockname must have a registered category".

We are also registering the blocks server side with PHP.

```
// adw-events.php
$blocks = [
    'adw-events/event-highlights',
    'adw-events/event-data',
    'adw-events/logogrid',
    'adw-events/hero',
    'adw-events/carousel',
    'adw-events/passes',
    'adw-events/speakers-grid',
    'adw-events/schedule',
    'adw-events/includes-and-partners-grid',
    'adw-events/tri-hero',
    'adw-events/big-image',
    'adw-events/capture-email',
    'adw-events/capture-form'
];

$instance = new ADW_Events_Blocks( $blocks );
class ADW_Events_Blocks
{
    protected $blocks;

    function __construct( $blocks = [] )
    {
        $this->blocks = $blocks;
        $this->enqueue_global_hooks();

        add_action( 'init', array( $this, 'register_blocks' ) );
        
        if ( is_admin() ) {
            add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_block_editor_assets') );
        } 
        else {
            add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_frontend' ) );
        }
    }

    // truncated code; skipping methods

    /**
     * Registers block scripts and styles. 
     *
     */
    public function register_blocks() {
        foreach( $this->blocks as $block ) {
            $registered = register_block_type( $block, array(
                'category'  => 'adw-events',
                'editor_script' => 'adw-events-backend',
                'editor_style' => 'adw-blocks-editor-styles',
                'style' => 'adw-blocks-front-end-styles',
            ) );

            if ( ! $registered ) {
                error_log( ' Could not register block name ' . $block );
            }
        }
    }
}
```

Is there something that must be done differently, such as registering only on server OR client? Perhaps there is something that must be lined up between the two types of registration?

**Comment by ckmahoney** [comment]
Here is the corresponding package.json: 
```
{
  "name": "masked",
  "version": "1.0.0",
  "description": "masked",
  "main": "webpack.config.js",
  "scripts": {
    "start": "wp-scripts start",
    "build": "wp-scripts build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "masked",
  "license": "ISC",
  "devDependencies": {
    "@wordpress/scripts": "^6.2.0"
  },
  "dependencies": {
    "@wordpress/block-editor": "^3.4.0",
    "@wordpress/components": "^8.5.0",
    "@wordpress/data": "^4.12.0",
    "@wordpress/editor": "^9.9.0",
    "@wordpress/element": "^2.10.0",
    "array-flat-polyfill": "^1.0.1",
    "moment": "^2.24.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  }
}
```

**Comment by ckmahoney** [comment]
Hi @youknowriad, I noticed you have closed this issue but wanted to check in since the problem persists. As far as we can tell we are following the rules for block registration, yet we see the errors as described.

**Comment by youknowriad** [comment]
Ddid you register this cactegory `adw-events`?

**Comment by ckmahoney** [comment]
Yes @youknowriad we register the category `adw-events`. 

There is no PHP function such as `register_block_category` and instead the docs instruct us to hook into the `block_catgories` filter. 

We do that using this method called on the `init` hook.

```
    /**
     * Add custom block category
     *
     */
    public function block_categories( $categories, $post ) {
        
        // We are getting many instances of this category in the inserter.
        // Patch for now to prevent duplicate block category insertion.
        foreach( $categories as $i => $cat ) {
            if ( $cat['slug'] === 'adw-events' )
                return $categories;
        }

        return array_merge(
            $categories,
            array(
                array(
                    'slug' => 'adw-events',
                    'title' => __( 'Events', 'adw-blocks' ),
                    'icon'  => 'buddicons-activity',
                )
            )
        );
    }
```

Quoted from above:
> ```
> class ADW_Events_Blocks
> {
>     protected $blocks;
> 
>     function __construct( $blocks = [] )
>     {
>         $this->blocks = $blocks;
>         $this->enqueue_global_hooks();
> 
>         add_action( 'init', array( $this, 'register_blocks' ) );
>         
>         if ( is_admin() ) {
>             add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_block_editor_assets') );
>         } 
>         else {
>             add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_frontend' ) );
>         }
>     }
> }
> ```

**Comment by youknowriad** [comment]
You can check on the console that the category is registered properly `wp.blocks.getCategories()` before registering the block. Maybe it's not done properly.

**Comment by 1manfactory** [comment]
I got the same error.

The solution for me was pretty easy.

Just delete

```
    if ( $post->post_type !== 'post' ) {
        return $categories;
    }
```

from the example in [](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#managing-block-categories)

I was using my block on a PAGE, hence the editor never found the category as it was supposed to only been added with POSTS - whatever the reason may have been for that.
