### ISSUE TITLE
How can I write a block using InnerBlocks alongside a RichText component

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#13770]
I have a requirement where I need to place `InnerBlocks` alongside a `RichText` component. Like this:

```
edit: function( props ) {
    var textContent = props.attributes.textContent;
    function onChangeTextContent( content ) {
	props.setAttributes( { textContent: content } );
    }

   return (
	<div className={ props.className }>
                <label class="editor-content-section-label">Content for gray section</label>
		<RichText
                    className={props.className}
                    onChange={onChangeTextContent}
                    value={textContent}
                    placeholder="Add content"
                />
                <InnerBlocks allowedBlocks={'hallmark/white-content-container'}/>
	</div>
   );
},
save: function( props ) {
   return null;
},
```
I am new in Gutenberg development. I have three questions.

1. Is this the right way to do it? The requirement is `white-content` needs to go inside the container of `RichText`.
2. How can I save the entire content using `render_callback`. The callback function saves the content of `RichText` fine but I don't know how to save the content of `InnerBlock`.

The final output should look like this:

```
<div class="gray-content">
   Content of RichText 
   <div class="white-content">
       Content of InnerBlock
   </div>
</div>
```
1. Although I have restricted `InnerBlocks` to sow only one block (`<InnerBlocks allowedBlocks={'hallmark/white-content-container'}/>`), the inserter dialog is showing all available blocks, both core and custom ones.

Please let me know how I can do it!

**Comment by FerrielMelarpis** [comment]
I'd be interested also on how to do this.

> Although I have restricted InnerBlocks to sow only one block (<InnerBlocks allowedBlocks={'hallmark/white-content-container'}/>), the inserter dialog is showing all available blocks, both core and custom ones.

I think what's wrong here is that you are passing a string rather than an array of string in `allowedBlocks` prop.
```js
<InnerBlocks allowedBlocks={ [ 'hallmark/white-content-container' ] } />
```
should fix your issue regarding the inserter dialog.

**Comment by youknowriad** [comment]
Hi there! thanks for the issue. This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

That said, yes, this seems like the way to do it and your `save` function should probably return something like:

```
<div class="gray-content">
  <RichText.Content value={props.attributes.textContent} />
   <div class="white-content">
       <InnerBlocks.Content />
   </div>
</div>
```
