### ISSUE TITLE
Format is already registered to handle class name error log

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#13776]
**Describe the bug**
Custom formats are logging this error : https://github.com/WordPress/gutenberg/blob/01be7ac89b97b76c490d57a15c16466657240770/packages/rich-text/src/register-format-type.js#L95 even when classNames were defined.

**To Reproduce**
1. Install https://wordpress.org/plugins/coblocks/
2. Load editor with 5.0
3. Uppercase and code formats are working perfectly but those errors were logging

**Expected behavior**
No error logs

**Screenshots**
<img width="1274" alt="screen shot 2019-02-08 at 12 57 06 pm" src="https://user-images.githubusercontent.com/3365507/52482539-7e22d900-2bec-11e9-8541-009a2562c260.png">

**Comment by aduth** [comment]
Related Slack conversation ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C02QB2JS7/p1549632859321200

The curious thing to me is that it gets this far under a condition of `className === null`, despite a class name being defined in the settings of the source format type:

https://github.com/thatplugincompany/coblocks/blob/ded312447bb9b0ab89f45f532d8c1580c87b5579/src/formats/code/index.js#L23

**Comment by phpbits** [comment]
@aduth Yeah, same here.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/blob/2d5dec7418435bbc182b4e128a7f5da50610148e/packages/rich-text/src/store/selectors.js#L42-L46

This might be an issue in the implementation, I see the following happening:
1. Format type with a class name A and tag name B gets registered.
1. Another format type without any class name but the same tag name B gets registered.

/cc @iseulde

**Comment by phpbits** [comment]
@gziolo Most of us will probably use `span` since it's easier to control inside divs and paragraphs. `getFormatTypeForBareElement` should check classNames too.

**Comment by phpbits** [comment]
@aduth @gziolo I hope it's fine to follow this up :) Thanks!

**Comment by pascalknecht** [comment]
I have the same issue while registering a custom format for links. Still does not work with the current version of gutenberg. Also the link toolbar button gets lost when registering this custom format. @aduth @gziolo
Example code:

```
const { registerFormatType } = window.wp.richText;
const { RichTextToolbarButton } = window.wp.editor;

registerFormatType( 'wk/no-icon', {
	edit( { isActive } ) {

		return (
			<RichTextToolbarButton
				icon={ 'editor-link' }
				title={ 'Link ohne Icon' }
				isActive={ isActive }
				/>
		);
	},
  	tagName: 'a',
  	className: 'without-icon',
  	title: 'Link ohne Icon'
} );
```

**Comment by gziolo** [comment]
I opened #15072 which tries to address this issue.
