### ISSUE TITLE
Latest Comments block - Additional CSS class field does not working

### ISSUE THREAD

**Issue by thejaydip** [WordPress/gutenberg#13773]
**Describe the bug**
When i add **Latest Comments** block in editor and add additional CSS class from the Advance, it's does not showing. Please see below attachment for more information.

**To Reproduce**

1. Add Latest Comments block
2. Add Additional CSS class from the Advance
4. See Additional class does not showing

![additional-css-class](https://user-images.githubusercontent.com/46511743/52479519-e662c200-2bce-11e9-8167-2790350464a0.gif)

**Desktop (please complete the following information):**
OS: Linux
Browser Chrome
Version 70.0.3538.77
Additional context

**Gutenberg: latest from master**
WordPress: 5.0.3

**Comment by gziolo** [comment]
@Soean, is it similar issue to what you are trying to solve with #13561?
