### ISSUE TITLE
Update core/image block to use align supports

### ISSUE THREAD

**Issue by ryanboswell** [WordPress/gutenberg#13780]
**Is your feature request related to a problem? Please describe.**
Several core blocks now use the `align` supports approach to block alignments (`center`, `wide`, `full`, etc..), allowing consistent controls and filtering of what alignments are allowed (or if they're allowed at all). But in adjusting these on a site I found that the `core/image` block still includes the `BlockAlignmentToolbar` itself, with a hard-coded array of alignments that make it impossible to filter externally. Trying to set the `align` supports value results in two `BlockAlignmentToolbar`s being added to the block (the smaller group is the custom set I provided, removing `left` and `right` options):

![duplicate-alignments](https://user-images.githubusercontent.com/1580218/52490431-973e7200-2b79-11e9-8e6e-4f8f139d4af1.png)

**Describe the solution you'd like**
Ideally the `core/image` block uses the alignment hooks approach implemented across other blocks like `core/cover`, `core/table`, etc.. so developers (plugin/theme/etc..) can modify them as needed, in a manner consistent with other blocks.

**Describe alternatives you've considered**
There really aren't many alternatives, since the hooks approach has already been implemented across many other blocks as a standard approach, and currently there isn't another way to change Image alignment options without monkey-patching Gutenberg or a rather complex series of BlockEdit filters (in theory, not sure that would even work).

**Comment by mcguffin** [comment]
As a supplement: `core/cover` behaves just like image blocks, when trying to modify the align support. 
Related: https://wordpress.stackexchange.com/questions/317113/how-to-disable-align-wide-for-specified-blocks-in-gutenberg/326667#326667

**Comment by jwktje** [comment]
Any update on this? Having the same issue.

**Comment by christophhapple** [comment]
Same here ... still no update?

**Comment by jwktje** [comment]
@christophhapple I have had no luck since I last tried either.

**Comment by youknowriad** [comment]
Right now this is not possible with the way alignments work in the image block but we're considering making the alignments more consistent and easier to support with #20650
