### ISSUE TITLE
iFrame title attribute missing

### ISSUE THREAD

**Issue by brianpeat** [WordPress/gutenberg#13787]
**Is your feature request related to a problem? Please describe.**
When scanning for accessibility compliance, a youtube iframe is flagged as having no title. If you use the Gutenberg Video block to embed videos, there's no way to ADD that attribute to the iFrame code as that level of code isn't visible in the html of the block.

**Describe the solution you'd like**
Add a field when the video block is active that lets you add a title, and have the title be applied to the iFrame. This would help with accessibility.

**Describe alternatives you've considered**
I could just use an html block, but then my clients will have to mess with embed code themselves, defeating the purpose of using Gutenberg.

-note, I'm new to the WP community, so if this is the wrong place to post this, let me know or remove lt.

**Comment by youknowriad** [comment]
Thanks for the issue,

worth noting that the HTML is the result of the oembed provider (youtube API) which means we can't do anything about it in Gutenberg I think.

**Comment by brianpeat** [comment]
Ah okay. I'm searching for a function that'll just inject the video name. Thanks for the info!

**Comment by brianpeat** [comment]
Found another thread for reference.

[https://core.trac.wordpress.org/ticket/40245](url)
