### ISSUE TITLE
Navigation block: Rearranging items

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#13792]
_This is intended to splinter conversation from #13690 and allow us to focus the conversation on one part of the problem at a time. We'll loop back to the tracking issue when we've determined a path forward. For this issue, we're focussing on ordering, hierarchy, and sub-menus:_

## How do I rearrange the items in my menu?

_This will probably hinge quite a bit on the direction chosen in #13789 and also on #13791. It's going to be a doozy so we're saving it for last!_

**Comment by nosolosw** [comment]
One of the tasks for phase 2 is adding Drag and Drop reordering to the Gallery block. There may be a common mechanism to do both (this and the gallery), as the mechanics seem similar. Cross-posting here for reference and visibility https://github.com/WordPress/gutenberg/issues/743

**Comment by jwold** [comment]
Agreed @sarahmonster that this probably makes sense to tackle after the other issues.

**Comment by sarahmonster** [comment]
Since design explorations have largely concluded here, I'm closing this ticket as non-actionable, and we can loop back to #13690 or new issues for any further conversation that comes up as development work progresses.

Thanks everyone for all the feedback! 🙌
