### ISSUE TITLE
Rich Text Excerpts

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#13798]
**Is your feature request related to a problem? Please describe.**
It would be nice if the Gutenberg Editor or at least a Rich text editor can be used for the post excerpt.

**Describe the solution you'd like**
Show Gutenberg editor/rich text editor for excerpt field.

**Describe alternatives you've considered**
As alternative, the [Rich Text Excerpts](https://wordpress.org/plugins/rich-text-excerpts/) plugin can be used, but it will add an additional field and 
the existing Gutenberg only-text excerpt field seems to be differently and stronger integrated.

**Comment by kjellr** [comment]
Hi @strarsis. Thank you for the issue! I can certainly see the use case for allowing rich text in excerpts, but it seems like somewhat of a power-user feature. As such, it seems like it'd be better handled in a plugin. I see you filed a related issue for the Rich Text Excerpts plugin — that's a good start. 

I'm going to close this for now, but if others feel that this would be useful, we can always reopen. Thanks again!

**Comment by Merlin-1D** [comment]
Unfortunately, there is no easy way to get a rich-text editor for excerpts. Also, the Rich Text Excerpts plugin did not work with Gutenberg, only with the Classic Editor, and now it is not available for download at all.

Perhaps there will be time to consider this possibility again in the context of using a block editor?
