### ISSUE TITLE
I Can't assign a post to a differnt Author

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1379]
On sites where production is a subset of editorial, it's very rare for the content author to be the one entering it into the CMS. Currently, there is no way to change the author.

**Comment by mtias** [comment]
See #968.

**Comment by youknowriad** [comment]
duplicate?

**Comment by aaronjorbin** [comment]
Sounds like a dupe.  Closing this since #968 has some more traffic.
