### ISSUE TITLE
Add support for RTL scripts

### ISSUE THREAD

**Issue by aahani** [WordPress/gutenberg#138]
I propose adding LTR, RTL (Left to right, Right to left) <a href="https://www.w3schools.com/cssref/pr_text_direction.asp">direction functionality</a> to blocks. It is useful for <a href="https://en.wikipedia.org/wiki/Right-to-left">RTL scripts</a> (Persian, Pashto, Arabic, Hebrew).
It is supported by TinyMCE: https://www.tinymce.com/docs/plugins/directionality/ as whown here:

![tinymce rtl button](https://cloud.githubusercontent.com/assets/15798894/23355653/fcd941da-fceb-11e6-98da-4a71fc4b28dd.png)

It can be a toggling button (Default LTR, toggle to RTL) before trash.

**Comment by jasmussen** [comment]
Interesting! 

RTL is absolutely important. Is there a a use-case for mixing LTR and RTL in a single post or page, though? Would it be enough that the wp-admin was set to an RTL language and so the block editor became RTL entirely as well?

**Comment by aahani** [comment]
There are many use cases of LTR in a RTL script (say Persian). For instance:

<strong>Case 1: A company active in oil &amp; gas industry is listing its products and services as well as its foreign partners. They usually list these items in English (LTR). For instance</strong>:

<p dir="rtl">شرکت نفت کاو در سال ۱۳۸۴ با هدف ارائه خدمات و کالاهای مورد نیاز صنایع نفت، گاز و پتروشیمی و بویژه پروژه‌های خطوط لوله و تاسیسات آغاز بکار نمود. این شرکت از‌‌ همان ابتدا بعنوان نماینده رسمی و انحصاری کارخانجات نورد و پروفیل ساوه عرضه کننده انواع لوله‌ها با استانداردهای ASTM و API فعالیت خود را آغاز نمود و با به دست آوردن رزومه‌ای قابل توجه در زمینه فروش انواع لوله‌ها به شرکت‌های نفت، گاز و پتروشیمی و آب و همچنین شرکت‌های پیمانکاری فعال در این صنایع بعنوان یکی از شرکت‌های پیشرو در ارائه خدمات و کالا‌ها به صنایع نفت و گاز اعم از مصارف جهت سرویس‌های ترش و شیرین و صنایع پایین دستی و بالا دستی معرفی می‌گردد. (Company Introduction)</p>

<p dir="rtl">کالاهای قابل تامین: (Products)</p>

<p dir="rtl">شیرآلات:  (Valves)</p>
<ul>
 	<li>Globe Valve</li>
 	<li>Gate Valve</li>
 	<li>Special Valve</li>
 	<li>Check Valve</li>
</ul>
<p dir="rtl">شرکای خارجی: (partners)</p>
<ul>
 	<li>Company A</li>
 	<li>Company B</li>
 	<li>Company C</li>
</ul>
<p dir="rtl">پمپها:  (Valves)</p>
<ul>
 	<li>Water Pumps</li>
 	<li>Diesel Pumps</li>
 	<li>Drum Pumps</li>
 	<li>Hand Pumps</li>
 	<li>Diaphragm Pumps</li>
 	<li>Centrifugal pumps</li>
</ul>
<p dir="rtl">شرکای خارجی: (partners)</p>
<ul>
 	<li>Company A</li>
 	<li>Company X</li>
 	<li>Company Y</li>
</ul>
&nbsp;

<strong>Case 2: Consider a university website that includes a section for academic papers. At the end of academic articles, they list their references in two sections: Persian &amp; Latin (LTR). For example:</strong>

<div dir="rtl">منابع فارسی: (Persian References)
<ol>
 	<li>الوانی، سیدمهدی؛ آذر، عادل؛ دانایی فرد، حسن. (1390). روش شناسی پژوهش کیفی در مدیریت: رویکردی جامع. اشراقی.</li>
 	<li>بازرگان، عباس. (1387). روش ﺗﺤﻘﻴﻖ آﻣﻴﺨته : روﻳﻜﺮدي ﺑﺮﺗﺮ ﺑﺮای ﻣﻄﺎﻟﻌﺎت ﻣﺪﻳﺮیت. دانش مدیریت، سال 21، شماره 81، تابستان 1387، صص 36-19.</li>
 	<li>حافظ نیا، محمدرضا . (1395). مقدمه ای بر روش تحقیق در علوم انسانی. سازمان مطالعه و تدوین کتب علوم انسانی دانشگاهها (سمت).</li>
</ol>
منابع لاتین: (Latin References)</div>
<ol>
 	<li>Aczél, J., &amp; Saaty, T. L. (1983). Procedures for synthesizing ratio judgements. Journal of mathematical Psychology, 27(1), 93-102.</li>
 	<li>Ahmadi, A., &amp; Golbabaie, E. (2015). A hybrid approach to supplier performance evaluation using artificial neural network: a case study in automobile industry. Journal of Industrial and Systems Engineering, 8(1), 1-20.</li>
 	<li>Arabzad, S. M., &amp; Ghorbani, M. (2011). Using Integrated FMEA-DEA Approach to Classify Purchasing Items based on Kraljic's Model. International Journal of Business and Social Science, 2(21).</li>
 	<li>...</li>
 	<li>Yeo, K. T.,  & Ning, J. H. (2002). Integrating Supply Chain and Critical Chain Concepts in Engineer-Procure-Construct (EPC) Projects. International Journal of Project Management 20, 253-262.</li>
 	<li>Yorke D. A. , Droussiotis G.(1994). The Use of Customer Portfolio Theory.  Journal of Business & Industrial Marketing, Vol. 9, No. 3, pp. 6-18.</li>
 	<li>Zolkiewski, J., & Turnbull, P. (2002). Relationship portfolios-past, present and future. Understanding Business Marketing and Purchasing, London, Thomson Learning, 289-304.</li>
</ol>
<strong>Case 3: In a knowledge management section of a company's intranet, they may use many English texts in a Persian script, e.g.:</strong>

<p dir="rtl">مدارک تهیه شده توسط واحد مهندسی فرآیند عبارتند از:</p>
<ul>
 	<li>Process flow diagram</li>
 	<li>Process equipment list</li>
 	<li>Process fluids list</li>
 	<li>Heat and material balance</li>
 	<li>Process data sheet</li>
 	<li>Process description and operating philosophy</li>
 	<li>Piping and instrumentation diagram (P&amp;ID)</li>
 	<li>Process line list</li>
 	<li>Process causes and effects diagram</li>
 	<li>Emergency shutdown (ESD) cause and effect diagram</li>
 	<li>Emergency shutdown (ESD) simplified diagram</li>
 	<li>Emergency shutdown (ESD) logic diagram</li>
 	<li>Emergency shutdown and depressurization philosophy</li>
 	<li>Flare Report</li>
 	<li>Calculation note</li>
 	<li>Operating manual</li>
</ul>
<strong>Case 4: In a site dedicated to teaching Persian to English, a teacher writes lessons and needs to provide translations</strong><strong> of conversations, e.g.:</strong>

<div dir="rtl">
<p>مکالمه:</p>
<p>ل- سلام، نام من لیلا است.</p>
<p>س- سلام، من سارا هستم.</p>
<p>ل- من در تهران زندگی می کنم، تو کجا زندگی می کنی؟</p>
<p>س- من در پاریس زندگی می کنم. من دانشجوی زبان و ادبیات فارسی هستم، شغل تو چیست؟</p>
<p>ل- چه جالب، من معلم زبان فارسی هستم</p>
<p>...</p>
</div>

Translation (English)
L: Hi, my name is Leila.
S: Hello, my name is Sarah.
L: I live in Tehran, where do you live?
S: I live in Paris. I study Persian language and literature, what's your job?
L: Very interesting, I am a Persian language teacher.
…
<hr/>
<strong><u>P.S.:</u></strong>

As a simple trick, some may try to use tables and left and right alignments (provided by current WordPress default editor / TinyMCE editor) in those tables, but it will not work. e.g.:
<table>
<tbody>
<tr>
<td><strong>Translation (English)</strong></td>
<td style="text-align: right;"><strong>فارسی</strong></td>
</tr>
<tr>
<td>L: Hi, my name is Leila.</td>
<td style="text-align: right;">ل- سلام، نام من لیلا است.</td>
</tr>
<tr>
<td>S: Hello, my name is Sarah.</td>
<td style="text-align: right;">س- سلام، من سارا هستم.</td>
</tr>
<tr>
<td>L: I live in Tehran, where do you live?</td>
<td style="text-align: right;">ل- من در تهران زندگی می کنم، تو کجا زندگی می کنی؟</td>
</tr>
<tr>
<td>S: I live in Paris. I study Persian language and literature, what's your job?</td>
<td style="text-align: right;">س- من در پاریس زندگی می کنم. من دانشجوی زبان و ادبیات فارسی هستم، شغل تو چیست؟</td>
</tr>
<tr>
<td>L: Very interesting, I am a Persian language teacher.</td>
<td style="text-align: right;">ل- چه جالب، من معلم زبان فارسی هستم</td>
</tr>
<tr>
<td>…</td>
<td style="text-align: right;">...</td>
</tr>
</tbody>
</table>
So, he shall go Text section of editor and use dir="rtl" in td of each Persian column! <strong>(a hard task if the table has a lot of rows)</strong>. The above table using inline markup:
<table>
<tbody>
<tr>
<td><strong>Translation (English)</strong></td>
<td dir="rtl"><strong>فارسی</strong></td>
</tr>
<tr>
<td>L: Hi, my name is Leila.</td>
<td dir="rtl"><span dir="rtl">ل- سلام، نام من لیلا است.</span></td>
</tr>
<tr>
<td>S: Hello, my name is Sarah.</td>
<td dir="rtl"><span dir="rtl">س- سلام، من سارا هستم.</span></td>
</tr>
<tr>
<td>L: I live in Tehran, where do you live?</td>
<td dir="rtl"><span dir="rtl">ل- من در تهران زندگی می کنم، تو کجا زندگی می کنی؟</span></td>
</tr>
<tr>
<td>S: I live in Paris. I study Persian language and literature, what's your job?</td>
<td dir="rtl"><span dir="rtl">س- من در پاریس زندگی می کنم. من دانشجوی زبان و ادبیات فارسی هستم، شغل تو چیست؟</span></td>
</tr>
<tr>
<td>L: Very interesting, I am a Persian language teacher.</td>
<td dir="rtl">ل- چه جالب، من معلم زبان فارسی هستم</td>
</tr>
<tr>
<td>…</td>
<td dir="rtl">...</td>
</tr>
</tbody>
</table>

**Comment by jasmussen** [comment]
Wow that is really interesting. Thanks so much for explaining this!

**Comment by jasmussen** [comment]
The block concept perhaps lends itself to approaching this challenge in a new light.

For example, do we have RTL and LTR blocks where whatever you put inside them is flipped? Or are LTR and RTL advanced properties that can be toggled for each block? See also #16

**Comment by aahani** [comment]
Hi again
A block as a whole or **some parts** of it can be RTL or LTR (e.g. some columns, e.g. translation columns in the above mentioned example). so I think it is better to consider it in the block edit section (inline markup)

![gutenberg issue 138 - edit block - topbar](https://cloud.githubusercontent.com/assets/15798894/23452261/e4d8de36-fe78-11e6-8a7c-820ff7d8bdc6.jpg)

**Comment by jasmussen** [comment]
Let's make sure we remember to add an LTR button when a user has an RTL language. This is what's been done in the past, let's consider that a baseline task. We should add this button as an inline button, as suggested here.

**Comment by intronic** [comment]
How about a language switcher as well? 
Language blocks could have their own spelling, translation options, and maybe other things as well as direction.

**Comment by gziolo** [comment]
@yurynix and @ranh given your experience with RTL on WordPress.com, do you have a suggestion what would be the best way to tackle it? I remember that you even worked on auto language direction in Reader (https://github.com/Automattic/wp-calypso/pull/9664).

**Comment by yurynix** [comment]
Until we have a way to apply styles to an inner element in a block ( nested block? ),
I'm not really sure how we can achieve this functionality.

So there are 2 issues here:
1. Alignment ( css `text-align: left|right;` )
2. Directionality ( css `direction: ltr|rtl;` )

Both of them needs to be applied to a parent html element, in a block context such as a table,
it'll be hard to figure that out unless the cell is itself a block?

As an intermediary solution, we might want to make it easy for people to insert these special unicode characters:
```
LRM | U+200E | LEFT-TO-RIGHT MARK | Left-to-right zero-width character
RLM | U+200F | RIGHT-TO-LEFT MARK | Right-to-left zero-width non-Arabic character
```
For more info see [here](http://unicode.org/reports/tr9/).

Here's an example:
![rlm](https://user-images.githubusercontent.com/326402/32040740-741cf604-ba3a-11e7-8e69-1fcbab0b3eb4.gif)
* Notice the exclamation mark, it's initially on the right and should be on the left in RTL
* I insert the RLM character and the exclamation mark moves to where it should be - on the left.  

This solves the directionality issue, but not the alignment issue.

Adding @yoavf as he might have more insights on that.

**Comment by aduth** [comment]
What are the actionable steps to be done here?

>Let's make sure we remember to add an LTR button when a user has an RTL language.

To clarify, is this to be included in RichText's formatting toolbar?

![Formatting Toolbar](https://user-images.githubusercontent.com/1779930/36555982-a01d97c8-17d1-11e8-8475-62ef937f512f.png)

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519322701000426)._

**Comment by youknowriad** [comment]
I tried addding these buttons in the formatting toolbar. The problem here is that they work only on multiine RichTexts (quote) and not in single line ones (paragraph), I guess that's because this direction applies to the paragraph level only. So instead of adding it as a formatting toolbar, I wonder if this should be a block level control instead.

What do you think?

**Comment by azaozz** [comment]
The classic editor gets only one button, LTR. It works by changing the text direction (on/off), no need for two buttons there.

> I guess that's because this direction applies to the paragraph level only.

Right, the `dir` attribute generally applies only to "block" elements. I think it makes sense to add that button as block level control (in the block properties) for single-line blocks, but what about multi-line blocks? Seems we will have to add one in the block properties, and another on the formatting toolbar. Logically this makes sense: one will apply to the whole block, the other to one of the block elements in multi-line blocks. May be a bit confusing though.

The alternative is to always have the LTR button in the formatting toolbar and apply it either to the whole block or one of the block elements according to the selection (this is how it works in the classic editor).

**Comment by youknowriad** [comment]
We discussed this a bit in WCEU and I think we should be pragmatic. The main way to create content in Gutenberg is using single line blocks (paragraph, headings...), let's try to get the block level support first and we can iterate to see if we add the multi-line support as well.

**Comment by yoavf** [comment]
A bit late, but chiming in an attempt to add a little bit of clarity to what we need to do, at least in order prevent a usability regression for users with RTL UI. 

@jasmussen said it right

> Let's make sure we remember to add an LTR button when a user has an RTL language. This is what's been done in the past, let's consider that a baseline task. We should add this button as an inline button, as suggested here.

In the classic editor, *when in RTL UI*, you get an extra button to your toolbar, in both visual and HTML modes:

**Visual Editor** - the button works on a paragraph level
<img width="860" alt="screen shot 2018-10-04 at 17 59 06" src="https://user-images.githubusercontent.com/844866/46505538-5ddaac00-c7ff-11e8-9ae0-a80c283c8401.png">

**HTML Editor**- the button applies to the entire editor
<img width="869" alt="screen shot 2018-10-04 at 17 59 36" src="https://user-images.githubusercontent.com/844866/46505680-d80b3080-c7ff-11e8-97e8-3bedb2673df1.png" />

For Gutenberg, I'd say that the minimum required **would be a similar button on the paragraph block formatting toolbar** when UI is RTL.
Then:
- Add that button (or a setting where there's no formatting bar) to other blocks.
- Document setting for directionality that would apply to the entire post.

For reference, Google Sheets has the following buttons on the main toolbar (possibly only for relevant users):

<img width="106" alt="screen shot 2018-10-04 at 18 23 36" src="https://user-images.githubusercontent.com/844866/46506571-c24b3a80-c802-11e8-8359-2efea0fee266.png">
Sheet direction button, cell direction buttons

**Comment by yoavf** [comment]
> @yoavf can you verify if the above approach is sufficient/right for now?

Yes, LGTM!

**Comment by aduth** [comment]
Pull request at #10663

**Comment by urShadoww** [comment]
Just wanted to check on when RTL support is expected for the end users. I am having a hard time writing posts containing English and Arabic.

**Comment by sardbaba** [comment]
As a temporary solution I've added a "rtl-content" class at block level and

`
.rtl-content {
	text-align: right;
	direction: rtl;
}
`
on both style.css and style-editor.css

**Comment by a-atalla** [comment]
@aahani  i think i came up with a solution via custom block  [smart-paragraph](https://github.com/a-atalla/smart-paragraph)

**Comment by oussjarrousse** [comment]
I cannot find the right-to-left button in the new Gutenberg blocks. 
@aduth Please consider reopening this issue or creating a new issue.

**Comment by youknowriad** [comment]
@oussjarrousse Would you mind creating an issue yourself and describe what you're seeing (screenshots, language...) and on which blocks? Thanks.

**Comment by dirad** [comment]
@youknowriad  @oussjarrousse 
Was another issue opend?

[this comment ](https://github.com/WordPress/gutenberg/pull/10663#issuecomment-534901153) on [10663](https://github.com/WordPress/gutenberg/pull/10663) talks about the problem.

I am using a en_US system, but need to be able to write Arabic and Hebrew, so RTL, but cannot find any button to do this.. or any reference online to the right way to get it.

**Comment by youknowriad** [comment]
@dirad I believe this issue matched the behavior in the classic editor: show the button when using an RTL locale but I can see the value for non-RTL languages too. Please do create an issue for it to discuss how it can be more globally made visible.

**Comment by danielwebguy** [comment]
@yoavf  I am looking for a solution for this issue and I see that even after 2-3 years I can't find a proper solution.
Can you please update us if there is a solution for this?
Thank you.
Daniel

**Comment by urShadoww** [comment]
Have been waiting for the solution since Gutenberg launched.

**Comment by shula** [comment]
> @AZAOZZ 
> The classic editor gets only one button, LTR. It works by changing the text direction (on/off), no need for two buttons there.

Oh, but it is needed:
The way you see it, RTL is the exception, such as **bold** text.  
But in many situations RTL is the norm, or LTR / RTL are has equal importance.
Also, a wordpress editor interface direction can be different than the OS settings.

A single button is therefore ambiguous.
I know it for myself and for my non-tech authors.

When 2 buttons are shown, the user gets clear unambiguous indication of the current direction,
**AND** the user will be able to set the direction without guessing.
2 buttons UI is also the de-facto standard in text editors (msoffice, libreoffice, and others).

A separate UI for wordpress alianates end users.
