### ISSUE TITLE
Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed  Embed 

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1380]
35. That's how many options are under the "EMBED" option in the new block selection right now. Is this too many?

**Comment by jasmussen** [comment]
I'm assuming you're referrong the the individually labelled embed aliases that show up in the inserter, and not multiple copies of the generic embed block. We are discussing in #1325 how to best handle many blocks, and will add a separate tab for those. One of the key arguments for surfacing every oembed as an explicit block is [presented here](https://github.com/WordPress/gutenberg/issues/1325#issuecomment-310293783).

**Comment by swissspidy** [comment]
I‘m sure having separate blocks for each embed provider isn‘t the only possible solution.

**Comment by jasmussen** [comment]
I'm going to close this ticket to direct conversation to #1325. I also think it's too early to optimize for not having embed aliases, since we haven't even given this a fair shake yet, and it's such a foundational pillar to the whole project.
