### ISSUE TITLE
Lift up state of a modal

### ISSUE THREAD

**Issue by daext** [WordPress/gutenberg#13803]
I've implemented a modal window like explained in [this tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/modal/). The problem is that I can't find a way to lift up the state to the parent component without using a custom store implemented with the [data module](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-data/). The store is then used in other parts of the program to keep the "url1" value in sync.

My solution works but I don't think it's ideal:

```
import {Button, Modal} from '@wordpress/components';
import {withState} from '@wordpress/compose';

const MyModal = withState({
  isOpen: false,
  url1: this.state.url1,
})(({isOpen, url1, setState}) => (
    <div>
      <Button isDefault onClick={ () => setState({isOpen: true}) }>Open Modal</Button>
      { isOpen && (
          <Modal
              title="This is my modal"
              onRequestClose={ () => setState({isOpen: false}) }>
            <Button isDefault onClick={ () => setState({isOpen: false}) }>
              My custom close button
            </Button>
            <TextControl
                label={__('URL 1', 'dahm')}
                value={url1}
                onChange={(value) => {
                  setState({
                    url1: value,
                  });

                  //IMPORTANT: This is used to save the state outside this function component
                  dispatch('custom_store/main').update({url1: value});

                }}
            />
          </Modal>
      ) }
    </div>
));
```

Is there a better alternative to this?

**Comment by daext** [comment]
I also want to add that if a function used to change the state of the parent component is passed in [withState](https://github.com/WordPress/gutenberg/tree/master/packages/compose/src/with-state) as a prop, the state of the parent is actually properly modified but the modal window automatically closes every time the parent component state is changed for some reason.

**Comment by youknowriad** [comment]
The store solution is perfect when you have global state shared across different parts of the UI. Not sure why you think it's not idea.

If you want to avoid a store and keep the state at higher-level, you can also move `withState` to your entry point and just pass its values as props...

**Comment by daext** [comment]
Thank you for the details. Is there a possibility that you can elaborate this part?

> If you want to avoid a store and keep the state at higher-level, you can also move `withState` to your entry point and just pass its values as props...

Otherwise I'll be asking in other forums as you suggested [here](https://github.com/WordPress/gutenberg/issues/13813#issuecomment-462338871).
