### ISSUE TITLE
Admin Doesn't Have Block Options

### ISSUE THREAD

**Issue by ChrissiePollock** [WordPress/gutenberg#13801]
When logged in as a site admin, some of the block options are not available unless one is the creator of the site. 

**To Reproduce**

1. Add the Image Block
2. If you are the site owner, you have the options: Upload, Media Library or Insert from URL as seen here:

![screen shot 2019-02-05 at 10 18 26 am](https://user-images.githubusercontent.com/2545184/52527217-107db800-2c93-11e9-8d61-938f3dc53417.png)

3. If you did not create the site, but are an admin, you only get the option to Insert from URL as seen here:

![screen shot 2019-02-05 at 11 18 35 am](https://user-images.githubusercontent.com/2545184/52527218-11164e80-2c93-11e9-8e36-707806efbb00.png)

**Expected behavior**
An admin should have all the same options as the site creator and other admin.

**Comment by ChrissiePollock** [comment]
I should also add that the admin did not have the option to add a poster image, either, but could when logged in as the site creator.

**Comment by swissspidy** [comment]
Did you at some point install plugins that changed user roles or something?

This looks like the user is missing the capability to upload media.

**Comment by youknowriad** [comment]
Closing as it has a good hint and seems stale.

**Comment by youknowriad** [comment]
Let's reopen if we manage to reproduce the issue.
