### ISSUE TITLE
Trying to delete shortcode with bold letters fails in Gutenberg

### ISSUE THREAD

**Issue by sfatfarma** [WordPress/gutenberg#13806]
Please check this video where I describe the issue I found: https://www.youtube.com/watch?v=5zhw-mNm36k

**Comment by jorgefilipecosta** [comment]
I'm able to reproduce the issue.
If we paste something like `<p><strong>[gallery ids="21923,21924"]</strong></p>` on the backend the shortcode is displayed in bold on the frontend a gallery appears. If we delete the bold text in the editor by selecting the content and deleting the text the delete does not has any effect.

**Comment by sfatfarma** [comment]
Exactly. :)

**Comment by ellatrix** [comment]
Sounds like the backspace key is not triggering a change. Which browser and OS is this?

**Comment by sfatfarma** [comment]
Win 10, Chrome 72

**Comment by youknowriad** [comment]
This seems fixed for me.
