### ISSUE TITLE
How to pass props to a function component that uses withState?

### ISSUE THREAD

**Issue by daext** [WordPress/gutenberg#13813]
How to pass props to a function component that uses [withState](https://github.com/WordPress/gutenberg/tree/master/packages/compose/src/with-state)?

Consider this example:

```
function MyCounter( { count, setState } ) {
	return (
		<>
			Count: { count }
			<button onClick={ () => setState( ( state ) => ( { count: state.count + 1 } ) ) }>
				Increment
			</button>
		</>
	);
}

export default withState( {
	count: 0,
} )( MyCounter );
```

How can I add props to `MyCounter` when it's actually used in a component?

**Comment by youknowriad** [comment]
Hi there!

As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you for your understanding.
