### ISSUE TITLE
Custom blocks can't use much CSS because of unfiltered_html capability 

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#13828]
**Describe the bug**
This was previously raised for Cover block: https://github.com/WordPress/gutenberg/issues/2539

If a non-Editor (or Admin in MS) uses Gutenberg with custom blocks that add some inline styles, such as `text-transform`, the block invalidates if the user doesn't have `unfiltered_html` capabilities.

This is happening with our Block library, Otter, as well as other block libraries that add inline CSS to customize blocks.

This is a really bad condition for custom block authors if they can't add inline CSS to customize their blocks. Not everyone using your block is gonna be an admin (or for MS, a super admin).

Is there a way around this, or a possible fix?

**To Reproduce**
1. Use WordPress as Author.
2. Use any block library which adds additional CSS, such as https://wordpress.org/plugins/otter-blocks/
3. Add a block, such as "Pricing"
4. Save the post and refresh the editor and you'll see unresolved errors.

**Expected behavior**
CSS or HTML added by the block shouldn't be filtered out.

**Desktop (please complete the following information):**
 Not browser/desktop specific. Happens everywhere.

**Comment by HardeepAsrani** [comment]
WordPress has a `safe_style_css` filter. If we add the CSS that we use, will it work?

**Comment by HardeepAsrani** [comment]
Using `safe_style_css` we were able to do most if but not some props like:

`filter:blur( 0px ) brightness( 1 ) contrast( 1 ) grayscale( 0 ) hue-rotate( 0deg ) saturate( 1 );`

**Comment by jorgefilipecosta** [comment]
Hi @HardeepAsrani, would using custom CSS classes in addition with [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) for dynamic CSS attributes be a possible solution?

**Comment by HardeepAsrani** [comment]
@jorgefilipecosta CSS variables won't work in our case, and we've right now done it with the server-side rendering of CSS (cool stuff), but inline CSS should be allowed. I get the reason why this limitation is there but `safe_style_css` should have some method of allowing properties like `filter` without stripping its value.

**Comment by youknowriad** [comment]
These custom CSS styles are not allowed for security reasons. I think to move this forward you'd probably have to create trac tickets for specific CSS properties you want to whitelist in the allowed style properties.

If you're looking for a whilecard here, I'm not certain this is possible and it's also better raised in a trac ticket, WP security team could chime-in and explain further.
