### ISSUE TITLE
Gallery block: Show only subset of images

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#13826]
**Is your feature request related to a problem? Please describe.**
Sometimes only the e.g. first two images of a gallery should be shown.
The user can then open the lightbox of that gallery to see the other images.
Basically a collection of images that are previewed by only showing the first image(s) on the page.

**Describe the solution you'd like**
A gallery block option for limiting the amount of images shown.

**Describe alternatives you've considered**
Hiding the other gallery item elements using CSS: Browser will still download them.
Using different Gutenberg block (like from a 3rd party plugin): Not sure there is one.

**Comment by swissspidy** [comment]
This sounds like a pretty rare use case to me, perhaps there are plugins that could add this kind of functionality?

**Comment by strarsis** [comment]
@swissspidy: What could one do to customize the output of gallery block? Are there filters a theme or plugin can use for limiting the amount of images shown? Or is there a block or plugin that offers a "limited" gallery?

**Comment by youknowriad** [comment]
I agree that this seems something completely different from the provided Gallery block to warrant a third-party implementation.
