### ISSUE TITLE
Asymmetric grid / rows in columns block?

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#13827]
**Is your feature request related to a problem? Please describe.**
A part of the page should be partitioned into two columns while the first column should be further subdvided into two rows, resulting in an asymmetric grid layout.

**Describe the solution you'd like**
Ideally the column block could be further advanced to offer grid-like features like adding rows and merging rows and columns for asymmetric grids.

**Describe alternatives you've considered**
I found no alternative yet that uses blocks and UX, there don't seem to be any plugins out there yet which offer a Gutenberg block that allows this kind of asymmetric grid layout, not even for just a "flag"-like layout that consists of two columns with one column split into two rows.

**Comment by youknowriad** [comment]
The columns block allows inserting multiple blocks inside it. What's different between inserting blocks in a column and a "row"? If you're looking for ways to split visually the rows, there is the #4900 section block coming that will solve this issue.

**Comment by strarsis** [comment]
How can a layout like this be achieved in Gutenberg editor?
![asymmetric-layout](https://user-images.githubusercontent.com/9271436/52806313-eeb47480-3088-11e9-927b-ca03def424dc.png)

The columns are equal in width, so the Gutenberg columns block with 
its current features could be used for equal width columns.
But the first column is also vertically divided into two equal parts.

**Comment by youknowriad** [comment]
The question is what is the content of these columns @strarsis 

I guess you want the overall height to be the same and this is the challenging part (needs to be fixed height to work) otherwise, you can just use 4 columns and have a longer block in the first one and two blocks in each one of the remaining columns.

**Comment by strarsis** [comment]
@youknowriad: Each "cell" should contain a profile block (name + portrait image + title + some description). The cell at the very left should consume two rows while the others should only consume one row.

**Comment by strarsis** [comment]
@youknowriad: 
I found the [Kadence Blogs](https://wordpress.org/plugins/kadence-blocks/) plugin which offers a working, nestable asymmetric columns block. This still doesn't allow adding a real row though.

**Comment by richtabor** [comment]
@strarsis I built a row block in CoBlocks that you may be able to pull this off with: https://wordpress.org/plugins/coblocks

**Comment by youknowriad** [comment]
I still feel like it's possible to combine the Columns block (which is now asymetric) and the Group block maybe to achieve what you want without any other third party block. 

Anyway, it seems that there's already a lot of options on the table here and I'm closing this issue for now.

**Comment by strarsis** [comment]
I finally found a plugin that offers a fully customizable Gutenberg grid:
https://wordpress.org/plugins/grids/

There is also Caxton plugin which (at time of writing) offers similar, fixed layouts:
https://wordpress.org/plugins/caxton/
