### ISSUE TITLE
Empty p tag renders when a p block is activated

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#13835]
**Describe the bug**
If you put your cursor inside a paragraph block, but don't enter any text, Gutenberg still renders an empty p tag.

**To Reproduce**
1. Create a new pist
2. Type something in the first paragraph
3. Hit enter
4. Don't type anything in the second paragraph
5. Save the post
6. Notice that in the post content is an empty `<p></p>` at the bottom of the post.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
This is the expected behavior, there has been prior discussions about whether we should trim the trailing empty blocks, but it was decided against it. #5185
