### ISSUE TITLE
Username @mentions in editor

### ISSUE THREAD

**Issue by SolespireMarcus** [WordPress/gutenberg#13837]
When typing the @ symbol in the new Gutenberg editor, a prompt panel appears, providing a list of Users onsite. After selecting a user, the username is pasted:

<img width="437" alt="screen shot 2019-02-11 at 16 02 55" src="https://user-images.githubusercontent.com/31710444/52642209-661eb400-2e8f-11e9-89cd-4e0b13615d8c.png">

After publish, this is the result:

<img width="307" alt="screen shot 2019-02-11 at 16 03 10" src="https://user-images.githubusercontent.com/31710444/52642349-b0079a00-2e8f-11e9-849b-57e4b49f7101.png">

The problem is that this is just plain text. I have to manually hyperlink it to the author's page. Is this a feature that never got finished?

**Comment by designsimply** [comment]
Hi! Thanks for the question. I found an explanation at https://github.com/WordPress/gutenberg/pull/4444 and would like to defer to that issue for this case.
