### ISSUE TITLE
Rerender innerblock template

### ISSUE THREAD

**Issue by DuyThanh89** [WordPress/gutenberg#13847]
I have: `<InnerBlocks` template={template}/>

with template=[[block1],[block2]]

I want to click button template will update : template=[[block1],[block2],[block3],...]
And InnerBlock re-render new template.

Somebody help me, Thanks

**Comment by youknowriad** [comment]
Hi there!

As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you for your understanding.

---

That said, for this particular question I have a quick hint. The `template` prop is something that gives the initial representation of the innerBlocks component, which means it can't be updated as the user may have touched the content.

However, you can update the content of any block, including providing new inner block objects using the data module (please read the docs about the data module). Not that you have access to the `id` of the current block as a prop in your `edit` function.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-data/
https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/

Good  luck.
