### ISSUE TITLE
Bottom indicator not showing on hover

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#13840]
**Describe the bug**
The bottom drop indicator which you get when hovering a block on another block's drop zone stopped showing after I activated the Gutenberg plugin. If I deactivate the plugin the bottom indicator reappears. Is this intended?

**To Reproduce**
1. Install Gutenberg plugin.
2. Hover a block on another block.

**Expected behavior**
Both top & bottom indicators to show when hovering a block near each individual area.

**Screenshots**
![ind](https://user-images.githubusercontent.com/9055437/52658613-2f36b580-2f04-11e9-8e6b-05b24d0302e3.gif)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [firefox, chrome]

**Additional context**
WP Version: 5.0.4-alpha-44523
Gutenberg Plugin Version: 5.0.0
Theme: Twenty Nineteen, Atomic
No other plugins activated.

**Comment by jorgefilipecosta** [comment]
Hi @amyriounis, thank you for reporting this issue! I'm not able to reproduce this issue anymore, It was probably solved as a side effect of other change. If you are still able to reproduce the problem, feel free to comment/reopen the issue.
