### ISSUE TITLE
Taxonomy selectors should use "core-data" resolvers for terms instead of maintaining a list of terms in internal state.

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#13849]
**Is your feature request related to a problem? Please describe.**
Currently, I'm working on a feature that relies on an up-to-date list of terms. Since the block editor allows you to add terms on the fly while editing a post, it would seem appropriate that this list of terms is managed in the `core/data` store, just like taxonomies for instance.

I think it's bad practice that the `HierarchicalTermSelector` and the `FlatTermSelector` both maintain an internal list (in local state) of terms while we can actually retrieve a list of terms using `wp.data.select( "core" ).getEntityRecords( "taxonomy", "category", { per_page: -1 } )`.

**Describe the solution you'd like**
I would like a new resolver in `core-data` for terms, aptly named `getTerms( taxonomySlug, arguments )`.  This should be relatively easy since the `getEntityRecords` resolver already allows for for terms to be fetched.

This resolver should then be used within the `HierarchicalTermSelector` and `FlatTermSelector`, allowing this data to be shared among other components that rely on term data.

**Describe alternatives you've considered**

**Comment by youknowriad** [comment]
Unfortunately, that's not possible at the moment because the core-data module relies on the `edit` context and doing so breaks the editor for the contributors as they don't have access to this role.

See #11643 for more details.
