### ISSUE TITLE
IndexSizeError when selecting apply format using Firefox

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#1385]
When using Firefox, I'm seeing a `IndexSizeError`  if I add a text block, select text, and then apply a format such as Bold, Italic, or Link.

ping: @spocke

**Comment by iseulde** [comment]
Not happening in plain mce, so it's most likely us doing something wrong somewhere.

**Comment by iseulde** [comment]
@mkaz This sounds like a duplicate of a previous ticket you created? #1069

**Comment by mkaz** [comment]
Too funny - I'll close this one in favor of that.
