### ISSUE TITLE
Limit Block to certin post Type only

### ISSUE THREAD

**Issue by chiraggmodi** [WordPress/gutenberg#13858]
is there any way, i can limit by custom block to testimonial post type only?
I have create meta block, but i want only to display this block in testimonial post type only.

**Comment by youknowriad** [comment]
Hi There

Yes, it's possible see #2685

---
Also, As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you for your understanding.
