### ISSUE TITLE
Watcher cannot resolve 'memize'

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#13859]
I am trying to build a custom block which is supposed to place it in the editor with 2 columns by default and then from Inspector control I can increase it up to 6 columns.

I am following https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/index.js

The watcher is unable to resolved, i.e. `memize`
The error message is `Module not found: Can't resolve 'memize' ...`

```
import classnames from 'classnames';
import memoize from 'memize';
```

I went through https://github.com/WordPress/gutenberg/issues/6707 but did not understand much of it.

I am a beginner to Gutenberg development. So don't know what I am doing wrong. I did skip some part of the code from the above URL as looked like I don't nee them in my custom block.

I have uploaded my code at https://gist.github.com/emfluenceindia/71846f7c76b19f8a974a0c3e0a30d4df

How can I fix this? :(

**Comment by youknowriad** [comment]
Hi there!

If you're building your JS files, make sure to install `memize` as an npm dependency (add to package.json + `npm install`)

--
Also, As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you for your understanding.
