### ISSUE TITLE
Left or right aligned image obscured by quote block

### ISSUE THREAD

**Issue by gitHab** [WordPress/gutenberg#13866]
Left or right aligned images are covered over by following quote block.

**To Reproduce**
1. Create quote block, add a bunch of text.
2. Create image block immediately above the quote, choose image, choose left or right alignment.
3. Check preview.

**Expected behavior**
Quote block should wrap around image and not obscure it.

**Screenshot**
![image](https://user-images.githubusercontent.com/4107222/52736038-e1b75880-2f96-11e9-8164-b652348c2e96.png)

**Comment by youknowriad** [comment]
Thanks for the report.

I just tested by adding a background to the quote block in the default theme and it works great. I think this issue is related to your theme and the way this background is applied in quotes. 

I'm closing right now but let me know if you think otherwise and why.
