### ISSUE TITLE
Add Block: Custom HTML

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1386]
Let's build a block that allows you to paste custom HTML into it.

This mockup includes a new pattern: Text button groups. It's exactly the same as the control group containing alignments, in that you can only pick one button at a time in the group. But this one has text instead of icons inside. 

## Attributes

- Code & Preview tabs

Clicking the preview tab shows a preview of the form instead of the HTML. 

Syntax highlighting and line numbers is a "nice to have", and doesn't need to be in this block in V1.

## States

Neutral:

![custom html](https://user-images.githubusercontent.com/1204802/27474189-e61c8cba-5801-11e7-86d5-d97170aafb0e.png)

Selected:

![custom html selected](https://user-images.githubusercontent.com/1204802/27474194-e8950026-5801-11e7-8db4-7cd19713b03d.png)

**Comment by StaggerLeee** [comment]
HI, What are You using to get code coloring (and line numbers) ? I have latest Gutenberg and cannot see it.

**Comment by jasmussen** [comment]
> OK, sorry...missed that "Mockup". Have seen it on some other issue too.

Right was about to say ;) syntax highlighting hasn't been implemented yet. But it would be really cool to have.

**Comment by StaggerLeee** [comment]
Do You (miss)use Amphetamines ? Or is Matt Mullenweg paying you well.

Anything people ask here you make for few days. You ask something smaller in Pods community, expect it be finished for 2 years.

Have never seen such activity and enthusiasm in anything connected to WordPress before.
