### ISSUE TITLE
Having a reusable block with ServerSideRender triggers on add new button click

### ISSUE THREAD

**Issue by pilou** [WordPress/gutenberg#13878]
**Describe the bug**
Having a reusable block with ServerSideRender triggers on add new button click

**To Reproduce**
1. Add a Lates Comments Widget Block, because it uses ServerSideRender
2. Save as reusable block
3. Click the + Add block

**Expected behavior**
Do not rerender, because content state didn't change

**Screenshots**
https://i.imgflip.com/2togwc.gif

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 71.0.3578.98 

**Additional context**
- Tested on vanilla wp 5.03, 5.1.0 beta
- In this usecase after reusable blocks are fetched http://localhost:11000/wp-json/wp/v2/blocks?per_page=100&_locale=user i think some state changes which triggers the ServerSideBlock fetch the json again and rerender after http://localhost:11000/wp-json/wp/v2/block-renderer/core/latest-comments?context=edit&attributes%5BcommentsToShow%5D=5&attributes%5BdisplayAvatar%5D=true&attributes%5BdisplayDate%5D=true&attributes%5BdisplayExcerpt%5D=true&post_id=1&_locale=user is done

**Comment by pilou** [comment]
Sorry for the small gif

**Comment by ehti** [comment]
Hi @pilou, 

Tested this today in the core editor triage. We aren't being able to reproduce it or see any error. Are you still experiencing this in the latest version?

If so, please add some clear images or steps and we'll take another look.

Thank you!

**Comment by pilou** [comment]
I don't use wp any more, so I won't test is. If you don't experience the
issue any more it's may be fixed.
Thank you.

Ehtisham Siddiqui <notifications@github.com> ezt írta (időpont: 2020. jan.
23., Cs 6:27):

**Comment by karmatosed** [comment]
For now, going to close this, however, we can always reopen if needed.
