### ISSUE TITLE
ServerSideRender remains in loading state when nothing is rendered

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#13870]
**Describe the bug**
When `<ServerSideRender />` receives a successful AJAX response `{"rendered":""}` it remains in the "loading" state instead of rendering nothing or rendering a message `No output` or similar.

This is slightly confusing because it doesn't provide user the feedback that "With these particular settings your block doesn't output anything" but instead it appears as if it's still working on getting the output:

![image](https://user-images.githubusercontent.com/6892634/52773927-c4d95e80-3044-11e9-9434-40eec0b85d56.png)

**Comment by aze3ma** [comment]
@ktmn Please could you provide a descriptive example with code sample.

**Comment by jorgefilipecosta** [comment]
I have noticed this problem before. An easy way to reproduce it is making the archives block render an empty string:
```
function render_block_core_archives( $attributes ) {
	return "";
...
```
When the change is applied and the archives block is added in the editor it stays loading forever.
A simple fix would be making sure the ServerSideRender components renders nothing (as the block rendered nothing in this case).
