### ISSUE TITLE
List Block: add type attribute for ordered list

### ISSUE THREAD

**Issue by igorbenic** [WordPress/gutenberg#13888]
**Is your feature request related to a problem? Please describe.**
I was writing a legal document and I could not choose if the list needs to be in numbers, words or any other type possible. I had to write the whole thing in one LIST block because there is no "start" option also.

**Describe the solution you'd like**
I would like to add attributes of an OL element as Block options so those are: `reversed`, `type` and `start`.

**Describe alternatives you've considered**
This can be done using the HTML of the block and changing it but this can be an issue when reloading the page since the save method might not take that into account.

And if you don't know HTML like regular users, there is no way of changing that.

**Comment by ellatrix** [comment]
This seems like something that could easily be added.

**Comment by Jackie6** [comment]
Hi @ellatrix does this mean we need to create list settings in the sidebar like below?
![image](https://user-images.githubusercontent.com/24849874/56463940-6e71fe80-63ac-11e9-8306-28b38ea11f14.png)

**Comment by ellatrix** [comment]
Exactly :)

**Comment by Jackie6** [comment]
@ellatrix I create a pr to fix this issue. There is still some work left to be done. I will continue to work on this. But I would really appreciate if you could provide some early feedback.

**Comment by ellatrix** [comment]
The attributes have been added except for `type`, which is a bit trickier. See https://github.com/WordPress/gutenberg/pull/15113#issuecomment-521613624. I think it will require some core theme changes as well. :)

**Comment by mcsf** [comment]
@Jackie6, thanks for working on this! My one note is that — for good accessibility — the Type control be a native selectbox component, similarly to how it’s used for the Image size and Default style selections.

![selecbox](https://user-images.githubusercontent.com/150562/64039783-60e73500-cb53-11e9-9fd0-46b258183337.gif)

**Comment by skorasaurus** [comment]
I am interested in seeing the additional list types in Gutenberg, willing to help move this forward where possible, and learned that @Jackie6 has added this in this [PR](https://github.com/WordPress/gutenberg/pull/15113) but it was [later reverted](https://github.com/WordPress/gutenberg/pull/15113/commits/7d4d35593e9b74cd3a7e698fc84cd3d31f7baa75) and @ellatrix  [asked for this to be made in a new PR](https://github.com/WordPress/gutenberg/pull/15113#issuecomment-521613624)

From the discussion on that PR ([specifically this](https://github.com/WordPress/gutenberg/pull/15113#issuecomment-521613624) from @ellatrix , it sounds like the next steps that are needed going forward are: 

- [ ] Confirm whether the selectors to be used are agreed upon 
(read for more context https://github.com/WordPress/gutenberg/pull/15113#pullrequestreview-230856570) 
(These may already be agreed upon but I don't fully understand just yet. )
- [ ] Make a new pull request
- [ ] Make any relevant patches to Core

Additional references: 
https://html.spec.whatwg.org/multipage/grouping-content.html#attr-ol-type

**Comment by skorasaurus** [comment]
As mentioned above, @ellatrix had mentioned the ordered list styles to be made in a new PR, so I began to re-implement it but there have been quite a bit that has changed (files being moved, etc) in just a few months. 

I think I figured out where and how to rewrite that code but there was code in packages/rich-text/src/component/editable.js 

but that file has since been removed from Gutenberg (https://github.com/WordPress/gutenberg/commit/d9de027fab3fa9635ff6f4491ff2c2fb31493451

Right now, I receive an ReferenceError that type is not defined. My code is at https://github.com/skorasaurus/gutenberg/tree/add/list-other-styles

**Comment by ramonjd** [comment]
Is it possible that this issue was already solved by:

- https://github.com/WordPress/gutenberg/pull/51186

**Comment by skorasaurus** [comment]
I think this can be closed because all of those features (what 'number' to start an ordered list, numbering style (Roman Number, and lower case roman numeral), and reverse order) have all been implemented in Gutenberg for some time.
