### ISSUE TITLE
Prevent Embed from using onReplace when template lock set to all in nested block

### ISSUE THREAD

**Issue by MonsterKing** [WordPress/gutenberg#13887]
I have created a block that has a title, a description, and an InnerBlock (for nesting core/embed). I don't want anyone to be able to add any additional blocks to the InnerBlock section. When I use templateLock="all", additional blocks can't be added, but the embed block loses functionality. Specifically, when I paste a URL into it and click the "Embed" button, I get an error (this.props.onReplace not a function). The error only goes away if I remove locking. If I've read the js for the embed block correctly, a core/paragraph block is created for the "caption." If this is true, then perhaps the problem is that by not allowing additional blocks, I stop the script from being able to create the caption's paragraph block.

I don't need the caption. In fact, I'd rather not have it, but we can ignore it. I would really like to turn off the ability to add another block, however. Does anyone know if this is possible without breaking the nested embed block?

Aside from locking (aka without locking), the entire block works fine.

Thanks for taking the time to read this!

**Comment by MonsterKing** [comment]
I don't know if this will be useful to anyone, but until I figure this out a better way, hiding the block-list-appender via css works:
.your-block-class .block-list-appender { display:none ! important; }

**Comment by jorgefilipecosta** [comment]
I think the problem here may be related to the fact that when locking all exits replacement of blocks is not possible and onReplace function is not passed to the blocks. It looks like embed block uses this function to replace itself with the correct embed after it is known and that function is not available in locking scenarios, probably this also affects CPT locking.
Thank you for reporting this issue and providing the workaround you used @MonsterKing.

**Comment by MonsterKing** [comment]
That makes sense. Thanks for replying, @jorgefilipecosta  I'm not sure of the proper etiquette here regarding closing the issue. As far as I'm concerned, it's closed, though if anything gets changed in core (in the future) that addresses it, I would love to know.

**Comment by gziolo** [comment]
> I think the problem here may be related to the fact that when locking all exits replacement of blocks is not possible and onReplace function is not passed to the blocks. It looks like embed block uses this function to replace itself with the correct embed after it is known and that function is not available in locking scenarios, probably this also affects CPT locking.

Reading that, I think this should be fixed by updating Embed block to check whether it can use `onReplace` in the first place.
