### ISSUE TITLE
One cpt doesn't pick up dark theme support

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#13885]
**Describe the bug**

I’m having a really weird issue. My site has several (7-8) custom post types, all of them created in the same way with the same settings. One of them however is acting up in the editor. I’m using dark theme support as the site has a black background. In only that one cpt the color of the placeholder content is a very dark gray (probably the same one you get when not using dark theme support). This makes the placeholder text more or less impossible to read against the black background of the editor. Is this a known issue or is there anyway to change the placeholder text in the editor stylesheet using css?

**To Reproduce**
Can't really reproduce.

**Desktop (please complete the following information):**
 - OS: centos and macOs
 - Browser  chrome (latest version)

**Additional context**

Happens both with and without the gutenberg plugin, have had this issue with at least the last 5 versions of Gutenberg and also with the plugin de-activated. Also happens with every wordpress version since gutenberg was added to core.

Using theme generatepress.

Happens with or without a custom editor stylesheet.

**Comment by youknowriad** [comment]
Can we have more details about how you register the cpts to test in similar conditions?

**Comment by slimmilkduds** [comment]
Hi!
I tried reproducing this again this morning without success. I did "solve" it by just changing name of the cpt which weirdly enough made it work again (after I had updated 1000 places where the old name was used hehe).

I would file this in the outlier category since I haven't heard anyone else experiencing it and you guys have way more important issues to focus on. I'll close this issue
