### ISSUE TITLE
Custom undo/redo possible for block?

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#13892]
Is there any way of opting-out of the default undo/redo behavior and handling block history explicitly in my block?

I've tried my luck with this:
```
withDispatch( ( dispatch ) => {
		const {
			createUndoLevel,
			redo,
			undo,
		} = dispatch( 'core/editor' );
		return {
			onCreateUndoLevel: createUndoLevel,
			onRedo: redo,
			onUndo: undo,
		};
	} )
```
but it doesn't seem to have any effect on how undo/redo affects my block. Maybe I'm not using it the right way. Could you please provide an example of how a block can handle it's own history?

**Why I need this**
My block needs to be aware of it's `innerBlocks` block types and performs checks on them to assure it. If something is out of place (a block of another type is inside it) it creates a new block of the correct type and moves the stray block* inside it. You can see how a normal undo/redo operation would be problematic in this context, as the past/future result of an undo/redo operation consists of more than one actions. 

I think that essentially what I need to do is to define when undo levels are being created for my block. Although, I cannot seem to find a way to prevent automatic in-between undo levels from being created, which would eventually lead to corrupt block state.

*stray block = block of a type that shouldn't be a direct child of the parent block (think of a row - column implementation)

**Comment by jorgefilipecosta** [comment]
There is some work in progress as part of the [phase 2 scope ](https://github.com/WordPress/gutenberg/issues/13113)  to improve undo behaviors maybe the new solution is useful here. cc: @aduth, @mcsf

**Comment by mcsf** [comment]
At the moment, it's looking like the next improvements to Undo/Redo (see long soul-searching in #8119) will preserve the model of tracking the editor's history as a whole, as opposed to a scenario of per-block history management. That said, if we do end up implementing the concept of sagas or history amends to a given block, that could be useful to the present intended use case.

However, your use case is currently not supported, @amyriounis.

**Comment by amyriounis** [comment]
@mcsf Thanks for the response, it properly addresses my initial question, and so as far as I am concerned, this issue can be closed. If you think keeping it open might be of use to someone else or serve as a reminder towards another direction regarding editor's history model further implementation, no problem either.

**Comment by amyriounis** [comment]
@mcsf @youknowriad @aduth To extend a bit on this before it gets totally forgotten, what I am essentially trying to accomplish is to develop a layout system in the likes of Elementor and Beaver Builder for Gutenberg.

**Common Use Case:**
As you know, draggin n' dropping rows and columns around is an essential part of such an editor but trying to accomplish it using Gutenberg gives me the impression that I have hit a wall.

For example, let's assume that a column has been dragged inside a row (any Gutenberg user migrating from an exisitng page builder would expect this behavior). This operation typically consists of more than one sub-operations in order to be considered complete. At the least, the row's column count must be incremented by one and the row's layout must be updated in order to apply the new layout structure. Let's say we only need those two updates. Now, when the user hits the "Undo" button after an operation like that, he expects the column to be removed from the row and put back to wherever it was, but instead what he gets is the row's layout attribute getting it's old value back which could probably invalidate the layout system since there would be a mismatch regarding the layout being applied for the current number of columns.

**Example Using Qubely Blocks**
Take a look here, the simple act of removing (or duplicating for that matter) a column, when being reverted, invalidates the layout system, cause using the current history model this operation is not treated as a whole (reverting all sub-operations it depends upon), creating a mismatch between columns count and layout.
![ezgif-3-ac2dcf84bb9a](https://user-images.githubusercontent.com/9055437/59567571-20117100-9078-11e9-816c-988d0c98e547.gif)



You can easily see that any operation that requires a number of sub-operations in order to be considered whole, suffers from the same problem. 

It's possible that I am missing something obvious here but please let me know if you think the scenario I mentioned above can be supported, maybe using another approach, as it is a crucial part of any modern page builder and I can't see how Gutenberg could not support a use case like that.
