### ISSUE TITLE
Missing seconds when planning a post

### ISSUE THREAD

**Issue by katsar0v** [WordPress/gutenberg#13898]
**Describe the bug**
When scheduling a post, a random (actually current) seconds are saved in the database. When WP_CRON is disabled and the linux crontab runs every minute exact on 00 seconds, this causes some posts to be missed.

Can we add also seconds in the planning block?

**Comment by katsar0v** [comment]
@jorgefilipecosta design should not be an issue, a simple additional input field like the minutes would be fine.

**Comment by karmatosed** [comment]
This would be functionality not design so for now removing the label for needs design.

**Comment by sarahmonster** [comment]
Let's avoid revealing the seconds in the UI—this introduces extra cognitive load for users and potentially leads them more open to errors. 

Rather than exposing additional UI controls that don't provide any real user value, let's solve this problem by saving the seconds as 00 for all scheduled posts, rather than the current second increment.

**Comment by katsar0v** [comment]
@sarahmonster currently the default value is current seconds, so not 00. I edit this via various filters and hooks in wordpress, so seconds are always 00. Maybe default value should be just 00 then (in Gutenberg, this is not a WP Core issue).

**Comment by aduth** [comment]
>WP_CRON is disabled and the linux crontab runs every minute exact on 00 seconds, this causes some posts to be missed.

This is a bit curious to me. Shouldn't it publish anything scheduled before the time it's run which hasn't yet been published, and not rely on being run at a specific time?

**Comment by katsar0v** [comment]
> This is a bit curious to me. Shouldn't it publish anything scheduled before the time it's run which hasn't yet been published, and not rely on being run at a specific time?
You are right, but obviously it does not

**Comment by aduth** [comment]
Okay, I'd say this needs further debugging then, and that #13898 would not be sufficient for closing this (cc @jorgefilipecosta). It may make sense as a general change to reflect the scheduled time at zero seconds, but it appears there's something else afoot in causing this bug.

**Comment by katsar0v** [comment]
Yes, would be another issue to investigate and debug this, however this issue is about the seconds, which cannit be entered and are always taken from current time (eg id you click publish on 18:30:15 it will take 15 as seconds and you cannot enter or change this)

**Comment by katsar0v** [comment]
Also if you plan post for 18:30 after two weeks from now, it will take the current seconds from browser, not 00, meaning the post should be published for example in two weeks on 18:30:25 (25th second just for example). Usually crons run on 0 to the 5th second (when setup as linux cronjob) and the schedule is missed. WordPress **does not publish missed schedules** and there is a plugin that fixes that
