### ISSUE TITLE
FocalPointPicker renders unlabelled input fields

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13894]
See https://github.com/WordPress/gutenberg/pull/10925#issuecomment-464060759

The FocalPointPicker component renders two input fields that are completely unlabelled:

<img width="311" alt="screenshot 2019-02-15 at 14 47 04" src="https://user-images.githubusercontent.com/1682452/52861587-37c10300-3133-11e9-965f-801a20d7b977.png">

The visible text is just plain text. There's no associated `<label>` element or `aria-label` attribute to give these two controls a proper label. I'm going to create an issue.

As this is not the first case unlabelled UI controls are merged in Gutenberg, I'd greatly appreciate some  discussion to find a way to avoid this kind of oversights. Better code reviews or automated testing may help. Thank you.

**Comment by afercia** [comment]
At this point, I'm pretty sure there are other unlabelled UI controls in Gutenberg, as some components e.g. the BaseControl allow to just ignore a proper labelling.

**Comment by afercia** [comment]
See https://github.com/WordPress/gutenberg/pull/9802#discussion_r257269125 for a general approach to avoid cases like this one.

**Comment by aduth** [comment]
Fixed in #14152 

#6989 should sufficiently track the future avoidance, currently proposed for improvement at #14151.
