### ISSUE TITLE
Bug when clicking on title block and then on new block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1390]
If you select the title block, then click on the empty "Write your story" block, you get two selections:

![image](https://user-images.githubusercontent.com/548849/27477898-ee24001c-580d-11e7-9fd5-9ba95fd5302b.png)

**Comment by kopepasah** [comment]
Currently in development by @kamataryo, see #1426.

**Comment by youknowriad** [comment]
Looks fixed to me

**Comment by youknowriad** [comment]
The bug is still here when the post content is empty. Reopening

**Comment by mtias** [comment]
This sounds like another thing that would benefit from "title" being a block. Also the fact that if you have title selected, inserting a new block adds it at the bottom of the post instead of below the title.
