### ISSUE TITLE
Won't show on WordPress side menu

### ISSUE THREAD

**Issue by Annielaing** [WordPress/gutenberg#13904]
**Describe the bug**
There is a problem with the plugin, it is not giving an option for the tab on the side. When you go try to post to a blog or page it doesn't give the option to do it. After activation, it says activated but nothing can be found anywhere on the dashboard. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33942127/52907059-e0698280-3259-11e9-8e7e-cf17f5cf32b4.png)

**Desktop **
 - Browser - Chrome
 - Version 5.0.0

**Comment by youknowriad** [comment]
I can't reproduce personally, when I enable the Gutenberg plugin I do see it on the sidebar. Maybe a conflict with other plugins/code.

**Comment by Annielaing** [comment]
Thank You, I deleted the classic editor and it seemed to have helped. Appreciate your feedback.

**Comment by youknowriad** [comment]
👍
