### ISSUE TITLE
How to execute Contact Form 7 shortcode in Editor?

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#13918]
Hello,

Is it possible to retrieve and execute CF7 Shortcode in Gutenberg editor? If possible can you please explain the steps? 

Thank you!

**Comment by earnjam** [comment]
You can use the Shortcode block to insert shortcodes, which will display on the front-end of the site. As far as retrieving them, that is up to plugin authors to implement a method for surfacing them, though I would suggest just converting them into to blocks.
