### ISSUE TITLE
Its saving feature is trash

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#13913]
![1](https://user-images.githubusercontent.com/44285360/52938231-82958180-33a4-11e9-90fc-1094d085774d.gif)
![2](https://user-images.githubusercontent.com/44285360/52938232-832e1800-33a4-11e9-99bd-eb1ad0aaec70.gif)
![3](https://user-images.githubusercontent.com/44285360/52938233-832e1800-33a4-11e9-9a5f-841f8fc0c06f.gif)

I save everytime but it never changes...

I feel so angry about it. I know you guys focus on phase 2 only. But you guys have to care details more. There are still bad things in gutenberg but I try to use it well. But I feel so angry now. What the????

**Comment by youknowriad** [comment]
Thanks for the report. I'm sorry you're having trouble. We don't focus only on phase 2, we also work on phase 1 improvements.

I'm not sure I understand the screenshots and what bug are you having?

**Comment by MYIG** [comment]
hmm... you work on phase 1 too...I can't believe it. Because i write many things here but most of them never changed... i understand the problem about korean because korean wordpress users are a few. but...

Anyway Please watch that gifs. I write · this and press spacebar and save it but it never changes...

**Comment by youknowriad** [comment]
Noting that adding "Spaces" to HTML (content) don't change anything to the output because multiple spaces is equivalent to one space, if you want spacing to be "persited", try adding non breaking spaces (`&nbsp;` in HTML).

I'm not certain how you add these spaces in the visual editor. @iseulde might know?

**Comment by MYIG** [comment]
no, it is not true. because
   this 3 space
    this 4 space it is different.

in this case
    · She sat on the grass, looking at the setting sun. -> 동시동작
   · A young man came, asking her to dance. -> 연속동작

i press spacebar again
    · She sat on the grass, looking at the setting sun. -> 동시동작
    **·** A young man came, asking her to dance. -> 연속동작

then i saved but it never changed like this
    · She sat on the grass, looking at the setting sun. -> 동시동작
   **·** A young man came, asking her to dance. -> 연속동작

i pressed 'save' button and just wait then 'autosave' but they are same.

**Comment by MYIG** [comment]
um... when i comment here, it has nothing difference.

but 3 space and 4 space are different in real. and the problem is one is 3 space and another is 4 space so i changed 3 space to 4 space but it doesn't change after saving.

**Comment by iseulde** [comment]
@MYIG Would it be possible to give us exact steps to reproduce the problem? For example: 1) create a list blocks, 2) enter some text, 3) enter a space etc. Without it, I'm not able to reproduce the problem you're describing.

**Comment by MYIG** [comment]
@iseulde hello. when I write that post, my block was list block. but my format is like that

1. ....
1) ....
· ....

2. ....
1) ....
· ....

like this. so I used · and it has a problem.  but you said I should use 'list block -> enter text -> enter space' I think you used list block right? how can I write my format???

it has no problem but it suddenly becomes problems. so I report here, but you said you guys can't do it? so I suggest 'option disable auto-changing block'(#10778) but it just closed~ so I say you guys have no detail about gutenberg and focus only on phase 2.

I already suggest many things here but it rarely changed... it is so amazing. you guys just listen and understand what do you want to. I feel stuffy so much. I still have many things to report but I keep it... I want to believe you developers more.

**Comment by youknowriad** [comment]
Doing some triage today, what are the actionable items here? It seems like the issues mentioned here are fixed or have dedicated issues?
