### ISSUE TITLE
Comments not linking to Article and includes a date of -0001/11/30 at 12:00 am

### ISSUE THREAD

**Issue by Pikkals** [WordPress/gutenberg#13915]
**Describe the bug**
Since update of Wordpress core, this error appears to be intermittent.  A person submits a comment and the comment is not linked to the article they commented under, and its date format is that of -0001/11/30 at 12:00 am 

I am hoping someone else is experiencing the same thing, or has experienced the same thing and a fix is already available.

**To Reproduce**
I do not know how to reproduce this behavior, it seems to be totally intermittent

**Expected behavior**
When a person comments, the comment needs to be linked to an article under which they commented, including the correct date and time.

**Screenshots**
![comment- date problem etc](https://user-images.githubusercontent.com/42873768/52942596-eeabc180-3373-11e9-916d-8464e3ae9a4a.JPG)

Here is what these commentators look like in the wp_comments table:  We are looking at Susan's comment in comparison to Tom's comment.  The Image 2 leads on from Image 1:

![commenter - susan m - 1](https://user-images.githubusercontent.com/42873768/52945258-f8382800-3379-11e9-97de-da1707b04529.JPG)
![commenter - susan m - 2](https://user-images.githubusercontent.com/42873768/52945268-fcfcdc00-3379-11e9-9760-9c6815bf90b0.JPG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
- Gutenberg 5.0.3–en_ZA

** PHP database **
- PHP v 7.0.33

**Comment by earnjam** [comment]
This sounds like an issue unrelated to Gutenberg. Could be a core bug, but I suspect it is likely a theme or plugin. Looks like from the screenshot that the `comment_date_gmt` is getting stored, but not the version for the timezone of the site. 

Have you tried deactivating all plugins and changing to the default theme to rule out any 3rd party code as the culprit?
