### ISSUE TITLE
Can't remove image caption containing HTML

### ISSUE THREAD

**Issue by soulstyle** [WordPress/gutenberg#13911]
**Describe the bug**
Image captions containing HTML (link or line-break) doesn't get removed when using backspace.

As a developer I can understand that the link is still there even after I removed all text, but for a normal user (client) it's not as clear. For them, the caption looks empty.
We've had multiple clients reporting this as a problem.

Shouldn't empty tags get stripped from the caption when saving?

Latest WP 5.0.3.
Tested on a fresh install with default theme and plugins.

**To Reproduce**
1. Edit a page or a post.
2. Add an image block.
3. Add a caption with a link.
4. Remove everything in the caption using backspace.

**Expected behavior**
The caption should disappear and "Write a caption.." help text should be shown.

If you save and refresh the edit page the link is still there in the caption. Either as an empty link or sometimes with the first character of the previous link text.

**Screenshots**
![screen recording 2019-02-18 at 01 42 pm](https://user-images.githubusercontent.com/1685747/52936781-44d43100-3383-11e9-8ccc-22029614c89b.gif)

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser Chrome
 - Version 72.0.3626.96

**Comment by soulstyle** [comment]
As seen in the GIF I also tried "Select all" and then backspace but the empty link is still not removed on save.

**Comment by iseulde** [comment]
@soulstyle Could you try installing Gutenberg 5.1.1 and see if the problem is still there? I can't reproduce it with the plugin. https://wordpress.org/plugins/gutenberg/

**Comment by tan-ahmed** [comment]
I can confirm the captions are not being removed on the latest WP 5.1.1 even when its just a blank space.

**Comment by jorgefilipecosta** [comment]
Hi @soulstyle, thank you for reporting this issue! The problem is not happening anymore on my tests with Gutenberg 5.8. If you are still able to reproduce the problem, feel free to comment/reopen the issue.
