### ISSUE TITLE
Add `sideEffects` property to package.json for our packages

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#13910]
**Description**
The `sideEffects` property indicates whether a package introduces any side effects. It can be specified as either `false` or as an array of files that have side effects.

By specifying this property, webpack is able to reduce the size of JavaScript bundles by eliminating unused imports:
https://webpack.js.org/guides/tree-shaking/

`sideEffects` is particularly relevant when implementing feature flags. Without it, features need to be flagged at every possible point. For further details, see this discussion: https://github.com/WordPress/gutenberg/pull/13829#discussion_r255878995
 
**How to implement this**
Packages will need to be assessed individually. The biggest cause of side effects is likely to be `registerStore`. Any function call in the outer-most scope can result in a side-effect, particularly if there's no return value:
```
registerStore( //... );
registerBlock( // ... );
```

Mutation of global or imported variables is another example:
```
import store from '@wordpress/core-data';

modifyStore( store );
store.foo = bar;

window.shim = window.shim || function() {
    // ...
};
```

Another good indication is any import that doesn't define any new variables. The imported file will almost certainly have side-effects:
```
import 'something-with-side-effects';
```

**Other ideas**
It might be possible to use a linting rule to enforce this. A quick look at npm shows limited prior art, so a custom rule might be needed.

**Comment by gziolo** [comment]
@talldan should we enable `sideEffects` property in some of the packages manually as the first step?

**Comment by gziolo** [comment]
@talldan do you plan to continue work on this issue? We added this flag to many packages where it was straightforward. I would be fine with closing this issue if handling the rest is too complicated and thus unreliable in the long run.

**Comment by talldan** [comment]
@gziolo Sorry for missing your pings. I didn't realise I'd self-assigned this. I stopped working on the eslint rule for package side effects (#14135)—although it half-worked there were too types of side-effects it didn't catch. I should've unassigned myself when closing that.

I think you're right, having an open issue here doesn't add much value. I think it's fine to continue on a case by case basis for packages and close this. Thanks for handling those PRs 👍 .
