### ISSUE TITLE
Description for Gutenberg button to include the word "link"

### ISSUE THREAD

**Issue by dc-simon** [WordPress/gutenberg#13923]
The current description for a Button Gutenberg block element is as such:

> Prompt visitors to take action with a custom button.

As the element inserted is not actually a <button> element but an <a> could we amend the wording to something like:

> Prompt visitors to take action with a button styled link.

Just so it is clear it is a link that just happens to look like a button.

**Comment by lucagrandicelli** [comment]
Not sure about this. Kinda of misleading for an average user who probably expects a button like thing on the screen, no matter which html element lies under.

**Comment by dc-simon** [comment]
But the "average user" knows what a link is... This covers both said user and the developer minded people who also use GB and know what a button actually is.

**Comment by afercia** [comment]
I’d consider to add a `link` alias for searching it:  `keywords: [ __( 'link' ) ],`. 

![screenshot 2019-02-18 at 18 56 14](https://user-images.githubusercontent.com/1682452/52969072-61865e00-33af-11e9-9014-aeb399faa3be.png)

**Comment by samikeijonen** [comment]
There is now PR in #13933.
