### ISSUE TITLE
Code Block renders embeds

### ISSUE THREAD

**Issue by mkronenfeld** [WordPress/gutenberg#13927]
**Describe the bug**
The Code Block renders embeds. 

**To Reproduce**
1. Create a code block.
2. Insert the following shortcode.

`[embed width="560" height="315"]
    https://www.youtube.com/watch?v=YuOBzWF0Aws
[/embed]`

3. Update the post.
4. You will see a YouTube Video inside a Code Block in your frontend.

**Expected behavior**
I expected the code block to display every character of (pseudo) code inside it. Nothing should render at all.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Any

**Additional context**
- WordPress 5.0.3

**Comment by spacedmonkey** [comment]
Related: #13852

**Comment by mkronenfeld** [comment]
@spacedmonkey Thanks for your head up, but only relation between both issues is the use of shortcodes.

This topic is about a rendering bug of the code block in the frontend. Yours is a feature for the embed block resp. block conversion in the backend itself.

Correct me if I am wrong.

**Comment by davilera** [comment]
This also occurs if the URL is not surrounded by the `[embed]` shortcode, but with empty lines. For example, this:

```

https://www.youtube.com/watch?v=YuOBzWF0Aws

```

renders the same result as OP described.
