### ISSUE TITLE
Consider only assigning animation styles after the page has fully loaded

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#13925]
**Describe the bug**

Currently, some animation styles are set to trigger as soon as their element first appears. For example: 

- When fullscreen mode is active, the `body` is set to fade in immediately. 
- When the sidebar is open, it is set to slide in from the right. 

These animations were mostly designed to occur after the user performs an action. The fullscreen fade was to happen when someone toggles fullscreen, and the sidebar was meant to animate in when it's toggled open. 

Because of the way these are built, they also trigger upon the initial page load. They're both quick animations, so it's a major problem, but we should consider adjusting these animations so that they don't occur in this context. 

A potential fix would be to hooking their appearance into a new `is-loaded` body class that only appears after the page is loaded, or something similar. 

**Screenshot:** 
_(GIF has been slowed down to show effect)_

![reload](https://user-images.githubusercontent.com/1202812/52958609-6ec92b80-3362-11e9-8708-627921cd74a7.gif)

**Comment by draganescu** [comment]
@kjellr is this still an issue as I've been unable to repro?

**Comment by kjellr** [comment]
Yeah, I don't see this happening anymore. 👍
