### ISSUE TITLE
HTML Block: Consider allowing users to convert between HTML and Code blocks 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#13935]
As originally raised in #8435, it might make sense to allow users to use the block switcher to convert between a Custom HTML block and a Code block. 

This would potentially benefit use cases where someone has entered code into the "Code" block, thinking that code will run on the front end. Or, for cases where a user has chosen the HTML block to write some example HTML code, thinking it'll render as code on the front end.

**Comment by draganescu** [comment]
I think this is a good ideae, added #21779 as a quick try, but it doesn't seem to cover all cases.
