### ISSUE TITLE
Update all possible blocks to use client-side rendering

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13943]
Gutenberg version 5.1 RC - test -

**Describe the bug**

Aligning Archives left - center - right has a short visible loading animation. Calendar Block also has this very short loading animation. All affected blocks:

* [ ] Archives
* [ ] Calendar
* [ ] Latest Comments
* [ ] RSS
* [ ] Tag Cloud

**To Reproduce**
1. Add the updated Archives or Calendar block.
2. Change the alignment.
3. See if a loading animation shows up.

**Expected behavior**
No visible loading animation.

**Screenshots**

Briefly seeing the loading animation for the Archive block:

![loading-animation-gutenberg](https://user-images.githubusercontent.com/5323259/53008199-2892cb80-3439-11e9-8802-c4d0046a0993.gif)

Briefly seeing the loading animation for the Calendar block:

![loading-animation-gutenberg-calendar](https://user-images.githubusercontent.com/5323259/53008387-90e1ad00-3439-11e9-8e53-24de351d3cf3.gif)

Example with the Categories block with no visible loading animation.

![no-loading-animation-gutenberg-categories](https://user-images.githubusercontent.com/5323259/53009304-83c5bd80-343b-11e9-9bdc-42e786e4f80e.gif)

**Desktop (please complete the following information):**
-  Mac OSX 10.13.6
-  Desktop Server and Chrome

**Comment by melchoyce** [comment]
I think that's an unfortunate consequence of using server-side rendering for widgets, but I'll let some devs chime in.

**Comment by ajitbohra** [comment]
That's the expected behavior for blocks using `ServerSideRender` for block edit. Action item here would be updating all possible blocks to use client-side rendering.

In docs, we recommend the same and core blocks are the best place to push this further.

> Server-side render is meant as a fallback; client-side rendering in JavaScript is always preferred (client rendering is faster and allows better editor manipulation).

https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/

**Comment by paaljoachim** [comment]
@ajitbohra 
"Action item here would be updating all possible blocks to use client-side rendering."

Should I create an new issue for this?

**Comment by gziolo** [comment]
> Should I create an new issue for this?

Yes, this is the only way to solve this issue. See Latest Posts block which has very complex set of props but works without any distractions like that because its `edit` implementation is fully implemented with JavaScript.

**Comment by paaljoachim** [comment]
It seems the easiest approach would just be to rename the title of this issue to become:
Update all possible blocks to use client-side rendering. 
Can you reopen this issue @gziolo ?

**Comment by mtias** [comment]
Such a general issue is hardly going to get much attention. It's better to open specific issues for the blocks we want to convert. Note that not all blocks are worth converting unless they have enough client interactions.
