### ISSUE TITLE
Scripts: Enforce repository.directory in package.json lint script

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#13947]
Related: #13946

The `wp-scripts lint-pkg-json` script is used to enforce `package.json` standard format:

https://github.com/WordPress/gutenberg/tree/master/packages/scripts#lint-pkg-json

With the addition of `repository.directory` as proposed in #13946, we should also enforce the inclusion of the new field.

**Comment by aduth** [comment]
It's not clear to me whether this is supported yet in `npm-package-json-lint`, since this is a very new feature introduced to npm. If not, we should seek to open an issue (and/or pull request) to propose it as an enhancement.

Possibly related rules:

- https://github.com/tclindner/npm-package-json-lint/wiki/require-repository

**Comment by greatislander** [comment]
I took a stab at a PR to [tclinder/npm-package-json-lint](https://github.com/tclindner/npm-package-json-lint/), as enforcing `repository.directory` is not yet supported: https://github.com/tclindner/npm-package-json-lint/pull/106
