### ISSUE TITLE
Entering from title automatically opens classic paragraph

### ISSUE THREAD

**Issue by Arno-van-den-Heuvel** [WordPress/gutenberg#13942]
When I typ in the title in the title block and I hit Enter, a classic paragraph opens, instead of a normal paragraph block. 

1. Open a new article
2. Hit Enter 

I would expect a paragraph block to open instead of a classic paragraph

 - OS: Windows10
 - Chrome Browser 
 - Version  72.0.3626.96

**Comment by jeremyfelt** [comment]
I just ran into this same issue and was able to resolve it by disabling the TinyMCE Advanced plugin. I'm attaching a GIF of the behavior, but it seems like it may not be a Gutenberg issue. /cc @azaozz
 
![classic-paragraph](https://user-images.githubusercontent.com/286171/57534241-73afd280-72f4-11e9-93d6-04e965e7e63b.gif)

**Comment by youknowriad** [comment]
@azaozz shared details about this here. Thanks https://github.com/WordPress/gutenberg/issues/15497#issuecomment-491002242
