### ISSUE TITLE
Missing return statement on line 175 of packages/components/src/drop-zone/provider.js

### ISSUE THREAD

**Issue by jasonculligan** [WordPress/gutenberg#13952]
Should there be a return statement in the toUpdate.map callback at line 175 of packages/components/src/drop-zone/provider.js ?

**Comment by jorgefilipecosta** [comment]
Hi @jasonculligan, thank you for opening this issue 👍  In PR https://github.com/WordPress/gutenberg/pull/13953 I describe what happened and I added a change to make sure future people reading the code don't get the same perception.

**Comment by aduth** [comment]
If possible, it would be worth exploring a lint rule which enforces an assumption that `Array#map` would always be either the value of a `return` statement, or used as the initializer to a variable declaration.

**Comment by aduth** [comment]
@jasonculligan Out of curiosity, did you come across the error as the result of some automated tooling, or just by glancing over the code?

**Comment by jorgefilipecosta** [comment]
> If possible, it would be worth exploring a lint rule which enforces an assumption that `Array#map` would always be either used as the value of a `return` statement, or as the initializer to a variable declaration.

Nice idea I will look into having a rule implemented.

**Comment by jasonculligan** [comment]
@aduth I used SonarCube Community Edition Version 7.6 (build 21501) which reported the find as a blocker type bug.
