### ISSUE TITLE
Gutenberg editor molding function.

### ISSUE THREAD

**Issue by YoshihisaSaito** [WordPress/gutenberg#13958]
How can I stop the automatic molding function and reflect the HTML you just entered?

**Comment by youknowriad** [comment]
Hi there! I'm not certain what molding function you're talking about. Can you share an example of HTML you entered, the result you had and what do you expect? Some screenshots could help. Thanks.

**Comment by YoshihisaSaito** [comment]
When you enter the original source code in the Gutenberg editor for creating a new page, p tag and br tag disappear and extra tags are inserted.

Text editor screenshots. Origin source code.
![origin-source](https://user-images.githubusercontent.com/16999864/53214629-a13f9500-3690-11e9-9e89-3f4e9b7163f7.PNG)

Gutenberg editor screenshots. Molding source code.
![molding-source](https://user-images.githubusercontent.com/16999864/53214741-1612cf00-3691-11e9-8efa-b3872e683fe3.PNG)

**Comment by youknowriad** [comment]
Are you talking about "pasting" content?

If you want to keep the exact same markup when pasting content in Gutenberg, consider using the classic block or the HTML block. These will preserve the markup AFAIK.

If you're not pasting the HTML, how are you entering your source code in Gutenberg?

**Comment by YoshihisaSaito** [comment]
Thank you very much!
Solved it with good advice.

**Comment by youknowriad** [comment]
Awesome 👍
