### ISSUE TITLE
"Open in new tab" link setting shows incorrectly when editing multiple links

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#13950]
**Describe the bug**
Editing multiple "Open in new tab" link settings sometimes results in the state being shown incorrectly on refresh.

**To Reproduce**
1. Create a new draft at /wp-admin/post.php and add at least two links
2. Enable "Open in new tab" on multiple links
3. Save the draft and refresh
4. Edit one of the links to turn off "Open in new tab"
5. Save draft and refresh
6. Edit the link that should still have "Open in new tab" enabled and note the state indicates it is disabled. Edit the other link, which should correctly show as disabled, then return to the link that should be enabled and the state will correctly show it enabled again.

This can be reproduced both within one draft and when changing this across multiple drafts.

**Expected behavior**
Editing this setting on one link should not affect other links.

**Screenshots**
![gutenberg new tab lost](https://user-images.githubusercontent.com/1900444/53026150-5aebfb00-3430-11e9-8282-d60d7e38f269.gif)

**Desktop (please complete the following information):**
 - OS: Mac OSX 10
 - Browser: Chrome
 - Version: Chrome 72.0.3626.109

**Additional context**
- WordPress 5.0.3

**Comment by youknowriad** [comment]
I'm not able to reproduce this anymore.
