### ISSUE TITLE
Wordpress block editor does not support adding Google photos

### ISSUE THREAD

**Issue by Tinytramper** [WordPress/gutenberg#13957]
**Describe the bug**
The new 'block editor' does not allow me to directly add Google photos from within a new blog post using the 'insert image' function. 

**To Reproduce**
1. Add a new blog post in Wordpress
2. Click the + sign to add a new block
3. Select image
4. Only options are: upload - media library - insert from URL. There is NOT an option to add photos from Google (as was available before with the classic editor).

**Expected behavior**
There should be an option to link to Google photos (as with old/classic editor) allowing me to add photos directly into the post without having to load my photos in the 'media' area separately. This is a huge backwards step in functionality, and extremely inconvenient for users.

**Desktop (please complete the following information):**
Firefox browser

**Additional context**
Gutenberg version 5?

**Comment by youknowriad** [comment]
Hi there!

I'm not sure how you were able to use Google Photos before but that was not part of the Classic editor by default. It's likely a plugin that was adding this feature and the feature is probably not ported yet to Gutenberg. 

I'd suggest opening an issue in the said plugin's tracker.

Thanks.
