### ISSUE TITLE
Moving the editor to the frontend

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1396]
Some thoughts here...
As the customizer and the Gutenberg editor will in a sense almost merge into a very similar experience it seems natural to just move both of them into the frontend. Seeing the site as it is with the header, sidebars (if any), content and the footer.

This means clicking edit post/page it moves directly into the frontend for a more true to layout editing experience.

**Comment by westonruter** [comment]
See https://github.com/WordPress/gutenberg/issues/1315#issuecomment-313900765

**Comment by mtias** [comment]
Closing as this is not on the roadmap for Gutenberg. The plan is to allow themes to provide the necessary styles so that the _editor_ looks like the _front-end_ when it comes to blocks.

**Comment by helloworldwhoami** [comment]
Gutenberg editor is now on frontend. Hope it might be the solution of your problem
https://wordpress.org/plugins/frontrom/
