### ISSUE TITLE
Copying text from Gist inserts a table

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#13961]
**Describe the bug**

When you copy any text from gist.github.com, it seems Gutenberg is getting the HTML markup and using that instead, which renders a table with each line as a row

**To Reproduce**
1. Go to https://gist.github.com/koke/41bd7a54d995dae00000dc9eb5b02a0d
2. Select the text and copy it
3. Paste it in a new Gutenberg post
4. A table is created

It's very tedious to recover from this and turn that table into a paragraph.

**Expected behavior**

I would have expected a paragraph with the copied text.

**Screenshots**

<img width="756" alt="hello" src="https://user-images.githubusercontent.com/8739/53073385-2f2c4c00-34e8-11e9-891b-34557a7c0c48.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0.2

**Additional context**

Tested using WordPress 5.0.3 with Gutenberg 5.0

**Comment by iseulde** [comment]
We get that markup from the browser... what can I do? :)
If you paste in editors like CKEditor or TinyMCE, you get the same thing.
Closing this issues unless there's a sane way to fix it.

**Comment by iseulde** [comment]
The best thing would be to report the issue with Github.
