### ISSUE TITLE
Handbook: Improve navigation on the sidebar

### ISSUE THREAD

**Issue by lgkonline** [WordPress/gutenberg#13962]
For me as a developer it's currently quite difficult to use the handbook/documentation. The sidebar is way too long and it's pretty hard to find what I need.

I think that only the direct child items should be visible by default and when I click on one of them, it will be expanded. Just like it already behaves with "Designer & Developer Handbook" and "Contributors Guide".

Link to the documentation: [https://wordpress.org/gutenberg/handbook/designers-developers/](https://wordpress.org/gutenberg/handbook/designers-developers/)

![Developer Documentation Screenshot](https://user-images.githubusercontent.com/7503135/53075710-1fb00180-34ee-11e9-8b0b-3bbff3fcef8f.png)

**Comment by felixtense** [comment]
### Agreed

**Comment by nosolosw** [comment]
We've just launched an improved handbook at https://developer.wordpress.org/block-editor/
