### ISSUE TITLE
IE 11: blank Demo page and JS error related to non-supported method assign()

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1397]
To reproduce:
- just go in the Demo page `?page=gutenberg-demo`

Error in the IE11 console:

![screenshot 110](https://user-images.githubusercontent.com/1682452/27482312-380e895a-5821-11e7-83e4-d307e6acf57e.png)

**Comment by westonruter** [comment]
Needs `Object.assign()` polyfill.
