### ISSUE TITLE
How to select text/node inside block programmatically?

### ISSUE THREAD

**Issue by tonyAndr** [WordPress/gutenberg#13976]
I'm looking for any alternative to TinyMCE's editor.selection.select() functionality or any other way to select DOM node or text by it's position in the document.

In my case: I have a plugin, which shows all links from the article's content in the sidebar panel.
When I click on any of those links, I want it to be selected (highlighted) in the editor.

The problem is, I can't find any documentation about selection functionality in Gutenberg, and standart 
window.getSelection/addRange isn't working as expected (it works once, but then there is no way to remove selection - .removeRange / .removeAllRanges or addRange(someNewRange) make no effect when another link clicked in the sidebar).

What is the best way to find a piece of text or DOM node (by selector), which could be in any block and then select it (not a whole block, only particular text/node)?

**Comment by iseulde** [comment]
This is currently not possible with Gutenberg APIs, as the selection state is local to the `RichText` component. There are plans to move this state to the editor state, which would make it possible to alter it. See also #12002.

I think you could use the browser API as well if you're fine with trying to find the right nodes etc. I'm a bit surprised that it doesn't work. It should work just like user selection. We don't have any logic separating user selection vs selection with the browser API. Maybe I can help more if I see an example in code.

**Comment by mtias** [comment]
@ellatrix can this one be closed?
