### ISSUE TITLE
Moving blocks on mobile is challenging

### ISSUE THREAD

**Issue by jonnyruzek** [WordPress/gutenberg#13980]
**Describe the bug**

Using an iPad, with only touch controls, it is difficult to make the move up/down arrows to appear and isn't obvious for users.

**To Reproduce**

Create new page using the block editor. Add some various blocks, then try to rearrange. The move up/down controls are not revealed unless the block is touched in certain places, such as its sides, making it not obvious to the user this is possible. The blocks cannot be dragged.

**Expected behavior**

Tapping on the block should reveal block controls, such as the move up/down arrows, and a way to drag & drop.

**Device**

 - OS: iOS (Android may apply as well)
 - Browser Chrome, Safari

**Additional context**

WordPress.com
10590760-hc

**Comment by draganescu** [comment]
Howdy @jonnyruzek I wonder, is this still an issue with the new UI? As it is today there is one place in the block controls where once tapped the mover shows: the transform handle.

I tested this on iPad and it seems to have improved this. Do you think it's still an issue?

**Comment by mtias** [comment]
Closing since there's been several improvements on mobile, including the addition of "move to".
