### ISSUE TITLE
Weird backspace behavior in Firefox

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#13982]
## Issue description
Pressing <kbd>Backspace</kbd> on empty lines has some weird behavior in Firefox.
![firefox-backspace-weirdness](https://user-images.githubusercontent.com/19592990/53117104-bfca5280-350f-11e9-86b9-064f1e69d960.gif)

## Steps to reproduce
1. Insert a Paragraph block.
2. Type a single character.
3. Press <kbd>Backspace</kbd>.
4. Notice that the Paragraph now has 2 lines.
5. Type two characters in the first line.
6. Move focus to the second line.
7. Press <kbd>Backspace</kbd> again.
8. Notice that both the second line and the last character of the first line are removed.

This bug also occurs with other blocks that use RichText.

## Testing environment
 - OS: Antergos Linux
 - Browser: Firefox Developer Edition 66.0b8
 - WordPress: 5.0.3
 - Gutenberg: 5.1 (the bug also occurred in 5.0... possibly earlier)

**Comment by youknowriad** [comment]
Could this be related and fixed by #13850 ?

**Comment by iseulde** [comment]
Yes, #13850 fixes this issue as well. Firefox inserts `<br>` elements for some actions. With that PR we keep track of line breaks inserted by us and discard the rest.
