### ISSUE TITLE
Inline Image Drop Cap issue

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#13994]
**Describe the bug**
i am using Inline Image, select Drop Cap but its not worked

**To Reproduce**

1. Click on Inline Image
2. Text Settings
3. Checked Display as Drop Cap

**Screenshots**

![inline](https://user-images.githubusercontent.com/45058029/53155874-0ab59a00-35e4-11e9-912b-8e1d228bc4f6.gif)

**Desktop (please complete the following information):**
OS: Linux
Browser Chrome
Version 71.0.3578.98
Additional context

**Gutenberg: latest from master**
WordPress: 5.1-RC2-44754

**Comment by GlennMartin1** [comment]
Likely related: https://github.com/WordPress/gutenberg/issues/9505 which was closed without resolution.

The drop-cap code should ignore initial content that cannot be drop-capped, and then drop-cap the first letter that can be drop-capped. 

Instead, other "non-drop-cappable" content creates issues like seen here.

**Comment by utsavtilava** [comment]
@GlennMartin1 

But font-size is completely worked ,why not work in drop-cap

**Comment by youknowriad** [comment]
As stated above unlike "font size" which applies to the whole block, Drop cap is by definition something that applies to the first character in the block, if it's "non-dropcappable", the content remains the same.
