### ISSUE TITLE
Transform video shortcodes to video blocks

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#14002]
It would be great if the video block contains a [transform](https://github.com/WordPress/gutenberg/blob/a615ce6862545360ce6a463a5a7a5a17f71711f4/packages/block-library/src/video/index.js#L83) for the [video shortcode](https://codex.wordpress.org/Video_Shortcode).

That way, when opening an old post containing a `[video]` shortcode (or when pasting it in a new post), they are converted automatically to video blocks like we do with the [gallery](https://github.com/WordPress/gutenberg/blob/72ff590394027945b4adea0cd1d838a6060671c1/packages/block-library/src/gallery/index.js#L117) or [caption](https://github.com/WordPress/gutenberg/blob/72ff590394027945b4adea0cd1d838a6060671c1/packages/block-library/src/image/index.js#L183) shortcodes.

It seems that all the shortcode options except width and height are supported by the video block attributes, so we might need to add new attributes for the width and height (or maybe just ignore them).

**Comment by nfmohit-wpmudev** [comment]
Submitted PR #14042 addressing this enhancement ❤️
