### ISSUE TITLE
Improve the horizontal centering of some button icons

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1400]
In the desktop view, there are two different types of buttons:
- with text
- without text

since the SVG icons have a default right margin of 4px, the icons of the buttons without text aren't really centered:

<img width="280" alt="screen shot 2017-06-23 at 16 47 55" src="https://user-images.githubusercontent.com/1682452/27487760-e5d5644c-5834-11e7-8e72-c533c8746859.png">

This changes in the responsive views, where the buttons text gets hidden and the buttons have a fixed width. However, in the desktop view we should maybe consider to remove the right margin for buttons without text.

**Comment by Rahmon** [comment]
Is this still happening? The buttons without text apparently be centered.

![gu](https://user-images.githubusercontent.com/6010232/31995261-70ab2e88-b962-11e7-9bc6-df69efcbcc0e.png)

**Comment by mtias** [comment]
Going to close, feel free to reopen if you still experience this.
