### ISSUE TITLE
Documentation: State of `innerBlocks`

### ISSUE THREAD

**Issue by AdamMarton** [WordPress/gutenberg#14004]
According to [this page](https://wordpress.org/gutenberg/handbook/designers-developers/developers/backward-compatibility/deprecations/#3-5-0), `innerBlocks` been removed from Gutenberg.

On the other hand, [Block Registration](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#transforms-optional) still referencing it (see [`transforms`](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#transforms-optional) and [`parent`](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#parent-optional)). The latter even includes a (now dead) link to [this page](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-editor/src/components/inner-blocks/).

In overall, documentation of Gutenberg was more accurate and straightforward before 5.0.

**Comment by ajitbohra** [comment]
> https://wordpress.org/gutenberg/handbook/designers-developers/developers/backward-compatibility/deprecations/#3-5-0

Mentions 
>InnerBlocks grouped layout is removed. Use intermediary nested inner blocks instead. See Columns / Column block for reference implementation.

It says `Grouped Layout` is removed in favor of using an intermediary nested blocks.

`InnerBocks` still exist (Link in docs is broken) https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/inner-blocks

Refer `Columns` block for example https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/columns
