### ISSUE TITLE
Documentation: Blocks Tutorial

### ISSUE THREAD

**Issue by AdamMarton** [WordPress/gutenberg#14005]
[Blocks Tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/) links to a repository where one can download a tutorial project to learn basic concepts of Gutenberg Blocks.

Code snippets in the [very next chapter](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/writing-your-first-block-type/) is referencing to a different directory structure (can be found [here](https://github.com/ahmadawais/gutenberg-boilerplate-es5)).

While it's not a game-breaker, it's definitely not up to date.

**Comment by ajitbohra** [comment]
Documentation refers to following https://github.com/WordPress/gutenberg-examples

Not https://github.com/ahmadawais/gutenberg-boilerplate-es5 mentioned in issue

**Comment by gziolo** [comment]
It looks like we should audit `gutenberg-examples` and ensure they stay in sync with the tuotrial. /cc @mkaz @nosolosw
