### ISSUE TITLE
How to add WPML compatiblity with custom Block created using Gutenberg?

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#14000]
Hello,

Can you please provide us details about how to add WPML compatibility to Custom block added using Gutenberg?

We added some block for Gutenberg and need to make it compatible with WPML. Does anyone know the steps for this?

We get this article but it is not useful - https://wpml.org/documentation/support/language-configuration-files/#gutenberg-blocks

Any help will be appreciable.

Regards,
Prajakta.

**Comment by ajitbohra** [comment]
https://wpml.org/documentation/support/language-configuration-files/#gutenberg-blocks

Mentions the required steps and code needed to make WPML work with the block. For support and help related WPML https://wpml.org/forums/forum/english-support/is the best place.
