### ISSUE TITLE
Table Block needs support for content types other than plain text

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#14016]
**Is your feature request related to a problem? Please describe.**
We are unable to input images, lists, captions etc into table block cells.

**Describe the solution you'd like**
Preferably, you'd be able to add multiple types of content into table cells.

**Describe alternatives you've considered**
While there are lots of issues with rich text and this type of development, I believe that a solution could be created and I'm happy to help think through and develop a solution.

**Comment by iseulde** [comment]
Images can be added. Open the block inserter and search for "inline image".

Lists inside tables becomes complex. Perhaps if we allow nesting blocks inside tables, but to be honest I don't think this will happen. Also worth noting that tables were not even supported in WordPress Core until the last release.

I'm going to close the issue as it's unlikely to get implemented anytime soon. Images you can already add though.
