### ISSUE TITLE
5.1.0 to 5.1.1 not updating

### ISSUE THREAD

**Issue by poi000** [WordPress/gutenberg#14013]
Update Failed: Download failed. Destination directory for file streaming does not exist or is not writable.

**Comment by skorasaurus** [comment]
Confirmed; I'm also unable to update to 5.1.1 from 5.1.0; while updating through the GUI (in wp-admin); I received a message stating 

> "Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions." 

Trying to update within wp-cli gave a slightly more verbose error message: 

> Warning: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions. "node_modules/.bin/tree-kill"

tree-kill has the same permissions as other files (shortcuts in its directory) 
lrwxrwxr-- 1 www-data vagrant    19 Feb 11 13:48 tree-kill -> ../tree-kill/cli.js


I am able to install other plugins in my environment without any issues.

**Comment by skorasaurus** [comment]
decided to try once more in a different environment, was successfully able to update; I think my issue was that I originally had clone the gutenberg repository to the plugins folder.

**Comment by poi000** [comment]
Tried again in IE rather than Chrome, all fine now.
