### ISSUE TITLE
Gallery: you can't select several images from media library

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1401]
You need to use the `Ctrl` key (on Windows) to be able select multiple, which is not very intuitive.
I think media library should select an image for a gallery on each click on any of them without additional keys.

Using Gutenberg plugin from WP.org v0.2

**Comment by youknowriad** [comment]
This is not specific to Gutenberg, maybe look for a similar ticket in Trac and create it if not raised before. https://core.trac.wordpress.org/

**Comment by mtias** [comment]
The "create gallery" mode of the media library allows you to just click to select images, we should select that mode for galleries by default.

**Comment by youknowriad** [comment]
Oh! my bad! I was not aware of that.
