### ISSUE TITLE
Pressing Escape in the Link inline toolbar doesn't restore previous caret position

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#14026]
When _actually inserting/updating_ a new link, everything seems to work nicely:
- test using only the keyboard
- insert or edit a link
- press the "Apply" button
- the inline toolbar closes and the previous selection or caret position are restored correctly

However, when pressing Escape to cancel the action and close the Link inline toolbar, the caret position or previous selection are not restored
- try to insert a link or edit an existing one by pressing Cmd(Ctrl) + K
- instead of pressing the "Apply" button, press Escape on your keyboard
- the inline toolbar closes
- the caret is now at the beginning of the content: instead, it should return to the previous position
- in the case of an existing link, the previous selection still looks "selected" but the caret is at the beginning of the content:

<img width="776" alt="screenshot 2019-02-21 at 18 02 49" src="https://user-images.githubusercontent.com/1682452/53188269-4876ea80-3605-11e9-980b-ca26e792d5e8.png">

In the above case, there's also one more issue: clicking on other parts of the content doesn't dismiss the inline toolbar.

See also https://github.com/WordPress/gutenberg/pull/14001#issuecomment-466069530

**Comment by paaljoachim** [comment]
From my testing this is different now then it was back in February 2019.

@joedolson Joe. As Andrea is away I am pinging you to this issue.

**Comment by joedolson** [comment]
Agree. This appears to work as expected in trunk.
