### ISSUE TITLE
Block contains not valid content

### ISSUE THREAD

**Issue by benjaminspi** [WordPress/gutenberg#14025]
**Description**
When I publish pages and revisit that page in editor mode, the content is broken.

“Block contains not valid content” (translated from german)

I get 2 options: solve and change to html. Also, the picture I uploaded are gone. Solving and changing to html breaks the site. Also jumping back to a previous version of the page does not work.

**Reproduce**
1. use two columns 
2. then use the “Classic” Element within those columns
3. publish the page 
4. go back to the editor
5. page is broken

**Desktop (please complete the following information):**
 - Windows
 - Chrome  72.0.3626.109
- WordPress Version 5.0.3

**Comment by youknowriad** [comment]
Can you send the block content used, which block you used? This can happen for several reasons and may be legitimate.

**Comment by talldan** [comment]
Noting these related issues: #14323, #13187, #12674, so I'll close this as a duplicate.
