### ISSUE TITLE
Request: Transform functions passed an extra `blockName` argument.

### ISSUE THREAD

**Issue by coderkevin** [WordPress/gutenberg#14029]
**Is your feature request related to a problem? Please describe.**

The ability to apply a single transform to multiple block types is already present in the transform specification, as `blocks: [ 'core/paragraph' ],` shows below:

```
transforms: {
    from: [
        {
            type: 'block',
            blocks: [ 'core/paragraph' ],
            transform: ( { content } ) => {
                return createBlock( 'core/heading', {
                    content,
                } );
            },
        },
    ]
},
```

However, this would be a lot better if the transform function could know what type it's getting.

**Describe the solution you'd like**

I propose adding a second argument to the transform function:

```
transform( attributes, blockName );
```

This would allow a transform to perform a `createBlock( blockName, transformedAttributes )` which could work for multiple types of blocks.

**Describe alternatives you've considered**

Right now, the only alternative is to create a separate "to" `transform` function for each and every block type.

**Comment by draganescu** [comment]
I wonder if having those granular "to" transforms isn't a good thing rather than encouraging some huge transform function bodies?

**Comment by mtias** [comment]
Closing as this is contemplated in the `experimentalConvert`
