### ISSUE TITLE
Better format boundary design

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#14023]
**Describe the bug**

Currently, the format boundary design is an added, or in some cases an updated, background colour. This doesn't really work well with all formats.

* The link format is an exception, it changes the colour to blue.
* The code format is an exception, it changes the colour to a different gray.
* Custom format would need to include their own styles as it may not work for them. E.g. a colour background button cannot have a background as a boundary style.
* It doesn't work great on different backgrounds, such as the cover image.

**Ideally**, we would need something that:

* Works well with all themes, so that themes do not need to update format boundaries.
* Works well with all formats and potential custom formats.
* Works well on all backgrounds.

I would suggest using:

* `currentColor` as it inherits the text colour, so the contrast will automatically work.
* Something that is *additional* foreground, not background. This is more difficult as it should not interfere with anything the format does. So no underline, as that interferes with links. It should also spread over the whole length. Perhaps an overline? This might not look so good.

The design of this is quite challenging. Cc @jasmussen @karmatosed @kjellr and maybe others (?) for ideas.

**Comment by iseulde** [comment]
<img width="178" alt="screenshot 2019-02-21 at 18 18 57" src="https://user-images.githubusercontent.com/4710635/53188221-31d09380-3605-11e9-89c9-86698108e076.png">

Maybe this could work?

**Comment by iseulde** [comment]
Personally I like the background, it just doesn't work in all cases. :(

**Comment by jasmussen** [comment]
Thanks for making this ticket and explaining it so thoroughly. Just to be sure, this is a design consideration, not a technical one, correct? 

I put together a codepen with two ideas: https://codepen.io/joen/pen/ZwdBgN?editors=1100

None honestly seem better than the background idea — and using mix-blend-mode we could theoretically ensure it should always work in any color sets. I also don't hagte your idea. Just wondering if it's obvious enough what's going on.

**Comment by iseulde** [comment]
The best thing I found so far is having ~20% `currentColor` and ~80% transparent as a background. The only problem is that there's no way other than using a pseudo element for it, which doesn't work well with inline elements. I tried `background: rbga( currentColor, 0.2 )`, but that doesn't work. :(

**Comment by jasmussen** [comment]
Yep, I had the exact same idea and even tried it. Didn't work. 

You can even use a magic CSS variable to use the color from the operating system selection color. But we tried that and it wasn't solid enough either :(

**Comment by iseulde** [comment]
@jasmussen I tried everything there is in CSS but couldn't get it to work in any way. Luckily we still have JavaScript. :) So now I made something that calculates the current color + opacity and puts the rule in an inline style element. Not perfect, but it works really well. There are some small downsides like hovering style won't change the background, but I think this may be ok. Even that I think I may be able to do.

Not sure if the amount of opacity is perfect, but we could tune it. When it is white, it seems like it could be more white, but when it is gray, I'm not sure if we can go darker.

Format | Before | After
--- | --- | ---
Link in Cover Image | <img width="335" alt="screenshot 2019-02-22 at 11 47 07" src="https://user-images.githubusercontent.com/4710635/53237980-63df0580-3698-11e9-93ce-63c4092afc47.png"> | <img width="340" alt="screenshot 2019-02-22 at 11 45 19" src="https://user-images.githubusercontent.com/4710635/53238001-6e010400-3698-11e9-8fbb-8841c302df7d.png">
Bold in Cover Image | <img width="255" alt="screenshot 2019-02-22 at 11 47 14" src="https://user-images.githubusercontent.com/4710635/53238013-7b1df300-3698-11e9-9f43-16c054022564.png"> | <img width="321" alt="screenshot 2019-02-22 at 11 45 27" src="https://user-images.githubusercontent.com/4710635/53238032-896c0f00-3698-11e9-9e93-9efa0287b394.png">
Bold in Button | <img width="186" alt="screenshot 2019-02-22 at 11 48 00" src="https://user-images.githubusercontent.com/4710635/53238053-9852c180-3698-11e9-8322-96467d86e428.png"> | <img width="165" alt="screenshot 2019-02-22 at 11 46 21" src="https://user-images.githubusercontent.com/4710635/53238063-9f79cf80-3698-11e9-9a83-10d877bd2eb8.png">
Link | <img width="346" alt="screenshot 2019-02-22 at 11 47 46" src="https://user-images.githubusercontent.com/4710635/53238079-ab659180-3698-11e9-8e6f-6ebce96fd5e5.png"> | <img width="336" alt="screenshot 2019-02-22 at 11 45 54" src="https://user-images.githubusercontent.com/4710635/53238091-b1f40900-3698-11e9-8204-09ffda8f9ed9.png">
Colour | <img width="136" alt="screenshot 2019-02-22 at 11 47 21" src="https://user-images.githubusercontent.com/4710635/53238102-bddfcb00-3698-11e9-96d1-50e2d0d93f40.png"> | <img width="122" alt="screenshot 2019-02-22 at 11 25 00" src="https://user-images.githubusercontent.com/4710635/53238107-c3d5ac00-3698-11e9-9ee9-1b56817328e4.png">
Bold | <img width="176" alt="screenshot 2019-02-22 at 11 47 29" src="https://user-images.githubusercontent.com/4710635/53238140-d2bc5e80-3698-11e9-8af9-4fce7f5c4ce1.png"> | <img width="164" alt="screenshot 2019-02-22 at 11 45 41" src="https://user-images.githubusercontent.com/4710635/53238159-d9e36c80-3698-11e9-9567-ec37993d5499.png">

**Comment by jasmussen** [comment]
Wow that is ... holy wow that's kind of incredible work. :slow clap for a long time:

I don't know why I didn't consider JS here — but this is a JS editor, it won't work at all without JS so it seems totally fine to do this. 

> There are some small downsides like hovering style won't change the background, but I think this may be ok.

I think that's totally okay, and can be revisited if we feel we need it.

**Comment by kjellr** [comment]
Wow, that latest exploration looks great, @iseulde! 👏  

I think the opacity could be tuned down very slightly, but otherwise that seems excellent. I totally agree with @jasmussen above — I don't see any reason not to use JS here, and I think the hovering issue is fine too. 👍

**Comment by iseulde** [comment]
@kjellr Less opacity? That would mean the background behind bold would be darker, which looks like a bit too much for me. It's hard to find a good balance.

**Comment by kjellr** [comment]
Sorry for the confusion — I mean that the background could be a little bit lighter, not darker. But yeah, striking a balance is tough. 🙂

**Comment by iseulde** [comment]
@kjellr even in that case, the background for e.g. white text would feel a bit too light to me. Happy to try to figure out to set different opacities for different circumstances though. Not sure what I’d have to base it on. :)

**Comment by kjellr** [comment]
Now that I'm looking at the screenshots again, I agree that'd be a problem in that case. Using different opacities for different backgrounds would be cool, but even if that doesn't work out I think this is a really solid solution. 👍
