### ISSUE TITLE
Pasting single line of text copied from Google Doc comes through as bold

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#14030]
When copying a single line of unformatted text in Google Docs, and pasting it in a paragraph block, the text is pasting as bold, even though the source text is not bold. However, when copying that same text as part of a multi-paragraph copy, it pastes correctly in Gutenberg. See attached screenshot.

**To Reproduce**

1. Copy a single line or a fragment of a line of unformatted text from a Google Doc
2. Paste the content in a paragraph block
3. The content pastes as bold

**Expected behavior**
The content should paste the same as the source formatting.

**Screenshots**

![paste-bold-bug](https://user-images.githubusercontent.com/465154/53200948-ced50180-35f0-11e9-9a62-62d4cba41cff.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version 72.0.3626.109

**Additional context**
- WordPress 5.0.3
- The HTML in the block is clean, `<p><strong>Lorem...</strong></p>` (this is not the same as #12991)
- Copying text that is a mix of bold and not-bold formatting pastes as just bold, e.g. copying "Lorem **ipsum** dolor" pastes entirely in bold

**Comment by iseulde** [comment]
Google Docs always wraps everything in `<strong>` tags. Looks like we're not successful at removing it for inline paste. Could you share what's been logged in the console?
