### ISSUE TITLE
Add a hook like enqueue_block_frontend_assets

### ISSUE THREAD

**Issue by Keith-Cancel** [WordPress/gutenberg#14037]
**Is your feature request related to a problem? Please describe.**
Currently, there is only 2 hooks.
- enqueue_block_assets
- enqueue_block_editor_assets

A third that only is called on the front end is clearly missing.

**Describe the solution you'd like**
Just an other hook, and perhaps called something like enqueue_block_frontend_assets.

**Describe alternatives you've considered**
Not really sure there is an alternative other than not adding the hook.

**Comment by youknowriad** [comment]
An alternative here is to use `enqueue_block_assets` with `is_admin` check https://codex.wordpress.org/Function_Reference/is_admin

**Comment by Keith-Cancel** [comment]
While that is possible to check if is_admin is false. It just seems like it would be also handy to just have a hook for it.

**Comment by AlchemyUnited** [comment]
How would this differ from the standard WP core style or script enqueue hooks? What am I missing?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
