### ISSUE TITLE
With Gutenberg Theme shows W3C CSS Validation Errors

### ISSUE THREAD

**Issue by Swagatam1975** [WordPress/gutenberg#14035]
Without Gutenberg my theme showed zero W3C CSS validation error, with Gutenberg it now shows the following errors in https://jigsaw.w3.org/css-validator/:

1 | .wp-block-column | break-word is not a word-break value : break-word
-- | -- | --
1 | .wp-block-media-text .wp-block-media-text__content | break-word is not a word-break value : break-word

**Desktop (please complete the following information):**
 - Windows 7
 - Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by draganescu** [comment]
Hi @Swagatam1975,

We use this `word-break: break-word` CSS rule for the columns block which is supported by Chrome, Safari and other WebKit/Blink browsers and ignored by other browsers.

While this will fail validation it does have a positive effect: break-word prevents cutting a word at any location for older versions of WebKit/Blink browsers.

```
// Prevent long unbroken words from overflowing.
word-break: break-word; // For back-compat.
overflow-wrap: break-word; // New standard.
```

In time we'll probably drop `word-break: break-word; ` when the browsers supporting it will have all moved on to recent versions.
