### ISSUE TITLE
Some responsiveness in the editor results in clipping

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#14046]
**Describe the bug**
At certain window sizes on desktops the blocks get clipped and become unusable.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a post in Gutenberg
2. Slowly resize window
3. At certain sizes the blocks get clipped.
4. Resizing the window a few pixels "fixes" the issue

**Expected behaviour**
No matter the window size the editor blocks should remain usable.

**Screenshots**
![clip](https://user-images.githubusercontent.com/107534/53232317-87ec1800-3693-11e9-9001-7bade4a33e37.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome, safari
 - Version latest

**Additional context**
Gutenberg 5.1

**Comment by talldan** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/14652, which has a few more details about reproducing and debugging.
