### ISSUE TITLE
Button: can't edit its label and target

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1404]
When adding a button I can enter only its url, but can't edit label and target (`_blank` for example).

![image](https://user-images.githubusercontent.com/282234/27488701-a0a6f73a-5840-11e7-9cb7-c3a928af7c82.png)

Gutenberg v0.2

**Comment by mtias** [comment]
By label do you mean the button text?

**Comment by slaFFik** [comment]
Yes, what is displayed on a button.

**Comment by mtias** [comment]
There's an issue with the placeholder text not showing properly so the cursor is missing, but you can edit the text:

![image](https://user-images.githubusercontent.com/548849/27489813-476bf8b8-583c-11e7-9a13-bd4964f81f42.png)

**Comment by slaFFik** [comment]
![button](https://user-images.githubusercontent.com/282234/27490108-bc58bc02-5845-11e7-877e-3746fd047f4c.gif)

Chrome 58, Windows 10 (latest update)

**Comment by mtias** [comment]
If you start typing before clicking on the url, does it work?

**Comment by slaFFik** [comment]
Yes. But it's not obvious that I need to actually type inside the block (not in url popover) to change the button text. There is not cursor or active placeholder is visible. I understood how to use the block only after you wrote `start typing`.

**Comment by mtias** [comment]
Yes, agreed, that is being iterated on here: https://github.com/WordPress/gutenberg/pull/1247

**Comment by iseulde** [comment]
Fixed in #1477.
