### ISSUE TITLE
Spacing issue on ColorPalette

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14049]
As you can see from the picture there seems to be spacing issue when you click on the colorpicker. The left part is going inside the box. This didn't happened until the latest update.

![](https://i.postimg.cc/t4PC1YJp/2-A1-DEA65-250-E-4-EF1-A92-A-42-F8-D7488518.png)

**Comment by draganescu** [comment]
Hey @ravishakya I am getting a different kind of space, at the right side:

<img width="267" alt="screenshot 2019-02-22 at 12 57 06" src="https://user-images.githubusercontent.com/107534/53238322-b375ff00-36a1-11e9-8842-2fb1e276a3ef.png">

Which block are you editing  and what browser are you using?

**Comment by youknowriad** [comment]
I'm not certain, but I think I saw updates to the styles of this component recently, so this might be already fixed.

**Comment by draganescu** [comment]
This seems fixed in latest WP indeed, so I will close this issue. @ravishakya let us know if it still is a problem :)
