### ISSUE TITLE
IE11: don't use the CSS value `unset` 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#14055]
Right now, there are two occurrences of `unset` used for `max-width`.

As far as I know, the CSS value `unset` is not supported by IE11 and shouldn't be used. 

Note:
not sure the one used for `wp-block-media-text` actually targets something, as the chile selector used there doesn't match the markup structure.

/Cc @jasmussen

**Comment by aduth** [comment]
It may be worth exploring how we can programmatically forbid this, e.g. by including a new rule for the existing `stylelint` CSS lint process.

https://stylelint.io/user-guide/rules/declaration-property-value-blacklist/

Since the rule appears to support regular expressions, I could imagine it would be possible to do:

```json
{
  "/.*/": [ "unset" ]
}
```

**Comment by ntwb** [comment]
> It may be worth exploring how we can programmatically forbid this, e.g. by including a new rule for the existing stylelint CSS lint process.
> 
> stylelint.io/user-guide/rules/declaration-property-value-blacklist
> 

Indeed that is one way of accompanying this, another is to use the [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features) plugin which uses [caniuse](http://caniuse.com/), [doiuse](https://github.com/anandthakker/doiuse), and [@wordpress/browserslist](https://github.com/WordPress/gutenberg/tree/master/packages/browserslist-config).

> _"This is a good rule to use with "warning"-level severity, because its primary purpose is to warn you that you are using features not all browsers fully support and therefore ought to provide fallbacks. But the warning will continue even if you have a fallback in place (it doesn't know); so you probably do not want this rule to break your build. Instead, consider it a friendly reminder to double-check certain spots for fallbacks."_

The results of my testing the `stylelint-no-unsupported-browser-features` plugin:

### Opera Mini
- Unexpected browser feature `background-img-opts` is only partially supported by Opera Mini all
- Unexpected browser feature `border-radius` is not supported by Opera Mini all
- Unexpected browser feature `css-animation` is not supported by Opera Mini all
- Unexpected browser feature `css-boxshadow` is not supported by Opera Mini all
- Unexpected browser feature `css-fixed` is not supported by Opera Mini all                                 - Unexpected browser feature `css-repeating-gradients` is not supported by Opera Mini all
- Unexpected browser feature `css-textshadow` is only partially supported by Opera Mini all
- Unexpected browser feature `css-transitions` is not supported by Opera Mini all
- Unexpected browser feature `css-unset-value` is not supported by IE 11, Opera Mini all
- Unexpected browser feature `pointer-events` is not supported by Opera Mini all
- Unexpected browser feature `transforms2d` is not supported by Opera Mini all

### IE 11
- Unexpected browser feature `css-featurequeries` is not supported by IE 11
- Unexpected browser feature `flexbox` is only partially supported by IE 11


### Opera Mini & IE11
- Unexpected browser feature `calc` is not supported by Opera Mini all and only partially supported by IE 11
- Unexpected browser feature `css-initial-value` is not supported by IE 11, Opera Mini all
- Unexpected browser feature `outline` is not supported by Opera Mini all and only partially supported by IE 11
- Unexpected browser feature `viewport-units` is not supported by Opera Mini all and only partially supported by IE 11

### Current Browsers (Per @wordpress/browserslist-config)
- Unexpected browser feature `css-appearance` is not supported by IE 11, Opera Mini all and only partially supported by Edge 17,18, Firefox 68,69, Chrome 75,76,77, Safari 12,12.1, Opera 60,62, iOS Safari 12.0-12.1,12.2-12.3, Android Browser 76, Chrome for Android 76, UC Browser for Android 12.12, Samsung Internet 9.2
- Unexpected browser feature `css-clip-path` is not supported by IE 11, Edge 17,18, Opera Mini all and only partially supported by Chrome 75,76,77, Safari 12,12.1, Opera 60,62, iOS Safari 12.0-12.1,12.2-12.3, Android Browser 76, Chrome for Android 76, UC Browser for Android 12.12, Samsung Internet 9.2
- Unexpected browser feature `css-filters` is not supported by IE 11, Opera Mini all and only partially supported by Edge 17,18
- Unexpected browser feature `css-gradients` is not supported by Opera Mini all and only partially supported by Safari 12,12.1, iOS Safari 12.0-12.1,12.2-12.3
- Unexpected browser feature `css-masks` is not supported by IE 11, Edge 17, Opera Mini all and only partially supported by Edge 18, Chrome 75,76,77, Safari 12,12.1, Opera 60,62, iOS Safari 12.0-12.1,12.2-12.3, Android Browser 76, Chrome for Android 76, UC Browser for Android 12.12, Samsung Internet 9.2
- Unexpected browser feature `css-mixblendmode` is not supported by IE 11, Edge 17,18, Opera Mini all and only partially supported by Safari 12,12.1, iOS Safari 12.0-12.1,12.2-12.3
- Unexpected browser feature `css-resize` is not supported by IE 11, Edge 17,18, iOS Safari 12.0-12.1,12.2-12.3, Opera Mini all
- Unexpected browser feature `css-sticky` is not supported by IE 11, Opera Mini all and only partially supported by Edge 17,18, Chrome 75,76,77, Opera 60,62, Android Browser 76, Chrome for Android 76, UC Browser for Android 12.12- Unexpected browser feature `css-textshadow` is only partially supported by Opera Mini all
- Unexpected browser feature `css3-cursors-newer` is not supported by IE 11, iOS Safari 12.0-12.1,12.2-12.3, Opera Mini all, UC Browser for Android 12.12, Samsung Internet 9.2
- Unexpected browser feature `intrinsic-width` is not supported by IE 11, Edge 17,18, Opera Mini all and only partially supported by Firefox 68,69, Safari 12,12.1, iOS Safari 12.0-12.1,12.2-12.3
- Unexpected browser feature `multicolumn` is only partially supported by Firefox 68,69, Chrome 75,76,77, Opera 60,62, Android Browser 76, Chrome for Android 76
- Unexpected browser feature `object-fit` is not supported by IE 11 and only partially supported by Edge 17,18
- Unexpected browser feature `text-decoration` is not supported by IE 11, Edge 17,18, Opera Mini all and only partially supported by Firefox 68,69, Chrome 75,76,77, Safari 12,12.1, Opera 60,62, iOS Safari 12.0-12.1,12.2-12.3, Chrome for Android 76, UC Browser for Android 12.12, Samsung Internet 9.2
- Unexpected browser feature `user-select-none` is not supported by Opera Mini all, UC Browser for Android 12.12
- Unexpected browser feature `will-change` is not supported by IE 11, Edge 17,18, Opera Mini all
- Unexpected browser feature `word-break` is not supported by Opera Mini all and only partially supported by UC Browser for Android 12.12
- Unexpected browser feature `wordwrap` is only partially supported by IE 11, Edge 17, Opera Mini all

----

To test yourself, apply the following diff and run 	npm install`:

```diff
diff --git .stylelintrc.json .stylelintrc.json
index 648e4d111..7a8ae8fd8 100644
--- .stylelintrc.json
+++ .stylelintrc.json
@@ -1,5 +1,6 @@
 {
-	"extends": "stylelint-config-wordpress",
+	"extends": "stylelint-config-wordpress/scss",
+	"plugins": ["stylelint-no-unsupported-browser-features"],
 	"rules": {
 		"at-rule-empty-line-before": null,
 		"at-rule-no-unknown": null,
@@ -11,6 +12,9 @@
 		"no-duplicate-selectors": null,
 		"rule-empty-line-before": null,
 		"selector-class-pattern": null,
-		"value-keyword-case": null
+		"value-keyword-case": null,
+		"plugin/no-unsupported-browser-features": [true, {
+			"severity": "warning"
+		}]
 	}
 }
diff --git package.json package.json
index 5bcba77dc..c9954b485 100644
--- package.json
+++ package.json
@@ -146,7 +146,9 @@
 		"simple-git": "1.113.0",
 		"source-map-loader": "0.2.4",
 		"sprintf-js": "1.1.1",
-		"stylelint-config-wordpress": "13.1.0",
+		"stylelint": "11.0.0",
+		"stylelint-config-wordpress": "15.0.0",
+		"stylelint-no-unsupported-browser-features": "3.0.2",
 		"typescript": "3.5.3",
 		"uuid": "3.3.2",
 		"webpack": "4.41.0",
```

**Comment by paaljoachim** [comment]
How can we move this issue onward?
Thanks!

**Comment by laras126** [comment]
According to [this recent discussion](https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/), it looks like Core will be dropping support for IE11. If that is the case, can this issue be closed?

**Comment by paaljoachim** [comment]
I think we will just leave it as it is for now. Until additional discussions in relation to time line of when IE11 will be dropped.

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
