### ISSUE TITLE
CSS output frontend

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14053]
**Is your feature request related to a problem? Please describe.**
Let's say you have a block where users can control the spacing of the block. For now what i am doing is adding spacing for each block in php render callback. eg.

```
function my_custom_block( $attr ){

    $padding_top = $attr['padding_top'];

    <style>.block1{ padding-top: $padding_top }<style>

    <div class="block1">{ CONTENT }</div>
}
```
This is really time consuming.

**Describe the solution you'd like**
What can be done is in `attributes` why not add css output.

eg. 

```
attributes: {
   padding_top:{
        type: 'string',
        default: '10',
        css_output: {
              'element' : '.block1',
              'property' : 'padding-top',
              'suffix' : 'px'
        }
   }
}
```
and in the frontend it will be displayed like this

```
<style>.block1{ padding-top: 10px}<style>
```

**Comment by vkoves** [comment]
@ravishakya -  with the existing block behavior, you could have an attribute for the padding, like you indicate:

```js
attributes: {
  paddingTop: {
    type: 'string',
    default : '10'
  }
}
```

And then you can just inline the style in your edit and save functions like so:

```js
save: function(props) {
  var paddingTop = props.attributes.paddingTop + 'px';

  return el(
      Fragment, null,
      el(
          'div',
          {
              style: {
                  paddingTop: paddingTop
              }
          }
      )
  );
}
```

I don't work on Wordpress, but I've been making custom blocks a lot recently, and this type of paradigm is something we use to good effect, and several tutorials follow this style. This also makes it relatively easy to have multiple style attributes available to edit. I hope this is helpful!

**Comment by youknowriad** [comment]
Seems like there's already a good reply :)
