### ISSUE TITLE
Import/export doesn't work

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#14068]
This is how it's obtained via `get_posts()` (please note that I also `json_encode` it):
`"post_content": "<!-- wp:myslug\/some-block-name {\"content\":\"This is some normal text. \\u003ca href=\\u0022https:\/\/example.com\/\\u0022\\u003eThis is a link but as you can see it was exported incorrectly and is being imported incorrectly\\u003c\/a\\u003e!\"} \/-->\n\n`

This is how it's displayed in the source code after being imported via `wp_insert_post()`:
`This is some normal text. u003ca href=u0022https://example.com/u0022u003eThis is a but as you can see it was exported incorrectly and is being imported incorrectlyu003c/au003e!`

**Expected behavior**
It must be possible to export post and import post without `<` and `"` being modified anyhow.

Tested on the just released WordPress 5.1.

**Comment by youknowriad** [comment]
I feel this is better served as a Core Trac Ticket, as these php functions are not Gutenberg related.

**Comment by nickcernis** [comment]
Just to close a loop here and note that I opened a Trac ticket on this here: https://core.trac.wordpress.org/ticket/47420
