### ISSUE TITLE
How to use wp.data.withSelect now?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#14064]
This was copied from the older documentation and it was working for me but stopped working by itself:
```
edit: wp.data.withSelect(function(select){
	return {
		customtype: '/wp/v2/customtype?per_page=5'
	};
})(function(props){
	if(!props.customtype.data){
		return __('Loading...');
	}

	if(props.customtype.data.length === 0){
		return __('No customtype.');
	}
```

Now I see some updated documentation page https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-data/ but this is not very useful if I can't quickly solve the simplest possible task (of fetching 5 posts from custom post type)!

Can someone please update the documentation to contain the same information as previously (that is: a copy-paste example of how to fetch 5 custom post types)?

**Comment by jorgefilipecosta** [comment]
Hi @manake, thank you for creating this issue. We still provide a sample usage of withSelect to implement the latest post block.
The sample is available at https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/.
The posts array contains should contain more than 5 posts (provided they exist)  and it should be possible to change the post type to a static CPT.
I'm closing the issue for now, if you think some detail is missing in the docs feel free to reopen and we can look further.

**Comment by manake** [comment]
That example, when copied, was returning `posts: null` for me when the final callback function had a JavaScript error (I was trying to access `props.posts.data` instead of `props.posts` by mistake).

So, what I was getting in the console was misleading and I thought it doesn't work but all is solved now. Thank you.
