### ISSUE TITLE
Embedding: entering the link in text on a new line doesn't work

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1406]
In old editor we are able to enter on a separate line (paragraph) a link that we want to be embedded - and it will be converted properly and displayed as an embed on front-end. Currently it seems to be not working in Gutenberg v0.2. 

Is it on purpose? It's much faster than manually making 3 clicks (`+`, scroll, `Embed post`, insert the link in input).

**Comment by youknowriad** [comment]
Duplicate #1033
