### ISSUE TITLE
editor-styles.scss overrides the default list-style-type set by the browser

### ISSUE THREAD

**Issue by nyordanov** [WordPress/gutenberg#14074]
**Describe the bug**

Browsers typically include `ul ul ul { list-style-type: square }` in their user agent's styles. Currently Gutenberg overrides this, leading to inconsistencies between the editor and the frontend, unless themes specifically include additional styles to override the `ul ul { list-style-type: circle }` added by Gutenberg.

**Expected behavior**

Either include styles for the third level unordered lists, or remove this entirely: https://github.com/WordPress/gutenberg/blob/a779901c4fba1d8cd32475d8489708c2a134bb9f/packages/editor/src/editor-styles.scss#L24-L35

**Screenshots**

[Browser default](https://screenshotscdn.firefoxusercontent.com/images/24295fdc-dc06-414b-b264-92cd70392914.png)
[Gutenberg styles](https://screenshotscdn.firefoxusercontent.com/images/be83ea80-b74d-40fb-9a7f-e29820a81bb4.png)

**Desktop (please complete the following information):**
 - Browser: checked on Chrome and Firefox
 - Version: all

**Comment by youknowriad** [comment]
Gutenberg without theme editor styles is "opinionated", it means it can style some elements to match the required output. 

Theme can opt-in and implement their own editor styles to have a WYSIWYG experience but by default no matter what styles we include, there will always be a difference between frontend and backend unless theme adjusts the editor styles.

I think we should close this issue but pinging some folks with more expertise in this are. cc @jasmussen @kjellr

**Comment by kjellr** [comment]
Thanks for the ping, @youknowriad. It sounds like we're currently overriding styles in the editor, but not carrying those through to the front end. Either way, we should make this looks the same in both places. 

That said, I'm not sure it makes sense for us to be too opinionated about the bullet styles. I think it's fine to have both the backend and the frontend align to browser defaults for this bullet hierarchy (I'm guessing all the major browsers use the same defaults here, but I could be wrong).

**Comment by jasmussen** [comment]
I have a feeling that the reason those styles are there is because if they are not, we _inherit the styles that WordPress provides_.

In other words, I don't think this is a question of having opinionated styles or not, this is a question of CSS bleed.

Long term, the solution could involve Shadow DOM, or just better scoped admin styles. Both should prevent the cascade for irrelevant styles from entering the editing canvas. But near term, let's make sure that whatever we remove, we test and make sure there isn't some WordPress style that just bleeds through instead.

**Comment by nyordanov** [comment]
>  I think it's fine to have both the backend and the frontend align to browser defaults for this bullet hierarchy

That's my point, except that I don't particularly care about the frontend styles in this case. I just want the default backend styles to match the browser defaults.

**Comment by jasmussen** [comment]
> I just want the default backend styles to match the browser defaults

That's reasonable. But in case this is a matter of CSS bleed, that likely means we'll still want some CSS  a la this:

```
ul { 
 	list-style-type: initial; 
 }
```

**Comment by carolinan** [comment]
The list style type in editor and front matches, and I believe that is the expected result.
My personal opinion is that it is more important that the views match, than that one view matches the browser defaults.

**Comment by kathrynwp** [comment]
@jasmussen @youknowriad Circling back to see whether we can move this forward somehow, or whether we might want to close it out as a "Maybe later" – thanks for having a look!

**Comment by jasmussen** [comment]
Thanks for the ping! I would tend to agree with Carolina and Riad, this was intentionally done, but is something an editor style can override and customize. So I'll close this one out for now.
