### ISSUE TITLE
Docs: Link not working if its further one level deep in packages src

### ISSUE THREAD

**Issue by ajitbohra** [WordPress/gutenberg#14076]
https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#parent-optional

Here the link to `innerblocks` is broken as it further one level deep.

https://wordpress.org/gutenberg/handbook/contributors/document/#using-links
```
/docs/*.md
/packages/*/README.md
/packages/components/src/**/README.md
```

In this case its 
`/packages/components/src/**/**/README.md
`

Related https://github.com/WordPress/gutenberg/issues/14004

cc @gziolo

**Comment by gziolo** [comment]
This links works for me, it loads GitHub url which is fine. I’m closing this issue, let me know if I missed something.
