### ISSUE TITLE
Scrolling in fullscreen mode is not possible.

### ISSUE THREAD

**Issue by mkronenfeld** [WordPress/gutenberg#14078]
**Describe the bug**
You can no longer scroll the Gutenberg content in the fullscreen mode. Scrolling the sidebar is still possible.

**To Reproduce**
1. Open any post.
2. Start fullscreen mode.
3. Try to scroll.

**Expected behavior**
As a user I expect the fullscreen mode to behave exactly like the default mode.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 5.1

**Comment by youknowriad** [comment]
@mkronenfeld Thanks for opening the issue. I noticed this too but it seems to be fixed in the Gutenberg plugin. All the improvements in the Gutenberg plugin will land in WordPress Core in the next version. Install the plugin if you want to test the features and fixes ahead of time.
