### ISSUE TITLE
render_block() doesn't render YouTube videos

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#14080]
This renders YouTube videos:
```
echo apply_filters( 'the_content', $content );
``` 

This doesn't render YouTube videos:
```
$blocks = parse_blocks( $content );

foreach( $blocks as $key => $block ) {
    echo render_block( $block );
}
```

That's unexpected.

**Comment by youknowriad** [comment]
Why that's unexpected? youtube videos are rendered using the embed filter which is a separate behavior different from the `render_block` function.

**Comment by manake** [comment]
I see.

That will be unexpected to 99% of people.

If there is a function with the name `render_block()` then as its name suggests it will "render every single block from PHP object to final state". Is this not what these two words essentially mean: RENDER + BLOCK? They do. So, the name is too misleading at this moment.

Maybe something like this would be better:
- `render_block` - converts PHP object to a complete block. No exceptions allowed.
- `render_block_partial_embed` - does some partial rendering.
- `render_block_partial_some_other_intermediary_preparation_step`

Only this looks OK to me.

**Comment by youknowriad** [comment]
`render_block` means render the dynamic block callback if existing, at least that's what the function is for. It's true that the name might be confusing but I don't think it was ever meant to be called by third-party code.

**Comment by manake** [comment]
At least please someone add this information to https://developer.wordpress.org/reference/functions/render_block/

The current description "Renders a single block into a HTML string." is misleading. That's not what that function does.

If I want to `parse_blocks()` and then render them manually what are ALL functions that I have to run? This information should be added there. Is it this:
```
echo apply_filters( 'the_content', render_block( $block ) );
```

**Comment by youknowriad** [comment]
> what are ALL functions that I have to run?

I don't really know, since `the_content` filter is "open" for third-party code as well, the list might be long. Ideally, you'd just run this filter over your HTML (not sure how is that possible though).

I'd suggest following this with a trac ticket as this code don't live in the Gutenberg repository anymore.

**Comment by richbrat** [comment]
@manake I noticed that you also posted this: https://github.com/WordPress/gutenberg/issues/7359
Maybe we have the same problem. I'm using a block template and want to output the title after the first block (which often is a Youtube embed). Did you solve this somehow?

**Comment by sschat** [comment]
Yes, 
got the same issue, the "google" brought me here. 
I parse the blocks to filter out, or catch a certain block.
Then after that, i used indeed the "render_block" function. 
All worked well, except the default youtube block. 

So, now i apply the filters to it:

`$clean_content .=  apply_filters( 'the_content', render_block( $block ) );`

And now the youtube block does work. 

Thanks community!

**Comment by chvon7thal** [comment]
> `render_block` means render the dynamic block callback if existing, at least that's what the function is for. It's true that the name might be confusing but I don't think it was ever meant to be called by third-party code.

On first reading, I thought the behavior as disturbing as manake sees it. When you understand that Gutenberg is nothing else then a filter for handling the content field of the post table. You understand, that what ever render_block gives back follows the workflow rules applying to this field. What makes Gutenberg development difficult, is the multiple layers of content rendering. react saving, dynamic javascript triggered by the block, and, and of course the the_content hook, that I forgot in this case.

@ sschat
Your post was a day saver.

**Comment by paulbrzeski** [comment]
Can the WP documentation please be updated as per @manake's suggestion?

I was scratching my head wondering what was going on until I found this thread.

I had checked the official docs and already resolved a block rendering issue by using render_blocks but thought it was some kind of HTML filtering issue heh.

**Comment by apieschel** [comment]
> So, now i apply the filters to it:
> 
> `$clean_content .= apply_filters( 'the_content', render_block( $block ) );`
> 
> And now the youtube block does work

This solution works if you're rendering an individual block, or a list of blocks all on the same nested level, but unfortunately it doesn't work if the Youtube Embed is an InnerBlock. Encountered when trying to use `render_block` to render a cover block containing a Youtube Embed for a custom hero area.
