### ISSUE TITLE
Post thumbnail loading full size

### ISSUE THREAD

**Issue by wpchannel** [WordPress/gutenberg#14084]
Post thumbnail should be using small size as classic editor did. Gutenberg editor displays full resolution which is slow and not green.

Just add a post thumbnail like a 6000 x 4000 pixels.

**Comment by jorgefilipecosta** [comment]
Hi @wpchannel thank you for reporting this issue. Just to confirm, by "post thumbnail" we are talking about the editor calls "feature image", is that right?
Thank you in advance for the clarification.

**Comment by wpchannel** [comment]
Hi @jorgefilipecosta yes exactly!

**Comment by jorgefilipecosta** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/15844.
