### ISSUE TITLE
Add block at the top of block

### ISSUE THREAD

**Issue by pilou** [WordPress/gutenberg#14087]
**Describe the bug**
If I click the "Add block" at the top of this block, the new block should be inserted above this block, regardless where the focus is. If the focus is in an empty paragraph the new block is replaces the paragraph block where the input focus currently is.

**To Reproduce**
1. Create any block
2. Set focus on empty paragraph below the new block, but don't type anything
3. Click the "Add block" button of the block created at 1. step
4. See error, the paragraph is replaced by the block created at 3. step 

**Expected behavior**
The block created at 3. step should be above the block created at 1. stem

**Screenshots**
https://www.youtube.com/watch?v=YI-ZbFR7UYI

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
- Tested on vanilla WP 5.1.0

**Comment by jorgefilipecosta** [comment]
Hi @pilou thank you for reporting this issue, I'm able to reproduce it in my tests.

**Comment by jorgefilipecosta** [comment]
Fixed as part of https://github.com/WordPress/gutenberg/pull/14020.
