### ISSUE TITLE
If I change a reusable block, it will not be taken over.

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#14085]
**Describe the bug**
I changed the background color of a reusable block. Everything is displayed correctly in Gutenberg. But in the frontend the color is not adopted:

**Gutenberg:**
![screenshot_1](https://user-images.githubusercontent.com/9355398/53346478-61d6aa00-3917-11e9-94fd-e54e82fe1405.png)

**Frontend (No gray Background):**
![screenshot_2](https://user-images.githubusercontent.com/9355398/53346534-7ca91e80-3917-11e9-981b-56c43b9a87e4.png)
https://baubeaver.de/abbund

**To Reproduce**
1. Go to 'reusable block'
2. Click on 'backgorund color'
3. Change the background color
4. Check Frontend and see error

**Expected behavior**
That the color is also displayed in the frontend.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 72.0.3626.119 (Offizieller Build) (64-Bit)

**Additional context**
- Gutenberg 5.1 and Wordpress 5.1
- I guess it's also because of the custom colors I've set. Because the problem doesn't occur with all blocks.

The code i use in the function.php:
`// Custom Colors Gutenberg
add_theme_support( 'editor-color-palette', array(
    array(
        'name' => __( 'BROWN', 'affiliatetheme-child' ),
        'slug' => 'brown',
        'color' => '#423733',
    ),
    array(
        'name' => __( 'LIGHT BROWN', 'affiliatetheme-child' ),
        'slug' => 'light-brown',
        'color' => '#877F7A',
    ),
    array(
        'name' => __( 'GREY50', 'affiliatetheme-child' ),
        'slug' => 'grey50',
        'color' => '#7F7F7F',
    ),
    array(
        'name' => __( 'GREY', 'affiliatetheme-child' ),
        'slug' => 'grey',
        'color' => '#E2E2E2',
    ),
	array(
        'name' => __( 'ORANGE', 'affiliatetheme-child' ),
        'slug' => 'orange',
        'color' => '#F2C42E',
    ),
	array(
        'name' => __( 'RED', 'affiliatetheme-child' ),
        'slug' => 'red',
        'color' => '#FD5A5C',
    ),
) );
`

**Comment by jorgefilipecosta** [comment]
Hi @SchneiderSam, thank you for reporting this issue.
Reusable blocks have some particularities, the blocks inside a reusable block are saved in an external post. If we add a reusable block with a paragraph we press edit; we change the background color, and we press normal save button the reusable block is not changed we are just changing the post referencing the reusable block, not the reusable block itself. In my tests, if I press the "Save" button in the reusable block itself the background color is changed ( the reusable block post is saved), could you confirm if that's the case?

**Comment by jorgefilipecosta** [comment]
Hi @SchneiderSam, thank you for reporting this issue.
Reusable blocks have some particularities, the blocks inside a reusable block are saved in an external post. If we add a reusable block with a paragraph we press edit; we change the background color, and we press normal save button the reusable block is not changed we are just changing the post referencing the reusable block, not the reusable block itself. In my tests, if I press the "Save" button in the reusable block itself the background color is changed ( the reusable block post is saved), could you confirm if that's the case?

**Comment by SchneiderSam** [comment]
Hi,

nope. So either I press the wrong save button or it just doesn't work.

The block itself:
![screenshot_2](https://user-images.githubusercontent.com/9355398/53371710-48525400-3951-11e9-8ee1-07e83df7d320.png)


and also in the post:
![screenshot_3](https://user-images.githubusercontent.com/9355398/53371798-83548780-3951-11e9-8e47-eb24522932a3.png)

**Comment by SchneiderSam** [comment]
@jorgefilipecosta Thank you for your fast Supoort

**Comment by SchneiderSam** [comment]
@jorgefilipecosta any Update here?

**Comment by jorgefilipecosta** [comment]
Hi @SchneiderSam, I am still having problems reproducing this issue.
I have a couple of question that may help me find the cause of this problem:
If we change the color of a normal not reusable paragraph do the colors get applied?
If we change the color to a custom color e.g: #f1f02a is the color applied?
Are classes that set these colors implemented and loaded on the frontend of the website e.g:".has-brown-background-color"?

Thank you in advance for the help.

**Comment by SchneiderSam** [comment]
Hi,

thank you for the support!

> If we change the color of a normal not reusable paragraph do the colors get applied?

No. In the Editor yes, but not in the frontend:

![screenshot_3](https://user-images.githubusercontent.com/9355398/53976841-1cc92980-4108-11e9-8576-029ced316d90.png)




> If we change the color to a custom color e.g: #f1f02a is the color applied?

Yes, it applied. In the Editor and in the frontend.

>Are classes that set these colors implemented and loaded on the frontend of the website e.g:".has-brown-background-color"?

Yes:
![screenshot_4](https://user-images.githubusercontent.com/9355398/53976979-5f8b0180-4108-11e9-8537-150262012bd5.png)

Source: https://baubeaver.de/interview-mit-dem-malermeister-patrick-legrand/

**Comment by SchneiderSam** [comment]
Or is the code wrong?

```
// Custom Colors Gutenberg
add_theme_support( 'editor-color-palette', array(
    array(
        'name' => __( 'BROWN', 'affiliatetheme-child' ),
        'slug' => 'brown',
        'color' => '#423733',
    ),
    array(
        'name' => __( 'LIGHT BROWN', 'affiliatetheme-child' ),
        'slug' => 'light-brown',
        'color' => '#877F7A',
    ),
    array(
        'name' => __( 'GREY50', 'affiliatetheme-child' ),
        'slug' => 'grey50',
        'color' => '#7F7F7F',
    ),
    array(
        'name' => __( 'GREY', 'affiliatetheme-child' ),
        'slug' => 'grey',
        'color' => '#E2E2E2',
    ),
	array(
        'name' => __( 'ORANGE', 'affiliatetheme-child' ),
        'slug' => 'orange',
        'color' => '#F2C42E',
    ),
	array(
        'name' => __( 'RED', 'affiliatetheme-child' ),
        'slug' => 'red',
        'color' => '#FD5A5C',
    ),
) );
```

**Comment by jorgefilipecosta** [comment]
Hi @SchneiderSam,
Based on your answer and on checking the images you provided, it looks like the color classes are not implemented on your theme styles.

Could you try adding the following to your theme styles:
```
.has-grey-background-color {
	background-color: #E2E2E2;
}
...
```

Themes are responsible for creating styles that represent the colors they need.
I think adding these styles will fix the problem.

Please let me know if this fixed the issue.

**Comment by SchneiderSam** [comment]
Okay, that works. So for each color I have to define the background as well as the text color. That makes sense, but it would also be nice to simplify the whole procedure.
