### ISSUE TITLE
List block: consider aligning list items with paragraphs

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#14098]
Right now, lists are intented rather agressively from other body content:

<img src="https://user-images.githubusercontent.com/376315/53363267-f3ecab80-3933-11e9-9dfc-5558d67237cd.png" width="400">

This can make it harder to read, since the flow of the text is interrupted. It can also mean that lists become hard to track and work with on small screens, especially when they're nested:

<img src="https://user-images.githubusercontent.com/376315/53364395-9e65ce00-3936-11e9-8740-4460e646b10f.png" width="200">

## Proposed solution

The typographically correct way to handle this would be to [hang the bullets outside of the text](https://markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2), so that all text shares a left alignment:

<img src="https://user-images.githubusercontent.com/376315/53363268-f3ecab80-3933-11e9-9199-014e75575c07.png" width="400">

If the negative margins there prove problematic (although with some cursory testing, I didn't run into any snafus), we could make do with decreasing the indentation somewhat instead:

<img src="https://user-images.githubusercontent.com/376315/53363265-f3ecab80-3933-11e9-8134-4eeb5e88842e.png" width="400">

This would bring things into closer alignment and clean it up on mobile a bit, without needing to be concerned with negative margins.

**Comment by kjellr** [comment]
I'd argue against a negative indent, as this is somewhat non-standard compared to other editors (Google Docs, etc.). I do agree that our current indentation for these seems like a little too much — I recommend we open a PR and adjust. Your alternative solution above seems like a good starting point to try out.
