### ISSUE TITLE
Separator block: consider setting background: transparent

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#14101]
Existing `<hr>` background styling (typically a background colour) is applied via the theme, which can create some unexpected behaviour. Consider setting background: transparent.

Issue made from block audit. Props @kjellr and @sarahmonster.

**Comment by draganescu** [comment]
Hi @karmatosed, inspecting a separator block in current Gutenberg shows `background-color: transparent !important;`. Does this mean this issue is solved?

**Comment by karmatosed** [comment]
It does! Let's close this up!
