### ISSUE TITLE
Options bar: add new button "Clear" that will clear the content of the post

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1411]
This definitely might be a super low priority or even an extension-territory, but it would be nice to a have a button, that on click will remove the content of the post, to be able to start from scratch.
Faster than removing one by one.

**Comment by mtias** [comment]
We have ctrl/command+A support to select all blocks, then you can delete them all at once:

![image](https://user-images.githubusercontent.com/548849/27489711-d3ee460c-583b-11e7-8681-0e4c20f210ba.png)

**Comment by slaFFik** [comment]
Ok, that works. I just didn't know about that.

**Comment by jasmussen** [comment]
Good question, and good that it was asked!

I think for now I'll close this ticket as resolved with the suggestions posted in the comments. But good to have if we need to revisit! Thanks.
