### ISSUE TITLE
Media blocks using the wrong icons in setup states

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#14111]
**Describe the bug**
The media blocks' setup states are using outdated icons. Instead of the new icons, they're using Dashicons.

I see this on the image, gallery, audio, video, file, and media & text blocks.

**To Reproduce**
1. Open the block library/inserter
2. Select any of the blocks mentioned above
3. Click on or tap the block
4. See that the block icon within the setup state is different from the icon in the block library, the toolbar, and the sidebar.

**Expected behavior**
The setup state should use the correct block icon.

**Screenshots**

![image](https://user-images.githubusercontent.com/2846578/53377086-b33e6380-392e-11e9-8534-ae255e08ee6e.png)

**Comment by chrisvanpatten** [comment]
I believe @ZebulanStanphill has a few tickets about this open :)

**Comment by melchoyce** [comment]
You're right! This was fixed in #11788. Closing :)
