### ISSUE TITLE
Pressing Arrow Down Button On Keyboard Make Caption Field Longer On Image Block

### ISSUE THREAD

**Issue by achmedislamic** [WordPress/gutenberg#14114]
**Describe the bug**
When you using Image Block, there is a caption field below the image. When you press the arrow down button on your keyboard, the image block becoming longer.

**To Reproduce**
1. Add or edit post using Gutenberg Editor
2. Insert image
3. Click the caption field
4. Press the arrow down button on your keyboard

**Expected behavior**
The cursor should go to the next block

**Screenshots**
![bug-caption-wordpress-gutenberg](https://user-images.githubusercontent.com/25688207/53412125-7b552000-3a03-11e9-9321-5b64b8135d1f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 October 2018 Update
 - Browser: Google Chrome
 - Version 72

**Additional context**
- Latest Wordpress 5.1
- Using PHP 7.3.2

**Comment by youknowriad** [comment]
@iseulde any idea about this. I feel I saw something related to this recently in one of your PRs.

**Comment by iseulde** [comment]
We've never had any logic for this in the image block I think. I'll have a look.

**Comment by iseulde** [comment]
What should the behaviour here be? Should we break out only when the caret is at the end and `enter` is pressed twice? Or should this only happen in the middle of the text?
