### ISSUE TITLE
Custom block preview on hover

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14117]
Let's say I have three slider blocks, and all of that have different layouts. What I want to do is I want to show the slider preview as an image when user hover on the block. Which will be helpful for the users to select the layout.

![Image of Yaktocat](https://i.postimg.cc/sfpVwSJy/071-BE3-E0-DD74-4234-83-D4-D7-D0-F317-CA7-C.png)

**Comment by youknowriad** [comment]
Another option would be a way to provide a set of "attributes" to use for the preview.

**Comment by ravishakya** [comment]
I can see only for reusable blocks the preview is enabled. It will be better if we can control the preview message.

**Comment by Bequiagal** [comment]
Has there been any advancement on this subject? 

I also really want to edit the preview image for each reusable block to give the site editors visual reference and not have to rely on the naming convention for these reusable blocks.

**Comment by youknowriad** [comment]
Yes, a first version of this should land with #17124
