### ISSUE TITLE
WP update broke pages

### ISSUE THREAD

**Issue by kweather9122** [WordPress/gutenberg#14126]
Recently I updated to WP 5.0.3.  Since it uses WPBakery as a default editor, I lost of my VC pages.  When I go to Dashboard > Pages and view the individual pages, WPBakery is installed and the pages are blank.  Obviously, the site pages aren't blank, but now how do I edit any of them if they are blank in WPBakery?  Also, two of my pages still have Classic Mode and Frontend Editor.  Why would they not convert to WPBakery with the WP update as well?

Why would WPBakery destroy all of my pages?  Doesn't it convert VC to WPBakery as pages instead of being blank?

**Comment by kweather9122** [comment]
WPBakery will not support because I got it with my theme, not a paid version.  I tried installing the classic editor but did not recover my classic done pages.  I am just going to work with WP Bakery for a while and see how it goes.







Kenneth B. Weatherford
Technical Writer Training LLC

Author, MS Word Styles and Other Tools
Co-Author, FrameMaker Structured Authoring (2017)
Adobe TechComm Partner

P: 405.603.7078 | C: 405.314.9559
kenneth.b.weatherford@techwritingcareer.com

 

    On Wednesday, February 27, 2019, 7:17:42 AM CST, Riad Benguella <notifications@github.com> wrote:  
 
 
I'm not sure I understand what you did here? Is it an issue with WPBakery plugin? you might want to reach out to them. There might be an incompatibility with some plugins.

Otherwise, if you want to stay with the classic editor experience in WP 5.0.3, you may want to install the classic editor plugin.

**Comment by bph** [comment]
Hi @kweather9122 -We had similar trouble with WPBakery / Visual Composer plugin. In the cases we didn't replace content out right,  we installed the [Classic Editor](https://wordpress.org/plugins/classic-editor/) for the sites and were able and resume working with the pages. 
After installation of the Classic Editor plugin, there are different settings available under _Dashboard > Settings > Writing_  and you can start using both on the same site. 

Maybe this process will also help you.

**Comment by kweather9122** [comment]
I tried setting for using WPBakery, Classic, and Gutenberg, but didn't work.



Kenneth B. Weatherford
Technical Writer Training LLC

Author, MS Word Styles and Other Tools
Co-Author, FrameMaker Structured Authoring (2017)
Adobe TechComm Partner

P: 405.603.7078 | C: 405.314.9559
kenneth.b.weatherford@techwritingcareer.com

 

    On Wednesday, February 27, 2019, 8:32:49 AM CST, Birgit Pauli-Haack <notifications@github.com> wrote:  
 
 
Hi @kweather9122 -We had similar trouble with WPBakery / Visual Composer plugin. In the cases we didn't replace content out right, we installed the Classic Editor for the sites and were able and resume working with the pages.
After installation of the Classic Editor plugin, there are different settings available under Dashboard > Settings > Writing and you can start using both on the same site.

Maybe this process will also help you.

**Comment by bph** [comment]
I think you best bet to figure this out would be to get in touch with WPBakery team and see if they can give you guidance how to best use it in a WordPress 5.1 world. This space is only for Gutenberg specific bug reporting and it seems this is a plugin issue more than a Gutenberg issue.
