### ISSUE TITLE
Errors when inserting inline image since Gutenberg 5.1

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#14123]
**Describe the bug**
Since https://github.com/WordPress/gutenberg/pull/13737, inserting an inline image has some issues.

**To Reproduce**
Issue 1: Insert an inline image at the beginning of a paragraph and directly click on the Apply icon without changing the width. It duplicates the image.

![error-duplicate](https://user-images.githubusercontent.com/44895380/53424469-90ba5200-39e3-11e9-9f99-a8f44b171ce7.gif)

Issue 2: Insert an inline image at the beginning of a paragraph, change the width and click on the Apply icon. It displays "This block has encountered an error and cannot be previewed."

![error-warning](https://user-images.githubusercontent.com/44895380/53424518-a29bf500-39e3-11e9-8bd7-0b32c0a1e84a.gif)

**Comment by youknowriad** [comment]
cc @iseulde

**Comment by iseulde** [comment]
This should be fixed by #13948.
