### ISSUE TITLE
Reusable blocks error Block has been deleted or is unavailable.

### ISSUE THREAD

**Issue by ezkitcabs** [WordPress/gutenberg#14127]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

Ok, I did all this and found some similar info on Github pages but did not find a solution that I could comprehend.

**Comment by ezkitcabs** [comment]
![image](https://user-images.githubusercontent.com/47403303/53445994-74181d00-39d7-11e9-979a-32752f366bee.png)
All of my reusable blocks look like this now.
The reusable blocks have images with links.
Only one reusable block "shows up"
![image](https://user-images.githubusercontent.com/47403303/53446192-f7d20980-39d7-11e9-8897-f192ac995970.png)
It contains a wp gallery of images, like the other blocks, but without links to pages, these images link to the media files.
![image](https://user-images.githubusercontent.com/47403303/53446482-b2faa280-39d8-11e9-9289-8448e786af65.png)
I can access the blocks here ^ but cannot figure out what to do with them, to fix the issues or the blocks showing as deleted on the pages.

OK, so this is in the editor, of course, on the live site, all the blocks still appear and function, but some are displaying with smaller thumbnails, and some display with no space between.
![image](https://user-images.githubusercontent.com/47403303/53446380-72028e00-39d8-11e9-97e8-f1e61418f09b.png)
This all happened, suddenly, this morning, I was adding a column in an existing reusable block on a page on my site, now everything is wacky like this.
What do I need to do?

**Comment by youknowriad** [comment]
I think the API endpoint call to fetch the reusable block list might be returning an error or not returning the correct value.

Can you check the returned response for this API call (`wp_block?_locale=user`) in the network tab of your browser's console.
Example in the screenshot here

<img width="963" alt="capture d ecran 2019-02-27 a 2 13 51 pm" src="https://user-images.githubusercontent.com/272444/53492797-03860480-3a9a-11e9-8c44-a5d2fd720770.png">

**Comment by youknowriad** [comment]
Let's reopen if there are steps to reproduce. Thanks

**Comment by Chandu4ever** [comment]
Hi

I'm also facing a similar issue with reusable blocks. Suddenly all resuable blocks showing with small sizes and I was unable to edit them from the post editor. 
error: Block has been deleted or is unavailable.
reusable block contains a table

please provide a solution, if anyone knows.
