### ISSUE TITLE
Photo Block has no "edit" button to re-open the media library modal

### ISSUE THREAD

**Issue by brentjett** [WordPress/gutenberg#1412]
When you insert a photo block, there is initially a button to open the media modal and select an image, but after having done so, there is no button to bring it back and select a different image.

![screen shot 2017-06-23 at 11 37 37 am](https://user-images.githubusercontent.com/1790660/27491596-aaec37ce-5808-11e7-8505-bf0919d2ab0d.png)

Worth noting is that the gallery block does have a button that brings up the edit gallery modal.

![screen shot 2017-06-23 at 11 38 19 am](https://user-images.githubusercontent.com/1790660/27491609-b54a68c6-5808-11e7-81c4-8ae0967c54f3.png)

**Comment by StaggerLeee** [comment]
I see the same.

Do we need now to use Ctrl + Left mouse click to select images for gallery ? Clicking only with mouse select only one image and remove marking of previous image.
