### ISSUE TITLE
Insert custom HTML in predefined PanelBody elements

### ISSUE THREAD

**Issue by nikitasinelnikov** [WordPress/gutenberg#14125]
Hi Gutenberg Team,

Could you provide some information how I can insert some custom content to your native Sidebar PanelBody. For example I have Categories List in my CPT and need to add link after this list

https://www.screencast.com/t/mqYWUPxWQTpE

Is there any ability to make this via Filters or Actions in Gutenberg. 

Best Regards and please let me know,
Thanks!

**Comment by youknowriad** [comment]
These panels are not extensible at the moment. We're tracking the extensibility of these panels here #13357
