### ISSUE TITLE
Undo removes pre-existing, already saved content

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1413]
Currently on master, to reproduce:.
edit a post that already has some pre-existing content, for example a simple title and text:

<img width="1003" alt="screen shot 2017-06-23 at 19 11 25" src="https://user-images.githubusercontent.com/1682452/27492947-5602e3e4-5848-11e7-98d9-87df2d9f13aa.png">

Add something to the title, and add something to the text:

<img width="1001" alt="screen shot 2017-06-23 at 19 11 52" src="https://user-images.githubusercontent.com/1682452/27492960-609b5124-5848-11e7-8199-91bd88a14a64.png">

Press the "Undo" button: all the paragraph text gets removed:

<img width="1001" alt="screen shot 2017-06-23 at 19 11 56" src="https://user-images.githubusercontent.com/1682452/27492987-70b21a98-5848-11e7-9a20-b649ebc991cd.png">

In this example. it should remove just ` Hello.`

**Comment by tg-ephox** [comment]
@afercia I can no longer replicate this on master, currently works as you expect

**Comment by afercia** [comment]
@tg-ephox true, can't reproduce any longer.
However, there's something that doesn't look right to me. In the same, simple, example above:
- I add the word "more" to the title
- I add the word "more" to the text block
- clicking undo:
  - with just one click, the "more" in the text gets deleted all together
  - at the second Undo click, the "e" in the title "more" gets deleted, and at the following clicks same: one letter at a time

**Comment by tg-ephox** [comment]
@afercia that's because currently the text block is wrapping TinyMCE and the block only gets the new content once TinyMCE loses focus . So all changes made within TinyMCE will be captured as a single change in regard to redo/undo.

**Comment by afercia** [comment]
@tg-ephox thanks, now I understand the technical reason behind this.

However, the more I test undo / redo, the more I'm worried about potential content loss and any sort of breakage in the users editing flow. 

I think the current behavior is confusing and it's also very different from the behavior in the classic editor. Probably a bit overlooked so far, but I feel this is one of the features that should be definitely improved.

**Comment by youknowriad** [comment]
Should this get closed by #4956

**Comment by aduth** [comment]
Undo has undergone significant changes lately. Specific issues should be addressed individually.

For the title "one character at a time", this is tracked at #4057
