### ISSUE TITLE
Attributes with type 'array' when updated affect all instances of the same block

### ISSUE THREAD

**Issue by djuric** [WordPress/gutenberg#14132]
Code like this works fine for 1 instance of the block in editor: 

```
/* EXTERNAL */
import _ from 'lodash';

/* WP */
const { registerBlockType } = wp.blocks;
import { TextControl } from '@wordpress/components';

registerBlockType('tblocks/cars', {
	title: 'Cars',
	category: 'common',
	icon: 'store',

	attributes: {
		cars: {
			type: 'array',
			default: [
				{
					id: 1,
					type: 'toyota',
					color: 'blue'
				},
				{
					id: 2,
					type: 'BMW',
					boja: 'black'
				}
			]
		}
	},

	edit: function(props) {
		const {
			attributes: { cars },
			setAttributes
		} = props;

		const handleNameChange = (name, id) => {
			const carList = [...cars];
			const index = _.findIndex(carList, { id: id });

			carList[index].name = name;
			setAttributes({ cars: carList });
		};

		return (
			<div>
				{cars.map(car => {
					return (
						<TextControl
							label={`Name ${car.id}`}
							value={car.name}
							onChange={name => handleNameChange(name, car.id)}
						/>
					);
				})}
			</div>
		);
	},

	save: function(props) {
		return null;
	}
});
```

However if I try to add another instance of the same block, values are duplicated and new input fields affect all of the copies together with input fields 

Am I updating attributes array incorrectly?

**Comment by youknowriad** [comment]
In this code

```
			carList[index].name = name;
```

You're mutating an existing object, in general when calling `setAttributes` the guidelines is to avoid mutations entirely.

This could be written

```js
const index = _.findIndex(carList, { id: id });
const newCar = { ...carList[index] };
const newCarList = [...cars];
newCarList[index] = newCar;
setAttributes({ cars: newCarList });
```

I hope this helps.

**Comment by Mr-Alexander** [comment]
> You're mutating an existing object, in general when calling `setAttributes` the guidelines is to avoid mutations entirely.

@youknowriad thanks for your help and pointing this out.

Are you able to explain this in more details, please? In particular, what is meant by mutation and what makes your workaround work.

**Comment by youknowriad** [comment]
Mutating means: editing a JavaScript object while keeping the same instance of the JS object. For performance reasons, applications based on "Redux" or similar tech (like Gutenberg) use "strict comparison" to check whether there was an update in data to "re render". If you "mutate" data instead of creating new objects, React (or Redux) won't know that there has been changes and won't re-render again causing stale data to be shown.
