### ISSUE TITLE
The classic block scrolls the to top after adding image or editing link

### ISSUE THREAD

**Issue by shindevijaykr** [WordPress/gutenberg#14134]
When we do any operation in an editor like adding an image at a particular point or editing a link, the mouse cursor focus shift to the top of the page making us scroll all over to again.

Attached video of the issue.

Wordpress 5.1 on Chrome latest browser, Windows 10 OS.

[Gutenberg cursor focus shift to top after adding image or editing links.zip](https://github.com/WordPress/gutenberg/files/2908610/Gutenberg.cursor.focus.shift.to.top.after.adding.image.or.editing.links.zip)

**Comment by youknowriad** [comment]
In my testing, the cursor don't move but yeah the block is scrolled to the top. And it concerns only the "classic block". Any particular reason you're using the classic block instead of converting your post to smaller blocks?

cc @iseulde @azaozz in case any of you have ideas, are aware about this bug.

**Comment by iseulde** [comment]
I thought we fixed this in #12415? Or is it just that it scrolls the caret moves out of view?

**Comment by youknowriad** [comment]
in my testing, if I type "arrow keys" right after, it works properly, but yeah the block had already scrolled to the top without touching the caret.

**Comment by iseulde** [comment]
Maybe we need to "scroll into view" after setting the caret back.

**Comment by glendaviesnz** [comment]
A temporary fix for this has been merged, but see @pento's comment for details about a fix needed in core for this - https://github.com/WordPress/gutenberg/pull/23544#issuecomment-651565212

**Comment by youknowriad** [comment]
Do we have a core trac ticket to reference here?

**Comment by kathrynwp** [comment]
I am no longer seeing this behaviour in the Classic block, with:

WordPress 6.0.1
No plugins active OR Gutenberg 13.6.0 active
Twenty Twenty-Two 1.2

I'm going to go ahead and close this out, but anyone's still experiencing the original issue, feel free to comment or reopen with additional details on how to replicate. Thanks!
