### ISSUE TITLE
Error with "postLockUtils undefined"

### ISSUE THREAD

**Issue by lotharthesavior** [WordPress/gutenberg#14141]
**Describe the bug**

After updating to the latest version of gutenberg I started to have a problem with a "white screen" at th block editor when the second user opens a document that is being edited. The error is ``postLockUtils is undefined``. This is the error being thrown with the ``npm run dev`` mode:

**To Reproduce**

1. Open a document
2. Open an incognito window and login with a different user
3. Open the same document (marked as being edited by another user)
4. You will get the white screen of death (the console shows this: ``postLockUtils is undefined``)

**Expected behavior**

The system should show the expected modal asking the user between take over the Post edition or go back to post list.

**Screenshots**

<img width="1676" alt="screen shot 2019-02-27 at 6 33 39 am" src="https://user-images.githubusercontent.com/1092909/53487915-d5cd9b00-3a5a-11e9-8662-502d58696eea.png">

**Desktop (please complete the following information):**

 - OS: maOS Mojave 10.14.13
 - Browsers: Firefox (65.0.1 (64-bit)), Firefox Developer Edition (66.0b10 (64-bit)), Chrome (72.0.3626.119 (Official Build) (64-bit))
 - Version: mentioned following the browsers names.

**Smartphone (please complete the following information):**
...

**Additional context**
- Updated with the commit 1ed999561b4b6c6d0f0a520e4ff0e302af14d09e (from Feb 27 4am EST)

**Comment by lotharthesavior** [comment]
I noticed that if I, just for testing, take out the ``<PostLockedModal />`` at the file **gutenberg/packages/edit-post/src/editor.js:69**, and build again, it opens the block editor with the post without the blocker functionality. I would say that there is a missing ``prop`` in this call? 

I'm saying this because I saw this: ``const { autosave, updatePostLock } = this.props;`` at the file **gutenberg/packages/editor/src/components/post-locked-modal/index.js:89**

**Comment by youknowriad** [comment]
Is this happening on master? Can you test in this branch https://github.com/WordPress/gutenberg/pull/14082 it can have an impact there?

**Comment by lotharthesavior** [comment]
Thanks for your comment here, I'll test in a few moments. I saw earlier that this call might not be the last "invocation" of that object, since it also goes through an action...  Because of that, It might be due to a missing dependency. I'll check this branch and let you know.

**Comment by lotharthesavior** [comment]
@youknowriad indeed, with that branch the problem doesn't happen, do you know what might be causing this?

**Comment by youknowriad** [comment]
I have an idea yes, recently we changed the editor settings location and they might be initialized a little bit too late in master causing this issue. In this PR, the settings are restored to their previous location.

**Comment by lotharthesavior** [comment]
Am I suppose to consider this ticket solved by that PR?

**Comment by youknowriad** [comment]
yes, when it's merged :)
