### ISSUE TITLE
Allow Paragraph-Pullquote Conversion/Transformation

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#14159]
**Is your feature request related to a problem? Please describe.**
I expected that I could convert a Paragraph to a Pullquote. I especially expect this because I can convert a pullquote to a blockquote and a blockquote to a paragraph.

**Describe the solution you'd like**
Standardize the block-type conversions. If I can convert a paragraph to a blockquote and vice-versa, I'd expect both block types to be convertible to the same list of blocks. However, that is not the case.

**Comment by joweber123** [comment]
Reported again here 2717061-zen
