### ISSUE TITLE
Expose `react.lazy` and `react.Suspense` in `@wordpress/element`

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#14155]
We're using the `react` external, but it'd be nice if this was exported on `@wordpress/element`. We're using this to async load some components ( outside of the block editor ).

**Comment by youknowriad** [comment]
Not against the idea but both these two components rely on the fact that the public URL of your website is known before hand and hardcoded on your bundler somehow. Curious how you plan to use these in the context of a WordPress plugin..

**Comment by TimothyBJacobs** [comment]
We're setting `__webpack_public_path__` at runtime.

https://webpack.js.org/guides/public-path/#on-the-fly

**Comment by youknowriad** [comment]
Oh interesting, I was missing this, thanks.
