### ISSUE TITLE
Inserter search field doesn't show highlighting of text

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14158]
**Describe the bug**
After typing some text in the search field of the inserter, I want to select the text and delete it. When I try to highlight all the text by way of the mouse or the keyboard, it doesn't show as highlighted.

![highlight](https://user-images.githubusercontent.com/617986/53530443-b6f3f680-3aa4-11e9-89a6-f5edb64a1768.gif)

**To Reproduce**
1. In Firefox, on a page using Gutenberg, open the Inserter.
2. Write some text in the search field.
3. Try to highlight the text.

**Expected behavior**
I expect the text to highlight similarly to how text would highlight when I select it elsewhere.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser FF
 - Version 65.0.1
- Gutenberg version 5.1.1

**Comment by Jackie6** [comment]
Hi @mapk I cannot reproduce the bug. I can highlight and delete the text in the search filed of the inserter.
![highlight-text](https://user-images.githubusercontent.com/24849874/54851524-92b0c180-4cc0-11e9-9613-69eb34a3b55d.gif)

**Comment by mapk** [comment]
Thanks for testing, @Jackie6. It must have been remedied by something recently. It works just fine for me now. I'm closing the issue.
