### ISSUE TITLE
RichText.value, discrepancy between default and empty (after deletion)

### ISSUE THREAD

**Issue by berengerzyla** [WordPress/gutenberg#14160]
I am building a custom block which contains a simple RichText.
A visual aid helps knowing if content has been type in, based in the value given by the RichText.

```
<RichText
  multiline="p"
  inlineToolbar="true"
  value={ description }
  placeholder={ __( 'Description', 'myi18n' ) }
  onChange={ ( value ) => { setAttributes( { description: value } ) }
  id={inputId}
/>
```

Test scenario (from the GIF):
- STEP1: Inserting the block, default is empty. The aid shows "Content missing" (ie. `RichText.content === ''`)
- STEP2: Saving, reopening. The aid shows "Content missing" (ie. `RichText.content === ''`). The saved output was an `[empty string]`.
- STEP3: Typing in content. The aid shows "Content" (green) (ie. `RichText.content !== ''`, which is actually `=== '<p>[TYPED IN CONTENT]</p>'`).
- STEP4: Deleting all content. The aid shows "Content" (green) (ie. `RichText.content !== ''`, which is actually `=== '<p></p>'`). Not the initial state.

**Expected behavior**
An empty RichText should return the same value wether it was just added or had its content removed.\

![gutenberg 1](https://user-images.githubusercontent.com/597743/53534608-98562580-3acd-11e9-8a4c-88b18f9627a3.gif)

**Desktop (please complete the following information):**
 - OS: OS X 10.14.3
 - Browser: Chrome
 - Version: 72

 - Gutenberg: 5.1.1

Thank you!

**Comment by iseulde** [comment]
Thanks for the report. This is a known thing. I agree that it should be changed at some point to return an empty string for more simple checks, but at the moment, you should use `RichText.isEmpty` to check for emptiness. See #10763 for more information. Let's use that one as a tracking issue.
