### ISSUE TITLE
Autosave meta block

### ISSUE THREAD

**Issue by pilou** [WordPress/gutenberg#14167]
**Describe the bug**
Autosave doesn't have `meta` in request playload, but publising does.

**To Reproduce**
1. Create a meta block like described here: https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/metabox/meta-block-3-add/
2. Write title, post content, content in the meta block 
3. Wait for autosave
4. See error, the request body does not contain the meta block content 

**Expected behavior**
The normal save does send the meta blocks, so the autosave should too.

**Screenshots**
https://youtu.be/Cbx8_pNPrvE

**Desktop (please complete the following information):**
 - OS: Max
 - Browser Chore

**Additional context**
- Tested on vanilla WP 5.1.0

**Comment by Soean** [comment]
Saving meta in revisions is not possible in WP see https://github.com/WordPress/gutenberg/issues/7767 and https://core.trac.wordpress.org/ticket/20299

**Comment by youknowriad** [comment]
Let's close in favor of the core ticket.
