### ISSUE TITLE
Edit old Post will not Save or Publish

### ISSUE THREAD

**Issue by tonyzeoli** [WordPress/gutenberg#1416]
I am running a WordPress multisite network and have installed the plugin on one test site (netmix.co) in the network.

I am trying to edit the Post Title for a post that was there before I installed Gutenberg, and I added a few lines of text in the next content blocks, but the post will not save when click on the save link at the top left of the editor. Not will the post Publish.

II do get the warning about the beta and that it won't display properly in the theme once I click on Publish, but it still doesn't save or publish. Could possibly conflict with plugins, I don't know.

**Comment by karmatosed** [comment]
I can confirm that editing an old post doesn't work, its not just mulisite. To recreate:

- Go to an old post
- Click 'Gutenberg' to edit

**Comment by youknowriad** [comment]
It works for me in master, could you confirm that, please? Thanks

**Comment by karmatosed** [comment]
I think this may be a care of plugin v master. I can recreate in the plugin from repo.

**Comment by youknowriad** [comment]
The `0.3` has been released if you experience this again, please feel free to reopen.
