### ISSUE TITLE
Video Block: Editing the video removes it from the editor

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#14172]
**Describe the bug**
When a video block is added, and when one clicks on the `Edit` icon on the block, the video disappears from the editor. Refreshing the page brings it back though.

**To Reproduce**

- Add a video block
- Add a video on it. I drag-dropped the file
- Click on the `Edit` pencil icon available at the top

**Expected behavior**

I am not entirely sure what's expected here, but is a video editing tool expected to popup? Like this one that appears when using the classic-editor?

![screenshot 2019-02-28 at 22 32 46](https://user-images.githubusercontent.com/18581859/53584095-e429cd00-3ba8-11e9-8a64-74003d331dae.png)

**What happens instead**

The block just disappears from the editor view. Refreshing the page shows that it's still available.

<img width="913" alt="screenshot 2019-02-28 at 22 00 17" src="https://user-images.githubusercontent.com/18581859/53584166-0de2f400-3ba9-11e9-8aec-72f2ef2b79d7.png">

The block buttons to upload new video files can be seen again.

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOS 10.14.2 - Mac OS Mojave 
 - Browser: Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by Soean** [comment]
Thanks for your feedback. This is the expected behavior for now. We are working on additional features like[ alternate file formats and subtitles](https://github.com/WordPress/gutenberg/issues/9457#issuecomment-456201572) at the moment. This will change this button.

**Comment by Soean** [comment]
We now use the `MediaReplaceFlow` component in all media related blocks. See #19162
