### ISSUE TITLE
Audio block: in posts/page editor m4a trigger security message, works find in Media

### ISSUE THREAD

**Issue by caimin-j** [WordPress/gutenberg#14174]
**Describe the bug**
Uploading an .m4a file using the Audio block in the post/page editor triggers a _Sorry, this file type is not permitted for security reasons error_, but the same file can be uploaded without any warning in Media.

This is the case in both Calypso and WP Admin.

**To Reproduce**

1. In the page/posts editor add an Audio block.
2. Click _Upload_ and select a .m4a file.
3. Observe the security message.
4. Go to Media
5. Cick Add New
6. Select a .m4a file
7. Notice the lack of a security warning.

**Expected behavior**
That there's a global consistency about whether .m4a files are permitted or not.

**Screenshots**

Calypso post/page editor: 
<img width="637" alt="screenshot 2019-02-28 at 18 01 01" src="https://user-images.githubusercontent.com/37620825/53587748-1cb6b000-3b83-11e9-8443-516d33fa90fc.png">

Calypso Media, successful upload:
<img width="156" alt="screenshot 2019-02-28 at 18 03 55" src="https://user-images.githubusercontent.com/37620825/53587843-5091d580-3b83-11e9-9849-4c7dee8ccf6a.png">

WP Admin page editor:
<img width="723" alt="screenshot 2019-02-28 at 18 05 17" src="https://user-images.githubusercontent.com/37620825/53587904-7c14c000-3b83-11e9-97a0-b721a61a445c.png">

WP Admin Media, successful upload:

<img width="172" alt="screenshot 2019-02-28 at 18 05 33" src="https://user-images.githubusercontent.com/37620825/53587940-92228080-3b83-11e9-8333-6383fd4ba396.png">

**Comment by Soean** [comment]
Thanks for reporting this issue. 
This problem is already known and tracked in #9028, so I am closing this one.
