### ISSUE TITLE
Video Block: Doesn't appear on frontend until autoplay value is chosen once

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#14171]
**Describe the bug**
When a video block is added and when a video is added on it, published/previewed, the video doesn't appear on the frontend. It shows a blank, black screen instead.

**To Reproduce**

- Add a video block
- Add a video on it
- Preview or publish the post

**Expected behavior**
The video appears, and shows a thumbnail. Can be played.

**What happens instead**

Unable to see the thumbnail. Unable to play the video either.

<img width="892" alt="screenshot 2019-02-28 at 22 27 50" src="https://user-images.githubusercontent.com/18581859/53584622-040dc080-3baa-11e9-87ae-2686614a5472.png">

**Desktop (please complete the following information):**

 - Device: MacBook Pro
 - OS: macOS 10.14.2 - Mac OS Mojave 
 - Browser: Google Chrome Version 72.0.3626.109 (Official Build) (64-bit) 

**Additional context**

Going back to the editor once, setting the video block's `Autoplay` setting to 1 (enable), and coming back to the post's frontend, it can be seen to be fine. 

Making a guess here: Is this not appearing on the frontend, because the video is being processed in some way? If so, my feeling is that it would be helpful to indicate that on the frontend - something like 'video is being processed, please wait'

[My file](https://cloudup.com/cIrv_J5YdoG) is small, but I have been able to reproduce this on multiple WordPress environments and after over 10 minutes, the video is not seen as expected.

**Comment by Soean** [comment]
I can't reproduce the problem. I tested your linked file on WordPress 5.1; twenty nineteen theme on Mac/Chrome. I see the preview on backend and frontend.
![bildschirmfoto 2019-03-03 um 11 47 29](https://user-images.githubusercontent.com/695201/53694127-78af4d80-3daa-11e9-970a-215e4b0c22c4.png)

What are the preload setting (in the sidebar) of the video?

**Comment by arunsathiya** [comment]
Thanks for taking a look! 

Further research indicates that there is no video/thumbnail show during the time the video is being uploaded to the site. Once the upload finished, I refreshed the post preview, and I was able to see the video thumbnail just fine.

Since it seems to be working as expected, I shall close this report. 👍🏽
