### ISSUE TITLE
HTML special characters in [code] shortcode block are escaped if a classic page is edited.

### ISSUE THREAD

**Issue by LuckyResistor** [WordPress/gutenberg#14186]
**Describe the bug**
If a classic page is opened in the Gutenberg editor, HTML special characters are escaped in e.g. `[code][/code]` blocks. This is done every time, opening the same page multiple times makes the code worse. This escaping will make the code render incorrectly and prevents a proper conversion to blocks at a later point.

**To Reproduce**
1. Create a page with the classic editor, containing a code block, using the "SyntaxHighlighter Evolved" plug-in:
```
[code]
int a = 1 << 5;
[/code]
```
2. Save this page.
3. Open this page with the Gutenberg editor.
4. The editor adds changes to the classic block which make rendering impossible:
- The editor encloses the `[code]` block with a `<pre>` tag.
- All HTML special characters are escaped *multiple times*
```
<pre>[code]
int a = 1 &amp;lt;&amp;lt; 5;
[/code]</pre>
```
- This prevents a proper conversion to blocks.

**Expected behavior**
- The `[code]` block should be kept untouched in the classic block.
- This would allow the page render correctly. 

**Screenshots**
![code](https://user-images.githubusercontent.com/9452552/53632995-96e44480-3c16-11e9-94f6-98d19b6f2a75.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 12.0.3

**Additional context**
- Gutenberg 5.1.1

**Comment by noisysocks** [comment]
I was able to reproduce this bug in WordPress `trunk` but not in Gutenberg `master`. Closing as fixed.
