### ISSUE TITLE
Conversion of syntax highlighting short codes like `[code]` into "Code" block.

### ISSUE THREAD

**Issue by LuckyResistor** [WordPress/gutenberg#14187]
**Describe the bug**
In the current version of Gutenberg, conversion of classic pages to blocks fails for syntax highlighting blocks with short codes like `[code]`, etc. from the widely used "SyntaxHighlighter" plugins. 

I am aware, part of this issue is based on the functionality of a plug-in. As I understand, the block conversion is done in the editor itself. 

**To Reproduce**
1. Open a classic page which contains source code with a `[code]...[/code]` block.
2. Select "Convert to Blocks"
3. The conversion is correct for most parts, expect for the `[code]` blocks:
- The `[code]...[/code]` blocks are converted into a preformatted block, not into a "Code" or "Syntax Highlighter" block.
- The code is HTML escaced, as described in issue #14186 .
- The shortcode elements are included in the block - but they should be the block.

**Expected behavior**
- The classic syntax highlighting shortcode blocks like `[code]` should be converted into a "Syntax Highlighting" block.
- Parameters like `language`, `line number` existing in the Syntax Highlighter block.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 12.0.3

**Additional context**
Gutenberg: 5.1.1

**Comment by swissspidy** [comment]
It's up to plugins to support blocks and conversion from shortcodes to custom blocks.

Gutenberg can't know about all the existing shortcodes out there and their behavior.

**Comment by LuckyResistor** [comment]
So, if the plugin which provides the [code] shortcode for the classic editor is responsible for the conversion to the block. Can you point me to the API the plug-in needs to use for this task?

I will further investigate and put the issue into the issue list of the plugin in this case.

**Comment by swissspidy** [comment]
Block transforms can be defined as part of block registration. Check out the handbook for detailed information: https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#transforms-optional

It contains an example of how to transform from a shortcode to a block, which is what you'd need in your case.

**Comment by nosolosw** [comment]
We've landed an improved version of the [Block Transforms API docs](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-transforms.md) that can be useful for this.

Note that I've pointed to GitHub and not the Handbook. We've locked the Handbook content to the last WordPress release and we're still figuring out [how to backport this kind of doc changes](https://github.com/WordPress/gutenberg/issues/21858).

Closing this as non-actionable for this repo.
