### ISSUE TITLE
Array of internal blocks becomes NULL when Re Edit

### ISSUE THREAD

**Issue by kmix-39** [WordPress/gutenberg#14185]
**Describe the bug**

If you refer to innerblocks in save as follows, it breaks.

```

save( props ) {
  const { innerBlocks } = props;
  ...
  return (
    { innerBlocks.length }
    ...
    <InnerBlocks.Content />
  );
},

```

**To Reproduce**

1. setting innerblocks in block.
2. post
3. edit
4. bloken block and return  innerBlocks.length = 0 ?

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser safari

**Additional context**
- Gutenberg version 5.1.1

**Comment by noisysocks** [comment]
Hey @kmix-39! Inner blocks may only be accessed using the [`<InnerBlocks />` or `<InnerBlocks.Content />` APIs](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks) that Gutenberg exposes. The `innerBlocks` array is an implementation detail and not passed to blocks. 

What are you trying to achieve? There may be an alternative approach.

Closing this as answered, but feel free to reply and keep the conversation going.
