### ISSUE TITLE
I can't embed instagram post in Gutenberg editor

### ISSUE THREAD

**Issue by sandymakruf** [WordPress/gutenberg#14181]
Hi, 
When embedding Instagram it says “Sorry, we could not embed that content.”
Why is that?

**Comment by swissspidy** [comment]
Can you share the URL here to the Instagram post you tried embedding? Is it perhaps a post of a private account?

**Comment by sandymakruf** [comment]
Oh i try in other website just normal.. I think my website have a problem..
