### ISSUE TITLE
Articles about Gutenberg

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1419]
I came across a mention of Gutenberg at the Advanced WordPress Facebook group and wanted to find a good way of sharing it. So I decided on creating this issue in regards to articles we came across that would be good to collect and study closer. As there are a lot of feedback from various people.

https://www.facebook.com/groups/advancedwp/permalink/1539270842801791/
(I found the below articles mentioned in the above link.)

https://www.mattcromwell.com/gutenberg-first-impressions/
http://www.wp-munich.com/first-look-gutenberg-wordpress/
http://chrislema.com/misunderstanding-goal-gutenberg-writing-experience/
https://www.wpwatercooler.com/video/ep238-future-wordpress-gutenberg/

Updated with links mentioned below and found elsewhere:
http://adrianroselli.com/2017/06/first-reactions-to-gutenberg.html
https://daily.jorb.in/2017/06/random-thoughts-on-gutenberg/
https://kinsta.com/blog/gutenberg-wordpress-editor/
https://wplift.com/gutenberg-editor-first-look
http://gschoppe.com/wordpress/improving-wordpress/improving-wordpress-pt-4-where-project-gutenberg-lost-me-open-letter-to-core/
https://mrwweb.com/first-reactions-gutenberg-future-of-wordpress/
https://www.customerservant.com/gutenberg-screen-reader-initial-thoughts-reactions/
https://wptavern.com/tag/gutenberg
https://joost.blog/gutenberg-and-yoast-seo/
http://wordimpress.com/gutenberg-mean-plugin-authors/
https://briancoords.com/blog/gutenberg-the-obligatory-review/
https://halfelf.org/2017/post-written-gutenberg/

[Gutenberg and why WordPress may have a marketing problem](https://www.mhthemes.com/blog/gutenberg-wordpress-marketing-problem/) 
26 June, 2017 - by MHThemes

[Project Gutenberg: Medium like editing experience coming to WordPress](http://freshvanroot.com/blog/2017/project-gutenberg-medium-like-editing-experience-coming-to-wordpress/)
27 June, 2017

[First Reactions to Gutenberg](http://adrianroselli.com/2017/06/first-reactions-to-gutenberg.html)
27 June, 2017 - By Adrian Roselli

[First Reactions to Gutenberg, the Future of WordPress](https://mrwweb.com/first-reactions-gutenberg-future-of-wordpress/)
27 June, 2017 - By Mark Root-Wiley

[Questions & concerns from my first impression of the WordPress Gutenberg editor](https://torquemag.io/2017/06/questions-concerns-first-impression-wordpress-gutenberg-editor/)
29 June, 2017 - by Josh Pollock

[Gutenberg: The Obligatory Review](https://www.briancoords.com/blog/gutenberg-the-obligatory-review/)
29 June, 2017 - By Brian Coords

[What Does Gutenberg Mean for Plugin Authors?](http://wordimpress.com/gutenberg-mean-plugin-authors/)
30 June, 2017 - By Matt Cromwell

[This Post Was Written on Gutenberg](https://halfelf.org/2017/post-written-gutenberg/)
30 JUNE, 2017 - By Mika Epstein

[Gutenberg Contributors Explore Adding Drag-and-Drop and Multi-Column Support for Blocks](https://wptavern.com/gutenberg-contributors-explore-adding-drag-and-drop-and-multi-column-support-for-blocks/amp)
1 July, 2017 - by Sarah Gooding

[WordPress Gutenberg Design Facelift](https://titan.as/wordpress-gutenberg-design-facelift-idea/) 
3 July, 2017 - by Titanas 

[Cloudways Tests Gutenberg — The Future WordPress Native Editor ](https://www.cloudways.com/blog/gutenberg-wordpress-editor-test-by-cloudways/amp/) 
5 July, 2017 - by Saud Razzak 

"Why Gutenberg? Because Everyone Loves Page Builders"
5 July, 2017 By Steve Burge
https://www.ostraining.com/blog/news/pagebuilders/

Gutenberg Editor Review: Please Don’t Include This in WordPress Core
6 July, 2017 By Brenda Barron
https://premium.wpmudev.org/blog/gutenberg-editor-wordpress/

“Accessibility testing WordPress Gutenberg – a first look”
7 July, 2017 By Claire Brotherton
https://www.abrightclearweb.com/accessibility-testing-wordpress-gutenberg-first-look/

"Introducing Gutenberg Boilerplate For Third Party Custom Blocks!"
15 July, 2017 By Ahmad Awais
https://ahmadawais.com/gutenberg-boilerplate/

"Do We Really Even Need Gutenberg?"
26 Jul, 2017 by Richard Ginn
https://sunflowerchildthemes.com/really-even-need-gutenberg/

"Gutenberg and the future of Meta Box"
10 August, 2017 by Anh Tranon.
https://metabox.io/gutenberg-and-meta-box/

"Five Ways I’d Like To Be Proven Wrong About Gutenberg"
10 August, 2017 by Josh Pollock.
https://calderaforms.com/2017/08/gutenberg-wordpress-concerns-five/

"Update on Gutenberg Meta Box Drama"
11 August , 2017 by Fred Meyer.
https://wpshout.com/links/update-gutenberg-meta-box-drama/

"Gutenberg and Publishers: unconference notes from WordCamp for Publishers"
18 August, 2017 by Aaron Jorbin.
https://daily.jorb.in/2017/08/gutenberg-and-publishers-unconference-notes-from-wordcamp-for-publishers/

"How Gutenberg Will Shape the Future of WordPress"
18 August, 2017 by Morten Rand-Hendriksen.
https://www.linkedin.com/pulse/gutenberg-morten-rand-hendriksen

WPTavern writes about Mortens article. -Check out the comments.-
21 august, 2017 by Jeff Chandler.
https://wptavern.com/morten-rand-hendriksen-on-what-gutenberg-means-for-the-future-of-wordpress

-----------

This is a site that mentions various Gutenberg news:
WordPress Gutenberg Editor - Resources & Posts
https://storify.com/bph/wordpress-gutenberg-early-comments

"We Called it Gutenberg for a Reason."
27 August, 2017 by Matt Mullenweg.
https://ma.tt/2017/08/we-called-it-gutenberg-for-a-reason/

**Comment by samikeijonen** [comment]
Here is one from Amanda, she's a screen reader user: [Gutenberg With A Screen Reader: Initial Thoughts And Reactions](https://www.customerservant.com/gutenberg-screen-reader-initial-thoughts-reactions/).

**Comment by samikeijonen** [comment]
@jasmussen Would it be a good idea to write an article that would answer (or at least try to answer) to most common questions what have been done and what will be done?

These topics comes to my mind:

- Ultimate goal of the Gutenberg
- How the data is saved and why. Can developers decide where they want to save the data from the blocks and which format.
- How old metaboxes (PHP) will work in the editor and in the front-end
- How would you build new metaboxes using JS
- Is there going to be column blocks (2-4 columns)
- Is there going to be nested blocks
- How front-end styling and themes interact. For example full width image. As a theme author I'd be responsible what full width image should look like in front end, or does my theme even support that.
- Does Guteberg involve editing posts/pages in the front-end
- How accessibility have been taken care of
- Is there WordPress theme for showcasing what you can do with the Gutenberg. Plans for Twenty 18 theme using the Gutenberg. 
- Is there documentation how you add your own blocks, or change the default ones
- Which are the parts you already know that's going to break backwards compatibility

**Comment by jasmussen** [comment]
I think that makes total sense, and would be a great FAQ for people concerned with the ongoing work. 

Part of such an FAQ/article should be simply restating the kickoff goal which I've had to repeat a number of times already, as it quite well encapsulates the ultimate goal. From https://make.wordpress.org/core/2017/01/04/focus-tech-and-design-leads/: 

> The editor will endeavour to create a new page and post building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML, or “mystery meat” embed discovery.

Key take-aways from parsing that paragraph:

- "rich posts". The key take-away. Boldface underline. 
- blocks as a unified concept for the evolution of shortcodes, custom HTML snippets, embeds, and shortcodes
- solving the "mystery meat" embed discovery problem, where you paste a URL on a new line, press enter, and hope it works. Also related: surfacing the fact that WordPress supports 30+ embeds out of the box, so you don't have to search for plugins to embed "Issuu" when that's already supported

**Comment by jasmussen** [comment]
In #1434 I took a first stab at some design principles for Gutenberg. This doesn't directly solve the issue suggested here, but it has some of the answers.

**Comment by afercia** [comment]
Adding to the collection... :)

First Reactions to Gutenberg
Adrian Roselli - June 27, 2017
http://adrianroselli.com/2017/06/first-reactions-to-gutenberg.html

**Comment by samikeijonen** [comment]
Also [First Reactions to Gutenberg, the Future of WordPress](https://mrwweb.com/first-reactions-gutenberg-future-of-wordpress/) by Mark Root-Wiley.

**Comment by jasmussen** [comment]
Lots of good articles.

It feels like a large amount of the issues reported revolve around:

- Pluggable areas, particularly metaboxes, tracked in #1352 
- WordPress release cadence, and anxiety that this will get merged into WordPress 5.0 without being _ready_
- Concern that accessibility aspects are being de-emphasized, and won't be addressed before merge (largely tracked in https://github.com/WordPress/gutenberg/labels/Accessibility)

I understand every concern here. I've shared those concerns in some way or other for the past 6 months. And while I can proclaim again that these are important issues that are not being ignored, I suspect the only way to alleviate these concerns is _to continue to address them_. At some point, I am confident, these concerns _will be addressed_. But absent a time machine all we can do is march onwards, and keep building. 

My personal goal isn't to destroy accessibility, or to create an editor that people want to disable. This may sound obvious at the face of it, but in context of some of the concerns it seems worth actually stating. My goal is to build an editor that works for everyone, helps enable people to author richer posts with less effort, and is built on a foundation that the webdesigners growing up today are excited to build, improve, and contribute to.

**Comment by afercia** [comment]
> all we can do is march onwards, and keep building

Agree 100% and that's because I'm trying to code _something_ and make it better instead of just bla bla 🙂  Also, version 1 is just version 1.

**Comment by jasmussen** [comment]
> Agree 100% and that's because I'm trying to code something and make it better instead of just bla bla 🙂 Also, version 1 is just version 1.

🎯

**Comment by mrwweb** [comment]
Might I suggest a FAQ become a major priority for this project? I think it really needs to be out by the time a 0.3.0 release comes out.

Even as someone who has tried to follow this project closely, I feel in the dark on some pretty basic questions. @samikeijonen's list is excellent. Particular +1s go to meta boxes, conversion from the old editor, and theme styling. It's really awkward writing a review at this point (although I think is important to do) when I don't know what basic issues I can ignore because they're coming and which issues are terrifying and deserve alarm bells right now. The alarm bells are in hopes that things get caught now when they're addressable. 

Related to the above, I can't find the comment I saw before, but so many questions are about existing features of the current editor. Things like:

- `editor-style.css`
- meta boxes
- markdown
- shortcodes
- the `mce buttons_*` filters

Has there been any comprehensive list made of current ways to customize the editor, common usages, and mapped equivalents to Gutenberg (along with issue #s?)? This would be relieve a lot of developer worries _and_ make sure the project doesn't overlook common types of customizations the editor needs to support.

> WordPress release cadence, and **_anxiety_**

As Adrian Roselli's article gets at, I rely on the current editor as a key tool for my client websites. Being able to support them on it in the future is a big concern. If I can't easily rebuild existing features, I'm going to have a lot of really unhappy clients. I feel like I owe them as much of a heads up as possible about coming costs (many need to budget up to a year ahead for major work), but the lack of basic feature parity questions has made me hesitant to say anything yet.

> My personal goal isn't to destroy accessibility, or to create an editor that people want to disable.

Totally believe that. In fact, I'm sure you want to make an editor that's accessible. I think my primary concern was simply that it feels like _a lot_ of work has been done already and accessibility retrofitting is never as good as accessibility from the start. I may be misreading things—that's absolutely the danger of weighing in on a project at this phase and I'm trying to be careful—but I hope that at least clarifies the thinking.

**Comment by androb** [comment]
From the TinyMCE team's perspective I'd like to see any FAQ address it's role in Gutenberg and WordPress in general going forward. To the extent that is known right now, of course.

**Comment by androb** [comment]
http://wordimpress.com/gutenberg-mean-plugin-authors/

**Comment by androb** [comment]
https://torquemag.io/2017/06/questions-concerns-first-impression-wordpress-gutenberg-editor/

**Comment by mrwweb** [comment]
Has some good high-level thoughts: https://briancoords.com/blog/gutenberg-the-obligatory-review/

**Comment by androb** [comment]
from Mika: https://halfelf.org/2017/post-written-gutenberg/

**Comment by aardrian** [comment]
“Accessibility testing WordPress Gutenberg – a first look”
July 7, 2017 By Claire Brotherton
https://www.abrightclearweb.com/accessibility-testing-wordpress-gutenberg-first-look/

**Comment by afercia** [comment]
Gutenberg Editor Review: Please Don’t Include This in WordPress Core
July 6, 2017 By Brenda Barron
https://premium.wpmudev.org/blog/gutenberg-editor-wordpress/

**Comment by paaljoachim** [comment]
"Why Gutenberg? Because Everyone Loves Page Builders"
July 5, 2017 By Steve Burge
https://www.ostraining.com/blog/news/pagebuilders/

**Comment by paaljoachim** [comment]
"Introducing Gutenberg Boilerplate For Third Party Custom Blocks!"
July 15, 2017 By Ahmad Awais
https://ahmadawais.com/gutenberg-boilerplate/

**Comment by westonruter** [comment]
“Gutenberg, Shortcodes, Shortcake, and Metaboxes”
July 15, 2917 by Davis Shaver
https://davisshaver.com/2017/07/15/playing-with-gutenberg-for-the-first-time/

**Comment by felixarntz** [comment]
"Thoughts on Gutenberg"
July 9, 2017 by Felix Arntz
https://leaves-and-love.net/blog/thoughts-on-gutenberg/

:)

**Comment by georgeh** [comment]
"Do We Really Even Need Gutenberg?"
Jul 26, 2017 by Richard Ginn
https://sunflowerchildthemes.com/really-even-need-gutenberg/

**Comment by paaljoachim** [comment]
"Gutenberg and the future of Meta Box"
10 August, 2017 by Anh Tranon.
https://metabox.io/gutenberg-and-meta-box/

**Comment by bph** [comment]
Right after WordCamp Europe, I started this Storify collecting Resources, links and blog posts. 
https://storify.com/bph/wordpress-gutenberg-early-comments

**Comment by paaljoachim** [comment]
"Gutenberg and Publishers: unconference notes from WordCamp for Publishers"
18 August, 2017 by Aaron Jorbin.
https://daily.jorb.in/2017/08/gutenberg-and-publishers-unconference-notes-from-wordcamp-for-publishers/

**Comment by paaljoachim** [comment]
"How Gutenberg Will Shape the Future of WordPress"
18 August, 2017 by Morten Rand-Hendriksen.
https://www.linkedin.com/pulse/gutenberg-morten-rand-hendriksen

**Comment by paaljoachim** [comment]
"Update on Gutenberg Meta Box Drama"
11 August , 2017 by Fred Meyer.
https://wpshout.com/links/update-gutenberg-meta-box-drama/

**Comment by paaljoachim** [comment]
"Five Ways I’d Like To Be Proven Wrong About Gutenberg"
10 August, 2017 by Josh Pollock.
https://calderaforms.com/2017/08/gutenberg-wordpress-concerns-five/

**Comment by paaljoachim** [comment]
NB! I have also added a few more articles to the first post in this thread.

"We Called it Gutenberg for a Reason."
27 August, 2017 by Matt Mullenweg.
https://ma.tt/2017/08/we-called-it-gutenberg-for-a-reason/

**Comment by ahmadawais** [comment]
@paaljoachim Thanks for creating this awesome thread. Here's another article that I wrote which I think is not linked here.

"Improve The WordPress Editor By Contributing to The Gutenberg Project!"
MARCH 1, 2017 — by Ahmad Awais
https://torquemag.io/2017/03/improve-the-wordpress-editor-by-contributing-to-the-gutenberg-project/

**Comment by ahmadawais** [comment]
ManageWP.org has a fair share of Gutenberg articles shared on it. 

https://managewp.org/search?q=gutenberg

**Comment by samikeijonen** [comment]
[Justin Sainton's article about Gutenberg is worth to read](https://zao.is/blog/2017/09/14/my-thoughts-on-gutenberg/), really good one.

**Comment by Stiofan** [comment]
[Enough with the Gutenberg Drama](https://wpgeodirectory.com/gutenberg-drama/) let's embrace the change and look forward... - Paolo Tajani

**Comment by afercia** [comment]
An alternative approach to Gutenberg
https://yoast.com/gutenberg-alternative-approach/
Joost de Valk – 03 October, 2017

**Comment by samikeijonen** [comment]
[Gutenberg, or the Ship of Theseus](http://matiasventura.com/post/gutenberg-or-the-ship-of-theseus/) by Matías.

**Comment by androb** [comment]
Gutenberg Myth-Busting (by me :))
https://go.tinymce.com/blog/gutenberg-myth-busting/

**Comment by youknowriad** [comment]
Just adding my two posts about Gutenberg

 - One thousand and one way to extend Gutenberg today https://riad.blog/2017/10/16/one-thousand-and-one-way-to-extend-gutenberg-today/
 - How Gutenberg is changing WordPress Development? https://riad.blog/2017/10/06/how-gutenberg-is-changing-wordpress-development/

**Comment by buzztone** [comment]
[Can Gutenberg be Guten-great?](http://idealienstudios.com/can-gutenberg-be-gutengreat)
25 October, 2017 - by Jamie Oastler

**Comment by paaljoachim** [comment]
User-testing Gutenberg
30 October, 2017 - Tim Hengeveld
https://yoast.com/dev-blog/user-testing-gutenberg/

**Comment by karmatosed** [comment]
As the project moves towards a full vision, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.

**Comment by afercia** [comment]
Random Thoughts on… Six Months of Using Gutenberg
January 4, 2018 – Aaron Jorbin
https://daily.jorb.in/2018/01/random-thoughts-on-six-months-of-using-gutenberg/

**Comment by ahmadawais** [comment]
Create Guten Block Toolkit: Launch, Introduction, Philosophy, & More! 🚀
2018-01-20
https://ahmadawais.com/create-guten-block-toolkit/

**Comment by ahmadawais** [comment]
🔰 `create-guten-block` — 🔥 ⚛‏ 📦 A zero-configuration #0CJS developer toolkit for building WordPress Gutenberg block plugins. https://AhmdA.ws/CreateGutenBlock_
⏳ DATE: 2018-01-21
👉 https://github.com/ahmadawais/create-guten-block

**Comment by paaljoachim** [comment]
Gutenberg WordPress Editor group (with additional articles etc not posted in this thread):
https://www.facebook.com/groups/161444577756897/

**Comment by metamn** [comment]
Getting started with Gutenberg theme development in five minutes
https://morethemes.baby/blog/2018/03/07/getting-started-with-gutenberg-theme-development-in-five-minutes

**Comment by DannyCooper** [comment]
"Gutenberg Block Library Provides a Searchable Index of Individual Blocks" 

https://wptavern.com/gutenberg-block-library-provides-a-searchable-index-of-individual-blocks
