### ISSUE TITLE
Customize block options

### ISSUE THREAD

**Issue by woorise** [WordPress/gutenberg#14193]
Is possible to customize the block options? For example I want to remove "Duplicate" and "Remove Block" options for a specific  block.

![screenshot_2019-03-01 edit campaign - demo](https://user-images.githubusercontent.com/22965450/53650515-64a20980-3c4d-11e9-9218-97160d551b68.png)

**Comment by noisysocks** [comment]
Hey @woorise! It is not currently possible to customise this menu. 

You may find that [block templates](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-templates/) are a good fit for your use case where you want to restrict the user from deleting and creating blocks.
