### ISSUE TITLE
Conditional results not showing up correctly

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#14190]
**Describe the bug**
I just happen to notice that the conditional results are not showing up correctly.

The calculator looks like this on the LIVE site:
<img width="413" alt="screen shot 2019-03-01 at 15 18 18" src="https://user-images.githubusercontent.com/5323259/53643800-46301400-3c35-11e9-8022-8baf65c172df.png">

After the upgrade to 1.8.1 looks like this on the DEV site.
<img width="380" alt="screen shot 2019-03-01 at 15 18 54" src="https://user-images.githubusercontent.com/5323259/53643826-57792080-3c35-11e9-9dae-035c023b76c4.png">

I will include the json form of the very heavy conditionals calculator in use here: 
https://celias.no/bestilling/

DEV site here: 
https://celias.no/dev/bestilling/

I have created a calculator using lots of conditionals.

**Screenshots**

Backend calculator:
<img width="1264" alt="screen shot 2019-03-01 at 15 22 29" src="https://user-images.githubusercontent.com/5323259/53644040-e128ee00-3c35-11e9-8df1-60098975c9b3.png">

Frontend calculator:
It starts with the correct numbers. Then moving the sliders changes. On refresh of the page it resets to original numbers.
![conditionals-caldera-forms](https://user-images.githubusercontent.com/5323259/53644226-5a284580-3c36-11e9-9034-a3f5324ce65d.gif)

**Desktop (please complete the following information):**
Mac using Chrome

I see no error message in the console.
I switched to Twenty eighteen.
Deactivated all plugins except Caldera Forms.

The Exported Calculator:
https://www.dropbox.com/s/v0e9ti77cd2y3cp/dugnadskalkulator-2018-export.json?dl=0

**Comment by swissspidy** [comment]
How is this related to Gutenberg?

**Comment by paaljoachim** [comment]
Hmm my mistake.... wrong repo. Now I understand where this issue disappeared to.
