### ISSUE TITLE
Pasting RTL languages displays letters in the wrong order

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14202]
**Describe the bug**
When writing in a Left-To-Right (LTR) language (ie. English) there are times when I'd like to paste another word from a RTL language inline with the text (ie. Hebrew). This worked in the Classic editor, but doesn't appear to work in Gutenberg.

**To Reproduce**
1. Start writing in a LTR language (ie. English).
2. Copy and paste a word from a RTL language (ie. מִרְיָם) (The name "Miriam" in Hebrew)
3. The letters appear in opposite order than they do in step number 2.

![hebrew](https://user-images.githubusercontent.com/617986/53671292-935eb680-3c32-11e9-85e1-01af62acc7ca.gif)

**Expected behavior**
I expect that when pasting a RTL word, the letters also appear Right to Left in the appropriate order.

**Desktop (please complete the following information):**
 - OS:OSX
 - Browser FIreFox
 - Version 65.0.1
- Gutenberg 5.1.1

**Comment by mapk** [comment]
@youknowriad I'm curious to know if you've experienced this with Arabic?

**Comment by youknowriad** [comment]
It seems fine in Arabic 🤔

**Comment by ellatrix** [comment]
@mapk I cannot reproduce. I copy pasted the exact word you mentioned above, and it appears the same as on this page.

**Comment by mapk** [comment]
I tried again, ran into the same problem. It seemed to be when I was typing a LTR language and then pasting a RTL word in when it occurred. BUT that being said, once I deleted that, and re-pasted, it worked. 

It's really not clear why I have this problem, and it's not all the time. I'll close this for now unless something more regular happens with this that I can explain better.
