### ISSUE TITLE
Bad display in fullscreen mode

### ISSUE THREAD

**Issue by lcswillems** [WordPress/gutenberg#14204]
**Describe the bug**

In normal mode, correct display:
![image](https://user-images.githubusercontent.com/5437552/53682282-5ce97000-3cf4-11e9-95c6-abfabced19ca.png)

In fullscreen mode, incorrect display:
![image](https://user-images.githubusercontent.com/5437552/53682270-33304900-3cf4-11e9-9aed-4801af1cd52b.png)

There is free space at the bottom. It should be removed.

**To Reproduce**

Install Yoast plugin then go in fullscreen mode.

**Expected behavior**

The free space at the bottom must be removed.

**Comment by youknowriad** [comment]
I'm not able to reproduce, this might have been already fixed in the last version of the plugin?

**Comment by lcswillems** [comment]
Effectively, it had been fixed.
