### ISSUE TITLE
columns issue / alignment

### ISSUE THREAD

**Issue by JeromeWidl** [WordPress/gutenberg#14208]
Hi everbody
Tried to find a solution but I'm stucked.

I create 3 columns, and insert a picture in one of each.
Everything looks good when it deals with full screen res.
However, with responsive, the 1st image is not aligned with the others.
Always on the left, more or less.
Did I do something wrong?
Found that it had to be solved with version 3.8 but I'm up to date.

Thanks for your help

Jerome

**Comment by youknowriad** [comment]
I can't reproduce the issue personally, maybe it's a theme issue? Styles from the theme conflicting with the block styles. Let's reopen if we find ways to reproduce.
