### ISSUE TITLE
InnerBlock core/freeform Error 'EndTag'

### ISSUE THREAD

**Issue by nguyenvanthinh06** [WordPress/gutenberg#14209]
I write a block, I use InnerBlock allowed block 'core/freeform'. When I saved block then I refresh page then It errors "Expected token of type `EndTag`" . I hope @GutenDev  solve help me this problem!

Thank you very much!

![error-freeform](https://user-images.githubusercontent.com/17206775/53722327-dd94a180-3e97-11e9-9874-b97d75d174ba.png)

**Comment by youknowriad** [comment]
Duplicate of #13187
