### ISSUE TITLE
Media & Text Block: Allow media to fill the entire column

### ISSUE THREAD

**Issue by frontdevde** [WordPress/gutenberg#14226]
## Feature Request

In the Media & Text block it would be nice to have the option to make the media fill the full height of its column. In addition to providing a new creative option, this would allow for a more consistent look of the block across different viewports.

### Current block behavior without media fill option

<img width="680" alt="screen shot 2019-03-04 at 16 45 21" src="https://user-images.githubusercontent.com/1562646/53765346-bf31a480-3e9d-11e9-97f2-02b6eab503ce.png">

### Proposed block behavior with media fill option

<img width="642" alt="screen shot 2019-03-04 at 16 50 38" src="https://user-images.githubusercontent.com/1562646/53765361-c9ec3980-3e9d-11e9-8227-c63243d3cba0.png">

**Comment by getdave** [comment]
Worth putting up a _draft_ PR for this as well.

**Comment by koke** [comment]
It seems #14445 implemented this feature, so I understand it should be fine to close this issue. Please feel free to reopen if that's not the case, and I missed any other details.
