### ISSUE TITLE
Possible bug in Gutenberg, or possible bug in theme

### ISSUE THREAD

**Issue by xaviergimeno** [WordPress/gutenberg#14223]
Hello,

Lately, from Gutenberg, when I try to use it (I have chosen to stop doing it), I get the following message: "Failed to load plugin url: https://www.xaviergimeno.net/wp-content/themes/purity/functions/tinymce/langs/en.js ".

It seems a problem with the theme (purity theme by Venteed), but I'm not sure.

I've checked if the message appears both with existing pages/posts and with new pages/posts, and it seems only appeared with existing pages/posts.
​Thanks.​

**Comment by addedlovely** [comment]
@xaviergimeno if you open that URL in the browser you'll see it's a 404 / not found page. Would suggest to re-upload that file to your theme folder as it is missing, or take the issue up with your theme developer. Doesn't look to be Gutenberg related.

**Comment by xaviergimeno** [comment]
Firstly, thanks for the quick reply. Yes, in effect, I've checked the url previously to write my report here, with same result. Today I've received a reply from theme developer saying that theme must be updated in May. Thanks for your support.

**Comment by youknowriad** [comment]
Yes, it doesn't seem like a Gutenberg issue to me.
