### ISSUE TITLE
The filter does not work

### ISSUE THREAD

**Issue by almendron** [WordPress/gutenberg#14221]
WordPress 5.1
Plugin https://wordpress.org/plugins/no-gutenberg/ : Installed and activated
Therefore, Gutenberg disabled
Filter:
`add_filter('tiny_mce_before_init','tinymce_allow_unsafe_link_target');
function tinymce_allow_unsafe_link_target( $mceInit ) {
	$mceInit['allow_unsafe_link_target']=true;
	return $mceInit;
}`

**The filter does not work**
If I edit an entry, then the editor TinyMCE adds "noopener" and "noreferrer".
This causes problems with plugins that use the field "rel" (for example, images if they use target = "_ blank"), since it does not differentiate between own links and links to external sites.

I have found two functions that could be related to the error.
File wp-includes/formatting.php.

`function wp_targeted_link_rel( $text ) {
	if ( stripos( $text, 'target' ) !== false && stripos( $text, '<a ' ) !== false ) {
		$text = preg_replace_callback( '|<a\s([^>]*target\s*=[^>]*)>|i', 'wp_targeted_link_rel_callback', $text );
	}
	return $text;
}`

and "function wp_targeted_link_rel_callback"

Functions "wp_init_targeted_link_rel_filters" and "wp_remove_targeted_link_rel_filters" are also involved in the problem.

**Comment by youknowriad** [comment]
How does this relates to Gutenberg? Should this be a Core trac ticket?

**Comment by almendron** [comment]
The function
`add_filter( 'wp_targeted_link_rel', '__return_false', 9999 );`
and
`add_action( 'wp_loaded', 'wp_remove_targeted_link_rel_filters' );`

They do not work in the new editor. Therefore, it is a problem related to Gutenberg.

I do not want the new editor to add parameters to own links that open in a new window

**Comment by youknowriad** [comment]
Gutenberg don't use tinymce which means it doesn't support `tiny_mce` related filters like `tiny_mce_before_init`. I think a `wp_content` filter could be applied to solve this as an alternative Similar to how `wp_targeted_link_rel` works.

**Comment by almendron** [comment]
WordPress 5.1
Plugin https://wordpress.org/plugins/no-gutenberg/ : Installed and activated
Therefore, Gutenberg disabled
**Problem solved** with `add_filter( 'wp_targeted_link_rel', '__return_false', 9999 );` o `add_action( 'wp_loaded', 'wp_remove_targeted_link_rel_filters' );`

WordPress 5.1
Gutenberg activated
The instructions indicated above do not work.
How to disable the addition of parameters?

**Comment by stratboy** [comment]
This code doesn't work in CLASSIC editor in Gutenbeg:

```php
add_filter( 'tiny_mce_before_init', 'add_tinymce_formats', 10, 2);
function add_tinymce_formats($mceinit, $editor_id){

  $new_styles = array(
    array(
      'title' => 'Test'
      ,'items' => array(
        array(
          'inline' => 'span',
          'title' => 'Red',
          'classes' => 'red'
        )
      )// end items
    )// and main array
  );

  $mceinit['style_formats_merge'] = true;
  $mceinit['style_formats'] = json_encode($new_styles);
  return $mceinit;
}
```

**Comment by kesiah** [comment]
@stratboy Were you able to solve it? I have the same problem.
WP version: 5.2.2
I already added 'styleselect' in mce_buttons_2 & Gutenberg is disabled with a plugin.

**Comment by stratboy** [comment]
Hi Laura, no sorry, I think it's a Gutenbenrg bug to be solved.

Laura ha scritto:

**Comment by mattsummers** [comment]
@stratboy @kesiah I had to add the "stylesheet" button to MCE button row #1 for it to work. I can confirm this works as of 5.2.4. There is no need to disable Gutenberg, these filters execute just fine.

It is also documented in the codex. But many of the old tutorials that show up in google searches leave out this step.

https://codex.wordpress.org/TinyMCE_Custom_Styles

**Comment by stratboy** [comment]
@mattsummers thank you

**Comment by youknowriad** [comment]
Looks like this has been answered.
