### ISSUE TITLE
Automated bulleted list regardless of paragraph setting.

### ISSUE THREAD

**Issue by addedlovely** [WordPress/gutenberg#14237]
**Describe the bug**
I wanted to add images after each numbered list item. Discovered that I couldn't - so split the list into separate paragraphs. 

I manually added the numbering in a paragraph block, but when adding the text '1. ' the block get's transformed to a paragraph block automatically. 

Reverting this back to a paragraph then clears the text. It's then not possible to just have text in a paragraph block that starts with '1. ' without changing it to HTML.

**To Reproduce**
1. Add a new paragraph block.
2. Type '1. ' (without the quotes).
3. The block transforms to the bulleted list.
4. Change the block type back to 'paragraph'
5. The paragraph block is now empty.

**Expected behavior**
When transforming the block back to a paragraph for it to retain the 1. text, or not transform again to a list block.

**Desktop**
 - Mac OS Mojave
 - Chrome - Version 72.0.3626.119 (Official Build) (64-bit)

**Additional context**
Wordpress Version 5.1

**Comment by youknowriad** [comment]
This was fixed in a recent PR, you'll be able to "undo" the automatic transformation and the text will be kept. It will land in Gutenberg 5.3 and WordPress 5.2
