### ISSUE TITLE
How to get image title in gallery block

### ISSUE THREAD

**Issue by chiraggmodi** [WordPress/gutenberg#14232]
I want to expanding gallery block to display title of image in data attribute. But i didn't able to fetch title from image.

**Comment by youknowriad** [comment]
Changing the output of the "save" function is not a good approach of extending blocks as it creates "invalid blocks" if you disable your plugin.

That said, if you still want to do it, you should be able to use the `getMedia( id )` selector (rest api) to fetch the data of your images, store their fetched titles in a new attribute maybe and use this attribute to update the saved value. (I don't recommend any of this)

My recommendation would be to try to do this server side using the `render_block` filter.
