### ISSUE TITLE
Add support for <details> tag

### ISSUE THREAD

**Issue by Ghost180195** [WordPress/gutenberg#14252]
It would be nice to have such an opportunity.

**Comment by Soean** [comment]
IE and Edge don't support this tag: https://caniuse.com/#feat=details
More infos about this new HTML element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

So what you like to see in the editor is a block to toggle content?

**Comment by Ghost180195** [comment]
IE is already dead.
Edge is moving to Chromium
The block must include two elements.
1) Title (only text)
2) Content (must be flexible for nested block elements)

**Comment by Soean** [comment]
We still support IE 11, see in the [handbook](https://make.wordpress.org/core/handbook/best-practices/browser-support/), so we can't use the native <details> HTML tag at the moment.

**Comment by youknowriad** [comment]
I think it's a good idea for the future, but since it's not supported by all the browsers we support at the moment, I'm going to close for now. We should definitely revisit this later.
