### ISSUE TITLE
Document the different block styles (editor, theme and structural styles)

### ISSUE THREAD

**Issue by addzycullen** [WordPress/gutenberg#14256]
**Describe the bug**
I've noticed on a lot of our sites lately that are running the classic editor that the frontend of the site is loading in the CSS for block styles regardless of whether theme support is added or not.

I was under the impression and please correct me if I'm wrong, but, are they not only suppose to enqueue on the frontend if the following line is added to the functions file `add_theme_support( 'wp-block-styles' );`

**To Reproduce**
1. Activate a theme that doesn't declare `add_theme_support( 'wp-block-styles' );`
2. View assets being loaded in to a page on the front-end
3. You'll be able to see the stylesheet being loaded in.

**Expected behavior**
Block Stylesheets should not be loaded in unless explicitly told to do so in the functions file. If a theme has opted not to declare `add_theme_support( 'wp-block-styles' );` then that should be honoured.

**Additional context**
I am right about how `add_theme_support( 'wp-block-styles' );` should work aren't I? If I'm not then the usage of this line needs more clarity/explanation

**Comment by youknowriad** [comment]
There are two types of block styles that are loaded in the frontend:

 - the structural styles are always loaded
 - the opt-in styles (called also theme styles): are only loaded if you opt-in, using `add_theme_support( 'wp-block-styles' );`

I'm going to keep this issue open to trac the missing documentation.

cc @mkaz @nosolosw

**Comment by addzycullen** [comment]
Ahh ok, thanks for the clarification on that, hoped I was missing something somewhere
