### ISSUE TITLE
"Scribd block" doesn't work with any url. 

### ISSUE THREAD

**Issue by neobabis** [WordPress/gutenberg#14261]
**Describe the bug**
I tried a lot of **Scribd documents**.
I copy the url of a Scribd document (not the shortcode) directly into a "Scribd block" but the return is "Sorry, we could not embed that content".
Urls is like: _https://www.scribd.com/document/XXXnumbersXXX/TITLE-OF-DOCUMENT_

**To Reproduce**
A solution is:
1. Copy the Url _https://www.scribd.com/document/XXXnumbersXXX/TITLE-OF-DOCUMENT_
2. Replace the word `/document/` with `/doc/`
3. Just paste the "new" Url to a Scribd block

**But is this a real solution?**

**Screenshots**
![scribd bug](https://user-images.githubusercontent.com/48261152/53875810-13f42d00-400e-11e9-9e84-512973883a41.png)

**Additional context**
Wordpress Version 5.1

**Comment by youknowriad** [comment]
I suggest creating a trac ticket for this issue as it's more related to the backend or the oembed provider. The links don't seem to work in the classic editor as well.

**Comment by neobabis** [comment]
Where can I create a trac ticket?

**Comment by youknowriad** [comment]
@neobabis Here https://core.trac.wordpress.org/ 👍 Thanks
