### ISSUE TITLE
Injected editor-styles invalidate :root declarations thus breaking custom properties

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#14297]
**Describe the bug**
_Same issue, but different reasoning than #11955, which was closed without resolution in November 2018. The issue deserves another look and a solution as the `:root` pseudo-class is a core element of CSS custom properties which will see significantly increased use as [browsers now provide wide-spread support](https://caniuse.com/#feat=css-variables):_

When a theme uses [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) (aka "CSS variables") and declare those properties using the [`:root` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:root) in the editor styles, the injection script invalidates those declarations by outputting `.editor-styles-wrapper :root`.

**To Reproduce**
1. In editor styles document, declare CSS custom properties with `:root` pseudo-class.
2. Use above custom properties in another rule.
3. Add editor style using `add_editor_style()`.
4. Run in browser.
5. Observe the declared custom properties not kicking in.
6. Inspect code and find the `:root` pseudo-class has the `.editor-styles-wrapper` class prepended.

**Expected behavior**
`:root` pseudo-class should be preserved without alterations.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All with custom property support
 - Version: trunk

**Additional context**
See WP Rig PR [#332](https://github.com/wprig/wprig/pull/332) and issue [#361](https://github.com/wprig/wprig/issues/361) for further discussion and original discovery of the issue by @benoitchantre.

**Comment by mor10** [comment]
Filed as Trac ticket as well: https://core.trac.wordpress.org/ticket/46435#ticket

**Comment by youknowriad** [comment]
This was fixed in #13325 (will land in WP 5.2)
