### ISSUE TITLE
Button isBusy styles overwritten on hover/focus

### ISSUE THREAD

**Issue by buhlahkay** [WordPress/gutenberg#14296]
**Describe the bug**
If you assign the prop "isBusy" to a Button component that also has the "isDefault" prop, then the "isDefault" styles will override the background animation on hover/focus. So if you want to apply the busy styles to a button on click, it won't show the animation until the user clicks away from the button.

**To Reproduce**
If you use this code and click/hover/focus you can see the different styles being applied.
```
<Button
  isDefault
  isBusy
>
  Button
</Button>
<Button
  isPrimary
  isBusy
>
  Button
</Button>
```

**Expected behavior**
I would think that the "isBusy" styles should override any other buttons styles. Currently focus overrides the animation with both default and primary styles, and hover overrides the animation on default styles. At the least, I think both styles should behave the same.

**Screenshots**
This is the code above. I'm not changing the props on click or anything.
![chrome-capture](https://user-images.githubusercontent.com/29661164/53913710-92a69580-4021-11e9-956e-a5e60d267d79.gif)

**Comment by sbardian** [comment]
New to this project, but taking a look...
