### ISSUE TITLE
Copy-Paste Creates Doublespace in Firefox

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#14298]
**Describe the bug**
I am seeing some confusing behavior in Firefox on Windows 10

**To Reproduce**
1. Open a webpage in Firefox. ([Example](https://www.nytimes.com/2019/03/06/technology/mark-zuckerberg-facebook-privacy.html))
1. Copy at least one full paragraph.
1. Paste content into editor.
1. Content includes semi-random doublespaces. They seem to often-but-not-always align with line breaks. (There are also extra spaces at the start and end of the paragraph, but that seems to be a different issue that's not browser-specific.)

This behavior only impacts text copied from Firefox, but it doesn't seem to matter what browser the content is pasted into.

**Expected behavior**
No doublespaces.

**Screenshots**
Copy a paragraph in Firefox:
![a highlighted paragraph](https://user-images.githubusercontent.com/1238696/53923713-fe8efb00-402d-11e9-94f4-6a7374caa604.png)

Paste into editor (both Firefox and Chrome tested):
![3 red arrows pointing to double-space issues, 2 blue arrows highlight extra space and beginning and end of paragraph](https://user-images.githubusercontent.com/1238696/53923767-41e96980-402e-11e9-8364-41a78cf81bd5.png)

**Desktop (please complete the following information):**
Firefox, Windows 10, WordPress 5.1

**Comment by youknowriad** [comment]
I can't reproduce, I think this was fixed recently by one of @ellatrix's PRs.

**Comment by florianbrinkmann** [comment]
The issue exists in the version that comes with WP 5.2.1. Should the PRs that may have fixed that be included there @youknowriad, or is the code only in the plugin version currently?

**Comment by youknowriad** [comment]
@florianbrinkmann I don't know. I probably tested this in master. And I think mars 7 master is probably already shipped in WP 5.2.1. Let's reopen to investigate further.
