### ISSUE TITLE
docgen: general improvements to Markdown format

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14290]
This is to add requests to improve formatting that we should apply in batch to all packages, once the PRs at https://github.com/WordPress/gutenberg/issues/14227 are landed.

**TODO**

- Add code formatting to titles. See https://github.com/WordPress/gutenberg/pull/14266#discussion_r262955423
- Review why list items get more spaces than one. See https://github.com/WordPress/gutenberg/pull/14279#pullrequestreview-211454019

**Comment by aduth** [comment]
Couple other thoughts:

- The generated function output looks very run together, and it's hard to identify where one function's documentation ends and the other begins. Additional formatting like using code for titles could help this by serving as a sort of visual mark. Line separators (`---`) may be another option, though perhaps too severe a division.
- Would it make sense to include a leading table of contents for the functions? Just a list of links. I could see a counter-point being that it might be more on the rendered context to make sense of the semantic structure of the markdown document and build its own table of contents if applicable (i.e. the WordPress Developer Handbook page or [GitHub itself](https://github.com/isaacs/github/issues/215) generating a table of contents)
