### ISSUE TITLE
Issuu embed block is not responsive

### ISSUE THREAD

**Issue by crunnells** [WordPress/gutenberg#14299]
The Issuu embed block is not responsive on smaller screens. The embedded JS that comes from Issuu adds an inline `width: 640px` and `height: 461px` to the `<iframe>` container block regardless of the screen size. An easy solution is to add some CSS: `.issuu-isrendered { max-width: 100%; }`

**To Reproduce**
1. Create a new post
2. Add an Issuu embed block
3. Add an Issuu URL to the embed field (eg: https://issuu.com/diymagazine/docs/diy_march_2019) 
4. Save page and then view on a mobile device/browser with responsive mode.

**Screenshots**
<img src="https://cldup.com/DJwZmxPUtb-3000x3000.png">

**Additional context**
- Bug affects any theme, but initially reported on Argent. I tested on Twenty Nineteen.
- Gutenberg in WP 5.1

**Comment by youknowriad** [comment]
Thanks for opening this issue.

Unfortunately the styles and the content of the embeds is not controlled by WordPress, this issue is better raised directly to the oembed provider (issuu here).

**Comment by senff** [comment]
Although we're not able to control the style and content, we can definitely make the container responsive, which will also make the iFrame in it responsive:

```
.embed-issuu  {
  position: relative;  
  max-width: 100%;
  height: 0;
  overflow: hidden;
  padding-bottom: 75%;
}

.embed-issuu .issuuembed {
  position: absolute;
  left: 0;
  top: 0;
  width: 100% !important;
  height: 100% !important;
}
```

**Comment by samiff** [comment]
Additional report in 2352576-zd

**Comment by Lofesa** [comment]
Hi
Same here.
WP 5.3.2
The embed has a style in the `<div data-url="url_from-issuu" style="width:1200px;height:848px" class="issuuembed issuu-isrendered">`

Changein the style to style="width:100%;height:848px" makes it responsive

**Comment by jordesign** [comment]
Closing this issue as there has been no additional activity in over 3 years. If there are additional reports - we can always open this again.
