### ISSUE TITLE
Scripts in HTML Block

### ISSUE THREAD

**Issue by klihelp** [WordPress/gutenberg#14293]
**Describe the bug**
Some characters, like &&, are escasped inside inline ```<scripts>``` and that breaks the javascript code.

**To Reproduce**
1. Add 
```
<script type="text/javascript">
// Scripts in the html block
var bool = true && true;
</script>
```
2. See font end source code, character & replaced to &#038;
```
<script type="text/javascript">
// Scripts in the html block
var bool = true &#038;&#038; true;
</script>
```

**Expected behavior**
HTML block inline scripts to work on frontend, without getting escaped.

**Desktop (please complete the following information):**
 - OS: macOS lates 
 - Browsers: all modern

**Comment by eltel** [comment]
+1!!

**Comment by noisysocks** [comment]
I was not able to reproduce this in the latest development version of Gutenberg. 

Steps I followed:

1. Insert an HTML block
2. Paste in this snippet:
   ```
   <script type="text/javascript">
   // Scripts in the html block
   var bool = true && true;
   alert( bool );
   </script>
   ```
3. Publish and view the post
