### ISSUE TITLE
Sidebar header navigation improvements

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1429]
Somehow related to #1356 

It took me a while to understand that clicking the "Post" link in the Sidebar header:

![screen shot 2017-06-25 at 14 55 08](https://user-images.githubusercontent.com/1682452/27516289-9d61729e-59b7-11e7-9ffc-aae2af26fabf.png)

switches back the sidebar to display the main settings instead of the specific setting of the block being edited:

![screen shot 2017-06-25 at 14 54 16](https://user-images.githubusercontent.com/1682452/27516298-c2b46ba0-59b7-11e7-9f73-e2ac31d7a1f5.png)

It's a pretty neat feature, maybe a bit hidden and not so easily discoverable. Basically the Sidebar header behaves like sort of "breadcrumbs" navigation. Wondering if just renaming some controls would help making this feature more discoverable, for example changing the button label "Post Settings" and the header first level "Post" to just "Settings".

Worth also noting both terms are a bit misleading when editing a Page (and, in the future, CPTs):

![screen shot 2017-06-25 at 14 56 00](https://user-images.githubusercontent.com/1682452/27516341-7e2aae08-59b8-11e7-8853-34dfa7d6263e.png)

![screen shot 2017-06-25 at 14 56 37](https://user-images.githubusercontent.com/1682452/27516342-7e2dad4c-59b8-11e7-8e11-d761261b6213.png)

**Comment by jasmussen** [comment]
Just to clarify, are you suggesting we rename the breadcrumb to "Post Settings" instead of just "Post" (and of course the CPTs)? If yes, I would agree that's a better experience 👍

**Comment by afercia** [comment]
Yep I think the "breadcrumbs" first level text (currently: "Post") should match the toggle button text and the default sidebar heading text. It could be "Post Settings" or maybe just "Settings": in the second case, there wouldn't be the need to distinguish between Post, Page, CPT...
