### ISSUE TITLE
Post 'Updating...' & 'Saving' never ends

### ISSUE THREAD

**Issue by milanbx** [WordPress/gutenberg#14302]
**Describe the bug**
If I edit a page/post and click on 'Update' btn, its caption changes to 'Updating...' and left ftom 'Preview' btn the 'Saving' caption with the cloud icon starts blinking. And this stays forever, until I erload the edit page. And sometimes the post gets saved, somthimes not.

**To Reproduce**
1. Edit a pag/post.
2. Click on 'Update'.
3. See error.

**Expected behavior**
1. The post/page should be always saved when 'Update' is clicked and it should be done inreasonble time. 
2. Once the post/page is saved, the btn caption should change from 'Updating...' back to 'Update'

**Screenshots**
see link: [screenshot](https://www.dropbox.com/s/ojle3lqb96r9nd6/updating%20hangs.jpg?dl=0)

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Firefox
 - Version 65.0.2 x64

**Comment by youknowriad** [comment]
Hi there!

I can't reproduce this personally.
Can you find the error in the network tab of you browser's console?

**Comment by milanbx** [comment]
Well, not sure. It ends up here:

**Comment by youknowriad** [comment]
I'm going to close as we can't reproduce this. This is most likely an issue with the REST API call somewhere. It could happen for several reasons (php errors/warnings, server config issue...)
