### ISSUE TITLE
Ignored backspace after switching italic and bold text

### ISSUE THREAD

**Issue by maurobringolf** [WordPress/gutenberg#1430]
I just tried writing my first post with Gutenberg and discovered this strange behavior:

1. Type regular text into a text block. End with a space.
1. Turn on bold and italic, then turn both off again (without typing anything).
1.  Hit backspace.

The backspace has no effect and the space character is not deleted. From what I have tested it only occurs when both italic and bold are switched and only if both are switched back and forth. 

It is a detail but I thought it is worth reporting here.

**Comment by karmatosed** [comment]
I am unable to recreate this following the steps using the latest plugin. Can you maybe show a video and add what browser you are using?

**Comment by maurobringolf** [comment]
I am using the following:

WordPress 4.8
Chrome 58.0.3029.110
MacOS Sierra 10.12.3

**Comment by karmatosed** [comment]
Closing as unable to replicate. If you can provide a video or further steps that would be great. Until then closing.
