### ISSUE TITLE
Update the documentation manifest to use relative links instead of pointing to "master" explicitely.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#14303]
This will allow building the handbook from several branches.

cc @chrisvanpatten @mkaz @nosolosw

**Comment by nosolosw** [comment]
Core ticket: https://meta.trac.wordpress.org/ticket/4244

**Comment by nosolosw** [comment]
@youknowriad was looking into this today. I saw the core patch to update the branch the contents are pulled from in the plugin.

I'm offering a different approach here that doesn't require adding steps to the WordPress release process:

- PHP docs importer will stay as it is. No changes necessary during WordPress releases.
- Manifest `markdown_source` entries are updated after the WordPress release to point to the latest stable branch. Example: https://github.com/WordPress/gutenberg/pull/14699

**Comment by nosolosw** [comment]
PR ready at https://github.com/WordPress/gutenberg/pull/14739

**Comment by nosolosw** [comment]
Closing this as the DevHub's handbook uses relative links.
