### ISSUE TITLE
Weird nested <ul> behaviour

### ISSUE THREAD

**Issue by rozmy** [WordPress/gutenberg#14310]
I built this simple example nested ul structure
`<ul><li>pancake<ul><li></li><li>berries</li><li>ice cream</li></ul></li><li>soup</li><li>main dish</li></ul>`
![image](https://user-images.githubusercontent.com/7920792/53957147-e4145a80-40dd-11e9-852c-54c5625b6c2e.png)

Try insert "pancake" before berries:
![image](https://user-images.githubusercontent.com/7920792/53957256-2ccc1380-40de-11e9-8b4f-533e8e37c5cd.png)

It becames something new, unused weird format

**Comment by youknowriad** [comment]
Which version of Gutenberg are you using? Is it WordPress 5.1? Is it the Gutenberg plugin 5.2. This should be fixed in the Gutenberg plugin and will land in WordPress in the next version.

**Comment by rozmy** [comment]
Plugin Version 5.2.0

**Comment by youknowriad** [comment]
Which browser?

**Comment by youknowriad** [comment]
Actually I reproduce on Firefox cc @ellatrix

**Comment by rozmy** [comment]
Chrome 72.0.3626.119 
OSX 10.14.3

**Comment by ellatrix** [comment]
Should be fixed by #13948.
