### ISSUE TITLE
Can't add any tags outside of the first ten on Safari

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#1431]
When I try to add one of the first ten tags, it works fine. If I try to add a new one, it vanishes after I press save.

**Comment by karmatosed** [comment]
@Ipstenu I wasn't able to recreate this, but it could be a case of me not getting the exact steps. I am doing the following:

- Creating a post with title and then add 10 tags. For example 'tag1.. tag2...'.
- Save post (not publish)
- Add another tag
- Save post (not publish)

Are those the steps you get the issue with?

**Comment by Ipstenu** [comment]
* Create a post with a title and post content.
* Save Post
* Make more edits
* Save post
* Add category 
* Add Tags (doesn't matter how many - if it's anything beyond the first 10 shown on the list)
* Save post

No tags :( It shows the tags properly up until I save, but then they're gone.

This is likely related to #1338

**Comment by Ipstenu** [comment]
Just in case people are still not sure what I mean, here: https://cloudup.com/cIVYWidtuXo

Seriously, on Safari I cannot save ANYTHING outside of the first 10 tags ☹️

**Comment by Ipstenu** [comment]
Oh and just for fun, if I add in tags via quick editor, here's what they look like in Gutenberg. 😧

<img width="280" alt="screen shot 2017-06-27 at 27 jun - 7 32 23 pm" src="https://user-images.githubusercontent.com/807903/27618144-6fd1646a-5b6f-11e7-85d4-8e4bf72c3436.png">

**Comment by youknowriad** [comment]
fixed in #1490
