### ISSUE TITLE
Block Navigation - Automatically scroll to the selected block

### ISSUE THREAD

**Issue by rozmy** [WordPress/gutenberg#14311]
The block navigation's selected item is sometimes way below the current viewport. This could be fixed by inner-scrolling to the selection.

![image](https://user-images.githubusercontent.com/7920792/53957853-c1834100-40df-11e9-8e30-5283d65b71f9.png)

**Comment by nickylimjj** [comment]
Working on this issue.

**Comment by gziolo** [comment]
@rozmy can you provide more details like your operating system and browser used?

**Comment by nickylimjj** [comment]
In recreating the bug, I discovered another one where the viewport didn't show the selected item if it's far below. I would require scrolling it. Working on a fix now

**Comment by nickylimjj** [comment]
![selected block not in view](https://user-images.githubusercontent.com/12999836/55898264-3985d080-5b90-11e9-9ff0-f8dc596836ca.png)
![additional step to scroll to block in view](https://user-images.githubusercontent.com/12999836/55898269-3be82a80-5b90-11e9-86bf-2a61f00ce7d9.png)

**Comment by nickylimjj** [comment]
Apologies for crowding this issue thread. I thought it was related and a trivial fix. I opened at issue #14913.

**Comment by nickylimjj** [comment]
Working on a fix.

**Comment by Mamaduka** [comment]
It is now possible with the List View. I'm going to close the issue.
