### ISSUE TITLE
Recent update breaks RangeControl step

### ISSUE THREAD

**Issue by kadencethemes** [WordPress/gutenberg#14319]
**Describe the bug**
Pull request #12952 breaks the ability to use a step less than 1. For example, if you set the step to 0.1 you can't slide the slider to anything but whole numbers. 

Being able to set the range control step is really useful for inputs that control opacity, em units etc...

This change from pull request #12952 breaks several controls in Kadence Blocks.

**To Reproduce**
1. Add a Range control and define the step as 0.1
2. Try to use that range control.

**Expected behavior**
The range control should allow the steps to be whatever is set through the properties of the input.

**Desktop (please complete the following information):**
Any - all.

**Additional context**
A simple workaround to keep the new functionality added with pull request #12952 would be to change [line 52](https://github.com/WordPress/gutenberg/blob/078041bd1f78b688eac133fb17838704ca0bc53c/packages/components/src/range-control/index.js#L51) to this instead:

```
let newNumericValue = parseInt( newValue, 10 );
if ( props.step !== undefined && props.step < 1 ) {
     newNumericValue = parseFloat( newValue );
}
```

**Comment by chrisvanpatten** [comment]
Great report @kadencethemes. Any chance you could open a PR for the fix you suggested?

**Comment by kadencethemes** [comment]
Added pull #14320
