### ISSUE TITLE
Column Block Issue

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#14323]
**Describe the bug**
i am using Column Block > Add Classic Block > UL&Li Using > Then Issue..

**To Reproduce**

1. Click on Column Block
2. Add Classic Block
3. Add Content For UL&Li
4. Save Your Page
5. Refresh Your Page
6. See error

**Screenshots**

![columnissue](https://user-images.githubusercontent.com/45058029/53980661-e060f200-4136-11e9-88b9-e5200459357d.gif)

**Desktop (please complete the following information):**
OS: Linux
Browser Chrome
Version 71.0.3578.98
Additional context

**Gutenberg: latest from master**
WordPress: 5.1

**Comment by talldan** [comment]
Hi @utsavtilava - thanks for reporting this issue.

The classic block is really only intended for backwards compatibility with the old classic editor. Unfortunately it doesn't work in quite the same way as other blocks, and as such I wouldn't have expected that inserting it in a column should be possible.

If you'd like to add a list (`<ul>`) to a column there's a way to do it without using the classic block:
1. Add a columns block.
2. In the columns block type '- ' (a hyphen followed by a space) or '* ' (an asterisk followed by a space).
3. A list is created.

Also noting these related issues: #14025, #13187, #12674, so I'll close this as a duplicate
