### ISSUE TITLE
Provide the 'triple dot' menu on empty paragraph for easier removal.

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#14325]
**Describe the bug**
Currently when you have an empty paragraph block to remove it you hit backspace (delete key) or you switch to Code View to remove it. New users are unaware of the backspace and often don't feel comfortable in Code View. It would be nice to provide the triple-dot menu which provides the Delete Block option on empty paragraph blocks.
Alternatively, could update the placeholder text 'Start writing or type / to choose a block.' to add 'To remove simply hit the backspace/delete button'. Or something along those lines.

**To Reproduce**
1. Go to the block editor
2. Add an empty paragraph block.
3. Click on it and find only the 'Add Block', 'Add Image', 'Add Heading' and 'Add Gallery' options.
*It's not clear how to remove this block.

**Expected behavior**
A clear method for removing the empty paragraph block would be nice. Something that didn't require the user to guess or read docs to understand how to remove.

**Screenshots**
![screen shot 2019-03-07 at 12 55 07 pm](https://user-images.githubusercontent.com/8726005/53988632-d0b2c080-40d8-11e9-80d7-3985f8f21bca.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome 72.0.3626.121

**Additional context**
- WordPress Core 5.1

**Comment by talldan** [comment]
Hey @garrett-eclipse, I found this issue, which appears to be the same as yours:
https://github.com/WordPress/gutenberg/issues/10385

I'll close this and make a note of your suggestion on that issue.

**Comment by garrett-eclipse** [comment]
Thanks @talldan I appreciate the reference and am now following there. All the best
