### ISSUE TITLE
Create Multiple/Move Toolbar?

### ISSUE THREAD

**Issue by Keith-Cancel** [WordPress/gutenberg#14327]
I am trying to creating a block that has multiple editable areas. I found easy enough to add buttons to the toolbar, but I also need separate toolbars like what happens when you put two blocks in the column block. So I have tried searching both issues, documentation, and code to try and figure out how to do this. 

Here is what I am mean that the a column block with paragraph blocks does quite close to what I am trying to achieve.

Here it is the toolbar with none of the two paragraphs actively being edited.
![no active](https://user-images.githubusercontent.com/8355441/54004035-15565000-4109-11e9-9bab-6ef7df0a706f.png)

Here is the toolbar with the left paragraph active.
![left](https://user-images.githubusercontent.com/8355441/54004471-792d4880-410a-11e9-8df4-0a74314d245e.png)

Here is the toolbar with the right active.
![right active](https://user-images.githubusercontent.com/8355441/54004169-72520600-4109-11e9-946d-1fc2beae3281.png)

Also the sub-blocks have a border, and nice hover functionality.
![hover](https://user-images.githubusercontent.com/8355441/54004219-a3cad180-4109-11e9-9570-275ad1e4cb33.png)

So here is a simple block I made with two rich text components in it with none being actively edited.b
![left](https://user-images.githubusercontent.com/8355441/54004286-decd0500-4109-11e9-93b1-17dc787672f2.png)

The left rich text component is now being edited.
![no active](https://user-images.githubusercontent.com/8355441/54004257-ca890800-4109-11e9-97e1-f595171d2829.png)

The right rich text component is now being edited.
![right](https://user-images.githubusercontent.com/8355441/54004309-f7d5b600-4109-11e9-9a7d-762ea6c174cf.png)

As you can see that toolbar remains exactly the same between the left and right. Is there some way to get the toolbar to move like it does when you have blocks in a column block depending on what you have actively selected.

**Comment by talldan** [comment]
Hi @Keith-Cancel, the columns block has nested blocks. This is achieved using a component called `InnerBlocks` within the columns block. Unfortunately there's no documentation beyond the README file:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inner-blocks/README.md

I'd recommend also looking at how InnerBlocks is implemented for other core blocks:

**Columns/ Column**
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/index.js
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/column.js

**Media & Text**
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/media-text/edit.js
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/media-text/index.js

**Cover**
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/cover/edit.js
- https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/cover/index.js

**Comment by Keith-Cancel** [comment]
Will do thanks.
