### ISSUE TITLE
docgen: review `--ignore` option

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14337]
Make it match the guidelines. Review what symbols don't adhere, and rename them. Ref: https://github.com/WordPress/gutenberg/pull/14268#discussion_r263577218

> Couple thoughts:
> 
> * If this is a regular expression, should we be assuring `^` so that we'd not inadvertently ignore the token `definitely_not_unstable` (ignoring the fact this would, for other reasons, not be allowed)
> * The [guidelines](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#experimental-apis) clearly prescribe the double-underscore `__` prefix. I don't think we want the tolerance here. I want to see clear and loudly in the produced documentation if we're not naming these correctly.

**Comment by paaljoachim** [comment]
Close issue?

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
