### ISSUE TITLE
docgen: generate namespace for symbols

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14332]
Explore the use of `@namespace`/`@memberof` to document where the symbols are to find. For example: the symbols within the `rich-text` package are to find in `wp.richText` package. How do we document that?

Potential approach: we could have a `--namespace=wp.richText` option for `docgen` that will add the necessary boilerplate (`@memberof` to symbols, global `@namespace`, etc.) to the intermediate representation without developers needing to write it one by one. Formatters then will take that input and could prepend the symbols with `wp.richText`, or group them by namespace when we are ready to present this info in developer.wordpress.org, etc. 

Ref:

* http://usejsdoc.org/tags-namespace.html
* http://usejsdoc.org/tags-memberof.html

**Comment by paaljoachim** [comment]
Close?

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
