### ISSUE TITLE
docgen: add `<caption>` to `@example` tag

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#14331]
When there are multiple examples -for instance: ES5 syntax and ESNext syntax- it's useful to caption them or even present them tabbed, like in the Gutenberg handbook. We could use the `caption` metadata to process this.

See discussion at https://github.com/WordPress/gutenberg/pull/14263#issuecomment-470072511

**Comment by nosolosw** [comment]
One issue that we may want to address is the fact that these are rendered in npm, github, and the handbook. At the moment, the tabs are only properly rendered in the handbook and weirdly rendered in the other places.

**Comment by oandregal** [comment]
I'm triagging issues we don't plan to tackle. We can reopen if it regains interest.
