### ISSUE TITLE
docgen: experiment with `@implements` to group symbols

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14333]
One thing we may want to do is to group symbols together for documentation purposes. For example, group all data actions, or all data selectors, group UI components, etc. See [discussion](https://github.com/WordPress/gutenberg/issues/14292#issuecomment-470475069) for a more detailed exploration of this.

**Comment by paaljoachim** [comment]
Can this issue also be closed?

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
