### ISSUE TITLE
When another editor takes over screen, the "All Posts" button doesn't make sense

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14345]
**Problem**
When I had a post taken over by another editor, I received a modal popup on the screen. I didn't get a screenshot but got a screenshot of the popup if I was going to take over the screen.

![screen shot 2019-03-08 at 7 07 51 am](https://user-images.githubusercontent.com/617986/54036807-5f731c00-4171-11e9-98c6-f49c95793254.png)

The "All Posts" button didn't make sense to me. The other two buttons are a call to action, but All Posts is not. And in the screen where another user takes over your editing, the button seems to make less sense b/c it's displayed by itself.

**Describe the solution you'd like**
Can the text be reworded to request an action instead? Maybe something like "View All Posts"?

**Comment by michelleweber** [comment]
Agree, good call. I think "View all posts" works (or "Return to posts list" if you want to be super clear (and don't mind the button getting longer) is an improvement.

I wonder if the best way to go, though, might be "Exit post editor." It's simple, and probably makes the most sense as an option -- if you get this pop-up, it means you're either staying on this page, leaving this page, or opening a new window (previewing). So let's just have the buttons map to those three options.

**Comment by mapk** [comment]
Thanks @michelleweber! I've got a PR ready that shows these changes.

**When taking over a screen**

![screen shot 2019-03-08 at 7 56 23 am](https://user-images.githubusercontent.com/617986/54039448-d3b0be00-4177-11e9-9b58-73b48259f707.png)

**When having screen taken over from you**

![screen shot 2019-03-08 at 7 55 58 am](https://user-images.githubusercontent.com/617986/54039461-db706280-4177-11e9-8888-67a2a0063ad2.png)

I went with "Exit the Editor" because these modals are used across Pages, Posts, and Portfolios. 

Props: @kjellr
