### ISSUE TITLE
ColorPicker Component doesn't save GUI state when saved using meta attributes

### ISSUE THREAD

**Issue by LiamWinterton** [WordPress/gutenberg#14346]
When using the ColorPicker and saving its value to postsmeta, reloading the page does not retain the same GUI state, even though the value has saved.

**To Reproduce**
1. Create a basic block with one attribute: 'color', that has the type of 'string', source of 'meta', and a desired meta key.
2. Render the ColorPicker inside the edit function of the `registerBlockType` options object. Include `onChangeComplete` functions to save your value via `props.setAttributes`
3. Return null in the save function.
4. In your plugin file, use `register_meta` to expose your meta field to the rest API via `show_in_rest`.
5. Use `register_block_type` to register your block, and create a basic function to return the front end html.
6. Add your new block, change the colour and save.

**Expected behavior**
Upon reloading the page, the color picker should be visibly selecting the previous color.

**Actual behavior**
The color picker GUI resets to the default `#000000` selection. In the postmeta table, the value is saved, and can be used in the created function in step 5.

**Screenshots**

Before Post reload

![Pre page reload](https://user-images.githubusercontent.com/32865805/54038534-ae906f80-41b8-11e9-87fa-a1a5f3dea32e.png)

After post reload

![image](https://user-images.githubusercontent.com/32865805/54038654-f0211a80-41b8-11e9-8f37-2ae704841ff4.png)

**Additional context**
- WordPress version: 5.1
- Theme used: `Twenty Nineteen`
- Converting the block to use the save function, and removing the register_block_type render_callback fixes this issue.

**Comment by youknowriad** [comment]
Could you share the code of your block?
