### ISSUE TITLE
docgen: add source URLs to the default formatter

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#14341]
As of https://github.com/WordPress/gutenberg/pull/14656 the generated docs no longer include the URL to the export statement.

These are some problems we faced:

- Relative URLs work well for [github](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-test-utils) or a local git repo, but they doesn't for [npm](https://www.npmjs.com/package/@wordpress/e2e-test-utils) or the [handbook](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-e2e-test-utils/).
- Using the `<>` symbol to point to code had a weird formatting in the handbook due to escaping (see https://github.com/WordPress/gutenberg/pull/14656).
- We may want to consider pointing to the symbol definition instead of/besides pointing to the export statement. See https://github.com/WordPress/gutenberg/pull/14243#discussion_r264547017

**Comment by aduth** [comment]
If I'm being honest, I don't know that I long for the URL to return. I think it could be argued that it provides some value, but also a fair amount of pain in the line-number-only revisions it has a tendency to introduce to a README file in the course of a pull request.

**Comment by nosolosw** [comment]
I share that sentiment. One thing that is growing on me is that its usefulness depends on context:

- I'm all in for having the URL in the handbook. That's something that you navigate with the browser, and you may want to have a quick look at the implementation.

- README files that are collocated with code: it's nice, but doesn't provide the same value.

Right now, both use the same README. But there is no reason they should (specially if/when we consider moving the symbols to developer.wordpress.org).

I don't feel the urge to prioritize this.

**Comment by oandregal** [comment]
I'm triagging issues we don't plan to tackle. We can reopen if it regains interest.
