### ISSUE TITLE
Switch toggle state sometimes reported incorrectly

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1435]
Looks like the switch toggle state is sometimes reported incorrectly. While, visually, everything looks OK, in some cases the actual state seems reported wrongly when using a screen reader. Testing with Safari + VoiceOver:

correct: "unchecked"

![screen shot 2017-06-26 at 11 13 19](https://user-images.githubusercontent.com/1682452/27532869-ec83ec62-5a61-11e7-99ed-dc1aa32e0a59.png)

incorrect: "checked"

![screen shot 2017-06-26 at 11 13 29](https://user-images.githubusercontent.com/1682452/27532890-feac5fd2-5a61-11e7-8528-57d792e9a108.png)

incorrect: "unchecked"

![screen shot 2017-06-26 at 11 13 35](https://user-images.githubusercontent.com/1682452/27532912-123dd562-5a62-11e7-83e8-4933e7660e53.png)

**Comment by afercia** [comment]
Can reproduce also with Firefox + NVDA:

![screenshot 114](https://user-images.githubusercontent.com/1682452/27533266-4072146a-5a63-11e7-825a-5ffc39a29a17.png)

**Comment by afercia** [comment]
I'm a bit surprised by how react treats the checked attribute, see https://github.com/facebook/react/issues/7051 and how it is deviating from simple, basic HTML requirements. These kind of deviations can easily produce side effects, like in this example. Following these React patterns, it may appear explicitly setting a `checked` attribute is not really needed. Instead, omitting it causes a serious accessibility issue. 
Looks like just explicitly adding a `checked` attribute, even if it's not printed in the DOM, fixes the issues because software, including screen readers, rely on its presence.

**Comment by youknowriad** [comment]
I think we should probably use the `checked` prop instead of the `value` (we're currently using). I suspect this would resolve the issue.

**Comment by afercia** [comment]
@youknowriad yep adding a checked attribute seems to fix it, see the PR.
