### ISSUE TITLE
How to tell if the current block state is the result of a history operation or not.

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#14357]
Is there a way to differentiate between changes happening to a block's state as a result of a redo/undo operation rather than direct manipulation (using it's interface)?

*Having an attribute like isInternalChange that is set to `true` only by internal state changes, is not an option in my case, as I have reserved this for determining other kind of behaviour in my block and would conflict with that logic.

**Comment by youknowriad** [comment]
There's no way to determine that AFAIK.

**Comment by amyriounis** [comment]
@youknowriad Thanks, I was hoping I could somehow determine it by user's last action or something of that sort. I'm closing this for now.
