### ISSUE TITLE
Latest Comments block: Can't center align

### ISSUE THREAD

**Issue by codebykat** [WordPress/gutenberg#14358]
**Describe the bug**
Centering this block in the editor shows correctly in the preview, but on the front-end it is still left-aligned.

Right-aligning the block in the editor does not right-align it in either the editor preview or the front-end.

This block seems to get the class `aligncenter` added to it regardless of the editor settings.

**To Reproduce**
1. Add a Latest Comments block
2. Center it and publish the post
3. Note that it is centered in the editor, but not the front-end
4. Right-align it and update the post
5. Note that it appears left-aligned both in the editor and the front-end

**Expected behavior**
Alignment options should work and the front-end view should match the editor preview.

**Screenshots**
Centered in editor:
<img width="561" alt="Screen Shot 2019-03-09 at 11 03 10 AM" src="https://user-images.githubusercontent.com/52152/54075455-4f803880-4254-11e9-90d7-e9818b486d6c.png">
Front-end display:
<img width="826" alt="Screen Shot 2019-03-09 at 11 03 16 AM" src="https://user-images.githubusercontent.com/52152/54075459-5eff8180-4254-11e9-8324-287914337ec4.png">
Right-aligned in editor:
<img width="580" alt="Screen Shot 2019-03-09 at 11 13 01 AM" src="https://user-images.githubusercontent.com/52152/54075461-658df900-4254-11e9-8fda-04f58a41da11.png">

CSS in inspector:
<img width="458" alt="Screen Shot 2019-03-09 at 11 11 16 AM" src="https://user-images.githubusercontent.com/52152/54075462-69218000-4254-11e9-9cad-c8a6970273b8.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox

**Comment by Jackie6** [comment]
Hi @codebykat I cannot reproduce the bug. Has the bug been fixed?

**Comment by liloo2040** [comment]
Hi! I think I have found why it doesn't work.

Try to work with it your css file. 

Just write `.aligncenter{
text-align: center;
}`
or 
`.alignright{
text-align:right;`.

I hope it helped you!

**Comment by codebykat** [comment]
This was on the Gutenberg Docker env, so it looks like the theme is Twenty Nineteen.

Just re-tested. Right align seems to be working now, but center still fails to center:

<img width="571" alt="Screen Shot 2019-04-25 at 8 54 03 PM" src="https://user-images.githubusercontent.com/52152/56782517-5a5b4200-679c-11e9-9d3c-df6361f6bcee.png">

<img width="632" alt="Screen Shot 2019-04-25 at 8 53 58 PM" src="https://user-images.githubusercontent.com/52152/56782519-5f1ff600-679c-11e9-8c50-63bb0afc7341.png">

**Comment by codebykat** [comment]
Oh, nevermind, I was just testing with the Latest Posts block (which might have a bug where it can't be aligned center)?

Latest Comments alignment seems to work now. 🎉
