### ISSUE TITLE
Media & Text: Content area and formatting tools width

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#14360]
**Describe the bug**

**To Reproduce**
1. Click on Add New Post.
2. Insert `Media & Text` block.
3. Notice the width of the content area and formatting tools.

**Expected behavior**
I expected the width of text input field to match or exceed the formatting tools width, in order to prevent it from extending beyond the block boundaries, or covering the Media section.

**Screenshots**

<img width="678" alt="Screenshot 2019-03-09 at 12 39 00" src="https://user-images.githubusercontent.com/1182160/54076396-82342c00-4268-11e9-80d8-3884617d1c1f.png">

<img width="652" alt="Screenshot 2019-03-09 at 12 42 39" src="https://user-images.githubusercontent.com/1182160/54076439-de974b80-4268-11e9-94b6-db4b48eeaae0.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 72.0.3626.119

**Comment by mapk** [comment]
I don't think this is necessarily an issue. While there are explorations around collapsing the toolbar items, having a toolbar that extends beyond the block isn't bad. Thanks for raising this though!
