### ISSUE TITLE
Core data store `getEntityRecords` selector throws "Actions must be plain objects" error

### ISSUE THREAD

**Issue by noahtallen** [WordPress/gutenberg#14363]
**Describe the bug**
When utilizing the Gutenberg core data store from a Wordpress plugin, the `getEntityRecords` selector fails with the error "Error: Actions must be plain objects. Use custom middleware for async actions." I'll show code, as that will be the easiest way to describe this 😉

```js
import { withSelect, withDispatch } from '@wordpress/data';
...
export default compose( [
  withSelect( select => {
    return {
      // This line right here:
      foos: select( 'core' ).getEntityRecords('postType', 'foo'),
    };
  } ),
 ...
] )( FooContainer );
```
**Important note I am consuming core data & data via the npm packages. So in my entry file, I import core data like so to register it:**
```js
import '@wordpress/core-data';
import { registerStore, combineReducers } from '@wordpress/data';
// Registration of my own store, etc
```
I do not access any of the core-data from the global `wp` variable. When inspecting my plugin in the browser with the redux dev tools, I see that the core-data store and my own stores are being registered successfully.

When I do access core-data from the global `wp` variable, this particular call seems to work correctly.

Interestingly, this all started when I tried to integrate `@wordpress/notices` just through npm (and with an import in my entry file). When I did `dispatch( 'core/notices' )`, it couldn't find that store even though it shows up in the redux manager. (it said it couldn't read a property of undefined.) So my guess was that notices is trying to register the store on `@wordpress/data` and not on the `wp.data` global which I was using to register my own store. So I tried to switch all of my uses of the data module to be consumed via the npm package instead. And that's how I ended up here :P 

I am, though, confused as to why this particular error does not happen when consuming everything via the `wp.data` global. The entire stack trace is:

```
Uncaught (in promise) Error: Actions must be plain objects. Use custom middleware for async actions.
    at Object.performAction (<anonymous>:1:34471)
    at y (<anonymous>:1:36743)
    at e (<anonymous>:1:40562)
    at promise-middleware.js:22
    at Object.dispatch (resolvers-cache-middleware.js:45)
    at _callee2$ (namespace-store.js:355)
    at tryCatch (wp-polyfill.min.js?ver=7.0.0:3)
    at Generator.invoke [as _invoke] (wp-polyfill.min.js?ver=7.0.0:3)
    at Generator.t.(:8082/wp-admin/anonymous function) [as next] (http://localhost:8082/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=7.0.0:3:25481)
    at asyncGeneratorStep (asyncToGenerator.js:3)
```
I was able to narrow it down to `getEntityRecords` by removing various functionality until it was the only line of code left. Removing the call to `getEntityRecords` makes the error go away.

So, the function itself does exist, the data module just doesn't want to use it(?).

I'd appreciate any guidance on this issue, and would be interested in opening PRs for code and/or documentation to help solve it :) 

**To Reproduce**
Try consuming core-data & the data module from npm and utilizing a basic getEntityRecords selector.

**Expected behavior**
The selector should work as expected, or throw a more specific error.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: any

**Additional context**
- Gutenberg Plugin: v5.2
- Wordpress: v5.1
- "@wordpress/core-data": "^2.1.0"
- "@wordpress/data": "^4.3.0"

**Comment by youknowriad** [comment]
Using core-data requires you to setup the `controls` plugins.

```
import { plugins } from '@wordpress/data';

registry.use( plugins.controls );
```

Good luck

**Comment by noahtallen** [comment]
Thanks @youknowriad! I'll submit a PR to the docs which notes that you need to do this.

I wonder if it would be possible to throw a more descriptive error in this situation - e.g. "The control plugin should be enabled to use this action"

**Comment by davepies** [comment]
I just ran into the exact same issue using the following package-versions:

-   Gutenberg Plugin: v5.2
-   Wordpress: v5.1
-   "@wordpress/core-data": "^2.2.2"
-   "@wordpress/data": "^4.4.0"

The suggested fix that @youknowriad kindly documented didn't work:

Store:
```javascript
import '@wordpress/core-data';
import { registerStore, combineReducers, plugins, use } from '@wordpress/data';
use( plugins.controls );
// ...
```

Container-Component:
```javascript
import { withSelect } from '@wordpress/data';
//...
```

This causes the exact same error as above.

Using `global.wp.data.withSelect` also works.

**Comment by noahtallen** [comment]
Howdy Dave! I ended up using the global script instead of importing with npm. Perhaps it would work if you called `use` directory on the created store? Not quite sure how that works.

**Comment by davepies** [comment]
Thanks for that Noah! 

I ended up using the globals too. It looks like that is the way it's intended to being used.
