### ISSUE TITLE
Button disappears in JetPack post email

### ISSUE THREAD

**Issue by reneedobbs** [WordPress/gutenberg#14376]
When a new post has a button and the post is published, the subsequent post notification email sent via JetPack does not display the button (there but invisible/transparent).

**To Reproduce**
(Must have JetPack setup to email new posts)
1. Create new post with button
2. Publish post
3. Check email to see if button appears in it.

**Expected behavior**
Button does not show in email.

Red button in post:
![Post button](https://user-images.githubusercontent.com/45937852/54146003-6f0a9300-4405-11e9-8cae-b1ff931c547a.jpg)

No red button in email:
![email button](https://user-images.githubusercontent.com/45937852/54146043-85b0ea00-4405-11e9-906f-c097f7d916c7.jpg)

**Comment by swissspidy** [comment]
This is probably a bug in Jetpack, not Gutenberg.

**Comment by reneedobbs** [comment]
Ah, okay. Will report it on the JetPack support forum.

**Comment by youknowriad** [comment]
Closing here, thanks.
