### ISSUE TITLE
How to implement flexibile content with Gutenberg shortcode block?

### ISSUE THREAD

**Issue by Ghost180195** [WordPress/gutenberg#14379]
With old content editor I can do such things:

![image](https://user-images.githubusercontent.com/31181880/54152748-cc333280-445f-11e9-84ac-66fb928421b0.png)

As you can see in content I have some paragraphs, heading text and link or even some images.

How can I implement such a thing with Gutenberg shortcode block?

**Comment by swissspidy** [comment]
Related: #12235

> How can I implement such a thing with Gutenberg shortcode block?

As far as I can tell there is none. Your best bet is to use nested blocks and not the shortcode block.

**Comment by youknowriad** [comment]
Yes, the shortcode block is not meant for these usecases. The options are:

 - Rewrite these shortcodes to blocks
 - Just use your shortcode inside the classic block.
