### ISSUE TITLE
Is it possible to add anchor to only specific part of block not whole block??

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#14385]
Hello,

I am one of the developer of Ultimate ad don's for Gutenberg , Convert Plus, Astra, Convert Pro, UAEL etc. 

Regarding this ticket - https://github.com/WordPress/gutenberg/issues/14372

We have a question that is it possible to add anchor to only specific part div, tags etc of block not whole block?

Refer this syntax- 
`var supports = {
  className: false,
  anchor: true
};`

If we add anchor in save function then it directly changes the block id. 
Refer this screenshot - https://monosnap.com/file/DwvLNPLXFhInYmTp2RHqxh6PLT6q9K

We do not want to change block id instead, we just want to assign this anchor to any tag **(hx, div )** of inside block . Is this possible?

Currently, we managed to assign a anchor compatibility to header using **headingId** - https://monosnap.com/file/UVZp2T4joFVLXM7YsixudWyk235U13

Is there any other way where we could assign anchor directly to tags inside block not whole block?

Also, as we can easily assign **`props.className`** to any div inside the block , similarly can we assign  `attributes.anchor` to any div?

Any help will be appreciable.

Regards,
Prajakta.

**Comment by youknowriad** [comment]
It is possible, just build your own anchor control in the inspector with your own block attribute without relying on the `support: { anchor: true } }` config. It should be simple enough.
