### ISSUE TITLE
File Block: "Copy URL" button copies the entire block HTML, instead of the file URL

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#14392]
**Describe the bug**

The File Block contains a button to "Copy URL". This button currently does not copy the URL to the file, but it instead copies the HTML for the entire block. 

**To Reproduce**
1. Add a File Block
2. Upload a file
3. Click the "Copy URL" button
4. Paste the copied text.
5. See error.

**Expected behavior**

I expected that only the file's URL would be copied to the clipboard. 

**GIF**

![copy-url](https://user-images.githubusercontent.com/1202812/54221232-785d3380-44c9-11e9-89bf-090a697eb903.gif)

**Comment by kelin1003** [comment]
I followed the steps to reproduce and it works fine on my end. Can you provide a bit more information about your setup?

**Comment by kjellr** [comment]
Ah, interesting — I'm still able to reproduce in a clean install of WordPress 5.1.1, but it looks like this may be fixed on master.
