### ISSUE TITLE
Media & Text: Insert from URL

### ISSUE THREAD

**Issue by codebykat** [WordPress/gutenberg#14397]
The Media and Text block is missing the "Insert from URL" option which is present in the Image block:

<img width="733" alt="Screen Shot 2019-03-12 at 2 52 12 PM" src="https://user-images.githubusercontent.com/52152/54238905-f3791680-44d6-11e9-8eb9-c3b2598dce49.png">

Originally reported here: https://github.com/Automattic/wp-calypso/issues/31399

Related: https://github.com/WordPress/gutenberg/issues/1536

**Comment by reneedobbs** [comment]
Just requesting this to be fixed soon. Please. Thank you!

**Comment by webmandesign** [comment]
+1 from me.
Would be great if this was implemented somehow (even after reading [@carolinan comment](https://github.com/WordPress/gutenberg/issues/42264#issuecomment-1178913763))

**Comment by richtabor** [comment]
> This feature used to exist but needed to be removed because there was no way to detect if the remote media was a video or image (I have no technical details of why). See https://github.com/WordPress/gutenberg/pull/19606.

Per @carolinan's comment, I suggest we close this as not planned. An alternative would be to use a columns, row, or grid block with the standard Image block.
