### ISSUE TITLE
Gutenberg site-wide options are stored by saving post

### ISSUE THREAD

**Issue by louiswolf** [WordPress/gutenberg#14396]
Gutenberg options behave unexpectedly from the user perspective: you can disable various 'panels' and save these settings by saving the post. However, these options are not specific to that post, but change behavior throughout the website.

In my opinion there are three 'solutions':
- The Gutenberg options dialog should have it's own save-button
- The Gutenberg site-wide options should be moved to their own settings page
- These Gutenberg site-wide options should be part of the _writing_ settings page.

![gutenberg-options](https://user-images.githubusercontent.com/2388796/54233374-1cb49980-450d-11e9-825f-4359a598d2eb.png)

**Comment by youknowriad** [comment]
Noting that these are not saved when you save the post, these are saved as soon as you change them.

**Comment by louiswolf** [comment]
Ah, interesting. In that case I think this would already be greatly improved with some visual feedback like a spinner and/or message on top of the dialog.

**Comment by kjellr** [comment]
This seems a bit analogous to the "Screen Options" settings in the classic editor: 

<img width="1099" alt="Screen Shot 2019-03-19 at 2 45 22 PM" src="https://user-images.githubusercontent.com/1202812/54633005-ac9a9c00-4a55-11e9-9a99-4c761d5f5979.png">

Those did not include a save button either. My gut says that it's okay to leave this as is, but I'm curious what others think. @mapk and I have been chatting a bit about the function of checkboxes in the Block Manager modal too, so looping him in here too.

**Comment by mapk** [comment]
Thanks for looping me in, @kjellr! I don't mind where these options exist right now, but the feedback to the user is something that still bothers me a bit.

Can we look into providing textual feedback to the user that the checkbox state has been saved? Something like below:

![options](https://user-images.githubusercontent.com/617986/54646916-e40d4680-4a5d-11e9-8dbb-1f385ceef44d.gif)

_The timing of the msg and fading is all off, but should provide something to talk about here._

**Comment by kjellr** [comment]
👍 That could be cool! I'd be up for trying that.

**Comment by karmatosed** [comment]
I am removing the 'User Experience (UX)' label as part of a label cleanup. It's not being used anymore consistently so let's try and keep to 'needs design' and 'needs design feedback'. If we find a need for another label we can consider it but having those 2 should cover this.

**Comment by joyously** [comment]
I prefer the previous Screen Options interface, as it lets me see the changes as I make them, whereas the overlay hides things I'm changing.

**Comment by skorasaurus** [comment]
I can confirm that this behavior no longer exists; site-wide options (now known as preferences) save immediately after toggling them.  (there is no notice that the changes have been saved however). 

Please reopen if you are still experiencing this.
