### ISSUE TITLE
Use Gutenberg to create an HTML template

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#14394]
Hi there!

I'm building a custom newsletter plugin for my business. I would like to have an HTML template editor included in it. Currently, I have a metabox with a `textarea` input where the user can enter his or her HTML code for the template. I thought it would be more user-friendly to have a drag-and-drop interface. I have seen that a lot of plugins achieve this with third-party libraries. However, I was wondering if it would be possible to achieve something like this with Gutenberg.

I read issues https://github.com/WordPress/gutenberg/issues/13142 and https://github.com/WordPress/gutenberg/pull/13088, but I didn't find any documentation in the handbook on how to achieve this. I was hoping you could point in the right direction.

Thanks!

Hernan

**Comment by noisysocks** [comment]
Hey @chvillanuevap!

The work being done in https://github.com/WordPress/gutenberg/pull/13088 is indeed intended to make it easier to re-use the Gutenberg block editor for more purposes than simple post and page editing. 

This work is in very early stages and so there is no documentation for the block editor module at this time. There is a follow-up task to add documentation in https://github.com/WordPress/gutenberg/issues/14043, so watch this space!
