### ISSUE TITLE
alternative to edit_form_top, or how to add some HTML anywhere on post-new.php

### ISSUE THREAD

**Issue by karimhossenbux** [WordPress/gutenberg#14401]
We were using `add_action('edit_form_top'` to add a button before the title on the classic editor.

I was trying to replicate this in Gutenberg with the newly added actions, but without any success. I'm not really sure what to look for in the documentation.

Can someone put me in the right direction please? I'm trying to add some basic HTML (button+modal) on the post-new.php page, it could be anywhere actually (as the button can have a `position:fixed;` on the page)

thank you!

**Comment by youknowriad** [comment]
Hi There! In Gutenberg we moved away from position-based extensibility APIs into semantic-based APIs because position-based APIs means each time you change the layout of the screen, these are going to break.

Can you describe more what is this button about, so I can try to find an alternative for you?

**Comment by karimhossenbux** [comment]
Thank you for the the quick answer!

The button will open a modal with some "base" post for the author to select from. Until this is not selected, an overlay over the editor will be displayed all over the editor/page to avoid the author to write content.

Once selected, it will set the post title and a custom metabox image field (not the featured image one).

Does it help?

**Comment by youknowriad** [comment]
You have different options here:

The first one is to use a sidebar plugin: See tutorial here https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/plugin-sidebar-0/ In this tutorial you can replace the sidebar by a modal component. But if you use a sidebar, your plugin will have the possibility to be pinned in the toolbar of the editor (see yoast for instance)

An alternative which might be better is to prefill the editor with a dummy block, that allows the user to pick content. This dummy block won't render anything, but picking content will replace it. To prefill the editor with blocks, see the templates documentation https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-templates/

I hope this helps.

**Comment by karimhossenbux** [comment]
Thank you for the help!
