### ISSUE TITLE
Sticky Notices overlap Classic Editor toolbar on scroll

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#14402]
**Describe the bug**
When editing a page with long content in the Classic Block the classic editor toolbar becomes sticky and follows you down the block. When you have sticky notices they overlap this toolbar on scroll requiring you to dismiss the notices to be able to edit.

**To Reproduce**
1. Go to the block editor
2. Add a Classic Block
3. Fill the contents with lengthy copy (privacy policy content for instance)
4. Save the post, and reload.
5. Make additional changes, pause, and reload to trigger the 'autosave' notice.
6. Scroll down the Classic Block, find it's editor toolbar becomes hidden behind the sticky notice.

**Expected behavior**
Not quite sure the best approach here but possibly have the toolbar pushed down below the notices so it becomes available. Or while the block is in focus being edited place it at a higher z-index than the notices so it becomes fully editable.

**Screenshots**
<img width="1091" alt="Screen Shot 2019-03-13 at 3 11 51 AM" src="https://user-images.githubusercontent.com/8726005/54271122-24406680-453e-11e9-8481-1d80d796531e.png">
<img width="1095" alt="Screen Shot 2019-03-13 at 3 12 31 AM" src="https://user-images.githubusercontent.com/8726005/54271123-24406680-453e-11e9-9d78-9cbc7629cfa0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.11.6
 - Browser Chrome 72.0.3626.121

**Additional context**
- I believe it's 5.2 that's currently in trunk as I'm working on WP 5.2 tickets

**Comment by youknowriad** [comment]
Noting that this is not specific to the classic block, it's the same for all blocks. Pushing down the toolbar is not possible because these are rendered in very different contexts. Not sure what we can do here. We can play with "z-index" but I feel what we have now is a fine compromise. Thoughts @jasmussen

**Comment by garrett-eclipse** [comment]
Thanks @youknowriad 

I had another thought on this last night. I wonder if the dismissable sticky notifs can have two action icons. The close that's there but a minimize as well that's beside the close. When minimized it slides to the left leaving just a tab in the notice colour. Hover on the tab and it displays some of it and clicking expands again so you can then read or dismiss it.

Thoughts?

**Comment by youknowriad** [comment]
I agree that these notices need to be improved. I think if we take a look at the kind of notices we have, we can distinguish two:

 - One type like the "autosave" one which should probably be read and closed while the post is loaded. I think these should stay as is (or not change that much as reading them is important for the user).

 - The second type is more about "timely" notices: save notices, reusable block notices... I think for these notices, we should revisit their design. Something like the Snackbar Material UI component makes more sense for me. https://material-ui.com/demos/snackbars/

I think there might be another issue talking about this kind of improvements, if we find the issue, we should close this one as a duplicate.

**Comment by garrett-eclipse** [comment]
Nice, those snackbars are yummy. And the bottom positioning I feel will work better to avoid interfering with block toolbars and editing in general.

**Comment by youknowriad** [comment]
Looks like I found the issue #13905 let's consolidate there.
