### ISSUE TITLE
Video block should have playsinline option

### ISSUE THREAD

**Issue by t-wright** [WordPress/gutenberg#14422]
**Is your feature request related to a problem? Please describe.**
The `core/video` block has an  'autoplay' option along with options to hide controls, mute and loop the video. These settings would make this block useful to display gifs in a more efficient video format, for instance. However for autoplay to work on mobile devices the `playsinline` attribute is also required on the `<video>` element. Currently if you enable autoplay and hide controls, the video is not playable on mobile devices. 

**Describe the solution you'd like**
Would be great to have a 'playsinline' option on this block or perhaps add the attribute to the markup automatically if controls are hidden and autoplay is selected. 

**Describe alternatives you've considered**
For the time being I'm adding this with attribute through a `the_content` filter but would be better if it was controllable through the editor.

**Comment by nfmohit-wpmudev** [comment]
Submitted #14500 which addresses this enhancement ❤️

**Comment by t-wright** [comment]
Thanks @nfmohit-wpmudev!

**Comment by planetahuevo** [comment]
Is this working on the cover background video? has this been deployed into core? 
Thanks!

**Comment by StefanXhunga** [comment]
Together Thank you
