### ISSUE TITLE
Tags disappear after updating posts 

### ISSUE THREAD

**Issue by berke11** [WordPress/gutenberg#14428]
When I am trying to update my existing posts, somehow after updating text, tags of the posts disappear even I do not touch them.

**To Reproduce**
1. Go to published post (with tags)
2. Click on 'Edit Post'
3. Add something inside your post
4. Update the post
5. See that there are no tags inside post

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.3
 - Browser Safari
 - Version 12.0.3

**Additional context**
- Wordpress 5.1.1
- I think it came after new editor.

**Comment by youknowriad** [comment]
Can I ask which theme are you using? There's a known bug for themes based on o2 (p2) causing this. Also curious how many tags do you have in your database?

**Comment by berke11** [comment]
I am using Collecto theme (v: 1.1.1.) of Themes Kingdom. This is the link for theme: https://themeskingdom.com/wordpress-themes/collecto-simple-magazine-wordpress-theme/

And this is my website: https://www.berkeozkok.com/

**Comment by katiebethbrown** [comment]
Another report in 17130673-hc, using the Journalistic theme.

**Comment by ehti** [comment]
@berke11 We tested this during editor triage today.

None of us were able to reproduce it, which likely means it's specific to that theme. If you're able to reproduce this on a default theme with no plugins, please post here and it can be re-opened.

Thanks!
