### ISSUE TITLE
Storing a String attribute and Editing it using a TextControl should not show HTML entities, but it does

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#14427]
**Scenario**

I have created a block that has an attribute like this:

```
author: {
  type: 'string',
  source: 'html',
  selector: '.author',
},
```

which is stored as follows:

```
save: props => {
  …
  const { author } = props.attributes;
  return (
    …
      <span class="author">{ author }</span>
    …
  );
}
```

and is edited using a `TextControl`:

```
<TextControl
  className="author"
  value={ author }
  onChange={ value => setAttributes( { author: value } ) }
  placeholder={ __( 'Add Author', 'nelio-blocks' ) )
/>
```

**The problem**

If I set the author to something like _David & Co_, this is stored as `David &amp; Co` (that is, _&_ is escaped to `&amp;`).

When I reload the post and the block is rendered in the editor, the value it pulls is `David &amp; Co` and so the `TextControl` shows _David &amp;amp; Co_ instead of _David & Co_.

Does anybody know how to address and fix this issue?

Thanks!

**Comment by youknowriad** [comment]
For security reasons, This `<span class="author">{ author }</span>` automatically escapes the HTML content. 

I think you can do

```
author: {
  type: 'string',
  source: 'html',
  selector: '.author',
},
```

which is stored as follows:

```
save: props => {
  …
  const { author } = props.attributes;
  return (
    …
      <span class="author">{ decodeEntities( author ) }</span>
    …
  );
}
```

and is edited using a `TextControl`:

```
<TextControl
  className="author"
  value={ decodeEntities( author ) }
  onChange={ value => setAttributes( { author: encodeEntities( value ) } ) }
  placeholder={ __( 'Add Author', 'nelio-blocks' ) )
/>
```

you need to find good implementations for decode/encodeEntities used above.

**Comment by davilera** [comment]
Thanks for your help, @youknowriad, but I think I found a better solution.

Instead of registering the attribute as follows:

```
author: {
  type: 'string',
  source: 'html',
  selector: '.author',
},
```

One has to register it using the `'text'` _source_:

```
author: {
  type: 'string',
  source: 'text',
  selector: '.author',
},
```

I guess the keyword _source_ made me think that, in order to pull an attribute from the HTML, _source_ has to be set to `'html'`... but apparently that's not the case. So there you go!
