### ISSUE TITLE
Spacer NaN warning

### ISSUE THREAD

**Issue by gregbia** [WordPress/gutenberg#14426]
If clearing the number input for the spacer block, we get a `"NaN" is not a valid number` console error. On save and refresh a block validation failed message shows.

![image](https://user-images.githubusercontent.com/39787658/54344993-7ce43200-4618-11e9-8192-22e205699c18.png)

![image](https://user-images.githubusercontent.com/39787658/54344851-31ca1f00-4618-11e9-8ec1-5657cc137876.png)

Version: WP 5.1

**Comment by kelin1003** [comment]
I see this happening in my local env as well, I'd like to take this issue if possible.
How do we want to proceed? Do we want some minimum height for spacer or 0 is fine?

**Comment by swissspidy** [comment]
A spacer with height 0 might be impossible to select/click on, so a sensible default might make sense. Needs testing though.

**Comment by kelin1003** [comment]
Yes with height 0 the spacer can't be selected unless using tabs or arrows.
Currently we have minimum value set at 20 for the input box.
