### ISSUE TITLE
How to add the editor inserter

### ISSUE THREAD

**Issue by gregbia** [WordPress/gutenberg#14424]
On some blocks using inner blocks I noticed that an inserter appears (screenshot below) and on other the placeholder "start writing or type/ to use block" shows. Why is that?

Also is there any way to add the editor inserter to any block I want, as in the screenshot below? The inserter is included in the handbook but there is no documentation for it: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-block-editor/#inserter

![image](https://user-images.githubusercontent.com/39787658/54342282-705cdb00-4612-11e9-8ee8-8dc79fdcb355.png)

**Comment by youknowriad** [comment]
If your innerBlocks area don't support the "paragraph" block, the inserter is shown like the screenshot above. #14241 is trying to make it available using an "opt-in" prop.
