### ISSUE TITLE
Wrong video size in the editor

### ISSUE THREAD

**Issue by PeopleInside** [WordPress/gutenberg#14421]
**Describe the bug**

Video are showed in not real version in the new Gutenberg editor:
![00](https://user-images.githubusercontent.com/5006150/54312801-1b03d800-45d8-11e9-9178-b0e05c62a156.png)

The correct look is in the Classic editor:
![01](https://user-images.githubusercontent.com/5006150/54312812-2525d680-45d8-11e9-9396-6bcec3a4fc2d.png)

**To Reproduce**
Simply have a video in the editor

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 65.0.2

**Comment by sbardian** [comment]
Was looking into this, the editor appears to display the video with the correct size, but after publishing the videos are all the same size because of the following css: 
.entry .entry-content .wp-block-video video {
    width: 100%;
}

changing this to the following would fix this issue: 
.entry .entry-content .wp-block-video video {
    width: auto;
}

but I have not yet found how to do this. . . 

### While editing: 
![image](https://user-images.githubusercontent.com/6384100/54484669-9069e580-4830-11e9-96ed-9623699b8dbf.png)

### Viewing page
![image](https://user-images.githubusercontent.com/6384100/54484682-d6bf4480-4830-11e9-86d9-e4a6721c8311.png)

**Comment by PeopleInside** [comment]
The issue of the video size in the Gutenberg editor seems to be related to:

```
.block-editor__container iframe {
    width: 100%;
}
```

If i remove the  width: 100%; the issue is resolved.

**Comment by sbardian** [comment]
Maybe I was looking at the wrong editor.  I was just editing a page and inserted a video block.  Feel free to ignore my previous comment if so. (y)

**Comment by PeopleInside** [comment]
I removed Gutenberg come back to classic editor. Gutenberg is not working

**Comment by marcus-hiles** [comment]
Wow, really @PeopleInside? what else isn't working for you, apart from the issue you reported?

**Comment by PeopleInside** [comment]
Video is not working, the size of the editor is wrong. I need install additional plugin and put hands on code for have the standard editor working? I really don't like Gutenberg.

**Comment by marcus-hiles** [comment]
Oouch @PeopleInside, seems like it's giving you hell. 
I've used it before it worked awesomely well. What version of wordpress are you using though?

**Comment by PeopleInside** [comment]
The last one.

**Comment by marcus-hiles** [comment]
@PeopleInside If its wordpress 5, then I noticed they have a few issues with it, they are working on. This normally happens with software upgrade.
You can report your issues here : https://wordpress.org/support/plugin/gutenberg/, so it can be fixed included in their next release.

**Comment by PeopleInside** [comment]
I done. See my previous message. Issue has been closed without a fix.

**Comment by marcus-hiles** [comment]
@PeopleInside Hmmm, I checked your comments here #14405. I think you are right the Gutenberg editor shouldn't be forced on us, we should be given the option to choose Gutenberg or use any other editor. That's putting the user's preferences and needs first, since user's contribute mightily to software growth and popularity.

**Comment by PeopleInside** [comment]
Yes sound strange Gutenberg has been forced... and give a lots of problems. And also from review people are not happy... and i want upgrade but too many issue... i cannot understand the sense to introduce an editor that cause issue. Anyway this is off-topic. I am here just because i tried to move to Gutenberg but still have issues and issues and issues.

**Comment by PeopleInside** [comment]
Any news about this issue?

**Comment by PeopleInside** [comment]
Someone in Wordpress has decided to force the use of this editor as standard.
The video size are showed wrong and this issue is kept open without updates also if i asked for months...

How i can use this editor if show in wrong size videos?
I cannot love this editor, i can't...

**Comment by glendaviesnz** [comment]
@PeopleInside I wasn't able to replicate this in the latest gutenberg editor build - when embedding a video in the classic block, and with the video embed block, they display at full width in the editor and the front end:

<img width="606" alt="video-width" src="https://user-images.githubusercontent.com/3629020/85956270-028c1c80-b9d9-11ea-9e23-209e83028cc6.png">

If you are still having problems with this can you please confirm which version of WordPress/Gutenberg you are now running, and which theme you have active when you see this problem, thanks.

**Comment by PeopleInside** [comment]
How it looks in the page?
Same size?
This is screen from editor.

**Comment by PeopleInside** [comment]
I still have this issue, never resolved.
I see support topics on WordPress about this plugin never get replies as this topic too, no replies from the team.
No solutions since 2019

https://wordpress.org/support/topic/wrong-video-size-in-the-editor/

The issue is caused by https://it.wordpress.org/plugins/tinymce-advanced/

**Comment by jordesign** [comment]
Looping back to this issue - and the fact it should be solved in Gutenberg itself.

> The issue is caused by https://it.wordpress.org/plugins/tinymce-advanced/

Just to confirm @PeopleInside  - does the issue only occur when you are using that plugin?

**Comment by PeopleInside** [comment]
Maybe the issue is resolved now, thanks
