### ISSUE TITLE
Gallery: add support for optional captions

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1443]
Individual images should have optional captions.

**Comment by janw-oostendorp** [comment]
A note, if you edit a gallery with the pencil you get the option  in the normal gallery edit. It's just unused.

**Comment by karmatosed** [comment]
This was discovered during @helen's trip into Gutenberg:

>  I can't edit captions on an inserted gallery? And adding captions to a new gallery doesn't actually show anything? Weird.

Here you can see a video of what I recreated (assuming it's the same thing)

![2017-08-03 14 35 53](https://user-images.githubusercontent.com/253067/28924361-60ce92a6-7859-11e7-96a6-a2a52504c90d.gif)

**Comment by mtias** [comment]
This is how inline captions could work:

https://user-images.githubusercontent.com/548849/28015550-5db412fc-6568-11e7-88e6-fca2029ca159.png

**Comment by Axinet** [comment]
It would be great if it could be possible to add a caption to the whole gallery under it (the same as for a singular image - there could be all images related to one thing) or as this ticket suggests for every image in the gallery (in my opinion default/demo style should match with single image styles).

**Comment by jorgefilipecosta** [comment]
Captions were added to the gallery in PR https://github.com/WordPress/gutenberg/pull/4199.
