### ISSUE TITLE
How can I get the latest version of react?

### ISSUE THREAD

**Issue by rebmullin** [WordPress/gutenberg#14438]
I looked around but I am not able to find how to get the most current version of react. I am on the latest Wordpress and when I use `wp.element` it seems to load react `v16.6.3`. I would like use the latest react version so I can integrate hooks:) 

Can anyone help with this or point me to a reference? 

thanks so much!

**Comment by youknowriad** [comment]
The lastest version of React was just merged in the Gutenberg plugin, it will be available in the WordPress 5.2 release.
