### ISSUE TITLE
Duplicated first Chinese word when typing

### ISSUE THREAD

**Issue by theturtle626** [WordPress/gutenberg#14434]
**Describe the bug**
Duplicated first Chinese word

**To Reproduce**
1. New  post
2. New phrase
3. Input Chinese, the first word will be duplicated.

It looks like this

case 1. 好好的 .... 
In this case "好" is duplicated automatically.

case 2.機基本上 ....
In this case "機" is the same sound with "基", and auto-input by gutenberg.

**Comment by ellatrix** [comment]
I can reproduce this for French:

![first](https://user-images.githubusercontent.com/4710635/54369614-87351900-4676-11e9-9f98-1fc060f7218c.gif)

It only happens for the first character inserted.

**Comment by ellatrix** [comment]
It doesn't happen if there's already content in the paragraph.
