### ISSUE TITLE
How to run slick carousel with in block editor when using server render

### ISSUE THREAD

**Issue by farookibrahim** [WordPress/gutenberg#14431]
I added a block which uses slick carousel, i am using $(.element).slick(); to trigger slick with in a script.js file and enqueued both script.js and slick.js in frontend. It works fine on frontend.

For editor i enqueued the both files with in "enqueue_block_editor_assets" however in editor it does not work. Is there any approach to use slick or owl carousel with in editor(server render) ?

**Comment by swissspidy** [comment]
It would be really helpful if you could share your code here.

Please note though that this type of question is better asked at https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/

**Comment by farookibrahim** [comment]
Hello @swissspidy,

Thanks for your reply. I posted this question in WP Support form.

Ref: https://wordpress.org/support/topic/how-to-use-slick-or-owl-carousel-with-in-block-editor-when-using-server-render/
