### ISSUE TITLE
Paragraph tags are getting stripped

### ISSUE THREAD

**Issue by pcgeek86** [WordPress/gutenberg#14442]
**Describe the bug**

I've been using Gutenberg successfully for a few months now. Today, when I preview or publish a post, written in the Gutenberg editor, the HTML `<p>` tags are getting stripped off. This results in consecutive paragraph blocks being rendered on the same line, because the `<p>` tags are missing from the post. I've attached an animated GIF showing the behavior below.

Right now this issue is essentially blocking me from publishing new content.

**To Reproduce**

1. Create a new post
2. Add two consecutive paragraph blocks
3. Preview or publish the post
4. Notice that both paragraphs appear on the same line, without any line break

**Expected behavior**

Paragraph blocks should be enclosed in `<p>` tags, and those tags should not be stripped off prior to publishing a post.

**Screenshots**

![2019-03-14-WordPress-Gutenberg-Issue](https://user-images.githubusercontent.com/466713/54382093-7a033480-464c-11e9-940f-8041d5165553.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 72

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

- WordPress 5.1.1
- Gutenberg plugin version 5.2.0

Possibly related issues:

- https://github.com/WordPress/gutenberg/issues/11211
- https://github.com/WordPress/gutenberg/issues/3922

**Comment by swissspidy** [comment]
Does this still happen with all plugins disabled and when using one of the default themes?

**Comment by pcgeek86** [comment]
- I changed just the theme to Twenty Twelve, and the problem remained
- I narrowed down the plug-ins to one called JP Markdown, which I haven't been using anyway
