### ISSUE TITLE
Top half of block toolbar unusable for block inserted after a columns block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#14447]
**Describe the bug**
This is potentially a z-index issue, the inner blocks in the column are receiving the click event before the toolbar.

![block-toolbar-z-index](https://user-images.githubusercontent.com/677833/54403189-79cd6c80-4712-11e9-9e2b-41e6610736fe.gif)

I tried to discover where this issue was introduced, it seems as though it's been present for at least a month (I didn't go back any further than that).

**To Reproduce**
1. Start a new post.
2. Insert a columns block.
3. After the columns block insert a paragraph block and type some content.
4. Hover over the top half of the paragraph blocks toolbar (e.g. the bold formatting button).
5. Observe that the columns block displays hover styles.
6. Try to click on a toolbar button.
7. Observe that the columns block is selected

**Expected behavior**
The intended toolbar button was selected

**Desktop (please complete the following information):**
 - Tested in Chrome 72 (Mac OS).

**Additional context**
- Discovered again master (latest commit was https://github.com/WordPress/gutenberg/commit/9a93e6a49fa86805e9e0a8bed6f102787e4d2e36)

**Comment by talldan** [comment]
Unable to reproduce in a more recent version, so closing this.

**Comment by styledev** [comment]
This issue is still happening when you have a column block followed by a block that allows for align-wide or align-full. Once you align wide/full say the cover block you can no longer access to the toolbar.

Here is a video showing the issue: https://www.dropbox.com/s/f5yr8nhw1voi8sr/Column%20%2B%20Wide%20Block%20Toolbar%20Issue.mov?dl=0

**Comment by talldan** [comment]
Yep, I can reproduce that. Thanks for pointing it out. Reopening.

**Comment by youknowriad** [comment]
This seems fixed for me.
