### ISSUE TITLE
Hide Edit Post Sidebar options

### ISSUE THREAD

**Issue by Furiacs** [WordPress/gutenberg#14452]
I need to hide some options on edit-post-sidebar like "change author, move to trash, etc" and I can't find any solution to do this the right way.

I wroted a function to search and hide those elements and I've mapped some events to call this function... it works but I'm having some performance issues.

Can someone help me in this issue?

Thanks

**Comment by Furiacs** [comment]
I guess it's not possible...

**Comment by youknowriad** [comment]
It depends. If your Post Type don't support "authors", the author dropdown won't be shown. Move to trash can't be removed at the moment. Some of these UI elements have dedicated classNames you can use to hide them.

I'm closing right now. but feel free to detail your use-cases and reasoning, why do you want to hide these? If the use-cases are considered valid and we can find a good generic API, we could consider adding extensibility APIs.
