### ISSUE TITLE
Consider having a plain theme pre-installed in the Docker image

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#14454]
Since most of the WordPress default themes now come with editor styles, it might be helpful for this repo's Docker environment to ship with a very plain theme for basic testing purposes.

Something like the [Gutenberg Starter theme](https://github.com/WordPress/gutenberg-starter-theme) may be a good candidate, since it supports full + wide alignments, but includes no Editor Styles.

**Comment by getdave** [comment]
I agree. This is  extremely important to allow devs to develop against an unopinionated Theme. We should require folks to install Docker in a special way to get a blank Starter Theme.

**Comment by youknowriad** [comment]
Looks like we have this now.
