### ISSUE TITLE
Input Interaction: Shift+ArrowUp uncollapsed single-line selection should expand upward

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14463]
**Steps to Reproduce:**

1. Navigate to Posts > Add New
2. Create two paragraphs, each with some amount of text
3. In the first line of the second paragraph, mark a selection using Shift+ArrowRight
   - ![image](https://user-images.githubusercontent.com/1779930/54452555-d38e6080-472b-11e9-814e-213b2b07d5e4.png)
4. Without releasing Shift, press ArrowUp

**Expected Result:**

Selection should adapt corresponding the expected browser + OS behavior of any other multi-line text field. For example, repeat the steps above as two lines in the "Add Comment" section of this GitHub comment box.

_In macOS + Chrome:_ The selection should collapse.
_In all other browsers, OS:_ The selection should expand upward a line. In terms of blocks, I would expect that given the steps above, it would trigger multi-selection to encompass the two blocks.

It's unclear to me, but it seems that as the outlier, the behavior of macOS + Chrome may be buggy for text fields broadly speaking. In which case, "all other browsers" expected behavior may be what we'd want to seek to emulate.

**Actual Result:**

_In macOS + Chrome:_ The selection collapses.
_In all other browsers, OS:_ The selection reverts to the beginning of the line.

![image](https://user-images.githubusercontent.com/1779930/54453031-d2a9fe80-472c-11e9-9f2b-422b70cbcdb0.png)

Noting that this recently seems to have improved (I suspect as of #14453), where previously _nothing at all would happen_ when pressing ArrowUp.

cc @ellatrix

**Comment by ellatrix** [comment]
Ah, I get it now. :)

**Comment by ellatrix** [comment]
@aduth Fixed it in #14487
