### ISSUE TITLE
Is there a way to limit the custom blocks added by the user ??

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14479]
I am creating a custom footer block, and if user adds more than one footer block I need to disallow it. How can i do that??

**Comment by swissspidy** [comment]
There's a [block support](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#supports-optional) property called `multiple`. When registering your block you can define that this block can only be inserted once:

```js
{
  supports: {
    // Use the block just once per post
    multiple: false,
  }
}
```

**Comment by ravishakya** [comment]
Thanks, exactly what I am looking for.
