### ISSUE TITLE
Image embeds are not responsive. Images not attached

### ISSUE THREAD

**Issue by galbaras** [WordPress/gutenberg#14480]
**Describe the bug**
Gutenberg plugin installed pre-WP5.0, then upgraded to 5.0.3, then to 5.1 and 5.1.1.

Posts not updated or converted in any way.

Images embeds not showing "srcset" or "sizes" attributes and images are "unattached" in media library (pretty sure they were before all of the updates).

**To Reproduce**

1. Go to https://www.get-business-online.com/web-presence/how-to-keep-online-business-alive/ and check the markup for the embedded image https://www.get-business-online.com/wp-content/uploads/2014/06/i-ve-been-hacked.jpg

2. Check the image in the library - currently "unattached"

**Expected behavior**

"srcset" and "sizes" attributes, referencing https://www.get-business-online.com/wp-content/uploads/2014/06/i-ve-been-hacked-300x225.jpg, https://www.get-business-online.com/wp-content/uploads/2014/06/i-ve-been-hacked-296x167.jpg and https://www.get-business-online.com/wp-content/uploads/2014/06/i-ve-been-hacked-213x120.jpg.

Also, the respective image should be attached to the post.

**Screenshots**

![image](https://user-images.githubusercontent.com/7981897/54501109-f65c8700-496e-11e9-9d8f-fbe63b562c9f.png)

![image](https://user-images.githubusercontent.com/7981897/54501122-0aa08400-496f-11e9-8587-92bb63f20440.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0.3626.121

**Additional context**

EWWW Image Optimizer
Media File Renamer Auto

See also https://core.trac.wordpress.org/ticket/46470

**Comment by youknowriad** [comment]
By looking at the link above, it looks like the srcset and sizes attributes are their now.
