### ISSUE TITLE
Add line break to Gutenberg

### ISSUE THREAD

**Issue by JanPaulKleijn** [WordPress/gutenberg#14496]
**Is your feature request related to a problem? Please describe.**
Line break makes two `<br>` tags in paragraph, which should be one. (If I want two, I make two line breaks.)
Line break does not work in list.

**Describe the solution you'd like**
The normal line break functionality, shift+enter breaks the line and cursor goes to beginning of new line in the same paragraph. Technically, shift+enter creates ONE `<br>` tag.

**Describe alternatives you've considered**
Alternative now in block editor to add a line break:
- shift+enter
- go to HTML editor
- remove the last `<br>` tag
- go back to visual editor
or:
- go to HTML editor
- type `<br>`
- go back to visual editor

Alternative now in block editor for adding line break in list:
- go to HTML editor
- type `<br>`
- go back to visual editor

**Comment by youknowriad** [comment]
I think this was fixed recently. Which version are you using? cc @ellatrix

**Comment by JanPaulKleijn** [comment]
My version is 5.1.1

**Comment by youknowriad** [comment]
The Gutenberg release 5.3 (meant to be released publicly on Wednesday) includes a fix for this bug. Let's way for confirmation from @ellatrix and close.

**Comment by JanPaulKleijn** [comment]
Let's wait for confirmation if it is solved on Wednesday and if so, then this can be closed, OK?

**Comment by youknowriad** [comment]
you can already try the RC to confirm if it's fixed by installing the plugin from the zip here https://github.com/WordPress/gutenberg/releases/tag/v5.3.0-rc.1

**Comment by JanPaulKleijn** [comment]
It also seems it is **impossible** to break out a secondary list and continue with text on the primary list.
Example:
```
<ul>
  <li>Testing
    <ul>
      <li>testing</li>
    </ul>
    Testing continued
  </li>
</ul>
```

**Comment by JanPaulKleijn** [comment]
I mean, not even possible with the HTML editor, the visual editor messes it up every time.

**Comment by JanPaulKleijn** [comment]
I will check the latest right away, thanks for that.

**Comment by JanPaulKleijn** [comment]
Should I install the Gutenberg.zip as a plugin?

**Comment by JanPaulKleijn** [comment]
I installed it as plugin (good guess) and checked it. It worked as I would like. Apart from the last bit I commented about.

**Comment by JanPaulKleijn** [comment]
Oops, I guess I did not test it thoroughly enough.
Secondary listing goes wrong. Any new item added to secondary list with 'enter' results in a new block being generated. So, FYI.
Perhaps wait till wednesday and after that create a BUG ticket if it doesn't work still?
