### ISSUE TITLE
Abstract away and document advanced constants used in webpack config

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#14492]
The documentation around webpack config has been documented in-depth as explained in https://github.com/WordPress/gutenberg/issues/8982#issuecomment-473894552. 

The last part left is how one can take advantage of global variables to do some advanced work:
- `WP_BUNDLE_ANALYZER`
- `WP_DEVTOOL`
- `WP_LIVE_RELOAD_PORT`

Ideally, those constants should be abstracted with CLI arguments similar to @draganescu did in #14129. In effect, we would be able to run the following, e.g.:
```shell
$ npx wp-scripts build --webpack-live-reload-port=12345 --webpack-bundle-analyzer --webpack-devtool=inline-source-map
```

Example of the existing implementation of similar CLI args for `npx wp-scripts test-e2e`:
https://github.com/WordPress/gutenberg/blob/master/packages/scripts/scripts/test-e2e.js#L46-L65

**Comment by gziolo** [comment]
By the way, it also reminds me that we forgot to document custom CLI args passed to `wp-scripts e2e` - it would be nice to include them as well.

**Comment by Jackie6** [comment]
Hi @gziolo I have created a pull request to update the documentation of wp scripts.

**Comment by gziolo** [comment]
This issue is waiting for volunteers again.

**Comment by gziolo** [comment]
A similar issue was raised on WordPress.org blog:

https://make.wordpress.org/core/2020/02/28/new-wordpress-create-block-package-for-block-scaffolding/#comment-38068

**Comment by gziolo** [comment]
`WP_LIVE_RELOAD_PORT ` won't be promoted to a CLI flag because its future is uncertain. It might get replaces with React Fast Refresh as proposed in https://github.com/WordPress/gutenberg/issues/21008.
