### ISSUE TITLE
Blank page on custom post when using custom capabilities

### ISSUE THREAD

**Issue by luuptekman** [WordPress/gutenberg#14507]
**Preconditions:**
- WordPress 5.1.1 installed
- Custom theme in use

**Steps to reproduce:**
1. Register a custom post type with custom capabilities
Example this is what I have in register_post_type arguments:
`
'capability_type' => 'articlecapa',
	'capabilities' => [
		'publish_posts'       => 'publish_articlecapa',
		'create_posts'       => 'create_articlecapa',
		'edit_posts'          => 'edit_articlecapa',
		'edit_others_posts'   => 'edit_others_articlecapa',
		'delete_posts'        => 'delete_articlecapa',
		'delete_others_posts' => 'delete_others_articlecapa',
		'read_private_posts'  => 'read_private_articlecapa',
		'edit_post'           => 'edit_articlecapa',
		'delete_post'         => 'delete_articlecapa',
		'read_post'           => 'read_articlecapa',
	],
`
2. In admin go to "Custom post name" ==> "Add new"

**Actual behaviour**
Blank page is shown. In browser console log, I can see that REST API fetch is forbidden:
`Failed to load resource: the server responded with a status of 403 (Forbidden)`
`http://mysite.test/api/wp/v2/articles/20030?context=edit&_locale=user`

**Expected behavior**
Edit post page with Gutenberg shown.

**Environment**
This is reproduced in Linux webserver as in my local environment (Mac OS with Vagrant installed).

I have also tried to deactivate all the plugins and bug is still happening. If I remove custom capability args, everything is ok.

**Also note**
I have used classic editor plugin before and there are several posts already created. If I click on some existing post, Gutenberg loads ok.

**Comment by youknowriad** [comment]
Seems like a REST API issue. Maybe @danielbachhuber @kadamwhite or someone else know the reasons here.

**Comment by Mamaduka** [comment]
I tested custom capabilities for a post type, and the editor works without errors. WordPress 6.2.2 and Gutenberg 15.8.

I'll close the issue, considering there have been no replies in a few years.
