### ISSUE TITLE
Gallery: choosing thumbnail size

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1450]
This is not a great experience in core at the moment, but since some themes / people may be relying on specific thumbnail generation for galleries, it'd be good to offer that option in the inspector, to choose a specific thumbnail size from the registered ones.

**Comment by paulwilde** [comment]
A consideration is that these options can currently be filtered in core with the [`image_size_names_choose`](https://developer.wordpress.org/reference/hooks/image_size_names_choose/) filter.

**Comment by kopepasah** [comment]
@mtias by "thumbnail size" I assume you referring to a registered image size. If that is the case this might be an issue because the registered image size may not have an image size stored in the upload directory, as adding an image size does not resize the currently uploaded images.

**Comment by kopepasah** [comment]
I see @mkaz and @jasmussen are assigned this issue (as of this comment). Are either of you currently working on this implementation?

**Comment by jasmussen** [comment]
> Are either of you currently working on this implementation?

I'm not, and I don't think Marcus has started yet either. We have a few other tickets to look at also, https://github.com/WordPress/gutenberg/issues/assigned/mkaz so please feel free to take this one if you're feeling adventurous, would really apprecaite it. Worst case, you can push your work early, and ping us, and we can work together. 

💓

**Comment by mkaz** [comment]
Correct, I'm still working on #1444 #1445 and #1447 which all involve gallery & media modal - so haven't started on this one yet

**Comment by jasmussen** [comment]
Reassigned this one to you, @kopepasah, but if it drops off your radar for any reason (understandable), just ping us and we'll be back on!

**Comment by Axinet** [comment]
If "image block" has a combo box to choose from registered image sized I don't understand the hesitation to provide a similar mechanism for the gallery block. In both cases there is a possibility that user may not have an image size stored in the upload directory, but looking at popularity of "Regenerate Thumbnails" plugin people are aware how to deal with it (by the way it is strange that core allow changing image sizes assigned to medium and large names but has no option to handle already uploaded files).

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519322010000460)._

**Comment by fabianpimminger** [comment]
Would be great if there is a solution to this (even as an intermediary step until there is better image size support/foundation in core as mentioned in the slack channel)

Think of all users that are uploading images in full sizes. This quickly adds big amounts of traffic to a site.

**Comment by klihelp** [comment]
+1

**Comment by radogado** [comment]
Inserting huge full size images would break the page. Thumbnails also needed for Lightbox modules. If possible, with the old gallery HTML structure.

**Comment by jasmussen** [comment]
Could the proposed UI enhancements for images work for this as well? https://github.com/WordPress/gutenberg/issues/4914

**Comment by klihelp** [comment]
+1

**Comment by klihelp** [comment]
A fix until thumbnails comes in - replace the gallery block with the gallery shortcode
https://github.com/klihelp/kli_gutenberg_gallery

**Comment by fabianpimminger** [comment]
I think the images in the gallery block should at least support the srcset attributes? Then the browser should be able to load only the image with an appropriate size?

**Comment by mor10** [comment]
@fabianpimminger Adding `srcset` and `sizes` only partially resolves the issue. See #6177

**Comment by DrYurets** [comment]
As a temporary fix (Gutenberg + Advanced Gutenberg for lightbox effect):
1) Install a @klihelp 's [plugin](https://github.com/WordPress/gutenberg/issues/1450#issuecomment-374720838)
2) [Fix it](https://gist.github.com/DrYurets/f7178889d71a6d352b915f04f97c4088)
3) [Fix it](https://gist.github.com/DrYurets/d7ea4d70e66077e553a849c778828140)

**Comment by erikjoling** [comment]
> Think of all users that are uploading images in full sizes. This quickly adds big amounts of traffic to a site.

Like @fabianpimminger said. Currently full-sized images are being loaded when I use the gallery block on a website. This isn't accessible for people on a slow internet-connection and an unnecessary waste of resources. 

I would expect the possibility to choose which image-size I want to load. Just like @mtias proposed in the opening of this issue.

**Comment by markfinst** [comment]
Please store image attachment IDs in JSON comment blocks (`<!-- wp:gallery -->` and `<!-- wp:image -->`). So content can be easily filtered by backend code. 

In the current version of Gutenberg only `wp:image` stores attachment ID, `wp:gallery` - **doesn't**.

If this won't happen, every plugin or theme that wants to modify Gutenberg gallery HTML markup needs to create another block. Which breaks backward's compability.

More info at: https://github.com/WordPress/gutenberg/issues/8193

**Comment by antpb** [comment]
I think @markfinst 's recommendation is a good one on storing `ids`. There are a few instances I could see this being useful:
1) Gallery shortcode fallbacks to respect older filters will likely rely on `ids` ( https://github.com/WordPress/gutenberg/issues/1451) 
2) https://github.com/WordPress/gutenberg/issues/10994 - though this issue may be a little more complicated than just getting all the ids to a single REST request, having `ids` stored will help make that an option.
3) extendability 
4) transform possibilities

For https://github.com/WordPress/gutenberg/issues/1451 I am exploring a `classic-gallery` block that allows for inspector controls in the sidebar. A temporary solution to this issue would be transforming large galleries to a shortcode or `classic-gallery` block. If we had the `ids` stored, this would be easy to adjust to. @mtias wanted to bring this one to your attention as we continue to discuss the possibility of a `classic-gallery` block. 

<img width="341" alt="screen shot 2018-10-28 at 3 33 33 pm" src="https://user-images.githubusercontent.com/8985705/47621512-f266c000-dac6-11e8-89d1-215e74378e1b.png">

Here's the branch where I am building the classic-gallery block: https://github.com/antpb/gutenberg/tree/add/classic-gallery

**Comment by mtias** [comment]
We are consolidating image handling improvements in https://github.com/WordPress/gutenberg/issues/6177. This is a good opportunity to avoid offloading the responsibility of determining the right size (performance, weight, quality) to the user and the engine doing it instead with responsiveness in mind.

Moving this out of 5.0 as there could still be some additions to the gallery block around showing certain cropped thumbnails as options, but it needs a better presentation as well.

**Comment by StancuFlorin** [comment]
Is this still on the roadmap?

**Comment by anybodesign** [comment]
Hi there :) 

Is it still planned to add the possibility to choose the thumbnail size in the gallery block? (As well as the "Link to" feature)

It is a heavily needed feature, there's a real performance issue with large galleries (20 and more picture). So far it is also impossible to create a gallery with square thumbnails.

Hope to hear from you soon

**Comment by u451f** [comment]
I'm also still looking for a fix or at least a workaround for this issue: either provide a general setting what image size galleries should link to or a per-gallery setting as it was pre-Gutenberg. Any hints?

**Comment by maffi-git** [comment]
Workaround for now seems to install the classic editor or use a gallery plugin. I've just started to implement a new site for a customer and this was the first real issue. Not beeing able to choose the thumbnail breaks the thing for me. 
Croping for the same size would be a partial-solution - I will try to find a styledefinition for that - croping for the same height looks not nice in my test-case.

**Comment by Backpackstudio** [comment]
To be honest, it's a disaster to not have an option to choose thumbnail size for gallery.

**Comment by drewclifton** [comment]
Any updates on this? As I run into this issue and reflect on its ramifications, I'm actually surprised the gallery block was even released in this state. Thank you!!! :smiley:

**Comment by Megaheff** [comment]
Any ETA on this? It is pretty useless without it. Cheers!

**Comment by patbar5** [comment]
Ref the tip :
Defining a fixed height for the class .blocks-gallery-item seems to do the trick. In my case:
.blocks-gallery-item {
height: 150px;
}

**Any tips how to handle the image width ? **

**Comment by simboonlong** [comment]
+ 1

**Comment by TheAggressive** [comment]
2 years later and this is still not fixed? Why are we sending large images over cellular networks? Wouldn't be better to load thumbnail images rather than large size that would have to be converted with CSS to appear as thumbnails? WordPress prides itself on being backwards compatible but this compatibility is broke in this block component. I would strongly consider fixing issues before continuing on new features.

**Comment by frogdesk** [comment]
Adding the images size selector didn't fix this problem. The gallery should use one size for the thumbnails and a different size for the full size. That is the problem to begin with. This should have been a release blocker.

**Comment by natedolesh** [comment]
Agreed that this still seems to be an issue in 2021. I try to select Thumbnail from the dropdown, but it just goes back to Large.
After so many iterations, we don't have a functional gallery block?

**Comment by umviajante** [comment]
same problem around here and I still haven't figured out a solution ...

**Comment by frogdesk** [comment]
> same problem around here and I still haven't figured out a solution ...

Unfortunately that is because there is no solution, evidently the Gutenberg developers see the gallery block as a developer example and not as an actually usable production level block. It is most unfortunate that this block is even included in general WordPress releases because it is clearly not intended for production use.

**Comment by skorasaurus** [comment]
@frogdesk & @umviajante @natedolesh  

I agree that the larger images are still being loaded; is really frustrating. I wrote [this recap](https://gist.github.com/skorasaurus/a01249d4302226bf12c80dd979322303) a couple weeks ago that summarizes the issues around loading larger than necessary images in Gutenberg. There's not quite one place at the moment to keep track of the progress around it but https://github.com/WordPress/gutenberg/issues/20778 may be the most appropriate for you.

**Comment by radogado** [comment]
It is unsustainable to insert 100 images at full size and the app will break. We need the old style gallery with thumbnails. Maybe stability should be top priority.
