### ISSUE TITLE
Can't switch status from publish to pending review or draft

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1452]
The available flows in the current WordPress "publish box" are maybe a bit complicated to follow and not sometimes have minor flaws but they always allow to change the post status.
For example, when a post is "published", it's always possible to switch it to "pending review" or "draft":

<img width="362" alt="screen shot 2017-06-26 at 14 29 04" src="https://user-images.githubusercontent.com/1682452/27540002-e09b9158-5a7e-11e7-8a1b-1524ea42dd71.png">

and then users are offered to "Save as pending" or "Save as draft" (or publish again):

<img width="311" alt="screen shot 2017-06-26 at 14 40 26" src="https://user-images.githubusercontent.com/1682452/27540032-f70fb662-5a7e-11e7-9099-27e80c129de4.png">

Currently, I can't find a similar flow on Gutenberg: unless I'm missing something, once a post is published, there'e no way to se it to pending review or draft. Not sure if this has already been discussed or if #708 may help.

**Comment by youknowriad** [comment]
You're right, we discussed adding a "Revert to draft" button to fix this.

Noting that the way WordPress stores the status is not easy to work within an SPA. (The visibility is mixed with the pending toggle and also mixed with the "draft/published" status, all in the same attribute `status`).

**Comment by afercia** [comment]
Yep... historical, technical debt. Worth also noting `register_post_status()` can be used to create new ones, even if the interface doesn't expose the. See https://core.trac.wordpress.org/ticket/12706

**Comment by moorscode** [comment]
It is currently not possible to revert a published post to `draft` or `pending review` status.

**Comment by seb-montana** [comment]
It's ok on v.4.7 - you can find a checkbox named "pending review" in "Status & Visibility" panel.
But nothing about register_post_status() ? Trying to register new post status, nothing appears in back end. Anyone can help me ?
