### ISSUE TITLE
Rich Text: Void blocks are considered plain-text, aren't converted

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14534]
**Describe the bug**

A void block (a block with no content, self-closing), when pasted, is not converted to a block (at least in macOS Chrome). The root cause is that `ClipboardData#getData` considers the comment-only markup as plain-text, not HTML. This could be considered a browser bug, though it has the practical impact of preventing blocks from being converted correctly.

Example void block:

```html
<!-- wp:latest-posts /-->
```

**To Reproduce**

1. Copy the block markup above
2. Navigate to Posts > Add New
3. Click on the writing prompt
4. Paste the block markup

**Expected behavior**

The pasted text is converted into a Latest Posts block.

Alternatively, if it was interpreted as plain-text, the plain text of the markup should be inserted into the paragraph.

**Actual behavior**

Nothing happens.

**Desktop:**

 - OS: macOS Mojave Version 10.14.3 (18D109)
 - Browser: Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Additional context**

Both HTML and plain text data are retrieved from the clipboard and passed to `clipboardData`.

https://github.com/WordPress/gutenberg/blob/27c0d00102341615df838d1df2a40f1e33ff7973/packages/block-editor/src/components/rich-text/index.js#L236-L237

For this reason, if it's not possible to have the browser consider the comment markup as HTML, an alternative to consider may be to update the following condition to consider `plainText`, in addition to `HTML`:

https://github.com/WordPress/gutenberg/blob/27c0d00102341615df838d1df2a40f1e33ff7973/packages/blocks/src/api/raw-handling/paste-handler.js#L130-L133

cc @ellatrix

**Comment by ellatrix** [comment]
Fixed in #14536.
