### ISSUE TITLE
Import problem for dynamic values

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14531]
I have created a slider block and to select sliders users will have to select a slider category. Let's say the slider category is 10.

When I export and import the XML file generated by WordPress. The slider category id is changed to some integer but not 10.

The problem here is, In the slider block there is still the selected category ID is 10 but the category ID has been changed. So is there any hooks to change the attribute value of the block field ??

In the past, all the values are saved in post meta so after importing we can change the post meta values but for the blocks that is not possible.

**Comment by swissspidy** [comment]
For reference, this is the same problem as with gallery shortcodes. See https://github.com/humanmade/WordPress-Importer/issues/41 for an example.

Basically, you‘d have to perform a search & replace operation after the import.

**Comment by ravishakya** [comment]
It would be much easier if we have some hooks to change the value. Let's say every block has a unique id. So we can do something like this to change the value.

`change_block_value( $post_id , $block_id , 'block_key' , $block_value );`

To achieve this all the block data should be store in its differect table, like post_meta is saved in "wp_postmeta", block data can be store in block_meta table. It would be easier to change the data.

**Comment by swissspidy** [comment]
> To achieve this all the block data should be store in its different table, like post_meta is saved in "wp_postmeta", block data can be store in block_meta table. 

That has been discussed plenty of times and for the sake of backward compatibility has been decided against. There are plugins that allow you to do this, but for the moment it is not being considered for core.

**Comment by skorasaurus** [comment]
This is being closed since this was decided to not be considered. Please comment if you have any questions.
