### ISSUE TITLE
Latest Update Fatal Error Possible Elementor conflict

### ISSUE THREAD

**Issue by studio500** [WordPress/gutenberg#14539]
Hi, just to let you know.
I updated to to the latest Gutenberg 5.3.0 update and Immediately received the below fatal error, which appears to be linked to a possible Elementor conflict.

Fatal error: Uncaught Error: Call to undefined function Elementor\gutenberg_can_edit_post_type() in /home/bisfhous/public_html/wp-content/plugins/elementor/includes/compatibility.php:54 Stack trace: #0 /home/bisfhous/public_html/wp-includes/class-wp-hook.php(286): Elementor\Compatibility::add_new_button_to_gutenberg(”) #1 /home/bisfhous/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(”, Array) #2 /home/bisfhous/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /home/bisfhous/public_html/wp-admin/admin-header.php(120): do_action(‘admin_print_scr…’) #4 /home/bisfhous/public_html/wp-admin/edit.php(353): require_once(‘/home/bisfhous/…’) #5 {main} thrown in /home/bisfhous/public_html/wp-content/plugins/elementor/includes/compatibility.php on line 54

**Comment by youknowriad** [comment]
yes `gutenberg_can_edit_post_type` is a plugin function and not something that is available in Core. I suggest and it was deprecated two releases ago (in the plugin). I suggest reaching out to Elementor.

Thanks.
