### ISSUE TITLE
Gallery: full-screen image preview

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1453]
It would be nice to be able to view gallery images without leaving the page that contains the gallery.  A couple of examples in the wild:

- https://jetpack.com/support/tiled-galleries/
- http://photoswipe.com/

While this feature is supported in Jetpack, I think it would be a great fit for Gutenberg, and common enough to warrant inclusion in core.

**Comment by swissspidy** [comment]
Tiled Galleries is not a good example… Did you perhaps mean https://jetpack.com/support/carousel/ instead?

Could the same be done for single images as well? It's something many people implement on their sites using the dozens of lightbox plugins out there.

**Comment by afercia** [comment]
As accessibility team, we've recently been asked for some advice about "image carousels" for a meta ticket, and done some research, see:

Improve Screenshot Slider Accessibility
https://meta.trac.wordpress.org/ticket/2654
(reading references posted there highly recommended)

In short, one of the most accessible carousels I've personally seen is:
https://jongund.github.io/aria-examples/bootstrap-carousel/carousel-3.html

There may be others, so any feedback welcome!

**Comment by karmatosed** [comment]
I think this would be nice. In a way it would help with the feeling of a front/back being the same. I do think we need to be cautious though of how this is done - with a11y mindfulness.

**Comment by mtias** [comment]
Closing as we are likely not going to get to front-end improvements like this one and it'll remain plugin territory.
