### ISSUE TITLE
Post meta values replaced when there are multiple same block.

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14545]
When you add multiple same blocks and the values of the block are saved in post meta, it seems it is replacing the values. I can save the value in attribute but I don't want that. What is the best way to handle this ??

**Comment by youknowriad** [comment]
Not sure I undersand the question 

> it seems it is replacing the values

Who is replacing which value? Can't you expand more?

**Comment by ravishakya** [comment]
My question is same as this thread https://github.com/WordPress/gutenberg/issues/5599

```
attributes: {
    catID: {
        type: 'number',
	default: 0,
        source: 'meta',
        meta: 'catID',
    },
},
```

When you have same two blocks the value of "catID" is replacing because one post meta has been used for both fields.

**Comment by youknowriad** [comment]
Well, that's "normal" because you're using the same post_meta for both, if you change one, it changes everywhere. If you want separate values per block you shouldn't use a post_meta for this or you should use a different meta key.

**Comment by ravishakya** [comment]
Thats a big limitation. It would have been easy if we have "block_meta" table like "wp_postmeta". All the block attributes are save on "block_meta" instead on the_content().

and we can do something like this to get the block data.

`get_block_meta( $post_id, $block_id , 'block_key' );`

A separate table for blocks. Just my view.

**Comment by youknowriad** [comment]
The backend at the moment has no knowledge about blocks, so there's no block_id etc...  Adding such feature is not our current roadmap. It's a big feature and it's not clear what user user-case this would solve.

Thanks for the suggestion, let's reconsider if there's more similar feedback.
