### ISSUE TITLE
abbreviation-Block

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#14553]
**Is your feature request related to a problem? Please describe.**
HTML5 supports abbreviations by the `<abbr>` element.
Abbreviations have to be added to a page sometimes, e.g. the ingredient-group in a menu card.

**Describe the solution you'd like**
An abbreviation-Block that allows to add an abbreviation including its full title, 
ideally it can be wrapped in a link to a page with more details.
Additional feature: Own abbreviation posts/taxonomy from which the abbreviation can be selected.

**Describe alternatives you've considered**
Manual adding `<abbr>` elements in code editor is tedious, 
also it hides the title in normal editor.

**Comment by youknowriad** [comment]
Hi There! Thanks for opening the issue.

Was this possible in the classic editor? I feel like this is better saved by a custom third-party format instead of a block.

**Comment by strarsis** [comment]
@youknowriad: I found one for classic editor: https://wordpress.org/plugins/abbreviation-button-for-tinymce/

This should be applicable to any (inline?) text in Gutenberg as any text can be an abbreviation, 
even text in the headings.

**Comment by youknowriad** [comment]
> This should be applicable to any (inline?) text in Gutenberg as any text can be an abbreviation,
even text in the headings.

Yes, that's definitely possible. Here's a tutorial that can help you achieve that https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/format-api/

I'm going to close this issue as I don't think this is something to be included in Core for the moment.

Thanks.

**Comment by strarsis** [comment]
There are some plugins available that offer abbreviation formatting:
- [editorskit](https://wordpress.org/plugins/block-options/)
- [abbr-gutenberg-wp](https://github.com/bunda3d/abbr-gutenberg-wp)

I hope abbreviation/acronym formatting is added to Gutenberg core as it is a core HTML feature.

I also noticed example code for using Gutenberg UI autocomplete for acronyms:
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/filters/autocomplete-filters.md#example
