### ISSUE TITLE
Refreshing Blocks after Page Attribute

### ISSUE THREAD

**Issue by CHEWX** [WordPress/gutenberg#14559]
**Describe the bug**
If you set blocks to be specific to page template then you need to save page as draft and then refresh the page to see any preset or block restrictions take place.

**To Reproduce**
1. Restrict blocks to page template or preset blocks to page template
2. Create new page
3. Change page to page template
4. Blocks stay the same

**Expected behavior**
Expected to see restriction/presets to auto-refresh after page template change.

**Comment by youknowriad** [comment]
> Restrict blocks to page template or preset blocks to page template

Can you clarify what you mean by this? or give an example?

> Change page to page template

same for this step

**Comment by CHEWX** [comment]
>Restrict blocks to page template or preset blocks to page template

Not sure if I can explain this any further, so here's an example.

```
add_filter( 'allowed_block_types', 'restrict_block_types', 10, 2 );
function restrict_block_types( $allowed_blocks, $post ) {
    if( get_page_template_slug( $post->ID ) === 'page-tpl-video.php' ) {
        return array( 'core/paragraph' );
    }
}
```

And docs.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#hiding-blocks-from-the-inserter

>Change page to page template

Not sure if I can explain this any further, so here's the docs.

https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-custom-page-templates-for-global-use

**Comment by youknowriad** [comment]
Got it, I think this API is not meant to be used with properties that can be changed in the editor itself. To solve this you'd need to update the allowed blocks with JS as soon as the template is changed in the editor.

This is possible using the data module but it's not that easy.

You'll have to subscribe to the data module changes, and if the template changes, you should call the `updateEditorSettings` action with the old editor settings + the updated allowed blocks.

Read more about the data module here.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-data/
