### ISSUE TITLE
Block settings item added by plugin not aligned

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14567]
Reported at https://github.com/WordPress/gutenberg/pull/7895#issuecomment-475579371

![block settings not aligned](https://user-images.githubusercontent.com/3365507/54819143-f1cd0100-4cd5-11e9-9ac9-1cd270cdf542.gif)

**Comment by nosolosw** [comment]
PR for this at https://github.com/WordPress/gutenberg/pull/14569

**Comment by phpbits** [comment]
@nosolosw Thanks! Any chance you have link for documentation on how I can add shortcut to the menu item? Thanks!
