### ISSUE TITLE
In Multisite Edit Page Is Missing From Toolbar And Root of Multisite Gets Displayed

### ISSUE THREAD

**Issue by testerofgutenberg** [WordPress/gutenberg#14562]
In a multisite network, the Toolbar site displayed after My Sites is changed to the root of the site when the admin User adds the Toolbar to the URL so they can edit the page. The Edit Page is also not displayed in the Toolbar.

- login to WordPress
-- in a multisite network
- select one of your multisites
- verify the correct site is loaded after My Sites
- create a simple test page
- publish the test page
- copy the link for the page and open the link in a new tab
- paste ?bar=yes to the url and press return on the url to display the toolbar
- notice that the multisite display after My Sites shows the main root site now instead of the multisite you are in based on the url you selected
- notice that the Edit Page does not show either

Expected behavior:
The selected site should display properly after My Sites and the Edit Page should display to the User.

- used WordPress 5.1.1 and the Gutenberg release installed with this version
- OS: Windows 7 Enterprise
- Browser chrome Version 73.0.3683.75

**Comment by youknowriad** [comment]
Can I ask how is this related to Gutenberg? Unless I'm missing something, It seems like this issue is better served with a Trac ticket here https://core.trac.wordpress.org/

**Comment by testerofgutenberg** [comment]
I believe it relates to Gutenberg because a test of 4.9.10 with Gutenberg plugin not installed and Gutenberg not a part of WordPress core in that release doesn't have that problem. Unless they made changes to WordPress in the 5.0 and above WordPress releases that would affect the behavior of the Toolbar in multisite, it appears that this is connected to Gutenberg. Are you not able to reproduce the reported behavior?

**Comment by youknowriad** [comment]
Understood, but it doesn't mean it's Gutenberg as there are a lot of changes in Core that are unrelated with Gutenberg in 5.0 and more recent releases. Also, note that a lot of parts of Gutenberg are now merged in Core in the PHP code of WordPress and maintained there. This feels like unrelated with the Gutenberg JS code (which is maintained in this repository), I think more people would be able to help if you open a trac ticket instead.

**Comment by testerofgutenberg** [comment]
I created a ticket there. 

https://core.trac.wordpress.org/ticket/46610

thank you for your response

**Comment by youknowriad** [comment]
I'm closing and deferring to the trac ticket instead.
