### ISSUE TITLE
Do we need to this plugin in latest WordPress 5.1.1?

### ISSUE THREAD

**Issue by nabtron** [WordPress/gutenberg#14561]
Do we still need to use gutenberg plugin in WordPress 5.1.1 ?

Or we can safely remove it?

I am using gutenberg blocks with lazyblocks plugin via gutenberg. So just want to make sure that nothing will break.

Thank you.

**Comment by youknowriad** [comment]
You can safely remove the plugin. 

The plugin is a little bit ahead of WordPress, which means it might contain more features and fix that haven't been merged yet to WordPress. So depending on whether you want to be on the bleeding edge, you should enable or disable the plugin :)
