### ISSUE TITLE
Enable extending webpack.config.js in packages/scripts/ 

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#14560]
When using [@wordpress/scripts](https://github.com/WordPress/gutenberg/blob/master/packages/scripts/README.md), you can _replace_ the existing `webpack.config.js` file with your own. It would be great if instead of having to build a full webpack config manually there was a way of _extending_ the existing config to add a new module or similar. As an example, [@svgr/webpack](https://www.npmjs.com/package/@svgr/webpack) is useful in the context of blocks but using it means rewriting the entire `webpack.config.js` file.

**Comment by swissspidy** [comment]
You can totally extend the default config. Gutenberg does it already.

I also did it yesterday in a plugin: https://github.com/ampproject/amp-wp/pull/2000

**Comment by mor10** [comment]
Hmmmmmm. I must be doing something wrong then. Or maybe we're not talking about the same thing.

**Comment by mor10** [comment]
@swissspidy can you point me at a basic example of extending the Webpack config with a single module?

**Comment by youknowriad** [comment]
Here's how you import the config https://github.com/WordPress/gutenberg/blob/master/webpack.config.js#L16 and you can see a few lines after how it's reused.

I hope this helps.

**Comment by youknowriad** [comment]
Can I ask why using `wp-scripts build` without extending is enough or not? Asking to see if there are common patterns we can ship by default in the scripts module.

**Comment by swissspidy** [comment]
For me the most annoying part is the default `entry` configuration with `src` and `build`. This might work well if you just have a single block in your plugin, but not when it is a bit more complex. Also, as Morten mentioned, adding more modules is often needed. But I think it is fine to just extend the config at this point. It's really straightforward.

**Comment by youknowriad** [comment]
@swissspidy What if we mimic parcel's api where we could do:

```
wp-scripts src/file1.js src/file2.js -o dist
```

This would produce two scripts based on these two entry points?

cc @gziolo

**Comment by gziolo** [comment]
> @swissspidy can you point me at a basic example of extending the Webpack config with a single module?

I see this line imports default config used inside `@wordpress/scripts`:
https://github.com/ampproject/amp-wp/pull/2000/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR10

which is exactly the same solution as @youknowriad shared in Gutenberg context.

> For me the most annoying part is the default `entry` configuration with `src` and `build`. This might work well if you just have a single block in your plugin, but not when it is a bit more complex. Also, as Morten mentioned, adding more modules is often needed. But I think it is fine to just extend the config at this point. It's really straightforward.

As always, we wanted to start with a very limited set of features and see how plugins use it before making further decisions. I want to play a bit more with `wp-scripts start/build` next week as it might work with the default CLI arguments webpack can process (unless config enforcement makes it to ignore those args).

In the case of Gutenberg, we have a new use case (#14497) where we would need to tweak an entry point, output folder, disable externals and probably handle CSS imports :)

**Comment by youknowriad** [comment]
> In the case of Gutenberg, we have a new use case (#14497) where we would need to tweak an entry point, output folder, disable externals and probably handle CSS imports :)

I don't know yet if we should implement a way to disable the externals, I'm not certain yet that this is something WordPress developpers would need. but yeah a "CSS build command" (to match Gutenberg build tools) would be a good idea.

**Comment by mor10** [comment]
This looks relevant as an example: https://storybook.js.org/docs/configurations/custom-webpack-config/

**Comment by mor10** [comment]
To help others who will have the same question I've proposed an update to the documentation complete with a simple code example. See #14590.

**Comment by aduth** [comment]
Unless I've totally misunderstood our build process, the proposed changes at #15226 pose an interesting related requirement in Gutenberg needing to opt-out of the default Babel processing. The most straight-forward option here is to unset all of the `module.rules` it inherits. This works partly by virtue of the fact that the Babel loader is the only entry included here. If we were to add more default `rules` in the future, it might require us to rethink how we'd recommend opt-in/opt-out for specific behaviors.

While simple rules could be done as such:

```js
module: {
	rules: defaultConfig.module.rules.filter( ( rule ) => rule.use !== 'simple-loader' )
},
```

...the current Babel loader configuration is a good example of a _not-so-simple_ rule, and would be far more convoluted to exclude:

https://github.com/WordPress/gutenberg/blob/c8695f72db8dc5ecc00f70d6fe556dc63da1fd36/packages/scripts/config/webpack.config.js#L37-L60

**Comment by shivapoudel** [comment]
@aduth How can we extend [these options](https://github.com/woocommerce/woocommerce-admin/blob/e67c071e91da126e23b65ebea1f2f1fe96f75afa/webpack.config.js#L136-L146) for `sass-loader` in the extended `webpack.config.js` config?
