### ISSUE TITLE
Draft button overlapped issue

### ISSUE THREAD

**Issue by mehidi258** [WordPress/gutenberg#14570]
**Describe the bug**
Draft button overlap issue on Small desktop (e.g. 1024px) windows os. while Top Toolbar is enabled.

**To Reproduce**
1. Go to 'post editor'
2. Click on 'add any gutenberg block that has all settings'
3. Click on 'Show more tools & options' on top right corner, Then Select Top Toolbar
4. You will see draft button is overlapped by block toolbar

**Expected behavior**
Button should not be overlapped.

**Screenshots**
![image](https://user-images.githubusercontent.com/34313754/54822366-02c64400-4ccf-11e9-83d7-5d36e0fd14e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Resolution: 1024x768
 - Browser: Chrome
 - Version: Any

**Comment by mapk** [comment]
I just tested this and was able to recreate the issue between screen widths 1080px and 1082px. I selected a Paragraph block, and selected the top toobar option from the settings.

![Screen Shot 2019-03-22 at 9 09 55 PM](https://user-images.githubusercontent.com/617986/54861509-33b27300-4ce7-11e9-963e-6c28704dc495.png)

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting; this appears to have fixed since you have reported; I am not able to reproduce this in chrome or firefox. Please reopen if you are still experiencing this issue.
