### ISSUE TITLE
Visual Editor appears behind Advanced Panels - see #12967

### ISSUE THREAD

**Issue by Psinergy** [WordPress/gutenberg#14581]
This is the same issue as #12967 , though for some reason it was closed before it was actually fixed. 

Visual Editor is still showing (as of 5.3.0) behind some of the advanced panels still.

Not sure why the Visual Editor isn't self-contained within an area before allowing for the Advanced Panels to be written.

![image](https://user-images.githubusercontent.com/24701951/54834337-f66dc700-4c8d-11e9-9925-aa1d7e5d36c6.png)

**Comment by youknowriad** [comment]
Hi there!

We investigated this already and it's not a Gutenberg issue. Read this thread for more details https://github.com/WordPress/gutenberg/issues/11378

The TLDR is that it's more likely a plugin showing a hidden php warning or notice causing the browser to show in "Quirks mode" breaking the styling of the page.

**Comment by Psinergy** [comment]
It was this plugin causing it: TinyMCE Smiley Button

There should be someway though that other plugins shouldn't be messing with this sorta of thing, tbh.
