### ISSUE TITLE
Block toolbar position broken for full-wide blocks in some themes.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#14588]
This _could_ end up being a Twenty Nineteen issue, but since it popped up recently (and nothing has changed in Twenty Nineteen), I figured I'd start here. 

Lately, I've noticed that the block toolbar for full-aligned blocks appears cut off on mobile when using Twenty Nineteen: 

![2019](https://user-images.githubusercontent.com/1202812/54849040-6e051b80-4cb9-11e9-9329-1c210c1ae0d9.png)

There's also a bit of toolbar misplacement when editing the children of the cover image block on mobile: 

![Screen Shot 2019-03-22 at 4 04 30 PM](https://user-images.githubusercontent.com/1202812/54850021-51b6ae00-4cbc-11e9-93ba-99b0f0f06317.png)

There have been no recent updates to Twenty Nineteen's editor styles, so my guess is that this is due to a recent change in Gutenberg. It could theoretically be fixed by setting the `.block-editor-block-contextual-toolbar` position to `left: 0` and `right: 0` in Twenty Nineteen's editor styles, but this sort of editor UI adjustment doesn't seem like the sort of thing theme styles should mess with. 

This exact issue does not appear in other themes, however a very similar issue appears if you view a full-wide image block in other Twenty- themes: 

![Artboard](https://user-images.githubusercontent.com/1202812/54849623-39925f00-4cbb-11e9-8085-d4a073941918.png)

(Note, these themes do not declare full/wide block support, so to reproduce you need to create a full-aligned block in a different theme and then switch to these themes to view the error).

**Comment by m-e-h** [comment]
I've experienced something similar. Pretty sure it has to do with the method the theme uses to align it's blocks and a full-width block. I recently switched from doing a `margin-left: calc(-50vw + 50%);` kind of thing to using flexbox and the issue disappeared for me.

Actually, the toolbar is now centered on align-full blocks but it's better than it was. I'll try to take a deeper look sometime this week.

**Comment by m-e-h** [comment]
_My similar issue above must've been something I did cause I can't seem to replicate it._ :confused: 

The issue you're seeing @kjellr I'm able to replicate on any theme that supports the full width.

Here's an unmodified underscores theme at `< 600px`:

![fullwidth](https://user-images.githubusercontent.com/3585901/54950426-a43fd680-4f17-11e9-9966-b4590055ec82.png)


>  It could theoretically be fixed by setting the .block-editor-block-contextual-toolbar position to left: 0 and right: 0

That's exactly where I see the issue too. 
This does get done at `> 600px`:
```
@media (min-width: 600px) {
	.block-editor-block-list__block .block-editor-block-contextual-toolbar {
		left: auto;
		right: auto;
	}
}
```
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L917-L920

I'm not seeing where we ever need that -14px on the `.block-editor-block-contextual-toolbar` itself. At least not with `[data-align="full"]`.
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L833-L843

The 14px padding is already compensated for on the `contextual-toolbar`'s parent div:
```
.block-editor-block-list__layout .block-editor-block-list__block[data-align="full"] > .block-editor-block-list__block-edit {
    margin-left: -14px;
    margin-right: -14px;
}
```
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L470-L484

What a beast of a file that `/block-list/style.scss` is, btw. :japanese_ogre:

**Comment by kjellr** [comment]
> The issue you're seeing @kjellr I'm able to replicate on any theme that supports the full width.

Ah yes, I'm seeing it everywhere now too. Opened #14669 as a potential fix. Thanks for the investigation, @m-e-h!
