### ISSUE TITLE
Add a "light" option in the Font Weight selector

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#14592]
Along with "normal" and "bold", I would like a "light" option as some websites would like this, particularly for headers and other pieces of text. The "light" attribute could add declare that the font weight should be 300 (most fonts that have a light weight have a 300 weight.)

**Describe alternatives you've considered**
In the meantime, I have converted the headers into a Classic Block and manually styled them using the `style=""` attribute. I don't think that the majority of WordPress users would want or know how to do this.

**Comment by Wingo5315** [comment]
It would work like the other font options: the entire header.
![image](https://user-images.githubusercontent.com/25369857/55570683-656a0780-56f3-11e9-848e-a5776c2b0ce7.png)

**Comment by ellatrix** [comment]
What plugin are you using there? I'm guessing that you'd like to make a recommendation to them?

**Comment by Wingo5315** [comment]
Turns it out it was Coblocks. I thought this was a default feature: customising the font family, weight etc. Maybe this could be a default feature in Gutenberg?

**Comment by mtias** [comment]
Structural support for font-weight is meant to be explored as part of this project: #20331
