### ISSUE TITLE
Create group block by 'group' interaction

### ISSUE THREAD

**Issue by ChemicalSailor** [WordPress/gutenberg#14601]
Opening an issue for separate tracking as per https://github.com/WordPress/gutenberg/pull/13964#issuecomment-472803015

An alternative method of adding the section/container block would be to select multiple blocks, then select 'group' from the ellipsis menu or potentially a separate button in the block toolbar.

cc @getdave

**Comment by chrisvanpatten** [comment]
I would love this interaction, and ideally it would be paired with an "ungroup" or similar!

**Comment by getdave** [comment]
Thanks for this @ChemicalSailor and @chrisvanpatten. Much appreciated.

**Comment by getdave** [comment]
@chrisvanpatten I'm now working on this and have a decent prototype

https://github.com/WordPress/gutenberg/pull/14908
