### ISSUE TITLE
Admin Post Navigation

### ISSUE THREAD

**Issue by mitchellkrogza** [WordPress/gutenberg#14611]
**Is your feature request related to a problem? Please describe.**
No way to navigate to previous or next post in admin. 

**Describe the solution you'd like**
A simple way to move between posts in admin, I have 250+ posts to edit due to a major change. This now currently involves editing one post, then going back to **Posts > All Posts** and trying to remember where I left off. This seemingly simple task of updating all my pages will turn into a few days work instead of a few hours.

Prior to Gutenberg this plugin https://wordpress.org/plugins/admin-post-navigation/ did the most perfect job but Gutenberg and Wordpress 5 broke it. 

![gute1](https://user-images.githubusercontent.com/9961541/54905554-01249800-4eea-11e9-9677-44b447c7c065.png)

**Describe alternatives you've considered**
The alternative solution was this plugin https://wordpress.org/plugins/admin-post-navigation/ but it's now broken by Gutenberg.

**Comment by youknowriad** [comment]
Hi there! and sorry for the inconvenience. 

I feel this is still plugin territory though and I think this is better raised as an issue in the plugin you shared. If this is very important for you, you can still install the classic editor plugin while the plugin author works on it?

Thanks.

**Comment by mitchellkrogza** [comment]
@youknowriad There should be some kind of ability to improve workflow for wordpress users. How much is to ask for some simple navigation :thinking: I am not the only person with hundreds of posts.

The plugin referenced is dead and unlikely to ever be revived but I'm stumped at all the waste of white space in Gutenberg (as in my screenshot) and nothing much useful there at all. 

Reverting to the classic editor is also not a solution nor an option. I now have many posts already converted to blocks so having a mish-mash of posts is really not a solution to this nor any CMS.

**Comment by youknowriad** [comment]
The editor is already full of buttons and UI and adding other features like this is not going to do a service for most users. I understand that for your particular workflow it's important but I'm not sure if navigating to previous/next posts is very common.

I'm pinging more designers for thoughts @mapk @jasmussen @karmatosed but happy to reconsider if people thing otherwise. The fact that it was considered plugin territory in the classic editor is telling.

**Comment by mitchellkrogza** [comment]
Thanks for tagging others for thoughts. 

I am busy replacing old buttons in posts created some years ago when Wordpress had no such lovely built in block feature as it does now. So now I've been fixing those old buttons with some ease thanks to Gutenberg but with 250+ posts to edit the job is really becoming tiresome.

Reverting back to the classic editor just to get this job done also does not help because I then have my next/prev buttons but absolutely no ability to insert a simple "Button" Block. Likewise opening the newer formatted posts in the Classic editor is less than savoury.

Surely Wordpress pays "some" thought to advanced users who've been using the platform since Day one.

For now I will have to try and hack through that older plugin to see if it can be revived at all.
