### ISSUE TITLE
Error for SVG

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#14610]
Hello,

I am one of the developer of Ultimate addons for Gutenberg.

We use the SVG icon for some of our blocks. If we create block using **admin** role then everything works fine. But the same block using **author** role throws an error for SVG.

Here is the error we get after save  - `Block validation: Expected token of type `StartTag` ({type: "StartTag", tagName: "svg", attributes: Array(2), selfClosing: false}), instead saw `EndTag` ({type: "EndTag", tagName: "div"}).`

Can you please let me know what is the solution for this? Why SVG is not acceptable in save block if the user role is Author?

Thank you!

**Comment by prajaktagadhave123** [comment]
FYI - We render SVG in block like this - https://monosnap.com/file/qqn0ZI57wsKMZcsL7zInbbA8qgpzC1

**Comment by youknowriad** [comment]
Hi there!

I think you should raise this as a Core Ticket instead https://core.trac.wordpress.org
I think this is probably a security behavior not allowing non-admin users to save `svg` elements in post content. 

I'm not personally aware of the exact reasons for this restriction but people there should know more.

Thanks.

**Comment by phpbits** [comment]
@youknowriad Same here : https://github.com/coblocks/coblocks/issues/455 . Do you have something like `MediaUploadCheck` to check user permission for SVG uploads? Thanks!

**Comment by youknowriad** [comment]
I don't think we have something specific for that as we didn't need this distinction in Core and unfortunately I'm not the right person to ask for the exact check that's needed.

**Comment by CodingJack** [comment]
it was a permissions problem on LocalWP for me.  online it worked fine.
