### ISSUE TITLE
getMedia() returns undefined in some cases

### ISSUE THREAD

**Issue by Pretzel63** [WordPress/gutenberg#14623]
I would like to get attachment data and I see getMedia() function is available for this. However I can't quite understand how to use this function. This returns undefined for me: 

```
edit: function(props) { 
  const image = wp.data.select('core').getMedia(2334);
  console.log(image);
}
```
2334 is valid ID of the existing attachment

Interesting thing is that if I add this block again in editor `image` returns media object correctly. Also, when I run directly in console it's also working. I tried to await it thinking this returns a Promise but it's still not working.

PS: where in code `getMedia()` is actually defined along with other functions from wp.data.select('core')? 

![where-are-they-defined](https://user-images.githubusercontent.com/40902723/54945833-08be5e00-4f37-11e9-8dfb-2899daf5b196.png)

**Comment by swissspidy** [comment]
`getMedia` is part of the `core-data` package (look for `getEntityRecord` and `entitySelectors`).

Perhaps this article is helpful: https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/

**Comment by Pretzel63** [comment]
Thank you very much @swissspidy 

This works great but I'm wondering now how to wait for the result of functions like this to finish. `getMedia` seems to be asynchronous, same as `editPost` function which I'm just trying to use now to set featured image for a post.

Simple use case would be: I would like to **disable the button** until it's completed

```
class MediaInfo extends Component {
	state = {
		generatingImage: false
	};

	changeFeaturedImage = attachmentId => {
		this.setState({ generatingImage: true });
		this.props.setFeaturedImage(attachmentId); // how to wait for it before updating state? 
		this.setState({ generatingImage: false });
	};

	render() {
		return (
			<button
				onClick={() => this.changeFeaturedImage(2423)}
				disabled={this.generatingImage}
			>
				Change featured image
			</button>
		);
	}
}
```
And my edit function:
```
edit: withDispatch(dispatch => {
	return {
		setFeaturedImage: function(attachmentId) {
			dispatch('core/editor').editPost({ featured_media: attachmentId });
		}
	};
})(MediaInfo)
```
Is there a callback I could use as 2nd parameter to execute only after `editPost` is completed?

**Comment by mr660** [comment]
+1
Why is it still unanswered???

**Comment by swissspidy** [comment]
Since a very similar question has been asked by you in #16003 and #16004, let's consolidate the answers here.

Since `getMedia` returns `undefined` when the data hasn't been retrieved yet, I suggest using the `withSelect` higher order component to do the `select('core').getMedia` part. Your component will re-render as soon as the data has been loaded and is available.

**Comment by mr660** [comment]
After a lecture on redux and react documentation and changing to function using `withSelect` as suggested instead of `Component` this is what i came up with:

```
const wp = window.wp
const { withSelect } = wp.data
const { Fragment } = wp.element
const { MediaPlaceholder, MediaUpload } = wp.editor
const { Spinner } = wp.components

const ALLOWED_MEDIA_TYPES = ['image']

function ImageControl (props) {
  const { value, onSelect, image } = props
  const onSelectValue = (media) => {
    onSelect(media.id)
  }

  if (!value) {
    return (
      <div className={`components-image-control is-select`}>
        <MediaPlaceholder
          className="components-image-control__placeholder"
          labels={{ title: 'Image' }}
          multiple={false}
          allowedTypes={ALLOWED_MEDIA_TYPES}
          onSelect={onSelectValue}
        />
      </div>
    )
  }

  if (!image) {
    return (
      <div className={`components-image-control is-loading`}>
        <Spinner className={`components-image-control__spinner`}/>
      </div>
    )
  }

  return (
    <div className={`components-image-control is-edit`}>
      <MediaUpload
        value={value}
        allowedTypes={ALLOWED_MEDIA_TYPES}
        onSelect={onSelectValue}
        render={({ open }) => (
          <Fragment>
            <button
              className={`components-image-control__btn is-loading`}
              onClick={open}
              onSelect={onSelectValue}
            >&nbsp;</button>
            <img src={image.source_url}/>
          </Fragment>
        )}
      />
    </div>
  )
}

export default withSelect((select, ownProps) => {
  if (typeof ownProps.image === 'undefined') {
    if (typeof ownProps.value !== 'undefined') {
      return {
        ...ownProps,
        image: select('core').getMedia(ownProps.value)
      }
    }
  }
  return ownProps
})(ImageControl)
```

@swissspidy Can You tell me how to do something like `withSelect` HOC in `Component` instead of wrapping a function?

**Comment by swissspidy** [comment]
That `withSelect` part should look more like this:

```jsx
export default withSelect((select, ownProps) => {
  return {
    image: ownProps.value ? select('core').getMedia(ownProps.value) : null,
  };
})(ImageControl)
```

An alternative to have this inline would be to use the `useSelect` hook. See https://github.com/WordPress/gutenberg/tree/master/packages/data#useSelect for an example.

**Comment by youknowriad** [comment]
It seems like this received some good replies. Thanks.

**Comment by artuswo443** [comment]
withSelect is not the best solution. At first render wrapping component still gets redux store without data. I find there should be flag if redux had retrieved all data

**Comment by dragipostolovski** [comment]
Once you get the post try this:

 posts: select( "core" ).getEntityRecords( "postType", "post", {
      per_page: 1,
      _embed: true
  }),


post._embedded['wp:featuredmedia'][0].source_url

**Comment by htmgarcia** [comment]
Another option if PHP is running along with JS is `register_rest_field()` in combination with `get_the_post_thumbnail_caption()`
