### ISSUE TITLE
Permalink section doesn't appear until many many seconds after

### ISSUE THREAD

**Issue by leecollings** [WordPress/gutenberg#14635]
So previously, when creating a new post or page, whenever shifting focus away from the title, the permalink would be displayed that was then editable. This usually happened in 1 - 2 seconds after moving focus away from the title.

Now though, it seems to take a minute for the permalink section to appear. Originally, I did think it didn't show at all, and would resort to saving as a draft in order to edit the permalink.

Then I noticed after leaving the page open, it did appear at some point. Can this be cleaned up, or perhaps made show the permalink section is always visible, and the value is updated whenever the title is edited?

**Comment by youknowriad** [comment]
I think that's because the permalink was not showing until a draft was saved. This is fixed now.
