### ISSUE TITLE
Validation Errors for Reusable Blocks

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#14639]
**Describe the bug**

We filter `blocks.getSaveContent.extraProps` to add some extra props and attributes only for a specific CPT.

When editing a regular post or page in Gutenberg and saving a block as a reusable block, it obviously won't contain this extra data.

When going back to the CPT, Gutenberg loads all reusable blocks when clicking on the inserter and checks to see if they're valid. Since they don't have the extra props and attributes (since they were created without any `blocks.getSaveContent.extraProps` filter), there will be a block validation error.

I know that the [documentation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#blocks-getsavecontent-extraprops) says that `blocks.getSaveContent.extraProps` needs to be called on every page load. However, I think this should not apply when editing a block on an entirely different screen / post type.

Thoughts?

**To Reproduce**
1. For CPT XY, hook into `blocks.getSaveContent.extraProps` to add some extra props, e.g. an `id` attribute, to all blocks.
2. Create a reusable block when editing a post.
3. Try to insert reusable block when editing CPT.
4. See block validation error.

**Expected behavior**

No block validation error.

**Screenshots**

**Additional context**

Gutenberg 5.3

**Comment by gziolo** [comment]
> I know that the [documentation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#blocks-getsavecontent-extraprops) says that `blocks.getSaveContent.extraProps` needs to be called on every page load. However, I think this should not apply when editing a block on an entirely different screen / post type.

I'm personally coming to the conclusion that we should rethink when validation error triggers. We should split that into two parts:
- very strict error: is the content of the block the same as when it was saved, does it contain all HTML attributes and DOM nodes that are referenced in `attributes` definition
- a tiny warning or no action required: your saved content contains some additional HTML attributes or nodes - clean it up or continue as is

/cc @youknowriad

**Comment by gziolo** [comment]
There is also a tracking issue for all things related to validation of blocks: #7604. It might make more sense to discuss it there to get more eyes.

**Comment by jordesign** [comment]
With this issue being 4+ years old - I will, indeed, close it in favouf of #7604
