### ISSUE TITLE
Add Option to Disable Code Editor

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#14647]
**Is your feature request related to a problem? Please describe.**
We are using Gutenberg for our UF Health sites which includes over 700+ sites and many more admins who aren't technical yet want to use the platform. It would really be nice if we can disable the Code Editor for them so they can only use the blocks we've specifically built for the platform. Otherwise we run into some trouble. Right now the only option is to disable the visual editor. That made sense with the classic editor but with something like Gutenberg I think it makes more sense to also have an option to disable the code editor. It's especially helpful as we try to enforce style standards across our stack.

**Describe the solution you'd like**
Please add an option, possibly to the block_editor_settings filter, to disable the code editor.

**Describe alternatives you've considered**
Right now the only thing I'm able to do is force the visual editor on load with the 'core\edit-post' data module.

**Comment by gziolo** [comment]
@youknowriad, how do you envision to have it implemented? Would it be enough to disable it with `block_editor_settings` PHP filter and propagate to the editor through the settings store?

**Comment by draganescu** [comment]
@gziolo there are only two ways to implement:

- a developer oriented one, where the block_editor_settings has and propagates a new isCodeEditingEnabled flag
- a site admin oriented one, where in the Settings screen you can disable the code editor for certain roles

@myleshyson raised the issue for the developer experience, which is a GTB issue, I wonder if it would be a good WP feature as well?

**Comment by gziolo** [comment]
Let's focus on the developer oriented one first.

**Comment by kanlukasz** [comment]
So which option disable this? I can't find this in the documentation
