### ISSUE TITLE
Improve error message on post save fail

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#14644]
**Is your feature request related to a problem? Please describe.**
Currently, when a post fails to save it displayed the message. 'Updating failed'. However in [#44625](https://core.trac.wordpress.org/changeset/44625) (See [#45933](https://core.trac.wordpress.org/ticket/45933)), if the json api fails it will return a a nice formatted json. An example of which. 

```
{
   additional_errors: [],
   code: "wp_die",
   data: {status: 500},
   status: 500,
   message: "<h1>Error establishing a database connection</h1>"
}
```

In WordPress 5.2,  [#44458](https://core.trac.wordpress.org/ticket/44458) even php fatal error will return valid json.

**Describe the solution you'd like**
This message returned to users should display the message returned in json. This will help users debug the issue they are having.

**Comment by spacedmonkey** [comment]
If useful, we could also return a header, like `WP_DIE: true`, so it is easier to know to display this message.

**Comment by aduth** [comment]
Related: https://github.com/WordPress/gutenberg/issues/4590#issuecomment-359491059

Implementation notes: 

- From the JSON blob, the `message` would need to be manipulated to remove the `h1`. Is it safe to assume the plaintext message would always be wrapped as `h1`?
- Notice creation occurs here:
   - https://github.com/WordPress/gutenberg/blob/a6ff3a0622142bb5ace6de3cfc958966f5573951/packages/editor/src/store/actions.js#L403-L414
   - https://github.com/WordPress/gutenberg/blob/a6ff3a0622142bb5ace6de3cfc958966f5573951/packages/editor/src/store/utils/notice-builder.js#L77-L107

**Comment by spacedmonkey** [comment]
@aduth 

I have  been working on how WordPress handles fatal errors. See these tickets from core [#45974](https://core.trac.wordpress.org/ticket/45974)  [#45975](https://core.trac.wordpress.org/ticket/41655) [#41655](https://core.trac.wordpress.org/ticket/41655). 

So the reason for the call to wp_die maybe many different reasons and the content of the error message will different depending on the which error is triggered. One thing that is more predictable is the error code. Maybe this, with a simple switch statement could be used to give more detail on the type of error.

**Comment by aduth** [comment]
>One thing that is more predictable is the error code. Maybe this, with a simple switch statement could be used to give more detail on the type of error.

I could see this working well.

As a plan for action, it may require:

- Auditing to discover which response codes are possible (or at least reasonable to account for as a reason for save failure)
- Devising copy for each to present to the user as both accurate and well-understood (may be good to use "Needs Copy Feedback" label or otherwise involve some copywriters).

Example:

`503` -> "Updating failed. The site is briefly unavailable for maintenance."

**Comment by spacedmonkey** [comment]
I think there are some key error states we need to handle here. 

- [Maintenance mode](https://github.com/WordPress/WordPress/blob/52354f3f0b7f2b6e53d6ca3578942d5940f84048/wp-includes/load.php#L182-L227)
- [Database dead](https://github.com/WordPress/WordPress/blob/a1f4b046d74b2c3ad20abbfbcbb4dfd9f4785331/wp-includes/functions.php#L4361-L4379)
- [PHP fatal error handler](https://github.com/WordPress/WordPress/blob/52354f3f0b7f2b6e53d6ca3578942d5940f84048/wp-includes/class-wp-fatal-error-handler.php#L190-L200)
- [wp_check_mysql_version](https://github.com/WordPress/WordPress/blob/b2e3f517e1bca2eb50c83dfdf0a816ff5d9c489f/wp-admin/includes/upgrade.php#L3176-L3182)

Not all of these return a usable error code, but this is easy to change. 
Also, if the rest api can return WP_Error object, for different reasons, like invalid params or auth errors. If those errors are not displaying a usable message, then that should be handled. 

But now there are is a format of these error message, this can be handled in one place and with a simple switch statement.

**Comment by pbiron** [comment]
> I think there are some key error states we need to handle here.

Another one to add to the list (it just happened to me):

* login cookie has expired but haven't yet gotten the Heartbeat API tick for the pop-up re-login

**Comment by spacedmonkey** [comment]
Yeah, these are two examples of errors rest api that allow should be handled. 
```
{
    "code": "rest_cookie_invalid_nonce",
    "message": "Cookie nonce is invalid",
    "data": {
        "status": 403
    }
}
```
and 
```
{
    "code": "rest_cannot_edit",
    "message": "Sorry, you are not allowed to edit this post.",
    "data": {
        "status": 401
    }
}
```

**Comment by spacedmonkey** [comment]
Some more examples of error output. 
```
{
    "code": "internal_server_error",
    "message": "The site is experiencing technical difficulties.",
    "data": {
        "status": 500
    },
    "additional_errors": []
}
```
```
{
    "code": "wp_die",
    "message": "Briefly unavailable for scheduled maintenance. Check back in a minute.",
    "data": {
        "status": 503
    },
    "additional_errors": []
}
```

```
{
    "code": "rest_post_invalid_id",
    "message": "Invalid post ID.",
    "data": {
        "status": 404
    }
}
```
```
{
    "code": "wp_die",
    "message": "<h1>Error establishing a database connection</h1>",
    "data": {
        "status": 500
    },
    "additional_errors": []
}
```
```
{
    "code": "wp_die",
    "message": "<p><code>No database selected</code></p>\n<h1>Can&#8217;t select database</h1>\n<p>We were able to connect to the database server (which means your username and password is okay) but not able to select the <code></code> database.</p>\n<ul>\n<li>Are you sure it exists?</li>\n<li>Does the user <code>wordpress</code> have permission to use the <code></code> database?</li>\n<li>On some systems the name of your database is prefixed with your username, so it would be like <code>username_</code>. Could that be the problem?</li>\n</ul>\n<p>If you don&#8217;t know how to set up a database you should <strong>contact your host</strong>. If all else fails you may find help at the <a href=\"https://wordpress.org/support/forums/\">WordPress Support Forums</a>.</p>\n",
    "data": {
        "status": 500
    },
    "additional_errors": []
}
```

@aduth After reviewing the messages here I think it should work in the following page. 
1. Check for error status code.
1. Check if valid json
1. Check if message is set and not empty. 
1. Check if string contains html. 
1. If string contains html, then default to generic error message. Updating failed
1. If just string, output this string as error message.

This means, we don't have to double to effort with new translatable strings.

**Comment by spacedmonkey** [comment]
PR created #15657

**Comment by swissspidy** [comment]
Closing as the PR has been merged.
