### ISSUE TITLE
Add Block: Archive

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1464]
## Attributes

- None, Left, Right, Center, Full Width?
- Display as dropdown
- Show post counts

## States

Selected:

![archives](https://user-images.githubusercontent.com/2846578/27979944-bfadc30e-6347-11e7-880b-a52ef5c2a24b.png)

Neutral:

![archive block](https://user-images.githubusercontent.com/2846578/27979946-c3c5ed5e-6347-11e7-8539-3bc69fccdfa4.png)

-----

Questions:
- Should we include alignment?
- If yes, should alignment be a default setting in the Block Level Formatting bar?

Related to #1011.

**Comment by swissspidy** [comment]
This would be a dynamic block like "Latest Posts", right?

Regarding the alignment, I don't think it's necessary as it doesn't make much sense for this block IMHO.

**Comment by melchoyce** [comment]
> This would be a dynamic block like "Latest Posts", right?

Correct :)

**Comment by mtias** [comment]
Should post counts be part of the link?

**Comment by swissspidy** [comment]
I have some almost-working code locally for adding an archives block`*`. It uses `wp_get_archives()`, just like the existing widget in WordPress. That function puts the count outside the link.

Perhaps we could improve that function in core to make it more accessible, i.e. add some screen reader text to the count. In that case, having it outside the link makes more sense for a11y and also styling reasons.

`*` What's missing is the part to fetch this via the REST API. Probably worth waiting for #780.

**Comment by melchoyce** [comment]
> Should post counts be part of the link?

They are currently in widgets, but I think they don't need to be.

**Comment by marsjaninzmarsa** [comment]
Post Type selector please. 😂

**Comment by melchoyce** [comment]
Updated the mockups to unlink the post counts.

**Comment by westonruter** [comment]
> If yes, should alignment be a default setting in the Block Level Formatting bar?

On #1803 it seems the decision is to put the alignment controls in the block toolbar instead of the inspector.

**Comment by karmatosed** [comment]
This looks good to me so removing the 'feedback' label as looks ready to implement.

**Comment by melchoyce** [comment]
Similar to #1462, I wanted to take a look at rethinking the Archive widget rather than just porting it over. I ended up with two ideas: an archive list, and an archive grid.

### Archive List

The current archive widget seems to be popular on blogs, especially things like food/craft/lifestyle blogs. However, if you've been running your blog for a while, you end up with a gigantic list of months. Additionally, there's no way to see what posts were written within that month — just the number. To see the posts, you need to click into the archive for that month. What if you could see which posts were written that month?

![archive-list](https://user-images.githubusercontent.com/2846578/39388854-41136fa2-4a51-11e8-9130-17c316e89695.png)

To solve these problems, I: 
- Swapped links to the month archives for accordions.
- Started with months from your current year, then dropped down to the year for older posts. Previous years have an extra level of depth, so you open them and see the available months from that year.

This should help both condense the lists for long-time bloggers, and help people find the posts they're browsing for faster.

### Archive Grid

While a list is great for a sidebar or a narrower widget area, blocks can also exist within post and page content. This is where a grid comes in handy, so you can have a more dynamic approach to listing out your archive without needing to code up a custom template.

![archive-grid](https://user-images.githubusercontent.com/2846578/39388963-f793e40a-4a51-11e8-941e-818d02f4985d.png)

This particular mockup is inspired by Tumblr's default archive pages. Thinking that we could load the current year, then include a "load more" button or year-based pagination at the end of the current year's list.

---

Both of these still need some work — for example, you can see neither has settings yet — but I wanted to get the conversation started as soon as I had something to show.

**Comment by paaljoachim** [comment]
Thinking levels here.
Level 1 - post with images.
Level 2 - Latest posts showing an excerpt and featured image.
Level 3 - Archive. Showing latest posts + featured images in an archive grid by month.
 
As this would be a mix of visual text and images. Giving the option to the user to use images along the various levels.

Mels Archive Grid is very interesting as it shows a lot nicer looking archive page. The user would then have the option to make a simple list, open most recent post links or to create a grid.

**Comment by melchoyce** [comment]
https://en.blog.wordpress.com/2018/ shows the featured image as the background of the post block, which I quite like. It's very subtle, but helps you distinguish between posts and brings in some extra character.

**Comment by rchipka** [comment]
We should also consider [adding a Query block](https://github.com/WordPress/gutenberg/issues/6663)

**Comment by paaljoachim** [comment]
This PR: #7966
Has block options such as Number of items, display author, display date, display excerpt etc that could also be added to Archive block.

**Comment by karmatosed** [comment]
I am not convinced we need to add those to the archive block @paaljoachim. I don't think every block needs those settings that could have. What data are you using to think that would be a good step? Is there any prior example you think means it should to be a consideration?

**Comment by paaljoachim** [comment]
Hey Tammie. I just wanted to mention it. I am thinking about consistency. As there will be certain blocks that will reuse specific settings.
