### ISSUE TITLE
How to disable drop cap today (late march 2019)

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#14654]
I'm on latest Wordpress (v 5.1.1)

Please excuse my frustration, but I just don't understand what's so hard about adding:
```php
add_theme_support("disable-drop-cap");
```
just like the already existing
```
add_theme_support("disable-custom-font-sizes");
```

Or is there another intended way to disable the drop-cap feature in the admin area that I'm missing? If not, which I fear is the case, how would you disable it today?

**Comment by youknowriad** [comment]
Hi There! I agree that ultimately we need something like that. I shared some thoughts here https://github.com/WordPress/gutenberg/issues/6023#issuecomment-485372463 and I'm closing this as a duplicate.

**Comment by carasmo** [comment]
This plugin works 
https://github.com/joppuyo/disable-drop-cap
