### ISSUE TITLE
Blocks API: define a way for blocks to specify they can occur only once

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1465]
Some blocks should only be used once in a single post (the "more" block, the "excerpt", etc). A block should have a way of stating that in the registration.

**Comment by mtias** [comment]
As part of this, the inserter should be aware of blocks that can only be used once, and have already been inserted (either removing or showing as disabled, maybe scrolling to the already inserted block if you click on it).

**Comment by paulwilde** [comment]
See also my comment https://github.com/WordPress/gutenberg/issues/1288#issuecomment-310648383 regarding the same idea. It'd be nice if it wasn't necessarily a single item or infinite, but a customisable amount.

**Comment by swissspidy** [comment]
As a followup to this:

* We should experiment with specifying different limits, not just "use once"
* What happens if a post already contains multiple blocks of the same type, exceeding the limit?
