### ISSUE TITLE
Categories not showing when create a new post

### ISSUE THREAD

**Issue by rhcarlosweb** [WordPress/gutenberg#14651]
Because i'm using the WordPress in a subdirectory..
When the Site URL and WordPress as differente values, gutenberg try to catch categories from Site URL and no from WordPress URL, and the side to select categories in new post don't load

**To Reproduce**
1. Go to General settings
2. Change the WordPress URL to a wordpress subdirectory installation, and Site URL to main domain
3. Click in create a new post

**Expected behavior**
Load checkbox list of categories

**Screenshots**
Different urls on general configuration
![image](https://user-images.githubusercontent.com/4534115/55044841-945ceb00-501a-11e9-863c-c58def82e4e0.png)

Console error, no permission to load taxonomies
![image](https://user-images.githubusercontent.com/4534115/55044976-046b7100-501b-11e9-8c27-77b08f6289a9.png)

![image](https://user-images.githubusercontent.com/4534115/55044955-ee5db080-501a-11e9-839d-228e3798a8ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 73.0.3683.86

**Additional context**
The version i tested is for WordPress 5.1.1

**Comment by youknowriad** [comment]
This is most likely a server configuration issue. See #1761 where there are some tips to solve it.
