### ISSUE TITLE
Resizing Media & Text block can cause half of the editor to appear blank

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#14652]
**Describe the bug**
This is a strange issue. Half of the editor is clipped when the media and text block image is resized to specific sizes. This seems to happen when Twenty Nineteen is used as the theme, the block is aligned full, and then the resize handle is used (or the browser width is changed, as the image uses a percentage width):
![media-text-resize](https://user-images.githubusercontent.com/677833/55054355-82229180-509a-11e9-9c58-b0abab21daa6.gif)

My theory is that this is a bug related to chrome's rendering model. Specifically the way it divides parts of a webpage into layers. Note, in the following image 'layers' are enabled in the dev tools, and one of the layers seems to correlate exactly with where content is cut-off:
![Screen Shot 2019-03-27 at 12 18 59 pm](https://user-images.githubusercontent.com/677833/55052857-49cc8480-5095-11e9-8c96-2f839f22f520.png)

**To Reproduce**
I've managed to reproduce:
1. Activate Twenty Nineteen as the theme
2. Start a new post
3. Add a media and text block and upload an image
4. Align the block to full size
5. Use the drag handle to resize the image
6. Observe that half the editor disappears when the image is at specific sizes.

Expected Behaviour: The editor should be fully visible

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome
 - Chrome 73

**Additional context**
- Seems to be particularly prevalent with Twenty Nineteen, I haven't been able to reproduce in other themes (e.g. Gutenberg Starter Theme)

**Comment by talldan** [comment]
(cc: @melchoyce who noticed this)

**Comment by talldan** [comment]
After more trial and error, it seems to be resizing the media and text image that causes the issue:
![media-text-resize](https://user-images.githubusercontent.com/677833/55054001-2c011e80-5099-11e9-81c6-057173673e52.gif)

When the image is at certain widths, the issue appears. Resizing the browser triggers this as well, since the image has a percentage width.

**Comment by melchoyce** [comment]
FWIW, I've seen this happen with Cover blocks and Column blocks, too — not just Media & Text.

**Comment by talldan** [comment]
@melchoyce You're right, I've just seen it happen with a post that only contained an image block.

![glitch](https://user-images.githubusercontent.com/677833/55302816-92a98200-5475-11e9-903f-090bc0e09047.gif)

It seems as though there's a strong chance it's the drag-to-resize thing that's used on those blocks.

Not sure why it only seems to happen with Twenty Nineteen though. 😕

**Comment by chrisjreber** [comment]
Easy to replicate in any theme. 
Add default column block with 3 columns, add image to first column then resize the browser until you see the white.

Only happens in Chrome not Firefox.
Also only with the Gutenberg plugin installed.
Running iMac.

**Comment by gwwar** [comment]
To reproduce this more easily using Chrome:
- Test on a WP instance with v6.0 of the Gutenberg Plugin
- Fullscreen Mode
- Add three columns
- Add an image 

![Jun-26-2019 12-33-46](https://user-images.githubusercontent.com/1270189/60209182-f80bd580-980e-11e9-886b-dd054d828e5b.gif)

Folks may need to resize the browser window to see the glitch. Refreshing the page will render with the glitch.

I suspect the common thread here is with the resizer code.

**Comment by nerdysandy** [comment]
Reported on 13687255-hc
