### ISSUE TITLE
Add the React hooks eslint to our default eslint config

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#14676]
Also check if can avoid conflicts with the late variable declaration rule.

See here https://github.com/WordPress/gutenberg/pull/14612#discussion_r268909604

cc @aduth

**Comment by gziolo** [comment]
Npm package: https://www.npmjs.com/package/eslint-plugin-react-hooks
Docs: https://reactjs.org/docs/hooks-rules.html
