### ISSUE TITLE
Inconsistent CSS include for BLOCKs across same version of WP

### ISSUE THREAD

**Issue by stljeff1** [WordPress/gutenberg#14671]
**Describe the bug**
I have been developing locally a theme for the past 2 months. I pushed my changes to a dev server with a fresh install of  WP. I am noticing much more CSS for blocks on my staging site compared to what I've seen in my local environment. Consequently, elements on my site do not look as they need to, and I am having to write CSS with very specific rules just to compensate for these new styles. My other option is to remove these styles from the queue serverside. 

The offending styles are in an asset located here: /wp-includes/css/dist/block-library/theme.min.css

If I am running the latest version of WP using the same theme on two different servers, why is one instance loading CSS from the `wp-includes` directory, but the other is not? Could this have to do with my hosting provider? Should I expect more of this type of intrusion as you continue to develop Blocks/Gutenberg?

**To Reproduce**
1. Install WP
2. add a blockquote to a page.
3. See /wp-includes/css/dist/block-library/theme.min.css included on front end

**Expected behavior**

I would expect both versions of my site behave the exact same, meaning that both sites load the same CSS. 

**Screenshots**
Yes
![blockquote](https://user-images.githubusercontent.com/9561866/55123542-469abe00-50c0-11e9-9df7-ed75b6e6441d.PNG)

**Comment by youknowriad** [comment]
These stylesheets are opiniated block styles that a theme can opt into. A theme can include these styles by doing this https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#default-block-styles

You're probably opting in in one of your installs?

**Comment by stljeff1** [comment]
Well, I am developing my own blocks, so yes, that featured is enabled on both installs.

So why does this style sheet show up on one install and not the other?

Furthermore, why are editor styles being included on the front end of my staging instance?

**Comment by youknowriad** [comment]
> Furthermore, why are editor styles being included on the front end of my staging instance?

Do you have other block plugins, some of them were doing this inadvertantly

> So why does this style sheet show up on one install and not the other?

I can't explain it, if you're opting in in, it should be loaded in both.

**Comment by stljeff1** [comment]
Fair enough. Thanks for validating my confusion. I did have a suspicion that you were loading extra styles on all new WP installs, but leaving legacy installs alone. Or, my hosting provider was injecting the styles. It seems both suspicions are false.

for anyone who is trying to get rid of these extra style includes, I am using the following code:

`

function dequeue_blocks_css() {

    wp_deregister_style('wp-block-library-theme');
}

add_action('wp_enqueue_scripts', 'dequeue_blocks_css', 999);

`

the '999' priority argument is crucial as the 'wp-block-library-theme' is queued very late in the process.

**Comment by youknowriad** [comment]
Noting that if you don't want these styles in the frontend, you should just remove this call from your theme, it should have the same effect.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#default-block-styles
