### ISSUE TITLE
Add option to keep drag handles in spotlight mode 

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#14670]
Hi from UF Health again. We wanted to use spotlight mode and fixed toolbar mode as defaults for our admins and to 1) give them an easier focused way to navigate the blocks since most of them are not technically savvy and 2) with the fixed toolbar give them some parody with tools they already use like Word where the toolbar is up top. However, once we made spotlight mode default for users, we noticed the the drag handles disappeared. 

I'm aware based on this comment https://github.com/WordPress/gutenberg/pull/9569#issuecomment-421925713 that spotlight mode is for focusing. This is also the reason why we want it as the default for our users. However, our users also find that drag functionality extremely useful as they create their layouts. Ideally, we would like the option to keep drag handles in spotlight mode and make that decision ourselves as far as whether users need that functionality or not. Since we have 1000's of admins through our network, we're already hearing complaints about the drag handles disappearing forgetting that they switched to spotlight mode. 

Again, maybe something either set in the block_editor_settings or a door in one of the data modules to hook in and enable drag handles would be great.

**Comment by jorgefilipecosta** [comment]
I confirmed that in spotlight mode the drag handles don't appear making moving the blocks very hard.

Hi @kjellr, @mapk, @melchoyce do you any thoughts about how the design should look for drag handles in spotlight mode?

**Comment by mapk** [comment]
I'm totally open to just adding them back the way they exist now. It's super frustrating trying to move blocks in spotlight mode without them.

This is what adding them back would look like.

![spotlight-mode](https://user-images.githubusercontent.com/617986/55209399-9308fb00-519f-11e9-961a-e3034f9baf01.png)

**Comment by kjellr** [comment]
Sounds good to me too. 👍
