### ISSUE TITLE
CSS changes to RichText broke core and custom blocks layout

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#14674]
Splitting this out from #14366 

https://github.com/WordPress/gutenberg/pull/14366/commits/9b84916f46464a8a2b36d30cd0f07ddd31c42bfc removed the top margin reset from the RichText editable area.

The removal of the margin is a breaking change for custom blocks that reuse RichText within a block. Example:

Before:

<img width="779" alt="custom before" src="https://user-images.githubusercontent.com/1682452/55141254-4c34ea00-513a-11e9-8a5b-0a1c0138f889.png">

After:

<img width="770" alt="custom after" src="https://user-images.githubusercontent.com/1682452/55141260-4fc87100-513a-11e9-835f-f73608dc28c5.png">

It's also breaking the core reusable blocks > edit mode:

Before:

<img width="774" alt="reusable before" src="https://user-images.githubusercontent.com/1682452/55141291-653d9b00-513a-11e9-8d59-1815877d148c.png">

After:

<img width="784" alt="reusable after" src="https://user-images.githubusercontent.com/1682452/55141300-6a024f00-513a-11e9-92be-c2b8578876e8.png">

I suspect there are also other cases.

I'm not sure this kind of changes can be made so lightly. Even if this is "just" CSS, it can break things because it's changing the expected rendering.

There has been a recent discussion on Slack about what can be considered a breaking change and what the level of backwards compatibility should be. There's a tendency to consider CSS changes as something that doesn't need backwards compatibility because not part of a "formalized API". Honestly, I really don't mind when discussions like that are made in a so abstract way without considering the real consequences for the developers ecosystem out there.

Trying to keep up with these changes is exhausting and not sustainable, especially when they're not communicated well in advance and with great relevance.

That said, this is breaking also the core blocks thus it's an issue that should be addressed in some way.

**Comment by m-e-h** [comment]
@afercia I'm trying to reproduce this.

I thing you're referring to removing the `.editor-rich-text__editable { margin: 0 }` which was discussed some here https://github.com/WordPress/gutenberg/pull/14407#discussion_r265105012
I do know @jasmussen pinged several people more than once about that particular change.

When I add the `0` margin back it does remove the browser default or in this case `common.css`'s `1em` top margin on the `p` tag. 

It's my understanding that one of the goals of the [commit](https://github.com/WordPress/gutenberg/pull/14366) this is about and the [one I linked above](https://github.com/WordPress/gutenberg/pull/14407) is to let the intended styles of the content shine through.

If your theme either adds a margin or doesn't remove the browser margin on `p` tags then I think it could be argued that your "after" screenshot is the way it should look and the "before" is actually a bug. 

I'm just talking about the reusable paragraph block though. It's hard to tell what's going on with the custom block. Is that a `li` or is it a `p` element as well?

> Even if this is "just" CSS, it can break things

The fact that CSS has been an afterthought for much of this editor's development isn't lost on me.

**Comment by m-e-h** [comment]
Gallery-item captions are also showing issues with the recent `figcaption` changes. 
The `.editor-rich-text__editable { margin: 0 }` would fix these in the editor but the front-end is also effected.

Both the front-end and the editor need the margin-bottom removed.

![Screenshot_2019-03-29 Gut Check – one wordpress test](https://user-images.githubusercontent.com/3585901/55205953-3a3f5f80-51ab-11e9-9759-6edb675c02e4.jpg)

I'll can try to put together a PR in the next day or two.

**Comment by afercia** [comment]
@m-e-h thanks for looking into this. I see you've clarified (by striking-through the related sentence) this has nothing to do with a theme. Actually, I'm testing with Twenty Nineteen. Regardless, this happens with all themes.
- Whatever we put it, this is a breaking change simply because "it breaks things".
- Besides custom blocks, so far we've identified two cases where this change breaks core blocks too: I suspect there are more. For example, I'd be curious to see what happens with nested blocks.

Seen from a plugins developer perspective, having to keep up with this kind of changes is not sustainable. I'd strongly recommend to consider that, at this point of the project, also some important CSS changes should be communicated well in advance as potential breaking changes.

**Comment by youknowriad** [comment]
This is more a communication issue and I think we've been doing better at communicating how our CSS changes can affect plugin authors and third party blocks. We can always do better though.
