### ISSUE TITLE
Display heading levels dynamically in Heading Options when Heading block is selected

### ISSUE THREAD

**Issue by igmoweb** [WordPress/gutenberg#14688]
So far, the heading levels are hardcoded in the Heading Edit component.

![Captura de pantalla 2019-03-28 a las 18 13 33](https://user-images.githubusercontent.com/1516569/55178233-49131b80-5185-11e9-947f-259aa3a2f565.png)

Here are the current lines of code in `public_html/wp-content/plugins/gutenberg/packages/block-library/src/heading`:

```js
<HeadingToolbar minLevel={ 2 } maxLevel={ 5 } selectedLevel={ level } onChange={ ( newLevel ) => setAttributes( { level: newLevel } ) } />
```

And 

```js
<HeadingToolbar minLevel={ 1 } maxLevel={ 7 } selectedLevel={ level } onChange={ ( newLevel ) => setAttributes( { level: newLevel } ) } />
```

However, under some circumstances, this selection could be limited by using `blocks.registerBlockType` filter to a reduced set of headings. Right now this is tricky due to the hardcoded numbers.

**Describe the solution you'd like**
Dynamically, extract the level numbers from `selector` attribute in `attributes.content` for Heading Block and generate the range of selectors based on that list.

I'm pushing a PR to demonstrate in a sec.

**Comment by igmoweb** [comment]
PR: #14689

**Comment by skorasaurus** [comment]
This is being tracked in https://github.com/WordPress/gutenberg/issues/20213 where there's a bit more discussion on accomplishing this.
