### ISSUE TITLE
gutenberg in category and tags page

### ISSUE THREAD

**Issue by rmanshk** [WordPress/gutenberg#14696]
we can use gutenberg for post and pages , but we have important tags and posts pages , and other taxonomy that need gutenberg as editor 
how can i enable gutenberg for taxonomy 
with gutenberg we can write better and clear writing 
is there any small plugin for activating gutenberg anywhere we want ? or an option for gutenberg to work in everywhere we need ?

**Comment by FrancisMarkert** [comment]
Categories are really important for our projects. Therefore we also need the Gutenberg editor for taxonomies.

**Comment by youknowriad** [comment]
With the Full site editing work happening, using the block editor to build taxonomies templates will be possible. I suggest following the "Full Site Editing" label in the repository. These things are still very experimental but we'll be iterated on during the next months.

See #16281 and https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Full%20Site%20Editing
