### ISSUE TITLE
Drop Cap font?

### ISSUE THREAD

**Issue by bobbyso** [WordPress/gutenberg#14700]
How I change only the font of drop-cap (only first letter) like size in block settings?

**Comment by swissspidy** [comment]
This is currently not supported by the editor and I doubt that this is something many people would use.

Your best bet would be using some custom CSS to change the font for the first letter.

**Comment by bobbyso** [comment]
How?

I can change the font to the whole paragraph, but not to the first letter..

**Comment by ellatrix** [comment]
Should be possible with `.has-drop-cap::first-letter`?
