### ISSUE TITLE
Unwanted line breaks & Paragraph in Layout elements More

### ISSUE THREAD

**Issue by chinmayrajyaguru** [WordPress/gutenberg#14701]
**Describe the bug**
WordPress Gutenberg is adding HTML P & BR tag in Layout elements of More. How can I rid off this issue? 

**Screenshots**
https://prnt.sc/n4mo96

**Additional context**
- The version of Gutenberg: 5.1.1
- The version of WordPress: 5.3.0

**Comment by noisysocks** [comment]
I wasn't able to reproduce this in the latest Gutenberg plugin version. It may be that there's a plugin causing the extra markup to be inserted.

@chinmayrajyaguru: Could you try disabling all plugins and providing steps to reproduce this issue? Will then be happy to re-open the issue and investigate 😀
