### ISSUE TITLE
Add the ability to quickly check the Gutenberg/Block-Editor Version

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#14708]
To help with bug reporting, it can be very useful to be able to check which version of the Block Editor we're using in the UI, without needing to trace the WordPress version release notes to discover the bundled Gutenberg version. Other programs do this in an about section.

Example About Sections:
<img width="721" alt="Screen Shot 2019-03-29 at 8 55 51 AM" src="https://user-images.githubusercontent.com/1270189/55245543-96809e80-5200-11e9-808b-872d537bc57c.png">

<img width="630" alt="Screen Shot 2019-03-29 at 8 56 41 AM" src="https://user-images.githubusercontent.com/1270189/55245560-9e404300-5200-11e9-88b8-8c2d6e8cd0a9.png">

**Comment by mapk** [comment]
Can a use case be provided here? It feels like a very edge case, but I want to understand this more.

**Comment by gwwar** [comment]
@mapk To quickly check what version of Gutenberg someone is using. This isn't obvious even for developers, since the Gutenberg version (unless I missed it) typically isn't included in WordPress release notes, and digging in packages_versions https://github.com/WordPress/WordPress/blob/3d84726ae8f5eb9f477367394e62a071966fdb29/wp-includes/script-loader.php#L226 we can maybe make a guess, but it still takes time.

Knowing what version of Gutenberg folks are having trouble with saves a lot of time in triage/debugging.

**Comment by gwwar** [comment]
If I'm reading the changesets, correctly it doesn't look like we'd have access to a handy package.json to power this. Maybe add a var here to return the Gutenberg'ish version tied with WordPress or the plugin value.

This may not be that clean either. We may need to rely on the pinned list of WordPress npm packages.

For example here's a straightforward bump to Gutenberg 5.3 https://core.trac.wordpress.org/changeset/44960

But then we also cherrypick ahead from Gutenberg 5.5 for a WordPress bugfix release.
https://core.trac.wordpress.org/ticket/46951

**Comment by mapk** [comment]
> Knowing what version of Gutenberg folks are having trouble with saves a lot of time in triage/debugging.

True. I'm just not sure providing a UI is necessary. I like the idea of being more explicit in the WP release notes, but understand even that may get complicated. Can we raise this in a Core meeting in slack? I'd love to find a way to utilize dev notes instead of creating an interface right now.

**Comment by aduth** [comment]
For WordPress patch releases specifically, they cannot be tied back to Gutenberg releases, because these commits are cherry-picked into custom releases ([documentation](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#minor-wordpress-releases)). This would complicate how the information is presented, since it's often not possible to identify a particular Gutenberg release that a site is running from.

**Comment by mapk** [comment]
Because of the limitations involved with clearly identifying a Gutenberg version (since we cherry pick a bunch of stuff) I'm going to close this for now. If you have some others thoughts around how to resolve this, please open it back up. Thanks!

**Comment by koke** [comment]
Even without an UI, why don't we tag what goes into core releases on GitHub?

**Comment by phpbits** [comment]
Looking forward on accessible variable to check version as well. Would be really for compatibility and deprecations. Thanks!

**Comment by phpbits** [comment]
Adding one on [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. Here's the preview on what I have so far. Thanks!

![check the Gutenberg/Block-Editor Version (2)](https://user-images.githubusercontent.com/3365507/66839587-3df4d100-ef99-11e9-8f1e-2076be66bffd.gif)
