### ISSUE TITLE
Selected Gallery item close control causes overflow and hoz scrollbar

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#14704]
When set to full width, the rightmost item within the Gallery cause a 1px hoz scrollbar to appear _when selected_. This is caused by...

```
<div class="block-library-gallery-item__inline-menu" />
```

...which has a negative offset of `-2px`.

**To Reproduce**
1. Open Firefox (it's easier to see the scrollbars - Chrome appears to compensate)
2. Install [a Theme which does not enqueue editor styles](https://github.com/WordPress/gutenberg-starter-theme) 
3. Add a Gallery with 6+ images
4. Make it full width
5. Select the _rightmost Image_
6. See hoz scrollbar appear on editor

**Expected behavior**
Should not have a hoz scrollbar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - Browser Chrome, FF, Safari (everything really)
 - Version (unknown - likely all)

**Additional context**
- Gutenberg 5.3

**Comment by kjellr** [comment]
**Screenshot:** 

![gallery-select](https://user-images.githubusercontent.com/1202812/55239141-6e973800-520c-11e9-884e-6cc3acb55df9.gif)

**Comment by rebeccaj1211** [comment]
I can't seem to to replicate this issue. Did you already fix it?

https://media.giphy.com/media/1wPWNnhA2BxirgkXFe/200w_d.gif

**Comment by getdave** [comment]
@rebeccaj1211 Apologies there were some other conditions needed to replicate this issue that in my haste I forgot to add.

I've now updated the Issue with these details (see above). For your info you need to both:

- Open Firefox (it's easier to see the scrollbars - Chrome appears to compensate)
- Install a Theme which does not enqueue editor styles

**Comment by kjellr** [comment]
Just noting that this seems to have spread: Galleries in general seem to cause horizontal scrolling, even when no item has been selected: 

![gallery](https://user-images.githubusercontent.com/1202812/60288312-eba47d00-98e1-11e9-87f0-3e3fe182bd2b.gif)

**Comment by pyronaur** [comment]
@getdave @kjellr I just tried this in FireFox 72 and Chrome 79 and I can't reproduce this. Is this still an issue?

**Comment by obenland** [comment]
@getdave It looks like Galleries can't be aligned wide anymore? I was not able to reproduce the bug, would you mind double-checking when you get a chance?

**Comment by getdave** [comment]
Can no longer replicate.
