### ISSUE TITLE
[Question] Extra p tags surrounding reusable block

### ISSUE THREAD

**Issue by willstocks** [WordPress/gutenberg#14709]
I don't know if I've done something wrong here, but essentially...

I have a custom shortcode setup:
```php
function postads() {
    return '<div id="adsense"><ins class="adsbygoogle" style="display:block; text-align:center;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-5933273263680205" data-ad-slot="7397086054"></ins></div>';
}
add_shortcode('googlead', 'postads');
```

I have then added that shortcode to a previous post and have then set that up as a reusable block.

Up until recently (or maybe I had just never noticed before... I'm sure I would have though!) this worked fine. However running Gutenberg 5.3 (plugin) I'm now seeing an extra `<p>` and `</p>` wrapping the `div`.

Screenshot from `view-source`:
![Screenshot 2019-03-29 at 17 27 00](https://user-images.githubusercontent.com/43744514/55251226-eafb3c80-5247-11e9-8c13-163fbd21fabc.png)

Screenshot from devtools (which is the one that threw me off initially, due to an empty element either side!):
![Screenshot 2019-03-29 at 17 28 18](https://user-images.githubusercontent.com/43744514/55251287-1aaa4480-5248-11e9-9fd4-cbef8723b154.png)

Have I done something wrong, is this intended behaviour (seems a waste!) or is this a bug?

**Comment by noisysocks** [comment]
I'm unable to reproduce this in the latest Gutenberg `master` + WordPress `trunk`.

I registered the shortcode by adding this:

```php
function postads() {
    return '<div id="adsense"><ins class="adsbygoogle" style="display:block; text-align:center;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-5933273263680205" data-ad-slot="7397086054"></ins></div>';
}

function blah() {
    add_shortcode('googlead', 'postads');
}

add_action( 'init', 'blah' );
```

I then inserted a shortcode block with `[googlead]` in it and turned that block into a reusable block.

When I previewed the page using the default theme, there was no wrapping `<p>`.
