### ISSUE TITLE
Grey placeholder color is inconsistent in the Shortcode block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14718]
The Shortcode block's background placeholder grey is lighter than the other greys used in the other block placeholders setup screens.

**To Reproduce**
1. Add an Image block and observe the grey background.
2. Add a Shortcode block and observe the grey background.
3. Add an RSS block and observe the grey background.

![Screen Shot 2019-03-29 at 5 52 05 PM](https://user-images.githubusercontent.com/617986/55269133-77f4c480-524d-11e9-8082-4c5f40c722b6.png)

**Expected behavior**
The grey background on the Shortcode block should match all the others.

All the others use the `.components-placeholder` style which uses the `background: rgba(139, 139, 150, 0.1)` but the Shortcode block doesn't use the `.components-placeholder` styles.

I'd like to see something like this instead, but maybe we can at least get a PR to fix the color.

![Screen Shot 2019-03-29 at 6 06 53 PM](https://user-images.githubusercontent.com/617986/55269142-8ba02b00-524d-11e9-9c94-a505705b31c6.png)

**Comment by melchoyce** [comment]
Looks good 👍👍👍

During [triage](https://wordpress.slack.com/archives/C02S78ZAL/p1554222042046800), we determined that we should move forward with @mapk's proposal and PR, and make a follow-up issue to increase the amount of lines available within the shortcode `textarea`, to better support multi-line shortcodes.
