### ISSUE TITLE
Typing in the inserter should automatically start searching

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1471]
Somewhat related to https://github.com/WordPress/gutenberg/issues/1378, it might be useful to make it so that when I click the insert button, I can immediately start typing and have it filter through the blocks. 

This would save time as I wouldn't have to click on the search input field and then start typing. I don't know if this is a separate issue from #1378 or not.

Thoughts?

**Comment by afercia** [comment]
I think this is already in the works, as 2 separate features:
- move the filter field to the top and autofocus it when the inserter opens see #1187 
- implement a-z filtering (like in native select elements) see #1064 
Please feel free to re-open if I'm missing something.

**Comment by jwold** [comment]
Perfect thanks! Agree that we should close this, and I've followed up on #1064
