### ISSUE TITLE
Twitter block: A tweet with media causes resizing loop when aligning left or right

### ISSUE THREAD

**Issue by zackkatz** [WordPress/gutenberg#14722]
### STROBE WARNING - A repeating GIF is embedded below.

**Describe the bug**
When a Tweet is embedded that has an image or video, and then is aligned to the left or the right, the block will resize itself in a loop. 

This only affects the block editor, not the front-end.

**To Reproduce**
1. Create a new post or page
2. Embed a tweet that contains a video or image
3. Align it to the right or the left
5. Align it to the middle
6. Error no longer occurs

Tweets I tested with:
https://twitter.com/mgratch/status/1025802852881588224
https://twitter.com/SiteLock/status/1025797554401955842

**Expected behavior**
The block maintains a consistent size and does not resize.

**Screenshots**

![GIF showing the bug in action](https://user-images.githubusercontent.com/870979/55279001-f77ba580-52d8-11e9-9b97-489eab58828c.gif)

Here's a video showing the full experience of aligning right and then center: https://share.gravityview.co/SnQfxR

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Safari
 - Version: 12

**Additional context**
- Running WordPress 5.1.1
- Occurs with the Twenty Nineteen, Twenty Seventeen, Twenty Sixteen themes, Retro Blog themes
- Does _not_ occur with the Steven theme

**Comment by jorgefilipecosta** [comment]
Hi @zackkatz, thank you for reporting this issue! I'm not able to reproduce this issue anymore (tested on safari with the samples provided on the last version of WordPress with the last version of the Gutenberg plugin), It was probably solved as a side effect of other change. If you are still able to reproduce the problem, feel free to comment/reopen the issue and we will look further into the problem.
