### ISSUE TITLE
Mobile: Highlight Causing Overlap with Toolbar

### ISSUE THREAD

**Issue by Aurorum** [WordPress/gutenberg#14727]
**Describe the bug**
Highlighting text on mobile renders the controls unusable

**To Reproduce**
1. Let's pick a common example, on a mobile device, add a paragraph block
2. Write a paragraph
3. Highlight a word
4. Try to make it bold... 

**Expected behavior**
The settings on mobile devices to be located in an accessible way to prevent an overlap, rendering the settings essentially unusable on highlight, which is _incredibly_ frustrating for any mobile experience. 

**Screenshots**

![Screenshot_20190330-145140](https://user-images.githubusercontent.com/43215253/55282649-866fd880-5340-11e9-84ea-eecab7e94686.jpg)

Using an Android, Samsung Galaxy Tab S2 on Chrome 71

**Comment by draganescu** [comment]
I think this is solved now by the fixed top toolbar. @Aurorum can you confirm we can close this?

**Comment by Aurorum** [comment]
Yes, thank you! :)
