### ISSUE TITLE
Update 'Move to trash' to 'Move to Trash' to match core

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/gutenberg#14720]
**Describe the bug**
The capitalization convention in core is 'Move to Trash' with a capital T, in the block editor the button uses 'Move to trash' with a lowercase t.

**To Reproduce**
1. Navigate to the block editor.

**Expected behavior**
Match core and have the button state 'Move to Trash'

**Screenshots**
<img width="273" alt="Screen Shot 2019-03-30 at 12 22 09 AM" src="https://user-images.githubusercontent.com/8726005/55272968-2286da80-5282-11e9-8693-639f69581e89.png">

**Comment by Soean** [comment]
@garrett-eclipse its already fixed, see #14591

**Comment by garrett-eclipse** [comment]
That's great news @Soean thank you
