### ISSUE TITLE
How to convert/parse raw html to wp gutenberg blocks using wp-blocks api?

### ISSUE THREAD

**Issue by Aligatro** [WordPress/gutenberg#14728]
Hi, i'm have a difficult with preparing my post data for importing it to the site. I'm want to convert all my raw html to gutenberg ready blocks (like `wp:paragraph
p>hello world</p> /wp:paragraph` ) to avoid manually transformation for each post. What happening now:

- Register a handler srcipt and dependencies - `wp_enqueue_script( 'filter', get_template_directory_uri() . '/js/article-filter.js', array('jquery', 'wp-blocks', 'wp-element'));`
- Calling rawHandler/pasteHandler - `
    var gutblock = wp.blocks.rawHandler({ 
        HTML:  '<p class="content">Hello world </p>',
    });`
- Get error - `Cannot read property 'attributes' of undefined`

Maybe i'm something misunderstood in main concept or do something wrong. 
Will be very appreciated for help.

**Comment by youknowriad** [comment]
This is very old. I think the problem here was that you're probably trying the conversion without loading the blocks or before.
