### ISSUE TITLE
Can't move block if it goes behind a left-aligned image

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1472]
If you add a Text block to the bottom of your content and then try to move it up the page, once it goes behind an image that is left aligned, you can no longer move the text block any further.

Here's a gif - https://cl.ly/3w1u0T3D0k37

Using plugin Version 0.2.0.

**Comment by truongwp** [comment]
It's a CSS problem. I have just created a pull request for fixing it.

**Comment by roikles** [comment]
I have just experienced this on a fresh install. 

I had a Left aligned image followed by a Cover Image block and until I unchecked left align I couldn't use the move up/move down buttons.

Wordpress **4.9.2** and Gutenberg plugin version **2.1.0.**
