### ISSUE TITLE
Responsive embeds are squished in the editor sometimes

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#14738]
**Describe the bug**

Sometimes responsive embeds like YouTube will be squashed and have whitespace in the editor. They seem to be fine on the front end.

**To Reproduce**
1. Open an incognito window so that all assets are loaded fresh
2. Start a new post
3. Embed a youtube video, e.g. https://www.youtube.com/watch?v=nnAaJ6Wc5nM
4. Paste the url into an empty block so it embeds a second time
5. See this:

![squish](https://user-images.githubusercontent.com/3314354/55322359-0e0a3400-5474-11e9-9233-974543abae1a.png)

If you publish the post and reload the editor, usually it's fixed, but the first time, it's squished.

**Desktop (please complete the following information):**
 - Browser: latest Chrome

**Comment by notnownikki** [comment]
You also have to embed a youtube video you've not embedded before and clear your cache, so nothing is cached at all.

**Comment by notnownikki** [comment]
seems like it might be related to the resizing iframe, watching the dimensions, the height isn't changing

**Comment by notnownikki** [comment]
and sometimes, embedding the video again will result in a scrollbar.

**Comment by notnownikki** [comment]
The problem is that the `Sandbox` component is built to allow us to replace the HTML inside it, however when we change the `className` to add responsiveness without changing the HTML, the margins get applied over what's there. For some reason the responsive classnames are applied in a second render after the initial render of the preview. That shouldn't happen.

**Comment by notnownikki** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/14748 which ensures the responsive styles are applied on the first render.

**Comment by draganescu** [comment]
This is fixed by #14748 which is merged.
