### ISSUE TITLE
Some E2E tests fail on the Docker environment 

### ISSUE THREAD

**Issue by ashwin-pc** [WordPress/gutenberg#14732]
**Describe the bug**
On a fresh clone of the Gutenberg repo on a new docker instance, some of the e2e tests fail. 

**To Reproduce**
1. Clone the Gutenberg repo
2. Setup a new Docker environment
3. Run `./bin/setup-local-env.sh`
4. Run `npm run build`
5. Test using `npm run test-e2e`
6. Some tests/snapshots fail (see attached screenshot below)

**Tests Failing**

- [x]  Reusable Blocks › can be created from multiselection
        `Error: waiting for selector "button[aria-label="More options"]" failed: timeout 30000ms exceeded`
- [x]  Reusable Blocks › multi-selection reusable block can be converted back to regular blocks
         `Error: No node found for selector: button[aria-label="Multi-selection reusable block"]`
- [x]  (Snapshot) RichText › should apply formatting with access shortcut
         `Expected - <p><s>test</s></p>`
         `Received + <p>test</p>`
- [x]  (Snapshot) RichText › should apply formatting with primary shortcut
         `Expected - <p><s>test</s></p>`
         `Received + <p>test</p>`    
- [x]  Multi-block selection › Should select/unselect multiple blocks
    `Expected: StringContaining "is-multi-selected"`
    `Received: "wp-block editor-block-list__block block-editor-block-list__block is-selected"`
- [x]  Multi-block selection › should speak() number of blocks selected with multi-block selection

**Expected behavior**
All test should have passed.

**Screenshots**
![image](https://user-images.githubusercontent.com/20453492/55293196-f4a8af80-53c1-11e9-970a-032f52530214.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by gziolo** [comment]
@aduth - it all looks similar to the Puppeteer’s bug with select all shortcut behavior. I’m wondering if there are other issues present.

**Comment by aduth** [comment]
Yes, it's highly likely these are all related to the same Cmd+A emulation issue under consideration for resolution by #14243 (the underlying issue described at https://github.com/GoogleChrome/puppeteer/issues/1313 )

**Comment by ashwin-pc** [comment]
@gziolo The PR #14243 Has since fixed all these failures and in the commit (454011ee865f1d245ac061cdb1438f8fa21e3e6a) in which the PR was merged in passes all the test cases. But the latest master brach fails one test not in this list. Do i raise a new issue on it or update this Issue by adding it here and marking the resolved ones as checked.

**Comment by gziolo** [comment]
@ashwin-pc, thank you for confirmation. Let's close this one and report the new issue independently. I did a quick check of open issues labeled with [Automated Testing](https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22Automated+Testing%22+) and it looks like we don't have any reports of known tests that fail locally.
