### ISSUE TITLE
Edit Post: Avoid using block editor classname in PluginBlockSettingsMenuItem

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14749]
Previously: #14745

The `PluginBlockSettingsMenuItem` and `PluginBlockSettingsMenuGroup` components should not be applying the block editor class names directly, per [CSS Naming Guidelines](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#naming) which prescribe that a class name must be named according to its package directory (and conversely, _not named_ using classes outside its package directory).

Possible action steps:

1. Eliminate the `block-editor-block-settings-menu__control` class name altogether. If it's assumed to be of type `wp.components.MenuItem`, then `BlockSettingsMenu` can simply target that class name (`.components-menu-item__button`) directly [in its own styles](https://github.com/WordPress/gutenberg/blob/ad7d183b493177992b720b66506f1cc71dd95b0a/packages/block-editor/src/components/block-settings-menu/style.scss#L36).
2. Abstract components in `block-editor` which apply the necessary class names, to be used by `edit-post` and others.

**Comment by paaljoachim** [comment]
Is this issue still relevant?

@gziolo

**Comment by gziolo** [comment]
I can't find those class names anymore. Let's close it, thanks!
