### ISSUE TITLE
Tab index lost after adding Table blocks in Firefox 67

### ISSUE THREAD

**Issue by svenvanhal** [WordPress/gutenberg#14753]
When adding a table block using either just the mouse or by using keyboard shortcuts, the "tab location" / tab index get lost.  This probably also holds for other blocks.

This behavior is observed using Gutenberg 5.4.0-rc.1in Firefox 67.0b6, but is not in Chromium 71.0.3578.98.

**To Reproduce**
1. Add new post
2. Click the `+` icon below the page title to add a Table block.
3. "Accidentally" press `Arrow Down` to lose focus, then `Arrow Up` to regain focus of the Table block.
4. Press `TAB`

Or:
1. Add new post
2. Press `Arrow Down`, 4x `TAB`, `ENTER` to "Add block"
3. Type "Table", press 3x `TAB`, `ENTER` to select the Table block.
4. "Accidentally" press `Arrow Down` to lose focus, then `Arrow Up` to regain focus of the Table block.
5. `TAB` to select the "Create" button and press `ENTER`
6. Press `TAB` to observe the lost document position.

Note that if the Table block keeps focus during this process, the first cell is selected as expected.

The issue **pops up in different places and in different forms** (sometimes, the browser toolbar gets focus, sometimes the first item in the DOM, sometimes the hidden "Open Publish Panel" button in the bottom right) depending on the sequence of steps and using keyboard or mouse. For example, this issue even pops up without losing focus in between when adding a third consecutive table.

Similar behavior is observed when adding a Gallery or Image block.

**Expected behavior**
Pressing `TAB` right after adding a table should select the first cell of the table.

**Desktop (please complete the following information):**
 - OS: Windows 10 (build 1809)
 - Browser Firefox Developer Edition 67.0b6 (broken)
 - Browser Chromium 71.0.3578.98 (works)

**Comment by youknowriad** [comment]
I'm not able to reproduce this issue.
