### ISSUE TITLE
The has_block function does not work on blogroll index views

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#14758]
**Describe the bug**
The `has_block()` function ([link](https://developer.wordpress.org/reference/functions/has_block/)) from #9058 **does not return true** if a particular block is present on a blogroll index/archive/search view. The function does work as expected on a single page. Perhaps there's another way we should be checking for blocks that would function everywhere?

**Expected behavior**
The `has_block()` should return true if a block is included on a blogroll page.

**Additional context**
- Tested on 5.1.1, as well as Gutenberg 5.3

**Comment by swissspidy** [comment]
What is your goal?

Worth keeping in mind the purpose of `has_block()`: to determine whether a `$post` or a string contains a specific block type. By default it checks the global `$post` object.  If you want to know whether there are _any_ blocks _anywhere_ in the current archive view, you'd have to loop over all posts in the view and run `has_block()` for each of them.

**Comment by youknowriad** [comment]
I'm going to close as it has a good reply.
