### ISSUE TITLE
Classic Editor Block breaks when parsing li tags with attributes

### ISSUE THREAD

**Issue by omacranger** [WordPress/gutenberg#14779]
**Describe the bug**
When parsing HTML lists with attributes applied (inline styles, data attributes) applied to a child the output of the classic block will malform the original HTML and output multiple nested or sibling lists breaking the context of the list to crawlers, readers, etc.

I'm specifically running into this when disabling the Classic Editor plugin and converting existing pages, but this can be observed on a blank installation as well.

**To Reproduce**
1. Create page with below example as content set specifically through "Code Editor" toggle. The specific inline style here is irrelevant, just that an attribute that exists breaks the conversion process.
```html
<ul>
     <li style="text-align: center">List Item 1</li>
     <li style="text-align: center">List Item 1</li>
</ul>
```
2. Exit "Code Editor" and preview output of classic block, which will be as follows: 
```html
<ul>
<li style="list-style-type: none;">
<ul>
<li style="text-align: center;">List Item 1</li>
</ul>
</li>
</ul>
<p> </p>
<ul>
<li style="text-align: center;">List Item 1</li>
</ul>
```

**Expected behavior**
HTML output is kept as-is or rearranged without breaking the original purpose / context.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73

**Additional context**
- Fresh installation of WordPress 5.1.1

**Comment by youknowriad** [comment]
I'm not able to reproduce in Gutenberg. Can you try with the last Gutenberg plugin release?

**Comment by omacranger** [comment]
@youknowriad Looks like this is fixed in the plugin release for Gutenberg, thanks.

This can be marked as solved, but one more question if you're able: Are we able to set the default block that WordPress populates Gutenberg with if Gutenberg was not previously active? Using `core/html` instead of `core/freeform` - for example?

**Comment by youknowriad** [comment]
yes, it should be possible, try  `wp.blocks.setFreeformContentHandlerName( 'core/html' );`

**Comment by omacranger** [comment]
@youknowriad Do you have an example of where that is used? I was trying that method in the core release and was running into some issues with registerCoreBlocks overriding it on initialization.

**Comment by youknowriad** [comment]
I don't, it's used in the Gutenberg code, i guess to work properly, you should have a custom script and register it after `wp-edit-post` but before the block initialization. so try a script with the `wp-edit-post` dependency with only this in it. 

I agree that the timing issues about the different dependencies should be fixed. There's an open issue about it somewhere but this is a complex problem to solve.

**Comment by omacranger** [comment]
I'll give that a shot. I had a sort of hacky solution working with a subscribe on the `wp.data` store and a function to set that value manually with the Core version each time it changed - so it would always override it. I imagine with the [filter](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/filters/editor-filters.md) system Gutenberg has it would likely be more beneficial to setup an official way to handle gracefully changing some of those defaults
