### ISSUE TITLE
Inline Image block not found in Inline Elements on Search

### ISSUE THREAD

**Issue by damiannep** [WordPress/gutenberg#14773]
**Describe the bug**
Add a block and search for inline, the Inline Elements section is closed and it looks like there are no blocks with the word Inline:
![inline search](https://cld.wthms.co/5VP40I+)
*Full link: https://cld.wthms.co/5VP40I*

Here is a gif to the same effect
https://cld.wthms.co/M4FjH6

**To Reproduce**
1. Go to edit a post or page
2. Click to add a block
3. Search for Inline Image
4. No blocks are found.

**Expected behavior**
I expect the block to show up under Inline Elements.

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser Chrome
 - Version 73.0.3683.86

**Comment by gziolo** [comment]
@ellatrix, I guess this behavior changes in WordPress 5.2, right?

**Comment by youknowriad** [comment]
yes, the inline images are not considered blocks anymore and should be visible in the block toolbar instead.
