### ISSUE TITLE
docgen: add support for `@since` tag

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14774]
WordPress core tags symbols with the `@since` tag containing the relevant information (a symbol will have as many `@since` tags as modifications). Example: [code](https://github.com/WordPress/WordPress/blob/130495e1c48977cfee04ed16657797e3f1a3f155/wp-includes/theme.php#L2308), [generated docs](https://developer.wordpress.org/reference/functions/add_theme_support/#changelog).

A different use case would be to use the `@since` tags to auto-generate CHANGELOGs. Relevant [slack convo in core-js](https://wordpress.slack.com/archives/C5UNMSU4R/p1554214902038100).

**Comment by paaljoachim** [comment]
Is this issue still relevant? Should it be closed?

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
