### ISSUE TITLE
Unable to remove Featured Image

### ISSUE THREAD

**Issue by danielbento** [WordPress/gutenberg#14777]
**Describe the bug**
In a page or post, after adding a Featured Image, if you decide to remove it and not using any, you can't. You can only replace by another. The button from Tiny MCE "Remove Featured Image" disappeared.

**To Reproduce**
Add a Featured Image. Then try to remove it.

**Comment by draganescu** [comment]
Hi @danielbento could you provide more information? I could not reproduce the problem with the current WP release (5.1.1) and using the twentynineteen theme along with the default editor.

**Comment by youknowriad** [comment]
<img width="259" alt="Capture d’écran 2019-04-03 à 10 24 53 AM" src="https://user-images.githubusercontent.com/272444/55468194-bcd87c80-55fa-11e9-9686-a3c8507a1a5e.png">

I can't reproduce either, See the "Remove featured image" link in the screenshot.

**Comment by danielbento** [comment]
Hi Draganescu, for some moments I was confused. But I believe is a Responsive Issue.

Take a look at my sidebar in Gutenberg:
https://user-images.githubusercontent.com/5781957/55553277-b0762180-56d7-11e9-9088-82b50a44f824.png

The remove image Link is not visible. Take a look at this gif:
https://cl.ly/da1c120eff1a

And my browser window is fully opened in a Macbook Pro Laptop.

Hope it helps.

**Comment by jorgefilipecosta** [comment]
Hi @danielbento, is the image you are setting as feature image an SVG? Would it be possible to share an image that is causing this problem?

Thank you in advance.

**Comment by danielbento** [comment]
Hi Jorge,

yes exactly, it is an SVG image.

This one we are using on a page where it is causing the issue.

Hope it helps.

Daniel

**Comment by draganescu** [comment]
@danielbento how did you get the SVG in the media library? It is not among the types of supported files for uploading?

I have enabled SVG upload in the media library by the means of the `upload_mimes` filter, but even after the SVG was available, adding it to the featured image inspector slot resulted in no image showing. So I still can't reproduce the problem with the remove link disappearing :(

**Comment by danielbento** [comment]
Hi Andrei, yes you are right. I had to include in functions.php the SVG
file so that I could import to Wordpress Media. This ™gwas done a few
months ago. But now I'm getting some error saying it can't import SVG files
again. Strange.

So I guess you can close this ticket. Because now I know how to remove the
file. Just change to jpeg, and then I can remove.

I can't also reproduce the issue at this moment, excepts for the SVG's file
I have there already. So, it's up to you.

Thanks for your help anyway.

Best regards,
Daniel
