### ISSUE TITLE
Copy the new image block flow to the media + text block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#14788]
Now that the image block has a new clearer flow for replacing images it's a great idea by @mapk to copy the behaviour to the image + text block:

![image](https://user-images.githubusercontent.com/107534/55459547-81d54980-55f8-11e9-98e4-7350781832c0.png)

**Comment by talldan** [comment]
Also Audio, Cover, File, Video. 😄

**Comment by draganescu** [comment]
Closing in favor of #14795
