### ISSUE TITLE
Block validation failed in Block: Gallery post

### ISSUE THREAD

**Issue by pallavic27** [WordPress/gutenberg#14792]
There is an error in console when we edit the "Block: Gallery" post 

**To Reproduce**
Import WordPress test data
Edit post Block: Gallery post 
Right click and Inspect element
Go to consol
Can see this error
Block validation: Block validation failed for `core/spacer` ({name: "core/spacer", title: "Spacer", description: "Add white space between blocks and customize its height.", icon: {…}, category: "layout", …}).

Expected:

<div style="height:200px" aria-hidden="true" class="wp-block-spacer"></div>

Actual:

<div style="height:76px" aria-hidden="true" class="wp-block-spacer"></div>

**Expected behavior**
There should not be this error

**Additional context**
- WordPress V5.1.1

**Comment by youknowriad** [comment]
It seems like the error is in the test data you're trying to import. Where does it come from?

**Comment by pallavic27** [comment]
Yes - this post gets created when you import WordPress test data

**Comment by youknowriad** [comment]
but which test data?

**Comment by jha1395** [comment]
you can import data from here [(https://codex.wordpress.org/Theme_Unit_Test)]

**Comment by youknowriad** [comment]
Got it, thanks for the info. I reproduced and the issue is coming from the test data set. You should create an issue here instead https://github.com/WPTRT/theme-unit-test

Thanks.

**Comment by pallavic27** [comment]
Thanks for sharing.
