### ISSUE TITLE
Delete handbook page that was renamed

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14793]
In https://github.com/WordPress/gutenberg/pull/12751 https://wordpress.org/gutenberg/handbook/designers-developers/developers/backwards-compatibility/ was renamed to https://wordpress.org/gutenberg/handbook/designers-developers/developers/backwards-compatibility/

The old page is still available. We should delete it.

**Comment by gziolo** [comment]
Asked for help in #meta on WordPress Slack (link requires registration): https://wordpress.slack.com/archives/C02QB8GMM/p1554886839002700

**Comment by coffee2code** [comment]
The old page has been deleted and its slug has been redirected via [[meta-8621]](https://meta.trac.wordpress.org/changeset/8621).

**Comment by gziolo** [comment]
@coffee2code thank you 🙇
