### ISSUE TITLE
Source for data.min.js?ver=4.2.1:1

### ISSUE THREAD

**Issue by s1100h** [WordPress/gutenberg#14809]
Hello,

Issue: 
I am developing a WP plugin that utilizes react, redux, and webpack4. Currently, the plugin conflicts with the Gutenberg editor, because when it is activated this error appears. 

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 1

data.min,js?ver=4.2.1:1

```
I have come to the conclusion that its a conflict with the output of webpack config files.  Even though my files are only loading when a shortcode is loaded on a specific page template, somehow it is having an impact on the data.min.js file. 

This error, by the way, stops the Template Selection dropdown from the Page Attribute section in the sidebar. 

Question
What is the source file for data.min.js?ver=4.2.1:1?  I just want to poke around (NOT CHANGE ANYTHING) to see what is causing the SyntaxError, so I can modify my plugin's code to not affect it. 

Any assistance is greatly appreciated.

Thank you!

**Comment by youknowriad** [comment]
Thanks for opening the issue. Unfortunately this bug tracker is not well suited for help request.

Please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thanks
