### ISSUE TITLE
Including "babel-plugin-makepot" package in "wp-scripts"

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#14803]
I was wondering wether it would make sense, to include the `babel-plugin-makepot` package in the `wp-scripts` package. Of course it is possible to extend the `wp-scripts` yourself, but adding the plugin to the babel config would require you to do a lot of work, while including it would be much easier. 

And having translations of the javascript inside our blocks should be made as easy as possible, so developers can easily make their blocks accessible to the entire world.

**Comment by youknowriad** [comment]
Since this plugin is not useful anymore to internationalize your plugin/theme, I don't think we should do this.

**Comment by youknowriad** [comment]
Details about the updated i18n workflow are here. https://wordpress.org/gutenberg/handbook/designers-developers/developers/internationalization/

Thanks for the suggestion.

**Comment by fabiankaegy** [comment]
What is the best way of adding internationalization to js then?
I’m probably missing something. 😅

**Comment by youknowriad** [comment]
The document above should be a good start. This has been introduced a little bit before the WP 5.0 release.

**Comment by fabiankaegy** [comment]
Thanks for providing the information. But that I was familiar with. But isn't there anything we can do to make it easier than using the wp cli and the po2json command?

**Comment by youknowriad** [comment]
`wp-cli` is the current recommendation. See here as well https://github.com/WordPress/gutenberg/issues/14780#issuecomment-479420642

Why do you think using `wp-cli` is not easy enough?

**Comment by fabiankaegy** [comment]
I think that wp-cli is cool and works great. But I would have loved to have something that's included in the build process so you don't have to break out of the regular workflow for it. Especially when using a local setup where you are not connecting to the wp-cli all of the time it is just another step that you have to keep track of. Instead of just having the pot always reflect the step you are developing as in that second.

**Comment by youknowriad** [comment]
I think in theory, you don't need this step at all, you just need the `wp_set_script_translations` call. IIRC that's all you need to do. Of course you can still provide your own translations using the wp-cli tools. I believe since it's not something that's useful for everyone, maybe it shouldn't be in the default babel config.

@swissspidy @gziolo What do you think?

**Comment by gziolo** [comment]
I personally don't know. I'm waiting for the response from @swissspidy as well to learn more :)

**Comment by swissspidy** [comment]
Thanks for raising this @fabiankaegy!

`babel-plugin-makepot` only really does one task of many for you: extracting all your strings from JavaScript files and putting them into a POT file.

But there is so much more to the picture.

* If you are working on a WordPress project (which I assume you are when using `wp-scripts`), you also need to extract strings from PHP files.
* You need to translate all the strings.
* You need to put the translations into JSON format
* You need to pass the translations to `@wordpress/i18n`, preferably with `wp_set_script_translations`

**Note:** when your project is hosted on WordPress.org or [similar infrastructure](https://github.com/wearerequired/traduttore/) is in place, you don't need to worry about all that. You just use `wp_set_script_translations` and the translations are handled in the background.

As you can see, when developing a WordPress plugin or theme however, `babel-plugin-makepot` only gets you halfway there. You'd still need to use WP-CLI for the PHP string extraction. You'd still need to use WP-CLI for creating the JSON translation files.

You can, of course, use WP-CLI only for PHP string extraction and then combine the result with the POT file from the Babel plugin. That totally works. But WP-CLI can handle the JS string extraction just as fine, so why not use only that one tool?

The only two scenarios where I can see the Babel plugin still being useful:

1. You are not developing a WordPress project
2. Your project's final build only contains minified JS and you want to extract the translations before that and do something with them

In both these cases you can probably just manually add the Babel plugin to the build config. No need to put it into `wp-scripts` for that.

**Comment by fabiankaegy** [comment]
Thanks to all of you for talking the time to go over this :) And yes with all that in mind I agree that it should not be in there. 

If it were only the step of translating I would have said that's okay to have that different. But because you the need to convert that again you are 100% right.

The inspiration for this was the WPGulp workflow, where the pot for the php files always gets created right on the spot. But the javascript side just has more steps to it.

**Comment by swissspidy** [comment]
>  where the pot for the php files always gets created right on the spot

Please note that this is usually a bad idea. When a translator is not sure how to translate a certain string, they need to check out the source code to verify the context. But all they will see is a reference to the PHP file, not the JS file.

**Comment by fabiankaegy** [comment]
Thanks for the helpful insight :) manny things to learn every day
