### ISSUE TITLE
Image Block: Should be linkable

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1481]
The image block should be linkable. Here's one mockup for how that could work:

![screen shot 2017-06-27 at 11 00 25](https://user-images.githubusercontent.com/1204802/27579484-f5feae00-5b27-11e7-848f-826def1437db.png)

**Comment by iseulde** [comment]
Inspector? 🙃

**Comment by jasmussen** [comment]
Haha, inspectors everywhere now! 

I think making the image linkable should count as a basic action. It could be the inline toolbar that paragraphs get, but with 3 of the buttons hidden/removed.

**Comment by mtias** [comment]
I agree with pushing this one to the inspector next to the alt text 🙃

**Comment by jasmussen** [comment]
It's treason then. 

(Just kidding. I'm a Star Wars fan.)

I would be okay if it was an inspector thing _only_ if this was a temporary decision. I can think of many use cases where the image is more than decorative, including people making their own custom buttons, or just a book review where you want the image linked to Amazon. To me it absolutely feels like the Image block should have this button.

**Comment by jwold** [comment]
Has there been a definitive conversation somewhere to help with the decision process for inspector vs inline?

**Comment by jasmussen** [comment]
> Has there been a definitive conversation somewhere to help with the decision process for inspector vs inline?

Very few things in this process are definitive. They are only definitive insofar as we have to keep moving and make interim decisions along the way.

So far the split between _basic on the quick toolbar, advanced in inspector_ has informed the design from the early on:

- It helps us recast content in the sidebar as primarily being contextual/document metadata, which is helpful in suggestion what goes there. For example "recent drafts" is probably not a good thing to put in a side metabox, as it's not document contextual.
- It allows us to replace the old immersive mode with one where you simply toggle off the sidebar, and thereby ensure a simpler interface for people who only use basic features. Imagine a casual user who just wants to write, overwhelmed by metaboxes. They should feel relieved when toggling off the sidebar. 

Also wrote a bit about it here: https://github.com/WordPress/gutenberg/blob/master/docs/design.md

**Comment by jwold** [comment]
@jasmussen thank you! This distinction is helpful. Checking out the design.md resource as well.

**Comment by iseulde** [comment]
Alt text seems even more basic then, as it is required in HTML and very prominent in Markdown. But I get what you mean. I guess the boundary will always be vague.

**Comment by jasmussen** [comment]
I'd like to defend having the lone link button in the quick toolbar, as mocked up initially.

The pattern for the quick toolbar right now, is `[switcher] [block level] [style] [inline]`. 

The image block doesn't have a switcher (sorry, mockup is misleading), and it doesn't have a style picker. But it does have block level alignments. Also, the link is technically inline, as it wraps _only the image_. If you'd like to insert a link in the caption, you can do that separately. As such, I feel like you can consider this to be a stripped down version of the inline toolbar controls, and it's stripped down because bold, italic, strikethrough do not have an effect on images.

**Comment by mtias** [comment]
Implemented in #1772.
