### ISSUE TITLE
Select Image Size/Crop used with (add_image_size).

### ISSUE THREAD

**Issue by Shanery** [WordPress/gutenberg#14829]
Similar to: issue #13434

When Adding an image, we often want to have multiple crops of that same image. When using the image block, I should be able to click on image size and select the correct crop. This makes CMS much easier.

Currently the only alternative I can think of is reuploading the same image, and cropping it there and reinserting, which is a workable but really painful process.

**Comment by mapk** [comment]
The [Design Triage in slack today](https://wordpress.slack.com/archives/C02S78ZAL/p1558456772021300) confirmed that we'd like to see some sort of cropping ability linked with the Image block, but it feels like a much larger endeavor. 

I'm leaving this open, but we'll need a larger focus on the Media library/modal in the near future especially in light of all the a11y issues related to it.

**Comment by paaljoachim** [comment]
WordPress version: 5.6.1
Gutenberg plugin: 9.9.1
Chrome
A local test site.
OSX 10.15.7

--

We now have image tools among them a crop function in the Image block.

<img width="716" alt="Screen Shot 2021-02-10 at 11 05 34" src="https://user-images.githubusercontent.com/5323259/107495229-18c5a200-6b90-11eb-9029-2c2335768e04.png">

I will go ahead and close this issue. If I am mistaken then please reopen.
