### ISSUE TITLE
Revisions memory fatal

### ISSUE THREAD

**Issue by mikeyarce** [WordPress/gutenberg#14825]
**Describe the bug**
Gutenberg currently loads post revisions for two reasons:
1. It needs to see if there's an autosave that can be returned for a prompt
2. It returns a Revision count in a meta box (is that the right term to use?)

When a post has *many* revisions - I've seen fatal errors happen from memory exhaustion.

**To Reproduce**
1. Create a large post.  I created a `txt` file that was 2MB in size and used `wp post create` with that file to make the post.
2. Add revisions to the post.  I used `wp-revisions-cli` to generate revisions: https://github.com/trepmal/wp-revisions-cli
3.  Once you generate around 100 revisions, you should see a fatal error  (You can also lower your PHP's allowed memory size if you need to, sometimes developing locally means they are not set to "real world" standards).

**Expected behavior**
 Show revision count and autosave prompt.

I've submitted a patch to core for this issue and included some performance metrics and updated unit tests for the solution as well: 
Trac: https://core.trac.wordpress.org/ticket/34560#comment:69
Patch: https://core.trac.wordpress.org/attachment/ticket/34560/34560.15.diff

My patch is pretty simple, instead of getting the entire content for all revisions, we just need to get the IDs and count them.  I also changed `wp_get_post_autosave` to use a custom query instead of getting all the revisions entirely to check if there is an Autosave.  With those changes, I no longer see Fatal Errors in Gutenberg when my posts have a large amount of revisions.

I wanted to surface that here as well because these old bugs might not surface easily and I have a feeling not many people will look at my trac comment. 

My profiling results:
![Screenshot](https://core.trac.wordpress.org/raw-attachment/ticket/34560/small-post-performance.png)
![Screenshot](https://core.trac.wordpress.org/raw-attachment/ticket/34560/large-post-performance.png)

**Comment by noisysocks** [comment]
This is a bug in Core (https://core.trac.wordpress.org/ticket/34560), so closing this issue out. Looks like the Trac ticket has some traction and may land in 5.4 🙂
