### ISSUE TITLE
Block gallery: deselect first/last image

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14823]
When tabbing through the image galleries, the images at the edges (first/last) don't get deselected when focus changes to the toolbar (it tabbing backward from first image) or the media buttons (if tabbing forward from last image):

![Peek 2019-04-04 17-20](https://user-images.githubusercontent.com/583546/55567454-fa71fe00-56fd-11e9-8f39-49e2498cd4ec.gif)

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/14930 fixes this.

**Comment by talldan** [comment]
@nosolosw as you might be able to tell, I'm looking through a few past gallery issues! 

This one doesn't seem to be an issue any more in my testing. The keyboard navigation has changed quite a bit in the editor, so I think that may have resolved things. Having said that, I noticed you have an open PR that was recently rebased. Can you reproduce this in master?

**Comment by talldan** [comment]
Oh wait, I completely misread this issue 🤦‍♂ 

Ignore my comment above..

**Comment by nosolosw** [comment]
@talldan any change you could help get #14930  reviewed? It's been a bit difficult to give it the attention it deserves :)
