### ISSUE TITLE
Should double enter in a list block break out of the list and create a paragraph?

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1482]
Right now, if you create a list, you can't break out of it with enter. If you are at the last list item of a list, and it's empty, enter simply does nothing.

Should we change this so enter on the last empty list item not only removes that empty list item, but breaks out and creates a paragraph block?

**Comment by jwold** [comment]
That would be a helpful behavior if it broke out!

**Comment by karmatosed** [comment]
Adding user feedback:

"This came up in user tests and got me thinking how the current editor has trained people to expect to get out of lists. Could we add a way to double return out of a list block like you currently can?

Some user comments:

"I understand this is beta but it seems very limited if I can't even end a list and start another paragraph. It looks cool though and I think it'll be great when it gets more usable for real writing"

"Easy enough to do but when your on a new line of a list item (ie. you've entered text on point 2, then press enter and point 3 appears but is blank) you can't press enter again to stop the list like you can in the current editor.""

**Comment by mtias** [comment]
This has been implemented: https://github.com/WordPress/gutenberg/pull/2170
