### ISSUE TITLE
Gutenberg5.4 blocks bug macOS/iOS  Safari

### ISSUE THREAD

**Issue by danyanjp** [WordPress/gutenberg#14836]
無事戻りました。
ありがとうございます。

**Comment by danyanjp** [comment]
Describe the bug
Access list is not displayed on the new post screen.
If you look at the source code, the source code is output properly.
Only the visual screen comes out.

**Comment by youknowriad** [comment]
I'm having a hard time understanding the issue. What is missing from the new post screen?

**Comment by danyanjp** [comment]
> **Describe the bug**
> 新規投稿画面にアクセススト表示がされません。
> ソースコードを見るとソースコードはきちんと出力されています。
> ビジュアル画面のみ出てきません。
> 
> Describe the bug
> Access list is not displayed on the new post screen.
> If you look at the source code, the source code is output properly.
> Only the visual screen comes out.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'gutenberg5.4のみバグが起こります。5.4以下のバージョンを入れると表示がされます。　　Bugs only occur in gutenberg 5.4. It will be displayed if you enter version 5.4 or less.'
> 2. Click on '5.4未満を入れると表示はされます。しかしエラーが出て5.4未満のバージョンは使えません　　If less than 5.4 is inserted, it will be displayed. But I got an error and I can not use the version below 5.4'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> はじめに私は日本人です。英語を勉強していなため翻訳サイト使って翻訳しているのでおかしい英語だったらすみません。
> プラグインを全てオフにして検証をしました。
> その結果プラグインの競合の問題ではありませんでした。
> 完全なgutenberg5.4のバグです。
> しかし私はブラウザーの検証をした結果macOS/iOSのSafariで問題が起きました。
> macOS/iOSのGoogle Chromeでは問題が起きませんでした。
> 
> メインサイトのWordPressではmac/iOSのSafariでは問題が起きました。
> 問題がなかったのはmacOS/iOSのChromeでは問題が再発しませんでした。
> サブサイトのWordPressでは問題が起きませんでした。
> 
> それとGutenbergのバージョンを5.4未満を入れるとビジュアルエディターは表示されますが投稿に失敗しましたのようなエラーが出ます。
> 結局のところ5.4を入れたままにしないと使用ができないようです。
> 
> At first I am Japanese. I'm not studying English, so I'm translating using a translation site, so I'm sorry if it's funny English.
> I checked all plug-ins off.
> The result was not a plug-in conflict issue.
> This is a complete gutenberg 5.4 bug.
> However, as a result of verifying the browser, a problem occurred with Safari of macOS / iOS.
> There was no problem with Google Chrome on macOS / iOS.
> 
> There was a problem with mac / iOS Safari on the main site WordPress.
> There was no problem. The problem did not recur on macOS / iOS Chrome.
> There was no problem with WordPress on the sub site.
> And if you enter Gutenberg version less than 5.4, the visual editor will be displayed but you will get an error like post failed.
> After all, it seems that you can not use it without leaving 5.4.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS] macOS10.14.3
> * Browser [e.g. chrome, safari]Safari
> * Version [e.g. 22]12.0.3(14606.4.5)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]iPhoneXr
> * OS: [e.g. iOS8.1]iOS12.2
> * Browser [e.g. stock browser, safari]Safari
> * Version [e.g. 22]
> 
> **Additional context**
> 
> * Please add the version of Gutenberg you are using in the description.
> * To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.
