### ISSUE TITLE
Customizing Gutenberg Labels

### ISSUE THREAD

**Issue by leomuniz** [WordPress/gutenberg#14833]
Hey there! 
I'm creating an E-mail Marketing system (using an external API) with Gutenberg and I need to accomplish some things that I really don't know how even if researching a lot:
- Replace the word **Publish** and all its variations by **Send** (after all we send a mailing, not publish it).
- Replace the word **Document** on the right sidebar by **Mailing**
- To keep it very simple, I want to have only **Draft**, **Scheduled** and **Sent** (Published) mailing status. So I want to hide/remove the **Pending Review** checkbox, as the Visibility, that I want always private. 
- As, in the real life, when a mailing is Sent it's not possible to edit it (after all it is in people inboxes), I want to lock the CPT and all its metaboxes to be edited immediatelly after published.
- For the same reason I want to avoid deleting it. It's historical data, something that has happened and, if it's sent, it should not be deleted by anyone. So how can I remove the *Move to Trash* button? 

The UX is very important for a product being successfull and without controlling these things inside Gutenberg, users would feel confusing (and, actually, can do weird things related to mailings).

These questions appeared on this issue: https://github.com/WordPress/gutenberg/issues/7712#issuecomment-479459859 and here I'm clarifying the use-case and all the needs. 

Thank you very much.

**Comment by gziolo** [comment]
There was a related request shared on the Gutenberg plugin forum by [sehrahmed ](https://wordpress.org/support/users/sehrahmed/):

https://wordpress.org/support/topic/customizing-editor-top-bar/

> Is there any way to customize the Editor Top Bar? I want to change the gear icon and label on the Settings button that toggles the sidebar, but it doesn’t seem configurable.

**Comment by gziolo** [comment]
It should be now possible with the changes added in #27966.
