### ISSUE TITLE
`@wordpress/e2e-test-utils` doesn't work with previously built Gutenberg 

### ISSUE THREAD

**Issue by kamataryo** [WordPress/gutenberg#14834]
**Describe the bug**

Some functions imported from `@wordpress/e2e-test-utils` works with Gutenberg@latest but not with that bundled with WordPress@5.1.1, for example, [`insertBlock`](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-test-utils#insertBlock).
**To Reproduce**

1. `npm install @wordpress/e2e-test-utils@1.1.0`
2. Prepare your own WordPress <= 5.1.1
3. write a jest-puppeteer test like below and run it against with your WordPress.

    ```javascript
    import { createNewPost, insertBlock } from '@wordpress/e2e-test-utils' 
    test( 'test', async () => {
      await createNewPost()
      await insertBlock( 'My Block' )
    } )
    ```
4. The test fails with timeout

**Expected behavior**
Tests with `@wordpress/e2e-test-utils` should work with Gutenberg which is bundled with WordPress <= 5.1.1.

**Screenshots**
 n/a

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
  n/a

**Additional context**

This comes from the commit of class name refactoring, https://github.com/WordPress/gutenberg/commit/7964f381e.
The newer `@wordpress/e2e-test-utils` can detect only class names like `.block-editor-inserter__menu` and not old class names like  `.block-editor-inserter__menu`.

`@wordpress/e2e-test-utils` can be a effective tool for block developers who want to write e2e tests for their products. I guess that backward compatibility should be kept if possible. How do you think?

**Comment by gziolo** [comment]
`@wordpress/e2e-test-utils` are published to npm and you can use previous versions as well. See current versions here:

https://www.npmjs.com/package/@wordpress/e2e-test-utils

I wasn't aware that changes in HTML might make those utils fragile with the previous versions of WordPress. The question is what it the reason it doesn't work anymore.

@aduth did we remove some class names from HTML? There still might be an issue that some subtle changes in DOM structure will make those utils hard to use with older versions of WordPress. We need to come up with some good guidelines and better document which version of utils works with which version of WordPress/Gutenberg.

**Comment by gziolo** [comment]
I can confirm that `createNewPost` will only work with WordPress 5.2 and up because it depends on the new class name introduced:

https://github.com/WordPress/gutenberg/blob/master/packages/e2e-test-utils/src/open-global-block-inserter.js#L8

I think the only way to make it clear is to update CHANGELOG for `@wordpress/e2e-test-utils`.

**Comment by gziolo** [comment]
I spent some more time investigating it and this is what I found out:

For version 1.0:
> The minimum version of Gutenberg `5.2.0` or the minimum version of WordPress `5.2.0`.

For the current 1.1 version:
> The minimum version of Gutenberg `5.3.0` or the minimum version of WordPress `5.2.0`.

I opened #15171 to make it clear.
