### ISSUE TITLE
How to repair error Visual Editors Not Working, Only Displaying HTML: Classic Editor or Gutenberg

### ISSUE THREAD

**Issue by hoangvannhandotcom** [WordPress/gutenberg#14832]
Hi!
I cannot get any visual editors to work.Only Displaying HTML: Classic Editor or Gutenberg.
I have tried installing the classic editor plugin and realize that it is behaving the same way.
Both editors will only display html. There is no preview/rendering of media/images inserted into a post in the classic editor. In Gutenberg, I am unable to add blocks, the + button is greyed out. I am unable to access any Gutenberg settings as the 3 vertical buttons at the top bar are missing.

the picture:
http://www.mediafire.com/view/rng45ig597indc9/Cap%202019-04-04%2021-15-12-869.png
http://www.mediafire.com/view/3idwapznn3204d5/Cap%202019-04-04%2022-24-38-117.png

The page I need help with: https://hoangvannhan.com/wp-admin/post.php?post=2045&action=edit

**Comment by hoangvannhandotcom** [comment]
anyone can help me!

**Comment by youknowriad** [comment]
I think you have the "visual editing" disabled in your user's profile. Let me know if that fixes the issue for you.

**Comment by dragons3232** [comment]
@youknowriad 's solution worked for me. After toggling "Disable visual editor ...", page editor worked as expected. No more html shown. Thank you very much.

**Comment by akimbokm** [comment]
Hey! I know this is an old post, but I was having this problem after changing a client site from a theme with a visual editor to a Genesis child theme using Gutenburg. As per the previous solution, toggling the "Disable visual editor" button On and then Off again has fixed my missing block editor. Thank you! Mwah!

**Comment by Intercounty-Appliance-Corp** [comment]
Hey! The “Disable the visual editor when writing” option is already unchecked, but the accordion plugin is still only showing in HTML and not appearing in the Visual editor. Please help!
