### ISSUE TITLE
Testing: Use SCRIPT_DEBUG in end-to-end test environment

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14845]
Previously: https://github.com/WordPress/gutenberg/pull/14371#issuecomment-471970997
Blocked by: #11360 

The end-to-end test suite includes automatic test failures for console error logging. By using development-mode scripts, we can receive more messages (and more helpful messaging) from some vendor dependencies such as React which provide warning messages in development environments.

This is currently blocked by #11360, since there are currently known warnings which occur in development environments related to the use of unsafe lifecycle methods. These must first be resolved before `SCRIPT_DEBUG` can be activated by default.

**Comment by aduth** [comment]
As #11360 is now closed, it's technically not blocked any longer. I suspect there may still be some rogue errors which occur in some components (see also #14851, #15790).

**Comment by waeled** [comment]
شراء اثاث مستعمل بالرياض 0508210186 ابو الطيب 0508210186 شراء-الأثاث-المستعمل نقل عفش بالرياض 0508210186 دخل وخراج الرياض 0508210186 محلات بيع وشراء اثاث مستعمل بالرياض 0508210186

**Comment by waeled** [comment]
شراء اثاث مستعمل بالرياض 0508210186 غرف نوم مكيفات مجلس عربية شركة شراء اثاث مستعمل بالرياض 0508210186شراء أثاث المستعمل باالرياض شراء اثاث مستعمل بالرياض 0508210186 غرف نوم مكيفات مجلس عربية شغرف نوم مكيفات مجلس عربي

**Comment by waeled** [comment]
شراء اثاث مستعمل بالرياض 0508210186 غرف نوم مكيفات مجلس عربية محلات بيع وشراء اثاث مستعمل بالرياض 0508210186 غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس عربية شراء-الأثاث-المستعمل-شمال الرياض غرف نوم مكيفات مجلس

**Comment by gziolo** [comment]
It's blocked by #17355 which should be worked on first.

**Comment by Mamaduka** [comment]
I'm going to close the issue. See: https://github.com/WordPress/gutenberg/issues/17355#issuecomment-2260746509 and #61943.
