### ISSUE TITLE
Column structure not copied with 'Copy all content'

### ISSUE THREAD

**Issue by ozireh** [WordPress/gutenberg#14842]
I created a page with block editor using several column blocks. I copied the content using 'Copy all content'.

When I pasted the code in another page, the content is there but the columns are lost. Below is the code of my page. 

https://gist.github.com/ozireh/be6a798a1f1062e52a6da8e04fb943e2

**Comment by youknowriad** [comment]
This seems fixed in my testing. Let me know if it's not the case for you in the last Gutenberg version.
