### ISSUE TITLE
Rich Text: Unrelated attributes are applied to Rich Text FormatType 

### ISSUE THREAD

**Issue by technote-space** [WordPress/gutenberg#14858]
**Describe the bug**
There is an error in the program, which causes strange behavior as described in the title.

**To reproduce**
1. Register format type which has no attributes
  ```tagName: span, className: my-span``` (hereinafter referred to format type A)
2. Register format type which has style attribute
  e.g. install and activate `Advanced Rich Text Tools for Gutenberg` plugin
  https://wordpress.org/plugins/advanced-rich-text-tools/
  (e.g. background color)
  (hereinafter referred to format type B)
3. Input text and apply format type A to Rich Text on block editor
4. Apply format type B to Rich Text, which is
 * same node as format type A
 * prior to format type A
 * not the beginning of the node
5. Clear format type B
⇒ the attributes that format type B had is applied to format type A
(the attributes are not applied on the front end or after reloading editor)

**Expected behavior**
Unrelated attributes should not be applied.

**Screenshots**
![screenshot](https://raw.githubusercontent.com/technote-space/screenshots/master/gutenberg/201904072150.gif)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: 
   - :x:: Chrome (72.0.3626.121)
   - :x:: FireFox (65.0.2)
   - :white_check_mark:: Edge (42.17134.1.0)
 - Gutenberg plugin v5.1.0 ～ v5.4.0, WP5.2 beta1

**Additional context**
https://github.com/WordPress/gutenberg/blob/release/5.4/packages/rich-text/src/to-dom.js#L212
```
for ( let ii = 0; ii < currentAttributes.length; ii++ ) {
	const { name } = currentAttributes[ ii ];

	if ( ! futureChild.getAttribute( name ) ) {
		currentChild.removeAttribute( name );
	}
}
```
I think that it should be changed as shown below.
```
for ( let ii = currentAttributes.length; --ii >= 0; ) {
	const { name } = currentAttributes[ ii ];

	if ( ! futureChild.getAttribute( name ) ) {
		currentChild.removeAttribute( name );
	}
}
```
I tried the above changes locally and confirmed that they worked correctly.
 - OS: Windows10
 - Browser: 
   - :white_check_mark:: Chrome (72.0.3626.121)
   - :white_check_mark:: FireFox (65.0.2)
   - :white_check_mark:: Edge (42.17134.1.0)
- Gutenberg plugin v5.4.0

**Comment by youknowriad** [comment]
cc @ellatrix in case you have more info here.

**Comment by ellatrix** [comment]
@technote-space Thanks! Would you be able to make a PR with the suggested code change and perhaps a test case?

**Comment by technote-space** [comment]
I created PR #15070 
Please review it.
