### ISSUE TITLE
Code block: weird focus position

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#1486]
<img width="475" alt="screenshot 2017-06-27 12 06 13" src="https://user-images.githubusercontent.com/4710635/27582415-16028ab0-5b31-11e7-80bb-346fa71b870e.png">

**Comment by iseulde** [comment]
There's a similar issue with HR. @jasmussen Any idea what caused this?

**Comment by jasmussen** [comment]
Yes indeed. This is when the block has no toolbar. The negative margin is still there.

But I fixed this way back, so it must have crept back in in a regression. 

If `.editor-visual-editor__block-controls` gets a `height: $block-controls-height;`, it should clear up the issue. But I'd be curious to first find out which commit removed that height, and maybe rethink this hack.

**Comment by youknowriad** [comment]
Closing as fixed
