### ISSUE TITLE
Fatal error: Cannot declare class WP_REST_Blocks_Controller

### ISSUE THREAD

**Issue by Plastotronic** [WordPress/gutenberg#14864]
Today I updated WP. Now even login fails with message in browser:

Fatal error: Cannot declare class WP_REST_Blocks_Controller, because the name is already in use in /home/.sites/539/site2198750/web/wordpress/wp-content/plugins/gutenberg/lib/class-wp-rest-blocks-controller.php on line 123

Many thanks

**Comment by Soean** [comment]
What Version of WP and Gutenberg are you using? 
We recommend WP 5.1.1 and Gutenberg 5.4.0. if you have an old version of Gutenberg, please update the plugin first.

**Comment by Plastotronic** [comment]
Due to login problem I looked via FTP:

WP:
in File: versionbkpislq7hw4iiw06 (???) there is 4.7.2

Gutenberg:
in File readme.txt:

=== Gutenberg ===
Contributors: matveb, joen, karmatosed
Requires at least: 4.9.6
Tested up to: 4.9
Stable tag: 3.3.0

Is it possible to update Gutenberg via FTP? (WP-Login fails) 

Thank you!

**Comment by Soean** [comment]
Yes, you can update the plugin via FTP, this should help. 
Some functions from Gutenberg were moved to core. So with an old version they are already defined.

**Comment by Soean** [comment]
Please reopen this ticket, if this issue still exists after the update.

**Comment by shula** [comment]
solved the issue by -manually- updating the Gutenberg plugin.
(e.g. via ftp, wp-cli, etc.)

To prevent the whole issue,  one should update the plugins BEFORE updating the wordpress;
But this should be noted / done in the update code :)  If you reached this bug report, then go for the manual plugin update via terminal / sftp.
