### ISSUE TITLE
Input Interaction: ArrowLeft in multi-line selection prematurely triggers multi-selection

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14871]
Possibly related: #12322, #14450

**Describe the bug**

In a paragraph block containing multiple lines of text, a selection spanning multiple lines may prematurely trigger multi-selection when expanding that selection using Shift+ArrowLeft

**To reproduce**

1. Navigate to Posts > Add New
2. Click the writing prompt
3. Add a paragraph with some text
4. Add a second paragraph with at least two lines of text (does not make a difference whether that occurs naturally or by Shift+Enter line break)
5. Starting in the second line of text, create a selection using Shift+ArrowLeft
6. Continue pressing ArrowLeft while holding Shift
7. Observe that as the selection expands into the first line of text, multi-selection occurs prematurely

**Expected behavior**

I can expand the selection until reaching the start of the first line of the paragraph. Only at that point should another ArrowLeft expand to create the multi-selection.

**Screenshots**

![arrow-left-multi](https://user-images.githubusercontent.com/1779930/55749119-395dc780-5a0e-11e9-943b-16c6ff227dd7.gif)

**Desktop:**

 - OS: macOS Mojave 10.14.4 (18E226)
 - Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
 - Version: `master` (1df302121f0ab7df8611d01e28ad41db25f40d52)

**Additional context**

The same issue does not appear to occur in the reverse direction, i.e. Shift+ArrowRight does not trigger multi-selection prematurely. **However**, it _never_ triggers the multi-selection, even when reaching the end of the paragraph, which is similarly an unexpected behavior.

**Comment by aduth** [comment]
cc @ellatrix

**Comment by ellatrix** [comment]
@aduth I'll have a look.

**Comment by ellatrix** [comment]
After looking closer, this actually appears to be a regression caused by #14462, which unfortunately no e2e test caught.
