### ISSUE TITLE
How to add a toolbar button in toolbar but not in dropdown menu

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#14881]
I try to add a toolbar button in toolbar like this:

```
( function( wp ) {
    var MyCustomButton = function( props ) {
        return wp.element.createElement(
            wp.editor.RichTextToolbarButton, {
                icon: 'editor-code',
                title: 'Sample output',
                onClick: function() {
                    console.log( 'toggle format' );
                },
            }
        );
    }
    wp.richText.registerFormatType(
        'my-custom-format/sample-output', {
            title: 'Sample output',
            tagName: 'samp',
            className: null,
            edit: MyCustomButton,
        }
    );
} )( window.wp );
```

This is copied in  [gutenberg document](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/format-api/2-toolbar-button/)

![C603AE87-396F-4934-8612-44967837C895](https://user-images.githubusercontent.com/22772830/55797672-9dac8400-5aff-11e9-9f57-5c6ea0d166ba.png)
My question is why the button is always in the dropdown menu, how can I add it in toolbar.

And it seems like it is not allow to add in toolbar after I view the code in [format-toolbar](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/rich-text/format-toolbar/index.js) and [rich-text](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/rich-text/index.js#L1126)

 It is dependent on the props but none be passed.

Wait online, it's urgent

**Comment by technote-space** [comment]
I use `BlockFormatControls` to add buttons in toolbar.
![BlockFormatControls](https://raw.githubusercontent.com/technote-space/screenshots/master/gutenberg/201904092109.png)

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-toolbar/index.js#L36

**Comment by QiShaoXuan** [comment]
> I use `BlockFormatControls` to add buttons in toolbar.
> ![BlockFormatControls](https://raw.githubusercontent.com/technote-space/screenshots/master/gutenberg/201904092109.png)
> 
> https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-toolbar/index.js#L36

Thank you so much, could you tell me where did you get your screenshot of the plugin?

**Comment by andpor** [comment]
Have the same problem...none of the examples around work...toolbar buttons always added to the end of More Rich Text Controls dropdown menu...so annoying...

**Comment by ghostmaster** [comment]
@QiShaoXuan: can you please share example, how to do that ?

**Comment by QiShaoXuan** [comment]
> @QiShaoXuan: can you please share example, how to do that ?

use `BlockControls` like this
```js
<BlockControls>
  <Toolbar>
    <IconButton
      icon="edit"
    />
  </Toolbar>
</BlockControls>
```

**Comment by screeper** [comment]
Or in ES2015:
```
return wp.element.createElement(
    wp.components.IconButton, {
       icon: 'editor-code',
       label: 'Sample output',
       onClick: function() {
           console.log( 'toggle format' );
       },
   }
);
```

**Comment by mahnunchik** [comment]
What are the differences between `RichTextToolbarButton` and `BlockFormatControls`? Why there are only `RichTextToolbarButton` in the examples?

**Comment by fabienlege** [comment]
Same issue for me. Any news ?

**Comment by mahnunchik** [comment]
Hi @nickhamze how did you solve it?

**Comment by nickhamze** [comment]
> Hi @nickhamze how did you solve it?

Look here at George's commit: 
https://github.com/sortabrilliant/emojiconbini/commit/d45573dc1f249715479f9d2b3acb179aca6ec906

**Comment by chrisvanpatten** [comment]
It would be great to see the `RichTextToolbarButton` component support controlling placement. Something like an `isPrimary` attribute, or some other way to "promote" to the main toolbar.

Long term a similar pinning approach to plugin sidebars would be pretty neat, or like the block visibility modal.

**Comment by t-hamano** [comment]
It has been quite some time since the assignment was submitted, but I have been thinking about this issue again.

The answer to this issue is to use `BlockControls`, but there is no specific tutorial or sample code even in the latest Gutenberg.
I think it is a good idea to add a new step at the end of [Formatting Toolbar API](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/format-api.md) document. I would like to create a sample code and submit a PR.

**Comment by t-hamano** [comment]
By updating the documentation, #29181 will be resolved at the same time.
Also related to this issue are #22663 and #30069 regarding the option to move the core format from the drop-down to the toolbar.

**Comment by mjjwatson** [comment]
Reigniting this with a potential issue—when adding the icon using `<BlockControls>` as described, if you have a RichText component using inlineToolbar, it renders to the parent block toolbar rather than your inline toolbar. Any work around or suggestions there?

**Comment by t-hamano** [comment]
@mjjwatson 
could you please attach a screenshot or specific code?

**Comment by mjjwatson** [comment]
Took a while as I've been away, sorry. 
Using the example from the documentation:
```
const MyCustomButton = ( { isActive, onChange, value } ) => {
	return (
		<BlockControls>
			<ToolbarGroup>
				<ToolbarButton
					icon="editor-code"
					title="Sample output"
					onClick={ () => {
						onChange(
							toggleFormat( value, {
								type: 'my-custom-format/sample-output',
							} )
						);
					} }
					isActive={ isActive }
				/>
			</ToolbarGroup>
		</BlockControls>
	);
};
registerFormatType( 'my-custom-format/sample-output', {
	title: 'Sample output',
	tagName: 'samp',
	className: null,
	edit: MyCustomButton,
} );
```

And then creating a RichText component with inlineToolbar:
```
<RichText
	tagName={'h2'}
	value={ value }
	onChange={ value => {
              if(onChange)
                  onChange(value) 
          }}
         inlineToolbar
/>
```

This renders the new block control within the RichText's parent block, in the top left, as seen on this screenshot:

![Screenshot 2023-03-11 at 15 33 52](https://user-images.githubusercontent.com/3973644/224493548-7dc47151-a199-43a2-80d3-981d79d1c140.png)

**Comment by t-hamano** [comment]
@mjjwatson
It is possible to render the [RichTextToolbarButton](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/format-api.md#step-2-add-a-button-to-the-toolbar) component into an inline toolbar dropdown. However, as far as I can tell, there does not seem to be a slot provided to insert the component directly into the inline toolbar.
