### ISSUE TITLE
Nested blocks + html

### ISSUE THREAD

**Issue by janeschindler** [WordPress/gutenberg#14884]
I'd like to wrap nested blocks in html in the parent block. This could happen in the template or in the edit/save functions, or via php in the register post template property. For example (I know the syntax is nonsensical but this explains what I wish I could do):
```
const TEMPLATE = [
<div class="row">
<div class="col-sm-6">
	['neuthalblocks/pickpost', {}, []],
</div>
<div class="col-sm-6">
	['neuthalblocks/pickpost', {}, []],
</div>
<div class="col-sm-6">
	['neuthalblocks/pickpost', {}, []],
</div>
<div class="col-sm-6">
	['neuthalblocks/pickpost', {}, []],
</div>
</div>
]
```
This should apply to the back end as well as the front end, so that my backend can look identical to my frontend. 
I'd also be glad to understand why this isn't the way blocks work or why this isn't a good idea.

**Comment by zkingdesign** [comment]
I'm also interested regarding this.

**Comment by youknowriad** [comment]
Did you consider using two levels of nesting and the a row and a column block? That's how the core columns block work.

**Comment by janeschindler** [comment]
Yes, that's what I ultimately did. But it seems crazy to me to keep making container blocks when all I need is a simple wrapper. For a single repeated field I have something like four blocks that produce minimal HTML, all of which I need to compile and version control. I'm really hoping someone develops a simpler way, or an ACF-style GUI to build blocks.

**Comment by youknowriad** [comment]
This is unfortunately a tradeoff of the current way of dealing with innerBlocks. The advantages is that it makes it simpler to build blocks with generic nested contexts like (group, columns, cover block...) but when we want more control over the produced markup, we need to play with the rules.

I'm going to close this issue as it's not really actionable at the moment.
