### ISSUE TITLE
change default icon

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#14892]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

**Comment by Soean** [comment]
Hello @QiShaoXuan,
can you edit this issue and add a description? 
I only see the placeholder text. What is the question or issue about?

**Comment by QiShaoXuan** [comment]
I`m so sorry this is touching the enter key accidentally.
