### ISSUE TITLE
Input interaction: up arrow key jumps to previous block

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#14896]
How to reproduce:

* Position the caret in the last line of a 3-line paragraph.
* Press up arrow key once: it moves the caret to the second line.
* Press up arrow key again: observe how it moves the caret to the previous block.

I'd have expected the caret was moved to the first line.

**Comment by ellatrix** [comment]
What browser are you using? I cannot reproduce in Chrome. Perhaps more detailed instructions might help.

**Comment by nosolosw** [comment]
I'm in Firefox 66. Tested Chrome and I can't repro either.

**Comment by youknowriad** [comment]
can't reproduce on Firefox either, this seems fixed.
