### ISSUE TITLE
Replace feature for reusable blocks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#14905]
**Is your feature request related to a problem? Please describe.**
Sometimes a reusable block has to be replaced on a page.

**Describe the solution you'd like**
An extra menu option for reusable blocks on a page for replacing it with another reusable block.

**Describe alternatives you've considered**
Inserting the new reusable block before/after the old reusable block and 
then deleting the old reusable block.

**Comment by youknowriad** [comment]
Thanks for the suggestion. I'd personally guard against adding two many UI elements to an already crowded UI. It seems like the alternative considered is fairly simple and this might be better kept as is.

I added the design feedback to confirm but I'd personally think we should not do this.

**Comment by kjellr** [comment]
👋 We discussed this during today's weekly design triage:
https://wordpress.slack.com/archives/C02S78ZAL/p1555431000083900
(A WordPress.org Slack login may be required to view that link)

@strarsis, would you mind sharing some use cases for this? It'd be helpful to see.

In general, I can imagine this being helpful to some — it's somewhat similar to block transforms. However I agree with Riad that this is probably somewhat low priority.

**Comment by strarsis** [comment]
@kjellr: Sure, in this case it was for translating pages. This may be different with other translation plugins, but for Polylang each page had to be duplicated, including the reusable blocks, then each duplicated reusable block had to be transltaed and then the original reusable block on the translated pages replaced.

**Comment by richtabor** [comment]
We discussed this in today's [Gutenberg triage meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1571156568134300) (Slack), coming to these conclusions: 

1. We'd like to see more desire for this before moving on it
2. We don't want to use transforms here, as blocks that transform are related - whereas reusable blocks may or may not be related at all. Also, folks may have any number of transforms - which would cause the UI to get quite messy.
3. The alternative action to this proposal is to remove the current reusable block and add the new reusable block. This flow is no different than removing any other block to replace with another. We couldn't detail why reusable blocks would be treated differently.

**Comment by youknowriad** [comment]
Let's close for now and revisit later if there's more desire.
