### ISSUE TITLE
Unexpected cell selection behavior in tables

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#14904]
**Describe the bug**
Cells in the table block seem to only accept selection when clicking in a specific area of the cell. Especially when writing longer texts, the issue becomes particularly apparent. The area seems to align with the part of the cell where the cursor appears when correctly selecting the cell.

**To reproduce**
1. Create a table block with at least two cells.
2. Add an example text to one of the cells. Especially when writing longer texts, the issue becomes particularly apparent (e.g., "Short example text to demonstrate unexpected behavior when selecting other cells in the created table. Short example text to demonstrate unexpected behavior when selecting other cells in the created table. Short example text to demonstrate unexpected behavior when selecting other cells in the created table.").
3. Optionally activate the "Fixed width table cells" option. However, this option does not change the unexpected behavior.
4. Select any of the other cells. Hovering with the mouse cursor over / clicking in different parts of the cell demonstrates that only a small area is actually accepting clicks to select the cell for editing. Compare with the areas highlighted in green and red in the attached _Screenshot 1_.

**Expected behavior**
As long as the user clicks somewhere in the rectangular area of a cell, it should not matter where the user clicks to select the cell for editing.

**Screenshots**
_Screenshot 1:_ The _green area_ seems to accept clicks by the user. The _red area_ does not accept clicks by the user.
![table_edit](https://user-images.githubusercontent.com/996503/55876879-ef551d00-5b98-11e9-8c6f-6971e6523378.png)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox 66.0.2 (64-bit)
 - Gutenberg 5.4

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue, I was able to reproduce the problem in the last version of Gutenberg 5.8.0.

**Comment by talldan** [comment]
There's also another report of this in issue https://github.com/WordPress/gutenberg/issues/15661, now closed as a duplicate.

**Comment by talldan** [comment]
I have a fix for this in https://github.com/WordPress/gutenberg/pull/16653
