### ISSUE TITLE
Constrain "Media & Text" resizing

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#14901]
We should not let this happen:

![image](https://user-images.githubusercontent.com/548849/55873272-7bfadd80-5b8f-11e9-818f-3af2fae69db0.png)

Can we restrict the max-resize here to something more reasonable?

cc @jorgefilipecosta

**Comment by marekhrabe** [comment]
Happy to add the limits once we figure them out. I'm currently working on things in this area.

Technically, the ratio value is saved as a percentage of how much space the Media takes — a number from 0 to 100. We are thus looking for the new min and max value in that range. They should both be the same distance from their respective side - like 10% and 90% or 15% and 85%. I think one of these might work while still providing a lot of flexibility.

What's the plan with supporting blocks made before this limitation that might lie outside our defined zone? Would we just migrate them to just use the closest allowed number?

**Comment by jorgefilipecosta** [comment]
I guess we can allow values between 15% and 85% and check if they look good and iterate from there.

> What's the plan with supporting blocks made before this limitation that might lie outside our defined zone? Would we just migrate them to just use the closest allowed number?

I think we should just leave them, we would apply this limitation at the UI component level to allow values outside this range if the user previously set other values that value is already in the attributes and would continue to be there. If the user tries to change the value it would not be possible to get back to values outside the range (of course the user could undo or not save the change).

**Comment by mtias** [comment]
Yes, limiting at UI seems fine, no need to coerce the existing values.

**Comment by marekhrabe** [comment]
PR #14951

**Comment by mapk** [comment]
This issue was resolved with #14951.
