### ISSUE TITLE
Navigation list doesn't always show selected block by default

### ISSUE THREAD

**Issue by nickylimjj** [WordPress/gutenberg#14913]
**Describe the bug**
The viewport doesn't show the selected block if it's far below. It would require scrolling.

**To reproduce**
1. Create numerous blocks such that the Navigation List has an inner scroll.
2. Select the last block.
3. Open the Navigation List.
4. See error.

**Expected behavior**
The viewport to show the selected block.

**Screenshots**
Error.
![gutenberg-1](https://user-images.githubusercontent.com/12999836/55900000-2c6ae080-5b94-11e9-8edf-6b1e26f7f4d5.png)

Ideal.
![gutenberg-2](https://user-images.githubusercontent.com/12999836/55900020-3856a280-5b94-11e9-8132-7d3549130de1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 66.01

**Additional context**
- using WordPress 5.1.1, gutenberg@5.4.0

**Comment by youknowriad** [comment]
It's seems to me like this is the same issue as #14311 I'm closing as a duplicate. Let me know why you think it should have a separate issue?

**Comment by nickylimjj** [comment]
It seems from that issue that the problem is inner scrolling not impelented, not that it is not scrolled. I started there but move here since it seemed different. But if it seems similar then I'll continue working off that. 😂
