### ISSUE TITLE
copy/pasting links within the editor adds unwanted code.

### ISSUE THREAD

**Issue by sk8zion** [WordPress/gutenberg#14928]
**Describe the bug**
When copying a link in visual mode, the original code is not copied but a "browser version" (for lack of a better way to say it)

**To reproduce**
1. Create a link in visual or HTML mode, for example `<a href="/newpage" class="btn">Link</a>`
2. In Visual mode, copy that link and paste it somewhere else.
3. Look at the new link in HTML mode, the code will look like `<a href="http://www.website.com/newpage">Link</a>`

**Expected behavior**
One would expect that the same link code would be copied like it did with the classic editor.  However not only is the entire site URL added to the code which is undesired, the class="btn" is stripped away and needs to be re-added.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

Thanks for taking the time to listen (or read), I hope the feedback helps.

**Comment by pento** [comment]
[WP47705](https://core.trac.wordpress.org/ticket/47705) describes a similar issue, where internal target links (eg, `<a href="#chapter1">Chapter 1</a>`) have the URL of the admin interface prepended to them.

**Comment by talldan** [comment]
Closing as this no longer happens. There was a different bug that I spotted when testing - #33585.
