### ISSUE TITLE
display: table-caption; incorrectly formatting text

### ISSUE THREAD

**Issue by markx2** [WordPress/gutenberg#14922]
User reported that under images in 2 columns the caption text was displayed single character vertically.

The code they had in their post:

<div class="wp-block-columns has-2-columns">
<div class="wp-block-column">
<div data-amp-layout="fixed" class="wp-block-image"><figure class="aligncenter is-resized"><img src="https://example.com/wp-content/uploads/2019/04/IMG.jpg" alt="" class="wp-image-834" height="400"/><figcaption>Bill Gates<br>Coder<br></figcaption></figure></div>

Under the image, the text was displayed as
B
i
l
l

G
a
t
e
s

C
o
d
e

**Expected behavior**
That the caption displayed horizontally, as normal.

**Screenshots**
![bug](https://user-images.githubusercontent.com/7057656/55951567-7e247100-5c4f-11e9-88fa-4b73e76eee66.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Vivaldi 
 - Version  2.4.1488.35 (Stable channel) (64-bit)
--

**Comment by youknowriad** [comment]
Hi There!

This issue is not actionable in its current form. Can you share the full HTML code of the post? It looks it got lost when you created the issue?

**Comment by youknowriad** [comment]
I'm closing at the moment as stale. Let's reopen if we have more details about the raise issue.
