### ISSUE TITLE
Edit Block : no changes on FrontEnd, or block crashes

### ISSUE THREAD

**Issue by alexis-magina** [WordPress/gutenberg#14937]
Hello,

(I'm just starting to use Gutenberg Blocks.) 
I'm building a custom block for a specific usage, and from my tests, I can see that if I edit the block, even with a very small modification and re-build (I'm using ESNext), that causes errors ; 
For example, if I write this simple piece of code, that just display an image : 
`<div>
  				{
  					mediaURL && (
  						<img src={ mediaURL } alt={ mediaALT } />
  					)
  				}
        </div>`

then, if i want to edit the block code to add a data-attribute : 
`<div data-test="1">
  				{
  					mediaURL && (
  						<img src={ mediaURL } alt={ mediaALT } />
  					)
  				}
        </div>`

So my modification is not very important, and isn't related with the img vars, but 
- On FrontEnd : The modification is not applied.
- On BackEnd : The block crashes, and I must convert it on HTML.

Is there a way to automatically apply the modification on existing pages that used this blocks ? 
How can I prevent the block to crash on back-end ?

Thank you!

**Comment by jorgefilipecosta** [comment]
Hi @alexis-magina, thank you for opening this issue.
When the markup of a block is changed block authors need to add a new deprectaed version to the block, so when the block editor opens the block is automatically migrated to the new version and the markup is updated (without noticeable errors)
Adding a deprecated version consists essentially in adding a deprecated property as a sibling of save and attributes, this property should be an array of objects each object should contain the attributes and save properties of the previous deprecated version (essentially copy and paste the save without the data attribute in the deprecations object). More information about this process can be found in https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-deprecation/.
