### ISSUE TITLE
rel="noopener noreferrer" is automatically added to my block, breaking validation

### ISSUE THREAD

**Issue by jakeparis** [WordPress/gutenberg#14934]
**Describe the bug**
Since WordPress 5.1, in my custom slideshow block, all my link tags are getting an added attribute `rel="noopener noreferrer"` at editor-load, causing it to fail block validation. 

**Expected behavior**
My block should validate just as it has in WP 5.0

**Actual behavior**
When the editor attempts to load my post's saved representation, it adds the attributes to the link tags first, then validates. The block then fails to validate because the rel attribute isn't in the saved block's representation.

**Comment by fabiankaegy** [comment]
I also experienced this problem. 

I understand that this is a valid security concern and that it's very important to add these. But having that break the validation of custom blocks doesn't seem to be the best user experience.

**Comment by jakeparis** [comment]
I [filed a bug](https://core.trac.wordpress.org/ticket/46886) about this on Trac.  The issue is that when WordPress sees a `target` attribute on a link, it adds the `rel` attribute, but the block editor no longer validates it. 

The actual bug (in my case) is that my block had a ` data-target=""` attribute, but the regex WP core is using to add the `rel` attribute was picking that up in error. 

But I still think it's a bug in the block editor that it no longer validates because of the rel attribute added behind the scenes.

**Comment by Horttcore** [comment]
I got this problem very often with custom blocks, the reasons are very different from block to block.

**Comment by maximebj** [comment]
Here is how we fixed it : 

On my custom Button I have an attribute isBlank that allow me to add a target blank. I just added the same check for the rel attribute : 

```
<a
            href={ url }
            target={isBlank && '_blank'} // Initial test
            rel={isBlank && 'noopener noreferrer'}  // Add this to fix
            className={ classnames( 'button', `button--${buttonClass}` ) }
            data-type={ buttonClass }
>
```

But yeah, this new feature broke retrocompatibility.

**Comment by TwisterMc** [comment]
@maximebj , your code worked great. However, what do you mean by "this new feature broke retrocompatibility."

**Comment by maximebj** [comment]
When developping a custom block, if you change the save markup, the parser will not understand and display an error `blocks.min.js?ver=6.2.5:2 Block validation: Block validation failed for...` 
It's the same thing here. If you use a link, the rel attribute will be automatically added and the block parser   will fire the error.

So it worked well, and when the team pushed the new feature, error appeared. WP should not break anything when adding a new feature (a mantra for a long time ago).

**Comment by loratov** [comment]
I need the ability to add different options to the rel attribute in my custom blocks while setting the target attribute as well but this feature prevents me from doing so. It keeps overriding whatever I set in the rel attribute.

**Comment by llemurya** [comment]
I have the same problem, block validation error, I want to set the `rel `attribute for my block but the Gutenberg inject the `rel` if the target is `_blank `and broke the markup match between the save method and content from post body. @youknowriad is any hook that can filter the second parameter from `deepFilterHTML` function, to remove the `phrasingContentReducer `callback that add `rel `attribute. Thanks a lot.

**Comment by rodrigodagostino** [comment]
Has anybody found a workaround for this? :S I thought I was doing something wrong until I realised that WP was forcing that into the save portion of my block.

**Comment by StefanXhunga** [comment]
Hi All,
thank you for your contribution.

**Comment by cngodles** [comment]
I am currently experiencing this in a project. One thing I'm noticing is that if you place an external URL in the link, then the `noopener noreferrer` is getting added. While we can test for empty links, etc, it may be more difficult to test for external links. I considered adding it always, but you wouldn't want that on an internal link or link within your own network of websites.

The problem seems to be it getting added before the validator runs. If this was added after validation, would that solve?

**Comment by talldan** [comment]
> I have the same problem, block validation error, I want to set the rel attribute for my block but the Gutenberg inject the rel if the target is _blank 

It isn't Gutenberg, WordPress core modifies the post markup to add the `rel` after the block editor has sent the post data to be saved. It's a security measure. I don't think the Gutenberg codebase can do anything to avoid this.

Given that I'm going to close this.

The validation issue as a side effect is unfortunate for block devs. Core blocks add the rel attribute to avoid that. There might be more that can be done but it isn't straightforward, it's being discussed here - https://github.com/WordPress/gutenberg/issues/39051
