### ISSUE TITLE
Add some virtual blank space at the bottom of the editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#14942]
**Is your feature request related to a problem? Please describe.**
When editing posts you quickly run out of screen real estate and reach the bottom of the screen where you remain forever. The "solution" to a more pleasant experience is to add new lines for no reason which remain there because you forget to delete them and get annoyed by them when you view the post.

**Describe the solution you'd like**
The post editor could provide what other editors refer to as "virtual space", which is space that doesn't contain newlines but is scrollable and allows for the content to be scrolled up so that editing could happen closer to the middle of the screen at all times.

Sublime Edit calls it 'scroll_past_end', PHP Storm calls is 'virtual space at file bottom', other editors just have it. Rich text editors have the concept of pages and they enqueue another page when you are near the end of the current one, so you can scroll past content end.

**Comment by talldan** [comment]
Interesting idea. VSCode also has this, I just noticed. Testing in google docs, and it doesn't seem as much of an issue there as it always shows the 'page' that you're working on.

This could be a setting in the options dialog. In terms of implementation, it could be a style variation of the element that sits at the end of the block-list:
![Screen Shot 2019-04-12 at 4 44 13 pm](https://user-images.githubusercontent.com/677833/56024702-29fab900-5d43-11e9-8256-32b3c1876f02.png)

**Comment by m-e-h** [comment]
I this is a similar request https://github.com/WordPress/gutenberg/issues/14852

**Comment by youknowriad** [comment]
Let's close as a duplicate.
