### ISSUE TITLE
Show Gallery Captions on hover

### ISSUE THREAD

**Issue by DanAntion** [WordPress/gutenberg#14949]
I like the appearance of the Tiled Mosaic Galleries, but you cannot see the captions/descriptions unless you enter the gallery slideshow (there is a problem with that, but I'll post it separately). 

In the Classic Mosaic Gallery, the "Captions" are revealed at the bottom of the image when you hover over the image in the mosaic collage. In Guttenberg, nothing happens. I think adding this feature would make the galleries more appealing to users who don't want to enter the slideshow.

This is hard to capture in a screen shot (because the cursor disappears) but I have a video of the two different behaviors - https://www.youtube.com/watch?v=A48YTHPZikg

Thanks for any consideration
Dan

**Comment by youknowriad** [comment]
I wonder if this behavior should be just CSS provided by themes that wants to opt into these hovered titles. Anyway Added a "Needs Design Feedback" label to get more designy thoughts.

**Comment by DanAntion** [comment]
Thank you! 

I have spend years working in development, but for an insurance company, I'm more than a bit out of my element here. I was exploring the elements to see if I could fix this by editing the CSS. I don't know that all users have that ability, but if I can figure it out, I'd try. It might be that themes haven't yet caught up to the new editor.

**Comment by scruffian** [comment]
If this is part of the Jetpack Tiled Galleries block, we are tracking the issue here: https://github.com/Automattic/jetpack/issues/11794

**Comment by kjellr** [comment]
Hi there! The mosaic gallery is part of Jetpack, so this should be handled separately in their repository. The link @scruffian provided is the best place to track that. 

I'll keep this issue open though, because I can see how implementing an optional "Show captions on hover" option for Gutenberg's existing gallery block could be a cool feature. 👍

**Comment by DanAntion** [comment]
@kjellr Thank you! I admit that I am unfamiliar with the complexity of this project, so I appreciate the information everyone has been providing. I will follow the other issue to tack the progress over there.

Thanks again
