### ISSUE TITLE
Tweet Embed ERROR!

### ISSUE THREAD

**Issue by papadopouloskostas** [WordPress/gutenberg#14953]
When I embed a tweet on "Gutemberg," the tweet appears in the preview but then does not appear in the post. 

I turned off all the possible plugins that might be causing the problem but found that something went wrong with the editor.

Example/ Link: https://www.thegreekpost.com/o-kyranakis-xeftilise-ton-arvaniti-gia-to-dithen-skandalo-novartis-vid/

**Comment by nerrad** [comment]
Thanks for reporting this.  There are a number of javascript errors on the front end of your site and its possible you have a theme or plugin conflict on your site thus the twitter js is blocked from executing.  You'll want to do some troubleshooting with the existing plugins you have active and theme you are using and see which is causing the conflict.

For further help with troubleshooting you can go to the [WordPress support forums](https://wordpress.org/support/)
