### ISSUE TITLE
Gallery block not showing descriptions

### ISSUE THREAD

**Issue by DanAntion** [WordPress/gutenberg#14959]
In a Guttenberg gallery, if there is no title or if the title is the image file name "aa123.jpg" the title field is not shown and the Description field appears below the image. If there is a custom title, depending on the characters in the title, it pushes the description down below the bottom of the window and the person viewing the gallery doesn't see it. In addition, if you make the browser window bigger, the image is adjusted and the title once again pushes the description below the screen.

I say "depending on the title" because it doesn't always seem to happen. I have noticed this in Firefox and in Chrome. [You can see this happening in this video](https://www.youtube.com/watch?v=Cof2SMuFm9k).

I can recreate this in Firefox and Chrome as follows:

1) Go to https://nofacilities.com/2019/03/24/coffee-table-made-from-trees/ and scroll down to the galleries (there are two).
2) Click on the leftmost image in the upper gallery (4 photos inline).
3) I see the Title, but not the description - resizing the window may or may not reveal the description, depending on the ending window size.
4) Click to advance to the next image in the gallery.
5) Because this image's "title" is the filename, the title is suppressed and the description is visible.

I would expect that the descriptions would always be visible below the image, regardless of the window shape or title contents. In the Classic galleries, the Captions would appear above the Title (centered beneath the image) regardless of what the title text was.

I am a WordPress.com user on a premium plan, so I don't know what version of Guttenberg I am using (the current production version, I suppose).

First screenshot shows the way the captions and titles are displayed in the Classic galleries (caption under image, title below).

Second screenshot shows gallery slide show image where a custom title pushes the description below the screen in a Guttenberg gallery

Third screenshot shows how the description is visible in a Guttenberg gallery, if there is no title or if the title is simply the image filename.

![Classic caption v title placement](https://user-images.githubusercontent.com/49531154/56045069-7e377600-5d0e-11e9-81f5-25ced11ca2d5.PNG)
![Guttenberg caption v title placement-3](https://user-images.githubusercontent.com/49531154/56045071-7e377600-5d0e-11e9-8cf5-913ca7b0d1ef.PNG)
![Guttenberg caption v title placement-4](https://user-images.githubusercontent.com/49531154/56045072-7e377600-5d0e-11e9-85ab-299415a2cbee.PNG)

**Comment by fabiankaegy** [comment]
I believe the core gallery block is not what's responsible for this Lightbox view of the gallery. I'm nut sure what your setup is, but I know that Jetpack for example will allow you to have the Gallery become a Lightbox. 

So you might want to raise this issue with whoever is actually creating the Lightbox. 

If you only have Wordpress 5.0 or higher running without any external plugins there is not Lightbox view included in the Gallery Block.

**Comment by DanAntion** [comment]
Thank you for that. I will mention that to the engineer I was dealing with. I am on a WordPress.com premium plan, so no plugins available.

**Comment by fabiankaegy** [comment]
Ahh okay that's good to know  👍 I was just thinking in the way of self hosted Wordpress pages. I believe that in that case it is still coming from the extension of Gutenberg wordpress.com build.

**Comment by DanAntion** [comment]
Thanks. I opened this, and one other issue related to the galleries (https://github.com/WordPress/gutenberg/issues/14949#issue-432550768) when the WordPress engineers felt that these were more design issues than errors. I had been working with them as if the two pieces were related, but I split them here, because I do think this one is a problem. The other one might be a design issue, butit's one I wish they'd reconsider.

**Comment by youknowriad** [comment]
Hi There! I'm not sure I understand the issues here. Are you trying to show the titles on hover like the second gallery in the first one?

Can you share the HTML content of your page? (you can find it in the code editor mode) 

Also by inspecting the source code of your page, it seems that these are not regular gallery blocks but JetPack tiled galleries right? I think it's probably better to raise an issue in the JetPack repository instead.

**Comment by DanAntion** [comment]
Hi. I am trying to have the Descriptions show in the Gallery block, when you click and enter the slide shoe (Lightroom?) If there is a custom title on the image, the description is pushed down below the visible portion in the window.

I'm sorry if I am in the wrong place. I am a WordPress.com premium user. I brought this issue up with their engineers, but they said "it seems like a design decision" so they told me to post here. 

I did enter another issue regarding the "hover" function, In my opinion, that could be considered a design issue. This I think is a bug, because if people took the time to write a description, and give an image a custom title, I think they would want them both to be visible.

Thanks.

**Comment by mtias** [comment]
This feature is specific to WP.com / Jetpack and not part of the core editor experience. It's already reported here: https://github.com/Automattic/jetpack/issues/11594
