### ISSUE TITLE
I lost all but the first item in a numbered list, now I have to rewrite it

### ISSUE THREAD

**Issue by rhyous** [WordPress/gutenberg#14965]
**Describe the bug**
I lost all but the first item in a numbered list, now I have to rewrite it.

**To reproduce**
I just wrote a list.
I had code before and after it.

**Expected behavior**
Not to lose my content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Please display the version in WordPress if you want this.

- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

FYI: Guttenberg is a terrible experience. I can understand trying to improve, but it is a major step back. It needs a lot of work to be a step forward. I probably am going to turn it off. Somebody at wordpress should have been told that it was ready for prime time.

**Comment by nerrad** [comment]
Thanks for your report.  There's not enough information in this issue for us to reproduce, can you provide some concrete examples of reproducing your issue?  Screenshots and/or screencasts are super useful as well.

**Comment by jorgefilipecosta** [comment]
Hi @rhyous, thank you for reporting this issue and sharing your feedback. Unfortunately, as @nerrad referred with the information provided we are not being able to reproduce the issue.
If possible please share with us a specific set of steps/actions that when followed trigger this error (most of the times).
Given that some time passed from the information request I'm going to close the issue, feel free to reopen the issue when the information is available.

Thank you in advance!
