### ISSUE TITLE
Invalid document time shown

### ISSUE THREAD

**Issue by Backpackstudio** [WordPress/gutenberg#14973]
WordPress 5.1.1 with built in Gutenberg.

When editing a post, invalid **time** is shown.

## Gutenberg editor:

Shows 12:30 instead of 00:30.

![Gutenberg](https://i.ibb.co/bH2DMDy/190413-0001.jpg "Gutenberg")

## Classic editor

Shows time correctly.

![Non Gutenberg](https://i.ibb.co/gvyx6kr/190413-0002.jpg "Non Gutenberg")

**Comment by nerrad** [comment]
Thanks for reporting this.  Can you provide us details about your date and time settings for your site (formats and whether your site is set to 12 or 24 hour time).  I'm assuming its set for 24 hour time.  Also what language you are using could be helpful.

**Comment by Backpackstudio** [comment]
> Thanks for reporting this. Can you provide us details about your date and time settings for your site (formats and whether your site is set to 12 or 24 hour time). I'm assuming its set for 24 hour time. Also what language you are using could be helpful.

Thank you!

Site language: Estonian
Date format: d.m.Y
Time format: H:i

**Comment by tobifjellner** [comment]
00:30 will show as 12:30 if 12 hrs format is chosen, that error can easily happen, the difference is just h>H. The parameter for this format is a part of the translation package. Now, even if this parameter is currently correctly "translated" for Estonian, one should note that the translation still has not reached 100% and therefore hasn't been released yet.

**Comment by Backpackstudio** [comment]
> 00:30 will show as 12:30 if 12 hrs format is chosen, that error can easily happen, the difference is just h>H. The parameter for this format is a part of the translation package. Now, even if this parameter is currently correctly "translated" for Estonian, one should note that the translation still has not reached 100% and therefore hasn't been released yet.

As you see on provided image, date part is translated somehow and is actually shown correctly according to local standards.

**Comment by getsource** [comment]
Hi @Backpackstudio! 

We talked about this in today's Gutenberg triage, and it seems to be working properly with master.
You can see the conversation (and a screenshot from one of the tests) [in the WordPress Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1580967952006100), if you'd like.

I'm going to go ahead and close this, but If you are still having issues, please feel to comment, and happy to continue conversation and reopen as necessary.

Thanks again for the report!
