### ISSUE TITLE
Non-removable empty last List Item

### ISSUE THREAD

**Issue by kennethz3** [WordPress/gutenberg#14977]
**Describe the bug**
When using both classic block and list block, an empty <li></li> is added at the end off the second list, without the user being able to delete.

**To reproduce**
1. Create a new post
2. Add List block as the first block below the title
3. Add a second List block after the first list block
4. Add two list items in both List blocks
5. Delete the last list item in the second List block.
6. Publish
7. Visit page in new tab, and second list block has an empty list item at the very end.
8. Refresh the Edit post tab. Editor now shows empty list item. Attempting to remove list item is unsuccessful. it doesn't record it as a change.

**Expected behavior**
When a list item is removed from editor, it should be removed from content as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/16528000/56090421-482afb00-5ea2-11e9-8907-6275e7486cc9.png)
![image](https://user-images.githubusercontent.com/16528000/56090423-4e20dc00-5ea2-11e9-9217-4fbf236d0704.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 66.02

**Additional context**
- WordPress 5.1.1

**Comment by timofeycom** [comment]
Can confirm. Anytime the page is Published then edited, the last bullet point reappears.

**Comment by timofeycom** [comment]
Seems like this issue has been fixed before in #12787 and once again reappeared.

**Comment by youknowriad** [comment]
Can you try with the last Gutenberg plugin release? The issue was fixed in Gutenberg 5.1 which is not included in WordPress 5.1.1

**Comment by kennethz3** [comment]
> 
> 
> Can you try with the last Gutenberg plugin release? The issue was fixed in Gutenberg 5.1 which is not included in WordPress 5.1.1

You're right @youknowriad , Gutenberg plugin solves the issue 👍 
Thanks!

**Comment by youknowriad** [comment]
Thanks for checking, let's close this.
