### ISSUE TITLE
Documentation: Clarify best practices surrounding color palette names

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14989]
Related:

- https://core.trac.wordpress.org/ticket/46698
- https://github.com/WordPress/gutenberg/issues/2699
- https://github.com/WordPress/gutenberg/pull/5273

Current documentation: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-support.md

The `editor-color-palette` theme supports enable a theme developer to specify a custom color palette for their themes. Each color should include a `name`, `slug`, and `color` values.

The current documentation neither describes each value, nor importantly does it set clear guidelines around the purpose a `name` should fulfill in providing human-friendly (and accessible) labels describing the color.

Per [the related ticket](https://core.trac.wordpress.org/ticket/46698), it may be good to include guidance around dynamic values (such as those sourced from a site option). For example, while not all dynamic values could be described programmatically, it may be advisable to provide meaningful names for at least the default values when applicable.

**Comment by nickylimjj** [comment]
Am picking this one up. Will submit a PR soon.
