### ISSUE TITLE
Paste: Convert parts with monospace font into code

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#14993]
**Is your feature request related to a problem? Please describe.**
I am writing some documents in Google Docs, where I used Courier New for code snippets. When pasting the text into the Gutenberg editor, that formatting is completely lost.

**Describe the solution you'd like**
It‘d be awesome if Gutenberg would turn these Courier New code snippets from my document into actual `<code>` upon paste.

**Comment by ellatrix** [comment]
This seems quite complex. How do you detect a monospaced font other than keeping a list of it? Could other user use it for something other than code? Someone might just like writing with Courier New? Google should add a code button. :)

**Comment by ellatrix** [comment]
Closing as it seems too complex to implement right. Semantic intent cannot be derived from font use.
