### ISSUE TITLE
Gallery: cannot edit properly after cancelling previous edit

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#14999]
**Describe the bug**

This bug is very annoying with trying to undo gallery edits.

**To reproduce**

1. Insert a gallery with a few images or open a post with one.
2. Edit the gallery with the pencil icon.
3. Remove an image.
4. Change your mind and close the media modal.
5. The post looks still good, the image is still there.
6. Edit the gallery again with the pencil icon. The image is no longer there.

**Expected behavior**

I expect changes to be fully undone.

**Comment by derweili** [comment]
I tried to reproduce this bug is not happening for me?

What do you mean with "pencil icon"? I don't have a pencil Icon. Only a "Media Library" button which opens the media modal.

I used Chrome 78

**Comment by talldan** [comment]
@derweili The pencil used to be a toolbar icon, but was removed as something not needed in a previous update.

I also can't reproduce this any more, so will close.
