### ISSUE TITLE
Group Block - clear visual distinction between blocks in admin

### ISSUE THREAD

**Issue by paulkirspuu** [WordPress/gutenberg#15001]
Suggestion for improvement regarding the Group block:

- update styling to have a clear distinction between Group blocks, e.g. https://i.snag.gy/cup3sY.jpg

Your thoughts, please.

**Comment by lkraav** [comment]
"Visual distinction"

**Comment by youknowriad** [comment]
I think this is a duplicate of #14935 and will be closed by #14961
