### ISSUE TITLE
Can't remove block library stylesheet from the editor

### ISSUE THREAD

**Issue by rocketdevcorp** [WordPress/gutenberg#15007]
**To reproduce**

In https://github.com/WordPress/gutenberg/issues/7776 others have said that they were able to remove 'wp-block-library-css' from the back end using similar code to this:

````
add_action( 'enqueue_block_editor_assets', 'popstar_modify_editor_styles', 10 );

function popstar_modify_editor_styles() {
 	wp_deregister_style( 'wp-block-library-css' );
	wp_register_style( 'wp-block-library-css', '' );
}

````

It's not working for me.  I also tried adjusting the priority on the action.

I'm using WP 5.1.1 and the Gutenberg plugin 5.4.0.

**Comment by samikeijonen** [comment]
@rocketdevcorp Are you using handle `wp-block-library` or `wp-block-library-css`?

This is the weird part. In I'm using WP 5.1.1 and the Gutenberg plugin 5.4.0. `wp-block-library` works for me.

But when I pulled latest code from `master` couple of days ago, it does not work anymore. [I'm using the code mentioned in this comment](https://github.com/WordPress/gutenberg/issues/7776#issuecomment-406700703).

**Comment by rocketdevcorp** [comment]
@samikeijonen I had already updated to Gutenberg plugin 5.5.0 before I saw your message, but I can say that now (WP 5.1.1 and GB 5.5.0), neither handle are working.

I posted this as a new bug report, instead of just adding to #7776, because what you had reported as working before no longer works.  But I guess this issue is really more of a Feature Request.  I concur that devs really do need to be able to remove this stylesheet, or else the WYSIWYG selling point of Gutenberg goes away.

**Comment by samikeijonen** [comment]
I confirm that in plugin version `5.5.0` handles `wp-block-library` and `wp-block-library-theme` doesn't work anymore.

**Comment by justintadlock** [comment]
Changing the hook to `enqueue_block_assets` works for me on 5.6.1.  Not sure how far back that's compatible.

**Comment by samikeijonen** [comment]
I'll confirm this works, thanks @justintadlock!

@rocketdevcorp I'm going to close this ticket now, but feel free to re-open if something is unclear.

**Comment by justintadlock** [comment]
**Side note:** The `enqueue_block_assets` runs on both the front and back end.  So, you may only want to de-register on this hook.  Still use `enqueue_block_editor_assets` to register your editor-only styles.
