### ISSUE TITLE
Group Block - custom markup filtering option

### ISSUE THREAD

**Issue by paulkirspuu** [WordPress/gutenberg#15000]
Suggestion for improvement regarding the Group block:

- custom markup filtering option (to change `<div>` -> `<section>`, add a `wrap` element between Group block and content, and etc.)

Your thoughts, please.

**Comment by lkraav** [comment]
Isn't there a generic block markup filtering chain in place already @paulkirspuu have you researched?

**Comment by paulkirspuu** [comment]
> Isn't there a generic block markup filtering chain in place already @paulkirspuu have you researched?

I have, didn't find a filtering option unfortunately.

**Comment by lkraav** [comment]
@paulkirspuu ping Slack #core-editor perhaps, as well.

**Comment by erikjoling** [comment]
The section block of the Ultimate Addons for Gutenberg plugin offers the possibility to switch the html-tag:

![image](https://user-images.githubusercontent.com/20614110/56800068-7e5d6880-681a-11e9-9a58-64a2efa127d4.png)

https://github.com/brainstormforce/ultimate-addons-for-gutenberg/tree/master/src/blocks/section

**Comment by swissspidy** [comment]
In the meantime, the `blocks.getSaveElement` filter can be used to change the HTML tags.

I don't think giving everyday users an option to change the HTML tag makes sense. They would not know what to do with that.

**Comment by lkraav** [comment]
Tyvm. @paulkirspuu lmk what you can do w/ this filter.

**Comment by strarsis** [comment]
But this means when a theme is switched, all pages have to be opened in page editor and re-saved so the `blocks.getSaveElement` filter can update the markup? Wouldn't it be better to have an intermediate layer that can change the markup on editor page and frontend, without affecting the stored editor content?

**Comment by strarsis** [comment]
But this means when a theme is switched, all pages have to be opened in page editor and re-saved so the `blocks.getSaveElement` filter can update the markup? Wouldn't it be better to have an intermediate layer that can change the markup on editor page and frontend, without affecting the stored editor content?

**Comment by carolinan** [comment]
@paulkirspuu
Hi!
The group block has an HTML Element filter in the Advanced section.
This was added in **https://github.com/WordPress/gutenberg/pull/28576**
Can this issue be closed?

**Comment by lkraav** [comment]
> Can this issue be closed?

We ended up using stock Group block markup in editor and we filter its output at PHP level via `add_filter render_block_data`.

Other options mentioned above also help people for alternatives.

This issue is solved.
