### ISSUE TITLE
className attribute is added automatically when updating attributes

### ISSUE THREAD

**Issue by alialaa** [WordPress/gutenberg#15017]
Hello, I am having a problem that I am not sure if it's a bug or an intended behaviour.
Let's say we have a very simple block with a boolean attribute amongst the attributes:
```
const attributes = {
   shadow: {
        type: 'boolean',
        default: false,
    },
}
```
Now in the let's say the save function looks like so, it depends on the boolean attribute to add/remove a class:
```
save: ({ attributes }) => {
        const { shadow, content } = attributes;

        const classes = classnames({
            'has-shadow': shadow,
        });

        return <RichText.Content
            tagName="p"
            value={ content }
            className={classes}
        />
}
```

Now if I create this block and turn on the 'shadow' attribute. I should have the 'has-shadow' class in the p tag as expected.
But let's say I changed the attribute name or removed it?
### **What I expect**
A deprecation error will be thrown because the current saved markup has the 'has-shadow' class but the new save() function does not return the p tag with this class.

### **What happens**
No deprecation errors, block works fine and the 'has-shadow' class still exists and is moved into a new attribute called 'className' and it cannot be removed except from the extra classes in the advanced settings.

So is this intended? if yes then how should I handle deprecations if I need to remove the shadow feature or change the attribute's name?

**Comment by youknowriad** [comment]
This is actually an expected behavior. For blocks that support custom classNames we don't consider extra classNames as validation errors. The main reason for this is that users tend to add and remove classNames in the markup too often and we don't want to create invalidation errors in these cases.

**Comment by alialaa** [comment]
Thanks a lot @youknowriad, that makes sense. So the only way to update that block if the attribute is removed is to manually remove the class from the extra classes filed right?

**Comment by youknowriad** [comment]
Yes, It seems like it.

**Comment by youknowriad** [comment]
Another option is to disable custom classNames for this block (I don't know if you want to do that though)

**Comment by alialaa** [comment]
OK thanks a lot for your help!
