### ISSUE TITLE
Publish button styling issue

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#15029]
**Describe the bug**
When you click on Publish button, it looks like this while it's in `isBusy` state. It appears `is-default` class is being added to the button even when it's set to primary.

<img width="257" alt="Screen Shot 2019-04-18 at 3 16 42 AM" src="https://user-images.githubusercontent.com/2649903/56323120-85d0a200-6188-11e9-9000-a27a72920a73.png">

**To reproduce**
1. Open Gutenberg and click on Publish.
2. Or you can manually add `is-busy` class to the button.

**Expected behavior**
Color to be blue.

**Desktop (please complete the following information):**
 - OS:MacOS
 - Browser Firefox latest

**Comment by jemlovestodraw** [comment]
Feedback as per #15231 
Agreed, it is hard to read. A simple fix could be to put the text (Updating...) in the medium blue of the original button.

**Comment by aduth** [comment]
Fix at #16303
