### ISSUE TITLE
Quote Block: more distinction between the quote and citation.

### ISSUE THREAD

**Issue by cecoates** [WordPress/gutenberg#15028]
## Steps to replicate

1. Add a quote block.
2. Be sure to add a quote, as well as a name for the citation.
3. Publish the page.

## Result

It's difficult to determine the difference in text between the quote and citation.

## Expected

More distinction, similar to how the pull quote block works:

![Annotation on 2019-3-3 (1)](https://user-images.githubusercontent.com/10121835/56322369-83d9f500-612e-11e9-9e72-02dcc90834d5.png)

If you italicize your quote for some reason (we allow people to do it, so they'll do it) the text is identical:

![Screen Shot on 2019-04-17 at 16_32_23](https://user-images.githubusercontent.com/10121835/56322398-981df200-612e-11e9-8d6f-847876b82259.png)

Reported in 1961093-zen.

**Comment by youknowriad** [comment]
I think this is more a theme issue than a Gutenberg issue. Gutenberg does provide more opinonated styles but these are "opt-in" in themes and themes can always override the default styles provided by Gutenberg.

**Comment by youknowriad** [comment]
The screenshots shared here do not correspond to the default citation styles provided by Gutenberg which means this theme is already tweaking the styles. I'm going to close, please make sure to follow-up with the theme author. Thanks.
