### ISSUE TITLE
When using `allowed_block_types` filter the inserter doesn't show reusable blocks which consists of multiple blocks.

### ISSUE THREAD

**Issue by erikjoling** [WordPress/gutenberg#15037]
**Describe the bug**
I'm using the `allowed_block_types` filter to whitelist blocks. I have the `core/block` whitelisted. But the inserter only shows the reusable blocks which have only one block inside them. If a reusable block consists of multiple blocks it is not shown in the inserter list.

**To reproduce**
1. Use the `allowed_block_types` to allow `core/block` and `core/paragraph`.
2. Create two reusable blocks: one with one paragraph block, the other with two paragraph blocks
3. Open the inserter
4. See that only one reusable block is available

**Screenshots**
![image](https://user-images.githubusercontent.com/20614110/56351108-a15d9c00-61cc-11e9-8893-e83dd2b931a5.png)

**Additional context**
- It is the same for Gutenberg 5.4 and 5.5

**Related**
- https://github.com/WordPress/gutenberg/issues/5893

**Comment by saulirajala** [comment]
I can confirm this bug to happen.

However, if you also whitelist `core/template`, the block with two paragraphs will appear

**Comment by talldan** [comment]
Tested the latest version of the plugin and this is now resolved, so will close the issue.
