### ISSUE TITLE
Don't show heading ancestors in the document outline

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15034]
See https://github.com/WordPress/gutenberg/pull/5314#issuecomment-484404484 and https://github.com/WordPress/gutenberg/pull/14889#issuecomment-482490646

When headings are nested within other blocks, the document outline displays the headings ancestors. Example screenshots:

<img width="400" alt="Screenshot 2019-04-18 at 10 28 29" src="https://user-images.githubusercontent.com/1682452/56347530-c2ba8a00-61c4-11e9-830d-5708c8a24ea9.png">

<img width="526" alt="screen shot 2018-04-06 at 18 49 11" src="https://user-images.githubusercontent.com/704594/38435987-49405780-39cb-11e8-9abd-8d226596d752.png">

To some extent, I understand the argumentation behind #14889, quoting:
> We are just showing the nesting path in the outline as a way to make the structure more intuitive to the user, and make it easier to navigate in the document.

However, I'm not sure displaying the ancestors adds a real value for users. Instead, it makes the UI pretty confusing. Also, the more nested blocks, the more the document outline UI will be confusing.

One more concern is the way the document outline is announced by screen readers: hearing, for example, "Section Column Column H2 My Heading" doesn't help so much.

As a user, I'd expect a tool called "Document Outline" would display just the... outline: headings. Worth also noting there are no known implementations of the HTML5 outline algorithm: as mentioned in https://github.com/WordPress/gutenberg/pull/5314#issuecomment-484404484 the current W3C recommendation is: "use heading rank (h1-h6) to convey document structure."

**Comment by draganescu** [comment]
This is still an issue in Gutenberg 7.9.1 and I agree with @afercia especially since we have the block navigation for "just showing the nesting path in the outline as a way to make the structure more intuitive to the user, and make it easier to navigate in the document."

**Comment by afercia** [comment]
Yup and worth also reminding there's now the "breadcrumbs path" below the content area that shows the nesting path.
