### ISSUE TITLE
Set featured image from remote URL

### ISSUE THREAD

**Issue by johnss** [WordPress/gutenberg#15039]
Gutenberg now already support insert image from url in the past it only allow media library but wordpress featured image currently only allow image from media library via post setting dropdown

I want gutenberg to have feature for setting featured image via gutenberg editor, instead of  via post setting dropdown, so featured image from URL will be possible

**Comment by johnbillion** [comment]
This sounds like something that needs to happen in core, not only in Gutenberg. WordPress core, plugins, themes, etc all expect there to be an attachment ID that can be used, so there would need to be a placeholder attachment that acted as a proxy for the remote URL.

**Comment by noisysocks** [comment]
> This sounds like something that needs to happen in core, not only in Gutenberg. WordPress core, plugins, themes, etc all expect there to be an attachment ID that can be used, so there would need to be a placeholder attachment that acted as a proxy for the remote URL.

Correct, this would need to happen in Core.
