### ISSUE TITLE
Why shortcode block outputs as oneline textarea in 5.5.0?

### ISSUE THREAD

**Issue by hustlahusky** [WordPress/gutenberg#15032]
**Describe the bug**
I've just updated to 5.5.0 and find out that all my shortcodes blocks looks like one-line textareas. I use shortcodes to wrap large amount of content, for example, to add fragments of code in my blog posts. And now it looks like this: https://imgur.com/2JzvARD.jpg . Also even my small shortcodes now not fully showed in one-line textarea: https://imgur.com/eTAxm2t.jpg
It just looks terrible and frustrates me. Right now I just forced to downgrading to old version of plugin.

**Expected behavior**
It must shows all my content inside textarea. At least you can simply fix this with expanding textarea while it filled with content

**Additional context**
- Pull request with change of shortcode block look #14719

**Comment by bobbingwide** [comment]
Oh my! It's atrocious. 
![core-shortcode-block-gutenberg-5 5-youre-joking](https://user-images.githubusercontent.com/2474435/56358188-d1f60380-61d5-11e9-8817-472a0dacdc09.jpg)

**Comment by bobbingwide** [comment]
Let me specify my basic requirements. 

- The shortcode block is basically a textarea where I can write shortcodes. 
- Unlike a paragraph block I don't expect any HTML to be generated other than that created by the shortcode. 
- Some shortcodes have many parameters so require a lot of space.
- Some shortcodes handle content between the start and end tags. These could also be very long.
- The textarea should expanded to fill the space available.
- As a sighted person the label is an unnecessary distraction; the custom HTML block (core/html) does not have a label. Nor does the preformatted block ( core/preformatted ).

**Comment by bobbingwide** [comment]
Here's an example showing a modified Shortcode block and Custom HTML and Preformatted blocks for comparison.
![image](https://user-images.githubusercontent.com/2474435/56496984-a2a40700-64f3-11e9-8514-09a469d88155.png)

**Comment by aduth** [comment]
Possible regression of #14719 (cc @mapk)

**Comment by bobbingwide** [comment]
It appears that it was this commit that messed it up. https://github.com/WordPress/gutenberg/pull/14719/commits/aaa9e3ac54d904ff96a97d4a9370d52b27f1b506

**Comment by mapk** [comment]
Sorry folks. The field should expand with the text, or at least be expandable by dragging the corner. I'll try to get a PR going to solve this asap.

**Comment by hustlahusky** [comment]
Nice to see that fix was implemented. But how soon it will be available in plugin?

**Comment by aduth** [comment]
@hustlahusky It should be available as of the Gutenberg 5.8 plugin release, scheduled for tomorrow (Wednesday, May 28).

For future reference, if you look to the pull request, it should typically be assigned into a release milestone, visible in the right sidebar.

See #15365 

![image](https://user-images.githubusercontent.com/1779930/58505250-82064700-815a-11e9-9938-c8ee36d09e9e.png)
