### ISSUE TITLE
Some package footers are missing "Code is Poetry"

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#15047]
**Describe the bug**
On package documentation pages, there is an inconsistency with the footers. Some have the "Code is Poetry" slogan and some do not.

![Screen Shot 2019-04-18 at 9 57 23 AM](https://user-images.githubusercontent.com/359867/56366152-6b1a1f80-61c0-11e9-9980-ced351314363.png)

The logo needs to be added where missing (and maybe pulled into a footer template that gets included everywhere). The presence of this slogan is important for when the README files are included on npm.js.

This was [originally reported in Trac](https://core.trac.wordpress.org/ticket/46430).

**Comment by manooweb** [comment]
I'm doing it for the first french contibutor day at WordCamp Paris 2019 today
