### ISSUE TITLE
parse_blocks() is creating NULL blocks

### ISSUE THREAD

**Issue by leecollings** [WordPress/gutenberg#15040]
When using `parse_blocks()` to create a `foreach` loop in PHP, there are NULL blocks being added between blocks that are disrupting any indexed loops from running.

For example, in Wordpress, I create three Media & Text blocks: 
![image](https://user-images.githubusercontent.com/6681733/56356657-6447d880-61d1-11e9-86af-6ccda6296313.png)

I expecting to be able to loop through using `parse_blocks()` and have them as an indexed array ie. `[0]`, `[1]` and `[2]`.

However, when I `var_dump(parse_blocks($post->post_content))` I'm actually returned with an array that has 5 elements, which 1 and 3 appearing as below: (0, 2 and 4 show up as the expected output)

` [1]=> NULL [2]=> string(2) " " [3]=> NULL [4]=> string(13) "
" } } [1]=> array(5) { ["blockName"]=> NULL ["attrs"]=> array(0) { } ["innerBlocks"]=> array(0) { } ["innerHTML"]=> string(2) " " ["innerContent"]=> array(1) { [0]=> string(2) " " } }`

Why is this happening, and how can the NULL array elements be removed?

I actually found this has been reported as an issue in Wordpress core (https://core.trac.wordpress.org/ticket/45312) but it was just closed without being looked into, so I'd like to try and get this re-opened. I'll try myself, but could others also help look into this please?

**Comment by dmsnell** [comment]
@leecollings as noted in [#45312](https://core.trac.wordpress.org/ticket/45312) this isn't the kind of thing where the code unexpectedly did something nobody intended. It may be surprising behavior to some but it's working as it was intended to work and this largely stems from the pool of concerns related to supporting existing WordPress posts and "non-block content."

If I were to suggest a place to consider changing things it would be at the tradeoff of providing easily-readable block output vs. removing needless whitespace as this is a decision that the editor makes on save. That is, if we remove the content between blocks then the parser won't generate the whitespace-only freeform HTML blocks.

To clarify, blocks whose `blockName` is `null` are specifically intended to convey - "this is a freeform HTML block."

---

If you want to skip over them then you are definitely able to and encouraged to do so. You could create a wrapper for `parse_blocks()` that adds your additional semantics to the parse.

```php
function is_non_empty_block( $block ) {
	return ! ( $block['blockName'] === null && empty( trim( $block['innerHTML'] ) ) );
}

function parse_blocks_ignore_empty_blocks( $input ) {
	return array_filter( parse_blocks( $input ), 'is_non_empty_block' );
}
```

**Comment by leecollings** [comment]
Thanks for this, with a little tweak to the way I'm counting the blocks (as it was still counting the hidden blocks), this has now solved my issue I was having.
