### ISSUE TITLE
Button Block: Focus style for the button text is not clear

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#15051]
As noted by @afercia in #10128, the focus style of button text within the button block is not clear. In this GIF, you can see a _very_ subtle cursor sitting in between the `t` and `e` of the placeholder text: 

![button-focus](https://user-images.githubusercontent.com/1202812/56374656-b688f980-61d1-11e9-82c6-54d1dc7aa856.gif)

This does not make it entirely clear that your focus is within the button, and that typing will add text to this area. 

When you start typing, this blinking cursor is a little more evident: 

![button-focus-text](https://user-images.githubusercontent.com/1202812/56374732-e2a47a80-61d1-11e9-8607-66150e8cacea.gif)

At a minimum, we should try to improve the visibility of the blinking cursor in the placeholder state, but I'd recommend we go further than that and sort out a stronger indicator of focus for the button as well.

**Comment by nfmohit-wpmudev** [comment]
I've started a PR for this [here](https://github.com/WordPress/gutenberg/pull/15058) ❤️
