### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#15068]
Overview of upcoming projects and areas of interest for the Gutenberg project. For suggesting other ideas, please open pull requests against the document for discussion.

### [View Document](https://github.com/WordPress/gutenberg/blob/master/docs/roadmap.md)

**Comment by annezazu** [comment]
Is this still in active usage? If not, it would be great to close this out in case someone stumbles upon it (like myself) :)

**Comment by mtias** [comment]
We had it pinned before to link to the document. We can proceed with the document :)
