### ISSUE TITLE
Classic bloc in Group bloc

### ISSUE THREAD

**Issue by nicpelletier** [WordPress/gutenberg#15060]
**Describe the bug**
After BE reload, a Classic block placed inside a Group Block is replaced by error message "This block contains unexpected or invalid content.". I'm using Gutenberg 5.5.0 and WordPress 5.1.1.

**To reproduce**
1. Insert Group bloc
2. Insert Classic bloc inside
3. Save
4. Reload the backend (F5 or go somewhere else and come back to edit this post)

**Desktop:**
 - OS: Windows
 - Browser : Chrome
 - Version : 73.0.3683.103

**Comment by youknowriad** [comment]
Thanks for opening this issue, this is a duplicate issue though (see #13187)
