### ISSUE TITLE
Undo - Redo : Paragraph block inconsistency

### ISSUE THREAD

**Issue by ashwin-pc** [WordPress/gutenberg#15064]
**Describe the bug**
The undo command on a paragraph block is inconsistent with the expected behaviour. When a paragraph block is split into two paragraphs by using the `return` key, the undo function replaces the text in the block that was split but does not delete the block that was created to produce the split. See screen grab for the issue. Even the Redo behaviour introduces this additional step.

**To reproduce**
Steps to reproduce the behaviour:
1. Create paragraph block with some text.
2. Place cursor in the middle of the text and hit the `Return` key.
3. Once the paragraph block is split in two, click undo or `Cmd + Z` 
4. The text in the first block that was removed comes back but the newly created block does not get deleted.

**Expected behaviour**
When the paragraph block gets split in two when the user hits the `Return` key, the undo should not only return the first paragraph block to the old state, but also delete the new paragraph block created to house the split section of the content.

**Screenshots**
![test](https://user-images.githubusercontent.com/20453492/56389768-68d3b780-61f8-11e9-85d1-0031850e175f.gif)

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave
 - Browser Chrome
 - Version 73

**Comment by draganescu** [comment]
Howdy @ashwin-pc I'll close this as it seems to not be an issue anymore in Gutenberg 7.9.1. Let me know if I've missed something, thank you!
