### ISSUE TITLE
HTML entities in Author name are not decoded

### ISSUE THREAD

**Issue by waviaei** [WordPress/gutenberg#15065]
**Describe the bug**
I have a user which contains "&" in Last Name of Name. `&amp;` is correctly decoded to display "&" everywhere, including the classic editor, but it is not decoded in the Block editor.

**To reproduce**
1. Go to 'Users'. Either edit the existing user or add new user
2. Type the 'Last Name' and make sure to include "&". Click Save.
3. Check on Block Editor
4. Check on Classic Editor

**Expected behavior**
`&amp;` should be correctly decoded to "&".

**Screenshots**

Name set in the User:
<img width="232" alt="スクリーンショット 2019-04-19 11 51 57" src="https://user-images.githubusercontent.com/1564991/56403190-2fa05380-629b-11e9-82bb-11035c3ab36b.png">

How it is displayed in Classic Editor:
<img width="429" alt="スクリーンショット 2019-04-19 11 51 21" src="https://user-images.githubusercontent.com/1564991/56403212-38912500-629b-11e9-9c7b-6594a56fb27a.png">

How it is displayed in the block editor:
<img width="261" alt="スクリーンショット 2019-04-19 11 51 46" src="https://user-images.githubusercontent.com/1564991/56403204-34650780-629b-11e9-9275-b1772deb2134.png">

**Desktop (please complete the following information):**
 - MacOS 10.13.6
 - Safari 12.1

**Additional context**

Tested with both:

- WordPress 5.2-beta3-45248
- WordPress 5.2-beta3-45248 + Gutenberg 5.5.0

**Comment by foysalremon** [comment]
#15090

**Comment by aduth** [comment]
Fixed by #15090
