### ISSUE TITLE
Mixed Content error on https

### ISSUE THREAD

**Issue by jazzsequence** [WordPress/gutenberg#1507]
Gutenberg editor does not appear at all for me and dev tools console shows a mixed content error:

`Mixed Content: The page at 'https://jazzsequence.com/wp-admin/admin.php?page=gutenberg' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://jazzsequence.com/wp-json/wp/v2/'. This request has been blocked; the content must be served over HTTPS.`

To be clear, my API endpoint is accessible at http://jazzsequence.com/wp-json/wp/v2/ **or** https://jazzsequence.com/wp-json/wp/v2/

**Comment by nylen** [comment]
We've fixed a few related situations in core (https://core.trac.wordpress.org/ticket/36451 for example).

I think what is probably going on here is that your site's "home URL" is set to `http:`, but it is being served over HTTPS.  Try visiting `Settings > General` in your dashboard and ensuring that both URLs are set to `https:` as follows:

![2017-06-27t18 27 57 0200](https://user-images.githubusercontent.com/227022/27598644-bffaed1a-5b2b-11e7-9083-d2e8d81c59e7.png)

**Comment by jazzsequence** [comment]
Okay, that makes sense. This is complicated by the fact that this is a multisite and this is my main site, so I can't edit the home url directly. I will try hacking the database and close if it resolves.

**Comment by nylen** [comment]
Another solution would be to add a filter on `rest_url` that forces the URLs to `https:`.

**Comment by sunapi386** [comment]
I'm using Bitnami and the URL settings were greyed out. I wanted to enforce https.
So I had ssh and to edit `/opt/bitnami/apps/wordpress/htdocs/wp-config.php` and edit these lines to `https`.

```
define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/');
```
