### ISSUE TITLE
Awkward behavior in format links due to "components-animate__appear" class on Popover Url

### ISSUE THREAD

**Issue by onuro** [WordPress/gutenberg#15079]
**Describe the bug**
After Gutenberg 5.4 the popovers reveal nicely animated. However when you format text to create a link, and start moving keys left and right between letters in the link, there's the awkward popover animation start over which feels annoying.

**To reproduce**
1. Create a paragraph
2. Select part of the text and click on "link" inthe format toolbar
3. Add some link to the selected text
4. Click on a character on the link and start moving between characters by keyboard left/right.

**Expected behavior**
Popover is not supposed to reanimate

**Screenshots**
![Screen Shot 2019-04-20 at 04 30 06](https://user-images.githubusercontent.com/645713/56449717-2d370b80-6326-11e9-895d-864d0add8728.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS 10.13.6]
 - Browser [Chrome]
 - Version [73]

My plugin's format extension also uses wp popover component and what I did to resolve it was disable animation if it has my custom class:
```
.kioken-format-highlight-popover {
    &.components-animate__appear {
      animation: none !important;
    }
}
```

**Comment by jorgefilipecosta** [comment]
Hi @onuro, thank you for reporting this bug. It was solved in the last version of Gutenberg (5.5). If the problem is persisting in your tests feel free to reopen the issue.
