### ISSUE TITLE
Paragraph Font Size field allows negative numbers

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15082]
**Describe the bug**
The Paragraph Font Size field shouldn't allow negative numbers.

**To reproduce**
1. Select a Paragraph Block
2. In the Settings Sidebar, click the font size down arrow to reduce the number below zero
3. Invalid numbers shouldn't be allowed

**Expected behavior**
Font size should't go below zero

**Video**
https://cl.ly/8a7a413d688d

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Browser: Firefox Quantum 66.0.2
- Version: 5.2-beta3

**Comment by draganescu** [comment]
I added a small PR for this, but am unsure if this is all it takes ;)
