### ISSUE TITLE
Double-click needed to change the focus style of ordered list

### ISSUE THREAD

**Issue by Jackie6** [WordPress/gutenberg#15086]
**Describe the bug**
Suppose you have a list block, the list is unordered and has multiple list items. You want to change it to an ordered list, you need to click the button "Convert to ordered list" twice in order to change the focus style of the button.

**Expected behavior**
Only one click is necessary

**Screenshots**
![PE0XAjT4pp](https://user-images.githubusercontent.com/24849874/56463855-995b5300-63aa-11e9-8845-9a843c7ede16.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Gutenberg 5.4

**Comment by jorgefilipecosta** [comment]
Hi @Jackie6, thank you for reporting this issue. Unfortunately, I was not able to reproduce this problem. Could you provide some additional details? Like what plugins you have installed on the test website? The version you are testing is Gutenberg 5.5? Does the problem also happen on Gutenberg master? Do you have any extensions installed on Chrome that may impact this behavior does the problem happens without extensions or in other browsers?

Thank you in advance!

**Comment by Jackie6** [comment]
@jorgefilipecosta After upgrading to Gutenberg 5.5, this issue disappears. Sorry for this. And the issue can be closed.

**Comment by jorgefilipecosta** [comment]
Thank you for confirming Gutenberg 5.5 fixed the issue.
