### ISSUE TITLE
Inline Image resizing doesn't work reliably

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15081]
**Describe the bug**
When you click on an inline image it displays a small control that allows you to change the width. If you try to click the up or down arrows in the number field, the control simply closes and doesn't let you change the number. The only way to change the number (using the up/down arrows) in the number field is by placing your cursor in the field, and then clicking the up/down arrows. If the number field isn't selected, the control simply disappears when you try to edit it.

**To reproduce**
1. Insert inline image
2. Click image to display width control
3. Click on the up/down arrows in the number field
4. Watch control disappear automatically

**Expected behavior**
I shouldn't have to select the number field before being able to click on the up/down arrows to change the number

**Video**
https://cl.ly/5700bd6a5fec

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Browser: Firefox Quantum 66.0.2
- Version: 5.2-beta3

**Comment by jorgefilipecosta** [comment]
Hi @maddisondesigns, thank you for reporting this issue. I was able to reproduce it in my tests on firefox. When testing on chrome the problem did not happen.

**Comment by maddisondesigns** [comment]
Just tested on Chrome 73.0.3683.103 now and yep, it seems to work fine on that browser. Chrome seems to auto-select the number field as soon as you hit one of those up/down arrows, whereas Firefox doesn't.

**Comment by paaljoachim** [comment]
Hey @maddisondesigns 

Is this issue still valid? Or can we close it?

**Comment by maddisondesigns** [comment]
@paaljoachim this appears to be fixed now so I'll close this one.
