### ISSUE TITLE
I think that the additional CSS should be reflected in the editor.

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#15088]
**Describe the bug**
The probrem that not only the block editor, also the classic editor, so I reported it in the core trac first, but I will also report here.
https://core.trac.wordpress.org/ticket/46224

I think that the "Additional CSS" should be reflected to the editor.  
Users I help setting additional styles expect it.

**To reproduce**
I added .red class to the addicional CSS.
<img width="1277" alt="additional CSS" src="https://user-images.githubusercontent.com/1094306/56467128-cdd81900-6455-11e9-842a-7400ace79ba6.png">

Block Editor
<img width="1280" alt="block-editor" src="https://user-images.githubusercontent.com/1094306/56467131-d597bd80-6455-11e9-8f6a-6cd0e96c1a92.png">

Classic Editor
<img width="1279" alt="visual-editor" src="https://user-images.githubusercontent.com/1094306/56467133-dfb9bc00-6455-11e9-862d-6e194115c7dd.png">

**Additional context**
I did not know which file to write the code, so I made a sample plugin and a patch for WP Core.
https://github.com/inc2734/additional-css
https://core.trac.wordpress.org/attachment/ticket/46224/patch.diff

**Comment by youknowriad** [comment]
https://wordpress.slack.com/archives/C02QB2JS7/p1555938450284400

We discussed this during today's triage and session and it was decided that for the moment, it's not the best approach to just load these styles in the editor. 

This is a catch-all bucket for frontend CSS which makes it hard to distinguish what styles are specific to the post content (the editor) and what is about the theme (sidebar, widgets, logo, header...). The potential of conflicts is too big.

Longer term, once everything is a block including theme templates, this might be reconsidered.

**Comment by inc2734** [comment]
In my implementation, instead of using the CSS entered in the Additional CSS as it is, I wrap it with `.editor-styles-wrapper`.

In other words, in theory, it is the same as `editor-style.css`, and I can not understand why the possibility of collision increases.

**Comment by torounit** [comment]
@youknowriad 
I have the same questions as @inc2734.

I think too that editor-style and "additional CSS" should work in the editor as well.

**Comment by youknowriad** [comment]
@inc2734 @torounit Think about the regular WordPress user that knows a little bit of CSS. HE's not going to use this stylesheet as a way to tweak generic CSS like the example above. maybe he'd want to tweak the background of the "body" of his frontend

```
body {
   background: "red";
}
```

while his theme also has a white background around the "post entry". 

This means if we apply that background in the editor, you'd end up with a red background in the editor which is not really the intent here (as the frontend still has a white background around the post content). 

That's just an example, the possibilities of conflicts and unintended side effects are illimited.

**Comment by inc2734** [comment]
I understood.

But, there is still a problem that the design differs between the front end and the editor when using the additional CSS, so I think that some measures should be taken, such as adding "additional CSS for the editor".
