### ISSUE TITLE
Styling for caption text

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#15085]
figcaption under default images is not styled, though the editor does show styling.

The styling in the editor is perfect, so I added the editor style to my style.css for the time being:

`figcaption{
    color: #555d66;
    font-size: 13px;
    text-align: center;
}`

Would be nice if this is added as the default.

**Comment by paaljoachim** [comment]
Hey Robin

I will just add this issue in here: https://github.com/WordPress/gutenberg/issues/534

**Comment by RobinRoelofsen** [comment]
Thanks!

Op ma 22 apr. 2019 10:45 schreef Paal Joachim Romdahl <
notifications@github.com>:

**Comment by aduth** [comment]
If I understand correctly, the styles presented in the editor can be inherited directly into a theme if it opts in to the `wp-block-styles` theme support:

https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#default-block-styles

I've confirmed that this is how the specific styles from the original comment are added, by presence of the `theme.css` file for the image block:

- https://github.com/WordPress/gutenberg/blob/48e06de/packages/block-library/src/image/theme.scss
- https://github.com/WordPress/gutenberg/blob/48e06de/assets/stylesheets/_mixins.scss#L313-L318
