### ISSUE TITLE
'image_default_size' setting doesn't work on Gutenberg

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#15091]
I'm Japanaese, so I'm sorry for my poor English.

The problem is 'image_default_size' setting doesn't work on Gutenberg.

I set ' image_default_size = full ' on /wp-admin/options.php, but the image set large size.

**Comment by aduth** [comment]
Related: #6177, #11529

It's possible it may be a duplicate of #11529 ? It does not mention the specific option `image_default_size`, however.

**Comment by talldan** [comment]
Also some discussion of this on https://github.com/WordPress/gutenberg/issues/8663

**Comment by henrikwirth** [comment]
Is there any update to this? For me this is a big problem. I actually want to remove all default image_sizes and only have `thumbnail` and `full` showing with the default selection of `full`.

From what I see the `large` is hardcoded as a constant here: https://github.com/WordPress/gutenberg/blob/bee1bf91958c71c733be4514b42cfa136243b3eb/packages/block-library/src/image/constants.js#L8

I guess this comment sums up what could/should be done: https://github.com/WordPress/gutenberg/issues/8663#issuecomment-588217060

**Comment by Timoostrich** [comment]
I still have this problem, too.

**Comment by laurentdebricon** [comment]
i would love this fixed !

**Comment by Mamaduka** [comment]
Fixed via #29966.
