### ISSUE TITLE
'Convert to blocks' from classic editor breaks side by side images

### ISSUE THREAD

**Issue by nicopujol** [WordPress/gutenberg#15093]
**Describe the bug**
We have many posts with small size photos which are layed out side by side from the time of the Classic Editor. We are converting the posts to blocks and from side by side, they are now vertically stacked.

**To reproduce**
- Sample page, post conversion: https://www.laylita.com/recettes/soupe-tortilla-dinde-poulet/
- Scroll down to see after the recipe card.
- The photos got converted to HTML blocks. Not sure why. 
- Here is a sample code from these new blocks (which seems to display side by side here on Github): 

<div><figure><img class="alignnone wp-image-2540 size-full" title="Préparation de la soupe de poulet ou de dinde" src="https://www.laylita.com/recipes/wp-content/uploads/2011/11/Tortilla-soup-prep-1.jpg" alt="Préparation de la soupe de poulet ou de dinde" width="320" height="214"></figure>&nbsp;<figure><img class="alignnone wp-image-2541 size-full" title="Préparation de la soupe de poulet ou de dinde" src="https://www.laylita.com/recipes/wp-content/uploads/2011/11/Tortilla-soup-prep-2.jpg" alt="Préparation de la soupe de poulet ou de dinde" width="320" height="214"></figure></div>

**Expected behavior**
Retain side by side layout after converting to blocks

**Screenshots**
![convert to blocks breaks side by side layout](https://user-images.githubusercontent.com/1319146/56476165-a6c71a80-6448-11e9-937a-7033c82497da.jpg)

Is there an easy we can do to keep the side by side layouts as before Gutenberg block conversion?

**Comment by jorgefilipecosta** [comment]
Hi @nicopujol, thank you for opening this issue. I guess the simplest way would be to select both images after conversion and convert them to a gallery block, it should provide a very similar design. Alternatively, adding the images inside the columns block may also fit this use case.
If none of the suggestions fit your use case feel free to reopen the issue.

**Comment by nicopujol** [comment]
Thanks @jorgefilipecosta. Unfortunately, we have so many side by side images which are only separated by 1 space bar in the classic editor, that the process of converting all pairs to a gallery block or column blocks does not seem to work with our current code. We will likely need to continue living in the Classic Editor, unless you can think of a way to quickly convert these for each post (ideally, the Convert to Blocks process would keep that layout intact).
