### ISSUE TITLE
Feedback: Video showing the use of multiple image blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15098]
I made a video: https://youtu.be/GI9EJJmzEuI showing various issues using multiple image blocks and using alignment.

I am on a Mac OSX 10.13.6 using Chrome.

**Comment by paaljoachim** [comment]
Here is part 2.
https://youtu.be/zgA1XJqPYwk

**Comment by youknowriad** [comment]
Let's extract anything useful into dedicated issues.

**Comment by paaljoachim** [comment]
Good idea Riad!

I went through video 1. It looks like the issues are mostly taken care of.
I believe the issues in video 2 are being worked on by @jasmussen .

New issues:
Caption alignment bug:
https://github.com/WordPress/gutenberg/issues/17162
