### ISSUE TITLE
Release @wordpress/dependency-extraction-webpack-plugin

### ISSUE THREAD

**Issue by michaelzangl** [WordPress/gutenberg#15092]
**Describe the bug**
The @wordpress/dependency-extraction-webpack-plugin is not released but included in the documentation.

**To reproduce**
See https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin/#installation

→ npm install @wordpress/dependency-extraction-webpack-plugin --save-dev
→ The command fails 
```
npm ERR! code E404
npm ERR! 404 Not Found: @wordpress/dependency-extraction-webpack-plugin@latest
```

**Expected behavior**
Either not add it to documentation or release it.

**Comment by jorgefilipecosta** [comment]
Hi @michaelzangl I think this plugin should be released during the next package release process. Is that the case @gziolo ?
Unfortunately, there is a time between the package creation/documentation and the release where the documentation is "wrong" maybe we should only merge the documentation update after the packages are released?

**Comment by aduth** [comment]
To the general issue of documentation being synced to `master` vs. what's available in stable (published) versions, I'd consider this as sufficiently tracked by:

- https://meta.trac.wordpress.org/ticket/4244
- #14303

>Hi @michaelzangl I think this plugin should be released during the next package release process. Is that the case @gziolo ?

This is correct, and described at the following documentation:

https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#packages-releases-and-wordpress-core-updates

See also previous conversation: https://github.com/WordPress/gutenberg/pull/14869#issuecomment-484040241

**Comment by michaelzangl** [comment]
@jorgefilipecosta / @aduth  Thanks for the explanation.
