### ISSUE TITLE
Close/open parent categories in sidebar.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15103]
**Is your feature request related to a problem? Please describe.**
I have made a top parent category named Archive. Inside it is all the old posts of the site. There are a lot of child categories. I have to scroll past all the Archive children categories to get to the newer categories below.

<img width="306" alt="Screen Shot 2019-04-22 at 12 48 25" src="https://user-images.githubusercontent.com/5323259/56497315-4f36b680-64fd-11e9-9a8e-b05130dc61dc.png">

**Describe the solution you'd like**
I would like a standard open/close sub page icons.

Perhaps something like this:

![Categories-children-Sidebar-open-Gutenberg](https://user-images.githubusercontent.com/5323259/56497600-8c4f7880-64fe-11e9-864b-96d1fde221a3.jpg)

![Categories-children-Sidebar-closed-Gutenberg](https://user-images.githubusercontent.com/5323259/56497601-8c4f7880-64fe-11e9-9deb-318c7260cfe8.jpg)

**Describe alternatives you've considered**
Scrolling in the sidebar categories list.

**Comment by kjellr** [comment]
This would no doubt be useful to some users — mostly in larger corporate sites. But it's largely an edge case. As such, it may make sense to only include this in a plugin. 

That said, if someone were dedicated to this, and wanted to open up a PR here, I don't think it'd do any harm to have it included. 

Some design questions: 

- How would these show/hide sections persist on page loads? If you expanded a section, would it remain expanded when you loaded up a new post? 
- I don't believe we have a slim show/hide control like that (other than maybe just our expand/collapse arrows?). Are there other areas where this would be useful?

**Comment by drw158** [comment]
See this example from Ant Design that has the same idea. It's helpful to see how it's implemented and how it feels. https://ant.design/components/tree/#header

**Comment by paaljoachim** [comment]
Use case. Example

![Screen Shot 2019-07-04 at 17 03 23](https://user-images.githubusercontent.com/5323259/60675856-afdb5b80-9e7d-11e9-8910-f8290a371da8.png)

A client site I have has an Arkiv (Archive) of older blog posts. These are inside a category structure with a parent Arkiv and various sub categories.

When there is a newer blog post I have to scroll past the Arkiv to the newer post categories.

<img width="337" alt="Screen Shot 2019-07-04 at 17 05 41" src="https://user-images.githubusercontent.com/5323259/60676013-106a9880-9e7e-11e9-972e-0f73fc3c5007.png">

It would be helpful to be able to close the post category Arkiv tree structure and only open it when needed.

**Comment by karmatosed** [comment]
My feeling is this should be in a plugin in agreement with @kjellr so let's close for now. If there is a plugin it could be great to then see that considered.
