### ISSUE TITLE
Embedded blocks or FaceBook links are not displayed properly in "Reusable‑Block"

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#15101]
**Describe the bug**
Embedded blocks or FaceBook links,
are not displayed properly in "Reusable‑Block",
when they were displayed properly before creating the "Reusable‑Block"…

**To reproduce**
1. Go to editor…
2. Make a post with one blockquote with text, and a link to a facebook post in a new line... Add some embedded (YouTube or else) contents.
3. Preview all appear, now convert all that page in Reusable‑Block.
4. See error : Preview, now the embedded contents & FaceBook links don't appear…

**Expected behavior**
All embedded contents and links in BlockQuote or else should appear properly…

**Screenshots or Screencasts**
Take to much time to make and edit them…

**Desktop (please complete the following information):**
 - O.S.: Windows 10
 - Browser: FireFox & Chrome
 - Version: last version both.i]

**Additional context**
- I use the Gutenberg integrated in the WordPress.com page…
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
This seems like a duplicate of #14608
