### ISSUE TITLE
Drag and drop from inserter to post

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1511]
Interested in options for adding drag and drop in the following situations:

1. Drag from insert modal to desired location on screen between existing blocks

~~2. Drag blocks above/below each other by dragging the gray borders~~ covered by #38 

Annotations:

<img width="3108" alt="drag and drop" src="https://user-images.githubusercontent.com/3411173/27599682-66544eb2-5b1e-11e7-98ec-eb56e70b8b5a.png">

_Note: This may have already been discussed, if so we can close this out._

**Comment by mtias** [comment]
Related #38.

**Comment by jwold** [comment]
@mtias thanks! That covers item #2 so we can ignore that. What about #1?

**Comment by mtias** [comment]
Sounds interesting as a progressive enhancement :)

**Comment by buzztone** [comment]
We've found that _Drag from insert modal to desired location on screen between existing blocks_ is still not well developed within the currently available React based npm modules. 

_Drag blocks above/below each other by dragging the gray borders_ is by contrast well supported & very solid.

**Comment by buzztone** [comment]
Another way to give _insert modal to desired location on screen between existing blocks_ could be to allow positioning of the + icon via arrows & vertical dragging.

![2017-06-29_01](https://user-images.githubusercontent.com/1927585/27664399-a96a8ecc-5caa-11e7-8236-2ca41f534659.png)

If I could position the + icon where I want before I click it or Insert, I could add each block where I want.

**Comment by folletto** [comment]
> If I could position the + icon where I want before I click it or Insert, I could add each block where I want.

This should already be working – just not with the `+` icon: it inserts below the block you've currently selected (or in other words: where the cursor is). Does it work for you?

**Comment by buzztone** [comment]
>Does it work for you?

Yes. Though I wasn't previously aware of this, I can see it when I go looking for it based on your explanation.

It's pretty well hidden. To see it I had to:

1. Select a Block
2. Click on the + icon
3. Hover over an item in the Inserter

**Comment by jwold** [comment]
> If I could position the + icon where I want before I click it or Insert, I could add each block where I want.

Since this is already working do you feel it offsets the need for drag and drop?

**Comment by buzztone** [comment]
>Since this is already working do you feel it offsets the need for drag and drop?

No - not at all.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518717428000579)._

**Comment by mapk** [comment]
The Inserter is now a sidebar that slides out when activated. As a sidebar, the ability to drag and drop blocks directly to the document feels much more natural. I'd like to look into how we can make this happen.

### Current Inserter

![Screen Shot 2020-05-12 at 3 22 01 PM](https://user-images.githubusercontent.com/617986/81751492-6330bb80-9464-11ea-9383-54fedc1e7ee5.png)

**Comment by gziolo** [comment]
It didn't take me much time to come to the same idea after the inserter was refactored :) It would make it so much easier to put a block or pattern in the nested context at the specific level. In addition, it feels more natural to drag and drop items rather than use the in-between the blocks inserter:

![Screen Shot 2020-05-13 at 07 37 43](https://user-images.githubusercontent.com/699132/81775209-ae8eac80-94ec-11ea-980c-5f6265c1af46.png)

By the way, have you considered changing the way in-between the blocks works with drag & drop from the inserter? At the moment it's very difficult to trigger (I'm using Safari), but regardless, it could maybe set the selection in the editor accordingly to the placement clicked and open the sidebar with the inserter?

**Comment by mapk** [comment]
I agree, the sibling is SUPER difficult to activate right now. I'm not sure why.

Having it trigger the sidebar Inserter is an interesting solution. Will pushing the focus to the Inserter sidebar have any a11y ramifications?

I remember, at one time, we talked about the sibling Inserter opening the Patterns tab by default too. 

Getting drag and drop right is going to be enough for this particular issue. It would be great to get some development help on it.

**Comment by mapk** [comment]
Being able to drag from the Inserter panel into the editor is also becoming a frequently requested item for the new Widget Screen. People would like to drag blocks directly into specific widget areas.

**Comment by shaunandrews** [comment]
![drag-and-drop blocks to insert](https://user-images.githubusercontent.com/191598/97199372-525fd200-1786-11eb-8bdd-19c8f64286c9.gif)

Drag-and-drop could help resolve some common confusion around adding blocks: #26404

**Comment by talldan** [comment]
I don't think drag and drop from the block library would be technically difficult. When blocks are dragged and dropped currently, a `dataTransfer` value is set with some data about the block (client ids of the blocks, where the block is dragged from, and a `type`, which is always `block` for blocks etc):
https://github.com/WordPress/gutenberg/blob/05ee652086f74b9bcfe2b51e10c5759798329341/packages/block-editor/src/components/block-draggable/index.js#L63-L67

That's then used in the drop event:
https://github.com/WordPress/gutenberg/blob/05ee652086f74b9bcfe2b51e10c5759798329341/packages/block-editor/src/components/use-on-block-drop/index.js#L64-L73

For dragging from the inserter I imagine this would be a slightly different bit of data. The `type` would probably be something like `insert-block` or `create-block`, and the block type would be passed. Similar could be done for patterns, a type of `insert-pattern` and the pattern markup.

There are some a11y considerations. Previously there's been some feedback against a button that can be clicked and dragged when we tried that on the block toolbar.

Secondly, if the block is selected after being dropped, the block library panel will close as it's a popover. That probably makes this a little less useful, but it's the same at the moment when clicking a block.

**Comment by mtias** [comment]
> Secondly, if the block is selected after being dropped, the block library panel will close as it's a popover.

For what is worth, there's been some feedback about changing this behaviour.
