### ISSUE TITLE
Editor: Specify `_fields` for parent page selector request

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#15115]
Previously: #12930 
Related: #15114

Posts responses can be slow to generate by the REST API. For this reason, it should be considered to optimize the current Parent Page field query to include only the necessary properties to present options in the interface.

Relevant code:

https://github.com/WordPress/gutenberg/blob/48e06dedd24b43f81760f1dc88354c80169701e6/packages/editor/src/components/page-attributes/parent.js#L51-L63

**Comment by iandunn** [comment]
https://github.com/WordPress/gutenberg/issues/13618 seems related as a quick glance.

**Comment by aduth** [comment]
> #13618 seems related as a quick glance.

Good call. Let's consolidate there.

**Comment by aduth** [comment]
Duplicates #13618
