### ISSUE TITLE
Add a setup state to columns block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#15127]
It would be great to explore having a row feature in columns. CoBlocks have a great example of this (props @richtabor). How could something like this work in Gutenberg core? 

Potentially this could be:

- column resizing
- ability to select a default state (two columns, 20% 80%, etc)

There's more explained here for the row block, whilst I am recommending in columns it's an idea: https://www.youtube.com/watch?v=cAQC_L03Z70

This addition really could open up some powerful layouts.

**Comment by xenonbart** [comment]
I'd really like this, also the ability to decide how columns breakdown on smaller screens, for example having four columns breakdown to 2 columns on mobile instead of 1 really long column.

**Comment by sarahmonster** [comment]
Changed the title here to make it a bit more clear, but basically what the aim is here is to create a setup state for the columns block, so users can easily choose their layout in a visual way before they start.

**Comment by mtias** [comment]
Closed by #16129.
