### ISSUE TITLE
Add descriptive text to post settings

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1513]
@nb and I discussed the potential for adding descriptive text to each of the blocks in the core-editor channel. This text could be added into the post settings panel and would help explain each of the blocks with a line or two of text. 

As a great example, I would imagine some users would have no idea what Classic Text means (it might make sense to revisit that label in another ticket). We had talked about adding tooltips to each of the blocks inside the inserter modal, but that doesn’t seem ideal.

Any feedback/thoughts on the annotations below?

<img width="2902" alt="annotation" src="https://user-images.githubusercontent.com/3411173/27601770-629120d2-5b25-11e7-9477-ba49dfadcb6d.png">

**Comment by mtias** [comment]
I like this but on a per case basis (I added something very similar to the "more" block). I don't think all blocks would need it.

**Comment by mtias** [comment]
See https://github.com/WordPress/gutenberg/pull/1440

**Comment by swissspidy** [comment]
I did the same in #1467.

Can we put together a list of blocks that could benefit from such a description? We could then add those all in one swoop.

**Comment by jasmussen** [comment]
In https://github.com/WordPress/gutenberg/pull/2427 I've started work on this. Though I think it would be good to have a discussion: do we want descriptions for all blocks, or only some?

Back when we had the breadcrumb trail in the sidebar, I would have agreed with having it on a case by case basis. But now that we have an explicit "Block" tab that you can keep open, it feels like we should have descriptions for every single block, even to the point that if a block author didn't provide one, we should output: "This block did not provide a description", or something in that vein.

**Comment by jwold** [comment]
I agree that descriptions on all the things makes more sense than being selective. I like that.

**Comment by mtias** [comment]
This can be considered done.
