### ISSUE TITLE
Inserter (+) is hidden in responsive design

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#1514]
There is a gap between when the WordPress black sidebar collapses and the Gutenberg editor shrinks that the (+) inserter is hidden. The following animation highlights it, not sure if it is browser specific using Firefox on Windows 10.

![responsive](https://user-images.githubusercontent.com/45363/27601979-0d0b1edc-5b26-11e7-84fb-d81f9b4e4f37.gif)

**Comment by swissspidy** [comment]
We can probably close this in favor of #1535. There are many more issues with the responsive design.

**Comment by jasmussen** [comment]
I think it's best to track these separately. Please report any other responsive issues individually too. Thanks.
