### ISSUE TITLE
Permalink generator way less picky with the new editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#15141]
**Describe the bug**
Originally reported in Trac here [Permalink generator way less picky with the new editor](https://core.trac.wordpress.org/ticket/46189):

> I have a title: 161: Acute Problems - What To Do
> The permalink of old would have been "161-acute-problems-what-to-do"
> But just now, I'm getting "161:-acute-problems---what-to-do"

**To reproduce**
Add a new post with the title "161: Acute Problems - What To Do"
Note the permalink: "161:-acute-problems---what-to-do"

**Expected behavior**
To have a simpler, safer permalink "161-acute-problems-what-to-do" with the ":" removed and no repeating "-" s.

**Comment by tellthemachines** [comment]
Closing this issue as I can no longer reproduce it. Feel free to reopen if the problem reoccurs.
