### ISSUE TITLE
I have installed gutenberg in WP, but I can not use it

### ISSUE THREAD

**Issue by RieJuerg** [WordPress/gutenberg#15154]
Hello ...
I have installed gutenberg in WP, but I can not use it. when I click on the "dashboard new page" and click on "add block" is only the classik editor available. What can I do to open the gutenberg editor at a new side
![Gutenberg](https://user-images.githubusercontent.com/21111160/56678037-10059280-66c2-11e9-820b-64f9a2915f75.jpg)
?
regards Jurgen

**Comment by youknowriad** [comment]
Did you manage to solve this? You might have the REST API disabled on your CPTs or things like that?
