### ISSUE TITLE
autop: Include tests for `removep` functionality

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#15152]
Previously: https://github.com/WordPress/gutenberg/pull/15128#discussion_r278153625

As described at https://github.com/WordPress/gutenberg/pull/15128#discussion_r278153625, due to the method of porting and adapting `autop` and `removep` functions from previous core equivalent PHP and JavaScript implementations, there were no unit tests included for `removep`.

>For historical context, the module originated as a direct port of the PHP implementation of `autop`, including its tests. There is no `removep` in PHP, so there are no tests. There was a previous `removep` implementation in JavaScript from which this implementation was adapted, but it had no tests to port over.

This function is notable due to its potential impact on content produced for posts consisting of legacy content (only containing the Classic block).

https://github.com/WordPress/gutenberg/blob/d5bdd5321c8cdd0804f92118c9222c7169d6b7d9/packages/editor/src/store/selectors.js#L821-L831

**Task:** Add unit test coverage for the `removep` function.

**Comment by gziolo** [comment]
Let's move it to the tracking issue that lists all public API functions in packages that don't contain unit tests and link back to this one.
