### ISSUE TITLE
Cursor position error after copy

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#15166]
When I copy a piece of text into the editor, the cursor always precedes the text, I think it need appear at the end of text.
You can try it in [gutenberg website](https://wordpress.org/gutenberg/).

**Comment by maurisrx** [comment]
Yes, I can also confirm that. Every time I copy paste text to new paragraph block, the cursor doesn't automatically move to the end of the text but it stays at the beginning of the text.

**Comment by GlennMartin1** [comment]
Same here.  Using Chrome on Windows.

**Comment by arunsathiya** [comment]
This is a duplicate of https://github.com/WordPress/gutenberg/issues/5317.

**Comment by gziolo** [comment]
> This is a duplicate of #5317.

Thanks for reporting, let's close it in favor of #5317.
