### ISSUE TITLE
Possible typo here on repository-management.md

### ISSUE THREAD

**Issue by saracope** [WordPress/gutenberg#15174]
**Describe the bug**
In the *Design Review * section, the first bullet says 
 `- Something based on a previous design, to check is as that design.`

This doesn't make sense to me, specifically the second part at `check is as`. I think there's something missing here, but not sure what.

**To reproduce**
[repository-management.md](https://github.com/WordPress/gutenberg/blob/6e4e9aa3f92ec6e568084630c295f020da9bb13e/docs/contributors/repository-management.md#design-review)

**Expected behavior**
Clear writing

If there's a change needed, I'd be happy to PR it once someone gives clarity about what the sentence should be.

**Comment by aduth** [comment]
> If there's a change needed, I'd be happy to PR it once someone gives clarity about what the sentence should be.

My guess is that it should is intended to read as:

>Something based on a previous design, to check **that it** is as that design **prescribes**.

_(Emphasis added for missing words)_
