### ISSUE TITLE
docgen: add support for classes and groups of things

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#15178]
At the moment, classes aren't well documented. Only the JSDoc from the class declaration is taken into account, but we should also include method information, etc. Example: [token-list](https://github.com/WordPress/gutenberg/blob/master/packages/token-list/src/index.js).

A different example that could fall in the same category, could be groups of things: functions or literal objects that contain other functions. See [api-fetch](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/index.js#L138) as an example.

**Comment by nosolosw** [comment]
One approach could be using the `@class` / `@memberof` tags. Without the use of `@memberof` we can extract a lot of method info from classes, though.

**Comment by aduth** [comment]
> functions or literal objects that contain other functions. See [api-fetch](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/index.js#L138) as an example.

Another example I encountered in #15176 is the `plugins` object from `@wordpress/data`, which I explained in the pull request as desiring to better document but having unclear direction or support.

**Comment by nosolosw** [comment]
Related https://github.com/WordPress/gutenberg/issues/14332

**Comment by nosolosw** [comment]
Also related https://github.com/WordPress/gutenberg/issues/15186 See https://github.com/WordPress/gutenberg/pull/15176/files#r278829802

**Comment by oandregal** [comment]
I'm triagging issues we don't plan to tackle. We can reopen if it regains interest.
