### ISSUE TITLE
docgen: add support for @callback

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#15179]
We should be able to relate a `@callback` function and using that info in the symbol that uses it. Use case: how to document the [autocomplete](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/autocomplete/index.js#L36) component.

**Comment by paaljoachim** [comment]
I am closing this issue as I see a PR associated with it has been merged.

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
