### ISSUE TITLE
"Unexpected error" in page editing

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg#15172]
**Describe the bug**
When editing an existing page, when I click anywhere on the screen I suddenly get "The editor has encountered an unexpected error." I copied the error:

```
zn@http://mysite.dev/wp/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45248
this.wp.editor</Gn</o<@http://mysite.dev/wp/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:46071
this.wp.editor</Gn<@http://mysite.dev/wp/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45906
u@http://mysite.dev/wp/wp-includes/js/dist/editor.min.js?ver=9.0.11:12:3425
g/n</</<@http://mysite.dev/wp/wp-includes/js/dist/data.min.js?ver=4.2.1:1:6377
this.wp.editor</zi<@http://mysite.dev/wp/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:109194
n@http://mysite.dev/wp/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13036
r@http://mysite.dev/wp/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13298
zf@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258
Mf@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:87:4
ph@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474
eg@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307
fg@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168
wc@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237
fa@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115
lg@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:148:342
re@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:23:322
Xb@http://mysite.dev/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:40:304
```

This is a custom theme that's been working just fine with Gutenberg up through 5.1, though this is my first test with 5.1.1. The only active plugin is Timber, which I use in all sites to allow Twig templates.

Hopefully this is the correct place to post this - been a while since I've checked up on GB/WP development and where things need to be put.

**To reproduce**
Open a page. Click on the edit screen.

**Expected behavior**
The ability to edit my content.

**Desktop (please complete the following information):**
 - OS: OSx, Windows 10
 - Browser Chrome, Firefox
 - 5.1.1

**Additional context**
I'm using the native Gutenberg editor in WP

**Comment by maxxwv** [comment]
Any update on this? It's happening on a fresh install of 5.1.1 with no plugins installed and running twentynineteen.

**Comment by maxxwv** [comment]
Please note that I'm also getting an Unhandled promise rejection Error: "[object Response]" being throw three times from wp-polyfill.min.js.

**Comment by maxxwv** [comment]
One (hopefully) last update for anyone that finds this issue - looks like it could be a cookies issue. I cleared my cookies completely and everything *appears* to be working.

**Comment by gziolo** [comment]
> One (hopefully) last update for anyone that finds this issue - looks like it could be a cookies issue. I cleared my cookies completely and everything appears to be working.

Glad to see it has been resolved, thanks for reporting back 👍
