### ISSUE TITLE
docgen: pull type definitions from @typedef

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#15186]
There are a few places in the codebase where we document our custom types. We should have a way to document them and use them in other symbols' docs.

**Comment by nosolosw** [comment]
A good use case for this is the block-editor' `SETTINGS_DEFAULTS` ([related discussion](https://github.com/WordPress/gutenberg/pull/15807/files/1e347b0b5ec1a37fc5951b349b328330d00df356#diff-5f75f5dc4707bd94c9d0950670315d1cL352)).

**Comment by aduth** [comment]
Prior art: In a recent side-project I worked on, I was fortunate to reference [the REST API documentation of Mixer.com](https://dev.mixer.com/rest/index.html#). One nice thing about it is that, for each "Request" or "Response" overview, any custom type will link to the relevant description and properties ([example](https://dev.mixer.com/rest/index.html#Achievement)), which can be recursive as well for custom types within those properties.

For `docgen`, I might imagine something similar. The automated documentation can produce two sections:

1. Functions (or "public/exported members" generally)
2. Types

For each function description, if a parameter or return type is a custom type, it should link to the relevant type description on the same page.

We will need to find some appropriate way to distinguish between types internal to the package itself, vs. types imported from other WordPress packages (link to the relevant README), vs. types imported from third-party packages (link to...their GitHub/npm listing?)

**Comment by oandregal** [comment]
I'm triagging issues we don't plan to tackle. We can reopen if it regains interest.
