### ISSUE TITLE
docgen: add support for @inheritdoc

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#15184]
See: https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/meta-boxes/meta-boxes-area/index.js#L13

**Comment by paaljoachim** [comment]
Close?

**Comment by nosolosw** [comment]
It's still relevant but if nobody has worked on it for so long we can assume it can go to the backburner. We can always re-open.
