### ISSUE TITLE
Build Tooling: Update use of docgen to target only unstable APIs named by convention

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#15197]
Previously: https://github.com/WordPress/gutenberg/pull/14557#issuecomment-475549047, #14565

The coding guidelines surrounding Unstable and Experimental APIs are very specific in how they ought to be named.

>An experimental or unstable function or object should be prefixed respectively using `__experimental` or `__unstable`.

https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis

The current `docgen` script is lenient toward variations of these guidelines, due to preexisting issues described at https://github.com/WordPress/gutenberg/pull/14557#issuecomment-475549047 .

**Task:** The script should be made non-lenient.

**Reason:** By removing leniency, it should help make clear where coding guidelines are being violated, since the invalid token would be included (wrongly) in the generated documentation.

**Blocked by:** Prexisting issues should be resolved (aligned to the guideline).

**Comment by aduth** [comment]
> **Blocked by:** Prexisting issues should be resolved (aligned to the guideline).

Upon further investigation, I find there are two existing issues:

- [ ] `UnstableRichTextInputEvent`
   - Proposed renaming at #15198
- [ ] `unstable__bootstrapServerSideBlockDefinitions`
   - This is tricky, because it is referenced upstream in WordPress ([source](https://github.com/WordPress/WordPress/blob/700f891c36df5390cff668e876b07fd20cca8af6/wp-admin/edit-form-blocks.php#L113))
   - It may be expected that this function can be eliminated as part of the ongoing work around the Blocks Registration RFC (#13693)
   - For the above reasons, I suggest that once #15173 is merged, we simply add a `@private` tag to the exported symbol's DocBlock as an alternative approach to exclude it from the documentation

**Comment by gziolo** [comment]
This is what is still left to do:

> For the above reasons, I suggest that once #15173 is merged, we simply add a @private tag to the exported symbol's DocBlock as an alternative approach to exclude it from the documentation

**Comment by ryanwelcher** [comment]
With https://github.com/WordPress/gutenberg/pull/42198, we can also use `@ignore`.

**Comment by ryanwelcher** [comment]
@gziolo is this issue still relevant?

**Comment by gziolo** [comment]
> With #42198, we can also use `@ignore`.

Yes, we should mark `unstable__bootstrapServerSideBlockDefinitions` with `@ignore` or something similar and consider this issue complete.
