### ISSUE TITLE
Issue changing SITE URL

### ISSUE THREAD

**Issue by Emiliano-Bucci** [WordPress/gutenberg#15208]
**Description**
Hello to all! I'm facing a small issue and wanted to ask if this could/should be the correct behavior. Basically i'm developing a `headless` wordpress site, using Next.JS, GraphQL, Apollo, and all that fancy stuff :). To be able to have both `Front End` and `Backend` working, i move my wordpress installation to a subdomain, eg: `https://wp.mysite.com`, and my Front End lives in `https://mysite.com`. Till here, everything ok. In order to keep the url with the correct name (since if i create a post, for example, the url would be: `https://wp.mysite.com/my-post`), i change the `Site Address (URL)`. Doing this, (almost) everything works fine; the only problem is that, with `gutenberg` i can't create posts (or pages) anymore. This is because of the previous change: looking into the console, i see that the API call is looking for the `https://mysite.com/wp-json/...` path. 

Is this the correct behavior? If yes, is there a way to solve this? 

Thanks a lot :)

**To reproduce**
1. Go to settings.
2. Change Site Address (URL).
3. Try to create a new post.

**Comment by swissspidy** [comment]
The REST API endpoints use the home URL _by design_. See https://core.trac.wordpress.org/ticket/37020.

You might be able to use the `rest_url()` filter if you want things to point to a different location.

Other than that, this is more of a WordPress core matter than a Gutenberg issue.

The `Invalid` label sounds a bit harsh, but I just wanted to make it clear that discussion is best kept on WordPress Trac / https://core.trac.wordpress.org/ticket/37020

**Comment by Emiliano-Bucci** [comment]
Hi @swissspidy, thanks for the quick answer! I Apologize; at first i thought that it was Gutenberg that use the API in that way. I will check with the `rest_url()` filter, thanks! :)

**Comment by Emiliano-Bucci** [comment]
@swissspidy I confirm that using the filter `rest_url` i can change the endpoint and everything works perfectly; thanks! :)
