### ISSUE TITLE
Enhance KeyboardShortcuts component to automatically document 3rd party shortcuts in modal

### ISSUE THREAD

**Issue by dsifford** [WordPress/gutenberg#15205]
This discussion began in a thread on Slack, so I've copied that conversation below...

> **dsifford**   _[Today at 4:02 PM]_
Random question for the maintainers: Has there ever been any talk about adding the ability for plugin authors to hook into the "keyboard shortcuts" modal to allow them to also list the shortcuts they added in the same place? Seems like it would be a fairly simple addition just by adding in a slot/fill..

> **aduth**   _[3 hours ago]_
I’ve not seen it be discussed. It sounds like a good idea, though I’m not sure adding a Slot and letting it be a free-for-all would be my preferred way to go about it. I could see it being a nice enhancement to the `KeyboardShortcuts` component. In other words, if you use the component, you get this behavior “for free”. Also has the added advantage of making it impossible for a plugin’s keyboard shortcuts _not_ to be listed, and centralizing behavior to this component can open up some options around mitigating conflicts of shortcuts between plugins and with native key combinations.

Happy to discuss this further and work together to figure out a proper solution. I think @aduth has exactly the right idea though.

**Comment by talldan** [comment]
I followed up on the slack convo (https://wordpress.slack.com/archives/C02QB2JS7/p1556222525488500 — signup required), so also duplicating that over here:

> I worked on the modal. I did think about it at the time. However, I agree with @aduth, that registering shortcuts should add them to the modal, and also potentially open them up for customisation (https://github.com/WordPress/gutenberg/issues/3218)

> The challenge with the `KeyboardShortcuts` component is that it’s a slave to rendering logic (the shortcut is only bound when the component is rendered), so the shortcuts wouldn’t be registered all at once. That side of things might require a rethink.

> An API that registers the shortcuts along with the descriptions into a store might be one way to go. The `KeyboardShortcuts` component could then access the registered shortcuts from the store using a selector.

**Comment by karmatosed** [comment]
I am removing the 'User Experience (UX)' label as part of a label cleanup. It's not being used anymore consistently so let's try and keep to 'needs design' and 'needs design feedback'. If we find a need for another label we can consider it but having those 2 should cover this.

**Comment by phpbits** [comment]
Additional Slot is needed in my honest opinion. As of now I'm using `registerPlugin` to create my own menu for Markdown keyboard shortcuts. If there's an available option to just hook this to existing Keyboard Shortcuts, I'll just add them there :

![Screen Capture on 2019-05-29 at 18-02-27](https://user-images.githubusercontent.com/3365507/58548537-14324c00-823c-11e9-9ccf-16119d44565a.gif)

**Comment by enriquesanchez** [comment]
This was [discussed during today's Gutenberg design triage meeting in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1579021489111800).

The team agrees that having this functionality would be beneficial. We think it'll be a good idea to start simple, and allow plugin authors to register their shortcuts and have them appear below the default list of shortcuts in the modal. 

If we later find the list gets too long, we can look at implementing an accordion UI or something similar for better organization.

One concern that was raised was the potential for conflicts with default shortcuts. We think that for now, we should look at implementing checks to avoid this.
