### ISSUE TITLE
Inner blocks of a missing parent are lost on save

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/gutenberg#15202]
**Describe the bug**
When a post contains a missing (i.e., unregistered) parent block containing inner blocks, its inner blocks are omitted from the content when the post is next saved.

**To reproduce**
1. Open the block editor to create a new post.
2. Add a columns block with a paragraph in each column.
3. Safe the post as a draft.
4. Open the same post in the Classic Editor and note the presence of the `wp:columns` block and its inner blocks.
5. Rename the opening and closing `<!-- wp:columns -->` delimiters to use the name `wp:columns-missing` and save the draft.
6. Reload the Classic Editor and note the presence of the `wp:columns-missing` block and its inner blocks.
6. Open the post in the block editor and note the missing block notice.
7. Add a paragraph block and save again.
8. Open the post in Classic Editor and note the presence of `wp:columns-missing` block and the absence of inner blocks.

**Expected behavior**
The inner blocks of the `wp:columns-missing` block would be preserved in the post content.

**Comment by aduth** [comment]
Can you explain the difference between this and #13391 ? I see this has been linked to from #15078 which is directly related to the other issue.

**Comment by brandonpayton** [comment]
At first, I thought it was the same issue. IIUC, the main thing about #13391 is that inner blocks cannot be nicely extracted from missing parent blocks.

**Comment by brandonpayton** [comment]
I'm not sure that was clear enough. I believe the difference is that #13391 focuses on getting the blocks out of a missing parent so they can be used apart from the parent, while this issue focuses on content disappearing on save.
