### ISSUE TITLE
Image details edit button doesn't appear in Gutenberg

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1521]
When I add an image block, I'm not able to change the size of the thumbnail, or edit any of the image details (Screen 1). 

If I publish the post in Gutenberg, and go to _Posts > All Posts > Edit post_ I can see an edit button. But even then image sizes are still missing (Screen 2 and Screen 3). 

I'm thinking it should be more like the default image details from Posts, when not connected to Gutenberg (Screen 4)

Is this a known bug or just a feature that hasn't been implemented yet?

![screen 1](https://user-images.githubusercontent.com/3411173/27611038-8730beaa-5b45-11e7-8314-f9bfe3d4f280.png)

-------

![screen 2-3](https://user-images.githubusercontent.com/3411173/27611039-873b497e-5b45-11e7-9c02-651ad5dc5936.png)

-------

![screen 4](https://user-images.githubusercontent.com/3411173/27611040-87417948-5b45-11e7-8ef3-d971f2c26d23.png)

**Comment by youknowriad** [comment]
FWIW, the edit button has already been added in #1459 

For the other options, seems like this is a duplicate to #1052 we should merge the interesting screenshots here into a unique issue I guess.

**Comment by jwold** [comment]
I think we're safe to close this ticket out (the screenshots merely referenced the problem I was trying to define) as it appears the tickets you referenced solve the two problems I was concerned with:

1. Will there be an edit button on images? (Yes, so all is good)
2. Will I be able to edit the image size when I click on the edit button? (Yes, #1052 seems to indicate so).

Thanks!
