### ISSUE TITLE
function gutenberg_reregister_core_block_types() 

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#15237]
Line 36  - if ( ! file_exists( $blocks_dir . $file ) ) {

Shouldn't there be a '/' between $blocks_dir and $file?

**Comment by Soean** [comment]
@AlchemyUnited 
No, because `$blocks_dir` already has a `/` at the end of the string.
Line 14: `$blocks_dir = dirname( __FILE__ ) . '/../build/block-library/blocks/';`
https://github.com/WordPress/gutenberg/blob/master/lib/blocks.php#L14

**Comment by Soean** [comment]
I am closing this issue. Please reopen it, if you still think there is a problem with this line.

**Comment by AlchemyUnited** [comment]
@Soean Aah. Thx. I was reading it as array $key . $value but $key isn't a key but another string. Sorry 'bout that.
