### ISSUE TITLE
Is there a way to add new attributes dynamically? 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#15233]
Hi, 

We know that attributes should be defined initially on registering the block, but is there a way to insert new ones dynamically after the block did mount? 

could we use setAttributes to do that at any time? 

Thanks!

**Comment by swissspidy** [comment]
`setAttributes()` just sets an attribute, but for that it needs to be in the list of valid/allowed attributes first.

There's plenty of [filters](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/) that allow you to modify the list of valid attributes for a block type. 

I have successfully used the `blocks.registerBlockType` and `blocks.getBlockAttributes` filters in the past for that.
