### ISSUE TITLE
Preview does not show updated content on previously published post

### ISSUE THREAD

**Issue by loratov** [WordPress/gutenberg#15234]
**Describe the bug**
The preview does not display content that has changed in the editor for previously published posts

**To reproduce**
1. Go to Posts
2. Click Add New Post
3. Write text in editor
4. Publish Post
5. Refresh admin
6. Edit text content in edotir
7. Click Preview
8. The preview does not have the updated text

**Expected behavior**
The preview should show the changes that have been made to the editor so people can see the changes before they click update

**Screenshots**
![Edit Post ‹ Sisense — WordPress (1)](https://user-images.githubusercontent.com/37795755/56860254-2a2ec180-699d-11e9-9264-881cade3ffd2.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 
 - Version 73.0.3683.103

**Smartphone (please complete the following information):**

**Additional context**
- Gutenberg 5.1.1

**Comment by nerrad** [comment]
Hi there - thanks for taking the time to report your issue here1

I followed your exact testing steps (thanks for that!) and was unable to reproduce the issue you experienced.  One thing that may be happening in your case is that you have opened a preview tab, made a change in the edited content, reloaded the preview tab and expected the change to appear there.  Changes won't appear in the preview tab until they have persisted to the db (either via clicking the "Update" button, clicking the "preview" button, or waiting for autosave to kick in.

I'm going to mark this as invalid for now but if you have any additional information to add that might help us with reproducing please feel free to post it!
