### ISSUE TITLE
Block Component does not render after reorder (arrows or dragdrop)

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#15243]
**Describe the bug**
When reordering a block, either via the arrow buttons or using dragdrop, the `blockType.edit()` function is not triggered.

On one hand this makes sense, because the component's props have not changed, however, this causes issues with JS libraries (such as tinymce) because the DOM element have changed.

Is it possible for Gutenberg to call `this.forceUpdate()` (or something similar) on the block components that have been re-ordered so that 3rd-party developers can "re-initialize" JS instances such as tinymce?

**Additional thoughts**
I'm confident this change will not cause any performance related issues, as the block's "selected" prop changes so often - which triggers the`blockType.edit()` function each time.

**Comment by nerrad** [comment]
Hey!  Will you provide a use-case that exposes this issue for you?  I know  you mentioned tinymce needing to be initialized when a DOM element has changed,  however having a concrete example will help for further work on this.

**Comment by elliotcondon** [comment]
Hi @nerrad 

Sure thing. Over at ACF, we are working on a [PHP framework](https://www.advancedcustomfields.com/resources/blocks/) for connecting custom fields and blocks. 

One of our field types is the WYSIWYG field which implements the tinymce library. We also offer other field types which use various JS libraries such as Select2.

Here is a short video demonstrating the issue. 

![NeSZrplE0A](https://user-images.githubusercontent.com/2296425/56942369-a8d25d00-6b5d-11e9-9b12-8d8fcacae2aa.gif)
[Link to video](http://recordit.co/NeSZrplE0A)

**Notes**
✅ tinymce work fine across multiple "render" calls when "align" setting is changed.
❌ tinymce breaks when the DOM is moved via the up/down arrows.
✅ tinymce is able to reinitialize when triggering "render" again by changing the "preview/edit" mode.

It is worth mentioning that this issue is only with the "up/down" arrows, not sortable. We offer compatibility with **sortable** by hooking into the sortstart/sortend events.

**Comment by gziolo** [comment]
> Is it possible for Gutenberg to call `this.forceUpdate()` (or something similar) on the block components that have been re-ordered so that 3rd-party developers can "re-initialize" JS instances such as tinymce?

With blocks that contain nested blocks or lots of DOM nodes, this might have some performance considerations. It's worth emphasizing that is not necessary to re-render blocks when changing their order in the case of all core blocks. This is all handled by React behind the scenes with its diff algorithm and virtual DOM. This is something that can be overridden using one of the filters like `editor.BlockEdit` and two selectors: one which returns the currently selected block and one which returns blocks order.

**Comment by elliotcondon** [comment]
Hi @gziolo, thanks for the reply.

> With blocks that contain nested blocks or lots of DOM nodes, this might have some performance considerations.

Is this any different to hovering over a block?

> This is something that can be overridden using one of the filters like editor.BlockEdit and two selectors: one which returns the currently selected block and one which returns blocks order.

I'm not sure that creating higher order components is the best way to approach this. This could create potential issues with future updates/changes.

If I was to investigate this, how would the `editor.BlockEdit` filter allow us to detect a change in block order as described in the original topic?

**Comment by youknowriad** [comment]
> If I was to investigate this, how would the editor.BlockEdit filter allow us to detect a change in block order as described in the original topic?

You coud use `withSelect` to fetch the block index `getBlockIndex` and just the fact of including this as a prop will rerender the block itself.

Also please note that we don't use this repository for technical help requests. They have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
