### ISSUE TITLE
Transform multiple articles to Gutenberg

### ISSUE THREAD

**Issue by pwartbichler** [WordPress/gutenberg#15245]
Hello,

we have several thousand articles and would like to save ourselves the trouble of manually converting them all to Gutenberg. Is there a way? 

Thanks for your help!

**Comment by Soean** [comment]
Hey,
this is not possible at the moment.

>At the moment such a function does not exist. Mainly because block types are only registered in JavaScript and on the server you have no idea which blocks exist.
However, server-side block registration is planned as per #2751. Once that is done, we will be able to provide such a function for developers.

>If you're adventurous, I think you can still use a node script running jsdom and use the wp.blocks.rawHandler function. Otherwise, you should wait for phase 2 work around server side awareness of blocks #2751

See #13163
