### ISSUE TITLE
Hyperlink - use the url in clipboard

### ISSUE THREAD

**Issue by Seenivasanseeni** [WordPress/gutenberg#15258]
Whenever you try to insert a URL as a hyperlink in an article, it happens that I have my URL in my clipboard itself. It will be a great feature if on selecting "insert hyperlink", it automatically fills up with URL if there is any on the clipboard.

**Comment by swissspidy** [comment]
Note that you can just select a phrase and paste your URL and the editor will automatically create a link for you. That‘s even faster :-)

**Comment by Seenivasanseeni** [comment]
Yep. But still above said feature can be useful. Correct me if I'm wrong.

**Comment by ellatrix** [comment]
You cannot just access the clipboard with JS. That would be a security issue. The user needs to paste it.
