### ISSUE TITLE
Content is lost if you remove P tags

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#1526]
If the text content 'loses' it's paragraph tags, it gets 'eaten' by Gutenberg.

So for example, if you have this, everything works:

```
<!-- wp:core/text -->
<p>I like that I can dance.</p>
<!-- /wp:core/text -->
```

Looks like this:

<img width="605" alt="screen shot 2017-06-27 at 27 jun - 7 41 27 pm" src="https://user-images.githubusercontent.com/807903/27618348-aec00c3e-5b70-11e7-9b52-9d29874b8485.png">

But if you have **this** it won't:

```
<!-- wp:core/text -->
This is a test post. I'm going to do something dumb. Hang on.
<!-- /wp:core/text -->
```

That looks like this:

<img width="623" alt="screen shot 2017-06-27 at 27 jun - 7 40 02 pm" src="https://user-images.githubusercontent.com/807903/27618351-b9eb0a78-5b70-11e7-8d57-1aa5c9b96e4d.png">

It basically created an EMPTY text block. If I go into the text editor, it looks like this:

```
<!-- wp:core/text -->
<p></p>
<!-- /wp:core/text -->
```

The easiest way to reproduce would be this:

1. Make a post in Gutenberg
2. Edit the post in the visual/tinyMCE editor for any reason (in my case, editing tags and adding meta box content)
3. Go back to Gutenberg

All your text will be lost. Sad panda. 🐼 

NB: You must save your content in the visual/TinyMCE editor. Because it strips p tags.

My recommendation would be to somehow force-add them back in? I know it should never happen in the future, but if someone goes into the text editor for any reason and adds content _not knowing_ that they have to have p tags, they'll lose content.

**Comment by youknowriad** [comment]
I think we can consider this as closed by #1929 because removing the `p` tags will mark the block as corrupted and it will be protected from any gutenberg change.
