### ISSUE TITLE
Reusable block: Add option to export / import with attachments

### ISSUE THREAD

**Issue by ivan-borisov** [WordPress/gutenberg#15266]
**Is your feature request related to a problem? Please describe.**
Now is possible only export / import reusable block structure, without images related to it

**Describe the solution you'd like**
It will be good if have option to export reusable block with images. For example, I want to create many sections or whole pages with background images, slider images and reuse them on new site.

**Comment by noisysocks** [comment]
Duplicate of https://github.com/WordPress/gutenberg/issues/10050.
