### ISSUE TITLE
Focus Issues with Post Title 

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#1527]
On Safari/MacOS (latest of both) if I try to click on the title of a post, it doesn't always work.

This is consistent for me, and I have to click out of my content box, into another one, and THEN I can go into edit the post title. Which is the only way I can find to get into the post settings (like schedule etc) so ... kinda frustrating.

Here's a video of it happening: https://cloudup.com/cHXHLjOtgO8

**Comment by afercia** [comment]
I was able to reproduce this also with the demo content post. I've also managed to crash Safari, just clicking on the various blocks:

![screen shot 2017-06-28 at 12 08 40](https://user-images.githubusercontent.com/1682452/27632193-4af180da-5bfb-11e7-8d20-71300a8313ea.png)

Haven't noticed errors in the console. Sorry, I know this doesn't help so much.

**Comment by karmatosed** [comment]
I am unable to replicate this using latest version. For now, going to close as I think this has been fixed - happy to open if it's not.
