### ISSUE TITLE
Page content is an invisible Tab stop

### ISSUE THREAD

**Issue by karlgroves** [WordPress/gutenberg#15285]
Page content is an invisible Tab stop

-   **Severity:** Medium
-   **Affected Populations:**
    -   Blind
    -   Low-Vision
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Edit Media

#### Issue description

On the Edit Media page, the main content element is an invisible Tab
stop, because it's in the Tab order but does not show focus.

This is potentially confusing for sighted keyboard users, since it will
make it appear as though no item has focus, or make it unclear as to
where the focus position is. Screen reader users will know they are on
the main area due to the `aria-label`, but it may be unclear to them
why the whole area is focusable.

##### Issue Code

```
    <div id="wpbody-content" aria-label="Main content" tabindex="0" style="overflow: hidden;">...</div>





    a, div {


        outline: 0;


    }


    #wpbody-content {


        ...


        overflow: visible !important;


    }
```

#### Remediation Guidance

If the `tabindex` is being used to allow the main content area to be a
working destination for skip links, then use `tabindex="-1"`
instead. This will allow the element to be focusable without placing it
in the Tab order.

This change will not affect keyboard users' ability to scroll the page
when the element has focus.

##### Recommended Code

```
    <div id="wpbody-content" aria-label="Main content" tabindex="-1" style="overflow: hidden;">...</div>
```

#### Relevant standards

-   [2.1.1 Keyboard
    (Level A)](https://www.w3.org/TR/WCAG20/#keyboard-operation-keyboard-operable)
-   [2.4.7 Focus Visible (Level
    AA)](https://www.w3.org/TR/WCAG20/#navigation-mechanisms-focus-visible)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-83 in Tenon's report

**Comment by afercia** [comment]
This applied to all the WordPress admin pages. As far as I can tell, it was fixed in WordPress 5.1 see https://core.trac.wordpress.org/changeset/44639. 

Please do feel free to reopen the issue if still relevant on latest WordPress.
