### ISSUE TITLE
Flickr URL not working properly for embedding photos within content

### ISSUE THREAD

**Issue by miyanialkesh7** [WordPress/gutenberg#1530]
I tried gutenberg to check possibilities with editing in backend.

But, when I was checking "Flickr URL" block then noticed that it is not working properly.

![screenshot_18](https://user-images.githubusercontent.com/4271344/27623138-a66ceb96-5bf8-11e7-9238-5b341393d5bc.png)

I tried number of flickr URLs but I am not getting anything with that block.

**Comment by swissspidy** [comment]
On Flickr, people can prevent downloading of their pictures. Perhaps that disallows oEmbed as well? Which URLs did you try?

I just embedded https://www.flickr.com/photos/rarst/35264958422/ locally without any problems.

**Comment by mtias** [comment]
Closing as lacking more information. Feel free to comment again or open another issue.

**Comment by miyanialkesh7** [comment]
I will recheck that issue again today or within 2 days and if possible then
capture video as we for more details.

Thanks for giving update to me on my ticket! 👍
