### ISSUE TITLE
Reading and focus order do not match visual order

### ISSUE THREAD

**Issue by karlgroves** [WordPress/gutenberg#15315]
Reading and focus order do not match visual order

-   **Severity:** Medium
-   **Affected Populations:**
    -   Blind
    -   Low-Vision
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Edit Media

#### Issue description

On the Edit Media page, the keyboard focus order and the visual reading
order are presented in a zig-zag pattern.

Users who are not using browser zoom can reach an option to show more or
fewer columns:

1. If users select content to appear in a single column (which still
produces two columns visually), content at the top is first, then comes
content on the right (Scale and Crop sections), then content back to the
left (the actual image and editing buttons), and finally content
underneath both columns (metadata).

2. If users select content to appear in two columns (which produces
three columns visually), content at the top is first, then comes a
column in the middle ("Scale" and "Crop" sections), then the column
in the left (the actual image and editing buttons), and then the content
at the bottom (the default metadata). After some of the content at the
bottom, the "Save" section is on the far right, and then if the user
added more boxes, these are last and visually placed after the default
metadata content.

Keyboard users benefit from a logical focus order which is consistent
with the reading order. Users who have a cognitive disability and have
difficulty reading may also be confused by an unexpected or illogical
focus order.

#### Remediation Guidance

Either change the visible layout with CSS to make the visual order match
the content order, or re-order the content in the DOM to match the
visual order.

#### Relevant standards

-   [1.3.2 Meaningful Sequence
    (Level A)](https://www.w3.org/TR/WCAG20/#content-structure-separation-sequence)
-   [2.4.3 Focus Order
    (Level A)](https://www.w3.org/TR/WCAG20/#navigation-mechanisms-focus-order)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-82 in Tenon's report

**Comment by melchoyce** [comment]
Screenshots from full report:

![image](https://user-images.githubusercontent.com/2846578/57182794-690abe80-6e58-11e9-8ea5-10883306a61f.png)
![image](https://user-images.githubusercontent.com/2846578/57182795-6f009f80-6e58-11e9-8165-1cdd43fd62df.png)

Note: This is a core Media issue, not Gutenberg, so we'll need to move it to Trac.

**Comment by anevins12** [comment]
Moved to Trac https://core.trac.wordpress.org/ticket/47136

**Comment by afercia** [comment]
Closing as moved to Trac.

**Comment by afercia** [comment]
Quick update: this was fixed in https://core.trac.wordpress.org/changeset/48265. See the related ticket: https://core.trac.wordpress.org/ticket/47136.

Follow-up ticket for a major redesign of the Image Editor: https://core.trac.wordpress.org/ticket/50523
