### ISSUE TITLE
Sidebar should remain closed on resizing the screen

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1535]
If I make my screen smaller I get this and lose content area:

![2017-06-28 at 11 13](https://user-images.githubusercontent.com/253067/27632207-f2158af4-5bf2-11e7-879c-1dd82f9e5a7e.png)

Version: plugin from directory.

**Comment by swissspidy** [comment]
Noticed the same. The post settings can be closed though and you can continue writing. Although the UX isn't ideal.

There are few more issues with the responsive design though, see #1514 for example. Perhaps we can fix some of them at once?

**Comment by youknowriad** [comment]
If you refresh the page, the settings will be closed by default. Thus, I don't think this is a bug because regular users don't resize their browsers to check responsiveness.

**Comment by swissspidy** [comment]
What if you switch your tablet from portrait to landscape mode, move the browser window from one screen to another (smaller) one, or just resize it because your 27-inch iMac screen is just too large to have fullscreen windows?

**Comment by mtias** [comment]
We probably need to create the concept of layout-focus if we want to improve this (I added a tool like this to calypso early on)—layout focus keeps track of what part of the layout is the primary focus at any given point. If you don't open the sidebar manually, then focus should be set to `content`, which would mean on mobile breakpoints it can be hidden. On desktop, even if sidebar is not focused it can be opened (initial load).

**Comment by karmatosed** [comment]
@youknowriad I actually disagree, mainly because I discovered this because I use a 13" macbook and the not having a full size window can easily create this issue.

**Comment by karmatosed** [comment]
A simple step for this would be to avoid this:

![m1](https://user-images.githubusercontent.com/253067/32340465-972c3c82-bff2-11e7-81d0-26c335e671bb.png)

Having as default settings closed (on first load):

![m2](https://user-images.githubusercontent.com/253067/32340481-a11428ea-bff2-11e7-816d-201e25445539.png)
