### ISSUE TITLE
Plain text appears to be a link

### ISSUE THREAD

**Issue by karlgroves** [WordPress/gutenberg#15358]
Plain text appears to be a link

-   **Severity:** Medium
-   **Affected Populations:**
    -   Low-Vision
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Publish and Unpublish

#### Issue description

There are three text elements within the Publish panel (the values for
"Visibility", "Publish", and "Suggestion") which are styled to
appear as links, but do not function as links. The entire containing
element is a button to open or close the expanding region, while the
text elements themselves have no direct function.

This may be confusing for users, since the expectation conveyed by their
appearance is that these elements are links.

##### Issue Code

```
    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


       ...


       Visibility:


       <span class="editor-post-publish-panel__link">Public</span>


    </button>





    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


        ...


        Publish:


        <span class="editor-post-publish-panel__link">Jan 18, 2019 4:40 pm</span>


    </button>





    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


       ...


        Suggestion:


        <span class="editor-post-publish-panel__link">Add tags</span></button>





    /* CSS */


    .editor-post-publish-panel__link {


        color: #007fac;


        text-decoration: underline;


        ...


    }
```

#### Remediation Guidance

Remove the `text-decoration` and `color` from these elements so that
they don't look like links.

##### Recommended Code

```
    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


       ...


       Visibility:


       <span class="editor-post-publish-panel__link">Public</span>


    </button>





    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


        ...


        Publish:


        <span class="editor-post-publish-panel__link">Jan 18, 2019 4:40 pm</span>


    </button>





    <button class="components-button components-panel__body-toggle" aria-expanded="false" type="button">


       ...


        Suggestion:


        <span class="editor-post-publish-panel__link">Add tags</span></button>





    /* CSS */


    .editor-post-publish-panel__link {


        ...


    }


```

#### Relevant standards

-   [1.3.3 Sensory Characteristics
    (Level A)](https://www.w3.org/TR/WCAG20/#content-structure-separation-understanding)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-13 in Tenon's report

**Comment by afercia** [comment]
Screenshot:

<img width="311" alt="Screenshot 2019-05-02 at 16 23 18" src="https://user-images.githubusercontent.com/1682452/57082245-a3f4e100-6cf6-11e9-844a-a0f847c7bd0a.png">

As these are not links and they're already within the expandable panel headers with the "chevron" icon,  not sure why they should look like links. +1 for removing the link styling.

**Comment by melchoyce** [comment]
They're probably styled as links to match the sidebar:

![image](https://user-images.githubusercontent.com/2846578/57186853-346c2680-6e9b-11e9-92f3-3794175c1a02.png)

@jasmussen @kjellr Any opinions here?

**Comment by jasmussen** [comment]
Probably fine to just make them text. They still appear as "variables", and the chevron does indicate clickability. 👍 👍

**Comment by afercia** [comment]
To clarify: this issue is about the panels in the pre-publish sidebar (see also page 287 of the full technical report).

It's the same `Panel` component used in the Document (screenshot on the left) and Block sidebar, not sure why the Panels used in the pre-publish sidebar should contain text styled as links (screenshot on the right):

<img width="605" alt="Screenshot 2019-05-06 at 15 03 27" src="https://user-images.githubusercontent.com/1682452/57227395-98b0f680-7011-11e9-9854-f4deb0344e1d.png">
