### ISSUE TITLE
Weird RichText span vs div bug

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#15360]
**Describe the bug**
We have a Richtext component that, on delete, whenever the cursor reached the first letter of text, would not delete that letter and then would refuse to send any more onChange events whenever the tagName was set to "span". Visually the first letter will be deleted, however the first letter remains in attributes as you can see in our inspector. However on changing the tagName to "div", the input started working again like normal, meaning it would delete all text in the block attributes. Not sure why there is a difference between span and tag.

Mac Os 10.14.4
Chrome 74.0.3729.108
WordPress 5.1.1

Here is the code and some gifs to show the problem.

### With span as tagName
![With span as tagname](https://user-images.githubusercontent.com/11747187/56992225-99581180-6b67-11e9-8cc0-72418f7e60e2.gif)

### With div as tagname
![With div as tagname](https://user-images.githubusercontent.com/11747187/56992226-99581180-6b67-11e9-936d-0b70746e469c.gif)

### Our Code
```js
import sanitizeHtml from 'sanitize-html'
import { allTheThings } from '../../../util/sanitizers'
import { RichText } from '../../imports'

const { pure } = wp.compose

const Editable = pure(({ title, set }) => {

  function handleTitleChange(e) { 
    set({ title: sanitizeHtml(e, allTheThings) })
  }

  return (
    <RichText
      formattingControls={ [] }
      multiline={ false }
      tagName="div"
      value={ title }
      onChange={ handleTitleChange }
      className="GB__PreventRichTextCollapse"
      placeholder="Write a title..." />
  )
})

export default pure(({ title, context, editing, set }) => {
  return context === 'card'
    ? (
      <h1 className="Hero__Title c-whiteFull ff-qm fs-24 fs-32--md m-0 mt-0 mb-8">
        {editing ? <Editable title={title} set={set} /> : title}
      </h1>
    ) : (
      <h1 className="Hero__Title mt-0 mb-16 mx-auto w-18--sm">
        <span className="ff-gb tt-u ls-1 fs-21 fs-32--md fs-40--lg px-16 py-8 px-32--md py-12--md ba-2 b-orange c-whiteFull d-ib">
          {editing ? <Editable title={title} set={set} /> : title}
        </span>
      </h1>
    )
})
```

**Comment by ellatrix** [comment]
`RichText` does not support elements with `display: inline`. The console should log a warning.
