### ISSUE TITLE
When saving a custom post type that doesn't support Authors, users without the "edit_others_posts" will get a JS error

### ISSUE THREAD

**Issue by zaantar** [WordPress/gutenberg#15367]
**Describe the bug**
Please see the issue title for description. Details and possible cause follow below.

**To reproduce**

1. Have a custom post type (let's say "Items") that **doesn't support the Author feature**.
2. Have an user without the "edit_others_posts" capability (let's say "author")
3. Have any metabox displayed on the Edit Post page:
    ```
    add_action( 'add_meta_boxes', function() {
        add_meta_box( 'test', 'my test metabox', function() {
            echo '<div>example metabox content</div>';
        } );
    });
    ```
3. Login as Author and try to create a new Item. Click on "Save draft" (for example).
4. Observe an error in the browser console:
    - `api-fetch.js?ver=2.2.8:673 POST http://localhost/wp-admin/post.php?post=11&action=edit&meta-box-loader=1&_wpnonce=0076082665&_locale=user 500 (Internal Server Error)`
    - `/wp-admin/post.php?post=11&action=edit:1 Uncaught (in promise) Response {type: "basic", url: "http://localhost/wp-admin/post.php?post=11&action=…eta-box-loader=1&_wpnonce=0076082665&_locale=user", redirected: false, status: 500, ok: false, …}`

    ![image](https://user-images.githubusercontent.com/6987234/57012920-08d20d80-6c09-11e9-95a6-cc7f27cc06c1.png)
    [localhost-1556704840840.log](https://github.com/WordPress/gutenberg/files/3134210/localhost-1556704840840.log)
5. Also note that the metabox refreshing doesn't finish, the spinner in its header keeps spinning and the post is still acting as "Saving..."

**Expected behavior**
No bugs or errors :)

**Desktop:** (however, this is probably irrelevant)
 - OS: elementaryOS (based on Ubuntu 14.04)
 - Browser: Chromium
 - Version: `Chromium 65.0.3325.181 Built on Ubuntu , running on elementary OS 0.3.2`

**Additional context**
- WordPress 5.1.1
- Adding notes from my research (please note that I am not familiar with the Gutenberg code): 

After saving a post, the block editor updates metaboxes through AJAX calls, and during this reloading, a post saving action is also being performed (or so it seems).

On [wp-admin/includes/post.php:74](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/post.php#L74), there's this condition - if the user is different from the post author, verify that they can edit other's posts:

```php
	if ( isset( $post_data['user_ID'] ) && ( $post_data['post_author'] != $post_data['user_ID'] )
		&& ! current_user_can( $ptype->cap->edit_others_posts ) ) {
            // ... fail ...
```

If this fails, the request produces an error in the browser because the call ends sooner than the desired metabox can be loaded.

Now, this started happening for users without the `edit_others_posts` role in the block editor, **if the post type doesn't have the Author feature enabled.**

In other situations, everything is fine (the post author ID equals to the `user_ID` value, even if the post type officially doesn't support post authors), but in this very scenario, `$post_data['post_author'] === 0` (**because `$_POST['post_author'] === 'undefined'`**) and as a result, the `edit_others_posts` capability is  required...

**Comment by youknowriad** [comment]
closed by #15375
