### ISSUE TITLE
Calendar for an article in draft

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/gutenberg#15369]
**Describe the bug**
It is impossible to put on the calendar, for a draft article, the option to publish it now, as on other articles.

**To reproduce**
1. Write an article
2. Put it in draft
3. Go back to the edition of this article
4. Click on the calendar "Posted ..."

**Desktop (please complete the following information):**
  - OS: Windows 10
  - Firefox Browser
  - Version 66.0.3

**Additional context**
Gutenberg on version 5.1.1 of WordPress

**Comment by youknowriad** [comment]
Can you clarify a little bit more, I'm having no issues with the calendar. Some screenshots might help?

**Comment by ValentinGratz** [comment]
You have the article that is in draft with the date of last modification
![visu 1](https://user-images.githubusercontent.com/39189263/57602164-b07f0200-755e-11e9-9e27-1137959bb3be.png)

On the article, here is the date on which the article would be published (when I made it in draft), so a previous date:
![visu 2](https://user-images.githubusercontent.com/39189263/57602527-a14c8400-755f-11e9-96e6-8c20ee0d4f05.png)

When I click on the date to modify and indicate "Publish now", this is not possible, it only puts me the calendar to schedule its publication.
![visu 3](https://user-images.githubusercontent.com/39189263/57602581-cccf6e80-755f-11e9-806e-70fa69bff634.png)

**Comment by youknowriad** [comment]
Oh Thanks for the clarifications @ValentinGratz 

I guess this is a duplicate of #12048
