### ISSUE TITLE
Paragraph layout and line break

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/gutenberg#15368]
When you go to the line, I realize that it creates a new paragraph. But what if I want to avoid leaving a blank, and just go back to the line.

To show you an example:

**Paste:**
I am writing an article with WordPress gutenberg, then I will ...
The second paragraph.

**Currently on Gutenberg:**

I am writing a paragraph.

I write the second paragraph, while I simply ask to go to the line without passing.

**Comment by ktmn** [comment]
`Shift + Enter` goes to a new line in the same paragraph
