### ISSUE TITLE
Import setAttributes() method in a separated module 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#15374]
Hi, 

Is there a possibility to import the setAttributes() method in a separated module, I mean in what package we can find that method outside the props of edit and save functions 

Thanks!

**Comment by swissspidy** [comment]
`setAttributes` effectively calls `dispatch( 'core/block-editor' ).updateBlockAttributes()`, so you can just use that reducer to update a block's attribute.

**Comment by DevinWalker** [comment]
☝️  helpful info, thanks!
