### ISSUE TITLE
Gutenberg Text Settings Rules not specific enough

### ISSUE THREAD

**Issue by coreyadkins** [WordPress/gutenberg#15379]
Running into an unexpected CSS issue with Gutenberg that I wanted to ask the noble community about.

Basically I have a client who wants to take advantage of the Text Settings options in the Block Editor to be able to set individual font-sizes for paragraphs as it is built to do.

However any CSS rules getting applied from that on posts are getting overwritten by the not-very-specific rule `.entry-content p`, because Gutenberg only applies these styles as a single class selector, like `.has-small-font-size`.

Is there a way I can manually increase the specificity of the CSS selectors that Text Settings applies? If a solution for this does not already exist, it seems like a pretty common thing that will come up for users. Was honestly surprised I was unable to easily find an answer to this issue with a bit of searching.

Thanks in advance for any help offered.

**Comment by swissspidy** [comment]
Where is `.entry-content p` coming from? Your theme?

**Comment by coreyadkins** [comment]
Sorry for the delay in response @swissspidy. Yes, that's coming from the theme. The point I was trying to make with it was that it's a really non-specific rule. I have to imagine I'm not the only one encountering an issue with applying the large and small text settings Gutenberg provides getting overwritten by the cascade, as an element needs to basically be clean of any font-size declarations in the stylesheet for them to apply, which seems really impractical. Which is why I wanted to check in to see if I'm missing something. Thanks for your help!

**Comment by youknowriad** [comment]
yes, these are not very specific on purpose but these are also defined by themes. Gutenberg has dome defaults but if you want to define your own font sizes with your own stylesheets instead of Gutenberg's default font sizes, you can do so. See this link for more details https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-font-sizes
