### ISSUE TITLE
Link popover does not scroll with page

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15371]
**Describe the bug**

Introduced by #14938. Cc @aduth.
Noticed while testing #15035.

When the link popover is visible, and you scroll the page, the link popover doesn't move. That's because it have a fixed position. Previously the popover element would be positioned in the RichText wrapper element, and would be positioned relative to that.

Suggested fix: add an option to `Popover` to allow inline positioning with relative coordinates.

**Comment by aduth** [comment]
> Suggested fix: add an option to `Popover` to allow inline positioning with relative coordinates.

A challenge to consider here is that `Popover` is implementing using portals (i.e. non-relative) in part to avoid dealing with CSS style cascade effects. Reintroducing relative positioning reintroduces this potential conflict.

**Comment by ellatrix** [comment]
@aduth Previously also used `Popover`, but wrapped in an extra relatively positioned `div`. Not sure how exactly it worked then. :)

**Comment by aduth** [comment]
> @aduth Previously also used `Popover`, but wrapped in an extra relatively positioned `div`. Not sure how exactly it worked then. :)

Did GitHub eat your markup between words "Previously" and "also" ? Unsure if your comment was meant to include a reference to a specific example.

If I recall correctly, Popover _was_ originally positioned relatively, and then refactored to be separate in the DOM when Slot/Fill was first introduced. Maybe that's the previous implementation relied upon.

Actually, just now looking at the implementation, worth pointing out that `Popover` _does_ render in-place if there is no Slot context for it to render in to:

https://github.com/WordPress/gutenberg/blob/c0ac81a6465e15125f1b54ee2b1bf63076d21e62/packages/components/src/popover/index.js#L393-L397

(Unrelated: cc @jorgefilipecosta you had mentioned some issues with Popover in Widgets screen, I wonder if this might be the cause)

**Comment by jorgefilipecosta** [comment]
> (Unrelated: cc @jorgefilipecosta you had mentioned some issues with Popover in Widgets screen, I wonder if this might be the cause)

Thank you for bringing this up, I think the popovers problems in the widgets screen were related to not having a working PopoverProvider there.

**Comment by ellatrix** [comment]
Did GitHub eat your markup between words "Previously" and "also" ? Unsure if your comment was meant to include a reference to a specific example.

Sorry, corrected. :) Just meant to refer to the component affected.

What I meant is that, previously the link container also used Popover, but somehow it was placed relatively to the rich text container. I'm not sure how this was done exactly.

**Comment by ellatrix** [comment]
Fixed by #17867.
