### ISSUE TITLE
Keyboard shortcuts use different colors.

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15387]
Splitting this out from https://github.com/WordPress/gutenberg/issues/10576#issuecomment-473382160

I'm not wrong, the block "more" menu shortcuts (on the left) and the ones in the main "more" menu (on the right) use two different colors: `#555d66` vs. `#40464d` both with 0.84 opacity set on the wrapper element.

<img width="526" alt="Screenshot 2019-03-15 at 18 36 34" src="https://user-images.githubusercontent.com/1682452/54451453-2c252400-4753-11e9-8a29-b489100d36e6.png">

@jasmussen any reason why they're using different colors? Of course, I'd prefer the darker `#40464d` for both 🙂 

Also: I'm not sure why many elements in the editor use CSS opacity, which makes things difficult when calculating color contrast. If there's the need for some transparency, I'd tend to think single elements should use `rgba()` colors, not opacity set on the container. @jasmussen can you shed some light on this? Is there any need to use opacity in these two specific cases?

**Comment by joyously** [comment]
Did you test how this affects dark mode?
I use opacity instead of rgba so that it works with all colors. Perhaps that was the reasoning?

**Comment by afercia** [comment]
Dark mode as in: a dark theme or something else? I don't believe dark themes change the Gutenberg UI.

**Comment by joyously** [comment]
OK. I meant whatever you get when the theme uses `add_theme_support( 'dark-editor-style' )`.
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#dark-backgrounds

**Comment by afercia** [comment]
That only changes the Editor _content_ area and the blocks backgrounds. Not the toolbars and menus. Example:

![Screenshot 2019-05-21 at 20 16 41](https://user-images.githubusercontent.com/1682452/58120413-7cae7700-7c05-11e9-9c1e-f3aaa6e91b5b.png)

The "Gutenberg" and "Gutenberg Dark" test themes allow to easily test. @kjellr would it be possible to make these two themes more widely known and available for download so that designers and testers can test autonomously?

**Comment by kjellr** [comment]
> The "Gutenberg" and "Gutenberg Dark" test themes allow to easily test. @kjellr would it be possible to make these two themes more widely known and available for download so that designers and testers can test autonomously?

Hey @afercia! Yes, I'd love to make these themes easier to access. They're key to testing, now that (I believe) all the default themes have some sort of editor style included. 

To start, there's an issue that aims to get the Gutenberg Starter theme included with this repository's Docker environment by default: https://github.com/WordPress/gutenberg/issues/14454. That would make the theme much more widely available for people using this repository. As for the dark mode, I should be able to actually just build that in as a theme option for the Starter theme so people only have to install one theme. I'll get a PR going for that later this week.

**Comment by joyously** [comment]
Circling back around, I think what was in my mind was the icons that show on hover at the bottom of the content. There is no background color on those, so they are not always visible.
And, it would be best to include another test setup for a theme that allows color choices but does not call the add_theme_support for dark mode, because that is the main case for legacy themes.
