### ISSUE TITLE
Allow 1 column in Columns or a Section/Row layout element

### ISSUE THREAD

**Issue by koszeggy** [WordPress/gutenberg#15390]
**Is your feature request related to a problem? Please describe.**
Columns block can be used perfectly for a section, which shares the same background color/image, for example. Unfortunately it must have at least two columns now. Of course, Columns does not have background settings now but I always set styles by CSS classes, which I can set in the Advanced settings.

Now a possible workaround is wrapping the blocks of the section into a `<div>` and converting the whole group to HTML but then the grouped content cannot be edited in the designer anymore.

**Describe the solution you'd like**
The simplest solution would be to allow 1 column. Some builders such as the Page Builder Sandwich have this single column layout approach as well.

**Describe alternatives you've considered**
If you find a single columned Columns confusing you could introduce a Row or Section element
allowing the customization of its background image/color/etc. as well as stacking inner blocks inside it.

**Comment by swissspidy** [comment]
I thought there already is a section/container block by now? Which version of WordPress and Gutenberg are you using?

**Comment by koszeggy** [comment]
Latest WP (5.5.1) with the built-in default Gutenberg.
But after all there are a lot of plugins, which make this available (eg. Kadence Blocks or Gutenberg Blocks Ultimate)
