### ISSUE TITLE
`lint-js` task lints `build/` directory

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15407]
**Describe the bug**

Running the JS linter will lint the `build/` folder, resulting in hundreds of errors because it's minified, etc.

**Expected behavior**

The `build/` folder should be ignored by the linter config.

**Comment by swissspidy** [comment]
In Gutenberg or did you mean in general? The `.eslintignore` in Gutenberg excludes build directories already, but I don't think there's any such default configuration in the scripts package.

**Comment by iandunn** [comment]
Not with Gutenberg, but in general, when using `wp-scripts` to build blocks or other plugins that use `wp.element`, `wp.component`, etc. [For example](https://github.com/iandunn/quick-navigation-interface/tree/4ff42c2).

**Comment by gziolo** [comment]
I would expect the same issue for lint-css as well.
