### ISSUE TITLE
Fatal error when unlinking words in a link

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15405]
I'm not exactly sure what steps I took to run into this problem in the first place, but it was something similar to this:

1. Write a sentanace
1. Highlight part of it
1. Paste URL to make it a link
1. Try to un-link the last few words via cmd+k, cmd+shift+k, clicking on link icon, etc.

At some point there was a JS error and everything stopped working.

I clicked `Save draft` and reloaded the page, but got a new fatal JS error, and the block can't be rendered.

> This block has encountered an error and cannot be previewed.

> react-dom.min.js?ver=16.6.3:104 TypeError: Cannot read property 'nodeType' of null

<img width="668" alt="Screen Shot 2019-05-02 at 5 02 23 PM" src="https://user-images.githubusercontent.com/484068/57114022-1d430280-6cfc-11e9-9c13-5667d4d47f6d.png">

So, there are three issues:

1) There's some combination of normal user behavior which creates a fatal error
2) The block's content is damaged and can't be recovered
3) There's a fatal error when re-loading the page because of the damaged content

Steps to reproduce issue 3:

1. Add a paragraph block
1. Kebab > Edit as HTML
1. Paste in this:

```html
<p>Rani Molla recently published <em><a href="https://www.vox.com/recode/2019/5/1/18511575/productivity-slack-google-microsoft-facebook">The productivity pit: how Slack is ruining work, and</a></em><a href="https://www.vox.com/recode/2019/5/1/18511575/productivity-slack-google-microsoft-facebook"></a></p>
```

4. Kebab > Edit visually

**Comment by ellatrix** [comment]
I can't reproduce this issue. :/ Would be great to have the unminified log.

**Comment by iandunn** [comment]
I can't reproduce problem 3 under the latest plugin version anymore either, and I haven't encountered problems 1/2 again, so maybe this was fixed by some other change.
