### ISSUE TITLE
Gutenberg change user when publishing content that has been put for review

### ISSUE THREAD

**Issue by Timpetersson** [WordPress/gutenberg#15401]
**Describe the bug**
When a contributer makes a submit for review, and the admin hits the publish butten the username changes to the admins username.

**To reproduce**
1. Submit for review as contributer
2. admin clicks on publish
3. Username changes

**Comment by Timpetersson** [comment]
Username changes to admin that is

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7
Twenty Twenty One
Gutenberg plugin 10.3

I made a post as a Contributor and submitted it for review.
Logged out and in as an admin user.
Published the contributor post.
The frontend and backend both showed the Contributor user name.

I would say that this bug has been fixed, so I will go ahead and close this issue. If I made a mistake then the issue can be reopened.
