### ISSUE TITLE
Video Block: Placeholder should use Oxford comma

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#15408]
**Current placeholder text:**

Drag a video, upload a new one or select a file from your library.

**Proposed placeholder text:**

Drag a video, upload a new one, or select a file from your library.

(Honestly, this whole sentence is kind of bad.)

**Comment by swissspidy** [comment]
That is indeed not an ideal sentence.

Dragging a video === uploading it anyway, so that part is redundant.

**Comment by michelleweber** [comment]
"Drag and drop a video file into this block, or use the buttons select to a file from your computer or media library." ?

**Comment by melchoyce** [comment]
Both of these descriptions leave out the "Insert from URL" button:

![image](https://user-images.githubusercontent.com/2846578/57184378-96af3200-6e6f-11e9-87c2-37f4cab74491.png)

I wonder if "...from your computer/media library" is maybe redundant? Would be be okay to do something more general, since the buttons then provide more context?

> Drag and drop a video file into this block, or use the buttons select to a file instead.

**Comment by michelleweber** [comment]
I dig that.

**Comment by melchoyce** [comment]
Thanks @michelleweber!

**Comment by Soean** [comment]
Changes were made in #16135, so I am closing this issue.
