### ISSUE TITLE
Edit Post: "View Post" link doesn't change when publishing draft

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#15402]
Previously: https://github.com/WordPress/gutenberg/pull/14740#discussion_r280502111

When editing an existing post, a "View Post" link appears in the admin toolbar.

![image](https://user-images.githubusercontent.com/1779930/57096323-fe844200-6ce2-11e9-8743-e59952c91cdb.png)

This link is intended to be automatically updated when the link for the post changes (e.g. changing the permalink and updating a published post):

https://github.com/WordPress/gutenberg/blob/920b8f03debfef626587ddb5c758877bc44eb11c/packages/edit-post/src/store/actions.js#L297-L310

However, the above implementation relies on a selector which is effective only for published posts, not for drafts:

https://github.com/WordPress/gutenberg/blob/920b8f03debfef626587ddb5c758877bc44eb11c/packages/edit-post/src/store/constants.js#L11

The link for a draft uses a different ID `wp-admin-bar-preview`.

**Steps to Reproduce:**

1. Navigate to Posts > Add New
2. Enter a title
3. Click "Save Draft"
4. Reload
5. (Optional) Take note of the link for "View Post"
6. Publish the post
7. Note that the link for "View Post" does not change (still links to preview by draft ID)

**Needs More Information:**

The links in the admin bar are dynamically generated. It's not entirely clear to follow which possible selector values must be accounted for.

https://github.com/WordPress/wordpress-develop/blob/5640763da953c28033e9f285c7c2a1da4c613aa3/src/wp-includes/class-wp-admin-bar.php#L464

**Comment by obenland** [comment]
I followed the testing instructions and was unable to reproduce the bug.
#15444 adds an additional selector there `VIEW_AS_PREVIEW_LINK_SELECTOR`, which fixed this issue.
