### ISSUE TITLE
Dependency extraction plugin should accept output filenames that are functions

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#15410]
**Describe the bug**
When using `@wordpress/dependency-extraction-webpack-plugin` in a custom plugin, the build process fails and returns the following error:

```TypeError: outputFilename.replace is not a function```

if the `output` object of a `webpack.config.js` `exports` uses a _function_ in the `filename` property:

```
module.exports = [
  {
    ...config,
    entry: { ... },
    output: {
      path: path.resolve( __dirname, './assets/dist/' ),
      filename: ( chunkData ) => `js/${ chunkData.chunk.name }.min.js`,
    }
  }
];
```

According to webpack docs, however, [output.filename can either be a _string_ or a _function_](https://webpack.js.org/configuration/output/#outputfilename).

**To reproduce**
1. Create a webpack.config.js that uses `WordPressExternalDependenciesPlugin`, as [described in its docs](https://github.com/WordPress/gutenberg/tree/master/packages/dependency-extraction-webpack-plugin)
2. Tweak the `module.exports` so that the `output.filename` uses a function, as described above
3. Run the build

**Expected behavior**
The build should run successfully.

**Comment by sirreal** [comment]
Thanks for the report, @davilera! I've proposed a fix in #15430, I'd appreciate if you give it a test.
