### ISSUE TITLE
Quote styles mistaken for headings and visibility issues

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1541]
I war changing the quoter style and it struck me how it was hard to see they were numbered and also that they looked like headings:

![2017-06-28 at 11 36](https://user-images.githubusercontent.com/253067/27633208-2c8d860c-5bf6-11e7-9b1f-ff4086043f67.png)

Can we improve the spacing at least?

**Comment by swissspidy** [comment]
I've never seen an editor with number quote icons. What's the difference between the two?

Also, how do you even get to this view? When I insert a quote block, the toolbar looks like this:

<img width="499" alt="screen shot 2017-06-28 at 12 51 37" src="https://user-images.githubusercontent.com/841956/27633706-95c8ba9c-5c00-11e7-9375-f6978f71bf6e.png">

Tested on Safari on macOS 10.13.

**Comment by jwold** [comment]
It appears that the two different quote styles are just changing the look of the quote block. In that case it might make sense to use some kind of different iconography?

**Comment by afercia** [comment]
> I've never seen an editor with number quote icons

Just change an existing heading block in a quote block and you will see them 🙂 

<img width="781" alt="screen shot 2017-06-28 at 19 43 30" src="https://user-images.githubusercontent.com/1682452/27651917-2cbcf1dc-5c3a-11e7-99f5-a255bd4dd516.png">

<img width="754" alt="screen shot 2017-06-28 at 19 44 28" src="https://user-images.githubusercontent.com/1682452/27651937-4158bba8-5c3a-11e7-9bb5-5f820aed16dc.png">

**Comment by karmatosed** [comment]
More usability testing feedback:

"And how do I do that, no option in any of the panels, sure I can change the style but I don't want the entire post to be a quote I assume anyway.
What alternit style, no option in the miriad of buttons panels and controls."

**Comment by mtias** [comment]
This has been updated to use separate icons:

![image](https://user-images.githubusercontent.com/548849/29476434-4de2a45e-8464-11e7-8220-80f436c7c932.png)
