### ISSUE TITLE
Twitter embed continuously resizes in columns block

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15416]
This GIF doesn't have many frames per second. In reality it happens much faster.

![twitter](https://user-images.githubusercontent.com/4710635/57143872-21385880-6dc0-11e9-9b8f-1625d46e9a7a.gif)

**Comment by draganescu** [comment]
Hi @ellatrix I re-tested this with Gutenberg 7.9.1 and TwentyTwenty and it seems to not happen anymore. Can you re-test or tell me if there is anything I've missed.

**Comment by ellatrix** [comment]
I _think_ it works fine now, but I'm using a different screen. Seems to the same size as the image above though. Let's close.
