### ISSUE TITLE
Correct block alignment prevented

### ISSUE THREAD

**Issue by rsepierre** [WordPress/gutenberg#15417]
**The Bug** : I am prevented from using something else then "wide" and "full" alignment on the "core/media-text" block
**Steps to reproduce :** Use a core/media-text block and try to change alignement

**Why is this a bug / requires a fix :**
- Not all themes support alignwide & alignfull
- It is a core / first party block and should not force choices uppon the user
- There is no official way to change this questionnable behavior without editing core files

**Expected Behavior :**
- Never prevent a alignement option that works flawlessly with a block.

**How to fix it :**
_wp-includes/js/dist/block-library.js @ lign - 9434_

Replace `align: ['wide', 'full'],`

with
`align: ['center', 'wide', 'full'],`

**More details + broader question :**

There is a pretty good block called "media-text".

It's neat, responsive and you can put an image and text side by side. It's handled both in the editor and in the front-end way better than if you were to use two columns, one with text inside and the other with media.

It's all very good. 

**But,** you only have two alignement options : "wide" and "full".

![image](https://user-images.githubusercontent.com/6746875/57143989-4f1d9d00-6dc0-11e9-869d-ce8dfc94ebb9.png)

- But hey, that's not what I want ?
- so ?

> I think that "no alignement" or "center" should ALWAYS be an option if the block supports align, especially for core blocks.

Maybe third-party can be less permissive because they are optionnal -> if you don't like it don't use it. But core is forced on everyone.

In the case of the "media/text" block, it's also not obvious why you would force it.
I removed the "alignwide" class in the front-end to see if there was any reason it was prevented. 
No, it worked flawlessly and the block behaves perfectly.
I just CAN'T choose this setting because BECAUSE.

**Screenshots**

Width without alignwide class (remove with inspector)
![image](https://user-images.githubusercontent.com/6746875/57144302-14683480-6dc1-11e9-8e26-95fbb1a066a1.png)

With alignwide class (forced uppon every user)
![image](https://user-images.githubusercontent.com/6746875/57144547-92c4d680-6dc1-11e9-94d9-7e48564197c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome, firefox, edge, ie
 - Version : last versions

**Additional context**
- Wordpress 5.1.1 core gutenberg editor

**Comment by draganescu** [comment]
Howdy @rsepierre this appears to work just as you describe if you don't select any align option:

![center-media-text](https://user-images.githubusercontent.com/107534/80077741-94e5ef00-8556-11ea-87eb-3142e5c41e09.gif)

I wonder if this is intuitive enough instead of having a third "center" button there.

**Comment by paaljoachim** [comment]
We brought up the issue during a Gutenberg Design Triage, and feel that @draganescu covers what @rsepierre asked about.
As we have not heard back from the author I will go ahead and close this issue.

Bottom line for this issue as I see it is that I believe that the person is asking about having a center alignment as an option not just as a default option when turning off the alignment options.
