### ISSUE TITLE
Front end form

### ISSUE THREAD

**Issue by A2ZWare** [WordPress/gutenberg#15427]
I have been learning Gutenberg and overall like a lot of it from a developer standpoint. But I am struggling with creating a front end form. I have a form (a sign up block where you can enter name and email to volunteer for something) which I would like available in both the editor and the front end. There could be multiple copies of this block in a post.
Works great in the editor. But when I put it in the save function it seems to get mostly stripped out. I am considering rendering the front end part server side just because I can't figure out how to keep Gutenberg from stripping out the form functionality.
Am I missing something obvious? When I started writing I thought it would function the same in the editor and on the front end. But that doesn't seem to be the case. What is the recommendation for this?

**Comment by swissspidy** [comment]
It would be helpful if you could share your code. Personally, I would probably render things like forms in PHP anyway as it can easily get complex and the markup might change rather frequently.
