### ISSUE TITLE
Blocks still clash with PopClip - can we resolve this?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1542]
I think we need to be careful with clashing as far as apps go that benefit users. Whilst I don't expect us to work with all, this particular app a lot use for spelling (a11y reasons) and also productivity reasons.

Here you can see what happens:

![2017-06-28 at 11 38](https://user-images.githubusercontent.com/253067/27633365-c71280ce-5bf6-11e7-8b29-50b4cd8115fb.png)

See https://pilotmoon.com/popclip/ for more details on what it does.

I am phrasing this as a question as in v1 we may decide this clash is ok - I do however feel it does need looking at. How many other thing cause this issue?

**Comment by iseulde** [comment]
We will also need to test the iOS inline toolbar. :/

**Comment by karmatosed** [comment]
Closing as the pattern has changed here.
