### ISSUE TITLE
Escaping from Modal breaks down key

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15429]
**Describe the bug**

When [a `TextControl` is inside a `Modal`](https://github.com/iandunn/gutenberg-escape-modal-bug/blob/475ae85/src/main/index.js), and the user types something and then escapes out of the modal, the `down` key no longer works.

**To reproduce**

1. `git clone git@github.com:iandunn/gutenberg-escape-modal-bug.git`
1. `npm install`
1. `npm start`
1. activate plugin
1. browse to `wp-admin/admin.php?page=gutenberg-escape-modal-bug`
1. type something into form field
1. press `esc` key
1. press `down` key. 

**Expected behavior**

The viewport scroll be scrolled down. Instead, nothing happens. The `up` key still works, but `down` seems to be prevented by something. 

Closing the modal by clicking on the `x` button does not trap the `down` key.

**Comment by lozinska** [comment]
Hello there! May I work on this issue?

**Comment by kathrynwp** [comment]
@iandunn Hey there. :) Is this still an issue in the current version of Gutenberg?

**Comment by iandunn** [comment]
It seems to be fixed now :)
