### ISSUE TITLE
Strange behaviour when resizing (images, spacers, etc)

### ISSUE THREAD

**Issue by vonloxx** [WordPress/gutenberg#15420]
**Describe the bug**
When resizing, for example, an image, the resize drag handlers disappear and only appear again when deselecting the block and selecting again. This also happens on spacer and media text blocks. Tested with Gutenberg 5.6.1 and Gutenberg Playground (also Drupal Gutenberg - latest dev 😉).

**To reproduce**
1. Add an image block
2. Resize using the resizer drag handler

**Screenshots**
![resizer-issue-1](https://user-images.githubusercontent.com/1254357/57147983-a0c62780-6dc0-11e9-8b1f-954c59f95ed5.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**
- Gutenberg 5.6.1

**Comment by vonloxx** [comment]
At a first glance, it seems the block loses its `.is-focused` class when clicking on the resizer handler.

**Comment by thorandre** [comment]
Confirming this issue. But the issue is more problematic with the "Media & Text" block, than with "Image". 
Also reported for Drupal Gutenberg here:
https://www.drupal.org/project/gutenberg/issues/3029680
