### ISSUE TITLE
Headings block a11y warning

### ISSUE THREAD

**Issue by hearvox** [WordPress/gutenberg#15425]
Perhaps the Headings block could warn users about to enter an improper heading level, e.g., an h4 after an h2. Might it be possible for block to be aware of the current Document Outline output and where, within it, user is currently entering the heading?

**Comment by swissspidy** [comment]
Those warnings are currently present in the Document Outline:

<img width="554" alt="Screenshot 2019-05-04 at 12 19 03" src="https://user-images.githubusercontent.com/841956/57177675-d7ef1400-6e66-11e9-886d-c2d8bd33bdae.png">

So you are suggesting to add these warnings to the heading block too, correct?

**Comment by hearvox** [comment]
Wow, had no idea about the headings warnings in Document Outline. Great feature. But, yes, I am suggesting a warning also appear in the Headings block. A minority of user consult the Document Outline (of those, most already understand heading-levels). A Headings block notice/warning would for the majority of users who don't. It would help lead them to a greater understanding of headings hierarchy, and would likely catch and correct maybe-millions of headings-level errors.

**Comment by afercia** [comment]
Related: #10581 which proposes to add a warning in the sidebar. In-progress pull request: #14889. Not sure a warning displayed within the block itself would make the design team happy :) @hearvox do you think a warning in the sidebar would be sufficient?

**Comment by hearvox** [comment]
@afercia  I absolutely think #10581 -- a notice in block sidebar -- is a great solution. Exposing the hierarchy in the headings block Closing this issue and following the related one. thx
