### ISSUE TITLE
Media & Text block: Option to link media.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15422]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to link the media in the Media & Text block. Similar to the single image block.

Existing Media & Text block:
<img width="1024" alt="Screen Shot 2019-05-03 at 18 19 56" src="https://user-images.githubusercontent.com/5323259/57151045-3fa65000-6dd0-11e9-801b-c5f378232dd7.png">

Single image block:
<img width="989" alt="Screen Shot 2019-05-03 at 18 21 03" src="https://user-images.githubusercontent.com/5323259/57151089-5a78c480-6dd0-11e9-950a-24806a4e1f2a.png">

**Describe the solution you'd like**
A standard single image linking method added to the block.

**Describe alternatives you've considered**
Well one could probably go in through HTML and add a link but that is not very intuitive.

-----

Btw we need a consistent way to handle images in all blocks.

**Comment by idea--list** [comment]
Yes please!
Just logged my first client confusion just because this.

**Comment by donalirl** [comment]
I've encountered this a few times. It's a common use case to want to link that image, and the only way possible right now is to use HTML. It would be great to see the link option added!

**Comment by paaljoachim** [comment]
So what we need right now is a dev that is able to add the image link icon to the toolbar.
So we go from this:

![Screen Shot 2019-08-23 at 12 46 59](https://user-images.githubusercontent.com/5323259/63587372-23f3cf00-c5a4-11e9-9789-40b3523314ea.png)

To this:
![Media-text-block-link-image](https://user-images.githubusercontent.com/5323259/63587389-2fdf9100-c5a4-11e9-9961-6dfbd17178ef.jpg)

**Comment by draganescu** [comment]
I guess here the main concern is that the block is Media + Text, not Image + Text. Video files are not usually linked and I feel as if folk use this block "improperly", instead of using a floated image block and a heading.

I'll label it accordingly and wait it out :)

**Comment by richtabor** [comment]
> I guess here the main concern is that the block is Media + Text, not Image + Text. Video files are not usually linked...

We could have the Link Settings panel only available if `mediaType` is _not_ video.

**Comment by phpbits** [comment]
I've created a solution for this issue few weeks ago on EditorsKit plugin : https://wordpress.org/plugins/block-options/ . Here's how it works :

![Screen Capture on 2019-09-25 at 01-05-53](https://user-images.githubusercontent.com/3365507/65533677-b33c2b80-df30-11e9-84ce-87d38993963c.gif)

My implementation is using the similar existing way of adding link on Image Block. Then added few link options for "rel" attributes. The link toolbar will only be available when media type is `image`.

**Comment by mapk** [comment]
@phpbits that feels pretty good. @draganescu what do you think about just showing the link option for images as in the EditorsKit plugin? ... without all the extra link options though...

**Comment by phpbits** [comment]
@mapk Thanks! I've spiced up the Media and Text Block a bit last few weeks. I've also added the card-like layout aside from left and right image position ;)

**Comment by draganescu** [comment]
Yes, I think we're set, will assign this to me and take a stab at it. ( cc @mapk )

**Comment by draganescu** [comment]
@mapk should we also include the Media File and Attachment options that the image block's link control provides?

**Comment by draganescu** [comment]
This is now testable in #18139

**Comment by Clearly5000** [comment]
Having a similar issue as described at the start of this post. Is this feature out of testing and live on Wordpress.org/.com? Would love to be able to use it!

**Comment by draganescu** [comment]
Howdy @Clearly5000 it is almost ready, goign through reviews right now, it will be testable as soon as #18139 gets merged in master.

**Comment by Clearly5000** [comment]
Great news, thanks!

**Comment by MAHNOORKHANDURRANI** [comment]
i used media and text block ....and i want to edit the image through html want to add more images with a class ewhich i will use for js ...but i cant find the edit as html option...plus how one can achieve this with media and text block

**Comment by draganescu** [comment]
Hi! @MAHNOORKHANDURRANI Your question seems more fit in the [WordPress developer forum](https://wordpress.org/support/forum/wp-advanced/)
