### ISSUE TITLE
Improve button focus styles

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#15432]
Input fields have a medium blue border that replaces the grey input border:

![image](https://user-images.githubusercontent.com/2846578/54308390-51bffb00-45a4-11e9-8635-23083cd571b7.png)

But buttons have light blue border outside of the button borders:

![image](https://user-images.githubusercontent.com/2846578/57184454-b85ce900-6e70-11e9-9c7e-44fa1f1a3751.png)

This is inconsistent, and the button focus styles need to have a minimum contrast ration of 3.1.

Prior idea from @jasmussen:

![image](https://user-images.githubusercontent.com/2846578/57184481-0bcf3700-6e71-11e9-87c2-25d32b0ad970.png)

Some additional ideas:

![image](https://user-images.githubusercontent.com/2846578/57184661-931daa00-6e73-11e9-9653-b4f52f8fdbc7.png)

The bottom color is `#008EC2`, which has a contrast ratio of 3.72. (We'll want to update the input focus styles to also be this color, but we can do that in a separate issue.) This is my preferred option of these three.

Related: #15325, #13900, and https://core.trac.wordpress.org/ticket/34904.

**Comment by afercia** [comment]
+1
See also #13267 for a bug that affects Firefox.

**Comment by jasmussen** [comment]
Thanks for taking a stab, Mel. Of your designs, these seem the most promising to me:

<img width="764" alt="Screenshot 2019-05-06 at 09 47 02" src="https://user-images.githubusercontent.com/1204802/57212427-f29ac780-6fe3-11e9-9dc6-30946c28d63a.png">

One thing I think is worth bringing up: those designs assume we can't redesign the buttons themselves. I'm not saying we absolutely have to do that, but rather opening that up as a "what if". What would buttons look like, redesigned from scratch, to be more legible, accessible, consistent?

Based on the existing tickets around this, I've dabbled with this for a while, and here's the most recent iteration:

<img width="754" alt="Screenshot 2019-05-06 at 09 47 49" src="https://user-images.githubusercontent.com/1204802/57212529-4f967d80-6fe4-11e9-8fb3-be618ee4c173.png">

One aspect I'd like to highlight with the above, is that this style affords us better contrast around the secondary button with the 1px border, where the old button relies on a drop shadow (which is removed in high contrast mode). Additionally, by leveraging that border to change the thickness on focus, we can keep the clear focus style change (contrast & shape), but without complicating the silhuette (double-borders). The double border is okay and necessary for the primary button given the similarity in colors, but given the primary button is a solid, the silhuette remains simple. Finally, changing the button border on focus gives a nice consistency callback to input fields:

<img width="136" alt="Screenshot 2019-05-06 at 09 51 13" src="https://user-images.githubusercontent.com/1204802/57212668-bddb4000-6fe4-11e9-954b-9b1955ea0032.png">

**Comment by afercia** [comment]
Relevant core Trac tickets:

**The design of the focus outline on buttons/elements could be improved**
https://core.trac.wordpress.org/ticket/34904
With some design proposals from @MichaelArestad 

**a11y-focus: Standardizing the handling of :focus and :hover**
https://core.trac.wordpress.org/ticket/34957

**Comment by truchot** [comment]
I ask a silly question: why some buttons have 1px spacing when focusing, but not all ? (like on secondary version or icons buttons)

**Comment by afercia** [comment]
Noting that this issue should cover also other similar cases reported in other issues, now closed in favor of this one. For example. the Calendar selected date, prev/next  month buttons, some custom elements in the sidebar, etc.

See for example screenshot from the full WPCampus report (issue #15277:

<img width="513" alt="Screenshot 2019-05-08 at 17 15 21" src="https://user-images.githubusercontent.com/1682452/57386764-4f011100-71b5-11e9-8811-26f71a27db76.png">

**Comment by afercia** [comment]
@truchot I guess because without the 1 pixel spacing, the focus  outline would just make the button bigger. The spacing allows to clearly see the additional shape on focus:

<img width="222" alt="Screenshot 2019-05-08 at 17 18 48" src="https://user-images.githubusercontent.com/1682452/57386937-b6b75c00-71b5-11e9-87fd-36fe52bde87f.png">

**Comment by melchoyce** [comment]
> I guess because without the 1 pixel spacing, the focus outline would just make the button bigger. The spacing allows to clearly see the additional shape on focus:

Yup! That's exactly it. It distinguishes the outline from the button.

**Comment by melchoyce** [comment]
> Based on the existing tickets around this, I've dabbled with this for a while, and here's the most recent iteration...

Let's get a PR up for this. Marking as `needs-dev`.

**Comment by truchot** [comment]
> > I guess because without the 1 pixel spacing, the focus outline would just make the button bigger. The spacing allows to clearly see the additional shape on focus:
> 
> Yup! That's exactly it. It distinguishes the outline from the button.

I visually prefer the 1px spacing that's the reason of my question, why not all ?
:)

**Comment by melchoyce** [comment]
Didn't feel necessary for the lighter buttons, but we could certainly try it out.

**Comment by truchot** [comment]
Maybe change the color to a dark gray ?

**Comment by truchot** [comment]
> Didn't feel necessary for the lighter buttons, but we could certainly try it out.

Maybe change the color to a dark gray ?

**Comment by truchot** [comment]
Should the button style be flattened or we keep the shadow style ?
