### ISSUE TITLE
Is 'H' intuitive a heading for quotes and text?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1543]
I was doing a test and found myself puzzled why the quote and text were hidden under the letter 'H'. I think this was a case of not having stepped back to think about this before. When you do, its a really odd placement.

![2017-06-28 at 11 44](https://user-images.githubusercontent.com/253067/27633501-72577778-5bf7-11e7-9dc0-4a66baf559e5.png)

Why would a user know what 'H' was for example? What does it even mean :)

**Comment by jasmussen** [comment]
We have been re-evaluating the feasibility of the switcher as it works now, though I still believe transformations are valuable. 

Short of going with this design...

![screen shot 2017-08-18 at 11 23 05](https://user-images.githubusercontent.com/1204802/29452709-a35e06b0-8407-11e7-88b7-488ec1523934.png)

... would things improve if we addressed #493 and then also added a more descriptive tooltip, such as "Transform Heading to..." when you mouse over?

**Comment by karmatosed** [comment]
I am closing as we need usability testing to prove this.
