### ISSUE TITLE
Creating <section> group block

### ISSUE THREAD

**Issue by Nazrinn** [WordPress/gutenberg#15437]
Hey there. I was just wondering if there was the possibility to change the tag of group blocks to `<section>` instead of `<div>`, or if there was any possibility to add an actual `<section>` block?

At worst I could always write down some custom HTML around my group block if I really wanted a `<section>` tag, but that seems rather clunky, and I'd really like be able to apply HTML semantic best practice to my pages directly via Gutenberg.

I know the group block feature is still pretty recent, but I wanted to at least know if you guys planned to add the possibility to use the actual `<section>` tag with Gutenberg.

**Comment by swissspidy** [comment]
Thanks for your report. We‘re already tracking this in #15000.
