### ISSUE TITLE
Issuu embed block is not responsive (re-opened, with fix)

### ISSUE THREAD

**Issue by senff** [WordPress/gutenberg#15439]
Originally reported in #14299 but was closed.

ISSUU embeds are not responsive. The DIV with classes `issuuembed` and `issuu-isrendered` gets some hard-coded values which break the layout.  This is **not** due to the contents of the iFrame, so we should have control over this.

**To Reproduce**

1. Create a new post
2. Add an Issuu embed block
3. Add an Issuu URL to the embed field (eg: https://issuu.com/diymagazine/docs/diy_march_2019)
 4. Save page and then view on a mobile device/browser with responsive mode.

**Suggested solution**
Remove the width and the height from the DIV with class `issuuembed1` and add the following CSS:

```
.embed-issuu  {
  position: relative;  
  max-width: 100%;
  height: 0;
  overflow: hidden;
  padding-bottom: 75%;
}

.embed-issuu .issuuembed {
  position: absolute;
  left: 0;
  top: 0;
  width: 100% !important;
  height: 100% !important;
}
```

**Comment by swissspidy** [comment]
Let's keep discussion at #15439.
