### ISSUE TITLE
LiveReload should be triggered by CSS changes

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15433]
**Is your feature request related to a problem? Please describe.**

LiveReload is a very helpful devex feature, but right now it's only triggered by JS changes, so devs have to manually refresh after making CSS changes.

**Describe the solution you'd like**

LiveReload should also be triggered by CSS changes.

Currently `wp-scripts` [doesn't support SASS](https://github.com/WordPress/gutenberg/issues/14801), and there isn't a clear direction on that ticket yet. In the meantime, it'd be nice to add it for any vanilla CSS files. Once SASS is supported, it should be added for those as well.

**Comment by gziolo** [comment]
It looks like it depends on https://github.com/WordPress/gutenberg/issues/14801.

**Comment by iandunn** [comment]
I don't think it does. We could just go ahead and add support for `.css`, `.scss`, and `.sass` files now, and it would work today for vanilla CSS, and automatically start working in the future when that issue is resolved. It'd be less work to do it all at once now, since I'd think we'd want vanilla CSS to be supported anyway.

**Comment by gziolo** [comment]
We want to replace LiveReload with React Fast Refresh that should also fix this issue. See #21008.

**Comment by gziolo** [comment]
I also found out that LiveReload seems to be no longer maintained. It doesn’t support webpack 5 that we plan to migrate to somewhat later this year.

I will close this issue in favor of https://github.com/WordPress/gutenberg/issues/21008. I wanted to add also that `wp-scripts` supports imports for CSS, images and fonts as of this week (to be released soon).
