### ISSUE TITLE
How to handle promise rejection for getEntityRecord

### ISSUE THREAD

**Issue by paulbonneau** [WordPress/gutenberg#15442]
Hello,

First thanks for your work.
As I started to make some experiments with custom Gutenberg blocks I stumbled onto the following problem : 
I'm using getEntityRecord to retrieve a post using a post id that I get from a field filled by the user ( it feel dumb but I'm just experimenting in order to get confortable with Gutenberg development ).
When the user enters an existing post post_id everything is ok. If the user enter a post_id that is not related to an existing post I get the following error in the console : 
`Unhandled promise rejection Error: "[object Object]"`
I searched and I came to the conclusion that there are no way to handle the rejection of that promise (but i could have miss something).

Here is my question : Is there a way to handle this promise rejection ? If no, am I using getEntityRecord in a way it is not supposed to be used ?

Here is the js code I use to create my custom component (sorry, I'm using ES5, I prefer to get confortable with the Gutenberg / React logic before digging into ESNext and its toolchain) 

`(function (blocks, element, data) {

	var el = element.createElement,	
	registerBlockType = blocks.registerBlockType,
	InspectorControls = blocks.InspectorControls,
	withSelect = data.withSelect;
	registerBlockType('custom-el/post-picker, {
		title: 'Post picker',
		icon: 'megaphone',
		category: 'widgets',
		attributes : {
			post_id: {
				type: 'number'
			}
		},
		save: function(props){
			return wp.element.createElement('div', props.attributes, '');
		},
		edit: withSelect(function (select, props) {
			return {
				props: props,
				post: _.isUndefined(props.attributes.post_id) ? undefined : select('core').getEntityRecord('postType', 'post', props.attributes.post_id)
			};	
		})(
			function (props,post) {
			var className = props.className;
			var getPostObj = function(post_id) {
				var post = wp.data.select('core').getEntityRecord('postType', 'post', post_id)
				setPostIdAttr(post)
				return post
			}

			var setPostIdAttr = function(post_obj){
				if (!_.isUndefined(post_obj)){
					props.setAttributes({
						post_id: post_obj.id
					})
				}
			}

			var post = !_.isUndefined(props.attributes.post_id) ? getPostObj(props.attributes.post_id) : undefined;

			if (_.isUndefined(post)) {
				return [
					el(
						'h3',
						{},
						'Ajoutez un post'
					)
					,
					el(
						wp.editor.InspectorControls, {
							key: 'inspector'
						},
						el(
							wp.components.TextControl, {
								label: 'Selection du post',
								onChange: getPostObj
							}
						)
					)
				]
			}else{
				return [
					el(
						'a', {
							className: className,
							href: post.link
						},
						post.title.rendered
					),
					el(
						wp.editor.InspectorControls, {
							key: 'inspector'
						},
						el(
							wp.components.TextControl, {
								label: 'Test',
								value: props.attributes.post_id,
								onChange: getPostObj
							}
						)
					)
				];
			}
		},)
	});
}(
	window.wp.blocks,
	window.wp.element,
	window.wp.data,
));
`

**Comment by nerrad** [comment]
Hi there,

It's awesome that you're experimenting with the WordPress data api!  Typically we don't answer usage type questions in this repository.  We reserve issues for bug reports and enhancement requests.  So I'm going to close this based on that.  You may want to try the [WordPress support forums](https://wordpress.org/support) or since this is a more technical help request, the [WordPress Stack Exchange](https://wordpress.stackexchange.com/).

One thing I do note in your submitted code is that this line:

```js
var post = wp.data.select('core').getEntityRecord('postType', 'post', post_id)
```

Should not be in the wrapped component and you should have it in the `mapSelectToProps` callback supplied as the first argument on the `withSelect`.

Also, some friendly advice, it makes it easier to comment on code and provide feedback if you put your example in a gist (or another repo) and link in issues :)

**Comment by nerrad** [comment]
Oh and I meant to mention, one thing I've found useful in learning how to do things within the Gutenberg is to see how Gutenberg itself is implementing things.  For instance,  via [this search](https://github.com/WordPress/gutenberg/search?q=getEntityRecord&unscoped_q=getEntityRecord) I found [this usage](https://github.com/WordPress/gutenberg/blob/d21e382f278d80872964dbbbf41eaf32c41150ea/packages/edit-post/src/editor.js#L115).

**Comment by paulbonneau** [comment]
Thanks for replying even if I wasn't posting in the right place, sorry for that ! I will dig into the ressource you gave me.
Sorry for the inconvenience again

**Comment by studionenontwerp** [comment]
I don't get it. Why is there absolutely no, or very bad, documentation on how to develop the new gutenberg/react way. As graphic designer coming php-development with basic js skills its very difficult to figure out how to build blocks in plain js. @paulbonneau, nice to notice I m not the only one in es5. Is there anyone who can give me a proper example on how to use getEntityRecord within a block.
