### ISSUE TITLE
Cover Block: text toolbar is overflow:hidden

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#15443]
Using WP 5.1.1
For some themes, such as Twenty Sixteen, the alignleft and alignright is only as wide as the content. For a Cover block aligned left or right and very short content, the text toolbar is hidden due to `overflow:hidden` on the block. The toolbar should be outside of the block to be unaffected.

**To reproduce**
1. Using Twenty Sixteen, edit a post.
2. Add a Cover block.
3. Choose image.
4. Type text of "xyz".
5. Align the Cover block left.
6. See the text toolbar is only partially visible.

**Expected behavior**
The text toolbar would be fully visible.

**Screenshots**
![hidden-text-toolbar](https://user-images.githubusercontent.com/7957680/57200516-a5224a00-6f52-11e9-9410-5353058eef67.jpg)

**Desktop:**
 - OS: Ubuntu Studio 16.04
 - Browser Firefox
 - Version 66
 - WP 5.1.1

**Comment by nerrad** [comment]
I can reproduce this in the current Gutenberg master branch.

**Comment by jorgefilipecosta** [comment]
Even though in Gutenberg 5.8 cover uses nested blocks, a similar problem happens to the toolbar of the paragraph.

**Comment by tanjoymor** [comment]
Almost opened a new report for this as I couldn't find this one - then the related issues beta tool found this one.

I'm able to reproduce the issue of the paragraph toolbar not being fully visible in every theme I've tested (about 5 different ones - Lodestar, Barnsbury, Gazette, Stow, Radiate).

1. Add a column block
2. Add a cover block within a column
3. Edit the text within the cover block
4. Can't see the full toolbar

https://d.pr/i/b3gdbX

Came up in chat #16912201-hc. Follow up ticket: #2518639-zen

**Comment by youknowriad** [comment]
This is fixed with the new block UI
