### ISSUE TITLE
Block Settings Menu in Toolbar trying to render for a non-existing (just removed) block

### ISSUE THREAD

**Issue by miina** [WordPress/gutenberg#15458]
**Describe the bug**

When removing a block via Toolbar (using the menu with three dots -> selecting Remove Block) then the Block Settings Menu will still try to render again, this will result in either:
a) The preceding block's Toolbar being rendered instead with the Block Settings Menu already open (it shouldn't render open by default), or
b) If there is no block selected (e.g. if the paragraph block is unregistered), then this results in an error:
![Screen Shot 2019-05-06 at 2 30 17 PM](https://user-images.githubusercontent.com/3294597/57225078-89c74580-700b-11e9-9f05-88f50e41cb3c.png)

**To reproduce**

1. Add an Image block as the only block.
2. Remove block via Toolbar:
![Screen Shot 2019-05-06 at 2 31 29 PM](https://user-images.githubusercontent.com/3294597/57225146-d1e66800-700b-11e9-9a17-cc7da9e99474.png)
3. See the default Paragraph Toolbar opening with the Settings Menu already open.

Steps to reproduce the console error:
1. Unregister `core/paragraph` block, e.g.
```
wp.domReady( () => {
	wp.blocks.unregisterBlockType( 'core/paragraph' );
} );
```
2. Add a block, e.g. Image block as the only block.
3. Remove the block via Toolbar
4. See console / error display in the editor.

- Potentially related issue: https://github.com/WordPress/gutenberg/issues/13276

**Expected behavior**

1. When removing a block via the Toolbar then the Toolbar should render for the next selected block without the Block Settings Menu being open.
2. When removing the last block of a post via Toolbar and a new block isn't added by default (e.g. if the paragraph block is unregistered and alternative default block not enforced) then an error shouldn't occur.

**Screenshots**
![Screen Shot 2019-05-06 at 2 40 33 PM](https://user-images.githubusercontent.com/3294597/57225546-f98a0000-700c-11e9-8a49-dac41dc30f67.png)

![Screen Shot 2019-05-06 at 3 26 13 PM](https://user-images.githubusercontent.com/3294597/57228138-61dbe000-7013-11e9-8075-2a06f6c39c92.png)

Tested on the `master` branch as of today.
Also tested with the released 5.6.1 from official plugin repo -- with that version, a console error occurs but the editor doesn't crash.

**Comment by talldan** [comment]
> 1. Unregister core/paragraph block, e.g.
wp.domReady( () => {
	wp.blocks.unregisterBlockType( 'core/paragraph' );
} );

For those testing, another option that doesn't involve code is to use the block manager to hide the paragraph block.

**Comment by talldan** [comment]
Also noticed the same thing was mentioned in the accessibility audit (#15313). That mentions that the issue of the non-closing dropdown occurs for all of the menu items.
