### ISSUE TITLE
The space bar isn't registering when typing a blog post. I have to hit it twice for it to register. 

### ISSUE THREAD

**Issue by dileiny1215** [WordPress/gutenberg#15467]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
Hi @dileiny1215, it would be great if you could fill out the description. The most important part is the **To reproduce** section. 

It sounds like an unusual issue, so it'd be great to understand whether there is a particular way of reproducing it, or whether a plugin might be causing a problem.

Thanks 😄

**Comment by youknowriad** [comment]
Closing as stale. Let's reopen if there are more details about how to reproduce the issue.
