### ISSUE TITLE
Gutenberg Block is modified when displaying in front end

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#15477]
Custom html tag attributes are stripped from the block content when it is displayed:

My block in Gutenberg "Code Editor View" looks like this, after a save/update (I removed the comment tags for clarity):
`<div my-test-attribute="myTestValue" class="wp-block-gutenberg-test-test-block">test text for frontend</div>`

but on the frontend it is only 
`<div class="wp-block-gutenberg-test-test-block">test text for frontend</div>`

the custom attribute `my-test-attribute="myTestValue"` is missing. Is this behaviour intentional and how can it be avoided? 

Thank you so much for any support! (Also is there any better place to look for Gutenberg advice?)
Daniel

**Comment by Soean** [comment]
You should be able to use a data-* attribute like `data-my-test-attribute="myTestValue"`

More infos about the data-* attribute [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*)

**Comment by estebanwaseaten** [comment]
Thank you very much Soean! 
If I would like to use frameworks like UIkit that use specific custom attributes in html tags, the only option would then be to use server-side-rendering of the block via php callback function, or is there another way?

**Comment by estebanwaseaten** [comment]
custom attributes in html tags are also stripped from the tag by the block's render_callback function.

**Comment by youknowriad** [comment]
Unless you're an admin I think custom attributes are stripped for security reasons I think. If you think a specific attribute should be white-listed, consider opening a trac ticket. https://core.trac.wordpress.org/
