### ISSUE TITLE
Testing feedback: adding an unordered list

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1547]
As the tests come in for Gutenberg I am going to make issues but also add feedback here as a constant thread for people to check.

For reference the tests are here: https://make.wordpress.org/test/2017/06/27/call-for-testing-gutenberg/

This feedback is on this task:

"Following the image, add an unordered list with three bullet points. You want to title the first bullet point “Date of Birth - March 14th, 1879.” Title the second bullet point “Known for - Developing the scientific theory of relativity.” Title the third bullet point “Date of Passing - April 19th, 1955.” "

**Comment by karmatosed** [comment]
"I couldn't figure out how to get more room to type so I deleted the image and put the list in there. Creating the list was easy."

**Comment by karmatosed** [comment]
"Easy enough to do but when your on a new line of a list item (ie. you've entered text on point 2, then press enter and point 3 appears but is blank) you can't press enter again to stop the list like you can in the current editor."

**Comment by karmatosed** [comment]
"I did not expect list to be a separate block. I found changing the (unlabelled / missing mouseover text) alignment type for the "write" box from left aligned text to list to be more intuitive. Especially if unordered and ordered were both shown there."

This is an interesting mental model the current editor encourages. How do we work around this and re-train people?

**Comment by karmatosed** [comment]
"So I know what an unordered list is but surely that term is confusing for novice users. The Insert popup just says List. The more detailed box shown above the block shows unordered & ordered list as icons. Without on-hover tooltips this is not very clear. I suspect novices would welcome some visual confirmation."

**Comment by jwold** [comment]
> an unordered list is but surely that term is confusing for novice users

Some editors use Bullet List and Numbered List. Would that make more sense?

**Comment by karmatosed** [comment]
"Ok, this is easier sort of.
1 opened that panel button again, clicked bullited list, code <ul> at top appears.
At this point since I have done basic html I know its probably an unordered list but there are no options for unordered or ordered bullited list.
There is bullited and numbered, there are no descriptions of what each means.
Numbered lists are ordered but bullited lists can be to.
Now is the interesting part.
add first point and hit enter.
add second point and hit enter
hit third point and hit enter.
But am I adding the point, nothing tells me that its there and there are no bullits to say its round, I assume I have added a point.
finally hit escape and then close the panel again.
Oh but looky here there is this publish button by the close panel button, hit the button and close panel is closed, is that button somewhere on the page or is it just extranious text showing or something."

**Comment by karmatosed** [comment]
"Same problem with the 'Write' block as above."

**Comment by karmatosed** [comment]
"I think lists should be in the quick add that you get from hovering over the plus icon. There is plenty of room to have more than just text and image there. Will there be filters for managing those items? Editing the list itself was very easy."

**Comment by karmatosed** [comment]
"Too much digging required to find where Lists are located. I would definitely need to repeatedly tell clients how to find it. Adding bullets shouldn't require 3 clicks (add text, drop down, then selecting lists). And if you want to change lists back to text, it isn't immediately clear."

**Comment by karmatosed** [comment]
"Relatively simple, though it may be less obvious to some users that you need to click the + to get additional options for inserting content, or use the 'insert' at the top of the page (rather than the default text & image options displayed)."

**Comment by karmatosed** [comment]
"I found this fairly easy, though I didn't immediately know I should click the + circle icon to add a new section.  I instead clicked the "Text" option that shows up below my previous block and then had to guess that the list option might be under the first dropdown, which it was.  I only later realized the + icon would have given me the option from the start."

**Comment by karmatosed** [comment]
"This was confusing - there is a Plus button, and a Text option.  Why are there two ways to add things?   I clicked on Text because a bulleted list is Text, and then I wasn't sure what to do, I found that the first option was a drop-down which confused me, and I did find "List" under there.   Later I just clicked the + sign instead of the "Text" and that made more sense to me because it gave me all the options."

**Comment by karmatosed** [comment]
"Most people don't know that the simple dotted list is 'unordered'. It defaults to ordered."

**Comment by karmatosed** [comment]
"at first glance you do not see list bullets in block options inline, need to click the plus icon to see more... not very obvious where to look. Also, is it really necessary to split out lists from a regular text block?"

**Comment by karmatosed** [comment]
"As with adding a Heading - the hardest part of the task was finding where the option is located, although I noticed it while adding the Heading. I later noticed that I could have also added a list by clicking on the "+" sign, and that felt easier and more intuitive. After the initial hurdle of finding the list option, adding a list was a breeze."

**Comment by karmatosed** [comment]
"Again same as previous task, should really be on a place I can enter the list.
The editer seemed to generate a lot of extrainious code in the document so I don't know where I exactly am in the content field I just pasted the task in and hoped it actually appeared, if this is part of things, I'd really like this to be hidden right now its just about the only thing which is taking this thing down, the old editor doesn't have this wp freeform and other such fucking shit on it.
Seriously guys, what is all that code for why does it even need to be visible to the user, I understand it may have baring on what is in the document but I have no idea if I am doing the task or not."

**Comment by karmatosed** [comment]
"The option to choose the type of block should be explained very clear in some kind of new user onboarding. There are so many elements on the page, that one might miss the arrow at the paragraph icon."

**Comment by karmatosed** [comment]
"I almost couldn't add this list at all. When I tapped on the "Insert Block" button, I had to tap half a dozen times to get the selections to pop up. Then, the window popped up all over the place (above, below, next to the button) where I couldn't view or scroll to it, also popping up my iPad's keyboard to cover the window. After rotating and trying repeatedly I got the window in a place where I could see it and select the List block.

Once the List block was added, writing out the bullet points was quite straightforward. I was surprised to discover that my iPad didn't autocapitalize the beginning of a new bullet point, but that was a minor detail."

**Comment by karmatosed** [comment]
"1) In my opinion, the plus sign by itself is not very noticeable and it's not really clear right away that you can insert blocks other than paragraph and image. Maybe having a label for that button would be better?

2) I tried to copy the text from here and paste it to the editor and the format was copied with the text. It's usually not a problem for me and I know that in old edi"

**Comment by karmatosed** [comment]
"It's easy to find the unordered list block and add it. It's perhaps less obvious that a list would be a new block and require a new paragraph block added afterwards, instead of the usual hit-enter-twice-to-finish-list pattern."

**Comment by karmatosed** [comment]
Closing as moving to the project. We are moving things to projects that aren't core Gutenberg and need to be done apart.
