### ISSUE TITLE
Search block with no button content

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#15487]
**Describe the bug**
Search block with no button label or text present is causing a PHP error within the editor and front-end of the website.

**To reproduce**
1. Edit any page
2. Add a search block (widget)
3. Clear the button label (content)
4. Save the page and visit the site on the front-end.

**Expected behavior**
No error should be displayed.

**Screenshots**
![](https://i.imgsafe.org/1e/1ef967fb30.png)

**Comment by karmatosed** [comment]
Thanks for reporting this. I can confirm I am also seeing the following:

![image](https://user-images.githubusercontent.com/253067/61561566-38a1ec00-aa67-11e9-910f-631e2f3f1627.png)

**Comment by skorasaurus** [comment]
This has been 'fixed' in https://github.com/WordPress/gutenberg/pull/16189 (and added in Gutenberg 6.3.0) and I am unable to reproduce this.

However, [I share @afercia 's sentiment](https://github.com/WordPress/gutenberg/pull/16189#issuecomment-502437421) that the current behavior, as currently, implemented, is not friendly for screen reader users who aren't aware that a search box is there when a user is focused on that element. 

The current implementation of the search block fails to conform to [WordPress' Accessibility Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/#labeling). :/

**Comment by talldan** [comment]
@skorasaurus Thanks for pointing that out. It seems like a separate issue though aside from the PHP Notice—would you be able to create a separate issue covering those concerns?

**Comment by skorasaurus** [comment]
@talldan that separate issue is made at https://github.com/WordPress/gutenberg/issues/17351

**Comment by talldan** [comment]
Thanks!
