### ISSUE TITLE
Block movement controls appear broken in WP5.2 update

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#15489]
**Describe the bug**
The block movement controls (up, down, drag icons) appear broken when a block's alignment is set to "wide" or "full" since the WordPress 5.2 update.

**To reproduce**
1. Add an image block
2. Change the block's alignment to "wide" or "full"
3. Note how the movement controls appear over the top of other controls.

**Expected behavior**
The movement controls should appear visible alongside the other toolbar controls.

**Screenshots**
Please see this screen recording to demonstrate the issue:
http://recordit.co/4dMQzETpg1

**Additional context**
- WordPress version 5.2

**Comment by karmatosed** [comment]
Thanks for reporting this. I can confirm I also see this.

![image](https://user-images.githubusercontent.com/253067/61561184-37bc8a80-aa66-11e9-8648-efb2c3acb1ef.png)
