### ISSUE TITLE
Gallery block image display issue on older iPad / iOS models

### ISSUE THREAD

**Issue by mikeicode** [WordPress/gutenberg#15488]
Images using the Gallery block don't display correctly on older iPads / iOS. Doesn't appear to be theme related as I have tested 5 different themes and they all have the same result.

**To reproduce**

* Add an image block to a page, add multiple images
* View published page on older model iPad

**Expected behavior**

Images should display correctly in the grid

**What happened instead**

The images stack on top of each other and the surrounding text.

![img](https://cld.wthms.co/Ne0wMY+)

**Device**
I am testing in Safari on an iPad with iOS 9.35. which is the latest available for this device.

**Additional context**
Gutenberg:  Version 5.1.1

**Comment by formosattic** [comment]
+1 in 2178677-zen

Tested with a few devices and iOS, via BrowserStack

## iPad Mini 2019, iOS 12 - looks OK ✅
![Screen Shot on 2019-07-20 at 15:47:54](https://user-images.githubusercontent.com/15944096/61575993-5eca9900-ab06-11e9-9091-16bb044e21f9.png)

## iPad 4 Mini, iOs 9.3 - not OK ❌
![Screen Shot on 2019-07-20 at 15:33:57](https://user-images.githubusercontent.com/15944096/61576012-86216600-ab06-11e9-8a7f-751e3ddf2fc3.png)

## iPad Mini 3, iOS 8 - not OK ❌
![Screen Shot on 2019-07-20 at 15:35:29](https://user-images.githubusercontent.com/15944096/61575999-65f1a700-ab06-11e9-942b-21a8bf651484.png)

**Comment by talldan** [comment]
It's frustrating that Apple doesn't update their browser on older devices.

The WordPress browser support policy is the last two versions of iOS - https://make.wordpress.org/core/handbook/best-practices/browser-support/.

Unfortunately iOS 9 is now much older (latest version is iOS 15), so I'll close this issue.
