### ISSUE TITLE
register_block_type() and the WP REST API 

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#15484]
Does the render_callback fire during a REST API request?

That is, if you use the r_b_t() function and the render_callback to override the block's default "view" with that override also happen during a REST API request for the content?

I would presume, yes; but knowing is better than presuming. tia

https://developer.wordpress.org/reference/functions/register_block_type/

**Comment by draganescu** [comment]
Howdy @AlchemyUnited ,

The blocks are rendered server side using a function named `do_blocks` which is hooked into the filter `the_content`. You can see that [here](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/default-filters.php#L172), where we have `add_filter( 'the_content', 'do_blocks', 9 );`.

`the_content` function will trigger `the_content` filter which will call (amongst others) `do_hooks` which executes `render_blocks` and this one, for each block calls `render_callback `.

Given that the REST api use the same content functions, thus triggering the same filters, the answer to your question is definitely yes.

**Comment by AlchemyUnited** [comment]
@draganescu - Thank you. And thanks for the details.
