### ISSUE TITLE
Group Blocks and Wordpress 5.2?

### ISSUE THREAD

**Issue by changeling** [WordPress/gutenberg#15490]
Group blocks don't appear to be present in WP 5.2, as far as I can tell.

I've searched support forums and issues in different contexts, but all I see are blog posts and discussions mentioning that they are great, and implemented and  intended to be releasing with WP 5.2. I've spent hours disabling plugins, spinning up WP instances with varying themes, and do not see Group blocks anywhere.

Two things:

a) Question: should I be seeing them, and if so, should I continue debugging/triaging to find what's blocking them?

b) Question: If they aren't there, is there documentation indicating that fact, and where might I find that? And Comment: If there isn't, there really, really, _really_ (I mean, REALLY) should be. And somewhere a user can easily find them.

**Comment by GlennMartin1** [comment]
To use the latest Gutenberg that includes group blocks, install the Gutenberg plugin. Group blocks was introduced too late for inclusion in WordPress 5.2.

**Comment by changeling** [comment]
Thanks for that! Is this clearly documented somewhere prominently visible?

**Comment by GlennMartin1** [comment]
On this page https://wordpress.org/gutenberg/ it says:

> Gutenberg is available as part of WordPress 5.0 and later.... Future development will continue in the Gutenberg plugin.

If you wish to be more up-to-date with the Gutenberg development, you've simply got to have the Gutenberg plugin activated and up-to-date.

**Comment by youknowriad** [comment]
Closing per @GlennMartin1's responses.
