### ISSUE TITLE
Table of contents link hash scroll issue.

### ISSUE THREAD

**Issue by parmarhardip** [WordPress/gutenberg#15493]
Content Hash (#) scrolling issue.

**To reproduce**
1. Open this link (https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/select-control/)
2. Go to "Table of contents"
3. Click Number Content. (1. Design guidelines, 2. Development guidelines, 3. Related components)

**Expected behavior**
It should be a scroll when click number content.

**Screenshots**
![2019-05-08_1307](https://user-images.githubusercontent.com/23077242/57364637-3ab31900-71a1-11e9-8152-4f290206e557.png)

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by aduth** [comment]
Fixed by #15494
