### ISSUE TITLE
Way to output custom html-tag-attributes from blocks

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#15492]
is there any way to include custom html-tag-attributes (not necessarily data-*) in the output of a block? Example:
`<div someAttribute="test">`
These attributes seem to get removed by the block's save() function as well as its php render_callback function. This makes it impossible to use third party frameworks that rely on these attributes.

I was thinking of using filters 'block_parser_class' or 'render_block', but without success so far.
Any hints are greatly appreciated.

**Comment by youknowriad** [comment]
Duplicate of #15477
