### ISSUE TITLE
Classic Paragraph is used by default when starting to create new post

### ISSUE THREAD

**Issue by vesaraiskila** [WordPress/gutenberg#15497]
**Describe the bug**
After WordPress 5.2 update, starting to write a new post results in the use of the Classic Paragraph.

**To reproduce**
1. Choose to add a new post.
2. Tap the text space under the heading field.

**Expected behavior**
A Gutenberg block is created.

Note:

If I don't tap the text space but instead the "plus" (Add block) sign on the left and then select "Paragraph", a Gutenberg block is created. Adding a new Gutenberg block from that on requires pressing the Enter key. 

Desktop (please complete the following information):

OS: Mac OS Mojave version 10.14.4
Browser: Safari
Safari version: 12.1
Additional context

WordPress version: 5.2 (with the included Gutenberg version)

**Comment by youknowriad** [comment]
I'd say it's probably not related to the JavaScript errors you're having but sharing those doesn't harm.
Even if it started with WordPress 5.2 doesn't mean it's not a plugin conflict. So if you have the possibility to disable plugins and test, that would be appreciated. Otherwise, can you share more about the plugins you have. I'm asking because we can't reproduce the issue with just WordPress 5.2.

**Comment by nicopujol** [comment]
Same issue/bug since upgrading to WordPress 5.2. It opens a classic block by default and will not allow deleting it or "converting to blocks".

**Comment by vesaraiskila** [comment]
> Same issue/bug since upgrading to WordPress 5.2. It opens a classic block by default and will not allow deleting it or "converting to blocks".

I can get rid of it by clicking the "plus" sign above the block and selecting "Paragraph". The classic block then just disappears, and pressing Enter creates additional Gutenberg blocks. However, the choice of blocks is then restricted to six, one of which is the Classic paragraph:

![image](https://user-images.githubusercontent.com/46203937/57433322-e0699500-7240-11e9-83e6-8787f255ca52.png)

@youknowriad I have shared the active plugins here:

https://github.com/WordPress/gutenberg/issues/15491#issuecomment-490765866

**Comment by vesaraiskila** [comment]
> Same issue/bug since upgrading to WordPress 5.2. It opens a classic block by default and will not allow deleting it or "converting to blocks".

I can also delete it by pressing the "Plus" sign (on the left of the block), after which the three dots appear at the top right corner of the block, and the menu that opens from that contains the delete block option.

Addendum to my above comment: sometimes pressing the "plus" sign on the left does open a dialog that contains all the available block options, not just the six in the screenshot above. Pressing "plus" **above** a Gutenberg block **always** brings up the dialog with all the options.

**Comment by Creat1veM1nd** [comment]
Had the same issue. Deactivating the plugin "TinyMCE Advanced" solved it.

**Comment by vesaraiskila** [comment]
> Had the same issue. Deactivating the plugin "TinyMCE Advanced" solved it.

Thanks for the information. Deactivating that plugin solved it for me too.

I guess we can close this issue now.

**Comment by azaozz** [comment]
Just FYI this is a setting in the TinyMCE Advanced plugin :)

It is mostly intended to "ease-in" the transition for users that have just updated WordPress and are "dropped into" a completely new, unfamiliar Edit Post screen (yeah, that's scary!). We've been looking at, using and working on Gutenberg for couple of years now. We've seen it evolve and get better and better, and of course are quite familiar with it. But a lot of WP users are not. Having a familiar place to start with is a big help :)

There haven't been any changes in the TinyMCE Advanced plugin in that area for 5.2, but seems Gutenberg handles changing the "default block" better now. It can easily be turned off for people that don't need it:

![default-block](https://user-images.githubusercontent.com/743931/57474953-355cd980-7248-11e9-95f7-995e40672688.png)

**Comment by nicopujol** [comment]
Interesting, thanks for the clarification. I think it will confuse users which did the mental and technical effort to move to Gutenberg blocks to find themselves with the classic editor when starting a post. It was quite perplexing yesterday as, without notice, the first block was no longer a 'paragraph' and it wasn't clear to how to remove it ("convert to blocks" failed since there was no content).

On the topic of TinyMCE Advanced we're seeing another glitch since this week, independent of this behavior (insertion of spaces when updating a classic block). It needs a new ticket, where can I report this?

**Comment by azaozz** [comment]
> ...to find themselves with the classic editor when starting a post.

This was always the "intended behaviour" when changing the default block (not just to classic paragraph, can be any block, image, list, etc.). It was a little bit glitchy before, now it works better/properly.

Best place to report bugs with the plugin is https://wordpress.org/support/plugin/tinymce-advanced/ (like all WP plugins).

**Comment by ombion** [comment]
Thanks for pointing out settings in TinyMCE. With default settings, Classic Paragraph blocks keeps taking over when I just want select another the block. This annoys the heck out of me.


> Just FYI this is a setting in the TinyMCE Advanced plugin :)
> 
> It is mostly intended to "ease-in" the transition for users that have just updated WordPress and are "dropped into" a completely new, unfamiliar Edit Post screen (yeah, that's scary!). We've been looking at, using and working on Gutenberg for couple of years now. We've seen it evolve and get better and better, and of course are quite familiar with it. But a lot of WP users are not. Having a familiar place to start with is a big help :)
> 
> There haven't been any changes in the TinyMCE Advanced plugin in that area for 5.2, but seems Gutenberg handles changing the "default block" better now. It can easily be turned off for people that don't need it:
> 
> ![default-block](https://user-images.githubusercontent.com/743931/57474953-355cd980-7248-11e9-95f7-995e40672688.png)

**Comment by officespacemike** [comment]
We have found this line of code:  on several hundred pages.
Is this likely to cause crawl issues?
