### ISSUE TITLE
Video upload isn't working like expected

### ISSUE THREAD

**Issue by marecar3** [WordPress/gutenberg#15510]
**Describe the bug**

1. When I try to upload an mp4 video using Premium account, It's with success in 30% of attempts and in a case of failure, I am getting random errors :

- Stuck on "converting 99% "
- Stuck on "Loading..."
- Stuck on "Conversion error"
- Stuck on "converting 52%" 

2. When it's a success I can't preview uploaded video

**To reproduce**
1. Download video from https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Create a new Post
3. Add video block
4. Select Upload and pick a downloaded video from step 1.

**Expected behavior**
Sometimes it's stuck with uploading, sometimes it's working

**Screenshots**

<img width="710" alt="Screen Shot 2019-05-08 at 1 34 45 PM" src="https://user-images.githubusercontent.com/28219092/57396044-7f39b700-7197-11e9-99ac-7d92996cfc1e.png">

<img width="1114" alt="Screen Shot 2019-05-08 at 11 10 02 AM" src="https://user-images.githubusercontent.com/28219092/57396069-9082c380-7197-11e9-9257-66434b4b8607.png">

**Desktop (please complete the following information):**
 - OS **Mac OS Mojave : 10.14.3**
 - Browser **Chrome**
 - Version **73.0.3683.86 (Official Build) (64-bit)**

**Comment by aduth** [comment]
>using Premium account

This appears to be an issue for WordPress.com or Jetpack video uploads (judging also by the [VideoPress](https://videopress.com/) UI), not a problem in the core WordPress software.

I'd recommend you instead open an issue on one of their respective repositories:

- https://github.com/automattic/wp-calypso/issues/new
- https://github.com/automattic/jetpack/issues/new
