### ISSUE TITLE
Copy + paste block

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#15513]
It is possible to duplicate a block inside the same (editor) page.
Is it also possible to copy a block into clipboard, then paste it in another (editor) page?
There seems to be no button for this yet, also `Ctrl` + `c` doesn't seem to copy a selected block either.

**Comment by swissspidy** [comment]
Yes, you can copy and paste blocks as you like by simply selecting all the content and using Ctrl + C and Ctrl + V.

Could you perhaps give us some additional information about which browser and which version of WordPress you are using?
