### ISSUE TITLE
Edited link URL doesn't reflect new value until after refresh

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15522]
**Describe the bug**

When copying a page and then editing the value of a link, the change is saved, but not  reflected in the UI until after refresh. 

**To reproduce**

1. Open a page that contains a Classic block and has links in it
1. Go to code editor and copy the raw markup
1. Create a new page and open the code editor, paste the raw markup, switch back to the code editor
1. Convert the existing Classic block into regular blocks
1. Click on a link inside one of the paragraph blocks, the toolbar and popover appear
1. Click on the pencil icon in the popover
1. Change the value of the URL
1. Hit enter
1. Notice that the value has not changed.
1. Save page, refresh, notice that the value has changed.

**Expected behavior**

The new value should be reflected in the UI immediately.

**Comment by iandunn** [comment]
Actually, I'm seeing this happen with existing pages too, without steps 1-4. It's odd that that wasn't noticed before 5.2 was release, though, so maybe there are other conditions?

**Comment by aduth** [comment]
It's quite likely this and #15503 are of the same underlying cause.
