### ISSUE TITLE
Handbook: duplicate pages

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#15526]
There are some pages that are duplicated in the handbook:

#### `HorizontalRule`:

* Canonical: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/horizontal-rule/
* To delete:
  * https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/horizontal-rule-2/
  * Delete: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/horizontal-rule-3/
  * Delete: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/horizontal-rule-4/
  * Delete: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/horizontal-rule-5/

#### `@wordpress/dependency-extraction-webpack-plugin`:

* Canonical https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin/
* To delete:
  * https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin-2/
  * https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin-3/
  * https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin-4/
  * https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-dependency-extraction-webpack-plugin-5/

#### `@wordpress/tests-e2e`

- To delete: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-tests-e2e/

~I don't think we've ever published this package? It doesn't exist in npm https://www.npmjs.com/package/@wordpress/tests-e2e cc @gziolo Do you happen to remember if it ever existed?~ ([see](https://github.com/WordPress/gutenberg/issues/15526#issuecomment-490872773))

#### `Getting started`

* Canonical https://wordpress.org/gutenberg/handbook/contributors/develop/getting-started/
* To delete
  * https://wordpress.org/gutenberg/handbook/contributors/develop/getting-started-2/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/getting-started-3/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/getting-started-4/

#### `Managing Packages`

* Canonical https://wordpress.org/gutenberg/handbook/contributors/develop/managing-packages/
* To delete
  * https://wordpress.org/gutenberg/handbook/contributors/develop/managing-packages-2/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/managing-packages-3/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/managing-packages-4/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/managing-packages-5/

#### `Localizing Gutenberg Plugin`

* Canonical https://wordpress.org/gutenberg/handbook/contributors/develop/localizing/
* To delete
  * https://wordpress.org/gutenberg/handbook/contributors/develop/localizing-2/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/localizing-3/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/localizing-4/
  * https://wordpress.org/gutenberg/handbook/contributors/develop/localizing-5/

**Comment by gziolo** [comment]
> I don't think we've ever published this package? It doesn't exist in npm https://www.npmjs.com/package/@wordpress/tests-e2e cc @gziolo Do you happen to remember if it ever existed?

It was marked as private before we renamed it to `@wordpress/e2e-tests`. It can be safely removed as it should never be exposed.

**Comment by chrisvanpatten** [comment]
All of these pages will be effectively invisible after the wildcard redirects are in place. Is it worth fixing them in the legacy handbook, or just verifying this won't be an issue in DevHub and ignoring the duplicate content for the time being?

**Comment by nosolosw** [comment]
Yeah, I don't think this is a pressing issue. I'd like to still track the existing problems, though, as to make sure we don't have them in the new system.

**Comment by nosolosw** [comment]
Closing as this doesn't happen in DevHub.
