### ISSUE TITLE
Enter and tab behaviour feedback

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1552]
This is a very specific feedback from a user test sent in via the testing form, so thought worth issue:

"I find the "enter" and "tab" behavior to be absolutely maddening. I expect at the end of an unordered list that hitting enter twice will LEAVE the list and start a new paragraph, instead I'm trapped in a list.

I find it bizarre that tab doesn't indent things like it does in every other editor I can remember using. Don't me wrong, I LOVE keyboard shortcuts and tab between form fields regularly, but these aren't form fields these are full on WYSIWYG content blocks and I expect them to behave like Word, TextEdit, etc... all do when it comes to the keyboard.

I _need_ keyboard shortcuts for formatting things, like turning 5 lines into an unordered list, or indenting/de-indenting some text. 

I've tried HARD to write in this, but after a few paragraphs I'm at my wits end and go back to the old editor because this is just too slowly and awkward."

**Comment by swissspidy** [comment]
> I find the "enter" and "tab" behavior to be absolutely maddening. I expect at the end of an unordered list that hitting enter twice will LEAVE the list and start a new paragraph, instead I'm trapped in a list.

See #1482.

Tab for indentation definitely makes sense to me.

**Comment by jwold** [comment]
That's some great feedback.

When I'm going longform on article writing I use shortcuts common to many editors, or write in markdown. 

A few shortcuts I use very regularly:

- Unordered/ordered lists
- Heading sizes
- Bold, italics, strike, underline
- Code

**Comment by afercia** [comment]
> Tab for indentation definitely makes sense to me.

Beware of keyboard traps 🙂

**Comment by afercia** [comment]
> I find it bizarre that tab doesn't indent things like it does in every other editor I can remember using. 

Just wanted to add that this is not how HTML works 🙂  Users sometimes get confused by what desktop editors (Word) do and they expect that works also in HTML. 
Instead, in HTML multiple spaces and tabs get converted to a single space. It's a SGML thing and there's nothing we can do about that.
Even when there's a "visual" indentation, for example with unordered/ordered lists, that's not a tab character and it's usually rendered with some padding or margin.

Only in preformatted text the tab characters are respected, or when using the related CSS properties.

**Comment by karmatosed** [comment]
Closing as moving to the project. We are moving things to projects that aren't core Gutenberg and need to be done apart.
