### ISSUE TITLE
Video upload on Free plan gives wrong error message on WordPress.com

### ISSUE THREAD

**Issue by marecar3** [WordPress/gutenberg#15533]
**Describe the bug**

When I try to upload an mp4 video using Free plan on WordPress.com, it gives an wrong error message. I think that we need to change that as it is not clear for users why they can’t upload videos.

**To reproduce**
1. Download video from https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Create a new Gutenberg (Block Editor) Post
3. Add video block
4. Select Upload and pick a downloaded video from step 1.

**Expected behavior**
We should inform user that he doesn't have Premium plan, something like this : 
<img width="630" alt="Screen Shot 2019-05-08 at 11 20 37 AM" src="https://user-images.githubusercontent.com/28219092/57454518-0c801880-7237-11e9-9b3f-4b96593e06c1.png">

**Screenshots**

<img width="1114" alt="Screen Shot 2019-05-08 at 11 17 46 AM" src="https://user-images.githubusercontent.com/28219092/57398330-b8285a80-719c-11e9-8c08-dc0721ce8691.png">

**Desktop (please complete the following information):**
 - OS **Mac OS Mojave : 10.14.3**
 - Browser **Chrome**
 - Version **73.0.3683.86 (Official Build) (64-bit)**

**Comment by Soean** [comment]
I am able to upload the Video in my test environment.
What do you mean by `Free account`? What message do you expect?

**Comment by marecar3** [comment]
Hey @Soean , thanks for the response.

I mean that if the user has `Free plan` he can't upload videos using the Gutenberg web.

Expected behavior
We should inform user that he doesn't have Premium plan, something like this :
<img width="630" alt="Screen Shot 2019-05-08 at 11 20 37 AM" src="https://user-images.githubusercontent.com/28219092/57454768-9f20b780-7237-11e9-9194-ad1af9d017ad.png">

**Comment by Soean** [comment]
Ah, you are talking about wordpress.com?

**Comment by marecar3** [comment]
Yes, sorry for not being clear. I am talking about WordPress.com
I will update the description.

**Comment by Soean** [comment]
Maybe we should hide the upload button, if the user is not allowed to upload videos?

**Comment by Soean** [comment]
They are allowed to add a Video by adding an external url, so they should be able to add this block.

**Comment by marecar3** [comment]
Ok, thanks for the information :)

**Comment by melchoyce** [comment]
@marecar3 Hey, can you report this on https://github.com/automattic/wp-calypso/ instead? This is an issue WordPress.com will have to solve with its particular implementation of Gutenberg.

Going to close this issue.
