### ISSUE TITLE
Table block breaks while editing

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#15530]
Somehow table block gets broken while editing.

The following error is shown within the browser console:
 
```
IndexSizeError: The index is not in the allowed range.
getRangeAt
(anonymous function) — load-scripts.php:16:9094
useMemo — react-dom.min.js:205
I — load-scripts.php:16:9044
Td — react-dom.min.js:82
hi — react-dom.min.js:102:388
Qg — react-dom.min.js:144:220
Rg — react-dom.min.js:145
Sc — react-dom.min.js:158:112
Z — react-dom.min.js:156:495
ah — react-dom.min.js:159:229
xf — react-dom.min.js:40
xf
```

![](https://i.imgsafe.org/40/400cc11fe1.gif)

**Comment by youknowriad** [comment]
I tried several manipulations and wasn't able to reproduce so far. Would you be able to clarify the steps to reproduce?

**Comment by youknowriad** [comment]
Closing as stale, let's reopen if we have more details about how to reproduce it.
