### ISSUE TITLE
Most Used Blocks Constantly Shifting Around

### ISSUE THREAD

**Issue by mitchellkrogza** [WordPress/gutenberg#15534]
**Is your feature request related to a problem? Please describe.**
Version 5.2 has somehow changed the most used blocks section when adding a block. While editing posts I am working with 2 block types, spacer and shortcode and constantly switching between the two. As a result they keep changing positions inside the most used block. Maybe great for some people only writing new posts, but it certainly wasn't like this in the previous version. Now editing over 100 posts, the position of where I expect the last block element I used to be, is now shifted to a new position and of course the 2 I am using also keep switching back and forth the whole time. I understand the logic to bring most recently used to a new position but at least give people the option to turn that off. 

**Describe the solution you'd like**
Have a list of most used blocks but prevent it from constantly moving all the block types around as each one has been used.

**Describe alternatives you've considered**
No current solution, just a lot of frustration and fatigue. Fatigue to users is something that seems to get very little consideration in design and functionality changes.

**Comment by designsimply** [comment]
Great suggestion. I am not sure what if anything changed in WP 5.2 and I am stopping by to add a screenshot and a note.

![Screen Shot 2019-05-14 at 2 50 19 PM](https://user-images.githubusercontent.com/1119271/57731709-8578d900-7658-11e9-9a31-0920f80cc6a0.png)
<p style="clear:both;"><sub>Tested with a WordPress 5.2 and Jetpack 7.3.1 as the only active plugin on a `jurassic.ninja` test site using Firefox 66.0.5 on macOS 10.14.4.</sub></p>

I noticed it was mentioned as a future possible update in https://github.com/WordPress/gutenberg/pull/2877 where the algorithm for the most frequently used blocks was adjusted in the past:

> We probably want to think about future refinements that "age" the usage too, in the future.

@mitchellkrogza as a workaround in the mean time, have you tried the slash inserter? It's not for everyone, but it might work well for your use case to avoid having to use the frequently used blocks section entirely.

**Comment by mitchellkrogza** [comment]
Thanks @designsimply never used the slash inserter, pretty neat.

**Comment by youknowriad** [comment]
I'm going to close this now as we have the option to hide the "Most used blocks" and if we chose to enable it, the positions will stabilize as we use the block editor more.
