### ISSUE TITLE
Reusable Block in template becomes invalid after save

### ISSUE THREAD

**Issue by koolkatwebdesigns** [WordPress/gutenberg#15542]
**Describe the bug**
A reusable block added via a template appears fine at first but becomes invalid after save

**To reproduce**
1.Add a reusable block to a template as follows:
‘template’ => array(
array( ‘core/block’, array(
‘ref’ => ‘547’,
) ),
2. In the dashboard, create a new instance of a custom post type via "add new"
3. Notice the reusable block appears in the editor.
4. Preview the post and notice the usable block appears in the front end
5. save the post as a draft or publish
6. Refresh the browser
7. Notice the reusable block is no longer present and is replaced by the message:
"Block has been deleted or is unavailable."

Note: The reusable  block can still be manually added to the post and will work fine.
Screen shot
![Screenshot 2019-05-09 09 34 02](https://user-images.githubusercontent.com/3653239/57470723-5e786c80-723e-11e9-940c-a89dc01c50d5.png)

**Expected behavior**
The reusable block should be saved with the post and re-appear

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser: chrome
 - Version:  74.0.3729.131

**Additional context**
I am using WordPress  5.2

**Comment by noisysocks** [comment]
This works when I try it in the latest Gutenberg.

![template](https://user-images.githubusercontent.com/612155/67921733-cf507e00-fbfc-11e9-8e5c-0bcad1c52385.gif)

I used this CPT to test:

```php
function myplugin_register_book_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Books',
        'show_in_rest' => true,
        'template' => array(
            array( 'core/block', array(
                'ref' => 30,
            ) ),
        ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

Possibly was fixed by https://github.com/WordPress/gutenberg/pull/14367.

**Comment by koolkatwebdesigns** [comment]
I am still seeing this issue in WP 5.3
