### ISSUE TITLE
Image crop workflow is confusing

### ISSUE THREAD

**Issue by kevincoleman** [WordPress/gutenberg#15546]
When cropping an image in the media library, after clicking the crop button and then dragging the edges to where I want the crop to be it’s unclear how to actually apply the crop. After discovering that I have to click the crop button again (not intuitive), it’s still confusing to see the save button—it makes me wonder if the crop is or isn’t saved at that point.

See a short video I created to demo the problem [here on YouTube](https://youtu.be/d31kmZEP1t0).

**Describe the solution you'd like**
It would make sense to me that while in the operation of cropping there would be a button that says something like “I’m done cropping” or “Apply this crop”. After applying a crop, it would make sense to have a small message that says something like “Your cropped image will look like this. Be sure to click save to save the cropped image to your media library.

**Describe alternatives you've considered**
Really, just anything to help guide people through this process would be better.

*Note* this may be a core issue or even a WordPress dependency issue. Unsure. Please refer it to the correct location.

**Comment by youknowriad** [comment]
Hi there thanks for opening the issue. Unfortunately, the media library is not maintained in this repository. May I suggest you to open an equivalent trac ticket here https://core.trac.wordpress.org/

Thanks.

**Comment by kevincoleman** [comment]
Great! Thanks for redirecting me, even if I have to suffer Trac. 👍🏻
