### ISSUE TITLE
Add link to gutenberg reusable blocks to admin sidebar

### ISSUE THREAD

**Issue by frogdesk** [WordPress/gutenberg#15549]
**Is your feature request related to a problem? Please describe.**
Gutenberg reusable blocks are one of the coolest features that came with Gutenberg. I've made extensive use of them, but every time I want to edit one or check something about it I have to go edit another post first, and then use the triple-dot drop down to get to the reusable blocks page. This is a lot of steps just to get to a page that I use a lot.

**Describe the solution you'd like**
My ideal solution would be to add "Reusable blocks" (or just "Blocks") link in the admin sidebar along with posts/media/pages/comments links. Alternatively, it could be a sub-item under posts, pages, or media, but I'm not sure any of those truly make sense as the parent item.

**Describe alternatives you've considered**
I suppose the alternative is leaving it where it is, imo that's not a very good user experience and these blocks are something that would be useful for non-coder editors to have easy access to.

It's possible that not too many are using them, or at least not the way I am, but I think they are extremely useful to create user-editable bits of content that you as a theme developer can insert into widgetized areas or other parts of your template.

It would be nice to at least have a configurable option to add a more convenient link easily.

**Comment by aristath** [comment]
Yes please!!

**Comment by frogdesk** [comment]
Here is a workaround for anyone who finds this issue and wants an immediate solution. Add this to your theme's functions.php:

`/**
 * Add blocks link to back end
 */
add_action( 'admin_menu', 'linked_url' );
function linked_url() {
add_menu_page( 'linked_url', 'Reusable Blocks', 'read', 'edit.php?post_type=wp_block', '', 'dashicons-editor-table', 22 );
}

add_action( 'admin_menu' , 'linkedurl_function' );
function linkedurl_function() {
global $menu;
$menu[1][2] = "/wp-admin/edit.php?post_type=wp_block";
}`

**Comment by Svobi** [comment]
In WP 5.2.2 
`add_action( 'admin_menu', 'linked_url' );
function linked_url() {
add_menu_page( 'linked_url', 'Reusable Blocks', 'read', 'edit.php?post_type=wp_block', '', 'dashicons-editor-table', 22 );
}`
is enough to make it work.

**Comment by KokkieH** [comment]
We've had a request for this [on WordPress.com](https://en.forums.wordpress.com/topic/the-manage-all-reusable-block-need-an-icon-link-in-wp-admin-and-block-sh/) as well.

**Comment by frogdesk** [comment]
I think it's really disappointing that something that is so completely easy to implement, and so obviously beneficial to the usability of the software, has not been added when it was requested almost a year ago. There is absolutely no reason not to add this. The lack of things like this getting worked on is why people have such a nasty, awful, horrible taste in their mouths about Gutenberg.

**Comment by paaljoachim** [comment]
Actually it could instead be added as a tab to the Block Inserter alongside the tab for Patterns.
https://github.com/WordPress/gutenberg/issues/17335#issuecomment-587951100

**Comment by noisysocks** [comment]
Closing this in favour of https://github.com/WordPress/gutenberg/issues/13390 which proposes to show the link within the inserter.

It's possible that a _Reusable Blocks_ will end up in the WP Admin sidebar when there are more block-related screens in WP Admin. For example:

- Blocks
  - Reusable Blocks
  - Block Directory
  - Block Patterns
  - Reusable Blocks

Something along these lines was proposed in [this comment on Make/Design](https://make.wordpress.org/design/2019/07/11/block-directory-in-wp-admin-concepts/#comment-25907).

https://github.com/WordPress/gutenberg/issues/15549#issuecomment-518276908 is a suitable workaround for folks who desire this functionality.
