### ISSUE TITLE
Format type no use when foucs the end of text

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#15556]
**Describe the bug**
Format type no use when foucs the end of text

**To reproduce**
1. create a paragraph block
2. type some text
3. select some texts & click blod format to make then strong
4. foucs in then end of these text & type something

**Expected behavior**
the new text should continue to use the style

**Screenshots**
![bug gif](https://raw.githubusercontent.com/QiShaoXuan/Q-gutenberg/master/bug.gif)

**Add**
The program is happended in [https://wordpress.org/gutenberg/](https://wordpress.org/gutenberg/) and my project which depend gutenberg, but not happen in my woedpress admin`s editor

**Comment by youknowriad** [comment]
I don't think that's necessarily a bug. When you have format boundaries, caret position can be "in" or "out" of the format (you can even have more than 2 meanings for the same caret position). The way we solve this is by allowing you to go in and out of boundaries using arrow keys. 

Clicking a position is ambiguous, there's no way to know whether the user wants to click inside the boundary, outside the boundary (what level of boundary if there are multiple ones).

cc @ellatrix

**Comment by QiShaoXuan** [comment]
I report this bug because I found it is normal in wordpress admin, and this is same computer and  browser.
![bug](https://raw.githubusercontent.com/QiShaoXuan/Q-gutenberg/master/bug2.gif)
