### ISSUE TITLE
create block instance according to block-template (in php)

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#15562]
I am moving a custom post type from old-style meta boxes to a "locked block template" in my theme. For new posts this works very well. 
The Problem: already existing posts do not include the blocks defined by the template. 
I would like to add those blocks programatically on the server side (php). I can check if $post has the needed block via `has_blocks( $post->post_content)`, but I can't find a way to add the block in case it is not there. 
Any help is appreciated!

**Comment by youknowriad** [comment]
Blocks are saved as just HTML, did you consider just adding the HTML of the blocks to `post_content`?

Also note that gor general help requests, it's better to post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
