### ISSUE TITLE
transform multiple selected blocks to columns

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#15560]
**Is your feature request related to a problem? Please describe.**
Right now when selecting two paragraphs we get the option to transform them into a quote or a list block, and these are the only options.

**Describe the solution you'd like**
It would be great to be able to transform the two selected blocks into a columns block, and have each column filled by one of the blocks, columns left to right, filled by selected blocks top to bottom.

This can work potentially for more than two paragraph blocks too, but not indefinitely, four probably being the upper limit.

**Comment by youknowriad** [comment]
This should be easy to build but I wonder if it's really an interaction users are looking for. I'll add a "Needs Design Feedback" to get more opinions.

**Comment by kjellr** [comment]
If it's not too difficult to explore, I do think this would be valuable to try out. I did notice in one of the [recent user tests](https://make.wordpress.org/test/2019/05/08/gutenberg-usability-testing-for-april-2019/) that someone looked in the Transform menu for this purpose. 

It's sort of analogous to the "Group" functions in #14908. Limiting this to paragraphs only may be a simple way to get us started, but I can see users wanting to do this for other blocks as well.

**Comment by gziolo** [comment]
@getdave since you spend a lot of time exploring #14908, could you share your insights related to this proposal?

**Comment by mapk** [comment]
Looks like a duplicate was opened? https://github.com/WordPress/gutenberg/issues/16504

The other issue has more visual exploration and design feedback. I'm closing this one in favor of the other.

**Comment by kjellr** [comment]
Oh wow, good call. 😄 I forgot about this one.
