### ISSUE TITLE
CustomTemplatedPathPlugin does not support replacing multiple template tags.

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#15567]
**Describe the bug**
When using the `CustomTemplatedPathPlugin`, if you specify more than one replacement tag, only the first replacement tag is replaced.

**Expected behavior**
All tags to be replaced.

Here: https://github.com/WordPress/gutenberg/blob/94d48e09dcfb547ad1b142d137a51a378d57077f/packages/custom-templated-path-webpack-plugin/src/index.js#L42

If I changed the return to be `path = path.replace(...` it works as expected.

**Comment by nerrad** [comment]
To be clear, you mean when you do something like this in the configuration object:

```js
plugins: [
		new CustomTemplatedPathPlugin( {
			basename( path, data ) {
				/** contents **/
			},
                        anothertag( path, data ) {
                                /** contents **/
                        },
		} ),
	],
```

The `[basename]` tag will parse but not `[anothertag]`?

**Comment by TimothyBJacobs** [comment]
Yes, exactly that.
