### ISSUE TITLE
Missing Embed Blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15579]
**Describe the bug**
The FunnyOrDie.com and Photobucket Embed Blocks no longer appear in the block inserter. Not sure about FunnyorDie but the Photbucket Embed is still definitely valid and works in the Classic Editor.

Both blocks were there in WP5.1

**Expected behavior**
If the Embeds are valid then there should be a block for them, just like all the other Embed blocks.

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Browser: Firefox Quantum 66.0.5
- Version: WP 5.2

**Comment by Soean** [comment]
Removed in #12759

**Comment by maddisondesigns** [comment]
Then why does the Photobucket embed still work in 5.2 with the Classic Editor?
Try pasting this Photobucket url into the Classic Editor:
`https://i1192.photobucket.com/albums/aa339/henriekegansevoort/SAM_5012.jpg`

**Comment by maddisondesigns** [comment]
Never mind. Just doing some more testing and it looks like it automatically converts any img url to a proper `img` tag. I wasn't aware of that. I'll close this one.
