### ISSUE TITLE
Add a drop zone to the rendered image in the Image block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#15588]
**Is your feature request related to a problem? Please describe.**
I should be able to drag an image file and drop it over an uploaded image in the Image block to easily replace the current image.

**Describe the solution you'd like**
When I drag an image file over an existing image, the drop zone should appear where I can drop the new image to upload. Upon releasing the file, the rendered image is replaced with the image file I dropped in.

Once learned, this experience would make switching out images within the Image block much easier to do, requiring just one action - instead of selecting on the block, clicking the "Edit image" toolbar control, then dragging in an image.

**Comment by swissspidy** [comment]
This already exists since #14983

**Comment by richtabor** [comment]
Sweet!
