### ISSUE TITLE
Since a recent update in wordpress.com, I can't convert block to reusable block, or edit previously created one…

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#15580]
**Describe the bug**
Since a recent update in wordpress.com, few day ago,
I can't convert block to reusable block, or edit previously created one…

**To reproduce**
1. Go to editor
2. Select any reusable block
3. Click the edit button
4. The button is disabled…

**Expected behavior**
We should be able to convert to "reusable block" or "edit" previously created one…

**Screenshots**
Edit button unusable :
- https://scontent.fbru1-1.fna.fbcdn.net/v/t1.0-9/60033393_10218933516557856_8512449920236519424_o.jpg?_nc_cat=106&_nc_ht=scontent.fbru1-1.fna&oh=c609b984a77510d2f45a50b5280bf622&oe=5D55F51F

Missing "Add to Reusable Block" in three vertical point (happened two ago, but it seems that now it’s corrected)…

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome & FireFox (same problem)
 - Version: last version.

**Additional context**
- I use wordpress.com and the Gutenberg used by them…
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by swissspidy** [comment]
Does this also happen on a self-hosted WordPress site? Have you reported this to WordPress.com in case it's a problem specific to their platform?

**Comment by Nemzag** [comment]
Hi, 
1. I don't know if it happen in a self‑hosted WordPress site, I don't have one…
2. I didn't reported to WordPress.com, I don't know it's a problem coming vrom their platform…

**Comment by youknowriad** [comment]
I'm going to close this right now as we can't reproduce without more details. I'd suggest you to contact the support of WordPress.com to help you debug and find the issue.

**Comment by Nemzag** [comment]
I contacted some time ago, and they corrected the bug next day.
Hi still have the bug of not saving, with some very huge content…

**Comment by youknowriad** [comment]
@Nemzag Do you have an issue about that? Also, if they can help you debug, that would also benefit us in finding ways to reproduce the issue.
