### ISSUE TITLE
Best practice/approach to execute JS after your custom block loads in the editor?

### ISSUE THREAD

**Issue by mashedcreative** [WordPress/gutenberg#15591]
Hi, I've just dived into Gutenberg, most of the time I can use the existing blocks to create much of the layouts I need, but I've been looking further into custom blocks.

I'm integrating Google Maps JS API into a custom block/plugin, but I need to load the JavaScript and execute the callback function after the block loads in the editor.

i.e. from Google (simplest implementation)...
`https://maps.googleapis.com/maps/api/js?key=xxxxx&callback=initMap`

So usually we can add the JS in the `enqueue_block_editor_assets` hook, but this happens too early, and the editor errors with `Uncaught (in promise) TypeError: Cannot read property 'firstChild' of null` as it can not see the `#map` element.
The `initMap` function is in another JS file called `map-and-address.js` (the first enqueued script). The `initMap` is called, however, the `#map` element is null.

`<div id="map">TEST</div>` is located in the `edit` function.

So my question is what is the best approach when working with Gutenberg blocks, when you need to execute JS after the block loads or can be seen?

**Example:**
```
var map;
function initMap() {
  alert(document.getElementById('map')); //null
  map = new google.maps.Map(document.getElementById('map'), {
    center: { lat: -34.397, lng: 150.644 },
    zoom: 8
  });
}
```

```
function blocks_map_and_address_editor_assets() {
	wp_enqueue_script( 'blocks_map_and_address-script',
		plugins_url( 'map-and-address.js', __FILE__ )
	);
	wp_enqueue_script( 'google-maps-api', 'https://maps.googleapis.com/maps/api/js?key=xxxxx&callback=initMap', array(), '1.0.0', false);
	
	wp_enqueue_script( 'blocks_map_and_address-editor-script',
		plugins_url( 'build/index.js', __FILE__ ),
		array( 'wp-blocks', 'wp-element', 'wp-editor', 'wp-components', 'wp-dom-ready' )
	);
	wp_enqueue_style(
		'blocks_map_and_address-editor-style',
		plugins_url( 'editor.css', __FILE__ ),
		array( 'wp-edit-blocks' ),
		filemtime( plugin_dir_path( __FILE__ ) . 'editor.css' )
	);
}
add_action( 'enqueue_block_editor_assets', 'blocks_map_and_address_editor_assets' );```

**Comment by swissspidy** [comment]
Have you tried [`componentDidMount`](https://reactjs.org/docs/react-component.html#componentdidmount) in your edit component?
