### ISSUE TITLE
Promoting Gutenberg page

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1559]
At the Community Summit there was discussion about creating a marketing page. This is an issue to begin that.

## Why?
We need to get information about Gutenberg out to as many people as possible, this page is aimed at doing that. Think of it as an advert for Gutenberg.

## What?
The contents of this we need to work out. In the design I identified areas we probably wand to call out:
- Download
- Contribute
- Test
- Learn more

I also think as we discussed at the summit having a demo, whether we do that or have a video is something to talk about.

## The design
I have worked on a really modular design for this. The brief after talking to people seemed to be:
- A design that can adapt to content: we may move things around and also not have some content showing at different times.
- Ease the 'shock of the new' feeling a bit by linking to WordPress branding.
- Reflect the styling of Gutenberg. Thanks to @jasmussen for feedback on that.

Here is what I have and note, it can adapt with different content - showing 3 versions of same design:

![v1](https://user-images.githubusercontent.com/253067/27641709-8f61dd14-5c14-11e7-8fa2-c9c472486fdc.png)

![v1-combo1](https://user-images.githubusercontent.com/253067/27641712-93ddede2-5c14-11e7-99ec-edc2ddff599e.png)

![v1combo-2](https://user-images.githubusercontent.com/253067/27641715-9673bb5e-5c14-11e7-8493-d88dc3351223.png)

Here are all the designs larger: https://cloudup.com/cnt6aCh_3rD

## Where?
Where we actually put this is a bigger question. Maybe we use some fun url ( getgutenberg )? Thats a point for discussion. If we could make this actually using Gutenberg for the main content area that would be amazing.

## When?
I feel the time should be asap on this, we can get the minimal version up and add to it overtime. The benefit in that.

**Comment by mtias** [comment]
Definitely sounds we should build this with gutenberg. It can also become the demo-content (apart from serving it as a page) that you can edit in the plugin.

**Comment by karmatosed** [comment]
> It can also become the demo-content (apart from serving it as a page) that you can edit in the plugin.

What an awesome idea!

**Comment by jasmussen** [comment]
I'm going to try and put together sort of a min press kit today. For starters, an FAQ and a stack of screenshots, and at some point we should have a fresh video also.

See also #1419

**Comment by buzztone** [comment]
The contents of this page could also be used as the basis for an updated plugin readme.txt that focuses much more on giving general WP users, quickly & easily, the info they need to decide to download, test & give feedback on the Gutenberg Editor.

**Comment by karmatosed** [comment]
I am assigning this to myself as starting to work on this. Where it goes hasn't been decided but we can move on with getting the design into a basic theme and then take from there.

**Comment by cedon** [comment]
Some of this might be dup'd elsewhere, but how about a "Why Gutenberg?" section? I discovered Gutenberg by accident when I saw a bunch of flames towards it. My initial reaction was "Dear God, what could be so horrible about this thing?" TBH, I was immediately reminded of Medium when I fired up the beta plugin.

But I think a "Why" section explaining the evolution from TinyMCE to Gutenberg. It could, and I think should, answer the question of how the transition will be planned. Will it be a switch flip and the next version of WP you install is Gutenberg and TinyMCE is a memory, or will it be something a user can choose to have as their editor and still have TinyMCE to fall back on or use outright?

**Comment by jasmussen** [comment]
> Some of this might be dup'd elsewhere, but how about a "Why Gutenberg?" section? 

Solid point. We actually do have that, [in the readme](https://github.com/WordPress/gutenberg#why), but it can be a bit hard to find and definitely worth surfacing, and even expanding, on a dedicated site. 

> explaining the evolution from TinyMCE to Gutenberg

[The FAQ](https://github.com/WordPress/gutenberg/blob/master/docs/faq.md) is also a bit buried. But you bring up a point that's answered there, and should probably be higher up on the list. And that is the fact that [TinyMCE isn't being dropped at all](https://github.com/WordPress/gutenberg/blob/master/docs/faq.md#is-gutenberg-built-on-top-of-tinymce). The current WordPress editor uses TinyMCE for the entire content area. Gutenberg uses TinyMCE for every textfield. Paragraphs, headings, lists, captions, citations — each of those uses an instance of Tiny to provide rich text. The benefit here is that you can write a custom block, with a couple of input fields (perhaps name, email), and decide that the larger "description" field can benefit from being rich text. You simply apply the `editable` attribute to that field, and Gutenberg takes care of applying Tiny behind the scenes. In that vein it's like the new WYSIWYG widget.

**Comment by StaggerLeee** [comment]
I have one suggestion to you.

- Take 10-20 plugins from repository, with most active installs.
- Explain to plugin developer(s) what they win, what they lose with Gutenberg. Compared to what they had BG (Before Gutenberg)
- Explain to their Users what they win, what they lose.

**Comment by cedon** [comment]
> Solid point. We actually do have that, in the readme, but it can be a bit hard to find and definitely worth surfacing, and even expanding, on a dedicated site.

I think this needs to be front and center. Especially given all the vitriol currently out there about Gutenberg and the fact there are even plugins right now to [strip it out](https://wordpress.org/plugins/glutenburg-free/). 

> And that is the fact that TinyMCE isn't being dropped at all. The current WordPress editor uses TinyMCE for the entire content area. Gutenberg uses TinyMCE for every textfield.

Will the old editor in its entirety be still available though for users who do wish to revert? That's the main concern I see with people. Granted a lot of it seems to be people not recognizing beta software is not anywhere near a final product (e.g. complaints about the paste bug which #2180 discusses). A lot of it seems to be, and I made this mistake too, is thinking of TinyMCE *is* the old editor as opposed to being a component behind it.

I think the decision needs to be made/publicized ASAP on if Gutenberg will be an option in 5.0 or mandatory in 5.0 in terms of using it. My personal view is that it should be a choice at least at the 5.0 level and maybe at 6.0 make it the only option.

Another thing I forgot to mention, and @StaggerLeee touched on, is that plugin developers need to be brought into the fold now. Especially ones who are using meta boxes and such like Yoast. I like StaggerLeee's suggestion about specifically targeting top 10-20 plugin makers.

Guides should be written on how to port over to Gutenberg should be constructed ASAP. Especially if the developer needs to start learning something new (e.g. React, JavaScript, etc.).

**Comment by jasmussen** [comment]
> Especially given all the vitriol currently out there about Gutenberg and the fact there are even plugins right now to strip it out.

That plugin is built by a Gutenberg contributor, and in good faith. I think this is one of the strengths of WordPress. Whether or not the old editor will be bundled with WordPress alongside Gutenberg (I don't know the inner machinations of what this might take), we can know for sure that there will always be a plugin available to restore it.

We are working as hard as we can for it to be _ready_ and _tested_, so it _can_ be in 5.0. But Gutenberg in 5.0 is not a done deal. If it's not ready, it's not ready. 

See also https://github.com/WordPress/gutenberg/blob/master/docs/faq.md

> Guides should be written on how to port over to Gutenberg should be constructed ASAP. Especially if the developer needs to start learning something new (e.g. React, JavaScript, etc.).

Agree completely. I have an updated design doc with best practices hopefully going out today, and the beginnings of block-creation documentation is linked from the README and lives here: http://gutenberg-devdoc.surge.sh/

**Comment by StaggerLeee** [comment]
Hi @jasmussen 
can you make some more advanced examples in docs ? Varying from light advanced to at least one very advanced. Do not care what people would use most, just imagine few blocks and make example(s).

I fond some on Github too, one of seems as old and gave error.
Seems as not a progress to show only one example of already existing block in Gutenberg (text block).

**Comment by jasmussen** [comment]
We should have many examples, both in the design doc (best practices) and for the blocks themselves.

All of this is not for a lack of desire to get this stuff done — everything is important. But we are stretched for resources.

**Comment by cedon** [comment]
> That plugin is built by a Gutenberg contributor, and in good faith. I think this is one of the strengths of WordPress.

That's good. I just noticed it after seeing some harsh talk about Gutenberg and went to grab the beta to see what it was all about.

> Whether or not the old editor will be bundled with WordPress alongside Gutenberg...

I do think, at least at the 5.x level of WordPress, it should be included. Gutenberg could/should be the default with a switch available in `Settings` -> `Writing` to switch between the two. At the 6.0 level, make it the only one and keep the reversion plugin going.

My case for this is that this gives the user the ability to switch back without having to add a third step. Granted a lot of WP installations are managed by 3rd parties who can easily install the plugin, regular everyday users may not have the working knowledge to locate the plugin and install it themselves. Plus there's also WordPress.Com to think about.

I can see this going the same way Windows 8 did with forcing the Metro UI onto people without the ability to fall back to Aero UI from Windows 7. That was the #1 reason I never upgraded to it myself and I've run every version of Windows from 3.x to WinNT to 2000 and beyond. This could lead to some people sticking with the last 4.x version which, in my view, sets up a bad security situation.

> I have an updated design doc with best practices hopefully going out today, and the beginnings of block-creation documentation is linked from the README

Looks good. In glancing through it, some screen shots would definitely help. But also maybe some explanation as to how things relate to the current model (i.e a Rosetta Stone) but I am guessing that this kind of stuff will be added later already.

**Comment by cedon** [comment]
Another thought I had, which you and I talked about in Slack @jasmussen, is that some of these blocks have no context to them. The example I used in slack is the *Cover Text* block. What is "cover text"? What is the purpose of this text block? Why would I use it? Because looking at it in both the visual and text editors, it looks just like any generic `<div>` element with a class of `wp-block-cover-text` attached to it.

**Comment by jasmussen** [comment]
Good thoughts, cedon. 

Cover Text is one of the blocks that I'm not _convince yet_ needs to exist as a separate entity. We may decide that the background color feature that headlines it, deserves to be moved to the plain Text block instead. 

However your point is still good — maybe we should separately open a ticket to add popover descriptions to each block in the inserter?

**Comment by karmatosed** [comment]
Closing as the initial page is now up at: wordpress.org/gutenberg
