### ISSUE TITLE
Underline formatting is removed on paste

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#15590]
**Describe the bug**
Any underline formatting in text that's pasted into the block editor is removed.

**To reproduce**
1. Open Google Docs / LibreOffice / Microsoft Word
2. Type some text that contains underline formatting
3. Copy the text
4. Create a new post in WordPress using the block editor
5. Press <kbd>Cmd</kbd>+<kbd>V</kbd>

**Expected behavior**
The text should appear in the block editor with underline formatting.

**Desktop**
 - OS: macOS 10.14.4 
 - Browser: Safari 12.1
 - WordPress Version: WordPress 5.2.0

**Comment by kadair** [comment]
Hi, I'd like to take this on as a first issue. 

I believe the solution is straightforward: Add a 'u' tag to the phrasing content schema to cover text underlined using a 'u' tag (Word and LibreOffice), and add a condition for 'text-decoration: underline' in the phrasing content reducer to cover text underlined using the style tag (Google Docs). 

For tests, can I add directly to the google-docs and ms-word-styled fixtures?
Thanks for your time!

**Comment by noisysocks** [comment]
Thanks for volunteering @kadair! ✊

That approach sounds reasonable to me, and, yes, using the existing test fixtures is a great way of verifying this change.

**Comment by kadair** [comment]
Sorry, I've had a whole host of problems on my new Windows machine and my old computer is done. If anyone would like to take this on, feel free. I have the solution but cannot currently build Gutenberg to test it. I'll keep trying.

**Comment by noisysocks** [comment]
@kadair: Jump into the #core-editor channel on the [Making WordPress Slack](https://make.wordpress.org/chat/) and ask for help! There's lots of us there that can help you get set up 🙂

**Comment by ellatrix** [comment]
That's because we don't really support underline, which would be inline CSS. Only semantic formatting will be pasted in Gutenberg. I'd suggest to close this issue.

**Comment by noisysocks** [comment]
Alright, makes sense. What about strikethrough, @ellatrix? (see https://github.com/WordPress/gutenberg/issues/15805)

**Comment by ellatrix** [comment]
@noisysocks doesn’t that already work? I believe I merged a PR a while ago that fixed strike through pasting from Google Docs.

**Comment by noisysocks** [comment]
@ellatrix: I dug into it and turns out it just wasn't working in Safari or JSDOM. Opened https://github.com/WordPress/gutenberg/pull/17187 to fix.
