### ISSUE TITLE
Fix the Pinned Plugins button styles when toggled

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15608]
After the changes to the header Settings button in https://github.com/WordPress/gutenberg/pull/14475 (my bad) the Pinned Plugins button styles are broken when the button is toggled:
- the different left margin makes the buttons "jump"
- colors of the SVG icon are inverted

The Settings button and the Pinned Plugins button inherit some common styles from `packages/edit-post/src/components/header/style.scss` but then the Pinned Plugins one has a few specific rules that need to be updated after the changes in #14475.

To reproduce:
- install a plugin that provides its own Sidebar 
- open the Plugin sidebar from the More menu
- click the "Pin to toolbar" button in the plugin Sidebar
- observe the pinned button styles when clicking on ti

Animated GIF:

![toggle](https://user-images.githubusercontent.com/1682452/57647027-426c2680-75c2-11e9-9244-b913777545a4.gif)

**Comment by simison** [comment]
This got reported here too https://github.com/Automattic/jetpack/issues/13212#issuecomment-522559329

Looked broken in Gutenberg 6.2.0 and 6.3.0 — this should be fixed in future versions, correct?
