### ISSUE TITLE
Consider new icons for "Group" and "Ungroup"

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#15602]
When the Group block was originally introduced, it was positioned as a "Container" or "Section" block. The icon was designed to represent that idea: 

![Frame 3](https://user-images.githubusercontent.com/1202812/57637848-6441bb00-757a-11e9-9355-a7cac2ff61e9.png)

Since merge, the block has been renamed to "Group", and work is in progress (#14908) to add group and ungroup actions alongside it. With this new framing, we should reassess whether or not the current icon best represents the block's functionality. 

For #14908, some initial thought was put into the icons for those actions, and the question was raised whether or not the actual block icon should be revised to match. Since decisions around those icons aren't essential to getting the functionality merged in, I wanted to break this out into a separate thread for discussion. 

Oddly enough, Material doesn't include icons for Group and Ungroup. [The draft icons](https://github.com/WordPress/gutenberg/pull/14908#issuecomment-482196334) used in #14908 are custom ones: 

![Frame 5](https://user-images.githubusercontent.com/1202812/57638927-d0252300-757c-11e9-82a7-5e64c0b10967.png)

These are loosely based on the closest thing we have to icons for "single/group" right now: The image and gallery icon: 

![Frame 6](https://user-images.githubusercontent.com/1202812/57639035-09f62980-757d-11e9-9ab4-74417b4facfd.png)

The "Group" icon is structured similarly to the Gallery icon, but the "Ungroup" one is a little more specific, showing two entirely separate cards being pulled apart. 

A quick glance at the icons used in other applications shows this "layered vs. apart" treatment is fairly common: 

<img width="120" alt="55973946-9a76dc80-5c54-11e9-9600-5e221d168f09" src="https://user-images.githubusercontent.com/1202812/57639223-7113de00-757d-11e9-9722-8837a2e706fd.png">
<img width="192" alt="55973947-9a76dc80-5c54-11e9-9bac-2419ae696800" src="https://user-images.githubusercontent.com/1202812/57639224-7113de00-757d-11e9-8bad-b252ab98e01a.png">
_(Keynote, Sketch)_

Those examples also show a selection outline. It may make some sense to try adding that here too. 

I'm dumping all my other explorations below for reference: 

<img width="659" alt="Screen Shot 2019-05-13 at 10 08 52 AM" src="https://user-images.githubusercontent.com/1202812/57628031-26876700-7567-11e9-9f74-bd08c2251e86.png">

As noted [in the other thread](https://github.com/WordPress/gutenberg/pull/14908#issuecomment-491836598), versions 1, 2, and 7 are my favorites for now. @melchoyce [liked 2, along with 9 and 10](https://github.com/WordPress/gutenberg/pull/14908#issuecomment-491854912). @mapk [felt that 8 best represented the actions. ](https://github.com/WordPress/gutenberg/pull/14908#issuecomment-491869532)

Any further ideas/reactions are greatly appreciated!

**Comment by mtias** [comment]
1 and 2 seem the clearest and most straightforward to me. 9, 10, 11 feel like they could be used for other layout tools (rows / columns).

**Comment by kjellr** [comment]
We actually use (the outline version of) that layers one for the individual column block. 😄 

![Screen Shot 2019-05-15 at 7 45 10 AM](https://user-images.githubusercontent.com/1202812/57773527-3bd6cf80-76e6-11e9-96f1-adfbc5d3e301.png)

**Comment by mapk** [comment]
I really like the "grouped" version of the icon to include an outline, but I think the box style shown above isn't great. I do like the examples where the box outline has nodes in the corners.

I lean toward 8 or 5 because any overlapping icons tend to communicate a _grouped_ item to me. If we can modify the outline in 8 like below, I think that might help. This is pretty rough just for conversations.

![icons](https://user-images.githubusercontent.com/617986/57794952-b0ffd000-76f9-11e9-9da1-805b5d943827.png)

**Comment by kjellr** [comment]
> If we can modify the outline in 8 like below, I think that might help.

Unfortunately, I haven't been able to make something like this this work given the constraints of the pixel canvas, and the size and line weight [requirements of Material Icons](https://material.io/design/iconography/system-icons.html). 

The closest I can get is something like these, and I think they're a little fiddly and weird looking.

![Screen Shot 2019-05-15 at 2 35 40 PM](https://user-images.githubusercontent.com/1202812/57800171-bfacae00-771e-11e9-9a33-ff6e46b5789d.png)

![Screen Shot 2019-05-15 at 2 36 11 PM](https://user-images.githubusercontent.com/1202812/57800204-d0f5ba80-771e-11e9-981a-19df73055b7e.png)

--

It seems like we're pretty all over the place. 😄 The most-liked one from above has been number 2, but @mapk disliked that it reminded him of pathfinder tools in Illustrator (which is totally valid and true, but perhaps not a universal issue):

![Screen Shot 2019-05-15 at 2 40 36 PM](https://user-images.githubusercontent.com/1202812/57800441-6f821b80-771f-11e9-9fc6-7c93c642cf86.png)

The more I stare at it, the more I'm not sure it's right. 

@drw158, do you have any thoughts for this one?

**Comment by jemlovestodraw** [comment]
I like option 8 above. For me, the box around the grouped items makes the distinction between grouped and un-grouped much clearer. Could be worth a look at Font Awesome for inspiration:
Group https://fontawesome.com/icons/object-group?style=regular
Ungroup https://fontawesome.com/icons/object-ungroup?style=regular
But I'm not a fan of the fiddly transform control boxes on the corners of those.

**Comment by strarsis** [comment]
+1! Being able to group a large number of selected blocks into a new group block would be really helfpul.

**Comment by mapk** [comment]
Similar to number 8 above, how does this look?

![Screen Shot 2019-05-24 at 3 47 39 PM](https://user-images.githubusercontent.com/617986/58360036-5245ff00-7e3b-11e9-9f29-30627f3cd814.png)


![Screen Shot 2019-05-24 at 3 48 17 PM](https://user-images.githubusercontent.com/617986/58360048-5eca5780-7e3b-11e9-877a-6b14e19d7efc.png)

**Comment by kjellr** [comment]
@mapk I find the shape in the Group version of that just a little awkward, personally. Here are a few more variations on that: 

<img width="777" alt="Screen Shot 2019-05-27 at 9 04 53 AM" src="https://user-images.githubusercontent.com/1202812/58421710-ab41ad00-805e-11e9-9e75-eb9b65f60429.png">

All of these use the handles from [Material's `format-shapes` icon](https://material.io/tools/icons/?icon=format_shapes&style=outline), which seems like a reasonable example to stick to. I like version 8D the best. 

(Also, I tried having the blocks stacked vertically, which would be more common in Gutenberg, but I felt that it read [too much like a `B`](https://cloudup.com/cSbc3EV7Skr)).

**Comment by mapk** [comment]
The handles from Material look good. Nice touch! I actually liked the stacked items in the shape of the B because of your relation to actual Gutenberg blocks. I removed the radius and kept it staggered. What do you think, @kjellr? Without all the rounded corners, I think it feels a lot better.

![Screen Shot 2019-05-28 at 1 24 15 PM](https://user-images.githubusercontent.com/617986/58509646-e8379d80-814b-11e9-8ab5-20e35abf0af9.png)

![Screen Shot 2019-05-28 at 1 21 16 PM](https://user-images.githubusercontent.com/617986/58509621-cfc78300-814b-11e9-85a8-9d3666147f81.png)

If that still doesn't sit well, let's go with **8D** from your mockups.

**Comment by kjellr** [comment]
I made a slight adjustment to include a bit of a rounded corner on the interior blocks: 

<img width="262" alt="Screen Shot 2019-05-29 at 9 34 38 AM" src="https://user-images.githubusercontent.com/1202812/58562427-381f6e80-81f7-11e9-8d77-da8aebbe0cdc.png">

Then I tried it out in context. I'm not particularly happy with it, personally. The handles look much too blocky — almost like it's a pixellated illustration of what we're going for: 

<img width="346" alt="Screen Shot 2019-05-29 at 9 45 41 AM" src="https://user-images.githubusercontent.com/1202812/58562475-51c0b600-81f7-11e9-94be-2e9322c13103.png">
<img width="338" alt="Screen Shot 2019-05-29 at 9 46 10 AM" src="https://user-images.githubusercontent.com/1202812/58562473-51c0b600-81f7-11e9-8f41-f293e332ee57.png">
<img width="415" alt="Screen Shot 2019-05-29 at 9 45 54 AM" src="https://user-images.githubusercontent.com/1202812/58562474-51c0b600-81f7-11e9-920b-794191508e1c.png">

I think straying from the Material example for those handles may be in our best interest after all. Something like this might work, but I need to double check when I'm on a non-retina screen later today (Since those handles are just 1px larger than the borders, I'm worried they may be blurry on some screens):

<img width="333" alt="Screen Shot 2019-05-29 at 10 03 58 AM" src="https://user-images.githubusercontent.com/1202812/58563525-50908880-81f9-11e9-883b-bbdc29ce719b.png">
<img width="332" alt="Screen Shot 2019-05-29 at 10 04 32 AM" src="https://user-images.githubusercontent.com/1202812/58563527-51291f00-81f9-11e9-9fb2-f32cf5a1f38a.png">
<img width="415" alt="Screen Shot 2019-05-29 at 10 04 22 AM" src="https://user-images.githubusercontent.com/1202812/58563526-50908880-81f9-11e9-82d7-59e172de7bc2.png">

**Comment by kjellr** [comment]
> Something like this might work, but I need to double check when I'm on a non-retina screen later today (Since those handles are just 1px larger than the borders, I'm worried they may be blurry on some screens):

Actually — looking at this on a non-retina screen, it's totally fine. 😄 So I think we're ok. 

My only remaining concern is that "Ungroup" doesn't really make much sense when it appears on its own. Does anyone have any thoughts or ideas about that? 

Thanks!

**Comment by melchoyce** [comment]
Maybe "Ungroup Blocks" would make it a tiny bit more clear?

**Comment by kjellr** [comment]
It sounds like we're feeling good about that last batch, possibly with the added "Blocks" label in the ellipsis menu item. I'll keep an eye on #14908 and create a PR for this after that's merged in.
