### ISSUE TITLE
Add a required attribute to the search block so empty searches aren't submitted

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#15600]
**Describe the bug**

The text field in the search block should be required so that empty or placeholder results are not submitted. 
This is also a [long-standing issue in core.](https://core.trac.wordpress.org/ticket/34886) (34886) that I hope could accompany this fix. 

cc @gibrown
**To reproduce**
1. Create a post or page
2. add a search block
3. publish the post or page
4. visit the post or page 

**Expected behavior**
an error message or notice stating that I'm submitting an empty form and a search term is required. 

**Additional context**
Comprehensive testing has been done by Pacello Group and made [some recommendations](https://developer.paciellogroup.com/blog/2019/02/required-attribute-requirements/); my understanding that adding the 'required' attribute to the input element alone is a great start to this. 

I've tested in firefox 66 on ubuntu; IE 11 and windows 10; and chrome and win 10 that by only adding the required attribute to the input element, visual messages for the user are displayed when the user submits a search that has a no value or a placeholder value.  

(filed as a CPL employee).

**Comment by gibrown** [comment]
+1000 yes please.

**Comment by skorasaurus** [comment]
I'm beginning to tackle this and would appreciate some accessibility feedback. 

I've only added `required` to the search input in [my branch](https://github.com/skorasaurus/gutenberg/tree/add/required-input-search-block). 


A test page with a couple search blocks is available at https://temp.cpl.org/testing-post/; I'll try to keep that page up to date with the latest commit in my branch https://github.com/skorasaurus/gutenberg/tree/add/required-input-search-block

(Because this is still a primarily PHP-based component, [there is not a storybook component for this.](https://wordpress.github.io/gutenberg/?path=/story/docs-introduction--page)). 

**Desired Effect:**
A user does not submit an search result without any input. In my humble opinion, there isn't a good use case to allow them to submit an empty search result. 

**What will when happen with this PR merged in:** 
_($label is what I'll use to describe whatever the label that is set in my 
 In a [previous PR](https://github.com/WordPress/gutenberg/pull/17983), I had added a default label of `search` (using an existing class for screen readers, `screen-reader-text`) when an editor removes the default label when editing a search block._ 



I've tested this with a couple browsers and screen readers ([NVDA and JAWS are two very popular screen readers](https://webaim.org/projects/screenreadersurvey8/)  - in my opinion, note that survey is arguably quite biased to self-selection although it a very thorough survey and the most comprehensive one that I know of); in my professional work at Cleveland Public Library, a remarkable majority of our users who use a screen reader use JAWS. 

**(User attempts to submit empty search by clicking on search button or pressing enter while focus is on search button):** 

On NVDA (default settings), Edge: 

screen reader announces: "$label edit required invalid entry, this is a required field, blank." 

On NVDA (default settings), chrome: 
screen reader announces: "please fill out this field alert"

On Android (using talkback, default screen reader), chrome: 
"please fill out this field alert"

**Comment by gziolo** [comment]
Closes with #18635
