### ISSUE TITLE
Consider reducing visual nudges and flashes like autosaving

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#15605]
This came up in the accessibility audit webinar. One person from the usability tests experienced issues with this causing a lot of cognitive load and impacting their experience. What could we do to ease that for everyone?

**Comment by karmatosed** [comment]
@youknowriad I wonder if your snackbar explorations could help this? One thing that strikes me is what balance can we find between knowing it's 'saving' and it flashing all the time. For those who are anxious knowing it's happening is assuring, however, if it is informing in a strong manner that's not at all assuring.

**Comment by aduth** [comment]
Am I correct in assuming context to be the pulsating "Saving" indicator?

![save](https://user-images.githubusercontent.com/1779930/57644360-f30a0400-7589-11e9-837f-1ea365786333.gif)

**Comment by karmatosed** [comment]
Yes, that is correct.

**Comment by sarahmonster** [comment]
That "Saving..." indicator is _very_ flashy. I could see how it might prove distracting. Does it only show up when a user clicks on the "Save draft" button, or does it self-initiate as well?

Do we need an indicator here at all? Do we have evidence that this indicator provides value to users? Could we try scaling it back to just showing the "saved" indicator, without the flashy animation? Does this animation respect users' `prefers-reduced-motion` settings?

My understanding here is that there are two different use cases:
- User initiates a save by pressing the "Save draft" button
- Auto-save triggers (I'm guessing this is on a time interval?)

In the former case, some kind of indication that something is happening is called for. Is it required for the latter case as well? Perhaps we need two slightly different flows to account for different user needs in either of those use cases.

**Comment by enriquesanchez** [comment]
Can we maybe get around all of these concerns if we just use the word "Saving..." without any flash or animation?

If we find that we still need a way to indicate that a process is happening, maybe the ellipsis "..." from "Saving..." can appear and disappear one by one, like a wave?

![2019-10-10 17-36-52 2019-10-10 17_37_36](https://user-images.githubusercontent.com/3276087/66611641-cd0e7d00-eb84-11e9-89e3-e8b168c563fd.gif)

There's more examples of minimal text-based spinners here: https://maxbeier.github.io/text-spinners/

**Comment by karmatosed** [comment]
I love the idea of pulsing or a wave.

**Comment by mapk** [comment]
It appears the Saving indicator is much slower now... and saving occurs so fast that it's hardly noticeable.

![save](https://user-images.githubusercontent.com/617986/81756014-67aea180-946f-11ea-85a4-e2bcf97545fd.gif)

I'm going to close this out for now.
