### ISSUE TITLE
Can not set new format across two format

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#15617]
**Describe the bug**
Can not set new format across two format

**To reproduce**
1. set bold format to some text
2. set italic format to some text before that 
3. set strikethrough format to text contain format above

Gutenberg-js will throw error: `Uncaught TypeError: Cannot read property 'nodeType' of null`
This case happened in all gutenberg project including [https://wordpress.org/gutenberg/](https://wordpress.org/gutenberg/)

**Screenshots**
![bug-image](https://raw.githubusercontent.com/QiShaoXuan/Q-gutenberg/master/bug3.gif)

**By the way**
[#15556](https://github.com/WordPress/gutenberg/issues/15556) close but not resolve
[#15166](https://github.com/WordPress/gutenberg/issues/15166) no one reply and resolve

**Comment by gziolo** [comment]
I was able to reproduce it. It's a bug which needs to be fixed.
