### ISSUE TITLE
Auto added default block can break Undo / Redo history

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15610]
Splitting this out from #15543. Yep this was also previously noted for a similar issue when pressing Enter at the beginning of a block. 

I've seen there are similar issues already but seems to me no one of them describes this specific behavior.

See https://github.com/WordPress/gutenberg/pull/15543#issuecomment-491940999 for a first scenario. Also, try the following steps:
- add a paragraph with some text
- move the caret at the beginning of the entered text
- press Enter
- a default block gets added _before_ the paragraph
- click Undo
- at this point, the paragraph is duplicated: looks like the default block has been replaced with the paragraph but the original paragraph is still there

Animated GIF to illustrate the issue:

![enter beginning](https://user-images.githubusercontent.com/1682452/57649284-1bb0ee80-75c8-11e9-8f18-4581eeba083c.gif)

**Comment by ehti** [comment]
Can't reproduce this as of Gutenberg 7.9.1. About to close but thought to check with you first @afercia if you're still able to repro.

Thanks

**Comment by skorasaurus** [comment]
not able to reproduce either; please reopen if you're still experiencing this.
