### ISSUE TITLE
When I click Edit Image, gutenberg displays an image insert instead

### ISSUE THREAD

**Issue by achmedislamic** [WordPress/gutenberg#15614]
**Describe the bug**
I have old post that is not using gutenberg. So, I convert that post to Blocks. When I convert to Blocks, select an image and click Edit image, Gutenberg displays image insert instead of editing that image like always.

**To reproduce**
1. Open one of your old post
2. Convert that post to Block
3. Select an image and click Edit Image
4. Gutenberg now wants you to insert image rather than editing the selected image.

**Expected behavior**
Gutenberg should shows image edit modal.

**Screenshots**
![image-bug-gutenberg](https://user-images.githubusercontent.com/25688207/57657628-7e2cdd80-760e-11e9-8033-e51fbcdd94ba.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 October 2018 Update
 - Browser Google Chrome
 - Version 74

**Additional context**
- Using Wordpress 5.2

Sorry for my bad english.

**Comment by swissspidy** [comment]
That is actually a feature... See #14142.

**Comment by achmedislamic** [comment]
I still don't get it why this is a feature. I really just want to edit the image like the image size, edit the Alt Text, description, etc. If I want to upload a new image, I just create new image block.

And I just realize the image that I used is an old image that I get from Blogger. I migrate my Blogger.com to Wordpress and the image is still from Blogger.

Sorry for my bad english.

**Comment by swissspidy** [comment]
Oh, I see.

Alt text and image size can be edited through the block sidebar on the right side:

<img width="1257" alt="Screenshot 2019-05-13 at 17 32 02" src="https://user-images.githubusercontent.com/841956/57662637-2908b180-75a5-11e9-9159-b5e7b5a6cb2a.png">

The caption can be added right below the image:

<img width="691" alt="Screenshot 2019-05-13 at 17 33 21" src="https://user-images.githubusercontent.com/841956/57662650-3d4cae80-75a5-11e9-9080-dfb29b7ffedb.png">

Although there indeed is no link to edit the attachment as a whole 🤔  That is a bit odd.

**Comment by achmedislamic** [comment]
Oh, this is my bad ☹
![image](https://user-images.githubusercontent.com/25688207/57662953-7a0bba80-7624-11e9-8c18-dc3043ddab3a.png)

I always use the Edit image modal to edit my image. I rarely used block sidebar.
But still, the "Edit image" button should show Edit image modal or highlight the block sidebar. It doesn't seems right the button says "Edit image" but in reality, user see the image upload block.

**Comment by swissspidy** [comment]
Agreed.

It's more "Replace image" than "Edit image". I guess that label should be replaced. Plus perhaps the pencil could be brought back somewhere to allow opening the media modal.

**Comment by kjellr** [comment]
In a recent release of Gutenberg (5.5 I believe), that edit icon was swapped out for a more appropriate  "swap" icon: 

<img width="651" alt="Screen Shot 2019-05-14 at 3 23 53 PM" src="https://user-images.githubusercontent.com/1202812/57725933-4fd5ef00-765c-11e9-8cce-e5399d85e6e0.png">

Image details like size/caption/etc. still live in the sidebar, since that's the usual place for those sorts of controls. Since the edit icon confusion has been addressed already, I'm going to mark this as closed, but feel free to let me know if there's another issue that still needs addressing!

**Comment by swissspidy** [comment]
@kjellr Correct me if I am wrong, but there still seems to be no way to edit the attachment in the media library. Also "Edit image" is misleading when the button is clearly for _replacing_ the image, not editing it. Shouldn't that be addressed?

**Comment by kjellr** [comment]
Rephrasing that tooltip is certainly something we can do. I'll reopen this ticket to track that. 

For editing the image in the media modal, I feel like most of that functionality should happen within Gutenberg eventually. I know there are tickets related to size + cropping (#13748, #14829) for instance — if there are other specific things, they should probably be funneled into individual issues.

**Comment by mapk** [comment]
There's a new "Replace media" component being built which should be merged soon. It will solve this issue completely. I'm closing this issue because it's actually a feature, and will be solved further with this other PR. https://github.com/WordPress/gutenberg/pull/16200
