### ISSUE TITLE
Disabled block switcher icons are blurry

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#15629]
When the block switcher is disabled, the block icon inside of it appears smaller than it should, resulting in some blurry icons on non-retina screens. Here's the Container block icon for instance, appearing at `20px` wide: 

![Screen Shot 2019-05-14 at 9 43 41 AM](https://user-images.githubusercontent.com/1202812/57702828-dd014f80-762c-11e9-906a-f9116e1e2e30.png)

For comparison, here's a non-disabled icon, which renders at the correct `24px` wide: 

![Screen Shot 2019-05-14 at 9 47 24 AM](https://user-images.githubusercontent.com/1202812/57703067-4bdea880-762d-11e9-8385-76c274ccd18f.png)

The issue appears to be that when the toolbar icon appears disabled like that, the IconButton parent gets a `has-text` class, which adds a `4px` right margin to the child SVG. Removing that rule renders the icon at the correct size:

![link](https://user-images.githubusercontent.com/1202812/57703637-74b36d80-762e-11e9-846a-4c0e5239fd5e.gif)

To fix, I suppose we can negate this with an extra style rule inside of `editor-block-switcher__no-switcher-icon`, but I'm wondering if this `has-text` class is needed here in the first place? Should that be removed in this case?

cc @jasmussen 
Related: https://github.com/WordPress/gutenberg/pull/13721

**Comment by jasmussen** [comment]
Argh, good catch. I could swear we had this fixed :( 

Yes: #13767. It echoes this comment too: https://github.com/WordPress/gutenberg/pull/13767#issuecomment-462401860

What's a good way to fix this? @gziolo my favorite person to ping, any tips?

**Comment by gziolo** [comment]
Is #15643 proposing the proper fix?

It looks like `IconButton` has a very unexpected logic for adding `has-text` class. It adds it when children prop is passed which was the case. However, an icon isn't really the text 🤷‍♂

**Comment by jasmussen** [comment]
According to Kjell it does, amazing thank you!
