### ISSUE TITLE
Dynamic block: PHP notice (kses.php) when rendering input-field with "[email]" in name-attribute

### ISSUE THREAD

**Issue by erikjoling** [WordPress/gutenberg#15621]
**Describe the bug**
I get the following notice: `Notice: Undefined index: input in [...]/wp-includes/kses.php on line 1155`

This happens when I have a dynamic block which renders an input field with `custom-form-name[email]` as a name.

**To reproduce**
```
function custom_render_block_contact_form( $attributes ) {
	return '<input type="text" name="custom-form-name[email]">';
}


function custom_register_block_contact_form() {
	register_block_type(
		'custom/contact-form',
		array(
			'render_callback' => 'custom_render_block_contact_form',
		)
	);
}

add_action( 'init', 'custom_register_block_contact_form' );
```  

**Additional context**
- Gutenberg 5.6.1

**Comment by youknowriad** [comment]
Hi there! where you able to find a solution for your problem?

I don't think kses runs on the HTML produced by the render callback but on the saved HTML. You might have something wrong in the "save" function of your block?

Also note that for general help requests, we use the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.
Thank you
