### ISSUE TITLE
Suite of Post Blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#15623]
We currently offer a "latest posts" blocks with some configuration options which can be pretty nice for setting up homepages with some dynamic content arranged in different sort of grids and lists. There is also some ongoing work to include showing a featured image and the post excerpt as features than can toggled on the block settings.

However, it is clear such a block won't scale to offer all the flexibility that a proper post loop on a theme provides — it's not just showing elements (date, author, and so on) but also their positioning — nor the best editing experience either compared to more granular blocks.

What would be interesting is to explore a "Post" block that works as the wrapper for the `post_ID` context, and which contains an inner blocks area with several available child blocks:

- [x] Post Title
- [x] Post Author
- [x] Post Date
- [x] Post Excerpt
- [x] Featured Image
- [x] Post Content
- [x] Categories
- [x] Tags

This would allow displaying a "post" element in any context and with full flexibility.

```html
wp:post { id: 1 }
    wp:post-title
    wp:featured-image
    wp:post-excerpt
```

Furthermore, this block can support templates, so on insertion it can offer a few defaults (just post title, post title and excerpt, featured image to the side, etc).

Starting with a single post would allow us to determine how the child blocks should be structured. By having each element be a child block, we can also expand on the configuration options much more elegantly: the **date** format display would be easier to connect, the excerpt can offer to customize the number of words and the trailing cutoff, the image can have specific settings, and so on.

If this proves convenient, we can then look at a more general purpose `Query` block that would allow to control the query parameters and then use the "post" block for display. This could be super useful for themes to build sophisticated static pages with dynamic content but full control over layout and content.

![image](https://user-images.githubusercontent.com/548849/57689552-fe1f6b80-763f-11e9-9e12-5bbc3b2cf572.png)

**Comment by richtabor** [comment]
Just for clarification, that screenshot is of three Post blocks using the Columns block? Or a block that adds posts based on a templateOption selection (using this Post block)? Just wrapping my head around it :)

**Comment by youknowriad** [comment]
> Or a block that adds posts based on a templateOption selection (using this Post block)?

This one I think. The parent block being something like a "repeater" block

**Comment by mtias** [comment]
> The parent block being something like a "repeater" block.

Yes, I figure we'd end up with a "Loop" container that defines and handles the query options. Inside, it would use a Post block with a specific template/layout.

That's why I think we can converge on the problem by enhancing the Latest Posts block and implementing these more granular sets of post child blocks.

**Comment by getdave** [comment]
So is the idea that this is a single block for now then later it might be combined with a post list block to provide the "item" for the list? It could also function as a stand alone block foe rendering a single post.

Practically if used within  post listing, how would this block receive the post id context? Would it require the parent list block to dispatch to update the attrs of the child post blocks? 

It would be great to see this come to life. Do we see the individual sub blocks (eg: post meta block) living at the top directory level a la the single column block?

**Comment by mtias** [comment]
In the context of loops this block would work rather like a template.

**Comment by luisherranz** [comment]
I love the idea of combining a `Query` block with `Post` blocks. I've seen so many custom-coded pages over the years whose only purpose was to output posts from a custom query that I'm shedding a tear right now.

Some questions:
- Have you taken a look at what the Newspack team is doing? It looks like they are working in a similar block for their theme, although it is not as flexible: https://videopress.com/v/xDLCB0QV
- Would this support pagination? If so, how would it work?
- Would it be possible to include the list of posts in the REST API response? 
*(Maybe add an option to the `Query` block that adds a `_link` which works with `_embed`).*

**Comment by mtias** [comment]
Thanks for chiming in @luisherranz 

I saw that block, it bundles a lot of customization options in a single block (similar to "Latest Posts" in core), which is what I'm looking forward to exploring here as a more flexible and usable alternative.

Related: https://href.li/?https://github.com/WordPress/gutenberg/issues/16283

> Would this support pagination? If so, how would it work?
Pagination as slideshow-style or as navigating to another URL?

**Comment by luisherranz** [comment]
Well, I was actually thinking about pagination to another URL, like `/custom-list/page/2`. 

I know that's probably way more complex than your original idea, so it's just a thought... But it could solve a pattern that has not been easy to solve in the past: lists of posts based on custom queries.

Some examples that require code right now but could be solved with a `Paginated Query` block:
- Posts from some category, but excluding an author or tag.
- Posts from two categories merged together.
- Products with a discount greater than X%, ordered by the discount.
- Gadgets containing a `Review` block, ordered by their review score. 
- Restaurants that belong to a certain city, ordered by the number of comments.

Besides, users would have much more freedom when choosing the way those posts are displayed thanks to the child blocks.

**Comment by mtias** [comment]
Oh, this would be part of work on dynamic pages that map to the template hierarchy and includes archive pagination. Those would have the concept of main query / loop or something similar, but is a bit beyond the scope of this one.

**Comment by luisherranz** [comment]
Glad to hear there are plans for that :)

**Comment by shaunandrews** [comment]
Worked up a flow for how a Post block could work in Gutenberg, using the newer block UI and taking a few liberties.

![Post Block i2](https://user-images.githubusercontent.com/191598/73565665-074fa300-4430-11ea-89e6-0b76c5f5a643.gif)

You can take the Figma prototype for a spin yourself to get a better feel for it: https://www.figma.com/proto/Lnc1Z6PLVIwGyn21a724e6/Blocks-Suite-of-Post-Blocks?node-id=47%3A0&viewport=-7295%2C-71%2C1&scaling=min-zoom

**Comment by mapk** [comment]
Post Tags block was merged, so I checked it off the list. https://github.com/WordPress/gutenberg/pull/19580

**Comment by mapk** [comment]
Post Author block has also been merged. https://github.com/WordPress/gutenberg/pull/19894

**Comment by youknowriad** [comment]
Going to close this issue now that we have most of these blocks. We should explore improving these blocks on specific issues.

**Comment by mtias** [comment]
It'd be great to create a pattern / variation with something similar to the original design from this issue to determine what is still missing.

**Comment by youknowriad** [comment]
So I was able to get the "content" of the screenshot above. Here are the limitations I found:

 - the Post Featured Image doesn't show up on the editor, it just shows a placeholder
 - I'm unable to show the list of posts as a horizontal list, the Query block always shows these as vertical lists. I believe we might want to offer different visualization options in the "Query Loop" block.
 - The Post Content block is very weird. I can directly edit the content of the posts inside the loop, I'm not certain that's a great thing there.

Maybe we can make some issues based on this or consolidate into other existing issues? cc @MichaelArestad @shaunandrews

**Comment by mtias** [comment]
Let's add these to the query block milestone as well #24762 cc @ntsekouras

**Comment by ntsekouras** [comment]
>The Post Content block is very weird. I can directly edit the content of the posts inside the loop, I'm not certain that's a great thing there.

Create a discussion issue here: https://github.com/WordPress/gutenberg/issues/25394.

>the Post Featured Image doesn't show up on the editor, it just shows a placeholder
I'm unable to show the list of posts as a horizontal list, the Query block always shows these as vertical lists. I believe we might want to offer different visualization options in the "Query Loop" block.

Edited this issue: https://github.com/WordPress/gutenberg/issues/24934 to include the above.

**Comment by iamtakashi** [comment]
I've made a few other issues related to Query Loop block and display. Some are just questions like "how might we make a design like this with the Query block", but all of them have a visual similar to the one in this issue that I anticipate users wanting to see in themes or have access to via Patterns. I have more "out there" layout ideas. If it's helpful to open issues like this I can keep doing that :) 

* Query Loop in Multi-column? https://github.com/WordPress/gutenberg/issues/25462
* Display Posts in Carousel https://github.com/WordPress/gutenberg/issues/25501
* Display Posts in Slider https://github.com/WordPress/gutenberg/issues/25502
* Display Posts in Sortable Table https://github.com/WordPress/gutenberg/issues/25503
* Display Posts as Inline List https://github.com/WordPress/gutenberg/issues/25505
* Post meta blocks inside sentence https://github.com/WordPress/gutenberg/issues/25448
* Read More Button https://github.com/WordPress/gutenberg/issues/25450
* Post Date Style Customization https://github.com/WordPress/gutenberg/issues/25456
* Multi-column Post Excerpt https://github.com/WordPress/gutenberg/issues/25459
