### ISSUE TITLE
Images don't load or only partially load since upgrading

### ISSUE THREAD

**Issue by BankshotComics** [WordPress/gutenberg#15633]
Hi, this happens with images hosted both in my own media library and hotlinked from offsite. I cleared my cache, tried swapping hotlinked images to self-hosted, reviewed in both Chrome and Edge, but regardless it persists. You can see some examples here:
https://www.brendanmcginley.com/heist/heist-plus-ultra-1-homeland-insecurity/
https://www.brendanmcginley.com/cracked/

**Comment by swissspidy** [comment]
Looking at your site, this appears to be a bug with Jetpack's Lazy Loading feature. Please try disabling that to see if the issue still exists. If not, you should report this to Jetpack.

Feel free to reopen / comment here when the issue exists even without Jetpack active.
