### ISSUE TITLE
Block validation fails with wrapping images in figure-tags

### ISSUE THREAD

**Issue by Horttcore** [WordPress/gutenberg#15646]
**Describe the bug**
Block validations fails because of a wrapping figure tag 

**To reproduce**
Just an example use <Richtext.Content value={foo} /> in edit.
This error is triggered with every kind of error i.e. duplicate className for an selector attribute etc.

**Expected behavior**
Don't wrap images in figure tags and break block validation.
Log a more clear error message to the console.

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - current version

**Additional context**
- Happy to help if more feedback is needed

**Comment by KenEucker** [comment]
I am also encountering this issue.

**Comment by mikemcalister** [comment]
I'm seeing the same thing in one of my blocks during the deprecation/validation routine. The editor adds a `<figure>` tag, as seen in the screenshot below. I already have a wrapping `<figure>` tag with a class on it, and the editor adds the `<figure>` without the class. 

Some clarity as to why the editor adds markup like this and how to avoid it would be appreciated!

![Figure error](https://d1jfzjx68gj8xs.cloudfront.net/items/0F1v1F1Z3B3b2T2g460x/Image%202019-07-12%20at%209.42.30%20AM.png)

**Comment by abursill** [comment]
Yes, all Gutenberg image blocks create invalid HTML code according to W3. a figure or figcaption may not be the child of a div.  Even when the figcaption is inside the figure and a div is an outside parent element somewhere it will create invalid HTML. 
So please fix your image blocks or give people the option of plain image block wrapped in a div or a figure image. Also please make your Gutenberg editor renderable on custom pages like the wp-editor is. Personally I am not loving Gutenberg after weeks of testing and pulling my hair out.

**Comment by sethrubenstein** [comment]
I'm also having this issue. I'm trying to include some art direction in a custom block
```
<picture>
<source srcset="..."/>
<img src="..."/>
</picture>
```
On WordPress Multisite for non super admins however the block when saved is getting wrapped in a figure tag and the picture tag is removed along with all its sources. How can we customize Gutenbergs post validation to allow the picture element or stop this figure element wrapping?

**Comment by sethrubenstein** [comment]
I'm honestly not sure if its Gutenberg of WP KSES and if it is KSES if anyone could point me to a way to whitelist the picture and source tags that would be much appreciated.

**Comment by LaudineCOW** [comment]
I had the same Problem and figured out, that the validation did NOT fali because of the inserted figure tags, but of a failure in my attributes configuration. In my case I declared a "content" attribute as type "array" but give a string to it. After changing the type declaration to "string" all validated well.

**Comment by talldan** [comment]
This is quite an old issue, so it'd be good to establish if it's still an issue.

For me, the Steps for reproduction are not very clear. If anyone experiencing this can provide easier to follow reproduction steps (potentially with code snippets) that would be appreciated.

**Comment by karmatosed** [comment]
As there has been no reply to this issue, let's wrap up the discussion for now. It can always be reopened if we get some steps for reproduction.

**Comment by abcdavid** [comment]
I had exactly this issue and eventually found a typo where the attribute sources are set (too many uses of word attribute becomes confusing here, bear with me...) - atribute rather than attribute when the source is an attribute.  Might help someone?  Surprised me that this was working at all.  Was very hard to track down this issue as there are no relevant warnings or errors until validation fails.

**Comment by julpec** [comment]
I have the same problem and the validation goes from the moment I put my attribute in a div containing a class. This does not work when there is a <p> tag or in a div without a class.
Working example: 
```
return (
      <div className="chapo">
        { chapoImage(attributes.imageUrl, attributes.imageAlt) }
        <div className="chapo-txt">
        { attributes.text }
        </div>
      </div>
    );
```
and a non-working example: 
```
    return (
      <div className="chapo">
        { chapoImage(attributes.imageUrl, attributes.imageAlt) }
        <p className="chapo-txt">
        { attributes.text }
        </p>
      </div>
    );
```
It gives me that when I refresh the page: 

![Capture d’écran du 2020-05-11 02-19-50](https://user-images.githubusercontent.com/8127324/81514225-1d71d700-932e-11ea-9059-eb31373c52ec.png)

it's really strange !!

**Comment by luckyape** [comment]
> I'm also having this issue. I'm trying to include some art direction in a custom block
> 
> ```
> <picture>
> <source srcset="..."/>
> <img src="..."/>
> </picture>
> ```
> 
> On WordPress Multisite for non super admins however the block when saved is getting wrapped in a figure tag and the picture tag is removed along with all its sources. How can we customize Gutenbergs post validation to allow the picture element or stop this figure element wrapping?

this exactly describes an issue im having.

**Comment by talldan** [comment]
@luckyape This issue is now closed as the reproduction instructions provided by the original poster were hard to understand. None of the comments seem to clarify the issue at hand.

If you can provide better steps for reproduction (I think this issue would require working code examples too), then I'd recommend creating a new issue.
