### ISSUE TITLE
Datepicker converts :0x minutes to :x, making for confusing output

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#15652]
It looks like we're currently saving minutes as an integer value, which removes the prefix "0" from values like ":02, :06, :09, etc":

This ends up being sort of confusing from a user perspective:

![Datepicker mystery time](https://user-images.githubusercontent.com/376315/57775235-68342100-76d1-11e9-9b9a-b856224fc371.png)

To reproduce:
1. Write a new post. 
2. Open the "publish" datepicker.
3. Manually add a value less than ten for the minutes.
4. Save value by clicking outside the popover. (Super awkward, see #12048 for a suggested solution here.)
5. Re-open the popover, and see the zero has been stripped out.

![2019-05-15 13 19 48](https://user-images.githubusercontent.com/376315/57775234-679b8a80-76d1-11e9-9f13-93fb8fab8255.gif)

On output, we should ensure the value for minutes is always two digits, and add a prefix "0" if it's only a single digit.

Note that this also occurs with the hours value, but it doesn't feel as confusing here. Ideally, for 24h clocks, we'd add a zero to the hours, but for 12h clocks, we'd leave them be, so times would look like so on output, depending on user date settings:

24h: 08:08
12h: 8:08pm

See also: #10181 and an array of other datepicker issues.

**Comment by aduth** [comment]
Implementation notes:

This can usually be resolved by formatting a value with the following logic:

```js
( '0' + minutes ).slice( -2 )
```

The way it works is to take the last two numbers, ensuring that it's front-padded (by zeros) to at least two numbers.

In the code itself, I imagine this would take place either here:

https://github.com/WordPress/gutenberg/blob/761ec3fc1a668f90f0fcd15b50f688d13daaa802/packages/components/src/date-time/time.js#L292

Or in assigning the minutes state:

https://github.com/WordPress/gutenberg/blob/761ec3fc1a668f90f0fcd15b50f688d13daaa802/packages/components/src/date-time/time.js#L192
