### ISSUE TITLE
24h time settings aren't respected in preview

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#15654]
If the user's time settings use 24h time (as opposed to 12h AM/PM time), the time shown in the publish settings still uses 12h time. This is especially confusing when the time is entered using 24h time:

![Datepicker 24h time](https://user-images.githubusercontent.com/376315/57776684-fbbb2100-76d4-11e9-9c9d-465d82c2c064.png)

To reproduce:
1. Change time settings to use 24h time. (Settings > General > Time Format > H:i)
2. Create a post.
3. Schedule for any time past 12:00. (ie, 13:25).
4. Close popover by clicking outside.
5. Publish date listed in 12h time.

The date format should respect the site settings across the UI.

See also: #10181 and #15652.

**Comment by swissspidy** [comment]
I'd even consider that as a bug.
