### ISSUE TITLE
Meta boxes arrow icons in RTL

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1565]
Many things still need to fully support RTL languages in the UI. One small detail is about the meta boxes icons. 

They're currently using a right-arrow icon when collapsed and a down-arrow icon when expanded:

<img width="316" alt="screen shot 2017-06-28 at 17 29 55" src="https://user-images.githubusercontent.com/1682452/27646024-ec4462dc-5c27-11e7-8715-1d1a2e2e2568.png">

See also related discussion on Slack https://wordpress.slack.com/archives/C02QB2JS7/p1498468801241441?thread_ts=1498209002.818056&cid=C02QB2JS7

If the right-arrow icon is going to stay, I guess it should be swapped to left-icon for RTL languages. I think this is something WordPress does during the build process with a custom grunt plugin `swap-dashicons-left-right-arrows`. Instead, Gutenberg sets these icons in the component, depending on the meta box opened state:
`icon={ this.state.opened ? 'arrow-down' : 'arrow-right' }`

/cc @ocean90

**Comment by jasmussen** [comment]
I built a fix for this one in #3831, which was then improved upon in #3844. As such, I'm closing this as fixed. Feel free to reopen if this was in error.
