### ISSUE TITLE
Block Library: Column: Move resizing controls to Columns block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#15660]
Previously: #15499 
Related (potentially blocked by): #7694

As of #15499, it is possible to resize a Column block using the "Percentage width" input in the block inspector. The usability of selecting an individual Column block is quite poor, however. Per @jasmussen's comment at https://github.com/WordPress/gutenberg/pull/15499#issuecomment-491194849 and prior consideration at #7694, we should consider moving the column resizing controls to the parent Columns block, and prevent individual columns from being selected at all.

**Comment by paaljoachim** [comment]
Can we close this issue?

@jasmussen

**Comment by jasmussen** [comment]
We can close and reopen if someone wants to work on it. I see the solution as there being resize handles directly on the columns block.

**Comment by paaljoachim** [comment]
Closing for now.
