### ISSUE TITLE
Unable to write already written line

### ISSUE THREAD

**Issue by soumyadip77** [WordPress/gutenberg#15675]
Unable to write content in between the already written line. Here I am sharing video 

Video Link  :https://drive.google.com/file/d/1XgbKFxGfvZI3x-kDrc5ifKLbABnYyNvp/view?usp=sharing

**Comment by talldan** [comment]
Hi @soumyadip77, thanks for the issue report and the helpful video. Would you be able to share which operating system and browser you're using?

I also just wanted to check, are you using the left-arrow key to move back and edit the already written text?

From the video is does look very similar to overtype mode in Windows:
https://support.office.com/en-us/article/type-over-text-overtype-mode-2fe125af-505f-4ce7-bbea-f0e64e381e75

**Comment by soumyadip77** [comment]
Using windows 7 Chrome browser and facing issue only with this block editor and not only with arrow key when i am trying with mouse same thing

**Comment by youknowriad** [comment]
Can't seem to open the video link anymore. Would you be able to provide it again?

**Comment by zdenys** [comment]
We have a user at WordPress.com who reports they can no longer use Overtype.

Their operating system is Windows 11. They tried overtyping mode in Chrome, Firefox, Edge and Opera. No success.
In MS Word and Openoffice Document this function is working fine.

Can this be reopened?
