### ISSUE TITLE
Cannot link to custom posts

### ISSUE THREAD

**Issue by gillespieza** [WordPress/gutenberg#15676]
**Describe the bug**
When I create a blog post using the new editor, I am not able to link to any of my custom posts. 

**To reproduce**
1. Highlight the word(s) I want to link, 
2. Click the link button
3. Search for the title of one of my custom posts
4. Don't see my custom post returned

**Expected behavior**
I expect: my custom post matching the title I searched for to be returned so I can click on it to link it. Instead, only my existing posts and pages appear in the link search results, not any of my custom posts.

**Screenshots**
https://www.dropbox.com/s/pnsdc3j1z2ouv1g/gutenberg-bug-screenshot.jpg?dl=0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 74.0.3729.157
 - WordPress: 5.2

**Comment by donmhico** [comment]
Hello @gillespieza, 

Thank you for your report. I can't reproduce the bug anymore in the latest commit at the of this writing - 85eaee368

Also custom post type needs to have `'show_in_rest' => true` and `'public' => true`.

**Comment by skorasaurus** [comment]
Unable to reproduce this; 

More information about registering your custom post type to ensure full gutenberg comptability at https://developer.wordpress.org/reference/functions/register_post_type/#comment-3847 

If you're still experiencing this issue, please comment and we'll reopen.
