### ISSUE TITLE
Date Picker panel hidden on Microsoft Edge

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#15689]
**Describe the bug**

The Date Picker panel is hidden behind the side panel when opened on Windows 10 making it unusable. See GIF below.

**To reproduce**
1. Using Microsoft Edge browser on Windows 10
2. Create new post 
3. Click Date to schedule post

**Screenshots**

![date-picker](https://user-images.githubusercontent.com/45363/57891140-2dc0a600-77ef-11e9-91fd-e277d9056e94.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by grappler** [comment]
This seems to be fixed. I just tested this.

Windows 10
Microsoft Edge 42.17134.1.0
WordPress 5.3
Gutenberg 7.0

**Comment by mkaz** [comment]
Thanks @grappler for revisiting and testing, I just confirmed it is fixed too.
