### ISSUE TITLE
Document Settings: Allow *Custom* Post Types to Add Sections

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15695]
Forgive me if this issue has been reported already (I wouldn't be surprised).

Currently it is impossible to add sections to the "Document" sidebar/ inspector. There are probably good reasons for this; we may not want to let plugins bloat this area. I completely understand that in the context of core post types. However, if you register post types (which are likely to be very different from posts or pages), being able to extend the document settings is _crucial_. I can think of so many post types that would want to have highly used settings for the _document_ in easy reach for the user.

So, what I'm proposing is that we add a slot or something similar _only_ for _custom_ post types, as we should make no assumptions on what that post type may need.

**Comment by ellatrix** [comment]
Just like we allow **custom blocks** to add settings to the **block inspector**, we should allow **custom post types** to add settings to the **document inspector**.

**Comment by swissspidy** [comment]
A quick search reveals #13357, which also has a PR: #13361
