### ISSUE TITLE
Webpack build process is overridding wp.utils

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#1569]
I was working on #1557 and noticed that even though `word-count.js` was added as a dependency, it was not available at `window.wp.utils`. The entire object is being overridden by the following portion of `webpack.config.js`

```
const entryPointNames = [
	'element',
	'i18n',
	'components',
	'utils',
	'blocks',
	'date',
	'editor',
]


entryPointNames.forEach( entryPointName => {
	externals[ entryPointName ] = {
		'this': [ 'wp', entryPointName ],
	};
} );
````
Essentially, any items in entryPointNames will be added to the`wp` object and override anything already exisiting with the same name.

Can we namespace this to `wp-gb` or something similar?

**Comment by ryanwelcher** [comment]
I've added a PR for this https://github.com/WordPress/gutenberg/pull/1571. The approach I took was to rename the `utils` folder and references to 'utils-gb'

**Comment by nylen** [comment]
See previous discussion around https://github.com/WordPress/gutenberg/pull/940#issuecomment-305004654:

> `word-count.js` [doesn't clobber `window.wp.utils`](https://github.com/WordPress/wordpress-develop/blob/4.7.5/src/wp-admin/js/word-count.js#L216-L219)

> So this means that the webpack version needs to be loaded first. We can accomplish this by adding `wp-utils` as a dependency of `word-count`.

**Comment by ryanwelcher** [comment]
@nylen thanks for your support on this!

I have put together a PR for the Word Count feature ( #1624 ) and am running into an issue where WordCounter is not available when the component initializes as it is loaded after Gutenberg. I have accommodated for that in the component but it would be better if the core items were loaded first. However, this puts us back to the issue of the namespace being overridden when Gutenberg loads.

We could address this by changing the namespace in Gutenberg from `uilts` to `gb.utils` or something to that effect. Do you have any suggestions for the best way to address this?

**Comment by nylen** [comment]
I think the `utils` thing is a good first exercise in integrating with the rest of core's JavaScript.  I'll see about fixing it over on your PR.
