### ISSUE TITLE
Safari - Editing Links in Paragraph Block - Block has encountered an error mesage

### ISSUE THREAD

**Issue by gwensmithx** [WordPress/gutenberg#15690]
**Describe the bug**
In Safari only and on AT sites only - if you add or edit a link in a paragraph block then click onto another block then back to the block that you just added/edited the link on - you will almost always get the **"This block has encountered an error and cannot be previewed"** message.

**To reproduce**
1. Open your AT site in Safari and open up a post or start a new one.
2. Add at least two paragraph blocks with text in both.
3. Highlight a word in one of the blocks and add a link
4. Click to the other paragraph blcok
5. Click back to the block with the link you just added
6. Block error message will come up.

**Expected behavior**
I would expect to be able to edit the paragraph I clicked on.

**Screenshots**
![Screen Capture on 2019-05-16 at 21-06-55](https://user-images.githubusercontent.com/5779512/57900856-cb33ce00-781f-11e9-8593-1dfe70761901.gif)

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser Safari
 - Version: Safari/605.1.15

**Additional context**
- **only seems to happen when you've added a link** and click back. This does not happen when editing between paragraphs that don't have a link
- **was only able to reproduce this on AT site** (user's and my own). Could not replicate on Simple site
- **only happens in Safari** - could not replicate on Firefox or Chrome

**Comment by spacedmonkey** [comment]
Had the same issue #15704 .

**Comment by youknowriad** [comment]
Closing as this is fixed in the last Gutenberg version and in WordPress 5.2.1. Can you clarify which WP version your website is using?

**Comment by spacedmonkey** [comment]
@youknowriad I can confirmed that this is fixed in 5.2.1. 🎉
