### ISSUE TITLE
No matching version found for @wordpress/editor@^9.2.5

### ISSUE THREAD

**Issue by afeiship** [WordPress/gutenberg#15694]
## I want to install these packages:
```json
"@wordpress/block-library": "^2.4.0",
"@wordpress/edit-post": "^3.3.0",
"@wordpress/format-library": "^1.4.0",
```

BUT when i install package, shell caught error:  `No matching version found for @wordpress/editor@^9.2.5`

I change package to fixed version like this:
```json
"@wordpress/block-library": "2.4.4",
"@wordpress/edit-post": "3.3.4",
"@wordpress/format-library": "1.4.4",
```

**Comment by swissspidy** [comment]
New package versions have been released this week. Is this still an issue you encounter?

**Comment by afeiship** [comment]
@swissspidy the `@wordpress/editor` package has updated to `9.3.0`, so the problem should disappeared... 
Thanks!
