### ISSUE TITLE
Paragraph preview error.

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#15704]
**Describe the bug**
I get a the following error when adding links to paragraph. 
```This block has encountered an error and cannot be previewed.```

**Reproduction steps**

1. Log into WordPress in Safari.
2. Create a new post.
3. Insert paragraph: "This paragraph has a hyperlink."
4. Select text "hyperlink"
5. Click the "link" button.
6. Enter "www.example"
7. Add another paragraph. "This paragraph does not."
8. Click on the hyperlink.
9. Click on the "expand" button 🔽
10. Try to check the "open in a new tab" toggle button.
11. Select the second paragraph.

**Expected behaviour**

In step 10, the toggle should change state.
In step 11, the first paragraph should remain intact.

**Observed behaviour**

In step 10, the toggle doesn't change state.
In step 11, the first paragraph is replaced by the message "This block has encountered an error and cannot be previewed"

The toggle not updating its state seems to occur in Chrome too, but I could only repro the error message on Safari. Both problems don't seem confined to a single site. I've observed them on the Greece and UK sites.

**Screenshots**
<img width="1436" alt="Screenshot 2019-05-17 at 16 25 58" src="https://user-images.githubusercontent.com/237508/57938961-31bcf880-78c1-11e9-90c5-35a8fed0b3e8.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4 
 - Browser Safari
 - Version 12.1

** Tech information **
- WordPress 5.2
- Gutenberg version is what ever shipped with 5.2
- Yoast 11.1 installed. 
- No other custom blocks.

**Comment by swissspidy** [comment]
Duplicate of #15690?

**Comment by spacedmonkey** [comment]
@swissspidy It seems like it. I am going to close.

**Comment by spacedmonkey** [comment]
I can confirmed that this is fixed in 5.2.1. 🎉
