### ISSUE TITLE
Latest Post Content - show Full Post -bug showing mix of Classic and GB-

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15719]
**Describe the bug**
I am testing the Latest Post block. Turned on Post Content. Selected to show the Full Post.
One of the posts content preview shows code that stretches across the page as well as image html.

<img width="943" alt="Screen Shot 2019-05-18 at 22 27 25" src="https://user-images.githubusercontent.com/5323259/57974652-374b3900-79bc-11e9-89ed-7e935b12914c.png">

The post that is causing the problem:
<img width="807" alt="Screen Shot 2019-05-18 at 22 28 23" src="https://user-images.githubusercontent.com/5323259/57974656-45995500-79bc-11e9-8ca5-9bb50c3fc3cf.png">

I do believe this is a more fundamental problem with Classic <-> Gutenberg then just the latest post block.

**To reproduce**
1. Create some posts with a mix of Classic and Gutenberg.
2. Add the Latest Post Block.
3. Show full content.
4. An error might be seen.

**Expected behavior**

**Desktop (please complete the following information):**
Local host - Desktop Server.
Chrome

@jorgefilipecosta

**Comment by arunsathiya** [comment]
I ran into a similar issue with the first word being very long, which I have flagged here - https://github.com/WordPress/gutenberg/issues/15721

**Comment by paaljoachim** [comment]
It looks like this has been taken care of.
1. Added the Lastet Post block.
2. Turned on full content.
3. It looks fine now.

Tested with Gutenberg plugin 9.8.
Themes: Twenty Twenty One and Twenty Twenty.

(A new bug showed up. Clicking the block does not activate the sidebar settings. A new issue will be created for it.)

Backend:
![Screen Shot 2021-01-22 at 11 45 52](https://user-images.githubusercontent.com/5323259/105481649-a2780300-5ca7-11eb-9ed6-0807c6713d64.png)

Frontend:
![Screen Shot 2021-01-22 at 11 48 48](https://user-images.githubusercontent.com/5323259/105481805-d81cec00-5ca7-11eb-917a-8e5860722c6f.png)
