### ISSUE TITLE
Latest posts block: Smaller font size for content and preserve content formatting

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#15722]
**Is your feature request related to a problem? Please describe.**

The `Latest posts` block has a new feature (https://github.com/WordPress/gutenberg/pull/14627 and https://github.com/WordPress/gutenberg/pull/15453) to show post content. This is a great feature addition! 

Although, when the content setting is enabled, the font size of the content matches the title font size.

The formatting of the content is not preserved either.

**Describe the solution you'd like**

- Set the content to a smaller font size by default. (requiring no custom CSS from user's end)
- Preserve content formatting (that is, new lines, bold, italics, and other customizations that can be seen on the actual blog post) on the `Latest posts block` as well.

Example:

<img width="1006" alt="Screenshot 2019-05-19 at 14 31 08" src="https://user-images.githubusercontent.com/18581859/57980002-c9962000-7a42-11e9-9198-0c1970e32cbe.png">
<img width="969" alt="Screenshot 2019-05-19 at 14 31 12" src="https://user-images.githubusercontent.com/18581859/57980003-ca2eb680-7a42-11e9-9bb8-7bc82d954b2f.png">

In these two images, it can be seen that:

- Font size of the content is the same as font size of the title.
- The new lines from the actual post content (after the sentence `Tubulo putas dicere?` in `Post 19`) is not seen on the `Latest posts` block.

**Describe alternatives you've considered**

- For now, can change content font size using CSS.

#### Gutenberg, browser and device version:

I am using Gutenberg 5.7.0-rc-1 on a Pressable site, with Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on macOS 10.14.4 - Mac OS Mojave.

**Comment by youknowriad** [comment]
I think it makes sense to me. cc @kjellr @AmartyaU

**Comment by kjellr** [comment]
> Font size of the content is the same as font size of the title.

This is just a Twenty Nineteen problem actually. Currently, Twenty Nineteen styles target everything within the latest post `li` item. It should really just style the title and post date. The excerpt should be unstyled and fall back to the default post content text styles. I'll work on that this week and link it back here. Other themes may need patches too, depending on how they've built these styles.

By default (if a theme supplies no styles), Latest Posts will look something like this: 

<img width="578" alt="Screen Shot 2019-05-21 at 10 27 54 AM" src="https://user-images.githubusercontent.com/1202812/58104670-27497a00-7bb3-11e9-9396-f5b4574e389e.png">

If anything, I think we could provide a little bottom padding to each of the latest posts. @jasmussen, what do you think? I know there's been pushback about adding styles like that. 

> The new lines from the actual post content (after the sentence Tubulo putas dicere? in Post 19) is not seen on the Latest posts block.

I agree it's a little weird without line breaks, but I'm guessing we're drawing from `the_excerpt()` here, which does usually strip out all new lines.

**Comment by jasmussen** [comment]
> If anything, I think we could provide a little bottom padding to each of the latest posts. @jasmussen, what do you think? I know there's been pushback about adding styles like that.

Honestly I think it's fine to do this to provide a good baseline. We even have some options here — if we feel the styles are fundamental, they go in style.scss which is loaded in editor and frontend regardless. We just need to make sure that the CSS we write has as little specificity as possible. 

If we're on the fence about the fundamental necessity of those margins, we put them in editor.scss, which means themes that opt in get it. The only downside to putting it here is that it's still loaded in the editor even if not on the frontend.

**Comment by kjellr** [comment]
Thanks, @jasmussen. I've opened #15760 to try this out.

**Comment by kjellr** [comment]
I'm going to mark this one as closed for now: 

#15760 adds some default spacing. 
[47340-trac](https://core.trac.wordpress.org/ticket/) handles this fix in Twenty Nineteen. 

Thanks!
