### ISSUE TITLE
[ Latest posts ] Post content overflows block space when first word is very long

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#15721]
#### Describe the bug

The `Latest posts` block has a new feature (https://github.com/WordPress/gutenberg/pull/14627 and https://github.com/WordPress/gutenberg/pull/15453) to show post content. In the `Excerpt` mode, if the first word is very long, it overflows the available block space.

#### Steps to reproduce 

- Start with Gutenberg 5.7.0-rc-1. It's available [here](https://github.com/WordPress/gutenberg/releases/tag/v5.7.0-rc.1).
- Add the `Latest posts` block.
- On the block settings, enable the option to show post content.
- Choose `Excerpt` mode and limit to a certain number of words. Say, 10.
- Publish the post/page.
- Create another post with the first being very long. Example word that you can use:

`testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt`

#### What is expected 

The content is within the block, and does not overflow.

#### What happens instead 

The content overflows the available block space. 

<img width="1706" alt="Screenshot 2019-05-19 at 14 22 56" src="https://user-images.githubusercontent.com/18581859/57979961-f564d600-7a41-11e9-8d59-d6ad7bbaf4fc.png">

#### Notes

This is because the block settings limits the content to "10 words". One solution to this would be to modify the setting to "number of characters" instead of "words".

This happens for the long first word in a column block as well.

<img width="1002" alt="Screenshot 2019-05-19 at 14 25 57" src="https://user-images.githubusercontent.com/18581859/57979968-0ca3c380-7a42-11e9-926b-a2768c2f34c7.png">

#### Gutenberg, browser and device version:

I am using Gutenberg 5.7.0-rc-1 on a Pressable site, with Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on macOS 10.14.4 - Mac OS Mojave. 

Related issues: https://github.com/WordPress/gutenberg/issues/15719

**Comment by draganescu** [comment]
Howdy @arunsathiya, wouldn't this be solvable by themes? It feels very little useful to have char length for excerpts _instead_ of word length, and having both options seems to much.

**Comment by paaljoachim** [comment]
Hey

I just closed my own issue that is somewhat related.
I did a new test for this issue.

Using Gutenberg version 9.8
Twenty Twenty One.
Chrome
WordPress 5.6

1. Made the first word very long in a post.
2. Added the Latest Post block in a page.
3. Made excerpt show 10 words.
4. Made another post where the first word was also very long.

The result:

Backend:
![Screen Shot 2021-01-22 at 12 15 30](https://user-images.githubusercontent.com/5323259/105484404-8b3b1480-5cab-11eb-9b54-eecc8baf3646.png)

Frontend:
![Screen Shot 2021-01-22 at 12 16 02](https://user-images.githubusercontent.com/5323259/105484454-a0b03e80-5cab-11eb-8b2f-e46157bd1807.png)

I will go ahead and close this issue. If I am mistaken then please reopen.
