### ISSUE TITLE
Page/URL autocompletion contains escaped HTML / HTML tags

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#15727]
**Describe the bug**
Page/URL autocompletion in Gutenberg editor (like for a link) contains escaped HTML / HTML tags.
Plugins (like [wp-typography](https://github.com/mundschenk-at/wp-typography)) can use filters for adding HTML to the title later being returned by `get_the_title()`.
The HTML is not shown in URL autocomplete of Classic editor, but in Gutenberg editor.

**To reproduce**
1. Filter the title of a page so it contains HTML or 
install + activate a plugin that does this, e.g. [wp-typography](https://wordpress.org/plugins/wp-typography/).
2. Open a page in Gutenberg editor.
3. Add text and apply format to it so the page/URL autocomplete opens.
4. Notice that there is HTML in the page titles in page/URL autocomplete results list.

**Expected behavior**
No HTML in page titles in page/URL autocomplete results list.

**Desktop (please complete the following information):**
 - OS: Windows 10/Ubuntu LTS
 - Browser: Chrome
 - Version: Latest

**Additional context**
Gutenberg 5.7.0

Related: https://github.com/mundschenk-at/wp-typography/issues/245

**Comment by mundschenk-at** [comment]
If the title is expected to not contain markup, PHP code would use [`the_title_attribute()`](https://developer.wordpress.org/reference/functions/the_title_attribute/). If I remember correctly, the code in Gutenberg relies on the `rendered` attribute from the REST API. In this case, the titles either should not be escaped (completely) or any tags stripped before escaping.

**Comment by strarsis** [comment]
@gziolo, @youknowriad: Could someone look into this again?

**Comment by strarsis** [comment]
*Push*

**Comment by Mamaduka** [comment]
Fixed via #48685.

## Screenshot
![Image](https://github.com/user-attachments/assets/d4351e11-0dc8-4d27-aa11-9897d229c114)
