### ISSUE TITLE
Save to Post Meta Without "show_in_rest => true" Possible?

### ISSUE THREAD

**Issue by JoshuaMcKendall** [WordPress/gutenberg#15728]
Sorry if something like this has been asked already, I searched on GitHub and across the internet, but couldn't really find an answer. 

I followed the HandBook's tutorial for making a plugin sidebar, and everything is working fine. I registered the post meta, show_in_rest => true etc. However, I have post_meta that is somewhat sensitive information and I'd like to be able to save/edit this data within Gutenberg without it being publicly available to anyone who is savvy with the REST API. Is this possible? Or am I thinking about this all wrong?

The sensitive information is not super important ( nothing like passwords, etc. ), but it's still something I'd prefer to be inaccessible to anyone who cannot edit posts.

**Comment by swissspidy** [comment]
Gutenberg uses the REST API to read and save post meta. It does not work without the REST API.

However, using the REST API does not mean the data is available to everyone on the world wide web. You can use auth/permission callbacks to limit access to users with only specific capabilities. You can learn more about that in the WordPress developer handbook and the Gutenberg handbook.

**Comment by JoshuaMcKendall** [comment]
Ah okay, thank you. I just did some more reading and changed my code a bit, and now it's working as intended. Thanks
