### ISSUE TITLE
RichText: copy paste inside same field sometimes duplicates text

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15724]
**Describe the bug**

Sometimes when I copy and paste a piece of text within the same RichText instance, the rest of the text is duplicated. I'm not sure what the cause of this is, I'll need to investigate it later. Just creating this ticket so I don't forget about it. Perhaps others have experienced the same.

Gutenberg v5.7 on Mac n Chrome

**Comment by GlennMartin1** [comment]
I've seen this, only since 5.7. Using Chrome on Windows.

**Comment by gziolo** [comment]
I have experienced this bug today with the latest version of Gutenberg plugin(6.2.0):
![copy-paste](https://user-images.githubusercontent.com/699132/62294185-b7852480-b46a-11e9-90f1-913aad8eaa4d.gif)
