### ISSUE TITLE
Setting Default Block Doesn't Work

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15730]
**Describe the bug**

I have a custom post type where I have a custom block that needs to be inserted by default. This means that:

* A post should start with an empty block of that kind.
* The appender should insert that type of block by default, not a paragraph.

I used `setDefaultBlockName` to set a new block type, and unfortunately neither works. I'm not even sure if it does anything at all.

CC @youknowriad (I'm not sure if you worked on the default block or someone else 🙂)

**Comment by youknowriad** [comment]
I think the "default block" has an interface to fulfill. It should have a "string" content property I think, otherwise, it doesn't work as expected. That said, it's a feature that is not used/tested a lot, so there might be some bugs here and there.

**Comment by ellatrix** [comment]
It does have an appender that is a paragraph block. From the perspective of an implementer, this should "just" work. :)

I can have a look when I find more time.

**Comment by FerrielMelarpis** [comment]
@youknowriad 
> I think the "default block" has an interface to fulfill. It should have a "string" content property I think, otherwise, it doesn't work as expected. That said, it's a feature that is not used/tested a lot, so there might be some bugs here and there.

I think it would be nice to have this documented [here](https://developer.wordpress.org/block-editor/packages/packages-blocks/#setDefaultBlockName). I have no clue why it doesn't work before so I resulted to have a workaround for it using `innerBlocks` with a custom appender. I'd also recommend adding a sample as well.

**Comment by nevnein** [comment]
Sorry to bump an old issue, but are there any news on this?

I'm in the same  situation as OP, I tried `setDefaultBlockName` but it's not working (I'm not even sure of where/when should it be called, right now I'm calling it just after the block registration), my custom block is mostly based on the default paragraph so the interface should be pretty the same.

I'm fairly new to Gutenberg but I know my way around React and WP, if given any hint on where to look maybe I can solve this and help documenting it.

**Comment by nevnein** [comment]
For anyone stumbling here, you have to use `setDefaultBlockName` inside a wp.domReady call for it to work properly. I guess that in my case my call was simply overwritten by the default `core/paragraph` registration.
```
wp.domReady(() => {
  wp.blocks.setDefaultBlockName('thename/ofyourblock');
});
```
In regards to the interface the default block is supposed to have, I'm afraid I can't add more, mine just worked.

**Comment by mtias** [comment]
@youknowriad @ellatrix is there more to do here?

**Comment by iruzevic** [comment]
I have tested this implementation and it works but not fully.
For some reason when you set a new custom block as a default block the / input to select blocks are not working.

- So when you change setDefaultBlockName to and core block that has input everything works.
- When you add default block to a custom block (dynamic block) the inserter is not working.

here is an video as an example:

https://user-images.githubusercontent.com/23283324/104108084-21d9ff80-52c2-11eb-8a0b-bd6f0c5d0510.mp4


Am I missing something in my custom block or?

**Comment by iruzevic** [comment]
Any updates on this issue?

**Comment by jordesign** [comment]
With no further input on this issue in 2 years - I'm going to close it. If it proves we need to still address setting a _custom_ block as the default - we can open a fresh issue for that.

**Comment by fedorenkodev** [comment]
There is another issue related to this: if you use setDefaultBlockName, then the "core/paragraph" stops reacting to the "/" symbol + the placeholder remains the same("Type / to choose a block").
