### ISSUE TITLE
Child blocks: Allow Restriction on Root

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15733]
**Describe the bug**

Currently it's possible to restrict child blocks to specific types of blocks, but I don't think it is possible to do the same on the root. (Maybe I missed some documentation.) It would be great if this were possible.

Use case: custom "slide" post type with "slide" blocks. No other block should be inserted at the root.

**Comment by youknowriad** [comment]
I think this issue might be a duplicate

**Comment by ellatrix** [comment]
Ah, seems like a duplicate of #7845.
