### ISSUE TITLE
Custom HTML Block: Is not wrapped

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#15747]
I wonder why the custom HTML block does not wrapped from a container like:

`<div class="wp-block-html">Content</div>`

The output content is not wrapped as expected, as with the other block types.

Without wrap this block, I have no theme side control to add margin or padding to this block. Is there a reason why you should not wrap this block type?

**Comment by Supanaught** [comment]
@CreativeDive I've just encountered this same issue myself and found a helpful plugin via a thread on Stack Exchange. The [Gutenberg Blocks](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/) plugin enables you to add a new Section block type within which you can add a Custom HMTL block. 

In the Block Settings sidebar in WP, you now have the Advanced dropdown option into which you can enter an Additional CSS Class. Create a corresponding class in your CSS, then you can add margin and padding to your heart's content.

Frustrating that this isn't an out of the box consideration from WordPress, but this plugin workaround does the job and enables you to isolate and deactivate any of their other packaged Gutenberg Blocks if you only want to use the Section block to act as a wrapper.

Hope that helps.

**Comment by CreativeDive** [comment]
@youknowriad why does this little issue is still not fixed?

**Comment by youknowriad** [comment]
Because as its name suggests, it's a custom HTML block, so the idea is that we won't generate HTML ourselves (like the wrapper div suggested here). I'd suggest the Group block to wrap your HTML block if needed.

**Comment by CreativeDive** [comment]
An other way to solve this issue:

```
function wrap_blocks( $block_content, $block ) {
		
		// HTML Core block
		if( $block['blockName'] === 'core/html' ) {
			
			$content = '<div class="wp-block-html">';
				$content .= $block_content;
			$content .= '</div>';
			
			return $content;
			
		}
		
		return $block_content;
	
	}

add_filter( 'render_block', 'wrap_blocks', 10, 2 );
```
