### ISSUE TITLE
Block Template Warning Missing in 5.2

### ISSUE THREAD

**Issue by benplum** [WordPress/gutenberg#15743]
**Describe the bug**
Prior to 5.2, a warning was displayed when a post's current blocks did not match the defined block template.  The warning contained an option to reset the post to match the block template.

**To reproduce**
1. Edit or add a block template to a post type.
2. Edit an existing post of that type. 
3. See that the warning is missing. 

**Expected behavior**
A warning should be displayed, with an option for the user to reset the block template. 

I know there was an issue where the warning would also display when the post type's block template contained a locked set of outer blocks, and unlocked set of inner blocks. If I had to choose one, I'd rather have an ever-present warning than no way to reset the block template. 

I've attempted a work around using: 
```
wp.data.dispatch('core/editor').resetBlocks([]);
wp.data.dispatch('core/editor').insertBlocks( ... );
```
However this fails if `template_lock` is on. (Also, how should `wp.data.dispatch( 'core/editor' ).synchronizeTemplate();` work?)

**Comment by youknowriad** [comment]
cc @jorgefilipecosta in case you have an idea about this.

**Comment by benplum** [comment]
Thanks, the warning is back. Hope #11681 get some attention soon.
