### ISSUE TITLE
[RNMobile] Master thread: Native support for inner blocks

### ISSUE THREAD

**Issue by Tug** [WordPress/gutenberg#15749]
In [previous](https://github.com/wordpress-mobile/gutenberg-mobile/pull/789) [efforts](https://github.com/WordPress/gutenberg/pull/14662) we tried to port the [BlockManager](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-manager.js) and related components from the [Gutenberg mobile repository](https://github.com/wordpress-mobile/gutenberg-mobile) to the Gutenberg repository, to pave the way for inner blocks on RN mobile. However that prove to be unsuccessful as the PR was getting too big to review at once.

To give more context, `BlockManager` is the equivalent of `BlockList` and it depends on many components that still lives in the gutenberg-mobile repo.
The goal here will be to make that port so that we can ultimately have BlockList be reused from the gutenberg repository in components such as `InnerBlock`.

This issue will serve as a reference for this task and will help monitor the progress on the different PRs.

- [ ] 1. Move `BottomSheet` and `Picker` to `@wordpress/components` make them available from outside the `block-editor` package (GB [PR#15750](https://github.com/WordPress/gutenberg/pull/15750) and GB-Mobile [PR#1008](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1008))
- [ ] 2. Port `KeyboardAvoidingView`, `KeyboardAwareFlatList` and `ReadableContentView` to gutenberg so we can reuse those from there
- [ ] 3. `Inserter` ported from [`BlockPicker`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-picker.js)
- [ ] 4. `BlockInspector` ported from [`InlineToolbar`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/inline-toolbar/index.js)
- [ ] 5. `BlockToolbar` ported from [`BlockToolbar`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-toolbar.js)
- [ ] 6. `BlockListBlock` ported from [`BlockHolder`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-holder.js)
- [ ] 7. `BlockList` ported from [`BlockManager`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-manager.js)
- [ ] 8. Create a native version of `InnerBlock`
 
cc @koke @hypest @daniloercoli @gziolo

**Comment by hypest** [comment]
I personally like the approach portrayed in this new ticket better, which is to port the deeper/smaller/more-leafy components first and then move up the dependency tree. I've been advocating for that in the past, though I understand it's not easy to validate unless one tries the ["big" approach](https://github.com/wordpress-mobile/gutenberg-mobile/pull/789) first. I'm optimistic about this new approach! 👐

**Comment by koke** [comment]
Is this replacing https://github.com/wordpress-mobile/gutenberg-mobile/issues/958 then? I don't mind if you prefer tracking progress here, but please make sure the project has the right issue in the right place.

**Comment by Tug** [comment]
Sorry @koke I forgot about the issue you create and made another one here. I agree we can close this one then 👍
