### ISSUE TITLE
Clicking "Move to trash" multiple times may display failure notices on slow networks

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15755]
**Describe the bug**
On a slow network, clicking the "Move to trash" button may trigger an error notice to appear in the UI. Trashing happens correctly (assuming there are no other errors), but the UI displays a "flash" of a notice that is potentially confusing for users.

**To reproduce locally**
- create a new post draft (or edit an existing post)
- in Chrome, throttle your network via the Dev Tools: I've opted for Slow 3G
- quickly click "Move to trash" twice
- be patient
- a notice appears to warn the post has already been trashed
- in the console, the API response shows a 410 error "Gone":

![Screenshot 2019-05-21 at 15 59 45](https://user-images.githubusercontent.com/1682452/58104117-7c51b400-7be4-11e9-87f4-f708ea8d6565.png)

- wait a few more seconds
- you're redirected to the Posts list

**Reproduced also on a production site**
This site has lots of content, several plugins, etc., and sometimes the admin gets a bit slow. It's still on WordPress 5.0.4 so the Gutenberg version is different.
- I've repeated the steps above
- got a different notice: "Trashing failed"
- in the console, the API response shows a 410:

![Screenshot 2019-05-21 at 16 06 06](https://user-images.githubusercontent.com/1682452/58104478-203b5f80-7be5-11e9-8024-f89ec950b288.png)

**Expected**
- The notice to not appear

**Suggestion**
Not an expert of the API so I'd leave investigation of this part to the experts.

From an user interface perspective, I'd tend to think multiple clicks on the "Move to trash" button should be prevented. However, for accessibility reasons the button shouldn't be really disabled to avoid focus losses. I'd like to suggest to use the same pattern already used in other places in Gutenberg:
- after the first click, "noop" the button
- set an `aria-disabled="true" attribute on the button
- wait for the response
- if trashing is successful, the redirect kicks in
- if trashing fails for any reason: restore the button action and remove the `aria-disabled` attribute

**Comment by paaljoachim** [comment]
@joedolson Joe
Do you think that this issue is still relevant?

**Comment by joedolson** [comment]
I can still trigger this issue using Gutenberg 9.7.2 and following the instructions from Andrea, above, so yes - still relevant.

**Comment by Mamaduka** [comment]
I created a proposal to introduce a new `isDeletingPost` selector, which should help us to fix this issue.
