### ISSUE TITLE
Command to list experimental/unstable API

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#15754]
As discussed in today's core-js meeting -[slack conversation](https://wordpress.slack.com/archives/C5UNMSU4R/p1558447405011300) (requires registration), link to notes (pending)-, we want to keep track of the existing unstable and experimental APIs and when they were added.

This should help with the next steps: figure out how to remove them or make them stable.

**Comment by gziolo** [comment]
@nosolosw, any progress on it?  We want to audit those APIs with https://github.com/WordPress/gutenberg/issues/17743.

**Comment by nosolosw** [comment]
Unfortunately, no: my focus has changed since and I didn't have the time to tackle this. Please, feel free to close, reassign, etc.

**Comment by nosolosw** [comment]
For what is worth, this is what I was thinking: we could use `docgen` to extract the existing export definitions, and then write a script that work with those. Something along the lines of:

    npx docgen packages/viewport/src/index.js --debug

Note the `--debug` in the command. That outputs a file ending in `-ir.json` (ir for intermediate representation) that contains all exports with names, etc. In the example above, we'd get:

```
[
	{
		"path": "packages/viewport/src/index.js",
		"name": "ifViewportMatches",
		"description": "...",
		"tags": [ ... ],
		"lineStart": 7,
		"lineEnd": 7
	},
...
]
```

The name exported is there under the `name` key so we could write a script that uses these files to look for `unstable`/`experimental` suffixes/prefixes.

**Comment by nosolosw** [comment]
Closing it, as it seems no longer needed.
