### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#1576]
At the moment, the custom fields options isn't shown with Gutenberg. Is this something that will be added in at some point or is it going to be missing from the end-product?

I ask as a plugin of mine uses custom fields to add meta to a post, rather than add its own meta box.

**Comment by swissspidy** [comment]
Yes, something like this will be added at some point. It's just too early yet. See #952 (closing as duplicate).

This will probably be part of the FAQ that is being put together, see #1419.
