### ISSUE TITLE
Z-index problem (with columns block and images?)

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#15766]
**Describe the bug**
The block inspector for  a paragraph block within a columns block that is inside another columns block has a z-index below an image block in another column block.

**To reproduce**
1. I have a nested columns block, with a structure as in shown in 
![structure](https://user-images.githubusercontent.com/3824560/58136297-d3f31e00-7bea-11e9-9b78-af50bbcaa653.png)
2. When I select a paragraph block in one of the nested column blocks (in red in the above diagram) part of the inspector for that paragraph block is behind the image in an adjoining column block of the outer columns block (in red in the above diagram).

**Expected behavior**
The paragraph block inspector should be on top of (a higher z-index) than the image.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3824560/58136460-554ab080-7beb-11e9-9922-e3ae7cee806a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 74
 - Version: WP 5.2.1 (no GB plugin)

**Comment by youknowriad** [comment]
<img width="330" alt="Capture d’écran 2019-08-22 à 2 05 14 PM" src="https://user-images.githubusercontent.com/272444/63516922-e4ff4400-c4e5-11e9-8849-4b87dbda4aac.png">

This looks fixed to me.

**Comment by pbiron** [comment]
what's the best way for me to confirm that it's fix?  Clone to master branch of the repo, build the plugin and install it, then test?  Or is the fix in a different branch?

**Comment by youknowriad** [comment]
yes, that works @pbiron. you can also try to install the plugin from the plugin repository if it was fixed in a previous release, I personally tested on master though.

**Comment by pbiron** [comment]
it appears to already be fixed in v6.3.0 of the plugin.

thanx!
