### ISSUE TITLE
Hubspot CTAs in multisite are transformed after save if not super admin

### ISSUE THREAD

**Issue by kepi0809** [WordPress/gutenberg#15763]
**Describe the bug**
I have a WP Multisite. I try to use Hubspot CTAs embed in my posts as `custom html` gutenberg block. It works fine with `Super admin` rights. The problem occurs when somebody is not super admin… (roles don't matter).

If you save the post with the Hubspot CTA it looks alright, preview is working fine as well. But if you reopen the post it breaks all of the CTAs so it makes from a custom html like this: 
```
<!--HubSpot Call-to-Action Code --><span class="hs-cta-wrapper" id="hs-cta-wrapper-SOME_TEXT_ID"><span class="hs-cta-node hs-cta-SOME_TEXT_ID" id="hs-cta-SOME_TEXT_ID"><!--[if lte IE 8]><div id="hs-cta-ie-element"></div><![endif]--><a href="https://cta-redirect.hubspot.com/cta/redirect/SOME_NUMBER_ID/SOME_TEXT_ID"><img class="hs-cta-img" id="hs-cta-img-SOME_TEXT_ID" style="border-width:0px;" height="250" width="800" src="https://no-cache.hubspot.com/cta/default/SOME_NUMBER_ID/SOME_TEXT_ID.png" alt="  Learn from the Leaders  "></a></span><script charset="utf-8" src="https://js.hscta.net/cta/current.js"></script><script type="text/javascript"> hbspt.cta.load(SOME_NUMBER_ID, SOME_TEXT_ID, {}); </script></span><!-- end HubSpot Call-to-Action Code -->
```

to something like this: 
```
<!--HubSpot Call-to-Action Code --><span class="hs-cta-wrapper" id="hs-cta-wrapper-SOME_TEXT_ID"><span class="hs-cta-node hs-cta-SOME_TEXT_ID" id="hs-cta-SOME_TEXT_ID">&lt;!--[if lte IE 8]&gt;<div id="hs-cta-ie-element"></div>&lt;![endif]--&gt;<a href="https://cta-redirect.hubspot.com/cta/redirect/SOME_NUMBER_ID/SOME_TEXT_ID"><img class="hs-cta-img" id="hs-cta-img-SOME_TEXT_ID" style="border-width:0px" height="250" width="800" src="https://no-cache.hubspot.com/cta/default/SOME_NUMBER_ID/SOME_TEXT_ID.png" alt="  Learn from the Leaders  "></a></span> hbspt.cta.load(SOME_NUMBER_ID, 'SOME_TEXT_ID', {}); </span><!-- end HubSpot Call-to-Action Code -->
```

so it basically removes the `script tags` and changes some `<` and `>` to their `html code`.

**To reproduce**
Create in a multisite wp instance a post and try to use a hubspot CTA in it (error should work on the edited CTA by me too I think)

**Expected behavior**
Having a way of disabling this probably security feature or having a workaround without making everbody Super admin who wants to use CTAs in their Posts

**Desktop (please complete the following information):**
 - OS: OSX 10.14.4 – not related to the issue
 - Browser chrome – not related to the issue
 - Version 74.0.3729.157 – not related to the issue

Thanks for your help in advance :v:

**Comment by ocean90** [comment]
This isn't really specific to Gutenberg. It's related to the [`unfiltered_html`](https://wordpress.org/support/article/roles-and-capabilities/#unfiltered_html) capability which only super admins have by default in a multisite.
To solve this you should probably create a block that renders the markup server-side.

**Comment by kepi0809** [comment]
oh thank you you're right, I need to keep the HTML at it is, because I only use headless WP but I believe I've found a way thanks to your clarification.

If somebody would have the same problems and don't want to give every editor/author `super admin` then here's a possible solution ;) 
https://kellenmace.com/add-unfiltered_html-capability-to-admins-or-editors-in-wordpress-multisite/
