### ISSUE TITLE
Image block: convert to Cover if user drops text on it

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#15771]
The cover block is amazing, but the user needs to know that it exists before it can be used.

One pattern that I've noticed people doing is this: trying to drag a text block over an existing image, with the hope it would be positioned on top. We could trigger the transformation from image to cover when that happens.

**Comment by mapk** [comment]
This is definitely a common interaction that is surfacing. Related: https://github.com/WordPress/gutenberg/issues/13202

**Comment by paaljoachim** [comment]
I just tested in WordPress beta 1 of 5.7
Using Twenty Twenty One.
Having the WordPress Beta Tester plugin activated.

Look what I found:


https://user-images.githubusercontent.com/5323259/107529024-c0f06080-6bba-11eb-9c1c-8ce2539005bd.mp4



Closing this issue as I believe the issue has been fixed.
