### ISSUE TITLE
Please restore 'Image Title Attribute' in the Gutenberg editor

### ISSUE THREAD

**Issue by FinnJackson** [WordPress/gutenberg#15776]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by swissspidy** [comment]
Marking as a duplicate of #11054, where you have commented on already.

**Comment by afercia** [comment]
Actually, the issue reported in #11054 and originally in #8291 is about the _attachment title_ and not about the title attribute. See https://github.com/WordPress/gutenberg/issues/11054#issuecomment-466824191
