### ISSUE TITLE
Tips: suggest the cover block the first time an user adds a block image

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#15772]
Related to https://github.com/WordPress/gutenberg/issues/15771

The cover block is amazing, but the user needs to know that it exists before it can be used. One thing we could do to improve discoverability is to trigger a Tip the first time the user inserts an image block with a suggestion along the lines of:

"Do you know you can have text over images? Discover the Cover block".

**Comment by idea--list** [comment]
That would lead to unwanted bloat. Imagine all the different block types would start displaying similar popup messages upon first use. You have to store cookies if it is a first time insertion for that block type, or alternatively store it in DB. If you chose cookies the messages will popup again if the user clears the browser history or if the cookies expire...

Not to mention if someone has 5 different WP sites... they will get those first time popups on each site regardless if they are already aware of which block they "should" choose.

I would prefer updating the default "welcome to gutenberg" post and introduce all the features of different blocks there. Of course there are people who can not or are not willing to read, but that does not mean everyone should get popups they did not ask for.

**Comment by nosolosw** [comment]
Wanted to say that those are valid concerns that I also have.

I like the idea of using the demo post as "welcome to gutenberg", but it suffers from the same issues (when do you stop showing that to users?).

**Comment by idea--list** [comment]
There is already a draft post called "welcome to gutenberg", that tries to give a general overview.
I would update that to be more detailed about each core block type.

Then i would place a link on the about screen with some similar text "GB is part of core since last december. If you still feel get lost between the block types check out this page" This way on installation and on every WP update one could find this link and read into the details, however we would not get bloat everywhere.

**Comment by paaljoachim** [comment]
I just tested in WordPress beta 1 of 5.7
Using Twenty Twenty One.
Having the WordPress Beta Tester plugin activated.

Look what I found:


https://user-images.githubusercontent.com/5323259/107529024-c0f06080-6bba-11eb-9c1c-8ce2539005bd.mp4



Closing this issue as I believe the issue has been fixed.

**Comment by idea--list** [comment]
All that could make more sense if:
- that would not be an "A" icon which only tells the programmer/designer what it does who invented the idea... for those who are just plain users, that icon will simply not tell anything about the context as that icon is super unintuitive.
- When the omage block gets converted to a cover block i would also inform the user about the change in a snack-bar message to help the user understand what has happened. As without being trained to the block editor one can not understand what is happening.

**Comment by paaljoachim** [comment]
Hey @idea--list Peter

Features over time are adjusted as better ideas come along. This is a feature that is brand new and it will need some adjustments to be made even better. Even though it is an "A" icon the feature is very helpful. What do you think should be there instead of the A icon?

I am hesitant about the snackbar coming up to let the user know that the block has switched from the Image block and over to the Cover block.

**Comment by idea--list** [comment]
@paaljoachim 
Well if the team wants to remain extremely minimalistic in regards of design why do not you just pick a "T" symbol which alone in itself is way more intuitive than an "A" icon that tries to tell exactly "a thing" but does not carry any meaning.

If the team does  not insist on being extremely minimalistic why do not you pick icons like [this](https://thenounproject.com/term/text/134105/) or [this](https://thenounproject.com/term/text/2240326/) or [this](https://thenounproject.com/search/?q=text+editor&i=2436640)

> I am hesitant about the snackbar coming up to let the user know that the block has switched from the Image block and over to the Cover block.
May i just ask why you are hesitant? For sure to those users who are already TRAINED to Gutenberg all this does not make much of a difference. So why leading them until they learn also this change. And what about the vast majority of the world who still did not use GB and thus they are not trained to it? Why to hesitate helping them to get trained?

Actually GB has many design flaws, the whole UI is fractionated into bits and pieces here and there. Oh i see, this is distraction free for some. For others minimalistic is the only glory way...but what about real people who are not fetishists/designers/programmers/WP wizards? No way give them a snack-bar that would be a perfect means to train them what actually happens in this case, right? ;-)

**Comment by paaljoachim** [comment]
As the feature is new for me as well. I can not assume the reason why it looks like it does.
For the next update of this new feature it is good to have your feedback in relation to a better icon and the snackbar.
I will just leave it at that for now. 
Thanks again Peter!

**Comment by richtabor** [comment]
I'd say we're good to close this, now that we have this "Add text over image" toolbar control for the Image block.

<img width="745" alt="CleanShot 2023-03-17 at 18 35 13" src="https://user-images.githubusercontent.com/1813435/226064374-cfbf5297-335f-4a7f-be21-2ed6af11d2b0.png">
