### ISSUE TITLE
Missing keyboard shortcut for Headings

### ISSUE THREAD

**Issue by uncertainquark** [WordPress/gutenberg#15782]
**Is your feature request related to a problem? Please describe.**
There is no keyboard shortcut for Heading tags. The expected shortcuts of `Ctrl+Alt+1/2/3` or `Alt+1/2/3` don't work.

**Describe the solution you'd like**
Assign a keyboard shortcut, preferably the same as other document editors, for assigning heading tags.

It is inconvenient to use cursor-based navigation while writing a post, which is keyboard based interaction.

**Comment by swissspidy** [comment]
Thanks for raising this, @uncertainquark!

This has been previously requested in #7438, thus I am going to close this one as a duplicate. That issue has already some good discussion about various options for keyboard shortcuts. Please follow along and join in the discussion, too!
