### ISSUE TITLE
Guttenberg Disappeared after adding Eliminator & updating Guttenberg and Wordpress

### ISSUE THREAD

**Issue by lambchop999** [WordPress/gutenberg#15797]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

**Comment by lambchop999** [comment]
Sorry if I am not posting correctly. I have been using Guttenberg for months now. I have 30 ore more pages all in Guttenberg blocks. Last night while editing everything disappeared after receiving a fatal error. All the pages are there along with the info but Guttenberg is gone as an editing option in the pages (usually I have an option of using classic or Guttenberg). This has also effected elements on the published page (things have disappeared or changed). If anyone can help me I would greatly, greatly appreciate it.
<img width="240" alt="Screen Shot 2019-05-23 at 7 18 10 AM" src="https://user-images.githubusercontent.com/50955884/58260361-276c8580-7d2b-11e9-9d2b-c46e72568455.png">

**Comment by talldan** [comment]
Hi @lambchop999 - this site is for the development of the Gutenberg plugin. Your issue sounds like a support request. Sorry to redirect you, but you might have more luck posting on the WordPress.org support forums - https://wordpress.org/support/forum/how-to-and-troubleshooting/.

When posting there, I'd recommend including details about the version you've upgraded from and to, and also details on any plugins you have installed or active on your site. Thanks.
