### ISSUE TITLE
Remove the usage of react-click-outside from the Modal component

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#15790]
That dependency still relies on deprecated React features (findDOMNode) and we have a better built-in alternative (See #14851).

**Comment by gziolo** [comment]
It uses now:
https://github.com/WordPress/gutenberg/blob/ba4793b3d3fbcd49a1ca2defc1734ec999867004/packages/components/src/modal/frame.js#L19
Resolved in https://github.com/WordPress/gutenberg/pull/16878.
