### ISSUE TITLE
Force re-render of all blocks in a site

### ISSUE THREAD

**Issue by Kalagounet** [WordPress/gutenberg#15793]
Hello ! 

I have a question about the use of deprecated blocks.

I made a change on one of my blocks, so I created a deprecated version so as not to lose my content.

I noticed that by going to a page, and updating it, the rendering of the block is updated to its latest version. This is fine because there is no need to update the block, but I need to "industrialize" this update.

I need to update all the blocks present on the site, without having to go to each page to force the rendering.

I tried a method of forcing the update of all pages, but it does not work. Does anyone have a solution to force a new rendering of all the blocks of my site?

**Comment by draganescu** [comment]
It the blocks are not dynamic then the save function has to be called and so the only way I see this working is to make a headless browser visiting the editor, opening each post, editing a non visible page/post attribute and then saving the page/post. Convoluted but, as you said, industralised.
