### ISSUE TITLE
Break lines with BRs when applying lists

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#158]
Requirement from: https://wordpress.slack.com/archives/core-editor/p1484770058001584

Highlight a bunch of text with br, press the list button, and have it be a series of list items rather than one block of text inside a single li

**Comment by iseulde** [comment]
Done in single: https://wordpress.github.io/gutenberg/tinymce-single/

**Comment by iseulde** [comment]
Is this done? I think this was added by @notnownikki?

**Comment by iseulde** [comment]
I do get a warning though.

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <ul>. See https://fb.me/react-warning-keys for more information.
    in li
```

**Comment by notnownikki** [comment]
I thought this was working... It's possible something else has broken it though, will look at it today.

**Comment by notnownikki** [comment]
Ah, looks like #2343 is open for fixing this.

This was working at one point, but I don't think there are tests for the transforms, which we should add to make sure formatting changes don't break stuff again.
