### ISSUE TITLE
editable_slug filter hook does not pass the correct value

### ISSUE THREAD

**Issue by JulioPotier** [WordPress/gutenberg#15802]
**Describe the bug**
When using the block editor, the 1st param $post_name passed to the editable_slug filter hook is not the same as the classic editor, which is the expected one.

**To reproduce**
1. Install Classic Editor to switch from block to classic
2. Create a draft post with title "the post title" and slug "this-is-the-slug"
3. Create a muplugin with: add_filter( 'editable_slug', function( $post_name ) { wp_die( $post_name ); } );
4. Refresh your edit page

**Expected behavior**
With the classic editor you should have "this-is-the-slug"
but when using block editor you have "the-post-title", sounds like the post_title sanitize with sanitize_title, it should be the real post_,name like classic is doing.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 74

Thank you

**Comment by noisysocks** [comment]
Core (not Gutenberg) is what calls this filter, so I've moved this ticket over into WordPress Trac: https://core.trac.wordpress.org/ticket/48622
