### ISSUE TITLE
Can't change colour for Cover Block Heading

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15804]
**Describe the bug**
We can change the text & background colour for Paragraph Blocks within a cover Block, but we can't change the colours for a Heading block. This is inconsistent and makes no sense. If we can change the colour for one, then we should be able to change the colour for the other.

Depending on the overlay colour that's selected, you may render your Heading Block near invisible if you're unable to change both the background colour and text colour, like you can for the Paragraph Block

**To reproduce**
1. Add Cover Block
2. Insert Paragraph Block into Cover Block and change background/text colour
3. Insert Heading Block into Cover Block and try to change background/text colour

**Expected behaviour**
I expect to be able to change the background and text colour of a heading block, within a cover block, in the same way I can do that for a Paragraph Block

**Screenshots**
Paragraph Block within a Cover Block
<img width="1920" alt="screenshot_53" src="https://user-images.githubusercontent.com/2078245/58302417-4a339280-7e2e-11e9-95b6-69bef55e38b0.png">

Heading Block within a Cover Block
<img width="1920" alt="screenshot_54" src="https://user-images.githubusercontent.com/2078245/58302425-54ee2780-7e2e-11e9-8ce1-3144ad2c073c.png">

Rendered Block
<img width="1920" alt="screenshot_55" src="https://user-images.githubusercontent.com/2078245/58302439-69cabb00-7e2e-11e9-9b3e-669134326d46.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Firefox Qunatum 66.0.5
 - Version: WP 5.2.1

**Comment by talldan** [comment]
Thanks for the report @maddisondesigns. This has already been fixed in https://github.com/WordPress/gutenberg/pull/15625.
