### ISSUE TITLE
Internet Explorer 11: "Write" placeholder visible when you Write.

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1580]
In Internet Explorer 11, the Write "placeholder" is still visible when typing in the field:

![screenshot 118](https://user-images.githubusercontent.com/1682452/27681873-df252d04-5cc0-11e7-83f2-81e101664aa9.png)

**Comment by mtias** [comment]
@afercia is this still a problem (we have changed how placeholders are presented on focus).

**Comment by afercia** [comment]
@mtias sorry can't test in IE 11 right now 🏖

**Comment by mtias** [comment]
This should no longer be an issue as focus hides the placeholder text.
