### ISSUE TITLE
Apostrophe use in WordPress posts and pages with escaping issues

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#15816]
This was previously reported on trac:

https://core.trac.wordpress.org/ticket/47328

"I raised a ticket with Yoast at https://github.com/Yoast/wordpress-seo/issues/12970 due to an issue I thought was with the Yoast SEO plugin, yet it turns out it is a flaw in the WordPress software coding.

If you have a word or phrase wrapped with apostrophes for single quote marks, or you have two or more words with apostrophes in the same paragraph, you can have issues where the apostrophes are not escaped in the output for PHP and JavaScript purposes. Because (I am assuming) Gutenberg is supposed to help those who know little to no HTML, I feel this is a serious flaw to a degree.

Whilst semantically it is incorrect to do so, most people do use apostrophes as single quote marks due to the fact that the correct character is not available on a standard computer keyboard. Those who do know about HTML entities can overcome this issue, but can we please have WordPress software correct the HTML output with &apos; when the apostrophe is typed?
Thinking about the issue, maybe double quotation marks should also be substituted with &quot;.

The only issue I can see with this is that a forewarning would need to go out to plugin and theme developers such as WooCommerce before the changes are implemented as it may affect the way data is saved, retrieved and outputted within their plugins etc."

**Comment by swissspidy** [comment]
Reading the original bug report by @rogersopen it seems to me that Yoast SEO simply doesn‘t properly escape its regex.

As for the apostrophe, WordPress should already convert them on the frontend thanks to the wptexturize function.

**Comment by rogersopen** [comment]
Please note that what I wished to point out is that apostrophe should be converted to html entity `&apos;` and double quote marks should be `&quot;`.  For some unknown reason, the code escaped entities I posted have been converted to the relevant characters in the question

**Comment by tellthemachines** [comment]
Is this still an issue? I tried adding sequences of `'` and `"` in the editor and it doesn't do anything unexpected. Was the issue reproducible specifically with the Yoast plugin?

**Comment by jordesign** [comment]
With no further input on this issue, and given it seems it is specific to Yoast's plugin (unless we hear otherwise) I'm going to close this issue.

If further testing shows the issue still exists - please re-open with the additional details
