### ISSUE TITLE
Avoid trailing space at the end of a translatable string

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#15813]
Original report: https://core.trac.wordpress.org/ticket/47374

Source:
https://github.com/WordPress/gutenberg/blob/636b7bf072a4365d5c41fec07872a81fe0247516/packages/edit-post/src/components/sidebar/post-link/index.js#L89-L94

We should make sure that it's always there instead of relying on translators to not miss the trailing space in the string.

**Comment by swissspidy** [comment]
We could simply add `{ ' ' }` in there.

Of course ideally these wouldn't be separate strings (see #9846) at all.
