### ISSUE TITLE
Multiple Facebook Embeds Cause Display Issues

### ISSUE THREAD

**Issue by coolbluematt** [WordPress/gutenberg#15824]
**Description**
I've found that when using two facebook embed blocks on one blog post (multiple posts, post+image, post+video), the scaling misfires, causing embeds to overhang the container. Have tested on latest WP version (5.2.1) with twentynineteen theme. (Note that videos seem to be the only purely "responsive" fb embeds, with posts and images resizing on refresh rather than on screen resize--videos are not affected by this behavior).

As a starting point, I think I've narrowed it down to the fact that the facebook sdk.js is loaded within each facebook embed block. On a simple test html page, if I load the sdk a single time in the header and add multiple fb-post or fb-video divs, they size to their container on refresh. 

**Reproduction**

1. Add one facebook embed block (post or photo).

2. Scale down the window to be narrower than the post. 

3. Refresh the window --- you should see the post is scaled to fit into the viewport.

4. Add a second facebook embed block.

5. Repeat steps 2 & 3. The posts are no longer scaling correctly. Depending on loading times, you may see a flash where they appear to be scaled to fit, and then they update to overflow the window.

**Expected behavior**
I would expect that multiple embeds would behave the same way as a single one, scaling to fit container if between 750px and 360px (on refresh).

**Screenshots**
Simple HTML page with one sdk inclusion and multiple embeds (via fb-post div):
![image](https://user-images.githubusercontent.com/16826006/58360516-06488980-7e3e-11e9-8bd0-c68df8199768.png)

Wordpress twentynineteen theme with sdk inclusion for multiple blocks:
![image](https://user-images.githubusercontent.com/16826006/58360544-3001b080-7e3e-11e9-9f92-546bcfa3457f.png)

**Desktop:**
 - OS: Mac OSX Mojave
 - Browser: Tested in Chrome(74.0.3729.169), Firefox(66.0.5), Safari(12.0.2)

**Smartphone:**
 - Scaling for mobile device seems to still fire as expected scaling embeds to 360px wide

**Additional context**
- WordPress 5.2.1

Let me know if you have any further questions or clarifications. Apologies if I've missed a similar issue (did a quick issue search to verify) or if I'm misunderstanding the issue.

Thanks!

**Comment by ehti** [comment]
I can reproduce this.

Single embed does scale (add an embed, open the post, zoom in. Then refresh).

If you add a second embed and do the same, it doesn't scale anymore.

**Comment by talldan** [comment]
Facebook embeds are now not supported, so closing this.
