### ISSUE TITLE
Table block: Text alignment (none, left, center, right)

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15823]
The Table block currently does not allow for text alignment within a cell. Users can benefit from text alignment within a cell when using numbers, dates, money. Often times these values are aligned right. This can't be done currently.

These options:

![Screen Shot 2019-05-24 at 1 34 59 PM](https://user-images.githubusercontent.com/617986/58355320-d5aa2500-7e28-11e9-8820-57d9dd62f529.png)

Should exist in the Table block toolbar.

![Screen Shot 2019-05-24 at 1 37 37 PM](https://user-images.githubusercontent.com/617986/58355416-1efa7480-7e29-11e9-81f3-ffad58bcd9fd.png)

This was initially noted in https://github.com/WordPress/gutenberg/issues/6923 by @helen. I'm pulling it into it's own issue.

**Comment by mtias** [comment]
This is an easy but very welcome addition. We should prioritize it for Tables.

**Comment by talldan** [comment]
Here's a PR for text alignment - https://github.com/WordPress/gutenberg/pull/16111.

I'll remove 'Needs Design' from this issue, as I've put 'Needs Design Feedback' on the PR :)
