### ISSUE TITLE
Gutenberg plugin throwing errors (possible attack?)

### ISSUE THREAD

**Issue by m4tek** [WordPress/gutenberg#15829]
It looks like there is active attack on gutenberg, but I was not able to track the vector, as Cerber and modsec blocked them. There are few sites reporting this error publicly:

https://www.google.com/search?q=%22Call+to+a+member+function+query%28%29+on+null+in%22+%22wp-content%2Fplugins%2Fgutenberg%2Flib%2Fclient-assets.php+on+line+58%22&oq=%22Call+to+a+member+function+query%28%29+on+null+in%22+%22wp-content%2Fplugins%2Fgutenberg%2Flib%2Fclient-assets.php+on+line+58%22

[Sat May 25 00:16:40.614841 2019] [:error] [pid 5310] [client 142.117.237.39:65229] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 00:16:40.969883 2019] [:error] [pid 5308] [client 142.117.237.39:65242] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 00:16:41.230248 2019] [:error] [pid 5312] [client 142.117.237.39:65248] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 00:16:41.497789 2019] [:error] [pid 5382] [client 142.117.237.39:65260] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 00:27:43.557976 2019] [:error] [pid 5308] [client 2001:41d0:a:fc3e::1:13972] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 01:01:48.286609 2019] [:error] [pid 5311] [client 2001:41d0:a:39ef::1:42572] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 01:36:09.193540 2019] [:error] [pid 5310] [client 79.137.109.83:55061] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:10:45.943101 2019] [:error] [pid 5806] [client 2001:41d0:a:ff34::1:52061] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:37:26.782353 2019] [:error] [pid 5312] [client 162.212.255.210:49250] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:37:27.463494 2019] [:error] [pid 5806] [client 162.212.255.210:49317] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:37:27.914899 2019] [:error] [pid 5309] [client 162.212.255.210:49365] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:37:28.311874 2019] [:error] [pid 5382] [client 162.212.255.210:49402] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 02:45:17.406797 2019] [:error] [pid 5311] [client 2607:5300:60:f6e::1:28283] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 03:19:36.911332 2019] [:error] [pid 5311] [client 2607:5300:60:4037:::30015] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 03:54:16.853509 2019] [:error] [pid 5312] [client 51.254.155.40:48248] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 04:28:30.409918 2019] [:error] [pid 5312] [client 178.32.46.62:22414] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 05:02:44.801737 2019] [:error] [pid 5309] [client 2607:5300:60:f6e::1:58987] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58
[Sat May 25 05:37:06.941149 2019] [:error] [pid 5382] [client 2607:5300:60:d15::1:3826] PHP Fatal error:  Call to a member function query() on null in <snip>wp-content/plugins/gutenberg/lib/client-assets.php on line 58

**Comment by nerrad** [comment]
On the surface this does not look like an attack and there isn't enough information to troubleshoot further.

If a security issue is discovered, the proper place to report can be found [here](https://github.com/WordPress/gutenberg/blob/master/SECURITY.md).
