### ISSUE TITLE
Reusable Blocks: allow to cancel changes

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#15838]
**Describe the bug**
When you edit a reusable block in the context of a post/page, you have no way to cancel your changes except a full page refresh.

**To reproduce**
1. Go to a post
1. Add a block to a Reusable blocks
1. Save
1. Click on the Edit button
1. Make some changes
1. Try to cancel your changes

**Expected behavior**
There should be a way to cancel changes in the block UI.

**Additional context**
Tested with WordPress 5.2.1 and Gutenberg 5.7

**Comment by swissspidy** [comment]
Related: #12940

**Comment by paaljoachim** [comment]
Let's close this issue and stay with the other issue @swissspidy mentions instead.
