### ISSUE TITLE
Image can’t align center inside block column

### ISSUE THREAD

**Issue by marybaum** [WordPress/gutenberg#15832]
**Describe the bug**
Centered images in block columns don't in fact center in the rendered post, and in some cases, as the trac ticket #47290, they don't offer a centering option in the block editor.
**To reproduce**
User's demo: http://232.email/myav/2019/05/16/7/

**Expected behavior**
When we center a pic in a column, it should center.

**Screenshots**
In 2019, in Mac Chrome 74, things look great in the block editor.
![Screen Shot 2019-05-26 at 2 05 12 PM](https://user-images.githubusercontent.com/3679459/58386535-c365ed80-7fc6-11e9-906f-a7b70fc21441.png)
But on the front end, in the rendered post:
![Screen Shot 2019-05-26 at 2 28 18 PM](https://user-images.githubusercontent.com/3679459/58386550-fd36f400-7fc6-11e9-9d00-b1307d607ee4.png)
No joy. (That's a US military term -- hubs is retired defense contractor, which is a big part of how I get to do this work!)

**Additional context**
I think we can solve this by editing the CSS. 
I did it in the moment by changing the image width and margin; we could also be more compatible with modern themes by writing the block CSS here in Flexbox. 

Patch upcoming!

**Comment by nerrad** [comment]
I can confirm the same exists as of this comment in Gutenberg master:

In the editor:

![editor example](https://www.evernote.com/l/AAMWcl-F5zlDWZakngssUEtsHuNrhc3jYRsB/image.png)

In the frontend (2019 theme):

![frontend example](https://www.evernote.com/l/AAPWQd-R029La5gEYHcAYFNnDYeI8oCLRQwB/image.png)

**Comment by marybaum** [comment]
Excellent! We're seeing the same thing.

**Comment by youknowriad** [comment]
It's the theme's responsibility to provide the styles for `alignright`/`alignleft`/`aligncenter`...
This leads me to think that this is a theme issue. cc @kjellr
