### ISSUE TITLE
 If user uses the normal editor and the default "Paragraph" block, then the toolbar is not getting displayed until the user adds content within the "Paragraph" block. But if user is selecting the top toolbar option, then the tools are getting displayed even if there is no content is added in the block.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#15846]
Steps to follow :

1. Open Editor.
2. Click on the default paragraph block and add content to it.
3. Remove the paragraph content and the toolbar above the block get disappear.
4. Now select the top toolbar option. 
5. Click on the default paragraph block and add content to it. Remove the paragraph content 
6. Check top toolbar. It should not display the top toolbar until any content is added.

https://www.screencast.com/t/oFE4qZybW

**Comment by youknowriad** [comment]
This is a duplicate issue. It's going to be hard for me to find the issue right now but I'm certain we have one :)

**Comment by nayana96249** [comment]
Thanks for your update. Please let me know once you find the original ticket. 👍

**Comment by youknowriad** [comment]
Ok I think I found it https://github.com/WordPress/gutenberg/issues/9063 Please add your thoughts there.

**Comment by nayana96249** [comment]
@youknowriad , I m trying to say here is that, Please check below screenshot 
https://www.screencast.com/t/SvKTxRFsAId

**Comment by youknowriad** [comment]
@nayana96249 yes, understood and that's exactly what the linked issue is about.
