### ISSUE TITLE
Selecting text block then selecting Bold/Italic etc should affect all text in block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15843]
This issue is probably already reported but I am not sure what to search for so I am adding it here.

1. Selecting a text block.
2. Then selecting Bold/Italic/Link etc
3. All text in the block should become affected by clicking Bold/Italic....

Right now if one has a block selected and clicks Bold the cursor begins to blink at the end of the text. One has to manually select the text to have it become Bold. It can be difficult in manually selecting all the text with the result that most is bold but perhaps not the first letter so that one has to reselect all of it click to turn off Bold and then on again. It is a bit cumbersome.

Hovering over the Bold button. (No text selected)
<img width="702" alt="Screen Shot 2019-05-27 at 12 13 10" src="https://user-images.githubusercontent.com/5323259/58413380-e7820700-8078-11e9-85f1-9ba91a33c285.png">

Clicking the bold button cursor is added at the end of the text.
<img width="641" alt="Screen Shot 2019-05-27 at 12 13 27" src="https://user-images.githubusercontent.com/5323259/58413389-ef41ab80-8078-11e9-8d97-9acb832af62b.png">

**Comment by ellatrix** [comment]
I don't understand the problem. You want bold to be applied on something that is not selected? Could you explain the problem more? Perhaps a video of another editor of how it should work?

**Comment by paaljoachim** [comment]
Hey Ella

To make something bold one clicks into the text block and selects the text one wants bold.
I am thinking that there should be a quick way to make all the text in the text block bold. Such as select the text block and click bold and all the text becomes bold.

![Select-text-block-then-bold](https://user-images.githubusercontent.com/5323259/60273929-75127a00-98f7-11e9-83bb-c521c1d05c28.gif)

**Comment by ellatrix** [comment]
I've never seen anything like this implemented before. It's sounds like strange behaviour to me tbh. You can select the whole paragraph text by triple-clicking the text.

**Comment by paaljoachim** [comment]
Well I was thinking that as a user selects a block and clicks italic/bold etc that the text content automatically becomes italic/bold etc. It just easier styling all the text in the block.
