### ISSUE TITLE
Featured image uses wrong default size

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#15842]
**Describe the bug**
By default gutenberg tries to load the featured image with the image size `post-thumbnail` in the editor sidebar:
https://github.com/WordPress/gutenberg/blob/c4cd4d8877087d08a80bbba9d4bf5f4f45cd6e83/packages/editor/src/components/post-featured-image/index.js#L34

This image size does not exist by default. The correct image size would be `thumbnail`.
See the default image sizes in the Codex: https://codex.wordpress.org/Post_Thumbnails#Thumbnail_Sizes

Because the specified image size does not exist, the `full` size is used as a fallback. 
This causes a performance issue, because a potentially far too large image is loaded.

**To reproduce**
1. Create a Post
2. Add a Featured image in a large size e.g. 2000px wide
3. Right-click on the image and choose "open image in new window"
4. You can see the image in full size.

**Expected behavior**
The Featured image should be loaded in a smaller version/thumnail site within the editor sidebar.

**Desktop:**
 - OS: OS X 10.13.6
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
- Gutenberg Version 5.8.0-rc.1

**Comment by derweili** [comment]
I think there should be a discussion which image size should be used in the editor sidebar. 
Maybe `medium` is better than `thumbnail` because it's not cropped by default.

**Comment by senadir** [comment]
WordPress uses medium size by default in the old editor so I think this should be respected in gutenberg as well
