### ISSUE TITLE
Links can be added to the Button Block's text using the shortcut

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#15858]
**Describe the bug**
The button block has its own UI for adding links. However, a user can also highlight the text in the button when editing a button block and use Cmd+K or Ctrl+K to add link formatting to button text.

This duplication is confusing.

**To reproduce**
1. Create a new post
2. Add a button block
3. Type some text in the button
4. Highlight the text in the button
5. Use the Cmd+K (Mac) or Ctrl+K (Windows/Linux) keyboard shortcut
6. Observe that link formatting can be applied to the button's text.

**Expected behavior**
The link format should be disabled on the button block as it has its own interface for adding links.

**Screenshots**
![Screen Shot 2019-05-28 at 4 25 01 pm](https://user-images.githubusercontent.com/677833/58462842-46bd4580-8165-11e9-84a8-34b5d82da2c0.png)

**Additional context**
Discovered while testing #10128

**Comment by epiqueras** [comment]
This line:

https://github.com/WordPress/gutenberg/blob/5cb8b8f3a025e4ecf24b9b3ec31988b2c7b02d5c/packages/block-library/src/button/edit.js#L81

excludes the "link" rich text format from the toolbar (and hotkeys?), but it doesn't seem to be doing anything.

cc @ellatrix

**Comment by chrisvanpatten** [comment]
I’ve noticed this as well - it seems like the behaviour around which controls are visible does not impact all keyboard shortcuts.

**Comment by chrisvanpatten** [comment]
(Also worth noting that the formats in the drop down are visible even though they aren’t explicitly enabled in formattingControls.)

**Comment by ellatrix** [comment]
Should be fixed by #14542.
