### ISSUE TITLE
CSS Hell between Default editor style and Frontend style. Both are messy to match.

### ISSUE THREAD

**Issue by leodluz** [WordPress/gutenberg#15855]
**Describe the bug**
The post displayed on the site is not identical to the post made on gutenberg.

**To reproduce**
1 - Create a custom template
2 - Try to make a post made in gutenberg look exactly the same on the site.

**Expected behavior**
That the post displayed on the site, was the same done in the gutenberg editor, with the same formatting.

**Screenshots**
Editor:
![image](https://user-images.githubusercontent.com/22651765/58444558-29d63300-80cf-11e9-9e59-244a45c1007b.png)
Frontend:
![image](https://user-images.githubusercontent.com/22651765/58444565-30fd4100-80cf-11e9-892c-509b448eea3e.png)

It is difficult and laborious to make a new style to look exactly like the editor. There could easily be a feature that puts a default gutenberg .css on the site, so that it fits exactly with what was made editor. Both the editor and template styles should be exactly the same file, to avoid disparity.

in this article [here](https://binaryfork.com/wordpress/tutorials/style-gutenberg-to-match-frontend-459/) it says that it is not possible to make the post in the frontend exactly the same as the one in the editor. This MUST be possible and would be very easy if both shared the same css. Create a wrapper to isolate these element styles from the remainder of the frontend and the administrator panel.

**Comment by swissspidy** [comment]
Hi! Which theme are you using?

It’s worth noting that there are shared stylesheets between Gutenberg and the theme, but it‘s ultimately up to the theme to provide a seamless experience.

**Comment by leodluz** [comment]
Hi! Thanks for the answer!

I'm creating my own theme. I'm still a beginner and this question put me in a sea of confusion. But after a whole day I was able to understand how mescanism works. Now I know how to proceed.

a suggestion to simplify the gutenberg:
       Provide a css file with guttenberg default styles to use on frontend. And put that in the documentation.

Thank you for the attention, success to you!

**Comment by swissspidy** [comment]
Good to know, thanks. I'm therefore closing this issue. 

> Provide a css file with guttenberg default styles to use on frontend. And put that in the documentation.

There's `add_theme_support( 'wp-block-styles' );` for that.

The [block editor handbook](https://developer.wordpress.org/block-editor/) has a detailed guide about adding theme support for the block editor: https://developer.wordpress.org/block-editor/developers/themes/theme-support/

**Comment by leodluz** [comment]
"add_theme_support( 'wp-block-styles' );"
I already used this one, it is not complete.

**Comment by leodluz** [comment]
https://developer.wordpress.org/block-editor/developers/themes/theme-support/
Já li este link muitas vezes também.
