### ISSUE TITLE
Consider implementing the block appender in the Post Title input

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#15851]
Some feedback was reported to me that it's confusing that you can use the "/" inserter in the default placeholder but not the "post title" especially when starting a new post.

**Comment by kjellr** [comment]
I spent a few minutes mocking this up. I was originally concerned that it'd be weird to be using the super bold text up there, but it actually seems okay to me. 

The main potentially confusing bit would be the focus jump from the title to the inserted block. It theoretically makes sense, but it feels just a little weird to have the title revert back to its placeholder state. 

**[▶️ Figma Prototype](https://www.figma.com/proto/bRJiDlhHxpa9hiTIKHKVmx23/Untitled?node-id=0%3A1&viewport=290%2C361%2C0.125&scaling=min-zoom)**

---

![02](https://user-images.githubusercontent.com/1202812/58975020-f0b65680-8791-11e9-8512-dbcc96fe926a.png)

![03](https://user-images.githubusercontent.com/1202812/58975021-f14eed00-8791-11e9-9599-8f519d349d44.png)

![04](https://user-images.githubusercontent.com/1202812/58975464-037d5b00-8793-11e9-93fa-53604a6007b1.png)

**Comment by mapk** [comment]
This was discussed in [today's triage meeting in slack](https://wordpress.slack.com/archives/C02S78ZAL/p1561481387363000). 

While @kjellr's mockups would solve the issue, it feels like the whole thing might be a non-issue until the Title area becomes an actual block. Using the `/` is a way to add a new block to the specified wherein one is typing, and the Title area isn't meant to respond that way. The outcome could be more confusing than the current behavior.

I opt for no action here until the Title area becomes an actual block in which case it makes much more sense.

**Comment by draganescu** [comment]
#16281 This issue appears to include this one as well. If the title becomes a block then it will support the appender by default. I am closing this in favour of the one mentioned, we'll see how the UX will be handled when the editor will include title as a block.
