### ISSUE TITLE
When adding a button block, the URL Input receives focus first

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#15859]
**Describe the bug**
When adding a button block, the URL Input field receives focus first, even though it's the second editable text field displayed to users.

**To reproduce**
1. Create a new post
2. Add a button block
3. Observe that the link input field receives focus

**Expected behavior**
The button text should receive focus as it's the first editable item presented.

**Additional context**
Discovered while testing #10128

**Comment by senadir** [comment]
fixed in #15951
