### ISSUE TITLE
The featured image panel layout breaks with small images

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15853]
In the Classic Editor, when setting a small featured image, the meta box layout works nicely. Actually, the image has only a max-width to honor: if it's smaller than the available space, its container adapts and the meta box doesn't break.

Instead, in Gutenberg there's a responsive component that works well only with large images. With small images, the container takes all the available width (and extra height), breaking the layout.

See in the screenshot below:
- on the left: 150 by 150 pixels image in Gutenberg
- on the right: the same image in  the Classic Editor

<img width="643" alt="Screenshot 2019-05-27 at 21 43 05" src="https://user-images.githubusercontent.com/1682452/58437552-be8a6200-80ca-11e9-8a16-95cb516d56b7.png">

Also: in the responsive view this panel needs some improvements, including the position of the buttons:

<img width="469" alt="Screenshot 2019-05-27 at 21 53 03" src="https://user-images.githubusercontent.com/1682452/58437586-e679c580-80ca-11e9-9241-e816812c24b7.png">

**Comment by kjellr** [comment]
@afercia can you share what browser you're seeing that in? It looks a bit different in my testing. The scaling up of a small image in my screenshots isn't great, but I'm not seeing the big empty space in your screenshots. 

**Desktop:**
<img width="280" alt="Screen Shot 2019-05-30 at 4 21 14 PM" src="https://user-images.githubusercontent.com/1202812/58662067-5371a300-82f7-11e9-8c7a-7a7e3719dcdc.png">

**Mobile:**
<img width="341" alt="Screen Shot 2019-05-30 at 4 23 21 PM" src="https://user-images.githubusercontent.com/1202812/58662068-540a3980-82f7-11e9-8f10-6d976afe621e.png">

Tested in Chrome, Safari, and FF on a Mac.

**Comment by afercia** [comment]
@kjellr I tested with the Gutenberg version in core and can still reproduce with all browsers.

I see that in the plugin version small images are scaled up like in your examples. I'd argue that's not correct as well 🙂 If, as a user, I upload a 150x150 image I don't want to see it scaled up.

**Comment by kjellr** [comment]
Ok cool — something must've changed in the plugin vs. core version. Agreed that the scaling up isn't great. In the meantime, I've opened a quick PR to address the positioning of the "Remove Featured Image" button: #15928

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7 RC1
Twenty Twenty One
Gutenberg plugin 10.0.2
Chrome.

I believe this issue has been fixed a while ago.
I am retesting using different size featured images.

280x400px
<img width="380" alt="Screen Shot 2021-03-02 at 22 22 43" src="https://user-images.githubusercontent.com/5323259/109717180-01ce0a80-7ba6-11eb-8c81-bbbd672c0752.png">

451x787px
<img width="382" alt="Screen Shot 2021-03-02 at 22 23 03" src="https://user-images.githubusercontent.com/5323259/109717237-13171700-7ba6-11eb-9683-fb3e87aafca1.png">

I am closing the issue. Please reopen if I am mistaken.
