### ISSUE TITLE
Ability to add a caption to a Gallery

### ISSUE THREAD

**Issue by DrBeta** [WordPress/gutenberg#15854]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have the ability to add a caption, like on a picture to a slideshow.

**Describe alternatives you've used**
Add a text block below the slideshow and center it.

**Comment by swissspidy** [comment]
I don‘t think there‘s a slideshow block by default. Did you use a plugin to add that? Or are you referring to the gallery block?

**Comment by DrBeta** [comment]
Yes, I'm using the gallery block

**Comment by melchoyce** [comment]
Hey @DrBeta, can you take a screenshot of your slideshow?

**Comment by kwight** [comment]
I think this can be closed since the merge of https://github.com/WordPress/gutenberg/pull/17101
