### ISSUE TITLE
Images: Adding images to a post doesn't also attach it 

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1586]
This can cause theme issues.

**Comment by aduth** [comment]
Should be fixed as of #1967

**Comment by rachelmcr** [comment]
I tested publishing a photo post in Gutenberg 1.4.0 and the photo wasn't attached. Video of my publishing flow and other details here: https://test.wordpress.com/2017/10/13/image-posting-flow-gutenberg/

**Comment by aduth** [comment]
To clarify, this appears to be specific to drag-and-drop upload, which uses its own implementation to upload to the WordPress REST API. Uploading using the media library within Gutenberg will correctly attach the image to the post.

**Comment by aduth** [comment]
The naive answer would be to inject `_wpMediaViewsL10n.settings.post.id` as `parent` property in the media upload:

https://github.com/WordPress/gutenberg/blob/23288283d86c25620d76ba058d200a9576d0d0a1/utils/mediaupload.js#L74-L77

But...

- Something is clobbering ``_wpMediaViewsL10n.settings` at runtime and it isn't accessible after page loda
- This ties the media upload tool to the presence of a window global, and is less predictable by its implicitness (not pure). Ideally that which calls the upload would also pass the post ID as an argument.

For drag-and-drop, that happens in the image block transform:

https://github.com/WordPress/gutenberg/blob/23288283d86c25620d76ba058d200a9576d0d0a1/blocks/library/image/index.js#L69-L81

This ties into #2473, where blocks (let alone transforms) don't currently have easy access to post state.

**Comment by theleemon** [comment]
Is the "Attached to this post" idea going to be deprecated with Gutenberg? I'm asking this because some custom post types I've seen out there (Portfolio, Events, Ads, etc...) use this to just display images attached to posts.

**Comment by bobbingwide** [comment]
Please can someone give this bug the attention it deserves? It's a backward compatibility issue.

**Comment by bobbingwide** [comment]
I’d just like to point out that this problem occurs when using the Upload button in the Image block.

**Comment by danielbachhuber** [comment]
@joemcgill Did you get anywhere on this or can I help out with it?

**Comment by joemcgill** [comment]
@danielbachhuber haven’t looked at it yet. Was hoping to have a go at it soon, but feel free.
