### ISSUE TITLE
Link dropdowns are layered awkwardly

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15872]
**Describe the bug**
There are two difference dropdowns that appear when attempting to link a word. 

**To reproduce**
1. Add some text.
2. Highlight a word to make into a link.
3. Click the link icon in the toolbar.
4. Click the arrow in the link dropdown.
5. Leaving that open, begin typing in the field and observe another dropdown.

**Expected behavior**
When one dropdown appears, the other should disappear.

**Screenshots**

![link](https://user-images.githubusercontent.com/617986/58520599-66f10280-816d-11e9-84fc-080f2d58fd34.gif)

Tested in Firefox.

**Comment by ehti** [comment]
UI of Link dropdowns have changed and I can't seem to reproduce it either, so closing it. Let me know if I missed something. :)
