### ISSUE TITLE
Translations missing when using Bedrock

### ISSUE THREAD

**Issue by Furo42** [WordPress/gutenberg#15889]
Most of the translations in the backend of the block editor are missing when using the Bedrock Boilerplate.
The translations were installed correctly.

A similiar problem was described in this topic and marked as fixed.
https://core.trac.wordpress.org/ticket/45528
Also this Bug happens only with the separate Gutenberg-Plugin. There is no problem when using the block editor in Wordpress 5.2.1.

**To reproduce**
1. Install WordPress with Bedrock Boilerplate (see https://roots.io/bedrock/)
2. Use a different language than English
2. Install Gutenberg Plugin with Composer or within the WP-Admin and activate it
3. Create a new Post
4. The Blocks and the Boxes on the right Sidebar are shown in English

**Screenshots**
![bedrock gutenberg bug](https://user-images.githubusercontent.com/51162201/58560425-64ea7a80-8225-11e9-97fc-a19665f7e24c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 74, Firefox 67

**Additional context**
- Tested with Gutenberg Version 5.7.0 and 5.8.0

**Comment by swissspidy** [comment]
I fail to see how this is an issue of the plugin.

Is the plugin fully translated to German? Did you install the latest translations in your WordPress admin and are there any translation files in wp-content/languages/plugins?

**Comment by Furo42** [comment]
The most strings are translated. The best indicator is the string "Status and Visbility" at the right sidebar which should be "Status und Sichtbarkeit" in German.
Also this happens only when using the Bedrock Boilerplate which is similiar to a subdirectory install with custom wp-content directory.
But this bug doesn't appear when WordPress is installed in a subdirectory. 

All translations are installed and located in "web/app/languages/plugins" ("app" is the wp-content custom directory). I copied them also to "web/wp/wp-content/languages/plugins/" (The WordPress directory in Bedrock) but this doesn't solve the problem.

I used WP 5.2.1 and all translations were installed via WordPress admin.

**Comment by swissspidy** [comment]
> Also this happens only when using the Bedrock Boilerplate which is similiar to a subdirectory install with custom wp-content directory.
> But this bug doesn't appear when WordPress is installed in a subdirectory.

In that case it's either a bug in your Bedrock setup _or_ in WordPress core because of the custom directory structure. 

Have you asked in the Bedrock support forums to see if someone has a similar issue?

Does this happen with other plugins like Yoast SEO as well?

**Comment by retlehs** [comment]
> or in WordPress core because of the custom directory structure.

most likely — see https://roots.io/bedrock/docs/bedrock-compatibility/

**Comment by strarsis** [comment]
Is there any open issue on WordPress trac concerning issues with translations in WordPress sites using custom (but valid) paths? I still have this issue: Bedrock site, Gutenberg plugin, installed language files using WordPress CLI. Other plugins correctly display the translated text - except the Gutenberg editor.

**Comment by Furo42** [comment]
I close this issue. I updated Bedrock to the latest version and now the translationes are available.

**Comment by strarsis** [comment]
@Furo42: Thanks for the hint! I will try this out right away, it is a very annoying issue.
