### ISSUE TITLE
Standardize collapsible arrows

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#15881]
**Describe the bug**
In some places around the post editor, different arrow icons are used than in other places. Notably, legacy metaboxes use a triangle, while sidebar collapsibles use the chevron.

<img width="383" alt="Screen Shot 2019-05-29 at 11 17 10" src="https://user-images.githubusercontent.com/6073772/58545327-51c6b300-8203-11e9-93fd-db9d3116ff1f.png">

**Expected solution**
We should standardize it to the chevron everywhere.

**Comment by draganescu** [comment]
Should we have a list of all the places? #16100 solves for the metaboxes, but which are the other places using wrong icons?

**Comment by carolinan** [comment]
Can we close this, since there are no other reported places?
