### ISSUE TITLE
link to tickets 

### ISSUE THREAD

**Issue by Otshelnik-Fm** [WordPress/gutenberg#15882]
https://github.com/WordPress/gutenberg/releases/tag/v5.8.0 how do I see links to tickets and commits (pull request)?
https://github.com/WordPress/gutenberg/releases/tag/v5.7.0 - here they are given links. It's important to me

**Comment by Soean** [comment]
This is caused by the new release process. You can see the links in this blog post https://make.wordpress.org/core/2019/05/29/whats-new-in-gutenberg-29th-may/

**Comment by youknowriad** [comment]
I'll add the links there.

**Comment by youknowriad** [comment]
I used a tool to convert HTML to markdown. It should be better now.
