### ISSUE TITLE
Expose focusOnMount <Popover> property in <Dropdown> component

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#15898]
**Is your feature request related to a problem? Please describe.**
When using the `<Dropdown />` component, I'd sometimes like to be able to set the `initialFocus` to the `container` instead of the `firstElement`.

**Describe the solution you'd like**
Expose `focusOnMount` in the `<Dropdown />` component so I can do `<Dropdown focusOnMount="container" />`.

**Describe alternatives you've considered**
The `<Dropdown />` component is thin enough that it is possible to reimplement when necessary. But having to do the `closeIfClickOutside` bit is annoying.

Happy to PR.

**Comment by talldan** [comment]
@TimothyBJacobs This prop already seems to be exposed on `Dropdown`:
https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown#focusonmount

I'll close the issue, but let me know if I've misunderstood and I'll reopen.

**Comment by TimothyBJacobs** [comment]
Ack, was looking at an older version of the file. Thanks @talldan.
