### ISSUE TITLE
Consider adding text-level color settings to all text blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15899]
Issues like #8171 are exploring block-level color settings for text and backgrounds. It might be equally beneficial to include text-level color settings in Gutenberg as well. In the future (props @mtias) I can see having site-level settings -> block-template-level settings -> block-level settings -> text-level settings. We need to figure out how to surface this UI and how it works together for the greater whole.

This being said, let's explore how we might add text-level color settings to the blocks. These settings would include, but not limited to:

1. Text color
2. Text highlight color

I know @phpbits and @ellatrix have both looked into this already.

**Comment by phpbits** [comment]
In need of better icon but here's what I have on Text Highlight Color. Don't we need Background Color on Text Highlighting also? Thanks!

<img width="701" alt="Screen Shot 2019-05-30 at 9 23 45 AM" src="https://user-images.githubusercontent.com/3365507/58601749-d9242d00-82bc-11e9-83fe-0fe53f3a0daa.png">

Regarding Text Color, I think it's better to have this similar across all blocks like what's been added recently on Heading Block.

Thanks @mapk!

**Comment by mapk** [comment]
> Don't we need Background Color on Text Highlighting also? 

Probably my bad terminology, but when I said "highlight color" I meant the background color of the text one highlights. 

> Regarding Text Color, I think it's better to have this similar across all blocks like what's been added recently on Heading Block.

I think there's a case for having the ability to change specific highlighted text colors and be able to change the whole block's text color. One is a text-level control and the other is a block-level control. And as the settings get more specific they begin to trump the other. So a text-level control would trump a block-level control.

**Comment by phpbits** [comment]
> Probably my bad terminology, but when I said "highlight color" I meant the background color of the text one highlights.

I see. In this case, both color options should be easily available on the toolbar format.

<img width="734" alt="Screen Shot 2019-05-30 at 10 30 30 AM" src="https://user-images.githubusercontent.com/3365507/58604344-9a937000-82c6-11e9-9a43-0de68d5d055e.png">

Block level color control should be the same as Paragraph block in my opinion. Having similar panels across blocks are easier to understand.

**Comment by mapk** [comment]
Thanks @phpbits for the mockups. Here's some early feedback.

1. I really like moving this to the toolbar. While it's not an "important" action, it's one that is more focused than just a block-level setting.
2. The heading, "Highlighted Text Settings" could be dropped entirely. The two labels should be sufficient.
3. Let's change the label for "Background Color" to "Highlight Color". Similar to Google Docs.
![colors](https://user-images.githubusercontent.com/617986/58891531-84f4c080-86a1-11e9-838a-ab9ffd97c2ac.gif)

**Comment by phpbits** [comment]
@mapk I've tried that before too, from Google Docs right? I just don't want users to have too much icon on the toolbar. It's probably better though, I'll try and create a PR for that. This will be my first PR so my apology in advance if I may do it incorrectly.

**Comment by phpbits** [comment]
@mapk Do you like this one for Text Color? Thanks!

![Screen Capture on 2019-06-05 at 12-01-12](https://user-images.githubusercontent.com/3365507/58929607-6b7b7380-878a-11e9-8805-fe0c4f6fb2b1.gif)

**Comment by phpbits** [comment]
@mapk Just created my first PR for text color. I need guidance on proper testing though if I missed something. Thanks a lot in advance.

**Comment by mapk** [comment]
> I just don't want users to have too much icon on the toolbar.

@phpbits I wasn't saying split them out into different icons... I meant just use the terminology they were using for each of the two color sections, ie. "Text color" and "Highlight color". I'm fine with keeping them together. I need to test your PR and I'll leave some comments there.

**Comment by mapk** [comment]
Because the PR https://github.com/WordPress/gutenberg/pull/16014 is being worked on, I'm going to remove the `Needs Design Feedback` label from this issue. Let's move the comments over there.

**Comment by youknowriad** [comment]
Seems like this is done now right?
