### ISSUE TITLE
Widget Screen ( Experimental ) issue with Popovers

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#15901]
**Describe the bug**
Popovers are having odd behavior. Not showing where it supposed to be.

**To reproduce**
1. Go to Gutenberg > Widgets(beta)

![Screen Capture on 2019-05-30 at 09-15-09](https://user-images.githubusercontent.com/3365507/58601548-da088f00-82bb-11e9-8cff-6789abed7048.gif)

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this problem @phpbits. This issue was fixed and popovers should work correctly in the last version of Gutenberg.
