### ISSUE TITLE
Release 5.8.0 introduced PHP Warnings, at least in 'wp shell'

### ISSUE THREAD

**Issue by n9yty** [WordPress/gutenberg#15902]
After upgrading to v5.8.0 I noticed when working in wp shell that I always get two of these warnings when the shell starts up:

Warning: Invalid argument supplied for foreach() in /home/ourpreschoollife/public_html/wp-includes/rest-api/endpoints/class-wp-rest-controller.php on line 287

Reverting to 5.7.9 removes them.

**Comment by TimothyBJacobs** [comment]
I believe this is because the rest controllers specify a schema callback when registering the route even though they don't define a schema using `get_item_schema()`

**Comment by lkraav** [comment]
Confirmed, this is happening. https://sentry.crdy.co/share/issue/cc7e19c03f5a4344a141d879ed7fb323/ is a traceback. Warning is caused by `/__experimental/widget-areas/(?P<id>.+)` route, and `$schema['properties']` is not a valid `foreach` argument.

**Comment by n9yty** [comment]
What is needed to move this forward?

**Comment by larssn** [comment]
`$schema['properties']` is undefined.

We're seeing it when invoking jobs via the WP CLI, like so:
`wp cron event run --due-now --url=$uri --path=/var/www/html`
