### ISSUE TITLE
Widgets (beta) screen doesn't populate with existing widgets

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15911]
**Describe the bug**
The new Widgets page is confusing. When I'm on the screen, I'm shown my various sidebars and they're populated with something called a 'Legacy Widget'. Within that Block is a dropdown to select a 'Legacy Widget'. 

<img width="1920" alt="screenshot_63" src="https://user-images.githubusercontent.com/2078245/58624689-326b7b00-8314-11e9-9767-28f4f2e31280.png">

Why doesn't this dropdown list all the existing widgets that I can select on the standard Widgets page (e.g. Archives, Calendar, Categories, Text etc...)?

This is the standard Widgets page on my test site. The Main Sidebar contains 6 Text widgets and a Calendar widget.

<img width="1920" alt="screenshot_65" src="https://user-images.githubusercontent.com/2078245/58624812-765e8000-8314-11e9-8e11-e0b286938c58.png">

Why can't I select a Text widget or Calendar widget from the from the 'Legacy Widget' dropdown? If they're being replaced with Blocks, then why haven't they been replaced automatically when I go to this new Widgets page? I hope I'm not expected to remove these Legacy Widgets myself and replace them with Classic Blocks and a Calendar Block, because that would be a horrible experience for a user.

I don't know whether this page just isn't working properly, or what I'm supposed to do.
 
**To reproduce**
1. Go to Widgets (beta) screen
2. Get confused

**Expected behavior**
If my existing Text and Calendar widgets are being replaced by blocks, then I would expect my sidebars to be automatically populated with the relevant blocks. e.g. Replace each Text Widget with a Classic Block and populate it with my content that was in the original Widget.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Firefox Quantum 67.0
 - Version: WP 5.2.1 Gutenberg 5.8.0

**Comment by swissspidy** [comment]
Thanks for your valuable feedback! I'll try to reply to some of your points as someone who has been contributing to Gutenberg regularly, but hasn't been involved in this new widgets screen.

> I don't know whether this page just isn't working properly, or what I'm supposed to do.

Please note that this new widget management screen is still in super early stages. It's to be expected that not everything works just yet.

> Why doesn't this dropdown list all the existing widgets that I can select on the standard Widgets page 
> Why can't I select a Text widget or Calendar widget from the from the 'Legacy Widget' dropdown?

These default widgets have been replaced by blocks, that's why you don't see them.

> If they're being replaced with Blocks, then why haven't they been replaced automatically when I go to this new Widgets page? I hope I'm not expected to remove these Legacy Widgets myself and replace them with Classic Blocks and a Calendar Block, because that would be a horrible experience for a user.
> If my existing Text and Calendar widgets are being replaced by blocks, then I would expect my sidebars to be automatically populated with the relevant blocks. e.g. Replace each Text Widget with a Classic Block and populate it with my content that was in the original Widget.

Worth keeping in mind that converting post content to blocks has been a manual process as well.

The reasons for this are simple:

1. If we'd automatically convert your blocks, you would have no way to go back to the old version.
1. Blocks sometimes have different features and behaviors than their legacy widget predecessors. Automatic conversion would lead to unexpected situations for users.

**Comment by maddisondesigns** [comment]
@swissspidy Thanks for those answers.

While I can understand the reluctance to auto-convert content, what is being shown to me at the moment, just makes it super confusing and worse than auto-converting.

When editing an old (pre 5.0) post in the new editor, it's not converted to individual blocks, but the content is still converted into one Block, the Classic Block. What's happening on the Widgets page isn't even doing that. None of my content has appeared on the page and there's no indication of what I'm supposed to do to get my content on the page. At least in the main Gutenberg editor, after your content is converted to a Classic Block, if you click around enough, you'll find a 'Convert to Blocks' option. I'm not even offered that here. Users are going to look at that dropdown, like I did, and then wonder how they're supposed to convert their Text Widget (as an example), into this new layout.

Even if they finally come to the conclusion that they have to add a block, they're going to look for a Text Block (to replace their Text Widget) and they wont find one. Even then, if they work out, oh, maybe I can use a Classic Block, they still have to go back to the original Widgets page, copy their content, and then go back into the new Widgets page and paste it into the new Block. That is a horrible experience, even for expert users.

Widgets are small, individually contained, bits of content. Say I have a very simple Text Widget with the following content:

<img width="483" alt="screenshot_69" src="https://user-images.githubusercontent.com/2078245/58633333-774edc00-832b-11e9-8bbb-446e25d0ca51.png">

Am I now just supposed to insert a Heading Block and Two Paragraph Blocks, just to replicate that one Widget? If so, that really is a horrible solution and you need to think of a better way to handle this because that is ridiculous. If I have 5 widgets in a Sidebar, I could potentially have to add 10, 15 or maybe even 20 Blocks, just to replicate them. At the very minimum, you'll need at least 2 blocks to replicate one Widget. One for the Header and one (or more) for the content. How is this making WordPress easier to use? The Widget Blocks in Gutenberg need to replicate how widgets currently work and their needs to be a Widget Block for every single Widget that is currently available on the current Widgets screen.

I can totally appreciate that this is still a work in progress, but unless some major re-thinking is done about how existing widgets are handled, this is going to be a nightmare for users to **(A)** Convert their existing widgets and **(B)** Manage their Widgets going forward.

**Comment by noisysocks** [comment]
> `[Feature] Navigation Screen` and `[Block] Navigation` issues and PRs that are important for the WordPress 5.6 release to replace the Menus screen with a block-based screen.

Note that this can be done in one click using the transform tool in the Legacy Widget block's toolbar. Maybe we need to make this functionality more prominent? Pinging @mapk for design feedback.

**Comment by maddisondesigns** [comment]
@noisysocks The only block choice that I get when clicking on "Transform To", is a Group block. If I select that, my content then disappears. This is worse than having having no Transform options at all.

Vid: https://share.getcloudapp.com/YEuooJe0

**Comment by mapk** [comment]
>Note that this can be done in one click using the transform tool in the Legacy Widget block's toolbar. Maybe we need to make this functionality more prominent?

Thanks for the ping! 

Ideally, I'd like to see any widget that has a one-to-one relationship with a block automatically convert to that block. It should be magic. I'm in a block editor now, so let's just convert them to blocks since we have a block created for the core widgets anyways. _but don't lose my settings or content when this happens_

I imagine two scenarios for the Legacy Widget block:

1. The Legacy Widget block is a way for me to pull in a 3rd party widget that I just installed on my site. The dropdown in the placeholder can list my 3rd party widgets. 
2. The Legacy Widget block is also used in the event I have a 3rd party widget _already installed and located_ in a widget area. It provides the means by which that widget can be used in the new Widget Editor.

These are both nearly identical, except one has to do with locating a new widget and getting it into the area while the other is about just displaying existing widgets already in a widget area.

**Comment by mapk** [comment]
In regards to number 1 above, it appears this is currently working. I have a 3rd party plugin called "Recent Posts with Thumbnails" and after adding a Legacy Widget to the area, I can then select that 3rd party widget to have it displayed in that widget area.

![widget](https://user-images.githubusercontent.com/617986/90453073-7cb95300-e0a4-11ea-8ea4-7a7d6e66167c.gif)

**Comment by noisysocks** [comment]
> @noisysocks The only block choice that I get when clicking on "Transform To", is a Group block. If I select that, my content then disappears. This is worse than having having no Transform options at all.
> 
> Vid: https://share.getcloudapp.com/YEuooJe0

Thanks for the video. This is definitely a bug. A Text widget should offer the option to transform into a Paragraph block.

**Comment by draganescu** [comment]
Just to move the discussion forward, there are two problems outlined in this issue:

- [ ] when a website has widgets in sidebars and these widgets are those for which we have blocks, we should either auto-convert or be clear with what we are displaying
- [ ] a legacy widget block should have transform options that convert it to the equivalent block

**Comment by noisysocks** [comment]
> when a website has widgets in sidebars and these widgets are those for which we have blocks, we should either auto-convert or be clear with what we are displaying

We should never auto-convert as there are nearly always differences between how the legacy widget works and how the block equivalent works. Requiring manual conversion gives the user a chance to confirm that nothing breaks on their site.

> a legacy widget block should have transform options that convert it to the equivalent block

This is already the case, it is just not working for the Text widget.

**Comment by noisysocks** [comment]
I'm going to close this in favour of https://github.com/WordPress/gutenberg/issues/25100 which describes the only actionable item here.

**Comment by draganescu** [comment]
@noisysocks the other thing mentioned that if we won't auto-convert we need a clear UI that shows the users their set up widgets.
