### ISSUE TITLE
Dragging a Widget outside the Sidebar breaks the site

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15912]
**Describe the bug**
If I drag 'n drop a widget outside the sidebar, everything breaks.

<img width="1920" alt="screenshot_66" src="https://user-images.githubusercontent.com/2078245/58625968-ea018c80-8316-11e9-820e-37c2557662f8.png">

Video: https://cl.ly/d88329970c92

The same thing happens when I try to drag that Legacy Widget to another sidebar.

**To reproduce**
1. Go to Widgets (beta) screen
2. Drag 'n Drop a widget outside the sidebar
3. See error

**Expected behavior**
You shouldn't be able to drop a widget outside a Sidebar

**Desktop (please complete the following information):**
- OS: macOS 10.14.5
- Browser: Firefox Quantum 67.0
- Version: WP 5.2.1 Gutenberg 5.8.0

**Comment by draganescu** [comment]
As of Gutenberg 7.9.1 I was unable too reproduce this. I will close, but @maddisondesigns let me know if you still think this should be an issue.

**Comment by maddisondesigns** [comment]
@draganescu Please re-open this as it's still an issue. Here's a new vid I just created:
 
Vid: https://share.getcloudapp.com/E0ubqypd

WP 5.4
Gutenberg 7.9.1

**Comment by draganescu** [comment]
Hmm, I'll retest, but for now this is back on :) Thanks for the quick reply!

**Comment by noisysocks** [comment]
I can't seem to reproduce this.

![believe-me](https://user-images.githubusercontent.com/612155/90215410-dddfed00-de3e-11ea-8e3d-ced423d4295b.gif)

**Comment by maddisondesigns** [comment]
Yup, just tried as well, and it seems to work as expected now 👍
