### ISSUE TITLE
Block Toolbar appears above Block Inserter on Widgets (beta) screen

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15914]
**Describe the bug**
If you select a block and then try to insert a Block above it, the toolbar on the selected block appears above the Block Inserter.

<img width="962" alt="screenshot_67" src="https://user-images.githubusercontent.com/2078245/58626592-84160480-8318-11e9-8a28-324a779cdb20.png">

**To reproduce**
1. Select your second Widget/Block
2. Open the Block Inserter on the Widget/Block above it
4. See toolbar appear above Block Inserter

**Expected behavior**
Block Inserter should appear above everything

**Desktop (please complete the following information):**
- OS: macOS 10.14.5
- Browser: Firefox Quantum 67.0
- Version: WP 5.2.1 Gutenberg 5.8.0

**Comment by youknowriad** [comment]
<img width="578" alt="Capture d’écran 2020-03-12 à 9 50 35 AM" src="https://user-images.githubusercontent.com/272444/76503878-f2125f00-6446-11ea-8b11-e88cd8327f9d.png">

this seems fixed now.
