### ISSUE TITLE
Inline elements in Wordpress.com? 

### ISSUE THREAD

**Issue by Gerard8** [WordPress/gutenberg#15910]
Can't find the option to put an inline element/image in a Gutenberg table any longer. Disappeared or moved elsewhere?

**Comment by swissspidy** [comment]
In the block toolbar you can click on the arrow to get the option to insert an inline image in a table:

<img width="603" alt="Screenshot 2019-05-30 at 13 22 07" src="https://user-images.githubusercontent.com/841956/58629887-ffa69000-82dd-11e9-9e4d-e90cbad993ae.png">

If you believe WordPress.com used to have more features than that, I suggest contacting their support.

**Comment by Gerard8** [comment]
Thanks a lot! Moreover, it's now easier to control the size of the picture!
