### ISSUE TITLE
Extended attribute schema

### ISSUE THREAD

**Issue by mr660** [WordPress/gutenberg#15919]
Feature that i think should be  mandatory should be repeatable attribute, can't explain it exactly so i'll show the example code.

Lets say i have a block with 3 cards. Each card have exactly same property. Now what i did is:
```
let attributes = {
  cardLeftTitle: {
    type: 'string'
  },
  cardCenterTitle: {
    type: 'string'
  },
  cardRightTitle: {
    type: 'string'
  },
  cardLeftDescription: {
    type: 'string'
  },
  cardCenterDescription: {
    type: 'string'
  },
  cardRightDescription: {
    type: 'string'
  },
  cardLeftButton: {
    type: 'number'
  },
  cardCenterButton: {
    type: 'number'
  },
  cardRightButton: {
    type: 'number'
  }
}
```

What i would like it to be:
```
let x = {
  card: {
    type: 'repeatable',
    schema: {
      title: {
        type: 'string'
      },
      description: {
        type: 'string'
      },
      button: {
        type: 'text'
      },
      target: {
        type: 'number'
      }
    }
  }
}
```

As You can see this is much cleaner and much more readable. And this is for only for 3 cards. Imagine how my controls looks to operate those attributes.

I guess it should have own component to repeat this how many times we want. So this:
```
<div className="rotating-cards__card">
            <TextControl
              label="Title"
              value={cardLeftTitle}
              onChange={(value) => setAttributes({ cardLeftTitle: value })}
            />
            <TextareaControl
              label="Description"
              value={cardLeftDescription}
              onChange={(value) => setAttributes({ cardLeftDescription: value })}
            />
            <TextControl
              label="Button text"
              value={cardLeftButton}
              onChange={(value) => setAttributes({ cardLeftButton: value })}
            />
          </div>

          <div className="rotating-cards__card">
            <TextControl
              label="Title"
              value={cardCenterTitle}
              onChange={(value) => setAttributes({ cardCenterTitle: value })}
            />
            <TextareaControl
              label="Description"
              value={cardCenterDescription}
              onChange={(value) => setAttributes({ cardCenterDescription: value })}
            />
            <TextControl
              label="Button text"
              value={cardCenterButton}
              onChange={(value) => setAttributes({ cardCenterButton: value })}
            />
          </div>

          <div className="rotating-cards__card">
            <TextControl
              label="Title"
              value={cardRightTitle}
              onChange={(value) => setAttributes({ cardRightTitle: value })}
            />
            <TextareaControl
              label="Description"
              value={cardRightDescription}
              onChange={(value) => setAttributes({ cardRightDescription: value })}
            />
            <TextControl
              label="Button text"
              value={cardRightButton}
              onChange={(value) => setAttributes({ cardRightButton: value })}
            />
          </div>
```
would look like this
```
          <Repeatable className="rotating-cards__card" attribute={card}  min="3" max="3">
            <TextControl
              label="Title"
              value={title}
              onChange={(value) => setRepatableAttributes(card, { title: value })}
            />
            <TextareaControl
              label="Description"
              value={button}
              onChange={(value) => setRepatableAttributes(card, { button: value })}
            />
            <TextControl
              label="Button text"
              value={button}
              onChange={(value) => setRepatableAttributes(card, { button: value })}
            />
            <PostSelector
              posts={target}
              onChange={(value) => setRepatableAttributes(card, { target: value })}
              limit="1"
            />
          </Repeatable>
```

Also i would propose adding attribute child so we can have organised attributes, e.g. looking on code above
```
const x = {
  cardLeft: {
    type: 'object',
    schema: {
      title: {
        type: 'string',
      },
      description: {
        type: 'string'
      },
      button: {
        type: 'number'
      },
      target: {
        type: 'number'
      }
    }
  }
}
```

In my opinion You should give developers **as much freedom of choice as You can**. Wordpress power comes from developer that makes plugins and themes. I think Gutenberg extensibility could be new era for Wordpress.

**Comment by talldan** [comment]
Hi @mr660—There is a `query` type that is already available and can be used to extract arrays of attributes:
https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/#query

In JSX there's not really a need for a `Repeatable` element, you can map over data using JavaScript to produce repeating elements.

An example of this in use for one of the core blocks is visible on the table block. Attributes for each row are fetched using nested `query` declarations:
https://github.com/WordPress/gutenberg/blob/c12859d12d87bb4194bec203531d2e7883c2bb9d/packages/block-library/src/table/block.json#L42-L60

When rendering the table rows, attribute data is mapped to produce repeating elements:
https://github.com/WordPress/gutenberg/blob/c12859d12d87bb4194bec203531d2e7883c2bb9d/packages/block-library/src/table/edit.js#L361-L393

> In my opinion You should give developers as much freedom of choice as You can. Wordpress power comes from developer that makes plugins and themes. I think Gutenberg extensibility could be new era for Wordpress.

Thanks for the feedback, it's great that you're excited about Gutenberg 😄. Just want to mention that this is an open source project, so there isn't really a 'You'. Any individual is free to contribute in a variety of ways, be it testing, design, code, copy, just about any way really!

Hopefully my response has covered your use case. I'll close the issue, but let me know if I've misunderstood in any way, and we can always reopen it.
