### ISSUE TITLE
Image is overlaying the editor toolbar.

### ISSUE THREAD

**Issue by leodluz** [WordPress/gutenberg#15923]
Image is overlaying the editor toolbar.

**To reproduce**
1 - paste this code in your gutenberg editor
2 - see with our own eyes.

**Expected behavior**
Toolbar in z-index 999999

**Screenshots**
![image](https://user-images.githubusercontent.com/22651765/58654809-23260680-82ef-11e9-9f69-f7044b6101b3.png)

**How to solve:**
Put the toolbar to z-index: 99999;

**editor css that I am using:**
<pre style="background-color: black;">
/* Main column width */
.wp-block {
    max-width: 1160px;
}
 
/* Width of "wide" blocks */
.wp-block[data-align="wide"] {
    max-width: 1080px;
}
 
/* Width of "full-wide" blocks */
.wp-block[data-align="full"] {
    max-width: none;
}

.wp-block[data-align="left"] {
    clear: both;
}
.wp-block[data-align="right"] {
    clear: both;
}
</pre>

**POST CODE**
<pre>
&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;right&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignright&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2018/07/GL-Quote-300x151.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;At Wohlsen, community involvement matters. We care about the places where we live and work, and our employees give back in many different ways. Volunteering our time and efforts are a big part of who we are and we would not have it any other way.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;In addition to supporting our local communities, we encourage employees to be active in various civic organizations by volunteering time, serving on boards and committees, or giving financially. Here is a bit of what we do:&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Wohlsen Crusaders&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/03/Tim-Cathy-Wendy-Trudy-Team-Lap-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;One in three people living in the US will be diagnosed with cancer in their lifetime. That number is way too high &#x2013; and that&#x2019;s why we formed The Wohlsen Crusaders. For 20 years, our team has raised funds for the American Cancer Society&#x2019;s Relay For Life.&#x26;nbsp;From bingo events and sandwich sales, to holiday wreaths, and daffodil fundraisers, the Crusaders work relentlessly to raise awareness and dollars for the Relay For Life. Our year-long, company-wide support culminates at Lancaster&#x2019;s Relay For Life, where we walk around the clock to show our support.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:video --&#x3E;
&#x3C;figure class=&#x22;wp-block-video&#x22;&#x3E;&#x3C;video controls src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/03/Wohlsen-Crusaders-Relay-For-Life-Video-1.mp4?_=1&#x22;&#x3E;&#x3C;/video&#x3E;&#x3C;/figure&#x3E;
&#x3C;!-- /wp:video --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2018/07/29178393_10155202283217155_874724339562315776_o-220x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;ABC Keystone Construction Wars&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen Construction participated in ABC Keystone&#x2019;s Construction Wars, an event which brought hundreds of local middle school students to the association&#x2019;s headquarters to learn about construction and construction careers. Students got to build wooden laptop stands, test electrical circuits, bend sheet metal for their own tool boxes, and more.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2018/07/Fence-Install-e1532032982156-250x185.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Wilmington Downtown Garden&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;In 2018, Wohlsen participated in the creation of a community garden located in downtown Wilmington, DE. The project transformed an old, vacant lot into an urban garden shared by members of the local community. In addition, the neighboring Salvation Army partnered with the Kiwanis Club of Wilmington to grow vegetables in the garden for the children and seniors served by the club.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/04/20170818_132509-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Habitat for Humanity&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen teammates from our Wilmington and Greater Philadelphia offices volunteer their time and talents to assist Habitat for Humanity (&#x3C;a href=&#x22;https://www.habitat.org/&#x22;&#x3E;https://www.habitat.org/&#x3C;/a&#x3E;) with the construction of safe, affordable homes for residents in the community.&#x26;nbsp;&#x26;nbsp;From laying floors to hanging doors, everyone involved pulls together to accomplish a great deal!&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/04/Wohlsens-Bowl-A-Thom-Team-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;ABC Bowl-a-Thon to Aaron&#x2019;s Acres&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen teammates participate the&#x26;nbsp;Annual Bowl-a-Thon, hosted by Keystone ABC&#x2019;s Young Professional Committee. Each year, a different charity is selected to receive the proceeds from the event. Last year&#x2019;s beneficiary was Aaron&#x2019;s Acres, a group which provides age appropriate recreational programs for children and young adults with special needs.&#x26;nbsp; For more information on Aaron&#x2019;s Acres and to learn how you can support this worthy cause, visit (&#x3C;a href=&#x22;https://aaronsacres.org/&#x22;&#x3E;https://aaronsacres.org/&#x3C;/a&#x3E;).&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/03/food-bank-of-delaware-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Food Bank of Delaware&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;At least twice a year, Wohlsen volunteers time to the Food Bank of Delaware (&#x3C;a href=&#x22;https://www.fbd.org/&#x22;&#x3E;https://www.fbd.org/&#x3C;/a&#x3E;). We have packed over 1,000 boxes of food over the past few years. Additionally, we organize in-office food drives around the holidays.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2017/11/Vista-School-Walk-for-Education-Sept-2016-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Vista School&#x2019;s Walk for Education&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen teammates took part in The Vista School&#x2019;s (&#x3C;a href=&#x22;https://www.thevistaschool.org/&#x22;&#x3E;www.thevistaschool.org&#x3C;/a&#x3E;) Annual Walk for Education event.&#x26;nbsp; Funds raised from the event help support the Vista School&#x2019;s programs and serve children with ASD.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2017/11/Boy-Scouts-Bashore-4-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Boy Scouts of America&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen teammates volunteered their time to build ten new tent platforms for the Boy Scouts of America&#x2019;s (&#x3C;a href=&#x22;https://www.scouting.org/&#x22;&#x3E;www.scouting.org&#x3C;/a&#x3E;)&#x26;nbsp;Bashore Scout Reservation located in Jonestown, PA&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/04/american-heart-walk-250x188.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;American Heart Walk&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;A group of Wohlsen employees and their families participate in American Heart Walk (&#x3C;a href=&#x22;https://www2.heart.org/site/SPageServer/?pagename=HeartWalk_Landing_Page&#x22;&#x3E;www.heartwalk.org&#x3C;/a&#x3E;) in Wilmington, DE.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:image {&#x22;align&#x22;:&#x22;left&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-image&#x22;&#x3E;&#x3C;figure class=&#x22;alignleft&#x22;&#x3E;&#x3C;img src=&#x22;https://www.wohlsenconstruction.com/wp-content/uploads/2016/03/ACE-Central-PA-250x167.jpg&#x22; alt=&#x22;&#x22;/&#x3E;&#x3C;/figure&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:image --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;ACE Mentor Program&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Wohlsen is active in the Central PA affiliate of the ACE (Architecture, Construction and Engineering) Mentor Program. The program is a partnership of industry professionals working together to attract high school students to ACE professions by providing hands-on learning opportunities and encouraging them to pursue studies and careers in these fields. Wohlsen&#x2019;s Operations Center serves as the host site for meetings of the program.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;&#x3C;strong&#x3E;Pedro&#x2019;s House&#x3C;/strong&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:paragraph --&#x3E;
&#x3C;p&#x3E;Pedro Toalo of Wilmington, DE was injured in a violent crime that left him confined to a wheelchair. The Planning Factory of Wilmington rallied supporters from the local community to provide labor and construction materials to renovate Toalo&#x2019;s home and make it more accessible for him and his family. Wohlsen was a proud supporter of the project.&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;
</pre>

**Comment by jasmussen** [comment]
I'm told by @senadir that this issue has been fixed by  #15537, so closing this one. If this was in error, let me know and we can reopen! 

Thanks so much for letting me know, senadir, and thanks leodluz for opening the ticket!
