### ISSUE TITLE
Explore Adding Motion to Block Moving Actions

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#15922]
This is a container issue to explore and discuss the use of motion to add extra clarity for the actions of moving and reordering (drag and drop) blocks in the editor interface.

### More Broadly → [Using Motion to Express Change](https://matiasventura.com/post/using-motion-to-express-change/)

* Implementation details around the use of `react-spring`.
* * Consistent motion feeling by tweaking tension, mass, resistance parameters.
* * Broader component guidelines integrations (popovers and micro-interactions).
* Considerations around [reduced motion](https://css-tricks.com/introduction-reduced-motion-media-query/) support.
* Considerations around other ways of disabling / enabling such interactions.

**Comment by richtabor** [comment]
This is so awesome! 

One idea would be to add an option to remove motion within the [OptionsModal](https://github.com/WordPress/gutenberg/blob/359858da0675943d8a759a0a7c03e7b3846536f5/packages/edit-post/src/components/options-modal/index.js#L46). 🤔

**Comment by mtias** [comment]
Done in #16065.

@richtabor glad you like it! Let's see how the reduced motion support works and we can always add our own setting if it's not sufficient or robust enough yet.
