### ISSUE TITLE
Custom HTML is not styled

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#15932]
A Custom HTML block is rendered in the editor in an iframe. This means that none of my theme's styles can affect it.

I tried this with WP 5.2.1 and with GB 5.8.0.

**To reproduce**
1. Define a class in your theme's style sheet to change the color.
2. Add a Custom HTML block
3. Enter HTML with the class to change the color.
4. Click on Preview on the Custom HTML block.
5. See that the color is not changed.

**Expected behavior**
The theme's styles should be able to affect every block, so the Custom HTML should be the changed color.

**Screenshots**
This shows my test, using a Custom HTML block and then the same HTML in a Paragraph block.
![Peek 2019-05-30 19-49](https://user-images.githubusercontent.com/7957680/58675029-1c5fb980-8318-11e9-99d3-2deec499fd2c.gif)

**Desktop**
 - OS: Ubuntu Studio 16.04
 - Browser Firefox
 - Version 66

**Comment by swissspidy** [comment]
I believe this is a duplicate of #9129.
