### ISSUE TITLE
ButtonGroup: the pressed button shouldn't look like a primary button

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15938]
When one of the buttons in the ButtonGroup component is in a "pressed" state, it gets an additional `is-primary` CSS class. This makes the button look like a primary button:

<img width="307" alt="Screenshot 2019-05-31 at 14 22 09" src="https://user-images.githubusercontent.com/1682452/58705842-aa877e80-83b0-11e9-90ca-bf53a42db1b8.png">

I'd tend to think this is not correct. For consistency, blue (primary) buttons should be the ones that identify a primary action (often, the only primary action in a page).

Instead, the ButtonGroup needs to communicate the "active" (pressed) state of a button. It should look like "pressed" and probably with a darker grey background.

I'd like suggest to implement a new `is-pressed` or `is-active` CSS class for the buttons, associated with a style to make the pressed button look like the ones in the Classic Editor media views, which looks more correct to me:

<img width="316" alt="Screenshot 2019-05-31 at 14 45 13" src="https://user-images.githubusercontent.com/1682452/58706635-ede2ec80-83b2-11e9-9909-5ea26ea9a33f.png">

**Comment by drw158** [comment]
In certain contexts where the ButtonGroup is a primary action, the primary style of ButtonGroup may be ideal. For example:

![Screen Shot 2019-05-31 at 10 23 27 AM](https://user-images.githubusercontent.com/618551/58716262-45229600-838e-11e9-918e-6cd3450f5a91.png)

I suggest we have a primary (blue) and "default" (gray) option to mirror our normal buttons.

Is a slightly darker background color + border be enough to signify active? Would a dark gray background be necessary for a11y?

![image](https://user-images.githubusercontent.com/618551/58717067-042b8100-8390-11e9-8896-5d3e8df8733d.png)

**Comment by AlwaysQuads** [comment]
+1

**Comment by chrisvanpatten** [comment]
I’m actually not totally sure it makes sense for ButtonGroup to have a primary style, even if it’s a “primary action”. Because ultimately, the button itself, once in the primary style, is _not actionable_ — clicking on it will produce no effect.

**Comment by drw158** [comment]
@chrisvanpatten I see your point, but my idea was not necessarily conveying primary _action_ but primary _selection_. I agree with this though:

> This is the only spot in the UI, as best as I can tell, where a primary button style is intended to communicate that something is selected. It definitely feels out of place.

Also, I'm not sure what you mean about the Help Scout example. I don't see any mention of Help Scout in the thread. I think you may be referring to the mockup I created, which isn't a Help Scout example. Or, I didn't intend for it to be at least :). I just quickly made it to illustrate different options. 

I also wouldn't assume that buttons will always be skeuomorphic — see this [trac ticket on updating button styles.](https://core.trac.wordpress.org/timeline?from=2019-06-20T13%3A24%3A13Z&precision=second)

So, would option B be required to meet a11y standards? It seems Icon Buttons have been given a similar treatment as B, but I just wanted to know what the requirements are.

**Comment by chrisvanpatten** [comment]
@drw158 Sorry I meant Gmail… not sure why my brain said Help Scout 😂

@afercia's example of how pressed styles work in the rest of core seem like an accessible solution that is the most in line with how the rest of core handles it: 

![](https://user-images.githubusercontent.com/1682452/58706635-ede2ec80-83b2-11e9-9909-5ea26ea9a33f.png)


If core updates its button styles then there is probably another option, but until we do that the example above seems most in line with how the rest of core handles this type of component.

**Comment by mapk** [comment]
This has been resolved with the new G2 designs.

![Screen Shot 2020-05-12 at 4 43 12 PM](https://user-images.githubusercontent.com/617986/81756126-b5c3a500-946f-11ea-9e1c-847042fe6e4e.png)
