### ISSUE TITLE
Select multiple blocks and apply the same settings to all

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#15957]
**Is your feature request related to a problem? Please describe.**
If I'm reformatting a page, often times I'll want to select multiple blocks and change the settings on them — for example, selecting a couple paragraphs or images and then changing their alignment.

**Describe the solution you'd like**
I'd like for any matching toolbar or sidebar settings to remain when you select multiple blocks. So, if all the blocks you selected have text alignment, still show text alignment. If they all have wide or full width support, still show those toolbar icons, etc.

**Comment by swissspidy** [comment]
I think #8743 already covers that enhancement request.
