### ISSUE TITLE
Use template blocks and meta values

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#15955]
Hello!

I'm trying to use template blocks when I register a post type. I'm trying to avoid use metabox, and I'd like to save the values from that template blocks in meta value.

How can i make it?

Thanks in advance!

**Comment by swissspidy** [comment]
There‘s plenty of documentation in the handbook: https://developer.wordpress.org/block-editor/

Maybe an example plugin like this helps you too: https://github.com/swissspidy/news-recommendations
