### ISSUE TITLE
Enhancement: Replace edit image icon with swap icon for multiple blocks

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#15954]
On https://github.com/WordPress/gutenberg/issues/15614#issuecomment-492376037, I noticed that we are now replacing the edit image icon with a "swap" icon, to indicate that the icon is more about replacing the image in the block rather than editing the image itself. This is a great move! 

Although, I see this new icon only on the image block at the moment.

| Block name | Image |
|------|------|
| Image | <img width="1039" alt="Screenshot 2019-06-02 at 14 50 01" src="https://user-images.githubusercontent.com/18581859/58759351-0f281200-8546-11e9-9860-0aeadce936b8.png"> | 

It's not seen on any other image blocks like the ones below:

| Block name | Image |
|------|------|
| Cover | <img width="1025" alt="Screenshot 2019-06-02 at 14 50 37" src="https://user-images.githubusercontent.com/18581859/58759349-0e8f7b80-8546-11e9-99fe-a9267e256ab1.png"> | 
| Gallery | <img width="1015" alt="Screenshot 2019-06-02 at 14 50 17" src="https://user-images.githubusercontent.com/18581859/58759350-0f281200-8546-11e9-8735-5ff1ea9b21df.png"> | 
| Media & Text | <img width="1182" alt="Screenshot 2019-06-02 at 14 49 47" src="https://user-images.githubusercontent.com/18581859/58759352-0f281200-8546-11e9-945a-8429d8e9e3de.png"> | 

For consistency reasons, all blocks should have the swap icon on it, instead of "edit" icon.

**Comment by swissspidy** [comment]
Thanks for your report! Please note that we are already tracking this in #14795.

**Comment by arunsathiya** [comment]
Ah, I tried searching for that ticket with multiple keywords but hadn't noticed that one. Thanks, Pascal!
