### ISSUE TITLE
Text alignment settings should be next to the Bold/Italic buttons in Heading block

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#15953]
I think it would be easier for users to find if the text alignment options were next to the Bold/Italic buttons rather than in the sidebar.
![image](https://user-images.githubusercontent.com/25369857/58757643-3e676080-84ff-11e9-8431-ecef5fcaaaab.png)

**Comment by swissspidy** [comment]
This was previously reported in a few issues already, for example in #12781. The agreement was that we should look at _all_ blocks to ensure consistency throughout the editor. There's an issue for that here: #15096.
