### ISSUE TITLE
Different OPTION values for the SELECT tag element in media insertion (Classic vs Block editor)

### ISSUE THREAD

**Issue by JulioPotier** [WordPress/gutenberg#15961]
Hello there

**Describe the bug**
When I'm using the Classic editor, the SELECT tag "link to" has an OPTION for "Attachment Page", the name of this option is "post". 
When I'm using the Block editor, the SELECT tag "link to" has an OPTION for "Attachment Page", the name of this option is "attachment". 

**To reproduce**
1. Add a media when using Classic
2. Verify the OPTION name of the SELECT tag `.link-to`
3. Repeat 1 with Block editor
4. Repeat 2 with SELECT tag `#inspector-select-control-x`

**Expected behavior**
The Block editor should use the same option name as the Classic one, "post" and not "attachment".

**Screenshots**
https://www.dropbox.com/s/mvf1nbx6hqj5sm3/Capture%20d%27%C3%A9cran%202019-06-03%2010.13.25.png?dl=0
https://www.dropbox.com/s/slpi1fphtwvlkwg/Capture%20d%27%C3%A9cran%202019-06-03%2010.13.43.png?dl=0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version 74

Thank you!

**Comment by swissspidy** [comment]
Is anything broken because of this? Or why else would it need to be changed?

**Comment by BoiteAWeb** [comment]
Hey Pascal.
I though about possible broken behavior based on a value selector, CSS or JS ones.
Also for sustainable code, a "post" OPTION value should stay a "post" and not become an "attchment"
I may be wrong.

**Comment by noisysocks** [comment]
It is not a goal of the block editor to have the same HTML as the classic editor. That is, it is not expected that CSS written for the classic editor will work in the block editor.

**Comment by JulioPotier** [comment]
So there is no retrocompatibility here, ok.
