### ISSUE TITLE
Inserter: Search should search all tabs, not just the active

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1596]
Right now search just searches the active tab. Ideally it should search through all tabs. Indeed the row of tabs should probably disappear as soon as you start searching, so when you tab from the search field after a successful search you enter the blocks. 

Perhaps low priority considering the flux the inserter is in with https://github.com/WordPress/gutenberg/issues/1588 and https://github.com/WordPress/gutenberg/issues/888.

**Comment by westonruter** [comment]
YES. I was going to comment on another issue that I think searching should return results from _all_ the tabs, not just the one selected. I've repeatedly been frustrated recently when typing into the search box to quickly access  a block, only to find that I hadn't selected the right tab first where the block is listed. So essentially I think there should be essentially a “search results” tab. This could have good tie-in with re-used external “shared blocks”, as noted in #1516. Searching can list matching block types first, followed by matches for all shared blocks that already exist.

**Comment by nylen** [comment]
Even knowing that this is the actual behavior, I get it wrong every time I try to use the inserter.
