### ISSUE TITLE
Column Reusable blocks preview design is not looks good.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#15978]
**Describe the bug**
Column Reusable blocks preview should be display proper.

**To reproduce**
1. Open Editor'
2. Click on 'Add block option'
3. Add Column block.
4. Add Content in the Column block.
5. Then Add block to the reusable block.
6. See the Preview of Reusable Block, 

**Expected behavior**
The preview should be display proper.

**Please find below Video**

https://www.screencast.com/t/NXFQmh3aM8Kv

**Comment by getdave** [comment]
This PR should help solve this https://github.com/WordPress/gutenberg/pull/16113

**Comment by youknowriad** [comment]
#16113 is merged now. It's not perfect yet but it's better.
