### ISSUE TITLE
Vimeo does not work when there is a space you link

### ISSUE THREAD

**Issue by felipeloureirosantos** [WordPress/gutenberg#15970]
**Describe the bug**
If you put a Vimeo link with space it won't work. It is not really a bug, but a small thing that should be improved. 

**To reproduce**
1. Create a page using Gutenberg
2. Add Vimeo block
3. Put a Vimeo video link and insert a space on the end of your link

**Expected behavior**
I believe that this space should be ignored, and just gets the link on it.

**Screenshots**
https://imgur.com/O3HAdz3.jpg

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0 (14606.1.36.1.9)

**Additional context**
- WordPress 5.2.1
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by swissspidy** [comment]
Works fine for me in the latest version of the Gutenberg plugin. I even added spaces before and after the URL, and the video still got embedded.

Can you test with the Gutenberg plugin as well?

**Comment by felipeloureirosantos** [comment]
I got this bug using 5.2.1 on a testing environment (https://jurassic.ninja). If you add a website using Jurassic Ninja, so you will get the exactly same environment.

I just realized about it when I was testing it for helping someone on a support forum topic. https://wordpress.org/support/topic/impossible-to-embed-vimeo-videos-anymore/

**Comment by swissspidy** [comment]
I was asking because maybe there is this bug in WordPress 5.2.1, but it has since been fixed already. By installing the latest version of the Gutenberg plugin you could verify this. Same by disabling Jetpack to see if it works without Jetpack.

**Comment by felipeloureirosantos** [comment]
Done. I just installed Gutenberg and it works now. :)

**Comment by Soean** [comment]
I tested the Vimeo video with the URL (https://vimeo.com/333519775) with the Gutenberg plugin and can’t reproduce the problem. Everything is working.

I am closing this issue, please reopen if you can reproduce it with the current plugin version.

**Comment by SxtBox** [comment]
i do not understand why you are so stupid? vimeo has simple methods to make get HLS/MP4 FREE/PRO users

simple function, simple regex, everything simple, why do you make it so tragic?
Check my apis https://paidcodes.albdroid.al/Vimeo_Apis
