### ISSUE TITLE
Inconsistent embed discovery/rendering within blockquotes

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#15971]
**Describe the bug**
When a link that can be auto-embedded is entered into a blockquote, a preview of the embed is not rendered in the editor, but the embed renders on the front end.

I discovered this while triaging [Trac-36756](https://core.trac.wordpress.org/ticket/36756) where the opposite behavior was true in the Classic Editor (embeds rendered in the editor, but not the front end).

**To reproduce**
1. Paste an embed link in a paragraph block (https://wordpress.org/news/2019/05/wordpress-5-2-1-maintenance-release/, for example) and see the embed detected and preview rendered.
2. Insert a blockquote block.
3. Paste the same URL into the blockquote and notice the preview is not rendered.
4. Save draft or publish, and view the post. Notice both embeds render.

@swissspidy recommended on the Trac ticket that embeds should only work when on a separate line on their own and not when inside a blockquote or paragraph. Is this still true, @swissspidy in the context of the block editor? Regardless of the answer, the experience on the front and back end should match.

**Comment by desrosj** [comment]
Here are screenshots of the block editor and front end preview using `trunk`.

![Screen Shot 2019-06-03 at 12 32 49 PM](https://user-images.githubusercontent.com/359867/58818317-bca92d00-85fb-11e9-94c3-75793720eca4.png)

![Screen Shot 2019-06-03 at 12 32 57 PM](https://user-images.githubusercontent.com/359867/58818329-c03cb400-85fb-11e9-9547-ad2beae7e749.png)

**Comment by ehti** [comment]
We discussed this in editor triage today and can replicate.

What's in the editor doesn't match with what's shown on the frontend (i.e., link is shown as plaintext link in the editor, but gets rendered on the frontend). So, that is an issue indeed.

Design feedback likely needed here, for how it should behave.

**Comment by paaljoachim** [comment]
Somewhat associated:
https://core.trac.wordpress.org/ticket/49185

**Comment by MichaelArestad** [comment]
I suggest that if someone drops a link like that in a Quote block (or any text block) by itself, it should convert to show the embed when deselected to reflect what is rendered on the front end. This could be tricky because a link that as part of a quote should still render as a quote.
