### ISSUE TITLE
New User Experience (NUX) tips hide content relevant to New Users

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15986]
Inspired by the testing session videos published by the design team on https://make.wordpress.org/test/2019/06/04/gutenberg-usability-testing-for-may-2019/

The "NUX" tips are meant to guide new users through the first steps to create content. However, they sometimes hide the UI parts they point to, thus defeating their primary purpose.

While this may be not so apparent to designers and developers (because we already know the user interface), it's made very clear in a couple of the videos above.

**Video 1**

At the very beginning, the user reads the content of the first tip, which literally says:

`Click the “+” (“Add block”) button to add a new block.`

So far so good. The user diligently does what they've been told to do: click the "Add block" button. The result of this action is highlighted in the screenshot below:

<img width="808" alt="first tester clicks add block after he read the tip" src="https://user-images.githubusercontent.com/1682452/58907125-c15e0600-870d-11e9-965a-18e480d0d61d.png">

The inserter opens but it's _behind_ the tip, partially hidden. Not a great user experience, as the hidden UI is exactly the one the user is supposed to use.

**Video 3**

The user tries to add a post title. The first "tip" is open so what the user actually sees is highlighted in the screenshot below:

<img width="715" alt="second tester fails to add the title because it's hidden" src="https://user-images.githubusercontent.com/1682452/58907241-071ace80-870e-11e9-9de6-26a64b26b3bd.png">

The title field is completely hidden by the tip.

Below the tip, the only visible thing is:

`Start writing or type / to choose a block`

At some point the user inadvertently clicks on it and the "sibling inserter" (or whatever it's called now) "+" plus button appears.

Since that's the only visible control that seems vaguely related to "add" something in the post, the user clicks on it in the attempt to find something to add a post title.

The user finds the Heading block and uses that to add what they think it's good as post title.

At this point, the user still doesn't have a clue there's a post title field still hidden behind the tip.

Only later the user finally closes the tip and discovers the post title. Then they realize the previously added heading is inappropriate and fill in the post title.

Aside: none of the two users clicks to see the following tips. At some point they just close the first one.

Overall, seems pretty clear that at least the first tip inappropriately hides important parts of the UI, thus contributing to make users confused rather than help them.

Also, the fact none of these two users clicks to see the following tips should probably be further tested to verify the actual usefulness of the tips.

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
