### ISSUE TITLE
Classic Editor plugin link and link target

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#15995]
**Describe the bug**
Gutenberg has following build in warning:

> The block editor requires JavaScript. Please enable JavaScript in your browser settings, or try the Classic Editor plugin.
![Bildschirmfoto 2019-06-05 um 12 02 47](https://user-images.githubusercontent.com/6911678/58948213-e4c69680-8789-11e9-9468-d95611225f86.png)

The "Classic Editor plugin" texts links to the classic editor in the Plugin repository. When clicking on this link, the user gets redirected to the plugin respository and leaves the WordPress admin without any warning.

**To reproduce**
1. Disable Javascipt
2. Create a post
3. See the message
4. Click on "Classic Editor plugin"

**Expected behavior**
I would expect not to leave the admin area.

There are two alternative behaviors I could think of:
**1.** The link opens in a new window/tab.
Therefore we need to add `target="_blank"` to the link.

**2.** Instead of linking to the respository, we could link to the plugin-install.php with the classic editor pre-selected. (if this is possible)

**Comment by Soean** [comment]
Thanks for creating this issue. 
The responsible code is just in WordPress Core, so not maintained via GitHub. Can you open this ticket in [Core trac](https://core.trac.wordpress.org/)? 
I know the current state with the two systems (Trac and GitHub) can be somewhat confusing. This will hopefully change in the future.

Code: https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/edit-form-blocks.php#L417

**Comment by derweili** [comment]
I created a ticket on trac:
https://core.trac.wordpress.org/ticket/47487#ticket
