### ISSUE TITLE
Bottom half of the create button in the table block is not clickable

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#15992]
**Describe the bug**
This issue is a continuation of [Trac-45565](https://core.trac.wordpress.org/ticket/45565).

When inserting a table block, the bottom portion of the Create button.

**To reproduce**
1. Insert table block.
2. Hover over the very bottom portion of the Create button.
3. Click and notice the table is not created.
4. Slowly move the cursor up and click, noticing that about 1/4 of the way up the button functions properly.

**Screenshots**
![create-table-button](https://user-images.githubusercontent.com/359867/58917607-25c09b80-86f5-11e9-81c4-c79e504e356f.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Firefox

**Comment by epiqueras** [comment]
This was fixed on the same day this issue was created, when #15903 was merged, and released with version 5.9.
