### ISSUE TITLE
select('core').getMedia returns undefined

### ISSUE THREAD

**Issue by mr660** [WordPress/gutenberg#16004]
**Describe the bug**
`wp.data.select('core').getMedia()` returns `undefined`

**Expected behavior**
`getMedia()` should return media object

Note: This is not help request. This is bug and should be fixed or There should be provided workaround to handle `getMedia` properly.

**Comment by Soean** [comment]
@mr660 Thanks for opening this ticket, but we already have #14623. So this seems to be a duplicate.

**Comment by swissspidy** [comment]
Closing as a duplicate, especially since you already commented on that issue.
