### ISSUE TITLE
Format of Publication for Article

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/gutenberg#16012]
**Is your feature request related to a problem? Please describe.**
Put back the publication feature of the article, have the choice of format as in previous versions of WordPress with "Default", "By the way" like this:
![format-articles-WordPress](https://user-images.githubusercontent.com/39189263/58982929-e1f19300-87d5-11e9-9876-b4dbd0333666.jpg)

**Comment by Soean** [comment]
If your theme supports this feature you should still be able to set the post format. The interface now looks a bit different:

![Bildschirmfoto 2019-06-06 um 10 49 27](https://user-images.githubusercontent.com/695201/59019770-ee630380-8848-11e9-8371-d669487c4544.png)

**Comment by ValentinGratz** [comment]
Thank you
