### ISSUE TITLE
[loop] shortcode from Custom Content Shortcode is messed up

### ISSUE THREAD

**Issue by philipt18** [WordPress/gutenberg#16015]
**Describe the bug**
I use the Custom Content Shortcode (CCS) plugin quite a bit, and it not surprisingly uses a number of shortcodes in square brackets. The new editor is messing up the code for at least one of them and makes it impossible to get it to save properly. For example, when the [loop] shortcode is inside a table (to repeat a row programmatically) it gets taken out of the table.

**To reproduce**
Here's an example of code that gets messed up. This is code on a page to display a list of posts with the title and thumbnail of the featured image:

```
<table style="width:100%; text-align: left;">
[loop type="post" count="100"]
<tr>
  <td style="width: 150px; height: 150px;">[field thumbnail]</td>
  <td style="font-size: 150%; padding-left: 10px;">[field link]</td>
</tr>
<tr>
  <td colspan="2"><hr></td>
</tr>
[/loop]
</table>
```

If I simply open that page to edit it (if created in a previous version of WP), or add that code in a code block in Gutenberg and then preview or post, it becomes:

```
[loop type="post" count="100"]

[/loop]
<table style="width:100%; text-align: left;">
<tbody>
<tr>
<td style="width: 150px; height: 150px;">[field thumbnail]</td>
<td style="font-size: 150%; padding-left: 10px;">[field link]</td>
</tr>
<tr>
<td colspan="2&quot;">

<hr>

</td>
</tr>
</tbody>
</table>
```

There doesn't seem to be a way to get it to save properly. I'm also not sure where that `&quot;` came from. That seems to be a different bug, but I haven't tested to figure out what is happening (since I can't save the code without it being changed).

**Expected behavior**
I expect a code block to save the code without changing it. This might be related to WP trying to 'clean up' the table code (such as adding <tbody> tags and the like), which I guess I would shut off if I knew how to.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Safari
 - Version: 12.1.1

**Additional context**
- I'm running WP 5.2.1

**Comment by philipt18** [comment]
Thanks @swissspidy for adding the appropriate tags.

**Comment by kathrynwp** [comment]
Hi @philipt18 is this still an issue in the current version of WordPress (6.0.1) , with or without the standalone Gutenberg plugin active (13.8.0)?

If it is, could you please clarify which block you're referring to? For example is it a Classic block in Code view, a Custom HTML block, or something else? Thanks!

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details as requested above, and I’ll be glad to reopen it.
