### ISSUE TITLE
need I install plugins on wordpress v 5.2.1

### ISSUE THREAD

**Issue by olygoelements** [WordPress/gutenberg#16010]
I have disabled all plugins lately and I find that gutenberg integrates guntenberg into the core wordpress. my question is simple: should I still activate the plug-ins?

**Comment by Soean** [comment]
Hey @olygoelements 
yes, the Gutenberg block editor in already integrated in WordPress 5.2.1. The Plugin is now a beta testing plugin for new editor features in WordPress.

So you don't need this plugin anymore, unless you want to test new features before they come into WordPress.

**Comment by olygoelements** [comment]
merci @Soean =)
