### ISSUE TITLE
blockquote right align ouput

### ISSUE THREAD

**Issue by timelsass** [WordPress/gutenberg#16027]
In looking at https://github.com/WordPress/gutenberg/issues/11609 and https://github.com/WordPress/gutenberg/issues/10970 neither seemed to address an issue I've been frequently running across for frontend output vs editor output.

I agree that the styling using something like `[style*="text-align: right"]` is a little hacky, but even in using it - the output on the frontend won't match that selector, and it has to be specified as `[style*="text-align:right"]` (no space).  The editor view includes a space.

I think it would be a nice addition to have the alignments handle via a class overall, but in the very least having the output for the inline style consistent would be helpful.  Sure a heavier selector could be used like `[style*="right"][style*="text-align"]` but that is still error prone leaving something like `[style*="text-align: right"],[style*="text-align:right"]` as being the only somewhat safe solution to cover both scenarios.

**Comment by gziolo** [comment]
I'm proposing a fix which could get applied to all blocks which use text alignment in #16035.

**Comment by timelsass** [comment]
@gziolo that resolves this issue (and some other conflicts I had but did't report since I assumed that a solution like that would be the right approach) - I'm going to close this issue, thanks for taking the time and working on this solution!
