### ISSUE TITLE
Meta attribute doesn't get updated with new value

### ISSUE THREAD

**Issue by bracketsberlin** [WordPress/gutenberg#16023]
**Description**
I created a Gutenberg Block with meta/custom fields. The first time I enter a value, it gets saved to the database. However, when I'd like to update this particular value and overwrite it with something new, the old/initial value reappears.

**Reproduction**
1. Create block in block-place.js
```
( function( blocks, editor, i18n, element, components, _ ) {

    var el = React.createElement;
    var components = wp.components;
    var editor = wp.editor;
    var TextControl = wp.components.TextControl;

    var blockIcon = 'location-alt';

    /* Init Block */
    blocks.registerBlockType('dxt/place', {
        title: 'Place',
        icon: blockIcon,
        category: 'common',
        attributes: {
            description: { 
                        type: 'string', 
                        source: 'meta', 
                        meta: 'description' 
            },
        },

        /* define editor-side */
        edit: function( props ) {
            var attributes = props.attributes;
            var className = props.className;
            var setAttributes = props.setAttributes;

            return [
                el(
                    "div",
                    null,
                    el( TextControl, {
                        label: 'Description',
                        value: props.attributes.description,
                        onChange: function( description ) {
                            setAttributes({ description });
                        }
                    } ),
                ) // close div
            ]; // close return
        }, // close edit

        // only store meta data, nothing to save here
        save: function() {
            return null;
        }
    })
} )(
    window.wp.blocks,
    window.wp.editor,
    window.wp.element,
    window.wp.components,
    window._,
);
```

2. Register block in plugin.php
```
function loadBlocks() {
    // place block
    wp_register_script(
        'place-block',
        plugins_url( 'blocks/block-place/block-place.js', __FILE__ ), // choose your folders
        array( 'wp-blocks', 'wp-element', 'wp-data', 'wp-editor','wp-components', 'wp-i18n' )
    );

    register_block_type( 'dxt/place', array(
        'editor_script' => 'place-block',
    ) );

    // enable in rest api
    register_meta( 'post', 'description', array( 'show_in_rest' => true, 'single' => true ) );
}

add_action( 'init', 'loadBlocks' );
```
3. Add block to article/post
4. Save initial value, eg. "cool description"
5. Overwrite initial value and save post/page
6. See: value doesn't get updated but the initial value is set again :-(

**Expected behavior**
The old (initial) meta value should be overwritten with the new value.

**Comment by swissspidy** [comment]
Birefly looking at your code I think the problem is that you're not passing an `auth_callback` for `register_meta`.  Try something like `'auth_callback' => '__return_true'`

**Comment by bracketsberlin** [comment]
Thanks for your answer. I tried this:

```
    register_meta( 'post', 'description', array(
        'show_in_rest' => true,
        'single' => true,
        'auth_callback' => '__return_true'
    ) );
```

And in the block.js
```
el( TextControl, {
                    label: 'Description',
                    value: props.attributes.description,
                    onChange: function( description ) {
                        setAttributes({ description });
                    }
                } ),
...

save: function() {
            return null;
        }
```

Unfortunately, nothing has changed. I still can only set an initial value but am not able to update this value.

**Comment by CarolynMcNeillie** [comment]
@bracketsberlin Have you solved your issue? I was encountering the same thing and I discovered that it seems to resolve if I turn off the Custom Fields advanced panel. When this is visible I think Wordpress is saving the new content from the meta block, but then simultaneously saving over it with the old value in the custom fields panel. Would be interested to find out if you're getting the same, or if you've found another way around it.

<img width="946" alt="Screen Shot 2019-07-04 at 11 21 32 AM" src="https://user-images.githubusercontent.com/35696879/60677990-09796100-9e51-11e9-88f0-537468f6cf1d.png">

<img width="378" alt="Screen Shot 2019-07-04 at 11 20 59 AM" src="https://user-images.githubusercontent.com/35696879/60677994-0ed6ab80-9e51-11e9-8bfa-5f4ba4a45c26.png">

**Comment by bracketsberlin** [comment]
@CarolynMcNeillie 
Thank you very much for your suggestion. Until now, I had no solution to this problem. But your hint was the key to success ;-)

I thought it might be unwanted/annoying that the meta box needs to be removed manually. This can be done with the following code:
`function remove_custom_fields_box() {
        remove_meta_box( 'postcustom' , 'page' , 'normal' ); // remove meta box from pages
        remove_meta_box( 'postcustom' , 'post' , 'normal' ); // remove meta box from ppsts
    }
    add_action( 'admin_menu', 'remove_custom_fields_box' );`

So, our solution could be a good workaround here?

I am glad someone else encountered the problem.

**Comment by nickcernis** [comment]
For others finding this, another solution here is to make your meta private so that it won't appear in the Custom Fields meta box, by prepending its name with an underscore:

```php
$args = [
	'auth_callback' => '__return_true',
	'type'          => 'string',
	'single'        => true,
	'show_in_rest'  => true,
];
register_meta( 'post', '_description', $args ); // _description instead of description.
```

That way it won't appear in the Custom Fields box and won't overwrite your component's state on save. This means you can preserve the Custom Fields meta box instead of forcing its removal, since it may be in use by some users.

It looks like this issue can now be closed.
