### ISSUE TITLE
Feature request: create a block list view for easy block discovery

### ISSUE THREAD

**Issue by tbradsha** [WordPress/gutenberg#16022]
**Is your feature request related to a problem? Please describe.**
Currently the modal to select a block shows only 9-12 blocks at a time, and for a word-centric person like me it's hard to scan through and discover the block I want unless I know the specific keyword to search.

**Describe the solution you'd like**
Have a toggle to allow a full list of available blocks, one row per block, perhaps alphabetical. Icons are optional but should be small and to the side of the block name.

**Comment by designsimply** [comment]
This option is available in the form of a menu that drops down when you place the cursor in a block and then adding a `/` character. There is a prompt in empty blocks that aren't already assigned a type when they are not active to try to help make it discoverable.

![Screen Shot 2019-06-06 at 12 52 08 PM](https://user-images.githubusercontent.com/1119271/59058700-700f5d00-885a-11e9-80d8-808868292bbe.png)
<sup>Tested with WordPress 5.2.1 and no active plugins using Chrome 74.0.3729.169 on macOS 10.14.5.</sup>

![Screen Shot 2019-06-06 at 12 52 20 PM](https://user-images.githubusercontent.com/1119271/59058751-861d1d80-885a-11e9-9229-115ae188ee5c.png)
<sup>Tested with WordPress 5.2.1 and no active plugins using Chrome 74.0.3729.169 on macOS 10.14.5.</sup>

**Comment by tbradsha** [comment]
Yes, the slash insertion works fine if you know what keyword you want, but it only gives 10 items.

Currently to browse all existing blocks I have to cilck the +, expand each section, and skim through dozens (or hundreds) of blocks. This is hard to do when there are three columns of blocks. To me, this is mockup is much more usable:

![image](https://user-images.githubusercontent.com/32492176/59068795-039c5a00-886a-11e9-8290-8365ace1baf9.png)

I don't mind icons as they are in the slash inserter menu, but there's so much white space in the current selector that it's painfully distracting and hard to scroll. Try expanding each section and then quickly scrolling through them to see what I mean.

Bonus points for the following settings:
* show list alphabetically
* show full list without being segmented into categories
* remember section expansions
* allow a larger (expandable?) modal

**Comment by kjellr** [comment]
👋 The design team discussed this during a [triage session in Slack today](https://wordpress.slack.com/archives/C02S78ZAL/p1566318398206200) (Note: You may need a [Slack account](https://make.wordpress.org/chat/) to log in.)

A few notes from the chat: 

- The block manager and the `/` inserter both use a list-view, so there's some precedence there. 
- The grid puts a lot of emphasis on visual recognition and the icon. This might have been ideal back when there was only a handful of blocks, but is definitely something to reconsider today. 
- This feels like something that could be explored in a plugin before bringing it in core. It could be especially beneficial for agencies or setups where folks have lots and lost of blocks. In general, reconfiguring the content in this panel seems like a good exercise, but we wonder how many people would use the options.

**Comment by designsimply** [comment]
Thanks @kjellr! I'll remove the `Needs Design Feedback` label for now since the design team discussed the issue and responded with some notes.

Next, would you say that moving forward with this feature request should be on hold until we see a lot more feedback here in this thread?

**Comment by kjellr** [comment]
> Next, would you say that moving forward with this feature request should be on hold until we see a lot more feedback here in this thread?

Yeah, I think that's fair. Thanks, @designsimply!

**Comment by pattonwebz** [comment]
I'm placing my vote here for us exploring this more. I would use this feature myself to add/reorganise the lists (even before adding more blocks) but it would be especially useful for people with large block libraries.

**Comment by youknowriad** [comment]
I think the new inserter design solves the original issue here since all categories are expanded.
