### ISSUE TITLE
0.3.0: toggling Visual -> Text mode converts content to HTML entities

### ISSUE THREAD

**Issue by lkraav** [WordPress/gutenberg#1603]
Classic Text element:

Visual `[column class="pure-u-xl-2-3"]` becomes
Text `[column class=&quot;pure-u-xl-2-3&quot;]`

Text mode should probably not translate things into entities?

https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=text%20html%20entity%20 has no matching results, so filing this issue.

**Comment by lkraav** [comment]
This may have been resolved with Custom HTML block for now, but since #1054 is still very much in flight, it probably doesn't make much sense to track this separately. Close if appropriate.

**Comment by westonruter** [comment]
I think this behavior just reflects the way that `ReactDOMServer.renderToStaticMarkup()` works.

**Comment by jasmussen** [comment]
Closing for now, let's reopen if it resurfaces.
