### ISSUE TITLE
Need to reduce the header height on hovering over the Heading block

### ISSUE THREAD

**Issue by rohanraha156** [WordPress/gutenberg#16039]
**Describe the bug**
When we add a "Heading" block on the editor and click outside the "Heading" block, then the height of the Heading block increases (on hovering).

**To reproduce**
1) Create a new page 
2) Add the "Heading" block.
3) Click outside the "Heading" block and now hover over the "Heading" block.
4) Observe the height of the "Heading" block.

**Expected behavior**
The "Heading" block height should not increase on hover. Similar to the "List" Block. 

**Actual result**
The height of the "Heading" block increase on hovering.

**Screenshots**
Issue video clip: https://www.screencast.com/t/pkBqZoSGhrlJ
ref video clip: https://www.screencast.com/t/hsHjoFxf

Thanks

**Comment by swissspidy** [comment]
Is there any chance you could upload the video somewhere/somehow that doesn't require Adobe Flash player? Nowadays it's not something many people have installed.

**Comment by rohanraha156** [comment]
Hello @swissspidy,

Sorry for the inconvenience caused.

I am uploading the same videos in MP4 format below:

Issue Clip:
![issue](https://user-images.githubusercontent.com/51081067/59109952-a7b1fe00-895b-11e9-9c5f-e7abbc8aaa38.gif)


Reference Clip:
![ref1](https://user-images.githubusercontent.com/51081067/59109901-8e10b680-895b-11e9-9c1c-4d7a278e43d9.gif)

Thanks

**Comment by akasunil** [comment]
Please provide requirements for testing.
WordPress version
Gutenberg version
Browser you are using

and Make sure all plugins except Gutenberg deactivated.

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this one out, but if you are still experiencing the original issue with the latest version of WordPress (with or without the Gutenberg plugin active), feel free to add a comment with additional details as requested earlier, and I’ll be glad to reopen it.
