### ISSUE TITLE
Lock post saving when media is being uploaded

### ISSUE THREAD

**Issue by sndrgb** [WordPress/gutenberg#16030]
Hi everybody, I need an help building a gutenberg block. I'm using MediaPlaceholder component as starting for add images (it's a carousel), but I have a lot of problems when I use the "load" button instead of "view library":
```
<MediaPlaceholder
                        icon="format-gallery"
                        className={ props.className }
                        labels={ {
                            title: __('Carousel'),
                            name: __('images'),
                        } }
                        onSelect={ onSelectImages }
                        accept="image/*"
                        type="image"
                        multiple
                    />
```
```
const onSelectImages = function(selectedImages) {
            const array = [ ...images, ...selectedImages ]
            const updatedImages = array.map((img, index) => {
                if (img.media_details) {
                    Object.assign(img, {
                        width: img.width,
                        height: img.height,
                        id: index,
                        imgid: img.id,
                    })
                }

                return Object.assign(img, { id: index })
            });

            setAttributes({ images: updatedImages });
        }
```
the big problem is that I cannot render on the save function images, because I need size of it and If the editor clicks "update article" before images loads async I cannot get img.media_details.sizes because it returns only an url with a blob like: `{url: "blob:" }`. what can I do?

**Comment by J0ker98** [comment]
I'm having the same problem

**Comment by paaljoachim** [comment]
Hi @sndrgb 

Please recheck the issue. 
Thanks!

**Comment by sndrgb** [comment]
I'll check it out soon, thanks a lot!

**Comment by adamsilverstein** [comment]
This should be fixed by https://github.com/WordPress/gutenberg/pull/41120

**Comment by paaljoachim** [comment]
Thanks for letting us know in this thread Adam @adamsilverstein 
I will go ahead and close this issue. It can always be reopened if that is needed.

**Comment by adamsilverstein** [comment]
Note: this is replaced by https://github.com/WordPress/gutenberg/issues/39223
