### ISSUE TITLE
Audio and Video blocks: the toolbar "Edit" button disappears or re-appears in a different position

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#16048]
Noticed in the Audio and Video blocks.

When clicking on the "Edit" button in the block toolbar, the button disappears. Depending on the interaction mode (mouse, keyboard) I've noticed different behaviors that I wasn't able to reproduce consistently. Also, not sure if there's a difference between Gutenberg in core (WordPress 5.3-alpha) or the plugin (currently 5.8.0).

Anyways, then the button disappears:
- there's a focus loss: this shouldn't happen as it's a terrible experience for keyboard users and assistive technology users
- there's no way to switch back from the block "placeholder" to the view with the embedded media other than:
  - click on "Insert from URL"
  - the embedded media URL is still there
  - click "Apply"

At this point, the "Edit" button re-appears, sometimes in the same location and sometimes... at the beginning of the toolbar. Couldn't reproduce consistently.

To clarify, I made two animated GIFs. To reproduce, sometimes the disappearing doesn't happen the first time "Edit" is clicked, so try multiple times.

Gutenberg version included in wp trunk 5.3:

![audio edit disappearing](https://user-images.githubusercontent.com/1682452/59124506-1c873700-8960-11e9-9a85-bdac786e04fa.gif)

Gutenberg plugin 5.8.0:

![audio edit disappearing plugin](https://user-images.githubusercontent.com/1682452/59124508-21e48180-8960-11e9-867f-263bc5a991bd.gif)

**Comment by afercia** [comment]
Related:
https://github.com/WordPress/gutenberg/pull/15518#pullrequestreview-242319410
https://github.com/WordPress/gutenberg/pull/15516#issuecomment-496720735

**Comment by afercia** [comment]
@draganescu hi! Do I recall correctly you fixed this?

**Comment by draganescu** [comment]
Hi @afercia it is work in progress. I've been away for the past 2 weeks. I am working on implementing a component that should replace / refactor this whole edit flow thing on all the affected components here: 

#16200

**Comment by afercia** [comment]
Thanks @draganescu !

**Comment by swissspidy** [comment]
This reminds me of #15641.

**Comment by Soean** [comment]
We now use the `MediaReplaceFlow` component in all media related blocks.
