### ISSUE TITLE
Block Library: Table: Consider "Fixed width table cells" as default

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#16045]
The table block supports an option for "Fixed width table cells", which changes the appearance of the table so that each column occupies an equal amount of width.

More information about `table-layout: fixed`: https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout

Arguably, this would be the more expected default use-case, and as such we should consider to make this the default behavior.

**Implementation Notes:**

Since this is a change in the default behavior, we should be careful to consider how we want backwards-compatibility to apply. If users have saved content with the current default setting and have expectations around the non-fixed behavior, these expectations should not be broken. Conversely, part of the intent of the defaults implementation of blocks (core blocks specifically) is to allow for revisions to these defaults to more sensible ones in future revisions. 

_Needs Feedback:_ Are we okay in changing the default for existing, saved content?

If existing defaults must be preserved, we should consider how we'd plan to version this, whether that be by introducing a new separate attribute, or some other way to identify the older content for the new default to take effect.

**Comment by mtias** [comment]
This makes sense to me, I find the current behaviour odd.
