### ISSUE TITLE
Add timeout for notices and messages

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1604]
I see 3 **"Post updated! View post"** messages, and they do not go away. Each time you click update one new is there all the time.
It is latest 0.3.0, updated today.

One timeout function to make those messages gone would be nice. It can be very long time, no matter so much. Just they dont pile up endlessly by clicking update each time.

**Comment by youknowriad** [comment]
One thing to consider when adding timeouts to notices is whether we should stop the timeout if we hover the notice. Also, should we stop the timeout for all the notices or just the hovered one.

**Comment by StaggerLeee** [comment]
Can you let permanently visible just last message about Post update ?
One message can be there and we can remove it manually, if you find yourself right now in much coding and dont have time for everything.

I mean last update notice null completely notice before it. So what is the point with more than one message.

**Comment by youknowriad** [comment]
> I mean last update notice null completely notice before it. So what is the point with more than one message.

Good point 👍 we need a way to override previous notices (maybe just reuse the same id)

**Comment by hedgefield** [comment]
Bumping this, because this is what I got today in 0.7.1:

![screenshot_1](https://user-images.githubusercontent.com/6073772/29023885-e2f34ac4-7b6f-11e7-9e3a-cc816fd502da.png)

A timeout (possibly combined with a limit - these notices continued on offscreen) would be nice 👍

**Comment by mtias** [comment]
This has been done in https://github.com/WordPress/gutenberg/pull/2282
