### ISSUE TITLE
Handbook: what is the purpose of Block Grammar 

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#16044]
the [Block Grammar ](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/grammar.md) is really contextless, what is the purpose of it, how could it be useful to a developer and how can someone help in it to document it more?

also, this was addressed in #10734 but was closed without correcting the documentation problem

**Comment by swissspidy** [comment]
I don't know why this is in the contributor docs section and not in the developer docs or something.

**Comment by senadir** [comment]
you still access it from the developer docs page (that's how I found it)
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/develop.md

the best I could decipher from it that those are the specs for a block anatomy

**Comment by swissspidy** [comment]
That's the _contributor_ docs for _developers_ though. I was more thinking about https://developer.wordpress.org/block-editor/developers/ which is the how-to guide for developers to work with the developer.

And yes, a grammar basically specifies how a block is constructed / what makes a block. Just like you have a grammar in the English language that describes how sentences are built, you have grammars that declare how a valid PHP file is written — or in this case a block. This way a program can easily parse the content using the grammar at hand.

**Comment by senadir** [comment]
yes I have fairly good understanding of how grammar works in programming languages.

so if I understand what you said correctly, you are asking why is this in core developer guide and not the public extending guide, as far as I see, there is no mention or use of such grammar when building blocks, so that rules out everyone who uses gutenberg to create blocks. the grammar is useful if someone wants to:
- create an external parser (out of the scope of the contributor docs and mostly fits the developer docs in an advanced section)
- extend or contribute to the internal parser in Gutenberg (the contributor guide)
