### ISSUE TITLE
Props incorrectly documented for FocalPointPicker

### ISSUE THREAD

**Issue by dsifford** [WordPress/gutenberg#16056]
**Describe the bug**
The docs for `components/focal-point-picker` state that `dimensions` is both a property, and required.

It appears that that prop was replaced with an internal function to get the dimensions from the DOM itself.

This should probably be removed to avoid confusion.

**The relevant portion of the outdated docs:**

https://github.com/WordPress/gutenberg/blob/a57202e635ff0cd190a09128d27951620db9a870/packages/components/src/focal-point-picker/README.md#L52-L56

**The relevant portion of the code:**

https://github.com/WordPress/gutenberg/blob/a57202e635ff0cd190a09128d27951620db9a870/packages/components/src/focal-point-picker/index.js#L57-L63

**Comment by UdokaVrede** [comment]
can I get further detail on this

**Comment by nosolosw** [comment]
Sure! The issue here is that the docs of the component don't reflect what the code really does at the moment. Specifically, the `dimensions`  property is no longer used. It'd be good to review whether the docs need other changes and prepare a Pull Request that updates them. Is this helpful?

**Comment by UdokaVrede** [comment]
If I am getting right, I'm to show what #dimensions does in the readme.md does in the code.

**Comment by seanvarnham** [comment]
Hi team, has there been any movement on this issue?

**Comment by skorasaurus** [comment]
Thanks for reporting; this was fixed in https://github.com/WordPress/gutenberg/pull/39168/commits/4f21fdbb23f15f935f4216af9aeaf555c4e21b55 and https://github.com/WordPress/gutenberg/commit/c5ae463d0fae24cf51c54f98922bb0de382ce6e6
