### ISSUE TITLE
Playlists content cut-off in the Classic Block

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#16054]
In the Classic Editor, a media playlist, for example:

`[playlist ids="5748,3175,821"]`

displays a preview with the media items listed below the player:

<img width="977" alt="Screenshot 2019-06-08 at 14 23 37" src="https://user-images.githubusercontent.com/1682452/59147280-d2eb2a80-89f9-11e9-81e0-3bd53350a7b1.png">

Instead, in the Gutenberg Classic Block the content of the playlist is not fully visible and shows only the first item in the playlist:

<img width="734" alt="Screenshot 2019-06-08 at 14 23 58" src="https://user-images.githubusercontent.com/1682452/59147296-fe6e1500-89f9-11e9-8300-d035fc83109a.png">

Seems to me it's related to a missing inline style which is supposed to be set via JavaScript. In the classic editor, the playlist iframe has an inline style that contains a height value:

```
<iframe ... class="wpview-sandbox" style="width: 100%; display: block; height: 237px;">
```

While in the Gutenberg Classic block the height is missing:
```
<iframe ... class="wpview-sandbox" style="width: 100%; display: block;"></iframe>
```

**Comment by afercia** [comment]
Note: the same applies to _video_ playlists.

**Comment by youknowriad** [comment]
Yeah, this seems like a duplicate to #12454 and #10806

Going to close this one for now.
