### ISSUE TITLE
Button Text Color is overridden on hover

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#16052]
**Describe the bug**
` .wp-block-button__link:hover` sets the color to `inherit` which overrides any custom button color settings

**To reproduce**
1. Add a button
2. Change the color to anything beyond the default.
3. Publish and hover over the button.

**Expected behavior**
The color of the button should stay the color that was selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser: Chrome (latest version)

**Additional context**
- Using Gutenberg 5.8 w/ 2019 Theme

**Comment by karmatosed** [comment]
I don't seem able to replicate this myself, would you be able to confirm with me if you are still experiencing this @bbertucc?

**Comment by bbertucc** [comment]
Yep, @karmatosed - Looks like this was resolved. Thanks for checking in!
