### ISSUE TITLE
How can i use MediaUpload element in a PluginSidebar component. 

### ISSUE THREAD

**Issue by jidefela** [WordPress/gutenberg#16069]
I need to be able to use MediaUpload of wp.editor element within a Panel. Something quite similar to the FeaturedImage uploader. 
 This is what i've got so far. 

`<MediaUpload
	 onSelect={this.onImageSelect}
	type="image"
        value={this.state.imageUrl}
	render={ this.getImageButton }
/>
`
 Using this throw an
 `Uncaught Invariant Violation: Minified React`  error. 

 Any help would be appreciated.

**Comment by swissspidy** [comment]
Have you already consulted the [examples in the readme](https://github.com/WordPress/gutenberg/blob/40797c63bbb5f2c28c0b9af17791d7565d181bc5/packages/block-editor/src/components/media-upload/README.md) and the actual featured image uploader implementation?

**Comment by jidefela** [comment]
I am now.  Very detailed and helpful.  Thanks.
