### ISSUE TITLE
Add a custom ID for each block on a page

### ISSUE THREAD

**Issue by jaclyntan** [WordPress/gutenberg#16064]
**Is your feature request related to a problem? Please describe.**
I'd like to customise each block with CSS by targeting each individually using an ID.

This would be particularly useful on pages with multiples of the same block.
**Describe the solution you'd like**
A custom ID will output in the html for each block.

eg.
```
`<div id="block123" class="wp-block-media-text alignfull has-media-on-the-right is-stacked-on-mobile" style="background-color:#ebf5fe"><figure class="wp-block-media-text__media">...
...
<div id="block124"class="wp-block-media-text alignwide"><figure class="wp-block-media-text__media">...
`
```

**Describe alternatives you've considered**
A section block is an alternative but it could bog down the page a lot. An ID would make Gutenberg x10000 more useful as a page builder.

**Comment by swissspidy** [comment]
If you only need the ID for the frontend, you might consider filtering at the PHP level using the `do_block` filter.

**Comment by jaclyntan** [comment]
Is there documentation on `do_block` I can have a look at?

**Comment by swissspidy** [comment]
https://developer.wordpress.org/reference/ has all the documentation for PHP functions and filters.

Looking at it again, I think the `render_block` filter or the `render_block_data` filter might be better suited

**Comment by jaclyntan** [comment]
Ah ok thanks, yeah I think `render_block` seems more like what I need, do_block**s** is actually for dynamic blocks which isn't what I am using.

**Comment by swissspidy** [comment]
Alright then! I'm closing this one for now. We can always reopen when something comes up.
