### ISSUE TITLE
Blank line at end of each paragraph when pasting from Google Docs

### ISSUE THREAD

**Issue by mikejanssen** [WordPress/gutenberg#16076]
Recently, I've noticed that pasting text from Google Docs into a post results in a blank line at the end of each paragraph block. Looking at the HTML, I can see that it's a `<br>` tag. This is occurring with version 5.2.1 in macOS using Chrome and Safari. It is not happening with Word.

**Comment by karmatosed** [comment]
I can replicate, thanks for reporting this.
