### ISSUE TITLE
Gallery block error after npm run dev

### ISSUE THREAD

**Issue by vanaf1979** [WordPress/gutenberg#16078]
- i forked this repo.
- Cloned it.
- Npm installed it.
- Make a change to the galary-block (Just a space, no actual change to the code).
(File i changed: gutenberg/packages/block-library/src/gallery/shared.js)
- I run Npm run dev.
- I add a galary block in the editor, and add some images.
- I deselect the block, select it again, and deselect it.

Now the block collapses and i get the following error in my console:
TypeError: "props.formatTypes is undefined"

I tried it without building first, and this doest happen.

Am i doing something wrong with the build process? Is this a known issue?

**Comment by youknowriad** [comment]
The builid process seems correct. The issue is probably related to something else: code changes, plugins...
