### ISSUE TITLE
Plus visible in preview

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#16086]
A small "add block" plus is visible in the style variation previews:

<img width="664" alt="Screenshot 2019-06-11 at 10 31 33" src="https://user-images.githubusercontent.com/1204802/59256472-4ed0b700-8c34-11e9-8018-43add3b3ef7d.png">

**Comment by jasmussen** [comment]
This is likely recent, I think @youknowriad may have worked on the plus.

**Comment by donmhico** [comment]
Hello @jasmussen,

I can't reproduce the bug anymore. I'm testing against the latest commit to this writing 85eaee368

<img width="946" alt="Screen Shot 2019-09-03 at 10 04 43 PM" src="https://user-images.githubusercontent.com/5747475/64180279-1ccb9b80-ce97-11e9-9c35-48ace3ecc87e.png">

**Comment by jasmussen** [comment]
Thanks for testing. I believe this may have been fixed by a recent merged change to the preview component. Closing as fixed for now.
