### ISSUE TITLE
Toolbar button line-height is off

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1609]
<img width="528" alt="screen shot 2017-06-30 at 9 57 02 am" src="https://user-images.githubusercontent.com/191598/27738812-817ad342-5d7a-11e7-9ace-853ef84d3fda.png">

The vertical centering for "Insert" and "Post Settings" is incorrect — the labels are too high compared to the icons.

**Comment by jasmussen** [comment]
Are you still seeing this? And if yes, which browser? I can't reproduce in Chrome and Safari.

**Comment by shaunandrews** [comment]
<img width="461" alt="screen shot 2017-08-21 at 2 40 39 pm" src="https://user-images.githubusercontent.com/191598/29533189-ba51142e-867e-11e7-8dca-5255ff1f56ab.png">

I still see it. Latest version of Safari on latest Mac OS.

**Comment by shaunandrews** [comment]
I'm not sure what other info I can give you, but this makes my eye twitch.

**Comment by mtias** [comment]
I believe this is fixed now.

**Comment by shaunandrews** [comment]
Can confirm. Much better now. My eye twitching as stopped. Thank you!
