### ISSUE TITLE
Reset button should be visible when user enter font size.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#16106]
**Describe the bug**
The reset button should be visible when the user enters font size.

**To reproduce**
1. Go to 'Editor'
2. Click on 'paragraph block'
3. Enter font size in the field.'
4. See the Reset button behavior. 

**Expected behavior**

The reset button should be visible when the user enters font size.

**Screenshots**
https://www.screencast.com/t/6mJbhLC8

Thanks

**Comment by epiqueras** [comment]
Fixed by #16148.
