### ISSUE TITLE
Post Settings accordion's are hard to click

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1610]
![sidebar clickable area](https://user-images.githubusercontent.com/191598/27738958-fffbf516-5d7a-11e7-83b4-6739ec5fa5d9.gif)

I keep missing the clickable area on the sidebar's accordion headers — only the text itself is clickable, not the whole header.

**Comment by youknowriad** [comment]
I feel this is a duplicate, already saw something similar elsewhere (and even a PR)

**Comment by youknowriad** [comment]
closing as duplicate #1335 PR pending #1337
