### ISSUE TITLE
Block Naming Convention: Title Case or Not?

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16118]
There is still some confusion around how we should capitalize block names in documentation or when referring to them in text.

Let's look at the Paragraph block as an example.

In the Inserter, we simply call it "Paragraph" but this doesn't clearly indicate how we might refer to it in text. Which one should we go with?

**1. Paragraph block**
Sentence case provides a capital to the name of the block, but leaves the block (the thing) lowercase. So this is how we'd refer to the Paragraph block in a sentence.

**2. Paragraph Block**
Title case provides a capital to both the name and the word "block." So this is how we'd refer to the Paragraph Block in a senetence.

**3. paragraph block**
All lowercase when the block name is not at the beginning of a sentence. So this is how we'd refer to the paragraph block in a sentence.

cc @michelleweber

I'm preferable to number 1.

**Comment by michelleweber** [comment]
In text, #1. This has come up a few times; I'm not sure what the best way is to get everyone on the same page.

**Comment by mapk** [comment]
That was quick! Thanks @michelleweber. I knew it had come up before, but I couldn't find it. So I wanted to have a clear issue about it that we can refer back to in the future. 👍

**Comment by sarahmonster** [comment]
Is this guidance in the documentation anywhere? I'm thinking it should probably belong here: https://developer.wordpress.org/block-editor/designers/block-design/#blocks (and, while we're at it, add a line about the verb + action format for the block description too). 

Thoughts? I'm happy to open a PR if I'm not missing this guidance elsewhere in the docs. 😄

**Comment by chrisvanpatten** [comment]
@sarahmonster I think this is new guidance, and it would be awesome to get into the docs!

As I noted in today's #core-editor chat, I'm also +1 to "Paragraph block", for the same reason you would write "Classic Editor plugin" instead of "Classic Editor Plugin"!

**Comment by pbrocks** [comment]
@chrisvanpatten and you were quoted on this: https://make.wordpress.org/core/2019/06/11/editor-chat-agenda-june-12th/#comment-35973

**Comment by garrett-eclipse** [comment]
Thanks for opening the discussion @mapk I tend to agree with @chrisvanpatten on 'Paragraph block' and once the convention is established am happy to update the [Spelling document](https://make.wordpress.org/core/handbook/best-practices/spelling/) to get this into the Best Practices Handbook. I'll also flag to #polyglots as many have Glossaries to flag this type of thing.

**Comment by mapk** [comment]
Alrighty, we've got consensus with number 1. Write block names accordingly:

Paragraph block
Cover block
Heading block
Image block
Latest Posts block
etc.

@sarahmonster, please create a PR for inclusion in the Docs when you have some time. Thank you! 🚀

**Comment by chrisvanpatten** [comment]
Thanks for taking action and confirming the consensus, @mapk!

**Comment by garrett-eclipse** [comment]
Thanks for the consensus all. I've added an entry to the Spelling handbook here;
https://make.wordpress.org/core/handbook/best-practices/spelling/

> “Paragraph block” | “Paragraph Block” or “paragraph block” | When referring to blocks capitalize the block name and keep ‘block’ lowercase. github#16118

I've also updated the locale glossaries I have access to and am posting to #polyglots
