### ISSUE TITLE
didPostSaveRequestSucceed data selector function 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#16124]
Hi, 
This function is a part of post editor data for data module, could be found here: 
https://developer.wordpress.org/block-editor/data/data-core-editor/

This function is returning false on publishing a new post, it should return true for either saving already published post or publishing a new one

**Comment by tellthemachines** [comment]
Hi @DOUARA ! Could you please add some more info on this issue, such steps to reproduce and environment you're running in?

**Comment by talldan** [comment]
Closing, as there's not been a reply in several months. This can always be reopened if the requested info is provided.
