### ISSUE TITLE
Add attribute types to docs

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#16128]
When registering a block you can define the attributes and their types, but I can't find any docs detailing what the allowed types are.

https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-attributes.md

I can guess what some of them are, but what about boolean? Is it boolean or bool? And number/ int/ float/ all of the above?

I think a proper list would be very helpful.

Thanks

**Comment by aduth** [comment]
I agree it should be documented more explicitly. To answer, the types support is meant to align with JSON Schema types, similar to that of the [schemas](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/) used in [registering REST routes](https://developer.wordpress.org/reference/functions/register_rest_route/) server-side.

https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1

**Comment by BinaryMoon** [comment]
Thanks - that helps.

**Comment by AdamDTak2112** [comment]
I can work on getting this info stated explicitly on the documentation, if still needed!

**Comment by chrisvanpatten** [comment]
@AdamDTak2112 That would be awesome!

**Comment by AdamDTak2112** [comment]
@chrisvanpatten Perfect. Should I include the Schema page that @aduth posted above listing the various types, or are a brief list enough for the developer to understand?

**Comment by chrisvanpatten** [comment]
@AdamDTak2112 I think a brief list would be a good starting point, and also maybe link out to the Schema docs for the WP REST API: https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/
