### ISSUE TITLE
Snackbar link becomes unreadable when focused and hovered

### ISSUE THREAD

**Issue by hempsworth** [WordPress/gutenberg#16122]
Snackbar notification links are unreadable when focused and hovered, due to button styles combining. The focus state gives the link a white background, the hover state makes the link white.

**To reproduce**
1. Save a post or page to create a new snackbar notification.
2. Focus the 'View Page' link inside the snackbar (right-click will do it).
4. See that it becomes a white rectangle, with the text unreadable.

**Screenshots**
![snackbar](https://user-images.githubusercontent.com/92863/59361876-7609b000-8d2a-11e9-91e0-cb94425446ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 74.0.3729.169

**Additional context**
- Gutenberg version 5.9.0

**Comment by swissspidy** [comment]
Seems to be theme dependent. In my quick testing the link color was at least not white. But the contrast is bad, regardless of the state (hover, focus, nothing)

**Comment by JustinyAhin** [comment]
I've tried all the default themes from 2012 to 2020, and the snackbar link background is always white when I click on it.

**Comment by gziolo** [comment]
It was fixed in https://github.com/WordPress/gutenberg/pull/17887.
