### ISSUE TITLE
Clickthrough: Quick access elements (since 5.9)

### ISSUE THREAD

**Issue by HarwinBorger** [WordPress/gutenberg#16120]
**Is your feature request related to a problem? Please describe.**
In 5.9 a new feature was added to access elements easier by clicking through them. However if you just want to edit the text (and the text is 5 levels deep) then this method could be in the way. 

**Describe the solution you'd like**
It would be nice if you can direct access the component by for example `cmd`+`click` (osx) or `alt`+`click`(windows). This way you don't need to click 5 times to edit the text element. 

This method would benefit you both the new and old way to get to an element.

**Comment by swissspidy** [comment]
For reference, this was added in #15537.

**Comment by onuro** [comment]
The shortcut option is a good way of it, however an informative on boarding might also be needed so a user would know there is such a shortcut for it, without having to check the shortcut list.

How about something like this?

![helper](https://user-images.githubusercontent.com/645713/60723730-1f645000-9f3d-11e9-8219-a3234eb9105b.png)

**Comment by youknowriad** [comment]
I think the solution presented here is a good middle-ground to solve both text-first selection and top-bottom selection #17088 Let's consolidate there
