### ISSUE TITLE
Surface user handbook in editor interface

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#16132]
Previously: #11252

Relevant Slack conversations ([links require registration](https://make.wordpress.org/chat/)):

- https://wordpress.slack.com/archives/C02QB2JS7/p1558531784196900
- https://wordpress.slack.com/archives/C02RQBWTW/p1560372677442600

A block editor user handbook can be reached at the following URL:

https://wordpress.org/support/article/wordpress-editor/

However, there are not very obvious paths for how a user might reach this documentation.

We should consider how to present these guides to a user who is becoming acclimated with the block editor.

Options to consider, amongst other possibilities:

- As part of the "New User" tips which appear upon first load of the editor, include a link to the user documentation
- Include a "Help" menu link under the "More tools & options" menu in the top-right, which directs to this navigation
- Reincorporate the "Help" panel which appears at the top of other administration screens ([screenshot](https://user-images.githubusercontent.com/1779930/59386300-4e1f4a00-8d34-11e9-85ac-e2742ca5d738.png))

**Comment by swissspidy** [comment]
Is that handbook translated / translatable? That would be a requirement for adding this IMO.

**Comment by karmatosed** [comment]
If it's translatable I think this would be great. If not, we should see about getting it translated and then adding it :)

**Comment by chrisvanpatten** [comment]
@swissspidy @karmatosed Right now the handbooks are _not_ translatable, but I'd recommend following up with the #docs team in Slack. There have been a number of proposals on how to support translations in HelpHub/DevHub, and I think they would absolutely welcome more attention to the issue. They are aware of the importance but have not been able to coalesce around a solution.
