### ISSUE TITLE
Font color depends on the theme's font setting 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#16141]
**Describe the bug**
The color of the font on the edit page (gutemberg) changes to the same color of the fonts on the theme.

What makes particularly impossible to work with a white font. My site has a black background and white fonts:
![image](https://user-images.githubusercontent.com/11801254/59394005-0c9a9900-8d4c-11e9-8b9e-21fc8fcfe267.png)

And when editing it gets the same color, but the background on the edit mode is also white, making the fonts invisible:
![image](https://user-images.githubusercontent.com/11801254/59394396-8b440600-8d4d-11e9-8d17-d9be41ba9b56.png)

The only way i can type and see is by selecting the text and memorizing the positions:
![image](https://user-images.githubusercontent.com/11801254/59394078-5aaf9c80-8d4c-11e9-9af9-16ec3423f7bd.png)

Of course i can change the color of the fonts to edit, and then change it back, but that will change the font color on the site while i am editing. 

**To reproduce**
1. Go to Appearance > Editor
2. Click on Fonts
3. Change Header 1 and paragraph colors to **white**
4. Publish the change
5. Go to Pages>All Pages and edit one page
6. Create a paragraph or a header block and write something on it.
7. The font will be white, and impossible to see

**Expected behavior**
The font should keep being black, so it contrast the white background

**Screenshots**
![image](https://user-images.githubusercontent.com/11801254/59394310-28eb0580-8d4d-11e9-96c0-29914bd70e3a.png)

![image](https://user-images.githubusercontent.com/11801254/59394325-330d0400-8d4d-11e9-87d5-12d39878269e.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser chrome
 - Version 74 Stable

**Comment by swissspidy** [comment]
Which theme are you using?

Changing font colors like this is not a default feature. So I'd argue that whatever theme you use would need to add the necessary compatibility with the editor.

**Comment by avagp** [comment]
You are right.

I am using Storefront, the Woocommerce default theme.

**Comment by avagp** [comment]
So, it will be better if i go and report it to storefront support?

**Comment by swissspidy** [comment]
I‘d say yes. :)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. Since this is an issue that is very specific to your theme, I am closing the issue.

**Comment by avagp** [comment]
I have to keep adding this.

My theme is storefront, which is fairly popular.

Now in the lasts versions, gutenberg's editor changes the background color matching the color of the site, so i can see the letters.

BUT, this is not the case with the HTML block

![Screenshot 2021-01-26 at 15 22 51](https://user-images.githubusercontent.com/11801254/105887340-610a8f00-5fea-11eb-8597-cb59145eb447.png)
![Screenshot 2021-01-26 at 15 22 47](https://user-images.githubusercontent.com/11801254/105887343-62d45280-5fea-11eb-8269-eceae0338405.png)

**Comment by jordesign** [comment]
Hi @skorasaurus - in my testing now the HTML block handles this correctly.

* Editing HTML shows dark text on light background
* Showing preview matches the style of the theme/page and is still readable.

https://github.com/WordPress/gutenberg/assets/1842363/fb7016ee-aa68-4a89-962f-0f0c9cdac866

As such - I'll close this issue.
