### ISSUE TITLE
Make WP navigation (sidebar) behaviour available outside of Gutenberg

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/gutenberg#16155]
Hey there,

Gutenberg introduces a new navigation behaviour for the WP sidebar. When editing a post, scrolling affects either the Gutenberg area or the navigation menu, depending on the position of the mouse:

![gutenscroll](https://user-images.githubusercontent.com/39319746/59431855-2ab4d780-8de6-11e9-8f74-dcbd3de148a7.gif)

When one is outside the editor, the content and the sidebar scroll at once, no matter where the mouse is:

![wpscroll](https://user-images.githubusercontent.com/39319746/59431893-428c5b80-8de6-11e9-8a67-1bb12a5293a7.gif)

I would love to have the editor scroll behaviour work that way on every part of the admin area. Is that possible somehow?

Best,
Dennis

**Comment by swissspidy** [comment]
> I would love to have the editor scroll behaviour work that way on every part of the admin area. Is that possible somehow?

Personally I don't think that would be desired user behavior.

In any way, since you are asking for an enhancement in WordPress itself and not in the editor, I recommend you to create a new ticket over at https://core.trac.wordpress.org/
