### ISSUE TITLE
Unable to add Blocks at bottom of editor window

### ISSUE THREAD

**Issue by ShaneSchroll** [WordPress/gutenberg#16162]
**Describe the bug**
When using the Block Editor, If a block is added near the bottom of the editor (creating a scrollbar) there is no way to add more blocks below it aside from using the + sign at the top right of the page.

**To reproduce**
1. Add blocks until the block editor creates a scrollbar
2. Attempt to add a block below the block that caused the scrollbar
3. There is no + sign below that block (and maybe 2px of space before ramming into the bottom of the browser window

**Expected behavior**
A + sign would be shown below the last block on the page along with allowing the editor to scroll beyond the last block (similar to code editors "Scroll beyond last line').

**Screenshots**
![image](https://user-images.githubusercontent.com/24775885/59451796-ec152200-8dd1-11e9-8c48-c4b463a7f9e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 [Version 10.0.17134.829]
 - Browser: Firefox Developer Edition (always up-to-date)
 - Version: It updates almost every time I open it. (multiple times a day)

Please add a "Scroll beyond last block" option. This would make the block picker drop down have more room than being smashed against the bottom browser window making selecting blocks very difficult.

**Comment by karmatosed** [comment]
Thanks for reporting this, whilst I can replicate I did want to comment on the flow. The expectation is you hit return to then open up the ability to add. Personally, whilst I don't think adding a '+' picker is needed there could be some easing here. 

I'd love to know what others think about this so marking I can replicate and for feedback.

![image](https://user-images.githubusercontent.com/253067/61559730-41dc8a00-aa62-11e9-959b-018c1947b59c.png)

![image](https://user-images.githubusercontent.com/253067/61559740-4a34c500-aa62-11e9-8689-86c07b978752.png)

**Comment by kjellr** [comment]
We do have https://github.com/WordPress/gutenberg/issues/14852 (and the associated PR, https://github.com/WordPress/gutenberg/pull/15165 open to address the issue of adding more space at the bottom of the editor.

One possible idea for inserting a subsequent block would be to have the sibling inserter appear on the last block, to give you a clear way to add a subsequent block without necessarily having a full inserter. Currently, it doesn't show up on the last block: 


![Screen Shot 2019-07-23 at 12 22 09 PM](https://user-images.githubusercontent.com/1202812/61729172-a9d1ef80-ad44-11e9-8bd6-36358fdf64a7.png)

**Comment by mapk** [comment]
I believe the Typewriter effect fixes this: https://github.com/WordPress/gutenberg/pull/16460
