### ISSUE TITLE
Rendering a block with PHP instead of Javascript

### ISSUE THREAD

**Issue by Alexius08** [WordPress/gutenberg#16171]
I just discovered that blocks don’t update their HTML code when changes to the CSS and Javascript are made unless posts containing the blocks are loaded in the editor and saved again. To ensure that the block HTML is always updated whenever changes to the code are made, I'll use PHP instead of Javascript for rendering.

However, one of the block attributes specify a source, e.g.

	someText: {
		type: 'array',
		source: 'children',
		selector: '.container-for-some-text'
	}

and that one attribute is the only one whose value can’t be read by the PHP script. Is there anything I could do to be able to use the attribute in PHP?

**Comment by Soean** [comment]
If you use a server side render block, there is just a HTML comment saved with the attributes like:

`
`

You don't need to specify a source. See in this example:

```php
register_block_type(
	'core/archives',
	array(
		'attributes'      => array(
			'showPostCounts'    => array(
				'type'      => 'boolean',
				'default'   => false,
			),
			'displayAsDropdown' => array(
				'type'      => 'boolean',
				'default'   => false,
			),
		),
		'render_callback' => 'render_block_core_archives',
	)
);
```

[More infos in the handbook](https://developer.wordpress.org/block-editor/packages/packages-server-side-render/)

**Comment by Alexius08** [comment]
Could data from blocks previously saved under the old attribute format be retrieved?

**Comment by Soean** [comment]
Not automatically, maybe with [deprecating blocks](https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/)
