### ISSUE TITLE
Ability to show/hide Table of Contents & Block Navigation buttons in Header Toolbar

### ISSUE THREAD

**Issue by desaiuditd** [WordPress/gutenberg#16174]
**Is your feature request related to a problem? Please describe.**

Currently there's no way I can hide 2 of the items from the top header toolbar i.e., Table of Contents and Block Navigations.

![Screen Shot 2019-06-14 at 15 21 16](https://user-images.githubusercontent.com/2236554/59485278-720b9880-8eb8-11e9-952e-e023f6c74c1b.png)

Neither there's a UI setting for this nor this is possible via code. Because, The `<HeaderToolbar />` component simply renders both the components without any consideration of settings or any filters that we can use as a developer to show/hide those items.

https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/header/header-toolbar/index.js#L41

As a user, I may not want to have those buttons always present on the screen.

**Describe the solution you'd like**
Couple of approaches I can think of at the moment:

- Maybe some hooks/filters/config in the code so that those buttons can be toggles programmatically via code.
- A UI setting to toggle the visibility of those buttons in the Options modal.

![Screen Shot 2019-06-14 at 15 21 30](https://user-images.githubusercontent.com/2236554/59487156-227c9b00-8ebf-11e9-8688-c2f4984f2f8c.png)

**Comment by gziolo** [comment]
Noting that with #14956 Document Outline and Block Navigation should get merged into one popover. It won't solve the issue you described but might simplify the proposed solution. It might be as simple as adding one item in the General section.

**Comment by priethor** [comment]
This issue is superseded by #44193
