### ISSUE TITLE
icon-button's CSS class has-text test is "too loose"

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#16179]
**Describe the bug**
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/icon-button/index.js

line ~32  - 'has-text': children,

The presence of children !== 'has-text'. That is, the children might not render anything. 

For example, within a custom built component I'm doing something like this:

```
<IconButton>
    { buttonText &&
            <span className="components-button-text__wrapper">
            {buttonText}
            </span>
    </IconButton>
```

I have cases where buttonText is false or blank and the 'has-text' class is still be added. It shouldn't be added unless children actually renders something.

**Comment by talldan** [comment]
Hi @AlchemyUnited. To be able to address any issue, you'd need to provide some more specific examples where line 32 fails. In the case where `buttonText` is an empty string it seems to work fine since an empty string is a falsey value. What kind fo values are you using for `buttonText`?

**Comment by AlchemyUnited** [comment]
@talldan - Per the above... "I have cases where buttonText is false or blank and the 'has-text' class is still be added. " Note: I assign those values to buttonText in the component - not passed in via props - just to be sure I wasn't losing it. 

What I'm reading / seeing is children can return true even if children doesn't ultimately render anything. 

If there's somerthing wrong with the example provided let me know. But I've added that snippet  and I've removed it. And when it's added, even when buttonText is false or empty,  has-text. gets added. It's not complicated ;)

**Comment by talldan** [comment]
@AlchemyUnited - I'm not able to reproduce the issue when `buttonText` is an empty string or false. I don't see the class name added as you suggest.

The code in your example had some syntax errors, I changed it to:
```
<IconButton>
	{ buttonText && (
		<span className="components-button-text__wrapper">
			{ buttonText }
		</span>
	) }
</IconButton>
```

When using an empty string or false, this was the markup the component produced:
<img width="210" alt="Screen Shot 2019-06-19 at 2 39 59 pm" src="https://user-images.githubusercontent.com/677833/59834671-a6fc6d00-9348-11e9-9cfc-d92e9c357a1c.png">

It has no `has-text` classname as expected. 

If you can provide more info about what your variable for `buttonText` contains that'd be helpful. It could be that you have a non-empty string like `' '`, which would be a truthy value.
