### ISSUE TITLE
insertBlocks not working in Inner Block Column

### ISSUE THREAD

**Issue by anik4e** [WordPress/gutenberg#16175]
**insertBlocks not working in Inner Block Column**
I try to insert paragraph programmatically in  column block. It works great in previous gutenberg version but not worked in latest version. insertBlocks working great in simple block but not inside in nested block like "Column".

`wp.data.dispatch( 'core/editor' ).insertBlocks( wp.blocks.createBlock('core/paragraph', { content: 'Test Data' }), 0, 'ParentClientID', true )`

I already check this issue and try to use it but failed.
https://github.com/WordPress/gutenberg/issues/10296

**Comment by youknowriad** [comment]
Did you try the `5.9.1` release? Does it fix your issue?

**Comment by anik4e** [comment]
I am using WordPress 5.2.1 & Twenty Nineteen theme. Not fixed yet.

You can check this in your browser console. Hope you will got the problem.

All block list-
`wp.data.select('core/editor').getBlocks()`

Insert a new created block()-
`wp.data.dispatch( 'core/block-editor' ).insertBlocks( wp.blocks.createBlock('core/paragraph', { content: 'Test Content' }),0, 'REPLACE_PARENT_CLIENT_ID, true )`

First add "Column" in page. Then try to insert a paragraph block into the column inner block(Via Column's parents client ID).
