### ISSUE TITLE
Consider using font-relative widths and heights in containing elements

### ISSUE THREAD

**Issue by anevins12** [WordPress/gutenberg#16181]
**Is your feature request related to a problem? Please describe.**
When structural elements contain text, we should consider setting their widths or heights in a way that responds to text size increase (not talking about zoom here).

This came about when looking at the resolution for #15973 . This is fine, but the sidebar is still very cramped with the increase of font size. It could do with being larger.

**Describe the solution you'd like**
Using `em` on the container's width or height values so that when text size increases, the containers also increase. 

We can start this approach on the sidebar discussed in 15973.

**Describe alternatives you've considered**
I think can use CSS 'max-width' to define a PX constraint to meet the design, and instead use CSS 'width' as the relative measurement:
`
.foo {
    max-width: something-reasonable-px;
    width: 100em
}
`

**Comment by paaljoachim** [comment]
@aristath and @ItsJonQ 
Is this issue still relevant?

**Comment by aristath** [comment]
>  Is this issue still relevant?

I don't think so, all block styles now use `em` values and not `px`, with just a few exceptions that don't have anything to do with this ticket.
I'll go ahead and close this issue, if however I am mistaken please feel free to post some clarifications and we can reopen it for further discussion :+1:
