### ISSUE TITLE
Mobile / iOS: Regression with "enter" behavior and jumping viewport

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#16193]
**Describe the bug**
The viewport jumps when pressing Enter on an iPhone.

**To reproduce**
1. Go to the editor on an iPhone.
2. Type text, press enter.

Notice how the viewport jumps a great deal for every time you press enter.

**Expected behavior**
This is a regression, not sure from when. In the past, @ellatrix fixed this using something that is close to "typewriter" scrolling (see #353). 

**Screenshots**
![linebreak jumping](https://user-images.githubusercontent.com/1204802/59586272-d5790e80-90e2-11e9-9831-b4ca6d34ab94.gif)

**Comment by ellatrix** [comment]
The fix was removed in #11971. It would be very good to know what changed. :)

**Comment by ellatrix** [comment]
#9716 reports that the block sometimes gets hidden behind the keyboard after pressing Enter. I think both of these problems could be fixed at once by ensuring that the block is always in view.

**Comment by ellatrix** [comment]
https://www.youtube.com/watch?v=fnfNsMWK9CI

https://www.youtube.com/watch?v=hEAr6_kw3vc

**Comment by jasmussen** [comment]
@ellatrix I suppose I can close this now that typewriter is merged, right?

**Comment by ellatrix** [comment]
@jasmussen To be honest, I would still leave it open. While the typewriter experience alleviates the problem, there's still some jumping. The jumping also still occurs when you use the  ˄˅ keys on the virtual keyboard. I think there's something going on in Gutenberg, as this doesn't happen normally with `contenteditable` + iOS, so it should be fixable. Perhaps The way we move selection isn't the best. It's not high on my priority list, but still worth looking into...

**Comment by fluiddot** [comment]
We still have this issue about the scroll jumping when creating a new block after pressing `enter`, however, it's no longer as jumpy as described in this issue. I'm closing it as we are already covering it at https://github.com/WordPress/gutenberg/issues/40029.
