### ISSUE TITLE
Pre-publishing panels for contributors

### ISSUE THREAD

**Issue by christincooper** [WordPress/gutenberg#16198]
There is a bug when displaying the pre-publish panel for `contributor` users. A bug report was added to [trac](https://core.trac.wordpress.org/ticket/47596) but it's suggested to post Gutenberg bugs here on GitHub. 

The pre-publish panel ([PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/)):

![pre-publish-panel](https://i.imgur.com/5YnQ3vi.png)

Is **not** displayed (_with_ the panels) for users without publishing capability (`contributor` role etc). So these users see:

![pre-publish-panel-contributor](https://i.imgur.com/HD1R9vl.png)

Meaning, any panels we add to [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/) will _not_ be displayed to contributors. 

It was initially there, but because some unwanted panels were displayed for contributors (see [#6729](https://github.com/WordPress/gutenberg/pull/6729)), they somehow entirely removed the pre-publish screen for contributors. Probably by mistake, making this essentially a bug. If not, a major design error, **because contributors need tips the most**.

If we can't fix this bug and add PluginPrePublishPanel for contributors, maybe we can at least introduce something like PluginPre**Review**Panel...

---

Contributor users are the ones who need publishing suggestions the most, as they are submitting a post for review, meaning, they are _least_ familiar with the publishing guidelines of the site.

A [great example](https://wordpress.stackexchange.com/a/339662/24875) of how the **PluginPrePublishPanel** can be used for contributors.

Can we fix this bug and have [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/) enabled for contributor users?

**Comment by gary-woods** [comment]
I really have to agree with this. It makes no sense that [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/) is not displayed to `contributor` users when they are the ones who need publishing suggestions the most!

Looks like the panels were removed when the visibility panel was accidentally displayed to contributor users, see [#6725](https://github.com/WordPress/gutenberg/issues/6725). 

I definitely suggest enabling **PluginPrePublishPanel** for contributor users as well as the purpose of it is to provide guidance and they need it the most. Alternatively, something like PluginPre**Review**Panel could work.

**Comment by christincooper** [comment]
A [bug report](https://core.trac.wordpress.org/ticket/47596#ticket) has been opened on Trac.
