### ISSUE TITLE
wp_set_script_translations on extended core blocks

### ISSUE THREAD

**Issue by mperes** [WordPress/gutenberg#16191]
Hey Folks, hope this message finds you all well.

We have a plugin that extends the core image block and we haven't been able to add support to translation to it. Tried using wp_set_script_translations without success. Translation works fine on php side of things, but on JS it does not. Is there a way to debug this?

Cheers,
Miguel

**Comment by swissspidy** [comment]
Please share the code you have tried using so far.

Most issues are usually with improper usage of text domains or wrong file names of the translation files.

**Comment by mperes** [comment]
Hey Pascal, glad to hear from you, and thanks for the quick reply. Below is an abstracted version of the code I am using. By the way, I tried moving the registering the script and moving wp_set_script_translations to init hook but that did not make any diff.

`<?php
/*
  Plugin Name: My Plugin
  Text Domain: my-plugin
 *
 *
 */

load_plugin_textdomain( 'my-plugin', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );

function myPlugin() {
  wp_enqueue_script(
    'my-plugin-script',
    plugin_dir_url(__FILE__) . 'my-plugin-script.js',
    array('jquery', 'wp-api', 'lodash', 'wp-blocks', 'wp-editor', 'wp-element', 'wp-i18n',),
    true
  );
  if(function_exists('wp_set_script_translations')) {
    wp_set_script_translations('my-plugin-script', 'my-plugin');
  }
}

add_action('enqueue_block_editor_assets', 'myPlugin');


//--------------------------------------------------
// my-plugin-script.js
//--------------------------------------------------
var addFilter = wp.hooks.addFilter;
var __ = wp.i18n.__;
var createHigherOrderComponent = wp.compose.createHigherOrderComponent;
var Fragment = wp.element.Fragment;
var InspectorControls = wp.editor.InspectorControls;
var PanelBody = wp.components.PanelBody;
var SelectControl = wp.components.SelectControl;
var TextControl = wp.components.TextControl;
var CheckboxControl = wp.components.CheckboxControl;

var modifiedCoreImageBlock = createHigherOrderComponent(function (BlockEdit) {
  [...]
  return function (props) {
    return React.createElement(Fragment, null, React.createElement(BlockEdit, props), React.createElement(InspectorControls, null, React.createElement(PanelBody, {
      title: __('My Plugin', 'my-plugin'),
      initialOpen: true,
    }, React.createElement(TextControl, {
      label: __('Some Label', 'my-plugin'),
      value: value,
      onChange: onChange,
      onBlur: onBlur
    })
  )));
  };
}, 'modifiedCoreImageBlock');

addFilter( 'editor.BlockEdit', 'my-plugin/editor', modifiedCoreImageBlock );
`

**Comment by swissspidy** [comment]
Thanks!

Where are your JavaScript translation files stored?

For this to work, you'd need to have JSON files in the form `$textdomain-$locale-$handle.json` within your plugin's `/languages` folder, e.g.  `my-plugin-de_DE-my-plugin-script.json` for the German translation. Then, you'd need to pass the path to the translation files when using `wp_set_script_translations()` as follows:

```php
wp_set_script_translations( 'my-plugin-script', 'my-plugin', plugin_dir_path( 'my-plugin' ) . 'languages' );
```

If your translation files are stored within `wp-content/languages` (usually the case for plugins available on WordPress.org), you can keep using `wp_set_script_translations( 'my-plugin-script', 'my-plugin' )` though. However, your JSON files are usually named differently in that case.

You can read more about how it works [here](https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/) or also [here](https://pascalbirchler.com/internationalization-in-wordpress-5-0/).

**Comment by mperes** [comment]
Hi Pascal,
My files are in plugin/languages, I generated them using po2json input.po output.json -f jed. However, I was not aware I needed to append the script slug to the end of the json file name, my bad. I will test it out and return to you. From what I read in the articles you pointed out, It should work out fo the box, with the code above, when made available at  WordPress.org, right?

On a related note, do I still need to declares "messages" as "domain" in the json or may I use the plugin domain already?

Cheers,
Miguel

**Comment by swissspidy** [comment]
> It should work out fo the box, with the code above, when made available at WordPress.org, right?

Yep. WordPress tries to do all of this for you in that case.

> On a related note, do I still need to declares "messages" as "domain" in the json or may I use the plugin domain already?

As of WordPress 5.0.3, both work! So you can just use your text domain _OR_ `messages`.

**Comment by mperes** [comment]
Pascal,It did work flawlessly. You have my thanks, Sir!

**Comment by mperes** [comment]
By the Way, Pascal, if I leave the wp_set_script_translations( 'my-plugin-script', 'my-plugin', $path) like that, am I right to assume it will still work when hosted on wordpress.org?

**Comment by swissspidy** [comment]
Glad to hear it worked!

And yes, it would still work once you publish it on WordPress.org. `load_script_textdomain()` in WordPress looks for translations in both locations.
