### ISSUE TITLE
Allow Group block contents to toggle between "centered" and "full-width" mode. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16197]
Following up from #15210. 

- Add a "centered column" toolbar control (possibly [using this icon](https://user-images.githubusercontent.com/1204802/58235262-c5b71600-7d40-11e9-8c7e-71bc268195c0.png)). This will be on by default.
- When this control is off, we'll remove (or ignore) the inner div from the Group block.
- When this control is off, we'll also disable all wide/full controls for child blocks. All children of the group block will take up all available horizontal space within the group block. 

---

"Centered column" is turned on: 

![](https://user-images.githubusercontent.com/1204802/58234522-06159480-7d3f-11e9-8581-8d274fff9df7.png)

"Centered Column" is turned off: 

![](https://user-images.githubusercontent.com/1204802/58234515-01e97700-7d3f-11e9-93b3-5fbbd4277b27.png)

**Comment by draganescu** [comment]
Hi @kjellr isn't this the same as the current wide/full setting on the Group block. The example in the second picture above can be achieved with setting the group to full and a cover to full.

**Comment by kjellr** [comment]
_Sort of_. I think the goal of this was actually to have a setting so that even interior blocks without wide/full options (like a paragraph for example) would still take up the full width in there. 

But that said, I think there are a bunch of potential ways around this. I'm not totally sure it makes sense to keep this open for now.

**Comment by draganescu** [comment]
In this case I'll close it and we can reopen at any time :) Thanks!
