### ISSUE TITLE
Gutenberg is broken on IE since react-spring was introduced

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#16194]
**Describe the bug**

Navigating to the post editor in IE11 results in a blank page. Dev tools console shows multiple JS syntax errors. 

**To reproduce**

1. Check out the master branch
2. On IE, in wp-admin, navigate to "new post" or any or edit any existing post.
3. Verify blank page results, open console and check errors (you may need to reload the page for all console errors to display)

**Expected behavior**

Post editor should work correctly in IE

**Desktop (please complete the following information):**

 - OS: Windows 7, WIndows 10
 - Browser: Internet Explorer
 - Version: 11 (latest)

**Additional context**

There's a related issue in `react-spring` repo that outlines a solution: https://github.com/react-spring/react-spring/issues/552#issuecomment-464680114
I have tested that fix on my local and it works; IE displays correctly after modifying webpack config and rebuilding.

**Comment by talldan** [comment]
Tested version 5.9.2 of the plugin on IE11 and confirm the error is present in the published plugin as well.

Looks like `react-spring` was introduced in 5.9 in https://github.com/WordPress/gutenberg/pull/15908
