### ISSUE TITLE
Classic block content not displaying inside advanced columns block

### ISSUE THREAD

**Issue by emar** [WordPress/gutenberg#16192]
Hi,

Wordpress: https://wordpress.org/support/topic/cant-displaying-classic-block-content-inside-advanced-columns-block/#post-11643803

I have the Classic Block inside Advanced Columns block.
If I refresh the editor page it says

This block contains unexpected or invalid content.

Two buttons: Resolve & Convert To HTML.
Only the Resolve button works.

In the resolve block window,
Convert to html or Convert to blocks don’t do anything.

So if I refresh the page I can’t edit anything,
All I see is this https://snag.gy/jpxbJ3.jpg

Any help appreciated,

Thanks

**Comment by talldan** [comment]
Thanks for the report @emar. This is a bug at the moment unfortunately, there are some details on issue #13187. That's already been given a priority of high. I'll close this issue for now as a duplicate.

**Comment by emar** [comment]
Thanks for the info Talldan, hopefully it'll be sorted soon.
