### ISSUE TITLE
Block: Paragraph > Toolbar > Change typography > Wonky UX

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#16217]
**Describe the bug**
This is fringe-y and I'm adding simply for completeness. 

If the paragraph block is the last block and the typography is manipulated (e.g., the font size is increased) the block will expand up such that the opened typography toolbar menu moves out from under the pointer / cursor. 

**To reproduce**
Block: Paragraph > Toolbar > Change typography

Then change the size, line height, and I suppose enough letter spacing would do it. 

**Sidebar**
For a UX perspective it's my (albeit personal/subjective) opinion that block-wide settings should not be listed side by side on the toolbar along with more granular "intra-block" settings. For example, with the paragraph toolbar there's a B (for bold) for bolding some selected sub-text out of the block's text universe (if you will). But then also in the Change typography menu there's a Weight: Bold option (for making changes at the entire block of text level).

The "global" block-wide settings should be in the Inspector panel. That is, what you see on the toolbar is directly related to the "inner-block" content you see. And what's in the Inspector is for tools at the higher broader block level. 

When the two are mixed as they are, this becomes a violation of "Don't make me think".

**Comment by swissspidy** [comment]
Gutenberg doesn't have typography settings as you describe them here. Are you using a plugin to add these?

Mind sharing a screenshot here?

**Comment by AlchemyUnited** [comment]
@swissspidy - You are so correct. I sit in shame. I had CoBlocks active and it was adding this. 

I apologize for the mix up. I promise to be more careful next time. Again, sorry.
