### ISSUE TITLE
Can't enter a tab

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1621]
Everytime I use the tab key, it takes me to a new block. I expect the tab key to insert a tab charachter while I am typing.

**Comment by swissspidy** [comment]
Possible duplicate of #1552.

Just note that such behaviour could quickly result in a keyboard trap for users, where you can't use tab for navigation anymore.

Probably one of the reasons it's not implemented in the current WordPress editor.

**Comment by afercia** [comment]
@aaronjorbin I;d be in favor of closing this issue, as the native behavior when pressing the Tab key is navigating through focusable elements. Even in TinyMCE, pressing Tab doesn't insert a tab character. Only in ordered/unordered lists it's used to indent the list items.

**Comment by jasmussen** [comment]
Given that there are accessibility concerns with this particular approach, and the discussion is likely to resurface for the code editor, I'm going to close this one for now. I would suggest that it is fine to open for discussion on a per-block basis.
