### ISSUE TITLE
wp_kses_post removes gutenberg functionality

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#16211]
**Describe the bug**
It seems that wp_kses_post() removes some tags that are generated by certain gutenberg blocks and thus removing the blocks functionality:

**To reproduce**
1. use wp_kses_post() to display page or post content in a theme
2. add the "search" block in Gutenberg (subsection widgets)
3. look at the generated page: the <form> and <input> tags are missing and the search block does not work.

**Expected behavior**
wp_kses_post() should not remove "default" Gutenberg functionality.
(or is wp_kses_post() not supposed to be used on post content? maybe I am doing something wrong here...)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 60.7.0

**Additional context**
- Wordpress Version 5.2.1

**Comment by ellatrix** [comment]
Why are you using `wp_kses_post`? Why not use `the_content` or `get_the_content`?

**Comment by estebanwaseaten** [comment]
Good question, ellatrix.
I have solved the issue by more or less exactly doing that. 
As wp_kses_post() exists, I was still wondering if it was intentional that the tags are removed by it (and why). Thanks for your quick reply!
