### ISSUE TITLE
NUX Tips: 2nd through 4th tips appear clipped off screen on mobile

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16225]
**Describe the bug**

The 2nd through 4th NUX tips appear clipped off screen on mobile. 

**To reproduce**

1. Open the editor for the first time on mobile. (you can also run `window.localStorage.clear()` from the JS console and reload the page).
2. Tap on "See next tip" 
3. See error
4. Continue tapping "See next tip" to see the error repeat itself for subsequent tips. 

**Screenshots**

![tips](https://user-images.githubusercontent.com/1202812/59777077-eca23280-9281-11e9-8de8-afe9166789b1.gif)

**Desktop (please complete the following information):**
 - iOS 12.3.1, Safari
 - MacOS 10.14.5, Chrome 74.0.3729.169 (with a small viewport)

**Comment by gziolo** [comment]
It seems like there is a general issue with popovers on the small screen:

![Screen Shot 2019-10-10 at 17 17 31](https://user-images.githubusercontent.com/699132/66582333-e2ce7300-eb81-11e9-83d7-83acf9783501.png)

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
