### ISSUE TITLE
Gutenberg editor display issue

### ISSUE THREAD

**Issue by Bandi017** [WordPress/gutenberg#16222]
This is a tricky one. I have a new project where i have created several pages ( more than 5 for the beginning). On one of these pages if i want to edit the page i do not fully see the content as if it would have overflow hidden css property. I double checked my CSS and nothing interferes with the editor; but what i did manage to find is this little property: 
@media (min-width: 600px)
.block-editor-block-list__layout .block-editor-block-list__block {
          padding-left: 43px;
          padding-right: 43px;
}
css is coming from this file: .../wp-content/plugins/gutenberg/build/block-editor/style.css...

Sadly i have no way of reproducing this...my other pages work properly but this one single page does not...this is the first time i have encountered this issue. 

Screenshot showing the issue: 
![Screenshot 2019-06-19 10 37 43](https://user-images.githubusercontent.com/25905393/59750316-ec546800-927e-11e9-89f2-d593f98e78d0.png)

**Comment by chrisjreber** [comment]
I've been fighting this one for awhile also. Seems to be with the Gutenberg plugin and not with Gutenberg core. Only happens in Chrome, Firefox is just fine.

To replicate:

1. Fresh install
2. Install Gutenberg plugin
3. on any page add columns block and set to full width
4. add image to any column
5. resize browser to see bug

Already discussed here: [#14652](https://github.com/WordPress/gutenberg/issues/14652), [#14046](https://github.com/WordPress/gutenberg/issues/14046)

**Comment by Bandi017** [comment]
thanks @chrisjreber for the heads-up. I've been using Chrome for such a long time that i completely forgot about loging-in via other browser...You are right...firefox has no issue with this...I consider this closed ad #14652 has enough information. Thanks for the reply
