### ISSUE TITLE
Apply a category to multiple items at once

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/gutenberg#16224]
**Is your feature request linked to a problem? Describe please.**
Unable to select items and categorize them all into one item category at a time.

**Describe the solution you want**
Having the opportunity to finish articles is all in one category

![Screenshot_1](https://user-images.githubusercontent.com/39189263/59771959-25a2cd00-92ab-11e9-9262-c69cc7308668.png)

**Comment by Soean** [comment]
Hey @ValentinGratz 
this interface in not part of the Gutenberg project. 
If I understand your problem, I think you can do it with the bulk actions (Actions groupées) -> edit.

**Comment by Soean** [comment]
I close this issue, because it's not part of the Gutenberg project.
Please use the [forums](https://wordpress.org/support/forums/) if you need more support or open a ticket on [trac](https://core.trac.wordpress.org/) if there is a bug or a feature request.
