### ISSUE TITLE
Justify Button on Safari/Firefox Appears To Not Work in Editor

### ISSUE THREAD

**Issue by sdixon194** [WordPress/gutenberg#16247]
**Describe the bug**
When editing with Gutenberg in Safari or Firefox, clicking on the justify button does not appear to make the text justified in the editor. However on the live site, the post or page is indeed justified. 

**To reproduce**
1. Go to edit or add a post or page
2. Add text inside a paragraph block
3. Click on the button to justify text
4. The paragraph block appears **not** to be justified in the editor. It is, however, still justified on the live site.

**Expected behavior**

The paragraph block in the editor to indicate the paragraph is justified, like it does in Chrome.

**Screenshots**
Gif of what it looks like in Firefox (couldn't get it to embed): https://cld.wthms.co/iFtvr4

Gif of what it looks like working properly in Chrome:

![%filltext:name=Desc%](https://cld.wthms.co/FUhAvc+)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser Safari  12.1.1 , Firefox 67.0.4

**Comment by swissspidy** [comment]
I don't have this Justify option on the latest version of Gutenberg. Are you using a plugin that adds this?

**Comment by mtias** [comment]
Looks to be a WP.com specific issue.
