### ISSUE TITLE
Remove Gutenberg CSS completely (not just the "wp-block-library")

### ISSUE THREAD

**Issue by whwaa** [WordPress/gutenberg#16251]
Is it possible to remove the CSS that covers [this area](https://i.imgur.com/Dqa9STz.png)? How? (i already disabled the "wp-block-library"). I need to create my own style for the editor and I want to avoid overwriting the default css, if is possible. It's bad practice.

**Comment by youknowriad** [comment]
You can try to unregister the default WordPress stylesheets loaded in the editor `wp-editor`, `wp-edit-post`, `wp-edit-blocks` `wp-block-library-theme`, `wp-block-library`.

These might not be that easy to replace entirely.

Also note that for general help requests, we use the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
