### ISSUE TITLE
Using "Ctrl(Cmd) + Z", editor screen become white.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#16257]
**Describe the bug**
I am Japanese. Sorry for ugly English

Frome WordPress5.2.0, occasionally cause an error.

I use "Ctrl(Cmd) + Z", editor screen become white.

<img width="1680" alt="スクリーンショット 2019-06-24 17 30 09" src="https://user-images.githubusercontent.com/31400297/60003491-c6c3c600-96a5-11e9-81ff-44eb971de504.png">

I can not do anything.
I have no choice but to update the window.

So, All articles written up to that point will disappear without being saved.

When I looked at the developer tool, some div elements of div#block-editor has 'hide-if-no-js' class.

And, I received the following message.

![スクリーンショット 2019-06-24 17 28 50](https://user-images.githubusercontent.com/31400297/60003414-95e39100-96a5-11e9-89b4-3486458304c0.png)

**Comment by karmatosed** [comment]
I am sorry you are experiencing that. I am unable to replicate but let's maybe find out if you have a particular theme or plugin combination could be causing this. Do you happen to know any more details about what you are doing before this happens? I understand it's occasional so harder to track down.

**Comment by ddryo** [comment]
Thank you for your reply.

Perhaps the cause may be the code below.
Is something wrong?

`function removeBlcokname(extraProps, blockType, attributes) {
    

    function isValidBlockType(blockName) {

        var validBlocks = [
            'mytheme/style-block',
            'mytheme/button',
        ]
        return validBlocks.indexOf(blockName) !== -1;
    }


    if (isValidBlockType(blockType.name)) {
        extraProps.className = attributes.className;
    }

    return extraProps;

}
addFilter("blocks.getSaveContent.extraProps", "loos/remove-blockname", removeBlcokname);`

This code is deleting a class 'wp-block-hogehoge'.

**Comment by ddryo** [comment]
In the local environment, the bug can not be reproduced.

So, It may occur when the Internet connection is unstable.

**Comment by ddryo** [comment]
The bug may be common when it contains blocks with style changes.

![issue_gif02](https://user-images.githubusercontent.com/31400297/65768579-47460700-e16c-11e9-9ec5-cda8d358d4fc.gif)


I also found that when the bug occurred, the console would output the following error message:
「Uncaught TypeError: Cannot read property 'name' of null」

**Comment by ddryo** [comment]
It has been found that this bug occurs when selecting and changing the style after registerBlockStyle is set to the paragraph block of the core block.

We were able to work around the bug by removing registerBlockStyle for paragraph blocks.
