### ISSUE TITLE
Remove Gutenberg plugin from first page repository suggestions

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#16256]
Hi,

Today Gutenberg plugin is shown in the repository suggestions. 
This create confusion for some people that doesn't understand if Gutenberg is still an add-on, if it's already on the core 
![repo](https://user-images.githubusercontent.com/1785489/60002083-49c62b80-9668-11e9-8f44-2c9931090881.jpg)

The text description create even more confusion "a new experience for WordPress is coming..."
(I train a lot of people for WordPress and they don't feel confortable with this until I explain them).

What could help : 
- Change the plugin title for Gutenberg (beta) 
- Change the plugin description for something like "want to discover the future features of the content editor? Try the beta version! But don't do this on your production website."
- Remove Gutenberg from the first suggestion area so people don't see it immediately

Other benefit : hide the non deserved 2 star note

Talked about this with @youknowriad before posting it here. He thinks that's a good idea.

What do you think?

**Comment by youknowriad** [comment]
I don't think we should remove from the featured plugin's suggestions, that helps us a lot getting it tested properly before shipping in Core. but yeah we should clarify the wording.

**Comment by mtias** [comment]
I don't mind removing it from the featured plugins for now and keeping it in the beta group — it can always be added back if we need another intense round of testing. People have commented some users are confused thinking Gutenberg and the current block editor in WP 5.0+ are separate things. The presence of the plugin so prominently is adding to this confusion.

**Comment by mtias** [comment]
I think by now it's fairly established that Gutenberg gives early access to beta features and we should keep it that way.
