### ISSUE TITLE
Error on import to test file when using @wordpress/scripts to run tests

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#16262]
**Describe the bug**
When running `yarn test:unit` in a plugin using `@wordpress/scripts` I get errors like this:
`    Cannot find module 'core-js/modules/es.date.to-json' from 'Form.test.js'` It is triggered by the first import in any test files.

I fixed it by adding `@core-js` after reading this: https://github.com/TryGhost/gatsby-starter-ghost/issues/29#issuecomment-478265557

**To reproduce**
1. Add a test
2. `yarn test:unit`
3. See error described above

**Expected behavior**
This should not be required.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version "@wordpress/scripts@3.3.0"
- Node v10.16.0

**Smartphone (please complete the following information):**

**Comment by gziolo** [comment]
Related PR #16259 I opened last week. There were some notable changes in Babel 7.4 around `core-js` and we still need to sort out what would be the way to tackle it.

**Comment by gziolo** [comment]
@Shelob9, I hope https://github.com/WordPress/gutenberg/pull/16259 will resolve this issue.

**Comment by gziolo** [comment]
I merged this change, we still need to wait until it's published to npm - it might happen on Wednesday this week.
