### ISSUE TITLE
WP admin bar - no gutenberg edit link

### ISSUE THREAD

**Issue by elkcreative** [WordPress/gutenberg#1627]
Pretty simple one, when previewing or looking at pages in a site, the WP admin bar should include a link to "edit in gutenberg" if you want people to bypass the standard editor. 

It would be ideal to have a jump to link from the standard editor to gutenberg also.

**Comment by westonruter** [comment]
Please review #1797. It improves the links in the post list table as well as adding links to the admin bar and for the edit links for posts with blocks.

**Comment by aduth** [comment]
Closed by #1797
