### ISSUE TITLE
Editing Posts Changes the Permalink for Certain Articles

### ISSUE THREAD

**Issue by basilkhuder** [WordPress/gutenberg#16273]
**Describe the bug**
Certain posts on my Wordpress website will have the permalinks changed, after updating/adding content to existing content. This does not occur for every article that is edited (it seems to happen once every five articles edited.)

Each time, the new permalink will add a number to the end of the slug.  For example, an article with the link:  mywebsite.com/article will become mywebsite.com/article-2.  Additional edits will change the permalink even further - to article-3, article-4, ect. 

**Additional context**

This began happening after I updated to 5.2 (I am now using 5.2.2 and the issue still persists.)

**Comment by suziwilson** [comment]
Hi, How do you have your permalinks set in Settings?

**Comment by youknowriad** [comment]
Closing, let's reopen if we have more concrete items on how to reproduce.
