### ISSUE TITLE
Help: Markup changes not being applied to all blocks. Showing warnings

### ISSUE THREAD

**Issue by afridley** [WordPress/gutenberg#16289]
Question. Recently QA reported accessibility error in the Hero Block on our site. The block had already passed QA but they noticed due to new standards. 

We fixed the bug by changing the edit: and save: functions. 

Now the Hero block on all 300 pages of the website are errored, still working but do not have the new markup, unless we go to the page and update it even then it shows "unexpected or invalid content warning". 

How do we apply the new markup to all 300 pages without going into each page individually?

We may also need to add new features to the blocks in the future. How can we do this without breaking every block on the site?

We are still on stage so this has not been released yet.

**Comment by Soean** [comment]
You can use the block deprecate function, then blocks won't show errors or breaks. Handbook: https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/

To apply the new markup you have to save the post again. I don't know whats the best solution for automating it is.

**Comment by youknowriad** [comment]
Related #7604
