### ISSUE TITLE
Overview: Writing Flow

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#16280]
_Writing Flow_ is a cross component _focus_. The goal of this focus is to make sure that the writing experience of the block editor is painless.

Here will be a summary of the goals and and most important issues.

It comprises:

## Pieces of the [`RichText` component](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BComponent%5D+Rich+Text%22)

The `RichText` component can be used to make pieces of text inside and outside blocks editable with formatting capabilities. This component enables the user to write within blocks.

* Input (typing).
* Format boundaries. (Enables you to navigate around formatting elements.)
* Autocomplete.
* Input Rules. (These are rules to convert given input to a block or formatting. For example, typing `* ` at the start of a paragraph converts it to a block.)

## [Copy, Cut, and Paste](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BComponent%5D+Raw+Handling%22)

Where the handlers are a part of raw handling in the `blocks` package, and are connected to `RichText` instances.

## [History](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3AHistory)

Text and block level **undo and redo**.

### Issues

- [ ] Store selection state in history reducer. (#12327)

### Block Selection & Navigation

* Arrow key navigation.
* [Multi-block selection](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Block+Multi+Selection%22).
* Drag and drop of text and block selection.

These are very closely related and deal with the browser's selection API.

### Block Splitting, Merging, and Deletion

The `Enter` and `Backspace` handlers. This can be on a block level only action (no `RichText` involved), or a block-`RichText` interaction.

**Comment by youknowriad** [comment]
Is this overview issue still necessary @ellatrix ?
