### ISSUE TITLE
Custom Block Attribute Sources

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#16282]
Blocks support two types of attributes:

- Attributes saved to post content (all the sourced and comment attributes),
- Post meta attributes saved to the post meta fields.

In order to support full site editing requirements, the attribute sources need to be expanded to cover a lot more use-cases:

 - Post title attribute,
 - Post content attribute (the whole post content string),
 - Post taxonomies,
 - Basically any editable post property in the REST API post object,
 - Site options attributes.

Instead of supporting all these attribute sources in an ad-hoc way, a generic API to register custom attribute sources should be provided.

**Related Issues and PRs:** <a href="https://github.com/WordPress/gutenberg/pull/5077">5077</a>, <a href="https://github.com/WordPress/gutenberg/pull/16075">16075</a></p>

**Comment by epiqueras** [comment]
We discussed a tentative API for this today with @aduth (we are not convinced of the naming yet) :

![Whiteboarding](https://user-images.githubusercontent.com/19157096/60464648-29284380-9c1d-11e9-8cad-cb93b5b52bfd.png)

The result of our collaborative white-boarding^^ I have to take the blame for the bad drawing skills 😆 

It supports registering custom sources of 3 different types that differ in where the data is kept in memory and storage. "Fetchers & Savers" define where to get the data from at the start of an editing cycle and where to put it at the end of an editing cycle. "Selectors & Actions/Updaters/Dispatchers", which are automatically generated based on the type of the source, define how the attributes are read and modified in memory, during the editing cycle.

It also adds a "shared attributes" slice to the block editor store for blocks to have a single source of truth for global or post-wide attribute sources.

- `type: 'post'` will have fetchers that read from the editor store's post properties and create a special slice of shared attributes that syncs with post properties in the editor store. This is necessary for maintaining block independence from the editor store. Reading and updating the values during editing will be pretty straightforward and the post saving functionality will take care of persistence.

- `type: 'shared'` will have asynchronous fetchers/savers that set/read to/from the shared attributes slice of the block editor store. Reading and updating from shared attributes will give cross-block syncing for free.

- `type: 'local'`, the default, will be almost identical to current standard attribute sources, except that they will have asynchronous fetchers and savers for defining where to get and put the data at the start and end of editing.

@aduth Will keep exploring this while I start to build the first use case for this in #16281 . 

Let's try to get as much feedback as possible on this and keep iterating, as I think that the final API for this will have a huge impact on the project.
