### ISSUE TITLE
pdf in media & text block

### ISSUE THREAD

**Issue by iannacone** [WordPress/gutenberg#16298]
**Describe the bug**
adding a pdf (and maybe others media too) in the media & text block does not show anything.

**To reproduce**
1. create a new page/post
2. add the media & text block
3. click on media library
4. in the upload files tab
5. click select files and select a pdf
   5a. drag and drop the file into the wp uploader
6. now you can select the uploaded file (also if it not visible into the view)
7. save
8. See error

**Expected behavior**
media & text should be available for all the media, if not it should be called image & text.
image block are currently showing a preview from a pdf (with an error #16297).

**Screenshots**
![image](https://user-images.githubusercontent.com/17182025/60177809-2a6f0000-981a-11e9-9a61-283379ea974f.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Smartphone (please complete the following information):**
 - Device: [need to test]
 - OS: [need to test]
 - Browser [need to test]
 - Version [need to test]

**Additional context**
wordpress 5.2.2

**Comment by swissspidy** [comment]
It's basically the same issue as the one you just reported #16297, as you should not even be allowed to insert a PDF there.

**Comment by iannacone** [comment]
then this block should be called image & text, not media & text...

**Comment by swissspidy** [comment]
@iannacone A PDF is a rich-format document format that cannot really be embedded on the web. It's just not possible. You'd have to display it in an iframe, and even then it might not fully work. The Media & Text is designed for inserting images and videos.

**Comment by iannacone** [comment]
ok, but can be considered in the future to display a preview image of the pdf?
i saw a lot of people looking for a pdf block. can be this maybe considered a solution?
