### ISSUE TITLE
Missing mime type validation for images

### ISSUE THREAD

**Issue by iannacone** [WordPress/gutenberg#16297]
**Describe the bug**
adding a pdf (and maybe others media too) in the image block shows a preview, but also the following error messages:
`**Notice**: Undefined index: file in **/[...]/wp-includes/media.php** on line **1381**`
`**Notice**: Undefined index: file in **/[...]/wp-includes/media.php** on line **1397**`

**To reproduce**
1. create a new page/post
2. add the image block
3. click on media library
4. in the upload files tab
5. click select files and select a pdf
   5a. drag and drop the file into the wp uploader
6. now you can select the uploaded file (also if it not visible into the view)
7. save
8. See error

**Expected behavior**
the same, but without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/17182025/60177809-2a6f0000-981a-11e9-9a61-283379ea974f.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Smartphone (please complete the following information):**
 - Device: [need to test]
 - OS: [need to test]
 - Browser [need to test]
 - Version [need to test]

**Additional context**
wordpress 5.2.2

**Comment by swissspidy** [comment]
I have run into similar issues before. The underlying issue is that the editor should not even allow you to select PDF files in an image block. Might be something that needs to be fixed in core.

**Comment by kathrynwp** [comment]
Closing in favour of #18593

Related core bug as mentioned in above issue: https://core.trac.wordpress.org/ticket/39625
