### ISSUE TITLE
Remove the CSS outline on selected Insert tab

### ISSUE THREAD

**Issue by lazharichir** [WordPress/gutenberg#1629]
Set the css property `outline` to `0` for the navigation tabs in the Gutenberg Insert popup box.

What it is now:

<img width="524" alt="screen shot 2017-07-01 at 11 45 14" src="https://user-images.githubusercontent.com/12215372/27760923-efb118de-5e52-11e7-8d15-8c72c501fb43.png">

What is should be:

<img width="331" alt="screen shot 2017-07-01 at 11 46 52" src="https://user-images.githubusercontent.com/12215372/27760928-fd6bc3f2-5e52-11e7-9914-6129af9a6604.png">

**Comment by jasmussen** [comment]
Closing this in favor of #904.
