### ISSUE TITLE
Adding a name to group blocks to be shown in block navigation

### ISSUE THREAD

**Issue by lucspe** [WordPress/gutenberg#16296]
Hi,

Whilst testing the recently introduced "group" block, I find a bit frustrating that there is no way to assign a name to each of them to make it easier to go through the document using the block navigation.

Currently, each "group" block will appear in block navigation simply as "Group" as per screenshot

![screenshot_what_i_see](https://user-images.githubusercontent.com/7618470/60173772-cd6e4c80-980f-11e9-9f6f-fbadddd68ad9.png)

It would be great if there was a way to assign some kind of name to be able to identify what each of those groups are, as per screenshot

![screenshot_what_i_would_like_to_see](https://user-images.githubusercontent.com/7618470/60173821-ed9e0b80-980f-11e9-84cd-21c34b90f080.png)

This is particularly frustrating when dealing with long posts or pages.

Beyond this particular block, in my opinion there are other blocks that could benefit from having the possibility of having a name assigned in the block navigation (such as images, videos, etc.) to make the block navigation a more effective tool.

@karmatosed, we discussed this briefly at WCEU and you suggested that I write it in GitHub. I hope the format is correct and the matter is clear.

Thank you

**Comment by swissspidy** [comment]
Reusable blocks already have names, maybe we can use the same component for that.

**Comment by karmatosed** [comment]
I think being able to add a name to a group block could be a really useful functionality. Thanks for suggesting this @lucspe.

**Comment by mtias** [comment]
It might also be interesting to expose the ID attribute if it's set for a block (group does support a specific anchor).

![image](https://user-images.githubusercontent.com/548849/60195452-66668d00-983b-11e9-8465-b1ede118be23.png)

**Comment by karmatosed** [comment]
What we have now for reusable blocks is this:

<img width="1416" alt="reusable-blocks" src="https://user-images.githubusercontent.com/253067/60292060-3808b080-9914-11e9-9037-1cb1ba13fe01.png">

I took a little exploration into maybe how we could take a slightly different approach:

<img width="2296" alt="alternative-editing" src="https://user-images.githubusercontent.com/253067/60292080-45259f80-9914-11e9-8674-d3c9aac4b076.png">

This gives us both options and maybe even something to explore with reusable blocks.

**Comment by richtabor** [comment]
> I took a little exploration into maybe how we could take a slightly different approach:

Definitely interesting and I like the idea. Thinking aloud here, but a few thought questions: 

Do you think this is important enough to be in the toolbar? Perhaps considering a control in the Sidebar Settings would be more appropriate. And _should_ users be encouraged to add a name to a Group block? Or is it a specialty case? 

I'm wondering how this plays with the context of other blocks. For example, should any block be namable? What's the user's expectation on that front?

**Comment by karmatosed** [comment]
> Do you think this is important enough to be in the toolbar? Perhaps considering a control in the Sidebar Settings would be more appropriate. And should users be encouraged to add a name to a Group block? Or is it a specialty case?

A good point. I went with that location to build on the position of the nested blocks. I wouldn't at all be opposed to explorations there also for nested blocks.

> I'm wondering how this plays with the context of other blocks. For example, should any block be namable? What's the user's expectation on that front?

I think as these have default names or 'group' 'nested', then naming unique names makes sense. However, it does make me wonder what the use case would be for naming anything and if that's something to explore. Thanks for making me think!

**Comment by mtias** [comment]
Let's definitely try this first in the "advanced" panel in the block inspector.

**Comment by karmatosed** [comment]
@mtias here is a quick mock-up to see if what you are thinking about:

![group](https://user-images.githubusercontent.com/253067/61227109-91961b00-a71b-11e9-9ce5-1a02a34dce4c.png)

I actually quite like that as an option, but only if we also change reusable blocks to use that.

**Comment by mtias** [comment]
> I actually quite like that as an option, but only if we also change reusable blocks to use that.

It's more important for reusable blocks to have a name than it is for group blocks. For reusable blocks it is a primary action, for blocks it's just an advanced setting for certain circumstances.

**Comment by lucspe** [comment]
> I think as these have default names or 'group' 'nested', then naming unique names makes sense. However, it does make me wonder what the use case would be for naming anything and if that's something to explore. Thanks for making me think!

@karmatosed & @mtias, let me share some details about why this request came up, maybe it is useful for you. 
We are working on a project where we are converting an existing website that is currently using a different visual builder to use Gutenberg instead. 
The marketing team builds rather complex pages, ther classic examples being landing pages, and the group block turned out to be extremely useful in this regard. 
Their feedback was that using the block navigation it was not immediate to grasp what each group contained so they asked if it was possible to assign descriptive names to them (examples given were: "intro text", "main call to action", etc.).
Based on your doubt whether there would be a "use case for naming anything" I discussed it with them and it turned out that the other block where they saw a use for it (although it was "not so important as for groups" in their own words) was the blocks that added multimedia content (youtube videos etc.).
I hope this helps.

**Comment by kyle-charlton** [comment]
Are there any further discussions on implementing this feature?
The development team I work with  make heavy use of groups, columns and Media & Text blocks on many of our custom pages and having the ability to name any type of "Parent block"  would be a welcome navigation improvement.

We generally try to organize our pages by break up different sections of a page into its own groupings, so a page with say 5 sections (header, content, unique design elements) would have 5 groups created.

Seeing a list like the image below could be more useful with custom names for navigating. 

![image](https://user-images.githubusercontent.com/12102133/79368293-01803e80-7f04-11ea-80f9-0efd4d098928.png)

I also like the idea of having the name field appear in the "advanced" panel in the block inspector




> @mtias here is a quick mock-up to see if what you are thinking about:
> 
> ![group](https://user-images.githubusercontent.com/253067/61227109-91961b00-a71b-11e9-9ce5-1a02a34dce4c.png)
> 
> I actually quite like that as an option, but only if we also change reusable blocks to use that.

**Comment by djbakedpotato** [comment]
I too would like to see this feature 

in the meantime we are using this plugin:

https://wordpress.org/plugins/block-navigation/

![image](https://user-images.githubusercontent.com/62084865/81953624-85921880-95cd-11ea-94a9-57448cb1cd45.png)

**Comment by sophiegyo** [comment]
I am glad I found this feature request already open as I was about to open a similar one, I'd definitely be interesed in being able to name blocks - either by showing the id/anchor or with a separate name field. I was also thinking of suggesting the name field in the Advanced section, it's a great-to-have, not a must in my opinion. Reusable blocks already show their names/post titles (since they're a post type) in the list view, and I think it could be handy for managing pages with lots of parent blocks that have content nested in them.

**Comment by justintadlock** [comment]
Just came by to say I was looking for this too.  I tend to use the breadcrumbs for navigation, and find it pretty much impossible to figure out which group I'm looking for in a theme I'm working on.  Example:

> ... > Group > Group > Template Part Name > Group > Group > Group

At the very least, adding the `tagName` argument would help.  Like `Group <header>`, `Group <footer>`, and so on.  Named would be better though.

**Comment by mtias** [comment]
Related #16307

**Comment by talldan** [comment]
I'm going to close this one out as a superseded by https://github.com/WordPress/gutenberg/issues/33583
