### ISSUE TITLE
Install of GeoDirectory plugin will fail with Gutenberg active

### ISSUE THREAD

**Issue by TD-er** [WordPress/gutenberg#16306]
With Gutenberg activated, it is not possible to run the setup wizard of GeoDirectory plugin.

It is a clean install, with only Gutenberg active and GeoDirectory installed and activated.
Starting the GeoDirectory setup wizard will fail.

The logs (emailed to me, great feature :) ):
```
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 20 van het bestand /var/www/clients/client2/web6/web/wp-content/plugins/gutenberg/lib/widgets.php. Foutmelding: Uncaught Error: Call to a member function is_block_editor() on null in /var/www/clients/client2/web6/web/wp-content/plugins/gutenberg/lib/widgets.php:20
Stack trace:
#0 /var/www/clients/client2/web6/web/wp-content/plugins/gutenberg/lib/widgets.php(28): gutenberg_is_block_editor()
#1 /var/www/clients/client2/web6/web/wp-includes/class-wp-hook.php(286): gutenberg_block_editor_admin_print_styles('')
#2 /var/www/clients/client2/web6/web/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/clients/client2/web6/web/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /var/www/clients/client2/web6/web/wp-content/plugins/geodirectory/includes/admin/class-geodir-admin-setup-wizard.php(214): do_action('admin_print_sty...')
#5 /var/www/clients/client2/web6/web/wp-content/plugins/geodirectory/includes/admin/class-geodir-admin-setup-wizard.php(193): GeoDir_Admin_Setup_Wizard->setup_wizard_header()
#6 /var/www/clients/client2/web6/web/wp-includes/class-wp-hook.php(286): GeoDir_Admin_Setu
```

After deactivating the Gutenberg plugin, the GeoDirectory setup wizard does start.

Versions:
- Running Wordpress on Ubuntu 18.04.
- Browser: Chrome (latest version) on Windows
- Gutenberg 6.0.0
- GeoDirectory: 2.0.0.62
- WordPress 5.2.2
- Theme: Twenty Nineteen

**Comment by swissspidy** [comment]
Here's the relevant code in Gutenberg:

https://github.com/WordPress/gutenberg/blob/0719922928f9c7e8764e80d1ecf648b1ed43d711/lib/widgets.php#L13-L21

The necessary `null` check was just added in #16201, which should actually prevent this kind of error.

**Comment by noisysocks** [comment]
Closing this as looks like https://github.com/WordPress/gutenberg/pull/16201 fixed it.
