### ISSUE TITLE
Best approach for a plugin with multiple skins (factory and custom-made)

### ISSUE THREAD

**Issue by LuigiPulcini** [WordPress/gutenberg#16301]
Hi everyone!

I have already posted the same question in the plugin support forum last week.

I am updating my plugin WavePlayer to feature a Gutenberg block. WavePlayer is essentially an audio player with waveform display and playlist support.

My first approach was to use the ServerSideRender (especially because I am definitely not a wiz in React) and everything seems to be working as expected. Now, I am contemplating the possibility to render the block without relying on the server but I haven’t found the best solution for rendering custom skins created by the users.

In fact, the next update of my plugin will feature the capability of choosing the skin of the player, not only selecting among a factory set of skins included with the plugin but also allowing the user/developer to customize or design from scratch their own skins (stored in a template subfolder of their child theme).

Now, for the factory skins, I could easily create a component for each skin and let the block select the most appropriate component based on the user’s choice.

But what about the custom skins?
I am thinking of one of the following solutions:

1) creating a component for each factory skin, while keeping using the ServerSideRender component for the custom skins;

2) creating a component for each factory skin, while limiting the users to only customize the CSS styling of the factory skins instead of allowing them to design their own structure;

Do you think of any other approach? Any input or suggestion would be truly appreciated.

Thanks,
Luigi.

**Comment by youknowriad** [comment]
I'm not sure what a "skin" is in the context of your plugin. you could also offer JS apis for third-party skins to "register the component for these skins" or thing like that` `myPlygin.registerSkin( config )`.

Anyway, it seems like this question is more suited for Technical section of the support forum at https://wordpress.org/support/forum/wp-advanced/ or stackexchange https://wordpress.stackexchange.com/.
