### ISSUE TITLE
Show block ID attribute on navigator

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16307]
If a block has an ID / anchor set, it could be displayed in the navigator to make it easier to distinguish among blocks and to reference them:

![image](https://user-images.githubusercontent.com/548849/60195886-42577b80-983c-11e9-902d-9c12fa624b8c.png)

**Comment by draganescu** [comment]
Is is still useful in the context of @talldan 's work (#18132 , #19664) to improve what we show in the navigator instead of the block's name? The PR for this looks pretty advanced but got stopped for some reason, at @sarahmonster 's comment on the usefulness of the original issue.

**Comment by talldan** [comment]
Relabelling this based on that there's already a PR, and this comment on that PR:
https://github.com/WordPress/gutenberg/pull/16898#issuecomment-531884375

**Comment by paaljoachim** [comment]
Here is an associated/duplicate issue: https://github.com/WordPress/gutenberg/issues/16621

Both issues and the PR have stopped up.
