### ISSUE TITLE
Descriptions would be nice to explain extra plugins installed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16300]
If you use the plugin version you get the following on your install page:

![2019-06-26 at 13 58](https://user-images.githubusercontent.com/253067/60181960-44f5a900-981b-11e9-9a60-a1913317a372.png)

It could be good to explain a little what each is over have blank descriptions. For example see other plugins:

![2019-06-26 at 14 04](https://user-images.githubusercontent.com/253067/60182027-648cd180-981b-11e9-9b25-c4356fcee199.png)

**Comment by swissspidy** [comment]
Those are plugins that are installed during E2E tests. That's not something a user usually sees.

I don't think it's necessary to add description to testing plugins.

**Comment by karmatosed** [comment]
The thing is they are seen by some people. I think just a little description even if the same for each to say they are tests could be a great step to ensure everyone knows what they are.

**Comment by gziolo** [comment]
All plugins can be found in
https://github.com/WordPress/gutenberg/tree/master/packages/e2e-tests/plugins

It’s fine to include a generic description 👍

**Comment by mtias** [comment]
This seems very low priority.
