### ISSUE TITLE
Help: Server Render <InnerBlocks.Content /> in a dynamic block

### ISSUE THREAD

**Issue by afridley** [WordPress/gutenberg#16319]
I am trying to figure out how to access <InnerBlocks.Content /> from my dynamic block as I would in the save function.

Here is an example
```php
function register_dynamic_block() {

  if (!function_exists('register_block_type')) {
    return;
  }

  register_block_type('example/hero-block', array(
    'attributes' => array(
      'message' => array(
        'type' => 'html',
      ),
      'label' => array(
        'type' => 'html',
      ),
      'type' => array(
        'type' => 'string',
        'default' => 'default',
      ),
      'subtitleSwitch' => array(
        'type' => 'boolean',
        'default' => false,
      ),
      'subtitle' => array(
        'type' => 'html',
      ),
      'image' => array(
        'type' => 'string',
        'default' => null,
      ),
      'blockAlignment' => array(
        'type' => 'string',
        'default' => 'full',
      ),
    ),

    'render_callback' => __NAMESPACE__ . '\render_dynamic_block'
  ));
}

function render_dynamic_block($attributes) {
  $message = $attributes['message'];
  $label = $attributes['label'];
  $type = $attributes['type'];
  $subtitleSwitch = $attributes['subtitleSwitch'];
  $subtitle = $attributes['subtitle'];
  $image = $attributes['image'];
  $blockAlignment = $attributes['blockAlignment'];

  ob_start(); // Turn on output buffering

?>
  <div class="wp-block-hero-block <?php echo "align$blockAlignment" ?> <?php echo "type-$type" ?>">
    <div class="layer-container">
      <div class="flex-container">
        <div class="hero-label">
          <h2 class="hdg_4">
            <?php echo $label; ?>
          </h2>
        </div>
        <div class="hero-body">
          <h1>
            <?php echo $message; ?>
          </h1>
        </div>
        <div class="subtitle-body">
          NEED INNER BLOCK CONTENT
        </div>
      </div>
    </div>
    <?php if (isset($image)) {
      echo "<div class='bg-image'><img src='$image' alt='$image' /></div>";
    } ?>
  </div>
<?php

  $output = ob_get_contents(); // collect output
  ob_end_clean(); // Turn off ouput buffer

  return $output; // Print output
}
```

I have tried what seems to be suggested here https://github.com/WordPress/gutenberg/issues/6751
But it doesn't seem to work for dynamic blocks

```php
function register_dynamic_block() {

  if (!function_exists('register_block_type')) {
    return;
  }

  register_block_type('example/hero-block', array(
    'attributes' => array(
      'message' => array(
        'type' => 'html',
      ),
      'label' => array(
        'type' => 'html',
      ),
      'type' => array(
        'type' => 'string',
        'default' => 'default',
      ),
      'subtitleSwitch' => array(
        'type' => 'boolean',
        'default' => false,
      ),
      'subtitle' => array(
        'type' => 'html',
      ),
      'image' => array(
        'type' => 'string',
        'default' => null,
      ),
      'blockAlignment' => array(
        'type' => 'string',
        'default' => 'full',
      ),
    ),

    'render_callback' => __NAMESPACE__ . '\render_dynamic_block'
  ));
}

function render_dynamic_block($attributes, $content) {
  return $content
}
```

**Comment by afridley** [comment]
For anyone looking for a possible solution to this problem: It is possible to mix the two. This works for my situation as the reason I am using dynamic blocks is so I can make bug fixes without needing to update every single block. 

my solution was to not server render the inner blocks.
```js
save: props => {
  return <InnerBlocks.Content />
}
```

Then on the php side
```php
...
function render_dynamic_block($attributes, $content) {
  $message = $attributes['message'];
  $label = $attributes['label'];
  $type = $attributes['type'];
  $subtitleSwitch = $attributes['subtitleSwitch'];
  $subtitle = $attributes['subtitle'];
  $image = $attributes['image'];
  $blockAlignment = $attributes['blockAlignment'];

  ob_start(); // Turn on output buffering

?>
  <div class="wp-block-hero-block <?php echo "align$blockAlignment" ?> <?php echo "type-$type" ?>">
    <div class="layer-container">
      <div class="flex-container">
        <div class="hero-label">
          <h2 class="hdg_4">
            <?php echo $label; ?>
          </h2>
        </div>
        <div class="hero-body">
          <h1>
            <?php echo $message; ?>
          </h1>
        </div>
        <div class="subtitle-body">
          <?php echo $content ?>
        </div>
      </div>
    </div>
    <?php if (isset($image)) {
      echo "<div class='bg-image'><img src='$image' alt='$image' /></div>";
    } ?>
  </div>
<?php
  /* END HTML OUTPUT */

  $output = ob_get_contents(); // collect output
  ob_end_clean(); // Turn off ouput buffer

  return $output; // Print output
}
...
```

**Comment by Ishtiaque-Shaad** [comment]
I have done the same thing to solve my projects 
`	save: () => {
		return (
			<div>
				<InnerBlocks.Content />
			</div>
		);
	},`

and in PHP code just use the `$content` to access & display the inner blocks. But I am little confused about this procedure.

There should be some exact declaration or documentation "How to use InnerBlock in perfect way". 

[FYI, I don't know if the documentation about this already exists now. peace ... 🎉  ]

**Comment by BenceSzalai** [comment]
Only problem is that this outputs the raw markup of dynamic blocks.
If dynamic blocks should be allowed inside the InnerBlocks, echo `do_blocks($content)` instead of `$content`.

**Comment by danny-vanrooijen** [comment]
I am trying to do the same, except that I also want my InnerBlock to be a dynamic block. When you use a mix of PHP rendered `$content` and setting the `InnerBlock.Content` in your save function, the `$content` is displaying what is built by JS. How do I extend this so that the InnerBlock is also rendered dynamically?

**Comment by zurmoehle** [comment]
Hello, i'm using the `InnerBlock` to display Content in a StageBlock. The Save Function with the `InnerBlock.Content` works fine for me. So my Content is now visible in the Frontend.

My Problem now is if i reload the Backend the Error `This block contains unexpected or invalid content.` appears. The Validation of the save function gives me an empty content and the validation from the post gives me the right content i setup previously. Is there a way to prevent this?

**Comment by shelaine** [comment]
@zurmoehle - I realize this question is old and you proably already figured it out. But for anyone new coming along reading this thread.

The `This block contains unexpected or invalid content.` error when using `InnerBlock.Content` might stem from not importing `InnerBlocks` in your code. 

For example to use  `InnerBlock.Content`  in your save you need to also `import {  InnerBlocks } from '@wordpress/block-editor'`

**Comment by torsumkhan** [comment]
I have done the same, but I still dont see the Inner block content on my front end.
