### ISSUE TITLE
Publishing flow: consider including a "post preview" in pre-publish panel

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#16311]
I'm including this here for further discussion splintering off #7602. The suggestion was to add a "preview" section to help users feel confident that their post is ready to publish live. This could help users review the most critical details about their post (that often get automatically pushed to social media sites upon publishing) and thereby increase confidence in the publishing process.

Before:
![Pre-publish no tags](https://user-images.githubusercontent.com/376315/60201624-9d8b6d00-9840-11e9-9988-61f85cf150b9.png)

After:
![Pre-publish preview](https://user-images.githubusercontent.com/376315/60201055-56e94300-983f-11e9-9c09-90502f26920e.png)

Pros to this approach: 
- could potentially increase user confidence in publishing process
- aids users who are concerned about what their post might look like on social media

Cons:
- adds more noise to the interface
- might unfocus attention
- may not be a perfect match with what the post looks like on social media

I'm leaning toward keeping the pre-publish dialog super lightweight and focussed, especially since plugins may wind up extending this panel anyway—and if a post preview is something that users would find helpful, it may be better suited for a social media or marketing plugin to handle. 

That said, I thought it'd be worth opening an issue for discussion if we have any evidence that something like this would provide real user value and increase their confidence in the publishing process, so I'd appreciate other insights & thoughts here!

**Comment by afercia** [comment]
> I'm leaning toward keeping the pre-publish dialog super lightweight and focussed

I'd totally agree :)

**Comment by karmatosed** [comment]
> I'm leaning toward keeping the pre-publish dialog super lightweight and focussed

More agreeing! I think it was worth opening but this feels like a plugin territory to me if someone wants to explore.

**Comment by sarahmonster** [comment]
I agree with everyone who agrees with me! 😉 

Thanks for the feedback @afercia @karmatosed; I'm going to go ahead and close this issue and move forward with a simpler interface.
