### ISSUE TITLE
Add experiments settings page to the plugin

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16318]
Having a settings screen to enable experimental features could be good. This was discussed during WCEU contribution day and I have done 2 really rough starting mockups to begin the work on this.

First, there needs to be a link in the menu, I would suggest something like this (note that all copy needs working on in these examples):

![Menu](https://user-images.githubusercontent.com/253067/60212681-b6544c80-9859-11e9-8408-82340848bd82.png)

I chose the word 'experiments' to avoid going onto 2 lines, settings could also work.

A simple settings page would contain all the options, off by default:

<img width="806" alt="Settings page" src="https://user-images.githubusercontent.com/253067/60212710-c3713b80-9859-11e9-8a80-5bd5ae8a68ca.png">

What do people think? I would love specific feedback on the copy/ Style wise this does use the default wp-admin settings page which in this case probably makes sense to use over diverging.

**Comment by paaljoachim** [comment]
I think this is a very good idea Tammie! When experimental features are created a check box can easily be added into the Experiments screen to turn on the specific feature. It makes testing a lot easier as I would then mainly focus on specific experiment I just activated. I also find the wording clear and straightforward.

**Comment by kjellr** [comment]
This looks great. Would it be appropriate to include some sort of disclaimer about the experiments here? As in: They may have limited functionality, etc.

**Comment by richtabor** [comment]
Just a thought, but if something like #16401 was available, the settings could be placed right within the editor - instead of having another admin page. 🤔

**Comment by youknowriad** [comment]
@richtabor I think the issue, in that case, is that some of these experimental features go beyond the editor screen (widgets, customizer)

**Comment by richtabor** [comment]
> @richtabor I think the issue, in that case, is that some of these experimental features go beyond the editor screen (widgets, customizer)

Ah good point Riad. 👌

**Comment by noisysocks** [comment]
Cool idea! Should it be a user setting or a site setting?

**Comment by youknowriad** [comment]
I think a site setting makes more sense. What do you think?

**Comment by paaljoachim** [comment]
Actually could a site setting become a very early exploration of a global setting?

**Comment by mapk** [comment]
@karmatosed's mockups here work great to get this going. I believe the word "experiments" is a great indicator that this section is hairy. Some added text on the page to further explain this as @kjellr pointed out is always a safe bet too.

Let's start building this! 😄

**Comment by tellthemachines** [comment]
Hey @karmatosed should this page have a "save settings" button or should the settings automatically be saved on clicking the checkboxes?

**Comment by youknowriad** [comment]
> we now make them not available by default?

There's still the possibility to have an "upgrade" script explicitly adding the setting while by default when installing the plugin, it will be unchecked. But we still need to discuss the best default value. Being enabled by default might make sense.

**Comment by karmatosed** [comment]
@tellthemachines we should probably have 'save settings' as all other pages do. I wish we didn't have to :)

**Comment by tellthemachines** [comment]
@karmatosed it should be technically possible to not have the "save settings" button, the question is more should we stay consistent with the rest of wp-admin?

**Comment by karmatosed** [comment]
@tellthemachines thanks for the confirmation, I agree as other pages have it we should also. Do you want me to mock that up or are you ok just adding in?

**Comment by tellthemachines** [comment]
> @tellthemachines thanks for the confirmation, I agree as other pages have it we should also. Do you want me to mock that up or are you ok just adding in?

@karmatosed happy to add it in, the styles are already there. I'll let you know when it's ready for a review 😄

**Comment by karmatosed** [comment]
@tellthemachines thanks, that's great!

**Comment by tellthemachines** [comment]
The experiments settings page has been merged, so we can close this now!
