### ISSUE TITLE
How to get child block content as soon as it changes

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#16322]
I’m currently working on a contact form block with with the input fields as child blocks. Now, to check some values, I need to update the contact form block whenever a child block is getting updated.

I already had a similar problem in another block and could get it working in around 90 % just by using `withState`:

```
edit: withSelect( ( select, props ) => {
	// update values
} ) ( function( props ) {
	// the edit function
} )
```

Unfortunately, it doesn’t even work a little bit at this block and yes, I know that `withState` isn’t supposed to be working like that.

Is there any possibility to get noticed in a block as soon as a child block gets an updated value?

**Comment by jorgefilipecosta** [comment]
Hi @KittMedia the parent can have access to the attributes of the child by using the withSelect HOC to subscribe to the editor store.
First, the parent needs to know its child blocks.
That can be done using the getBlock function:
 var block = blockEditorSelect.getBlock( ownProps.clientId ); - block.innerBlocks, contains the child blocks of the parent.

Then we need to know the id of the child block we want to read the attributes. It can be the first child block, or more advanced e.g.: the first child block of a given type (it depends on your use case).
var childBlock = blockEditorSelect.getBlock( block.innerBlocks[ 0 ].clientId ); --  all the attributes of the first child will be available via `childBlock.attributes`.

I created a full sample for you that is available at https://gist.github.com/jorgefilipecosta/e4e4ee8da7983c9d8a84e00fc2dcf893.
When you add Test Parent block, the block updates when its own input field is updated but also when the child input field updates.
I hope you find this information useful if you need more information feel free to comment and we will look further into this issue.

**Comment by KittMedia** [comment]
Thank you for your answer, @jorgefilipecosta.

What you describe is nearly the exact same solution I’m currently using. Sorry if that was unclear in my question. However, in my case it doesn’t work that well because it’s not about updating input values but about changing toggles.

The `withState` doesn’t get fired every time I change a toggle. I created a video to demonstrate it:
https://youtu.be/0k8EyhOsFsM

In this case, the `console.log` fires on every `withState` of the form block. It iterates through each input block and gets the name attribute of every input block that has the `required` toggle enabled.

As you can see there, it updates less frequently than I actually change the values. This way, it could result in a form block without the actual values of the required fields.

Do you have any hint how to improve that? If you need to see the code for that, I can provide it. 🙂

**Comment by jorgefilipecosta** [comment]
Without having the code is hard to understand the potential problem, but I guess for a case like this withState should be avoid, ideally we retrieve the attributes of the childs using withSelect and we compute a new value based on the attributes, if the computation is expensive memoization should be considered, (react hooks make that simple, in that case we should use useSelect instead of withSelect). I currently withState is being used as a way to cache the value derived from the attributes and that value is not being updated every-time the child changes.

**Comment by KittMedia** [comment]
Maybe it helps if I attach the plugin here?

[rh-block-contact-form.zip](https://github.com/WordPress/gutenberg/files/3377213/rh-block-contact-form.zip)

If you need any further information, I will do my best to give it to you.
