### ISSUE TITLE
Full-width columns block is indented inside of standard and wide Group blocks. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16321]
**Describe the bug**

Full-Width columns blocks appear unintentionally indented on the left when they exist within a standard or wide-width Group blocks. 

They appear as intended when they exist within full-width Group blocks.

**To reproduce**
1. Insert a columns block within a Group block.
2. Set the Group block to either Standard or Wide width.
3. Set the columns block to wide width.

**Screenshots**

_Columns blocks inside of a standard-aligned Group block:_ 

<img width="624" alt="Screen Shot 2019-06-26 at 8 56 37 PM" src="https://user-images.githubusercontent.com/1202812/60225569-55c31080-9855-11e9-963e-18c891e200c7.png">

_Columns blocks inside of a wide-width Group block:_ 

<img width="711" alt="Screen Shot 2019-06-26 at 9 04 51 PM" src="https://user-images.githubusercontent.com/1202812/60225741-1648f400-9856-11e9-92c7-b1eee6406312.png">

**Screenshots (Expected Behavior)**

_Columns blocks inside of a standard-aligned Group block:_ 

<img width="624" alt="Screen Shot 2019-06-26 at 9 03 48 PM" src="https://user-images.githubusercontent.com/1202812/60225712-f285ae00-9855-11e9-982c-fd9e1868b611.png">

_Columns blocks inside of a wide-width Group block:_ 

<img width="706" alt="Screen Shot 2019-06-26 at 9 03 56 PM" src="https://user-images.githubusercontent.com/1202812/60225720-f5809e80-9855-11e9-8842-75f063d81ed7.png">

**Additional context**
- Gutenberg v6.0

**Comment by youknowriad** [comment]
Just tested in 2020. This seems fixed for me.
