### ISSUE TITLE
How to change or hide the Wordpress Animated Logo when loading a a post/page preview

### ISSUE THREAD

**Issue by leomuniz** [WordPress/gutenberg#16326]
Hi there!
I found some useful information about replacing or hiding the **Wordpress Animated Logo** when **loading** a post/page **preview** in these issues. But, although the filter **editor.PostPreview.interstitialMarkup** has an example to use, I couldn't make it probably due to my lack of experience with Gutenberg. So I would appreciate if someone can offer a more complete solution than only the JS part.

I created a very simple plugin with 2 files only, without React and using WP 5.0.4 to handle this:

my-plugin.php
```
<?php
/**
 * Plugin Name: My First Plugin
 * Plugin URI: http://www.mywebsite.com/my-first-plugin
 * Description: The very first plugin that I have ever created.
 * Version: 1.0
 * Author: Your Name
 * Author URI: http://www.mywebsite.com
 */

function enqueue_gutenberg_js() {
		wp_enqueue_script(
				'replace-animation-script',
				plugins_url( 'my-plugin.js', __FILE__ ),
				array( 'wp-element', 'wp-editor', 'wp-hooks' ),
				filemtime( plugin_dir_path( __FILE__ ) . '/my-plugin.js' )
		);
	}

 add_action( 'enqueue_block_editor_assets',  'enqueue_gutenberg_js' );
```

my-plugin.js
```
var customPreviewMessage = function() {
    return '<b>Post preview is being generated!</b>';
};

wp.hooks.addFilter( 'editor.PostPreview.interstitialMarkup', 'my-plugin/custom-preview-message', customPreviewMessage );
```

Of course, it's not working and I'm still seeing the default Wordpress logo animation with the same text below it (otherwise I wouldn't be here). But my JS file is loaded successfully when loading Gutenberg Editor (I also added a console.log('test'); after wp.hooks.addFilter and it worked). There is no JS error in console and neither in PHP log files. Does anyone know what I'm doing wrong? I can think about some possibilities like:

- Is the **enqueue_block_editor_message** the proper hook?
- Are *wp-element*, *wp-editor* and *wp-hooks* the needed dependencies?
- Is React needed somehow? Even with my JS code being executed with no errors?

These are related issues and documentation: 
- Pull thread of filter creation: https://github.com/WordPress/gutenberg/pull/12463
- https://developer.wordpress.org/block-editor/developers/filters/editor-filters/
- https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/filters/editor-filters.md
- Help request on how to hide the logo: https://github.com/WordPress/gutenberg/issues/12216
- Help request on how to replace the logo: https://github.com/WordPress/gutenberg/issues/12238

Thank you very much

**Comment by swissspidy** [comment]
I just ran this in the browser console:

```js
wp.hooks.addFilter( 'editor.PostPreview.interstitialMarkup', 'my-plugin/custom-preview-message', function() { return 'Hello World'; } );
```

And it worked as expected. So it's probably just a matter of the order in which things are executed.

> Is the `enqueue_block_editor_message` the proper hook?

I hope you mean `enqueue_block_editor_assets`? If so, yes.

> Are `wp-element`, `wp-editor` and `wp-hooks` the needed dependencies?

At first glance, yes. Perhaps you also need `wp-edit-post`.

> Is React needed somehow? Even with my JS code being executed with no errors?

No, `wp.element` does that for you.

**Comment by leomuniz** [comment]
Thank you, @swissspidy. 

I just tried to do the same (actually I already tried this before), in two different WP sites and it did not work. :(  Git below.

![wp-animated-logo](https://user-images.githubusercontent.com/4562945/60266509-168dd180-98e0-11e9-904f-a93ef7b2a4cc.gif)

I thought it could be related to the WP version. But I have 5.0.4 and in the pull thread there is a comment saying that feature was released in 5.0.2. 

Do you have any other idea what could be wrong?

**Comment by leomuniz** [comment]
> I hope you mean enqueue_block_editor_assets? If so, yes.
Yes, I mean ` enqueue_block_editor_assets`.

**Comment by swissspidy** [comment]
It might not be in WordPress 5.0.2. Please try updating WordPress / the Gutenberg plugin first.

**Comment by leomuniz** [comment]
Just updated the vesion to 5.2.2 and it worked! Thank you. Now I'm trying to discover on which verrsion this was released.

**Comment by vs999** [comment]
> Just updated the vesion to 5.2.2 and it worked! Thank you. Now I'm trying to discover on which version this was released.

Hi, could you share the correct code to make it work? I'm trying to remove the preload WP logo but I didn't menage to do it :(
