### ISSUE TITLE
To hide meta block(s) in certain post format?

### ISSUE THREAD

**Issue by yduke** [WordPress/gutenberg#16323]
As I followed in wordpress "Block Editor Handbook"  meta blocks,
I added a "meta block" to my theme, and it worked, but the block I add is an "audio file url" to replace the old meta box to talk to the custom field, it should be only appears when "audio" post format is selected, and hide when other post formats are selected.
My php goes like:

```
    function duke_blocks() {

    wp_register_script(
        'wb-blocks-js',
        get_template_directory_uri() . '/inc/meta-block.js',
        array( 'wp-blocks', 'wp-editor', 'wp-element','wp-components' )
    );
    register_block_type( 'dukeyin/audio-url', array(
        'editor_script' => 'wb-blocks-js',
    ) );

}
add_action( 'init', 'duke_blocks' );

function duke_register_block_meta() {

    register_meta( 'post', 'audio-url', array(
        'show_in_rest' => true,
        'single' => true,
        'type' => 'string',
        'object_subtype' => 'audio',
    ) );

}

add_action( 'init', 'duke_register_block_meta' );
```

and javascript goes 

```
( function( wp ) {
    var el = wp.element.createElement;
    var registerBlockType = wp.blocks.registerBlockType;
    var TextControl = wp.components.TextControl;

    registerBlockType( 'dukeyin/audio-url', {
    title: 'Audio file URL',
    icon: 'media-audio',
    category: 'layout',
    attributes: {
        blockValue: {
            type: 'string',
            source: 'meta',
            meta: 'audio-url',
        }
    },

    edit: function( props ) {
        var setAttributes = props.setAttributes;

        function updateBlockValue( blockValue ) {
            setAttributes({ blockValue });
        }

        return el(
           'div',
           { className: "audio-url" },
            el( 'h5',{}, 'URL to audio file:'),
            el (TextControl,
            {
                onChange: updateBlockValue,
                value: props.attributes. blockValue,
            })
        );
    },

    save: function( props ) {
         return null;
    },
    } );
} )( window.wp );
```

I've tried the jQuery way to crate an event on "select.components-select-control__input" change, but it didn't work cos there is no "selected" add to the sub options element, any better way to hide and show "meta-blocks" when post-format changes?

**Comment by Soean** [comment]
Only one approach, not a complete solution:
You can get the post format with `wp.data.select( 'core/editor' ).getEditedPostAttribute( 'format' )`
You can unregister a block with `wp.blocks.unregisterBlockType( 'dukeyin/audio-url' );`

**Comment by youknowriad** [comment]
You can also subscribe to data changes `wp.data.subscribe( () => { // do something } )`

With these three functions, you should be able to achieve a solution.
