### ISSUE TITLE
Block indication label goes over toolbar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16334]
The block indication label covers the toolbar, perhaps considering moving this to the right or iterating could avoid this?

![2019-06-27 at 19 11](https://user-images.githubusercontent.com/253067/60289967-8f585200-990f-11e9-9c9b-e72777eb8f6b.png)

**Comment by kjellr** [comment]
It'll be just a tiny bit better when #14961 lands: 

<img width="639" alt="Screen Shot 2019-06-27 at 2 25 17 PM" src="https://user-images.githubusercontent.com/1202812/60290801-8ce20200-98e7-11e9-9dda-49c23e37a66a.png">

... but that will also come with more problems: 

<img width="677" alt="Screen Shot 2019-06-27 at 2 27 18 PM" src="https://user-images.githubusercontent.com/1202812/60290879-b307a200-98e7-11e9-801f-2e7750646359.png">

In general, we've talked in other threads about [removing these breadcrumbs entirely](https://github.com/WordPress/gutenberg/issues/14095#issuecomment-468778570). I'm sort of leaning that towards, personally — I'm not convinced that knowing the type of block on hover is actually all that beneficial, especially as PRs like #14961 and #15537 make it easier to work within nested block situations.

**Comment by karmatosed** [comment]
> In general, we've talked in other threads about removing these breadcrumbs entirely.

If there isn't an option that doesn't have down-sides I do kind of agree with removing for now in light of those PRs.

**Comment by richtabor** [comment]
> In general, we've talked in other threads about [removing these breadcrumbs entirely](https://github.com/WordPress/gutenberg/issues/14095#issuecomment-468778570).

I'm also for removing these breadcrumbs.

**Comment by chrisvanpatten** [comment]
I was pro-remove, but I've started work on a set of custom blocks for an internal project where the blocks are all very similar in appearance. For this case, having the labels has been truly invaluable, and I think removing them would be a mistake.

**Comment by karmatosed** [comment]
@chrisvanpatten How common is that project? I am not saying this isn't a use case, but I really wonder if most find it a problem that another solution wouldn't be better than one that for most causes issues.

**Comment by kjellr** [comment]
I opened a quick PR to try this out: https://github.com/WordPress/gutenberg/pull/16506

**Comment by bigvibes909** [comment]
Please, please get rid of these labels. 

As an editor I work with WordPress on multiple sites all day and I can't tell you how much lost productivity I've had to deal with due to these labels. This issue I'm sure is one of the reasons people swear at Gutenberg since it actually makes using WordPress unusable.

I'd think just about everyone would agree that just being able to simply use the editor is the most important thing rather than having all these minimally used bells and whistles.

**Comment by ZebulanStanphill** [comment]
@bigvibes909 There is a pull request which, if merged, will remove the hover indicators entirely: #18862.

**Comment by ZebulanStanphill** [comment]
Closing since #18862 has been merged.
