### ISSUE TITLE
Feedback - Classic Text Editor

### ISSUE THREAD

**Issue by mssbee** [WordPress/gutenberg#1634]
A couple of things for the classic text editor: change font color, add a link and add media. Why not put those basics into that editor. It would give me and I would think most other folks most the used items from the editor we are use to now. It would really help those of us who past copy from clients. In most cases we don't need to use separate blocks for them. In fact creating those blocks would increase time spent - not a bonus point.

**Comment by jasmussen** [comment]
Thank you for the feedback!

Font color and link options are both there:

![screen shot 2017-08-18 at 11 41 58](https://user-images.githubusercontent.com/1204802/29453546-4b9276a2-840a-11e7-8e15-d58c455eaef0.png)

They may not have been when you reported this ticket.

With regards to adding media, for now we are looking at a way to insert media inline, to both paragraph blocks, and to the classic text block. See #2043

Closing now as partially addressed, partially ticketed elsewhere. Thanks!
