### ISSUE TITLE
Reusable blocks can no longer be selected

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#16359]
Reusable blocks can no longer be selected. I can't insert reusable blocks. Since the last Gutenberg update this is no longer possible.

**To reproduce**
1. Go to 'Post'
2. Click on 'Reusable blocks'

**Expected behavior**
I would like to continue using the Reusable blocks.

**Screenshots**
Interestingly, 18 are displayed in the counter. But I can't choose:
![Screenshot_3](https://user-images.githubusercontent.com/9355398/60383357-cc3b5a80-9a6f-11e9-973b-10eaabec811b.png)

![Screenshot_4](https://user-images.githubusercontent.com/9355398/60383390-394ef000-9a70-11e9-9051-b8f170b7e313.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 75.0.3770.100 (Offizieller Build) (64-Bit)

**Additional context**
- Gutenberg 6.0

**Comment by swissspidy** [comment]
Does it work when you disable your multilingual plugin? That might cause issues.

**Comment by SchneiderSam** [comment]
After deactivate and activate WPML again, the Problem is solved. So WPML was the problem. Thank you @swissspidy !!

See: https://wpml.org/de/forums/topic/reusable-blocks-can-no-longer-be-selected/
