### ISSUE TITLE
Image in columns

### ISSUE THREAD

**Issue by vfxdude** [WordPress/gutenberg#16361]
When resizing a column (core/columns block) with an image it sometimes causes half of the page not to render. This seems to be a Chromium bug, since it only happens in chromium browsers. 

I'm not saying you should fix a Chromium bug, but there might be a workaround. This seems to be related to the auto height set to the image, because the problem goes away when setting a px height to the image in Chrome Developer Tools.

**To reproduce**
1. Add a columns block and add an image into the first column (or any other)
2. In the column settings for that column change the width to see if parts of the page disappears (clicking into the with width input and using the up and down arrows on the keyboard might be best approach).

**Expected behavior**
Expect the whole page to render.

**Screenshots**
![chrome_2019-06-29_17-02-35](https://user-images.githubusercontent.com/20110677/60386156-d3736000-9a91-11e9-8439-ddc8fa6e1c8e.jpg)
![chrome_2019-06-29_17-02-18](https://user-images.githubusercontent.com/20110677/60386157-d40bf680-9a91-11e9-8b44-c27b1416ceab.jpg)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, Vivaldi, Brave (Chromium based browsers)

**Additional context**
- Gutenberg 6.0
- All other plugins deactivated.

**Comment by GlennMartin1** [comment]
+1 

Same issue using Chrome for Windows.

**Comment by karmatosed** [comment]
I find myself unable to recreate this using a mac and Chrome. I wonder if this is now resolved. Would you be able to check again @GlennMartin1 or @vfxdude, just to be sure?

**Comment by GlennMartin1** [comment]
I have not seen this issue reappear since 6.1.

It may be resolved.

**Comment by karmatosed** [comment]
Thanks, I am going to close this then as we can always reopen.
