### ISSUE TITLE
Extension to show blocks time based (date time from / till)

### ISSUE THREAD

**Issue by hannesdorn** [WordPress/gutenberg#16363]
Is there an extension that allows you to schedule an arbitrary block?
I would like to be able to specify one from and / or one to date (date + time).

It exits for pages or posts, but not on block level.

I would like to show on the homepage a holiday notice, which automatically disappears after the holiday. Yes, I know, I could do that with JavaScript, but I need it for end users in the backend.

**Comment by draganescu** [comment]
Hey @hannesdorn as cool as it may be, this sounds a lot like a custom block, not like a core feature. Do you have any reason why this should be supported on every block or be a core API?
