### ISSUE TITLE
Media & Text block: wide alignment is not being passed to `render_block` filter

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#16365]
**Describe the bug**
Looking at the block attributes passed to [`render_block` filter](https://developer.wordpress.org/reference/hooks/render_block/), the `align` attribute is not set even if the wide alignment is chosen in the editor for Media & Text block.

Maybe caused by wide alignment being a default value for Media & Text block?

**To reproduce**
1. Insert a Media & Text block into post content, set an image and text. Do not tweak any other options - the block should have wide alignment applied by default.
2. Publish the post.
3. Check the output of the `$block` parameter of [`render_block` filter](https://developer.wordpress.org/reference/hooks/render_block/) (in front-end). You can see there is no `align` attribute under `$block['attrs']`.

**Expected behavior**
Alignment value should be passed to `render_block` filter even if the block uses a specific alignment value by default. (Actually, all default values of block attributes should be passed into `render_block` filter.)

**Additional context**
- Tested on WP 5.2.2

**Comment by jorgefilipecosta** [comment]
Hi @webmandesign, thank you for reporting this issue. The issue is happening because wide align is the default align attribute for media & text bloc. The problem is common to all default attributes in every block.
Previously default attributes were not passed to render_block because the server may have not been aware of them. With the block.json work maybe we can now pass default values when they are known on the server. Any thoughts on this @gziolo?

**Comment by webmandesign** [comment]
Thanks for the info @jorgefilipecosta 
I thought it could be the case. Would be really great if default atts could be passed to the `render_block` filter. They are significant part of the block appearance.

**Comment by gziolo** [comment]
> Previously default attributes were not passed to render_block because the server may have not been aware of them. With the block.json work maybe we can now pass default values when they are known on the server. Any thoughts on this @gziolo?

The long term idea is to register all core blocks on the server using `block.json`. It will solve the issue for all the regular attributes but not necessarily for `align` which is kind of special when used through `supports: align` construct. We will still have to develop the compatibility layer which will inject this attribute on the server for all those blocks which will enable `support: align`.

**Comment by carolinan** [comment]
Hi @webmandesign I am not able to reproduce this with WP 6.2.2 and Gutenberg trunk, is this still an issue?
The block is not wide by default anymore, but when an alignment is used, I see the attribute when I dump the result of the render_block.

**Comment by webmandesign** [comment]
Hi @carolinan I guess this is resolved now after those years ;) You can close the issue.
