### ISSUE TITLE
Selection lost when right-clicking on multiple blocks

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#16376]
**Describe the bug**

You can't right-click on multiple blocks to copy them.

**To reproduce**

1. Highlight multiple blocks
2. Right-click on one of them

**Expected behavior**

All blocks should remain highlighted, and selecting Copy from the context menu should copy all blocks.

**Actual behavior**

The selection is reset to only the block that was clicked on, and copying only copies that block.

Related #7283 , #6128

**Comment by ellatrix** [comment]
@iandunn I cannot reproduce this with `master`. Could you test again? Perhaps it's fixed with the new multi selection behaviour in `master`.

**Comment by iandunn** [comment]
Yeah, it's working for me with cc44f8b3aad83f9b5c8564739d95d734d9abb440, thanks!
