### ISSUE TITLE
Date/Time picker hour/minute fields reversed in RTL languages

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#16373]
**Describe the bug**
When editing a post date in the "Status and Visibility" panel, the hour and minute fields are swapped. 

Note this also affects the classic editor as well as the _quick edit_ feature of the post list screen, see https://core.trac.wordpress.org/ticket/30506.

**To reproduce**
1. Edit a post in an RTL language.
2. Edit the post publish time/date.
3. Note the hour/minute fields are reversed. 

**Expected behavior**
The hour field should be to the left of the minute field, eg. HOUR:MINUTE even in RTL languages.

**Screenshots**
Post edited at 8:20 am, viewed with my profile set to use hebrew - note the minutes are incorrectly to the left of the hours.

![image](https://user-images.githubusercontent.com/2676022/60445675-e8a8d580-9bdc-11e9-898a-f27b3afa1004.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version Beta

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ramiy** [comment]
@adamsilverstein The [Trac ticket](https://core.trac.wordpress.org/ticket/30506.) was fixed.

As for Gutenberg RTL issue, you should know that in many languages the use of AM/PM is not common. In Hebrew we use 24 hours system (we prefer 17:00 over 5:00PM).

**Comment by adamsilverstein** [comment]
> As for Gutenberg RTL issue, you should know that in many languages the use of AM/PM is not common. In Hebrew we use 24 hours system (we prefer 17:00 over 5:00PM).

@ramiy thanks for the context. this PR only addresses the ordering of the minute and hour fields keeping them in a left to right visual order, eg HH::MM regardless of language - does that part seem correct?
