### ISSUE TITLE
Standardize SlotFills that use <PanelBody/> to inherit icon property from registerPlugin

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#16379]
Based on the work done in #13361, it now seems to make sense that any SlotFill that uses `<PanelBody/>` that is added by via `registerPlugin()` should be able to inherit the icon property.

SlotFills:

PluginPrePublishPanel: #16378 
PluginPostPublishPanel: #16383

**Comment by gziolo** [comment]
Both linked PRs were landed a while ago. This can be closed 🎉
