### ISSUE TITLE
Bottom Metaboxes overlap the post editor content in Chrome 76

### ISSUE THREAD

**Issue by xenobytezero** [WordPress/gutenberg#16382]
**Describe the bug**
If there are metaboxes docked in the bottom dock area of the editor, and the editor content is larger than the window, the bottom metaboxes will sit at the inital "bottom" position and overlap the post content when scrolling.

**To reproduce**
1. Go to Gutenberg Demo Page
2. Scroll page down.

**Expected behavior**
The bottom metaboxes should always be at the bottom of the page under the content.

**Screenshots**
![](https://user-images.githubusercontent.com/5059527/60471538-00c03980-9c5d-11e9-8344-c073ea279990.png)

**Desktop (please complete the following information):**
 - OS: Win10 Pro 1903
 - Browser: Chrome 76.0.3809.46 (Not Reproducable on FF 67.0.4)
 - Wordpress 5.2.2
 - Gutenberg 6.0.0

**Additional context**

I raised an issue very similar to this last year (#5653), and the "fix" included in that post seems to work, however that issue was due to a misbehaving plugin. I can now repro this with only Gutenberg, ACF 5 and Timber installed (the essentials for my theme).

The issue appears to be Chrome only, cannot reproduce this issue in Firefox.

The issue can be worked around by adding the following to a theme.

```php
add_action('admin_head', function() {
    echo '<style> div.edit-post-visual-editor.editor-styles-wrapper > .editor-writing-flow { height: unset; } </style>';
});
```

**Comment by stiucsib86** [comment]
Seems like you are using Chrome Beta. 

Chrome Beta 76.0.3809.46

**Comment by stiucsib86** [comment]
Seems like you are using Chrome Beta. I'm not able to reproduce this in Chrome Stable (75.0.3770.100). Only in Chrome Beta (76.0.3809.46) and Chrome Canary (77.0.3838.0).

And this looks like a Chrome issue. Maybe file a bug report in chromium?

**Comment by xenobytezero** [comment]
Chrome 76 is becoming stable at the end of this month (July 30th) so this might become a problem for more people when this happens. 

I'm unclear if this is actually a Chrome regression or a Gutenberg regression, since the Chrome behaviour seems correct based on the CSS of the edit page?

**Comment by kieusonlam** [comment]
Any status on this, this is kind of anoying.

**Comment by xenobytezero** [comment]
Chrome 76 has been patched a few times, the issue is still present, and 76 goes stable in 6 days.

**Comment by xenobytezero** [comment]
The final version of Chrome 76 Stable (76.0.3809.87) appears to no longer have the issue. Can anyone else confirm?

**Comment by karma007** [comment]
I have the same issue on chrome 64bits, will try now to upgrade.

**Comment by karma007** [comment]
Problem was in Version 76.0.3809.62 (Build officiel) beta (64 bits)
Problem solved in Version 76.0.3809.87 (Build officiel) beta (64 bits)
:)

**Comment by archduck** [comment]
I'm having the same issue on Brave Browser 76.0.67.112. `.block-editor-writing-flow` has a rule setting its height set to 100% ([GitHub link to rule](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/writing-flow/style.scss)); unsetting that rule restores the proper content flow.

Couldn't reproduce in Chrome, Opera, or Firefox, but confirmed with a clean Brave user profile.

**Comment by archduck** [comment]
![2019-08-05-191731_1600x900_scrot](https://user-images.githubusercontent.com/51252802/62504458-dad70900-b7b5-11e9-8d2b-ae980333345e.png)

**Comment by karma007** [comment]
Hello, same bug again, with update chrome 77.0.3865.70 (Build officiel) beta (64 bits)

**Comment by forkless** [comment]
And the same for Version 77.0.3865.75 (Official Build) (64-bit) (Yes, I realize it's a minor release change from the previous comment.

**Comment by mazzopalazzo** [comment]
Same experience here. Version 77.0.3865.75 (Official Build) beta (64-bit)

**Comment by youknowriad** [comment]
Just took this for a spin and it seems that I'm not able to reproduce this anymore.
