### ISSUE TITLE
Saving needs to cancel on error (ex. 500 or 504)

### ISSUE THREAD

**Issue by constip** [WordPress/gutenberg#16386]
If the server has a problem while saving and returns for example a 503, Gutenberg won't allow me to try and save again, the button is just inactive.

Autosaving is still running in the background, but Gutenberg neither tries to save again nor let's me manually do it. The problem is probably an uncaught promise (see screenshot).

![gutenberg_error](https://user-images.githubusercontent.com/12857972/60493575-5fad9f00-9cad-11e9-8a6f-35ac02f68fd3.png)

**Comment by manuel-84** [comment]
Same error happens when I have activated some plugins (like ACF or All in one SEO) that adds custom metaboxes into pages

**Comment by noisysocks** [comment]
Hi @constip, are you still experiencing this issue?

**Comment by constip** [comment]
Haven't used WordPress for a long timeOn 16 Apr 2020 7:13 am, Robert Anderson <notifications@github.com> wrote:
Hi @constip, are you still experiencing this issue?
