### ISSUE TITLE
First 2 characters in Paragraph, Heading and Verse blocks disappear on IE

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#16388]
**Describe the bug**
On Internet Explorer 11, when writing in Paragraph, Heading or Verse blocks, the first 2 characters typed don't appear. If `Delete` key is pressed before entering any text, then all characters appear normally. (This is `Delete`, not `Backspace`.)
This does not happen on all rich text fields; Quote, Pullquote, Code, List and Table work as expected.

**To reproduce**
1. On IE, add new post.
2. Add a paragraph block and start typing.
3. Verify that first two characters did not appear.
4. Add another paragraph, press `Delete` and then start typing.
5. Verify that characters now appear normally.

**Expected behavior**
Expected all characters to appear when typing.

**Desktop (please complete the following information):**
 - OS: Windows 7 and Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Additional context**

Using up-to-date master branch. I checked that this issue is reproducible as far back as version 5.8 of Gutenberg, but didn't manage to test any further back than that.

**Comment by youknowriad** [comment]
Is this still happening? Seems pretty serious if it's still the case.

**Comment by tellthemachines** [comment]
I can no longer reproduce this as of 6.9.0. However, as of the lastest master, the editor is completely broken in IE: https://github.com/WordPress/gutenberg/issues/18719
