### ISSUE TITLE
Block Library: Columns: Improve template picker UI for large viewports

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#16394]
**Describe the bug**
The inner blocks template picker needs improved 

**To reproduce**
1. Install and activate Gutenberg 6.0
2. Add a new page
3. Add a Columns block
4. View from a wide viewport
5. See issue

**Expected behavior**
Perhaps the buttons are center aligned or grow with the width of the placeholder/picker (or both).

**Screenshots**
<img width="1392" alt="Screen Shot 2019-07-02 at 10 21 34 AM" src="https://user-images.githubusercontent.com/1813435/60520347-398afd80-9cb3-11e9-9b4c-c03aad587249.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 12.1.1

**Additional context**
- Gutenberg 6.0

**Comment by kjellr** [comment]
Good catch! I didn't realize it at the time, but I think I took care of this yesterday in #16371. 

![Screen Shot 2019-07-02 at 4 06 31 PM](https://user-images.githubusercontent.com/1202812/60543080-6951f980-9ce3-11e9-82bd-9c139617d09c.png)
