### ISSUE TITLE
Page which is used for posts uses classic editor

### ISSUE THREAD

**Issue by Horttcore** [WordPress/gutenberg#16399]
**Describe the bug**

**To reproduce**
* Set a page as "page_for_posts"
* Edit the page
* edit-post.php is in classic mode

**Expected behavior**
It should be possible to enter content for this page.
With a notice, that this page is selected as page_for_posts.
And the theme might not use the content

**Comment by swissspidy** [comment]
Yeah the block editor currently doesn't support editing a post without the content area.  IIRC there should be a "Posts Page" block first before that makes sense.

Core tickets:

https://core.trac.wordpress.org/ticket/45537
https://core.trac.wordpress.org/ticket/45263

**Comment by mtias** [comment]
Closing based on the above tickets. With the site editor the templates that holds the blog will be editable in blocks.
