### ISSUE TITLE
Add functionality for plugins to add options to the OptionsModal

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#16401]
**Is your feature request related to a problem? Please describe.**
It would be quite useful if there was a singular place for plugins to append on/off options within the OptionsModal. Currently, each plugin with settings of some sort has to either create a separate sidebar/modal for their controls, or simply not provide any settings. 

A number of settings modals is quite heavy-handed UX, and the alternative of not providing settings limits the flexibility of Gutenberg/WordPress that we all have come to appreciate.

**Describe the solution you'd like**
Plugins that deploy a number of enhancements could have options listed within the OptionsModal, instead of building out another modal just for their plugin. This is similar to how iOS has a number of app settings in one familiar location, the Settings app.

For example, a real-world scenario would be in CoBlocks, where we're considering adding an option to remove more advanced controls, to provide a simpler interface for folks (or clients) that don't want or need a high level of flexibility that CoBlocks currently offers.

**Describe alternatives you've considered**
Making a separate plugin/modal for options. It's not awesome and soon enough most block plugins will have their own options modal, likely consisting of their own flavor of UI/X. This would lead to a fragmented experience whereas a simple way to add to the OptionsModal would limit that fragmentation quite a bit.

**Screenshot**
<img width="967" alt="Screen Shot 2019-07-02 at 3 34 41 PM" src="https://user-images.githubusercontent.com/1813435/60541167-f8a8de00-9cde-11e9-9faf-d835e14aa720.png">

**Comment by klihelp** [comment]
Thank you, good idea.

**Comment by jordesign** [comment]
With https://github.com/WordPress/gutenberg/pull/33774 merged - is this something that could be looked at now?

**Comment by skorasaurus** [comment]
I think this also can be implemented with the preferences package now available https://github.com/WordPress/gutenberg/blob/trunk/packages/preferences/README.md

@richtabor Please reopen if you have questions.
