### ISSUE TITLE
List block: Add keyboard support for list indenting and outdenting

### ISSUE THREAD

**Issue by DevinWalker** [WordPress/gutenberg#1640]
## Issue Overview

Currently when using the list block element you cannot _indent_ lists using the keyboard shortcut (`⌘` + `]`) or `tab`. As well, you can not easily outdent using (`⌘`+ `[`) or (`shift` + `tab`). This means increased time to make lists that are more than one hierarchy. 

![2017-07-01_16-14-59](https://user-images.githubusercontent.com/1571635/27766124-968b70d8-5e7a-11e7-9bf3-5ca2d584d2f8.png)

I believe adding this would help improve the usability. Currently you can use (`⌘` + `b`) to bold and same for italics, why not also for list indenting? 

**Notes:**
This functionality is referenced here: https://github.com/WordPress/gutenberg/issues/1552

**Comment by afercia** [comment]
Worth noting using the Tab key for indentation breaks keyboard navigation through blocks.

**Comment by DevinWalker** [comment]
Noted. But tabbing is not really working as currently should for all blocks currently:

![2017-07-02_11-13-49](https://user-images.githubusercontent.com/1571635/27772445-cbaada0e-5f17-11e7-8564-cc9521593316.gif)

I would prefer (⌘+ [) rather than the tabbing for indenting lists.

**Comment by EphoxJames** [comment]
One other thing that needs to be considered is that '[' and ']' are not on all keyboards. I'm told that the locals 'fr', 'nl', 'sv', 'ru', 'de', 'es' and 'it' do not have those keys. Apparently on textbox.io the square brackets, "meta+]" for indent and "meta+[" for outdent, are used on most locales and "meta+m" / "meta+shift+m" is used for the ones which don't have the square brackets.

I will put in a pull request with those key bindings.

**Comment by afercia** [comment]
Right, for example on an Italian keyboard layout `[` and `]` can be typed only pressing Alt+è and Alt++.
