### ISSUE TITLE
Columns block unusable on Internet Explorer

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#16403]
**Describe the bug**

On IE 11, it is not possible to add content to a Columns block and existing Columns blocks  overlay content below them.

**To reproduce**
1. On IE, add new post or edit existing post with a Columns block.
2. Try to click on the buttons to add a new block inside each of the columns.
3. Verify new blocks cannot be added inside columns.
4. Add some content, such as a paragraph, below the Columns block.
5. Verify that Columns block is displaying over the content below it.

**Expected behavior**
Expected to be able to add blocks to the columns inside the Columns block and not to have Columns block overlaying content below it.

**Screenshots**

<img width="1048" alt="Screen Shot 2019-07-02 at 3 55 35 pm" src="https://user-images.githubusercontent.com/8096000/60567526-a71b5480-9dad-11e9-8161-85f4cd29256c.png">

**Desktop (please complete the following information):**
 - OS: Windows 7 and Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by paaljoachim** [comment]
Hey Isabel. Is this issue still relevant?

**Comment by tellthemachines** [comment]
Hi Paal, I just checked on IE11/Windows 10 and cannot reproduce it any longer. Closing.
