### ISSUE TITLE
Page Break Block: should only be insertable at root level

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#16411]
**Describe the bug**

I can insert page breaks inside e.g. a column block. This should not be possible, as it will result in invalid HTML when the content is split into multiple pieces.

I think the same can be said about the More block.

**To reproduce**
Create a column block or any block that allows nesting, and insert a page break.

**Expected behavior**
Shouldn't be possible.

**Comment by HardeepAsrani** [comment]
Like we allow `parent` block attribute to allow child blocks to only be inserted in a particular section, we can maybe provide a parent of `root` or `editor` to allow this behavior, else maybe something in `support` attribute?

**Comment by HardeepAsrani** [comment]
This will also solve an issue with rested blocks behaving weird when Read More block is used inside: https://github.com/Codeinwp/gutenberg-blocks/issues/127

**Comment by glendaviesnz** [comment]
Have tried a very simplistic approach to what @HardeepAsrani suggested at #18260. It works and doesn't seem to break anything, but I need to do much more digging and testing to get a better understanding of what cases will return a parentName of null, in case it isn't only root level blocks that will do this - just noting here in case my explorations are helpful to others, rather than as a suggested solution :-)

**Comment by glendaviesnz** [comment]
I have done some more testing with #18260, and it seems to work, but as mentioned on the PR I am sure I am overlooking something obvious :-)

**Comment by glendaviesnz** [comment]
@ellatrix - a couple of people have tested my suggested fix for this at #18260 - would be interested to know if you think this is an effective solution, or not, when you get a moment.

**Comment by Soean** [comment]
#18260 is merged, so we can close this issue, right?

**Comment by glendaviesnz** [comment]
> #18260 is merged, so we can close this issue, right?

Yes, should have closed it when that was merged.

**Comment by CreativeDive** [comment]
@glendaviesnz @ellatrix I tested this behavior with WP 6.2 and Gutenberg 15.5.0 and it no longer works. If the block has "`core/post-content`" set in the "`parent`" attribute in `block.json`, the block can be grouped. But that shouldn't be possible.

I have other custom blocks that are restricted to the root level of the editor, but the options to group these blocks are available. But that shouldn't be possible.

It would be nice if it works as expected again.

**Comment by CreativeDive** [comment]
@glendaviesnz @ellatrix It seems it's handled here:

https://github.com/WordPress/gutenberg/blob/a43afc673255965d919803cb32923a82855c1de4/packages/block-editor/src/store/selectors.js#L1511-L1525

I've made a simple test:

```javascript
blockTypeParent = blockType.parent !== undefined ? blockType.parent : null;

if( blockTypeParent ) {
    if( blockTypeParent.includes('core/post-content') ) {
        return false;
    }
}
```

In any case, a block has `core/post-content` defined in `parent`, my test comes up with `return false;`, which should disable the canInsert possibility. But it's still possible. Can someone help me to find the reason why it stopped working?

It used to work, but not anymore.

**Comment by CreativeDive** [comment]
Created a new issue https://github.com/WordPress/gutenberg/issues/49662
