### ISSUE TITLE
Move permalink control to sidebar once post title is a block

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#16412]
**Is your feature request related to a problem? Please describe.**

The permalink control on the post title becomes unusable at high zoom levels:

<img width="1195" alt="59984277-a4ad5200-966b-11e9-969d-5b1bcfd0f698" src="https://user-images.githubusercontent.com/8096000/60638795-23bc3a80-9e63-11e9-89f7-80ebc8863d50.png">

Overall it makes semantic sense to have this feature in the sidebar instead of directly attached to the component, and it makes it easier to use on small screens or at high zoom levels.

**Describe the solution you'd like**

In #16277 it was suggested that the permalink control be moved into the sidebar. This is dependent on the post title component being a block in its own right, approaches to which are being discussed in #16281 

**Describe alternatives you've considered**

The fix for the immediate accessibility problem is already in #16277. 
However, that doesn't solve the wider problem of where it makes more sense to attach that control.

**Comment by Soean** [comment]
The permalink was removed from the title in #21099. Now it's only in the sidebar.
