### ISSUE TITLE
Date for non AM/PM countries

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#16414]
Hi, 

A little graphic bug:

Here is the date picker in a standard english WordPress install: 

![capture 2019-07-04 à 09 59 44](https://user-images.githubusercontent.com/1785489/60650194-f44a0580-9e43-11e9-9032-352f9771764a.jpg)

But then, in french (where am/pm) doesn't apply:

![capture 2019-07-04 à 09 59 09](https://user-images.githubusercontent.com/1785489/60650210-fca24080-9e43-11e9-976c-746cb1428e4c.jpg)

The button are still showing, but are empty. They should be removed

See also : #15654

**Comment by swissspidy** [comment]
@maximebj What makes this different from #15654? As for as I can see, the PR attached to it (#15757) solves the problem with AM/PM nicely.

**Comment by maximebj** [comment]
I was not sure it was the same issue. I'm closing it thanks.
