### ISSUE TITLE
Rest API Exposure

### ISSUE THREAD

**Issue by CHEWX** [WordPress/gutenberg#16422]
**Describe the bug**
Using core blocks such as `core/image`, firstly this is not exposed to the Rest API. So If I was to expose using `parse_blocks()` and `rest_prepare_cpt_project` there is no way to get the caption?

**Expected behavior**
To have access to captions as an attribute like images.

**Screenshots**
```
Array
(
    [blockName] => core/image
    [attrs] => Array
        (
            [id] => 16
        )

    [innerBlocks] => Array
        (
        )

    [innerHTML] => 
<figure class="wp-block-image"><img src="http://wordpress.test/wp-content/uploads/2019/07/image-1-1024x730.jpg" alt="" class="wp-image-16"/><figcaption>This is a caption</figcaption></figure>

    [innerContent] => Array
        (
            [0] => 
<figure class="wp-block-image"><img src="http://wordpress.test/wp-content/uploads/2019/07/image-1-1024x730.jpg" alt="" class="wp-image-16"/><figcaption>This is a caption</figcaption></figure>

        )

)
```

**Desktop (please complete the following information):**
All.

**Smartphone (please complete the following information):**
All.

**Comment by skorasaurus** [comment]
this is being fulfilled in https://github.com/WordPress/gutenberg/pull/2649

**Comment by mtias** [comment]
Tracked in https://core.trac.wordpress.org/ticket/53603
