### ISSUE TITLE
Able to replace photos in Gallery block

### ISSUE THREAD

**Issue by reginabally** [WordPress/gutenberg#16426]
**Is your feature request related to a problem? Please describe.**

Currently, when we want to replace a photo in a Gallery block, like replacing photo in the 3rd position with a new photo, we have to:

1. Unselect the old photo
2. Upload the new photo
3. Rearrange the new photo to the 3rd position

**Describe the solution you'd like**

It’ll be great if we can click on the photo that we want to replace, choose a new photo and the new photo got immediately replaced on the same position of the old photo.

**Comment by mapk** [comment]
As mentioned in my [comment over here](https://github.com/WordPress/gutenberg/issues/10057#issuecomment-569368309), the idea is to enable the Gallery block so that it uses nested Image blocks. When this happens, it should resolve this issue because Image blocks already allow this.

**Comment by simison** [comment]
>the idea is to enable the Gallery block so that it uses nested Image blocks

@mapk That might take a while to happen. 

What do you think if we'd have in interim something like this:

<img width="337" alt="Screenshot 2020-03-12 at 22 20 14" src="https://user-images.githubusercontent.com/87168/76565504-62ef6080-64b3-11ea-8988-1b3b0d2d7bab.png">
or
<img width="336" alt="Screenshot 2020-03-12 at 22 16 26" src="https://user-images.githubusercontent.com/87168/76565507-64b92400-64b3-11ea-9f8c-8241ee7e8d9a.png">

**Comment by mapk** [comment]
@simison, this is definitely a good interim solution. Do you think that "Replace" text will fit into smaller widths like below? It might be worth a try.

![Screen Shot 2020-04-13 at 8 19 27 PM](https://user-images.githubusercontent.com/617986/79182658-2c637900-7dc4-11ea-8cdf-f8ea5df0f519.png)

**Comment by youknowriad** [comment]
This has been implemented recently.
