### ISSUE TITLE
Reusable blocks issue with columns block

### ISSUE THREAD

**Issue by evolvesnc** [WordPress/gutenberg#16427]
Hello everyone,

if you try to save a column block as “reusable block” and try to edit again you are no more able to click on the appender buttons.

The issue is present in the latest Gutenberg plugin 6.0 and also on the WordPress 5.2.2 version.

Here’s a video that explains how to reproduce the issue:
https://www.dropbox.com/s/31hevc639ztz2j6/reusable%20columns%20issue.mov?dl=0

Browse: Chrome

**Comment by talldan** [comment]
I gave this a test and was able to reproduce the issue. Steps:

1. Insert a columns block into a post
2. Choose any of the predefined options for the columns block
3. Create a reusable block from the columns block
4. Name and save the reusable block
5. Edit the reusable block
6. Click the appender button

**Expected**
The popover for inserting blocks opens and a block can be selected and inserted

**Actual**
The popover for inserting blocks opens but then closes straight away.

No errors in the console or anything to indicate what the issue might be..
