### ISSUE TITLE
Pullquote with color causes invalid content bug

### ISSUE THREAD

**Issue by DeoThemes** [WordPress/gutenberg#16429]
**Describe the bug**
When choosing Pullquote with primary color it breaks the block in the editor after page refresh with the following error: _This block contains unexpected or invalid content_ It happens on default 2019 theme.

**To reproduce**
1. Add basic Pullquote block
2. Select main color 
3. Update the post
4. Refresh the page

**Screenshots**
![pullquote](https://user-images.githubusercontent.com/16485360/60723184-91e92600-9f65-11e9-933e-9a6cc38415cd.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by pmmueller** [comment]
Why was this removed from the 6.2 milestone? 

A simple pullquote like this not working properly is so annoying...

**Comment by CreativeDive** [comment]
+1 Waiting for the bugfix.

**Comment by DesignerThan95** [comment]
I have the same problem in this theme but also in my own theme. To get the colors the customizer sets, it is needed to update the color palette and I think, as soon as this happens, the pullquote with default styling gets somehow destroyed.

The twentynineteen Theme does update the colors while loading the editor, so after a reload it is destroyed. I in my theme do it when the customizer gets saved but that has the same effect. 
Maybe someone has a idea how to solve that problem.
