### ISSUE TITLE
Writing flow: hitting backspace causes block to lose heading when prior block is empty

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#16436]
**Describe the bug**

This is a small writing flow issue.

**To reproduce**

1. Create an empty paragraph
2. Press `Enter`
3. Create a heading with some text
4. Put the caret at the start of the heading
5. Press `Backspace`

**Expected behavior**

The block should be preserved if the previous block is empty.

**Comment by paaljoachim** [comment]
Hey Ella
Is this issue still relevant?

**Comment by annezazu** [comment]
Noting that this can still be replicated with 6.3 RC 1:

https://github.com/WordPress/gutenberg/assets/26996883/e636cfe0-2b23-4ff4-8c3c-e535fa6cefce

**Comment by bangank36** [comment]
@ellatrix Is the issue still worth fixing? I can reproduce it on latest GB

|  Below Paragraph | Below Empty Paragraph  |
|---|---|
| ![Kapture 2023-08-23 at 19 55 20](https://github.com/WordPress/gutenberg/assets/10071857/d9fad30d-d56f-40a4-8ffb-971b5815e849)  |  ![Kapture 2023-08-23 at 19 53 33](https://github.com/WordPress/gutenberg/assets/10071857/1bcdfdff-0a9f-4f3c-84ff-2961ac592937) |

### Expected
The heading should not be merged with previous block if paragraph is empty
![Kapture 2023-08-23 at 20 04 55](https://github.com/WordPress/gutenberg/assets/10071857/c17553ee-9279-4691-8994-d148bb12f71f)
