### ISSUE TITLE
Adding Gutenberg to the WP admin Dashboard

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#16430]
I would like to be able to add Gutenberg blocks to the WP-admin Dashboard.

The existing Dashboard:
![Screen Shot 2019-07-05 at 15 43 16](https://user-images.githubusercontent.com/5323259/60726394-b8926700-9f3b-11e9-8b2d-e7ab245d0c8d.png)
 
-----

What would the new Dashboard look like?

Having the Dashboard similar to a page/post. Adding blocks to where we can create a valuable help resource for the client. Adding such things as notes, video, stats and more.

**Comment by paaljoachim** [comment]
@audrasjb Suggested refreshing the wp-admin dashboard section with the Gutenberg design.

![dashboard-gutenberg](https://user-images.githubusercontent.com/5323259/63212188-d0dfcf00-c100-11e9-88c7-35e6bab2b1e8.jpg)

**Comment by gziolo** [comment]
Shouldn’t it be discussed in WordPress trac instead?

**Comment by paaljoachim** [comment]
I added a trac issue: 
https://core.trac.wordpress.org/ticket/48385#ticket

**Comment by swissspidy** [comment]
Closing in favor of the Trac ticket
