### ISSUE TITLE
Update code primitives to use SettingsSidebar

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#16437]
Per issue #14988 and PR #16138 

Capturing here to address using the proper terms in code to match [Designer Handbook](https://developer.wordpress.org/block-editor/designers/design-patterns/) to improve developer and user experience with consistent terms.

Update code primitives to use the Settings Sidebar term instead of Inspector.

cc: @nosolosw

**Comment by lozinska** [comment]
Hello there! I would like to work on this issue, but as I'm new to Open Source I would like to clarify that Inspector names should be changed to Settings Sidebar?

**Comment by mkaz** [comment]
I'm not sure there is enough value here trying to rename `InspectorControls` to `SettingsSidebar`

The component has been around for a couple years now, and there hasn't been much interest or support on renaming, so closing out this issue.
