### ISSUE TITLE
How can I access the Block settings in the Widgets (beta) area?

### ISSUE THREAD

**Issue by adam-ind** [WordPress/gutenberg#16432]
Normally when editing blocks I get a nice sidebar to change some settings for blocks like so: 
![image](https://user-images.githubusercontent.com/48963897/60731264-27a89500-9f15-11e9-9b8e-0b5c0c8df286.png)
But in the Block Areas aka Widgets (beta) that sidebar doesn't seem to show up, so I am unable to customize things like number of columns:
![image](https://user-images.githubusercontent.com/48963897/60731335-5161bc00-9f15-11e9-80b1-a2d18e32be49.png)
Is there a way to view this sidebar? Thanks!

**Comment by Soean** [comment]
This feature was added in #16203 and will be included in Gutenberg 6.1, which will be released on July 10th.
