### ISSUE TITLE
Provide a way for blocks to opt-out of being grouped by the Group block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#16446]
**Is your feature request related to a problem? Please describe.**
Currently there's no implementation for blocks to opt-out of being wrapped within the Group block. One common use case I see here is with child blocks that only exists within specific parent blocks. These likely do not need to ever be grouped. And if the Group block is not added as an allowed block within InnerBlocks, it doesn't get added anyhow. 

[Relevant discussion](https://wordpress.slack.com/archives/C02QB2JS7/p1562099001499700) on WordPress Slack.

Examples: 
1. A Form block with Field child blocks
2. A Pricing Table block with child blocks within for each table

Sure, we could group the child blocks in these scenarios, but what value would we really add, and at what UX cost? If we're expecting users to first group before adding any background colors, that's quite a few extra steps to do so (vs. having a Background Color selection within the Settings Sidebar of the child block). 

**Describe the solution you'd like**
Perhaps child blocks are opted-out already and must opt-in to support being grouped. And if so, the Group block should probably be white-listed as an allowed block within InnerBlocks - so we're not relying on folks to add it every time.  

**Describe alternatives you've considered**
There's currently no way to remove the Group block transformation for blocks.

**Comment by paaljoachim** [comment]
The issue seems similar to: https://github.com/WordPress/gutenberg/issues/16416

**Comment by richtabor** [comment]
> The issue seems similar to:
> "Add supports option to enable/disable group option per block."
> #16416

Good find. I'll post a comment with the info I added here.
