### ISSUE TITLE
Getting Update When The Order Of Components Are Changed

### ISSUE THREAD

**Issue by meceware** [WordPress/gutenberg#16443]
Hi,

I'm looking for a way to find a React event when the component order is changed inside a parent component, such as moving up or down.

![image](https://user-images.githubusercontent.com/16402717/60753908-0eb9e580-9fe2-11e9-9ecc-235c03fcb224.png)

I tried various methods including componentDidUpdate() but none of them worked. I couldn't find any information on a maybe-hook of that buttons or drag-drop hook either. 

Is there a way to get an update when the order of components inside a parent component is changed?

Thank you!

**Comment by youknowriad** [comment]
you can subscribe to the data changes `wp.data.subscribe(listener)`  and check for the value of the blockOrder property their `wp.data.select( 'core/block-editor' ).getBlockOrder()` and see if the value changes. 

Also note that for general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/. 

Thanks for your understanding.
