### ISSUE TITLE
Why are selectors missing from Wordpress core data store

### ISSUE THREAD

**Issue by TKY2048** [WordPress/gutenberg#16442]
When selecting the "core" store of Wordpress JavaScript API via wp.data.select("core") It returns an incomplete list of selectors.

The selectors returned are the following: 
canUser: ƒ ()
getAuthors: ƒ () 
getEmbedPreview: ƒ () 
getEntitiesByKind: ƒ () 
getEntity: ƒ () 
getEntityRecord: ƒ () 
getEntityRecords: ƒ () 
getMedia: ƒ () 
getMediaItems: ƒ () 
getPostType: ƒ ()
getPostTypes: ƒ () 
getTaxonomies: ƒ () 
getTaxonomy: ƒ () 
getThemeSupports: ƒ () 
getUserQueryResults: ƒ () 
hasUploadPermissions: ƒ () 
isPreviewEmbedFallback: ƒ ()
isRequestingEmbedPreview: ƒ ()

Instead of the full lists shown in https://developer.wordpress.org/block-editor/data/data-core/

For example, wp.data.select("core").getCurrentUser() returns undefined when called from the edit function of a block declared inside a regiterBlockType function in a JS script registered in the init hook.

**Comment by Soean** [comment]
I can see all selectors in my console:
![core-data](https://user-images.githubusercontent.com/695201/60772179-f1287100-a0f2-11e9-8299-b36949dbce0d.png)

For resolving the undefined problem, please see https://github.com/WordPress/gutenberg/issues/14623#issuecomment-499445665

**Comment by TKY2048** [comment]
I'm trying to show some fields in a block based on user capabilities (only visible for admins). From what I understood from the post, I should be using withSelect HOC to inject, in this case, what would be the user object returnet by wp.data.select('core').getCurrentUser() as a prop for my component. Doing this still returns undefined, what makes me think i'm missing out something here. Still, when evaluating wp.data.select('core') directly in the console i get this list : 
![image](https://user-images.githubusercontent.com/16092783/60988124-9d8f7080-a308-11e9-8fe3-61b64af83353.png)
intead of the list shown by @Soean, but it's the same list that @Pretzel63 got in  #14623 what makes me think we both were doing something wrong. 
This is what I'm trying to do:
`const { withSelect } = wp.data;

function MyComponent ({currentUser}) {
	console.log(currentUser);
	return null;
}

export default  withSelect( ( select ) => ( {
    currentUser: select( 'core' ).getCurrentUser(),
} ) )( MyComponent );`
Can I get some insight of what I could be doing wrong?

**Comment by stuartshields** [comment]
I know this is closed, but @TKY2048 I had the same issue as you and after digging around for a while I found out it's because it's not in the core build of WP yet. Hopefully this helps.

**Comment by TKY2048** [comment]
I found a workaround, got the expected behaviour with:

`export default withSelect( select => ( {
	userIsAdmin: select( 'core' ).canUser( 'create', 'users' ),
} ) )( PlaceAdditionalInfoEdit );`

**Comment by janwidmer** [comment]
@stuartshields there seems still to be a discrepancy regarding available methods when doing `wp.data.select("core")` in the browser console versus what is documented on https://developer.wordpress.org/block-editor/data/data-core/.

E.g. the method `getPostTypes` is not documented. You wrote, it's not part of the core build, do you know, in which repo it is located then?

**Comment by swissspidy** [comment]
`getPostTypes` and the like are derived from the `getEntity` selectors I think. They are not documented individually due to repetition

**Comment by janwidmer** [comment]
ah ok.. funny enough, I also don't really find any usages in this repo when I search for the method..just two within tests..
