### ISSUE TITLE
Inserter: fix the tabs focus style

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1644]
Currently the focus style looks like this:

<img width="326" alt="screen shot 2017-07-02 at 19 49 30" src="https://user-images.githubusercontent.com/841956/27772319-e0efcdb4-5f5f-11e7-9a31-d6c7acc5cbae.png">

The tab with the focus key needs some `z-index` love here. Even `z-index: 2` already works.

Note: I can't seem to be able to trigger it with the keyboard, because pressing tab automatically goes to the blocks list. See https://github.com/WordPress/gutenberg/issues/1606#issuecomment-312506265 for a possible solution to that.

**Comment by josephfusco** [comment]
I can't seem to reproduce this.

Tabbing through seems to lock the focus into an infinite cycle within the current tab content with no obvious way on how to change tabs.

**Comment by afercia** [comment]
Tabbing to the tabs is currently broken, known issue and pending a final decision on the inserter functionalities to be fixed.

Accessibility of the inserter worked at some point (there were no tabs) see https://github.com/WordPress/gutenberg/pull/527. Then the introduction of tabs didn't address keyboard navigation. The inserter has seen other changes under the hood, I hope it will be in a stable state soon so we can address accessibility.

**Comment by afercia** [comment]
See also https://github.com/WordPress/gutenberg/issues/1497#issuecomment-325688527

**Comment by jasmussen** [comment]
Pretty sure this is fixed by #3080.
