### ISSUE TITLE
openGeneralSidebar action is not working 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#16447]
**Describe the bug**
the action **openGeneralSidebar** form [the The Editor’s UI Data](https://developer.wordpress.org/block-editor/data/data-core-edit-post/) is not working, as the documentation said that it could be used to open the editor sidebar when it is closed 

I have added a button to the editor, add an event listener to it, so when it clicked I call this action with the dispatch method like this: 
`    
dispatch("core/edit-post").openGeneralSidebar();
`

But nothing happens, also I have noticed that when the side bar is opened this function actually closed it!

**Comment by Soean** [comment]
To open the sidebar, you have to add the sidebar name as a parameter

Open document sidebar
`wp.data.dispatch("core/edit-post").openGeneralSidebar( 'edit-post/document' );`
Open block sidebar
`wp.data.dispatch("core/edit-post").openGeneralSidebar( 'edit-post/block' );`
