### ISSUE TITLE
Move 'Link to' to Image block's toolbar

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#16451]
We ought to move the Image block's 'Link to' functionality from the sidebar to the toolbar, as it is common functionality that should be surfaced. 

@jasmussen explains it best in https://github.com/WordPress/gutenberg/issues/5309#issuecomment-410967307, which I shall copy and paste verbatim:

> Good discussion here, and nice work overall.
> 
> However I feel like the discussion missed a relatively important aspect of the block design principles, the split between basic and advanced functionality. The principles essentially suggest that you should not put anything in the sidebar that is necessary for the basic operation of the block ([the full text](https://wordpress.org/gutenberg/handbook/reference/design-principles/#editor-settings)). 
> 
> Those principles are intentionally left up to interpretation, and it is definitely up for debate whether linking an image is _basic_ or _advanced_ functionality. But the net result is that now we have this:
> 
> ![screen shot 2018-08-07 at 09 44 03](https://user-images.githubusercontent.com/1204802/43761929-d4c5dcf6-9a26-11e8-8120-b0ca5511458b.png)
> 
> ☝️ In this screenshot, the Settings sidebar is dismissed. How do I link the image?
> 
> Note that this is not just about casual users that want a simpler editing experience. It is also an issue when the user is using a plugin, for example "Drop It", which allows you to insert images from Unsplash:
> 
> ![screen shot 2018-08-07 at 09 48 06](https://user-images.githubusercontent.com/1204802/43762014-0e7c2cf2-9a27-11e8-9c59-8159b01a72fb.png)
> 
> **If we feel that linking an image is advanced functionality**, then what is in `master` right now is absolutely the right design.
> 
> **If we feel that linking an image is basic functionality**, then we should either consider adding back the link button to the toolbar as it was, or find a way to add the "Links to" functionality to this modal:
> 
> ![screen shot 2018-08-07 at 09 50 16](https://user-images.githubusercontent.com/1204802/43762122-521da332-9a27-11e8-9f41-43d7a6734761.png)
> 
> ---
> 
> Having written this comment, I'm obviously in the "it's basic functionality" camp. But I'm not strongly so, and I won't argue it to the moon and back. But I have a gut feeling we'll get tickets about this, so it's good to have the discussion.

**Comment by jasmussen** [comment]
Given you quoted me, I've obvioiusly already left my "design feedback" suggesting that it'd be nice to move this functionality to the block toolbar. 

I seem to recall @jorgefilipecosta having some code that might enable this.

**Comment by youknowriad** [comment]
It seems like this is already done and merged.

**Comment by jasmussen** [comment]
Oh wow, you're right! Master:

<img width="692" alt="Screenshot 2019-07-08 at 10 21 43" src="https://user-images.githubusercontent.com/1204802/60794535-45226c80-a16a-11e9-86b6-748112e41cf6.png">

It just hasn't yet shipped in the plugin:

<img width="374" alt="Screenshot 2019-07-08 at 10 22 09" src="https://user-images.githubusercontent.com/1204802/60794542-4a7fb700-a16a-11e9-9c37-5fd2cb829cc5.png">

Closing as fixed! 🎉

**Comment by noisysocks** [comment]
Oh! My mistake! Glad we addressed this paper cut 😌
