### ISSUE TITLE
Column block: Image link in block toolbar is hard to use (6.1.RC)

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#16467]
I was testing the new setting for the link for the image block, when it was used in a column setting. It took multiple tries to get the link button to open to enter the url and use the other features, as the column block borders seems to get in the way of registering the click/hover. 

**To reproduce**
1. Add a column block with two columns
2. Add an image block to the left one
3. Add a cover block in the right one
4. Add a link to the image blick via the block toolbar.

**Expected behavior**
that i would be able to easier access the toolbar button. 

**Screenshots**
I created a video: http://recordit.co/ZEZB0L4h1K

**Desktop (please complete the following information):**
 - OS: 10.13.6 MacOS
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by youknowriad** [comment]
Is it still the case @bph I tried reproducing the issue today but it was working properly.
