### ISSUE TITLE
Tips: Consider a dedicated "Help" area of the interface

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16464]
_This is a bit of an alternate idea for #16315. I believe the solution proposed in the other ticket is stronger, but wanted to document this in case it triggers other ideas later on._ 

---

Currently, the [user-facing Gutenberg documentation](https://wordpress.org/support/article/wordpress-editor/) is not particularly easy to find from within the Gutenberg interface. 

Simultaneously, there are a number of issues with the current "Tips" NUX experience. To name a few: tips block important UI, are hard to find once dismissed, and are frequently ignored by users. 

Along the path to solving these problems, I drew up mockups for a sidebar-based "Help" area. This would exist as a `?` icon  in the top toolbar, and would trigger a sidebar, like plugins do currently:

![Screen Shot 2019-07-08 at 11 56 39 AM](https://user-images.githubusercontent.com/1202812/60824367-7a818700-a177-11e9-8b38-f17fabaf2375.png)

This would allow us to potentially do a couple cool things:

## 1. Dedicate space to a step-by-step NUX/Welcome flow:

<img width="958" alt="01-Help-Panel" src="https://user-images.githubusercontent.com/1202812/60825016-c254de00-a178-11e9-8e47-a03508bb02dd.png">

🖥  **[Desktop Prototype](https://www.figma.com/proto/ctlWVC9KjYCLQlxTMAm81OT2/Tips-Iteration?node-id=103%3A6645&viewport=4%2C549%2C0.5&scaling=min-zoom)**

## 2. Provide contextual help, relative to the element the user is focusing on: 

<img width="958" alt="02-Help-Panel" src="https://user-images.githubusercontent.com/1202812/60825237-3e4f2600-a179-11e9-9c51-657c55afdb39.png">

🖥  **[Desktop Prototype](https://www.figma.com/proto/ctlWVC9KjYCLQlxTMAm81OT2/Tips-Iteration?node-id=108%3A962&viewport=372%2C767%2C0.5&scaling=min-zoom)**

---

In addition, it would provide a handy "escape hatch" for users who're lost. It's a recognizable icon that would house evergreen help resources. 

There are a number of obvious issues with this approach: 

- The sidebar has been a perennially problematic interface from an a11y perspective. 
- This is a very desktop-centric exploration: Sidebars typically take up the entire screen on mobile, which would negate the contextual nature from the comps above. 
- The sidebar would have to disappear if users wanted to interact with any other sidebars. 

For those reasons, I believe  #16315 is a somewhat more effective solution to most of the issues with Tips. However, I could see a dedicated area for user documentation being extremely helpful for folks. (This could even just be a "Help" menu item, that opens a modal full of links).

**Comment by kjellr** [comment]
For reference, the approaches outlined above are reminiscent of the contextual help in [Ableton Live](https://www.ableton.com/en/live/): 

![Screen Shot 2019-07-03 at 11 07 05 AM](https://user-images.githubusercontent.com/1202812/60894850-829dfd00-a231-11e9-8e7a-9ebd60bf86c2.png)

Thanks @MichaelArestad for the tip.

**Comment by karmatosed** [comment]
I really like how Figma does this for keyboard shortcuts:

![image](https://user-images.githubusercontent.com/253067/61082386-47622080-a421-11e9-9376-0e59f4e688a3.png)

**Comment by mapk** [comment]
Adding a dedicated help section is a solid point of return for those in need of help. I believe it would help the experience. My only concern is the position of the question mark in the top bar. As plugins add their own sidebar icons, space gets limited. 

Because I haven't seen a lot of plugin icons there in my experience, I don't think it will be a problem, but something to consider.

**Comment by kjellr** [comment]
> As plugins add their own sidebar icons, space gets limited.

On the other hand, that area was built to scale depending on the number of icons in it — I believe if a user added more than two plugins, they just flow into the ellipsis dropdown automatically right now.

**Comment by tomjn** [comment]
Given that there's usually a help tab in most WP Admin pages in the same slot, would it make sense to turn this into an admin wide pattern and put it in the toolbar when it's available? That might simplify things in more places and avoid scrolling to the top of the screen for help

**Comment by mapk** [comment]
Closing this as we look to add "Help" to more areas in the interface.

For example, we now have this:

![Screen Shot 2020-01-28 at 9 16 19 AM](https://user-images.githubusercontent.com/617986/73288161-56d36c00-41af-11ea-8ba8-b291538b5c5d.png)
