### ISSUE TITLE
I have a weird issue in wordpress 5.0 new block editor

### ISSUE THREAD

**Issue by zainabid3108** [WordPress/gutenberg#16472]
I am looking around this problem from last 10 hours now and visited different forums but did not get any help

For better understanding I want you to see this page.

http://tailormadebodiez.net/vip-online-coaching/

I have made a clone of this page in wordpress and just added some space in editor and now this page looks like this

http://tailormadebodiez.net/vip-online-coaching-2/

Everything gone! style, images etc. (only in content area)

This is the picture of backend.

https://prnt.sc/ocesd1 (this is the correct page screen shot)

https://prnt.sc/ocetbm (this is the clone page screen shot which is same but its front end is not same like the above one)

Backend page screen short (from below) for both pages correct one and cloned one: https://prnt.sc/oceumi

**Comment by Soean** [comment]
You Screenshot does't look like the Gutenberg Block Editor. If I look in you source code, it looks like you a using the ThemeFuse Visual page builder. Maybe try to contact the theme author.
