### ISSUE TITLE
Block validation failed for Custom Blocks

### ISSUE THREAD

**Issue by mohanvvr** [WordPress/gutenberg#16474]
Hello!

I have created a Custom image upload function in Gutenburg Block. I have tried to apply few controls for the block. I'm getting error "this block contains unexpected or invalid content" in the page and saying 

Current
<div class="wp-block-responsive-blocks-ra-team-table-avatar img-wrapper"><img src="http://localhost/wordpress/wp-content/uploads/2019/06/avatar2.png" alt=""/></div>

After Conversion
<div class="wp-block-responsive-blocks-ra-team-table-avatar img-wrapper">**<figure>**<img src="http://localhost/wordpress/wp-content/uploads/2019/06/avatar2.png" alt="">**</figure>**</div>

Also see javascript console error below:

**Warning:**
blocks.min.js?ver=6.2.5:2 Block validation: Expected attributes 
Array(2)
0: (3) ["style", "padding-top:2px;padding-right:2px;padding-bottom:10px;padding-left:20px", true]
1: (3) ["class", "wp-block-responsive-blocks-ra-team-table-avatar ra-team-table-avatar img-wrapper", true]
length: 2
__proto__: Array(0)
, instead saw 
Array(1)
0: (3) ["class", "wp-block-responsive-blocks-ra-team-table-avatar img-wrapper", true]
length: 1
__proto__: Array(0)

**ERROR**
blocks.min.js:2 Block validation: Block validation failed for `some-blocks/xxx-xxx-xxx-xxx` (Object).

Content generated by `save` function:

<div style="padding-top:2px;padding-right:2px;padding-bottom:10px;padding-left:20px" class="wp-block-responsive-blocks-ra-team-table-avatar ra-team-table-avatar img-wrapper"><img src="http://localhost/wordpress/wp-content/uploads/2019/06/avatar2.png" alt=""/></div>

Content retrieved from post body:

<div class="wp-block-responsive-blocks-ra-team-table-avatar img-wrapper"><img src="http://localhost/wordpress/wp-content/uploads/2019/06/avatar2.png" alt=""/></div>
(anonymous) @ blocks.min.js:2

Please help me to solve this
Thanks in Advance
Mohan

**Comment by youknowriad** [comment]
It seems like you applied some custom styles to a block that doesn't support these styles by default. Thisi message is expected, if you want to create random HTML, you might want to consider using the HTML block or the classic block.
