### ISSUE TITLE
Uncaught PHP exceptions in do_blocks()

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#1647]
`Gutenberg_PEG_Parser::parse()` can throw an exception which is not caught by an error handler in `do_blocks()` leading to a fatal error.

**Comment by nylen** [comment]
Which exception is this? With what content does it occur?

**Comment by swissspidy** [comment]
There's a ` throw new Exception("Can't start parsing from rule \"" + $options["startRule"] + "\".");` line in that method.

**Comment by ocean90** [comment]
Right, there's also `throw $this->peg_buildException()`, a wrapper for `Gutenberg_PEG_SyntaxError`.

**Comment by nylen** [comment]
Neither of these are reachable in our setup. Feel free to reopen this if there is a unit-testable case here but I am pretty sure there isn't.

**Comment by ocean90** [comment]
Looks like the current parser isn't the best solution anyway so I'm fine with closing.

**Comment by nylen** [comment]
That's a separate discussion.  I closed this because I don't think it's a practical problem.  If that's not right, please let me know and we'll fix it.
