### ISSUE TITLE
Can't replace selected content in a text block by pasting from clipboard

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#1648]
![kapture 2017-07-02 at 22 23 06](https://user-images.githubusercontent.com/617637/27773239-b1c15b78-5f75-11e7-8d8f-4258ea8f52b3.gif)

Tested in Chrome 59.0.3071.115 and Safari, works in Firefox.

May be related to #1331.

**Comment by youknowriad** [comment]
Can't reproduce anymore
