### ISSUE TITLE
Button Block and Multiple Buttons

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16480]
One fairly common need is aligning more than one button in a row. Multiple block libraries have added similar tools (either a special multiple buttons block or the ability to add more instances in a single button block). We should explore bring this into core, likely leveraging child blocks for the extra buttons, but in a more convenient way than forcing people to add columns first to hold each button in place.

**Comment by jasmussen** [comment]
YO! I passionately love this ticket, so I created a mockup:

<img width="1282" alt="buttons" src="https://user-images.githubusercontent.com/1204802/63575928-7d9bcf80-c58b-11e9-90f8-40c88caa1b2f.png">

The mockup above is inspired by efforts underway in https://github.com/WordPress/gutenberg/pull/16897#issuecomment-523399945, where we are building a container for social links that show up side by side. 

This would work the same for a Button Group or what the name might end up as. 

As noted in that ticket referenced, this would make use of a new UI feature we'd build for parent block containers, to allow child block UIs to be absorbed by the parent.

**Comment by mtias** [comment]
> This would work the same for a Button Group or what the name might end up as.

I hope we can call this just "Buttons". Another thing that this should also help with is that alignment controls move from the individual "Button" block (what we have right now) to the container "Buttons".

**Comment by ZebulanStanphill** [comment]
What if the Group block had a horizontal layout option? Using flexbox you could have a wide range of alignment/spacing controls, and you could use show several blocks (not just buttons) on the same line without having to use columns. (And with `flex-wrap` it would be easily responsive.)
