### ISSUE TITLE
Add support for gradients in Button blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16482]
It'd be nice to explore how gradients could work as the fill color choice for buttons.

**Comment by karmatosed** [comment]
It's referenced but noting in: https://github.com/WordPress/gutenberg/issues/16662 that there are some explorations to tie back into this.

**Comment by samhermes** [comment]
It's frustrating to see this feature added without a proper way to disable it. For most of the WordPress projects I'm involved in, I need control over branding.

**Comment by mtias** [comment]
This is an experimental feature that only works in the plugin so far and is unfinished. It will definitely have more controls and integrations (including `add_theme_support`).

**Comment by youknowriad** [comment]
Gradients support for buttons is in. improvements to the gradients UI is tracked here #16662
