### ISSUE TITLE
How can I order by a metaKey with getEntityRecords 

### ISSUE THREAD

**Issue by mathishuettl** [WordPress/gutenberg#16487]
Hello,

is it possible to order posts by a metaKey when using getEntityRecords()?

`getEntityRecords( "postType", "mycpt", { order: "desc", orderby: "meta_value_num", metaKey: "xxx" } );`

Gives me that error:

> orderby: "orderby ist nicht eins von author, date, id, include, modified, parent, relevance, slug, include_slugs, title."

**Comment by Soean** [comment]
You can only use what the REST API supports: 

>One of: author, date, id, include, modified, parent, relevance, slug, title

Documentation: https://developer.wordpress.org/rest-api/reference/posts/#arguments
