### ISSUE TITLE
Cannot update permalink on home page

### ISSUE THREAD

**Issue by SallieBentley** [WordPress/gutenberg#16486]
Despite reading several forums and trying several things (including clicking in the title field)  I still cannot simply change my main website permalink to remove the word "/admin" from the end of the url - why is this so hard - surely it must be possible to do - my designer left the word admin in from the test site but it makes no sense - how can I change the page link url?

**Comment by youknowriad** [comment]
Hi There!

It's not clear from the issue whether that `/admin` is before the name of the page or after (a full link could help). In Gutenberg you can edit the page slug from the "Permalink" panel in the "Document" sidebar.

And I believe you might need to go to the "Permalink" settings of your dashboard to tweak the overall structure of your links.

That said, please note that for general help requests, the support forum is preferred. https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you.
