### ISSUE TITLE
Try to make link UI in the button block consistent with other link interfaces

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#16495]
See also #2216, #6392

**Description**
#10128 involved quite a bit of iteration on the link UI in the button block, which was perhaps out of scope for the related issue. Eventually, a simplified design was settled on in order to move the PR forwards, but there's was acknowledgement that we're still left with inconsistencies across link user interfaces in Gutenberg.

This issue summarises some of the explorations on that PR and captures that further exploration may be required.

### Using the link popover in the button block (https://github.com/WordPress/gutenberg/pull/10128)
![pull-8000](https://user-images.githubusercontent.com/20284937/45930305-3888ab00-bf80-11e8-94ea-d59988bab76f.gif)

For:
- Brings consistency across link interfaces

Against:
- This approach was very hard to make accessible. Since the link input field is in a popover it wasn't possible to tab from the button text to the link input and back again.

### Using a button to open the link popover (https://github.com/WordPress/gutenberg/pull/10128#issuecomment-480205865)
![button-link](https://user-images.githubusercontent.com/677833/55616988-b2b6a980-57c5-11e9-93e0-1f983b5cb52a.gif)

For:
- Is still consistent with other link interfaces
- Solves some accessibility problems inherent other solutions

Against:
- It's a bit weird, a confusing extra step that users have to take

Other info:
- It was suggested that the button could be a toolbar button, though I think this hides an essential piece of functionality for the button block.

### An inline version of the link popover (https://github.com/WordPress/gutenberg/pull/10128#issuecomment-481963432)
![inline-link](https://user-images.githubusercontent.com/677833/55931029-7ddba400-5c56-11e9-835f-7ba69c00f9a7.gif)

For:
- Is still consistent with other link interfaces
- Solves some accessibility problems inherent other solutions

Against:
- It's visually busy

Other info:
- I discovered afterwards that this is similar to how coblocks displays the link user interface in its blocks. For example: https://github.com/godaddy/coblocks/pull/580
- Some further design feedback here on this option: https://github.com/WordPress/gutenberg/pull/10128#issuecomment-482130323

### A simplified version of the link UI (screen capture is similar to what was implemented)
![8000](https://user-images.githubusercontent.com/20284937/56182552-86f0ba80-6034-11e9-986f-11b61701c876.gif)

For:
- Visually clean
- Solves some accessibility problems inherent other solutions

Against:
- Still inconsistent with other link user interfaces.

**Comment by afercia** [comment]
Seems to me one of the inconsistencies (and an actual problem for accessibility) is that when a link suggestion is highlighted, tabbing away from the input field sets the link.

This is a problem because the Tab key must be reserved for keyboard navigation. Triggering an action (setting the link) while users just want to navigate away would be completely unexpected.

**Comment by talldan** [comment]
Yep, though just to clarify, the link is updated on every keypress not when the input blurs. That's not something new, but the way the button block worked before #10128 as well.

Introducing a submit/apply button would make it more consistent and probably help in the implementation of #16494 as well. Could even be done as part of fixing that issue.

**Comment by talldan** [comment]
Closing as the link UI has recently been updated.
