### ISSUE TITLE
New post: automatically focus post title

### ISSUE THREAD

**Issue by JDGrimes** [WordPress/gutenberg#1649]
When creating a new post, I expect to be able to just start typing. Instead, I have to manually focus the title field before entering my title.

(Apologies if this is a duplicate or has already been rejected for some reason.)

**Comment by afercia** [comment]
Auto focusing some UI controls is always a bit tricky and, generally, assumes just _one_ workflow. It makes sense when there's one, very specific, task. For example, a short form gets displayed in some UI section with a very specific task to complete: focusing the first form field makes sense. 
However, in the editor there are several, possible, workflows. Users may prefer to start setting some post settings, or clicking on the inserter to add some blocks. Also, some custom post types don't have a title. 

For keyboard users, auto focusing the title field would "skip" all the UI controls that are placed before the field, forcing them to tab backwards. For screen reader users, "skipping" all the toolbar would make those controls harder to discover.

Somewhat related also to the general grouping and order of controls, see #467 

Ideally, if a UI controls is important enough to automatically receive focus, then maybe it's worth considering placing it as the very first thing in the interface. This is what WordPress has already done, for example, with the comments textarea. See https://core.trac.wordpress.org/ticket/29974

**Comment by JDGrimes** [comment]
Yeah, I thought that might be an issue. However, WordPress already does this on the add new post screen, so I guess I just kind of missed it and it felt like a regression.

**Comment by afercia** [comment]
> WordPress already does this on the add new post 

Yep, right. I missed to mention that. However, in the current edit screen there's very little before the title field: main heading, screen options/help tabs. Instead, in Gutenberg many important controls are placed before the title.

**Comment by mtias** [comment]
Going to close this, as it's not clear it'd be an improvement (specially if you don't want a title).
