### ISSUE TITLE
Button block URL input has no validation or audible feedback

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#16494]
**Description**
When adding or modifying a url in the button block, the user can enter anything, there's no validation or feedback about whether the URL has any errors, or even about whether the URL was successfully added.

There's also no audible feedback for screenreader users.

Tasks:
- Add the same URL validation that's present in the paragraph block's link format to the button block.
- Ensure there's sufficient visual feedback for users about whether the link was successfully added or whether it might contain errors. 
- Ensure there's audible feedback for screen reader users (e.g. using the `speak` functionality).

**Additional Details**
Discovered in #10128, but is an issue present since the launch of the button block.

**Comment by talldan** [comment]
Just noting the discussion on https://github.com/WordPress/gutenberg/issues/16495#issuecomment-510004478, which mentions introducing an apply/submit button for the url input field. That might also be a consideration for implementing this PR as well.

**Comment by karmatosed** [comment]
I would vote for having real-time searching not for it to only work on clicking of a button.

**Comment by karmatosed** [comment]
As there is a discussion on #16495 and it seems that this wouldn't need a design as much as validation, let's remove that label for now.

**Comment by talldan** [comment]
The UI is considerably different now, so I imagine this outdated. Closing.
