### ISSUE TITLE
Google Trends embed graphs (Javascript) not working in WordPress 5.0.2

### ISSUE THREAD

**Issue by spektacle** [WordPress/gutenberg#16492]
Hello,

I recently updated to WordPress 5.2.2 and now Google Trends embed graphs are not showing up in any of my published Posts. I have been embedding Google Trends in all my Posts and didn't have an issue until this update. Google Trends embed uses Javascript code.

Essentially, when I create a new Post, the embed script appears in the Code Editor, but nothing appears when I publish. It's a blank space. 

I tried using a custom HTML block to drop in the script but it does not work.

Any ideas?

**Comment by Soean** [comment]
Do you have a code example?

**Comment by spektacle** [comment]
Yes for example this is a GT chart for 'almond milk' in the UK:

<script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1845_RC03/embed_loader.js"></script> <script type="text/javascript"> trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"/m/03376x","geo":"GB","time":"today 5-y"}],"category":0,"property":""}, {"exploreQuery":"date=today%205-y&geo=GB&q=%2Fm%2F03376x","guestPath":"https://trends.google.com:443/trends/embed/"}); </script> 

I've tried to display it in Wordpress using different themes and with all plugins turned off without any luck.

**Comment by youknowriad** [comment]
I just tried with the same code and it works great for me. It might have been fixed in the recent versions of the plugin.

<img width="727" alt="Capture d’écran 2019-07-25 à 5 19 42 PM" src="https://user-images.githubusercontent.com/272444/61890931-79cf4b80-af00-11e9-8570-059c81b42b76.png">
