### ISSUE TITLE
Pressing return in the title field does not create a block

### ISSUE THREAD

**Issue by JDGrimes** [WordPress/gutenberg#1650]
Pressing return in the title bar does nothing. I expected that it would advance into the first block in the post content.

Related: https://github.com/WordPress/gutenberg/issues/1003

**Comment by youknowriad** [comment]
This should also handle backspace (and maybe merge the content of the text block into the title?).
I'm thinking we should leverage the `WritingFlow` component to address this. it wraps the title and the blocks and enables arrow navigation for now, we could do the same for Enter/Backspace handling. It might not be so easy but worth exploring.
