### ISSUE TITLE
Add "Transform to Columns" option when multiple blocks are selected. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16504]
This could live in the standard block transforms area. Like the "Group" transform, this would create a new block (a Columns block in this case) that would contain the selected blocks. Each block would become its own column. 

![columns](https://user-images.githubusercontent.com/1202812/60971247-b6d8f280-a2f1-11e9-9e66-c645a9cdfd05.gif)

**Comment by richtabor** [comment]
If you select three blocks, will it add them to a Columns block with three columns? 🤔

**Comment by kjellr** [comment]
> If you select three blocks, will it add them to a Columns block with three columns? 🤔

I think so! I figure we could make this available for up to a certain number of blocks/columns. If you have a giant number of items selected the option would disappear from the menu.

**Comment by mtias** [comment]
Sounds like an interesting idea to try.

**Comment by mapk** [comment]
I agree. I think with a limit set for transforming to a column block, this could work great! Maybe in the future it can be dependent on the number of columns in whatever grid the theme registers. So if the theme registers an 8 column grid, it only allows for eight columns? Just a thought.

Let's build it!

**Comment by kjellr** [comment]
This is probably not until later down the road, but it would also be pretty cool if we could combine this with the Patterns API work (https://github.com/WordPress/gutenberg/issues/16283) to let folks create columns from just a single selected block. This would bring us more in line with the original intent from #16049. 

![columns-alt](https://user-images.githubusercontent.com/1202812/61299865-e767d300-a7ae-11e9-8c4a-654ddc529054.gif)
