### ISSUE TITLE
Buttons overlapping the placeholder of block

### ISSUE THREAD

**Issue by vbaimas** [WordPress/gutenberg#16503]
**Describe the bug**
When I hover over the Block, the buttons of `Αdd Image`, `Add Heading`, `Add Gallery` are overlapping the placeholder of block. This appears on `Customizing Widget Blocks (Experimental) ` area.
Gutenberg Version  : 6.1.0 

**Screenshots**
![Image of Yaktocat](https://d1sz9tkli0lfjq.cloudfront.net/items/0M0U2l040d142P1Z0l1L/Screen%20Recording%202019-07-10%20at%2002.36%20PM.gif)

**Desktop:**
 - OS: iOS
 - Browser : Firefox
 - Version : 67.2.04

**Comment by karmatosed** [comment]
I can replicate this, thanks for reporting.

**Comment by noisysocks** [comment]
We don't have this UI anymore.
