### ISSUE TITLE
Testing: Include IE11 "Canary" test in Travis build

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#16509]
There have been a number of occurrences[[1]](https://github.com/WordPress/gutenberg/issues/16194)[[2]](https://github.com/WordPress/gutenberg/issues/10315)[[3]](https://github.com/WordPress/gutenberg/issues/9640)[[4]](https://github.com/WordPress/gutenberg/pull/9795)[[5]](https://github.com/WordPress/gutenberg/pull/5528)[[6]](https://github.com/WordPress/gutenberg/issues/3875)[[7]](https://github.com/WordPress/gutenberg/issues/1397)[[8]](https://github.com/WordPress/gutenberg/issues/664) of catastrophic errors in Internet Explorer which would be immediately obvious on any attempt to load the block editor. In lieu of running the full set of end-to-end tests, we should explore a minimally viable solution to verify that the editor loads without errors and displays some expected elements on the screen.

Possible approach references:

- Travis supports a Windows build environment ([reference](https://docs.travis-ci.com/user/reference/windows/))
- Microsoft offers a [Internet Explorer WebDriver tool](https://support.microsoft.com/en-us/help/2990999/webdriver-support-for-internet-explorer-11)
- If Microsoft's tool is insufficient, we could explore using the [Selenium InternetExplorerDriver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver)
- If we cannot build our own environment for testing Internet Explorer, we could consider [BrowserStack-based automation](https://www.browserstack.com/docs?product=automate) ([possibly free?](https://www.browserstack.com/open-source?ref=pricing)) or similar tooling ([SauceLabs](https://saucelabs.com/), etc)

**Comment by aduth** [comment]
Considering the future of browser support (eventually dropping Internet Explorer support), using something like BrowserStack to attempt minimal loading in a variety of browsers might be a more advisable approach.

Worth mentioning that Puppeteer support is expanding to add [official support for Firefox](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox), where we can broaden our end-to-end coverage to include this browser as well (a separate task).

**Comment by aduth** [comment]
The implementation is different than what is proposed here, but there was some improvements to the general broad goal of protecting against Internet Explorer-related issues in @tellthemachines's pull request at #18774 (simulating IE by running ESLint on the generated bundles in ES5 mode).

**Comment by tellthemachines** [comment]
Have there been any instances of this since I added the lint check? I haven't seen immediate errors on load for a while, but from time to time there are smaller issues like #21276. This wouldn't be caught if we were just checking for page load. I wonder if it would be more useful to have a few checks for basic interaction, e.g. can write text, can add blocks etc.

**Comment by aduth** [comment]
@tellthemachines I'm not personally aware of any "catastrophic failures" (white screens), but there's been a handful of smaller issues related to interaction (the one you mention, also #19979, #20598, and a few other minor ones). I agree that would be useful have testing for those interactions. At this point, since there's so little settled here as far as an approach, it would probably depend whether the solution we choose would have the means to script those sorts of interactions. The options in the original comment are all still viable, and still encompassing of what I understand to be the most promising options available. Writing some basic Selenium tests for Internet Explorer to run in Travis' Windows environment could be the most promising for what you're suggesting, perhaps?

**Comment by sainthkh** [comment]
I've created an experimental PR in #21528. I hope this solves the IE testing problem.

**Comment by gziolo** [comment]
WordPress is dropping support for IE 11 later this year so this issue is no longer relevant:

https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/

Thank you everyone for all the time spent on exploring this idea 🙇🏻
