### ISSUE TITLE
wp data action to duplicate a block 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#16523]
Hi, 

I am looking for a way to duplicate a block using some wp data action. 

I have looked on the documentation but it seems there no way, so what would be the best approach to do that ? 

thanks

**Comment by talldan** [comment]
Hi @DOUARA, probably the best guide will be to look at how Gutenberg's built-in duplicate functionality is implemented:
https://github.com/WordPress/gutenberg/blob/c23228fb78887ae3146c49b2e370150d025a256f/packages/block-editor/src/components/block-actions/index.js#L59-L95

The steps taken are:
1. Fetch the blocks to be duplicated using `getBlocksByClientId`.
2. Clone the blocks using `cloneBlocks`.
3. Insert the cloned blocks using `insertBlocks`

I'll close this as a question answered, but will continue to look out for further responses.

**Comment by zangab** [comment]
@talldan 
these steps seem to be out of date, right?
how could i clone a core block (for exmaple the `core/list`) to create my own (with some modifications)?? 🤔

**Comment by chrisvanpatten** [comment]
@zangab This ticket is regarding how to duplicate a block within a post, like if you type in a paragraph and want to create a copy of that paragraph.

To create your own version of a block, you will need to copy the code and modify it to fit your needs. You can also look at some of the built-in [block filters](https://developer.wordpress.org/block-editor/developers/filters/block-filters/) which allow you to modify other blocks.

**Comment by landwire** [comment]
Hi Chris
you have written this:
> To create your own version of a block, you will need to copy the code and modify it to fit your needs.

But I would like to extend my own block based on an existing core block without copying any code. If I would copy the code I would maintain a totally different version and not get any of the updates to the core blocks. All I would like to do for now is add a wrapper to my own block with `add_filter('render_block', 'Proctor\Blocks\addBlockWrapper', 10, 2);`

So let's say I use `core/paragraph` as a base I somehow create my own block `proctor/paragraph`. The question her is how do I do this? It is an exact clone of `core/paragraph`, but is registered as `proctor/paragraph`. This way I can do the following in my addBlockWrapper function:

```
if ($block['blockName'] === 'proctor/paragraph') {
  addWrapper();
}
```

I appreciate any help!

**Comment by landwire** [comment]
Ok, I thought my comment would open the issue again. I create a new one.

**Comment by htmgarcia** [comment]
About cloning a block, these steps may help:

1. `getBlock`
2. `cloneBlock`
3. `insertBlock`
