### ISSUE TITLE
Editor: Refactor currentPost state to use core-data package

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#16520]
Previously: https://github.com/WordPress/gutenberg/pull/16402#discussion_r301216604

The editor maintains a copy of the original post being edited in its state, as `currentPost`. This value is always representative of the last saved value of the post; edits are maintained separately. There should be effectively no difference between this value and what would be produced by...

```
wp.data.select( 'core' ).getEntityRecord( 'postType', 'post', wp.data.select( 'core/editor' ).getCurrentPostId() );
```

By using the entity provided from the `core-data` data store, we gain some benefit:

- There is only at most one copy of the post held in memory at a given time
- Updates to the canonical post are reflected in the editor, and vice-versa
- The implementation will likely push us to implement saving and setting behaviors for `core-data` entities (and a subsequent refactor of `savePost` to use `core-data` as well)
- Reduced implementation complexity and maintenance overhead of the editor reducer file

**Implementation Specifics:**

For the most part, the crux of the implementation requires changing...

https://github.com/WordPress/gutenberg/blob/8995efde26c7eea6790f0d593dc7bfb5137d0084/packages/editor/src/store/selectors.js#L156-L158

...to:

```js
export const getCurrentPost = createRegistrySelector( ( registry ) => ( state ) => {
	return registry.select( 'core' ).getEntityRecord( 'postType', 'post' /* !!! */, getCurrentPostId( state ) );
} );
```

Some details:

- How do we know the post type? We may still need to track this in editor state, or as an edit. This is unfortunately required because an entity cannot be retrieved from the REST API without providing its post type ([related discussion](https://wordpress.slack.com/archives/C02RQC26G/p1546983215113700)).
- We should see about providing a simpler interface to retrieving entities (I thought we already had `getPost` etc. auto-generated for entities?)

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/blob/ba4793b3d3fbcd49a1ca2defc1734ec999867004/packages/editor/src/store/selectors.js#L162

It looks like it was addressed in https://github.com/WordPress/gutenberg/pull/16932 by @epiqueras.

**Comment by Mamaduka** [comment]
@gziolo, should we close this issue?

**Comment by gziolo** [comment]
I don't know and that's why I didn't close this issue 😄

**Comment by gziolo** [comment]
I did another check. Everything is implemented.
