### ISSUE TITLE
Images & Gallery placeholder opens media library if switching from text

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1652]
Steps to reproduce:

1. Insert an image block
2. Click the "close" button so that a placeholder gets inserted
3. Switch to text mode
4. Switch back to visual mode

Notice how the media library gets loaded as soon as the placeholder is initialized. You can also do this if you save the post, then return back to edit it later.

**Comment by youknowriad** [comment]
Not sure how to solve this without adding a new prop to the block's `edit` function. Maybe an `isNew` flag stating that a block has just been inserted without any change. cc @aduth

**Comment by jasmussen** [comment]
Right now in master, whenever I load the post content, the media library pops up because there's a gallery placeholder. 

Seeing as the "get the media library on insert" is very much an _insert_ related action, would it make sense to attach an extra action to the inserter? Or does that not make sense?

**Comment by westonruter** [comment]
I can reproduce this in the demo content. I access the demo page and immediately the media library opens even though I didn't click anything.

**Comment by aduth** [comment]
This should be fixed by #1784 ? @westonruter can you check whether you have latest master pulled?

**Comment by westonruter** [comment]
Indeed. The demo is fixed on `master` now.
