### ISSUE TITLE
Snackbar | Press Link 

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/gutenberg#16535]
I found one special bug. If I press the Link the color of the text is than invisible. 

**Look here:** 

![](https://i.ibb.co/RYcV3xB/press.jpg)

**Comment by karmatosed** [comment]
I can also replicate this, thanks for reporting @BenjaminZekavica. I was able to replicate using Chrome, in case it's browser-specific.

**Comment by gziolo** [comment]
It was fixed in https://github.com/WordPress/gutenberg/pull/17887.
