### ISSUE TITLE
Changelog link for packages readme

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#16533]
As the NPM Packages are part of the Gutenberg repo the packages on npmjs link to the Gutenberg repo.

This makes it more difficult to find the changelogs. For example: https://www.npmjs.com/package/@wordpress/components

By linking the changelog in the readme anyone can access the changelog directly from the npmjs website.

**Comment by swissspidy** [comment]
Worth noting that the "homepage" link directly links to the component's readme. From there the changelog is only two clicks away.

![Screenshot 2019-07-11 at 14 23 25](https://user-images.githubusercontent.com/841956/61050547-8a070700-a3e7-11e9-9615-920beb117b6f.png)

**Comment by gziolo** [comment]
Yes, I think that I always navigate from npm to the repository through the link that @swissspidy highlighted. I think it’s the standard approach. The could maybe automate it on the npm side one day 😃
