### ISSUE TITLE
Add Post Type to hyperlinks search window

### ISSUE THREAD

**Issue by edwinhamers** [WordPress/gutenberg#16534]
WordPress, before Gutenberg, used to show the post type (page/post) within the search for hyperlink. Can this be added?

**Before Gutenberg links**
![image](https://user-images.githubusercontent.com/3518216/61045921-27f4d480-a3dc-11e9-9c48-fdaf0398be6a.png)

**After Gutenberg**
![image](https://user-images.githubusercontent.com/3518216/61045939-36db8700-a3dc-11e9-8544-c6be8529c203.png)

**Comment by swissspidy** [comment]
Related: #13641

**Comment by sarahmonster** [comment]
Many users often don't understand the distinction between different post types, so providing this information isn't always helpful. For power users who are more likely to make use of custom post types, this information is likely to be more relevant. The trick here is to determine a way of providing this information only when it's helpful to users, and avoid revealing information that contributes to complexity of the interface when it isn't helpful.

One approach would be to provide this distinction only when it's contextually relevant and will help users make a more confident choice, only showing the post type when there are two results with the same title. There are some mockups that relate to/directly address this on #8573.

**Comment by myosotisgit** [comment]
> Many users often don't understand the distinction between different post types, so providing this information isn't always helpful. For power users who are more likely to make use of custom post types, this information is likely to be more relevant. The trick here is to determine a way of providing this information only when it's helpful to users, and avoid revealing information that contributes to complexity of the interface when it isn't helpful.
> 
> One approach would be to provide this distinction only when it's contextually relevant and will help users make a more confident choice, only showing the post type when there are two results with the same title. There are some mockups that relate to/directly address this on #8573.

Looks good in those other issues. Maybe close this issue and keep working on it in the other ones?

**Comment by skorasaurus** [comment]
Thanks for reporting. 
This has been added into Gutenberg and the Block editor.
