### ISSUE TITLE
Gutenberg 6.1.0 breaks the customizer ( blank screen ) after deactivation of the plugin

### ISSUE THREAD

**Issue by Nikeo** [WordPress/gutenberg#16538]
Hi guys, after playing a little bit with the latest widget block in the customizer, I could not access the customizer anymore.
I tested several times on a fresh WP install, and could reproduce the problem.
Here's the detailed problem + screenshot.

**Describe the bug**
After activating Gutenberg plugin ( v6.1.0 ), doing some customizations, and deactivating Gutenberg, it is not possible to customize the site anymore. 
The customizer preview frame is blank. And the console log displays the error : _Uncaught SyntaxError: Unexpected token <_

In the Html code of the page, the PHP error is 

> <br />
> <b>Warning</b>:  array_intersect(): Argument 1 is not an array in <b>/srv/www/wp-betas/htdocs/wp-includes/class-wp-customize-widgets.php</b> on line <b>1380</b><br />
> <br />
> <b>Warning</b>:  array_values() expects parameter 1 to be array, null given in <b>/srv/www/wp-betas/htdocs/wp-includes/class-wp-customize-widgets.php</b> on line <b>1380</b><br />

**To reproduce**
Start from a fresh install ( not mandatory ) with the latest WP version
1. Activate the Twenty Nineteen theme
2. Activate Gutenberg latest version
3. Open the customizer
4. Open the Homepage settings ( Screenshot 1 )
   - select "A static page" and pick "Sample page"
   - publish
   - exit the customizer
5. deactivate Gutenberg plugin
6. open the customizer : you should see a blank screen with a console.log error : Screenshot 2 and 3

**Expected behavior**
The customizer should work after deactivating Gutenberg.

**Screenshots**
### Screenshot 1
![2019-07-11_15-27-51](https://user-images.githubusercontent.com/3038156/61055760-76ad6900-a3f2-11e9-800a-9d1dcada2207.jpg)

### Screenshot 2
![2019-07-11_15-28-40](https://user-images.githubusercontent.com/3038156/61055766-790fc300-a3f2-11e9-90b5-b3f62012dd64.jpg)

### Screenshot 3
![2019-07-11_15-29-03](https://user-images.githubusercontent.com/3038156/61055803-8b89fc80-a3f2-11e9-9011-e283e9e3535d.jpg)

**Desktop :**
 - OS: Windows
 - Browser : chrome
 

**Additional context**
- Gutenberg v6.1.0
- WordPress v5.2.2
- Twenty Nineteen v1.4

Thanks

**Comment by epiqueras** [comment]
Fixed in #16544 .

**Comment by Nikeo** [comment]
@epiqueras in your fix, from what I understand, you prevent the problem from happening. But what about websites that have been broken already ? 
Can you confirm that this fix will "clean" the broken widgets, and then allow users to disable Gutenberg and let them open the customizer without activating Gutenberg permanently again ?
