### ISSUE TITLE
If text color and heading color are set to white in Appearance >> Customize >> Typography, the text is also white when editing pages making the text invisible

### ISSUE THREAD

**Issue by grigorijurasov** [WordPress/gutenberg#16537]
**Describe the bug**
If text color and heading color are set to white in Appearance >> Customize >> Typography (that might be necessary if the site background color is black) - the text is also white when editing pages making the text invisible.

**To reproduce**
1. Go to Appearance >> Customize >> Typography 
2. Set the text color and heading color to white and publish.
3. Head back to wp-admin >> Pages and open a random page
4. See the error

**Expected behavior**
I'd expect either the text to remain black on white background in page editor, or to see the background of the same color as the page so that the text is readable/editable.

**Screenshots**

<img width="293" alt="Screenshot 2019-07-11 at 16 23 21" src="https://user-images.githubusercontent.com/13084901/61054951-2980c580-a3f9-11e9-9dc6-2dcab2ebd590.png">

<img width="984" alt="Screenshot 2019-07-11 at 16 23 07" src="https://user-images.githubusercontent.com/13084901/61054960-2dace300-a3f9-11e9-8c58-c99b7051f800.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 75.0.3770.100

**Additional context**
- WordPress 5.2.2

**Comment by swissspidy** [comment]
`Appearance >> Customize >> Typography` is not a core feature of WordPress.

If your theme adds options like these, it is also responsible for adding the necessary style changes to the block editor.
