### ISSUE TITLE
Media Library: Sometimes items don't load.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1653]
It's hard to give steps to reproduce, but I know for a fact that you need _a media library with a bunch of images_. I also use WP Docker (so it's nginx under the hood), this could possibly be related.

What happens is, _most of the time_ when I insert an image or gallery, items in the media library load fine. 

But some times, the media library appears to be empty, even though clicking the media library item in the sidebar shows I have items. Perhaps there's a race condition somewhere?

Trackig so others can hopefully add reproducible steps.

**Comment by westonruter** [comment]
I'm seeing the `post_mime_type` query parameter being set incorrectly. Working on a fix…

![image](https://user-images.githubusercontent.com/134745/27810680-43221b42-6012-11e7-81fd-e2b42e1b861a.png)
