### ISSUE TITLE
GB 6.1.0 Gives White Screen When Adding Posts or Pages

### ISSUE THREAD

**Issue by VR51** [WordPress/gutenberg#16553]
Probably connected to #16518 and #16502.

There is also an issue report on WordPress.org at https://wordpress.org/support/topic/creating-new-post-editing-existing-blank-page/

WordPress displays a white screen when adding a new post or page using Gutenberg version 6.1.0.

Appears to be a conflict with other plugins, Jetpack seems to be the main culprit. Console shows an error for Social Pug when GB 6.1.0 is enabled, which may be a coincidental error.

Console output with the Gutenberg 6.1.0 plugin enabled shows the following:

```
23:57:21.928 jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
23:57:22.280 index.js?ver=1562808508:1 wp.editor.withColors is deprecated and will be removed. Please use wp.blockEditor.withColors instead.
r @ index.js?ver=1562808508:1
23:57:22.945 gutenberg-image-pinterest-pro.js?ver=2.7.0:41 Uncaught TypeError: Cannot read property 'from' of undefined
    at register_block_attributes_image_pinterest (gutenberg-image-pinterest-pro.js?ver=2.7.0:41)
    at index.js?ver=1562808508:1
    at index.js?ver=1562808508:2
    at Array.map (<anonymous>)
    at ne (index.js?ver=1562808508:2)
    at index.js?ver=1562808508:14
    at Array.forEach (<anonymous>)
    at Sc (index.js?ver=1562808508:14)
    at Object.so (index.js?ver=1562808508:12)
    at HTMLDocument.<anonymous> (post-new.php:610)
23:57:22.952 timer.js:129 Started
23:57:25.921 ?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6
00:02:15.247 jquery.js:3 [Violation] 'resize' handler took 350ms
00:02:15.262 [Violation] Forced reflow while executing JavaScript took 346ms
```

With Gutenberg disabled:

```
00:10:48.620 jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
00:10:52.821 timer.js:129 Started
00:10:53.925 ?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6
```

The version of Gutenberg available from GitHub ([up to this commit](https://github.com/WordPress/gutenberg/commit/cb718ffdff57e35f05f4239ff03ceb476ae69a86)) works but deleting the line ```defined( 'GUTENBERG_DEVELOPMENT_MODE' ) or define( 'GUTENBERG_DEVELOPMENT_MODE', true );``` causes the editor page white screen to show again.

**Comment by talldan** [comment]
Thanks creating the issue @VR51. It should be fixed by #16518, so I'll close this.

**Comment by VR51** [comment]
Thank you @talldan.

**Comment by talldan** [comment]
My understanding is there should be a v6.1.1 released today that you'll be able to upgrade to, and that will include the fixes.

**Comment by VR51** [comment]
6.1.1 seems to work well so far. Thank you again.
