### ISSUE TITLE
6.1.0 - "Open link in new tab"  Link Option doesn't Persist on Chrome

### ISSUE THREAD

**Issue by puddinman** [WordPress/gutenberg#16550]
**Describe the bug**
publishing a post on Chrome resets the 'Open in New Tab' option.

**To reproduce**
1.  Go to a post page
2. Add  a paragraph block to a page
3. Add some text and a link with the "Open link in new tab" setting enabled
4. Confirm Link opens in new tab
5. Reload editor page, confirm  "Open link in new tab" link setting isn't enabled
6. Click the update(publish) button
7. Link no longer opens in new tab

**Expected behavior**
Setting should persist when set

**Screenshots**
![Screen Shot 2019-07-11 at 2 50 52 PM](https://user-images.githubusercontent.com/44071383/61087726-51692c80-a3eb-11e9-8edb-5df88dde94ee.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 75.0.3770.100

**Comment by talldan** [comment]
Hi @puddinman Thanks for the report. I tried to reproduce this one following your steps but couldn't. The Open In New Tab option continued to be enabled after reloading the page.

Which versions of WordPress / Gutenberg are you using?
