### ISSUE TITLE
Onboarding popup overlaps everything

### ISSUE THREAD

**Issue by drawcard** [WordPress/gutenberg#16555]
**Describe the bug**
The onboarding popup overlaps everything on screen (if it is not dismissed prior). Here's an example of the popup overlapping the media library. It's not a critical bug, but it's a bit confusing coming across it for the first time.

**Correct display**
![image](https://user-images.githubusercontent.com/1435638/61095169-7e701a80-a491-11e9-8442-d3b7943f90ab.png)

**Incorrect display**
![image](https://user-images.githubusercontent.com/1435638/61095083-33560780-a491-11e9-929e-25eca42b9726.png)

**To reproduce**
1. New install of Wordpress 5.2.2
2. Create a new post with supplied Gutenberg editor
3. Do something, like attempt to set a featured image

**Expected behavior**
The popup should not cover all UI elements.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
