### ISSUE TITLE
Updating failed when page includes iframe embed or link with certain characters

### ISSUE THREAD

**Issue by versatilehuman** [WordPress/gutenberg#16568]
**Describe the bug**
Updating fails ("Updating failed" error at top) when opening a page (or attempting to publish) that contains an iframe similar to this:

`<iframe src="https://www.google.com/maps/embed?pb=!4v1562947928310!6m8!1m7!1sCAoSLEFGMVFpcE5nM2NvRnhDSmFvd01penJTMlFYWGpNYnhBWGJtNFV2MkhzY1Zu!2m2!1d42.0457382!2d-88.01853179999999!3f155.1384358334455!4f-10.163745588698475!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>`

or a link that contains these characters: `+%26+`

**To reproduce**
1. Edit a page
2. Add iframe code above to customHTML block
3. Attempt to publish
4. See "Updating failed" error

**Expected behavior**
No error, able to publish. 

**Console errors**
```
Failed to load resource: the server responded with a status of 403 ()
/wp-json/wp/v2/pages/628?_locale=user:1 

POST https://XXXX/wp-json/wp/v2/pages/628?_locale=user 403
api-fetch.min.js?ver=3.1.2:1 

_ @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
O @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
t.(anonymous function) @ api-fetch.min.js?ver=3.1.2:1
n @ api-fetch.min.js?ver=3.1.2:1
u @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
x @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
u @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
x @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
e @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
u @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
(anonymous) @ api-fetch.min.js?ver=3.1.2:1
P @ api-fetch.min.js?ver=3.1.2:1
API_FETCH @ editor.min.js?ver=9.2.6:17
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
Promise.then (async)
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
e @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
t @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ redux-routine.min.js?ver=3.2.0:1
(anonymous) @ editor.min.js?ver=9.2.6:17
(anonymous) @ editor.min.js?ver=9.2.6:17
(anonymous) @ data.min.js?ver=4.4.0:1
value @ data.min.js?ver=4.4.0:1
onClick @ editor.min.js?ver=9.2.6:17
sh @ react-dom.min.js?ver=16.8.4:164
rh @ react-dom.min.js?ver=16.8.4:13
uh @ react-dom.min.js?ver=16.8.4:13
Ge @ react-dom.min.js?ver=16.8.4:15
vh @ react-dom.min.js?ver=16.8.4:165
ad @ react-dom.min.js?ver=16.8.4:15
cd @ react-dom.min.js?ver=16.8.4:17
Uh @ react-dom.min.js?ver=16.8.4:39
Zg @ react-dom.min.js?ver=16.8.4:158
Xe @ react-dom.min.js?ver=16.8.4:23
oc @ react-dom.min.js?ver=16.8.4:40
(anonymous) @ react-dom.min.js?ver=16.8.4:159
unstable_runWithPriority @ react.min.js?ver=16.8.4:27
ah @ react-dom.min.js?ver=16.8.4:159
xf @ react-dom.min.js?ver=16.8.4:40
```

**Devices**
Occurred on desktop and mobile on multiple networks.
 - OS: Windows 10
 - Chrome 69.0.3497.100

 - Device: iPhone 6S
 - OS: iOS12.1.2

**Additional context**
- WordPress 5.2.2

**Comment by swissspidy** [comment]
Works just fine here.

Have you tried installing the latest version of the Gutenberg plugin?
Have you tried disabling all other plugins and switching to one of the default themes to see if this still happens?

**Comment by versatilehuman** [comment]
Thank you. Yes, I tried the standard testing and it still occurs. I set up a staging site with the only difference between the two being a Sucuri firewall and the domain. Looks like there is some issue there.

**Comment by dbotti** [comment]
I have seen this issue as well on a few sites with a Sucuri firewall.  Where the IP is whitelisted there is not an issue, but other users cannot make edits to the page because it can't be updated.  In Google chrome, seeing a status 403 forbidden for api-fetch.min.js?ver=3.1.2:1 and /wp-json/wp/v2/pages/ when trying to update.  May be similar to this issue too? [14835](https://github.com/WordPress/gutenberg/issues/14835)

**Comment by ercanertan** [comment]
with my experience , this is related to cookie plugin..

**Comment by dbotti** [comment]
For the cases I have seen I have confirmed that Sucuri firewall is blocking access to the url  /wp-json/wp/v2/pages/ for updates when there is an iframe used to embed content.

**Comment by versatilehuman** [comment]
Update:
I disabled security headers in the Sucuri Firewall that potentially blocked iframes in a custom HTML block. No luck. 

In fact, I'm now getting this warning when loading the page (or post) editing screen, without performing any action:

> api-fetch.min.js?ver=3.6.4:1 GET https://XXXX/wp-json/wp/v2/users/me?_locale=user 403
> N @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> s @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> forEach.t.<computed> @ api-fetch.min.js?ver=3.6.4:1
> n @ api-fetch.min.js?ver=3.6.4:1
> c @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> (anonymous) @ api-fetch.min.js?ver=3.6.4:1
> w @ api-fetch.min.js?ver=3.6.4:1
> etc...
> 
> 
> data.min.js?ver=4.9.2:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}code: "invalid_json"message: "The response is not a valid JSON response."__proto__: Object
> n @ data.min.js?ver=4.9.2:1
> a @ data.min.js?ver=4.9.2:1
> Promise.then (async)
> n @ data.min.js?ver=4.9.2:1
> c @ data.min.js?ver=4.9.2:1
> (anonymous) @ data.min.js?ver=4.9.2:1
> (anonymous) @ data.min.js?ver=4.9.2:1
> s @ data.min.js?ver=4.9.2:1
> a @ data.min.js?ver=4.9.2:1
> u @ data.min.js?ver=4.9.2:1
> (anonymous) @ editor.min.js?ver=9.7.5:11
> e @ data.min.js?ver=4.9.2:1
> (anonymous) @ data.min.js?ver=4.9.2:1
> r @ data.min.js?ver=4.9.2:1
> (anonymous) @ editor.min.js?ver=9.7.5:11
> (anonymous) @ data.min.js?ver=4.9.2:1
> Tt @ data.min.js?ver=4.9.2:1
> (anonymous) @ data.min.js?ver=4.9.2:1
> etc...

I'm reaching out to Sucuri, but any insight on potential conflicts?

**Comment by versatilehuman** [comment]
This Sucuri specific issue (other firewalls may conflict, but I don't have direct experience) can be resolved by whitelisting specific user IP addresses or whitelisting parts of URLs that are being blocked through Sucuri.
