### ISSUE TITLE
Define allowed inner blocks in register of block type

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#16560]
As detailed in https://github.com/WordPress/gutenberg/issues/13955 there is currently no way to filter the allowed block in a inner block area. Allowed blocks are stored in a none filterable array variable. See these examples. 
- [Columns block](https://github.com/WordPress/gutenberg/blob/855be7927f31cf89229e954829e78e23d6a871e8/packages/block-library/src/columns/edit.js#L47)
- [Media & text block](https://github.com/WordPress/gutenberg/blob/a95d5de3bcb6afaa9b50a672f89cae4802575571/packages/block-library/src/media-text/edit.js#L36)
- [Cover](https://github.com/WordPress/gutenberg/blob/84543ff908fab4f88c45e42e656b553afa4fdd48/packages/block-library/src/cover/edit.js#L57)

Even finding which blocks are available requires you to dig through code.  

**Describe the solution you'd like**
The allowed inner block should be defined when the block is registered. A new `children` or `innerBlocks` field could be added when a block is registered. This would mean, that this information would be available to all parts of gutenberg. This data could be exposed in the up coming blocks api, as this data would be useful to the mobile team.  

Following the naming pattern of `children` would match with existing `parent` field for child block, already found in gutenberg.

**Comment by spacedmonkey** [comment]
I spent on sometime today. What I worked on was the following. 

Added a new field called `innerBlocks` in the block.json file for cover, media + text and columns. 

In the edit function, I type to get the block type so I could read the innerBlock values and as attributes to Innerblocks. However, it didn't work, as blockType was not yet defined. I wanted to `blocks.registerBlockType` to make the innerblock values filterable. 

Next port of call, is to make the args to innerblock type filterable. But I don't love this solution.

**Comment by chriscasper** [comment]
Any update to this?

**Comment by skorasaurus** [comment]
> Any update to this?

@chriscasper this is being worked on at https://github.com/WordPress/gutenberg/pull/58262

**Comment by jsnajdr** [comment]
Reading @spacedmonkey's notes from 5 years ago, it's notable how much Gutenberg has changed since then. Today it was a very straightforward addition, there's no problem accessing `blockType.children` everywhere I need it.

**Comment by skorasaurus** [comment]
This has been merged into trunk with https://github.com/WordPress/gutenberg/pull/58262 ; documentation for this is available at https://github.com/WordPress/gutenberg/blob/b48d66e231193dc11978ce6b71f882ee93313ad9/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md#defining-a-children-block-relationship
