### ISSUE TITLE
WordPress 4.9: Consider "Try Gutenberg" dashboard notice

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1656]
This is more of a meta ticket. It's been suggested that Gutenberg could reach WordPress in version 5.0. What form exactly this would take (opt-out?) has yet to be discussed. But even prior to that, reaching WordPress hinges upon [the plugin](https://wordpress.org/plugins/gutenberg/) getting a huge amount of installs; 100.000 has been suggested.

Should we explore putting a dismissable dashboard notice in WordPress 4.9, that says "Try a preview of the new WordPress editor", which when clicked would allow you to install the plugin?

**Comment by buzztone** [comment]
While we probably can't say at this stage if 100,000 active installs is realistically achievable, it's certainly a worthwhile target in my opinion. While 10,000 - 20,000 (currently 1000+) might be sufficient to get widespread usage & feedback, 100,000 active installs would demonstrate support within the community for the advantages Gutenberg offers.

For comparison I'd be interested to see how many downloads [MP6](https://wordpress.org/plugins/mp6/) had before it was merged. MP6 certainly had a significant number of users & a very extensive review process. I believe this contributed significantly to acceptance of the MP6 changes when merged. As I recall I was using the MP6 plugin on many sites, before it merged, for the advantages it offered.

[Shiny Updates](https://wordpress.org/plugins/shiny-updates/) was another feature plugin that I was already using on most sites before it merged. This gave me direct first hand confirmation that Shiny Updates worked & I just waited patiently for the merge into core.

**Comment by hedgefield** [comment]
I'd be all for it. We were otherwise planning to write a little plugin that sets Gutenberg as default so our content team can get used to it and provide feedback.

**Comment by melchoyce** [comment]
> Should we explore putting a dismissable dashboard notice in WordPress 4.9, that says "Try a preview of the new WordPress editor", which when clicked would allow you to install the plugin?

I think we could even get this into the next point release.

**Comment by jasmussen** [comment]
This is done! Hooray!
