### ISSUE TITLE
Copying into a block quote from keynote brings in code

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16572]
![2019-07-12 at 22 04](https://user-images.githubusercontent.com/253067/61158615-6334f780-a4f1-11e9-8d6a-adfaf7404049.png)

As you can see from this image, it looks like there is no stripping happening causing this to bring in the font styling for example.

**Comment by ellatrix** [comment]
Hi Tammie! :)

Could you share what the console is logging for you when you paste?

I'm looking for this:

<img width="657" alt="Screenshot 2019-08-07 at 10 53 18" src="https://user-images.githubusercontent.com/4710635/62609234-ac664480-b901-11e9-972a-7383ec88b930.png">

Please copy the text and paste it in between backticks:
````
```
content
```
````

Thank you!

**Comment by karmatosed** [comment]
I just retested this and I think it can be closed as works now - yay!

![image](https://user-images.githubusercontent.com/253067/69885518-76e0cf00-12d5-11ea-9161-3d20b106e973.png)
