### ISSUE TITLE
Popover Component Y axis Broken When Combined With CSS animation 

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#16596]
**Describe the bug**

When a popover component appears, it has a `top:` CSS style applied dynamically, ensuring it appears in the correct place with the right alignment.

So, I loaded the block list and provider components on my sites frontend via a plugin. This site has a CSS animation that fades in the content and moves it upwards into place.

During this animation, calculations are done, and used as the basis for the `top` value, resulting in the inserter and popover components appearing further up the page. Additionally the `top` value changes depending on the scroll position. When at the top of the page, `top` contains the full height of the page in pixels. At the bottom of the page, `top` contains a low value, ( 32px IIRC, likely the height of the admin bar ). As a result the only way to view the component is to scroll to the middle of the page and watch it move past in the opposite direction.

Replacing the fade in and up animation with a fade in animation resolved the problem, but it would be better to account for this.

**To reproduce**
1. Install and active https://github.com/tomjn/block-comments
2. Activate a theme with a CSS transition on page load that involves movement of the containing div
3. Attempt to use a popover component such as the inserter in the comment form

**Expected behavior**

I expected the inserter to appear in the same location it would if used in the post editor

I tested this in Chrome 75 and Firefox 67 on MacOS Mojave

**Additional context**
- Tested with Gutenberg 6.1

**Comment by paaljoachim** [comment]
Hey Tom

Is this issue still relevant? If so what can do to to move it onward?

**Comment by tomjn** [comment]
No idea, I think that the way popovers work and even the component used has changed completely since this issue was written
