### ISSUE TITLE
Oversized Toolbar Icons

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#16597]
**Describe the bug**

When instantiating a basic editor using the block list and provider components, toolbar icons can appear oversized in some Admin and frontend contexts

<img width="376" alt="Screenshot 2019-07-15 at 21 47 09" src="https://user-images.githubusercontent.com/58855/61248013-21eb5480-a74a-11e9-8e32-d5ffe62e0689.png">

I expected this:

<img width="359" alt="Screenshot 2019-07-15 at 21 47 38" src="https://user-images.githubusercontent.com/58855/61248040-32033400-a74a-11e9-8091-26fa30b76b25.png">

I've temporarily corrected the behaviour by applying a `max-width` and `max-height` of `20px` to `.components-toolbar__control.components-button > svg` but this doesn't explain the discrepancy and is a crude fix.

Reproduced in Chrome 75 and Firefox 67 on MacOS Mojave in Gutenberg 6.1.

**Comment by youknowriad** [comment]
I wonder if we're relying on some Core CSS that is not available in other contexts?

**Comment by tomjn** [comment]
Most likely, the same thing happens on term edit pages and various other WP Admin screens so it isn't isolated to frontend instances.

Here's what happens if you swap out the term description textarea for a block list based editor:

<img width="834" alt="Screenshot 2019-05-22 at 20 02 50" src="https://user-images.githubusercontent.com/58855/61291087-5c460780-a7c5-11e9-9968-fb83e7f10b6d.png">
 non-WP Admin contexts

The containing div has some padding and a border but nothing else. Of note, whatever is making the icons appear correct for the post editor is enqueued by Frontenberg

**Comment by mtias** [comment]
We have a lot more examples now of embedded editors where things work as expected. The design has also changed and toolbar components reconciled regarding sizes. Please, reopen if you still run into issues.
