### ISSUE TITLE
Widgets: When no changes are needed, Update btn should be disabled

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16605]
In the new widgets screen, the "Update" button should be disabled if there are no changes. Right now it's always in it's primary state, even when I haven't made any changes. This makes me think that maybe my update didn't save correctly.

![Screen Shot 2019-07-15 at 3 26 58 PM](https://user-images.githubusercontent.com/617986/61253292-5395f880-a715-11e9-8be1-300b24382555.png)

Can we change it to be disabled?

![Screen Shot 2019-07-15 at 3 29 46 PM](https://user-images.githubusercontent.com/617986/61253323-76281180-a715-11e9-9661-9fe4c1a553fc.png)

**Comment by karmatosed** [comment]
+1 for this. It's really weird having it show when you can't update.
