### ISSUE TITLE
Widgets: Blocks areas need width/padding adjustments

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16600]
Some width and padding adjustments can help the new widgets screen visually.

The new widgets screen shows blocks areas in a narrow column that's set to `max-width:610px` and it also includes a large amount of padding on the left/right sides of the blocks.

**Solutions**

1. Change the `max-width` of `.edit-widgets-widget-area` to `700px` instead of `610px`.
    Proposed:
    `.edit-widgets-widget-area { max-width: 700px; }`

2. Remove the padding on left/right side of `.block-editor-block-list__layout` for this screen.
    Proposed:
    ~`.block-editor-block-list__layout { padding-left:46px; padding-right:46px; }`~

----

**Current appearance:**

![Screen Shot 2019-07-15 at 2 05 35 PM](https://user-images.githubusercontent.com/617986/61249553-62c37900-a70a-11e9-88b7-096a83e6f552.png)

**Proposed appearance:**

![Screen Shot 2019-07-15 at 2 05 00 PM](https://user-images.githubusercontent.com/617986/61249588-7a9afd00-a70a-11e9-8474-715dce2f8369.png)

**Comment by karmatosed** [comment]
Thanks for reporting this. I agree so much it's better with less padding. I do wonder though, could you go a step further? What about aligning the edge to the text and arrow? Would that be too big a block space?

**Comment by mapk** [comment]
Here's an example of the blocks being wider.

![Screen Shot 2019-07-24 at 7 09 16 AM](https://user-images.githubusercontent.com/617986/61800538-1222de80-ade2-11e9-94f9-0a12d54e7fa1.png)


The block UI starts falling outside the Block Area. The additional padding on the left/right sides help keep this UI inside and mimic more of the Editor "feel" here. Let's keep the proposed appearance in the early mockup.

**Comment by karmatosed** [comment]
> The block UI starts falling outside the Block Area.

Ah good catch, in that case 100% agree with more padding.
