### ISSUE TITLE
Widgets: In Customizer the widget-blocks interface are also missing the block appender button

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16607]
[As in the new widget wp-admin screen](https://github.com/WordPress/gutenberg/issues/16601), let's add the block appender button to the widget-blocks in the Customizer as well. This particular appender will need to change from "Add a block" to "Cancel". See below.

![appender](https://user-images.githubusercontent.com/617986/61255452-7cba8700-a71d-11e9-86a4-b6c241e0e279.gif)

**Comment by karmatosed** [comment]
My only ponder here is I am not sure changing the appender to say cancel isn't confusing. Is there any other option of where to put cancel?

**Comment by mapk** [comment]
I would agree @karmatosed, but I was trying to implement something similar to today's Customizer interaction to keep the development overhead minimal.

**Current Customizer Interaction**

![widgets](https://user-images.githubusercontent.com/617986/62498034-b0278900-b792-11e9-8322-f6d55f43d22c.gif)

**Comment by karmatosed** [comment]
Ah ok, I didn't think it was reusing the Customizer code, if that's case then it makes sense. If it's not then adding a cancel seperate I think is an experience improvement.

**Comment by jorgefilipecosta** [comment]
I'm closing this issue as currently, the customizer contains a block appender button it uses the same code as the widgets screen and the block appender is also available there now.
