### ISSUE TITLE
Widgets: The block's toolbar is protruding offscreen in the Customizer

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16608]
The block's toolbar is protruding offscreen in the Customizer. This will be fixed if we conform the interface to the mobile web view of Gutenberg as requested in https://github.com/WordPress/gutenberg/issues/16606.

![Screen Shot 2019-07-15 at 4 29 47 PM](https://user-images.githubusercontent.com/617986/61255572-02d6cd80-a71e-11e9-9fa0-158f6c16ea3f.png)

**Comment by karmatosed** [comment]
I can also replicate this. I second using mobile interface, there just isn't space otherwise.

**Comment by noisysocks** [comment]
This is still an issue.

<img width="320" alt="Screen Shot 2020-08-14 at 14 31 13" src="https://user-images.githubusercontent.com/612155/90214088-d0c0ff00-de3a-11ea-9e42-b12f56317cbc.png">

**Comment by draganescu** [comment]
Is this still an issue considering that on the customiser view will always display the toolbar at the top like we do on mobile viewports? cc @mapk

**Comment by draganescu** [comment]
I think #25201 makes this obsolete.
