### ISSUE TITLE
Widgets: Update the Customizer view of widget-blocks to look like the mobile web version of Gutenberg

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16606]
Currently, the new Customizer interface for widget-blocks is showing what we see in the wp-admin screen, but in the narrow Customizer interface. It makes the interface difficult to parse and understand. Let's update this to look like the prototype and use the mobile web version of Gutenberg here.

In order to do this, it was suggested to use a global class to help force the media queries. Can we make this happen? It will lead to a much better experience.

**Proposed solution:** Also presented in the [original issue](https://github.com/WordPress/gutenberg/issues/13205#issuecomment-477816658).

![Widget blocks in Customizer 01 Preview Mode   InVision](https://user-images.githubusercontent.com/617986/61255254-9b6c4e00-a71c-11e9-9ca5-1b7a94b0134f.png)

**Comment by karmatosed** [comment]
If it is possible to get this to work for mobile display that would be far better. The current experience is really not working so well in the smaller space.

**Comment by ZebulanStanphill** [comment]
Since #22533 was merged, I guess this issue can be closed now?

**Comment by mapk** [comment]
I _think_ so. There are few UI and UX issues that I'll link to this one, but we can close it.
