### ISSUE TITLE
Widgets: The Legacy Widget block has options that are out of context

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16604]
When adding a Legacy Widget block to the Block Area, the user is presented with a select box to select a widget. When I click on that, the options don't make sense.

![Screen Shot 2019-07-15 at 3 13 55 PM](https://user-images.githubusercontent.com/617986/61252874-efbf0000-a713-11e9-8b24-ddad96c4e6f0.png)

1. If I don't have any widgets, maybe I shouldn't be able to see this Legacy Widget block? It could cause some confusion.
2. I'm not sure what the option "block area" does? But it returned this result.

![Screen Shot 2019-07-15 at 3 20 13 PM](https://user-images.githubusercontent.com/617986/61252974-49272f00-a714-11e9-9232-9ba19ebac868.png)

**Comment by karmatosed** [comment]
I think this is going to be fixed with scripts, or that was my understanding @youknowriad? The ideal is yes to not have legacy widget show like this.
