### ISSUE TITLE
<MediaUpload /> How to retrive image title, alt & description?

### ISSUE THREAD

**Issue by mathishuettl** [WordPress/gutenberg#16613]
Hello,

I use the <MediaUpload /> component. When i log the output in the onSelect callback I can't find the title tag. Only the alt & caption are there. How can I get alt, title & description for an image?

**Comment by mathishuettl** [comment]
I found a solution ... is that a good one? 

I use the HOC withSelect to get all the image-details:
```
export default withSelect( ( select, ownProps ) => {
	const { getMedia } = select( 'core' );
	const { id } = ownProps;

    let img = id ? getMedia(id) : null;

	return {
		image: img,
	};
} )( GalleryImage );
```

And in the ComponentDidUpdate I retrive the author (description)
```
componentDidUpdate() {
        const { image, author, setAttributes } = this.props;

        if (image && !author && !this.state.gotAuthor ) {
            setAttributes( { author: image.description.raw, } );
            this.setState( { gotAuthor: true } );
        }
    }
```

**Comment by youknowriad** [comment]
That's a great one :)

**Comment by andfinally** [comment]
For anyone else looking for this functionality, when the user selects an image, `onSelect` now returns an object including alt, author, caption and other useful details.

**Comment by anteksiler** [comment]
@andfinally I am not able to retrieve the width and height attributes to pass to responsiveWrapper
