### ISSUE TITLE
Custom block update rendering when reused

### ISSUE THREAD

**Issue by nicpelletier** [WordPress/gutenberg#16614]
I developed a custom (Gutenberg) block that have to update is content on almost every block manipulation on the block editor.

It works great, mostly: i "listen" to changes with a `wp.data.subscribe` function and update the block attributes with `wp.data.dispatch( 'core/block-editor' ).updateBlockAttributes`.

The problem is that the blocks stop updating when converted to a reusable block or put in one (like a reusable group). It's fine in the reusable block manager, but the feature that let you edit a reusable block inside the post it is used on is like a frame that don't fire my wp.data.subscribe function.

How do i check for modifications in this "window" and update blocks inside it?

It's just a backend problem. The client side rendering is dynamic so it works fine.

I've searched a lot, and asked here ( where you can also find the code) : https://wordpress.stackexchange.com/questions/342753/custom-block-update-rendering-when-reused.

I'm an experienced WP developer, but pretty new to React so sorry if my vocabulary is off...

Thank you,

**Comment by youknowriad** [comment]
yes, I don't see how this problem could be solved because the reusable blocks work on a separate data module registry. I believe ideally the inline-editing for reusable blocks should be refactored or removed in favor of links to the edit page of reusable blocks potentially.
