### ISSUE TITLE
Move buttons are hard to use within a nested block

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#16617]
**Describe the bug**
Using a meda+text block, its hard to move the paragraphs around without actually focusing on them — the move buttons appear when hovered, but you can't actually interact with them. Here's a GIF that hopefully helps you understand the problem:

![confusing buttons](https://user-images.githubusercontent.com/191598/61314637-12f8b680-a7cb-11e9-9125-629b2e0baadb.gif)

Alternatively, sometimes the opposite is true — the move buttons get in the way of resizing the image. Here's another GIF:

![confusing buttons 2](https://user-images.githubusercontent.com/191598/61314775-5fdc8d00-a7cb-11e9-809b-3c15a4fd0dae.gif)

The behavior seems to change depending on what block you currently have focused, but I can't seem to understand the logic behind the change.

**Comment by mapk** [comment]
Talked about this in [today's design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1563897921026900).

Let's explore an option to only show the move icons when the block is selected. Although I feel like this is a workaround, it may be the workaround we need. A `try/` PR could help communicate this.

Related: https://github.com/WordPress/gutenberg/issues/16718 and kind of https://github.com/WordPress/gutenberg/issues/16646

**Comment by mapk** [comment]
Another related issue with weirdness around these controls:
https://github.com/WordPress/gutenberg/issues/16742

**Comment by karmatosed** [comment]
Another issue with spacer:

![68587735-ad1df200-047f-11ea-860a-0afd7cf9ac46](https://user-images.githubusercontent.com/253067/68605746-d8ff9e80-04a4-11ea-91c5-3097ff3a36a1.png)

**Comment by karmatosed** [comment]
I think this can be solved as part of the iterations here: https://github.com/WordPress/gutenberg/issues/18667

**Comment by jasmussen** [comment]
Yes, this would definitely be fixed by #18685!
