### ISSUE TITLE
Icon of anchor is not shown in the Block Editor

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#16621]
When we use anchors in a post, the icon indicating that there is an anchor is not shown in the Block Editor (view mode), in the Classic Editor there is no such problem.

Exemplifying with the following code:

```
<!-- wp:heading {"level":3} -->
<h3>Index:</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><a href="#title1">Title 1</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#title2"> Title 2</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph --><!-- /wp:paragraph -->

<!-- wp:separator --><hr class="wp-block-separator" /><!-- /wp:separator -->

<!-- wp:heading {"level":3} -->
<h3><a name="title1"></a> Title 1</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse egestas risus sit amet accumsan consectetur. Aenean eget velit in lorem congue suscipit et eget nulla. Nunc id sapien quam. Fusce laoreet et ligula in volutpat. Cras id dolor a massa molestie varius at in ante.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><a name="title2"></a> Title 2</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse egestas risus sit amet accumsan consectetur. Aenean eget velit in lorem congue suscipit et eget nulla. Nunc id sapien quam. Fusce laoreet et ligula in volutpat. Cras id dolor a massa molestie varius at in ante.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} --><!-- /wp:paragraph -->
```

As shown in the following print, in the Block Editor (view mode), the anchor icon is not shown:

![Anotação 2019-07-16 200709](https://user-images.githubusercontent.com/11923491/61327842-c389a900-a811-11e9-98dc-6701e59b24a8.png)

In the Classic Editor, it is shown the icon that indicates the existence of an anchor:

![InkedAnotação 2019-07-16 200507_LI_](https://user-images.githubusercontent.com/11923491/61327856-cab0b700-a811-11e9-84e1-1a2fc8b9d3d1.jpg)

The Block Editor should also show the icon which indicates that there is an anchor.

**Comment by melchoyce** [comment]
Quick terrible mockup idea, adding the anchor into the block navigator instead of inside the editor:

![image](https://user-images.githubusercontent.com/2846578/66414226-fd102180-e9c6-11e9-8d7f-ccce768e57a5.png)

**Comment by paaljoachim** [comment]
The issue that comes up for me is...
Should the anchor in the backend layout be seen as it is not seen in the frontend?
I believe at the moment one is working on only showing in the backend what is a part of the layout on the frontend.

I do also believe that when Full Site Editing comes into place that we will likely face the issue of showing something in the backend that we will not see in the frontend layout. 

@melchoyce suggestion is a very good idea. Something we can move forward with.

I will also ask for Mark's @mapk and Joen's @jasmussen comment on this issue.

**Comment by jasmussen** [comment]
Not a bad idea, Mel. Anchors are important when you need/use them, but they are also a rather advanced feature. 

_Quick sidenote, there's some related conversation deep in the archives: #1734_

The primary issue with showing a little anchor icon next to the item that has one, is that it either indents the heading (like in the classic editor), breaking the WYSIWYG feel. Or it sits offset to the side, and risks overlapping other content in complex layouts, or just getting cropped off the side of the screen.

If we had a solid idea for where/how to show the anchor, I suspect it would be okay to do so. It would only show up if the user had intentionally added the anchor as text in the advanced section. I wonder if it could be aprt of the block toolbar?

**Comment by mapk** [comment]
If the anchor is something only visible on the backend, I'm in favor of Mel's proposed solution. I don't think it should be included in the editor if it's not going on the frontend. 

There's always the option of showing a `#` right after the text similar to how WordPress.org Handbook pages work.

**Comment by joyously** [comment]
I tried making an anchor, and found I could only do it on a Heading. Is that correct, or did I miss something? Unlike the markup shown above, the current editor uses `id`, not `name` attribute. But there could be `id` attributes on various blocks, especially third party blocks. Would they all get an icon? They all would be potential link targets.
I don't see why the editor has to look just like the front end. Everyone knows they are editing, and there is always a Preview button. It could be something like the little blue circle used in the Customizer. Something that floats on top and isn't too intrusive. But it should help the user make a link to it (however that is done).

**Comment by mapk** [comment]
Because the Block Navigator is getting filled with features, I'm rethinking this. Maybe we can add a visual in the Editor. Rather than placing it at the beginning of the text, how about after the text? Keeping the color muted helps indicate this hashtag is different than the rest of the text.

![Screen Shot 2020-07-16 at 11 18 24 AM](https://user-images.githubusercontent.com/617986/87707620-42cbf880-c756-11ea-96e4-848541f4845d.png)

**Comment by paaljoachim** [comment]
Let's try it out the backend anchor hashtag and see how it works.
We could ask for a developer to create a draft PR.

**Comment by jasmussen** [comment]
> Because the Block Navigator is getting filled with features, I'm rethinking this. Maybe we can add a visual in the Editor. Rather than placing it at the beginning of the text, how about after the text? Keeping the color muted helps indicate this hashtag is different than the rest of the text.

Good to not put it on the left, because side UI has failed the many contexts in which blocks need to work.

However when using the same font as the heading itself, it distinctly looks like _content_ rather than _block UI_, which breaks the front-end/back-end visual sync, which is important. Is this meant to also show up on the frontend?

**Comment by mapk** [comment]
>However when using the same font as the heading itself, it distinctly looks like content rather than block UI, which breaks the front-end/back-end visual sync, which is important. Is this meant to also show up on the frontend?

I don't think it should show on the frontend. 
Here's an iteration with a hashtag icon to signify the anchor rather than the text itself. Should it be a lighter grey?

![Screen Shot 2020-08-04 at 3 41 22 PM](https://user-images.githubusercontent.com/617986/89352509-1de9e780-d669-11ea-94ce-d2e2eb5dae7e.png)

**Comment by jasmussen** [comment]
If it is to only show in the editor, I'd only show it on select, and I'd make it look more like block UI (like give it a background of the same material as the block toolbar).

**Comment by joyously** [comment]
+100 on styling it as UI, including the background, because if you only affect the color, you have no idea if it's visible with what the theme is doing.

**Comment by talldan** [comment]
Is the idea to only show the anchor in the heading block? Anchor can be set on lots of blocks now, so just showing it on the header seems inconsistent.

**Comment by jasmussen** [comment]
> Is the idea to only show the anchor in the heading block? Anchor can be set on lots of blocks now, so just showing it on the header seems inconsistent.

You're referring to this one in the sidebar, right?

<img width="353" alt="Screenshot 2020-12-10 at 09 45 56" src="https://user-images.githubusercontent.com/1204802/101748193-8855dd00-3acc-11eb-9f3a-561043da0c82.png">

You make a good point. Any block, virtually, can get anchors. But we can't show an anchor in-canvas in a consistent way, it won't work as blocks can be anything. Which rewinds us back to Mel's solution outlined in https://github.com/WordPress/gutenberg/issues/16621#issuecomment-539594654 as a potential path forward.

**Comment by mtias** [comment]
Closing this as we have a solution that renders the anchor name in the list view:

![image](https://user-images.githubusercontent.com/548849/118815950-03a88f80-b8b2-11eb-8122-61ae253f7e27.png)
