### ISSUE TITLE
Allow custom inserters in inner blocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#16629]
**Is your feature request related to a problem? Please describe.**
When using inner blocks we need a way to specify a custom inserter so that resulting blocks can implement various designs. For example the menu block needs to hide the default inserter and add a new custom one. 

**Describe the solution you'd like**
Have a custom inserter passed as a value to the innerBlocks component.

**Comment by mkaz** [comment]
@draganescu would the renderAppender work? https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks#renderappender

This allows you to replace the (+) with anything you like, however it requires you to build all the pieces you'll need to select or insert blocks.

**Comment by mkaz** [comment]
@draganescu This might be related to what you want, which is how I found yours when searching for similar tickets before I created mine. https://github.com/WordPress/gutenberg/issues/17280
