### ISSUE TITLE
Implement link editing

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#16633]
Once a link is added to the menu we need to be able to edit it.

**Comment by karmatosed** [comment]
Can't you repurpose the existing editing of link design over having another one? There does feel like a strong pattern already exists here.

**Comment by draganescu** [comment]
In the design offered by #13690 the flow is quite different from the two places where links can be edited. 

In the navigation block we need to edit in a dropdown:

<img width="349" alt="Screenshot 2019-07-18 at 13 23 20" src="https://user-images.githubusercontent.com/107534/61450285-656adc00-a95f-11e9-963a-1cd3386b13e0.png">

In the button block we have a URL input always present:

<img width="673" alt="Screenshot 2019-07-18 at 13 23 44" src="https://user-images.githubusercontent.com/107534/61450323-7ae00600-a95f-11e9-9182-0a90297d2df6.png">

In the link editing of RichText we have a popover:

<img width="379" alt="Screenshot 2019-07-18 at 13 24 04" src="https://user-images.githubusercontent.com/107534/61450345-8c291280-a95f-11e9-8617-7bad757e9b99.png">

My problem is which pattern and how to merge it into the dropdown?

1st option is to edit the link in the dropdown with an edit icon next to it. It is kinda clunky though and the nesting would be so much: Menu > Item > Dropdown > Link > Edit.

2nd option is to remove the "Edit label text" dropdown entry and replace it with "Edit link". Edit label text is useless because label text is editable immediately after the item is selected. 

When Edit link is pressed we would get the link in the dropdown editable like the link input of the button component. I can test that and see how it works. @sarahmonster

**Comment by karmatosed** [comment]
I'll leave this to others to add insight, but for me adding a link should be a consistent experience.

**Comment by noisysocks** [comment]
Closing this. https://github.com/WordPress/gutenberg/issues/17539 tracks enhancements to the Menu item block.
