### ISSUE TITLE
InnerBlocks renderAppender Issue 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#16639]
Hi, 

renderAppender is a new feature for the InnerBlocks component and doesn't work with the old versions of Gutenberg including the current one on the core, I want to make that available on all versions.. starting from WordPress 5.0 ... 

What is the best approach to achieve that? 

Thank you.

**Comment by swissspidy** [comment]
The easiest way to achieve it would be to override the existing JS in core with the latest one from Gutenberg, just like the Gutenberg plugin itself does this.

Keep in mind though that this might cause unwanted side effects when other plugins or other scripts rely on the original version. Plus, it might cause issues with translations when the replacing script contains i18n strings.

**Comment by DOUARA** [comment]
@swissspidy I got it! 

I think it is better to clone that component and give it a different name to avoid all problems, what do you think?

**Comment by DOUARA** [comment]
Hi @swissspidy 
cloning the component required cloning the whole package since it depends on many other components within the package, but I got that error on the console: 
![Screen Shot 2019-07-18 at 12 49 41 PM](https://user-images.githubusercontent.com/39377174/61455204-bf1cd780-a95a-11e9-84eb-cc66c07079be.png)

it seems that the props of the wrapper component is not getting passed to the new InnerBlocks component 

Any ideas on how to solve that?

**Comment by youknowriad** [comment]
The simplest solution I can think of is trying to hide the appender in CSS and render your own in your block.

Also, nothing that Github issues is not meant to address technical help requests. They have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.  You may also ask for technical support at https://wordpress.stackexchange.com/.

Thanks.
