### ISSUE TITLE
Spacer block: Can't grab the block's height adjuster

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16646]
**Describe the bug**
I can't grab the block's height adjuster due to the block below showing the Insert block appender over it.

**To reproduce**
1. Add a Spacer block.
2. Add another block below it.
3. Select the Spacer block again.
4. Try moving the cursor to the node on the bottom of the Spacer block to adjust its height.
5. Observe the Block Inserter appender appearing preventing you from grabbing the node.

**Expected behavior**
I expected to be able to grab the node to the adjuster without it being hidden under the block appender.

**Screenshots**

![spacer-hover](https://user-images.githubusercontent.com/617986/61412933-0fcefa80-a89f-11e9-9844-fe2c4deb82a3.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

**Comment by mtias** [comment]
This is pretty annoying.

**Comment by enriquesanchez** [comment]
[Discussed during today's ](https://wordpress.slack.com/archives/C02S78ZAL/p1563899820054400) [Design triage in Slack](https://make.wordpress.org/chat/).

The team agreed that this was a larger issue around the placement of the appender. A couple of suggestions came up:

1. Have the appender appear in between two blocks when you hover long enough, moving them slightly apart.

2. Have the appender positioned just outside the main block UI so it doesn't overlap any of the block's UI. Quick mockup:

![mockup](https://user-images.githubusercontent.com/3276087/61738975-1e129000-ad51-11e9-9589-cb5cff9b5737.png)

Concerns about accessibility and mobile support should be considered.

**Comment by mtias** [comment]
Let's try how a delay of 2s or so feels for this. It might give a decent baseline since it'd appear when you want to, but not be in the way during most common operations.

**Comment by shaunandrews** [comment]
I worked up a mockup showing what it could be like to only show the inserter after hovering for a second, and then moving blocks out of the way to make room:

![navigation and inserter](https://user-images.githubusercontent.com/191598/63453585-034a3e80-c417-11e9-9b26-3932d5e05ced.gif)

**Comment by shaunandrews** [comment]
![inserter animation 2](https://user-images.githubusercontent.com/191598/63456064-18759c00-c41c-11e9-8044-7a4c38b6bb57.gif)

Here's another iteration on the animation above. This time, I made the line thinner and had it transition in earlier than the + icon.

**Comment by jasmussen** [comment]
Looks great, Shaun. 

A question will likely surface whether this makes it harder to get to the sibling inserter. Which it might. But at the same time it also makes the act of inserting between two blocks more intentional and less fiddly, and opens up blocks like #17143 for happening. In that vein, I would suggest this is a fine tradeoff to make. 

What's the next step to get this shipping? I'll juggle some labels.

**Comment by kjellr** [comment]
I'm going to reopen this one. #17136 was an improvement, but it still requires some very careful mousework to differentiate between the resizer and the inserter.

**Comment by mtias** [comment]
This seems to be working fairly well now with the latest design adjustments. There's probably some further improvements that could be done to the in-between inserter in general.
