### ISSUE TITLE
Columns block: Placeholder text causes narrow columns to be extremely tall

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16647]
**Describe the bug**
I'm trying to be a bit creative with the Columns block. In the image below, I have a 4 column block with the second column set to be very narrow. I want it to be just a solid color, so I added a Paragraph block to it and set the Paragraph block's background to light blue.

When I click away, the Paragraph block fills with the placeholder text, "Start writing or type / to choose a block". This text causes my Column block to become extremely tall and odd-looking. 

**Expected behavior**
I don't expect the placeholder text to fill the space like true written text would. The placeholder text should cause this result.

**Screenshots**

![Screen Shot 2019-07-17 at 2 35 17 PM](https://user-images.githubusercontent.com/617986/61413572-b5369e00-a8a0-11e9-87f5-7a25a3078359.png)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

**Comment by mapk** [comment]
Looks like there might be a relationship to this one: https://github.com/WordPress/gutenberg/issues/10051

**Comment by talldan** [comment]
I closed #23451 as a duplicate. There's a slight difference between the exact behavior in the two issues, but they both relate to very narrow columns causing inner blocks to overlap or be squashed, so it seems like a good idea to combine them.

**Comment by mapk** [comment]
Alrighty. So we just need to figure out how to handle this. I suggest hiding the placeholder text when the column is super narrow. This feels like an element query though and I'm not too familiar with those. Do we use them elsewhere? Or is there another way to accomplish this?

**Comment by annezazu** [comment]
Was testing this out today and it seems to no longer be a problem with the current flow in 10.6.1. Check it out: 

https://user-images.githubusercontent.com/26996883/118549142-4898be80-b718-11eb-8eb0-1ec13f56737f.mov

Going to close this out as a result but feel free to re-open if there is an aspect of this that hasn't been addressed.
