### ISSUE TITLE
Pasting text into columns isn't showing up on frontend

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16645]
**Describe the bug**
I'm trying to paste test into the Column block, but that text isn't showing on the frontend. It only shows up if I make a change to the color, size, or another attribute first, then it shows.

**To reproduce**
1. Add Columns block.
2. Copy and paste text from another website into each of the columns.
3. Save the document and preview it.
4. Observe that the text isn't showing on the frontend.

**Expected behavior**
I expect that the text shows without having to change any attributes of it. In the screencast below, I've already copied the text in the Columns block. I've made an attribute change to the text in the first columns making a line bold. But the other two columns I haven't touched. When I check the preview, the two columns of text don't show.

**Screenshots**

![columns](https://user-images.githubusercontent.com/617986/61412168-00e74880-a89d-11e9-9e98-f5420cbfb6e5.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

**Comment by draganescu** [comment]
I think this is a problem with all Inner Blocks. So far found the behaviour in both columns and the group block.

**Comment by noisysocks** [comment]
When the text is pasted, the `REPLACE_BLOCKS` action swaps out the inner block for a new block. My guess is that this doesn't update the store in a way that invalidates the cached `getBlocks` selector:

https://github.com/WordPress/gutenberg/blob/643412ca070f187c5504683c71c393637808b42a/packages/block-editor/src/store/selectors.js#L176-L188

**Comment by talldan** [comment]
I have a theory, but it needs more testing to verify it. The issue might be the caching of `getBlock`, which `getBlocks` calls through to.

https://github.com/WordPress/gutenberg/blob/643412ca070f187c5504683c71c393637808b42a/packages/block-editor/src/store/selectors.js#L123-L144

I notice that it only has `state.blocks.cache[ clientId ], ` as the data that invalidates it.

This cache looks like it is updated when the `replaceBlocks` action is triggered, but only for the replaced block itself (the leaf inner block that the content has been pasted into):
https://github.com/WordPress/gutenberg/blob/643412ca070f187c5504683c71c393637808b42a/packages/block-editor/src/store/reducer.js#L266-L273

The issue might be that when `getBlock` is called for the parent column block, its cache entry hasn't been invalidated, so it doesn't bother recursing down to fetch the replaced inner blocks. The selector still returns the column as having the old inner block

Contrast this to inserting a new block for an inner block and it looks like the `rootClientId` is added to the list of blocks that should be invalidated, which means it doesn't happen there:
https://github.com/WordPress/gutenberg/blob/643412ca070f187c5504683c71c393637808b42a/packages/block-editor/src/store/reducer.js#L244-L256

**Comment by talldan** [comment]
Looks like it's related to the incorrect clientId being passed into `getBlocksWithParentsClientIds`. #16717 should fix it.
