### ISSUE TITLE
Adding a `>` to the beginning of a line forces a conversion to a Quote block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16649]
**Describe the bug**
I'm trying to create my own list of items and add my own bullet point, a `>` character. Every time I do this, Gutenberg converts the Paragraph block to a Quote block. If I was in some sort of markdown editor, I'd expect this, but I'm not. I'm just trying to add a `>` to the beginning of my paragraph.

**To reproduce**
1. Add a Paragraph block.
2. Add a `>` character to the beginning of the text.
3. Add a `space` after that character.
4. Observe the block switch to a Quote block.

**Expected behavior**
I expect to add any character I want anywhere on the page without triggering a markdown switch of blocks.

**Screenshots**

![bullet](https://user-images.githubusercontent.com/617986/61418441-54fb2880-a8af-11e9-93af-12e5bb42f343.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

**Comment by ellatrix** [comment]
There’s a PR to make it easier to undo such transforms: #14776. Would that help?

**Comment by ellatrix** [comment]
We have the same thing for lists (`* `), separators (`---`), and code formatting `` `code` ``.
