### ISSUE TITLE
Separator block: The sidebar styles are messed up

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16644]
**Describe the bug**
Looking at the separator block style variations in the sidebar, they all looked pretty messed up.

**To reproduce**
1. Add a Separator block to document.
2. View the sidebar with the block selected.
3. Observe the style variations are messed up.

**Expected behavior**
I expected them to look as they used to. This appears to be a regression?

**Screenshots**

![Screen Shot 2019-07-17 at 1 07 15 PM](https://user-images.githubusercontent.com/617986/61408127-320f4b00-a894-11e9-980a-1e8b5f7d1f2a.png)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

**Comment by karmatosed** [comment]
That's super interesting as I can't replicate and would love to work out how to. I tried using the latest version and got the following:

![image](https://user-images.githubusercontent.com/253067/61413369-3020a880-a8e3-11e9-8eda-96e0d2cca7b6.png)

There is a strange mark to one side on them all but I do see the lines.

**Comment by youknowriad** [comment]
I think this is fixed with scaling even if not perfect.
