### ISSUE TITLE
Unify text alignment location between Heading and Paragraph blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16648]
The text alignment for a Paragraph block is located right in the toolbar. When making a text alignment change to a Heading, I expected it to be located similarly in the toolbar as well. 

Can we unify the placement of the alignment options? Maybe we can move the text alignment options for the Heading block to the block's toolbar as well?

**Screenshots**

![text-alignment](https://user-images.githubusercontent.com/617986/61415143-d1d4d500-a8a4-11e9-9e09-5078ef501aad.gif)

**Comment by karmatosed** [comment]
Ah alignment, this has gone back and forth :) I think to make it consistent works so for me, that's the baseline here.

**Comment by kjellr** [comment]
Yes — It's very weird to have this in the sidebar but not in the toolbar. No other blocks do that, so we should make it consistent.
