### ISSUE TITLE
Images with `alignfull` and `alignwide` shouldn't be enclosed by `p`

### ISSUE THREAD

**Issue by pfefferle** [WordPress/gutenberg#1665]
A full width image with no caption is rendered like:

```HTML
<p>
  <img src="..." alt="..." class="alignfull wp-block-image">
</p>
```

Most themes will have a full width `p` element, so it is nearly impossible to make the image full width, without JS or some `position: *` hacks.

Some possible solutions:

* always use the `figure` element for `alignfull` and `alignwide`
* use a `div` element with `alignfull` and `alignwide` instead of the `p`
* add the `alignfull` and `alignwide` classes also to the `p` element.

Similar to https://github.com/WordPress/gutenberg/issues/1305

**Comment by youknowriad** [comment]
This makes sense to me cc @jasmussen 

I'd go for the `figure` wrapper in this case.

**Comment by jasmussen** [comment]
I think this is a very solid observation, and great ticket. Making images go full-width is going to be complicated already, but this would make it slightly easier for themes. 👍 👍

**Comment by pfefferle** [comment]
this was fast, thanks :smile:
