### ISSUE TITLE
Relax Cover and Media+Text inner blocks restrictions 

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16658]
It doesn't make a lot of sense to restrict these so much, we should let people choose whatever block they want to add there. 

For example, `Cover` only allows:
```js
const INNER_BLOCKS_ALLOWED_BLOCKS = [ 'core/button', 'core/heading', 'core/paragraph' ];
```

**Comment by LyleBennett** [comment]
I agree, I've been struggling a lot with the cover block and it's innerblock limitations. 
Is there not a filter or hook I can use in my plugins/themes to choose to allow other blocks in the cover?

At the moment my solution is to use the group block with a custom class, then in the css do backgrounds and overlay styling.

This ends up with a lot of extra classes, groups and css which could be simplified and avoided if it were possible to choose/filter/hook the allowed inner blocks.

**Comment by manuel-84** [comment]
I agree and I think an override should be provided (no more const...)

**Comment by senadir** [comment]
the limitations are now removed

**Comment by mtias** [comment]
Thanks @senadir!
