### ISSUE TITLE
Add ability to turn off RichText list indent toolbar controls 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#16650]
**Is your feature request related to a problem? Please describe.**
List indenting controls render when using the `RichText` component as a `ul` with `multiline="li"` ([source](https://github.com/WordPress/gutenberg/blob/39f568faf2e62c57736bb80d7088a996eb067944/packages/block-editor/src/components/rich-text/index.js#L1058)). It would be beneficial to opt out of indention support, so that extra controls don't display when they're not needed. 

Use case: I have a ul/li RichText component in the CoBlocks Pricing Table block, of which the list items are centered and are meant to display plan features. Indenting lists is not necessary as it would complicate the tables and add lower readable. And as the list items are centered, the indention has no effect.  

**Describe the solution you'd like**
A prop to opt out of indenting lists while maintaining the ul/li relationship. 

**Describe alternatives you've considered**
Using `<p>` RichText components, although it's not a great approach.

**Screenshot:**
<img width="884" alt="Screen Shot 2019-07-17 at 8 20 26 PM" src="https://user-images.githubusercontent.com/1813435/61420421-5be66300-a8d0-11e9-9030-677001b63017.png">

**Comment by noisysocks** [comment]
Hi @richtabor, this seems to have been fixed by https://github.com/WordPress/gutenberg/pull/16962. The indent buttons will not only show in the List block.
