### ISSUE TITLE
[WORKAROUND] Custom Post Types & `rest_cookie_invalid_nonce`

### ISSUE THREAD

**Issue by DaveyJake** [WordPress/gutenberg#16668]
Hopefully this will help someone and prevent them from spending hours upon hours of Google searching but I encountered the `rest_cookie_invalid_nonce` error on my local dev server.  This error occurred when using the [Custom Post Type UI](https://wordpress.org/plugins/custom-post-type-ui/) [**CPTUI**] plugin in conjunction with previously written custom code based on the [WP Rest API Handbook](https://developer.wordpress.org/rest-api/extending-the-rest-api/).

# TL;DR
Removing the CPTUI-created post type solved my issue with `rest_cookie_invalid_nonce`.

# If you need to extend the WP Rest API response...
Depending on any plugins that you have installed, there may be some that generate a custom post type upon installation.  However, there are some plugins that do not automatically include the generated plugin inside the WP Rest API response.  **If you have a plugin that's not already visible inside of any WP Rest API response, then you would need to add them using your own custom code.**

# Moral of the story...
Do not include any custom post types that were created using CPTUI in any custom code that you've written to extend the WP Rest API needs for your project.  CPTUI contains all of the options needed to properly add your custom post type to the WP Rest API interface.

I hope this helps someone out there going through a similar issue, especially when the screen shows up blank due to bad JavaScript being run.

**Comment by paaljoachim** [comment]
Hey @DaveyJake Davey

Thanks for opening this issue!
Some time has passed.
Is this issue still valid?

**Comment by DaveyJake** [comment]
@paaljoachim Looking back, at the time I submitted this, I was trying to achieve the same end-result using two different means being **CPTUI** and **WP REST API**.

Today, I'm not longer dependent on plugins create custom post types nor custom taxonomies--I do that manually in the code.  I haven't encountered this issue since.

**Comment by paaljoachim** [comment]
Hey @DaveyJake Davey

As others might come across this issue and may have a similar question it would be great if you could share the code or a link to a place where you have the code. As you would then be sharing the question as well as the solution you found. 
Thank you!
