### ISSUE TITLE
Converting galleries shortcode (exclude and include attribute) results in empty block

### ISSUE THREAD

**Issue by mtoensing** [WordPress/gutenberg#16661]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when galleries in posts are not converted to blocks. e.g.

`<p>[gallery size="thumbnail" exclude="14231,14291,14307" link="file"]</p>`

or

`<p>[gallery size="thumbnail" include="14231,14291,14307" link="file"]</p>`

or

`<p>[gallery link="file"  ids="20456,20478,20438,20502,20501,20503,20496,20495,20476,20475,20477,20508,20511,20467,20466,20472,20473,20505"]</p>`

**To reproduce**

Create an normal classic article. 

Switch to HTML mode and paste in the following

`<p>[gallery size="thumbnail" include="14231,14291,14307" link="file"]</p>`

Save.

Now activate Gutenberg.

From the menu, click Convert to blocks.

This created block will just be an Embed placeholder. e.g.,

`<figure class="wp-block-gallery"></figure>`

**Describe the solution you'd like**
Galleries are converted to blocks of type gallery. 

**Describe alternatives you've considered**
The resulting block should contain the contents of the original shortcode.

**Desktop (please complete the following information):**
OS X
Chrome 75
WP 5.2.2
Gutenberg

**Comment by mtoensing** [comment]
relates to #15869

**Comment by bph** [comment]
@mtoensing could you describe or maybe include a screenshot of what is happening on your site. I tried to reproduce it via the classic editor and convert a gallery to block as well as via the classic block, create a gallery and both conversion worked as expected. 

What is exactly happening when you try to convert the gallery shortcode to blocks. Does it only display the shortcode string or are they converted to images? 
 
You mention Gutenberg, but not which version. Are you using the Gutenberg plugin? or the default editor that is in WordPress 5.2? 

And could you please list other plugins that are on your site or sites. To fix this for all use cases, we need some more information about your sites.

**Comment by mtoensing** [comment]
Hi, 
I uninstalled all plugins. As I mentioned the markup results in an empty div: 

`<figure class="wp-block-video"></figure>`

I use the latest version of wordpress and the included Gutenberg Editor as stated at the end of my comment. Maybe the `<p></p>` tags are the problem?

**Comment by mtoensing** [comment]
I made a video on an empty Wordpress 5.2.2 installation: https://youtu.be/bwf1v_6WYQM

**Comment by bph** [comment]
The video was very helpful, to see what happens when you try. 

The gallery in the old post didn't have any pictures in it. The ids in your shortcode reference the ids of images 'include="14231,14291,14307`- that were uploaded to the Media library and than added to the gallery. If you take the shortcode to a different site, and your Media Library doesn't have the image with those ids, you automatically get an empty gallery with the notification "Not items found".

That why you get after the  conversion the note  asking you to upload images. 

Can you try to replicate this with images you loaded to the Media library and see what happens to the gallery view in the Classic Editor. Then try to convert it to a block. It should work now...

**Comment by mtoensing** [comment]
That was just an example. I will make a video with existing image ids. It happend on a live system with live ids

**Comment by bph** [comment]
That would be fabulous! Thank you for your patience! You might want to test it on your clean install as well, and see if you can reproduce it with uploading images there. Just to be sure. :-)

**Comment by youknowriad** [comment]
Closing as adressed by @bph.
