### ISSUE TITLE
Resizing image in columns gives you interesting visual

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16667]
I resized the image I added in columns and managed to get this interesting effect:

![image](https://user-images.githubusercontent.com/253067/61490064-fcf21e00-a9a3-11e9-89b4-42b8aa1f4af3.png)

This was on Chrome.

**Comment by youknowriad** [comment]
What would you expect? Do you think columns should have `overflow: hidden`?

**Comment by karmatosed** [comment]
@youknowriad I have to admit I am not sure now what I expected in July. I do think though that overflow hidden might help some complications.

**Comment by mtias** [comment]
A ton has changed in the block and placeholder UI. If there are further concrete ideas for improving, let's open new issues with them.
