### ISSUE TITLE
Duplicated content for Block Controls & Inspector

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#16670]
These pages in the Handbook has exactly the same content:

[Block Controls: Toolbars and Inspector](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/block-controls-toolbars-and-inspector/)

[Block Controls: Block Toolbar and Settings Sidebar](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/block-controls-toolbar-and-sidebar/)

They're both under the Tutorials > Block menu. It's confusing. Please delete one of them.

**Comment by swissspidy** [comment]
Yeah the importer doesn't currently delete old pages when they have been renamed.

**Comment by gziolo** [comment]
Both URLs redirect to one page now. Thanks for the report 👍
