### ISSUE TITLE
E2E test utils do not support localized WordPress environment

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#16675]
**Describe the bug**
Many of the e2e test utilities assume that the WordPress environment is in English, for example by using `[aria-label]` selectors with English text in them.

That means I cannot run the e2e tests against a WordPress site that was localized into German, for example.

However, that would be really useful as there can be UI changes depending on the locale, e.g. longer texts, different date pickers, RTL layouts, etc.

**Examples**

https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/e2e-test-utils/src/open-global-block-inserter.js#L5

https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/e2e-test-utils/src/ensure-sidebar-opened.js#L13

https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/e2e-test-utils/src/open-document-settings-sidebar.js#L6

**Expected behavior**

E2E test utilities should not use hardcoded English strings in selectors. Instead, they should rely on other selectors like IDs and class names.

**Comment by swissspidy** [comment]
Another issue, but a bit unrelated to i18n:

`findSidebarPanelToggleButtonWithTitle` doesn't work when the panel button is wrapped in a `span`, for example when trying to target the `Color Settings` panel.

**Comment by kathrynwp** [comment]
Hi @swissspidy, I'm just circling back to this issue to check whether it's still valid. Let me know if you'd like it to be kept open or not. Thanks!

**Comment by swissspidy** [comment]
Still valid but should be ok to close as maybelater
