### ISSUE TITLE
List block - Inserting new list item adds empty line 

### ISSUE THREAD

**Issue by pmmueller** [WordPress/gutenberg#16671]
**Describe the bug**
Inserting a new item in an ordered or unordered list inserts an additional new line underneath the new item (see GIF) 

**To reproduce**
Steps to reproduce the behavior: see the list in the GIF 

![wp-block-editor-list-block-bug](https://user-images.githubusercontent.com/1928205/61515084-fb574300-aa01-11e9-8bad-09e4d361b5ea.gif)

**Expected behavior**
There shouldn't be an empty line.  

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 
 - Browser: Firefox 
 - Version 68.0.1

In Chrome and Safari the new line does not appear. 

**Additional context**
GIF was recorded without Gutenberg plugin, but same thing happens with 6.0.1 activated.

**Comment by karmatosed** [comment]
Thanks for reporting this @pmmueller, I can replicate:

![image](https://user-images.githubusercontent.com/253067/61655415-6e88df80-acb6-11e9-8a81-379b5b07ddc6.png)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I'm unable to reproduce this in Firefox 84 and Gutenberg 9.8.0.  

 Please reopen this issue if this is still affecting you.
