### ISSUE TITLE
WP components audit: selection controls

### ISSUE THREAD

**Issue by davewhitley** [WordPress/gutenberg#16689]
**Is your feature request related to a problem? Please describe.**

This issue is part of a review on the naming, structure, and composition of the UI components as brought up in https://github.com/WordPress/gutenberg/issues/16367

These are the current components that are related to text input fields that I considered in this issue:

- CheckboxControl
- FormToggle
- RadioControl
- RangeControl
- SelectControl
- ToggleControl
- TreeSelect

# [CheckboxControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/checkbox-control) / [RadioControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/radio-control)

![image](https://user-images.githubusercontent.com/618551/61159398-847def80-a4c1-11e9-83aa-d5c33e154fdb.png)

## Audit
Opportunities I came across while reviewing this component.

- Initially not clear how these relate to the BaseControl component. Using the term "control" seems to unnecessarily confuses the names of these components.

## Suggestions

- Simplify language by using simpler names, **Checkbox** and **Radio**.
- Consider adding a new [RadioGroup](https://evergreen.segment.com/components/radio) component to easily group radio buttons.

# [FormToggle](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/form-toggle) / [ToggleControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/toggle-control)

![image](https://user-images.githubusercontent.com/618551/61159478-c9a22180-a4c1-11e9-89db-d91d0d7360f6.png)

## Audit
Opportunities I came across while reviewing this component.

- I was confused why there were two toggle components that seemed very similar. Hard to understand the difference between the two.
- Same as CheckboxControl and RadioControl, it's not clear how ToggleControl is related to BaseControl.

## Suggestions

- Simplify language by using a simpler name for both components, **Switch**. This aligns with the [aria switch role](https://www.w3.org/TR/wai-aria-1.1/#switch).
- “Toggle” is a generic verb that can be used in other places in the system to describe on/off behavior. We need a unique term to describe this UI element.

# [SelectControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/select-control) / [TreeSelect](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/tree-select)

![image](https://user-images.githubusercontent.com/618551/61159692-6c5aa000-a4c2-11e9-8e83-66099d690cac.png)

## Audit
Opportunities I came across while reviewing this component.

- See above components with the "Control" suffix. Same applies here.
- It was confusing trying to understand the difference between TreeSelect and SelectControl.

## Suggestions

- Simplify language by using a simpler name, **Select**.
- Consider provide the functionality of TreeSelect in the Select component as a prop to make things simpler.
- Consider removing the multiple option. This native option on the select element seems unfamiliar and hard to use (requires keyboard shortcuts to select multiple). We want people to use checkboxes or maybe FormTokenField in this case.
- Consider an “enhanced” option that provides a custom popover for selecting elements.

# [RangeControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/range-control)

Note: [a11y audit](https://github.com/WordPress/gutenberg/issues/14166) on the RangeControl component.

![image](https://user-images.githubusercontent.com/618551/61159716-84322400-a4c2-11e9-806c-5bda9cd7d555.png)

## Audit
Opportunities I came across while reviewing this component.

- See above components with the "Control" suffix. Same applies here.

## Suggestions

- Simplify language by using a simpler name, **Slider** or **RangeSlider**. "**Slider**" is more recognizable and more visually descriptive than RangeControl.

# Feedback

The feedback I'm looking for is related to naming, structure, and composition. I'm not looking for visual feedback of the components. I'm also not examining each prop for each component; only the ones that I think are relevant for the audit. I know this issue is a lot to take in, and I appreciate any feedback you have.

**Comment by drw158** [comment]
# Props audit

As an addendum, here is a deeper evaluation of the props for these components. This is an effort to expand the components to be more useful and to answer the [question](https://github.com/WordPress/gutenberg/issues/16367), "Are properties well thought out and consistently applied?" This only covers visual props. Event handler props will be evaluated at a later date.

## Checkbox/Radio

### ✨ New
- indeterminate or mixed: the "mixed" state of the checkbox
- **hideLabel**:
- **disabled**:
- **error**: depends on how we implement error states in [text inputs](https://github.com/WordPress/gutenberg/issues/16685#issuecomment-513343858).

### 📋 Rename
- **help** → helpText

### 👍 No change
- **checked**
- **label**

### ✂️  Remove
- **heading**

---

**Comment by hacknug** [comment]
It would be great if we could use this as an excuse to also revisit #12732 and maybe even start using `<CheckboxControl />` for the Categories list :v:

**Comment by mapk** [comment]
I'm closing out the Component Audit issues for now.
