### ISSUE TITLE
Suggestion: Only show one set of block movers at a time. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16681]
Currently, if you have a nested child or parent block selected, and then hover over adjacent blocks, you'll see two sets of block movers: 

<img width="681" alt="Screen Shot 2019-07-19 at 9 27 10 AM" src="https://user-images.githubusercontent.com/1202812/61538444-68b9a280-aa07-11e9-87c4-7ee71d479542.png">

GIF: 

![overlap](https://user-images.githubusercontent.com/1202812/61538549-a1f21280-aa07-11e9-947a-e97e73381249.gif)

This is really confusing, and looks broken. We should try only showing one set of block movers at a time, in order to prevent this overlap.

**Comment by swissspidy** [comment]
This is not limited to nested blocks, happens with regular blocks too:

![Screenshot 2019-07-19 at 15 44 20](https://user-images.githubusercontent.com/841956/61539587-1fd01100-aa3c-11e9-9df4-292de86e7505.png)

**Comment by kjellr** [comment]
Good point. This is also related to https://github.com/WordPress/gutenberg/issues/11725

**Comment by karmatosed** [comment]
Totally agree we should bring in more consistently showing only one of any type of interactive element at a time, of any.

**Comment by kjellr** [comment]
Closed via #17315.
