### ISSUE TITLE
Gutenberg Editor Tips Always Show Regardless of Options Picked

### ISSUE THREAD

**Issue by ShaneSchroll** [WordPress/gutenberg#16688]
**Describe the bug**
In Firefox specifically, Gutenberg insists on showing tips every time it loads. I have unchecked the option to "Enable Tips". Yet it still shows tips. I have also scoured forums and reddit posts with users having the exact same issue.
Here's just 1 for reference. You can see there are a lot of "hacky" workarounds for making it work.
https://wordpress.org/support/topic/disable-tips/

**To reproduce**
1. In **Firefox**: Go to any page that has Gutenberg Enabled as the Editor
2. See the Tips popup.
3. Uncheck "Enable Tips" in the more options section. Refresh page and see tips again.

**Expected behavior**
When unchecking "Enable Tips" I expected them to go away. This is not the case.

**Desktop (please complete the following information):**
 - OS: Windows (10)  /  Mac (High Sierra & Mojave)
 - Browser: Firefox
 - Version: Developer Edition (nightly builds) - always on newest version

**Additional context**
WP Version: 5.2.2
Block Editor (Gutenberg) is enabled (No plugins that disable gutenberg are present - as I know this can cause issues with GB)

**Comment by talldan** [comment]
Hey @ShaneSchroll - Thanks for the bug report. I haven't been able to reproduce this.

The option for whether tips are displayed is stored in browser localstorage. Is there any chance you've blocked the site you're testing on from being able to use localstorage?
https://support.mozilla.org/en-US/kb/storage#w_allow-or-block-websites-from-storing-information

**Comment by ShaneSchroll** [comment]
Ah, I did have block all cookies enabled. It works now without re-appearing when I added the exception for it in FF. This can be closed now. Thank You!
