### ISSUE TITLE
Incorrect slug for German characters

### ISSUE THREAD

**Issue by uok** [WordPress/gutenberg#16695]
**Steps to reproduce**

_Editor_
Change title of page to "Letzte Änderungen" (German for "last updates")
Clear field for slug and save page
Incorrect slug: letzte-anderungen

_Quick edit_
Change title of page to "Letzte Änderungen"
Clear field for slug and save changes
Correct slug: letzte-aenderungen

**Expected behavior**
both changes should result in correct slug

WP 5.2.2

**Comment by ocean90** [comment]
Duplicate of #12907.
