### ISSUE TITLE
Unable to remove autop from core/shortcode block

### ISSUE THREAD

**Issue by bracketsberlin** [WordPress/gutenberg#16694]
The shortcode-block (core/shortcode) wraps all shortcodes with a paragraph (**autop** function) while transforming it as found in:
`/wordpress-develop/node_modules/@wordpress/block-library/src/shortcode` (index.js:29-52)
```
transforms: {
		from: [
			{
				type: 'shortcode',
				// (...)
				tag: '[a-z][a-z0-9_-]*',
				attributes: {
					text: {
						type: 'string',
						shortcode: ( attrs, { content } ) => {
							return removep( autop( content ) );
						},
					},
				},
				priority: 20,
			},
		],
	},
```

Is there a chance to use the core/shortcode block inside a custom Gutenberg block and assign an updated transforms-value to it via its attributes or something comparable? 
`[ 'core/shortcode', { transforms: UPDATED_VALUE } ]`

Goal: remove automatic paragraphs around shortcodes which are added through the core/shortcode block.

Thanks for a hint.

**Comment by swissspidy** [comment]
You can use the [`blocks.registerBlockType`](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#blocks-registerblocktype) filter to override a block's attributes and transforms.

**Comment by bracketsberlin** [comment]
Thank you, @swissspidy - I tried it, but it did not work for some reason. I'll give it another try. Thank you.

**Comment by bracketsberlin** [comment]
@swissspidy is your suggestion to fully reregister/recreate the core/shortcode block?

**Comment by swissspidy** [comment]
No, my suggestion was to use that filter to tweak the block's transforms configuration.

**Comment by youknowriad** [comment]
Not sure I understand what you're transforming, I just tried transforminig some random shortcode from a classic block to a shortcode block, it worked without extra "p".
