### ISSUE TITLE
Wordpress custom block type, that will manage list of string

### ISSUE THREAD

**Issue by vitali-yablonski** [WordPress/gutenberg#16703]
I need create custom block type, that will manage list of strings or urls. Can you recommend tutorial or example? Thanks.

**Comment by derweili** [comment]
Take a look at this example:
https://gist.github.com/derweili/bb3486f7abf7862b85fbbf01bb1eb52f

You need an attribute of the type array to manage a list of strings.

Some tutorials can be found in the Gutenberg handbook:
https://developer.wordpress.org/block-editor/tutorials/

**Comment by youknowriad** [comment]
Looks like there's already an answer.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thanks for your understanding.
