### ISSUE TITLE
Blocks tutoiral misordered 

### ISSUE THREAD

**Issue by bardic** [WordPress/gutenberg#16719]
**Describe the bug**
introducing-attributes-and-editable-fields.md and block-controls-toolbar-and-sidebar.md are not in the correct order on the tutorial website 

**To reproduce**
1. Go to https://developer.wordpress.org/block-editor/tutorials/block-tutorial/
2. See in the sidebar that the two aforementioned tutorial links are not in the correct order

**Expected behavior**
introducing-attributes-and-editable-fields.md  should be before block-controls-toolbar-and-sidebar.md

**Comment by Soean** [comment]
The file `block-controls-toolbars-and-inspector` was renamed to `block-controls-toolbar-and-sidebar` in [16138](https://github.com/WordPress/gutenberg/pull/16138/files#diff-898656577829f3ff69c0ab8c788664e1). 

The source code looks good, but the handbook now keeps the old and the new file. I think this is a ticket for the meta trac.

**Comment by Soean** [comment]
Meta trac ticket: https://meta.trac.wordpress.org/ticket/4619

**Comment by swissspidy** [comment]
Yeah old pages need to be deleted manually after renaming.

Closing since there's a Meta Trac ticket.

**Comment by Soean** [comment]
The old site was deleted and redirected.
