### ISSUE TITLE
WP components audit: Lists, Menus, & Panel

### ISSUE THREAD

**Issue by davewhitley** [WordPress/gutenberg#16725]
**Is your feature request related to a problem? Please describe.**

This issue is part of a review on the naming, structure, and composition of the UI components as brought up in https://github.com/WordPress/gutenberg/issues/16367

These are the current components that are related to Lists and Menus that I considered in this issue:

- DropdownMenu
- Dropdown
- MenuGroup
- MenuItem
- MenuItemsChoice
- Panel
- PanelBody
- PanelRow

# Lists (✨ new)

![List](https://user-images.githubusercontent.com/618551/61067028-45ba3d80-a3cc-11e9-955a-5ed575b980df.png)

## Audit

I'm starting this issue with a new component because many of the same concepts and patterns found within **Menus** and **Panel** can be generalized into a new component. By creating a more generalized component, we can standardize the visuals and functionality of common patterns. Lists can be broken down into these sub-components:

- **List**
- **ListGroup** (similar to the existing MenuGroup)
- **ListItem** (similar to the existing MenuItem)
- **CollapsibleList** (similar to the existing Panel)

The libraries that most resemble this can be seen in [MDC React](https://github.com/material-components/material-components-web-react/tree/master/packages/list), [Material UI](https://material-ui.com/components/lists/#lists), and [RMWC](https://rmwc.io/lists). The closest Polaris example I could find is their [Resource List](https://polaris.shopify.com/components/lists-and-tables/resource-list). Ant has a [List](https://ant.design/components/list/) component as well.

### List

![image](https://user-images.githubusercontent.com/618551/61076597-36de8580-a3e2-11e9-8df2-acb53b802ab4.png)

- Contains ListItems.

### ListGroup

![image](https://user-images.githubusercontent.com/618551/61074848-44920c00-a3de-11e9-9d8e-828ebbd2d442.png)

- Similar to MenuGroup. It groups lists together.
- Provides a header and divider either as props or separate ListGroupSubheader and ListDivider components.

Example structure:
```
ListGroup
─ ListGroupSubheader
─ List
── ListItem
── ListItem
─ ListGroupSubheader
─ List
── ListItem
── ListItem
```

### ListItem

![image](https://user-images.githubusercontent.com/618551/61075954-b408fb00-a3e0-11e9-9faa-89223d2953a9.png)

- Similar to MenuItem. An individual item in a List.
- Provides text and graphics either as props or separate ListItemText, ListItemGraphic (similar to the `icon` prop on MenuItem), and ListItemMeta (similar to the `shortcut` prop on MenuItem) components.

Structure:
```
List
─ ListItem
── ListItemGraphic
── ListItemText
── ListItemMeta
```

### CollapsibleList (previously: [Panel](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/panel))

![image](https://user-images.githubusercontent.com/618551/61078370-16182f00-a3e6-11e9-940d-18ef65bec69f.png)

- **Panel** seems to have some functionality that isn't used very much (e.g. the header prop).
- The name "Panel" does not accurately describe the main use case of the component, which is to provide collapsible list items.
- This also replaces the need for **PanelBody** and **PanelRow**.

Structure:
```
CollapsibleList
─ ListItem
── ListItem
── ListItem
── ListItem
```

Here are a few different examples of collapsible components: [Polaris](https://polaris.shopify.com/components/behavior/collapsible), [Ant](https://ant.design/components/collapse/#header), [Material UI](https://material-ui.com/api/collapse/#collapse-api).

# Menus
Current existing components: ([MenuGroup](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-group), [MenuItem](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-item), [MenuItemsChoice](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-items-choice)) 

![image](https://user-images.githubusercontent.com/618551/61085706-8929a180-a3f6-11e9-989a-bc709e9413e6.png)

## Audit

Menus mirror the List components above except for the additional "Menu" component. Because of this, I won’t go into detail for each component. All of the same props are available for each component. This is how Material implements Menus in their [React library](https://href.li/?https://github.com/material-components/material-components-web-react/tree/master/packages/menu). I’m not sure how it works technically, but they share the same props. Is there a term for this type of component? A component with a shared API?

- **Menu** 
- **MenuList** = List
- **MenuListGroup** (previously: [MenuGroup](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-group)) = ListGroup 
- **MenuListItem** (previously: [MenuItem](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-item)) = ListItem 

### Note on [MenuItemsChoice](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-items-choice)

Choosing one option from a list, either exclusively (radio) or multiple (checkbox), is a common pattern, but I think it could be built with the proposed component additions and changes:

![image](https://user-images.githubusercontent.com/618551/61085857-f3dadd00-a3f6-11e9-91bf-f19369c0dcdd.png)

I suggest that this exclusive/multiple choice selection be a prop on the **MenuList** component instead of its own separate component. For example:

```jsx
<MenuList exclusive>
     <MenuListItem />
     <MenuListItem />
</MenuList>
```

An alternative may be to provide the prop on MenuListGroup instead:

```jsx
<MenuListGroup exclusive>
     <MenuList>
          <MenuListItem />
          <MenuListItem />
     </MenuList>
</MenuListGroup>
```

### [DropdownMenu](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown-menu) and [Dropdown](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown)

One big difference between Menus and Lists is that Menus have a shadowed container (usually activated by a button) that appears once clicked.

I could use some help figuring out the best approach for handling the element that activates the Menu. Some systems have a **MenuSurfaceAnchor** or **MenuSurface** components and I’m having a hard time sorting it out. For example, I don’t know exactly what DropdownMenu and Dropdown are and how they are different. I couldn't figure it out from the documentation, which leads me to think it could be improved.

# Feedback

The feedback I'm looking for is related to naming, structure, and composition. I'm not looking for visual feedback of the components. I'm also not examining each prop for each component; only the ones that I think are relevant for the audit. I know this issue is a lot to take in, and I appreciate any feedback you have.

- Is it viable to have a generic List component?
- I could use some help structuring the Collapse component. Seems like we might want the same collapse functionality for other components. Should it be some sort of wrapper component?
- Is there a name for components that share props? Shared API?
- What's the difference between DropdownMenu and Dropdown?

**Comment by drw158** [comment]
# Props audit

As an addendum, here is a deeper evaluation of the props for these components. This is an effort to expand the components to be more useful and to answer the [question](https://github.com/WordPress/gutenberg/issues/16367), "Are properties well thought out and consistently applied?" This only covers visual props. Event handler props will be evaluated at a later date.

### Menu/List

Because these components are almost the same, I'll audit the props together. Example of props we could include in the new List component:

#### Props

**List**
- **dense**
- **avatarList**: uses larger leading graphics, suitable for avatars.
- **twoLine**: two lines of text for the ListItems.
- **checkboxList**: multiple selection in a list.
- **radioList**: exclusive selection in a list.

**ListItemText**
- **primaryText**: primary dark text
- **secondaryText**: secondary lighter text

**ListItemGraphic** and **ListItemMeta** components can accept text, image, or a component.

---

Event handler props will be evaluated at a later date.

**Comment by mapk** [comment]
I'm closing out the Component Audit issues for now.
