### ISSUE TITLE
Issue with nested text formats 

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#16721]
Better describe this with screenshots (bear with me).

**1. Registering my own format and surfacing my controls.**
![DeepinScreenshot_select-area_20190723184015](https://user-images.githubusercontent.com/9055437/61728102-39939000-ad7d-11e9-9f51-16bd4cde70d1.png)

**2. Adding some text**
![DeepinScreenshot_select-area_20190723190636](https://user-images.githubusercontent.com/9055437/61728129-4912d900-ad7d-11e9-8c7a-462203dbff36.png)

**code editor:**
![DeepinScreenshot_select-area_20190723183944](https://user-images.githubusercontent.com/9055437/61728190-68116b00-ad7d-11e9-9400-71318536bafa.png)

**3. Applying my format ( font, line-height, letter-spacing ) to the whole text.**
![DeepinScreenshot_select-area_20190723184520](https://user-images.githubusercontent.com/9055437/61728347-b6266e80-ad7d-11e9-8641-0065e40bcb4c.png)

**code editor:** :heavy_check_mark: 
![DeepinScreenshot_select-area_20190723184535](https://user-images.githubusercontent.com/9055437/61728370-c0486d00-ad7d-11e9-9142-835215a7cbc8.png)

**4. Applying my format to a subset of the text with new values.**
![DeepinScreenshot_select-area_20190723184724](https://user-images.githubusercontent.com/9055437/61728428-e110c280-ad7d-11e9-832b-081d3e38f751.png)

**code editor:** :heavy_check_mark:
![DeepinScreenshot_select-area_20190723185159](https://user-images.githubusercontent.com/9055437/61728589-3220b680-ad7e-11e9-8f6d-d09e0e0c2e59.png)
 
**inspector:** :heavy_check_mark:
![DeepinScreenshot_select-area_20190723184925](https://user-images.githubusercontent.com/9055437/61728524-0f8e9d80-ad7e-11e9-8c1d-74b5afbca729.png)

**5. Navigating back to the visual editor. The format appears to be lost.**
![DeepinScreenshot_select-area_20190723185255](https://user-images.githubusercontent.com/9055437/61728604-3c42b500-ad7e-11e9-9cba-47d557e8d91d.png)

**inspector:** :x: 
![DeepinScreenshot_select-area_20190723185343](https://user-images.githubusercontent.com/9055437/61728703-68f6cc80-ad7e-11e9-9584-2ddaf75b938e.png)

**But switching back to the code editor, we can see the format is still there.
code editor:** :heavy_check_mark: 
![DeepinScreenshot_select-area_20190723185516](https://user-images.githubusercontent.com/9055437/61728746-790eac00-ad7e-11e9-9e92-8201a74c1f13.png)

**Also, it's correctly being applied to the frontend.
frontend:** :heavy_check_mark: 
![DeepinScreenshot_select-area_20190723185832](https://user-images.githubusercontent.com/9055437/61728935-db67ac80-ad7e-11e9-8bc7-1cf189ab0735.png)

**Notice:**
Instead of registering different formats for every style I wanted to be applied, I registered a single text format containing all the styles (font, line-height, text-transform, letter-spacing) and did the style merging myself.

```
registerFormatType(
	name,
	{
		title,
		tagName: 'span',
		className: 'vgblk-rto',
		attributes: {
			style: '',
			'data-lh': '',
			'data-ls': '',
			'data-uc': '',
			'data-lc': '',
			'data-cw': '',
			'data-font': '',
		},
		edit: MyRichTextOptions,
	},
);
```

Also did not use the suggested `RichTextToolbarButton` cause of how limiting the "More Rich Text Controls" `DropdownMenu` appears to be.

I could provide the `edit` function code in a secret gist to a core developer to check, if that's needed, but by the looks of it, looks like a core bug ( visual/code editor mismatch).

**Comment by talldan** [comment]
@amyriounis Apologies for the amount of time it's taken to get a reply for this one.

@ellatrix would know more and would be able to correct my understanding here.

I think this is related to the way adjacent (or nested formats) are merged when the format is serialized and created. IIRC, the className and tagName are used to identify and merge formats that are the same into one:
```html
<span class="my-test-format">he</span><span class="my-test-format">llo</span>
```
when serialized becomes merged into:
```html
<span class="my-test-format">hello</span>
```

And I guess the same must happen when formats are nested, they're reduced into a single format.

What I think you'd need to do is create separate formats, e.g. a font format, a line height format, a line spacing format.

In terms of displaying them all in the same panel, that might be a challenge. It might be possible to use slots or portals to achieve that.

I don't know that this would be considered a bug, though I think potentially the formatting system when applying the format could behave in the same way as it does when serializing the format.

I'll add the Needs Technical Feedback label as I'm not sure how to classify this.

**Comment by ellatrix** [comment]
Right, the formats are not designed to be nested. You cannot nest bold inside bold, or a link in a link. I'd also recommend one format per style.

**Comment by amyriounis** [comment]
@talldan @ellatrix thanks for your replies. Closing this one as this behavior is by design.
