### ISSUE TITLE
Moment.js localization strings are ignored.

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#16727]
**Describe the bug**
`setSettings()` of `date` ignores the localization strings for `relativeTime` of moment.js. Also the two existing `relativeTime` values are incorrect.

There is an existing [trac ticket](https://core.trac.wordpress.org/ticket/47373) for it.

**Comment by swissspidy** [comment]
Since there's a Trac ticket, it's a change that needs to happen in core only, no?

**Comment by manzoorwanijk** [comment]
@swissspidy, no that is not the case. The strings in Gutenberg are hard-coded as you can see [here](https://github.com/WordPress/gutenberg/blob/v6.1.1/packages/date/src/index.js#L67-L77). So the change is required here as well, otherwise the localization from the core will be ignored completely.
