### ISSUE TITLE
Verse Block vs Code Block

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#16720]
**Describe the bug**
I'm not sure if this qualifies as a bug. It's likely it was a design decision somewhere along the way - as odd as it might be.

Long to short, in the editor Verse wraps its content in a < pre > tags. But Code does not. Why not? Is this because Code doesn't use RichText (which would give it a toolbar.). 

Yet, on the frontend, both use the < pre > to wrap. 

Again, feels minor, but none the less odd. Perhaps, if not already done do, this could be documented somewhere? For the sake of history?

**Comment by talldan** [comment]
@AlchemyUnited It now uses pre, since Gutenberg 7.9.

Glad this has been resolved now, and the block should be consistent in the editor and the post.
