### ISSUE TITLE
An empty paragraph is added when using the Copy and Paste functionality

### ISSUE THREAD

**Issue by deeptiboddapati** [WordPress/gutenberg#16736]
Bug Description:
This bug happens when copying text from Google Docs, and pasting the text into the Gutenberg. Sometimes an empty paragraph block is is added in the middle of the other blocks. This means editors have to go back through the content to find and delete these empty blocks. 

This screen shot shows the empty paragraph block.

![GutenbergCopyPasteBug](https://user-images.githubusercontent.com/8887945/61807095-7d7aa980-adfe-11e9-9e90-d737bb4aa5d4.png)

**Comment by youknowriad** [comment]
Can you share the original good doc from which this happens?
