### ISSUE TITLE
Consider revising default quote and pullquote colors in dark mode. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16732]
When a theme [enables dark mode](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#dark-backgrounds), we change the color of many aspects of Gutenberg UI in order to accommodate a darker background. One thing we do not adjust is the color of Gutenberg-provided block styles. 

For instance, Gutenberg provides dark gray colors used in the quote and pull quote block borders: 

<img width="646" alt="Screen Shot 2019-07-24 at 9 13 59 AM" src="https://user-images.githubusercontent.com/1202812/61797001-91b9a900-adf4-11e9-915b-603ecc5d2219.png">

[If a theme opts in](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#default-block-styles), these are provided in the front-end as well, via the [`theme.css` stylesheet](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/quote/theme.scss). However, if a theme opts into dark mode, these elements are likely difficult (or impossible) to see by default: 

<img width="648" alt="Screen Shot 2019-07-24 at 9 14 26 AM" src="https://user-images.githubusercontent.com/1202812/61797338-35a35480-adf5-11e9-8fb7-be897611433c.png">

A theme can overwrite these styles, but I wonder if we should consider changing them when we know a theme has a dark background.

**Comment by mapk** [comment]
[Today's discussion in the design channel in slack](https://wordpress.slack.com/archives/C02S78ZAL/p1564502856190700) resulted in an agreement that this should be done.

I don't think we should rely on themes to handle this for us. It feels like part of the Gutenberg UI and should be accessible. I believe we change some styles elsewhere anyways, so let's continue here as well.

**Comment by senadir** [comment]
what colors should be used?

**Comment by kjellr** [comment]
> what colors should be used?

The quote block uses a [`$black` border by default](https://github.com/WordPress/gutenberg/blob/509c9cb18beb140f4e6ec6e87aad2986650cc833/packages/block-library/src/quote/theme.scss), and the [pullquote uses `$dark-gray-500`](https://github.com/WordPress/gutenberg/blob/5430dced1e3594ca28f5a9c829aa9baac8905e27/packages/block-library/src/pullquote/theme.scss#L2-L3). 

(I'm not sure why these are different, but) I'd suggest we just flip those to start, and use `$white` for the quote block and `$light-gray-500` for the pullquote.
