### ISSUE TITLE
is_admin returning false in backend in server side rendered block

### ISSUE THREAD

**Issue by cre-mer** [WordPress/gutenberg#16731]
I have a server side rendered block that lists cards with page thumbnails and the title wrapped in a link.
I want that the link only gets a href when I'm in the frontend so I avoid clicking on the cards by mistake in the backend and getting redirected to the card page.
Here is my code:
```
    $link = is_admin() ? ""
            : " href='" . get_permalink($post->ID) . "'";
                  
    echo <<<CPTItem
        <div class="cpt-list-item"><a class="cpt-list-item__link" $link>
    CPTItem;
```
Unfortunately is_admin() is returning false in the backend in the block itself. I really don't know why, the only thing I can think about is that it's because the block is server side rendered.
Is there a way around?

**Comment by Soean** [comment]
If you have a server side rendered block in the backend, it is rendered via the REST API endpoint `/wp/v2/block-renderer/xyz/blockname`. This endpoint calls your render function. In the frontend the render function is called directly. The function `is_admin()` checks if a backend page was requested. In a REST API Request is no backend page, so the function returns `false` on REST API requests.

Instead you can check, if it is a REST API request via: 
```php
if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
   echo 'Backend'; 
} else {
   echo 'Frontend';
};
```

Maybe we should add this info to the support handbook?

@cre-mer I also answered you question here: https://wordpress.stackexchange.com/questions/343583/is-admin-returning-false-in-backend-in-server-side-rendered-block/343592#343592 Please don't post support questions on both platforms.
