### ISSUE TITLE
media queries block development question

### ISSUE THREAD

**Issue by NasKadir123** [WordPress/gutenberg#16735]
Hi!
I registered a new block with padding for div:
```JSX
registerBlockType( ... {
...
margin: {
			type: "number",
			default: 0
		},
...
edit: ( props ) => { ....
	<div className={ classnames( 'new-block' ) } style={{ margin: margin }}>
	
		<RangeControl
			value={ margin }
			onChange= ( value ) => {
			setAttributes( { margin: value } );};
			min={ -200 }
			max={ 200 }
			allowReset
		/>
...
save: ( props ) => { ....
	<div className={ classnames( 'new-block' ) } style={{ margin: margin }}>
....
```

It works good, but now I want to add new padding for media queries for mobile.
So question is how can I add media queries for div style? Can you help me, please?
I will create new attribute:
	mobileMargin: {
			type: "number",
			default: 0
		}
but then I don't know what to do? I can't add @media screen( max-width 430px ) to my div style.
Thanks.

**Comment by Soean** [comment]
Hi there!

As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you for your understanding.

**Comment by NasKadir123** [comment]
> Hi there!
> 
> As mentioned in our help request template, this repository is for tracking bugs and features to be worked on and is not meant for help requests.
> 
> For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.
> 
> Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.
> 
> You may also ask for technical support at https://wordpress.stackexchange.com/.
> 
> Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.
> 
> Thank you for your understanding.

Ohh, sorry! Thanks for your answer!
