### ISSUE TITLE
Preview link clicked - save a revision

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1673]
If anything was changed before the manual saving (previous version of content) and Preview link click - save content as a revision and then open a post preview (with updated data).

This will give ability to actually save a draft somehow (see related #1672) and preview the latest version of content after the last saved copy and what is currently available in content area.

**Comment by westonruter** [comment]
We should also take this as an opportunity to ensure that postmeta are included in the revision. See also https://core.trac.wordpress.org/ticket/20564 but alternatively as I'm proposing in https://github.com/WordPress/gutenberg/issues/1516#issuecomment-313246865 we could also use the a Customizer changeset to preview changes to posts and postmeta, which would also help 
address the concern about an explosion in the number of postmeta fields being inserted.

**Comment by mtias** [comment]
Saving when clicking preview has been implemented.
