### ISSUE TITLE
A closing angle bracket as &gt in a SyntaxHighlighter code

### ISSUE THREAD

**Issue by bravikov** [WordPress/gutenberg#16743]
**Screenshots**

![Selection_052](https://user-images.githubusercontent.com/700868/61817702-d3c80680-ae57-11e9-9161-fcb63bd4b204.png)
![Selection_051](https://user-images.githubusercontent.com/700868/61817704-d4609d00-ae57-11e9-93c8-874f7ad92b16.png)

- wordpress.com blog
- OS: Ubuntu 18.04
- Chrome 59

**Comment by senadir** [comment]
cannot reproduce this issue, can you try using a different keyboard or copy paste this code
```
#include <iostream>

int main()
{
    return 0;
}
```

![image](https://user-images.githubusercontent.com/6165348/61994544-888a3f80-b073-11e9-933d-e53473e12976.png)
![image](https://user-images.githubusercontent.com/6165348/61994545-8de78a00-b073-11e9-8e02-b99b121e2c05.png)

**Comment by youknowriad** [comment]
I believe this might be related to a third-party code block adding syntax highlighting which is not in Gutenberg by default. You might want to raise the issue in the plugin's tracker.

**Comment by youknowriad** [comment]
You're mentioning wordpress.com, you could contact the support there, they'll help you track this bug.

**Comment by pauljacobson** [comment]
If anyone experiences this issue on WordPress.com, here's a related issue:

https://github.com/Automattic/wp-calypso/issues/34826
