### ISSUE TITLE
Column block: Add block icon (+) is hidden under column toolbar

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16742]
**Describe the bug**
There's a situation that when the column in a Column block is selected, a user can hover just in the right spot to reveal a hidden "Add block" inserter icon. 

**To reproduce**
1. Add a Column block.
2. Add some content to a column.
3. Click up to the Column level and hover right above the content block within the column.
4. Observe the Inserter `+` icon appear but hidden under a toolbar.

**Expected behavior**
I expect the icon to be completely visible or not show at all. It's a weird situation.

**Screenshots**

![column-addblock](https://user-images.githubusercontent.com/617986/61816444-38a44200-ae01-11e9-844f-2dbfb4ed33ef.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1.1

**Comment by karmatosed** [comment]
I 'think' this should just be a case of a z-index bug and maybe doesn't need design? For me, it should be visible no matter what. I'll swap out labels but happy to change that.

**Comment by ZebulanStanphill** [comment]
Related: #13571

**Comment by enriquesanchez** [comment]
[Discussed during today's design triage meeting in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1564504694212200) ([login required](https://make.wordpress.org/design/handbook/get-involved/first-steps/)).

The team agreed that applying z-index would not take care of the underlying issue. It was suggested to explore only showing block mover icons when the block is selected and to perhaps rethink sibling inserters to find different ways they can exist.

**Comment by mapk** [comment]
Only showing block movers when the block is selected is being worked on here: https://github.com/WordPress/gutenberg/pull/16745

**Comment by mapk** [comment]
Actually, nevermind... that other one is a duplicate of this one which has already been merged. https://github.com/WordPress/gutenberg/pull/17315

**Comment by mapk** [comment]
Just tested and this isn't resolved because the mover icons aren't the issue. Darnit! So still need to rethink the Sibling Inserter here and the interaction.

**Comment by karmatosed** [comment]
@mapk would you mind testing this on master please? I am not getting it right now but this could be me missing a recreation step.

**Comment by karmatosed** [comment]
It would be great to have this worked on as part of #18667

**Comment by mapk** [comment]
Just tested again today in `master`. I still see the issue. Albeit it was a bit more difficult to get to this problem though due to traversing up from nested columns seems harder nowadays without the additional parent block borders.

**Single Column selected:**
![Screen Shot 2019-12-16 at 2 33 17 PM](https://user-images.githubusercontent.com/617986/70948790-178ef880-2011-11ea-98ee-430b51fe591d.png)

**and Columns block selected:**
![Screen Shot 2019-12-16 at 2 35 53 PM](https://user-images.githubusercontent.com/617986/70948925-6dfc3700-2011-11ea-930a-7269362c9037.png)

**Comment by youknowriad** [comment]
This seems fixed in my testing. We still have the issue that it's impossible to insert a block at the beginning of the column but this is tracked separately #16094
