### ISSUE TITLE
Build Tooling: Collapse or omit successful test results from Travis build

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#16744]
In order to reduce contributor friction resulting from a failing build, we should seek to keep build results as actionable as possible. A failing Jest build is difficult to decipher because it includes potentially thousands of passing test cases. In these situations, usually only the failed test is relevant for the contributor.

Example: https://travis-ci.com/WordPress/gutenberg/jobs/211276270

**Task:** Logging for successful tests should be silenced or collapsed.

**Relevant Details:**

- Travis internally uses special prefixes for its own logging collapsing, `travis_fold:start:FOO` and `travis_fold:end:FOO` ([example](https://github.com/BanzaiMan/travis_production_test/blob/34004d93b62e1dbaf0b71f7d3697ccc3fc9a759d/.travis.yml#L9-L12)). These could be used for collapsing log output of the successful test cases.
- PHPUnit tests "show" all tests run, but simply display a "." dot character for the successful tests ([example](https://travis-ci.com/WordPress/gutenberg/jobs/219168198))
- At a glance, [Jest CLI options](https://jestjs.io/docs/en/cli) don't appear to support this use-case, but we could use a custom [reporter](https://jestjs.io/docs/en/cli#reporters) to customize the output (e.g. [`jest-silent-reporter`](https://github.com/rickhanlonii/jest-silent-reporter), [`jest-simple-dot-reporter`](https://github.com/jodonnell/jest-simple-dot-reporter))

**Comment by epiqueras** [comment]
https://github.com/rickhanlonii/jest-silent-reporter works well. Should we just add that?

**Comment by aduth** [comment]
> https://github.com/rickhanlonii/jest-silent-reporter works well. Should we just add that?

It seems like a good option.

**Comment by epiqueras** [comment]
A folding one would be better, but I can't find one.

**Comment by aduth** [comment]
> A folding one would be better, but I can't find one.

It's maybe needlessly complex, but there might be something with:

1. Use [`jest-standard-reporter`](https://github.com/chrisgalvan/jest-standard-reporter) to partition logging between `stdout` and `stderr`
2. [Redirect outputs](https://askubuntu.com/a/625230) to two files for `stdout` and `stderr`
3. Echo the contents of `stdout` file between the Travis start and end tags for folding
4. Echo the contents of `stderr` file outside/after the folded success output
5. Delete the files

**Comment by epiqueras** [comment]
I'd rather build a reporter that does that instead of hacking it in a script that creates files.
