### ISSUE TITLE
Problem with Captions in Chrome

### ISSUE THREAD

**Issue by martinfritch** [WordPress/gutenberg#16754]
We are having a recurring issue with captions, and appears to not work in Chrome.  The blog editors enter an image block using the image size select in the media and enter a caption.

The image and caption look fine in the editor.  However, when the blog post is published the caption is wrong in Chrome.  In Firefox, the caption is centered under the image, but in Chrome the caption is smashed up against the left side of the space.

Examining the elements in Firefox, the element is `<figcaption style="width: 724px;">` but the element in Chrome is `<figcaption style="width: 0px;">`

![CaptureA](https://user-images.githubusercontent.com/15878459/61889174-eb90a080-aed2-11e9-9229-b688166a4f4b.PNG)

**Comment by youknowriad** [comment]
hi There! Can you share which theme are you using? The theme stylesheets can affect this. I've just tried in the Twenty Nineteen team and I was not able to reproduce.

**Comment by martinfritch** [comment]
It's a custom theme, unfortunately.  Also, it doesn't occur 100% of the time, only maybe once out of 10 or so blog posts.  I've been trying to determine if the writers are doing something different on the times the problems occur, but they swear they are being consistent.

**Comment by youknowriad** [comment]
Try debugging the CSS of your custom theme. Something should be conflicting.
