### ISSUE TITLE
Copy: Inconsistent capitalization of labels in tooltips and dropdown menus

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#16764]
Related: #12366.

Some examples of tooltips existing as of today in different places of the block editor:

![Screen Shot 2019-07-26 at 10 05 36](https://user-images.githubusercontent.com/699132/61936716-95346800-af8d-11e9-88df-48fb8110ccf8.png)
![Screen Shot 2019-07-26 at 10 05 40](https://user-images.githubusercontent.com/699132/61936717-95ccfe80-af8d-11e9-8fb0-c167ab258eb3.png)
![Screen Shot 2019-07-26 at 10 05 47](https://user-images.githubusercontent.com/699132/61936718-95ccfe80-af8d-11e9-9237-3176562e57a7.png)
![Screen Shot 2019-07-26 at 10 05 52](https://user-images.githubusercontent.com/699132/61936719-95ccfe80-af8d-11e9-9189-dcfcc1523ccd.png)
![Screen Shot 2019-07-26 at 10 06 04](https://user-images.githubusercontent.com/699132/61936721-95ccfe80-af8d-11e9-9784-4a4e885385ee.png)
![Screen Shot 2019-07-26 at 10 06 08](https://user-images.githubusercontent.com/699132/61936722-96659500-af8d-11e9-8d22-bf52f7231363.png)
![Screen Shot 2019-07-26 at 10 06 12](https://user-images.githubusercontent.com/699132/61936723-96659500-af8d-11e9-823b-2801bee920ce.png)
![Screen Shot 2019-07-26 at 10 06 17](https://user-images.githubusercontent.com/699132/61936724-96659500-af8d-11e9-8f94-e6e3c2db3eb3.png)
![Screen Shot 2019-07-26 at 10 06 25](https://user-images.githubusercontent.com/699132/61936725-96659500-af8d-11e9-8cd2-9fbdba912532.png)

Some examples of dropdown menus:

![Screen Shot 2019-07-26 at 10 11 04](https://user-images.githubusercontent.com/699132/61936841-d298f580-af8d-11e9-8d01-3e6d01ba052c.png)
![Screen Shot 2019-07-26 at 10 11 09](https://user-images.githubusercontent.com/699132/61936842-d3318c00-af8d-11e9-94a0-1f71d68d75e6.png)
![Screen Shot 2019-07-26 at 10 11 13](https://user-images.githubusercontent.com/699132/61936843-d3318c00-af8d-11e9-91e9-3380cdf2a585.png)
![Screen Shot 2019-07-26 at 10 11 46](https://user-images.githubusercontent.com/699132/61936851-d6c51300-af8d-11e9-9e80-4955cb5a4c1d.png)

When working on #16557 I also noticed this interesting case where the same controls can be displayed in the dropdown or inline:

![Screen Shot 2019-07-26 at 10 13 25](https://user-images.githubusercontent.com/699132/61936966-17bd2780-af8e-11e9-9905-bf58e1e845a7.png)
![Screen Shot 2019-07-26 at 10 13 32](https://user-images.githubusercontent.com/699132/61936967-17bd2780-af8e-11e9-93e9-06136af5729a.png)

In both cases, they use the same labels. My proposal is to use the same capitalization in tooltips as we do for labels in dropdown menus to make everything easier.

**Comment by gziolo** [comment]
@mapk and @karmatosed - do we have guidelines around it?

**Comment by karmatosed** [comment]
Core usese:

![image](https://user-images.githubusercontent.com/253067/62065606-3be76580-b227-11e9-808b-35d7613b6ac4.png)


That feels like the best pattern to stick to and be consistent.

**Comment by sarahmonster** [comment]
From our [copy guidelines](https://developer.wordpress.org/block-editor/contributors/document/copy-guide/#five-pay-attention-to-capitalization):

> Feature names and dashboard sections typically use title case (think “Site Stats” or “Recently Published”), whereas feature labels typically use sentence case (like “Show buttons on” or “Comment Likes are,” where “Likes” is capitalized because it’s the feature name, but the overall label is using sentence case).

It sounds like we may need to give more examples here to make it super clear for future usage as well.

The above rather reads as though tooltips and the like would be classified as "feature labels" (and thus should use sentence case), but the majority of these seem to be using title case. 

The [guidelines for core](https://make.wordpress.org/core/handbook/best-practices/spelling/#capitalization) say that the following should use title case:

> Labels
> Button labels
> Actions

Again, this may be a bit vague and warrants further clarification (is a tooltip a label?) once we've decided on a pattern here. More explicit guidelines may be required to ensure a more consistent experience.

Seems like most tooltips in wp-admin use sentence case:

![2019-07-29 22 45 26](https://user-images.githubusercontent.com/376315/62085108-b24d8d00-b252-11e9-9d75-69d930f4b70c.gif)

**Comment by afercia** [comment]
Previously: https://github.com/WordPress/gutenberg/pull/4832 / https://github.com/WordPress/gutenberg/issues/4325

**Comment by gziolo** [comment]
In the example, @sarahmonster shared, there is this exact issue which triggered my willingness to unify everything. You see `Add Contact Form` (title-case) as the label of the button in the top section but in the toolbar, there is `Add contact form` (no title-case) in the tooltip. In addition, we are planning to introduce a setting which allows displaying tooltips as labels for icon-only buttons. It would be much easier to have one way of handle all those 3 use cases with one version of text rather than provide 2 or 3 versions depending on the context. This would also further simplify the process of translation. Otherwise, we will have to add logic which displays a proper version of the text.

**Comment by afercia** [comment]
Some past (Dec. 2014) conversation on Slack about title-casing: https://wordpress.slack.com/archives/core/p1418759343002024

Personally, I'm not sure I understand all this extensive usage of title-casing. I do realize it's more a traditional thing in English typography. However, title-casing it's not used in many other countries. 

In Europe, it's very rarely used. Just have a quick look at the most important online newspapers from France, Germany, Spain, Italy, etc. and even UK: no title-casing there. Can anyone provide an example of a big news site that uses title-casing? I doubt it's used on US big news sites as well.

A few quick questions 🙂 
- Why WordPress uses title-casing so extensively?
- Is there any good reason to do that?
- Does it improves readability in any way?
- Is there any data to support it's better?

I can only tell that one of the items in the Italian polyglots guidelines is to avoid title-casing at all costs.

That said, inconsistencies in the admin are everywhere so this is not just a Gutenberg issue. Example:

"Remove From Bulk Edit"
"Restore from Trash"

Any reason why `from` is title-cased in the first sentence and it's not in the second sentence?

Also, there are cases of _slightly excessive_ usage of title-casing. For example, thing like

"Log Out Everywhere Else" (formerly "Log Out of All Other Sessions")

look a bit excessive to me. 

Overall, I'd tend to think the intent to reduce inconsistency is very valuable but maybe the best option would be to drastically simplify and just use normal sentence-casing.

**Comment by gziolo** [comment]
> Overall, I'd tend to think the intent to reduce inconsistency is very valuable but maybe the best option would be to drastically simplify and just use normal sentence-casing.

I'm fine with that as well. Whatever makes more sense and makes life simpler for developers, translators, and more importantly users. 



> In Europe, it's very rarely used. Just have a quick look at the most important online newspapers from France, Germany, Spain, Italy, etc. and even UK: no title-casing there. Can anyone provide an example of a big news site that uses title-casing? I doubt it's used on US big news sites as well.

The same applies to Polish. Some examples from Facebook:

![Screen Shot 2019-07-30 at 21 24 03](https://user-images.githubusercontent.com/699132/62158754-8264bf00-b310-11e9-9144-07bcb68e89aa.png)
![Screen Shot 2019-07-30 at 21 23 41](https://user-images.githubusercontent.com/699132/62158753-8264bf00-b310-11e9-80fd-4f6d08f0da4f.png)
![Screen Shot 2019-07-30 at 21 24 19](https://user-images.githubusercontent.com/699132/62158755-82fd5580-b310-11e9-901e-6bb8b6568773.png)
![Screen Shot 2019-07-30 at 21 24 27](https://user-images.githubusercontent.com/699132/62158756-82fd5580-b310-11e9-8383-b1cdccbd4a63.png)

By the way, GitHub uses sentence case for buttons :)

**Comment by mapk** [comment]
Based on @sarahmonster's [digging](https://github.com/WordPress/gutenberg/issues/16764#issuecomment-516175904), other comments in this thread, and my own personal feelings 😉, I'm much more inclined to use Sentence-case for the tooltips. I'm sure we can add documentation to support this decision, but this can be justified by saying tooltips are not "Labels, Button Labels, or Actions" so we should be good to go.

**Comment by karmatosed** [comment]
Can we loop back to core a patch to also change that? I know it's a big ask but unifying here would be a nice addition.

**Comment by enriquesanchez** [comment]
Regarding the accessibility of sentence case vs. title case, there does not seem to be any consensus or formal studies that prioritize one over the other.

I was able to dig this [Microsoft study](https://docs.microsoft.com/en-us/typography/develop/word-recognition) that briefly touches on the topic of alternating case, which is not exactly what's being discussed here, as it refers to a single word.

It does however offer some insights that I think can be expanded to our situation:

> The fourth piece of evidence supporting the word shape model is that it is difficult to read text in alternating case. AlTeRnAtInG case is where the letters of a word change from uppercase to lowercase multiple times within a word. The word shape model predicts that this is difficult because it gives a pattern of ascending, descending, and neutral characters that is different than exists in a word in its natural all lowercase form. Alternating case has been shown to be more difficult than either lowercase or uppercase text in a variety of studies. Smith (1969) showed that it slowed the reading speed of a passage of text, Mason (1978) showed that the time to name a word was slowed, Pollatsek, Well, & Schindler (1975) showed that same-difference matching was hindered, and Meyer & Gutschera (1975) showed that category decision times were decreased.

I vote for consistency but also maintainability. I think title case will lead to more errors and inconsistency in the future, since it's not an international practice.

Also, have y'all seen that we use title case for our GitHub labels? 😝

**Comment by afercia** [comment]
> I vote for consistency but also maintainability. I think title case will lead to more errors and inconsistency in the future, since it's not an international practice.

+1 to this 🙂 

> Also, have y'all seen that we use title case for our GitHub labels?

🙈

**Comment by sarahmonster** [comment]
WordPress uses a lot of title case. I'd love to see us start to shift toward more sentence case where possible:
- It's easier to pick out proper nouns (or any nouns, in the case of German).
- It's more internationally universal, reflecting WordPress' varied global user base. (See also: German.)
- Fewer inconsistencies and variation. Everyone knows how to apply sentence case, but title case isn't as clear. (Do you capitalise articles and prepositions? What about conjunctions?)
- Easier to read when strings get long because it mirrors how we read body copy. (I didn't find any research to back this, but If You Write A Sentence Something Like This It Sort of Forces You To Stop At Every Word And Feels Rather Stilted.)
- It's friendlier. Title case feels very formal, and WordPress may want to be more casual in voice & tone.
- Clearer application ("Does this require title or sentence case?" questions are simpler to answer when the correct response is always "sentence case").

Some more reading on the topic:
- https://www.precisioncontent.com/blog/sentence-case-versus-title-case-for-topic-based-authoring/
- https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98
- https://uxplanet.org/why-letter-casing-is-important-to-consider-during-design-decisions-50402acd0a4e
- https://www.herosmyth.com/article/headline-capitalization-ux-title-case-vs-sentence-case
- https://blog.prototypr.io/sentence-case-or-title-case-5bd581f05d88

**Comment by karmatosed** [comment]
@enriquesanchez we use title case for labels because it was used in other interactions. It's a loop where it was first in core then propagated throughout :)

**Comment by mapk** [comment]
Can we unpropagate it? Like what if we start using Sentence case in Gutenberg and at least submit a Trac issue for Core? A little reverse-propagation never hurt anyone, right? 😉

**Comment by gziolo** [comment]
> Can we unpropagate it? Like what if we start using Sentence case in Gutenberg and at least submit a Trac issue for Core? A little reverse-propagation never hurt anyone, right? 😉

I’d love to see it happen. It was my intention that we bet on one approach and apply it everywhere. I must admit that seeing GitHub using sentence case for buttons every time I comment here convinced me to follow this approach. 😃

**Comment by gziolo** [comment]
#17336 fixes it only partially.

**Comment by mapk** [comment]
While #17336 fixes the tooltips, we now need another PR to cover the popover component and change those options to Sentence Case too. 

**Examples:**

![61936851-d6c51300-af8d-11e9-9e80-4955cb5a4c1d](https://user-images.githubusercontent.com/617986/64907679-84a98f80-d6aa-11e9-932d-a203e7b13da1.png)

![61936966-17bd2780-af8e-11e9-9905-bf58e1e845a7](https://user-images.githubusercontent.com/617986/64907681-896e4380-d6aa-11e9-9ad6-831815bd5079.png)

**Comment by karmatosed** [comment]
@mapk as we now have a PR in #18758, could this be closed?

**Comment by mapk** [comment]
Yep! PR is merged, let's close this!

**Comment by gziolo** [comment]
Awesome work @karmatosed and @mapk. Thank you for wrangling it. It should make everything more consistent :)
