### ISSUE TITLE
Gutenberg – PrePublish Panel

### ISSUE THREAD

**Issue by rajmera** [WordPress/gutenberg#16768]
I would like to integrate the pre publish panel into my plugin, but when I looked at the PostPublishPanelPrepublish component, it’s not exported and hence not available for use.

Same is the case with other components like, MaybePostFormatPanel and MaybeTagsPanel.

Can this be fixed?

**Comment by senadir** [comment]
I'm not really sure about this side of code, but if what you're to do is integrating your plugin in the editor & the side panel, you can try looking into Slots & Fills

**Comment by chrisvanpatten** [comment]
@senadir I believe what @rajmera is saying is that they want to use the component itself, but it isn’t exported so it can’t be reused without copying the code.

There [is a slotfill available](https://github.com/WordPress/gutenberg/blob/ca1a39a20e85e71beac16c56727e19d6bee6a243/packages/edit-post/src/components/sidebar/plugin-pre-publish-panel/index.js) to insert content into this panel, but it doesn’t solve the problem of reusing the entire component.

**Comment by senadir** [comment]
I'm not if this is a technical choice or something that was forgotten, better wait for someone who worked on that component for a comment

**Comment by rajmera** [comment]
@chrisvanpatten you are correct. That is exactly what we are looking for. 

Oasis Workflow plugin registers a plugin as a sidebar and while performing one of the actions, we loose the ability to add the  PostPublishPanelPrepublish into our component.

If this component was exported, we could have easily used into our plugin.

Let me look into it and see if I can export it into a PR for it to be reviewed.

**Comment by youknowriad** [comment]
We don't want to expose all of our components because if we do so, we'll never be able to change them if we decide to change the content or the design of such components. For each component exposed we need to ensure that it's something that can be maintained forever.
