### ISSUE TITLE
Columns: Changing from predefined layout can create a column overlap

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#16785]
**Describe the bug**
Add the Column block.
Select one of the predefined column layouts that do not have equal column widths.

![Screen Shot 2019-07-28 at 03 59 52](https://user-images.githubusercontent.com/5323259/62001220-3a655280-b0ec-11e9-910c-86456af62790.png)

For instance layout 5 with 3 columns. Two smaller on the sides and a bigger in the middle.
Result:
![Screen Shot 2019-07-28 at 04 05 48](https://user-images.githubusercontent.com/5323259/62001271-15bdaa80-b0ed-11e9-88ce-9994220959db.png)

Change the column width from 3 to 4.
Result might look like this:

![Screen Shot 2019-07-28 at 04 05 58](https://user-images.githubusercontent.com/5323259/62001277-2a9a3e00-b0ed-11e9-9455-043cd9d55aff.png)

**Desktop (please complete the following information):**
 - OSX 10.13.6
 - Chrome in Desktop Server.
 - Gutenberg plugin version: 6.1.1

Btw I made a little longer video showing the status how columns are at present:
https://youtu.be/gfrrDEMU5Zg

**Comment by youknowriad** [comment]
I'm not able to reproduce. I remember fixing this in some unrelated PR.

**Comment by paaljoachim** [comment]
I just tested and adding/subtracting columns now works nicely! Thanks!
