### ISSUE TITLE
Changing slug or post name is not possible when having custom permalinks

### ISSUE THREAD

**Issue by katsar0v** [WordPress/gutenberg#16786]
**Describe the bug**
Changing postname not possible.

![gif1](https://user-images.githubusercontent.com/7236157/62002993-91c8ea00-b10f-11e9-8e62-bc0f8c0cbd56.gif)

**To reproduce**
1. Use this filter for custom permalinks:
```
function append_query_string( $url, $post, $leavename=false ) {
	if ( $post->post_type == 'post' ) {
    $url = get_site_url() . '/bg/' . $post->post_name . '/';
	}
	return $url;
}
add_filter( 'post_link', 'append_query_string', 10, 3 );
```
2. Try to change the slug or name of a post

**Expected behavior**
I expect to somehow change the name of the post, currently there is no possibility in Gutenberg. In the old editor, the post name could be enabled in screen options and then changed.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04
 - Browser Chromr
 - Version Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by katsar0v** [comment]
Is there any update on this?

**Comment by joyously** [comment]
When are you expecting that filter to run?
Are you aware that `get_site_url()` is for getting the WordPress URL, not the URL that the visitor sees? (sometimes they are the same, but not always)

**Comment by chrisvanpatten** [comment]
I sent this in WP Slack but I believe the problem is that your filter function is not obeying the `leavename` flag. Gutenberg looks for the presence of the permalink token to determine if the slug can be changed. Something like this may work:

```php
function append_query_string( $url, $post, $leavename = false ) {
    if ( $post->post_type == 'post' ) {
        $token = $leavename ? '%postname%' : $post->post_name;

        $url = get_site_url() . '/bg/' . $token . '/';
    }

    return $url;
}
add_filter( 'post_link', 'append_query_string', 10, 3 );
```

**Comment by katsar0v** [comment]
I will try the `$leavename` variable, thanks.

@joyously what do you mean? I use `get_site_url` to get the site url of wordpress :)

**Comment by katsar0v** [comment]
@chrisvanpatten you are right, this has helped me, thank you for the fix!

**Comment by joyously** [comment]
> @joyously what do you mean? I use get_site_url to get the site url of wordpress 

I mean you can install WordPress in a folder and have it control the root, or be in multisite, and your code would not work right.

**Comment by katsar0v** [comment]
Ah yeah, correct, well that's not the case, but thanks for the advice!
