### ISSUE TITLE
Is the current position of trash logical?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1679]
I was writing a post and out of the corner of my eye saw the red trash icon. A few things struck me:

- It is really easy to lose where it is.
- It doesn't feel like it belongs with the actions near it. For example, should it maybe go here?

![2017-07-03 at 20 57](https://user-images.githubusercontent.com/253067/27806474-ae27796c-6032-11e7-8bf7-6b48495dd461.png)

**Comment by elzette** [comment]
Your comments is kind of related to mine. When I started setting up a post it was not obvious where the Save button is. It is not a button and feels far out. 
For me that tie in with what @karmatosed said - the bin / trash should be there far out and the Save as a button with the other actions?

**Comment by jwold** [comment]
1. Personally I'm ok with the trash button being down in a corner. I expect trash to be a bit more hidden when it comes to deleting an article. 
2. Not sure about the save button location. I think I'm ok with it where it's at.

**Comment by mtias** [comment]
@karmatosed do you still want to explore alternatives or should we close?

**Comment by karmatosed** [comment]
I still feel it's an issue but I would like to close and consider feedback when we focus on usability testing at full force.
