### ISSUE TITLE
Reusable blocks preview not working.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#16808]
The preview that shows when you hover reusable blocks in the inserter has regressed. It shows:

<img width="705" alt="Capture d’écran 2019-07-30 à 12 13 01 PM" src="https://user-images.githubusercontent.com/272444/62124966-8e765f80-b2c3-11e9-930c-51fc96e716b9.png">

I tried debugging quickly. I think the issue comes from the fact that we use an embedded editor (separate blocks store) but we don't load the content of the reusable blocks in the sub reducer.

**Potential solutions**

 - Refactor the reusable blocks to use an embedded editor (There's some PRs in progress)
 - try to load the reusable blocks in the BlockEditorProvider used for the preview.

**Questions**

This used to work, so I'm curious when it regressed and what's the "hack" that allowed it to work previously.

cc @aduth @jorgefilipecosta

**Comment by aduth** [comment]
I'm having trouble with my local environment when running Gutenberg at older commits, but I wonder if it might have something to do with #14678, and the fact that the blocks store for the reusable blocks preview would now be separate from the top-level? 

https://github.com/WordPress/gutenberg/blob/87d5d5a19e9f57ba6414d51c19657fb6ed6b7d81/packages/block-editor/src/components/block-preview/index.js#L35-L40

Maybe simple enough to `useSubRegistry={ false }` ?

**Comment by aduth** [comment]
I'm not able to reproduce the issue in master, however?

**Comment by youknowriad** [comment]
Interesting, we were two people reproducing the error with @getdave I might have to check again tomorrow.

**Comment by marekhrabe** [comment]
I've been definitely seeing it for weeks in previews.

**Comment by youknowriad** [comment]
It is introduced by https://github.com/WordPress/gutenberg/issues/16808
