### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by cre-mer** [WordPress/gutenberg#16809]
There is an unnecessary comma after 'PluginMoreyMenuItem' here:
[const { PluginMoreyMenuItem,} = wp.editPost;](https://github.com/WordPress/gutenberg/blob/e91dc282dbf5f111225592c31976ef1ce80a4645/docs/designers-developers/developers/slotfills/plugin-more-menu-item.md#L9)

**Comment by rbrishabh** [comment]
Can I take this up?

Thanks!

**Comment by aduth** [comment]
@rbrishabh Yes, feel free!
