### ISSUE TITLE
Ability to save and add groups of blocks with default content

### ISSUE THREAD

**Issue by Idealien** [WordPress/gutenberg#1680]
Definitely Enhancement.
This issue is opened to explore the idea of register / save groups of blocks with default/placeholder content. It may be a better fit as a part of the customizer enhancements?

**Use Case 1 - New Theme for Existing Site**
Default content feature with 4.7 / 2017 addressed part of this issue for new sites looking as good "out of box" as the preview pictures. But an existing site transitioning to a new theme site still struggles. Offering the theme developer ability to register groups of text + image blocks would change the ramp up from "Create a new page, add these 10 blocks, put these 4 settings and swap in your images" to "Create a new page, select the Home Page Layout 2, and edit the text".

**Use Case 2 - Repetitive Content Scenarios**
For authors that create multiple pages that have common groups (which are not stored as separate CPT / meta) it would offer the ability to save a set of blocks. Example: Golf leagues with weekly prize types, meeting agenda templates, regular blog series, etc.

**Use Case 3 - Plugin Jumpstart**
Same as Use Case 1 but tailored towards plugins that may use a series of blocks as "dashboard" or to offer sites the ability to make a layout "exactly like the demo site" without forcing page creation into the plugin activation cycle.

**Comment by youknowriad** [comment]
related #1516

**Comment by karmatosed** [comment]
I feel that this issue does fall under #1516. For now, lets make sure the discussion happens in one place. If I am wrong, we can reopen.
