### ISSUE TITLE
Navigation Block: Data View 

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16812]
Regardless of how the UI evolves for this block, I think there will always be a need for representing the menu structure as a child block tree with all menu hierarchies mapped out consistently and not hidden (dropdowns, etc).

Luckily, we already have a view that handles that representation in the "block navigator". That means if the navigation menu block is represented through child blocks, we'll get this view for free. Furthermore, if we allow drag and drop to reorder items in the navigator (see #11408) we'll also inherit it, making interactions more reliable and consistent with much higher chances of shared improvements and accessibility.

We can also probably look at rendering this view inline or in a modal from the navigation menu block itself.

**Comment by talldan** [comment]
I'll pick this up. To start with I'll stick with a toolbar button that opens the block navigator (for the current nav block) in a modal.

**Comment by talldan** [comment]
I've knocked together a PR. Would be great to get some testing on it and think about how we want it to evolve.
