### ISSUE TITLE
Navigation Block: add support for vertical menus

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#16829]
Both horizontal (e.g. in a header) and vertical (e.g. in a sidebar) menus should be supported by the Navigation block.

**Comment by melchoyce** [comment]
As an example, I'm working on designing a theme right now that would benefit from having a vertical menu block:

![image](https://user-images.githubusercontent.com/2846578/72453659-7620d100-378d-11ea-993d-79ed233c397f.png)

Currently, there's no way to achieve this using the navigation block without using a bunch of CSS hacks. Native support would be helpful for achieving this kind of menu design in Gutenberg themes.

**Comment by mtias** [comment]
Agree this should be achievable. It'd be good to explore using this API for it: #16283.

**Comment by mtias** [comment]
Notice this could be a great case for using the `variations` system if we want to make it easily discoverable in the inserter.

**Comment by paaljoachim** [comment]
The question is then how to add a way to make the navigation vertical.
Some options as I see it.
A control in the sidebar to switch the navigation between horizontal/vertical.
A Styles pattern. User selects the vertical pattern.
A narrow alignment option that pushes the navigation to become vertical.

Styles
![Screen Shot 2020-03-17 at 23 01 39](https://user-images.githubusercontent.com/5323259/76906007-5e57ed00-68a3-11ea-82eb-a7766d900d48.png)

Selected Navigation
![Screen Shot 2020-03-17 at 23 08 03](https://user-images.githubusercontent.com/5323259/76906425-3026dd00-68a4-11ea-9670-054c3366a502.png)

Alignment
![Uploading Screen Shot 2020-03-17 at 23.09.07.png…]()

**Comment by karmatosed** [comment]
> Notice this could be a great case for using the variations system if we want to make it easily discoverable in the inserter.

@mtias are you suggesting have 2 types of navigation blocks?

**Comment by paaljoachim** [comment]
Btw here is something similar. Placing buttons in a vertical line.
https://github.com/WordPress/gutenberg/pull/20160#issuecomment-601018891
