### ISSUE TITLE
Block toolbars misaligned on desktop for inner blocks within a full width block

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#16837]
6.2 seems to have introduced a regression to how the toolbars are positioned.

Before:
<img width="442" alt="Screen Shot 2019-07-31 at 14 11 16" src="https://user-images.githubusercontent.com/704594/62214552-301daf80-b39d-11e9-9250-6f6bffbe1d65.png">

After:
<img width="392" alt="Screen Shot 2019-07-31 at 14 10 09" src="https://user-images.githubusercontent.com/704594/62214558-357afa00-b39d-11e9-9794-10db97761c77.png">

Having a very quick look into it, seems like a media query is being applied setting `left` to `14px`. Setting it back to `1px` seems to have fixed the visual glitch:

<img width="317" alt="Screen Shot 2019-07-31 at 14 13 07" src="https://user-images.githubusercontent.com/704594/62214629-5b080380-b39d-11e9-9815-61c0857caf79.png">

Right aligned elements (such as images and buttons) seem to be totally broken and the toolbar is positioned offset from the actual block UI which hides behind the block inspector. (Note: I'm using a custom component to handle linking the button, but reverting back to the default behaviour still has the problem, ruling out this being a modification issue).

Before:

<img width="455" alt="Screen Shot 2019-07-31 at 14 26 59" src="https://user-images.githubusercontent.com/704594/62215877-a6bbac80-b39f-11e9-9b3a-b351c4db6c2d.png">

After:

<img width="635" alt="Screen Shot 2019-07-31 at 14 29 02" src="https://user-images.githubusercontent.com/704594/62215886-ab806080-b39f-11e9-9816-bbd5ff18b4f9.png">

**Comment by paulwilde** [comment]
I tested this with a default theme (Twenty Nineteen) and no addition plugins installed and the issues seem to be there, so it's not an issue with some modification conflicts.

**Comment by paulwilde** [comment]
I've found the culprit: https://github.com/WordPress/gutenberg/pull/16579

**Comment by kjellr** [comment]
Thanks for the report, @paulwilde. It looks like the styles from #16579 are unnecessarily being inherited by the nested block children. Should be fixed in #16858.
