### ISSUE TITLE
Icon component causes invalid or unexpected content error

### ISSUE THREAD

**Issue by narthur** [WordPress/gutenberg#16844]
**Describe the bug**
Using the Icon component in a Gutenberg block results in invalid content error on editor refresh. The "Resolve" action shows that it wants to change the SVG "viewbox" attribute to "viewBox"

**To reproduce**
1. Use a block containing the `wp.components.Icon` component.
2. Save the page.
3. Refresh the editor.
4. Notice the invalid content error, and click "Resolve" to see found difference.

**Expected behavior**
Using `wp.components.Icon` should not trigger an invalid content error.

**Screenshots**

![Screen Shot 2019-07-31 at 3 49 51 PM](https://user-images.githubusercontent.com/4655422/62243470-56e2e280-b3ab-11e9-9226-0e26667bda0f.png)

**Desktop:**
 - OS: macOS Mojave 10.14
 - Browser: Chrome 75.0.3770.142

**Additional context**
- WordPress 5.2.2

**Comment by narthur** [comment]
I looked up [the Icon component source file](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/icon/index.js) and the [SVG primitive source file](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/primitives/svg/index.js). However it wasn't immediately apparent to me how to go about fixing the issue.

**Comment by narthur** [comment]
I switched away from using the Icon component, and found that I was still receiving the error. This time it looks like `el('a' ... )` is at fault, as extra parameters being injected seem to be causing the validation to fail:

![Screen Shot 2019-08-01 at 9 34 23 AM](https://user-images.githubusercontent.com/4655422/62297639-99ee9580-b43f-11e9-81cd-7a515bd53a60.png)

**Comment by jordesign** [comment]
Hi @narthur - just checking in to see if you still find this issue in place?

**Comment by Mamaduka** [comment]
I'll close this issue. No update has been provided in more than a year. The comments remain open, and any additional details can still be shared here.
