### ISSUE TITLE
Using hooks in a functional component which is inside the block's save function throws a React error.

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#16843]
**Describe the bug**
Using hooks in a component which is inside the block's save function triggers a "Violation: Hooks can only be called inside the body of a function component." error. I noticed this only happens when hooks are inside **save** but not if they are inside **edit**.

**To reproduce**
Register the following block type. Add it to a post, update the post, reload the page.

	const { useEffect } = wp.element;

	const Qqq = props => {
		useEffect(() => {
			console.log(123);
		}, []);

		return <div>qqq</div>;
	};

	wp.blocks.registerBlockType("qqq/qqq", {
		title: "qqq",
		icon: "carrot",
		category: "common",
		edit: props => <Qqq {...props} />,
		save: props => <Qqq {...props} />,
		attributes: {}
	});

**Version:**
 - WordPress 5.2.2
 - Gutenberg 6.2.0

**Comment by swissspidy** [comment]
The `save` function should be a pure function that depends only on the attributes used to invoke it.

It can not have any side effect or retrieve information from another source, e.g. it is not possible to use the data module inside it or hooks.

Check out https://developer.wordpress.org/block-editor/developers/block-api/block-edit-save/#save to see the reasons why.

**Comment by alvaro0555** [comment]
I see, it would be nice to have this kind of explanation before/instead of the React error; just a suggestion. Thanks @swissspidy

**Comment by YaronMiro** [comment]
@garciaalvaro 
Maybe this is to late, But for your purpose you need to use a dynamic block and then you can have a dynamic output for the block render on the front end.
see the official [guide](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/)
