### ISSUE TITLE
Consider Adding border-color to block styles classes

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#16848]
**Is your feature request related to a problem? Please describe.**
consider adding border-color as a native color class like `has-background` `has-very-light-gray-color` and so on to the `getColorClassName`

**Describe the solution you'd like**
add border-color classes so they can be inserted from the editor color panel for supporting Blocks so we will have classes like `has-border-color` & `has-very-light-gray-border-color`

**Comment by paaljoachim** [comment]
@nosolosw @ItsJonQ @jasmussen  is still issue still relevant?

**Comment by mtias** [comment]
We now have support for border color.
