### ISSUE TITLE
Toolbar is in two rows in the lists blocks.

### ISSUE THREAD

**Issue by josephahaden** [WordPress/gutenberg#16847]
The toolbar associated with bulleted and numbered lists is showing in two rows instead of one.

1. Go to the editor
2. Create a new list block by any method
3. Click inside an item to make the toolbar appear

<img width="690" alt="Screen Shot 2019-07-31 at 4 19 52 PM" src="https://user-images.githubusercontent.com/1886921/62254925-eb4f4400-b3af-11e9-82b0-95234a0c42e4.png">

 - OS: macOS Mojave v 10.14.5
 - Browser: Chrome v 75.0.3770.142

**Comment by roykho** [comment]
I just tested this in the latest master (6.8.0) and I am not seeing this issue.

![](https://cld.wthms.co/zMYYGg+)

**Comment by mapk** [comment]
I did not see the issue either. Closing for now.
