### ISSUE TITLE
Cover: Nested blocks set to full width are left-aligned

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#16851]
https://github.com/WordPress/gutenberg/pull/16751 removed the inner blocks restriction from the cover block, so we can insert any block there now.

While testing this feature, I noted that any nested block set to full width looks left-aligned in the editor:

**Image**
<img width="1019" alt="Screen Shot 2019-08-01 at 10 52 50" src="https://user-images.githubusercontent.com/1233880/62259795-957baa00-b44a-11e9-9cb9-d1113a2cbba9.png">

**Columns**
<img width="1006" alt="Screen Shot 2019-08-01 at 10 54 34" src="https://user-images.githubusercontent.com/1233880/62259864-c6f47580-b44a-11e9-920a-5a3b77fc42be.png">

**Video**
<img width="1003" alt="Screen Shot 2019-08-01 at 10 56 36" src="https://user-images.githubusercontent.com/1233880/62259934-0f139800-b44b-11e9-81e1-a4fe1e1fa6b2.png">

However, in the published view they look center-aligned:

**Image**
This actually looks right-aligned, but I'm assuming this is caused by the image size,
<img width="756" alt="Screen Shot 2019-08-01 at 10 57 18" src="https://user-images.githubusercontent.com/1233880/62259972-42eebd80-b44b-11e9-9269-ed7f3fac05f1.png">

**Columns**
<img width="742" alt="Screen Shot 2019-08-01 at 11 00 06" src="https://user-images.githubusercontent.com/1233880/62260102-c8726d80-b44b-11e9-9625-b4ae169c7e4e.png">

**Video**
<img width="736" alt="Screen Shot 2019-08-01 at 11 00 55" src="https://user-images.githubusercontent.com/1233880/62260108-cf997b80-b44b-11e9-8130-86cecc8ce035.png">

I was expecting these blocks to take the full width of the cover block.

Not sure if this a theme issue though (I checked this on the Twenty Nineteen theme).

**Comment by paaljoachim** [comment]
Hey @mmtr Miguel

A lot of improvements have happened with the Cover block since you made this issue.
I checked a few of the above such as image and columns.

I will go ahead and close this issue. If I am mistaken then please reopen.
