### ISSUE TITLE
Media & Text block: media dimensions

### ISSUE THREAD

**Issue by mobby2561** [WordPress/gutenberg#16853]
It's nice to have the option to resize the image in this block, BUT you can't do it pixel perfect for more of these blocks in a row.

Please make visible the width right on the change (Microsoft Excel has it nicely done - when you change the dimension of the row/column you see it instantly).

It would be also great to have some kind of input field settings to set the dimension right ahead instead of driving mouse like a crazy.

**Comment by senadir** [comment]
@mobby2561 can you provide more information or an example of the behavior you're describing?  a quick gif will do

**Comment by mobby2561** [comment]
My problem is slightly similar to this PR https://github.com/WordPress/gutenberg/pull/14483
But I'd rather see the px/% image resolution.
For example when you are editing an image in the media gallery
![Screen Recording 2019-08-09](https://user-images.githubusercontent.com/17024123/62768841-0d278580-ba98-11e9-9131-e0f40ae0b79b.gif)

**Comment by draganescu** [comment]
I suspect #14483 handles this better as if offers both inputs for exact sizes and some standard sizes which themes can implement.
