### ISSUE TITLE
Improve the Experience of Pure Text Editing (markdown, for example)

### ISSUE THREAD

**Issue by Ramlinbird** [WordPress/gutenberg#16855]
I just update my wordpress to 5.2.2, and found the editor has changed to gutenberg, a totally new editor which is very different with the classical one.
I want to share my using experience, and post some suggestion about enhancing the functionality of pure text editing.

### About the gutenberg
1. Very powerful, so many block to choose, and the design is beautiful.
2. Powerful is double-edged sword, the editor now looks more complicated than before.
For many blogger, we just want to post some text and photos, having no much time to manage multiple blocks in one page.
As for me, the markdown is enough at most time, but the markdown is not supported well as before in the new editor. Follow are some of my experience and suggestions.

### About the markdown
1. I use jetpack and open its markdown mode. But the **classical block** will change the markdown text (though it looks fine while publish or previewed), this makes maintenance more difficult.
2. While using **jetpack's markdown block** instead, all things seems good except latex preview in editor (I had reported this to jetpack). My question is, maybe gutenberg can work with jetpack group to make the markdown editor more natively and friendly to users?

Thanks a lot. And hope that gutenberg can provide bloggers a simpler and efficient way to write.

**Comment by phpbits** [comment]
@Ramlinbird You can try my EditorsKit plugin which is available for free on .org repository : https://wordpress.org/plugins/block-options/ . I've previously added live markdown typing but it only supports bold, italic and strikethrough as of the moment. You can check the preview here : https://twitter.com/phpbits/status/1135895882216329216 

I hope this helps. Thanks!
