### ISSUE TITLE
Block Collection instead of category

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16866]
So far we have allowed people to register a new category with an icon and it's been used by many block libraries or collections to register all the blocks in a single category.

This is not the most optimal for users because blocks that really belong in core categories are placed instead in plugin specific ones. However, it's also useful to see all the blocks coming from a single source. Several libraries have requested we allow more than one category for a block, but I think that is a sub-par solution and has the potential of making categories useless.

So I'd like to propose an addition to the block API which would be the notion of a _collection_. The way it'd work would be something like the following:

```js
registerBlockCollection( namespace, title, icon = {} );
```

* `namespace` would be matched against a block prefix and included automatically in a registered collection.
* a block can then register itself in the most appropriate functional category.
* if a collection is not registered nothing happens.

Thoughts?

**Comment by shaunandrews** [comment]
Would we expose the collection anywhere in the UI? Like you said it could be helpful to see all blocks in a collection, but we’d need to offer someway to sort blocks by collection along with the current category listing.

**Comment by mtias** [comment]
By default, a registered collection would work as a block category does today.

**Comment by mapk** [comment]
Since this has essentially been merged with #17609, I'm closing this issue.
