### ISSUE TITLE
How to change Permalink?

### ISSUE THREAD

**Issue by Vishakha-Patel** [WordPress/gutenberg#1686]
Hi,

I tried adding a post and wanted to change the permalink but could not find an option to do so. It is helpful for bloggers like me to have the permalink editable and handy like above title or somewhere.

Thanks.

**Comment by westonruter** [comment]
Please see #1285.

**Comment by Swagatam1975** [comment]
The easiest way to edit permalink is to go to the "post draft" section, then press "quick edit" for the selected article, and change the slug by pasting the title of the post!!

Hope this helps!

**Comment by natoinet** [comment]
I find it incredibly impractical !

**Comment by KeithLang** [comment]
Looks like Gutenberg 5.3 removed the ability to edit URL permalinks. I can't edit an URL directly in the post anymore. I'm stuck with the "edit permalinks" option, which 99.99% of people will not need instant access to. How often do we Edit Permalink structures? Not well thought out.
Anyone know how to edit URLs now?

**Comment by Swagatam1975** [comment]
you can install the plugin: **Disable Gutenberg** by jeff star if you are not comfortable with it.

**Comment by ezvr** [comment]
@Swagatam1975 That is such a toxic and unproductive answer: "If YOu DOn'T LIke IT yoU CaN STOp uSINg It" 

why even reply?
