### ISSUE TITLE
Misplaced checkmarks in the options modal

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#16860]
I'm seeing some misplaced checkmarks in the Options modal. Tested using `master` in the latest versions of Safari, FF, and Chrome on MacOS: 

<img width="394" alt="Screen Shot 2019-08-01 at 10 01 31 AM" src="https://user-images.githubusercontent.com/1202812/62299851-bf7d9e00-b443-11e9-8fb3-dff9407b28fe.png">

Likely related to #16551.

cc @youknowriad + @jffng

**Comment by jffng** [comment]
Thanks @kjellr, I'm looking into this. Looks like it also affects the Block manager modal.
