### ISSUE TITLE
How do I put a label on a DateTime in the InspectorControls for a block?

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#16868]
Raising this here because it's quite in-depth Guntenberg stuff and I think I could turn into a proper issue.

I'm trying to build a fairly simple block where you have in the `InspectorControls` sidebar a start and end date/time selector, and the block shows some details of posts that were published between the two dates.

I'm totally stuck trying to label the `DateTime` components in the InspectorControls because:

* The `DateTime` component does accept a label parameter
* I tried wrapping the `DateTime` in a `BaseControl` component but I think the `BaseControl` wants an `id` and the `DateTime` doesn't have an `id`
* I tried inserting a `BaseControl.VisualLabel` too, but I couldn't get that to display.
* I could try creating an HTML `<label>` but I don't know what the `for` attribute should be because the `DateTime` generates multiple inputs.
* There are various ways of just adding text, but it always looks wrong. I want to insert a properly formatted `label` that looks like other form field labels do in this area

Can you please advise on the proper way to add a label to a `DateTime` component?

And should a `label` property be added to the `DateTime` component that gives an easy way to do this?

Thanks

**Comment by talldan** [comment]
@rosswintle

The way the `DateTimePicker` is implemented in Gutenberg is a bit different, as it's in a 'Dropdown':
<img width="331" alt="Screen Shot 2019-08-02 at 4 35 44 pm" src="https://user-images.githubusercontent.com/677833/62356481-c4297b80-b543-11e9-8c95-e20537112924.png">

That's all implemented in this `PostSchedule` component. You could do similar to this:
https://github.com/WordPress/gutenberg/blob/905ea9523add9a2519faca9843b1287a50e14837/packages/edit-post/src/components/sidebar/post-schedule/index.js#L8-L36

If you wanted the whole date picker in the sidebar, then a `label` isn't the right thing to use—as you mention the datepicker is already composed of several input elements so you can't label them all with a single label.

I think the right thing would be to use a `Panel` component around the date picker. The `Panel` has its own header that you can use and you can put more text in the explanatory text in the panel using a `p` element if needed. I think this is also a good approach as the DatePicker is significantly complicated/busy, and arranging it with other UI elements only makes it more complicated.

Alternatively, you could wrap it in a `fieldset` and use a `legend` as the title.
https://www.w3.org/WAI/tutorials/forms/grouping/

I'll close this issue as it's not related to core gutenberg development. Hope the answer was of help.
