### ISSUE TITLE
Text is not editable on right aligned image

### ISSUE THREAD

**Issue by Vishakha-Patel** [WordPress/gutenberg#1687]
Hello,

The editor is very nice and useful. 

I added an image on the left-hand side. After that, I added a text field on right side. But when I click on it to add text, it does not show me a cursor.

![gutenberg-1_left image](https://user-images.githubusercontent.com/29881234/27817028-a6436600-60ac-11e7-9fbe-3ccdca431d2c.png)

Furthermore, I posted a text paragraph. After that, I performed select all, delete and then tried typing but that did not work as well. 

Hope this helps to make the plugin better.

**Comment by karmatosed** [comment]
I am not getting this on the latest version, could you please test and if you still have this reopen.
