### ISSUE TITLE
Media Text and Cover placeholder content overrides post template innerblocks.

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#16881]
**Describe the bug**
On new posts Media & Text and Cover placeholder content overrides inner blocks defined for on post templates.

**To reproduce**
1. Add a post template which defines innerblocks for cover and media-text blocks.

    ```php
    function myplugin_register_template() {
      $post_type_object = get_post_type_object( 'post' );
      $post_type_object->template = array(
        array( 'core/media-text', array(), array(
          array( 'core/heading', array( 'placeholder' => 'Test' ) ),
        ) ),
      );
    }
    ```

2. Create a new post
3. Notice that the default _Content..._ placeholder definied by the media-text component is shown rather than the post template defined one.

**Expected behavior**

Templates defined on post types should override the placeholder content on media-text and cover blocks.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 76

**Additional context**
- Gutenberg v6.2.0

**Comment by youknowriad** [comment]
This is fixed by your PR yesterday right @jorgefilipecosta ?

**Comment by oxyc** [comment]
Yes and I confirmed it worked with his PR
