### ISSUE TITLE
Remove excerpt metabox at whole

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1689]
Now when you refurniture everything it is maybe right oportunity to think about ditching excerpt metabox and think in other directions. Trying to see it from very editor beginner perspective.

Some reasons for and against:
Against (excerpt metabox):

- It goes against human visual perception to have excerpt metabox after content area. Now is better in right sidebar, but still same feeling.
- Allways dilema if you would have visual editor in excerpts, for themes allowing HTML tags in excerpts.
- Textarea box is small and no way you can make it bigger this way.
- There have never been in WordPress right visual preview, bird eye, how excerpt and content work and look together.

If you ditch excerpt metabox at whole (maybe left something for backward compability) you get this:
For (Gutenberg block/element):

- You make excerpts as additional Gutenberg block/element.
- Beginners place excerpt after title, at the beginning.
- Excerpt block is designed and styled there is no way confuse it visualy with rest of content blocks.
- Beginners see excerpt and content as one compact unity. For the first time since WordPress exist. They see directly how they collaborate. 
- One additional gain with it is no duplicate content in database, as im many cases, when beginner paste/type same text in content and first part of it copy/paste in excerpt metabox.

Maybe some more, but dont remember now.

**Comment by swissspidy** [comment]
> You make excerpts as additional Gutenberg block/element.

See https://github.com/WordPress/gutenberg/issues/1288#issuecomment-310544967, #1684, #1465.

**Comment by StaggerLeee** [comment]
Nice. I like idea to have it in first position without moving options.

**Comment by MaxZiebell** [comment]
+1
