### ISSUE TITLE
editor-visual-editor__block

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1690]
Can you name classes for different blocks differently ?

Not everyone has time for lengthy Photoshop mockups. Sometimes one need only chrome inspector and change some things to be able to leave screenshots here.

Beside this different classes, a lot of them, would be needed in the future for plugins developers, and those who want to change something visually in editor.

- editor-visual-image-editor__block
- editor-visual-gallery-editor__block
- editor-visual-quote-editor__block
- editor-visual-embed-youtube-editor__block
- editor-visual-embed-vimeo-editor__block

etc.......

**Comment by youknowriad** [comment]
There are already different classes for the different blocks, the `editor-visual-editor__block` is for the wrapper which shouldn't be tweaked by themes/plugins.

**Comment by youknowriad** [comment]
Closing, feel free if the `wp-block-image`, `wp-block-quote`.... classes don't address your issues
