### ISSUE TITLE
Draggable component in README is not draggable

### ISSUE THREAD

**Issue by ryansborn** [WordPress/gutenberg#16916]
The [Usage](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/draggable#usage) section of the Draggable component README gives an example that is not in fact draggable. The problem appears to be that the draggable attribute is assigned to a Dashicon component, which is rendered as an SVG element. But assigning a draggable attribute to an SVG element doesn't result in the element having a draggable DOM property. The reason for this, I presume, is that SVG elements don't support HTML 5 Drag and Drop events. See discussion here: [https://github.com/facebook/react/issues/3192](https://github.com/facebook/react/issues/3192)

**Comment by talldan** [comment]
Fixed by #18158, and it looks like the example has been updated since then further.
