### ISSUE TITLE
Group block: Inner block toolbars are indented

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16917]
**Problem**
Some weird indentations have happened in relation to the Group block. As noted about the columns in this issue https://github.com/WordPress/gutenberg/issues/16321, I've also noticed that the inner block toolbars are indented on their blocks as well.

![toolbar-group-block](https://user-images.githubusercontent.com/617986/62502267-4794d800-b7a3-11e9-8dd4-2d098d11901b.gif)

**Expected behavior**
The inner block toolbars shouldn't be indented on the block.

![better](https://user-images.githubusercontent.com/617986/62502344-c38f2000-b7a3-11e9-8e8a-e401e0c31aab.gif)

**Comment by glendaviesnz** [comment]
This appears to be resolved on latest master.

![indent](https://user-images.githubusercontent.com/3629020/65654475-0fa46580-e06d-11e9-8bfa-52778c1c6242.gif)

**Comment by mapk** [comment]
Good call. Thanks!
