### ISSUE TITLE
Can't add text to columns

### ISSUE THREAD

**Issue by beautifullume** [WordPress/gutenberg#16914]
I cannot add any blocks or text within columns. It gets me to the point you see below, but as soon as I move my mouse, the block options disappear before I can click an option ...

<img width="389" alt="Column issue" src="https://user-images.githubusercontent.com/53798175/62498070-d5b49280-b792-11e9-8d99-5b8de83bc804.png">

Any suggestions?

I am using:
Wordpress 5.2.2
Gutenberg 6.2.0
This issue is happening in Both Firefox and Chrome

Thank you!

**Comment by beautifullume** [comment]
I cannot add any blocks or text within columns.  It gets me to the point you see below, but as soon as I move my mouse, the block options disappear ...

<img width="389" alt="Column issue" src="https://user-images.githubusercontent.com/53798175/62497886-2677bb80-b792-11e9-9419-add0d52b9b7b.png">

Any suggestions?

I am using:
Wordpress 5.2.2
Gutenberg 6.2.0
This issue is happening in Both Firefox and Chrome

Thank you!

**Comment by swissspidy** [comment]
Are you using any other plugins?

**Comment by beautifullume** [comment]
> Are you using any other plugins?
Yes, I have quite a few plugins.  But have not had issues with any other blocks - just columns...

**Comment by swissspidy** [comment]
That doesn‘t mean it can‘t be a plugin‘s issue. For example, we had a bug in the AMP plugin that caused issues with the column block. Are you using that per chance?

**Comment by beautifullume** [comment]
I deactivated AMP and that has fixed the problem.  Thank you for your help!

**Comment by swissspidy** [comment]
@beautifullume You might want to try the beta version of the next release of the AMP plugin, which includes a fix for this:

[amp.zip](https://github.com/WordPress/gutenberg/files/3485636/amp.zip)

Better than disabling :-)
