### ISSUE TITLE
Settings / Publish Button Size and Design

### ISSUE THREAD

**Issue by Titanas0** [WordPress/gutenberg#1692]
Hi,

I've been thinking about the Settings and Publish buttons size and looks. Even though the two buttons are very close to each other, they are visually separated and look very different and maybe confusing to some.

Publish. One of the most important, if not the most important, buttons in Gutenberg is smaller in size compared to Settings. Next to is sits Settings, which initially looks like a link with an icon but when clicked transforms to a button with a bigger size than Publish.

The mockup idea i'm proposing has **both** buttons look like like buttons with the **same** size and without the space separator in between.

The Settings buttons doesn't use the cog icon anymore. Instead there is a down arrow, very recognizable from mobile, to indicate the space and intent of the actions after clicking on Settings.

![gutenberg 2c](https://user-images.githubusercontent.com/4397364/27825112-d6108780-60ae-11e7-9aff-705a7be186f2.png)

**Comment by jwold** [comment]
I agree with the suggestions here. This UI change does a few things:

1. Establishes visual hierarchy for the buttons. I can tell which one is most important (publish) without having to read them.
2. Changing the cog to an arrow makes more sense and tells me that something is going to popup below that button. 

Great suggestion. +1 from me!

**Comment by mtias** [comment]
The equal sizing would stop working quickly with i18n.

**Comment by karmatosed** [comment]
Unfortunately, I don't agree this is a better change this time. I think we maybe can iterate this area, but the suggestions I do not think improve this or achieve what is being wanted.

Having a down arrow indicates more content would show, not that it shows/hides. Mobile or not it's a universal pattern. I would therefore not suggest we implement that change. It's not connected it does just pop and therefore it doesn't fit.

I also agree that different languages will change things. We should be aware of that and not design to prioritise one language format.

For now, I am closing this. But, I am open to iterations around this area that don't cause further confusion.
