### ISSUE TITLE
Refactor experiments settings e2e tests

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#16922]
**Is your feature request related to a problem? Please describe.**

Follow-up from #16626. 

**Describe the solution you'd like**

* ~~[Make sure each setting is disabled before enabling it](https://github.com/WordPress/gutenberg/pull/16626#discussion_r310914424)~~
* ~~In `packages/e2e-test-utils/src/enable-experimental-features.js`, move `submit` click outside the loop so it only gets clicked once.~~
* Should features be disabled again after tests have run?

UPDATE: Most of these issues were fixed in #16930 . Leaving this open just for disabling features after tests run.

**Comment by paaljoachim** [comment]
Hey Isabel. @tellthemachines 

I see an associated merged PR. Can this issue be closed?

**Comment by tellthemachines** [comment]
Yup, closing, thanks Paal!
