### ISSUE TITLE
Group Block: Allow Scheduling the Block

### ISSUE THREAD

**Issue by Aurorum** [WordPress/gutenberg#16933]
**Is your feature request related to a problem? Please describe.**
Since I've started blogging, I've always wanted to be able to schedule content to be released _after_ my post is published. The Group Block seems to be the perfect way of making that possible. Its uses could be unlimited; they extend from businesses display notices about sales after some time has passed, to allowing bloggers to schedule images or videos.

**Describe the solution you'd like**

I'd like for it to be possible to schedule a Group Block to be displayed after a certain time has passed. That could look something like this:

![group block concept](https://user-images.githubusercontent.com/43215253/62578256-92dce280-b898-11e9-80bc-29f1bfde202b.png)

Or perhaps something like this:

<img width="770" alt="Screenshot 2019-08-06 at 22 09 45" src="https://user-images.githubusercontent.com/43215253/62578266-9a9c8700-b898-11e9-99b7-312a24e26c93.png">

Here's I imagine it would work:

1. Write a post
2. Schedule my Group block for 12th August (for example)
3. Publish post or schedule it for 8th August (for example)
4. The post is released, but the blocks inside the Group Block are _not_ present
5. On 12th August, the blocks inside the Group Block are now present

**Describe alternatives you've considered**

This could be a separate **Scheduler** block but I think it makes sense to fit this into the Group Block. I think that the wide variety of use cases justifies adding this to the Group Block instead of relying on external plugins.

**Comment by karmatosed** [comment]
Interesting suggestion @Aurorum and I can totally see how useful to some. I do think this would go beyond just one block though and for me is something a plugin could do over being in core itself. In saying that I am not dismissing how useful it would be to some but I don't feel it would be something everyone would want. It could also be good to explore in plugin to consider.

I am going to flag this to get other inputs as the above is just my own thoughts.

**Comment by Aurorum** [comment]
(I could be being biased because I'm a WP.com site owner here without access to custom plugins!) 

I do agree that not _everyone_ will use it as the Group Block has other use cases as well, so an option in the sidebar to schedule it seems harmless, but I also think that enough people could benefit from the _huge_ variety of use cases that it does justify being implemented to core. This does go beyond one block, but as users can place any block inside the Group Block, it does make sense, if it was to be implemented, to be added to the Group Block. That way, people could schedule large chunks of content instead of having to schedule individual paragraph blocks, for example. :)

**Comment by swissspidy** [comment]
I don't see why this should be specific to the group block. For example, when I have a signup form that should be open until XYZ, I don't want to put it into a group block just to make it work.

FWIW, there are already plugins that solve this, e.g. https://wordpress.org/plugins/schedule-content-block/

**Comment by karmatosed** [comment]
As there is a plugin and this would apply for all blocks, for now, I am closing this out. It absolutely can be revisited but it doesn't feel specific to one block or something to add to core right now.

**Comment by hamedJenabi** [comment]
I wish this dream was true!
