### ISSUE TITLE
WP Components: Docs: Idea for Grouping/Categorization

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#16946]
Hi there 👋 ,

I've been having chats with @griffbrad and @mtias regarding WP Component docs. One thing that came up was navigation and grouping.

At the moment, there isn't a way to do this in the component `README.md` files.

I have a suggestion! Would do you folks think about leveraging [front-matter](https://jekyllrb.com/docs/front-matter/) to do this?

For example, with `@wordpress/components/src/button/README.md`, the front-matter can start with:

```
---
title: Button
category: Actions
---
```

In addition to grouping or categories, we can add other info like a title, description, etc... that can help with doc generation.

I feel like this is a pretty universal (and simple) way to get something started with little overhead. I've done this in the past, and it's worked out very nicely. Not just for devs, but for all folks reading or contributing to the docs.

For inspiration, [Shopify's Polaris](https://github.com/Shopify/polaris-react/blob/master/src/components/ActionList/README.md) does this with their docs :)

Would love to hear what folks think!

Thanks!! 🙏

**Comment by griffbrad** [comment]
Seems reasonable to me.  The Gutenberg Handbook uses this JSON manifest file to represent this kind of information during the import into WordPress:

https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json

Front-matter in Markdown files seems like a close enough analog to that per-page key-value block in the manifest that we could always convert to one or the other, if needed.  I'd say let's try it out.
