### ISSUE TITLE
Facebook block: "Resize for smaller devices" not working

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#16948]
**Describe the bug**
The "Resize for smaller devices" option doesn't help resize the embed on mobile screens.

**To reproduce**
1. Create a new post.
2. Add a new Facebook block and insert your URL embed
3. Make sure the option "Resize for smaller devices" is turned on
4. Check the front end.

On my end regardless of the theme, browser or environment, the option didn't resize the Facebook embeds.

**Desktop:**
 - OS: macOS
 - Browser Chrome
 - Version 76

I managed to replicate this on a WordPress.com and self-hosted WordPress site.

**Comment by tbradsha** [comment]
Replicated on WordPress.com using Chrome 77 on macOS 10.14.6.

**Comment by tedw** [comment]
I appears `data-width="500"` is always added to the `<div class="fb-post">` wrapper, which disabled the default responsive behavior (see https://developers.facebook.com/docs/plugins/embedded-posts/#settings).

Example output with JS disabled:
```html
<figure class="wp-block-embed-facebook wp-block-embed is-type-rich is-provider-facebook">
  <div class="wp-block-embed__wrapper">
    <div class="entry-content-asset">
      <div id="fb-root"></div>
      <script async="1" defer="1" crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v5.0"></script>
      <div class="fb-post" data-href="https://www.facebook.com/threespot/photos/a.10150163047463613/10156285252298613/?type=3" data-width="500">
        <blockquote cite="https://www.facebook.com/threespot/photos/a.10150163047463613/10156285252298613/?type=3" class="fb-xfbml-parse-ignore">
          <p>On International Women's Day, we celebrate women everywhere who are breaking barriers and pushing equality forward.</p>
          Posted by <a href="https://www.facebook.com/threespot/">Threespot</a> on&nbsp;<a href="https://www.facebook.com/threespot/photos/a.10150163047463613/10156285252298613/?type=3">Friday, March 8, 2019</a>
        </blockquote>
      </div>
    </div>
  </div>
</figure>
```

Really surprised this hasn’t come up before. I tried to find where this code exists to submit a PR but am not very familiar with the WP and Gutenberg codebases. A quick GitHub search didn’t turn anything up. Hope someone can else fix this soon!

**Comment by tedw** [comment]
Was able to hack something together to fix this for the time being:

```php
/**
 * Remove “data-width” attribute on Facebook embeds
 */
add_filter('the_content', function($content) {
  global $post;
  $pattern = '/<div class=\"fb-post\" (.*) data-width=\"500\">/i';
  $replacement = '<div class="fb-post" ${1} data-width="auto">';
  $content = preg_replace($pattern, $replacement, $content);
  return $content;
});
```

Obviously, this is not a great long-term solution.

**Comment by talldan** [comment]
This ticket was mentioned during the core-editor triage today (link requires a slack account - https://wordpress.slack.com/archives/C02QB2JS7/p1588225441100800).

We could reproduce the behavior described in the issue, so I'm removing the `Needs Testing` label.

One thing observed is that the embed does resize appropriately on a page reload, that might either be how it was originally designed or indicative of a bug.

The embed would ideally resize on the fly to sufficiently cover use-cases like mobile users rotating their screen.

**Comment by talldan** [comment]
The facebook embed is no longer supported so closing.
