### ISSUE TITLE
Classic Text block still has "Freeform" tag name

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1695]
When you add a Classic Text block (the name of which we settled on in #1326), the code version still looks like

```
<!-- wp:core/freeform -->
<p class="wp-block-freeform"></p>
<!-- /wp:core/freeform -->
```

If we're gonna commit to the name we should also change the tag.

Version 0.3.0

**Comment by youknowriad** [comment]
This won't harm backwards compatibility since it's the default block used if no matching block is found.

**Comment by mtias** [comment]
The plan is to not show comment/name for this block.
