### ISSUE TITLE
Inconsistency in where Inserter adds a block

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1696]
I noticed that if you pick one of the shortcuts that appear when you hover over the inserter, those blocks get added below the existing content.

![screen_shot_2017-07-04_at_13_08_08](https://user-images.githubusercontent.com/6073772/27828008-45c69c94-60ba-11e7-9176-cb7c2c3908d3.png)

But if you pick one from the actual inserter menu, it appears below the block you have selected.

![screen_shot_2017-07-04_at_13_08_15](https://user-images.githubusercontent.com/6073772/27828010-46866fba-60ba-11e7-8622-0c58523a57f0.png)

The first method is the most intuitive, but in lieu of an inserter appearing between blocks I prefer the second method. What should we do about this?

Version 0.3.0

**Comment by mtias** [comment]
Going to close as we do have an inserter showing in-between blocks now.
