### ISSUE TITLE
Unable to type certain characters 

### ISSUE THREAD

**Issue by Leon-APMMA** [WordPress/gutenberg#16965]
I have had a very unusual issue while trying to post on WordPress/Gutenberg the last couple of weeks. The issue only occurs after I have added the featured photo to the post. Up until that point, there are no issues. Once I have added the photo, I can no longer type the following four characters anywhere in the post:

‘
%
&
( 

This issue happens on both Chrome and Safari. The issue started after I updated to the latest version of WordPress and installed updates to the theme and twelve of my plugins.

Anyone else having the same issue?

**Comment by riccardomel** [comment]
Same here, when i left the article opened for a while i can't add any of the char listed 
 ‘
%
&
(

Any advice?

**Comment by brezocordero** [comment]
I was not able to reproduce it. 
Gutenberg 6.8.0
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

I added a paragraph, added special chars :
‘
%
&
(

I added a featured image. I was able to type the characters again.

I waited some time with the post opened, could type the chars again. 

@Leon-APMMA is this still happening on your end?

**Comment by Leon-APMMA** [comment]
Hi,

No, the issue resolved itself a couple of weeks ago, after persisting for a couple of months. It was a strange little issue but I'm glad it's all sorted now.

Thanks
