### ISSUE TITLE
register_rest_field's get callback happens after fetch, not before

### ISSUE THREAD

**Issue by panfanky** [WordPress/gutenberg#16970]
**Describe the bug**
Custom meta for custom post registered with register_rest_field updates the JSON, but too late - after it's already been fetched by the editor.

My code:
```
function get_post_meta_for_api( $object, $attr ) {
 //get the id of the post object array
 $post_id = $object['id'];
 //return the post meta
 return get_post_meta( $post_id, $attr )[0];
}
function create_api_posts_meta_field() {
 register_rest_field( 'tha_events', 'thasubtitle', array('get_callback' => 'get_post_meta_for_api','schema' => null));
}

add_action( 'rest_api_init', 'create_api_posts_meta_field' );
```

**To reproduce**
1. In a custom post type, edit the title and also edit custom meta field
2. Click on 'publish'
3. Open console and see XHR request to wp-json/...
4. See: the title comes back updated, but the custom meta's got the old value.
5. Go to api url
6. See: both are updated now

**Expected behavior**
I wanted to use [apiFetch middleware](https://developer.wordpress.org/block-editor/packages/packages-api-fetch/#middlewares), so I could work with the data with js when the post was updated. So I expected to get the updated data, not old. When I console.log the result in apiFetch.use, again:the title comes back updated, but the custom meta's got the old value.

Note: I also tried register_meta, but no meta array appeared in the Custom post type's JSON. That one only worked with classic posts.

**Comment by youknowriad** [comment]
Hi There! I'm not sure I can help here but do you have the "custom-fields" enabled on your CPT? 

Note that this tracker is not used for help requests.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
