### ISSUE TITLE
Cannot Embed Content when using oembed_fetch_url filter

### ISSUE THREAD

**Issue by bradmsmith** [WordPress/gutenberg#16976]
**Describe the bug**
Pasting a URL into a post returns Sorry, this content cannot be embedded when a filter is set on oembed_fetch_url

**To reproduce**
1. Add the following code to functions.php then try to embed a Vimeo URL

```php
// https://wordpress.org/support/topic/disabling-do-not-track-for-oembeds/

function dl_oembed ( $provider, $url, $args ) {
  if ( strpos( $provider, 'vimeo.com' ) !== false) {
     $provider = remove_query_arg( 'dnt', $provider );

  }

  return $provider;
}
add_filter( 'oembed_fetch_url', 'dl_oembed' );
```

**Expected behavior**
The block should embed the video without the DNT parameter

My guess is the issue is with switchedURL parameter in gutenberg/packages/block-library/src/embed/edit.js since the filter will change the URL by removing parameters

**Comment by noisysocks** [comment]
I wasn't able to reliably reproduce this. When I follow the steps the embed works but I do not get the expected behaviour which is that the DNT parameter is removed.

@bradmsmith: Are you still seeing this issue?
