### ISSUE TITLE
Copy one or multiple blocks from one page to another 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#16983]
I needed to copy parts of a page to another page. I tried to select a block and press ctrl+c to copy it and then in another page press ctrl+v, but that did not work.

**Describe the solution you'd like**
I would like to be able to copy various blocks from one page to another.

**Describe alternatives you've considered**
The option is to use the contextual (I think the 3 dot menu is called) and select copy all the contents. It is awesome that one can easily copy the full contents of the page to another page, but just copying parts of it I did not get to work.

So I thought I might as well create an issue for it to bring it out there...and mention it.

**Comment by phpbits** [comment]
@paaljoachim I had the same experience/problem but if you are looking for alternative now, you can use [EditorsKit](https://editorskit.com/) then select the blocks. Click the Block Settings(3 dots) then export. Lastly, drag and drop the exported file to the page to paste. Not as good as copy+paste but it's an alternative that's available right now :) Thanks!

**Comment by paaljoachim** [comment]
Hey Jeffrey. @phpbits 
Thanks for the headsup regarding an alternative way to copy and paste block!

Btw
Here is a suggestion for Core. At the bottom I added the option to "Copy Selected Blocks."
![Block-Settings-drop-down](https://user-images.githubusercontent.com/5323259/62818811-36561d80-bb4d-11e9-8148-80fcb32f5ee6.jpg)

**Comment by phpbits** [comment]
@paaljoachim Just added this to EditorsKit plugin as well : https://wordpress.org/plugins/block-options/

Here's the preview on how it works :


![ezgif com-optimize (3)](https://user-images.githubusercontent.com/3365507/65701595-29b56680-e0b4-11e9-95a2-df7c0dd67136.gif)

**Comment by StaggerLeee** [comment]
This option is really needed.

**Comment by paaljoachim** [comment]
Copy Block was added
https://github.com/WordPress/gutenberg/pull/22186

https://make.wordpress.org/core/2020/05/27/whats-new-in-gutenberg-27-may/
