### ISSUE TITLE
Copy/paste from Word to some core blocks displays Word HTML

### ISSUE THREAD

**Issue by thorandre** [WordPress/gutenberg#16986]
**Description**
When pasting from Word on some Gutenberg Cloud components the Word's HTML is pasted.

It happens on: Quote, Verse, Content in Columns, Table and PullQuote

**To reproduce**
1. https://testgutenberg.com (or some Gutenberg editor)
2. Add a "Quote" block from Gutenberg core
3. Go to Word and copy some text
4. Paste the text inside the Quote block

**Expected behavior**
The content pasted nicely without styling or visual HTML from Word.

**Screenshot**
![Screenshot from Gutenberg editor after paste from Word](https://www.drupal.org/files/issues/2019-07-17/paste_from_word.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 75
 - MS Word Version 1907 (Build 11901.20176)

**Additional context**
- First reported for Drupal Gutenberg here: https://www.drupal.org/project/gutenberg/issues/3068356

**Comment by ellatrix** [comment]
Hi @thorandre ! Thanks for the report.

Could you share what the console is logging for you when you paste?

I'm looking for this:

<img width="657" alt="Screenshot 2019-08-07 at 10 53 18" src="https://user-images.githubusercontent.com/4710635/62609234-ac664480-b901-11e9-972a-7383ec88b930.png">

Please copy the text and paste it in between backticks:
````
```
content
```
````

Thank you!

**Comment by maggie-drupal** [comment]
Hi @ellatrix ,
here is what the console is logging:
```
Received HTML:

 <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/syntila/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/syntila/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/syntila/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Normal</w:View>
  <w:Zoom>0</w:Zoom>
  <w:TrackMoves/>
  <w:TrackFormatting/>
  <w:PunctuationKerning/>
  <w:ValidateAgainstSchemas/>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:DoNotPromoteQF/>
  <w:LidThemeOther>EN-GB</w:LidThemeOther>
  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>
  <w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>
  <w:Compatibility>
   <w:BreakWrappedTables/>
   <w:SnapToGridInCell/>
   <w:WrapTextWithPunct/>
   <w:UseAsianBreakRules/>
   <w:DontGrowAutofit/>
   <w:SplitPgBreakAndParaMark/>
   <w:EnableOpenTypeKerning/>
   <w:DontFlipMirrorIndents/>
   <w:OverrideTableStyleHps/>
  </w:Compatibility>
  <w:DoNotOptimizeForBrowser/>
  <m:mathPr>
   <m:mathFont m:val="Cambria Math"/>
   <m:brkBin m:val="before"/>
   <m:brkBinSub m:val="&#45;-"/>
   <m:smallFrac m:val="off"/>
   <m:dispDef/>
   <m:lMargin m:val="0"/>
   <m:rMargin m:val="0"/>
   <m:defJc m:val="centerGroup"/>
   <m:wrapIndent m:val="1440"/>
   <m:intLim m:val="subSup"/>
   <m:naryLim m:val="undOvr"/>
  </m:mathPr></w:WordDocument>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="false"
  DefSemiHidden="false" DefQFormat="false" DefPriority="99"
  LatentStyleCount="375">
  <w:LsdException Locked="false" Priority="0" QFormat="true" Name="Normal"/>
  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 1"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 2"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 3"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 4"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 5"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 6"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 7"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 8"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 9"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 1"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 2"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 3"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 4"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 5"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 6"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 7"/>
  <w:
??-eJyVz8EKwjAQBNAfsi6h1pv4LTa7lI3pbkg2pv69FaRncxyYBzPQ0sDiY0UqEAoYy3v1BCnWhaVA5GLll86hnGDvexUjsaOz1D3OlBeYK0cEpJTJP4wQWJC2f52osd9n9KG69QHTJ8nw/dXnXkwtae5UTTN6rdLJCNk0H+a+3tx0dW6cRncJH0YppOo=:2216 Received plain text:

 This section shall include a message from the chair
index.js?ver=1555337988:2 Processed inline HTML:

 



<br>
<br>
<br>
<br>
<br>
<br>
<br><br>

&lt;!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:3 0 0 0 1 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-536859905 -1073732485 9 0 511 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:0in;
	text-align:justify;
	line-height:115%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-font-family:Calibri;
	mso-ansi-language:EN-GB;
	mso-fareast-language:EN-GB;}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-fareast-font-family:Calibri;
	mso-hansi-font-family:Calibri;
	mso-bidi-font-family:Calibri;
	mso-ansi-language:EN-GB;
	mso-fareast-language:EN-GB;}
.MsoPapDefault
	{mso-style-type:export-only;
	margin-bottom:10.0pt;
	text-align:justify;
	line-height:115%;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-paper-source:0;}
div.WordSection1
	{page:WordSection1;}
--&gt;
<br>
<br>



<br><em>This section shall include a message from the
chair</em>
```

**Comment by ellatrix** [comment]
It looks like some of the HTML comments in the source are escaped. I see `&lt;!--`. This means that it will just be processed as text. Unfortunately, I don't think there's much we can do.

What happens when you paste this in other text editors, like Google Docs or [TinyMCE](https://www.tiny.cloud)? Do you see similar output?

**Comment by paaljoachim** [comment]
I happen to notice when pasting quote author from word into quote author in the quote block...

Before:
<img width="842" alt="Screen Shot 2020-02-12 at 22 17 23" src="https://user-images.githubusercontent.com/5323259/74378055-82786800-4de5-11ea-857d-d7c64043c763.png">

After having pasted in a new quote author. (copy ctrl+C and Paste ctrl+V)
<img width="859" alt="Screen Shot 2020-02-12 at 22 18 32" src="https://user-images.githubusercontent.com/5323259/74378117-a20f9080-4de5-11ea-9ef3-17aafaa60bb9.png">


To get the correct text I did a copy and paste match formatting into the Gutenberg quote author area. By holding down ctrl+alt+shift+V.

**Comment by chaion07** [comment]
Upon testing I noticed no issues with paragraph block in latest version of WP
![image (1)](https://user-images.githubusercontent.com/64467850/88016249-d5004200-cb44-11ea-84b3-6e7eceebf4e5.png)
the following:

**Comment by chaion07** [comment]
But there were issues with pullquote
![image (2)](https://user-images.githubusercontent.com/64467850/88016301-f2cda700-cb44-11ea-8355-2ce62c28fce1.png)

**Comment by chaion07** [comment]
Also the table block
![image (3)](https://user-images.githubusercontent.com/64467850/88016371-0ed14880-cb45-11ea-8761-b4a0d2611493.png)

**Comment by talldan** [comment]
This was tested in a triage session on slack (conversation here: https://wordpress.slack.com/archives/C02QB2JS7/p1595308016215200).

As mentioned above a few observed that the issue doesn't seem to happen any more in the Quote block, but does in other blocks (Table, Pull Quote).

Copy pasting from the Pages app in Mac Os to the quote block also seemed to produce the same issue.

**Comment by annezazu** [comment]
Tested this today in another triage session using Gutenberg 10.3.2 and WordPress 5.7 with the Twenty Twenty-One theme:
- Table: can replicate ✅ 
- Pull Quote: can replicate ✅ 
- Quote: can't replicate ❌ 
- Code: can't replicate ❌ 
- Verse: can't replicate ❌

**Comment by pupunzi** [comment]
We have the same problem using the wp.blockEditor.RichText.

**Comment by jozs3f** [comment]
Any updates on this ? we are having issues with <RichText> as well. On the paragraph block i get the following consoles and it works fine
![paragraph-block](https://user-images.githubusercontent.com/54510424/131682471-bf6c2c84-bcb5-4589-88e2-b858bf68b631.png)

However in a custom block where we have a RichText we get the following:

>  <RichText
          tagName="p"
          placeholder={ __( 'Text' ) }
          value={ text }
          className="text"
          keepPlaceholderOnFocus
          preserveWhiteSpace
          onChange={ ( value ) => {
            setAttributes( { text: value } )
          }}
        />

![custom-block-richtext](https://user-images.githubusercontent.com/54510424/131682738-2e9e4149-b500-4fcb-bec0-de922ccfacdc.png)

In the onChange we don't have access to the plainText either that would be cool as well but not sure how to get the html without the @page ..... text .
If i saw it correctly the **import { _pasteHandler_ } from '@wordpress/blocks';** pastehandler is used to work some magic in core/paragraph but i didn't managed to reproduce that in a custom block.

**Comment by maplerock** [comment]
This is also an issue when copying into the page title.

<img width="1075" alt="Screenshot 2022-08-17 at 12 56 42" src="https://user-images.githubusercontent.com/8367270/185112628-73a55519-1614-4a98-9d49-ff620831938e.png">
.

**Comment by annezazu** [comment]
@maplerock does this happen with Gutenberg 13.8.2?

**Comment by ellatrix** [comment]
#46402 fixes this.
