### ISSUE TITLE
publishing failed & update failed as soon as an external link is included

### ISSUE THREAD

**Issue by Kevin7911** [WordPress/gutenberg#16980]
Hello all,

I have an issue with updating & publishing Gutenberg posts. Classic did work for this issue, but that is not the solution for me.

This morning I was able to insert an external link and update no problem. Then I installed the MonsterInsights plugin for Google Analytics and connected it with Analytics. Afterward anytime I tried updating, publishing or saving any post that included an external link was leading to an error. Deleting the plugin did not resolve the problem. 

How can this be restored to normal?

WP version: latest
Browser: Chrome

**Comment by senadir** [comment]
can you test with the latest Gutenberg version? you can find it at the plugin directory when you search for Gutenberg, if the problem still persist can you include a way for us to reproduce the problem, copy & paste the content you used by accessing the code editor on the top right in Gutenberg

**Comment by Kevin7911** [comment]
Hi guys, I had my troubles for some time but without any indication, it just started working again.
Sometimes the machine seems to have a heart after all :)
Thank you for your help anyway!
