### ISSUE TITLE
Pasting unformatted text removes formatting and converts heading to paragraph

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#16990]
**Describe the bug**

If I paste an unformatted word (eg. copied from the URL bar) into an empty heading block or a paragraph with styling applied, all styling is reset and the block is converted to a paragraph.

**To reproduce**

1. Create a _Heading_ block
2. Copy an unformatted word, eg a word from the URL bar of the browser
3. Paste it into the block
4. Notice that the block is now a paragraph.

Same happens if you paste it into the styled placeholder paragraph block in _Media & Text_.

**Expected behavior**

If I paste an unformatted word I would expect it to keep the previous styling and block type rather than resetting everything to an unformatted paragraph.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 76

**Additional context**

This works as expected with [v4.7.1](https://testgutenberg.com/) and v5.5.0. It does not work in v5.9.1, v6.2.0 and master branch.

**Comment by nerrad** [comment]
I'm able to reproduce in the editor included with WordPress 5.2.2 but not with Gutenberg active from the latest master branch.

**Comment by oxyc** [comment]
Still happening with the playground on master branch for me. I can confirm it with the plugin tomorrow.

![demo](https://user-images.githubusercontent.com/302736/62839644-c20d9e00-bc62-11e9-9f28-e4d870ecf7ae.gif)

**Comment by nerrad** [comment]
To clarify, I'm not testing using the playground against Master but am using the build tested in a WordPress install.  There may be a variation between GB in playground and in a WP environment that may be contributing to this then.

**Comment by oxyc** [comment]
This also happens with the plugin for me. Tested in Safari, Chrome and Firefox, all of them behave the same.

I ran these steps to build the plugin:

```
git pull origin master
npm run package-plugin
mv gutenberg.zip ~/......
```

**Comment by oxyc** [comment]
Just saw there's apparently https://wordpress.github.io/gutenberg/ which is built on master according to https://github.com/WordPress/gutenberg/issues/16967#issuecomment-519844757.

It's reproducible there too.

**Comment by peterwilsoncc** [comment]
I've tested this locally and am having a similar problem, please find a screencast attached.

Testing environment
- WordPress 5.2.2
- Gutenberg master@0b4d9c8
- Chrome 76.0/macOS 10.13.6

Build environment
- node 10.16.0
- npm 6.9.0
- built with `npm run build`, ie not running in dev mode

Console output
```
Received HTML:

 
index.js?ver=1566448714:12 Received plain text:

 Pens and pencils
index.js?ver=1566448714:2 Processed HTML piece:

 <p>Pens and pencils</p>
index.js?ver=1566448714:12 Received HTML:

 
index.js?ver=1566448714:12 Received plain text:

 Pens and pencils
index.js?ver=1566448714:2 Processed HTML piece:

 <p>Pens and pencils</p>
```


![pasting](https://user-images.githubusercontent.com/519727/63487005-fdbf2800-c4ec-11e9-8349-1959915c336c.gif)

**Comment by ellatrix** [comment]
The problem is that we always force `BLOCKS` mode in the paste handler when the input field is empty. I remember there being a reason for it, but I forgot, and unfortunately it's not commented on. I'll search through some similar issues for an answer.

Regardless, whatever it did fix, we should find something better, because enforcing `BLOCKS` mode for an empty block seems like the wrong approach.

**Comment by ellatrix** [comment]
Related: #10614, #6516, but not seeing the answer there.

**Comment by ellatrix** [comment]
Found it. This code was added 2 years ago to tigger embedding when pasting a URL on an empty line. #3326

I'll work on a fix now.

**Comment by ellatrix** [comment]
This issue is also a blocker for me to introduce splitting to captions. Without a fix you wouldn't be able to paste in an empty caption.
