### ISSUE TITLE
Cover: Allow directly setting a background

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16996]
The `Cover` block has evolved quite a bit from its time as just a `Cover Image`, supporting a lot of interesting configurations (videos, overlays, etc).

It'd be interesting to let users select a solid color if they want to skip setting an image or video from the placeholder step. It could look something like this:

![image](https://user-images.githubusercontent.com/548849/62824369-ff0f5d00-bb9c-11e9-8f54-e7318c73b7ad.png)

When background gradient options are finalized, we should revise the presentation a bit.

Also, once patterns (#16283) are further established, it'd be cool to surface a few predefined defaults here as well to show the variety of end results. It gets tricky with media as it cannot be easily previewed before user uploads content.

**Comment by mapk** [comment]
This tends to push toward the Group block quite a bit. I'm okay with that because the Cover block feels much more opinionated design-wise. Providing background color support is a good evolution. The PR should also include the background color options in the Block Settings sidebar.

**Comment by enriquesanchez** [comment]
Hey @senadir! 

Here are a couple of initial mockups.

A) Similar to the color settings on the block sidebar, but using only one row of colors to keep it short. It includes the options to select a custom color (if one is selected, we can then show the `Clear` button)

<img width="804" alt="Screen Shot 2019-08-14 at 5 40 50 PM" src="https://user-images.githubusercontent.com/3276087/63061450-cc29d980-beba-11e9-9f31-298bcfc5cf06.png">

B) Similar concept but making the last color a color picker button instead.
<img width="804" alt="Screen Shot 2019-08-14 at 5 40 57 PM" src="https://user-images.githubusercontent.com/3276087/63061519-0e531b00-bebb-11e9-9069-d7e75b2aa4db.png">

Let me know what you think. Which one seems more feasible? 

cc @mapk

**Comment by senadir** [comment]
you can reference #17041
@enriquesanchez any use for the clear button?

**Comment by enriquesanchez** [comment]
>@enriquesanchez any use for the clear button?

**Comment by senadir** [comment]
and when selecting a color, the view changes directly and the options will move to the side panel, making the existence of the clear button useless in that view
