### ISSUE TITLE
Adding `loading="lazy"` to an image in HTML mode invalidates that image

### ISSUE THREAD

**Issue by wolffe** [WordPress/gutenberg#17008]
Adding `loading="lazy"` to an image in HTML mode invalidates that image and turns it into custom HTML. Native lazy loading in now live in Chrome and I'd like to be able to use it for all images.

 - OS: Windows 10
 - Browser: Chrome
 - Version: 76

I am using WordPress 5.2.2 without the Gutenberg plugin.

**Comment by draganescu** [comment]
Howdy @wolffe isn't this a correct behavior? I think all blocks are doing the same thing. Maybe this issue is more about making the image block have lazy loading optional or default?

**Comment by wolffe** [comment]
It's definitely not correct behaviour, as the parameter is a default HTML one. The image doesn't become invalid just by adding this parameter. But this is a non-issue now with the new core lazy loading plugin.
