### ISSUE TITLE
Pasting text from one block to the other creates strange results

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1700]
I was busy converting an old post (that had been converted to a Classic Text block by opening it in Gutenberg) to separate text and heading blocks. Right after the problem I had with heading blocks (#1698), I copied a paragraph from the Classic block and pasted it in a new Text block. Then this happened:

![ooops](https://user-images.githubusercontent.com/6073772/27833130-bafc5f32-60d1-11e7-8f47-5f891681e872.gif)

The placeholder text `Write...` stayed visible, while the pasted text was overlaid. The block also didn't expand in size to fit the new text, so it became a bit of a mess. Only after converting the block to a heading and then back into text did it go okay.

plugin version 0.3.0
chrome 59.0.3071.115
VVV2 dev environment
latest OSX macbook

**Comment by iseulde** [comment]
Having a hard time reproducing this. Any JavaScript errors? https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

**Comment by hedgefield** [comment]
Part of this may be caused by the Grammarly plugin, as we discovered in #1698, but with it turned off I still get some occasional weirdness (this and the overlapping text), so here's a sample of the errors in my console:

![new_post_ _wordpress_develop_ _wordpress](https://user-images.githubusercontent.com/6073772/27836860-9286ed6e-60e1-11e7-9671-1546513cbe19.png)

**Comment by iseulde** [comment]
@hedgefield Is this still an issue in the latest version?

**Comment by hedgefield** [comment]
No, because opening 'old' content in gutenberg now locks the entire text (see #2132), and pasting it in converts it to blocks 👍
