### ISSUE TITLE
No longer able to extend ServerSideRender

### ISSUE THREAD

**Issue by steveush** [WordPress/gutenberg#17000]
**Describe the bug**
Due to the changes made to extract the `ServerSideRender` package into a stand alone component any classes inheriting from it will break even after updating import statements. The issue is that `ServerSideRender` is now being wrapped in a `withSelect` which is then what is being exported in https://github.com/WordPress/gutenberg/blob/master/packages/server-side-render/src/index.js.

**To reproduce**
1. Create a new component that extends `ServerSideRender`.
2. Check the prototype.

**Expected behavior**
When importing the `ServerSideRender` component the actual component should be imported, not the `withSelect` wrapper.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.100

**Additional context**
- Using Gutenberg 6.2 & WordPress 5.2.2

The standard `ServerSideRender` component is lacking in a lot of features and many blog posts can be found showing how to extend this component to add in those missing features. Personally this is going to effect only one of my own plugins but that alone has over 100k users so I can only assume there will be many others caught out by this change once it goes live.

If I've missed a simple way to import the actual component without its' wrapper please let me know.

Thanks

**Comment by kevin940726** [comment]
Extending a component is not a recommended way in React. Instead, you should wrap it with another higher-order component if you need more controls. See [Mixins Considered Harmful](https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html) for more info.

I think we can close this as it's unlikely we would revert this change. Happy to discuss about alternatives though :)

**Comment by pryley** [comment]
@kevin940726 A common reason for extending ServerSideRender was to provide a way to trigger something after a render. Currently this is not possible. I have suggested a React solution for this here: https://github.com/WordPress/gutenberg/issues/35294

**Comment by steveush** [comment]
@pryley Initializing JavaScript on the newly rendered markup is precisely why I was previously extending ServerSideRender.

I ended up basically doing as you mentioned in your feature request, basically copying the current class and adding in a hook allowing me to do something after it had rendered. This has served me well now for basically 2 years but it does leave a bad taste in my mouth having to duplicate the entire class rather than just hooking into some form of pre-existing callback.

@kevin940726 I hope you guys take a look at @pryley's request and implement it. I'm willing to bet there are many plugins with a complete copy of the ServerSideRender class in them just to be able to initialize some JavaScript on the newly rendered markup.

**Comment by kevin940726** [comment]
I'm not sure about implementing a `onRender` prop on `<SeverSideRender>` but I don't see why not either. I was simply closing this issue because it's unlikely we would converting back to class based component, but happy to discuss alternatives in other issues or PRs :).
