### ISSUE TITLE
Custom sidebar do NOT show under 782px width screen

### ISSUE THREAD

**Issue by conanliuhuan** [WordPress/gutenberg#17021]
**Describe the bug**
Custom sidebar do NOT show on 600~782px width screen.
Custom sidebar Button disappeared on 600px and smaller width screen.

**To reproduce**
1. Follow ["Gutenberg handbook / tutorials" ](https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/plugin-sidebar-1-up-and-running/) to registered a custom sidebar.
2. Open editor (Write a new post)
3. Resize your browser width smaller than 782px
4. Try to click sidebar button, No effects!

**Expected behavior**
The sidebar can open correctly

**Screenshots**
![图片](https://user-images.githubusercontent.com/26618275/62921706-083a3d00-bddc-11e9-8cac-1265ce94808e.png)
![图片](https://user-images.githubusercontent.com/26618275/62921733-2011c100-bddc-11e9-9655-ccd3296d4080.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 68.0.1

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by HardeepAsrani** [comment]
Yea, that's the expected behavior as all the icons are collapsed to make space for toolbar in mobile. 

<img width="212" alt="Screen Shot 2019-09-20 at 8 48 42 pm" src="https://user-images.githubusercontent.com/2649903/65338569-1869e700-dbe8-11e9-9a2c-88cc73de81e5.png">
