### ISSUE TITLE
The Events Calendar w/blocks - Editing event resets the date and featured selection

### ISSUE THREAD

**Issue by kimwhite** [WordPress/gutenberg#17029]
**Describe the bug**
When the Gutenberg plugin is activated, when I go to edit and existing event, it resets the date, time, and featured checkbox.   The Date gets changed to the current day.

**To reproduce**
1. Go to an event
2. Click on "edit event"
3. When open you will see date has been reset to the current day, date is reset, featured meta removed

**Expected behavior**
The date should stay the same, time should stay the same, featured event meta should stay checked.

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser [chrome, safari, firefox]

**Additional context**
- Gutenberg Version 6.2.0
- The Events Calendar Version 4.9.6

**Comment by swissspidy** [comment]
This might just as well be an issue in the Events Calendar plugin itself. Have you reported this to the respective developers as well?

**Comment by kimwhite** [comment]
Yes. I also submit bug report to the Gutenberg .git.

And yes. I deactivated pro and it still happen.

Kim White
Cell: 610.533.0254
Pixelpaper.net
websites – updates – training

**Comment by kimwhite** [comment]
I'm sorry. I answered that backwards.
YES. I submitted a ticket to The Events Calendar also.

**Comment by kimwhite** [comment]
I just heard back from The Events Calendar, the tech who responded to me does not appear to be aware of the Gutenberg plugin. They instructed me how I could disable blocks.
I wrote and explained the plugin and that I DID want to use blocks.

**Comment by bph** [comment]
We just experienced on one of our sites as well. It worked with 6.1.1 and now after upgrade to 6.3 is resets the event date to today's date: https://recordit.co/XnVdp2Z3P3

**Comment by leahkoerper** [comment]
Hey there, Leah from The Events Calendar team here. Thanks for reporting this issue! We've now got it logged in our internal tracker as well so we can look into a fix.

**Comment by paaljoachim** [comment]
Sometime has passed and I also see that @leahkoerper has responded.
I will go ahead and close this issue. If that is a mistake then I will reopen the issue.
