### ISSUE TITLE
Create optgroup control inside the components package

### ISSUE THREAD

**Issue by ferdiesletering** [WordPress/gutenberg#17032]
In my project, I've created a custom optgroup control. 
<img>
I was wondering maybe this could be a contribution to Gutenberg. The components package contains a select-control.

![image](https://user-images.githubusercontent.com/6705443/63013695-16946180-be8d-11e9-8fc8-5272a5126dee.png)

**My considerations where:**
1. Add to the current select-control, which I think is impossible due to the data structure of the options parameter.
2. Create a new control `optgroup-control` which has many similarities to the `select-control`
 
I would love to contribute and implement this feature. Before I start, I want to make sure this would be a useful contribution.

Any feedback is welcome

**Comment by JohnRDOrazio** [comment]
I would also like to see optgroup implemented for the SelectControl, perhaps when an array is supplied as the "value". See a similar discussion on the WP Customizer Controls here:
https://core.trac.wordpress.org/ticket/47692

**Comment by Ugoku** [comment]
Bumping to avoid this issue being closed by the upcoming Stalebot

**Comment by t-hamano** [comment]
In #29540, the `SelectControl` component now supports `children` prop. This allows for the injection of `optgroup` elements.

- [Usage (Render a user interface to select items within groups)](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/select-control#usage-1)
- [Storybook (With Custom Children)](https://wordpress.github.io/gutenberg/?path=/story/components-selectcontrol--with-custom-children)

I would like to close this issue as I believe it was resolved, but if I have missed something, please comment.

**Comment by Ugoku** [comment]
Just tested this in WordPress 6.2 and it appears to work perfectly! @t-hamano do you know in which Gutenberg version (or WP version) this was implemented?

**Comment by t-hamano** [comment]
@Ugoku 

#29540 was included as part of Gutenberg 11.8. And [Gutenberg 11.8 is bundled with WordPress 5.9](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/). Perhaps it was available starting with WordPress 5.9.

**Comment by Ugoku** [comment]
Thanks!
