### ISSUE TITLE
Add shortcode block inside cover block

### ISSUE THREAD

**Issue by uok** [WordPress/gutenberg#17037]
**Describe the solution you'd like**
Currently you can insert a paragraph, headline or button into a cover block. It would be great to also have a shortcode block available.

**Describe alternatives you've considered**
Workaround: Inserting shortcode into paragraph block seems to work (but of course inside `<p>` tag

**Comment by youknowriad** [comment]
All blocks are available since the previous Gutenberg plugin release.
