### ISSUE TITLE
Deeplink support for plugin sidebars (and other UI)

### ISSUE THREAD

**Issue by roborourke** [WordPress/gutenberg#17035]
## The problem

With the default block editor you are always presented with it in the default state, or with any panels opened in the document sidebar still open.

In my specific use case I wanted to link from a notification (eg. an email) to the post edit screen with my plugin sidebar already open, as that's the next step a user would need to take given the context of the notification.

It would be preferable for there to be a standard core approach to doing this rather than plugins having their own individual solutions.

## Suggested approach

If every part of the editor eg. sidebars, panels, options, block navigator, views are addressable or knowable in some way such as `my-plugin/my-sidebar` for plugin sidebars then the editor could use a URL hash to figure out what to show or not. For example:

```
http://example.com/wp-admin/post.php?post=1&action=edit#show:my-plugin/my-sidebar
```

Would load the edit screen with the requested sidebar visible.

## Alternatives

So far I have implemented the above approach just within my plugin.

Another possibility might be linking via a proxy admin page that updates user preferences and redirects to the edit screen.

**Comment by talldan** [comment]
@roborourke I don't think deep linking is the kind of thing that would be implemented as a core api, but I think what you describe might already be possible for a plugin.

The plugin would have to check the URL for the specific parameter, and when that's present call a function to open the sidebar. Some of that's described here:
https://developer.wordpress.org/block-editor/packages/packages-edit-post/#PluginSidebar

The specific function call is:
```js
wp.data.dispatch( 'core/edit-post' ).openGeneralSidebar( 'plugin-name/sidebar-name' );
```

I'll close the issue given everything seems possible. Feel free to continue to ask any questions and I'll keep an eye out for an answer.
