### ISSUE TITLE
Wrong error message in registerFormatType

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#17039]
**Describe the bug**
When using `registerFormatType()` with no `className` and a `tagName` of `span`, this triggers the following warning:

https://github.com/WordPress/gutenberg/blob/989c224ce81008d3448932cfb03aa0a71922e6be/packages/rich-text/src/register-format-type.js#L81-L90

However, the format name in that error message is actually

**To reproduce**

Register a format like so:

```js
registerFormatType( 'foo', { title: 'Foo', tagName: 'span', className: null } );
```

Notice error message in the console says:

```
Format "foo" is already registered to handle bare tag name "span".
```

Run `wp.data.select( 'core/rich-text' ).getFormatTypeForBareElement( 'span' )` in the console and you'll get the `foo` format back.

The weird thing is the format registration should actually bail early, so no idea why it's even added to the formats list in the first place.

**Expected behavior**

I was expecting a message like this:

```
Format "Underline" is already registered to handle bare tag name "span".
```

Because the Underline format currently uses `span` without `className`.

**Screenshots**

**Additional context**

- Gutenberg 6.3.0

**Comment by Mamaduka** [comment]
Hi, @swissspidy

I'm no longer able to reproduce this issue. Used following code for testing:
```js
wp.richText.registerFormatType( 'format/foo', { title: 'Foo', tagName: 'span', className: null } );
wp.data.select( 'core/rich-text' ).getFormatTypeForBareElement( 'span' );
```

**Comment by swissspidy** [comment]
Yep looks like this no longer occurs.
