### ISSUE TITLE
Post scheduler: Cannot move to prev/next month

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#17042]
After upgrading to Gutenberg 6.3.0, I cannot move to the previous or next month when scheduling a post publish date. The date picker dialog is hidden after clicking on the navigation buttons:

![Aug-15-2019 11-15-40](https://user-images.githubusercontent.com/1233880/63068526-65560000-bf4e-11e9-91fc-9bc71bd98ff2.gif)

The issue is not reproducible in Gutenberg 6.2.0.

**Comment by mmtr** [comment]
I wonder if this is a regression caused by https://github.com/WordPress/gutenberg/pull/14851 cc @aduth

**Comment by youknowriad** [comment]
I think the problem is related to #14851 but the fix shouldn't be to update how withFocusOutside work. I think there's an a11y bug where in some browsers, the focus is lost entirely when we switch months. Ideally, when switching months, the focus should:

 - Stay on the button we just clicked
 - Focus the first day of the shown month.

**Comment by talldan** [comment]
Tricky one to resolve as the button is handled internally to https://github.com/airbnb/react-dates ... this component in particular:
https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerSingleDateController.jsx

It seems like a completely new dom tree is mounted for the date picker on every month change, which seems entirely unnecessary. Initially I thought this `key` prop might be one of the reasons for that, but removing it has no effect on the bug:
https://github.com/WordPress/gutenberg/blob/2e45a8b1b75d40933e73d19a4068e82235b3b7ca/packages/components/src/date-time/date.js#L67

Did some digging in the issues and this seems like it might be relevant:
https://github.com/airbnb/react-dates/issues/1006

**Comment by jorgefilipecosta** [comment]
I confirmed using git bisect that this regression was intruduced in #14851.

**Comment by getdave** [comment]
Does this fix it?

https://github.com/WordPress/gutenberg/pull/1705
