### ISSUE TITLE
Gallery: flow for adding new items

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1704]
Let's figure out a way to add and remove new images without going through the media library. This would also mean that the placeholder view can show individual gray boxes for missing images, thus reflecting column count even before you added images.

**Comment by mtias** [comment]
Another good thing would be to allow dragging an image to an existing gallery to add to it. Moving to "nice to have" since we do have a flow through the library.

**Comment by youknowriad** [comment]
Can we close this issue, as we can add an image with Drag And Drop and remove them by selecting and removing images? Or should we add a "+" somewhere to allow adding images individually from the media library?

**Comment by mtias** [comment]
I think we should add a plus, maybe on the toolbar as a quick action — drag and drop is a bit of a hidden feature. cc @jasmussen @karmatosed

**Comment by mtias** [comment]
@jasmussen yes, though my expectation was that it would add a new placeholder thumb to the gallery, with the same controls as an image block to upload directly.

That said, this is not high priority and comes with a few difficult interactions to sort, so let's keep it on the backlog.

**Comment by jasmussen** [comment]
Ah, I see! If course. Something like this?

Unselected, 2 column gallery:

<img width="340" alt="unselected" src="https://user-images.githubusercontent.com/1204802/34562755-04d673f4-f150-11e7-9001-40d0cfe32d54.png">

Selected 2 column gallery:

<img width="369" alt="selected" src="https://user-images.githubusercontent.com/1204802/34562762-0aa1813e-f150-11e7-8afb-709712375da4.png">

**Comment by mtias** [comment]
Yep :)
