### ISSUE TITLE
List block: allow dynamic numbering 

### ISSUE THREAD

**Issue by andreamiddleton** [WordPress/gutenberg#17040]
I'm writing a list of procedures that is interrupted by block quotes and things, so I need to restart my numbering in different blocks from time to time. 

I'd like to be able to start a list at any number, and have the list block continue the numbering for me. 

Currently my workaround is to number each item manually, which is clunky and annoying. To be fair, I am used to the slick numbered list tool in Google Documents.

**Comment by swissspidy** [comment]
That would be a really nice addition.

Just saw that #13888 with the suggested fix at #15113 covers this, so I am closing this issue as a duplicate. Please follow that for any updates :-)

**Comment by ellatrix** [comment]
Hi @andreamiddleton and @swissspidy. That's being worked on indeed! I'll rebase that PR today, and leave out the more controversial pieces for a separate PR.

**Comment by ellatrix** [comment]
Fixed. This will be in Gutenberg 6.4 and WordPress 5.3.

**Comment by GwynethLlewelyn** [comment]
Seems to be a pity that we'll have to wait so long for such an important change... the beta version is still at 5.2.5, one has to run the bleeding edge version to get 5.4 (what happened to 5.3???) and cross fingers that everything else still works...

Anyway, thanks for implementing this for 2020...

**Comment by ellatrix** [comment]
@GwynethLlewelyn WordPress 5.3 is coming 12 November, which includes this change. See https://wordpress.org/news/2019/10/wordpress-5-3-rc2/.
