### ISSUE TITLE
[Embed] Gist works but returns error

### ISSUE THREAD

**Issue by dougaitken** [WordPress/gutenberg#17054]
**Describe the bug**

Sorry, this content could not be embedded.

Much like #16575 & 

Opened in #1567 

**To reproduce**
1. Add new embed block
2. Copy and paste a Gist link such as `https://gist.github.com/dougaitken/4a2e9469dee1ed2a6e67ab3fbb947b3b`
3. Click Embed

**Expected behavior**

A message should return showing the Gist works or the Gist should show the embed

**Screenshots**

![https://cld.wthms.co/JIpBZV](https://cld.wthms.co/JIpBZV+)
Image link: `https://cld.wthms.co/JIpBZV`

**Desktop (please complete the following information):**
 - macOS 10.14.6
 - Firefox & Chrome latest

**Comment by paaljoachim** [comment]
Hi Doug @dougaitken 
I noticed the image is broken. Can you upload the image again?

**Comment by youknowriad** [comment]
Thanks for the issue @dougaitken The issue is that Github doesn't support OEmbed which means WordPress can't add support by default unless we use a custom API which is not something WordPress did in the past. We don't rely on custom third party APIs.

See comment here https://github.com/WordPress/gutenberg/issues/1567#issuecomment-521893967

**Comment by youknowriad** [comment]
I believe you're testing in an environment where there's a plugin that make these links work on the frontend. In which case, this plugin should also try to register a custom embed block for the Gist Provider.

**Comment by dougaitken** [comment]
I must've deleted it @paaljoachim but the error was the same as #16575 

Thanks, @youknowriad - I tried to reproduce with only WP and the GIst was shown on the front-end as a plain link so looking into it more, I think it is Jetpack which is rendering it and I've been so used to see it 🙈 

Looks like Automattic/jetpack/issues/10161 is the best place for this now

**Comment by paaljoachim** [comment]
I sent an e-mail to Github support asking them if they can support OEmbed for embedding gists in WordPress. They will look into it.

**Comment by youknowriad** [comment]
Thanks for the update. 

@paaljoachim That's great 👍 Keep us up to date.

**Comment by jasperf** [comment]
Any news on that request @youknowriad ?

**Comment by paaljoachim** [comment]
Hey @jasperf 

I sent another support request to Github a few days ago. They sent it onward to their developers.
Keep the pressure on and do also send them requests about supporting OEmbed.
