### ISSUE TITLE
List Block: indenting in reverse order messes up numbering

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#17052]
**Describe the bug**

<img width="643" alt="Screenshot 2019-08-15 at 13 37 59" src="https://user-images.githubusercontent.com/4710635/63092396-ecf93a00-bf61-11e9-9a44-304b3f059be1.png">

**To reproduce**

* Convert the list in the demo content to a numbered list.
* Indent one of the middle items.
* Indent the item above.
* Both items now have the number 1...

**Expected behavior**
The second item should have the number 2.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by draganescu** [comment]
I've hit this bug as well. Easily solved by converting to unordered and then back to ordered.

**Comment by draganescu** [comment]
My solution does not work because now we also have #32405 wich will cause content to be lost when switching list types.
