### ISSUE TITLE
Image block – Can't set theme specific image size for external URL image

### ISSUE THREAD

**Issue by r-manasek** [WordPress/gutenberg#17062]
**Describe the bug**
Image block has a drop down menu where one can select from image sizes (both built-in and registered by the theme). Selecting any of drop down menu items works properly only for images inserted through the media library or uploaded from a local HD. For images inserted from an external URL, the drop down menu always selects the large image size.

**To reproduce**
1. Add Image Block
2. Click on 'Insert from URL'
3. Paste or write URL and confirm
4. Go to Image Size drop down menu and select any of available sizes
5. Despite selection made, large size is always picked

**Expected behavior**
Same behaviour like for images inserted via media library

**Desktop**
 - OS: macOS High Sierra 10.13.6
 - Browser Safari 12.1.1

**Additional context**
Gutenberg 6.3.0, but is the same in the latest version bundled with the latest worpress core version

Sorry for my English, I am not a native english speaker

**Comment by youknowriad** [comment]
Thanks for the issue, unfortunately, the image sizes offered by WordPress work by targetting specific images files created when you upload an image to the media library (depending on the defined sizes).

When using an external URL, there's no way to guarantee that these URLs exist. WordPress doesn't manipulate external images.

I'm going to close this issue as there's nothing we can do about it.

**Comment by r-manasek** [comment]
But why this works while setting the image size in pixels in width and height fields?

**Comment by youknowriad** [comment]
Yes, but that's not the same thing. 

The size selector is about selecting which image file to use, the width/height fields are about resizing the image in the browser directly.

**Comment by r-manasek** [comment]
OK.

As for original issue: so why using external URL at all if there's no way to guarantee that these URLs exist...

I think it would be sufficient to let the drop down menu select from listed (and registered) image sizes (rather then pushing 'large-size' as defaults – this is a real bug by my opinion). The rest would be up to the theme (and Jetpack plugin which can handle delivering proper image sizes). Just my cents...

**Comment by youknowriad** [comment]
I feel like there's something I'm not understanding properly in this issue. If you choose "Insert from URL" you're going to provide an image URL, there's no guarantee this is even coming from a WordPress website or anything. You're just saying use this URL, there's no "large size" or any size in that case.
