### ISSUE TITLE
Author field is required in Gutenberg for Custom Post Type

### ISSUE THREAD

**Issue by stuartshields** [WordPress/gutenberg#17073]
So currently when you create a Custom Post Type and are using Gutenberg, when a post is saved the `post_author` field in the database for that post is `0`. This does not happen in the classic editor or revisions.

**Steps to reproduce**
1. Create a custom post type using `register_post_type`
2. Create a new post for the new custom post type
3. Check database table `*_posts`
4. `post_author` field is 0

Confirmed this has been happening in all versions of Gutenberg.

**Short term solution**
When creating the custom post type make sure to add `author` is added to `supports` and this will add the author id to the post.

Because of this we should also update the documentation for Gutenberg when using Custom Post Types.

**Long term solution**
Because Post and Page automatically add the author id to the `post_author` column in the database when using Gutenberg, we should also make this happen for Custom Post Types, as this the case with the classic editor.

Let me know if you need anymore information on this.

**Comment by swissspidy** [comment]
To me that sounds like expected behavior 🤔 if a post type does not support authors, no post author should be set in the database.

**Comment by stuartshields** [comment]
@swissspidy That goes against how WP worked previously before Gutenberg, I just went in and created a new CPT that doesn't have anything for author under `supports` and didn't have Gutenberg enabled, the author was added to the database. We should make Gutenberg reflect this functionality as well.

**Comment by tomjn** [comment]
I did a quick check, and wrote a simple plugin and a JS snippet to test this:

<details>
<summary>Test CPT Plugin</summary>

```php
<?php
/**
 * Plugin Name: Tom No Author Rest Test
 **/

add_action( 'init', 'codex_noauthorbook_init' );
function codex_noauthorbook_init() {
	$labels = array(
		'name'               => _x( 'Books', 'post type general name', 'your-plugin-textdomain' ),
		'singular_name'      => _x( 'Book', 'post type singular name', 'your-plugin-textdomain' ),
		'menu_name'          => _x( 'Books', 'admin menu', 'your-plugin-textdomain' ),
		'name_admin_bar'     => _x( 'Book', 'add new on admin bar', 'your-plugin-textdomain' ),
		'add_new'            => _x( 'Add New', 'book', 'your-plugin-textdomain' ),
		'add_new_item'       => __( 'Add New Book', 'your-plugin-textdomain' ),
		'new_item'           => __( 'New Book', 'your-plugin-textdomain' ),
		'edit_item'          => __( 'Edit Book', 'your-plugin-textdomain' ),
		'view_item'          => __( 'View Book', 'your-plugin-textdomain' ),
		'all_items'          => __( 'All Books', 'your-plugin-textdomain' ),
		'search_items'       => __( 'Search Books', 'your-plugin-textdomain' ),
		'parent_item_colon'  => __( 'Parent Books:', 'your-plugin-textdomain' ),
		'not_found'          => __( 'No books found.', 'your-plugin-textdomain' ),
		'not_found_in_trash' => __( 'No books found in Trash.', 'your-plugin-textdomain' )
	);

	$args = array(
		'labels'             => $labels,
		'description'        => __( 'Description.', 'your-plugin-textdomain' ),
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'book' ),
		'capability_type'    => 'post',
		'has_archive'        => true,
		'hierarchical'       => false,
		'menu_position'      => null,
		'show_in_rest'       => true,
		'supports'           => array( 'title', 'editor', 'thumbnail', 'excerpt', 'comments' )
	);

	register_post_type( 'noauthorbook', $args );
}


add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_script( 'wp-api' );
});
```

</details>

<details>
<summary>JS to create posts</summary>

```js
var ourPostData = {
    "title" : "test book",
    "content" : "Lorem Ipsum",
    "status": "publish",
    "author": 2
}

var createPost = new XMLHttpRequest();

createPost.open("POST", wpApiSettings.root + wpApiSettings.versionString + "noauthorbook" );
createPost.setRequestHeader('X-WP-Nonce', wpApiSettings.nonce);
createPost.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
createPost.send(JSON.stringify(ourPostData));
createPost.onreadystatechange = function() {
    if(createPost.readyState == 4) {
        if( createPost.status == 201 ) {
            console.log('201');
        } else {
            console.log('Error - Try again.');
        }
    }
}
```

</details>

The JS on the frontend when ran in the dev tools console will attempt to create a post and assign the author as user `2`. In my tests the REST API assigns the author as the current user  ( `1` in my case ). The same is true if I ommit the `author` field from the REST request

I then tried to reproduce the issue in WP 5.2.2, and again with the Gutenberg v6.3.0 plugin installed and active. Both resulted in a post of `noauthorbook` with author value of `1`. I checked this by looking in the posts table directly.

Perhaps I missed something, or there's another factor involved. I performed the tests logged in as an administrator on a single site install, happy to do some follow up testing

**Comment by stuartshields** [comment]
@tomjn You need to make sure you check what is saved in the database. Please try again, as I copied your code and got the same response in the database.

**Comment by tomjn** [comment]
hmmm I'll have to retest in a multisite environment, here's a screenshot of my results for reference:

<img width="507" alt="Screenshot 2019-08-23 at 00 13 17" src="https://user-images.githubusercontent.com/58855/63555988-e9098100-c53a-11e9-82a9-ecbfe699972c.png">

**Comment by stuartshields** [comment]
Also just updated the install to WP 5.2.2 just incase, but I can confirm the issue still happens.

**Comment by tomjn** [comment]
Retested in a multisite with the same results

**Comment by stuartshields** [comment]
@tomjn Another thing is how are you calling the CPT? Is it from themes folder?

**Comment by tomjn** [comment]
literally as I described earlier, copy the install test CPT plugin into the plugins folder and active, then copy paste the JS into the dev tools console to test, check the database table for the result

**Comment by markhowellsmead** [comment]
Additional for this issue. (Perhaps related.) If a custom post type is registered without author support, then the author support is added later, the author `select` isn't shown in the Gutenberg document sidebar. If `show_in_rest` is then set to false, the post reloaded, then set to true again, then the post is reloaded again, the `select` appears from then on.

**Comment by talldan** [comment]
The block editor doesn't send any author data to the REST API when saving regardless of the post type, this seems to be set by the REST API server side. 

Here's the example payload sent when saving a new post that shows no author data is sent:
<img width="429" alt="Screenshot 2020-04-22 at 2 06 03 pm" src="https://user-images.githubusercontent.com/677833/79946521-c00f0680-84a2-11ea-9050-fd1fdb7ada94.png">

Since this logic is defined server side, I think this ticket is in the wrong place, REST API issues are tracked in core trac. It looks like there's an issue here that covers things, so lets transfer the conversation:
https://core.trac.wordpress.org/ticket/47041
