### ISSUE TITLE
Error on update MCE Views in gutenberg block "Classic Editor"

### ISSUE THREAD

**Issue by vjik** [WordPress/gutenberg#17087]
**Describe the bug**
Block "Classic Editor" refresh and no changes are applied to MCE Views.

**To reproduce**
- Install new site on WordPress 5.2.2.
- Create new page.
- Add editor block "Classic".
- Add media gallery into classic editor with 2+ images.
- Open edit gallery window.
- Switch to another tab in the browser.
- Wait a little...
- Get back to tab with WordPress.
- Make any change in "edit gallery window" and click "Update gallery".
- Gallery is not updated and there is an error in the browser console.

The problem is also observed in other plugins that use MCE Views for pretty view shortcodes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome 
 - Version 76

**Additional context**
- Internal in WordPress 5.2.2 or Gutenberg 6.3.0

Error in browser console:
```
wp-tinymce.js?ver=4940-20190515:3 Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at wp-tinymce.js?ver=4940-20190515:3
    at Object.map (wp-tinymce.js?ver=4940-20190515:3)
    at Object.select (wp-tinymce.js?ver=4940-20190515:3)
    at mce-view.min.js?ver=5.2.2:1
    at Function.s.findKey (underscore.min.js?ver=1.8.3:1)
    at Function.s.find.s.detect (underscore.min.js?ver=1.8.3:1)
    at N.d.update (mce-view.min.js?ver=5.2.2:1)
    at mce-view.min.js?ver=5.2.2:1
    at N.d.<anonymous> (mce-view.min.js?ver=5.2.2:1)
    at s (backbone.min.js?ver=1.2.3:1)
```
----

I think reason of problem in the following: after open "edit gallery window" gutenberg block updated, and after click "Update gallery" node for update (use in "update" function in mce-views) no longer in the document.

**Comment by paaljoachim** [comment]
Hey @vjik Sergei

Thank you for creating the issue!
A lot of time has passed.
Is this issue still valid?

**Comment by vjik** [comment]
Seems already not actual.

**Comment by paaljoachim** [comment]
I will then go ahead and close the issue. Please reopen if need to.
