### ISSUE TITLE
Button Block: Refactor to avoid cropping the URL input field

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#17086]
When a button has short text, the URL input field is cropped initially, cutting off part of its placeholder text: 

![button-crop](https://user-images.githubusercontent.com/1202812/63266638-5a58e380-c25e-11e9-8e62-533c46593bef.gif)

This should be adjusted so that the text isn't cut off, but so that it will (ideally) still fit in areas where there isn't much room.

---
Originally noted in #17063, related to updates made in #16873.

**Comment by talldan** [comment]
A couple of other issues that might also have resulted from #16873.

The movers are incorrectly sized when a left/right alignment is set on the button block:
![Screen Shot 2019-10-18 at 2 50 23 pm](https://user-images.githubusercontent.com/677833/67072197-eb90fb80-f1b6-11e9-965d-10b620a759e4.png)

Block warnings aren't full width for the button block:
![Screen Shot 2019-10-18 at 2 51 14 pm](https://user-images.githubusercontent.com/677833/67072245-05324300-f1b7-11e9-805d-8108ab21fb7d.png)

**Comment by skorasaurus** [comment]
I came across this while debugging another button issue; this appears to now be fixed; I'm unable to reproduce this. 

Below is what appears even while emulating a small moto4 (width 360px) in chrome
![zach test_wp-admin_post php_post=8 action=edit(Moto G4)](https://user-images.githubusercontent.com/955351/99846524-796eb100-2b44-11eb-97cb-d792c15ff371.png)

**Comment by kjellr** [comment]
It is! The URL field has moved back into a popover, so this is no longer an issue. Thanks for the nudge!
