### ISSUE TITLE
Columns - drag and dropping in to an empty column

### ISSUE THREAD

**Issue by SpeccyGreg** [WordPress/gutenberg#17081]
This is a usability issue I am having, if you have a 3 column layout, with content in two of them but an empty third, you can not drag content into the empty column unless you add a block to it first! Which I think is very annoying and not very user-friendly.

**Comment by youknowriad** [comment]
I was able to drag and drop into an empty column. Can you provide a screenshot? Which Gutenberg version are you using?

**Comment by SpeccyGreg** [comment]
Hi Riad,

Sure, see attached video.

https://www.dropbox.com/s/pfdfs1apm13mhc4/GB%20-%20column%20issue.mov.zip?dl=0

Version 5.8.0, maybe an updated might solve it. I can't update the live
site yet as need some time to do that.
but if you can confirm if that is the cause? Was it a known bug that was
fixed?

—-—-—-—-—-—-—-

Additionally, still not a massive fan of Gutenberg, I can see why WP needed
to go down this route, but the interface is so buggy and really hard to
use. It's cramped, and confusing.
Just trying to select blocks that are existing on a page is hard! which it
really shouldn't be.

I'm hoping it improves!  Thanks.


Kind Regards,




[image: Greg]

Creative Director
01473 356403 <01473356403>




  [image: Rubious] <https://rubious.co.uk/>   [image: Design with flawless
clarity]

**Comment by youknowriad** [comment]
In master,  I'm definitely able to drag into an empty column. Let me know when you'll be able to drag.

**Comment by youknowriad** [comment]
I'm going to close the issue as it's fixed for me but let's reopen if it comes up again.
