### ISSUE TITLE
Documentation: Add information about core/data isResolving

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#17082]
The `isResolving` selector on the `core/data` store appears to be undocumented. Please consider adding detailed documentation on how to use this selector.

**Comment by paaljoachim** [comment]
Hey @sirreal Jon

Thanks for creating the issue!
I see no linked PR so I assume that this issue is still valid.

Marcus @mkaz is this something for you to take a closer look at? Thanks.

**Comment by xavier-lc** [comment]
Whenever you tackle this, please remember to add `hasFinishedResolution` and `hasStartedResolution` too! In the meantime, the documentation on https://unfoldingneurons.com/2020/wordpress-data-store-properties-resolvers is an amazing alternative.
