### ISSUE TITLE
Navigation menu block: Revisit placeholder/default state

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#17096]
From #16821:

> Explore how the Nav block works when added to the page.
> Does it default to the primary menu?
> Does it offer an empty state for creating new Navs?
> Are there helper messages?
> Tips?
> Place holders?

## Prior work

When @melchoyce and I originally worked on this, we spent some time discussing what happens when a user adds a navigation menu block—see sketches and conversation over at #13786.

Our [original proposal](https://github.com/WordPress/gutenberg/issues/13690#issuecomment-480102173) suggested a "smart menu" to reduce the burden of choice on the user:

---------
When the user selects the “navigation menu” block, a few things happen behind the scenes in an attempt to help them start with as smart a default as possible. 

First, the menu is contextual depending on where the user is adding it to their site. 

- Site header → defaults to a horizontal menu with a selection of their top- and second-level pages
- Site footer → orientation is vertical, same content
- Post or page → menu is acts as a table of contents, linking to the headings in the page.

We then try to build out a menu for the user, following this logic:

![](https://paper-attachments.dropbox.com/s_BE4B35674A1F3200488D7675F494F87A67C5DC5159263086EB2F576364E6A10B_1554324260775_Smart+Menu+Flow2x.png)

1. If the user already has a legacy menu on their site, we build them out a menu automatically from the existing menu and show a notification.
2. If the user has multiple legacy menus, we ask them which they’d like to use.
3. If the user doesn’t have any legacy menus but has > 5 top-level pages on their site, we build them a menu automatically from the top-level pages (maybe also second-level?) We use a notification to let the user know we’ve built them out a menu automatically, and the “add new pages automatically” setting is checked by default.
4. If we don’t have enough information to build a smart menu, we present the user with a short wizard to get up and running more quickly.
----------

## Exploring further

Before diving back into explorations, I'd like to be sure I'm clear on our aim here. Are there technical or UX problems inherent in the proposed model we need to resolve? Do we want to scrap the concept of a "smart" menu altogether and introduce more manual choices for users, or do we just need clarification on how the proposed model works? 

cc @mtias @mapk @karmatosed

**Comment by karmatosed** [comment]
I won't speak for others, for me there are a few factors here. I think the empty state should guide how to create. That's something to do in UI for example, which is why thinking placeholders here.

I wonder if by pre-filling out we are falling into the problem where a menu auto-populates in a theme and people get frustrated removing it.

Legacy menus I think perhaps building out is a good idea but that would be only if the menu wasn't on the page or post? I ask just to avoid double menus.

**Comment by sarahmonster** [comment]
Following a [discussion in Slack today](https://wordpress.slack.com/archives/C02S78ZAL/p1567087584206800) (Note: You may need a [Slack account](https://make.wordpress.org/chat/) to log in.), we've decided to close discussion on this issue and instead work from Mel's original mockups here: https://github.com/WordPress/gutenberg/issues/16974#issuecomment-522097790

We can reopen and revisit if any further design assets are required here.
