### ISSUE TITLE
Image Block maintains link to previous media after replacing an image

### ISSUE THREAD

**Issue by brandbrilliance** [WordPress/gutenberg#17119]
1. Create a Image block with LINK SETTINGS, set Link to "Media File".

2. When you switch out the image block using the "edit/pen" icon and select a new image, the link to "media" URL isn't changed. 

3. When you view the post, if you click on the thumbnail that you just changed in the saved post, then link is still to the previous image (in 1).

4. The hot fix currently for me it to change the drop-down for the Link to "None" and then changing it back to "Media" again. This "refreshes" the LINK URL.

**Comment by talldan** [comment]
I could also reproduce this.
