### ISSUE TITLE
Allow "Cover" block to be resizable

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#17113]
It'd be interesting to extend the **Cover** block with `ResizableBox`, in the same implementation as the **Spacer** block (resize handle at the bottom center), to allow changing the default height of the block.

**Comment by kjellr** [comment]
👍 Down the road, this may also be worth exploring for the Media & Text block as well.

**Comment by davipontesblog** [comment]
+1 to this. Many users ask for this option when customizing a landing page for example.
