### ISSUE TITLE
Only show the inserter help panel when opened from the top toolbar

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#17110]
Followup from #16813. 

Currently, the help panel is displayed on all desktop views of the block library:

<img width="814" alt="Screen Shot 2019-08-20 at 2 53 54 PM" src="https://user-images.githubusercontent.com/1202812/63375889-9bceb900-c35a-11e9-9b75-32abd7a4bc1c.png">
<img width="967" alt="Screen Shot 2019-08-20 at 2 54 16 PM" src="https://user-images.githubusercontent.com/1202812/63375890-9bceb900-c35a-11e9-9afa-91dbdec84106.png">
<img width="967" alt="Screen Shot 2019-08-20 at 2 54 42 PM" src="https://user-images.githubusercontent.com/1202812/63375891-9bceb900-c35a-11e9-935b-2a22144a2145.png">

In order to lighten up the experience, we should consider only displaying the panel when it's opened from the top toolbar.

**Comment by youknowriad** [comment]
Looks like this is the case now.
