### ISSUE TITLE
Question: No way to delete an empty block unless I start typing

### ISSUE THREAD

**Issue by stefanos82** [WordPress/gutenberg#17125]
While I was typing in my editor, I have created an empty block by mistake. I have tried to delete it, but couldn't see any option at the upper right corner of it; as soon as I have started typing, I could see the three dots that let me choose the deletion option.

Is this the expected behavior?

Why isn't there a delete option by default?

**Comment by talldan** [comment]
@stefanos82 Pressing backspace should allow you to delete the empty paragraph.

**Comment by stefanos82** [comment]
Ah very nice. I learned something new today :smile: thank you @talldan :+1:
