### ISSUE TITLE
Image block - "open in" option missing

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#17120]
Gutenberg 6.3

I'm not seeing the link options ("link to") anymore in the image block. Jumping back to Gutenberg 6.0 and it pops back. Is there a new workflow for this or what am I missing?

I've deactivated all plugins, using generatepress theme.

<img width="290" alt="Screenshot 2019-08-21 at 10 58 26" src="https://user-images.githubusercontent.com/40266703/63418038-b2c8e600-c402-11e9-95ac-0499234fd19d.png">

Cheers!

**Comment by mtias** [comment]
The image link tools have been moved to the main toolbar:

![image](https://user-images.githubusercontent.com/548849/63424877-a434fb80-c40f-11e9-9ac6-459e8211ccc4.png)

**Comment by slimmilkduds** [comment]
ahaa, missed that, thanks!
