### ISSUE TITLE
Block Inserter: Add graphical empty state

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17122]
If you search for something and get no blocks returned just text comes back:

![image](https://user-images.githubusercontent.com/2846578/63791503-9f69bf00-c8c9-11e9-962c-3e53ec0ea084.png)

It could be nice to have a graphic or something here to bring a little delight along with text that informs.

**Comment by melchoyce** [comment]
Some initial ideas:

![image](https://user-images.githubusercontent.com/2846578/63622678-6a0d5a80-c5c5-11e9-88c2-8061c0b5ee7d.png)

**Comment by enriquesanchez** [comment]
These are good! I like how the dashed outline combined with the question mark in the 2nd option provide a lot of context to this empty state.

**Comment by karmatosed** [comment]
I really like either 1 or 3 the most, although I like them all. I can see how 3 could have some animation behind it which might be nice.

**Comment by melchoyce** [comment]
Let's go with @kjellr's suggestion.
