### ISSUE TITLE
Improve the basics on mobile

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1712]
It is an early stage, but I today ran the editor through a really simple mobile test. I was using an iPhone 7 plus for this and the 0.3.0 plugin version.

In short, a lot was not possible. A lot was also very much more buggy than it was on desktop. Some areas like actually adding a block were particularly unpredictable in behaviour. Sometimes it shot up to the top, other times it didn't open.

I am aware that the fact it works on mobile at this point at all is a blessing, but we should be considering this experience as really important.

Here are a few screens to show a couple of issues. I would encourage at least some focus on a how this works on mobile. Maybe we just turn things off for now - ultimately though that would be a shame.

![img_1262](https://user-images.githubusercontent.com/253067/27841800-2cb52a94-60fc-11e7-8aa3-61e6b06dabf8.PNG)

![img_1261](https://user-images.githubusercontent.com/253067/27841804-2fc4e300-60fc-11e7-90fd-859eaa936dd0.PNG)

**Comment by jwold** [comment]
Your post inspired me to try writing a blog article on my iPhone 7 Plus as well. I gave up after a few paragraphs.

1. The initial interface for Gutenberg looks great. When I go to add a title it feels good.
2. As soon as I tap on the text below title it jumps the screen a bit and pops up with the UI box. At this point I just want to start typing, not formatting. 
3. When I press enter twice to create a new paragraph it pops into a new content box (discussed here: https://github.com/WordPress/gutenberg/issues/1561). 
4. Tried adding an image. The whole interface looks squished and I can't even load an image from my phone.

Agreed this needs some thought! :)

**Comment by karmatosed** [comment]
A core ticket to note: https://core.trac.wordpress.org/ticket/29923

**Comment by jasmussen** [comment]
Are these issues reproducable today? I feel like they should be fixed.

**Comment by mtias** [comment]
Going to close, let's open individual issues for individual bugs and improvements.
