### ISSUE TITLE
Post Updated notification overlaps with other UI elements

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1713]
## Issue Overview

When you update a post, the notifications hover in weird ways over the other UI elements.

## Steps to Reproduce (for bugs)

1. Write a new post in gutenberg.
2. Publish
3. Edit and save changes/update
4. Change browser size and scroll around
5. Make another change and update again
6. Now there are two notifications!

plugin version 0.3.0
chrome 59.0.3071.115
VVV2 dev environment
latest OSX macbook

## Expected Behavior

I'd want to see this banner full-width above the content column, preferrably sticky under the top toolbar.

## Current Behavior

On desktop, it looks like it's restricted to the empty space on the left of the content column. But when you start changing the browser dimensions it starts to overlap with the text, with the inspector, with the toolbar, even with the WP admin bar (layering issue I guess). It can also spawn off screen if you're looking at the bottom of your post, which defeats the point of having the notification at all.

![notif3](https://user-images.githubusercontent.com/6073772/27856547-c931d968-616e-11e7-9f85-d21d1061de82.gif)

**Comment by youknowriad** [comment]
The fixed position has been merged. and the multiple notifications is a duplicate of #1604

I think we should close this.

**Comment by hedgefield** [comment]
Cool thanks!
