### ISSUE TITLE
Cover block: Overlay setting is stuck inside the Cover setting in sidebar

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17131]
**Describe the bug**
The "Overlay" settings is inside the "Cover Settings" panel. They both visually have the same hierarchy though. When closing the Cover Settings panel, the Overlay settings is no longer viewable. This is confusing.

**To reproduce**
1. Add a Cover block.
2. Add an image.
3. View the Cover Settings panel and notice the Overlay panel below it, but at the same hierarchical level.
4. Collapse the Cover Settings panel and observe the Overlay panel has disappeared.

**Expected behavior**
I expect the Overlay panel to stay visible when the Cover Settings panel is closed. They both have the same visual hierarchy.

**Screenshots**

![overlay-panel](https://user-images.githubusercontent.com/617986/63468514-ee70a980-c41c-11e9-8c1e-7c8db9fad73c.gif)

**Solution**
I think the best solution here is to rename the "Cover Settings" panel as mentioned in @kjellr's comment here: https://github.com/WordPress/gutenberg/pull/17041#issuecomment-523591254 to "Media."

**Comment by ZebulanStanphill** [comment]
This kind of raises the issue of how to style nested accordions, or perhaps if nested accordions should even be used/recommended at all.

**Comment by senadir** [comment]
there shouldn't be nested accordions, Color Panel is a separate panel, someone mistakenly put it under settings panel, it should be fixed in #17041
