### ISSUE TITLE
Image block gets overflow when inserted in column with full width option

### ISSUE THREAD

**Issue by anischarolia-multidots** [WordPress/gutenberg#17141]
**Describe the bug**

While going through the Image block, and using its new "full width" option, I noticed that while using "Full width" option when image is inserted in one of the columns of "column block", the design gets disturbed both on admin and front side. It is because the image tries to get full width while column suppresses it.

**To reproduce**

1. Insert Column block and add image in one of the block.
2. Select "Full width" option for image.
3. You will see image will overflow beyond the column boundary and will break the design both in admin and front side.

**Expected behavior**
Here we should make it sure that this new "full width" option for image works fine in all scenario. It should not make trouble in any condition. Here as I found it doesn't work as expected in  column block. 

**Additional context**
-Possible solution:
Maybe we can fix that with css. Considering column as its parent, we can re-write all the css to normal which is being added with "[data-align="full"] on admin side and with class "alignfull" on front side. Or we can somehow code the image block with condition if it has column block as parent, the "full width" option will be hidden.

**Comment by anischarolia-multidots** [comment]
**Screenshots**

On admin side:

![admin-side-image-block](https://user-images.githubusercontent.com/53076388/63505719-aa030d80-c4f1-11e9-8552-84620b2a3730.png)

On front side:

![front-side-image-block](https://user-images.githubusercontent.com/53076388/63505767-bc7d4700-c4f1-11e9-8e10-ef0137c81726.png)

**Comment by youknowriad** [comment]
I can't seem to reproduce this anymore. It seems fixed.
