### ISSUE TITLE
IE11: Ctrl + K for linking text doesn't work, button works fine

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#17158]
There are some issues with the toolbar in IE11:

![ctrl k ie11](https://user-images.githubusercontent.com/1204802/63578226-4c71ce00-c590-11e9-8630-ef06c7f6d048.gif)

- <strike>The always-collapsed toolbar is causing for a broken layout</strike>
- <strike>Accessing the link button is difficult, but the link function works there.</strike>
- Ctrl + K works for opening the link dialog, but the dialog flickers.

Issues 1 and 2 are fixed by #17214.

**Comment by talldan** [comment]
The flickering no longer seems to be an issue, but it's still not possible to add links.

Visually a few more issues have become apparent with the toolbar:
<img width="664" alt="Screenshot 2020-04-22 at 4 51 10 pm" src="https://user-images.githubusercontent.com/677833/79961756-be9d0880-84b9-11ea-9516-97f589683e37.png">

And also I sometimes see this 😱 :
<img width="160" alt="Screenshot 2020-04-16 at 2 48 21 pm" src="https://user-images.githubusercontent.com/677833/79961838-d8d6e680-84b9-11ea-95b1-db270853f93c.png">

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
