### ISSUE TITLE
Feature suggestion: easy way to convert classic text to blocks

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1715]
I've been converting a few of my posts to the blocks format to test gutenberg, and the process of copying a bit of text, adding a block, pasting it, etc is getting pretty tedious. A one-click auto-convert would be great to have, but I also recognize that could do more harm than good for posts that have a lot of custom content in them.

As a first step, perhaps having a dedicated button show up in the inspector when you select a bit of text in a Classic block would be useful? Where you can convert the selection to a new, separate block. Or something like the Inserter, but which takes selected content, cuts it out, and pastes it in a new block of my chosen type.

Does that seem useful to anyone else?

**Comment by jasmussen** [comment]
Part of this is being worked on in #1331.

**Comment by hedgefield** [comment]
Ah nice, it's good to see that converting foreign content is already being worked on. I see mentions in those adjacent tickets of converting existing WP content already, so I'll close this.
