### ISSUE TITLE
Custom URLs in images without schema creates relative links

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#17155]
**Describe the bug**
The custom URLs entered in an image block are not being sanitized / validated, so entering an URL without the schema (`http(s)://`) will create a relative URL.

**To reproduce**
1. Insert an image block and upload/select an image.
1. On the block toolbar, click on "Edit link".
1. Enter an address without http:// or https:// (i.e. `wordpress.org`).
1. Publish the page/post.
1. Visit the published post/page.

**Expected behavior**
To be taken to the external website upon clicking the image, but instead you're taken to an internal path (i.e. `example.com/2019/08/23/my-post/wordpress.org`).

**Comment by paaljoachim** [comment]
Here is another Image block issue. This is probably the 3 or 4th issue in relation to the Image block.

Pinging:
@WordPress/gutenberg-core

**Comment by paaljoachim** [comment]
Hi @mmtr Miguel

This issue looks like a duplicate of this:
Button Block does not prefix a URL with `http://`
https://github.com/WordPress/gutenberg/issues/6841

The focus in the other issue is though the Buttons block. If you can leave a comment there then we can close this issue.
Thanks.

**Comment by mmtr** [comment]
@mrwweb already did that in https://github.com/WordPress/gutenberg/issues/6841#issuecomment-774337703, so we can close this one as duplicate.
