### ISSUE TITLE
Prettier with VsCode and eslint-plugin

### ISSUE THREAD

**Issue by eddysims** [WordPress/gutenberg#17150]
I am trying to use Prettier with https://www.npmjs.com/package/@wordpress/eslint-plugin and VsCode. However i am getting an error when trying to format on save.

package.json
```
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wordpress/eslint-plugin": "^2.4.0",
    "prettier-eslint": "^9.0.0",
    "prettier-eslint-cli": "^5.0.0"
  }
}
```

.eslintrc
```
{
    "extends": [ "plugin:@wordpress/eslint-plugin/recommended" ]
}
```

.vscode/settings.json
```
{
    "editor.formatOnSave": true,
    "prettier.eslintIntegration": true,
}
```

Error I'm receiving
```
Failed to load plugin 'jsx-a11y' declared in 'CLIOptions'/Users/***/***/***/src/index.js:: Cannot find module 'eslint-plugin-jsx-a11y'
Require stack:
- /__placeholder__.js
```

**Comment by talldan** [comment]
@eddysims My understanding is that `jsx-a11y` is a dependency of `@wordpress/eslint-plugin`:
https://www.npmjs.com/package/eslint-plugin-jsx-a11y

After `npm install` do you see it in your `node_modules` folder?

**Comment by eddysims** [comment]
I have run `npm install` Im sure its actaully a bug with prettier vscode plugin. running `prettier-eslint ./**.js` works. but `"prettier.eslintIntegration": true,` doesn't

**Comment by orionrush** [comment]
There could be a few things at play, depending on your setup. 

This issue on [vscode-eslint](https://github.com/microsoft/vscode-eslint/issues/696) covers a lot of people seeing this error for various reasons. Check out my comment where I try to break down the major themes. I don't know your setup, but I believe you need to define `"eslint.workingDirectories"` in your project's workspace settings. '.vscode/settings.json`.
