### ISSUE TITLE
Cog icon next to block doesn't close post settings yet

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1716]
I noticed that the cog icon next to blocks can open the Post Settings sidebar when it is hidden, but when it is already showing you can't close it again if you click the cog icon again. Since having the Post Settings open is the default, it makes it seem as if the cog button is broken/doesn't do anything.

**Comment by jasmussen** [comment]
The chief purpose is indeed to open the post settings inspector if closed, and set focus on it so you can tab there (and back) if need be. Would it be sufficient if we "flashed the borders" of the inspector when clicking the cog, if it's already open? CC: @afercia

**Comment by hedgefield** [comment]
Duplicate: #1608

**Comment by jasmussen** [comment]
Good point.
