### ISSUE TITLE
Revise method of preventing a "flash" of default inserter help panel content

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#17168]
_This is technically two bugs, but they should probably be addressed together._ 

#16813 removed [horizontal padding for inserter list items](https://github.com/WordPress/gutenberg/pull/16813/commits/af52a80f42d905f4a6e842424fea9511c977a9c1), in order to prevent a "flash" of the default block content when moving the mouse from one block to the next horizontally. This did not address the issue when moving the mouse vertically up or down the list: 

![flicker](https://user-images.githubusercontent.com/1202812/63598931-8b068900-c58e-11e9-9b43-971ef82c2686.gif)

Additionally, this padding removal introduced a regression in the focused state for those inserter list items. Turns out that padding was necessary to properly house the focus state borders: 

<img width="337" alt="Screen Shot 2019-08-23 at 10 11 13 AM" src="https://user-images.githubusercontent.com/1202812/63598879-72966e80-c58e-11e9-8a61-8d870dc60e39.png">
<img width="400" alt="Screen Shot 2019-08-23 at 10 10 54 AM" src="https://user-images.githubusercontent.com/1202812/63598881-72966e80-c58e-11e9-88f1-b2ec5939c127.png">

We should fix that regression and come up with a better way of preventing the flash. Perhaps by adding a delay to he transition between hovered items in the sidebar.

**Comment by jasmussen** [comment]
Sorry about that, github got smart with my phrasings!

**Comment by youknowriad** [comment]
Seems like this is not needed anymore.
