### ISSUE TITLE
Top Toolbar overlaps permalink options

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#17161]
**Describe the bug**
When the Top Toolbar option is enabled and the window is less than 1080px width, the post permalink options are overlapped (see screenshot).

**To reproduce**
1. Make the window less than 1080px width
2. Enable 'Top Toolbar' using the meatballs icon in the top right corner of the screen.
3. Click on the Post title
4. Observe the overlap

**Expected behavior**
No overlap

**Screenshots**
![Screen Shot 2019-08-23 at 6 09 33 pm](https://user-images.githubusercontent.com/677833/63585417-a21a9a80-c5d1-11e9-8a20-982dc999888d.png)

**Comment by dinhtungdu** [comment]
I tested this issue with the latest commit on Chrome and Firefox (macOS 10.14.6), I didn't see the overlap.

**Comment by nicholasio** [comment]
I'm also not able to reproduce this issue (Brave/Chromium)

**Comment by xibe** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/2806515/66471259-4cb82100-ea8b-11e9-8b90-172bb11c5492.png)

Firefox 69 and WP 5.3-beta3-46450.

**Comment by talldan** [comment]
I also can't reproduce the issue now, so closing this.
