### ISSUE TITLE
Gutenberg uses user's language rather than site language

### ISSUE THREAD

**Issue by bracketsberlin** [WordPress/gutenberg#17179]
Hi,

## Problem
I created a custom block and localized it. Everything works fine, except for one issue:
My account's language is DE and I'm creating posts in EN. I provided two translation files, one for de_DE and one for en_US. Everytime when I create a post and save the block, all strings e.g. `__('mehr anzeigen', 'dxtheme-blocks')` (means "show more") are displayed in German, rather than in English despite the post's language is EN (using Polylang).

I found out, that WordPress doesn't use the post's language rather than the editor account's language. Namely, if I change my account to EN, the block is created in English.

## Expected Behavior
Block's should use the post's language for localization rather than the account's language.

Am I dumb or is this the desired behavior? At least not in my case. Thanks for a short hint.

---

## Implementation
**In the plugin's php:**

```
wp_register_script(
        'click-and-ask-block',
        plugins_url( 'blocks/block-click-and-ask/block-click-and-ask.js', __FILE__ ),
        array( 'wp-blocks', 'wp-editor', 'wp-element', 'wp-components', 'wp-i18n' )
    );

    // add variables to script
    wp_localize_script( 'click-and-ask-block', 'click_and_ask',
        array(
            'pluginAssets' => plugins_url().'/dxtheme-blocks/assets'
        )
    );

    register_block_type( 'dxt/click-and-ask', array(
        'editor_script' => 'click-and-ask-block'
    ) );

    // register translations
    wp_set_script_translations( 'click-and-ask-block', 'dxtheme-blocks', plugin_dir_path( __FILE__ ) . 'languages/js-translation' );
```

**Inside JS save function:**
`el( 'span', { className: 'reveal-options' }, __('mehr anzeigen', 'dxtheme-blocks') ),`

**Language File**
`{"translation-revision-date":"2019-08-23 22:42+0200","generator":"WP-CLI\/2.3.0","source":"blocks\/block-click-and-ask\/block-click-and-ask.js","domain":"messages","locale_data":{"messages":{"":{"domain":"messages","lang":"en_US","plural-forms":"nplurals=2; plural=(n != 1);"},"mehr anzeigen":["show more"],"Mehr\/weniger Optionen anzeigen":["blabla"],"weniger anzeigen":["blabla"]}}}`

**Comment by bracketsberlin** [comment]
I found a solution. Maybe it's more of a Polylang's problem.

Problem:
On the admin pages (and so is the post.php), AJAX calls are made with the user's locale. Subsequently, the blocks are also retrieved using the user's locale. The goal was it, to change the AJAX call's locale based on Polylang's post language.

Inside my plugin-registration file, I initialized the following function and now everything works:
```
/**
 * Load plugin textdomain.
 */
add_action( 'init', 'wpdocs_load_textdomain' );
function wpdocs_load_textdomain() {
    // Correctly localize block's language
    // Problem: localized JS-files are pulled in the editor's language rather than in the site's language defined by Polylang
    // change locale temporarily to the desired post language (e.g. en_US)
    // to circumvent the ajax calls pull everything in the user's language (e.g. de_DE)

    // only do this on post.php
    global $pagenow;

    if ( $pagenow === 'post.php' ) {
        // retrieve post/page's ID
        $locale = pll_get_post_language( $_GET['post'], 'locale' );

        // set desired locale
        add_filter('determine_locale', function () use ( $locale ) {
            return $locale;
        });
    }

    // localize plugin
    load_plugin_textdomain( 'dxtheme-blocks', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}
```

Please note, that blocks must be – still – localized with a valid JSON file in the desired language as stated here: https://developer.wordpress.org/block-editor/developers/internationalization/

**Comment by thiagolcks** [comment]
I'm having the same issue, but not using Polylang. The website is in Portuguese and the user's setting is English, the block is being displayed in English for the users. I'll try the @bracketsberlin solution, but it seems like a bug to me. Or maybe I'm using the wrong approach.

**Comment by mindaugasbudreika** [comment]
@thiagolcks Have you found solution?
