### ISSUE TITLE
Always Show Block Labels

### ISSUE THREAD

**Issue by seanbrightly** [WordPress/gutenberg#17170]
I'm trying to make it more clear the user what block they have selected. I'd like to find a way to always show the small block labels. They appear to use the aria-label attribute.

I'm using ACF and it's just a little hard when there are a lot of custom blocks on the page to tell what is what.

![image](https://user-images.githubusercontent.com/53917538/63602454-7c6fa000-c595-11e9-8ec5-b4135eeb6238.png)

**Comment by youknowriad** [comment]
Hi There! Gutenberg needs to keep a balance between being an editor to write text and an editor to build pages. For the first one, it doesn't really make sense to keep the labels visible.

For this, I think we should close this issue. Using the `editor.BlockEdit` filter, you can potentially render the label on your own for each block.

Thanks for your understanding.
