### ISSUE TITLE
Pasting From Word MS Fails

### ISSUE THREAD

**Issue by OIITCONZ** [WordPress/gutenberg#17176]
**Describe the bug**
When pasting content from MS Word Gutenberg fails to preserve any form of formatting.

**To reproduce**
Steps to reproduce the behaviour:
1. Add a new page / post in WordPress
2. Copy content from Word
3. Paste into the new page / post
4. Text with no formatting of any type appears.

I've looked for WORD / MSWord blocks. None in Gutenberg

**Expected behavior**
I would expect content to paste and keep formatting. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 
 - Version 68.0.2

**Additional context**
- Wordpress 5.2.2.  
- All plug ins up todate
- 2019 Theme - Vanilla with no changes
- Classic Editor Plug in is turned off for testing

Blow by blow seen here: https://th.web.kiwi.nz/pasting-from-word-to-gutenberg-is-broken/

AS seen in Gutenberg
![in-gutenberg-doc](https://user-images.githubusercontent.com/54460321/63630778-b2368680-c672-11e9-9d27-9f670420c7ce.jpg)

As seen when pasted into classic editor
![in-classic-doc](https://user-images.githubusercontent.com/54460321/63630779-b498e080-c672-11e9-8f50-e5267e40b6fd.jpg)

As seen in Word (what was copied from
![in-word-doc-redacted](https://user-images.githubusercontent.com/54460321/63630873-91bafc00-c673-11e9-80dc-e338d1cb6d7a.jpg)

Plug ins loaded in WordPress. Tried it with Classic Disabled

![Plugins ‹ Theology House — WordPress-682](https://user-images.githubusercontent.com/54460321/63630816-f0cc4100-c672-11e9-802c-0789786cbe1a.png)

**Comment by ellatrix** [comment]
Hi @OIITCONZ! Thanks for the report.

Could you share what the console is logging for you when you paste?

I'm looking for this:

<img width="657" alt="Screenshot 2019-08-07 at 10 53 18" src="https://user-images.githubusercontent.com/4710635/62609234-ac664480-b901-11e9-972a-7383ec88b930.png">

Please copy the text and paste it in between backticks:
````
```
content
```
````

Thank you!

**Comment by noisysocks** [comment]
Closing this out for now as the issue can't be reproduced without more info. @OIITCONZ, if you're able to share the debugging information printed in the console, as above, we can re-open the issue.
