### ISSUE TITLE
Visual queues for Edit and Navigation Mode

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#17184]
**Is your feature request related to a problem? Please describe.**
Recently while using the editor I've been thinking about the new Edit and Navigation mode (https://github.com/WordPress/gutenberg/pull/16500), and what it's like for users using the editor for the first time. 

What does it mean when my block is highlighted with a blue border? My feeling is that it's ok if you're a mouse user, clicking on the block allows you to edit it. 

If you're someone who primarily uses only the keyboard (as I quite often do), then I'm concerned that it might not be clear why nothing happens when attempting to type in a block in nav mode.

**Describe the solution you'd like**
One way to remedy this could be using tips. I think first and foremost, if a user finds themselves in navigation mode, it'd be great to show some kind of tip that tells them how to get back into edit mode.

Here's a little example of what this could look like to get the ball rolling:
![Screen Shot 2019-08-26 at 1 14 43 pm](https://user-images.githubusercontent.com/677833/63666720-a928ef00-c803-11e9-8cd8-e437f8a2768e.png)

If this seems too noisy, one option could be that the tip only appears if the user tries typing.

**Describe alternatives you've considered**
Perhaps typing should switch back into edit mode? This would rule out my other idea - https://github.com/WordPress/gutenberg/issues/17185

**Comment by karmatosed** [comment]
That's actually a pretty valid query, it does look like it becomes an input. I wonder what it would feel like but that of makes sense. Focus, then edit.

**Comment by ibdz** [comment]
In [design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1582650502035100) in slack, we agreed some kind of cue is needed. Finding a general way to enable tips/help mode similar to Gmail for compact/expanded display or another way might help.

**Comment by mapk** [comment]
We need some design work here to figure this out.

- Is this a snackbar notification? What wording will be used?
- @paaljoachim mentioned just dropping the user into Edit mode when they start typing. How does that feel?

**Comment by paaljoachim** [comment]
Today Select Mode changes to the Edit Mode on double clicking a block.
Select Mode could also change to Edit Mode when the user begins to write. As it gives a signal that the user wants to interact with the block.

**Comment by mapk** [comment]
> If you're someone who primarily uses only the keyboard (as I quite often do), then I'm concerned that it might not be clear why nothing happens when attempting to type in a block in nav mode.

@talldan, is the process of selecting to enter Select mode enough of an indicator as to why the blocks are now blue?

**Comment by talldan** [comment]
@mapk It's also triggered using the Escape key, which is something that is often reflexively pressed. Once Escape is pressed there's not much indication of what the change in mode means.

> @paaljoachim mentioned just dropping the user into Edit mode when they start typing. How does that feel?

I think it could be worth trying something along those lines.

**Comment by mapk** [comment]
Another option is when entering the Select mode using the `Esc` key display a snackbar notification, and vice-versa.

**When using the Esc key to enter Select mode**

![snackbar](https://user-images.githubusercontent.com/617986/87714522-bbd04d80-c760-11ea-90f4-ffa9a26888db.png)

**When using the Enter key to enter Edit mode**

![snackbar2](https://user-images.githubusercontent.com/617986/87714698-0225ac80-c761-11ea-86c9-0689d7ea6dc8.png)

**Comment by paaljoachim** [comment]
I see there has been no movement here for a while.
@jasmussen Joen I thinking you might want to also give some feedback here?

**Comment by jasmussen** [comment]
The snackbar to indicate tool shift seems fine to try, but I'd massage the text if we can:

- While it's technically a mode shift, so is it a mode shift when you choose the marquee tool in Photoshop, and the term "mode" seems technical and unhelpful as there's nothing intrinsic about that word that explains what's going on. 
- To go back to editing text, you can also click again on a block already selected. Or you can choose the tool from the toolbar. 
- Since editing is default and in use most of the time, we can probably keep that phrase simpler. 

I'd welcome copy suggestions, but here's a quick stab:

1. Now selecting blocks. Click twice or press Enter to edit.
2. Now editing text.

**Comment by hedgefield** [comment]
The snackbar still feels a little ephemeral, but it's a good improvement over what we have now, so I'd vote for trying this out too. I also like the idea of automatically switching based on certain inputs.

**Comment by talldan** [comment]
Closing this as stale. The issue is fairly old and never gained any clear direction.
