### ISSUE TITLE
Iterate on design to add option to select the style for default on block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17189]
There is now an option to select a style by default:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/253067/63687816-81368d00-c7fd-11e9-8b24-6dd1bf5861ce.png">

I wonder if changing this to be a checkbox like we use for galleries could be an option?

<img width="325" alt="Frame" src="https://user-images.githubusercontent.com/253067/63687832-8abff500-c7fd-11e9-80de-fc65b0353569.png">

**Comment by richtabor** [comment]
I'm not sure if a default state is really necessary honestly - as the default style is stated in the select. 🤷‍♂️

<img width="316" alt="Screen Shot 2019-10-02 at 5 41 03 PM" src="https://user-images.githubusercontent.com/1813435/66084107-d15ee880-e53b-11e9-8063-03a0d83b3bff.png">

**Comment by paaljoachim** [comment]
I agree with Rich that. It seems pretty clear as it is.

**Comment by enriquesanchez** [comment]
[This issue was discussed](https://wordpress.slack.com/archives/C02S78ZAL/p1586276011309100) during the Design team's Gutenberg triage meeting ([requires registration](https://make.wordpress.org/chat/)).

We agreed that this is unnecessary given that the default style is indicated in the dropdown.
