### ISSUE TITLE
Navigation Mode and Keyboard Shortcuts

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#17185]
**Is your feature request related to a problem? Please describe.**
Previously, contributors to the project have had a torrid time implementing block keyboard shortcuts. The issues are:

- Keyboard shortcuts cannot involve a printable character, as the user's key interaction is primarily typing text
- Keyboard shortcuts cannot clash with browser, accessibility tools and os shortcuts
- Keyboard shortcuts need to be memorable and related to the action

After going through these steps to identify an appropriate shortcut for a feature it often turns out there are no decent candidates.

**Describe the solution you'd like**
Navigation mode seems like an opportunity. With the way it works now it eliminates this rule:

> Keyboard shortcuts cannot involve a printable character, as the user's key interaction is primarily typing text

This opens up many opportunities. Some ideas for shortcuts that only exist in nav mode:
- Holding Cmd and using arrow keys moves blocks
- Shift and arrow keys multi-select blocks
- `G` groups blocks
- `D` duplicates blocks
- Numerical keys focus sidebar panels

**Comment by shaunandrews** [comment]
Not sure there's much here for design _right now_, but I agree that while in Select mode we could open up to allow more keyboard commands.
