### ISSUE TITLE
Custom dropdown, tooltip hidden

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#17191]
**Describe the bug**
I am building a custom dropdown that I have added to the top toolbar. This dropdown has a label. However, whenever I hover over the icon for the dropdown, the tooltip is covered by the admin bar. 

**To reproduce**
1. Register custom dropdown in toolbar
1. Hover over icon. 
1. See tooltip not displaying

**Expected behavior**
Tool tip displays

**Screenshots**
![Screenshot from 2019-08-26 13-00-10](https://user-images.githubusercontent.com/237508/63689807-dde87680-c802-11e9-8d94-c6c81a3a1ef9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome / Firefox
 - Version Version 76.0.3809.100 (Official Build) (64-bit) / 68

**Comment by nfmohit-wpmudev** [comment]
Hi!

You can add the `tooltipPosition="bottom"` prop on a `Button` component to make it show below. [Here's an example](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inserter/index.js#L44).

Hope this helps. Closing this now.
