### ISSUE TITLE
Header Block + Move blocks before the "Page Title" and other possibilities

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17190]
Creating custom blocks is awesome with the new block editor. 

BUT, are there any considerations for the following?

> What can we do, if we want to add a custom "Header", which appears above the "Entry Page Title" and the **possibility to edit the "Header" like a block inside the block editor**?

### Which conditions must be fulfilled in the example for a header block?

> 1. Always the first position of the block.

--> The block should be positioned **above** the "Entry Page Title".

> 2. Restricting the multiple use of blocks.

--> The block should **only be used once** without the option to "duplicate" it or add it several times.

> 3. Restricting the moving of blocks.

--> The header block should **not be movable**.

### What will the future bring?

Is there a plan about this point in the future?

It would make the editor even better.

**Comment by CreativeDive** [comment]
This is only an example for a full page header, which is overlaid from the site logo and the site navigation.

![header](https://user-images.githubusercontent.com/31563167/63689997-d5e10480-c80b-11e9-8bc0-08572dc4c83b.jpg)

At this time there is no possibility to add custom headers like this in a user friendly way inside the block editor.

**Comment by swissspidy** [comment]
There are plans to support this, for example by making the title field an actual block that can be moved.

You can follow #11553 for any progress on this.
