### ISSUE TITLE
Refine front-end styles

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1720]
This is a meta issue to ensure that the front-end looks like the back-end, which includes refine all markup.

This is separate from #1315, in that it deals largely with the blocks we have and how they render out of the box. 

Related:

- https://github.com/WordPress/gutenberg/issues/1642
- https://github.com/WordPress/gutenberg/issues/1417
- https://github.com/WordPress/gutenberg/issues/801

**Comment by mtias** [comment]
Closing as it's a bit vague. If we have concerns with individual blocks or markup implementations, we should create specific issues. We will do a review of all blocks in any case at various points leading to eventual core merge.
