### ISSUE TITLE
Incorrect type definition for WPNoticeAction and missing docs for type option for notices

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#17203]
* Notices support a `type` property which isn't documented yet. The default value is `'default'` but can also be `'snackbar'`. Should be documented in
  * https://github.com/WordPress/gutenberg/blob/5920ab8620e0a5ea6ed810e399dc42fd94d99abd/packages/notices/src/store/selectors.js#L17-L34
  * https://github.com/WordPress/gutenberg/blob/495608246d3ccdc8e3ff3271eee94d51474acb7e/packages/notices/src/store/actions.js#L11-L33
* For `WPNoticeAction`, [`callback`](https://github.com/WordPress/gutenberg/blob/5920ab8620e0a5ea6ed810e399dc42fd94d99abd/packages/notices/src/store/selectors.js#L42-L43) should be `onClick`, see https://github.com/WordPress/gutenberg/blob/master/packages/components/src/snackbar/index.js#L55-L63.

**Comment by simono** [comment]
@ocean90 I've tried to fix this in #17206. What do you think?
