### ISSUE TITLE
Inconsistencies in the Edit Media Toolbar Icon

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#17219]
The icon to edit the image or video is different between different core blocks. For example the image block already has the new SVG icon, while the Video, Media-Text & Cover blocks still use the "Edit" dashicon.

I would suggest unifying these Icons to the new Icon first implemented in the Image Block to make it more clear how that action works. No matter which block you are using. The "Edit" dashicon is more general and can / will be useful to have for other operations in the future.

**Comment by Soean** [comment]
We use the `MediaReplaceFlow` component in all media related blocks now.
