### ISSUE TITLE
Allow anchor links to have user defined title attribute

### ISSUE THREAD

**Issue by acal** [WordPress/gutenberg#17212]
I would find it very useful if the anchor tags could have the title attribute available. Perhaps within the same sub-UI that you can already select if the link opens in a new tab or not? I frequently like to have this as users can hover over the link and see more detail prior to clicking.

I searched for this feature but did not find it elsewhere. Sorry, in advance if it is a duplicate.

**Comment by skorasaurus** [comment]
Thanks for your suggestion but it's strongly discouraged to use the title attribute in links. 

Information about why not to use them is at https://github.com/WordPress/gutenberg/issues/20198
