### ISSUE TITLE
Inserter: Better handle long block titles. 

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1721]
![2017-07-05t13 13 53_0200](https://user-images.githubusercontent.com/1204802/27862351-12f421e4-6185-11e7-91ba-ac2b6f360809.png)

Two ways to solve this. 

1. ellipsis trim the text (or use longfade mixin)
2. move to 1 column for the inserter. See also https://github.com/WordPress/gutenberg/issues/1497

**Comment by dinhtungdu** [comment]
Hi, I'm new to Gutenberg :).

I think that having a long block title is very natural. Sometime we can not have a meaningful title in one or two words. This is my approach: align icon to top and align text left. We just need some change with styling. 
![](https://image.prntscr.com/image/wyOecTKhS_eC-x5lwa-kXQ.png)

**Comment by mtias** [comment]
The new inserter should handle this better.
