### ISSUE TITLE
Post format needs to be a selector

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1722]
Right now we infer post formats. If you have multiple blocks, you get the standard post format:

<img width="305" alt="screen shot 2017-07-05 at 13 30 36" src="https://user-images.githubusercontent.com/1204802/27862584-3aa67bd2-6186-11e7-8e09-80c6ad91a34f.png">

If you have only an image, you get an image post format:

<img width="302" alt="screen shot 2017-07-05 at 13 30 52" src="https://user-images.githubusercontent.com/1204802/27862589-4251b374-6186-11e7-87f8-f61ab1e4dfba.png">

This is cool, but you also need to explicitly be able to choose it yourself. So it should be a dropdown or selector interface like the visibility one.

**Comment by swissspidy** [comment]
That's a lot of status & visibility options already. Can we perhaps make this more compact during that process? For example, why is "Pending review" so prominent?

**Comment by jasmussen** [comment]
> That's a lot of status & visibility options already. Can we perhaps make this more compact during that process? For example, why is "Pending review" so prominent?

I think that's a fair question, but it's probably worth tacking separately from this issues. I know we have a lot of issues, but it feels like we're in a phase where it's good to keep the issues as atomic and specific as we can.

**Comment by JoshuaMckendall** [comment]
Will you make it possible to keep the post format even when the user decides to add extra blocks to that post? For example, a user chooses the video post format, and a default video block is provided.  The user wants to add another text block as a description of the featured video while retaining the style / structure of that format (doesn't revert back to standard).

![video_post_format_selector](https://user-images.githubusercontent.com/7562755/27926929-b672ba86-624f-11e7-9915-5cccac927fed.png)


![video_post_format_selector_selected](https://user-images.githubusercontent.com/7562755/27926933-b9cd793c-624f-11e7-865e-9664d1d92222.png)

**Comment by jasmussen** [comment]
Yes! That would be the primary reason for making it a selector.

**Comment by youknowriad** [comment]
There's a small problem we need to figure out to solve this. When do we decide that the suggested post format is not a suggestion anymore and should be saved? Is this on the first "save" (and auto-save) call?

Seems too short and also if we change the content, add a block etc... the post format won't change anymore.

**Comment by jasmussen** [comment]
Really great question.

The only good answer I can think of, is that the post format isn't finalized until you _publish_, or explicitly set it yourself. That last part is probably difficult, but it seems like the most predictable behavior to me.

**Comment by youknowriad** [comment]
Actually, the second part is impossible, because we can't save a "null" value, we can't make a difference between a "standard' post format and an explicitly set "standard" post format. 

Maybe the suggestion could be just an information shown next to the selector?

**Comment by jasmussen** [comment]
> Actually, the second part is impossible, because we can't save a "null" value, we can't make a difference between a "standard' post format and an explicitly set "standard" post format.

So one approach is that you _can't_ select the post format. It's automatically set based on what we infer, and if it changes as you author, tough beans. This seems heavy handed, and that we're not quite ready to do this.

Can we save a "user choice" token, in addition to the actual post format? And if set to true, then we stop inferring/overriding this choice?

So let's say we save "post_format" and "post_format_user_set" when saving. In a new post where you insert a quote, we'd have: **post_format = quote, post_format_user_set = false**.

Then you go and click the selector, choose "Standard", and now we save this: **post_format = standard, post_format_user_set = true**.

In the first case, we keep inferring and overriding. In the second, we stop overriding and inferring. 

Doable? CC: @mtias

**Comment by youknowriad** [comment]
> Can we save a "user choice" token, in addition to the actual post format? And if set to true, then we stop inferring/overriding this choice?

I believe we could use a "meta" field for this but I'm not sure if it's suited for this. Can't see any other way to store Post Related Custom Data using the REST API.

**Comment by paaljoachim** [comment]
I really think that Post Format should just be removed. I think it will just confuse the user. As it is just one more thing the user will need to have an opinion on.

**Comment by jasmussen** [comment]
Per a discussion yesterday, I promised I'd ask the Android devs how they infer post format in the app. Turns out they don't. I just always use the app to post images, and at some point I set my _default post format_ to Image. 

Perhaps we should go with the suggestion for now:

```
Suggested post format: [link]Image[link]    [Standard ▼]
```

That is, click the "Image" link and the dropdown is set to image. But otherwise we do nothing.

**Comment by paaljoachim** [comment]
As I am posting directly in the pull request https://github.com/WordPress/gutenberg/pull/2307 I thought I might as well continue here...

Is it possible to have post format hidden and if one needs post formats one can add a code snippet to have the post format panel visible?

If one is converting a post made outside of Gutenberg, and that post uses a non standard format, what about showing the post formats panel so the user can if they decide then go in and adjust it?
