### ISSUE TITLE
disabled components CSS pointer events

### ISSUE THREAD

**Issue by mmaarten** [WordPress/gutenberg#17223]
**Describe the bug**

I am creating some blocks with Twitter Bootstrap components inside.
A noticed that the [stretched links](https://getbootstrap.com/docs/4.3/utilities/stretched-link/) have a `pointer-events: auto;` on the `::after` pseudo-element.

this makes that the link is still clickable.

**Expected behavior**
Following should fix this.
`.components-disabled *,
    .components-disabled *::before,
    .components-disabled *::after {
      pointer-events: none;
    }`

Kind regards

**Comment by talldan** [comment]
Thanks for pointing this out @mmaarten. Would this be a fix you might be willing to contribute in a pull-request?

**Comment by afercia** [comment]
Noting there's a pending PR to improve the `Disabled` component. See https://github.com/WordPress/gutenberg/pull/17064

On links, it will disable them by removing the `href` attribute. To  my understanding, this should work also with the "stretched links" `::after` pseudo-element.

**Comment by mmaarten** [comment]
ok. Thank you guys.
