### ISSUE TITLE
Button Block: Only display buttons if the title attribute exists 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#17221]
**Describe the bug**
Currently, a Button block without a `title` attribute still renders an empty button via the save function, leaving an empty `<a>` on the page. 

**To reproduce**
1. Add an empty Button block
2. Publish the page
3. View the published page

**Expected behavior**
A button is not rendered unless the `title` attribute is entered, preventing empty buttons from displaying if it's not intentionally configured within the editor.

**Screenshots**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/63803293-721d1100-c8c9-11e9-9d19-4f223c6b0d16.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 12.1.1

**Additional context**
Using Gutenberg 6.3, although it happens regardless of whether or not the plugin is active.

**Comment by bobbingwide** [comment]
Problem still occurs when you add a new button to the buttons block with Gutenberg 7.2.0

**Comment by dgaik-gg** [comment]
What for example with arrow buttons where the arrow is added using a class and text is not necessary? Currently adding a space allows this button to be rendered but this is not a good way.

**Comment by getsource** [comment]
Hi @dgaik-gg!

Thanks much for the note about this!
Would you mind opening [a new issue](https://github.com/WordPress/gutenberg/issues/new/choose), to open discussion about the best way to address this?
