### ISSUE TITLE
Prohibit block insertion before and / or after a block

### ISSUE THREAD

**Issue by anUserFr** [WordPress/gutenberg#17238]
I've already looked at template_lock, but it's too restrictive (only all and insert). I make a wordpress template. I have a lot of templates. For all templates, I have to forbid insertion before the template. Regarding insertion after, it depends on the template...

**Comment by talldan** [comment]
@anUserFr I think this existing issue seems to promote similar ideas, so I think the best thing to do is to close this issue and add your suggestion to that one:
https://github.com/WordPress/gutenberg/issues/8112
