### ISSUE TITLE
How to document for different platforms

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#17230]
We're increasing the code we share between mobile and web, so we need to figure out ways to automatically document what belongs to each platform.

Reference: ([core-js slack conversation](https://wordpress.slack.com/archives/C5UNMSU4R/p1566914617419700)).

- In consolidating some components to work for on web and mobile (ReactDOM and React Native) we have the need to mark some props to belong only in a specific platform ([example](https://github.com/WordPress/gutenberg/pull/17145#discussion_r317196982), `className` is another web-only prop).
- We also likely need to mark some to work on Android or iOS.
- There might be props that are required in one platform but not in another. Pending use case.
- Event handlers are a bit more nuanced. We're aiming to have the same API, but some cases may need to be declared per-platform (for ex: `onError`). 

Some examples:

- ReactNative's RefreshControl ([code](https://github.com/facebook/react-native/blob/91f139b94118fe8db29728ea8ad855fc4a13f743/Libraries/Components/RefreshControl/RefreshControl.js#L76), [docs](https://facebook.github.io/react-native/docs/refreshcontrol#colors)). It looks like they generate the docs from source.
- IonicFramework [docs](https://ionicframework.com/docs/utilities/platform#platforms).
- [Apple Developer Documentation](https://developer.apple.com/documentation/).

**Comment by hypest** [comment]
FYI, added this to the "Mobile Apps" project board to cover the apps side of the issue.

**Comment by oandregal** [comment]
docgen has been in use for a few years now and this hasn't been an issue. We can reopen if it becomes one.
