### ISSUE TITLE
InnerBlocks in nested 'save' functions causes validation issues

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#17231]
When making the Navigation Block dynamic we found a limitation in saving nested inner blocks. In our specific case, a menu item can contain other menu items and this is achieved using `<InnerBlocks />` and `<InnerBlocks.Content />`.

The problem is that when nested blocks are saved in such a way that the result varies depending on number of items and nesting levels, such as a nested list of navigation menus, the block gets falsely invalidated.

In our menu item block we used this snippet to avoid rendering an empty UL if there is nothing nested:

```
export default function save( { attributes, innerBlocks } ) {
[ ... ]
return (
[ ... ]
{ ( innerBlocks.length > 0 ) && <ul>
	<InnerBlocks.Content />
</ul> }
```
When this code was used the result was that at every reload of the post the Navigation Block got invalidated with some empty `<ul></ul>` for nested items.

@noisysocks investigated and found that the problem is  because block validation doesn’t consider inner blocks at all. Block validation, which is the call to `isValidBlockContent` in `packages/blocks/src/api/parser.js:createBlockWithFallback`, doesn't even pass innerBlocks to `isValidBlockContent`.

Rob worked on a quick fix that can be previewed by applying [the diff in this gist](https://gist.github.com/noisysocks/f103fb7c8978ccd032cc77972142922d) but the thing it fixes should be considered for wider implications.

All in all, as long as the InnerBlock mechanism is getting wider usage we should be able to build nested structure of indeterminate depth and access all the needed information at any point in a block's lifecycle.

**Comment by noisysocks** [comment]
Right now a Navigation block appears in `post_content` like so:

```html
<!-- wp:navigation-menu -->
	<!-- wp:navigation-menu-item {"label":"Amsterdam"} /-->
	<!-- wp:navigation-menu-item {"label":"Berlin"} -->
		<!-- wp:navigation-menu-item {"label":"Barcelona"} /-->
		<!-- wp:navigation-menu-item {"label":"Brussels"} /-->
	<!-- /wp:navigation-menu-item -->
	<!-- wp:navigation-menu-item {"label":"Copenhagen"} /-->
<!-- /wp:navigation-menu -->
```

Because it's completely dynamic, the block will not appear at all in some contexts e.g. email clients and RSS readers. This might be fine if the intention is that this block is more for site layout than it is for posts and pages, but it's a point worth considering. 

cc. @mtias

**Comment by mtias** [comment]
> This might be fine if the intention is that this block is more for site layout than it is for posts and pages, but it's a point worth considering.

Yes, this was the design decision included in the "make the block dynamic". I think it's still worthwhile to discuss what a fallback could be — a link to a sitemap, a link to the home of the site, etc.

**Comment by mtias** [comment]
Is there anything actionable here @draganescu ?

**Comment by draganescu** [comment]
Yes there is. The original issue was that `InnerBlocks` when used in save functions to create infinitely nested structures caused block validation issues. In the meantime `Navigation` got dynamic so it is not affected by this, but I believe the issue still remains.

**Comment by mtias** [comment]
Thanks for renaming the issue.

**Comment by tellthemachines** [comment]
Is this issue still valid? I can't reproduce it, and from the conversation above it seems to no longer apply to the Navigation block. If it's still an issue for other blocks, it would be great to add specific steps for reproduction in the description, and remove it from the Navigation tracking issue.

**Comment by draganescu** [comment]
Removed it from the Navigation block project and tracking issue but did not test with another block.

**Comment by draganescu** [comment]
Closing for lack of more info.

**Comment by AlexanderBorysenko** [comment]
I've faced such problem) I've been thinking about that for 3 days and found solution!)
May be it is not the best approach but it works =>

add innerBlocksData attribute to your Block

then inside EDIT function
`
Edit({ setAttributes, clientId })=>{

        const innerBlocks =
		select('core/editor').getBlocksByClientId(clientId)[0].innerBlocks;

	useEffect(() => {
		setAttributes({ innerBlocksData: innerBlocks });

	}, [innerBlocks]);
}
`

and than we can access it inside save function!)
