### ISSUE TITLE
Image: add_theme_support for wide and full alignments

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1724]
The new alignment toolbar adds two more options for image, wide and full:

<img width="187" alt="screen shot 2017-07-05 at 13 51 31" src="https://user-images.githubusercontent.com/1204802/27863151-14736184-6189-11e7-844b-7953d0ef6159.png">

An image block with the wide option applied gets the CSS classes `alignwide wp-block-image`, while an image with the full option applied gets `alignfull wp-block-image`. But the theme itself may not have the required CSS styles to support these, and it's difficult for the block itself to provide these styles inline, as they require some architecting of the theme itself, in order to work well.

We should let themes opt in to these buttons by delaring something like `add_theme_support( 'wide-images' );`, and the buttons should be hidden unless the theme has opted in.

**Comment by davidakennedy** [comment]
This makes sense to me. It's along the lines of what we talked about in a group discussion among the Theme Team at Automattic.
