### ISSUE TITLE
Cannot switch from Password Protected to Public within Post visibility

### ISSUE THREAD

**Issue by dariaknl** [WordPress/gutenberg#17247]
**Describe the bug**
Setting Post visibility to Public from Password Protected does not work if you have your password filled in. The issue found on master branch f9a342a

**To reproduce**
1. Go to create post.
2. Protect your post with password:
<img width="286" alt="Screenshot 2019-08-29 at 09 06 27" src="https://user-images.githubusercontent.com/19681708/63918453-05c31e80-ca3d-11e9-9f43-5c1e94674ab8.png">

3. Publish your post.
4. Go to edit post once again, open Post visibility configuration. Try to click Public toggle - nothing happens:
<img width="337" alt="Screenshot 2019-08-29 at 09 07 02" src="https://user-images.githubusercontent.com/19681708/63918621-55094f00-ca3d-11e9-9870-367762a5e87b.png">

5. Empty password field, and click Public toggle, now it is selected:
<img width="286" alt="Screenshot 2019-08-29 at 09 07 57" src="https://user-images.githubusercontent.com/19681708/63918669-694d4c00-ca3d-11e9-8dfe-7746d6f0ca03.png">

**Expected behavior**
I expect that I can switch to Public without emptying the password.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome

**Comment by talldan** [comment]
Thanks for submitting the bug. I can confirm it. Seems related to https://github.com/WordPress/gutenberg/pull/17210 (cc: @epiqueras).

I think `null` must have been used to clear the password. But does cause the side effect of the post always needing to be updated.

**Comment by epiqueras** [comment]
Yeah, the empty string worked: #17257.

**Comment by dariaknl** [comment]
Yes, tested, the issue is fixed!
