### ISSUE TITLE
Image, Gallery: Improve "Edit Image" flow if we can

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1725]
WordPress comes with a nice built in image editing tool. Right now you can access it by first clicking the edit button on an image:

<img width="297" alt="screen shot 2017-07-05 at 13 59 27" src="https://user-images.githubusercontent.com/1204802/27863383-319fadfc-618a-11e7-9f10-1f372fa1bd5a.png">

then click the little "Edit Image" link:

<img width="272" alt="screen shot 2017-07-05 at 13 58 48" src="https://user-images.githubusercontent.com/1204802/27863389-377012b2-618a-11e7-8787-3e904859177d.png">

Clicking this, though, opens in a new window, with a URL of something like `/wp-admin/post.php?post=40&action=edit&image-editor`. 

Is there a simple/quick way we can improve this flow as an interim solution to something even better?

**Comment by jasmussen** [comment]
If you edit an inserted image in the old editor, you get this interface:

<img width="1103" alt="screen shot 2017-07-05 at 14 06 17" src="https://user-images.githubusercontent.com/1204802/27863605-3459301c-618b-11e7-90ca-6146254f1b26.png">

<img width="1107" alt="screen shot 2017-07-05 at 14 06 29" src="https://user-images.githubusercontent.com/1204802/27863608-35ebc9c6-618b-11e7-9ed5-a8f10bb9a0b1.png">

It would be nice if we could utilize this style here.

**Comment by karmatosed** [comment]
As reported also in #2075, something needs to be done to fix the broken flow we have right now. For now, marking this as a higher priority and for 0.8.

**Comment by nic-bertino** [comment]
Something to react to on this, but it may be worth prototyping and testing.

![image inserter](https://user-images.githubusercontent.com/883093/29087570-3c7046ae-7c2b-11e7-8408-d2b9e0c53556.png)

**Comment by karmatosed** [comment]
I did a couple of explorations to show how we could go here.

First up, the 'easy win'. This simply makes sure if you were in Gutenberg that the link after edited goes back to Gutenberg:

![01](https://user-images.githubusercontent.com/253067/31023471-d47f0a1c-a533-11e7-9903-6f26e9db7236.png)

The next option takes everything that currently happens in editing 'into Gutenberg. This does not change or adjust anything. For what it's worth that editing screen I feel needs some work (outside Gutenberg), however we need to be cautious dropping anything and going down that rabbit hole yet. For now, putting everything in seems a fair middle ground if we go this route:

![02](https://user-images.githubusercontent.com/253067/31023526-02cc49de-a534-11e7-9bed-d242500eb01a.png)

**Comment by jasmussen** [comment]
I think your suggestions sound pragmatic, Tammie. Agree that media as a whole needs an iteration of its own, perhaps even a focus, so we should probably focus on quick wins there.

**Comment by karmatosed** [comment]
> Agree that media as a whole needs an iteration of its own, perhaps even a focus, so we should probably focus on quick wins there.

@jasmussen absolutely. This is slightly my concern by putting it into the small screen, although we totally should explore if that's possible.

@mtias what do you think? My thinking is we could get the low hanging option in, then maybe also evaluate the 'everything in Gutenberg' option for editing.

**Comment by jasmussen** [comment]
Will this improve automatically now that Gutenberg when the plugin is activated sets itself as the default editor? @karmatosed

**Comment by karmatosed** [comment]
Unfortunately the pitfall of a new tab opening and then having no way back - unless I remember or notice it's a new tab - on editing, is still there @jasmussen. We should cover that trap for users.

**Comment by karmatosed** [comment]
Confirming that right now we have a new tab. We could add a link to say 'back to editor' that would solve some issues. However, I think taking a little bit to work on this would be sound.

**Comment by mellis32** [comment]
Why was CUSTOM not an option in the in Gutenberg image scaling dropdown?

As far as I can tell the only way to scale the way the image displays in Gutenberg is to edit the Media file directly? Frustrating.

**Comment by aaronjorbin** [comment]
I don't view this experience being any worse than what is currently in core and has been the norm for core.  So pushing it to`future`

**Comment by jasmussen** [comment]
I'm actually going to close this one, as the user interface has changed so much that what's discussed is likely not super actionable anymore. Additionally, the flow _has_ improved, with big buttons and patterns for changing an existing gallery.

With separate efforts to explore galleries leveraging child blocks, and separate improvements to the media library, all the more reason to revisit if and when it becomes necessary.
