### ISSUE TITLE
Cover Block: add "Height in pixels" to solid color

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/gutenberg#17258]
With 6.4.0, we are introducing two nice updates for the cover block:

1.  [Define a height](https://github.com/WordPress/gutenberg/issues/17113)
2. [Directly set a background color](https://github.com/WordPress/gutenberg/pull/17041)

When using a background image in the cover block, I can set a `Height in pixels`:

![Screen Shot 2019-08-29 at 13 17 11](https://user-images.githubusercontent.com/1136160/63958264-6adc3b80-ca60-11e9-9177-4d0218ae5adf.png)

This same field, however, isn’t there when I use a solid background.

For consistency, we could have the `Height in pixels` setting on both cases, either using images _or_ a plain color.

**Comment by talldan** [comment]
Had a quick peek at the code in the PR, and yes, it seems that the height input is only visible when an image is uploaded. I think the idea is that it's the height of the image.

@senadir Was wondering what your opinion on this might be—should the 'height in pixels' always be available?

I suppose one option is to use a Spacer block, but that seems like quite a bit of effort.

**Comment by senadir** [comment]
@talldan yeah for consistency min-height option should persist if you decide to remove the image, to not show height is not the intended behavior here, I will fix it today, meanwhile @eduardozulian a quick hack till next release is you set an image, define the height & remove the image, the value will persist.

Thanks for reporting!

**Comment by eduardozulian** [comment]
Awesome.

And good to know about that workaround, @senadir!
