### ISSUE TITLE
Configurable Block Features

### ISSUE THREAD

**Issue by Horttcore** [WordPress/gutenberg#17252]
**Is your feature request related to a problem? Please describe.**
Gutenberg core blocks getting more features with each release. 
As I'm developing client websites I have the need for removing some block features i.e. cover resizable feature. Authors will only mess with the content. 
This is also the same for many other blocks.

**Describe the solution you'd like**
Adding the possibility to configure block features i.e.
`remove_block_feature('core/cover', 'resizable')`

**Current solution**
At the moment I have to recreate a lot of core blocks just to strip away features, my client don't need.

**Comment by mcsf** [comment]
Cross-referencing #8352.

@mtias, @youknowriad, something for your consideration.

**Comment by gziolo** [comment]
Can we move this discussion to #15450?

**Comment by mcsf** [comment]
> Can we move this discussion to #15450?

Probably. There's symmetry with _Limit number of columns in Columns block (#12861)_

**Comment by mcsf** [comment]
Closing in favour of #15450
