### ISSUE TITLE
View jumps to top of window when editing in Microsoft Edge

### ISSUE THREAD

**Issue by Haldaug** [WordPress/gutenberg#17255]
**Describe the bug**
After installing the newest update of the Gutenberg plugin (version 6.4.0) this problem appears:

When editing text in blocks that are further down the page, the window scrolls to the top of the window.

If I disable the Gutenberg plugin and use the stock editor, the problem disappears.

**To reproduce**
1. Edit a post
2. Insert enough text so that the title scrolls out of view.
3. Edit the text by typing any character.
4. Observe that each time you press a key on the keyboard, the window scrolls to the top.

**Expected behavior**
I expect the window scroll position to stay put while I edit the text.

**Screenshots**
![typewriter](https://user-images.githubusercontent.com/3501914/63945562-d085f300-ca73-11e9-8c15-a074285942dc.gif)
Observe that the window scrolls to the top each time I type a character.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [44.17763.1.0]

**Comment by blogger912** [comment]
I am having the same issue. Only way I can type is by deactivating Guttenberg.

**Comment by dugsteen** [comment]
Same. Anyone find a workaround?

**Comment by blogger912** [comment]
One solution is to disable Gutenberg and go back to Classic Editor.  But I
am accustomed to using the blocks.  My next solution is to switch from
Microsoft Edge to Google Chrome.  I think it may be a browser issue.

**Comment by kwight** [comment]
I can confirm this issue is still valid as of 6.5.

**Comment by katiebethbrown** [comment]
Another report in #3416092-hc

> every time I type on my blog it shakes.

Edge 18.18362 on Windows 10.0.0

**Comment by mriyazuddin** [comment]
Another such issue reported here: #2392945-zen

**Comment by ellatrix** [comment]
I can reproduce the bug in Browserstack. I'll have a look into it now.

**Comment by ellatrix** [comment]
The cause is the `Typewriter` component. I'll see if it can be fixed, otherwise it could be disabled for Edge in the meantime.

**Comment by ellatrix** [comment]
The problem is that Edge does not support the `y` property on a `DOMRect`: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect and https://developer.mozilla.org/en-US/docs/Web/API/DOMRect.

**Comment by ellatrix** [comment]
I'm surprised not more stuff is broken in Edge because of this. It also doesn't seem to support the `DOMRect` constructor.

**Comment by katiebethbrown** [comment]
I just had another report of this in #15677812-hc.

`Every time I start typing in a block, it moves to the bottom of the page and I can no longer see what i'm writing`

Edge 18.17763 on Windows 10.0.0

**Comment by aliashoj** [comment]
This issue is still present on wp 5.3 and Mircosoft Edge, here. Happens on client's computer and in our office. Editing text causes the screen to jump to the top.

**Comment by vincepettit** [comment]
Two of my website authors are experiencing this in the latest release too in Edge.

**Comment by mft-dev** [comment]
Seeing this on WP 5.3 in Edge (Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362)

**Comment by ScaryDBA** [comment]
You are not alone. I can validate this same issue. First time editing a WordPress blog post with a brand new laptop.

**Comment by ellatrix** [comment]
The fix will be added to WP 5.3.1. In the meantime you could use the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/).

**Comment by akshayhallur** [comment]
The issue is still there in WP 5.4.
