### ISSUE TITLE
IE11 - Cannot use backspace to delete an empty paragraph that follows another empty paragraph

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#17266]
**Describe the bug**
When in an empty paragraph in other browsers, backspace can be used to delete it, but not in internet explorer if the paragraph is after another paragraph

**To reproduce**
1. Go through complicated process to test editor in IE11
2. Create two empty paragraph blocks
3. Try using backspace to delete the second
4. Observe that paragraph isn't removed

**Expected behavior**
Paragraph is removed

**Additional context**
- Discovered on master at 713807dee2378951678d5971ff76d4a58d39c7d0

**Comment by aduth** [comment]
This should be fixed as of #20594.

However, there's a separate issue which I've described at #20598.
