### ISSUE TITLE
Make Pending review toggle less prominent

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1726]
## Issue Overview
In the current WordPress editor, the option to mark a post as pending review is way less prominent than now in Gutenberg. All the single-author blogs out there won't need this option and don't know what it is for. Even multi-author blogs rarely use it.

## Expected Behavior

It should be more similar to the current editor meta box:

<img width="304" alt="screen shot 2017-07-05 at 14 03 15" src="https://user-images.githubusercontent.com/841956/27863571-0875285c-618b-11e7-9ecf-721e077dfbc4.png">

See also #1452.

## Current Behavior

Every possible option is listed in the settings sidebar, even if they're not used that frequently. Perhaps even more will be added. See #1722.

## Possible Solution

Use a dropdown, add an "advanced view", etc.

**Comment by jasmussen** [comment]
Matías mentioned in #1945:

> we should look again at the status area from the point of view of published/draft.

and pointed to this ticket. That's because some of the reason for the current design is that the toggles have a direct action on the status of the post. 

We should revisit this. And in that vein I'm also capturing a note from https://github.com/WordPress/gutenberg/pull/2020#issuecomment-318031577:

> I think the "Save" link actually saves the published post (and not only as a draft)

This shouldn't be the case, that would be confusing, so we should consider hiding the Save Draft button on the left if editing an already published post.

**Comment by jasmussen** [comment]
![settings](https://user-images.githubusercontent.com/1204802/29025220-ff4f12f6-7b75-11e7-871a-924cd449df63.png)

Would this improve things?

Added a "Stick to Frontpage" button, which would be nice to extract from the visibility dropdown, and reverted to having a "Status" dropdown.

**Comment by jasmussen** [comment]
CC: @mtias for ☝️

**Comment by aduth** [comment]
Per https://github.com/WordPress/gutenberg/pull/2526#issuecomment-325232901, the current editor better reflects that "Pending Review" is a distinct post status, i.e. it is not possible to save a draft while "Pending Review" is toggled, because `pending` is mutually exclusive from the `draft` status. Rather, we ought to consider "pending" like other publish statuses (publish, future, private).

**Comment by mtias** [comment]
We invested a significant amount of effort in this area in Calypso (cc @folletto), as the combinations of status, sticky, privacy, is hard to wrap your head around.

The way we went about it is that it needs to be very easy to know the state of a post. That includes emphasizing certain things (a post that is going to published in the future as a "scheduled" post, should show that clearly). The other aspect is that—conceptually—a post can be in two states: published or unpublished. Given that is not true for WP statuses, what we tried to do was to make status more contextual.

Example: if a post is published now or in the future, we show a "revert to draft" button. Pending review is only exposed if you revert to draft first.

**Comment by folletto** [comment]
For reference this is the latest design for Calypso we did (in preparation for Gutenberg), which was aimed to solve among various things the problem above too:

![screen shot 2017-08-29 at 10 44 38](https://user-images.githubusercontent.com/4389/29815040-34feaa82-8ca7-11e7-8a91-bc8150335321.png)

Notice how the post status is always included in the header, regardless of it being open or closed.

The structure is similar to the one in #1722, what's different is the order: as "Pending Review" is the least used one, it's shown at the bottom. Also relevant to notice that that approach tries to hide a little bit the limitations of the current post _status_ field, by showing the option only if the post is in draft status, thus not cluttering it once the post has been published.

**Comment by aduth** [comment]
What are the remaining tasks here? Pending toggle arrangement was deemphasized in #2592, and it was already the case that the toggle is not shown for published posts (#945). The issue of "saving draft as pending" (impossible) still exists, but seems we may not be interested in addressing this?

("Revert to Draft" and status subheading, if desired, should be separate issues)

**Comment by karmatosed** [comment]
It feels to me (maybe wrongly), we have now addressed most / all of this ticket. If that's not the case, we can of course reopen.
