### ISSUE TITLE
KSES filters force a dirty state in the editor

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#17264]
**Describe the bug**

As of Gutenberg 6.4.0, the KSES filters are making the editor to believe there are unsaved changes where there are none.

These filters are only registered when a user doesn't have the `unfiltered_html` capability (which is the case for [multisite regular admins](https://core.trac.wordpress.org/browser/tags/5.2.2/src/wp-includes/capabilities.php?marks=401,402#L401)).

When these filters are active, syntax like `<img src="..." class="..."/>` (produced by the `core/image` block) is transformed to `<img src="..." class="..." />` (note the [extra whitespace ](https://core.trac.wordpress.org/browser/tags/5.2.2/src/wp-includes/kses.php?marks=1113#L1113) at the end).

That extra whitespace is putting the editor in dirty state, but it seems that those whitespaces were ignored on Gutenberg 6.3.0 and below.

**To reproduce**
1. Activate Gutenberg 6.4.0 on a multisite install, or test with a user not having the `unfiltered_html` capability.
2. Add a new post and insert an image block.
3. Publish the post.
4. Note how the publish sidebar is automatically hidden.
5. Note how the "Update" button is enabled, despite not having entered any change.
6. Run `wp.data.select('core/editor').getEditedPostAttribute('content')` and `wp.data.select('core/editor').getCurrentPostAttribute('content')` on the browser devtools console.
7. Note how the current post content contains an extra whitespace:
<img width="1173" alt="Screen Shot 2019-08-30 at 10 40 52" src="https://user-images.githubusercontent.com/1233880/63994451-b3aef580-cb2f-11e9-9888-008ff51db7ba.png">

8. Run `wp.data.select('core/editor').isEditedPostDirty()` on the browser devtools console.
9. Note how the above command returns `true`.

**Expected behavior**
The same behavior we had in Gutenberg 6.3.0 and below:
- The publish sidebar shouldn't disappear in 4.
- The "Update" button should be disabled in 5.
- `isEditedPostDirty` should return false in 8.

**Comment by kwight** [comment]
Related: #15137.

**Comment by BennyVL** [comment]
Maybe related to #17491
