### ISSUE TITLE
Social Links Block: Add additional flex-based alignments in the Inspector

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#17275]
In #16897 a "social links" block is likely to land in its first version. 

Based on feedback for that first version, we'd like to explore some additional features. 

One of these being to allow additional flex-based button alignments in the inspector. At launch it will have left/center/right alignments, but it would be nice to have additional controls such as "space between".

Combined with a icon size control (#17276), this could allow for finegrained control.

**Comment by MaggieCabrera** [comment]
Other blocks that could use space between as an alignment would be Navigation (https://github.com/WordPress/gutenberg/issues/27132) and the buttons block too

**Comment by jasmussen** [comment]
Also potentially related, #27324 and conversations around unifying flex containers. CC: @shaunandrews

**Comment by jasmussen** [comment]
Space between has landed for social icons! 🎉
