### ISSUE TITLE
Social Links Block: Allow plugins to change the default links inserted

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#17278]
In #16897 a "social links" block is likely to land in its first version. 

Based on feedback for that first version, we'd like to explore some additional features. 

When you insert a social links block, 6 links will be inserted by default:

![Screenshot 2019-08-30 at 15 17 38](https://user-images.githubusercontent.com/1204802/64023783-5b7cf100-cb39-11e9-9f56-4ab4753ab636.png)

It would be nice to surface a simple way for plugins or themes to change what those default links are, to better tailor the experience.

**Comment by paaljoachim** [comment]
Is this issue still valid?

**Comment by jasmussen** [comment]
Excellent point! No it isn't! Because no links are inserted anymore. Thank you Paal.
