### ISSUE TITLE
Editor Full Screen Mode Issue

### ISSUE THREAD

**Issue by Nazir-zz** [WordPress/gutenberg#17270]
In Editor When Set View "Full Screen Mode" and hide Settings sidebar than there editor area is still showing small same like normal screen mode.

when i inspect code and i found there is class "wp-block" which max width is 610px ".wp-block{max-width: 610px;}" so i change its max-width 1170px though is my container width and now each block view is looking perfect.

So If Set Editor Width 90% of screen width than i thing this issue resolved.

Please check below screen shot:

![screen-1](https://user-images.githubusercontent.com/66909/64009265-2a9abd00-cb35-11e9-920c-2c6102411673.jpg)

![screen-2](https://user-images.githubusercontent.com/66909/64009206-0a6afe00-cb35-11e9-97ed-971f2a28e509.png)

**Comment by youknowriad** [comment]
Thanks for opening the issue, however, the Full-screen mode is not meant to adapt the width of the editor canvas. That's a theme responsibility. more details here https://github.com/WordPress/gutenberg/issues/16747
