### ISSUE TITLE
Social Links Block: Allow plugins to add additional logos/social links

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#17277]
In #16897 a "social links" block is likely to land in its first version. 

Based on feedback for that first version, we'd like to explore some additional features. 

At launch, the Social Links block will have a wide range of icons for most present social networks and sites to link to. 

But there will always be some network, service, or tool that the block does not link to, but which the block does not contain. It would be good to explore how to add a simple way for plugins or themes to register new child blocks, so that the core list of blocks can remain relatively slim for maintenance purposes, but still allow flexibility for themers and developers.

**Comment by mcsf** [comment]
If/once #19887, this becomes automatically possible thanks to the Variations API:

```js
wp.blocks.__experimentalRegisterBlockVariation('core/social-link', {
    name: 'latin-wikipedia',
    title: 'Vicipædia',
    icon: 'smiley',
    attributes: {
        site: 'latin-wikipedia',
        url: 'https://la.wikipedia.org/',
    }
});
```

<img width="587" alt="Captura de ecrã 2020-02-05, às 13 36 15" src="https://user-images.githubusercontent.com/150562/73846568-a4d61880-481c-11ea-87c1-70457342bc07.png">
<img width="403" alt="Captura de ecrã 2020-02-05, às 13 36 26" src="https://user-images.githubusercontent.com/150562/73846564-a3a4eb80-481c-11ea-985f-2ff7aff9c046.png">

**Comment by mcsf** [comment]
Once #20068 lands, the API becomes `wp.blocks.registerBlockVariation`.
