### ISSUE TITLE
Allow customization of InnerBlocks block library inserter

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#17280]
A nice extension to InnerBlocks would be the ability to modify the block inserter that is used. 

The need arose while developing the Social Links #16897 PR which uses InnerBlocks to contain each of the links, this gives search and other features from the block inserter but brings along features such as the tip/description part.

![image](https://user-images.githubusercontent.com/45363/64025617-ed610b80-caf1-11e9-9024-ef83724a0082.png)

**Describe the solution you'd like**
It would be nice to be apple to pass options to the inserter something like:

```
<InnerBlocks
    inserterOptions={ showDescription: false  }
    ...
/>
```

**Describe alternatives you've considered**

The only option I found to extend would be to use the `renderAppender` but that would require recreating the majority of the block inserter.

**Comment by mtias** [comment]
Closing as the quick inserter doesn't come with the tips / preview now.
