### ISSUE TITLE
Unable to prevent paragraph block auto transforms

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/gutenberg#17289]
When creating a new paragraph it is possible to transform it into a list by starting it with an asterisk. It is however not possible to create a paragraph that starts with an asterisk because it is always transformed and it is not possible to transform back to a paragraph without loosing the asterisk. 

This same behaviour also happens with quotes as well I hear.

**To reproduce**
1. Create a new paragraph block.
1. Start the paragraph with an asterisk and press space - paragraph transforms to list.
1. Transform the list back to a paragraph and the asterisk is gone.

**Expected behavior**
Ability to prevent the transform somehow or revert it without character losses.

**Screenshots**
![Peek 2019-08-31 22-41](https://user-images.githubusercontent.com/3902039/64069402-afbec880-cc40-11e9-962a-657783a6dbc6.gif)

**Notes**
One suggestion was that this could work similar to the double `##` used to transform paragraph to heading and another suggestion was `shift` + `space`

**Comment by senadir** [comment]
I'm not sure if I can call this a bug or a feature request, I'm leaving it up to @ellatrix & @mapk to decide

**Comment by pattonwebz** [comment]
Yeah I clicked back and forth between those a couple times when opening this, also uncertain if it's a bug or a feature.

For some added context though this issue I hit early on when writing my post today and to fix it I flicked to the html editor. I did not return back to blocks - I wrote the rest of the post in html. I only mentioned this in the `core-editor` channel because I realised the fact I stayed in the html editor and did not revert back to blocks put me in a situation where the new editor was not helping me - it was only in my way :(

**Comment by mcsf** [comment]
#14776 was merged recently and sought to address this problem using Undo. @pattonwebz, would it solve your problem?

**Comment by pattonwebz** [comment]
I will try pull the latest branch and test this when I get a chance. Looks like that would solve the problem I ran into :)

**Comment by senadir** [comment]
it's available in 6.4 and wordpress.com as I've tested, I'm going to close this for now since it's already solved, feel free to open back if anything came up
