### ISSUE TITLE
Documentation: Add examples of how to programmatically remove the panels in Document sidebar

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17281]
Follow-up for:

https://github.com/WordPress/gutenberg/pull/11802

> Execute the following code in the JS console to remove one of the panels and ensure it is not present in the sidebar and Options modal (you can access it from More Menu):
> 
> ```js
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-category' ) ;
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'taxonomy-panel-post_tag' );
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'featured-image' );
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'post-excerpt' );
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'discussion-panel' );
> ```
> 
> Note that you can't remove `Post & Visibility` panel. The following (despite being valid) won't be reflected in the UI:
> 
> ```js
> wp.data.dispatch( 'core/edit-post').removeEditorPanel( 'post-status' );
> ```

Aside: It will be possible to remove `post-status` panel if PR https://github.com/WordPress/gutenberg/pull/17117 from @noahtallen is going to be accepted (which is very likely).

**Comment by gziolo** [comment]
@mkaz or @ryanwelcher – any thoughts were to add related documentation? Would it make sense to add a tutorial on how to manage Document settings sidebar with the existing SlotFills (like https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/sidebar/plugin-document-setting-panel/index.js) and `removeEditorPanel` action?

**Comment by ryanwelcher** [comment]
I like the idea of adding some SlotFill tutorials to the handbook this would also address #19747
