### ISSUE TITLE
Gallery: Handle old gallery shortcode in Classic Text block, or use Switcher

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1728]
We have a new gallery block. But existing galleries created using the shortcode will still work.

We need to handle the shortcode better. That is both conversion from the shortcode to the new gallery, and perhaps the other way too. This could happen through the switcher, or it could happen as a button in the inspector. We also need to figure out how to preview the shortcode gallery. It already renders fine in the Classic Text block, so perhaps simply convert it to that.

**Comment by aduth** [comment]
Related (potential duplication): #2454

**Comment by iseulde** [comment]
I agree that this is a duplicate. Also related to #2478 which would handle shortcodes on paste (raw content). I need to redo that one a bit after the recent paste commits.
