### ISSUE TITLE
Removing Blocks' Top / Bottom Margins in the editor

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#17295]
I've found this:

.block-editor-block-list__layout .block-editor-default-block-appender>.block-editor-default-block-appender__content, .block-editor-block-list__layout>.block-editor-block-list__block>.block-editor-block-list__block-edit, .block-editor-block-list__layout>.block-editor-block-list__layout>.block-editor-block-list__block>.block-editor-block-list__block-edit {
    margin-top: 32px;
    margin-bottom: 32px;
}

However, apparently, the blocks actually overlap somehow in a way I can't seem pinpoint. What is this CSS voodoo? :)That is, at any given moments the space between two consecutive blocks is 32px, not 64px. What's going on here? More importantly - for my education - why? Why not margin-bottom: 16px and margin-top: 16px such that the two total32

I have a remove (top and/or bottom) spacing component/attribute but am current at a loss on how to best represent it in the editor, and to do so with minimal technical (js) gymnastics. I tried having a class with a negative top / bottom margin but that's not working as expected (because of the overlap issue).

I've looked at other blocks with a similar feature and some make no change to what's displayed in the editor. That's not a good UX either. Maybe the blocks can't actually meet due to toolbars, etc? If not, then what? 

I'd like to get some insights on my immediate issue, but also want to suggest this be visited (revisited?) such that there's a common standard that everyone can follow.

**Comment by alaczek** [comment]
> However, apparently, the blocks actually overlap somehow in a way I can't seem pinpoint. 
This would be because of [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)?

**Comment by talldan** [comment]
The selector that applies the margin is `.editor-styles-wrapper .block-editor-block-list__block`, I couldn't see any issue with overriding the styling, so will close the issue.

It's hard to grasp exactly what the goal is, but I think the way alignments are implemented could probably serve some inspiration:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/hooks/align.js

**Comment by AlchemyUnited** [comment]
@talldan - The goal is to adjust the admin block margins to reflect what's going to be rendered in the frontend.

**Comment by talldan** [comment]
Is this for a theme you're developing?
