### ISSUE TITLE
Special character request for rupee symbol ₹

### ISSUE THREAD

**Issue by poojashetty18** [WordPress/gutenberg#17299]
Got a request on this hc-14950083 to include the Rupee symbol

**Comment by Soean** [comment]
Hey @poojashetty18,
thanks for your ticket. Can you describe the issue more precisely and give a context? Where exactly should this symbol be added? In a specific block or a setting?

And what does `hc-14950083` mean?

**Comment by talldan** [comment]
@Soean It's a customer enquiry reference code used internally at Automattic. I know they're used on Automattic github projects like Calypso, but they shouldn't be posted in WordPress.org projects.

I've reached out to @poojashetty18 to remove the reference and share a bit more info in the description 👍

**Comment by poojashetty18** [comment]
Hey sorry for the trouble by not being detailed about it.

I got a request where a customer wanted to use the rupee symbol ₹ that they would be using multiple times on many posts and it wasn't present in the special characters list and they mentioned copy pasting it would be a trouble everytime so they requested for an enhancement request to add the rupee symbol ₹

Special characters list screenshot: ![https://d.pr/free/i/o189Sn](https://d.pr/free/i/o189Sn+)

Full image link: https://d.pr/free/i/o189Sn

**Comment by Soean** [comment]
Thanks for clarification.
The Special characters are not implemented in Gutenberg, just in the Classic block and old editor. We have a closed ticket about this feature #1678. So I am not sure we can do anything here.

**Comment by talldan** [comment]
@Soean agreed. It looks like there's a plugin for this functionality in the block-editor now as well:
https://github.com/WordPress/gutenberg/issues/1678#issuecomment-526758686

I think the best course of action is to close this issue.

**Comment by jeffpaul** [comment]
@poojashetty18 note that the rupee symbol is available in the [Insert Special Characters plugin](https://github.com/10up/insert-special-characters/releases/tag/1.0.3), you can use that in place / until special character functionality is added to Gutenberg.
