### ISSUE TITLE
Tags: Single Apostrophe turns into &#039 in editor

### ISSUE THREAD

**Issue by JoshuaGoode** [WordPress/gutenberg#17291]
**Describe the bug**
When adding a tag with an apostrophe,`'`, via Gutenberg -- the tag briefly disappears and the apostrophe appears as the HTML `&#039`.

It appears this is the only special character/symbol with this behavior.

The tag appears properly via the tag manager in WP-Admin but not in the editor.

If added via the tag manager (WP-Admin > Posts > Tags), the tag will appear properly on both the tag manager and the editor. 

**To reproduce**
1. Go to a post
2. Add a tag with an apostrophe
3. Tag may disappear but will be available via tag search.  The tag will show the apostrophe as `&#039`

**Expected behavior**
For the tag to properly display the apostrophe and not the HTML symbol code.

**Screenshots**

Video of adding a tag with an apostrophe via the editor: https://cld.wthms.co/qHOsTq

Example of what it looks like in the editor:
![Screen Shot on 2019-08-24 at 12-29-01](https://user-images.githubusercontent.com/4887830/64070100-c6a4f100-cc27-11e9-9063-8bc7e6e5ca28.png)

Example of what things look like on the tags management page:
![Screen Shot 2019-08-24 at 12 28 41](https://user-images.githubusercontent.com/4887830/64070106-f8b65300-cc27-11e9-8fea-51f762e6514c.png)

**Desktop (please complete the following information):**
 - OS: Latest MacOS
 - Browser: Tested in latest versions of Chrome, Safari, and Firefox
- Standard US English Keyboard

**Additional context**
- 6.4.0 / WP Core 5.2.2

**Comment by dickmoomaw** [comment]
Reproduced this issue:
MacOS Version 10.14.6
Gutenberg Version 6.8.0
Chrome Version 78.0.3904.70
Standard US English Keyboard

**Comment by Chrispwired** [comment]
Reproduced this issue using Catalina:
MacOs Version 10.15.1
Gutenberg Version 6.8.0
Chrome Version 78.0.3904.97
Mac U.S. English keyboard

**Comment by GeoJunkie** [comment]
I worked with someone encountering this issue:
 User Agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48
WP 5.3

**Comment by youknowriad** [comment]
cc @jorgefilipecosta as you worked on terms escaping some time ago according to git history :)

**Comment by mdrockwell** [comment]
WordPress.com user is experiencing this issue on their site here: 2791718-zen
