### ISSUE TITLE
Page going to the top when typing making writing a page almost impossible

### ISSUE THREAD

**Issue by SabrinaCs** [WordPress/gutenberg#17294]
**Describe the bug**
New Wordpress site, privacy page, as precompiled by Wordpress, when writing in any text block exceeding the end of the video at the first character typed the page scrolls to Top so it is impossible writing pages longer than some paragraphs.
And the Classic Paragraph is not available.
as a comment:
In my Blog that is born way before Gutemberg this does not happen.

**To reproduce**
1. Create a new Website (mine was a third level domain) it is hosted on 1and1 ionos but I use the full manual Wordpress template no precooked versions.
2. Configure the home page as a simple Page.
3. Create the page writing some text.
4. Go to the Privacy Page created by Wordpress
5. Try to write something on a paragraph below the end of the page.
6. Change the Theme to the Wordpress (last version of it) to see if it changes.
7. Create a new page to see if it is due to the precompiled page
8. Write Headers and Paragraphs to the new page
9. After reaching the end of the video, things do the same as soon as a key is typed the page scrolls to top and you don't see what you are writing.

**Expected behavior**
The same I have on my blog, I can write pages and articles longer than the video length.

**Desktop (please complete the following information):**
 - OS: WIndows 10 64 bit last update
 - Browser Edge, Chrome
 - Version Edge: 44.17763.1.0 Chrome: 76.0.3809.132

**Additional context**
- Gutemberg Version: Latest available

**Comment by talldan** [comment]
Hi @SabrinaCs. Thanks for reporting this. It sounds similar to the issue reported in https://github.com/WordPress/gutenberg/issues/17255, although in Chrome as well as Edge.

I've tried testing and wasn't able to reproduce the problem with the page scrolling to the top. I wonder what could be causing that issue.

> And the Classic Paragraph is not available.

This does sound unusual. If you check in the Block Manager, does the classic block appear in the list of blocks? It should appear like below:

![Screen Shot 2019-09-02 at 11 56 25 am](https://user-images.githubusercontent.com/677833/64089581-3a0a4800-cd79-11e9-9e72-e5b7ae3800f4.png)

The block manager can be accessed from the editor settings menu in the top-right:

![Screen Shot 2019-09-02 at 11 56 16 am](https://user-images.githubusercontent.com/677833/64089576-34146700-cd79-11e9-89ca-4c8ae75e4b32.png)

**Comment by SabrinaCs** [comment]
Thank you for the rapid answer, The Classic Paragraph is the one with the Keyboard as icon? Because I remember trying it but it does not behave as the classic paragraph on my blog.
The only further info I can give You is that I was using a Theme from CompeteThemes.com (Tracks) with its PRO, and my first thought was "it is a problem of the Theme", but even changing it with the Twenty Nineteen did not change anything. The only other Plugins installed were the Google Captcha and the Wordpress Bulletin board.  I have no other info I can share and I hope you can reproduce the problem and find why it happened.
Bye
Sabrina

**Comment by talldan** [comment]
@SabrinaCs Yep, it's the one with the keyboard as the icon. Were you able to follow the steps I posted above to see if it's present in the block manager?

**Comment by SabrinaCs** [comment]
I will try again in the weekend, I've cancelled the test site (my bad) I will do an installation from scratch to test this and let you know more.

**Comment by youknowriad** [comment]
I think this is probably the same one as #17255 i'm going to close as a duplicate and I've raised the priority of that issue.
