### ISSUE TITLE
Edit meta_value in any edition page

### ISSUE THREAD

**Issue by anUserFr** [WordPress/gutenberg#17307]
How to edit meta_value in a gutenberg block located in any edition page, knowing the meta_key and post_id?

**Comment by u1qqlv** [comment]
is this a bug or a support request? looks like a support request.

**Comment by anUserFr** [comment]
@u1qqlv , it s a a support request.

**Comment by swissspidy** [comment]
Hi there

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.
