### ISSUE TITLE
Inspector: Consider pill button to split between Block and Post/Page settings

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1730]
As discussed in #1356 (CC: @GaryJones), and also per recent discussions on #1716 and #1251, there's some confusion around how to access advanced block settings.

Let's explore renaming the sidebar from "Post Settings" to "Settings", and add a pill button switch to the sidebar itself. The pill button would have two options, "Post Settings", and "Block Settings". 

This would make the cog behavior more obvious. It would also let you see just the post settings, without having the block settings interfere, as you select blocks. 

This pattern mimics how Keynote does it.

**Comment by jasmussen** [comment]
Here's yet another mockup: 

![inspector](https://user-images.githubusercontent.com/1204802/27996611-5d8eb6e2-64e6-11e7-8d19-a248da547957.png)

**Comment by GaryJones** [comment]
As that last mockup is, it doesn't leave much space for longer translations, or plugin customisations (i.e. wanting to add a third "tab").

**Comment by jasmussen** [comment]
Could we do with "Post" and "Block" as the titles? Also, I wouldn't imagine this area be pluggable.
