### ISSUE TITLE
PDF into Gutenberg I get unnecessary spaces

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#17302]
When I import a text from a PDF into Gutenberg I get unnecessary spaces. Example:
![cbSBHX6zOU](https://user-images.githubusercontent.com/9355398/64124169-9172dd00-cda6-11e9-9721-40c37e6a3e02.gif)

And the Screenshot:

![Screenshot_2](https://user-images.githubusercontent.com/9355398/64124274-e0207700-cda6-11e9-9a18-abd795448491.png)

This distance makes sense if I want to insert a new sentence after an existing one. However, if I add a new paragraph, this space is superfluous.

**Describe the solution you'd like**
When a new paragraph/block is inserted, there should be no space at the beginning.

**Describe alternatives you've considered**
I don't know

cc: @ellatrix

**Comment by paaljoachim** [comment]
Thanks for adding this issue SchneiderSam. I have also noticed an extra character before pasted text most of the time.

**Comment by ellatrix** [comment]
Thanks for the report. The solution would be to trim the spaces in the raw handler. Right now, the spaces should collapse on the front-end though.

**Comment by SchneiderSam** [comment]
If that fits the frontend, that's great. It would be nice if it is the same in the editor. Sorry for these little things...
