### ISSUE TITLE
Table block generate same table until refresh the page.

### ISSUE THREAD

**Issue by rishishah41194** [WordPress/gutenberg#1731]
If I created a table and added data into it. Later I add the table in the same post the table will create with old table data automatically until I refresh the page. I have attached the GIF file for the same.

![guternburg_table](https://user-images.githubusercontent.com/23692490/27865900-f237f476-61b1-11e7-8f1c-1485165e0d0d.gif)

**Comment by tg-ephox** [comment]
@rishishah41194 I can no longer replicate this on master

**Comment by mtias** [comment]
Closing this. Feel free to reopen if you can still replicate.
