### ISSUE TITLE
Insert link: leading spaces pasted into hyperlink modal not stripped out

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#17314]
**Describe the bug**
When using the hyperlink button in a paragraph block to insert a link, if a leading space is pasted in along with the link, the space is not stripped out but included in the published markup, causing the link to break. Trailing spaces are also not stripped out, but don't break the link.

**To reproduce**
1. Add a new paragraph block with some text
2. Select some text and click on the hyperlink icon in the editing toolbar
3. Paste in a URL that was copied with a leading space, or simply type in a URL with a leading space
4. Publish/preview the post (or just check the markup in the HTML view of the editor

The resulting markup for the link appears as `<a href="http:// https://example.com/">` - note the extra `http://` and space before the inserted URL.

Inserting a link by simply highlighting and then pasting does not result in the same problem - there the leading space gets stripped out correctly. This only happens when the hyperlink icon from the edit toolbar is used.

**Expected behavior**
I would expect the leading space to be stripped out/ignored, with the href attribute in the HTML view/published post to just contain the URL itself.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Firefox 68.0.2

**Additional context**
- Confirmed on a site using WordPress 5.2.2 and Gutenberg 6.4.0

Originally reported to the WordPress.com Twitter account.

**Comment by donmhico** [comment]
Thanks for the report @KokkieH. #17320 should address the issue.

**Comment by KokkieH** [comment]
Excellent. Thanks @donmhico!
