### ISSUE TITLE
Flipped colors in color picker

### ISSUE THREAD

**Issue by hamedmoody** [WordPress/gutenberg#17321]
In post paragraph block color picker the color pallet is flipped.  
when i  clicked on gradient on violet  color but yellow was selected
at the top when clicked on full color but white selected
slide for range color does not work

![image](https://user-images.githubusercontent.com/9475089/64225726-ef600b80-cef1-11e9-9fad-060758670bbc.png)

![image](https://user-images.githubusercontent.com/9475089/64225755-19193280-cef2-11e9-8d37-9fb984a163ac.png)

**Comment by talldan** [comment]
Thanks for reporting this @hamedmoody. I can confirm the bug occurs when a RTL language is used.

**Comment by hamedmoody** [comment]
Yes it is just css, this problem will solve by small css
I use this code for solve this prolem

http://dnjy.ir/FeD1

**Comment by hamedmoody** [comment]
many Same rtl problems found in gutenberg in Rtl setting but this most important.
