### ISSUE TITLE
Cover Block: Default height cuts off taller content published before 6.4

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#17339]
This issue has already been mentioned in the PR #17143, but I thought it'd be good to open a new issue for it so that it won't be forgotten :)

Since the default value of the new setting "Height in pixels" is added to all the existing cover block in a site, taller content published before 6.4 gets cut off in the editor with the update. (6.4 is on the right) 

<img width="638" alt="screen-shot-2019-08-31-at-00 19 47" src="https://user-images.githubusercontent.com/908665/64304893-7e6a3380-cf85-11e9-953e-aa32849dad9c.png">

This is a problem in large sites that have a lot of already published posts and page with the block, and I'm curious about the next step to resolve this if there is any.

**Comment by jorgefilipecosta** [comment]
Hi @iamtakashi, @allancole I proposed a PR that refactors the height mechanism https://github.com/WordPress/gutenberg/pull/17365 it should fix the problems being faced.
