### ISSUE TITLE
Block within Block can not be dragged to another position

### ISSUE THREAD

**Issue by kgolubic** [WordPress/gutenberg#17330]
Block within Block can not be dragged to another position.

**To reproduce**
1. Create a new page
2. Insert Two columns
3. Add one paragraph to the first column
4. Add two paragraphs to the second column

![image](https://user-images.githubusercontent.com/46486712/64263549-176e5f80-cf30-11e9-966e-4272fe54008d.png)

5. Drag and drop paragraph from the first column to the second one

I've tried adding other types of blocks to columns and behavior is always the same. If there is just one block within some other block commands for rearranging block are not shown. 

**Expected behavior**
I would expect that controls for reordering of the blocks would be visible for all of the blocks.

It can not be done since controls are only visible if there is more than one block in a column.

![image](https://user-images.githubusercontent.com/46486712/64263712-674d2680-cf30-11e9-8bed-e94843de7d4f.png)

![image](https://user-images.githubusercontent.com/46486712/64263742-716f2500-cf30-11e9-9198-f234e11dd220.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome 
 - Version 76.0.3809.132 

**Additional context**
- I've used a clean install of Wordpress 5.2.2

**Comment by youknowriad** [comment]
I think this is fixed.
