### ISSUE TITLE
Consider revising the color swatch states. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#17332]
The current "Selected" color circle makes it really difficult to see the actual selected color. To combat this, Gutenberg adds a second, rectangular color swatch next to the panel title. 

<img width="264" alt="Screen Shot 2019-09-04 at 3 02 01 PM" src="https://user-images.githubusercontent.com/1202812/64284216-11c04c00-cf27-11e9-8aaa-2dbbd4e3e398.png">

We should consider revising the circular swatch treatment in order to negate the need for that additional swatch. 

One quick idea would be to adopt the select + focus states [used for block styles](https://github.com/WordPress/gutenberg/pull/16545). Here's how that might look: 

<img width="400" alt="Frame 5" src="https://user-images.githubusercontent.com/1202812/64284408-8c896700-cf27-11e9-8b49-c60b9b47b9b5.png">

_Comparison to current approach:_ 
<img width="356" alt="Frame 6" src="https://user-images.githubusercontent.com/1202812/64284409-8c896700-cf27-11e9-8ee8-6fbaee820efc.png">

This isn't quite as clear, so I think some more iteration is needed. Also worth considering: either way, we'll need a place to include a swatch if the user selects a custom color.

**Comment by drw158** [comment]
What about a white check icon in the circle without the additional white circle inside it?

![Screen Shot 2019-09-04 at 3 10 41 PM](https://user-images.githubusercontent.com/618551/64287760-2e0fb900-cf26-11e9-9495-bc090534c6e9.png)

**Comment by ZebulanStanphill** [comment]
@drw158 That wouldn't work for the color white... unless the check had a black outline around it. Alternatively, a black check icon with a white outline could be used.

**Comment by drw158** [comment]
Yes, that is what I had in mind. The check icon color would simply change to black to meet contrast requirements, depending on the color.

**Comment by sarahmonster** [comment]
I could see how the concentric circles might make it tricky for users to differentiate between the selected and hover/focus states. A check mark feels a bit more universally understood here, and it's a pattern we're already establishing elsewhere (see: image galleries) for selected states. (See also #17189, where an idea was floated for using the checkmark for a non-selected state.)

Here's a quick comparison of those options, including how it might look with the inverse (black check mark) treatment, riffing off @kjellr's original mockup. This should be easily accomplished using the tinycolor2 library already in use for contrast checks. (The [mostReadable function](https://www.npmjs.com/package/tinycolor2#mostreadable) is probably the easiest way to return the best result against the swatch colour.)

<img src="https://user-images.githubusercontent.com/376315/64720570-b4963e80-d4c2-11e9-9355-4cc3ced85e8e.png" width="320" alt="Mockups of unselected and selected colour swatches in default, hover, and focus states, using different styles of select indicators." />

Note that this screenshot uses the blue focus ring used elsewhere in the UI for consistency, but we could also use the grey one currently in use for a less jarring contrast against certain colours:

<img src="https://user-images.githubusercontent.com/376315/64723070-ae569100-d4c7-11e9-9610-426ee2973e33.png" width="320" alt="The same swatch mockups, using a grey focus ring and a smaller checkmark" />

The above mockup also uses a slightly smaller checkmark, just so we can see more of the swatch itself. Providing it doesn't cause visibility issues, I'd be inclined to go with slightly more padding inside of the swatch.

**Comment by enriquesanchez** [comment]
I love how y'all collaborately iterated and arrived to an awesome solution. 

I like the last mockup that @sarahmonster shared. I think that the checkmark and the gray focus ring work really well.
