### ISSUE TITLE
Entering multi-block selection mode inappropriately in Safari

### ISSUE THREAD

**Issue by claudiosdc** [WordPress/gutenberg#17331]
In Safari, if one clicks on a select/dropdown control found in a block (any block) while editing and selects one of its options, the mouse cursor starts behaving as if it was still pressed so the blocks get selected as the cursor moves on the page.

1. On Safari, create a new page and add a "Categories" block to it;
2. Change the Categories Settings so the "Display as Dropdown" option is selected;
3. Using the mouse, click on the dropdown control and select any of its options (it could even be the already selected one);
4. Then move the mouse cursor up or down and you will notice that the Categories block and any adjacent blocks around it will get selected, as if the mouse button was kept pressed while the cursor moves.

Expected behavior: after selecting the dropdown option and moving the mouse cursor, no block should get selected.

System configuration:
 - OS: macOS ver. 10.14.6
 - Browser: Safari ver. 12.1.2
 - WordPress ver. 5.2.2

**Comment by glendaviesnz** [comment]
I have tested this and verified on Safari 12.1.1 and it is easily replicated following the above steps. 

![safari-selection](https://user-images.githubusercontent.com/3629020/65596713-8dc02800-dfeb-11e9-8d01-ca95dbd9950d.gif)

It does not happen on Chrome or Firefox.

**Comment by ellatrix** [comment]
This is fixed with #16835. Will be in the next Gutenberg plugin release.
