### ISSUE TITLE
Unable to unit test component method that uses @wordpress/api-fetch

### ISSUE THREAD

**Issue by con322** [WordPress/gutenberg#17345]
**Describe the bug**
Unable to unit test a method on a class/component that calls the wp.apiFetch method but when I run the test it always says TypeError: apiFetch is not a function the below structure has worked for other test cases,  all be it they don't make any api calls. Which is why I raise this as a bug but feel free to assign as help request if my setup is the issue.

**Stripped down test setup**
```
global.wp = {};
// some other packages
Object.defineProperty(global.wp, 'apiFetch', { get: () => require('@wordpress/api-fetch') });
```

**Stripped down test**
1. Shallow render the component
2. Call the method in question on the component instance - at this point here the tests error because of the error mentioned at the top.
3. Check that the method was called
```
  it('createAuthor valid', () => {
    // may have to mock window.fetch as wp.apiFetch uses it but that's currently not the issue

    const componentProps = {
      someFunc: jest.fn(),
    };

    const component = shallow(<NewAuthor {...componentProps} />);
    component.setState({ name: 'john smith' });

    component.instance().createAuthor();

    expect(componentProps.someFunc).toHaveBeenCalledTimes(1);
  });
```

Stripped down component
```
const { apiFetch } = wp;
// some more constants from window

class NewAuthor extends Component {
  // constructor
  // method to test
  createAuthor = () => {
    const { someFunc, someErrorFunc } = this.props;
    const authorObject = {
      name,
    } = this.state;
    const createPath = '/wp/v2/users';

    apiFetch({
      path: createPath,
      data: authorObject,
      method: 'POST',
    })
      .then((user) => {
        console.log('success', user);
        someFunc();
      })
      .catch((error) => {
        console.log('error', error);
        someErrorFunc();
      });
  };
  // some more methods
  // render
}

export default NewAuthor;
```

**Comment by talldan** [comment]
@con322 The issue with `apiFetch` not being a function definitely seems like it would be an issue with your test setup. The first thing is that if you mock `apiFetch` itself in your tests, you won't need to worry about using `require` in your test setup, you can just define it as a `noop`:
```
global.wp = { apiFetch: () => {} };
```

The following code snippets show how `apiFetch` is mocked in the gutenberg codebase:
https://github.com/WordPress/gutenberg/blob/bd45ebdbe7831c6fa9406dfd3562df8c9439bd28/packages/editor/src/store/effects/test/reusable-blocks.js#L39

https://github.com/WordPress/gutenberg/blob/bd45ebdbe7831c6fa9406dfd3562df8c9439bd28/packages/editor/src/store/effects/test/reusable-blocks.js#L86-L92

I'd recommend following that kind of approach as it's tried and tested in this codebase.

I'll close this issue as this isn't really supposed to be a support forum, hope the response is of help though.
