### ISSUE TITLE
meta box problem with $context

### ISSUE THREAD

**Issue by NasKadir123** [WordPress/gutenberg#17348]
Hi!
I created a simple meta box with select options:
function themename_add_meta_box() {
    add_meta_box( 
        'themename_post_metabox', 
        esc_html__( 'Post Settings', 'themename' ), 
        'themename_post_metabox_html', 
        'post', 
        'normal', 
        'high');
}
add_action( 'add_meta_boxes', 'themename_add_meta_box' );
function themename_post_metabox_html($post) {.....

And added some options and made save_post.
Everything was working, but then I changed $context 'normal' to 'side'.
My meta box moved to right to settings, so it's ok, then I return back to 'normal',
but nothing was moved.
I delete all metabox file and return it, but nothing.
Can you help me with that?
Thanks.

**Comment by youknowriad** [comment]
I believe the classic editor has some stored preferences about the meta boxes position, this could potentially bleed into Gutenberg. Consider trying to drag the meta box in the classic editor and try again?

Note that this tracker is not used for help requests.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
