### ISSUE TITLE
Handle invalid blocks without modifying their markup

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1736]
We need to detect blocks with invalid markup (e.g. added classnames, added or removed tags).

One way to do this (idea from @mtias): Detect "invalid" blocks by re-serializing blocks that we see in the editor.  If it changes beyond a certain threshold (e.g. whitespace doesn't matter), then show the block as a `core/html` block and highlight how the markup would be changed.

Like #1735 it is important that the default "save" operation not alter the markup inside the block.

**Comment by afercia** [comment]
As an example: noticed during work on the Pullquote block, see #1987 

When editing a post with a pullquote in the Classic editor, and then again in Gutenberg, the content gets lost. For example: inserted a pullquote with 2 paragraphs:
```
<blockquote class="wp-block-pullquote alignnone">
    <p>My quote</p>
    <p>with multiple par</p>
    <footer>my caption</footer>
</blockquote>

```

Saved, then opened the same post using the Classic editor, switched to text mode and the markup was changed to:
```
<!-- wp:core/pullquote -->
<blockquote class="wp-block-pullquote alignnone">My quote

with multiple par

<footer>my caption</footer></blockquote>
<!-- /wp:core/pullquote -->
```

This perfectly works in the Classic editor, but when editing again in Gutenberg, it doesn't of course and the content gets stripped out.
