### ISSUE TITLE
Have multiple empty paragraph breaks -> convert to spacer block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17366]
**Is your feature request related to a problem? Please describe.**
I find it cumbersome to have to add so many spacer blocks to gain some margin/padding in the layout. Having another quicker way to add the spacer block would help.

**Describe the solution you'd like**
@melchoyce mentioned this:
"One thing that could be cool re: spacer block, it automatically converting multiple paragraph breaks (say, three or more) into a spacer block."
https://github.com/WordPress/gutenberg/issues/11824#issuecomment-528918801

I found it a very interesting idea! As one could easily press enter multiple times (three or more times) and have a spacer block inserted. A lot quicker then having to manually add the spacer block.

**Comment by ellatrix** [comment]
When would that conversion happen? Cc @melchoyce.

**Comment by melchoyce** [comment]
I think the third time you press enter, we should turn those paragraph breaks into one spacer.

**Comment by paaljoachim** [comment]
I am thinking we might need design to look this over and give it a thumbs up so we can add the need dev label. We might also need a larger discussion around this issue. I have added a comment to the core editor agenda. 
@mapk

**Comment by mapk** [comment]
I love this idea and saw something like this with @phpbits' plugin I think. 

Should we communicate to the user when this happens? Any sort of notification like a snackbar?

**Comment by melchoyce** [comment]
A snackbar is a good idea, maybe paired with an "undo" link?

**Comment by paaljoachim** [comment]
Good idea having a snackbar with an undo link!

**Comment by paaljoachim** [comment]
I think we are about ready to get a PR going.

**Comment by paaljoachim** [comment]
Here is what the notification can look like:
![Convert-to-Spacer-Gutenberg](https://user-images.githubusercontent.com/5323259/78001970-c3e1ba00-7336-11ea-9303-30456a732c7c.jpg)

**Comment by jasmussen** [comment]
#27995 was just merged, which makes sure a linebreak in the editor shows up as a linebreak on the frontend. 

Does that mitigate or even fix this issue?

**Comment by paaljoachim** [comment]
I am not sure Joen. Let's test out the merged PR in the next version of Gutenberg and get a feel for it.

**Comment by paaljoachim** [comment]
Closing this issue, as it has mostly been taken care of.
