### ISSUE TITLE
Planned date does not take care of 24h format.

### ISSUE THREAD

**Issue by chdenat** [WordPress/gutenberg#17369]
When you planned a post to, ie 10:30 am or  10:30 pm you should see
Publish  ---- 10:30  or  ---- 22:30 when you are using 24h time format. 
Today, in both case, you see 10:30 and do not know the exat publis time until you open the calendar.

**Expected behavior**
You should see in one case 10:30, in the other 22:30

**Screenshots**
Added screenshots : once with 10:30, the other with 22:.30

**Desktop (please complete the following information):**
 - OS: W10
 - Browser : chrome, firefox,Edge
 - Version : latest

**Additional context**
- Gutenberg plugin  6.4

![2019-09-08 11_09_50-Window](https://user-images.githubusercontent.com/9724885/64486104-471bb100-d229-11e9-8055-a4400b4aa0f8.png)
![2019-09-08 11_09_21-Window](https://user-images.githubusercontent.com/9724885/64486105-50a51900-d229-11e9-801c-6a19159421a1.png)

**Comment by roykho** [comment]
The time format I believe is dictated by the time format you have in your WP settings as seen here ![](https://cld.wthms.co/jbWxKf+) When it is set to the 24h time, it will show in that format and vs versa.

![](https://cld.wthms.co/JwqOGC+)

**Comment by chdenat** [comment]
No ! It was not due to the hour settings, mines were Ok !  It seems fixed in Gutenberg 6.8.0  (did not check in intermediate release), so I close the issue.
