### ISSUE TITLE
Change Block Name

### ISSUE THREAD

**Issue by alpezed** [WordPress/gutenberg#17372]
**Is your feature request related to a problem? Please describe.**
I've created a block like bb-gutenberg/box but i have a dynamic block already with prefix better-gutenberg/box. After updated my block to **better-gutenberg/box** name it breaks everything.

**Describe the solution you'd like**
I just want to update my block from **bb-gutenberg/box** name to **better-gutenberg/box** name without breaking my old content that using old block name (**bb-gutenberg/box**)

**Comment by swissspidy** [comment]
Hi there!

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

For your specific case, please check out https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#transforms-optional and https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/ for documentation.

**Comment by alpezed** [comment]
Hi, sorry but what i need exactly is change my block from **bb-gutenberg/box** namespace to **better-gutenberg/box**, but it breaks everything because the **bb-gutenberg/box** is missing. 

### Screenshot

![2019-09-10_1920](https://user-images.githubusercontent.com/4197193/64609757-3709fa00-d400-11e9-852c-df01bd40e92d.png)

**Comment by simonhammes** [comment]
Maybe it would be an option to add a name property to objects in the deprecated property of the new block to accommodate a new block name?

**Comment by alpezed** [comment]
Yes something like that, that will be great if you can add a name property to objects in the deprecated property so i can update or change my block name because i have some other block also that i want to update and change the block name.

**Comment by alpezed** [comment]
Is there any other alternative way to do this? like search the **'<!-- wp:bb-gutenberg'** and replace with **'<!-- wp:better-gutenberg'** so the old block name was replace by "<!-- wp:better-gutenberg".
