### ISSUE TITLE
link box: move toggle to right side

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17379]
**Is your feature request related to a problem? Please describe.**
Opening the arrow one has to move the cursor over to the left side.

![Screen Shot 2019-09-09 at 09 08 49](https://user-images.githubusercontent.com/5323259/64510061-77268b00-d2e1-11e9-8074-555e1f73a19d.png)

**Describe the solution you'd like**

What if we move the cursor to the right side just below where one clicks the arrow?
As it would be just below where one clicks the arrow.

![Link-box-toggle-right-side-gutenberg](https://user-images.githubusercontent.com/5323259/64510891-6545e780-d2e3-11e9-8d0e-ffbb6da84fcf.jpg)

Btw this is how it looks like in Editorskit:
![Screen Shot 2019-09-09 at 09 17 29](https://user-images.githubusercontent.com/5323259/64510552-b86b6a80-d2e2-11e9-8d82-a7a226adf807.png)

@phpbits
https://wordpress.org/plugins/block-options/

**Comment by karmatosed** [comment]
As there is a new interface being worked on let's focus there https://github.com/WordPress/gutenberg/issues/17557.
