### ISSUE TITLE
Improving the link dialog box

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17378]
**Is your feature request related to a problem? Please describe.**
It can be difficult in renaming an existing link.

**Describe the solution you'd like**
I would like a straight forward way of renaming a link.

Here is a suggestion. Click the arrow to open to see the link name.

![Link-dialog-box-ver1](https://user-images.githubusercontent.com/5323259/64509663-7f31fb00-d2e0-11e9-8ffe-1dae4fd46598.jpg)

**Comment by swissspidy** [comment]
> It can be difficult in renaming an existing link.

Why is that so?

> I would like a straight forward way of renaming a link.

It should be possible to change the text just by... editing it inline.

**Comment by paaljoachim** [comment]
I am backing up some...
Let's look at the "old" method.

![Screen Shot 2019-10-02 at 07 33 09](https://user-images.githubusercontent.com/5323259/66020313-fd9c4a00-e4e6-11e9-97ff-73b1f058fde2.png)

Then compare with the new Gutenberg way.

![Screen Shot 2019-10-02 at 07 40 17](https://user-images.githubusercontent.com/5323259/66020611-ea3dae80-e4e7-11e9-9313-7a4d18fe67e0.png)

Comparing the two the most important part that is missing is the line to define the text link.
That can be added such as the below.

![Gutenberg-link](https://user-images.githubusercontent.com/5323259/66020341-173d9180-e4e7-11e9-8768-7a5a01d8899f.jpg)

**Comment by karmatosed** [comment]
@paaljoachim for now going to close this in favour of the iteration going on here #17557. This entire interface if being worked on so good to focus.
