### ISSUE TITLE
Widgets block area is weird empty state

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17387]
Seeing an empty sidebar is a little weird experience with it saying 'Block areas'. Perhaps this should not say that and just appear when interacting with a block?

![image](https://user-images.githubusercontent.com/253067/64556243-f2665c00-d336-11e9-8a7e-3057abe20daa.png)

**Comment by noisysocks** [comment]
There's no empty sidebar now, instead you see a _Block areas_ panel.
