### ISSUE TITLE
SetAttributes does not work as expected with two or more post meta fields

### ISSUE THREAD

**Issue by tstarmer** [WordPress/gutenberg#17384]
**Describe the bug**

setAttributes does not work as expected when two or more block attributes are sourced from post meta; e.g. Only one input can be edited and/or saved

**To reproduce**

If you enter text into one input field with block attributes sourced from post meta and then enter text into another input, the text in the first input field is erased. In practice this means only one meta field can be edited at a time and you must save in between or else fields are lost.

**PHP**
```
function register_directory_meta() {
	$fields = array(
		'name_first_name',
		'name_last_name',
	);

	foreach ($fields as $field) {
	register_post_meta('people', $field, array(
		'auth_callback' => '__return_true',
		'type'          => 'string',
		'single'        => true,
		'show_in_rest'  => true,
	));
	}
}
add_action('init', 'register_directory_meta');
```

**JS**
```

import { registerBlockType } from '@wordpress/blocks';
import { TextControl } from '@wordpress/components';

registerBlockType('my-directory/name-controls', {
   title: 'Name Fields',
   category: 'my-directory',
   attributes: {
      my_first_name:{
         type: 'string',
         source: 'meta',
         meta: 'name_first_name',
      },
      my_last_name: {
         type: 'string',
         source: 'meta',
         meta: 'name_last_name',
      },
   },
   edit: (props) => {
      function updateName(value, attribute) {
         props.setAttributes({
            [attribute]: value,
         });
      }
      return (
         <div id="metatest">
            <TextControl
               onChange={value => updateName(value, 'my_first_name')}
               label="First Name"
               key="firstName"
               value={props.attributes.my_first_name}
            />
            <TextControl
               onChange={value => updateName(value, 'my_last_name')}
               label="Last Name"
               key="lastName"
               value={props.attributes.my_last_name}
            />
         </div>
       );
   },
   save: function (props) {
      return null;
   }
})


```

**Expected behavior**

A user should be able to fill out all inputs without having to save in between editing separate fields

**Additional context**
- WordPress version: 5.2.3 
 - Gutenberg Editor version: 6.4.0

We have also tried disabling custom fields, through the user interface and programmatically in functions.php but results are the same.

Additionally, to work around this behavior we changed the block edit function to a stateful component and found that while the multiple fields could be changed on the last edited field could be saved.

**Comment by gchtr** [comment]
I can confirm this issue. It seems like it was introduced in Gutenberg 6.4.0, because with 6.3.0, I don’t have that problem.
