### ISSUE TITLE
wp-edit-post can not be enqueued in the front-end due to postbox missing.

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#17386]
**Describe the bug**
I'm trying to build a playground of the BlockEditor in the front-end. Using npm to import each package  and building a react-only app works perfectly.

The issue comes when trying to set this inside a WordPress environment, using `wp_enqueue_script` and defining gutenberg packages as dependencies.

As far as I could test, other packages work fine except `wp-edit-post` which seems to depend on `postbox` script which is missing (according to Query Monitor plugin). This means that `wp-edit-post` can't be loaded and neither the script.

**To reproduce**
This is the point I am at, still might need to add more dependencies but right now I'm stuck with `wp-edit-post`:

	add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\enqueue' );
	function enqueue() {

		wp_enqueue_script(
			PLUGIN_NAME,
			BUILD_DIR . 'test.js',
			array(
				'lodash',
				'wp-blocks',
				'wp-block-library',
				'wp-components',
				'wp-compose',
				'wp-core-data',
				'wp-data',
				'wp-dom-ready',
				'wp-edit-post', // here
				'wp-element',
				'wp-hooks',
				'wp-i18n',
				'wp-plugins',
				'wp-rich-text',
			),
			PLUGIN_VERSION,
			true // Enqueue in the footer.
		);
	}

**Versions**
- WordPress 5.2.3
- Gutenberg 6.4

Thanks

**Comment by swissspidy** [comment]
The `wp-edit-post` package is specific and closely tied to the edit post admin screen in WordPress. So is the `postbox` script. If you want to build a block editor on the frontend I'd recommend building your own package for that, or alternatively manually enqueueing the `postbox` dependency yourself.

See https://github.com/tomjn/Frontenberg as an inspiration for the latter.
