### ISSUE TITLE
Widgets: move adding widget button to top of widgets

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17389]
If you have quite a number of widgets you have to scroll a long way to add widgets.

![image](https://user-images.githubusercontent.com/253067/64556533-82a4a100-d337-11e9-80e1-f42238c9aa7b.png)

One possible option could be to move the adding action to the top.

**Comment by ZebulanStanphill** [comment]
Personally, I don't think we should be showing every block area on the same page like this. Additionally, doesn't the sibling inserter exist to insert blocks in between other blocks?

**Comment by noisysocks** [comment]
Each block area is collapsed by default which alleviates this somewhat.

**Comment by mtias** [comment]
Closing as the design is a bit outdated and there are now different proposals for addressing this.
