### ISSUE TITLE
Safari: Moving Blocks is SUPER slow

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#17383]
**Describe the bug**

**To reproduce**
0. Use Safari.
1. Create a few blocks or open the demo content.
2. Use the block movers.
3. The block(s) move very slowly to the target position. This is even more annoying when you want to move the block(s) several positions up or down.

**Expected behavior**

Moving blocks should be (near) instant.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: 12.1.1 (14607.2.6.1.1)

**Comment by ellatrix** [comment]
Cc @youknowriad if you have any idea why it's so slow. :)

**Comment by youknowriad** [comment]
Anything particular in the testing environment. Quickly testing this, I was not able to notice laginess.

**Comment by ZebulanStanphill** [comment]
@youknowriad The block movement animation just doesn't happen at all for me on large posts with lots of blocks, but there is still about a second of delay between clicking the button and the block moving. Even on smaller posts when the animation does occur, there seems to be a brief delay before the animation starts.

**Comment by youknowriad** [comment]
I would appreciate if one of the people reproducing this could debug a bit and see if there's anything obvious we're missing?

**Comment by ellatrix** [comment]
I didn’t see anything obvious but I’ll look again when I have the chance.

**Comment by ellatrix** [comment]
I was again able to reproduce with the Gutenberg plugin demo content in Safari Version 12.1.2 (14607.3.9). My battery is 92% charged and I have normal CPU activity. I recorded a GIF:

![move](https://user-images.githubusercontent.com/4710635/64937994-0e9d5800-d865-11e9-9289-f5c1928dbe56.gif)

**Comment by mcsf** [comment]
There's another slowness for me, clearly felt in `master`+Safari, that isn't just animation-related. It's a general sluggishness and tendency to stall — sometimes for several seconds, during which I face the macOS beachball. Have you noticed it, @ellatrix? Should we report that separately?

**Comment by ellatrix** [comment]
I'm trying this again, and the block movers are hidden...

<img width="264" alt="Screenshot 2019-09-24 at 12 13 08" src="https://user-images.githubusercontent.com/4710635/65498524-b8fc2780-dec4-11e9-8bfa-5d4d34f074e7.png">

I don't see the "beachball" at any point though.

When working on native cross block selection, I did notice that Safari was really slow in updating the DOM tree of asynchronously rendered blocks (the ones that are not selected). May be related?

**Comment by youknowriad** [comment]
About the async rendering and whether it's related. It make me think that we use a self-polifilled version of **requestIdleCallback** in the priority-queue package to handle that, and it seems Safari doesn't support it https://caniuse.com/#search=requestidlecallback 

So maybe we have an issue with our polyfill.

**Comment by ellatrix** [comment]
![ezgif-3-b8414f84128b](https://user-images.githubusercontent.com/4710635/65503395-873b8e80-decd-11e9-9d84-3f9199d5e6d2.gif)

Here you can see the DOM updates in Safari. The whole animation takes well over 10 seconds.

**Comment by ellatrix** [comment]
To be honest I had no idea the animation requires _all_ blocks to be updated. This might even be slow in other browsers for a big number of blocks. The benefit this animation brings seems small for the amount of DOM updates and calculations it brings. Is there no way it could be limited to one or two blocks, and done in CSS?

**Comment by jasmussen** [comment]
I can reproduce this. The more blocks on the page, the slower it gets. Potentially #17534 is related, since the things are there just with zero opacity.

Idea: instead of updating _every block_ on the page, only update the ones visible in the viewport. Since the point for moving block is to show the context, these are the only ones that need to animate, anyway. The total height of the entire document remains the same. 

So if we could make it so _the selected block and the preceding ten blocks, and the subsequent 10 blocks_ were the only ones that got animated, presumably this would fix the animation performance issue entirely?

**Comment by ellatrix** [comment]
This is a timeline recording in Safari. The moving takes 12 seconds (!) to complete with very high CPU usage.

<img width="1280" alt="Screenshot 2019-09-25 at 12 05 10" src="https://user-images.githubusercontent.com/4710635/65586845-8702c800-df8d-11e9-9467-8e29f1abb10f.png">

**Comment by ellatrix** [comment]
Updated to Safari Version 13.0.1 (14608.2.11.1.11), and it's still slow.

**Comment by draganescu** [comment]
I would like to add that not only moving but, as @mcsf mentioned, generally everything is slow, for example selecting blocks or deselecting blocks.

Also this is an issue I could reproduce in iPadOS 's Safari and iOS 13. On tablet and mobile it is even worse with seconds of lag between keystroke and text showing up on screen.

**Comment by youknowriad** [comment]
I have a beginning for a fix in #17573
