### ISSUE TITLE
Using post revisions kicks me back to the old editor

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1738]
## Steps to Reproduce

1. Open/start a new post in Gutenberg
2. Write a little here and there so it builds up revisions
3. Open the revisions 'viewer' so to speak, from the sidebar
4. Restore an earlier revision, or just click the 'back to editor' link
5. Now I'm back in the 'old' WP editor...

plugin version 0.3.0
chrome 59.0.3071.115
VVV2 dev environment
latest OSX macbook

**Comment by jasmussen** [comment]
A couple of things here:

- The revisions history can be vastly improved by being part of the new editor. But it's also likely out of scope for Gutenberg initially. 
- The problem describe sounds like it would likely be "solved" if/when the editor project gets merged in to become the default editor.

Good to make sure, though, that we'd get sent back to the right editor, though!

**Comment by mtias** [comment]
Related https://github.com/WordPress/gutenberg/issues/2166

**Comment by jasmussen** [comment]
Still an issue even with Gutenberg as default.

**Comment by aduth** [comment]
Should be fixed with #3511.

Same issue: #2808
