### ISSUE TITLE
Video block not converting to embed when pasting a link

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#17385]
Wordpress version: 5.3.3
Gutenberg version: 6.4
Browser: Chrome
OS: OSX Mojave 10.14.6

Whenever I paste in a youtube link (either the share link or the link in the url), the video block doesn't do anything. In the code it looks like it's supposed to convert to an embed block.

[https://recordit.co/2wOqmLXjda](https://recordit.co/2wOqmLXjda)

**Comment by Soean** [comment]
I tested a YouTube link in Gutenberg 6.4 and the Video block was converted into the YouTube block. Can you post an example link?

**Comment by myleshyson** [comment]
Ah ok. Its because we disabled the youtube block in our theme. closing this issue. thanks!
