### ISSUE TITLE
Widgets: list bullet points not showing up

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17391]
The bullet points seem to not work on the list block when a widget:

![image](https://user-images.githubusercontent.com/253067/64556705-e4650b00-d337-11e9-902a-1b2e85e3475d.png)

**Comment by noisysocks** [comment]
Strangely, it works for ordered lists.

**Comment by shaunandrews** [comment]
![widget-list-block](https://user-images.githubusercontent.com/191598/91314362-7aca5080-e784-11ea-914a-66bf28b44c1c.gif)

I'm able to reproduce this — it seems there's a `list-style: none;` coming from some `common.css` file that is rather aggressive and overriding the default list styling. Or, we're missing some block-related styles.

Worth noting that the general spacing around the block seems off when the ordered list numbers appear — they're far too close to the edge of the white container for the widget area.

**Comment by draganescu** [comment]
Trying to test this, now the block toolbar is stuck to the right side and I can't see all of it to switch between list styles.

**Comment by adamziel** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/25699
