### ISSUE TITLE
wp_set_script_translations prints the same JavaScript block for every script file

### ISSUE THREAD

**Issue by arjendejong12** [WordPress/gutenberg#17394]
Hey,

Gutenberg prints the following inline script before every Gutenberg .js file in the footer and all inline scripts are exactly the same. This has to do with `wp-i18n` being set as a dependency I guess.
```
<script type="text/javascript">
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>
```
Is there a way to only have it print once before the first Gutenberg .js file? Our server minifies and concatenates our scripts, but only consecutive scripts. As you may understand now, this doesn't work, becuase of the multiple inline scripts between the .js includes.

The following line is responsible: `gutenberg\lib\client-assets.php:96`.

**Comment by paaljoachim** [comment]
Hey @arjendejong12 Arjen

Thanks for opening this issue!
A lot of time has passed.
Is this issue still valid?

**Comment by arjendejong12** [comment]
@paaljoachim Good question. I will let you know soon.

**Comment by arjendejong12** [comment]
@paaljoachim This issue can be closed as it is no longer relevant. Thanks for bringing it up!
