### ISSUE TITLE
Multi-line titles should display on multiple lines

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1739]
![2017-07-05t16 59 04 0200](https://user-images.githubusercontent.com/227022/27870506-4e197526-61a3-11e7-8a46-7ca0f2d5e508.png)

**Comment by nylen** [comment]
Now that I refresh the page, I'm no longer seeing this issue.

**Comment by nylen** [comment]
This appears to be an edge case that is pretty dependent on specific title lengths and window widths.  I can consistently reproduce it on this post:

![2017-07-05t17 28 59 0200](https://user-images.githubusercontent.com/227022/27871926-7efc8440-61a7-11e7-88b1-5c68013b68f4.png)

The full title is `gutenberg-boilerplate-es5/hello-world`.

**Comment by aduth** [comment]
Are you still able to reproduce this? I have not observed this in recent usage.

**Comment by karmatosed** [comment]
Closing as part of triage, if this is still an issue please reopen.
