### ISSUE TITLE
Can't reorder blocks using drag & drop in block editor playground.

### ISSUE THREAD

**Issue by costasovo** [WordPress/gutenberg#17393]
**Describe the bug**
Can't reorder blocks using drag & drop in block editor playground.

**To reproduce**
1. Go to https://wordpress.github.io/gutenberg/
2. Add some blocks
3. Try to reorder blocks using drag & drop
4. Dragging starts but it is not possible to drop the block to a different place

**Expected behavior**
I'm able to use drag & drog to reorder blocks.

**Screenshots**
[Gif](https://d.pr/i/xQuJF7)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome, safari
 - Version 76.0.3809.132, 12.1.2

**Comment by costasovo** [comment]
@swissspidy This seems to be fixed. Probably by this PR https://github.com/WordPress/gutenberg/pull/15054

**Comment by swissspidy** [comment]
Then feel free to close it :-)
