### ISSUE TITLE
Editor warns of unsaved changes even if there are none

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#17395]
**Describe the bug**
With Gutenberg 6.4.0, the editor sometimes warns of unsaved changes when navigating away, even if all changes are saved. This happens with a clean installation and only e.g. a paragraph in the content.

**To reproduce**
1. Create a new post with some content (irrelevant which blocks) and schedule it.
2. Attempt to navigate away from the editor view.

**Expected behavior**
The navigation should happen with no warnings.

**Desktop (please complete the following information):**
 - OS: Windows and OSX
 - Browser: Chrome, Safari, Firefox
 - Version : various

**Comment by swissspidy** [comment]
I cannot seem to reproduce this in Gutenberg 6.5 / WordPress 5.3 Beta

**Comment by youknowriad** [comment]
yes, this was fixed by #17532
