### ISSUE TITLE
Dependency error when attempting to use `@wordpress/block-editor` in fresh react app 

### ISSUE THREAD

**Issue by ryaanwells** [WordPress/gutenberg#17396]
**Describe the bug**
Hello 👋 I am attempting to use the `@wordpress/block-editor` in a fresh react app and I am receiving the following error.

```
Failed to compile.

./node_modules/@wordpress/block-editor/build-module/components/rich-text/index.js
Attempted import error: 'LINE_SEPARATOR' is not exported from '@wordpress/rich-text'.
```

This is on a completely fresh-cut `npx create-react-app` using the latest version of `@wordpress/block-editor`.

**Versions**

Tool | Version
---- | --------
npx | 6.4.1
npm | 6.4.1
node | 10.13.0
react | 16.9.0
@wordpress/block-editor | 3.1.0

**To reproduce**
1. `npx create-react-app gutenberg-test`
2. `cd gutenberg-test`
3. Following [install instructions](https://www.npmjs.com/package/@wordpress/block-editor) `npm install @wordpress/block-editor --save`
4. Update `src/App.js` to:
```
import {
  BlockEditorProvider,
  BlockList
} from '@wordpress/block-editor';
import { useState } from '@wordpress/element';

function App() {
  const [ blocks, updateBlocks ] = useState( [] );
 
  return (
      <BlockEditorProvider
          value={ blocks }
          onInput={ updateBlocks }
          onChange={ updateBlocks }
      >
          <WritingFlow>
              <ObserveTyping>
                  <BlockList />
              </ObserveTyping>
          </WritingFlow>
          <Popover.Slot />
      </BlockEditorProvider>
  );
}

export default App;
```
5. `npm start`.

**Expected behavior**
Block editor to run in the react application.  

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
- [package-lock.json.txt](https://github.com/WordPress/gutenberg/files/3595197/package-lock.json.txt) attached (with .txt extension as GitHub doesn't allow direct attachments of .json!)

**Comment by karimkawambwa** [comment]
I ran into the same issue.
I did not dig too much but I found this in the change log:
> * Renamed `LINE_SEPARATOR` to `__UNSTABLE_LINE_SEPARATOR`

**Comment by ryaanwells** [comment]
Hi @ellatrix - thanks for updating here with the related PR 👍 

What's the release cadence of these NPM modules (when should I expect to be able to validate this fix)?

**Comment by ellatrix** [comment]
Every Gutenberg release I believe. Which should be... today I think. :)
