### ISSUE TITLE
Gutenberg block message

### ISSUE THREAD

**Issue by econscentric** [WordPress/gutenberg#17404]
Hi

I have this message for all the blocks I created It gave me this message this block contains invalid or unexpected content. I tried to press the resolve button and re-convert to block but is not helping to rectify the issue.

Page url: https://econscentric.com/wp-admin/post.php?post=553&action=edit

I dont know if the chrome extension Ginger is causing the issue as I can see the code class="ginger-module-highlighter-mistake-type-1" id="gwmw-15680146564750193184233">  in the source code (screenshot). I tried to remove the Chrome extension but the code is still there.  

![2019-09-10](https://user-images.githubusercontent.com/55173701/64669389-ef34b280-d493-11e9-94bf-fe5fc065931d.png)

I am worried. Can anyone help? 

Thanks

**Comment by swissspidy** [comment]
Please try  disabling the Chrome extension you mentioned and see if this persists.

If it does, I recommend posting in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/ to get further help.
