### ISSUE TITLE
Issue with WYSIWYG lists on UXP-based browsers.

### ISSUE THREAD

**Issue by wolfbeast** [WordPress/gutenberg#17412]
**Describe the bug**
WordPress 5.2.2 seems to have an issue with UXP-based browsers (Pale Moon, Basilisk) in that the WYSIWYG list editor (for bulleted lists) will erase the text from a bullet point when pressing enter (except the first character) and then does not advance to create another bullet point.

There are no errors in the browser consoles when this happens. 

**To reproduce**
1. Go to 'Edit post'
2. Click on 'Add block', select 'bulleted list'
3. Enter a list item and press enter

**Observed behavior**
The text of the bullet point is removed with the exception of the first character.
No new bullet point is created.

**Expected behavior**
A new bullet point is created.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Pale Moon, Basilisk.
 - Version 28.7.0, 2019.09.03

**Comment by JamesTheAwesomeDude** [comment]
This weekend, I'll attempt some debugging

being unfamiliar with both codebases, my current agenda is just to pull up both the UXP-based browser and Firefox in parallel, prepare to replicate the bug, activate the JS debugger, hit the newline; then just keep pressing "Step Into" alternately in each browser while keeping a sharp eye on the scope variables, and when they start to diverge I'll wing it from there

if anyone has any suggestions for how to optimize this process / hints for what to look at / where to add breakpoints / how to proceed once the divergence happens, I'm all ears.

**Comment by JamesTheAwesomeDude** [comment]
also, note that I can confirm this bug on WordPress 5.2.3 as well

I am not actually sure whether there _was_ any surely-working UXP+Gutenberg version matchup; if anyone reading this thread can chime in with confirmed working version pairings that'd be great.

**Comment by sebigbos61** [comment]
I´m just a user. I have the same bug using mypal, which is an adaptation of the palemoon browser to xp.
I can use newest version of wordpress/gutenberg (5.3.2) and the to palemoon 28.5.2 corresponding version of mypal without the bug appearing. Since version 28.6.0 the bug appears

**Comment by wolfbeast** [comment]
For the record, here are the release notes for v28.6.0 if that might help narrow down the issue:
http://www.palemoon.org/releasenotes-archived.shtml#v28.6.0

**Comment by wolfbeast** [comment]
We've narrowed it down ourselves to a rather obscure bug in JS array handling in the browser's JS engine that apparently only gets tickled by WordPress code. As such I no longer think this is, in fact, a bug in WordPress, but rather in the browser's code. The version where this started occurring as mentioned also aligns with the code changes that would have caused this bug. We're still investigating but it seems highly likely this issue can be closed as invalid.

**Comment by mtias** [comment]
@wolfbeast thanks for debugging there. If any issue still persist, feel free to reopen. Thanks!
