### ISSUE TITLE
Cannot use Drag libraries like react-dnd inside blocks.

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#17428]
**Describe the bug**
I run into this bug will working on a side project, it seems using drag & drop libraries like react-dnd is not possible inside blocks for some reason, the same code used outside Gutenberg seems to work.

Been trying to debug this for the past two days with no avail. 

For more info, here is a [prototype](https://codesandbox.io/embed/gutenberg-drag-example-4pi1f) with working dragging in React
Here is [a gist](https://gist.github.com/senadir/365c8f578acd64be85cbcf1c3c068d56) for the same code inside a block, the same code is used in the plugin
[this is a plugin to directly try, it register a new block called Tagging Block](https://github.com/WordPress/gutenberg/files/3610870/tagging-block.zip) or the[ code repo](https://github.com/senadir/taggable-image-block/tree/bugging-the-bug)

**To reproduce**
- use the provided code or plugin to install a block that has drag ability
- try to drag
- doesn't work

**Expected behavior**
Dragging should work

**Screenshots**
#### inside Gutenberg
![cannotDrag](https://user-images.githubusercontent.com/6165348/64878474-87c16300-d64b-11e9-9c0a-ab71c4c380f5.gif)

#### outside Gutenberg
![canDrag](https://user-images.githubusercontent.com/6165348/64879099-197da000-d64d-11e9-81c8-d83819d46e2b.gif)

**Desktop:**
 - OS: OSX
 - Browser: Chrome
 - Version: 77

**Additional context**
- Gutenberg: master
- WordPress: latest

**Comment by senadir** [comment]
I'm not sure if I should close this or not, using react-draggable worked, so I guess it's a conflict with react-dnd core and not dragging in general

**Comment by danieliser** [comment]
@senadir - I wonder if its dependency overlap. WP includes custom versions of react, redux etc. React-DnD also uses those but explicitly the normal versions which would end up bundled with your code as well.

**Comment by Jackky90** [comment]
Any workarounds? Stuck with similar task: want to implement DnD reorder UI inside elements of a block. Using `react-sortablejs` and it's work great with `InspectorControls` context, but absolutely won't work inside block itself.

**Comment by danieliser** [comment]
@Jackky90 Can you run debugger or console to see if the different drag actions are actually occurring on the block? Haven't used it in that context, but much of our issues of it not working in various scenarios came from how we were manipulating & storing the state of the DnD list. SortableJS adds and removes quite a few properties to each object over time. We had to adjust validation mechanisms to allow for those properties as it would strip them out and nothing would work.

**Comment by Jackky90** [comment]
@danieliser ah, sorry, absolutely forgot to mention strange detail: there are no errors (or, even, warnings) thrown in console. One of the reason I simply don't know which way to look to make this work.

**Comment by danieliser** [comment]
@Jackky90 - You will likely need to add some extra listeners to your React SortableJS component to dump to console for debugging.

I can't say for certain that within a block it will work, but I can say we use it in a infinitely nestable scenario (which the documentation says isn't doable in React 18), and it works perfectly fine. So assuming your using `wp-scripts` and there isn't some other conflict, it might just be weirdness in how block data is handled.

Honestly I'm not sure what to tell you as package handling in this scenario can be a bit unreliable due to loading many of them from wp assets and some from your bundled files.
