### ISSUE TITLE
Icon buttons on the Top Toolbar has black border when clicked on twice

### ISSUE THREAD

**Issue by ravenstewart** [WordPress/gutenberg#17425]
**Describe the bug**
Buttons with icons on the Top Toolbar starts off with no border.  If you click on any of the icon buttons and then click on them again a black border will show up on the button.  This makes the button no longer match the rest of the buttons on the Top Toolbar until you click elsewhere.

**To reproduce**
1. Look at the Top Toolbar buttons on a fresh page, notice none of the buttons have a black border.
2. Click on any button with an icon on it in the Top Toolbar
3. Click on the same button again.
4. Notice a black border is now on the button that was clicked on
7. Click somewhere not on that button
8. Notice the black border is now gone.

**Expected behavior**
I expect no black border to appear on the button.

**Screenshots**

**How the button looks after you click on it twice**
![black_border](https://user-images.githubusercontent.com/54042392/64836932-bdb20900-d5b1-11e9-8f6e-5cc9d8a56faa.png)

**How the button should look**
![normal](https://user-images.githubusercontent.com/54042392/64837001-08cc1c00-d5b2-11e9-81e9-d8f31aff5d53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Google Chrome Version 76.0.3809.132
 - Gutenberg Version 6.4.0

**Comment by ravenstewart** [comment]
I modified the issue description and title because I noticed that this actually happens with all the icon buttons on the Top Toolbar.

**Comment by youknowriad** [comment]
This is working as expected, that's just the "focus" style of the button which is important for a11y reasons.

**Comment by ravenstewart** [comment]
Ah. That's good to know.  Thank you for clarifying!
