### ISSUE TITLE
Updating the title loses the Permalink editing until you move focus to another block and come back

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#17430]
**Describe the bug**
When updating a post title often you want to also update the permalink. It's nice that the permalink appears above the title when you initially focus on the title, but as soon as you start typing it vanishes and the only want to have it re-appear is change the focus to a block and then come back to the title.

**To reproduce**
1. Go to a post with Gutenberg
2. Click on the title, notice the permalink editor appears above.
3. Enter some text, note the permalink editor vanishes.
4. To get it to return you need to go to another block and then back to the title.

**Expected behavior**
It would be nice to have the permalink editor stay persistently while typing so once you've changed the title it is an easy thing to then update the permalink.

**Screenshots**
![69d7710efe27957123f1bea2b972871b](https://user-images.githubusercontent.com/8726005/64883732-eae3d300-d614-11e9-8ea0-716cc824a5f6.gif)

**Desktop (please complete the following information):**
 - OS: Mac 10.14.5
 - Browser: Chrome 76.0.3809.132

**Additional context**
- Gutenberg Core for WordPress 5.2.3

**Comment by youknowriad** [comment]
This UI has been removed in favor of the permalink sidebar panel. Thanks
