### ISSUE TITLE
Increase Coverage of Undo/History E2E Tests

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#17434]
To catch regressions like the ones fixed in #17420 and #17259.

**Comment by mcsf** [comment]
@epiqueras would be great to prioritise this one.

**Comment by epiqueras** [comment]
@mcsf Me and @ellatrix have been working on it:

https://github.com/WordPress/gutenberg/commits/d79a8400aa6308c8e2367406c473721bf3ba347f/packages/e2e-tests/specs/undo.test.js

**Comment by mcsf** [comment]
@epiqueras, could you revisit this? I'd like to be able to close the issue soonish. 🙏

**Comment by epiqueras** [comment]
I think we're good to close now right @ellatrix ?

I've also made some improvements to the change detection tests.

**Comment by ellatrix** [comment]
We certainly have more e2e tests, but there's still no unit tests for the `undo` reducer at all. We used to have unit tests for `withHistory`, and any new reducer should ideally be introduced together with some unit tests. Without unit tests, it's hard for anyone else to work on the code. https://github.com/WordPress/gutenberg/blob/0552712059ac5519fad0aeab6dddc5b84f049192/packages/core-data/src/test/reducer.js

**Comment by mcsf** [comment]
Agreed, we still need this issue.
