### ISSUE TITLE
Block save function wrapping innerBlocks

### ISSUE THREAD

**Issue by mmaarten** [WordPress/gutenberg#17438]
I would like to access inner blocks data to wrap html around each block.

I noticed that during the block save process the `props.innerBlocks` is filled with block data.
But when the editor page reloads the `props.innerBlocks` is empty.

    const CarouselSave = ( { ...props } ) => {

      const { attributes, className, innerBlocks } = props;
      
    };

Is there an alternate way to the data of the inner blocks?

below the block save method:

    import {
      __,
    } from '@wordpress/i18n';
    import {
      Component,
    } from '@wordpress/element';
    import {
      getSaveElement,
    } from '@wordpress/blocks';
    import {
      select,
    } from '@wordpress/data';
    import {
      isEmpty,
    } from 'lodash';
    import
      classnames
      from 'classnames';

    const ACTIVE_INDEX = 0;

    const CarouselSave = ( { ...props } ) => {

      const { attributes, className, innerBlocks } = props;
      const { id, controls, indicators, autoplay } = attributes;

      return ! isEmpty( innerBlocks ) && (

        <div className={ className }>

          <div
           className="carousel slide"
           id={ id }
           { ...{ 'data-ride' : autoplay ? 'carousel' : undefined } }
           >

            <div className="carousel-inner">

              { innerBlocks.map( ( block, index ) => {

                const itemClasses = classnames( {
                  'carousel-item' : true,
                  'active' : ACTIVE_INDEX === index,
                } );

                return (
                  <div key={ index } className={ itemClasses }>
                    { getSaveElement( block.name, block.attributes, block.innerBlocks ) }
                  </div>
                );

              } ) }

            </div>

          </div>
          
        </div>
      );
    };

export default CarouselSave;

**Comment by mmaarten** [comment]
To be more precise:

I am making a carousel block type which uses inner blocks for the items.
The idea is that the user can choose between different types of items (block types). e.g. core/image, core/cover, … or a custom one.

Inside the save function I need to wrap each inner block inside a `<div class="item"></div>` element. Can't be done with: `<Innerblocks.Content />`

## Access to inner blocks in save function

I noticed that this method is called in two ways:

### 1. during editor save/update.

`props.innerBlocks` is filled with the inner blocks data.

### 2. during editor load.
comparison is made between the **Content generated by save function** and **Content retrieved from post body**.

`props.innerBlocks` is an empty array.

### Searching for an alternative…

In my **edit function** I store the inner blocks inside an attribute (items) so i can access them in the save function.

Finally I loop through each item (inner block) and found the `getBlockContent` method to return the html content for a specific block.

Everything seems to work fine but not when those inner blocks has also inner blocks. like the core/cover block type.

During the *during editor load* i get following error:

## Issue

Content generated by `save` function:

    <div class="wp-block-my-blocks-carousel">
        <div class="item">
            <div class="wp-block-cover has-background-dim" style="background-image:url(http://wordpress.local/wp-content/uploads/2019/07/adventure-calm-clouds-414171.jpg)">
                <div class="wp-block-cover__inner-container">
                    
                    <p style="text-align:center" class="has-large-font-size">Paragraph</p>
                    
                </div>
            </div>
        </div>
    </div>

Content retrieved from post body:

    <div class="wp-block-my-blocks-carousel">
        <div class="item">
            <div class="wp-block-cover has-background-dim" style="background-image:url(http://wordpress.local/wp-content/uploads/2019/07/adventure-calm-clouds-414171.jpg)">
                <div class="wp-block-cover__inner-container"></div>
            </div>
        </div>
    </div>

## Edit Component
 
    import {
      __,
    } from '@wordpress/i18n';
    import {
      Component,
    } from '@wordpress/element';
    import {
      InnerBlocks,
    } from '@wordpress/block-editor';
    import {
      withSelect,
    } from '@wordpress/data';
    import {
      compose
    } from '@wordpress/compose';

    const ALLOWED_BLOCKS = [ 'core/image', 'core/cover' ];
    const DEFAULT_TEMPLATE = [ [ 'core/cover' ] ]
    const UPDATE_INTERVAL = 1000;

    class CarouselEdit extends Component {

      constructor() {
        super( ...arguments );

        this.updateInterval = null;
        this.update = this.update.bind( this );

        // Set inner blocks template.
        this.template = DEFAULT_TEMPLATE;
        if ( this.props.attributes.items.length ) {
          this.template = this.getTemplate( this.props.attributes.items );
        }
      }

      componentDidMount() {
        // Set update interval.
        this.updateInterval = setInterval( this.update, UPDATE_INTERVAL );
      }

      componentWillUnmount() {
        // Clear interval.
        clearInterval( this.updateInterval );
      }

      getTemplate( blocks ) {
        return blocks.map( ( block ) => {
          return [ block.name, block.attributes, this.getTemplate( block.innerBlocks ) ];
        } );
      }

      update() {
        console.log( 'update' );

        this.props.updateItems();
      }

      render() {

        const { attributes, className } = this.props;

        return (
          <div className={ className }>
            <InnerBlocks
             allowedBlocks={ ALLOWED_BLOCKS }
             template={ this.template }
            />
          </div>
        );
      }
    }

    export default compose( [
      withSelect( ( select, ownProps ) => {
        const { getBlock, getBlocks } = select( 'core/editor' );

        return {
          block : getBlock( ownProps.clientId ),
          // Store inner blocks inside 'items' attribute.
          updateItems() {
            const innerBlocks = getBlocks( ownProps.clientId );
            if ( JSON.stringify( ownProps.attributes.items ) !== JSON.stringify( innerBlocks ) ) {
              ownProps.setAttributes( { items : [ ...innerBlocks ] } );
            }
          },
        };
      }),
    ] )( CarouselEdit );




## Save function

    import {
      __,
    } from '@wordpress/i18n';
    import {
      InnerBlocks,
    } from '@wordpress/block-editor';
    import {
      RawHTML,
    } from '@wordpress/element';
    import {
      getBlockContent,
    } from '@wordpress/blocks';

    const CarouselSave = ( { ...props } ) => {

      const { attributes, className } = props;
      const { items } = attributes;

      return (
        <div className={ className }>
          { items.map( ( innerBlock, index ) => {
            const itemContent = getBlockContent( innerBlock );
            return (
              <div key={ index } className="item">
               <RawHTML>{ itemContent }</RawHTML>
              </div>
            );
          } ) }
        </div>
      );
    };

    export default CarouselSave;

**Comment by mediacs** [comment]
I'm experiencing the same issue. Any luck yet with solving the problem?

**Comment by talldan** [comment]
@mmaarten @mediacs I would consider solving this in a blocky way, by creating a new blocks `CarouselItemImage` and `CarouselItemCover`. These could be implemented with your wrapper and use the InnerBlocks template prop to ensure they only contain the desired block:
```
<div class="item">
    <InnerBlocks template={ [ 'core/image', {} ] } templateLock="all" />
</div>
```

You could probably write a function that generates these inner blocks:
```
function createCarouselInnerBlocks( innerBlocksConfig ) {
    return blockNames.map( ( { templatedBlockName, title, etc.. } ) => {
        return {
            title,
            edit: () => {
                // ...
                return (
                    <div class="item">
                        <InnerBlocks template={ [ templatedBlockName, {} ] } templateLock="all" />
                    </div>
               ),
           },
           save: ...
    } );
}
```
