### ISSUE TITLE
de_DE_formal translations are not shown.

### ISSUE THREAD

**Issue by Furo42** [WordPress/gutenberg#17448]
**Describe the bug**
If you're using the language `de_DE_formal` and Gutenberg plugin most of the strings are not translated. The language files `gutenberg-de_DE_formal.po` and `gutenberg-de_DE_formal.mo` were automatically downloaded but there are no `*.json`files in `wp-content/languages/plugin/` with the prefix `gutenberg-de_DE_formal`.
The missing translationes are available in the `*.po`-file, for e.g. the string `Status & Visibility` should be translated to `Status und Sichtbarkeit`.
If you're using just `de_DE` as language it works fine.

for further information you can read [this](https://github.com/roots/bedrock/issues/438). **Attention**: This is bug is **not** related to Bedrock. It also appears in a default WordPress installation.

**To reproduce**
1. Install Gutenberg
2. Go to Settings and change the Website's language to `Deutsch (Sie)` (this is `de_DE_formal`)
3. Create a new post or edit an existing one.
4. See error: Most of the strings are in english.

**Expected behavior**
Strings like "Status & Visibility" should be translated to German.

**Screenshots**
![gutenberg_translations](https://user-images.githubusercontent.com/51162201/64941147-20332f80-d866-11e9-98ec-88ed87159b25.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome v77, Firefox v69

**Additional context**
- Gutenberg v6.4.0

**Comment by swissspidy** [comment]
The [de_DE_formal translation](https://translate.wordpress.org/locale/de/formal/wp-plugins/gutenberg/) of Gutenberg is only 62% percent complete. Language packs are only built when they are at >= 95%. Once the translations are complete, it should work as expected.
