### ISSUE TITLE
SelectControl will not store "number" attribute type

### ISSUE THREAD

**Issue by iamleese** [WordPress/gutenberg#17441]
It appears that the SelectControl component will not save the 'number' attribute type. 

I've registered an attribute that has a data type of "number" which is set through the SelectControl component:

```
attributes: {
      myorder : {
          'type' : 'number',
      }
},

edit: function ( props ) {
		
		const {attributes, setAttributes} = props;
		
		const MySelectControl = withState( {
				order: '1',
			} )( ( { order, setState } ) => (
				<SelectControl
					label="Order"
					value={ attributes.myorder }
					options={ [
						{ label: 'First', value: '1' },
						{ label: 'Second', value: '2' },
						{ label: 'Third', value: '3' },
					] }
					onChange={ ( order ) => { setState( { order } ), setAttributes( { myorder : order } ) } }
				/>
			) );
				
		return (
			<div className={ props.className }>
				<p>Select an Order</p>
				<MySelectControl />
			</div>
		);
	},
```

When the page is saved/published the attribute appears to be saved in the in the code editor. 

```
<!-- wp:cgb/block-fim-test {"myorder":"2"} -->
<div class="wp-block-cgb-block-fim-test"></div>
<!-- /wp:cgb/block-fim-test -->
```

But once the page is refreshed, the attribute disappears.

However, if I change the attribute type to "string"
```
attributes: {
       myorder : {
           'type' : 'string',
	 }
},
```

It saves properly and the data is available once the page is refreshed.

**Comment by talldan** [comment]
@iamleese You can use a `number` attribute type, but there's no automatic conversion of types, so you'll need to make sure you convert types explicitly when calling setAttribute... e.g.:
```
setAttributes( { myorder: parseInt( value, 10 ) } );
```

**Comment by iamleese** [comment]
Got it — good to know.

I'm new to React and learning as I'm going so I'm not sure that it's a Gutenberg issue or a React issue. It kind of defeats the purpose of declaring it a 'number'  if you still have to convert it. It seems that the validation would be to check if it's NaN — at least that's what the documentation suggests.
