### ISSUE TITLE
An alternative to ReactSelect

### ISSUE THREAD

**Issue by daext** [WordPress/gutenberg#17443]
Can you please confirm that there isn't native Gutenberg solution to handle a select box with a high number of item? Would it be possible to add this component to Gutenberg?

ReactSelect: https://github.com/JedWatson/react-select

**Comment by chrisvanpatten** [comment]
Hi @daext - 

There is currently no great native Gutenberg solution for this use-case. The [Autocomplete](https://developer.wordpress.org/block-editor/components/autocomplete/) component is one option but it's not strictly a "select" box in the conventional sense.

You might also be interested in the discussions happening in #7384, #7385, and #16666. There are a lot of accessibility barriers to this type of component, and while it's still being explored you might find it easier to bundle `react-select` or a similar component in your own project, if it meets your specific use-case.

As this is not strictly a bug, I'm going to close this issue but would definitely recommend reading the comments in the tickets I linked to above. Thanks!
