### ISSUE TITLE
Follow-up work for the Block Directory

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#17440]
We opted to merge https://github.com/WordPress/gutenberg/pull/17431 behind an experimental flag with some outstanding issues, listed here:

- [x] [API: Make it more "RESTful"](https://github.com/WordPress/gutenberg/pull/16524/files#r324215213)
- [x] API: Ensure the directory respects `canInsertBlockType`, (e.g. when the selected block has a template lock like the column block does, or only specific child blocks are allowed).
- [x] [UI: Consider removing 'with an average rating of 0' copy](https://github.com/WordPress/gutenberg/pull/16524/files#r324271407)
- [x] [A11y: Determine better alt text for block icons](https://github.com/WordPress/gutenberg/pull/16524/files#r324268820)
- [x] [A11y: Improve 'Add' button copy](https://github.com/WordPress/gutenberg/pull/16524/files#r324217233)
- [x] [UI: Consider alt text for icons in search results](https://github.com/WordPress/gutenberg/pull/16524/files#r324222681) 
- [x] [UI: Fix `onMouseEnter`/`onMouseLeave`](https://github.com/WordPress/gutenberg/pull/16524/files#r324258927)
- [x] [UI: Use inline notices](https://github.com/WordPress/gutenberg/pull/16524/files#r324259260)
- [ ] [Refactor: Replace `Slot/Fill` with a more useful abstraction](https://github.com/WordPress/gutenberg/pull/16524/files#r324238286)
- [x] [Refactor: Split reducer into seperate reducers](https://github.com/WordPress/gutenberg/pull/16524/files#r324233060)
- [x] [API: Use `canUse` to check permissions](https://github.com/WordPress/gutenberg/pull/16524/files#r315493053)
- [x] [Insertion: Make `loadScript` async](https://github.com/WordPress/gutenberg/pull/16524/files#r324244982) 
- [x] [Insertion: Double check handling of `object` form](https://github.com/WordPress/gutenberg/pull/16524/files#r324255408)
- [x] [Insertion: Clarify `0` in `resolve( 0 )`](https://github.com/WordPress/gutenberg/pull/16524/files#r324247341)
- [x] [Refactor: Move uninstallation code to own component](https://github.com/WordPress/gutenberg/pull/16524/files#r324226685)
- [x] [API: Use `new WP_Error`](https://github.com/WordPress/gutenberg/pull/17431#issuecomment-531407485)
- [x] [Insertion: Fix handling of script dependencies](https://github.com/WordPress/gutenberg/pull/17431#discussion_r324346211)
- [x] [Flags: Add tree shaking](https://github.com/WordPress/gutenberg/pull/17431#discussion_r324425057)
- [x] Tests: Add E2E tests for the Block Directory flow 
- [x] Tests: Add unit tests for the selectors, actions, reducers, etc.
- [x] Tests: Add unit tests for the new API controller

cc. @tellyworth @dd32 @talldan @ck-lee

**Comment by StevenDufresne** [comment]
Just noting that I'm checking the boxes for items represented elsewhere in a PR or another issue with the aim of closing this out. 🧹

**Comment by StevenDufresne** [comment]
I'm closing this issue since everything that is directly related to the original PR is completed save for the Slot/Fill abstraction which is not specific to the block directory and the source code has been refactored a few times already.
