### ISSUE TITLE
Dynamic/Generated Google Font URL Embed in registerFormatType

### ISSUE THREAD

**Issue by sudheer-ranga** [WordPress/gutenberg#17442]
**What am I building?**
I am creating a custom format called typography which helps in choosing google fonts.

```
const { registerFormatType, applyFormat } = wp.richText;
import _ from 'lodash';

import { __ } from '@wordpress/i18n';
import { Fragment } from '@wordpress/element';

import { InspectorControls } from '@wordpress/editor';
import { PanelBody, SelectControl } from '@wordpress/components';

import googleFonts from './google-fonts';

const name = 'my-custom-format/typography';
const title = __('My Typography');

const MyTypography = props => {
  const { value, onChange, isActive, activeAttributes } = props;
  let activeFontFamily = '';

  console.log('rendering');

  const addGoogleFontToHead = (fontFamily, fontObject) => {
    if (!fontFamily || !fontObject) {
      return;
    }

    const head = document.head;
    const link = document.createElement('link');

    link.type = 'text/css';
    link.rel = 'stylesheet';
    link.href =
      'https://fonts.googleapis.com/css?family=' +
      fontFamily.replace(/\s+/g, '+') +
      ':' +
      fontObject.variants.join(',');

    head.appendChild(link);
  };

  if (isActive) {
    const style = activeAttributes.style;
    activeFontFamily =
      (style && style.replace(new RegExp(`^font-family:\\s*`), '')) || '';

    let fontObject = _.find(googleFonts, ['value', activeFontFamily]);

    addGoogleFontToHead(activeFontFamily, fontObject);
  }

  return (
    <Fragment>
      <InspectorControls key="inspector">
        <PanelBody title={title} initialOpen={true}>
          <SelectControl
            label="Font Family"
            value={activeFontFamily}
            options={googleFonts}
            onChange={font => {
              let startIndex = 0;
              let endIndex = value.text.length;

              onChange(
                applyFormat(
                  value,
                  {
                    type: name,
                    attributes: {
                      style: `font-family: ${font}`
                    }
                  },
                  startIndex,
                  endIndex
                )
              );
            }}
          />
        </PanelBody>
      </InspectorControls>
    </Fragment>
  );
};

registerFormatType(name, {
  title,
  tagName: 'span',
  className: 'my-typography',
  attributes: {
    family: 'data-family',
    variant: 'data-variant'
  },
  edit: MyTypography
});
```

The above code works fine when I add new block and choose a google font. The `addGoogleFontToHead()` gets executed and the google font URL is added to head. Here is the screenshot.
![](https://i.ibb.co/k0crJHt/Screenshot-2019-09-15-at-2-49-27-AM.png)

**Problem**
However, when I reload the editor default fonts are shown. This is because the google font URL is not added to head as the block's `settings.edit` doesn't get executed during load.
![](https://i.ibb.co/VVYTT63/default.png)

If I click on each individual block, the block gets executed and the `addGoogleFontToHead()` gets executed which will set the google fonts URL in the head properly and the font is displayed.
![](https://i.ibb.co/q71Yjtb/block.png)

As I said, the `console.log('rendering');` statement in the above code gets triggered only when I click on the particular block.

**How can I load the google fonts URL when the editor loads?**

**Comment by swissspidy** [comment]
> How can I load the google fonts URL when the editor loads?

My suggestion would be to do something like this:

1. Wait until editor has loaded
2. Go through all blocks
3. For every block, get the formats / font definitions
4. Load stylesheet for that particular font

You could also look into using `subscribe()` to listen for any newly added blacks (e.g. from pasting or block conversion) to load the stylesheets there as well.

Ps. Please note that technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. You may also ask for technical support at https://wordpress.stackexchange.com/.

**Comment by sudheer-ranga** [comment]
Thank you for the reply @swissspidy 

Another quick question. Is there any WordPress hook that I can use which triggers a callback when blocks are loaded into the editor when the page loads?

What I mean is:

- When the post page loads, each block is loaded individually.
- Use some WordPress hook that will trigger a callback function when each block is loaded. If there are 2 paragraph blocks loaded into the editor then we get 2 callbacks.

**Comment by swissspidy** [comment]
No, such a specific hook doesn't exist.
