### ISSUE TITLE
Build Tooling: Further improve asset file produced by Webpack for each entry point

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17454]
In #17298 we started to generate asset files for the WordPress packages in PHP format with the list of all dependencies and stable version for each file which updates when it's source code changes.

There are some follow-up tasks which we can work on to further improve developer experience as summarized by @nerrad in https://github.com/WordPress/gutenberg/pull/17298#pullrequestreview-288564652:

> Summarizing what can be iterated on in future pulls:
> 
> - [x] flagging what assets have translations (likely can be done by detecting `@wordpress/i18n` as a dependency)
> - [x] generating/returning the handle to use for registering the asset (essentially that is already the case for the dependency arrays)
> - [x] potentially introducing a new asset php api for registering assets using these generated files (`wp_register_asset`?).

**Comment by jrchamp** [comment]
The asset file produced doesn't appear to generate all dependencies when using the `wp.data` and other globals as described in the documentation. #17423

**Comment by gziolo** [comment]
We can close it now since all those points were resolved in WordPress core and the last item is going to be tackled separately.
