### ISSUE TITLE
Filtering an existing block's inspector control

### ISSUE THREAD

**Issue by minhruhr** [WordPress/gutenberg#17457]
Hi,
I'm looking for a proper way to change the "max" attribute of a RangeControl from an existing block (not mine).

I've already looked into `wp.hooks.addFilter('blocks.registerBlockType',...)` and `wp.hooks.addFilter('editor.BlockEdit',...)` but the first one only let me edit the settings of the block, and the second one, I've only found example showing how to add new custom control, not altering an existing one.
I feel like the right direction is with editor.BlockEdit but I can't get how to do that.

So far, I've only managed to write a work-around script to change on the fly the max attribute of my RangeControl with an onclick event on the panel whenever this one is-opened.

**Comment by swissspidy** [comment]
I don't think that's currently possible

**Comment by youknowriad** [comment]
Hi there!

That's only possible if the block author provides the given filter. We're very reluctant to add such filters in Core block though because of the maintenance cost and the inconsistent experience it could create if these hooks are abused.
