### ISSUE TITLE
Be consistent about case in settings

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1745]
We have some inconsistencies in our naming. For example:

'Pending review' and 'Post Format'. See here:

![2017-07-05 at 18 08](https://user-images.githubusercontent.com/253067/27875989-2f35c2ea-61ad-11e7-9370-c570d1ca1e30.png)

**Comment by karmatosed** [comment]
There are a few of these so once we decide a to case of not, a PR can be made to catch all.

**Comment by hedgefield** [comment]
Stopping by to say I'd prefer Caps on the first word only.

**Comment by ahmadawais** [comment]
My vote goes to Title Case.
