### ISSUE TITLE
Hiding/collapsing RichText formatting controls

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#17462]
**Is your feature request related to a problem? Please describe.**
https://github.com/WordPress/gutenberg/pull/14542 deprecated `formattingControls` prop from `RichText`. 

My use case for this prop was to add `formattingControls={[]}` to inputs that are opinionated and should rarely need formatting, but the freedom to do so remained with hotkeys.

Example: A custom button block that inherits font-weight from theme options. By default the button text is bold, so displaying the `Bold` control on the toolbar is not relevant. But if the theme is configured to not use bold, then being able to `Ctrl + B` when needed would be possible.
`Italic` in a button is rarely desirable, so displaying the control on the toolbar is just adding visual clutter, but in the edge case that it's needed `Ctrl + I` could do the job.
A button can have a link, so mine contains the control for it on the toolbar. But without `formattingControls={[]}` a Rich Text inline-link control is also displayed, uses the same icon, and is very rarely needed, and could be used unknowingly if it's prominently displayed, making the button text a link, but not the actual button. In the edge case that it is actually needed (for multiple links in a button or what ever), `Ctrl + K` could do the job and wouldn't break this particular block.
With the new `allowedFormats` prop I don't have the control to just hide the formats while still keeping them available.

**Describe the solution you'd like**
While `formattingControls={[]}` was not ideal since it hides the controls completely and beginner users may not know it's possible to format, deprecating it also removes the ability to cherry pick the most relevant formats for the toolbar. I don't think it should be removed.

Being able to tuck away all the controls for opinionated inputs would be ideal:
![image](https://user-images.githubusercontent.com/6892634/65014062-0eb15c80-d926-11e9-94f9-e2b92a416169.png)
Making all of them available but not prominent, `formattingControls='compact'` if you will.

Instead of a whitelist `allowedFormats` prop, a blacklist `disallowedFormats` prop would make more sense for completely disabling formats that are known to break the block.
To disable a format using `allowedFormats` you would need to extensively list every format except the one you want to disable and this would also disallow 3rd party formats unless you use some sort of query to fetch all the registered ones and then filter out the one you want to disable. Seems like a lot of work for disabling 1 format. Or you just allow some formats that you think are right and make the block very limited in terms of edge cases.

**Comment by paaljoachim** [comment]
Hey @ktmn 

Thanks for creating the issue!
I see it has been overlooked.
Is the issue still valid?

**Comment by ktmn** [comment]
I'm not sure, is there a way to hide rich text controls from the toolbar while still keeping the hotkeys now? I haven't kept up with the RichText component developments.

You used to be able to do it, now you can't (as far as I know), so it's a regression. If it's an acceptable regression feel free to close.

**Comment by paaljoachim** [comment]
I really do not know. 
@gwwar Kerry. Perhaps you can check?

**Comment by gwwar** [comment]
> I'm not sure, is there a way to hide rich text controls from the toolbar while still keeping the hotkeys now?

I'm not sure either about the hotkeys.

Overall this feature request is valid, but we'd need to ping owners of the rich-text component to see what they think. I suspect folks may prefer the whitelist.

For what it's worth, `formattingControls` is deprecated, but I also don't see a target version for it being removed in code. This likely means it may remain for quite a while for backwards compatibility support. 

> unless you use some sort of query to fetch all the registered ones and then filter out the one you want to disable.

All registered formats are available in the 'core/rich-text' store. Passing in everything but the item we'd want to disable is possible, but a little clunky. Let me know if you need a more detailed sample if you're unfamiliar with the data stores.

<img width="756" alt="Screen Shot 2021-02-24 at 7 49 03 AM" src="https://user-images.githubusercontent.com/1270189/109026795-f8f4aa80-7674-11eb-8ace-5e6089f44ed3.png">

We also have the ability to completely unregister a format by calling `unregisterFormatType`, but that might be overkill for certain scenarios.

https://github.com/WordPress/gutenberg/blob/0a91d2bb07b454f446b0e90c4aa39e2478457364/packages/rich-text/src/unregister-format-type.js#L22-L33

**Comment by skorasaurus** [comment]
Thanks for reporting; this was also requested in https://github.com/WordPress/gutenberg/issues/28841 and you can follow its progress in that issue.
