### ISSUE TITLE
[Performance] don't fetch images from the REST API that were already added to the post.

### ISSUE THREAD

**Issue by omarreiss** [WordPress/gutenberg#17465]
**Describe the bug**

At Yoast we have an intranet site running on managed hosting. We have one post with about 100 images. When we load the page with Gutenberg 6.4, the server crashes, due to 100 REST API calls being fired at it for each image. When I check the network tab, I see Gutenberg calls  `/wp-json/wp/v2/media/{attachment_id}?context=edit&_locale=user` for each image. That is a huge performance issue. Since the url is already in the attributes of the `core/image` I don't see why the editor should need to do these calls.

**To reproduce**
1. Open your network tab.
2. Open a post with multiple images.
3. See Gutenberg do these calls.

**Expected behavior**

Fetch the images directly.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 76

**Additional context**
- Gutenberg version: 6.4

**Comment by epiqueras** [comment]
I think this does the trick: #17504
