### ISSUE TITLE
Several overlapping objects on first visit

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#17468]
**Describe the bug**
When visiting a Gutenberg page for the first time, the user is confronted with a popover that starts with "Welcome to the wonderful world of blocks..." and a nux-dot that overlaps a button that has a tool-tip, and all of them combined together looks a hot mess.

The bug here, is that it is possible for 1 single button to have 3 things hovering around it at the same time. It's distracting. It's unpretty. It does not make the world of blocks feel wonderful.

**To reproduce**
1. Go to "New Post" on a fresh installation of WordPress
2. Hover over the "Add block" button

**Expected behavior**
I expect for things that have popovers and nux-dots to be inaccessible until the popover is acknowledged, or that hovering over the button to hide the popover, or that clicking anywhere outside of the popover to hide it, or for none of this distracting stuff to even exist in the first place.

**Screenshots**
<img width="117" alt="Screen Shot 2019-09-17 at 4 53 57 PM" src="https://user-images.githubusercontent.com/88951/65082951-d41ee280-d96c-11e9-9dd2-8db469b4d7bf.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari (any will do)
 - Version: Version 13.0.1 (15608.2.11.1.1)

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
