### ISSUE TITLE
wordpress/scripts env unmounts plugin after e2e test run

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#17464]
**Describe the bug**
Every time I run the `wp-scripts test-e2e` command my local environment setup with `wp-scripts env install` looses the mounted plugin folder.

**To reproduce**
1. Create a new WordPress Plugin
2. Install the `@WordPress/scripts` and `@WordPress/e2e-test-utills` packages
3. Install the local env using `wp-scripts env install`
4. Write a simple e2e test
5. Run that test using the `wp-scripts test-e2e` command.
6. Go to the admin page of the local site and navigate to the plugin screen
7. The Plugin files will be missing

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - @WordPress/scripts 4.1.0 & 5.0.0

**Comment by gziolo** [comment]
I don’t think it is an issue anymore after pretest-e2e command was removed. It caused the whole env to be recreated from scratch leading to the issues you described. Let’s close it. We can reopen if we detect some similar issues in the future.
