### ISSUE TITLE
Using MediaPlaceholder as a separate package not working.

### ISSUE THREAD

**Issue by muhammedmagdi** [WordPress/gutenberg#17473]
I am building a simple WordPress admin page with React. I wanted to use MediaPlaceholder component in Gutenberg so I installed "@wordpress/block-editor" package and started to use MediaPlaceholder component but it always gives me one result: To edit this block, you need permission to upload media.
How to fix this?

**Comment by muhammedmagdi** [comment]
It seems for me that hasUploadPermissions is always returning false.
Main problem I think at canUser('create', 'media') returning false always. I don't know why.
At posts and pages, Media blocks works well. but in custom screens, it doesn't.

**Comment by muhammedmagdi** [comment]
@gziolo @youknowriad  @aduth  Is there any way to solve this?

**Comment by HardeepAsrani** [comment]
Seems like you can't use `wp.data.select` in non-Gutenberg pages. Everything is empty, even when `wp-data` package is added as a dependency. Weird.

**Comment by muhammedmagdi** [comment]
@HardeepAsrani Yes, that's also so weird!

**Comment by muhammedmagdi** [comment]
I am closing this as I solved it.

**Comment by abaicus** [comment]
Hey @muhammedmagdi!

Can you please share the way you managed to work around this? 

Thanks!

**Comment by muhammedmagdi** [comment]
@abaicus 
Sorry for the delay. 
I just installed WordPress Media Utils
`npm install @wordpress/media-utils`
and then I used it easily like that:
`import { MediaUpload } from "@wordpress/media-utils";
<MediaUpload
            onSelect={media =>
             console.log( media.id, media.url) }
            allowedTypes={[ "image" ]}
            render={({ open }) => (
              <Button
                className="media-upload-btn"
                onClick={open}
              >
                Add
              </Button>
            )}
          />
`
