### ISSUE TITLE
Show Featured Images on the “Latest Posts” block 

### ISSUE THREAD

**Issue by seokai** [WordPress/gutenberg#17472]
I would like to build an AMP first website with the latest posts as part of my homepage.

Could you add a way to show the featured image on the “Latest Posts” block?

The page I need help with: https://staging.search-one.de/ - currently I can only display title, excerpt and the date.

**Comment by HardeepAsrani** [comment]
If we are moving forward with this, I can take over this and send a PR. :)

**Comment by franzikusderreine** [comment]
I'm interested as well.

I just can't seem to figure out how to extend the core block "latest-posts" :/

**Comment by mrmakadia94** [comment]
I'm interested as well and do some research on it .

First we request for rest api call for media through  `https://example.com/wp-json/wp/v2/posts?_embed`  in that query find the media list then we can do that.

**Comment by mrmakadia94** [comment]
Hello @swissspidy 
 
Here i share one design request for the feature image
![latest-post-feature-image-design](https://user-images.githubusercontent.com/46365208/65760976-9fb0e080-e13b-11e9-96fb-05c7e27ddb6b.png)

Needs Design Feedback

**Comment by HardeepAsrani** [comment]
Why have three different panels when we can have them in a single panel? They’re mostly related. We can also think if we should give an option to choose image size? 

We’ve done similar in our plugin and I’m happy to contribute here and take this further, if we decide to add option.

**Comment by karmatosed** [comment]
> Why have three different panels when we can have them in a single panel? They’re mostly related. We can also think if we should give an option to choose image size?

I would encourage thinking about grouping here and what is needed or having everything there.

**Comment by mapk** [comment]
There is an existing draft PR for this: https://github.com/WordPress/gutenberg/pull/17151

**Comment by strarsis** [comment]
What can I use in the meantime? Are there plugins that offer such a block with featured thumbnail images?

**Comment by Tikio88** [comment]
> What can I use in the meantime? Are there plugins that offer such a block with featured thumbnail images?

My solution was to use a plugin used [Getwid](https://wordpress.org/plugins/getwid/). I've found it to work very well, but it does come with many other features which you may, or may not appreciate. You could also try programming it yourself obviously, but I as I wanted to save time, I chose to use Getwid.

Hope this helps 😀

**Comment by strarsis** [comment]
@Tikio88: Apparently this feature has been already merged. I can find the thumbnails option in the recent posts block with latest Gutenberg plugin now. But I had to downgrade to older Gutenberg because of an unrelated issue.

**Comment by Tikio88** [comment]
@strarsis That's great, I'll need to check the new Gutenberg version!
