### ISSUE TITLE
Drop Cap is on a different number of lines on front end vs. vackend

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1747]
Gutenberg version: 0.3

## Issue Overview

Inside Gutenberg, drop caps cover two lines.  On the front end, they cover three.

## Steps to Reproduce (for bugs)

1. Apply a drop cap
2. View the post

## Expected Behavior

I expect the same number of lines to be covered by the drop cap on both the front end and the back end

## Current Behavior

Inside Gutenberg:
<img width="109" alt="screen shot 2017-07-05 at 1 41 30 pm" src="https://user-images.githubusercontent.com/622599/27879632-e4bcedbc-6187-11e7-950a-766392467fd0.png">
Inside my theme:
<img width="170" alt="screen shot 2017-07-05 at 1 41 44 pm" src="https://user-images.githubusercontent.com/622599/27879631-e4b4cd44-6187-11e7-9d79-bd0c7014f376.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I guess that depends on the theme fonts which are probably different from Gutenberg fonts and font sizes. I don't think Gutenberg should enforce the basic styles (fonts, font size, default text color) for frontend. But there are open issues to bring/use theme stylesheets in Gutenberg blocks.

**Comment by mtias** [comment]
The themes can already styles this. It seems like something that would need to be documented as needing theme attention for optimal work. Might also be something we could fix if the theme supplies a default font-size / line-height. Though that gets tricky with a theme using responsive typography, at which point we are back at the theme supplying the styles directly.

**Comment by jasmussen** [comment]
Given there's hopefully a future where we can load the theme's `style.css` file into the editor itself, this feels to me like a theme issue same as a blue link in the current editor might be green in the theme itself, if an editor style hasn't been loaded.

**Comment by youknowriad** [comment]
Closing as won't fix. This could be fixed by the theme proving a stylesheet to the editor.
