### ISSUE TITLE
When in text, stay in text

### ISSUE THREAD

**Issue by krogsgard** [WordPress/gutenberg#1748]
Using: Gutenberg 0.3.0 and WP 4.9 Nightly (July 5)

## Issue Overview

I believe continuous text should be a single block, or at least visually appear as one. Not doing so is a visual distraction, especially for longish form writing.

### Broader description.

Each new block brings up a faded outline and text options. When you're in the flow of writing in depth, it is jarring to the writing experience. Given the nature of short paragraph writing, it is quite a distraction for an otherwise beautiful editing experience.

Each new paragraph is surrounded by options that have nothing to do with the thought I am trying to put on the screen.

![new paragraph clutter](https://cldup.com/9m6qcUObCx.png)

I think a good rule of thumb would be, "when in text, stay in text," and a visual representation of a singular block would be ideal (even if for some reason in the backend each paragraph-as-block is a better technical implementation).

I think the (+) button alone is enough to inform me that I can do other things. As for moving around paragraphs... I think the long used copy/paste within the block is perfectly normal and acceptable UX, even for the least tech savvy.

**Comment by youknowriad** [comment]
I think #1561 would address the concerns here.

**Comment by krogsgard** [comment]
I tried searching issues, but apparently could've done better!

Yes, I think that ticket is largely the same visual complaint. The only additive I make is that continuous text may be better served as one block, vs many... is there a technical reason for using a new block for every text paragraph?

It seems like it could all be one, unless I'm missing something.

**Comment by nylen** [comment]
Previously: https://github.com/WordPress/gutenberg/pull/1078

**Comment by nylen** [comment]
PR to bring back multi-paragraph text: #1959

**Comment by nylen** [comment]
Also related: #1989, #2135

**Comment by mtias** [comment]
This has been a design decision made early on to treat paragraphs as individual blocks. Advantages include: ability to reorder paragraphs with block arrows, ability to lock at paragraph level for collaborative editing, ability to apply block level modifications (alignments/attributes) with consistent UI.

It may still be the case a text block with multiple paragraphs can be added, either replacing the current one, as a new one, or as a setting.
