### ISSUE TITLE
Local autosave: expand e2e test coverage

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#17495]
Follow up on #16490. See https://github.com/WordPress/gutenberg/pull/16490#pullrequestreview-288676101:

> - [ ] Add documentation for the newly introduced component
> - [ ] Make the local autosave interval configurable so sites could tweak it and at the same time to speed up e2e tests
> - [ ] Let's add more e2e tests which cover other use cases like (mostly to prevent regressions):
logging out - which wipes the saved post ensuring that the saved content doesn't get loaded in the other post

**Comment by gziolo** [comment]
Can we consider it done? There were a few follow-up PRs.

**Comment by jorgefilipecosta** [comment]
Closing this issue as it seems some end to end tests were already added.

**Comment by mcsf** [comment]
I never got round to adding documentation, and that's why the issue remained open.
