### ISSUE TITLE
Docs for date-time are misleading.

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#17497]
**Describe the bug**
The [docs](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/date-time#datetimepicker) for `DateTimePicker` mention the prop `isInvalidDate`, but it's never passed to the inner `DatePicker` component.

Wasted so much of my time thinking that my code is wrong :(

**Comment by mkaz** [comment]
This is partially a documentation bug, but it is also the way the component is packaged.

The `date-time` directory exports the `DateTimePicker`, `DatePicker`, and `TimePicker`. The one readme documentation file does not expose each of the components, and which props go with which.

The `DatePicker` does receive the `isInvalidDate` property, but the `DateTimePicker` components, which includes the `DatePicker` does not pass it forward. So one fix should be passing the prop forward.

Additionally, it seems like the DatePicker and TimePicker should be moved to their own component directory.  @ItsJonQ  what do you think?

**Comment by ItsJonQ** [comment]
> Additionally, it seems like the DatePicker and TimePicker should be moved to their own component directory. 

@mkaz I agree. It would avoid confusion and provide an opportunity to create README and [stories](https://github.com/WordPress/gutenberg/issues/17973) for these components as well. I think your explanation of how it currently works is reason enough to refactor :).

I'm guessing to avoid breaking previous implementations of `DatePicker`, `DatePicker/index.js` would have to import/export the relocated `DatePicker` and `TimePicker` components.

@manzoorwanijk A real bummer to hear that this component gave you trouble <3
