### ISSUE TITLE
Please Stop Changing the HTML Markup of a block

### ISSUE THREAD

**Issue by hrsetyono** [WordPress/gutenberg#17509]
Few days ago I accidentaly updated Gutenberg plugin on a production site (I used Composer and just did `composer update` command)

Then today I realized some of my pages has **messed up Gallery**. Apparently now Gutenberg add an inner wrapper to Gallery block?

Other example is how **Table is now wrapped inside figure**. Which also messed up my styling.

```html
<figure class="wp-block-table">
  <table>
    ...
  </table>
</figure>
```

Previously, it's like this:

```html
<table class="wp-block-table">
  ...
</table>
```

I know this is a non-issue if I simply not update Gutenberg.

But some of my projects use core Gutenberg from WP 5.2. What if the next WP 5.3 has updated Gutenberg?

Please consider this before updating the core Gutenberg.

Thank you

**Comment by swissspidy** [comment]
Sometimes this cannot be avoided. For example, #16324 introduced this `figure` element to fix issues with accessibility and allow for further enhancements to blocks.

**Comment by hrsetyono** [comment]
That's understandable. I will install old version of Gutenberg on my site to avoid the upcoming changes in WP 5.3.

But that Table zoom-level issue can be easily solved by adding `display: block` and `overflow-x: auto` to the table.

It doesn't feel right to change the display of table, but it does the job for my site.

Thanks

**Comment by talldan** [comment]
> But that Table zoom-level issue can be easily solved by adding display: block and overflow-x: auto to the table.

@hrsetyono That's been tried previously with the table block, but it breaks `table-layout: fixed`.
