### ISSUE TITLE
Paragraph - text aligning not working

### ISSUE THREAD

**Issue by Computino** [WordPress/gutenberg#17510]
Hello everyone,

I am using the latest version of the Gutenberg plugin for Wordpress.

I've just noticed this issue. I add a paragraph on the editor, I center the text, and it works. When I publish the article, the output text is not centered but keeps staying on the left.

The same happens if I try to align the text on the right.

I am using: Firefox (latest) Windows 10

![image](https://user-images.githubusercontent.com/55628281/65374802-ace94d80-dcab-11e9-97c9-bb4f4d066c8c.png)

![image](https://user-images.githubusercontent.com/55628281/65374806-b8d50f80-dcab-11e9-9031-14257fface55.png)

**Comment by HardeepAsrani** [comment]
Which theme and plugins are you using? Can you give a link to your website so I could check? :)

**Comment by Computino** [comment]
Hello @HardeepAsrani,
thank you for the reply and sorry for the delay.

I am using Bimber theme and quite some plugins, everything registered and updated.

I just tried something. If I use a "Classic Editor" block, and I center the text, it works.

By the way, this is one of the page from the website that shows the problem, https://procontro.com/miglior-tablet/. Right on top, the 6th paragraph, "LA MIA TOP 3", should be centered.

**Comment by HardeepAsrani** [comment]
It has `has-text-align-center` which shouldn't be there, as it only gets added to Quotee & Cover block. Which version of WordPress are you using? And also, can you create a new post and see if the same happens?

**Comment by Computino** [comment]
The pictures uploaded are from a new post. Wordpress is updated.

**Comment by swissspidy** [comment]
If you use Gutenberg 6.3 or newer, or WordPress 5.3 Beta, then the `has-text-align-center` class is expected to be there. See #16794. If your text is not aligned in that case, it probably means that your theme does not yet support classes like `has-text-align-center`

**Comment by Computino** [comment]
I am using WordPress 5.2.3, it updates by itself, and Gutenberg Plugin 6.5.0.
I think I will just wait for a Wordpress update or a theme update.
It's not a bug at least and, plus, it's not like users and google give so much importance to these "not-center-aligned paragraphs". As long as the website doesn't go down for this, it's okay.

Thanks for the answers and helpfulness, btw.

**Comment by carolinan** [comment]
Closing this, as it is confirmed to be a theme issue.
