### ISSUE TITLE
Table block causes errors when no table elements are selected

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1751]
- Add a new table block
- Do not focus any elements (the block is selected, but no elements within it are focused)
- Click the table dropdown menu and click an operation such as "Insert Row Before"
- Observe console errors, and that nothing happens:

![2017-07-05t21 24 00 0200](https://user-images.githubusercontent.com/227022/27881532-4b378002-61c9-11e7-8af0-214209b438da.png)

cc @EphoxJames

**Comment by EphoxJames** [comment]
Seems to be a Chrome specific bug (the table is automatically selected on Firefox) which I guess is why I never saw it in development.

**Comment by EphoxJames** [comment]
This looks like a TinyMCE bug as it should be focusing the editor on load but because the body element is a table it's not working.

I will file a bug on Jira for TinyMCE and work around the bug by selecting the first table cell on init.

**Comment by nylen** [comment]
After #1755 this is a bit better; however, automatically selecting the first cell is not enough.  It's not difficult to select a block without focusing any of its elements:  click the space under the block mover arrows.  Then this error appears again.

**Comment by westonruter** [comment]
Also, there is a regression regression with #1755: the cell is getting focused even when the block is not focused. On the Gutenberg Demo page, after the page loads the cursor gets put onto the table halfway down the page:

![image](https://user-images.githubusercontent.com/134745/27974909-e6fd37ba-6314-11e7-8904-86ef2ce9eba4.png)

**Comment by nylen** [comment]
@EphoxJames can we get an update on this?  #1798 is at least a partial fix but it really needs to be fixed in the table plugin instead.

**Comment by EphoxJames** [comment]
I've added a check before calling execCommand to see if the table is selected and apply a default selection of the first cell if it is not.
