### ISSUE TITLE
Some CSS rules applied in the editor override theme styles

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#17511]
Some of the rules which are provided to style the HTML elements which are only used for editor functionality override the usual CSS cascade. This forces Theme/Block authors to write more complicated CSS than is necessary.

An example is `.wp-block-cover .block-editor-block-list__block {color: #f8f9f9;}`. This is a specific colour assignment to an element which is only in the editor. However, this means that all children of `.block-editor-block-list__block` will inherit this colour. The much simpler CSS standard colour inheritance - which allows me to set the text colour on the outer .wp-block-cover and have it inherit down the tree - is broken.

**Comment by ItsJonQ** [comment]
@markhowellsmead Thank you for raising this!

This CSS specificity fighting between Blocks x Themes is one of the main problems that the [Global Styles focus](https://github.com/WordPress/gutenberg/issues/19611) is attempting to solve.

From our initial research/testing, we have ideas of how the style relationships between blocks, themes, and user configurations can live harmoniously (the dream)

We've started with the very [first phase](https://github.com/WordPress/gutenberg/projects/40) of development. We're still quite ways off from implementing it into all blocks, as well as blocks x themes, but we'll get there!

**Comment by markhowellsmead** [comment]
Thanks for the feedback @ItsJonQ. Good to know that a solution is on the way. I guess you don't need me to cross-reference other issues along similar lines, such as #17069?

**Comment by markhowellsmead** [comment]
Closing this due to a lack of activity over the last three years.
