### ISSUE TITLE
The Gallery block is showing the dark gradient even when there's no caption in the editor

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17525]
![image (1)](https://user-images.githubusercontent.com/272444/65427920-4c712200-de0b-11e9-8ef9-f73e9dda5524.png)

**Expected behavior**

The background should only be added for images with captions.

**Comment by youknowriad** [comment]
I added the "Needs Design Feedback" label to confirm with designers the expected behavior.

**Comment by karmatosed** [comment]
I am about to add a complication wish :) If there are no captions, could it show no gradient and if there are some could it show gradient? I say this as for me showing a mixture isn't great so if one caption showing on all makes sense. If a choice though I'd say no gradient.

**Comment by youknowriad** [comment]
> I say this as for me showing a mixture isn't great so if one caption showing on all makes sense. If a choice though I'd say no gradient.

I'd like to see this tested but for me even if one image is captioned, it feels weird to obfuscate other uncaptioned images. It can be seen as just an effect of the image itself and maybe an undesired one.

**Comment by mtias** [comment]
This used to work well before: no gradient shown unless individual image is selected or the images has a caption set.

**Comment by mapk** [comment]
I agree here. The gradient should not be visible unless it has a caption or is selected. 👍
