### ISSUE TITLE
Disable Preview / Tips Panel from in-page Inserter

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#17520]
Let's try disabling the preview / tips panel when using the in-page inserter (as opposed to the top-level inserter).

**Comment by karmatosed** [comment]
+1 to this as feels a good improvement to the experience.

**Comment by mapk** [comment]
I know there's a lot of UI going on with that Inserter + panel, but I rarely ever use the Top Toolbar inserter to add blocks. Going through the usability testing videos, I noticed that users are kind of split here (ie. some use the sibling inserter dominantly, other the top toolbar inserter). For those who don't really use the one in the Top Toolbar, they may never really experience the Help Panel. Are we okay with that?

I don't think it's a necessary experience that every user should have, so I'm okay removing it, or at least trying it out.

**Comment by talldan** [comment]
Removing it from the in-page inserter would also solve this issue that's cropping up at the moment:
https://github.com/WordPress/gutenberg/issues/17177

**Comment by mapk** [comment]
The Design Team discussed this one [in today's slack triage](https://wordpress.slack.com/archives/C02S78ZAL/p1569342246221600).

There's a consensus to drop the Help Panel from the sibling inserter, especially in light of #17177 that @talldan mentioned above. We needs some dev!
