### ISSUE TITLE
Duplicate Block - Unique ID not updating

### ISSUE THREAD

**Issue by diggeddy** [WordPress/gutenberg#17536]
**Describe the bug**
Bug since 6.5 update. When duplicating a 3rd Party grid container block the unique element ID does not update when first published.  Editing and updating the post will update the IDs.

**To reproduce**

1. Install Kadence Blocks plugin
2.Add a row container with 2 column Grid and populate.
3. Make duplicate of block and make style changes to differentiate.
4. Publish the post.
5. View the Post.
6. Inspect the HTML of the original and duplicated block to see the IDs

Example:
<img width="451" alt="Screenshot 2019-09-23 at 23 39 17" src="https://user-images.githubusercontent.com/30641942/65468686-bfef4f80-de5c-11e9-928f-fbcd91c9c36b.png">

I have tested this with other blocks that use the clientID method of registering a unique ID and they display the same issue. This  seems to only happen when the 'container' block has a grid within it.

**Expected behavior**
Duplicated block should register new ID in editor before publishing. This is pre-6.5 behaviour.

**Comment by HardeepAsrani** [comment]
Hey @diggeddy,

Seems to be an issue with how blocks are doing their ID. We do something similar in https://wordpress.org/plugins/otter-blocks/ and it works fine (or at least I'm not aware of such issues), so you should ask the plugin author to make sure IDs are not getting duplicated.

When a block is added, they should check if the clientId & IDs used in the block are same, if not then update.

**Comment by diggeddy** [comment]
@HardeepAsrani the method used in Otter Blocks forces the ID to be updated every time the editor is loaded which is something we're trying to avoid. I used Kadence as an example as their unique IDs remain constant on editor load. 
This bug, albeit related to the method of registering the ID, only arose on 6.5 update.

**Comment by HardeepAsrani** [comment]
@diggeddy When I say updates each time the block is loaded, it meant on its initial load. If you add a block in the editor, then it will have the same ID forever. If you duplicate it or copy-paste the block to somewhere, only then the ID will change. So the ID stays the same, while getting updated when duplicated. :)

**Comment by HardeepAsrani** [comment]
Regarding "Duplicated block should register new ID in the editor before publishing. This is pre-6.5 behavior."

Blocks don't really register a new ID in Gutenberg, but it's done by the plugins like Kadence & Otter. :)

**Comment by talldan** [comment]
@diggeddy I see you've created https://github.com/kadencewp/kadence-blocks/issues/65, which in my opinion is the best first step since Gutenberg isn't the creator those unique IDs, the plugin implements this behaviour. 

I think the best approach would be for the plugin developer to investigate first. If they discover that there is a backwards compatibility issue in Gutenberg, they should be able to report which APIs have the issue and it can then be investigated here.

I'll close the issue in the meantime, but it can always be reopened if it's discovered the problem lies here.

**Comment by diggeddy** [comment]
Thanks @talldan - in the absence of a core function for generating stable unique IDs the Kadence method has proven to be the only stable method. We're trying like Ben from Kadence to understand what was changed in 6.5 that broke this function when duplicating blocks. Any insights are appreciated. Ben has commented on the Kadence github regarding this.

**Comment by talldan** [comment]
@diggeddy I've had the same issue previously with ids, definitely something that's not so easy to implement in blocks.

I have an open issue where I'm trying to gather ideas:
https://github.com/WordPress/gutenberg/issues/17246

**Comment by htmgarcia** [comment]
> @HardeepAsrani the method used in Otter Blocks forces the ID to be updated every time the editor is loaded which is something we're trying to avoid. I used Kadence as an example as their unique IDs remain constant on editor load.
> This bug, albeit related to the method of registering the ID, only arose on 6.5 update.

Hi @HardeepAsrani,
I'm curious if there is a technical disadvantage to allow the editor assign new IDs to blocks?
___
Regards

**Comment by HardeepAsrani** [comment]
Hi @HardeepAsrani,

> I'm curious if there is a technical disadvantage to allow the editor assign new IDs to blocks every time the post/page is edited?

Hell no, just something I hadn't realized then and fixed after the issue came to my notice. :)
