### ISSUE TITLE
List block: indentation keyboard shortcut prevents MacOS emoji panel from opening at start of list item

### ISSUE THREAD

**Issue by bluefuton** [WordPress/gutenberg#17538]
**Describe the bug**

In the list block, there is a keyboard shortcut to indent the list (Ctrl + Space).

On OS X, there is a system keyboard shortcut to open the emoji panel (Ctrl + Cmd + Space).

This conflict means that it is not possible to open the emoji panel at the start of a new list item.

![2019-09-24 12-05-58 2019-09-24 12_07_51](https://user-images.githubusercontent.com/17325/65471726-5e62cb80-dec4-11e9-8ae0-9785d75ab154.gif)

**To reproduce**
1. Create a new list block
2. Create a list item without any text
3. Press Ctrl+Command+Space to bring up the emoji panel
4. Notice that the list item is indented instead

**Expected behavior**
When I press Ctrl+Command+Space, the emoji panel should always appear.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 76

**Comment by ellatrix** [comment]
Thanks for the report!

**Comment by bluefuton** [comment]
Thanks for fixing this @ellatrix! 🎉
