### ISSUE TITLE
Block Navigator: Add ability to insert blocks from inside navigator

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#17543]
![](https://user-images.githubusercontent.com/677833/65411186-cd85e480-de1e-11e9-82b3-c7f57312acb5.png)

It would be useful for the Navigation block if users could Block Navigator could insert blocks from within the Block Navigator.

The primary use case is for adding Menu Items to a Navigation block.

**Comment by tellthemachines** [comment]
A couple of questions/thoughts on this:

- Should this functionality be available in the general post content block navigator, in all the parent block navigators e.g. columns or should it apply only to the navigation block navigator? It could be a useful layout feature for complex nesting situations, but overkill if you're just adding in paragraphs and images to a blog post.

- Should we allow editing of blocks within the navigator, or only insertion? If the first, how do we avoid ending up with a nested editor-within-the-editor sort of thing? If the second, I'm wondering what the resulting workflow will look like: do you add a bunch of blocks and then use the navigator to click through to them individually and edit them, or add in a block, click through to edit, go back to the navigator and add another block, etc.? Either way seems like there'll be a lot of back and forth between editor and navigator.

**Comment by shaunandrews** [comment]
I've been exploring a little with how we could use the Block Navigator as a way to manage pages within the Navigation block:

![block-navigator-options](https://user-images.githubusercontent.com/191598/67240337-40cf4600-f41f-11e9-9bc1-98ac15cc8a28.gif)

That GIF uses a modal, but I could see this living in a popover or in the sidebar as well:

<img width="2279" alt="image" src="https://user-images.githubusercontent.com/191598/67240357-488eea80-f41f-11e9-869d-351a3327bd74.png">
