### ISSUE TITLE
Navigation block: Add initial state

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#17541]
![](https://user-images.githubusercontent.com/548849/62833066-d89eff80-bc38-11e9-9993-c154d43a694f.png)

- When a Navigation block is inserted, it should contain menu items for each top level page in the site.
- A top level page is a page that has no parent.

**Comment by shaunandrews** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/191598/65629911-5bd6a380-dfa2-11e9-8527-f91fe6f04fe6.png">
