### ISSUE TITLE
Dragging a block out of the editor breaks the site

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#17549]
**Describe the bug**
If I grab a block and drag it outside the editor, the site breaks.

Video: https://cl.ly/5d8d3feb2659

**To reproduce**
Steps to reproduce the behaviour:
1. Edit a page
2. Drag a Paragraph block to the left-hand side menu 
3. See site break

**Expected behavior**
The Block should just return to its original position. The site shouldn't break.

**Screenshots**
See above vid.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox Quantum 69.0.1
 - WP 5.3 Beta 1

**Comment by ItsJonQ** [comment]
Whoa! That's pretty nuts. I wasn't able to reproduce on my end 🤔 

Tested with the latest WP beta install locally on Firefox and Chrome

* OS: Mac OS Mojave 10.14.6
* Browser: Firefox 69.0.1 and Chrome 77.0.3865.90
* WP 5.3-beta1-46288

**Comment by maddisondesigns** [comment]
Have just updated another site (with a different theme) and was able to replicate the exact same issue.

Tried Chrome (77.0.3865.90) on both sites but wasn't able to replicate.

**Comment by maddisondesigns** [comment]
This still happens in 5.3-RC1-46558. Have also tested with Firefox Developer (v71.0b1) and the same thing happens also.

**Comment by maddisondesigns** [comment]
Have just tried this again and the issue still occurs with WP5.4

Tested with WP5.4, Firefox 75.0, Twenty-Twenty

**Comment by noisysocks** [comment]
I was was able to reproduce this in Firefox but not Chrome. Thanks @maddisondesigns!

**Comment by talldan** [comment]
I can no longer reproduce this in Firefox using Gutenberg 8.6. If anyone else is able to confirm that'd appreciated.

I'll close the issue for now though.

**Comment by maddisondesigns** [comment]
@talldan Seems to work ok for me now too 👍
