### ISSUE TITLE
Navigation block: Add default block stylesheet

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#17542]
<img width="701" alt="Screen Shot 2019-09-24 at 12 11 54" src="https://user-images.githubusercontent.com/612155/65475891-85210200-dec4-11e9-8944-6665a3d4ee1a.png">

- Add a block stylesheet that styles the Navigation block to look similar to how it looks in the editor.
- Allow for themes to override these styles and do the heavy lifting using their own stylesheets.

**Comment by noisysocks** [comment]
Anything we do here has to take into account that colours will be customisable as per #16830.

**Comment by karmatosed** [comment]
Just flagging this as needs design then we can get feedback after.

**Comment by karmatosed** [comment]
I think a default theme style is ace.  Removing myself as this feels like a solution we can 'just do'.

**Comment by obenland** [comment]
Fixed in #18094.
