### ISSUE TITLE
WooCommerce Blocks: not responsive 

### ISSUE THREAD

**Issue by brookewp** [WordPress/gutenberg#17555]
**Describe the bug**
All of the WooCommerce blocks (they appear to have the same structure) aren't responsive on mobile. As the screen gets smaller, they all squish together making the content broken and unreadable. I tested new products, on sale, top rated, and product categories which all resulted in the same issue. 

**To reproduce**
1. Create a page or post 
2. Add any WooCommerce block  
3. Make sure to set at least 3 columns since it won't be noticeable otherwise
4. Check out how it looks on tablet/mobile 

**Expected behavior**
For it to reduce to fewer columns on tablet and stack on mobile, like our column block. 

**Screenshots**

<img width="359" alt="Screen Shot 2019-09-24 at 12 02 17 PM" src="https://user-images.githubusercontent.com/35543432/65528896-31fa7f80-dec3-11e9-934f-bc749bf720a9.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 76.0.3809.132 

**Smartphone:**
 - Device: Google Pixel 3
 - OS: Android
 - Browser: Chrome
 - Version: 9

**Comment by swissspidy** [comment]
Hi there

You‘d need to report this to WooCommerce, as these blocks are part of that plugin, not Gutenberg.
