### ISSUE TITLE
Link interface iteration

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17557]
I took some time to imagine where the link interface could evolve to. There are a few reasons we should consider evolving this.

- The navigation block action to add links needs to be able to pick from pages/posts.
- Currently, you can't see suggested links.
- We have multiple link interfaces so uniting makes sense.
- In the link interface now no meta details such as page/post are shown.

Props to @mtias for suggestions and feedback to get to this issue.

## What can we use as inspiration for this? 

![image](https://user-images.githubusercontent.com/253067/65529969-08efe400-deef-11e9-90bb-1fbb406a5760.png)

![image](https://user-images.githubusercontent.com/253067/65530599-34bf9980-def0-11e9-966a-17a05c599209.png)

When thinking about navigation, I had explored the following:

![image](https://user-images.githubusercontent.com/253067/65531186-39388200-def1-11e9-9fcb-898d739a7cd1.png)

### Abstraction
I began with an abstraction exercise, how far could I take this back? Here are some sketches.

![image](https://user-images.githubusercontent.com/253067/65529418-f4f7b280-deed-11e9-88e0-5fae5c739474.png)

![image](https://user-images.githubusercontent.com/253067/65529345-e01b1f00-deed-11e9-8177-70b46e097f08.png)

![image](https://user-images.githubusercontent.com/253067/65529363-e7422d00-deed-11e9-80e8-365c06e8724a.png)

![image](https://user-images.githubusercontent.com/253067/65529386-ed380e00-deed-11e9-9718-65ec45981d1d.png)

@mtias showed me this from @shaunandrews:

![image](https://user-images.githubusercontent.com/253067/65530976-da730880-def0-11e9-8227-c8948ccbc90e.png)

### Thrown out ideas

I will share some ideas I decided to drop to add context to path I ended up going back to.

<img width="441" alt="Frame 6 9" src="https://user-images.githubusercontent.com/253067/65531424-bbc14180-def1-11e9-9282-e370a0434e6c.png">

![image](https://user-images.githubusercontent.com/253067/65531476-dd222d80-def1-11e9-9afa-b5f9b4d46a87.png)

## Exploring

From there, I went on a little iterative quest and kept coming back to the following, despite going pretty far in some explorations. As a result, I wanted to share the place I am at right now with this:

<img width="441" alt="Frame 6 6" src="https://user-images.githubusercontent.com/253067/65531275-6d13a780-def1-11e9-9372-b22a72b480e1.png">

<img width="441" alt="Frame 6 7" src="https://user-images.githubusercontent.com/253067/65531385-a77d4480-def1-11e9-8064-aa66eebca90c.png">

<img width="441" alt="Frame 6 8" src="https://user-images.githubusercontent.com/253067/65531394-ab10cb80-def1-11e9-8288-f618260d3217.png">

So, what's next? I would love opinions on the direction and any details on what is missing really should be added. Relating to that what is there should be subtracted? If you have any ideas please also add them. 

I plan to do some rapid iterations based on feedback to hopefully get by end of the week something feels good to prototype. I will then look at how this could look both for the link interface in blocks (mocking up various blocks) and then how it adapts to navigation. 

One thing to learn from the link interface so far is feeling and using this is key, so the earlier we get into prototype the better.

**Comment by pablohoneyhoney** [comment]
Chiming in quickly with some first reactions. Excuse if I lack all the context:

- You could benefit from aligning elements and adding some consistent margins.
- The interface could benefit from a known/familiar behavior from other habitual ones, as you reference to. Wonder if you looked up more examples.
- Toggle seems a primary interaction, unsure if that's the intent.  
- This overlay will live on top of other elements. It might benefit from reduction (are date, location, or type all relevant? Can you avoid the dividers?), but also will help if you contextualize this mockup in a few real scenarios. 
 
Hope this helps!

**Comment by karmatosed** [comment]
Thanks for the great feedback @pablohoneyhoney. I'll be iterating based on it but wanted to also reply to a few bits whilst work on that.

I thought it could be good to add the original interface here too so we can bounce from that in discussion:

![image](https://user-images.githubusercontent.com/253067/65543820-df908180-df09-11e9-90b7-96bbc10515ed.png)

![image](https://user-images.githubusercontent.com/253067/65543835-e7502600-df09-11e9-918e-6ce5ff783a73.png)


> You could benefit from aligning elements and adding some consistent margins.

Absolutely, it's a tight space and I recognise I need to iterate the rhythm. In one aspect, I was trying to offset the toggle to distil its weight but might have caused the opposite reaction in that case. I'll have some experimentation there and see where I can find a good middle point. 

> The interface could benefit from a known/familiar behavior from other habitual ones, as you referenced to. Wonder if you looked up more examples.

I agree and if we look at what we have now, I am not sure we have that balance yet. I explored a few different platforms. Most seemed to fall into the linked examples. The most minimal was, for example, Medium:

![image](https://user-images.githubusercontent.com/253067/65542319-d94cd600-df06-11e9-9732-b9515858648c.png)

OneNote as an interface I find interesting for some features (it's reading modes), but it was very similar to Google:

![image](https://user-images.githubusercontent.com/253067/65542272-c6d29c80-df06-11e9-9d70-b44a7a1e9f08.png)

Notion is closer to what we have today (without icons and unlink in toolbar):

![image](https://user-images.githubusercontent.com/253067/65542594-5e37ef80-df07-11e9-8e78-b28926a51732.png)

Do you have any interfaces you think would be great to consider in this iteration?

> Toggle seems a primary interaction, unsure if that's the intent.

It's not and the toggle is hidden in our current interface. I wouldn't be against adopting that approach in this one at all. My experiment in surfacing everything does expose some hierarchy flaws as a toggle is a strong element.

> This overlay will live on top of other elements. It might benefit from reduction (are date, location, or type all relevant? Can you avoid the dividers?), but also will help if you contextualize this mockup in a few real scenarios.

Here is where I think we need to work out what is relevant, which is great as an opportunity. Initially, in exploring this I kept to our current version showing nothing apart from the link. I'll explore some versions around that to see where the essentials are now we have a point with everything there. Type is relevant as we move to navigation, but whether that's shown in tabs over meta. Dividers helped visually, but let me explore the pace of the design as perhaps there's gain there to extract dividers.

Thanks for the feedback as it's good fuel for next iterations.

**Comment by karmatosed** [comment]
Just adding a distilling of the design as a quick iteration.

<img width="441" alt="Frame 6 10" src="https://user-images.githubusercontent.com/253067/65545521-70b52780-df0d-11e9-971f-2b39ec76ccd8.png">

**Comment by phpbits** [comment]
Adding this one for reference : https://github.com/WordPress/gutenberg/issues/17556 

The interface should have room for more options aside from "Open to new Tab"

Thanks!

**Comment by shaunandrews** [comment]
Over in #17544 I shared a design for the link inserter that was specifically focused on adding Pages. It looks like this:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/191598/65633516-51b8a300-dfaa-11e9-8892-354864879284.png">

However, I've been toying with designs for expanding this to include pages, posts, categories, and even the ability to add a new page. One of the first ones (shared above as well) uses a tabbed interface to allow users to switch between types of content to link to:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/191598/65633700-b3790d00-dfaa-11e9-8e30-be03b90fac57.png">

--

Another option uses the existing UI accordion pattern from the block inserter to show groups of content types:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/191598/65633802-ede2aa00-dfaa-11e9-87a9-17ce9071be2c.png">

--

Similarly, we could also adopt the inserter preview pane to show a visual preview of the post/page/etc along with more detailed information:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/191598/65633905-1a96c180-dfab-11e9-9f27-1870bcee43d8.png">

**Comment by karmatosed** [comment]
@phpbits, as discussed in the weekly design meeting for now adding new options to the interface isn't something going to be done in core but a way to extend will be there. Whatever interface the ability to extend is going to absolutely have to be a consideration.

**Comment by karmatosed** [comment]
Let's look at how we can progress here, thanks for all the great input @shaunandrews. 

As far as the multiple paged approaches:

- Pagination: for me this adds a new pattern I don't think we need.
- Tabs: uses an existing pattern used in document panel.
- Accordion: uses an existing pattern used in a category section (block library).

My own feelings are that the accordion makes sense but I wouldn't be against the tabs if everyone feels they are right.

I do wonder if using the preview makes this too the same as block library? I also followed that pattern several iterations ago and the feedback was they were distinctly different. Maybe let's park preview whilst we consider which direction to go regarding tabs or accordion.

There are 2 other decisions I feel around this before we can have 'one link' interface.

- Do we have an action button? In some mocks there is a button to search, in others, there isn't. 

<img width="441" alt="nobutton" src="https://user-images.githubusercontent.com/253067/65954570-33d1bf00-e43e-11e9-856f-d1bdd8498f42.png">

<img width="441" alt="button" src="https://user-images.githubusercontent.com/253067/65954574-38967300-e43e-11e9-9ab9-08b844eab218.png">

- Toggle to open in new tab. This option when placed I absolutely agree looks primary. How can this be still easily available but less of a primary action?

<img width="441" alt="toggle" src="https://user-images.githubusercontent.com/253067/65954590-3f24ea80-e43e-11e9-9a8f-1a8f231826d3.png">

- Link meta. Specifically what do we show of the post or page? Is updated time key? Type seems to be something to agree on until we have sections, then type seems less important.

- Sections. For me, there needs to be by default 'recent' and that should be a summary of all types, this allows for all types of sites. However, in explorations we have 'recent pages' or 'recent posts'. What do others think?

Once the discussion has happened around this I think we are close to at least moving into code to feel what this interface is, thanks everyone for all your hard work to get here.

**Comment by jasmussen** [comment]
I like the last iteration (https://github.com/WordPress/gutenberg/issues/17557#issuecomment-536973640) quite a bit. A few things:

- We probably want the switch to the left of the text to follow the pattern from the sidebar. 
- The visuals are perfect, look superb.

So what remains to do? It seems to me like discussions around tabs, accordions and pagination all relate to the need for this to work for the Navigation Menu also. Specifically tabs or accordions could help group all Pages into one, all Posts into another, all Categories into a third, and so on. Pagination could help when an install has 2000 pages.

But it does beg the question, can we file that as a future improvement and go with what you have right now? How would that work? Well, for one Pages, Categories, Posts, would all be mingled together in one big pool, and we would show only `n` total suggestions so as to not freeze the page trying to load 2000 page suggestions. We would rely utterly on search, in other words. **And maybe that's fine?** 👈 This is probably the question we need to answer.

**Comment by karmatosed** [comment]
@jasmussen here's an iteration based on the toggle, it has the 'add' button which is also up for conversation. Having a physical 'add' feels better to me than an icon but we might decide to have none.

<img width="441" alt="Frame 6 13" src="https://user-images.githubusercontent.com/253067/65961536-b9f60180-e44e-11e9-9b6f-727f27afe43c.png">

**Comment by jasmussen** [comment]
Nice. I like "Add". 

Remaining nitpicks can probably happen in implementation, but I imagine that Add, Portfolio, and Open in new tab should all have the same font size and color, and be the same font size. I'm assuming that's the case but it's a little hard to see.

**Comment by melchoyce** [comment]
+1 to @jasmussen's comments. I also think the text should align with the left side of the search bar, not the search bar's label.

**Comment by shaunandrews** [comment]
Having an "Add" button there all the time seems unhelpful — its confusing in the context of searching. Perhaps a confirm/add button should only show when a URL is pasted into the input. Otherwise, I think the search input should look/work exactly like the search in the Block Inserter.

**Comment by shaunandrews** [comment]
> Toggle to open in new tab. This option when placed I absolutely agree looks primary. How can this be still easily available but less of a primary action?

I don't think this needs to be exposed when adding a link. It should just be a setting within the block sidebar after you add the link.

**Comment by karmatosed** [comment]
Here are some iterations with a few points:

<img width="441" alt="iteration-01" src="https://user-images.githubusercontent.com/253067/65986266-6cdc5480-e47b-11e9-98db-bbfe97bc7054.png">

<img width="441" alt="iteration-02" src="https://user-images.githubusercontent.com/253067/65986283-72399f00-e47b-11e9-9267-fe0340aadb41.png">

Whilst open in new tab to me is also a secondary action, we have it right now as primary. It would have to be an action based on the block the link is added if it's to go in the sidebar, does that make sense from a usability view? Would I look in the block and what if I had more than one link? The point is we are creating a link interface to replace the adding of links everywhere that adapts to navigation.

**Comment by shaunandrews** [comment]
> The point is we are creating a link interface to replace the adding of links everywhere that adapts to navigation.

Ah, this helps. I've only been considering the very specific use-case for the Navigation block. This reframes the problem.

--

Here's an updated mockup:

![Link Inserter i1](https://user-images.githubusercontent.com/191598/65995545-c042a880-e463-11e9-8a48-c2d84ebcc503.png)

* Focusing on a collective list of content (posts, pages, categories, etc), rather than distinct groups lets us forget about the need for accordions or tabs.
* By default, the Link Inserter would show 4 recent items across all content types. This could extend to show more, using infinite scroll to load more as needed.
* Added the "new tab" setting to the bottom.
* In order to accommodate both a timestamp and the content `type` I've moved the `type` to the right. This makes it easier to scan, and highlights the difference between items in the unified list.
* As you type in the search we show results in realtime, and highlight the matching. I'm unfamiliar with the heuristics of search, so this might not be possible or helpful.
* Search results would scroll if needed, to keep the height of the popover consistent.

**Comment by shaunandrews** [comment]
Oh, and when pasting a URL we could do something like this:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/191598/65996675-dfdad080-e465-11e9-88ad-3acead49aac9.png">

**Comment by shaunandrews** [comment]
![Link Inserter i1](https://user-images.githubusercontent.com/191598/65996924-655e8080-e466-11e9-8854-9d85b7334712.gif)

**Comment by karmatosed** [comment]
I think we're at :shipit:  for me! I might suggest we have less indent like in @melchoyce's recommendation, but that is super minor.

Thank you so much @shaunandrews for the work here, it's incredible to see this evolving.

@mapk let's get your feedback and then for me, this feels ready to move to dev which is so exciting.

**Comment by melchoyce** [comment]
I think the indentation makes a little more sense now that I'm seeing @shaunandrews's prototype.

How will inserting work — click on an item to add? If so, will folks need to toggle on "open link in new tab" before selecting an item?

**Comment by mapk** [comment]
Wow, this has definitely made a circle, albeit improved, back to some of [the original mockups regarding the Nav block](https://camo.githubusercontent.com/73038406faa4f33b882a5dff8e6aa396329b8763/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f393234423035444545424235423134313344444135364530384537333341464544394336414633383433323144343545413643423433453731343446453443375f313535343431383030393735305f53637265656e73686f742b323031392d30342d30342b61742b32332e34342e32392e706e67). Really nice work throughout this thread!

The last prototype from @shaunandrews feels like an intuitive solution for the user. It presents some common results, clearly indicates what type of content they are, and allows searching or simple pasting to happen. The UI is scannable and easy to digest. My only concern is the lighter gray meta data. I'm sure everyone's thought about it, but let's make sure it passes color contrast.

When considering this in relation to the Nav block (which I know this issue is kind of aimed at), @melchoyce brings up a good point about adding an item? What if my "About" page doesn't exist? Should I be able to create it within this popover?

**Comment by shaunandrews** [comment]
> How will inserting work — click on an item to add?

Yea, that was my intention.

> will folks need to toggle on "open link in new tab" before selecting an item?

In this design, yes. But this same (or a state of this) interface will appear when editing a link, so you can toggle the setting.

> My only concern is the lighter gray meta data. I'm sure everyone's thought about it, but let's make sure it passes color contrast.

Sure, I mostly _eyeballed_ the colors, so once this is in code we'll use standard colors and have to double-check to ensure they past any contrast requirements.

> What if my "About" page doesn't exist? Should I be able to create it within this popover?

I've ignored the ability to create a new page/post/category — there's too many open questions there, and is probably best saved for a future iteration.

**Comment by karmatosed** [comment]
> I've ignored the ability to create a new page/post/category — there's too many open questions there, and is probably best saved for a future iteration.

That feels right for me too, it feels like an extra iteration for now. Worth exploring but that can be done after we have a v1 for me.

**Comment by shaunandrews** [comment]
> But this same (or a state of this) interface will appear when editing a link, so you can toggle the setting.

Speaking of editing an existing link, here's a quick idea of what that could look like:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/191598/66009996-1414b800-e48b-11e9-8ee3-b9b06f8fbb30.png">

**Comment by karmatosed** [comment]
@shaunandrews I like that as follows pattern. I do think it's an extra for now though still. Very good to have an idea visually though.

**Comment by shaunandrews** [comment]
I’m not sure how it’s “extra.” We need to let people edit existing links somehow. What do you suggest?

**Comment by karmatosed** [comment]
By extra I guess for me the baseline is unlinking/removing - not elegant but functional. I love this interface and happy to have this be our pattern for unlinking.

**Comment by getdave** [comment]
Great work on this. I'm looking to start work on some implementation and it was simple to follow the exploration and thought process. Kudos to all for exposing your working methodology here.

I'm going to start with some research into the existing Link interfaces in the codebase.

I'd also benefit from some direction on how we expect this to line up with the work currently underway in the Nav Block. For example, would it be possible to see this Link interface in context within the current iteration of the Nav Block design?

Much appreciated.

**Comment by talldan** [comment]
> Are you aware of anyone else working on this concept?

The navigation block work has been the main prompt for this change. @noisysocks @tellthemachines @draganescu and I have so far been working on that, but we haven't yet looked at implementing the link interface. Very happy to have you work on it @getdave. I'll add us all as reviewers for the PR.

> Where (in the codebase) would you suggest placing this new component? @wordpress/components or @wordpress/block-editor?

I would go with `block-editor` to start with, as that's where the current components are.

> Is there any technical direction you'd like to offer prior to my commencing work on a working prototype?

Worth thinking in advance about how the implementation will work in the context of the link format. The current implementation is here:
https://github.com/WordPress/gutenberg/blob/master/packages/format-library/src/link/inline.js

I'm sure it could be tidied up a bit.

**Comment by karmatosed** [comment]
> would it be possible to see this Link interface in context within the current iteration of the Nav Block design?

Yes, the idea is this is the link interface to use everywhere.

> For example, would it be possible to see this Link interface in context within the current iteration of the Nav Block design?

Absolutely and I'll mock that up for you.

**Comment by phpbits** [comment]
@karmatosed  I'm still concerned about the plan on making this area extensible. Thanks!
<img width="444" alt="Screen Shot 2019-10-09 at 11 10 49 PM" src="https://user-images.githubusercontent.com/3365507/66494383-28d7f800-eaea-11e9-8a89-667c465789c1.png">

**Comment by karmatosed** [comment]
@getdave here is what it looks like with navigation.

<img width="891" alt="innav" src="https://user-images.githubusercontent.com/253067/66494473-a0d4fc80-eaaf-11e9-9140-6dde90991458.png">

**Comment by karmatosed** [comment]
@phpbits that really depends on 'what' you want to extend. For me, the 2 places would be either having a 'settings' option to use or adding below new tab. I think so long as extending options are given that makes sense.

**Comment by phpbits** [comment]
@karmatosed Here are the toggle options I currently used on [EditorsKit](https://wordpress.org/plugins/block-options/). I'm not sure if there are other options that can be added on the link, probably link classes. I think those should be considered on the interface iteration as well. Thanks!

<img width="424" alt="Screen Shot 2019-10-09 at 11 14 48 PM" src="https://user-images.githubusercontent.com/3365507/66494781-c6cbc280-eaea-11e9-8fb7-bf8b532d162b.png">

**Comment by getdave** [comment]
@karmatosed Thanks very much for the UI updates. A [couple more questions up here](https://github.com/WordPress/gutenberg/issues/17557#issuecomment-539442889) when you have time.

@phpbits Appreciate you bringing up these use cases. It really helps. We can easily provide a render prop to allow you to customise that area with additional items. Please feel free to hold me to account on that _when_ I request a review on https://github.com/WordPress/gutenberg/pull/17846. Thanks.

**Comment by getdave** [comment]
@phpbits As you've noted [the reference visual above](https://github.com/WordPress/gutenberg/issues/17557#issuecomment-537209125) has `Open In New Tab` **_always_ visible**. 

However, when you have a number of controls this could be said to become rather...intrusive.

The component I'm using under the hood has an option for an additional settings draw which can be toggled open/closed. @karmatosed what do you think about putting the "additional controls" area behind this toggle (including "New Tab")? 

Here's some screen captures of what I'm thinking (from my working code-based prototype!):

#### Single Setting Control

![Screen Capture on 2019-10-09 at 16-30-40](https://user-images.githubusercontent.com/444434/66496459-d8917380-eab2-11e9-832e-e6810cff65ee.gif)


#### Multiple Setting Controls
![Screen Capture on 2019-10-09 at 16-31-47](https://user-images.githubusercontent.com/444434/66496327-a8e26b80-eab2-11e9-96f2-a033aa9400e3.gif)

**Comment by karmatosed** [comment]
> I'm just concerned that these options won't be included on the mockups

@phpbits they won't be because there isn't a plan to add them right now. I think whether they should or not is a different debate to be had outside this issue. That is an absolutely fine discussion to have, but we shouldn't be showing in mocks today as a result.

There is room to grow but I have to agree with @getdave I do think showing 3 toggles like that might not be the best intuitive experience. That said there are a few spaces you could explore for that, including secondary panels and adding a 'settings' cog (you could extend that far).

**Comment by shaunandrews** [comment]
Here's an animation showing the flow in action when adding a link to a Paragraph block:

![Link Inserter i2 Animation](https://user-images.githubusercontent.com/191598/66506360-331ed580-ea9b-11e9-8dd4-8cb6bbec620c.gif)

You should be able to see the full-res screens in Figma at this link:
https://www.figma.com/file/90LsscYFOt3QADgab2MXY9/Link-Inserter?node-id=0%3A851

--

@getdave Here's some answers for your questions:

> Why is there a different UX for URL-based links and internal Post-based links?

I don't think this was intentional, just a remnant of the iterative design process above. I've updated the design and tried to make the UX for URL and post-based links the same. Essentially the only thing I did was remove the "Add Link" button.

> Can we see the full UX workflow (from search -> link insertion)
> please could I have the key individual frames from this

I think the new GIF and Figma link above should answer these two.

**Comment by phpbits** [comment]
@armatosed  Agreed. Gear or dots icons would be really great in order to have cleaner interface. 

<img width="341" alt="Screen Shot 2019-10-10 at 11 44 49 AM" src="https://user-images.githubusercontent.com/3365507/66537573-7d638d80-eb53-11e9-8106-e098f0bc6261.png">

**Comment by getdave** [comment]
> I think the new GIF and Figma link above should answer these two.

@shaunandrews Thank you! Almost there. Could you provide a visual for editing an existing **_URL_** link please? I'm sure you've already noted that as a user, for URLs I'd expect to be able to "tweak" the url after it's been entered. I don't want to have to ditch the entire URL and re-enter it just to change `http` to `https` for example.

**Comment by shaunandrews** [comment]
> Could you provide a visual for editing an existing URL link please?

I thought I did this in the Figma file, but you bring up a good point about wanting to tweak the URL. I’ll work up something in a bit. 

> The mockup shows results that include taxonomies such as Category.

The current implementation might be limited, but we do need to support Categories (and other CPTs) — especially for the Navigation block. To see the functionality we need to match, take a look at the UI for managing Menus within we-admin. 

<img width="306" alt="PNG image" src="https://user-images.githubusercontent.com/191598/66571814-ed671900-eb3d-11e9-896a-abc65497522c.png">

**Comment by getdave** [comment]
Does anyone have any knowledge of a means by which we could look up a site's favicon by URL?

Unless I'm wrong @shaunandrews the design (below) implies that we've looked up the favion for `make.wordpress.com` and displayed it inline? If I'm wrong please let me know.

<img width="743" alt="Screen Shot 2019-10-10 at 17 05 30" src="https://user-images.githubusercontent.com/444434/66586480-93d40e00-eb80-11e9-80d5-5e4595e2581b.png">

@talldan @youknowriad Do you have any knowledge of how we could do this?  Presumably a request to an API endpoint which would do the fetching and downloading of the favicon and return to the user? Is this something we could / would consider doing? I assume cross-origin rules will stop us from just hotlinking this.

**Comment by gustavpursche** [comment]
@getdave I'm not assicated with the issue at all (just following) by I know that google runs a favicon service: https://www.google.com/s2/favicons?domain=twitter.com

I don't believe it would be a good idea to use that in the Backend because of privacy issues, but technically this should be possible.

**Comment by karmatosed** [comment]
I think we can explore also without favicon if needed.

**Comment by mtias** [comment]
I'd suggest showing the path for non-post items (pages, categories, etc), including hierarchy, instead of the date. Also "open in a new tab" seems to be extremely prominent for non-primary action.

**Comment by getdave** [comment]
>  the path for non-post items

@mtias Can I clarify that by "path" you are referring to "url"? Just want to be 100% in case I"ve misunderstood.

**All** - for reference, this is the data I currently have available (for a single search result) when we use the REST API `search` endpoint:

<img width="546" alt="Screen Shot 2019-10-11 at 15 30 56" src="https://user-images.githubusercontent.com/444434/66659950-44531800-ec3c-11e9-8adb-c1498c3d7449.png">

**Comment by shaunandrews** [comment]
> Can I clarify that by "path" you are referring to "url"? Just want to be 100% in case I"ve misunderstood.

Yup, without the root domain. So it could be `/`, `/team/dave-smith`, or `/category/random`.

**Comment by mtias** [comment]
Yes, what @shaunandrews said.

**Comment by getdave** [comment]
> I think we can explore also without favicon if needed.

@karmatosed In the spirit of getting to an MVP I'd say this is a good option.

We can always add this on in follow up PRs as and when (and if) we work out a solution. 

@shaunandrews mentioned he was going to work something up design-wise. I'll leave this to you both. Much appreciated.

**Comment by getdave** [comment]
Thanks for this update @shaunandrews. Looking good!

I still need a few minor states however:

- once I have selected an option how to I transition back to "search" state to change it (for example - I may have accidentally clicked the wrong option).
- once I have selected an option what does clicking on the "cross" icon do? Remove the selected state or remove _and close_ the link UI entirely?
- once I have selected an option **which is a URL**, how do I transition back to "edit" mode to tweak the URL?

Other than that here's my responses:

> I think we can ditch the ever present new tab switch, and only show it once a link has been added or selected

This seems good.

> Removed the favicon from URL-based results. This is primarily just to reduce scope; At some point I'd love to add this in.

Agreed.

> The height of the popover is now fluid, with a max height of 340px. Below this max height the popover should shrink to fit the content. When larger than this height, the popover should scroll.

This is currently the case already so that is good.

> The popover now stays open after selecting a link, transitioning to its edit state which is where the link settings (like new tab) will appear.

I'll look into this state.


Thanks again 👍

**Comment by shaunandrews** [comment]
Here's another iteration on the design, in GIF form:

![Link Inserter i4 Animation](https://user-images.githubusercontent.com/191598/66868258-0111e580-ef6b-11e9-927f-01f2201bf33e.gif)

> once I have selected an option can I transition back to "search" state to change it (for example - I may have accidentally clicked the wrong option)?

Excellent feedback. I've added a way to change the link once added.

> once I have selected an option what does clicking on the "cross" icon do? Remove the selected suggestion or remove and close the link UI entirely? What happens to the UI when this icon is clicked?

I found the "X" icon to be too uncertain, and have replaced it with a button.

> once I have selected an option which is a URL, how do I transition back to "edit" mode to tweak the URL?

Hopefully the new button and the GIF above help explain how this flow works.

Let me know if there are any questions.

**Comment by getdave** [comment]
> Here's another iteration on the design, in GIF form:

@shaunandrews Thanks for this. I've attempted to update the code with these tweaks.

![Screen Shot 2019-10-16 at 11 23 56](https://user-images.githubusercontent.com/444434/66910952-76cb8f00-f007-11e9-8083-b82c0421f09e.png)

> I found the "X" icon to be too uncertain, and have replaced it with a button.

I've done this but the `<Button>` component in default mode (ie: `isDefault`) looks different to what you've provided. Is your version a custom button style or shall we stick with what's coming down the CSS cascade (see highlighted in screenshot).

> Hopefully the new button and the GIF above help explain how this flow works.

Yes thank you. However, I'm still wondering whether it addresses the following scenario:

"As a user editing a link, when I have an existing link I should see a way to remove it so that I can get rid of the link from my text"

I know I _could_ hit `Change` and then clear the input and then close the popover but that feels long-winded and ambiguous in terms of how the code should handle the state and flow.

Would it be useful to have a dedicated (and _explicit_) remove button somewhere?  

Another question is regarding link colors for the selected item link. I'm just inheriting browser defaults for hyperlinks, but can I confirm you'd like to use something from [`_variables.scss`](https://github.com/WordPress/gutenberg/blob/0ee2b784c10ace28f6c84d079ec601ff80a76199/assets/stylesheets/_variables.scss)?

**Comment by getdave** [comment]
# Questions for Core Editor chat (16th Oct 2019)

* Should we extend `URLInput` and/or `URLPopover` or create a new component - note I'm still researching this so I can provide information on if this is a suitable approach.
* How can I best add an _additional_ query for `categories` to [this method](https://github.com/WordPress/gutenberg/blob/f5a7e6558e2c074161b240def55605d42d615964/packages/editor/src/components/provider/index.js#L30) which is used to retrieve the list of search suggestions?

**Comment by paaljoachim** [comment]
(I added the below comment directly to the PR but it seems better to add it directly to this issue instead.)

Can we get a text field box/line to where we can just rename the link? Instead of having to click the link directly and renaming it there it would be easier to have a name that link box. Here is an idea I added earlier: #17378

Use case:
Having multiple words as a link. This can be somewhat difficult to accomplish directly in the link text and much easier in a dedicated link text box.

**Comment by mtias** [comment]
@getdave let's consider any extra info for remote links to be an enhancement post v1, should not be a priority.

Likewise with updating `URLInput`, we need to get the initial merge for navigation menu to start seeing how things behave and where we want to consolidate with regular link interface.

**Comment by draganescu** [comment]
@mtias you might want to develop a bit on:

> Likewise with updating URLInput, we need to get the initial merge for navigation menu to start seeing how things behave and where we want to consolidate with regular link interface.

Does it mean in your view that the current component should be added to the `NavigationMenu` and then consider updating `URLInput` in the future, taking into account the issues and successes of having the `LinkControl` used in `NavigationMenu` ?

In that case `LinkControl` should be marked `__experimental*` so that no one starts depending on it.

**Comment by getdave** [comment]
@mtias Thanks for the direction here. As there seems to be some ambiguity, could you possibly clarify if you feel the below reflects how you think we should proceed:

* All enhancements relating to fetching information about remote URLs is a v2 and **not for this PR**.
* Adding `Categories` to the search results (currently endpoint only returns Posts) is a v2 and **not for this PR**.
* We should continue focusing on refining the current approach of **a new component** called `LinkControl` and not attempt to refactor `URLInput` or `URLPopover` _at this stage_. 
* (If yes to the above) The new component should be marked as "experimental".
* In the future, if the `LinkControl` is deemed acceptable, that is when we will decide how it is best to add this to existing areas where a "select a link" control is required. 

The way we proceed here will have a large impact on delivery times and scope of work, so it would be great if we could agree a route forward.

Many thanks.

**Comment by mtias** [comment]
That's correct.

**Comment by getdave** [comment]
As a result of the above I'm going to proceed as follows:

* Raise Issues for 
  - adding `Categories` into search suggestions
  - fetching information about remote urls 
  - routes for integrating the new component into Gutenberg 
* Make component as `__experimental` in the export
* Update automated tests to cover more of the functionality of this component.
* Fix automated tests for `URLInput` component.
* Document changes to `URLInput` and refine as required.
* Request final design review.

If anyone is aware of anything else they would like to see addressed prior to merge of this as a v1 please let me know here. Much appreciated.

**Comment by shaunandrews** [comment]
Since we'll no longer have the favicon or page title in this iteration, I've updated the design a little for adding a URL-based link:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/191598/67304857-79742b80-f4c2-11e9-9688-157be8068a49.png">

**Comment by retrofox** [comment]
> Likewise with updating URLInput, we need to get the initial merge for navigation menu to start seeing how things behave and where we want to consolidate with regular link interface.

Just FYI: https://github.com/WordPress/gutenberg/pull/18062

**Comment by aduth** [comment]
I'm circling back here from #20007 (and #20052), I observe that some of the early mockups incorporated the "Open in New Tab" as part of the edit state, but it was later suggested for removal.

From: https://github.com/WordPress/gutenberg/issues/17557#issuecomment-541125677

> I think we can ditch the ever present new tab switch, and only show it once a link has been added or selected. To overview the changes in the above GIF:

Per #20007, I don't think this is something we would want to do, since it would require that we make the preview state focusable, presumably requiring an additional step in the workflow. One of:

- <kbd>Cmd+K</kbd> shifts focus to the preview and not immediately to the URL editor (this is now the new behavior as of #19462)
- Or: <kbd>Enter</kbd> after editing a URL would keep focus in the popup, rather than move back to the paragraph

If it's agreeable, I would like to propose that the toggle be made available as part of the editing of the URL, perhaps more like some of the earlier mockups. I am beginning to explore this in #20052.

**Comment by phpbits** [comment]
@aduth @getdave Did the `LinkControl` plan changed? I'm trying if this is possible : https://github.com/WordPress/gutenberg/issues/18833#issuecomment-562203364 but there seems to be no option on adding custom toggle/options in the LinkControl. Did I miss something? Thanks!

**Comment by aduth** [comment]
@phpbits That code appears to be stale. There is a `settings` prop that supports providing custom settings configurations.

See: https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md

Note that this component is currently experimental and I expect it will probably remain so as of WordPress 5.4, so there may still be breaking changes in the future to how the component works.

In the meantime, it is available at `wp.blockEditor.__experimentalLinkControl` (from the `wp-block-editor` script handle).

#18061 appears to have been created as the "next steps" tracking issue for this.

**Comment by phpbits** [comment]
Thanks @aduth! I thought it's out of experimental because link format is using it on the Gutenberg plugin. I'll just use the URLPopover for the meantime. Thanks again!
