### ISSUE TITLE
Can't paste paragraph block contents inside quote block

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#17553]
Pasting paragraph blocks into a quote block replaces the quote block with paragraph blocks, instead of transforming the text of the paragraph blocks to be normal text inside a quote block.

There may be other combinations of blocks where a similar behavior occurs.

### Reproduction steps

1. Write several paragraphs of text as normal paragraph blocks
2. Insert an empty quote block
3. Copy/cut the paragraph blocks from step 1
4. Click inside the quote block, and paste

### Expected

The text from all of the paragraph blocks should be inserted into the quote block, just as if they had been typed.

### Actual

The quote block is removed, and the text is pasted as paragraph blocks, instead of paragraphs of text inside a _quote_ block.

**Comment by KokkieH** [comment]
Possibly related, if you paste multiple paragraphs of text copied somewhere else into a quote block, only the first paragraph appear in the quote block, with subsequent paragraphs getting pasted in as paragraph blocks instead.

**Comment by supernovia** [comment]
I run into this frequently as well. It seems most html block-level elements (lists, paragraphs, etc) can't survive the quote block.

**Comment by zdenys** [comment]
Somewhat related [feedback about the experience of trying to transform two-paragraph blocks and an ordered list block into a quote block](https://wpmainline.com/2021/08/06/why-cant-i-transform-two-paragraph-blocks-and-an-ordered-list-block-into-a-quote-block/).

**Comment by zdenys** [comment]
Cross-linking a PR for easier searchability of where the work is happening. The work requires changing how quotes work and a good balance has been hard to reach. More details here: https://github.com/WordPress/gutenberg/pull/25892

**Comment by starapple2** [comment]
At least they could set a prompt to "Paste as plain text?"

**Comment by mtias** [comment]
This should be fixed after #25892.
