### ISSUE TITLE
Is there a way to remove the .is-style prefix in an element?

### ISSUE THREAD

**Issue by pmqa** [WordPress/gutenberg#17554]
I'm using **wp.blocks.registerBlockStyle** to add a style variation to a text element: 

`wp.blocks.registerBlockStyle( 'core/heading', {
		name: 'default',
		label: 'Default',
		isDefault: true,
	} );
`

Is there an option to remove the **.is-style** prefix that appears in this element, in this case **.is-style-default**? 

Maybe we could add a `hasPrefix: false` parameter?

**Comment by swissspidy** [comment]
What‘s the use case for that?

The default style doesn‘t add a class name anyway AFAIK.

**Comment by pmqa** [comment]
A cleaner style (sass) codebase. Being able to use the same cleaner style classes everywhere: **.page-title** instead of **.is-style-page-title**.

**Comment by jstrangfeld** [comment]
This is a duplicate of #11763
