### ISSUE TITLE
Selecting "Media Library" in Gallery Block opens upload screen

### ISSUE THREAD

**Issue by hugobaeta** [WordPress/gutenberg#17563]
**Describe the bug**
It seems that, in the block placeholder for the Gallery block, when selecting the "Media Library" button we get the Media modal opening in the last tab visited. If the last tab was "Upload", then you get that. We should make sure the button action is matching what it says.

**To reproduce**
1. Add a Gallery block
2. Click "Media Library"
3. The Media modal opens in the last used tab (in this case "Upload") instead of opening what the button says it will open.

**Expected behavior**
I expect the Media Library tab to be selected when I click the "Media Library" button.

![gallery](https://user-images.githubusercontent.com/1514660/65554076-611dea80-dedd-11e9-938f-9a87f39ea219.gif)

<img width="626" alt="Screen Shot 2019-09-24 at 3 09 21 PM" src="https://user-images.githubusercontent.com/1514660/65554081-6713cb80-dedd-11e9-80cb-539ae7f29a0a.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.6)
 - Browser: Chrome
 - Version: 77

**Additional context**
- Gutenberg bundled with core in 5.2.3.

**Comment by jorgefilipecosta** [comment]
Hi @hugobaeta thank you for reporting this issue. In my tests, it seems it will be fixed on WordPress 5.4.
