### ISSUE TITLE
Parameter inconsisntency found in gutenberg_provide_render_callback_with_block_object()

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#17568]
Hi Team,

There seems to be an inconsistency with the way `WP_Block_Type::render_callback` is called between WordPress core and the Gutenberg plugin.

This can be seen within the [gutenberg_provide_render_callback_with_block_object()](https://github.com/WordPress/gutenberg/blob/1b3274fd6ee4bba03472f9b7f99f60d5ff3f3df1/lib/compat.php#L43) function, which is calling the `render_callback()` with and extra `$block` parameter.

For reference, the `WP_Block_Type::render_callback` is called with only two parameters:
```
call_user_func( $this->render_callback, $attributes, $content );
```

Here, however, the `WP_Block_Type::render_callback` is called with three parameters; 
```
call_user_func( $block_type->render_callback, $prepared_attributes, $block_content, $block );
```

Is this a mistake, or an upcoming change to WordPress core?

**Comment by youknowriad** [comment]
This is tracked in this core ticket https://core.trac.wordpress.org/ticket/48104 
For now, the ticket is targetted for WP 5.4.
