### ISSUE TITLE
Inconsistent markup classes in core blocks with columns

### ISSUE THREAD

**Issue by hugobaeta** [WordPress/gutenberg#17560]
There are at least two core blocks with multi-column support, `galleries` and `columns`. They both use classes to indicate the amount of columns, but the classes naming is inconsistent: one uses `columns-2 ` and the other `has-2-columns`, respectively.

I'd expect the classes to match, since they give you, functionally, the same result.

<img width="420" alt="Screen Shot 2019-09-24 at 2 15 31 PM" src="https://user-images.githubusercontent.com/1514660/65551029-c837a100-ded5-11e9-916c-9c4ae362f810.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.6)
 - Browser: Chrome
 - Version: 77

**Additional context**
- Gutenberg bundled with core in 5.2.3.

**Comment by youknowriad** [comment]
Hi there! thanks for the issue and good observation.

The `hax-x-columns` has been removed from the columns block though in the last plugin version and the upcoming WP 5.3.
