### ISSUE TITLE
"Convert to Blocks" not working

### ISSUE THREAD

**Issue by thetwopct** [WordPress/gutenberg#17570]
**Describe the bug**
Moved a site to Gutenberg using latest plugin version 6.5. 
Trying to convert pages Classic Editor blocks in to Gutenberg blocks.
When clicking the "Convert to Blocks" option for the block, nothing happens. 
No error console message or other errors.

**To reproduce**
1. Write text in Classic Editor
2. Enable Gutenberg
3. Click convert to Block
4. Watch nothing happen

**Expected behavior**
I would expect the old Classic content to be turned in to blocks

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Safari 12.1.2

What could be causing it? How does the convert option work? Thanks 🙏

**Comment by youknowriad** [comment]
Would you be able to prove the content of the post you're trying to convert?

**Comment by thetwopct** [comment]
I cannot, but this is on all content, so a few basic p paragraphs, or something with a shortcake in it.

**Comment by youknowriad** [comment]
We can't reproduce this. I'd suggest trying to disable the plugins you're using one by one to see if there's any incompatibility.

**Comment by thetwopct** [comment]
How does the convert option work? What does it use? The JSON feed?

**Comment by youknowriad** [comment]
no, it parses HTML and produces blocks. Some things just can't be converted and will stay as is.

**Comment by thetwopct** [comment]
Fixed it. As I was doing this on a staging site there were non-secure images being pulled in to the page. As soon as I removed them, the conversion worked. 

`The page at xxx was allowed to display insecure content from xxx`

So non-secure content will prevent the "convert to blocks" option working.

**Comment by Inwerpsel** [comment]
Pressing a button and seeing nothing happen can be quite confusing, especially if a user is expecting something to happen. That user might be unfamiliar with html, so cannot see the reason why block A converts, while block B stays a html block.

Wouldn't this be easily mitigated by showing some kind of message whenever clicking "Convert to blocks" results in no changes (i.e. 1 html block before => the same html block after)? Something like "We tried, but cannot further convert this into blocks"?

Currently the behavior is indistinguishable from a bug or from the editor being unresponsive for most users.

**Comment by stefanfisk** [comment]
I just encountered this, here the gist of the offending HTML: https://gist.github.com/stefanfisk/a8ac166660657145008661f6905e5920

**Comment by stefanfisk** [comment]
It seems like `Convert to Blocks` is broken on my site even for fairly simple HTML. Does anyone have any tips on how to go about debugging this feature?
