### ISSUE TITLE
Dropped radio buttons

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17589]
I am not sure if this is because of the 5.3 beta patch but you can see dropped radios here:

![image](https://user-images.githubusercontent.com/253067/65645972-69ffe080-dff1-11e9-97bd-5ab39606c84d.png)

**Comment by jorgefilipecosta** [comment]
It seems like this problem is also happening in core radio components:
<img width="266" alt="Screenshot 2019-09-26 at 15 13 40" src="https://user-images.githubusercontent.com/11271197/65696057-83943d00-e070-11e9-89e3-30490099ac14.png">

**Comment by enriquesanchez** [comment]
For reference, this is how it should look:

![image (1)](https://user-images.githubusercontent.com/3276087/65704874-fab7da00-e04c-11e9-9c71-417e0570bd9b.png)
