### ISSUE TITLE
Gallery Block: Captions are breaking layout in left- or right-aligned galleries.

### ISSUE THREAD

**Issue by kwight** [WordPress/gutenberg#17584]
**Describe the bug**
The new gallery captions are breaking layout in galleries that are not center-aligned.

<img width="1289" alt="Screen Shot 2019-09-25 at 1 04 45 PM" src="https://user-images.githubusercontent.com/349751/65636057-61c68780-df96-11e9-84c3-bcbea3f28c78.png">

When switching back to center-aligned from another alignment, the same breakage happens:

<img width="1119" alt="Screen Shot 2019-09-25 at 1 04 28 PM" src="https://user-images.githubusercontent.com/349751/65636092-7b67cf00-df96-11e9-91a8-df04189a4e36.png">

**To reproduce**
1. Add a Gallery block.
2. Align it left or right.
3. Notice that the dropzone is no longer 100%.

**Expected behavior**
The uploader dropzone should be the same full width of the gallery regardless of alignment.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [master]

**Comment by epiqueras** [comment]
It's happening with galleries that have a left, right, or center alignment. Every other alignment or no alignment at all works fine.

Here's the fix: #17586.
