### ISSUE TITLE
Add spacing or remove top line on keyboard shortcuts

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17588]
Currently, the top line is very close to the top section:

![image](https://user-images.githubusercontent.com/253067/65645879-0c6b9400-dff1-11e9-823b-f6fce912788a.png)

I would recommend adding spacing or removing the top line.

**Comment by mapk** [comment]
I agree here. The initial mockups hid this quite well. In fact, I believe the PR did too at one point. Maybe something changed causing it to drop down again and show the top border? Let's definitely clean this up. 👍

**Comment by JuanVqz** [comment]
Hi! I didn't see the mistake anymore.

If is ok, maybe you could close the issue.
Regards

![image](https://user-images.githubusercontent.com/7331511/67977870-87baf980-fbde-11e9-8c00-d08b8777a68e.png)

**Comment by mapk** [comment]
The problem still exists. I'll try to knock this out soon.

![Screen Shot 2019-11-06 at 6 11 12 PM](https://user-images.githubusercontent.com/617986/68354301-db3ab500-00c0-11ea-98b1-5858063c67ed.png)

**Comment by JuanVqz** [comment]
I could help but I didn’t see, what is the file? When selecting a block it shows?

**Comment by mapk** [comment]
@JuanVqz, which version of Gutenberg are you using? It looks like the keyboard shortcut panel reveals it might be an older version? Do you have the Gutenberg plugin installed and updated?

**Comment by JuanVqz** [comment]
Right now I don’t know what version I have but I think is a new version because I downloaded recently. (Like 6 days ago)
tomorrow I could share my version
