### ISSUE TITLE
Update Button styles to match Core

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17585]
With the advent of new UI changes in Core (WordPress 5.3) which [update the buttons styles](https://core.trac.wordpress.org/ticket/34904#comment:47) ([Trac ticket 34904](https://core.trac.wordpress.org/ticket/34904#comment:47)), Gutenberg should also work to match that style.

**Current Gutenberg button styles:**

![Screen Shot 2019-09-25 at 2 16 37 PM](https://user-images.githubusercontent.com/617986/65640394-2086a580-df9f-11e9-926c-7fd4aaccb905.png)

**New Core styles:** (Notice the absence of dropshadow and strong border on secondary button)

![Screen Shot 2019-09-25 at 2 33 58 PM](https://user-images.githubusercontent.com/617986/65641475-b0c5ea00-dfa1-11e9-8422-f3762e4bea86.png)

![Screen Shot 2019-09-25 at 2 37 05 PM](https://user-images.githubusercontent.com/617986/65641577-03070b00-dfa2-11e9-8ae5-73183f95151b.png)

**Comment by karmatosed** [comment]
![image](https://user-images.githubusercontent.com/253067/65645791-d29a8d80-dff0-11e9-9382-3caa24bd9a54.png)

I am not super surer this is a bug (it might be), but we need to iterate on this page too. Notice the buttons are out of line.

**Comment by mapk** [comment]
@karmatosed your image there also appears to show the new default buttons style, but the old primary style too? Am I seeing that right?

**Comment by talldan** [comment]
I've made a little adjustment to buttons on https://github.com/WordPress/gutenberg/pull/17601, which I was thinking of holding back until after WP5.3.

However, if all buttons are being updated anyway, it might be something to incorporate into that change.

**Comment by swissspidy** [comment]
@mapk looks like it, because the primary button there is inserted by Gutenberg via JS.

**Comment by youknowriad** [comment]
Here's the trac ticket to follow the last updates of the design https://core.trac.wordpress.org/ticket/34904

**Comment by karmatosed** [comment]
@mapk yes for some unknown reason that page seems to be stuck to old styling ... super weird.
