### ISSUE TITLE
Select drop downs out of line in beta 1

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17587]
![image](https://user-images.githubusercontent.com/253067/65643474-bb0bd680-dfe9-11e9-9f57-f971dacbafc8.png)

Looks like the work done on input fields has negatively effected the Gutenberg dropdowns. This is for all.

**Comment by talldan** [comment]
This is looking better after using the latest patch on https://core.trac.wordpress.org/ticket/47477#comment:27

Might not need a gutenberg fix.

**Comment by karmatosed** [comment]
Ok, let's close this one now then and leave it as a core patch. Thanks.
