### ISSUE TITLE
Input button out of balance with action button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17592]
I was testing the beta changes on inputs and discovered this:

![image](https://user-images.githubusercontent.com/253067/65646204-37a2b300-dff2-11e9-9c11-45fbe55d2944.png)

I will test other blocks but to me it feels too out of balance.

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed,
It seems that in your screenshot the button and the input field are not aligned, the button seems smaller.
But when testing Gutenberg master with last WordPress trunk things seem aligned.
2020:
![image](https://user-images.githubusercontent.com/11271197/65699250-b7259600-e075-11e9-94c7-ec282e1a6c44.png)


2019:
![image](https://user-images.githubusercontent.com/11271197/65699313-d15f7400-e075-11e9-9b30-d21abff8e47b.png)

Do you think things look good on these screens or there is still some improvement we should do?

**Comment by karmatosed** [comment]
It is still out of line but a little less on today's svn up. I tried in different themes just incase.

Twenty Nineteen:

![image](https://user-images.githubusercontent.com/253067/65705814-0f15ca00-e081-11e9-9f70-398210cd86dd.png)

Twenty Twenty:

![image](https://user-images.githubusercontent.com/253067/65705889-310f4c80-e081-11e9-8ffd-8d512eaabd7b.png)

**Comment by enriquesanchez** [comment]
I can confirm there's a tiny offset between the two:

<img width="449" alt="Screen Shot 2019-09-26 at 12 26 26 PM" src="https://user-images.githubusercontent.com/3276087/65710634-00b3b800-e059-11e9-8e06-e9ee774114c8.png">
