### ISSUE TITLE
Date picker formatting out of line

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17590]
Since beta 1 (I think) the date picker now looks like this:

![image](https://user-images.githubusercontent.com/253067/65646037-93b90780-dff1-11e9-80ad-eb63c1225860.png)

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed,
Currently, the date picker appears like this for me (last Gutenberg master and last WordPress trunk):
![image](https://user-images.githubusercontent.com/11271197/65693138-b6880200-e06b-11e9-8c2e-028bbd69aac1.png)


The calendar is centered, while the date inputs just have the normal grid margin. Would you prefer the calendar to be uncentered and aligned with the input fields?

**Comment by karmatosed** [comment]
I think that seems fair @jorgefilipecosta. I also wonder if the latest patch has solved the issue of the dropped fields?
