### ISSUE TITLE
Formatting buttons do nothing in 'Text' editor mode

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#1759]
## Issue Overview
Using version 0.3.0 on a test install, the formatting buttons that are displayed when in 'text' mode rather than visual mode don't seem to do anything.

## Steps to Reproduce (for bugs)

1. Open up a post in the editor and switch to Text mode
2. Highlight a word
3. Click on a formatting button, for example to make the word bold or italic - nothing happens, no HTML tags are inserted

Seem using current version of Safari (10.1) on MacOS (10.12.5)

## Expected Behavior

I would expect to see insertion of HTML tags as happens in the current Text editor mode.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by afercia** [comment]
See #761

**Comment by afercia** [comment]
Closing because this is already tracked in #761
