### ISSUE TITLE
Cover image: clear media is just clearing settings

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17606]
To remove settings you 'clear media' on cover image. For me, this is 'clear' as you aren't removing or clearing any media.

![image](https://user-images.githubusercontent.com/253067/65683087-53d73c00-e054-11e9-8f43-da0f1cd33578.png)

**Comment by richtabor** [comment]
Here are some notes from discussing this in today's [Gutenberg Triage meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1570552344179600) (Slack link). 

1. Selecting "Clear Media" essentially **resets the block to its placeholder state** - although InnerBlocks content remains. Clearing the background color also resets the block to its placeholder state. This "reset" could very well lead folks to believe their InnerBlocks content has been lost - when the block resets to its placeholder state. 

2. Perhaps clearing media or background color settings **should not force the block back into its placeholder state**. Clearing media or background color would simply return a blank box with whatever InnerBlocks content the user has added to the block. Not only would this improve this interaction, it would add more flexibility to the block by allowing folks not to have background colors/images to the block. 

**Current Flow when selecting "Clear Media":**
![cover](https://user-images.githubusercontent.com/1813435/66415286-43ff1680-e9c9-11e9-883b-39dec6946c2e.gif)

**Comment by mapk** [comment]
Number 2 under @richtabor's comment above makes sense to me. Let's move forward with a `try/` PR around this concept.

**Comment by akasunil** [comment]
Current implementation of "Clear Media" is as below. It just clear the media attached to cover block background. 
Do we required to extend this functionality ? if not, we can close this issue i think. @richtabor 

![CleanShot 2024-03-14 at 14 39 02](https://github.com/WordPress/gutenberg/assets/61308756/c6909522-bf7e-4b42-a719-40e5156bd2cd)

**Comment by Mamaduka** [comment]
I think we can close this after #64630 is merged.

**Comment by akasunil** [comment]
I'm closing this since the `Reset` option is available now in toggle bar for the cover block. Added through PR https://github.com/WordPress/gutenberg/pull/64630

<img width="837" alt="image" src="https://github.com/user-attachments/assets/ef950bb0-e91e-4ab5-88b8-969bd9981cc9">
