### ISSUE TITLE
Separator style thumbnails too subtle

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17608]
I thought there was an issue for this and if there is one please close this (I wasn't able to find it). The style thumbnails for the separators are incredibly subtle, so much I couldn't see them.

![image](https://user-images.githubusercontent.com/253067/65684882-9a2e9a00-e058-11e9-9470-05a70d907ae4.png)

**Comment by mapk** [comment]
I've moved this issue to a comment on #17620.
