### ISSUE TITLE
Add Block: Table of Contents

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1760]
Had to delete all issue directions, as it is not a bug.

I know there are 2 issuse about  block. But I would like to ask for additional feature, block, a bit different. Just to se what others say about it. Can dare to say I needed it often.

As it is now it is easy to echo in template Post pagination, from "nextpage".  

- It is just numbers in most cases.
- It is like a black hole, never know what to expect when clicking on number.
- Not user friendly at all. 

I would like to ask for one new block with actually 2 under-blocks. 
One for "nextpage" pagination, and other (optional) for Table of Content (TOC). Like plugins below make it:

https://wordpress.org/plugins/table-of-contents-plus/
https://wordpress.org/plugins/bainternet-simple-toc/

It is needed often for serious news portals. Following a story that spans under long time period. 
Can be used for any story, article, on smaller websites, when some update about news comes after long time.

I tried before all those plugins but decided to stay away from them. Usually one man developing, in free time. And any sligh change in WP URL routing code makes those plugins have groove problems with permalinks. Not to mention additional problem with cache plugins. You are after all huge base of coders who could maintain this Gutenberg block much better.

**Comment by karmatosed** [comment]
For now closing this as it's not a required block for release. It may be something either someone makes as a plugin block or something later added. For now though, we have a table of contents within Gutenberg, just not a front end displaying one.

**Comment by heyakyra** [comment]
is there some way to use it without the front end for displaying?

**Comment by karmatosed** [comment]
@heyakyra what do you mean?

**Comment by heyakyra** [comment]
@karmatosed, you mentioned 

> we have a table of contents within Gutenberg, just not a front end displaying one.

so how does one take advantage of the ToC feature?

**Comment by karmatosed** [comment]
Ah thanks for context. Potentially yes someone could but that would require a separate plugin to be developed.
