### ISSUE TITLE
Publish button is a moving target

### ISSUE THREAD

**Issue by andfinally** [WordPress/gutenberg#17600]
**Describe the bug**

Publishing a post is the most delightful moment of using WordPress. But the block editor's addition of a second stage to publishing takes away something of that pleasure. I never want to do anything in the "Are you ready to publish?" form: I always just want to publish. The fact that the first and second publish buttons are in two different positions on the page makes this second stage feel even more like a hurdle. If the second button was in the same place as the first, I could at least keep my mouse where it is and just click on it. But instead I have to actively hunt for the second button.

**To reproduce**
1. Go to https://[ DOMAIN ]/wp-admin/post-new.php and create a draft post.
2. Click on the "Publish" button.

**Expected behavior**
I expect the second "Publish" button to appear in the same position as the first, so I can click on it without moving my mouse.

**Screenshots**
![publish-button](https://user-images.githubusercontent.com/1647564/65671802-d1dd1800-e03f-11e9-8c15-25a3de7c3f8e.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: FF
 - Version: 69 

**Additional context**
WordPress 5.2.3

An example where keeping targets in position helps usability is with notifications in Calypso. When you have a stack of multiple notifications, it's easy to close them all by keeping your mouse in position over the close button of the top one. When you dismiss that notification, the next notification's close button appears below your mouse.

**Comment by jorgefilipecosta** [comment]
It seems like this issue is fixed in the last version of WordPress.
