### ISSUE TITLE
Unclear dropzone in gallery

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17605]
I was doing a block test and for me the way this dropzone appears is unexpected.

![image](https://user-images.githubusercontent.com/253067/65682674-4ec5bd00-e053-11e9-9ae2-b7aa5a768b32.png)

I didn't expect to see buttons in what is a dropzone styling, which made me wonder could we move buttons out from this?

**Comment by mapk** [comment]
Good catch here. I no longer recognize this as a dropzone anymore now that it includes buttons.

This could use another redesign. Switching labels!

**Comment by enriquesanchez** [comment]
Could we replicate what we already do in the block placeholder of images/galleries, etc?

<img width="533" alt="Screen Shot 2019-10-07 at 2 30 32 PM" src="https://user-images.githubusercontent.com/3276087/66342439-08077b00-e90f-11e9-8880-2f782fc35d51.png">

While there's no visible "drop zone", the whole area acts as one:

<img width="653" alt="Screen Shot 2019-10-07 at 2 25 40 PM" src="https://user-images.githubusercontent.com/3276087/66342489-266d7680-e90f-11e9-93a6-87001acd0e05.png">

So it could end up looking like this:

<img width="577" alt="Screen Shot 2019-10-07 at 2 26 26 PM" src="https://user-images.githubusercontent.com/3276087/66342512-31280b80-e90f-11e9-9a64-97eda2b2fb9d.png">

In this mockup, I've moved 'Write gallery caption...' above the drop zone and closer to the images.

**Comment by youknowriad** [comment]
Should we close this as a duplicate of #21247

**Comment by karmatosed** [comment]
I think so @youknowriad.
