### ISSUE TITLE
Auto Draft set as post title

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#17628]
**Describe the bug**

When I create a new post in Gutenberg and publish with some content but **no** title, it gets saved with the title set to “Auto Draft”.

I have to remove the title again and change the slug when I really want a post without a title.

**To reproduce**
1. Create new post
2. Write some content
3. Publish post
4. See "Auto Draft" title.
5. View post on frontend, notice "Auto Draft" title and "auto-draft" slug.

**Expected behavior**

The post should have no title and its ID as the slug.

**Screenshots**

![Screenshot 2019-09-27 at 11 11 54](https://user-images.githubusercontent.com/841956/65757643-dd9c0d80-e117-11e9-9672-38a2455d1087.png)

Video: https://cloudup.com/c5bALGfxT_8

**Additional context**
- Chrome 77 on macOS
- Current Gutenberg master
- WordPress 5.3-beta1-46334 running Twenty Nineteen theme
- PHP 7.3 and MySQL 5.6 on Apache

The same issue with "Auto Draft" was reported in #6614, but the bigger issue there was a nginx misconfiguration.

#8770 is kinda related too.

**Comment by brentswisher** [comment]
I tried looking into this. I suspect it is related to the changes here: https://github.com/WordPress/gutenberg/pull/17317, but I haven't been able to find a solution to the problem. I thought it might be worth it to bring that PR to the attention of anyone else looking into this.

Also might be worth noting that the title gets set to "Auto Draft" when starting a new post, adding content and manually saving it as a draft, not just when publishing.

**Comment by joyously** [comment]
Is this related to what happens when you click Preview? It seems to save the post and you can get out of the editor without a prompt to Save even if you didn't ever click Save or Publish.
