### ISSUE TITLE
Impossible to select Column if it is the only item in the page

### ISSUE THREAD

**Issue by simonclay** [WordPress/gutenberg#17624]
**Describe the bug**
If the only item in a page is a Column, it is not possible to see the 'Column Handle' when hovering.

**To reproduce**
1. Create new page
2. Choose Columns as the first block
3. Add content to the columns.
4. It is not possible to select the 'Column Handle' to enable adding more Columns

**Expected behavior**
I would expect to be able to click the Column Handle to add more columns to the existing block

**Screenshots**
![Screen Shot 2019-09-27 at 09 06 21](https://user-images.githubusercontent.com/2143351/65753399-d91b2900-e106-11e9-997b-05038b34263d.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser [chrome and safari]

**Additional context**
WordPress 5.2.3

**Comment by youknowriad** [comment]
To solve this kind of nesting issues, we've added three things:

 - The Block Navigation menu (top toolbar)
 - The Select mode that allows you to select blocks from parent to children using multiple clicks
 - The breadcrumb in the footer with the hierarchy of the currently selected block.

I think we're in a better position now and we can close this issue.
