### ISSUE TITLE
How to highlight words in the paragraph blocks ?

### ISSUE THREAD

**Issue by hassanz** [WordPress/gutenberg#17639]
Hello,

I am trying to build a plugin where I have to highlight a word in the paragraph block.
I know the clientId of the block and the word and its offset value. 

I am currently using pure javascript `replace` function but I believe there should be a better to do this with the APIs. I see there is [annotation ](https://developer.wordpress.org/block-editor/developers/block-api/block-annotations/)api but it is not available for me.

![image](https://user-images.githubusercontent.com/1437800/65838166-3ad9bf80-e2ce-11e9-9087-447c4c47944c.png)

And I am not sure if or how can I use the rich-text module to do that as well.

Is there an easy way of highlighting words in a block ?

**Comment by swissspidy** [comment]
Since annotations are still experimental, they are not enabled by default. Try enqueueing the `wp-annotations` script in your plugin to load it. Then the data store should be available to you.
