### ISSUE TITLE
Options under "three dots" are sometimes inaccessible 

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#17636]
**Describe the bug**
If I use a larger font on a smaller screen, some of the options under the "three dots" menu in the upper right are cut off and inaccessible through scrolling.

What I see with zoom at 0 on my MacBook Air:
![Screen Shot 2019-09-27 at 2 17 22 PM](https://user-images.githubusercontent.com/3476361/65800191-0f6e9d80-e133-11e9-81e7-7a65713901a9.png)

What I see if I "zoom" in my screen for accessibility - I can't scroll to see more:
![Screen Shot 2019-09-27 at 2 17 40 PM](https://user-images.githubusercontent.com/3476361/65800185-0bdb1680-e133-11e9-9052-a65cfb9f58b9.png)

**To reproduce**
Use a smaller screen, zoom in for accessibility. Note the menu gets cut off.

**Expected behavior**
The menu should scroll or wrap so options are available.

**Screenshots**
See above

**Desktop (please complete the following information):**
Any laptop if you zoom in a bit. I was using Chrome on Mac, both current.

**Additional context**
Reported here:
https://en.forums.wordpress.com/topic/block-editor-settings-not-fully-displayed/

Tested on .com and .org.

**Comment by ZebulanStanphill** [comment]
This is happening to me as well. Using Gutenberg 6.5 on WordPress 5.2.3; using a browser based on Chromium 76.

**Comment by Ringish** [comment]
I can scroll the menu on a fresh fork with WordPress 5.4-alpha-46582-src.

**Comment by Soean** [comment]
@Ringish Thanks for your feedback!

I also tested in Chrome, Firefox and Safari with the current master and was able to scroll. Please reopen if you still can reproduce this issue in any browser.
