### ISSUE TITLE
Focus change in "Publish" makes date picker re-render & jiggle

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#17644]
**Describe the bug**
When attempting to change the values in the date that something will be published, the "Immediately" text changes to a formatted date/time, which causes the pop-up date picker to quickly close and reopen again in a new location.

**To reproduce**
1. Go to 'Add New' page/post in WordPress
2. Click on 'Immediately' to change the Publish date
3. Click on any field in the date picker, then change focus to any other field in the picker
4. See that 'Immediately' changes to a date/time, and watch the date picker hide and reappear in a new location

**Expected behavior**
This date picker should be persistent. When it's open, it should stay open. When it's closed, it should stay closed. The content of the link/button/label changing should not trigger a close/open of the same date picker.

**Screenshots**
QuickTime Movie compressed: [month-select-click.mov.zip](https://github.com/WordPress/gutenberg/files/3669138/month-select-click.mov.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.1 (15608.2.11.1.8)

**Additional context**
- WordPress 5.3 Beta

**Comment by ehti** [comment]
Looks like this isn't happening anymore in Gutenberg 7.9.1, so closing. Please ping if you're still running into it. :)
