### ISSUE TITLE
Link control modal is on top of quick toolbar menu items

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1764]
## Issue Overview

When you are on a link in the text, a modal of the link pops up in your face.
This popup is higher than quick toolbar menu sliding down.

## Steps to Reproduce (for bugs)

1. Create a block
2. Insert some text and create a link on it
3. Focus the block and see the link modal opening
4. Use the quick toolbar to change the block type
5. See the link modal floating above, obscuring items in the menu

<img width="795" alt="new_post_ _test_ _wordpress" src="https://user-images.githubusercontent.com/2005352/27918957-c5d1d0cc-6270-11e7-96d2-c671d3fd4d36.png">

## Expected Behavior

When a menu is opened, the link modal should be hidden.
If the order is moved down the z-index it still confuses visually.

## Todos
- [ ] Tests
- [ ] Documentation

Plugin version: 0.3.0

**Comment by westonruter** [comment]
I've been experiencing this on `master` as well.

**Comment by afercia** [comment]
On latest master (post 0.4):

![screen shot 2017-07-10 at 16 54 42](https://user-images.githubusercontent.com/1682452/28024292-96c91bfa-6590-11e7-93ef-e550586548dd.png)

**Comment by karmatosed** [comment]
This looks to be fixed:

![2017-09-04 at 20 44](https://user-images.githubusercontent.com/253067/30037351-dea49c72-91b1-11e7-8380-4d6c353fe22f.png)

If it's not, please let me know what browser to check against.
