### ISSUE TITLE
UX for the alignwide alignfull and align "none"

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#17654]
Hi

When you enable:
add_theme_support( 'align-wide' );

The UX to change and go back to align "none" basic state is not clear
![Capture d’écran 2019-09-30 à 15 30 17](https://user-images.githubusercontent.com/2622001/65883613-adfb3880-e397-11e9-8beb-1f912dfcf058.jpg)

You have to click again on the current state to go back to normal. 
It would be much more simple to list all the align state.

**Comment by paaljoachim** [comment]
Hi @davouid 

Thanks for creating this issue!
A lot of time has passed and I see that this has been overlooked.
Is the issue still valid?

**Comment by carolinan** [comment]
This is the same problem described here:
https://github.com/WordPress/gutenberg/issues/30724

I would really like to understand why this is problematic for the widths, but not for other options.
Why it is not clear that clicking the icon a second time disables the option.
For example, if you make a text bold, then you also need to click that icon again to remove the bold.
