### ISSUE TITLE
extend BlockList component

### ISSUE THREAD

**Issue by niklasp** [WordPress/gutenberg#17656]
I want to change the containing dom element of the `BlockList` to a custom component. It is contained in [this line.](https://github.com/WordPress/gutenberg/blob/29ad4d8740b04b5bf094b6901cccd71552767cb3/packages/block-editor/src/components/block-list/index.js#L207). Is that possible somehow? What I want to achive is that the `BlockListBlock` items do not appear in the surrounding div but in my custom one. I need it for a custom slider component, where all innerBlocks should become slide Items.

Something like 
```
<MySliderComponent>
  { blockClientIds.map( ( clientId, index ) => {
    ...
  }
</MySliderComponent>
```

Or is there any other way to get the Edit Components of a block? Something like a `BlockList`-Filter? There is only filters for `BlockListBlock` and `BlockEdit` as far as I see.

**Comment by swissspidy** [comment]
There's currently no such filter and as such it is not possible to change this from a `div` to something else.

**Comment by niklasp** [comment]
And is there any way to import the `BlockEdit` components? They are not exported. Maybe this would be a feature? E.g. if someone wants to edit blocks in a modal or in a slider, or any other context, without putting the whole `<InnerBlocks>` Component to that place?

**Comment by niklasp** [comment]
Maybe this can help me later https://developer.wordpress.org/block-editor/packages/packages-block-editor/ ?!

**Comment by niklasp** [comment]
Are there updates on this? @swissspidy can the new gutenberg render single innerblocks? Like in a map function?
