### ISSUE TITLE
Social links Block Style is repeating for 3 times

### ISSUE THREAD

**Issue by AbmSourav** [WordPress/gutenberg#17650]
**Social links**
Block Styles, Styles, Default Style. The same thing is repeating for 3 times.

**Expected behavior**
I think only **Styles** section is enough instead of 3(Block Styles, Styles, Default Style)

**Screenshots**
![social link block](https://user-images.githubusercontent.com/39233955/65875713-a6448f80-e3a9-11e9-955f-42ffcf04f256.png)

**Desktop:**
 - OS: PC
 - Browser: Chrome
 - Version: 77

**Additional context**
Gutenberg version: 6.5.0

**Comment by swissspidy** [comment]
It is worth noting that the "Default Style" option serves a different purpose than the other selection — it allows you to select the default style that should be used whenever you insert a block of this type. So it's not the same as the others.

**Comment by jasmussen** [comment]
This is a high level question about not just the social links styles, but about block styles in general (see Quote also).

Stepping back a little, the block toolbar is for primary actions, the sidebar is for secondary actions. In some cases redundancy — repeating the same UI in two places — is okay when it’s an important UI. Same as we have tags and schedule settings repeated in the pre-publish flow.

The visual design could use a refresh, both in the sidebar and block toolbar, sure. Notably I'd love to find a new design pattern for style variations that can perhaps embrace the _orientation_ transform tool that has been added to Buttons and Navigation blocks to change direction from horizontal to vertical. #27331 affords a place to explore a better visual for style transforms. One mockup that was made as part of that effort, but could use more attention, is this one, based on work by @shaunandrews :

<img width="335" alt="Screenshot 2021-02-03 at 08 38 39" src="https://user-images.githubusercontent.com/1204802/106713862-5445f680-65fb-11eb-9031-9e9a3acf9a27.png">

Fundamentally I see nothing wrong about redundancy, though.

**Comment by paaljoachim** [comment]
Thank you for the really good feedback, Joen!

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this as the components have since been redesigned the default control has been removed altogether. Please feel free to reopen if needed.
