### ISSUE TITLE
Media/Text Block: Reset column width to 50% / 50% again

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17672]
Hey, after manually changing the column width of the media / text block, I can not reset the column width to the starting point of 50% / 50%. The main problem is that I do not see the column values ​​when changing the width.

How can I easily solve this problem without creating a completely new media / text block?

**Comment by simonhammes** [comment]
Here's what worked for me:
* open the code editor
* change the `mediaWidth` property to 50
* remove the whole style attribute of the div `.wp-block-media-text`

**Comment by CreativeDive** [comment]
@simonhammes thank you. But this is not a user-friendly way :-)

**Comment by koke** [comment]
I think having the resize snap at 50% could be a good solution, and the underlying library [seems to support that](https://bokuweb.github.io/re-resizable/?path=/story/snapping--absolute).

**Comment by CreativeDive** [comment]
I think the best practice is to show the percentage values of both columns while scaling it. So the user can easily see and set the same values, if the media / text block is used multiple times.

**Comment by bozzmedia** [comment]
Yes, please. Still a need for this heading into 2021.

**Comment by BusinessBloomer** [comment]
+1 

I find it difficult to resize columns without knowing their width percentages. A simple "50/50", "49/51", "30/70" label while you resize may be sufficient.
