### ISSUE TITLE
Block Switcher does not always show all Text block types

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1767]
It confused me that the options you get in the Text block switcher are contextually limited. It makes sense that you cannot convert text into an image (or whatever non-text blocks there may be), but for example, if I have a Text block I get the option to turn it into a Quote/List/Formatted/Heading, but when it is a Heading, I can only change it to Text or Quote. Why is that?

**Comment by westonruter** [comment]
Each block can have a `transforms` property that defines how the block converts from and into other block types. For example:

* `list`: https://github.com/WordPress/gutenberg/blob/master/blocks/library/list/index.js#L79-L134
* `preformatted`: https://github.com/WordPress/gutenberg/blob/3037de6fa9d4a405a2acfbde8a9917ac4c7de049/blocks/library/preformatted/index.js#L26-L43
* `heading`: https://github.com/WordPress/gutenberg/blob/3037de6fa9d4a405a2acfbde8a9917ac4c7de049/blocks/library/heading/index.js#L40-L92

So if a block doesn't have a `transforms` definition to convert to the desired block, then the option won't be available, as I understand.

**Comment by hedgefield** [comment]
Gotcha, so if someone feels compelled to add a transform they can append those files with the 'conversion formula' so to speak?

**Comment by westonruter** [comment]
Yes, that's right. I'm pretty sure a plugin could add their own transforms to, say, the Text block by amending the object returned by `wp.blocks.getBlockType('core/text').transforms`.
