### ISSUE TITLE
Modifying custom class after initial update doesn't enable update button 

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#17688]
**Describe the bug**
When a user modifies a custom class on a block after the update button has been clicked within the post, the update button remains disabled.

**To reproduce**
1. Create a new page.
2. Add a block to the page (e.g. `Heading`).
3. Add an additional CSS class in the edit panel for the heading.
4. Save the page.
5. Without leaving the editor and coming back, attempt to edit the class you just added.
6. The update button remains disabled.

**Expected behavior**
I would expect that the update button would allow me to save the change to the additional class field.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Safari
 - Version: 13.0.1

**Additional context**
- Gutenberg v6.5.0
- Wordpress v5.2.3

**Comment by fresatomica** [comment]
We've got a user report about this here: https://twitter.com/4rchi7/status/1179273379880280064

**Comment by jorgefilipecosta** [comment]
Hi @philbuchanan, @fresatomica, thank you for reporting this issue. In my tests, it seems it was fixed and the problem should not happen when WordPress 5.4 is released.
