### ISSUE TITLE
Incorrect CSS spacing in the form control elements in the sidebar 

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#17684]
The CSS for `SELECT` boxes and radio buttons in the editor have been changed. In the current beta version of 5.3, the spacing, alignment and paddings are all incorrect.

**Screenshots**

![5-3-beta-select-styling](https://user-images.githubusercontent.com/1571592/65985064-5fc26400-e481-11e9-93e9-ed013a8c915b.jpg)
![5-3-beta-radio-styling](https://user-images.githubusercontent.com/1571592/65985065-5fc26400-e481-11e9-8899-3d2e0e4d3fb8.jpg)

**Desktop (please complete the following information):**
Latest Chrome on OSX

**Additional context**
Gutenberg 6.5
Latest WordPress 5.3 beta

**Comment by swissspidy** [comment]
Does this still exist in current Gutenberg master?

**Comment by markhowellsmead** [comment]
@swissspidy Not with WP 5.2.3 and Gutenberg 6.6.0 (plugin), no.

**Comment by ellatrix** [comment]
Is this still an issue after the 5.3 release and Gutenberg 6.9?

**Comment by markhowellsmead** [comment]
@ellatrix No.

**Comment by talldan** [comment]
Re-closing as github still seemed to think this was an open issue when viewing the issues list.
