### ISSUE TITLE
Inconsistent naming of the isDismissable/isDismissible property

### ISSUE THREAD

**Issue by wpscholar** [WordPress/gutenberg#17687]
**Describe the bug**
The Modal component uses [isDismissable](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/modal/index.js#L111) as a property, whereas the Notice component uses [isDismissible](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/notice/index.js#L23). 

I believe that `isDismissible` is the more correct spelling? We should probably create an alias in the Modal block for the correct spelling so as to fix the inconsistency without breaking existing usages.

**Comment by agawish** [comment]
I can refactor that if it is not too much of a trouble!
