### ISSUE TITLE
Dropcap tag doesn't get cleaned up

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1768]
## Issue Overview
This is a minor thing, but something that triggered my clean markup spidey sense.

## Steps to Reproduce
1. Create a text block with some text
2. Look in the code view and see: `<!-- wp:core/text -->`
3. Turn the Dropcap toggle on
4. Look in the code view and see: `<!-- wp:core/text {"dropCap":true} -->`
5. Turn the Dropcap toggle off
6. Look in the code and see that it says `<!-- wp:core/text {"dropCap":false} -->`

version 0.3.0

## Expected Behavior
That the tag gets cleaned up after you turn dropcaps off. By default, when the tag is absent, it should assume that dropcaps are not wanted.

## Current Behavior
The tag remains in the block definition.

**Comment by swissspidy** [comment]
This is likely to come up again for other blocks with default attribute values. Is there a way we can fix this for all of them?

**Comment by westonruter** [comment]
Working on a patch…

**Comment by westonruter** [comment]
Please try fix in #1910.
