### ISSUE TITLE
Navigation customization: simplified approach

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17683]
This is a splitting out of the work done in #16830 and aimed at focusing on what a minimal approach could be here.

For reference the current idea is:

![image](https://user-images.githubusercontent.com/253067/65982256-d4da6d00-e472-11e9-8287-a3f13a6e8424.png)

@shaunandrews created the work that got us here and that is combined with the recent columns colour picking.

**Comment by shaunandrews** [comment]
![Navigation Block Simple Color Controls](https://user-images.githubusercontent.com/191598/65984141-18ba7b80-e44d-11e9-8cda-3980d26aee4a.gif)

**Comment by marekhrabe** [comment]
This is the first time I see a color picker inlined in the editor, usually those were in sidebars of other blocks. But technically they should work well in that place too, right? 

Just mentioning that we should implement the feature that alerts you about about good/bad contrast.

**Comment by karmatosed** [comment]
> This is the first time I see a color picker inlined in the editor, usually those were in sidebars of other blocks.

This position has been decided on for the columns block so yes is a change but it's one happening in a few places @marekhrabe
