### ISSUE TITLE
Internet Explorer 11: New checkboxes need to be improved

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#17680]
**Describe the bug**

See screenshot below:
- on the left: checkboxes on current WP trunk 
- on the right: checkboxes on WP 5.2.3

As far as I know, the new checkbox uses a SVG icon but it appears there's still some CSS pseudo generated content (not sure why it's visible only in IE). Notice there's a double checkmark shape.

Also, there's no blue background.

/Cc @kjellr @youknowriad 

![checkbox ie11 5 2 3](https://user-images.githubusercontent.com/1682452/65965512-077a6a80-e45f-11e9-8371-3e66c0a8f159.png)

**Comment by kjellr** [comment]
Spent a couple minutes digging into this. From what I can tell, IE doesn't support `background-color` on checkbox inputs. 😞 

There are a few possible ways around this: 

- Implement the background color using a new pseudoelement.
- Add a background color to the SVG.
- Ensure the checkmark appears as gray (or blue) in IE only. 

Either way, I think we'll want to add some CSS to hide the existing WP-Admin dashicon checkmark when this SVG is used.

**Comment by afercia** [comment]
Thanks @kjellr !
Maybe we can just accept there's no background in IE and try the option 3: Ensure the checkmark appears as gray (or blue) in IE only? 🙂Things don't need to look the same, especially in IE11.

However, please notice that there's a `:before` pseudo element generated _inside_ the `<svg>` tag. Is that expected? Clearly visible in the Chrome inspector.

I think it's the `dashicon-yes` class applied on the SVG that still renders the `\f147` glyph?
```
.dashicons-yes:before {
    content: "\f147";
}
```

**Comment by kjellr** [comment]
> I think it's the dashicon-yes class applied on the SVG that still renders the \f147 glyph?

That's what I thought initially too, but I actually think we may actually just be seeing the default IE checkmark still. In any case, I was able to hide it using [a weird IE pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/%3A%3A-ms-check) in #17714. Please give that a test when you get a chance.
