### ISSUE TITLE
Post visibility unification

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17686]
Currently, the post visibility has 2 styling options for the same content. A baseline would be unify radios, default states and copy formatting.

![image](https://user-images.githubusercontent.com/253067/65986680-4539bc00-e47c-11e9-9c17-29051ecc26fe.png)

![image](https://user-images.githubusercontent.com/253067/65986692-4d91f700-e47c-11e9-943a-c841c2574404.png)

**Comment by enriquesanchez** [comment]
The alignment and spacing issues on that second screenshot have been fixed on #17613. This is how they both look on `master` right now:

<img width="665" alt="Screen Shot 2019-10-01 at 5 22 54 PM" src="https://user-images.githubusercontent.com/3276087/66005169-4bc23680-e470-11e9-9244-a252a87a608f.png">

I notice a slight variation of color on the text, but upon quickly inspecting the CSS they both seem to have the same color assigned (`color: #82878c;`). This is odd 🤔.

**Comment by richtabor** [comment]
It looks like the `.editor-post-publish-panel` style of `color: #555d66;` is being applied to the whole panel, styling post visibility properly - whereas `.edit-post-post-visibility__dialog-info` seems to be inheriting the body color of `#444`.

I've changed it to `#d52411` to show it:
<img width="654" alt="Screen Shot 2019-10-02 at 5 36 38 PM" src="https://user-images.githubusercontent.com/1813435/66083858-41b93a00-e53b-11e9-92bc-4193b9326243.png">

**Comment by enriquesanchez** [comment]
Oh interesting. Is there any reason why we wouldn't want to use the body color (`#444`) in this case?

**Comment by enriquesanchez** [comment]
@karmatosed @richtabor I created a PR (#17731) to fix the text color variation. Please let me know if you have any feedback

**Comment by karmatosed** [comment]
> Oh interesting. Is there any reason why we wouldn't want to use the body color (#444) in this case?

Not sure there is and consistency would be great to start from.
