### ISSUE TITLE
Latest Posts Block: Option to show/hide the post author

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/gutenberg#17681]
We already offer a way to show/hide post dates using the block. Perhaps we could do the same for post author(s).

Given that we're working with post meta, I believe having also the post author could be a great addition. Quick mockup:

<img width="278" alt="Captura de Tela 2019-10-01 às 11 47 28" src="https://user-images.githubusercontent.com/1136160/65973480-c889ec00-e441-11e9-9b43-18aff744d7cb.png">

In the future, we could also add other fiels like:

* Show/hide post tags
* Show/hide post categories

**Comment by swissspidy** [comment]
This is already in progress here: #17163.

**Comment by skorasaurus** [comment]
This has been implemented and can be closed :)
