### ISSUE TITLE
core/editor store having issues updating meta if register_meta single option is false (if its multiple)

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#17692]
**Describe the bug**
Previous Gutenberg versions could update multiple-value meta without problem. Since one of the latest versions there is an issue were meta is not saved correctly. Let me expalin with an example:

**To reproduce**
Register a multi-value meta:
````
add_action( 'init', __NAMESPACE__ . '\register_meta' );
function register_meta() {
	register_post_meta(
		'post',
		'my_meta_multiple',
		array(
			'show_in_rest' => true,
			'single' => false,
			'type' => 'string',
		)
	);
}
````
Inside a post using the console update the meta value:

````
wp.data.dispatch("core/editor").editPost({ meta: { my_meta_multiple: ['aaa','bbb','ccc'] } })
````
This will save correctly, the Update button of the Post will be enabled and if saved the value updates.

Now, if we try to update the value it acts in the following ways:

- `['aaa']` -> `['aaa','bbb','ccc']` removing the last/s already-saved elements will not receive any update. Changing the content and saving the post, will keep showing the previous value.
- `['bbb','ccc']` -> `['bbb','ccc','ccc']`
- `['xxx','yyy','zzz']` -> `['xxx','yyy','zzz']` I believe the issue is with removing elements

**Version**
- Gutenberg 6.6.0 RC1
- WordPress 5.2.3

**Comment by garciaalvaro** [comment]
This is a gif showing the issue. The Meta Issue plugin contains the above PHP code. In case it's not clear, the steps are:

- nothing ->`['aaa','bbb','ccc']`. Correct
- `['aaa','bbb','ccc']` -> `['aaa','bbb']`. Editor doesn't notice the change so can't press Update button
- `['aaa','bbb','ccc']` -> `['bbb']`. Change is noticed, but what gets saved is `['bbb','ccc','bbb']`

![meta-issue](https://user-images.githubusercontent.com/4710040/66048963-d23b4e80-e52a-11e9-9d25-0b984145131d.gif)

**Comment by garciaalvaro** [comment]
@youknowriad Is there any chance to take a look at this? It is currently breaking one of my plugins.

I created [this repo with a plugin](https://github.com/garciaalvaro/multi-meta-bug) to test it. To reproduce:

1. Install the plugin (activate also the Gutenberg plugin)
2. Go to a post editor, give it a title and publish.
3. Open the console and execute `wp.data.dispatch("core/editor").editPost({ meta: { my_meta_multiple: ['aaa','bbb','ccc'] } })`
4. Update the post
5. Open the REST API for the post to see the saved values (`...wp-json/wp/v2/posts` see the latest post meta property)
6. Back in the editor in the console execute `wp.data.dispatch("core/editor").editPost({ meta: { my_meta_multiple: ['bbb','ccc'] } })`
7. Go back to the REST response, refresh and see how instead of `['bbb','ccc']` what was saved is `['bbb','ccc','ccc']`

This same process works correctly without the Gutenberg plugin active (with the version WP 5.2.3 has).

**Comment by youknowriad** [comment]
We fixed a bug in Gutenberg 6.6 about meta attributes. cc @epiqueras 
I'm not certain it's the same as this one though.

**Comment by epiqueras** [comment]
It was different, here is the fix: #17850.

**Comment by garciaalvaro** [comment]
Thanks for taking a look. @epiqueras if the problem is in Core Data I guess [this other issue](https://github.com/WordPress/gutenberg/issues/17756) could also be solved with the fix?

**Comment by epiqueras** [comment]
That one is unrelated: https://github.com/WordPress/gutenberg/issues/17756#issuecomment-539642268.
