### ISSUE TITLE
Image block + columns block makes it difficult to add new block in between

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17698]
**Describe the bug**
Not possible to add a new block between image block and a columns block when nested/inner blocks are present.

**To reproduce**
1. Add an image block with an image.
2. Add a column with 3 cells.
3. Add something inside of each cell.
4. See if your able to add a block between the image and the columns block.

The below screenshot shows the inserter in the beginning of the columns block.
![Screen Shot 2019-10-02 at 07 54 13](https://user-images.githubusercontent.com/5323259/66021212-296cff00-e4ea-11e9-8cf1-c3fc1fb2c834.png)

![Missing-inserter-between-image-column-blocks](https://user-images.githubusercontent.com/5323259/66021409-f8d99500-e4ea-11e9-9406-f199b513ba92.gif)

**Expected behavior**
To be able to add a block between the image and column blocks.

**Desktop (please complete the following information):**
Mac OSX10. something
Chrome
Desktop server

**Additional context**
Gutenberg version: 6.5

**Comment by youknowriad** [comment]
Seems like this was fixed.

**Comment by paaljoachim** [comment]
Yeah it seems to work better now. I have to hover the cursor between the image block and the columns block and wiggle it a bit and then the inserter shows up.
