### ISSUE TITLE
Publish button is off-center

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#17691]
**Describe the bug**
When publishing a new post, the 'Publish' button on the confirmation/settings screen is not properly centered in its containing space.

**To reproduce**
1. Create a new post
2. Click on 'Publish'
3. See error

**Expected behavior**
The 'Publish' button should be horizontally centered.

**Screenshots**
<img width="296" alt="Screen Shot 2019-10-01 at 5 21 39 PM" src="https://user-images.githubusercontent.com/3276087/66005500-50d3b580-e471-11e9-9e58-a15df5ddb39d.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave v10.14.15
 - Browser Firefox 69.0.1

**Comment by richtabor** [comment]
Yea that should be tweaked a bit. 👍
