### ISSUE TITLE
Better scope the "Vanilla Block Styles" CSS selectors

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#17702]
**Describe the bug**

We currently faced a CSS conflict issue with our plugin meta box and after some digging it appears Gutenberg uses some very general CSS selectors in the `block-library` stylesheet. See:

https://github.com/WordPress/gutenberg/blob/a1eda99eaf97b957120c4b3400dd3d968f7bbf04/packages/block-library/src/style.scss#L174-L196

While I do understand the need to target some elements across all blocks (which by the way goes a bit against the principle of isolated, reusable, components), it appears some of thes CSS selectors aren't scoped at all and they target all the related elements. Even the ones in the UI added by plugins, whether it's a meta box or a sidebar or anything else.

They even target any related element in the WordPress admin UI, which may potentially produce breakages. I'd tend to think this shouldn't happen and these selectors should be better scoped.

Specifically:
- the `img` type selector targets any image in the edit post page: I'd say this is the most important case
- minor: same happens with the `figcaption` and `iframe` selectors: `figcaption` and `iframe` are likely less used by plugins but there's a potential of breakage anyways.

To my understanding, the main goal of these "Vanilla Block Styles" is to provide some baseline styles for all the blocks. If so, seems to me they should at least be better scoped with an additional selector that targets the blocks area and excludes all the rest of the page.

**Comment by paaljoachim** [comment]
I am wondering if this issue is still valid.

@WordPress/gutenberg-core

**Comment by tellthemachines** [comment]
The vanilla styles have been removed, so we can close this issue now.
