### ISSUE TITLE
Gutenberg Demo Video

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#1770]
With Gutenberg on the horizon, and a [desired marketing page in the works](https://github.com/WordPress/gutenberg/issues/1559), there was a request for a Gutenberg demo video. I took a crack at it, and am presenting something to gather thoughts and feedback. 

THE VIDEO
https://cldup.com/mgxwzWPqNR.mp4

**Constraints**

- Keep it under 3 minutes.
- I'm not a video expert, and was hoping to simply use iMovie to complete.

**Needs**

- Include demos of the new blocks (ie. Button Block, Recent Posts Block, etc.)

**Concerns**

- Should we demo Gutenberg on mobile as well and include it in this video?
- Should we add audio? Music?
- Video optimization... can someone help?

Any other feedback?

**Comment by buzztone** [comment]
Great work - gives solid quick introduction.

> Should we demo Gutenberg on mobile as well and include it in this video?

No - it's not ready & minor use case at this stage in development

> Should we add audio? 

Yes - including voice-over would convey info more easily

> Music?

Yes - Would go well with voice-over

Could also be a lot shorter if focus only on top 3 items. I'd seen all I needed to decide to download & test it after 1 min.

**Comment by karmatosed** [comment]
Great first pass @mapk. A few general thoughts:

- I think it could be shorter.
- I would suggest easing off on a lot of the animation/motion. From an accessible view a lot find that hard and particularly on titles and at the end they get a bit intense.
- I think it needs some voice over/music

**Comment by mapk** [comment]
I took in the feedback, thanks @buzztone and @karmatosed. I agree about the mobile aspect the both of you brought up. I haven't added any voice-over. If we choose to go that way, let's get someone who feels comfortable recording their voice and get a script together.

**Edits include:**

- Added music
- Removed some of the animation of the transition title slides
- Shortened the video to 1:46

**VIDEO**
https://cldup.com/R5OcshBxaA.mp4

**Comment by buzztone** [comment]
Shortened version with music is very good. I now feel voice over may not be necessary. My only suggestion is to remove the Multiple Selection section (probably not significant issue for many users).

**Comment by karmatosed** [comment]
Closing as v1 is done.
