### ISSUE TITLE
First launch on mobile is unwelcoming

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#17708]
**Describe the bug**

I was going to test gutenberg on a new install (via `npm run env install`) with the iOS simulator, and noticed this is what you see the first time you open gutenberg:

![gutenberg-ios-nux](https://user-images.githubusercontent.com/8739/66040920-e8d8aa00-e518-11e9-8d9f-0f6ec52bb71e.gif)

First, instead of showing the editor, the settings sidebar is initially visible, completely covering the editor.

Second, the tooltips appear over the sidebar, pointing to things that aren't there. If you choose to see the next tip, the tooltip is partially rendered off-screen and can't be closed unless you turn your phone to landscape.
_Edit: This one is already reported in #16225._

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Simulator
 - OS: iOS 13.1
 - Browser Safari
 - Version 13?

**Additional context**

Tested using one of my branches based on latest master: 0682fb459

**Comment by gziolo** [comment]
Another issue:

![Screen Shot 2019-10-10 at 17 17 31](https://user-images.githubusercontent.com/699132/66582333-e2ce7300-eb81-11e9-83d7-83acf9783501.png)

**Comment by gziolo** [comment]
@mapk - are you aware of whether some of those visual issues are tracked somewhere else? I can't check myself until tomorrow.

**Comment by gziolo** [comment]
> Second, the tooltips appear over the sidebar, pointing to things that aren't there. If you choose to see the next tip, the tooltip is partially rendered off-screen and can't be closed unless you turn your phone to landscape.

This one is tracked in #16225.
