### ISSUE TITLE
Multiple style targets for the same element in default block styles

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17700]
Hey, in some cases the default block css includes different style targets for the same element.

Example for gallery block (4 different style targets):

`.blocks-gallery-grid.columns-1 .blocks-gallery-image` and 
`.blocks-gallery-grid.columns-1 .blocks-gallery-item` and 
`.wp-block-gallery.columns-1 .blocks-gallery-image` and
`.wp-block-gallery.columns-1 .blocks-gallery-item` for the same container.

Example for cover block (2 different style targets):

`.wp-block-cover` and `.wp-block-cover-image` for the same container.

There are more other multiple style targets in other block types.

I'm wondering, which style target will be the final and which one will removed in the future? How can I know which style target I need to override default styles for theme adjustments, without adding multiple style targets from the default block styles?

**Comment by paaljoachim** [comment]
Hey @CreativeDive Martin

Thank you for creating this issue!
I see that it has been overlooked.
Is this issue still valid?

I will ping Isabel.
@tellthemachines

**Comment by tellthemachines** [comment]
`.blocks-gallery-image` and `.wp-block-cover-image` are deprecated and only included in the CSS for backward compatibility purposes. `.blocks-gallery-item` and `.wp-block-cover` should be used instead.

The best way to check which classes are currently in use for styling is to inspect the markup generated in the front end. When changes to markup happen (not super often, but sometimes we need to adjust something) there will be dev notes describing the changes, published [here](https://make.wordpress.org/core/). Hope this helps! I'll go ahead and close the issue now.
