### ISSUE TITLE
Cover Block: Custom Text Color not working

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17706]
Hey,

the cover block comes with the following default CSS styles:

`.wp-block-cover-image .wp-block-subhead, .wp-block-cover-image h1, .wp-block-cover-image h2, .wp-block-cover-image h3, .wp-block-cover-image h4, .wp-block-cover-image h5, .wp-block-cover-image h6, .wp-block-cover-image p, .wp-block-cover .wp-block-subhead, .wp-block-cover h1, .wp-block-cover h2, .wp-block-cover h3, .wp-block-cover h4, .wp-block-cover h5, .wp-block-cover h6, .wp-block-cover p {
    color: inherit;
}`

and 

`.wp-block-cover-image .wp-block-cover-image-text, .wp-block-cover-image .wp-block-cover-text, .wp-block-cover-image h2, .wp-block-cover .wp-block-cover-image-text, .wp-block-cover .wp-block-cover-text, .wp-block-cover h2 {
    color: #fff;
    font-size: 2em;
    line-height: 1.25;
    z-index: 1;
    margin-bottom: 0;
    max-width: 610px;
    padding: 14px;
    text-align: center;
}`

The style `color: inherit` from example 1 and the style `color: #fff;` from example 2 (specific for h2 only) override custom text colors in case of:

`<h2 class="has-royal-color has-text-align-left">Cover Block with nested Heading – H2</h2>`

or

`<h3 class="has-royal-color has-text-align-left">Cover Block with nested Heading – H3</h3>`

or

`<p class="has-text-color has-royal-color">Paragraph</p>`

and 

`.has-royal-color {
    color: #9498e6;
}`

So we can't add custom text colors for paragraph or headings nested in the cover block, because the default cover block style override the custom color style.

**Comment by youknowriad** [comment]
Just tested this with the TwentyNineteen theme and the last Gutenberg plugin and it works as intended.
Which version are you testing? would you be able to try installing the last plugin version?
Which theme are you using?

**Comment by CreativeDive** [comment]
@youknowriad I'm using Gutenberg 6.5 and WP 5.2.3

**CASE 1:**

![heading-h2-color](https://user-images.githubusercontent.com/31563167/66040350-8206c100-e517-11e9-9e61-33e60860a617.gif)

1. Create a Cover block
2. Add heading H2
3. Change the color (not to white, a other color like red)
4. Save
5. Go to frontend
6. You will see the color is still white.

The reason of this issue is `color: #fff` from the following default style:

`.wp-block-cover-image .wp-block-cover-image-text, .wp-block-cover-image .wp-block-cover-text, .wp-block-cover-image h2, .wp-block-cover .wp-block-cover-image-text, .wp-block-cover .wp-block-cover-text, .wp-block-cover h2 { color: #fff; font-size: 2em; line-height: 1.25; z-index: 1; margin-bottom: 0; max-width: 610px; padding: 14px; text-align: center; }`

**Comment by CreativeDive** [comment]
@youknowriad 

**CASE 2:**

1. Create a Cover block
2. Add heading like H3 and paragraph
3. Change the color of heading + paragraph (not to white, an other color like red)
4. Save
5. Go to frontend
6. You will see the color is still white (ONLY IN CASE, A TEXT COLOR IS ADDED LIKE THE FOLLOWING:)

My custom color style:

`.has-royal-color { color: #9498e6; }`

The default cover block style:

`.wp-block-cover-image .wp-block-subhead, .wp-block-cover-image h1, .wp-block-cover-image h2, .wp-block-cover-image h3, .wp-block-cover-image h4, .wp-block-cover-image h5, .wp-block-cover-image h6, .wp-block-cover-image p, .wp-block-cover .wp-block-subhead, .wp-block-cover h1, .wp-block-cover h2, .wp-block-cover h3, .wp-block-cover h4, .wp-block-cover h5, .wp-block-cover h6, .wp-block-cover p { color: inherit; }`

... overrides my custom color style:

`.has-royal-color { color: #9498e6; }`

The color is still white, but it should be "#9498e6".

In the case of "Twenty Nineteen", this is only working, because the theme developers has explicit added a override style like:

```
.entry .entry-content .has-primary-color {
    color: #0073aa;
}
```

If the custom color is not explicit overrides like the upper example from "Twenty Nineteen", then the custom color is not working.

Now the **QUESTION**, how we should add custom color als theme developer? Like this:

```
.entry .entry-content .has-primary-color {
    color: #0073aa;
}
```

or like this (NOT WORKING):

```
.has-primary-color {
    color: #0073aa;
}
```

**Comment by CreativeDive** [comment]
@youknowriad 

[https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes](url)

Here we can see, custom colors should be added like this:

```
.has-strong-magenta-background-color {
    background-color: #313131;
}
 
.has-strong-magenta-color {
    color: #f78da7;
}
```

BUT, only `.has-strong-magenta-color` don't overrides `.wp-block-cover-image .wp-block-subhead, .wp-block-cover-image h1, .wp-block-cover-image h2, .wp-block-cover-image h3, .wp-block-cover-image h4, .wp-block-cover-image h5, .wp-block-cover-image h6, .wp-block-cover-image p, .wp-block-cover .wp-block-subhead, .wp-block-cover h1, .wp-block-cover h2, .wp-block-cover h3, .wp-block-cover h4, .wp-block-cover h5, .wp-block-cover h6, .wp-block-cover p { color: inherit; }`.

In the example of "Twenty Nineteen". This is ONLY working, because the custom color is explicit overwritten like:

```
.entry .entry-content .has-primary-color {
    color: #0073aa;
}
```

Do you know what I mean?

**Comment by CreativeDive** [comment]
@youknowriad The main issue comes from this default style:

```
.wp-block-cover-image .wp-block-cover__inner-container, .wp-block-cover .wp-block-cover__inner-container {
    width: calc(100% - 70px);
    z-index: 1;
    color: #f8f9f9;
}
```

Each child text color of the cover block has automatically `color: #f8f9f9;` without changing it manually. However, the cover block may have a light background color or an image background with a light overlay. It is not logical that the Cover block has an auto color of `color: # f8f9f9;`. This is only appropriate if the background of the color block is dark.

It is confusing for the user, because the text color changes without changing the text color manually.

**Comment by youknowriad** [comment]
Ok, I tried several things I only reproduce right now with the Heading block inside a Cover block and by picking one of the color palette colors, not a custom color.

Thanks for the details.

**Comment by CreativeDive** [comment]
@youknowriad Please also note this related issue.

#17704 

This problem can be solved easily and quickly.
