### ISSUE TITLE
Media & Text order when stacking seems wrong

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#17716]
I don't know if this is wrong in all cases, but a common page layout that comes to mind when using media-text is an alternating left and right when showcasing a series of features, blog posts,... One example I could find is https://apps.wordpress.com/mobile/, but I'm sure there are many others:

![Example](https://user-images.githubusercontent.com/8739/66052735-5ee90b00-e531-11e9-9f23-5b0c08d70ea9.png)

When a layout like that gets displayed in a smaller screen, what usually happens is that it turns into a vertical stack of image, then text:

![Apps](https://user-images.githubusercontent.com/8739/66052893-a53e6a00-e531-11e9-87ca-e5ac7ccb32b9.png)

However, if you try to reproduced the same layout in Gutenberg, media-text assumes that right-to-left implies bottom-to-top and orders things producing some funny looking results:

![Gutenberg](https://user-images.githubusercontent.com/8739/66052967-c3a46580-e531-11e9-9251-18877ddb3e3f.png)

I think this is also somewhat related to #16698 where @melchoyce was proposing a top-down layout option for media-text also on larger screens, but I didn't want to hijack that conversation.

Also related to the efforts in #16790. I feel like defaulting to media on top when stacking is a better option that make it dependent on direction when not stacking, but I'm sure there will be use cases for the contrary, and I think we might need better ways to express how to stack things responsively.

cc @iamthomasbishop

**Comment by melchoyce** [comment]
Hey @koke, I totally agree. There's an existing issue for this: #14283. I'm going to close this, and we can continue the conversation there — would love if you could post this as a comment since it's a great example.

**Comment by koke** [comment]
Thanks, I looked at the Media & Text label and somehow missed that one 🤦‍♂
