### ISSUE TITLE
The Inserter Help Panel look a bit broken if the block doesn't have any attached example

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17720]
We should try to hide it or fallback to the default help panel content for these cases.

<img width="302" alt="Capture d’écran 2019-10-02 à 5 13 14 PM" src="https://user-images.githubusercontent.com/272444/66061807-1123d100-e538-11e9-820a-b7596827ca6a.png">

**Comment by richtabor** [comment]
I lean towards showing the default help panel. 🤷‍♂
