### ISSUE TITLE
Performance on lower powered machines/not current gen machines

### ISSUE THREAD

**Issue by willstocks** [WordPress/gutenberg#17730]
**Describe the bug**
So, I happen to have a relatively low powered machine. It's a "cheap" windows tablet that I use when travelling to avoid lugging around an expensive/heavier device. Overall, the specs aren't _that_ bad considering.
 - Intel Atom x5-Z8350 (Quad Core) 
- 4GB LPDDR3 RAM

On to the issue - when writing Gutenberg based posts, the typing experience is borderline unusable. Almost all other sites I don't really see any issues at all - especially when it comes to typing. I've only ever seen it happen on one other site... fortunately I never had to visit/use that one again :grin: 

**To reproduce**
... the only thing I can suggest is go out and get a lower powered machine that's not current gen. This one set me back roughly £150/$150 so not too bad. I'm not sure what range of specifications Gutenberg is tested for by default? 

I have no issue whatsoever on "standard" machines (current gen/modern spec Windows machines or MacBook Air's/Pro's)

**Expected behavior**
I should at least be able to write up a blog post relatively uninterupted/cleanly. I'd happily give up some of the fancier nice-to-haves if I could actually write up my content!

**Screenshots**
How's a video? See https://drive.google.com/file/d/1NFdQfrLjp9mdQglZvmQl-ixcloZN8xAE/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 / Ubuntu 19.04
 - Browser: Chrome 76 & 77 / Brave 68

**Additional context**
Gutenberg v6.4.0 + 6.5.0
WP v5.2.3

**Comment by willstocks** [comment]
Just a note - this continues to be a pain on lower powered devices. Tablets/machines that are a couple of years old.

**Comment by mtias** [comment]
There's been a lot of performance improvements over the past year, hopefully it has made some of these scenarios better.
