### ISSUE TITLE
Improving the List block with basic HTML list types 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17738]
Hey

My customer wants it to look like this:
![Screen Shot 2019-10-02 at 08 16 47](https://user-images.githubusercontent.com/5323259/66022055-0263fc80-e4ed-11e9-8bbb-8373fe2a97fa.png)

This seems like a challenge for the list block.
There are multiple things to consider. Checkmarks, numbers, letters, roman numbers etc. Then also having the list horizontal instead of vertical.

I would suggest to have drop down of the prefix icons. Similar to what we do with alignment options in other blocks.

That could mean a drop down with name such as ordered list and the icon. Followed by names and icons of other options.

One would then check the drop down and select the type of icon one wants to use.

Mockup:
![Improving-list-block](https://user-images.githubusercontent.com/5323259/66022963-e0b84480-e4ef-11e9-8eb9-ec8728d00511.jpg)

**Additionally**

Then also add an alignment option drop down similar to other blocks. To show the list in 
Horizontal or vertical mode.

**Comment by Wingo5315** [comment]
For the checks in the list, there could be an option where the user could upload an SVG/PNG image which could be used as a bullet. 

Also, whilst we're on the subject of improving the List block,I think there should be a number of ways that the numbers can be displayed (roman numerals, indented lists with 1, 1.1, 1.1.1 etc.) that the user can choose from.

**Comment by joyously** [comment]
I wonder how much of this should be in the core block and how much should just be styles added by a plugin.

Does the current list block expose the `start` attribute? How about the `reversed` attribute?

**Comment by Wingo5315** [comment]
The horizontal - vertical option should be added by a plugin or custom CSS, as it's something most users won't want or need.

However, I do think that with the numbers, such as the roman numerals, maybe we should have the numbering options that are provided in Microsoft Word:
![image](https://user-images.githubusercontent.com/25369857/66224026-760c3200-e6c4-11e9-849d-369243cf07b0.png)
And, in terms of the bullet styles, there should be these options:
- filled-in circle (default)
- circle outline 
- filled-in square
- use an image as a bullet (PNG)

**Comment by skorasaurus** [comment]
Regarding bullet styles, there's a couple issues that also mention it #9117 and #15005.

**Comment by phpbits** [comment]
@paaljoachim Just wanted to let you know that I've just added few list block styles on [EditorsKit Plugin](https://wordpress.org/plugins/block-options/). Here's the preview and I hope you'll love it. Cheers!

https://twitter.com/editorskit/status/1213105775632977921

![gutenberg-list-block-styles](https://user-images.githubusercontent.com/3365507/71730035-1a487500-2e7c-11ea-9b4c-a2edd69f9d9c.gif)

**Comment by joyously** [comment]
How does that connected one look with nested lists? Or with text that wraps to a second line?

**Comment by joyously** [comment]
> as I understand, the current block exposes both the start and the reversed attribute.

I just tested this, and the attributes are only available on the outermost list.

**Comment by phpbits** [comment]
> I just tested this, and the attributes are only available on the outermost list.

The style will also be applied on the nested list :)

**Comment by paaljoachim** [comment]
Design folks really need to go through this issue. Thanks a lot for sharing Jeffrey! I look forward to seeing your List Block improvements make it's way into GB Core.
@karmatosed @mapk

**Comment by karmatosed** [comment]
Let's get the design feedback label on this so we can dive into some thinking here. I do first off think we need to be cautious about what we add here as a lot can be done with a combination of styles and also a class.

I'd be cautious as a result of my above comment to add a way to upload an image. I think there's a lot can be done with maybe another block style variation (maybe a couple), but I don't think making this too complex is the way to go. I also think this should be done under style variations over in toolbar.

**Comment by mapk** [comment]
> I would suggest to have drop down of the prefix icons.

I actually like the block styles option that @phpbits proposed as a way to do this. We don't need to provide every possible bullet symbol, but a good few that are common to use.

> Then also add an alignment option drop down similar to other blocks.

This reminds me of the Navigation block and might be worth an exploration there if it hasn't happened yet. 

In either case, providing more bullet options sounds good to me. Using them as block styles opens them up for plugins to easily expand and add their own styles too.

**Comment by strarsis** [comment]
Please make nested lists stylable! This is easily possible with HTML and I can indeed achieve the same in editor by manually adding the `is-style-*` classes to nested `<ul>` and `</ol>` elements, but it appears that the editor removes them when changing the uppermost list block (e.g. changing its block style).
Also it is currently not possible to return back to list item when a nested list has been added to it:

1. Top 1
2. Top 2
  1. Level 2
    1. Level 3
    2. Level 3
    **Back to same item!**
3. Top 3
4. Top 4

**Comment by paaljoachim** [comment]
One focus area is to add styles to the List Block such as Jeffrey mentioned in his comment above. https://github.com/WordPress/gutenberg/issues/17738#issuecomment-570594829
I also made an  animated gif.

![List-Block-Styles](https://user-images.githubusercontent.com/5323259/78245448-cafbfa00-74e7-11ea-8314-bd0547706500.gif)

I would suggest that we add these styles into the Core List Block:
Default
None
Arrow
Checked
Dashed
Starred

**Comment by mapk** [comment]
It seems there's some consensus around adding a variety of bullets to the List block. Using the style variations for this purpose feels like the right way to go. Shall we move this to dev?

**Comment by paaljoachim** [comment]
Hey Jeffrey. @phpbits 
Can you add some styles to the block?

**Comment by zdenys** [comment]
>Additionally
Then also add an alignment option

This would be really nice indeed, as compared to the paragraph block, list one is missing the alignment option but also justify option. Having both for parity would be good. 
| Paragraph | List|
----|----
|![](https://d.pr/i/kHP1El+)|![](https://d.pr/i/be8O8L+)|

**Comment by joyously** [comment]
@zdenys What else do you have installed?
There is no Justify option. It was removed from WP years ago, and not added back in the new editor. This screenshot is from WP 5.5RC2:
![para-menu](https://user-images.githubusercontent.com/7957680/89455283-b050c080-d727-11ea-8dbc-5d688cde9948.jpg)

**Comment by strarsis** [comment]
Note: The [EditorsKit](https://wordpress.org/plugins/block-options/) plugin adds a justify option.

**Comment by zdenys** [comment]
> @zdenys What else do you have installed?
> There is no Justify option. It was removed from WP years ago, and not added back in the new editor. This screenshot is from WP 5.5RC2:
The screenshots I provided are from a site with only Gutenberg plugin version 8.7.0. and Jetpack version 8.8. In fact, it may be coming from the later as when I deactivated it, I could see the justify option disappear.

**Comment by strarsis** [comment]
@zdenys: Yes, the Jetpack plugins [adds a justify format option to Gutenberg](https://github.com/Automattic/jetpack/blob/3f81e32a0a7350c859346b20ba15485b54cc7aeb/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L313).

**Comment by mtias** [comment]
I think this is more plugin territory. Unless we were to support any symbol / emoji, which might be worth exploring, specific style variations can quickly become dated while still needing to be supported for a long time.

**Comment by CHEWX** [comment]
Really missing roman numbers, impossible to do Privacy Policies and legal documents.

**Comment by strarsis** [comment]
@CHEWX: Exactly this!

**Comment by Wingo5315** [comment]
@CHEWX I think we should get this in for WP 5.6.

**Comment by createscape** [comment]
I am just working on a legal document in Gutenberg and found that I couldn't style the nested lists with different numbering system ( lowercase or roman numerals inside numbered list).  Editing the HTML didn't work either and I found this frustrating (assuming it's because Gutenberg isn't actually using HTML ).   I had to add a CSS class to remove the list items of the nested lists and just type in the lowercase and roman numerals.

**Comment by annezazu** [comment]
The ability to have more options rather than bullets or `1,2,3` came up in the [FSE Outreach Program's fourteenth call for testing](https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/#comment-2467). Specifically, there was a desire to offer `a, b, c` options. 

I think it would be interesting to explore as possible style variations for the block!

**Comment by solaceten** [comment]
Hello, I am wondering if this will get implemented and when?  It would also be nice to have the ability to add list style e.g. A) B) C) etc

**Comment by kohheepeace** [comment]
I think emoji is better than preset default style.

![2022-10-20 01 27 19](https://user-images.githubusercontent.com/29557494/196750386-1e9fc664-0458-48d7-a5bd-f761f8b5fb7f.gif)

[Idea]:
- Add `emoji` attribute to `core/list`
- Add `InspectorControls` with [emoji-mart](https://github.com/missive/emoji-mart) to allow user select emoji
- Inline css to `ul` when user select emoji
```html
<ul style="list-style-type: "📌";">
...
</ul>
```

[caveat]:
- It does not support nested list
- It does not support Serial number style

**Comment by druxstr** [comment]
I feel this issue tries to address 2 different problems and should be split to better solve them.

1. Adding _cosmetic_ list types (checks, stars, pins, emojis, etc.)
2. Adding [basic HTML list types](https://html.spec.whatwg.org/multipage/grouping-content.html#attr-ol-type) (letters, Roman numerals)

Cosmetic list types are about `<ul>`. They _may_ be better dealt by a plugin.

Basic HTML list types are about `<ol>`. They should be dealt by core.

What's at stake isn't the same. 

With no support for basic HTML types, [nested ordered list are barely usable](https://github.com/WordPress/gutenberg/issues/45567) in Gutenberg. With no support for stars and emojis, unordered lists still work.

**Comment by mtias** [comment]
@druxstr that's a good point, would be good to split.

**Comment by annezazu** [comment]
Changed the title of this issue and created a new one for cosmetic list types to better split things out: https://github.com/WordPress/gutenberg/issues/45830

**Comment by tomjn** [comment]
Noting that while I agree with this ticket for unordered lists, css and block styles are the way to go.

**_But for ordered lists_**, the `type=""` attribute is needed.

**Comment by paaljoachim** [comment]
Yess! 
@glendaviesnz has created a PR here: https://github.com/WordPress/gutenberg/pull/51186 go and check it out and give feedback!

**Comment by jasmussen** [comment]
I shared some design thoughts in https://github.com/WordPress/gutenberg/pull/51186#issuecomment-1573234749 that might be relevant to this issue.
