### ISSUE TITLE
Add Autosave functionality

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1773]

**Comment by DevinWalker** [comment]
Also mentioned here: https://github.com/WordPress/gutenberg/issues/1295

**Comment by aduth** [comment]
Some context on effects to privately publishing posts discussed at https://github.com/WordPress/gutenberg/pull/1361#issuecomment-314847331

**Comment by aduth** [comment]
Adding Needs API Endpoint label because [`wp_create_post_autosave`](https://developer.wordpress.org/reference/functions/wp_create_post_autosave/) is not exposed through any REST API endpoints, which is necessary for creating autosaves of published posts.

**Comment by mtias** [comment]
Moving to future milestones as first pass is done.

**Comment by mtias** [comment]
Going to close this, further improvements should be on specific issues.
