### ISSUE TITLE
Separate the e2e tests into groups.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17745]
Right now, the e2e tests are all shared in the same folder structure and can't be split logically.  Ideally, a third-party plugin or WordPress Core should be able to run Gutenberg e2e tests with their own setup to ensure nothing is broken.

My original idea for the ` e2e-tests` package was to only include there the tests that we consider stable and that are generic enough (don't require the plugin) and move the remaining tests outside the package, to the local `test/e2e` folder maybe until the feature is stabilized.

An alternative approach could be to create "groups" and having support for e2e tests groups ni our CLI ` wp-scripts test-e2e`. We could have three groups to start with:

 - Editor: All stable editor features that can be run from Core without the plugin as well.
 - Experimental: Tests for experimental features waiting to be marked as stable.
 - Local: Tests that are only useful in the plugin (like the demo page), to be honest, these should probably not be in the package at all.

cc @gziolo

**Comment by gziolo** [comment]
Fixed with #17990.
