### ISSUE TITLE
Try a different pattern for the font size picker

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#17755]
I'd like to propose we try a different direction that will help address the accessibility issues we've been encountering with previous attempts of the font size picker (#15319, #16148, #17418).
 
<img width="665" alt="Screen Shot 2019-10-03 at 11 21 22 AM" src="https://user-images.githubusercontent.com/3276087/66145442-79be8c80-e5d0-11e9-8862-0ea299b1b008.png">

While this solution takes a different direction, it covers all the requirements we need:

- It's accessible 
- Visually shows the size of the options
- Let's the user see which options is currently active

In addition, this solutions also informs the user of all the available options at a glance, without the need to interact with a custom select component or menu button in order to find out what's inside.

**Comment by mapk** [comment]
This is a good direction to try. Let's see if we can get this built rather quickly for WP 5.3. It will require some testing to ensure it's a good solution.

**Comment by karmatosed** [comment]
I commented over on the PR, just to close that loop I will also comment here. 

Whilst, I understand the reason for exploring this, I do feel this is a problematic direction. It adds a pattern we haven't used yet but is similar to the styles. I also think if you consider adding styles and font sizes, that rapidly becomes a very complex interface to do something simple, change font size.

I also have concerns over the cognitive load of that section right now with this added. If I am isolated in this feeling that's fine, but personally, it feels like a direction that needs deeper consideration.

**Comment by epiqueras** [comment]
I agree with @karmatosed, I'd go with @jasmussen's approach: https://github.com/WordPress/gutenberg/pull/17759#issuecomment-538090974.

**Comment by epiqueras** [comment]
https://github.com/WordPress/gutenberg/pull/17759#issuecomment-538123800

>It could also be shown below it, as a preview.
>
>Anyway, it looks like we can use Downshift now and stick to the original design: #16473 (comment).

**Comment by gziolo** [comment]
> Whilst, I understand the reason for exploring this, I do feel this is a problematic direction. It adds a pattern we haven't used yet but is similar to the styles. I also think if you consider adding styles and font sizes, that rapidly becomes a very complex interface to do something simple, change font size.

This is also something that theme developers can customize, so you might see there 10 options as well. In addition, people can use any text they like and any size they need so I'm afraid it won't scale.

**Comment by gziolo** [comment]
@enriquesanchez, thank you for sharing this option. It looks like related PR was closed based on the feedback received, should we close this issue, too?

**Comment by mapk** [comment]
> This is also something that theme developers can customize, so you might see there 10 options as well. In addition, people can use any text they like and any size they need so I'm afraid it won't scale.

This was one of our early concerns as well. If theme devs did customize this, it _could_ get unwieldy pretty quick.
