### ISSUE TITLE
The link explaining what is a post excerpt is linking to the wrong page

### ISSUE THREAD

**Issue by fr-laurentn** [WordPress/gutenberg#17751]
Hi, 

I've noticed that the link directing to the page explaining what is an excerpt is pointing to https://codex.wordpress.org/Excerpt.

It should point directly to https://wordpress.org/support/article/excerpt.

![image](https://user-images.githubusercontent.com/15927630/66137705-c40a3280-e5fd-11e9-8b41-88f97bac9fa9.png)

Thanks,

**Comment by Pierre-Lannoy** [comment]
I've just proposed PR #17753 for that... ;)
