### ISSUE TITLE
How to deregister column style? 

### ISSUE THREAD

**Issue by eduardoarandah** [WordPress/gutenberg#17757]
**How to deregister default column css styling?** 

Can't find any filter for that

I'd like to style it again in the frontend without having to override default styles. 

Specifically remove all this from the frontend css:

```
.wp-block-columns {
	display: flex;
	flex-wrap: wrap;
}
@media (min-width: 782px) {
	.wp-block-columns {
		flex-wrap: nowrap;
	}
}
.wp-block-column {
	flex-grow: 1;
	margin-bottom: 1em;
	flex-basis: 100%;
	min-width: 0;
	word-break: break-word;
	overflow-wrap: break-word;
}
@media (min-width: 600px) {
	.wp-block-column {
		flex-basis: calc(50% - 16px);
		flex-grow: 0;
	}
	.wp-block-column:nth-child(2n) {
		margin-left: 32px;
	}
}

```

**Comment by youknowriad** [comment]
Hi there!

this is not possible. you can opt-in or opt-out of the opinionated styles of the blocks https://developer.wordpress.org/block-editor/developers/themes/theme-support/#default-block-styles but the structural ones are mandatory.

your best bet would be to override them.

**Comment by nicomollet** [comment]
This helped: https://wordpress.org/support/topic/core-block-supports-inline-css/#post-16235888

```php
add_action('wp_footer', function () {
    wp_dequeue_style('core-block-supports');
});
```
