### ISSUE TITLE
Heading block with custom color: has-text-color class is missing

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#17761]
**Describe the bug**
I have noticed the following bugs when you apply a text color to an Heading block:

- `has-text-color` class is missing in the block output
- a link inside the title doesn't inherit from the selected color

The block editor stylesheet uses a selector that targets only paragraphs (`p.has-text-color a` instead of `has-text-color a`).

**Expected behavior**
- Blocks which have a specific text color should have `has-text-color` class.
- Links inside a block with a custom color should inherit from the color

**Additional context**
- Tested with WordPress 5.3 beta 2.

**Comment by youknowriad** [comment]
I believe thisi was added yesterday. Thanks for the issue. cc @jorgefilipecosta
