### ISSUE TITLE
Provide a simple way to add fallback content for RSS or E-mail view

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#17764]
Most blocks you author work everywhere. The paragraph block outputs its own content in the editor, in the published post, and it will work as is when consumed through an RSS feed reader, or as an email notification.

However some blocks only work in the browser, outside of E-mail and RSS clients. This includes blocks that feature advanced layout features, or blocks that are dynamic or generative based on on-the-fly browser data, things like embedded content that requires a plugin, or even something like a live-blog Block.

For those situations, block authors need to provide alternate content. Consider the following example where the AMP version of a CNN article is not able to include the embedded transcript, and instead provides a button, "View on CNN":

![amp](https://user-images.githubusercontent.com/1204802/66193482-ec903c00-e692-11e9-9e48-1a74bae2e745.png)

Here's the non-amp version of that article: https://edition.cnn.com/2019/10/03/politics/chairs-on-volker/index.html

While it should be possible for block developers to create this fallback content even today, should this use case be handled by the block editor itself? Like a developer is able to provide example content, should a developer be able to ask for a button like the above, to show up in email and RSS content? Or even provide a customized snippet of HTML?

**Comment by mkaz** [comment]
To illustrate the above two examples, one is our Timeline block it has a rich graphical layout, that requires more complex markup and CSS to style. Another is a countdown block that uses JavaScript to dynamically alter the block over time.

In both of these instances, we need to use the `save()` function to write the markup in `post_content` but what we also want is something different depending on the context (RSS, Email, Excerpt? etc...)

I'm not sure this is a new problem with Gutenberg, it probably existed with rich content and additional JS/CSS in WP prior. 

My initial thought was be adding a new server-side function, something like `render_static` that would be triggered in the other contexts, but the server-side `render_callback` function right now doesn't get called then, it currently uses what currently exists in `post_content`

**Comment by karmatosed** [comment]
> Like a developer is able to provide example content, should a developer be able to ask for a button like the above, to show up in email and RSS content? 

Whatever the feelings about the experience on these, I think so. It's a bit like the 'read more' if I am understanding this correctly?

> Or even provide a customized snippet of HTML?

I can't decide if this is extending or should be part of core editor. It feels like something to start in a plugin.

**Comment by paaljoachim** [comment]
We discussed this issue during the Gutenberg Design triage. (Link requires registering to Slack.)
https://wordpress.slack.com/archives/C02S78ZAL/p1586277268325100

@jasmussen 
Joen what are you thoughts on moving forward with this issue?
We briefly mentioned adding the feature into a plugin so that we could test it out before adding it to Gutenberg.

**Comment by jasmussen** [comment]
> Joen what are you thoughts on moving forward with this issue?

The feature suggested is sort of a "quality of life" thing for developers. It would be nice to have.

But it increasingly feels like a technical question. Is this possible to build at all? And if not, then we might as well close it. So it's mostly a matter of clearing out the technical feedback label, and closing if unfeasible! Thanks.

**Comment by jasmussen** [comment]
In absence of a good response here, I'm going to close this one and let it remain indexable by Google. If people search for it and comment for it to be reopened, we can do so!
