### ISSUE TITLE
Block preview - negative margin impacting preview visuals

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#17760]
**Describe the bug**
During implementation of block previews in Jetpack, I discovered all three blocks that have InnerBlocks display poorly in the preview pane because a core style is adding a negative margin. Here's what that looks like:

![image](https://user-images.githubusercontent.com/1123119/66156107-4682fa00-e5de-11e9-91f6-6cfd14c98b16.png)

The Contact Form block is a good example of the problem. In the following PR, I have overwritten these styles to make it look nice in the preview. I did this for the other blocks as well, but that does not address the root problem.

https://github.com/Automattic/jetpack/pull/13629

It looks like the culprit is in this file:
'gutenberg/build/block-editor/style.css?ver=1570107929`

and is this style block:

```
.block-editor-block-list__block .block-editor-block-list__layout {
 padding-left:0;
 padding-right:0;
 margin-left:-14px;
 margin-right:-14px
}
```

Found [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L56).

I'm unsure of why that component is used where it is in our blocks or if that's normal. CC @simison 

If it's on our end, we'll fix it.

@mapk @retrofox

**Comment by paaljoachim** [comment]
I am not sure, but is this issue still valid?

@WordPress/gutenberg-core

**Comment by youknowriad** [comment]
I  thinks is not relevant anymore,  the design there changed a lot.
