### ISSUE TITLE
Add PHP API for registering custom gradient presents

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#17774]
As originally discussed in https://github.com/WordPress/gutenberg/pull/17169#issuecomment-535411779 and with work continue https://github.com/WordPress/gutenberg/pull/17603 . 

In https://github.com/WordPress/gutenberg/pull/17169 gradient presents were added to buttons. This function similar to the present colors already found in gutenberg. The present colours allow for register of list of colours in PHP using theme supports. Example. 

```
add_theme_support( 'editor-color-palette',
			array(
				array(
					'name'  => __( 'Primary', 'twentynineteen' ),
					'slug'  => 'primary',
					'color' => twentynineteen_hsl_hex( 'default' === get_theme_mod( 'primary_color' ) ? 199 : get_theme_mod( 'primary_color_hue', 199 ), 100, 33 ),
				),
				array(
					'name'  => __( 'Secondary', 'twentynineteen' ),
					'slug'  => 'secondary',
					'color' => twentynineteen_hsl_hex( 'default' === get_theme_mod( 'primary_color' ) ? 199 : get_theme_mod( 'primary_color_hue', 199 ), 100, 23 ),
				),
				array(
					'name'  => __( 'Dark Gray', 'twentynineteen' ),
					'slug'  => 'dark-gray',
					'color' => '#111',
				),
				array(
					'name'  => __( 'Light Gray', 'twentynineteen' ),
					'slug'  => 'light-gray',
					'color' => '#767676',
				),
				array(
					'name'  => __( 'White', 'twentynineteen' ),
					'slug'  => 'white',
					'color' => '#FFF',
				),
			)
);
```

A similar api should be added for gradient presents. I would recommend the name `editor-gradient-presets`.

**Comment by spacedmonkey** [comment]
I have a WIP PR  #17841

While working on this PR, I am starting to believe that another `theme_supports` should be added called `disableCustomGradients` to bring it inline with colors.

**Comment by spacedmonkey** [comment]
I think we should add `add_theme_support('disable-gradient-presets')`. See #18213

**Comment by bbertucc** [comment]
@spacedmonkey - I'm working on a site now with brand guidelines that specifically discourage using gradients, so yes- would love `add_theme_support('disable-gradient-presets')`

**Comment by spacedmonkey** [comment]
@bbertucc Have you seen https://github.com/WordPress/gutenberg/pull/17603/files#diff-bda1f53deac273d361a56c63a5b90adeR146 ?

**Comment by bbertucc** [comment]
Thanks @spacedmonkey - That's an awesome experimental fix. Should I be worried about the `__experimental` part of the variable? Once its mature, will there be a fallback, or should I just keep tabs on #18213 for updates?
