### ISSUE TITLE
Image block srcset includes "unnecessary" image_sizes 

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#17778]
**Describe the bug**
This isn't a bug as much as a feature deficiency ;) And I suppose it couild be related to this:

https://github.com/WordPress/gutenberg/issues/6131

But that issue seems to be stuck in committee :) Is there any status on this? Images, especially as they can be a page load killer - are pretty important. That is, this feels like a important issue in the bigger scheme of things. 

**To reproduce**
- Added an image block
- Set the width in the tool bar to: default (content width)
- Use the inspector's Image Size select
- The frontend has images wider than the one specified. And since the sizes specifies 100vw it looks like a larger image that necessary is being picked by the browser. 

**Expected behavior**

-- Ideally, to have finer control over the images added to srcset without having to use a filter. As it is, afaik, the filter does pass the specified width attribute setting (or any block attributes value for that matter). Filtering srcset and sizes on say an index / archive grid page makes sense. Using those filters anywhere else feels llike guess work, at best. Or perhaps I'm misunderstanding things. 

Ultimately, this feels like a tough one. Doable, but at what cost to the less CSS aware content editors? Srcset + sizes makes a lot of sense...as long as you're NOT using a CMS. Maybe that's just me? :)

**Comment by paaljoachim** [comment]
Hey @AlchemyUnited 

Is this issue still valid?

**Comment by paaljoachim** [comment]
I am thinking you might have something to share in regards to this issue:
@talldan  @tellthemachines 
Thanks.

**Comment by tellthemachines** [comment]
Let's close this as a duplicate of #6131; the `sizes` should really be specified by the theme.
