### ISSUE TITLE
Gallery block not "Cropping" images not working on Internet Explorer and Edge 15

### ISSUE THREAD

**Issue by mlaetitia** [WordPress/gutenberg#17775]
**Describe the bug**

When setting up a Gallery block and choosing the option Crop Image : 

![see screen shot](https://cld.wthms.co/gp8Uhm+) https://cld.wthms.co/gp8Uhm

on Internet Explorer 11 or Edge 15 the images don't get cropped - on the editor, preview or live site.

**To reproduce**
1. Go to Post or Page -> Add New Gallery block and choose two / three pics having at least one in portrait and one landscape
2. Choose the option "Crop Images"
3. From the editor, you can see the images aren't cropped / the same size.

**Expected behavior**
As with other browsers the images should be the same size in the gallery

**Screenshots**
In IE 11: https://cld.wthms.co/pDI7Pu
In Firefox: https://cld.wthms.co/hI3RbE

**Desktop (please complete the following information):**
Tested on Browser Stack, plus on a Windows 7 + IE11 computer

**Comment by bunglegrind** [comment]
...because of object-fit: cover not supported by IE11 and EDGE < 16.

**Comment by bunglegrind** [comment]
a workaround:

`.is-cropped .blocks-gallery-item img {
  width: auto !important;
  height: 230px !important;
  max-width: 1000% !important;
  position: relative;
  top: 50%;
  left: 50%;
  -webkit-transform: translateX(-50%) translateY(-50%);
  transform: translateX(-50%) translateY(-50%);
}

.is-cropped .blocks-gallery-item figure {
  overflow: hidden;
}

@supports ((-o-object-fit: cover) or (object-fit: cover)) {
  .is-cropped .blocks-gallery-item img {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    -o-object-fit: cover;
    object-fit: cover;
    height: 230px !important;
    width: 100% !important;
    max-width: 100% !important;
    position: unset !important;
    top: unset !important;
    left: unset !important;
    -webkit-transform: unset !important;
    transform: unset !important;
  }

  .is-cropped .blocks-gallery-item figure {
    overflow: unset !important;
  }
}`

**Comment by talldan** [comment]
Thanks for reporting this.

Despite it being mentioned that `object-fit` is now pollyfilled in IE11 (see #25171), this seems to still be a bug when I tested.

See the following screenshots for comparison:
IE11:
<img width="1329" alt="Screenshot 2020-09-29 at 1 30 01 pm" src="https://user-images.githubusercontent.com/677833/94516368-3edd4c00-0258-11eb-82ad-8cc379237be7.png">

Firefox:
<img width="857" alt="Screenshot 2020-09-29 at 1 30 10 pm" src="https://user-images.githubusercontent.com/677833/94516409-50265880-0258-11eb-8874-7c3fa07a4145.png">

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
