### ISSUE TITLE
Data: Silent test failure in registry tests

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#17771]
There is an unhandled promise rejection which occurs in `pacakges/data/src/test/registry.js` which appears to be intended to cause the test suite to fail. The warning is shown in the test output, but the tests pass nonetheless:

```
⇒ npm run test-unit packages/data/src/test/registry.js           

> gutenberg@6.6.0 test-unit /Users/andrew/Documents/Code/gutenberg
> wp-scripts test-unit-js --config test/unit/jest.config.js "packages/data/src/test/registry.js"

(node:3104) UnhandledPromiseRejectionWarning: Should not have dispatched
(node:3104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  packages/data/src/test/registry.js
```

Relevant code:

https://github.com/WordPress/gutenberg/blob/3d7e81324563461232b3954fb6e11274515ff5c2/packages/data/src/test/registry.js#L352-L358

In addition to resolving the underlying issue, the `throw` should be updated or replaced with another implementation which fails the test suite as expected.

**Comment by epiqueras** [comment]
I'm pretty sure errors in callback-style async jest tests are supposed to be ignored.

We could easily refactor this into checking for a flag instead.

But, I don't think the test makes sense. The store will dispatch the `START_RESOLUTION` action, because there is a resolver for the selector being called. @youknowriad Do you remember what the intention was when writing this?

**Comment by youknowriad** [comment]
I think the test make sense. Initially,  the ` START_RESOLUTION` was not fired per store, but it was fired in a specific store only. Once we refactored that, this test probably started breaking (false positive).

We could check that the reducer is not called with an "undefined" action instead (the value returned by the resolver's promise).

**Comment by epiqueras** [comment]
>We could check that the reducer is not called with an "undefined" action instead (the value returned by the resolver's promise).

That value is not dispatched though.

We could check for the `START_RESOLUTION` action explicitly.

**Comment by youknowriad** [comment]
> That value is not dispatched though.

Well that's the whole purpose of the test, ensure that the value is not dispatched. Basically if the reducer is called with that value, it's an error.

**Comment by epiqueras** [comment]
```js
	const mapSelector = ( selector, selectorName ) => {
		const resolver = resolvers[ selectorName ];
		if ( ! resolver ) {
			selector.hasResolver = false;
			return selector;
		}

		const selectorResolver = ( ...args ) => {
			async function fulfillSelector() {
				const state = store.getState();
				if ( typeof resolver.isFulfilled === 'function' && resolver.isFulfilled( state, ...args ) ) {
					return;
				}

				const { metadata } = store.__unstableOriginalGetState();
				if ( metadataSelectors.hasStartedResolution( metadata, selectorName, args ) ) {
					return;
				}

				store.dispatch( metadataActions.startResolution( selectorName, args ) );
				await fulfillResolver( store, mappedResolvers, selectorName, ...args );
				store.dispatch( metadataActions.finishResolution( selectorName, args ) );
			}

			fulfillSelector( ...args );
			return selector( ...args );
		};
		selectorResolver.hasResolver = true;
		return selectorResolver;
	};
```

So `store.dispatch( metadataActions.startResolution( selectorName, args ) );` dispatches something to one store, but `undefined` to all the others?

**Comment by youknowriad** [comment]
no what we're testing here is inside `fulfillResolver` and has nothing to do with `startResolution`.

We're testing that if a resolver returns a promise, and that promise resolves to a value that is not in the current shape `{ type: "something", ...}`, that value is not dispatched as an action (you'll notice that the previous test is about the opposite, checking that action-like objects are dispatched)

**Comment by epiqueras** [comment]
```js
	const action = resolver.fulfill( ...args );
	if ( action ) {
		await store.dispatch( action );
	}
```

Right, the promise gets dispatched here. So if the promise resolves to undefined, the middleware will dispatch undefined, and that's what's failing here.

**Comment by youknowriad** [comment]
Right, it looks like a regression to me.  I feel ideally,  we shouldn't dispatch automatically here at all (I guess that's what causing the "post" action to be triggered in the "core-data" store when you save a post). It is though a breaking change, but given that it has a potential of breakage, maybe we can do the breaking change and dev-note it.

**Comment by epiqueras** [comment]
>(I guess that's what causing the "post" action to be triggered in the "core-data" store when you save a post)

Yeah.

I know Jetpack relies on it. Should we change it? We could do it at the middleware level.

**Comment by epiqueras** [comment]
I think we should change it. It was never documented and relying on it leads to less declarative and reactive code.

**Comment by jsnajdr** [comment]
The offending test has been removed in #36344.
