### ISSUE TITLE
Writing Flow: Cannot type after clicking below writing prompt in new post

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#17776]
**Describe the bug**

Previously, when starting a new post, you could click anywhere in the blank space and start typing immediately. Currently, this does not work as expected.

- When clicking on the ["click redirect" element](https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/block-editor/src/components/writing-flow/index.js#L407), a new paragraph is added, but the caret is not placed immediately within it. Another click is necessary to begin typing.
- The "click redirect" element is assigned a maximum height ([50vh](https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/edit-post/src/components/visual-editor/style.scss#L10-L12)), so clicking toward at the bottom of the viewport will not create or focus the last block.

For context, this behavior was originally implemented to mimic the behavior of other editors and text fields (e.g. the empty space below the first line of text in the comment field textarea on this page).

There's even an end-to-end test which is falsely passing which is expected to enforce this behavior of immediately typing after clicking in the space below the writing prompt:

https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/e2e-tests/specs/adding-blocks.test.js#L33-L35

**To reproduce**

1. Navigate to Posts > Add New
2. Click **_below_** the writing prompt
3. Start typing
4. Note that while the paragraph was created and is focused, your typed characters are not reflected because the caret was not placed within the paragraph

**Expected behavior**

A new paragraph is created, and typing results in characters added to the paragraph.

**Desktop:**
 - OS: macOS Mojave 10.14.6 (18G103)
 - Browser: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context:**

Ideas for suspected causes:

- Async rendering of block list prevents caret focus within newly created block?
- Thought to have been possibly related to [this discussion](https://github.com/WordPress/gutenberg/pull/16460/files#r309260478), but reverting the change appears to have no effect.
- Pull requests #16460, #16500, and #16846 have changes in code relevant to this behavior and could be starting points for debugging.

Presumably, the behavior worked based on the following steps:

- The redirector [focuses the last text field](https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/block-editor/src/components/writing-flow/index.js#L379-L385)
- The default block appender (writing prompt) [is a textarea](https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/block-editor/src/components/default-block-appender/index.js#L61-L68) which appends a new block when focused
- The new block would become selected and [place the caret within itself](https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/block-editor/src/components/block-list/block.js#L203-L240)

**Comment by aduth** [comment]
@youknowriad I think this was introduced in #16500. Specifically, the logic which would normally result in the newly-added paragraph from focusing itself bails because the "breadcrumb" is considered the focused element at this condition:

https://github.com/WordPress/gutenberg/blob/f68a107c777169cd80b3ce56ec4f7c8360f2178c/packages/block-editor/src/components/block-list/block.js#L209-L215

**Comment by youknowriad** [comment]
the `edit` mode is supposed to be triggered when you click the canvas. I think the issue here is that it's not when we click the redirect element.
