### ISSUE TITLE
Read more does not function as expected when used as a reusable block

### ISSUE THREAD

**Issue by lordmatt** [WordPress/gutenberg#17783]
**Describe the bug**
If you add the "More" element as a reusable block, that block is ignored entirely.

Seen in Version 6.6.0 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Layout Elements
2. Click on "More"
3. Edit the "Read more" text
4. add this version to reusable blocks
5. Start a new post
6. Use your new reusable block
7. Publish the post
8. View post
9. See that WordPress has ignored the block

**Expected behaviour**
The index page should show everything up to the "more" and then show the custom text you have supplied as a link which is what happens with the "More" block.

**Comment by youknowriad** [comment]
Duplicate of #8633
