### ISSUE TITLE
cursor position in inserter menu

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#17788]
**The text cursor in the inserter menu is below the text input**
The blinking cursor is not where the text that I type is.

**To reproduce**
1. Click on the + icon at the bottom of a block to bring up the inserter menu.
2. Note where the text cursor is.
3. Type a character.
4. Note that the character is not typed where the cursor is, and cursor doesn't move.

**Expected behavior**
The cursor should be in the text input field, where you type.

**Screenshots**
![cursor-position](https://user-images.githubusercontent.com/7957680/66261989-35341c00-e79d-11e9-8bd3-c31db1a13881.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu Studio 16.04
 - Browser: SeaMonkey 2.49.5
 
**Additional context**
- I was testing WP 5.3 beta2.
- It appeared correctly in Firefox 69.

**Comment by youknowriad** [comment]
Hi There! thanks for the issue but I don't think that's a browser that is officially supported. https://make.wordpress.org/core/handbook/best-practices/browser-support/

**Comment by joyously** [comment]
I know, but it's my best option, and I'm sure there are others in my situation. I don't have the setup to test it in IE11 or other supported browsers.
How can something as simple as cursor placement be a browser issue? Why have such fragile code?

**Comment by youknowriad** [comment]
I'm not certain that is due to fragile code? Anything, in particular, makes you think otherwise?

for this particular issue, I remember that Firefox used to suffer from the same issue a long time ago. It could be that SeaMonkey is using an outdated version of the Firefox rendering engine.

**Comment by joyously** [comment]
Yes, SeaMonkey is based on older Firefox.
So your answer could have been better expressed as "that is a browser bug", instead of "we don't support your browser". There is a big difference.
