### ISSUE TITLE
Can't paste inside new column until manually add content

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#17784]
### Problem

1. Copy some content
1. Add a new Columns block
1. Try to click inside one of the columns in order to set the cursor position, so that you can paste something inside that column

You can't paste anything until you manually add a Paragraph block via the UI inserter. That's a clunky flow, and will also be confusing to a lot of users, who won't think to add a Paragraph first.

### Potential Solutions

Maybe add an empty paragraph below the placeholder button, but delete it if the user uses the button to insert a different type of content?

Or maybe set the cursor inside the container automatically, so that pasting something replaces the button?

**Comment by paaljoachim** [comment]
Hey @iandunn Ian.

Is this issue still valid?

From my own testing. 
I copied some text.
Made a new column. 
With the inserter added a paragraph block.
Then pasted the text into the block.

**Comment by iandunn** [comment]
It looks like the UI/flow has changed since I created this, and it now forces you to explicitly add a block before you can interact with the column. It also makes it obvious that you need to do that, so I think that fixes the issue 👍🏻
