### ISSUE TITLE
Create Custom HTML Anchor for Cover Image Block

### ISSUE THREAD

**Issue by jarretc** [WordPress/gutenberg#17781]
When creating a Heading block, you're allowed to set a custom HTML Anchor within the Advanced block settings. However, when creating a Cover Image block this option isn't available.

**Comment by youknowriad** [comment]
noting that you ca nest the cover block inside a group block and you can assign an HTML Anchor to the group block.

**Comment by adam66** [comment]
"Group Block" is not released yet, right? Just surfing around to check the alternatives. Looks like there's currently a plugin that offers a "Section" block. If I made extensive use of such a plugin, I'd have to convert each one manually to a "Group" block when 5.5 comes out, right? Would it best to stay patient? I'm a big fan of keeping it simple.

**Comment by youknowriad** [comment]
The group block will be included in the upcoming WP 5.3 release. Otherwise, you can just install the Gutenberg plugin in the meantime.

**Comment by frogdesk** [comment]
The release of the group block, while awesome, does not really solve this problem. Cover still has different functionality from the group block, such as an image background with a fixed position.

IMO, it would be best to give all the cover block functionality to the group block and just combine the blocks, but, either way, it doesn't really make sense to have a block that you cannot give an anchor tag IMO.

**Comment by paaljoachim** [comment]
Here is an issue that is aiming to add a link to the Cover block.
https://github.com/WordPress/gutenberg/issues/12684

Accessibility mentioned a problem of linking the Cover Block (which should be possible to be linked) because of the inline link that can be added. Having a linked item inside another linked item was a big no no as I understood from reading a comment in the above issue..

**Comment by youknowriad** [comment]
This is actually possible now.

**Comment by paaljoachim** [comment]
Will this in any way help this issue? (I linked to the comment which basically shut down the issue.)
https://github.com/WordPress/gutenberg/issues/12684#issuecomment-698198163

**Comment by youknowriad** [comment]
It's unrelated IMO. this just adds an id to the cover wrapper.
