### ISSUE TITLE
Image Block: breaks when setting the align

### ISSUE THREAD

**Issue by chiilog** [WordPress/gutenberg#17799]
**Describe the bug**

If I set `settings.attributes.align.default = 'right';`, when it breaks.

**To reproduce**

```
import { addFilter } from '@wordpress/hooks';
addFilter(
    'blocks.registerBlockType',
    'my-plugin/support-default-image-align',
    ( settings, name ) => {
        if ( name !== 'core/image' ) {
            return settings;
        }
        settings.attributes.align.default = 'right';

        return settings;
    }
);
```

**Expected behavior**

I expected that set default alignments.

**Screenshots**

<img width="603" alt="20191007172319" src="https://user-images.githubusercontent.com/25993565/66296392-6b51d700-e928-11e9-923f-73e1b7787a45.png">

<img width="746" alt="20191007172334" src="https://user-images.githubusercontent.com/25993565/66297235-43fc0980-e92a-11e9-8f4a-5f372122cb35.png">

**Additional context**
- Gutenberg 6.5

**Comment by skorasaurus** [comment]
I'm able to still reproduce on Gutenberg 9.5.2.

**Comment by paaljoachim** [comment]
@talldan Dan are you able to take a look?

Thanks.

**Comment by talldan** [comment]
It worked fine for me, so not really able to help:
![image-right](https://user-images.githubusercontent.com/677833/107601267-2eef6300-6c61-11eb-973a-948c59d053f0.gif)

@chiilog Is this still happening for you?

**Comment by 5n** [comment]
@talldan Hi, I'm also able to still reproduce on Gutenberg 10.1.1.
The problem is that the value of default alignment is not saved in block’s markup.

If you don't set default alignment:
```
<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->
```

If you set default alignment as 'right':
```
<!-- wp:image -->
<div class="wp-block-image"><figure class="alignright"><img alt=""/></figure></div>
<!-- /wp:image -->
```

It works fine for new blocks, but not for existing blocks.

**Comment by talldan** [comment]
I see, yes, changing the default alignment would invalidate existing blocks that don't have that alignment. That is the expected behavior.

I think your code would need to add a deprecation to the image block to handle that (https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/).
