### ISSUE TITLE
Block Editor Padding Error 

### ISSUE THREAD

**Issue by hamidlatache** [WordPress/gutenberg#17792]
**Hello guys**
**The padding of the block is not well adjusted for use**

![image](https://user-images.githubusercontent.com/55231501/66273679-e4402880-e86d-11e9-91ec-063810c93f7b.png)

- As you can see guys, The area where I write or I add blocks is not well adjusted and it's smaller. I have looked for similar issues but I couldn't find a solution that can help. I have tried to install the Gutenberg plugin but has given me this error: 
![image](https://user-images.githubusercontent.com/55231501/66273738-9a0b7700-e86e-11e9-9cdb-4dde5e8fba31.png)

**Please provide me with a suitable solution.**
Thank you!

**Comment by youknowriad** [comment]
1- In Gutenberg, it's the theme's responsibility to adjust the width of the canvas. See #16747 for more details.

2- Is it possible that you have the Gutenberg plugin installed twice? or maybe there's another plugin redeclaring that function, try disabling your plugins.

**Comment by hamidlatache** [comment]
> 1- In Gutenberg, it's the theme's responsibility to adjust the width of the canvas. See #16747 for more details.
> 
> 2- Is it possible that you have the Gutenberg plugin installed twice? or maybe there's another plugin redeclaring that function, try disabling your plugins.

Yeah I think there is a problem in the theme, I forced to change the theme unfortunately
