### ISSUE TITLE
Iterate information section

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17806]
Currently, we combine document outline with the information panel. There are explorations into how that could become one 'navigator', combining block navigator and document outline. With that in mind, the information panel could transform into a useful single.

Here is what we have today:

<img width="438" alt="Frame 8" src="https://user-images.githubusercontent.com/253067/66307364-2dd75480-e8fc-11e9-9318-9f3af5310de6.png">

I have begun some exploring around this taking inspiration from apps like Bear (which was original inspiration for @mtias when this idea first came around):

<img width="297" alt="bear" src="https://user-images.githubusercontent.com/253067/66307391-3c257080-e8fc-11e9-95d3-8aab60f87767.png">

My focus isn't on a redesign as much as adding information to it and taking away the outline. I feel this is a good first step. 

[NOTE: the first designs shown here are abstraction sketches, exploring in confines of the existing design, I will be going beyond as we decide what to include]

<img width="370" alt="Frame 6 11" src="https://user-images.githubusercontent.com/253067/66307735-1ba9e600-e8fd-11e9-88c0-823317a0ff20.png">

We could maybe explore an alternative design...

<img width="352" alt="Frame 6 11" src="https://user-images.githubusercontent.com/253067/66307843-6af01680-e8fd-11e9-8bb7-cd1167d87c47.png">

For now, the things I think are good to add:

- Revisions link
- Last modified date
- Status of post
- Time to read (this might not be something to add but put as a could have).

I have taken away paragraphs as not sure how useful, but of course that can be added. One note is to consider how this section can expand to include things that come with collaborative editing and other 'document' information.

Based on the above exploring here are some questions to then lead me to next iterations:

1. What should be the contents of this panel?
2. Is there a preferred size for this? I have shown 2 variations at 300 and 250 (on desktop). Both, are smaller than the existing one which I think is the better approach.

**Comment by phpbits** [comment]
@karmatosed I would like to suggest that slotfill should be available on this section as well. I've recently added Estimated Reading Time on EditorsKit plugin : https://wordpress.org/plugins/block-options/ and using JS append since there's no way to extend the information section. Thanks!

https://twitter.com/editorskit/status/1175992071687036928

![EFH2jMPVUAA4msy](https://user-images.githubusercontent.com/3365507/66310476-e0300b80-e93e-11e9-8743-808fbd8b97b9.jpeg)

**Comment by karmatosed** [comment]
@phpbits totally agree that once this is just information having it easier to extend is a great step forward. Thanks for pushing on that.

**Comment by karmatosed** [comment]
For now, let's close this as there is a lot of moving interface with the block navigator. Once that all settles revisiting how that could fit is a nice next step.
