### ISSUE TITLE
Add function to check Gutenberg version via Javascript

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#17809]
**Is your feature request related to a problem? Please describe.**
Add a way to check Gutenberg version via JS similar to what we have on PHP `wpVersions > 5.3 || gutenbergVersion > 6.4`. This will help us plugin users to create conditional statement and deprecated conditions on blocks and features. Thanks!

**Comment by youknowriad** [comment]
There's nothing specific to Gutenberg in this proposal. I think if we were to do something, it should be a generic thing for all plugins. I'd suggest opening a trac ticket instead. Thanks.

**Comment by phpbits** [comment]
@youknowriad Changed to `gutenbergVersion > 6.4` so it'll be specific to Gutenberg. Thanks!

**Comment by youknowriad** [comment]
What I'm saying is that you want to check the gutenberg plugin's version, someone else might want to check Yoast version... You should be able to check any plugin's version.

**Comment by phpbits** [comment]
@youknowriad Ah sorry for the confusion. What I'm meaning to say is the `editor` version itself not the Gutenberg plugin.Thanks!
