### ISSUE TITLE
Data: withSelect throws "Invalid hook call" React error

### ISSUE THREAD

**Issue by adekbadek** [WordPress/gutenberg#17805]
**Describe the bug**
When trying to use `withSelect` from `@wordpress/data` (in a WP plugin code), [error](https://reactjs.org/docs/error-decoder.html/?invariant=321) is thrown by React:
```
Invalid hook call. Hooks can only be called inside of the body of a function component.
```

**To reproduce**
A. Locally with a WP setup: recreate the [basic example](https://github.com/WordPress/gutenberg/blob/master/packages/core-data/README.md#example) to display authors
B. Or, see [reproduction on codesandbox](https://codesandbox.io/s/heuristic-feather-8mn37)

**Expected behavior**
Error is not thrown.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 77, Firefox 69

**Comment by adekbadek** [comment]
Update: the problem might be due to react versions mismatch between my plugin code and Gutenberg plugin: 
1. Deactivating Gutenberg plugin solves the issue, 
1. as does [externalizing react dependencies](https://github.com/webpack/webpack/issues/1275#issuecomment-176255624) in webpack (with which the plugin code is bundled).

**Comment by adekbadek** [comment]
Possibly duplicate of #15873

**Comment by gziolo** [comment]
> Or, see [reproduction on codesandbox](https://codesandbox.io/s/heuristic-feather-8mn37)

I can confirm that it’s the same issue as #15873. Let’s continue there.

**Comment by gziolo** [comment]
@adekbadek, thank you for sharing detailed reproduction steps 👍
