### ISSUE TITLE
Insert new components tab not work into responsive 

### ISSUE THREAD

**Issue by viralsampat90** [WordPress/gutenberg#1780]
Hello all,

I have checked the Gutenberg plugin on my mobile device and I want to add a component from Insert components tab.

But, it does not display properly on my mobile device.

For better understanding, I have attached screenshot.

Please let me know if anything.

![insert_components_issue](https://user-images.githubusercontent.com/29949460/27959555-8a79543e-6345-11e7-8643-92883005c9eb.gif)

**Comment by karmatosed** [comment]
Currently the entire (pretty much) non-desktop experience is flawed. This is just one of many issues. Let me label this for now, but we will have to consider the entire mobile experience.

**Comment by jasmussen** [comment]
This should be fixed!
