### ISSUE TITLE
Should Image Block use `Full` as default image size?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#17803]
**Describe the bug**
I'm creating Gutenberg Tips and Tricks; and seems like this should be resolved on core : https://twitter.com/editorskit/status/1179727978353135616 . Thanks!

**Comment by paaljoachim** [comment]
Hey Jeffrey.

I have a feeling this is being looked at in different newer issues. 
I have also noticed that "bigger" images will automatically show I believe Large size, and "smaller" images will default to the thumbnail size. There are some bugs around these that need to be looked at. There are a few issues circling around.

I am wondering if we should close this issue.
What do you think?

**Comment by paaljoachim** [comment]
Hey Jeffrey @phpbits 

Currently the default image size is "Large".

There is another issue.
Image Size: Remember the last size used.
https://github.com/WordPress/gutenberg/issues/8663

I will go ahead and close this issue. I hope that is alright.
