### ISSUE TITLE
Upload image from media not found.

### ISSUE THREAD

**Issue by parmarhardip** [WordPress/gutenberg#1782]
Hello,

I have tried to upload an image from Image section. It was not displaying the existing or newly added images in the image uploder. For more information please see GIF image.

Thanks,

![upload_image_issue](https://user-images.githubusercontent.com/23077242/27961522-9c43d52a-634c-11e7-976a-ef4af1a1e228.gif)

**Comment by karmatosed** [comment]
I can also replicate this with 0.3.0 version of the plugin. I think it's a matter of that not being implemented yet but it's really worth noting and getting resolved when implemented.

**Comment by westonruter** [comment]
@parmarhardip @karmatosed this should be fixed as of https://github.com/WordPress/gutenberg/pull/1682

It will be part of the impending 0.4.0 release. Please test again either on `master` now or once the new release is out.

**Comment by karmatosed** [comment]
I am unable to replicate this so closing. If you are able to @parmarhardip then please could you add those details and we can reopen. Thanks.
