### ISSUE TITLE
Edit "Submit for review" button functionality

### ISSUE THREAD

**Issue by lcerliani** [WordPress/gutenberg#17822]
Hi everyone! I've been investigating through weeks and I found nothing to solve my problem. I need to edit the "Submit for review" button functionality, actually it sends the post from draft to pending, but I need to make it open a modal when I click it. I didn't find a hook or something similar, I tried to access the button with javascript getElementsByClassName and nothing, I'm really going crazy with this.

Any idea would be grateful.

Thanks!
Lucas.

**Comment by youknowriad** [comment]
Hi there!

I don't think that's currently possible. DOM access is not considered an API and is going to break very quickly.

What is this modal about, maybe you can consider using the "PrePublish" slots instead. https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/

Note that this tracker is not used for help requests.
Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.
You may also ask for technical support at https://wordpress.stackexchange.com/.
Thank you!
