### ISSUE TITLE
Add Custom URL to Gallery

### ISSUE THREAD

**Issue by peterpenguw** [WordPress/gutenberg#17833]
**Is your feature request related to a problem? Please describe.**
What is the point of a gallery if a business can't generate call to actions from it?  I want people to "shop" my gallery by clicking the picture, which should open a URL I customize.  Literally no one is using "attachment pages" or "media" files as the default link option

**Describe the solution you'd like**
Currently there are 3 options for each picture of a gallery... the 4th one should be "CUSTOM URL"

**Describe alternatives you've considered**
classic editor or elementor

**Comment by talldan** [comment]
Closing as a duplicate of #10057.
