### ISSUE TITLE
Add support for other "group"-like blocks

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#17837]
**Is your feature request related to a problem? Please describe.**
I have a Container block that behaves mostly like the new Group block and I'm trying to create a "convert to container" button that is similar to the new "covert to group" button.

Mine somewhat works after mimicking how things are done in https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/convert-to-group-buttons/convert-button.js

It only works though if you're grouping the **same** types of blocks together (e.g. 2 paragraph blocks). Grouping different types of blocks (e.g. a heading block and a paragraph block) doesn't work.

I traced the problem to the `switchToBlockType` function. It's stopping my grouping from happening because there's a check for `! isContainerGroupBlock( name )` that fails since this checks whether the block trying to do a grouping matches the currently registered `core/group` block. It doesn't allow for multiple container/group-like blocks.

**Describe the solution you'd like**
Allow the registration of other "group"-like blocks that would allow `isContainerGroupBlock` to pass. This in turn would allow `switchToBlockType` to work for custom "group"-like blocks.

This might need some code refactoring since `getGroupingBlockName` would probably need to be changed as well to accommodate multiple types of grouping blocks.

**Describe alternatives you've considered**
My current work around is to override the registered grouping block name before doing my `switchToBlockType` then reverting it afterwards. I need to revert it afterwards or else the native Group Button will stop working.

```js
// Workaround is to set my own grouping block name temporarily.
const currentGroupingName = select( 'core/blocks' ).getGroupingBlockName()
setGroupingBlockName( 'ugb/container' )

// Activate the `transform` on the Grouping Block which does the conversion
const newBlocks = switchToBlockType( blocksSelection, groupingBlockName )

if ( newBlocks ) {
	replaceBlocks(
		clientIds,
		newBlocks
	)
}

// Bring back the original grouping block name.
setGroupingBlockName( currentGroupingName )
```

**Comment by talldan** [comment]
This was probably a decision made on purpose to avoid too many options in the block menu.

@getdave developed the grouping functionality and might be able to offer more insight.

Block transforms would be the recommended alternative.

**Comment by bfintal** [comment]
@talldan maybe, but I don't think the options in the block menu is the problem here since it's easy to add a menu in there right now using `PluginBlockSettingsMenuItem`. 

I think the problem key here is that the `switchToBlockType` won't work for multiple blocks unless it's the `core/group` block.

**Comment by talldan** [comment]
Right, I see. I think about it slightly differently, that there could be improvements to the transform system rather than allowing more grouping blocks. You mentioned:

> It only works though if you're grouping the same types of blocks together

But what if that wasn't the case, and instead a selection of blocks that all were able to transform to the same block type were allowed. 

An example would be a playlist block that allows inner video and audio blocks. If a user makes a selection of separate image and video blocks, the transform system currently would not allow them to be transformed/grouped to a single block. Perhaps it should? The advantage here is that a playlist can't just 'group' any block, but using the transform system would allow specific blocks to be 'grouped'.

**Comment by bfintal** [comment]
I agree, and I think @getdave already had that in mind https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/group/index.js#L90 :)

**Comment by getdave** [comment]
I'm sorry. My Github foo has been off and I've missed a tonne of pings. Apologies and thanks for raising this.

> It only works though if you're grouping the same types of blocks together

That's expected (as you've realised). The Grouping mechanic is handled at many locations at a lower level based on whatever is assigned as the default "container" block.

We could have more grouping blocks, but I'd be slightly wary of this opening the door to the possibility of 3rd party Blocks registering as grouping Blocks. If we created a "Group using..." UI for each registered "container" we'd quickly find the UI becoming quite cluttered! Not sure if this is exactly what you were suggesting but I thought I'd present my concerns around this. 

As you know you can already change the default Container Block to your own Block. In addition, you still have transforms which you can register to handle other container types you might have.

>  have a Container block that behaves mostly like the new Group block and I'm trying to create a "convert to container" button that is similar to the new "covert to group" button.

I'm wondering whether a "secondaryContainerBlocks" could be created which could house any 3rd party Blocks registered. The default container Block would remain "as is" but we'd adjust all the mechanics to also account for the Blocks registered as secondary container Blocks thereby allowing you to create this custom UI if you needed.

Just my thoughts such as they are.

**Comment by youknowriad** [comment]
Closing as this seems intended per the previous discussion.
