### ISSUE TITLE
Insert block programmatically to a page thanks to its id

### ISSUE THREAD

**Issue by anUserFr** [WordPress/gutenberg#17849]
I am doing a theme. When admin chooses a services page (page that displays all services) from the existing pages on the site, I want to programmatically insert a block "services" on this page thanks to the id of the page.

```
let block = wp.blocks.createBlock( 'core/paragraph', { content: 'test' } );
wp.data.dispatch( 'core/editor' ).insertBlocks( block );
```

The code above is interesting, but that insert a block on the current page, while I wish on another page thanks to its id

**Comment by simonhammes** [comment]
Off the top of my head: I think you need to do this in PHP and insert the block "manually" into the post content (maybe using the WP REST API).

**Comment by talldan** [comment]
Looks like this questions has been answered, so I'll close the issue. I'd also mention that repo's issues are supposed to be related to Gutenberg rather than a help forum for theme development.

There are lots of other places to ask questions like Stack Exchange or the WP.org forums.
