### ISSUE TITLE
Relative time in block-directory-controller.php should be i18n-friendly

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#17844]
Location:
https://plugins.trac.wordpress.org/browser/gutenberg/trunk/lib/class-wp-rest-block-directory-controller.php#L303

Contains the line:
`$block->humanized_updated = human_time_diff( strtotime( $plugin['last_updated'] ), current_time( 'timestamp' ) ) . __( ' ago', 'gutenberg' );`

Which creates the string " ago" for translation.

1. It's unlucky that the string begins with a space without this being specifically noted in a translators' comment.
2. The string "3 minutes ago", would in Swedish ideally translate into "För 3 minuter sedan". I.e. the term "ago" is split into 2 pieces and the time value should be injected between them. 
This can be easily handled in PHP with printf(), but is there any decent way to do this in JS, too?

At least, a translators' comment would be needed, though.

**Comment by paaljoachim** [comment]
Hi @tobifjellner 

Thanks for creating the issue Tobi!
A lot of time has passed since it was created.
Is the issue still valid?

@swissspidy Pascal. I am pinging you into this issue and hope that is alright.

**Comment by tobifjellner** [comment]
This particular string looks OK now.
Ref: https://plugins.trac.wordpress.org/browser/gutenberg/tags/9.7.4/lib/compat.php#L56

```
'relative'      => array(
--
/* translators: %s: Duration. */
'future' => __( '%s from now', 'default' ),
/* translators: %s: Duration. */
'past'   => __( '%s ago', 'default' ),
```
