### ISSUE TITLE
List: Merging lists erroneously joins indented items

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#17843]
**Describe the bug**
Assuming two List blocks:

 _List one_

* ABC
  * DEF
  * GHI
  * JKL

_List two_

* MNO

Merging these lists will yield:

* ABC
  * DEFGHIJKL
* MNO

**To reproduce**
1. Start a new post
2. Add two consecutive List blocks, per the example above
3. Place the caret at the start of _MNO_
4. Press <kbd>Backspace</kbd>

Alternatively:

3. Place the caret at the end of _JKL_
4. Press <kbd>Delete</kbd>

**Expected behavior**
The merged list would be:

* ABC
  * DEF
  * GHI
  * JKL
* MNO

/cc @ellatrix

**Comment by ellatrix** [comment]
Oooh! Thanks!
