### ISSUE TITLE
Columbus WordPress Meetup, Gutenberg Review

### ISSUE THREAD

**Issue by ameeker** [WordPress/gutenberg#1787]
Last night at our meetup, we installed Gutenberg, and then attempted to use it to write a post. There is a (sort of crappy) video of this meetup at https://www.facebook.com/wordcampcolumbus. Here are some of the observations from our Meetup members:

Their overall question was why? Why is this necessary? One member said, "It seems like they're trying to build a page builder, but page builders already exist that do much more than this, so why use this if you want a page builder?"

Those who are aware of Calypso wanted to know what Gutenberg has to do with Calypso. A year ago, Calpyso was the best thing since sliced bread, and now it seems like that shifted to Gutenberg. In both cases, the why question comes up again.

They wanted to know how this will interface with the Customizer. Will this eventually allow users to see their edits on the front end, live like the Customizer does now? If not, why was that feature built out quite the way it was in the first place.

They really liked being able to insert widget areas anywhere.

They did not like how a hard return (two enters) created a new block.

They want to know if page/post templates built using Gutenberg will be able to be shared amongst users (like themes now). 

In the same vein, they want to know if templates created using Gutenberg can be saved on the same site for later reuse.

They wanted to see even more page builder esque features, since to them, that's what Gutenberg is. They didn't seem to understand why they would use this when BeaverBuilder, Divi, Elementor allow them to do much more. This seems like a "lite" but not as practically useful page builder.

They wanted easier column support.

The individual settings that only appear when the mouse is placed in an element, or hovered over - they didn't like that. Hiding the settings on hover has consistently been a dislike of our meetup (for example, the current Posts admin page, where you have to hover to see "edit, quick edit, delete, etc..."

The Insert drop down was not immediately obvious as to what it did. The tabs within it, neither.

They wanted to be able to drag/drop blocks rather than using the arrows. They wanted to be able to drag and drop blocks into columns.

They wanted to know if the blocks would eventually have their own settings in the right side to allow them to assign colors or specific widths to the blocks. 

That's all.

**Comment by nylen** [comment]
Thanks for writing up this feedback.  I can answer a few of these questions; for others (drag and drop, column support for example) there are already dedicated issues if you search the repository.  I can also point you towards our nascent FAQ document:  https://github.com/WordPress/gutenberg/blob/master/docs/faq.md

> They wanted to see even more page builder esque features, since to them, that's what Gutenberg is. They didn't seem to understand why they would use this when BeaverBuilder, Divi, Elementor allow them to do much more. This seems like a "lite" but not as practically useful page builder.

This is a very early version of the page builder that Gutenberg will eventually become.  We plan to start within the post content / editor and gradually expand outwards to cover more parts of the page.

> They wanted to know how this will interface with the Customizer. Will this eventually allow users to see their edits on the front end, live like the Customizer does now?

This is the general plan, yes.

> They want to know if page/post templates built using Gutenberg will be able to be shared amongst users (like themes now).
>
> In the same vein, they want to know if templates created using Gutenberg can be saved on the same site for later reuse.

There is some related discussion at #991.

**Comment by ameeker** [comment]
I understand it's very earlier, but with Matt's suggestion that it will be out in 5.0, I just don't see it. I don't see how this could possibly be ready to replace the current editor by then.

**Comment by ameeker** [comment]
Also, (this is my opinion, not the meetups'), the more I think about it, the less I like shoving all of the functionality available to a post/page into that Insert drop down. It reminds me of how Menus behave in the current Customizer, which is to say I don't like it.

**Comment by karmatosed** [comment]
For now, going to close this up as we've had a lot of feedback and iterations on things. If there is an exact issue we can create, lets do that in a new issue. Thanks for the feedback.
