### ISSUE TITLE
In the block inserter, hint that there are more blocks below 'Most Used'

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#17872]
**Describe the bug**
When opening the block inserter, it is not obvious that there are more blocks below 'Most Used' and that I have to scroll.

<img width="715" alt="Screen Shot 2019-10-09 at 4 34 48 PM" src="https://user-images.githubusercontent.com/3276087/66523022-7f2a4400-eab4-11e9-940c-f22a183959b2.png">
<img width="462" alt="Screen Shot 2019-10-09 at 4 44 59 PM" src="https://user-images.githubusercontent.com/3276087/66523026-83eef800-eab4-11e9-8016-c1d31a12c8e3.png">

**Proposed solution**
It'd be more obvious and useful if we hinted that there's more content. I don't think we need an arrow or label to explain this. I think that if we only show a hint of what's below, the interaction should be obvious.

I just reduced the padding and margin for the purpose of this example, but I assume we can also explore other alternatives to achieve this:

<img width="721" alt="Screen Shot 2019-10-09 at 4 36 26 PM" src="https://user-images.githubusercontent.com/3276087/66523054-979a5e80-eab4-11e9-8797-6f32af747de5.png">

**Comment by karmatosed** [comment]
I love the idea of hinting but I think we can do it without adjusting the visual order around spacing in the block library. We could, for example, grow the library by a few px, or have animation. It would be great to explore what is a good 'hey there is more' way here. Do any other apps have one we can learn from?

**Comment by enriquesanchez** [comment]
>We could, for example, grow the library by a few px

I think this would be the simplest approach. That being said, I'm not familiar with why or how we landed on the current height for the inserter popover, so I'd be cautious until someone with more knowledge chimes in. Maybe @mapk? 

>Do any other apps have one we can learn from?

I think we can gather a lot of inspiration from mobile UI. IMHO they do a really good job of communicating availability of additional content on tight spaces.

<img width="814" alt="Screen Shot 2019-10-10 at 11 54 43 AM" src="https://user-images.githubusercontent.com/3276087/66589766-db44a500-eb54-11e9-85ab-83feef3a53bc.png">

**Comment by enriquesanchez** [comment]
While looking at something else in https://wordpress.org/gutenberg/, I noticed that the inserter used there already does this:

<img width="726" alt="Screen Shot 2019-10-10 at 12 36 39 PM" src="https://user-images.githubusercontent.com/3276087/66592499-c408b600-eb5a-11e9-9422-0dfe2c428128.png">

It seems there are different margin/padding settings:

<img width="1485" alt="Screen Shot 2019-10-10 at 12 40 58 PM" src="https://user-images.githubusercontent.com/3276087/66592750-472a0c00-eb5b-11e9-95d3-d2eb4b71f8d0.png">

**Comment by enriquesanchez** [comment]
Upon further inspecting, it seems that the difference is that the buttons (both the panel toggle and the list items) in the demo page have a `line-height: 1;`, where the buttons on trunk have different values. Setting them to `line-height: 1;` gets us similar results:

<img width="729" alt="Screen Shot 2019-10-10 at 1 30 34 PM" src="https://user-images.githubusercontent.com/3276087/66596567-c242f080-eb62-11e9-846d-8b0563cbc6e4.png">

Still not ideal though, since 'Common Blocks' is cut off in half and looks more like a quirk instead of something intentional.

**Comment by karmatosed** [comment]
> That being said, I'm not familiar with why or how we landed on the current height for the inserter popover

I can let you know there :) There is no reason it can't grow it was just set that way in first designs. I would be cautious about it growing too much but it absolutely can be explored.

**Comment by enriquesanchez** [comment]
Closing in favor of #19836
