### ISSUE TITLE
Repurpose 'Hello World' post to also serve as a Gutenberg tutorial

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#17874]
On new WordPress installs, users get a 'Hello World' post by default. The post's content is minimal and does not do a great job of explaining users what to do next.

![Screen Shot 2019-10-09 at 4 01 1](https://user-images.githubusercontent.com/3276087/66525471-32963700-eabb-11e9-9255-372e30775d42.png)

I'm wondering if we can instead make better use of the 'Hello World' post and maybe have some pre-loaded content that can help new users learn the basics of the Block Editor and maybe serve as a little showcase of the cool things you can do.

## The new 'Welcome to WordPress" demo post

![Frame 1](https://user-images.githubusercontent.com/3276087/66525578-7d17b380-eabb-11e9-8875-eb42dfe48bc7.png)

☝️ The above is a quick example that hopefully can serve as starter to iterate to something better. 

Because the guide is _in the block editor_, the idea is that the guide itself shows what users can do by using different types of blocks and features. For example, the guide can make use of column blocks, video, group, etc. We can use it as a nice showcase of what can be done with Gutenberg.

We can also probably use better images or even fancy illustrations, to make it more interesting and engaging. 

In the example above, which again is just a quick attempt, the guide starts by showing users how to add a block using the Block Inserter in the top toolbar. That right there communicates to the new user that the plus sign icon adds blocks and when/if they find it somewhere else in the interface, they will already know what it does. It also discretely shows that there's more options in the toolbar that the user can then explore.

The guide then moves on to explain that there are different types of blocks and that they can be customized by using the options in the Block Toolbar. 

And finally, the guide explains that there's a sidebar with additional settings for the document and the blocks.

Again, this could be improved in so many different ways: 
- we can iterate on the contents and topics of the guide,
- we can use better images or illustrations,
- we can be more clever and use different blocks and make the guide more interesting

I'd love to hear your thoughts on this.

**Comment by enriquesanchez** [comment]
Thanks for the feedback @karmatosed! 

>One thing I wonder is the amount of text. For example, are you suggesting we translate this? I feel that a lot of text like this will be quite a bit for many to follow. How could we perhaps take this idea and make it more inclusive to everyone?

I totally agree. There should definitively be a balance. A big block (no pun intended) of text would not be inviting. I think we should make use of as many elements and formats as possible to make this more engaging and educational.

I can see us using video, illustrations, guided steps (like "Add your first block") and even linking to external resources and examples.

The guide could also be formatted in a way that can be consumed in parts, so folks can come back to it and continue where they left if they want.

**Comment by karmatosed** [comment]
What would the most minimal amount of information we could get across for the most impact? I know you are mentioning a few things like video, illustration, guided steps. What do you think the minimum could be? What other examples are there out there to explore too? I know it's a common ask but I do think on things like this we can learn.

**Comment by enriquesanchez** [comment]
[Discussed at today's design meeting on Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1571251034235000) (a [login is required](https://make.wordpress.org/chat/) for access).

I'll attempt to add the general feedback from different folks:

- We need to be cautious and avoid this becoming a manual.
- Explore merging with demo page
- How would this complement Tips?
- Explore renaming from 'Hello World'  to something more obvious and engaging, so users don't ignore it. (Introduction, Tips, Guide, etc.)
- This might be useful to see how well themes supports the Block Editor.

**Comment by enriquesanchez** [comment]
For inspiration, I'm starting to look at how other products/services do welcome guides/tutorials. 

Here's [Trello's 'Welcome Board'](https://trello.com/b/bKbdmCKB/welcome-board) that every new users gets by default on their account:

![Screen Shot 2019-10-17 at 16 19 56-fullpage](https://user-images.githubusercontent.com/3276087/67048766-6a742e80-f0fa-11e9-8a35-8831ac4ac974.png)

I like how the board is divided into 3 lists (Basics, Intermediate and Advanced), which by itself teaches the new user about lists and how to use them.

It's nice that the amount of cards on each list is relatively short, so it should be hard for most folks to feel overwhelmed.

The cards themselves are used both as step by step actions and as examples/demos of the available features (click on a card to see what's behind, drag this card anywhere, etc.).

![Screenshot_2019-10-17  or checklists on Welcome Board Trello](https://user-images.githubusercontent.com/3276087/67049465-ed49b900-f0fb-11e9-83d0-6cce2d1ab3f0.png)
![Screenshot_2019-10-17 Finished with a card Archive it on Welcome Board Trello](https://user-images.githubusercontent.com/3276087/67049487-f9357b00-f0fb-11e9-84d3-d81bfc6a315b.png)


Instead of getting complicated or long, the 'Advanced' list points the user to external resources such as Help docs, longer online guide, API info, etc. where if interested, the user can then dive deeper and learn more.

**Comment by enriquesanchez** [comment]
[Notion](www.notion.so) also has an onboarding guide that is presented to new users as soon as they finish creating their account:

![Screenshot_2019-10-21 Notion – The all-in-one workspace for your notes, tasks, wikis, and databases ](https://user-images.githubusercontent.com/3276087/67245965-df10db00-f422-11e9-974d-c938a3a6ec9b.png)

Similar to Trello, the UI elements are used to format the tutorial and guide the users on a step-by-step basis:

<img width="507" alt="Screen Shot 2019-10-21 at 5 01 46 PM" src="https://user-images.githubusercontent.com/3276087/67246634-965a2180-f424-11e9-9fa4-9498f723e862.png">


The workspace is also preloaded with some sample templates that include some guidance on how to use them:

![Screenshot_2019-10-21 Notion – The all-in-one workspace for your notes, tasks, wikis, and databases ](https://user-images.githubusercontent.com/3276087/67246040-04054e00-f423-11e9-8476-7fb726174d0d.jpg)

![Screenshot_2019-10-21 Notion – The all-in-one workspace for your notes, tasks, wikis, and databases (1)](https://user-images.githubusercontent.com/3276087/67246048-09fb2f00-f423-11e9-9936-1fc4726b2420.png)

**Comment by enriquesanchez** [comment]
Here's another screen grab from Notion. While this is one of their help articles and not a welcome guide, I think they're making great use of images while keeping text to a minimum:

![screencapture-notion-so-Start-here-6c279d3e7e92400d93672bbdd7da1f8a-2019-10-18-12_12_27](https://user-images.githubusercontent.com/3276087/67590500-d5d48680-f720-11e9-8df6-33a430bea0e8.png)

**Comment by enriquesanchez** [comment]
This issue has been migrated to Trac: https://core.trac.wordpress.org/ticket/48758
