### ISSUE TITLE
Block Validation fails on refresh or edit when using the data store

### ISSUE THREAD

**Issue by mieradi** [WordPress/gutenberg#17885]
Hey all,

The block I am currently authoring is using content from wp.data. When I edit and save, it renders to the front end without an issue. 

However, If I go back to edit the page with the block on it I get a validation error because the content is not yet loaded. So, it validates the loading state against the body content.

A couple questions: 

**Is there any async methods for the save function that I am missing?** 

**Is there anyway to use the data store in a static block, or do I strictly need to use a dynamic block and template with PHP?** 

Thanks!

**Comment by swissspidy** [comment]
Yeah you'd need to render the block with PHP in that case.
