### ISSUE TITLE
Can no longer paste images after update to 5.2.3

### ISSUE THREAD

**Issue by TeamKinetic** [WordPress/gutenberg#17881]
**Describe the bug**
Previously I could paste an image from the clipboard and I would see a preview and then it would upload to the gallery and insert it into the document with an image block.

**To reproduce**
1. Go to Posts > Add New
2. Copy an image to the clipboard (not from a website which inserts the images URL and works) from the snip tool or use CTRL Print Screen
3. There is a brief screen jump but no image is pasted.

**Expected behavior**
The image preview should appear and then the image should be uploaded

**Screenshots**
Added the javascript error window
![image](https://user-images.githubusercontent.com/17031269/66556866-e1cd1f80-eb48-11e9-93de-9510d44dfdcc.png)

**Desktop (please complete the following information):**
windows 10
wordpress 5.2.3

**Additional context**
Yesterday I could just paste images from the clipboard and it would appear
We use Jetpack

I cant figure out a way to rollback the update either, I have replaced the folder with a backup and the database table but the changes to Guttenberg are still there and the problem persists.

**Comment by mcsf** [comment]
Hi, could you provide some extra details? Namely:

- Browser version
- The output in the browser console after attempting to paste
- Can you also confirm that you don't have the Gutenberg plugin installed (i.e. that you are solely relying on the block editor as shipped in WordPress 5.2.3)?

**Comment by TeamKinetic** [comment]
I'm sorry I forgot this report!

If you add a PARAGRAPH block you can paste an image directly into that block and it uploads and becomes an image block. If however you are using the 'classic paragraph' block you cant paste an image into it.

Thanks

**Comment by youknowriad** [comment]
Hi There!

I think that's the expected behavior as the classic block is meant to mirror the old editor where you have everything inside one giant editable area while the blocks paradigm is more about having granular blocks with custom customization options.

Thanks
