### ISSUE TITLE
Flickr URL Incorrectly Embedded

### ISSUE THREAD

**Issue by shahzisme** [WordPress/gutenberg#17898]
**Describe the bug**
I am using Wordpress v5.2.3 (I'm not sure where to check the Gutenberg version, but it's the one that was packaged with it)

When I insert the flickr URL, it automatically converts the character to lowercase on the front-end.

I tested with the following URL:

https://www.flickr.com/photos/148984684@N03/albums/72157711285349221

![image](https://user-images.githubusercontent.com/1318063/66639323-39eb4b00-ec49-11e9-995b-9fd9f759a8ff.png)

But on the front end, it shows as follows:

![image](https://user-images.githubusercontent.com/1318063/66639507-86368b00-ec49-11e9-9792-2b525604b4f8.png)

As you can see, the URL has been changed to lowercase:

https://www.flickr.com/photos/148984684@n03/albums/72157711285349221

This causes the end URL to be 404 on Flickr.

Weirdly, the primary image actually loads fine.

**To reproduce**
1. Add Flickr Box
2. Insert the Embed URL (You would need a capital letter in the URL, feel free to use mine above)
3. Preview

**Expected behavior**
A proper URL would be embedded and lead to the album page.

**Screenshots**
Added in the description above for better explanation.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (Build 1809)
 - Browser: Chrome
 - Version 77

**Comment by Pixelrobin** [comment]
I would be down to look into this one if no has yet.

**Comment by skorasaurus** [comment]
This appears to have been fixed sometime since the issue was made.
I am not able to reproduce this on Gutenberg 9.1.

**Comment by annezazu** [comment]
Closing this out due to inability to replicate at this time. Feel free to re-open if you can replicate with the latest version of Gutenberg (9.3).
