### ISSUE TITLE
block_editor_settings filter

### ISSUE THREAD

**Issue by michaelbourne** [WordPress/gutenberg#17892]
Hey everyone, I'm trying to disable the code editor mode in Gutneberg. Based on old issues here and some PRs, I figured this code would work:

```php
function prefix_custom_editor_settings( $settings, $post ) {

	$settings['richEditingEnabled'] = true;
	$settings['codeEditingEnabled'] = false;
	$settings['titlePlaceholder'] = 'Write a captivating title!';

    return $settings;
}
add_filter( 'block_editor_settings', 'prefix_custom_editor_settings', 10, 2 );
```

The **titlePlaceholder** was added as a test and it worked perfectly. Problem is, the code editor is still available.

Any tips?

**Comment by swissspidy** [comment]
Hi there and thanks for your report!

Which version of WordPress and Gutenberg are you using?

**Comment by michaelbourne** [comment]
Hey @swissspidy 

This is a default installation of WP 5.2.4 and its bundled Gutenberg version.

It might be good to note that the above code snippet works as intended in 5.3-RC1-46558 (Bleeding Edge update via Beta tester plugin), so this issue may be moot, however I was unable to locate a specific PR that fixed it.

**Comment by swissspidy** [comment]
This feature was introduced in #14932, which I don‘t think is in 5.2. Therefore closing as it‘s working in 5.3 / current GB.
