### ISSUE TITLE
Add Block: Categories

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1790]
## Attributes

- None, Left, Right, Center, Full Width
- Display as dropdown
- Show post counts
- Show hierarchy

## States

Selected:

![categories](https://user-images.githubusercontent.com/2846578/27979953-d45b650e-6347-11e7-8786-9788412df4e0.png)

Neutral:

![category block](https://user-images.githubusercontent.com/2846578/27979955-d7df8638-6347-11e7-81a3-2f609eb6cf7f.png)

**Comment by westonruter** [comment]
Should the counts also be linked? A least, should they be styled as links? I'm not seeing that for the tag cloud widget: https://core.trac.wordpress.org/ticket/35566

**Comment by melchoyce** [comment]
That came up in the Archive widget conversation without a conclusion: https://github.com/WordPress/gutenberg/issues/1464#issuecomment-311378205

**Comment by melchoyce** [comment]
Looks like the post count isn't linked in the existing Category widget, so let's go ahead and say no, the post count shouldn't be a link on any of the widget blocks.

**Comment by melchoyce** [comment]
Updated the mockups to unlink the post counts.

**Comment by tyxla** [comment]
I've started working on this one in #2102, it will be ready for review soon.

**Comment by tyxla** [comment]
#2102 is ready for a review, thanks everyone!
