### ISSUE TITLE
Undo after automatic change causes block to loose focus

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#17912]
This is somewhat extension to #12002. If this is about to be added to #12327 then IMHO must be added with good description as this seems to be a quite different thing than all the scenarios given in #12327.

**Describe the bug**
When user undoes an automatic change (i.e. changing block type into list after writing `1.`)  within the same block, this block itself looses focus. This does not happen during regular writing, i.e. after non-automated change.

**To reproduce**
1. Start a new block.
2. Type `1.` and hit <kbd>Space</kbd>.
3. Observe automatic change of block's type from paragraph to numbered list.
4. hit <kbd>Ctrl</kbd>+<kbd>z</kbd> or click appropriate button in toolbar to undo this automatic change.
5. Observe that focus is lost / shifted from active block.

Repeat above steps writing anything that does not trigger an automatic change and observe that you can undo as much operations as you need without loosing focus from current block.

**Expected behavior**
Undo behavior should be consistent. No undo operation should cause a block to loose focus.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 77
 - Gutenberg: 6.6.0

**Comment by ellatrix** [comment]
Thanks for the report! We're aware of this issue. It should be fixed by #17824. Would you be able to test it?

**Comment by trejder** [comment]
Of course. Just let me know, if I should test unstable nightly or wait for the stable production version?

BTW: Loosing focus on undo is a small thing. Great that you've fixed it, but that could wait. The #16172 is by far more important, because it is open 4+ months and drives million of people crazy.

**Comment by mrfatguy** [comment]
Closing as https://github.com/WordPress/gutenberg/pull/17824 is closed and merged.
