### ISSUE TITLE
Cover Block minimum height does not reflect content height

### ISSUE THREAD

**Issue by timhibberd** [WordPress/gutenberg#17919]
**Describe the bug**
The Cover Block minimum height does not reflect the actual height of the cover block.

**To reproduce**
1) Create a Cover Block with a 3 column Columns block with an image per block
2) Using the mouse, shrink the height of the Cover block to less than the content height
3) Release the mouse button used to shrink the Cover Block window (the Cover Block window will snap back to the height of its content).

**Expected behavior**
The Minimum Height admin box should reflect the actual Cover Block height but it gets stuck on the smallest vertical height  of the window shrink process in step2 above. See screenshot below.

NOTE: If you click the mouse on the bottom of the Cover Block window the Minimum Height admin box adjusts to the correct value.

**Screenshots**
![CoverMinimumHeightBug](https://user-images.githubusercontent.com/18463324/66698904-da1aa000-ed2d-11e9-8509-2d2194c41376.gif)

**Desktop (please complete the following information):**
    OS: Windows10
    Browser Firefox
    Version 69.0.3

**Additional context**
- Not using the GB plug-in. Using WP 5.3-beta3-46461
- Latest Twenty-Nineteen theme

**Comment by paaljoachim** [comment]
Hey @timhibberd Tim

I just tested this and noticed that there is a minimum height even though I add a very small Minimum height of cover. As it can say 15 px but looking at the layout it is bigger. I am though not able to drag it smaller hiding the column images.

Conclusion based on your gif I see that this has changed.

I will go ahead and close the issue. Please reopen if I am mistaken.
