### ISSUE TITLE
Animate placeholder text color

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#1791]
I found this subtle animation in another online writing tool a nice addition and it would be easy to add:

![lwhzzm2aad](https://user-images.githubusercontent.com/2160304/27972104-f3bf952a-6309-11e7-9c19-6dbfb1e38bcd.gif)

**Comment by jwold** [comment]
Is the purpose here to show to me that the text can be changed? If so I think this could be a nice touch. Might be nice to have the cursor auto change to text cursor?

**Comment by georgeolaru** [comment]
It might be a good idea but I think could be confusing too. If the default placeholder color is the same (or even similar) with the input text, then it will blend with other filled text blocks.

The current placeholder UI that uses opacity: 50%, seems pretty intuitive now.  If you remove that and make it respond only on hover, it could be difficult to identify the actual text from placeholders:
![screen shot 2017-07-05 at 10 28 05](https://cl.ly/3P1E3t3a0x1V/Screen%20Recording%202017-07-08%20at%2011.19%20AM.gif)

**Comment by karmatosed** [comment]
I would second this seems to confuse, over add any actual enhancement. For now, lets leave as is. We are having some animations worked on, so let's focus on those which animate the blocks.
