### ISSUE TITLE
Change post content with javascript while create/edit

### ISSUE THREAD

**Issue by brunokaue** [WordPress/gutenberg#17923]
I have a problem to change content post, when I'm make or edit in wordpress.
I made a plugin to load names from an API and put it in a select box, this is working.
The problem is the operation, when I select the name and click the button, is to change the name for a link, this is done, but when saving, it does not save with the link.
Has anyone faced this problem?
Below I am sending you a link to see what happens.

https://vimeo.com/user103875507/review/365996569/adf65e3a0b

**Comment by swissspidy** [comment]
Hi @brunokaue, your link is not working unfortunately. Also, in such cases it is extremely helpful to share any code so people can better assist you.

That being said, for general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.
