### ISSUE TITLE
Pasting content while blocks are selected should overwrite selected blocks

### ISSUE THREAD

**Issue by eberhardweber** [WordPress/gutenberg#17931]
**Description**
Pasting content while blocks are selected should overwrite the selected blocks. Right now, copying on selected blocks just copies the pasted content under the selected blocks.

**To reproduce**
Select blocks in the Gutenberg post editor, paste content

**Expected behavior**
Pasted content should overwrite the selected content.

I believe this feature is essential and goes together with the block-style editing that Gutenberg offers. Overwriting is also key feature of copypasting and would have been possible in the Classic Editor.

**Comment by swissspidy** [comment]
> Right now, copying on selected blocks just copies the pasted content under the selected blocks.

Just noticed that it can even duplicate content when blocks are multi-selected.

**Demo video:** https://cloudup.com/c9XIn8FoZra
