### ISSUE TITLE
Create Table button vertical alignment is off

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#17947]
**Describe the bug**
When User add the table block, Button label text should be in center align.

Verison : 
WordPress Beta 5.3

**To reproduce**
Steps to reproduce the behaviour:
1. Go to '.page'
2. Add a new Page.
3. Click on 'Block option'
4. Add Table block.
4. See the Button label.

**Expected behaviour**
Button label text should be in center align.

**Screenshots**

![image](https://user-images.githubusercontent.com/51028940/66817093-ca32d400-ef58-11e9-874b-5fb8423c6fa8.png)

**Comment by brezocordero** [comment]
Tested it with Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Gutenberg 6.8.0

Couldn't reproduce the issue. Table button vertical alignment is correct.

![TableButton](https://user-images.githubusercontent.com/8002881/68091096-1a5ad300-fe41-11e9-953d-7225980025b9.png)

**Comment by Dabalina** [comment]
Tested on Firefox 70 on Windows 10, Gutenberg 6.8.0 and the vertical alignment is a bit off.

<img width="669" alt="Screen Shot 2019-11-03 at 1 53 25 PM" src="https://user-images.githubusercontent.com/4277676/68091176-1c716180-fe42-11e9-90dd-65b97a7995b1.png">

**Comment by karmatosed** [comment]
I think this is resolved now as shown in this image on Firefox:

![image](https://user-images.githubusercontent.com/253067/69993711-481c6000-1544-11ea-8606-3593ad17045e.png)

If it still is an issue please comment and it can be looked at.
