### ISSUE TITLE
Consider adding option to add custom keyboard shortcut on "Keyboard Shortcuts" modal.

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#17944]
**Is your feature request related to a problem? Please describe.**
Consider adding filter for custom keyboard shortcut item on "Keyboard Shortcuts". I've recently created a shortcut and there's no easy way to add it on the list.

**Describe the solution you'd like**
Custom filter would be really nice.

**Comment by swissspidy** [comment]
Thanks for your report.

We're already tracking this in #3218 and #15205.
