### ISSUE TITLE
Image Block : Error getting displayed When user add the image block and upload the image.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#17948]
**Describe the bug**
Image Block: Error getting displayed When user add the image block and upload the image.

Version : 

5.3 Beta

**To reproduce**
1. Go to 'Add Block'
2. Click on 'Image Block'
3. Upload image.'
4. See the error.

**Expected behavior**
The image should able to upload.

**Screenshots**

![image](https://user-images.githubusercontent.com/51028940/66817458-55ac6500-ef59-11e9-82a9-461c22557601.png)

**Comment by swissspidy** [comment]
Does this still happen when you disable all plugins and use one of the default themes?

**Comment by nayana96249** [comment]
Hello @swissspidy 

Yes, Still it is happening when we upload the images as well preview the page. Same error getting displayed. 

Also, I have deactivated all the plugins and fresh installed beta version 5.3. While Preview the page, error displaying  "Updating failed. Error message: The response is not a valid JSON response."

Thanks

**Comment by TrueSoft** [comment]
I've had a similar error like yours.

I think the problem was with the permalink settings. (Mine was set to `/%postname%`) I just changed to something else, saved, then changed back, saved, and the error was gone.

**Comment by diquispe** [comment]
> I've had a similar error like yours.
> 
> I think the problem was with the permalink settings. (Mine was set to `/%postname%`) I just changed to something else, saved, then changed back, saved, and the error was gone.

I tried your solution, with  unsuccessful results

**Comment by ChrissiePollock** [comment]
I was not able to replicate on WordPress 5.3 using Firefox 70.0.1 (64-bit)

**Comment by ellatrix** [comment]
The error you see might be a result of having no connection to the server.

**Comment by annezazu** [comment]
Closing this out due to lack of activity and inability to replicate. You're welcome to re-open this if this continues to be a problem!
