### ISSUE TITLE
Regression: placeholder remains visible after typing

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#1795]
Commit causing the regression: fa810e26c56a0aba809d8a5038608cfd2d053b5c.

To reproduce, open the demo content, insert a text block, and start typing. If you remove the table from the demo content, everything works fine.

cc @jasmussen @EphoxJames

**Comment by nylen** [comment]
It wouldn't surprise me if this was an issue with the `core/table2` block all along, but renaming `core/table2` to `core/table` caused the issue to become apparent in the demo content because it contains this type of block.

**Comment by mtias** [comment]
This was introduced with the `table` plugin. The condition in which we check for `state.empty` in Editable never fires because of:

```js
      editor.on('SelectionChange', function (e) {
        if (hasCellSelection) {
          e.stopImmediatePropagation();
        }
      }, true);
```

Which comes from the tinymce table plugin.

**Comment by iseulde** [comment]
Not sure if I like the solution in the PR... Shouldn't this be fixed in the table plugin? There's clearly something going wrong in there. The active editor is not the table, yet `hasCellSelection` is true. And why `stopImmediatePropagation`? cc @spocke

**Comment by iseulde** [comment]
Maybe revert the commit for now until this works?

**Comment by mtias** [comment]
@iseulde which commit in particular?

**Comment by iseulde** [comment]
Retiring old table. Keep two for now until the new one works properly.

**Comment by nylen** [comment]
> Not sure if I like the solution in the PR... Shouldn't this be fixed in the table plugin?

Agreed.  I don't necessarily think we should merge #1798 but it shows what the problem is and what needs to be done to fix it.
