### ISSUE TITLE
Image Block and improving sizes="..." and srcset="..."

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#17959]
I'm not sharing this here to be a self-promoting jerk. I'm doing so because it's more likely to be seen by the people most interested in such things. Hopefully, someone who matters will have a look and consider how this might be incorporated into core. Images. I hear the internet likes them :)

Long to short, plain vanilla WP doesn't give any consideration to the image block settings (aka attributes) when adding the sizes="..." and srcset="...". At the extreme, an Image Size full in an align center block is likely going to yield a sub-optimal sizes value. That is, sizes should be limited to content_width (as that's as wide as the block with that setting is gonna go). 

This is my (first) attempt to correcting such things:

https://gitlab.com/WPezPlugins/wpez-guten-better-image

**Comment by swissspidy** [comment]
Thanks for sharing this! It certainly is appreciated and great to see such contributions from the community.

However, GitHub issues are really not meant for promoting other plugins. This is better suited for a blog post or perhaps Twitter.

You are more than welcome though to create an actual issue to discuss improvements to media handling. That should probably happen on Trac though, as it's not limited to Gutenberg.

**Comment by AlchemyUnited** [comment]
@swissspidy - Fair enough.  Please let me know how else do you want me to show you that how WP (in the Gutenberg era) - does sizes and srcset is - and I'm being kind - sloppy? I'm not promoting a plugin. There's nothing in it for me.  I'm showing you definitively YOU have a problem and there's a way to fix it. This isn't about me or a plugin. It's about you and the product you ship. You're welcome? 

I'd open a bug report but those are consistently met with whining and side-stepping. 

Gawd this is tiring. 

p.s. I'm not sure who shipped the cover block but that might be the more negligent / irresponsible chunk of code I've ever seen.  A full-size background image? Really? SMH.

**Comment by AlchemyUnited** [comment]
@swissspidy "You are more than welcome though to create an actual issue to discuss improvements to media handling. That should probably happen on Trac though, as it's not limited to Gutenberg."

Hoops. Hoops. And more hoops. My gawd, is this a software product or lessons in bureaucracy? 

Please keep in mind: "The Experience is The Product." Why is it, every time I engage with your product I regret it? And, FYI, I'm not alone. 

Have a nice day. This is the last time I'm going to experience shame on me at the hands of hacks.

**Comment by jcklpe** [comment]
This issue was not handled very well @swissspidy   It's pretty clear from OP's post that they aren't trying to promote a plugin but that they are suggesting an improvement to WP core and simply don't know how to best go about contributing that change. Considering the size of the WP codebase I think that's probably pretty reasonable confusion to have.

**Comment by swissspidy** [comment]
My apologies for not interpreting the intent correctly. I clearly should have worded this better and added some more context / explanation.

I do think that we've got quite a few issues about media handling already as there are known fundamental problems. See #6177 and #11822 for example. They (and the issues they reference) cover these aspects of media handling / image sizes in WordPress and Gutenberg specifically.
