### ISSUE TITLE
Cover Block Returns error when Focal point is changed

### ISSUE THREAD

**Issue by rossanafmenezes** [WordPress/gutenberg#17952]
When using the cover block it returns an error 'block contains
unexpected or invalid content' error after moving the focal point picker. If you perform any other
block functions (moving the pic to one side or the other, adding text, changing
the background color, etc.) it does not generate an error.
When you choose 'attempt block recovery' the block seems to recover successfully.
However when you reload or return to the page, the error recurs.

**To reproduce**

1. Create a post or a page on a simple site
2. Add a cover block
3. Move the focal point from the settings column
4. update the post and reload the page

**Expected behavior**

The error should not occur

**Screenshots**

![](https://cldup.com/0hZviN527S.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Google Chrome OS Version 77.0.3865.105 (Official Build) (64-bit) 
 - Browser Chrome 77 on ChromeOS and Firefox 60 on Linux

**Additional context**

This seems to happen only on simple sites. Tried with AT sites and the block did not return the error. 

The user is using Radcliffe2 and I was able to reproduce the error, however I have also tried with DARA and Mayland themes and got the same error on all of them. 

ZD-2422005

The same issue is happening with the Text & Media block 

![](https://cldup.com/1Y2huIUIdi.png)

**Comment by glendaviesnz** [comment]
The CoBlocks Hero block has the same issue when setting focal point on wpcom - https://github.com/Automattic/wp-calypso/issues/36586#issuecomment-542496154, with any lucj the two will be related so we can kill two birds with one stone :-)

**Comment by glendaviesnz** [comment]
The following is the console error when loading a saved cover block on a simple site in Calypso:

```
 Block validation: Block validation failed for `core/cover` 

Content generated by `save` function:

<div class="wp-block-cover-image has-background-dim wp-block-cover" style="background-image:url(https://.../leaves.jpg)"></div>

Content retrieved from post body:

<div class="wp-block-cover has-background-dim" style="background-image:url('https://.../leaves.jpg');background-position:6.4516129032258% 7.6388888888889%;"><div class="wp-block-cover__inner-container"></div></div>

```

**Comment by brezocordero** [comment]
I could not reproduce the issue with the Cover block. 
Gutenberg 6.8.0
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

This seems to happen only on WordPress.com simple sites.

**Comment by ellatrix** [comment]
I cannot reproduce either with Gutenberg 6.9.0. Could you report the bug with https://github.com/Automattic/wp-calypso?
