### ISSUE TITLE
Change Authors on individual posts

### ISSUE THREAD

**Issue by SheElf** [WordPress/gutenberg#17954]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

**Comment by SheElf** [comment]
Hi, I'm unable to discern how to change the author on an individual post in Gutenberg. I thought it was on the sidebar under Publish, but I cannot find it. Will this option be returned? In the meantime, how do I change the author for some of my posts? Thank you.

**Comment by swissspidy** [comment]
Hi there,

For general help requests, please post in the support forum at wordpress.org/support/forum/how-to-and-troubleshooting.

To answer your question, the author can be changed in the publish panel:
![Screenshot 2019-10-15 at 14 36 04](https://user-images.githubusercontent.com/841956/66831992-36add300-ef59-11e9-8a3b-2a5b17c88390.png)

The option only shows when there is more than 1 user with publishing capabilities, e.g. 2 editors. You cannot assign subscribers as authors.

**Comment by SheElf** [comment]
I don't know where the publish panel is. I'm the only user on my blog and I
have writers who contribute articles. Is it still possible to change the
author?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/15/19,
06:40:32 AM
