### ISSUE TITLE
Cover block set default paragraph color

### ISSUE THREAD

**Issue by thune** [WordPress/gutenberg#17953]
If I have a light background color in the cover block, the default paragraph text becomes invisible. I can change the paragraph block color, but when clicking enter to create a new paragraph inside the cover block the text is yet again white and invisible against a light background. It's annoying that the cover block is just made for dark backgrounds.

**Comment by ninetyninew** [comment]
We have the same issue - let's say you create a full width cover block for the top of the page, use a background image on it with no opacity then inside you want to add a 2 columns, the first with a white cover block inside to create a white box 30% of the cover, when you add a heading or paragraph the default text color is inherited in the CSS and therefore makes the text you are typing white and invisible, it was really hard to determine what was happening, if I apply a dark text color it's visible again but it would be really difficult to spot this has occurred to do that. @thune @swissspidy

**Comment by akasunil** [comment]
With text color option, we can make all inner block placeholder and text visible according to background of cover block.
that being said, we can close this issue now. 
Cc: @annezazu 

![CleanShot 2024-03-14 at 14 28 24@2x](https://github.com/WordPress/gutenberg/assets/61308756/2a76c0c7-60b2-475c-8161-03bb061412df)

**Comment by annezazu** [comment]
Thanks for following up. Closing this out.
