### ISSUE TITLE
json 403 error only when cover block is in use

### ISSUE THREAD

**Issue by amandablum** [WordPress/gutenberg#17965]
I've read everything out there on the JSON errors updating pages, and no solution out there has worked.  Its wacky. No user permission mods. Using current Gutenberg plugin. Dumped htaccess and regenerated via permalinks. Cloudflare and all caching off. Default theme, no plugin but Gutenberg, problem still persists. 

1. if there is a cover block on a post or page, some people won't be able to update it. they'll get a json error. 
2. there is no difference in user permissions for who can update and who can't. those who can't, can't on any computer or browser, and the same for those who can. Doesn't matter if they're logged in as me or them. 
3. Those who can update can do so from any computer and browser, regardless of whether they're logged in as me or people who can't update elsewhere. 
4. This ONLY happens on pages/posts with a cover block. Remove the block, you can update. Doesn't matter what image is in the block. 

Just looking for any idea of where to go with this. 

![image002](https://user-images.githubusercontent.com/2366499/66882887-e3e81180-ef80-11e9-8f8a-28976a00d577.png)

**Comment by amandablum** [comment]
is it possible that someone could relay what is unique about the cover block? it uses JSON in regards to the color overlay, right? Is that the only block that does that? Other blocks utilize JSON, too, right? I can't seem to find another block instance that has the same result for us, but I'd like to test any that use JSON.

**Comment by ehti** [comment]
Hi @amandablum!

We discussed this editor triage today. None of us were able to reproduce it - just checking, are you still running into this issue?

If so, can you also detail what specific user roles are affected at your end, and are you able to reproduce this on a site with no plugins / custom themes?

Thanks!

**Comment by karmatosed** [comment]
I am also unable to replicate this, so for now, let's close this up and we can always reopen if continues as an issue.

**Comment by jomurgel** [comment]
I'm able to replicate this issue with the cover block if the cover block contains a background image. POST success if the cover block does not.

I have found, however, if I create a blank cover block (no image, no setup) and then add another one underneath that with any settings including a background image, WordPress will save just fine.

Making that same curl request replacing `style=\\"background-image:url` with `style=\\"background:url(...` also will avoid the 403 regardless of any of the above.

Hosting is BlueHost.

Still debugging, but this doesn't appear to be server config related but could be the result of some firewall or security parsing.

I do not have this issue outside of BlueHost.

**Comment by shadigaafar** [comment]
I get the same error on custom block....
