### ISSUE TITLE
`value` prop misdocumented in MediaPlaceholder

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#17967]
**Describe the bug**
`value` is documented as ["Media ID (or media IDs if multiple is true) to be selected by default when opening the media library."](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/media-placeholder/README.md#L156-L162). But this is not true since it's actually expecting an object or an array of objects which provide an `id` prop:

https://github.com/WordPress/gutenberg/blob/0ee2b784c10ace28f6c84d079ec601ff80a76199/packages/block-editor/src/components/media-placeholder/index.js#L311-L315

**Expected behavior**
The docs are updated to reflect what type is supported. Maybe even try to support a plain ID or a list of IDs?

**Additional context**
The docs seem to be copied from [MediaUpload](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/media-upload/README.md#L77-L83)

**Comment by mkevins** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/17980. Thanks @ocean90 for reporting, and @phwebi for updating the docs. :tada:
