### ISSUE TITLE
Multiple block inspector missing some spacing

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#17975]
## The issue
The multiple block inspector is missing some spacing, as you can see in this screenshot.
![image](https://user-images.githubusercontent.com/19592990/66930111-bbe8c480-eff9-11e9-9d55-d20dac3d77a0.png)

I suspect this regression was caused by #17880.

## How to reproduce
1. Open the block inspector.
2. Select multiple blocks.

## Testing environment
 First discovered on WordPress 5.3 RC1 with Gutenberg 6.7.0. Still present when using WordPress 5.3 with Gutenberg 6.9.0.

## Side notes
The block and word count seem like something that don't belong in the inspector, but rather in a location such as a status bar (as seen in common code editors e.g. Visual Studio Code). Gutenberg just got a status bar, so perhaps it should be put there.

**Comment by ajotka** [comment]
I was trying to reproduce the bug, but it seems to be working.

My env: 
- WP 5.3
- Chrome

![screenshotAtUploadCC_1574441588060](https://user-images.githubusercontent.com/15144546/69445003-c1040680-0d51-11ea-8b72-3d9faa0d7c14.png)

@ZebulanStanphill @youknowriad 
Could you check again and then write more specific environment?
e.g. browser, browser version, resolution

**Comment by ZebulanStanphill** [comment]
@ajotka I checked, and it looks like this issue is not present in WordPress 5.3 with the Gutenberg plugin disabled, so this issue must be a regression introduced at some point around Gutenberg 6.7.0. The issue is still present in Gutenberg 6.9.0.
