### ISSUE TITLE
WordPress 5.3 Block Editor props

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#17974]
Block editor is hosted in a different repository than the rest of WordPress. To correctly attribute/props credits for Block Editor contributions, we need a mapping of GitHub usernames to WordPress.org usernames.
Recently WordPress.org profiles got a feature that allows connecting with a GitHub, but not everyone is aware of this feature yet. So, the collection of WordPress 5.3 Block Editor props was mostly a manual process (more details https://meta.trac.wordpress.org/ticket/4763).
Even after the manual process, it was impossible to map some GitHub usernames to their WordPress profile.

In this issue, I'm pinging the usernames that we were unable to match.

@AdamDTak2112, @ahamed07sajeeb, @ajlende, @ashwin-pc, @codesue, @fritz-cwp, @Jackie6, @marecar3, @mkevins, @rbrishabh, @sambgordon, @svenvanhal, @them-es, @xel1045, first of all, thank you for your contributions to the block editor that will be part of WordPress 5.3.
As a second point, could you please share your WordPress.org profiles as comments on this issue?

In the future, to make the match automatic, it would be helpful if you could connect your GitHub profile with your wordpress.org account. You can do so by going to https://profiles.wordpress.org/#YOURUSERNAME#/profile/edit/group/1/ there you will find a GitHub username option.

Thank you in advance!

**Comment by them-es** [comment]
Thanks for your efforts on acknowledging all Gutenberg contributors in the upcoming WordPress 5.3 release @jorgefilipecosta

The WordPress.org username for @them-es is **[themes-1](https://profiles.wordpress.org/themes-1/)**

**Comment by ashwin-pc** [comment]
Yeah thanks for taking the effort to acknowledge the contributors @jorgefilipecosta.  My WordPress.Org username is [ashwinpc](https://profiles.wordpress.org/ashwinpc/)

**Comment by ajlende** [comment]
@jorgefilipecosta my WordPress.org username is [ajlende](https://profiles.wordpress.org/ajlende/) and my GitHub should now be linked to that profile.

**Comment by mkevins** [comment]
Hi @jorgefilipecosta :wave: Thanks for the heads up about the feature! I've linked my GitHub profile on WordPress.org. My WordPress.org username is `snapfractalpop`.

**Comment by rbrishabh** [comment]
Thank you! @jorgefilipecosta. My WordPress.Org username is ```[rbrishabh](https://profiles.wordpress.org/rbrishabh/)```

I have also linked my GitHub profile on WordPress.org. 
Thanks again!

**Comment by xel1045** [comment]
My WordPress.org username is [xel1045](https://profiles.wordpress.org/xel1045/) and it's now linked to my Github profile. Thanks!

**Comment by svenvanhal** [comment]
My WordPress.org username is svanhal, thanks!

**Comment by jorgefilipecosta** [comment]
Thank you all 👍 The usernames provided were added to the props spreadsheet available at the meta ticket.
