### ISSUE TITLE
Block Editor: Improve UX for the URL link viewer

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17972]
Follow-up for #17928 where @glendaviesnz fixed the root issue of #17657:
> Block disappear when clicking on a link (anchor, <a>) with no href

> 
> Before:
> 
> <img width="515" alt="before" src="https://user-images.githubusercontent.com/3629020/66729681-75845000-eea9-11e9-88fb-3a0f344b0c99.png">
> 
> After: 
> 
> <img width="456" alt="after" src="https://user-images.githubusercontent.com/3629020/66729678-70bf9c00-eea9-11e9-9803-d632015d1cf6.png">

One option to improve the UX is to:

> I tested it with the Class block and it looks like the way it's handled there is, it gets never converted into a link if you leave the input field empty. In the case where you remove the URL and save it, it works as if you would remove the link. We should replicate the same behavior.

## To reproduce

1. Copy text from a source where there is a tag with no href
or
create a link with no href when editing a block in HTML mode
2. In visual mode, click on the link or drag over it (like when you want to select text containing a anchor with no href).
3. Check how popover behaves.

**Comment by shaunandrews** [comment]
I don't have a big problem with the empty popover, but maybe adding a "(no URL)" label could help:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/191598/70553887-03975280-1b4a-11ea-8adb-8ecf591f1146.png">

**Comment by joyously** [comment]
I don't have a problem with how it works now either, except that there is no part of the UI to make an anchor instead of a link.

**Comment by shaunandrews** [comment]
> there is no part of the UI to make an anchor instead of a link.

You just type the anchor into the input field, like this:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/191598/70554333-eca53000-1b4a-11ea-82ba-76119cdea26d.png">

**Comment by joyously** [comment]
> You just type the anchor into the input field

That makes a link, not an anchor. You don't use a href on an anchor, you use the ID attribute. It's a destination, not a way to get there.

**Comment by shaunandrews** [comment]
Ah, I see what you mean now. I've never used a link as an anchor point — only to link to one. Currently, Gutenberg allows you to add an ID anchor to the Heading block — which is the only way I've ever done it.

**Comment by mapk** [comment]
I just tested this out by creating an empty anchor in the code editor. While we have a new LinkControl component, we just show an icon now with no text. Is this still a problem?

![Screen Shot 2020-04-14 at 9 29 01 AM](https://user-images.githubusercontent.com/617986/79249720-88fd7d00-7e32-11ea-9e1f-19d947455301.png)

**Comment by gziolo** [comment]
> I tested it with the Classic block and it looks like the way it's handled there is, it gets never converted into a link if you leave the input field empty. In the case where you remove the URL and save it, it works as if you would remove the link. We should replicate the same behavior.

I guess the motivation in the Classic editor was to avoid creating an anchor that is invalid because it doesn't have `src` defined. However, you could argue that it might have `id` (`name` in the past) attribute and be valid as well. It's probably up to the accessibility team to advise what's the best way to move forward.

**Comment by mapk** [comment]
@enriquesanchez, can you provide some accessibility feedback on this one?

**Comment by enriquesanchez** [comment]
I think we should communicate that the link contains an empty `href` attribute. 

That can be something like adding the text "This link is empty". We should also remove the visually hidden "(opens in a new tab)" and the SVG icon.

![Frame 5](https://user-images.githubusercontent.com/3276087/80758520-596d9680-8afb-11ea-95b5-49099ef59279.png)

**Comment by joyously** [comment]
To me, "link is empty" means there is no text to click. Perhaps "address is empty" or "no destination"?

What _is_ the procedure for making an anchor (no href)?

**Comment by skorasaurus** [comment]
related: https://github.com/WordPress/gutenberg/issues/26351

**Comment by gziolo** [comment]
@getdave, should we close this issue after all the iterations applied to the URL link tooltip?

**Comment by getdave** [comment]
@gziolo I can see the same issue still occurs, namely that the Link UI doesn't expect this scenario and the UX is non-optimal.

<img width="825" alt="Screen Shot 2021-09-15 at 09 43 06" src="https://user-images.githubusercontent.com/444434/133401156-6fda281f-da91-46a1-88c4-7a9ffbdfbdf2.png">
<img width="524" alt="Screen Shot 2021-09-15 at 09 42 53" src="https://user-images.githubusercontent.com/444434/133401164-b000dfb0-a870-4394-a8d2-2edd8c76e421.png">


Therefore I don't think we should close this one but instead I think we should **re-do the description** to ensure it's up to date with the changes in the codebase. 

@javierarce You and I have worked on the link UI quite a bit. How do you think we should communicate to the user that there is no link or it is invalid? 

@gziolo Would you agree an empty `href` should be considered an "error" state?

**Comment by gziolo** [comment]
> Would you agree an empty href should be considered an "error" state?

I guess it's a correct assumption. We should show some hints to the user so they could fix it.

**Comment by javierarce** [comment]
@getdave I think https://github.com/WordPress/gutenberg/issues/17972#issuecomment-622109556 is still a good solution but we could change the icon:

![image](https://user-images.githubusercontent.com/4933/133473715-920ba38e-d2a8-46e1-836d-e3dfbeab6443.png)

I also notice that it's possible to create empty links by inserting a space in the input field and the control will create an empty link with just the string `http://`.

**Comment by getdave** [comment]
This task is now on my radar to be worked on when I can.
