### ISSUE TITLE
Hover state of "Close" button in Options dialog modal is whacky

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17976]
**Describe the bug**
The hover state of the "Close" `X` button is a bit off due to some of the recent hover state improvements made earlier I believe.

**To reproduce**
1. Open the "Options" dialog modal.
2. Hover cursor over the `X` icon.
3. Observe the outline is a bit off.

**Expected behavior**
I expect this hover state to match those found in the top toolbar.

**Screenshots**

![hover](https://user-images.githubusercontent.com/617986/66937550-7fff3080-eff4-11e9-8e2a-4bf4cd69a702.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 69.0.2
 - Gutenberg 6.7

**Comment by enriquesanchez** [comment]
Currently on `master` and I don't seem to be able to reproduce:

Firefox 69.0.2
<img width="446" alt="Screen Shot 2019-10-16 at 11 24 52 AM" src="https://user-images.githubusercontent.com/3276087/66939947-a8455a00-f009-11e9-91d9-58a469caf575.png">

Chrome 7.0.3865.120
<img width="437" alt="Screen Shot 2019-10-16 at 11 25 18 AM" src="https://user-images.githubusercontent.com/3276087/66939991-bc895700-f009-11e9-95a3-f8ac99aaf088.png">

Safari 12.1.1
<img width="452" alt="Screen Shot 2019-10-16 at 11 25 42 AM" src="https://user-images.githubusercontent.com/3276087/66940022-cc08a000-f009-11e9-8c40-293961e95155.png">

**Comment by enriquesanchez** [comment]
Big thanks to @jasmussen for the troubleshooting help:

>The dialog is vertically centered using translate. Meaning all pixels can land on subpixels if the viewport is an uneven number of pixels tall, which on a 1x screen can result on some 1px strokes blurring away entirely. Way to test is up test on 1x screen and slowly resize the browser vertically, while the button has hover locked in the devtools.

Testing on a 1x monitor, I was able to reproduce at some viewport heights:

![Capture](https://user-images.githubusercontent.com/3276087/66943459-d4b0a480-f010-11e9-9a5f-f75c16d64bfa.PNG)

**Comment by KernelZechs** [comment]
I can confirm this is still happening in Firefox on various operating systems. The issue is that this Modal is using a subpixel transform (as stated above). The solution here is to use flexbox wrapper for centering to prevent subpixel translation errors regardless of DPI of the display or browser rendering style.

### With Translate
![image](https://user-images.githubusercontent.com/46404303/96702258-96566f80-135f-11eb-97c2-c9f0bed545d2.png)

### Without Translate
![image](https://user-images.githubusercontent.com/46404303/96702360-aa01d600-135f-11eb-8c86-d9dc83a8ccd1.png)

**Comment by enriquesanchez** [comment]
I can no longer reproduce this. The modal's header is using `flex` and `align-items: center`.

**Comment by skorasaurus** [comment]
[Following these steps](https://github.com/WordPress/gutenberg/issues/17976#issuecomment-542809033), I'm able to reproduce this in firefox: 

![Selection_032](https://user-images.githubusercontent.com/955351/100626092-5cc83b00-32f3-11eb-8f76-1afd6f50ca5c.jpg)

The left and top of the of that close button ever so slightly has a thicker edge compared to the right and bottom; although it's barely (imho) perceivable.

**Comment by mapk** [comment]
I tested this on a couple different monitors and didn't find any big problems. I'm going to close this for now.
