### ISSUE TITLE
Word Count in the block editor is off 

### ISSUE THREAD

**Issue by boemedia** [WordPress/gutenberg#17988]
The number of words counted in the block editor is not right. 

1. I typed a text in Google Docs of exactly 100 words
2. I copied the text to the block editor
3. I says it's 95 words instead of 100

Obviously, I expect the word count to be correct and the same in different text editors.
I also checked the count online in a word counter and in Microsoft Word, they all register 100 words.

This is the Block editor word count:
![a2d843dc4625bafe0bee4440833159a1 _Image%202019-10-17%20at%209 41 36%20AM](https://user-images.githubusercontent.com/29769622/66988816-6aa50780-f0c3-11e9-826d-dba6e284bd04.png)

This is the Google Doc word count:
![34966716aeef22133ef38615e048c04f _Image%202019-10-17%20at%209 37 24%20AM](https://user-images.githubusercontent.com/29769622/66988659-32052e00-f0c3-11e9-8f95-c0658d729344.png)

**Comment by talldan** [comment]
@boemedia Would you be able to share some example text? I just tested with 100 words, 3 blocks and the editor was correct. It might be that particular characters are being counted incorrectly.

**Comment by boemedia** [comment]
Basically all posts so far on my new blog: https://moniquedubbelman.eu/

**Comment by talldan** [comment]
Thanks for the info. It looks like the block editor isn't counting any of the numbers in the posts as words.

**Comment by tshevchenko271285** [comment]
I created several custom Gutenberg blocks using the Block Lab plugin. Everything works well, but Gutenberg does not take into account the content of these blocks by the number of words. Can I do something extra to make this work for me?

**Comment by DannyCooper** [comment]
@tshevchenko271285 I'm having the same problem, did you find a solution?

**Comment by skorasaurus** [comment]
There's an another issue that has more discussion on this at https://github.com/WordPress/gutenberg/issues/26339 and you can Subscribe to that issue to follow its progress.
