### ISSUE TITLE
Incorrect BaseControl margin

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#17984]
**Describe the bug**

Currently there is CSS applying a `margin-bottom` to every `BaseControl` which follows another `BaseControl` (so effectively the margin is for everything but the first element).

https://github.com/WordPress/gutenberg/blob/master/packages/components/src/base-control/style.scss#L24-L26

This causes inconsistent margins between `BaseControl`s; I believe this is intended to be a `margin-top` instead.

This was observed in WordPress 5.3 RC1, and the problematic CSS is currently in `master`.

**Screenshots**

Before:

**<img width="285" alt="Screen Shot 2019-10-16 at 9 30 05 PM" src="https://user-images.githubusercontent.com/1231306/66970644-2fbbb900-f05c-11e9-920c-285accb2d90f.png">**|**<img width="285" alt="Screen Shot 2019-10-16 at 9 30 56 PM" src="https://user-images.githubusercontent.com/1231306/66970691-537eff00-f05c-11e9-9734-050bba9b201f.png">**
:-----:|:-----:

After:

**<img width="287" alt="Screen Shot 2019-10-16 at 9 32 33 PM" src="https://user-images.githubusercontent.com/1231306/66970757-89bc7e80-f05c-11e9-9e86-f9fdafece1b4.png">**|**<img width="286" alt="Screen Shot 2019-10-16 at 9 32 39 PM" src="https://user-images.githubusercontent.com/1231306/66970767-8fb25f80-f05c-11e9-8749-c69d78da4eb2.png">**
:-----:|:-----:

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 77.0.3865.120

**Comment by chrisvanpatten** [comment]
My proposed solution in #17985 didn’t quite past muster for the various reasons that @ItsJonQ pointed out on the PR. It’s the right move, but the fundamental issue persists.

It might be best to approach the problem more holistically, perhaps as part of a greater effort to rework the Gutenberg grid in the G2 efforts or the Emotion experiments.

**Comment by mirka** [comment]
We'll be addressing this in #38730
