### ISSUE TITLE
Clarify the status of the Gutenberg WordPress plugins.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17998]
Let's add a sentence about the plugin being a "beta/developpement" plugin that only supports the latest version of WordPress in the WordPress.org plugin's page and descriptions.

Right now, if you use WordPress 5.3 with an old version of the plugin, it will break. Clarifying the expectationis there is needed.

**Comment by swissspidy** [comment]
This should also be reflected in the „Requires at least“ header

**Comment by gziolo** [comment]
Cross-posting from the Gutenberg plugin support forum:
https://wordpress.org/support/topic/is-this-plugin-an-unstable-prototype-for-experimentation/.

**Comment by youknowriad** [comment]
The description has been updated and the minimum version set to 5.2. I'm closing this but let's consider raising the minimum version to 5.3 in future versions of the plugin.
