### ISSUE TITLE
[Feature] Inserter: Missing way to close the inserter on small screens

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17995]
**Describe the bug**
On smaller screens, the only way to close the inserter is by clicking on the narrow header which isn't very intuitive. An alternative way is to add a block ... 😅 

**To reproduce**
1. Change the browser size to use mobile or tablet viewports.
2. Open the existing page or post, or create a new on.
3. Open the inserter.
4. Try to close it.

**Expected behavior**
There is a visible way to close the inserter on mobile devices.

**Screenshots**

![Screen Shot 2019-10-10 at 17 14 14](https://user-images.githubusercontent.com/699132/67004921-ae0e6e80-f0e1-11e9-885a-45f44ca9af75.png)
![Screen Shot 2019-10-17 at 13 25 13](https://user-images.githubusercontent.com/699132/67004923-ae0e6e80-f0e1-11e9-9bc8-9c7474f8c2b1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome (small resolution)
 - Version: 77

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.1.2
 - Browser Safari

**Comment by melchoyce** [comment]
We could duplicate how the sidebar works on mobile, and add the title + an X button as a header to the modal:

![image](https://user-images.githubusercontent.com/2846578/69999192-0c729d80-1526-11ea-89ad-a99fe97122af.png)

**Comment by karmatosed** [comment]
This works for me @melchoyce. Although I think rethinking mobile visuals a bit is good but that's a bigger issue.

**Comment by Soean** [comment]
I tested this issue and it seems to be fixed, see screenshot of current master:

<img width="441" alt="Bildschirmfoto 2020-02-24 um 11 15 52" src="https://user-images.githubusercontent.com/695201/75128522-0e986280-56f7-11ea-9352-ea9b35e94b74.png">

Please reopen if I oversee something.
