### ISSUE TITLE
Add Block: RSS

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1799]
## Attributes

- RSS Feed URL
- Number of posts to show
- Display content
- Display author if available
- Display date

## States

Selected:
![rss](https://user-images.githubusercontent.com/2846578/27979829-e11eeea6-6346-11e7-8ec4-a7574170bafe.png)
![rss feed with dates](https://user-images.githubusercontent.com/2846578/27979830-e2c865f2-6346-11e7-81cc-5675de725179.png)
![rss feed with author](https://user-images.githubusercontent.com/2846578/27979831-e4299470-6346-11e7-8a12-60aa1d826a1c.png)
![rss feed with dates and author](https://user-images.githubusercontent.com/2846578/27979833-e611778a-6346-11e7-8724-23c29af4aaaf.png)
![rss feed with dates author and excerpt](https://user-images.githubusercontent.com/2846578/27979835-e75b0a66-6346-11e7-8c9a-4ee5f6ea9776.png)

Neutral:

![rss block](https://user-images.githubusercontent.com/2846578/27979836-ec85d8f4-6346-11e7-9357-a1b9fc7ef09b.png)

-----

Questions:
- Do we need to display the feed’s site title in the block itself? I didn't include this in the mockup.
- Can we get a post’s featured image from RSS?
- Can we display RSS posts as a grid? (Does this make a lot of sense if we can’t get featured images?)

**Comment by karmatosed** [comment]
Design looks solid to me.. let's get this marked for development.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
