### ISSUE TITLE
`allowed_block_types` allows block types which require a specific parent, to be added to root

### ISSUE THREAD

**Issue by benhuson** [WordPress/gutenberg#17991]
**Describe the bug**
I have created a container "grid" type block, and a "grid-item" type block.
The "grid-item" only has support for a parent of "grid".

For a bespoke theme I want to use the `allowed_block_types` filter to whitelist a small amount of blocks that may be used.

If I whitelist some core blocks and "grid", "grid-item" is not available to be inserted.
If I whitelist "grid-item" it allows me to insert this into the root (ie. the parent is ignored)

**To reproduce**
Register the grid and grid-item blocks:

```
registerBlockType( 'my-plugin/grid', {
	title       : 'Grid',
	description : 'A container for repeating grid items.',
	icon        : 'grid-view',
	edit( { className } ) {
		return (
			<div className={ className }>
				<InnerBlocks allowedBlocks={ ['my-plugin/grid-item'] } />
			</div>
		);
	},
	save() {
		return (
			<div>
				<InnerBlocks.Content />
			</div>
		);
	}
} );

registerBlockType( 'my-plugin/grid-item', {
	title       : 'Grid Item',
	description : 'A grid item.',
	icon        : 'screenoptions',
	supports    : {
		parent : [ 'my-plugin/grid' ],
	},
	edit( { className } ) {
		return (
			<div className={ className }>
				<InnerBlocks allowedBlocks={ ['core/paragraph','core/heading','core/image','core/list','core/button','core-embed/vimeo','core-embed/youtube'] } />
			</div>
		);
	},
	save() {
		return (
			<div>
				<InnerBlocks.Content />
			</div>
		);
	}
} );
```

Whitelist some core blocks and the grid and grid item blocks:

```
function my_plugin_allowed_block_types( $allowed_block_types, $post ) {

	return array(

		// Common
		'core/paragraph',
		'core/heading',
		'core/image',
		'core/quote',
		'core/gallery',
		'core/list',

		// Formatting
		'core/freeform',
		'core/html',
		'core/table',

		// Layout Elements
		'core/separator',
		'core/spacer',
		'core/button',
		'core/columns',
		'core/media-text',

		// Widgets
		'core/categories',
		'core/latest-posts',
		'core/shortcode',

		// Embeds
		'core/embed',
		'core-embed/vimeo',

		// Grid
		'my-plugin/grid',
		'my-plugin/grid-item',

	);

}
add_filter( 'allowed_block_types', 'my_plugin_allowed_block_types', 10, 2 );
```

How can I whitelist a block which must be used with a specific parent without making it available in the root?

**Comment by simonhammes** [comment]
First and foremost, every block must have a registered category. I'm assuming you only included a part of your source code ...

Now concerning your question: You have to whitelist both blocks and change the parent setting in the inner block: The `parent` property is not a child element of the `supports` property. Then it works according to your needs (for me at least).

https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#parent-optional

**Comment by talldan** [comment]
Closing, as this seems to have received feedback.
