### ISSUE TITLE
[Block] Columns: Insert button in the Column block overlaps the block toolbar

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17993]
**Describe the bug**
The insert button in the Column block overlaps the block toolbar on small screens.

**To reproduce**
1. Change the browser width to enable small viewport.
2. Add a new post.
3. Insert any block.
4. Insert Columns block.
5. Select the previous block.
6. Observer how the insert button in the Column block overlaps the block toolbar.

**Expected behavior**

**Screenshots**

![Screen Shot 2019-10-10 at 17 19 17](https://user-images.githubusercontent.com/699132/67004055-b665aa00-f0df-11e9-86a4-421c8d47c128.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by jasmussen** [comment]
I can't reproduce.

![mobile](https://user-images.githubusercontent.com/1204802/67087561-71a34700-f1a3-11e9-8196-9d0b78819935.gif)

I'm noticing a ton of other mobile bugs that are bad, but not this specific one. Can you give additional steps to reproduce?

**Comment by gziolo** [comment]
I guess you are testing with Safari on the simulator. I was testing with Chrome and small viewport:

![Screen Shot 2019-10-18 at 14 59 50](https://user-images.githubusercontent.com/699132/67096466-92c26280-f1b8-11e9-90ae-10c07cccda71.png)

**Comment by jasmussen** [comment]
No this was chrome in the inspector. Could be Safari related then?

**Comment by gziolo** [comment]
Safari:

![Screen Shot 2019-10-18 at 15 08 08](https://user-images.githubusercontent.com/699132/67096778-2005b700-f1b9-11e9-85e4-176bc6b69de0.png)

**Comment by edmundcwm** [comment]
Hello all,

First-timer here. I managed to replicate the issue. Anyone looking into this currently? If not i will try.

**Comment by gziolo** [comment]
@edmundcwm, go for it, thanks 🙇

**Comment by jasmussen** [comment]
Worth noting that this PR, https://github.com/WordPress/gutenberg/pull/18686, will make the toolbar docked to the top on mobile breakpoints, which should obviate the need for this to be fixed. So maybe it isn't worth it?

**Comment by gziolo** [comment]
@jasmussen can we close it now that you landed PR which changes how the toolbar works?

**Comment by jasmussen** [comment]
We can, yes!

![Screenshot 2019-12-10 at 10 39 35](https://user-images.githubusercontent.com/1204802/70517750-62080500-1b39-11ea-8cf4-b8e0599fd246.png)

Thank you.
