### ISSUE TITLE
Rich Text: inline image width popover appears on non-image-tags

### ISSUE THREAD

**Issue by mcguffin** [WordPress/gutenberg#18000]
**Describe the bug**
In rich text if you click on a non-image element (eg. `<span class="dashicons dashicons-yes"></span>`)

**To reproduce**
1. Add a text block. Enter some text.
2. Edit as HTML. Insert `<span class="dashicons dashicons-yes"></span>`.
3. Edit visually.
4. Click on the dashicon. The width popover appears. (Browsers: see Notes)
5. **Bonus:** Enter a width and press return. The `<span>` is replaced with `<img style="width: 123px;">`

**Expected behavior**
No popover on non-images in the first place.

**Screenshots**
*HTML:*
<img width="696" alt="grafik" src="https://user-images.githubusercontent.com/402988/67016317-4d3e6080-f0f8-11e9-8e0f-0e971136b7a0.png">

*The unwanted Popover*
<img width="690" alt="grafik" src="https://user-images.githubusercontent.com/402988/67017265-c9857380-f0f9-11e9-91ae-c101a6166dd7.png">

*The damage done 🎵*
<img width="680" alt="grafik" src="https://user-images.githubusercontent.com/402988/67016511-942c5600-f0f8-11e9-9249-15760f5ae54d.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Firefox latest, Chrome latest
 - Version WP 5.2.4

**Notes:**
*macOS Firefox* popover appears on every click.
*macOS Chrome + Safari:* popover only appears sometimes on click, always on doubleclick

**Comment by ellatrix** [comment]
Thanks for the report! This should be fixed in #17750, which is in Gutenberg 6.7.
