### ISSUE TITLE
Publish and Settings Buttons are different height

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18004]
**Describe the bug**

I know it's a small thing, but it keeps catching my eye...

The publish button is one pixel smaller. :)

<img width="424" alt="Screenshot 2019-10-17 at 18 31 11" src="https://user-images.githubusercontent.com/4710635/67028971-97314180-f10c-11e9-8053-d069a60d4b5e.png">

Cc @jasmussen

**Comment by ellatrix** [comment]
This is probably caused by the new button styles. :) Not sure where it should be fixed.

**Comment by jasmussen** [comment]
You're right! This is intolerable:

![Screenshot 2019-10-18 at 08 40 21](https://user-images.githubusercontent.com/1204802/67071478-f336ad00-f182-11e9-94d2-46ed94a7fca6.png)

ON IT!

**Comment by ellatrix** [comment]
😅
