### ISSUE TITLE
Button Block: Custom background color fails to display correct color in editor

### ISSUE THREAD

**Issue by jerrysarcastic** [WordPress/gutenberg#18012]
**Describe the bug**
When a button is created with a custom background color, this change is correctly reflected in the block editor.  However, if you reload the page (or return to edit it at a later date) the button background color reverts to a dark grey

I recorded a short video of this behavior here:  https://cld.wthms.co/ribfAh

**To reproduce**
1. Add a button block to a page or post
2. set a custom color for the button
3. Publish (or update the page) the reload the browser window
4. See error:  button is no longer custom color, but a dark grey

**Expected behavior**
Custom button color (correctly shown when setting or editing the background color) be retained when revisiting the editor

Note:  Custom BG color is correctly applied on the published page.  Bug seems to only affect the view in the editor itself.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.7
 - Browser Chrome 77.0.x and Safari 13.0.2
 - Wordpress 5.2.4
 - Gutenberg 6.7

**Comment by talldan** [comment]
@jerrysarcastic Thanks for taking the time to create this ticket, I was also able to replicate the issue.
