### ISSUE TITLE
Unable to crop images in Media Library

### ISSUE THREAD

**Issue by thatdevgirl** [WordPress/gutenberg#18010]
**Describe the bug**
I am unable to crop images in the Media Library. I am able to edit the image, but if I make any changes to crop the image, the "Save" button remains disabled, so I am unable to save my changes.

**To reproduce**
1. Go to the Media Library in the admin.
2. Select an image and click "Edit Image" underneath the image.
3. Click the "Crop" button.
4. Select the portion of the image that you want to keep after the crop.
5. Attempt to save. Note that the "Save" button is disabled.

Other things I tried: Changing the aspect ratio, pressing enter, double-clicking inside the selected portion of the image.

I do not see any errors or warnings in the dev tools console.

**Screen capture**
![edit-image](https://user-images.githubusercontent.com/5687778/67046507-57fbf400-f0fe-11e9-8f85-ec90f43e3ea1.gif)

**Expected behavior**
I expected to be able to save my changes to the image.

**Environment:**
 - OS: MacOS
 - Browser: Chrome (latest)
 - Wordpress core 5.2.4 (version of Gutenberg is whatever version is packaged with core v 5.2.4).

**Comment by anthonyburchell** [comment]
Hi there @thatdevgirl ! Thanks for making this issue. I just happened to have done work recently to bring this frame back to the modal, so this issue caught my eye. :) 

I did some testing and was seeing the same behavior! It turns out, [this is a ticket ](https://core.trac.wordpress.org/ticket/30155) that we have open currently Core side. 

I also found that it does work if you click the crop icon again after selecting your area. After clicking the crop icon, you should get the Save button able to be selected.

I'll admit, that's something I hadn't known about the crop tool so thanks for making this issue. I see we have it milestoned for a future release. Will keep my eye on it. Let me know if clicking the icon works and I'll close this one in favor of the trac ticket.

**Comment by swissspidy** [comment]
Can we close this in favor of the core ticket since this is working as "expected" and not specific to Gutenberg?

**Comment by thatdevgirl** [comment]
HI @anthonyburchell! Thank you for the tip! That does work for me - clicking the crop button again.

To be honest, I didn't even think to look for a core ticket because it is something my team noticed only with Gutenberg. (One of my colleagues noted that this is not an issue when using the core editor.) So, we figured it was a Gutenberg issue.

We can close this issue in favor of the core ticket.

**Comment by briantw** [comment]
Well, thankfully I googled this. Itʼs over a year and a half later and I was flummoxed by this issue. Thankfully the unintuitive behaviour of clicking Crop, then cropping, then clicking Crop again does the trick.

**Comment by sommerper** [comment]
Had to google this as well. All I can say is that this didn't work as I "expected".

**Comment by azatecas** [comment]
yeah still not intuitive, thanks for this ticket

**Comment by deanoakley** [comment]
How is this bad UX _still_ not fixed...

**Comment by JeremyWasHere** [comment]
Hello from 2022, still not fixed.

**Comment by gillmourtunhira** [comment]
absolutely annoying, need to be fixed... 2022 and still going

**Comment by duke-mediavine** [comment]
> absolutely annoying, need to be fixed... 2022 and still going

The Wordpress Core issue was also merged and closed as complete. Yet, the crop + save button use case was missed, which was enumerated in the [defect description](https://core.trac.wordpress.org/ticket/30155) as such:

> To save and apply the crop there should be one prominent button called "Apply crop" (currently the user needs to click on the crop tool again, which makes no sense and none of our test users could figure it out)

**Comment by guidofd** [comment]
This is still unbelievably unsolved.

**Comment by gavin310** [comment]
WordPress - WTF?

**Comment by rJonatan** [comment]
Still not fixed, it seems ... ! Thankfully I was able to use the workaround described.
