### ISSUE TITLE
Add Block: Tag Cloud

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#1801]
## Attributes

- None, Left, Right, Center, Full Width
- Taxonomy: Tags, Categories (retiring Link Categories?)
- Show post counts

## States

Selected:

![tag cloud](https://user-images.githubusercontent.com/2846578/27979896-5904373c-6347-11e7-8e81-4e0eed1008ca.png)

Neutral:

![tag cloud block](https://user-images.githubusercontent.com/2846578/27979899-5cdbf264-6347-11e7-9d05-7e80f8859fd7.png)

-----

Question:
- Why can you choose categories and link categories in the Tag Cloud? It's not indicated in the title or the description. Why were other taxonomies introduced to this widget?

**Comment by westonruter** [comment]
The inclusion of non-tag taxonomies in the Tag Cloud widget was done in [#11612](https://core.trac.wordpress.org/ticket/11612) (Expand the Tag cloud widget to support non-tag taxonomies). See [r13276](https://core.trac.wordpress.org/changeset/13276).

The taxonomies that are available for displaying in the Tag Cloud widget are all for which they are registered with `show_tagcloud` as `true`: https://github.com/WordPress/wordpress-develop/blob/4.8.0/src/wp-includes/widgets/class-wp-widget-tag-cloud.php#L131-L180

Taxonomies get registered with `show_tagcloud` as `true` by default: https://github.com/WordPress/wordpress-develop/blob/4.8.0/src/wp-includes/class-wp-taxonomy.php#L115

**Comment by karmatosed** [comment]
+1 from me on this design, looks ready to have someone begin development.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.

**Comment by jahvi** [comment]
Hey guys, I'm trying to give this one a go over at #4994, would love to get some feedback!
