### ISSUE TITLE
I would like to be able to call a "Reusable block" inside an "HTML block". By adding is name_number.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#18038]
**Is your feature request related to a problem? Please describe.**
We can create "Reusable block",
but we can't call them inside an "HTML block",
and it's annoying & joyless.

**Describe the solution you'd like**
To be able to use "Reusable Block" inside an "HTML Block"…

**Comment by swissspidy** [comment]
The HTML block is really made for adding static HTML, nothing else. What would be your use case for including a Reusable block (or any other block, really) within that?

Couldn't you insert an HTML block followed by the reusable one and then another HTML block?

**Comment by Nemzag** [comment]
Because I use HTML block starting with blockquote.
And if I split,
the graphical result is not good,
and not what I expect !

**Comment by mtias** [comment]
Unfortunately this is not possible. You can always break out of the HTML block, add a reusable block, and continue in another HTML block.
