### ISSUE TITLE
Text Block Border Radius

### ISSUE THREAD

**Issue by Titanas0** [WordPress/gutenberg#1805]
Following up #1692 and in order to provide a coherent visual experience across the board, text block border radius could be changed to have a radius of value 4, matching the rounded button style that exists today on Gutenberg (even without the changes suggested in 1692), matching the switch style rounded looks in Post Settings and also the rounded border style of the pop up when clicking on +

![gutenberg 4](https://user-images.githubusercontent.com/4397364/27984339-6c87f8ba-63d4-11e7-8cc1-7c620591d010.png)

**Comment by youknowriad** [comment]
I don't think we should do that unless we change it for all the blocks too, the post-title style matches the block styles.

**Comment by Titanas0** [comment]
Yes, that would be the next step for a consistent visual experience across the Gutenberg UI.

**Comment by litka** [comment]
I think rounding the hover and selected states of blocks is a great idea. According to research, rounded corners require less cognitive load and are more friendly and inviting.

There are a number of articles on the topic, but here's a good one for further reading:
https://designmodo.com/rounded-corners/

**Comment by karmatosed** [comment]
I would be cautious over a change unless @jasmussen wants to do that as this impacts other areas. I would be a -1 on this as feel it would mean other changes.

Rounded corners do not always mean less cognitive load and friendly - they actually can have opposite issues for some and be considered not mature and frivolous. I say that without personal opinion, just that we can't take everything as binary with regards to research. It's a matter of context. I think so long as we are consistent, either works.

**Comment by jasmussen** [comment]
Yep, I'm reluctant to do this primarily because we really are embracing the block as the interface. They should context together like masonry, to represent their underlying markup and structure.

Thanks for the mock-ups though!

**Comment by Titanas0** [comment]
@karmatosed i agree, the issue is consistency or actually the lack of it. Buttons and switches are rounded but not the borders of said text blocks

**Comment by karmatosed** [comment]
I am going to close this. I stand by my feelings and we have some design feedback to not do this.
