### ISSUE TITLE
Add scope to iframe 100% width css style

### ISSUE THREAD

**Issue by barryceelen** [WordPress/gutenberg#18050]
Gutenberg global styles [insist that an iframe should be 100% wide](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/style.scss#L194).

This overrides any iframe width or height attributes, I guess to be able to render videos and such responsively, but leads to trouble where the width and height attributes should not be overridden (in our case: ads).

**Expected behavior**
The `width: 100%` iframe style should be scoped to the block that needs it, in stead of being global.

**Comment by NicktheGeek** [comment]
Second to this. Currently the stylesheet is outputting even when gutenberg is disabled and it is breaking live sites that are on WP 5.3.

**Comment by NicktheGeek** [comment]
Follow up here as some folks may end up searching for a solution. In my case the styles shouldn't even be loaded because GB is not enabled on the sites this was breaking, so I just added `wp_dequeue_style( 'wp-block-library' );` to the wp_enqueue_scripts hook. I'm hoping to make that a temp change as I'd like to see GB support on these sites eventually, but this CSS needs to change.

**Comment by federicojacobi** [comment]
This works really nicely:
```
add_action( 'enqueue_block_assets', function() {
	wp_dequeue_style( 'wp-block-library' );
	if ( current_theme_supports( 'wp-block-styles' ) ) {
		wp_dequeue_style( 'wp-block-library-theme' );
	}
} );
```
It is basically the reverse of https://github.com/WordPress/WordPress/blob/master/wp-includes/script-loader.php#L2831

**Comment by bengreeley** [comment]
+1 Seeing this mess up ads that don't have explicit width/height attributes specified in the iFrame code. Disabling the Gutenberg plugin and relying on core functionality for now, but it would be great if this was fixed.

**Comment by bengreeley** [comment]
Actually, looks like it may be fixed 🎉 https://github.com/WordPress/gutenberg/pull/18287
