### ISSUE TITLE
Unable to add reusable block if it contains more than one block.

### ISSUE THREAD

**Issue by iruzevic** [WordPress/gutenberg#18063]
**Describe the bug**
If you create a reusable block that has more than one block added that are not a part of some parent block it won't show in the blocks list to add in the editor.
 
**To reproduce**
1. Create a reusable block with more than one block inside.
2. Go to any page editor and click on plus to add a block
3. Reusable block will not show.

**Expected behavior**
If your reusable block contains multiple blocks that are not a part of a parent block (group, etc) it should still show in the reusable block list to be able to add.

**Screenshots**
I have attached the video.
[Missing reusable block.mov.zip](https://github.com/WordPress/gutenberg/files/3756539/Missing.reusable.block.mov.zip)

**Desktop:**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome 77.0.3865.120

**Additional context**
- WordPress - 5.2.4

**Comment by talldan** [comment]
@iruzevic I haven't been able to reproduce this issue, but it might be because I'm using a newer version of Gutenberg. Are you using the Gutenberg plugin, or the version that comes with core?

**Comment by iruzevic** [comment]
I'm not using a plugin. This is a version from core. WordPress version 5.2.4.

But I did some deeper research I now see that you have to have two core block enabled in the project for reusable blocks to work:

core/block; - This is used for reusable blocks
core/template; - This is used for my problem.

It would be great to have this in the documentation for the reusable blocks.

Tnx we can close this ticket.
