### ISSUE TITLE
adsense automatic ads are not shown in the post

### ISSUE THREAD

**Issue by mfa95** [WordPress/gutenberg#18065]
Hi, I don’t know English I’m using google translate, sorry.

Google announced the new feature! now automatically places ads on the site itself. but no ads appear in the article.

this problem is very common. nobody knows why. but I noticed. articles written in the classic editor have ads, but articles written in guttenberg have no ads!

new automatic ads code
`<script data-ad-client="ca-pub-xxxxxxxxxxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`

placed before the head tag </head>. google determines the position of ads.automatic ad positions works in classic editor but not in guttenberg

Please solve this problem.

**Comment by swissspidy** [comment]
Hi there

If you have issues with AdSense Auto Ads on your site, I recommend asking for help in the [Google AdSense Help Community](https://support.google.com/adsense/community?hl=en) or perhaps the [WordPress.org support forums](https://wordpress.org/support/). Those are more appropriate places to get help with that.

Thanks for understanding!
