### ISSUE TITLE
Documentation: Make it easier to check when the next npm release is scheduled

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18075]
There are some existing documents which contain the necessary details, but they are hard to discover and aren't properly cross-linked:
- https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#packages-releases-and-wordpress-core-updates
- https://github.com/WordPress/gutenberg/blob/master/packages/README.md#releasing-packages

There is also https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/packages.md which doesn't contain any reference.

There is also this roadmap issue (https://github.com/WordPress/gutenberg/issues/15068) pinned and displayed on the issues page:
![Screen Shot 2019-10-23 at 13 15 41](https://user-images.githubusercontent.com/699132/67389043-1786f500-f59a-11e9-9864-008c390d8c84.png)

We could include the details about the major WordPress releases and how it impacts npm releases.

**Comment by paaljoachim** [comment]
I am pinging in @noahtallen here.
Should the issue remain open or should we close it?

**Comment by gziolo** [comment]
I don't think it's improved much.

**Comment by noahtallen** [comment]
I agree this would be very helpful, especially during the core WP release cycle.
