### ISSUE TITLE
Navigation Block: Implement a solution for CSS custom properties in Internet Explorer.

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#18076]
The current way to apply styles to the `<NavigationMenuItem />` is using [CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) and it isn't supported by Internet Explorer. Dig in order to find a way to implement the desired behavior for this browser as well.

**Comment by draganescu** [comment]
We should not find a way to do it in IE, instead we could simply hide the color controls in IE.

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
