### ISSUE TITLE
Add prop to richtext to remap newline to a different keycode

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#18080]
**Is your feature request related to a problem? Please describe.**
We created a a custom table block using the RichText component in the cells that allows our users to navigate the table like excel, (tab/shift+tab to navigate columns, enter/shift+enter to navigate rows.). I have some custom code that filters out line breaks on shift enter, but we would like to allow users to create a new line if they do alt+enter. Currently though there doesn't seem to be a way to map a different keyboard code for that new line break. Would it be possible to add a new prop to the RichText component that allows for a different new line keycode?

**Comment by paaljoachim** [comment]
Hi @myleshyson Myles

Thank you for creating the issue!
A long time has passed.
Is this issue still valid?

I'll ping in Dan as well. @talldan

**Comment by myleshyson** [comment]
Hi @paaljoachim, 

Valid yes, however not really a big priority for us anymore. I still think it would be nice though.

**Comment by talldan** [comment]
This is already possible from what I understand using the `multiline` prop.

Here's an example in the codebase where the list block uses it to insert an `li`:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/list/edit.js#L162

**Comment by talldan** [comment]
Whoops, sorry if you saw my previous comment, I completely misread the description and gave the wrong feedback, so have deleted it.

It's an interesting proposal, and I see the use case having checked out google sheets.

However, I'm hesitant to leave this open as I don't realistically expect this to be implemented. It seems like a very niche behaviour, and my opinion is that there won't be enough demand to see this actually happen. It's out of scope for core blocks at the moment, including the table block where arrow keys can already be used for navigation.

So I'm going to close the issue (again! 😓 ), but thanks for proposal, input is always welcome. Issues can always be reopened if there's demand, so it's potentially not forever, more of a task management process for us.
