### ISSUE TITLE
Reusable Block: Embed block only shows URL on frontend

### ISSUE THREAD

**Issue by eoinsav** [WordPress/gutenberg#18098]
**Describe the bug**
When some of the Embed blocks (YouTube, Vimeo, Twitter, and more) are turned into Reusable blocks, only the URL is displayed on the front end and not the embedded content. It does show as embedded in the edit screen, though.

This is the same as the following closed bug report: https://github.com/WordPress/gutenberg/issues/9937

That bug was fixed here: https://github.com/WordPress/gutenberg/pull/10035

**To reproduce**
1. Create a new page or post.
2. Add a YouTube, Vimeo, or Twitter block.
3. Embed some content from one of those platforms.
4. Add to reusable blocks.
5. Add the reusable block to a page or post.
6. View the page or post on the frontend of the site.

**Expected behavior**
The embedded content should be displayed but only the embedded URL is displayed.

**Desktop:**
 - OS: macOS 10.15
 - Chrome
 - Version 77.0.3865.120

**Additional context**
- WordPress Version 5.2.4

**Comment by junaidbhura** [comment]
Looks like there's a Tract ticket for this: https://core.trac.wordpress.org/ticket/46457

**Comment by rickmgithub** [comment]
Hi. I had a similar issue with the Twitter block when a group of blocks is included in a reusable block.

The twitter block no longer works after converting to a reusable block.

When you convert it back to a normal block from a reusable block it works again.

2548846-zen

**Comment by maximilliangeorge** [comment]
I'm experiencing this problem. I'm using the REST API in a headless set-up.

I'm getting this on the website:

```
<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio">
  <div class="wp-block-embed__wrapper">https://vimeo.com/387549808</div>
</figure>

**Comment by noisysocks** [comment]
Closing this issue in favour of https://github.com/WordPress/gutenberg/issues/14608.

**Comment by waleedt93** [comment]
@junaidbhura Worked Perfectly, Thank You
