### ISSUE TITLE
Editable: inconsistent CSS selector between save and edit

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#1810]
Stumbled upon this while adding the verse block: https://github.com/WordPress/gutenberg/pull/1809/files#diff-8d2ebfe47a97df303bfb65b6e0692d50

```css
pre.wp-block-verse,
.wp-block-verse pre {
	...
}
```

As you can see, the editor and front end version require different selectors, because the actual editable area is wrapped in a div. One solution could be to apply the class the the actual editable area rather than the wrapper, but still, that might have unintended side effects.

**Comment by youknowriad** [comment]
Do we have any actionable item on this one? maybe this could be an ok drawback as the `Editor` and `Frontend` can never match 100%. 

That said, we could make them as close as we can.

**Comment by iseulde** [comment]
I don't mind for now
