### ISSUE TITLE
Hitting Enter in 'core/paragraph'-template with template_lock on deletes content

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#18103]
**Describe the bug**
I have a post type with a block-template set to a single 'core/paragraph'-block and template_lock='all'.

When I edit a post and write a few words in the paragraph, then put the cursor in the middle of the written text and hit "enter", the content past the cursor disappears. In this case it would be great if "enter" would always insert a `<br>` instead of trying to create a new paragraph and failing.

**To reproduce**
1. define block template for a custom post type (or set it for 'post' or 'page') that allows only one 'core/paragraph' block and set template_lock to 'all'
2. write some text in that respective post type 
3. put cursor somewhere within the text and press "enter"
4. the text past the cursor disappears (because wp tries to put it into a new paragraph which it cant do due to the template_lock.

**Expected behavior**
inserting a `<br>` instead of trying to create a new paragraph.

**Desktop (please complete the following information):**
 - Windows 7
 - Firefox

**Additional context**
I only tested this on WordPress 5.2.4

**Comment by jorgefilipecosta** [comment]
Hi, thank you for reporting this issue 👍 
It seems on the last version of WordPress part of the content is not lost anymore. I'm closing this issue, for now, feel free to leave a comment if you have further insights.
