### ISSUE TITLE
Add Font Picker component

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#18113]
We provide a way for themes to declare color schemes, which goes a long way for allowing theme-curated customization of sites. I wish we had the same feature for fonts, where a theme could declare font files to enqueue. Then, themes could choose which blocks to add a font picker to.

I imagine you'd first have to enqueue the font, then the different variations/weights/styles in JSON.

We wouldn't expose the font picker by default — it would only be shown if a theme adds support.

**Comment by paaljoachim** [comment]
I think adding a Font Picker component is a very good idea! As sometimes one just wants to use another font then the default one available.

@ItsJonQ @youknowriad

**Comment by mtias** [comment]
Font family support is now part of theme.json
