### ISSUE TITLE
Combining EditorHistory with standalone BlockEditor

### ISSUE THREAD

**Issue by arnvanhoutte** [WordPress/gutenberg#18120]
Is it possible to combine [EditorHistory](https://github.com/WordPress/gutenberg/tree/4e9d9b3d36841c264bce35d4bf1ba3d9ff75f659/packages/editor/src/components/editor-history) with the standalone [BlockEditor](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor)? This seems to be included in the default editor but they would be a welcome extra in the standalone editor.

**Comment by talldan** [comment]
I think it'd be easy enough to make components that handle undo and redo, something along the lines of this for undo:
```jsx
function UndoButton() {
  const undo = useDispatch( 'core' ).undo;
  const hasUndo = useSelect( ( select ) => select( 'core' ).hasUndo(), [] );

  return (
    <Button
	icon={ undoIcon }
	label={ __( 'Undo' ) }
	aria-disabled={ ! hasUndo }
	onClick={ hasUndo ? undo : undefined }
    />
  );
}
```
