### ISSUE TITLE
Readme.txt is too big – move old changelog items to separate changelog.txt

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#18126]
**Describe the bug**
Readme.txt for version 6.7.0 is 15 kbytes.
The readme parser may have problems handling files larger than 10 kbytes. Easiest fix is to migrate older items in the changelog to a separate changelog.txt.
A positive side-effect of this is that the number of readme strings in the translation project will be less.

**Comment by swissspidy** [comment]
Where do you see that?

http://plugins.svn.wordpress.org/gutenberg/trunk/readme.txt only contains 1 changelog entry. So does http://plugins.svn.wordpress.org/gutenberg/tags/6.7.0/readme.txt.

**Comment by tobifjellner** [comment]
I didn't actually read the readme. I just noted that its size is about 15 kb and know that some plugins have had issues with too big readme and it's been said that 10 kb should be regarded as the limit.
Anyway, if it still doesn't break things, then I guess it would not be high prio to "fix" this :)

**Comment by swissspidy** [comment]
It's indeed quite large even with only listing the most recent changelog.

I know some plugins remove the changelog entirely and just point to `changelog.txt` or the changelog on the GitHub release page.

We could do that here too. A quick test shows that it would reduce the size from almost 16KB to around 7KB.

**Comment by youknowriad** [comment]
@swissspidy I'd love more thoughts on the subject, but that seems reasonable to me, we would have to tweak the release tool a little bit for the change, but it should be minor.

**Comment by youknowriad** [comment]
These files have been moved to the Git repository (cc @jorgefilipecosta), implementing this will be easier now.

**Comment by jorgefilipecosta** [comment]
Hi @youknowriad, it seems currently we only keep the changelog of the last version, but even the changelog for one version is huge.
There are some options we can follow:
- Force the person doing the release to provide a smaller changelog with a character limit.
- Parse the changelog and only include some sections e.g: the new features part.

Which option would you prefer?

**Comment by youknowriad** [comment]
I'd just go with the linking personally as well
