### ISSUE TITLE
Button Block with gradient: Border style issue

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#18124]
Hey,

if I use the new gradient styles for the button block, so I get a small design issue in case of the button have a default border by the theme, like:

`.button { border-style: solid; border-width: 2px }`

<img width="924" alt="Bildschirmfoto 2019-10-27 um 20 05 07" src="https://user-images.githubusercontent.com/31563167/67639840-1a188000-f8f5-11e9-98e1-757b1e23a8e2.png">

<img width="324" alt="Bildschirmfoto 2019-10-28 um 10 48 47" src="https://user-images.githubusercontent.com/31563167/67668621-969c7480-f970-11e9-9096-b1492c1246eb.png">

To solve the issue, we need a selector class in the case of the element have a gradient like: "`has-gradient`" class.

So we could handle this case like:

`.btn.has-gradient { border: 0 }`

<img width="413" alt="Bildschirmfoto 2019-10-27 um 19 57 48" src="https://user-images.githubusercontent.com/31563167/67639802-9b234780-f8f4-11e9-9bde-c3920536c965.png">

But currently there is no way to handle this case.

An other way to handle this case, is to add a default panel to the button block to set the border width manually. Also an additional border color selection would be great.

**Comment by jorgefilipecosta** [comment]
Hi @CreativeDive,
Does the margin issue also happen when a solid background color is selected?
Would it be possible to relly on has-background class instead?

Thank you in advance for any insights you could provide!

**Comment by CreativeDive** [comment]
@jorgefilipecosta This only happens if the button with a default border has a gradient. If the button has a solid background color, the border looks good. In the case of a selected background gradient, the button gets a strange border style, as you can see in my sample images.

You can reproduce it by adding a fixed border width for the button.

The selector "has-background" does not help, because I want to display the border for buttons with a solid background. I would also show the border for buttons with gradient background, but that does not look good.

Do you have any idea how we can solve this case?

**Comment by CreativeDive** [comment]
Ok, I think I have found a working solution: https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin

`.wp-block-button__link {background-origin: border-box!important;}`

This fix is working fine and the strange border on buttons with gradient is gone.

I think we can close this issue :-)

**Comment by jorgefilipecosta** [comment]
Thank you for debugging this issue 👍
