### ISSUE TITLE
Components: Ensure that ExternalLink component doesn't show up visually hidden elements when rendered outside of WordPress

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18127]
**Describe the bug**
Discovered when testing the Storybook integration of the `ExternalLink` component. See the related comment https://github.com/WordPress/gutenberg/pull/18084#issuecomment-546817096:

> CSS styles for `screen-reader-text` don't load:
> 
> ![Screen Shot 2019-10-28 at 07 59 31](https://user-images.githubusercontent.com/699132/67658106-ec652280-f958-11e9-83c0-8c6a8c69b4a4.png)

**To reproduce**
1. Run Storybook: `npm run design-system:dev`.
2. Go to the `ExternalLink` section.

**Expected behavior**
`(open in a new tab)` text is only visible for screen readers. Instead of using the class `screen-reader-text`, the text should be put inside the `VisuallyHidden` component introduced by @mkaz in #18022.  You can also check a similar refactoring in #18013.

**Comment by youknowriad** [comment]
Wes should do a global PR that replaces all usages of screen-reader-text className with VisuallyHidden component;
