### ISSUE TITLE
Improve code readability in latest-comments.php (and possibly other)

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#18143]
Follow up from trac: https://core.trac.wordpress.org/ticket/48447#comment:5.

The code readability in `latest-comments.php` and probably other places can be better.

Generally having nested function calls with each param on its own line adds a lot of "vertical bloat" and "indentation bloat". These can be avoided by making the code a bit more "wordy" but the result is quite easier to read.

Also each `if () {}` statement signifies a new "logical block" with its own indentation. Usually better to have empty lines around.

Also, for better readability long ternary operators should probably be:

```php
if ( ! empty( $comments ) ) {
    return sprintf( '<ol class="%1$s">%2$s</ol>', $classnames, $list_items_markup );
} else {
    return sprintf( '<div class="%1$s">%2$s</div>', $classnames, __( 'No comments to show.' ) );
}
```

instead (especially when returning from them).

The six level deep nested array in `register_block_core_latest_comments()` is also quite "problematic" with some vertical and indentation bloat and uneven/weird white spaces but that's a bug in WPCS that needs fixing upstream (the issue there has been open for a long time!).

Example patch: https://core.trac.wordpress.org/attachment/ticket/48447/48447-readability-fixes.diff.

**Comment by paaljoachim** [comment]
Hey @azaozz 

Thanks for creating the issue!
Is this issue still valid?

@WordPress/gutenberg-core

**Comment by noisysocks** [comment]
Agree this could be cleaned up but I think better to do it next time substantial work is being done on this block.
