### ISSUE TITLE
Partially checked checkbox looks visually askew

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#18152]
**Describe the bug**
Partially checked checkboxes need some styling tweaks.

**To reproduce**
1. Open the Block Manager
2. Uncheck an individual block
3. Observe that the checkbox for the category becomes partially checked but the horizontal line is off-center.

**Expected behavior**
The checkbox should appear correctly

**Screenshots**
![Screen Shot 2019-10-29 at 12 33 27 pm](https://user-images.githubusercontent.com/677833/67738367-4e04ba00-fa49-11e9-973f-ebfef7f4f553.png)

**Additional context**
- Tested in Chrome on Mac OS against `master` 2980cb97cad080d256c1523b88a18cfe78915fd6

**Comment by sourcediz** [comment]
So while fixing this issue I ran across one more problem with the checkbox bar changing media queries to early (see related pics)
![Screen Shot 2019-10-29 at 5 39 19 pm](https://user-images.githubusercontent.com/21496039/67747078-b10b4680-fa73-11e9-8d41-1d3531971c97.png)
![Screen Shot 2019-10-29 at 5 38 24 pm](https://user-images.githubusercontent.com/21496039/67747080-b1a3dd00-fa73-11e9-9a25-fa6eda8b0b07.png)
![Screen Shot 2019-10-29 at 5 38 07 pm](https://user-images.githubusercontent.com/21496039/67747081-b1a3dd00-fa73-11e9-94d1-5a85b7dec028.png)

Here is the finished result
![Screen Shot 2019-10-29 at 5 46 09 pm](https://user-images.githubusercontent.com/21496039/67747480-8968ae00-fa74-11e9-978e-49d3601f80c0.png)
![Screen Shot 2019-10-29 at 5 45 53 pm](https://user-images.githubusercontent.com/21496039/67747481-8a014480-fa74-11e9-8acd-336544521651.png)

Thought I would just add this comment so you would be able to assign me the issue now as I cant do a pull request right this second cheers.

Super Excited to to contribute to Gutenberg/Wordpress as one of my first PR

**Comment by talldan** [comment]
Thanks for picking this up @sourcediz! I've assigned you 👍

**Comment by talldan** [comment]
Hi @sourcediz, are you still planning to work on a fix for this?

**Comment by sourcediz** [comment]
Hi @talldan, I submitted the pull request quite a long time ago. Sorry I should of commented here and updated you. Here is the link to the pull request.

https://github.com/WordPress/gutenberg/pull/18293

**Comment by talldan** [comment]
It looks like this is fixed in a recent change, so closing the issue.
