### ISSUE TITLE
Sentences that are difficult to translate

### ISSUE THREAD

**Issue by nukaga** [WordPress/gutenberg#18151]
**Description**

Working on the translations for 5.3 we (Japanese polyglots) found some difficult passages to translate.

```content: Object(external_this_wp_i18n_["__"])('// A "block" is the abstract term used') + '\n' + Object(external_this_wp_i18n_["__"])('// to describe units of markup that,') + '\n' + Object(external_this_wp_i18n_["__"])('// when composed together, form the') + '\n' + Object(external_this_wp_i18n_["__"])('// content or layout of a page.') + '\n' + Object(external_this_wp_i18n_["__"])('registerBlockType( name, settings );')```

https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/block-library.js?marks=9190#L9190

**Problem**
The order of words in English and Japanese changes, so if you add a translation that corresponds to the word, the whole sentence will be strange.

**Solution**
We may include translations that do not correspond to words. 
If the comments indicate the intent of such a passage, we will be able to include a translation that matches that intent. For example, "Check line feed".

**Comment by swissspidy** [comment]
Source code:

https://github.com/WordPress/gutenberg/blob/b5fe68187f94c0a204a336825e7c6aa6042c48aa/packages/block-library/src/code/index.js#L23-L31
