### ISSUE TITLE
Special characters in permalink not being properly converted

### ISSUE THREAD

**Issue by bartczyz** [WordPress/gutenberg#18177]
**Describe the bug**
In Danish there are some extra letters - Ø Å and I've noticed that they are not being properly converted, so:

- "Ø" should be converted to "OE"
- "Å" should be converted to "AA"

Initially I thought that this might be an issue with Core, but after doing some tests the characters are converted properly when using Classic Editor:

![danish_special_characters_classic_editor](https://user-images.githubusercontent.com/1191500/67840741-ce352900-faf6-11e9-867a-0ca556e9b26b.png)

Since it's not an issue with Core it has to be an issue with Gutenberg. 🤔

![image](https://user-images.githubusercontent.com/1191500/67841626-d4c4a000-faf8-11e9-98d8-2880ccba80e3.png)

In Gutenberg `post-permalink` component contains a method called `onSavePermalink()`, that method is using `cleanForSlug()` helper function that is responsible for performing basic cleanup of a string for use as a post slug.

From what I noticed that function is using `lodash.deburr()` that deburrs string by converting [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)#Character_table) and [Latin Extended-A](https://en.wikipedia.org/wiki/Latin_Extended-A) letters to basic Latin letters and removing [combining diacritical marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks), which is causing the whole issue.

**To reproduce**
1. Go to 'Add New Post'
2. Put 'Ø Å' in the title and save the post
3. Click on the saved title to see the slug

**Expected behavior**
To behave in the same manner as Core.

**Additional context**
- I was testing on WordPress 5.2.4 and WordPress 5.3 using Gutenberg 6.7.0.

**Comment by getdave** [comment]
Looks like a good candidate for a PR. Here is the offending function

https://github.com/WordPress/gutenberg/blob/51fee9a045298a9c81e81675893c889e8df971cf/packages/editor/src/utils/url.js#L41

**Comment by swissspidy** [comment]
This is a longstanding and known issue. The main discussing is being tracked in #12907, but it also has been reported in #16695 before. I am therefore closing it as a duplicate.

That doesn't mean it's not a valid report or anything, it just helps us keep a better eye on things.

As for the `cleanForSlug` function, it already states in the docs that it is somewhat similar to `sanitize_title`. The only real way would be to replicate the function as-is (some duplicated logic across PHP and JS), or use the REST API (inefficient)
