### ISSUE TITLE
How to disable gradients?

### ISSUE THREAD

**Issue by benhuson** [WordPress/gutenberg#18171]
With the custom colour palettes it is possible to disable them by disabling custom colours:

`add_theme_support( 'disable-custom-colors' )`

...then defining an empty custom palette:

`add_theme_support( 'editor-color-palette', array() );`

Is there a similar way to disable/hide the gradients palette? eg.

`add_theme_support( 'editor-gradient-palette', array() );`

**Comment by youknowriad** [comment]
Thanks for the issue. Theme support for gradients is being worked on in #17774 and it will include the possibility to disable them
