### ISSUE TITLE
Block breadcrumbs overlapping toolbar WP 5.3 RC3

### ISSUE THREAD

**Issue by Runemark7** [WordPress/gutenberg#18186]
**Describe the bug**
Im trying to change width on the image that is inside of a column as you see in the gif. The problem is that the columns breadcrum prevents me to click at the buttons in the toolbar.

NOTE: I can't press on any button in the toolbar (even the buttons that is outside of the breadcrumb)

How the blocks is structured:
Group
   -columns
       --column
          ---image <- trying to make this full width
       --column
          ---image

**Screenshots**
![07bb4397a306e934abf072b1f7f2c8f0](https://user-images.githubusercontent.com/42864172/67861103-c76edc00-fb1f-11e9-98f7-9fdb7701ddd3.gif)

**Additional context**
- Wordpress 5.3 RC3
- Wordpress language: Swedish

**Comment by jorgefilipecosta** [comment]
Hi @Runemark7,
Thank you for reporting this issue 👍 
In my tests, it seems this problem is not happening with the last version of Gutenberg and with WordPress 5.3 final.

If the problem is still happening in your tests, please leave a comment so we look further into this problem.
