### ISSUE TITLE
Template not found in version 6.8.0

### ISSUE THREAD

**Issue by SoftwaregeekNL** [WordPress/gutenberg#18192]
**Describe the bug**
When I updated Gutenberg to 6.8.0 the website brobe.
Use DIVI Theme.

**To reproduce**
1. Go to admin backoffice Wordpress version 5.2.4
2. Click on activate Gutenberg version 6.8.0.
3. Scroll down to website 'TEMPLATE NOT FOUND'
4. 
**Expected behavior**
80.101.234.46 - - [30/Oct/2019:17:08:29 +0100] "GET /wp-content/uploads/2019/10/cropped-softwaregeeklogo-3-1-1-100x100.png HTTP/1.0" 200 450 "https://www.softwaregeek.nl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:40 +0100] "GET /wp-admin/plugins.php?action=activate&plugin=gutenberg%2Fgutenberg.php&plugin_status=all&paged=1&s&_wpnonce=5211f10ca2 HTTP/1.0" 302 651 "https://www.softwaregeek.nl/wp-admin/plugins.php?plugin_status=all&paged=1&s" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
80.101.234.46 - - [30/Oct/2019:17:08:41 +0100] "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/1.0" 200 147912 "https://www.softwaregeek.nl/wp-admin/plugins.php?plugin_status=all&paged=1&s" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
80.101.234.46 - - [30/Oct/2019:17:08:42 +0100] "GET /wp-content/plugins/gutenberg/build/i18n/index.js?ver=29110a0aa3d8e3d67abbd6c0f11a3e04 HTTP/1.0" 200 442 "https://www.softwaregeek.nl/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
80.101.234.46 - - [30/Oct/2019:17:08:46 +0100] "GET / HTTP/1.0" 200 33986 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:48 +0100] "GET /wp-content/plugins/gutenberg/build/block-library/style.css?ver=1572449583 HTTP/1.0" 200 438 "https://www.softwaregeek.nl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:48 +0100] "GET /wp-content/cache/et/global/et-divi-customizer-global-15724517270098.min.css HTTP/1.0" 200 455 "https://www.softwaregeek.nl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:48 +0100] "GET /wp-content/themes/Divi/css/ HTTP/1.0" 403 1464 "https://www.softwaregeek.nl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:48 +0100] "GET /wp-content/uploads/2019/10/cropped-softwaregeeklogo-3-1-1-100x100.png HTTP/1.0" 200 450 "https://www.softwaregeek.nl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3950.0 Safari/537.36 Edg/80.0.317.1"
80.101.234.46 - - [30/Oct/2019:17:08:59 +0100] "GET /wp-admin/plugins.php?action=deactivate&plugin=gutenberg%2Fgutenberg.php&plugin_status=all&paged=1&s&_wpnonce=4c15db30b6 HTTP/1.0" 302 653 "https://www.softwaregeek.nl/wp-admin/plugins.php?plugin_status=all&paged=1&s" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by aristath** [comment]
Make sure that the experiments are turned off in Gutenberg's plugin options.

**Comment by saas786** [comment]
It happens for me when I enable "Full Site Editing" in experiments tab.

Is it half baked? Is there any doc on this topic, feature? So we can properly utilize it.

**Comment by tellthemachines** [comment]
Hi @SoftwaregeekNL , could you please check if you have "Full Site Editing" enabled in Gutenberg plugin "Experiments" section? If so, this is expected behaviour. Thanks!

**Comment by talldan** [comment]
Closing the issue as there hasn't been a response.
