### ISSUE TITLE
Column Block: Movers for Full and Wide Images inside columns are not visible

### ISSUE THREAD

**Issue by mikeyarce** [WordPress/gutenberg#18195]
**Describe the bug**
When you add a Full or Wide image inside a Column Block, the movers are not visible:

<img width="816" alt="Screen Shot 2019-10-30 at 1 24 02 PM" src="https://user-images.githubusercontent.com/3220162/67895923-9808a100-fb18-11e9-8f35-86f853764aef.png">

**To reproduce**
Steps to reproduce the behaviour:
1. Create a new Column Block
2. Add an Image block inside a column
3. Set the image to Wide or Full
4. The Mover will not be visible

**Expected behaviour**
I should be able to see and use the Mover

**Screenshots**
With a "Full" width column block and a Full width image:
<img width="1405" alt="Screen Shot 2019-10-30 at 1 25 58 PM" src="https://user-images.githubusercontent.com/3220162/67896062-d69e5b80-fb18-11e9-9c07-14e6fa079ead.png">

With a "Full" width column block and a Wide image:
<img width="596" alt="Screen Shot 2019-10-30 at 1 28 20 PM" src="https://user-images.githubusercontent.com/3220162/67896250-3432a800-fb19-11e9-8466-42e661928064.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
- Using latest `master`

**Comment by talldan** [comment]
I tested, and this does indeed seem to be a bug.

At the moment there's a proposal to relocate the movers to the toolbar, which would solve this issue: https://github.com/WordPress/gutenberg/pull/18685.
