### ISSUE TITLE
Components: Spinner is oddly floated to the right outside of WordPress

### ISSUE THREAD

**Issue by brentswisher** [WordPress/gutenberg#18199]
**Describe the bug**
When accessing the Spinner component outside of WordPress, it is floated to the right in its container. Originally reported here: https://github.com/WordPress/gutenberg/pull/18145#pullrequestreview-308289448

**To reproduce**

Run Storybook: npm run design-system:dev.
Go to the Spinner section.
See that it is floated to the right

**Expected behavior**
Open to design feedback, but I would imagine either no alignment applied or centered (See: https://github.com/WordPress/gutenberg/pull/18145#issuecomment-547807231)

**Comment by gziolo** [comment]
You can see how it aligns currently here:
https://wordpress.github.io/gutenberg/design-system/components/?path=/story/spinner--default
