### ISSUE TITLE
URLs without protocols are not detected when pasted

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#18193]
This issue was originally reported against the Classic Editor in WordPress Trac (see [Trac-37805](https://core.trac.wordpress.org/ticket/37805)), but the behavior also exists in Gutenberg. Moving here for consideration. Note: I could have sworn that I have seen a similar issue here on GitHub, but couldn't find it.

Original report: 
> Currently TinyMCE doesn't detect www links without http:// in front of them.
> 
> This means that the workflow for making www.url.com into a link is Select Text -> Press Link Button (or Ctrl+k) -> Type (or copy/paste) text into link dialogue, while the workflow for an http:// is simply Link Button (or Ctrl+k) -> Enter.
> 
> Since www is still pretty common for canonical urls, it seems like it would be useful to include detection of www links in TinyMCE, and avoid the extra step, and improve this workflow. This would especially benefit more basic users (who may not realize they can c/p and Ctrl+k in the first place) by making the WordPress experience friendlier and faster for them.

**Comment by jorgefilipecosta** [comment]
Hi @desrosj thank you for bringing this issue to our attention. A question that arises is on links without protocol should we use HTTPS or HTTP as a protocol?
HTTPS is safer and exposes users to fewer risks but it can be an invalid link if the page does not support HTTPS.

**Comment by skorasaurus** [comment]
I'm not able to reproduce this in gutenberg 11.0 and WordPress 5.8. 

Please reopen if you're still to reproduce. 

to reproduce:

create new paragraph block; type in random words, select one of the words, hyperlink it to www.wordpress.org ; highlight that link, and then copy and paste into new block. 

note: gutenberg is automatically prepending http:// to the urls

**Comment by desrosj** [comment]
Thanks @skorasaurus. It makes sense that this has fixed itself as TinyMCE is no longer used under the hood.
