### ISSUE TITLE
Font Size Picker: The selected preset doesn't change to Custom when picking a random value

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18211]
**Describe the bug**
Originally reported in https://github.com/WordPress/gutenberg/pull/18149:

> The selected preset doesn't change to `Custom` when I pick a random value:
> ![Screen Shot 2019-10-31 at 10 39 23](https://user-images.githubusercontent.com/699132/67935738-cb0b6d00-fbca-11e9-9e33-a3de63055cf3.png)

**To reproduce**
1. Run Storybook: `npm run design-system:dev` or open https://wordpress.github.io/gutenberg/design-system/components/.
2. Go to the `FontSizePicker` section.
3. Pick the one named `Default`
4. Change the value of the picker to something which the select box doesn't cover, e.g. 77.
5. Observe that the preset doesn't update to `Custom`.

**Expected behavior**
The selected preset should change to `Custom`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 77

**Comment by Clarity-89** [comment]
@gziolo did you mean `withSlider` component since that's what corresponds to your screenshot? It seems like the slider isn't connected to input/select dropdown because it uses the `onChange` prop directly and not `onChangeValue` function. 

I'm happy to submit a fix for it if that's ok.

**Comment by gziolo** [comment]
@Clarity-89 - feel free to work on it. I didn't investigate closer. It should be easier to integrate. If 2 Gutenberg team members didn't catch it, then it's very unlikely that it's going to be a smooth process for other folks.

**Comment by gziolo** [comment]
It's no longer an issue. I re-tested it.
