### ISSUE TITLE
Testing: Explore possible ways to integrate with React prerelease channels

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18216]
There was an announcement from the React team about official prerelease channels: 

https://twitter.com/reactjs/status/1186721158210576385

https://reactjs.org/blog/2019/10/22/react-release-channels.html

> This post will be most relevant to developers who work on frameworks, libraries, or developer tooling. Developers who use React primarily to build user-facing applications should not need to worry about our prerelease channels.

At first glance, it seems like this is it mostly npm install'ing it and then poking around to make sure nothing explodes? Everything builds, all tests pass, etc.

According to the document, in our case, we would also need to tweak PHP code as well, because we use `react` as an external library in the webpack config and enqueue it using WordPress API. Related PR with `react` version upgrade might be useful here to better explain it:
https://github.com/WordPress/gutenberg/pull/16982

This topic was discussed during the last weekly WordPress core JS chat (link requires registration):
https://wordpress.slack.com/archives/C5UNMSU4R/p1572357832196200

**Comment by lozinska** [comment]
Hi! I would like to work on solving this issue

**Comment by gziolo** [comment]
> Hi! I would like to work on solving this issue

Excellent 👍

**Comment by lozinska** [comment]
Hi @gziolo I have a question, after I went through the link you have posted in a comment above I wonder which PreRelease channel should be implemented for Gutenberg  [Next](https://reactjs.org/blog/2019/10/22/react-release-channels.html) or [Experimental](https://reactjs.org/blog/2019/10/22/react-release-channels.html). Thank you

**Comment by gziolo** [comment]
I guess it applies mostly to `Experimental` but we could cover both as well. It would make it easier to make the decision about upgrading to the next stable version of React when `Next` is well tested.

**Comment by lozinska** [comment]
Ok, thank you!

**Comment by lozinska** [comment]
Hi @gziolo. I have been looking into this issue for the past 2 weeks and I have another question. So far I updated all react 16.9.0 to experimental. I stack on the testing part. I just wonder if I have to write any tests, because it seems that test against updated react package already exist in [this file](https://github.com/WordPress/gutenberg/blob/master/phpunit/class-vendor-script-filename-test.php). Moreover when I try to run tests (npm run test-unit) locally it is failing because of   

`>wp-scripts test-unit-js --config test/unit/jest.config.js`
No test found, exiting with code 1
I just wonder if it has to do with testing updated packages.
Thank you

**Comment by gziolo** [comment]
@lozinska, can you share your code, it's hard to tell what might go wrong otherwise. If you run the same tests on masters you should see tons of them. It feels like your setup doesn't quite work as it should.

**Comment by lozinska** [comment]
Hi @gziolo. Here is my code snippets where I updated react version. 
package.json
<img width="341" alt="r1" src="https://user-images.githubusercontent.com/49209351/72744853-5f5aef80-3b7c-11ea-8870-5aa35de435d9.PNG">

class-vendor-script-filename-test.php
<img width="336" alt="r2" src="https://user-images.githubusercontent.com/49209351/72744909-80234500-3b7c-11ea-8edd-83b3a058ce62.PNG">

And this is a screenshot of the problem I'm running into while i execute command 
`npm run test-unit`

**Comment by lozinska** [comment]
@gziolo another question is: after I update React version to "experimental" do I have to create any additional test that will check failures towards updates in "experimental"? Thank you

**Comment by gziolo** [comment]
I have no idea what might be wrong here. You probably need to start with the fresh `master` and debug for each dependency updated.

**Comment by gziolo** [comment]
Let's close this one since we depend too much on React Native releases which are always delayed a few weeks compared to the React core releases.
