### ISSUE TITLE
Column Block:  Toolbar positioning for wide and full images inconsistent

### ISSUE THREAD

**Issue by mikeyarce** [WordPress/gutenberg#18217]
**Describe the bug**
When adding Wide and Full-Width images inside the Column Block, the toolbar positioning is not consistent.

**To reproduce**
Steps to reproduce the behaviour:
1. Create a new Post
2. Add a Column Block with at least 2 columns
3. Add a Full Width image in one column
4. Add a Wide image in another column
5. The toolbar positioning seems off

**Expected behaviour**
The Toolbar should be aligned the same way.

**Screenshots**
Normal Image:
<img width="510" alt="Screen Shot 2019-10-31 at 9 00 51 AM" src="https://user-images.githubusercontent.com/3220162/67964122-f9824b80-fbbc-11e9-9615-69a6038b043e.png">

Wide Image:
<img width="469" alt="Screen Shot 2019-10-31 at 9 00 42 AM" src="https://user-images.githubusercontent.com/3220162/67964151-0606a400-fbbd-11e9-9599-acf8ed226dfd.png">

Full Width Image:
<img width="488" alt="Screen Shot 2019-10-31 at 9 00 47 AM" src="https://user-images.githubusercontent.com/3220162/67964177-0e5edf00-fbbd-11e9-99f0-5e5e9971bab1.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

I have a PR in place to fix the position of the block-mover which is currently underneath the toolbar:  https://github.com/WordPress/gutenberg/pull/18196 

Once that PR is merged, what should be the position for the toolbar?  I'm thinking they should all be like the "normal" image screenshot above.

**Comment by talldan** [comment]
Hi @mikeyarce. I always thought that the slightly inset position of the toolbar was on purpose 😄 

I've added the `Needs Design Feedback` label, it'd be great to get an opinion from the design team on this.

**Comment by karmatosed** [comment]
I am fairly sure it's not on purpose, let's mark as bug and get fixed :)

**Comment by mikeyarce** [comment]
@karmatosed take a look at my proposed PR:  https://github.com/WordPress/gutenberg/pull/18196
Happy to make changes and with any feedback you might have! :)

**Comment by youknowriad** [comment]
This is not valid anymore.
