### ISSUE TITLE
Add theme support option to disable gradient picker

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#18213]
In the same way that there is an option `add_theme_support('disable-custom-colors');`.

**Comment by spacedmonkey** [comment]
Related: #18171 #17774

**Comment by talldan** [comment]
It looks like this was added as an experimental feature only very recently:
https://github.com/WordPress/gutenberg/commit/5e68cdce7c8ed4c5fb831c4ccd89ade97524f073#diff-bda1f53deac273d361a56c63a5b90adeR157

@jorgefilipecosta Any further info the reporter should be aware of for this issue?

**Comment by jorgefilipecosta** [comment]
Hi @markhowellsmead, as @talldan referred this feature is now available in an experimental state.
It is possible to completely disable gradients using:
```
add_theme_support( '__experimental-editor-gradient-presets', array() );
add_theme_support( '__experimental-disable-custom-gradients', true );
```.

Thank you for reporting this issue!

**Comment by markhowellsmead** [comment]
Great! Thanks @jorgefilipecosta!

**Comment by Ahrengot** [comment]
For anyone wondering why the above snippet no longer works. It's been changed to:

```
add_theme_support('editor-gradient-presets', []);
add_theme_support('disable-custom-gradients', true);
```

Not sure when that happened, but removing the `__experimental-`-prefix works for me using WordPress 5.4

**Comment by jorgefilipecosta** [comment]
Hi @Ahrengot, thank you for sharing the new code, since the original discussion the APIs were stabilized and now the experimental prefix should not be used.

**Comment by ooksanen** [comment]
These don't seem to work with the latest plugin. Functions as expected when plugin is disabled.

**Comment by EmSixTeen** [comment]
> For anyone wondering why the above snippet no longer works. It's been changed to:
> 
> ```
> add_theme_support('editor-gradient-presets', []);
> add_theme_support('disable-custom-gradients', true);
> ```
> 
> Not sure when that happened, but removing the `__experimental-` prefix works for me using WordPress 5.4

Want this too and just tried this, but doesn't seem to be working here - with or without the current Gutenberg (13.3.0) plugin.

A little disconcerting if this isn't just user error on my part but is instead just something else that's now defunct.

**Comment by markhowellsmead** [comment]
This option is now best controlled using the theme.json file. https://fullsiteediting.com/lessons/theme-json-color-options/#h-how-to-disable-gradients

**Comment by EmSixTeen** [comment]
I don't particularly want to convert my sites to using theme.json just to disable gradients, especially when the option was already previously there.

**Comment by markhowellsmead** [comment]
Then I'd suggest opening a new ticket to address the fact that the following theme support definitions don't work for you. (This ticket has been closed since December 2019.)

```
add_theme_support('editor-gradient-presets', []);
add_theme_support('disable-custom-gradients', true);
```

**Comment by via-lars** [comment]
@EmSixTeen did you open a new ticket? which?

Apart from disbabling gradients not working for me without theme.json I noticed disabled colors are still delivered as CSS variables inline in HTML wp-head `global-styles-inline-css`
