### ISSUE TITLE
Font Size Picker: `disableCustomFontSizes` doesn't remove `Custom` option from the select box

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18212]
**Describe the bug**
Originally reported in #18149:

> The example which has the custom sizes disabled works only partially, since, in the dropdown, there is still 
>  an option labeled `Custom`:
> ![Screen Shot 2019-10-31 at 10 40 33](https://user-images.githubusercontent.com/699132/67935891-0ad25480-fbcb-11e9-8bee-8f0ebc51172f.png)
> 

**To reproduce**
1. Run Storybook: `npm run design-system:dev` or open https://wordpress.github.io/gutenberg/design-system/components/.
2. Go to the `FontSizePicker` section.
3. Pick the one named `Without Custom Sizes`
4. Check the select box.

**Expected behavior**
There is no `Custom` option when `disableCustomFontSizes` flag is passed to `FontSizePicker` component.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 77

**Comment by brentswisher** [comment]
Thanks for filling these followups, this one was already reported in #17941 and has a fix in progress in PR #18049 so I'm going to close this one.
