### ISSUE TITLE
Code Syntax block - background color in non-focused state

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1821]
Would like to ask if you could add background-color for code block in backend ?
Something like: background-color: #f5f5f5; makes a great difference. At least when there is no pointer focus on code block.

And if you can style "pre" tag the same as "div[data-type="core/code"] textarea". For backward compability when people remove syntax plugins, or similar.

If you find better tittle for issue be free to change it.

**Comment by karmatosed** [comment]
I think for now this would be something up to the theme. I totally get the need you have for this, but we can't have every single thing in v1 of Gutenberg. Maybe it's even something for a plugin.
