### ISSUE TITLE
Block Toolbars: Reposition block toolbars to ensure they render within the viewport

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#18223]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/191598/67975730-0b7ae300-fbeb-11e9-9efb-764d92ed083b.png">

Depending on the viewport width, the placement of the block, and the length of the toolbar — its not uncommon to see the toolbar renders outside the visible space on the screen. Right now this adds a horizontal scrollbar to the entire document.

Instead, I'd expect the toolbar to move itself to ensure it displays within the viewport. Something like this:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/191598/67975897-5f85c780-fbeb-11e9-9215-e41073f9ea33.png">

**Comment by morgandruscarr** [comment]
Yes, that's a great idea.

**Comment by jasmussen** [comment]
This is fixed by #18685 as of https://github.com/WordPress/gutenberg/pull/18685#issuecomment-574090474
