### ISSUE TITLE
I didn't find the navigation block in the dev version 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#18242]
Hi, 

I am planning to start contributing to [the navigation block project ](https://github.com/WordPress/gutenberg/projects/31), I have successfully setup the environment following the steps  [here](https://developer.wordpress.org/block-editor/contributors/develop/getting-started/) but I noticed that there's no Navigation block with it: 

![Screen Shot 2019-11-01 at 9 52 34 PM](https://user-images.githubusercontent.com/39377174/68056186-c8a43280-fcf2-11e9-866e-0ed6f8b11f03.png)

I am a new contributor so I must be missing a lot of things, is that block in another branch? 
I read the documentation but I didn't find anything useful for this 

Thanks

**Comment by senadir** [comment]
Hello Abderrahman, I'm really glad that you're considering contributing to Gutenberg, contributing had really a huge effect in my life but I know how tough it can be when you get started.

For your question, the Navigation block is available under the experimental features
https://github.com/WordPress/gutenberg/blob/85b07292622255f268c8a51c7a856344f3dac957/packages/block-library/src/index.js#L179-L180

So you need to enable that by going to Gutenberg -> Experiments, this [WP Tavern article](https://wptavern.com/gutenberg-6-5-adds-experimental-block-directory-search-to-inserter-and-new-social-links-block) might aid you as well.

In the future, if you have any questions regarding the core development of Gutenberg, you can always ask at the [`#core-editor` channel on the Making WordPress Slack.](https://wordpress.slack.com/messages/C02QB2JS7)

I believe this answers your question, so I'm going to close this ticket for now, feel free to reopen it if you have any questions.
Good luck contributing and have a great day.
