### ISSUE TITLE
Cannot add new block in editor interface if enter is not pressed in paragraph block

### ISSUE THREAD

**Issue by jarretc** [WordPress/gutenberg#18250]
Replication

1. Create a new post 
2. Add text into default paragraph block, click outside of the paragraph block without hitting Enter
3. A new block cannot be added below the paragraph block in the editor window

![gutenberg-paragraph](https://user-images.githubusercontent.com/1584764/68081460-9fa3a080-fdcb-11e9-98e3-8c9d986fa3bc.png)

However, it appears that when adding any other block type, the + button on the left hand side shows up to add a new block when no action is taken in most recent block

![gutenberg-image](https://user-images.githubusercontent.com/1584764/68081462-a6321800-fdcb-11e9-92d9-91437fcb2a9d.png)

Tested in WP 5.2.4 with default editor as well as Gutenberg plugin ( 6.8.0 )activated

**Comment by jorgefilipecosta** [comment]
Hi @jarretc,
Thank you for reporting the issue you faced.
The inserter you see at the side only appears when the last selected block is not a paragraph.
When the last selected block is a paragraph and you want to insert a block without pressing enter you can use the inserter located at the top:
![Nov-20-2019 19-33-39](https://user-images.githubusercontent.com/11271197/69362082-baa85880-0c85-11ea-940c-17bc71b0fbf7.gif)

If you think this issue deserves additional discussion feel free to leave a comment.

**Comment by jarretc** [comment]
Hi, not sure what your gif is meant to show as that isn't related to this specific issue. I realize that you can add a block above the paragraph block but then you have to move it down below the paragraph block where Enter wasn't pressed.

I realize that typically a user would press Enter after they are done typing but it may not always be the case. If you copy a section of text from a different window that doesn't have any blank lines, paste it into the Paragraph block, you are still unable to create a new block below that paragraph block. You have to click inside of the block where the text was just pasted and then hit Enter to get the block insertion icon.

Just seems like it would be simpler to allow a block to be added below a Paragraph block without having to force an additional action into the workflow.
