### ISSUE TITLE
Inconsistent margin styling on audio blocks

### ISSUE THREAD

**Issue by emilyatmobtown** [WordPress/gutenberg#18255]
**Describe the bug**
A [styling bug](https://core.trac.wordpress.org/ticket/48448) was reported on Trac for Twenty Sixteen, but exists independent of theme. No bottom margin exists on audio blocks, which is inconsistent with other blocks, such as quote and image blocks.

**To reproduce**
1. Add an audio block to a post.
2. Add another block below the audio block.
3. Publish and view the page.
4. See the lack of margin below the audio block.

**Expected behavior**
I expect to see a margin below the audio block to be visually consistent with other blocks.

**Screenshots**
As provided by the bug reporter on Trac #48448:
![audio-no-margin-bottom](https://user-images.githubusercontent.com/24902269/68091762-7164a600-fe49-11e9-8d57-e36e1c32e337.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6 (18G103)
 - Browser: Chrome 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
- Bug was tested with Block Library version 2.7.0

**Comment by emilyatmobtown** [comment]
**For further context:**
The quote block provides bottom margin to .wp-block-quote in its theme.scss. The image block provides bottom margin to .wp-block-image in its style.scss. The audio block provides no bottom margin to .wp-block-audio in its block-library stylesheets, leaving it butting up against the following block, unless overridden by a theme.

Was the audio block developed without margin for a reason or is a patch needed?

**Comment by carolinan** [comment]
I am closing this as solved, a bottom margin has been added to the block styles.
