### ISSUE TITLE
Block shortcuts change order after inserting multiple of same type

### ISSUE THREAD

**Issue by jarretc** [WordPress/gutenberg#18251]
![gutenberg-shortcuts](https://user-images.githubusercontent.com/1584764/68081552-ee9e0580-fdcc-11e9-8cfa-5466cffffdc0.png)

I'm not quite sure what to call the 3 icons on the far right of the new block input other than shortcuts, see above image for reference ( media, heading, page break )

Replication

1. Create a new post
2. Hover over default paragraph block below title block, click the 2nd icon
3. Repeat step 2 a few times, eventually you'll see the icon move into the 1st position

This doesn't appear to happen when inserting multiple page breaks however assuming the page break is the 3rd icon. The issue only appears to happen between the 1st and 2nd icons

Tested in WP 5.2.4 with default editor as well as Gutenberg plugin ( 6.8.0 ) active

**Comment by swissspidy** [comment]
These shortcuts show the most commonly blocks, ordered by how often you've used them. So the icon moving to first position after using it multiple times is expected behavior.

**Comment by jarretc** [comment]
Thanks for the response, I suppose that makes sense! Will close out this issue
