### ISSUE TITLE
"Move to Trash" with metaboxes prompts about unsaved changes, 500 server error

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18269]
**Describe the bug**

The "Move to Trash" button does not work very well when meta boxes are present on the page:

1. The user is prompted about there being unsaved changes
2. In the browser Developer Tools Network log, a 500 error is shown for a failed request

It appears this is largely caused by a combination of:

- The meta box values try to save at the same time the browser redirect of a trashed post tries to occur (the meta box save occurs as a separate step after the "default" post save)
- The meta box save attempt fails because the post is already trashed

https://github.com/WordPress/gutenberg/blob/3d2b41a895a267650bbc7355a80f16ef0eacf87b/packages/edit-post/src/components/browser-url/index.js#L58-L66

```json
{"code":"wp_die","message":"You can&#8217;t edit this item because it is in the Trash. Please restore it and try again.","data":{"status":500},"additional_errors":[]}
```

**To reproduce**

1. Use an addon which includes a save step for meta boxes in the post editor (e.g. AdvancedCustomFields with fields present on the post editor)
2. Navigate to an existing post
3. Press "Move to Trash"
4. See prompt, failed network request

**Expected behavior**

The user is redirected without a prompt or error'd request.

My expectation is that the save request for meta boxes would be skipped when the user tries to save the post, or it must occur prior (or at least prior to the saving of the status to "trash", since as noted in the error message, post values cannot be saved when the post is trashed).

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15 (19A603)
 - Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Additional Context**

Most of the relevant code here is contained in the `BrowserURL` component (responsible for redirecting after trashing a post), the `trashPost` action (which sets the status and saves the post), and the `edit-post` "effect" for saving meta box values after the default post save procedure.

https://github.com/WordPress/gutenberg/blob/3d2b41a895a267650bbc7355a80f16ef0eacf87b/packages/edit-post/src/components/browser-url/index.js#L48-L51

https://github.com/WordPress/gutenberg/blob/3d2b41a895a267650bbc7355a80f16ef0eacf87b/packages/editor/src/store/actions.js#L324-L365

https://github.com/WordPress/gutenberg/blob/3d2b41a895a267650bbc7355a80f16ef0eacf87b/packages/edit-post/src/store/effects.js#L51-L70

**Comment by paaljoachim** [comment]
I see a merged PR in relation to this issue.

Should it be closed?
@WordPress/gutenberg-core

**Comment by adamsilverstein** [comment]
@paaljoachim yes, as far as I can tell this issue was resolved by https://github.com/WordPress/gutenberg/pull/17427 along with https://github.com/WordPress/gutenberg/issues/17426. Closing as resolved.
