### ISSUE TITLE
"Copy permalink" button only works when padding area is clicked

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#18274]
**Describe the bug**
On the permalink options above the title, the "copy permalink" on the very left side only works on mouse clicks when clicking into the padding area between the SVG icon and the border.
It does work with focusing the element via the keyboard and hitting enter.

**To reproduce**
1. Go to a saved post or page, where a permalink is available.
2. Click on the title, the permalink options appear.
3. Click on the "copy permalink" button on the left, exactly on the SVG image.
4. The permalink options close, but the permalink was not copied.
5. Open the permalink options again by clicking on the title.
6. Now repeat to click on the "copy permalink" button, this time in the white space between the SVG image and the border of the button. The permalink get's copied and the options bar doesn't close yet.

**Expected behavior**
Clicking on the icon itself should also copy the permalink and not close the options bar immediately.

**Gif**
![Copy permalink issue](https://user-images.githubusercontent.com/7585600/68145183-8585d180-ff35-11e9-8746-4b253e3b4a7d.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Firefox 70

**Additional context**
- WordPress 5.3-RC3-46639
- Gutenberg Plugin NOT installed

**Comment by phpbits** [comment]
I was able to replicate the issue on FireFox as well. Version 69.0.1 and 70.0.1

**Comment by youknowriad** [comment]
This UI has been removed in favor of the sidebar panel. Thanks.
