### ISSUE TITLE
Rich Text Controls buttons are broken when the content contains an <a> element

### ISSUE THREAD

**Issue by zohar** [WordPress/gutenberg#18271]
Using Gutenberg I have a text paragraph with an <a> element inside of it.
If I choose the entire paragraph and use one of the Rich Text Controls (code, strikethrough...) the result is at least 3 different elements - one before the <a> element, one wrapping only the text of the <a> element and a third one around the third chunk of text.

See the attached image.

**To reproduce**
1. Edit a post with Gutenberg
2. Select a text which has link in it (e.g. "This is a normal text paragraph. [It has a link](http://example.com). Then some more text.")
3. Switch to HTML view

**Expected behavior**
The whole selection should be under a single element (whether it's < code >, < s >, < cite >...)

**Screenshots**
![Add New Post ‹ Healthline — WordPress](https://user-images.githubusercontent.com/109613/68127636-8ce9b280-ff16-11e9-8632-1b4e6aebfb63.jpg)

**Additional context**
WP version 5.2.4

**Comment by ellatrix** [comment]
I can't reproduce this. I get the following HTML:

```html
<p><s>This is a normal text paragraph. <a href="http://example.com/">It has a link</a>. Then some more text.</s></p>
```

**Comment by kirillrocks** [comment]
> I can't reproduce this. I get the following HTML:
> 
> ```
> <p><s>This is a normal text paragraph. <a href="http://example.com/">It has a link</a>. Then some more text.</s></p>
> ```

This is what I'm getting on a totally new WP environment, version 5.2.4.

I hyperlinked "That is the test" and then I selected the whole row and added Code.
![image](https://user-images.githubusercontent.com/24845797/69633886-c024ea80-1059-11ea-83cb-cd026e5f88f1.png)

**Comment by zohar** [comment]
I just checked on Wordpress 5.3 - the problem seems to be fixed. On 5.2.4 I still experience it.
