### ISSUE TITLE
Delete/Trash and Setting/Cog icon not visible/accessible on mobile

### ISSUE THREAD

**Issue by turtlepod** [WordPress/gutenberg#1828]
It's visible on hover, cannot access it on mobile/touch device

**Comment by karmatosed** [comment]
There are a number of issues on mobile as the experience hasn't been optimised for it yet. Let me label this but we do need an approach to mobile in entirety.

**Comment by jasmussen** [comment]
This should be fixed! They are in an ellipsis menu now.
