### ISSUE TITLE
Navigation Menu: Nested menu-items are prepended instead of appended

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#18299]
**Describe the bug**
A new toolbar button was recently added to navigation menu items, to allow adding other nested menu items underneath them.

![Screen Shot 2019-11-06 at 5 50 17 pm](https://user-images.githubusercontent.com/677833/68287861-623a5e00-00be-11ea-8ac5-a951189d3d5b.png)

However, this seems to prepending the nested blocks. Instead they should be appended. It's pretty apparent when using the button to build a menu that the behaviour isn't correct, the user has to add their menu in reverse, or add the items and then re-order them.

**To reproduce**
1. Add a navigation menu block (enable it as an experimental feature first).
2. Add a menu item to the navigation menu.
3. Try adding multiple nested menu items within the menu item created in step 2.
4. Note that the button prepends blocks

**Expected behavior**
The button appends blocks

**Comment by getdave** [comment]
I tested this and items are being appended. It looks like this has been resolved @talldan do you agree?

![Screen Capture on 2019-11-06 at 17-22-52](https://user-images.githubusercontent.com/444434/68321751-29988580-00ba-11ea-9df4-a1920188676f.gif)

**Comment by talldan** [comment]
@getdave Hmm, so there's now an appender there as well as the toolbar button. When I created this there wasn't an appender, but the issue with the toolbar button still seems present.

Here's a gif of the issue I'm referring to:
![prepending-toolbar-button](https://user-images.githubusercontent.com/677833/68441586-91111b00-0209-11ea-89fe-fd17c04fae3c.gif)

We may need to reconsider how that toolbar button works. It's pretty awkward to use.

**Comment by draganescu** [comment]
Yes this is happening because the position is hardcoded:

```insertBlock(
	blockToInsert,
	0,
	clientId,
);```

that zero, should be a call to something that figures the last position.

**Comment by getdave** [comment]
I got this.
