### ISSUE TITLE
Newest version on github doesn't work for me...

### ISSUE THREAD

**Issue by raspi0124** [WordPress/gutenberg#1830]
I installed the newest version of gutenberg at 12:42(European time).
but when I active it, I can see gutenberg menu at sidebar on admin panel, but I can't make new post with it..
and even demo doesn't work..
is it because of this plugin or my site?
And when I install it from WordPress plugin directory, it's work.
![image](https://user-images.githubusercontent.com/22224201/28014679-e1ecc1cc-656d-11e7-8f85-808b237a2786.png)

**Comment by nylen** [comment]
Are there errors in your browser console?

Did you follow the instructions at https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#installing--building-the-plugin ?  Instlling the repository is not enough to make the plugin work.

**Comment by mtias** [comment]
Closing as lack of information.
