### ISSUE TITLE
Navigation Block: Caret isn't visible when menu item is selected but has no text

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#18301]
**Describe the bug**
When adding a new navigation menu, it's not particularly clear whether the user can type, since no caret is visible when adding a block or when the text field is empty but focused.

**To reproduce**
1. Add a navigation menu (it'll need to be enabled as an experimental feature first.
2. Add a menu item to the nav menu
3. Observe that the caret isn't visible

**Expected behavior**
A caret should be visible, indicating to the user where text will appear if they type.

**Screenshots**
![Screen Shot 2019-11-06 at 6 07 58 pm](https://user-images.githubusercontent.com/677833/68289264-c78f4e80-00c0-11ea-9c3f-1bdc723f2856.png)

**Desktop (please complete the following information):**

**Additional context**
- Tested in Chrome, Mac OS X

**Comment by getdave** [comment]
@talldan @karmatosed Is this still an issue now that the link UI is auto focused? Or is that just masking the problem. Is the question also whether the Link UI _should_ auto focus?

![Screen Capture on 2019-11-06 at 15-30-21](https://user-images.githubusercontent.com/444434/68312116-7bd1aa80-00aa-11ea-9d6d-a859fc113785.gif)

**Comment by mtias** [comment]
I don't think it's related to auto-focus, since if you focus on the label and remove the text the cursor also disappears.

**Comment by talldan** [comment]
It doesn't seem to be an issue now. Not sure what fixed it.
