### ISSUE TITLE
Navigation Block: Improve initial state.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#18307]
Right now adding a navigation block loads all top level pages. We should instead use the placeholder patterns to allow users to choose whether they want to start with existing pages, import an existing menu, or start from scratch.

@melchoyce created this mockups some time ago to address this need:

Some older mockups around the placeholder:

![image](https://user-images.githubusercontent.com/2846578/63187747-a3762100-c02d-11e9-8263-0e647345b85e.png)

![image](https://user-images.githubusercontent.com/2846578/63187781-b688f100-c02d-11e9-9494-5ac43010040e.png)

![image](https://user-images.githubusercontent.com/2846578/63187841-d7e9dd00-c02d-11e9-96ec-7e65d1a99ec4.png)

---

I see two separate tasks here:

- [ ]  Add placeholder component with initial options for load existing top-level pages (current behaviour) and start from scratch (empty menu).
- [ ] Add ability to import an existing menu (if one exists).

**Comment by karmatosed** [comment]
I totally agree there should be a better placeholder. I will assign this to myself and work on some mockups today.

**Comment by getdave** [comment]
Happy to wrangle the dev on this one once we have a design.

**Comment by karmatosed** [comment]
I have been going backwards and forwards on this a bit tonight. I have settled I think on a potential direction which either works or can serve as idea fuel for an iteration tomorrow.

If we can link to existing menus here is my suggestion:

<img width="758" alt="navigation-placeholder" src="https://user-images.githubusercontent.com/253067/68344269-83af4000-00e6-11ea-8516-b2edd5db51a1.png">

I didn't add a skip as for me the 'skip' is to create a blank page. I actually don't like the 'fill it out with all pages' option, but maybe that could be the default if people prefer there. Maybe it's an option though to 'add all pages'.

The second is perhaps the easiest to do in version one if accessing menus isn't easy:

<img width="758" alt="Frame 5" src="https://user-images.githubusercontent.com/253067/68344326-accfd080-00e6-11ea-93d8-bd01bebf8478.png">

**Comment by draganescu** [comment]
@getdave I think the second option above is what we need at this stage right?

**Comment by getdave** [comment]
I would agree @draganescu.

It would be good it @mtias could confirm he's happy to skip the Menu piece for now, we can split that into a separate Issue. 

Thanks for the design and thinking @karmatosed 👍

**Comment by mtias** [comment]
> It would be good it @mtias could confirm he's happy to skip the Menu piece for now, we can split that into a separate Issue.

Yes, happy with that.

I have some feedback on the design.
* The button text seems a bit too long and repetitive ("Create..."), can we simplify?
* It should also be possible to fit the two buttons in a row with terser actions.

**Comment by karmatosed** [comment]
<img width="758" alt="Frame 6" src="https://user-images.githubusercontent.com/253067/68388496-b134d180-0158-11ea-88f1-6401cc9b32fe.png">

This is a suggestion but we can have a copy review also.

**Comment by mtias** [comment]
Maybe the first one could say "All Top Pages" or similar.

**Comment by michelleweber** [comment]
I feel like I want the button and link to say "Create page menu" and "Create empty menu" for parity and clarity. 

Even better, maybe, would be something like "Create page menu" and "Create custom menu," with updated text above that says something like "Create a menu with all of your site's current pages, or build a custom menu with a mix of links."

(Which also makes me just want two buttons, to show that these are two different but equal options, but I'm not a designer :) )

**Comment by getdave** [comment]
OK no problem. Unless @karmatosed gets here first, I'll give @mtias's feedback a go and she can critique it and provide amendments as required.

**Comment by getdave** [comment]
I've created this PR with a reasonable approximation of the design. Feel free to leave further feedback there for me to action.

https://github.com/WordPress/gutenberg/pull/18363

@mtias I have a technical query that I could do with some assistance on if possible.

**Comment by mapk** [comment]
I remember [Matt saying we're getting away from calling this a "menu"](https://youtu.be/LezbkeV059Q?t=1276). Should this be something we reflect in this work? "Menu" does feel nice in context to how the wording is structured, but if moving away from that word is a goal, we should align that here too.

**Comment by shaunandrews** [comment]
Worked up a few more ideas around the Navigation block's initial state. The first uses two buttons with a skip to let you choose from either your existing pages or existing menus (if one or more exists):

![nav initial state 1](https://user-images.githubusercontent.com/191598/68408920-39fd3e80-0154-11ea-9529-3185d446acbb.gif)

The second mockup uses radio buttons to outline all the available options:

![nav initial state 2](https://user-images.githubusercontent.com/191598/68409253-c0b21b80-0154-11ea-9e3c-0fa446a16928.gif)

The third mockup simplifies things down to adding all top-level pages, a dropdown for existing menus (if they exist) and a skip button:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/191598/68409486-256d7600-0155-11ea-8414-0243bee06aef.png">

**Comment by shaunandrews** [comment]
After posting my comment above, I refreshed the page and realized I didn't see a bunch of comments. (Never trust Github to be up-to-date.)

That said, here's another option we could consider:

![nav initial state 3](https://user-images.githubusercontent.com/191598/68410401-a8430080-0156-11ea-8393-2a1332171c98.gif)

**Comment by getdave** [comment]
So as things stand for MVP it looks like we're going to ship with [this implementation](https://github.com/WordPress/gutenberg/pull/18363#discussion_r344164672). We can then iterate towards:

* Shaun's designs.
* Adding Menus

...in follow up PRs.
