### ISSUE TITLE
Navigation Block: highlight items missing a URL

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#18305]
In the navigation menu block, it's possible to have a menu item without a URL set. There's nothing in the UI that indicates a menu doesn't have a link set.

![image](https://user-images.githubusercontent.com/548849/68293088-8762a880-008d-11ea-9c82-d4e117289fbd.png)

It'd be great to indicate that — could be as simple as a red bottom border on the item.

Likewise in this view, the link item in the toolbar looks the same way whether there's a URL set or not.
![image](https://user-images.githubusercontent.com/548849/68293160-aa8d5800-008d-11ea-8bed-93070c0ceef6.png)

cc @shaunandrews @karmatosed

**Comment by retrofox** [comment]
> It'd be great to indicate that — could be as simple as a red bottom border on the item.

Wondering what happens when the bgc is red? 😆 

What do you think about setting the same color as the item link?
