### ISSUE TITLE
Navigation Block: Reduce toolbar options for menu item

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18318]
Right now you see a lot of options for menu items that I think could be reduced.

![nav-toomuch](https://user-images.githubusercontent.com/253067/68313265-2f876a00-00ac-11ea-98fe-30b23b35e38d.png)

I would suggest all 3 are removed.

**Comment by mtias** [comment]
Inline image is useful if you want to add an icon before the text. I'd probably only remove the inline code. (Also this can be extended by plugins.)

**Comment by MDWolinski** [comment]
Removing any or all of these options reduces the ability of the user to format their inline paragraph text in the wysiwyg environment, unless these options were added to another place on the interface.

To me, we would need to expand this menu to allow additional inline text formatting such as: `Underline`, `Superscript`, and `Subscript` which would match some functionality of the classic editor.

However, should that be baked into core or is this menu able to be added to by Plug-ins where users would have to add a Superscript plugin to add that capability.

**Comment by karmatosed** [comment]
A good decision here is then to remove inline code. I am removing feedback and marking this to be moved to a PR.

**Comment by karmatosed** [comment]
Wrongly closed by issue mis-numbering.

**Comment by MDWolinski** [comment]
I still don't understand the logic for removing Inline Code from the formatting menu.

But even worse, I don't understand why have a drop down menu with only two options on it? You are literally 1 button on the main NavigationLink away from not needing a drop down menu.

**Comment by karmatosed** [comment]
@MDWolinski  happy to chat about this more, it's closed because the extending work has been done on this now. Inline code I do stand by being not a common case, that said would you be able to give a clear case where you feel this would be used and we can review? As far as allowing additional, if I am understanding there is now the option to extend so that can be done in an awesome plugin.

**Comment by MDWolinski** [comment]
@karmatosed While I appreciate the goal of making the interface as tight as possible, a WYSIWYG editor has just a handful of inline code formatting options that have valid uses in blogging. While I don't necessarily have blog post examples at hand, you see `Inline Code` used heavily in comments and Slack.

![Code Used in Slack](https://user-images.githubusercontent.com/22196395/72003635-ca6d0380-3217-11ea-8a4b-1549534b9c64.png)

To regress this functionality, which is already built in, to a plug-in seems like a heavy-handed approach just to add `<code>` and `</code>` into the code.  (See, I just used it for that sentence.) I'd prefer to reduce the number of plug-ins needed to necessary ones and not have to install a handful just to handle WYSIWYG functionality.

Blogs that deal with technical / development topics may utilize the `Inline Code` heavily.

To that end, I'd also argue for the inclusion of Sub/Superscript which is beneficial for creating footnotes, etc in long form/educational posts.

**Comment by MDWolinski** [comment]
Also, while I've not reviewed the code submitted for this issue, at glance it seems to limit the menu to specific items and is not capable of being extended.  But I'm not holding a hardline on that.

**Comment by mtias** [comment]
@MDWolinski this issue only applies to rich formatting when writing a label for a menu item, not for rich text in general (like in paragraphs, quotes, etc).

**Comment by MDWolinski** [comment]
@mtias @karmatosed Doh!  I get it now. 🙄

**Comment by mtias** [comment]
Hah, no worries! :)
