### ISSUE TITLE
Consider different icon for menu item

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18316]
The menu icon confused me as it was very similar to the Star Trek one and on seeing for a single menu item I was unsure what it meant.

![nav-startrek](https://user-images.githubusercontent.com/253067/68312591-32ce2600-00ab-11ea-9d9f-62289848ce19.png)

I was so unsure, I ended up clicking it (which was a weird experience as didn't do anything). If you have the sidebar open you can see what it is, but it should be readable without that.

**Comment by shaunandrews** [comment]
I don't think there is an icon that shouts "Navigation", but the current one seems to be the best I've seen so far. Regardless of what icon we use, I think it's going to be a little obtuse for some people.

That said, I'm not sure the icon is super important for the majority of use-cases with the Navigation block.

**Comment by Zalbatros** [comment]
Would it help if the icon looked a little more like a compass? Maybe make the arrow smaller, put a circle around it. Or maybe just rotating it a couple of degrees counter clockwise will do the trick?

**Comment by karmatosed** [comment]
As this seems to work for others, let's close this now.
