### ISSUE TITLE
Navigation Block: sub-menu items design

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#18310]
The design of the sub-menu should correspond to what is shown on the front-end (right now it's a dropdown on hover/focus). The editor is showing just an indented list:

![image](https://user-images.githubusercontent.com/548849/68295503-d828d000-0092-11ea-975d-0e62062c336b.png)

This is a block that should have opinionated styles (assigned to `theme.scss`) that themes can opt into.

**Comment by karmatosed** [comment]
💯 for this. I also notice that for example on front it shows extra characters

![nav-front-style1](https://user-images.githubusercontent.com/253067/68311456-7aec4900-00a9-11ea-87f4-16cc21dc4ce8.png)

**Comment by getdave** [comment]
Can I clarify the intent here:

Are we saying we want the Editor and Theme (front of site) to utilise a common set of "opt in" styles for the Nav Block whichL

1. Ensure it's a _horizontal_ nav on large screens (presumably "stacked" on small screens?).
2. Create dropdown menus for sub items.

Questions: 

* what about sub-sub items? 
* how do sub menus work/look on small screens?

**Comment by retrofox** [comment]
> for this. I also notice that for example on front it shows extra characters

is ti defined by the list-style?

**Comment by retrofox** [comment]
> > for this. I also notice that for example on front it shows extra characters
>
> is it defined by the list-style?

No, [it is not](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation-menu/style.scss#L101).

**Comment by karmatosed** [comment]
Noting the bit 'to do' on this is reflecting in the editor itself.

**Comment by karmatosed** [comment]
A few points on this. Right now there is some very opinionated styling as default, I am not sure if we reflect that but having a way to avoid this, for example, would be great:

![image](https://user-images.githubusercontent.com/253067/69884110-c4a60900-12ce-11ea-850d-2f059e76baf5.png)

More in: #18830

I wonder could we have something like this:

![image](https://user-images.githubusercontent.com/253067/69884122-d8516f80-12ce-11ea-921b-72d5ce6931a5.png)

I think directly having the arrow might be too much as in:

![2](https://user-images.githubusercontent.com/253067/69884251-6299d380-12cf-11ea-8fe7-7e337a856d8f.png)

A suggested middle ground would be a white background:

![1](https://user-images.githubusercontent.com/253067/69884259-6cbbd200-12cf-11ea-8ab9-d315d47498e1.png)

**Comment by karmatosed** [comment]
If we are making this as much like front as possible, potentially adding + within works:

<img width="780" alt="dropdown" src="https://user-images.githubusercontent.com/253067/71112223-f241ec00-21c2-11ea-81c2-184d2ac9014e.png">

**Comment by apeatling** [comment]
Related: https://github.com/WordPress/gutenberg/issues/18830

**Comment by getdave** [comment]
@karmatosed @shaunandrews Just noting that there might be some overlap between this and https://github.com/WordPress/gutenberg/issues/18830. Do we need to take account of that and/or update the designs?

**Comment by karmatosed** [comment]
I took a step to distil this back in design as a point to build from. A few points to note:

- Sub-navigation should appear as actually a sub not indent.
- A dark version of the design should be made once settled.

<img width="931" alt="edit" src="https://user-images.githubusercontent.com/253067/72091237-9cff8300-3307-11ea-90cd-2b61b3a9dd3b.png">

<img width="751" alt="front" src="https://user-images.githubusercontent.com/253067/72091253-a1c43700-3307-11ea-970a-285c2b9dfbea.png">

**Comment by richtabor** [comment]
> I took a step to distil this back in design as a point to build from. A few points to note:
> 
> * Sub-navigation should appear as actually a sub not indent.
> * A dark version of the design should be made once settled.
> 
> <img alt="edit" width="931" src="https://user-images.githubusercontent.com/253067/72091237-9cff8300-3307-11ea-90cd-2b61b3a9dd3b.png">
> 
> <img alt="front" width="751" src="https://user-images.githubusercontent.com/253067/72091253-a1c43700-3307-11ea-970a-285c2b9dfbea.png">

100% agree with this implementation. We'll need to have _some_ opinionated styling to frame the submenu (I'd say arrows are fine). Framing the sub just like the frontend will also improve the experience of adding a submenu link.

**Comment by richtabor** [comment]
Perhaps we should add a label to the "+" inserter within the submenu, to make it clear that this inserter creates another navigation link to the submenu. 

And another note, I am _slightly_ concerned that the inline inserters we use (within this block, Buttons, and Social Links blocks) are indistinctive of the inserters we use to insert top-level blocks. 

It seems one could be confused about what element being added to the page, as the block library doesn't show when you decide to add one here - its automatic. Whereas, selecting the same icon somewhere else would likely pull up the block library. 

Just a thought.

**Comment by apeatling** [comment]
> And another note, I am slightly concerned that the inline inserters we use (within this block, Buttons, and Social Links blocks) are indistinctive of the inserters we use to insert top-level blocks.

I agree with this concern. I think if a representational design can also be used within the editor with the inserters within the sub menus, this would be much improved.

**Comment by mtias** [comment]
>  I think if a representational design can also be used within the editor with the inserters within the sub menus

Not sure I follow what you mean here.

One thing that should be possible is that if a nested blocks inserter only has one child block option, that it lists the name of the block next to the +. So in the case navigation it'd say `+ Add Navigation Link`, in the case of buttons it'd say `+ Add Button`, etc.

**Comment by apeatling** [comment]
> Not sure I follow what you mean here.

I mean matching the new design of the menus in the editor as well as the front end. So that there is greater visual separation between inserters and avoiding the bunching of inserters we currently see.

**Comment by retrofox** [comment]
by your leave, I'm going to start to work on this. :-D

**Comment by frontdevde** [comment]
@karmatosed Could you confirm whether the design you shared here https://github.com/WordPress/gutenberg/issues/18310#issuecomment-572673462 is ready for implementation? 

I'm asking as the issue is still labeled `Needs Design Feedback` and the design feels quite `wireframe-y` (which might be the intended look?). I would just like to make sure we have a clear direction of where we're heading before we potentially start implementing a solution that doesn't solve the UX issues.

**Comment by karmatosed** [comment]
I did intend it to be wireframey as the idea was that we came up with a basic style which would work across as many themes as possible, including dark and light modes. For that reason, I want to avoid things like shadows and too much in-depth styling. It doesn't mean we can't get a tiny bit more opinionated though and I have done some iterations to show states.

## Back hover dark
This is a bit heavy but would swap light / dark for a hover.

<img width="931" alt="backhover-dark" src="https://user-images.githubusercontent.com/253067/72367120-8dab7b80-36f3-11ea-84f9-3360777ac509.png">

## Back focus dark
This brings in the dark only on focus menu

<img width="931" alt="back2" src="https://user-images.githubusercontent.com/253067/72367153-9a2fd400-36f3-11ea-808d-1b47a2c2f991.png">

## Back minimal
This brings in link styling from the theme, so that we bring in for example blue in Twenty Nineteen. Hover is simply underline.

<img width="931" alt="Frame 5" src="https://user-images.githubusercontent.com/253067/72367249-ccd9cc80-36f3-11ea-9dcf-1cc2a6b08436.png">

Important to note in above the appender only appears when 'in' sub menu and only one shows.

Let's move onto the front now and explore beyond 2 levels deep. I started to explore how this could adapt for multiple. It's worth noting the back end will also have same sub menu styling.

## Front all way across

<img width="751" alt="front1-long" src="https://user-images.githubusercontent.com/253067/72367335-f72b8a00-36f3-11ea-91a1-ddd72d4b5abf.png">

## Front second level drop down

<img width="751" alt="frontshort" src="https://user-images.githubusercontent.com/253067/72367356-014d8880-36f4-11ea-941f-c07e12e91d44.png">

## Front second level drop down and minimal styling

<img width="751" alt="frontminimal" src="https://user-images.githubusercontent.com/253067/72367405-0b6f8700-36f4-11ea-803c-66c0e08ce495.png">

There are benefits in the last one as more economical on space and also it can be easily styled, with a dark variation easily done.

**Comment by shaunandrews** [comment]
I think we can simplify even more, reducing the need for the pointers. Here's another take for how the submenus and inserter can work:

![Nav Submenus](https://user-images.githubusercontent.com/191598/72371352-377a1080-36d2-11ea-9703-ddaff11d9663.gif)

When rendered, here's how the navigation submenus would work when hovered:

![Nav Submenu Render](https://user-images.githubusercontent.com/191598/72371375-4365d280-36d2-11ea-97d4-20a53315f369.gif)

**Comment by mapk** [comment]
Looking at these mockups, here's a few thoughts.

1. I like the addition of an arrow in @shaunandrews' mockups for the top level that includes a sub-nav. It's a great visual indicator that there exists a sub-nav.

![Screen Shot 2020-01-14 at 10 56 17 AM](https://user-images.githubusercontent.com/617986/72373133-82892900-36bc-11ea-8d57-6a6c2f7b053d.png)

2. Showing the sub-nav as aligned to the right (and not below) the parent nav item, as proposed in both @karmatosed and @shaunandrews' mockups, feels right and adds visual clarity.

3. Shaun's continuation of the arrow treatment is nice, except it gets a bit tricky at this intersection. Thinking through the block toolbar in relation to the sub-navs gets complex and I'm glad it's being shown here. 

![Screen Shot 2020-01-14 at 10 57 02 AM](https://user-images.githubusercontent.com/617986/72382103-6a6dd580-36cd-11ea-8e88-c207ba29b076.png)

**Comment by karmatosed** [comment]
Regarding the arrow indication, we can merge #18396 maybe into this which is set to bring that in with this iteration - 2 issues with one!

**Comment by frontdevde** [comment]
@karmatosed @shaunandrews @mapk 

Would it be possible to distill the design explorations above into _**one**_ representational design that we can then implement? Mainly thinking about this in terms of efficiency as it can potentially be quite an effort to rework in code if we walk down the wrong direction. Thank you!

**Comment by shaunandrews** [comment]
> Would it be possible to distil the design explorations above into one representational design that we can then implement.

I think of the GIFs I posted yesterday as a distillation of the previous explorations, and would be what I prefer we implement.

**Comment by frontdevde** [comment]
> I think of the GIFs I posted yesterday as a distillation of the previous explorations, and would be what I prefer we implement.

Thank you for providing us with a clear design decision here. 👍 Just linking to the GIFs we'll implement here again for anyone that didn't follow the thread: https://github.com/WordPress/gutenberg/issues/18310#issuecomment-574311244

**Comment by shaunandrews** [comment]
If people get wacky, they can keep adding submenus. Those additional submenus should continue to stack onto the right. Here's what it'd look like with another submenu:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/191598/72451412-e3cafe00-3789-11ea-8b33-b57bb77a501f.png">

**Comment by frontdevde** [comment]
@shaunandrews

Should the colors selected in the navigation color picker propagate to the submenu?

Otherwise it would look something like this (light style variation):
<img width="373" alt="Screenshot 2020-01-16 at 15 46 56" src="https://user-images.githubusercontent.com/1562646/72534655-75646980-3877-11ea-9acb-156b8dc338e4.png">

Or something like this (dark style variation):
<img width="327" alt="Screenshot 2020-01-16 at 15 49 23" src="https://user-images.githubusercontent.com/1562646/72534839-cc6a3e80-3877-11ea-9985-720486566c39.png">

**Comment by apeatling** [comment]
I think if the top level link color changes the submenu colors as well, you’re going to get clashes because the user does not have control over the background color of the submenus at this point.

It’s better to do light/dark and deal with colors when we can provide full control to users. Otherwise a situation where background color on the top level is light grey, the text color black, and they select the dark style means links in submenus are going to be unreadable.

**Comment by retrofox** [comment]
> Otherwise a situation where background color on the top level is light grey, the text color black, and they select the dark style means links in submenus are going to be unreadable.

Just to be clear about technical implementations. We can propagate the colors of text and background to the sub-items and completely ignore the light/dark styles here, as the primary menu (items in level 0) already does.

**Comment by apeatling** [comment]
Right, but I don't want to end up in a situation where the nav looks like this with no control over the submenu colors:

![image](https://user-images.githubusercontent.com/1464705/72546204-361a2680-383f-11ea-834b-bfa45aeb9562.png)

**Comment by apeatling** [comment]
To be clear, although subjectively I don't think the above looks good, if there is control over the submenu colors I think this is a fine outcome.

**Comment by shaunandrews** [comment]
> Should the colors selected in the navigation color picker propagate to the submenu? Both from a design perspective but more importantly from a UX perspective: What would the user expect?

As a user, I would expect the colors to propagate to the submenu. But, I'd probably also expect to be able to change the colors for the submenu independently. However, the current UI gets pretty overwhelming if we add two more color options:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/191598/72548788-6f618f00-385d-11ea-88af-1269228e62f5.png">

But we could move the submenu color options to the toolbar when a top-level item with children is selected:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/191598/72548961-c6fffa80-385d-11ea-9841-553905301887.png">

--

For now, I think we should just keep the colors tied to the top-level items and look at adding color options for submenus in another PR.

**Comment by apeatling** [comment]
> As a user, I would expect the colors to propagate to the submenu. But, I'd probably also expect to be able to change the colors for the submenu independently.

I think this is the ideal setup, and what we should be aiming for. The light/dark styles were a stop-gap until we could support color changing. By the sounds of it this is causing implementation confusion.

Here's a suggestion building from Shaun's above, please chime in with thoughts:

1 .Remove the light/dark style variations
2. Propogate the color changes for background and text through to all submenus
3. Implement and merge the new submenu design with the above to items considered
4. Follow up immediately with support for submenu text and background color changing support

**Comment by retrofox** [comment]
> Here's a suggestion building from Shaun's above, please chime in with thoughts:
> 
> 1. Remove the light/dark style variations
> 2. Propagate the color changes for background and text through to all submenus
> 3. Implement and merge the new submenu design with the above two items considered
> 4. Follow up immediately with support for submenu text and background color changing support

Sounds like a nice plan. Going to add these points in the PR https://github.com/WordPress/gutenberg/pull/19681

**Comment by karmatosed** [comment]
I like the plan apart from removing light / dark styles beyond a temporary removal. If we bring those back later I would be ok with it as we create the new style.

**Comment by retrofox** [comment]
We haven't talked about how to apply the border-color for sub-menus. What we did, as an experiment, was applying the same color that the text if it's defined. If not, it will apply the Light/Dark color.
Another option is adding a new border color section in the color selector popover.
Ideas and suggestions are over welcome. Thanks, folks!

**Comment by karmatosed** [comment]
Could border color just balance off from the base of background? Looping @ItsJonQ in here as know this is something we are exploring in global styles where one style generates other options using CSS variables.

**Comment by retrofox** [comment]
> Could border color just balance off from the base of background?

Do you mean for instance applying a kind of filter or rgba()?

> other options using CSS variables.

No IE11 support, then ;-)

An aside note related to this: Using CSS vars would make all these implementations soooooooooo easy

**Comment by karmatosed** [comment]
@retrofox personally I think for 'additional styling' the support isn't an issue and in #19611 along with other places this has been discussed. It's a case of having a decent baseline so it looks good across all browsers, then extras come if can support.

I do think if we don't go that route them filter or some method of rgba (even opacity) could work. I just think we have to be careful about at least for now not having so many color options it is a confusing interface. If I set a background I would want things to just work out, as a baseline.
