### ISSUE TITLE
Placeholder text should be display full in the link.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#18312]
**Describe the bug**
Placeholder text should be display full in the link.

Version :

WordPress 5.3 beta

**To reproduce**
1. Go to 'editor'
2. Click on 'button'
3. Add Button block
4. See the link placeholder text.

**Expected behavior**
Placeholder text should be display full.

**Screenshots**
![image](https://user-images.githubusercontent.com/51028940/68301817-c7924d00-00c6-11ea-9cc6-95cf85f363ec.png)

**Comment by paaljoachim** [comment]
Hi @nayana96249 

The Button block has changed a lot since you made this issue. It now looks different.
I will go ahead and close this issue. If I am mistaken then please reopen.
