### ISSUE TITLE
Navigation block: Consider reducing the interface on clicking in a menu item

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18315]
Currently, when you click to add an item you see this:

![nav-allon](https://user-images.githubusercontent.com/253067/68312056-665c8080-00aa-11ea-9f6f-8352852d64f8.png)

I would suggest that reducing what is shown by default to adding a link. Then when that's done the rest of the toolbar and items could appear. I know this isn't a behaviour we use everywhere right now but what we present is a lot for someone to experience.

**Comment by mapk** [comment]
I'd also really like to see that input field to be larger 2 characters by default.

**Comment by karmatosed** [comment]
I don't think the input is the issue here though. For me, it's showing everything on at once. For example, reducing the toolbar back and having it just load a link interface would be better for the cognitive load. I also don't see this as an input field as it's like typing for me.

**Comment by mapk** [comment]
> I don't think the input is the issue here though. 

Nevertheless it's still an issue. I'm happy to create a new one if you'd like.

**Comment by karmatosed** [comment]
@mapk absolutely, saves it being hidden in this.

**Comment by WunderBart** [comment]
Sounds good to me, @karmatosed! Also IMO, when the toolbar is visible it suggests that the block content/input is currently active. In our case (right after clicking the ⊕ button) it actually isn't - the popup input is. It becomes obvious once you start writing which will make the toolbar disappear instantly, so for me it's another reason to hide it by default. Any mouse movement brings the toolbar back, so it should not make anyone's life harder, I guess?

I'd be happy to take this one on!

**Comment by WunderBart** [comment]
@karmatosed I'm holding off my work (https://github.com/WordPress/gutenberg/pull/19531, https://github.com/WordPress/gutenberg/pull/19561) on this one as it's a `wontfix` at this point (please see https://github.com/WordPress/gutenberg/pull/19531#issuecomment-577662603 and https://github.com/WordPress/gutenberg/pull/19561#issuecomment-577659422). Let's get back to it once https://github.com/WordPress/gutenberg/pull/19344 is in.

**Comment by mtias** [comment]
@WunderBart I'd like to try the "absorb child block toolbar in the parent" setting for this one.

**Comment by tellthemachines** [comment]
> @WunderBart I'd like to try the "absorb child block toolbar in the parent" setting for this one.

@mtias could you elaborate on this approach, or point us to where it was discussed?

I'm wondering if it still makes sense to have this issue as specific to the Navigation work, given the comments [here](https://github.com/WordPress/gutenberg/pull/19531#issuecomment-573061322) and [here](https://github.com/WordPress/gutenberg/pull/19561#issuecomment-573605742) point to this requiring a solution consistent between all blocks.

**Comment by mtias** [comment]
@tellthemachines this work: https://github.com/WordPress/gutenberg/pull/18440

And the `__experimentalCaptureToolbars` API.

**Comment by getdave** [comment]
Glad the `__experimentalCaptureToolbars` got used :)

**Comment by draganescu** [comment]
It looks like #18440 closed this issue.
