### ISSUE TITLE
Clicking into a menu item shows no style

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18319]
If you have a style selected for navigation it is lost when you are in the menu item.

![nav-clickin-nostyle](https://user-images.githubusercontent.com/253067/68313780-10d5a300-00ad-11ea-93ee-215942a09c21.png)

I would argue the menu item should still be styled.

**Comment by mtias** [comment]
I don't know why it has that gray border either.

**Comment by karmatosed** [comment]
Yes, that was super confusing. I guessed it was a 'nothing' state but had to think about it a bit.

**Comment by draganescu** [comment]
Yes, I will remove the border and see how to preserve the style in edit mode.

**Comment by karmatosed** [comment]
Related to this I get the following where the theme styling seems to vanish:

![image](https://user-images.githubusercontent.com/253067/68414352-ec022e00-0187-11ea-9662-ae0c275836d7.png)

**Comment by retrofox** [comment]
Please [try to get this one](https://github.com/WordPress/gutenberg/pull/18374) before to start to work on this.

**Comment by retrofox** [comment]
It seems it was tested with an old master version since now the background color is applied to the whole navigation menu.
