### ISSUE TITLE
Should you be able to just add text to navigation menu?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18317]
In the current implementation, you can just add text to the navigation menu. I personally wonder if this should be allowed or restricted? It seems weird to just have text but maybe there is a use case for this?

![nav-empty](https://user-images.githubusercontent.com/253067/68312936-b25bf500-00ab-11ea-99b2-2eb1ff332d96.png)

I am tentatively going to mark this as bug but would love feedback.

**Comment by mtias** [comment]
See #18305.

**Comment by mtias** [comment]
I think this should be allowed, we can improve how it's communicated in #18305.
