### ISSUE TITLE
Remove one place for open in new window on menu item

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18320]
With the recent changes, we now have 2 places for 'open in new window'.

![nav-doublenewtabs](https://user-images.githubusercontent.com/253067/68314288-d1f41d00-00ad-11ea-8129-4a1984f99e9d.png)

I would suggest we reduce this to only one location and have by the menu item, removing in sidebar.

**Comment by mapk** [comment]
AND they're both written differently: One uses `Title Case`, while the other uses `Sentence case`. However we move forward here, let's use `Sentence case` for sure!

I'm okay with removing the one in the sidebar if we're removing one. The one in the popover aligns nicely with other link interfaces in the UI.
