### ISSUE TITLE
Sub menu item icon iterations

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18328]
The current sub menu item looks like this:

![nav-addsub](https://user-images.githubusercontent.com/253067/68315772-2ef0d280-00b0-11ea-9cbb-c568736973fc.png)

In testing this, I wasn't at all sure this was for adding. I expected '+' or something not the loopy arrow. It also feels similar to me to navigators which are planned to be added to this toolbar.

**Comment by mapk** [comment]
I can see how this might be understood as "Move this top item to the bottom". We should look into a new icon for adding sub-menus. 👍

**Comment by karmatosed** [comment]
Here are a few options:

![image](https://user-images.githubusercontent.com/253067/70468139-73f89200-1abe-11ea-849e-cd636abfab8a.png)

I think the top one probably is best.

**Comment by mapk** [comment]
I agree the top one is better, although, I'm not sure how the bottom longer line works in relation to submenus. Are these existing Material icons, @karmatosed?

Here's some concepts based on that inspiration.

**Option 1 with plus**

![icons-1](https://user-images.githubusercontent.com/617986/70949825-b3b9ff00-2013-11ea-9dd7-47d28ae14d87.png)


**Option 2**

![icons-2](https://user-images.githubusercontent.com/617986/70949830-b61c5900-2013-11ea-8d11-d064471062b8.png)

**Comment by karmatosed** [comment]
These are existing material icons yes.

**Comment by karmatosed** [comment]
I think the top one I suggested is a little better as points to within adding. Let's try that. I am removing design feedback for now.

**Comment by mapk** [comment]
I actually don't think that top one makes much sense in context of a submenu, but I don't want to hold this up. If we need a custom svg that communicates better, I'm happy to help.

**Comment by karmatosed** [comment]
Happy to add back in the label but I don't think the two you gave really say sub as they show top with a +. Let's put the label back.

**Comment by getdave** [comment]
Just checking did we decide on a direction here? I also share the concern that the icon isn't clear enough.

**Comment by jeryj** [comment]
Agreed. I'm happy to replace this code-wise once the svg is settled on. IMO something that includes the + is ideal, as it stays inline with adding the other menu items.

**Comment by apeatling** [comment]
Personally I don't think the icons above are an improvement, they are still ambiguous unless you hover over and read the tooltip. 

What about using a label in the same vein as the "Replace" menu on an image block? "Add Submenu"?

**Comment by mapk** [comment]
Yea, this is hard. I don't think text is gonna work length-wise, but worth a visual. 

![text](https://user-images.githubusercontent.com/617986/72025993-d1ebd700-322e-11ea-84bf-804f96148bb6.png)

After doing some searching for "submenu" icons, I created this one:

![icons](https://user-images.githubusercontent.com/617986/72026198-87b72580-322f-11ea-81b6-2193ac6a421c.png)


Here's how it looks in context:

![Navigation block](https://user-images.githubusercontent.com/617986/72026027-f34cc300-322e-11ea-87b3-413f93d87603.png)

**Comment by mapk** [comment]
Here's one with a more defined arrow:

![Navigation block v2](https://user-images.githubusercontent.com/617986/72026916-07de8a80-3232-11ea-9495-d54aff2db17a.png)

**Comment by karmatosed** [comment]
What about "+ submenu"?

**Comment by shaunandrews** [comment]
I like the "more defined arrow" icon from @mapk 

I think the "+ submenu" could work — it matches the pattern for adding menu items elsewhere in the Navigation block — but I worry about the toolbar getting excessively long with a label and the addition of movers at some point.

**Comment by karmatosed** [comment]
This is what text could look like (just editing html to mock):

![image](https://user-images.githubusercontent.com/253067/72385153-c446bd80-3716-11ea-8057-855ab4fb257d.png)

Or smaller:

![image](https://user-images.githubusercontent.com/253067/72385187-d0cb1600-3716-11ea-9dc1-275de4ad41d6.png)

**Comment by mapk** [comment]
Thanks for mocking that up, @karmatosed. They appear to be saying `Link + Submenu`.  I ran across this as well in https://github.com/WordPress/gutenberg/issues/18328#issuecomment-572315630 which is why I added the divider. I still don't think the text works all that well here. 

Let's go with the icon: 

![icons](https://user-images.githubusercontent.com/617986/72385376-3ba72d80-36d4-11ea-8519-fdd0f3a3803c.png)

Should I get a PR going for this?

**Comment by apeatling** [comment]
I mocked up the text using a plus sign with a more appropriate weight, and with the line. I still prefer this to an icon even if it adds length. @mapk I do think your icon is an improvement, but I still don't believe it fixes the root issue of the icon not being self explanatory.

<img width="569" alt="Screen Shot 2020-01-14 at 2 47 34 PM" src="https://user-images.githubusercontent.com/1464705/72389360-0e12b200-36dd-11ea-88bc-73a83b1a4f59.png">

**Comment by shaunandrews** [comment]
I tried a bunch of variations with the button in the toolbar:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/191598/72462348-e71cb480-379e-11ea-9450-7d07f711db6a.png">

...but I tend to agree with @apeatling — this doesn't really solve the root problem. Lets explore showing the "Add submenu" inline again when a menu item is selected.

Selected a top-level item (without children) we'd show an empty dropdown with a placeholder for adding a new submenu:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/191598/72462842-1122a680-37a0-11ea-8685-a343cd927f34.png">

When selecting any other-level menu item, we'd show the flyout placeholder:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/191598/72462862-1a137800-37a0-11ea-9f1e-ed1c1c0055d0.png">

--

Here's a GIF of how it would feel in action:

![nav submenus 2](https://user-images.githubusercontent.com/191598/72462900-28fa2a80-37a0-11ea-8064-857bbe99bfe8.gif)

**Comment by jasmussen** [comment]
I think the icon as is, is not the greatest icon there is. However I think it's worth asking whether it's worth it to change this icon at all, at least urgently. 

The new UI being explored in #19344 is reducing the UI of aspect _around_ the navigation block menu, making the sub-optimal icon less urgent:

![menu](https://user-images.githubusercontent.com/1204802/72462936-827b4d00-37d2-11ea-868d-2d4af4081291.gif)

The other aspect is to balance the importance of each feature. I personally find it less important to create submenu items compared to top level items. For "Replace image", on the Image block, the action was so relevant that a big fat text label was necessary. I'm not personally sure submenu items have the same importance.

**Comment by apeatling** [comment]
> The new UI being explored in #19344 is reducing the UI around the navigation block menu, making the sub-optimal icon less urgent:

I think the G2 UI is a nice improvement. I tried the PR! While the UI is definitely clearer, I don't think it addresses this particular problem of having an obscure icon and the feeling that the submenu flow is just a bit quirky overall.

**Comment by jasmussen** [comment]
Oh 19344 is no panacea! The Menu block remains a beast to handle.

To expand a little bit, I meant to suggest that the submenu flow feels secondary to creating primary menu items. That doesn't mean it shouldn't be adressed head on, but just that even the primary menu item flow is quirky. Focus is still unclear, adding menu items is still also a little funky. Once that flow feels solid, we'll be in a better place to decide whether submenu items are something to continue creating inline as they are currently (which I think can be made to work), or whether we need to go back to the drawing board. A plan B, for example, could be to not allow creating submenu items inline at all, and instead have a button in the main block toolbar called "Edit menu", which would open a modal dialog visibly reminiscent of the block navigator, for creating and sorting primary and submenu items.

**Comment by karmatosed** [comment]
One thing I would love to avoid is multiple '+' where possible - for me it's a singular 'add here' action so feels really odd visually having multiple. Yes, I know we have that already but I would really like us to explore moving from that. In your explorations could that happen @shaunandrews?

**Comment by karmatosed** [comment]
I have to say after watching user testing videos on navigation where finding sub nav was a problem, I do worry about any icon being a hitch for people regarding sub nav. Maybe for now we keep the icon we have and then iterate the flow? @mapk what do you think about that as an action here? I'll note I'm not saying any icon is worse/better more I think the general interaction is hidden and we might not be helping with anything here. This is really based on the usability testing recently done on make/test for navigation.

**Comment by mapk** [comment]
> Maybe for now we keep the icon we have and then iterate the flow? @mapk what do you think about that as an action here?

Thanks for the ping! I agree that a simple icon is just not going to convey the perfect meaning here. For this reason, keeping the current icon is fine right now while we move efforts to the bigger interactions within the block itself.

**Comment by karmatosed** [comment]
Ace, thanks for the feedback. For now, closing this as we can revisit and reopen.
