### ISSUE TITLE
Background empty state on navigation style reads like stripes

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18323]
The empty state being shown is:

![nav-nobackground](https://user-images.githubusercontent.com/253067/68314890-dbca5000-00ae-11ea-981a-4196e27b36a3.png)

We'd need to explore this but it for me reads like stripes. Maybe just a line crossed through a circle to show no would be better?

**Comment by mapk** [comment]
Do we have examples of how other UIs handle this? Google docs tends to separate out these two into their own icons.

![Screen Shot 2019-11-06 at 4 47 27 PM](https://user-images.githubusercontent.com/617986/68350437-2353da80-00b5-11ea-994f-ba415d6aacb9.png)

I don't think a line through the circle would work because that would indicate to me that there's no text or color. Maybe we don't show anything? So it's just text in a circle. Like this:

![Screen Shot 2019-11-06 at 4 49 18 PM](https://user-images.githubusercontent.com/617986/68350501-66ae4900-00b5-11ea-9ff1-efa4ee2738eb.png)

**Comment by karmatosed** [comment]
Problem with just circle like that it can look like 'white' is color selected.

**Comment by karmatosed** [comment]
One idea (probably not what we will end up on).

<img width="774" alt="tyr" src="https://user-images.githubusercontent.com/253067/68430944-04367500-01a9-11ea-876c-c792693f6a5a.png">

**Comment by retrofox** [comment]
> Problem with just circle like that it can look like 'white' is color selected.

This is the reason why I added the background stripe. `white` is a very common option.

> One idea (probably not what we will end up on).

Don't get what you did :-(

**Comment by retrofox** [comment]
Maybe just removing the circumference when there is no background-color?

<img src="https://user-images.githubusercontent.com/77539/68610797-60deac00-0497-11ea-8d5f-23cfc381f8bb.png" width="300px" />

or even

<img src="https://user-images.githubusercontent.com/77539/68610811-69cf7d80-0497-11ea-8025-68d27d423004.png" width="300px" />

**Comment by mapk** [comment]
@retrofox I really like option 1 there! Remove the circle outline and striped background when no color is selected. Looks great! 👍

**Comment by karmatosed** [comment]
My only concern is this changes the view quite a bit but in balance, it's probably the best first step forward. Even a cross out seems weird and interferes with the visual.

**Comment by retrofox** [comment]
> @retrofox I really like option 1 there! Remove the circle outline and striped background when no color is selected. Looks great! 👍

> My only concern is this changes the view quite a bit but in balance, it's probably the best first step forward. Even a cross out seems weird and interferes with the visual.

We need to keep in mind that the background option was removed from the current approach. However, It is good to know if it's going to be restored.

**Comment by karmatosed** [comment]
Let's close this for now as I think we can bring it back but things might be different then.
