### ISSUE TITLE
Color picker overlaps on color settings for navigation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18325]
The color picker pops out of the settings and if it's due to size, maybe we can increase that block and centre?

![nav-colorpicker](https://user-images.githubusercontent.com/253067/68315273-6ca12b80-00af-11ea-853c-7711de0c858a.png)

**Comment by epiqueras** [comment]
What branch is this on?

**Comment by karmatosed** [comment]
I just checked this on master and don't see anymore so let's close.
