### ISSUE TITLE
Be consistent where we say edit or change

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18321]
The new link interface says 'change' and we say 'edit' in other places. I suggest we should be consistent about saying just one of these and do it throughout. I don't really mind which but we might want to explore which translates more elegantly.

![nav-linkstate](https://user-images.githubusercontent.com/253067/68314550-3e6f1c00-00ae-11ea-884a-38f4eb7bb104.png)

**Comment by markarms** [comment]
I can't speak to translation here but agree that "Edit" makes sense and if it already used across other areas then we should go with that.

**Comment by mapk** [comment]
I agree that "Edit" should work fine here.
