### ISSUE TITLE
Adding link to menu item should change icon to unlink

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18322]
If you add a link, it would be great to then show the icon for link adding to 'unlink'. We had this in the previous link interface so I suspect it's just a case of bringing that back in.

![nav-linkstate](https://user-images.githubusercontent.com/253067/68314809-b6d5dd00-00ae-11ea-86aa-5d3eac479391.png)

**Comment by mtias** [comment]
I don't agree here. The link button is not a toggle and can be used to edit an existing link, so should remain as the same icon. It's the same behaviour as links for images:

![image](https://user-images.githubusercontent.com/548849/68331466-4e4e2680-00d5-11ea-8598-c4aca96ebc13.png)

**Comment by karmatosed** [comment]
What about highlighting it has a link somehow? There is a lack of a visual indicator as that icon just doesn't change for link.

**Comment by mtias** [comment]
We should highlight when it doesn't have a link: #18305.

In the future, an exploration could be done to show the link directly in the toolbar: 
![image](https://user-images.githubusercontent.com/548849/68392421-0decb800-016a-11ea-96d6-c600ca3b2fd7.png)

**Comment by karmatosed** [comment]
Ok cool, closing this one out in preference of #18305 then.
