### ISSUE TITLE
RGB button placement is wonky

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18326]
Currently, the button placement in Chrome looks like this:

![nav-rgblink-buttonplace](https://user-images.githubusercontent.com/253067/68315489-c0ac1000-00af-11ea-8a0e-19bd98ee1d74.png)

**Comment by getdave** [comment]
@karmatosed I think I might be able to guess but could you post another screenshot with the full context as to where this appears just in case? Much appreciated.

**Comment by apeatling** [comment]
This is what it looks like elsewhere

<img width="334" alt="Screen Shot 2020-01-09 at 9 04 04 AM" src="https://user-images.githubusercontent.com/1464705/72088420-fe4f3400-32be-11ea-8870-75488e23f61b.png">

**Comment by jeryj** [comment]
@karmatosed, maybe this got fixed since the issue got opened? I can only find one rgb color selection related to the navigation block, and it appears to be rendering correctly in chrome now.

<img width="1190" alt="Custom RGB selection in navigation block" src="https://user-images.githubusercontent.com/967608/72104299-bea14000-32f0-11ea-936b-ea4319067e26.png">

**Comment by obenland** [comment]
Clicking through Hex, rgb, and hsl, it looks like there are two different line heights between Hex and the other two settings. I also think it would be good to change the height of the button to the same as the input fields, while keeping the button square.

**Comment by jeryj** [comment]
Or would it be better to increase the height of the inputs? Do we need some design input here to make this more actionable? I agree that the misalignment of the inputs and button here feels off, especially since the button style basically matches the input style.

**Comment by obenland** [comment]
If a designer has strong opinions about how that button is displayed, sure! In the meantime, lets not have perfection be the enemy of progress. Aligning the button height with the inputs is a good first step.
