### ISSUE TITLE
Spacing needed on navigation when displaying on front by default

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18335]
There is a bit of a lack of consistency between what you see on front and what you see in back on the menu. The biggest of these is the lack of spacing to one side:

![nav-addlink-empty](https://user-images.githubusercontent.com/253067/68317488-1fbf5400-00b3-11ea-90ab-ebfa43498bb1.png)

**Comment by draganescu** [comment]
@karmatosed what theme did you use? With the new twenty twenty and gutenberg starter I do have the spacing. However there are other issues which I've come accross:

- the front end styling does not apply to the back end editor
- there are some styling glitches when editing menu items 
- there is some top padding missing in the menu block

A small screencast: http://cloudup.com/cNPklJRqXoH

**Comment by karmatosed** [comment]
Twenty Nineteen was what I tested with, it should work with that though.

**Comment by getdave** [comment]
@wunderbart Will be taking this one on I believe.

https://github.com/wunderbart

**Comment by retrofox** [comment]
@draganescu I've created an issues list from your list. We can check them once done.

**Comment by WunderBart** [comment]
@karmatosed, I used the Twenty Nineteen but still can't replicate the issue. Could you provide more details on how to replicate it, please?

**Comment by karmatosed** [comment]
With the background changes, I can't replicate this so going to close up for now. Thanks everyone.
