### ISSUE TITLE
Add full color hex information to parameters in getEditWrapperProps

### ISSUE THREAD

**Issue by fentron** [WordPress/gutenberg#18338]
**Is your feature request related to a problem? Please describe.**
When registering custom blocks that use the withColors HOC, it's helpful to have an accurate preview of the color in the editor. The currently selected colors are passed into the edit function in a helpful object that includes the hex code of the color. This allows the block to display the selected colour without needing to know the slug. It also allows for custom colors outside of the theme palette to be used:
`{name: "Brand green", slug: "brand-green", color: "#73c157", class: "has-brand-green-background-color"}`

When trying to use the same information in `getEditWrapperProps()`, the only information that is passed is the slug of the color: `brand-green`.
Unless the theme is including a custom editor stylesheet that includes rules for the color palette, this is useless for styling the editor. For custom colors outside of the palette, it's not possible to style the editor wrapper properly this way.

**Describe the solution you'd like**
I'd like the format of color settings passed to `getEditWrapperProps` to match that of the `edit` component

**Describe alternatives you've considered**
I've enqueued custom editor stylesheets for colours within the theme palette, and restricted user choice on a few sites by using the `disable-custom-colors` theme support option to get around this. I've tried to find a good workaround for custom colours but have as yet been unable to get it to work.

**Comment by jorgefilipecosta** [comment]
Hi @fentron,
Ideally, if possible, we should avoid getEditWrapperProps to add color styles. Would it be possible to refactor the component to have a wrapper div inside edit where you can style the component?
withColors is HOC while getEditWrapperProps is a function so we can not use withColors on getEditWrapperProps.
Ideally, getEditWrapperProps is a pure function depending on its attributes, so making it depend on the color value would make it impure. That said, relying on the className would not make it impure, and with the color slug attribute, you can generate the className from the slug using the function wp.blockEditor.getColorClassName.

I'm going to close this issue for now, if you think the issue needs additional discussion feel free to leave a comment.

**Comment by fentron** [comment]
@jorgefilipecosta, Understood, thanks for your response. Using a wrapper div works, it was just much simpler for me to style a container style block if the colours lived on the root element rather than an inner div, especially when the container wasn't full width.
