### ISSUE TITLE
Fade background to focus current interaction

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18330]
This idea came to me when using the existing navigation interface. As you add an item it focuses on that but the UI from the other elements is still on the same level.

![nav-fadeback](https://user-images.githubusercontent.com/253067/68316224-00272c00-00b1-11ea-873a-5c22ac7068f7.png)

What if the background faded/blurred or was someway dissolved a bit?

![image](https://user-images.githubusercontent.com/253067/68316367-42506d80-00b1-11ea-982e-55940ce7ff71.png)

I am just throwing this idea out there but it will need design exploration.

**Comment by mapk** [comment]
As I fiddle with this block, you're suggestion here makes a lot of sense! 👍 

I'd like to see something like this to help the user focus on the item they are editing. Right now it's a bit too difficult to figure understand the edited item's relationship to the whole.

**Comment by mtias** [comment]
This is what "Focus Mode" does and works well with the navigation block since it uses child blocks. I don't think it should be forced on the default experience.

**Comment by karmatosed** [comment]
> This is what "Focus Mode" does and works well with the navigation block since it uses child blocks. I don't think it should be forced on the default experience.

Whilst I get that it did make me think about this being for nested blocks the default. Maybe something to explore or at least note in a Tip could help (if we have Tips include things like that later).

**Comment by mapk** [comment]
Well by golly! The focus mode on the Nav block help quite a bit!

![Screen Shot 2019-11-08 at 5 03 16 PM](https://user-images.githubusercontent.com/617986/68520044-b887d800-0249-11ea-860c-b8e462779a9e.png)

**Comment by karmatosed** [comment]
For now, closing this as people can opt to turn this on.
