### ISSUE TITLE
Unclear what description does in menu

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18334]
Right now adding a description seems to do nothing to menu items. I can logically work out why but it would be good to say that.

**Comment by apeatling** [comment]
@karmatosed Could you give more details on this one, are you talking about link descriptions?

**Comment by getdave** [comment]
I think Tammie might be referring to the sidebar where it says "Description". 

<img width="1118" alt="Screen Shot 2020-01-08 at 16 15 14" src="https://user-images.githubusercontent.com/444434/71995164-12991f80-3232-11ea-917a-b5f4f36aa6e5.png">

I think perhaps Jerry (@jeryj) will look at this.

**Comment by apeatling** [comment]
Thanks, and agreed.

**Comment by getdave** [comment]
@jeryj Suggest you research how the current WordPress Menu items utilise `Description` when output in WP Menus using PHP. Then we should map this across to Gutenberg. Then add a description.

Documenting your research here would also be super helpful for posterity.

**Comment by jeryj** [comment]
Can do! It looks like the old Appearance -> Menus method handles it with a good description for the description :) 

> The description will be displayed in the menu if the current theme supports it.

<img width="430" alt="Screen Shot 2020-01-08 at 10 46 41 AM" src="https://user-images.githubusercontent.com/967608/71998160-bf5ca800-3204-11ea-8961-20f8ec881430.png">

**Comment by jeryj** [comment]
I've added that description in, and opened a PR for it. I can update it with any necessary changes if we decide to go a different direction.
