### ISSUE TITLE
Raw Handling: Cannot paste in inline boundary and retain style

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18348]
**Describe the bug**

When pasting text while within an inline boundary (i.e. an italicized segment of text), the inline styles are not applied.

**To reproduce**

1. Copy some text. Like this: `Hello world`
2. Navigate to Posts > Add New
3. Click the writing prompt
4. Press <kbd>Cmd+I</kbd> to italicize the text
5. Write something
6. Attempt to paste the contents of your clipboard and have it be italicized
7. Observe that it's not possible, neither by <kbd>Cmd+V</kbd> (paste and match style) nor <kbd>Cmd+Shift+V</kbd> (paste as plain text). The pasted text is plaintext.

**Expected behavior**

I can have an italicized paste. Style should be retained respective to whether "paste and match style" is the intended action (it's probably reasonable that <kbd>Cmd+Shift+V</kbd> must conversely _not_ be italicized).

**Desktop:**

- OS: macOS Catalina 10.15 (19A603)
- Browser: Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by ellatrix** [comment]
Correct me if I'm wrong. I think the underlying issue is the same as #11571.

**Comment by aduth** [comment]
Seems likely!
