### ISSUE TITLE
Reduce settings available on link blocks

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18341]
I wonder if editing html and making reusable block should be limited for menu links?

![image](https://user-images.githubusercontent.com/253067/68323710-e809d980-00bd-11ea-8985-90c8cc4948c7.png)

**Comment by mapk** [comment]
"Add to reusable blocks" can probably go away. However, "Edit as HTML" might be useful? Say if I had a link that I wanted to display differently than the others... maybe I can edit the HTML to do so.

**Comment by karmatosed** [comment]
Editing HTML can very easily mess things up, do we want to expose that?

**Comment by mapk** [comment]
> Editing HTML can very easily mess things up, do we want to expose that?

I think that can be said for every instance of "Edit as HTML". However we still show it in other places. I'm not sure this should be excluded.

I did actually try it out and was met with a disappearing act. After switching it to HTML, I have no idea how to edit it.

![html 2019-11-08 17_06_06](https://user-images.githubusercontent.com/617986/68520128-36e47a00-024a-11ea-9cbf-b3bf7b6caee9.gif)

**Comment by karmatosed** [comment]
Remove design feedback as we can at least remove the resuable blocks.
