### ISSUE TITLE
Remove one of places you view block navigator in navigation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18340]
There are 2 places you can see the block navigator or structure of navigation. I would argue there should be only one and to remove from sidebar.

![image](https://user-images.githubusercontent.com/253067/68323169-ceb45d80-00bc-11ea-9c8f-9e69b6240236.png)

**Comment by karmatosed** [comment]
Another point why removing from sidebar might be good is the experience adding:

![nav-confusing-jump](https://user-images.githubusercontent.com/253067/68323366-37033f00-00bd-11ea-83cb-064d58b37685.gif)

**Comment by mapk** [comment]
Adding an item from the sidebar does feel a bit awkward. This can be solved by just removing the "Add" option in the sidebar.

I'm not sold that we should remove the entire Nav structure from the sidebar though. It's nice to see it laid out without overlapping the block itself. For larger menus this might serve to be quite useful.

**Comment by mtias** [comment]
Related https://github.com/WordPress/gutenberg/pull/18203

**Comment by karmatosed** [comment]
Closing in favour of #18203 but connecting back.
