### ISSUE TITLE
RSS Block: missing “has-dates”, “has-authors” and “has-excerpts” classes in <ul> tag

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#18349]
**Describe the bug**
The `has-dates` class is missing in the RSS Block when the **Display date** option is activated.

**To reproduce**
1. Add a new **RSS block**.
2. Check the **Display date** option in the block settings.
3. Inspect the block's HTML and find the `<ul>` tag. The `has-dates` class is missing there.

**Expected behavior**
There should be a `has-dates` class in the `<ul>` tag. The Latest posts block also have a **Display date** option with a correspondent `has-date` class in the `<ul>` tag. So, for consistency sake, this class should also be added to the RSS block.

**Screenshots**

RSS Block
![image](https://user-images.githubusercontent.com/1451087/68333129-c0634300-00b6-11ea-883d-8dbfd6e3e66a.png)

Latest posts block
![image](https://user-images.githubusercontent.com/1451087/68332972-74b09980-00b6-11ea-9425-c652072e2657.png)

**Desktop (please complete the following information):**
 - Mac OS Mojave (10.14.6)
 - Google Chrome
 - Version: 78

**Additional context**
- WordPress 5.3-RC3-46639.
- Gutenberg version 6.8.0.

**Comment by Soean** [comment]
@pagelab Then we also should add `has-authors` and `has-excerpts`. Do you have an example why we need this styles or only for consistency?

**Comment by pagelab** [comment]
Yes, I should have mentioned `has-excerpts` and `has-authors` also. The Latest Posts block also should add a `has-excerpts` class, is missing there.

Anyway, it's not just for the sake of consistency. Without these classes, we lose much flexibility in styling blocks if any of these elements are active in markup.

Here's a practical example. I'm creating a style that display the dates beside the title:

<img width="567" alt="rss-has-dates" src="https://user-images.githubusercontent.com/1451087/68490996-c711c780-0228-11ea-8d12-ab6b6b20a5ee.png">

If a post excerpt and an author are also added, I want to position the author and the date below the title, close to each other, but right above the excerpt:

<img width="576" alt="rss-has-dates-has-excerpts" src="https://user-images.githubusercontent.com/1451087/68491009-cc6f1200-0228-11ea-9f9e-1a1f93f4021c.png">

Without `has-dates`, `has-authors` and `has-excerpts` present in the parent `<ul>` element, this will not be possible.

**Comment by Mamaduka** [comment]
Created PR to add missing classes #39716.
