### ISSUE TITLE
Navigation block: Removing the block causes an error

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#18356]
**Describe the bug**
When removing a block, I get an error.

**To reproduce**
1. Add a Navigation block.
2. Remove the Navigation block.
3. Observe the error.

**Expected behavior**
I don't expect any errors to happen.

**Screenshots**

![error 2019-11-06 16_26_43](https://user-images.githubusercontent.com/617986/68349575-71b3aa00-00b2-11ea-9dc8-33659f6c2e42.gif)

**Desktop (please complete the following information):**
 - OS Catalina
 - Firefox 70.0.1
 - Gutenberg 6.8

**Comment by noisysocks** [comment]
I'm noticing this too! I don't think we should mark the block as non-experimental with this bug.

**Comment by frontdevde** [comment]
Note: While I can't reproduce this error on Chrome, it does occur every time on Firefox.
