### ISSUE TITLE
Iterate on message for no block found when experiment de-activated

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18352]
Currently, you get the following when for example you use the navigation block and then de-activate it.

![nosupport-message](https://user-images.githubusercontent.com/253067/68344642-7181d180-00e7-11ea-805b-591f5bc39894.png)

It could be good to review this copy and also maybe add some notice styling.

**Comment by melchoyce** [comment]
Is it technically possible for us to detect if the missing feature is included an experiment?

If so, we could do something like:

> [Navigation menu] is an experimental feature. You can re-enable it from the Gutenberg Experiments settings page.

**Comment by karmatosed** [comment]
Hmm, interesting point. @youknowriad do you know if that is possible?

**Comment by youknowriad** [comment]
It's possible of course, but I'm not sure it's worth adding. The Navigation menu is not experimental anymore and I'm not sure it makes sense for the other experiments.

**Comment by mtias** [comment]
Closing as there are no concrete proposals for improving it. Some work is meant to happen around the block directory for blocks that are present there but might be deactivated / uninstalled.
