### ISSUE TITLE
Surface user's visual editor preferences into the post editor settings panel.

### ISSUE THREAD

**Issue by jmichaelward** [WordPress/gutenberg#18351]
**Is your feature request related to a problem? Please describe.**
As a WordPress user, if I have checked "Disable the visual editor when writing" option in my profile preferences, I may have a confusing onboarding experience once I'm finally ready to try the new block editor.

A friend of mine, who is an infrequent user of WordPress, long ago checked this preference in his user profile because he preferred to write his content in HTML-only mode. Today, he reached out to a local Slack community asking how to add blocks to his content. Disabling the visual editor presents the content in a different way (different fonts, in particular, but which also disables the "+" button in the toolbar that allows content authors to add blocks), which led me to believe there was some kind of error or bug in his system, and we went down the usual troubleshooting paths before we realized he'd disabled the visual editor altogether.

**Describe the solution you'd like**
At a minimum, I would like to see us surface the value of that user's preference into the "more options" panel in the post editor preferences pane. Users who have disabled the visual editor altogether are not provided the option to switch between Visual and Code modes, and there is no other editor-based preference that reminds them that they have disabled Visual Editing altogether. It seems to make logical sense to group that preference with others relating to the post editing experience.

Naturally, while support for the Classic Editor exists, we'll need to continue to keep the existing preference inside the user preferences, as Classic Editor users do not have the post editing screen options available to them. 

**Describe alternatives you've considered**
n/a

**Comment by mtias** [comment]
This is a good point.

**Comment by phpbits** [comment]
@mtias How about having button to enable the visual editor? About to add on [EditorsKit](https://wordpress.org/plugins/block-options/) plugin but there seems to be no slotfill available on that area.

<img width="877" alt="Screen Shot 2019-11-09 at 2 11 27 PM" src="https://user-images.githubusercontent.com/3365507/68523956-0ad50180-02fb-11ea-9acf-2c2af7ae50bd.png">

**Comment by jmichaelward** [comment]
I feel there are two important elements for consideration here. As a user who has disabled visual editing in my profile:

- I likely will not want to have a persistent call to action present in the editor suggesting I re-enable it.
- I may not understand the relationship between that setting and the new editor experience.

Importantly, the "Editor" setting in the attached screenshot is not visible when a user has disabled visual editing via their profile. See:

<img width="368" alt="Screen Shot 2019-11-10 at 2 59 37 PM" src="https://user-images.githubusercontent.com/1407326/68550738-417a4d00-03cb-11ea-8754-54894aa07571.png">

My thought is that surfacing that setting there will better satisfy the two scenarios described above: leaving it out of view for users who truly wish to continue to write their content in this fashion, but unifying that preference with other editor-related preferences so that it is more easily discoverable.

**Comment by karmatosed** [comment]
Starting with a button seems to make sense. Let's remove the design feedback label and get it in to see what we think.
