### ISSUE TITLE
NavigationMenuItem: Set placeholder when creating a new item.

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#18368]
When a new item is created and the LinkControl popover field focused, the RichText field should show the same text that when it's empty: `Add item...`

![image](https://user-images.githubusercontent.com/77539/68388097-a705d980-013e-11ea-9ef0-d4a2602fea4f.png)

**Comment by mtias** [comment]
This should be just a case of focus and selection. A good reference is how the image block handles the caption rich text field.
