### ISSUE TITLE
'@wordpress/base-styles@latest' is not in the npm registry

### ISSUE THREAD

**Issue by GilCarvalhoDev** [WordPress/gutenberg#18375]
I am trying to install Wordpress base-styles as per the command below:

`npm install @wordpress/base-styles --save-dev`

This command is recommended at the link:
https://github.com/WordPress/gutenberg/tree/master/packages/base-styles

Could you correct it please?

Thanks.

Problem screenshot:
![image](https://user-images.githubusercontent.com/3825188/68401872-38824500-0159-11ea-8548-bf9314c603ac.png)

**Comment by gziolo** [comment]
This package wasn’t published to npm yet so it isn’t an issue in that regard as this os planned to happen some time after WordPress 5.3 release.

**Comment by gziolo** [comment]
This package is available on npm for some time.
