### ISSUE TITLE
Navigation background color doesn't show and gets stuck

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18377]
I just had an interesting experience where the background color wasn't showing despite being set:

![image](https://user-images.githubusercontent.com/253067/68406649-12b96800-017a-11ea-8984-3de03d3eacb8.png)

I also just noticed on changing themes it seemed to be stuck on the color I'd set before. I wonder if that makes sense or it should reset?

**Comment by retrofox** [comment]
could you tell me what is the theme in these tests?

**Comment by retrofox** [comment]
> I also just noticed on changing themes it seemed to be stuck on the color I'd set before. I wonder if that makes sense or it should reset?

Well, it applies the colors with inline style beyond if they were applied via the color palette or with customs ones. I'm not sure if it's easily doable.

**Comment by retrofox** [comment]
Sorry, maybe I'm misunderstanding the issue here.

![image](https://user-images.githubusercontent.com/77539/68419117-61660280-0178-11ea-8bb6-521f5db0acb6.png)

Looking at your picture, what I see is not ok is the colors-selector icon. It shows background-color white (green circle). Btw, It's already fixed if I'm not wrong.
However, the background color of the menu seems to be consistent with the current selection (pink arrows). 
Am I missing something?

**Comment by karmatosed** [comment]
Oh so to be sure (because this confused me). The circle is showing 'if' something has been applied - it's got 'nothing if not'? I say because of these changes:

![image](https://user-images.githubusercontent.com/253067/68429296-b53b1080-01a5-11ea-9003-bc2bf8dadc69.png)


![image](https://user-images.githubusercontent.com/253067/68429317-bec47880-01a5-11ea-800b-6c0dce157fd2.png)

I really think we either show colors (which was the initial intention) or don't show a change here. @shaunandrews looping you in incase I am going over your decision.

**Comment by shaunandrews** [comment]
I think this is/was a bug that seems to be fixed for me in the latest `master`:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/191598/68429753-b1df5f00-017c-11ea-9734-849a13d23143.png">

All seems to be working as expected.

**Comment by retrofox** [comment]
@karmatosed just for organizing purposes I'm going to close this one since it seems to be already fixed. Please feel free to re-open it if you keep seeing this bug.
