### ISSUE TITLE
Adding a nav item without a link does nothing

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#18384]
If I type in a title for a navigation item, but then don't add a link to it, it looks like any other navigation item. When I look a the front end nothing shows:

![2019-11-07 13 53 16](https://user-images.githubusercontent.com/1464705/68431274-a8e39300-0166-11ea-9b07-9257c99ade6b.gif)

I would expect to see the item in the front end, but it not be a linked to anything.

**Comment by apeatling** [comment]
I would also expect links in the navigation block to look like links as they do on the front end.

**Comment by mtias** [comment]
Related https://github.com/WordPress/gutenberg/issues/18305

**Comment by draganescu** [comment]
this one is weird because the server side rendering code should show it with no href

**Comment by draganescu** [comment]
@apeatling I am unable to reproduce this behaviour, for me adding a menu item with no link results in an anchor tag with no href printed on the front end.

However, we could as @retrofox suggested not show an anchor anymore but another kind of tag, maybe a span since with no href, there is no link.
