### ISSUE TITLE
Different style when selecting a navigation block item

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#18383]
When I select a navigation block item, I wouldn't expect the text style to change so dramatically. The change in size make it easy to lose your focus point and is disorienting.

![2019-11-07 13 40 09](https://user-images.githubusercontent.com/1464705/68430044-307bd280-0164-11ea-82b2-c6459f7ff434.gif)

I think the selected style of the navigation block item should remain consistent so there is no jumping around.

**Comment by mtias** [comment]
This is being handled in https://github.com/WordPress/gutenberg/pull/18367.

**Comment by mtias** [comment]
For completeness, this was fixed before and regressed in https://github.com/WordPress/gutenberg/pull/18172

**Comment by obenland** [comment]
Fixed in #18367.
