### ISSUE TITLE
Load translations outside WP

### ISSUE THREAD

**Issue by tpaksu** [WordPress/gutenberg#18393]
Hello, I'm tinkering with GB outside the WP environment, and I'm trying to use different Jed formatted JSON configurations to translate the GB editor. But when I load the translations via `wp.i18n.setLocaleData`, some parts loaded before the setLocaleData don't change, for example the block titles and descriptions. I'm using this code to load translation into GB:

```
function getTranslations () {
    return axios.get("/laraberg/i18n").then((response) => {
        if(typeof response.data.jed !== "undefined"){
            ( function( domain, translations ) {
                var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
                localeData[""].domain = domain;
                wp.i18n.setLocaleData( localeData, domain );
            } )( response.data.jed.domain, response.data.jed );
        }
    });
}
```

Even if I run the editor initialization code inside the `.then()` wrapper, the result is the same. And I've checked if the untranslated strings match, yes they do and they do exist in the given translation.

Is there any filter that I can hook into when the wp.i18n Tannin instance is created or something? I think I need to load the translations before everything else runs related to GB. But I can't.

An example jed file which I'm using is here: 
https://github.com/tpaksu/laraberg/blob/lfm-fix/src/resources/lang/vendor/laraberg/tr_TR.jed

**Comment by paaljoachim** [comment]
Hi @tpaksu Taha

Thank you for creating this issue!
A long time has passed.
Is this issue still valid?

@swissspidy Pascal I am just letting you know about this issue. Thanks.

**Comment by tpaksu** [comment]
@paaljoachim Hi, 

Nope, it's been a long time since I stopped working on gutenberg. It was so hard extracting the translations from both gutenberg, wordpress core and god knows where, so I moved to another editor. (If I remember correctly). Hope you guys made this easier in the last versions :)

Thank you.

**Comment by paaljoachim** [comment]
Thanks for your comment Taha!

I hope the devs have made it easier extracting translations.
@WordPress/gutenberg-core 

Have a great day!
