### ISSUE TITLE
Block API: pasteHandler() incorrectly treats single-line pastes as inline content.

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#18390]
**Describe the bug**

When pasting a single line of content that is transformed into a block, `pasteHandler()` will treat the resulting block as inline content.

**To reproduce**
1. Create a block with a `raw` transform which returns that block.
2. Paste content that matches the transform's `isMatch` rule.
3. Observe that the block is not inserted into the editor.

**Comment by ellatrix** [comment]
> Create a block with a raw transform which returns that block.

Could you share (simplified) code?

**Comment by pento** [comment]
Sure, here's a contrived example for simplicity, see Automattic/jetpack#13999 for a slightly more complex (but practical) example. The `transform` doesn't actually need to return itself, it can return any block.

```js
( function( blocks ) {
	blocks.registerBlockType( 'foo/test-paste', {
		title: 'Test Paste',
		category: 'common',

		transforms: {
			from: [
				{
					type: 'raw',
					isMatch: function ( node ) {
						console.log( 'Checking if the paste matched...' );
						return 'lol' === node.textContent.trim();
					},
					transform: function () {
						console.log( 'Returning a YouTube block...' );
						return blocks.createBlock( 'core-embed/youtube', {
							url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
						} );
					},
				},
			],
		},
	} );
} )( window.wp.blocks );
```

Paste the string "lol" (without the quotes, and no newlines) to see it in action.

**Comment by pento** [comment]
For comparison, paste this to see it work as expected:

```
lol
<br>
```
