### ISSUE TITLE
Tooltip Breaks If Child Button Uses dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Kelderic** [WordPress/gutenberg#18411]
**Describe the bug**
If a <Button> that `dangerouslySetInnerHTML` to set innerHTML is wrapped by a `<Tooltip>`, the editor crashed on render attempt.

**To reproduce**
1. Create a custom block. Add:

`
	    <Button
	    	title="My Title"
	    	dangerouslySetInnerHTML={ __html('<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 22 18"><rect x="0" width="22" height="18"/></svg>') }>
	    </Button>
`
2. Load the editor and observe.
3. Edit custom block code to be:
`
<Tooltip text="More information">
	    <Button
	    	title="My Title"
	    	dangerouslySetInnerHTML={ __html('<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 22 18"><rect x="0" width="22" height="18"/></svg>') }>
	    </Button>
</Tooltip>
`
4. Return to editor and reload. Select block and observe.

**Expected behavior**
The button should be loaded with a tooltip.

**Actual behavior**
The editor crashes.

**Screenshots**

![Bug Screencast](https://user-images.githubusercontent.com/1747252/68494105-d1799480-021b-11ea-88e6-575097e96851.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
- I'm not sure what version of Gutenberg. It is the version that is bundled in WP v5.2.4.

**Comment by noisysocks** [comment]
I wasn't able to get the `Button` code snippet you provided working regardless of whether it was wrapped in `Tooltip` or not.

Rather than using `dangerouslySetInnerHTML`, I recommend using the `SVG` component in `@wordpress/components`. Something like this should work better:

```js
import { G, Path, SVG, Button } from '@wordpress/components';
...
const MyIcon = () => (
    <SVG
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
    >
        <Path fill="none" d="M0 0h24v24H0V0z" />
        <G>
            <Path d="M20 4v12H8V4h12m0-2H8L6 4v12l2 2h12l2-2V4l-2-2z" />
            <Path d="M12 12l1 2 3-3 3 4H9z" />
            <Path d="M2 6v14l2 2h14v-2H4V6H2z" />
        </G>
    </SVG>
);
...
<Button title="My Title">
	<MyIcon />
</Button>
```

https://developer.wordpress.org/block-editor/components/svg/
