### ISSUE TITLE
Using the line code [code language="html"] …HTML code… [/code] in HTML block, in reusable block is not displayed.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#18415]
**Describe the bug**
Before creation of **« Syntax High‑Lighter Block »**,
we vere able to make colouration using :
`[code language="html"]html code…[/code]` {you can also use **CSS**, **JavaScript**, **PHP**, **…**, in language="".
But if you it in **« HTML block »**, the code function,
if you transform it in **« Reusable block »**,
the code is not displayed and invisible.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'post editor'
2. Create a **« HTML block »**
3. Put some **« HTML code »** in [code language="html"] … [/code], but remember to replace < & > with &amp;lt; & &amp;gt; 
4. Preview, normally you will see syntax colouration.
5. Convert the **« HTML block »** in **« Reusable Block »**
6. Preview, the code is invisible and not coloured.

**Expected behavior**
The [code language="html"] … [/code] and his content should be visible,
even in **« Reusable Block »**…

**Screenshots**
Use‑less…

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 70.0.1

**Additional context**
- I use wordpress.com blog, I don't know what version of GutenBerg they use ?

**Comment by ehti** [comment]
Hi @Nemzag,

That appears to be an issue in a block that's available in the WordPress.com editor, not core Gutenberg. The appropriate channel to report this issue would be WordPress.com's support, I'd suggest you to reach out to them.

All the best!
