### ISSUE TITLE
Quote Block rendered by Default Style dropdown is inconsistent

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18421]
**Describe the bug**
When you insert a Quote Block and then set the style to Large, you get a quote that looks like this.

<img width="1077" alt="screenshot_35" src="https://user-images.githubusercontent.com/2078245/68542291-5cff4b00-03ff-11ea-91d8-a072fc7e2600.png">

By selecting the _Large_ style from the _Default Style_ dropdown, every Quote Block that you insert into the page thereafter, should automatically take on that default style. However, when you insert a new Quote Block, the quote that gets inserted looks different to the _Large_ style. The actual quote text isn't centered and the citation is left aligned instead of centered.

<img width="1071" alt="screenshot_36" src="https://user-images.githubusercontent.com/2078245/68542350-f4fd3480-03ff-11ea-80be-6df6d804463d.png">

**To reproduce**
1. Insert Quote Block
2. Set Style to large
3. Select Large from the Default Style dropdown
4. Insert a new Quote Block
5. Add content to block and see that it's different to the previously styled 'Large' Quote.

**Expected behavior**
When a Default Style is selected, it should exactly match either the Default Style or the Large Style.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox 70.0.1
 - Version: WP 5.3-RC4-46680
- Theme: TwentyNineteen

**Comment by karmatosed** [comment]
I am actually seeing the following on latest version, perhaps this has been resolved?

![image](https://user-images.githubusercontent.com/253067/69353719-d48e6f00-0c76-11ea-9893-e15bf9227fd7.png)

Would you please be able to try and see if that is the case? If not, I can try and investigate further but might need to delve a bit deeper into the factors. Thanks.

**Comment by maddisondesigns** [comment]
Yep, it looks like this must've been fixed with the 5.3 release. It works as expected now so I'll close this one.
