### ISSUE TITLE
Consider side movers on spacer

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18430]
The spacer block is incredibly useful if you are creating complicated layouts but it is somewhat problematic when you are in tighter spaces. For example, in a column block, above an image you get this:

![image](https://user-images.githubusercontent.com/253067/68587735-ad1df200-047f-11ea-860a-0afd7cf9ac46.png)

I would suggest side or 'not central' movers for the spacer block could be super helpful.

**Comment by jasmussen** [comment]
I think this issue might be a duplicate of one @shaunandrews created for the same issue. I can't find it, but perhaps Shaun can?

**Comment by shaunandrews** [comment]
https://github.com/WordPress/gutenberg/issues/16617

There's a bunch of related issues with regards to floating UI elements obscuring or otherwise making it difficult to interact with other UI elements.

**Comment by karmatosed** [comment]
Closing out to focus on that issue, thanks.
