### ISSUE TITLE
Registering a dynamic block in JS overrides all attributes defined in PHP

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#18439]
**Describe the bug**
For dynamic blocks, you register them in PHP and in JS. You also include the attributes in PHP when registering the block.

However, if you register the block in JS and you include an `attributes` property (even if `null` or `undefined`), all the attributes of the dynamic block are now overridden by JS.

**To reproduce**
1. Register a dynamic block named `'my/block'` in PHP with some attributes
2. Register the same block `'my/block'` in JS but add `attributes: null` to the block settings during registration
3. Check `wp.blocks.getBlockAttributes( 'my/block' )` and see that all attributes defined in PHP are overridden.

**Expected behavior**
2 things:
1. For dynamic blocks, I was expecting the attributes defined in PHP to be always used.
2. Or, passing a falsey value to the `attributes` property during JS block registration won't override the attributes.

I prefer ignoring the JS attributes passed during JS block registration since I was scratching my head wondering why any of my attributes wasn't being followed by the dynamic block because I had used the `attributes` property during `registerBlockType`

**Additional context**
- Checked using Gutenberg included in WP 5.2.x and Gutenberg 6.8.0

**Comment by aduth** [comment]
As I see it, this is working as intended. The JavaScript registration will merge with properties defined server-side, but only as a shallow merge. Thus, if an `attributes` property is defined, regardless of what the value is, it will take precedent over what is defined from the server.

- If you don't want to override the server-side attributes, just don't provide `attributes` in the settings object.
- If you do want to override the server-side attributes, then you should expect that the object or value you provide wholly substitutes the server-side registration.

If I'm mistaken on this, can you clarify what is the use-case for providing a falsey value for attriutes?
