### ISSUE TITLE
Dragging any block breaks the block and editor

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18434]
**Describe the bug**
When I drag any blog, it doesn't move as it should, and just sits over the rest of the content, when I scroll up and down the editor. Upon deselecting the block, it returns to it's original place and becomes uneditable.

Vid: https://share.getcloudapp.com/WnuA8lr9

**To reproduce**
1. Insert any block
2. Use the drag handle to try and drag it somewhere

**Expected behavior**
Dragging blocks shouldn't break them

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6
- Browser: Firefox 70.0.1
- Version: WP 5.3-RC4-46680
- Theme: TwentyNineteen

**Additional context**
- See also #18282

**Comment by dbushell** [comment]
I'm experiencing the same problem. Firefox 70.0.1 / WP 5.3.

It looks like React is correctly moving blocks and updating the DOM order (save/refresh confirms). However, the animations seem to be failing to execute and the block get stucks with `translate3d` CSS props causing havoc with the visual layout. This makes the editor practically unusable in Firefox.

**Comment by youknowriad** [comment]
I think this is fixed now.
