### ISSUE TITLE
Support Markdown syntax

### ISSUE THREAD

**Issue by felixarntz** [WordPress/gutenberg#1843]
## Issue Overview
At the moment, when writing a very simple post (regular text content only) in Gutenberg, the user is required to use the mouse for things like inserting headings, links, formatting text in bold/italic etc. While Gutenberg is optimized for supporting creation of complex layouts, it should be as easy and streamlined as possible to write a basic post with text content. Only having to use the keyboard would make that much quicker.

## Possible Solution
If Gutenberg supported the Markdown specification, that would be possible. The current WordPress editor at least supports a subset of it, but I think Gutenberg should support much more of it. If users could simply write `## My Heading` and make that a heading block automatically, it would make the process of writing a post much quicker. Same applies of course for the other things, like formatting text or maybe even adding links.

@schlessera highlighted recently that [Dropbox Paper](https://www.dropbox.com/paper) has that kind of support for Markdown, and when I tested it, I loved it. Please try it to get an idea of my suggestion.

**Comment by westonruter** [comment]
Support for text patterns is being worked on in #1674. I imagine that could be extended to support headings.

**Comment by pento** [comment]
Core's textpatterns already support headings, so I assume it will be part of #1674.

-1000 on full Markdown support, that should be a plugin. It's far too niche, and a maintenance nightmare to make sense of the [various Markdown parsing libraries](http://johnmacfarlane.net/babelmark2/faq.html).

**Comment by ntwb** [comment]
No _WordPress Flavoured Markdown_ then 🤔

**Comment by felixarntz** [comment]
@pento Right, I probably went over the top with supporting "the Markdown specification". Headings and links in addition to the current stuff (bold, italic, code...) would be very beneficial though.

I wasn't aware of #1674, I'll leave a comment there too.

**Comment by mtias** [comment]
The basic markdown-like patterns are implemented.

**Comment by terrylinooo** [comment]
Maybe you can consider the [Markdown editor plugin](https://github.com/terrylinooo/githuber-md).

**Comment by phpbits** [comment]
@felixarntz I've just released markdown support for Gutenberg on EditorsKit( [https://wordpress.org/plugins/block-options/](https://wordpress.org/plugins/block-options/) ). It's integrated directly on RichText editor so you don't have to use custom block. Here's the preview on how this feature works :

https://twitter.com/phpbits/status/1135895882216329216
