### ISSUE TITLE
Add Block: Author Bio

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1844]
I dont know if it is already mentioned with different name. Sorry if it is, be free to close issue.

Seems as you forgot this very fine block used everywhere.
Just to exclude my subjective and personal opinion about it, to state one fact. I never used it on any website done by me, not once, zero. If my memory serves me well.

But I see this block is very popular. Wherever you turn on net, Blogs, news portals, have this Author Bio block inside Posts.

**Comment by karmatosed** [comment]
#1516 mentions bio, but not specifically saying about an author bio. I do wonder if it needs to be called out explicitly. I can see users wanting that. It is also something I have seen people switch themes just to have - so to me a good thing to have as a block.

**Comment by paaljoachim** [comment]
I have earlier made a tutorial for creating an author box. 
https://www.easywebdesigntutorials.com/create-your-own-author-bio-box-in-wordpress-without-a-plugin/

Here are some of the screenshots.

![custom-authorbox-wordpress](https://user-images.githubusercontent.com/5323259/28055004-79a07956-6617-11e7-8b04-441d5d23e885.jpg)

![users-your-profile-added-contact-info-wordpress](https://user-images.githubusercontent.com/5323259/28055011-7e90879e-6617-11e7-85ee-dbfaa58ae919.jpg)

As one would need to include social links in the right sidebar options. Social links that could also be used for a social sharing block.

**Comment by StaggerLeee** [comment]
I see now problem with User profile. Not a small one.
For start block could use  (Info)  what exist in WP core, and have filters to extend it later by developers.

- Username (Nicename)
- Gravatar, or any picture of avatar plugins (they usually override it)
- Number of Posts, linked to Posts list
- "About me" is already there
- Website

**Comment by karmatosed** [comment]
@paaljoachim I think using what already is in the system over adding more fields would be preferable, at least for a v1.

**Comment by karmatosed** [comment]
Here is a suggestion as to how we could have an author/authors block - the default is author.

![author01](https://user-images.githubusercontent.com/253067/28083681-0eff05b6-666e-11e7-87db-820d71228618.png)


![author02](https://user-images.githubusercontent.com/253067/28083687-13a4e0ae-666e-11e7-8d3a-0eee54082580.png)


Props to @melchoyce for helping me with iterations.

**Comment by melchoyce** [comment]
Thinking a bit more about it — I think it might make sense to split these into two blocks: an author bio block, and an author list block. I can see both blocks being useful in different contexts. Author bio is great to add to the bottom of your posts, while you likely won't want a list of every author on your site on every posts. However, you might want a list of all your authors on an About page, or on archive pages.

**Comment by karmatosed** [comment]
That's a good point about how much we should combine functionality in a block. I can see a point for doing both. In the case you are suggesting then I imagine we'd have two blocks called 'authors list' and simply 'author'. The UI translates to both, if we decide to go that route. Here are those split:

![author1](https://user-images.githubusercontent.com/253067/28179675-8ff3e136-67fa-11e7-9629-dc62e4657515.png)

![author2](https://user-images.githubusercontent.com/253067/28179678-948a3ba0-67fa-11e7-8404-61fb765b3bd8.png)

**Comment by hedgefield** [comment]
Looks good. Maybe a dropdown in the author block to select other authors if you have multiple? On a post it can be the post author by default, but I can also see this used on a Team or About Us page to display bios.

**Comment by jwold** [comment]
Would there be anyway, from the user interface, to have the author bio always show on a post? For instance, on a multi-author blog it'd be nice to have that be automatic, and not manually added each time. 

This could either be territory for "templates" with reusable blocks (https://github.com/WordPress/gutenberg/issues/1516) or might just need to be handled by the theme.

**Comment by karmatosed** [comment]
I don't think showing always on a post is a good idea, for example when working on themes it was a common request to remove. Having this able to be somehow set in a theme could work but again it's a common thing to remove. I would think off by default is the way to go.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
