### ISSUE TITLE
Question: What mean *.native.js files in the format-library package?

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#18444]
What mean *.native.js file versions in the format-library package?

For example:

* https://github.com/WordPress/gutenberg/blob/master/packages/format-library/src/link/index.js
* https://github.com/WordPress/gutenberg/blob/master/packages/format-library/src/link/index.native.js

**Comment by gziolo** [comment]
See https://github.com/WordPress/gutenberg/blob/master/docs/contributors/native-mobile.md. Gutenberg codebase is also used for the WordPress mobile apps for the editing experience. Those files allow to override behavior when the web implementation is tied to the browser implementation.
