### ISSUE TITLE
Emoji only url allowed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18441]
I am unsure what kind of URL checking (if any) is happening but I found myself able to make an emoji only URL. 

![image](https://user-images.githubusercontent.com/253067/68606778-12d1a480-04a7-11ea-923f-512aecfed771.png)

I would suggest we can at least prevent this, although it's kind of fun :)

**Comment by mpark86** [comment]
Hi, I would like to try working on this.

**Comment by pento** [comment]
Funnily enough, this isn't really a bug, it's possible to have emoji in domains. For example, https://🐮.ws.

I don't know if it's possible to have an emoji-only domain (it would probably require having a custom DNS server, as I wasn't able to make it work with some quick tests in `/etc/hosts`), but without putting in full domain resolution, I don't think it's possible to improve the accuracy of this UI without also restricting actual domains that people can enter.
