### ISSUE TITLE
eslint-plugin: Increase severity of JSDoc rules to error

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18458]
Previously: https://github.com/WordPress/gutenberg/pull/16869#discussion_r341168788

We should generally seek to avoid any [`'warn'` severity](https://eslint.org/docs/user-guide/configuring#configuring-rules) in our rulesets. If we have a rule, it should be enforced strictly, else it shouldn't be a rule. Exceptions are to be made using [inline comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).

**Task:** In [the `jsdoc` ruleset](https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/configs/jsdoc.js), all custom rule configurations should be changed from `'warn'` to `'error'`. Similarly, if we are extending `'plugin:jsdoc/recommended'`, we should override all rules with equivalents where the severity is changed from `'warn'` to `'error'`.

Reference for `'jsdoc/recommended'` rules: https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/index.js#L34

**Comment by gziolo** [comment]
> We should generally seek to avoid any [`'warn'` severity](https://eslint.org/docs/user-guide/configuring#configuring-rules) in our rulesets. If we have a rule, it should be enforced strictly, else it shouldn't be a rule. Exceptions are to be made using [inline comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).

Totally agree. Warnings are ignored by contributors. We should stop using them and pick errors instead 👍

**Comment by aduth** [comment]
Noting that we have a fair few warnings related to invalid syntax caused by [TypeScript-specific JSDoc extensions](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc) which are not yet supported by `eslint-plugin-jsdoc`.

See also: https://github.com/jsdoctypeparser/jsdoctypeparser/issues/50, #18838

We could consider to either leave this one specifically as a warning in the meantime, or disable it altogether.
