### ISSUE TITLE
Navigation Block: add automated tests

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#18451]
There should be some automated testing in place for the block as it transitions from an experimental block to a non-experimental one:

- Test fixtures for the 'full-content' test (https://github.com/WordPress/gutenberg/tree/master/packages/e2e-tests/fixtures/blocks)
- Block functional tests for various flows
- Unit tests for any new APIs added (if they're non-experimental).

**Comment by getdave** [comment]
See also https://github.com/WordPress/gutenberg/pull/18594#pullrequestreview-319041609
