### ISSUE TITLE
Full site editing with Gutenberg feature encountered with "No matching template found"

### ISSUE THREAD

**Issue by Gtarafdar** [WordPress/gutenberg#18468]
**Describe the bug**
Gutenberg comes with a new feature: full site editing feature. If I enable the feature whole site encountered with an error of "No matching template found". 
Testing environment:
WordPress 5.3 running Twenty Nineteen theme.
Running PHP version: 7.3.11-1+bionic
I tried it with a freshly installed (Live)site. Tried the default themes Twenty Nineteen/ twenty-twenty. Also, set the permalink to post name. 

**To reproduce**
1. Go to 'Gutenberg Settings'
2. Click on 'Experiment'
3. Give check mark to 'Enable Full Site Editing'
4. Visit Site
5. See Error "No matching template found".

**Expected behavior**
I like to use this feature to edit my full site with Gutenberg, any pages and posts.

**Screenshots**
I have recorded the whole scenario in this video.
https://www.loom.com/share/f7ac207afde243ae8b5ac54a542a91f0

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]
 - Version [ 78.0.3904.97 ]

**Smartphone (please complete the following information):**
Not Tested.

**Additional context**
- Gutenberg Version 6.8.0
- I've only one extra plugin while testing in the recording time: WP Reset: Version 1.75, I've tried it without this plugin too. The problem still exists.

**Comment by phpbits** [comment]
I've opened similar issue before : https://github.com/WordPress/gutenberg/issues/18209 . I hope this could help. Thanks!

**Comment by saiftheboss7** [comment]
I confirm this issue.

**Comment by youknowriad** [comment]
Closing as a duplicate

**Comment by nvjacobo** [comment]
Hi 

I have this issue on: 
- Twenty Twenty Versión: 1.1 
- Wordpress  5.3.2–es_ES
- Gutenberg 7.1.0
