### ISSUE TITLE
getSettings() returns WP defaults outside of edit() and save()

### ISSUE THREAD

**Issue by galloppinggryphon** [WordPress/gutenberg#18467]
`wp.data.select( 'core/block-editor' ).getSettings()` returns WP default settings rather than theme settings (including colors, fontSizes, etc.) configured in functions.php in some contexts. Defaults are returned when getSettings() is called in

- global scope (e.g. caching before calling registerBlockType())
- migrate()
- save() before edit() has run

Users should expect getSettings() to reliably return theme settings, not defaults, regardless of calling scope within a Gutenberg plugin. In my case, I need access to theme settings are during block migration. 

Tested in WP 5.2 and 5.3.

(Edited for clarity)

**Comment by youknowriad** [comment]
What do you mean exactly by block migration?

**Comment by galloppinggryphon** [comment]
> 
> 
> What do you mean exactly by block migration?

Using the migrate() function to update deprecated blocks. 

To be even more clear, here's what's returned in different contexts:

```
//returns WP defaults
console.log( wp.data.select( 'core/block-editor' ).getSettings() ) 

registerBlockType( 'foo/bar', {
    ...
    edit() {
        //returns settings defined by theme in functions.php, e.g.  with add_theme_support()
        console.log( wp.data.select( 'core/block-editor' ).getSettings() ) 
        return <div>Hello world</div>
    },
    save() {
        //returns WP defaults when triggered before Edit(), returns theme settings after.
        console.log( wp.data.select( 'core/block-editor' ).getSettings() )
        return <div>Hello world</div>
    },
    deprecated: [ {
         attributes: {},
         save( props ){},
         migrate( attributes ) {
              //returns WP defaults
              console.log( wp.data.select( 'core/block-editor' ).getSettings() 
         }
   }  ]
} )
```

**Comment by youknowriad** [comment]
Yes, this won't work because the migrate function is supposed to be a pure function (doesn't rely on any global variable/side effect and transform the existing attributes to new attributes). It is executed before the block editor is initialized, so at that moment there's no settings yet.

**Comment by galloppinggryphon** [comment]
Thanks @youknowriad, I suspected something like that. Seems like a documentation problem then: it was obvious to you, but it's not obvious to those with less experience with Gutenberg.

**Comment by youknowriad** [comment]
Right! we do mention this explicitely for save functions https://developer.wordpress.org/block-editor/developers/block-api/block-edit-save/#save 

We could do the same for the deprecations.

**Comment by galloppinggryphon** [comment]
Ahaaa, I see. I understand the issue now but I did not when I read it the first time some time ago.

Quote: `It can not have any side effect or retrieve information from another source, e.g. it is not possible to use the data module inside it select( store ).selector( ... ).`

It could stand to be more accessible for people with less experience with React -- make it crystal clear that the data in the props attribute is all there is. I was thinking of the deprecated functionality as a more conventional 'update' function for the block, but it looks like that will have to be split between migrate() and sine post-migrate processing in save(). 

Additionally, it was not intuitive that getSettings() returns data, just not the data I wanted. A big fat failure would have been more helpful...

Anyway, thanks for all the hard work.

**Comment by mburridge** [comment]
Does this still require any action?

**Comment by matteoFeduzi** [comment]
Is there by any chance a solution to this problem?

I tried this on my save.js file:
`wp.data.select("core/editor").getEditorSettings().fontSizes`

It will always retrieve the default WordPress fonts and not the fonts set on the theme.json file.

**Comment by Mamaduka** [comment]
I'm going to close the issue.

The behavior here is intentional and mentioned in [the docs with alternatives](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#save) for rendering dynamic data.
