### ISSUE TITLE
Inspector Controls needs some extendability

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/gutenberg#1846]
Currently, it doesn't seem possible to add `InspectorControls` to a custom block added by a plugin. I had to export it here: https://github.com/WordPress/gutenberg/blob/90ed19b53f2e799260d8890d71b8632130a647a7/blocks/index.js

This brings up a further question though, how does this project want to handle the individual controls - radio, range, checkbox, etc? Making these available will help plugins match styles and flows with each other, which would be a big win for UX.

I talked with @youknowriad shortly about this, and he mentioned some concerns about exporting all of these as it could be a backwards compatibility headache down the line. He mentioned one possible alternative could be making them available as their own npm module.

Anyways, just wanted to spur the discussion since I didn't see it anywhere else :)

**Comment by mtias** [comment]
Yes, we'd want to export them under the `components` group, which is what the eventual components library would become.

**Comment by mtias** [comment]
This should be working now.
