### ISSUE TITLE
FormTokenField throws error when maxLength is hit

### ISSUE THREAD

**Issue by lindapaiste** [WordPress/gutenberg#18463]
**Describe the bug**
When using the maxLength prop on the FormTokenField component, attempting to enter more than the allowed number of tokens causes an error **"Uncaught TypeError: this.props.onChange is not a function"**

The problem is caused by the renderInput() function on the FormTokenField class.

```	
if ( ! ( maxLength && value.length >= maxLength ) ) {
	props = { ...props, onChange: this.onInputChange };
}

return (
	<TokenInput { ...props } />
);
```

TokenInput expects to always have a callable onChange prop, however the onChange prop is only being set by the FormTokenField when the number of tokens is less than or equal to the maxLength. When maxLength > value.length, no onChange prop is passed and this causes TokenInput to throw an error.

**To reproduce**
1. create a FormTokenField component with the maxLength prop set to a number n.
2. enter n tokens to the field
3. attempt to add an additional (unallowed) token

behavior can be seen on CodeSandbox: https://codesandbox.io/s/objective-joliot-o5dfv

**Expected behavior**
The field should either fail gracefully and do nothing; or, better yet, communicate to the user that the maximum number of entries has been hit and no more can be added.

**Comment by rdm** [comment]
This still happens in wordpress 5.3.2

I ran into this, trying to get FormTokenField to substitute for a combobox (with maxLength: 1).

Possibly, we could have a documented callback to take action when the user attempts to add an additional character once maxLength is reached.

For now, my hopeful workaround will be to set maxLength higher than desired and implement maxLength in the onChange and maybe onInputChange handler(s). (In other words: the current maxLength implementation is dysfunctional and needs to be replaced any place where it's relevant.)
