### ISSUE TITLE
Navigation: Color scheme not fully supported

### ISSUE THREAD

**Issue by obenland** [WordPress/gutenberg#18464]
When switching themes, the navigation menu background color stays the same, and doesn't change to the new themes' color scheme, while menu items do change.

**To reproduce**
1. Create a navigation menu with a couple of menu items.
2. Set the background color to the first or second suggested color in the picker.
3. Switch to a theme with a different color scheme.
4. Load the menu in the front end.

**Expected behavior**
* Menu and menu items have the same background color
* The background color switches to the new theme's color scheme.

**Screenshots**
![Screen Shot 2019-11-12 at 1 42 48 PM](https://user-images.githubusercontent.com/1398304/68713302-60efb200-0552-11ea-820b-bfda174a460f.png)

**Additional context**
- Gutenberg v6.9.0-rc1

**Comment by frontdevde** [comment]
Just double-checking if I understand this correctly: The wanted behavior is that the custom colors selected via the color picker override the theme colors. At the same time, once a new theme is selected, the picked colors should be reset? Definitely agree that either the behavior should match for text and background color, just wondering whether we want to keep or remove the user-defined colors on theme change.

**Comment by obenland** [comment]
Themes can define color palettes (see https://github.com/WordPress/twentytwenty/blob/9ac5ba33839cf2e5f87d9fe39c81ec5aca19493f/functions.php#L484), and when themes define different colors for the same slug (like `primary` or `secondary`), these colors change after theme switch.
Because we also hard-code hex values in style attributes, the `nav` element background color can't change, leading to above shown result.

**Comment by obenland** [comment]
Not an issue anymore after #18407.
