### ISSUE TITLE
Blank Editor on Safari WordPress 5.3

### ISSUE THREAD

**Issue by seraphyn** [WordPress/gutenberg#18470]
**Describe the bug**
Creating a new Blogpost ends in an empty page on Safari Version 13.0.3 (15608.3.10.1.4) on macOS Catalina Version 10.15.1 (19B88).
Sourcecode is available via Developertools.
Javascript Errors are:
[Error] TypeError: Attempted to assign to readonly property.
	(anonyme Funktion) (server-side-render.min.js:1:6842)
	n (server-side-render.min.js:1:159)
	(anonyme Funktion) (server-side-render.min.js:1:955)
	Globaler Code (server-side-render.min.js:1:965)

[Error] Unhandled Promise Rejection: Error: Actions must be plain objects. Use custom middleware for async actions.
	dispatchException (data.min.js:1:22123)
	(anonyme Funktion) (data.min.js:1:24291)
	n (data.min.js:1:19513)
	a (data.min.js:1:19752)
	promiseReactionJob

Works without a problem on same Plattform but with Firefox.

**To reproduce**
1. Go to Dashboard
2. Click on + to create an article

**Comment by youknowriad** [comment]
Hi There!

I've not been able to reproduce the error. Do you have plugins enabled? Can you try disabling the plugins?

Also, is it possible to define the "SCRIPT_DEBUG" constant https://wordpress.org/support/article/debugging-in-wordpress/#script_debug (this will show better errors)

Thanks

**Comment by DKudleichuk** [comment]
Hi, @youknowriad! I'm using just Wordpress 5.3 with a Gutenberg in core, not as a separate plugin

**Comment by seraphyn** [comment]
It's a Plugin.
Disabling all gives me the editor.
Found later a wrong code in a functions.php that removes css/js.
Works flawlessy on prior Version of WordPress, but not with the new one.

Thanks for the help and of course for Gutenberg.
Keep up the good work
