### ISSUE TITLE
Motion again super slow in Safari

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18478]
**Describe the bug**

Previously: #17383.

For me this issue makes the editor **very** hard to use. If I'm editing a post quick block movement is perpetually delayed. :(

**To reproduce**

* Undo or redo blocks OR
* Paste blocks OR
* Delete a block

I think it becomes more obvious as there are more blocks present.

**Expected behavior**

I expect the blocks to move nearly instantly. Currently it takes a few seconds to move.

**Screenshots**

![slow-motion](https://user-images.githubusercontent.com/4710635/68771157-b9dd4a00-0627-11ea-9318-a24497dbe8bd.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: 13.0.3

WordPress version 5.3

**Comment by ellatrix** [comment]
![slow-motion-plugin](https://user-images.githubusercontent.com/4710635/68776671-c6b26b80-0630-11ea-9a8f-5c406cc79734.gif)

I can consistently reproduce this. The above is with the `master` branch of this plugin and the Gutenberg demo content.

Worth noting that I'm trying this on battery power @ 75%, but I don't have this issue in Chrome with the same amount of battery power. Not sure if this is even relevant. I'll try it later again when I'm charging the computer.

**Comment by ellatrix** [comment]
Also restarted Safari and I have the same issue.

**Comment by ellatrix** [comment]
Charging or not charging, it doesn't make a difference.

**Comment by mcsf** [comment]
@ellatrix, I'm trying this and can't repro:

* Safari
* Catalina
* Gutenberg demo post
* Current `master`
* Development build
* No plugins other than Gutenberg

Can you confirm there's no other plugin active? I only ask because in the past we found an E2E-related plugin interfering with motion in Safari.

**Comment by ellatrix** [comment]
I don't think the plugin was active, at least I didn't activate it myself. I've now tested again and everything seems to work fine, except that now the page doesn't scroll in Safari if I move a block. The animation seems to be smooth now though, but as far as I know it sometimes goes away an comes back. I'll try to test it regularly.

**Comment by ellatrix** [comment]
Let's close for now until I can reproduce it again.
