### ISSUE TITLE
WP 5.3 Change text alignment problems

### ISSUE THREAD

**Issue by MiloMen** [WordPress/gutenberg#18473]
**Describe the bug**
I recently made an update on WP 5.2 to version 5.3. I found a bug in the text alignment section. I tried to use text in the middle of the result, I don't see any changes..Have done a browser cleaning and cleaning the web cache the results remain no change. Refine the text align (center) so that it functions properly. Thank you.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1809
 - Browser Google Chrome
 - Version 78.0.3904.97

**Additional context**
Latest WordPress 5.3 and iconic one pro 2.9.6 theme.

**Comment by youknowriad** [comment]
Copying my response from the trac ticket https://core.trac.wordpress.org/ticket/48594

In previous versions of WordPress, text alignment was using inline styles but inline styles have a lot of problems (SEO...) so we switched to classNames.

By inspecting your site, I can see that your theme style has this style defined

```
.entry-content p, .entry-summary p {
    text-align: justify;
}
```

This is overriding the alignment class defined by WordPress

```
.has-text-align-center {
    text-align: center;
}
```

A dev note was written to let theme authors know about these changes https://make.wordpress.org/core/2019/09/27/block-editor-theme-related-updates-in-wordpress-5-3/

For now, I'm considering this a theme issue and I'd suggest contacting the theme author about it. Ideally, themes shouldn't have strong specificity like this. That said, I'm noting this and if we notice this several times, we might consider forcing a higher specificity in Core itself.

Thanks.
