### ISSUE TITLE
Social Links Block: No Option to Open Links in New Tab

### ISSUE THREAD

**Issue by scosgro** [WordPress/gutenberg#18486]
The Social Links Block is missing the option to open links in a new tab. This is the only link creator that is missing this feature. 

**To reproduce**
1.  Create a new Page
2. Add the Social Links Block
3. Populate the block with social media links and publish the page.
4. Visit the page and click a link. All of the links open in the same tab as the site, directing the reader away from your site, and to social media. There is no option to change this in the block.

**Expected behavior**
The ability to open links in a new tab. The Buttons block, all social link widgets, menus, paragraph block links, image block links, etc all have this feature, but the option is missing in the Social Links Block.

**Comment by edwinho89** [comment]
2762795-zen

**Comment by tbradsha** [comment]
Another vote for this!

**Comment by wprhunt** [comment]
+1 from me and this chat:
https://mc.a8c.com/support-stats/happychat/transcript.php?id=19035780

**Comment by paaljoachim** [comment]
Hey @scosgro 
Should we close your issue and go with https://github.com/WordPress/gutenberg/issues/20707 ?
As the issue as some beginning careful movements.

**Comment by scosgro** [comment]
@paaljoachim Up to you! Wherever it'll get visibility/updates works for me. :)

**Comment by mapk** [comment]
Alrighty, we'll close this in favor of #20707.
