### ISSUE TITLE
Breadcrumb text cut off

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18480]
<img width="203" alt="Screenshot 2019-11-13 at 15 33 34" src="https://user-images.githubusercontent.com/4710635/68773005-13934380-062b-11ea-9d83-b4847d709b32.png">

In WP 5.3.

**Comment by karmatosed** [comment]
I think this might be resolved now:

![image](https://user-images.githubusercontent.com/253067/69972382-6d47a900-1519-11ea-8b62-2b9fbfe00808.png)
