### ISSUE TITLE
The Paragraph Paradox

### ISSUE THREAD

**Issue by keoshi** [WordPress/gutenberg#18481]
**Describe the bug**

This is definitely a weird one, but bear with me for a second. Let’s call this _the paragraph paradox_: a paragraph is the default block, and I can use the block selector to “add” one, but it isn’t searchable through the `/` slash command.

I realize it might be a search limitation because we’re already inside a paragraph and nothing really changes by selecting it, but it made me wonder.

**To reproduce**
1. Open the block editor.
2. Type `/` and starting typing `paragraph` to filter out the results.
3. Confirm that the paragraph block is not returned.

**Expected behavior**
If the paragraph block is selectable through the `(+)` icon, it should also be available through the `/` command, no matter the current context.

**Screenshots**

![gutenberg-paragraph-paradox](https://user-images.githubusercontent.com/390760/68773781-0de62f80-0624-11ea-8481-2325143ed740.gif)

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - Version: 78.0.3904.70 (Official Build) (64-bit)

**Comment by talldan** [comment]
I think the difference is that the '+' button can exist in situations where there isn't a paragraph next to it. For example, if you add an image block, the '+' button appears to the left underneath the image, but there's no paragraph below the image, so users need a way to insert one.

**Comment by talldan** [comment]
I'm adding the `Needs Design Feedback` label. I'm not convinced the paragraph needs to appear in the dropdown when a user is already searching from within a paragraph, so I think maybe this can just be closed. Would be good to get a second opinion from a designer though!

**Comment by keoshi** [comment]
Yep, feel free to close this one.
