### ISSUE TITLE
Tag Cloud - Toggle "Sort by counts"

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#18497]
I had the idea for another "Sort by counts" toggle in the new Tag-Cloud Widget Block and have tested it before. What is your opinion?

![tg01](https://user-images.githubusercontent.com/6922544/68839114-4f2c1d00-06c0-11ea-9685-73c773e57ca7.png)

![tg02](https://user-images.githubusercontent.com/6922544/68839116-4f2c1d00-06c0-11ea-89a0-9920faa1d830.png)

If Category is selected, the toggle will be inactive because that sorting will not work there.

![tg03](https://user-images.githubusercontent.com/6922544/68839117-4f2c1d00-06c0-11ea-9b07-78f2bd1347fc.png)

**Comment by youknowriad** [comment]
Could be a good little addition.

**Comment by karmatosed** [comment]
It seems that right now tags are being sorted by counts:

![image](https://user-images.githubusercontent.com/253067/71092815-e42ea400-219f-11ea-98fc-7469a61109d7.png)

![image](https://user-images.githubusercontent.com/253067/71092934-18a26000-21a0-11ea-8752-6ba2e892870f.png)

For now, I am going to close this but we can always reopen if I am not understanding the intent correctly.

I am going to close this but just incase I am not understanding this correctly, we can always reopen.
