### ISSUE TITLE
Typing 1, followed by a dot, then space forces a list

### ISSUE THREAD

**Issue by sterndata** [WordPress/gutenberg#18492]
Typing 1, followed by a dot, then space forces a list.  See https://wordpress.org/support/topic/5-3-is-forcing-list-creation/?view=all#post-12129804

**To reproduce**
1.  type "1." then space
2.  The line becomes an ordered list
3.  Changing the block to a paragraph block undoes the ordered list, but removes the "1."

**Expected behavior**
I should be able to type listy-looking things without being forced into another block, or at least have an easy way to undo the change.

**Screenshots**

Version: WP 5.3

**Comment by pattonwebz** [comment]
I ran into this before and I do still dislike this auto transform behavior. I opened this ticket before about a very similar thing: https://github.com/WordPress/gutenberg/issues/17289 the introduction of [these undo patterns](https://github.com/WordPress/gutenberg/pull/14776) eases the problem but it is still something I run into almost every time I write in the new editor

**Comment by pb7107** [comment]
> I ran into this before and I do still dislike this auto transform behavior. I opened this ticket before about a very similar thing: #17289 the introduction of [these undo patterns](https://github.com/WordPress/gutenberg/pull/14776) eases the problem but it is still something I run into almost every time I write in the new editor

From what I'm seeing, the undo patterns (backspace, escape, delete) are very finicky. You need to keep your mouse pointer completely still after it does the transformation, or else they don't work. It barely qualifies as a solution in my book.

Before the 5.3 update, I was able to convert it back into a heading and it was fine, but now I can't even do that.

**Comment by ellatrix** [comment]
> From what I'm seeing, the undo patterns (backspace, escape, delete) are very finicky. You need to keep your mouse pointer completely still after it does the transformation, or else they don't work. It barely qualifies as a solution in my book.

That shouldn't happen. I'll investigate.
