### ISSUE TITLE
Images in Gallery-Block are not resized

### ISSUE THREAD

**Issue by markggn** [WordPress/gutenberg#18504]
Images in a Gallery-Block are not physically resized, they are scaled via HTML/CSS. This ends up in a lot of large images beeing loaded when accessing the page.

My gallery consists of 12 images, 8 small in a row and 4 in the second row.

![gallery](https://user-images.githubusercontent.com/7011195/68851330-08e1b880-06d6-11ea-8011-ed962932bb96.JPG)

They are 1.024px × 768px and scaled to 83px × 111px. I would expect an image in the size of 83px × 111px to be created and linked correctly.

**Comment by ellatrix** [comment]
Thanks for the report, @markggn. The image should have multiple sources for the browser to pick from, depending on the size the image should be rendered at. Does that make sense?

The HTML should be something like

```html
<img src="image-768x1024.jpg" alt="" data-id="..." data-full-url="image.jpg" data-link="..." class="wp-image-29" srcset="image-768x1024.jpg 768w, image-225x300.jpg 225w, image-1152x1536.jpg 1152w, image-1536x2048.jpg 1536w, image-1200x1600.jpg 1200w, image-1980x2640.jpg 1980w, image.jpg 1920w" sizes="(max-width: 768px) 100vw, 768px">
```

**Comment by markggn** [comment]
> 
> 
> Thanks for the report, @markggn. The image should have multiple sources for the browser to pick from, depending on the size the image should be rendered at. Does that make sense?

Partly. This is, what WP does:

<img src="image-1024x768.jpg" srcset="image.jpg 1024w, image-678x509.jpg 678w" sizes="(max-width: 1024px) 100vw, 1024px" />

But: The images are still shown as 83px × 111px, scaled down from at least 678px x 509px. Do I need to add smaller sizes for every single image on my blog, just in case?

**Comment by nosilver4u** [comment]
@markggn If you want smaller images to be possible, then yes, you need to add smaller sizes. While some gallery plugins will auto-generate various image sizes for you (leaving a mess all over your server), WP core (and Gutenberg) will only use what already exists for sizes.

Alternatively, there are a few image optimization plugins that would auto-generate extra sizes for you. I'm not sure if Jetpack's image performance module does it, but EWWW Image Optimizer's easy mode does, and I suspect Optimole and Shortpixel adaptive images would do the same.

**Comment by markggn** [comment]
> @markggn If you want smaller images to be possible, then yes, you need to add smaller sizes. While some gallery plugins will auto-generate various image sizes for you (leaving a mess all over your server), WP core (and Gutenberg) will only use what already exists for sizes.

Well, actually, there IS a 200x200 px version of every image. But it seems like it is not used by WP for showing the 83x111 px image (which would be still not okay but much better). Instead, the 678x509 px version or even the full size is shown.

**Comment by nosilver4u** [comment]
It's possible that size is marked as a sort of "hidden" size. See if the Simple Image Sizes plugin lets you toggle that size to available, that might do the trick.

**Comment by markggn** [comment]
No, there's nothing hidden. The 200x200 px is the "normal" thumbnail.

**Comment by ShareTextures** [comment]
I have this problem too. In my galleries, I upload them as 512x512 px. Gutenberg gallery show them as 512x512, Why it can't use the thumbnail? If it can use thumbnail images instead of the full size it's %75 faster to load.  I don't want to re-scale all images as 125x125 because some people want to see full-size images instead of thumbnails. (this is why we use lightbox am I right?)

Is there any trick to do it with Javascript or something?

**Comment by skorasaurus** [comment]
I too, also experience this.

**Comment by padams** [comment]
Pretty sure core srcset generation respects the aspect ratio/orientation of the image. so a 200x200 shouldn't be included for an image that isn't square. 

The bigger issue I see is that picking an image size in gallery edit assumes that you know exactly how large the image will display in your theme. That's not possible all the time especially when you are also specifying "columns" or using some other exotic gallery layout (masonry, mosaic, etc.).

One way around this is push the generation of the image Sizes attribute down to the client by using  CSS `calc()` in the media query. For example, in the case of the grid/column gallery layout use something like `calc( 100vw / ${columns} )` . 

That approach at least makes srcset viable for the images included in a gallery. it doesn't however solve for setting the correct width and height attributes of gallery images for lazy loading -- however I'm not sure that's a huge issue as long as they are just set with something that respects the image's aspect ratio.

**Comment by jordesign** [comment]
This should be resolved with the new implementation of Galleries (from ~12 months ago) so I'm going to close this issue.
