### ISSUE TITLE
Ask user block type when dropping multiple images

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18501]
Support thread: https://wordpress.org/support/topic/uploading-multiple-images-not-intuitive-for-non-geeks/.

Currently, when a user drops multiple images in the editor, a gallery block is created with those images, but the user may not always want to create a gallery.

I would suggest instead to ask the user which block they want to use. This could be an image or gallery block, but also any block accepting multiple images through a transform.

**Comment by mtias** [comment]
I'm on the fence whether asking the user provides a better experience than a common default, specially considering you can transform a gallery into several image blocks already.

**Comment by ellatrix** [comment]
Sure, but that option is more hidden and it may not be so obvious.

**Comment by mtias** [comment]
We should continue to make the transform flow more obvious as it has long lasting benefits.
