### ISSUE TITLE
Use block templates when there is no post_content

### ISSUE THREAD

**Issue by eshannon3** [WordPress/gutenberg#18517]
Use case: updating sites that have previously relied on postmeta for content - such as sites using ACF or page builders, where the main content is not stored in post_content.

Feature suggestion: I really wish Block Templates that are applied to post types would apply for not just new posts, but any post that does not currently contain any post_content.

I am converting several large sites over from using ACF in the past, where we heavily structured content and in many cases there is no post_content at all because it was all templated, over to the Block Editor instead. It is a tedious process that would be much faster if the Block Templates I have defined, which work beautifully for new posts, would also work for existing posts - but the templates aren't applied, I just get a completely blank "Start writing" screen.

The alternative I have is to delete my current posts and build new ones. What I don't like about that approach is, my sites have shortened permalinks, and it's not currently possible to set a permalink before you publish. It's hard to remember to update the permalinks in addition to all of the content, so I run the risk of a lot of 404 errors using this route. It also makes the content appear as though it was created whatever day I publish the new Block Editor version - it doesn't keep the historical published and updated dates, which are valuable for content auditing.

**Comment by ellatrix** [comment]
Hi! You could use the `default_content` filter in PHP to define some default content for new posts. See https://developer.wordpress.org/reference/hooks/default_content/. For example, you could set it to

```html
<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->
```

to start with an image placeholder. I agree that there should be an easier way to do this though. It would be nice if it's possible to use a block template to define default content.

**Comment by eshannon3** [comment]
Thanks for the reply, but that's not what I'm asking. New posts are already covered. My suggestion is, use the block template to add blocks not just to new posts, but also to existing posts when there is no post_content at all and someone is entering the editor.

**Comment by talldan** [comment]
I think this is probably covered by the Block Patterns feature now in that the template can be made into a pattern as well that's easily insertable:
https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/

I'll close this issue.
