### ISSUE TITLE
Can't register block when importing from @wordpress/blocks

### ISSUE THREAD

**Issue by ronka** [WordPress/gutenberg#18519]
Hey, I can't seem to register a block even though it looks like it does register it because registerBlockType function returns a WPBlock object. When I try the same function using the global variable it works just fine.

I use `wp-scripts start` to compile the files.

Do I need to some how mark to WordPress that packages are an external dependencies? if so how?

WordPress 5.3v
Gutenberg plugin 6.9v

Block script:
```
/**
 * Block dependencies
 */
import './style.scss';
import icon from './icon';

/**
 * Internal block libraries
 */
import { __ } from '@wordpress/i18n';
import { registerBlockType } from '@wordpress/blocks';

/**
 * Register block
 */
export default registerBlockType(
	'testtest/example',
	{
		title: __( 'Example Block', 'test' ),
		description: __( 'Demonstration of how to make a static call to action block.', 'jsforwpblocks' ),
		category: 'common',
		icon,
		keywords: [
			'TEST',
			'Example Block',
		],
		edit: ( props ) => {
			const { className } = props;
			return (
				<div className={ className }>
					<h2>{ __( 'Static Call to Action', 'test' ) }</h2>
					<p>{ __( 'This is really important!', 'test' ) }</p>
				</div>
			);
		},
		save: () => {
			return (
				<div>
					<h2>{ __( 'Call to Action', 'culturetrip' ) }</h2>
					<p>{ __( 'This is really important!', 'culturetrip' ) }</p>
				</div>
			);
		},
	},
);
```

package.json:
```
"devDependencies": {
    "@wordpress/babel-preset-default": "^1.2.0",
    "@wordpress/block-editor": "^3.2.4",
    "@wordpress/blocks": "^6.7.2",
    "@wordpress/components": "^8.3.2",
    "@wordpress/data": "^4.9.2",
    "@wordpress/editor": "^9.7.5",
    "@wordpress/element": "^2.8.2",
    "@wordpress/eslint-plugin": "^3.1.0",
    "@wordpress/i18n": "^3.6.1",
    "@wordpress/keycodes": "^2.6.2",
    "@wordpress/scripts": "^5.1.0",
    "@wordpress/server-side-render": "^1.3.4",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "classnames": "^2.2.5",
    "cross-env": "^5.1.5",
    "css-loader": "^0.28.11",
    "eslint": "^5",
    "eslint-plugin-import": "^2.18.2",
    "extract-loader": "^3.1.0",
    "file-loader": "^4.2.0",
    "husky": "^3.0.5",
    "lodash": "^4.17.15",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "postcss-loader": "^2.1.5",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.19.1",
    "stylelint": "^11.0.0",
    "stylelint-config-wordpress": "^14.0.0",
    "stylelint-scss": "^3.11.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.40.2",
    "webpack-cli": "^3.3.8"
  }
```

**Comment by ellatrix** [comment]
Hi! You should import from WordPress dependencies like this:

```js
const { registerBlockType } = window.wp.blocks;
```

Does that work?

**Comment by skurzynowski** [comment]
@ellatrix Why in the codex there is import from `@wordpress/blocks` if it doesn't work. I guess there is some object collector to register all blocks that's why we need to use the already created object? Am I right?

**Comment by ellatrix** [comment]
Could you link the codex page? I'm not sure if it would or wouldn't work, but the recommended way is to use the `wp` global. Maybe @gziolo knows more about the details. :)

**Comment by gziolo** [comment]
Did you follow the tutorial explaining the JavaScript build setup:
https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/

and how to provide the advanced setup for Webpack:

https://developer.wordpress.org/block-editor/packages/packages-scripts/#provide-your-own-webpack-config

I see your code imports CSS so I don't think you use defaults provided by `@wordpress/scripts` listed as one of your dev dependencies.

**Comment by ronka** [comment]
I managed to solve it,
Apparently what was missing is telling webpack to replace any @wordperss npm dependency with a wp global variable.(basically setting webpack externals).
Not sure if it's mentioned any where in the docs, maybe I missed it.

(I didn't use wp-scripts as it didn't fit my project requirements)

**Comment by siddharth-thevaril** [comment]
@ronka Can you please share your `webpack.config.js` file? I'm facing the same problem.

**Comment by dwatts3624** [comment]
@siddharth-thevaril I know it's been a *very* long time since your comment but wanted to document this since I found this thread first and it took me a while to find the solution.

There's actually a Webpack plugin that covers this!  It also handles the dynamic PHP file generation for version & dependencies:
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-dependency-extraction-webpack-plugin/

You can also handle this manually as an alternative.  I ended up going this way since I have a Webpack config that's driving the frontend and block compilation (probably something I'll need to change the in the future but it works for now):
```js
module.exports = {
  externals: { 
    '@wordpress/blocks': 'wp.blocks',
    '@wordpress/block-editor': 'wp.blockEditor' 
  },
};
```
