### ISSUE TITLE
MediaPlaceholder component doesn't allow upload outside Editor context

### ISSUE THREAD

**Issue by abaicus** [WordPress/gutenberg#18511]
Hey guys, 

It seems that the `MediaPlaceholder` component doesn't allow uploads outside the editor context on the backend. I should mention that I'm using this particular block inside a customizer control. 
![image](https://user-images.githubusercontent.com/15010186/68863644-73a3eb80-06f8-11ea-8569-fcf31b2976cd.png)

This seems to be related to the `mediaUpload` API. The way permissions were assessed before is different now. 

Could you guide me as to how I might get this sorted out? 

Thanks!

**Comment by ellatrix** [comment]
I think `MediaPlaceholder` is only meant to be used within blocks.

**Comment by enriquesanchez** [comment]
Closing as this does not seem to be a bug. Please feel free to reopen and clarify if necessary.
