### ISSUE TITLE
Spotify Embeds: Height issue on desktop related to 'Resize for smaller devices'

### ISSUE THREAD

**Issue by mikeicode** [WordPress/gutenberg#18518]
If you choose the setting "Resize for smaller devices" for Spotify embeds the 380px height on the iframe is not used on desktop, resulting in an embed that is too tall.

I think this happened after the WP 5.3 update.

 It appears related to the class `wp-embed-aspect-9-16` on the figure that surround the `embed`. This class adds padding, a different height, and absolute positioning to the iframe inside the embed.

**To reproduce**
1. Add a Spotify embed block to a page
2. Choose 'Resize for smaller devices' option
3. View published page

![img](https://cld.wthms.co/DVMc3M+)

**Expected behavior**

The iframe should be set to 380px high on desktop.

**Result**

The height is too tall:

![img](https://cld.wthms.co/hM7aQ6+)

**Version**

WP 5.3

**Comment by karmatosed** [comment]
In the latest version of WordPress and plugin, without using other plugins I can't seem to replicate having an option for the adjusting. Would you be able t check and see if you are still having the issue, please? If there are still issues, it would be great to see if there is another factor such as a plugin. I'd love to create this for you, thanks for hopefully giving more details.

**Comment by mikeicode** [comment]
I checked now and the option and issue still exist. I tested on 2 separate .org installs, on different hosts. WP 5.3, using the Twenty Nineteen theme (I tested other themes also). All plugins deactivated. I also tried with the Gutenberg 6.9.0 plugin installed but it didn't make a difference.

Here is a video of what adding this block to the page looks like for me:

![img](https://cld.wthms.co/YzuC2Q+)

With the option "Resize for smaller devices" enabled:

![img](https://cld.wthms.co/XrmOf4+)

With that option not enabled:

![img](https://cld.wthms.co/VDBPji+)

**Comment by carinapilar** [comment]
I got a report for this on #12964601-hc. User reported that before the update the embed was full width and the high was responsive.

@karmatosed, I was able to replicate the issue on an AT site with the Pique theme.

**Comment by westonruter** [comment]
I believe I've found the reason for why the issue is no longer occurring. See #25972.

**Comment by mikeicode** [comment]
Just ran into this again on a .com hosted site.

**Comment by noisysocks** [comment]
This came up here: https://wordpress.org/support/topic/spotify-block-enlarged-after-wp-update/#

The [embed code in the Spotify docs](https://developer.spotify.com/documentation/widgets/generate/embed/) has the iframe width set to 300 and the height set to 380. Maybe Gutenberg could force this?

**Comment by noisysocks** [comment]
Closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/27720 since that one has a potential fix in the description.
