### ISSUE TITLE
Navigation Block: "top pages" is ambiguous 

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#18522]
In the navigation block placeholder, the button "Create from all top pages" is ambiguous. Is this my pages with the highest traffic? I know it's not, but it could easily be read this way and think that top means "best" in some way.

Although it feels more technical "top-level" is used elsewhere in wp-admin. So "Create from all top-level pages" seems better, although possibly a touch long.

<img width="416" alt="Screen Shot 2019-11-14 at 8 49 41 AM" src="https://user-images.githubusercontent.com/1464705/68878162-15591780-06bc-11ea-8d38-91ffa8c93604.png">

**Comment by draganescu** [comment]
I think @apeatling is right and `top level` is the correct formulation.
