### ISSUE TITLE
syntax error on line 1059 in file ../wp-includes/functions.php

### ISSUE THREAD

**Issue by tevaw19108** [WordPress/gutenberg#18524]
i want to report syntax error on line 1059 in file ../wp-includes/functions.php

please confirm.

php version 5.5

**Comment by hai991dk** [comment]
please upgrade PHP version >7.x

**Comment by ellatrix** [comment]
Thanks for the report! It looks like the error is coming from WordPress core. Could you report the issue here: https://core.trac.wordpress.org/newticket?
