### ISSUE TITLE
Windows: add non breaking space shortcut

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18523]
Alt+Space doesn't seem to work on Windows. It's the standard shortcut in Word, so it doesn't hurt to add it. On a Mac, this shortcut is built in.

See https://wordpress.org/support/topic/adding-nbsp/.

**Comment by yankiara** [comment]
+1000

**Comment by tybor** [comment]
> Shift+Ctrl+Space doesn't seem to work on Windows. It's the standard shortcut in Word, so it doesn't hurt to add it. On a Mac, this shortcut is built in.
It is also an almost ubiquitous shortcut on Linux too and in LibreOffice. I've been routinely using it for at least 10 years

**Comment by fr-laurentn** [comment]
I totally agree. It's painful to edit in HTML mode and add &nbsp;

**Comment by rezeau** [comment]
Totally agree, an absolute must. In French typography, the "double" punctuation signs ; : ! ? need to have a (non breaking) space between them and the word placed before them.

**Comment by TonyGravagno** [comment]
I'd like to keep this one alive. Keyboard shortcuts for Text Formatting include ctrl+b, ctrl+shift+k, etc. These hotkeys transparently modify the underlying markup. A new shortcut like ctrl+shift+space (compatible with other apps) should take the existing character(s) and convert each of them to "&nbsp;".

Perhaps this clear description will help to ease the implementation. If this is approved I might take a shot at the code myself.

Thanks.

**Comment by fr-laurentn** [comment]
For the record, I've noticed that it seems fixed with WP 5.6.2.

I haven't tried on a fresh install, but I've noticed on various websites that using ALT+255 on Windows now creates a non-breaking space.

**Comment by tybor** [comment]
Il 26/02/21 08:53, Laurent Naudier ha scritto:
>
> For the record, I've noticed that it seems fixed with WP 5.6.2.
>
> I haven't tried on a fresh install, but I've noticed on various 
> websites that using ALT+255 on Windows now creates a non-breaking space.
>
No, it hasn't been fixed. You're using a word-around. The old editor has 
a nice shortcut available on all systems. I would like to get it back
>

**Comment by ellatrix** [comment]
Would be great if someone else can attempt this. It's a good first issue and I don't use Windows personally.

**Comment by pierrefrance** [comment]
How do you add a unbreakable space in Gutenberg editor using mac ? Using windows, we can enter an alt-code but with mac, nothing seems to work.

**Comment by ellatrix** [comment]
Shift+Option+Space (= Shift+Alt+Space)

**Comment by noisysocks** [comment]
Let's be sure to make this shortcut work on Linux too.

**Comment by tybor** [comment]
Il 09/03/21 21:09, Ella van Durpe ha scritto:
>
> Shift+Option+Space (= Shift+Alt+Space)
>
Tried on Win10, the shortcut Alt+Space opens the menù of the current window

**Comment by tybor** [comment]
Il 16/03/21 06:29, Robert Anderson ha scritto:
>
> Let's be sure to make this shortcut work on Linux too.
>
No, it doesn't work on Linux. I tried Shift-Alt-space and 
Shift-Super-space on win10 and they don't work too. The first opens the 
menù of the current window, the second change the keyboard layout

**Comment by ellatrix** [comment]
The shortcut I mentioned above only works for Mac. On windows there's no shortcut, hence the issue.

**Comment by burnuser** [comment]
I need non breaking space in WordPress on Windows each day! (That's a main reason why I'm still working with classic editor.)
Any chance for an implementation of this classic feature in Gutenberg in the near future?

**Comment by rezeau** [comment]
Again, I agree with @burnuser and others. A simple shortcut is needed. The most natural one being, IMHO, Shift+Space bar.

**Comment by zackkatz** [comment]
I'm adding my vote for `Option + Space` on the Mac.

**Comment by benjaminpwarren** [comment]
Shortcut for Windows is ALT+0160.

**Comment by t-hamano** [comment]
I am a Windows user and would like to work on this issue.
