### ISSUE TITLE
Editor scrolling while typing in Microsoft Edge

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#18546]
While working on the support forums, I saw several reports suggesting that we have issues with Edge while if you type on long posts, the post keep scrolling to the top.

I didn't not confrm the bug yet, but I'm marking it as high priority.

**Comment by NongBenz** [comment]
Same. New bug also on Edge. Every input scrolls the whole page to the top so you can't finish any post.

**Comment by gwwar** [comment]
@youknowriad let us know if you need help testing, I believe we had one report of this behavior with WP 5.3 latest and the Gutenberg plugin disabled.

**Comment by NongBenz** [comment]
That report helped me. Downloading and aciviting the Gutenberg plugin fixed the issue in vanilla Wordpress. I've read downloading Classic Editor may also help.
https://wordpress.org/plugins/gutenberg/

**Comment by ellatrix** [comment]
Sounds like a typewriter bug. I'll try to reproduce.

**Comment by ellatrix** [comment]
I cannot reproduce on Windows 10 with Edge 18. What versions are you using?

**Comment by youknowriad** [comment]
(I didn't test personally but saw several reports in the forums)

**Comment by youknowriad** [comment]
So, it seems like we didn't backport this particular fix https://github.com/WordPress/gutenberg/pull/17707 into WordPress 5.3 :( 

Let's make sure it gets included in 5.3.1
