### ISSUE TITLE
General Interface: Usability issues with Inserter on desktop monitors with large width

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18568]
Originally reported on the Gutenberg plugin support forum by [slkfsdf8y34ljhsfsdfkuhfkl84hj](https://wordpress.org/support/users/slkfsdf8y34ljhsfsdfkuhfkl84hj/) at https://wordpress.org/support/topic/two-suggestions-how-to-make-gutenberg-great-on-desktop-monitors/:

> This video explains a big problem that people have with desktop monitors and Gutenberg.
> 
> It explains the issues and provide two simple solutions as a suggestion.
> 
> https://www.youtube.com/watch?v=OfSJy6P1hUA
> 
> If implemented, these will dramatically increase the productivity for people using desktop monitors

**Comment by youknowriad** [comment]
Closing cause the video has been removed so can't really know what are the raised issues.
