### ISSUE TITLE
Classic change EventListener fires multiple times on page template select change

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#18578]
I want to add specific blocks to the block editor content, when the page template is changed. For that, I added a classic `change` event listener to the page template select. The issue is, that – sometimes – this event is fired multiple times when the select value changes, so I end with multiple new blocks. For example, when nothing is selected in the content area, I get two change events.

I already tried throttling them, to be able to check if the specific block is already in the post content, but it seems that the events are fired exactly at the same time.

I guess it has something to do with the Gutenberg way to update the select, but I am not sure. Can someone help me or give me a hint how to prevent the event from getting fired multiple times?

**Comment by youknowriad** [comment]
You should not be relying on DOM to detect changes as DOM is not considered an official API, I'd suggest taking a look at the data module.

you should subscribe to the data module  using `wp.data.subscribe` and ensure you trigger your callback only when the value of the template changes ` wp.data.select( 'core/editor' ).getEditedPostAttribute( 'template' )`

I hope this helps.

**Comment by florianbrinkmann** [comment]
> I hope this helps.

Yes, it does, thanks a lot @youknowriad!
