### ISSUE TITLE
HTML block: expanding option

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18570]
I am unsure if this exists still but using Twenty Twenty/Nineteen, there is no option to expand this block. Someone on the support forums reports they used to be able to do this and it was useful for them.

> I use the HTML-block to write entire pages in HTML code, on many wordpress websites. The html-block in Gutenberg allowed for enlarging it by dragging the lower righthand corner. With the latest update of WP this is no longer possible. 
https://wordpress.org/support/topic/html-block-gutenberg-no-longer-extendable/

I see both the code editor and HTML block are unable to expand.

![image](https://user-images.githubusercontent.com/253067/69051622-c0d7d400-09fc-11ea-96b2-7fa6ba4dab76.png)

![image](https://user-images.githubusercontent.com/253067/69051652-d64cfe00-09fc-11ea-88e8-6b93c6ff5ae5.png)

Also, it might be good to along with this add in the ability to set to full width for this, for example, if someone is using HTML block for layout.

**Comment by raoulunger** [comment]
Thanks for picking this up ( I was the one mentioning it in the forum).
To clarify: this is not specifically related to the Twenty Twenty/Nineteen theme, but to any theme the Gutenberg builder is used in (I'm using the Bootstrap boilerplate).
The possibility of making the block full width is a very good suggestion! I'm presently using a plug-in for that, but I think it would be good for WP to provide this out of the box. Many developers code within Wordpress, and the narrow blocks make code much more difficult to read, especially in case of longer lines, such as <img tags>. (The same holds true for the custom css panel...)

Thanks!

**Comment by carolinan** [comment]
I am not able to reproduce this. The HTML block has a drag handle in the bottom right corner.
The code editor mode is expandable by adding a new line.
Tested on macOS with Safari, Firefox, Chrome.

**Comment by karmatosed** [comment]
I also can't anymore so going to close this.
