### ISSUE TITLE
Unable to post，”The release failed. Error message: this response is not a valid JSON response.“

### ISSUE THREAD

**Issue by NewDoer** [WordPress/gutenberg#18585]
Today, I just updated to version 5.3. After writing a new post on Gutenberg system, I clicked "publish", which prompted the following error：
”The release failed. Error message: this response is not a valid JSON response.“
I tried the following methods, but they could not eliminate the error:
1. Disable all plug-ins
2. Change to the default theme
3. Disable REST apis
Gutenberg editor I think is cool, please help me how can I make sure it works。Thank you！
My email is 5330555@qq.com

**Comment by youknowriad** [comment]
I suspect that you have php errors, warning or notices in your installation (REST API) causing this issue.

You can check the response of the network request causing this error (network tab of your browser's developer tools) or you can check your server's error log to see if you can find any errors.

**Comment by gziolo** [comment]
There are 3 more similar issues filed after this one. Should we consolidate them?

**Comment by youknowriad** [comment]
Closing as stale. In general these issues are related to plugin conflicts in some cases, server config in most cases. Ideally the reporter should check similar issues and debug his install. We should close these issues.
