### ISSUE TITLE
Persist and weight recently used blocks

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#1859]
## Current Behavior

The current simple implementation of the recently used blocks just puts whatever you've used most recently at the top, and at the start of a new post it populates with blocks from the common category.

## Expected Behavior

The blocks have some kind of weighting, so that we persist usage data and display more frequently used blocks first.

Open for discussion!

**Comment by westonruter** [comment]
Depends on having an endpoint for persisting the recently-used blocks: #1455.

**Comment by danielbachhuber** [comment]
> The blocks have some kind of weighting, so that we persist usage data and display more frequently used blocks first.

What would this weighting algorithm be?

**Comment by mtias** [comment]
Done in #5342.
