### ISSUE TITLE
Navigation: Markup is broken

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#18604]
Markup is broken since it doesn't escape the characters in the link title.
<img src="https://user-images.githubusercontent.com/77539/69142557-d81ecc00-0aa5-11ea-9037-c8e52605d7ab.png" width="353" />
<img width="353" alt="Screen Shot 2019-11-19 at 8 26 45 AM" src="https://user-images.githubusercontent.com/77539/69142844-6e52f200-0aa6-11ea-907e-e715602c62b5.png">

**Comment by draganescu** [comment]
Hi @retrofox what are the steps to reproduce this bug?
