### ISSUE TITLE
Consider other ways to offer configuration of blocks shown

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18606]
I know there are ways to turn on and off blocks, however, someone in the forums proposed adding more options to this and perhaps it's something worth exploring. I raise it here as a discussion point: 

> Even just some constants or an array in wp-config would suffice for configuring which blocks are loaded, or even a function that can be added to functions.php.

https://wordpress.org/support/topic/extends-the-power-of-wordpress/

**Comment by draganescu** [comment]
What I know we have is the interface below:

<img width="402" alt="Screenshot 2019-11-19 at 17 45 06" src="https://user-images.githubusercontent.com/107534/69161833-66ba3a00-0af4-11ea-954b-df55720ea1a0.png">

> Even just some constants or an array in wp-config would suffice for configuring which blocks are loaded, or even a function that can be added to functions.php.

This sounds interesting and there is a way to do it in code via plugin or theme functionality by using the `allowed_block_types` hook and return only the ones you want.

**Comment by karmatosed** [comment]
@draganescu can you use that function in wp-config or functions.php? I assume yes to later and no to wp-config?

**Comment by draganescu** [comment]
You assume right :) it is not something done in wp-config as those there are low level parameters, while what block are available are higher level and can be decided by themes and/or plugins.

**Comment by mtias** [comment]
@karmatosed I think it'd be worth folding into #15121 as part of improvements to the manager.

**Comment by karmatosed** [comment]
Closing in favour of taking conversation to #15121, thanks.
