### ISSUE TITLE
How can I get "Reusable Blocks" as menu item

### ISSUE THREAD

**Issue by murshed** [WordPress/gutenberg#18603]
**Describe the bug**
When I create a block as "Reusable" and I can't find a Reusable block on the menu. It has no own menu.

**To reproduce**
https://theme.test/wp-admin/edit.php?post_type=wp_block

**Screenshots**
I can get that from
- https://i.imgur.com/9ncAC5y.png

but it has no menu item > https://i.imgur.com/sXthWT6.png

**Comment by youknowriad** [comment]
Duplicate of #13390
