### ISSUE TITLE
Overriding Gutenberg Styles

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#18612]
The Gutenberg editor has lots of styles automatically loaded and thats ok.

However i find it tedious to override if I want it to match the front end of my theme as some of the styling is very deep and nested to a high degree.

For instance, the default layout uses margins and paddings that wont always match up on the front end. 
In fact my theme assumes alignwide is container/wrap width, while alignfull is 100% full screen. However this does not seem to be the case on the back end, and as a result things don't line up at certain screen sizes (see below how the text of the purple alignfull section does not line up with the align wide section above it)

![Screenshot 2019-11-19 10 05 05](https://user-images.githubusercontent.com/11615474/69158723-e0323800-0ab4-11ea-9de2-98ca09a88512.png)

I was able to get this working by adding my own styles to the back end, however it was not easy and required large css selectors that scared the living $h!t out of me. 

Selectors like: 
```
//removed negative margins for alignwide and add your own negative margins
.edit-post-visual-editor .block-editor-block-list__block .block-editor-block-list__block-edit,
.block-editor-block-list__layout .block-editor-block-list__block[data-align="full"] > .block-editor-block-list__block-edit {
	margin: auto;
}

//add our themes negative margins to actual block
.block-editor-block-list__layout .block-editor-block-list__block[data-align="full"] {
	margin-left: calc(-1 * var(--container-padding)); //negative margins to counteract the containers padding
	margin-right: calc(-1 * var(--container-padding));
}
```

**Why did the css selectors have to be so deep?** 

On top of that there is styling embedded at the top of the page. Styles like the font family that will be used which overrides the themes font on the back end which was applied via the custom Gutenberg  stylesheet.

**Comment by 1sd15** [comment]
This too have been the bane of my work. Especially with SVG's as their scaling get's changed by the un-removable backend Guttenberg Blocks. At this point I think I would rather style the display of the blocks myself.

**Comment by mtias** [comment]
The new theme.json introduction should make disabling and modifying core styles a lot easier.
