### ISSUE TITLE
Components: RangeControl: initialPosition 0 does not work

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#18610]
**Describe the bug**
![Screen Shot 2019-11-19 at 9 06 11 AM](https://user-images.githubusercontent.com/2322354/69153285-eff94e80-0aab-11ea-8bd1-a3d7bd593909.png)

Setting the `initialPosition` of `0` does not work with `RangeControl`. When it is set to `0`, it is set to the middle instead.

**To reproduce**

Try the following code:
```jsx
<RangeControl
  initialPosition={ 0 }
  value={ null }
  label={ label }
/>
```

**Expected behavior**
Initial value to the `0`, if set to `0`.

**Additional context**

The reason for this issue is the ternary used to determine the `initialSliderValue`, specifically this part:

```
initialPosition || ''
```

Zero should be a valid value, but it is not when piped. I feel like the solution should be checking to see if the `initialPosition` is defined, rather than truthiness.

Example:

```js
const initialFallbackValue = ! isUndefined( initialPosition ) ?
  initialPosition : '';

const initialSliderValue = isFinite( currentInputValue ) ?
  currentInputValue : initialFallbackValue;
```

**Comment by mtias** [comment]
Also #4420.
