### ISSUE TITLE
Firewall recommendations for Gutenberg/REST API

### ISSUE THREAD

**Issue by amandablum** [WordPress/gutenberg#18615]
There are a multitude of reports across the web of 403 errors when updating WordPress while employing Gutenberg, and they happen either for a variety of reasons, or Gutenberg is so new that no one is really nailing the problem, because it seems as if most people don't find resolve. 

In our case, its a firewall issue. So I think it would be helpful to develop a guide on what settings your firewall should have to best avoid 403 issues. I'm working with Sitelock at the moment, but I'm reading about plenty of use cases from Cloudflare as well. 

Its unrealistic to expect that WP users will just avoid using firewalls, so working with these services to develop best use practices seems smart.

**Comment by youknowriad** [comment]
💯

I think a REST-API trac ticket could be better in that case, there might be more people there to weight-in.

**Comment by mburridge** [comment]
Closing this as doesn't appear relevant to this repo.
