### ISSUE TITLE
Navigation: handle special chars in Editor canvas

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#18613]
Currently, the Navigation is not handling rightly the special chars when the links are created from the blog posts/pages.

**Comment by draganescu** [comment]
Hi @retrofox can you detail this a bit more? Is it diacritics in manual links or what kind of special chars?

**Comment by retrofox** [comment]
> Hi @retrofox can you detail this a bit more? Is it diacritics in manual links or what kind of special chars?

Hi Andrei, I'm sorry I forgot to link the PR 🤦‍♂ #18617
