### ISSUE TITLE
How to add Media Upload permissions in the block editor?

### ISSUE THREAD

**Issue by arnvanhoutte** [WordPress/gutenberg#18625]
I have implemented the standalone block-editor in my website, but that one doesn't seem to support media upload. Upon reading the documentation I noticed that I could handle the "hadUploadPermission" in the editor provider, but not in the block-editor-provider. The documentation does mention the MediaUpload component but gives no example on how to set this up: https://developer.wordpress.org/block-editor/

**Comment by youknowriad** [comment]
for standalone usage, you just need to provide a `mediaUpload` function (function called to upload the media and return the uploaded object, see the default one for an example) and provide it as a setting to the BlockEditorProvider https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/provider/index.js#L113.

**Comment by arnvanhoutte** [comment]
I have done that, but I still don't get an upload button on my image block
