### ISSUE TITLE
How to add Media Upload permissions in the block editor?

### ISSUE THREAD

**Issue by arnvanhoutte** [WordPress/gutenberg#18628]
This is in response to #18625.

I've added a `mediaUpload` function to the settings of my block-editor-provider but still no success. If I add a gallery-block I get an error saying that `mediaUpload is not a function`. Yet when I look at the block-editor-provider with the console, I can clearly see that the settings.mediaUpload parameter is a function

![image](https://user-images.githubusercontent.com/5654490/69230819-4045de80-0b88-11ea-981e-f62d3aef14fe.png)

I've tried expanding the settings object with SETTINGS_DEFAULTS  from `@wordpress/block-editor` but that doesn't change it either

**Comment by youknowriad** [comment]
it might be __experimentalMediaUpload in the previous versions. (It depends on the package version you're using)

**Comment by youknowriad** [comment]
Also, please not that this issue tracker is not used for help request.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you

**Comment by arnvanhoutte** [comment]
`__experimentalMediaUpload` did the trick. Thank you, and my apologies

**Comment by simulieren** [comment]
I also struggled with this. The documentation is almost non-existent for [this `mediaUpload` setting](https://github.com/WordPress/gutenberg/tree/4c472c3443513d070a50ba1e96f3a476861447b3/packages/block-editor#SETTINGS_DEFAULTS).
I will leave my steps to the solution here so other people will have an easier time when creating their standalone Editor with Gutenberg. 

---

First I had to create a function called mediaUpload:

```js
const mediaUpload = (e) => {
  // Upload a file somewhere or do something else here
  const data = {
    alt: "ALT TEXT",
    caption: "CAPTION TEXT",
    title: "TITLE TEXT",
    url: "https://images.unsplash.com/photo-1593642532454-e138e28a63f4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
  }

  // Call this at the end to update the block editor
  // This has to be an array
  e.onFileChange([data])
  // Return the data as an array
  return [data]
}
```

Add this function to a settings object:

```js
const settings = {
  ...
  mediaUpload
  ...
}
```

Pass the settings object to the `BlockProvider`.

```js
<BlockEditorProvider
  value={blocks}
  onInput={updateBlocks}
  onChange={updateBlocks}
  settings={settings}
>
```
