### ISSUE TITLE
Components: Popover: Arrow flashing at top

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#18636]
**Describe the bug**
When toggling between Toolbar/menu items that have a dropdown/popover, the arrow (triangle) of the Popover flashes at the top centre of the screen.

**To reproduce**
1. Create a block
2. Click on an item in the Toolbar
3. Press tab to cycle between items
4. Observe the top centre of the screen

**Expected behavior**
The Popover menu/arrow should (appear to) render together

**Screenshots**
![Screeny Video Nov 20, 2019 at 10 02 59 AM](https://user-images.githubusercontent.com/2322354/69251497-7a5eb280-0b7f-11ea-8630-df49425b4bba.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version  78.0.3904.97

**Comment by paaljoachim** [comment]
Hey Jon @ItsJonQ 

I will go ahead and close this issue. If I am mistaken then please reopen.
