### ISSUE TITLE
Creating and utilizing an official Triage team.

### ISSUE THREAD

**Issue by nerrad** [WordPress/gutenberg#18634]
Now that github has the ability to assign people to a triage role, we discussed in the [latest slack meeting](https://wordpress.slack.com/archives/C02QB2JS7/p1574259369277500) (slack link) that it'd be good to take a bit of time to formalize a triage team as a way for people to contribute to the project.  This issue is a master issue to track the things that will help this succeed:

* [x] Create Github triage team. (@youknowriad )
* [ ] Document how to self-triage and how to run a triage session.  Emphasis should be placed on the value of self-triaging but there is value in group sessions as well (note we already have a APAC triage session happening and it'd be great to start a US/UK session as well).
* [ ] Document the purpose of the triage team/group/role and expectations.
* [ ] Post a list of mentors/triage crew somewhere.

**Comment by karmatosed** [comment]
So excited about this. Just adding a link from the design team that we can use as fuel: https://make.wordpress.org/design/handbook/workflows/weekly-design-triage/.

**Comment by youknowriad** [comment]
Team created https://github.com/orgs/WordPress/teams/gutenberg-triage-team/members
Let me know if anyone wants to be added.

**Comment by karmatosed** [comment]
I have begun to create a document to work on the text for this: https://docs.google.com/document/d/1URq7G2QmhC1jOyKWpAGYdFCp6SyY9oJrOtU8_YgX2GU/edit?usp=sharing

**Comment by talldan** [comment]
I'd like to get involved in the team as a mentor or crew member.

**Comment by karmatosed** [comment]
@talldan I would love you to help edit that doc above, it's ready for more eyes :)

**Comment by talldan** [comment]
Oh, didn't see that originally. I've added some suggestions @karmatosed.

**Comment by karmatosed** [comment]
Thanks @talldan

**Comment by nerrad** [comment]
I've added some suggestions to the doc as well.  It looks like it's shaping up pretty good and we could submit a pull to update the existing doc with this?
