### ISSUE TITLE
Editor broken after wordpress update

### ISSUE THREAD

**Issue by iheartsearch** [WordPress/gutenberg#18639]
**Describe the bug**
After the recent wordpress update, my post editor looks broken... the block selection menu is weird and acts not normal as before.

**Screenshots**
![gutenberg broken](https://user-images.githubusercontent.com/58001523/69257456-c03d6a00-0bc3-11ea-98fc-20f348f10fcb.png)
![gutenberg ](https://user-images.githubusercontent.com/58001523/69257559-ea8f2780-0bc3-11ea-87b8-400cdeb56e15.png)

Thanks

**Comment by youknowriad** [comment]
Hi There!

Which browser are you using? 
Did you try disabling your plugins to see if it's coming from one of them?

**Comment by iheartsearch** [comment]
1) I am afraid to disable plugins to not break some important parts of the website... 
2) I am using Chrome.
3) Unfortunately, I can't switch theme... at least not when the website is live with traffic

**Comment by youknowriad** [comment]
If you can install plugins, install “Health Check”: https://wordpress.org/plugins/health-check/. On the troubleshooting tab, you can click the button to disable all plugins and change the theme for you, while you’re still logged in, without affecting normal visitors to your site.

**Comment by iheartsearch** [comment]
So after I switched to my theme under Troubleshooting mode, it happened again.

**Comment by youknowriad** [comment]
I guess you have something wrong in your theme affecting the styling of the editor. Probably some stylesheets loaded in the editor.

**Comment by iheartsearch** [comment]
OK, I will check out with my theme provider.
