### ISSUE TITLE
Make the open in the new tab defaut

### ISSUE THREAD

**Issue by skuhar2** [WordPress/gutenberg#18633]
Hey i was using wordpress 5.3 in my website and the thing is as if we add a new link in the text editor of wordpress it shows the option of making the link tab open in new window so is there any way i can make that option default enable for making link tab open in new window
![github support](https://user-images.githubusercontent.com/16589329/69246463-c6851380-0bce-11ea-8638-54dbc201217e.png)

**Comment by talldan** [comment]
Hi @skuhar2 Thanks for reaching out with the suggestion. I don't think that's possible and it's unlikely that this option would be enabled by default. I'll close this issue in favour of https://github.com/WordPress/gutenberg/issues/19015 which suggests making this configurable.
