### ISSUE TITLE
MailChimp Block Success Message has White Text

### ISSUE THREAD

**Issue by marcuswisecaesar** [WordPress/gutenberg#18647]
**Describe the bug**
First noticed in 2482935-zen on a Simple Site when adding a Jetpack Mailchimp block, the success message after submitting an email address comes through as white text on the white background of the site. 

**To reproduce**
1. On a core WordPress.com site add the MailChimp Block to a Page.
2. Publish the Page.
3. View the Page and enter a test e-mail address into the Form.
4. You will see Processing, but then nothing...

**Expected behavior**
Expected to see Processing message, and then Success as set in the Block Editor.

**Screenshots**
![screenshot](https://cld.wthms.co/TS7CNy+)
[Direct Link](https://cld.wthms.co/TS7CNy)

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - Browser: Chrome 
 - Version: 78

**Comment by jorgefilipecosta** [comment]
Hi @marcuswisecaesar, thank you for reporting this issue. Mailchimp is not part of the core blocks offered I moved this issue to the JetPack repository https://github.com/Automattic/jetpack/issues/14087.
