### ISSUE TITLE
Cleanup of stale branches

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#18655]
Currently there are 550 branches in the Gutenberg repository.

It seems like the branches are not being automatically deleted once a PR is merged. 

GitHub offers a feature to do that: https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by youknowriad** [comment]
Thanks for the suggestion, it's actually already enabled. If you take a look at the number of open PRs, the number of plugin release branches, and the number of WordPress release branches. We'll get close to 550 branches. We probably have a few orphan branches but I think the number is very small.
