### ISSUE TITLE
Embed blocks -- Always give a choice for "convert to link"

### ISSUE THREAD

**Issue by waviaei** [WordPress/gutenberg#18653]
**Is your feature request related to a problem? Please describe.**

When you copy an paste URL into a paragraph block, it will try to automatically convert to embed block, and use oembed to embed that content. While this is usually great, particularly with media e.g. YouTube, it is not always the case. There are at a time you don't want to embed, rather, you just want to display a url in plain text or text link where text is the url.

The only way I found so far is to use HTML block to write HTML myself... frustrating.

Currently, if it is not oembed-able, the block gives you option to "Convert to link". Please add an option to do this for any embed block, even if it is embeddable.

E.g. When pasting WordPress site link, no way to convert to a link.

![2019-11-21 16-22-51 2019-11-21 16_30_54](https://user-images.githubusercontent.com/1564991/69316507-52a14480-0c7c-11ea-9aa0-404becfce921.gif)

e.g. same when pasting YouTube link.

<img width="709" alt="スクリーンショット 2019-11-21 16 24 24" src="https://user-images.githubusercontent.com/1564991/69316520-592fbc00-0c7c-11ea-8c2f-00e3f2f2835c.png">

**Describe the solution you'd like**

I think, it is ok to automatically convert. But allow to have option to Convert to link, when one click Edit block button. In a same way as when a block fail to oembed

_There is Convert to Link button!_
<img width="713" alt="スクリーンショット 2019-11-21 16 24 45" src="https://user-images.githubusercontent.com/1564991/69316610-8da37800-0c7c-11ea-9ea8-f12e9a81e9cb.png">

**Describe alternatives you've considered**

Not "alternative" as such, but it would be nice to have a setting in "three dots >> Options" modal. So that one can perhaps check a checkbox e.g. "Turn off automatic embed" or something...

**Comment by karmatosed** [comment]
I think this makes sense to explore, although I feel it could do with some work in how it looks to avoid multiple buttons. Let's put the 'needs design' label on so that can happen.

**Comment by karmatosed** [comment]
Here is one potentially minimal idea, by adding to the text the option. Once you clicked that the screen would then change.

![image](https://user-images.githubusercontent.com/253067/81694560-5f4b6c00-9459-11ea-9298-e6f8ad5f1338.png)

<img width="701" alt="4" src="https://user-images.githubusercontent.com/253067/81694902-cc5f0180-9459-11ea-8053-d58142927ea1.png">

More of the copy might have to change, but the idea is it adapts to your choice.

The benefit of this is avoiding multiple buttons, but there could be discoverability failings. It's really a case of working out if those are worth it for this instance.

**Comment by karmatosed** [comment]
I am going to close this to merge into #21789 as there are a lot of similarities and we can then focus on one solution, hope that works.
