### ISSUE TITLE
Navigation Block: not fully functional for contributor role due to `getEntityRecords` records issue

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#18659]
When using the Nav Block as a user with the `Contributor` Role to the "Create from Pages" option in the placeholder will never work. This is because of a potential "bug" with `getEntityRecords` (which is infact potentially a bug with the REST API - @youknowriad may be able to shed additional light on this).

As it stands Blocks need to avoid `getEntityRecords` in favour of `apiFetch` directly until this bug is resolved.

In order that Nav Block can land we need to swap out the usage of [this selector](https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/block-library/src/navigation/edit.js#L208) for `apiFetch()` directly.

**To reproduce**

1. Create a User with `Contributor` Role.
2. Create some Pages (_not_ Posts!).
3. Create a new Post and add the Nav Block.
4. See the `Create from all Top Pages` button is always disabled.

**Expected behavior**
The Block placeholder should load and show the option to create from Pages for all Roles.

**Screenshots**

![Screen Capture on 2019-11-21 at 09-59-52](https://user-images.githubusercontent.com/444434/69328191-b4df5280-0c46-11ea-8978-ccd4ee3f4258.gif)

**Additional Context**

See also:

* https://github.com/WordPress/gutenberg/issues/18661
* https://core.trac.wordpress.org/ticket/45252

**Comment by getdave** [comment]
After investigating I'm not sure I see this as a Blocker. The Block UI handles the lack of Page data gracefully and the Block is still usable even if you can't auto create from Pages.

As Contributors can't access Pages anyway it could be argued that this should be the correct state.

This is progressive enhancement in action.

**Comment by getdave** [comment]
@youknowriad I'm not 100% as to whether this is still considered a "bug" or whether it is an intended feature of the permissions system?

**Comment by youknowriad** [comment]
I personally think it's probably still a bug, because a contributor has access to these pages "view" so it should be possiible to use them to create menu items. We're not editing these pages here right?

**Comment by getdave** [comment]
> We're not editing these pages here right?

Not as I understand it. Text labels for menu items shouldn't be related to the underlying entities. That said I am aware that folks wanted to be able to create Pages from the Nav Block interface.

**Comment by mtias** [comment]
@youknowriad I think we should actually disable this block for contributors and authors since there is not clear use of it in those contexts.

**Comment by getdave** [comment]
> @youknowriad I think we should actually disable this block for contributors and authors since there is not clear use of it in those contexts.

@mtias is this still your opinion? Because this Issue may need reopening soon and it could be a lot simpler to disable the block from being registered based on user role.

**Comment by mtias** [comment]
Yes, I think so. There might still be contexts in which it's desirable that this blocks _renders_ properly, even if it's not editable by the current user.
