### ISSUE TITLE
E2E Test Utils: `createNewPost` should reset to an initial state, avoid navigation

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18668]
Previously: https://github.com/WordPress/gutenberg/pull/18662#discussion_r349048122

Most of our end-to-end tests are written with a `beforeEach` or `before` lifecycle method to create a new post, in order to assure an isolated environment in which the test cases can be run. Naturally, since `createNewPost` requires a full page navigation, this setup work can contribute significantly to the overall runtime of the test suite.

Since most all of the editor state should be contained within the [`data` module](https://github.com/WordPress/gutenberg/tree/master/packages/data), it may be possible to track the initial state of a new post the first time a navigation occurs, then subsequent calls to `createNewPost` would simply reset to that initial state, rather than perform their own full page navigation.

Not all state can be accounted-for in `data`, and may need to be manually adjusted:

- Scroll position
- Active focus element
- [...others?]

**Comment by paaljoachim** [comment]
I see a bunch of PRs have been merged so that I will go ahead and close this issue.

@gziolo (Greg. This is the last issue. As I would rather not close an issue when the author will likely not be available to reply.)

**Comment by gziolo** [comment]
It would be a nice optimization but it's probably fine to close given that nobody worked on it for so long.

**Comment by paaljoachim** [comment]
@WordPress/gutenberg-core 
I am bringing this older issue by Andrew to a broader aspect of devs and others so it becomes more visible.
I closed it based on a merged PR, but as Greg is mentioned it is a nice optimization to get included.
It is closed but anyone can go ahead and reopen it and put it on their list.
