### ISSUE TITLE
Cover block focal points rounding

### ISSUE THREAD

**Issue by dzoniub** [WordPress/gutenberg#18665]
**Describe the bug**
When creating cover block, and selecting focal points in inspector, values for focal point x or y aren't rounded properly when you switch to code editor. For example, when selecting the focal point x to be 14%, and y to be 57%, when you switch to code editor, the gutenberg tag for focal points will be `"focalPoint":{"x":0.14,"y":0.57}` but in the style attribute these values aren't rounded, `background-position:14.000000000000002% 56.99999999999999%` is what is generated in style. For some other values, the bug is there no more, for example if you put 1%, it will be rounded up nicely in style.

**To reproduce**
1. Go to gutenberg block editor.
2. Create cover block.
3. Assign focal points to values: x:14%, y:57%.
4. Switch to code editor view, and check the `background-position` style attribute generated by the block.

**Expected behavior**
The values in style attribute should correspond to the ones that are given through `focalPoint` tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/30981201/69342499-fafadd00-0c6b-11ea-9acc-d26b724c6e72.png)
![image](https://user-images.githubusercontent.com/30981201/69342544-10700700-0c6c-11ea-8528-e363234e78cf.png)

**Desktop (please complete the following information):**
 - MacOS Mojave
 - Bug reproduced in Google Chrome 78.0.3904.97, didn't try on other browsers or other Chrome versions.

**Additional context**
- Gutenberg version 6.9.

**Comment by mmtr** [comment]
I can still reproduce this (i.e. when using a 7% focal point):

![Dec-16-2019 15-58-28](https://user-images.githubusercontent.com/1233880/70917155-1bc11300-201d-11ea-8319-9d3a3c06a7b5.gif)

I guess we'd need to round the focal point as well when saving the cover block: 

https://github.com/WordPress/gutenberg/blob/42fdd1e1eb9a883891ebf0349dd6e6b6a5fb67b5/packages/block-library/src/cover/save.js#L48

cc @jorgefilipecosta
