### ISSUE TITLE
ColorPicker: Color format toggle looks like a dropdown

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#18678]
**Describe the bug**
The color format toggle (Hex, RGB, HSL) in the `ColorPicker` looks like a drodpown:

![68704932-c479df80-0552-11ea-90ea-ddf488f5e1d8](https://user-images.githubusercontent.com/3276087/69381734-09042a00-0c7b-11ea-991a-8ab900101028.gif)

**Expected behavior**
The element should look like  toggle instead. It was suggested on #18448 to [change the arrow for a different icon](https://github.com/WordPress/gutenberg/pull/18448#pullrequestreview-316051796), to[ use a a ButtonGroup instead ](https://github.com/WordPress/gutenberg/pull/18448#issuecomment-553488032) or to [convert it to an actual Dropdown](https://github.com/WordPress/gutenberg/pull/18448#issuecomment-556606821):

<img width="127" alt="68784658-e5057080-060a-11ea-9494-f41b8faac347" src="https://user-images.githubusercontent.com/3276087/69381900-6bf5c100-0c7b-11ea-96b1-8b0a501db110.png">
<img width="231" alt="69289643-ce3ebb00-0bc2-11ea-856b-081b2d83480c" src="https://user-images.githubusercontent.com/3276087/69381903-6dbf8480-0c7b-11ea-9efa-5a190591eb34.png">
<img width="273" alt="69289815-63da4a80-0bc3-11ea-9424-a993f8f6744a" src="https://user-images.githubusercontent.com/3276087/69381904-6ef0b180-0c7b-11ea-85ec-1a29c751ea38.png">

Let's explore these ideas and see which one feels the best.

**Comment by enriquesanchez** [comment]
Here's a proposal for the color format selector using the dropdown pattern already found elsewhere. I felt that the button group takes too much space, and it's already a bit tight due to the color input fields.

<img width="598" alt="Frame 2" src="https://user-images.githubusercontent.com/3276087/70100476-75761600-15f7-11ea-8dd2-30d663647599.png">

Using the dropdown approach allows us to keep the UI clean and provides the necessary affordance.

Would love to hear what you think @richtabor @jasmussen @mapk.

**Comment by jasmussen** [comment]
As a mockup, this looks good to me! I'm assuming it will use the standard popover component? Alternatively, maybe it could just be a stock dropdown?

<img width="86" alt="Screenshot 2019-12-04 at 09 30 06" src="https://user-images.githubusercontent.com/1204802/70126173-c1b56a80-1678-11ea-8f40-c84b5f1505ea.png">

**Comment by richtabor** [comment]
This is great @enriquesanchez! Perhaps the stock dropdown would work best as @jasmussen suggested. That's what we've migrated other similar dropdown utilizing components to (such as the FontSizePicker). 

Just to confirm, what would the label update to, if `RGB` and `HSL` we're selected? Currently its "Color value in hexadecimal."

**Comment by enriquesanchez** [comment]
Thanks @richtabor and @jasmussen!

I agree that the stock dropdown should be used here.

>Just to confirm, what would the label update to, if RGB and HSL we're selected? 

Thanks for raising this. I think it should just say "Color value", because we now have the color format specified on the dropdown. What do you think?

**Comment by richtabor** [comment]
> Thanks for raising this. I think it should just say "Color value", because we now have the color format specified on the dropdown. What do you think?

Good idea; I think that'll work.

**Comment by enriquesanchez** [comment]
Here's an update that takes into account all 3 formats and also adds a label to the format select for accessibility:

<img width="1324" alt="Screen Shot 2019-12-05 at 14 10 18" src="https://user-images.githubusercontent.com/3276087/70270011-133d2280-1769-11ea-8dcb-00c9b68a2170.png">

**Comment by richtabor** [comment]
What about using `Hexadecimal` instead of `Value` for the Hex view?

**Comment by richtabor** [comment]
I wonder if `Color value` would be fine, instead of changing it per format.

**Comment by enriquesanchez** [comment]
>I wonder if Color value would be fine, instead of changing it per format.

@richtabor I think we'd still want to keep `R` `G` `B` and `H` `S` `L` above the corresponding fields when those formats are selected.

**Comment by mapk** [comment]
I like this direction, @enriquesanchez! Because we are using `hsl` and `rgb` in the label, maybe we can do what @richtabor mentioned about using `hexidecimal` there for the hex? Or is it important to indicate somewhere here that it's a "value" of sorts?

**Comment by enriquesanchez** [comment]
@mapk @richtabor Agreed, I think `Hexadecimal` works great here. This way all three toggle states will show the corresponding label for the color format:

<img width="1223" alt="Screen Shot 2019-12-17 at 14 07 40" src="https://user-images.githubusercontent.com/3276087/71030227-ab76c800-20d6-11ea-8591-f4a5d09fc45f.png">

**Comment by shaunandrews** [comment]
Was just thinking about this yesterday and spent some time on a few variations. Here's one of my fav's:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/191598/72450593-a3b74b80-3788-11ea-8f7e-035d97552b1e.png">
 
I also explored having the hex/rgb/hsl input _outside_ of the color picker:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/191598/72450639-b9c50c00-3788-11ea-88e0-804b21c9fe66.png">

**Comment by mapk** [comment]
@shaunandrews I really like your mockups with the hex _outside_ the color picker for two reasons:

1. It's much quick to identify the color value and verify it's what I wanted.
2. I don't have to open anything to edit it.

Thanks for these explorations!

**Comment by enriquesanchez** [comment]
> 1. It's much quick to identify the color value and verify it's what I wanted.
> 2. I don't have to open anything to edit it.

I agree with @mapk on these!

One thing I'm not sure about is how to have this coexist with the current pattern of having the theme palette visible. From your mockups @shaunandrews, it looks like the color palette will be visible only when the picker is invoked, right?

**Comment by enriquesanchez** [comment]
Here's another version riffing off what @shaunandrews shared above:

<img width="767" alt="Screen Shot 2020-02-19 at 19 36 35" src="https://user-images.githubusercontent.com/3276087/74892473-54e46f00-534f-11ea-8d75-fe69ddbb4950.png">

I still think that the color palette should be just one-click away, instead of hidden inside the color picker. I expect that to be useful for the majority of users, who might not know what RGB, HEX, etc.

I got rid of the label on each field (R, G, B, etc.) that I had on https://github.com/WordPress/gutenberg/issues/18678#issuecomment-566728410 because this is not a common pattern and it's probably not really necessary here. 

Also in this version, I like how the selected color is bigger and clearer

@richtabor @mapk @shaunandrews what do you think?

**Comment by enriquesanchez** [comment]
Closing this in favor of #19785, which is exploring similar iterations to the color picker.

Thanks @richtabor @mapk @shaunandrews for all the feedback and help. Let's continue moving this forward on that other issue.
