### ISSUE TITLE
Compose: withContext HOC

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#18679]
**Is your feature request related to a problem? Please describe.**

While working on creating blocks with many layers and props, I wanted to use context to help reduce "prop drilling" with my components.

I noticed that hooks weren't working for nested components within the `edit.js` file of my block. Instead of `useState`, I used the [`withState`](https://github.com/WordPress/gutenberg/blob/master/packages/compose/src/higher-order/with-state/index.js) HOC from the `@wordpress/compose` library. I wanted to do the same for context, but I noticed it wasn't available.

---

Sidenote: I've followed advice from respected React folks like Michael Jackson and Kent C Dodds on the Component composition:
https://www.youtube.com/watch?v=3XaXKiXtNjw

Still there were a couple of props that I felt could have benefitted from Context (which they say isn't the first choice, but still okay)

---

**Describe the solution you'd like**
I'm not sure of the state of the `@wordpress/compose` library (no pun intended). It looks like these HOCs were needed before React hooks were a thing. I know we're starting to use hooks more within this library, which is great. However, it looks like there are certain areas where hooks don't work yet.

With that said, do folks think a `useContext` HOC as part of `@wordpress/components` would be a good idea?

In terms of how it works, it would be something like...

```jsx
import { createContext } from '@wordpress/element';
import { useContext } from '@wordpress/compose';

const MyContext = createContext({})

const Thing = ({ useContext }) => {
    // Do things with Context
    const context = useContext()
    return <div>...</div>
}

const ConnectedThing = useContext(MyContext)(Thing);

const App = () => {
    const contextProps = {
        hello: 'there'
    }

    return (
        <MyContext.Provider value={ contextProps }>
            <ConnectedThing />
        </MyContext.Provider>
    )
}
```

Granted, you could achieve the same thing use [Context.Consumer](https://reactjs.org/docs/context.html#contextconsumer). This makes it a little nicer.

Thank you!

**Comment by youknowriad** [comment]
> const ConnectedThing = useContext(MyContext)(Thing);

I assume this was meant to be `withContext(MyContext)(Thing)`?

 // Do things with Context
>    const context = useContext()

How is  this different from `useContext( MyContext )`

**Comment by ItsJonQ** [comment]
@youknowriad I think there's something not right up with my local dev instance. There's a (new) block that I'm working on that errors when I try to use the `useContext` hook:

<img width="880" alt="Screen Shot 2019-11-22 at 9 20 39 AM" src="https://user-images.githubusercontent.com/2322354/69433910-8aef6400-0d0a-11ea-954d-ee89e569a21b.png">

Or any hook (like `useState`).

Let's pretend the code lives in a file named `a.js`. Using hooks in that code, breaks things.
If I copy and paste that exact code (with hooks) into another file, `b.js`, it works.

I think because of this weirdness... I had thought that hooks didn't work in certain scenarios?

This may be an isolated case. I can close this issue :)
Thank you for taking a look at it!

**Comment by ItsJonQ** [comment]
Update. I think it must have been a caching thing. I cleared it out, and fired up my local dev, and it seems to be behaving now. Very strange! Apologies for the false alarm 🙏
