### ISSUE TITLE
Introduce a convention for naming and structuring CSS-in-JS files

### ISSUE THREAD

**Issue by jameslnewell** [WordPress/gutenberg#18677]
There have been a few discussions around the naming and structuring of CSS-in-JS files since [the introduction of CSS-in-JS](https://github.com/WordPress/gutenberg/pull/17963).

To avoid it coming up on every PR, it would be good to have a clear but concise guideline that covers all use cases.

Related discussions:
- https://github.com/WordPress/gutenberg/pull/18652#issuecomment-557125704
- https://github.com/WordPress/gutenberg/pull/18495#discussion_r347239461

**Comment by paaljoachim** [comment]
Hey James @jameslnewell 

Thank you for creating this issue!
A long time has passed. I see that one PR has been merged and the other closed.
Is this issue still valid?

**Comment by ryanwelcher** [comment]
Closing due to in-action. Feel free to re-open if needed!
