### ISSUE TITLE
Write unit tests for new `useColors` hook.

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#18672]
https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/block-editor/src/components/colors/use-colors.js#L1-L302

**Comment by gziolo** [comment]
@youknowriad, do we still use `useColors` in the codebase?  My understanding was that we are trying the approach with WordPress hooks like in #21021.

**Comment by youknowriad** [comment]
We might still be using it but Ideally, we should sunset it yes.

**Comment by epiqueras** [comment]
Haha, I always thought `supports` was a better place for this. I'll close this then.
