### ISSUE TITLE
Aligned images unable to be moved

### ISSUE THREAD

**Issue by JeremyJRoberts** [WordPress/gutenberg#1868]
## Issue Overview

A right or left aligned image loses its ability to be moved with the arrow on the left hand side.
<img width="960" alt="unaligned" src="https://user-images.githubusercontent.com/22798784/28120365-d4b1975c-66e5-11e7-94ed-3b56a0ba1ef3.png">
<img width="960" alt="aligned" src="https://user-images.githubusercontent.com/22798784/28120447-15256cb4-66e6-11e7-9868-ab39fb0e95e1.png">

## Steps to Reproduce (for bugs)

1. Create a New post
2. Add a text block
3. Add an image
4. Align it left or right

## Expected Behavior

Ability to move an aligned image or move a text box at the bottom down to move the image up
## Current Behavior

An aligned image added below text can only be added to the paragraph above/below it and not be moved up your post independently.

## Todos
- [ ] Tests

**Comment by karmatosed** [comment]
I am unable to recreate this in the latest version of Gutenberg. If you can still, please reopen.
