### ISSUE TITLE
Block Author Focused Documentation in Storybook

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#18680]
Currently, prospective block authors don't have a canonical, focused source of documentation for them to get started building custom blocks.

The [Block Editor Handbook](https://developer.wordpress.org/block-editor/) is very hard to navigate and contains information on all aspects of Gutenberg, most of which are irrelevant to block authoring.

I think that the barrier to entry to authoring blocks is way lower than our documentation makes it out to be and that having focused documentation for this would also serve as an onramp for potential future Gutenberg contributors.

Our new [Storybook MDX powered docs pages](https://wordpress.github.io/gutenberg/?path=/docs/docs-introduction--page) would make a great home for this new documentation.

I suggest we restructure the storybook into the following sections:

- Playground
- Docs
  - Getting Started (Setting up an environment and all that.)
- Recipes
  - Basic Block Plugin
  - Block Style Variations
- Advanced Guides
  - Deprecating Block Versions
- Components (Include "Other")
- Blocks API Reference
- FAQ

We should also [theme our storybook](https://storybook.js.org/docs/configurations/theming/) to better fit the WordPress brand.

**Comment by epiqueras** [comment]
cc @ItsJonQ @aduth

**Comment by youknowriad** [comment]
I wouldn't suggest starting to document a lot of things in Storybook yet unless we figure out how to put things in wp.org first. We can't start by reorganizing the handbook if needed.

**Comment by epiqueras** [comment]
Storybook outputs static markup so that shouldn't be hard.

**Comment by mkaz** [comment]
I agree the Block Editor Handbook could use some improvements. It contains a mix of interests and is not necessarily clear about the intent of all its pieces of documentation. I found this article about the [Four Types of Documentation](https://www.divio.com/blog/documentation/) useful when thinking about our documentation. The four types being Tutorials, HowTos, Explanations, and Reference. 

The other aspect mixed into our Gutenberg docs is the audience, we have developers, designers, contributors, and users. These audiences are mixed together both as developers of Blocks and contributors to the Gutenberg project. Also, I'm not sure it makes sense to still make a split between developers and designers.

I don't have a structured proposal yet on what our docs should look like, but agree with @youknowriad that we should probably iterate on current docs reorganization. I would like to think about a structure that takes into account audience first, and then the type of documentation needed for that audience.

I see StoryBook being a great resource that fills the API Reference probably for multiple audiences.

Thoughts?

**Comment by nosolosw** [comment]
I also agree we should focus on iterating on contents within the handbook (reorganizing, updating, creating as necessary) and fill gaps as necessary.

One gap that a Storybook-like tool can fill is the showing components live. I'd love to have that. What would we need to do to take Storybook (or its components, or something similar) and embed it into the handbook?

**Comment by epiqueras** [comment]
It's a static app, we could even just iframe it.
