### ISSUE TITLE
Users may not understand the concept of a block having focus or not having focus

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#18688]
Passing feedback shared on: https://wordpress.org/support/topic/need-better-developers/#post-12163366

I think one of the biggest issues I see that impacts a lot of how the block editor works is that users don’t understand the concept of a block having focus or not having focus. And it has always bothered me that when a block does have focus and the block editing buttons appear, that they overlap the bottom of the block above. That causes confusion because it’s just not clean. And I suggest that the little plus icon at the top of each block that only appears when you hover over that little area where it resides, be always visible.
I know that one of the goals is probably to keep the interface as minimalistic as possible, and I get that, but I suspect that there are a ton of users, maybe even most users, that would rather have all the buttons and controls and everything right out there to be seen so we don’t have to search around for everything. Maybe there needs to be two modes of editing, one for minimalist and one for folks like me and my many customers using WordPress.

**Comment by youknowriad** [comment]
Should this be combined with #18667 

While the proposed solutions are different, I think it addresses the same issues.

**Comment by youknowriad** [comment]
I think you should also suggest to this person to use the "Top Toolbar" mode as it addresses this issue as well.

**Comment by jorgefilipecosta** [comment]
Thank you @youknowriad, I tied to find the related issue searching by focus but yes I agree the issues are related. I will suggest the Top Toolbar mode.
