### ISSUE TITLE
Block text/background color doesn't work. Please help.

### ISSUE THREAD

**Issue by jacopotj** [WordPress/gutenberg#18694]
**Describe the bug**

When editing the color of background / text it doesn't work. I asked to theme support and after a couple days the edits i did were fixed, but when making new edits (with new colors) it doesn't work again or it changes to other colors making the text invisible. With some colors it works, with others it doesnt, with other it changes to another color like white.
*THIS IS NOT A CACHE ISSUE!
This thing is driving me mad, the website is new too.

**To reproduce**
1. Go to ' https://www.calcioshow.tv/cristiano-ronaldo-record-champions-league-2017-18/ '
2. Under the video, there's text (you can see if you highlights, but it didn't follow the color editing. See this screenshot inside gutenberg https://ibb.co/YZ7062K

**Expected behavior**
Obviously color should change to requested colors
**Screenshots**

**Desktop (please complete the following information):**
 Tested on chrome, pc, android, iphone. Not a browser nor a device problem - or cache

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by jorgefilipecosta** [comment]
Hi @jacopotj,
Thank you for reporting this issue.
It seems the colors are being applied using classes: has-col-000000-color has-col-ebebeb-background-color.
These classes are not being loaded on the frontend. It seems it is a theme issue and the theme is not adding these classes to the stylesheet. The class format itself is strange as the class format refers to a color value.
Could you please provide us a link to the theme you are using, if it is freely available?
Could you please provide us the WordPress version you are using and if you have Gutenberg plugin installed could you provide us the version?

Thank you in advance!

**Comment by jacopotj** [comment]
Hi, thanks a lot for this quick and accurate support. Wish the theme support - which i pay too - was as good ;)

Asnwering your questions, the theme is the popular enfold theme.
https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990
Guteneberg is part of the theme, also i have the latest version.

One thing, i just found a turnaround to display the colors the way I want.
Instead than picking the colors that the theme gives me, i choose a custom one myself, and the color changes correctly.
If i choose one from the themes options, it doesnt change or sometimes it does the opposite, like black becoming white.

Do you think i should just ignore this bug and set custom color codes to get the work done, or it should still be fixed?

THhanks again, screenshot shows what i mean by "using theme color options".
![Cattura](https://user-images.githubusercontent.com/56704907/69464791-9d57b500-0d7f-11ea-862c-3779d78d22d4.PNG)

**Comment by youknowriad** [comment]
> Do you think i should just ignore this bug and set custom color codes to get the work done, or it should still be fixed?

ideally, the theme should fix it because the custom colors are inline styles and classnames (the theme . palette) are preferable.
