### ISSUE TITLE
Gutenberg not compatible with WordPress 5.2.4 

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#18697]
I ask the question because we need Gutenberg installed to be able to make and improve our developments.
Even if I saw on WordPress.org that [Gutenberg 6.9.0 is tested up to WordPress 5.2.4](https://wordpress.org/plugins/gutenberg/), I have strange behaviours

**WordPress 5.2.4, 
Gutenberg 6.9.0 downloaded, installed and activated form WordPress backend**

No editor is displayed

![image](https://user-images.githubusercontent.com/1003778/69439166-aed09b00-0d46-11ea-925c-b67c35b82d84.png)

**WordPress 5.2.4
Gutenberg 6.9.0 build by my own by cloning from github**

No editor is displayed - a beautiful blank page :-) and not with the same error.
It seems that wp.hooks.addAction is unknown in inline javascript
See [script-loader.php](https://github.com/WordPress/WordPress/blob/5.2-branch/wp-includes/script-loader.php#L536-L560)

![image](https://user-images.githubusercontent.com/1003778/69441588-50f28200-0d4b-11ea-8e70-4fb56937cc83.png)

With WP_DEBUG and WP_DEBUG_LOG = true, I have nothing in the debug.log file.

**Note 1:** With WordPress 5.3.1, the two cases above works correctly
**Note 2:** With WordPress 5.2.4, if I downgrade to Gutenberg 6.8.0 by building by my own, everything is ok too. Exactly the same build of Gutenberg 6.8.0 installed on WordPress 5.3.1 also works fine.

**Comment by youknowriad** [comment]
The requirement right now is WP 5.2 but we'll be moving soon to WP 5.3.

You have an error on your plugin code. My guess is that you haave a missing script dependency (wp-hooks probably)

**Comment by manooweb** [comment]
It works perfectly right on WordPress 5.3.1 without doing anything else and with or without gutenberg plugin, strange, isn't it ?

**Comment by youknowriad** [comment]
No, it's not strange when you don't define your dependencies properly, you rely on the random loading order for that version, that loading order can change as WordPress scripts evolve.

The only way to ensure something is loaded when you use it is to add it as a dependency.

**Comment by manooweb** [comment]
Sure! but this wp.hooks.addAction is a WordPress code loaded by script-loaded.php in WordPress core.
It's not our plugin code and until now we don't use wp.hooks package. So I don't understand why I need a dependency on something I don't need.

**Comment by youknowriad** [comment]
Ohhh makes sense now.

Did you try disabling other plugins? What plugins do you have, just Gutenberg?

**Comment by manooweb** [comment]
Yes! all plugins are dectivated except Gutenberg 6.9.0 built by myself
![image](https://user-images.githubusercontent.com/1003778/69448547-0d9f1000-0d59-11ea-9bac-8662d48ed913.png)

**Comment by youknowriad** [comment]
Thanks @manooweb and sorry for the back and forth.

There might be something breaking then. I'll reopen so we can test this further. 
Anyway, Gutenberg is a development plugin and we're considering making 5.3 the minimum version very soon anyway.

**Comment by manooweb** [comment]
Ok. Thanks. I understand but some of our developments need Gutenberg plugin for better debugging but we have customers not yet in WordPress 5.3 :-) and we need to be able to test this lower WordPress version too.

**Comment by youknowriad** [comment]
It's fine for developpement, but for your plugins, I don't think you should be recommending the Gutenberg plugin.

**Comment by manooweb** [comment]
We don't recommend that. It's easier for us for debugging and be close as possible from our customers' environment

**Comment by manooweb** [comment]
I updated to Gutenberg 7.2.0 then 7.3.0 still with WordPress 5.2.x and I haven't these errors anymore.

So we can close this issue.

**Comment by jorgefilipecosta** [comment]
Thank you for updating us @manooweb.

**Comment by manooweb** [comment]
Thanks @jorgefilipecosta.
I completed a bit my comment above.
