### ISSUE TITLE
Apply Pullquote border and main color using class names instead of inline style

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#18691]
**Is your feature request related to a problem? Please describe.**
The inline styling approach of the Pullquote block is really frustrating. I spent hours trying to do a simple task: apply a custom style to the Pullquote block. Assuming that border and background colors should be applied to a specific element in a specific way is limiting the theme developers a lot.

I had to filter the front block output using `render_block` filter and alter the block's editor version using `BlockListBlock` filter jus to add a class name to help me do the job.

Just imagine that - for some reason - I need to apply the border color to the `blockquote` element or pseudo-element instead of the parent `figure` element, or maybe I want to make the border or background has a gradient of the same color (fade to transparent for example).

One of the blocks that used to be conflicting with the theme developer decisions was the button block with rounded/square/..etc choices, but this was fixed in the latest Wordpress 5.3 update leaving only the fill/outline choices. I hoped if you fixed the Pullquote inline styling as well to leave more freedom to the theme developer on how the blocks should blend with the theme style.

**Describe the solution you'd like**
Instead of applying inline styling, just apply the class `has-<color>-border-color` and `has-<color>-main-color` to the block parent and let the theme developer decide how the block should look like.

**Comment by jorgefilipecosta** [comment]
Hi @premitheme,
Thank you for raising this issue 👍
We are using inline styles for the border color because we never documented that when using color classes themes should create classes for borders, only color and background-color properties were expected.
There is a tradeoff, using classes for borders would require additional effort from theme authors as they would need to create border classes. As only one block was using border colors in a specific style we opted to use inline styles to avoid requiring additional effort from theme authors.
We may in the future look again into this decision, it may even make sense to rethink the block itself and avoid the need for border colors so we don't use inline styles.
Any thoughts on this @youknowriad, @epiqueras?

**Comment by epiqueras** [comment]
Can we use classes if the theme provides them, and fall back to inline styles if it doesn't?

**Comment by premitheme** [comment]
@jorgefilipecosta thanks for the reply. WordPress was always aiming to make a space of freedom for theme authors to make their design/style decisions, this is the core idea of WordPress themes. And as this particular option (colors) belongs to this field, I was expecting to have the same ability. But it turns out that I need to do a lot of additional effort to achieve this small modification; adding a class name.

IMO, theme authors already do a lot of effort to make sure the block editor styles and look are matching the front-end output, it will not matter if they added extra few lines of CSS. And altering the documents to reflect this small change will not harm or conflict anyone.

> Can we use classes if the theme provides them, and fall back to inline styles if it doesn't?

Maybe provide both classes and inline styles, by this, if the theme author is happy with the inline style, then no harm, and if he wants to take the further step and use the classes, he can override the inline styles with `!important`.

My respect to all your efforts guys.

Regards,
Ahmed

**Comment by jorgefilipecosta** [comment]
> Can we use classes if the theme provides them, and fall back to inline styles if it doesn't?

We never went this path, but I think the editor can check if the border classes exist on the loaded CSS. So provided the themes enqueued the colro styles on the editor and not just on the frontend it may work well.

1.

**Comment by epiqueras** [comment]
Maybe this is something for `add_theme_support`?

**Comment by jorgefilipecosta** [comment]
> Maybe this is something for add_theme_support?

You mean creating a something like add_theme_support( 'border-color-classes' ), so themes can specify if they are implementing border-color classes?

**Comment by epiqueras** [comment]
Yes.

**Comment by jordesign** [comment]
Looping back to this issue - just wanted to see if is still relevant, or if subsequent improvements have resolved it for you @premitheme @epiqueras  ?

**Comment by jordesign** [comment]
With no further activity on here in 3+ years I'm going to close the issue.

If it is still a concern with the current version of WP/GB a new issue can be opened with updated screenshots and testing details.
