### ISSUE TITLE
Page edit in Block Editor slows down massively when new line (enter key) is not preceded with whitespace (spacebar).

### ISSUE THREAD

**Issue by kchodera** [WordPress/gutenberg#18693]
**Bug description**
When new line (enter/return key) is placed directly inside text/code and is not preceded with whitespace (spacebar), Block Editor slows down massively (up to a minute to load simple text page and each edit attempt is delayed making editing impossible). Placing a whitespace (spacebar) right before new line solves the issue.

**To reproduce**
1. Open new page with Block Editor enabled
2. Add text `JohnDoe`
3. Add new line (enter/return key) between two words : `John
Doe`
4. Save page and reload/reopen page edit.

**Expected behavior**
This is potentially common scenario and such whitespaces should not affect the edit page loading speed nor its usability.

**Desktop :**
 - OS: iOS 10.15.1
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**
- WordPress 5.3

**Comment by talldan** [comment]
@kchodera Is this something you're still experiencing? It's be great if you were able to test with the latest version of the plugin (7.3) if you have time.

The latest version has quite a few performance improvements, time taken for handling a keystroke was almost halved:
https://make.wordpress.org/core/2020/01/22/whats-new-in-gutenberg-22-january/

**Comment by torounit** [comment]
@kchodera We have not been able to reproduce this problem.

I believe the problem has already been solved.

If you are still having problems, please leave a note.
