### ISSUE TITLE
Changing number of columns in columns block doesn't change class

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18705]
**Describe the bug**
I had a Column Block that had three columns. It had the class `has-3-columns`. When I change the number of columns, this additional css class doesn't change in the editor, or when the block is rendered on the front-end. As well as just being wrong, this is going to lead to significant display issues if a theme has styled these various `has-x-columns` classes.

Vid: https://share.getcloudapp.com/04ukpKo8

<img width="1061" alt="screenshot_39" src="https://user-images.githubusercontent.com/2078245/69474385-ba8a9300-0e14-11ea-8852-c211bf77801b.png">

<img width="1440" alt="screenshot_41" src="https://user-images.githubusercontent.com/2078245/69474386-bceced00-0e14-11ea-8792-d2af9e4d6827.png">

When I add a new Columns Block into my page, it doesn't get these `has-x-columns` classes. If this class name is a leftover from as previous incarnation of the Columns Block, then it means that Core hasn't updated the Columns Blocks properly as this class should've been removed when the block was updated. Not doing so is likely to cause significant rendering problems on the front-end. I shouldn't have to re-edit every single page within a site that has a Columns Block, just to manually remove these classes if they're no longer needed/used.

**To reproduce**
1. Find a Columns Block that has an additional class specified
2. Change the number of columns
3. View the class name not changing

**Expected behavior**
If the number of columns change in the Columns Block, so should the class. If the Class name is  no longer used by the Columns Block, then it should've been automatically removed, even without having to edit the page.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox 70.0.1
 - Version: WP 5.3

**Comment by carasmo** [comment]
Yes, recently the column classes are gone and so custom breakpoints and adjustments cannot be made.

**Comment by carasmo** [comment]
The css for this is also not in the block css, so there is no string "has-3-columns" which was there last week.

**Comment by carasmo** [comment]
This is the way it goes, see the duplicate https://github.com/WordPress/gutenberg/issues/17765.

**Comment by gziolo** [comment]
> This is the way it goes, see the duplicate #17765.

@youknowriad, I see you closed the issue mentioned. Should this one get closed as well? It seems like the old class name could get removed when updating the number of columns though.

**Comment by maddisondesigns** [comment]
If those class names are no longer used, then they should be automatically removed from **every** instance of the columns block. A user shouldn't be expected to remove them manually by updating every single page in their site.

**Comment by youknowriad** [comment]
The fact that the block supports custom classNames, the system can't make a difference between custom classNames and generated ones in previous versions.

**Comment by maddisondesigns** [comment]
Soooo if core introduces a block that uses a class, which would then most likely get used by theme developers, and then a few versions later you decide that class is no longer needed, you're saying that users have no option but to manually edit every single page where that block is. What a ridiculous limitation.

**Comment by youknowriad** [comment]
If you have ideas about how to solve it, please do push a PR. Otherwise, I'd suggest that you soften the language a little bit. Thanks
