### ISSUE TITLE
Can't cut multiple blocks with `command-x`

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#18700]
1. Select multiple paragraphs
1. Right click and choose `Cut`, you'll see the blocks removed from the editor, and they'll be added to the OS clipboard
1. `command-z` to undo
1. Select the paragraphs again
1. `command-x` should cut them, but instead nothing happens

**Comment by iandunn** [comment]
🤔 , now when I try to right-click to `cut`, the selection is wiped out and focus is reset on the individual block that I right clicked on. That also seems wrong, but I'm not sure why it worked the first time I tried.

It seems like `command-x` works in Firefox, but not Chrome.

**Comment by ellatrix** [comment]
I tried Cmd+C on multiple selected block in Chrome on Mac and it works fine. The blocks disappear and are in my clipboard.

**Comment by iandunn** [comment]
Yeah, it's working for me now on cc44f8b3aad83f9b5c8564739d95d734d9abb440. Thanks :)
