### ISSUE TITLE
Unable to save attributes being filtered onto 3rd party blocks

### ISSUE THREAD

**Issue by jayhill90** [WordPress/gutenberg#18709]
**Describe the bug**
When using block filters to add attributes to non-core blocks, the attributes don't get saved into post_content in the database. It works fine when adding classNames though.

**To reproduce**
1. Install a 3rd party block such as Atomic Blocks or CoBlocks or any other block plugin.
2. Create a plugin to add the below code as a filter. When you toggle the Visible on Mobile button for either the core/paragraph or core/heading block and save the page when you query post_content for this post, the attributes are saved in those blocks.

```
/**
 * External Dependencies
 */
import classnames from 'classnames';

/**
 * WordPress Dependencies
 */
const { __ } = wp.i18n;
const { addFilter } = wp.hooks;
const { Fragment }	= wp.element;
const { InspectorAdvancedControls }	= wp.editor;
const { createHigherOrderComponent } = wp.compose;
const { ToggleControl } = wp.components;

//restrict to specific block names
const allowedBlocks = [ 'core/paragraph', 'core/heading' ];

/**
 * Add custom attribute for mobile visibility.
 *
 * @param {Object} settings Settings for the block.
 *
 * @return {Object} settings Modified settings.
 */
function addAttributes( settings ) {
	
	//check if object exists for old Gutenberg version compatibility
	//add allowedBlocks restriction
	if( typeof settings.attributes !== 'undefined' && allowedBlocks.includes( settings.name ) ){
	
		settings.attributes = Object.assign( settings.attributes, {
			visibleOnMobile:{ 
				type: 'boolean',
				default: true,
			}
		});
    
	}

	return settings;
}

/**
 * Add mobile visibility controls on Advanced Block Panel.
 *
 * @param {function} BlockEdit Block edit component.
 *
 * @return {function} BlockEdit Modified block edit component.
 */
const withAdvancedControls = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {

		const {
			name,
			attributes,
			setAttributes,
			isSelected,
		} = props;

		const {
			visibleOnMobile,
		} = attributes;
		
		
		return (
			<Fragment>
				<BlockEdit {...props} />
				//add allowedBlocks restriction
				{ isSelected && allowedBlocks.includes( name ) &&
					<InspectorAdvancedControls>
						<ToggleControl
							label={ __( 'Mobile Devices Visibity' ) }
							checked={ !! visibleOnMobile }
							onChange={ () => setAttributes( {  visibleOnMobile: ! visibleOnMobile } ) }
							help={ !! visibleOnMobile ? __( 'Showing on mobile devices.' ) : __( 'Hidden on mobile devices.' ) }
						/>
					</InspectorAdvancedControls>
				}

			</Fragment>
		);
	};
}, 'withAdvancedControls');

/**
 * Add custom element class in save element.
 *
 * @param {Object} extraProps     Block element.
 * @param {Object} blockType      Blocks object.
 * @param {Object} attributes     Blocks attributes.
 *
 * @return {Object} extraProps Modified block element.
 */
function applyExtraClass( extraProps, blockType, attributes ) {

	const { visibleOnMobile } = attributes;
	
	//check if attribute exists for old Gutenberg version compatibility
	//add class only when visibleOnMobile = false
	//add allowedBlocks restriction
	if ( typeof visibleOnMobile !== 'undefined' && !visibleOnMobile && allowedBlocks.includes( blockType.name ) ) {
		extraProps.className = classnames( extraProps.className, 'mobile-hidden' );
	}

	return extraProps;
}

//add filters

addFilter(
	'blocks.registerBlockType',
	'editorskit/custom-attributes',
	addAttributes
);

addFilter(
	'editor.BlockEdit',
	'editorskit/custom-advanced-control',
	withAdvancedControls
);

addFilter(
	'blocks.getSaveContent.extraProps',
	'editorskit/applyExtraClass',
	applyExtraClass
);
```

3. Add one of the 3rd party blocks to the allowedBlocks const in the above code and try toggling the Visible on Mobile for that 3rd party block. Save the page and the attribute won't be saved into the database bu the className will. 

**Expected behavior**
As a user I expect to be able to add custom attributes to 3rd party blocks the same way I can with core blocks.

I tested this on a few different blocks with several different block filters and attributes only saved into post_content on core blocks. 

**Desktop (please complete the following information):**
 - OS: OS X 
 - Browser Chrome or Firefox
 - Version Latest

**Additional context**
- Gutenberg 6.7-6.9

**Comment by thrijith** [comment]
Hi @jayhill90, did you manage to get a fix for this?

**Comment by jayhill90** [comment]
I have not it's still a bug :)

**Comment by aduth** [comment]
On first glance, this could be an issue where your script is enqueued _after_ the other third-party plugin, so by the time your filter is added, the other block had already been registered.

I should also point out that this sort of attributes extension can become potentially troublesome if the user chooses to deactivate your plugin, as it may cause extended blocks to begin appearing as "invalid", since your code will no longer present to add the required filtering.

**Comment by thrijith** [comment]
Hi @aduth,

Thanks for taking a look, here is the current code I am using to add custom setting ( adding a new attribute ) to the block, https://gist.github.com/thrijith/8cff51c88151a08849faafccb7192d70, I did some test with deactivating the plugin that adds new attribute which seems to be working as expected.

Hope it helps, Thanks.

**Comment by thrijith** [comment]
Hey @jayhill90 

Can you verify if lowering the priority works for you, also make sure that your script is loading similar to third party script.

Even after lowering the priority it didn't work for me, it happened because I was loading my script in footer while the the third party script was loaded in header.

Hope it helps.

**Comment by jayhill90** [comment]
> Hey @jayhill90
> 
> Can you verify if lowering the priority works for you, also make sure that your script is loading similar to third party script.
> 
> Even after lowering the priority it didn't work for me, it happened because I was loading my script in footer while the the third party script was loaded in header.
> 
> Hope it helps.

So you're saying to enqueue my scripts with a lower priority number or higher number?

**Comment by thrijith** [comment]
> So you're saying to enqueue my scripts with a lower priority number or higher number?

Lower number.

**Comment by youknowriad** [comment]
Closing as it already had some proposals/answers
