### ISSUE TITLE
Wrong columns count on table block creation

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#18715]
**Describe the bug**
When I'm creating a table block and set the columns count to any number, the created table reduces this number by 1. Example: I set the columns to 4 > the created is 3. The rows count works fine.

**To reproduce**
1. Go to block editor.
2. Create a table block
3. Set any number of columns (i.e. 4 columns).
4. The resulted table has 1 column less (3 columns).

**Expected behavior**
The resulted tablet should have the same number of columns that are set on creation.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version 78.0.3904.108

**Additional context**
- WP 5.3

**Comment by talldan** [comment]
Hi @premitheme. I'm unable to reproduce this issue. Here's a gif showing my reproduction:
![table](https://user-images.githubusercontent.com/677833/70878478-9e85a600-1ffc-11ea-9bfb-e98def0b4d37.gif).

The project also has automated tests in place that would catch this bug if it were ever to occur:
https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/table.test.js#L34-L64

It may be that you have a plugin installed that's causing an issue.
