### ISSUE TITLE
Registering additional controls with 'editor.BlockEdit' hook causes duplicate image upload

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#18717]
**Describe the bug**
If you register additional controls to the Image Block with the `editor.BlockEdit` hook, an image uploaded via drag-n-drop (or the standard browser file upload UX) will be uploaded twice. My expectation is that the image would just be uploaded once.

**To reproduce**

1. Register a custom control to the `core/image` block with:

```js
const {
	PanelBody,
	TextControl,
} = wp.components;

const {
	createHigherOrderComponent,
} = wp.compose;

const {
	InspectorControls,
} = wp.editor;

const {
	Fragment,
} = wp.element;

const {
	__,
} = wp.i18n;

const {
	hooks,
	media,
} = wp;

const registerFields = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		if ( 'core/image' !== props.name ) {
			return (
				<BlockEdit { ...props } />
			);
		}

		const {
			attributes,
			setAttributes,
		} = props;

		// Accommodate both an image inserted from Media Library
		// and an image inserted from a URL.
		if ( ! attributes.id && ! attributes.url ) {
			return (
				<BlockEdit { ...props } />
			);
		}

		const {
			customText,
		} = attributes;

		return (
			<Fragment>
				<InspectorControls>
					<PanelBody title={ 'Custom Panel' }>
						<TextareaControl
							defaultValue={ customText }
							onChange={ ( value ) => setAttributes( { customText: value } ) }
							label={ __( 'Custom Text', 'dbx' ) }
							placeholder={ '' }
						/>
					</PanelBody>
				</InspectorControls>
				<BlockEdit { ...props } />
			</Fragment>
		);
	};
} );

hooks.addFilter( 'editor.BlockEdit', 'dbx/extend-image-block', registerFields );
```

2. Upload a image onto the Image Block via drag-n-drop or by selecting an image from your computer.

3. Observe that the image was POST'ed twice (and then appears twice in the Media Library):

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/36432/69502755-ba979b00-0ec7-11ea-8307-2aa9ba5f8aec.png">

**Additional debugging**

If I only return `<BlockEdit { ...props } />`, then one image is uploaded as expected:

```js
return (
	<Fragment>
		<BlockEdit { ...props } />
	</Fragment>
);
```

But, if I include any additional controls or panels, then the duplicate image is unexpectedly included:

```js
return (
	<Fragment>
		<InspectorControls>
			<PanelBody title={ 'Custom Text' }>
			</PanelBody>
		</InspectorControls>
		<BlockEdit { ...props } />
	</Fragment>
);
```

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Firefox
 - Version: 70.0.1
 - Gutenberg: 6.9.0

**Comment by bemyhre** [comment]
I cannot tie this to any specific code, but I am seeing a similar issue since 5.3. When I use the image loader via Gutenberg and add a new image, two are loaded into the media loader and it is showing the same duplicate POST calls in the network tab.

If I go to the media library and upload directly there rather than a post, it works fine.

**Comment by bemyhre** [comment]
curious... wouldn't this be considered a bug?

**Comment by danielbachhuber** [comment]
@gziolo Have any suggestions on how I might debug this?

**Comment by danielbachhuber** [comment]
Interestingly, if I drag an image to a drop zone in the editor (outside of the image block), the image is only uploaded one time as expected:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/36432/72071775-6ee75800-32a1-11ea-8242-23eb01b0fb77.png">

It's only when I drag and drop onto an image block or use the "Upload" UX inside the image block that there's a duplicate upload:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/36432/72071874-9fc78d00-32a1-11ea-89be-384aecfcb162.png">

**Comment by gziolo** [comment]
> @gziolo Have any suggestions on how I might debug this?

I asked in the #core-editor channel on WordPress Slack:
https://wordpress.slack.com/archives/C02QB2JS7/p1578577173180900

I don't really know how it work internally and what could cause the issue.

**Comment by danielbachhuber** [comment]
... and I've figured out the issue! The offending lines in my code snippet above are:

```js
// Accommodate both an image inserted from Media Library
// and an image inserted from a URL.
if ( ! attributes.id && ! attributes.url ) {
	return (
		<BlockEdit { ...props } />
	);
}
```

This code snippet only shows my fields if there's an image specified for the block. However, I think this causes the block to remount during the upload process, which must cause `mediaUpload` to be called again:

https://github.com/WordPress/gutenberg/blob/18393a357cdcbee79c215274cd55420e100e6b7e/packages/block-library/src/image/edit.js#L115-L139

If I remove the offending lines from my code snippet, only one image is uploaded as expected.

I'm not sure if there's a good way for the block editor code to guard against this, but I'm fine to simply show my fields all of the time.

**Comment by danielbachhuber** [comment]
> If I remove the offending lines from my code snippet, only one image is uploaded as expected.
> 
> I'm not sure if there's a good way for the block editor code to guard against this, but I'm fine to simply show my fields all of the time.

Actually, I've found a better solution. If I import `isBlobUrl`:

```js
const {
	isBlobURL
} = wp.blob;
```

Then I can avoid rendering my controls until _after_ the image has been uploaded:

```js
// Accommodate both an image inserted from Media Library
// and an image inserted from a URL.
if ( ! attributes.id && ( ! attributes.url || isBlobURL( attributes.url ) ) ) {
	return (
		<BlockEdit { ...props } />
	);
}
```

I think this is the _correct_ way my code should be implemented, so probably no changes are expected in the Image Block.

**Comment by youknowriad** [comment]
Closing as the solution above seems decent.
