### ISSUE TITLE
Remove "Custom" from font size dropdown when custom fonts are disabled

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#18716]
**Describe the bug**
While using `add_theme_support( 'disable-custom-font-sizes' )`, "Custom" option still show up in the font sizes drop down.

**To reproduce**
1. Add `add_theme_support( 'disable-custom-font-sizes' );` as documented.
2. Go to block editor.
3. Create a paragraph block.
4. Try to change the font size from the sidebar controls.
5. "Custom" option still show up in the font sizes drop down.

**Expected behavior**
"Custom" option should be removed when using `add_theme_support( 'disable-custom-font-sizes' )`.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version 78.0.3904.108

**Additional context**
- WP 5.3

**Comment by carasmo** [comment]
Yes, this started happening with the latest update to WordPress. Frustrating and confusing for people.
