### ISSUE TITLE
Social Links: Broken left and right alignments

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#18723]
**Describe the bug**
Setting a left or right alignment to the Social Links block makes it float out of the normal flow of the editor.

**To reproduce**
1. Insert in this order: Paragraph, Social Links, Paragraph.
2. Set the Social Links alignment to left or right.
3. Observe how Social Links is not in the expected position.

**Expected behavior**
I expected to see the Social Links border, and its intended location, even when aligning it to the left or right.

**Screenshots**

<img width="1127" alt="Screenshot 2019-11-25 at 16 31 50" src="https://user-images.githubusercontent.com/2070010/69559808-8a70fa80-0fa2-11ea-90c6-fdafd21126fe.png">
Note how it appears _after_ the "Start writing" message.

| No alignment | Right aligned |
| - | - |
| <img width="706" alt="Screenshot 2019-11-25 at 16 33 03" src="https://user-images.githubusercontent.com/2070010/69559888-b3918b00-0fa2-11ea-99c8-5d4d81bb86be.png"> | <img width="709" alt="Screenshot 2019-11-25 at 16 33 20" src="https://user-images.githubusercontent.com/2070010/69559894-b68c7b80-0fa2-11ea-9be1-6ec9abc614f1.png"> |

**Desktop:**
 - OS: macOS 10.15.1
 - Browser: Chrome
 - Version: 78

**Comment by gwwar** [comment]
cc @mkaz @youknowriad for triage

**Comment by youknowriad** [comment]
I'm not sure I see the bug here? This is just behaving like floats in general. Floats are broken by nature?

**Comment by Copons** [comment]
> I'm not sure I see the bug here? This is just behaving like floats in general. Floats are broken by nature?

Well, but is this the intended behaviour?
I mean, I've started with the Social Links block in the middle of two blocks, and when I've aligned it to the right it moved to the bottom of the container.
I personally expected to see it aligned to the right while maintaining the same vertical position... 😄

**Comment by youknowriad** [comment]
It is expected yes, I guess you're looking for a "clear float" option, which I believe has its own issue.

The question is do you expect that align left/right make the text wrap around the current block or not?

**Comment by youknowriad** [comment]
you can also see that the same happens for any block you left/right align, not just the social links block.

**Comment by Copons** [comment]
You're right @youknowriad.
For some reasons I was sure other blocks (like Image) kept the UI and behaved differently when left/right aligned, but it's not the case.

I'll close this one then, thanks for looking into it!
