### ISSUE TITLE
Layout: Incorrect positioning on small screens with sidebar open

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#18726]
**Describe the bug**
The new layout is incorrectly positioned in small screens with the sidebar open.

In the browser's dev tools I can see:
```
@media (max-width: 782px)
.auto-fold .wp-responsive-open .edit-post-editor-regions {
  left: 190px
}
```

If I toggle that off, the layout repositions almost correctly.

I've tried empirically, and to position the editor adjacent to the sidebar (which is indeed `190px` wide) we'd need `left: -18px`, which I'd say it's not ideal and the culprit is likely somewhere else.

**To reproduce**
1. Open the editor and resize the window to under `782px`.
2. Open the sidebar.
3. Observe that the editor layout is offset by ~200px away from the sidebar.

**Expected behavior**
The editor should have been directly adjacent to the sidebar.

**Screenshots**
![Screenshot 2019-11-25 at 17 07 41](https://user-images.githubusercontent.com/2070010/69564019-1fc3bd00-0faa-11ea-83cf-1d3fc16f289f.png)

**Desktop (please complete the following information):**
- OS: macOS 10.15.1
- Browser: Chrome
- Version: 78

**Comment by paaljoachim** [comment]
Hey @Copons Jacopo

I just checked and it looks like this has been fixed, so I will go ahead and close the issue. If I am mistaken then please reopen.
