### ISSUE TITLE
Add props for InnerBlocksTemplatePicker icon, label and instructions

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#18738]
**Is your feature request related to a problem? Please describe.**
The [`Placeholder`](https://github.com/WordPress/gutenberg/blob/6928e41c8afd7daa3a709afdda7eee48218473b7/packages/components/src/placeholder/index.js#L18) component (and other similar components) allow for `icon`, `label`, and `instructions` props, for an "informed" component. [`InnerBlocksTemplatePicker`](https://github.com/WordPress/gutenberg/blob/855be7927f31cf89229e954829e78e23d6a871e8/packages/block-editor/src/components/inner-blocks/template-picker.js) does not allow for this, as each of the corresponding props are established within the component itself.

It would be useful for blocks to pass custom `icon`, `label`, and `instructions` props, so the template picker can be relative to the current block. 

For example, we recently adapted this functionality within the [CoBlocks Form block](https://github.com/godaddy-wordpress/coblocks/pull/1128#issuecomment-557731336). It works great, but the template placeholder is not relative to the Form block. Without the block icon within the toolbar, you wouldn't know this was a Form block template/pattern selector.

<img width="595" alt="Screen Shot 2019-11-25 at 7 35 24 PM" src="https://user-images.githubusercontent.com/1813435/69592498-15162180-0fc4-11ea-8dff-4012bfd8017f.png">

**Describe the solution you'd like**

If props were available, I would:
1. Use the block's icon, in place of the layout icon currently provided
2. Change "Choose layout" to "Choose form layout"
3. Update the instructions to reference form templates.

These would all make the block's placeholder state much more relative, providing context to the pattern selector.

**Describe alternatives you've considered**
There are none.

**Comment by gziolo** [comment]
I have a patch ready in #18283 that addresses all the issues you mentioned. I also struggled with the default proposal which couldn't be customized for other block types.

The same PR renames `InnerBlocksTemplatePicker` to `BlockPatternPicker`. We still haven't decided whether it's going to be exposed as part of the public API but this PR does it and marks it as experimental.

**Comment by gziolo** [comment]
@richtabor, thanks for sharing your use case. I see that you are using experimental props for `InnerBlocks`:
https://github.com/godaddy-wordpress/coblocks/blob/520869d400807659f57479107461dca1b48fdb33/src/blocks/form/edit.js#L387-L400

I propose in #18283 we remove all those experimental features in favor of standalone `BlockPatternPicker ` which might even stay internal if we find a nice way to abstract Patterns API in a way where it's all handled by `BlockEdit` based on the registered patterns. This should make it easier to maintain all those predefined templates. I'm wondering if you have some thoughts on how this can be handled so CoBlocks could continue to work with the previous versions of Gutenberg. Do you think it's possible to implement some sort of feature detection?
