### ISSUE TITLE
Save button label should be filterable to better enable custom workflows with custom statuses

### ISSUE THREAD

**Issue by davisshaver** [WordPress/gutenberg#18743]
**Is your feature request related to a problem? Please describe.**
Working with the Edit Flow project, we have run into an issue regarding how best to alter the "save" label to reflect the target status. Currently the text flips from "Save" to "Save Draft" after a user clicks save, regardless of status, which we find to be a confusing user experience.

Here is where the label is generated: https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-saved-state/index.js#L104

See discussion here: https://github.com/Automattic/Edit-Flow/pull/555#issuecomment-558193745

**Describe the solution you'd like**
Allow the function that generates the label filterable. Here is the logic used for the "default" function.

```
const label = isPending ? __( 'Save as Pending' ) : __( 'Save Draft' );
```

If the function were filterable, plugins could provide a function that is passed or has access to the status and use their own mapping for what label should be returned.

**Describe alternatives you've considered**
Currently we are exploring `MutationObservers` and polling as ways to get an updated label text in the block editor. There are performance implications with these approaches and it would be ideal to identify a "block editor native" means of accomplishing this.

**Links to related issues**
We believe this issue is a new and self-contained feature request, but there are related issues open in the project already. See also:

- https://github.com/WordPress/gutenberg/issues/12788
- https://github.com/WordPress/gutenberg/issues/14833
- https://github.com/WordPress/gutenberg/issues/3144

**Comment by paaljoachim** [comment]
Hey @davisshaver Davis

How is this issue coming along?

**Comment by gziolo** [comment]
It should be now possible with the changes added in #27966.
