### ISSUE TITLE
WP Hover Link in Editor disappear when mouse leave of link

### ISSUE THREAD

**Issue by dhieuSynova** [WordPress/gutenberg#18744]
Hi WP, 

In WP admin editor, when I create link in editor in these steps:

1. add text in editor
2. attach link in that text
3. paste link
4. move mouse to click enter or settings button

At step 4, I cannot done because when mouse leave of link area, popup is disapear. Please help me fix it

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on WordPress 5.3, Gutenberg 7.7.0 and Chromium Chromium: 78.0.3904.108 

![link-issue](https://user-images.githubusercontent.com/3629020/69839379-2f017e00-12bc-11ea-976f-6c294b8bd6e3.gif)

@dhieuSynova, are you able to provide more details about the versions or WordPress and your browser, along with some screen captures of the problem you are experiencing?

**Comment by glendaviesnz** [comment]
Closing as can't be replicated, and no additional details provided by reporter.
