### ISSUE TITLE
Debugging "Updating failed. Error message: The response is not a valid JSON response."

### ISSUE THREAD

**Issue by mwoodpatrick** [WordPress/gutenberg#18796]
I'm trying to run wordpress 5.3 on Ubuntu 18.04 on Windows WSL-2 using:

nginx version: nginx/1.14.0 (Ubuntu)

mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

php-fpm7.2

When publishing simple posts I'm getting the error:

    Updating failed. Error message: The response is not a valid JSON response.

I have the following debug settings in my wp-config.php:

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'SCRIPT_DEBUG', true );
define( 'SAVEQUERIES', true );

but the query monitor and wp-content/debug.log are not showing any further details.

Any suggestions on what I can do to generate more detailed debugging information

**Comment by streetxmilena** [comment]
I am getting the error message "Updating failed." Without any further explanation.
When deactivating every plugin, the message says "Updating failed. Error message: The response is not a valid JSON response."

The solution I have found online was to use the old editor, which solves the error message, but it is unusable, makes everything very slow. 

Here is what the Site Health Plugin says about the site: 
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/virtual/fraestreik.lu/htdocs
wordpress_size: 50.83 MB (53302243 bytes)
uploads_path: /var/www/virtual/fraestreik.lu/htdocs/wp-content/uploads
uploads_size: 605.88 MB (635308697 bytes)
themes_path: /var/www/virtual/fraestreik.lu/htdocs/wp-content/themes
themes_size: 34.04 MB (35695117 bytes)
plugins_path: /var/www/virtual/fraestreik.lu/htdocs/wp-content/plugins
plugins_size: 84.07 MB (88149952 bytes)
database_size: 17.98 MB (18857984 bytes)
total_size: 792.80 MB (831313993 bytes)

### wp-active-theme ###

name: Divi (Divi)
version: 3.29.3 (latest version: 4.2.2)
author: Elegant Themes
author_website: http://www.elegantthemes.com
parent_theme: none
theme_features: custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /var/www/virtual/fraestreik.lu/htdocs/wp-content/themes/Divi

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team
Twenty Twenty: version: 1.1, author: the WordPress team

### wp-plugins-active (8) ###

Give - Donation Plugin: version: 2.5.13, author: GiveWP
Head, Footer and Post Injections: version: 3.1.6, author: Stefano Lissa
Health Check & Troubleshooting: version: 1.4.2, author: The WordPress.org community
Really Simple SSL: version: 3.2.9, author: Rogier Lankhorst, Mark Wolters
Smash Balloon Instagram Feed: version: 2.1.5, author: Smash Balloon
The Events Calendar: version: 5.0.0.1, author: Modern Tribe, Inc.
WP Statistics: version: 12.6.12, author: VeronaLabs
Yoast SEO Premium: version: 12.9.2, author: Team Yoast

### wp-plugins-inactive (3) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Classic Editor: version: 1.5, author: WordPress Contributors
Polylang: version: 2.6.9, author: WP SYNTEX

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 12
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.15.0-72-generic x86_64
httpd_software: Apache
php_version: 7.0.33-15+ubuntu18.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 30
memory_limit: 128M
max_input_time: 60
upload_max_size: 19M
php_post_max_size: 20M
curl_version: 7.58.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
server-headers: 
	date: Sun, 02 Feb 2020 16:25:23 GMT
	server: Apache
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	link: <https://www.fraestreik.lu/wp-json/>; rel="https://api.w.org/", <https://www.fraestreik.lu/>; rel=shortlink
	x-tec-api-version: v1
	x-tec-api-root: https://www.fraestreik.lu/wp-json/tribe/events/v1/
	x-tec-api-origin: https://www.fraestreik.lu
	x-frame-options: SAMEORIGIN
	strict-transport-security: max-age=0; includeSubDomains
	vary: Accept-Encoding
	content-encoding: gzip
	x-xss-protection: 1; mode=block
	content-type: text/html; charset=UTF-8
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.1.43-MariaDB-0ubuntu0.18.04.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/virtual/fraestreik.lu/htdocs/wp-content
WP_PLUGIN_DIR: /var/www/virtual/fraestreik.lu/htdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 128M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by youknowriad** [comment]
These issues are in general due to factors external to Gutenberg and Gutenberg can't provide you with more information about it.

- Consider checking your server logs.
- Consider checking your server configs.
- Disable plugins restricting REST API access.

These are just some ideas, as the error could be anything that generates a failure on the REST API.
