### ISSUE TITLE
Cannot modify block due to overlapping tag getting in way

### ISSUE THREAD

**Issue by bigvibes909** [WordPress/gutenberg#18807]
I’ve been battling with Gutenberg for quite awhile now and can’t seem to figure this one out.

When I try modifying a block, for example, I want to click the three vertical dots. There are times when I just cannot actually click the three dots icon because there’s an overlapping tag (the grey tags that label the block – eg. column). See this screenshot: https://prnt.sc/pxqvk6

I’ve tried resizing my browser and that does work sometimes, but not always.

Is there a way to turn off those labels? That would solve the problem.

**Comment by glendaviesnz** [comment]
Looks like a duplicate of https://github.com/WordPress/gutenberg/issues/16334
