### ISSUE TITLE
Full Site Editing: Request a documentation for testing

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#18803]
Hey,

I would like to test the experimental "Full Site Editing". However, I can not find documentation or help files for adding block templates or template_parts for use in custom content areas.

I think it would be very helpful if we could test this future feature to identify issues.

What is the current status and when can it start? :-)

**Comment by youknowriad** [comment]
The current status is that, there are a lot of issues and a lot of tesing is not something that will help us move forward today. 

That said, things are coming along nicely and we'll start adding documentation and call for testing soon enough.

Today, if you really want to be an early adopter, you should follow this label https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Full+Site+Editing%22

**Comment by CreativeDive** [comment]
@youknowriad thanks, I'm hoping for a first alpha version of this very useful feature :-)
I will certainly be one of the first to test this.

**Comment by youknowriad** [comment]
The initial documentation for this is available here https://developer.wordpress.org/block-editor/developers/themes/block-based-themes/
