### ISSUE TITLE
options table value in block

### ISSUE THREAD

**Issue by ipatate** [WordPress/gutenberg#18802]
how to get options table value in block ? 

select('core').getEntityRecord('options', 'blogname') ?

Thank you!

**Comment by talldan** [comment]
Hi @ipatate, The issues here are for bugs or enhancement requests related to development of the editor. For help requests please could you post your question somewhere else like the WordPress support forums (https://wordpress.org/support/forums/) or the WordPress stack exchange (https://wordpress.stackexchange.com/).

Thanks.

**Comment by ipatate** [comment]
It's enhancement because apparently, it's not possible.

**Comment by ipatate** [comment]
thanks
