### ISSUE TITLE
Enhance the Placeholder to better scale and adapt

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#18800]
The "Placeholder", or [the setup state of the block](https://developer.wordpress.org/block-editor/designers/block-design/#setup-state-vs-live-preview-state), is one of the most important pieces of the block editor. It serves to:

- Provide quick and easy setup of more advance blocks
- Provide slots in templates that users can "fill in"
- Provide helpful next steps

The component has been with us from the start. It has received many new features, but it has not been revisited in context of other features that were added, such as nested blocks or narrow slots as part of other compound blocks. In some cases it does not scale down beyond being a top level block:

![image](https://user-images.githubusercontent.com/1204802/69791623-2f6b1d80-11c5-11ea-9849-9469f85f6b3f.png)

This pull request is a first attempt at improving the scale of the placeholder: https://github.com/WordPress/gutenberg/pull/18745:

![69622478-4d0f7a00-1041-11ea-87e6-3e8439a6210e](https://user-images.githubusercontent.com/1204802/69791686-51fd3680-11c5-11ea-8723-afad97f2cae3.png)

But some of the design decisions made in that PR could use additional conversation and insight, and it could perhaps be informed by some of the efforts being explored in #18667. Some questions to ponder:

- What breakpoints should there be?
- What is the role of the icon, title, and description in the component? Do we need more, or less?
- What should be shown at the smallest possible breakpoint, how small should that be, and how should it behave?
- What is the relationship between controls available in the placeholder state, vs. them being present in the block toolbar after the fact?
- How can we reduce the visual appearance further? This could benefit compound blocks such as the Collage Gallery from CoBlocks.

_Collage Gallery_:
<img width="629" alt="Screenshot 2019-11-28 at 09 59 44" src="https://user-images.githubusercontent.com/1204802/69791959-e5cf0280-11c5-11ea-879c-f663c47fc126.png">

## Mockups

Building off of mockups in #18667, here are some ideas to help the discussion along:

<img width="1440" alt="Image Placeholder" src="https://user-images.githubusercontent.com/1204802/69792831-a1dcfd00-11c7-11ea-9b31-aa9927fdc9dc.png">

The base placeholder is vastly reduced to a single title, no icons, and a single primary button. This keeps it helpful for when you need quick access to any of those actions in large breakpoints, but keeps the appearance simple, which matters for templates that might include multiple placeholders.

When the placeholder is selected, it's focused and the block toolbar is present:

<img width="1440" alt="Placeholder has focus" src="https://user-images.githubusercontent.com/1204802/69792910-c507ac80-11c7-11ea-8e98-7c997148dcc2.png">

By left-aligning content, (right aligned in RTL languages), we can provide a natural balance to additional controls such as colors in the setup state:

<img width="1440" alt="cover" src="https://user-images.githubusercontent.com/1204802/69793015-f4b6b480-11c7-11ea-8f0a-5f1d5f5f000f.png">

This left aligned pattern can then scale to the toolbar itself:

<img width="1440" alt="cover 2" src="https://user-images.githubusercontent.com/1204802/69793031-fda78600-11c7-11ea-877f-ca54a554b339.png">

In very narrow context, we reduce the placeholder to a single word and button:

<img width="1440" alt="narrow" src="https://user-images.githubusercontent.com/1204802/69793050-0730ee00-11c8-11ea-9624-a8fd94fd1f58.png">

What does the button do, then? Does it expand the placeholder to full width in a modal/light-boxy fashion? Does it simply open a popover with options for browse or add a URL?

Your thoughts are welcome!

**Comment by ZebulanStanphill** [comment]
The <kbd>Add…</kbd> button could open a dropdown similar to the <kbd>Replace</kbd> button proposed in #16200.

![image](https://user-images.githubusercontent.com/107534/65603102-bd503f80-dfad-11e9-9265-d25b290568f6.gif)

**Comment by karmatosed** [comment]
> What breakpoints should there be?

I think we should be as fluid as we can, with it growing. However I think we can have 3 to start as fixed points:

- Smaller screens: for example an Android phone
- Tablet screens: for example iPad
- Monitor screens: starting from 13 inch laptop

> What is the role of the icon, title, and description in the component? Do we need more, or less?

I actually don't see the icon as important here and happy if it goes. I have similar feelings over title and description if they become a call to action of 'add your image' for example.

> What should be shown at the smallest possible breakpoint, how small should that be, and how should it behave?

I think that relates to my suggestion above of a smaller phone. I think it should clear as much out of way as possible.

> What is the relationship between controls available in the placeholder state, vs. them being present in the block toolbar after the fact?

I would actually like placeholders to move back to just being that. The changes there would be for example dragging into the interface (I think showing a hit area interaction is still useful feedback).

> How can we reduce the visual appearance further? This could benefit compound blocks such as the Collage Gallery from CoBlocks.

How minimal can we make them? Let's get them as minimal as possible!

The worst we have right now are button stacks (3 in places), we don't need that and things like the upload icon aren't giving ups anything here.

**Comment by jasmussen** [comment]
> The Add… button could open a dropdown similar to the Replace button proposed in #16200.

Yes, that's a good idea. There's potentially also some new patterns from #18667 we can leverage there:

<img width="1440" alt="replace menu" src="https://user-images.githubusercontent.com/1204802/69944500-c26ac700-14e7-11ea-95f2-2260d9360e53.png">

**Comment by jasmussen** [comment]
> Smaller screens: for example an Android phone
> Tablet screens: for example iPad
> Monitor screens: starting from 13 inch laptop

I think we actually need to go way smaller than that, so as to accommodate something like the coblocks gallery. For example a phone query would be around 320px, which should be enough to fit three buttons. But on a phone with the coblocks gallery, each of the placeholders should probably be reduced to a single button, i.e. have a query that is < 160px. 

In #18745, I used these sizes:

- Larger than 320px applies size-lg (size large) to the Placeholder component.
- Between 320px and 160px applies size-md (size medium)
- Below 160px, applies size-sm (size small)

So those three happen below the phone breakpoint.

> I would actually like placeholders to move back to just being that. The changes there would be for example dragging into the interface (I think showing a hit area interaction is still useful feedback).

Solid point. This needs a visual for what happens when you drop an image on a placeholder — this is an interaction that could need a love in what we have today. @pablohoneyhoney do you have any thoughts here?

**Comment by pablohoneyhoney** [comment]
> I would actually like placeholders to move back to just being that. 

Agree, reducing the elements of the interface to its most relevant and primary actions lowers the cognitive process. Reducing copy helps, even with localization.

**Comment by jasmussen** [comment]
I'm actually going to close this one as the primary purpose has been achieved with element queries in the placeholder component. Additional enhancements can be ticketed separately.
