### ISSUE TITLE
Gutenberg default CSS on frontend - how to?

### ISSUE THREAD

**Issue by sstepski** [WordPress/gutenberg#18819]
Hi,

NOTE: This question has been ignored or twisted by multiple 'experts' on multiple channels. This is my last resort.

I would like to include the default Gutenberg CSS in my theme.

By "default Gutenberg CSS" I mean the styles I can see inside the block editor when there are no editor styles attached.

In other words, I want to make the results of using the_content(); looking 1:1 like the editor.

I want to do this because I want to establish some kind of common ground between the editor and the content before I try to use my own styling. Currently when I'm trying to style (especially the editor style) I have no idea what I'm doing (or what I'm fighting, to be exact)

I understand this may also affect things outside the_content(); and I'm ready for it. I will just overwrite that stuff with my own CSS. 

Oh yeah, wp-block-styles is not the answer. I want full CSS, not jus the "odd" blocks.

**Comment by aristath** [comment]
In addition to `add_theme_support( 'wp-block-styles' );` you can try enqueueing the `wp-includes\css\dist\block-library\style.css` file. If I'm not mistaken adding `wp-block-styles` support loads the `wp-includes\css\dist\block-library\theme.css` file.

**Comment by youknowriad** [comment]
Looks like this was adressed

**Comment by TutorFx** [comment]
> In addition to `add_theme_support( 'wp-block-styles' );` you can try enqueueing the `wp-includes\css\dist\block-library\style.css` file. If I'm not mistaken adding `wp-block-styles` support loads the `wp-includes\css\dist\block-library\theme.css` file.

Dude, u just saved my life!
