### ISSUE TITLE
Navigation choose pattern of adding a new link

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18830]
Currently there are 2 different patterns of adding links:

- Clicking '+'
- Clicking sub nav link

When you are at the top level, to add a sub nav you can only click the sub nav link. However, when you are in the sub nav a '+' icon shows.

![image](https://user-images.githubusercontent.com/253067/69881682-aa1b6200-12c5-11ea-9273-44c58d98ff1f.png)

The confusing point is that of course, you can add a sub to the 2nd level item, making a 3rd level menu. However, this reads a little confusing.

The entire thing can get really complicated to navigate visually if you see the top level:

![image](https://user-images.githubusercontent.com/253067/69881739-d505b600-12c5-11ea-8cce-9c9c7292144e.png)

I would suggest we need to only show 2 clear ways of adding things by default and look at how we can focus depending on where you are.

**Comment by karmatosed** [comment]
This also gets worse the more sub nav you have:

![image](https://user-images.githubusercontent.com/253067/69884032-83adf480-12ce-11ea-9df2-e469d1e51ca1.png)

**Comment by yunjuc** [comment]
First time commenting so hope I didn't miss information from other discussions. 

I agree many sub nav "+" together is confusing. How about not having the sub nav "+" at all? I saw the sub nav "+" only shows up on the second level but not the first level, which means when users start using the sub nav "+", they also know how to use the sub nav link. 

Having only one way to add sub nave also makes "+" icon less ambiguous - "+" is for new link and sub nav icon is for sub nav.

**Comment by shaunandrews** [comment]
Maybe we take a cue from the Block Navigator UI and add some structural indicators for sub-navs:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/191598/70471679-ae046c80-1a9b-11ea-81ce-c5c01badba41.png">

**Comment by karmatosed** [comment]
I like that @shaunandrews, let's explore this in a PR and then see what it feels like. Removing design feedback to progress.

**Comment by apeatling** [comment]
Related: https://github.com/WordPress/gutenberg/issues/18333

**Comment by getdave** [comment]
> let's explore this in a PR and then see what it feels like

This is ready to be taken forward into code.

**Comment by karmatosed** [comment]
There absolutely is overlap, I think we can close out this issue and focus on the menu looking like the one that we have in #18310
