### ISSUE TITLE
Navigation Block not accepting formats

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#18844]
**Describe the bug**
The custom formats are not working on Navigation Block links. For example using [EditorsKit](https://wordpress.org/plugins/block-options/) plugin text and highlight color display this on the frontend. Thanks!

<img width="670" alt="Screen Shot 2019-12-01 at 12 27 28 AM" src="https://user-images.githubusercontent.com/3365507/69903204-96f5b880-13d1-11ea-9eae-8a350074264c.png">

**Comment by phpbits** [comment]
Just realized that all formats are not working on Frontend. Is it still under experimental? Thanks!

<img width="337" alt="Screen Shot 2019-12-01 at 12 40 21 AM" src="https://user-images.githubusercontent.com/3365507/69903375-32d3f400-13d3-11ea-95b6-ae7367763744.png">

**Comment by talldan** [comment]
Closing in favour of #21649, which while more recent has more detail.
