### ISSUE TITLE
Embed not spanning available width

### ISSUE THREAD

**Issue by westerdaled** [WordPress/gutenberg#18845]
The embed widget: with  only spans 500px rather than 100% of the available space - am pretty sure this working  perfectly, in a previous release

1. On my WordPress 5.3 / StudioPress 3.21/ Gutenberg 7.0 blog, I create a new page.
2. Next  I add an embed block and configure my url.

**Expected behavior**
In this case I wanted the entire featured image from the post link to span the space available.

Note, it looks like I would need jQuery to modify the width attribute of the embed iframe which seems like total overkill. 

**Screenshots**

![embed iframe](https://user-images.githubusercontent.com/937208/69903272-1f9f3500-138f-11ea-80c3-5e7654351a60.PNG)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 

**Additional context**
Gutenberg 7.0

**Comment by paaljoachim** [comment]
Hi @westerdaled Daniel

Thank you for creating this issue!
A lot of time has passed.
Is this issue still valid?

@ntsekouras Nik. I thought I would let you know about this issue.

**Comment by westerdaled** [comment]
I will have to recreate this issue and let you know although my site is being completely redesigned so no longer using the theme or indeed Genesis Framework.

**Comment by paaljoachim** [comment]
Should we close this issue, and if it is still valid you can open a new?

**Comment by ntsekouras** [comment]
Thanks for reporting this! I think it's okay to close. Feel free to reopen if needed.
