### ISSUE TITLE
Improve selectability

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#18846]
**Is your feature request related to a problem? Please describe.**
Some themes add a background image or complex background or just want to format some text in page body.

Currently, I have to use this selector, preferably either as CSS preprocessor or CSS variable:
```scss
$editor-gutenberg-background-selector: ".editor-writing-flow > div > div > div > .editor-block-list__layout";
````

The styles are enqueued, I try to use as much frontend-styles for backend as possible:
```php
/**
 * Gutenberg scripts and styles
 * @see https://www.billerickson.net/block-styles-in-gutenberg/
 */
function gutenberg_scripts() {
    wp_enqueue_style(
        'editor-theme',
        asset_path('styles/editor.css'),
        false,
        true
    );
}
add_action( 'enqueue_block_editor_assets', __NAMESPACE__ . '\\gutenberg_scripts' );
````
Especially generic text elements like `<p>`, `<ul>`, etc without a style variation need to be selected, too.
When I just select all `<ul>` I would either select all `<ul>` in WordPress backend and inspector panels, too - or nothing of them because I use a selector for the front end markup only (e.g. `body:not(.wp-admin) ul`, `main ul`).

**Describe the solution you'd like**
Some attribute or class for the innermost editor wrapper so background and typographic styles can be safely and easily applied by a theme (or plugin).

**Describe alternatives you've considered**
The alternative I am currently using is some custom selector that may change between Gutenberg updates which requires themes to handle different DOM structures for different Gutenberg versions.

**Comment by strarsis** [comment]
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#editor-styles

**Comment by mtias** [comment]
With the editor iframe targeting editor only / frontend without disturbing the admin chrome should be a lot easier.
