### ISSUE TITLE
Clicking Preview button opens blank browser tab

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18851]
**Describe the bug**
Tried to preview a Draft Post by clicking the Preview button and all it did was open an emnpty browser tab.

Vid: https://share.getcloudapp.com/geurv18X

**To reproduce**
1. Open Draft page
2. Click on Preview button
3. View blank/empty browser tab

**Expected behavior**
Clicking Preview should actually open a preview of the page

**Screenshots**
<img width="1440" alt="screenshot_46" src="https://user-images.githubusercontent.com/2078245/69910825-d40b8a80-1465-11ea-820b-3c5e2c7f6121.png">

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6
- Browser: Firefox 70.0.1
- Version: WP 5.3

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on WP 5.3 on Firefox or Chrome:

![preview-draft](https://user-images.githubusercontent.com/3629020/69923787-4d5db880-150c-11ea-9865-b7e5eaf495d7.gif)

@maddisondesigns  - are there any errors in the dev tools console in the Page Edit tab after you click on the preview link?

**Comment by maddisondesigns** [comment]
@glendaviesnz Just had another look into this. It appears to only be happening when I have the tab in "Responsive Design Mode" (using Firefox).

The Console generates the following error:
```
TypeError: this.previewWindow is null
editor.min.js:11:77696
    value http://your-wordpress-site.com/wp-includes/js/dist/editor.min.js?ver=9.7.5:11
    value self-hosted:1019
    Vh http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:163
    Uh http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:14
    Xh http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:14
    af http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:14
    Yh http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:164
    nd http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:15
    nc http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:15
    Of http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:38
    Ac http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:39
    bind_applyFunctionN self-hosted:1197
    Ac self-hosted:1161
    unstable_runWithPriority http://your-wordpress-site.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26
    Ma http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52
    Be http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:119
    xi http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:39
    xi self-hosted:1120
```

**Comment by talldan** [comment]
Thanks for the report @maddisondesigns. This one's a bug in firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1564471

The window.open command returns `null` for some reason even though the window opens.
