### ISSUE TITLE
Overlapping on columns block outlines

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18872]
This might need to link into another outline issue, but I noticed there is some rather confusing overlap going on for example with columns block and image:

![image](https://user-images.githubusercontent.com/253067/69977279-70936280-1522-11ea-9a0c-b73f5c40d77d.png)

cc @jasmussen for maybe looping this into another issue.

**Comment by jasmussen** [comment]
The dashed outlines should have been made better by #18105, in that they should be gone, mitigating this issue. Is this master?

The thing is, those block outlines are all outset from the block footprint by 14px. Which means that if you select a block inside a _column_ inside a columns block, there will essentially be conflicting stacked outlines. This is a strong argument for rethinking the block outlines in #18667 in two ways:

- Fewer. This isn't helping anyone.
- Perhaps reduce to just the block footprint, so we don't get this overlapping behavior. 
- Show only when _actually_ necessary.

**Comment by karmatosed** [comment]
This is master, unfortunately.

**Comment by jasmussen** [comment]
That's weird, I'm seeing this from having compiled just now:

![Screenshot 2019-12-02 at 18 28 27](https://user-images.githubusercontent.com/1204802/69980936-92e0ac80-1531-11ea-9efc-cae9380e6c05.png)

Could it be you've fetched a different origin of master? Or perhaps just need a fresh pull?

**Comment by karmatosed** [comment]
Ah ok, this is weird but good. I just grabbed again, npm installed and this is what see:

![image](https://user-images.githubusercontent.com/253067/69990069-e3113c00-153c-11ea-8001-5d17c91d07d3.png)

I will close this out as seems my original issue is fixed but there is still room to iterate here. Thanks.
