### ISSUE TITLE
Templates: PHP warning: glob(): At least one of the passed flags is invalid or not supported on this platform

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#18876]
**Describe the bug**

The calls to `glob()` in `gutenberg_find_template()` pass a value of `1` to the `$flags` parameter. I'm not sure what the intention of this flag is, but it's triggering a PHP warning and it should use one of the predefined `GLOB_*` constants instead of a numeric value.

The PHP warning that's showing up for me when viewing a page that uses full site editing is:

```
glob(): At least one of the passed flags is invalid or not supported on this platform
wp-content/plugins/gutenberg/lib/template-loader.php:151
```

**To reproduce**

1. Enable the Full Site Editing experiment from Gutenberg -> Experiments
2. Create a template from Appearance -> Templates, and give it a slug of `front-page`.
3. Visit your site's front page.

**Expected behavior**

Nice things happen.

**Screenshots**

Error in Query Monitor:

<img width="943" alt="" src="https://user-images.githubusercontent.com/208434/69995968-fa562680-1548-11ea-823e-571aa29173f3.png">

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
- Gutenberg 7.0.0
- PHP 7.3.12

**Comment by epiqueras** [comment]
I can't replicate this, it must be environment specific.

Does using the constants fix it?

We should use them anyways, so here is a PR: #18893.
