### ISSUE TITLE
Improve widescreen experience

### ISSUE THREAD

**Issue by pb52** [WordPress/gutenberg#1887]
On my 2K monitor the editing space occupies only 31% of the available screen width.  tinyMCE uses 100%

See areas highlighted in pink on screenshot
![image](https://user-images.githubusercontent.com/30155991/28178936-2649d490-67f8-11e7-87a0-65b88c1fcc68.png)

The 'Insert' link is out of focal point and out of peripheral vision way over on the right

Chrome Browser

**Comment by aduth** [comment]
While the existing post editor's UI extends the full width of the screen, the edited content does not (may depend on theme's `$content_width`).

![image](https://user-images.githubusercontent.com/1779930/28180730-0c4c11b2-67d4-11e7-94c7-97ae6c77f4c9.png)

May also relate to [ideal line length](https://en.wikipedia.org/wiki/Line_length) research.

**Comment by pb52** [comment]
The theme's content width is:

![image](https://user-images.githubusercontent.com/30155991/28182590-99fb8f58-6804-11e7-9bf3-28ba56c396e8.png)

**Comment by pb52** [comment]
The theme's content width is:

![image](https://user-images.githubusercontent.com/30155991/28182674-c6d81e1a-6804-11e7-86db-32e01d9405c9.png)

**Comment by pb52** [comment]
And I think ideal line length is my choice.

**Comment by swissspidy** [comment]
> The theme's content width is: […]

`$content_width` is something else. It's a value in pixels set by the theme in the code. It's usually around 600-800px as anything higher is really hard to read (again, ideal line length).

**Comment by pb52** [comment]
"It's usually around 600-800px as anything higher is really hard to read (again, ideal line length)."

But when you have 2 sidebars, that considerably reduces the body content width.  And, as I said before, if I choose to use a widescreen monitor then that is my choice.  I am perfectly happy with a display such as:
![image](https://user-images.githubusercontent.com/30155991/28184372-1116135a-680b-11e7-8ff7-63b5d2570af1.png)

And I also consume my content on a tablet and a smartphone.  My chosen theme is responsive to all those devices.  Why should I be limited on the editor?  I have been editing in full width on the wide screen ever since I started using WordPress and the width of the text has never been an issue for me.

I can see the benefit in having the editor reflect the same width as the body content of the theme but to squeeze me into a highly constrained box in the middle doesn't work for me.  Does the Theme's author have to change the theme to suit Gutenberg?  I hope not or there will be a lot of unhappy theme owners and users.

But as long as Gutenberg isn't imposed as core functionality and tinyMCE remains available as a plugin I won't have an issue.  I haven't found anything in Gutenberg that's of interest to me.  The new UI is a hindrance, not a help because it increases the clicks required to achieve tasks and forces the user to stop and think where things have been hidden.

**Comment by hedgefield** [comment]
It's true that the current editor takes its max-width from the theme (mostly by lack of tinymce setting a width, which means it uses the width from the theme's body property), but in gutenberg this has not been added yet, as far as I can see. The editor is set to a static pixel width by the developers, probably indeed based on ideal line length research.

`max-width: $visual-editor-max-width + ( 2 * $block-mover-padding-visible );`

It would be nice to make this optional at least (or indeed make it depend on the theme's setting again).

**Comment by pb52** [comment]
Yes that would help.  But unless there's an option to unhide everything that's useful, Gutenberg will never be for me.  It is a dreadful UI / UX.  I just hop it is not imposed as core product and that tincyMCE Advanced remains an option.  It has a few issues and it would have been better to fix those rather than reinventing the wheel and making it square.

**Comment by karmatosed** [comment]
In https://github.com/WordPress/gutenberg/issues/2045 there is more discussion about this. Closing that to merge to this older ticket.

**Comment by karmatosed** [comment]
@melchoyce reported this from a user:

> From: https://wordpress.org/support/topic/dreadful-awful-unusable/

Responsiveness has been totally ignored. I use a wide screen monitor. The current editor used the full-screen width. The new one uses a very narrow editing column in the centre of the screen and presents me with blank areas to both sides. Of the available screen width that the editing space could fill, Gutenberg uses 30.8% That’s less than a third of what’s available. tinyMCE uses 100%

> Meanwhile the “Insert” link (pretty important when you’re editing) is placed miles away in the top right corner, out of my focal point, beyond my peripheral vision.
Maybe we could consider a max-width on the content area on wide screens. Worth playing around with a couple different ideas to improve this experience.

**Comment by hedgefield** [comment]
Quote above comes from the OP of this issue ;)

I think targeting something adjacent to ideal line length is good as the default. Many people will probably not think so deeply about this, so we should make the decision for them based on what the research shows is the most comfortable. But there should be a way to extend this for people who want to. Personally I prefer something around 960px - which I believe is also the breakpoint at which Wordpress switches to tablet view.

A few ideas to start:

- Youtube has a dedicated button that extends the video to cover the entire body width (separate from the fullscreen button). It makes sense more for video than for text, but it could be a nice toggle. Something like this exists in the current editor, but not in gutenberg.

- [Ommwriter](https://ommwriter.com/) shows a fullscreen writing environment, and within that floats the text field. This area can be resized at will with the anchors on the sides of the text field. We could perhaps do something similar, by placing a grabbable control next to the text area, by which you can stretch it to your desired width. This should only appear on the desktop when enough empty space appears around the text column.

**Comment by mtias** [comment]
It would be easy to add a setting at the document level for changing the main content length. Also it is expected themes can inform the default, probably through the work being done in https://github.com/WordPress/gutenberg/pull/2021

**Comment by pb52** [comment]
As long as it's a set once and forget option, that's fine.  But I don't
want to have to reset this every time I go in.  The problem, it seems to
me, that 'responsive' seems to be applied at the bottom end of the scale
range but not the top.  Yet something like 35% of the monitors being bought
today are > 25 inches.

Paul (The OP)

**Comment by mtias** [comment]
> As long as it's a set once and forget option, that's fine.

Of course.

> The problem, it seems to me, that 'responsive' seems to be applied at the bottom end of the scale range but not the top.

That's not true. Many of us are working on large monitors. It's just that—design wise—the preference has been set for what is generally considered to be a readable line length. Some people, like yourself, may have different preferences, and that's ok. The above are a few ways to offer that, but it's not a general disregard for large viewports.

**Comment by pb52** [comment]
OK, I get that now.

What about my other issues?  Is there going to be an option to have all the
edit options visible at all times instead of disappearing when you are not
doing a mouse-over?  I don't mind menus being context sensitive but I do
want to see them please

Paul

**Comment by mtias** [comment]
Sorry, I must have missed that. Which ones are you referring to that appear / disappear on mouse moves?

**Comment by melchoyce** [comment]
Would it help if the top menu (From the visual/text switcher to publish) had a max-width, maybe between 1400–1600px?

**Comment by pb52** [comment]
Around the top of the edit box there are hidden editing functions that only
appear on mouse over

**Comment by jasmussen** [comment]
Given changes to the top-bar since July, as well as the option to fix the toolbar to the top of the screen, I feel like this issue is largely addressed, and going to close it as such. 

If there are still sub-optimal issues on wide screens, it's perfectly fine to open separate specific tickets for those.
