### ISSUE TITLE
Huge icons

### ISSUE THREAD

**Issue by djkeu** [WordPress/gutenberg#18875]
![gutenberg icons](https://user-images.githubusercontent.com/58443395/69988518-14d8d180-1542-11ea-8381-a352ad02b4ad.jpg)

See picture/attachment for how icons show up in my WordPress 5.3 installation, using the twenty-twenty theme, although this was also the case in earlier installations. As you can (just about) see the huge icons in the pulldown menu's push the text to the right, leaving it pretty unworkable. The same happens with the icons in the sidebar. 

Any solution would be welcome.

**Comment by aduth** [comment]
@djkeu Can you please include some details about your browser and operating system? This should have been one of the prompted questions in the issue template.

**Comment by djkeu** [comment]
Using Firefox 70.0.1 on Windows 10.

**Comment by aduth** [comment]
I was unable to reproduce this under an identical browser environment:

![image](https://user-images.githubusercontent.com/1779930/69989329-69b02400-1511-11ea-9d12-08d69e97e7d8.png)

I notice in your screenshot that there is a non-default text background color. Could you share what theme you are using, or try to change to a different theme to see if it makes any difference?

**Comment by aduth** [comment]
Oh, I see you mentioned TwentyTwenty. It doesn't seem that should be how the editor background appears with that theme, however 🤔 (my screenshot above is using TwentyTwenty)

**Comment by djkeu** [comment]
The icons appear huge indepent of the background color and in fact also appear this way in older themes, but if you'd like to I can provide you with a screenshot..

**Comment by aduth** [comment]
Would you be able to share which plugins you have active on the site?

**Comment by djkeu** [comment]
Sure!

- Akeeba backup for Wordpress
- Akismet Anti_spam
- Audiomack
- Companion Auto Update
- Gutenberg (7.0.0)
- Jetpack
- Menu in post
- NextGEN Gallery
- PHP compatibility checker
- Posts in sidebar (left-over from an older theme)
- Simple Image Sizes (hm...)
- SiteOrigin CSS (active, but not in use to add any css)
- Social Media Feather
- Sticky Menu (or Anything!) on Scroll
- Vanilla PDF embed
- WP editor

**Comment by aduth** [comment]
Do you have any relevant browser extensions to note, particularly those which might filter content?

From a technical point-of-view, I can see how this might happen if the `width` and `height` attributes are removed from the icon's `svg` HTML, demonstrated in the screenshot below which appears very similar to your original report.

![image](https://user-images.githubusercontent.com/1779930/70001398-37abbb80-152b-11ea-8daa-f029976ab6c1.png)

Of course, this should never happen under normal conditions, which gets me wondering if it's filtered by some browser extension, or perhaps one of the plugins running on your site.

Some potential debugging tasks you might consider:

- Are you able to reproduce on any other sites, if you are able to test on one? Perhaps using a test environment like [jurassic.ninja](https://jurassic.ninja/)
- Does it happen in all browsers?
- If possible, try temporarily deactivating all plugins, or one plugin at a time, to see if it makes any difference

**Comment by djkeu** [comment]
I use 'uBlock origin' to block ads but doesn't block any parts of the wordpress installations (turned it off just to make sure and indeed the problem persists).

Next to the huge icons there are some differences between how the fonts show up in the editor and how the appear on the site, most notably the sans-serif fonts on the site (using a little css) showing up as serif in the editor, which does indicate different stylesheets are used. Which may control the way the icons appear.

I'm going to try deactivating the plugins first to see if it will have any effect and if it doesn't, I will try to perform the other debugging tasks you suggested.

**Comment by djkeu** [comment]
It does happen in Edge as well by the way.

**Comment by djkeu** [comment]
Deactivating all plugins solved the problem.
I'm just gonna have to find out which one is the faulty one. Thanks for your help, much appreciated!

**Comment by aduth** [comment]
Glad we could pinpoint the problem, and thanks for following up with the specific plugin. Are you able to report this issue to the developer? It will be good to have in mind, in case other users encounter similar issues.
