### ISSUE TITLE
All text in paragraph block hidden on selection (Microsoft Edge)

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#18889]
**Describe the bug**
When selecting all of the text or blocks the text in the paragraph block is not visible.

**To reproduce**
1. Open Microsoft Edge
2. Create a new post with a paragraph of text
3. Select all with keyboard shortcut "ctrl + a"
4. See issue

**Expected behavior**
Still be able to see the text when selecting all of the blocks or text.

**Screenshots**
Not selected
![Not selected](https://user-images.githubusercontent.com/1785641/70068214-dbf73600-15ef-11ea-8408-b97262487155.JPG)
Selected
![selected](https://user-images.githubusercontent.com/1785641/70068229-e5809e00-15ef-11ea-99fb-3058a27087d6.JPG)

**Environment**
 - OS: Windows 10
 - Browser: Edge
 - Version: 42.17134.1.0
 - WordPress:5.3
 - Gutenberg: 7.0

**Comment by ellatrix** [comment]
Is this fixed in `master`? The multi selection behaviour has changed.

**Comment by grappler** [comment]
I tested the issue with Gutenberg 7.1. The text is being shown when the text is selected.

The problem I am see now is that `ctrl+A` or `cmd+A` is selecting all of the blocks in Edge but in Chrome it only selects all of the text in a block. In Chrome only when using the shortcut again is all of the blocks selected.

@ellatrix Would you prefer me to open a new issue for this?

**Comment by ellatrix** [comment]
@grappler Yes please! :)

**Comment by grappler** [comment]
> Yes please! :)
Done #19102

Fixes in #18915
