### ISSUE TITLE
Paste from Microsoft Word in Microsoft Edge

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#18888]
**Describe the bug**
Random characters are added to end of paragraph on paste from Word in Edge.

The random characters also exist in "Received HTML" in the console. This seems to be only a problem with Gutenberg. Pasting the same text in a normal field is not a problem.

**To reproduce**
1. Copy a paragraph from Microsoft Word
2. Create a new post in Microsoft Edge on Windows 10
3. Paste the the paragraph
4. See the extra content at the end.

**Expected behavior**
No extra content after pasting the paragraph.

**Screenshots**

![Paste end](https://user-images.githubusercontent.com/1785641/70067835-317f1300-15ef-11ea-9c5e-8708182ebb9c.JPG)

**Environment**
 - OS: Windows 10
 - Browser Microsoft Edge 
 - Version: 42.17134.1.0
- WordPress: 5.3
- Gutenberg: 7.0

**Comment by ellatrix** [comment]
Thanks for the report, @grappler. :) Could you share what the console is logging for you when you paste? Thanks!

**Comment by Soean** [comment]
@grappler I can't reproduce the problem with the current Edge version. Can you confirm if the issue still exists?

**Comment by grappler** [comment]
@Soean Thank you for testing this. Which version of Edge and Gutenberg were you using?

**Comment by annezazu** [comment]
Closing this out since there hasn't been a reply. You're welcome to reopen this @grappler if this is still a problem. If you do so, please provide what the console is logging along with the latest version of WordPress & Gutenberg you've tested this on!
