### ISSUE TITLE
Focus issue when using select tool on nested blocks

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#18881]
## Description
If you click repeatedly in just the right spot, you can get some weird behavior while using the select tool. Clicking too quickly causes the block to become invalid, and then if you try to click a block again, the editor crashes.

![select-mode-weirdness](https://user-images.githubusercontent.com/19592990/70018895-1fe52f00-154d-11ea-99bf-48e2386f262c.gif)
![image](https://user-images.githubusercontent.com/19592990/70019171-04c6ef00-154e-11ea-900f-af5e02df442e.png)

## How to reproduce
1. Create a Group block.
2. Create a Columns block inside the Group block.
3. Use the Select tool to select the Columns block.
4. Click in the area shown in the GIF; if you click in the right spot, you will select the Group block.
5. Keep clicking in the same spot. You will alternate between selecting the Columns and the Group block.
6. Try clicking more quickly; the block will become invalid. If you keep clicking, the editor will crash.

## Environment
- WordPress 5.4-alpha-46810
- Gutenberg `master` as of https://github.com/WordPress/gutenberg/commit/0303999ddc0c798b1c0e3b1a6b750d1f26319b69
- Using Dissenter browser 0.70 (based on Chromium 78)

**Comment by talldan** [comment]
I couldn't reproduce it in Chrome, but maybe I was clicking in slightly the wrong place.

**Comment by ZebulanStanphill** [comment]
It seems like the issue is a lot easier to reproduce when using a Group block nested in another Group block. (Look at the breadcrumb bar to see which block you currently have selected.)

**Comment by ZebulanStanphill** [comment]
Actually, nevermind. How easy it is seems to vary for some reason. If you can't seem to find the right spot, try unselecting the block and trying again.
