### ISSUE TITLE
error: Ha fallado la actualización. Mensaje de error: Las respuesta no es una respuesta JSON válida.

### ISSUE THREAD

**Issue by darkkail** [WordPress/gutenberg#18887]
Al actualizar a la versión 5.3, me arroja el siguiente error: Ha fallado la actualización. Mensaje de error: Las respuesta no es una respuesta JSON válida..
He buscado como solucionarlo pero no ha sido exitoso, espero puedan orientarme, muchas gracias

**Comment by gziolo** [comment]
English translation by Google Translate:

> When updating to version 5.3, I get the following error: The update failed. Error message: The response is not a valid JSON response.
I have looked for how to solve it but it has not been successful, I hope you can guide me, thank you very much

Can you provide more details:
- when exactly does it happen?
- do you have Gutenberg plugin installed?
- what OS and browser do you use?

Thanks.

**Comment by Ritsu95** [comment]
Hello @gziolo, I have the same problem.

- **when exactly does it happen?**
I get that message wether I create a new post/page and try to publish it or I just push the "Publish" button on a draft. There is a short wait (like 10-15s more or less) and then the message, like as a timeout.

- **do you have Gutenberg plugin installed?**
I have a fresh Wordpress 5.3.2 installation, no plugins at all and just the default themes (Twenty Sixteen 2.0, Twenty Seventeen 2.2, Twenty Nineteen 1.4 and Twenty Twenty 1.1).

- **what OS and browser do you use?**
I normally use Safari 13.0.4 or Chrome v79.0.3945.88 on MacOS 10.15.2. I've also tried from a Windows 10 computer (both Chrome and Edge) and on smartphones/tablet (Safari/Chrome on iOS and Chrome on Android)

**Comment by Dmontenegro214** [comment]
I have the same problem, no one can give a solution.

**Comment by Dmontenegro214** [comment]
Hey! I installed the classic editor plugin of wordpress and no more problem at least publishing pages. Elementor still not working.

**Comment by Ritsu95** [comment]
"Not using Gutenberg" is not a solution to the error, it's a workarround.
Anyway, Gutenberg is the default editor on WordPress, so it should "just work" on a fresh installation.

**Comment by cris-Duarte** [comment]
Hi Guys... 
I just wanna say I got the same problem... (exactly the same)
I installed the Classic Editor, and nothing works 
Just that, I'll inform you all if I got a solution

Have a nice day

**Comment by cris-Duarte** [comment]
JFR 
https://es.wordpress.org/support/topic/problemas-al-cargar-las-imagenes/
In the forum, the discuss the same error but do not provide any solution

**Comment by A2020gm** [comment]
Hi all,
I have the same problem when change permalink settings in a fresh Wordpress V 5.3.2 installation over Ubunbtu Server 18.04.03 LTS.
Solved if I select option "Simple" in Wordpress-->settings --> permanent links.

**Comment by aduth** [comment]
>Solved if I select option "Simple" in Wordpress-->settings --> permanent links.

This can often help clear up issues in my experience. The problem can occur if rewrite rules are not configured correctly for the site. This can also be a problem based on how the server is configured, or if the site is using some sort of CDN solution (e.g. Cloudflare).

https://ixnfo.com/en/error-solution-with-rest-api-the-response-is-not-a-valid-json-response-wordpress-nginx.html
https://community.cloudflare.com/t/wordpress-updating-failed-error-message-the-response-is-not-a-valid-json-response/135947

Ultimately, this is not a bug with Gutenberg, and is indicative of the WordPress REST API not being available. Gutenberg is simply a consumer of the REST API.

You can usually verify whether an issue exists with the REST API using the Site Health tool available with WordPress 5.1 and newer.

https://wordpress.org/news/2019/02/betty/

**Comment by wifixcort** [comment]
> Hi all,
> I have the same problem when change permalink settings in a fresh Wordpress V 5.3.2 installation over Ubunbtu Server 18.04.03 LTS.
> Solved if I select option "Simple" in Wordpress-->settings --> permanent links.

Yes, this in some way fix the problem, but if you want to use something different from "Simple" it does not work

I'm using a fresh install of Wordpress
