### ISSUE TITLE
Templates: "Sorry, you are not allowed to move this item to the Trash."

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#18880]
**Describe the bug**
It seems like it's not possible to remove a template if the template's title and slug have the "index" word in it.

**To reproduce**
1. Enable the Full Site Editing experiment from Gutenberg -> Experiments.
2. Create a new template in Appearance  -> Templates -> Add New.
3. Use "index" for the title and the slug (see a screenshot).
4. Publish a template.
5. Go to Appearance  -> Templates and select the template you've created in a step 4.
6. Select "Move to Trash" from the Action drop-down list.
7. Click Apply. 

**Expected behavior**
The template should be moved to a trash.

**Screenshots**

![The Block Editor with a custom template](https://i.snipboard.io/4G7fH3.jpg)

![Error message](https://snipboard.io/bJiEpn.jpg)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
- Gutenberg: 7.0.0
- WordPress: 5.4-alpha-46782

**Comment by epiqueras** [comment]
This was originally intended so that the behavior matched regular theme templates where you need to have an index template.

It was changed/fixed in https://github.com/WordPress/gutenberg/pull/18554/files#diff-9ef35a788437d52364a1e2b87b2e9730.
