### ISSUE TITLE
DropZone: Pass originating event in onHTMLDrop and onFileDrop callbacks

### ISSUE THREAD

**Issue by mwidmann** [WordPress/gutenberg#18885]
**Is your feature request related to a problem? Please describe.**

Trying to implement a Drag'n'Drop enabled block from an external resource (in our case our editorial archive) is rendered difficult as `DropZoneProvider` hides away data that is would be valuable as it makes some arbitrary choices. 

Dragging the required content from our archive system has three types in the `e.dataTransfer.types`
array: ["text/plain", "text/uri-list", "text/html"]. in DropZone this results in `onHTMLDrop` to be used to give the data back, but only the data provided by `e.dataTransfer.getData('text/html')` 

**Describe the solution you'd like**

Besides passing an array of files and the position in `onFilesDrop` or the html and the position in `onHTMLDrop` also pass the originating event as a third argument.

Alternatively always also trigger `onDrop` which receives the originating event.

**Describe alternatives you've considered**
For the time being I'll try to implement my own DropZoneProvider which passes the data I need.

**Comment by mwidmann** [comment]
Ok, so i tried to somehow find a way to handle the drag and dropping in my component on my own, but that doesn't seam to be feasible.

But I found out there is a `window.event` set when `onHTMLDrop` or `onFileDrop` is set. I'm not sure how stable this will work and how consistent the data is. Therefore it would still be better if the two functions passed on the events. 

Until then I hope using `window.event` works.

**Comment by talldan** [comment]
@mwidmann Thanks for explaining the use case. I suppose you've identified that this is the relevant code:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/drop-zone/provider.js#L204-L215

This does seem a bit restrictive. A Pull Request is welcome if you have a proposal on how to change this (a third argument as you propose seems like an option, or possibly a way to configure `dropZone` to use `onDrop`?).

**Comment by Mamaduka** [comment]
I think this can be closed after recent iterations on the DropZone component (see #30310).

Why?

* The `DropZoneProvide` is deprecated.
* [`DropZone` components](https://wordpress.github.io/gutenberg/?path=/docs/components-dropzone--docs) `onDrop` prop can be used to access the whole event.
