### ISSUE TITLE
Block type unexpectedly not registered when icon is '' or null in WordPress 5.3

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#18894]
Before WordPress 5.3, it was possible to register a block type using an empty string or null value for `icon`. This would result in the block type using the default 'block' icon.

In WordPress 5.3, a block type registered with `icon: ''` or `icon: null` will trigger this warning:

![image](https://user-images.githubusercontent.com/36432/70078093-f19c3980-15b6-11ea-96fe-04c73c29126d.png)

The early return statement added in https://github.com/WordPress/gutenberg/commit/1a7255fb751f1bf519968330c8ca5fcda740c1e5#diff-bcd12caf7289c956a519c4cd8f3f363eR144-R150 causes the block type to not be registered.

My expectation is that a block type with `icon: ''` or `icon: null` would be registered with a default icon.

I took a look at the history of `normalizeIconObject` (https://github.com/WordPress/gutenberg/blame/a71241ca616642f6f590d6982fd82b46d96158ac/packages/blocks/src/api/utils.js#L85-L106). It seems like the last changes are a year old, so I'm not sure why we're only now experiencing this issue?

**Comment by tellthemachines** [comment]
I can confirm that this error is occurring when a block is registered with `icon: ''` or `icon: null`.

**Comment by gziolo** [comment]
Opened #34350 to address it.
