### ISSUE TITLE
Navigation Link: Default to list of pages

### ISSUE THREAD

**Issue by obenland** [WordPress/gutenberg#18899]
By default the Navigation Link block shows an empty search box, which is not super helpful when looking to add a new link. Rather than forcing users to search for the page they just created before they're able to add a link to it, let's offer them a list of their most recent pages by default.

**Comment by getdave** [comment]
I'm going to take a look at this one.

**Comment by getdave** [comment]
I'll be updating this comment as I explore possible approaches.

## Basic Research

* The Nav Link block uses `<LinkControl />` to create the hyperlink creation interface. It is this component that needs to display the list of default Pages.

## Possible Approaches
