### ISSUE TITLE
Navigation Block adds an empty link for untitled pages

### ISSUE THREAD

**Issue by guicmazeredo** [WordPress/gutenberg#18897]
**Describe the bug**
When creating a navigation block from all top pages, if there are untitled pages, the links to these pages not added. 

**To reproduce**
1. Make sure you have at least 1 page published with no title.
2. Add a Navigation Block to a page. 
3. Click on "Create from all top pages" 
4. A menu item is added for the untitled page but it doesn't have a link to the page like the other pages. 

**Expected behavior**
I would expect that the link to the page would be pulled just like it does for pages with titles. I also find that it would be more clear if instead of "Add link" the menu item was named "Untitled" just like it appears for untitled pages. 

**Screenshots**
I recorded this video to show:

https://d.pr/v/kqxxCc

**Comment by WunderBart** [comment]
> I would expect that the link to the page would be pulled just like it does for pages with titles.

I can see that the link is actually pulled correctly there:

![untitled top level page nav link](https://user-images.githubusercontent.com/1451471/71975793-1d918700-3215-11ea-822b-21be3e1d2f12.gif)

Could you confirm, @guicmazeredo?

**Comment by WunderBart** [comment]
> it would be more clear if instead of "Add link" the menu item was named "Untitled" just like it appears for untitled pages.

Should we use `(no title)` instead of `Untitled` [as we currently do for posts without titles](https://github.com/WordPress/gutenberg/pull/17074)? I'd also suggest to prepend the post number to `(no title)` as it's currently done in the Primary Menu:

![image](https://user-images.githubusercontent.com/1451471/71976669-2daa6600-3217-11ea-9602-3fa186fbc0f8.png)

**Comment by marekhrabe** [comment]
it sounds reasonable to match `(no title)` from other places 👍
