### ISSUE TITLE
Navigation Block Doesn't Output Alignment Classes

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#18898]
**Describe the bug**
The navigation block doesn't output wide/full alignment classes.

**To reproduce**
1. Add a navigation block
2. Select "Wide" alignment
3. Publish
4. View page

**Expected behavior**
Classes should show up on frontend.

**Screenshots**
<img width="437" alt="Screen Shot 2019-12-03 at 3 50 16 PM" src="https://user-images.githubusercontent.com/46652/70092780-a39e2a80-15e4-11ea-9c72-7da2e3303a71.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
- Theme: 2020

**Comment by obenland** [comment]
@getdave Do you think you could take a look at this? 
This should probably also include left-, right-, centeralign classes.

**Comment by getdave** [comment]
@obenland Agreed. I've addressed this in https://github.com/WordPress/gutenberg/pull/18909.
