### ISSUE TITLE
cover image bug 

### ISSUE THREAD

**Issue by kevIN-kovaDIA** [WordPress/gutenberg#18891]
add cover block in gutenberg page buidler.

1) add cover block in gutenberg page buidler.
2) Select assent ( in my case green color) or any color as cover block background.
3) add any image from media gallery.
4) after adding image, suppose we do not like an image and we would like to set default assent or any  fix color background, then there is no option for the same.

![Screenshot from 2019-12-03 22-52-07](https://user-images.githubusercontent.com/38972017/70074401-a3238500-1620-11ea-8173-4110c98708c5.png)

kindly do needful.

**Comment by talldan** [comment]
Thanks for the report @kevIN-kovaDIA. 

This might be something that has recently been fixed. I can see a `Clear Media` button for removing the image:
![Screen Shot 2020-01-24 at 3 35 46 pm](https://user-images.githubusercontent.com/677833/73052089-3b224a00-3ebf-11ea-9ac6-963822f8681b.png)

I'll close this as it seems to be working well in the latest version of the plugin. Definitely reply if you're still having problems though.
