### ISSUE TITLE
Forward slash popover doesn't go away when clicking other icons

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#18918]
**Describe the bug**
When I do that forward slash command to begin searching for a block, but then change my mind to click on another UI element in the page, the popover doesn't go away.

**To reproduce**
1. Begin typing `/` followed by a word to bring up the popover.
2. While this is visible use your mouse and click on another icon on the page.
3. Observe that the popover doesn't disappear.

**Expected behavior**
When clicking on other UI elements, I expect the popover to disappear.

**Screenshots**

![popover-of-doom 2019-12-04 10_01_45](https://user-images.githubusercontent.com/617986/70168370-9123ff80-167d-11ea-8f98-4502deb65ad9.gif)

**Desktop (please complete the following information):**
 - OS Catalina
 - Chrome and FF most recent builds
 - Gutenberg 7.0

**Comment by draganescu** [comment]
I think this is a side effect of a recent change of the focus setting on the appender #18379

**Comment by draganescu** [comment]
nope, testing showed that change not to be the problem, looking into some z-index things now.

**Comment by draganescu** [comment]
@tellthemachines [this commit](https://github.com/WordPress/gutenberg/pull/17696) appears to have moved the top bar popovers lower in the stack which created the behaviour found by Mark. No idea how to solve (z-index hell) but I thought you could come up with a wise solution!

**Comment by tellthemachines** [comment]
@draganescu I would expect the forward slash popover to close when focus is moved elsewhere on the page, and that's unrelated to z-index. z-index only affects if it displays over or under the other elements, but even if it displays under the top nav stuff it's still open, and it should be closed.  Will need some investigation to find out why this is happening.

**Comment by annezazu** [comment]
Noting that I can't replicate this in Gutenberg 10.0.2 and am closing this out as a result. If this should be re-opened, please do so! Here's a video of the current behavior:

https://user-images.githubusercontent.com/26996883/109734527-62495180-7b7e-11eb-856b-2685030bbef5.mov

**Comment by annezazu** [comment]
Sigh. Forgot to close ;)
