### ISSUE TITLE
Post Published Notice Appears Ontop of Flyout menu

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1892]
Version 0.4

## Issue Overview

After publishing a post, the notice can be on top of the admin menu flyouts. Observed in Chrome

## Steps to Reproduce (for bugs)

1. Publish a Post
2. Hover over a menu item near the notice

## Expected Behavior

I expect the menu to appear on top of the notice

## Current Behavior

<img width="363" alt="screen shot 2017-07-13 at 5 39 03 pm" src="https://user-images.githubusercontent.com/622599/28189099-94cb1e0c-67f2-11e7-95d1-39147628708a.png">

## Possible Solution

Adjust the z-index on the notice

**Comment by nylen** [comment]
#1884 will fix this

**Comment by nylen** [comment]
Fixed in #1884.
