### ISSUE TITLE
The enqueue_block_assets hook gets assets enqueued in the Editor!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#1893]
As far as I know, Gutenberg has introduced to new hooks!

- `enqueue_block_editor_assets` for assets to be enqueued for Editor only.
- `enqueue_block_assets` for assets on frontend 

This `enqueue_block_assets` hook, however, is also including the assets in the editor which is causing problems! 

```php

// Hook: Editor assets.
add_action( 'enqueue_block_editor_assets', 'gb_block_04_tweet_editor_assets' );

/**
 * Enqueue the block's assets for the editor.
 *
 * @since 1.0.0
 */
function gb_block_04_tweet_editor_assets() {
	// Scripts.
	wp_enqueue_script(
		'gb-block-04-tweet', // Handle.
		plugins_url( 'block.js', __FILE__ ), // Block.js: We register the block here.
		array( 'wp-blocks', 'wp-i18n', 'wp-element' ), // Dependencies, defined above.
		filemtime( plugin_dir_path( __FILE__ ) . 'block.js' ) // filemtime — Gets file modification time.
	);

	// Styles.
	wp_enqueue_style(
		'gb-block-04-tweet-editor', // Handle.
		plugins_url( 'editor.css', __FILE__ ), // Block editor CSS.
		array( 'wp-edit-blocks' ), // Dependency to include the CSS after it.
		filemtime( plugin_dir_path( __FILE__ ) . 'editor.css' ) // filemtime — Gets file modification time.
	);
} // End fucntion gb_block_04_tweet_editor_assets().


// Hook: Frontend assets.
add_action( 'enqueue_block_assets', 'gb_block_04_tweet_block_assets' );

/**
 * Enqueue the block's assets for the frontend.
 *
 * @since 1.0.0
 */
function gb_block_04_tweet_block_assets() {
	// Styles.
	wp_enqueue_style(
		'gb-block-04-tweet-frontend', // Handle.
		plugins_url( 'style.css', __FILE__ ), // Block frontend CSS.
		array( 'wp-blocks' ), // Dependency to include the CSS after it.
		filemtime( plugin_dir_path( __FILE__ ) . 'editor.css' ) // filemtime — Gets file modification time.
	);
} // End fucntion gb_block_04_tweet_block_assets().
```

Looking forward!

**Comment by ahmadawais** [comment]
I have to fix it this way! 

```php
// Hook: Frontend assets.
add_action( 'enqueue_block_assets', 'gb_block_04_tweet_block_assets' );

/**
 * Enqueue the block's assets for the frontend.
 *
 * `wp-blocks`: includes basic styles built out of Gutenberg through `npm build`.
 *
 * @since 1.0.0
 */
function gb_block_04_tweet_block_assets() {
	// Only frontend.
	if ( ! is_admin() ) {
		// Styles.
		wp_enqueue_style(
			'gb-block-04-tweet-frontend', // Handle.
			plugins_url( 'style.css', __FILE__ ), // Block frontend CSS.
			array( 'wp-blocks' ), // Dependency to include the CSS after it.
			filemtime( plugin_dir_path( __FILE__ ) . 'editor.css' ) // filemtime — Gets file modification time.
		);
	}
} // End fucntion gb_block_04_tweet_block_assets().

```

I don't think that this is an intentional behavior!

**Comment by swissspidy** [comment]
The [README](https://github.com/WordPress/gutenberg/blob/ac75dba9f712d77390f0ce0c64799c0441e36b80/blocks/README.md) clearly says:

> There is also an `enqueue_block_assets` hook which is run under __both__ the editor and front-end contexts.

See also https://github.com/WordPress/gutenberg/blob/7779f79b844ed9ce13bdbddebeff88df0d5c7628/docs/blocks-stylesheet.md.

So it's basically the other way around than you think:

`enqueue_block_editor_assets` is for editor specific blocks only. `enqueue_block_assets` is for block styles in general (which are needed in the editor _and_ on the front end, after all)

So looking at the docs this all seems to be working just as intended. Perhaps we could make the docs more clear, but there's also nothing wrong with an `is_admin()` check in your code, really. If really needed, you could also wrap your `add_action( 'enqueue_block_assets', … )` call inside another function that is hooked to `wp_enqueue_scripts`.

**Comment by ahmadawais** [comment]
@swissspidy Thanks for making it clear :) I'll probably send in a PR to update docs.

**Comment by ahmadawais** [comment]
It's confusing coz the heading says `Frontend Styling` → https://github.com/WordPress/gutenberg/blob/7779f79b844ed9ce13bdbddebeff88df0d5c7628/docs/blocks-stylesheet.md#front-end-styling

**Comment by aduth** [comment]
Could you describe your use-case for front-end only styles for a block?

**Comment by swissspidy** [comment]
Front-end only _scripts_ make more sense I guess.

**Comment by ahmadawais** [comment]
@aduth It can be anything! Maybe I want an icon to be displayed only on the frontend and not on the backend for a tweet block. Or maybe, for frontend I need more styles than I need on the editor.

**Comment by ahmadawais** [comment]
@aduth I am also sure that the editor's CSS interferes with the blocks' CSS. When trying to keep the visual appearance for the tweet block in a boilerplate I was not able to edit the tweet block if it had the same CSS as that of what I have at the front end. Also adding a placeholder made things weird.

![Check](http://g.recordit.co/D845lf7r10.gif)

The content area is displaced as compared to the placeholder.
![img](http://g.recordit.co/lsGwE7I1ew.gif)
I have removed all the cache!

**Comment by swissspidy** [comment]
Well, CSS is not limited to a component, it's _cascading style sheets_ after all. So it's certainly possible that some other CSS on the page affects your tweet block. That's why you have to possibility to enqueue styles for the back end only.

**Comment by ahmadawais** [comment]
True! But what I see in the GIFs above can be fixed in the future releases :)

**Comment by swissspidy** [comment]
@ahmadawais Would you mind creating a new issue / PR for making that CSS more robust?

**Comment by ahmadawais** [comment]
@swissspidy sure!
