### ISSUE TITLE
Babel Preset: Update @babel/preset-env to enabled optional chaining

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#18939]
Optional chaining reached stage 4!

![image](https://user-images.githubusercontent.com/699132/70235060-5c3da880-1762-11ea-8139-1b8c22d96411.png)

https://twitter.com/NicoloRibaudo/status/1202323456899067906

This means that... it should be soon enabled by default in `@babel/preset-env` and in `@babel/parser`.

There are two issues to track progress:
- https://github.com/babel/babel/issues/10809
- https://github.com/babel/babel/issues/10810

Once those two packages are updated and published to npm we should take an action and update `@wordpress/babel-preset-default` and all other packages using Babel to use the latest version of all Babel packages.

## Resources

- https://tc39.es/proposal-optional-chaining/
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
- https://2ality.com/2019/07/optional-chaining.html

**Comment by jsnajdr** [comment]
After the Babel update ships and we proceed to update Gutenberg, we'll need to add the `shippedProposals: true` option to the `preset-env` configuration. That tells the preset to include features that are not yet part of the published standard (that happens officially once a year), but are already approved (stage 4+) and are shipping in production browsers.

Babel will empty the list of shipped proposals once the standard is published and will enable these features by default. Then the list can grow again over the next year 🙂

**Comment by devdivdev** [comment]
Hey @jsnajdr we are supposed to add `opts.shippedProposals = true;
` to Babel Preset package right ?

**Comment by jsnajdr** [comment]
> we are supposed to add `opts.shippedProposals = true`; to Babel Preset package right ?

If the Babel update that adds optional chaining to `preset-env` makes it a part of the `shippedProposals` option, then yes, Gutenberg will need to enable that option in its Babel config.

**Comment by gziolo** [comment]
Babel 7.8 is out with the support for the feature:
https://babeljs.io/blog/2020/01/11/7.8.0
