### ISSUE TITLE
core image block breaks when transformed from core galley

### ISSUE THREAD

**Issue by mcguffin** [WordPress/gutenberg#18934]
**Describe the bug**
Block validation failed with image blocks that were transformed from a core gallery block.

**To reproduce**
1. Create a gallery
2. Transform to image
3. Save + Reload

**Screenshots**
<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/402988/70221086-edebec80-1747-11ea-8312-7dc38e17c12d.png">

The content retrieved from post body has an extra class `wp-image-<id>`.

**Additional context**
- WP 5.3, twenetytwenety theme, no plugins

**Comment by talldan** [comment]
@mcguffin I haven't been able to reproduce this, but it might be something that was fixed more recently. Is this something you're still experiencing?

**Comment by mcguffin** [comment]
@talldan Thanks for the reply! 
You are right. It's working in WP 5.3.2.
