### ISSUE TITLE
Exploring iterating the block library

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18940]
This issue is a start just like we did with the link interface to rethink what could be now we know more about the library. 

## Library drives
Let’s start at the beginning. Pressing the ‘+’ is motivated by a few different drives:

![image](https://user-images.githubusercontent.com/253067/70235556-16311680-175b-11ea-8c31-ba4b27f72e32.png)

**Search:** find what you want (typically based on knowing what want in the first place).

![image](https://user-images.githubusercontent.com/253067/70235598-247f3280-175b-11ea-8428-b51342159098.png)

**Browse:** find what you want (potentially not based on knowing what you want in the first place).

Browsing and searching both are very different motivated behaviours. If you think about pace, they also tend to have a different pace. Browsing is slower, ponderous and waiting for your eye to be caught. Searching is more rapid, the results are the driver.

There are several states you get to this point from, just a few could be:

- **Flow:** in the middle of creating and ‘just need something’.
- **Discovery:** curiously finding what could be there.

## Entering the library
There are 3 main ways you get into the library:

- / : whilst this is a shorter list it’s still the library
- ‘+’ : in between blocks.
- ‘+’ : in the toolbar, by block or fixed to the top of the editor.

![image](https://user-images.githubusercontent.com/253067/70235730-61e3c000-175b-11ea-93d9-6a2a9e1763e7.png)

Simplest of this is the /, this is the quickest, the easiest way to get to the library.

## Library elements

The clicking of the library is done with motivations. However, the library itself has to serve a growing variety of purposes and therefore elements needed:

- Search
- Browse
- Preview

![image](https://user-images.githubusercontent.com/253067/70235770-788a1700-175b-11ea-9c72-612fc3982e67.png)

The blocks are distilled to an icon and text. You need to know a rough idea about what the block does and then currently the preview gives you more information.

Our needs for the library are changing as the layout is being considered for example in #. This means it just being about blocks isn’t true anymore. Our library now has multiple media, books, videos, digital… like a physical library adapts we should consider that also.

## Sketching the library
I have been using the term library for this interface because for me that feels right. A collection of elements stored, able to be browsed, indexed and searchable. This brought me to sketching around how similar to a book our actual library is, could be.

![image](https://user-images.githubusercontent.com/253067/70235797-8dff4100-175b-11ea-9a6d-d3cf3c75a924.png)

Right now, the feel of browsing isn’t there. There is something tangible of flicking through libraries, books, the record store. Perhaps the experience could be adjusted to reflect this?

![image](https://user-images.githubusercontent.com/253067/70235820-98213f80-175b-11ea-93f8-221ef6e8a427.png)

## Library locations
Where you access the library is key both to motivation on what you need and I think how the interface could adapt.

If you view the screen as ‘hot corner’s for interactions, perhaps considering the following makes sense:

![image](https://user-images.githubusercontent.com/253067/70235853-a8d1b580-175b-11ea-98f6-8a0ebd4074d5.png)

- Top corner left: full library
- Top corner right: more menu
- Bottom corner: options?

## Taking into ideas
All of this is exploring in thoughts, how could this come into actual ideas? I would first say I would love to see sketches around this and exploring. Whilst there is other work that needs changes today, we can and should consider all aspects of the interface up for iteration and exploring. This is what I am doing here.

Today I noticed @jasmussen posting here: https://github.com/WordPress/gutenberg/issues/17335#issuecomment-562049752 and this brought me back to the ‘+’.

![image](https://user-images.githubusercontent.com/253067/70235889-c43cc080-175b-11ea-9198-d9bc404c9040.png)

If we take the new ideas from #18667 and explore what the search could look like:

![image](https://user-images.githubusercontent.com/253067/70235909-cc94fb80-175b-11ea-9cf6-35692a62e19e.png)

Perhaps, we take it a stage further and consider motivation, drive to reflect form and position.

- Top toolbar: library: you have time to browse.
- By block: simple search: you know what want and can rapidly add.

![image](https://user-images.githubusercontent.com/253067/70235956-dfa7cb80-175b-11ea-9e74-83d4e3d2ecfd.png)

![image](https://user-images.githubusercontent.com/253067/70235976-e9c9ca00-175b-11ea-8bf1-eac703a6c2ca.png)

As for the main library itself, I took the exploration @jasmussen did a little further and considered what a sliding panel could be.whilst an idea previously not needed, have we got to a place it now is? 
Do we need a larger interface?

![image](https://user-images.githubusercontent.com/253067/70235998-f64e2280-175b-11ea-96cd-5938c15faf2f.png)

## Where now?
The work going on to bring in things to the library doesn’t have to stop, this work can be done in parallel, I am suggesting exploring what-ifs and starting from a place of a blank sheet.

A starting place could be explorations and feedback on:

- What do we need where? For example in flow state does someone need the entire library?
- What other examples can we look to as we consider if our library of today should be the one we go forward with?
- How can the library elements be presented? What could our organising look like?
- How can the UI suggestions be brought into the library? This feels like a starting point as explored by @jasmussen, but shouldn’t be our endpoint.

Even if it’s a really out there sketch, now is a good time to explore. While there is a need to bring in things like patterns sooner over later, as noted, iterations can happen and thinking ‘what if’ collectively is always a good idea.

**Comment by mapk** [comment]
Just recording a quick thought: I do find it valuable to display the block's icon next to (or above) the block name in the Library. This helps make the relation to the icon in the block's toolbar which I appreciate.

**Comment by karmatosed** [comment]
With the G2 work and iterations on the library, let's close this for now.
