### ISSUE TITLE
Registering a block doesn't work when using the `@wordpress/blocks` package

### ISSUE THREAD

**Issue by eddysims** [WordPress/gutenberg#18949]
**Describe the bug**

Registering a block doesn't work when using the `@wordpress/blocks` package

**Additional context**

My block won't register when using `@wordpress/blocks`. The following block registers

```js
const { registerBlockType } = wp.blocks;

const blockStyle = {
	backgroundColor: '#900',
	color: '#fff',
	padding: '20px',
};

registerBlockType( 'gutenberg-examples/example-01-basic-esnext', {
	title: 'Example: Basic (esnext)',
	icon: 'universal-access-alt',
	category: 'layout',
	example: {},
	edit() {
		return <div style={ blockStyle }>Hello World, step 1 (from the editor).</div>;
	},
	save() {
		return <div style={ blockStyle }>Hello World, step 1 (from the frontend).</div>;
	},
} );
```

However changing to this, the block no longer registers

```js
import { registerBlockType } from '@wordpress/blocks';

const blockStyle = {
	backgroundColor: '#900',
	color: '#fff',
	padding: '20px',
};

registerBlockType( 'gutenberg-examples/example-01-basic-esnext', {
	title: 'Example: Basic (esnext)',
	icon: 'universal-access-alt',
	category: 'layout',
	example: {},
	edit() {
		return <div style={ blockStyle }>Hello World, step 1 (from the editor).</div>;
	},
	save() {
		return <div style={ blockStyle }>Hello World, step 1 (from the frontend).</div>;
	},
} );
```

**Comment by mcsf** [comment]
This depends highly on your local build setup. If you are using a custom webpack config, these are some possible causes:

1. `@wordpress/blocks` isn't defined as external.
2. `@wordpress/block` is defined as an external, but not set up as a dependency.
3. Unintended tree-shaking on `@wordpress/blocks` could lead to skipping [store initialisation](https://github.com/WordPress/gutenberg/blob/52d2a87db8b78344d89bfa7c6adb571d6c512769/packages/blocks/src/store/index.js#L13).

We might be able to help more if you're able to describe your build process and share any config.
