### ISSUE TITLE
Please provide a "porting" guide for plugin developers

### ISSUE THREAD

**Issue by dmccan** [WordPress/gutenberg#1894]
Gutenberg 0.4.0 - version as of this issue.

I have a plugin that adds editor buttons to TinyMCE that has a popup with inputs and provides shortcodes. I'm down to port this to Gutenberg blocks or whatever but would like a guide. I imagine there are a lot of people in the same boat as I am, who are ready to get with the program and have things ready for testing and launch.

Some information that would be useful for me is:

- A way to know that this page is being edited in Gutenberg so that I can switch behavior.

- A guide to creating a block to replace the TinyMCE button. My plugin provides a popup that gives a UI for entering the values that will go into the shortcode. It also does an AJAX type-ahead lookup based on the input. The shortcode is providing a wiki style link, so it goes in line with the paragraph content. I'm not sure if it should be a separate block or something else?

- Understanding if / how I can render the shortcode in the block to preview the content for a better experience. 

- Is there anything needed for permissions or is that handled on the page level?

- Are there any changes to revisions? 

- In general, a "best practices" and style guide would also be good. Also, if there are security best practices / nouces etc, then now is the time to beat them into our heads. 

Thanks!

**Comment by StephenAtty** [comment]
I am facing similar problems - I have a custom meta box which does Ajax lookups and inserts a short code at the current cursor location in the post - although the meta box is working without me doing anything (apart from changing 'advanced' to 'normal') the rest of it doesn't work for obvious reasons and I seem to be unable to find out how I'd do the equivalent in Gutenberg. I imagine there must be a lot of developers facing the same issue - as well as potentially learn React at the same time.

**Comment by danielbachhuber** [comment]
Related #4151

**Comment by mtias** [comment]
Closing this as there are/will be multiple docs for various integration points. Keep an eye on https://wordpress.org/gutenberg/handbook/extensibility/ and its sub-pages.

**Comment by danielbachhuber** [comment]
@dmccan @StephenAtty Just a heads up that I'm working on a [more specific migration guide](https://make.wordpress.org/core/2018/04/26/your-help-wanted-gutenberg-migration-guide/) and welcome your input.
