### ISSUE TITLE
Docs: Add "User Documentation" section that links to HelpHub

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#18952]
**Is your feature request related to a problem? Please describe.**
Based on some conversations, [including this recent one on Twitter](https://twitter.com/redcrew/status/1202655150495670272), folks looking to share Gutenberg user documentation often first look at the Gutenberg Handbook. Not a lot of people know that the user docs have been integrated into WordPress' default support docs.

**Describe the solution you'd like**
I think we should consider adding a section for "User Documentation" that links to a couple support articles, like:
- https://wordpress.org/support/article/wordpress-editor/
- https://wordpress.org/support/article/blocks/
- https://wordpress.org/support/article/adding-a-new-block/

I'm happy to write something up, I'd just need someone to do a PR — I don't understand how to add a new section to the docs.

**Comment by mkaz** [comment]
Here is the documentation for adding a new item to the documentation.
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/document.md

The `docs/toc.json` file is just the hierarchy of links, you can add a new section by adding it to the proper hierarchy level you want, and then add any additional files within. 

After adding the files, run `npm run docs:build` and it will generate a new manifest file that you should commit with the other files, or the integration test will fail. 

Let me know if you have any additional questions, feel free to ping on Slack, I try to keep up with Github notificaitons, but there are... a lot

**Comment by annezazu** [comment]
@melchoyce closing this issue out in light of the merged PR from @mkaz: https://github.com/WordPress/gutenberg/pull/19361 As noted, a link to the top-level page in the handbook was added but, any additional spots or ideas for adding more links to user docs are welcome 🥳Feel free to re-open this if that's the case.
