### ISSUE TITLE
Template add uncomplete div

### ISSUE THREAD

**Issue by albedo0** [WordPress/gutenberg#18974]
**Describe the bug**
When i try to had a paragraph in the template of my CPT i have an issue which add the following code : 
`<div style="display: none; position: absolute; width: 0px; height: 0px; margin-top: 0px;">`
which is a problem because it mask the rest of the page.

**To reproduce**
I wrote my template like that : 
```
'template' => array( 
    array('core/paragraph'),
    array('core/more')
),
```
Thanks for your help

**Comment by talldan** [comment]
@albedo0 I'm sorry, but I don't really understand what the following means:
> i have an issue which add the following code 
> `<div style="display: none; position: absolute; width: 0px; height: 0px; margin-top: 0px;">`
> which is a problem because it mask the rest of the page.

Would you be able to provide some more information?

**Comment by enriquesanchez** [comment]
Hey @albedo0! 👋

Are you still having this issue? If so, can you please provide more info?

**Comment by albedo0** [comment]
Sorry to not answer before ! 
The problem is solved now. I haven't change anything in the template description but no more div is added...

**Comment by enriquesanchez** [comment]
Thanks for clarifying @albedo0! I'll be closing this issue then.
