### ISSUE TITLE
Is it possible to remove/customise buttons at the bottom of Gallery block?

### ISSUE THREAD

**Issue by danielsequeira** [WordPress/gutenberg#18971]
Hi,

I'm trying to customise the Gallery block behaviour using `Block Filters` (https://developer.wordpress.org/block-editor/developers/filters/block-filters/). I would like to be able to create a gallery block without the "Upload" and "Media Library" buttons that show up at the bottom of the Gallery:

![Screenshot 2019-12-06 at 13 24 38](https://user-images.githubusercontent.com/12091319/70323109-3bda2080-182c-11ea-9d8b-5e5898dc57ec.png)

I tried to use `editor.BlockEdit` filter for this, but without success. Can you guys let me know if this is even possible?

Thank you very much for your time!

**Comment by richtabor** [comment]
> I would like to be able to create a gallery block without the "Upload" and "Media Library" buttons that show up at the bottom of the Gallery

I'm curious what the reasoning behind your goal here is? 🤔

**Comment by youknowriad** [comment]
Closing as stale
