### ISSUE TITLE
File Block: Add background/text color support

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#18989]
The File Block has an optional button, but you can't change the background or text colors of that button. This can present a problem if your site's background color conflicts with the default button color. For example:

![image](https://user-images.githubusercontent.com/2846578/70367583-55508c00-186f-11ea-9b0c-655f867691e1.png)

We should consider adding color support to this block.

**Comment by paaljoachim** [comment]
I am doing a status update.
The File block looks like this:

![Screen Shot 2021-01-18 at 21 37 17](https://user-images.githubusercontent.com/5323259/104960862-71f94600-59d5-11eb-8fe0-39fa60304f19.png)

It is still missing color controls.

Associated issue:
Consider adding color and text size customizations to all text-based blocks.
#8171

**Comment by paaljoachim** [comment]
Actually the File block is missing Color and Typography controls.
Both controls are needed. All blocks that handle text in some way are to have both of these controls in place.

**Comment by juanfra** [comment]
Hi @paaljoachim - I don't see any problem implementing the typography control. What I found is that the text of the filename is a link, how should we handle that regarding to colors? Also, there's a button as well, should that have separate controls for colors/typography?

**Comment by gwwar** [comment]
> Also, there's a button as well, should that have separate controls for colors/typography?

@juanfra if you'd be interested in working on this, it's probably easier to see what works better in a PR. We can also loop in Mel for design feedback.

**Comment by jasmussen** [comment]
Also happy to provide feedback here. Specifically on the question of colors, I would think global styles would eventually allow us to opt in to supporting link colors, so you'd have 3 color options — background, text, and links.

**Comment by paaljoachim** [comment]
Hey @juanfra Juan

Here is an example from the Heading block. Also the Paragraph block has Text, Background and Link colors.

![Screen Shot 2021-04-08 at 19 44 17](https://user-images.githubusercontent.com/5323259/114072847-f5bf2200-98a2-11eb-9a60-98765f0e2274.png)

Thank you Juan!

**Comment by carolinan** [comment]
For the color of the button in the file block please see 
https://github.com/WordPress/gutenberg/issues/52850
https://github.com/WordPress/gutenberg/issues/57314
