### ISSUE TITLE
Always show URLs if external in media replace menu

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#18992]
**Is your feature request related to a problem? Please describe.**
#16200 introduces a media replace menu which has the possibility to use URLs for media. These URLs can be external (e.g. an Unsplash picture) or internal (some image from the Media Library). However, there is a difference between the two:

- when the image is from the media library, the URL is less important. Also it is of a somewhat higher probability to want to change that image with another from the Media Library
- when the image is from an external URL then you should be made aware about this, instead of hunting the menu for that information, and it is also more likely to want to replace that image with another external image.

**Describe the solution you'd like**
When the current media's URL is external the URL viewer should be always open, un-collapsible via the Insert From URL menu item. When the current media's URL is internal the URL viewer should be collapsible and should hide when the menu is toggled.

Props @talldan for the idea.

**Comment by karmatosed** [comment]
I'd love to dig a bit more into why the URL is needed. From an end-user perspective it's 'an image' and where comes from likely won't matter as much. What is the usability reason for this idea, what problem does it solve?

**Comment by draganescu** [comment]
The URL is there because you have the option to insert media via URL, therefore, local media and remote media can be swapped only by URL.

**Comment by shaunandrews** [comment]
If I'm reading this right, you're suggesting that the URL should always be shown when the Replace button is clicked:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/191598/70471328-ec4d5c00-1a9a-11ea-9045-640dca4247ec.png">

If that's true, then I agree.

--

Its usually helpful to include visuals to help get everyone on the same page right from the get-go without the need for a back-and-forth comment thread.

**Comment by karmatosed** [comment]
Ah ha! Ok that makes sense I was confused it was going to show by the actual image. @draganescu is @shaunandrews correct?

**Comment by shaunandrews** [comment]
A few options for how this could work:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/191598/70536607-0a639c80-1b2d-11ea-8819-55e15d92a28e.png">

**Comment by draganescu** [comment]
yes @tammie that's what this is about. sorry for the confusion, I created this issue too quickly.

@shaunandrews I think the second option 

![second-option-insert-url](https://user-images.githubusercontent.com/107534/70537946-f722f200-1b69-11ea-8319-3621455540d9.jpg)

is best but, I don't see the reason for having the insert from URL option anymore?

![no-insert-url](https://user-images.githubusercontent.com/107534/70537959-fdb16980-1b69-11ea-9d1f-a654a0bba841.jpg)

**Comment by shaunandrews** [comment]
> is there a reason for having the insert from URL option anymore?

Really just consistency, I imagined that option would do the same thing as Change. I'm not sure I have a strong opinion on this based on the design — when/if we have something to actually use I'm sure I'll develop an opinion.

**Comment by karmatosed** [comment]
Removing design feedback as this now has a direction.
