### ISSUE TITLE
Simple Payments Block Disappears With Pagination

### ISSUE THREAD

**Issue by ChrissiePollock** [WordPress/gutenberg#18996]
**Describe the bug**

When a site has infinite scroll turned off and has posts with Simple Payment Blocks, the Simple Payment info is not shown on the older posts. I tested with Olsen and Twenty Sixteen.

**To reproduce**

1. Go to My Site>Manage>Settings>Writing and make sure Infinite Scroll is disabled. Also make sure settings are for full posts to show. 
2. Go to the post page and notice that you can see the Simple Payments option on posts
3. Scroll down to the bottom of the page and choose the Older Post option.
4. Notice that the first batch of posts still show the Simple Payments option but the next batch does not.

**Expected behavior**

All the posts should show the Simple Payment options.

**Screenshots**

See a screencast on https://d.pr/i/ttxAVW

**Desktop (please complete the following information):**
 - OS: Macbook Pro - 10.15.1
 - Browser Firefox version 71.0 and Chrome version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**

#2544423-zen -- Please check the notes on the issue for more details.

**Comment by Soean** [comment]
Hey @ChrissiePollock 
can you give more context about your WordPress installation? There is no infinite scroll option or Simple Payment block in WordPress. Have you installed some plugins or are you using a SaaS Hoster like WordPress.com?
Maybe you have to contact your Hoster or the plugin developer.

**Comment by ChrissiePollock** [comment]
Thanks, @Soean. This is on WordPress.com and the site has no plugins. I might have posted in the wrong spot. Moving to https://github.com/Automattic/wp-calypso/issues/38323.

**Comment by Soean** [comment]
Yes, then the issue should be on the calypso repo, so I am closing this issue here.
