### ISSUE TITLE
Focal point for image (portrait)

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19003]
**Is your feature request related to a problem? Please describe.**
When adding an image with the portrait of a person and then using a rounded mask style, 
sometimes the head is cropped off.

**Describe the solution you'd like**
Ideally one could just change the center of the image by using drag and drop (or touch).
The thumbnail with the new center should then be generated internally.

**Describe alternatives you've considered**
Alternatively, one would have to center/crop this in an image editing program like Photoshop.
The upside of using a focal feature in WordPress is that the original image is still preserved (that may still look great when not being in a circle frame) and the focal/center settings can be used by theme or plugin as metadata of that image.

**Comment by paaljoachim** [comment]
Hi @strarsis 

First of all I have to apologize as I see no one has commented on your issue.

Going through your suggestion using visuals.

Adding a portrait to an Image block (yes it's me..:). Then adding a rounded style.
![Screen Shot 2020-12-17 at 20 40 49](https://user-images.githubusercontent.com/5323259/102535273-461e3400-40a8-11eb-9e00-eab0b4c9bc5d.png)

There is no way for me to move the image around.

Adding the Cover block. Then the same image. Minimum height of the cover is 600.
Using the Focal Point Picker. Here I am able to move the image around.

![Cover-block-using-Focal-point-picker](https://user-images.githubusercontent.com/5323259/102536796-63ec9880-40aa-11eb-8824-0a1e8d6bcc6a.gif)

I would say adding the focal point picker to the Image block would be helpful.

@retrofox 
What do you think?

**Comment by mtias** [comment]
In https://github.com/WordPress/gutenberg/pull/28414 we added the ability to go from an image block to a cover block more seamlessly. The new crop tools on the image can also be used to set the focus directly. I think those two paths address the main issue here, so going to close this one.
