### ISSUE TITLE
Media Text Block CSS is-image-fill applied to all children

### ISSUE THREAD

**Issue by castles** [WordPress/gutenberg#19009]
**Describe the bug**
When adding an image to the content of the media and text block that has image-fill applied then it inherits the main media block styles. 

**To reproduce**
1. Create media Text Block
2. Add an image
3. Add an image to the content of the media text block
4. Under Media & text settings turn on "Crop image to fill entire column"

To fix this change this:
```
.wp-block-media-text.is-image-fill figure {
  height: 100%;
  min-height: 250px;
  background-size: cover; }

.wp-block-media-text.is-image-fill figure > img {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0; }

```

to this:

```
.wp-block-media-text.is-image-fill > figure {
  height: 100%;
  min-height: 250px;
  background-size: cover; }

.wp-block-media-text.is-image-fill > figure > img {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0; }
```

in wp-includes/css/dist/block-library/style.css

**Comment by talldan** [comment]
@castles Thanks for the report. As far as I could tell this doesn't seem to be an issue any longer. It looks like class names are now used on the selectors now:
```
.wp-block-media-text.is-image-fill figure.wp-block-media-text__media {
	height: 100%;
	min-height: 250px;
	background-size: cover;
}
```

As such, I'll close the issue.
