### ISSUE TITLE
Consider hover indictation radius in toolbar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19018]
The hover on the toolbar has a radius:

![image](https://user-images.githubusercontent.com/253067/70450818-4995dd00-1a9c-11ea-80b4-c729f301beb1.png)

You can see it clearly here:

![image](https://user-images.githubusercontent.com/253067/70450891-66caab80-1a9c-11ea-8940-4d9232637aac.png)

If the border-radius is removed it looks like this, which feels more fitting for now:

![image](https://user-images.githubusercontent.com/253067/70450982-8661d400-1a9c-11ea-909d-326aee745f96.png)

It's worth noting this uses a shadow to get hover effect and seems related to a component, so a PR might need some deeper digging.

**Comment by shaunandrews** [comment]
I don't think removing the border-radius is the right solution. That radius is applied to all buttons and icon-buttons throughout the editor, including in the top toolbar. I think the better solution might be to add 2px of space around the icon-buttons in the toolbar, bumping up the size of the toolbar to 40px.

Here's the current (36px) space, vs the proposed (40px) space:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/191598/70552340-2a07be80-1b47-11ea-9a96-78cfa6a0ed4c.png">

**Comment by phpbits** [comment]
> I don't think removing the border-radius is the right solution. That radius is applied to all buttons and icon-buttons throughout the editor, including in the top toolbar. I think the better solution might be to add 2px of space around the icon-buttons in the toolbar, bumping up the size of the toolbar to 40px.

+1, adding margin will make it look better. Here's what I'm using on EditorsKit plugin for toolbar button with text content :

![Consider hover indictation radius in toolbar](https://user-images.githubusercontent.com/3365507/70552540-87862480-1bb4-11ea-8264-55c83512a8e3.gif)

**Comment by karmatosed** [comment]
Marking as good first issue as making a PR to add margin could be a good starting place.

**Comment by Addison-Stavlo** [comment]
I have opened a PR as noted above that does what @shaunandrews suggested.

I have a question there (with screenshots) regarding weather or not we also want this margin on the block-mover part of the toolbar.
