### ISSUE TITLE
How to customize URL popover 'Open in new tab" to be checked by default

### ISSUE THREAD

**Issue by bpshadow** [WordPress/gutenberg#19015]
![image](https://user-images.githubusercontent.com/44585096/70444952-ba230680-1a68-11ea-8ad9-1666466af808.png)

Open in New Tab is unchecked by default in Wordpress block editor.
Is there any way I can customize this in my theme or plugin to be true by default using any hook or javascript?
Thanks

**Comment by paaljoachim** [comment]
Hey @bpshadow 

Here is a very late response!
Thank you for your question!

I will ping a few folks regarding this issue.
@WordPress/gutenberg-core

**Comment by youknowriad** [comment]
Thanks for the issue.

There's no way to change that aside  replacing the "link" format entirely. I don't think  adding a filter or something for this very specific use-case is a good thing. So I'm just closing this for now.
