### ISSUE TITLE
Only show image resizers when image is selected

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19017]
I noticed the image selectors are there as I select a block:

![image](https://user-images.githubusercontent.com/253067/70450373-83b2af00-1a9b-11ea-86af-d8d9fb8c1d76.png)

It might be better to show these on interacting with the image. I understand why they show as it does give indication you can resize, but I am not sure they need to be on by default click.

**Comment by shaunandrews** [comment]
I don't understand the problem you've outlined, and would be in favor of closing this issue.

**Comment by ibdz** [comment]
I think it's related to the interaction of the selected image block, the Image Settings and Crop Settings have interaction for Image Dimensions.

This issue will be solved if:
- The block's border has a new solution (for example, less dominant)
- Separate the interaction for image block and the image itself.
- reduce the resize indication to be like disable state.

**Comment by karmatosed** [comment]
It is @ibdz. If you select the block then the dot resizers show on an image block. The question is should they show even when you aren't selecting the image?

I think in light of feedback on this the feeling is yes so lets close.
