### ISSUE TITLE
Large gap displayed to left of editor at browser widths of 782px and 960px.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#19011]
**Describe the bug**
A large gap is displayed down the side of the editor at particular viewport widths (960px and 782px).

I have a feeling this bug has been around for a long time. It's pretty hard to spot, and I only noticed it when watching the end-to-end tests, which run at 960px. It's also more obvious with the background color that Twenty Twenty uses.

When the admin menu collapses at 960px and 782px, the Gutenberg layout only adjusts at 959px and 781px. 

The issue seems to be happening because WordPress admin uses desktop first (max-width) media query breakpoints, while Gutenberg uses mobile first (min-width), so the media queries take effect at different widths.

**To reproduce**
1. Set the browser window width to 960px or 782px.
2. Observe that the editor has a white gap down the side. 

**Expected behavior**
No gap is present.

**Screenshots**
<img width="791" alt="Screen Shot 2019-12-09 at 4 44 12 pm" src="https://user-images.githubusercontent.com/677833/70420675-31758c00-1aa3-11ea-96cd-9eeffe01b9a4.png">

<img width="977" alt="Screen Shot 2019-12-09 at 4 44 26 pm" src="https://user-images.githubusercontent.com/677833/70420678-33d7e600-1aa3-11ea-8fe9-0f7457f0339a.png">

**Comment by talldan** [comment]
An easy fix is to change the breakpoints to 783px and 961px in Gutenberg, not sure if that's something we'd consider though.

The other, probably better option is to rely on browser layout rather than setting a specific `left` value on the `.edit-post-layout`.

**Comment by youknowriad** [comment]
we have an `editor-left` mixin to assign the right "left" value. The problem is that there's so many use-cases/variations in Core and we're probably missing one (sidebar open, closed, auto-folded, responsive...)

**Comment by jorgefilipecosta** [comment]
The problem for 960px was solved we should apply a similar fix to https://github.com/WordPress/gutenberg/commit/5945e48bc03a5654a900fec4b60dce7ec0333a03 to fix the 782 breakpoint.
