### ISSUE TITLE
Use less underlines in navigation block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19025]
There are quite a few underlines in the navigation block, what could be done to make it less visually complex?

![image](https://user-images.githubusercontent.com/253067/70472270-bc1bb280-1ac6-11ea-9355-5e2f74d3ac3c.png)

**Comment by shaunandrews** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/191598/70472335-eb1d2e80-1a9c-11ea-8404-b2aa24bad4f2.png">

I'm not sure why we're using a border-bottom rather than text-underline for these links.

**Comment by getdave** [comment]
> I'm not sure why we're using a border-bottom rather than text-underline for these links.

Guessing, but probably because you can't control the distance between text and underline if you use `text-decoration: underline`.

**Comment by apeatling** [comment]
Let's switch to underline, after which the design changes coming through in https://github.com/WordPress/gutenberg/issues/18310 will help with this.
