### ISSUE TITLE
Sourcemaps not working in Safari

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#19057]
**Describe the bug**
Sourcemaps for JS (and possibly also CSS) are not working in Safari

**To reproduce**
1. Using a local dev environment, run `npm run dev`.
2. Open up Safari and start a new post on your local env
3. Open up the dev tools and try to browse to a JavaScript file
4. Observe that only the `index.js` file for each package can be browsed to, and only compiled code can be viewed.

**Expected behavior**
Sourcemaps should work, allowing developers to view and debug using uncompiled code.

**Screenshots**
It looks like the sourcemaps should appear in this folder for each package, but the folder is empty:
![Screen Shot 2019-12-10 at 12 28 54 pm](https://user-images.githubusercontent.com/677833/70588423-a530a980-1c07-11ea-9b51-e580715c877b.png)

**Comment by Mamaduka** [comment]
@talldan, I can no longer reproduce the issue on Safari 15.5.

## Screenshot
![CleanShot 2022-08-02 at 18 16 37](https://user-images.githubusercontent.com/240569/182397030-1a4eafc1-636b-4dad-9a3d-bef1803a92b8.png)
