### ISSUE TITLE
Submitting a link in the navigation block using the enter key causes a console warning.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#19056]
**Describe the bug**
Submitting a navigation link causes the warning 'Form submission canceled because the form is not connected' to appear in the console.

**To reproduce**
1. Add a navigation block
2. Choose the 'Create empty' option on the placeholder
3. Type in a URL and use the 'Enter' key to submit it.
4. See error in the console

**Expected behavior**
The console error does not occur.

**Comment by aduth** [comment]
This is pretty disruptive for Travis builds. Should we revert #18933 in the interim?

**Comment by apeatling** [comment]
@talldan Are you still looking at this one?

**Comment by talldan** [comment]
@aduth This PR resolved the issue for e2e tests for the moment:
https://github.com/WordPress/gutenberg/pull/19189/files#diff-b0caeafd8d509b35dbb33e19934e991bR138-R143

@apeatling yep, should have a PR up soon. I'll remove the above workaround for e2e tests in that PR.
