### ISSUE TITLE
Grouping certain blocks pushes content out of bounds of background color

### ISSUE THREAD

**Issue by CompChris** [WordPress/gutenberg#19052]
**Describe the bug**
On non-Gutenberg first themes, if a Media & Text block is used inside of a **group** with a color, and is set to "Wide Width," it overflows outside of the background color.

**To reproduce**
1. Activate a theme like Radcliffe 2 or Dyad 2.
1. Create a new page.
2. Add a new Media & Text block.
3. Add an image on the left and text on the right.
4. Add a paragraph block below that. Add some text.
5. Highlight both blocks, and make them into a group.
6. Select the group, and add a Background color.
7. Make the alignment on the Media & Text block "Wide Width."
8. Save

**Expected behavior**
The content should not go outside of the background color for the group.

**Screenshots**
![Screen Shot on 2019-12-10 at 16:03:46](https://user-images.githubusercontent.com/6847710/70568829-a9f15100-1b66-11ea-8fef-aa8b3d3c24ce.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version 78.0.3904.108

**Additional context**
- Gutenberg 7.0.0

**Comment by talldan** [comment]
@CompChris Thanks for creating the issue, but this seems like something that should be taken up with Automattic support.

Anyway, I went to the lengths of installing the theme, and it looks like you just need to set the group block's alignment to wide and unset the cover block alignment.

Given the above two points, I'll close the issue.
