### ISSUE TITLE
Hover States: Hover states inconsistently appear

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#19051]
Today I noticed that I haven't been seeing hover states for blocks. Here's a GIF to hopefully explain what I'm seeing:

![wut the wut](https://user-images.githubusercontent.com/191598/70561164-f6816000-1b57-11ea-8a72-a00177a7786d.gif)

This is in Safari. When I first load the editor and start moving my mouse around, I don't see hover states on blocks. I _do_ see the in-between inserter and the hover state for the post/page title. If I start to click around a little, then at some point the hover states start to work right.

**Comment by karmatosed** [comment]
I also see intermittent issues on master using Chome. For example, I can get in-between blocks adding to show but not labels.

**Comment by karmatosed** [comment]
@youknowriad just let me know the PR for removing hovers has been merged which explains my weird intermittent issue. Thanks for the context.

I will add it's a little weird to see 'adding' in between now flash up.

I tried to test on Safari and Chrome and only can get that to show up.
