### ISSUE TITLE
The demo templates were not included in the last release zip

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#19066]
This file is missing `/lib/demo-block-templates/index.html`
It's probably related to the build-zip script.
We should consider a `7.1.1` once we fix that.

cc @epiqueras

**Comment by aduth** [comment]
> It's probably related to the build-zip script.

Specifically, the ZIP includes only whitelisted files:

https://github.com/WordPress/gutenberg/blob/f31ae1cc6c678c5cc7bb54a4c7be6c342b10439a/bin/build-plugin-zip.sh#L112-L125

If there are new files to be included, a corresponding pattern should be expected in the parameters of this command.

**Comment by epiqueras** [comment]
Thanks @aduth, I opened a PR: #19072.
