### ISSUE TITLE
Welcome Guide: improve method for assessing whether a user is "new"

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#19079]
From https://github.com/WordPress/gutenberg/pull/18041#issuecomment-562661218:

>[...] the method for assessing whether a user is "new" to Gutenberg is significantly flawed: the usage of local storage for this means that a user will be new on every device they use, on every browser they use, and on every new site they launch. Secondarily, because the detection appears to be based on the positive presence of 'modal dismissed' setting in local storage, it will essentially be impossible to permanently disable it; anytime the local storage is flushed it will come back. (See #15105)

**Comment by noisysocks** [comment]
Since the welcome guide setting is stored using the persistence plugin, addressing #15105 will in turn address this.
