### ISSUE TITLE
[Feature Request] Optionally don't expand "Most Used" accordion item

### ISSUE THREAD

**Issue by lonix1** [WordPress/gutenberg#19070]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a frustration.

In the block editor, when clicking to add a new block, the popup shows an accordion with the first item expanded ("Most Used"). It gets in the way - I almost always end up choosing something from another group. So it just adds friction... it's a small nuisance but I've stumbled over it a hundred times.

**Describe the solution you'd like**
An option to open the popup with all accordion items collapsed.

**Describe alternatives you've considered**
userscripts

**Comment by lonix1** [comment]
Same thing for the block editor (on the right hand side, after clicking a block). I it automatically opens the first accordion item.

**Comment by jeathree** [comment]
Yes, the "Most Used" category is super annoying, I don't see any reason for it.  The blocks in each category already appear to organize themselves based on the recently used.

I hide the Most Used category with CSS BUT then realized the search results show up in there.  So I guess there really isn't a way for us to hide it.

**Comment by clarkewd** [comment]
I'm in favor of making the "Most Used" group optional

**Comment by virgo79** [comment]
+1 for me too. I've also hidden the Most Used tab with css.

Also, I would like to raise a doubt about the mechanism of "show on top the most recent used blocks". I think this feature should be also considered to became an "optional" feature. 

When a user search for a block the first time, he expect to find that block in the same position. 
Changing the blocks order could give a feeling of confusion and impermanence.

Maybe someone could consider very useful to see the most recent used block on top of every category, but I don't think could be considered comfortable for all.
Why not make this feature optional.

**Comment by youknowriad** [comment]
We added an option to disable this panel. This is solved now.

**Comment by brisa-pedronetto** [comment]
@youknowriad Hey Riad, would you mind pointing out to the documentation page where this information is? I can't sem to find it 🤔  Thanks!

**Comment by youknowriad** [comment]
I'm not sure there's a documentation page about this but you can see the option here: (second checkbox of the options modal)

<img width="448" alt="Capture d’écran 2020-07-29 à 10 33 06 AM" src="https://user-images.githubusercontent.com/272444/88783659-f7b6da00-d186-11ea-9bfe-77ce806c5a7c.png">

**Comment by brisa-pedronetto** [comment]
Thanks for the answer! That's funny, I'm using Wordpress 5.4.2 this is what shows in the Options panel. Any ideas?

![image](https://user-images.githubusercontent.com/13985387/88794205-9fcfa180-d18d-11ea-9175-522fda4aa79b.png)

**Comment by youknowriad** [comment]
@brisa-pedronetto yes, this is coming in WordPress 5.5 (next week). You can also install the Gutenberg plugin if you want to get features early but know that the Gutenberg plugin is considered as the "alpha" version of the next WordPress block editor.

**Comment by brisa-pedronetto** [comment]
Super! Thanks again for your support 👍
