### ISSUE TITLE
Verse block new lines are not rendered

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#19083]
**Describe the bug**
When saving a verse, using the verse block the new lines are stripped out, all verses are on one line (tested in firefox)

**To reproduce**
1. Edit a post and add a verse block
2. Enter a verse with new lines in it
2. Click on Publish

**Expected behavior**
New lines are preserved as intended

** Actual Behavior**
New lines are removed, all content is on one line

**Screenshots**
Before publishing
![Selection_028](https://user-images.githubusercontent.com/22446385/70674509-16955880-1ceb-11ea-863d-d2d95c2babae.png)

After publishing:
![Selection_029](https://user-images.githubusercontent.com/22446385/70674511-18f7b280-1ceb-11ea-84cc-bfd10f27a109.png)

Example
https://erutest123.blog/2019/12/12/verse-test/

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 71

**Comment by katinthehatsite** [comment]
Also reported in 2559066-zen

**Comment by formosattic** [comment]
+1 in 17339857-hc

The new lines aren't kept when converting from a **Verse** to **Paragraph** block.

**Comment by goblinartificer** [comment]
Also in 2562683-zd

**Comment by rickmgithub** [comment]
Also in 2564769-zd

**Comment by sophiegyo** [comment]
It doesn't look like this is fixed - I'm still seeing the same issue.
Screenshot: https://d.pr/i/qzTp2m

Checked in two browsers:
Chrome 79.0.3945.88
Firefox 71.0

**Comment by rickmgithub** [comment]
Hi. 

Looks like this one is back.

2625003-zd

I can also replicate it on a test site too.

So the verse block is showing the content in one line.

**Comment by youknowriad** [comment]
@rickmgithub which Gutenberg version are you using?

**Comment by WunderBart** [comment]
Looks good in [Gutenberg v7.3.0](https://github.com/WordPress/gutenberg/tree/v7.3.0)

![image](https://user-images.githubusercontent.com/1451471/75180715-0fec7e00-573d-11ea-8fe5-040b126d5adf.png)
