### ISSUE TITLE
Add Google reCAPTCHA to contact form

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#19085]
_As a user, I want to be able to add a Google reCAPTCHA field to my contact form so that my cont form is protected from bots._

---

**Is your feature request related to a problem? Please describe.**

The current contact form does not contain any spam protection. As a result of that, bots can spam the default contact form.

**Describe the solution you'd like**

Adding a Google reCAPTCHA element to the existing form elements to allow users to add Google reCAPTCHA to their contact forms.

**Describe alternatives you've considered**

n/a

**Comment by Soean** [comment]
WordPress Core doesn't have a contact form, maybe its a calypso issue?

**Comment by nielslange** [comment]
@Soean I'm not aware of a contact form in core, are you? I'm only aware of the contact form block in Gutenberg and the contact form shortcode in Jetpack, besides all other form plugins such as Contact Form 7, Ninja Forms, etc. of course.

**Comment by Soean** [comment]
@nielslange There is no contact form in Gutenberg, only in Jetpack: https://github.com/Automattic/jetpack/tree/master/extensions/blocks/contact-form
