### ISSUE TITLE
Multi-Select: Selection not always clearing

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#19087]
When you click outside blocks to deselect, the new native multiselect doesn't always clear. That is — `is-multi-selected` is always properly cleared, but the selection marker isn't.

- It appears most of the time that if you start and end the selection in a paragraph, selection does clear when clicking outside.
- The issue seems to be easiest to reproduce when starting selection in text, then stopping in a non-paragraph block such as Image.

However the above isn't completely consistent. GIF:

![selection not clearing](https://user-images.githubusercontent.com/1204802/70691114-9950f000-1cb8-11ea-9f90-af2f4decd205.gif)

@ellatrix do you have any idea what might cause this?

**Comment by ellatrix** [comment]
@jasmussen Which browser is this? I have a tried in both Chrome and Firefox and cannot reproduce.

**Comment by jasmussen** [comment]
Chrome, Mac. I'll try and repro in Firefox.

**Comment by jasmussen** [comment]
I'm seeing some additional issues, and I'm starting to suspect it may be editor style related. The following issues are both in twentytwenty, probably in others but haven't tested that.

Issue 1: can't click left or right of the block to clear multi selection:

![multi select 1](https://user-images.githubusercontent.com/1204802/72803464-736f2180-3c4e-11ea-90da-5f991bd1986f.gif)

I can click on a single block to select that, which clears the multi select. But there doesn't appear to be any other way to do so.

I know we've removed a lot of divs from the editing canvas lately, is it possible we removed one of the divs holding the click trigger to clear the block selection?

Issue 2: if I drag outside the bottom of the canvas, into the invisible appender, the multi selection is cleared instantly:

![multi select 2](https://user-images.githubusercontent.com/1204802/72803493-884bb500-3c4e-11ea-9d47-be0edff82dd8.gif)

**Comment by ellatrix** [comment]
@jasmussen No, we didn't remove hat div. :) It's likely to be #19762, there's a new focusable container which now seems to be capturing the focus instead of the element clearing the selection. This is not part of the 7.3 release. I'll look into a fix, and I'll also look into the other issues.

**Comment by ellatrix** [comment]
It doesn't look like there was an e2e test for this behaviour, so I'll add that too.

**Comment by jasmussen** [comment]
This issue appears to have been fixed!
