### ISSUE TITLE
Welcome guide: Modal unnecessarily changes size on large viewports

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#19093]
**Describe the bug**
On large viewports, the welcome guide modal's width will change with each step causing the _Previous_ and _Next_ buttons to move around.

**To reproduce**
1. Resize your viewport to something huge e.g. 2268x768. (I used DevTools to do this artificially.)
2. Open the welcome guide 
3. Click _Next_

**Expected behavior**
The modal's width should not change and the _Next_ button should be in the same place.

**Screenshots**
![welcome-guide-max-size](https://user-images.githubusercontent.com/612155/70699482-81359c80-1cc9-11ea-8b9b-cf1128236b29.gif)

**Fix**
We likely need to add a `max-width` to `WelcomeGuideModal`.

**Comment by draganescu** [comment]
This doesn't seem to happen in Firefox 71 ...

**Comment by draganescu** [comment]
I can't reproduce in Chrome either. @noisysocks 

Does this still happen to you?

**Comment by noisysocks** [comment]
Yep, seems OK now!
