### ISSUE TITLE
Paragraph Block bug with Font Size class

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#19107]
**Describe the bug**
Changing font size should add specific font size classes but `has-custom-font-size` is not available.

**To reproduce**
Here's a GIF on how to reproduce.

![Paragraph Block bug with Font Size class](https://user-images.githubusercontent.com/3365507/70737643-f9de3c80-1d4d-11ea-807d-8b44cfc589af.gif)

**Expected behavior**
`has-custom-font-size` should be use.

**Comment by shitalmarakana** [comment]
i am working on this

**Comment by talldan** [comment]
@phpbits Could you provide more of an explanation on why this is a bug? Was this class name previously provided by the paragraph block?

**Comment by phpbits** [comment]
@talldan `has-custom-font-size` is not being applied on the element. On the GIF above, it's only applying the classname for small, large and larger.

**Comment by talldan** [comment]
@phpbits But why is that a bug?

**Comment by enriquesanchez** [comment]
Hey @phpbits! 

I tested this and while `has-custom-font-size` is not being added, any `has-X-font-size` class gets removed as soon as you enter a custom font size.

I'm not sure this is a bug, but please feel free to reopen the issue if I'm missing something.
