### ISSUE TITLE
Stuck scrolling the content

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#19101]
**Describe the bug**

Since a while, I always get stuck scrolling the content area. I have no idea why it happens.

**To reproduce**
1. Open the editor
2. Scroll the content area a little bit up and down until it gets stuck.

**Expected behavior**

I expect to keep on scrolling.

**Screenshots**

![scroll](https://user-images.githubusercontent.com/4710635/70714447-776f6180-1ce8-11ea-9c7b-781a52c107d7.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**
Gutenberg `master`.

**Comment by ItsJonQ** [comment]
Oh boy! I've experienced this too. It's also random...
I wasn't able to really pinpoint it... other than when my mouse randomly goes over an image (similar to your GIF)

**Comment by ellatrix** [comment]
It doesn't seem limited to scrolling over an image. It also happens when I scroll over text.

**Comment by youknowriad** [comment]
It seems related to this #19682

**Comment by ellatrix** [comment]
I'm not sure that it is... I'm not clicking in a list at all.

**Comment by ellatrix** [comment]
I haven't noticed this problem in ages. Feel free to reopen if it comes back.
