### ISSUE TITLE
Can i add block templates in plugin ??

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#19116]
As you may know, blocks are plugin territory and cannot be put in themes. I want to give the block templates in the plugin.

Users will download the theme and the theme will have a companion plugin. In that plugin, all the block templates and custom blocks will be given and users can use the full site editing features.

Is that possible in the current scenario?

**Comment by talldan** [comment]
@ravishakya As far as I know, it's fine to recommend a plugin when your theme is installed. I've seen other themes and plugins do this. Worth checking the guidelines to see what's possible:
https://make.wordpress.org/themes/handbook/review/required/#plugins

This repository is for the development of Gutenberg, so this isn't the right place to answer your question fully. I'd recommend asking on the WordPress.org forums or the WordPress stack exchange. A quick google showed this has been asked a few times already.
