### ISSUE TITLE
Font select UI doesn't grow to fit depending on theme

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19130]
If you use Twenty Nineteen and select font sizes you get the following:

![1](https://user-images.githubusercontent.com/253067/70818690-3cdef500-1dcc-11ea-9871-3bd96c495a90.png)

I actually get this on Twenty Twenty also but that could be my end:

![image](https://user-images.githubusercontent.com/253067/70818720-5122f200-1dcc-11ea-9483-08621ca85aae.png)

**Comment by youknowriad** [comment]
Closed by #19130
