### ISSUE TITLE
Change icon of verse block

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1913]
## Issue Overview

#1809 added a new block for adding verses. Surprisingly, it uses a carrot as an icon. It was mentioned in the comments on the PR that choosing this icon was a bit unusual. For me, it was really surprising to see such an icon because it has nothing to do with the type of block. Even a pencil icon would have been better.

It was mentioned that a new quill dashicon could be created for that block. That would definitely preferable.

So consider this a tracking issue for changing the icon for the verse block, just as mentioned on #1809. Just so it doesn't get lost.

**Comment by HardeepAsrani** [comment]
I've added #1915.

In this PR, I've replaced Carrot with a Pencil icon(Edit: https://developer.wordpress.org/resource/dashicons/#edit).

If we come up with a Quill in Dashicons then that's great, but testing and seeing a carrot made me little mad so found the best possible icon in the current pack.

Also, Alignment icons look good for a Verse: https://developer.wordpress.org/resource/dashicons/#editor-aligncenter

Thoughts?

**Comment by melchoyce** [comment]
cc @field2 ^

**Comment by hedgefield** [comment]
Good suggestion. I was confounded by the carrot also.

**Comment by HardeepAsrani** [comment]
Painted a picture of Bugs Bunny writing a verse with a carrot in a Looney Tunes. 🥕

**Comment by field2** [comment]
Should we design a new quill icon or use the pencil?

**Comment by hedgefield** [comment]
I personally like the pencil, though I don't/wouldn't use this block, so maybe the people who do have a different connotation with it.

On a side note, Yoast SEO uses a quill icon for its readability analysis score, so if a quill is preferred here, should make sure it doesn't look similar, or it could become confusing.

**Comment by StaggerLeee** [comment]
Your "Verse" break container at the right and text goes outside.

Who ads verses to a website ? I dont get it.

**Comment by karmatosed** [comment]
The icon is now a pencil, for now lets close.. although I do love the idea of a quill :)
