### ISSUE TITLE
Disable autoscroll on block selection?

### ISSUE THREAD

**Issue by electricric** [WordPress/gutenberg#19137]
Hello folks, 

i just upgraded the Gutenberg plugin from 6.2 to 7.1 and now the editor automatically scrolls to the bottom of a block the second i select it (by clicking on it or using the block navigation toolbar). I read that you included the "dom-scroll-into-view" module into Gutenberg, so this might be the cause for this behaviour.

This is a nice feature for small blocks, but i have a large container-block in my plugin, so the editor scrolls to the bottom of the whole page once i click on it to make a change in one of its inner blocks.

I spend some time to find an option or dispatch method to disable the autoscroll-on-select behaviour,  or at least to define some kind of offset for my blocks so the page jumps to the top of the block instead of the bottom. Needless to say i didn't find any solution. 

Did i overlook something or is this not possible at the moment?

**Comment by youknowriad** [comment]
This looks like the same issue raised in #19682 

Closing as duplicate.
