### ISSUE TITLE
Shortcode block: No visual indicator when highlighting text, ::selection is transparent 

### ISSUE THREAD

**Issue by JoshuaGoode** [WordPress/gutenberg#19139]
**Describe the bug**
Highlighting and selecting text within a shortcode block has no visual indicator.  

Upon inspection, ::selection is set to transparent and the following CSS is applying to the input.

```
.block-editor-block-list__layout .components-placeholder ::selection {
    background: transparent;
}
```
This only occurs when the Gutenberg plugin is active and does not appear to be an issue in core.

**To reproduce**
1.  Activate the Gutenberg plugin. (Currently 7.1.0 at the time of testing).
2.  Add a Shortcode block within a post/page
3. Add text to within the block and attempt to highlight the text. 

**Expected behavior**
A visual indicator for highlighted text. For ::selection to have a color. 

**Visual Demonstration**
![Screen Capture on 2019-12-13 at 17-03-16](https://user-images.githubusercontent.com/4887830/70835283-90e8da00-1dca-11ea-9143-2832df6ae02e.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: Chrome 
 - Version: 79.0.3945.79

 - Reproduced on multiple browsers and devices.
--

**Additional context**
- WordPress version 5.3.1
- Gutenberg plugin version 7.1.0

**Comment by Soean** [comment]
I tested the issue in the current master in chrome on macOS and I can't reproduce the issue. I also can't finde the CSS on GitHub

**Comment by JoshuaGoode** [comment]
@Soean The CSS that is applying here seems to be from https://github.com/WordPress/gutenberg/blob/c73b6b7c07421e9015434ce0b2f61ca1fe900041/packages/block-editor/src/components/block-list/style.scss#L183

I was able to reproduce it again today and am getting numerous user reports. This requires that the Gutenberg plugin be activated and doesn't occur in the Gutenberg integration in WordPress core.

**Comment by skorasaurus** [comment]
I'm unable to reproduce on a vanilla site using WordPress 5.4.0, with the gutenberg plugin disabled (relying on the built-in one) even though the code hasn't changed. 

![image](https://user-images.githubusercontent.com/955351/79152249-db3e8f80-7d99-11ea-9eca-b9648563d91f.png)

**Comment by JoshuaGoode** [comment]
@skorasaurus Thanks for testing.

I'm specifically seeing this when the plugin is activated, though. 

I'll need to run a test to see if it's still lingering around but the steps to reproduce include activating the Gutenberg standalone plugin. 

> This requires that the Gutenberg plugin be activated and doesn't occur in the Gutenberg integration in WordPress core.

**Comment by youknowriad** [comment]
Just tested this again and I'm not able to reproduce with or without the plugin.
