### ISSUE TITLE
Keyboard Block Inserter search sometimes doesn't work in IE11

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#19142]
**Describe the bug**
Sometimes an error is thrown when typing `/` into the block editor to initiate a block insertion using the keyboard with IE11 

<img width="552" alt="Screen Shot 2019-12-13 at 2 43 26 PM" src="https://user-images.githubusercontent.com/1270189/70837375-5118f700-1db8-11ea-8821-97c7499d3bad.png">
<img width="897" alt="Screen Shot 2019-12-13 at 2 42 59 PM" src="https://user-images.githubusercontent.com/1270189/70837378-55451480-1db8-11ea-9500-33b4d710e48f.png">

Should be fixed by the added guard in https://github.com/WordPress/gutenberg/pull/14815 though the PR did not make it into the 7.1.0 release

**To reproduce**
1. Load Gutenberg in IE11
2. Type `/` and some letters
3. JS error is thrown, block inserter does not appear

**Expected behavior**
Block search results should display 

**Additional context**
- IE11, Gutenberg plugin 7.1.0

**Comment by paaljoachim** [comment]
Hey @gwwar Kerry

Is this issue still valid?

**Comment by gwwar** [comment]
Forgot to close this one out
