### ISSUE TITLE
Overview: Block-based Demo Theme

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#19143]
Since #18554, we've had a way of shipping demo block templates for the full site editing experiment in the Gutenberg plugin. It'd be nice if we shipped a block-based version of TwentyTwenty in there, that we could then package into a standalone theme as an example implementation for block based themes. It will also be very nice to work with in [the new site editor](https://github.com/WordPress/gutenberg/pull/19141).

Let's keep track of needed work here:

- [ ] Index/archive template. (PR)
  - They are shared so I guess the archive block will just not output anything if `get_the_archive_title` is not set.
  - [ ] Header template part. (PR)
    - [ ] Site description block. (PR)
  - [ ] Archive block. (PR)
    - Should wrap posts block.
  - [ ] Posts block with pagination. (PR)
    - Receives context from query or parent block, e.g. archive block.
  - [ ] Footer template part with widget replacements. (PR)
- [ ] Singular template. (PR)
  - [ ] Comments block. (PR)
- [ ] 404 template. (PR)

**Comment by dashkevych** [comment]
Are we allowed to add custom CSS classes to the blocks in these templates (for example, if the theme has decided to use utility-first CSS framework) ?

If we are allowed to use custom CSS classes in the templates, how the template updates will work if the template will be saved as CPT after the user's changes (https://youtu.be/__VN9VNtT0E).

**Comment by epiqueras** [comment]
Yes, the classes will also save in the created CPT post.

These templates are just the editor's serialized output. You could also use [block style variations](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#block-style-variations).

**Comment by mtias** [comment]
We are no longer bundling a demo theme.
