### ISSUE TITLE
Numbered list correctly continues in editor, not in published post.

### ISSUE THREAD

**Issue by valtoire** [WordPress/gutenberg#19145]
I wish to have some text and headers in between the numbered list, and the block editor seems to know what I'm up to, helping me to number off the H3 headers as I wanted it to appear.

![Screenshot 2019-12-14 at 2 02 46 PM](https://user-images.githubusercontent.com/58873010/70844341-cea53b80-1e7a-11ea-8b12-95d301e10c5d.png)

But after publishing it, the numbered list resets itself after each H2 header. Any idea what's going on and how to get the number flowing again without having to manually type in the number (because in future, I wish to be able to update the post without changing all the numbers)?

![Screenshot 2019-12-14 at 2 02 56 PM](https://user-images.githubusercontent.com/58873010/70844366-25ab1080-1e7b-11ea-8f54-eb0a1efd7183.png)

**Comment by mcsf** [comment]
1. Can you provide detailed steps on how to create the content shown above? In addition, could you share the full content as shown in Code mode? You can copy it all at once by pressing <kbd>Ctrl-A Ctrl-A Ctrl-C</kbd>.

2. Do you have any other active plugins?
