### ISSUE TITLE
Media replace flow doesn't show errors

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#19156]
**Describe the bug**
The new component which handles media replace flow does not show erros, as it leaves this to the parent component. However, the parent comonents where this new flow needs to be implemented relied on an "editing" state where the media was absent and a placeholder would display both edit actions and eventual erroes.

In all the 

**To reproduce**
1. Try to upload an oversized image
2. Observe it failed but no message was shown

**Expected behavior**
A clear and concise message should be shown somewhere. Where?

Given the lack of space in the media blocs when displaying media or "players", should we use a snackbar?

**Comment by karmatosed** [comment]
I would advise against snackbars for this as it's not right by where the error occurs and it's also the wrong use of that style of the component.

A possible 'quick fix' would be:

<img width="816" alt="narrow" src="https://user-images.githubusercontent.com/253067/70919613-12ce4280-2019-11ea-9023-d3406bd16b37.png">

Or, a simpler:

![wide](https://user-images.githubusercontent.com/253067/70919627-182b8d00-2019-11ea-9f23-7d887011fb95.png)

Once this link interface iterates that could be used also:

<img width="820" alt="link" src="https://user-images.githubusercontent.com/253067/70919664-29749980-2019-11ea-848f-38776a66770d.png">

**Comment by draganescu** [comment]
@karmatosed I implemented the 1st option above in #19244 as it was the one that kept the errors in the same place as where the action happened.

I used the standard noticeUI (which the placeholder also uses) and fixed a bit of CSS to make it fit the smaller space of the replace menu.
