### ISSUE TITLE
Blocks with Width option - can't easily go back to Default width after changing to Wide or Full

### ISSUE THREAD

**Issue by juliaamosova** [WordPress/gutenberg#19160]
**Is your feature request related to a problem? Please describe.**

Spotted this issue during WooCommerce 3.9 beta1 testing which includes [WooCommerce Product blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block) as a part of WooCommerce core experience. In `All Products` Block, for example - can't easily go back to default width after changing to `Wide` or `Full`. 

Clicking on the currently selected width allows going back to the default width, however - not very intuitive. 

**To Reproduce**

1. Go to page or post where you can add blocks;
2. Add `All Products` block;
3. Note that when you add the block, the default width is set on the block:

![all_products1](https://user-images.githubusercontent.com/19143190/70794889-99bfb880-1d96-11ea-9117-ece9922c8500.jpg)

4. Change the width to either `Wide` or `Full`:

![all2](https://user-images.githubusercontent.com/19143190/70795036-ddb2bd80-1d96-11ea-9862-b925ec219bf9.jpg)

5. Try to switch the width back to default and you'll see that there is no default width option:

![all3](https://user-images.githubusercontent.com/19143190/70795205-308c7500-1d97-11ea-9950-e2d279c809db.jpg)

**Describe the solution you'd like**

I expected to be able to go back to the default width after switching to either Wide or Full by selecting the Default option from the dropdown. It is not clear that you must click on the currently selected width option to go back to Default:

![default](https://user-images.githubusercontent.com/19143190/70901540-e56e9e00-1ff2-11ea-97bc-380d6ab08d96.jpg)

**Describe alternatives you've considered**

None.

**Comment by mapk** [comment]
The block toolbar's icon interaction, for the most part, behaves like toggles. This toggling interaction is the normal behavior across all the icons.

![toggle 2020-02-18 09_33_58](https://user-images.githubusercontent.com/617986/74762085-ffff0680-5231-11ea-8c92-20ed165ec30f.gif)

It is a bit of a learning curve in reference to the popover selections that appear. But I think once that behavior is understood by interacting with the other icons in the toolbar, it becomes more obvious. I'm going to close this for now for those reasons.
