### ISSUE TITLE
Align publish button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19175]
Currently, the publish button floats in the middle of the screen :

![image](https://user-images.githubusercontent.com/253067/70922342-d6e9ac00-201d-11ea-9728-8a6b8a7b00d3.png)

**Comment by karmatosed** [comment]
If we aligned left it would be placed here:

![image](https://user-images.githubusercontent.com/253067/70923172-59bf3680-201f-11ea-98c8-2c3595eb7b86.png)

**Comment by MichaelArestad** [comment]
What is the reason for the center alignment? Feels like a one-off? It probably should be aligned left.

**Comment by shaunandrews** [comment]
I think it looks centered right now because its aligned with the position of the Publish button in the normal Top Bar of Gutenberg. Making it wider could help it keep the appearance of that alignment, but also fill the space a little more and be easier to tap:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/191598/70923671-3c29a700-1ff6-11ea-8b33-7c27a26704db.png">

**Comment by shaunandrews** [comment]
If we wanna get fancy with it, we could add a transition to the button so it appears to grow in size when the publish sidebar appears.

**Comment by karmatosed** [comment]
I actually prefer it aligned left as stops us having the close and publish right next to each other. Beside each other, they feel like a trap we are laying down.

**Comment by karmatosed** [comment]
An interesting point the button changes anyway:

<img width="394" alt="Frame 18" src="https://user-images.githubusercontent.com/253067/70927458-e4576400-2026-11ea-962b-c70f7f70e6bb.png">

**Comment by MichaelArestad** [comment]
> An interesting point the button changes anyway:

Yeah. That's what I saw. Worth testing as a PR.

**Comment by shaunandrews** [comment]
> having the close and publish right next to each other.

On mobile, it seems to be more logical for the next action (publish) to be on the right. The cancel (or maybe it should be a back arrow?) would logically be on the left. (This would be reversed with rtl languages.)

**Comment by MichaelArestad** [comment]
> On mobile, it seems to be more logical for the next action (publish) to be on the right. The cancel (or maybe it should be a back arrow?) would logically be on the left. (This would be reversed with rtl languages.)

That thought crossed my mind as well. A media query to change the close button position and button position on mobile could work. The downside is the close button would be in a different spot _just_ for this part of the flow.

I wonder if the button should be here:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1123119/71104841-b0408800-2179-11ea-8a27-7be8d7978481.png">

Just some things to consider.

**Comment by mapk** [comment]
In the vein of @shaunandrews' comment, here's an idea of how that might look.

![publish](https://user-images.githubusercontent.com/617986/71130986-38d61d00-21a8-11ea-82e4-d7f7b0f26fc9.png)

**Comment by karmatosed** [comment]
@mapk that mock covers the close though, I don't think < works as action here.

**Comment by mapk** [comment]
@karmatosed yea, it doesn't "cover" the close `X` icon, just replaces it with the `<` icon. We do use this pattern elsewhere when shifting back to another view. For example in the editor Top Toolbar.

![Screen Shot 2019-12-23 at 3 51 31 PM](https://user-images.githubusercontent.com/617986/71385374-1d01bb00-259c-11ea-9ee8-76ede4ada3fe.png)

However, I'm completely open to other ideas and was just sharing some visuals. Because I agree that having the "Publish" button right next to the `X` feels like an accident waiting to happen, I'd be more in favor Michael's solution because it moves the "Publish" button away from the `X`.

**Comment by karmatosed** [comment]
Moving back to design feedback as not sure we have a clear way here yet (we are close though).

**Comment by enriquesanchez** [comment]
just FYI, the publish button was recently updated to be center aligned in https://github.com/WordPress/gutenberg/pull/17726

**Comment by folletto** [comment]
Taking Shaun's idea one step beyond — and noting that this means updating all the panels (pre, post) as it changes the `×`, what if we make the top part with only buttons, and in a flexbox that extends always the full width?


![stretchbuttons](https://user-images.githubusercontent.com/4389/74765411-6ceabe80-527b-11ea-8c79-62567de3fad4.png)

![stretchbuttons-one](https://user-images.githubusercontent.com/4389/74765413-6eb48200-527b-11ea-93ed-c462a058ceed.png)

This would have an extra benefit to make the top area work from zero to three buttons, and have also an explicit label for close. It would also mark the panel as clearly distinct from the other kind of panel (which uses the ×), supporting the perceptual difference between the two.

**Comment by paaljoachim** [comment]
Having a Publish and Cancel button would make it a lot cleaner, visually better and create better clarity then what exists today.

**Comment by enriquesanchez** [comment]
I think @folletto's exploration is much clearer to what we have now. We should definitively try this.

**Comment by karmatosed** [comment]
It looks like we have a decision on the way forward, so let's wrap up this feedback round and get a needs-dev label on this. Thanks everyone.

**Comment by juanfra** [comment]
I'd love to help on this one. I started to make some tests and the only thing I found (If I understood correctly the way it should be implemented) is that once we have the two buttons one beside the other, when "Publish" is clicked, the "Cancel" button is just beside, but the action won't cancel the publishing, but close the panel instead. I found this the only thing that could be misleading:

<img src="https://cldup.com/iD8AUtDNfL.gif" >

**Comment by paaljoachim** [comment]
Hey @juanfra 

Thanks for getting involved!

Going through the existing process:

1. Default
<img width="367" alt="Screen Shot 2020-05-14 at 23 44 32" src="https://user-images.githubusercontent.com/5323259/81989107-e99ff580-963c-11ea-8bd5-83157b34bef9.png">

Clicking Publish brings user to step 2.

--

2. Screen.
<img width="335" alt="Screen Shot 2020-05-14 at 23 45 14" src="https://user-images.githubusercontent.com/5323259/81989141-fae90200-963c-11ea-82c4-aa8ea57b8774.png">

Clicking the X = Brings user back to default 1.
Clicking the Publish button. (Are you ready to publish?) brings user to step 3.


--

3. Published.
<img width="313" alt="Screen Shot 2020-05-14 at 23 47 00" src="https://user-images.githubusercontent.com/5323259/81989264-397ebc80-963d-11ea-8aab-c6c3d1f4bf56.png">

Clicking the X = Brings user back to default 1.

-------------

The new process:

1. Default
<img width="367" alt="Screen Shot 2020-05-14 at 23 44 32" src="https://user-images.githubusercontent.com/5323259/81989107-e99ff580-963c-11ea-8bd5-83157b34bef9.png">

Clicking Publish brings user to step 2.

--

2. Screen.
![Publish-step-2](https://user-images.githubusercontent.com/5323259/81991095-c6774500-9640-11ea-86bb-43880b4a5c44.jpg)

Clicking the Cancel button = Brings user back to default 1.
Clicking the Publish button. (Are you ready to publish?) brings user to step 3.

--

3. Published.
![Publish-Close](https://user-images.githubusercontent.com/5323259/81991432-819fde00-9641-11ea-850c-16943f86c0bc.jpg)


Clicking the Close buttons = Brings user back to default 1.

**Comment by juanfra** [comment]
Thanks so much for the clarification, @paaljoachim! :)

I just submitted a PR with the proposed changes.

**Comment by paaljoachim** [comment]
I added an animated gif of what the new Publish button flow looks like.
https://github.com/WordPress/gutenberg/pull/22390#issuecomment-631031685

**Comment by skorasaurus** [comment]
https://github.com/WordPress/gutenberg/pull/22390 has been merged; closing.
