### ISSUE TITLE
Table Individual cells align does not work

### ISSUE THREAD

**Issue by murshed** [WordPress/gutenberg#19191]
**Describe the bug**
I have tried to set table cells left-right individually but it now works.

**Expected behavior**
It should work individually

**Screenshots**
- https://i.imgur.com/DxGiYP6.png
- https://i.imgur.com/nZQFY8T.png

**Comment by talldan** [comment]
Hi @murshed, the option is specifically for aligning columns at the moment. I think once there are more options to select entire rows and columns in the table block the alignments would work only on the current selection. There's an issue for selecting columns/rows here, so I'll close your issue for that one:
https://github.com/WordPress/gutenberg/issues/16294

**Comment by murshed** [comment]
Thank you so much :)
