### ISSUE TITLE
Block Editor doesn't warn when an attribute type is misspelled

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#19192]
**Describe the bug**
The Block Editor doesn't warn when an attribute type is misspelled. The opposite happens and things still continue to work, which is not a great experience for block developers.

The relevant code is here:
https://github.com/WordPress/gutenberg/blob/master/packages/blocks/src/api/parser.js#L102

When an attribute type doesn't match one of the listed types, the function still returns `true` to consider it valid.

I think the best plan of action would be to add a console warning as there may be active blocks with misspelled types.

**To reproduce**
1. Edit an existing block's attribute type to be a random value (e.g. change the paragraph block 'content' attribute type to be 'thisisnotanattributetype'.
2. Create a post an add some paragraphs
3. Observe that everything still works

**Expected behavior**
The editor provides some kind of warning that an attribute type is specified but is not valid.

**Comment by simono** [comment]
I'll take a look into this :)

**Comment by aduth** [comment]
I think as far as validation is concerned, if the parser doesn't know a validation procedure associated with a particular type, it would be fairest to assess a value as being valid. I believe this is also being used for when a type is omitted, in which case the same should apply.

As to the question of developer experience in warning about an unsupported or misspelled type, I think there could separately be some improvements there, yes.

**Comment by paaljoachim** [comment]
Hey @talldan Dan!

Is this issue still valid?
It would be great with a status update.
Thanks!

**Comment by talldan** [comment]
It's still a good developer experience improvement, but it's low priority.

**Comment by t-hamano** [comment]
@talldan 

At the time this discussion, the JSON schema did not exist.
But now, validation can be done on the code editor.
Is validation with JSON schema worth resolving this issue?

![block json](https://user-images.githubusercontent.com/54422211/179922218-7824047a-a737-4683-866d-2213db568368.png)

**Comment by talldan** [comment]
Thanks for pointing that out @t-hamano, I think that's a good enough reason to close this issue. The tooling is there now for anyone that wants it.
