### ISSUE TITLE
i18n: the isRTL flag should be provided by the current locale data

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#19212]
Currently, when Gutenberg code needs to know if the current text direction is LTR or RTL, it gets it from various sources:
- the Block Editor has `isRTL` value in its settings
- components query the DOM: `document.documentElement.dir === 'rtl'`

But there is one place that could and should be the source of truth for everyone -- the `@wordpress/i18n` library and its current locale.

Every WordPress locale has a special translation string called `_x( 'ltr', 'text direction' )`. If the translation is `rtl`, then we're dealing with a RTL language. See the usage of this translation string in [Core PHP `WP_Locale` class](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-locale.php#L217)

`@wordpress/i18n` should export a new function that returns authoritative value of the RTL flag:
```js
import { isRTL } from `@wordpress/i18n`;

const popoverAlignment = isRTL() : 'left' : 'right';
```

**Comment by sirreal** [comment]
I've opened #20298 to implement this.

**Comment by sirreal** [comment]
With https://github.com/WordPress/gutenberg/pull/20298 and https://github.com/WordPress/gutenberg/pull/27838 I believe this is complete.
