### ISSUE TITLE
Error when duplicating multiple blocks

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#19219]
**Describe the bug**
Blocks cannot be previewed if they have been created through duplicated a bunch of selected blocks.

**To reproduce**
1. Add 3 paragraph blocks.
1. Select all of them.
1. Duplicate them.

**Expected behavior**
Blocks should be duplicated and previewed. Instead, they are duplicated but cannot be previewed. Switching momentarily to the code editor and going back to the visual editor makes the error to go away.

**Screenshots**
![Dec-18-2019 15-23-44](https://user-images.githubusercontent.com/1233880/71094384-2dd0bc00-21ab-11ea-8351-9307b40e7db6.gif)

**Comment by epiqueras** [comment]
I can't reproduce this anymore.

Has it been fixed?

**Comment by mmtr** [comment]
> Has it been fixed?

It seems so!
