### ISSUE TITLE
This block can't be previewed error message has inconsistent styling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19215]
I discovered this by having multiple blocks erroring. Whilst I am unsure what happened there, it did provide me an opportunity to see this:

![image](https://user-images.githubusercontent.com/253067/71091055-4d141d00-219c-11ea-97f7-c2c5771be6d2.png)

I would argue this message should be a consistent size and visual.

**Comment by tellthemachines** [comment]
@karmatosed were any of those blocks inside a Columns or other layout block with inner blocks? 
A screenshot of the markup in the inspector would be very helpful for debugging this.
The closest I can get to reproducing it is by 

1. Adding a two column block, 
2. Adding blocks inside each column
3. Causing the blocks inside each column to error by changing the markup in code view

Then I get 
<img width="704" alt="Screen Shot 2020-01-07 at 11 43 30 am" src="https://user-images.githubusercontent.com/8096000/71859620-a4762f00-3143-11ea-9787-d275449c5347.png">
Where one of the columns is now outside the Columns block:
<img width="559" alt="Screen Shot 2020-01-07 at 11 43 11 am" src="https://user-images.githubusercontent.com/8096000/71859653-ccfe2900-3143-11ea-90a2-d35a8537c5ab.png">

**Comment by tellthemachines** [comment]
Removing the `Good First Issue` label as this doesn't seem very straightforward to debug.

**Comment by karmatosed** [comment]
@tellthemachines I don't recall now but looking at last one that is likely columns. That said we should try and catch all with that far better error. If I find this again I can reopen but happy to close until do.
