### ISSUE TITLE
Site doesn't have any tags message in tag cloud should have some styling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19216]
The message that appears when the tag cloud has no tags, actually isn't styled:

![image](https://user-images.githubusercontent.com/253067/71091289-bf84fd00-219c-11ea-87eb-cf7269133d24.png)

**Comment by Ringish** [comment]
What about styling it in a kind of "disabled" way? Outfaded.

**Comment by karmatosed** [comment]
That sounds interesting @Ringish - would you like to do a mockup to show this? If not, I can.

**Comment by mapk** [comment]
Here's an example where the placeholder text mimics the placeholder text for the Paragraph block. It shows until the block has content.

![tags](https://user-images.githubusercontent.com/617986/87716584-e53ea880-c763-11ea-9288-8fa82c52db7d.png)

**Comment by cguntur** [comment]
Can I work on this?

**Comment by mapk** [comment]
>Can I work on this?

@cguntur Yes, please take it on! That would be wonderful. 🎉

**Comment by cguntur** [comment]
I fixed this issue, Here is the pull request - https://github.com/WordPress/gutenberg/pull/25323

**Comment by paaljoachim** [comment]
It seems like we can remove the "Needs Design Feedback" label here.

**Comment by Jorgeural** [comment]
This issue should be closed as @jasmussen says in the PR

![image](https://user-images.githubusercontent.com/16987747/123212608-4d922000-d4c5-11eb-8656-49cb2d00b52f.png)

**Comment by jasmussen** [comment]
Since it's so easy to reopen an issue if closing was in error, I'll close this one for now. Thanks Jorge.
