### ISSUE TITLE
Font size picker: "Huge" option exceeds width of selector

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#19220]
**Describe the bug**
Really big font sizes like the "Huge" one defined by the Twenty Twenty theme exceeds the default width of the font size picker, resulting in a weird layout.

**To reproduce**
1. Install and activate the Twenty Twenty theme.
1. Insert a paragraph block.
1. On the right sidebar, open the preset size selector under the Text Settings section.
1. Check the layout.

**Expected behavior**
1. The width of the selector should increase dynamically to the largest of the options, so the layout is uniform.

**Screenshots**
When "Huge" is not selected:
<img width="271" alt="Screenshot 2019-12-18 at 15 39 18" src="https://user-images.githubusercontent.com/1233880/71095570-201c3600-21ad-11ea-97c6-12ee23e55d1b.png">

When "Huge" is selected:
<img width="268" alt="Screenshot 2019-12-18 at 15 39 30" src="https://user-images.githubusercontent.com/1233880/71095881-a59fe600-21ad-11ea-8473-8a16f24ce0da.png">

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by chrisvanpatten** [comment]
Hi @mmtr - I believe this is a duplicate of #19130 and the associated PR #19150. I'll close this in favor of this issue but please reopen if you feel it's not :)

**Comment by mmtr** [comment]
It's the same issue indeed. I didn't find it before opening this issue, sorry!
