### ISSUE TITLE
Date picker does not properly format minutes

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#19229]
**Describe the bug**
In WordPress 5.3.2, with or without Gutenberg 7.1.0, when scheduling a post's publish date, any leading 0s are stripped from the minute field as soon as focus is changed.

**To reproduce**
1. Add a new post.
2. Click on "Immediately" next to "Publish".
3. Change the minute field to `00` or `01`.
4. Click on AM or PM.
5. The minute field has changed to `0` or `1`.

**Expected behavior**
I expect that any valid minute, `00` through `59`, would remain as entered.

**Screenshots**
![00-not-showing](https://user-images.githubusercontent.com/286171/71134865-a425ec00-21b4-11ea-9076-ace502672baf.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox
 - Version: 71.0

The attached gif also shows the effect described in #17644, which I would agree is jarring.

**Comment by youknowriad** [comment]
I'm not able to reproduce that issue, what locale, date format are you using?

**Comment by jeremyfelt** [comment]
* Date format: `F j, Y`
* Time format: `g:i a`
* Locale: `en_US`

It appears that this is browser specific and due to the field's `type="number`. If I create a simple HTML file containing `<input type="number" value="01" />`, Firefox displays an input field with `1`. That same file in Chrome and Safari displays an input field of `01`.

The classic editor used a `text` input instead of `number` for this field, which I'm guessing could partially be for this reason, though I haven't really looked into that.

**Comment by jeremyfelt** [comment]
The Gov.uk team wrote up their recent decision to switch from `type=number` to `type=text` with some additional info on accessibility / browser support. https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by jeremyfelt** [comment]
I now see `00` properly in the latest version of Firefox and latest WordPress and Gutenberg versions. It may still be worth looking at the difference between number/text inputs, but I'm going to go ahead and close this. :)
