### ISSUE TITLE
Weird CSS issue with Placeholders!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#1922]
When trying to keep the visual appearance for the tweet block in a boilerplate I was not able to edit the tweet block if it had the same CSS as that of what I have at the front end. Also adding a placeholder made things weird.

![Check](http://g.recordit.co/D845lf7r10.gif)

The content area is displaced as compared to the placeholder.
![img](http://g.recordit.co/lsGwE7I1ew.gif)
I have removed all the cache!

**Comment by karmatosed** [comment]
Is this using your boilerplate and not vanilla Gutenberg? I ask as I can't find a way to recreate this within Gutenberg. If it's not, then please provide some steps and what browser - the more information we have the better.

**Comment by ahmadawais** [comment]
@karmatosed Thanks for looking into it. 

Yes, It's happening with custom code only. If you can install this [boilerplate](https://github.com/ahmadawais/Gutenberg-Boilerplate) and uncomment [this line](https://github.com/ahmadawais/Gutenberg-Boilerplate/blob/master/block/04-tweet/block.js#L81) you'll be able to reproduce the issue.

**Comment by karmatosed** [comment]
@ahmadawais in that case, I would respectfully suggest you on your boilerplate repo work through this. You are welcome to bring to core-editor in Slack, but having an issue for something that isn't Gutenberg core at this stage, isn't really helping focus.

**Comment by ahmadawais** [comment]
@karmatosed I think it's what people are going to do. When Gutenberg gets into the core, people are going to extend it. This issue is related to that. It's not specific to a plugin. Don't you think?

**Comment by karmatosed** [comment]
I don't think we can say that and it's something for the team to work on, if it needs me to install your plugin when Gutenberg isn't released yet, then I feel yes it should be as I suggested.

**Comment by nylen** [comment]
@ahmadawais if you can frame this as a specific issue with specific CSS classes (and point to the rules that are causing the problem) then it would be a good fit for this repo.  See #1744 for example.
