### ISSUE TITLE
Alignment of dates in DatePicker is confusing

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#19228]
**Describe the bug**
On WordPress 5.3.2 with Gutenberg 7.1.0, the day numbers in the date picker are not aligned with the day names in their respective columns when using the date picker to schedule a post's publish date.

When selecting the day number, I had to pay closer attention than I expected when deciding which date was Friday.

It appears that this is intentional as part of #18856, which fixed #17129. 

**To reproduce**
1. Add a new post.
2. Click "Immediately" next to "Publish" to show the date picker interface.

**Expected behavior**
I expect the numbers on the calendar to be aligned with their respective day text.

**Screenshots**
***Before: (WordPress 5.3.2, no Gutenberg plugin)***
<img width="310" alt="Screen Shot 2019-12-18 at 4 16 31 PM" src="https://user-images.githubusercontent.com/286171/71134225-455f7300-21b2-11ea-8a7d-7b705d9decea.png">

***After: (WordPress 5.3.2, Gutenberg plugin 7.1.0)***
<img width="333" alt="Screen Shot 2019-12-18 at 4 16 52 PM" src="https://user-images.githubusercontent.com/286171/71134253-5f995100-21b2-11ea-860a-52be8b142fdc.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Firefox 
 - Version 71

**Comment by talldan** [comment]
Thanks for pointing this out @jeremyfelt, seems like there are all of a sudden lots of issues with the date picker!

**Comment by tellthemachines** [comment]
Closing as this was fixed in #19294.
