### ISSUE TITLE
Scripts: Add new command which generates `zip` file for the plugin

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#19237]
Plugin developers could benefit from having one command to run to output the zip file with all assets that should be included for the plugin to work in WordPress.

I discussed it with @bph and she raised the concern that having big folders like the `node_modules` one included might be not the best experience. She shared her workaround:

> I worked ‘around’ it to upload it to GitHub which is probably where it all ends up in the end. But it would be great for local testing without the need to use the GitHub repository and have the zip file easy to produce.

**Comment by bph** [comment]
For completeness sake: The quoted workaround above 'omits' the step to **add the node-module directory to the .gitignore file.**

**Comment by gziolo** [comment]
There is also this article from @mkaz explaining how to automate plugin publishing with GitHub action created by @helen and @10up:

https://mkaz.blog/wordpress/deploy-wordpress-plugin-using-github-actions/

**Comment by aduth** [comment]
Is it something which Gutenberg could use for its own plugin distribution? It would be nice to "dog-food" this solution.

On the point about `node_modules` and the fact that Gutenberg defines its own [whitelisting of files to include](https://github.com/WordPress/gutenberg/blob/510f18b6808dc8be9bb75d0b47d5ce21f71ec68e/bin/build-plugin-zip.sh#L112-L125), maybe it's something where it could support a feature like [npm's files](https://docs.npmjs.com/files/package.json#files) setting? `.gitignore` could work as well, though it's not clear this would have the desired effect, considering that the built outputs of the plugin should in most cases be included in a project's `.gitignore`.

**Comment by gziolo** [comment]
> On the point about `node_modules` and the fact that Gutenberg defines its own [whitelisting of files to include](https://github.com/WordPress/gutenberg/blob/510f18b6808dc8be9bb75d0b47d5ce21f71ec68e/bin/build-plugin-zip.sh#L112-L125), maybe it's something where it could support a feature like [npm's `files`](https://docs.npmjs.com/files/package.json#files) setting? 

It made me think about using `files` In `package.json` as a primary way to source the list of included files for the plugin’s `zip` file. The nice side-effect would be the possibility to run [`npm pack`](https://docs.npmjs.com/cli/v6/commands/npm-pack) which generates the tarball file. In fact, you could as well publish the package to npm and consume the tarball from there. Unless the tarball isn’t an option?

**Comment by skorasaurus** [comment]
Is this requesting something different than `npm run build:plugin-zip` ? (https://github.com/WordPress/gutenberg/blob/master/bin/build-plugin-zip.sh)

I ask because I'm looking for a command that would build a 'lean' zip of Gutenberg (like that command does) but that commands deletes node_modules, etc locally on my computer; and I found this issue. 

(For use cases, I then use that zip on another testing wordpress site on a remote server, without having to install node, etc on said server)

**Comment by gziolo** [comment]
Yes, it's different. The one you shared is unique to Gutenberg plugin.

**Comment by bph** [comment]
@skorasaurus I am not sure if I understood what you are looking for. Maybe you could benefit from the ['Gutenberg Nightly' ](https://gutenbergtimes.com/need-a-zip-from-master) version

**Comment by skorasaurus** [comment]
@bph Thanks for the mention and your work on this! I wasn't aware of it and that solves most of my use cases.

**Comment by bph** [comment]
You are welcome! Glad to read, most use cases are solved with the 'Nightly' 👍

**Comment by gziolo** [comment]
I finally found some time to implement the new `plugin-zip` command in `@wordpress/scripts` with #37687.
