### ISSUE TITLE
Text describing a new scheduled post displays encoded HTML

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#19231]
**Describe the bug**
In WordPress 5.3.2, with and without Gutenberg 7.1.0, when post is scheduled, the success message showing the new status encodes HTML.

**To reproduce**
1. Add a new post.
2. Give the post a title with an apostrophe in it. (e.g A post about Jeremy's great blog post titles)
3. Schedule a future publish date for the post.
4. The success text shows: "A post about Jeremy&#39;s great blog post titles is now scheduled."

**Expected behavior**
I expect the success text to show: "A post about Jeremy's great blog post titles is now scheduled."

(I apologize, I was apparently feeling very uncreative when creating that example title.)

**Screenshots**
<img width="301" alt="Screen Shot 2019-12-18 at 5 13 38 PM" src="https://user-images.githubusercontent.com/286171/71136630-498f8e80-21ba-11ea-82c6-b72f3289c673.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox
 - Version: 71.0

**Comment by Soean** [comment]
Related to `Fix/title encoding bug`: #19187

**Comment by youknowriad** [comment]
Hey @jeremyfelt I haven't been able to reproduce this.  It might have been fixed by #19187
