### ISSUE TITLE
Running "wp-scripts lint-js" produces ELIFECYCLE error

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress/gutenberg#19249]
Hey there, 

I'm new to using `wp-scripts` for Gutenberg block dev and I haven't had any issues so far until attempting to lint my Javascript. I've never run this command before (I've been sticking to `npm run start` and `npm run build`) but when I run `npm run lint:js` after having modified my `package.json` file with `"lint:js": "wp-scripts lint-js ./src"`- I get an error and the script fails shortly after printing the lint violations.

Here's what the output looks like:

```
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid blocks@1.0.0
15 verbose cwd /Users/yikes/vagrant-local/www/testing/public_html/wp-content/plugins/blocks
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "run" "lint:js"
18 verbose node v12.12.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error blocks@1.0.0 lint:js: `wp-scripts lint-js ./src`
22 error Exit status 1
23 error Failed at the blocks@1.0.0 lint:js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any help would be appreciated. Thank you!

**Comment by mkaz** [comment]
Can you share more of what your package.json includes? I think we are missing some required dependecies in the gutenberg-examples repo, just want to confirm.

I get an error if my only dependency is `@wordpress/scripts`

I have it working with the following in my package.json (and doing an npm install after)

```json
"devDependencies": {
	"@wordpress/eslint-plugin": "^3.1.0",
	"@wordpress/scripts": "^5.1.0",
	"eslint-plugin-eslint-comments": "^3.1.2",
	"eslint-plugin-import": "^2.18.2"
},
"scripts": {
	"start": "wp-scripts start",
	"build": "wp-scripts build",
	"lint-js": "wp-scripts lint-js"
}
```

**Comment by metalandcoffee** [comment]
Hi @mkaz!

My package.json looked like this.
```
{
  "name": "metal-coffee-blocks",
  "version": "1.0.0",
  "description": "A Suite of Gutenberg blocks by Metal & Coffee",
  "main": "index.js",
  "scripts": {
    "build": "wp-scripts build",
    "start": "wp-scripts start",
    "lint:js": "wp-scripts lint-js ./src"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": ""
  },
  "homepage": "",
  "devDependencies": {
    "@wordpress/scripts": "^6.0.0"
  }
}
```

I went ahead and installed the missing packages based on your sample above so now my devDependencies look like this.
```
  "devDependencies": {
    "@wordpress/eslint-plugin": "^3.3.0",
    "@wordpress/scripts": "^6.0.0",
    "eslint-plugin-eslint-comments": "^3.1.2",
    "eslint-plugin-import": "^2.19.1"
  }
```

It's still not working for me though. It's the same error as above.

**Comment by mkaz** [comment]
After you updated package.json, make sure you run `npm install` and then `npm run lint:js`

**Comment by gziolo** [comment]
@mkaz you shouldn’t need to install any additional packages. If this is the case, we probably should tweak either the package exposing wp-scripts or @wordpress/eslint-plugin which is meant to handle everything is required.

**Comment by metalandcoffee** [comment]
Hey @gziolo @mkaz - Even after I do another `npm install` with those additional dependencies, it's still failing. Some of it may be on my end but it's definitely not fully working right out of the box. It does show my linting errors though so I'm stll able to get my code up to standard! But it seems like the script doesn't end properly.

```
metalandcoffee$ npm run lint:js

> metalandcoffee-blocks@1.0.0 lint:js /Users/metalandcoffee/vagrant-local/www/testing/public_html/wp-content/plugins/metalandcoffee-blocks
> wp-scripts lint-js


/Users/metalandcoffee/vagrant-local/www/testing/public_html/wp-content/plugins/metalandcoffee-blocks/src/blocks/cta/save.js
   2:10  error  'Fragment' is defined but never used           no-unused-vars
   4:27  error  Block must not be padded by blank lines        padded-blocks
   7:17  error  'type' is assigned a value but never used      no-unused-vars
   8:12  error  Missing trailing comma                         comma-dangle
  14:10  error  A space is required after '{'                  react/jsx-curly-spacing
  15:5   error  Expected property shorthand                    object-shorthand
  16:21  error  Missing trailing comma                         comma-dangle
  17:5   error  A space is required before '}'                 react/jsx-curly-spacing
  20:13  error  Unexpected usage of singlequote                jsx-quotes
  24:13  error  Unexpected usage of singlequote                jsx-quotes
  32:1   error  Block must not be padded by blank lines        padded-blocks
  34:21  error  Newline required at end of file but not found  eol-last

✖ 12 problems (12 errors, 0 warnings)
  10 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yikes-blocks@1.0.0 lint:js: `wp-scripts lint-js`
npm ERR! Exit status 1
```

**Comment by mkaz** [comment]
@metalandcoffee that looks like it is working, you just have lint errors that need fixing :-)

You need to go through each and fix each, for example the first you define Fragment, likely on an import but then it is not used elsewhere, so that can probably be removed.

**Comment by metalandcoffee** [comment]
Gotcha @mkaz - I guess I got confused by the way the script was ending and thought something was wrong. But when I fixed the JS lint errors, it echoed nothing which I assume is good news 👏🏾 Thanks for your help.

@gziolo I went through and restored my package.json to what it was prior to adding any additional packages and it still seems to lint properly. Here's the output for when there is a linting error:
```
> wp-scripts lint-js
/Users/yikes/vagrant-local/www/testing/public_html/wp-content/plugins/metalandcoffee-blocks/src/blocks/cta/save.js
  50:1  error  Expected indentation of 2 tabs but found 1  indent

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metalandcoffee-blocks@1.0.0 lint:js: `wp-scripts lint-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the metalandcoffee-blocks@1.0.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/metalandcoffee/.npm/_logs/2019-12-23T18_10_44_190Z-debug.log
```

Here's the output for when it's clean.
```
> wp-scripts lint-js
```

So I'm no longer having issues. Just got confused by seeing the `npm ERR!` which usually indicates a script problem. Thank you.

**Comment by mkaz** [comment]
@metalandcoffee I'm glad to see it is working for you now.  There is a bug with the includes that we need to fix, thanks for unintentionally finding it :-).  Right now it continues to work for you without error because you previously installed the packages, so they exist in the `node_modules` directory. If you delete that directory and do a fresh `npm install` you'll get the error again. So for now you will need the extra entries in your package.json.

@gziolo Here is a test repo that demonstrates the error, I think the eslint-plugin needs to specify the comments plugin. Repo: https://github.com/mkaz/test-block

Error:

```
> npm run lint-js

> mkaz-test-block@0.1.0 lint-js /home/mkaz/src/mkaz/test-block
> wp-scripts lint-js


Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the plugin "eslint-plugin-eslint-comments".

(The package "eslint-plugin-eslint-comments" was not found when loaded as a Node module from the directory "/home/mkaz/src/mkaz/test-block".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-eslint-comments@latest --save-dev

The plugin "eslint-plugin-eslint-comments" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by gziolo** [comment]
I couldn't reproduce with the latest version of `@wordpress/scripts` **v6.1.1**. See https://github.com/WordPress/gutenberg-examples/pull/103. 

@mkaz, I think the issue you have is produced by your own ESLint config override which adds this plugin:

https://github.com/mkaz/test-block/blob/96cb51b5b25bfef87373fbd47ee327833418c9e4/.eslintrc.js#L6

So you need to install it, since it's not included in WordPress distribution.

**Comment by mkaz** [comment]
Thanks @gziolo :+1:
Confirmed fixed removing the custom .eslintrc.js and upgrading wp-scripts
