### ISSUE TITLE
Edit Site: Display current theme template and template hierarchy selection

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#19252]
The new `edit-site` editor environment should clearly display the current template being edited (index, home, singular, etc) and offer the ability to switch to a different one.

One challenge is going to be to determine _how much_ of the template hierarchy should be displayed without exposing all of its complexity. A good baseline is going to be to start by only showing what the theme has defined and evolve from there.

Initial IA proposal:
![image](https://user-images.githubusercontent.com/548849/71202534-bbd89f80-229c-11ea-97d0-10867761ea9b.png)

- Clearly show current template.
- Offer a dropdown to select other templates (highlight the currently viewed one).
- Allow selecting template parts separately (flyout menu) to discriminate between parts and full page templates.
- Allow creating a new template part from the flyout itself.

(The "navigate to:" should be explored elsewhere, see #19204.)

**Comment by epiqueras** [comment]
### Current Prototype:

###### Switching templates:

<img width="374" alt="Screen Shot 2019-12-20 at 9 33 30 AM" src="https://user-images.githubusercontent.com/19157096/71255182-f9c0dc80-230b-11ea-8a37-193eb2c65c5e.png">

###### Adding templates:

<img width="339" alt="Screen Shot 2019-12-20 at 9 33 40 AM" src="https://user-images.githubusercontent.com/19157096/71255187-fdecfa00-230b-11ea-9e28-61fa4bdfe550.png">

Clicking on a template part isolates it, like described in #19253.

**Comment by mtias** [comment]
Let's move it to the left so that it can provide location awareness.

**Comment by epiqueras** [comment]
Good idea. I also added the "New" button and removed the form from the sidebar:

<img width="1140" alt="Screen Shot 2019-12-20 at 10 31 01 AM" src="https://user-images.githubusercontent.com/19157096/71257992-e154c000-2313-11ea-926f-33797bcbf118.png">

<img width="994" alt="Screen Shot 2019-12-20 at 10 31 38 AM" src="https://user-images.githubusercontent.com/19157096/71258007-ed408200-2313-11ea-834b-bbaa05241c41.png">

**Comment by shaunandrews** [comment]
Spent some time this week looking at how we could show templates and template parts. One question that came to mind as I worked on this was how to list template parts; That is, in @mtias' first mockup is the list of template parts showing _all_ template parts, or is it showing template parts related to the current document?

With that question in mind, here's a few design variations I came up with:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/191598/73076919-1ad99780-3e8d-11ea-9eae-ba3d657c609f.png">

The list of templates could be rather large:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/191598/73076967-3c3a8380-3e8d-11ea-8c50-35aed322998e.png">

We could go with a two-column layout, but the feels overly complex:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/191598/73077047-5ffdc980-3e8d-11ea-887f-1f3c179c0d18.png">

If we wanted to show the relationship between templates and the parts they use, maybe we could add submenus for each template — or just the currently selected template:

![Template Part Submenus](https://user-images.githubusercontent.com/191598/73077242-ce428c00-3e8d-11ea-9bf1-c6dd176c3ea5.png)

Another option for showing the relationship between the current template and it's template parts is to show them in the same list with some indentation:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/191598/73077365-0649cf00-3e8e-11ea-89fc-a23e6b427bb8.png">

--

Another option is to separate the template parts from the templates. We could show the template parts used by the current document in the Content Structure menu:

![Add Template Parts to Block Navigator](https://user-images.githubusercontent.com/191598/73077606-7d7f6300-3e8e-11ea-8738-f12a8c5e9335.png)

**Comment by epiqueras** [comment]
This is excellent stuff!

The first variation makes the most sense to me. I don't like that the other ones either take up more space or show the same template part in multiple places.

>is the list of template parts showing all template parts, or is it showing template parts related to the current document?

I am not sure either, but I think the latter makes more sense. It's a sort of zoom-in focused editing feature, and the site's entire repertoire of template parts could get rather long for a dropdown. It makes more sense to have that in a searchable gallery on the empty template part block placeholder.

**Comment by mtias** [comment]
> I am not sure either, but I think the latter makes more sense. It's a sort of zoom-in focused editing feature

Yes, the selector for template parts is about seeing what is used and focusing, it's not necessarily the best way to insert a template part to the document.

**Comment by MichaelArestad** [comment]
I tried a variation of this in conjunction with tackling a few other issues. I thought they might fit nicely in the block toolbar like this:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1123119/75926929-95042100-5e28-11ea-9527-88f0b344e01d.png">

**Comment by jasmussen** [comment]
Glad to see so many high fidelity mockups coming out, it's really conducive to fast focused discussion. Thank you!

I see what you're trying to do with the shading — but it feels a bit heavy, and I'm wondering if we need it at all. One of the things to remember with static mockups is that they are static — I wonder how it would look if the padding simply animated in and the background simply bled through. There would be edgecases, yes, where a particularly fixed background image would lose perfect 1:1 synchronicity, but given the principle of "a block can show additional controls when selected" this seems worth a shot.

**Comment by shaunandrews** [comment]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/191598/77102877-ed721b80-69ef-11ea-8f8c-b49f5e3e608a.png">

**Comment by mtias** [comment]
This looks like a good start to me. I feel the "Create..." is lost a bit without the + icon.

**Comment by joanrho** [comment]
@shaunandrews @MichaelArestad Saw this was moved to Needs Dev. Just to confirm, are we moving forward with the direction posted in Shaun's last comment or is there a newer direction that has an add (+) icon before the "Create new template"?

**Comment by MichaelArestad** [comment]
We're moving forward with this. We can iterate further as we get feedback on the PR.

**Comment by ockham** [comment]
I'd like to give this a shot :slightly_smiling_face:

**Comment by ockham** [comment]
Some preliminary findings on what's needed to implement https://github.com/WordPress/gutenberg/issues/19252#issuecomment-601351888:

- A submenu component (for template parts). I've checked `DropdownMenu`, `MenuGroup`, `MenuItem`, and friends, and there doesn't currently seem to be one. (I also didn't see one in the UI, at least at first glance.)
- We need to query the currently active theme. I haven't seen a dedicated selector/resolver; should be easy tho, it's the `'/wp/v2/themes?status=active` endpoint (used [here e.g.](https://github.com/WordPress/gutenberg/issues/19252#issuecomment-601351888))

I've noticed (and [asked about](https://wordpress.slack.com/archives/C02QB2JS7/p1586524395204300)) a bit of a discrepancy between templates and template parts that are stored as CPTs (manually added through the eponymous submenus of the 'Appearance' menu) vs the ones that `select( 'core' ).getEntityRecords( 'postType', 'wp_template_part' )` gives me. The latter are coming from the currently active theme.

- I'm going to ignore this discrepancy for now, as it's arguably orthogonal to this issue. (We'll probably need to provide some sort of endpoint that replicates the fallback order of CPT/theme-provided/whatever for templates that we're going to use for the frontend IIRC.)

Of note, I'm using the https://github.com/WordPress/theme-experiments repo for testing template-based themes (thanks to a [tip](https://wordpress.slack.com/archives/C02QB2JS7/p1586524314202900) by @mtias). This is easily done by adding a `.wp-env.override.json` to your local Gutenberg copy with the following contents ([see](https://github.com/WordPress/gutenberg/blob/319a8fcdbf89dd001532c68e7ce7d82a6b69ee0a/packages/env/README.md#a-complete-testing-environment)):

```json
{
	"core": "WordPress/WordPress",
	"plugins": [ "." ],
	"themes": [ "WordPress/theme-experiments" ]
}
```

(I'm currently using the _Parisienne_ theme from that repo for testing.)

**Comment by noahtallen** [comment]
> A submenu component (for template parts)

There is an existing issue here for this part of the functionality that I was looking into: #20470. Tldr is that the current popover API doesn't currently handle an implementation that would look like the design, so I made #21275 about improving the popover API :)

**Comment by ockham** [comment]
Thanks Noah, hadn't seen those issues!

Turns out there's also a dedicated one for showing the current theme in the popover menu: #20469

**Comment by mtias** [comment]
This is mostly done or obsolete. Let's close it and focus on improvements that can be done to the template sidebar, the inspector, and the header dropdown.
