### ISSUE TITLE
wp-env start throws errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by davidshq** [WordPress/gutenberg#19258]
**Describe the bug**
Running wp-env (using latest available via npm) start fails due to errors with Docker.

**Update**
In my case the issue was that I had installed docker-compose directly from Docker's site before I correctly installed Docker (it was installed, but using Ubuntu's repos, which have an older version). I removed docker-compose and reinstalled and things are working now.

**To reproduce**
1. Use Docker's instructions to add the package repositories for Docker (including removing Ubuntu Docker if installed): https://docs.docker.com/install/linux/docker-ce/ubuntu/
1. Install Docker: `sudo apt install docker.io`
1. Test Docker is working: `sudo docker run hello-world`
1. Run wp-env: `wp-env start`
1. Error appears: "spawn docker-compose ENOENT"
1. Install Docker Compose using Docker instructions: https://docs.docker.com/compose/install/
1. Test Docker Composer is working: `sudo docker-compose --version`
1. Run wp-env: `wp-env start`
1. Error appears: 
"Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable"

**Expected behavior**
Environment to successfully start.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser NA
 - Version NA

**Comment by mkaz** [comment]
I know this is not a great answer, but I believe the docker and docker-compose versions included in Ubuntu 18.04 version are out of date. I would recommend trying a more recent version from: https://docs.docker.com/compose/install/

I've had success using a newer version of Docker on Ubuntu.

**Comment by davidshq** [comment]
Thanks mkaz. I have tried that as well to no avail. I've updated my original issue to reflect going this route rather than using Ubuntu's Docker.

**Comment by davidshq** [comment]
I've updated original post to note that I was able to resolve the issue for myself. Still, it is quite a hurdle to get over for folks using Ubuntu, I'd recommend we add specific steps to the README.md to ensure folks progress correctly. I'm guessing this probably applies to other Linux distros as well?
