### ISSUE TITLE
Edit Site: Isolate template parts for editing

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#19253]
In the new `edit-site` context, it'd be good to explore a view mode that allows focusing only on a template part while editing.

**Example (Header):**
![image](https://user-images.githubusercontent.com/548849/71202867-45886d00-229d-11ea-97bb-7f2aaafb7815.png)

I imagine it could be added here as a section (`Template Parts`):

![image](https://user-images.githubusercontent.com/548849/71203298-0870aa80-229e-11ea-9826-5326b2c8490e.png)

**Comment by jasmussen** [comment]
In https://github.com/WordPress/gutenberg/pull/19082#issuecomment-567508590 I shared a mockup that embraces the same "View" dropdown, for starters just showing the responsive breakpoints. The dropdown interface scales well in an area that is already crowded, especially with the "Top Toolbar" option.

**Comment by epiqueras** [comment]
That's similar to how I implemented it for now: https://github.com/WordPress/gutenberg/issues/19252#issuecomment-567913179.

**Comment by MichaelArestad** [comment]
Can you provide an example situation where editing a template part in isolation would be necessary/useful?

**Comment by epiqueras** [comment]
Whenever you want to focus on a very reused part, like a header.

**Comment by mtias** [comment]
Also for a complex site (a large magazine) it might be reassuring to focus on a specific area (featured content, widget area, etc) knowing you won't affect the rest of the site by mistake.

**Comment by jasmussen** [comment]
A tangentially related use case is to have something more akin to a "template editor", where you might have a list of templates in a theme-package as a list where you can click to edit each. Having this overview of all the ingredients that make up your site is likely going to be crucial for editing templates that are otherwise not easy to navigate to organically, such as 404.

**Comment by mtias** [comment]
That is meant to be covered by https://github.com/WordPress/gutenberg/issues/19252 or were you think about something else?

**Comment by jasmussen** [comment]
Nope, I had forgotten about that one. That covers the 404 case. _As you were!_

**Comment by mtias** [comment]
The bulk of this already works, but should be updated to use the same visual treatment as the device preview:

Template Part focused:
![image](https://user-images.githubusercontent.com/548849/76169603-2271a900-617a-11ea-996c-2b563cc1bb24.png)

Device preview:
![image](https://user-images.githubusercontent.com/548849/76169618-492fdf80-617a-11ea-887a-55099c4f32f6.png)

**Comment by mapk** [comment]
Along the path of @MichaelArestad's and @shaunandrews' recent explorations, I fixed up a prototype of how this could work when isolating template parts.

**Prototype**

![isolate-part](https://user-images.githubusercontent.com/617986/76670219-a944ce00-654c-11ea-963a-114b7bbbb9f8.gif)

**Figma**
[https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=1405%3A2](https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=1405%3A2)

**Comment by MichaelArestad** [comment]
@mapk I think this is a solid direction. My only feedback is super minor so I'll save that for the PR. Let's move forward with this concept for now.

**Comment by MichaelArestad** [comment]
Very minor update:

![image](https://user-images.githubusercontent.com/1123119/78716404-15141f80-78dc-11ea-8473-0ca05d0ffcbc.png)

[Figma link to the frame](https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=1816%3A94)

**Comment by MichaelArestad** [comment]
It seems like this already works pretty close to the designs. Closing for now.

![image](https://user-images.githubusercontent.com/1123119/86408560-6f6f1300-bc74-11ea-80fc-cca830b74e23.png)

**Comment by mtias** [comment]
Reopening since it's not possible to focus just on one element from the toolbar anymore:

![image](https://user-images.githubusercontent.com/548849/97011792-68cc1a80-1547-11eb-91b7-b78129a9a255.png)

cc @shaunandrews @jameskoster

**Comment by jameskoster** [comment]
I feel like I'm missing something super obvious, but if I’m editing a template and can see the "Header" Template Part, why would I need to visually isolate it? Why not just click in and edit as normal? The top bar indicates that I'm editing a Template Part, what more information is required?

I understand the need perhaps for a 'mosaic' style view of _all_ Template Parts, with management functions (trash). And from there I might enter an an isolated view to edit a specific Template Part. But I’m not sure we need a shortcut to that view from regular template editing.

**Comment by mtias** [comment]
Being able to isolate template parts is a crucial part of the flow to me. It can be a great way to collaborate without running into each other. It can give a good sense of focus. It can help reach specific parts that might be hard to get to when in their final place (edges). It can allow editing templates that might not be immediately visible (a fixed header that slides in, for example) in a much more organized context. Etc.

**Comment by jameskoster** [comment]
I suppose we'll need the isolated view regardless, so it can't hurt to have a shortcut to that from template editing 👍

**Comment by noahtallen** [comment]
@matias this is actually still possible by selecting a template part from the nav sidebar. 

I’ve heard different approaches re the template part text in the header:
1. Clicking it does nothing because it would be confusing for accessibility 
2. Clicking it selects the template part
3. Clicking it “zooms in” to the template part

**Comment by mtias** [comment]
@noahtallen yes, sorry, I mean accessing from within the editor interface itself.

**Comment by jameskoster** [comment]
Here's an idea for Template part isolation:

<img width="2276" alt="Screenshot 2020-10-30 at 15 35 28" src="https://user-images.githubusercontent.com/846565/97725034-983dd280-1ac5-11eb-9cab-fd57a04e21e0.png">

The `back` row / link would only appear on occasions where a user enters Template Isolation directly from another document.

Upon isolation the Template Part will appear slightly offset on the Canvas, with a border to indicate its boundaries.

**Comment by carolinan** [comment]
I believe that this has been solved and that the issue can be closed? 
Or do we still want to add an edit link to the block inspector as in the screenshot?

**Comment by jameskoster** [comment]
We have a basic implementation, so can probably close this issue and continue refining in https://github.com/WordPress/gutenberg/issues/29148
