### ISSUE TITLE
Add predefined classes to className

### ISSUE THREAD

**Issue by antek83** [WordPress/gutenberg#1925]
## Issue Overview

The new `className` accepts true or false but I could not find a way to 'hook' into it to define a set of predefined classes. 
This is something that I think would be very useful. As an example there is a block that creates a info box with some text in it, developers could pre-define the allowed classes like: red green and blue and they would display in the 'sidebar' in a select box instead of an input field this would benefit both the UX and create a standard UI for doing things.

**Comment by mtias** [comment]
@aduth I believe this should be possible now, right?

**Comment by youknowriad** [comment]
Yes, that's how the "anchor" or "custom classname" hook work:

 - Adding a className to the `save` function
 - Adding an inspector control  to `BlockEdit`
