### ISSUE TITLE
Edit Site: Export all templates from `wp_templates`

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#19260]
There should be a way to export all templates defined in `wp_templates` as a theme package. Considerations should include whether it should use the current theme files if there is no matching user defined template.

This could start as an advanced tool in the actual templates CPT (similar to exporting reusable blocks) or within the editor ellipsis menu settings.

**Comment by epiqueras** [comment]
I made an exporter using @melchoyce 's Johannes theme as a template.

https://youtu.be/lT3qU0Wx0uU

<a href="http://www.youtube.com/watch?feature=player_embedded&v=lT3qU0Wx0uU
" target="_blank"><img src="http://img.youtube.com/vi/lT3qU0Wx0uU/0.jpg" 
alt="Gutenberg Edit Site Theme Exporter Demo" width="480" height="360" border="10" /></a>

**Comment by mtias** [comment]
Nice, I think we should add this as an ellipsis-menu tool in the top right of the header.

**Comment by epiqueras** [comment]
Done 😄 

<img width="1199" alt="Screen Shot 2020-01-07 at 12 55 36 PM" src="https://user-images.githubusercontent.com/19157096/71916963-1010ca00-314d-11ea-877e-db8dc00e2d42.png">

**Comment by jasmussen** [comment]
Nice!

Can it be a vertical ellipsis though, to match the one from the post editor?

![Screenshot 2020-01-07 at 19 12 21](https://user-images.githubusercontent.com/1204802/71917994-ae1e8780-3181-11ea-90ec-c193621c51d4.png)

**Comment by pablohoneyhoney** [comment]
If I'm not mistaken, on these circumstances the user is downloading as a theme her/his own design settings. If so, the copy could be more precise saying: _Export as a theme_, _Package as a theme_ or _Download as a theme_.

**Comment by epiqueras** [comment]
>Can it be a vertical ellipsis though, to match the one from the post editor?

Done.

>If so, the copy could be more precise saying: Export as a theme

Updated.

**Comment by mintplugins** [comment]
@epiqueras Is there already a related PR for this, or is this just a visual demo at this point?

**Comment by epiqueras** [comment]
https://github.com/WordPress/gutenberg/pull/19141

**Comment by skorasaurus** [comment]
I'm a little curious why this is marked as low. 

I had been wondering why there haven't been many examples of people sharing FSE themes just yet and this one reason why. 

To quickly experiment with other developers' themes, share my own theme creations and templates, and use version control on them, the theme templates need to be exported. 

Enabling the export (and import) of templates to HTML (or any file other based format) that developers can easily share, distribute, and manage is important.

**Comment by carolinan** [comment]
**I am very torn about this**. 
Do I look forward to using this as a way to create and package new themes? Sure.

But it does not belong in Gutenberg. It does not belong in core. It belongs as a separate plugin, like a child theme generator.

Yes, it is a feature that helps people make very small changes and save something as a new theme.
**But it is just as much a feature that invites abuse of commercial products, copyrights, and licenses, that can not be prevented.**

**Comment by mtias** [comment]
@carolinan that's a fair point. I'd add that including it in Gutenberg (the plugin) shouldn't mean eventually launching it in core. Right now it's useful for developers as they get to test and play with block themes.

**Comment by mtias** [comment]
Also, I think if it's ever considered for core inclusion it should likely be part of Tools -> Export.
