### ISSUE TITLE
Navigation block: Create from all top pages limited to 10 pages

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19266]
**Describe the bug**
In the Navigation block, if there are more than 10 top level pages and you choose `Create from all top level pages` then you only get the first 10, ordered by post ID. 

**To reproduce**
1. Create 11 or more top level pages.
2. Add a Navigation block.
3. Select `Create from all top pages`.
4. See only 10 listed.

**Expected behavior**
Well that depends. If there are only 11-20 pages then it would seem reasonable to create the menu with all the items. 
If there are hundreds then it might not be so.
Alternatively, let the user know that the output is limited. 
Maybe you can just remove the word 'all'. 
See also #18522.

**Screenshots**
I noticed this when the page entitiled 'Block plugin TODO list' was not displayed. It has a post ID of 3994. Here's the REST request and the response.
![image](https://user-images.githubusercontent.com/2474435/71248492-de0d0480-2312-11ea-9db1-335111e0e084.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 79.0.3945.79

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Gutenberg 7.1.0

- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
Thanks for reporting this @bobbingwide. Confirmed that I could reproduce this

**Comment by noisysocks** [comment]
We could maybe do the quick fix of e.g. `per_page=-1` for now since this endpoint likely won't be used in `nav-menus.php`.
