### ISSUE TITLE
Edit Site: Identify templates that have user modifications

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#19269]
With the block template system in `edit-site`, WordPress will have the ability to handle both theme templates and user templates contiguously. There should be a way to identify when a template has local modifications compared to the vanilla template.

Template selector, no modifications:
![image](https://user-images.githubusercontent.com/548849/71250495-1830d300-2320-11ea-912f-903dc6fda2af.png)

Template selector, "home" has been modified by the user / site:
![image](https://user-images.githubusercontent.com/548849/71250533-2f6fc080-2320-11ea-9235-c37745908595.png)

Showing a tooltip:
![image](https://user-images.githubusercontent.com/548849/71250552-3991bf00-2320-11ea-8936-f172f0b73aa4.png)

This could also be the basis for doing template reverts (restore a theme default) as well as "theme switches".

**Comment by epiqueras** [comment]
Implemented:

<img width="443" alt="Screen Shot 2019-12-20 at 2 54 10 PM" src="https://user-images.githubusercontent.com/19157096/71280250-7322f400-2339-11ea-9e3e-ccfdcdde48b7.png">

**Comment by pablohoneyhoney** [comment]
Nice one @epiqueras !
Is _Edited_ a better term than _Customized_?

**Comment by epiqueras** [comment]
"Edited" could be confused with "Unsaved Changes".

**Comment by mtias** [comment]
@epiqueras do we have anything left here or can we close?

**Comment by epiqueras** [comment]
We can close.
