### ISSUE TITLE
Audit and document what notices happen under what situation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19277]
Right now we have a few notice styles. It would be great to check through and then document clearly under what case we use which.

The documentation we have so far:
- Notices: https://developer.wordpress.org/block-editor/components/notice/
- Snacbkar: https://developer.wordpress.org/block-editor/components/snackbar/

This is more of a task as needs to go through and see what we use where then come up with some guidelines. Marking a low priority but a great little task to ensure it's easy to know what to use when.

**Comment by mtias** [comment]
This seems a bit too open ended to keep as an issue. Were you planning on doing anything with it @karmatosed?

**Comment by karmatosed** [comment]
Not right now, we can close and review along with the styling we have coming in.
