### ISSUE TITLE
Media: add new link interface

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19271]
The current link interface for image block isn't the new one using in navigation.

![image](https://user-images.githubusercontent.com/253067/71255698-8d9fa200-2326-11ea-8d16-8ad576a13cd8.png)

It would be great to bring in the one from navigation;

![link](https://user-images.githubusercontent.com/253067/71255704-94c6b000-2326-11ea-9ebc-35c6986e990b.png)

This would include the new media flow.

**Comment by johnwatkins0** [comment]
Hi, @karmatosed. This has been done, correct?

<img width="475" alt="Screen Shot 2020-02-18 at 9 44 34 PM" src="https://user-images.githubusercontent.com/9020968/74800069-f6a88500-5297-11ea-82dc-f5f34ececd70.png">

(On latest `master` branch.`)

**Comment by karmatosed** [comment]
Yes we can close this, thanks.
