### ISSUE TITLE
Font size picker see through background

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#19275]
**Describe the bug**
When trying to select a font size using the font size picker in the sidebar the text behind the selector is visible and cut by the selector's border.

**To reproduce**
1. Make a post
2. Add some text in a Paragraph block

**Expected behavior**
The stuff behind the selector should not be visible through the area of the selector.

**Screenshots**
<img width="340" alt="Screenshot 2019-12-20 at 16 27 47" src="https://user-images.githubusercontent.com/107534/71261412-fa766480-2345-11ea-9932-f4ca8aac78d1.png">

**Desktop (please complete the following information):**
 - OS: osx
 - Browser Firefox 71
 - Version 71

**Comment by bartczyz** [comment]
This is a duplicate of #19130 and was fixed by #19150.

**Comment by draganescu** [comment]
Yep, rechecked and seems fixed! Thanks @bartczyz :)
