### ISSUE TITLE
Rich text blocks: add new link interface

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19270]
Currently, paragraph block looks like this:

![image](https://user-images.githubusercontent.com/253067/71255341-8d52d700-2325-11ea-9945-f4c60215d299.png)

It would be good to bring in the new link interface from navigation:

![link](https://user-images.githubusercontent.com/253067/71255612-3f8a9e80-2326-11ea-8ec5-04cab614bdb9.png)

This should be done across all rich text blocks, for example,  quote, heading, paragraph and quote.

**Comment by paaljoachim** [comment]
Btw after choosing a link and clicking enter the next step is seeing something like this:

<img width="473" alt="Screen Shot 2020-01-31 at 12 24 51" src="https://user-images.githubusercontent.com/5323259/73535796-bc7c5e00-4424-11ea-8a6b-d89878edae68.png">

The Open in new tab will then also become visible.

**Comment by karmatosed** [comment]
@paaljoachim thanks for sharing that image. Are you suggesting it should be iterated or just showing the implementation? If you are interested in exploring other options an issue might be best to do that in so we can get the link interface the same across all interfaces and then iterate.

**Comment by paaljoachim** [comment]
Hey Tammie. @karmatosed  I was just showing the implementation of how Open in new tab has been implemented.
