### ISSUE TITLE
Navigation block: Long page titles cause horizontal scroll bars

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19273]
**Describe the bug**
When I created a Navigation with a top level page that had a very long title 
a horizontal scroll bar appeared in the editor. 

Additionally, the long page title is not at all well handled in the Page Attributes Parent Page drop down. It makes the drop down unusable. Should this be a separate issue? 
See the screenshot. 

**To reproduce**
1. Create a top-level page with a very long title
2. Add a new page
3. Add a Navigation block
4. Choose `Create from all  top-level pages` 
5. See the horizontal scroll bar being added.

**Expected behavior**
The long page title wraps on spaces but doesn't force the wrap when there aren't any.
It either needs to wrap or be truncated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/71256825-e45aab00-2329-11ea-984c-2db487f38083.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Development version. 

- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
I've labelled as a bug, though with this kind of thing there's always a question of exactly when should the value be capped/truncated. And also what if a user wants a long title? Shouldn't they be allowed to have one?

I'll add the `Needs Design Feedback` to see if there's any specific feedback on how we might better handle this from a designer.

**Comment by ibdz** [comment]
In [design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1582651218046500) in slack, we agreed that wrapping the title (_overflow-wrap_) would be the easiest way to handle a very long title like what themes do.

**Comment by karmatosed** [comment]
This is a duplicate of https://github.com/WordPress/gutenberg/issues/18337. So let's close this one to ensure focus on that and get this resolved.
