### ISSUE TITLE
Recent block list gets in the way of the block inserter

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19281]
**Describe the bug**
I often use `/ ` inside the empty paragraph block to get to the recent block list. More often than not I continue to type the right letters and the block I want appears.
But when I find I'm not sure what block I want I go up to the Add Block button ( top left ) and click on that. The component popup doesn't go away.
 I wish it would.

**To reproduce**
1. Add new post
2. Type `/` to start the block selection process
2. Click on the Add block in the tool bar ( top left )
3. Notice that the popup moves and hides 66% of the available blocks 

To resolve the problem you have to go back to the empty block and remove the /.
It's only three undo clicks, but it's not obvious.

**Expected behavior**
It would be nice if the popup went away, and perhaps even the `/`.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/71280331-cf464200-2352-11ea-814f-fe110bd9c842.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Gutenberg 7.1.0 - but it's been like that for a while.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by mapk** [comment]
Looks like a duplicate of https://github.com/WordPress/gutenberg/issues/19353. I'm closing this one in favor of the other.
