### ISSUE TITLE
Style Variants not parsing properly on load

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#19287]
**Describe the bug**

When creating a new block and setting the `styles` block attribute, the style does not get parsed properly and causes a block invalidation.

Example block:

```jsx
registerBlockType( 'mkaz/test-block', {
	title: 'Test Block',
	icon: 'smiley',
	category: 'widgets',
	styles: [
		{ name: 'default', label: 'Default', isDefault: true },
		{ name: 'large', label: 'Large' },
	],
	edit: ( { className } ) => (
		<div className={ className } >
			<p>Hello World.</p>
		</div>
	),
	save: ( { className } ) => (
		<div className={ className }>
			<p>Hola Mundo.</p>
		</div>
	),
} );
```
**To reproduce**

Use the sample test block above (also available at [my test-block repo](https://github.com/mkaz/test-block)) to reproduce the error.

1. Clone repo and build block plugin
2. Add the Test block to a post and select Large style
3. Navigate to Post (or reload) and block invalidates

![style-variant](https://user-images.githubusercontent.com/45363/71296904-27228000-2336-11ea-8fcc-12fb4a6169da.gif)

Block validation error message:
```
Content generated by `save` function:

<div class="wp-block-mkaz-test-block"><p>Hola Mundo.</p></div>

Content retrieved from post body:

<div class="wp-block-mkaz-test-block is-style-large"><p>Hola Mundo.</p></div>
```

The `is-style-large` value is properly saved in post_content, but when the block loads the classes are not parsed as a valid style name and thus invalidates the block.

**Expected behavior**

The style should be parsed from class names list and style set for block. 

**Additional context**

Tested on WordPress 5.3 and latest Gutenberg (7.1 at time of testing) same issue on both.

I believe this bug is also the cause of this reported issue: https://github.com/WordPress/gutenberg/issues/19248

**Comment by gwwar** [comment]
@mkaz do you mind including the published comment block and markup?

Testing against the v7.1 tag I'm seeing:
```
<!-- wp:mkaz/test-block {"className":"is-style-large"} -->
<div class="wp-block-mkaz-test-block is-style-large"><p>Hola Mundo.</p></div>
<!-- /wp:mkaz/test-block -->
```

Which does load correctly on second editor load.

**Comment by mkaz** [comment]
@gwwar I don't get the className property in the comment, mine is simply:

```html
<!-- wp:mkaz/test-block -->
<div class="wp-block-mkaz-test-block is-style-large"><p>Hola Mundo.</p></div>
<!-- /wp:mkaz/test-block -->
```

**Comment by gwwar** [comment]
Ah so, without the className property in block attributes, we can't expect the block to regenerate matching HTML markup. The bug here is that for whatever reasons that's not serialized in post-content.

🤔 Any other customizations locally?

This is what I'm seeing locally:
![test](https://user-images.githubusercontent.com/1270189/71298458-fd208c00-233c-11ea-9f8a-3aedba940840.gif)

**Comment by mkaz** [comment]
ok, weird. I uplodated the test block to a different test site and it worked.
Class name shows in comment and works as expected.
```html
<!-- wp:mkaz/test-block {"className":"is-style-large"} -->
<div class="wp-block-mkaz-test-block is-style-large"><p>Hola Mundo.</p></div>
<!-- /wp:mkaz/test-block -->
```

I'll try to figure out what's different between the two, I trimmed it down to nothing special and it still errors. The one erroring is running on Local By Flywheel (nginx) and the other is an external site running on Apache. I'll test a few more things.

**Comment by gwwar** [comment]
When clicking on a style in the sidebar we should dispatch an `UPDATE_BLOCK_ATTRIBUTES` action to add the class. https://github.com/WordPress/gutenberg/blob/56cd1df587d48fcb7d710aaae12098832a40a152/packages/block-editor/src/components/block-styles/index.js#L164

<img width="1367" alt="Screen Shot 2019-12-20 at 3 59 39 PM" src="https://user-images.githubusercontent.com/1270189/71299358-e4ff3b80-2341-11ea-93c6-8efac9e2a30e.png">

**Comment by gwwar** [comment]
In console we can then compare block state:

With `wp.data.select( 'core/editor' ).getBlocks()`:

<img width="840" alt="Screen Shot 2019-12-20 at 4 02 27 PM" src="https://user-images.githubusercontent.com/1270189/71299453-298ad700-2342-11ea-82f2-9b9984165888.png">

**Comment by gwwar** [comment]
Summarizing a slack chat, it appears that on an affected site we're seeing
```
<!-- wp:mkaz/test-block -->
<div class="wp-block-mkaz-test-block is-style-large"><p>Hola Mundo.</p></div>
<!-- /wp:mkaz/test-block -->
```

in the code view, but the in memory block looks okay:

![screenshot_from_2019-12-20_16-08-24](https://user-images.githubusercontent.com/1270189/71299865-ebdb7d80-2344-11ea-9cbc-5df7194979e5.png)

I think stepping though here next might help shed some light. https://github.com/WordPress/gutenberg/blob/56cd1df587d48fcb7d710aaae12098832a40a152/packages/blocks/src/api/serializer.js#L153

**Comment by talldan** [comment]
@mkaz I couldn't reproduce this one with your test block in the latest version of the plugin, could this be something that has been resolved?

**Comment by mkaz** [comment]
Thanks for following up @talldan 
I can no longer reproduce either. :man_shrugging:
