### ISSUE TITLE
Publish button warns in development mode

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#1928]
Based on the condition at the following line, it seems expected that a prompt should not be shown in development environments:

https://github.com/WordPress/gutenberg/blob/6a8e248/editor/header/tools/publish-button.js#L54

The issue is that the boolean coercion occurs before the equality check, so it effectively becomes `false === 'production'`, which will never short-circuit.

Instead, we should use a `!==` operator.

**Comment by mtias** [comment]
We are not warning anymore.
