### ISSUE TITLE
individual column background colours do not fill the entire column

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#19295]
If I add a background colour to a column in the column block then I expect the colour to fill the entire column, but it does not.

For example I want to reproduce this:
![medium](https://user-images.githubusercontent.com/1004130/71326640-7ebb1a00-24f5-11ea-9c0a-a33b8c5c6c16.jpg)

So; I add 2 columns. In the first column, I put a header, a title, and then another column block. In the second column I put an image, set the background colour to grey, and set the vertical alignment to center.

This is a screenshot of what I have done in the editor. _Note that it works as I expect here_:
<img width="1147" alt="Screenshot 2019-12-22 at 20 15 58" src="https://user-images.githubusercontent.com/1004130/71326818-20436b00-24f8-11ea-98f0-140e11fa103b.png">

You can see an example of the problem here (with a slightly different layout):
https://demo.prothemedesign.com/wordpress/gutenberg/2019/12/20/column-background-bug/

In a previous post someone said that they don't think the entire column should change background colour. I disagree.

1. If I set the background colour for a column to a something else, then (in my mind) it's logical that the entire column would change colour.
2. In the editor the entire background changes as I would expect (seen in the screenshot above), but on the frontend the layout does not match.
3. As a designer having the entire background of the change column change colour is more useful than adding a small background around a piece of content.

**Comment by talldan** [comment]
@BinaryMoon How did you set a background color for a column? 

There isn't an option to do this with the core columns block. It might be that you're using a plugin for this functionality. If thats is the case you'd need to raise this issue with the plugin developer.

**Comment by BinaryMoon** [comment]
I don't know. I assumed it was a core feature. I didn't realise it isn't something core can do. In that case it could be Editorskit (@phpbits?) since that seems to do everything.

I'll close this then since it doesn't seem to be a core thing.

**Comment by phpbits** [comment]
@BinaryMoon Seems like `align-self` behavior of flexbox. And yes, the column background is a feature from EditorsKit :)
