### ISSUE TITLE
Bit space in the search bar placeholder. Also when we start to enter something it should be started after a single space.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#19300]
**Describe the bug**
Bit space in the search bar placeholder. Also when we start to enter something it should be started after a single space.

**Version:** 5.3.2 
**Theme:** Twenty Twenty

**To reproduce**
1. Go to 'Editor'
2. Click on 'Add Block'
3. Add "Search Block"
4. See the placeholder text.

**Expected behavior**
Also when we start to enter something it should be started after a single space.

**Screenshots**

![image](https://user-images.githubusercontent.com/51028940/71353334-afa35980-259e-11ea-82c0-a54fcfa16b1d.png)

**Comment by talldan** [comment]
Fixed by #19452.
