### ISSUE TITLE
Flickring issue in Paragraph Block

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#19302]
**Describe the bug**
When we add Paragraph block manually and set custom font size, drop cap, text color and try move from paragraph block. Unable to move to the next block.

**To reproduce**
1. Go to 'editor'
2. Click on 'add block'
3. Select paragraph block and add.
4. Set the Font size, drop cap, text color.
5. See the flickering issue.

**Expected behavior**
When we clicking on the editor after editing the paragraph setting , It should be Flickr.

[Paragraph_issue.zip](https://github.com/WordPress/gutenberg/files/3994719/Paragraph_issue.zip)

**Comment by talldan** [comment]
@nayana96249 I don't seem to be able to reproduce this issue. Is it something you're still experiencing?

**Comment by karmatosed** [comment]
I am unable to replicate this, that's not to say there might not be a step missing though. For now, let's close this and if it's still an issue we can reopen.
