### ISSUE TITLE
Image Block: When we add any captions, then the preview in the Style section keeps blinking

### ISSUE THREAD

**Issue by RohanMultidots** [WordPress/gutenberg#19304]
**Describe the bug** 
When we add any captions to the images added in the Image block, then the preview in the Style section keeps blinking.

**To reproduce**
1. Add a new post.
2. Type /image to add the image block in the editor.
3. Add an image from the Media Library
4. Expand the Style section, and add a caption in the newly added image block.
5. Observe the preview in the Style section

**Expected behavior**
When we add captions, it should not flicker.

**Screenshots**
[Image_issue.zip](https://github.com/WordPress/gutenberg/files/3994829/Image_issue.zip)

**Comment by talldan** [comment]
I think this is the preview reloading/updating, which is curious as the preview doesn't show the content of the block so shouldn't need to reload.

**Comment by ntsekouras** [comment]
I can't reproduce this now. Can you verify that it has been fixed?

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7.2. Gutenberg plugin 10.6.2. Twenty Twenty One.

1. Adding a new post.
2. Typed: /image
3. Added an image from the Media Library.
4. Styles section is expanded (open). 
5. Added a caption. 
6. I could not see any flicker of the Styles area.

I have come across something similar where I have the browser window at a specific size then multiple sidebar objects have flickered. There are a few other issues for this flickering.

As I am not experiencing it and it has been quiet in this issue for a long time. I will go ahead and close it.
If I am mistaken please add additional details and we can then reopen the issue.
