### ISSUE TITLE
Mobile: content scrolls horizontally

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#19309]
**Describe the bug**

I'm not sure when this regressed. Currently the content width is larger than the viewport and now scrollable horizontally

**To reproduce**

**Expected behavior**

**Screenshots**

<img width="418" alt="Screenshot 2019-12-23 at 17 32 24" src="https://user-images.githubusercontent.com/4710635/71369332-b33cdd80-25aa-11ea-8dd6-cd7a5774cbef.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ellatrix** [comment]
Cc @jasmussen

**Comment by ellatrix** [comment]
Also cc @youknowriad since you refactored layout recently.

Looks like removing `display:flex` on `.edit-post-editor-regions__body` fixes the issue.

**Comment by karmatosed** [comment]
I think this is the same issue (maybe) reported here: https://github.com/WordPress/gutenberg/issues/19184

**Comment by ellatrix** [comment]
@karmatosed Might be related, but this issues is about the post content, not the block toolbar.

**Comment by jasmussen** [comment]
Is this issue present in both TwentyTwenty and TwentyNineteen? How about vanilla styles?

**Comment by mkaz** [comment]
Tested as part of Triage.

I tested on 10.6.2 and cannot duplicate using TwentyNinetween, TwentyTwenty on Firefox or Chrome.

I'm closing; we can reoopen if can be duplicated.
