### ISSUE TITLE
Broken "Insert from URL" Behavior when using Video block with templateLock = 'all' 

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress/gutenberg#19311]
**Describe the bug**
I have a block template defined to use `core/video` and I have the InnerBlocks templateLock set to `'all'`. Upon using my custom block and attempting to set the video from the "Insert from URL" option, the following console error is received.

```
Uncaught TypeError: this.props.onReplace is not a function
    at VideoEdit.onSelectURL (block-library.js?ver=2.9.6:19380)
    at MediaPlaceholder.onSubmitSrc (dmp.js:19)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.9.0:341)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.9.0:391)
    at invokeGuardedCallback (react-dom.js?ver=16.9.0:448)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.js?ver=16.9.0:462)
    at executeDispatch (react-dom.js?ver=16.9.0:594)
    at executeDispatchesInOrder (react-dom.js?ver=16.9.0:616)
    at executeDispatchesAndRelease (react-dom.js?ver=16.9.0:719)
    at executeDispatchesAndReleaseTopLevel (react-dom.js?ver=16.9.0:727)
```

**To reproduce**
1. Create a new block via InnerBlocks. Define the block template with a video block. And make sure to set the templateLock to 'all'.
```
const TEMPLATE = [
  [ 'core/video', {} ],
];
<InnerBlocks
  template={ TEMPLATE }
  templateInsertUpdatesSelection={ false }
  templateLock="all"
/>
```
2. Create new post
3. Add custom block
4. Set video from "Insert from URL" option and smash Enter.

**Expected behavior**
Video loads properly based on source (whether it be YouTube, Vimeo, etc)

**Screenshots**
Currently, nothing happens and a JS error is thrown every time you smash Enter.
![image](https://user-images.githubusercontent.com/20868511/71376408-554ecc80-258f-11ea-8f85-02afe534dff7.png)

**Desktop**
- OS: MacOS
- Browser Chrome
- Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by perrout** [comment]
I have the same problem.. did you find any solution for this?

**Comment by aristath** [comment]
Thank you for reporting this.
The issue was discussed and confirmed during a triage session.
The problem here is that when pasting a URL, the video block gets converted to an Embed/Youtube block.
Possible solutions discussed:
* A template could also accept more than one block type in a particular position
* Allow silently mutating block-types that are similar, soft-allowing multiple block-types.

Removing the `Needs Testing` tag and marking as a confirmed bug.

**Comment by isaquemelo** [comment]
Same here ;(
