### ISSUE TITLE
Add Block Window Cut Off when Using InnerBlocks

### ISSUE THREAD

**Issue by kevinfodness** [WordPress/gutenberg#19313]
**Describe the bug**
When using InnerBlocks, adding another block can cause the block picker to appear above the block to be added, which can result in it getting cut off if there is not enough content above the block being added. See attached screenshot for an example of this behavior.

**To reproduce**
1. Create a sample block as follows:
```js
/* global wp, React */

const {
  blocks: {
    registerBlockType,
  },
  editor: {
    InnerBlocks,
  },
} = wp;

registerBlockType(
  'sample-plugin/sample-block',
  {
    category: 'widgets',
    description: 'A sample block.',
    edit: () => (
      <InnerBlocks
        allowedBlocks={
          ['core/paragraph']
        }
      />
    ),
    icon: 'editor-insertmore',
    keywords: [
      'sample',
      'block',
    ],
    save: () => <InnerBlocks.Content />,
    title: 'Sample Block',
  }
);
```
2. After transpiling/registering/etc the block above to get it to load in Gutenberg, create a new post and add the block.
3. Click on the plus icon to add new InnerBlocks and notice that, depending on the position of the add icon relative to the middle of the screen, the block picker can appear above the insertion point such that part of it is obscured by the admin bar and is inaccessible.

**Expected behavior**
When using standard blocks, the editor intelligently determines whether to place the block inserter above or below the plus depending on whether there is more available screen real estate above or below the insertion point at the time it was clicked. If the user scrolls, the block inserter will reposition itself to where there is more space. If the user scrolls up and there is not enough room between the insertion point and the top of the window, the block inserter will intelligently move itself below the insertion point. However, this behavior does not work properly when using InnerBlocks, as the collision detection routine for the top of the window does not appear to be working as expected.

**Screenshots**
See screenshot of the collision here:
<img width="1008" alt="Screen shot of the collision between the block inserter and the top of the window" src="https://user-images.githubusercontent.com/2650828/71382172-c056ce00-25a4-11ea-8dd7-7884088526dc.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome 79.0.3945.88

**Additional context**
- WordPress 5.3.2, using default version of Gutenberg present in that release.

**Comment by talldan** [comment]
I could reproduce, but generally the browser has to be quite short, and full screen mode has to not be in use for it to appear under the wp-admin topbar.

**Comment by kathrynwp** [comment]
@talldan would you be able to confirm whether this is still an issue? Thanks!

**Comment by talldan** [comment]
It seems fine now. If there's enough space underneath, the popover will position there, otherwise it flips above the '+' button.

If there isn't enough space either above or below, the popover will have a reduced height with a scrollbar:
![Screen Shot 2022-08-05 at 12 09 26 pm](https://user-images.githubusercontent.com/677833/182999878-349c48cf-e459-4926-bb4c-956f48972476.png)
