### ISSUE TITLE
Crowdsignal and alignment tools

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#19321]
**Describe the bug**
Added a Crowdsignal embed block.
Tried to center align the block using https://d.pr/i/9Jxk6H
Tried on Maywood and Independent Publisher 2
Center align option doesn't work
Align right does work. 

**Expected behavior**
Align center option to work

**Desktop (please complete the following information):**
This is my set up but unaware of users set up
 - OS: MacBook Pro (15-inch, 2018) Catalina 10.15.2 
 - Chrome

2492066-zd

**Comment by talldan** [comment]
@rickmgithub Thanks for reaching out. This is potentially an issue with those themes rather than the Block Editor itself. I tried with two of the bundled core themes, Twenty Nineteen and Twenty Twenty, and the alignment options worked fine.

I'd recommend reaching out to the theme developer.
