### ISSUE TITLE
Incorrect heading number?

### ISSUE THREAD

**Issue by kmix-39** [WordPress/gutenberg#19339]
**Describe the bug**
The heading tag number is incorrect.

**To reproduce**
1. Go to 'Editor'.
2. Click on 'Heading'.
3. Insert 'Heading block'.
4. Setting 'h2'.
5. Insert 'Heading block'.
6. Setting 'h3' and Setting 'Numbered' style.
7. Insert 'Heading block'.
8. Setting 'h3' and Setting 'Numbered' style.
9. Setting 'h2'.
10. Insert 'Heading block'.
11. Setting 'h3' and Setting 'Numbered' style.
12. Insert 'Heading block'.
13. Setting 'h3' and Setting 'Numbered' style.
14. See number

**Expected behavior**
I think the number of the second heading should start from 1 again.

**Screenshots**
<img width="791" alt="スクリーンショット 2019-12-27 11 46 43" src="https://user-images.githubusercontent.com/34811629/71498354-62293400-289f-11ea-95b9-e461cbdec634.png">
----
<img width="790" alt="スクリーンショット 2019-12-27 11 47 24" src="https://user-images.githubusercontent.com/34811629/71498355-62293400-289f-11ea-930e-98868444c324.png">
-----
<img width="799" alt="スクリーンショット 2019-12-27 11 47 43" src="https://user-images.githubusercontent.com/34811629/71498356-62c1ca80-289f-11ea-9adb-3198b30346b3.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X Catalina
 - Browser: safari
 - Version: Gutenberg 7.1.0

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13
 - Browser: safari
 - Version: Gutenberg 7.1.0

**Comment by talldan** [comment]
Hi @kmix-39. I couldn't see a 'Numbered Style' on the heading block. Is it possible that you're using a plugin that provides this?

**Comment by kmix-39** [comment]
Oh, Very sorry. 
This seems to be a problem with the theme you are using, or another plugin.
