### ISSUE TITLE
Social Links Block: custom class not applied to individual icons

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/gutenberg#19335]
**Describe the bug**
The Social Links Block not only lets you add a custom class to the entire block but also to individual icons. However, the classes on the individual icons are not displayed on the front end. 

This feature is super helpful in cases you want to:

1. Change the image on a certain social network
2. Add a custom image to a network that has the default icon

**To reproduce**
1. Add the Social Links Block
2. Click on one of the icons you added
3. Open the _Advanced_ tab
4. Add a custom class
5. Publish the post

**Expected behavior**
To see in the front end the class I added in the editor:

<img width="1263" alt="Captura de Tela 2019-12-26 às 12 25 04" src="https://user-images.githubusercontent.com/1136160/71480976-c504c780-27da-11ea-9b6b-f97f767a98df.png">

**What happens**
The `custom-facebook` class I added is not displayed in the front-end:

<img width="678" alt="Captura de Tela 2019-12-26 às 12 26 42" src="https://user-images.githubusercontent.com/1136160/71481029-0006fb00-27db-11ea-930a-58851eea2d6c.png">

**Additional context**
Gutenberg Version 7.1.0

**Comment by talldan** [comment]
Thanks for reporting @eduardozulian. Confirmed that I could also reproduce this issue.
