### ISSUE TITLE
Columns block: No blocks found when using Top Toolbar Inserter while Column block is selected

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19354]
**Describe the bug**
When I have a single Column block selected within the Columns block and then click the `+` icon in the Top Toolbar, the Block Library shows "No blocks found".  This is super confusing.

**To reproduce**
1. Add a Columns block to the page.
2. Make sure the Column block is selected.
3. Immediately click the `+` icon in the Top Toolbar.
4. Observe the "no blocks found" messaging.

**Expected behavior**
I originally expected a list of blocks that can be added, but was completely confused by the messaging and didn't understand why. It wasn't until I realized that I had the single Column block selected. Maybe we should display better messaging in the Inserter in this case?

**Screenshots**

![cols 2019-12-27 14_30_36](https://user-images.githubusercontent.com/617986/71535110-4da56580-28b8-11ea-905c-d76e12eb1df3.gif)

**Desktop (please complete the following information):**
 - Mac OS Catalina
 - Firefox 71.0
 - Gutenberg 7.1

**Comment by enriquesanchez** [comment]
[Discussed during today's design triage in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1578417038043800).

The team agrees this is confusing. We shouldn't allow the user hit this dead end and/or provide better messaging. The message should explain what is happening and how to proceed.

**Comment by mapk** [comment]
I've added a `copy` label and `Needs Technical Feedback` because:

1. We need to know if there's a good technical solution here. If a user has a Column child block selected, can we prevent the `+` icon from being clicked? Should we? 

2. It needs some copy help if we're going to allow the user to click the `+` icon. We'll need to detect if they have the Column child block selected so we can present the appropriate copy.

**Comment by youknowriad** [comment]
Actually, this can be solved easily by allowing the single "column" block to appear in the inserter. It's not a perfect solution but I believe it's good enough.
