### ISSUE TITLE
« Norm‑al » style button icon, in GutenBerg Bloc editor.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#19359]
**Is your feature request related to a problem? Please describe.**
In some theme blockquote use Italic, but in some case I would like that some term or full text to be in `font-style:normal`

**Describe the solution you'd like**
A "**Normal**" button icon, like **Bold**, **Italic**…
Because use of HTML editor but it's a waste of time.

**Describe alternatives you've considered**

Now we have :
- « **Bold** »,
- « **Italic** » (« / »),
- « **Under‑line** »,
- « **Strike‑through** »,
- …

I proposed to Microsoft : « **Semitic** » (« \ »),
in Vôrdh / Word,
- https://aka.ms/AA4w1u0

but now,
and today,

I want "Norm‑al" to avoid need of use of code like `style="font-style: normal;"`,
in case of C.S.S. who use « Italic » or else,
in WordPress GutenBerg bloc or anywhere.

To set the defined **norm‑al**,
as `font-style:normal`,
in a BlockQuote who is set as « **Italic** ».
And who of priority upon it (by use of `style` in `tag` or else `!important`.

Please.
Thank you.
Good continuation and success.

**Comment by youknowriad** [comment]
Hi There!

since by default, the font style is normal, I believe having this in the toolbar would seem like a bug for most users. (don't do anything). I'd suggest writing a custom format for your use-case.

https://developer.wordpress.org/block-editor/tutorials/format-api/

Thanks.

**Comment by Nemzag** [comment]
Ok, but pro those who don't know how to code it's a complication,
think about these guys and case’s.
Thank you.

**Comment by youknowriad** [comment]
I understand but it's not a reason to add something that feels broken for most users right?
