### ISSUE TITLE
Saving entity data causes the entity to be reloaded WITHOUT context=edit

### ISSUE THREAD

**Issue by lindapaiste** [WordPress/gutenberg#19350]
When using the core-data package, all API calls through getEntityRecord included the parameter "?context=edit".  But when saving changes using the saveEntityRecord action, the POST request does not include "?context=edit".  Since the default context is "view" rather than "edit," this will cause API fields which are context-dependent to refresh with the incomplete or wrong version.

**Comment by noisysocks** [comment]
Closing as per https://github.com/WordPress/gutenberg/pull/19351#issuecomment-569462570.
