### ISSUE TITLE
Cannot increase the font size of text in "AB Drop Cap" Block

### ISSUE THREAD

**Issue by aashish-av** [WordPress/gutenberg#19358]
I am using the Atomic Blocks plugin to insert customizable drop caps to my text. However, I am not able to change the font size of the text in that block. 

Please help

**Comment by youknowriad** [comment]
Hi There!

Since this seems to be caused by the plugin, I'd suggest you open an issue in the plugin's tracker to address your issue.

Thanks for your understanding.
