### ISSUE TITLE
New block dialog (embed page) going off screen

### ISSUE THREAD

**Issue by voldemortensen** [WordPress/gutenberg#1936]
## Issue Overview

Embed search box goes off the top of page.

## Steps to Reproduce (for bugs)

1. Add new post.
2. Add asdfasdf as title
3. Add enough filler text to take up two lines
4. Click add block button
5. Click embed.
6. It goes above the screen boundary.

OSX 10.12.x Firefox 54

## Expected Behavior

Embed popup should stay on screen.

## Current Behavior

It goes off the screen.

**Comment by voldemortensen** [comment]
<img width="776" alt="guten" src="https://user-images.githubusercontent.com/7786383/28329378-db13a854-6ba6-11e7-953e-2cbe72029718.png">

**Comment by karmatosed** [comment]
Good catch! I can replicate that myself. Marking as a bug.

**Comment by mtias** [comment]
@karmatosed is this still the case after the improvements to the popover component?

**Comment by karmatosed** [comment]
I can't replicate now so marking as fixed 👍
