### ISSUE TITLE
Links getting removed from my content "New Post"

### ISSUE THREAD

**Issue by smoothunpack** [WordPress/gutenberg#19364]
Hi, Links are getting removed when i click on publish article. and i'm facing this issue from last night, this is the very first time i'm facing this issue.
and this is happening with only one of my website which is: [https://decorsimilar.com/](https://decorsimilar.com/)

**Comment by youknowriad** [comment]
Do you an example of post content to reproduce this issue?   By default it's not something we can reproduce. thanks.
