### ISSUE TITLE
Block Navigation doesn't display contents of a Reusable Block

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/gutenberg#19372]
**Describe the bug**
The blocks contained inside a Reusable Block aren't shown in the Block Navigation in a sub-tree similar to how other parent blocks such as Columns show the blocks they contain.

**To reproduce**
1. Insert multiple blocks in the Block Editor.
2. Highlight multiple blocks and select Convert to Reusable Block.
3. Name and Save the Reusable Block.
4. Open the Block Navigation from the Editor Toolbar and only Reusable Block is shown, not the contained blocks as a sub-tree.

**Expected behavior**
The Block Navigation should ideally reveal the contents of a Reusable Block in a sub-tree similar to how Columns, Groups, Media & Text and other blocks that contain children display a sub-tree when highlighted.

**Additional context**
- WordPress: Version 5.3.3-alpha-46995

**Comment by noisysocks** [comment]
This isn't expected functionality as the Reusable Block is a block which has an entirely different block editor in it, *not* a block with child blocks. Agree that it would be a nice enhancement, though.

**Comment by 0aveRyan** [comment]
@noisysocks I'm aware it's using `BlockEditorProvider`, separate data storage, underlying code, etc. 

I disagree it's not expected behavior -- to an end user the UX is just another block containing child blocks. The user doesn't know it's an entirely different Block Editor. It's the DX that's entirely different.

I'm happy to explore a PR for this.

**Comment by 0aveRyan** [comment]
I'll be working on a PR to explore this later this week. At the same time I'll be looking to address block breadcrumbs in the footer for consistency.

**Comment by helpdata** [comment]
This is surely a bug. I have a reusable block that consists merely of one container with a few containers in that, and I now cannot navigate with that structure since the Block Navigation does not show it, just shows "reusable block", even the block has been opened to "edit".

**Comment by helpdata** [comment]
Then when I click on the "..." on the top menu, the whole editor crashes with "The editor has encountered an unexpected error.

Attempt Recovery
Copy Post Text"

Goodness, how flaky.

**Comment by Ugoku** [comment]
Adding my experience to this bug:
I have a group, made up of two columns with content that I made into a reusable block. Now, there appears to be no way to change the classes of the block or to select the columns. Having the blocks inside a reusable block in the navigation tree would be very beneficial.
