### ISSUE TITLE
HTML Block escapes & after a < inside the block

### ISSUE THREAD

**Issue by FireEmerald** [WordPress/gutenberg#19371]
**Describe the bug**
The gutenberg editor **sometimes** escapes the char `&` > `&#038;` inside a `html` block.
This entirely breaks the usage of the `wp:html` block.

**To reproduce**
I don't know exactly how to reproduce. But it seems like the `<` comparator breaks it.
Could have to do something with your detection of the `<!-- wp:html -->` ?

**Expected behavior**
The `&` should not be escaped as shown in row 174.

**Screenshots**
Backend editor:
![2019-12-31 15_27_05-Window](https://user-images.githubusercontent.com/1107939/71624441-e69eee00-2be2-11ea-9ef6-859bf8a3c1d0.png)

Produced frontend code:
![2019-12-31 15_27_41-Window](https://user-images.githubusercontent.com/1107939/71624444-e868b180-2be2-11ea-8365-f772b8a96f8b.png)

Every `&` below line 174 is escaped - it's irrelevant where i place it:
![2019-12-31 15_51_50-Window](https://user-images.githubusercontent.com/1107939/71624958-7fcf0400-2be5-11ea-8c63-336f37553422.png)

If i place a `>` directly after `<`, the `&` is **not** escaped anymore:
![2019-12-31 15_56_42-Window](https://user-images.githubusercontent.com/1107939/71625095-421eab00-2be6-11ea-85c9-875506d27547.png)

Just for fun i placed inside a comment a `>` and it's working (as workaround):
![2019-12-31 16_07_17-Window](https://user-images.githubusercontent.com/1107939/71625383-cd4c7080-2be7-11ea-9b09-ba0b9e2e561b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 79.0.3945.88

**Additional context**
- Gutenberg: WordPress 5.3.2
- This issue was already reported and closed in #14293 but it's still present or again(?).

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; there's another issue that covers this - #26362 and has more discussion about this so I'm closing this to direct discussion to there. 

Thank you very much for the images and detailed description; that is really helpful.
