### ISSUE TITLE
Color Picker: Dragging color selection handle off of picker container causes unrecoverable block error

### ISSUE THREAD

**Issue by iamthomasbishop** [WordPress/gutenberg#19389]
**Describe the bug**
When dragging the color picker selection handle, if you pull it to an edge and then mouseUp while outside of the picker UI, it causes the block to fail with an error message of `This block has encountered an error and cannot be previewed.`.

**To reproduce**
1. Create a block that has color settings
2. Open that block's settings inspector
3. Click on "Custom Color"
4. Click and hold from the center of the picker, continue holding until your cursor is off the picker UI
5. Release the click, note that the block has an error

**Expected behavior**
I expect the custom color to be applied, with no error.

**Screenshots**
![GB-color-picker-bug-01022020-min](https://user-images.githubusercontent.com/1200432/71681171-94c8a600-2d51-11ea-9974-5f1816071b40.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.2
 - Browser Safari (13.0.4), Chrome (79.0.3945.88)
 - GB versions tested: 7.1.0 on GB core (self-hosted test site), also on WordPress.com (which afaik is running latest version 7.1.0)

**Additional context**
Note: works as expected on mobile, because it's not possible to drag the handle off of the picker UI.

**Comment by glendaviesnz** [comment]
I was able to replicate this on 7.1 and got the following console error:

<img width="690" alt="Screen Shot 2020-01-09 at 5 31 28 PM" src="https://user-images.githubusercontent.com/3629020/72038431-3463d680-3306-11ea-98b3-3c59813fbeb9.png">

I wasn't able to replicate it on latest master:

![color-picker-bug](https://user-images.githubusercontent.com/3629020/72038444-42195c00-3306-11ea-9254-29137d1e478d.gif)

But I couldn't find any obvious PRs/commits that may have fixed it.

**Comment by youknowriad** [comment]
Let's close as it appears fixed in master
