### ISSUE TITLE
Button block with gradient background failed to appear on preview and/or live site

### ISSUE THREAD

**Issue by retnonindya** [WordPress/gutenberg#19383]
**Describe the bug**
Button block with gradient background will fail to be displayed on the page/post's preview and/or live site.

**To reproduce**
1. Add 'Button block' on the page or post
2. Set the gradient background from the sidebar 
3. Click 'Preview'
4. See the button with no gradient background

**Expected behavior**
I expected the gradient background will be visible both on the editor and on the preview/live site.

**Screenshots**

Button block on editor view. Notice the gradient background on the button.

![button](https://cldup.com/J86LigNzft.png)

Button block when viewed on Preview and/or live site. Notice the missing gradient and the first button has black text and black border (I set the text color to black) and notice the "missing" second Button block (the text color is white).

![button](https://cldup.com/1kn4XqRoIx.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.2)
 - Browser: Chrome
 - Version: Version 79.0.3945.88 (Official Build) (64-bit)
- Gutenberg version: 7.1.0

**Comment by ThomasG1** [comment]
I am having issues with the Button Block.
A developer said it seems to be tied to this issue:
https://github.com/WordPress/gutenberg/issues/19287

But there seems to be no movement on any button block issues.

**Comment by youknowriad** [comment]
It is possible that your theme's CSS is forcing the background of the buttons. Do you have an example URL we can use to check?

**Comment by youknowriad** [comment]
I'm going to close this issue until we get more information.

**Comment by retnonindya** [comment]
Hi @youknowriad! So sorry for the late reply! 

On my end, it's Maywood theme. And for the URL, it's from my test site:
https://premiumtestsite2.corianderpho.blog/test-gradient-button-block-in-page/

Currently, the site is set to Private; I have set it to Public so you can check. Thank you so much for checking into this.

**Comment by youknowriad** [comment]
It seems like you're defining a color palette for your theme like so https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-gradient-presets

but you didn't provide the stylesheet for these gradients in your theme. I think the documentation should be clearer about that (like we do clarify in the Color Palette support)

**Comment by jorgefilipecosta** [comment]
Thank you for bringing this to my attention @youknowriad. I will submit a PR to fix the issue.
