### ISSUE TITLE
Editing linked text popover disappears and has awkward interactions

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19394]
**Describe the bug**
When editing linked text, the popover disappears resulting in confusion. After it disappears, I have to click the linked text twice to view the popover again in edit mode.

A secondary problem resulting from this is that once the popover shows the edit mode for the URL, if I click on another link without dismissing the first popover, the second link shows the same popover URL that can be edited... even if that second link doesn't use the same URL from the other link.

**To reproduce**
1. Add and link a couple different words in Gutenberg.
2. Click on the first link to show the popover.
3. Click to edit that URL.
4. Observe the popover disappear.

**Second problem**
5. Now click two times on the first link to pull up the popover again. 
6. Notice it's now in edit mode.
7. Before clicking anything else, click the second link in the text.
8. Notice the popover for that second link is already in edit mode showing the URL from the first link which doesn't match the URL for this second link.

**Expected behavior**
1. I expected that clicking the edit button, the popover would remain on screen and switch over to edit mode.
2. When clicking away from one popover to view another link, I expected to NOT see the same popover previously opened for the first link. I wanted to see the popover for the second link.

**Screenshots**

![links 2020-01-02 14_49_34](https://user-images.githubusercontent.com/617986/71698422-51316480-2d70-11ea-97b3-409169937fd5.gif)

**Desktop (please complete the following information):**
 - WordPress 5.3.2
 - Firefox 71.0
 - Gutenberg 7.1

**Comment by epiqueras** [comment]
The first part of this issue was solved by #19437.
