### ISSUE TITLE
set a default in template

### ISSUE THREAD

**Issue by pbearne** [WordPress/gutenberg#19402]
**Is your feature request related to a problem? Please describe.**
I am creating templates for CPT's and would to be able to set some default for the editor to start with and then edit as needed 

**Describe the solution you'd like**
I would like to pass a default string via the template parm in the args for register_post_type()
```
'template' => array(
	array(
		 'core/heading',
			array( 
                              'placeholder' => 'Details of Participation',
                              'className' => 'terms-header',
                             **"defult" => "Details of Participation",** 
			),
                     ),
                ),
```

**Describe alternatives you've considered**
If not I guess we will have to fork the blocks we need and set the text that way. :-(

**Comment by Soean** [comment]
@pbearne 
In `core/heading` you can use `'content' => 'Hello World'` to set the default content.

**Comment by pbearne** [comment]
Yes that worked
Does this work with all blocks?
Let's make this a Docs update request

**Comment by Soean** [comment]
You can set all attributes of the block, which are defined in the `block.json` file.

Heading for example has `align`, `content`, `level`,` placeholder`, `textColor` and `customTextColor`. See https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/heading/block.json

**Comment by youknowriad** [comment]
Looks like this was addressed properly.
