### ISSUE TITLE
Found 2 elements with non-unique id #_wpnonce

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19405]
**Describe the bug**
In my Chrome console log I can see a warning message: 
```
[DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) 
<input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"f7ed9b2359">​ 
<input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"d9feda16a6">​
```
The first is associated with the metabox-base-form
the second with the toggle-custom-fields-form. 

**To reproduce**
1. Open Chrome inspector and filter Console message to Warning.
2. Add new post
3. See the Warning

**Expected behavior**
No warning about non-unique id #_wpnonce

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/71770231-369eed00-2f22-11ea-9675-22af2727ceee.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Problem occurs in WordPress 5.3.2 with / without Gutenberg ( 7.1.0)
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by aduth** [comment]
Thanks for the report. This is an issue in core, and not something which can be resolved in the Gutenberg codebase.

There is an existing ticket here. It discusses the issue more broadly with duplicate nonce IDs:

https://core.trac.wordpress.org/ticket/23165

My latest comment there describes the specific pieces of (core) code which cause this warning:

https://core.trac.wordpress.org/ticket/23165#comment:15

**Comment by bobbingwide** [comment]
Thanks for that. I added a comment to the TRAC in response to dealing with a static.
https://core.trac.wordpress.org/timeline?from=2020-01-14T18%3A25%3A49Z&precision=second

**Comment by davidperezgar** [comment]
For us, is causing that the categories are not loading...

<img width="288" alt="Captura de pantalla 2021-03-08 a las 18 43 31" src="https://user-images.githubusercontent.com/10096360/110359866-535f1500-803e-11eb-813a-4319b8b23dc3.png">
