### ISSUE TITLE
Unable to set how many tweets to show in embed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19417]
This would be nice maybe to add as a feature for those embeds that are a stream. There is currently no way to set number to show.

![embed-twitter-nocontrolhowmany](https://user-images.githubusercontent.com/253067/71816365-403b6880-307a-11ea-8a63-6b11fc538c32.png)

**Comment by paaljoachim** [comment]
Hey Tammie.

That sounds like a very useful feature.
I am wondering if @ntsekouras Nik could take a closer look at this.

**Comment by ntsekouras** [comment]
Hey, this is definitely related with this: https://github.com/WordPress/gutenberg/issues/2744#issuecomment-330837395

Interesting feature to have :)

**Comment by mtias** [comment]
Closing in favor of the above to consolidate :)
