### ISSUE TITLE
If a tweet is in excerpt it shows the link url not content

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19418]
Potentially I would argue this should just output the tweet or skip it as what we have right now can cause issues for example in latest posts:

![excerpt-twitter-bug](https://user-images.githubusercontent.com/253067/71816502-b049ee80-307a-11ea-879e-fffce77410a5.png)

**Comment by draganescu** [comment]
Hi @karmatosed is that a generated excerpt of a post which had an embeded tweet? If it's embed then indeed, all embeds should be stripped before generating an excerpt.

**Comment by karmatosed** [comment]
@draganescu this is using the latest posts block.

**Comment by draganescu** [comment]
After some research I learned that the latest posts block does not use the core filterable `get_the_excerpt` which would not have this problem as by default it goes through `wp_strip_all_tags` at some point.

```
$post_excerpt = $post->post_excerpt;
if ( ! ( $post_excerpt ) ) {
	$post_excerpt = $post->post_content;
}
$trimmed_excerpt = esc_html( wp_trim_words( $post_excerpt, $excerpt_length, ' &hellip; ' ) );
```

I will make a PR where the `LatestPosts` block will use the core excerpt generation mechanism, that should fix this embed problem too.

**Comment by draganescu** [comment]
Looking closer, the problem seems to also because the embed block's saving in the page of the URL as a text node.
