### ISSUE TITLE
Datepicker dropdown overlaps

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19415]
Possibly this is related to: https://github.com/WordPress/gutenberg/issues/19414. The dropdown overlaps on longer names for publishing dates.

![datepicker-overlap](https://user-images.githubusercontent.com/253067/71815630-00738180-3078-11ea-8243-9236b43d8507.png)

**Comment by tellthemachines** [comment]
Closing as fixed in latest master:
<img width="294" alt="Screen Shot 2020-01-07 at 11 21 11 am" src="https://user-images.githubusercontent.com/8096000/71858611-fc129b80-313f-11ea-8220-1978057390ea.png">

**Comment by karmatosed** [comment]
It's not in Chrome fixed as of today using Twenty Nineteen:

![image](https://user-images.githubusercontent.com/253067/71904261-b95fbc00-315d-11ea-8adf-80f3275c6609.png)
