### ISSUE TITLE
Instagram profile embed doesn't work

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19419]
It seems like the Instagram embed might be broken:

![image](https://user-images.githubusercontent.com/253067/71816613-1c2c5700-307b-11ea-9cd2-a45ea57d80e7.png)

Profile link I was using: https://www.instagram.com/karmatosed/ (which works)

**Comment by aduth** [comment]
Do you know that this ever worked as expected? Specifically, embedding a _profile_, as opposed to an individual photo/post from Instagram.

From what I can tell, embedding photos still appears to work correctly.

**Comment by karmatosed** [comment]
I thought it did, now you have me considering it might not. Let's move this to enhancement as supporting profiles would make a lot of sense as twitter does.

**Comment by aduth** [comment]
Looking over the Instagram developer documentation, I'm not sure it's something we can support, since it relies on the functionality to be supported by the embed provider (Instagram).

As best I can tell, their oEmbed support is limited to posts.

See: https://www.instagram.com/developer/embedding/

**Comment by karmatosed** [comment]
Hmm, that does feel like this is going to be too difficult then. Let me close this out and thanks for digging into the possibility.
