### ISSUE TITLE
Allow filtering the blocks displayed in the "Continue Writing" control

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1942]
Plugins and themes should be able to customize the list of blocks that appear in the "Continue Writing" control (and potentially whether these blocks are shown on hover or always shown, see https://github.com/WordPress/gutenberg/pull/1941#issuecomment-316208187):

> <img src="https://user-images.githubusercontent.com/227022/28364167-a9d10cc2-6c83-11e7-85fa-0a99dd42559a.png" width="400">

How can we do this?  [JavaScript hooks and filters](https://github.com/WordPress/packages/pull/13):

```js
const blockSlugs = hooks.applyFilters(
    'gutenberg_continue_writing_blocks',
    [ 'core/text', 'core/image' ]
);

**Comment by jasmussen** [comment]
Just noting that in case #3078 gets addressed, which I believe it will, this issue will become obsolete.
