### ISSUE TITLE
How to add google rich snippet to gutenberg block?

### ISSUE THREAD

**Issue by yazdi** [WordPress/gutenberg#19429]
Hi, for example I want to make a recipe block.
I want to add [rich snippet](https://developers.google.com/search/docs/guides/intro-structured-data) in block with JSON-LD format.
I need to add a inline script tag to the content. How I do this?

**Comment by youknowriad** [comment]
Did you try using the Custom HTML block? It should work if you have admin capabilities. 
You can also try using some known SEO plugins that add custom blocks implementing these schemas.

Good luck.
