### ISSUE TITLE
The search input text is a little close to the left side

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19422]
Tested in Chrome using Twenty Nineteen:

![image](https://user-images.githubusercontent.com/253067/71817068-9d381e00-307c-11ea-8509-41e39420720f.png)

**Comment by skorasaurus** [comment]
there's a similar described issue at https://github.com/WordPress/gutenberg/issues/19300

**Comment by talldan** [comment]
Fixed by #19452.
