### ISSUE TITLE
[ Latest Posts ] Post list should have some spacing on grid view

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19421]
The margins are a little tight when you view in grid view the latest posts block:

![postlist-spacing](https://user-images.githubusercontent.com/253067/71817019-6c57e900-307c-11ea-9cc9-1038f877e568.png)

**Comment by epiqueras** [comment]
The margin in-between them is 16px now. Should we increase it further?

**Comment by karmatosed** [comment]
Yes, that would be helpful. I think 20px would work as a start, but let's add the design feedback label to get thoughts.
