### ISSUE TITLE
Input larger than embed button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19420]
On the Instagram embed the input for URL is larger than the embed button:

![image](https://user-images.githubusercontent.com/253067/71816774-98269f00-307b-11ea-8b12-9c6847c78fc7.png)

**Comment by karmatosed** [comment]
Seems Twitter embed also has this:

![image](https://user-images.githubusercontent.com/253067/71830840-835c0280-309f-11ea-8321-d581f8d55f77.png)

I did add max-width 30px to it and it aligned back, however in CSS can't see how this works, it didn't pick it up putting on .components_placeholder__input.

**Comment by ItsJonQ** [comment]
Interesting! I'll take a looksy.

**Comment by ItsJonQ** [comment]
<img width="661" alt="Screen Shot 2020-01-06 at 12 09 44 PM" src="https://user-images.githubusercontent.com/2322354/71834558-7fb78400-307d-11ea-889e-dbcd9497295c.png">

It's happening for all the embeds (at least for me)

**Comment by ItsJonQ** [comment]
Update! It's a CSS issue, `display: flex` related, by the wrapping parent `<form>` element.
It's causing the `input` to be responsively tall.

Working through solutions now. I know what they are :).
It's just picking the least risky one, as I'm unsure of the CSS side effects.
