### ISSUE TITLE
Columns block in column needs some iterating

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19446]
I would suggest where the columns layouts have to stack, considering putting the visuals centre aligned and maybe with some spacing between. Right now it looks like this:

![image](https://user-images.githubusercontent.com/253067/71849452-02fec700-30ca-11ea-9d8f-c4a75f9be46d.png)

**Comment by MDWolinski** [comment]
Issue was discussed in the Design meeting today.

Because the placeholders are left justified, Mark U. was fine maintaining the left justification of the column, however, it was agreed that vertical spacing is needed between the wrapped icons.

**Comment by noahtallen** [comment]
How does this look? https://github.com/WordPress/gutenberg/pull/19494#issuecomment-572323944

**Comment by noahtallen** [comment]
Looks like the PR was merged. Looking much better now!
