### ISSUE TITLE
Block library above another showing through toolbar of block below

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19445]
I was testing columns block and managed to create this:

![image](https://user-images.githubusercontent.com/253067/71849258-88ce4280-30c9-11ea-87c7-527ac702c870.png)

Whilst, it's a bit of a stress case, I would suggest we set a rule potentially of only having one open at a time.

**Comment by karmatosed** [comment]
Whilst #18918 will fix the popover for 'slash command' there is a second issue here of the top block's library peering through.

![image](https://user-images.githubusercontent.com/253067/71915812-71985f00-3174-11ea-8761-28b10528a703.png)

I created this by adding a column block then a paragraph one. I'll update the title.

**Comment by youknowriad** [comment]
Duplicate of #19353
