### ISSUE TITLE
Gutenberg uses wrong url for internal REST API requests

### ISSUE THREAD

**Issue by vavra7** [WordPress/gutenberg#19459]
1) Make clean installation of latest wordpress on **http://some-wp-domain.com**
2) Go to Settings -> General and change field "Site Address (URL)" to value "**http://another-frontend-domain.com**". Hit "Save Changes".
3) Go to Pages -> Sample Page make a random change and hit "Update"
4) ERROR
	reason is that Guttenberg's internal request leads to
	http://another-frontend-domain.com/index.php?rest_route=%2Fwp%2Fv2%2Fpages%2F2&_locale=user
	expected is internal request to
	http://some-wp-domain.com/index.php?rest_route=%2Fwp%2Fv2%2Fpages%2F2&_locale=user

![2020-01-07_12-54](https://user-images.githubusercontent.com/45885390/71894190-dee4c980-314d-11ea-9bb8-8616313893c7.png)
	

By other words: Guttenberg uses for internal REST API requests "siteurl" domain instead of "home" domain

**Comment by youknowriad** [comment]
Hi there!  thanks for opening the issue.

I believe this was already discussed before and that it's the right approach. REST API folks would know more. cc @spacedmonkey @TimothyBJacobs

**Comment by TimothyBJacobs** [comment]
Yeah, Gutenberg is using the WordPress APIs for these things so it is the correct behavior according to core.

A [core trac ticket was created](https://core.trac.wordpress.org/ticket/49146) as well but closed because that is the intended behavior and a filter exists to change it.

**Comment by youknowriad** [comment]
Thanks @TimothyBJacobs

**Comment by isuke01** [comment]
@youknowriad There is more about this issue https://github.com/WordPress/gutenberg/issues/1761
