### ISSUE TITLE
Unifying importing components in documentation 

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#19468]
At the moment there are multiple ways using components is shown in the documentation. In some places object deconstruction is used. In other places the import syntax is used. But there doesn't seem to be any reasoning behind what's used where and I believe it would be more clear if either ore would be used across the board. 

## Deconstruction Syntax
```js
const { MyComponent } = wp.components;
```
- [InspectorControls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inspector-controls)
- [MediaPlaceholder](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/media-placeholder)
- [URLInput](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/url-input)

## Import Syntax 
```js
import { MyComponent } from '@wordpress/cpmponents';
```
- [BlockVerticalAlignmentToolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-vertical-alignment-toolbar)
- [InnerBlocks](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks)
- [MediaUploadProgress](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/media-upload-progress)
- [MediaUpload](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/media-upload)
- [ResponsiveBlockControl](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/responsive-block-control)
- [RichText](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/rich-text)
- [URLPopover](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/url-popover)
-  [Animate](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/animate)
- [Autocomplete](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/autocomplete)
- [BaseControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/base-control)
- [ButtonGroup](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/button-group)
- [Button](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/button)
- [Card](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/card)
- [CheckboxControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/checkbox-control)
- [ClipboardButton](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/clipboard-button)
- [ColorIndicator](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/color-indicator)
- [ColorPalette](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/color-palette)
- [ColorPicker](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/color-picker)
- [CustomSelectControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/custom-select-control)
- [Dashicon](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dashicon)
- [DateTimePicker](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/date-time)
- [DimensionControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dimension-control)
- [Disabled](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/disabled)
- [Draggable](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/draggable)
- [DropZone](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/drop-zone)
- [DropdownMenu](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown-menu)
- [Dropdown](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown)
- [ExternalLink](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/external-link)
- [Focal Point Picker](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/focal-point-picker)
- [Focusable Iframe](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/focusable-iframe)
- [FontSizePicker](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/font-size-picker)
- [FormFileUpload](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/form-file-upload)
- [FormToggle](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/form-toggle)
- [Form Token Field](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/form-token-field)
- [Icon](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/icon)
- [Isolated Event Container](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/isolated-event-container)
- [Keyboard Shortcuts](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/keyboard-shortcuts)
- [MenuGroup](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-group)
- [MenuItem](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-item)
- [MenuItemsChoice](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/menu-items-choice)
- [Modal](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/modal)
- [NavigableContainers](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/navigable-container)
- [Panel](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/panel)
- [Placeholder](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/placeholder)
- [Popover](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/popover)
- [QueryControls](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/query-controls)
- [RadioControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/radio-control)
- [RangeControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/range-control)
- [ResizableBox](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/resizable-box)
- [ResponsiveWrapper](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/responsive-wrapper)
- [Sandbox](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/sandbox)
- [ScrollLock](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/scroll-lock)
- [SelectControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/select-control)
- [Slot Fill](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/slot-fill)
- [Spinner](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/spinner)
- [TabPanel](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/tab-panel)
- [TextControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/text-control)
- [TextHighlight](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/text-highlight)
- [TextareaControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/textarea-control)
- [ToggleControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/toggle-control)
- [Toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/toolbar)
- [Tooltip](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/tooltip)
- [TreeSelect](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/tree-select)

**Comment by mkaz** [comment]
It looks like the three PRs merged above close out this issue.
Please reopen if more is needed.
