### ISSUE TITLE
Table block: pasting content in a table cell: content is always pasted in the last cell

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1946]
To reproduce:
- go in the Gutenberg "New Post" page
- add a table block
- by default it gets two rows and two columns
- write "hello" in the first cell
- select the text
- click in the second cell
- paste with Cmd/Ctrl + V
- the content is pasted in the last cell in the second row
- add a new row to the table
- click on a cell other than the last one
- paste: the content is pasted in the last cell

Note: I can't reproduce consistently in the page with Demo content. It always happen in the New Post page though.

**Comment by karmatosed** [comment]
That's an 'interesting' bug. I can reproduce at will in the new post too.

**Comment by EphoxJames** [comment]
I am having trouble replicating this bug. Does it happen on a specific browser or operating system? How do you go about selecting the text - mouse or keyboard?

**Comment by afercia** [comment]
Can't reproduce any longer. Probably fixed by other recent changes.
