### ISSUE TITLE
Slot / Fill: prefer consistent naming conventions

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1947]
For beginners, like me, it can be hard to get how things work when approaching a new codebase. Some consistency in the naming conventions would certainly help. For example:
```
import { Fill } from 'react-slot-fill';
import { Slot } from 'react-slot-fill';
```

Edit: the above naming are currently used in `VisualEditorBlock`, `Editable`, and `BlockControls`. I'd propose to choose one of them and be a bit more consistent :)

**Comment by aduth** [comment]
Slot and Fill serve different purposes (i.e. a slot may render many fills). Could you clarify the inconsistency?

**Comment by afercia** [comment]
Ah. I admit I haven't got how it works :) Closing.
