### ISSUE TITLE
Grab and Move on Submenu Item in Navigation Block always become a top level item

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19478]
**Describe the bug**
When trying to grab and move a submenu item on the navigation block, it will always become a top level item even if you try to place it back in the submenu.

**To reproduce**
1. Go to a submenu item on a navigation block menu
2. Click the grab/move area (dots between the arrows on the left
3. Try to place it back in its old position
4. Release the click
5. Menu item is moved to the top-level

**Expected behavior**
1. Go to a submenu item on a navigation block menu
2. Click the grab/move area (dots between the arrows on the left
3. Try to place it back in its old position
4. Release the click
5. Menu item is still in the submenu

**Screenshots**
![image](https://user-images.githubusercontent.com/967608/71907827-6fadac00-3132-11ea-8a41-4e308a0ee189.png)

**Desktop**
OS: MacOS Catalina - 10.15.2
Browser: Chrome
Version: Gutenberg 7.2.0-rc.1 & 7.1

**Additional context**
Tested locally with built version of `master` and WordPress Version 5.3.2 with Gutenberg as the only active plugin.

**Comment by jeryj** [comment]
I'm wondering if the drag handle was never supposed to show, as there isn't code I see to handle it. I do see that it's hidden via CSS for the top-level links:

```
.block-editor-block-mover {
	&.is-horizontal {
		.block-editor-block-mover__control-drag-handle {
			display: none;
		}
	}
}
```

I'm still very new to this navigation codebase, so I'm having a hard time tracking down how the mover even ends up taking a sub-item and inserting it as a top-level item. My guess it that it's a default functionality and that it was never actually added as a feature here.

So, I see two ways forwards:
1. Hide the drag mover on the submenu via CSS. This would mean there is no way to move a sub-item to a top-level item. As it stands, you can't move a top-level to sub-item anyways.
2. Build out the functionality to drag move subitems anywhere (and likely top-level too).

For now, I would think 1 with opening an issue as a feature to build out 2.

**Comment by obenland** [comment]
Agreed, let's go with that
