### ISSUE TITLE
Drop downs for text settings too tall

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19472]
This is what I see on paragraph settings in Twenty Twenty:

![image](https://user-images.githubusercontent.com/253067/71903198-7ef51f80-315b-11ea-863e-812e4ca257b2.png)

Here it is in Twenty Nineteen:

![image](https://user-images.githubusercontent.com/253067/71903431-fd51c180-315b-11ea-95f3-94bab6bbd05f.png)

**Comment by ItsJonQ** [comment]
Thanks for reporting this @karmatosed ! I'll take a look at it in a moment 🙇

**Comment by ItsJonQ** [comment]
Update! Found the issue.

The new `FontSizePicker` needs to adjust it's `<Button />` size to small, to match the inputs/buttons it sits next to.

The updated `FontSizePicker` uses `CustomSelectControl` underneath. Will need to update that to accept button modifications :)

https://github.com/WordPress/gutenberg/blob/master/packages/components/src/custom-select-control/index.js

**Comment by karmatosed** [comment]
Oh wow that's some sleuthing! Thanks.
