### ISSUE TITLE
Export `MINUTE_IN_SECONDS`, `HOUR_IN_SECONDS`, etc

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#19496]
### Problem

On the PHP side, plugin developers can use the `MINUTE_IN_SECONDS` and `HOUR_IN_SECONDS` constants provided by `default-constants.php`.

The Date package defines both of those, but only locally, so plugin developers have to create duplicate local constants.

Additionally, Core PHP provides more constants which would be useful to JS plugin developers:

```php
define( 'MINUTE_IN_SECONDS', 60 );
define( 'HOUR_IN_SECONDS', 60 * MINUTE_IN_SECONDS );
define( 'DAY_IN_SECONDS', 24 * HOUR_IN_SECONDS );
define( 'WEEK_IN_SECONDS', 7 * DAY_IN_SECONDS );
define( 'MONTH_IN_SECONDS', 30 * DAY_IN_SECONDS );
define( 'YEAR_IN_SECONDS', 365 * DAY_IN_SECONDS );
```

### Proposed Solution

- [ ] Add the additional constants, for consistency with PHP
- [ ] `export` the `{*}_IN_SECONDS` constants, so that they could be reused.

I personally wouldn't export `{*}_IN_MINUTES` constants, since it's inconsistent with PHP, and could be easily overlooked, leading to subtle bugs. That's not a big deal if others disagree, though.

**Comment by aduth** [comment]
To me it feels like a relatively agreeable / non-offensive proposal, but as with any new API, I consider:

- What's the demonstrated use-case?
- What's the intended scope of the package(s) we consider for these APIs?

I think it's fair to say the `date` package in particular intentionally offers equivalent functionality to many of the same utilities offered through core (PHP), and on that basis alone it could be argued to be justified. It's not entirely clear to me what the full scope of that functionality should include, whether these sorts of constants fall within that, or whether they're better suited elsewhere (or not at all).

One important distinction to note is there is a different time scale between PHP and JavaScript, where timestamps in PHP are measured in _seconds_ from epoch ([see `time`](https://www.php.net/manual/en/function.time.php)) vs. in JavaScript where it is measured in _milliseconds_ ([see `Date.now`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)). These constants seem especially optimized for working with seconds-based timestamps. For that reason, I might question whether these constants provide the same usefulness, whether other constants would be needed, or whether it undermines the entire value proposition. If the primary benefit is that including these constants would provide a path for one to transition their existing PHP knowledge, is it still valuable if the developer must then do the same sorts of time conversions that these constants are meant to abstract in the first place? Or at worst, does it set up a developer for failure if we imply that the knowledge can transfer with these as direct parallels, if they're not wary of the caveats?

(cc @momotofu re: proposed additions at #19760)

**Comment by momotofu** [comment]
That’s a good point @aduth We are implying that the constants would be measured in seconds instead of milliseconds since the Date package delivers PHP-like dates. Maybe we could explicitly show that caveat, by adding more detail to the package documentation. (I.E., time units are measured in seconds from epoch).

**Comment by aduth** [comment]
For the reasons mentioned in https://github.com/WordPress/gutenberg/issues/19496#issuecomment-576412685, I don't think this would make for a good addition at this time.
