### ISSUE TITLE
Comparing the TinyMCE experience to Gutenberg

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1950]
The TinyMCE editing experience:

Focus on flow of content.
- Title is separate from content.
- No visible borders between content.
- One content flow.

![screen shot 2017-07-19 at 22 24 33](https://user-images.githubusercontent.com/5323259/28387903-234be386-6cd1-11e7-8fbe-ec2eceb26036.png)

---
The Gutenberg editing experience (The mouse is hovering over the heading so the outline is visible):

Focus on editing with blocks.
- Editing is much more focused directly into each block.
- Visible borders between blocks. Creating a separation of the text flow compared to TinyMCE.

![screen shot 2017-07-19 at 22 24 43](https://user-images.githubusercontent.com/5323259/28387921-33861cd0-6cd1-11e7-8460-95701fde2ad5.png)

IF we were going to Gutenfy the TinyMCE it could perhaps contain something similar to these wireframes. 
![gutenfi-tinymce1](https://user-images.githubusercontent.com/5323259/28389038-e1945258-6cd4-11e7-8db1-ff3a466b8c12.jpg)

The heading is in focus a down arrow shows up on the left side. Showing one can push it downward. (Similar to Gutenberg).

![gutenfy-tinymce2](https://user-images.githubusercontent.com/5323259/28389116-2c6d16f2-6cd5-11e7-8161-570930d071ac.jpg)

Here the mouse is hover the heading showing a border around it.... Hmm not sure I like that..
It can create a clear differentiation between sections such as heading, paragraph etc.

The question is how can we add some of the features that are added to Gutenberg into the TinyMCE to make it even better? Softening the transition to Gutenberg. Having additional similarities without adding blocks to TinyMCE would hopefully also benefit the existing creation process.
 
A time will come when the user can choose between using Gutenberg or the default TinyMCE editor. Perhaps as a toggle in settings.

**Comment by karmatosed** [comment]
I am not sure that adding to TinyMCE is right to say here over a core ticket, I'm also not sure that it's the right move to do with the merge proposal looming the end of this year.

For now going to close this ticket as there are no actionables from it. It's worth noting comparing the two will become even more distance as Gutenberg grows, but we're learning lessons along the way.
