### ISSUE TITLE
I wish Gutenberg has following features

### ISSUE THREAD

**Issue by kevIN-kovaDIA** [WordPress/gutenberg#19509]
1) countdown timer block for an event, website launch, marriage date, product release, movie launch-related coming soon page (currently, i am using a plugin called "Blocks Animation: CSS Animations for Gutenberg Blocks" for the same)

2) timeline block to showcase one's journey, milestone, road map. 

3) image link option in the gallery (as recently added in media + text)

4) motion animation block. (currently, i am using a plugin called "Blocks Animation: CSS Animations for Gutenberg Blocks" for the same)

5) directly import images with creative commons licence from directories such as pixabay, mediawiki, etc. (currently I am using "ImageInject" WordPress plugin for the same.)

6) adding feature image from direct URL (same as in Image).

7) emoji block, because emoji is lifeline nowadays. (Right now, i am using plugin called "Emoji Autocomplete Gutenberg" for the same)

**Comment by youknowriad** [comment]
Thanks for the issue, the best way forward is to split this into multiple issues so each one could be addressed separately.

Quick answer/opinion.

1, 2, 4, 5 are great suggestions but look like plugin territory for me (rely on third-party providers, or maybe a use case that is not common to all WordPress users).

3. Good proposal, I believe there's a proposal to use the image block for gallery images (this would solve the issue)

6. This is better raised as a Core trac ticket https://core.trac.wordpress.org/ as it's not possible server-side.

7. I believe this should be an OS keyboard (like MacOS emoji keyboard),  in the meantime as other OS implement it, a plugin can be used as well.

**Comment by youknowriad** [comment]
I'm closing as non-actionable as is but please feel free to continue in separate issues.
