### ISSUE TITLE
Disabling the Welcome Modal?

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#19512]
Hey this is just a question, but is there filter to disable the welcome modal? We are testing the plugin update for our multisite instance, and the way it is now that welcome modal is gonna pop up and confuse all 1500 plus of our users once we update the plugin.

**Comment by aduth** [comment]
I have similar need for this in my plugin [Disable NUX](https://github.com/aduth/wp-disable-nux), which did something like this for disabling the previous incarnation of the new user experience tips.

It seems the [implementation there](https://github.com/aduth/wp-disable-nux/blob/0fda553460b1c9967d5af410ebe7121ef9f20b90/index.php#L15) is no longer valid. Looking at #18981 as a reference for migrating to the new implementation, I might expect something like the following could work:

```php
wp_add_inline_script( 'wp-edit-post', 'wp.data.select( "core/edit-post" ).isFeatureActive( "welcomeGuide" ) && wp.data.dispatch( "core/edit-post" ).toggleFeature( "welcomeGuide" )' );
```

I haven't tested this yet. Running the code directly in my browser, it appears to have the intended effect.

Let me know if this works for you. I'm going to try it in my plugin as well. I'll close the issue preemptively, but it can be reopened if it continues to be an issue.

cc @noisysocks

**Comment by GraemeFulton** [comment]
```
registerPlugin('disable-welcome-guide', {
       render: function () {
        //disable welcome guide
        wp.data.select( "core/edit-post" ).isFeatureActive( "welcomeGuide" ) && wp.data.dispatch( "core/edit-post" ).toggleFeature( "welcomeGuide" )
    }
})
```
Worked for me! I have it defined inside a `registerPlugin` included in my theme's JS 👍🏽

**Comment by pwkip** [comment]
for those who are just looking for a quick plugin to turn off the annoyance: https://wordpress.org/plugins/disable-welcome-messages-and-tips/
