### ISSUE TITLE
inline image width pop-up 'wanders' down page in Safari

### ISSUE THREAD

**Issue by ugyballoons** [WordPress/gutenberg#19519]
Editing the value in an inline image 'width' pop-up causes the pop-up to 'wander' down the page in Safari.

In a Header box, add an inline image
Click on image to reveal 'width' pop-up
Alter value in the pop-up via widget or keyboard

<img width="385" alt="Screen Shot 2020-01-08 at 23 11 32" src="https://user-images.githubusercontent.com/624222/72024033-5577e900-326c-11ea-8056-241d449feb3b.png">

The pop-up wanders off the page

<img width="475" alt="Screen Shot 2020-01-08 at 23 11 49" src="https://user-images.githubusercontent.com/624222/72024136-9f60cf00-326c-11ea-9a51-38558a73dfc6.png">

 - MacOS 10.12.6
 - Safari
 - 12.1.2

Using Gutenberg in WordPress 5.4-alpha-47053

**Comment by youknowriad** [comment]
Can you reproduce this issue with Gutenberg 7.2 (plugin installed and activated), I believe this was fixed.

**Comment by ugyballoons** [comment]
Yes, still happening.

**Comment by youknowriad** [comment]
Thanks for checking :)

**Comment by ugyballoons** [comment]
No problem. I'm happy to help :)

**Comment by paaljoachim** [comment]
I just noticed the same error in Gutenberg 7.4 which I just updated and went back to recheck to see if the error remains.

I call this the Pacman meets Gutenberg or perhaps it is Pong meets Gutenberg  - grin -

![Inline-image-Width-Gutenberg](https://user-images.githubusercontent.com/5323259/73881690-120b9d00-4861-11ea-814b-a2cf0a6347dc.gif)
