### ISSUE TITLE
Navigation: Misaligned left border between menu item and block controls

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19510]
**Describe the bug**
There's a 1px misalignment between the heavy left border on the menu item block controls and the menu item itself.

**To reproduce**
1. Click on a menu item in the navigation block
2. See how the left border between the block controls and the menu item are not aligned

**Expected behavior**
The border on the block controls and the menu item will be aligned.

**Screenshots**
<img width="258" alt="Misaligned left border on navigation item block" src="https://user-images.githubusercontent.com/967608/72001368-f33acc00-320a-11ea-9367-570eac4b3c6f.png">

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - Version  79.0.3945.88

**Additional context**
Tested on Gutenberg v7.2.0

**Comment by tellthemachines** [comment]
I can reproduce this on latest master. Changing `left` to `14px` on `[data-type="core/navigation-link"] .block-editor-block-toolbar` in `navigation-link/editor.scss` seems to fix it.
