### ISSUE TITLE
Improve context to initial suggestions on Nav Link Block

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19513]
In https://github.com/WordPress/gutenberg/pull/19458 we are introducing a list of the most recently created pages to the link inserter UI:

<img width="419" alt="Screen Shot 2020-01-08 at 10 19 14 AM" src="https://user-images.githubusercontent.com/1464705/72006588-d3080e80-3204-11ea-913a-bc834b695119.png">

I think this UI could use some context with an indicative title to say that "these are your most recently created pages". Currently there's a lack of context that makes this feel slightly odd as a user. It takes me a few seconds to adjust and think about what these pages represent (there is also no call to action on items but we can deal with that later).

Here's a suggestion. It would make this UI more consistent with the block inserter UI and allow the introduction of a title to give context:

<img width="1811" alt="Screen Shot 2020-01-08 at 10 34 26 AM" src="https://user-images.githubusercontent.com/1464705/72006688-06e33400-3205-11ea-9b2e-0f7657addd23.png">

I think these tweaks can also help with https://github.com/WordPress/gutenberg/issues/18425 where URLs typed into the search field always show first, and can then be visually separated:

<img width="483" alt="Screen Shot 2020-01-08 at 10 47 35 AM" src="https://user-images.githubusercontent.com/1464705/72006776-2e3a0100-3205-11ea-9246-7cb56f82922e.png">

Adding context with titles I think helps reduce the thinking time in an interface like this. It's used elsewhere in Gutenberg in the form of accordion menus (I realize this follows the same pattern but without the expand/collapse), and it's also common place in other UIs such as iOS.

Interested in thoughts on the changes.

/cc @shaunandrews

**Comment by jeryj** [comment]
I especially like the URL at the top, as otherwise you have to scroll down to find it or know to press `enter`.

I think a title to mention the context on the list makes sense. Two questions on this:

1. Should the title "Recently Create Pages" contain "Pages" or be more generic, like "Latest"? My thoughts are that they 1. May not have created it recently (could be from a few months ago) and 2. may not always be a Page if custom post types or archives end up being an option.
2. What should the title be, if anything, when a search happens?

**Comment by apeatling** [comment]
> 1. May not have created it recently (could be from a few months ago) and 2. may not always be a Page if custom post types or archives end up being an option.

I think in the current implementation it is only pages that would show in the "recent" section? I'm basing this entirely on scanning the code and testing the PR, but if it's more than that then definitely the title should be something different.

**Comment by shaunandrews** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/191598/72096948-44b98880-32e9-11ea-8cee-be6ad9a105bd.png">

I tweaked it removing the border and reducing the font-weight. I also changed it the heading to be more generic, but (hopefully) equally informative.

I don't think trying to match the pattern/styling of the accordions in the Block Inserter is the right page. This isn't an accordion, and shouldn't look like one.

**Comment by apeatling** [comment]
This works for me, my main concern is the lack of context when first seeing the default items shown.

**Comment by karmatosed** [comment]
I do kind of prefer it with the border for visual clarity. I wonder if the same clarity could be brought in with just some extra space?

**Comment by getdave** [comment]
> I think in the current implementation it is only pages ordered by creation date that would show in the "recent" section? I'm basing this entirely on scanning the code and testing the PR, but if it's more than that then definitely the title should be something different

@shaunandrews is actually correct in that the code is based on _modified_ date and not _created_ date. If you feel that's not what people would expect then please do let me know @apeatling.

Note also that as things stand if any results are returned due to a user typing into the search box the "recent pages" initial suggestions are removed. They only appear when there is no current search/search result. 

Minor: my gut reaction was that`Recently updated` didn't stand out enough to me [here](https://github.com/WordPress/gutenberg/issues/19513#issuecomment-572708050). I wonder whether a time-related icon next to the text might help provide additional clarity and context?

**Comment by mtias** [comment]
Could the URL protocol be dropped?

**Comment by mtias** [comment]
Also I think before it was discussed using only the path + slug since the base domain was superfluous for your own content.

**Comment by getdave** [comment]
> Could the URL protocol be dropped?

For Entities such as Pages - yes. So for initial suggestions, we can ditch it as they are all Pages.

For direct entry URLs we need the protocol as some may be `http` or `https` and we need to be explicit about the link.

> Also I think before it was discussed using only the path + slug since the base domain was superfluous for your own content.

👍 As above.

**Comment by mtias** [comment]
Yes, I only mean for the content that appears in this "recently updated".

**Comment by getdave** [comment]
![Screen Capture on 2020-01-10 at 17-17-15](https://user-images.githubusercontent.com/444434/72172490-27f68100-33cd-11ea-8b16-00a73350ecfd.gif)

Here's where I got with this working locally. Appreciate it's not 1:1 with @shaunandrews's design yet but it's in the right direction.

Waiting on https://github.com/WordPress/gutenberg/pull/19458 to merge and then I'll push up the code.

**Comment by getdave** [comment]
@apeatling I've renamed this Issue to focus on the main issue of adding the context to the initial suggestions. Other suggestions made within this thread have been spun off into new issues.

This is ready to test if you have time today.

**Comment by apeatling** [comment]
Looks like it was already merged! 🎉
