### ISSUE TITLE
Gutenberg is not normalizing if text is pasted from within Gutenberg

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/gutenberg#19533]
**Describe the bug**
If NFD text (decomposed characters) is pasted in the editor it gets normalized on paste via JS/ES6.

Since this issue/PR for details: 
https://github.com/WordPress/gutenberg/issues/433
https://github.com/WordPress/gutenberg/pull/6880

But if I have NFD text in the editor from before Gutenberg and copy&paste it from within Gutenberg, it does not normalize.

**To reproduce**
1. Go to https://core.trac.wordpress.org/ticket/30130 and download the PDF
2. Open the PDF in Preview on a Mac
3. Copy the content to the editor (in Chrome or Firefox, NOT Safari)
4. Paste it in classic WP editor (no normalization - which is correct)
5. Switch to Gutenberg
6. Copy the text inserted in 4. and paste it in a new paragraph
7. No normalization. **Not** correct this time.
(8. You can copy and paste direct from the PDF to Gutenberg, which is working correctly.)

**Expected behavior**
I expected the normalization to happen all the time, even if copy&paste from within Gutenberg.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6, but should happen on all Macs (tested up to 10.14)
 - Browser: Paste in Firefox/Chrome (Safari is normalizing all inputs)

**Smartphone (please complete the following information):**
 This could not be reproduced in iOS.

**Comment by ellatrix** [comment]
How did the text end up not being normalised? How was it entered into Gutenberg?

**Comment by Zodiac1978** [comment]
> How did the text end up not being normalised? How was it entered into Gutenberg?

1. Entered before Gutenberg was active or
2. Entered in Classic Editor (because Gutenberg is configured as optional) or
3. copied from title, because no normalization there (see #19533)

**Comment by ellatrix** [comment]
Ok, we can add normalisation to the raw handler in general, which should fix all cases.

**Comment by rickmgithub** [comment]
This looks like another example of this on #3489711-zd

When a "&" is added to the title, as soon as the post is updated, it becomes "&amp;"

I tried this on a test site and it occurred with 2 different themes - 2015 and 2020

**Comment by ellatrix** [comment]
Could you share the logged messages in the console after pasting the text from the classic editor into Gutenberg?

**Comment by Zodiac1978** [comment]
@ellatrix Is this question for me? Can't test anymore, because http://gutenberg.run/19559 is not working anymore. Showing "Invalid pull request".

**Comment by ellatrix** [comment]
I'll close the PR. I'd love to get some [more information](https://github.com/WordPress/gutenberg/issues/19533#issuecomment-794423818) here.

**Comment by Zodiac1978** [comment]
I would like to help you here @ellatrix, but as I mentioned already http://gutenberg.run/19559 is not working anymore, so I can't provide the necessary information.

Or do you mean to paste the text on a normal WP 5.7 install and just show the logged messages there?

**Comment by ellatrix** [comment]
Yes, just a normal install with the latest GB version

**Comment by Zodiac1978** [comment]
Tried in WordPress 5.8-alpha-50533 and got this in the console:
```
JQMIGRATE: Migrate is installed, version 3.3.2 load-scripts.php:5:709
Received HTML:

 <empty string> editor.min.js:12:144424
Received plain text:

 Fünf gäbe schön editor.min.js:12:144467
Processed inline HTML:

 Fünf gäbe schön blocks.min.js:3:143684
Received HTML:

 <empty string> rich-text.min.js:2:45018
Received plain text:

 Fünf gäbe schön rich-text.min.js:2:45061
Processed inline HTML:

 Fünf gäbe schön
```
Not sure if this is just fixed locally in my dev environment or is this normalized on save?

**Comment by ellatrix** [comment]
Is it now normalising on paste or not? :) I can't tell from the above.

**Comment by Zodiac1978** [comment]
No, it is not normalizing on paste in the backend, but title and content are normalized in the frontend. Going back to the backend it is still not normalized. Therefore internal search still broken.

**Comment by ellatrix** [comment]
I copied the text you pasted above and `'Fünf gäbe schön' === 'Fünf gäbe schön'.normalize() => true`.

**Comment by ellatrix** [comment]
Anything pasted into Gutenberg is normalized except if it comes from within Gutenberg (copy pasting blocks or rich text within Gutenberg).

**Comment by Zodiac1978** [comment]
> I copied the text you pasted above
You need to copy from the PDF provided in https://core.trac.wordpress.org/ticket/30130 on a Mac with a Non-Safari Browser (opened in Preview for example).

https://core.trac.wordpress.org/attachment/ticket/30130/copy-paste-test.pdf

**Comment by ellatrix** [comment]
I tried that.

```
Received HTML:

 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title></title>
	</head>
	<body>
		<div class="page" title="Page 1">
			<div class="layoutArea">
				<div class="column">
					<p><span style="font-size: 12.000000pt; font-family: 'Abel'">Fünf
gäbe
schön
</span></p>
				</div>
			</div>
		</div>
	</body>
</html>
index.js:373 Received plain text:

 Fünf gäbe schön
paste-handler.js:208 Processed HTML piece:

 <p>Fünf gäbe schön</p>
```

The input is not normalised, but the output is. I'm not sure how to reproduce the case. Should I first paste it in the classic editor, then copy it again and paste into Gutenberg?

**Comment by Zodiac1978** [comment]
> The input is not normalised, but the output is.

Then you have reproduced the problem or am I missing something?

**Comment by Zodiac1978** [comment]
I have recorded this to show the problem:
![normalize-bug](https://user-images.githubusercontent.com/870475/111476766-c0556780-872e-11eb-9de9-a66e27e17c36.gif)

I am just pasting the content from the PDF (from Preview) and you see the broken title in Gutenberg. My browser extension is showing that the proofreading is failing (red underline) and using backspace is removing the diaresis (points above the letter), but not the letter "o" in this case as these are two letters.

**Comment by ellatrix** [comment]
I fail to reproduce this in both Chrome and Firefox on MacOS. I copy the text and paste it in the title and the text is normalised. I checked the console and it is correct. Backspace removes the whole letter ö. Can anyone else reproduce this?

**Comment by Zodiac1978** [comment]
I mixed this ticket up with https://github.com/WordPress/gutenberg/issues/14178, so I recorded another one.

As the title is not normalized copying from it is not normalized:

> except if it comes from within Gutenberg

![normalize-bug-copypaste-from-title](https://user-images.githubusercontent.com/870475/111529460-79816500-8762-11eb-8bb6-5323fe9e6d78.gif)

This is the problem mentioned in the first place.

If this does not happen for you, can you post your mac OS version? I am still on Mojave (10.14.6). Maybe this is fixed on a later version?

**Comment by ellatrix** [comment]
How do I end up with non normalised text in the title?

**Comment by ellatrix** [comment]
I have macOS Big Sur but I doubt it makes a difference.

**Comment by Zodiac1978** [comment]
> How do I end up with non normalised text in the title?

I don't know which information you need. I am on macOS Mojave 10.14.6 and was testing in FF 86. But I could reproduce this in other browsers as well. Need to double check, but can provide this info if necessary.

I have shown what I have done: Open provided PDF in Preview, copy & paste in WP post title and content and end up with non-normalized text in the title.

> I have macOS Big Sur but I doubt it makes a difference.

If you have any idea which other difference *is* relevant, please ask. After years of explaining this issue on different places I am tired ...

**Comment by Zodiac1978** [comment]
Testing this on WordPress 6.1-alpha-54269 it looks like this is now working and the title is normalized to.

Therefore I close this issue. If anyone is still seeing this behavior, please re-open. Thank you!
