### ISSUE TITLE
Gutenberg

### ISSUE THREAD

**Issue by helenpercival** [WordPress/gutenberg#19542]
Gutenberg v 6.3 appears to be breaking my website since the update to wordpress 5.3.2. and I've received an email that starts 

"Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email. In this case, WordPress caught an error with one of your plugins, Gutenberg........ Error Details

An error of type E_ERROR was caused in line 14 of the file /home/cluster-sites/7/t/thegreenewell.co.uk/public_html/wp-content/plugins/gutenberg/lib/class-wp-block-styles-registry.php. Error message: Cannot declare class WP_Block_Styles_Registry, because the name is already in use." 

I've updated the gutenberg plugin to version 7.2. Does anyone know if this fixes the problem and if not how I can fix the issue. 

Thanks

**Comment by gziolo** [comment]
Yes, this is a known issue that was fixed in Gutenberg 6.5 or 6.6. In addition, it’s all good since with WordPress 5.3.x you shouldn’t be using the version of the plugin older than the one bundled in WordPress core. Thanks for opening this issue.
