### ISSUE TITLE
Block mover buttons z-index higher than toolbar z-index

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1954]
When scrolling the page, ant the "block mover" buttons are displayed, they're in top if the toolbar:

![screen shot 2017-07-20 at 11 20 26](https://user-images.githubusercontent.com/1682452/28410403-e34dd786-6d3d-11e7-80c7-6ae81e925f51.png)

**Comment by timmyc** [comment]
Duplicate of #1860 and fixed in #2001
