### ISSUE TITLE
Navigation-link block - inline image misbehaving

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19557]
**Describe the bug**
I tried to add an inline image to a Navigation-link.
Quite a few strange things happened. 
1. The insert link dialog remained visible while I was selecting the inline image.
2. When I tried to size the inline image the dialog _walked off the screen._
3. The front end display just showed the HTML.

**To reproduce**
1. Insert a Navigation block ( core/navigation )
2. Create empty
3. Add link...
4. Search for content and choose anything.
5. Choose Inline image toolbar icon
6. Insert image
7. Click on image to set width
8. Click in the field then choose the up or down arrow
9. The popup dialog wanders off the screen
10. Save anyway
11. Publish and view

Note: some actions cause  the dialog to re-appear and start wandering again.

**Expected behavior**
Inline image to appear in the Navigation link at the size I want to set it.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/72152115-f916e580-33a1-11ea-86f0-74a4f1d329a9.png)
![image](https://user-images.githubusercontent.com/2474435/72152510-22844100-33a3-11ea-86b6-0144f6dacd59.png)
![image](https://user-images.githubusercontent.com/2474435/72152529-2ca63f80-33a3-11ea-9d02-b5dae578c9d3.png)

See also
https://blocks.wp.a2z/block_example/core-navigation-link-with-inline-image/
https://youtu.be/sHlNUZr-9-E

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Gutenberg 7.2.0

**Comment by bobbingwide** [comment]
I just tested what happened with an Inline image in a Button in a Buttons block. 
Same wandering as shown in the YouTube video.

### Workaround
edit the image size using the code editor.

**Comment by jasmussen** [comment]
Thanks for the ticket. I believe this has been fixed with the navigation item setup state:

![nav](https://user-images.githubusercontent.com/1204802/123914075-48c6e380-d97f-11eb-927c-6674fd1cfbb0.gif)

Closing as such, let me know if this was in error.
