### ISSUE TITLE
Buttons block button - HTML not stripped from title attribute

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19553]
**Describe the bug**
When the title of a post is styled with HTML tags the title attribute of the link produced for the Button block is displayed with the HTML showing. 

**To reproduce**
1. Create a post where the title contains HTML such as a span
2. Add a Button
3. Enter the link text
4. Click to insert the link
5. Choose the post created in 1.
6. Notice the escaped HTML in the link 
7. Save and view
8. Hover over the button

**Expected behavior**
Either the HTML should be stripped from the title attribute

Or the title tag should not be shown at all. 
See https://github.com/WordPress/gutenberg/issues/8315

**Screenshots**
![button-block-escaped-HTML-in-link](https://user-images.githubusercontent.com/2474435/72142701-27d69100-338d-11ea-8e32-b18cdc33aa99.jpg)

![buttons-block-two-problems](https://user-images.githubusercontent.com/2474435/72142299-4ab47580-338c-11ea-9bf8-d86a9c6b5a8f.jpg)

For examples see https://blocks.wp.a2z/block/buttons-core-buttons/ and
https://blocks.wp-a2z.org/block/button-core-button/

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 79.0.3945.88 

**Smartphone (please complete the following information):**

**Additional context**
Gutenberg 7.2.0

**Comment by youknowriad** [comment]
cc @getdave

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7.1. Twenty Twenty One. Gutenberg plugin 10.4.1

Added a post with the site title: `<span>a title</span>`

![Screen Shot 2021-04-22 at 22 16 01](https://user-images.githubusercontent.com/5323259/115779509-5fb5ec00-a3b8-11eb-93ba-cbc1c5ff5470.png)


Added another post with a button. Linked to the above post title post. I noticed the span in the link before selecting the post, but it was not visible when the link was added.

![Screen Shot 2021-04-22 at 22 17 11](https://user-images.githubusercontent.com/5323259/115779644-883de600-a3b8-11eb-8338-ca1b00718083.png)


![Screen Shot 2021-04-22 at 22 12 58](https://user-images.githubusercontent.com/5323259/115779198-f504b080-a3b7-11eb-891c-94a12cf02c08.png)

Saved as draft and previewed the frontend. Hovered over the button.

![Screen Shot 2021-04-22 at 22 14 30](https://user-images.githubusercontent.com/5323259/115779328-21b8c800-a3b8-11eb-8714-33c79aabebe3.png)

I would say that this issue has been fixed.

**Comment by paaljoachim** [comment]
Closing issue. If something was missed the issue can always be reopened.

**Comment by bobbingwide** [comment]
- In the editor I no longer see the markup in the link.
- It would appear that the button block no longer creates a `title` attribute for the link
- But editing an existing button block's link does not delete the title attribute.

Workaround: Delete the button and add a new one or edit the HTML.
Didn't expect this though. What's the link dialog doing where it is?
![image](https://user-images.githubusercontent.com/2474435/115785595-93dcdd00-a3b7-11eb-9516-268b8ad3168b.png)
