### ISSUE TITLE
Navigation block: incorrect mover direction in top toolbar

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#19565]
<img width="364" alt="Screenshot 2020-01-10 at 16 46 45" src="https://user-images.githubusercontent.com/4710635/72166030-cb916280-33c8-11ea-8f6b-2f0bcaa3e5fd.png">

**Comment by getdave** [comment]
> That doesn’t work well for the top toolbar though

Can you define top toolbar? Is it the Block that is using/rendering `<InnerBlocks>`?

**Comment by draganescu** [comment]
How did you get this result @ellatrix ? For me the movers show correctly in the navigation block :)

<img width="692" alt="Screenshot 2020-01-11 at 14 12 29" src="https://user-images.githubusercontent.com/107534/72204050-77e05100-347c-11ea-9786-b9f4ac2c4eac.png">

**Comment by draganescu** [comment]
Oh nevermind, I see this is now closed in #19574

**Comment by ellatrix** [comment]
@draganescu The contextual toolbar was correct, but the top toolbar wasn't (if you enable the top toolbar).
