### ISSUE TITLE
Text block: link editor should have "Open in new window" option

### ISSUE THREAD

**Issue by lkraav** [WordPress/gutenberg#1956]
Not sure if part of #1670, but `target="_blank"` option would be useful to have.

**Comment by iseulde** [comment]
This has been discussed many times for WordPress core, and I don't think we plan to bring this back. See https://core.trac.wordpress.org/ticket/36226, https://make.wordpress.org/core/2016/03/28/the-editor-in-wordpress-4-5/#comment-29560, etc.

**Comment by lkraav** [comment]
I have probably triple digit number of core tickets starred... and yet 36226 wasn't one of them. Thanks :)

**Comment by lkraav** [comment]
Looks like #2204 just went and did it anyway *toot*
