### ISSUE TITLE
Block quote alignment now working

### ISSUE THREAD

**Issue by rstarweb** [WordPress/gutenberg#19563]
**Describe the bug**
Quote block is set to left align and is showing center aligned. Examples on: https://www.judithstarkston.com/hand-of-fire/

**To reproduce**
Add a block quote, select left align, and it remains center aligned in the editor and rendered.  To be perfectly clear, this started when I shifted from ThemeIsle Amadeus to ThemeIsle Neve.

**Expected behavior**
I would expect the text to left align or right align when I select that

**Screenshots**
![image](https://user-images.githubusercontent.com/46076905/72162259-dde6ae80-337e-11ea-8d1c-61327852f023.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
That's because you have a "text-align: center" applied to all blockquotes automatically by your theme CSS

<img width="311" alt="Capture d’écran 2020-01-13 à 2 03 59 PM" src="https://user-images.githubusercontent.com/272444/72258152-a2addf00-360d-11ea-83d8-43af2809c574.png">

Consider removing that style from your theme.

**Comment by rstarweb** [comment]
ThemeIsle says it's a Gutenberg problem...

**Comment by youknowriad** [comment]
Well can you direct them to this issue so I can explain to them properly?

**Comment by youknowriad** [comment]
In your post, you didn't set any explicit alignment which means it's "left" aligned (as this is the default in HTML) while your theme forces all blockquotes with no explicit alignment to be centered.

There are two options:

 - Your theme should provide editor styles to force blockquotes to be centered by default in the  editor that way they look like the fronted.

 - Or your theme should remove the opinionated alignment style from its CSS.

**Comment by rstarweb** [comment]
Yes, thank you much.  I will reference ThemeIsle support to this post.  I am having a similar problem with their  menu alignment and It's likely the same reason..
