### ISSUE TITLE
No drag handles on blocks inside groups

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#19585]
No drag handles on blocks inside groups, even if there are multiple blocks inside the group.

2020 theme, create 2 paragraphs, see the drag handle on both.
Put one block inside a group, see the group has a handle, but the paragraph inside doesn't.
Create a second paragraph inside the group, still no handle on either paragraph.

If this is expected behavior, it is not mentioned in the 7.2 change log, unless I miss it. I certainly might have.

Windows 10
Edge BETA
Gutenberg 7.2

![Untitled-1](https://user-images.githubusercontent.com/37098565/72223568-462fbe80-353e-11ea-8ba0-44223988a617.png)

**Comment by youknowriad** [comment]
@jorgefilipecosta @getdave any idea why the movers and the block drag handle are not visible for blocks inside a Group block?

**Comment by jorgefilipecosta** [comment]
Fixed on https://github.com/WordPress/gutenberg/pull/19640.
