### ISSUE TITLE
Selecting text can be difficult

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#19587]
Not sure if this is just me, can anyone replicate this?

Selecting text inside paragraphs, headings etc, as well as inside input elements in the sidebar. 

Essentially, if you click and drag to select any text, and mouseup outside of the text area, focus will be lost. Once focus is lost, keyboard shortcuts affect the entire document. Ctrl-A selects everything and scrolls you to the top, del deletes everything, etc

One of the worst culprits is the hyperlink tool. This has only been happening in recent versions. Click on an existing hyperlink, click the edit hyperlink button, the box disappears. This might be a separate issue.

This is infuriating for a developer, so I can only imaging how the average user feels.

Windows 10
Edge BETA
Gutenberg 7.1

**Comment by youknowriad** [comment]
Did you try Gutenberg 7.2? I think this is fixed there?

**Comment by joshm33333** [comment]
Tested in 7.2, it's fixed in paragraph and headings, but not in sidebar controls.
For example, on item I tried was image alt text. Seems to affect all textareas and inputs

Also the link issue still exists as well. When you click edit url, the dialog disappears.

Both of these are purely cosmetic issues. I happy to see progress has been made.

**Comment by youknowriad** [comment]
Would you mind sharing a screenshot or something that explains better because I'm not sure I understand exactly what you're seeing. (It could be that everything is working fine for me)

Also, I'm not able to reproduce the link issue personally, so it could potentially be a plugin conflict.

**Comment by joshm33333** [comment]
You are absolutely right, it was a plugin issue
Properly tested and all of these issues are resolved in 7.2! Thank you!
