### ISSUE TITLE
Focus is lost when tabbing from toolbar back to block.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#19591]
GIF:

![focus](https://user-images.githubusercontent.com/1204802/72247513-535bb480-35f5-11ea-9215-8c9e7b7f7dc2.gif)

In this GIF, I have a title and a paragraph:

- Click the paragraph
- Press Shift + Tab twice to enter the block toolbar
- Press Tab twice

Expected result: I'm back to editing text.

Actual result: focus appears to land on the canvas which then redirects it to the Title.

I can reproduce this consistently in Chrome 79.0.3945.117 on MacOS Mojave 10.14.6.

**Comment by ellatrix** [comment]
Already discussed it with @jasmussen, but I'm unable to reproduce it. Would be nice if someone could confirm the issue.

**Comment by joshm33333** [comment]
I don't have this issue either

Tested in 7.1 and 7.2
Windows 10
Edge BETA (runs on the same engine as chrome)

**Comment by ellatrix** [comment]
Note that it should be tested with `master`.

**Comment by jasmussen** [comment]
Not entirely sure this is related, but I'm seeing the following console error.

![focus](https://user-images.githubusercontent.com/1204802/72340446-8458e980-36c8-11ea-8f3e-65590a96cdb4.gif)

**Comment by ellatrix** [comment]
@jasmussen Sounds like the error is related. Does #19621 fix the issue?
