### ISSUE TITLE
Color Picker Format Toggle Icon uses a Dropdown/Accordion Arrow

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19608]
On the color picker, the button to toggle between formats uses a down chevron arrow. This is the same arrow used by accordions and dropdown options.

The icon suggests that it does something different than it actually does (toggles between color types). Is there a different icon that would better fit? Possibly something that suggests changing the format type, like the block switcher icon?

**To reproduce**
1. Go to the editor
2. Adjust the color on something
3. Click the "custom color" button/link to view the color picker
4. See the down chevron in the bottom right

**Screenshots**
![image](https://user-images.githubusercontent.com/967608/72296899-591abf80-3620-11ea-9f7c-6ed0c69e5530.png)

**Comment by enriquesanchez** [comment]
Hey Jerry! 

Thank for pointing this out. There are some explorations to fix this in #18678.

I'm going to close this for now and we can continue work on the other issue.
