### ISSUE TITLE
"Top Toolbar" mode now has drag handle (broken) and arrows, should it?

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#19602]
**Describe the bug**
When in "Top Toolbar" mode, the moving handle and arrows are now in the toolbar too, which:
1. It's buggy, as the drag handle doesn't work anymore
2. It's not ideal, because even if it worked, it moved the handle away from where the drag should happen, and having 3 more buttons up there takes away a lot more space for the toolbar.

![Screenshot 2020-01-13 at 18 59 12](https://user-images.githubusercontent.com/4389/72283677-2b8d4080-3637-11ea-99dc-2fe2a5b84a7f.png)

**To reproduce**
1. Create new post
2. Set the toolbar to "Top Toolbar"
3. Try to write a few paragraphs
4. Try to move a paragraph with the drag handle.

**Expected behavior**
The arrows and drag handle should be near the block (left side):

![Screenshot 2020-01-13 at 19 03 38](https://user-images.githubusercontent.com/4389/72283824-7e66f800-3637-11ea-848e-6c49b26cacbb.png)

**Desktop (please complete the following information):**
 - macOS 10.15.2
 - Chrome 79.0.3945.117

**Comment by epiqueras** [comment]
Maybe we should keep the arrows at the top and hide the drag handler?
