### ISSUE TITLE
Plugin Sidebars cannot edit meta when Custom Fields are visible

### ISSUE THREAD

**Issue by csalzano** [WordPress/gutenberg#19600]
If, in the Editor's Options, Custom Fields is checked and the corresponding Custom Fields meta box contains the meta key that a plugin sidebar also edits, the plugin sidebar will be unable to change the value for said meta key.

I followed these instructions: https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/

And I couldn't edit any meta values using my new sidebar until I disabled Custom Fields in the Editor Options. If there is no value set for a meta key, and therefore said key is not displayed in the Custom Fields editor meta box, then the plugin sidebar is able to edit the value.

**Comment by noisysocks** [comment]
Custom Fields are saved when the post is saved, so I suspect what is happening here is:

1. Page loads. `Value A` is loaded from post meta and placed into the Custom Fields text field.
2. User uses sidebar to update post meta to `Value B`.
3. User saves the post. Custom Fields UI still has `Value A` in the text field so updates post meta to be `Value A`. This clobbers the data entered by the sidebar.

I suggest prefixing the name of the post meta key with an underscore `_` which should hide it from Custom Fields.

We should also update the tutorial to suggest using a name that begins with an underscore.

**Comment by carolinan** [comment]
Tested and confirmed.

When following the tutorial, I also ran in to this problem with the sidebar not re-appearing if it is hidden:
https://wordpress.org/support/topic/sidebar-gone-forever-once-hidden/
Can this be added to the tutorial? 

When the tutorial is updated with the new name,  the permission check needs to be included too.
