### ISSUE TITLE
Pasting Text adds empty space in front

### ISSUE THREAD

**Issue by icc365** [WordPress/gutenberg#19614]
**Describe the bug**
For the longest time, when I copy and paste text into a paragraph or heading block, it always adds an empty space in front (I added screenshots). Basically, I have to remove that space each time I paste content.

**To reproduce**
1. Create a new page
2. Add a Heading block and paste text into it (don't type it in); or,
3. Add a paragraph block and paste some text into it (don't type it in).
4. After pasting text (which I grabbed some lorem ipsum content), see the space.

**Expected behavior**
Should be that when pasting text content into a block, there should be no space added in front of the first line (sentence).

**Screenshots**
I've added a screenshot showing the block editor, source code, and a browser web tools view.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.117

**Smartphone (please complete the following information):**
 - Untested in any mobile device

**Additional context**
- Working Locally on XAMPP, but this also happens on a live site.
- This is an issue I noticed has existed for as long as I can remember when first trying out Gutenberg.
- This is also using WordPress 5.3 and the core block editor (no GB plugin).
![gb-pasting-space](https://user-images.githubusercontent.com/54302511/72304046-2f639780-3624-11ea-8ace-4b2f684845fb.jpg)

**Comment by icc365** [comment]
I've also today noticed that I also get extra spacing on the left and right side of a word when I copy and paste a word to replace another word in a paragraph block. So where there is normal spacing, after selecting a word and then pasting the new word, it adds left and right space.

Seems like pasting things into a block, the editor is adding spaces.

**Comment by talldan** [comment]
@icc365 This issue was present for a while, but the good news is it's fixed and the fix will be released with WordPress 5.4.

The issue was originally reported in issue https://github.com/WordPress/gutenberg/issues/16172 and fixed by https://github.com/WordPress/gutenberg/pull/19043.
