### ISSUE TITLE
Inserter malfunctions on mobile

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1961]
## Issue Overview
When opening the inserter on screens smaller than 782pixels it works in mysterious ways.

When pressing the button (+) in the top bar, the inserter is displayed on top of the bar.
Making it unusable because scrolling up is not available.
<img width="402" alt="new_post_ _test_ _wordpress_and_gutenberg_983" src="https://user-images.githubusercontent.com/2005352/28423750-348ceed8-6d6c-11e7-8a28-268a74709f14.png">

When pressing the (+) button in the blocks content, the modal is placed off-screen on the left. The buttons on the bottom are placed below the window, having to scroll to reach them.

<img width="402" alt="new_post_ _test_ _wordpress_and_new_issue_ _wordpress_gutenberg" src="https://user-images.githubusercontent.com/2005352/28423773-41aba35c-6d6c-11e7-832d-88a053fd696a.png">

## Steps to Reproduce (for bugs)

1. Make the screen smaller than 782 pixels wide
2. Open the inserter on any location

**Comment by karmatosed** [comment]
This doesn't make it any less of an issue, but there are a lot of issues with the mobile experience - it's not there yet. I am going to label this for mobile, but there needs to be a general focus and fix for all of the mobile experience, this is just one part of that.

**Comment by aduth** [comment]
The first of the two issues described here is fixed as of #1204

**Comment by mtias** [comment]
Closing as the main issue is fixed. There's ongoing work in further improving the inserter design.
