### ISSUE TITLE
Cover block: Vertical spacing of color circles doesn't match horizontal spacing

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19612]
**Describe the bug**
The vertical spacing between the color circle rows in the Cover block's placeholder screen doesn't match the horizontal spacing. They should be equal similarly to how they look in the sidebar color settings.

**To reproduce**
1. Add a Cover block.
2. Observe the vertical spacing doesn't match the horizontal spacing in the placeholder.

**Expected behavior**
I expected the spacing to match vertically and horizontally.

**Screenshots**

![Screen Shot 2020-01-13 at 4 19 48 PM](https://user-images.githubusercontent.com/617986/72303102-0ab9f080-3621-11ea-8203-f9dd3a94f1ee.png)

It should look similar to the sidebar color settings:

![Screen Shot 2020-01-13 at 4 23 57 PM](https://user-images.githubusercontent.com/617986/72303139-20c7b100-3621-11ea-8708-c22d8629b8e4.png)

**Desktop (please complete the following information):**
 - OS X Catalina
 - Firefox 71
 - Gutenberg 7.2

**Comment by mtias** [comment]
This was because we were showing gradients and solid colors. We are no longer showing gradients by default in the placeholder.
