### ISSUE TITLE
TabPanel hover inherit wrong styles in Gutenberg 7.2

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/gutenberg#19624]
See screenshot:

![PixelSnap 2020-01-14 at 13 29 10](https://user-images.githubusercontent.com/39319746/72344667-19acab80-36d2-11ea-89e0-4301411fbc09.png)

**Comment by talldan** [comment]
Guessing this has been established as a bug given there's a linked PR that fixes it.

@dnnsjsk The description is a little too brief, it'd be great if you could add some more information on what the issue is.

**Comment by dnnsjsk** [comment]
Hey @talldan,

there were no :hover styles on the tab panel before 7.2 and this update introduced them. (as seen on the screenshot) also, note that the block is focused, so the hover styles override the blue bottom border indicating focus.
