### ISSUE TITLE
Navigation Block: when the site doesn't have published Pages initial suggestions shows a blank popover.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#19628]
_Originally posted by @retrofox in https://github.com/WordPress/gutenberg/pull/19458#issuecomment-574145934_

> ...what happens when the site doesn't have published entries. It shows a blank popover:

<img src="https://user-images.githubusercontent.com/77539/72343451-aabd5b80-36ad-11ea-8bb9-5f0e3bb50643.png" width="400px" />
Wondering if we should show a message about this. Anyway. probably out of this scope. Feel free to ignore it.

Is this an issue? If so should we show a message here but I'm thinking it might create more confusion.

**Comment by mtias** [comment]
I don't think it'd be an issue after #18900. Also by default there should at least be an about page, a hello world post, etc.

**Comment by retrofox** [comment]
> I don't think it'd be an issue after #18900

Yup, it's right.

> Also by default there should at least be an about page, a hello world post, etc.

Agree that it's an edge case but it's possible.

**Comment by getdave** [comment]
> I don't think it'd be an issue after #18900

I take your point, I'm not 100% sure this covers the same issue. Granted, you will be able to create a new Page from the Nav _but_  I can imagine Users creating some Pages from within the `Pages` area of the WP Dashbord but not _publishing_ them. They might then expect to be able to add these to the Nav Block because they are not yet fully aware of the importance of the Post Status.

It could perhaps be confusing to not see these appear. Especially for new users. What do we think?

I wonder whether Design could give us their view here as well @karmatosed?

**Comment by shaunandrews** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/191598/72638421-64782e80-3931-11ea-8750-28451d607512.png">

I mocked up a few quick ideas for how we could add a message to the default state of the Link UI when a site has no published content — including and excluding the possible "Create new" button. I'm not sure the message is super helpful on its own, and when paired with the "Create new" button I find it visually unbalanced.

Instead, I think it might be better to show some messaging once the user starts typing in the search input:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/191598/72638539-9a1d1780-3931-11ea-8aff-2c95911a0074.png">

**Comment by karmatosed** [comment]
@shaunandrews I think I agree with you on the last one being the best there. I like the add new page there and wonder if this could extend for other content (add post, add custom post type). My only wonder still which I feel might just be me is the '+', is there an option without that?

**Comment by draganescu** [comment]
I don't think this is still an issue, as with #18900 where there is no page you are offered the suggestion to make a new one. Therefore I will close but if I am wrong feel free to reopen.
