### ISSUE TITLE
Can't read full permalink on smaller screen

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1962]
## Issue Overview
Depending on the URL of the website, the permalink will be partially or fully obscured by the `Copy` button on smaller screens.

<img width="399" alt="new_post_ _test_ _wordpress" src="https://user-images.githubusercontent.com/2005352/28424229-60c03d38-6d6d-11e7-8d48-3db012bc9020.png">

## Steps to Reproduce (for bugs)

1. Create a new post
2. Enter some title
3. Save the post
4. Reduce the screen width and see the important part of the permalink being faded out

## Possible Solution
Make the fade on the left side, instead of the right side.

## Related Issues and/or PRs
As the permalink cannot be modified currently, an additional button might be needed to edit it.
Related: https://github.com/WordPress/gutenberg/issues/1285

**Comment by karmatosed** [comment]
I think this isn't an issue as permalinks could be really long. There is the option to copy, so I don't think this is a problem. Fading the other way could cause confusion to some.
