### ISSUE TITLE
Don't open block appender modal if only one block is allowed

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#19620]
Hey,

I am only allowing one block on my page using this code:

```
add_filter('allowed_block_types', 'sp_allowed_block_types', 10, 2);

function sp_allowed_block_types($allowed_blocks, $post)
{

    if ($post->post_type === 'page' || $post->post_type === 'post') {
        $allowed_blocks = array(
            'sp/block',
        );
    }

    return $allowed_blocks;
}
```

It doesn't really make sense to allow the modal in this case, the appender icon should instead insert the only block that is available.

![screencapture-spacepress-local-sp3-wp-admin-post-php-2020-01-14-12_24_51](https://user-images.githubusercontent.com/39319746/72340884-45776380-36c9-11ea-8496-af02e97bd95c.png)

**Comment by mtias** [comment]
This is how the "navigation" and "buttons" blocks work already. cc @jorgefilipecosta

**Comment by chrisvanpatten** [comment]
Looks like #16708 is where this was added. @dnnsjsk are you using Gutenberg in WordPress core or via the plugin? It doesn't look like this change made it to WP core yet.

**Comment by mtias** [comment]
Ah, indeed.

**Comment by dnnsjsk** [comment]
@chrisvanpatten I am using the Gutenberg plugin. The problem also persists when only allowing the Paragraph block.

![paragraph](https://user-images.githubusercontent.com/39319746/72429836-20e6be80-3791-11ea-8298-69bfc1d1e002.png)

**Comment by jorgefilipecosta** [comment]
I did some tests, and it seems like the behavior currently implemented to insert the block if only one block is allowed only happens for insertions inside inner blocks. Outside innerblocks for the root bock, it does not occur. This seems inconsistent, and if possible, it is something that we should fix.

**Comment by paaljoachim** [comment]
Hello everyone. It would be great with a status update here.
@jorgefilipecosta is this issue something you might be able to take a closer look at?

**Comment by jorgefilipecosta** [comment]
Hi @paaljoachim, yes I can take a close look into this issue :)

**Comment by Mamaduka** [comment]
I'm going to close this. The Inserter's behavior has changed recently. Now, it displays the allowed block at the top, followed by the remaining blocks. See #62169.
