### ISSUE TITLE
Can't upgrade Downshift

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#19644]
Can anyone update `downshift` in `@wordpress/components`? I've tried through all possible methods, but using `4.0.5` always leads to the build failing with:

```sh
Module not found: Error: Can't resolve 'downshift' in '/Users/epiqueras/Desktop/Work/gutenberg/packages/components/src/custom-select-control'
```

**Comment by epiqueras** [comment]
The module doesn't get downloaded into `node_modules` anywhere for some reason.

**Comment by epiqueras** [comment]
cc @silviuavram

**Comment by gziolo** [comment]
It was on our side because of the complex monorepo setup.

**Comment by silviuavram** [comment]
I also took a look, I can install the new version and codesandboxes with 4.0.5 work as well.

**Comment by epiqueras** [comment]
It was broken for certain NPM versions.
