### ISSUE TITLE
A more generic Modal

### ISSUE THREAD

**Issue by adekbadek** [WordPress/gutenberg#19643]
**Is your feature request related to a problem? Please describe.**

The [Modal](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/modal) component displays a title, has internal padding, and has constrained width. 

**Describe the solution you'd like**

It'd be nice to be able to:
1. skip the title
2. fill the whole internal modal space
3. make the modal fill the screen, or set a minimal padding (e.g. 20px from screen edge) to keep the visual context

**Describe alternatives you've considered**

Using `react-modal` ;)

**Comment by talldan** [comment]
@adekbadek Thanks for reaching out. The `@wordpress/components` package is intended to provide components styled appropriately for use in WordPress, and the goal is for these components to be consistent and also meet accessibility requirements.

Providing a title is best practice for creating accessible modals, the title is used by the `aria-labelledby` attribute.

You can pass a custom `className` to the modal, and style the modal as needed, so I think much of what you mention should be possible. For a generic modal I'd recommend a third party library.

I'll close this issue, as this is something that's unlikely to be fixed unless a requirement in WordPress core arises for this style of modal.
