### ISSUE TITLE
WP notifications fall behind toolbar and inspector

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1964]
## Issue Overview
When plugins throw a notification using WP's own notification system, they render behind the gutenberg UI.

<img width="775" alt="notifs" src="https://user-images.githubusercontent.com/6073772/28425762-8e6f5774-6d71-11e7-8748-83a365648244.png">

## Steps to Reproduce (for bugs)
1. In this case, I installed three premium yoast plugins, which throw an error when they are not registered, but there are other plugins that do this too.
2. Open gutenberg and witness the errors lurking behind the UI, pushing the content down

## Expected Behavior
Hide the errors.

## Current Behavior
The errors show up in the content area, at the top of the screen, behind the toolbar and inspector UI. The more there are, the further they push the actual content down.

**Comment by hedgefield** [comment]
Addendum: these notifications also interfere with the tabbing behaviour, see #1960. Most notably if you select 'skip to main content', the first few tabs still move focus to the notifications which technically live inside the content area here.

**Comment by mtias** [comment]
Consolidating in #3395.
