### ISSUE TITLE
Nav Block: Hide the transform menu for navigation link inner blocks

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19654]
**Describe the bug**
We show a navigation link transform menu that doesn't do anything. Since we have horizontal movers that show up before this menu item, it feels strange and out of place. I would expect this to confuse users since they would click it and nothing would happen.

<img width="362" alt="Screen Shot 2020-01-14 at 3 12 58 PM" src="https://user-images.githubusercontent.com/1464705/72390777-6a2b0580-36e0-11ea-8256-9ed0bcfe9a81.png">

I think it should either be hidden, or appear at the start of the menu to match every other block with vertical movers. My preference is to hide it.

**Comment by mtias** [comment]
This should be seen in the larger context of https://github.com/WordPress/gutenberg/issues/18667

The block type is one of the elements that consistently remains as an anchor point for all blocks.

**Comment by apeatling** [comment]
Okay! This makes more sense to me -- especially with the movers hiding and showing in that way.

**Comment by shaunandrews** [comment]
So do we wait for the G2 work to land, and accept this as a symptom of an awkward growing phase? (I think that's the right way forward, just want to confirm.)

**Comment by apeatling** [comment]
I don't think we should take temporary steps in the meantime. The G2 PR seems to be progressing well.

**Comment by karmatosed** [comment]
If I am right, everyone is agreeing to close this for now? I'll do that and we can always reopen.
