### ISSUE TITLE
Embed failure placeholder design is broken

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#19662]
<img width="809" alt="Capture d’écran 2020-01-15 à 11 19 11 AM" src="https://user-images.githubusercontent.com/272444/72425883-eed15e80-3788-11ea-9a4d-4fa9edf21a7b.png">

I believe this should look closer to the embed default placeholder with the failure message and buttons under the input?

<img width="755" alt="Capture d’écran 2020-01-15 à 11 20 15 AM" src="https://user-images.githubusercontent.com/272444/72425976-1e806680-3789-11ea-8008-e02fe24a392b.png">

I guess this happened with the placeholder refactorings cc @jasmussen @ItsJonQ

**Comment by ItsJonQ** [comment]
@youknowriad Halloo! Thank you for spotting this! I just took a looksy 🤔 

The error markup HTML element isn't playing nicely with the `display: flex` of the `form`. These changes were made 1+ year ago. Not too sure why it's popping up now.

Will work on this now, and submit a fix as soon as it's ready

**Comment by davemart-in** [comment]
This may or may not be related. I'm happy to create a separate issue if it's unrelated. 

I noticed a couple of irregularities when a field and a button occupy the same row. Here are a couple examples of what I'm seeing:

**RSS Block**

<img width="702" alt="rss-block" src="https://user-images.githubusercontent.com/5634774/72528345-cef97380-3838-11ea-9ffe-cc6bcdc60703.png">

**Embed Block**

<img width="704" alt="embed block" src="https://user-images.githubusercontent.com/5634774/72528409-efc1c900-3838-11ea-903e-b03bb2e9f2d7.png">

It seems like in both instances the input could benefit from being the same height as the button.

Hat tip to @jasmussen for pointing me to this issue.
