### ISSUE TITLE
Sidebar: Custom block missing Panel Control looks broken

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#19660]
**Is your feature request related to a problem? Please describe.**

It isn't apparent that when creating a Custom block you should also include a `PanelBody` component to ensure that the sidebar has consistent padding. It also allows you to add content right below the `BlockCard` and it doesn't visually separate the content. This is inconsistent with how the rest of the Gutenblock blocks work (Or most).

**Describe the solution you'd like**

1 The content of inside of my `InspectorControls` should be padded to match other elements in the sidebar 
2. The `BlockCard` should close itself with a border bottom.

**Describe alternatives you've considered**

I can't think of a use case where I would not want the padding.

**Screenshots**

![image of broken sidebar](https://d.pr/i/8SbRp8.png)

**Comment by youknowriad** [comment]
Hi There! If I  understand properly, you're suggesting that the InspectorControls should automatically add a PanelBody of some sort.

These are good thoughts but I don't think we can change that at the moment. The boat has sailed. If we do automatically add panels today. Plugins will show up with double panels.

Also, how do you add multiple panels (like all core blocks), how do you give titles to these panels?

**Comment by StevenDufresne** [comment]
That's fair. The juice is probably not worth the squeeze here.

Would it make sense to require the child of an `InspectorControl` be a `Panel` or at least kick up a warning in dev mode?

**Background**:
I was slightly mislead by this tutorial:
https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/plugin-sidebar-1-up-and-running/

We should consider updating it to talk about the panel component:
https://developer.wordpress.org/block-editor/components/panel/

If agreed, I'll file the ticket over there.

**Comment by youknowriad** [comment]
Makes sense we should update the tutorial I think https://github.com/WordPress/gutenberg/edit/master/docs/designers-developers/developers/tutorials/sidebar-tutorial/plugin-sidebar-1-up-and-running.md

**Comment by StevenDufresne** [comment]
Closing.... tutorial doesn't appear to exist anymore.
