### ISSUE TITLE
Unable to center paragraphs

### ISSUE THREAD

**Issue by SheElf** [WordPress/gutenberg#19678]
![center](https://user-images.githubusercontent.com/17300848/72452041-1cfb7200-377a-11ea-9144-4c1f46c5a4de.PNG)
**Describe the bug**

**To reproduce**
1. Go to '...' https://pausitiveliving.ca/2020/01/iyura-head-turner-trio-2.html

3. Scroll down to '....' content under the first image. I clicked the 'center' option, but it doesn't work. It's never worked and I thought with you recent updates, you fixed it.  see attached.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

I'm using a Dell PC and Chrome Browser with the latest version. 
WordPress 5.3.2 running Voice Child theme.
Running PHP version: 7.1.33

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by SheElf** [comment]
![center](https://user-images.githubusercontent.com/17300848/72452583-0a356d00-377b-11ea-9fe9-446c0e48983c.PNG)

**Comment by youknowriad** [comment]
Hi There!

if you take a look at the CSS loaded on your page. You'll notice that you have 

```
#primary p {
    text-align: justify !important;
}
```

This style overrides the style applied by Gutenberg to center the text. You should try to figure out where this style is coming from. It can come from your theme, from a plugin or from a Custom CSS you added to your site/page.

I hope that helps.
