### ISSUE TITLE
Bug occurs when I enable Gutenberg for WooCommerce products

### ISSUE THREAD

**Issue by kiber-chaka** [WordPress/gutenberg#19683]
**Describe the bug**
When I enabled **Gutenberg** for **Woocommerce**, as it recommended [here](https://wplook.com/how-to-enamble-gutenberg-for-woocommerce-products/), content from Yoast Seo tabs disappeared ([screenshot](http://pix.toile-libre.org/upload/original/1578239961.png)).
It happens only with products that have at list one comment.

**To reproduce**

1. Create a product using the classic editor
2. Submit a product review and approve it in the product edit screen
3. Enable Gutenberg for products as explained in this guide
4. Edit the product using Gutenberg

**Expected behavior**
Not disappearing of YoasSeo tabs content.

**Screenshots**
http://pix.toile-libre.org/upload/original/1578239961.png

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Chrome
 - Version latest.

**Additional context**
- Latest version of Gutenberg. I have tried build in version of Gutenberg and the plugin.

**YoastSeo Support looked and here is their answer:**
We had a look at the product edit screen (on the screen you can see, that tabs of Yoast Seo Plugin are empty):

http://pix.toile-libre.org/upload/original/1578239961.png

and found the following error in the browser's console: **ReferenceError: commentsBox** is not defined We temporarily disabled Yoast SEO Premium and confirmed that the error still occurs when our plugin is disabled which means it's not caused by Yoast SEO Premium. However, the error prevents the Yoast metabox from loading properly. As the error details indicate, the error is related to the comments feature. We've been able to reproduce the error in our testing environment by following these steps:
1. Create a product using the classic editor
2. Submit a product review and approve it in the product edit screen
3. Enable Gutenberg for products as explained in this guide
4. Edit the product using Gutenberg
We were able to fix the error on our test site by editing the product with the classic editor, sending the existing comment to trash and then switching the editor to Gutenberg. You may want to try this workaround on your website or, alternatively, contact the WooCommerce team and bring this issue to them. They'll be able to investigate this issue further and hopefully find a solution.

**Comment by youknowriad** [comment]
Hi There! since this doesn't seem to be a Gutenberg bug but more a WooCommerce or a Yoast issue. I'd suggest opening an issue there to get better responses.

Thanks for your understanding.

**Comment by kiber-chaka** [comment]
I have opened it there, but they closed the bug also.

**Comment by youknowriad** [comment]
Can you cross link the issue here so we can get more info?

**Comment by kiber-chaka** [comment]
Hi!
I can't give you the link, because the problem is in admin area:
[http://pix.toile-libre.org/upload/original/1579326818.png](http://pix.toile-libre.org/upload/original/1579326818.png)

But you can easily recreate the situation by following this steps:

1. Create a product using the classic editor
2. Submit a product review and approve it in the product edit screen
3. Enable Gutenberg for products as explained in [this guide](https://wplook.com/how-to-enamble-gutenberg-for-woocommerce-products/)
4. Click **edit** the item with the product review.
5. Look under  the editing textarea on YoastSeo settings:
http://pix.toile-libre.org/upload/original/1579326818.png

**Comment by youknowriad** [comment]
I'm sorry I was unclear, i meant the link the issue reported upstream. Thanks

**Comment by kiber-chaka** [comment]
Hello!
Here is the WooCommerce link: 
https://github.com/woocommerce/woocommerce/issues/25352

With YoastSeo people I spoke by email.

**Comment by AlexeySvidentsov** [comment]
> Hi There! since this doesn't seem to be a Gutenberg bug but more a WooCommerce or a Yoast issue. I'd suggest opening an issue there to get better responses.
> 
> Thanks for your understanding.

Hello, but why you are saying that this not Gutenberg issue? Its in WP core files. 
When we are using Gutenberg - code for including comments are just ignored - https://github.com/WordPress/WordPress/blob/master/wp-admin/post.php#L186-L204. 
Comment form markup is also ignored and not included in block editor - https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L759-L761
Its not related to WooCommerce, Yoast or any other plugins. Its completelly WP issue.
