### ISSUE TITLE
Screen focus is lost when a user clicks on a list item in a lengthy list block 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#19682]
**Describe the bug**
When a user tries to edit an item near the end of a list block with lengthy content, is not alread in that block, and clicks on the list item, the user is brought to the center of the list block. For longer lists, this behavior (re-centering/focusing) is problematic for users who expect the screen to remain where they clicked. 

It is a bit difficult to exactly express this behavior, but this GIF captures it quite nicely. 
![ezgif-6-6b059c98208b](https://user-images.githubusercontent.com/955351/72464393-2b11b880-37a3-11ea-8c02-e428a10ae9c7.gif)

**To reproduce**
1. Create a list with lengthy items that would extend beyond the current view of the desktop. 
2. scroll to a list item that is near the end of the list 
3. click on a list item 

**Expected behavior**
When a user clicks on a list item, the current view of the screen would remain where the user clicked; not towards the center of the block. 

**Desktop (please complete the following information):**
- Firefox (have not tested this on Chrome) on both linux and windows 
- Gutenberg v7.2.0; 
- replicated this on both TwentyTwenty theme and our internal custom theme. 

**Work around**
I've been able to workaround this with our content editors by instructing them to first click anywhere within the list block (which establishes initial focus), and then click the list item that they wish to edit.

**Comment by youknowriad** [comment]
Thanks for creating the issue. I think this issue is independent of the block used. It happens with any lengthy.

**Comment by maxlisewski** [comment]
as @log1x pointed out in the related issue #20111, blocks immediately scroll to bottom when clicked. 

![](https://camo.githubusercontent.com/7c49453fff348833a46833a35753465a339bec55/68747470733a2f2f692e696d6775722e636f6d2f446c41534459472e676966)

the expected behaviour stays the same: users expect the screen to remain where they clicked.
