### ISSUE TITLE
Nav Block: Smaller viewport widths losing container padding

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19689]
⚠️ **IMPORTANT**
Let's wait until #19681 ships before to work on this, since it will introduce many changes in the styles organization.

-----------------

**Describe the bug**
On smaller viewport widths the navigation items switch to vertical, but there is no container padding so the links hit up against the edge.

<img width="321" alt="Screen Shot 2020-01-15 at 3 20 03 PM" src="https://user-images.githubusercontent.com/1464705/72479936-acb91480-37aa-11ea-87c4-29e260396953.png">

**To reproduce**
1. Add a navigation block with some items
2. View the nav block in the front end at a smaller viewport width

**Expected behavior**
Some amount of padding suitable for smaller screens.

**Comment by apeatling** [comment]
Related https://github.com/WordPress/gutenberg/issues/19688

**Comment by retrofox** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/19681

<img src="https://user-images.githubusercontent.com/77539/73701929-f016ec80-469f-11ea-8a3d-9e8b80333427.png" width="400px" />
