### ISSUE TITLE
Fullwidth Blocks

### ISSUE THREAD

**Issue by AdsonCicilioti** [WordPress/gutenberg#1968]
It would be interesting, since Gutenber's proposal is to be an ultra modern editor, he owns an advanced version as well as how the wp_editor has the full version and the tiny one. In this advanced version of Gutenberg you could have support for Fullwidth (or boxed) Blocks with Background options. Could be quite used in creating home pages, but nothing prevents it from being used for other types of posts.

Just my 2 cents.

**Comment by mtias** [comment]
Did you see the "cover text" block? If your theme has added support for "wideImages" in Gutenberg, it does a lot of what you described.

(Closing to keep the list of issues manageable, but feel free to continue the conversation.)
