### ISSUE TITLE
Cover block (and similar): Image registration by theme

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19692]
**Is your feature request related to a problem? Please describe.**
Some themes use the same large image for different purposes, e.g. for a cover block but also as a background image. E.g. a large header with an image and an "infobox" on that image, which is also a cover with a group block that got a semitransparent background. Further below the same image is also re-used with some effects, etc.

**Describe the solution you'd like**
Allow themes to register their own images, using internal URLs as those would be image files from the theme, to be used by the cover block. Additionally, make it possible for themes to lock the images that can be used for the cover block, similar to the color palette.

**Describe alternatives you've considered**
As the current workaround, a cover block style each for a separate background (forced by theme CSS) is registered by the theme. This approach requires to disable the background customization for these cover block styles and other tricks, focal points won't work as with an usually added image.
Instead of a cover block, a group block with block styles for background images could be used, but this doesn't offer any cover block related options, like the focal point.

**Related issues**
https://github.com/WordPress/gutenberg/issues/16350

**Comment by youknowriad** [comment]
Hi There!

It seems like you're suggestion that themes should be able to programmatically add images into the WordPress media library in order to be used by Gutenberg and any editor.

I think this goes is a little bit out of scope of Gutenberg and should be raised as a trac ticket.

Thanks.

**Comment by strarsis** [comment]
@youknowriad: It would be similar to what themes can already do with the [header image](https://developer.wordpress.org/themes/functionality/custom-headers/#set-a-custom-header-image) (before Gutenberg). The theme registers the image by using its URL. So this would combine URL support for cover block and the ability for themes to register these URLs programmatically.

**Comment by kathrynwp** [comment]
As there's been no movement on this in several years, I'm going ahead and closing this out, since @youknowriad  mentioned this would be a feature to request in Core Trac rather than in this repo.

@strarsis You're still welcome to put in Trac ticket and link to it from here. Thanks!
