### ISSUE TITLE
Nav Block: Inserter color should always retain contrast to the background color

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19690]
**Describe the bug**
When using a dark background color on the navigation block, the inserter becomes difficult to see:

<img width="950" alt="Screen Shot 2020-01-15 at 3 28 03 PM" src="https://user-images.githubusercontent.com/1464705/72480333-f81ff280-37ab-11ea-818f-8fd3116a6f76.png">

I think it should either always adjust itself to be a color that is high contrast to the selected background color, or match whatever the text color is.

**To reproduce**
1. Add a navigation block with some items
2. Set the background color to a darker color

**Expected behavior**
The inserter is always a color that is high contrast to the background color.

**Comment by apeatling** [comment]
Should be fixed by https://github.com/WordPress/gutenberg/pull/18327

**Comment by karmatosed** [comment]
This has now changed with recent iterations to a uniform '+'. For now, closing but we can always reopen.
