### ISSUE TITLE
New Block: Post Date

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19697]
As indicated in #15623, there will be a suite of Post blocks that make up the Post template.

This is the Post Date block.

### Features

- Support for date formatting.
- Allow editing by opening a calendar.

### Mockups

![Screen Shot 2020-01-15 at 6 32 43 PM](https://user-images.githubusercontent.com/617986/72488311-71780f00-37c5-11ea-9fa4-c5fa38f26bc9.png)

![Screen Shot 2020-01-15 at 6 32 28 PM](https://user-images.githubusercontent.com/617986/72488314-7341d280-37c5-11ea-850d-7d54b0586e80.png)

### Questions

- Should the "time" toggle exist separate from the "format" dropdown, or should it be included in the dropdown?
- Should the format be included in the block toolbar as a primary action?

**Comment by epiqueras** [comment]
>Should the "time" toggle exist separate from the "format" dropdown, or should it be included in the dropdown?

I think it's cleaner to keep it together with the format.

>Should the format be included in the block toolbar as a primary action?

Yes, I think this should be in the toolbar and that the calendar should open when clicking on the date in the block itself. This aligns better with the philosophy of direct manipulation.

**Comment by mapk** [comment]
Look at me just defaulting to the sidebar! Thanks for pulling me back, @epiqueras. 

Here's are some revised mockups.

### Date selection

![Screen Shot 2020-01-16 at 9 34 05 AM](https://user-images.githubusercontent.com/617986/72550505-ba70a780-3847-11ea-8d63-4e2d4f978255.png)

### Date and time format

![Screen Shot 2020-01-16 at 10 04 29 AM](https://user-images.githubusercontent.com/617986/72550508-bcd30180-3847-11ea-9fdd-95ff4c17233e.png)

### Notes

- I've not added all the date and time formats, but just prepared something visual.
- I'm not sure the "Date and time format" popover should include a heading as my mockup shows because I don't normally see this pattern in other areas, or haven't noticed.
- Is an "Edit" pencil icon good for this interaction? I _think_ so.

**Comment by epiqueras** [comment]
That looks so much better! Nice work.

>I'm not sure the "Date and time format" popover should include a heading as my mockup shows because I don't normally see this pattern in other areas, or haven't noticed.

Yeah, we can drop it.

>Is an "Edit" pencil icon good for this interaction? I think so.

I would like to see something more descriptive here. Maybe a sketch of 2 different formats with a slash between them?

**Comment by mapk** [comment]
Here's a mockup using the "M/D/Y" as the icon for date format. I've also removed the heading from the popover and added an option with the time too so we might see what that looks like.

![Screen Shot 2020-01-16 at 4 08 49 PM](https://user-images.githubusercontent.com/617986/72573437-85ca1380-387a-11ea-8cdb-b1949733ac3d.png)

However, I don't think the M/D/Y are good for i18n.

**Comment by epiqueras** [comment]
How about a calendar with a clock and some sort of edit indicator?

**Comment by epiqueras** [comment]
The calendar is less clear on the second one and the third one blurs the
pencil.

**Comment by mcsf** [comment]
It would be good to also recognise and support the site's global date format, per the setting on `wp-admin/options-general.php`, including honouring whatever custom value it may have:

<img width="313" alt="Captura de ecrã 2020-01-17, às 11 54 45" src="https://user-images.githubusercontent.com/150562/72610768-30484200-3920-11ea-9af2-a042e6b28f77.png">

**Comment by epiqueras** [comment]
It should default to that.

**Comment by richtabor** [comment]
> Here's a couple icon variations. We need to be careful not to add too much to an icon for the sake of clarity. I fiddled a bit with combining a pencil and calendar.
> 

What if we used the word "Format", similar to how the Image block (and relative blocks) employ "Replace" instead of an icon?

![format](https://user-images.githubusercontent.com/1813435/73086933-980e0800-3e9f-11ea-8ea1-f63557b5f144.png)

**Comment by epiqueras** [comment]
Localization can break the layout with long words.

**Comment by richtabor** [comment]
> Localization can break the layout with long words.

What's the solution for the Image block then, in regards to i18n with "Replace"?

**Comment by epiqueras** [comment]
There isn't one. We could make an icon with a thumbnail and a replacement arrow.

**Comment by shaunandrews** [comment]
I noticed this issues has a lot of chatter around editing the date itself. This brings up an interesting question; Are you editing the post itself? If so this will bring up some _interesting_ complexities around saving and publishing changes.

Instead, I'd suggest that this Block (and the other related Post blocks) are more about display content defined elsewhere. Options on these blocks should allow users to adjust display properties (color, font, size, date format, alignment, etc) but the content itself should _not_ be editable.

In the context of the larger Post block, the `post_id` would be defined by the parent block. But in scenarios where these _post-related_ blocks (like this Post Date block) we'll need to add some UI for selected a `post_id` in the setup state, and (maybe) in the toolbar. Here's a quick mockup:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/191598/73100077-d238d300-3eba-11ea-87f1-1aeaa00ad19e.png">

Once the post is selected, the option could be accessible from the sidebar:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/191598/73100214-19bf5f00-3ebb-11ea-9e62-8859c86d14f4.png">

--

I'm a fan of using a labelled dropdown for the formatting options. Something like this is what I would expect:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/191598/73101003-c51ce380-3ebc-11ea-8747-2f92e3028dfe.png">

Combining the day and time formatting would also mean we wouldn't need the "Show time" switch in the sidebar.

**Comment by epiqueras** [comment]
>Instead, I'd suggest that this Block (and the other related Post blocks) are more about display content defined elsewhere. Options on these blocks should allow users to adjust display properties (color, font, size, date format, alignment, etc) but the content itself should not be editable.

I think that argument can be made for things like the date because of scheduling. But directly manipulating the excerpt is a lot more intuitive. The same can be said of the featured image, for example.

>But in scenarios where these post-related blocks (like this Post Date block) we'll need to add some UI for selected a post_id in the setup state, and (maybe) in the toolbar. Here's a quick mockup:

Replicating this functionality in every post field is repetitive. You would wrap it in a post block that already has a post selector.

>Combining the day and time formatting would also mean we wouldn't need the "Show time" switch in the sidebar.

Yes, we are already doing that.

**Comment by shaunandrews** [comment]
> But directly manipulating the excerpt is a lot more intuitive. The same can be said of the featured image, for example.

Hmmm, I don't know. Unless the contents of the excerpt is isolated (and not actually editing the excerpt data for the post in the DB), I could see there being confusion around editing a post's data and not understanding that it will change it everywhere. Also, there'd still be an issue around saving post data — would the data be saved immediately? When you published the post/page that contains the customized block? What if the page containing this block is scheduled, would we only update the post data when the page is published?

> Replicating this functionality in every post field is repetitive. You would wrap it in a post block that already has a post selector.

But what if these post-related blocks are used _outside_ of a post block? Or, is that not something we'd want, or would consider useful?

**Comment by epiqueras** [comment]
>Hmmm, I don't know. Unless the contents of the excerpt is isolated (and not actually editing the excerpt data for the post in the DB), I could see there being confusion around editing a post's data and not understanding that it will change it everywhere. Also, there'd still be an issue around saving post data — would the data be saved immediately? When you published the post/page that contains the customized block? What if the page containing this block is scheduled, would we only update the post data when the page is published?

This is all related to global change saving. See the discussions on #18029.

>But what if these post-related blocks are used outside of a post block? Or, is that not something we'd want, or would consider useful?

They will inherit the root post ID if any, otherwise they will show a placeholder. This approach optimizes for being able to easily move these blocks between post and query blocks and reuse layout pieces across different contexts without having to deal with post-selection at multiple levels.

**Comment by MikeWhelan** [comment]
> It would be good to also recognise and support the site's global date format, per the setting on `wp-admin/options-general.php`, including honouring whatever custom value it may have:
> 
> <img alt="Captura de ecrã 2020-01-17, às 11 54 45" width="313" src="https://user-images.githubusercontent.com/150562/72610768-30484200-3920-11ea-9af2-a042e6b28f77.png">

It's been two years since this announcement was made. When will it be possible to use a date block that defaults to site's global format?  In my case, I just want to show the year ( 'Y' ), but that option is not available, even though it is specified in my global options.
