### ISSUE TITLE
i18n Inline Format for Localizing Posts and Templates

### ISSUE THREAD

**Issue by epiqueras** [WordPress/gutenberg#19707]
The future of Gutenberg requires a way for user content to be translatable. Not only for things like distributing posts in multiple languages, but also for localizing block templates and other site-wide content like block template parts.

I propose we add a new inline format, `core/i18n`, to the format library for this, with a server-side rendering component to it.

**Comment by Thelmachido** [comment]
Hi @epiqueras there hasn't been much movement on this in the last two years. I will close this, for now, please feel free to review and reopen the issue.
