### ISSUE TITLE
Featured image panel now looks like a button

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19708]
**Describe the bug**
It appears that the fix for #17739 ( PR #17754 ) has broken the styling of the thumbnail in the Featured Image panel. 

**To reproduce**
1. Activate Gutenberg 
2. Add new post
3. Click on Set Featured image
4. Choose image - pick a squarish one
5. See just part of the image displayed in the button
![image](https://user-images.githubusercontent.com/2474435/72546854-6a173b00-3883-11ea-9889-d236a6df3678.png)

**Expected behavior**
With Twenty Twenty theme and NO plugins.

![image](https://user-images.githubusercontent.com/2474435/72546979-a9de2280-3883-11ea-916f-aa9343588d4c.png)

**Screenshots**
See above plus. 
View in Gutenberg 7.1.0, 7.0.0 and 6.9.0
With 6.8.0 it's fine
![image](https://user-images.githubusercontent.com/2474435/72547341-60da9e00-3884-11ea-9dcb-359770b0d046.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] current

**Smartphone (please complete the following information):**

**Additional context**
Problem occurs with Gutenberg 6.9.0 and above.

**Comment by ehti** [comment]
Still happening for you @bobbingwide ? Can't seem to reproduce in Gutenberg 7.91.

**Comment by jorgefilipecosta** [comment]
This issue was fixed before the WordPress 5.4 release.
