### ISSUE TITLE
Navigation: Implement drag and drop for reordering navigation block links

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19703]
There currently is not way to move a top-level item into a submenu item, or reposition a submenu item and its children outside of a submenu.

Navigation link blocks should be able to be moved around via a drag handle and placed in the top-level or nested within a submenu. 

**Describe the solution you'd like**
Show the drag handle between the arrows (as of this writing, it's hidden via CSS) and allow items to be drag/dropped anywhere in the navigation block.

**Describe alternatives you've considered**
For now, we've hidden this functionality, as you can move items within their current level using the arrows.

**Comment by tellthemachines** [comment]
It's already possible to move Navigation links between nesting levels with drag and drop; can we close this issue now, or is there anything left to address?

**Comment by draganescu** [comment]
I think we can close this issue.
