### ISSUE TITLE
Losing the block toolbar when dragging block in/out of Group block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19714]
**Describe the bug**
When dragging a block in or out of the Group block, the block's toolbar disappears and won't come back unless you click off block and back again.

**To reproduce**
1. Create a Group block. 
2. Add some blocks inside the Group block.
3. Drag one of those blocks outside the Group block.
4. Observe the block's toolbar disappears.

**Expected behavior**
I expect the block's toolbar to remain visible when dragging in and out of the Group block.

**Screenshots**

![lost-toolbar 2020-01-16 18_39_40](https://user-images.githubusercontent.com/617986/72580121-e7e14380-388f-11ea-864e-1302e7fa57fb.gif)

**Desktop (please complete the following information):**
 - OS X Catalina
 - Firefox 72.0.1
 - Gutenberg 7.2

**Comment by youknowriad** [comment]
I'm not able to reproduce this, it seems fixed for me.
