### ISSUE TITLE
Text view - very small area click-area to start typing content

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1971]
## Issue Overview
When in "text" view/mode I have a hard time finding the place to click to be able to start typing content.

## Steps to Reproduce (for bugs)

1. Create a new post
2. Switch to "text" mode
3. Click on the title and type something
4. Click anywhere on the white "canvas" to start typing content

## Expected Behavior
I expect the entire white canvas, except for the title-block, will focus the editor so I can just start typing my content.

## Current Behavior
There is a very small area on which the textarea lives, which will let me focus it .
The only way to know that you can click there is the change of cursor, which is very subtle.

![text view - click to type](https://user-images.githubusercontent.com/2005352/28465061-ca404f40-6e27-11e7-9a6d-948443ff0841.gif)

## Possible Solution
Make the entire canvas listen for a mouse click/touch event and focus the textarea when triggered.

**Comment by youknowriad** [comment]
This has seen some updates recently and can't be reproduced any more
