### ISSUE TITLE
Google Chrome cant render Gutenberg-Editor fonts

### ISSUE THREAD

**Issue by Skyfuller1303** [WordPress/gutenberg#19718]
**Describe the bug**
Gutenberg Text-Editor cant show font NonBreakingSpaceOverride and"Hoefler Text"

**To reproduce**
1. Go to 'Sites'
2. Open a Site

**Screenshots**
[https://i.imgur.com/feL77nS.png](url)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2
 - Browser Chrome v79.0.3945.117 (left), Firefox v73.0b5 (right)

**Additional context**
Wordpress Version 5.3.2
<img width="1825" alt="Bildschirmfoto 2020-01-17 um 10 56 05" src="https://user-images.githubusercontent.com/58360545/72603690-ca58bc00-3919-11ea-9354-fb4178aa4704.png">

**Comment by youknowriad** [comment]
What theme are you using? I personally can't reproduce with TwentyTwenty theme. But from the screenshot your theme is adding editor styles to the editor and loading its fonts. So it's probably a theme issue and better raised in the theme tracker.

**Comment by aduth** [comment]
I believe this may be an upstream issue? https://bugs.chromium.org/p/chromium/issues/detail?id=1036250

Specifically in how Chrome + macOS render the "Hoefler Text" font, which is used in the TwentyNineteen and TwentyNineteen themes.

(That said, I use this same browser, OS, theme combination and have never been able to reproduce this)

**Comment by youknowriad** [comment]
Thanks for the heads up @aduth Let's close then in favor of the upstream issue.
