### ISSUE TITLE
Button prop isSecondary not rendering

### ISSUE THREAD

**Issue by martinowren** [WordPress/gutenberg#19728]
**Describe the bug**
Button prop isSecondary does not render is-default button styles. 

**To reproduce**
![image](https://user-images.githubusercontent.com/22822433/72631191-39530680-3954-11ea-8326-6dd9b111306b.png)

**Expected behavior**
Applies the default button styles 
![image](https://user-images.githubusercontent.com/22822433/72631393-7a4b1b00-3954-11ea-9c79-889c8c934568.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/22822433/72631245-4ff95d80-3954-11ea-9db6-4d6f7402694a.png)

**Comment by youknowriad** [comment]
Hi There are you using the Gutenberg plugin? This waas recently introduced and may come to WordPress in 5.4. You can use isDefault in Core today.

**Comment by martinowren** [comment]
That explains is, downloaded and installed the gutenberg plugin, and `isSecondary` now works. Maybe there should be something in the Block Editor Handbook that states if a feature is in core or not?
Ref: https://developer.wordpress.org/block-editor/components/button/

**Comment by youknowriad** [comment]
Ultimately all these APIs end up in Core. I left a comment here https://meta.trac.wordpress.org/ticket/4244#comment:8 to consider switching the branch used to publish the handbook to the one already in Core.
