### ISSUE TITLE
Admin menu collapses for 960px width but editor doesn't

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#19732]
**Describe the bug**
This was originally noted by @JJJ on core Trac here - https://core.trac.wordpress.org/ticket/49212
After reproducing and investigating I found the issue lies in Gutenberg here;
https://github.com/WordPress/gutenberg/blob/4310db7712c19e54c28028ff343daa96ba73b3d7/packages/edit-post/src/components/editor-regions/style.scss#L36
*This mixing creates a min-width: 960px breakpoint, editing in inspect to 961px resolved the issue.

**To reproduce**
Steps to reproduce the behaviour:
1. Install WP Trunk or Gutenberg latest plugin
2. Navigate to the Editor
3. Resize your browser to exactly 960px wide
4. See white gap on the left.

**Expected behavior**
The editor and menu should respond together.

**Screenshots**
<img width="1072" alt="Screen Shot 2020-01-16 at 7 12 55 PM" src="https://user-images.githubusercontent.com/8726005/72638986-836ac680-3919-11ea-9e60-13ac01c1c019.png">

**Details**
 - OS: macOS Catalina 10.15.2
 - Browser: Chrome 79.0.3945.117
- WP: Trunk

**Comment by jorgefilipecosta** [comment]
Hi @garretthyder, I'm not being able to reproduce this issue. Maybe it was resolved as a side effect of another change. Would it be possible to repeat the test on the last version of Gutenberg (or even better Gutenberg master) with the last version of WordPress trunk?

**Comment by garretthyder** [comment]
Thanks for testing @jorgefilipecosta I just retested using WP trunk and Gutenberg master and was able to reproduce the issue. It is a little difficult to reproduce as it's only present at exactly 960px. At 956 or 961 the issue dissappears.
Myself I see the issue daily as I use Divvy to split my screen in two and 960px is exactly half so everytime I load the editor in half a screen the issue presents itself.

Let me know if you're still unable to reproduce.

**Comment by jorgefilipecosta** [comment]
Thank you I think I was being affected by other parallel change. In my last test, I was able to reproduce the issue.
