### ISSUE TITLE
Issues w/ Welcome Guide

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#19733]
**Describe the bug**
Love the new Welcome Guide concept that popped up on my trunk install. Some minor issues I've come across;
1. The close dialog button overlaps the content;
![Screen Shot 2020-01-17 at 10 37 47 AM](https://user-images.githubusercontent.com/8726005/72640287-6daad080-391c-11ea-99e3-84357264989a.png)
2. On smaller screensize (960px) the text becomes a skinny column;
![Screen Shot 2020-01-17 at 10 38 23 AM](https://user-images.githubusercontent.com/8726005/72640360-903ce980-391c-11ea-90c9-6d4de3f2dfc7.png)
Note: I noticed #19209 which present a revamp that should resolve this.
3. The text inside of the next/prev buttons isn't vertically centered;
![Screen Shot 2020-01-17 at 11 35 01 AM](https://user-images.githubusercontent.com/8726005/72640796-7a7bf400-391d-11ea-9f12-bc96ef212069.png)
Note: Seems setting them to 16px font-size fixed that;
![Screen Shot 2020-01-17 at 11 35 11 AM](https://user-images.githubusercontent.com/8726005/72640825-8962a680-391d-11ea-8ac9-2aa1cc5aad4d.png)

**To reproduce**
1. Install Latest
2. Goto Editor
3. Click on the triple dot menu
4. Click on the Welcome Guide
5. View on smaller screen or resize browser.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Browser: Chrome 79.0.3945.117
- Gutenberg: WP Trunk

**Comment by gziolo** [comment]
Some similar issues I see on iPhone X and Safari:

![Coulinarnia — WordPress com-1](https://user-images.githubusercontent.com/699132/72659107-ebbdb480-39ba-11ea-9d29-1ab85d7808d5.png)

![Coulinarnia — WordPress com](https://user-images.githubusercontent.com/699132/72659113-02640b80-39bb-11ea-97ff-50e330e6a609.png)

**Comment by mtias** [comment]
There's a redesign proposed that addresses most of these concerns in https://github.com/WordPress/gutenberg/issues/19209

**Comment by garretthyder** [comment]
Thanks @mtias re-reviewing the ticket you're right and they also seem to address the placement of the x raised by @gziolo so am closing this ticket in favour of the redesign in #19209.
