### ISSUE TITLE
The Add New Tag field in the post editor is missing a scoll bar

### ISSUE THREAD

**Issue by DeveloperWil** [WordPress/gutenberg#19740]
**Describe the bug**
When editing a post, the Add New Tag field in the Tags meta box does have a scroll bar.

**To reproduce**
1. create a new post
2. in the Tags meta box, add 10 tags
3. navigate out of the meta box
4. navigate back into the meta box

You cannot see all 10 tag or navigate to them correctly because there is no scroll bar on that field.

**Expected behavior**
I would expect a scroll bar to be on the Add New Tag field to be able to scroll through all the tags in the limited space available.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 79.0.3945.117

**Additional context**
WordPress 5.3.2

**Comment by ntsekouras** [comment]
Hey @DeveloperWil - is this still relevant? I tried to find some code through the last year that would have solved this but with no luck. It seems okay :)

<img width="267" alt="Screenshot 2021-03-26 at 8 28 56 PM" src="https://user-images.githubusercontent.com/16275880/112677231-239f7200-8e72-11eb-8ac6-718802e3f663.png">

**Comment by DeveloperWil** [comment]
Seems to be resolved for me now.
