### ISSUE TITLE
Group Block - Add option to Move up/down for nested child blocks 

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#19748]
In a Group block, the nested child blocks don't have the option to be moved up or down.

What's happening, no Move up/down option on the left side:
![Screen Shot on 2020-01-19 at 15:16:35](https://user-images.githubusercontent.com/15944096/72676653-b30eff80-3ace-11ea-9491-bb51a739e08a.png)

What I expect, have the Move up/down option on the left side:
![Screen Shot on 2020-01-19 at 15:17:24](https://user-images.githubusercontent.com/15944096/72676664-d6d24580-3ace-11ea-9fb5-e9edd9f79906.png)

Would this be solved by #18014?

**Comment by youknowriad** [comment]
This was fixed recently. Thanks
