### ISSUE TITLE
Update "Preview" button to "View" if there are no changes

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#19750]
Currently we show a "Preview" button even when the post has no changes — marked by "Update" being disabled:

![Screenshot 2020-01-19 at 17 07 41](https://user-images.githubusercontent.com/4389/72685086-764b0480-3ade-11ea-988c-51cd38f03869.png)

What are we "pre-viewing" if the post is the same? It always makes me wonder if the "Preview" link does something different from just getting me to the post on the front-end.

Unless I'm missing a reason for this, I feel that the button should be marked as "View" if there are no changes, thus having these two states:

If there aren't changes:
![Screenshot 2020-01-19 at 17 10 06](https://user-images.githubusercontent.com/4389/72685101-a72b3980-3ade-11ea-9a92-e735fbb4a981.png)

If there are changes:
![Screenshot 2020-01-19 at 17 07 51](https://user-images.githubusercontent.com/4389/72685094-88c53e00-3ade-11ea-86b5-cb9f47f7fdf4.png)

**Comment by ZebulanStanphill** [comment]
The preview tab refreshes automatically to reflect changes in the editor, so technically the Preview button does have a different effect than a simple "View" button. It's a live-reloading view of the latest version of the post (published or unpublished).

**Comment by folletto** [comment]
I just realized what you just said... is the cause of another issue I couldn't identify — **ghost auto-saves**. It seems that every time I click "Preview" it generates one, even if the post has no edits, and triggering this "Auto-Saves" error in case of reload:

![Screenshot 2020-01-20 at 17 15 04](https://user-images.githubusercontent.com/4389/72745783-7283b480-3ba8-11ea-8594-0a45fa97e47d.png)

![Screenshot 2020-01-20 at 17 15 17](https://user-images.githubusercontent.com/4389/72745827-87f8de80-3ba8-11ea-97aa-28c30340283a.png)

If this is the case, then it's not just a very opaque feature — it's also creating the problem above.

I'd think that changing to "View" and only triggering "Preview" when there's actually the need of an auto-save the it would solve both problems.

**Comment by aduth** [comment]
> I just realized what you just said... is the cause of another issue I couldn't identify — **ghost auto-saves**. It seems that every time I click "Preview" it generates one, even if the post has no edits, and triggering this "Auto-Save" error in case of reload:

It would be worth testing to see if this still happens with the "Preview externally" link in the new preview dropdown. I sense it probably behaves the same as it did previously (including the redundant saves?)

![image](https://user-images.githubusercontent.com/1779930/75473753-c03bcb80-5963-11ea-8975-819893877c4f.png)

Seems like it may be a related but separate issue than that originally reported here. Would be good to have tracked if it still occurs.

Noticed a related Trac ticket: https://core.trac.wordpress.org/ticket/49532 (should probably be tracked in GitHub instead/in addition)

**Comment by aduth** [comment]
Ah, I see that @Inwerpsel reported this at #20505 as well.

**Comment by folletto** [comment]
> The UI changed with the devices dropdown, I believe we can close this issue now.

I don't think the new UI addresses the issue I raised here. The dropdown doesn't solve the ambiguity of view/preview, if anything, makes it worse.

This was raised again as an issue in slack:
https://wordpress.slack.com/archives/C02S78ZAL/p1583429569244200

And a new issue was opened:
https://github.com/WordPress/gutenberg/issues/20602

**Comment by jasmussen** [comment]
Reopening this per discussions in #20602.

**Comment by folletto** [comment]
To summarize the discussion that overlapped in the other thread, we need to:

* have both a "View" if no-changes or "Preview" if changes (UI side)
* have a fix: "View" shouldn't trigger a revision being created (API side)

**Comment by shaunandrews** [comment]
I don't think most people will understand the distinction between Preview and View — nor do I think most people will even notice the label changing at all.

With that in mind, I think this suggestion adds complications to the UI with no real benefit to the end user.

**Comment by folletto** [comment]
Even if it's not a major issue, I disagree. This emerged already multiple times, and dismissing it doesn't make us a favor. The last one was highlighted in the Slack chat above.

It's fine if people won't notice the difference, it's not meant to be a big change, so that's a fine outcome. Yet the underlying logic is important. It's not _just_ a label change (notice the two bullet points). It also changes the behaviour.

**Comment by Mamaduka** [comment]
Should we close this now that there's a separate "View Post"  button for published posts?

**Comment by jasmussen** [comment]
I'll tentatively close this one as fixed by the following flow:

![view](https://github.com/WordPress/gutenberg/assets/1204802/28e52d93-43d2-42f8-8c95-6f27576c4e2f)

Though I will also point to conversation on [this thread](https://github.com/WordPress/gutenberg/issues/51006#issuecomment-1580324356) where it's discussed whether we can show the "View post" button _always_, not just when a post is published first. That issue can be reopened if need be, as it contains some valid nuance from a developer. And with this link it should also be connected to this older issue for even deeper context!

And even if closing here is in error, we can always reopen 🙏
