### ISSUE TITLE
Updating the browser history should take into account URL fragment identifiers

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1976]
When saving a post, `REQUEST_POST_UPDATE_SUCCESS` does its job and at the end updates the browser history, appending the post ID to the URL in the browser's address bar.

However, it currently doesn't take into account URL fragment identifiers such as the ones appended to the URL when using the "skip links", leading to unexpected behaviors.

The easiest way to reproduce is:
- go in the Gutenberg "New Post" page
- using the keyboard, tab to make the "Skip to main content" link appear
- press Enter to activate the skip link
- the initial URL parameter changes from `?page=gutenberg` to `?page=gutenberg#wpbody-content`
- write something in the post and save
- in the address bar there's now something like `?page=gutenberg%23wpbody-content&post_id=2395`, notice the hash `#` has been URL encoded and the URL fragment identifier is now part of the page parameter name
- refresh the page 
- since the page `gutenberg%23wpbody-content` doesn't exist, all you get is:

<img width="1155" alt="screen shot 2017-07-22 at 13 02 53" src="https://user-images.githubusercontent.com/1682452/28490865-b02c82f0-6ee4-11e7-9e71-63bcd6251f32.png">

Worth noting this happens also with other fragment identifiers ("skip to toolbar" or any other one that plugins might use).

**Comment by westonruter** [comment]
@afercia give #1984 a try.
