### ISSUE TITLE
ESLint Plugin: Add I18N ESLint rules

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#19777]
**Is your feature request related to a problem? Please describe.**

Similar to the i18n sniffs in WPCS there could be some custom ESLint rules to catch some common i18n mistakes.

**Describe the solution you'd like**

Off the top of my head, there could be rules like follows:

**Done**

* [x] Missing text domain
* [x] Mismatched text domain (would require setting the expected text domain in the ESLint config)
* [x] Unnecessary text domain (e.g. when passing `default` instead of just omitting it)
* [x] Missing translator comments when using `sprintf` with placeholders
* [x] ~Not using numbered placeholders when using `%s` and `sprintf`~ -> tracked separately in #20554.

**Likely to-do**

* [x] Using variables instead of string literals (see https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-plugin-wpcalypso/lib/rules/i18n-no-variables.js, https://github.com/WordPress/gutenberg/blob/622362a6e43164e2d3f3697303e63ee90cb0f297/.eslintrc.js#L70-L87)
* [x] Using three dots instead of ellipsis (see https://github.com/Automattic/wp-calypso/blob/8fec020a3cd6baee6a84bf2b200ed11170593ad7/packages/eslint-plugin-wpcalypso/lib/rules/i18n-ellipsis.js, https://github.com/WordPress/gutenberg/blob/622362a6e43164e2d3f3697303e63ee90cb0f297/.eslintrc.js#L88-L92)
* [x] Using collapsible whitespace in strings (see https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-plugin-wpcalypso/lib/rules/i18n-no-collapsible-whitespace.js)
* [x] Using strings which include only placeholders (see https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-plugin-wpcalypso/lib/rules/i18n-no-placeholders-only.js)
* [ ] String containing thing which should probably be `%s` placeholders instead (e.g. URLs)

**On the fence**

* [ ] Non-translatable text  
  Needs some way to detect whether text is passed as a prop or child that should probably be translatable (e.g. `aria-label` prop). Helps catch places where `__()` is forgotten.
* [ ] String concatenation within `__()` (e.g. `__( 'Hello' + '' + 'World' )`
* [ ] Suggest using `_x()` instead of `__()` under certain conditions (needs list of ambiguous terms)
* [ ] When using markup in strings but not `__experimentalCreateInterpolateElement`
* [ ] String concatenation with markup instead of using `__experimentalCreateInterpolateElement`
* [ ] Using translation functions as `defaultProps` (when using prop-types)

Actual implementation should be split up into multiple PRs.

**Describe alternatives you've considered**

Find other solutions out there that likely won't work with `@wordpress/i18n` or build something custom.

**Comment by swissspidy** [comment]
I have a working version of text domain validation ready, will push it soon.

> Passing a variable to `__()` et al instead of a string literal

This is currently enforced using `no-restricted-syntax`:

https://github.com/WordPress/gutenberg/blob/4ea066829724caf7641af9a60bbbf5b38e2036b5/packages/eslint-plugin/configs/custom.js#L8-L28

Should be fairly easy to port this to its own proper rule.

**Comment by swissspidy** [comment]
> Needs some way to detect whether text is passed as a prop or child that should probably be translatable

Some cases, off the top of my head:

* `aria-*` attributes
* string between tags, e.g. `<div>Hello World</div>` or `<div>{ 'Hello World' }</div>`
* additional attributes could be added via whitelist

Might even be fixable by wrapping the found strings in `__()`

**Comment by gziolo** [comment]
It looks like a lot of tasks listed are done. Excellent work! There is only one left on the list that was initially marked as “likely to do”. @swissspidy, what would be your current recommendation on criteria to consider this issue finished?

**Comment by swissspidy** [comment]
I was just thinking the pther day that a rule for catching trailing whitespace would be nice. See https://core.trac.wordpress.org/ticket/55669

This mistake wasn‘t caught in the Gutenberg code base.

**Comment by gziolo** [comment]
> I was just thinking the pther day that a rule for catching trailing whitespace would be nice. See https://core.trac.wordpress.org/ticket/55669
> 
> This mistake wasn‘t caught in the Gutenberg code base.

I agree that it would be great to cover as much as possible from the cases that slipped through WP 6.0 Beta phase from the Gutenberg repository ❤️

**Comment by swissspidy** [comment]
Looks like #38225 introduced such a rule (`i18n-no-flanking-whitespace`)

Edit: this begs the question why it didn't catch dd7db32c1a3430046576b9c2da3f306d7cec06d2

**Comment by swissspidy** [comment]
Looks like the rule was only enabled for React Native code and not the whole code base 🙃 

@jhnstn Do you recall why it wasn't considered to apply the `i18n-no-flanking-whitespace` rule for the rest of the code base? Seems like a missed opportunity.

**Comment by gziolo** [comment]
> @jhnstn Do you recall why it wasn't considered to apply the `i18n-no-flanking-whitespace` rule for the rest of the code base? Seems like a missed opportunity.

It would be great to find out and potentially enable for the rest of Gutenberg 👍🏻
