### ISSUE TITLE
7.3 RC: Warning of missing file 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#19770]
**Describe the bug**
Warning: file_get_contents(/app/public/wp-content/plugins/gutenberg/build/block-library/blocks/shortcode.json): failed to open stream: No such file or directory in /app/public/wp-content/plugins/gutenberg/build/block-library/blocks/shortcode.php on line 25

Appears when activating Gutenberg plugin 7.3. RC1 

**To reproduce**
1. Create a clean WordPress instance
2. Install Gutenberg 7.3 RC and activate
3. Enable Debugging
4. Use any of the default Themes

Error message appears on top of the screen. 

**Expected behavior**
no warning or missing file

**Screenshots**
![Screen Shot 2020-01-20 at 7 22 40 PM](https://user-images.githubusercontent.com/39980/72765406-4a9d4c80-3bba-11ea-9c07-1e3772d38004.png)

**Desktop (please complete the following information):**
 - OS: 10.15.2
 - Browser : Chrome
 - Version: Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by aduth** [comment]
Likely related to #19534 (cc @koke, @chipsnyder, @gziolo).

If it's a necessary file, it needs to be included in the files/patterns targeted for plugin build here:

https://github.com/WordPress/gutenberg/blob/1ffedef81e0a6bfe830d4783361e27aeef2745ba/bin/build-plugin-zip.sh#L112-L126

**Comment by gziolo** [comment]
Fixed by @ockham with #19772.

**Comment by ellatrix** [comment]
Let's close since this has been fixed.
