### ISSUE TITLE
Unhandled Metabox APIFetch Promise Failure, Perpetual Spinning Save Loop

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#19780]
**Describe the bug**

Note this code:

```js
		additionalData.forEach( ( [ key, value ] ) => formData.append( key, value ) );

		// Save the metaboxes
		apiFetch( {
			url: window._wpMetaBoxUrl,
			method: 'POST',
			body: formData,
			parse: false,
		} )
			.then( () => store.dispatch( metaBoxUpdatesSuccess() ) );
	},
	SWITCH_MODE( action ) {
		// Unselect blocks when we switch to the code editor.
```

https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/store/effects.js#L109-L115

The `apiFetch` call has no catch or failure handler. As a result, if you press save just before your train heads into a tunnel, or a PHP fatal error occurs, or your login cookies expired a second or two earlier and you need to login, or any other reason it might fail or not return 200, it will fail.

But because there is no error handling, `metaBoxUpdatesSuccess` is never called, and the UI is now in an undefined state. To the end user, this looks like a saving spinner that never goes away, and there is no UX to step back and re-attempt a save. The user has to go back/refresh and looses their work.

Additionally there is `REQUEST_META_BOX_UPDATES` and `META_BOX_UPDATES_SUCCESS` but no `META_BOX_UPDATES_FAILURE`

**Expected behavior**

When the call fails, it should catch the error and either retry, or present it to the user

**Comment by noisysocks** [comment]
Possibly related: #6966

**Comment by planetwarevince** [comment]
Changing:
```js
    external_this_wp_apiFetch_default()({
      url: window._wpMetaBoxUrl,
      method: 'POST',
      body: formData,
      parse: false
    }).then(function () {
      return store.dispatch(metaBoxUpdatesSuccess());
    });
```
...to:
```js
    external_this_wp_apiFetch_default()({
      url: window._wpMetaBoxUrl,
      method: 'POST',
      body: formData,
      parse: false
    }).then(function () {
      return store.dispatch(metaBoxUpdatesSuccess());
    }).catch(function(){
      console.log("Caught error that wordpress core missed!  Re-enabling save/update/publish button.");
      return store.dispatch(metaBoxUpdatesSuccess());
    });
```
...fixed the issue for me.  Hopefully a proper/permanent fix can be added to the core.

Thanks!

**Comment by paaljoachim** [comment]
@noisysocks Robert.
We have two issues that seem related how can we move a solution forward and get both issues fixed?
