### ISSUE TITLE
Navigation: Submenu + Icon disappears when focusing a submenu navigation link

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19788]
When a submenu navigation link block receives focus, the + icon to add another submenu link disappears.

**To reproduce**
1. In the editor, click a top level navigation link that has a submenu (or create one and do this)
2. See the + is visible to click to add a new submenu item
3. Click an existing submenu item to give it focus
4. See the + to add a new submenu item is no longer visible

**Expected behavior**
Previously, the + icon was available to add another submenu item in this situation. As it stands, the only way to add a new submenu item is to click back to the top-level item so it will show the + to add a submenu item again 😢 

**Screenshots**
![+ disappears on submenu select](https://user-images.githubusercontent.com/967608/72825855-685fc580-3c3d-11ea-991f-6974e78343bc.gif)

**Desktop (please complete the following information):**
 - OS: Mojave MacOs
 - Browser Chrome, Safari, and Firefox
 - Version: latest

**Additional context**
- Gutenberg `7.3.0-rc.1`

**Comment by jeryj** [comment]
It's caused by https://github.com/WordPress/gutenberg/commit/24c0e60c7ab0763d071266af5313e9b77a90b819#diff-2e071f8429cd2c500b830947ffde4239R200, but maybe it was intentional per discussion here: https://github.com/WordPress/gutenberg/pull/19598.

Not sure the best course, as the whole submenu is in redesign mode.

**Comment by draganescu** [comment]
Hey @jeryj , it was intentional, as there is the toolbar icon for adding a submenu icon. See @mtias 'comment here and the followup exchange https://github.com/WordPress/gutenberg/pull/19598#discussion_r365900580

I also find it somewhat weird but it does provide a cleaner UI as a result.

**Comment by jeryj** [comment]
@draganescu Thanks for pointing me there. I read through, and there's a lot of brain power involved in trying to track if the discussion is around adding a new submenu level vs an additional submenu item on the same level 😝 

I made two gifs to illustrate what I'm talking about to make sure we're on the same page. My specific UX focus here is creating a new submenu link item (not a new submenu). 

Here's a gif of a PR I'm working on with **the current state:**
![submenu item appender missing](https://user-images.githubusercontent.com/967608/72993294-c2d26080-3dba-11ea-8afd-f15a08eb5790.gif)

Here's the flow if you **revert back to showing the appender:**
![submenu item appender present](https://user-images.githubusercontent.com/967608/72993340-d8478a80-3dba-11ea-8dc3-82e3b148ec3e.gif)

In the current state, creating a submenu with multiple items (which I imagine is a common thing), is quite annoying. If the appender is present, it's _so_ much smoother. The current state requires you to *reselect* the parent of the submenu before you can see the appender to add another item to that submenu. 

I think your PR cleaned up a lot of the annoying trailing appenders all over the place, and is much better overall. I'd still like to see the appender for the current submenu level, even if you're on an item within that though. 

What do you think would be a good way forward here?

**Comment by jeryj** [comment]
@draganescu, I put in a PR https://github.com/WordPress/gutenberg/pull/19846 that changes it slightly. There's still a chance of getting multiple + appenders next to each other, but it still greatly reduces the visible appenders while *hopefully* showing you the ones you need at the moment.
