### ISSUE TITLE
Different Size Columns Based on Screen Size

### ISSUE THREAD

**Issue by ChristinaSW** [WordPress/gutenberg#19783]
**Is your feature request related to a problem? Please describe.**
With some layouts, there are different size columns for different screen sizes such as on desktop the columns may be 40%, but on iPad they may be 50%. There is no way to set a different column size based on tablets and phones unless you set it in CSS. This is fine for developers, but not for end clients.

**Describe the solution you'd like**
Would like to see a tablet and phone option for column sizes

**Describe alternatives you've considered**
Setting sizes in css. Restyling what is already there based on screen size.

**Comment by talldan** [comment]
Thanks for reaching out @ChristinaSW. There's an existing issue, https://github.com/WordPress/gutenberg/issues/13363, where a lot of this has been explored.

There's also https://github.com/WordPress/gutenberg/issues/19909, which is on the same theme.

As it seems like there are already a couple of issues exploring the same topic, I'm going to close this issue as a duplicate.

I'd also like to mention https://github.com/WordPress/gutenberg/pull/19082, which proposes to add options for viewing blocks in different viewports/screen sizes.
