### ISSUE TITLE
Allow media workflow to be passed to MediaUploadButton

### ISSUE THREAD

**Issue by joemcgill** [WordPress/gutenberg#1979]
## Issue Overview

In #1820, a `gallery` prop was added to the `MediaUploadButton` component, which is used to select a custom workflow for creating an image gallery. This works, but it seems like a better solution might be to let components using `MediaUploadButton` pass a custom workflow (e.g., `wp.media.frame` ) to the `MediaUploadButton` instead, since we're likely going to need custom workflows for many different kinds of media blocks that access the media modal.

## Related Issues and/or PRs

* 1820

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518715323000493)._

**Comment by antpb** [comment]
@joemcgill  do you think this would be solved with the work being done in #6523 ? I know we'll be looking at this in the coming days. If this issue is a duplicate, I say we merge it with https://github.com/WordPress/gutenberg/issues/6523

**Comment by antpb** [comment]
to add...this is now related: https://github.com/WordPress/gutenberg/issues/8748

**Comment by youknowriad** [comment]
Doing some triage today and landed in this issue.

I think instead of focusing on technical matters (passing a "flow" prop which is loosely defined) we should focus on solving use-cases like #6523 ... 

I'm thinking we should close this issue.

**Comment by youknowriad** [comment]
I think we can close now with the last updates to MediaUpload. Let's open more specific issues if needed.
