### ISSUE TITLE
wp-block-subhead class selectors in editor/block-library styles

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19797]
**Describe the bug**
There are still styles targetting the `wp-block-subhead` class in the Gutenberg editor block-library styles.

**To reproduce**
1. Insert cover block.
2. Add some text to it.
3. Inspect the text element.
4. In developer tools, open the Computed tab.
5. Expand `color` attribute.
6. Notice that the `inherit` value stems from the Gutenberg editor block-library `styles.css`.

**Expected behavior**
As the Subhead block had been [retired from Gutenberg](https://github.com/WordPress/gutenberg/pull/9355) for many months, 
there shouldn't be any Subhead block related styles left, not even for backward compatibility,
because there had also been a deprecation phase.

**Comment by talldan** [comment]
Related - https://github.com/WordPress/gutenberg/issues/19267

**Comment by paaljoachim** [comment]
I am seeing two issues that address similar concerns.

Pinging:
@WordPress/gutenberg-core

**Comment by youknowriad** [comment]
At the moment, the block is still there to support old content. Until then we can't remove the styles. See #19267 for potential removal.
