### ISSUE TITLE
Individual Block Designs

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#198]
**Embed**

Empty:

![embed-empty](https://cloud.githubusercontent.com/assets/1204802/23659122/659ce794-0345-11e7-8146-61bc5267c327.png)

Neutral:

![embed-neutral](https://cloud.githubusercontent.com/assets/1204802/23659127/6cfc575e-0345-11e7-91f1-e254e7e9cc78.png)

Selected:

![embed-selected](https://cloud.githubusercontent.com/assets/1204802/23659135/7181113e-0345-11e7-8268-734c23999bf5.png)

Caption:

![embed-caption](https://cloud.githubusercontent.com/assets/1204802/23659143/781f28be-0345-11e7-9f29-19576dedb470.png)

**Gallery**

Neutral:

![gallery-neutral](https://cloud.githubusercontent.com/assets/1204802/23659155/87f1b414-0345-11e7-8022-bae8f95e59ba.png)

Selected:

![gallery-selected](https://cloud.githubusercontent.com/assets/1204802/23659160/8bdc2136-0345-11e7-8150-297c856ac5d7.png)

Individual image selected:

![gallery-image-selected](https://cloud.githubusercontent.com/assets/1204802/23659178/98f397d2-0345-11e7-8e0a-85d0c47327f6.png)

_Mouse over an image to see the move/drag hand so you can rearrange_

Caption:

![gallery-caption](https://cloud.githubusercontent.com/assets/1204802/23659197/a3201ef6-0345-11e7-86af-1048c1a813ff.png)

**Image**

Neutral:

![image-neutral](https://cloud.githubusercontent.com/assets/1204802/23659213/ad62948e-0345-11e7-9800-51e0377f7f76.png)

Selected:

![image-selected](https://cloud.githubusercontent.com/assets/1204802/23659218/b17f5174-0345-11e7-8098-3873efbbe7eb.png)

Caption:

![image-caption](https://cloud.githubusercontent.com/assets/1204802/23659223/b50c78da-0345-11e7-88b8-0b6fc686c6c0.png)

**Text**

Neutral:

![text-neutral](https://cloud.githubusercontent.com/assets/1204802/23659233/c46e8322-0345-11e7-84a0-e806875ddbfa.png)

Selected:

![text-selected](https://cloud.githubusercontent.com/assets/1204802/23659238/c8274fc6-0345-11e7-9137-2dc4edf60d0d.png)

**Heading**

Neutral:

![heading-neutral](https://cloud.githubusercontent.com/assets/1204802/23659251/d0e282ca-0345-11e7-95da-38724d9434ee.png)

Selected:

![heading-selected](https://cloud.githubusercontent.com/assets/1204802/23659254/d526d6d8-0345-11e7-88bc-e9d340f376f0.png)

**Quote**

Neutral:

![quote-neutral](https://cloud.githubusercontent.com/assets/1204802/23659265/df3d05b6-0345-11e7-92e0-7fadbf71cd5f.png)

Selected:

![quote-selected](https://cloud.githubusercontent.com/assets/1204802/23659271/e2b68aaa-0345-11e7-9649-85ef08521cce.png)

Citation:

![quote-citation](https://cloud.githubusercontent.com/assets/1204802/23659280/e700067c-0345-11e7-90a7-34a70f22e135.png)

**Quote 2**

Neutral:

![quote 2-neutral](https://cloud.githubusercontent.com/assets/1204802/23659290/f0a0d102-0345-11e7-967f-e47276537601.png)

Selected:

![quote 2-selected](https://cloud.githubusercontent.com/assets/1204802/23659296/f455da0e-0345-11e7-83f1-42e9cc932b78.png)

**Comment by iseulde** [comment]
Nice!

**Comment by mtias** [comment]
Lovely, thanks.

**Comment by shaunandrews** [comment]
Digin' it. Nice work.

<img width="438" alt="screen shot 2017-03-07 at 10 40 00 am" src="https://cloud.githubusercontent.com/assets/191598/23664037/6d82e08a-0322-11e7-849d-b41236d51532.png">

There's something about the multiple active items in these menu's that bothers me. There's no separation between groups of items, which makes it hard to grok what "things" are active, and what options are available for those active states. In the image above, for example, its unclear if clicking "B" will "unclick" the quote button.

**Comment by jasmussen** [comment]
> There's something about the multiple active items in these menu's that bothers me. There's no separation between groups of items, which makes it hard to grok what "things" are active, and what options are available for those active states. In the image above, for example, its unclear if clicking "B" will "unclick" the quote button.

Solid point, Shaun. I'm always tweaking the Sketch file I have, and in this case the block mockups went out with one where I tried a unified band approach. Seems like we need some separators, or bring back the separate bands approach that are shown in <a href="https://github.com/WordPress/gutenberg#mockups">the README mockups</a>.

**Comment by mapk** [comment]
> Seems like we need some separators

I agree. Separators help group selected items visually with what other items can be selected in their stead.

**Comment by mapk** [comment]
Forgive my ignorance, but is it _possible_ to float gallery blocks?

![screen shot 2017-03-07 at 9 01 35 am](https://cloud.githubusercontent.com/assets/617986/23668059/b78d2450-0314-11e7-90fd-f07773187b16.png)

**Comment by iseulde** [comment]
@mapk I think any object block should be allowed to float. Example: http://www.nytimes.com/projects/2012/snow-fall/#/?part=tunnel-creek

**Comment by jasmussen** [comment]
Closing in favor of all the mockups being shown in the README: https://github.com/WordPress/gutenberg#mockups

We can open individual tickets for individual blocks if issues arise. This sort of meta-ticket just becomes confusing :)
