### ISSUE TITLE
Moving multiple blocks deselects the blocks after a single action

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#19807]
Select multiple blocks and use the mover control to move up or down. 

Expected result: multiselection remains after moving.

Actual result: multiselection is cleared after moving.

GIF:

![mover](https://user-images.githubusercontent.com/1204802/72879803-f00d0900-3cfd-11ea-96cd-cbb63bfb636e.gif)

CC: @ellatrix in case you have insights.

**Comment by ellatrix** [comment]
I already made a PR for it yesterday: #19784

**Comment by jasmussen** [comment]
Of course you have 😅
