### ISSUE TITLE
Using standalone block-editor package inside metabox

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#19806]
Is it possible to use Gutenberg inside a metabox? For a custom post type, I have some HTML code inside a regular WP metabox (classic editor) that reads: `<div class="gutenberg__editor" id="boldermail-editor"></div>`

I copied the sample code from the block editor package:

```
import {
	BlockEditorProvider,
	BlockList,
	WritingFlow,
	ObserveTyping
} from '@wordpress/block-editor';
import { Popover } from '@wordpress/components';
import { useState } from '@wordpress/element';
import { render } from "@wordpress/element";
import { registerCoreBlocks } from '@wordpress/blocks';

function MyEditorComponent () {
	const [ blocks, updateBlocks ] = useState( [] );

	return (
		<BlockEditorProvider
			value={ blocks }
			onInput={ updateBlocks }
			onChange={ updateBlocks }
		>
			<WritingFlow>
				<ObserveTyping>
					<BlockList />
				</ObserveTyping>
			</WritingFlow>
			<Popover.Slot />
		</BlockEditorProvider>
	);
}

// Make sure to load the block editor stylesheets too
import '@wordpress/components/build-style/style.css';
import '@wordpress/block-editor/build-style/style.css';
import '@wordpress/block-library/build-style/style.css';
import '@wordpress/block-library/build-style/editor.css';
import '@wordpress/block-library/build-style/theme.css';

render( <MyEditorComponent />,  document.getElementById("boldermail-editor"));

registerCoreBlocks();
```
I keep getting an error that says `Object(...) is not a function`. The error goes away if I comment out the `registerCoreBlocks` function. I enqueue the built `index.js` file using:
```	$block_path = 'build/index.js';
wp_enqueue_script(
    'boldermail-editor',
    plugins_url( $block_path , __FILE__ ),
  [ 'wp-i18n', 'wp-element', 'wp-blocks', 'wp-block-library', 'wp-block-editor', 'wp-components', 'wp-editor' ],
  '1.0.0', true
);
```
I'm new to Gutenberg, so I'm not sure what I'm doing wrong. Is my approach to mix the classic editor with Gutenberg a dead end? My goal is to use Gutenberg similar to how the `wp_editor` function works. I currently have 3 instances of `wp_editor` inside different meta boxes, and would like to replace them with the new drag-and-drop editor.

**Comment by alessandrotesoro** [comment]
Have you had a look at this https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default ? It seems it's possible to create a "standalone" version of the editor. 

I have no experience with this, I just thought I'd mention it because I was doing research on the possibility of having gutenberg on a custom admin page to manage stuff not related with posts.

**Comment by youknowriad** [comment]
Definitely take a look at the playground, it's a good starting point to use the Gutenberg editor in a generic way outside the post editor.
