### ISSUE TITLE
Register sidebar with options instead of post_meta

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/gutenberg#19811]
Following this guide: https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/ it would be amazing to be able to create a sidebar using options instead of post_meta for data, so it can be accessed from every page/post.

**Comment by jorgefilipecosta** [comment]
Hi @dnnsjsk, the sidebar the block editor makes available is agnostic to where the data it uses is stored. The editor provides API's to render a sidebar; it is possible to render anything there and save the information anywhere, post_meta, site options, use a third party rest API to save it an external place.
So your use case should already be possible. The tutorial is only providing a sample with post meta, but it would be possible to use other data-source, e.g.: options provided they are exposed via an API.


I'm closing the issue, for now, feel free to comment if you need additional information.
