### ISSUE TITLE
Iteration on range control

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19845]
There are a number of limitations of our current range selector including the arrows often going missing and small spaces to interact with. #14166 audited this control, I took a dive into iterating this based on the great work being done in #18667.

As I am working on global styles, one of the controls will be the range one to interact with the typography scale, so this was a little diver deeper into that control.

<img width="270" alt="now" src="https://user-images.githubusercontent.com/253067/72996289-5ecb8e80-3df2-11ea-9143-6eaf45e6452a.png">

Before I dive in, props to @ItsJonQ for providing some fuel to the investigation I went on here. Some research links to share:

![image](https://user-images.githubusercontent.com/253067/72996429-9c301c00-3df2-11ea-9b96-a90d23615328.png)
Material tooltip

![image](https://user-images.githubusercontent.com/253067/72996449-a6eab100-3df2-11ea-84b2-5e2f278ef33d.png)
[Colored ranges](https://www.sketchappsources.com/resources/source-image/ranger-slider-gabrielsmelo.jpg)

Our range control has 2 states to adapt to so far (with idea it might need to flex):

- A scale without numbers.
- A scale that can also be increased by numbers.

I also wanted to explore later what a tooltip could bring in.

## Making it bigger

I began by starting to increase the hit space for the slider.

<img width="396" alt="range-basic" src="https://user-images.githubusercontent.com/253067/72996854-4d36b680-3df3-11ea-9c89-1b91b910aafa.png">

Then I began to explore how this could develop.

<img width="396" alt="range-mono" src="https://user-images.githubusercontent.com/253067/72996883-5b84d280-3df3-11ea-8db3-dc7d0e629886.png">

## Bring some color to it

Next, I brought in some tones and colors.

<img width="396" alt="range-color-versions" src="https://user-images.githubusercontent.com/253067/72996921-6d667580-3df3-11ea-81e9-d39b89c6657c.png">

## With numbers and arrows

How could this then scale to give both states? I first started with a larger version.

<img width="487" alt="range-largest" src="https://user-images.githubusercontent.com/253067/72996980-866f2680-3df3-11ea-8876-44a5a87d6cb2.png">

Then, I took it back a little to align more with the balance we have already.

<img width="457" alt="range-middle-color" src="https://user-images.githubusercontent.com/253067/72997010-925ae880-3df3-11ea-953c-d359da234a1c.png">

Finally, what about making the control stronger so it really focuses?

<img width="457" alt="range-middle-color-strong" src="https://user-images.githubusercontent.com/253067/72997451-51af9f00-3df4-11ea-9d75-d996ca2c7965.png">

## With tooltip

My final exploration was into what a tooltip could bring to this.

<img width="360" alt="range-middle-tooltip" src="https://user-images.githubusercontent.com/253067/72997281-06958c00-3df4-11ea-9c9a-a260eca29873.png">

## Feedback

I would love some feedback on the directions I am going in. As you can see this isn't a final polished piece yet, more exploring what could be here. As the work on advancing the interface is moving on, I want to be sure to align there so cc'ing in @jasmussen.

One little point, I haven't included reset yet here as focusing on the control, but a final version would, of course, show that. I also think maybe that becoming a link makes sense, but another issue should have that discussion.

**Comment by ItsJonQ** [comment]
@karmatosed These designs + suggestions are wonderful! In working through the experiments and technical side of [Global Styles](https://github.com/WordPress/gutenberg/issues/19611), it became clear that we'll be needing and relying on a lot of Controls. Therefore, these Controls need to stable and awesome 🙌 , for block controls, global styles controls, and beyond 🚀 

From simpler ones like Text/Number fields to Range and ColorPicker. Interfaces that enable users to modify values that are used in the Global Styles system.

I've looked into the `RangeControl` before, so I'm familiar with it.
I'll see if I can make some updates to refresh the design but also improve usability.

For example, I've struggled to grab/drag the controls in the past - due to the small(ish) hitbox.

**Comment by ItsJonQ** [comment]
Updates on my end!

![Screen Capture on 2020-01-23 at 16-52-41](https://user-images.githubusercontent.com/2322354/73027170-ea4c1c00-3e00-11ea-8d72-023bf2d46047.gif)

This is what I have so far :)

Features:
* Uses native `<input type="range" />`. Get all the browser support for drag, keyboard, etc...
* Visual tooltip that displays current value. Follows the "thumb" (circle)
* Larger hitbox, making it easier to click/drag

![Screen Capture on 2020-01-23 at 16-55-37](https://user-images.githubusercontent.com/2322354/73027347-3bf4a680-3e01-11ea-83b0-a144f12b3fc0.gif)

* Renders step markers with a simple prop (`marks`)
* Tooltip auto positions `top` or `bottom`, based on ideal rendering position
* Respects `reduce-motion` to disable all animations
* Can easily change the color of the "track" using a `color` prop
* Can customize the tooltip's content with a custom renderProp

So far, the component's props looks like this:

```
export const RangeControlNext = forwardRef( ( {
	alwaysShowTooltip = false,
	className,
	color: colorProp = color( 'blue.wordpress.700' ),
	disableToolTip = false,
	disabled,
	help,
	id,
	label,
	marks = false,
	min = 0,
	max = 100,
	onChange = noop,
	step = 1,
	value: valueProp = 0,
	renderTooltipContent = ( v ) => v,
	tooltipZIndex = 100,
}, ref ) => {
  ...
})
```

**Comment by jasmussen** [comment]
What about this?

<img width="289" alt="Screenshot 2020-01-24 at 08 39 02" src="https://user-images.githubusercontent.com/1204802/73052263-01345200-3e85-11ea-82a9-2c200aa40cbd.png">

Then we'd avoid any contrast issues with the light gray border around the white knob.

**Comment by karmatosed** [comment]
@jasmussen my only ponder with that is whether the control stands out enough, which I know is maybe unexpected saying with it being a bright color. Maybe on interacting it could show but I do wonder if it shouldn't change color, for example, it's not a button to click as much as move. I am very happy to be wrong there though as we're getting into the nuance of this.

**Comment by jasmussen** [comment]
The benefit of just using two colors is that it just uses two colors, which simplifies the look and the contrast equation. But the dark color works too, and the shadow that Q added in his lovely prototype is also a way to signal interactivity. That's all a way to say this seems on a good track as is. But the white knob with light gray border as is, likely won't pass the contrast needs.

**Comment by karmatosed** [comment]
I think the a11y point is really important. We might want to then open up both as a point to see which is more acceptable.

**Comment by ZebulanStanphill** [comment]
It's worth restating that from a usability and accessibility point, it only makes sense to use slider controls like this for things that don't require high precision. In other words, something like the number of columns in a Columns block should just use a simple number input rather than a slider, since the exact number of columns is really important in that context, and a slider doesn't add much to the experience.

I say all this because I notice that there are design mockups here containing tick marks, but I can't see why you would use a slider for such controls in the first place.

**Comment by ItsJonQ** [comment]
📹 Screencast to demo new RangeControl
https://www.loom.com/share/ab01335a805043ee86e470e3308e621a

@jasmussen + @karmatosed 

Neat! Let me know what design/colours you'd like to go with, and I can make that update :)

> ... I notice that there are design mockups here containing tick marks

@ZebulanStanphill 

Haii 👋 ! The native HTML `input` supports the rendering of marks/ticks, which is handy:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

Since this `RangeControl` components acts serves as an enhanced wrapper for that element, I believe that it should support that feature.

**Comment by ItsJonQ** [comment]
![Screen Capture on 2020-01-24 at 18-23-34](https://user-images.githubusercontent.com/2322354/73111050-dbd03400-3ed6-11ea-8f10-a1f2070c59ef.gif)

It's in a pretty good state! All previous `RangeControl` tests pass, without regression. The new one has feature parity with the old one with new features.

Tested within Gutenberg (above)

Here's the branch so far 😊 

https://github.com/WordPress/gutenberg/tree/try/range-controls-ui-update

**Comment by ZebulanStanphill** [comment]
The handle seems to blend into the background a bit too much. Could it be given a darker border?

**Comment by ItsJonQ** [comment]
@ZebulanStanphill Good suggestion!

<img width="553" alt="Screen Shot 2020-01-24 at 7 48 00 PM" src="https://user-images.githubusercontent.com/2322354/73113606-bb0ddb80-3ee2-11ea-83b3-c6a2a64e2bda.png">

I've darkened it to use `darkGrey.200` from the libraries colour palette.

Focus/hover darkens it a bit:

<img width="419" alt="Screen Shot 2020-01-24 at 7 51 26 PM" src="https://user-images.githubusercontent.com/2322354/73113639-f27c8800-3ee2-11ea-92c6-349a170280d4.png">

@jasmussen / @karmatosed 
How does that look? 😊 

Note: The selected range color uses the default WordPress blue color to make it look cohesive with the current component set. Open to any colour changes!

The code looks like it's in good shape. I can submit a PR first thing on Monday 💪

**Comment by jasmussen** [comment]
> How does that look? 😊

Having worked so much on #18667 adjacent PRs, the only two colors I can think of when looking at these are shipping the new Blueberry color and applying it in as many places as possible, including the knob 😅— but that's a personal opinion.

What matters most is the border passes the contrast requirements, and it looks like it does so. Going back to the G2 efforts, they introduce a new singular "dark border color", which is used for all primary UI — toolbars, icons, primary popovers. If G2 was shipped already, I'd use that dark color for resting and hover both, and even remove the drop shadow and reserve that elevation for menus and dialogs. 

But in absence of that, yeah looks good!

**Comment by karmatosed** [comment]
@ItsJonQ this looks great. I think maybe once G2 is in bringing in that blueberry for the slide measure would be great. However, without that maybe bring in the 'blue' we use now for hover/primary buttons? Thanks for this, super excited to see the iteration in a PR.

I would be ok with having the 'blue' showing on an interaction, even feeling what it's like for the dot. I think any could work there so let's go with whatever is consistent with new iterations.
