### ISSUE TITLE
The post content shifts to the right when publishing

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#19840]
**Describe the bug**
When publishing a new post, the whole post content shifts to the right producing an unexpected movement of the whole content section.

As a user, I'd be very confused by things moving while I publish and I'd wonder if something went wrong.

Having the whole editor unexpectedly moving doesn't seem an optimal user experience.

GIF:

![centered](https://user-images.githubusercontent.com/1682452/72981336-d2fb3780-3ddc-11ea-816b-461b1a3082a6.gif)

**To reproduce**
This happens only on WordPress trunk, with or without the Gutenberg plugin activated. Doesn't happen on 5.3.2.
- create a post
- make sure the Gutenberg Settings sidebar is expanded
- enter a title
- enter some content
- click Publish
- the content area shifts to the right
- the publish sidebar appears
- click the Publish button within the publish sidebar
- the content area is still shifted to the right
- close the publish sidebar by clicking on the X button
- the content area shifts back to its original position

**Expected behavior**
To not see the whole editor area move

**Additional context**

This seems related to the changes from https://github.com/WordPress/gutenberg/pull/18044

Previously, the Editor content area had a right margin equal to the sidebar width. With the refactoring from https://github.com/WordPress/gutenberg/pull/18044 the margin is gone.

**Comment by draganescu** [comment]
I can confirm this behavior.
