### ISSUE TITLE
Pullquote block HTML is different in the editor and in the frontend

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#19847]
**Describe the bug**
The block in the editor is styled using class names, which aren't applied to the HTML which is saved to the post content and output in the frontend. e.g. the citation has the class name `wp-block-pullquote__citation` in the editor, but not in the saved HTML.

**Expected behavior**
The block and its children should be styled using the same CSS rules in the editor and in the generated post content.

**Comment by jorgefilipecosta** [comment]
Hi @markhowellsmead thank you for submitting this issue. In the editor normally we are more liberal with adding classes, while in the final markup we are more strict. For example, the paragraph block in the editor contains the class wp-block-paragraph while on the markup for the frontend the class is not added.

> The block and its children should be styled using the same CSS rules in the editor and in the generated post content.

To use the same styles in both places use the styles that work on the frontend something like `.wp-block-pullquote cite` should work well in both places.

I'm closing the issue, for now, feel free to comment if you need additional information.

**Comment by markhowellsmead** [comment]
@jorgefilipecosta That could make sense, but the HTML is different in the editor and in the saved content, too. The editor uses a `DIV` but the saved content contains a `CITE` tag. If this logic is extended to every block, this would result in approximately twice as many definitions, which is a considerable and unacceptable level of bloat.

**Comment by jorgefilipecosta** [comment]
Hi @markhowellsmead thank you for bringing our attention to the fact that "The editor uses a DIV but the saved content contains a CITE tag". That seems problematic. I will reopen the issue.
@ellatrix do you know if we can use a "cite" tag with RichText?

**Comment by youknowriad** [comment]
Historically, we can't use any "inline" element in RichText and I think it's still the case. That's the reason for this difference.

**Comment by markhowellsmead** [comment]
That would encourage the use of the CSS class names for the elements. All of the other CSS work we do is class name based - never element selectors - which means that we can retain the same styling irrespective of the HTML tag which is being used.

**Comment by paaljoachim** [comment]
Over a year has gone by.
Is this issue still valid?
Could we get a status update here?

**Comment by skorasaurus** [comment]
> Over a year has gone by.
> Is this issue still valid?
> Could we get a status update here?

Yes, I have this issue myself; it's still applicable in Gutenberg 11.1 and WordPress 5.8.

**Comment by markhowellsmead** [comment]
Yes, it’s still an issue.

**Comment by kevin940726** [comment]
> Historically, we can't use any "inline" element in RichText and I think it's still the case. That's the reason for this difference.

@youknowriad Why can't we? Is there a technical reason behind this, preferably documented somewhere in an issue?

**Comment by youknowriad** [comment]
There was a technical reason behind it related to focus disappearing or something like that (and there's no place to click to actually focus the empty element), I think it might have changed lately though. @ellatrix did some work there.

**Comment by ellatrix** [comment]
Using it with inline elements should be fine now

**Comment by diegobroncano** [comment]
Hi! But can't you add a class to the front-end cite tag, so we could use the same selector in the editor as well as in the front-end?

**Comment by mrleemon** [comment]
Is this planned to be changed? The Quote block already uses a CITE tag in the editor. Why is the Pullquote block not?

**Comment by ndiego** [comment]
#39414 fixes this issue by standardizing the markup in the Editor and Frontend so both use `<cite>`. That PR has been merged.
