### ISSUE TITLE
[Monorepo] Update react-native-video dependency to remove Apache 2.0 dependencies 

### ISSUE THREAD

**Issue by Tug** [WordPress/gutenberg#19860]
This is part of the Monorepo effort (see #18508).

Some of the dependencies `gutenberg-mobile` currently have are not compatible with GPLv2. We need to fork and update the one that are bundled/distributed. We can keep the ones that are involved in the build process, but we should make sure those are devDependencies.

We have identified the following dependencies that will need to be rewritten:
```
gutenberg@7.2.0
├─┬ @wordpress/react-native-editor@1.20.0
│ └─┬ react-native-video@4.4.1
│   ├── keymirror@0.1.1                <- Apache 2.0 license
│   └── shaka-player@2.5.8             <- Apache 2.0 license
```

**Comment by maxme** [comment]
I opened a PR to remove `keymirror` and `shaka-player` from `react-native-video`: https://github.com/wordpress-mobile/react-native-video/pull/6
