### ISSUE TITLE
Give the ability to only lock a template from moving blocks

### ISSUE THREAD

**Issue by Mahjouba91** [WordPress/gutenberg#19874]
**Is your feature request related to a problem? Please describe.**
I have a requirement for a website with thousand of articles. I need to support a basic template with two blocks : an intro paragraph and a read more block.

Currently the [lock feature](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#locking) allow these values:
- all — prevents all operations. It is not possible to insert new blocks, move existing blocks, or delete blocks.
- insert — prevents inserting or removing blocks, but allows moving existing blocks.

**Describe the solution you'd like**
I would like to have a third parameter:
- move

So that the user would be able to add any blocks he wants, but he won't be able to move the first two blocks of the template, it will remain on the top.

**Describe alternatives you've considered**
I was thinking of implementing it in a weird way like:
- Create a block that basically just create an Inner block. Then, create a template with a paragraph, read more, and inner block. The template will be locked, and the user could only add blocks to the inner block. And I'm not actually sure it will fix the issue because of the lock inheritance, It will disallow even on the InnerBlock to add any block inside it.
- Just hack the style or JS a bit to lock the first two blocks order.

**Comment by Mahjouba91** [comment]
It seems to be linked to this existing issue: https://github.com/WordPress/gutenberg/issues/8112

Despite the issue is only mentioning Inners Blocks and not templates

**Comment by talldan** [comment]
@Mahjouba91 Yep, I think this is covered in #8112. I'll close this issue as a duplicate if that's ok with you.
