### ISSUE TITLE
Edit site: Template part focus styling

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#19886]
It should be obvious when a user starts editing a template part as these changes impact any page using the template part. I propose we add a focus state when editing a template part or its contents.

Note: My mockups are a frankenstein of low-fi mocks and some newer styles. They're not to be taken literally as much as convey an idea.

Here's a rough example to give you an idea of what I'm referring to:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1123119/73110885-4c6e5500-3ec5-11ea-9fea-38485916403e.png">

Here's a [quick prototype of what I'm proposing](https://www.figma.com/proto/fud7MwfNd2rS0fjxMRdHwu/Full-Site-Editing-%E2%80%93-Templates?node-id=243%3A2360&viewport=-266%2C302%2C0.5&scaling=min-zoom).

And a big old gif of the prototype:

![template-part-focus-i1](https://user-images.githubusercontent.com/1123119/73110963-ac64fb80-3ec5-11ea-8519-313f654e0b0d.gif)

@epiqueras would you be interested in tackling this? I can help with styles.

**Comment by epiqueras** [comment]
Yes, and we should also have this for blocks such as the Post Content block because it has the same inner block saving mechanics.

**Comment by MichaelArestad** [comment]
@epiqueras exactly!

**Comment by karmatosed** [comment]
What about this on navigation? That block has some complexities might be easied by a focus.

**Comment by johnstonphilip** [comment]
Could this help us avoid the need for this pop-up (which I've found really confusing)?

<img width="422" alt="Screen Shot 2020-02-19 at 2 28 34 PM" src="https://user-images.githubusercontent.com/7538525/74868769-c9ee7f00-5324-11ea-8bc1-7873c6ff29d9.png">


Perhaps when popping into-focus a new set of `Publish/Update` controls appear that are specific to that template part, and the only way to get out-of-focus is to either `update` it, or `cancel`. 

<img width="1196" alt="73110885-4c6e5500-3ec5-11ea-9fea-38485916403e" src="https://user-images.githubusercontent.com/7538525/74869173-7f213700-5325-11ea-999f-e879c17b6dcd.png">

**Comment by epiqueras** [comment]
I don't think that is the right solution. You would be forced to edit global areas sequentially and would lose the ability to make edits in parallel and publish them all at once.

This can be bad for UX but can also outright break sites where it is essential for a set of edits to go live together.

**Comment by johnstonphilip** [comment]
Hmm. I disagree that attaching and publishing multiple different contexts in a single user action is a good UX. I think the user will be very lost and unsure about what step they are actually taking. If you need to push a set of changes live all at once, I think the best route is to use a staging site.

**Comment by epiqueras** [comment]
That would be way too involved for such a typical operation: E.g., changing header and footer background color in one go.

**Comment by johnstonphilip** [comment]
@epiqueras I'm not sure if I understand what you mean. Can you elaborate?

**Comment by epiqueras** [comment]
On which part? I'm saying that having to use a staging site to change multiple template parts at the same time is way too involved for such a typical operation.

**Comment by BMO-tech** [comment]
It seems like making edits to multiple sections (template and template parts) and then being prompted with a popup of "What do you want to save" is also a complex pattern/UX for the average user. Perhaps the better experience when clicking "save" is that items that were edited simply save; and an "Undo" option is available (as is provided by Gutenberg already).

Also, the save behavior doesn't seem to be relevant to this issue; rather just a visual representation that a specific template part is being edited.

**Comment by epiqueras** [comment]
Some sort of pre-publish flow is needed. You should be able to decide what set of changes you want to publish.

>Perhaps the better experience when clicking "save" is that items that were edited simply save; and an "Undo" option is available (as is provided by Gutenberg already).

That would be a very bad UX, users could be unaware that they are making site-wide changes, and then come lots of questions related to whether undoing is global or specific to some part.

>Also, the save behavior doesn't seem to be relevant to this issue; rather just a visual representation that a specific template part is being edited.

They are related if this gives the idea that the pre-publish flow isn't needed.

**Comment by MichaelArestad** [comment]
> Some sort of pre-publish flow is needed. You should be able to decide what set of changes you want to publish.

> Perhaps the better experience when clicking "save" is that items that were edited simply save; and an "Undo" option is available (as is provided by Gutenberg already).

I think we should pursue both routes. I share concerns that users won't realize they are making site-wide changes, but I am not confident that my concerns match reality. In using other site builders or similar applications, there is usually just a save/publish button that indiscriminately publishes changes. Is this the best for users? That remains to be seen. We can work this out as we iterate on the save/publish flow.

**Comment by MichaelArestad** [comment]
I'm thinking we should probably shelve this for now in favor of just using the usual block focus styles and revisit if deemed necessary or useful later on.

**Comment by epiqueras** [comment]
#21522 makes this less crucial too. Closing for now.
