### ISSUE TITLE
Install environment for gutenberg not working ! 

### ISSUE THREAD

**Issue by KaramHnni** [WordPress/gutenberg#19892]
Hi , 
I'm trying to install gutenberg on my local computer 
I've installed docker and docker compose by following the following getting started tutorial : https://developer.wordpress.org/block-editor/contributors/develop/getting-started/

Now when i'm running the `npm run env install`
The terminal is throwing the following error 
`$ npm run env install

> gutenberg@7.3.0 preenv /WIN_E/studies/Web Developement/Web Projects/Gutenberg/gutenberg
> npm run check-engines

> gutenberg@7.3.0 check-engines /WIN_E/studies/Web Developement/Web Projects/Gutenberg/gutenberg
> wp-scripts check-engines

sh: 1: wp-scripts: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! gutenberg@7.3.0 check-engines: wp-scripts check-engines
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the gutenberg@7.3.0 check-engines script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/karam/.npm/_logs/2020-01-25T12_00_59_802Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! gutenberg@7.3.0 preenv: `npm run check-engines`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the gutenberg@7.3.0 preenv script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
Thank you

**Comment by youknowriad** [comment]
Hi @KaramHnni It seems like you're trying to run the project on Windows. This is very uncommon for us so you might face some issues we're not aware of.

**Comment by noahtallen** [comment]
@KaramHnni We recently introduced a new environment tool which might solve your issue. You can read about how to use it here: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md#step-1-installing-a-local-environment

**Comment by enriquesanchez** [comment]
I'm closing this issue as there seems to be a solution. Please feel free to reopen if necessary.
