### ISSUE TITLE
experimentalUseColors: labels are not translatable

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#19890]
**Describe the bug**
The labels in the `__experimentalUseColors` component are not translatable. Used in heading, navigation, paragraph and group block.

Navigation block edit.js
```js
__experimentalUseColors(
	[
		{ name: 'textColor', property: 'color' },
		{ name: 'backgroundColor', className: 'background-color' },
	],
	...
)
```

`__experimentalUseColors` in use-colors.js
```js
panelLabel = startCase( name ), // E.g. 'Background Color'.
```

**Screenshots**
Navigation block.
<img width="268" alt="Bildschirmfoto 2020-01-25 um 11 52 46" src="https://user-images.githubusercontent.com/695201/73120034-bb9d8500-3f69-11ea-9d78-63e8d2b4bed6.png">

**Comment by jorgefilipecosta** [comment]
cc: @epiqueras

**Comment by epiqueras** [comment]
@jorgefilipecosta Should we pass an explicit `label` property for each color?

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta Should we pass an explicit `label` property for each color?

Yes, I guess that should be the solution.

**Comment by epiqueras** [comment]
Do you want to open the PR?

**Comment by jorgefilipecosta** [comment]
Sure I will submit a PR soon 👍
