### ISSUE TITLE
Copy/pasting numbered list from Zoho writer removes content

### ISSUE THREAD

**Issue by webtrainingwheels** [WordPress/gutenberg#19897]
When copy/pasting a numbered list from Zoho Writer into the block editor, the content of the list is lost. (Unordered lists seem to work fine.) 

Reproduced on WordPress 5.3.2, Twenty Twenty theme, no plugins. 

Original content: 
![zoho](https://user-images.githubusercontent.com/1043076/73129191-cc162580-3f92-11ea-8b32-0ed1c8d0f88e.jpg)

After pasting into the block editor: 

![Edit_Post_‹_WordPress_Themes_—_WordPress](https://user-images.githubusercontent.com/1043076/73129195-df28f580-3f92-11ea-86cf-e51570a8c52d.jpg)

Code view: 

![code_view](https://user-images.githubusercontent.com/1043076/73129217-37f88e00-3f93-11ea-8eff-88cd2858f17d.jpg)

**Comment by talldan** [comment]
@webtrainingwheels Yes, it also looks like if I paste from Zoho to other places it also doesn't create a list correctly. For example, pasting to Google Docs, it didn't create a list properly, just separate lines with numbers and the last item in the list was lost. In slack it created a list, but the numbers were duplicated and the last item wasn't pasted in the list, similar to the block editor

Looking at the HTML from the paste event, it looks invalid, Zoho provides an ordered list element `<ol>`, but the content isn't in list items `<li>`.

So I think this is an issue with Zoho, I'd recommend raising it with their support
