### ISSUE TITLE
UI/UX: Inconsistent patterns for active/selected control colors

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#19904]
Just starting a conversation around developing a consistent active/selected color for controls primarily within the Settings Sidebar/`InspectorControls`. 

For active/selected button states within `InspectorControls` regions, should folks be employing the editor's primary color? Or perhaps the dark gray color that is used on the Setting Sidebar button and within the `HeadingToolbar`? While [G2](https://github.com/WordPress/gutenberg/issues/18667) is looking good, we can work to establish a pattern now - that will be naturally adopted into G2. We briefly discussed this in the Slack [#design](https://wordpress.slack.com/archives/C02S78ZAL/p1579883813001500) channel.

Looking through our current UI, here are a few variants of active/selected states that are employed today (screenshots below).  

### A. Settings Sidebar button
Uses a dark gray color for the active/selected state.

<img width="410" alt="Screen Shot 2020-01-26 at 5 32 40 PM" src="https://user-images.githubusercontent.com/1813435/73142906-e965f500-4061-11ea-9992-8fb7ef4ad5d9.png">

--

### B. Heading block HeadingToolbar
Also uses a dark gray color for the active/selected state:

<img width="271" alt="Screen Shot 2020-01-26 at 5 33 41 PM" src="https://user-images.githubusercontent.com/1813435/73142922-0e5a6800-4062-11ea-90b9-75574b09c3af.png">

--

### C. Image dimensions ButtonGroup
Uses the primary theme color (blue in this case) to signify a selected button within the group:

<img width="271" alt="Screen Shot 2020-01-26 at 5 34 52 PM" src="https://user-images.githubusercontent.com/1813435/73142946-377af880-4062-11ea-9e6f-5c2380ddb11e.png">

--

### D. ToggleControl
This example is from the Paragraph block. Note that the control utilizes a different blue in the default theme:

<img width="270" alt="Screen Shot 2020-01-26 at 5 36 02 PM" src="https://user-images.githubusercontent.com/1813435/73142961-61ccb600-4062-11ea-86cb-84f260c17f89.png">

--

### E. Gradient tabs
Here's a `ButtonGroup` that is utilizing secondary and primary button styles (primary signifying the active tab):

<img width="266" alt="Screen Shot 2020-01-26 at 5 56 57 PM" src="https://user-images.githubusercontent.com/1813435/73143213-4c0cc000-4065-11ea-9e62-9248079cc627.png">

--

### F. Radio/Checkbox controls
<img width="147" alt="Screen Shot 2020-01-26 at 6 02 45 PM" src="https://user-images.githubusercontent.com/1813435/73143272-1b795600-4066-11ea-9db4-2ec60e0119cf.png">

--

### G. Third party blocks/controls
This is an example from a CoBlocks block utilizing the `ButtonGroup` component with primary and secondary button styles.

<img width="574" alt="Screen Shot 2020-01-24 at 11 35 15 AM" src="https://user-images.githubusercontent.com/1813435/73143136-7c079380-4064-11ea-85e3-9313dec3c575.png">

--

After reviewing the different cases, an applied standard would be nice here - again, one that we could roll right into G2. I could be convinced either way if active states should be using the primary color, or the (_currently_) darker gray color - though I lean towards a color that is not so heavy - simplifying the UI - rather than flashing color. And we're not signifying a primary action (whereas the "Publish/Update" does) - but instead identifying a selection.

Thoughts?

**Comment by karmatosed** [comment]
What a great deep dive @richtabor, let me loop in @jasmussen as there certainly is some connecting work here with the iterations on interface going on.

**Comment by jasmussen** [comment]
> For active/selected button states within InspectorControls regions, should folks be employing the editor's primary color? Or perhaps the dark gray color that is used on the Setting Sidebar button and within the HeadingToolbar? While G2 is looking good, we can work to establish a pattern now - that will be naturally adopted into G2. We briefly discussed this in the Slack #design channel.

Delightful question to be asking, and one that, as you allude to, the G2 efforts have tried to address. In that design, the treatment for a toggled state is a (very) dark background. The two exceptions are the Switch control, and the Checkbox control, both of which use the theme color.

It would be only reasonable to explore those with the UI we have today, to help inform it and shape it. In that vein, what would it look like if we employed the same gray inversion/toggled state across the elements you mention? In my minds eye, it surfaces some design challenges with how buttons look after the latest iteration. While the stronger focus styles are helpful, the blue border and gray material inside has not worked as well. In exploring the dark gray toggled state, we may need to look also at how secondary buttons look.

**Comment by richtabor** [comment]
We should add the `ResizableBox` handles to this as well, as they're using a different color blue than the current G2 primary color.

<img width="768" alt="Screen Shot 2020-06-01 at 2 02 44 PM" src="https://user-images.githubusercontent.com/1813435/83439248-c765f000-a410-11ea-9978-3dd27aba9e2b.png">

The handles are using `theme(primary)` whereas the primary blue buttons are using `theme(button) shade(6%)`. Source: https://github.com/WordPress/gutenberg/blob/0552712059ac5519fad0aeab6dddc5b84f049192/packages/components/src/button/style.scss#L25`

**Comment by jasmussen** [comment]
> We should add the ResizableBox handles to this as well, as they're using a different color blue than the current G2 primary color.

😱 

I have to fix this. Thank you for bringing it to my attention. I hope to get to this soon.

**Comment by jasmussen** [comment]
@richtabor I'm taking a look at a few of these items here today, but it appears this one, https://github.com/WordPress/gutenberg/issues/19904#issuecomment-637020185, might have been fixed. 

Looking at the latest version of the button style in https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/style.scss#L45 it uses the same `$theme-color` as the resize handles do. If I'm missing something, happy to fix, otherwise I'll assume this one is done.
