### ISSUE TITLE
Latest Posts: posts without title show up empty

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1990]
Let's add (Untitled) to these.

**Comment by afercia** [comment]
The current convention in core is `(no title)`. No strong opinions about that though. I'd like to say the current Recent Posts widget does the same but I've just noticed it shows the post ID instead 😬 
Will open a Trac ticket...

<img width="393" alt="screen shot 2017-07-24 at 23 34 08" src="https://user-images.githubusercontent.com/1682452/28545862-e7f7d988-70c8-11e7-94b8-778346841576.png">

**Comment by westonruter** [comment]
Fix has been added to #1992.
