### ISSUE TITLE
Experimental block directory search does not show blocks when plugin deactivated

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#19906]
**Describe the bug**
I was testing the Experimental Block directory search in my development environment and was unable to find the `boxer` block. Analysis of the response from wordpress.org indicated that the block / plugin was returned in the list. But the plugin was already installed so was excluded from the results returned to the browser. The plugin was already installed; but it was deactivated.  

**To reproduce**
1. Install boxer block plugin but don’t activate it
2. Enable Block Directory experiment
3. Add new post
4. Open block inserter and search for boxer
5. Find it’s not listed.

**Expected behavior**
I should be offered the opportunity to activate the plugin.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPad
 - Browser [e.g. stock browser, safari] Safari

**Additional context**
Gutenberg 7.3.0
Problem occurs on WordPress and Multi Site.

**Comment by annezazu** [comment]
Thanks for reporting this. It's a great find. I was able to replicate it in my testing! It seems the block directory doesn't handle cases where a plugin is installed on the site but is inactive. It only works if the block plugin is installed and active OR if the plugin isn't installed at all.

**Comment by StevenDufresne** [comment]
Related: 

https://github.com/WordPress/gutenberg/issues/15121#issue-436093072

See second bullet point.

**Comment by StevenDufresne** [comment]
@bobbingwide We merged #22286 to address this issue. More information can be found within the ticket :)

Thanks for the ticket!

**Comment by bobbingwide** [comment]
It seems the recent updates for #22454 have (intentionally) broken the fix in #22286. 
The new issue is #23570.
See the Block directory issue ( #23378 ) for the list of issues that are needed for the block directory to make it into 5.5.
