### ISSUE TITLE
Copy: Setting Sidebar controls case inconsistencies

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#19902]
**Describe the bug**
In support of utilizing sentence case (as we've started implementing in #16764, #18758 and #19900), block controls within a block's `InspectorControls` should have sentence case formatting.

Related/expands on: #16764, #12366, #19900

**Screenshots**
Here are a few, though there are a number of control labels that need adjusting:

<img width="270" alt="Screen Shot 2020-01-26 at 4 29 43 PM" src="https://user-images.githubusercontent.com/1813435/73142113-1feb4200-4059-11ea-95d9-48701be6bcde.png">
<img width="267" alt="Screen Shot 2020-01-26 at 4 30 24 PM" src="https://user-images.githubusercontent.com/1813435/73142116-2a0d4080-4059-11ea-990c-fcceff44236d.png">

**Comment by mapk** [comment]
Looks like the PR is approved and will be merged shortly.
