### ISSUE TITLE
`align` vs `textAlign` vs `contentAlign` attributes

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#19905]
**Describe the bug**
`align` and `textAlign` attributes need to be differentiate properly. `align` is being used on full width/wide selection and text alignment. But for some reason, some blocks are using `textAlign` and `contentAlign` on alignment. It's super confusing. Thanks!

**Comment by youknowriad** [comment]
This seems like a duplicate to #19672 for me. Let's consolidate the discussions there.
