### ISSUE TITLE
Copy: PanelBody title case inconsistencies

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#19900]
**Describe the bug**
In support of utilizing sentence case (as we've started implementing in #16764 and #18758), all the `PanelBody` titles should be in sentence case. 

Related/expands on: #16764, #12366

Screenshots: 
<img width="281" alt="Screen Shot 2020-01-26 at 3 39 27 PM" src="https://user-images.githubusercontent.com/1813435/73141452-24602c80-4052-11ea-918c-c2e70fd91fb8.png">
<img width="282" alt="Screen Shot 2020-01-26 at 3 40 22 PM" src="https://user-images.githubusercontent.com/1813435/73141458-2de99480-4052-11ea-9d65-30eed67bb373.png">

**Comment by karmatosed** [comment]
I 'think' this might need the same magic that @mcsf worked on with me when we get to the PanelBody titles. Just including incase that is needed and we pull in from core itself.
