### ISSUE TITLE
Werid layout issues 

### ISSUE THREAD

**Issue by nathanmarkley** [WordPress/gutenberg#19913]
Hi: 
Was wondering if anyone has seen this issue before? When I go to create or edit a post, and page with the new editor, some of the icons on the top bar and left sidebar are missing and just look weird. See screenshot. 
Any thoughts? 
![wordpressgutenburgnewposticonsmissing](https://user-images.githubusercontent.com/7587056/73192106-9722e380-40f6-11ea-8461-4ed7bd233385.png)

Thanks: 
nathan

**Comment by talldan** [comment]
I haven't had any issue like that @nathanmarkley, my icons look normal:
![Screen Shot 2020-02-06 at 3 26 32 pm](https://user-images.githubusercontent.com/677833/73914887-213c2a80-48f5-11ea-8226-0a258950beea.png)

Not sure what could cause that, possibly a plugin?

**Comment by nathanmarkley** [comment]
Ok. thanks. Yeah, its weird. Thinking it may be a custom theme thing. 
Disabling plugins still make it not show up.
