### ISSUE TITLE
Migrate existing single button blocks to buttons/button block (wrapped)

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19919]
**Describe the bug**
When editing pages that contain singular butto**n** blocks that had been edited before the buttons block has been introduced, there is no automatic or easy way for converting/upgrading these singular butto**n** blocks into button blocks that are wrapped by a button**s** block.
The easiest approach would just mimic what is already done with any other elements and wrapping it into a group block: When a singular butto**n** block is selected that isn't wrapped by a button**s** block yet, the transform menu should not only offer "Wrap into group" as with all other blocks, but also "Wrap into button**s** block".
Additionally, an extra option that auto-wraps all the singular butto**n** blocks into button**s** blocks would be a nice addition. Some pages can have lots of these singular buttons.

**To reproduce**
Edit a page that had been created when Gutenberg had no button**s** block yet.
Select a singular, unwrapped butto**n** block, open the transform options.
Notice that there is no transformation that wraps this singular butto**n** block into a button**s** block.

**Expected behavior**
A transform option for wrapping a singular butto**n** block into a button**s** block.

**Comment by talldan** [comment]
Yep, makes sense that there's a transform from Button to Buttons. 👍

**Comment by Ringish** [comment]
I'm working on this!

**Comment by talldan** [comment]
Thanks @Ringish. If you need any code to reference, there's a similar transform from Image to Galleries:
https://github.com/WordPress/gutenberg/blob/056d7c108ac968363b7a747660ea50b13069f87a/packages/block-library/src/gallery/transforms.js#L26-L58

`isMultiBlock: true` is pretty handy as it means a single selected image or multiple selected images can be converted to a gallery. Seems like the same should be possible for the button block.

and the docs for transforms are here:
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#transforms-optional

**Comment by Ringish** [comment]
@talldan @strarsis 
Got it working on my fork and the branch [here](https://github.com/Ringish/gutenberg/blob/add/transform-button-to-buttons/packages/block-library/src/buttons/transforms.js).
![buttons](https://user-images.githubusercontent.com/3396172/73824486-86f7bc00-47fa-11ea-9caf-6d87fff14613.gif)

Is this correct and expected behaviour?

**Comment by talldan** [comment]
@Ringish That looks great! You should be able to open a pull request against this repo using the branch on your fork.

Let me know if you need any assistance with that. I anticipate some tests will need to be updated, this fixture here I think just needs to be manually updated with the new transform:
https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/fixtures/block-transforms.js

You can run unit tests locally by using `npm run test` or `npm run test:watch`, and end to end tests are `npm run test-e2e` or `npm run test-e2e:watch`.

**Comment by strarsis** [comment]
Maybe it would make sense to add a 'vertical' list as the buttons block default style so the button blocks wrapped by buttons block are still on separate lines.

**Comment by talldan** [comment]
@strarsis True. At the moment you can add separate Buttons blocks, but that doesn't seem completely intuitive.

I think this would have to be a separate issue though, is that something you'd be happy to create?

**Comment by strarsis** [comment]
@talldan: https://github.com/WordPress/gutenberg/issues/20081

**Comment by talldan** [comment]
Thanks!
