### ISSUE TITLE
The editor has encountered an unexpected error with Gutenberg with 7.2.0 and 7.3.0

### ISSUE THREAD

**Issue by DeanE1** [WordPress/gutenberg#19938]
When trying to edit posts with either version of Gutenberg, 7.2.0 or 7.3.0, I get this error:

 "The editor has encountered an unexpected error".

In Google console I see this:

react-dom.min.b694e242.js:103 TypeError: Cannot read property 'disableTips' of null
    at ho (index.js:6)
    at je (react-dom.min.b694e242.js:78)
    at ph (react-dom.min.b694e242.js:215)
    at lh (react-dom.min.b694e242.js:126)
    at O (react-dom.min.b694e242.js:121)
    at ze (react-dom.min.b694e242.js:118)
    at react-dom.min.b694e242.js:53
    at unstable_runWithPriority (react.min.0212dc62.js:26)
    at Ma (react-dom.min.b694e242.js:52)
    at mg (react-dom.min.b694e242.js:52)

I've had to return to Gutenberg 7.1.0 to get things working correctly again.

My site is deancent.com

**Comment by jorgefilipecosta** [comment]
Hi @DeanE1! Thank you for reporting this issue. It seems is disableTips is part of  wp.nux package. Probably the website has a plugin/theme or custom code that is calling `wp.data.dispatch('core/nux').disableTips();`, to disable the new user experience UI could you provide the plugin that you think could be related to this?

That said `wp.data.dispatch('core/nux').disableTips();` was a valid way to disable nux so we should be back-compatible with this call and it seems currently the call throws an error that may make the editor crash. cc: @noisysocks

**Comment by aduth** [comment]
> That said `wp.data.dispatch('core/nux').disableTips();` was a valid way to disable nux so we should be back-compatible with this call and it seems currently the call throws an error that may make the editor crash. cc: @noisysocks

It could be a problem that the plugin does not define a dependency on the `wp-nux` script handle. If the plugin does not define the dependency, and neither does the editor (now as of the introduction of the new Welcome Guide), then it's quite likely that the `'core/nux'` data store would never be registered, and this is expected.

The solution would be: Make sure that `'wp-nux'` is included in the `$deps` (third argument) of `wp_enqueue_script` (`wp_register_script`) of whichever script is calling `dispatch('core/nux').disableTips`.

**Comment by jorgefilipecosta** [comment]
Hi @aduth, thank you for providing additional context to this issue. So this seems to be a bug in a plugin or theme.
@DeanE1 do you have an idea of the plugin that may be causing this?

**Comment by DeanE1** [comment]
Hi Jorge, I disabled yoast seo premium, Tried editing a post and the problem was still present. I then refreshed the post edit page while holding ctrl + shift and the problem went away. Not sure if this is an actual conflict with Yoast or just my cache. Considering everything, this appears it could have been cache related although all my caching I thought should be bypassed while logged into the back-end of my site.

Anyways sorry for wasting anyone's time.

**Comment by jorgefilipecosta** [comment]
I verified that if we add a dependency on wp-nux, the call `wp.data.dispatch('core/nux').disableTips();` does not crashes and shows a deprecation message in the console.
I think we can close the issue. Thank you @aduth and @DeanE1 for the insights.
