### ISSUE TITLE
Discussion: Should we keep CONTRIBUTORS.md 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#19948]
During the update of the main README file in #19743, @youknowriad brought up if we should keep the [contributors file here](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTORS.md)

> I wonder if it's time to retire that file. I understand its purpose (non-code contributions) but it's a challenge to keep up to date and I'm not sure the difference with code contributors is huge. (anyway a separate discussion)

This ticket is here to open the discussion. My two cents is to remove, it is a confusing file and not accurate. The majority of people in the file are also on the contributors tab within Github, also do we need the mapping of usernames Github => WordPress?

Open to suggestions for ways to honor and show our appreciation to non-code contributors who are valuable to the project.

**Comment by mkaz** [comment]
This ticket was brought up in [today's core-editor chat](https://wordpress.slack.com/archives/C02QB2JS7/p1587565513159700) by @Soean 

**Questions raised:**

- Was it ever supposed to be used for code contributors in the first place?
- Is there an alternative place where contributors can get credited? if I google "Gutenberg contributors" it's the first link, and other links aren't very relevant
- The [contributors page on Github](https://github.com/WordPress/gutenberg/graphs/contributors) only shows the top 100 contributors for the selected time range.

**Suggestions:**

- Maybe we remove code contributors from the file, and only list non-code contributors and add  a link to Github contributor list
- Could we use something like: https://allcontributors.org/

**Comment by youknowriad** [comment]
This file was just removed.

I forgot about the existence of this issue.
