### ISSUE TITLE
Standardize script naming in main package.json

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#19949]
During development of #19855, we struggled with the naming of new scripts, and realized there wasn't quite a standard for how scripts should be named within package.json. For example, when and why to use dash to separate parts, or when to use `:`

@gziolo suggested:

> We could bring some structure to the names of all the existing scripts in the main package.json file as an independent patch smile

This ticket opens the discussion for it so we don't forget to circle back on it.

**Comment by gziolo** [comment]
Sharing a related tool that could be used as a baseline for the patterns: https://github.com/peerigon/scriptlint.

The rules they offer for the `package.json`'s `"scripts"` section:

- have a `test` script that is not the default script from `npm init`
- have a `dev` script and a `start` script
- _abstract script names from their implementation (`test`, not `jest`)_
- _use namespaces to categorize scripts (`"test:unit": "jest"`)_
- _use `:` as a namespace separator_
- _have the scripts in alphabetic order_
- _have a trigger script for all hooks (ex: if you have `prefoobar`, there must be a `foobar` script)_
- _use `camelCase` for all script names_
- _not alias `devDependencies` (no `"jest": "jest"`)_
- _not use `&&` or `&` for sequential or parallel script execution_

(_italic = strict rule_)

**Comment by gziolo** [comment]
@t-hamano, now that you wrapped up all tasks to make tooling work with Windows OS, do you think we would benefit from standardizing script naming in `package.json`? I'm on the fence now because those commands are documented in so many places and they have been around for so long.

**Comment by t-hamano** [comment]
> do you think we would benefit from standardizing script naming in package.json?

Yes, I agree with you.

However, since npm script is used in various places (including GitHub Actions), I wonder how to proceed.
Which is better to standardize scripts in one PR or in stages?

**Comment by gziolo** [comment]
> However, since npm script is used in various places (including GitHub Actions), I wonder how to proceed.
Which is better to standardize scripts in one PR or in stages?

I hope it's possible to do it one PR and keep old aliases for some transition period.

**Comment by t-hamano** [comment]
I see, is this what you mean by keeping old aliases ? 🤔

```json
{
	"name": "gutenberg",
	"version": "13.6.0",
	"scripts": {
		//new scripts
		"new-dev": "npm run build:packages && concurrently \"wp-scripts start\" \"npm run dev:packages\"",
		"new-build": "npm run build:packages && wp-scripts build",
		// old scripts
		"dev": "npm run new-dev",
		"build": "npm run new-build"
	}
}
```

**Comment by gziolo** [comment]
> I see, is this what you mean by keeping old aliases ? 🤔

Yes, that would work as a temporary solution for a few months 👍🏻

**Comment by t-hamano** [comment]
Ok, then I would like to work on this issue.
I would like to temporarily install `scriptlint` and start by scanning the current script.

**Comment by gziolo** [comment]
@t-hamano, excellent work tackling this task ❤️
