### ISSUE TITLE
Some blocks might not play well inside vertical aligned columns

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#19962]
**Describe the bug**
Playing with the Slideshow block in Jetpack, I found a possible bug in the Columns block.

**To reproduce**
1. Install and activate Jetpack
2. Add a columns block (using the 50%-50% layout preset) in a page
3. Add a Slideshow block inside one of the columns and add some images to it
4. Set a explicit vertical alignment in the columns block (top, center or bottom)
5. The Slideshow disappears

**Expected behavior**
The block works as expected

**Screenshots**
![alignment-none](https://user-images.githubusercontent.com/2060659/73450515-d86cfa80-4365-11ea-9da1-71a9f9e0ff4b.jpg)
![alignment-top](https://user-images.githubusercontent.com/2060659/73450526-db67eb00-4365-11ea-9d44-b02e60b7d981.jpg)
![alignment-center](https://user-images.githubusercontent.com/2060659/73450529-dc991800-4365-11ea-976a-2fbda75de0b8.jpg)
![alignment-bottom](https://user-images.githubusercontent.com/2060659/73450533-ddca4500-4365-11ea-8c52-59f7c9b7c504.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 72 and Chrome 79

**Additional context**
- I'm using the Gutenberg version that comes with WordPress 5.3.2

**Possible fix**

If I add `width: 100%` to the `.wp-block-column.is-vertically-aligned-top`, `.wp-block-column.is-vertically-aligned-center` and `.wp-block-column.is-vertically-aligned-bottom` CSS rules in Gutenberg, the slider block works as expected:

```
.wp-block-column.is-vertically-aligned-center {
    align-self: center;
    width: 100%; /* new */
}
```

**Comment by jorgefilipecosta** [comment]
Hi @mrleemon, thank you for reporting this issue. Hi @getdave, would you be able to have a look into this problem?

**Comment by mrleemon** [comment]
The Image Slider block from the following plugin https://wordpress.org/plugins/getwid/ suffers the same problem.

**Comment by mrleemon** [comment]
The Image Slider block from the following plugin https://wordpress.org/plugins/ultimate-blocks/ doesn't overflow the column when vertically aligned but there are some visual glitches if the `width: 100%` property is not present.

**Comment by mrleemon** [comment]
The Image Slider block from the plugin https://wordpress.org/plugins/otter-blocks/ is affected by this, too.

**Comment by mrleemon** [comment]
The Gutenbee plugin https://wordpress.org/plugins/gutenbee/ is also affected by this.

![gutenbee-without](https://user-images.githubusercontent.com/2060659/74586863-2c294600-4fec-11ea-8314-09141a1614d7.png)
![gutenbee-with](https://user-images.githubusercontent.com/2060659/74586865-2e8ba000-4fec-11ea-978f-fa743d92938e.png)

**Comment by paaljoachim** [comment]
Andrew @aduth 
I think this is an issue you might want to know about.
