### ISSUE TITLE
Mobile block library goes out of view on click

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#19977]
GIF:

![mobile block library](https://user-images.githubusercontent.com/1204802/73522730-7c5bb200-4409-11ea-8c3b-f4872e4c1e72.gif)

Steps to reproduce:

- Open the block library at a mobile breakpoint (<600px)
- Click anything that isn't a block, header or accordion

Result: layout breaks

This is possibly a regression from #19268.

**Comment by ellatrix** [comment]
Isn't this a duplicate of #19758 and fixed by #19771?

**Comment by jasmussen** [comment]
Probably and not sure. I saw the above issue in master this morning. Are you not seeing it? I've been having some issues with my local environent, so it's entirely possible I did something wrong.

**Comment by ellatrix** [comment]
I'll test right now :)

**Comment by ellatrix** [comment]
You are completely right. It is broken. I'll fix it now.
