### ISSUE TITLE
Nav block: sub menu hidden when Nav block not selected.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#19986]
I noticed that the sub menu is not seen when the navigation block is not selected.

![Screen Shot 2020-01-31 at 17 43 20](https://user-images.githubusercontent.com/5323259/73557281-39253180-4451-11ea-8f19-008ea4be6521.png)

Then when clicked it looks like this:

![Screen Shot 2020-01-31 at 17 43 57](https://user-images.githubusercontent.com/5323259/73557348-4e9a5b80-4451-11ea-8051-57d37ea7f044.png)

It would be good to show the full navigation structure when hovering over the nav block, as it quickly gives an idea of all elements in the navigation block.

Selecting the block: This whole thing really needs to be cleaned up.
Make it more consistent with other blocks. https://github.com/WordPress/gutenberg/issues/19984
Perhaps left align submenu to parent menu item. Having them on a left aligned invisible vertical line.

Btw I have used the theme Twenty Twenty for the various Navigation block tests.

**Comment by paaljoachim** [comment]
Regarding the cleaning up that will happen here: https://github.com/WordPress/gutenberg/issues/18667

I still think that we need to in some way show the submenu when not clicked. 
But perhaps it is good enough to just leave as it is for the moment.

A related issue I made and have closed: https://github.com/WordPress/gutenberg/issues/19984

I can leave it open for now and it can be closed any time.

**Comment by draganescu** [comment]
Hi, isn't the inspector tree showing all the items by default? It would be very hard to edit in space-constrained situations (kinda everywhere) if the menu would be always showing all the sub-items, right?

**Comment by paaljoachim** [comment]
Hey Andrei

I am taking another look.

Clicking/selecting the nav block I do expect to see the full menu. At present time clicking the nav block one only sees the top menu items.
<img width="1090" alt="Screen Shot 2020-02-12 at 10 00 09" src="https://user-images.githubusercontent.com/5323259/74319002-83c27a00-4d7e-11ea-82ff-351b0f6898fe.png">

I have to click into the menu item that has a submenu for the submenu to be seen:
<img width="728" alt="Screen Shot 2020-02-12 at 10 02 47" src="https://user-images.githubusercontent.com/5323259/74319253-e7e53e00-4d7e-11ea-96d5-baf47b0c7cd0.png">

My suggestion would be to hover over the menu block to get a kind of quick birds eye view of the full navigation structure. + I would also suggest when clicking/selecting the nav block that all menu items are seen. 

Clicking into a menu item it would be helpful to also have a better visual "this is selected" for instance adding a lighter background color behind the menu item that is selected. 
![Nav-Block-Selected-menu-item](https://user-images.githubusercontent.com/5323259/74319904-ff70f680-4d7f-11ea-933a-219c497ff05c.jpg)

The Inspector tree in the sidebar and the Block navigation both show the nav tree. But this is somewhat separate from interacting with the navigation.
Clicking Block navigation - inspector tree:
<img width="370" alt="Screen Shot 2020-02-12 at 10 00 57" src="https://user-images.githubusercontent.com/5323259/74319059-9f2d8500-4d7e-11ea-8264-b1e504eea947.png">

**Comment by karmatosed** [comment]
This is by design as it's a sub-navigation. I am not sure showing it all on hover is good as that could be distracting. I am open to other ways that the navigation feels more obvious though. What other ideas might there be?

**Comment by paaljoachim** [comment]
I think I want to close this issue for now, as there are so many changes going on in the interface. We can instead reopen when/if needed.
