### ISSUE TITLE
Nav block: A more consistent block experience.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#19984]
I am looking at the Navigation block experience and comparing it with other blocks. Clicking into the block it then suddenly looks like this:

![Screen Shot 2020-01-31 at 16 59 09](https://user-images.githubusercontent.com/5323259/73554054-51924d80-444b-11ea-9b43-145402c4cdbf.png)

Tests looks like it is outside of the navigation block. 
It looks like the navigation contains a bug the way it looks when clicked into.

--

Here is a new wireframe example. That uses some of the same structure and consistency as blocks today. We then need a way to show the current selected menu item.

![Nav-section-Gutenberg](https://user-images.githubusercontent.com/5323259/73555818-923f9600-444e-11ea-84ec-f219c7abf5ea.jpg)

One clicks a menu item and a border shows up around it. Giving a clear signal that the specific item is selected.

**Comment by mapk** [comment]
It's similar to clicking into the Columns block or any other block with nested blocks.

**Columns block**

![Screen Shot 2020-02-03 at 11 57 12 AM](https://user-images.githubusercontent.com/617986/73686242-791c2c80-467c-11ea-8c86-cdfc2ad9cc7d.png)

**Social block**

![Screen Shot 2020-02-03 at 11 57 45 AM](https://user-images.githubusercontent.com/617986/73686269-833e2b00-467c-11ea-8190-b7e843febe3a.png)

I recommend holding off on any work around this until G2 is implemented. It may help alleviate some of the problems here. In fact with G2, without the left-border, it seems to work nicely.

![Screen Shot 2020-02-03 at 12 04 07 PM](https://user-images.githubusercontent.com/617986/73686710-5fc7b000-467d-11ea-87fa-9c472b747fa3.png)

@paaljoachim, if you agree, what do you think if we close the issue?

**Comment by paaljoachim** [comment]
> I recommend holding off on any work around this until G2 is implemented. It may help alleviate some of the problems here. In fact with G2, without the left-border, it seems to work nicely.

I agree the work with G2 without the left border will make a much nicer visual experience. I wonder though if it might be better to have a fixed toolbar that does not move around in relation to block content that is clicked. The toolbar seems like the stable area as the content varies.

**Comment by paaljoachim** [comment]
Btw 
I really hope the social block still does not look like that. For it looks like a bug when the toolbar with the black vertical line moves. As we are used to having the toolbar stand still. 
Nesting such as the columns the toolbar for a nested block stands still over each nested block. The black vertical line when the toolbar moves make it feel really out of place.

**Comment by retrofox** [comment]
> Tests looks like it is outside of the navigation block.

True, because indeed it's effectively outside of the Navigation, it's inside of the NavigationLink. If you focus the Navigation block, you will get the toolbar in the desired place.

![image](https://user-images.githubusercontent.com/77539/74047170-c05c3300-4984-11ea-8d89-28b419c25ae9.png)

> It's similar to clicking into the Columns block or any other block with nested blocks.

:this:
