### ISSUE TITLE
Is the block selection list too narrow for long block titles?

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#20006]
**Describe the bug**
I'm developing a new block which currently has a 40 character title (1st example - above the ruler).

When the block selection list is displayed it gets wrapped onto 2 lines.
It doesn't look right. 

```
Content block for dynamic oik-shortcodes
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9
Content block for dynamic oik-shortcodes. Expands dynamic content oik shortcodes.
Content block for dynamic oik-shortcodes. Expands dynamic content oik shortcodes. OK in block manager?

```
When the block name is longer ( 2nd and 3rd example ) part of the title isn't displayed.

Note: When the block name is longer the Block Manager can handle it. 
The Block Manager expands as the block title gets longer. 
The Block Inserter also displays the full title. 

BTW. I'm using Chrome on Desktop here.

**To reproduce**
1. Register a block with a long `title:` attribute.
2. At the block inserter type `/startofthelongblocknameyouchose`
3. See the popup with the block name wrapped and cropped.

**Expected behavior**
I don't know what should happen. That's why it's a question.
Whatever solution is proposed it should cater for translations, 
which are often longer than the English. 
eg. bloc de contenu pour les codes courts dynamiques.

Easy suggestion. Perhaps the documentation needs to be updated to recommend using a shortish title. 
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/73661700-66145700-4692-11ea-82c4-f7b814abdb02.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 79.0.3945.130 

**Smartphone (please complete the following information):**

**Additional context**
Gutenberg 7.3.0
See also #1721

**Comment by mapk** [comment]
I tested this and noticed and only noticed an issue in the `/` slash inserter. The other instances had a somewhat decent solution.

### The `/` slash inserter
The words seemed to be centered when pushed to two lines.

![Screen Shot 2020-02-03 at 12 07 36 PM](https://user-images.githubusercontent.com/617986/73687076-1f1c6680-467e-11ea-9089-c849ad81c0d0.png)

### The Block Manager
The really long name just pushes the modal to be wider.

![Screen Shot 2020-02-03 at 12 09 20 PM](https://user-images.githubusercontent.com/617986/73687127-3bb89e80-467e-11ea-8b9e-0f4120268659.png)

### The Block Library
The text is restrained but pushed to multiple lines.

![Screen Shot 2020-02-03 at 12 11 29 PM](https://user-images.githubusercontent.com/617986/73687224-6c003d00-467e-11ea-82af-a0525e8e8351.png)

**Comment by mapk** [comment]
I recently tested the `/` inserter and it looks better now.

![Screen Shot 2020-05-12 at 9 15 40 AM](https://user-images.githubusercontent.com/617986/81718986-4e870000-9431-11ea-9d72-e46ffd937f92.png)
