### ISSUE TITLE
There is no navigation block

### ISSUE THREAD

**Issue by jucunda** [WordPress/gutenberg#20005]
With me there is no navigation block.
I can not change font or anything else, nor can I link buttons etc. What do I have to do?
![Guttenberg](https://user-images.githubusercontent.com/42065490/73661945-45043400-469b-11ea-9b5d-23e6d51a721f.jpg)

**Comment by jorgefilipecosta** [comment]
Hi @jucunda,
The navigation block does not appear by default. It needs to be inserted by going to the block inserter and searching for it. Is the block not appearing on the block inserter? What version of Gutenberg are you using?

Thank you in advance for any additional information you could provide.

**Comment by jucunda** [comment]
Hi @jorge Costa

 

I am usin Version 730.

 

Greetings

Werner

 

Von: Jorge Costa <notifications@github.com> 
Gesendet: Montag, 3. Februar 2020 20:00
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] There is no navigation block (#20005)

 

Hi @jucunda <https://github.com/jucunda> ,
The navigation block does not appear by default. It needs to be inserted by going to the block inserter and searching for it. Is the block not appearing on the block inserter? What version of Gutenberg are you using?

Thank you in advance for any additional information you could provide.

**Comment by paaljoachim** [comment]
Hi Jucanda

In using the Gutenberg plugin 7.3.0.

By pressing the inserter (circle with + in it) and beginning to write nav I see this:
![Screen Shot 2020-02-04 at 01 14 19](https://user-images.githubusercontent.com/5323259/73702324-bc15e880-46ec-11ea-81d0-2f0554b76e68.png)

-----

Ahhh. It looks like the toolbar is not showing up in the screenshot you shared. 
I am thinking you have an error.

Right click anywhere on your screen and choose Inspect and then Console and see if there are any errors that show up. Copy the errors into a message here. Thanks.

**Comment by jucunda** [comment]
Hello Joachim.

here is the Screenshot. 

Sorry, in German language.

 

 

 

 <http://www.jucunda-juechen.de/> 

 

Birkenstr. 5; 41363 Jüchen; redaktion@jucunda-juechen.de 

 

Von: Paal Joachim Romdahl <notifications@github.com> 
Gesendet: Dienstag, 4. Februar 2020 01:25
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] There is no navigation block (#20005)

 

Hi Jucanda

In using the Gutenberg plugin 7.3.0.

By pressing the inserter (circle with + in it) and beginning to write nav I see this:
 <https://user-images.githubusercontent.com/5323259/73702324-bc15e880-46ec-11ea-81d0-2f0554b76e68.png> 

  _____  

Ahhh. It looks like the toolbar is not showing up in the screenshot you shared.
I am thinking you have an error.

Right click anywhere on your screen and choose Inspect and then Console and see if there are any errors that show up. Copy the errors into a message here. Thanks.

**Comment by paaljoachim** [comment]
Hi Jucanda. Click the 3 dots to edit your post and re-add the screenshot again. It is not showing up.

**Comment by jucunda** [comment]
I hope, i understood!

 

Here one more Try

 

 

 

 

 <http://www.jucunda-juechen.de/> 

 

Birkenstr. 5; 41363 Jüchen; redaktion@jucunda-juechen.de 

 

Von: Paal Joachim Romdahl <notifications@github.com> 
Gesendet: Dienstag, 4. Februar 2020 19:11
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] There is no navigation block (#20005)

 

Hi Jucanda. Click the 3 dots to edit your post and re-add the screenshot again. It is not showing up.

**Comment by paaljoachim** [comment]
Hello again Jucunda

Drag and drop an jpg or png or gif into the area you are writing in. Give it a few moments to upload. See this video: https://www.youtube.com/watch?v=pp1NzgH-EK0

Btw
Do also make a search in a search engine to learn more about how Github works. As it is good to learn the basics of Github.

If you have difficulty explaining/writing in English then use Google translate or something similar to write in German and then have it translated to English. Then paste it in to a response.

Hopefully this helps..:)

**Comment by talldan** [comment]
@jucunda I think you'll have to use the github interface to reply and upload your image, rather than replying via email.

Here's the link to do that, you'll need to make sure you're logged in: https://github.com/WordPress/gutenberg/issues/20005

**Comment by jucunda** [comment]
I will try it here:
![Guttenberg 2](https://user-images.githubusercontent.com/42065490/74020623-420a8b80-499a-11ea-946e-c5be680556f3.jpg)

**Comment by paaljoachim** [comment]
Hey Jucunda! Yes that worked. I am more of a design person myself so a developer will need to comment on the error codes that exist in the screenshot you shared.

**Comment by jucunda** [comment]
10 Minutes before it came a Update.

Now It works perfect.

 

 

 

 

 <http://www.jucunda-juechen.de/> 

 

Birkenstr. 5; 41363 Jüchen; redaktion@jucunda-juechen.de 

 

Von: Paal Joachim Romdahl <notifications@github.com> 
Gesendet: Freitag, 7. Februar 2020 11:47
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] There is no navigation block (#20005)

 

Hey Jucunda! Yes that worked. I am more of a design person myself so a developer will need to comment on the error codes that exist in the screenshot you shared.

**Comment by paaljoachim** [comment]
Great to hear! :)
Please click the comment and close red button below, so we can close this issue.
Thanks!
