### ISSUE TITLE
Gutenberg Editor : Custom Shortcodes and Metaboxes

### ISSUE THREAD

**Issue by Ansif** [WordPress/gutenberg#2002]
Hi,

I just want to know the possibilities of adding Custom Shortcodes and Custom Metabox options like we do already within WordPress API.

### How can i add our own shortcodes in this insert link?
![custom-shortcode](https://user-images.githubusercontent.com/5621180/28571646-831118ec-7161-11e7-8457-08270ece7dcc.png)

<hr>

### How can i add metabox options in sidebar?
![metabox](https://user-images.githubusercontent.com/5621180/28571660-944c69d6-7161-11e7-8a4d-c2f3f8faf51e.png)

Thanks! 👍

**Comment by westonruter** [comment]
@Ansif for the first point, you can add new blocks via the documentation you can find at https://github.com/WordPress/gutenberg/tree/master/blocks#readme

As part of this, you can add controls to the Block settings which appear in the sidebar.

As for adding entirely new expandable sections in the sidebar, this is not yet supported. But you can follow the conversation at #1352.
