### ISSUE TITLE
Create a "gutenberg" GitHub team so contributors can request feedback

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#2003]
To improve the contributor workflow, it would be helpful to have a `@wordpress/gutenberg` GitHub team so contributors can request feedback without knowing who to ping directly.

If this team is created, then it should be mentioned in `CONTRIBUTING.md` for visibility.

**Comment by mtias** [comment]
I can look at setting this up.

**Comment by mtias** [comment]
Sorry for the delay here, there's both a gutenberg team and a gutenberg-core (which should cover your need for pings).
