### ISSUE TITLE
Backport PR's to WordPress core (5.4 Release)

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#20035]
To check for PR's to backport to WordPress core that were not labeled I checked the git history until 25 of September 2019 for the lib folder:
https://github.com/WordPress/gutenberg/commits/master/lib

From this set, some were issues already backported into 5.3. 
Most refer to changes to features not yet part of the core (Widgets, FSE), etc..

I concluded that the following PR's need to be backported:

 - [ ] Gradients theme API: https://github.com/WordPress/gutenberg/pull/17603, https://github.com/WordPress/gutenberg/pull/17841, https://github.com/WordPress/gutenberg/pull/20107
Assigned to: @jorgefilipecosta 
Ticket: https://core.trac.wordpress.org/ticket/49389
 - [x] Expanding on sentence case to everywhere else https://github.com/WordPress/gutenberg/pull/18758
Original developer involved: @mcsf 
 - [ ] And new block editor settings in core https://github.com/WordPress/gutenberg/pull/17151
Original developers involved: @ryelle  
Ticket: https://core.trac.wordpress.org/ticket/49389

I had doubts if this PR need any backporting/core work:
 - [x] Packages: Add information for webpack about no side effects - https://github.com/WordPress/gutenberg/pull/17862
cc: @gziolo 
 - [x] Switch require_once to require for loading asset files #18599
cc: @mkaz 
 - [ ] Deprecate '@wordpress/nux' package #18981
cc: @noisysocks 
 - [x] Add an apiFetch middleware to automatically handle media upload failures
#17858
cc: @youknowriad 

@gziolo, @mkaz, @noisysocks could you confirm if the PR referred need any backporting/change in core

@epiqueras I checked that you have several PR's touching the PHP codebase related to FSE. I think none of this PR's needs to be backported, but could you confirm that?

If I'm missing a PR to backport, please let me know.

**Comment by epiqueras** [comment]
>@epiqueras I checked that you have several PR's touching the PHP codebase related to FSE. I think none of this PR's needs to be backported, but could you confirm that?

They're only for the experiment.

**Comment by youknowriad** [comment]
Should we close this @jorgefilipecosta ?

**Comment by jorgefilipecosta** [comment]
Closing this issue as 5.4 was already release :)
