### ISSUE TITLE
RangeControl does not show value in input and does not work if there is no icon

### ISSUE THREAD

**Issue by zkmark** [WordPress/gutenberg#20037]
**Describe the bug**
RangeControl does not display the values saved in input, and does not work if it has no icon

**To reproduce**

1.- use the same example here
https://developer.wordpress.org/block-editor/components/range-control/#usage-2

2.-and it looks like this ( picture 1)

3.- I added the icon and it looks like this (picture 2) 
RangeControl already works
 but does not display the values saved

`
const MyRangeControl = withState( {
			columns: columns,
		} )( ( { columns, setState } ) => (
			<RangeControl
				beforeIcon="admin-settings"
				label="Columns"
				value={ columns }
				onChange={ ( columns ) => setState( { columns } ) }
				min={ 2 }
				max={ 10 }
			/>
		) );
`

**Expected behavior**
to show the number as in picture 3

**Screenshots**
![range](https://user-images.githubusercontent.com/10190162/73789368-45b4cd00-4764-11ea-8ccb-c2134bd22c84.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
- Wordpress 5.3.2

**Comment by talldan** [comment]
@zkmark Could you provide some more information, what exactly isn't working when there's no icon? It looks like there's no slider bar in the pic, is that right?

When I tried the linked example from the docs, this is what I'm seeing (this was added in one of the sidebars in the block editor):
![Screen Shot 2020-02-05 at 1 56 08 pm](https://user-images.githubusercontent.com/677833/73814922-5f671a80-481f-11ea-8b4d-fb2e5f1ae6f8.png)

There are also examples in the Gutenberg StoryBook that seem to work ok without an icon:
https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--default

One thing that might help is understand exactly where you're looking to add the RangeControl (e.g. an editor plugin, or a completely separate app), and also if you could share the exact code snippets you're using.
