### ISSUE TITLE
Autosave should not save empty content even when using Gutenberg templates

### ISSUE THREAD

**Issue by swedishboy** [WordPress/gutenberg#20033]
New custom posts get autosaved even if the content is empty and no title has been set when using a blocks template for a custom post. This can end up in cluttering your post screen with a lot of untitled empty posts.

_Solution:_
The autosave progress should check if the content compared to a new post (with it's block template) are equal and if so not create an autosave. Possibly add a parameter for register_post like autosave_empty_templates = false/true.

_Alternative:_
I'm aware I can use the hook `wp_insert_post_empty_content` to stop this from happening. But maybe a default template that's not been altered should be considered empty?

**Comment by jorgefilipecosta** [comment]
Hi @swedishboy thank you for reporting this issue 👍 

Hi @epiqueras, can the API's you used to fix the problem of template parts making the post dirty being used here to address this problem?

**Comment by epiqueras** [comment]
Yes, it can make sure the template sync does not introduce a dirtying change.

**Comment by epiqueras** [comment]
Mmm, what version of Gutenberg is this with? On `master` these initial template syncs are already non-persistent.

**Comment by swedishboy** [comment]
How is this check planned to work? Right now autosave does not save blocks using the metadata box model. (source meta) I ran a test where the only thing I changed was a meta select menus value. It saved a blank post **without** the metadata. I think the autosave should save metadata in case it's been set/changed.

@epiqueras In case you're asking what version I was using for my test: I don't know the gutenberg version. _WP is 5.3.2_

**Comment by epiqueras** [comment]
Autosaves do save post meta.

Can you try with the plugin?

**Comment by swedishboy** [comment]
Aha. Interesting. Will do. 

How far behind is the built in Gutenberg shipped with wordpress compared to the plugin? I didn't know there was a seperate plugin to get more functionality. It might be common knowledge for those knowing Gutenberg better, but for one who's just started learning the ins and outs it can be a bit puzzling if you read some docs and think you can do X with Gutenberg but it's only supported in a later version used in the Gutenberg plugin.

**Comment by epiqueras** [comment]
The plugin is updated every ~2 weeks.

**Comment by swedishboy** [comment]
Ok. Even when using the Gutenberg plugin empty posts with my custom block template gets saved. My template consists of a few custom blocks and a meta connected block. There are some file blocks and a block group with my meta block and a few others.

Preferably the check should strip any common tags (for example <p> and most inline except <img>) trim the `$post_content` var  and just look for text in `post_content` and `post_title`.

Some of you may ask is this important? Yes. Imagine a big wordpress site (magazine or such) with a lot of editors/writers. Let's say you have a staff of 50 people writing stuff. If each one accidentaly creates just 1 empty post per day you would, after just one week, have 350 empty drafts (!). Having to delete them with the default screen setting of 20 posts per page you would have to wade through over 17 pages using the bulk action for move to trash.

**Comment by epiqueras** [comment]
It could be the file block causing the issue. Sometimes these introduce changes on-mount. Can I see the code for the template?

**Comment by swedishboy** [comment]
Here's the empty post's genereated block-tags from start without any input
```
<!-- wp:mysite/intro -->
<p class="wp-block-mysite-intro"></p>
<!-- /wp:mysite/intro -->

<!-- wp:paragraph {"placeholder":"Enter text here..."} -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:mysite/metagroup -->
<div class="wp-block-mysite-metagroup"><!-- wp:mysite/publisher /-->

<!-- wp:mysite/metaboxes /-->

<!-- wp:mysite/writer /-->

<!-- wp:file /-->

<!-- wp:file /-->

<!-- wp:file /--></div>
<!-- /wp:mysite/metagroup -->
```

**Comment by swedishboy** [comment]
I tried using the `wp_insert_post_empty_content` filter to short circuit any autosaves. But now it stopped working so I'm investigating a fix.

**Comment by swedishboy** [comment]
Is gutenberg using it's own autosave? Or is it firing `heartbeat_autosave`?

**Comment by swedishboy** [comment]
> I tried using the `wp_insert_post_empty_content` filter to short circuit any **empty** autosaves. But now it stopped working so I'm investigating a fix.

Got it working again. Apparently Gutenberg sometimes saves the post as draft and not auto-draft. Don't know excatly how and why. So now my `wp_insert_post_empty_content` filter looks like this:
```
function check_autosave_content($maybe_empty, $postarr) {
	 $content = trim( strip_tags($postarr['post_content'],'<img><iframe>') );
	 if( empty($content) && stripos($postarr['post_status'], 'draft') !== false) {
		if( empty(trim($postarr['post_title'])) )
			return true;
	 }
	return false;
}
```

**Comment by swedishboy** [comment]
However this fix I use for the time being is not optimal since it displays an error message in Gutenberg. Preferably this would be silent.

**Comment by epiqueras** [comment]
Is the issue still present with a simple template without any of your custom blocks?

**Comment by karmatosed** [comment]
Just checking if this is still an issue?

**Comment by annezazu** [comment]
@swedishboy closing this out for now since there hasn't been an update. If this is still an issue, please test against the latest version of Gutenberg and feel free to reopen. Thank you!
