### ISSUE TITLE
Gallery Images Need to Be Resolved After Transforming into Image Blocks

### ISSUE THREAD

**Issue by MauiPhotographer** [WordPress/gutenberg#20041]
I have been having a problem with needing to resolve images after transforming a gallery into blocks. I have three photography blogs and it is happening on all of them. 

I saw this post here that was closed about the problem. 

https://github.com/WordPress/gutenberg/issues/14231

The part that is missing is that the photos are imported as a gallery and as soon as you transform the gallery into individual blocks, by clicking the **Image button**, so you can tag the images individually then save and go back in it wants you to resolve all the images. 

Here a couple of photos. 

![shot](https://user-images.githubusercontent.com/60678963/73803900-3898dd80-4766-11ea-9455-70ac1970d9b0.jpg)
![shot2](https://user-images.githubusercontent.com/60678963/73803912-40588200-4766-11ea-9396-a2006ff7884e.jpg)

So this is the process: 

1. You upload the images as a gallery
2. You transform the gallery images into blocks using the block transformation button (or you can't tag the images in the visual editor). 
3. Once you transform the images into blocks.  Save the post and exit the post back to the main post editor. 
4. Go back into the post and it will ask you to transform all of the images. 

It happens to us every time on 3 different blogs. We have created nearly 30 posts that it has happened on and nobody can figure out the problem from multiple help forums. 

Here is another post I did on Wordpress with no resolution.

https://wordpress.org/support/topic/breaking-image-gallery-into-blocks-creates-a-mess/

Please help!!

**Comment by Ringish** [comment]
@MauiPhotographer I'm afraid I can't reproduce the error. What steps are you doing when uploading the images? Do you add a gallery and uploads the images from there?

**Comment by talldan** [comment]
I was able to reproduce this a couple of times, but it was inconsistent for me, it didn't happen every time. 

Here's a screenshot of my console log showing how the markup differs:
![Screen Shot 2020-02-07 at 11 10 47 am](https://user-images.githubusercontent.com/677833/73997858-bba27980-499a-11ea-9015-c2525aa20f86.png)

I'll look into this some more today to see if I can find the cause.

**Comment by talldan** [comment]
I see what the issue is. The gallery sometimes stores its image ids as strings instead of numbers, while the image block requires them to be numbers. If they're not numbers when transforming the blocks end up being invalid.

Some reproduction steps that should work every time:
1. Create a gallery with a couple of images
2. Edit the caption of one of the images (this will cause the ids to change from numbers to strings).
3. Transform the gallery to image blocks
4. Save the post.
5. Reload
6. Observe the images are invalid.

I'll work on a fix.
