### ISSUE TITLE
Allow Ability to Italicize part of a Post Title 

### ISSUE THREAD

**Issue by ccwalburn** [WordPress/gutenberg#20048]
**Summary**
It is possible to italicize part of a post title in the Classic Editor by using the `<em>` tag, but it doesn't seem to work with Gutenberg. This is particularly useful when your title contains a book name because it is standard practice to italicize book titles.

I have tested this by adding the title `The <em>Italic</em> TItle` to a post using the Twenty Twenty theme. If I create the post using the Classic Editor, it looks like this: 
![screenshot](https://d.pr/i/5u0Vd6+)
Image URL: https://d.pr/i/5u0Vd6

If I create it using Gutenberg, it looks like this: 
![screenshot](https://d.pr/i/PG6lPC+)
Image URL: https://d.pr/i/PG6lPC

**Describe the solution you'd like**
Allow formatting tags in the post title.

**Comment by talldan** [comment]
Hi @ccwalburn Thanks for reporting this. This was a bug that was introduced for a short time. It was fixed recently by this change - https://github.com/WordPress/gutenberg/pull/19955.

The fix will be released in version 7.4 of the Gutenberg plugin or WordPress 5.4 if you're not using the plugin.

**Comment by talldan** [comment]
Actually, it'd be good to double-check whether you're using the plugin @ccwalburn?

I don't think this bug was ever introduced into WordPress core, it should only have been temporarily in the plugin.

**Comment by ccwalburn** [comment]
Yes, the site was using the plugin. Thanks so much for letting me know and pointing me to the correct request!
