### ISSUE TITLE
Consider custom post type and custom fields support

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2005]
This came from the support forum for the plugin and worth us looking at:

> 1. Add support for custom post type and custom fields in a way that a content block could access CPT’s and its fields to display content from them. Pods and Beaver Themer do this kind of relational database publishing and adds enormous power to the wat pages are composed based on content form datatables.

> 2. Second thought on this would be the possibility to save a page buolt form ‘blocks’ as a template. CPT’s and CF’s are there for years and for plugin and theme developers it is great to program their archive and single (custom) post pages in PHP. But the need for non-PHP designers/web developers is there. Gutenberg might bring WordPress to a better accessible level of (relational) database publishing.

We may want to split these out into issues but I think it's worth adding here as a comment and feedback for us to review.

**Comment by westonruter** [comment]
Yes, both of these have been discussed. For point one, what is needed is adding support for a `source` (neé `matcher`) that pulls data from sources outside of the post content.

For the second point, this has also been discussed in the context of creating a box/group of blocks that have predefined default/placeholder values which users just have to fill in. Such a block could serve the basis of a page template or custom post type. Blocks in such a group could be locked so that they can't be removed or moved.

**Comment by cr101** [comment]
I'm planning to build a React-powered app using the WordPress REST API and the [Pods Framework plugin 2.7 Beta](https://pods.io/2017/05/30/pods-2-7-beta/). 
I've only just started playing around with Pods which enables you to create custom post types, field types (i.e relationship related to a taxonomy or or a post type, plain text, date, etc), custom taxonomies, connections between posts and taxonomies, etc.
Do you plan to add these Pods like features to Gutenberg?

**Comment by StaggerLeee** [comment]
So, it means Gutenberg is now quilty one why new major PODS version will be late for 3 more years ?
Already 7 years passed, always some "obstacles".

Sorry, had to. Joke or not.

**Comment by sc0ttkclark** [comment]
Not helpful Stagger, we've talked about this already and explained why that's not entirely true.

Back on topic -- I'm very interested in working with the Gutenberg team for the purposes of integrating Pods features.

**Comment by karmatosed** [comment]
I am going to close this as metaboxes are in PR.
