### ISSUE TITLE
Display comments respective to the post being edited

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#20054]
**Description**
The Latest Comments block fetches comments for the entire site. As a post author, I'd like the ability to display comments specific to their post.

**Considerations**
I would imagine this is related to the suite of blocks being created like #19953 and #19954 to support a generic Post Block (#15623).   

I do not know whether this is a new block, or a feature of the Latest Comments block.

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras, with comments for FSE this problem should be addressed right?

**Comment by epiqueras** [comment]
Yes
