### ISSUE TITLE
Cover Image: Add control for overlay opacity

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2006]
What if instead of an on/off toggle, we added a range slider for opacity?

![cover-slider](https://user-images.githubusercontent.com/2846578/28583647-e4cfcc2e-7137-11e7-81e4-486df024649f.png)

Could snap it to percentages of 10, maybe, and then allow any number in the input field.

**Comment by westonruter** [comment]
Also, this cover image control would particularly benefit from having the color options added in #2036, as it could be that if you have selected a light image then all you need is to select a dark color for the text. In that case, you wouldn't need any dimming at all.

**Comment by melchoyce** [comment]
Probably overkill, but could also be fun to add some CSS image filter options, like grayscale, sepia, and blur.

**Comment by WPDevHQ** [comment]
Could also do with further controls on fixed image like "image position" i.e contain, cover e.t.c

**Comment by karmatosed** [comment]
Closing this as it's merged in :)
