### ISSUE TITLE
Twenty Nineteen misalignment on editor

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20067]
I note I am only seeing this in Twenty Nineteen but it might also be a problem in other themes. I did explore all the "Twenties" and a few others to try and find if it was to do with editor styles. Props to @jasmussen for the idea to explore that.

I see the following in Chrome and Safari:

![twentynineteen](https://user-images.githubusercontent.com/253067/73937585-458c0d00-48dd-11ea-9409-dfd7fccb5b4c.png)

I tested on branch today with a recent install/run to make sure up to date.  I am marking this as high in case this is a situation needs fixing for 5.4 and looping in @mapk and @jorgefilipecosta. I know a few have seen this infrequently before but it now seems constant. 

A little note, if it does turn out to be Twenty Nineteen I can make a trac ticket but just in case this is editor let's open here first.

**Comment by karmatosed** [comment]
This trac ticket might be related and if so good to get fixed for 5.4: https://core.trac.wordpress.org/ticket/48526

**Comment by jasmussen** [comment]
Great detective work.

The misalignment issue you report is almost certainly the one that I have provide a patch for in the trac ticket. We really need that shipped for TwentyNineteen, as the refactor of the editor that makes the misalignment happen will ship with 5.4.

There's a separate misalignment issue with the default appender that needs fixing in the block editor, note the margin on the left here:

![Screenshot 2020-02-06 at 16 18 08](https://user-images.githubusercontent.com/1204802/73950596-792a5f80-48fc-11ea-910f-7aa3a0b2756c.png)

And then note once I've started typing:

![Screenshot 2020-02-06 at 16 18 20](https://user-images.githubusercontent.com/1204802/73950621-80ea0400-48fc-11ea-937b-c762aad42557.png)

Note that the font discrepancy is _separete_ from that, and is a TwentyTwenty specific issue, that is in part tracked in https://github.com/WordPress/gutenberg/issues/18571.

**Comment by kjellr** [comment]
Just a heads up that I've updated [core.trac.wordpress.org/ticket/48526](https://core.trac.wordpress.org/ticket/48526), and it should definitely take care of this. It needs some testing and a couple more small fixes before landing.

**Comment by jorgefilipecosta** [comment]
Closing this ticket as https://core.trac.wordpress.org/ticket/48526 seems to address the issue. Thank you to all involved.
