### ISSUE TITLE
Block Editor: Warning when rendering InnerBlocks

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20069]
**Describe the bug**

A warning is logged in development environments when a Columns block (or presumably any block with `InnerBlocks`) is rendered.

```
react-dom.8b3dda97.js?ver=16.9.0:539 Warning: React does not recognize the `hasPopover` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `haspopover` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**To reproduce**

1. Navigate to Posts > Add New
2. Insert a Columns block
4. Open Developer Tools Console and observe warning

**Expected behavior**

No warnings.

**Additional context**

Introduced in #19922.

Fix is to avoid applying prop to `Container` when `Container` is assigned as `'div'`.

https://github.com/WordPress/gutenberg/blob/8313c650f7d1bdb5e3dc893888e467afed4da329/packages/block-editor/src/components/block-list/index.js#L74

https://github.com/WordPress/gutenberg/blob/8313c650f7d1bdb5e3dc893888e467afed4da329/packages/block-editor/src/components/block-list/index.js#L82-L89

cc @yansern, @ockham

**Comment by ragnarokatz** [comment]
@aduth Hello, I would like to give this issue a try please.

**Comment by ragnarokatz** [comment]
@aduth Hello, I have created a PR to address this issue. Please review it when you have time. Thanks.

**Comment by yansern** [comment]
@aduth Thank you for catching that issue and @ragnarokatz thank you for getting to this swiftly.

**Comment by ockham** [comment]
Sorry, missed that in my review!
