### ISSUE TITLE
NavigationLink: caret is hidden when the label is empty

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#20073]
**Describe the bug**
When the label of the NavigationLink is empty and focused, the carte isn't shown.

**To reproduce**
1. Go to post edit.
2. Create a Navigation menu
3. Add a Navigation Link
4. Do not select a link. Just close the popover
5. Focus the label in order to start to edit it

Confirm that the caret is not there. However, if you start to type, it appears. 

**Expected behavior**
Be able to see the caret even when the label is empty

**Screenshots**
![no-cartet-issue](https://user-images.githubusercontent.com/77539/72998391-8283da00-3ddc-11ea-8f0c-fa91a9583fc7.gif)

**Comment by jorgefilipecosta** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/20075.
