### ISSUE TITLE
Link Control: Give Create Page option priority unless search term is URL-like

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#20079]
Important! Requires https://github.com/WordPress/gutenberg/pull/19775 to be merged. Originally brought up here by @shaunandrews : https://github.com/WordPress/gutenberg/pull/19775#issuecomment-582974659

> I know we've talked about it in the past, but it would be nice to not show the default "Press ENTER to add this link" option unless the text entered looks like a URL. If I'm typing "Services" I'd expect the "New page" button to be the first option and that pressing enter would add the new page

When using the Link Control component to create a new page, we should give priority to the Create Page unless the search term is URL-like.

**To reproduce**
1. Add a link to the navigation block
2. Enter a one word search, like "Demo"
3. See the priority is given to "press Enter to add this link"

**Expected behavior**
Unless the term is a valid URL, it doesn't really make sense to show the URL option, and especially not give it priority.

**Screenshots**
<img width="453" alt="Screen Shot 2020-02-06 at 2 59 58 PM" src="https://user-images.githubusercontent.com/967608/73978335-bc330580-48f1-11ea-9a77-b4524518e669.png">

**Comment by adamwoodnz** [comment]
https://github.com/WordPress/gutenberg/pull/19775 is merged, so this is unblocked.

**Comment by annezazu** [comment]
Coming back to this four years on and I _think_ what was being asked for here has been implemented where the "create page" option is given priority:

![Screenshot 2024-09-05 at 8 56 08 PM](https://github.com/user-attachments/assets/5822c074-f677-4062-bc14-25f44ca99c7c)

As a result, I'm going to close this out but happy to reopen if I missed something here!
