### ISSUE TITLE
Add "Vertical" block style to buttons block

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20081]
**Is your feature request related to a problem? Please describe.**
Currently the default styles of buttons blocks results in its 
containing button blocks being aligned horizontally.
This can be annoying if existing, singular button blocks (from a time where Gutenberg hadn't used a wrapper buttons block when a button block is inserted) are [transformed to be wrapped by a buttons block](https://github.com/WordPress/gutenberg/issues/19919#issuecomment-583182682), because singular button blocks on each line would suddenly put on a single line in the containing buttons block.

It would therefore make sense to either add a "Vertical" core block style for the buttons block or style the buttons block default styles to vertically aligned button blocks right away.

**Describe the solution you'd like**
"Vertical" block style for buttons block -or-
Default blocks styles align its containing button blocks vertically, one on each line.

**Describe alternatives you've considered**
The alternative would be to add such a "vertical" buttons block style by plugin/theme or re-styling the default buttons block style by plugin/theme, or adding some inline styles. This can be a hassle for users that migrate singular button blocks to wrapped button blocks in buttons blocks.

**Comment by Ringish** [comment]
Been looking into this. Is this expected behaviour?

![Skärminspelning 2020-02-10 kl  17 03 58](https://user-images.githubusercontent.com/3396172/74166986-d0477180-4c27-11ea-8fb9-3588e1562702.gif)

**Comment by strarsis** [comment]
@Ringish: This is nice. Though shouldn't this be an exclusive toggle between horizontal and vertical alignment as there must be one and only one of these two selected?
A theme could then provide block styles for `buttons` block for horizontal and vertical.
The alternative would be providing two core block styles for `buttons` block.

**Comment by nfmohit-wpmudev** [comment]
Hi! 👋

I just submitted a PR that tries to address this request.

Thanks! ❤️
