### ISSUE TITLE
Social Block: Out of place vertical black line

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20086]
I will call this a bug report as this looks like a bug (even though I know it is supposed to be this way):

<img width="553" alt="Screen Shot 2020-02-07 at 08 09 25" src="https://user-images.githubusercontent.com/5323259/74008678-c1d82c00-4981-11ea-9a8a-4cf84e6cd0c5.png">

Looking at the above the black vertical line looks out of place. I removed it so we can compare.

![Social-Block-no-black-line-Gutenberg](https://user-images.githubusercontent.com/5323259/74009143-dff25c00-4982-11ea-9412-a16f0c2d9651.jpg)

The interface will be getting a makeover with G2: https://github.com/WordPress/gutenberg/issues/18667

In the mean time I am not sure what to do with this issue.

@mkaz @jasmussen @mcsf @mapk

**Comment by jasmussen** [comment]
I agree it looks out of line, but I also think this will be fixed with #18667, and there aren't any bandaids in the mean time. I'm working hard on getting the G2 branch in a good state, so that it can hopefully prove itself worthy of merge not too long after the 5.4 release.

**Comment by paaljoachim** [comment]
I will just go ahead and close this as this will not be a concern in the new toolbar being worked on.
