### ISSUE TITLE
Some pasted content crashes editor

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2008]
## Steps to Reproduce

1. Copy a couple paragraphs of text from http://lipsum.com/feed/html
2. Paste into a new Gutenberg > New Post post text block

## Expected Behavior

Content is pasted.

## Current Behavior

Editor crashes.

[`Uncaught TypeError: text.replace is not a function`](https://github.com/WordPress/WordPress/blob/de31d6f/wp-admin/js/editor.js#L317)

(Note this is a core file, but the same error does not occur in the current post editor)

## Possible Solution

It's not yet clear to me whether there are hidden characters in the text that are causing issues. Pasting it into a plain text editor, then re-copying, then pasting into editor works as expected.

**Comment by nb** [comment]
I hit this one, too – `text` is an array of React elements, instead of the expected string.
