### ISSUE TITLE
Latest posts: consider to don't list the post where the block is used

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2009]
When inserting a "Latest posts" block in a post, it displays also the "host" post if it's recent enough:

![screen shot 2017-07-25 at 20 18 11](https://user-images.githubusercontent.com/1682452/28592531-99199934-7189-11e7-822e-b226f6c56615.png)

This doesn't seem particularly useful. While the classic Recent Posts widget is typically used in a sidebar and thus it's correct it displays all the recent posts, the Latest Posts block (aside: why it has a different name: Recent vs. Latest?) is used in the post content and should exclude the "host" post when this is in the recent ones.

Additionally, when inserting the Latest Posts block in Gutenberg:
- create a new post
- don't save the post yet
- insert a Latest Posts block
- the "host" post is not included (because it's still a draft):

![screen shot 2017-07-25 at 20 19 02](https://user-images.githubusercontent.com/1682452/28592747-4bc04092-718a-11e7-9271-979273b3bd94.png)

- save
- refresh the page
- now the host posts is listed

This mix of different behaviors can be confusing for users and should probably be improved a bit.

**Comment by youknowriad** [comment]
If we were to add this feature, we should consider the fact that this block could be used in a page or a site builder later (the same block) and there's no post host.

**Comment by nylen** [comment]
I think the way forward here is to support some or all of the REST API's query parameters and automatically include `?exclude=ID` for the current post ID.

**Comment by westonruter** [comment]
> I think the way forward here is to support some or all of the REST API's query parameters

See comments around https://github.com/WordPress/gutenberg/issues/1594#issuecomment-312921231

**Comment by jasmussen** [comment]
To me this sounds like a perfect toggle to have in Block Settings.

Something like:

```
Omit most recent post       [ on/off ]
```

?

**Comment by karmatosed** [comment]
Let's close this one for now. It could be something we add later but that would be after phase one. It may also be something people extend.
