### ISSUE TITLE
Title attribute should not be a recommended field in Navigation Block

### ISSUE THREAD

**Issue by joedolson** [WordPress/gutenberg#20104]
**Describe the bug**
The navigation block places the 'title' attribute field in a highly prominent position under SEO settings & pre-populates the field. (See #20102 for autopopulating behavior).  The title attribute is a field that should be avoided for accessibility reasons, per decisions made throughout WordPress core. The field has been hidden by default in the menus screen since WordPress 4.4, and those decisions should remain in place in Gutenberg.

The attribute should be moved to the Advanced settings and the text describing its purpose should be removed, to avoid the implication that this setting is desirable to complete. In Advanced settings it will be hidden by default, which is an acceptable equivalence to the current menu screen. (The field can currently be enabled from Screen Options.)

**To reproduce**

Create a navigation block. Activate 'Create from all top-level pages'.  All created links have a pre-filled title attribute, prominently available in SEO settings.

**Expected behavior**
The field should not be pre-filled and should not be visible.

**Additional context**
 Gutenberg 7.4

**Comment by jeryj** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/19990
