### ISSUE TITLE
Latest posts: Notice: Undefined index: `$attributes['layout']`

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2010]
I'm getting a PHP notice in the admin for a post that contains a Latest Posts Block:
`Notice: Undefined index: layout in / ... /gutenberg/lib/blocks/latest-posts.php on line 74`

seems to me introduced in https://github.com/WordPress/gutenberg/commit/8580da527d056ad89f2ce17e7a14511feec7c153 where before checking for `if ( 'grid' === $attributes['layout'] )` is probably necessary to check for `isset()`.

**Comment by westonruter** [comment]
This is something else that would be unnecessary if we shared schema defaults between the client and server: #1905.
