### ISSUE TITLE
Navigation block should not autopopulate title attribute

### ISSUE THREAD

**Issue by joedolson** [WordPress/gutenberg#20102]
**Describe the bug**
The navigation block autopopulates the menu item 'title' attribute using the link text. This behavior was eliminated from WordPress in version 4.4, and those decisions should be retained in Gutenberg.

**To reproduce**

Create a navigation block. Activate 'Create from all top-level pages'.  All created links have a pre-filled title attribute.

**Expected behavior**
No links should have title attributes.

**Additional context**
 Gutenberg 7.4

**Comment by jeryj** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/19990
