### ISSUE TITLE
Block width issue when search for a block on small device 

### ISSUE THREAD

**Issue by akkspros** [WordPress/gutenberg#20115]
**Describe the bug**
Block width issue when search for a block on small device 

**Screenshots**
![gutenberg](https://user-images.githubusercontent.com/56331609/74085727-ef19fc80-4a9d-11ea-8db3-db1afdfa35ab.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 2 
 - Browser: chrome
 - Version 5.3.2

**Comment by jorgefilipecosta** [comment]
Hi @akkspros, thank you for reporting this issue.
The screen size of the Nokia 2 appears to be 720 x 1280 pixels and when testing in this screen resolution I'm not able to replicate the issue.
Maybe the problem only happens on real devices.
Could you provide additional information:
- The version of chrome used to test.
- DO you have Gutenberg installed if yes what version?


Thank you in advance for any additional information you could provide.

**Comment by akkspros** [comment]
@jorgefilipecosta 

![Screenshot_20200209-134543](https://user-images.githubusercontent.com/56331609/74099226-18409880-4b43-11ea-9492-1756dad97dc5.png)

WordPress Version 5.3.2
Gutenberg Version 7.4.0

**Comment by jorgefilipecosta** [comment]
Hi @akkspros, if the Gutenberg plugin is disabled the issue still happens?

**Comment by karmatosed** [comment]
I tried to replicate this and wasn't able to using an emulator. Now, this might be the issue that using an emulator isn't getting the issue. In this case, if you are still experiencing this can you please report back. For now, I am closing this as we do need a little more information. It can always be reopened.
