### ISSUE TITLE
When updating beyond 7.1.0 editor font color changes to black and font style changes as well.

### ISSUE THREAD

**Issue by itchaboy** [WordPress/gutenberg#20114]
When I update to any gutenberg version beyonce 7.1.0 my editor changes font colors and styles, it becomes very hard to see as my websites background is a dark blue.

To be clear, on my actual website the articles appear just fine, exactly how they should be, white font, correct styling and formatting.

I am unable to update beyond 7.1.0 as it is impossible to edit properly.

**Comment by jorgefilipecosta** [comment]
Hi @itchaboy, thank you for reporting this issue. Would it be possible to provide additional details:
What theme you are using?
Do you have any plugins installed that may interact with the editor?
If you feel comfortable using browser development tools would you be able to inspect a paragraph in the editor and verify what CSS rule is overwriting the color the paragraph should normally have?
What browser you are using?


Thank you in advance for any additional information you may be able to provide.

**Comment by itchaboy** [comment]
Theme: Astra - v.2.2.1
Browser: Chrome - Latest Public

I used to have a couple of plugins like Elementor's Gutenburg Add-ons but I iuninstalled them afterward the first gutneburg update messed up. Hasn't made any difference.

I do have other plugins, would you want me to list them all? None seem to be directly involved with gutenburg but may be influencing it, I can't say.

Can't say I'd know what to look for in the development tools, I'd need some instruction on that one.

**Comment by karmatosed** [comment]
@itchaboy are you still getting this issue?

**Comment by itchaboy** [comment]
I have tried various builds since 7.1.0 but to no avail. I haven't tried the latest 8.0.0 so I will do a backup and give that a shot.

**Comment by itchaboy** [comment]
So the issue has improved but various things are still odd.

- H3 and H4 titles are still black but H2 titles have correct colors. When manually changing the H3/4/5 titles to a color they change, but upon clearing the color they return to black.
- Paragraph text is the correct color now, it was also black before.

**Comment by karmatosed** [comment]
@itchaboy could you try using a default theme just as a test as I am unable to replicate.

**Comment by youknowriad** [comment]
I believe this was due to the custom color palettes not loaded on the editor (and not enforced). I think it should be fixed now.
