### ISSUE TITLE
Let user insert non-breaking spaces

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2011]
## Issue Overview

In current version of Gutenberg (0.5.0), I can’t insert non breaking space using the standard macOS keyboard shortcut.

## Steps to Reproduce (for bugs)

1. Insert a non-breaking space with ⌥space
2. A standard space is added instead of non-breaking.

I’m using latest final versions of macOS (10.12.6) and Safari (10.1.1).

## Expected Behavior

Gutenberg should let me insert non-breaking space, like the standard WordPress editor does (at least in HTML mode).

## Current Behavior

Gutenberg inserts standard breaking space instead.

**Comment by nicolinuxfr** [comment]
Same behavior with 0.6.0.

**Comment by karmatosed** [comment]
I am not sure you are able to do this now or if you can still in the usual editor. Can you try without Gutenberg activated, to compare?

**Comment by karmatosed** [comment]
I am going to close this, if we get some feedback we can reopen.

**Comment by tybor** [comment]
I can somehow confirm this bug on Linux (CentOS). 
Neither the classic editor nor Gutenberg allow to insert a non-breaking space using the keyboard shortcut offered by the operative system (on Linux it's Ctrl-Shift-Space). 
Yet, while pasting from LibreOffice a text into classic editor retain the non breaking spaces doing the same in Gutenberg translate them into plain spaces. 
Manually inserted &nbsp; are converted into plain spaces too in both editors.

**Comment by Nate-Wessel** [comment]
Is there a workaround for this? What is the easiest way to insert a non-breaking space? Is it possible without going into the HTML editor?
