### ISSUE TITLE
Gutenberg inspector contols seem totally ipossible to track for validation

### ISSUE THREAD

**Issue by abursill** [WordPress/gutenberg#20127]
Gutenberg Inspector controls for items like page attributes are totally impossible to track or validate because they have no static ID''s .

I just wrote some code to try to validate the input of the page template field and the parent page, but because the inspector select control ids change every time you try to add a block it is impossible.

The template page select id started as document.getElementById("inspector-select-control-1" when I tried to add a block and went back to it. It has now changed to document.getElementById("inspector-select-control-2" but if I add no blocks it stays as control-1

How are any of us developers supposed to work with this, when select input ids get changed dynamically to the same as existing id's when the page first loads?

**Comment by draganescu** [comment]
hi @abursill! Did you try to check and validate the data that these controls manipulate instead? I see that the page template selector sets a `template` state in the `'core/editor'` store:

```
onUpdate( templateSlug ) {
	dispatch( 'core/editor' ).editPost( {
		template: templateSlug || '',
	} );
},
```

You can get this state using the selector `getEditedPostAttribute( 'template' )` from the `'core/editor'` store and validate that.

Would that work for you? This could be a better solution since accessing items in the dom should be a last resort approach in a React app.

**Comment by youknowriad** [comment]
DOM nodes are not considered valid APIs, you should try to check their value by accessing the DOM element, instead, consider using the data modules to retrieve the post data like suggested by Andrei. Thanks.

**Comment by abursill** [comment]
@andrei thank you I shall have a look! @Riad so you are basically trying to tell me I am wrong and that a DOM form element for the input for something like a comment should not have id="commentr or name="comment and should be randomly renamed at every mouse click?. Being forced to make an XMLHttpRequest every time you need to check the current state or value of something, that should not have changed is not good. If everything was properly thought out everything would have an id and or name. Gutenberg and Wordpress go perfectly together as they are both poorly documented.

**Comment by youknowriad** [comment]
No, that's not what I'm trying to tell you.

I'm trying to tell you that you shouldn't consider access to DOM directly as a WordPress API. It is true that HTML form elements have ids that should to allow for labels to target fields but there's nothing in the HTML spec that says the id can't change. In fact HTML says that the id should be unique and these components are generic in Gutenberg which means they can be shown multiple times in the same page, so changing them on each render could be seen as a good thing.

What I'm telling you too is that if you want to access this data, you shouldn't call any Rest API bust use the official API (called data module), gutenberg provides if you want to access any data on the page.

For example, getting the template is done using:

```
wp.data.select('core/editor').getEditedPostAttribute( 'template' )
```
