### ISSUE TITLE
UI/UX: Convert HeadingToolbar to ButtonGroup

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#20126]
In order to bring more consistency across controls, as originally discussed in #19904, let's consider employing the `ButtonGroup` control, instead of a one-off `HeadingToolbar` component we're currently using, within the Heading block. 

**Here's what we currently have:** 
![toolbar-1](https://user-images.githubusercontent.com/1813435/74107630-5f249300-4b2f-11ea-8fca-55ec735c79be.jpg)

**Here's what it would look like, as a `ButtonGroup`:** 
![toolbar-2](https://user-images.githubusercontent.com/1813435/74107608-2edcf480-4b2f-11ea-957b-269db1cba2f5.jpg)

**Comment by kevIN-kovaDIA** [comment]
oh yes, looks better.

**Comment by kevIN-kovaDIA** [comment]
just an idea, Can we use adjust height H1 icon as same font size and so on as shown in attached image.
![WP](https://user-images.githubusercontent.com/38972017/74126539-34edd680-4bfe-11ea-88c9-9887eeeb2c9f.png)

can this increase visual appeal?

**Comment by shaunandrews** [comment]
I wonder if we need to have this option in both the sidebar and the toolbar? It seems with the toolbar we could add all the options and just get rid of the sidebar options.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/191598/74162749-4a0f3900-4bef-11ea-9206-25e6d4ded01f.png">

--

Looking towards the new block UI, I think we could basically take the sidebar component and use in a popover:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/191598/74163190-0537d200-4bf0-11ea-93f6-1d954f75422d.png">

**Comment by richtabor** [comment]
> I wonder if we need to have this option in both the sidebar and the toolbar?

That's an interesting proposition. I'm down for decluttering for sure.

I'm curious if we could get some user testing around this, to see if users understand that they can change the heading level via the toolbar `H{level}` label, or they need to see the label/array of sizes first (like within the sidebar).

**Comment by karmatosed** [comment]
I think moving to the toolbar as @shaunandrews suggests make a bit more sense visually and also brings in the iterated UI. 

As far as user experience goes,  I do think in the sidebar there is even more invisibility than being in the toolbar.

**Comment by paaljoachim** [comment]
I will also mention this PR: https://github.com/WordPress/gutenberg/pull/20246

**Comment by mapk** [comment]
After [today's design team triage in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1589905107367200), it was decided to close this issue due to the above mentioned PR. Once the controls get merged into the block toolbar, it would be a good idea to create a new PR that removes these controls from the sidebar. That makes this issue obsolete.
