### ISSUE TITLE
Has there been a major CSS change?

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#20121]
Hey!

I've noticed a lot of things look very different when using the latest version of Gutenberg, including a lot of third party plugins (including our own), as well as placeholder components of Gutenberg, like here's how the Column block looks:

<img width="1213" alt="Screen Shot 2020-02-09 at 3 44 31 PM" src="https://user-images.githubusercontent.com/2649903/74100285-11ba1d00-4b53-11ea-8338-2658fa462f2e.png">

Has there been a change in styles in the latest version or is this a bug which broke some of the styles?

**Comment by jorgefilipecosta** [comment]
Hi @HardeepAsrani, yes Gutenberg brings a considerable amount of design changes. The design of the columns block shared on the screenshot seems to be the expected one.

> I've noticed a lot of things look very different when using the latest version of Gutenberg, including a lot of third party plugins (including our own)

Is there anything on these changes that affected third party blocks that you consider "broken"/unexpected or it is just a different design?

Thank you in advance for any information you may provide!

**Comment by HardeepAsrani** [comment]
Hi @jorgefilipecosta,

Anything with uses a Placeholder complement or Button component so far. You can do a fresh install of gutenberg from WPorg or build from GitHub to see the issue.

**Comment by HardeepAsrani** [comment]
Were you able to reproduce this @jorgefilipecosta?

**Comment by youknowriad** [comment]
@HardeepAsrani What is the issue for you? That screenshot is correct, there's no issue there? and yes the design of Placeholder and Button component changed. https://make.wordpress.org/core/2020/02/13/an-updated-button-component-in-wordpress-5-4/

**Comment by HardeepAsrani** [comment]
Yes, that was the question. Thanks for the clarification. :)
