### ISSUE TITLE
Export server-side date format for use in JS by Moment.js

### ISSUE THREAD

**Issue by westonruter** [WordPress/gutenberg#2013]
See https://github.com/WordPress/gutenberg/pull/1992#issuecomment-317657482

> It'd be nice to use `_wpDateSettings.formats.date` but PHP and moment.js tokens don't match.

So part of this would be a JS finction to convert the PHP `date()` format into the Moment.js format.

This is needed by both the Latest Posts block and the Latest Comments block.

**Comment by youknowriad** [comment]
I think the `date` module already providers utilities to do this.
