### ISSUE TITLE
Format Library: Inline link formatting popover can stretch beyond viewport

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20146]
Previously: https://github.com/WordPress/gutenberg/pull/20052#pullrequestreview-355890018, https://github.com/WordPress/gutenberg/pull/20052#issuecomment-583537869

**Describe the bug**

When editing a paragraph link on a narrow viewport, the popover may stretch beyond the edges of the screen.

<img width="341" alt="Screenshot 2020-02-10 at 14 02 10" src="https://user-images.githubusercontent.com/107534/74148972-51ded580-4c0f-11ea-897b-8a230169c6f3.png">

<img width="380" alt="Screenshot 2020-02-10 at 14 00 11" src="https://user-images.githubusercontent.com/107534/74148976-53100280-4c0f-11ea-987f-6d4e717a2eb7.png">

**To reproduce**

1. (Prerequisite) Shrink screen (manually or via [emulation](https://developers.google.com/web/tools/chrome-devtools/device-mode)) or use mobile device
2. Navigate to Posts > Add New
3. Insert a paragraph
4. Click in the block toolbar to insert a link
5. Note that link editor may stretch beyond the screen edges.

**Expected behavior**

Link editor shows within the constraints of the viewport.

**Additional context**

For solution:

- Consider how this behaved previously.
- See if there are fixed or minimum widths in any of the relevant components that may be the cause of this issue (LinkInlineUI, LinkControl, URLInput)
- Consider centering the popover on small devices, rather than opening to the right.

**Comment by aduth** [comment]
> * Consider centering the popover on small devices, rather than opening to the right.

It is implemented this way already:

https://github.com/WordPress/gutenberg/blob/38f4914149bc6fecbeb45e86ed29b2c101ca65fc/packages/format-library/src/link/inline.js#L168

If I recall correctly, the `Popover` component will adjust to the left or to the right if there is not enough natural space in its default preferred position. Thus, I expect that the issue is that the Popover itself is wider than the viewport in the examples given.

Possible solutions could include:

- Reduce or eliminate padding in the popover
- Set a smaller input width or otherwise allow it to shrink for smaller viewports

**Comment by aduth** [comment]
Possible implementation idea, from https://github.com/WordPress/gutenberg/pull/20154#issuecomment-591024640 :

>With regards to the discussion here about the tooltip's overflow mechanics, I think it might be worth considering to pull in [Popper](https://popper.js.org/) to replace our implementation. I've been a bit resistant to it when brought up previously, in part because our custom implementation has been mostly sufficient for our purposes, and we don't need all of what the library brings with it (i.e. avoid inflating bundle size).
>
>Notably, it does quite well in this regards of "pushing away" from the bounds of a container:
>
>![push-away](https://user-images.githubusercontent.com/1779930/75279680-fcdbbb80-57d9-11ea-85ca-5d9aafd4ca5f.gif)
>
>https://popper.js.org/docs/v2/modifiers/arrow/

**Comment by talldan** [comment]
This is now fixed 🎉
