### ISSUE TITLE
Block Library: Social Links: Translated label string should use placeholder

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20152]
Previously: https://github.com/WordPress/gutenberg/pull/18651#discussion_r377275288

The following string may be difficult to translate:

https://github.com/WordPress/gutenberg/blob/9ac8c66ebc1f0a927093b3b1f27919ac6b3571c7/packages/block-library/src/social-link/index.php#L18

1. Translators will only be provided the string "Link to " without contextual clues to know that it is being used in a concatenation.
2. Some translations may require that the position of the placeholder be changed relative to the rest of the sentence.
3. Even with a placeholder, this sort of string can still be problematic where the translation may vary depending on e.g. the gender of the noun of the placeholder value. In this case, I don't believe that should be a problem, given that the values to be substituted are proper names of companies / services.

**Task:**

- Confirm whether the last of these is correct to assume as a non-problem.
- Update the string to use a placeholder.
- Consider including a [translator comment](https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions) to explain substituted values.

**Comment by mcsf** [comment]
Thanks for catching this, I definitely think it should be fixed.
