### ISSUE TITLE
Add automated tests for resizable editor functionality

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#20159]
**Is your feature request related to a problem? Please describe.**
 The resizable editor work from PR https://github.com/WordPress/gutenberg/pull/19082 needs some form of automated testing. 

**Describe the solution you'd like**
Ideally we should add e2e tests as discussed in [this thread](https://github.com/WordPress/gutenberg/pull/19082#discussion_r375735554) and perhaps unit tests for some of the helper functions.

**Describe alternatives you've considered**
See thread linked to above.

**Comment by Thelmachido** [comment]
@tellthemachines  there hasn't been much movement on this since 2022. I will close this for now, please feel free to circle back and reopen the issue.
