### ISSUE TITLE
Include Categories in Nav Block link creation UI search results

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#20165]
In the original designs for the new link UI in the Nav Block, @shaunandrews included `Categories` in the search results. This was descoped to allow teams to focus on returning `Pages` (the primary use case).

This Issue documents the originally suggested featured for posterity. It may well be that this isn't deemed desirable, but it helps to have a record.

**Describe the solution you'd like**
(If desired) When searching for an existing entity in the Link UI within the Nav Block, the results should include not only `Pages` but also WordPress `Categories`.

Note that currently, the Nav Block returns only `Pages` from the [Core REST API `search` endpoint](https://developer.wordpress.org/rest-api/reference/search-results/).

However, adding this feature doesn't _necessarily_ require customising [the Search endpoint in Core](https://github.com/WordPress/WordPress/blob/67104bb3f4b992f458d5e4189d8ceb2fa9b4a440/wp-includes/rest-api/search/class-wp-rest-post-search-handler.php#L52).

We could also explore the idea of [adding another query into the `__experimentalFetchLinkSuggestions` within Gutenberg](https://github.com/WordPress/gutenberg/blob/03e034fea925afd1cd359de4e2713ebde92ce2dc/packages/editor/src/components/provider/index.js#L30) and then combining the results before returning them to the Editor data store.

**Describe alternatives you've considered**
Not including Categories at all. It might be too much and very much a secondary use case.

**Comment by karmatosed** [comment]
This feels like it needs to move to development so I'm going to do that. Unless I am mistaken the idea would be to just show categories as results, no design needed.
