### ISSUE TITLE
Navigation block - submenu arrows don't follow the color of menu in the editor

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#20174]
**Describe the bug**
Try to create a contrast using a different color than black on the menu items color while using Gutenberg 7.4.0.

**To reproduce**
1. Create a block navigation menu
2. Select beige as the navigation menu color and red/etc for the background.
3. Enable the "Show submenu icon for top-level items" to view the arrows
4. The arrow on submenu elements remains black.

**Expected behavior**
To follow the color of the menu item/

**Screenshots**
<img width="732" alt="menu" src="https://user-images.githubusercontent.com/6737345/74276842-2a772e00-4d1f-11ea-95ce-4681befd8b41.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 10.15.3 / 80

**Comment by Ringish** [comment]
This seems to be fixed when I run the latest version of master?

**Comment by karmatosed** [comment]
I am going to. close this as seems resolved, if it isn't we can always reopen.

![image](https://user-images.githubusercontent.com/253067/77457663-e46cba00-6df4-11ea-8544-45fc57154f35.png)
