### ISSUE TITLE
Schedule Button and Publish Button

### ISSUE THREAD

**Issue by benlumia007** [WordPress/gutenberg#20173]
is it normal that sometimes when creating a new post or page, I see the schedule button instead of publish button, and sometimes it just goes back and forth?

was there a release that may cause this problem. I don't' know if I would put this in help request or a bug request so. 

I'm on wordpress 5.3.2, and i have disabled and enabled the gutenberg plugin, same thing. 

please point me to the correct destination if there is :D

**Comment by danielbachhuber** [comment]
I'm seeing this quite often too.

Something interesting though: I literally saw "Schedule...", switched to a different tab, switched back to my editor, and the button changed back to "Publish...".

**Comment by paaljoachim** [comment]
Is this issue still valid?
@retrofox Damian might have some input here.

**Comment by ghost** [comment]
oh wow, this is still open! :)

**Comment by retrofox** [comment]
HI, there. I can take a look at it these days. :-)

**Comment by ndiego** [comment]
This issue was reviewed in the weekly Editor Bug Scrub and 3 testers were unable to reproduce in the latest version of WordPress and Gutenberg. Therefore, I am closing but if someone is able to reproduce, feel free to reopen.
