### ISSUE TITLE
Link editor styles ignored

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#20179]
**Describe the bug**
I enabled editor styles via `add_theme_support` and have the following in my `editor-styles.css` file:

```
a {
    color: #999999;
}

a:hover,
a:focus {
    color: #bbbbbb;
}
```

But, unlike the body and heading (h1, h2, h3, h4, h5, h6) styles defined in `editor-styles.css`, the link styles are not rewritten using the `editor-styles-wrapper` class in the Gutenberg editor and the block editor picks the link colors defined by default.
Is this by design? Is this the expected behavior?

I'm using the block editor version that comes with WP 5.3.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 72

**Comment by paaljoachim** [comment]
Hi @mrleemon 

Thank you for creating this issue!
Is it still valid?
Thanks.

**Comment by mrleemon** [comment]
No, you can close the issue.
Now, the version of Gutenberg found in WP 5.6 picks the link styles from the `editor-styles.css` file correctly.
Thanks!
