### ISSUE TITLE
Discussion: Expand JavaScript coding standards

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2017]
There's been talk about how Gutenberg is following the WordPress coding standards (https://codex.wordpress.org/WordPress_Coding_Standards), and how we are slowly adding to those standards with the new toolchain used for building Gutenberg.

It would be good to discuss and perhaps document what additions and/or changes we are making to the coding standards, so that these can be proposed for being added to the official guidelines. For example there's still some inconsistency in how deeply we nest SCSS classes, and how we label variables (http://getbem.com/introduction/). Some of those standards are from the Calypso standards: https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md

CC: @melchoyce as we discussed this.

**Comment by mtias** [comment]
Going to close as this is not very actionable here, and is already part of broader discussions.
