### ISSUE TITLE
Wide width has no effect

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#20188]
**Describe the bug**
Setting wide or full width on the cover or group block has no effect. 

**To reproduce**
1. In a new post
2. Insert a group block
3. Insert an image
4. Select the group block
5. From the block toolbar set witdth to full or wide
6. Observer bug

**Expected behavior**
Full or wide to work.

**Screenshots**

![no-wide-width](https://user-images.githubusercontent.com/107534/74339698-46c1ac00-4dad-11ea-96d2-a353ad481c0f.gif)

**Desktop (please complete the following information):**
 - OS: osx
 - Browser Firefox

**Comment by youknowriad** [comment]
this is probably a theme bug. What theme are you using? Is it one without Gutenberg editor styles support?

**Comment by draganescu** [comment]
I tested with both TwentyTwenty and Gutenberg starter theme. I also tested on current wordpress-develop and there the bug only manifests on the Group block, however the Cover block still works.

**Comment by draganescu** [comment]
Apparently I had some different node versions on my system and somehow a messed up build because of that. Now everything looks good, so will close this.
