### ISSUE TITLE
[i18n] Strings missing capitalization and inconsistent

### ISSUE THREAD

**Issue by pedro-mendonca** [WordPress/gutenberg#20186]
**Describe the bug**
Many action button strings miss capitalization, as used in WP core.
Some could benefit of merging with already existent strings.

![imagem](https://user-images.githubusercontent.com/7371591/74332595-00108980-4d8e-11ea-9798-a9b5d77794ad.png)

![imagem](https://user-images.githubusercontent.com/7371591/74332636-11f22c80-4d8e-11ea-9f5e-8438ed850f04.png)

**Comment by aduth** [comment]
Based on https://github.com/WordPress/gutenberg/pull/20187#issuecomment-590960935, it may be that this is not possible or desirable at this time. If so, the issue should be closed. But I would appreciate confirmation about this.

**Comment by pedro-mendonca** [comment]
Thank you @aduth 
I understand the guidelines in https://developer.wordpress.org/block-editor/contributors/document/copy-guide/#five-pay-attention-to-capitalization

Hopefuly this kind of decisions should happend in WP core and later propagate to each project, and not otherwise.
Still, it's great to see the issue discussed and decided with guidelines :)

I hope this will get consistent in a near future, between core and Gutenberg.

I'll close the issue.
Thanks!
