### ISSUE TITLE
Bring colors by the block for some blocks

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20197]
This has been explored in navigation and other blocks, I would like to open the discussion on bringing colors by the block for all blocks. By unifying their place we can start on a path that could see styling out of the sidebar completely.

## The problem
Look at how far away and lonely the color options are:

![image](https://user-images.githubusercontent.com/253067/74364659-76c87980-4dc4-11ea-9464-1857f994b139.png)

I joke a little, however it is a weird experience having to have the sidebar option for this. Shouldn't all these just work right by the block itself?

## Existing solutions
I am going to first link what was explored in columns #16660 and similarly in navigation.

<img width="730" alt="1" src="https://user-images.githubusercontent.com/253067/74364171-e8ec8e80-4dc3-11ea-9bbc-5c3f0f22b6e7.png">

This is a pretty intense UI and just more or less puts what we have in the sidebar into a drop-down. This is a different space, so that could be iterated leaning on new styling coming in.

## Moving into new exploring
I have been doing some thinking around this and how we could perhaps simplify. I came to an iteration feels still forming, but maybe good to share. This isn't meant to be a final design as much as a feedback discussion starter.

<img width="730" alt="v2" src="https://user-images.githubusercontent.com/253067/74364218-06b9f380-4dc4-11ea-973f-65398f2e30b9.png">

A picker would either drop-in/down/or appear, that's not set yet but this does simplify. It could also show more than just theme colours, but there is more space with this tab.

Maybe it also looks like this on hover:

<img width="730" alt="3" src="https://user-images.githubusercontent.com/253067/74364281-28b37600-4dc4-11ea-9e87-91877bf4a270.png">

There is some work on iterating the color picker so wanted to note that here as I am in this looking to align #19785.

The more I explored this, the stronger I felt moving other options from the sidebar is worth exploring (more to come on that later). If we start though, colors feel like a great starting point.

I will add that unexplored here is what it looks like with both colors 'on'. I will do that in later iterations should we decide this is a great route. My thinking is the circle could show both colors, however, this needs exploring.

## Next steps

I would love some feedback around:

- Is this worth exploring more as a tabbed interface?
- Is this a good idea to move from the sidebar to by all blocks in the toolbar?

**Comment by mtias** [comment]
This has to be intentional based on the role they play for the block and should not be generalized. In the case of a **Paragraph** block it should not be considered a primary interaction. For a **Cover** block, on the other hand, it should be easy to access from the toolbar.

Another case in point: the cover block shows colors in the placeholder while paragraph does not.

**Comment by karmatosed** [comment]
Thanks for feedback @mtias. Happy to be wrong about paragraph block. My personal feeling was moving more styling closer to where it happens helps context. As a ponder, how do you feel about a styling section by the block to include over clutter with more options there? Just putting this out there as an idea.

![image](https://user-images.githubusercontent.com/253067/74365648-69ac8a00-4dc6-11ea-9585-cbca48cdad7e.png)

For me, the sidebar is a place this is lost and whilst it might not be a primary action I do feel it's a handy thing to have by the block. I keep coming back to having consistent styling in one place could be a benefit. Happy to explore where that could be a wrong turn though.

Let me list where this then could happen to be sure that has some clarity:

- Columns block
- Cover block
- Navigation (?)

I put a '?' beside navigation as unsure if this now falls into the division between primary and secondary.

**Comment by karmatosed** [comment]
As a possible iteration even in sidebar this could be explored:

<img width="1191" alt="Frame 14" src="https://user-images.githubusercontent.com/253067/74367686-31a74600-4dca-11ea-835c-64f9b0b5521b.png">

Very rough mock to show how even if in a different place we could maybe follow a more distilled interface.

**Comment by karmatosed** [comment]
Totally agreeing it gets tricky. I'll explore a little more on that then.

**Comment by karmatosed** [comment]
Noting changed the title to be 'some blocks' so we can collate and work through a list where the right ones for this are.

**Comment by richtabor** [comment]
> This has to be intentional based on the role they play for the block and should not be generalized. In the case of a **Paragraph** block it should not be considered a primary interaction. For a **Cover** block, on the other hand, it should be easy to access from the toolbar.
> 
> Another case in point: the cover block shows colors in the placeholder while paragraph does not.

But at the same time, having different locations for the same controls could be quite jarring to folks - regardless of the selected block. Especially if they're as foundational as changing a design/color.

**Comment by ZebulanStanphill** [comment]
I already opened a similar issue: #20070. Should I close it?

**Comment by shaunandrews** [comment]
> having different locations for the same controls could be quite jarring

Agreed. I can't seem to come up with logical reasons for why color controls exist in one place for one block and a different place for a different block; It seems random. I'd imagine most people will not understand, and just assume that a paragraph block doesn't allow color customization.

**Comment by mtias** [comment]
It depends, as the color tools do different things depending on context. For example, these mockups are placing block color after the rich text controls, which are based on inline selection (they don't affect the _whole_ block at once).

![image](https://user-images.githubusercontent.com/548849/74608129-d5506900-50de-11ea-91dd-2495db6d5e02.png)

And paragraph already has support for inline color in the "more tools" of the toolbar:

![image](https://user-images.githubusercontent.com/548849/74608152-03ce4400-50df-11ea-98c1-088e4243df44.png)

**Comment by ZebulanStanphill** [comment]
@mtias I think the (not-inline) color control should definitely go before the RichText tools, in order to keep with the currently-established pattern of putting the controls that affect the entire block first in the toolbar.

**Comment by mtias** [comment]
Yes, definitely, but that's also why I don't think block color belongs in a paragraph's toolbar, because it gives more prominence to color choices than to rich text tools (bold, italics, etc), which are the most important controls on paragraphs, while making the toolbar as a whole busier. The paragraph block is the most basic text unit we have and should be clear of incidental distractions.

That results in the following clauses for block color:

- Should not be added _after_ Rich Text tools because it applies at the block level.
- Should be avoided at the beginning of the paragraph toolbar because it pushes the most important controls aways.

**Comment by ZebulanStanphill** [comment]
@mtias Good point. I think the Paragraph and Heading blocsk can keep the block-level color controls in the inspector. I do think the block-level color controls belong in the toolbar of other blocks like Group or Columns, though.

(I also think it would be good if we could make the inspector more easily accessible and more clearly attached to the selected block somehow.)

**Comment by nosolosw** [comment]
Somehow related, there's https://github.com/WordPress/gutenberg/issues/22700 to track the progress of adding style controls to the blocks.

**Comment by mtias** [comment]
Let's handle this on a per block basis where it makes sense, like Cover.
