### ISSUE TITLE
Blocks: Contextual tips tied to specific search queries

### ISSUE THREAD

**Issue by davemart-in** [WordPress/gutenberg#20196]
## Problem

Folks who are new to WordPress and Gutenberg start off with a very rudimentary mental model of how WordPress works. Once they are in Gutenberg, it's easy to see how they might assume that all customization of their site can be done within the editor. When people search for terms like:

- CSS
- theme
- plugin
- header
- colors

Not only do we show zero results, but we currently do nothing to point them in the right direction.

## Proposed Solution

Let's use the tips system (which already exists in the inserter and can be made searchable) to contextually suggest alternative sections of WordPress when specific keywords are entered into the block inserter. 

**Preview**

Here's a preview of what that might look like:

![tip](https://user-images.githubusercontent.com/5634774/81076282-7b7b6600-8eb9-11ea-9ea8-3629d223ab62.png)

**Proposed keyword/copy**

- CSS - `You can visit the <a href="/customize.php?autofocus[section]=custom_css" target="_blank">the Customizer</a> to edit the CSS on your site.`
- theme - `You can visit the <a href="/themes.php" target="_blank">theme directory</a> to select a different design for your site.`
- plugin - `You can visit the <a href="/plugin-install.php" target="_blank">plugin directory</a> to install additional plugins.`
- header - `You can visit the <a href="/customize.php?autofocus[section]=title_tagline" target="_blank">the Customizer</a> to edit your logo and site title.`
- colors - `You can visit the <a href="/customize.php?autofocus[section]=colors" target="_blank">the Customizer</a> to edit the colors on your site.`

## Alternatives Considered

**1) Using tips in their current location**

![tip-link-3](https://user-images.githubusercontent.com/5634774/74362299-73b69480-4d96-11ea-96a7-fd2d9f4bc103.png)

I started off by attempting to use tips within their current location, but it felt off. The white space feels a tad excessive. 

2) Replace "no results" with tip

![tip-link-2](https://user-images.githubusercontent.com/5634774/74362307-787b4880-4d96-11ea-9727-4328a0d6783d.png)

The next thing I tried was simply replacing the "No blocks found." text with the tip. I believe this text provides valuable context though, so I moved the tip to the bottom (as seen in the proposed solution above)

**Comment by mtias** [comment]
I like this. A good start would be to compile a list of possible tips, then we can decide if they show only when searching or if they become part of the rotating set.

**Comment by mapk** [comment]
We've also got a list of block-specific tips that we've yet to incorporate into the build.

Related: https://github.com/WordPress/gutenberg/issues/16595

**Comment by shaunandrews** [comment]
Nice. Worth connecting this to #19836 which updates the way the tip is displayed. That said, I like that the tip replaces the "no results" label — it seems more obvious and helpful.

**Comment by davemart-in** [comment]
> A good start would be to compile a list of possible tips, then we can decide if they show only when searching or if they become part of the rotating set.

Here are the first few that I outlined above: 

- **CSS** - You can visit the <a href="/customize.php?autofocus[section]=custom_css" target="_blank">the Customizer</a> to edit the CSS on your site.
- theme - You can visit the <a href="/themes.php" target="_blank">theme directory</a> to select a different design for your site.
- **plugin** - You can visit the <a href="/plugin-install.php" target="_blank">plugin directory</a> to install additional plugins.
- **header** - You can visit the <a href="/customize.php?autofocus[section]=title_tagline" target="_blank">the Customizer</a> to edit your logo and site title.
- **colors** - You can visit the <a href="/customize.php?autofocus[section]=colors" target="_blank">the Customizer</a> to edit your logo and site title.

If anyone else has additional ideas, please share them.

**Comment by paaljoachim** [comment]
This is what it looks like right now when I write css in the block panel inserter.

![Screen Shot 2021-02-02 at 17 11 54](https://user-images.githubusercontent.com/5323259/106628271-e7d6e300-6579-11eb-849b-2fce3f2470ba.png)

I do like the topics suggested for giving additional information.

**Comment by paaljoachim** [comment]
This PR is merged to WordPress.com and should also be copied over to wp.org and Gutenberg.
https://github.com/Automattic/wp-calypso/pull/42038

**Comment by Mamaduka** [comment]
@WordPress/Gutenberg-design, is this still relevant, or can we close it?

**Comment by jasmussen** [comment]
Let's close it. There are some tips in some of the suggested places, and additional tips as they become surfaced, do not require this issue to still be open to address. And if someone else feels otherwise, we can reopen this!
