### ISSUE TITLE
Sidebar: Difficult to drag and select content of input 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#20207]
**Describe the bug**
When you click into an input and drag left, you must stop your drag within the input or else the input focus is lost.

**To reproduce**
1. Add a `Quote` component (any component really)
2. Click on the `Block` tab and open the `Advanced` section
3. Type something in the input
4. Click and hold mouse, drag left to select text in input and release anywhere outside of the input

Notice the focus from the input is "stolen".

**Expected behavior**
If the click started in the input, it should select any of the text right or left (depending on my drag direction) of where I started and where I release.

**Screenshots**
![Image of Yaktocat](https://d.pr/i/GA1LYR.gif)

**Desktop (please complete the following information):**
 - macOs: Catalina (10.15.2)
 - Chrome
 - 79.0.3945.130 (Official Build) (64-bit)

**Additional Information**
Build: master@cf8fa0a13659229ff8651e7ffd8d252ddf225e53

**Comment by jorgefilipecosta** [comment]
Hi @StevenDufresne thank you for reporting this issue, it seems it was solved meanwhile. If you are still able to reproduce the issue on master please leave a comment and we will look further.
