### ISSUE TITLE
Adjusting inline image width in paragraph block causes popover to drift away

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#20204]
**Describe the bug**
Clicking on an inline image within a paragraph block displays a popover to adjust the width of the image. Currently if you use the browser controls in the input field to increase the width of the image, it causes the popover to animate its way off the page.

**To reproduce**
1. Create a paragraph block and fill it with some text.
2. From the toolbar, click the dropdown and select to insert an Inline Image
3. Upload or add an image and insert it
4. Click on the image, and the popover will appear
5. Hover over the input field and use the browser's controls to increase the size of the image (sometimes the issue would only happen for me on decreasing the image size)

**Expected behavior**
The popover to stay where it is and not go wandering off the page 😃

**Screenshots**
![inline-image-in-paragraph-block-issue](https://user-images.githubusercontent.com/14988353/74398158-cb263480-4e6a-11ea-91e1-4df5744129c6.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave version 10.14.6
 - Browser: Chrome (Version 80.0.3987.100)
 - Also confirmed the issue appears in Safari (Version 13.0.5) and Firefox (72.0.2)

**Additional context**
- Tested in Gutenberg v7.3.0, v7.4.0, and v7.5.0
- Issue does not appear for me in WordPress 5.3.2 _without_ the Gutenberg plugin installed.

This issue was found while testing out Gutenberg in WordPress.com, thanks to @guarani for finding it.

**Comment by jorgefilipecosta** [comment]
Hi @andrewserong, thank you for reporting this issue in great detail, it seems to be the same issue as https://github.com/WordPress/gutenberg/issues/19519.
In order to avoid duplicate issues, I'm going to close this issue. https://github.com/WordPress/gutenberg/issues/19519 is part of WordPress 5.4 must-have and should be addressed before WordPress 5.4 is released.

**Comment by andrewserong** [comment]
Thanks @jorgefilipecosta! I thought there might be an existing issue but didn't manage to find that one already reported, thanks for closing this :)
