### ISSUE TITLE
Navigation block: Submenu dropdown hidden behind Cover block overlay

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#20203]
**Describe the bug**
When the Navigation block sits right above the Cover block, the submenu dropdown, when opened, sits behind the Cover block's overlay.

**To reproduce**
1. Add a Navigation block. Fill it out with menu items.
2. Add a Cover block right below it. Make sure it has an overlay.
3. Click to add a submenu item in the Navigaiton block. You may need to add two items.
4. Observe problem.

**Expected behavior**
I expect the submenu items to have a higher z-index than the overlay of the Cover block.

**Screenshots**

![Screen Shot 2020-02-12 at 7 08 39 PM](https://user-images.githubusercontent.com/617986/74398145-839c9b80-4dcb-11ea-9fcc-9ab4d20fef97.png)

**Desktop (please complete the following information):**
 - OS Catalina
 - Firefox 72.0.2
 - Gutenberg 7.5

**Comment by talldan** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/24062
