### ISSUE TITLE
npm -g i @wordpress/dev not working

### ISSUE THREAD

**Issue by azizultex** [WordPress/gutenberg#20216]
Hello, 
I get error whenever trying to install @wordpress/dev What would be new repo? Is it removed? 
```azizultex@Azizuls-MacBook-Pro  ~/www/wp-env-test  npm -g i @wordpress/dev
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wordpress%2fdev - Not found
npm ERR! 404
npm ERR! 404  '@wordpress/dev@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.```

**Comment by mkaz** [comment]
If you are trying to runr the development enviornment try `env` instead of dev. 
`npm install @wordpress/env`

If you are trying to run the dev build use: `npm run dev`

**Comment by talldan** [comment]
@azizultex Is there some documentation that's advising you to run that command? It'd be great if you could link to that so that it can be corrected.

**Comment by azizultex** [comment]
> If you are trying to runr the development enviornment try `env` instead of dev.
> `npm install @wordpress/env`
> 
> If you are trying to run the dev build use: `npm run dev`

Thanks @mkaz This solved my issue.
