### ISSUE TITLE
7.5.0 not mobile friendly

### ISSUE THREAD

**Issue by gladpaws** [WordPress/gutenberg#20227]
**Describe the bug**
Scroll is not possible on mobile devices once the new version is installed. 

**To reproduce**
1. Go to any page
2. Click on 
3. Scroll down to NO OPTION TO SCROLL
4. See error - Pages not working at all

**Expected behavior**
I expect to be able to scroll to see content on the website on a mobile device. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR
 - OS: [e.g. iOS8.1] 13.3.1
 - Browser [e.g. stock browser, safari] Safari
 - Version [e.g. 22] 13

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by glendaviesnz** [comment]
Duplicate of #20214
