### ISSUE TITLE
Every block should have help text

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2023]
Inspire by discussion in https://github.com/WordPress/gutenberg/pull/1343#issuecomment-318033673 and related to https://github.com/WordPress/gutenberg/pull/1924#issuecomment-317969798, now that we have a split "Settings" sidebar with sticky Document and Block tabs, we should ensure that information is shown in the "Blocks" inspector for every single block you select.

If no description or inspector is provided by a block, we should show some text there, such as "This block has no description."

**Comment by octalmage** [comment]
Here's one I wrote to take the date format specified in WordPress and use it to format dates client side. We've used it in a production application for a while now. 

https://github.com/octalmage/phptomoment

**Comment by aduth** [comment]
>If no description or inspector is provided by a block, we should show some text there, such as "This block has no description."

We should consider creating a separate issue for this from merely adding descriptions for more blocks (assuming I understand the intent of this pull request). This is also related to some previous discussion #1100 and effort at #1343.

**Comment by jasmussen** [comment]
Noting that I have a PR that needs a massive rebase here: https://github.com/WordPress/gutenberg/pull/2427 — it virtually addresses this, though. Will look at getting this ship shape today.

**Comment by jasmussen** [comment]
Closing as fixed per the merging of #2427. Additionally I have opened separate tickets for the remaining blocks:

#2831
#2832
#2833
