### ISSUE TITLE
Multiple Update clicks in a row to even leave the editor

### ISSUE THREAD

**Issue by icc365** [WordPress/gutenberg#20249]
**Describe the bug**
It appears the block editor requires the author of a post or page to do multiple Update clicks in a row, The most frustrating part of this is that if I update a post and I go to leave the screen, I get a "Leave Site" popup with message "Changes that you made, may not be saved". This now means I have to risk and leave or once again click the update button. 

**To reproduce**
Not sure how to say to replicate this as it seems to be random/varied on when I see that popup message thinking I did not save or update the post/page. But it happens to be often, even if I click update on the post.

**Expected behavior**
After clicking Update, I should be able to do that just once and be able to leave the editor screen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 80.0.3987.106

**Additional context**
It appears this is how the editor was created to do this. I did come across another issue posting back in 2017 where maddisondesigns reported the poor implementation of multiple save/update clicking required. This issue I am experiencing is reaching my patience as this has been happening for the longest time since I started using the block editor....ready to walk away. Please be aware that I am clicking the update button and randomly it still gives me the popup warning message. Is this how the editor is to function?
![after-saving](https://user-images.githubusercontent.com/54302511/74567373-7ba73d80-4f2a-11ea-9b7a-7677c2134b87.jpg)

**Comment by glendaviesnz** [comment]
When you experience this issue, does the `Update` button change to `Updating ...` and then back to a slightly opaque `Update` indicating changes have saved before you try leaving the page, as below, or does it go back to the brighter blue indicating there are still changes to save?

![update](https://user-images.githubusercontent.com/3629020/74617708-6f71e900-5193-11ea-9d73-18f0d085f42c.gif)

If it goes back to the brighter blue indicating unsaved changes, are there any errors in your browser console when this happens?

**Comment by icc365** [comment]
I noticed that it gets greyed out but it seems as though after a short while, it becomes an active button to be clicked again. Basically the latter, back to the blue. I will have to try and remember to observe how much time goes by before it does that on its own. Does the editor do a self-update on a timed delay even without doing anything in the editor?

**Comment by glendaviesnz** [comment]
> Does the editor do a self-update on a timed delay even without doing anything in the editor?

As far as I am aware the editor Update button should only become active again if the post content or any block attributes have changed - just double checked this by leaving a page open for an hour and Update did not become active again. 

One thing to take note of is which blocks you have in the post when you encounter this problem -  maybe there is a custom block you are using that does some background updating of its attributes that is putting the editor in a dirty state.

**Comment by icc365** [comment]
I will have to watch more carefully as I create content and try to remember to be aware and make notes of what steps I did, how many times I click the Update and if I click or do anything after updating. I'd keep this issue open for a while and then when I get more info, I will update this one.

**Comment by icc365** [comment]
A little update....today, I noticed one thing in relation to this issue...if I have a post open in the editor where I click to update the post. Then, if I go into the code editor and then switch back to the visual editor without touching anything, that requires a click of the update button. I encounter this often (I work in both the code and visual).

**Comment by icc365** [comment]
Another update. I was just creating a post on my site but saved it as a Draft. I went to go elsewhere in my dashboard and then got the popup notice "**Changes that you made may not be saved**". This was right after clicking on S**ave as Draft**. Looks like I have to click that twice too. I think the double-clicking to publish or save as a draft is more quirky than a benefit, not to mention extremely annoying. 

Still, the original item I posted to open this ticket is still not 100% known. I'm still trying to make a note as I create content in the site(s).

**Comment by youknowriad** [comment]
I just tried with several scenarios, this is not happening to me. I think you might have some plugins installed that trigger changes programmatically even if you don't touch the editor causing this behavior. Consider disabling plugins to see if you find the culprit.

I'm going to close this issue for now, if we find ways to reproduce in Gutenberg only, we should reopen it.
