### ISSUE TITLE
Consider to de-enqueue unused script from the Gutenberg page

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2025]
In the Gutenberg page, many scripts that seem not useful in the Gutenberg context, are still enqueued. For example, `wp-link` also produces all the markup necessary for the link modal dialog:

![screen shot 2017-07-26 at 16 55 18](https://user-images.githubusercontent.com/1682452/28628070-d87ce2a8-7223-11e7-8ca5-cf5aaf715eb8.jpg)

Not sure if this, and other script, should stay because plugins might potentially still use them.

**Comment by nylen** [comment]
> Not sure if this, and other script, should stay because plugins might potentially still use them.

We can still change the set of scripts we enqueue while we're in beta.  Plugins should expect to enqueue scripts that they depend on themselves.

**Comment by aduth** [comment]
>not useful in the Gutenberg context

If it's enqueued in the editor, we can assume it's at least indirectly used, via the dependency tree of the script loader. We don't directly reference `wp-link` anywhere, but I assume something we depend on is itself dependent upon this script.

This is more a point in favor of granular modularization, as I expect it's one of the "bigger" dependencies that has many of its own dependencies, e.g. `'editor'`.
