### ISSUE TITLE
Block Based Themes: Indicate which Block Template will be used

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#20252]
**The Problem**
With Block Based Themes and Block Templates, when creating/editing a post, you have to jump through a few hoops to discover which Block Template will be used when it gets displayed, which could get tedious, and result in user confusion. 

 For a blog titled `Hello World`, these are the current steps required to discover which Block Template will be used:
1. First, you'll need to have an understanding of Block Template hierarchy
2. In `wp-admin`, navigate to the `Appearance > Templates` page and search for the slug which matches the post in question. Search for the word "single", and analyze the results to see if any would match your post:
  - `single-post-hello-world`
  - `single-post`
  - `single`
3. If none match there, you have to navigate to the theme's source files and do the same check, first looking for matching html files. 
  - `single-post-hello-world.html`
  - `single-post.html`
  - `single.html`
4. If none match there, you have to start looking for matching PHP files
  - `single-post-hello-world.php`
  - `single-post.php`
  - `single.php`

While this process of hunting for the right source file isn't new to theme developers, it will be new to users, who now have the ability to create Block Templates.

To me, this process feels like a bit of a wild-goose-chase  🦆, especially when it's information we can easily provide!

**Describe the solution you'd like**
When editing a post, I would like to see an indication of which Block Template will be used as the source. Here's a mockup of a possible solution:

<img width="285" alt="Screen Shot 2020-02-14 at 6 17 16 PM" src="https://user-images.githubusercontent.com/7538525/74575806-5f20fa80-4f56-11ea-91b9-253a01079765.png">

While that mockup is one approach, I can already see it leading to questions from the user, wondering why they can't just change the template. So perhaps it's better living outside a "settings" area, like in the admin bar.

<img width="447" alt="Screen Shot 2020-02-14 at 6 19 53 PM" src="https://user-images.githubusercontent.com/7538525/74575886-b0c98500-4f56-11ea-96b3-c574e367ef92.png">

Regardless of where it might ultimately fit best, I think this could be a huge time-and-confusion-saver which helps users discover why their posts/pages look the way they do.

**Comment by epiqueras** [comment]
Thanks for opening this, it's a must-have!

**Comment by johnstonphilip** [comment]
Another mockup idea is to do something similar to the "Permalink" section in the Document sidebar:

<img width="288" alt="Screen Shot 2020-02-17 at 5 12 56 PM" src="https://user-images.githubusercontent.com/7538525/74689366-de0d7180-51a8-11ea-8d73-4373ce7b0a3e.png">

**Comment by paaljoachim** [comment]
It would be very helpful to have the post/page template name and link just below the Publish link.

**Comment by skorasaurus** [comment]
Just n'thing this; I was about to report this today because I couldn't figure it out. 

This is still applicable as of July 7, 2020 commit (51256763abb2f54fa66ebfa7b6e1e5efb6eb5210)

**Comment by paaljoachim** [comment]
This PR is being worked on: 
https://github.com/WordPress/gutenberg/pull/26355

**Comment by mtias** [comment]
Closing as the initial implementation is covered in the above.
