### ISSUE TITLE
Updated gutenberg and mobile stopped scrolling

### ISSUE THREAD

**Issue by waterplea** [WordPress/gutenberg#20264]
**Describe the bug**
I've updated editor and wordpress yesterday and now mobile version of my site stopped scrolling vertically. I've noticed that if I remove `position: fixed` from `html` (style comes from Gutenberg) — it starts scrolling

**To reproduce**
1. Go to https://alphamama.me/ using mobile or Chrome devtools emulation
2. Try to scroll

**Expected behavior**
Page should scroll vertically

**Additional context**
Gutenberg v7.5.0 
Wordpress v5.3.2
Theme: Graphy

**Comment by waterplea** [comment]
I had to override it with position: static as a hotfix on my site, so it still works. You can disable that override in DevTools to see the issue.

**Comment by talldan** [comment]
@waterplea Thanks for reaching out. The CSS was changed in this pull request to use a class name, so you shouldn't see this in Gutenberg v7.6: https://github.com/WordPress/gutenberg/pull/20245/files#diff-4d8551b27a54fe4f0a0a70e0df53ae98R3

This bit of CSS is supposed to only be used in the editor. It does seem unusual that you're seeing it in your site's CSS outside of the editor. I wonder why that's happening. It might be something to raise with your theme's author.

**Comment by waterplea** [comment]
The issue was because of **Emoji Autocomplete Gutenberg** plugin. Thankfully you can now add emoji in Chrome just by right click or Windows + dot so this plugin is obsolete :)
