### ISSUE TITLE
Create block: Add more options to control the plugin created

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#20263]
## Description

Moved from https://github.com/gziolo/create-wordpress-block/issues/1.

There was this question from @bph:

> If I wanted to use it for a single block plugin, and I see a great use case for it, but it would need boilerplate `pluginname.php`. I created the file added the header information and move the `index.php` information to that file. That was easy, so easy, that it might go into the script?

It was already addressed but there are two action items left:
- [ ] Add `readme.txt` file to both existing templates (ES5 and ESNext)
- [ ] Make it possible to override default values with prompts for fields like `author`, `license` or `version`:
https://github.com/WordPress/gutenberg/blob/07e8b8430ef7bb164a52d63a25120f8be5cd82e8/packages/create-block/lib/templates.js#L24-L26

## More details

Comment from @bph:

> For the plugin directory, we also need the readme.txt file that holds the information displayed in the WP directory for "Tags" "Installation" "Description" "Screenshot" "Version" etc..
>
> Here are two examples of readme text from my favorite plugins.
> 
> @JJJ [Post Type Switcher](https://github.com/JJJ/post-type-switcher/blob/master/readme.txt)
> @ocean90 [Public Post Preview](https://github.com/ocean90/public-post-preview/blob/master/readme.txt)

Comment from @ntwb:

> See also:
> 
> _"Readme files: To make your entry in the plugin browser most useful, each plugin should have a readme file named readme.txt that adheres to the WordPress plugin readme file standard. You can put your readme file through the readme validator to check it. "_
> • https://wordpress.org/plugins/readme.txt
> • https://wordpress.org/plugins/developers/readme-validator/

**Comment by pereirinha** [comment]
@gziolo I opened a PR to address this issue. However, I'm having trouble to test the proposed code change. So far, all attempts have failed.
