### ISSUE TITLE
Error in Ubuntu local development troubleshooting doc.

### ISSUE THREAD

**Issue by sainthkh** [WordPress/gutenberg#20260]
**Describe the bug**
If you follow [the local development troubleshooting doc for Ubuntu](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/env-ubuntu.md), it doesn't work. 

**To reproduce**
1. Do everything on [the page](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/env-ubuntu.md). 
2. Open http://localhost:8889
3. You can see the page below:

![Screenshot from 2020-02-17 14-51-21](https://user-images.githubusercontent.com/8130013/74627789-3dfb1c80-5197-11ea-906e-bb477bb1a876.png)

**Expected behavior**
Local development should set up successfully.

**Screenshots**

Check above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version 80.0.3987.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
- Gutenberg version: master branch [currently 7.5.0]

**Comment by sainthkh** [comment]
@talldan At first, I thought this issue would be fixed if I changed the doc. But I realized that this doc should be removed when #20180 is done. 

After that, I'll remove this `ubuntu-env` doc and remove the link to it in `getting-started`.

**Comment by noahtallen** [comment]
@sainthkh If you're interested, feel free to test https://github.com/WordPress/gutenberg/pull/20253 for me! (I don't have an ubuntu box at the moment.)

Testing steps are to check out the branch and run `./packages/env/bin/wp-env start` from the gutenberg root. (the command should complete successfully and give you a WordPress instance on localhost:8888 with Gutenberg mapped as a volume.)

**Comment by noisysocks** [comment]
`npm run env` is not _yet_ deprecated, but it's my intention that will be once we're confident in `wp-env`'s ability as a replacement. 

Do we need a 'Getting set up on Ubuntu' page for `wp-env`?

**Comment by sainthkh** [comment]
Unfortunately, `wp-env` doesn't work on Ubuntu now. We need to revisit this issue when `wp-env` fully works on Ubuntu.

**Comment by mkaz** [comment]
The original issue, the [document you are linking](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/env-ubuntu.md) is for just setting up the WordPress environment on Ubuntu.

The full developer environment setup, which does include the install/build steps is here: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md

**Comment by t-hamano** [comment]
I followed the history of #20261, and this issue should have been resolved by #25060, so I am closing it.
