### ISSUE TITLE
Empty Block Templates output string on front-end stating "Empty Template".

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#20276]
**Describe the bug**
If a block template has no content in post_content, instead of seeing a blank page (which would match the template), a string is output on the front-end stating "Empty Template", even for logged-out users.

<img width="505" alt="Screen Shot 2020-02-17 at 4 42 30 PM" src="https://user-images.githubusercontent.com/7538525/74688306-232fa480-51a5-11ea-9281-7f2596770e2b.png">

**To reproduce**
1. On a fresh install, create a Block Based Theme with just a single.html file, and put no content in that file. 
2. View the "Hello World" post.
3. See the message that states "Empty template.".
4. Log out. 
5. Notice you still see that message.

**Expected behavior**
I would expect 2 things here:
- If logged-out, I would expect to see a blank page on the front-end, which matches the template.
- If logged-in with admin-level capabilities, an error might appear stating "The single.html template was blank", thought this is likely better shown in wp-admin, rather than on the front-end.

**Desktop (please complete the following information):**
- OS: MacOS Catalina
- Browser: Chrome
- Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
The code for this is happening here:
https://github.com/WordPress/gutenberg/blob/a8e49fc6deea5fb72a16666ec32d287d431e5697/lib/template-loader.php#L99

- Gutenberg version: `master`.

**Comment by johnstonphilip** [comment]
A similar problem occurs with template-parts that are empty:

See where a string is returned if a blank template part is found here:
https://github.com/WordPress/gutenberg/blob/21304f999b1cbcc53d8ad098d297a6e9cf049e69/packages/block-library/src/template-part/index.php#L33

One additional aside thing is that that message is untranslated.

**Comment by johnstonphilip** [comment]
One other related issue here is this:

- Create a block template called `front-page`
- Add a template part, and make it call `footer`
- Don't place anything in the footer template-part. 

You will _not_ get the error message that is intended to show, but a blank page, as the output on the page is simply this:

`<!-- wp:template-part {"postId":141,"slug":"footer","theme":"my-theme"} /-->`

Since that is not `empty`, you don't get the error message that was intended.

**Comment by carolinan** [comment]
For template parts, this can be solved with https://github.com/WordPress/gutenberg/pull/28398
