### ISSUE TITLE
Dynamic Rendered Block that contains React Component

### ISSUE THREAD

**Issue by lievikoff** [WordPress/gutenberg#20274]
Hi! I want to create a dynamic block that creates a div and then i mount a react component to that div. It would be nice to be able to insert a React Component that you don't need to re-insert all the time to see changes. An example i have 100 pages with a block and i changed something. Am i going to update all 100 pages to see the changes? Can anyone tell me how i can avoid that re-insert block to see what i changed? It sounds like a crazy way to develop any complex block.

**Comment by lievikoff** [comment]
It seems like by some magic i did it.

For those who want to develop something in React with WordPress:

Return your React Component in the edit method.
Return null in save method.

Add a callback function that renders an empty single div for that block at frontend.
Mount your React Component with wp.element.render function like this:
`render( <Greeting />, document.getElementById( 'your-id-name' )[0] );`

And no more annoying re-inserts. You build your component and see it at the editor and frontend.

**Comment by lassenorgaard** [comment]
Hi @lievikoff, where did you do the wp.element.render?

**Comment by lievikoff** [comment]
> Hi @lievikoff, where did you do the wp.element.render?

@lassenorgaard Hej! I use another js file that i called render.js. I load the file ONLY at frontend so that was the main reason to separate render from register_block stuff. It doesn't make any sense to load register_block function at frontend. My render.js file looks like this:

```javascript
import { render } from "@wordpress/element";
import Search from '../../components/search';

const elements = document.getElementsByClassName( 'charitybase-wp-search' );

for ( let i = 0; i < elements.length; i++ ) {
	render( <Search />, elements[ i ] );
}
```

I am having a hard time with Gutenberg too so if you have any question you can email me lievikoff[at]gmail.com i will be glad to share what i found.

**Comment by solutions4theweb** [comment]
How are you getting the block attributes on the frontend?
