### ISSUE TITLE
[Navigation] Don't publish directly and don't render drafts

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#20282]
**Is your feature request related to a problem? Please describe.**
#19775 introduced the possibility to create a page directly from the block. By default the status of this page is `published`. This results in the situation that as soon as the place where the Navigation block is saved users of the website will be able to click on a navigation menu item that leads to an empty page.

**Describe the solution you'd like**
I would suggest that the Navigation block does not publish pages, but instead it creates drafts.
Drafts should be visible, but visually marked as drafts in the Navigation block.
When the Navigation block is deselected drafts should not be visible.
On the server when the navigation block is rendering, if the current `NavigationLink` is a page, it's status should be checked and if it is not `published` it shouldn't be rendered.

**Comment by noisysocks** [comment]
Creating the page as a draft makes sense to me.
