### ISSUE TITLE
I want to change or limit length of paragraph free.

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#20285]
![I want to change the length of paragraph](https://user-images.githubusercontent.com/44285360/74742026-3c1d8000-52a1-11ea-8811-6624c42ee787.jpg)
 

This picture shows what I want... I want to change or limit the length of the paragraph. Then I can make huge pic - appropriate paragraph length. You guys may know one span length of paragraph is best to read.

**Comment by jorgefilipecosta** [comment]
Hi @MYIG, that change could be applied by using CSS and applying it to the "p" element.
If you want to apply that change just to some paragraphs I suggest registering a style for the paragraph block https://developer.wordpress.org/block-editor/developers/filters/block-filters/#block-style-variations and then with CSS you can apply the rules just for paragraphs with that style `.is-style-small-paragraph { width: 70%; margin: auto; }`.

I hope this information is useful, feel free to leave a comment if you think additional discussion is needed.

**Comment by MYIG** [comment]
It is a good information to me. Thank you about it. But I want to request 'changing basic width of paragraph' feature. That CSS is veery useful to me but I think I should change all paragraph one by one. It is bothersome;; So I want an basic option about width or is there a global option about it?
