### ISSUE TITLE
size "small" is larger than "normal" when adjusting Base Font in wordpress.com

### ISSUE THREAD

**Issue by nouseforausername** [WordPress/gutenberg#20297]
When Customizing a wordpress.com blog in Twenty Twenty theme, and attempting to adjust the Base Font, there size options go from "tiny" to "small" to "normal"; however, the "small" option is much larger than normal. 
There definitely _should_ be a size between "tiny" and "normal", so I'm hoping this bug can be fixed, and a size "small" will exist, as tiny is too small, and normal irritatingly large, at least to my eyes.

**Comment by talldan** [comment]
@nouseforausername Thanks for reporting this. It looks like this is only an issue in WordPress.com, there isn't a 'tiny' option by default in the editor. I'd recommend contact wordpress.com support about the issue:
https://en.support.wordpress.com/
