### ISSUE TITLE
I want a feature 'saving color' or 'color bookmark

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#20295]
![vivaldi_7pp7QDuRiG](https://user-images.githubusercontent.com/44285360/74771295-3c357400-52d1-11ea-9dfe-7f60e2bc0a4e.jpg)

I think Color feature in gutenberg is better and better. But I want a feature 'saving color' or 'color bookmark'. I have my signiture color in blog. But It is bothersome to type color each time...

**Comment by talldan** [comment]
Thanks for reporting this @MYIG. This was originally requested in #6941, so I'll close this and copy your request over to a comment on that issue.
