### ISSUE TITLE
Request to Link Thumbnail Captions of Galleries

### ISSUE THREAD

**Issue by Woolwit** [WordPress/gutenberg#20299]
WP 5.3.2
Twenty Seventeen Theme
Page: https://svsurrender.com/welcome-aboard/
On images that contain captions, link to activate gallery is not present in vicinity of caption. Depending on size of the thumbnail, this may amount to over 50% of the image. 

Desired behavior would be that link is active anywhere over image/caption.

**Comment by talldan** [comment]
Thanks for reporting this, an issue was already created here for this problem:
https://github.com/WordPress/gutenberg/issues/14304
