### ISSUE TITLE
Should 'Export as JSON' be an available row action when Block is in the Trash

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#20303]
**Describe the bug**
With most of the list tables found in WP-core the only options available in the row actions from the Trash are 'Restore' and 'Delete Permanently'. The Blocks list table leaves 'Export as JSON' as an option even when the block is in trash. Should it be available? Or should a user have to restore a block before they're able to export it's JSON representation.

**To reproduce**
1. Go to the Blocks list table - '/wp-admin/edit.php?post_type=wp_block
2. Create a block.
3. Move the block to the Trash.
4. Navigate to the trash and hover over the block.
5. Note the 'Export as JSON' row action is still available.

**Expected behavior**
I don't expect any actions aside from Restore and Delete Permanently when an item is in the Trash.

**Screenshots**
![Screen Shot 2020-02-18 at 1 45 57 PM](https://user-images.githubusercontent.com/8726005/74781062-aa3c5580-5255-11ea-826a-aace111ed3e9.png)

**Desktop (please complete the following information):**
OS: MacOS 10.15.3
Browser: Chrome 80.0.3987.87
Gutenberg: bundled version from WP 5.4-Beta2

**Comment by talldan** [comment]
@garretthyder I don't really see an issue with it being exportable from the trash. I can imagine it serving a valid use case too—if a user wants to keep a copy of the block before deleting it permanently from a site. Having to restore, export, trash, then delete is quite a long workflow for that.

**Comment by garretthyder** [comment]
Thanks @talldan that makes sense, I guess it's an unintended feature. Closing this as I feel you're correct in that there's no negative here and if anything it's beneficial to keep that ability even though it's the only Trash list table in WP which provides more than the standard Restore/Delete
