### ISSUE TITLE
Import from JSON button design is jarringly different

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#20302]
**Describe the bug**
The button for 'Import from JSON' found on the wp_blocks list table is drastically different than it's sibling 'Add New' button.

**To reproduce**
1. Go to '/wp-admin/edit.php?post_type=wp_block'
2. See the two sibling buttons that are visually different in size.

**Expected behavior**
Both buttons should follow the same design convention for size.

**Screenshots**
![Screen Shot 2020-02-18 at 1 32 49 PM](https://user-images.githubusercontent.com/8726005/74780483-8b898f00-5254-11ea-8c30-a80b039c17a8.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browser: Chrome 80.0.3987.87
 - Gutenberg: bundled version from WP 5.4-Beta2

**Comment by youknowriad** [comment]
Seems like we can solve this by applying isSmall prop?
