### ISSUE TITLE
mobile version of site can't scroll down after loading - site not usable

### ISSUE THREAD

**Issue by pskall25** [WordPress/gutenberg#20314]
Severe bug in the new version???
activating the plugin leads to a total freeze status in the mobile version of our site, all pages even the generated ones are not usable(scrollable). 
with activated plugin the startpage/site was loaded correctly, the viewable buttons are usable but its not possible to scroll the page down and use the other content.
the desktop and tablet version of the site are still working well
Problem is solved when the plugin is deactivated!  
I hope you can correct this misbehaviour very soon.

**Comment by talldan** [comment]
Hi @pskall25, this sounds very similar to this issue:
https://github.com/WordPress/gutenberg/issues/20264

Does it seem like the same problem?

**Comment by pskall25** [comment]
Hi @talldan, 

**Additional context**
Gutenberg v7.5.0
WordPress v5.3.2
Theme: Twenty Sixteen / Child Theme
about 30 other plugins activated

Yes, It's exactly  the same thing.. shall I close my issue?
Greets from Dortmund (Germany)

**Comment by hartrusion** [comment]
Good Morning,
I have the same issue after updating to v7.5.0. on WP v5.3.2. Deactivating the plugin solved the issue instantly.

I'm using twenty twenty theme. Changing theme, removing all custom CSS, deactivating most of the plugins (I didnt deactivate polylang yet) did not solve the issue.

Problem occured on Firefox and Chrome on Android, as well on Firefox on Windows, it doesn't seem to be a device or browser Issue. As soon as the browser with is smaller then somewhat of 780 px or something, scrollbar disappears and scrolling is impossible.

**Comment by jorgefilipecosta** [comment]
I'm sorry for the problems this bug is causing. We already merged a fix that should be part of the next Gutenberg release and is already part of WordPress 5.4 beta 2. I'm closing the issue as the fix was already merged.
