### ISSUE TITLE
Pasting text trims spaces before and after the copied text

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#20310]
**Describe the bug**
Related https://github.com/WordPress/gutenberg/issues/16172

Props @YukinoHayakawa for identifying this here - https://github.com/WordPress/gutenberg/issues/16172#issuecomment-586686930.

**To reproduce**
1. Add some text with leading and trailing spaces to a paragraph block.
2. Copy the text and paste into a separate paragraph
3. Observe that the leading/trailing spaces are lost.

**Expected behavior**
Ideally content that is pasted is as close as possible to the content that is copied.

**Additional context**
Tested on Mac OS X Mojave 10.14.6, Chrome 79.0.3945.130

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7
Gutenberg plugin 10.1.1
Twenty Twenty One

Tapping the spacebar a few times then writing some text and tapping the spacebar again.
Then copy the space, text and space into another paragraph block looks like this.
(I have both paragraphs selected.)

![Uploading Screen Shot 2021-03-11 at 20.43.13.png…]()

Conclusion is that one can copy the space and the text into a new paragraph block and it copies over.
Closing issue.
