### ISSUE TITLE
Latest Posts block: Excerpt doesn't respect the excerptLength attribute (WP 5.4 Beta 2)

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#20311]
On front-end, the excerpt for the Latest Posts block isn't trimmed to the length given by the user with the excerptLength attribute.
This bug was introduced in https://github.com/WordPress/gutenberg/pull/19669

**Comment by youknowriad** [comment]
cc @draganescu @jorgefilipecosta

**Comment by draganescu** [comment]
Hi @dianeco I've added a fix in PR #20313. The behavior of this is to limit the length of _generated_ excerpts to what is set in the editor, but leave the manual excerpts to whatever length they have.

Thank you for raising this issue!
