### ISSUE TITLE
@wordpress/env: Add support for more types of sources

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#20325]
`wp-env`currently supports three types of _sources_, as detailed in [the documentation](https://developer.wordpress.org/block-editor/packages/packages-env/#wp-env-json):

| Type | Format | Example(s) |
| -- | -- | -- |
| Relative path | `.<path>` or `~<path>` | `"./a/directory"`, `"../a/directory"`, `"~/a/directory"` |
| Absolute path | `/<path>` or `<letter>:\<path>` | `"/a/directory"`, `"C:\\a\\directory"` |
| GitHub repository | `<owner>/<repo>[#<ref>]` | `"WordPress/WordPress"`, `"WordPress/gutenberg#master"` |

There are several new types of sources that can be added that would be useful for day-to-day WordPress development:

| Type | Format | Example(s) |
| -- | -- | -- |
| Git repository (git protocol) | `git://<host>/<path>[#<ref>]` | `"git://github.com/WordPress/wordpress-develop.git"`, `"git://develop.git.wordpress.org/"`, `"git://develop.git.wordpress.org/#master"` |
| Git repository (http protocol) | `git+http[s]://<host>/<path>[#<ref>]` | `"git+https://github.com/WordPress/wordpress-develop.git"`, `"git+https://github.com/WordPress/wordpress-develop.git#master"` |
| Git repository (ssh protocol) | `git+ssh://<host>/<path>[#<ref>]` | `"git+ssh://git@github.com:WordPress/wordpress-develop.git"`, `"git+ssh://git@github.com:WordPress/wordpress-develop.git#master"` |
| SVN repository (svn protocol) | `svn://<host>/<path>` | `"svn://core.svn.wordpress.org/trunk/"` |
| SVN repository (http protocol) | `svn+http[s]://<host>/<path>` | `"svn+https://core.svn.wordpress.org/trunk/"` |
| ZIP file | `http[s]://<host>/<path>.zip` | `"https://wordpress.org/wordpress-5.4-beta2.zip"` |

The specification for these URLs are [borrowed largely from `npm`](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

## Implementation

`wp-env` was written with the expectation that more source types would be added. Adding support for new sources involves updating  `parseSourceString` to handle a new pattern, and then handling the new `source.type` in `downlodSource.`:

https://github.com/WordPress/gutenberg/blob/57533e8fa2d63829d71b40a87a2e7f79f3291645/packages/env/lib/download-source.js#L19-L23

All git sources including GitHub should create a source object with `source.type === 'git'`.

## Progress

- [ ] git://
- [ ] git+https://
- [ ] git+ssh://
- [ ] svn://
- [ ] svn+https://
- [ ] http://*.zip

---

cc. @epiqueras @noahtallen

**Comment by epiqueras** [comment]
How valuable do you think these will be? I'd rather avoid increasing the size of the package for such a seldom-used feature.

**Comment by noisysocks** [comment]
Agree that bloat is a concern, and I wouldn't bother with e.g. support for `.tar.gz` files. But SVN and ZIP are very prevalent in the WordPress ecosystem. Specifically, support for SVN lets us install and test plugins and themes in the w.org repository, and support for ZIP files lets us install and test WordPress betas.

Example:

```json
{
	"core": "https://wordpress.org/wordpress-5.4-beta2.zip",
	"plugins": [
		"svn+https://plugins.svn.wordpress.org/wordpress-seo/trunk/",
		"svn+https://plugins.svn.wordpress.org/woocommerce/trunk/"
	],
	"themes": [
		"svn+https://themes.svn.wordpress.org/oceanwp/1.7.5/"
	]
}
```

**Comment by epiqueras** [comment]
Then why do we need multiple protocols for Git and SVN? I think `<owner>/<repo>[#<ref>]` and `<host>/<path>` covers all use cases.

**Comment by noisysocks** [comment]
> and <host>/<path> covers all use cases

So WooCommerce would be `"woocommerce/trunk"`? How would we disambiguate that from the [woocommerce/trunk](https://github.com/woocommerce/trunk) GitHub repository?

I figured it was best to align `.wp-env.json` closely to what npm does for its `"dependencies"` field, and that adding support for all protocols isn't too much extra effort because one regular expression can handle all the cases.

For example, if `/^(git:.*)|git+(.*)$/` matches the string then the first matching group would contain the URL that we pass to `git fetch`.

**Comment by epiqueras** [comment]
We already default to git, so maybe svn could be `svn://<host>/<path>`.

**Comment by noisysocks** [comment]
> Specifically, support for SVN lets us install and test plugins and themes in the w.org repository

I thought about this some more and no longer think it's worth the added complexity. Plugins and themes hosted on w.org can be installed via a URL to the ZIP file, e.g:

```json
{
	"plugins": [
		"https://downloads.wordpress.org/plugin/akismet.4.1.3.zip"
	],
	"themes": [
		"https://downloads.wordpress.org/theme/astra.2.3.1.zip"
	]
}
```

So, in other words, I think #20426 is sufficient.

**Comment by epiqueras** [comment]
Yeah, I thought that too, that's why I tackled ZIP file support first.

**Comment by juanmaguitar** [comment]
I'm trying to create a `.wp-env.json` to recreate the development environment needed for DevHub as explained here
https://make.wordpress.org/docs/handbook/devhub/

There are several plugins required for this environment that doesn't seem to have a `.zip` available and are only available through its svn address, for example:

- https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/handbook/
- https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/
- https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-cli/

Is there any current way to deal with these SVN addresses or these types of internal plugins?

This is what I'm trying to use but the SVN sources are not recognized

_`.wp-env.json`_
```
{
  "plugins": [
    "WordPress/phpdoc-parser",
    "https://downloads.wordpress.org/plugin/jetpack.9.9.zip",
    "https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/handbook/",
    "https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/",
    "https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-cli/"

  ],
  "themes": [
    "https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/"
  ]
}
```

**Comment by n3f** [comment]
I'd like to revisit this issue, specifically as I've found having the git protocol (ssh) is valuable for private repos & authentication.  I found a simple change to `parse-config.js` worked.

```diff
@@ -112,10 +112,28 @@ function parseSourceString( sourceString, { workDirectoryPath } ) {
 			path: path.resolve( workDirectoryPath, basename ),
 			basename,
 		};
 	}
 
+	const gitHubProtocol = sourceString.match(
+		/^(git@github.com[^\/]+)\/([^#\/]+)(\/([^#]+))?(?:#(.+))?.git$/
+	);
+	if ( gitHubProtocol ) {
+		return {
+			type: 'git',
+			url: `${ gitHubProtocol[ 1 ] }/${ gitHubProtocol[ 2 ] }`,
+			ref: gitHubProtocol[ 5 ] || 'master',
+			path: path.resolve(
+				workDirectoryPath,
+				gitHubProtocol[ 2 ],
+				gitHubProtocol[ 4 ] || '.'
+			),
+			clonePath: path.resolve( workDirectoryPath, gitHubProtocol[ 2 ] ),
+			basename: gitHubProtocol[ 4 ] || gitHubProtocol[ 2 ],
+		};
+	}
+
```

Would it be OK to reopen? Or should I create a new issue?

**Comment by noahtallen** [comment]
I think it's reasonable to support SSH authentication for git. Is there a way we could support it without making it GitHub specific? (E.g. it'd be nice to support auth for other git providers as well without having to list them all :))
