### ISSUE TITLE
Site Title block: do not force h1 on all pages

### ISSUE THREAD

**Issue by nickcernis** [WordPress/gutenberg#20333]
**Is your feature request related to a problem? Please describe.**
The `site-title` block currently uses an `h1` element at all times:

https://github.com/WordPress/gutenberg/blob/32aaed94dcc5c9b27889a1819142d4de1d6f7e94/packages/block-library/src/site-title/index.php#L14

Subpages and archives will wrap the site title in an h1 as a result. This is less good for accessibility and SEO, because the site title is not normally the most important title on those pages — the page/post/archive title is.

Popular themes typically use `h1` only if `( is_front_page() || is_home() ) && ! is_page()`, and a `div` or `p` at other times.

From [Twenty Twenty](https://github.com/WordPress/twentytwenty/blob/6d0a5240af108d02f58ec797fd49b32458a4c698/inc/template-tags.php#L43-L45
):

```php
		'home_wrap'   => '<h1 class="%1$s">%2$s</h1>',
		'single_wrap' => '<div class="%1$s faux-heading">%2$s</div>',
		'condition'   => ( is_front_page() || is_home() ) && ! is_page(),
```

Genesis does something similar, but lets users choose whether to use h1 or p on the homepage, defaulting to h1 for “latest posts” and p for static pages.

**Describe the solution you'd like**
Should WP behave like Twenty Twenty, Genesis, and others instead of forcing an h1 everywhere and placing the burden on theme developers to adjust it?

Users could still filter the result if they wish, but it would be more optimal by default.

**Describe alternatives you've considered**
Users who care about accessibility and SEO will need to filter `site-title` block output or use a theme or SEO plugin that handles this for them.

**Comment by youknowriad** [comment]
Sounds legit to me, we should be able to choose the level and sometimes even show the site title at multiple places in the same page.

**Comment by mtias** [comment]
@youknowriad this to me would be another point towards making this block a `variation` of **Heading**, so you get access to any h-level (with h1 as the default, perhaps), color support, document outline support (for invalid heading), etc.

**Comment by nickcernis** [comment]
> @youknowriad this to me would be another point towards making this block a `variation` of **Heading**, so you get access to any h-level (with h1 as the default, perhaps), color support, document outline support (for invalid heading), etc.

@mtias Perhaps the default should be p/div if we go this route? That way, it's correct for the most use cases (subpages), and users only have to override it on their homepage (to set an h1 there if they choose). Otherwise we're asking users to change from h1 to p on every post and page they create.

There may also be a case to leave the site title block as a separate block if we decide to add other block properties to it, such as the option for logo output: https://github.com/WordPress/gutenberg/issues/1851#issuecomment-588965603
