### ISSUE TITLE
Spotify: Embed failure (again)

### ISSUE THREAD

**Issue by bsanevans** [WordPress/gutenberg#20346]
**Describe the bug**
Tests indicate the same bug as https://github.com/WordPress/gutenberg/issues/19604 has resurfaced.

**To reproduce**
1. Add a Spotify block.
2. Try to embed a Spotify URL or URI
3. Click on Embed button.

**Expected behavior**
For the Spotify item to embed.

**Desktop (please complete the following information):**
 - OS: MacOS X 10.15.3
 - Browser Chrome 80.0.3987.106, Safari 13.0.5
- WordPress 5.3.2

**Comment by bsanevans** [comment]
The issue was also reported a few hours ago on the original thread: https://github.com/WordPress/gutenberg/issues/19604#issuecomment-589335504

Last time, the issue was thought to be with Spotify. An issue was opened here: https://github.com/spotify/web-api/issues/1432

We never heard back from them, and the issue was resolved a few weeks later.

**Comment by Soean** [comment]
@bsanevans The old issue #19604 was reopened. Should we close this issue?

**Comment by bsanevans** [comment]
Sure. Thanks!
