### ISSUE TITLE
Remove save className auto-application

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2035]
Currently when a block is saved, we automatically inject a generated class name to the generated markup without the block author's intervention.

However, the block author _must_ apply this generated class themselves in the `edit` implementation, using the provided `className` prop.

The block author must also have general awareness of this class name to be able to apply styling to their block in stylesheets, so it is not intended to be totally transparent.

We must decide one or the other of the two actions below:

- Remove auto-application and force block implementer to consistently apply `className` themselves in both `edit` and `save`
- Account for auto-application in [invalid block preview](https://github.com/WordPress/gutenberg/blob/073cfc4/editor/modes/visual-editor/block.js#L417-L422)

**Comment by youknowriad** [comment]
Making the `className` explicit sounds like the good approach to me for consistency between edit/save methods.

**Comment by youknowriad** [comment]
Like mentioned here https://github.com/WordPress/gutenberg/pull/2394#discussion_r132979991 The className property has two roles right now:

 1- Overriding the default generated className and dropping this className if set to false.
 2- Setting it to false hides the className inspector control.

Does it make sense to have two different attributes for this: declare support for the inspector control and another property to override the generated className (or disable it)?

This separation would allow us to have a more generic `support` property to declare support for advanced inspector controls. (className and anchor)

**Comment by aduth** [comment]
>Does it make sense to have two different attributes for this: declare support for the inspector control and another property to override the generated className (or disable it)?

Please no 😩  If it really must be opt-out, we can still do `supports` as an object of boolean values.

**Comment by gziolo** [comment]
It was implemented in #2507. Closing this one.
