### ISSUE TITLE
Navigation menu block: keyboard accessibility issues

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#20369]
The accessibility team [recently performed a few accessibility tests of the new navigation menu block](https://docs.google.com/spreadsheets/d/1yFCFlPK78Ryl7WT9iRhn4Xe0PpWvnzAKSzBLi6L8GHY/edit#gid=0).

The general consensus is that keyboard-only interaction is very difficult, and at times impossible. In particular, the team found that:

- Could not move keyboard focus to the 'Add Navigation Link' inserter button.
- I was able to add a submenu item by way of the 'Add submenu' option in the block's toolbar. This pattern feels more intuitive and easier to navigate. However, having the interaction split into two different places (on the modal I create a new navigation link, but then I have to go back to the block to edit the newly added link placeholder) was confusing.
- Having the nested links disappear when the subblock was not selected was disorienting. It made me believe that somehow my sublinks had been deleted. 
- Moving between the main block and nested blocks was very difficult and unpredictable. There was no visible focus that gave a clear sense of place while exploring the blocks. It was very difficult to understand what was going - what mode am I in? Am I in the navigation block, or in a menu item? 
- Tabbing from an active submenu list item sent focus to the sidebar, when I had expected to move to the next top level menu item
- The relationship between a top-menu list item and its children was confusing; it seemed like being in edit mode for the parent item automatically included being in edit mode for the children, but that didn't continue to other parent items.
- In the color palette when you don't like the default colors offered, you need to open another popover and you can only use arrows keys to change the color. When I tab to use HEX section the popover closes.

Worth adding that on my tests, the 'block navigator' overlay felt much more intuitive and easier to navigate.

**Comment by karmatosed** [comment]
Noting @enriquesanchez is going to split this out into actionable issues so we can make a move on each and work out which need design and which don't. Thanks for doing that!

**Comment by karmatosed** [comment]
@enriquesanchez as you've split this out into issues, should this one be closed now?
