### ISSUE TITLE
Is there a way to make the *Styles* PanelBody default to open?

### ISSUE THREAD

**Issue by jakeparis** [WordPress/gutenberg#20363]
This is the built-in Styles panel, and it always defaults to closed. I'd like for it to be initially open on a given block. Is there a way to override that state for a specific block?

**Comment by youknowriad** [comment]
No there's none. This panel is added by Gutenberg itself so you can't access and tweak its props.

The idea is that blocks already have too many panels so it's hard to find the right balance between opened and closed ones. 

That said, there's an ongoing project about redesigning Gutenberg and it will most likely impact this panel too. So let's see how it evolves in the next weeks.
