### ISSUE TITLE
display: table-caption;  on figcaption looks bad!

### ISSUE THREAD

**Issue by carasmo** [WordPress/gutenberg#20362]
**Describe the bug**

**To reproduce**
1. Add an image with a caption

**Expected behavior**
The caption should be the width of the image above it and not some tiny narrow area.

**Comment by talldan** [comment]
@carasmo Thanks for reaching out. Would you be able to provide more information about the following:
- Which theme you're using.
- Are you using the Gutenberg plugin and if so, which version?
- Which version of WordPress are you using.

Thanks.

**Comment by karmatosed** [comment]
In the latest version of Gutenberg, using Twenty Twenty I see this and it's the full width. 

![image](https://user-images.githubusercontent.com/253067/76803087-f507a980-67d0-11ea-8ed2-a08f8c69e8df.png)

I think, for now, let's close this. However, we can reopen if needed and find more information out.
