### ISSUE TITLE
Add simple container block to wrap smaller elements in block-based themes

### ISSUE THREAD

**Issue by Netzberufler** [WordPress/gutenberg#20376]
I have experimented with Full Site Editing and turned an existing theme with PHP templates in a block-based WordPress theme. 

There were multiple times where I had the need to wrap some elements. While the Group block works fine with larger sections it felt a bit much for wrapping smaller elements like the post date and author:

It would have quickly turned into this to achieve the same structure as in the PHP version:
```
<!-- wp:group {"className":"entry-meta"} -->
<div class="wp-block-group entry-meta">
	<div class="wp-block-group__inner-container">

		<!-- wp:group {"className":"entry-date"} -->
		<div class="wp-block-group entry-date">
			<div class="wp-block-group__inner-container">

				<!-- wp:post-date /-->

			</div>
		</div>
		<!-- /wp:group -->

		<!-- wp:group {"className":"entry-author"} -->
		<div class="wp-block-group entry-author">
			<div class="wp-block-group__inner-container">

				<!-- wp:post-author /-->

			</div>
		</div>
		<!-- /wp:group -->

	</div>
</div>
<!-- /wp:group -->
```

The Group block generates a lot of HTML markup and often you also don't need the full range of settings like aligment and colors (and probably more to come) for each and every element.

So I wish there was a simple container / wrapping block for this, with less HTML markup and without any settings. Maybe users are able to transform it to a full Group block if they want adjust colors or make any changes. And it should allow semantic tags (related to #20200)

**Comment by mtias** [comment]
I think the inner container of the group block should be optional.

**Comment by carolinan** [comment]
In block themes, there is no longer an inner container for the group block.

@Netzberufler What types of settings do you think are missing from the post blocks (date, terms, author etc) for you to not have to use the wrapper?

**Comment by jordesign** [comment]
With no longer input on this issue in almost 2 years, and the increased maturity of the Block Editor - I'm going to close this issue.
