### ISSUE TITLE
Global Styles: Attributes and Controls

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#20370]
(This details some of the requirements specified in https://github.com/WordPress/gutenberg/issues/20331)

As we dive deeper into the system, we realized that we needed a better mechanism to handle Block attributes and the controls used to update them.

If we distill attributes down, we can bucket them into 2 "types":

**Styles** and **Functionality**.

Design vs. configuration.
"Color" vs. "Drop cap" (for paragraph)

The core system should have a way to recognize certain Block attributes, and perhaps automatically render certain controls as required.

For example, if "fontSize" is needed, then the FontSize controls would render.

At the moment, blocks must **manually** "setup" of attributes and controls. Tying this together in an ad-hoc manner. Also, certain attributes (color, fontSize), are (in a way) bound to blocks, making it difficult to be accessed outside.

This detail is important if we want Attributes and Controls to be **shared** between the Post Editing and Site Editing/Global Styles Editing experience.

---

That being said. If absolutely required, we can perhaps work around this to for the sake of  prototype/demo.

However, this unified mechanism of Attribute x Control needs to be solved for Global Styles to work seamlessly with the editing experience.

**Comment by nosolosw** [comment]
Ah, this is a walk down on memory lane! We've come far since this was discussed and we now have an initial system for this already. Closing this and pointing people to the more specific https://github.com/WordPress/gutenberg/issues/22700
