### ISSUE TITLE
Assuming link rel meaning can lead to confusion

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20373]
If you add a link on a button you could end up thinking 'link rel' was where you put the link. This is even more compounded by the focus of the link icon being lost, for example:

![image](https://user-images.githubusercontent.com/253067/75077285-2eaf0280-54fa-11ea-82f8-99c1761d52a8.png)

I think there are a few options:
- Add text to describe what link rel is (not the way to link).
- Remove link rel and add it to the link interface.

**Comment by Soean** [comment]
@karmatosed I opened a ticket about this field just a few days ago: https://github.com/WordPress/gutenberg/issues/20208

**Comment by karmatosed** [comment]
Ah great! Let's close this then and focus there.
