### ISSUE TITLE
Rename Gutenberg as The Block Editor Lab plugin 

### ISSUE THREAD

**Issue by daveloodts** [WordPress/gutenberg#20407]
The name Gutenberg is only known by people dived deep into the community. For anyone else, it just creates doubts and friction.

On a last meetup - a helpdesk meetup (heard this via the organizer) there were 4 new members. When they heard about Gutenberg; they fell out of the sky. Never heard about that.
When the organizers explained it that is was about the block editor; the 4 persons apparently worked already with the block editor for 6 months. They loved working with it.

They seemed to like the Gutenberg plugin as the organizers presented it, but they never ever would made the connection themself. 

**We need to promote the block editor as the block editor.**
Not as Gutenberg.
I just creates friction, and marketing-wise it's just not good to set a new technology in our market.

Only use the naming: "The Block Editor", drop the name Gutenberg

Rename the Gutenberg plugin as The Block Editor Lab plugin.

Gutenberg could stay as the name of the particular Block Technology, which can be used on Drupal and MailChimp. The name stays known in the community, as some kind of "codename". 

But in the context of WordPress: on every official blog, on the rep and in our admin-screen, and so towards non-community users; the name Gutenberg just isn't a good choice.

**Comment by Soean** [comment]
In WordPress itself and the documentation, we already use "block editor" for the editor. Gutenberg is not mentioned there and should not.

The Project / Plugin "Gutenberg" is more than just the Block editor. We explain it on the plugin page and here on Github:
>"Gutenberg" is a codename for a whole new paradigm in WordPress site building and publishing, that aims to revolutionize the entire publishing experience as much as Gutenberg did the printed word. Right now, the project is in the first phase of a four-phase process that will touch every piece of WordPress -- Editing, Customization, Collaboration, and Multilingual -- and is focused on a new editing experience, the block editor.

https://wordpress.org/plugins/gutenberg/

Not every WordPress user should install the plugin, for most of them the current WordPress version is the best solution.

After more than 3 years the code name "Gutenberg" has established itself well in the community in my opinion, so that many can imagine something under the project. If we rename the plugin it would only lead to confusion.

**Comment by swissspidy** [comment]
Previously: #4681.

> The Gutenberg name will continue to live on as the label for the overarching Gutenberg project: Gutenberg phase 1 (the block editor) is approaching its conclusion, while Gutenberg phase 2 (site customisation) will start to ramp up soon.
> 
> There's no immediate need to deprecate the Gutenberg name (if there ever will be), so I'm going to close this issue. We can always revisit it at the conclusion of the Gutenberg project, but there's no timeline for that at this stage.

**Comment by daveloodts** [comment]
Sorry i have missed the duplicated ticket.
I've read it now and was surprised that the majority was okay with removing the name Gutenberg. 
But the decision was blown in the wind, seems like.

And all the predictions of @mor10 just came out, from my point of view. Smart guy.

Again, **Only the 1 WP percenters** (read: the WP Community members) know what Gutenberg is.
And still, the naming is used (or mis-used) on a lot of (official) articles.

Just one fine official example: https://wptavern.com/gutenberg-one-year-later
(okay, wptavern is read by the community, but the way how we (the 1 WP percenters) handle naming terms is carried through till the end user. And they are confused when they gonna google stuff.)

Just to verify my point: google on 'block building wordpress' or 'block wordpress' and the top 10 is stuffed with the word Gutenberg. Jumping from the word 'block editor' to 'gutenberg', so on.
It's just confusing the end-user, as we see that on meetups.

This is the mind of the end-user, the 99 WP percenters: What is Gutenberg? I can't find Gutenberg in my dashboard? Ow, but Gutenberg seems to be a plugin? Do i need to install a new plugin to work with blocks? But why? Don't get it. Googling things makes me more confused. Damn, that Gutenberg plugin has a lot of negative reviews. Don't think i'm gonna install it. I'll try something else. Hey, what's that? Elementor!  
(not to be joking: but Elementor tripled in growth since the launch of 5.0)

But okay: close the ticket. There was a chance/request to change it...

Thanks for the fast reply!
