### ISSUE TITLE
[doc] Development instructions don't work

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20400]
**Describe the bug**
The Gutenberg development instructions don't work in the basically [first step](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md#step-1-installing-a-local-environment).
````
npx wp-env start
````
````
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/wp-env - Not found
npm ERR! 404
npm ERR! 404  'wp-env@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/build/.npm/_logs/2020-02-23T16_29_21_407Z-debug.log
Install for [ 'wp-env@latest' ] failed with code 1
````

**To reproduce**
1. Ensure that recent node (like LTS) is used (e.g. `nvm install lts/* && nvm use lts/*`
2. Update `npm` to ensure latest, bug-fixed `npm` is used: `npm install -g npm`
3. Now invoke the `npx` (`npm` script runner thing) from the developer documentation: `npx wp-env start`
4. The command fails because that script/package can't be found on the npm registry:
````
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/wp-env - Not found
npm ERR! 404
npm ERR! 404  'wp-env@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/build/.npm/_logs/2020-02-23T16_29_21_407Z-debug.log
Install for [ 'wp-env@latest' ] failed with code 1
````

**Expected behavior**
The `npx` command works and sets up a WordPress dev environment for me.

**Desktop (please complete the following information):**
WSL 1 Ubuntu (stable) on Windows Pro x64
Docker Desktop (stable) with Hyper-V

**Comment by talldan** [comment]
Hey @strarsis. The issue will be that you haven't run `npm install` yet. That's in the first section, Getting Started:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md#getting-started

**Comment by strarsis** [comment]
@talldan: Thanks, now it works.

**Comment by carolinan** [comment]
The documentation needs to be improved.  There are two "first steps", and _it should not say step 1 if it is not step 1._
Don't assume that the reader can read between the lines.

Should not step one be to clone the Gutenberg repo?
