### ISSUE TITLE
Uncaught Invariant Violation: Invalid hook call

### ISSUE THREAD

**Issue by surajv** [WordPress/gutenberg#20423]
Hello,

I am getting this error:
```
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
On this line of code
```
return (
	<li key={ id } className={ classes } dangerouslySetInnerHTML={ { __html: result.getText() + ( result.hasTooltip() ? renderToString( <Tooltip>{ result.getTooltip() }</Tooltip> ) : '' ) } } />
)
```
As soon as I remove the `renderToString` code works fine.

Could you please help me to understand why is that happening?

Thank you.

**Comment by ahmadawais** [comment]
You sure you don't have conflicting versions of React. Also why are you using `dangerouslySetInnerHTML` prematurely. You should only render the HTML with it and not the logic.

**Comment by surajv** [comment]
Hey Ahmad,
Thank you for reverting back.
It seems like the issue was something else and we got that ironed out.

Appreciate your help though!
