### ISSUE TITLE
Support images in the List block

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2042]
Adding images into a list is a common task for websites that include documentation or instructions, and would be good to support within the general List block eventually.

Yes, I know this requires nested blocks, but it's come up in a couple reviews so I thought it would be good to get a conversation started. :)

**Comment by iseulde** [comment]
This will be fun. Any other use cases? Could this be a separate block?

**Comment by melchoyce** [comment]
> Could this be a separate block?

Totally could be. @mtias had the same idea.

Recipes is another good one. Sounds like you were playing around with a recipes block at some point?

**Comment by iseulde** [comment]
Yeah, I used a recipe card block as on example for a template block: https://github.com/nylen/gutenberg-examples/tree/master/05-recipe-card

**Comment by iseulde** [comment]
I think a separate block might be a good way to go as we don't want to burden the general list block with controls for smaller use cases. It feels like they'd be better off with a custom flow anyway.

**Comment by afercia** [comment]
How many users would want to do this? Would the Classic Text (TinyMCE) or the HTML blocks be an option?

**Comment by melchoyce** [comment]
HTML block is likely too complicated, but I do think we should be able to support this use case in the Classic Text block. See #2043.

**Comment by mtias** [comment]
I think we have two paths:

### Nesting
Use this case as a way to get started with nested block insertion, changing a bit how inserter works. An idea I discussed with @jasmussen is to make inserting a two-step process.

1. You pick item in the inserter.
2. You pick where to insert.

This would also help with people wanting to insert something _before_ a block. We could allow certain things to be inserted within other blocks, like images handled by tinymce in list, table, etc.

### Embrace blocks
Many of these use cases are symptomatic of what we are trying to solve in the first place—creating "rich" posts should not depend on workarounds, or knowing html, or fragile approaches.

May be an opportunity to create a "List with images" block of sorts, like @iseulde recipe one (which we should add to the plugin as an example, even if it's plugin territory later on). This would come with placeholder for images, likely more robust markup, and something that is more evident to new users how it could be used.

**Comment by jasmussen** [comment]
So, this could be a case of enabling inline images in text. This is, I would say, an edgecase, and we probably wouldn't want to optimize too highly for it. For example, I don't think you should be able to click an inline image and set it to "full wide". Perhaps it doesn't have very many block options at all. Lots to discuss, but to get the ball rolling, here's a mockup of a "Sticky inserter":

Step 1, click a block in the inserter. It sticks to your cursor:

![sticky inserter step 1](https://user-images.githubusercontent.com/1204802/28669565-02e557b2-72d5-11e7-9582-0ae06cdf1303.png)

Step 2, click where you want to inserter it in the text. There's a little blue line indicating where it'll show:

![sticky inserter step 2](https://user-images.githubusercontent.com/1204802/28669576-176bb118-72d5-11e7-8f8e-d1ab475ca697.png)

Or, insert it between blocks:

![sticky inserter step 3](https://user-images.githubusercontent.com/1204802/28669581-20a2f688-72d5-11e7-8aaf-ef21c72535db.png)

As a reminder, this is the current behavior:

![current flow](https://user-images.githubusercontent.com/1204802/28669586-2658a794-72d5-11e7-8596-5486934cde0b.png)

We'll likely want great keyboard shortcuts for this, for speed and accessibility.

**Comment by senlin** [comment]
@jasmussen 

> This is, I would say, an edgecase...

Any numbers to support that?

Someone on the "edge" has been so kind to add this as an issue to [his review](https://wordpress.org/support/topic/counter-productive/)

**Comment by jasmussen** [comment]
> Any numbers to support that?

I already regret calling it an edgecase. Would you permit me to retract that?

In my haste to write a comment (we get a lot of incoming tickets), I was thinking of a particularly gnarly situation where you can insert an image in the middle of a word, then float it, and the word will read as though it's not split in the middle, though it will be for search engines:

```
<p>I'm sorry I called it an edge<img src="heart.jpg" style="float: right;">case, please forgive me <3</p>
```

Even that above might not be an edgecase, but it's certainly what I would call undesireable behavior, something we can protec the userfrom. 

What I mean to say about that isn't that we _should not support inline images_, just that it's a difficult interface problem to solve. Bear with us :)

**Comment by hedgefield** [comment]
That 'sticky' inserter is a really cool concept @jasmussen. We were looking at it from the opposite angle (pick the spot, then the block) in #2061.

As for nesting vs a new block, I would go with the block approach. It's the core of what gutenberg is, so perhaps it is best to stick to our guns and provide a list-with-images block or expand the current list block to support this? I'm not convinced that nesting won't make things harder to understand, although I've not heard the ideas for other use cases.

**Comment by jasmussen** [comment]
Should we rename this ticket to something like "Inline images"?

**Comment by maddisondesigns** [comment]
Just wanted to add that I raised this as an issue (along with an example) in #1281

**Comment by jasmussen** [comment]
Closing in favor of #2043

**Comment by benoitchantre** [comment]
> Any other use cases?

Lists of logos in business and events websites.
