### ISSUE TITLE
buildTermsTree returns only 1 result

### ISSUE THREAD

**Issue by Chrico** [WordPress/gutenberg#20430]
**Describe the bug**
We're using a CPT which is hierarchical. 

In Gutenberg the "Select Parent" only shows 1 item, but we have 198 results splitted up into 2 requests for this select:

![image](https://user-images.githubusercontent.com/3417446/75230457-ede21280-57b3-11ea-89f7-995bfeb1a402.png)

When debugging the component i'm seeing, that the [`buildTermsTree`](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/editor/src/utils/terms.js#L13)  just returns an array with 1 result:

![image](https://user-images.githubusercontent.com/3417446/75230678-6648d380-57b4-11ea-8c25-6152d944b7ec.png)

- `a`  = result from those 2 splitted up requests 
- `s` = the result from `buildTermsTree`

As far as i could debug, the error occurs in the recursive function [`fillWithChildren`](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/editor/src/utils/terms.js#L26-L37), after applying this on the terms, the array will shrink to 1.

**Additional context**
- Gutenberg: 7.5
- WordPress: 5.3.2

This seems also to be related to https://github.com/WordPress/gutenberg/issues/12795 - maybe it is time to avoid rendering such "large" things and adding a select with autocomplete search functionality like e.G. https://react-select.com/home does.

**Comment by Chrico** [comment]
Is there any feedback regarding this? I guess it's not reproduceable, but is there any plan to provide a new SelectControl which behaves more like an autocomplete and searches for typing?

It could occure, that there are a lot of Pages/CPT Posts which need to be rendered. So instead doing multiple requests and splitting up, you can just show the "current selected" and search on staring typing.

**Comment by bobbingwide** [comment]
@chrico We experienced this problem today in a site with just over 140 pages. 
We noticed that the menu_order for each page was 0. 
Changing just one value to a non-zero value seemed to help. 
We chose to set the Front page's menu order to -1. 
This meant it was first in the list so would be returned in the first REST request. 

In my opinion the orderby on the query should include post_parent and name/title

**Comment by noisysocks** [comment]
Hi @Chrico. Could you please provide some steps to follow which demonstrates the problem? I'm not sure how to test it otherwise.

**Comment by Chrico** [comment]
Good morning @noisysocks . Steps are kind of listed in initial issue description: You need a CPT which is hierarchical and >100 Posts in it with "menu_order = 0" (default). When you try to select the "menu_order" it renders not correctly.

**Comment by annezazu** [comment]
@Chrico checking back in on this and am going to close this out for now. Know that we can _easily_ re-open if upon retesting you can re-confirm the issue. Thanks so much!
