### ISSUE TITLE
Block Editor: LinkControl suggestions height consistency, overflow

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20446]
Previously: https://github.com/WordPress/gutenberg/pull/20154#discussion_r378489009, https://github.com/WordPress/gutenberg/pull/20154#issuecomment-591024640

1. The comment at https://github.com/WordPress/gutenberg/pull/20154#discussion_r378489009 alluded that if `white-space` is removed, then we probably should also remove the related `text-overflow` and `overflow` styles.
2. Per @getdave's comment at https://github.com/WordPress/gutenberg/pull/20154#discussion_r380350729, we now no longer have the consistent heights intended with the link suggestions.

These could be considered mutually exclusive. In other words:

- If we want consistent height, then we must restore overflow behavior, with solution to bugginess mentioned by @epiqueras at https://github.com/WordPress/gutenberg/pull/20154#discussion_r380351518
   - Per my screenshots in https://github.com/WordPress/gutenberg/pull/20154#discussion_r378489009, I had not been able to reproduce this.
- Otherwise, we should adjust `text-overflow` and `overflow` styles in accordance with the removal of `white-space`

**Comment by epiqueras** [comment]
When I apply all three properties, this is what I get:

<img width="213" alt="Screen Shot 2020-02-25 at 12 15 21 PM" src="https://user-images.githubusercontent.com/19157096/75283896-8c786e80-57c8-11ea-9861-382902ea74ba.png">

Something with the DOM structure of the component is not letting that work.

**Comment by aduth** [comment]
I haven't yet debugged the cause, but as of current master (i.e. after #20154), I see some strange clipping of search results in LinkControl:

![image](https://user-images.githubusercontent.com/1779930/75287135-d755ae80-57e7-11ea-832f-3e2e6a194751.png)

Note the "URL" tag to the right of the suggestion entry.

Possibly related to this and the original issue, I think we should want to get rid of the explicit width values like these:

https://github.com/WordPress/gutenberg/blob/7c21d2c519be31b18f5bb19d6f576f17c40cf42e/packages/block-editor/src/components/link-control/style.scss#L164

...since it seems like it could contribute to these sorts of issues, and reduce overall reusability of this component outside popover contexts. We should be able to reserve space for the "tag" element just by using some combination of flex styling.

**Comment by epiqueras** [comment]
Figured it out: https://github.com/WordPress/gutenberg/pull/20448.
