### ISSUE TITLE
Turning a list to headings creates <br>

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2044]
Feedback from https://wordpress.org/support/topic/great-example-of-why-developers-are-not-ux-experts/:

> In content creation I often reformat text, for example changing listed items to headings or switching an H2 to an H3 to create a better structure. Gutenberg did not handle this well at all. Turning a list to headings created some hideous heading block with br’s

**Comment by iseulde** [comment]
Should this even be possible? Imho we should remove the transformation, and let the user use copy paste for this? Or should it detach the first item (or even item that has the caret) and transform it into a heading?

**Comment by hedgefield** [comment]
The first thing my mind jumped to was the same idea as @iseulde, selecting the item in question and converting that to a separate heading block, leaving the other list items intact. Although that does present some challenges, such as do we only show the heading buttons when a bit of text is selected? Does the new heading insert above or below the list block? Does the list block split if the item was in the middle?

Maybe a simpler and more logical way would be to still allow the list > heading transformation, but break each list item apart as a separate heading block. I don't know if that's the intended use case, but at least that would make much more sense to me for this transformation than adding all the list items into one heading block, separated by line breaks.
