### ISSUE TITLE
align-self values without flex- prefix

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#20455]
**Describe the bug**

Are `start` and `end` (without the `flex-` prefix) valid values for the `align-self` property?

https://github.com/WordPress/gutenberg/blob/f96c3d478caa423017354a72032af3a3bfb517a9/packages/block-library/src/media-text/style.scss#L18
https://github.com/WordPress/gutenberg/blob/f96c3d478caa423017354a72032af3a3bfb517a9/packages/block-library/src/media-text/style.scss#L32
https://github.com/WordPress/gutenberg/blob/ae05adbdbc5de4eb038210e6ec53408d20910df5/packages/block-library/src/media-text/editor.scss#L9
https://github.com/WordPress/gutenberg/blob/ae05adbdbc5de4eb038210e6ec53408d20910df5/packages/block-library/src/media-text/editor.scss#L23

Aren't they missing the `flex-` prefix? Or are they aliases for the `flex-` values?

**Comment by jorgefilipecosta** [comment]
Hi @mrleemon, thank you for looking into the code and raising this question. According to https://developer.mozilla.org/en-US/docs/Web/CSS/align-self start and end are valid values for align-self and they are different from flex-start/flex-end.

I'm going to close the issue for now, if something is not working as you expect, or you have additional insights feel free to leave a comment.
