### ISSUE TITLE
v0.8.1 of @wordpress/create-block "Minimum system requirements not met!"

### ISSUE THREAD

**Issue by mattwatsoncodes** [WordPress/gutenberg#20450]
**Describe the bug**
With version 0.8.1 of the @wordpress/create-block script, I always get the error "Minimum system requirements not met!"

Node version: v13.8.0
npm version: 6.14.0

Running `npm init @wordpress/block@0.8.0` works fine, so is definitely an issue with the latest version. 

**To reproduce**
1. run `npm init @wordpress/block`
3. "Minimum system requirements not met!" error given

**Expected behavior**
The script should run in interactive mode.

**Screenshots**

<img width="925" alt="Screenshot 2020-02-25 at 21 41 59" src="https://user-images.githubusercontent.com/2066205/75290130-abeab800-5817-11ea-822b-c3c73b532c55.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Terminal: zsh (also tested with bash with same issue)

**Comment by mattwatsoncodes** [comment]
Note that if I have an existing package.json file and run`npm install check-node-version --save-dev` 

Then  if I run `npm init @wordpress/block ` the script does run.  So looks like it could be a missing dependancy.

**Comment by gziolo** [comment]
I was able to replicate this issue. It's very strange. I plan to investigate it further.

**Comment by gziolo** [comment]
Let's try to explicitly pass node and npm versions as proposed in https://github.com/WordPress/gutenberg/pull/20456. I'll publish shortly to npm to see if it helps.

I tried both `npx @wordpress/create-block` and `npm init @wordpress/block` – they fail when commands are executed in a folder without `package.json`. I tested it inside Gutenberg repository after release where it works 🙃

**Comment by gziolo** [comment]
#20456 didn't help. We probably need to use Node API instead.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/pull/20461 - another attempt :)

**Comment by gziolo** [comment]
It works correctly with the latest version: `0.8.3`. Can you confirm on your end?

**Comment by mattwatsoncodes** [comment]
@gziolo I can confirm that it is now working at this end! Thank you :)

**Comment by pisandelli** [comment]
Hello guys! I'm having the same issue but with the latests versions

**Describe the bug**
With current version **0.18.0** of the @wordpress/create-block script, I always get the error "Minimum system requirements not met!"

**Node version**: v14.15.1
**npm version**: 6.14.8
**OS**: Ubuntu 20.10

Running npm init @wordpress/block@0.8.0 seems to work fine (although some `UnhandledPromiseRejectionWarning` errors), while versions 0.8.3 to latest don't (at least for me)

![Screenshot from 2020-12-04 09-05-21](https://user-images.githubusercontent.com/1986634/101164940-93b09080-3614-11eb-9535-dee524465704.png)

**Comment by gziolo** [comment]
> With current version **0.18.0** of the @wordpress/create-block script, I always get the error "Minimum system requirements not met!"
> 
> 
> 
> **Node version**: v14.15.1
> 
> **npm version**: 6.14.8
> 
> **OS**: Ubuntu 20.10

Something has to be wrong with this function:

https://github.com/WordPress/gutenberg/blob/873f94106a11e11bfab0184998421907dc6370c5/packages/create-block/lib/check-system-requirements.js#L15L32

I'm not quite sure though why it would error on your machine.

**Comment by withmukeshjoshi** [comment]
I am getting this error while running npx @wordpress/create-block in terminal. I have node v14 and npm v7 installed already. 
OS: Ubuntu: 20.04

Minimum system requirements not met!
Error: Wanted node version >=12 (>=12.0.0)

![Screenshot from 2021-08-13 19-13-06](https://user-images.githubusercontent.com/43911307/129366259-b8fc3e2a-8ec4-4bd1-bd07-e04100b1c367.png)

**Comment by withmukeshjoshi** [comment]
Note: The issue occurs with the Node v14.17.5 LTS.

After I update my node to v16*, the script started working.

**Comment by heartofeurope** [comment]
I got this error with Node v16.14.0 and after updating to v17.5.0 it disappeared, but I got a different one:

error = new Error(message);
                        ^

Error: Command failed with exit code 2: npm run build
[webpack-cli] HookWebpackError: error:0308010C:digital envelope routines::unsupported
