### ISSUE TITLE
Social icons in the front end miss the accessible attributes

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#20466]
**Describe the bug**

All the SVG icons rendered in the front end by the Social Icons block miss the accessible attributes

`role="img" aria-hidden="true" focusable="false"`

**To reproduce**
- create a post, add a Social Icons block with some icons, publish
- inspect the rendered source in the front end 
- see all the icons misse the above attributes

Note: the SVG icons meant to be used on the front end are hardcoded in the block component `index.php` file. See there the `<svg>` tags miss the required attributes.

**Comment by donmhico** [comment]
Hey @afercia,

Thanks for pointing this out. I've linked a PR in this issue. Can you test it out when you have the time? Thank you!
