### ISSUE TITLE
Theme name in Template Selector

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20469]
It'd be good to display the current theme name in the template selector of `edit-site`.

![image](https://user-images.githubusercontent.com/548849/75366628-4ce07e00-58bf-11ea-9654-11ea284e76a6.png)

**Comment by shaunandrews** [comment]
At the bare minimum, I could see adding a section to the bottom of the menu to display the theme name...

<img width="512" alt="image" src="https://user-images.githubusercontent.com/191598/76107730-49c44c80-5fa7-11ea-91df-d16fb20154d6.png">

...but I'm not entirely sure what purpose this serves. Maybe we can add a preview on hover, and some other options to view the theme details and view all themes:

![Template Menu with Theme](https://user-images.githubusercontent.com/191598/76109070-bf311c80-5fa9-11ea-8855-3634edb2f5e1.gif)

The "Theme details" item probably isn't necessary — selecting the theme name could open the details like we do now in the Themes screen in wp-admin:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/191598/76109232-0ae3c600-5faa-11ea-9dec-d33834d03c4f.png">

I'm not sure if we can use that exact modal within the editor, but I could see adapting that UI. We could look to add more template-related information about the theme here as well.

**Comment by MichaelArestad** [comment]
> It'd be good to display the current theme name in the template selector of edit-site.

@mtias I'm still curious as to why. I'm not sure exactly what purpose this would serve.

**Comment by mtias** [comment]
Right now you cannot tell while in edit site view which theme you have enabled. The templates and template parts come from a mixture of site content (user modified) and theme content. It's important to trace where those are coming from.

**Comment by MichaelArestad** [comment]
> Right now you cannot tell while in edit site view which theme you have enabled. The templates and template parts come from a mixture of site content (user modified) and theme content. It's important to trace where those are coming from.

@mtias Right. Perhaps we can delineate which templates are coming from the theme and show the theme name in conjunction with the template? Perhaps when previewing the template?

**Comment by mtias** [comment]
That's somewhat already in place — all templates come from the theme unless the have the "modified by user" dot as explained here https://github.com/WordPress/gutenberg/issues/19269

**Comment by MichaelArestad** [comment]
@mtias And templates couldn't be added by other sources like plugins?

**Comment by shaunandrews** [comment]
Building on the work from #20470, here's the latest on the theme info (shown in its `:hover` state):

<img width="626" alt="image" src="https://user-images.githubusercontent.com/191598/76452488-9b097d00-63a7-11ea-9ecd-23f573246ea3.png">

**Comment by mapk** [comment]
This hover experience from @shaunandrews communicating the theme visually works really well. I noted that if this hover+preview is used here, it would be great to see it used for the templates in this issue: https://github.com/WordPress/gutenberg/issues/20476

**Comment by johnstonphilip** [comment]
What would show where the theme is, if the template is not part of the theme, but only exists as a `wp_template` post_type?

**Comment by joanrho** [comment]
@shaunandrews  Does this still need design feedback or has a final direction already been decided upon? If so, can you please provide some updated visuals and links to the Figma source files?

**Comment by MichaelArestad** [comment]
@joanrho This works for now and fits with the template previews. Moving to Needs dev.

**Comment by shaunandrews** [comment]
> Does this still need design feedback or has a final direction already been decided upon?

This seems like a mostly straight-foward one, I have nothing more to add design-wise at this point. I'll remove the design feedback label.

Figma file is here: https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=1060%3A0

**Comment by johnstonphilip** [comment]
@MichaelArestad @shaunandrews Any thoughts on this? https://github.com/WordPress/gutenberg/issues/20469#issuecomment-603445859

**Comment by johnstonphilip** [comment]
I also feel like this comment is worth addressing as well:
https://github.com/WordPress/gutenberg/issues/20469#issuecomment-597730143

**Comment by MichaelArestad** [comment]
> What would show where the theme is, if the template is not part of the theme, but only exists as a wp_template post_type?

I would expect nothing to show there. Perhaps, if the template is added by a plugin, it could show the plugin name in place of the theme.

**Comment by ockham** [comment]
I came here via #19252. Going to give this a stab.
