### ISSUE TITLE
Show Template Parts in Flyout Menu (or similar)

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20470]
We should find a more scalable way to show template parts as the dropdown could start growing a lot. Either a flyout menu like:

![image](https://user-images.githubusercontent.com/548849/71202534-bbd89f80-229c-11ea-97d0-10867761ea9b.png)

Or something like splitting the whole panel with tabs (Templates and Parts).

**Comment by MichaelArestad** [comment]
I'm not sure it is necessary to show the template parts in this menu at all. The included template parts can be selected via the navigator or, with some minor changes to the template part blocks, directly in the editor.

Why not use the inserter to add or create a new template part?

**Comment by mtias** [comment]
The selection that occurs from this menu is different since it isolates the template part. It's the equivalent view you'd get by directly loading a single template post type.

**Comment by shaunandrews** [comment]
Here's an updated mockup with the template parts showing in a submenu, along with the template previews (from #20478) and the theme info (from #20469):

![Template Menu](https://user-images.githubusercontent.com/191598/76332795-324ad380-62c7-11ea-9a36-3684007ea24a.gif)

I also tried tabs in the menu, but quickly abandoned it as I found the multiple select/focus states confusing:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/191598/76332936-51496580-62c7-11ea-979f-2481326d1a96.png">

**Comment by shaunandrews** [comment]
One thought on the combination of the template previews, and the template part flyout: The position of these elements is different.

- The previews appear in a fixed position with the hopes of making it easier on your eyes as you scrub between templates.
- The flyout menu appears relative to its parent menu item.

Does this mixing of positions feel ok?

**Comment by shaunandrews** [comment]
Also, thinking a little bit about mobile.

We could make the dropdown a fullscreen modal on small devices, and how the template parts inline:

![Template Menu Mobile - Full Screen](https://user-images.githubusercontent.com/191598/76339435-7393b100-62d0-11ea-990b-8a0d56f92378.gif)

Alternatively, we could keep the dropdown/flyout interaction the same on mobile, repositioning the flyout menu as needed:

![Template Menu Mobile - Flyout](https://user-images.githubusercontent.com/191598/76339500-8e662580-62d0-11ea-943d-ad2b9979532b.gif)

I thought the flyout might be problematic on mobile devices, but when playing with the the above prototype on my phone it actually feels pretty natural.

**Comment by MichaelArestad** [comment]
@shaunandrews Could the template parts flyout show up when hovering over a template?

**Comment by mtias** [comment]
@MichaelArestad list of all so far.

**Comment by MichaelArestad** [comment]
Ah. Thanks for clarifying @mtias. I think we can move forward with the proposals (without tabs) from @shaunandrews.

**Comment by noahtallen** [comment]
Do we have any existing components which handle flyouts? Do we need to create one?

**Comment by mtias** [comment]
Not currently. We need to create one.

**Comment by noahtallen** [comment]
It doesn't look as if the current Popover positioning will be able to handle this style, so I created an issue about improving the API to make it more flexible (#21275). I'm working towards getting a basic flyout working, even if the style doesn't match 100% yet

**Comment by vindl** [comment]
Given that we'll likely be removing the template dropdown and replacing it with navigation sidebar (https://github.com/WordPress/gutenberg/issues/23939), this issue is probably no longer relevant?

**Comment by MichaelArestad** [comment]
@vindl let's keep this open for now, but focus on the sidebar. If we can get that sidebar implemented, we can close this out.

**Comment by mtias** [comment]
This UI has changed quite a bit and is no longer applicable.
