### ISSUE TITLE
Add Block: OpenGraph Link

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2047]
We should have a block whose sole purpose it is to show a standardized OpenGraph box with site icon, title description and link. Kind of like what you see on this page: https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fgithub.com%2FWordPress%2Fgutenberg

The block would be inserted as a placeholder, like the Embed block. When an arbitrary link is pasted in, the block crawls out and fetches the OG data and populates it. 

It would be good to have this be a separate block to the Embed block, as you might want to opengraph link to a youtube video without embedding it.

**Comment by jasmussen** [comment]
CC: @iseulde as I know you're working on oembeds right now (#1033 ), and would love your thoughts and feedback on this idea.

When using oEmbed, you paste a URL on a blank line and press enter. This converts it to an embed. Cool.

What if, when you paste an unrecognized URL — something that's not on the oEmbed whitelist — we crawl out and fetch opengraph data and get an "OpenGraph Card" like the following:

![screen shot 2017-08-04 at 09 45 49](https://user-images.githubusercontent.com/1204802/28959218-bc1c1516-78f9-11e7-87bc-c8633cf3cf07.png)

Wouldn't that be cool?

This could be in addition to an explicit OG block as ticketed here.

**Comment by iseulde** [comment]
So then a URL on a line will always convert to something? I guess this will all have to go through the same endpoint, which would first try to embed with oEmbed, then fall back to OpenGraph, then maybe plain document title, favicon, etc.

**Comment by iseulde** [comment]
In other words, this would still be part of the general embed block, just doesn't have a sub type registered.

**Comment by iseulde** [comment]
Or we need something different for pasting URL, as there we don't know what type the user wants, so we need to do oEmbed => OpenGraph => fallback?

**Comment by jasmussen** [comment]
> oEmbed => OpenGraph => fallback

That _sounds_ right to me. Or perhaps this:

> oEmbed => OpenGraph => plain hyperlink

What do you think?

**Comment by iseulde** [comment]
Yeah, maybe, we can try.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
