### ISSUE TITLE
Make Update Design primary button be contextual

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20471]
When choosing a template part in the template dropdown (and the UI focuses just on that template part) we should update the button text to say `Update {TemplateName}`:

![image](https://user-images.githubusercontent.com/548849/75367041-f758a100-58bf-11ea-9de8-69f8d48250ce.png)

**Comment by shaunandrews** [comment]
Since `TemplateName` may very well be something like `Post` or `Page`, I think having an "Update Post" or "Update Page" button might actually be pretty confusing.

Perhaps it should be more general, like "Update Template" or "Update Template Part" — or even just simply "Save" or "Save changes".

**Comment by noahtallen** [comment]
doesn't the update button open a menu with all of the possible changes? that might be more broad than just a single entity like a "template"

**Comment by youknowriad** [comment]
I think with all the recent updates to the save flow, this issue probably doesn't make sense anymore.
