### ISSUE TITLE
Block Editor: Ungroupable, non-reusable blocks show redundant block settings popover section

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20480]
Possible regression of #19344 (cc @youknowriad, @jasmussen )

![image](https://user-images.githubusercontent.com/1779930/75369480-81d5dc00-5891-11ea-81a3-b7d34c37ef07.png)

**Steps to Reproduce:**

1. Navigate to Posts > Add New
2. Insert Social Icons block
3. Click block settings
4. Observe undesirable blank section between "Duplicate" and "Remove block"

**Suspected cause:**

This section of the block settings normally contains "Add to Reusable blocks" and "Group" options, which leads me to think that we are not correctly omitting the section when a block is neither reusable nor groupable.

Example for paragraph block:

![image](https://user-images.githubusercontent.com/1779930/75369616-c95c6800-5891-11ea-9721-ce398474d0b8.png)

I note that this is a "possible regression of #19344", because I am not able to reproduce this in WordPress 5.4 Beta 3, but I can reproduce it in the latest `master`.

**Comment by gziolo** [comment]
It might be related to https://github.com/WordPress/gutenberg/pull/20233. It has guard clause that checks fills before it renders the wrapper but it might be buggy.
