### ISSUE TITLE
Gutenberg is unintentionally incompatible with WordPress 5.2.x.

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#20484]
**Describe the bug**

Introduced in #17151. Quoting from https://github.com/WordPress/gutenberg/pull/17151#issuecomment-591633757

The [introduction](https://github.com/WordPress/gutenberg/pull/17151/files#diff-620130744b6b73b822a3df609671d930) of `gutenberg_extend_settings_image_dimensions` **breaks Gutenberg in WordPress 5.2.x**, due to the call to `wp_get_registered_image_subsizes`, a function [introduced in 5.3.0](https://github.com/WordPress/WordPress/blob/ac9b6fcef88b8de83ed551fa60e2e2d3cdf4e51e/wp-includes/media.php#L879-L888).

The Gutenberg plugin [requires WordPress 5.2.0+](https://github.com/WordPress/gutenberg/blob/d026d5b5c189e85bf1bb83321a74494c664e0159/readme.txt#L3). We should either bump that to 5.3.0, or guard against missing `wp_get_registered_image_subsizes` in `lib/client-assets.php`.

**Comment by youknowriad** [comment]
If there's no easy alternative and since WP 5.4 is very close, we can consider updating the minimum version required by the Gutenberg plugin to 5.3.

**Comment by jorgefilipecosta** [comment]
Yes to me it seems we should update the minimum version on the plugin.

**Comment by mcsf** [comment]
Follow-up PR: #20628
