### ISSUE TITLE
Storing Post Meta with a Block is not working anymore (WordPress 5.4 beta)

### ISSUE THREAD

**Issue by them-es** [WordPress/gutenberg#20494]
This bug only seems to be related to WordPress 5.4 (beta) as it can't be reproduced on WordPress 5.3 (stable).

**Steps to reproduce the behavior:**
1. Create a simple meta block based on the following tutorial: https://developer.wordpress.org/block-editor/tutorials/metabox/meta-block-1-intro/
2. Add some text to the _TextControl_ and save the post
3. Reload the page and notice the empty _TextControl_
3. The post meta key/value can't be found in the database

**Desktop:**
 - OS: macOS
 - Browser: Chrome/Firefox
 - Version: latest stable versions
 - Theme: TwentyTwenty

**Additional context:**

Working 😀
- WordPress 5.3.2
- WordPress 5.3.2 + Gutenberg 7.6

Not working 🙁
- WordPress 5.4 beta3
- WordPress 5.4 beta3 + Gutenberg 7.6

**Comment by aduth** [comment]
In implementing a fix, there exists an end-to-end test which is intended to be capturing issues with this behavior. It should be updated to account for whatever is lacking to have caught whichever regression exists in meta behavior.

- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/plugins/meta-attribute-block.php
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/plugins/meta-attribute-block/index.js
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/plugins/meta-attribute-block.test.js

**Comment by aduth** [comment]
I confirmed the bug. It appears to specifically affect blocks where the JavaScript which registers the block in the editor is enqueued earlier than the editor itself.

A fix is proposed at: #20544

An interim workaround can be to change your script enqueue to take place in the footer (the [fifth argument `$in_footer` of `wp_enqueue_script`](https://developer.wordpress.org/reference/functions/wp_enqueue_script/)).

**Comment by them-es** [comment]
Thank you for fixing that bug so quickly and for providing a workaround. Adding the `true` parameter in `wp_enqueue_script` is working as intended!
