### ISSUE TITLE
Inserting new blocks after HTML Blocks (In Group Blocks) is virtually impossible

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#20500]
**Describe the bug**
Inserting new blocks after HTML Blocks (In Group Blocks) is virtually impossible

**To reproduce**
1. Go to 'https://wordpress.org/gutenberg/'
2. Insert a Group Block
3. Insert a HTML Block
4. Try inserting any block after the HTML block (the block should stay in the group and not outside).

**Expected behavior**
A + or placeholder after the HTML block to add new blocks. I can add a new block below the group. But not within the group!

**Screenshots**
![27-02-_2020_14-12-28](https://user-images.githubusercontent.com/9355398/75448535-ac946300-596b-11ea-9576-9e9950573bc4.gif)

And other exampel:

![27-02-_2020_13-29-57](https://user-images.githubusercontent.com/9355398/75448505-a1413780-596b-11ea-93e0-7e8d1dba2370.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version latest version

**Additional context**
- Please add the version of Gutenberg you are using in the description. Wordpress 5.3
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
duplicate of #17837
