### ISSUE TITLE
Syntax Error in the `useHTMLClass` causes Unexpected Error in older Safari

### ISSUE THREAD

**Issue by cwood821** [WordPress/gutenberg#20504]
**Describe the bug**
A Syntax Error in the `useHTMLClass` hook causes the editor to show recovery options. I'm seeing this on Safari 12.1.1 on Mac OS Mojave. Coworkers on newer Safari (13+) do not have the same error.

The syntax error [right here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/editor-skeleton/index.js#L16) where the selector is missing a closing `)` seems to be the root problem. Other browsers evaluate that selector without error, but older versions of Safari do not.

**To reproduce**
This specifically applies to WordPress 5.4 Beta 2 on older versions of Safari.

1. Go to Add New Post in Safari 12.1.1 (or earlier version)

**Expected behavior**
Rendered Gutenberg editor should show

**Screenshots**
![unexpected_error](https://user-images.githubusercontent.com/7462489/75470184-ea868c80-5955-11ea-9e59-106e48128696.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 
 - Browser: Safari 
 - Version: 12.1.1 

**Smartphone (please complete the following information):**
- Have not tested on mobile Safari

I'd be happy to open a PR, but would need some guidance on base and target branches.

**Comment by aduth** [comment]
Introduced in #20245 (cc @jorgefilipecosta)

**Comment by aduth** [comment]
Pull request: #20507
