### ISSUE TITLE
Clicking preview multiple times causes the autosave revision to be created and deleted repeatedly.

### ISSUE THREAD

**Issue by Inwerpsel** [WordPress/gutenberg#20505]
**Describe the bug**
Click the preview button multiple times in a row, without making any changes to the post in between. This will result with the autosave revision being created and destroyed repeatedly (check the response of the api request that does the autosave, it alternates between 200 and 400).

**To reproduce**
1. On any post, save it and don't make any changes after that
2. Click on the preview button.
3. Notice the browser sends a request to `/wp-json/wp/v2/post_type/{id}/autosaves` that gets a 200 response code.
4. Click on the preview button again.
5. Notice the same requests as above is sent, however now this requests gets a 400 response code.
6. You can now repeat steps 2 to 5 indefinitely and the response code will keep on alternating between the two.
7. Check the database between the steps and notice how a record in the wp_posts table keeps being created and deleted, each time bumping the ids of the table.

**Expected behavior**
Clicking the preview button multiple times without any changes to the post should not create a record more than once.

Perhaps this is something that should be fully tackled on the backend side, however maybe a solution/mitigation in the gutenberg editor is possible here? For example the editor could not send the request in the first place when pressing the preview button consecutively.

**Additional context**
- Opened a core bug for the rest API endpoint https://core.trac.wordpress.org/ticket/49532#ticket

**Comment by annezazu** [comment]
@Inwerpsel is this still an issue? I ask after seeing your PR merged: https://github.com/greenpeace/planet4-master-theme/pull/1026 I tried to replicate but wasn't able to with Gutenberg 9.8.3.

**Comment by Inwerpsel** [comment]
> @Inwerpsel is this still an issue? I ask after seeing your PR merged: [greenpeace/planet4-master-theme#1026](https://github.com/greenpeace/planet4-master-theme/pull/1026) I tried to replicate but wasn't able to with Gutenberg 9.8.3.

We didn't have the issue anymore after the workaround we did (which so far has worked well for us). I have to catch up again with the issue, will let you know more soon. Probably it's indeed fixed by changes to autosaving and previewing that happened in the meanwhile.

**Comment by annezazu** [comment]
Thanks @Inwerpsel! I'm going to close this out for now but please feel free to re-open if the problem recurs.
