### ISSUE TITLE
Adding icon is misaligned with button block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20513]
It might be nice to show the adding icon a little centrally aligned for the button block. Currently, you can see the following:

![misalignedbuttons](https://user-images.githubusercontent.com/253067/75484681-3e559d80-5977-11ea-8d15-362bc715f1e2.png)

Possible solutions are:

- Centrally align.
- Reduce height of the button.

I feel the first option might be best.

**Comment by marekhrabe** [comment]
Alignment sounds like a good start 👍

If we manually match the inserter button height to other buttons, it's still likely that a theme style override will put them out of sync again, right? 

Would it be too crazy to style the appender using the same classes as the button? It will definitely solve them being in line but I'm not sure what's the current take of differentiating editor UI and content.

**Comment by mtias** [comment]
The appender should not have that outline.

**Comment by karmatosed** [comment]
Closing as this is now fixed in the latest version.

![image](https://user-images.githubusercontent.com/253067/80383044-fbdb0f00-889a-11ea-92e2-ffeba9f3177c.png)
