### ISSUE TITLE
How do I test for "emptiness" of "falseness"

### ISSUE THREAD

**Issue by trev-dev** [WordPress/gutenberg#20518]
Search first! Your issue may have already been reported.

Hey there.

I have a basic input field that's supposed to hold a string type attribute with a default of `''`

However if I log the empty input, the log shows <empty string> and the conditional content that should show up when there is _not_ an empty string still renders when it's empty.

How do we test for empty attributes the "Gutenberg Way". Why does Gutenberg have to diverge from normal react patterns so much?

Thanks.

**Comment by swissspidy** [comment]
Could you please share your code?

I‘m sure it‘s just a JS issue and not one with Gutenberg.

**Comment by marekhrabe** [comment]
Also happy to look at a code example and help figuring out what's happening.

**Comment by trev-dev** [comment]
@swissspidy Absolutely. Here it is:

```javascript
	attributes: {
		buttonText: { type: 'string', default: '' },
		buttonHref: { type: 'string', default: '' },
		bottomText: { type: 'string', default: '' }
	},
	edit: function({ attributes, setAttributes, className }) {
		const columnsTemplate = [
			['sherman-blocks/split-columns-inner', {
				position: 'Left'
			}],
			['sherman-blocks/split-columns-inner', {
				position: 'Right'
			}]
		];

		const allowedBlocks = ['sherman-blocks/split-columns-inner']

		const {
			buttonText,
			buttonHref,
			bottomText
		} = attributes;

		const updateProps = (val, prop) => {
			console.log(val, prop);
			setAttributes({
				...attributes,
				[prop]: val,
			});
		};

		return (
			<div className={className}>
				<h1>Fancy two column table</h1>
				<hr />
				<InnerBlocks
					template={ columnsTemplate }
					allowedBlocks={ allowedBlocks }
					templateLock="insert"
				/>
				<div>
					<h2>Add bottom content?</h2>
					<label htmlFor="bottomText">Add text to the bottom of the 2 columns? </label>
					<br />
					<RichText
						tagName="div"
						onChange={ val => updateProps(val, 'bottomText') }
						value={ bottomText }
						placeholder="Text for Bottom of 2 Columns"
					/>
					<label htmlFor="column_bottom_text">Add a button to the bottom?</label>
					<br />
					<input
						type="text"
						value={ buttonText }
						onChange={ e => updateProps(e.target.value, 'buttonText') }
						placeholder="Button Text"
					/>
					<input
						type="text"
						value={ buttonHref }
						onChange={ e => updateProps(e.target.value, 'buttonHref') }
						placeholder="Button Link"
					/>
				</div>
			</div>
		);
	},
```
What you're looking at is the two input elements near the bottom and the updateProps function. If I console.log the `val` passed in, I can see the string update letter for letter, and when it's empty, it's not falsy, and the console reads _\<empty string\>_

I've attempted testing explicitly for `''` as well.
Please excuse the wild tabbing whitespace

**Comment by ajlende** [comment]
@trev-dev Thanks for sharing some of your code!

I tried it out and, both `!val` and `val === ''` evaluated to `true` for me when the string was empty. The _\<empty string\>_ message is just what the browser prints so you know that you have an empty string instead of just an empty log.

I didn't see where you are evaluating the conditional you mentioned. Maybe the problem could be there?

**Comment by trev-dev** [comment]
Thanks @ajlende - I noticed this _<empty string>_ message is a console message that I can replicate anywhere an empty string occurs now. I'm fairly sure I didn't put the conditional in the example, but I'll take a closer look at my work. Thank you :)
