### ISSUE TITLE
[ Latest Posts ] Appending "Read More" to the excerpt is inconsistent with some default themes

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/gutenberg#20510]
**Describe the bug**
When the excerpt is enabled in **Post content settings**, the block [attempts to check](https://github.com/WordPress/gutenberg/blob/release/7.6/packages/block-library/src/latest-posts/index.php#L90-L95) if the default `&hellip;` that is appended to trimmed excerpts has been modified. If not, it appends a "Read More" link to the end of the excerpt. The problem is, the substring that it's looking for is not accurate for determining if modification has already happened. This causes unintended behavior in some default themes:

* Twenty Sixteen, Twenty Seventeen, and perhaps some others, modify `excerpt_more` with their own "Continue Reading" link, but still use `&hellip;` as well, so this causes there to be two separate, redundant links at the end of each excerpt.
* Twenty Nineteen and Twenty Twenty don't modify the default `excerpt_more` at all, but this also isn't detected correctly by Latest Posts, because the default string is `'[&hellip;]'`, while Latest Posts is looking for `' &hellip; '` (note the spaces). So in these themes, the excerpts don't get any "Read More" link at all, though it seems like the intention is that they should.

**To reproduce**
1. Publish a couple of posts with a significant amount of content (so it will get trimmed for the excerpt).
1. Add the Latest Posts block to a page. In **Post content settings**, turn on Post content, and then ensure that the Excerpt is the type of content to show.
1. With Twenty Sixteen activated, view the page. It will show something like `… Continue readingRead more` at the end of each post. Note that this isn't what is shown in the block preview.
1. With Twenty Twenty activated, view the page. Each post excerpt will have `[...]` at the end, but no "Read More" link. Note that this isn't what is shown in the block preview.

**Expected behavior**
Ideally, I think, the Latest Posts block would make a `has_filter` check on `excerpt_more` and skip appending anything if that returns `true`, rather than checking for an arbitrary string.

**Screenshots**

Twenty Sixteen frontend:
![2016_frontend](https://user-images.githubusercontent.com/916023/75481561-1c98ee00-5958-11ea-86f1-42e1a60d0481.jpg)

Twenty Sixteen editor:
![2016_editor](https://user-images.githubusercontent.com/916023/75481602-2a4e7380-5958-11ea-8de3-5f49cdbe2af5.jpg)

Twenty Twenty frontend:
![2020_frontend](https://user-images.githubusercontent.com/916023/75481645-3d614380-5958-11ea-9bd2-4543a1c1a054.jpg)

Twenty Twenty editor:
![2020_editor](https://user-images.githubusercontent.com/916023/75481677-46eaab80-5958-11ea-8233-16d08f806430.jpg)

**Desktop**
 - OS: macOS Catalina
 - Browser: Firefox 73
 - WP: 5.3.2
 - Gutenberg: 7.6.0

**Comment by skorasaurus** [comment]
I'm also encountering this in our custom theme and would like advise on what I should expect to be used; I too expected that excerpt_more would be used or 

Using the `'the_content_more_link` hook would also enable a developer to customize the by adding link classes.

**Comment by draganescu** [comment]
Related to #20511, in #20541 I removed the appending of read more by the `LatestPosts` block. That link should be there only if added by the result of running `get_the_excerpt`.

What do you think of this solution?

Also, an important question: how could the block be aware of what the theme does to that "read more" text?

**Comment by coreymckrill** [comment]
> What do you think of this solution?

I think that's a good idea, for the appending to only happen within the filter.

> how could the block be aware of what the theme does to that "read more" text?

I don't think there's a perfect solution to this, but what I mentioned above in the ticket might get pretty close: use `has_filter( 'excerpt_more' )` to see if anything at all is hooked to it. If so, it seems like a fairly safe assumption that we shouldn't append a link.

**Comment by skorasaurus** [comment]
Thanks for the PR and as much as I don't want to unnecessarily block progress (and your PR solves the problem for my custom theme), [this PR](https://github.com/WordPress/gutenberg/pull/20541/commits/cdeee6f9185270c3d42076c42cab6e2cd9b647b0) does have a blocker: 

Gutenberg now ignores the [excerptLength](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/edit.js) that is configured by the user within the block's inspector control. 

The excerpt length on the front end (the render block viewed by the user) is now always 55, the default for an excerpt](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/formatting.php#L3804) regardless what the user sets when they edit the block.

**Comment by skorasaurus** [comment]
I think your PR brings up an important point in that, which trade-offs should we accept and what should be the accepted practice(s) for creating and modifying excerpts in Gutenberg. 

There may have been good rationale why the twentytwenty developers decided to move away from the old practice but [the older way that appended links to excerpts](https://github.com/WordPress/gutenberg/issues/20511#issue-572335250) that Corey indicated earlier was far more accessible for assistive technology users as it included the context for the link by appending the title of the page to the link. 

Additionally by hard coding the 'read more' in the latest posts block, theme developers aren't able to either modify that without extensive hacking of using regular expressions to search and replace of  read more text. 

Modifying the text at the end of an automatically generated excerpt has been possible through the [excerpt_more](https://developer.wordpress.org/reference/hooks/excerpt_more/) hook and you can modify the by appending text/html through the get_the_excerpt hook.

**Comment by azaozz** [comment]
https://github.com/WordPress/gutenberg/pull/20541 looks good for fixing [this edge case](https://github.com/WordPress/gutenberg/issues/20511), and partially fixes this issue. 

When the option to display "Post content" is turned on it seems to mix two different WP features: post excerpts and the `<!--more-->` tag. It's true that the same mixing can also happen in themes, but there it can be handled better.

Thinking it's worth it revisiting/improving how the "Post content" option is handled. Seems better to use a consistent, auto-generated, text only excerpts that will also respect the length set by the user.

**Comment by allykmyta** [comment]
A report was made about this here: #3034519-zen
I was able to replicate this issue on my own (launched) atomic site with the default theme Twenty Twenty and Gutenberg version 8.2.1

**Comment by jorgefilipecosta** [comment]
Given that https://github.com/WordPress/gutenberg/pull/20541 was merged, could we close this issue? @draganescu

**Comment by draganescu** [comment]
I think so yes.
