### ISSUE TITLE
Block Types registered with no attributes end up "sharing" attributes list.

### ISSUE THREAD

**Issue by dougwollison** [WordPress/gutenberg#20524]
**Describe the bug**
If you register block types with no attributes (not an empty list; if you leave out the attributes key entirely), they will "share" an attributes list should any of them be modified by filters.

**To reproduce**
1. Register a block type, leave out the attributes entry.
2. Register a second block type, same way, but with a support like `align` specified.
3. Check the resulting WPBlock objects, the first one now has the `align` attribute, and an equality check confirms that the attributes list is the same object on both.

**Expected behavior**
The first block should not have the `align` attribute registered.

**Additional context**
Tested on WordPress 5.3.2 with and without the Gutenberg plugin.

-----

A use case would be if you're registering multiple simpler block types that legitimately doesn't need unique attributes (such as a custom grouping/wrapping block), but supports features that add attributes to that block type during registration (such as align or a custom feature).

I'm currently getting around this by adding an explicit empty attributes list to all my block definitions. The other option is to have my filters that add attributes simply assign to a new object every time, but that wouldn't prevent issues caused by the hooks in the block-editor package.

This issue could also apply to the keywords list, since any blocks that don't register one end up "sharing" the same array, but filters adding keywords to blocks is a pretty niche sitation.

The issue is due to `DEFAULT_BLOCK_TYPE_SETTINGS` being defined with the empty attributes object and keywords array, rather than the defaults being delared on each call of registerBlockType (though doing it that way probably causes it's own hiccups/annoyances).

**Comment by marekhrabe** [comment]
Defaults are indeed reused between blocks. Filters can get around this by treating the objects as immutable and returning a new ones if there is need to edit one of them or, as you have done, passing empty attributes as an empty object to prevent the usage of the default one.

I agree think this should be updated in the block registration so each block will get their own defaults that are not shared and there will be no surprises.

**Comment by marekhrabe** [comment]
For now, I have added a failing test in #20565, I'll work on the fix later.

**Comment by dougwollison** [comment]
> Filters can get around this by treating the objects as immutable and returning a new ones if there is need to edit one of them or, as you have done, passing empty attributes as an empty object to prevent the usage of the default one.

Seems the latter method is what's "recommended" right now, since the align hook doesn't return a new attributes object and blocks like buttons and social-links one register empty attributes. But in that case the documentation should suggest that as best practice.
