### ISSUE TITLE
Allow going down to the editor from the post title using keyboard

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2052]
You can navigate through blocks using the keys, not on from the post title. It'd be nice to support that.

----

Sort of related, I bring back the idea of post-title being a real block that is fixed to the top. The the permalink can be done using regular toolbars, and we could have block inspector show related things.

**Comment by westonruter** [comment]
Re: post title being a block, see #1914.

**Comment by iseulde** [comment]
So should it be a block? That makes sense to me. In that case this issue will be automatically fixed. Happy to create a block for it.

**Comment by westonruter** [comment]
I think it also depends on introducing the concept of block locking: the post title block should be fixed to the top of the content and not able to be moved once it is added. Something similar is needed for the excerpt block (#1288). The other consideration is that this block should not be available if the post type does not have `title` support, and if it _does_ have support, should the title block be always added by default? I would assume so the title, but I would assume the excerpt block would not be added by default (and then in that case, blocks need a way to determine whether or not their respective `source` is populated and if so, whether they should display regardless. I had some more thoughts on this in #1754.

**Comment by aduth** [comment]
This issue encompasses two tasks. Arrow navigation is already satisfied by #2424.

**Comment by jasmussen** [comment]
Can we close this? I can move down using arrowkeys.

**Comment by mtias** [comment]
Yes, done.
