### ISSUE TITLE
List: unordered should be the default

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2053]
By default, Lists are set with ordered format, but it is the second option on the toolbar.

![image](https://user-images.githubusercontent.com/548849/28671463-18f020d4-72dd-11e7-80f4-63194da3a58b.png)

Let's make unordered the default instead.

**Comment by EphoxJames** [comment]
Easily fixed. :-)

**Comment by EphoxJames** [comment]
Fix should now be in master. Closing issue.

**Comment by mtias** [comment]
Thanks!
