### ISSUE TITLE
Navigation Block: Add support for a dynamic home URL

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#20542]
Today, when you add a homepage menu item in the Navigation Block, this gets mapped directly to that page's ID & URL. For example: 

```
<!-- wp:navigation -->
<!-- wp:navigation-link {"label":"Home","id":1837,"url":"https://wordpress.test/?page_id=1837"} /-->
<!-- /wp:navigation -->
```

This is fine for a single site, but when the navigation block is used in a theme template or template part (or even in a block pattern), we'll want a way to have a homepage link dynamically map directly to the site's homepage, via something like [`home_url()`](https://developer.wordpress.org/reference/functions/home_url/).

**Comment by mtias** [comment]
Absolutely. This is also related to the tasks of removing the url attribute for site resources.

**Comment by bobbingwide** [comment]
I took a pragmatic approach to this problem in https://github.com/bobbingwide/fizzie/issues/22
I intercept the navigation link block, adjust the attributes, then call the original rendering function.

In my theme I've left the hardcoded string as originally coded. 
eg
```
function fizzie_render_block_core_navigation_link( $attributes, $content, $block ) {
    $attributes = fizzie_nav_atts( $attributes );
    $html = gutenberg_render_block_core_navigation_link($attributes, $content, $block);
    return $html;
}

function fizzie_nav_atts( $attributes ) {
    $attributes['url'] = str_replace( 'https://s.b/wp56', site_url(), $attributes['url'] );
    return $attributes;
}
```

**Comment by mtias** [comment]
I think we should create a special block variation of `Link` that is `Home`, showing up as such in the inserter.

**Comment by gwwar** [comment]
@priethor were you still working on this one?

**Comment by priethor** [comment]
I kind of am. I expect to retake it in a few days as it's a good first issue but can of course pass it along as soon as it starts becoming a blocker. 👍

**Comment by gwwar** [comment]
Sounds good @priethor 👍 Let us know if anything changes.

**Comment by mtias** [comment]
Where are we with this one?

**Comment by priethor** [comment]
I was exploring this last week, and my first impression is that a block variation might not be the best solution, as the block would better be a dynamic one so that the link stays in sync with the home URL whenever it's changed in the settings. Also, it would require a different workflow and state handling than normal links as it would never be empty and would not require placeholder states, for example.

In any case, as the need for this feature becomes more prominent, I think it's about time for me to unassign the issue and let somebody focus on it and truly bring it forward.

**Comment by gwwar** [comment]
As an FYI these two landed, so another navigation link variation + some custom handling should do the trick.
https://github.com/WordPress/gutenberg/pull/29095
https://github.com/WordPress/wordpress-develop/pull/1015

Folks should also be aware of the following issue in the navigation editor:
https://github.com/WordPress/gutenberg/issues/29793

**Comment by priethor** [comment]
Thanks @gwwar , those changes simplify the Home variation, indeed! 💯

**Comment by mtias** [comment]
Curious why this one needs to be a variation instead of just its own block as a wrapper for `get_home_url`?

**Comment by gwwar** [comment]
> Curious why this one needs to be a variation instead of just its own block as a wrapper for get_home_url?

It's own block would work too.

**Comment by mtias** [comment]
I'd say a separate block makes more sense since we don't need any of the UI to set a custom link.

**Comment by priethor** [comment]
>we don't need any of the UI to set a custom link

I started exploring the block variation based on previous comments on the issue, but because of not needing any of the UI, I find a separate block would keep it simpler and wouldn't violate the open-closed principle.

**Comment by gwwar** [comment]
@priethor was there a PR here to help review?

**Comment by priethor** [comment]
There isn't, I explored the variation but didn't proceed with the new block @gwwar. It's open to being picked among the Navigation block priorities.
