### ISSUE TITLE
Editor fails with new plugin

### ISSUE THREAD

**Issue by programmin1** [WordPress/gutenberg#20556]
**Describe the bug**
I just got a bug editing a post I just edited yesterday with latest Gutenberg editor. After disabling "Gutenberg" plugin normal gutenberg can edit it fine.

**Expected behavior**
Gutenberg should work like gutenberg

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 73.0.1

It gives the following error to copy:
As/</<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=241345a79547bcd17b5c2c78b839ed72:49:273323
As/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=241345a79547bcd17b5c2c78b839ed72:49:273283
Vb@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:104:431
Xi@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:151:136
unstable_runWithPriority@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react.min.0212dc62.js?ver=16.9.0:26:340
Ma@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:52:280
Yb@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:150:420
O@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:120:254
ze@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:118:14
mg/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:53:49
unstable_runWithPriority@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react.min.0212dc62.js?ver=16.9.0:26:340
Ma@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:52:280
mg@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:52:498
V@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:52:431
Sb@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:213:96
Mg@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:85:82
e@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:23173
Me/</t<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:23257
o/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:17407
o@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:17379
B/b</<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:14612
p@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:7240
s/</</<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:9734
x/</<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:8634
A/</</<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:9069
dispatch@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/data/index.js?ver=32d9234b375464a49b690601fa7de56c:1:8365
n@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:9409
e/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5201
e@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5176
u/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5130
360/r.any@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5727
e/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5201
e@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5176
u/<@https://howtotrainyourrobot.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=a85028ba25a9f2cb5f04967557099f8e:1:5124

**Comment by jorgefilipecosta** [comment]
Hi @programmin1, thank you for reporting this issue.
Do you have any plugins installed that interact with the editor?
What theme are you using?
Does the error happens when creating a new empty post, or happens when editing a specific post?

**Comment by karmatosed** [comment]
I haven't seen any other reports of errors like this,  so for now going to close this. If you are still experiencing this issue it can be reopened.
