### ISSUE TITLE
Appender element in non-edited, placed reusable blocks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20558]
**Describe the bug**
The appender element (with `block-list-appender` class) is added to placed, reusable blocks that aren't even currently edited. This results in a transparent vertical space at the bottom of the reusable block, which causes visual vertical gaps between blocks.

**To reproduce**
1. Insert a new block, make it reusable or place a reusable block.
2. Notice that there is now a visual space at the bottom of that reusable block. Upon careful inspection of the elements inside the reusable block, one notices it is the appender element.

**Expected behavior**
The appender element in a reusable block is only inserted/displayed when it is actually added (where it makes sense).

**Comment by adamziel** [comment]
I have tested this and discovered there is in fact some vertical spacing between the reusable blocks and other blocks. However, the appender block remains invisible. The root source of the problem is `WritingFlow` component which nested in reusable blocks. It has `display` CSS property set to `flex`, which breaks collapsing the `margin-top` from the bottom block into `margin-bottom` of the top block. Once `display: flex` is removed, the spacing is gone.

*Before:*

![image](https://user-images.githubusercontent.com/205419/75673931-5f263780-5c84-11ea-8079-528fdca3ae61.png)

*After:*

![image (1)](https://user-images.githubusercontent.com/205419/75673945-664d4580-5c84-11ea-8961-68689b9fb531.png)

The question here is - is this extra spacing intentional? Should it be there? I'll `needs design feedback` so we can get more input

**Comment by strarsis** [comment]
@adamziel: When the appender element is hidden (of unedited blocks) using CSS, empty space below the block is disappearing, you can try it yourself by adding these styles:
```css
.components-disabled .block-list-appender {
  display: none;
}
````

**Comment by adamziel** [comment]
@strarsis The extra spacing is definitely there:

<img width="604" alt="Zrzut ekranu 2020-03-4 o 11 45 22" src="https://user-images.githubusercontent.com/205419/75872259-2023ed80-5e0e-11ea-8ea4-72f0edd72283.png">

 When I inspect the appender, it looks like this:

<img width="870" alt="Zrzut ekranu 2020-03-4 o 11 47 18" src="https://user-images.githubusercontent.com/205419/75872230-15695880-5e0e-11ea-85c0-031b954a985e.png">

However, adding the CSS rule doesn't seem to fix it:

<img width="1053" alt="Zrzut ekranu 2020-03-4 o 11 47 58" src="https://user-images.githubusercontent.com/205419/75872240-1a2e0c80-5e0e-11ea-8e24-f52f9145cb05.png">

I even tried removing all appender elements but no dice as well. Only when I remove `display: flex` from `.block-editor-writing-flow` the extra spacing disappears as vertical margins are getting collapsed into previous and next blocks:

<img width="1085" alt="Zrzut ekranu 2020-03-4 o 11 48 28" src="https://user-images.githubusercontent.com/205419/75872247-1b5f3980-5e0e-11ea-8302-a7f11297b535.png">

Hence I wonder, if it was added intentionally to indicate that reusable block is different from other blocks. For example, when I select it, here's how it looks like:

<img width="736" alt="Zrzut ekranu 2020-03-4 o 11 52 44" src="https://user-images.githubusercontent.com/205419/75872573-b48e5000-5e0e-11ea-811e-99ff7ac5fce6.png">

Design feedback appreciated!

**Comment by strarsis** [comment]
Does this [PR](https://github.com/WordPress/gutenberg/pull/20753) fix this issue? It seems to be related?

**Comment by noisysocks** [comment]
This seems OK to me now.

Not selected:

<img width="1552" alt="Screen Shot 2020-04-21 at 14 14 24" src="https://user-images.githubusercontent.com/612155/79824796-7824ac80-83da-11ea-9e67-55680926ba74.png">

Selected:

<img width="1552" alt="Screen Shot 2020-04-21 at 14 14 27" src="https://user-images.githubusercontent.com/612155/79824805-7bb83380-83da-11ea-8ad8-ada7c2210cc2.png">

There's some extra padding at the top when the block is selected but I think this is desirable as it creates spacing in between the reusable block toolbar and the reusable block content.
