### ISSUE TITLE
Reusable blocks post type has no admin menu item

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20557]
**Describe the bug**
The reusable block post type has no admin menu item, hence when editing a reusable block post, there is no way getting back to the reusable block post type list, one has to resort to the browser back button.

**To reproduce**
1. Edit a reusable block.
2. Notice that there is no reusable blocks menu item in as it would be usually the case. Also notice that there is no way getting back to the list without using the browser back button.

**Expected behavior**
The reusable blocks post type should have its own admin menu item as other post types usually have.

**Additional context**
Related to https://github.com/WordPress/gutenberg/issues/20551.

**Comment by karmatosed** [comment]
Just to clarify what you are looking for here @strarsis. right now there is a way to view all reusable blocks and then you can see in list. Is there a different path you would prefer?

**Comment by strarsis** [comment]
@karmatosed: It would be nice to have a better way getting to that list than using the inserter and multiple steps.

**Comment by strarsis** [comment]
The [Reusable Blocks Extended](https://wordpress.org/plugins/reusable-blocks-extended/) plugin adds these features (and some). It would be nice to have this in Gutenberg core.

**Comment by carolinan** [comment]
Related/ Duplicate: https://core.trac.wordpress.org/ticket/51534

**Comment by kathrynwp** [comment]
I'm going ahead and closing out this issue, since the corresponding ticket was closed in Core Trac over a year ago, with the following comment:

> I am going to close this one out as a maybelater. While this is a good idea, there are other things that need to be considered and adjusted before this can be explored further. Discussion is always encouraged to continue on maybelater tickets, and it can be reopened at any time.
