### ISSUE TITLE
Tags are not saving on wordpress Posts

### ISSUE THREAD

**Issue by Deadsell25** [WordPress/gutenberg#20553]
Hey, i have a problem when i try to add TAGS on posts.
When i write tags and put more with space OR , the post doesnt save the TAGS.
So when i write like 3 tags it maybe save one or 0 tags

Whats the problem how i can fix this?

**Comment by draganescu** [comment]
Howdy @Deadsell25 :) 

I can confirm some inconsistencies in saving tags using the `master` branch of the Gutenberg plugin. 

![tag-issues](https://user-images.githubusercontent.com/107534/75621473-7a6a4780-5b9d-11ea-936a-1d1cd66d7671.gif)

On stock WordPress installs tags work as expected.

**Comment by Deadsell25** [comment]
so how can we fix this issue?

**Comment by jorgefilipecosta** [comment]
Hi @draganescu, is the problem happening on wordpress/trunk (WordPress 5.4)?

**Comment by draganescu** [comment]
@Deadsell25 it appears that the issue has been solved in the mean time (it was probably a side effect of some other bug). I have tested both the upcoming WordPress 5.4 RC and the current Gutenberg master and the tags work all right. 

I will therefore close this issue, thank you for reporting!
