### ISSUE TITLE
Corrupted save_post-hook when saving a post.

### ISSUE THREAD

**Issue by markvanwijnen** [WordPress/gutenberg#20550]
**Describe the bug**
When in your WordPress theme you hook into the save_post-hook and try to get the current permalink or terms you end up with getting the previous one and not the actual one. When using Gutenberg to save/update a post. This issue does not occur in Quick Edit, or when you have Custom Fields enabled, or when you add a custom meta box.

**To reproduce**
1. Start with clean hosting and database.
2. Install [WordPress](https://nl.wordpress.org/download/) (v5.3.2)
3. Create a new theme folder and name it "Sample".
4. Insert a blank "index.php" file.
5. Insert a "style.css" file with the following contents:
```
/*
Theme Name: Sample
*/
```
6. Insert a "functions.php" file with the following contents:
```
add_action( 'save_post', 'custom_save_post', 10, 3 );
function custom_save_post( $post_id, $post, $update ) {
    file_put_contents( get_template_directory() . '/log-permalink.txt', get_permalink( $post_id ) );
}
```
7. Create a couple of categories.
8. Change permalink to **Custom Structure:** /%category%/%postname%/
9. Update the default Hello World-post or create a new one. Make sure to select a category.

**Expected behavior**
For example, you have two categories: Fruit (1) and Vegetables (2) and the post is titled "Hello World". When you select Fruit as the category you will see the permalink is changed to `fruit/hello-world`. However if you look in the `log-permalink.txt` file in your theme directory. You will notice it is called `no-category/hello-world`. 

Now if you unselect Fruit and select Vegetables notice how the permalink is changed to `vegetables/hello-world`. However if you now look in the `log-permalink.txt` file in your theme directory. You will notice it is called `fruit/hello-world`.

It seems it's always one behind.

You will get the corrected behavior by going to the three dots in the upper right corner and by selecting options. Enable Custom Fields. When you now switch category, let's say back to Fruit. The permalink is changed to `fruit/hello-world` and if you look in the `log-permalink.txt` file in your theme directory it will now properly reflect that. It will now also say `fruit/hello-world`.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome and Safari 
 - Version 78 and 13

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS13
 - Browser stock browser Safari

**Additional context**
- Gutenberg version 7.6.0

**Comment by jorgefilipecosta** [comment]
Hi @markvanwijnen, in WordPress 5.3.2 does the issue happens without Gutenberg plugin enabled or only when Gutenberg is enabled?
Thank you in advance for this information!

**Comment by markvanwijnen** [comment]
@jorgefilipecosta I don’t have the option to enable the Gutenberg plugin it comes with WordPress. I can however install the classic editor and then the problem does not occur. 

If you go into the REST-hooks (rest_after_insert_{post-type}) it functions normally. However it gives problems when you have different entry points to the hook with different behavior without a way to distinguish between the both.

Since save_post with Quick Edit acts differently then with Gutenberg Update. Which is truly annoying.

**Comment by jorgefilipecosta** [comment]
Thank you for the detailed steps, I was able to reproduce the problem on WordPress 5.3.2 without the Gutenberg plugin enabled.

**Comment by markvanwijnen** [comment]
@jorgefilipecosta can you tell me how I can install WordPress without the Gutenberg plugin enabled? So I can reproduce it myself. On Google I can only find plugins that disable Gutenberg.

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta can you tell me how I can install WordPress without the Gutenberg plugin enabled? So I can reproduce it myself. On Google I can only find plugins that disable Gutenberg.


Hi @markvanwijnen, by default WordPress brings a stable version of the block editor and it is not possible to disable it. The Gutenberg plugin brings the most recent developments on the block editor. Unless the plugin was explicitly installed and appears on the plugin list there is no need to disable it. If the plugin was installed it can be disabled like any other plugin. Disabling the Gutenberg plugin does not disable the block editor, it just reverts back to the stable block editor version and removes some of the newer features.

**Comment by paaljoachim** [comment]
Hey @markvanwijnen and @jorgefilipecosta 

Is this issue still valid?

**Comment by ndiego** [comment]
This situation still exists in the Block Editor as of WordPress 6.0 and Gutenberg 13.7.3. That said, I am not sure if this should be considered a bug as the `save_post` hook simply works differently in the Editor. 

To achieve the result you are looking for, you can use the `rest_after_insert_{$this->post_type}` hook. Here is the [documentation reference](https://developer.wordpress.org/reference/hooks/rest_after_insert_this-post_type/). The code example below does what you are looking for. 

```
add_action( 'rest_after_insert_post', 'custom_save_post', 10, 3 );
function custom_save_post( $post, $request, $creating ) {
    file_put_contents( get_template_directory() . '/log-permalink.txt', get_permalink( $post->ID ) );
}
```

Let me know if you have any questions.
