### ISSUE TITLE
Add color transparency support

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20552]
**Is your feature request related to a problem? Please describe.**
Sometimes a color should not be completely opaque but also be semitransparent.
E.g. a slightly transparent group block.

**Describe the solution you'd like**
Add a transparency option to the color selection.

**Describe alternatives you've considered**
Add and use a block style, however, this would require to add a block style per block type and [combining block styles isn't possible yet](https://github.com/WordPress/gutenberg/issues/14598), so manual class editing is required, too.

**Comment by kjellr** [comment]
This issue is very close to #18095, except it's only about the Group block. It would make sense to roll out an opacity control more globally, so I'll close this issue and we can continue tracking in #18095. 

Thank you!
