### ISSUE TITLE
[Question] Fit to height / fill height

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20561]
The cover block inside a column block should extend to expand to the height of the column block.
How can I do this? I can apply a block style to the cover block, but in the editor that block got multiple wrappers that can't be selected by an `is-style-` class.

**Comment by annezazu** [comment]
@strarsis hey there! In case you missed it, a new feature exists that sets the cover block to full height: 

https://user-images.githubusercontent.com/26996883/118546584-6284d200-b715-11eb-9359-610e316aad80.mov

Feel free to reopen if you'd like but, for now, this is likely the best way to accomplish this.
