### ISSUE TITLE
Font size picker: Difference between "normal" and "default"

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#20560]
By default, the Block editor provides six options:

- Default
- Small
- Normal
- Medium
- Large
- Huge

If I understood correctly, the "Default" option = default font size that is specified in the theme stylesheet (example: `body { font-size: 16px; }` ). What would be the font size for the "Normal" option in this case? Are these two options (default and normal) have the same purpose?

![Font size picker](https://snipboard.io/jd5v7w.jpg)

**Comment by marekhrabe** [comment]
Font sizes are defined by the theme [as documentation suggests](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-font-sizes) and some fallback settings are directly in Gutenberg. 

> If I understood correctly, the "Default" option = default font size that is specified in the theme stylesheet (example: body { font-size: 16px; } ).

This is correct. Default means no classname will be added and thus the setting will be inherited by standard means of CSS.

In case the theme doesn't define their own sizes, default size list for the picker will be used:

https://github.com/WordPress/gutenberg/blob/8b9f65d5a360deb5df0767c00c768bf1e906b7c8/packages/block-editor/src/store/defaults.js#L100-L126

And on frontend, those will be applied to elements using the generated class name (defaults here): 

https://github.com/WordPress/gutenberg/blob/c219fed9e282a1c8467827edacf0b90303587497/packages/block-library/src/style.scss#L217-L239

Does this answer your questions?

**Comment by jorgefilipecosta** [comment]
It seems @marekhrabe already answered this question. I'm closing the issue for now in case there are any additional comments/question feel free to leave a comment.
