### ISSUE TITLE
G2 Block Interface followup

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#20575]
Recently, #19344 was merged as a first step towards addressing the interface learnings outlined in #18667.

It was a big PR, but advancing the block UI is a big undertaking, and there are followups to address. Two immediate ones are high-luminance default colors (#20460), and improving icon consistency (#20464)

As part of working on the PR, though, I wrote down a list of smaller tasks that deserve followup. As we discuss the following list on this ticket, we may even find the need to extract items to their own tickets. 

- [x] The direction that block toolbar menu items open in, seems arbitrary.
- ~[ ] The block toolbar, when there's space, should be offset 48px to the left, so the block indicator becomes the anchor point.~ — we may need to rethink this.
- [x] Dropdowns opened from the block toolbar should be the same material as the toolbar itself, dark gray border, spaced correctly according to the grid.
- [x] Renaming the "Publish..." button to just "Publish", as the ellipsis does not add value.
- [x] Remove and unify behavior of trailing appenders from block-lists. Currently they appear at the end of any nesting container if the last block is not a paragraph, which means a grouped list inserts a (+) button regardless of block selection state.
- ~[ ] Placeholders: consider simplifying further by merging the title with the description and removing the icon. This will scale better to very tiny states, necessary for patterns.~ — let's either ticket this seperately, or just revisit placeholders entirely to be more decorative. 
- [x] Explore a directional "appear" animation to the block toolbar.
- ~[ ] Unify consistency of resize handles: dots are used in some places, larger hit-area pills are explored in mockups.~ — Decided to punt this for now, as the tall handles will break for very small images. Open for others to explore. 
- ~[ ] Refine the gallery block, revisit the idea of popping out the appender at the bottom. Perhaps leverage the new "Replace" button from the Image block instead.~ Tracked separately in #21247
- ~[ ] List block: explore collapsing list types and indents in subsequent dropdowns.~ Tracked separately in #21477
- ~[ ] Icons are missing in the selection mode label indicator.~ Spun into separate issue: #21479
- [x] Notices behave inconsistently towards the mobile breakpoint.
- [ ] Explore 32px buttons in header.
- [x] Button states, hover and toggled, should animate in.
- ~[ ] Block transform menu needs love.~ Tracked separately in #21478 
- [x] "Saving" button state when saving reusable blocks has a bad gradient.

**Comment by mtias** [comment]
If both movers are disabled, it might be better to render the dotted-grid to signal dragging works.

![image](https://user-images.githubusercontent.com/548849/75671015-297e5000-5c7e-11ea-8f66-fadaa5041f45.png)

The growing triangle on hover looks rough (pixelated) during the transition. It's so small that it might be better to not do anything:
![image](https://user-images.githubusercontent.com/548849/75671118-529ee080-5c7e-11ea-97d7-8ff5a4c041e4.png)

On the navigator, the active state looks a bit excessive:

![image](https://user-images.githubusercontent.com/548849/75671222-8c6fe700-5c7e-11ea-8c31-e0efedac2387.png)

Let's make sure we open this more consistently to the bottom (and only top when there is no space):

![image](https://user-images.githubusercontent.com/548849/75671277-add0d300-5c7e-11ea-95d2-19edad9db886.png)

Also, we should collapse this to single icon dropdown with tooltips.

**Comment by mtias** [comment]
Another small one — the dropdowns should open to the right and with a bit more spacing.

![image](https://user-images.githubusercontent.com/548849/76027776-d9f68900-5ef6-11ea-86da-be7eb78743ca.png)

**Comment by jasmussen** [comment]
Fixed the tools menu:

<img width="323" alt="Screenshot 2020-03-06 at 10 01 53" src="https://user-images.githubusercontent.com/1204802/76068834-2cd14e80-5f92-11ea-9a6d-5055a56c8b30.png">

**Comment by mtias** [comment]
Another small one: we should update the rounded borders and icon weight of the custom gallery controls.

![image (61)](https://user-images.githubusercontent.com/548849/76165656-fbef4600-6158-11ea-9d42-60cb5827254b.png)

**Comment by mtias** [comment]
Another small issue:

![image](https://user-images.githubusercontent.com/548849/76316838-82cc2c00-62db-11ea-8373-390eb7fd881d.png)

**Comment by jasmussen** [comment]
I checked the "Explore a directional "appear" animation to the block toolbar", as I tried making that happen, but could not get it buttery smooth, and it felt interruptive to the experience. So it's been explored, shelved for now, and therefore checked!

**Comment by jasmussen** [comment]
#20782 fixes a few of the items outlined here, including the image dimensions issue.

**Comment by gziolo** [comment]
Some issues I noticed after rebasing with `master`:

1. `+` icon on the bottom is black:
![Screen Shot 2020-03-12 at 18 09 24](https://user-images.githubusercontent.com/699132/76547030-cd40da80-648c-11ea-82cf-d4ce2ab2bce4.png)

2. The close icon is bigger than before but it might be correct, needs confirmation:
![Screen Shot 2020-03-12 at 18 09 19](https://user-images.githubusercontent.com/699132/76547029-cca84400-648c-11ea-8c42-c040da0db8a2.png)

3. The placeholder in Columns block when tabbing between variations to pick:
![Screen Shot 2020-03-12 at 18 07 14](https://user-images.githubusercontent.com/699132/76547026-cc0fad80-648c-11ea-8f49-86a9f06d258f.png)

**Comment by jasmussen** [comment]
Thanks for the comment, @gziolo. I'll get to this as soon as I can.

Note that the black plus is a result of TwentyTwenty styling the plus when it shouldn't be. This is reported in Trac where it arguably should be fixed upstream. Separately we can discuss shadow domming such elements, so themes can't style them, intentionally or not. But I don't think we should override it in the block editor css even if we can.

**Comment by jasmussen** [comment]
We should consider rephrasing the Reusable blocks feature, and adding an icon to this one as it's one of the "bigger" features:

<img width="644" alt="Screenshot 2020-03-16 at 09 02 39" src="https://user-images.githubusercontent.com/1204802/76735311-f26f6a80-6764-11ea-856b-ea8d45388950.png">

**Comment by pablohoneyhoney** [comment]
Here a tiny optimization to bold, italic, and strike icons. Reduced to 14 height instead of 16, to look more even in the toolbar. Green dot in [this Figma file](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1178%3A0) indicates update or optimization. 

<img width="396" alt="icon-strikethrough" src="https://user-images.githubusercontent.com/25516611/76788382-2f515680-6791-11ea-8f9c-1322694a358f.png">
<img width="396" alt="icon-italics" src="https://user-images.githubusercontent.com/25516611/76788383-2fe9ed00-6791-11ea-8964-d5fc6e5b194f.png">
<img width="396" alt="icon-bold" src="https://user-images.githubusercontent.com/25516611/76788384-30828380-6791-11ea-908d-291a96fdd5df.png">


- Before
- After
<img width="382" alt="Screen Shot 2020-03-16 at 2 23 09 PM" src="https://user-images.githubusercontent.com/25516611/76788940-40e72e00-6792-11ea-9a6a-44f76f01cf66.png">

**Comment by pablohoneyhoney** [comment]
One icon that needs an update is _Latest Posts_

<img width="396" alt="block-latest-posts" src="https://user-images.githubusercontent.com/25516611/78391483-783c4400-75b4-11ea-9aea-1fa007d57a6a.png">

**Comment by jasmussen** [comment]
We should explore making the tappable hit area of buttons in the top toolbar 48x48 like in the block toolbar, even if not the visual hit area.

**Comment by jasmussen** [comment]
@gziolo I can't reproduce your columns issue:

![cols](https://user-images.githubusercontent.com/1204802/78760808-f6686400-7981-11ea-862d-c5ca1153a052.gif)

**Comment by gziolo** [comment]
> I can't reproduce your columns issue:

Did you try hover + focus? If yes, then it might get fixed together with other changes :)

**Comment by jasmussen** [comment]
I did try hover and focus and I can't reproduce. 

There are some related issues with the secondary button but none that produce the issue you saw. I think you may have had a ghost of the mixin?

**Comment by jasmussen** [comment]
I spent a bunch of time today in #21476, which fixes the overwhelming majority of issues listed in this thread. It doesn't get us to G2 perfection, but it gets us much farther, and very probably enough to close _this_ ticket in favor of separate individual tickets from now on.

One remaining issue is one of button sizes. First off, based on the comment here: https://github.com/WordPress/gutenberg/issues/20575#issuecomment-610795160 — bigger tap targets. 

We can do that — icon buttons in the block toolbar are 48px tall, and unless there are multiple in sequence, they are also 48px wide. Like so:

<img width="390" alt="Screenshot 2020-04-08 at 12 32 45" src="https://user-images.githubusercontent.com/1204802/78776359-0be88880-7998-11ea-8267-e86dfcebe710.png">

But it does require a bit of jiggery pokery and positioning the focus rectangles so that they are actually visually useful and consistent — those need to become pseudo elements that are positioned carefully inside the _hit area_ of the button. To the question is: *would that be an acceptable approach?*
