### ISSUE TITLE
Block API: Integrate variations with the `/` inserter

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#20583]
## Description

Follow-up for #16283.

With https://github.com/WordPress/gutenberg/pull/19243, we integrate block variations API with the inserter. We still should seek a way to do a follow-up for the `/` inserter. At the moment, it only lists block types.

**Comment by mtias** [comment]
It's a bit unfortunate that the quick inserter is so separate from the main one. Changes to what gets listed there should propagate more easily.

**Comment by apeatling** [comment]
+1 to this. I just lost 40mins thinking I was doing something wrong because variations were not showing up, only to realize they don't show in the `/` inserter. :)

**Comment by strarsis** [comment]
Is there already terminology for this kind of inserter?
"/"-Inserter
Quick-Inserter
Shortcut-Inserter
Fast-Inserter
?

**Comment by nk-o** [comment]
Really need this for our plugin with Gallery and Posts blocks:

![](https://user-images.githubusercontent.com/14810891/81980543-7a73d280-9637-11ea-8044-d942b0c2f60b.png)

**Comment by paaljoachim** [comment]
Let's see if I got this right.
One block can show up in multiple ways through the inserter panel. 
I remember testing a PR some time ago where the Navigation showed up twice regular horizontal and a vertical mode. This is actually much more a layout choice / styles choice. 

The example @nk-o shares seems to me more like styles and should be added to the Styles Panel. Having 5 options for the same block in the inserter is not the level it should be at.

Here is an associated comment:
https://github.com/WordPress/gutenberg/issues/20584#issuecomment-642542169

**Comment by strarsis** [comment]
> I remember testing a PR some time ago where the Navigation showed up twice regular horizontal and a vertical mode. This is actually much more a layout choice / styles choice.
Probably [this issue](https://github.com/WordPress/gutenberg/issues/22085).

**Comment by mtias** [comment]
@paaljoachim variations when exposed in inserter are to be considered new blocks, so they are meant to show up in all inserting contexts. What specific block choose to do is a separate conversation altogether.
