### ISSUE TITLE
Sidebar scroll overflow in macOS Safari

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2059]
## Issue Overview

Scroll overflow occurs in the sidebar in macOS Safari when it shouldn't:

![Scroll overflow](https://user-images.githubusercontent.com/1779930/28688075-a915ca5a-72de-11e7-9825-24a0bc29e79f.png)

## Steps to Reproduce

By default, scrollbars are hidden in macOS unless scrolling. I tend to keep them always shown... because I encounter issues like this all the time 😆 

If needed, adjust in System Preferences > General:

![System preferences](https://user-images.githubusercontent.com/1779930/28688159-ed5ff780-72de-11e7-9d8e-6a829a4f3c6e.png)

Browser details:

Safari Version 10.1.1 (12603.2.4)

**Comment by afercia** [comment]
See #1899

**Comment by aduth** [comment]
Closing as duplicate of #1899. Thanks for the pointer.
