### ISSUE TITLE
Rich Text: Selection placed incorrectly after deleting empty paragraph (Internet Explorer)

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#20598]
Previously: https://github.com/WordPress/gutenberg/pull/20594#issuecomment-593617082
Possibly related to: #19536

**Steps to Reproduce:**

1. (Prerequisite) Use Internet Explorer
2. Navigate to Posts > Add New
3. Insert a paragraph with some text
4. Press <kbd>Enter</kbd> to insert a second paragraph
5. Press <kbd>Backspace</kbd> to delete the second paragraph
6. Note that the caret selection is placed at the beginning of the first paragraph

**Expected Outcome:**

Caret selection should be placed at the end of the first paragraph.

**Additional Context:**

This is working correctly in WordPress 5.3.2 and, as such, is flagged as "Regression".

cc @ellatrix

**Comment by ellatrix** [comment]
The problem is this line that has been added: https://github.com/WordPress/gutenberg/pull/20594/files#diff-829f9f4e942450ee8c33f082c016b173R322.

**Comment by ellatrix** [comment]
If I comment that line out, everything works fine.
