### ISSUE TITLE
Multiple instances of Gutenberg on the same page

### ISSUE THREAD

**Issue by erralb** [WordPress/gutenberg#20590]
**Is your feature request related to a problem? Please describe.**

I would like to create a Gutenberg ACF field type. 
With ACF, we can have multiple wysiwyg editors on the same edit page.
I would like to be able to have multiple Gutenberg editors.

**Describe the solution you'd like**

From what I can see, Gutenberg depends on  window.wp, so we would need to create some sort of duplication.
Other people are talking about it: https://github.com/VanOns/laraberg/issues/32#issuecomment-593138396

**Describe alternatives you've considered**

Possibility to add Gutenberg blocks to a specific ACF area

**Comment by youknowriad** [comment]
This should already be possible if you use the wp.blockEditor package. Just see. how the playground is implemented.

https://github.com/WordPress/gutenberg/blob/master/storybook/stories/playground/index.js

and the result is here. 

https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default

That's one instance but you can use the component twice in a page if needed.

**Comment by jorgefilipecosta** [comment]
Another use-case of multiple block editors is the experimental widgets screen where we render a block editor per widget area https://github.com/WordPress/gutenberg/blob/30bc64c73daeae879f344992e9f74131d7366acb/packages/edit-widgets/src/components/widget-area/index.js#L122. I guess edit-widgets could be a sample for that use-case.
I will close the issue, for now, feel free to reopen if you any other comments/questions/etc...

**Comment by erralb** [comment]
Thanks you for the answer!

**Comment by christianmagill** [comment]
@erralb Did you ever make any progress on this?

**Comment by erralb** [comment]
> @erralb Did you ever make any progress on this?

Nope, sorry. 
I found workarounds for the project I was working on at the time, using ACF Gutenberg Blocks (so basically the other way around) : https://www.advancedcustomfields.com/resources/blocks/

If ever you make it please let us know !
