### ISSUE TITLE
Gutenberg doesn't remove commas from permalink, whereas WordPress does once saved

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#20600]
**Describe the bug**
Gutenberg plugin version 7.6.0 on WordPress 5.3.2.

When a new post is composed and the title contains a comma, Gutenberg converts this title into a permalink preview in the sidebar but doesn't remove the comma. Once saved however, the post's permalink has its comma removed.

**To reproduce**
1. Compose a new post in Gutenberg.
2. Enter a title with a comma.
3. Click "Save Draft". The permalink will be generated and displayed in the sidebar.
4. Note that the permalink shown in the sidebar contains a comma.
5. Publish the post. The permalink shown in the sidebar (and the actual post URL) will not contain a comma any more.

**Expected behavior**
The predicted permalink in the Gutenberg editor should match the eventual permalink used by WordPress. WordPress removes commas from titles so Gutenberg should too.

**Screenshots**
After saving draft, before publishing:
![Before saving](https://user-images.githubusercontent.com/5225190/75721266-011f4180-5cd0-11ea-8080-22d5135f22fd.png)

After publishing:
![gutenberg-bug-2](https://user-images.githubusercontent.com/5225190/75721516-6410d880-5cd0-11ea-98fa-6d579025604f.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Browser: Firefox Nightly
 - Version: 75.0 a1

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by Soean** [comment]
Maybe a duplicate of #16445

**Comment by talldan** [comment]
Definitely looks the same to me, thanks for spotting that @Soean!
