### ISSUE TITLE
Edge Browser: Missing toolbars when "Top Toolbar" not selected

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/gutenberg#20610]
In the Edge browser on Windows, blocks are missing the formatting toolbar, as well as the up/down arrows and drag-and-drop handle.

**To reproduce**

1. Use Edge browser on Windows
2. Open a page or post in the block editor
3. Select a block
4. Note the missing toolbars and up/down arrows:

![2020-03-02-2-edge-gutenberg](https://user-images.githubusercontent.com/7662449/75784565-63a82a00-5d30-11ea-8056-e8069f102610.png)

![2020-03-03-edge-gutenberg](https://user-images.githubusercontent.com/7662449/75784885-e29d6280-5d30-11ea-84a2-06f8b5c80631.png)

5. Click the vertical ellipsis at the top right and select "Top Toolbar"
6. The toolbars and up/down arrows appear at the top, as expected

**Expected behavior**
When "Top toolbar" is not selected, the toolbar should appear directly above the block, and up/down/drag-and-drop handles should appear to the left of the block.

**Desktop (please complete the following information):**
- Replicated on Microsoft Edge 44.19041.1.0 / Windows 10 Pro - Build 19041.113 / WordPress 5.3.2 on WordPress.com
- Reported by several WordPress.com users with Microsoft Edge 44

**Additional context**
- Gutenberg 7.3.0 on WordPress.com. (Not able to replicate on self-hosted WP)

**Comment by mkaz** [comment]
I tested on 5.4 beta 3 and the issue does not appear.

It looks related to the Gutenberg plugin, I also had issues running the latest released plugin on Edge.

**Comment by jasmussen** [comment]
Can confirm I'm seeing some issues with Classic Edge and running the plugin, furthermore seeing this error in the console that's possibly related:

![Screenshot 2020-03-03 at 16 46 05](https://user-images.githubusercontent.com/1204802/75792600-7e00f880-5d6e-11ea-9628-5f6ae7826ca4.png)

Note that this is not an issue in IE11, nor is it in the modern Edge that is [rolling out and will replace classic edge](https://www.windowslatest.com/2020/01/15/new-microsoft-edge-rollout-explained/).

**Comment by zdenys** [comment]
Cross-linking the previously reported one here https://github.com/Automattic/wp-calypso/issues/39072 just in case this one needs to be closed. In Gutenberg, it was fixed already https://github.com/WordPress/gutenberg/issues/19979.

**Comment by jorgefilipecosta** [comment]
I verified the bug is fixed on WordPress 5.4.
