### ISSUE TITLE
Inline Inserter?

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2061]
While using the editor a bit, I personally found it a bit strange to have the inserter in a popover and a line at the point of insertion while hovering over the blocks. In my opinion, it would be better if the inserter is at the place where to block will be inserted, much like placeholders (which would be a stage in-between). You could see the inserter as an early stage placeholder. There would be max. one, and would not be saved of course. A nice side effect is that you can move it around. So if you wanted to insert not exactly after, but before, or a bit further down, you can just move it before going further. What I also like about it is that there wouldn't be as much movement as you insert blocks.

Another interesting side effect: If we get the undo levels right, you might be able to go back to the inserter if you accidentally inserted the wrong block or embed. Just an idea for this flow... It probably doesn't make sense to keep this detail in the undo stack for long, maybe it should be removed once you change selection.

How do you all feel about both flows?

<img width="804" alt="screenshot 2017-07-27 22 48 46" src="https://user-images.githubusercontent.com/4710635/28836968-6969aff0-76eb-11e7-901d-b005cddba940.png">

**Comment by StaggerLeee** [comment]
You are making it better than some Drupal inline insert fields/modules (in this case blocks).
I personaly would prefer you leave option on top-bar too. If you decide later for inline Inserter.

**Comment by hedgefield** [comment]
I agree that having the inserter appear at the place where you want to insert will save a lot of cognitive load and clicking buttons.

We should keep the one in the top bar (though I've noticed I rarely use it for some reason), but the 'content inserter' would be more useful if it appeared between blocks. Meistertask is my shining example of this - meistertask is a trello-alike, but improves on trello's UX in many ways, this being one of them.

![inserter](https://user-images.githubusercontent.com/6073772/28768336-8b72c68c-75d7-11e7-9b3e-626503643936.gif)

**Comment by StaggerLeee** [comment]
I need to ask somethine naive. How would those "Plus" icons show on mobile devices ?
Otherways I like this idea.

**Comment by hedgefield** [comment]
That's a very good question, because they do not show in the Meistertask app either (and it frustrates me sometimes).

Hover obviously is not a possibility on mobile, so we could show the + above and below a block when you select it, similar to the movement arrows. That might get crowded, so we could also decide to not to include them and rely on the existing inserters and drag-and-drop. Or maybe we can make the spaces between the blocks tappable, there's some room to brainstorm there.

**Comment by StaggerLeee** [comment]
Detect when block is centered on screen on smartphones, and show icon on centered block. Users will get very fast what it is all about, and how to use it.

Do not know, just thinking aloud.

**Comment by iseulde** [comment]
I always make screenshots for my tickets, and I always forget to attach them. Added it now. :)

**Comment by hedgefield** [comment]
Ohhh cool, that could work pretty well in combination with a context-senstive + button :)

**Comment by jasmussen** [comment]
In light of the slash command (#2284), I think we should close this ticket once that gets in 🎉

**Comment by aduth** [comment]
Closed by #2630
