### ISSUE TITLE
Latest Posts Widget: Adding class for the title

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#20618]
It looks like all sections in this widget have a special CSS class except the title. Here is a screenshot:

![HTML of the Latest Posts Widget](https://i.snipboard.io/xjoOeF.jpg)

It would be great if the title had a CSS class as well. For example, `wp-block-latest-posts__post-title`

Currently, we need to use these CSS selectors to make style changes for the title: `.wp-block-latest-posts li > a`

By having a special CSS class for the title, we can avoid have long selectors when styling the title in the Latest Posts widget.

WordPress version: 5.4-RC1-47424

**Comment by skorasaurus** [comment]
Thanks for reporting; this has been fixed in https://github.com/WordPress/gutenberg/pull/38740
