### ISSUE TITLE
Slash inserter not working in Storybook playground

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#20619]
**Describe the bug**

In the [Storybook Gutenberg playground](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default), typing `/` in the editor does not cause the block autocomplete dropdown to appear as expected. Placeholder text still reads "Start writing or type / to choose a block" so this functionality should work.

**To reproduce**
1. Go to [Storybook Gutenberg playground](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default)
2. Click on the placeholder that says "Start writing or type / to choose a block"
3. Type "/"
4. Observe nothing happens.

**Expected behavior**

Expected block dropdown to appear.

**Comment by mtias** [comment]
I think @dmsnell run into this and it was a lack of some imports.

**Comment by dmsnell** [comment]
Yes! I had to `import '@wordpress/editor'` in order to get it hooked up and then everything happened as I expected.

I believe that I also had to register the core blocks to get it fully right - maybe we still have some implicit dependencies hiding in there

**Comment by gziolo** [comment]
@getdave, any idea what’s missing? Is it also an issue that you had with your version of the standalone editor when working on the tutorial?
