### ISSUE TITLE
Fullscreen mode: Add keyboard shortcut 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20626]
Add Fullscreen mode shortcut to drop down list beside the words:
Fullscreen mode
Work without distraction

Similar to Code Editor visible shortcut.

![Screen Shot 2020-03-04 at 16 36 51](https://user-images.githubusercontent.com/5323259/75895812-72790480-5e36-11ea-9e62-0ce3e4003590.png)

**Example:**

![Fullscreen-mode-shortcut-Gutenberg](https://user-images.githubusercontent.com/5323259/75898527-760e8a80-5e3a-11ea-8529-ee66e36f2b33.jpg)

**Comment by Clorith** [comment]
This would be very useful, as guiding users through where to click in a GUI is often more tedious than just telling them a quick combination of keys to toggle a mode.

**Comment by paaljoachim** [comment]
Should we use Shift + Alt + F as the shortcut for FullScreen mode?
