### ISSUE TITLE
Buggy focus behavior with the Table block when using Firefox

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2063]
Splitting this out from #1975 

When using Firefox, and using the keyboard to navigate, I've noticed the focus is not set correctly on the Table block. To better illustrate, I'm overriding the `:focus` style with a solid red outline.

Starting from the post title:

![screen shot 2017-07-28 at 00 15 26](https://user-images.githubusercontent.com/1682452/28694722-8011e09c-732b-11e7-84d0-8c8de21bae18.png)

press Tab: the Table block toolbar appears but nothing seems to have focus:

![screen shot 2017-07-28 at 00 15 31](https://user-images.githubusercontent.com/1682452/28694745-9a8f4c70-732b-11e7-83a0-b771460ed121.png)

press Tab again: focus goes to the bottom Inserter:

![screen shot 2017-07-28 at 00 15 34](https://user-images.githubusercontent.com/1682452/28694756-a67ddb14-732b-11e7-9f0b-91c76e464b3c.png)

This is also noticeable in #1975L when the Table drop down menu is open, tabbing forward closes the menu but fails to set focus on the table, bit weird since the table is the next focusable element.

Not sure the behavior is correct In Chrome too, since focus is set on the outer container first and I guess it should go in the table content instead, as it happens, for example, with the Text block.

Also, seems arrow navigation through blocks (see #1778) doesn't work well with the Table block.

**Comment by EphoxJames** [comment]
I believe this has been fixed because I can not replicate the issue. @afercia can you test to see if this is still an issue?

**Comment by afercia** [comment]
@EphoxJames Yep seems fixed, can not reproduce any longer.
