### ISSUE TITLE
Media and Text: Image duplicate when using "Crop image to fill entire column" option

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#20630]
**Describe the bug**
There is an issue with the image when the "Crop image to fill entire column" option is used. See a video: https://cloudup.com/crdLL84acf5

Note, it only happens in the Editor. The block looks good on the front-end of the site.

**To reproduce**
1. Add the Media and Text block;
2. Add text and image to the block;
3. Set "Crop image to fill entire column" option;

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome 80.0.3987.122]
 - WordPress [5.4-RC1-47424]

**Comment by jorgefilipecosta** [comment]
Hi @dashkevych, thank you for reporting this issue.
The issue was already reported in https://github.com/WordPress/gutenberg/issues/20434. We will try to cherry-pick https://github.com/WordPress/gutenberg/pull/20439 and https://github.com/WordPress/gutenberg/pull/20539 into WordPress 5.4 RC2.
