### ISSUE TITLE
Adding a block example causes display issues with block styles

### ISSUE THREAD

**Issue by reedcodes** [WordPress/gutenberg#20641]
**Describe the bug**

I built a custom block in a plugin, and I am adding block styles through a custom theme. The block styles work beautifully, _until_ I add an `example` to the custom block. All of the block styles then revert to using the default style instead.

When the block styles are added through the theme, it creates `.is-style-` classes for each of the styles in the block styles declaration. Those styles are working just fine! But as soon as the `example` is added, it's like those `.is-style-` classes no longer exist on the block styles in the popover and inspector panel. However, the functionality for the block itself continues to work -- if I select one of the block styles, it _does_ add the class to my block.

**To reproduce**

1. Build a custom block in a **plugin**. Add block styles through a custom **theme**.
1. Add a new page or post, click to add the custom block in the editor.
1. Select block styles from either the popover or the inspector panel. They work!
1. Go back to dev for the custom plugin, and add an `example` that will preview when clicking the "Add Block" icon from the top left in the editor top bar on the editor screen.
1. After build, go back to the editor, and click the "Add Block" icon from the top left in the editor top bar. The example previews just fine.
1. Add the custom block, then select block styles from either the popover or the inspector panel again. Notice that now they are all using the _default_ style, and none of the other styles.

**Expected behavior**

When adding an `example` to a custom block, I expect all the block styles to preview in the popover and the inspector panel. The example preview could use the default styles, but the block styles in the popover and inspector panel should respect all of the other `.is-style-` classes defined in the block styles.

**Screenshots**

Here is a screenshot of my test custom block _without_ the `example`. Block styles working great! Content added in the block previews here in the block styles. I'm using Paragraph as `InnerBlocks`.
![block-styles-block](https://user-images.githubusercontent.com/18013388/75935407-1c638b80-5e4d-11ea-8a25-99643e9faa3d.png)

Here is a screenshot showing the proper classes on the block in the Styles panel in the inspector. Classes are also present in the popover.
![block-styles-block-classes](https://user-images.githubusercontent.com/18013388/75935450-356c3c80-5e4d-11ea-9b97-af488839afd2.png)

Here is a screenshot of my test custom block _with_ the `example`. Block styles not working. The content here was added through the `example` in the block code.
![block-styles-example](https://user-images.githubusercontent.com/18013388/75935517-664c7180-5e4d-11ea-800a-b1f41c922106.png)

Here is a screenshot showing the classes missing on the block in the Styles panel in the inspector. Classes are also missing in the popover.
![block-styles-example-classes](https://user-images.githubusercontent.com/18013388/75936572-8c274580-5e50-11ea-8ba5-4f302b3141d0.png)

**Code samples**

I'm adding my block styles server side through the theme.

```
function test_block_styles() {
  wp_register_style(
    'test-theme-css',
    get_stylesheet_directory_uri() . '/build/editor.css'
  );
  register_block_style(
    'test/atest',
    array(
      'name'         => 'primary',
      'label'        => 'Primary',
      'style_handle' => 'test-theme-css'
    )
  );
  [and other styles...]
}
add_action( 'after_setup_theme', 'test_block_styles' );
```

In my custom block, I'm making sure my `edit` and `save` functions are adding the class names to the block.

```
return (
  <div className={ `${ className }` }>
    [block stuff...]
  </div>
);
```

My custom block also includes the `example` when I register the block, right after I define the title, description, category, and icon.

```
testExample = {
  innerBlocks: [
    {
      name: 'core/paragraph',
      attributes: {
        content: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis congue viverra nisi, eget luctus odio blandit at..'
      }
    }
  ]
};
```

**Version information**
 - WordPress 5.3.2
 - macOS 10.15.3
 - Chrome 80.0.3987.122
 - Firefox 73.0.1

**Comment by noisysocks** [comment]
Hi @reedcodes, are you still experiencing this? Could you provide an example in e.g. a [Gist](https://gist.github.com) that contains the complete block registration?

**Comment by reedcodes** [comment]
@noisysocks, apologies for the late reply! The notification got lost in a sea of notifications. I'll keep an eye on this.

We've done additional work on this custom block since opening this ticket, and with the recent update to WP 5.5, we'll need to do a bit more. I wonder if anything in 5.5 could have done anything behind the scenes to resolve this?

As soon as I have more information about this, I'll post an update, with a gist, and let you know! Thank you for asking.

**Comment by reedcodes** [comment]
I'm going to self-close this. I've had no other issues with this, and I can no longer reproduce. We stay on top of WordPress core updates regularly, so either something in core or something in our own code addressed this. If this becomes an issue again, I'll offer more information.
