### ISSUE TITLE
createHooks function is not defined

### ISSUE THREAD

**Issue by kub1x** [WordPress/gutenberg#20651]
WordPress version: 5.3.2, PHP version: 7.3

Hey on my recent installation of WordPress I've bumped into a really weird error: editor fails whenever I click a text block to edit it. I've traced the error to the fact that `createHooks` function is `undefined` on the `hooks` object. Might have been tree-shaked or something. Is there anything I could do to bring my WordPress editor back to life? Reinstalling WordPress last version didn't help. 

Following error is printed to the console: 
``` 
react-dom.min.js?ver=16.9.0:103 TypeError: Object(...) is not a function
    at Me (blocks.min.js?ver=6.7.2:formatted:3958)
    at blocks.min.js?ver=6.7.2:formatted:3914
    at i (lodash.min.js?ver=4.17.15:6)
    at An.filter (lodash.min.js?ver=4.17.15:99)
    at Ae (blocks.min.js?ver=6.7.2:formatted:3913)
    at Be (blocks.min.js?ver=6.7.2:formatted:3953)
    at t.value (block-editor.min.js?ver=3.2.5:49)
    at re (react-dom.min.js?ver=16.9.0:95)
    at Vg (react-dom.min.js?ver=16.9.0:95)
    at ph (react-dom.min.js?ver=16.9.0:217)
```

Which is just following piece of code missing the `createHooks` function on the `G` (hooks) object. 

![image](https://user-images.githubusercontent.com/1833840/75978346-95f78a00-5ede-11ea-93e1-3d20f4e1f534.png)

The G object seems incomplete and is different from what hooks.js file seems to generate. I don't understand how this could happen. 

![image](https://user-images.githubusercontent.com/1833840/75977868-94799200-5edd-11ea-8cf7-2f35a6e9f7ba.png)

And has the same shape when reached from console: 

![image](https://user-images.githubusercontent.com/1833840/75979647-3ea6e900-5ee1-11ea-9c19-8029c2ac9e86.png)

**Comment by aduth** [comment]
Do you have any other plugins installed on the site? Would you be able to test whether the issue is resolved by deactivating all other plugins?

Typically, this can be a problem when script dependencies are not set up correctly such that the `wp-hooks` script would be loaded later than the `wp-blocks` script. This shouldn't be the case in a default installation, however ([source](https://github.com/WordPress/WordPress/blob/cad04902d6a162ba8320f82a6c65c7eb58cf9759/wp-includes/script-loader.php#L357)).

**Comment by kub1x** [comment]
Hey, @aduth, thanks for the hint. As the site is in production, I could not turn all plugins off, but putting breakpoints after each bunch of `<script>` tags and watching the `wp.hooks` variable in debugger narrowed it down. Figured it was the Advanced Custom Fields PRO plugin which for some reason replaced wp.hooks with it's own reduced version. Thanks again.
