### ISSUE TITLE
Snackbar container block portion of UI while present.

### ISSUE THREAD

**Issue by dougwollison** [WordPress/gutenberg#20654]
**Describe the bug**
When a snackbar notice appears, such as after saving changes to a post, the container for it spans the width of the editor UI, including the sidebar. This causes an annoyance where any UI elements at the same Y axis as the snackbar are unclickable, making the user think something is broken when in fact there clicks are being intercepted by an invisible container.

**To reproduce**
1. Open a post/page, with your window sized in a way that there are interactive sidebar elements visible at the bottom of your viewport.
2. Click save/update, the update snackbar notice should appear.
3. Try clicking on said interactive elements, the click will be blocked.

**Expected behavior**
Since visually the notice is only on a fraction of the width of the screen, clicking those elements while it's present should be possible.

**Screenshots**
https://imgur.com/wyrbpzY

**Suggested Solution**
I'm currently patching it by adding this styling to my theme's block editor stylesheet:

```scss
.components-editor-notices__snackbar {
	visibility: hidden;

	.components-snackbar {
		visibility: visible;
	}
}
```

This does the trick, hiding the hitbox of the container while maintaining the hitbox of the actual notice elment.

**Comment by talldan** [comment]
Thanks for reporting @dougwollison, I can also reproduce that. The visible part of the snackbar also seems very wide now.

**Comment by jorgefilipecosta** [comment]
In 5.3 the snack bar also seems wide according to the inspector, but the bug did not happen while in 5.4 RC I'm able to reproduce this consistently.
