### ISSUE TITLE
wp-env: config.pluginSources.flatMap is not a function

### ISSUE THREAD

**Issue by gilbitron** [WordPress/gutenberg#20661]
**Describe the bug**
I have just installed wp-env on macOS (Catalina) using the instructions from [the documentation](https://developer.wordpress.org/block-editor/packages/packages-env/). Every time I run `wp-env start` I get the following error (with and without a `.wp-env.json`):

```
config.pluginSources.flatMap is not a function
TypeError: config.pluginSources.flatMap is not a function
    at buildDockerComposeConfig (/usr/local/lib/node_modules/@wordpress/env/lib/build-docker-compose-config.js:20:44)
    at initConfig (/usr/local/lib/node_modules/@wordpress/env/lib/env.js:316:30)
```

**Comment by youknowriad** [comment]
I think you're probably using an old node version. Which version are you on?

**Comment by gilbitron** [comment]
Yep, that was it 👍 I was using Node v10.17. After upgrading to Node v13 and re-installing it works. Thanks.

**Comment by slaFFik** [comment]
@gilbitron What is the min version needed for this package?
It would be nice to have this info at least somewhere (or better notify on package installation as an error).

**Comment by gilbitron** [comment]
@slaFFik It looks like `flatMap` [was added](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) in Node 11.0. I agree it would be good to have a notice somewhere about the minimum requirements (probably during installation).
