### ISSUE TITLE
Remove Redundant "Link to" in Social Icons aria-label

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#20665]
At present, a social link looks like this:

```html
<a href="https://profiles.wordpress.org/" aria-label="Link to WordPress">
  <svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
    <path d="..."></path>
  </svg>
</a>
```
I believe "Link to" in the default `aria-label` can be removed. Because it's a link element, that is redundant information.

**Comment by Soean** [comment]
It was added in #18651,  see the issue #18620 why it was added.

**Comment by mrwweb** [comment]
To clarify: Having an aria-label is good. What I'm saying is that the specific words "Link to" in "Link to Twitter" or "Link to Facebook" in the default text are redundant.

A screen reader will say something like "{aria label}. Link.", so in this case it would say "Link to Facebook. Link." Therefore, the aria-label should just say "Twitter" or "Facebook".

Is that clearer?

**Comment by 0aveRyan** [comment]
@mrwweb I've validated and opened a PR to address this, thanks for the report!
