### ISSUE TITLE
Iterate on levels of + icon when showing multiples

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20688]
Now the icon treatment is stronger the impact of multiple on a page is more intense.

<img width="780" alt="image 1" src="https://user-images.githubusercontent.com/253067/76106907-b5baab00-5fcf-11ea-81b9-1fc554744260.png">

It could be interesting to explore setting levels to the icon, here are some initial ideas:

<img width="1662" alt="Frame 4" src="https://user-images.githubusercontent.com/253067/76106944-c79c4e00-5fcf-11ea-827a-87dc5892cc84.png">

Another option could be to only show the one beside where the focus (keyboard/mouse) is, but this could be problematic.

**Comment by paaljoachim** [comment]
Hey Tammie

The new black background inserter icons are too prominent. Take too much visual space. It is the UI and not the layout and should be more subtile.

Old:
<img width="748" alt="Screen Shot 2020-03-09 at 22 24 07" src="https://user-images.githubusercontent.com/5323259/76258885-b617a800-6254-11ea-836e-e1067859e78f.png">

New (with a Twenty Twenty theme CSS bug.)
<img width="686" alt="Screen Shot 2020-03-09 at 22 22 40" src="https://user-images.githubusercontent.com/5323259/76258906-c3cd2d80-6254-11ea-97ff-26d2fd4c7883.png">

It would be better to have an outline. Similar to the old.

**Comment by jasmussen** [comment]
The G2 interface introduces a slew of contrast to the interface, intentionally so. One problem a dark-background with white plus inserter solves, is that it is visible on any background color set by the theme.

I do agree that it needs revisiting — but I think it needs a more profound revisit than just shifting around the colors of what we have:

- We should do what @davemart-in [suggested here](https://github.com/WordPress/gutenberg/issues/20728#issuecomment-596603492), and show the button-plus only when the block is selected.
- We could merge the plus that sits on the right side of an empty paragraph with the sibling inserter.

The latter deserves some thought and fleshing out — it's barely an idea at this point. But lately the sibling inserter has improved with its appearing only after a brief pause, and given its utility in being able to insert between _any_ block (not just replacing the paragraph you just made), it might be the interface to focus on instead.

On a personal note, lately I've very much embraced the Yoda-esque principle of _either do it, or don't do it at all_. Ironically, if you have too much "subtle", it'll bog down an interface with a thousand little cuts.

**Comment by karmatosed** [comment]
> We should do what @davemart-in suggested here, and show the button-plus only when the block is selected.

That sounds great and I am happy to close this issue to focus on that approach for this block. It needs working on throughout but having a cohesive approach makes sense.
