### ISSUE TITLE
Contributor user sees inaccurate message in the image block type

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#20682]
**Describe the bug**

When logged in as a user with a role of Contributor, the message within the image block type says `Upload an image file, pick one from your media library, or add one with a URL`. This is inaccurate because the user can only add an image with a URL as they don't have access to the media library.

**To reproduce**
1. Log in as a Contributor, or any other user without the `upload_files` capability.
2. Create a new post
3. Insert an Image block
4. Observe the inaccurate help text within the block

**Expected behavior**

I think the preferred behaviour is to not show a message at all. This is how the Video and Audio block types behave when logged in as a contributor.

**Screenshots**

<img width="588" alt="" src="https://user-images.githubusercontent.com/208434/76086082-43d06a80-5fab-11ea-91e5-acc5fdcb5c76.png">

**Additional context**
- Using the block editor in WordPress 5.4.

**Comment by aladin002dz** [comment]
@youknowriad  this message should follow the "current user"'s role, right?

**Comment by youknowriad** [comment]
@aladin002dz Simple solution is to just remove the message for contributors like the other blocks.

**Comment by jorgefilipecosta** [comment]
I was able to reproduce the issue on WordPress 5.3.2.
