### ISSUE TITLE
Patterns: The pattern preview should adjust height depending on actual height of pattern

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#20692]
**Describe the bug**
The Pattern Previews cut off some of the patterns making it difficult to determine if that pattern is what the user wants.

**To reproduce**
1. Click the Pattern sidebar icon.
2. Observe the "Natural Columns" preview.
3. Notice that it is cut off.

**Expected behavior**
The preview height should adjust to show the whole pattern.

**Screenshots**

**The Natural Columns pattern is cut off**

![Screen Shot 2020-03-06 at 12 35 41 PM](https://user-images.githubusercontent.com/617986/76120912-5c3e8600-5fa7-11ea-8377-5f03cef52802.png)

cc @youknowriad @enriquesanchez

**Comment by youknowriad** [comment]
I'm not sure that's possible at the moment. Last I remember working on the BlockPreview component, I think it requires a given height to work since it's supposed to vertically center the content.

That said, maybe we can have multiple ways of showing the BlockPreview.

**Comment by mapk** [comment]
> I'm not sure that's possible at the moment.

As long as this can happen sometime soon, I'm okay with that. This is an important part of previews. The user needs to see the whole thing. In regards to the block previews, I get that we centered it vertically, but what if that doesn't need to happen, and rather the preview container is just the height of the content?

Getting to this solution is a necessity for success with this interface.
