### ISSUE TITLE
Post type without title support. can't save/update etc.

### ISSUE THREAD

**Issue by isuke01** [WordPress/gutenberg#20696]
**Describe the bug**
As all know, we can register pot type without support for `title`, If this is done, Page cant be saved or updated if that is existing post type and support for `title` was removed.

In this case Im having custom meta fields that are used to generate title during save action.
I don't want user to be able to edit title manually.

**To reproduce**
Just create any post type, without `title` support
`'supports'              => [ 'editor'],`

**Expected behavior**
Same situation like without Gutenberg, post will be saved but (no title) set by default, if user does not provide one. 
That should work if there is no title support for post. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12289763/76141887-8d32bf80-6068-11ea-9d08-72976eb211f4.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Wordpress: Version 5.3.2

**Comment by jorgefilipecosta** [comment]
Hi  @isuke01 thank you for reporting this issue! Do you have the Gutenberg plugin installed or you are using "WordPress: Version 5.3.2" without Gutenberg plugin? If you have Gutenberg plugin installed could you share what version?

Thank you in advance for this information!

**Comment by isuke01** [comment]
Hey, 
Im using Gutenberg without plugin,
I have used Gutenberg that is delivered with Wordpress Version 5.3.2
:)
I also have tried it without any plugin activated, same issue
Here is screen form console, no errors.
![image](https://user-images.githubusercontent.com/12289763/76758050-28bee100-6789-11ea-91a0-5f932749d2ed.png)

**Comment by jorgefilipecosta** [comment]
I'm not being able to reproduce the issue, I registered the following CPT without title:
```
/**
 * Registers a custom post type that is hierarchical and does not supports the title attribute.
 */
function cpt_without_title_cpt() {
	register_post_type(
		'cpt-no-title',
		array(
			'public'       => true,
			'label'        => 'CPT No Title',
			'show_in_rest' => true,
			'supports'     => array( 'editor', 'thumbnail', 'comments', 'post-formats' ),
			'show_ui'      => true,
			'show_in_menu' => true,
		)
	);
}
add_action( 'init', 'cpt_without_title_cpt' );
```

And all the publishing, changing of post and updating worked as expected.


It seems the screenshot is using metaboxes. @youknowriad on posts with metaboxes shouldn't the update button always be clickable?

**Comment by youknowriad** [comment]
@jorgefilipecosta yes, it should I didn't test but potentially it's a regression.

**Comment by jorgefilipecosta** [comment]
I tested 5.4 with the simple CSS metabox plugin and when the metabox is enabled, the update button is always available.
@isuke01 is the problem still happening in your tests?

**Comment by isuke01** [comment]
Yes right, If I add any Block inside Gutenberg, I can save post, but In my case on this post type setup I have disabled all blocks, because it is just few meta blocks. 
So I that why I facing this issue.

**Comment by youknowriad** [comment]
Any updates here, is the issue still happening for you on the last WP version. We're unable to reproduce any breakage here.
