### ISSUE TITLE
Fullscreen icon - cycle between various screen modes.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20695]
EDIT: I am looking into adjusting the exit arrow in Gutenberg. Which shows up in Fullscreen mode. It gives an association of in a way exiting the customizer. It would be better to find a way to readjust how this arrow works. Change the icon and look for a better overall solution.

We can make it easier to switch between various screen modes.

Photoshop UI overview.
![Screen Shot 2020-03-07 at 01 40 51](https://user-images.githubusercontent.com/5323259/76132960-f0dfcd00-6015-11ea-8d1a-3b5ebcdf70f0.png)

Photoshop has an icon at the bottom of the toolbar:
![Screen Shot 2020-03-07 at 01 40 11](https://user-images.githubusercontent.com/5323259/76132762-cf321600-6014-11ea-8576-c40fc19583c4.png)

Standard Screen Mode
Full Screen Mode with Menu Bar
Full Screen Mode.

Clicking the shortcut F multiple times cycles through these various screen modes.

We can bring something similar to Gutenberg.

----

In Gutenberg there are various types of top toolbars. (More icons will over time also be added.)

Top toolbar
![Screen Shot 2020-03-07 at 01 30 03](https://user-images.githubusercontent.com/5323259/76132844-53849900-6015-11ea-8d00-1b48bbe9e3f7.png)

Top toolbar with block toolbar.
![Screen Shot 2020-03-07 at 01 47 11](https://user-images.githubusercontent.com/5323259/76132907-a1010600-6015-11ea-8113-c34b109f21df.png)

Top toolbar with exit to all pages/posts screen
![Screen Shot 2020-03-07 at 01 30 17](https://user-images.githubusercontent.com/5323259/76132858-67c89600-6015-11ea-855d-099924f4d0c4.png)

Top toolbar with exit to all pages/posts + block toolbar
![Screen Shot 2020-03-07 at 01 30 47](https://user-images.githubusercontent.com/5323259/76132931-c55ce280-6015-11ea-8f1d-541a55f1717c.png)

Switching out the icon and feature so one does not exit Gutenberg as if it was the customizer one could instead have an icon with a drop down to where one selects which screen mode to enter into. Perhaps something like this:

![Fullscreen-mode-Gutenberg](https://user-images.githubusercontent.com/5323259/76133618-5a150f80-6019-11ea-80a2-f694f4740721.jpg)

The reasoning behind the icon and the drop down is to give a signal to the user that is is very easy to cycle between various screen modes. There could be a visible icon for each mode. The top icon could then show the mode that is active.

One can Collapse menu in the WP menu sidebar. To almost remove the left WP menu.
One can go into the 3 dot drop down and select full screen mode. But that is hidden inside a drop down. Adding a screen cycle mode with an easy to access icon would make it easier for users to just quickly cycle through the modes to find their own perfect layout. It could also be incorporated into Full Site Editing.

**Comment by mtias** [comment]
This is an outdated capture. Check out https://github.com/WordPress/gutenberg/issues/20579

**Comment by mapk** [comment]
I think having a fullscreen icon, especially in that position, brings too much importance to switching between fullscreen and not. I believe most users will pick one and stick with it making this icon less important, and more of a setting that is adjusted once and left alone.

I'm glad you did the exploration because I had been kicking this around in my head as well. 

There are definite improvements that need to happen with the "W", but with one click on the "W", I'm back to the list of my posts or pages. In this case, I'd have to click two times to get there.

Let's see how the "W" feels for a bit, @paaljoachim. If there's still problems arising, we can review this again. Cool?

**Comment by paaljoachim** [comment]
I am very hesitant in having to click the W to get back to all pages/all posts. It could just instead minimize the left WP menu bar. Similar to clicking the left arrow on the button.

But yeah. Let's try it out for a bit and see how we feel.

**Comment by mapk** [comment]
Alrighty, let's close this for now.
