### ISSUE TITLE
Button arrangement in "poster" video attribute

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20704]
This doesn't look great. We should consider it as we look at the sidebar controls:

![image](https://user-images.githubusercontent.com/548849/76164405-f1c84a00-614e-11ea-8dff-4f4da20c84c8.png)

cc @jasmussen  @pablohoneyhoney

**Comment by jasmussen** [comment]
Yeah what a mix of things going on here. 

What are the heuristics for the labels here? Some of them are pieced together from post types, right? And what can we do as far as changing the verbiage? Not just unifying the case structure, but rephrasing as well. For example it seems worth trying:

```
Image

[Replace]   Remove
````

With "Replace" being either primary or secondary and "Remove" being tertiary.

**Comment by mtias** [comment]
> Some of them are pieced together from post types, right?

I don't think so, this is just custom to the Video block.

**Comment by jasmussen** [comment]
Created #20754 to address this.
