### ISSUE TITLE
Social icons Block: Open link in a new tab.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20707]
It would be nice to have the possibility to open social icons in a new tab.

We also received a request for it here: https://wordpress.org/support/topic/social-icons-link-target-attributes/

Today the link attribute in Social Icons Block look like this:

<img width="517" alt="Screen Shot 2020-03-08 at 19 15 00" src="https://user-images.githubusercontent.com/5323259/76168581-6f04b680-6171-11ea-8e89-2821ae1c923e.png">

@mkaz @jasmussen

**Comment by mkaz** [comment]
Good catch, `<LinkControl>` was under active development so wasn't ready to switch over.
It should be ready now to switch `URLInput` out for using `LinkControl`

**Comment by paaljoachim** [comment]
I also assume that the Social Block will be almost an exact replica setup/UI style as the Buttons Block.

**Comment by mkaz** [comment]
The first attempt was to use LinkControl, see #20740, this approach is not a good solution since it requires setting the parameter on each link. The ideal solution is to set the attribute on the parent and not each individual block, then on render add the proper target for the links

To read the parent attribute from the server-side render requires #19685

So this ticket can be picked up after that one closes.

An additional piece when adding a `target="_blank"` to a link, we should also include `rel="noopener noreferrer"` for security per 
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by mrwweb** [comment]
This appears to be a duplicate of #18486.

**Comment by paaljoachim** [comment]
Btw I believe this issue in relation to consistency in the Link Control could use a look at: 
https://github.com/WordPress/gutenberg/issues/17293

**Comment by xpurichan** [comment]
Another request in 22526349-hc.

**Comment by drywall** [comment]
Put me down as someone else requesting this. I'm sure there are compelling technical reasons why it hasn't been done, but for an end-user this is inexplicable... seems like a reasonably common use case.

**Comment by chaitanyamsv** [comment]
23238643-hc

**Comment by paaljoachim** [comment]
New explorations are being done with link control: https://github.com/WordPress/gutenberg/issues/23375
I would think that this would also drip down to the Social Icons Block.

**Comment by allysonsouza** [comment]
I'm with @drywall, it's really a very common use case, it's even difficulty to explain to an end user why it's not solved yet.

**Comment by paaljoachim** [comment]
Hi @allysonsouza 

I am testing with WordPress 5.7 RC1.
No Gutenberg plugin active.
I am using the WordPress beta tester plugin.
Twenty Twenty One is the active theme.

Social icons will open in a new tab if one chooses to do so. 
There is a Link settings in the sidebar:

![Screen Shot 2021-03-01 at 23 14 29](https://user-images.githubusercontent.com/5323259/109566248-e69ac680-7ae3-11eb-9005-181a57fda9b4.png)

**Comment by gaswirth** [comment]
Has there been any movement here? Agreeing with @drywall and @allysonsouza et al. that this is a super common use case, and it seems that @paaljoachim has come up with a working solution. Any reason we can't get this merged?

Thanks all !

**Comment by bomsn** [comment]
This is still an issue with widget blocks, there needs to be an option to open them in a new tab.

**Comment by HumanGeigerCounter** [comment]
Checking in from the future where this is **_still_** an issue... I am guessing it is a ploy to encourage users to purchaser a higher tier plan that allows the installation of plugins to correct the issue...

**Comment by HumanGeigerCounter** [comment]
> Hi @allysonsouza
> 
> I am testing with WordPress 5.7 RC1. No Gutenberg plugin active. I am using the WordPress beta tester plugin. Twenty Twenty One is the active theme.
> 
> Social icons will open in a new tab if one chooses to do so. There is a Link settings in the sidebar:
> 
> ![Screen Shot 2021-03-01 at 23 14 29](https://user-images.githubusercontent.com/5323259/109566248-e69ac680-7ae3-11eb-9005-181a57fda9b4.png)

Is this something that was launched in an update or did it die in beta? I don't currently see anything like this in my editor view. Any help is appreciated, thanks!
