### ISSUE TITLE
+ Icon not center on Columns

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#20700]
**Describe the bug**
If you add a placeholder or some non-RichText block and then a paragraph, the + icon isn't on center.

**To reproduce**
1. Add a Columns block
2. Then add an Image block without an image. And add some text in paragraph following it.
3. Hover on the bottom border of Image and the (+) sign is not on center.

**Expected behavior**
It should be on center.

**Screenshots**
<img width="692" alt="Screen Shot 2020-03-08 at 4 34 14 AM" src="https://user-images.githubusercontent.com/2649903/76153731-12b08100-60f6-11ea-8d7c-1c3895067da8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Latest
 - Browser Firefox Latest
 - Gutenberg 7.6.0

**Comment by ehti** [comment]
Howdy @HardeepAsrani 🙂

I believe this behavior and UI has changed so this shouldn't be an issue anymore either. Closing it but let me know if I missed something.

Cheers
