### ISSUE TITLE
Add a way to control spacing between gallery images

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20705]
It'd be great to allow changing the size of the gaps between images when using galleries.

By default:
![image](https://user-images.githubusercontent.com/548849/76165500-d44bae00-6157-11ea-9061-d6807408cb12.png)

With zero gaps:

![image](https://user-images.githubusercontent.com/548849/76165529-06f5a680-6158-11ea-99d7-4288e887ee4c.png)

Once it's absorbed into the style system, this would also be an attribute the theme should control.

**Comment by tdechangy** [comment]
This should certainly be a WP/theme option first.

**Comment by andrewserong** [comment]
Just linked a PR, this issue will be addressed by #34608
