### ISSUE TITLE
@wordpress/hooks: the 'all' hook's handlers are run too many times

### ISSUE THREAD

**Issue by Crusse** [WordPress/gutenberg#20710]
**Describe the bug**

The line at https://github.com/WordPress/gutenberg/blob/f07e7560456dc364e306a01d5e6ba6bc47523649/packages/hooks/src/createRunHook.js#L37 is pushing to the `hooks[ hookName ].handlers` array. Therefore, whenever `doAction()` or `applyFilters()` is run, the `all` handlers are pushed **again** to the `hooks[ hookName ].handlers` array. Eventually this creates many duplicates of the `all` handlers in many hooks.

**To reproduce**

index.js:
```
const { createHooks } = require( '@wordpress/hooks' );

const hooks = createHooks();

hooks.addAction( 'all', 'bug', () => {
  console.log( 'Handler count:', hooks.actions[ hooks.currentAction() ].handlers.length );
} );

hooks.addAction( 'foobar', 'bug', () => {} );

hooks.doAction( 'foobar' );
hooks.doAction( 'foobar' );
hooks.doAction( 'foobar' );
```

The above code prints:

```
$ node index.js 
Handler count: 2
Handler count: 3
Handler count: 3
Handler count: 4
Handler count: 4
Handler count: 4
```

**Expected behavior**

I would expect the above code to print:

```
$ node index.js 
Handler count: 2
Handler count: 2
Handler count: 2
```

**Comment by kathrynwp** [comment]
Hi @Crusse – circling back to this issue, is it still occurring with the latest version of Gutenberg and WordPress? Thanks!

**Comment by kathrynwp** [comment]
As there's been no movement on this in several years, I'm going ahead and closing this out, but if you are still experiencing the original issue, feel free to reopen with any additional details.
