### ISSUE TITLE
Add pattern: side by side image

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20716]
Good to offer this as a pattern since it's not immediately clear what the quickest way to achieve this effect might be for the user:

![image](https://user-images.githubusercontent.com/548849/76206654-b97f4500-61fc-11ea-8c89-d2abb4a689c1.png)

**Comment by ZebulanStanphill** [comment]
Closed by #20725.

**Comment by mtias** [comment]
I hope we can get some better images.
