### ISSUE TITLE
Inner Blocks inserter on single-child blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20728]
When a block uses inner blocks but only supports a specific block type as a child, we should consider stating more clearly what the + does.

Current:
![image](https://user-images.githubusercontent.com/548849/76224733-13dbce00-621c-11ea-8349-81548d786b8e.png)

Something like this:
![image](https://user-images.githubusercontent.com/548849/76225107-51d8f200-621c-11ea-905a-6994fd9b5e54.png)

**Comment by davemart-in** [comment]
Thoughts on also hiding the Add Button icon and text when in preview mode and only showing it when the button block is selected?

![button-add](https://user-images.githubusercontent.com/5634774/76230252-d5351c00-61f9-11ea-92c2-5c9d54b426b0.gif)

**Comment by mtias** [comment]
Yes, it should show when the container (Buttons) or a child (Button) is selected. This should apply to all nested contexts, though — selecting an item inside a column, or the column itself, would show the +, otherwise it should not appear.

**Comment by karmatosed** [comment]
I would +1 what @davemart-in showed above and say that we can remove the 'needs design' label as that feels right to get as soon as possible into code. Going to add a feedback label just to keep that flowing though.

I really like this and also note that it can be an opportunity to centre the '+' along with this aligning better with the button. It will also stop multiple '+' without context and all feeling like they add a block.

**Comment by jasmussen** [comment]
Loved your idea so much, Dave, I ran with it in https://github.com/WordPress/gutenberg/pull/20753.

**Comment by paaljoachim** [comment]
When removing a button or social icon the parent block of both become empty. We see an inserter that seems out of place. Hovering over the inserter gives some info what they are.

I would suggest when no child block (social icon or button) is present then the parent is also removed.
