### ISSUE TITLE
Suggestion: add Title Case tool to Gutenberg editor to improve titles on 36% of the web

### ISSUE THREAD

**Issue by lancewillett** [WordPress/gutenberg#20739]
Suggestion: Add a utility action to quickly toggle title case when publishing a post or page.

A common task for me when posting on a WordPress website is opening making the post or page title title cased, meaning it looks like a title.

Currently I use a JavaScript tool called `to_title_case()`: https://github.com/gouch/to-title-case

Including something simple like this would not just save time for people that care about proper title case, it might just make more posts and pages on the web more readable and useful.

**Comment by draganescu** [comment]
Hi @lancewillett! This is a very interesting suggestion and as we're developing the Post blocks for the incoming Full Site Editor, this option to automatically convert to title case would be a great feature of the Post title block, maybe as a toggle in the inspector for that block.

<img width="772" alt="Screenshot 2020-03-10 at 13 07 58" src="https://user-images.githubusercontent.com/107534/76306918-71c9ed80-62d0-11ea-9fe3-8fe6c939f9eb.png">

**Comment by Soean** [comment]
I think this is a feature for a plugin, not for core. For example in german we don't use title case.

**Comment by lancewillett** [comment]
Good point, @Soean. Thanks for sharing your perspective.

I'm happy to treat this as a plugin feature that improves Gutenberg for people that want and need it.
