### ISSUE TITLE
Iterations on Navigation Mode

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20732]
Columns (and likely other nested contexts) have become traps for **navigation mode**. It's not possible to press "down" from the last block of a column to move out of the column block and into the next block.

Ideally, when navigating columns, you would also be able to press right / left arrows to move selection to the next / previous column.

![image](https://user-images.githubusercontent.com/548849/76230371-e3982d80-6223-11ea-97bb-edd60063f472.png)

Also, pressing escape _again_ while on a child block (paragraph inside column), we should move selection one level up.

**Comment by karmatosed** [comment]
I am very keen to remove any traps, so agree in adding those interactions. It strikes me that keyboard navigation likely is depending on the column blocks density pretty useful.

**Comment by mapk** [comment]
There's some tricky interactions that need to happen for sure. I haven't experienced it as a trap, but it does require both the Select and Edit tools to navigate through with the keyboard.

![keyboard](https://user-images.githubusercontent.com/617986/81023520-8684b680-8e25-11ea-884d-8995a6c6594b.gif)
