### ISSUE TITLE
Block editor inserter is missing the '+' 

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#20735]
**Describe the bug**
Running the most recent from `master` I noticed that the block inserter in the editor is missing the '+' icon, unless you hover it:

![2020-03-09 11-10-14 2020-03-09 11_10_56](https://user-images.githubusercontent.com/3276087/76239517-563ee400-61f7-11ea-8faa-3ed8d5c2fed4.gif)

This behavior also happened on other blocks:

<img width="675" alt="Screen Shot 2020-03-09 at 11 12 22" src="https://user-images.githubusercontent.com/3276087/76239465-3d363300-61f7-11ea-9b57-2269286ae88e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox and Safari

**Comment by bph** [comment]
I saw the same. Seems to be a Twenty Twenty Theme. It went away when I switched to the Twenty Sixteen theme.
![Screen Shot 2020-03-09 at 1 51 38 PM](https://user-images.githubusercontent.com/39980/76244397-5b5c5d00-6210-11ea-9c8e-f495b3956660.png)

OS: macOS
Browser: Google Chrome.

**Comment by enriquesanchez** [comment]
Thanks @bph!

Since this seems to be a theme issue, I'm closing in favor of: https://core.trac.wordpress.org/ticket/49610
