### ISSUE TITLE
Version 7.7: New blue square inserter is too prominent.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20744]
I am looking at the RC of 7.7.

The blue square inserter is too prominent. UI should have a subtile feel to it. The blue button is too strong. It stands out too much compared to everything else in the area.

<img width="1421" alt="Screen Shot 2020-03-09 at 21 54 01" src="https://user-images.githubusercontent.com/5323259/76256609-8666a100-6250-11ea-887e-5ed45001d239.png">

Compare it to earlier version of the inserter:
<img width="1423" alt="Screen Shot 2020-03-09 at 21 58 47" src="https://user-images.githubusercontent.com/5323259/76257026-33411e00-6251-11ea-9acd-efe18be0ff0a.png">

Notice how the old inserter is better in balance with the other icons around it.
It does not overshadow the other buttons.
It is more subtitle.
The Content Structure is round and has a good balance with the round Inserter.
<img width="185" alt="Screen Shot 2020-03-09 at 22 15 50" src="https://user-images.githubusercontent.com/5323259/76258305-98960e80-6253-11ea-996a-1880f7b06d7a.png">

Look at the new icons.
<img width="263" alt="Screen Shot 2020-03-09 at 22 18 00" src="https://user-images.githubusercontent.com/5323259/76258467-e90d6c00-6253-11ea-9705-c2be0a0662d4.png">

There is much more going on. The balance is lost. There is more contrast. It does not flow as well as the older version.

Here is what it looks like in a style similar to the earlier version. (There is still a contrast with having multiple shapes. Square, round and other shaped icons.

![New-square-inserter-Gutenberg](https://user-images.githubusercontent.com/5323259/76258379-b6637380-6253-11ea-9fa9-959d89aa94e3.jpg)

![Screen Shot 2020-03-09 at 22 20 10](https://user-images.githubusercontent.com/5323259/76258588-2e319e00-6254-11ea-9952-e269fc59652d.png)

**Comment by mtias** [comment]
> Notice how the old inserter is better in balance with the other icons around it. It does not overshadow the other buttons.

This was precisely what the design update aims to address: adding blocks has to be the most prominent interaction we offer and should not blur with other — way less important — items (like the content structure one!).

**Comment by paaljoachim** [comment]
Hey Matias

Gotcha. I will use the UI for a while and get used to it and take it from there.

**Comment by mtias** [comment]
Please, do reopen if it doesn't grow on you :)
