### ISSUE TITLE
Preview feels disconnected from Block inserter

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20747]
I slept in class. I know Joen @jasmussen and I also believe @enriquesanchez worked on what I am going to mention below. Anyhow here goes.

The gap between selecting the Columns block and the preview makes it feel disconnected.

<img width="786" alt="Screen Shot 2020-03-09 at 22 38 54" src="https://user-images.githubusercontent.com/5323259/76259988-19a2d500-6257-11ea-8b59-ce867ef098b7.png">

Here is one where I placed the preview right next to the Most used area.
![Preview-next-to-block-Gutenberg](https://user-images.githubusercontent.com/5323259/76260302-c715e880-6257-11ea-8c7a-b32c27670340.jpg)

It is right up to the Blocks area. It covers the full Most used area. Not background gap is seen between Block icons and the preview. They feel tight and they should be tight...:)

**Comment by jasmussen** [comment]
I personally disagree :) — I think of it as a tooltip, and tooltips are disconnected. However, I noticed a lack of border radius and shadow on the preview which I'll look into fixing!

**Comment by draganescu** [comment]
It is kind of floating out there. I don't know, maybe it's simply a reaction to entrenched patterns, but that small arrow that tool tips have does a great job of connecting the information. Just my 2 cents :)

**Comment by enriquesanchez** [comment]
The gap could certainly be reduced, but I think an important part here is the hover interaction. To me, the fact that when you hover a block the preview popover appears is enough to communicate that the two elements are related.

I did a quick attempt at reducing the gap size. It currently is 20px wide.

**Here's at 12px:**

![2020-03-10 12-58-07 2020-03-10 12_59_21](https://user-images.githubusercontent.com/3276087/76349345-6de99b80-62cf-11ea-90b9-6b0f9964c160.gif)

**And here's at 16px:**

![2020-03-10 13-00-56 2020-03-10 13_01_58](https://user-images.githubusercontent.com/3276087/76349364-7510a980-62cf-11ea-95f1-e1a6b51610a3.gif)

Both feel good to me.

**Comment by paaljoachim** [comment]
Hey Enrique 

Good idea!

Having it closer really helps. It creates a proximity association between elements.
I liked the 12 px gap the most. Then Joen can add some shadow and use sandpaper to round the corners..:)

**Comment by enriquesanchez** [comment]
@jasmussen [I attempted a quick PR](https://github.com/WordPress/gutenberg/pull/20777) to reduce the gap and also add the missing border radius and box shadow. I'll appreciate a review.
