### ISSUE TITLE
Make media editing flow part of the experience

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2075]
To recreate the main broken flow:

- Add an image
- Click on pencil to edit when in editor
- Click on 'edit image' text link

You will see a page like this:

![2017-07-28 at 10 14](https://user-images.githubusercontent.com/253067/28722243-f57f3a4e-73aa-11e7-97d0-e4525a3229fe.png)

If you click 'update' you are taken to the edit section in the media library. You never go back to Gutenberg and could potentially lose content, also get lost along the way.

**Comment by mtias** [comment]
See #1725.

**Comment by karmatosed** [comment]
Closing this and marking the other ticket more of a priority. #1725 would fix a broken flow and that's important.
