### ISSUE TITLE
TinyMCE: Deleted, then replaced text loses <strong> tag.

### ISSUE THREAD

**Issue by michaeldcain** [WordPress/gutenberg#2076]
## Issue Overview
When deleting and replacing quick tag-bolded text. `<span style="font-weight:600">` gets used instead of `<strong>`.

## Steps to Reproduce (for bugs)
1. Add a new post in Gutenberg.
2. Write some text. Highlight it and use quick tag to make it bold.
3. View Text mode - `<strong>` was used for bolding.
4. Return to Visual mode, highlight bolded text, _delete_, then replace text.*
5. View Text mode - `<strong>` was switched to `<span style="font-weight:600">`.

Gutenberg 0.5.0
Chrome 59.0.3071.115
macOS Sierra 10.12.6

## Video of Issue
https://cloudup.com/cGxtwspSHEs

## Expected Behavior
The same tag (`<strong>`) should be used when deleting and replacing quick tag-bolded text.

## Current Behavior
`<strong>` is correctly used for general replacing of quick tag-bolded text, except when text is fully deleted before being replaced. Then `<strong>` is replaced with `<span style="font-weight:600">`. 

## Related Issues and/or PRs
Related core TinyMCE ticket: https://core.trac.wordpress.org/ticket/41475

**Comment by mtias** [comment]
This now also includes the bg used for the formatting boundaries. cc @androb

**Comment by iseulde** [comment]
See https://wordpress.slack.com/archives/C0UCMQP0F/p1515086628000146

**Comment by iseulde** [comment]
From the conversation linked, it seems like and edge case that is not trivial to fix. Closing, at least for now.
