### ISSUE TITLE
Selecting gallery items is disorienting

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20764]
The current combination of selection / scrolling is pretty disorienting on galleries that are large enough. See video: https://cloudup.com/cs6FeAO4Tgy

We should fix this.

**Comment by paaljoachim** [comment]
Thank you for adding the issue Matias!

@glendaviesnz This is something to test in relation to the updated Gallery block.

**Comment by glendaviesnz** [comment]
It doesn't happen with the refactored gallery as clicking on an image block just selects that image rather than the parent gallery:

![gallery-selection](https://user-images.githubusercontent.com/3629020/114937435-e7b86500-9e91-11eb-9340-c64175a57e93.gif)

**Comment by mtias** [comment]
Yes, I'm going to close this as it should be addressed there.
