### ISSUE TITLE
Date picker has some unexpected styling on borders

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20774]
I think this might be due to the recent interface changes, however, I saw this on latest version today:

![image](https://user-images.githubusercontent.com/253067/76341536-1a8a4400-62f5-11ea-95c9-5c8cb4c01280.png)

@jasmussen looping you in here as feels like needs some adjusting. My recommendation would be to have a dark border on PM to balance and also balance the heights on inputs in day and month.

**Comment by jasmussen** [comment]
Yep. There are some things here that need love. I was doing some PRs today, hoping to look at the sidebar tomorrow, I'll see about this one too.
