### ISSUE TITLE
Site Editing: home page indicator

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20788]
We should add an icon to indicate what is currently set as the home template:

![image](https://user-images.githubusercontent.com/548849/76416787-051c2500-639c-11ea-93dd-30c74e3e8008.png)

The order should reflect some hierarchy as well, with home page / front page being always at the top.

And also need to start thinking about the site setting and how it interacts with the blog being set as home or on a sub-path.

**Comment by MichaelArestad** [comment]
Does this need to be reflected here or in something like a template manager? I could also envision a Template "tab" next to Document and Blocks in the sidebar that displays information about the template like theme, pages using it, template parts.

**Comment by epiqueras** [comment]
We need something like that, but wouldn't a home icon in the template switcher also be a good addition?

**Comment by MichaelArestad** [comment]
Here's a mockup by @joanrho that does the job:

![image](https://user-images.githubusercontent.com/1123119/80644854-8f414b00-8a27-11ea-953d-eb3f34d00c9e.png)

Some questions:
* Is it enough of an indicator?
* Does it need an explanation (perhaps in the template preview on hover)?

For now, I think it's definitely a good start.

SVG code:
```
<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.5 4V9.5H6.75V6.25V5.75H6.25H3.75H3.25V6.25V9.5H0.5V4L5 0.625L9.5 4Z" fill="black" stroke="black"/>
</svg>
```

**Comment by epiqueras** [comment]
Yes, a tooltip on the icon would suffice, right?

**Comment by joanrho** [comment]
A tooltip with text along the lines of "Current Home page template" could be helpful since the template name could be anything. Or, would it communicate better if it were a line of text at the very top of the Template Preview pane, since that preview appears alongside each template on hover over template name?

**Comment by MichaelArestad** [comment]
> Yes, a tooltip on the icon would suffice, right?

Totally. As long as it plays nicely with the menu.

> "Current Home page template"

Right! Perhaps a slightly shorter version: "Home page template"

**Comment by epiqueras** [comment]
@MichaelArestad See #22004

**Comment by mtias** [comment]
Commented on the PR, but we should not introduce another baseline icon grid of 10/10.
