### ISSUE TITLE
[ Latest Posts ] Markup issue for Read more link inside the editor

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#20783]
Inside the editor, the markup for the Read more link (href attribute) is missing double-quotes. As a result, the target attribute is concatenated to the URL (e.g. `http://localhost/gutenberg/2020/03/11/hello-world/target=_blank`) which creates wrong links.
[L336-L338](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/edit.js#L336-L338):
```
' ... <a href=' +
	post.link +
	'target="_blank" rel="noopener noreferrer">' +
```

**Comment by draganescu** [comment]
Howdy @dianeco thanks for raising this issue!

I added the PR above. If you could test and see that it fixes the issue, it would be awesome :)

**Comment by dianeco** [comment]
@draganescu LGTM
