### ISSUE TITLE
Allow changing text color of a character

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#20798]
The text color option is great, but it'd be great to allow changing the color per character, just like how the bold and the italic option work.

**Example**:
![Pattern 40](https://user-images.githubusercontent.com/908665/76444762-52a88a00-63bc-11ea-9b7b-7995f7c660ad.png)

**Comment by iamtakashi** [comment]
I just saw the text color option, so I've edited the above. But it'd still be great if we could extend the option to per character.

**Comment by iamtakashi** [comment]
Never mind, I was able to change color per character. Not sure why I didn't see it :)

**Comment by designsimply** [comment]
@iamtakashi may I ask how you changed text color per character? I was not able to figure out how to do that without a plugin like [Advanced Rich Text Tools for Gutenberg](https://wordpress.org/plugins/advanced-rich-text-tools/).

**Comment by designsimply** [comment]
Never mind 😁 I found it! I was looking in the block settings on the right but it's in a dropdown inside the block toolbar! It took me a bit of research to find it as well. ([ref](https://github.com/WordPress/gutenberg/pull/16014#pullrequestreview-354627103), announced for 5.4 [here](https://wordpress.org/news/2020/03/adderley/))
