### ISSUE TITLE
Navigation menu block: dissapearing submenus is disorienting 

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#20807]
This issue comes from the the accessibility test performed by the Accessibility team (#20369). One of the issues raised was that having submenus appear and disappear depending on child block selection can be disorienting. 

>Having the nested links disappear when the subblock was not selected was disorienting. It made me believe that somehow my sublinks had been deleted.

![2020-03-11 12-57-50 2020-03-11 13_00_31](https://user-images.githubusercontent.com/3276087/76454803-d05b9e00-639a-11ea-8b60-4672e6157810.gif)

I understand that the UI is replicating the front-end behavior, but I expect that not everyone will understand it. Also, users of assistive technology will probably find it disorienting.

**Comment by enriquesanchez** [comment]
If we can't have sub-menus visible at all times (because we want to keep a 1:1 similarity between the editor and the front-end), I think we could make it more obvious that there is a sub-menu. 

This perhaps means increasing the size of the sub-menu icon (the little triangle), or using a different icon that communicates the existence of a sub-menu in a better way.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/22107 addressed this.
