### ISSUE TITLE
Gutenberg 7.7 Columns with Paragraph block bug

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#20803]
**Describe the bug**
If you have a paragraph inside a column, you cannot navigate to the column, or to the columns.

**To reproduce**
1. Create a columns block with 3 columns.
2. In the first column insert a paragraph, in the second an image, and in the third another paragraph.
3. To see the bug, try to select the first or third columns (individually), or try to select the entire columns block. Now at least with the second column which there no paragraph block we can navigate to that column, but still impossible to select the entire columns block.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser Chrome
- Fresh installation on Xampp (localhost), WP 5.3.2, Gutenberg 7.7 plugin, default 20/20 theme, php 7.x.

**Comment by youknowriad** [comment]
There's multiple ways to navigate to the parent hierarchy when there's no padding/margins.

The "Block Navigator" in the top toolbar, using the Navigation/Select mode (can be triggered using Escape or from the top toolbar) where clicks select parent to children or use the breadcrumb shown in the footer of the editor.

I hope that helps.

Thanks.

**Comment by nick6352683** [comment]
Hi @youknowriad ,

Neither the Block Navigator or the breadcrumb work... that was my point (although not very clearly). In the situation that I described IT IS IMPOSSIBLE to select a column or a block.

I can produce a video if needed as proof, this issue should be reopened.

**Comment by youknowriad** [comment]
Oh sorry for the confusion, yes, I can definitely reproduce the issue. 

@ellatrix I wonder if this is related to the focus thing we updated for consistency in block.js

**Comment by nick6352683** [comment]
Thanks @youknowriad , if there is anyone I can trust in the team, is you !

**Comment by youknowriad** [comment]
Thanks :) I can assure you everyone is doing their best.
