### ISSUE TITLE
Gutenberg 7.7 Adding background color to columns bug.

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#20804]
**Describe the bug**
Adding background color to the Columns block only works on the front end, and not in the editor.

**To reproduce**
1. Create a columns block.
2. Add contents to the columns, but NOT paragraph block, as adding a paragraph block to a column will result in column selection problems !
3. Add a background color to the columns block.
4. Observe that the background color is not displayed in the editor, but it is correctly displayed on the front end.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser Chrome
- Fresh installation on Xampp (localhost), WP 5.3.2, Gutenberg 7.7 plugin, default 20/20 theme, php 7.x.

**Comment by zkingdesign** [comment]
Same issue here. Unfortuantely the background color is not visible in the admin area.
