### ISSUE TITLE
Navigation block uses alignment and justification as terms where other blocks do not

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20813]
For most blocks, for example the paragraph blocks the term 'text alignment' is used:

![text-alignment](https://user-images.githubusercontent.com/253067/76462223-3830d980-63d9-11ea-9040-cc64ea1c9dec.png)

An image block uses 'alignment':

![image](https://user-images.githubusercontent.com/253067/76462246-40891480-63d9-11ea-8866-63b4ffc38653.png)

The navigation block has a combination of these terms but uses 'justification':

![nav-alignmentbeingwidth?](https://user-images.githubusercontent.com/253067/76462285-53034e00-63d9-11ea-8730-0f821b8dfa26.png)

![nav-justificationisalignment](https://user-images.githubusercontent.com/253067/76462301-5991c580-63d9-11ea-9bd3-7e9c2fa0af31.png)

I would maybe consider having alignment and text alignment as options in the toolbar because there is past ground for this within other blocks. It might make things make a little more sense. If this isn't agreed, then saying justify text might make more sense than justify items. I still would recommend we don't use the term justify unless we start changing this for other blocks.

**Comment by mtias** [comment]
These alignments work quite differently than the others. There are a few issues already discussing it.

**Comment by ZebulanStanphill** [comment]
This is a difficult thing to discuss due to the rather confusing terminology WordPress currently uses; a lot of things called "alignments" are not actually alignments. See #19672.

**Comment by jasmussen** [comment]
Going through the navigation tasks here, I'm actually going to close this one in favor of #19672. There's definitely an alignment conversation to be had, but it's not specific to navigation, as we are adding justification controls also to the Buttons block, potentially to the Social Links block as well.
