### ISSUE TITLE
Error on Block Copy Paste

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#20819]
**To reproduce**

1. Copy a block from code view.
2. Add new page
3. Press Ctrl + Shift + Alt + M to switch to code view.
4. paste the block code.
5. If you click outside or anywhere and again press Ctrl + Shift + Alt + M. It will work but after pasting the code, without clicking anywhere if you press Ctrl + Shift + Alt + M, nothing will be viewed on the editor. 

see here an example https://drive.google.com/file/d/1diieAWXl31KdzJR-mvXfj2cC6Xku6151/view

**Comment by ehti** [comment]
Can reproduce too.

**Comment by paaljoachim** [comment]
Wow that is interesting.
I opened up the Code editor. 
Pasted in a block.
Then immediately pressed the keys: Shift + Ctrl + Alt + M.
It went back to visual editor but no block was seen.

The error is still there.

**Comment by Mamaduka** [comment]
I believe I recently fixed this issue - #40730.
