### ISSUE TITLE
Only show 'group' option when you have more than one block selected

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20814]
You can select a single block and make it a group. I would perhaps recommend that this option only appears when you select multiple blocks. Unless there is another benefit of being a group?

![nav-singlegroup](https://user-images.githubusercontent.com/253067/76462986-898d9880-63da-11ea-8217-32c06b11b72f.png)

**Comment by mtias** [comment]
There are some benefits to this since you can use the group to add certain styles (background and text color) and more in the future (paddings, alignments).

**Comment by karmatosed** [comment]
Thanks for the explanation, happy to close this then. It felt weird but if there are benefits we can revisit how it feels.
