### ISSUE TITLE
Navigation menu block: cannot select custom color

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#20810]
This issue comes from the the accessibility test performed by the Accessibility team (#20369).

>In the color palette when you don't like the default colors offered, you need to open another popover and you can only use arrows keys to change the color. When I tab to use HEX section the popover closes.

![2020-03-11 13-57-49 2020-03-11 13_59_19](https://user-images.githubusercontent.com/3276087/76459052-1e73a000-63a1-11ea-8018-1ed5cc288be1.gif)

If using a keyboard only, selecting a custom color is impossible because the custom color picker disappears and the focus returns to the first item of the color palette.

**Comment by mtias** [comment]
The custom color picker seems to be closing eagerly on almost every interface I've tried.

**Comment by talldan** [comment]
Seeing this in the paragraph block as well 😱.

Focus is being shifted back to the block. It's hard to tell what's causing it, there's either an event listener somewhere transferring focus, or the popover content is being replaced causing a loss of focus.

**Comment by sstabrizi** [comment]
Just adding a +1 that this is still an issue on the latest Gutenberg release. I encounter the problem in the Paragraph block when trying to change either the background color or text color. It did seem to work properly when trying to change the color for an individual word inside a paragraph block, which is new for this release.

**Comment by roo2** [comment]
This is the same issue as #21163
It might be fixed by #21037

**Comment by tellthemachines** [comment]
This issue can be closed now because the color select tools are no longer in the block toolbar, and color selection in the block inspector is working properly with the keyboard. Thanks everyone!
