### ISSUE TITLE
Spacer Block : Add desktop, tablet and mobile option

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#20820]
For desktop, I need 100px and for mobile and tablet, I need 50px. Currently, you cannot do that. It would be helpful if there are some responsive options.

Thanks

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/10081 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
