### ISSUE TITLE
Search internal links not working properly

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2082]
## Issue Overview
The new feature of Gutenberg 0.6.0, the ability to link to internal post, does not work for me. The block always shows the latest posts and not the searched posts I want.

## Steps to Reproduce (for bugs)

1. Create a link
2. Search for a post

Latest version of Gutenberg, macOS Sierra and Safari used.

## Expected Behavior

Gutenberg should show the posts according to the search.

## Current Behavior

Gutenberg always show the latests posts, no matter what I search : 

<img width="447" alt="capture d ecran 2017-07-29 a 13 50 31" src="https://user-images.githubusercontent.com/2078386/28744618-f3cc6bd0-7464-11e7-910f-691d52122003.png">
<img width="437" alt="capture d ecran 2017-07-29 a 13 50 49" src="https://user-images.githubusercontent.com/2078386/28744619-f55c0c30-7464-11e7-9525-11856634f24c.png">

## Related Issues and/or PRs

Related : https://github.com/WordPress/gutenberg/issues/1040

**Comment by youknowriad** [comment]
This feature is based on the "search" argument of the REST API endpoint https://developer.wordpress.org/rest-api/reference/posts/#arguments

I'm guessing this parameter searches in the post content too. Could it be possible that all these posts contain the text you entered?

The "search" parameter is the only available option to filter posts using the REST API endpoint right now.

**Comment by nicolinuxfr** [comment]
No, it’s not possible. Both were very precise searches and I should have different results than last posts for both queries.

**Comment by nicolinuxfr** [comment]
With 0.70, it’s worse : I have nothing showing as results.

Digging a little deeper, I noticed 400 errors while using the function. For some reason, the URL used to do the search returns this kind of error :

```
{"code":"rest_no_search_term_defined","message":"Vous devez d\u00e9finir un terme \u00e0 rechercher pour ordonner par pertinence.","data":{"status":400}}
```

This is an example of an URL used by Gutenberg for the search : https://voiretmanger.fr/wp-json/wp/v2/posts?search=nolan&per_page=20&orderby=relevance

Interestingly, when you switch the arguments to end with search, it works fine. So for instance : https://voiretmanger.fr/wp-json/wp/v2/posts?orderby=relevance&per_page=20&search=nolan 

I suppose it’s a bug on my part… If someone has an idea to debug this, I’d like to hear it !

**Comment by nicolinuxfr** [comment]
It was a bug on my side, a bad configuration of my server. If you're using Caddy Server, here's the fix : https://caddy.community/t/caddy-and-wordpress-rest-api/2479/9

Anyway, I can close the issue now !
