### ISSUE TITLE
Can't drag and drop any block to a column after upgrade to 7.7

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#20834]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by davouid** [comment]
Went back to 7.6 and fine.

**Comment by youknowriad** [comment]
We just released 7.7.1 with a fix.

**Comment by davouid** [comment]
Great!
