### ISSUE TITLE
Make it possible to determine which blocks are dynamic from the client side.

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#20833]
Hello,

For a feature we're developing we need to add a new attribute (a simple string) to blocks.
So we hooked our code to the blocks.registerBlockType filter and everything is fine except for some dynamic blocks as `core/latest-comments` which use the REST API `block-renderer` endpoint.

Indeed, for this kind of block the render doesn't work anymore due to a REST API verification error.
This error no additional properties are accepted by the endpoint due to this line
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-block-renderer-controller.php#L64

![image](https://user-images.githubusercontent.com/1003778/76527909-43831400-6470-11ea-8154-183533d9a4fc.png)

Because we don't need to add the attribute to dynamic blocks, we wanted to exclude dynamic blocks during registration and needed a way to identify which block is dynamic.

We found a workaround by testing the `save` function of block. Indeed by default the result return by this function is null 
See https://github.com/WordPress/gutenberg/blob/master/packages/blocks/src/api/registration.js#L148
and not overriden by dynamic blocks.

The code below is just an example to illustrate this workaround

```
function addAttributes( settings ) {

	if ( typeof settings.attributes !== 'undefined' ) {

		try{
			if ( isNull( settings.save() ) ){
				return settings;
			}
		} catch( exception ) {
			settings.attributes = assign(
				settings.attributes,
				{
					pllid:{
						type: 'string',
						default: '',
					}
				}
			);
		}
	}

	return settings;
}

addFilter(
	'blocks.registerBlockType',
	'pll/custom-attributes',
	addAttributes
);
```

But I'm not fully satisfied by this code because we need to run the `save` function of the block.

So I'm looking for a better way to identify dynamic blocks or ideas to explore to add a property to the block to identify which kind of block it is.

Thank you very much for the help
Regards

**Comment by talldan** [comment]
@manooweb The original issue you experienced might be happening because dynamic block attributes are declared server side. You might need a server side filter to extend the dynamic block.

But given you could ignore dynamic blocks that also seems like an option. I don't think there's a good way to detect this in client side code, so I've relabeled and re-titled this issue to consider it an enhancement request.

**Comment by manooweb** [comment]
@talldan thank you,

The need is the opposite. We want to remove the attribute we add by applying the filter blocks.registerBlockType only on dynamic blocks because the block-renderer REST API endpoint forbids that by declaration.

However I agree with you, we need a way to remove this attribute by filtering the request before its verification. But unless I'm wrong I didn't find anything to do that between
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-request.php#L523 called here https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L322
and https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L342 where the verification is done https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L953

As I'm writing, I see I have the rest_pre_dispatch in the dispatch function that I can maybe use to manipulate the request as we want. I'm going to explore this way too.

**Comment by manooweb** [comment]
It's ok for me I found a solution by using the `rest_pre_dispatch` filter. The it's no longer necessary to know if a block is dynamic client side.

In our case, we always add the `pllid ` attribute by using the `blocks.registerBlockType` filter in js for all blocks and we remove this attribute only for dynamic blocks server side with something like that.

```
add_filter( 'rest_pre_dispatch', 'pll_get_rest_query_params' ), 10, 3 );
function pll_get_rest_query_params( $result, $server, $request ) {
	$matches = array();
	$pattern = '#^' . preg_quote( '/wp/v2/block-renderer/', '/' ) . '(?<block_name>.*)#';
	if ( preg_match( $pattern, $request->get_route(), $matches ) ) {
		$params = $request->get_query_params();
		$dynamic_block_names = get_dynamic_block_names();
		if ( in_array( $matches['block_name'], $dynamic_block_names ) && isset( $params['attributes'] ) && isset( $params['attributes']['pllid'] ) ) {
			unset( $params['attributes']['pllid'] );
			$request->set_query_params( $params );
		}
	}
	return $result;
}
```

So I closed this issue.
