### ISSUE TITLE
Cover: internal alignment / position

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20836]
The **Cover** block is a pretty nice tool. However, its internal positioning is quite inflexible. You can align individual blocks to left / right / center, but not a group, and not vertically.

It'd be neat to explore some more cardinal positions:

![image](https://user-images.githubusercontent.com/548849/76531825-0f125680-6476-11ea-9421-d98d047f9ef7.png)

Combining them in a single tool should help with clarity:

![image](https://user-images.githubusercontent.com/548849/76532112-70d2c080-6476-11ea-8dd0-1fedee597c2f.png)

Since there is no internal width or padding (at least until the work on dimensions in "Group" is finalized), you should still be able to flush individual blocks to the left or right even with a default set:

![image](https://user-images.githubusercontent.com/548849/76532006-4da81100-6476-11ea-9048-c3a5e667ddea.png)

**Comment by pablohoneyhoney** [comment]
Added a new icon-position in [the icon Figma library](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1970%3A0). 

<img width="300" alt="toolbar-cover" src="https://user-images.githubusercontent.com/25516611/76550704-2b9f9600-6458-11ea-87f7-73181577c49e.png">

<img width="419" alt="Screen Shot 2020-03-12 at 11 54 53 AM" src="https://user-images.githubusercontent.com/25516611/76550790-4c67eb80-6458-11ea-8daa-63fc3d286888.png">

**Comment by pablohoneyhoney** [comment]
Also with the small detail of highlighting the current position. It does depend on the contrast of the accent color.

<img width="300" alt="Paragraph-block-active-1" src="https://user-images.githubusercontent.com/25516611/76552124-4de5e380-6459-11ea-83fc-49553e3560ec.png">
<img width="300" alt="Paragraph-block-active" src="https://user-images.githubusercontent.com/25516611/76552126-4e7e7a00-6459-11ea-822e-3de2e5b44d7b.png">

Or scale slightly the dot to 4px

<img width="300" alt="Paragraph-block-active-1" src="https://user-images.githubusercontent.com/25516611/76553076-a3ba8b80-6459-11ea-9257-fa9db98f4cb7.png">
<img width="300" alt="Paragraph-block-active" src="https://user-images.githubusercontent.com/25516611/76553084-a4532200-6459-11ea-9353-4a79df209008.png">

**Comment by mtias** [comment]
Yes, that's why in the original I was using gray for the non active ones. It's a nice detail, I think.

**Comment by pablohoneyhoney** [comment]
Here another iteration. 

<img width="933" alt="Screen Shot 2020-03-12 at 12 28 56 PM" src="https://user-images.githubusercontent.com/25516611/76555418-34469b00-645d-11ea-94b1-7a2c2db08bf2.png">

And wonder if that function could afford direct manipulation. 

<img width="926" alt="Screen Shot 2020-03-12 at 12 29 08 PM" src="https://user-images.githubusercontent.com/25516611/76555489-55a78700-645d-11ea-924d-45fd58914cd8.png">

Or even fade out the styles of the cover to focus on the specific interaction.
<img width="922" alt="Screen Shot 2020-03-12 at 12 29 15 PM" src="https://user-images.githubusercontent.com/25516611/76555555-77a10980-645d-11ea-9f49-ed60595d7f51.png">

Note that these screenshots are not 100%. Click to view.

**Comment by ItsJonQ** [comment]
👋 Haiii! I started experimenting with creating the AlignmentControl component.

I have a working prototype here:

👩‍💻 Code
https://codesandbox.io/s/align-control-u9uwe

✨ Demo
https://u9uwe.csb.app/

![Screen Capture on 2020-03-19 at 19-07-46](https://user-images.githubusercontent.com/2322354/77122901-2670b700-6a15-11ea-9a8f-2ae2c73e7f3d.gif)

The Demo showcases an `AlignmentControl` and an `InteractiveGridOverlay` (an interactive counter-part to the control).

Some notable features:

* The AlignmentControl handles focus like a `select` or any other HTML control element would
* When focused, use `up`, `down`, `left`, `right` keyboard commands would move the alignment within the 9x9 grid
* The components have `onChange` callbacks to communicate
* Components can be controlled (accepting new incoming alignments)
* Alignment definitions are flexible, like CSS. Meaning, `top center` or `center top` are both acceptable

**Comment by ItsJonQ** [comment]
@pablohoneyhoney I've made adjustments to my prototype to better match your designs!
I've also created a smaller icon for Align control:

![Screen Capture on 2020-03-20 at 11-36-13](https://user-images.githubusercontent.com/2322354/77179729-3d5beb80-6a9f-11ea-8add-230f92c201a9.gif)

Due to the dynamic nature of the icon, from a technical perspective, I think it may be better to create it using HTML/CSS rather than SVG. But, we'll match the Icon dimension/sizes as best as possible to ensure that it looks consistent with the other icons.

**Comment by ItsJonQ** [comment]
Started coding it! Working branch:
https://github.com/WordPress/gutenberg/tree/try/cover-alignment-control

So far, I've focused exclusively on the new Control component.
Will create a PR once it gets integrated into the Cover block.

**Comment by pablohoneyhoney** [comment]
Nice! Have we considered a direct manipulation in the block canvas instead of a panel control (dropdown)? This was a premature mock up:


![](https://user-images.githubusercontent.com/25516611/76555489-55a78700-645d-11ea-924d-45fd58914cd8.png)

**Comment by ItsJonQ** [comment]
@pablohoneyhoney Yes! I've experimented with direct controls in my prototype:

https://u9uwe.csb.app/

Although, the aesthetics I have make them look like 9 cells/boxes, rather than points (like yours). But the idea is the same :).

One tricky thing re: the Direct manipulation overlay.
The "edit" mode for this needs to be enabled/disabled somehow.

For example (not saying this is how it should be):

* Click "Align" from toolbar
* Edit mode engages
* Makes changes (or not)
* Click "Cancel" to revert changes. Or. Click "Apply" to apply changes
* Edit mode disengages

Hope this makes sense 🙏 
If it does, it would be cool to see some rough flows or designs for this 😍

**Comment by mtias** [comment]
I think we should get it into the toolbar first — I can see multiple issues with the in-canvas presentation based on background / image / video presence in the cover block.
