### ISSUE TITLE
[ Navigation block ] Remove the block navigator in the sidebar

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20846]
There are 2 navigator interfaces for the navigation block, in the toolbar and the sidebar. I would recommend removing one of them. I actually like the sidebar for this as it feels a great place, there are also some good issues to iterate that. Although, I also think the modal works well. I'm a bit torn which way to recommend, but I do feel just one is better.

![nav-multiplenavviews](https://user-images.githubusercontent.com/253067/76560611-6d046580-6499-11ea-8b58-19491fbc3f64.png)

**Comment by ZebulanStanphill** [comment]
I'm of the opinion that the main Block Navigation menu should be souped up with additional functionality (think [Divi Layers View](https://www.elegantthemes.com/blog/theme-releases/divi-layers-view); see #11408) and turned into a pinnable sidebar. If that happened, I would prefer removing the Navigation block's copy entirely, or at least revamping it to be more specific to the block by including the ability to edit link titles and URLs straight from that interface... not unlike the current wp-admin Menus UI. See #20748.

**Comment by karmatosed** [comment]
@ZebulanStanphill whilst I also agree that adding functionality to the block navigator wouldn't be a bad thing, I do think that reducing to just one instance can be done earlier and the two things aren't connected. Right now, having 2 places is a little confusing, so iterating that could help.

**Comment by karmatosed** [comment]
Just updating this with some iterations that have gone on outside this issue. There is a consideration to have the block navigator become the primary interface for sub-navigation. If this happens, I would suggest that the toolbar block navigator should be removed, just keeping the sidebar one.

**Comment by ZebulanStanphill** [comment]
@karmatosed A primary interface shouldn't go into the inspector, which is for secondary controls.

**Comment by karmatosed** [comment]
@ZebulanStanphill my comment was about it being used for the sub-navigation adding #21727 has more information.

**Comment by ZebulanStanphill** [comment]
@karmatosed Oh, I guess I misunderstood your post. You're suggesting that the interface in #21727 would replace the Block Navigation UI currently present in the toolbar, right? That makes sense.

**Comment by karmatosed** [comment]
Yes, that's idea @ZebulanStanphill.

**Comment by MichaelArestad** [comment]
I propose we remove the navigator in the sidebar for a few reasons:
* It isn't adding any block-specific functionality.
* It can be a [source of confusion](https://github.com/WordPress/gutenberg/issues/19691) when actually trying to use it.
* There is already a block navigator at the top that does the job pretty well.

**Comment by talldan** [comment]
Closed by #23022
