### ISSUE TITLE
Link modal suggestions only include posts when they should also include pages and CPTs

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2084]
The link modal links suggestions implemented in #1985 currently searches just for posts.

<img width="314" alt="screen shot 2017-07-24 at 13 58 25" src="https://user-images.githubusercontent.com/272444/28524397-38a61350-7078-11e7-85ee-0e19fab74f5b.png">

Instead, the current implementation in WordPress searches also for pages and Custom Post Types (any public post):

![screen shot 2017-07-29 at 17 39 06](https://user-images.githubusercontent.com/1682452/28746065-5593b8f8-7485-11e7-9cc7-ab9ce4993130.png)

As mentioned in #1985, this is a limitation of the REST API. See the related Trac ticket: https://core.trac.wordpress.org/ticket/39965. Regardless of the reason why, right now there's no feature parity with the current WordPress implementation.

There are also performance concerns, since by default the REST API returns _all_ the post fields including the post content. The response can be huge in size, even several hundreds KB or more than 1MB with very long posts. See related considerations on:
https://core.trac.wordpress.org/ticket/38920
https://core.trac.wordpress.org/ticket/38922
and especially:
"REST API: Provide interface to include or exclude specific fields from response JSON"
https://core.trac.wordpress.org/ticket/38131

**Comment by westonruter** [comment]
> There are also performance concerns, since by default the REST API returns all the post fields including the post content. The response can be huge in size, even several hundreds KB or more than 1MB with very long posts.

For this, do note that you can make the request with `?context=embed` and the `content` field will be excluded. That would be a good short term fix.

**Comment by afercia** [comment]
I'd suggest to milestone https://core.trac.wordpress.org/ticket/39965 (add search endpoint) for 5.0.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520529558000186)._

**Comment by braders** [comment]
In the current editor it is also possible to inject non-WordPress resources with the `wp_link_query` filter (For example allow selection of archive pages). It would be great if this functionality (or similar) was supported by the new editor.

**Comment by danielbachhuber** [comment]
@felixarntz is going to do a first pass on this against Gutenberg over the next week.
