### ISSUE TITLE
Navigation block: show when adding a link

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20847]
The current version of the navigation block makes it hard to see when a link is set or when that link is active to edit. This will, of course, be dependent a little on the theme,  however, the 'link' icon doesn't change state to active.

![image](https://user-images.githubusercontent.com/253067/76561395-2283e880-649b-11ea-92a7-ddf8a28461da.png)

I would recommend something along these lines for an iteration, cc'ing @jasmussen to check alignment with toolbar styling.

<img width="835" alt="Frame 1" src="https://user-images.githubusercontent.com/253067/76561486-4d6e3c80-649b-11ea-936c-fecb5d09f093.png">

**Comment by karmatosed** [comment]
This also on sub-nav, should probably show the sub-navigation menu open, not close it:

![image](https://user-images.githubusercontent.com/253067/76570944-50265d00-64ae-11ea-94d6-dc7b762ea4b2.png)

**Comment by jasmussen** [comment]
Definitely something to think about. Right now I find it slightly weird that you can create a menu item _at all_, and not have it be linked. I can't really think of a use case for that — the two seem intrinsically linked.

**Comment by karmatosed** [comment]
So, the root of that is creating a base for sub-navigation @jasmussen, for example, a section for 'services' and then just listing pages under it. I can fall both sides of the argument so it's worth debating and find a way through.

**Comment by jasmussen** [comment]
Right now we're attempting to have both direct manipulation of menu items right in the canvas. Which is noble. And on top of that, menu editing in the "block navigation" menu (which should maybe say Edit Menu instead?) — the latter seems to be able to scale fairly well. The former feels somewhat like an experiment to me. And at some point we should consider whether that experiment is successful or not.

**Comment by karmatosed** [comment]
I think that's valid, there has to be a cut-off point to any experiment. That said, I think showing when something is selected to be a link could be a foundation here.

**Comment by noisysocks** [comment]
In `nav-menus.php` all menu items will have a link so this isn't necessary for that body of work, though we will want to fix this for Navigation in FSE.

**Comment by mapk** [comment]
In [today's triage meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1597162942271500), the Design Team did not have any strong opinions on this one.

It was noted that this proposal would align with how links work elsewhere. Looking at the Paragraph block:

![Screen Shot 2020-08-11 at 9 29 59 AM](https://user-images.githubusercontent.com/617986/89923723-df4ab480-dbb5-11ea-8ec4-417c3ab3f836.png)

**Comment by paaljoachim** [comment]
Hey @shaunandrews 

Any thoughts on this issue? Do you think it is still valid?

**Comment by shaunandrews** [comment]
When looking at the way the link button works when editing text, its not really an "open/close" toggle. Instead, it serves as a way to _unlink_ previously linked text.

This is certainly strange when compared to the other RichText tools (like Bold and Italic), but I'm not sure we should try to mimic the toggle behavior just for the Link/Navigation block.
