### ISSUE TITLE
[Question] Inserter/block handles missing on new site

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20840]
On a blank, new site, the inserter is missing in the editor.
Also, the block "handles" are missing, so I can't drag blocks around and into other blocks (like groups).
Is there an editor option for enabling inserter and block handles?

**Comment by WesternWeb** [comment]
I am missing the inserter + symbol too between the blocks when hovering. Several of my clients have complained

**Comment by strarsis** [comment]
The issue is caused by the Gutenberg plugin: Disabling it solves the issue.
However, I want to use the extra functionality and blocks provided by the Gutenberg plugin.

**Comment by paaljoachim** [comment]
Hi

Can you @strarsis or @WesternWeb please take some screenshots to show us what is going on? Do also add a step by step instruction. It would be good with additional details as to what you experience. If you can just edit your comment that would be great.

Block handles: Move the cursor to the left side of the toolbar. Drag handles should show up.
![Screen Shot 2020-03-17 at 17 12 03](https://user-images.githubusercontent.com/5323259/76876705-9b57bb80-6872-11ea-96be-39f5c15636cd.png)

Additional screenshots:

New Inserter 7.7
![Screen Shot 2020-03-17 at 17 14 21](https://user-images.githubusercontent.com/5323259/76877100-32247800-6873-11ea-8ea1-90845f92a9e8.png)

Inserter and outline 7.6 and earlier.
![Screen Shot 2020-03-17 at 17 15 43](https://user-images.githubusercontent.com/5323259/76877166-4cf6ec80-6873-11ea-9f7a-cf2d557575e3.png)

**Comment by strarsis** [comment]
@paaljoachim: This explains it: The handles are collapsible now in Gutenberg editor and the user has to uncollapse them first.

**Comment by paaljoachim** [comment]
@WesternWeb and @strarsis 
Is there anything else we need to address in this issue?

If not then we can close it.
Click the Close button.
Thanks.

**Comment by strarsis** [comment]
@paaljoachim: Well, it turns out that, additionally to not knowing the new collapsible feature, another plugin added some extra styles that directly interfered with the handles.

**Comment by paaljoachim** [comment]
Hey @strarsis 

Ahh. The best way to test it to take a clone of the site, or just quickly deactivate the various plugins (except Gutenberg) and switch to one of the Twenty something default themes. Then retest. If the problem goes away then it can be a plugin conflict which you found.

Btw there are also some difficulties with the new user interface but it is being worked on.

**Comment by strarsis** [comment]
One important thing concerning the editor options and how they influence the handles:
In the editor options, there is the option "Top Toolbar".
When this option is disabled, the toolbar docks to the selected block.
With the Gutenberg plugin enabled, and the "Top Toolbar" disabled,
the toolbar docks to the selected block as usual, but with the collapsing drag handle.

There seems to be an additional issue with the Gutenberg plugin:
When the "Top Toolbar" option is enabled, the controls go to the top toolbar as the option says.
However, the drag handle completely disappears, only the arrow buttons for moving the block up and down in order are available in the top toolbar.
Hence with the "Top Toolbar" in use a selected block can only be re-ordered relative to its siblings, 
it is not possible drag and drop it into a different parent block, like a group block.

**Comment by paaljoachim** [comment]
Hey @strarsis 

It sounds like we need to create a new issue mentioning that the block drag drop handles are gone in 7.7 when the top toolbar is active.

I am looking through: https://github.com/WordPress/gutenberg/issues/18667
"Advancing the toolbar" 
Looking for more information.

@jasmussen

**Comment by strarsis** [comment]
@paaljoachim: The issue seems to be related, but no "dragging anchor point" (as they call it) is mentioned in relation to being unavailable when the top toolbar is enabled.

**Comment by tomwalkr** [comment]
Hey, just ran into this problem and got here from a search. Removing the handles from the UI when "Top Toolbar" is enabled is _immensely_ confusing if you are an end user - the drag handles are part of your workflow, you change one setting accidentally, and then they're gone and you have no idea how to get them back.

**Comment by paaljoachim** [comment]
Yes. At present there are no drag handles when one uses the "Top Toolbar". There are no suggested solution that I know of at the moment. In the mean time I guess one will have to click the up or down arrow to move each block.

**Comment by tomwalkr** [comment]
Not really a workaround as the up/down arrows don't allow you to move things into groups/columns/etc.

**Comment by strarsis** [comment]
Right, the arrows don't allow to get out/inside blocks.

**Comment by jasmussen** [comment]
I believe this can be closed in favor of #21407. If this was in error let me know and we'll just reopen!
