### ISSUE TITLE
Block Focus

### ISSUE THREAD

**Issue by WesternWeb** [WordPress/gutenberg#20843]
**Is your feature request related to a problem? Please describe.**
The new block UI makes it difficult to determine where the block is.

**Describe the solution you'd like**
Some type of background or background to denote the block boundaries. It is hard to see where the edges of the block are and where to click to edit a block.

Also, there needs to be some type of handle next to the up and down arrows to denote a spot to drag the block.

**Comment by karmatosed** [comment]
I think this issue: https://github.com/WordPress/gutenberg/issues/20875 is similar. For now, closing this one. If it's not the same, please comment and we can always reopen.
