### ISSUE TITLE
Cannot update child page to (no parent) with trashed parent page without making another change

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#20855]
**Describe the bug**
When the parent page of a child page is trashed the Parent Page dropdown automatically changes to (no parent) but the post cannot be updated to apply the (no parent) setting without first changing it to another page, and then back to (no parent) or making another change.

**To reproduce**

1. Create two pages, make one a child of the other
2. Trash the parent page (Do not delete the parent page from the trash)
3. Edit the child page and note (no parent) is set, but the post cannot be updated without changing the setting or making another change to the post.

**Expected behavior**
To be able to Update the child page with (no parent) set by default.

**Screenshots**

![no parent update highlight](https://user-images.githubusercontent.com/1900444/76581905-46e7c100-64ab-11ea-9304-0388d6491144.jpg)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 79

**Additional context**
- WP 5.3.2

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7.
Twenty Twenty One
Gutenberg plugin 10.4.1

I made a parent page.
Then I made a child page which then was associated with the Parent Page.
I trashed the parent page.
Went back to the child page and was able to make changes and save.

I would say that this issue as been fixed. Please let me know if I made a mistake. As the issue can always be reopened if need be.
