### ISSUE TITLE
Iterate placeholder state for navigation block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20853]
This was found in Chrome. If you add a navigation block to a column block you get the following:

![image](https://user-images.githubusercontent.com/253067/76571257-f70af900-64ae-11ea-826b-48f5b0b43a87.png)

Now, it's a small spot, but I would expect maybe it doesn't break out of the container.

cc @jasmussen as this might be due to interface changes.

**Comment by jasmussen** [comment]
Excellent ticket. 

Outside of the obvious improvements that can be made — rephrase, or rephrase when small like this, I would suggest this also opens up a separate question: **why do we have a placeholder state for this menu at all**?

It may be just me, but I have not a single time created a menu and pressed "Create Empty". Every single time I've created a menu, I click "Crete from all top-level pages", to the point that this seems redundant. 

An added benefit to getting rid of the placeholder state is that it more immediately becomes obvious to a user what they just inserted. Right now many of our placeholders look exactly the same: squint and you can't tell the difference between a navigation menu and an embed placeholder. By immediately outputting a menu that will likely be the default choice anyway, we simply smooth out the process.

_That doesn't mean we should remove all placeholders, just that we should not default to using them._

**How do you create an empty menu, then?**

For one, I'd consider replacing this menu icon with an "Edit Menu" label:

<img width="292" alt="Screenshot 2020-03-13 at 08 01 28" src="https://user-images.githubusercontent.com/1204802/76597599-1e8ab180-6501-11ea-8809-f7ae2201d797.png">

And I'd then consider adding some quality of life buttons to this interface:

<img width="371" alt="Screenshot 2020-03-13 at 08 01 21" src="https://user-images.githubusercontent.com/1204802/76597614-277b8300-6501-11ea-823b-19a5a8b225ac.png">

For example a "Reset" or "Clear Menu" button. If we combine that with an "are you sure", that seems fine.

**Comment by karmatosed** [comment]
> It may be just me, but I have not a single time created a menu and pressed "Create Empty". Every single time I've created a menu, I click "Crete from all top-level pages", to the point that this seems redundant.

I can actually see a use case for this, but do agree it's probably not as common. For example, building a particular type of menu from scratch. An example would have been social links but we have that now. I wonder if we default to having build from all though if you have a lot that could be 'a lot' of removing pages?

Maybe the edit could be a 'remove all' pages? I don't mind that idea of a reset/clear at all.

**Comment by jasmussen** [comment]
I do like the inverse thinking of defaulting to a good default and then providing options to account for what's possibly an edgecase.

**Comment by tellthemachines** [comment]
There's a "create from existing menus" option being worked on [here](https://github.com/WordPress/gutenberg/pull/18869). If we remove the placeholder, how might that be approached?

**Comment by karmatosed** [comment]
@tellthemachines let me mark this for exploring in design as I think it could do with a holistic approach.

**Comment by jasmussen** [comment]
> There's a "create from existing menus" option being worked on here. If we remove the placeholder, how might that be approached?

I'd honestly put that in the toolbar! I'll respond on the ticket.

**Comment by karmatosed** [comment]
@jasmussen awesome, thanks.

**Comment by karmatosed** [comment]
Noting just changing the title of this issue so this can now focus on some iterations to the first state.

**Comment by karmatosed** [comment]
I sat down to take a look at iterating here. Here is what we have now:

<img width="756" alt="1" src="https://user-images.githubusercontent.com/253067/80112900-8a891c80-8579-11ea-8f3c-d002855e529e.png">


There is other work in #21727 that starts from:

<img width="403" alt="2" src="https://user-images.githubusercontent.com/253067/80112914-8eb53a00-8579-11ea-86e6-7d9cc4043f10.png">

As noted, we could either have then either add an icon, perhaps like this:

<img width="403" alt="3" src="https://user-images.githubusercontent.com/253067/80112977-9e348300-8579-11ea-9f3b-550ead8b1fc6.png">

Alternatively, having the option under the ellipsis could work:

<img width="509" alt="4mock" src="https://user-images.githubusercontent.com/253067/80113012-a8ef1800-8579-11ea-9f73-95441d3c820a.png">

As far as feedback goes, I think deciding where the option should go is a great next step.

**Comment by jasmussen** [comment]
Thanks for exploring this! Just looking at it I'm getting a possibly crazy idea — what if instead of using the Plus button appender, we use the text one and customize the placeholder text? We might even wrap that text appender inside menu item classes so that it can look like a "menu item placeholder". Too crazy?

**Comment by karmatosed** [comment]
> Thanks for exploring this! Just looking at it I'm getting a possibly crazy idea — what if instead of using the Plus button appender, we use the text one and customize the placeholder text? We might even wrap that text appender inside menu item classes so that it can look like a "menu item placeholder". Too crazy?

I don't think that's too out there. Just to see if on same page it could look like this?

<img width="403" alt="Frame 5" src="https://user-images.githubusercontent.com/253067/80205761-16a34e80-8623-11ea-91b6-fa96b2d2572e.png">

**Comment by jasmussen** [comment]
Oh that's right I did forget that you can add more than one type of thing there, gosh darnit. But yes that was what I was thinking, if the menu item was square and blue! Hmm thanks for trying that, let me sleep on it :D

**Comment by dwolfe** [comment]
@jasmussen The placeholder state has always seemed off to me too, and a comment you made on a different issue crystallized it for me: **an empty navigation block has no value**. I think the choice in the placeholder state isn't empty/full, but rather shortcut/manual. "Build me a menu from this existing list of stuff" or "I want to curate my own list of links." It's a subtle shift, but I think there's value in both approaches, we just need to present them in the right way.

**Comment by jasmussen** [comment]
> It's a subtle shift, but I think there's value in both approaches, we just need to present them in the right way.

Yep. @shaunandrews pointed out that currently menu items aren't added to a menu when new pages are added. I wonder if we can make it so that when you insert a navigation block, by default it's chained to what pages you have, and when you make an edit, it becomes customized and unchained — with a snackbar notice informing you of said fact.

This is a half baked idea, not digestible yet. But sharing in case it inspires either of you.

**Comment by dwolfe** [comment]
@jasmussen You triggered an idea earlier - one issue I noted about the current placeholder is that "Top-level pages" doesn't give you a sense of what the resulting menu will be - I originally thought that we should at least improve that button with a badge showing the number of links that would be created, but as I was thinking about serving the use cases I mentioned above ("Use a shortcut" or "I'll do it myself"), I wondered if a group of selectable elements might cover a wider range of possibilities:

![Screen Shot 2020-04-28 at 1 40 58 PM](https://user-images.githubusercontent.com/1348738/80535998-8a609680-8956-11ea-8a51-6f3057ec8578.png)

This is a really rough visual, but hopefully the idea comes through. The dropdown (from #18869) could allow the user to start with any of a few different options – top-level pages would be one, plus any existing menus, and probably an "empty" option – which could then be further customized with a few clicks. (Basically bulk add - the advantage is speed, versus adding/removing links one-by-one, which would each require multiple clicks and possibly input.)

I haven't thought through all the details, but the bottom sketch above imagines how it could adapt to a narrower space.

**Comment by jasmussen** [comment]
Lots of small improvements that can benefit the navigation block. So long as we don't paint ourselves into a corner with tying those tightly to the `Placeholder` component, it seems like a fine iterative step.

However to be more clear about the limitation we've seen with the Placeholder component: it encourages form-like design that looks nothing like the block will, when rendered. This is increasingly going to be a problem as we move towards full site editing with lavish templates and accurate WYSIWYG.

Here's TwentyNineteen rendered, for example:

![rendered](https://user-images.githubusercontent.com/1204802/80569393-22af5780-89f9-11ea-81dc-27045958fec5.jpg)

Now imagine the not too distant future where the above is simply a page template waiting to be customized by a user. You might be looking at this:

![with-placeholder](https://user-images.githubusercontent.com/1204802/80569553-7326b500-89f9-11ea-8dff-4c196b252df6.jpg)

That's an exaggerated sketch, but it's a reminder that it would be good to start thinking about how the Placeholder component affects templates, and what we can do to minimize the massive shift in layout it causes.

**Comment by draganescu** [comment]
Closing this in favor of #23207

**Comment by mtias** [comment]
Now it's closed :)
