### ISSUE TITLE
Clicking layout inserter brings up a long Block window

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20857]
**Describe the bug**
I am not sure what to call this. But looking at the behavior I feel like almost wanting to call it a bug.

**To reproduce**
1. Click the layout inserter icon.
2. Notice the block window show up.

**Expected behavior**
Not sure, but I do feel it is something we need to take a closer look at. 
Perhaps I do expect it to resize to fit into the available space where I clicked the inserter in the page layout.

**Screenshots**
![Clicking-in-layout-Inserter](https://user-images.githubusercontent.com/5323259/76594836-6a862800-64fa-11ea-8275-c34e714b951c.gif)

**Comment by karmatosed** [comment]
This seems fairly reasonable to me, it's filling up space from where you open the library. To compare:

![image](https://user-images.githubusercontent.com/253067/76794362-bff25b80-67be-11ea-82f3-ce527a62c4b7.png)

For now, let's close this but perhaps something to iterate if others feel it is. We can always reopen.
