### ISSUE TITLE
Bug: Inserter icon on top of bottom breadcrumb bar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20858]
**Describe the bug**
I noticed when scrolling when using the theme Twenty Twenty (I also tested Twenty Nineteen) that the black inserter icon shows up on top of the bottom breadcrumbs bar.

**To reproduce**
1. Scroll and notice the location of the block inserter icon.

**Expected behavior**
I expected the icon to go underneath the bottom breadcrumbs bar.
A z-index issue.

**Screenshots**

![Screen Shot 2020-03-13 at 07 23 04](https://user-images.githubusercontent.com/5323259/76595349-a8378080-64fb-11ea-8fb7-dd24f1e1162f.png)

Hovering over the icon:
![Screen Shot 2020-03-13 at 07 23 19](https://user-images.githubusercontent.com/5323259/76595357-af5e8e80-64fb-11ea-8463-cfa6770f0b84.png)

I am using:
Chrome
on my Mac
in Desktop Server (local site)

**Comment by karmatosed** [comment]
I am unable to replicate this today, but that could be because of this being a few days old.

![image](https://user-images.githubusercontent.com/253067/76794250-7d308380-67be-11ea-8b3d-3e56ae1b9c46.png)

For now, I am going to close this but if it persists please report it again @paaljoachim.

**Comment by paaljoachim** [comment]
Hey Tammie

Click to the left of where you see the black inserter so the area is selected. Like so.
If you click below the area then the inserter will go below the bottom document bar.

![z-index-inserter-Gutenberg](https://user-images.githubusercontent.com/5323259/76795036-950d0500-67c8-11ea-92d5-2265cc4b3ee9.gif)
