### ISSUE TITLE
Navigation block toolbar has indexing issues on position

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20852]
The navigation block toolbar, particular for sub-navigation when on Chrome seems to get a little stuck.

![2020-03-12 21 57 46](https://user-images.githubusercontent.com/253067/76570289-ece7fb00-64ac-11ea-83da-57e85d2bde29.gif)

**Comment by karmatosed** [comment]
This one feels similar to https://github.com/WordPress/gutenberg/issues/20940. However, it might be worth exploring why in that one multiple links appeared.

**Comment by talldan** [comment]
I've put together two PRs which should make this a lot better: #21033, #21035
