### ISSUE TITLE
Block validation failed with only activated plugin 7.7.1

### ISSUE THREAD

**Issue by Vanillabacke** [WordPress/gutenberg#20866]
**Describe the bug**
Enviroment:
- Mac OS 10.13.1
- Google Chrome 80.0.3987.132
- WordPress 5.3.2-de_DE
- Gutenberg 7.7.1

I've developed a custom block and the validition works fine with the build-in Gutenberg Editor.
When I activate the standalone Gutenberg plugin (7.7.1) and create an instance of the custom block in the editor and reloading the page after saving it, the block gets an validation error. The strange thing is, that the generated content in save and the retrieved from post body is equal to each other.

I can  deactivate the Gutenberg plugin, reload the page and the block is working fine again without any errors. Is there a new way of validation like prop validation?

```
Content generated by save function:

<div class="video-player" id="vPlayer-1584097252202" data-settings="playPause,volume,seekbar,fullscreen,quality" class="wp-block-vimeo-video"><div class="video-player__wrapper"><div class="dimension" style="padding-bottom:56.25%;"></div><video class="video-player__video"></video></div></div>

Content retrieved from post body:

<div class="video-player" id="vPlayer-1584097252202" data-settings="playPause,volume,seekbar,fullscreen,quality" class="wp-block-vimeo-video"><div class="video-player__wrapper"><div class="dimension" style="padding-bottom:56.25%;"></div><video class="video-player__video"></video></div></div>

```

**Comment by youknowriad** [comment]
Would you be able to provide a plugin containing your custom block (a zip or something)?

**Comment by Vanillabacke** [comment]
I've found the problem.

In 'save' i have returned something like this:
```
const RenderedHTML = (
	<div class={classNames}>
		some code ... 
	</div>
)


if( attributes.url ) {
	return (
		<a href={attributes.url} 
			target={isBlank && '_blank'}
        	rel={isBlank && 'noopener noreferrer'}
			>
				{ RenderedHTML }
		</a>
	)
} else {
	return (
		RenderedHTML
	)
}
```



And the problem was, that this was accepted with the build-in editor:
```
return (
	RenderedHTML
)
```

And the solution was to wrap it in an element like a div:
```
return (
	<div>{RenderedHTML}</div>
)

```
