### ISSUE TITLE
Add color controls for text and background into the toolbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20862]
This issue is based on:
"Add option to add text color to specific text inside RichText"
https://github.com/WordPress/gutenberg/pull/16014

Associated issues:
"Text color icon appears and disappears"
https://github.com/WordPress/gutenberg/issues/20861
"Add a way to add inline text background color"
https://github.com/WordPress/gutenberg/issues/20835

This issue is focused on the color control to be added to the toolbar.
@karmatosed has an issue I am not able to find right now in relation to consolidating the color controls and only changing the name while keeping the color option the same.

**Comment by mtias** [comment]
This is the issue: #20197. I don't think it should be done across all blocks as context is important and the toolbar is a way to communicate what are the main actions of a block.

**Comment by paaljoachim** [comment]
Great you found it!
Thanks!
