### ISSUE TITLE
Please bring back block borders in the editor

### ISSUE THREAD

**Issue by charlottehobbit** [WordPress/gutenberg#20869]
Dear Wordpress team,

Please bring back the block borders you removed a few Gutenberg updates ago, brought back (sort of) and then removed AGAIN with the latest Gutenberg update to 7.7.1. The borders are really useful to see which blocks are nested into each other, especially when moving around blocks and putting them into containers. Working without them is really frustrating because it's impossible to see what I'm doing.

Anyone with me? I can't imagine being the only one who's annoyed by the removing of this feature...

**Comment by mtias** [comment]
If you press escape on any block you should be able to see the borders to be able to move / select. Could you check if that flow works for you? There's also a tool in the top left that switches between select and edit.

**Comment by karmatosed** [comment]
As there is a way to bring borders in, for now I am going to close this. That doesn't mean we can't iterate and improve but let's focus that in other issues.
