### ISSUE TITLE
Text color icon appears and disappears

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20861]
Continuing discussion from:
"Add option to add text color to specific text inside RichText"
https://github.com/WordPress/gutenberg/pull/16014

Into a new issue. Where we can focus.
1. Text color icon appears and disappears from toolbar. 
2. Bring colors by the block for some blocks: https://github.com/WordPress/gutenberg/issues/20197
3. Background color issue here: https://github.com/WordPress/gutenberg/issues/20835

![Text-color-icon-appear-disappear](https://user-images.githubusercontent.com/5323259/76598917-2861e400-6504-11ea-9c12-823c0a88bcc0.gif)

Comments from:
@ellatrix 
https://github.com/WordPress/gutenberg/pull/16014#pullrequestreview-354428911

> Looks good to me. Not sure if I like the conditional placement of the button, but we can experiment with that. Also think it would be nicer to consolidate the custom color popover, but also could be adjusted later.

@mapk 
https://github.com/WordPress/gutenberg/pull/16014#pullrequestreview-354627103

> I totally agree with @ellatrix's comment. Having it appear and disappear is somewhat odd. But I just tested this out and it was working great. I'm all for getting this in and iterating later.

@afercia 
https://github.com/WordPress/gutenberg/pull/16014#issuecomment-594010817

> Saw this new feature today and I'd totally second that. I would expect to find controls where I saw them the first time. Instead, they just disappear and appear in a new place. Not to mention that, from an accessibility perspective, the accessibility team has pointed out several times that the continuous appearing / disappearing of controls is highly confusing.
> 
> I'd definitely recommend to further iterate on this soon.

---------------

**Comment by mapk** [comment]
@paaljoachim do you have a solution around keeping the color icon visible all the time? Does it just show the default color for the text until the user selects the custom color letters?

**Comment by MDWolinski** [comment]
An option I proposed is that the options (Bold, Italic, Text Color, Links, etc) show in the toolbar if they are used in the document (or the most recently used 3 or 4).  If they are not used, then they can be collapsed into the dropdown menu.

**Comment by paaljoachim** [comment]
I do think that the most used icons such as Bold, Italic, Link should stay in the toolbar. 
If others inside the "More rich text controls" are being used than these should be added on to the toolbar.

![Screen Shot 2021-01-10 at 18 19 25](https://user-images.githubusercontent.com/5323259/104130350-73d95e80-5370-11eb-80bd-d63b40053bf4.png)

--

Coloring a single word:
![Screen Shot 2021-01-10 at 18 24 03](https://user-images.githubusercontent.com/5323259/104130548-98820600-5371-11eb-8bfa-50e2adb77448.png)

New approach: Selecting any other word in the block still shows text color, but does not show the color of the default text.
![Color-inline](https://user-images.githubusercontent.com/5323259/104130531-87d19000-5371-11eb-9b56-3d15874d546f.jpg)

It still keeps the text color icon in the toolbar as it has been used in the text.

**Comment by kellychoffman** [comment]
Looks like this one has been updated (Text color icon has been moved and is always present) and is no longer an issue. 🎉Reopen if I am mistaken. 

<img width="423" alt="Screen Shot 2021-05-18 at 12 55 55 PM" src="https://user-images.githubusercontent.com/5835847/118715450-76ddd300-b7d8-11eb-8b1e-053d96663162.png">

**Comment by paaljoachim** [comment]
Hey Kelly @kellychoffman 

This is what I see:

https://user-images.githubusercontent.com/5323259/118727348-e7b1d900-b832-11eb-84e8-0484284dd304.mp4

Clicking the text that has the inline color shows the A with the red line below it. Clicking any other place the A is not seen.


WordPress 5.7.2.
Twenty Twenty One
Gutenberg plugin 106.1

**Comment by jasmussen** [comment]
Having lived with the current behavior for a while, I'm starting to think it's the best approach with the current design, and that simply showing the color icon always is not going to be a good user experience.

**Comment by ellatrix** [comment]
Fixed in #21892.
