### ISSUE TITLE
Icons missing from toolbar menu in Gutenberg 7.7?

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#20863]
Hey

Testing Gutenberg 7.7.1. The styling seems off to me, and icons seems to be missing from the toolbar submenu. I personally prefer the styling of Gutenberg shipped with WP 5.3. A bug or a shift en design?

[Gutenberg 7.7 screenshot](https://i.postimg.cc/jqgnw0kZ/gutenberg-7-1.png)

[Gutenberg shipped with WP 5.3 screenshot](https://i.postimg.cc/rFRX1xg7/gutenberg-from-wp-5-3.png)

Best regards
Bjarne

**Comment by youknowriad** [comment]
Hi there!

That's a design choice made on purpose. See #18667 for more details.

Thanks.
