### ISSUE TITLE
Block patterns: hide sidebar when no patterns are registered

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#20867]
**Describe the bug**
When there are 0 block patterns registered, the sidebar shows up empty:

![screenshot-2020-03-13-at-12 03 56](https://user-images.githubusercontent.com/87168/76616764-69222300-652d-11ea-901b-7ab94777362b.png)

Kudos @akirk for spotting.

**To reproduce**
1. Unregister all block patterns (@akirk do you have code at handy to do this?)
1. Open block patterns sidebar
1. Observe empty sidebar

**Expected behavior**
No block pattenrs sidebar available.

**Comment by akirk** [comment]
> Unregister all block patterns

On the PHP side it can be done with this snippet:
```
function disable_block_patterns( $settings ) {
	unset( $settings['__experimentalBlockPatterns'] );
	return $settings;
}
add_filter( 'block_editor_settings', 'disable_block_patterns', 100 );
```

**Comment by mtias** [comment]
This is temporary UI, I don't think it's worth handling this. It should be easy to unregister the whole patterns plugin if that's what you want to do.

**Comment by akirk** [comment]
Could you give suEasier said than done, no? I see the BlockPatterns loading is hardcoded here: https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/plugins/index.js#L17

**Comment by mcsf** [comment]
> This is temporary UI, I don't think it's worth handling this. It should be easy to unregister the whole patterns plugin if that's what you want to do.

Should we pluck `BlockPatterns` into its own plugin? The following allows disabling of patterns via `wp.plugins.unregisterPlugin( 'edit-post-block-patterns' )`:

<details>

```patch
diff --git a/packages/edit-post/src/plugins/index.js b/packages/edit-post/src/plugins/index.js
index 87853d4493..a821d53366 100644
--- a/packages/edit-post/src/plugins/index.js
+++ b/packages/edit-post/src/plugins/index.js
@@ -16,11 +16,20 @@ import ToolsMoreMenuGroup from '../components/header/tools-more-menu-group';
 import WelcomeGuideMenuItem from './welcome-guide-menu-item';
 import BlockPatterns from './block-patterns';
 
-registerPlugin( 'edit-post', {
+registerPlugin( 'edit-post-block-patterns', {
 	render() {
 		return (
 			<>
 				<BlockPatterns />
+			</>
+		);
+	},
+} );
+
+registerPlugin( 'edit-post', {
+	render() {
+		return (
+			<>
 				<ToolsMoreMenuGroup>
 					{ ( { onClose } ) => (
 						<>

```
</details>

**Comment by mtias** [comment]
Yes, I thought that was the case already.

**Comment by mcsf** [comment]
Ready for review in #20871

**Comment by youknowriad** [comment]
The plugin approach is also temporary as I was planning to work on the patterns inserter UI and we'll most likely need a way to hide patterns there if no patterns found.

**Comment by mcsf** [comment]
> The plugin approach is also temporary as I was planning to work on the patterns inserter UI

Yes, I stated this in in #20871, but I don't think it precludes the proposed improvement (IMO it should have been done this way from the start).

**Comment by paaljoachim** [comment]
I am wondering if this issue is still valid or if it needs updating?
Is there anything here or in associated issues/PRs that contains information that should be added to the Block Editor Handbook?

Perhaps there should be a way through preferences to hide Patterns?

**Comment by ntsekouras** [comment]
This should be fixed with: https://github.com/WordPress/gutenberg/pull/31687.
