### ISSUE TITLE
Some paddings, margins in "Document" blocks

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2087]
- 0.6.0 version.
- Vivaldi browser, chrome engine
- Chrome browser

Content of Metaboxes is pressed against outlined (borders) header.

![](https://s12.postimg.org/6hjoobmhp/2017-07-30_095626.jpg)

**Comment by karmatosed** [comment]
The Table of Contents also has this issue:

![2017-08-02 at 18 37](https://user-images.githubusercontent.com/253067/28886556-d522d0c0-77b1-11e7-8282-c32e52c99f99.png)

**Comment by karmatosed** [comment]
Looks like this issue has been resolved:


![2017-09-25 at 15 27](https://user-images.githubusercontent.com/253067/30813734-21144a62-a206-11e7-8978-26ee55c57a1a.png)
