### ISSUE TITLE
Show block outline when focusing / hovering the block type

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20875]
One detail we didn't get to implement from #18667 is that when the user focuses or hovers the block type / movers, the outlines of the whole block appear to clearly show its boundaries.

![image](https://user-images.githubusercontent.com/548849/76622147-3712c000-6531-11ea-8d09-5f487b643450.png)

This is the equivalent of the "selection" tool.

**Comment by paaljoachim** [comment]
Thanks I missed having a clearly defined area showing the outline of the block area.

**Comment by paaljoachim** [comment]
Comparisons

Blue outline around the selected Cover Block:
![Screen Shot 2020-03-16 at 11 55 22](https://user-images.githubusercontent.com/5323259/76749651-23f43000-677d-11ea-81b4-8790f3fbcd91.png)

No outline in the selected child paragraph block:
![Screen Shot 2020-03-16 at 11 55 30](https://user-images.githubusercontent.com/5323259/76749681-31111f00-677d-11ea-8001-1f5b851eda86.png)

Blue outline around the selected spacer block. Which also uses a grey background placeholder.
![Screen Shot 2020-03-16 at 12 01 06](https://user-images.githubusercontent.com/5323259/76750050-da581500-677d-11ea-896f-fe1a2f5baa6a.png)

Blue outline around the selected Image Block:
![Screen Shot 2020-03-16 at 11 55 52](https://user-images.githubusercontent.com/5323259/76749740-4be39380-677d-11ea-9ef2-6b4cc9c96a42.png)

No outline in the selected caption area. (Caption it almost like a child paragraph block to the image block.)
![Screen Shot 2020-03-16 at 11 58 06](https://user-images.githubusercontent.com/5323259/76749857-81887c80-677d-11ea-80bf-d87338753987.png)

Selected Paragraph block.
![Screen Shot 2020-03-16 at 11 59 56](https://user-images.githubusercontent.com/5323259/76749967-b7c5fc00-677d-11ea-8e98-8c204aaf85da.png)


Having outline to all parent or stand alone blocks would very much help. It gives a clear definition of the space they contain. The defined area that is being manipulated. 
Without having to go to the top toolbar to go into the drop down to select the Select tool.

**Comment by mtias** [comment]
> Without having to go to the top toolbar to go into the drop down to select the Select tool.

You can also press the escape key.

**Comment by joyously** [comment]
I too miss the outline (and isn't it part of accessibility?), especially since the editor is using a color without regard to the background color that the theme has set. This also applies to the placeholder text. I found in the CSS that the placeholder text is set to gray, opaque, and a background of transparent. (that's just downright irresponsible)

**Comment by karmatosed** [comment]
One thing to also consider is too many outlines and too heavy an interface can also cause accessibility issues. What I like about this initial proposal in the issue, gives some steps onto how a balance can happen. I think it's important to look back at that point of this issue a little and focus on that, through the movers.

**Comment by shaunandrews** [comment]
> No outline in the selected child paragraph block

Part of the logic here is that the caret (the blinking line that indicates you can type) _is_ the focus state for text-related blocks like Paragraph and Heading.

**Comment by ItsJonQ** [comment]
I'm taking a look at this now 🤞

**Comment by ItsJonQ** [comment]
I have this working:

![Screen Capture on 2020-03-16 at 13-53-18](https://user-images.githubusercontent.com/2322354/76786398-8d7c3a80-678d-11ea-982c-f6bd0e00877c.gif)

It's currently using **the same styles as selection**. The show/hide mechanics follow the same rules as the Movers.

If folks have an idea for perhaps alternative styles, please let me know :)
