### ISSUE TITLE
`SlotFills` not working in a custom page with custom sreen

### ISSUE THREAD

**Issue by surajv** [WordPress/gutenberg#20885]
I am making a custom screen on a custom page in WordPress using React and want to use `SlotFills`, but when I add the code using `registerPlugin` as per the documentation, it is not rendering the fills.

**Comment by ajlende** [comment]
@surajv Are you referring to the code from the [SlotFill Usage Overview](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/slotfills/README.md#usage-overview)? If so, have you registered your script with [`wp_enqueue_script`](https://developer.wordpress.org/themes/basics/including-css-javascript/#scripts) and enabled the plugin?

There are also a couple other things you can try in the [JS Troubleshooting Docs](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/javascript/troubleshooting.md) that might help.

**Comment by talldan** [comment]
@surajv You'll need to make sure the `Slot` components are rendered somewhere in your page.

For example, for rendering a Popover in a slot, you'd render `Popover.Slot` somewhere in your page.
