### ISSUE TITLE
Syncing fails after a while

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2088]
<img width="803" alt="screenshot 2017-07-30 17 00 05" src="https://user-images.githubusercontent.com/4710635/28754722-dbd17f7e-754b-11e7-8958-2afae259f9fb.png">

Syncing a post fails after I left the page open, and came back the following day. It seems the nonce fails to refresh.

Response:

```json
{"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

Heatbeat response:

```json
{"nonces_expired":true}
```

**Comment by iseulde** [comment]
This might be just one error now instead of many as in the screenshot.

**Comment by adamsilverstein** [comment]
I'm not sure if the sync happens when you leave the window open (looks like it), if it does you should get a refreshed nonce since https://core.trac.wordpress.org/changeset/41553. Are you testing with trunk?

**Comment by adamsilverstein** [comment]
@iseulde I worked on a potential fix in https://github.com/WordPress/gutenberg/pull/2790, can you give it a test please to see if it resolves your issue?

**Comment by mariadanieldeepak** [comment]
@baturkacamak,

I had the same issue and it resolved when I logged out and logged back in.
