### ISSUE TITLE
My perfect slider

### ISSUE THREAD

**Issue by anna-vanlee** [WordPress/gutenberg#20882]
The right Gutenberg slider for mobile sites
good afternoon
There is a site
https://150.hbr-russia.ru/

and if you access it from your smartphone, you will see the best slider carousel I’ve ever seen
http://prntscr.com/rdmonj
By the way, scrolling the slider and control the keyboard
I will tell ONLY about what are the distinguishing features of this slider in the mobile version (although such a block as on the above site, with the display of tiles in the desktop version, is fine)
Slider Features:
1) No stupid pictures – and it’s great
2) Almost the entire separate slide link (there are borders inside the slide to exclude erroneous clicks)
3) Different external design of slides (borders and fill with color)
4) There is no need to put a link to the text (accordingly, the color of the link does not change to blue) – the link is attached to the slide
5) There are no guides (arrows) – left-right (plus for me, although I understand that for some they are needed)
6) There is no limit on the number of slides (dots below and so on)
7) The previous and next slide is visible on the smartphone screen (it is intuitively clear that you can scroll left and right)
8) Slide change the scale
I went through the pages of all the main developers of Gutenberg blocks and found several similar ones:

1) https://getwid.getmotopress.com/blocks/image-slider-block/
Perhaps the most similar slider
It doesn’t scale well (the slide shows very little on the right and left), I don’t know if it is possible to add text

2) https://qubely.io/block/post-carousel/
Very good, but:
Slides do not change scale, slides from right to left are not visible, quantity limit, parentheses or dots
3) https://demo.wpxpo.com/post-slide-1/
Itself is very beautiful, but with a restriction on nesting, with dots, and one slide is visible at a time
This is all I found ((
Dear developers))
Please take this example on a note and make such a slider)))
It seems to me that this is how a beautiful site and Gutenberg slider should look

**Comment by mapk** [comment]
Thanks for raising this issue. Right now the Gutenberg team considers sliders as a perfect opportunity for 3rd party plugins.

This one that you shared in particular appears to just use `display: flex;` with `overflow-y: hidden;` which is really just allowing for a horizontal scroll. This could be very interesting in the context of blocks. However, I'm going to close this for now because it is better suited for plugins.
