### ISSUE TITLE
Hide Block Settings in drop down gets too much attention.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20906]
I noticed the following:

Example from Social Block drop down:
<img width="618" alt="Screen Shot 2020-03-14 at 14 59 40" src="https://user-images.githubusercontent.com/5323259/76684827-6ef03500-660f-11ea-9717-518f3ee58564.png">

Example from Paragraph Block drop down:
![Screen Shot 2020-03-14 at 16 17 22](https://user-images.githubusercontent.com/5323259/76684843-7e6f7e00-660f-11ea-8856-80dc178a497e.png)
 
Notice how the Hide Block Settings have a blue border around it.
The blue border looks like an option has already been selected or is being hovered over.
It would be good to move the option further down and also remove the blue border around it.

There are three ways (that I know of) to hide the Block Settings.
By clicking the Settings button. A shortcut. Or the Hide Block Settings in the drop down.
Full Screen by hiding the left WP menu has one option. Clicking the W.

It would be better to consolidate hiding sidebar areas into one button one can cycle through the options. It would keep a consistency in hiding sidebar areas. I already have an issue for it.
This issue is really just about removing the blue border and pushing the Hide Block Settings down the drop down list.

**Comment by talldan** [comment]
> The blue border looks like an option has already been selected or is being hovered over.

Hey @paaljoachim,  this is indeed what it's showing, the blue border shows which menu item is focused, if you use arrow keys the focus moves to other menu items. You'll notice the same in other drop down menus.

This is an important accessibility feature, so not something that can be removed. As such, I'll close the issue.

**Comment by paaljoachim** [comment]
Ahhh gotcha! Thanks Dan!
