### ISSUE TITLE
Gutenberg Version 7.7.1 throws off alignment

### ISSUE THREAD

**Issue by clickdujour** [WordPress/gutenberg#20910]
Updating to Gutenberg to 7.7.1 throws off image alignment in edit mode.

Rolling back Gutenberg to version 7.6.0 solved my problem.

I might add that IMO the new 7.7.1 Gutenberg UI is clunky compared to 7.6.0

**Comment by karmatosed** [comment]
I am currently unable to reproduce this. It doesn't mean the issue doesn't exist though. For now, I am going to close as can't replicate, however, if you still can would you please be able to give a few more details like what browser and theme you are using? Perhaps even record a video?
