### ISSUE TITLE
[ Navigation Block ] Add the ability to add formats to menus

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#20924]
**Is your feature request related to a problem? Please describe.**
In the current WordPress menus one is able to add a format to the menu.

**Describe the solution you'd like**
When I type the name of a format I would like a suggestion to link to the archive page of that format.

**Related**
#20165

**Describe alternatives you've considered**
Not including Formats archive pages at all.

**Comment by karmatosed** [comment]
@draganescu I am trying to work out how this would work. I know there's an option for categories. When you say format what do you mean? Apologies as it might be me being a little confused here.

**Comment by draganescu** [comment]
[Formats](https://wordpress.org/support/article/post-formats/)  appear as an option to be inserted in the menu in the current menu builder:

<img width="1200" alt="Screenshot 2020-03-17 at 08 00 17" src="https://user-images.githubusercontent.com/107534/76844879-a72d8880-6846-11ea-94c8-ddc97b1a6b16.png">

In the screenshot above the box contained Gallery as soon as I added a post and set its format to gallery. The link is to an archive listing of all the posts with that format (gallery). Ignore the blank formats as they're added by FakerPress.

**Comment by karmatosed** [comment]
Ah so it's post formats, adding all those types of formats to the listing. Thanks for visual. I think just adding like categories makes sense then.

**Comment by draganescu** [comment]
So we don't have an endpoint that lists formats to use in Gutenberg
