### ISSUE TITLE
Adding an initial Block Style select - similar to the select a variation for Columns

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20920]
After having initially selected to use a Column Block we are presented with options in how the columns are to be laid out.

![Screen Shot 2020-03-16 at 10 49 23](https://user-images.githubusercontent.com/5323259/76744033-e6d77000-6773-11ea-8112-608aa3515f67.png)

The Columns Block "Select a variation to start with." gives the user an initial option of what kind of structure they want to use.

We could do something similar for blocks that have styles associated with them.

Here is a suggestion:
![Buttons-initial-style-Gutenberg](https://user-images.githubusercontent.com/5323259/76745040-7a5d7080-6775-11ea-94bd-dfcc680082f6.jpg)

![Buttons-initial-style-Gutenberg-ver2](https://user-images.githubusercontent.com/5323259/76745334-ffe12080-6775-11ea-8af8-ed72c758b4dc.jpg)

What it would solve.
At present I believe there is a discoverability issue in having Block Styles in the toolbar.
Having an initial startup area for all blocks where styles can be added will be of great benefit in showing right away the styles that are available. The user can also later on select the styles tab in the sidebar and change the style of the block if they change their mind.
I also believe it will fit nicely in with Block pattern areas in the Block Inserter screen.

**Comment by karmatosed** [comment]
Whilst I understand what you are trying to do here by surfacing block styles, I am not sure the placeholder is the right way forward. As shown in your example, this adds a lot of cognitive weight to the initial state of a block, where that's probably not desirable. 

A setup placeholder state makes sense for columns as there is something to set up. You could say block styles are secondary, so having them there isn't really the right hierarchy. It makes more sense to have them be applied after you have chosen to use that block, not before you've even got there.

I will add a feedback label to this, but it's my recommendation if discoverability of block styles is an issue to explore other ways to surface.

**Comment by mapk** [comment]
Thanks for the suggestion, @paaljoachim! I'm glad you're spending time thinking this through. I would agree that discoverability is difficult sometimes, but I don't think the block placeholder is the right spot either.

The block placeholder is for things that are mostly a required set up step before adding the block to your content. Because adjusting column width is sooooo hard to find right now, having that in the placeholder is important. 

I agree with @karmatosed here, let's keep the style variations separate from the placeholder.

**Comment by paaljoachim** [comment]
As I see it it gives an initial option for how one wants to show a specific block. Highlighting the styles in this way is one method to show the user that styles are available, and can be selected right away.

1. User adds a block.
2. Right away is presented with options to how the specific block is to be styled. Can select a style or just click skip. 

Disadvantage is that this is an extra click the user might not want to have. It slows down the process of quickly adding a block. That means finding ways to better showcase the sidebar Styles area.
