### ISSUE TITLE
[ Navigation block ] Allow menus to be assigned to locations

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#20925]
Currently WordPress themes have the feature of defining preset menu locations. Menus in WordPress can then be assigned to these locations.

The use of locations is that, like widgets areas, for lack of free editing, one needs to know where the menu will appear, and themes need to control where they will output the menu.

In the context of Full Site Editing menu locations make no sense as everything is editable inline, therefore a Navigation block can be added anywhere. However, for current themes a menu needs a location in order to be rendered by the theme on the front end.

**Comment by mtias** [comment]
I don't think a menu needs a location, but a location needs to refer to a menu. This is context that I would place entirely out of the navigation block, for example.

**Comment by karmatosed** [comment]
Wouldn't this be in the menus.php interface over in the block? I feel that's a better spot for this assignment assuming I am understanding this issue @draganescu.

**Comment by draganescu** [comment]
Yes, it may be out of the scope of the block, but: we don't manage nav-menus.php migration to using blocks separately from the Navigation block itself. I suggested we do but got the info that 
for now it's in the same project.

Therefore I added it as referring to the block, but it is only useful for allowing the block to manage current WP menus.

**Comment by karmatosed** [comment]
I still don't see how this would need to be by the block then if there is potentially a v2 interface that sees blocks placed on templates.

**Comment by draganescu** [comment]
Wait, this is essential for the nav-menus.php migration. If in the end it won't be a feature of the Navigation block that is a different story. But that board is also managing the nav-menus.php migration, am I wrong?

**Comment by karmatosed** [comment]
Ah ok,  so this is menus.php but for the block? Thanks for clarifying that. This project board is for everything we need in 5.5 for navigation.

**Comment by draganescu** [comment]
#21351 closed this.
