### ISSUE TITLE
Problem Placing and Moving Blocks in the new Gutenberg editor interface.

### ISSUE THREAD

**Issue by bryanhiggs** [WordPress/gutenberg#20931]
**Describe the bug**
The new editing interface has several shortcomings

**To reproduce**
1. Go to the Gutenberg editor and try adding and moving blocks

**Expected behavior**
I have experienced difficulties in placing a new block. I have found that the "+" that is supposed to appear when you mouse over an existing block to insert a block before the existing block sometimes is hard to find, or doesn't appear to be present. I think that having the "+" be always there, rather than only when you mouse over would be much easier to use, rather then having to randomly search.

When I have managed to create a new block, and then tried to move it up to a particular location by dragging it, it refuses to be inserted, under some circumstances. This is very frustrating. 
I am using a Kadence Blocks' Tabs block, where this has been very apparent. Not sure if this a Kadence Blocks issue or a Gutenberg issue.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS (but probably not specific to that)
 - Browser: Chrome (probably not specific to that)
 - Version: 80.0.3987.132 (probably not specific to that)

**Additional context**
- Gutenberg plugin 7.7.1

**Comment by karmatosed** [comment]
I find myself able to add blocks,  which makes me think would you be able to perhaps record so I can see what you are experiencing?

**Comment by paaljoachim** [comment]
Associated issue:
https://github.com/WordPress/gutenberg/issues/20955
There is difficulty dragging blocks into and out of and inside the group block.

**Comment by karmatosed** [comment]
@paaljoachim would it be better to merge the issues?

**Comment by bryanhiggs** [comment]
I, too have had problems trying to move blocks inside a group block. So
perhaps it's a good idea to combine the two.

------------------------------
*Dr. Bryan J. Higgs*
*13 Quarry Circle*
*Milford, NH 03055*
*U.S.A.*


*Tel: 603-673-7601*
‎"A nation's greatness is measured by how it treats its weakest members." ~
Mahatma Ghandi
------------------------------

**Comment by paaljoachim** [comment]
Hey Bryan

What you can then do is click the Comment and close button to close this issue, and we will keep open the one I added open since I have an animated gif in it that shows the difficulty with moving blocks inside/out/in of the Group Block.

**Comment by enriquesanchez** [comment]
Closing in favor of #20955
