### ISSUE TITLE
New Gutenberg Editor interface lacks a 'View Page' choice

### ISSUE THREAD

**Issue by bryanhiggs** [WordPress/gutenberg#20932]
**Describe the bug**
The new Gutenberg editor interface is deficient in that it lacks a way of viewing the page/post.
When one does an update, the popup message at the bottom comes up, giving the choice of viewing the page, but it disappears. The new interface seems to have suppressed the black admin bar, which has that as an option. As a result, one has to go back to the site to do this elementary operation.
If there is an option to do this in the new editor interface, I have failed to find it. It seems overly sparse.

**To reproduce**
1. Go into the new Gutenberg editor.

**Expected behavior**
A way of viewing the page/post that is apparent and easy.

**Screenshots**
None

**Desktop (please complete the following information):**
OS, Browser and version are irrelevant, as far as I know.

**Additional context**
- Gutenberg 7.7.1

**Comment by karmatosed** [comment]
Hi @bryanhiggs, there is a way to preview a post as you can see here:

![image](https://user-images.githubusercontent.com/253067/76793185-815ba180-67bc-11ea-8ac2-7e16294965e0.png)

This isn't to say there could be a discoverability issue, which there might be and there are a few issues to iterate. For now, as this exists I am going to close this issue. Thanks though for reporting this.
