### ISSUE TITLE
Adjust hover effect when over empty Social Icons Block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20930]
When the Social Icons Block is empty and deselected.
Hovering shows this:

![Social-Icons-empty-hover](https://user-images.githubusercontent.com/5323259/76769414-bce67380-679c-11ea-9ff2-f563c4efafd9.png)

A suggestion.
![Social-Icons-empty-hover-outline](https://user-images.githubusercontent.com/5323259/76769859-5150d600-679d-11ea-91dd-60764ab21d93.jpg)

Do adjust the Add block tooltip to Add Social Icon text.

Instead of the above suggestion one and just have a modified selected Social Block to work with hover.
![Social-Blocks-Selected](https://user-images.githubusercontent.com/5323259/76769948-72b1c200-679d-11ea-9669-0371155abce0.png)

@mkaz 

Associated:
https://github.com/WordPress/gutenberg/issues/20908

**Comment by mtias** [comment]
The label suggestion is already captured in #20728.

**Comment by paaljoachim** [comment]
Great! Thanks! It looks like it is being dealt with there. I will close this issue.
