### ISSUE TITLE
Visual Autosave Indicator when typing

### ISSUE THREAD

**Issue by benjaminstocker** [WordPress/gutenberg#20949]
**Is your feature request related to a problem? Please describe.**
When typing long Texts in the Block Editor, Autosave will store this Changes regularly. However, there is no visual "OK, saved"  Feedback while typing. The former Classic Editor wrote a message "Last saved at nn:nn:nn" to the Status bar after every update. 

**Describe the solution you'd like**
Visual Autosave Feedback and no "Leave Editor?" question when the Text is up to date. 

Thank you  for developing the Gutenberg Block Editor!

**Comment by paaljoachim** [comment]
Here is an associated issue I made earlier today which I will go ahead and close.
https://github.com/WordPress/gutenberg/issues/20957

**Comment by benjaminstocker** [comment]
That's fine, @paaljoachim, please reopen your issue and close this one. Thanks for your help.
