### ISSUE TITLE
Add block “Plus” icon is black

### ISSUE THREAD

**Issue by JeanDavidDaviet** [WordPress/gutenberg#20945]
**Describe the bug**
The "add block" icon svg path is black 

**To reproduce**
1. Go to any post or page editor
2. The "add block icon" is black
3. See error

**Expected behavior**
The "add block" icon svg path should be white.

**Screenshots**
![add-block-icon-black](https://user-images.githubusercontent.com/1676202/76836525-421b6800-6831-11ea-8eb1-1310c97e463b.jpg)

**Desktop (please complete the following information):**
 - OS: macOs 10.15.3
 - Browser Chrome
 - Version 80.0.3987.132

**Additional context**
- Plugin WordPress Beta Tester enabled
- Plugin Gutenberg enabled

**Comment by youknowriad** [comment]
Thanks for the issue, I believe this is a bug in 2020 that was already raised in Trac. Unfortunately, I'm not able to find the ticket anymore.
