### ISSUE TITLE
Nav block: popover z-index is overlapping oddly

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#20940]
**Describe the bug**
The overlap of popovers in the Nav block appear janky.

**To reproduce**
1. Add a Nav block with items.
2. Add a subnav item.
3. Click the "add a link" under the first subnav item.
4. Observe the problem.

**Expected behavior**
I did not expect there to be oddly overlaid parts.

**Screenshots**

![Screen Shot 2020-03-16 at 1 55 59 PM](https://user-images.githubusercontent.com/617986/76799184-4e9ab480-678e-11ea-8b1a-aeb43a9d82fd.png)

**Desktop (please complete the following information):**
 - OSX Catalina
 - Firefox 73.0.1
 - Gutenberg 7.7

**Comment by karmatosed** [comment]
Closing as similar to https://github.com/WordPress/gutenberg/issues/20852 - let's focus over there for now.
