### ISSUE TITLE
Gutenberg 7.7.1 block preview too small for content, unable to navigate to preview.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#20953]
**Describe the bug**
Preview of blocks seems to be shown in an iframe(?) thats too small for its content. When trying to navigate to the preview to use the scrollbars, the preview disappears. Screencast attached.

**To reproduce**
1) add a post
2) click add block button
3) hover over a block
4) notice the preview

**Expected behavior**
I expect the preview to remain so I can navigate (using its scroll bars), to see the actual preview.

**Screenshots**
https://www.youtube.com/watch?v=JX9qth4RTR0&feature=youtu.be

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Latest Chrome, Latest Firefox
 - Version: Current latest stable version

**Additional context**
Gutenberg 7.7.1 from WordPress.og
1920x1080 screen resolution
No zooming done (100% zoom) in browsers.

**Comment by youknowriad** [comment]
Thanks for creating this issue, this is already fixed in master by #20817

**Comment by oldrup** [comment]
Oh cool! Thanks :)
