### ISSUE TITLE
Scheduled post does not show correct url on preview

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20954]
Support request from: https://wordpress.org/support/topic/real-url-not-showing-in-preview

Creating a scheduled post and then previewing it does not show the correct url.

Step by step.

1. Create a post. 
2. Set a date forward in time to make it scheduled.

![Screen Shot 2020-03-17 at 12 42 52](https://user-images.githubusercontent.com/5323259/76853088-f676b780-684c-11ea-8fbe-1883149399fa.png)

3. Click Schedule.

![Screen Shot 2020-03-17 at 12 43 18](https://user-images.githubusercontent.com/5323259/76853117-0098b600-684d-11ea-9b3b-50a200599fb6.png)

4. Click Schedule again.

![Screen Shot 2020-03-17 at 12 44 31](https://user-images.githubusercontent.com/5323259/76853165-11e1c280-684d-11ea-936e-5297f21824c1.png)

5. Notice the post URL.

![Screen Shot 2020-03-17 at 12 44 57](https://user-images.githubusercontent.com/5323259/76853218-29b94680-684d-11ea-9134-5723c1ef2abb.png)

![Screen Shot 2020-03-17 at 12 47 05](https://user-images.githubusercontent.com/5323259/76853388-73099600-684d-11ea-8f84-84f249bb98e7.png)

The URL needs to show the correct URL.

Use case mentioned by user in the Gutenberg forum:
"So no easy way to copy the “final” URL to plan social media posts etc."

**Comment by kirilzh** [comment]
Hi, I would like to be assigned to this issue : )

**Comment by paaljoachim** [comment]
Hi @kirilzh 

When do you plan to create a PR for this issue?

I ask, as the fix has a potential to be a part of the release of 5.4.1.

**Comment by kirilzh** [comment]
Hi @paaljoachim I know it's taking me a while but I'm still figuring some things out. I hope one more week will be sufficient

**Comment by paaljoachim** [comment]
The same error happens using the Classic Editor plugin in Gutenberg.
1. Create post.
2. Schedule a date in the future.
3. Click Schedule.
4. View Post / Preview post
5. Check the URL. Even though the site uses pretty permalinks it will show a non pretty a number in the url. Such as sitetitle.com/?p=108
