### ISSUE TITLE
Group block: Difficult to drag blocks into/out of and inside.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20955]
Based on this support forum feedback: https://wordpress.org/support/topic/top-add-block-plus-mark-missing/

**Describe the bug**
There is no internal blue line when draging a Block inside a Group Block.
(Yes one can click the up or down arrows.)
It is also very difficult to drag Blocks into and out of the Group block.

**To reproduce**
1. Add a Group Block.
2. Add 3 paragraph blocks with some content inside the group block.
3. Drag the 3 paragraphs up and down. Notice that there is no blue outline.
4. It is difficult to drag blocks inside of the Group block. It is also difficult to drag blocks into and out of the group block.

**Expected behavior**
I expect a blue outline when draging a block.

**Screenshots**
![Drag-internal-Group-blocks](https://user-images.githubusercontent.com/5323259/76857269-67ba6880-6855-11ea-9887-7162052ecd73.gif)

OSX
Chrome
Desktop Server
Gutenberg version 7.7.1

**Comment by a4jp-com** [comment]
What program did you use to make that animated gif of the problem? Sorry for asking here but I'll do the same for other problems.

**Comment by paaljoachim** [comment]
I use Screenflow on my Mac.
I did a search: https://www.ecosia.org/search?q=create+gif+animation&addon=chrome&addonversion=3.1.2

These programs has been mentioned earlier.
https://www.cockos.com/licecap/
https://gifox.io/

Or do a search for gif animation review and see what options show up.

**Comment by paaljoachim** [comment]
In version 7.8 draging is a little better in the Group block. More fixes are being worked on.

**Comment by timhibberd** [comment]
On Windows / Firefox / Twenty-Twenty Theme ? WP5.4 I couldn't drag any blocks into the group block at all.

**Comment by paaljoachim** [comment]
There are multiple issues for Drag and Drop. The following issue includes a few links.
https://github.com/WordPress/gutenberg/issues/21391

**Comment by mtias** [comment]
We now have an improved chip design that is much more reliable.

**Comment by paaljoachim** [comment]
This issue was closed. We do have a more focused issue in https://github.com/WordPress/gutenberg/issues/24750
"While moving a block: Show border and block name of hovered blocks."

As that will help with dragging in and out of blocks. Such as the Group block.
