### ISSUE TITLE
No visible timestamp for autosave.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#20957]
**Is your feature request related to a problem? Please describe.**
From support forum: https://wordpress.org/support/topic/autosave-visual-feedback/

> My Question is: How (or where) can I see (while writing) when the last Autosave has been executed. In the Classic Editor, there is a Indicator in the Status Bar “Last saved at nn:nn:nn”.

**Describe the solution you'd like**
A simple way to see when the last autosave was made.

**Screenshots:**

The classic editor shows word count and draft saved time on the bottom.
![Screen Shot 2020-03-17 at 14 10 40](https://user-images.githubusercontent.com/5323259/76860214-ec5bb580-685a-11ea-91e5-b3cee0d57548.png)

Gutenberg. Should there be a similar Save area bottom right on the Breadcrumbs bar?
![Screen Shot 2020-03-17 at 14 25 11](https://user-images.githubusercontent.com/5323259/76860381-393f8c00-685b-11ea-97bd-9dc238316f68.png)
Where would be a logical place to show a timestamp for autosave?

**Comment by paaljoachim** [comment]
Closing in as another similar issue has been made.

**Comment by paaljoachim** [comment]
Reopening as I have screenshots added.

**Comment by kellychoffman** [comment]
> Should there be a similar Save area bottom right on the Breadcrumbs bar?

We could, but it's not common to have a timestamp present in an interface that utilizes autosaving. 

I would expect timestamps to be only visible as part of version history.

**Comment by paaljoachim** [comment]
I went ahead and consolidated this issue into the Autosave issue (linked to my new comment): https://github.com/WordPress/gutenberg/issues/16053#issuecomment-843590998
and will go ahead and close this issue.
