### ISSUE TITLE
Requests to oEmbed proxy fail with plain permalinks

### ISSUE THREAD

**Issue by dlh01** [WordPress/gutenberg#2096]
## Issue Overview

In the embed block, `doServerSideRender()` appends `'oembed/1.0/proxy?url='` to the root REST API URL When plain permalinks are used, a `?` is already present in the root URL, so appending `?url` doesn't work.

Using `master` as of e7e266c6c88d79121a1a8f01a58c7eb1a21852df, Chrome 59.0.3071.115.

## Steps to Reproduce (for bugs)

1. Set Settings > Permalinks to "Plain."
2. Create a post in Gutenberg.
3. Add an Embed or YouTube block with a URL like https://www.youtube.com/watch?v=-tWhPv2U6aQ.

## Expected Behavior
The video should embed.

## Current Behavior
"Sorry, we could not embed that content" is shown; the developer tools show a 404 for https://domain.com/index.php?rest_route=/oembed/1.0/proxy?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-tWhPv2U6aQ

## Possible Solution
Use the `addQueryArgs` function in `editor/utils/url` to construct the URL.

## Related Issues and/or PRs
PR incoming.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by westonruter** [comment]
Fixed by #2097, right?
