### ISSUE TITLE
Add a way to control size of buttons block

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#20967]
It's nice that we now have the control for `border-radius`, and it'd be great if we could change the size of a button.

I was working on the following block pattern, and I thought it'd be nice if I could make the button larger by increasing the button text size and the paddings.

![call-to-action](https://user-images.githubusercontent.com/908665/76886037-166fa080-6878-11ea-9ea5-abf7e86dfd68.jpg)

**Comment by carolinan** [comment]
This would be a great addition, currently having to add custom styles for this.

**Comment by mapk** [comment]
As discussed in [today's triage in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1594140666441200):
This request makes sense. We're adding these controls currently to other blocks, so bringing them here would be worth a PR.

We can bring the font size control from the Paragraph block and also the padding control from the cover block? We'll need some dev around this. cc @ItsJonQ

**Comment by mtias** [comment]
@apeatling do you think this can be closed with the current button tools we have?

**Comment by apeatling** [comment]
I think this can be closed with padding/axial padding support now in place.
