### ISSUE TITLE
How to trigger Block Controls?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#20963]
Hi,

The clickable area for block controls is too small. Is there a way to manually trigger block controls toolbar visibility? I suspect if block controls on hover actually work.

Using wordpress 5.3.2

**Comment by paaljoachim** [comment]
Hi Nav

Have you tried the Gutenberg plugin to see how that works in relation to WordPress 5.3.2?

A new version of WordPress 5.4 will be released at the end of the month. Containing a newer version of Gutenberg then the one included in 5.3.2.

Btw
Remember to include screenshots that clearly shows what you are also explaining.

**Comment by navxio** [comment]
Clicking inside my block actually 'conducts' the click through to my block code- Is there a way to capture it to show the block toolbar instead?
![image](https://user-images.githubusercontent.com/9297865/77357996-1c311e80-6d6f-11ea-9947-632894fd8eac.png)

![image](https://user-images.githubusercontent.com/9297865/77358057-3408a280-6d6f-11ea-93fc-443e6300554e.png)

**Comment by navxio** [comment]
Solved it using <Disabled />
