### ISSUE TITLE
Wrong behavior when selecting all text in list block

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#20975]
I found it in the Japanese environment, but when I select all the text of the first or last item of "list block" with "command + Shift + left / right cursor key", the blocks before and after "list block" are selected. I will.

This seems to occur when "font-family" or "line-height" is applied to the li tag.

**To reproduce**

0. In preparation for reproduction in English environment, rewrite the font-family of the list block.

Here, as an example, specify the "Baskerville" font.
Overwrite the font that "Twenty Twenty" has applied to the ul tag from the developer tool as follows.

<img width="400" alt="set_Baskerville" src="https://user-images.githubusercontent.com/31400297/76918952-d3aad880-690a-11ea-9b3d-92cc3d3bb1c6.png">

( In Japanese environment, it occurs in plain "Twenty Twenty" even without this step. )

If the following steps are taken with the font overwritten, a bug will occur.

1. Place paragraph blocks before and after list blocks.
2. Place three items in the list block.
3. The middle item allows you to select all the text, 
4. but the first and last items behave erratically.

![li_text_select_bug](https://user-images.githubusercontent.com/31400297/76919671-e3c3b780-690c-11ea-86c6-818b19927e29.gif)

This bug may occur only by changing the font setting, or the same font may or may not cause the bug depending on the "line-height" value.

**My environment**
- macOS Catalina
- Google Chrome (Confirmed bug reproduction on Safari)

**Comment by jorgefilipecosta** [comment]
Hi @ddryo thank you for reporting this issue 👍 

What version of WordPress are you using?
Do you have the Gutenberg plugin installed? If yes what version is installed?

Thank you in advance for this information!

**Comment by ddryo** [comment]
No plugin was used. It was verified with WordPress5.3!
I will try to reproduce the bug with the plugin version.

**Comment by ddryo** [comment]
This bug was reproduced in the latest Gutenberg (7.7.1)

**Comment by ddryo** [comment]
This bug was reproduced Gutenberg 8.2.1 !

**Comment by youknowriad** [comment]
I'm not able to reproduce this anymore. It seems like it was fixed.
