### ISSUE TITLE
Update style variation documentation to reduce confusion

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#20972]
Now that we have block "styles variations" and block "variations", we should update our documentation to separate these out a bit - so that they're less confusing for folks navigating our documentation.

**Describe the solution you'd like:**
Wherever we currently reference "styles variations", we should simply reference "styles". 

Example (from [this doc](https://github.com/WordPress/gutenberg/blob/ec91b39ac8fcf4a4dbe321a914db79052a1520cd/docs/designers-developers/developers/block-api/block-registration.md#L195)):

> Similarly to how the block's style **variations** can be declared, a block type can define block variations that the user can pick from. 

...should be: 
> Similarly to how the block's styles can be declared, a block type can define block variations that the user can pick from.

Here's where we're referencing "block style variations". 

https://github.com/WordPress/gutenberg/blob/2e996852b6f5856ba30357c041ee2a0a2ae3fb5f/docs/designers-developers/developers/filters/block-filters.md

https://github.com/WordPress/gutenberg/blob/2e996852b6f5856ba30357c041ee2a0a2ae3fb5f/docs/designers-developers/developers/filters/block-filters.md

https://github.com/WordPress/gutenberg/blob/19c40af0d6d98dd329d8f5e64aba748ea288be63/docs/designers-developers/developers/tutorials/javascript/extending-the-block-editor.md

https://github.com/WordPress/gutenberg/blob/ec91b39ac8fcf4a4dbe321a914db79052a1520cd/docs/designers-developers/developers/block-api/block-registration.md

https://github.com/WordPress/gutenberg/blob/7d592007dae04dc1ec3dce91f720a4d7605b4367/docs/rfc/block-registration.md

https://github.com/WordPress/gutenberg/blob/7515397fef469e8cbdaf68162d6d6e1f2a5f9aa1/docs/designers-developers/developers/data/data-core-edit-post.md

**Comment by mateuswetah** [comment]
Hi @richtabor. This seems to be a simple task for me to take. Is it something that needs some discussion with more people? I'm also seeing that the change [on this file](https://github.com/WordPress/gutenberg/blob/7515397fef469e8cbdaf68162d6d6e1f2a5f9aa1/docs/designers-developers/developers/data/data-core-edit-post.md) would also require updates on some js files, that use the `updatePreferredStyleVariations` variable.

**Comment by paaljoachim** [comment]
A followup reminder @richtabor 
I will also add Marcus @mkaz here as he might also have some feedback.

**Comment by skorasaurus** [comment]
Went through the above links (since i was confused again on block styles variations and block styles); 
I couldn't find any of use "styles variation" or "style variation" in the current documentation anymore EXCEPT at https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/data/data-core-edit-post.md
which contains a function - `updatePreferredStyleVariations` for the edit-post package. 

Should we keep this issue open to rename that function? 

Would like some confirmation from another triager or contributor before closing. :)
