### ISSUE TITLE
I want to be able to edit the footer and header of my website with Gutenberg

### ISSUE THREAD

**Issue by krachteneu** [WordPress/gutenberg#20988]
**Is your feature request related to a problem? Please describe.**
It's only possible right now to edit the content section of a website using the handy Gutenberg editor. But editing the **footer.php** and **header.php** of my website has to be done the old-fashioned way. It puzzles me! 

**Describe the solution you'd like**
I want to have a different field in the form to be able to edit all the sections of my website, not only the main content. I also want to use those pretty blocks in my menu's for example. 
 
**Describe alternatives you've considered**
There are currently no alternatives on the market. You have to program the blocks in manually. And that in the era of drag and drop. I really can't get it.

**Comment by youknowriad** [comment]
Hi There! 

This request is basically what the Full Site Editing project is about. It requires some big changes in how WordPress themes work. It's tracked here #20791 and all the related issues.
