### ISSUE TITLE
Device Preview: Tablet and Mobile previews show wp-admin toolbar and sidebar

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#20991]
When changing the device in the Preview menu, the wp-admin toolbar and sidebar appear breaking the UI:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/191598/76979332-2a65e180-690e-11ea-9b4f-7c0e9994efb0.png">

**Comment by noisysocks** [comment]
cc. @tellthemachines
