### ISSUE TITLE
After extending core/code the deprecation gives me the error

### ISSUE THREAD

**Issue by pasaulismargas** [WordPress/gutenberg#20994]
At first I just wanted to extend one of WordPress Gutenberg blocks by learning purposes. I chose the ‘core/code’ block. I created a new attribute and added the h4 tag for a title below the default content, this part worked fine. Then I decided to change the h4 tag to h2 tag. As I understand I needed to add deprecated array to settings object. I did this but I have this error:
"Block validation: Expected tag name h2, instead saw h4."

There is my code:

```
const { InspectorAdvancedControls }	= wp.editor;
const { createHigherOrderComponent } = wp.compose;
const { Fragment } = wp.element;
import { RichText} from "@wordpress/editor";
import deprecated from "./deprecated";
 
const enableExtendOnBlocks = [
    'core/code',
];
 
function addAttributes( settings, name ) {
 
    if ( ! enableExtendOnBlocks.includes( name ) ) {
        return settings;
    }
 
    if( typeof settings.attributes !== 'undefined' ){
 
        settings.attributes = {
            ...settings.attributes,
            vista:{
                type: 'string',
                default: 'vista',
                source: 'html',
                selector: 'h2',
            }
        };
 
        settings.title = 'My Code';
 
        settings.supports = {
            html: false,
        };
 
        settings.deprecated = deprecated;
 
    }
 
    return settings;
}
 
wp.hooks.addFilter(
    'blocks.registerBlockType',
    'extend-block-example/custom-attributes',
    addAttributes
);
 
const withInspectorControls =  createHigherOrderComponent( ( BlockEdit ) => {
 
    return ( props ) => {
 
        if ( ! enableExtendOnBlocks.includes( props.name ) ) {
            return <BlockEdit { ...props } />;
        }
 
        const onChangeVista = (vista) => {
            props.setAttributes({
                vista: vista
            });
        };
 
        return (
            <Fragment>
                <BlockEdit { ...props } />
                <RichText
                    tagName="h2"
                    formattingControls={[]}
                    value={props.attributes.vista}
                    onChange={(vista) => onChangeVista(vista)}
                />
            </Fragment>
        );
    };
}, "withInspectorControl" );
 
wp.hooks.addFilter( 'editor.BlockEdit', 'my-plugin/with-inspector-controls', withInspectorControls );
 
function codeSaveElement( element, blockType, attributes ) {
    if ( blockType.name !== 'core/code' ) {
        return element;
    }
 
    return (
        <>
            <pre  className={attributes.className}>
                <code>{ escape( attributes.content ) }</code>
            </pre>
            {/*{element}*/}
            <RichText.Content
                tagName="h2"
                value={attributes.vista}
            />
        </>
    );
}
 
wp.hooks.addFilter(
    'blocks.getSaveElement',
    'extend-block-example/custom-save',
    codeSaveElement
);
```

and there is deprecated array:

```
import {RichText} from "@wordpress/editor";
 
const oldAtt = {
    vista: {
        type: 'string',
        source: 'html',
        selector: 'h4',
        default: 'vista',
    },
    content: {
        type: "string",
        source: "text",
        selector: "code",
    },
    className: {
        type: "string",
    }
};
 
const oldAtt2 = {
    content: {
        type: "string",
        source: "text",
        selector: "code",
    },
    className: {
        type: "string",
    }
};
 
const deprecated = [
    {
        attributes: oldAtt2,
        save: function (oldAtt2) {
            return (
                <>
                    <pre  className={oldAtt2.className}>
                        <code>{ escape( oldAtt2.content ) }</code>
                    </pre>
                </>
            );
        },
    },
    {
        attributes: oldAtt,
        save: function (oldAtt) {
            return (
                <>
                    <pre  className={oldAtt.className}>
                        <code>{ escape( oldAtt.content ) }</code>
                    </pre>
                    <RichText.Content
                        tagName="h4"
                        value={oldAtt.vista}
                    />
                </>
            );
        },
    },
];
 
export default deprecated;
```

What do I do wrong? 

I found these steps how to fix invalid blocks:
	1.	Using the code editor, change the h4 tag to h2 tag.
	2.	Switch back to the visual editor

I can say that it works.

But shouldn't the deprecation fix that invalid block automatically? Because if I have a lot of old blocks and want to extend them, there is no other way how to fix them automatically instead of manually? I did a test with a simple block. After creating deprecate array, the block was updated automatically, but I have this problem with core blocks after extending them.

**Comment by talldan** [comment]
@pasaulismargas There seem to be a few things going on here. Firstly, the `registerBlockType` filter also applies to deprecations, so here you're overwriting the deprecated attributes, changing the selector for the vista attribute from an h4 to an h2, which means your deprecation can't source the attribute correctly:
```
        settings.attributes = {
            ...settings.attributes,
            vista:{
                type: 'string',
                default: 'vista',
                source: 'html',
                selector: 'h2',
            }
        };
```

Next up, the `getSaveElement` filter is also overriding the save function for your deprecation. So what's being output by the deprecation is also an `h2` instead of an `h4`. 

In both cases you'll need a way to detect if it's the deprecation that is being passed into the filter function, and if so not apply your filter.

Hope that helps. I'll close the issue.

I know this was probably a learning exercise but I'd recommend not applying deprecations unless needed, they're only needed when you have released code and the output of the save function needs to be changed.

**Comment by pasaulismargas** [comment]
Thanks for your answer, I moved further. 

One more situation: 
I have core block and I have the same core block but with these filters (first time modification);

Now let's say I have to do the modification for the same core block again but it should work for both the old one and after the first modification (already with filters).

Is it possible to write the additional depreciation for this result?
