### ISSUE TITLE
Strangely aligned URL entry bar in the Button block

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2099]
## Issue Overview
When selecting a button block, it shows a URL entry bar at the bottom of the block, but it is misaligned both horizontally and in the Z-depth.

<img width="825" alt="alignment" src="https://user-images.githubusercontent.com/6073772/28769535-3635a234-75dc-11e7-82fe-0e75aefb47d2.png">

## Steps to Reproduce
1. Insert a button block.
2. Note the strangely aligned URL bar.
3. Insert a block after the button.
4. Select the button block again.
5. Hover over the block below the button.
6. Note how the positioning arrows overlap with the URL entry bar.

chrome on mac
wordpress 4.8
vagrant dev env
gutenberg 0.6.0

## Expected Behavior
For the URL entry bar to be hidden until you click on the link button above the block (which is not present), and it then appearing properly aligned just as it does on a text block.

**Comment by mtias** [comment]
Closing as new button design addresses this.
