### ISSUE TITLE
@wordpress/scripts to be able to transpile .jsx files in addition to .js files

### ISSUE THREAD

**Issue by cliffordp** [WordPress/gutenberg#21009]
**Is your feature request related to a problem? Please describe.**
`.jsx` files aren't processed by wordpress/scripts' webpack file, but `.js` files are.

**Describe the solution you'd like**
Is it as simple as changing https://github.com/WordPress/gutenberg/blob/v7.7.1/packages/scripts/config/webpack.config.js#L38

from:
`test: /\.js$/,`
to:
`test: /\.jsx?$/,`

**Describe alternatives you've considered**
I was playing around with this so much, I didn't isolate if the above code change would solve things, but it just might???

**Comment by talldan** [comment]
Hi @cliffordp. My understanding is that the `jsx` extension is not needed, but I realise there might be a preference for some to use that extension. 

Another consideration is that WordPress might consider a coding standard around file extensions to keep things consistent across projects.

As this is a small change, it might be an idea to put together a PR with your proposal.

**Comment by cliffordp** [comment]
I've chosen not to use wp/scripts for my build process, for other issues besides this, but if you want me to submit it, I surely will... just won't be dogfooding it. Let me know.

**Comment by gziolo** [comment]
We don’t use .jsx extension for files in both Gutenberg and WordPress core. It’s something that is totally optional for many projects and needs extra configuration. In practice, it’s something that might become a challenge at scale when you refactor and you end up having files that no longer contain JSX and it forces you to rename the file or what’s even worse you forget to do so. It’s just simpler for the wider group of people to have one extension supported. I would be in favor of keeping things as is. It would require changes not only for the build script but to bring consistency also for:
- format-js
- lint-js
- test-e2e
- test-unit

It’s something you can raise for the WordPress Core JS meeting that happens every week (check https://make.wordpress.org/meetings/#core for the exact date) to validate with the wider group. I might be in the minority.

**Comment by gziolo** [comment]
> It’s something you can raise for the WordPress Core JS meeting that happens every week (check https://make.wordpress.org/meetings/#core for the exact date) to validate with the wider group. I might be in the minority.

Actually, I did it already, see:
https://docs.google.com/document/d/1grsJXePI9Dd1R4Cz4Pou82ufIt5Ylx5E76lONyyHblQ/edit.

There is a similar proposal for JS formatting opened by @a6software in #21151.

**Comment by gziolo** [comment]
Notes from the Core JS chat (https://make.wordpress.org/core/2020/04/06/javascript-chat-summary-march-31-2020/):

> There is a small discussion about seeing if it is necessary to discourage or not jsx files. Noticing that changes to accept jsx are quite simple. And are even accepted in some code already. There are different opinions, so the team prefer to continue the discussion.

**Comment by gziolo** [comment]
Given that this proposal aligns with other commands that already work with `.jsx`:
- `format-js`
- `lint-js`
- `test-unit`

I decided to open #28002 that implements it, mostly for consistency 😄
