### ISSUE TITLE
WordPress 5.4 Block Editor Props

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#21013]
Block editor is hosted in a different repository than the rest of WordPress. To correctly attribute/props credits for Block Editor contributions, we need a mapping of GitHub usernames to WordPress.org usernames.
WordPress.org profiles have a feature that allows connecting with a GitHub profile.

@Addison-Stavlo, @adekbadek, @agawish, @Aljullu, @alshakero, @AmirS, @andrewserong, @Aurorum, @bartczyz, @bastibeckr, @chriskmnds, @Copons, @costasovo, @CreativeDive, @davidshq, @ddryo, @devdivdev, @dhurlburtusa, @dphiffer, @dpkm95, @dratwas, @edmundcwm, @glendaviesnz, @gregrickaby, @Hypnosphi, @ItsJonQ, @jbinda, @JeanDavidDaviet, @jeryj, @jkmassel, @kasparsd, @laras126, @lukewalczak, @Mahjouba91, @marecar3, @mattnyeus, @microbit-mark, @miminari, @mlbrgl, @mmtr, @nekomajin, @nukaga, @ockham, @p-jackson, @phpbits, @phwebi, @pstonier, @ragnarokatz, @Ringish, @riobahtiar, @sainthkh, @scruffian, @sgomes, @Shizumi, @StevenDufresne, @struna, @WebPraktikos, @WodarekLy, @WunderBart, @yansern, All of you contributed to the Block Editor and have changes part of WordPress 5.4, so first of all thank you a lot for your contributations and for being a core contributor for WordPress 5.4!
Unfortunately based on WordPress mapping of GitHub profiles and on information collected for previous releases it was not possible to map your GitHub usernames to the corresponding WordPress.org usernames. I would like to ask all of you to map your GitHub profile with your WordPress profile. You can do so by going to https://profiles.wordpress.org/me/profile/edit/ there you will find a GitHub username option.
If you don't have a WordPress.org profile feel free to create a new one.
Doing this process will ensure that your contributions are properly credited on the next WordPress releases.

Thank you in advance!

**Comment by jorgefilipecosta** [comment]
Mentioning these usernames again as it seems GitHub has a limitation on the number of users one can mention in a single comment/message @sainthkh, @scruffian, @sgomes, @Shizumi, @StevenDufresne, @struna, @WebPraktikos, @WodarekLy, @WunderBart, @yansern.

**Comment by sainthkh** [comment]
Done.

**Comment by gregrickaby** [comment]
Done.

**Comment by JeanDavidDaviet** [comment]
Done.

**Comment by Shizumi** [comment]
Done!

**Comment by phpbits** [comment]
Done as well :) Thanks!

**Comment by Aurorum** [comment]
Also done, thank you! :)

**Comment by davidshq** [comment]
Done :)

**Comment by WodarekLy** [comment]
Also done! :)

**Comment by jbinda** [comment]
Done as well
---
Pozdrawiam
Jakub Binda


czw., 19 mar 2020 o 14:46 WodarekLy <notifications@github.com> napisał(a):

**Comment by scruffian** [comment]
Done

**Comment by lukewalczak** [comment]
Done

**Comment by nukaga** [comment]
Done, thank you! :)

**Comment by AmirS** [comment]
Done. Thank you!

**Comment by dphiffer** [comment]
Done, and sorry to add one more email to everyone's inbox!

**Comment by ragnarokatz** [comment]
done, thank you.

**Comment by Copons** [comment]
Done, thanks! 🙇

**Comment by struna** [comment]
Done, thanks ;)

**Comment by jeryj** [comment]
Done! Thanks for tracking all of us down! 🙇

**Comment by bartczyz** [comment]
Done, thank you! :)

**Comment by ddryo** [comment]
Done !

**Comment by nekomajin** [comment]
Done, thanks 🙃

**Comment by edmundcwm** [comment]
Done!

**Comment by Addison-Stavlo** [comment]
Done!  Thank you 😄

**Comment by jorgefilipecosta** [comment]
Thank you all for mapping your profile and for being WordPress contributors 👍
