### ISSUE TITLE
Allow ID attribute (HTML Anchor) on all blocks

### ISSUE THREAD

**Issue by bobeaston** [WordPress/gutenberg#21023]
Essentialy, this is a request for reconsideration of [issue #8124](https://github.com/WordPress/gutenberg/pull/8124).

Currently (as of 5.4-RC3-47470) attempts to use id="foo" on any block type other than Heading or Group is either removed while converting to blocks or is flagged as invalid HTML when editing blocks.  The attribute is useful for many other block types and is compliant HTML according to the latest [W3C HTML specification](https://html.spec.whatwg.org/), which says: "The class, id, and slot attributes may be specified on all HTML elements."

If we respect the W3C specification, all block types should support the HTML anchor attribute.  The decision made in #8124 to "allow the id attribute on blocks that support anchor" conflicts with the W3C specification.  WordPress should not be treating the attribute as invalid when converting from Classic to blocks. 
 
Now, for the UI side of the question: From a practical point of view, most people will rarely need a UI element, like the one under Advanced in the current Heading block, in the editor to add an HTML Anchor.  So, it might not be useful to provide the UI for some block types.  From 20+ years of experience, I think it would be useful to have the UI element on these block types: Heading, Paragraph, Separator, Form, Table, Group ... and maybe Collections.

**Comment by paaljoachim** [comment]
This feature has been added to Gutenberg.
I will go ahead and close this issue.

**Comment by paaljoachim** [comment]
This feature has been added to Gutenberg.
I will go ahead and close this issue.
