### ISSUE TITLE
Links in the content break arrow navigation through blocks

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2104]
To reproduce:

- insert a link in the content
- place the cursor before the link

<img width="438" alt="screen shot 2017-07-31 at 13 23 06" src="https://user-images.githubusercontent.com/1682452/28775750-e8a16004-75f3-11e7-8e7c-7a1c101bea1e.png">

- use the Right arrow key to move the cursor one character at a time
- as soon as the cursor reaches the start of the link, focus goes to the following block
- same when placing the cursor after the link, use Left arrow: focus goes to the previous block

**Comment by jasmussen** [comment]
Seeing this also:

![boundaries](https://user-images.githubusercontent.com/1204802/29269354-48491d32-80f1-11e7-8a90-bc6cd5ce9b79.gif)

**Comment by iseulde** [comment]
This was fixed by #2453.
