### ISSUE TITLE
Global styles: add hook to dynamically change theme global styles to facilitate style variations and previews

### ISSUE THREAD

**Issue by nickcernis** [WordPress/gutenberg#21046]
### Is your feature request related to a problem? Please describe.
Global styles are shaping up really well! Thanks for all the work that's gone into them so far.

Our team has been trying out global styling, so please consider this an experience report as well as a feature request.

**We'd love to provide the ability to swap-out a theme's global styles and offer multiple styling options without switching themes.**

I expect other theme and plugin developers would like to do the same. @richtabor demonstrated a similar idea in the [first Block-Based Themes Slack meeting](https://make.wordpress.org/themes/2020/02/20/block-based-themes-chat-summary-19-feb-2020/). Variations were implemented via Customizer controls with the intent to migrate to global styles later.

In experiments so far we've encountered one big issue that blocks the ability to switch out global styles dynamically:

**We can only alter a theme's default global styles by overwriting the `experimental-theme.json` in the theme root.**

This creates two challenges:

1. Admins cannot preview theme default global styles changes. They have to apply them to the live site before they can see the variations a theme provides.
2. Overwriting the `experimental-theme.json` when applying new styling can destroy manual edits a user has made.

### Describe the solution you'd like
Apply a `theme_global_styles` filter when the `experimental-theme.json` is first read by Gutenberg, and before any styles resolution occurs:

https://github.com/WordPress/gutenberg/blob/f0e36362104e9be9e655ce8cfa9e5c6b45913602/lib/global-styles.php#L160-L164

Theme and plugin developers can then hook into this to override a theme's default styling dynamically. This opens up more creative options for developers and users, and offers a migration path for themes like Go that currently provide variations via the Customizer.

### Describe alternatives you've considered
- Drop the idea of switching global styles dynamically. Users would then only be able to switch global style defaults by switching themes. This effectively kills the idea of mono-themes like GoDaddy's Go if they want to be able to use global styles, though.
- Continue to overwrite the `theme.json` file. Warn users they can't preview variations because they apply immediately.
- Implement an official style variations system in Gutenberg, like the [Variants in Styled System](https://styled-system.com/variants/) or the [Modes from Theme UI](https://theme-ui.com/color-modes). The downside to this is that Gutenberg would also have to implement variation libraries, previews, and switchers and maintain those components. Not every theme will need these, so perhaps they're better left to plugins and themes to implement as they choose — we just need the ability to switch global styles dynamically to start on that work. Some guidance about whether a filter PR would be accepted or not would be really helpful!

**Comment by justintadlock** [comment]
I believe this is now satisfied by the global styles variations feature.  @nickcernis - Do you think we can close this one out now?

**Comment by nickcernis** [comment]
@justintadlock Sure, let's close this out.
