### ISSUE TITLE
Are gradients supported now?

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#21055]
Are gradients supported now in the latest Gutenberg plugin?
I added theme support for `editor-gradient-presets` and added some gradients, 
but only solid colors can be selected, gradient selection is completely missing.
Is this an experimental feature? Is this only available in Gutenberg master?

And will preset gradient selection still work with custom colors 
disabled (`add_theme_support( 'disable-custom-colors' );`?

**Comment by jorgefilipecosta** [comment]
Hi @strarsis, the cover and buttons block both support gradients. Was the option to pick a gradient not available on these blocks with WordPress 5.4 or the last Gutenberg plugin?

> And will preset gradient selection still work with custom colors
disabled (add_theme_support( 'disable-custom-colors' );?

Yes, it should work with custom colors disabled.

**Comment by strarsis** [comment]
@jorgefilipecosta: Ah, is it possible to enable (background) gradients for `core/group` and `core/column` blocks?

**Comment by talldan** [comment]
@strarsis It looks like #21375 should do that.

**Comment by jorgefilipecosta** [comment]
Closing this issue as I think all the questions were answered :)
