### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by a4jp-com** [WordPress/gutenberg#21059]
https://wordpress.org/support/topic/the-edit-block-icons-hide-the-paragraph-above-making-it-difficult-to-edit-pages/#post-12567059

**Comment by paaljoachim** [comment]
Hi

We need step by step details with screenshots and also an animated gif if possible. 
Thanks.

**Comment by earnjam** [comment]
The solution here is to use the Top Toolbar mode. It would be a massive waste of space to provide a big enough gap between each block to fit the full block toolbar without overlap. 

This was an intentional design decision, so I don’t think it qualifies as a bug. I’m going to close as invalid. 

If you have some proposed solutions that might help, feel free to add those here or open a new issue as an enhancement.

**Comment by a4jp-com** [comment]
The icons just need to be moved down about 14 pixels to perfectly show everything even without changing the gap at all. Can that be done? Even if it is just half of that 7 pixels. I want the icons on the box being edited, not in the top bar, as it is really annoying on a 4k screen having to move the mouse that much all the time to change any basic setting. It's also terrible having the icons just hiding the content by pixels. If 1 pixel of space was added to any box that would also easily give 2 pixels of space. Please reopen this and move the icons a few pixels down please.

**Comment by a4jp-com** [comment]
Changing this line so the dead space at the bottom of the margin is removed would make it easy to make the text readable. The icons would also be 48 pixels as Google recommends and nothing would change.
`<div role="toolbar" aria-orientation="horizontal" class="block-editor-block-contextual-toolbar" aria-label="Block tools" style="margin-bottom:0!important">`

As the paragraphs already have 28 pixels padding, just making the bottom only 35 to 38 pixels would make the text readable even if it is cut off a bit. We just need to be able to see enough of the text to read it to work and 7 to 10 pixels isn't a big change.
`<p aria-label="Paragraph block" role="textbox" aria-multiline="true" class="wp-block block-editor-block-list__block has-selected-ui is-selected rich-text block-editor-rich-text__editable" contenteditable="true" id="block-b453c51a-790b-422a-8034-a1f05629afcf" data-block="b453c51a-790b-422a-8034-a1f05629afcf" data-type="core/paragraph" data-title="Paragraph" tabindex="0" style="white-space: pre-wrap; transform-origin: center center; transform: none;margin-bottom:35px!important">`

**Comment by earnjam** [comment]
@a4jp-com If you'd like to open a pull-request with your suggested changes, I'd be happy to take a look and we can get some feedback from the design team.

**Comment by a4jp-com** [comment]
Examples of how the text gets covered up:
[http://a4jp.com/0/bugs/2020-03-18th-09-18am.png](http://a4jp.com/0/bugs/2020-03-18th-09-18am.png)
[http://a4jp.com/0/bugs/2020-03-18th-09-19am.png](http://a4jp.com/0/bugs/2020-03-18th-09-19am.png)
----------------------------------------------------
An example of the space being changed from 28 to 38 pixels at the bottom of paragraphs. I don't think almost anyone would even notice the change in size.
[http://a4jp.com/0/bugs/2020-03-23-08-07pm.png](http://a4jp.com/0/bugs/2020-03-23-08-07pm.png)
An example after CSS changes. The text is easy to read and editing is heaps better instead of having to click on another block just to move the icons that cover content. And it's also easier to edit or move blocks around as you don't have the go to the top bar lots of times.
[http://a4jp.com/0/bugs/2020-03-23-08-06pm.png](http://a4jp.com/0/bugs/2020-03-23-08-06pm.png)

**Comment by a4jp-com** [comment]
I haven't done a pull request here for years. I'll check how to do it again. I just need to create a new fork and then edit the code, right?

**Comment by paaljoachim** [comment]
Hey @a4jp-com 

The screenshots you are linking to is not the newest Gutenberg plugin version 7.8.
I did though mention this issue to Joen, and he made this PR. We can now have a discussion about the gap distance in the PR.

https://github.com/WordPress/gutenberg/pull/21166
