### ISSUE TITLE
Three Column Block: Unable to Display Recurring Payments Block

### ISSUE THREAD

**Issue by allykmyta** [WordPress/gutenberg#21058]
When the Recurring Payments block is added as its own individual block or in a two-column block it appears correctly. When added in a three-column block it is not possible to configure this block.

**To reproduce**
1. Go to page editor and add a three-column block
2. Select first column and add the Recurring Payment block
3. See the inability to configure this block

![Screenshot](https://d.pr/i/ifx60A/GGqW34XE1T+)
Original screenshot link: https://d.pr/i/ifx60A/GGqW34XE1T

**Expected behavior**
Should be able to configure this block clearly as it currently works in both two column block and its own individual block.
![Screenshot](https://d.pr/i/31n0o2/QuUAjedBtt+)
Original screenshot link: https://d.pr/i/31n0o2/QuUAjedBtt

**Desktop (please complete the following information):**
 - OS: Catalina vs. 10.15.3 
 - Browser: Chrome
 - Version:

**Comment by gziolo** [comment]
There is no Recurring Payments block in the WordPress core. This issue needs to be filed against the plugin that introduces this functionality.
