### ISSUE TITLE
Is it a specification that the "wp-block-heading" class has disappeared from the heading block?

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#21062]
I am trying 5.4-RC3.
One thing I noticed is that the heading block doesn't have "wp-block-heading".

From what I have seen, the structure of the heading block is as follows:
`.wp-block[data-type="core/heading"] > h2.rich-text`

However, paragraph blocks have a "wp-block-paragraph" class.
`.wp-block[data-type="core/paragraph"] > p.rich-text.wp-block-paragraph`

(".block-editor-rich-text__editabl" is omitted)

**Comment by youknowriad** [comment]
That's actually not a regression because the frontend doesn't have this class and we want to match the frontend as closely as possible. The paragraph class has also been recently removed.

Thanks.

**Comment by ddryo** [comment]
understood! Thank you very much!
