### ISSUE TITLE
Deleting or repositioning a block may force focus to the top of the editing screen.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#21061]
As you can see from the title, after deleting a block or changing its position, if you try to edit another block, the focus may be forced to the top of the edit screen.

**To reproduce**
1. Swap or delete blocks.
2. Click another block to try to edit.
3. Sometimes it moves to the top of the screen forcibly.

**Screenshots**
Example 1: When blocks are replaced.

![ex1_swap](https://user-images.githubusercontent.com/31400297/77223518-ad05cf80-6ba0-11ea-9561-ec61a0859d77.gif)

Example 2: In some cases, everything will be selected from the block that should have been selected to the top of the screen.(I feel like this is the case when there are many types of blocks.)
![ex2_swap_selected](https://user-images.githubusercontent.com/31400297/77223550-f5bd8880-6ba0-11ea-9838-1bf8febcbb42.gif)

Example 3: Occurs after deleting a block.
![ex3_deleted](https://user-images.githubusercontent.com/31400297/77223603-6d8bb300-6ba1-11ea-9921-84cd6bddbe33.gif)

**Verification environment**
 - OS: Mac OS Catalina
 - Browser : Google Chrome
 - Theme : Twenty Twenty
 - WP Version : 5.4 and 5.3
 - Language : Japanese

It also happened with the Gutenberg plugin(ver. 7.7.1) installed.

**Comment by ddryo** [comment]
Gutenberg 7.8.1 may no longer have this bug...！

**Comment by talldan** [comment]
I couldn't reproduce in the latest version @ddryo, is it resolved for you as well?
