### ISSUE TITLE
Firefox: js error when inserting a link: the link modal doesn't show up

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2106]
Noticed while testing #2098 

Using Firefox, just select some text and press the button to add a link. Getting a JS error in the console, seems related to selection range:

![screen shot 2017-07-31 at 12 33 54](https://user-images.githubusercontent.com/1682452/28775328-986c8688-75f1-11e7-9fce-3d09cb1703a9.jpg)

Latest Firefox, on macOS and Windows.

**Comment by tg-ephox** [comment]
@afercia this looks to be a duplicate of https://github.com/WordPress/gutenberg/issues/1069

**Comment by afercia** [comment]
@tg-ephox it is, thanks!
