### ISSUE TITLE
Buttons Block has extra padding when used inside a Media & Text Block.

### ISSUE THREAD

**Issue by towfiqi** [WordPress/gutenberg#21067]
**Is your feature request related to a problem? Please describe.**
With the latest nightly build , I see that the button block has been changed and now it appears inside a container so that adding multiple buttons are possible. Great Initiative. 

But there are 2 issues with the Button Block.
1. The Button Text is always uppercase and cannot be capitilized/lowercased.
2. When the button block is inserted inside a Media & Text Block, there is extra padding around the buttons, which prohibits the buttons to line up with the text.
![alt text](https://i.imgur.com/ADxooX3.png "Buttons not Lining Up")

**Describe the solution you'd like**
1. Users should be able to change cases of any elements, be it buttons, quotes or headings.
2. Buttons should not have an extra padding inside Media & Text Blocks.

**Comment by talldan** [comment]
Hi @towfiqi, thanks for raising this issue.

The first issue, about the uppercase text appears to be related to the Twenty Twenty theme, which applies the `text-transform: uppercase;` style. Other themes don't apply this style.

A workaround could be to use a custom class name and custom css to override that.

If you're able to make an issue for that on trac (where Twenty Twenty issues are reported) it would be very much appreciated:
https://core.trac.wordpress.org/

**Comment by towfiqi** [comment]
Sorry, I am not sure how it did not occur to me that the uppercase style was being applied by the theme. Forgot that its possible to enqueue stylesheet for the editor body.

**Comment by youknowriad** [comment]
I believe the issue is because those styles are only supposed to affect the first level of innerBlocks not nested innerBlocks. I'm afraid of touching media & text block styles :P (BC...) so @jorgefilipecosta can you help here?

**Comment by sdixon194** [comment]
Unsure if this is related or I should open a new issue, but centering the block inside a media and text block doesn't appear to center it in the editor either. Some other general alignment wonkiness. 

![Screen Capture on 2020-04-11 at 12-32-29](https://user-images.githubusercontent.com/33553323/79049268-a17e5500-7bf0-11ea-8b20-edaae8f2e7c1.gif)
