### ISSUE TITLE
".is-selected" not added to current block if that block is empty

### ISSUE THREAD

**Issue by Abruptive** [WordPress/gutenberg#21071]
**Describe the bug**
The "is-selected" class does not get added to an empty block. And the "is-typing" class only gets added if you navigate blocks using your keyboard.

**To reproduce**
1. Make sure you have a few blocks so you can navigate.
2. Click an empty block and check the inspector.
3. Try navigating blocks using your keyboard and using mouse clicks. You'll see the difference.

**Expected behavior**
- The blocks should add the "is-selected" class regardless.
- Blocks should add the "is-typing" class even if clicked.

**Screenshots**
https://share.getcloudapp.com/12u1Qdm4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Latest

**Additional context**
- Gutenberg Included with the Latest WP Version

**Comment by talldan** [comment]
> The "is-selected" class does not get added to an empty block.

Hi @Abruptive, I couldn't reproduce this issue, but it'd be good to double check what you mean by empty block? I tried with a paragraph that didn't have text and it worked ok. It'd be great if you can test with the latest version of the Gutenberg plugin or the WordPress 5.4 release candidate.

> And the "is-typing" class only gets added if you navigate blocks using your keyboard.

This seems like the correct behavior, if a block is clicked that's not typing so the class shouldn't be added.

**Comment by enriquesanchez** [comment]
Hi @Abruptive! 👋

I was also not able to reproduce. I see the `is-selected` class even if the block is empty:

<img width="1190" alt="Screen Shot 2020-04-01 at 16 19 20" src="https://user-images.githubusercontent.com/3276087/78192119-ba3e7c00-7434-11ea-8576-232ff2fa3c0f.png">

Where you able to double-check as @talldan suggested?

**Comment by Abruptive** [comment]
All good! Must've been an older version. Thanks!
