### ISSUE TITLE
Calendar not closing after clicking help in Chrome

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21098]
**Describe the bug**

Merged PR: https://github.com/WordPress/gutenberg/pull/20824

I just tested...
Clicking the Calendar help link to view the information then clicking outside the box (into empty space) it does not close.

**Steps to reproduce**
1. In Chrome, create a new post
2. From the Document panel in the sidebar click the 'Immediately' button for the Publish option
3. When the calendar opens, click Calendar Help
4. Try clicking outside of the popover

Expected behaviour - The popover closes
Actual behaviour - The popover stays open

![Date-Picker-screen](https://user-images.githubusercontent.com/5323259/77408191-a309e980-6db7-11ea-800d-5cf522197d49.gif)

**Comment by talldan** [comment]
I can't reproduce this @paaljoachim. It may have already been fixed:
![calendar](https://user-images.githubusercontent.com/677833/78624322-f140e180-78bb-11ea-8dce-651fb036c03d.gif)

**Comment by paaljoachim** [comment]
Hey Dan @talldan 

I am retesting locally using Chrome and Twenty Twenty.
The same problem is still in effect.

Clicking outside the Calendar Help screen into an empty area does not close the help screen.
It does close it once I click into an empty paragraph block or another block is selected.

![Publish-screen-help-stuck](https://user-images.githubusercontent.com/5323259/78638968-75d83380-78ad-11ea-9b5e-37a29df6175c.gif)

**Comment by talldan** [comment]
Ah ok. I use Firefox. I can reproduce in Chrome, but still seems fine in Firefox. It would be great if you can include browser info when reporting as that'll prompt me to test the right browser 👍

**Comment by paaljoachim** [comment]
I just checked the original post and noticed that I included a mention of browser in step 1, but it is probably easy to overlook. I will remember to keep browser info, theme etc separate from the steps. Making it more obvious. Thanks for checking Dan!

**Comment by talldan** [comment]
@paaljoachim I edited the description to include those details 😄
