### ISSUE TITLE
Hide the toolbar when the Inserter is open

### ISSUE THREAD

**Issue by pablohoneyhoney** [WordPress/gutenberg#21094]
When the user's intent is to browse or add a new block, the toolbar should ideally hide to clean the interface presented and keep the focus on the chosen action. And rather indicate where the new content would be placed. 

**Currently**

<img width="840" alt="Screen Shot 2020-03-23 at 6 34 11 PM" src="https://user-images.githubusercontent.com/25516611/77370167-b32db480-6d36-11ea-92c2-1f76eeaabfd3.png">
 
**Proposal**

<img width="840" alt="inserter-notoolbar" src="https://user-images.githubusercontent.com/25516611/77370425-38b16480-6d37-11ea-84dd-e366138708e2.png">

**Comment by youknowriad** [comment]
I think now that the inserter is a panel, this issue is invalid. I'm closing but let me know if it's not.
