### ISSUE TITLE
Gallery Block Description Doesn't Show With Underscores

### ISSUE THREAD

**Issue by susanjanec** [WordPress/gutenberg#21101]
**Describe the bug**
When adding a description with underscores in it, the description doesn't appear when clicking into the individual image. 

**To reproduce**
1. Apply the theme Canard
2. Add the Gallery block
3. Add images and add a description with an underscore within the description
4. When clicking into the individual image, the description with the underscores in it will not show, but if adding a description on another image without an underscore in it will show the description when viewing the individual image.

**Expected behavior**
When clicking into the image, the description should show, even if there are underscores within the description 

**Screenshots**
Tested this on my own test site here - https://susanteststhings.home.blog/testing-gallery-block-description/

The first and third image has a description set with underscores. The second image in the center has a caption without underscores.

**Desktop (please complete the following information):**
 - OS: High Sierra 10.13.6
 - Browser Chrome
 - Version Version 80.0.3987.132

**Additional context**
- The site reported initially and test site are both hosted at WordPress.com

**Comment by talldan** [comment]
Hi @susanjanec, I couldn't reproduced this without the Canard theme. If it only occurs with the Canard theme, I'd recommend reaching out to the theme authors about the issue.
