### ISSUE TITLE
Show template part name in the navigator

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21104]
Lets display the _name_ attribute in the navigator for template parts.

![image](https://user-images.githubusercontent.com/548849/77425880-b62ab280-6dd3-11ea-9d4b-7fb8bc8a9a97.png)

Example: _Header_, _Footer_, etc.

**Comment by kirilzh** [comment]
I can take this issue : )

**Comment by noahtallen** [comment]
Note: we need to follow up with this to include more information when we create a template part. At the time being, we only gather a slug attribute. It might be useful to add a display name as well.
