### ISSUE TITLE
Shortcode transforms on paste no longer work

### ISSUE THREAD

**Issue by hrkhal** [WordPress/gutenberg#21103]
**Describe the bug**
When pasting a pre-made shortcode string into the paragraph block it no longer transforms into the block with the relevant transform defined. 

I.e pasting in `[gallery ids="13,12,14"]` does not transform into a gallery block even though the transform is defined for it: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/transforms.js#L60

It isn't even converted into the generic shortcode.

**To reproduce**
Steps to reproduce the behaviour:
1. Create a new post
2. Paste the following into a paragraph block: `[gallery ids="13,12,14"]` 
3. Note that it remains as plain text in the paragraph block and that it isn't transformed into the gallery block

**Expected behaviour**
Pasting a pre-made shortcode into the paragraph block should transform it into the relevant block that has a transform defined for it. It used to do so but we're not sure when they stopped working.

**Additional context**
- This is happening on 5.3.2 and on the various 5.4-RC3 nightlies we've been testing
- I've replicated the issue on a clean install of WordPress with the twentytwenty theme installed
- Its happening for users on Mac and PC and on Firefox and Chrome
- If I create a classic block, put the gallery shortcode into that and then `Convert to blocks` it is correctly transformed to a gallery block.

**Comment by jorgefilipecosta** [comment]
I was able to replicate the issue in WordPress 5.3.2 and WordPress 5.4.

**Comment by nosolosw** [comment]
I've prepared a potential fix for this at https://github.com/WordPress/gutenberg/pull/21864
