### ISSUE TITLE
Can't select aligned images

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#21114]
**Describe the bug**
If an image block is aligned and there is some text that floats in the remaining space the image can't be selected with the mouse anymore.

**To reproduce*
1. Add a page
2. Add an image
3. Add some text below the image
4. Resize the image to 50% of text width
5. Align the image right
6 Observe the bug

**Expected behavior**
I should be able to click on the image to select it.

**Screenshots**
![image-select](https://user-images.githubusercontent.com/107534/77454998-f86ae880-6e01-11ea-9221-dd71aab34293.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 74

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by strarsis** [comment]
+1, same issue. Can be reproduced in [Frontenberg](https://frontenberg.tomjn.com/post.php?post=1&action=edit) Gutenberg demo.

**Comment by kathrynwp** [comment]
Can replicate in Firefox 74.0 (64-bit), macOS 10.14.6

Another person replicated in Chrome 80.0.3987.149 (Official Build) (64-bit), OS unknown

**Comment by roo2** [comment]
I tracked it down to this change https://github.com/WordPress/gutenberg/pull/20576 @ellatrix @youknowriad 
I'll look into if I can work out a fix that preserves the intention of that PR or perhaps we can revert just that PR safely

**Comment by draganescu** [comment]
Fixed by #21167 (props @ellatrix)
