### ISSUE TITLE
Pressing Enter on an empty paragraph block only sometimes blocks creating a new block

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2112]
Gutenberg v0.6
## Issue Overview
If I press enter on an empty paragraph block, sometimes it creates a new block. sometimes it doesn't. This behavior should be consistent.

It seems as though this is based on if I have entered content in the block already or not. If I press enter without having entered any content, for example by pressing enter twice in a row, then I end up with multiple empty blocks. If I type something and then delete it, then pressing enter on the newly empty block does nothing. 

## Expected Behavior
I would expect that the behavior was consistent and not dependant on if I had entered content previously. I personally think it should always be to NOT create a new block if the current one is empty.

**Comment by iseulde** [comment]
Sorry about that! I'll have a look into it. I also notices some other ENTER bugs since that change in behaviour this release.

**Comment by maddisondesigns** [comment]
Having a new block created every time Enter is pressed is going to be **extremely** frustrating. If I write 5 paragraphs of text and then decide to move that text, I don't want to have to move 5 separate blocks. I should be able to move just one block, that contains all 5 paragraphs. Gutenberg shouldn't be automatically creating blocks for me. That should be left up to me. If I want to create a simple post with multiple paragraphs, I should be able to put that in one Text block, and not have it separated out into multiple blocks.

Same frustration is going to exist if I want to copy and paste a couple of paragraphs of text from one page to another. I don't want to have to perform multiple copy and pastes, I should be able to do it in one hit.

It should be up to the user to decide whether their text content is across multiple blocks or in one block, not Gutenberg.
