### ISSUE TITLE
Text color custom color pallette doesn't line up

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21120]
When you select a custom color, the palette is out of line:

![2020-03-24 at 19 37](https://user-images.githubusercontent.com/253067/77471407-22c0a400-6e0a-11ea-98e5-0da3463faee1.png)

I would suggest just aligning it with the popover above is a visual fix. Potentially also bringing it down by 10px to not clip the 'clear' button in Chrome. In Firefox there is no clipping.

**Comment by mtias** [comment]
This seems fixed:

![image](https://user-images.githubusercontent.com/548849/109818815-b4987a00-7c33-11eb-9ac9-be9a4d0510d4.png)
