### ISSUE TITLE
Gutenberg conflicts with Grammarly chrome extention 

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2113]
## Issue Overview
As someone with grammar and spelling issues, I need to use additional technologies to not screw up there, their, thier, and they're. I know I'm not without compony in this challenge. I use the [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) chrome extension to make my writing a bit more readable.  Grammarly adds markup which highlights misspellings, wrong word choices, and common grammar errors. Gutenberg sometimes saves this markup in a nonvisual manner that creates unexpected line breaks on the front end and can't be deleted in Gutenberg without going into the text view. 

This is a regression from the current WordPress editor. 

## Steps to Reproduce (for bugs)
1. Install Grammarly
2. Make a spelling mistake in the middle of a line
3. Save and preview the post

**Comment by hedgefield** [comment]
Related: #1761.

**Comment by jasmussen** [comment]
Closing this one in favor of #1698, which I'll give a better label.
