### ISSUE TITLE
Buttons Block: Give the user the option to use capital or lowercase letters

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21144]
Today the buttons block uses all capital letters.
It would be nice to be able to change button text to lowercase letters. 
Example Going from "TEST BUTTON" to "Test button".

If I want to use all capital letters then I can turn on the caps lock key and make all the letters capital letters. Right now I have no option  to turn these off. 

Fix. Turn off all caps. Give the user the option to use capital or lowercase letters.

![Screen Shot 2020-03-25 at 14 50 43](https://user-images.githubusercontent.com/5323259/77543638-463a2c00-6ea8-11ea-99da-e0531864c805.png)

**Comment by mtias** [comment]
> Today the buttons block uses all capital letters.

This is the theme forcing that display, not the button block:

![image](https://user-images.githubusercontent.com/548849/77560276-88ba3380-6ebd-11ea-9e43-955ff2fa5548.png)

**Comment by paaljoachim** [comment]
Ahhh so this is a Twenty Twenty theme issue.
I will close it and mention it in the core-themes channel.
Thanks Matias!

**Comment by mtias** [comment]
No worries! It's another example of how tricky it is to navigate what the theme does and what the block does, since user won't generally see any of those boundaries.

**Comment by ianbelanger79** [comment]
Trac ticket for this issue: https://core.trac.wordpress.org/ticket/49710
