### ISSUE TITLE
RichText can't have style attribute containing CSS Variables (ver 6.5)

### ISSUE THREAD

**Issue by hrsetyono** [WordPress/gutenberg#21145]
## Describe the bug

I have a RichText and PanelColorSettings. I want to implement the changes as CSS Variable `--bgColor` and `--textColor`.

The color is applied properly using the default value, but when I select any color, they're gone. The CSS Variable in `style` are gone.

## To reproduce

Full code sample can be found here https://github.com/hrsetyono/wp-blocks-tutorial/tree/master/04c-custom-colors

1. Create a Color setting in InspectorControl (both `editor.PanelColorSettings` and `editor.ColorPalette` are bugged)
1. Create a RichText and apply the color as CSS Variable in `style` like this:

```js
// var atts = props.attributes;
el( RichText, {
  tagName: 'p',
  className: props.className,
  value: atts.content,
  style: { '--bgColor': atts.customBgColor, '--textColor': atts.customColor },
  onChange: ( value ) => {
    props.setAttributes( { content: value } );
  }
} )
```

If I replace the CSS Variable with normal CSS like below, it works fine:

```js
style: { 'backgroundColor': atts.customBgColor, 'color': atts.customColor },
```

## Expected behavior

The CSS Variable should be updated. Instead, the CSS variable is gone from `style` attribute.

This works when I implemented it on `div`, but not on `RichText`.

## Desktop:

- OS: Windows 10 Home 1903
- Browser: 80.0.3987.149 (Official Build) (64-bit)

## Additional context

- Gutenberg Version: 6.5 (built-in from WP 5.3)

## Temporary Solution

Wrap the RichText inside a div

```js
el( 'div',
  {
    style: { '--bgColor': atts.customBgColor, '--textColor': atts.customColor }
  },
  el( RichText, {
    tagName: 'p',
    className: props.className,
    value: atts.content,
    onChange: ( value ) => {
      props.setAttributes( { content: value } );
    }
  } )
),
```

**Comment by kathrynwp** [comment]
Hi @hrsetyono  – is this still occurring with the latest version of Gutenberg (13.7.3) and WordPress (6.0.1)? Thanks!

**Comment by kathrynwp** [comment]
As there's been no movement on this in several years, I'm going ahead and closing this out. If you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.
