### ISSUE TITLE
Deleting or cutting all content from a Paragraph Block freezes page

### ISSUE THREAD

**Issue by bjcfuller** [WordPress/gutenberg#21183]
**Describe the bug**
Removing all content from a Paragraph Block, either through 1) backspacing or 2) selecting and cutting, immediately freezes the page and/or browser tab.

Backspacing results in the issue only when the final (first) character is reached. Selecting all paragraph content and deleting does not produce this issue.

Issue appears to be confined to Safari.  Chrome (v80.0.3987.149) and Firefox (v74.0) do not exhibit this issue.  There are no JavaScript errors when the issue occurs.

WP version 5.3.2

**To reproduce**
1. Create a new page/post or edit an existing page/post.
2. If none exist, create a paragraph block and enter some text.
3. Delete characters using the backspace or delete key.
4. When attempting to delete the last remaining character, observe that the character is not deleted and the interface freezes.
5. Alternatively, select all of the text in the block and perform a cut (either via the Edit menu or keyboard shortcut).
6. Observe that the text is not cut and the interface freezes.

**Expected behavior**
Text in a paragraph block should be able to be completely removed either through cutting or backspacing without freezing the interface, and the paragraph block should return to placeholder text.

**Desktop**
 - OS: macOS 10.15.3
 - Browser: Safari
 - Version: 13.0.5

**Comment by jorgefilipecosta** [comment]
Hi @bjcfuller, thank you for reporting this issue 👍 
I'm not being able to reproduce this issue are you still facing this problem?
Do you have any plugin/them installed that may interact with the editor?

**Comment by bjcfuller** [comment]
Hi @jorgefilipecosta, I've since done some more testing and determined that the issue is likely related to the theme we have installed. I'm not sure what the fix is yet but will update this thread if the issue traces back the block editor. 

Looping in my colleague @johnpennypacker. 

Thank you!

**Comment by bjcfuller** [comment]
I was able to resolve this issue in our theme, so it is definitely not an issue with the block editor.

Thanks @jorgefilipecosta for your attention to this!
