### ISSUE TITLE
Small annoyances with gutenberg updates

### ISSUE THREAD

**Issue by charlottehobbit** [WordPress/gutenberg#21199]
Hey Wordpress,

Gutenberg is going downwards FAST in terms of user friendliness. Some things you might want to look into:

- No borders around blocks so I can't see if I'm actually dragging a block into another (container) block;

- The + button for adding blocks inbetween 2 other blocks is really difficult to find with mouseover (only on the exact correct spot), and half the time it's also unclickable (typing cursor instead of hand cursor);

-Can't properly type an exact value for things like spacer height, container width, etc.

- Why is spacer height suddenly limited to a minimum of 20 px?!

I've loved Wordpress for over 5 years now, please let me love yo a bit longer. Because working like this every day is really tiresome.

**Comment by paaljoachim** [comment]
Hello Charlotte

Thank you very much for your feedback!

Regarding:

> No borders around blocks so I can't see if I'm actually dragging a block into another (container) block;

Drag & handles is being worked on in this issue: https://github.com/WordPress/gutenberg/issues/20762

> The + button for adding blocks inbetween 2 other blocks is really difficult to find with mouseover (only on the exact correct spot), and half the time it's also unclickable (typing cursor instead of hand cursor);

It is a known bug which is also being worked on: https://github.com/WordPress/gutenberg/pull/21232


> Why is spacer height suddenly limited to a minimum of 20 px?!

I looked it up and found a specific issue for this: https://github.com/WordPress/gutenberg/issues/18906
There are discussions in the issue and a better solution will be found.

**Comment by paaljoachim** [comment]
When you feel that your concerns have been raised then you can also go ahead and close this issue.
Have a wonderful day!

**Comment by talldan** [comment]
It looks like all these issues are being tracked separately, so I'll go ahead and close this as a duplicate.
