### ISSUE TITLE
Extreme flickering of the Block Pattern selection panel

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#21194]
**Describe the bug**
If I have my browser window at full width, editor mode on full screen, and I click the button to open the block pattern selection panel, the panel opens but flickers **a lot.**

This only happens with some themes, but I was not able to narrow down why.
I can reproduce it with Twenty Twenty but not Twenty Nineteen.
-It does not make a difference if I create a new post, or edit an existing post.
if I reduce the window width, the bouncing stops.

**To reproduce**
1. Make sure the browser window is at full width
2. In the editor, click on the icon to open the block pattern selection panel.
3. Watch the panel and the panel content bounce around.

**Expected behavior**
The panel and its content should not move once it is opened.

**Screenshots**
**Warning, do not watch this .gif if you are sensitive to movement.**
https://imgur.com/a/W44GJ1S

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Google Chrome Version 80.0.3987.149
- Gutenberg version 7.8.0
WordPress Version 5.3.2 and 5.5-alpha-47511

**Comment by smwcollege** [comment]
I'd like to add that we are only experiencing this issue with Gutenberg full-screen mode. While my screen recording framerates do not capture how fast it is flickering, it looks exactly like the what carolinan is seeing. Reducing the browser window size also fixes it, but it still happens with dev tools open (thus shrinking the viewport) provided the browser is maximized and the editor is full-screen, which leads me to think it's related to browser rendering.

I was able to stop the flickering by commenting out this code using dev tools:
`@media (min-width: 782px)
.components-panel__header.edit-post-sidebar-header__small {
    display: none;
}` 

**Screenshots**
Full-screen testing: [https://recordit.co/br41et0d28](https://recordit.co/br41et0d28)
Commenting out CSS removes flicker: [https://recordit.co/qqd9XPbWc9](https://recordit.co/qqd9XPbWc9)

**Desktop:**

- OS: Windows 10
- Microsoft Edge version 80.0.361.109
- Gutenberg version 7.8.1
- WordPress version 5.4

**Comment by carolinan** [comment]
I am no longer able to reproduce this. Because the panel has moved and other changes has been made I would say that this has been fixed.

**Comment by Morgunov-Vitaly** [comment]
I have the same issue!
