### ISSUE TITLE
Platform Component is undefined in WP 5.3.2

### ISSUE THREAD

**Issue by vicolaspetru** [WordPress/gutenberg#21200]
**Describe the bug**
I use `Platform.select()` in my plugin, and now when I tested it with WP 5.3.2 (Gutenberg deactivated) I have the following error `TypeError: undefined is not an object (evaluating 'm.Platform.select')` in post edit page. Will be this component included in the next WP update?

**Comment by talldan** [comment]
@vicolaspetru The component was only recently added - https://github.com/WordPress/gutenberg/pull/18058.

Is it available in WordPress 5.4? If not it should be in 5.5.

**Comment by vicolaspetru** [comment]
Yes it's now available in the WordPress 5.4 version. Thank you! 🙂
