### ISSUE TITLE
SSR block nested inside InnerBlocks not rendering inside container

### ISSUE THREAD

**Issue by codigodo** [WordPress/gutenberg#21206]
I'm trying to render a ssr block inside another ssr block, but it appears outside the container.

This is how I save the parent block content `save: () => <InnerBlocks.Content />`

I display it to the client this way
``` javascript
<div id={panelid} className={classcollapsible} aria-expanded="false">
  <div dangerouslySetInnerHTML={{ __html: innerblockcontent }} className="panel-body panel-body-inverted" />
</div>
```

Resulting on this
![error](https://i.imgur.com/JaDISwu.png)

This issue adds some context https://github.com/WordPress/gutenberg/issues/6751#issuecomment-496038612

**Comment by talldan** [comment]
@codigodo Sorry it's taken a little (or long) while to get back to you on this issue. Is it something you're still experiencing?

I'm finding it a little hard to understand from the information provided what could be happening, would you be able to provide a fuller code example?

**Comment by talldan** [comment]
Closing the issue as there's been no response from the OP.
