### ISSUE TITLE
The template preview causes the menu container to grow and shrink

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21213]
The `TemplatePreview` being rendered within the dropdown menu seems to be adding a little bit of extra spacing at the bottom.

cc @youknowriad

**Comment by carolinan** [comment]
Is that's what is happening here? https://github.com/WordPress/gutenberg/issues/21194

**Comment by mtias** [comment]
@carolinan that one is separate, this is about the template selector (top left) in the "edit site" editor.
