### ISSUE TITLE
Increase default menu items per REST page to 100

### ISSUE THREAD

**Issue by kadamwhite** [WordPress/gutenberg#21212]
Per [discussion in the `#core-restapi` channel](https://wordpress.slack.com/archives/C02RQC26G/p1585128430000900) about the menus endpoints added in #20292, we should up the default per_page value for the new collections controllers to 100 (the maximum) as there are very few situations where you wouldn't want as comprehensive list of menu items as possible. We could also look at upping the maximum per_page for this controller specifically to a value above 100, as menus are usually already retrieved in one batch and there's less risk of custom meta and other situations that can make large collections of posts or other resources so expensive.

**Comment by mtias** [comment]
See also https://github.com/WordPress/gutenberg/pull/21019

**Comment by spacedmonkey** [comment]
As discussed in the slack conversion, it is unwise to allow a unlimited query like this. The REST API returns a header of `X-WP-TotalPages`. This can be used to easily do multiple fetches of the api to get all the results. See [this]( https://github.com/google/web-stories-wp/blob/d03bd026ae971bb195f309a9cc3bdef05e0ea747/assets/src/edit-story/app/api/apiProvider.js#L262-L283) code snippet as an example.

**Comment by mtias** [comment]
I don't disagree, just connecting the existing issues. :)

**Comment by kadamwhite** [comment]
@spacedmonkey It's also worth noting that (I believe this is still true) when making a request from the Gutenberg code using `apiFetch`, passing `-1` actually triggers a middleware within `apiFetch` which uses that header to recursively fetch using `per_page=100`. `-1` is still invalid within the API controller code itself.

Also cross-linking #18869 which is also related, and which raised this 10-item-limit issue originally.

**Comment by spacedmonkey** [comment]
There are now PRs on both repos

- https://github.com/WordPress/gutenberg/pull/21243
- https://github.com/WP-API/menus-endpoints/pull/46
