### ISSUE TITLE
WP logo in Gutenberg is rasterized on non-retina screens

### ISSUE THREAD

**Issue by davemart-in** [WordPress/gutenberg#21216]
**Describe the bug**
If you load Gutenberg on a non-retina screen, the WP logo looks like this:

![Image 2020-03-27 at 2 35 53 PM](https://user-images.githubusercontent.com/5634774/77790473-4a4a8300-703b-11ea-9421-ade59020b8ba.png)

Notice how the outer ring of the WP logo looks really messy?

**To reproduce**
1) Load Gutenberg on a non-retina screen.

**Expected behavior**
The logo should look crisp and clean.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by pablohoneyhoney** [comment]
We could go with the simplified version if that helps. I kind of prefer it to keep cleanness. 
https://wordpress.org/about/logos/

But it should work with either.

**Comment by ItsJonQ** [comment]
@pablohoneyhoney Great suggestion! That's the solution I went with :)

https://github.com/WordPress/gutenberg/pull/21217
