### ISSUE TITLE
Site Editor Template menu doesn't show saved Templates / Template Parts

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#21219]
The site editor Template menu in the top-right does not list Templates / Template Parts that are created and saved through Appearnce -> Templates / Template Parts.

![Screen Shot 2020-03-27 at 4 31 48 PM](https://user-images.githubusercontent.com/28742426/77798059-8f28e680-7048-11ea-92c5-0e000f33c77f.png)

Similarly, the "+ New" button only allows us to create a new template and does not give us the option to select an already existing one:

![Screen Shot 2020-03-27 at 4 33 47 PM](https://user-images.githubusercontent.com/28742426/77798166-bf708500-7048-11ea-9f36-b69131f6ec09.png)

Perhaps we should either:
* Show all templates Created/Saved through Appearance -> Templates to be shown in the Template menu by default.
* Allow the "+ New" component to display existing saved templates that match the query on the input field.

related - #21218

**Comment by mtias** [comment]
Closing as the menu is no longer relevant.
