### ISSUE TITLE
Copy All Content As Text - Feature Request

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#21233]
**Is your feature request related to a problem? Please describe.**
Hello, using the Copy All Content feature and pasting into my text editor it came along with all of the block markup which I then had to clean up before I had a usable document. It would be nice to provide an additional copy action which didn't carry over the block markup comments, maybe call it Copy All Content As Text. I understand the block markup is there so you can paste to another gutenberg page, but when pasting externally there's no desire for that markup and it becomes a burden to remove it from the pasted content.

**Describe the solution you'd like**
Introduce a Copy All Content As Text option which copies the page contents without the block markup.

**Describe alternatives you've considered**
Alternatively could just have the current Copy All Content only provide the text content, but I assume that would break the ability to copy from one block editor page to another.

**Comment by skorasaurus** [comment]
Hi, 

This is very similar to what's described at https://github.com/WordPress/gutenberg/issues/9018 and that issue has a lot of discussion about it so I'm closing this; please reopen if you have questions :)
