### ISSUE TITLE
Custom HTML Block is treating code as invalid when it contains an iframe with allowFullScreen or allowTransparency

### ISSUE THREAD

**Issue by jodamo5** [WordPress/gutenberg#21237]
**Bug Description**
Facebook's standard iframe embed code for Facebook videos includes the tags allowFullScreen and allowTransparency. However if we insert this code into a Custom HTML block, when we next edit the page (or refresh the page) the Custom HTML Block gives the warning "This block contains unexpected or invalid content". 

**To reproduce**
1. Edit a page and insert a Custom HTML Block. 
2. Paste this code into it (which is the exact code given by Facebook for embedding videos).
`<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fharvestcentrerotorua%2Fvideos%2F1106339649713337%2F&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>`

3. Save/Update the page.
4. Refresh the editing screen (F5).
5. Now you will see that the block shows the warning "This block contains unexpected or invalid content". 
6. If we remove `allowTransparency="true" allowFullScreen="true"`from the iframe code, update the page and then refresh the editing page, the block displays without any warnings/errors.

**Expected behavior**
The block should be treated as valid HTML even when `allowTransparency="true" allowFullScreen="true"` is used.  It should display just like it did before the page was refreshed. 

**Screenshots**
Screenshot attached showing the error. 

**Desktop:**
 - Windows 10
 - Browser Chrome
 - Version 80.0.3987.149

**Additional context**
Wordpress/Gutenberg version 5.3.2

![2020-03-29_1626_gutenberg_error](https://user-images.githubusercontent.com/7741749/77839545-2ec9ae80-71da-11ea-913e-8243d0460a48.png)

**Comment by talldan** [comment]
@jodamo5 When I tested in 5.3 those attributes become lowercase, but the iframe is also unusually wrapped in a `figure` element:
<img width="1167" alt="Screenshot 2020-03-31 at 3 34 29 pm" src="https://user-images.githubusercontent.com/677833/77999436-42555080-7365-11ea-9bfa-944d61f99e6a.png">

In the upcoming 5.4 the attributes are converted to lowercase, with no validation warning:
<img width="594" alt="Screenshot 2020-03-31 at 3 32 30 pm" src="https://user-images.githubusercontent.com/677833/77999242-ee4a6c00-7364-11ea-8e1e-ede42d7218e7.png">

FWIW, they should be lowercase, and from my understanding, this is how the browser corrects the markup. The attributes are also deprecated/not in the spec. It seems like Facebook could update the HTML they produce:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

I'll close the issue as the behavior you described doesn't seem present in WP5.4.
