### ISSUE TITLE
Set custom preview-options

### ISSUE THREAD

**Issue by Bowriverstudio** [WordPress/gutenberg#21235]
**Is your feature request related to a problem? Please describe.**

I'm sure this is part of a roadmap I use bootstrap which has different breakpoints than wordpress.

**Describe the solution you'd like**

I like away to modify the gutenberg/packages/edit-post/src/components/preview-options/index.js and add/modify MenuItem.

Instead of Desktop / Tablet / Mobile -> I'd like to use bootstraps

Extra large devices / Large devices / Medium devices / small devices: https://getbootstrap.com/docs/4.4/layout/overview/#responsive-breakpoints

**Comment by talldan** [comment]
@Bowriverstudio I think this was discussed on the original pull request - https://github.com/WordPress/gutenberg/pull/19082

I looks like an issue was never created, so this can become that issue.

Another use case I remember mentioned for being able to filter those menu options was adding preview options when using WordPress as the backend for a static site (like [Gatsby](https://www.gatsbyjs.com/guides/wordpress/)), where the URL for the site would typically be different to the one WordPress expects.

**Comment by skorasaurus** [comment]
Might be possible to work more on this with https://github.com/WordPress/gutenberg/pull/36119 ?

**Comment by annezazu** [comment]
Closing this out as it overlaps with this recently merged PR that introduces the ability to extend this preview panel: https://github.com/WordPress/gutenberg/pull/64644#top

> This extension point allows for greater flexibility in preview functionality, enabling plugin developers to integrate custom preview options seamlessly into the WordPress editor. It addresses the need for varied publishing flows and tools, such as:
> 
> Custom format previews (e.g., AMP, social media shares)
> Previewing content with different access restrictions or user roles
> Specialized preview modes (e.g., dark mode, email format)

This is expected to land in the WordPress 6.7 release so stay tuned. There's more work to do as well and that's being tracked here: https://github.com/WordPress/gutenberg/issues/65005
