### ISSUE TITLE
Replace Media URL in edit mode not updated immediately

### ISSUE THREAD

**Issue by isabellachen** [WordPress/gutenberg#21241]
**Describe the bug**
When replacing media, the display URL is updated, but the value in the input box is not. This only happens immediately after the media is replaced. Once the user clicks away from the image (thus closing the Block editing UI) and clicks into it again, the URL in the input is updated as expected.

![Mar-29-2020 16-55-32](https://user-images.githubusercontent.com/9280665/77852471-2f187880-71df-11ea-8f9d-124cbb84f2e6.gif)

**To reproduce**
1. Replace an image. In the gif the original image is from unsplash
2. Choose an image from the media library
3. See that the displayed URL has been updated
4. Click the edit button and realise the URL in input box is still the url of the previous image.

**Expected behavior**
Expect the URL to be the URL of the new image after replacement

**Desktop (please complete the following information):**
 - iOS
 - Chrome
 - Version 80.0

**Additional context**
- Gutenberg version 7.8.1

**Comment by talldan** [comment]
@isabellachen Thanks for reporting, I could also replicate the issue. I used the Insert From URL option to initially create the image block, which makes the error more easily observable. I'm not sure if this is also happening when initially creating the block using a media library image.

**Comment by paaljoachim** [comment]
Hi @isabellachen 

I am testing using WordPress 5.7 beta 1.
Theme: Twenty Twenty One.
With and without the Gutenberg plugin activated.
A local test site.
Chrome
OSX 10.15.7


1. Replace an image. In the gif the original image is from unsplash
2. Choose an image from the media library
3. See that the displayed URL has been updated
4. Click the edit button and realise the URL in input box is still the url of the previous image.

I added the Image block. Then added an image from the Media Library.
I noticed the URL displayed.
Clicked the Edit button. Pasted in this link: https://hometown-tourist.com/wp-content/uploads/2015/01/Manhattan-Neighborhood-Street-Scene.jpg
Noticed after clicking the Enter/Return Submit icon that the URL was automatically updated to the new URL.

I tested with the Gutenberg plugin version 9.9.1 activated and with it not activated.

Conclusion the issue has been fixed. I will close this issue. Please let us know if I am mistaken.
