### ISSUE TITLE
Add link to templates and template parts listing in site editor

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21246]
The same way we have a link to "manage reusable blocks" we should have links to the Templates and Template Parts post type listings. The place should likely not be the ellipsis menu (as reusable blocks) but within the template selector.

**Comment by noahtallen** [comment]
> The place should likely not be the ellipsis menu (as reusable blocks) but within the template selector

From what I can tell, we don't yet have a template selector, but we are iterating towards designs with that in #20477 and also the nav sidebar? (Would these links go in the nav sidebar then?)

**Comment by jameskoster** [comment]
It seems to me that there might be multiple links. One in the sidebar seems very likely as you mentioned. Another might exist in the [document settings](https://github.com/WordPress/gutenberg/issues/20877).

**Comment by shaunandrews** [comment]
Over in #20877 we're looking at adding a dropdown in the top bar that would allow you to switch a document's template. I think it could make sense to have a link here to manage all templates:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/191598/94189560-e7fefd80-fe78-11ea-8fa6-186eb2b7b282.png">

**Comment by mtias** [comment]
> here to manage all templates

I think I mentioned that elsewhere, but it'd be interesting to see if it can also mimic what we do on the quick inserter with "browse all".

**Comment by shaunandrews** [comment]
> I think I mentioned that elsewhere, but it'd be interesting to see if it can also mimic what we do on the quick inserter with "browse all".

Here's how that could look:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/191598/94302165-c87bd980-ff39-11ea-9773-9eacc7b093d5.png">

**Comment by jameskoster** [comment]
I'm not sure this format works on the "page details" popover. For the sake of consistency this button should link to "Browse all pages" in that context instead.

Edit page > Manage templates doesn't feel like a particularly common flow to me, so the pathway perhaps doesn't need to be as prominent. I wonder if the "Browse all templates" button could be part of the template switch/selection UI instead?

**Comment by vindl** [comment]
Given that we'll be able to browse and search all templates via navigation sidebar, and manage them via document settings dropdown, what value is this adding? Especially considering that it will be navigating away from site editor into another wp-admin page. The only thing that it allows is performing bulk actions on templates, but I don't think that should be high on the priority list right now.

**Comment by vindl** [comment]
Disregard my comment above. It was clarified by @mtias in https://github.com/WordPress/gutenberg/pull/26132#issuecomment-709531990 that this should open the navigation sidebar and not wp-admin listing, so everything is fine.

**Comment by mtias** [comment]
Yes, I believe the original phrasing was because we didn't have the W menu browsing list at all. Now it makes more sense to connect users there.

**Comment by noahtallen** [comment]
I think this is finished now with #26132. please re-open if there is more to do!

**Comment by mtias** [comment]
Thanks!
