### ISSUE TITLE
Reusable Blocks: Move E2E tests setup logic to a beforeAll()

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#21249]
The tests in `packages/e2e-tests/specs/editor/various/reusable-blocks.test.js` have an assumed order which is incorrect as tests should be able to run independently of one another.

From https://github.com/WordPress/gutenberg/pull/7947#discussion_r399341588:

> There should ideally be no concept of "above" as assuming tests to be run in particular order (or even that any others are run at all). I should be able to change this to [`it.only`](https://jestjs.io/docs/en/api#testonlyname-fn-timeout) and the test should be fine to run in isolation. Common behaviors should be established in lifecycle (`beforeEach` or `beforeAll`) or repeated in every test case.
>
> Note: I'm encountering this in implementing a new end-to-end test case for verifying the fix at #21205. Ideally I'd like to iterate on the test case with `it.only`, but at least as currently presented, there's no prior art for me to leverage commonly available reusable blocks to work with. For the purposes of my test, I might just copy the logic from "can be created" to create the reusable block. It could be straight-forward enough to refactor to its own function; not sure if I'll do that or end up just following the pattern here of reusing the block created in an earlier test case once finished.

**Comment by noisysocks** [comment]
As part of this refactor we can remove the `'can be inserted after refresh'` test added in https://github.com/WordPress/gutenberg/pull/20605 as it is redundant if the `'can be inserted'` test begins from a clean slate.

**Comment by youknowriad** [comment]
I did an extensive refactor to this test a few weeks ago and I believe it's now based on independent tests.
