### ISSUE TITLE
Don't save a reusable block until the user adds a name

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21259]
At the moment, when creating a reusable block, we save an entry on the post type immediately. We should require the user to enter a name first. Saving immediately also has the issue that if you start typing and the async update happens a brief moment later, it removes the text you typed.

**Comment by youknowriad** [comment]
It seems like this might be a duplicate of #12940

**Comment by youknowriad** [comment]
closing as duplicate
