### ISSUE TITLE
Selection state can get stuck in navigation block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21253]
_Only in full-site editing_

![image](https://user-images.githubusercontent.com/548849/77904258-8b81a380-7284-11ea-8ac9-b44532a9afb2.png)

**Comment by carolinan** [comment]
I have not been able to reproduce this in the site editor, with mouse or keyboard (Chrome, Windows 10, TT1 Blocks).

**Comment by mtias** [comment]
Closing, this is such a poor bug report :D
