### ISSUE TITLE
Highlighting all text from bottom does not always have toolbar control applied

### ISSUE THREAD

**Issue by edwinho89** [WordPress/gutenberg#21262]
**Describe the bug**

When highlighting all text in a block from bottom, sometimes the first few lines in the block aren't being properly selected, and applying changes like bold, italic skips these few lines.

**To reproduce**
1. Create a new post or page
2. Create a new paragraph block of texts
3. Highlight all text of the block using your mouse, starting by highlighting from bottom to top
4. Apply text changes like **bold** or *italic*

**Expected behavior**

Text changes would apply on all texts.

**Screenshots**

Attempted multiple ways to highlight texts in a block with a mouse:
* Highlight all texts by triple click
* Highlight all texts from top to bottom
* Highlight all texts from bottom to top

![video  link 1](https://cldup.com/WeoC953vAw.mov)
Video link 1 : https://cloudup.com/claa1M3g2Py

Attempted second time to be sure.

![video link 2](https://cldup.com/m4A0bZeBC3.mov)
Video link 2: https://cloudup.com/cKfLkKhevGF

**Additional context**

* Results are inconsistent - sometimes it works normally as expected

**Comment by talldan** [comment]
Thanks for reporting @edwinho89, I was able to reproduce the issue.

**Comment by ntsekouras** [comment]
Hey @talldan. How did you reproduce this issue? I'm trying with no luck..

**Comment by noisysocks** [comment]
I wasn't able to reproduce this either. What browser are you using?

**Comment by talldan** [comment]
This seems to work ok now. Closing the issue.
