### ISSUE TITLE
URLPopover : filter the default link target based on URL

### ISSUE THREAD

**Issue by OksanaRomaniv** [WordPress/gutenberg#21264]
Is there a way to set/filter the default value of "Open in New Tab" setting for inline links formatting? For example, set all external links to open in a new tab automatically?

Thanks!

**Comment by talldan** [comment]
@OksanaRomaniv Not at present. I think the only way to handle that would be to unregister the current link format and register a custom one, but granted that's not a trivial task. The current link format code is here, so it'd be a matter of replicating this code:
https://github.com/WordPress/gutenberg/tree/master/packages/format-library/src/link

**Comment by OksanaRomaniv** [comment]
@talldan thank you for the reply. Are there any plans to add a filter/hook for this setting in the future?

**Comment by talldan** [comment]
There's an issue here that I think is along similar lines - https://github.com/WordPress/gutenberg/issues/17556

This PR also attempted to add the feature initially, but never quite progressed to the point where it could be merged:
https://github.com/WordPress/gutenberg/pull/13190
