### ISSUE TITLE
Editor settings not correct in `block.registerBlockType` filter

### ISSUE THREAD

**Issue by willrowe** [WordPress/gutenberg#21267]
**Describe the bug**
The correct editor settings are not available when accessed in the `blocks.registerBlockType` filter.

**To reproduce**
1. Create the file `test.js` in the currently active theme directory. Copy and past the following into it:
```js
(function (wp) {
        wp.hooks.addFilter(
        'blocks.registerBlockType',
        'test-editor-settings',
        function (settings, name) {
            console.log(wp.data.select('core/editor').getEditorSettings().testValue);

            return settings;
        }
    );
})(window.wp);
```
2. Add the following to the `functions.php` file for the currently active theme:
```php
add_action(
    'init',
    function () {
        wp_enqueue_script(
            'custom-theme-block-editor',
            get_stylesheet_directory_uri() . '/test.js',
            [
                'wp-blocks',
            ],
            wp_get_theme()->get('Version')
        );
    },
    30
);

add_filter(
    'block_editor_settings',
    function ($editor_settings, $post) {
        $editor_settings['testValue'] = 'test';

        return $editor_settings;
    },
    10,
    2
);
```
3. Go to the WordPress dashboard and edit or create a new page.
4. Open up the DevTools and look at the console.

**Expected behavior**
- The console should display a number of `test`. Instead it displays `undefined`.
- This is also affecting customizations made to the colors and font sizes that are loaded into the editor settings. They are set to their default values.
- If `wp.data.select('core/editor').getEditorSettings().testValue` is called after the page is loaded using `wp.DomReady()` it displays the correct value.
- It seems that the `blocks.registerBlockType` filter is being triggered before the editor settings have been loaded.
- Either `blocks.registerBlockType` needs to be triggered later or the editor settings need to be immediately loaded with the correct values instead of loading them after they can be referenced with the wrong, default values.

**Desktop:**
 - OS: macOS 10.15.4
 - Browser: Chrome
 - Version: 80.0.3987.149

**Additional context**
- This is happening with the bundled Gutenberg editor in WordPress 5.3.2, the plugin is not installed.

**Comment by youknowriad** [comment]
The editor settings is `core/editor` property, which means you need to add `wp-editor` as a dependency of your script to run after that.

That said, that won't be enough because these settings are changed by the `editPost` script when it's initialized and can change over time, so if you want the right value you need to subscribe to the data changes and check if the value changed `wp.data.subscribe`

I hope this helps.

**Comment by willrowe** [comment]
I guess the main thing I am wondering is why the settings are initialized with values which are not correct and then overwritten with the correct values so late in the process.

> if you want the right value you need to subscribe to the data changes and check if the value changed wp.data.subscribe
At that point the block types would have already been registered. I need access to the settings in order to affect how the blocks are registered.
Specifically, I am trying to adjust the allowed parent blocks, which as far as I know can only be changed in the `block.registerBlockType` filter.

**Comment by youknowriad** [comment]
> At that point the block types would have already been registered. I need access to the settings in order to affect how the blocks are registered.

Well that's not possible at registration time conceptually, because registering a block, doesn't mean an editor exists, so it doesn't necessarily mean there are settings.

How do you want to change the behavior of the blocks, what modifications do you want to achieve?

**Comment by willrowe** [comment]
> Well that's not possible at registration time conceptually, because registering a block, doesn't mean an editor exists, so it doesn't necessarily mean there are settings.

Can you explain more about this? I would assume that if you are registering a block type it would be for use in the editor. Can block types in this context be used independently of the editor?


> How do you want to change the behavior of the blocks, what modifications do you want to achieve?

I am trying to control where a block can be inserted, based on settings from the backend. For example, limiting a custom block to only be allowed inside a `group` block.
The `parent` setting which can be altered in the `block.registerBlockType` filter is specifically editor behavior, which is why I was expecting the editor settings to be available.

**Comment by youknowriad** [comment]
> Can block types in this context be used independently of the editor?

Yes, they can, the block editor package is a generic package that can be used to power any alternative editors. I saw for instance some people using it for comments. The Gutenberg project itself is using it for the experimental widgets screen where we should one editor per widget area, and the experimental edit site screens. 

> I am trying to control where a block can be inserted, based on settings from the backend. For example, limiting a custom block to only be allowed inside a group block.

Why are you using `wp.data.select('core/editor').getEditorSettings()` to retrieve these backend settings? Shouldn't you use your own store, or just a simple localized variable?

**Comment by willrowe** [comment]
> Yes, they can, the block editor package is a generic package that can be used to power any alternative editors. I saw for instance some people using it for comments. The Gutenberg project itself is using it for the experimental widgets screen where we should one editor per widget area, and the experimental edit site screens.

That's really interesting. Thank you for the information.

> Why are you using wp.data.select('core/editor').getEditorSettings() to retrieve these backend settings? Shouldn't you use your own store, or just a simple localized variable?

I originally used it since it was accessible alongside the color palette and font size settings and did not require any additional code to load them in, just the `block_editor_settings` filter. I see what you are saying about loading it in earlier manually, that should hopefully do the trick.

The only thing I am still not clear on is why the editor settings are available with incorrect values. If the editor has not been loaded yet and the correct settings have not been loaded either, should it throw an error or not be available at all. It took me a bit to debug why it was not working before figuring out that the settings had not actually been loaded yet, event though it appeared that they had.

Thanks for all your help @youknowriad!
