### ISSUE TITLE
Locked block: visualise instead of showing HTML

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2126]
I noticed that, if a block is no longer registered, but there are blocks of this type in the content, the HTML is shown. This issue strange as it's now a freeform block internally.

Another issue is that the content now saves as a freeform block. I would expect that, since it is locked, it would keep the block type and preserve everything.

**Comment by mtias** [comment]
I mentioned leaving an unrecognized block as unrecognized instead of converting to freeform. It may be as simple as not adding the freeform comment at all for freeform blocks (it is the fallback for anything unrecognized, which would include unrecognized blocks as well as just unrecognized markup).
