### ISSUE TITLE
Update Tumblr logo in social link options

### ISSUE THREAD

**Issue by fetherston** [WordPress/gutenberg#21270]
**Describe the bug**
Hi Gutenberg fam 🙌 full disclosure I work at Tumblr. The logo in the social links is our old logo. Can we update it?

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/social-link/variations.js

The correct logo is at tumblr.com/logo 

**To reproduce**
1. Turn on Tumblr as a sharing option
1. View Tumblr logo
1. It's the Tumblr logo from 4-5 years ago

**Expected behavior**
The logo should be the new logo! 

**Screenshots**
![image](https://user-images.githubusercontent.com/7718971/77940150-41012680-7286-11ea-9087-203dba65b5fe.png)

**Desktop (please complete the following information):**
 - Any and all!

**Smartphone (please complete the following information):**
 - All of um!

**Additional context**
- Thanks for the help keep our branding up to date folks!

**Comment by mcsf** [comment]
Hi! The two places in which to update the logo are:

* Client-side: https://github.com/WordPress/gutenberg/blob/c827188abca89c8d831202db75acfeb5107ecb0e/packages/block-library/src/social-link/icons/tumblr.js#L6-L10
* Server-side: https://github.com/WordPress/gutenberg/blob/c827188abca89c8d831202db75acfeb5107ecb0e/packages/block-library/src/social-link/index.php#L219-L222

As you see, an SVG file is expected. Can you contribute with one? Thanks!

**Comment by fetherston** [comment]
Oops sorry, forgot to leave this link: https://www.tumblr.com/logo. SVGs are available in that download.
