### ISSUE TITLE
5.4 - Buttons in Buttons block improperly aligned with margin auto applied.

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#21272]
**Describe the bug**
A margin is applied to buttons within the buttons block here:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/buttons/style.scss#L3

The result is improperly aligned buttons, as opposed to the old singular button block, which is properly aligned.

**To reproduce**
1. On WP 5.3, add a button block and set it to be right-aligned. Publish the post.
2. On WP 5.3.3-alpha-47419 add 3 `Buttons` blocks, aligning them left, centered, and right.
3. Update and view the post.
4. See the buttons are not aligned properly.

This appears to be caused by the margin, as removing it fixed the alignment problems. 

## With margin
<img width="1792" alt="Screen Shot 2020-03-30 at 5 04 44 PM" src="https://user-images.githubusercontent.com/7538525/77962357-71a68780-72a9-11ea-85f9-c0a4911aaabd.png">

## Without margin
<img width="1792" alt="Screen Shot 2020-03-30 at 5 01 12 PM" src="https://user-images.githubusercontent.com/7538525/77962347-6eab9700-72a9-11ea-9d95-024269d9f14c.png">

**Expected behavior**
Buttons should be aligned properly by default, with no extra margin.

**Comment by youknowriad** [comment]
This looks like the same issue as the one raised here #21293 
I'm going to close as a duplicate. I believe that margin is only needed when there's multiple buttons.
