### ISSUE TITLE
This Block contains unexpected or invalid content - HTML Block

### ISSUE THREAD

**Issue by icc365** [WordPress/gutenberg#21271]
**Describe the bug**
Using the HTML block, I paste in a table structure I have to do outside of the block first. It saves, and viewable on front-end. Later if I go to edit the block, I always get the "This block contains unexpected or invalid content" message and I have to convert to HTML (which is odd considering it's an HTML block).

**To reproduce**
To reproduce, I may have to provide you with the source code of my table structure. 

**Expected behavior**
Regardless of what kind of table structure I paste into the HTML block, it should stay as an HTML block without having to always re-convert it to HTML.

**Screenshots**
I've attached a screenshot showing the block after opening the page in the editor to edit that block.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 80.0.3987.149

**Additional context**
- I've noticed over time, I've gotten that error message, but this time decided to post this issue. It seems as though the HTML block only likes the absolute basics
![invalid-block-message](https://user-images.githubusercontent.com/54302511/77961770-372ff100-728f-11ea-9066-72df0239e9d6.jpg)
 of HTML. In this situation, my table contains a variety of elements:  `colgroup`, `classes`, `thead`, `<i>` tags, spans, etc.

I should also mention that clicking on Resolve, does not help and I have to always hit the Convert to HTML button. I also notice that when I open the page in the editor, that HTML block is being rendered (and it shouldn't be) as you can see in the screenshot.

**Comment by talldan** [comment]
@icc365 It'd be great if you could share an example of the HTML you're using in the HTML block.

**Comment by icc365** [comment]
I just attempted a new HTML block and re-entered the source code for my table. I updated my page, closed it, then reopened it and sure enough, it was happening to the block. However, I clicked Attempt Block Recovery and it seemed to have worked. 

I will still post a text file here with the source code of my table to see if it happens to you.
[table-source-code.txt](https://github.com/WordPress/gutenberg/files/4406810/table-source-code.txt)

**Comment by talldan** [comment]
There's some invalid HTML in the snippet, the `colgroup` has to appear before `thead` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup). So that might be what's causing the issues. The block is sometimes a little fussy about the HTML being correct, and Attempt Block Recovery can resolve those issues.

I think there's a separate issue about making the Attempt Block Recovery option more prominent, as that's usually the most successful option!

I'll close the issue now that it seems to be resolved.
