### ISSUE TITLE
Add unit tests for every function in edit-navigation/store.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21285]
**Is your feature request related to a problem? Please describe.**
#21036 implemented the Navigation screen. This screen allows the creation of nav menus (in their current form in WordPress) using the new navigation block.

It achieves this using redux actions, reducers, and resolvers to convert the block attributes to menu properties that are saved via the REST API. This conversion would ideally be unit tested.

**Comment by adamziel** [comment]
Should be easier after the refactoring from https://github.com/WordPress/gutenberg/pull/22825 - we now have small atomic units responsible for specific tasks only

**Comment by adamziel** [comment]
@noisysocks @draganescu does it make sense to address it now? Or would it be better to wait until it's clearer whether or not the navigation management screen is going to stick?

**Comment by draganescu** [comment]
Yes, let's see how the screen's implementation evolves in light of the talks to use a Block Editor.

**Comment by draganescu** [comment]
This is blocked due to the current rapid evolution of the navigation screen.

**Comment by adamziel** [comment]
I updated the issue to talk about the data layer and not the useNavigationBlocks hook.
