### ISSUE TITLE
Allow creation/deletion of Navigation Menus on the Navigation screen.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21281]
**Is your feature request related to a problem? Please describe.**
#21036 implemented the experimental nav screen. Currently a user can select an existing menu created through the existing menu screen, but cannot create or delete menus.

This should be possible from the screen.

**Describe the solution you'd like**
- [ ] A button for creating new menus.
- [x] A button for deleting menus (with a confirmation stage).

**Comment by draganescu** [comment]
Following  #21379 we have a button to delete menus.
