### ISSUE TITLE
env: Support some option for WP-CLI shell command

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21301]
**Is your feature request related to a problem? Please describe.**

In order to test the outputs of various WordPress functions, I have historically found a lot of use for WP-CLI's shell command:

https://developer.wordpress.org/cli/commands/shell/

Specific example: In reviewing the pull request at #21007, I would like to test the outputs of [the `remove_accents` function](https://developer.wordpress.org/reference/functions/remove_accents/).

`@wordpress/env` _does_ support WP-ClI, and for most commands you can use it in the form of something like (within this project):

```
wp-env run cli post get 121
```

However, if you run the equivalent for `wp shell`, the command spins and hangs forever:

```
$ wp-env run cli shell

⠏ Running `shell` in 'cli'.
```

Presumably the issue is that this script is a prompt, and is awaiting some input which will never come.

In the past, I've tended to work around this by running `docker-compose` directly. This became harder when the project's root `docker-compose.yml` was moved into `packages/env`, and recently became impossible as part of one of the recent revisions to this package.

**Describe the solution you'd like**

One of:

1. `wp-env` should support interactive inputs
2. I should be able to have some option for manual override to use Docker commands directly, not through these proxied Node scripts

**Describe alternatives you've considered**

I believe `wp shell` can handle piped input, so if there were some way to pipe input through `wp-env`, that would work just as well.

```
$ echo "remove_accents('ȘșȚț');" | wp shell
=> string(4) "SsTt"
```

Unfortunately, the same does not work when running through `wp-env`, at least using the project's root `npm run wp-env`:

```
$ echo "remove_accents('ȘșȚț');" | npm run wp-env run cli shell
```

**Comment by noahtallen** [comment]
It sound like there are a lot of good ideas here:
- add support for interactive commands
- expose docker compose commands directly
- better support for piping input in and out of wp-env

**Comment by pablinos** [comment]
> recently became impossible as part of one of the recent revisions to this package

What was that addition @aduth? I hit this problem recently too. I managed to go the `docker-compose` command route by using:

```
docker-compose -f $HOME/.wp-env/`md5 -qs $PWD/.wp-env.json`/docker-compose.yml run --rm cli wp shell
```

Definitely a hacky solution. It got me wondering whether we could have a command that allowed us to run arbitrary `docker-compose` commands.

It would also be really useful to be able to override the location of the environment's installation folder. I'd rather have it as a sub-folder of the project and add it to `.gitignore`, this would help with locating `docker-compose.yml`, but would also help with my editor's language server setup as the definitions would all be in one place. 

Currently, if you have more than one environment and want to do something like put some debug into a core file, it's tricky to know which one to edit. I realise these are probably unique problems to my workflow!

**Comment by aduth** [comment]
>What was that addition @aduth?

I don't know that there's any one specific revision I could point to, just that iterations in `@wordpress/env` weren't optimized toward direct usage of Docker, so in the course of its development I eventually lost access to my workflow solution here 🤷 

Thanks for sharing that command. Even if it's a hack, it's nice to have an option next time I want a shell 👍

**Comment by pablinos** [comment]
> Even if it's a hack, it's nice to have an option next time I want a shell 👍

Yes, I find a shell to be kind of essential these days. I'll have a bit more of a play when I get some time, and see if I can get something less hacky working

**Comment by noahtallen** [comment]
> see if I can get something less hacky working

feel free to contribute it to wp-env! :) I think this is where we'd need to start looking. I _think_ there is a docker-compose option for interactive mode?

https://github.com/WordPress/gutenberg/blob/2102f7ab34c8697a8273d38b3dfde9e4229b3908/packages/env/lib/commands/run.js#L27-L31
