### ISSUE TITLE
Option for Gallery block to choose a target image size when using target: media

### ISSUE THREAD

**Issue by huubl** [WordPress/gutenberg#21302]
**Describe the solution you'd like**
I'm missing an option to choose an image size when linking to media. I like to use large or a custom image size instead of the full image.

<figure>
  <a href="../image-url[chosen-media-size].jpg" data-gallery-id="1">
    <img ...>
   </a>
</figure>

**Comment by tdechangy** [comment]
Nice idea, and should be set in default settings to allow big images on server while using smaller once where desired.
Image sizes is a topic that Wordpress don't seem to take seriously and it's a pity. where are all the settings we should have in a serious CMS ?

**Comment by skorasaurus** [comment]
This has been possible in the gallery block by modifying the media file option in the block. 
![Selection_088](https://user-images.githubusercontent.com/955351/132905924-414c0bff-2a2e-4f89-84d3-7e2a4c6dd2c0.jpg)


Please reopen to clarify or I'm misunderstanding.
