### ISSUE TITLE
Improve Notices CSS layout with and without __unstableHTML

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#21316]
Splitting this out from https://github.com/WordPress/gutenberg/pull/20578

The change to the notice action button (`float: right` added) doesn't seem ideal to me. 

1
Large screen with a notice long text: position and alignments don't look so ideal:

<img width="1296" alt="Screenshot 2020-04-01 at 10 34 27" src="https://user-images.githubusercontent.com/1682452/78116645-eb9f5380-7404-11ea-96bf-db6775b298d5.png">

2
On a custom notice, it is possible to reset the default CSS classes and set custom CSS classes on the action button. See `noDefaultClasses`. By using `className` it is possible, for example, to add an `is-link` class to make the button look like a link. In this case, the layout doesn't look so ideal as well:

<img width="1299" alt="Screenshot 2020-04-01 at 10 34 30" src="https://user-images.githubusercontent.com/1682452/78116905-42a52880-7405-11ea-94ac-fa085ad170e1.png">

3
By using `__unstableHTML`, it is possible to use HTML for the notice text. However, `__unstableHTML` renders an additional `<div>` element via the `RawHTML` component. This additional div breaks the flex layout:

<img width="1298" alt="Screenshot 2020-04-01 at 10 35 32" src="https://user-images.githubusercontent.com/1682452/78117148-91eb5900-7405-11ea-93eb-cfc51abf1f34.png">

4
Pre-existing issue: it seems to me there's something that doesn't work as expected in the `RawHTML` component. To my understanding, the wrapper div should be "stripped out by the serializer unless there are non-children props passed". However, seems to me it isn't stripped out.

https://github.com/WordPress/gutenberg/blob/c5fab6d23ff7478096942412bc20dc30654ca82e/packages/element/src/raw-html.js#L6-L25

**Comment by jasmussen** [comment]
I have pushed a fix to the floated button. Sorry about that. 

Regarding unstableHTML and even rawHTML, from a design and user interface point of view, I feel we should not optimize towards using those in notices at all. One of the biggest benefits of using the notice API is to help ensure that even 3rd party plugins have an accessible and consistent display of notices.

**Comment by afercia** [comment]
Regarding unstableHTML I do agree. However, at the moment is not even possible to have a simple link or a bold text within a notice without using unstableHTML.

It's not even possible to pass a custom component, because any passed content is cast to a string. Right now there's really no alternative to unstableHTML, which makes the "notice API" a bit limited for practical usage.
