### ISSUE TITLE
Moving button between columns

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#21319]
**Describe the bug**
It seem i can't move a button block between block columns.
Image and paragraphs works fine

Everything up date, using gutenberg plugin. With chrome.

**Comment by talldan** [comment]
@davouid Yes, this is a bit trickier now. The Button block has been changed to Buttons in WP5.4. If you have a Buttons block in a column, you need to make sure you select and drag the parent Buttons block, then it should work.
