### ISSUE TITLE
Add 'Automatically add new pages' feature to Nav Menus page.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21311]
**Description**
#19170 created an experimental page for using the nav block to created existing WordPress menus.

The old menus page has a feature for automatically adding new pages to the menu. The new page should also have this for feature parity.

**Comment by draganescu** [comment]
The current menus store this as a string of menu ids in an option named `nav_menu_options`. The REST API does not have an endpoint to manage options. According to a [brief Slack Q&A](https://wordpress.slack.com/archives/C02RQC26G/p1590506589022700) we should manage this as part of the menus endpoint, in `WP_REST_Menus_Controller`.
