### ISSUE TITLE
(Gutenberg) with Custom BuIld Website 

### ISSUE THREAD

**Issue by ixlosbek** [WordPress/gutenberg#21325]
Can we use Gutenberg with html or Custom build Website.Becouse i Need blog publisher for my Web.But i am not using a WordPress For But i Have Downloaded (Gutenberg) Clone  From GitHub.

**Comment by youknowriad** [comment]
You can use the block editor to build custom editors outside of WordPress if needed. The playground https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default should be a good indication about how to do so

https://github.com/WordPress/gutenberg/blob/master/storybook/stories/playground/index.js
