### ISSUE TITLE
Layout problem with text size control

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#21327]
**Describe the bug**
As reported by @Zebedeu in https://core.trac.wordpress.org/ticket/49752
The layout of the "Text size" control for the "Text block" breaks if the labels are too long.
See a couple of screenshots in the referred Trac ticket.

**To reproduce**
1. Use virtually any language version of WordPress 5.4, except English
2. Select some text in a text block and look at the block level controls for text size. There's great probability that the "Reset" button will be partially located outside the boundaries of its container.

**Additional context**
- This is visible in plain WordPress 5.4 with German translation, for instance.

**Comment by enriquesanchez** [comment]
I can reproduce it too (v 7.7.2).

If UI is set to Spanish:

<img width="280" alt="Screen Shot 2020-04-01 at 11 37 49" src="https://user-images.githubusercontent.com/3276087/78169582-dc250800-740e-11ea-9cd3-debcd5bc8867.png">
