### ISSUE TITLE
WordPress Dashboard to use more specific styling

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#21331]
I don't know if this classifies as a feature or a bug, but now that Gutenberg is mainstream and we are trying to make the front end look like the back end, WordPress should make sure to use a bit more specific selectors in the admin area so that our code for our theme and blocks should not need to undo styling.

For instance the class ".card" is used somehow on the back end of WordPress. 
There is no specificity at all.

This messes with our blocks that we create, for example using the class ".my-block .card"
I have to style my element AND make more styling to undo everything done by WordPress because there was no specificity for their .card

There are a few classes I have run into with his here and there...

**Comment by talldan** [comment]
@saltnpixels Gutenberg classnames are prefixed with the name of the package they come from, so I think your concern is already addressed in this codebase. For example, you can see that the Card component has the classname `components-card`:
https://github.com/WordPress/gutenberg/blob/db0327dbc95184c88816fd27bad42433c2222b84/packages/components/src/card/index.js#L35

It looks like there's a `.card` style in Core WordPress, so this is unrelated to Gutenberg. That style has been around for over 5 years and predates Gutenberg:
https://github.com/WordPress/wordpress-develop/commit/df2c74e87841d7df974b909072c4f6b50ac08b90

I'd recommend reaching out with a core trac ticket for WordPress core issues:
https://core.trac.wordpress.org/
