### ISSUE TITLE
Social net icons – possibility to add custom image for icon

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#21330]
**Is your feature request related to a problem? Please describe.**
There are many social nets that are not represented in new social icons block, that appeared in 5.4 WordPress versions. Discord, for example.

**Describe the solution you'd like**
It would be convenient if the user could add their own image to the custom social net icon right in Gutenberg and use it sitewide.

**Comment by mtias** [comment]
There are plans to do that in #19041. Specific suggestions that would have wide appeal can also be suggested for including.

**Comment by NekoJonez** [comment]
I would love a feature like this.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/39868  . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
