### ISSUE TITLE
Make Navigation screen responsive for mobile and tablet viewports

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#21337]
https://github.com/WordPress/gutenberg/pull/21036 added a new experimental Navigation screen and https://github.com/WordPress/gutenberg/pull/21314 improved its UI.

We will need to make this new screen adapt to mobile and tablet viewports. 

![](https://user-images.githubusercontent.com/677833/78117773-a6951480-7438-11ea-95a5-c03fe77ea9e7.png)

**Comment by tellthemachines** [comment]
Closing as both #21414 and #21471 have been merged.
