### ISSUE TITLE
Env: Remove "request" package dependency

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#21336]
`@wordpress/env` specifies `request` as a dependency, but this package is deprecated:

https://www.npmjs.com/package/request
https://github.com/request/request/issues/3142

Which isn't necessarily to say that a deprecation is bad, but we can't expect any future maintenance (which could become problematic for security issues and the like). Another option like [`got`](https://www.npmjs.com/package/got), [`bent`](https://github.com/mikeal/bent) (from the author of `request`), or just straight [`https`](https://nodejs.org/api/https.html) may be a more reliable long-term dependency. For the specific needs of progress events, the first of these alternatives does have the most compatible API for how we're using it here, though a combination of an `https` response `Content-Length` header plus an incrementing value in a [stream iteration](https://github.com/WordPress/gutenberg/blob/307e1fb2fc4955f77af8089ab380d457c71a20c2/packages/url/scripts/download-wpt-data.js#L47-L51) may suffice as well.

_Originally posted by @aduth in https://github.com/WordPress/gutenberg/pull/20426_

**Comment by jessie-ross** [comment]
Hi @noisysocks , I have taken a look at this issue.

`got` seems to be the best option out of the above choices: 
- For this use-case `bent` only provides protocol checking on top of `http`/`https`
- `bent` and `http` don't provide what you would expect from an http client, e.g. redirects,  caching and cookies. These are useful for developer tooling.
- `got` is well maintained with a good dev community.
- `got` fits in quite nice here.

Another option is `node-fetch` and using the `progress-stream` package for the progress event:
- It is more popular.
- It doesn't handle cookies.

I'll shortly attach a PR for the `got` version.
