### ISSUE TITLE
add_action( 'wp_trash_post') not work with Gutenberg?

### ISSUE THREAD

**Issue by yarovikov** [WordPress/gutenberg#21347]
Hi all!
I use custom function for delete from custom data table.
When a use Trash button on posts list page it's ok. When I delete post from edit post page (block editor) not work.

```
class RetreatsFilter {
		
	function __construct() {
		add_action( 'wp_trash_post', array( $this, 'my_delete_post' ) );
	}
	
	public static function my_delete_post( $post_id ) {
		global $wpdb;			
		$table_name = $wpdb->prefix . "acf_data";
		$wpdb->delete( $table_name, array( 'id' => $post_id ) );			
	}	

}
```

How can fix it? Thanks!

**Comment by Soean** [comment]
Gutenberg uses the REST API, so the hook is `rest_delete_post` for the post type post.

See: https://developer.wordpress.org/reference/hooks/rest_delete_this-post_type/

**Comment by yarovikov** [comment]
@Soean thanks! it's work but i have error 500 
http://yarovikov.local:8888/one-retreat/wp-json/wp/v2/retreats/269?_locale=user

`add_action( 'rest_delete_retreats', array( $this, 'my_rest_delete_post' ) );`

```
public static function my_rest_delete_post( $post, $response, $request ) { 
	global $wpdb;			
	$table_name = $wpdb->prefix . "acf_data";
	$wpdb->delete( $table_name, array( 'id' => $post_id->ID ) );
}
```

**Comment by Soean** [comment]
Use `$post->ID` instead of `$post_id->ID`.

**Comment by yarovikov** [comment]
@Soean same problem 😥

**Comment by Soean** [comment]
I can't test it local at the moment. Maybe you have to use `'ID'`(uppercase) as array key?

**Comment by yarovikov** [comment]
@Soean debug log

Uncaught ArgumentCountError: Too few arguments to function RetreatsFilter::my_rest_delete_post(), 1 passed in /Users/yarovikov/Sites/one-retreat/wp-includes/class-wp-hook.php on line 289 and exactly 3 expected in /Users/yarovikov/Sites/one-retreat/wp-content/themes/one-retreat/inc/class-rereats-filter.php:112

🤷‍♂️

**Comment by Soean** [comment]
Remove the second and third parameter of you function: (`$response` and `$request`).

Or pass the parameters:
`add_action( 'rest_delete_retreats', array( $this, 'my_rest_delete_post' ), 10, 3 );`

**Comment by yarovikov** [comment]
@Soean ok, but it not delete from table

<img width="547" alt="Screenshot 2020-04-02 at 21 46 50" src="https://user-images.githubusercontent.com/30932012/78289915-8db95b80-752b-11ea-9ad2-a963f98de199.png">

**Comment by Soean** [comment]
This problem is about the ACF database and not Gutenberg related. The GitHub issues are not for support, so I am closing this.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/. Or ask the ACF table plugin support.

**Comment by yarovikov** [comment]
@yarovikov why i have not this problem with classic editor?
