### ISSUE TITLE
Ability to change the default social icons

### ISSUE THREAD

**Issue by woorise** [WordPress/gutenberg#21348]
I searched in the documentation but I didn't find anything relevant.

Is there any way to change the default set of social icons for the Social Icons block?

**Comment by mkaz** [comment]
No, there is not a way to change the social icons, yet. 

We have a ticket open at #19041 to discuss how the icon storage might look to make it extensible, the idea is to allow being able to add their own custom icons.

By default set, I assume you mean what shows when initially inserting the block. This might be a good filter to add before solving the storage. Likewise, it might be good to add a filter to limit which icons are shown to simplify the list.

**Comment by jasmussen** [comment]
In a previous iteration of the social links block, we pre-inserted a few blocks that were unconfigured, allowing you to click them to add your profiles. But we can't know your profiles, and by the blocks being preinserted we found users were confused expecting them to work, so we replaced it with an empty setup state instead, forcing you to insert social links one by one.

In that vein, it isn't really possible to change the default set anymore. I'm closing for that reason, but please do comment in case there's a piece of the puzzle I'm missing!
