### ISSUE TITLE
Add save/error notifications to Navigation Menu page

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21344]
## Description
Currently when saving a menu on the new Nav Menu page, there's no indication anything happened. Ideally:

- The Save button would be disabled until changes that can be saved have been made
- A Snackbar notice would appear when save is successful
- A Notice notice would appear when a save error happens.

I had a look into this initially while working on #21342, I tried creating a react hook that used a store subscription, but it's not trivial to implement so I avoided adding more complexity to that PR.

Part of the difficulty come from the way MenuItems are saved one-by-one:
https://github.com/WordPress/gutenberg/blob/4bbfbc13603d28fcc45368c529954164bf8581de/packages/edit-navigation/src/components/menu-editor/use-navigation-blocks.js#L60-L83

A subscription wouldn't know which one of these indicates the final saving of the menu and when to show a snackbar notice.

It might be an idea to move this code to an action generator, like `savePost` in the block editor, and use the same approach for triggering notices:
https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/editor/src/store/actions.js#L221-L296

**Comment by adamziel** [comment]
What about a partial success? As in saving a menu item initiates 10 requests and only 8 of them succeeds? Even with the most crafty notification this would still seem broken. I think we need to take a step back here and start with an atomic save operation with a binary success / failure result.

**Comment by talldan** [comment]
Very true @adamziel. The discussion here about the best way to save menus also ties into what's being discussed on https://github.com/WordPress/gutenberg/issues/21964.

With partial success, we could consider showing errors on the menu items, but blocks don't really have a generic system for showing errors.

I agree a request for saving would be nice.

**Comment by adamziel** [comment]
Let's move the discussion there then :-)

**Comment by adamziel** [comment]
Related PR from Andrei (Adds snackbar notification: https://github.com/WordPress/gutenberg/pull/21557)

**Comment by adamziel** [comment]
This is fixed
