### ISSUE TITLE
Unable to tick the checkbox of a template or template part to save (Full site editing - Site Editor page)

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#21355]
**Describe the bug**
In Site Editor (beta) page, after editing the site, and clicking on the "Update Design" button, it is impossible to check on of the checkboxes of templates or templates parts in order to save the changes made.

**To reproduce**
On a fresh WordPress install,
1. Install and activate the Gutenberg Plugin
2. Go to Gutenberg > Experiments, and enable "Full site editing" and "Full site editing demo templates" option.
3. Go to Gutenberg > Site Editor (beta) and made some changes to the site in the block editor.
4. Click on "Update Design" button and try to check one of the checkboxes.

**Expected behavior**
We should be able to select one of the checkboxes (Template: Front Page and Template Part: Header) to save them.

**Screencast**
https://res.cloudinary.com/segbedji/video/upload/v1585841865/Gutenberg/Site_Editor_beta_Gutenberg_WordPress_-_Firefox_Developer_Edition_02_04_2020_16_30_28_v4whxh.mp4

**Desktop**
 - OS: Windows 10 Professional 1803
 - Browser: Firefox Developer Edition
 - Version: 75.0b11

**Additional context**
- WordPress 5.4
- Gutenberg 7.8.1

**Comment by skorasaurus** [comment]
Thanks for reporting; I've had this problem as well and it has been reported at https://github.com/WordPress/gutenberg/issues/21355

**Comment by talldan** [comment]
Thanks for spotting that @skorasaurus!
