### ISSUE TITLE
Comma in Select option treated a separator and creates new option

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/gutenberg#21356]
**Describe the bug**
When a comma is used in a Form's Select option, the portion of the option after the comma is treated as a new option.

**To reproduce**
1. Create a page with a Form and a Select block
2. Add three options as seen below in my screenshot.

**Expected behavior**
Three options

**Screenshots**
Editor View:
![image](https://user-images.githubusercontent.com/3489003/78272837-a564f580-74d3-11ea-952a-40d93d0486b8.png)

Page View: 
![image](https://user-images.githubusercontent.com/3489003/78272960-caf1ff00-74d3-11ea-87bb-fb583c57983f.png)

Source: 
![image](https://user-images.githubusercontent.com/3489003/78272971-cf1e1c80-74d3-11ea-8811-84edf4480df2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 80

**Additional context**
WordPress: Version 5.3.3-alpha-47419
Host: wordcamp.org multisite

**Comment by talldan** [comment]
> Form and a Select block

Hi @CdrMarks, These aren't part of the blocks offered by Gutenberg, they'll be provided by a plugin.

I notice this is related to a WordCamp site. I'd recommend reaching out through an issue over at https://github.com/WordPress/wordcamp.org
