### ISSUE TITLE
PHPUnit tests are run 3 times per Travis task instead of 2

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#2136]
cc @notnownikki 

All Travis PHP jobs appear to be running the PHPUnit tests 3 times instead of the expected 2 (once in single-site mode and once in multisite mode).

Examples:

- https://travis-ci.org/WordPress/gutenberg/jobs/259927956 (PHP 7.1)
- https://travis-ci.org/WordPress/gutenberg/jobs/259927958 (PHP 5.3)
- https://travis-ci.org/WordPress/gutenberg/jobs/259927959 (PHP 5.2)

As this is resolved, it is probably also worth double-checking that all of those test suite runs are performed using the expected versions of PHP and PHPUnit.

**Comment by notnownikki** [comment]
Found the problem. I have the phpunit version argument wrong. There's supposed to be a section of the script where it shows the php and phpunit versions, so we know the correct things are getting run, but it's actually running phpunit instead of showing the version.

Fixing now...

**Comment by notnownikki** [comment]
Checked the versions, all is fine. If you read through the job logs, you'll see initially the 5.2/3 jobs report php as 7, but if you search for "Running with the following versions" you'll see the correct php and phpunit versions reported.
