### ISSUE TITLE
Not able to click + to add blocks

### ISSUE THREAD

**Issue by FruJohansen** [WordPress/gutenberg#21378]
Hi. Just startet my site from scratch, after I somehow lost everything including my admin/user. Now I can't click the + icon to add more blocks when I write a new post. Why? 

Everything is updated to the latest version, and my theme is Color Mag.

**Comment by talldan** [comment]
Hi @FruJohansen, for user support I'd recommend reaching out on the WordPress Forums:
https://core.trac.wordpress.org/ticket/48531

**Comment by talldan** [comment]
@FruJohansen, Just in case you're only checking your email notifications, I originally posted the wrong link to the forums. Here's the correct one:
https://wordpress.org/support/forums/
