### ISSUE TITLE
Within Columns Block, if child block has attribute with name "txt" column will empty upon update

### ISSUE THREAD

**Issue by rogerlos** [WordPress/gutenberg#21388]
When placing a child block within a column, if there is an attribute whose name is `txt` when a value is saved to that attribute (in my case, via an inspector field), the entire column will be emptied (including any and all other blocks) upon update. Note that the editor will still show all content present, but refreshing the editor, or viewing the front-end version of the page, will show the column is completely empty.

Changing the attribute name within the block from `txt` to `ztxt` stopped this from happening--is `txt` a reserved attribute name within the context of a column?

**Comment by talldan** [comment]
@rogerlos Not that I'm aware of. It might be something else causing the issue rather than the attribute name. If you're able to share your code I might be able to take a look.

**Comment by talldan** [comment]
Closing due to a lack of reply
