### ISSUE TITLE
Components height inconsistency

### ISSUE THREAD

**Issue by wpSpade** [WordPress/gutenberg#21382]
WordPress 5.4

Fix input, select etc. height accordingly to button height:

![inconsistency](https://user-images.githubusercontent.com/54949999/78378381-8c466c80-75d9-11ea-972d-1680d34b6a41.jpg)

Expected:

![expected](https://user-images.githubusercontent.com/54949999/78378515-bd26a180-75d9-11ea-9cfe-24422b7c24a9.jpg)

**Comment by talldan** [comment]
@wpSpade This looks like a WordPress core issue. I think this has already been reported here - https://core.trac.wordpress.org/ticket/48531.
