### ISSUE TITLE
Option to remove icon in PluginBlockSettingsMenuItem

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#21390]
**Is your feature request related to a problem? Please describe.**
The `PluginBlockSettingsMenuItem` slot-fill has an icon option. If you don't add an icon, it uses a default icon, which was good until 5.4. With the new Gutenberg UI, it is less so as by default Menu Items don't have icons.

<img width="576" alt="Screen Shot 2020-04-04 at 2 39 14 AM" src="https://user-images.githubusercontent.com/2649903/78405149-7eb2d600-761d-11ea-9cc7-f41c3a6678cd.png">

So it doesn't make a sense to force the spot-fill to have an icon.

**Describe the solution you'd like**
Not have a default icon.

Sending a PR.

**Comment by karmatosed** [comment]
Just removing the design feedback label as the discussion is happening in PR.
