### ISSUE TITLE
Should contributors be able to select images from media library?

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/gutenberg#21393]
As an admin/author, when adding media you can upload a new image, choose from the library, or insert from a URL. But as a contributor (or somebody without upload_files cap specifically), you only have the option to insert from URL.

It's my understanding that the `upload_files` capability should prevent users from being able to upload new files, not also prevent from being able to choose/use ones that are already in the library.

The component in question: https://github.com/WordPress/gutenberg/blob/ef73ed07bd59bdcbbe77cc1c537299d8e39167b1/packages/block-editor/src/components/media-placeholder/index.js

You can see the fallback is to just show the URL Selection option, but I'm thinking it should also fallback to selecting from the media library. However, maybe it was done this way because currently the media library selection/upload process is closely tied together in the modal: https://d.pr/i/Ib39ut ? 

### With `upload_files`:
![](https://d.pr/i/dF0Xir+)

### Without `upload_files`:
![](https://d.pr/i/VdaggP+)

**Comment by WPprodigy** [comment]
Hmm, somewhat related as well is the behavior of changing out an image.

If an image block already exists on a contributor's post, then they will see the option to replace the image, but the media library modal won't fully load.

![](https://d.pr/i/KrY0rs+)

**Comment by johnbillion** [comment]
Discussion around whether or not a contributor should be able to select from the media library is a WordPress core issue, not a Gutenberg-specific one.

Regarding the `Open Media Library` option appearing here when it shouldn't does appear to be a bug in Gutenberg.

**Comment by talldan** [comment]
I've created https://github.com/WordPress/gutenberg/issues/21442 to cover the Media Library button being present in the replace dropdown.

I'll close this. As mentioned by @johnbillion, this is more of a core WordPress topic. Historically Contributors can't access the Media Library, and this is probably something that can't change for backwards compatibility reasons.
