### ISSUE TITLE
more than 9 icon are not mobile friendly

### ISSUE THREAD

**Issue by kevinkovadia** [WordPress/gutenberg#21395]
**Describe the bug**
When I add more than 9 icons using social icon Gutenberg block, it will preview properly on desktop site as shown in this image
![Screenshot from 2020-04-04 09-30-56](https://user-images.githubusercontent.com/38972017/78418198-ab83df00-7657-11ea-8938-9abd435e53f5.png)

But when we see that page in mobile, it shows something like this image 
![Screenshot_20200404-093105](https://user-images.githubusercontent.com/38972017/78418281-73c96700-7658-11ea-8292-70d884846433.png). Here, 9th social icon (link) is not visible due to space constrain. what we tap left on a mobile screen, then only that 9th icon is visible like this image 
![Screenshot_20200404-093116](https://user-images.githubusercontent.com/38972017/78418339-ef2b1880-7658-11ea-8205-2ff3764887c8.png). that is not mobile-friendly, right?

Probable solution: when the screen is full of icons, the next icon should go in the next line with centre align.

Kindly do needful.

**To reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by desrosj** [comment]
This was also reported on [Core Trac in ticket #50806](https://core.trac.wordpress.org/ticket/50806). I did some more testing, and it seems that allowing the icons to wrap would fix this issue, and others that result from similar issues with breakpoints. I added some more info over on #21842.

**Comment by sabernhardt** [comment]
The `flex-wrap` was added in PR #25334 and seems to fix this, too.

**Comment by jasmussen** [comment]
I can't reproduce this, so it seems the wrapping note mentioned by sabernhardt fixes it:

<img width="1495" alt="Screenshot 2021-03-09 at 10 09 24" src="https://user-images.githubusercontent.com/1204802/110446524-91504d80-80bf-11eb-8d36-66cefd9add7f.png">

The missing margin is a bug that will be fixed by #29657.
