### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#214]
We need to design how to display a visual indication of errors on:
- blocks
- text
- inline elements such as hyperlinks

We also need to be able to display error and warning messages. 

Examples of errors:
- broken hyperlinks
- images that didn't upload
- block-parse errors

Examples of warnings:
- try to publish with placeholders

**Comment by androb** [comment]
@jasmussen not sure where this is in on the priority list? Might be worth putting into the swim lanes somewhere. It would be great to get a designer looking at it (cc @annaephox in case she has bandwidth).

**Comment by jasmussen** [comment]
> not sure where this is in on the priority list? 

It's something we need, absolutely, but something I've been pushing in front of me, sort of assuming we'll get to it eventually, if nothing else then when we implement it in the code. But if Anna has bandwidth, all the ✨!

**Comment by senadir** [comment]
has this been handled yet or not?

**Comment by jasmussen** [comment]
> has this been handled yet or not?

Not yet! If you have bandwidth, feel free to take a stab!

**Comment by jasmussen** [comment]
Closing as fixed by the recent features added to detect and handle changes.
