### ISSUE TITLE
Reordering list items with drag and drop

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#21406]
**Is your feature request related to a problem? Please describe.**

It would be great to be able to drag and drop the items within a list (`<ul>` or `<ol>`) to reorder the items, similarly to how blocks can be dragged and dropped for reordering.

_Background:_ I recently observed a client creating text-heavy content from scratch in the block editor and they made frequent use of reordering blocks with drag and drop as they fleshed it all out. However they found it frustrating that they couldn't reorder items within a list, and they had to do it "the old-fashioned way" of cutting and pasting.

**Describe the solution you'd like**

Some form of control for reordering items within a list, preferably drag and drop but in the future potentially the same controls that block reordering uses.

**Stretch Goals / Wishlist**

* Dragging and dropping sideways to create indented list items
* Dragging from one list and dropping into another

**Comment by mtias** [comment]
Prior discussions around this focused on whether each list item should be a child block so that movers / drag behaviours were built in. With the ability of inner-blocks to absorb the toolbar of a child this might become doable.

**Comment by JimMcL61** [comment]
List management in WP is horrific.  Agree with the above description and challenges.  HTML editor doesn't make the job any easier.
