### ISSUE TITLE
[Question] Is there any way to detect when the DOM loaded ".editor-post-title"?

### ISSUE THREAD

**Issue by Abruptive** [WordPress/gutenberg#21423]
Hi,

Is there any way to check if ".editor-post-title" is loaded? Trying to move it somewhere else via jQuery. Tried: `window._wpLoadBlockEditor.then(function () {` but the only way it's working is with a setTimeout. 

Any ideas?

**Comment by talldan** [comment]
@Abruptive I think you should try Stack Exchange for this type of question, it seems like a generic web development question.
