### ISSUE TITLE
Improve developer documentation for creating plugin blocks

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#2142]
Follow-up tasks to #1619 and #1786.

- [x] Transfer https://github.com/nylen/gutenberg-examples to https://github.com/WordPress/gutenberg-examples
- [ ] Add a short readme to the above examples repo
- [ ] Review http://gutenberg-devdoc.surge.sh/ and add links to relevant sections of the examples repo
- [ ] Remove or dramatically simplify [`blocks/README.md`](https://github.com/WordPress/gutenberg/blob/3543d4c/blocks/README.md) with links to the above documentation

**Comment by lumberman** [comment]
@nylen thanks for great code examples!
By any change you can create a simple example on how to use image/upload feature in the custom block? I was trying to follow the default image module, but for some reason it doesn't work. Maybe there is a way to reuse default blocks like Image/Text/Button in our custom blocks? It will be great to not copy/paste functionality that is already in place.

**Comment by mtias** [comment]
Closing as outdated. The handbook with some tutorials now lives at: https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/
