### ISSUE TITLE
CSS Columns?

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#21433]
CSS Columns allow masonry-like columns and can be very useful (and are well supported).
What Gutenberg block can be used for this? A list? A columns block - but wouldn't its column wrapper prevent this from working?

**Comment by talldan** [comment]
@strarsis I think this could probably be fairly effective on the paragraph block, making the text flow over multiple columns (which seems to be the main strength of CSS Columns). The paragraph supports inline images, so it'd be possible to make newspaper style layouts.

Here's something I hacked together using `column-count: 2;` in my browser dev tools:
<img width="594" alt="Screenshot 2020-04-23 at 12 39 59 pm" src="https://user-images.githubusercontent.com/677833/80059870-ad0e3c00-855f-11ea-93cd-d2502149061b.png">

Group could also be another candidate if the columns were applied to the inner wrapper:
<img width="606" alt="Screenshot 2020-04-23 at 12 46 51 pm" src="https://user-images.githubusercontent.com/677833/80060193-87cdfd80-8560-11ea-820e-696426178b09.png">

I think the toughest thing in terms of bringing this kind of functionality to a core block would be making it work responsively in a reliable way, a similar challenge for lots of other properties of blocks. That and the very similar functionality to the columns block, which might be confusing for users.

I'll close the issue as this seems to be more of a question, but I'm happy to continue the conversation. The Core CSS Weekly chat in slack might be another good place to discuss the topic (on Thursdays or Fridays depending on timezone):
https://make.wordpress.org/meetings/#core
