### ISSUE TITLE
Regression in WP5.4: Preformatted block drops leading space and loses characters on paste

### ISSUE THREAD

**Issue by kkm000** [WordPress/gutenberg#21438]
**Describe the bug**
My provider has just upgraded WP to 5.4. Since the upgrade, the Preformatted block loses all leading whitespace and the `-` characters on paste. 

**To reproduce**
1. Copy the following text to clipboard
```yaml
lotsa_spaces:
  conundrum:
  - foo:
      answer: 42
  - bar:
      question:
```
2. Paste the text into any text editor to be sure that the text in clipboard is in fact formatted correctly, to exclude possible corruption when copying from the GitHub page.
3. In the post editor, add the Preformatted block, and paste text into it.

All whitespace and even the leading `-` symbols are deleted on paste.

**Expected behavior**
Pasted text keeps whitespace as is and does not lose significant characters on paste.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8228229/78607735-7c669c80-7814-11ea-89f3-c4f4c0b90d98.png" width="33%">

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Firefox 64-bit
 - Version: 75.0

**Additional context**
This is a regression; the Gutenberg version that came with the previous latest WP 5.3 did preserve formatting and did not lose characters.

All non-initial whitespace runs in the pasted text are compressed into one space. Also, the leading `#` characters are removed.

I cannot tell the Gutenberg version. I hope that "The version bundled with WP 5.4" is unambiguous? There is no Gutenberg plugin installed, so I am sure I am using the stock WP 5.4 version. I'll be happy to try anything you would suggest to narrow it better.

Symptoms look like a reoccurrence of the bug #6917, fixed nearly 2 years ago.

**Workaround (horrifically inefficient)**
* Switch to HTML. Thanks for never adding a keyboard shortcut for this menu item, despite so many user pleas.
* Add a line break between `<pre>` and `</pre>`
* Paste text into the gap.
* Remove extraneous line breaks before and after text.
<img src="https://user-images.githubusercontent.com/8228229/78608294-7cb36780-7815-11ea-88e4-6feeb56de58b.png" width="58%">

* Switch back to visual editing by dropping your keyboard, hunting for your mouse and mousing frantically through the dropdown menu. The block is now formatted as expected:
<img src="https://user-images.githubusercontent.com/8228229/78608384-ab314280-7815-11ea-8c17-ce02168b2266.png" width="33%">

**Comment by paaljoachim** [comment]
I went ahead and tested with WordPress 5.7.
Gutenberg plugin version 10.1.1
Twenty Twenty One

Backend:
<img width="562" alt="Screen Shot 2021-03-11 at 20 19 15" src="https://user-images.githubusercontent.com/5323259/110842265-29f4f200-82a7-11eb-8c12-877fcc0decd1.png">


Frontend:
<img width="372" alt="Screen Shot 2021-03-11 at 20 19 51" src="https://user-images.githubusercontent.com/5323259/110842273-2d887900-82a7-11eb-809f-e331c96a5fff.png">

This issue is working in WordPress 5.7. So I will go ahead and close this issue.
