### ISSUE TITLE
Optimize Gutenberg for alternate color schemes

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2144]
From Helen:

https://twitter.com/helenhousandi/status/892392500966686720

Here's a screenshot:

![screen shot 2017-08-02 at 10 28 38](https://user-images.githubusercontent.com/1204802/28864619-635d871c-776d-11e7-8464-eda5c67eae13.png)

Her point is solid, specifically around the accent colors. 

We have so far optimized for @hugobaeta's new admin colors. We should override those, for accent colors that the admin theme provides.

**Comment by mtias** [comment]
What's the best way to change the primary / secondary colors?
