### ISSUE TITLE
Navigation: When creating submenu automatically suggest existing submenu pages.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21447]
**Is your feature request related to a problem? Please describe.**
An example.

We created a menu with a lot of submenu pages.
<img width="306" alt="Screen Shot 2020-04-07 at 09 47 32" src="https://user-images.githubusercontent.com/5323259/78643652-dae35780-78b4-11ea-9f92-adb6ac4a9f1f.png">

Let's check out the navigation in Gutenberg.
I see that add existing menu is still not merged. So I add top level pages.

![Screen Shot 2020-04-07 at 09 50 29](https://user-images.githubusercontent.com/5323259/78643906-4d543780-78b5-11ea-9869-df8ae2631528.png)

I click Rooting Agents -> Add Submenu. I expect the existing submenu items to show up in the recently updated suggestion screen.

![Screen Shot 2020-04-07 at 09 52 08](https://user-images.githubusercontent.com/5323259/78644093-a02def00-78b5-11ea-90ca-0a5c72d0e535.png)

Here we see only recently added and not a suggestion of existing submenu pages. As can be seen in the Appearance -> Menus -> Pages screen.

**Describe the solution you'd like**
I would like to be able to see a suggestion of submenu items to an existing parent menu item.

**Describe alternatives you've considered**
Looking up the name of the submenu items and then begin writing the first letters so they show up in the suggestion/recently added screen so that I can select them.

**Comment by jasmussen** [comment]
@shaunandrews had an idea that either in addition to, or as a feature of the incoming "Page List" block (https://github.com/WordPress/gutenberg/pull/28265), when this block was added as a submenu block it would simply list all submenu items, and they would stay in sync when new subpages were added. I'd suggest that be the ideal way to fix this issue.

Already now, said "page list" block does add submenu items, so there's an argument to be made that that PR will fix this one.

**Comment by paaljoachim** [comment]
Thank you Joen! It looks like a very interesting block!
We can close this issue when the PR is merged.

**Comment by tellthemachines** [comment]
#28265, which adds the Page list block, has been merged. @paaljoachim can we close this issue now, or are there any remaining concerns to be addressed?
