### ISSUE TITLE
Copy/cut input values copying entire block/removing block

### ISSUE THREAD

**Issue by tomusborne** [WordPress/gutenberg#21440]
I'm getting some weirdness in WP 5.4 with and without the Gutenberg plugin when it comes to copying/pasting/cutting values.

The following video shows the process/how to reproduce. It was taken using Chrome on Windows.

https://www.screencast.com/t/5I006Nyxhd

I used Twenty-Twenty with no plugins other than Gutenberg activated and used the paragraph block as an example. I originally noticed the problem in my own blocks that I'm building, but it seems to happen with core blocks as well.

It seems to only affect number inputs.

- Copying the value copies the entire block
- Pasting doesn't seem to work (obviously), as it's trying to paste the entire block into the value
- Cutting the value seems to delete the block entirely

It seems like Gutenberg is mistaking the selection for the block itself, even though the input is selected.

**Comment by kirilzh** [comment]
Hi I would like to be assigned to this issue : )

**Comment by quantumleap33** [comment]
WP 5.4.1 maintenance update. Still same issue. Seriously, guys?

**Comment by quantumleap33** [comment]
Apologies, it seems that you are on it, guys! I just had to install the Gutenberg plugin.
