### ISSUE TITLE
Navigation Link block uses incorrect classname for nested submenu

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21444]
**Describe the bug**
The Navigation block uses a Navigation Link inner block and each Navigation Link can also have child Navigation Links to create sub-menus, e.g.:
```
- Navigation
  '- Navigation Link
      '- Navigation Link
```

However when building a deeply nested navigation block and checking the class names used in a post, an incorrect `wp-block-navigation__container` class is used within `wp-block-navigation-link`:
<img width="407" alt="Screenshot 2020-04-07 at 1 07 54 pm" src="https://user-images.githubusercontent.com/677833/78632348-5d7a1000-78d1-11ea-973f-6498f809d3fa.png">

This can also be seen in the Navigation Link's edit function where an incorrect `wp-block-navigation__container` class is used:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation-link/edit.js#L300

This should be easier to solve in both places once https://github.com/WordPress/gutenberg/pull/21075 is merged.

**To reproduce**
1. Build a deeply nested navigation block
2. Preview the post
3. Observe the incorrect class names when inspecting a nested menu

**Expected behavior**
The `wp-block-navigation__container` should be changed to `wp-block-navigation-link__container`.

**Comment by jasmussen** [comment]
> This should be easier to solve in both places once #21075 is merged.

Since that one is merged now, is it time to revisit this one?
