### ISSUE TITLE
Request: Forms Block

### ISSUE THREAD

**Issue by jeremy-blevins** [WordPress/gutenberg#21443]
Hello Everyone,

I am setting up a website with minimal/ no plugins using the twenty twenty theme. I would say most if not all WordPress websites have a contact form. Would it be possible to build a basic form into Gutenberg so it can be part of WordPress Core?

**Comment by deborah86** [comment]
I would also like this. A contact form is a standard on websites. It should be a block.

**Comment by ellatrix** [comment]
Let's close this in favour of #21443, which has more discussion on this topic.
