### ISSUE TITLE
Can't Delete Group Block if there are more than one

### ISSUE THREAD

**Issue by timhibberd** [WordPress/gutenberg#21456]
**Describe the bug**
Can't Delete Group Block if there are more than one

**To reproduce**

1. Add group block
2. Add second group block
3. Try to delete either group block...but there is no user interface to delete the selected group block

**Expected behavior**
Should be able to delete either group block

**Screenshots**
![image](https://user-images.githubusercontent.com/18463324/78673576-ad82c200-7925-11ea-8263-d075dad62ded.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 74.0.1

**Additional context**
- Twenty Twenty Theme V1.2
- WP 5.4

**Comment by bobbingwide** [comment]
I followed the steps to reproduce in WordPress 5.5. beta 3 but found what's necessary for step 3.

3. Use block navigation or the Select tool to select the block you want to delete
4.  then press the delete key or use the

The user interface to select the group block is not intuitive, but it's possible to delete the blocks once they're selected.
It's not as obvious as deleting an empty ( and unwanted ) paragraph block. 
Both methods need clear documentation - perhaps they could be hints displayed at the bottom of the block inserter.

 

![image](https://user-images.githubusercontent.com/2474435/88342535-78b14400-cd37-11ea-9c96-c9cbc99baaa5.png)

**Comment by jordesign** [comment]
Closing this issue as it can no longer be recreated. Group blocks can now be interacted with and deleted when empty.

<img width="869" alt="Screenshot 2023-08-17 at 2 15 16 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/3577da05-fbb3-4b6e-8620-887decc93daf">
