### ISSUE TITLE
Move Gutenberg to be under "Posts" menu

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2145]
From Helen:

https://twitter.com/helenhousandi/status/892392061793599489

Long term our hope is for Gutenberg to _be_ the new post page, which would solve this. As an interim step, to make it easier for people to test this plugin, should we remove the separate menu item, and simply make items under the major Posts menu? 

I.e.:

```
Posts
  All Posts
  Add New
  Add New (Gutenberg)
  Gutenberg Demo
  Categories
  Tags
```

**Comment by hedgefield** [comment]
That would put it closer to where people go to make posts 👍 although perhaps a little less prominent, but probably proximity will balance out prominence.

**Comment by StaggerLeee** [comment]
Maybe to make all Posts hidden from public to start with.
Homepage widgets, queries, etc will show all Gutenberg Posts as latest by date on each "Publish/Save".

Something those testing Gutenberg on live site(s) do not like and want.

**Comment by karmatosed** [comment]
I think either what you have @jasmussen or directly under 'Posts'.

**Comment by melchoyce** [comment]
From [today's chat](https://wordpress.slack.com/archives/C02QB2JS7/p1501695983311919), let's also consider doing the same under "Pages." (Maybe we can leave out the demo there, though, and only have the demo live under "Posts.")

**Comment by paaljoachim** [comment]
I would suggest something like this:
(Perhaps use the word Gutenberg instead of editor.)

![gutenberg-add-new-editor-page](https://user-images.githubusercontent.com/5323259/28942119-77926e36-789a-11e7-9e95-4dd654c70551.jpg)

and

![gutenberg-add-new-editor](https://user-images.githubusercontent.com/5323259/28942140-87844800-789a-11e7-9417-6a9a2dee6db7.jpg)

**Comment by westonruter** [comment]
See also #1797.

**Comment by jasmussen** [comment]
Given Gutenberg is now default, I'm closing this one.
