### ISSUE TITLE
Editor: Top toolbar only gets activated if "Fullscreen mode" gets deactivated first.

### ISSUE THREAD

**Issue by mardroid** [WordPress/gutenberg#21458]
Since WP 5.4, the "Fullscreen mode" is pre-activated on all sites. 

**Describe the solution you'd like**
It's confusing in the sense of UI that when a user clicks on the Block Editor sidebar on "Top toolbar" nothing happens, as the "Fullscreen mode" is pre-configured. 

In order to activate the "Top toolbar" It's necessary first to deactivate the "Fullscreen mode". 

As many 3rd party plugins activate several buttons on the toolbar, the user should have this option easily accessible. (Orders, Clear Cache, Languages, ...)

**Describe alternatives you've considered**
#1 If a user clicks on "Top-toolbar" it should deactivate the "Fullscreen mode" automatically. 
#2 Keeping both options checked is not working. So it doesn't make sense to allow to check both options to be activated.
![top-toolbar](https://user-images.githubusercontent.com/2980214/78676489-cc159880-78e6-11ea-8759-bcfd1458495e.png)

**Comment by talldan** [comment]
@mardroid The top toolbar setting refers to the block toolbar rather than the WP Admin toolbar. There isn't an option for showing the WP admin top toolbar in full screen mode.
