### ISSUE TITLE
From WordPress 5.4, when trying to insert a block, the "Page Break" block is always set at the very beginning of the "Most used" list.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#21462]
As the title says, from WordPress 5.4, when trying to insert a block, the "Page Break" block is always set at the very beginning of the "Most used" list.

<img width="364" alt="page_breaaaak" src="https://user-images.githubusercontent.com/31400297/78683487-503d3f80-792a-11ea-9345-827d83c3b961.png">

**Comment by talldan** [comment]
Thanks for creating the ticket @ddryo, I can also reproduce this.

**Comment by talldan** [comment]
The comments in #19303 maybe explain why this is happening. It seems Page Break is now a child block of Post Content, and my hunch is that child blocks are being given priority in the inserter?

**Comment by galakhyati** [comment]
I was able to replicate this on multiple other sites too. 

On checking the comments on #19303 I am not sure I understand if there are going to be changes applied to how the blocks are being shown. Can someone shed some light on this?
