### ISSUE TITLE
Unable to change heading level for site title

### ISSUE THREAD

**Issue by Retrofitterdk** [WordPress/gutenberg#21464]
**Describe the bug**
After adding site-titel block to either a html-template or a page with the editor, I am unable to change heading level. It is preset to H1 and cannot be changed.

**To reproduce**
1. Enable full site editing
2. Go to Gutenberg -> Site Editor
3. Add Site Title Block
4. Try to change heading level for the Site Title Block

or

1. Add a new page
2. Add Site Title Block
3. Try to change heading level for the Site Title Block

**Expected behavior**
As described in #20361 I would have expected to be able to heading level for the site title since it is not always appropriate to use H1.

**Screenshots**

![heading-level-site-title](https://user-images.githubusercontent.com/9422676/78689112-413c9a00-78f6-11ea-861f-28795a69af9e.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome, Safari and Firefox

**Additional context**
- Gutenberg  version 7.8.1
- Full site editing enabled
- WordPress version 5.4

**Comment by annezazu** [comment]
Thanks for reporting @Retrofitterdk! I'm closing this in favor of the following earlier issue which touches on adding styling attributes to Site Title, Site Description, and Post Title Blocks: https://github.com/WordPress/gutenberg/issues/19491
