### ISSUE TITLE
Inserter: Always show blue line

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#21475]
In previous versions, a blue line would appear in the block list, where the block itself would be inserted:

![blue line before](https://user-images.githubusercontent.com/1204802/78758282-2c0b4e00-797e-11ea-90d5-f250c2f1e063.gif)

This regressed recently, and that blue line is no longer available:

![blue line](https://user-images.githubusercontent.com/1204802/78758302-3299c580-797e-11ea-9ecc-f2897561da45.gif)

Let's both fix this, and revisit it. We should try showing this blue line _as soon as you open the inserter_. I.e. this:

<img width="1220" alt="Screenshot 2020-04-08 at 09 48 07" src="https://user-images.githubusercontent.com/1204802/78758350-48a78600-797e-11ea-83d7-49b6240d0cd9.png">

So, not just on hovering a block in the inserter, but just by virtue of it being open.

**Comment by jasmussen** [comment]
@ellatrix I know you've worked on making the DOM lighter — do you have any idea if that might have caused the blue line to go missing?

**Comment by ellatrix** [comment]
@jasmussen There's aPR here: #20792
