### ISSUE TITLE
List block: explore dropdowns.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#21477]
The List block looks like this:

<img width="675" alt="Screenshot 2020-04-08 at 10 58 44" src="https://user-images.githubusercontent.com/1204802/78765516-68dc4280-7988-11ea-97ed-46f17b95bb4f.png">

So as to optimize and group items, we should explore collapsing the list type and tools in dropdowns, like so:

<img width="481" alt="Screenshot 2020-04-08 at 11 02 03" src="https://user-images.githubusercontent.com/1204802/78765562-75609b00-7988-11ea-9daa-706b99662332.png">

This would also potentially afford some interesting additional list types, like ordered with letters.

**Comment by jasmussen** [comment]
_As you can see from my ticket rename, I was originally drafting a different ticket ;)_

**Comment by paaljoachim** [comment]
Companion issue: https://github.com/WordPress/gutenberg/issues/17738

**Comment by karmatosed** [comment]
I think exploring any reduction to drop-downs for the toolbar makes sense. It also benefits all screen sizes and reduces cognitive load.

**Comment by paaljoachim** [comment]
This is a very good idea!
We have the list type options as primary options directly in the toolbar.

**Comment by mapk** [comment]
I noticed in the description that the toolbar isn't reflecting the list type chosen. 

![Screen Shot 2020-12-01 at 12 56 17 PM](https://user-images.githubusercontent.com/617986/100795897-a2106980-33d4-11eb-9d41-590de04a9241.png)

I'm guessing this is an oversight, and it would look like this:

![Screen Shot 2020-12-01 at 12 59 24 PM](https://user-images.githubusercontent.com/617986/100796159-12b78600-33d5-11eb-9d16-b280c701ab46.png)

**Comment by mapk** [comment]
I'll also note that the icons there are really starting to look too similar. In the Figma library, they look like this:

![Screen Shot 2020-12-01 at 1 03 26 PM](https://user-images.githubusercontent.com/617986/100796606-c4ef4d80-33d5-11eb-8881-c967dceb5d0e.png)

The Figma options feel different enough to provide an easier understanding.

**Comment by richtabor** [comment]
Had some thoughts here. The `>` `<` buttons are an action you do multiple times perhaps, I'm not 100% that they should be in the dropdown. To indent a list item, you'd need to click on the icon, then click the correct dropdown item - instead of currently where you can move it in and out quickly.

**Comment by paaljoachim** [comment]
I believe we are looking at having a consistency with how we select alignments controls today. It is a familier UI flow.
Here is an example from the Image block.

<img width="494" alt="Screen Shot 2020-12-01 at 22 10 20" src="https://user-images.githubusercontent.com/5323259/100797287-2dfcb280-3422-11eb-8c73-1a6404ebdecc.png">


Which we can then transfer over to having a similar selection but for list types.

**Comment by jasmussen** [comment]
Eagle eyes. Thankfully the icons have already been updated in the code, to this:

<img width="213" alt="Screenshot 2020-12-02 at 08 50 11" src="https://user-images.githubusercontent.com/1204802/100844087-a0e64780-347b-11eb-88f7-b0ea4dff838a.png">

Additionally in revisiting this, I'd remove the separator between the two items as they are related:

![Untitled-1](https://user-images.githubusercontent.com/1204802/100844254-e60a7980-347b-11eb-8965-43e56e5e6b34.png)

> Had some thoughts here. The > < buttons are an action you do multiple times perhaps, I'm not 100% that they should be in the dropdown. To indent a list item, you'd need to click on the icon, then click the correct dropdown item - instead of currently where you can move it in and out quickly.

Is this an often enough occurrence that it needs separate buttons vs. be grouped in the dropdown?

**Comment by jasmussen** [comment]
In light of the List block receiving nesting, I'm going to close this one as essentially obsolete. There are still aspects of the conversation here that may be relevant, so they're crosslinked from the nesting work in https://github.com/WordPress/gutenberg/pull/39605#issuecomment-1073644254.
