### ISSUE TITLE
Pasting old content creates extra unnecessary blocks.

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2147]
## Issue Overview
Pasting content from a post written with the current editor into gutenberg creates some extra blocks. Result:
<img width="776" alt="_untitled____gutenberg_ _wordpress_develop_ _wordpress" src="https://user-images.githubusercontent.com/6073772/28865574-a706b2b0-7770-11e7-836e-30c9e8bb60fe.png">

## Steps to Reproduce (for bugs)
1. Open a simple post written with the current editor.
2. Select all, copy.
3. Start a new post via the gutenberg admin menu.
4. Paste into the first/default empty text block.
5. Note that the conversion to blocks happens correctly, but the original placeholder block is still there, as well as an empty block in between that and the pasted content, which gets selected?

version 0.6.0
vagrant dev env
chrome on mac

## Expected Behavior
For the old text to be reformatted into blocks as best it can and the placeholder to be removed/replaced.

There is no reason, text-wise, why it should deal with this strangely. Opening the original post in the text view shows no strange markup - none at all, in fact. Literally the first character in there is the first character of the first sentence.

**Comment by iseulde** [comment]
@hedgefield Does this still happen in current master now?

**Comment by hedgefield** [comment]
Yes it does, running 0.9.0. Pasting the copied Visual view content does this. Pasting the copied Text view content doesn't recognize the html tags and dumps it all in a single paragraph.

**Comment by iseulde** [comment]
Okay, I mean master here with the latest commits. It will be in 0.10.0 then.

**Comment by hedgefield** [comment]
Okay cool, will test with the next release.

**Comment by iseulde** [comment]
@hedgefield How's the latest release? :)

**Comment by hedgefield** [comment]
Fixed! :)
