### ISSUE TITLE
Introduce peer dependent Blocks.

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#21488]
## The Problem

You want to create some blocks, that works together, and needs each other to make sense, yet can't have the parent-child relation, they should be top-level blocks, but the relationship could be:

### 1. Block B needs Block A (One to One optional on one side).
- A block type will require having another block present on the page for it to function.

### 2. Blocks A and B are dependent on each other (One to One).
- Both blocks need each other to work, as they do things that the other one compliment. 

### 3. Block B needs Block A and C (One to Many).
- A single block might need more than one block to function.

## The Solution

Introduce a new setting when registering a block to define an array of peer blocks.

```js
export const settings = {
	title: __( 'Filter by Price' ),
	peer: [ 'woocommerce/all-products' ],
	//...
}
```

### Validation

We currently have two modes of restrictions in the editor (visually)

- Parent: the block won't be visible in the inserter, it will only be visible if you're inserting inside its parent block.
- Support.Multiple: when a block can only be inserted once, you will see it disabled on the block inserter.

Both of those limitations exist before you can insert the block, for our case, we can only have that in the first case (with some limitations).

#### Scenario 1 (One to One optional on one side):
- A block (Filter) depends on another block (Product grid) to exist for it to work.
You try to insert the `Filter` block, it wouldn't work since you don't have `Product grid` inserted.
You insert `Product grid` block, the `Filter` block is now insertable.
You delete `Product grid` from the page, what will happen to `Filter` block, will it also be deleted? or saved normally?

#### Scenario 2 (One to One):
This is the same as the first example yet each one depends on the other, who will be inserted first, each one will disable the other and so on.

For this we need another kind of validation, save level validation, which is different from the draft autosave, when you click on Save, Update or Add post, your blocks will be validated, if a block is missing a peer dependency, you will not be able to save, an error will be shown either on the block as a tooltip, or a top-level notice, telling you that this block needs another block to work.

## Before inserting
This can also be taken one step further, for third party blocks that work with each other, dependencies will be validated after all blocks are registered, if a block has a dependency for a block that is not registered, you will not be able to insert it, some sort of context should be shown, the block will be disabled on the inserter level, because it wouldn't make sense to install it.
Plugins have this sort of dependency, it could be moved to blocks, so when we start having independent blocks being installed (from the future block directory).

## Real-life use cases:

A good question is why such a thing is needed, I'm not aware if other use cases exist, but they could exist in dynamic blocks, an example is our work on WooCommerce blocks, we have cases in which certain blocks work with each other, those blocks are a
- Products grid block, that shows all products on a website.
- Other Filter by attribute type of blocks, that changes what Product grid block is showing right now.
- An Active filter block, that shows all currently active filters you have, that also depends on having Filter blocks in the page.

## Other types of dependencies:

We only discussed dependencies in which a block will need another to work, another dependency is when the block will not function well if another block is present on the page, so only one of them can exist.

An example is Cart and Checkout Blocks, in which both communicate to the same data and backend in different ways, having both of them on the same page causes some issues and unexpected behavior.

**Comment by mcsf** [comment]
From the examples discussed here, I'm not convinced that we'd benefit from introducing a formal concept of peer-dependent blocks. Do you have specific reasons in mind against letting blocks manage these relationships on their own?

From a UX perspective, here are a few things on my mind:

* Many times, blocks that are missing a "block dependency" can gracefully handle that absence. For instance, a Products Grid block with no Filter nearby will just show all products, unfiltered. A Table of Contents block with no Headings nearby will naturally show nothing at all. In these cases, the blocks are just following their default behaviour. A similar a8c example: the [Project Status block](https://github.com/Automattic/wp-calypso/pull/38303) will just read "0 tasks" if there are no Task blocks nearby (although there's a bug to fix where it shows _NaN % completed_).

* It's useful to nudge the user in the right direction, just as the editor already does for low-contrast colour configurations or for unbalanced headings in a document. And a nudge is a lot nicer than an error or a failure. For instance, the aforementioned Project Status block doesn't "fail" in the absence of Task blocks, but it could perhaps be improved to suggest that the user start adding tasks to see changes in the block. The same advice applies to Woo's Filter block: a Filter with no Products nearby isn't necessarily wrong — it can be a statement of intent if the user is expecting to later add a products grid, or some other filterable block — so let's just remind the user that a good next step is adding Product Grid.

* It's also already an established design pattern in the block editor that, while an unselected block should look as close as possible to the front end, a selected block can have more contextual visual elements attached to it, like placeholders. So, contextual nudges could potentially only be shown when a block is selected — but the block author can make that choice.

* Finally, especially when dealing with failure states, the front end and the editor view may mismatch. If there is some block out there with peer dependencies that really needs other blocks to avoid "failure", then this failure should only be visible in the editor. In the front end, that block would most likely just not render. A Filter block with no Product Grid blocks nearby makes sense while in the editor, but in the rendered page that Filter block should disappear.

These UX considerations are important to conclude that, IMO, there is no user-facing need to provide some editor-level support for peer dependencies. The current affordances are plenty and flexible to accommodate one-to-one, one-to-many and other relationships.

I would even argue that there are UX arguments _against_ formal peer dependencies; for instance, could the hiding of peer-dependent blocks from the Inserter be detrimental to the user experience? Whereas parent-dependent blocks are a one-way relationship that is easier to understand, peer dependency can mean many things, and — judging only by the scenarios originally presented — it can quickly become quite complex. A user might not understand why a block is sometimes available and sometimes not. It can also harm discoverability of blocks and features. Wouldn't it be preferable to let a user insert a Filter block — even if they don't yet know what it does — and let the Filter block teach them that they can now insert specific blocks to make everything work?

That leaves us with the technical considerations. Here, too, I believe we have everything we need:

* Blocks can be static but also dynamic, which can be useful to deal with certain failures.

* There are plenty of components to represent nudges (banners, snackbar, popover, inspector controls) and the underlying technology (Slot/Fill) allows us to build anything else.

* The data layer provides everything that a block needs to listen to other blocks.

* On the server side, the block parser is available if there are specific server-side needs.

However, it's important to note some opportunities for improvement:

* Deep block traversal is less convenient than linear operations on top-level blocks, so perhaps exposing some handy block-traversal utilities or documentation could help block authors.

* Server-side parsing is still fairly limited in that there is no attribute sourcing.

To close this comment, I'll come back to my first question: do you have specific reasons in mind against letting blocks manage these relationships on their own? I'm interested in hearing that and any counterargument to the above.

**Comment by Thelmachido** [comment]
@senadir no information was provided since this was marked as stale I’m going to go ahead and close out this issue. If anyone feels it should still be looked at, please feel free to circle back and reopen.
