### ISSUE TITLE
Replicate Figma's "Auto Layout" feature for containing blocks

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#21494]
Now that we've been [working on creating block patterns](https://github.com/WordPress/gutenberg/issues/20345), I'm finding that spacing, margins, and paddings are some of the hardest layout elements to manipulate.

While working on Figma, I couldn't help but think that it would be incredibly useful to have something similar to their Auto Layout feature in some of Gutenberg's blocks, particularly those that are used as "containers" (group, column, etc.).

The Auto Layout feature in Figma basically takes care of spacing and alignment of child items inside a frame (a frame in Figma is similar to what we call a group in Gutenberg).

The tool looks like this:

<img width="240" alt="Screen Shot 2020-04-08 at 17 01 52" src="https://user-images.githubusercontent.com/3276087/78838677-4ebc5780-79bc-11ea-8118-da5890529b4d.png">

It allows for the setting of horizontal and vertical direction, horizontal and vertical padding, and spacing between child elements.

In practice, it looks like this:

![2020-04-08 17-22-50 2020-04-08 17_25_27](https://user-images.githubusercontent.com/3276087/78839378-fdad6300-79bd-11ea-903d-632b60112ba4.gif)

Being able to manipulate these settings on a per-block basis would be very useful when creating custom layouts and patterns.

**Comment by ItsJonQ** [comment]
Wow 😍

**Comment by talldan** [comment]
GSomething in discussion over in #23915 is how to let users incorporate different types of blocks into or alongside the Nav Block.

Horizontal layouts are pretty common on the web, a user might want their navigation links on the left and a search form on the right. Something like this seems like it could solve the problem.

Options similar to flexbox's `justify-content` rule might also be useful (that might be something figma already has options for):
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by talldan** [comment]
Also related: https://github.com/WordPress/gutenberg/issues/20141

**Comment by mtias** [comment]
I believe this is mostly already in place in flex based container — new blocks would fit in the horizontal or vertical layout, and they'd inherit the block spacing property. If there are any further improvements to be made we should consider them in new tasks.
