### ISSUE TITLE
Consider adding playlists for audio and video

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2150]
Currently on the existing editor audio and video there is an option for a playlists. For example:

![2017-08-02 at 10 47](https://user-images.githubusercontent.com/253067/28868038-09653298-7770-11e7-998d-e3ba4fe79296.png)

![2017-08-02 at 10 47](https://user-images.githubusercontent.com/253067/28868056-163467fa-7770-11e7-8e16-f2277b29f3bb.png)

![2017-08-02 at 10 48](https://user-images.githubusercontent.com/253067/28868066-2115c312-7770-11e7-8522-a9fea2218297.png)

We currently have tickets for video and audio blocks. Should this be an option for the blocks or should it be a separate block?

**Comment by mtias** [comment]
Can we close in favor of https://github.com/WordPress/gutenberg/issues/805 ?

**Comment by karmatosed** [comment]
Totally!
