### ISSUE TITLE
Term names in taxonomy meta box form token field are escaped on output

### ISSUE THREAD

**Issue by goldenapples** [WordPress/gutenberg#21513]
**Describe the bug**
In the FormTokenField component of a taxonomy meta box on the post screen, terms are output with HTML encoding.

**To reproduce**
1. Create a tag with a curly quote or other special character in the title that gets HTML encoded on save. 
    ![Screenshot from 2020-04-09 14-21-19](https://user-images.githubusercontent.com/665992/78927785-71f30f80-7a6d-11ea-9f17-6423a6226cde.png)  
    ![Screenshot from 2020-04-09 14-21-04](https://user-images.githubusercontent.com/665992/78927791-761f2d00-7a6d-11ea-9be0-dee066b9f013.png)
2. Edit a post and try to apply this term to the post through the Tags control in the document inspector.
4. Tag name shows up with HTML entities escaped.  
    ![Screenshot from 2020-04-09 14-20-37](https://user-images.githubusercontent.com/665992/78927880-9c44cd00-7a6d-11ea-8937-452f19340009.png)

**Expected behavior**
I'd expect the tag name to display in this component the way it does when output through PHP. This seems like a case where the `<RawHTML>` component would be used to render the title, or it be set  as inner HTML of the wrapper element using `dangerouslySetInnerHTML`.

**Comment by johngodley** [comment]
I wasn't able to reproduce this problem with WordPress 5.4, or the latest Gutenberg.

![image](https://user-images.githubusercontent.com/1277682/79470248-17236000-7ff9-11ea-9261-0c4166895102.png)

What version of Gutenberg are you using? Are you running any plugins that might manipulate tags? Could you paste the exact tag you've used here?

**Comment by goldenapples** [comment]
This is happening for me in a vanilla WordPress 5.3.2 with Gutenberg plugin version 7.7.0.

The tag name in the example above is exactly `Tag&#039;s with curly quotes`. (Don't ask how I found this bug, it has something to do with a client creating content in Google Docs and copying it into input fields in the WP admin. They paste formatted strings from another app into the tag name field to ensure that texturized output like curly quotes are preserved on output, which works fine when this string is output from PHP. Its only a problem when run through the JSX escaper.)

**Comment by johngodley** [comment]
This isn't happening for me on WordPress 5.4. Could you try upgrading to WordPress 5.4? Are you running any plugins that could modify the tag?

**Comment by karmatosed** [comment]
I am currently unable also to replicate this. If you are then please update this issue and we can reopen, for now closing until more details.
