### ISSUE TITLE
Replace `wp_make_content_images_responsive()`.

### ISSUE THREAD

**Issue by joemcgill** [WordPress/gutenberg#21510]
**Is your feature request related to a problem? Please describe.**
Based on https://core.trac.wordpress.org/changeset/47554, `wp_make_content_images_responsive()` will be deprecated in WP 5.5 and replaced by `wp_filter_content_tags()`. There are currently two places in this plugin where `wp_make_content_images_responsive()` are being called directly, which will throw deprecation notices when running against WP trunk. See: https://github.com/WordPress/gutenberg/search?q=wp_make_content_images_responsive&unscoped_q=wp_make_content_images_responsive

**Describe the solution you'd like**
Replace instances of `wp_make_content_images_responsive()` with `wp_filter_content_tags()` if the latter function exists and fallback to `wp_make_content_images_responsive()` if not.

**Describe alternatives you've considered**
I'm curious in the two places where this is called why specifically all these formatting functions are being called directly, rather than applying `the_content` hook to the template part code?

**Comment by johnstonphilip** [comment]
I just opened a PR for those here:
https://github.com/WordPress/gutenberg/pull/21514

@joemcgill You can find the PR why that (the_content) was changed here:
https://github.com/WordPress/gutenberg/pull/20343

**Comment by joemcgill** [comment]
Yeah the PR looks good. Thanks for the explanation and helpful example. I wonder if long-term it would make sense to process all formatting functions through a filter specifically for template parts so that changes to default formatting of content could be hooked/unhooked as needed, but this takes care of the current problem.

**Comment by skorasaurus** [comment]
was later fixed in https://github.com/WordPress/gutenberg/pull/21514
