### ISSUE TITLE
Pasting RTL words into the editor that is set for LTR end up with backward words

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#21517]
**Describe the bug**
I frequently write in English and would like to share Hebrew words in the middle of sentences. I'll pull the word from another source, and paste it into the editor only to find out the word gets pasted backwards. 

**To reproduce**
1. Make sure the editor is set for a LTR language like English.
2. Copy and paste a Hebrew word into the editor.
3. Observe that it is backwards from where you copied it.

You can try coping a word from Google Translate to grad a word.

**Expected behavior**
I expected the RTL word to keep its letter order.

**Screenshots**

![Screen Shot 2020-04-09 at 12 23 55 PM](https://user-images.githubusercontent.com/617986/78933064-816a5c80-7a5d-11ea-9210-ecb9da0a531a.png)

This issue was also recorded here: https://wordpress.org/support/topic/having-issue-with-text-format-and-slug/

**Comment by mapk** [comment]
Related: https://github.com/WordPress/gutenberg/issues/12352

**Comment by kathrynwp** [comment]
Hi @mapk – I'm no longer seeing this behaviour. 

With my WordPress install set to English, I pasted `אביב` (a word copied directly from [here](https://www.teachmehebrew.com/500-basic-hebrew-words.html)) into the editor. 

The word remained like that, both in the editor and on the front end:

![Add_New_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/182712715-16c5461c-2714-40e6-9132-b52333fc2037.jpg)

Tested with:

WordPress 6.0.1
Gutenberg 13.8.0 active or inactive
No other plugins active

I'm going ahead and closing this as fixed, but if you can still replicate, feel free to add a comment with more information about how to replicate, and I'll be glad to have another look.
