### ISSUE TITLE
In block-template - Shortcode block does not work

### ISSUE THREAD

**Issue by Bowriverstudio** [WordPress/gutenberg#21519]
**Describe the bug**

In block-templates

[greeting]

Displays [greeting] instead of "Hello World"

**To reproduce**
1. Download parisienne theme from https://github.com/WordPress/theme-experiments
2. Activate Gutenberg Experiments
3. Add the function in functions.php

```
function demo_shortcode() { 
 
    // Things that you want to do. 
    $message = 'Hello world!'; 
     
    // Output needs to be return
    return $message;
    } 
    // register shortcode
    add_shortcode('greeting', 'demo_shortcode'); 


```
4. add the code

app/public/wp-content/themes/theme-experiments/parisienne/block-templates/index.html

[greeting]

5. Add the same code in the post editor.

**Expected behavior**

I see "Hello World" from the post, and [greeting] from the block-template

**Additional context**
- Gutenberg - 7.8.1
- Wordpress 5.4

**Comment by Bowriverstudio** [comment]
```

<!-- wp:shortcode -->
[greeting]
<!-- /wp:shortcode -->
```
Sorry the HTML comments was removed by github.

**Comment by johnstonphilip** [comment]
Shortcodes were intentionally removed from template parts here:
https://github.com/WordPress/gutenberg/pull/20343#issuecomment-589815581

**Comment by Bowriverstudio** [comment]
@johnstonphilip thank you for letting me know.
