### ISSUE TITLE
Color picker issues in various blocks

### ISSUE THREAD

**Issue by tbradsha** [WordPress/gutenberg#21511]
**Describe the bug**
When choosing colors on the Paragraph, Heading, Cover, and Group blocks (probably others as well), the color picker modal disappears when clicking or dragging on the color palette. This doesn't appear to affect all blocks (e.g. Pullquote works fine).

**Screenshots**
Using core block editor (Gutenberg plugin disabled):
![Screen Capture on 2020-04-09 at 10-26-46](https://user-images.githubusercontent.com/32492176/78918010-f4b7a280-7a4c-11ea-97c2-932e6a245a3b.gif)

With Gutenberg 7.8.1 plugin enabled:
![Screen Capture on 2020-04-09 at 10-24-09](https://user-images.githubusercontent.com/32492176/78917637-65aa8a80-7a4c-11ea-82f6-9a8a3f15e1c9.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: Chrome 80.0.3987.163, Safari 13.0.4, Firefox 75.0

**Comment by youknowriad** [comment]
I believe this has been fixed recently.
