### ISSUE TITLE
Template parts saving behavior is confusing

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#21512]
Right now, when you want to override theme's provided template parts and save them while editing a parent template. If it's the first time a theme's template is being customized, the saving will create template parts but only for the given edited template. My expectation is that unless I decide to "fork" the template part, the edited version should override the theme's one in all of the theme templates relying on that template part.

**Comment by vindl** [comment]
cc @Addison-Stavlo since you were looking into saving flow improvements recently.

**Comment by Addison-Stavlo** [comment]
Yeah, i definitely agree the current behavior with TPs is a bit confusing.  I have mostly been improving the interface around the save flow, but there definitely seem to be some underlying issues like this that we will need to handled soon before we are able to implement more desired functionalities.
