### ISSUE TITLE
Position navigation save menu to right

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21523]
In the experimental interface, the 'save' button is left aligned. I think it makes a little more sense to be right-aligned. This also reflects the existing screen.

![image](https://user-images.githubusercontent.com/253067/78936732-0cbc1000-7aa7-11ea-8544-f80c222c2911.png)

**Comment by draganescu** [comment]
@karmatosed #21486 introduces a delete button and that complicates this :)

**Comment by karmatosed** [comment]
@draganescu I'll take a look but I think my point is still valid as to the ordering.

**Comment by karmatosed** [comment]
Closing this one as we're dealing with this in #21486
