### ISSUE TITLE
Iterating on the New Template Area (Partial) flow

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#21526]
Here is a gif and an image of a new template area (partial) inserted into the site editor in Gutenberg (master):

![2020-04-09 15 36 53](https://user-images.githubusercontent.com/1123119/78943375-f6975b00-7a78-11ea-87c0-5db22ca2c2c5.gif)

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1123119/78944573-73c3cf80-7a7b-11ea-8c04-85dec70a3810.png">

### Proposal

This works well enough for demo purposes. Now, it's time to iterate on the process a bit. I propose we make some minor changes to make the process a little tidier. I put together a prototype using a design pattern from [an issue iterating on the Inserter](https://github.com/WordPress/gutenberg/issues/21080). It's not particularly relevant to this issue as the changes I'm proposing are limited to the moment after the Template area is inserted into the post.

Try [the prototype](https://www.figma.com/proto/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=2928%3A5129&viewport=-1508%2C2425%2C1&scaling=min-zoom).

![2020-04-09 13 55 11](https://user-images.githubusercontent.com/1123119/78944899-3ca1ee00-7a7c-11ea-9d2e-816bfd565707.gif)

Lets not ask for the theme name. If it's necessary, that should be done behind the scenes. Let's not ask for a slug. Instead, we should generate a slug based on what the user names the template area (similar to how a site title translates into a URL).

### Screenshot
![image](https://user-images.githubusercontent.com/1123119/78945161-d6699b00-7a7c-11ea-8b67-66a346192654.png)

**Comment by karmatosed** [comment]
Firstly, I love the reduction in things being asked for and move towards simply creating the template area. I also think a move to visual for this makes a lot of sense. I wonder could this go further and just create the template area name, similar to reusable blocks where you edit after creation? I might be missing the benefit though of giving it a name first.

**Comment by mapk** [comment]
> Lets not ask for the theme name. If it's necessary, that should be done behind the scenes. Let's not ask for a slug. Instead, we should generate a slug based on what the user names the template area (similar to how a site title translates into a URL).

Thanks Michael! I agree with all of this. Can we get this integrated sooner than later? I'd love to fiddle with this new interaction in the Site Editor.

**Comment by MichaelArestad** [comment]
> Can we get this integrated sooner than later? I'd love to fiddle with this new interaction in the Site Editor.

Sounds good to me!

**Comment by MichaelArestad** [comment]
I've proposed an update to the design for this on a comment on [#21218](https://github.com/WordPress/gutenberg/issues/21218#issuecomment-641629633). For simplicity, I would like to keep conversation there.

**Comment by MichaelArestad** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/23295
