### ISSUE TITLE
Allow for 'absolute positioned' images (or other blocks)

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#21539]
Here's an aspirational block pattern that cannot currently be created with Gutenberg:

![Frame 10](https://user-images.githubusercontent.com/3276087/79025606-e7cda880-7b4b-11ea-979c-bc514700f60f.png)

If we were to have the ability to position images freely (or within the constraints of a grid) anywhere inside a group or cover block, achieving this kind of layout could be a possibility.

**Comment by marceloaof** [comment]
I support proposals to achieve overlappping elements inside a grid design.
Margins and paddings on each block are also needed to solve this issue properly on a responsive web design, in which CSS properties set by device mode/breakpoints allow adjusting the spacing.

**Comment by mtias** [comment]
@enriquesanchez that seems to be on the same plane as this issue https://github.com/WordPress/gutenberg/issues/20193 I think "background positioning" would be more achievable than positioning blocks.

**Comment by enriquesanchez** [comment]
@mtias Agreed, background positioning should be easier to achieve. One aspect I was considering is that absolute positioning could allow us to have more than one element to be positioned this way, but it didn't occur to me that [the same could be achieved with multiple background images](https://css-tricks.com/almanac/properties/b/background-image/#article-header-id-3).

Closing in favor of #20193.
