### ISSUE TITLE
Block button after update to 5.4 not centered on front end and have huge gaps in the editor

### ISSUE THREAD

**Issue by yura-x** [WordPress/gutenberg#21531]
After update and introducing 'core/buttons' block there is a 4px gap for first button in the buttons group:

**To reproduce**
1. Create 'buttons' block
2. See how it looks on the front end

**Expected behavior**
Want that first button have not left margin:

**Screenshots**
[https://prnt.sc/rwmg04](https://prnt.sc/rwmg04)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - WordPress Version 5.4

It can be fixed like this:

```
.wp-block-button:first-child {
    margin-left: 0;
}
```

Also there is a too big gap for buttons block inside columns block in the editor:

[https://prnt.sc/rwmkaj](https://prnt.sc/rwmkaj)

It can be fixed like this:

```
.wp-block-buttons .block-list-appender,
.wp-block-buttons .wp-block.block-editor-block-list__block[data-type="core/button"] {
	margin-top: 0;
	margin-bottom: 0;
}
```

Hope this will be helpful.

**Comment by youknowriad** [comment]
Thanks for the issue, the margin have been fixed recently and will be part of the next Gutenberg release. The frontend centering is potentially a theme issue. Make sure to center the wrapper (the buttons block) and not the button block itself.

I hope that helps.

**Comment by yura-x** [comment]
Many thanks for quick reply. However i think that the first button inside buttons block should not have 4px margin in any theme. By the way theme that I was tested is the default 2020 theme.

**Comment by youknowriad** [comment]
I agree and it was fixed in the Gutenberg plugin already;
