### ISSUE TITLE
Preformatted block to  be compatible with doc files formatting.

### ISSUE THREAD

**Issue by jimmy19742** [WordPress/gutenberg#21541]
**"Preformatted" block to be compatible with MS Word formatting**

Dear team members, I read carefully what the purpose of the"Preformatted" block is. However as a person who writes their posts in MS Word format (a.doc file) I cannot use it from the very beginning of my adoption of Gutenberg. It was from its version 3.8. All formatting gets lost. And there are 4 of us. For security reasons I'm the only one with an access to the login page.( via a htaccess the)
As a newbie in JavaScript and in React framework I do not know how this could be accomplished of if it's possible to be implemented at all. However if there is a way for this, it will save me time and double efforts .And probably not only to me. If you think it's too complex to be included or it's not worth it for some other reason, please excuse me and discard this  proposal.
Best regards!
[Edit] Putting it simply it's this**I copy the content of a . doc(x) file where there are bold, italic ,bold & italic sentences,and pasting in a block where this formatting will stay/ will be kept**

**Comment by johngodley** [comment]
If you are copying content from Word then you can paste straight into the editor and it will retain formatting. The pre block is equivalent to using a `<pre>` html tag, and I don't think what you want.

**Comment by jasmussen** [comment]
@jimmy19742 Let us know if John's suggestion of just copy pasting content directly, without using the preformatted block, works for you!

**Comment by jimmy19742** [comment]
Dear, @johngodley  I did understand that the Preformatted block purpose was different and I have never used it except one to be sure.
I ve been pasting the content in a long  Paragraph block and all formatting was gone. However I  just finished reading an article how to dublicate a post in Gutenberg and it came to my mind that if I select from the 3 dots  "Top toolbar" and I paste the whole content without wrapping it in a Paragraph block , it might solve my problem.

What do You think about this,Sir?

**Comment by jimmy19742** [comment]
@johngodley Give me about 10-15 minutes , please , I'll let You know!

**Comment by jimmy19742** [comment]
Well,the default Block is the Paragraph Block  and everything was lost. Then I tried with the Classic block albeit I don't like it because I totally enjoy the opportunities Gutenberg gives me ,and it didn't work either.

**_However , it's not a big deal. Please, consider the issue as resolved and excuse me for bothering the whole team
Best regards!._**

**Comment by jimmy19742** [comment]
**This sorta of ticket is closed.
At least for me
Wish you all have a great day**
