### ISSUE TITLE
Input field in BlockControls doesn't work

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#21543]
**Describe the bug**
If you add an input field in BlockControls using Popover/Dropdown, it closes and selects the block as you start to type.

- It works fine when you stick the toolbar to the top.
- It happens with all blocks, not just RichText.

**To reproduce**
1. Add a button to BlockControls which opens a Popover which has an Input Field, new or existing.
2. Click and type on the input field and it will close the popover
3. Stick the toolbar to top and it will work.

**Expected behavior**
It should work just like when you stick it to top.

**Screenshots**
Sorry for the low-quality GIF.

![Gif](https://user-images.githubusercontent.com/2649903/79039072-54a07b80-7bfc-11ea-8e0d-e1477869919e.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 74.0.1

**Additional context**
- Gutenberg version: http://www.giphy.com/gifs/YrGl1bRDxSdtsmPZZd

**Comment by youknowriad** [comment]
This was recently fixed in the repository. Thanks
