### ISSUE TITLE
Consider to improve the categories selection UI when there are many categories

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2154]
Splitting this out from #1490 

> For the categories selector, we'd have to rewrite completely (maybe with virtual scroll, something like Calypso) to load paginated categories

When there are many categories, the list is really... long 🙂 

![screen shot 2017-08-02 at 13 34 29](https://user-images.githubusercontent.com/1682452/28872107-f646caa6-7787-11e7-8e17-d7fee7004c95.png)

**Comment by karmatosed** [comment]
+1 to this. Actually similar UI issues have been plaguing core, its an issue with any long list. Tags could in theory get the same problem with enthusiastic tagging.

**Comment by afercia** [comment]
Yep, haven't mentioned tags but I do use the Theme unit test content where there's a post "Edge Case: Many Tags" which illustrates the potential issue from enthusiastic 🙂  tagging. Not new to Gutenberg though.

**Comment by StaggerLeee** [comment]
Now when you rewrite all, can you make chosing child category select parent category ?

I use jQuery snippet on all websites. It makes me huge problems when Users forget parent category. Typical case is Galleries Archive from Posts, one Post per Gallery.

Now, I am aware it could be undesired cases with it ? If you can point me to a trac discussing it thanks. I dont want to start this off-topic discussion here, it is something I just say in passing. As a big problem I had.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518715072000217)._

**Comment by mtias** [comment]
Closing this as there is filtering built in now and the list is sorted alphabetically.
