### ISSUE TITLE
The classname is not applying on Edit function

### ISSUE THREAD

**Issue by AshiqKiron** [WordPress/gutenberg#21548]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

**Comment by johngodley** [comment]
Can you provide a full description of your problem, including steps how to reproduce it?

**Comment by AshiqKiron** [comment]
Hi @johngodley,

I've managed to resolve the issue, thank you for your comment. This was the solution - https://developer.wordpress.org/block-editor/developers/block-api/block-edit-save/#classname
