### ISSUE TITLE
env: Expose port 3306 of MySQL container

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#21544]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to connect to the MySQL container of @wordpress/env from external. This is similar to [#WP48281](https://core.trac.wordpress.org/ticket/48281).

**Describe the solution you'd like**
The default `docker-compose.yml`should be extended with a `ports` setting for `mysql`. For now I don't think it requires another environment variable to specific the exact port as it can be retrieved by calling `docker-compose port mysql 3306`

**Comment by draganescu** [comment]
Yes +1 to this. I now have to exec bash on the mariadb container and use the CLI mysql client.
