### ISSUE TITLE
Video poster image is ignored when inserted into editor

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#21553]
**Describe the bug**

When a video attachment already has a poster image, it is ignored when the video gets inserted into the editor.

**To reproduce**

1. Go to Media -> Add New and upload a video
2. Click 'Edit' and on the attachment editing screen, select a poster image for the video in the Featured Image meta box
3. Save the video attachment
4. Create a new post and insert the video using the Video block type

Observe that the video's poster image does not get used, and the user has to choose the poster image again using the Select Poster Image button in the block controls

**Expected behavior**

When a video has an existing poster image (featured image) it should be used when that video is inserted into the editor using the video block type.

**Screenshots**

<img width="298" alt="" src="https://user-images.githubusercontent.com/208434/79076044-d8d32b80-7cee-11ea-85b5-b2769a933c52.png">
<img width="179" alt="" src="https://user-images.githubusercontent.com/208434/79076046-dbce1c00-7cee-11ea-8236-3a61215a3d01.png">

**Comment by draganescu** [comment]
i tested this and was able to reproduce it.
