### ISSUE TITLE
Exceeding available space on multisite displayed as unknown error when rest API request is enveloped

### ISSUE THREAD

**Issue by david-binda** [WordPress/gutenberg#21560]
**Describe the bug**
In case a REST API request for media upload is sent with `_envelope=1` param, the response is being returned with 200 status, even when the media upload fails, eg.: due to maximum space available exceeded (on WordPress multisite install). The expected 400 status code is inside the envelope, but is not being recognised by the media upload block/component, and only "An unknown error occurred." message is displayed (vs. "This file exceeds the maximum upload size for this site." displayed when no `_envelope=1` param is used in the request)

**To reproduce**
This might be tricky to reproduce on a local WordPress install, however can be seen in action on a WordPress.com site, where all the image upload REST API calls from Gutenberg are being proxied with `_envelope=1` param being automatically added.

1. Go to your site hosted on WordPress.com and attempt to upload a file exceeding the maximum upload size.
2. See the "An unknown error occurred."

**Expected behavior**
Similar error as is shown when the `_envelope=1` param is not being used. Eg.: vanilla WordPress install. The component might need to try harder to dig into the reponse to check on whether it contains an error message which might be displayed instead of a default one.

**Screenshots**
<img width="907" alt="Screenshot 2020-04-13 at 15 51 27" src="https://user-images.githubusercontent.com/3651036/79125653-c7e1f300-7d9e-11ea-9042-4b2d30a0d23b.png">

The response of the request says:

```
{"body":{"code":"rest_upload_limited_space","message":"Not enough space to upload. 473 KB needed.","data":{"status":400}},"status":400,"headers":{"Allow":"GET, POST"}}
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: chrome
 - Version: 80.0.3987.163 (64bit)

**Additional context**
Reproduced with Gutenberg 7.8.1

**Comment by kathrynwp** [comment]
Hi @david-binda, is this still occurring with the latest version of Gutenberg (13.7.3) and WordPress (6.0.1)? 

> attempt to upload a file exceeding the maximum upload size.

What is the maximum file size that you're referring to?

**Comment by ndiego** [comment]
Hey @david-binda, this issue was reviewed in today's Editor Bug Scrub. Would you be able to confirm if this is still an issue or provide some guidance on how to easily replicate it on a local MS installation? Thanks!

**Comment by jordesign** [comment]
As we've not had any further advice or information on this issue - I'm going to close it out. Please feel free to re-open if it is still an issue - along with any further details.
