### ISSUE TITLE
Noticeable lag using the Button block

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#21567]
**Description**
There is a noticeable lag between interactions when adding buttons to a post. Keystrokes and button additions are delayed. 

It appears to only happen in Chrome (I'm on 81.0.4044.92). In Safari, the interactions are smooth. This issue was also [experienced by](https://github.com/WordPress/gutenberg/issues/21561#issuecomment-613002806) @carolinan.

The console shows the following warning, issued multiple times any interaction in the button block is made:

<img width="505" alt="Screen Shot 2020-04-13 at 5 28 26 PM" src="https://user-images.githubusercontent.com/5375500/79163002-34172380-7dac-11ea-88d0-0f354ae211d4.png">

**Comment by skorasaurus** [comment]
I'm also able to confirm this on Firefox (75), but nothing in the console. 
I first noticed this sometime last week but thought it was my machine (I'm using a vm setup with vvv).

**Comment by youknowriad** [comment]
Good catch here, can you both confirm that the lags only happen when you have the sidebar opened? (the styles on the sidebar). It seems related to the BlockPreview component.

**Comment by skorasaurus** [comment]
Yes, I can confirm that the lag only happens when the sidebar is opened :)
