### ISSUE TITLE
Default button styles are broken when there are no editor styles provided

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#21561]
**Describe the bug**

When a theme does not provide editor styles, buttons are currently appearing broken in the editor.

**To reproduce**

1. Use a theme that provides no editor styles (like the Gutenberg Starter theme)
2. Activate Gutenberg 7.9 RC1 (or `master` currently)
3. Add a button block. 
4. View error. 

**Screenshots**

Current, broken example: 
<img width="302" alt="Screen Shot 2020-04-13 at 12 29 58 PM" src="https://user-images.githubusercontent.com/1202812/79140088-72e5b300-7d85-11ea-9fdf-581e7f297356.png">

Same block, but with the plugin deactivated: 
![Screen Shot 2020-04-13 at 12 53 55 PM](https://user-images.githubusercontent.com/1202812/79140335-d66fe080-7d85-11ea-8e8d-7331b0538ee3.png)

**Version**

Gutenberg 7.9 RC1

**Comment by kjellr** [comment]
cc @youknowriad could this be related to #21266?

**Comment by paaljoachim** [comment]
Testing using the Gutenberg Starter theme: https://github.com/WordPress/gutenberg-starter-theme

Local site using Desktop Server.
Chrome
WordPress 5.4
First I tested with using Gutenberg version 7.8.1.
Button block showed up.

------------

Testing Gutenberg version 7.9.0-rc.1.
I am getting the same result as Kjell did further above.

Result:

Selected button:
![Screen Shot 2020-04-13 at 19 23 03](https://user-images.githubusercontent.com/5323259/79142719-371a1000-7dbc-11ea-9096-d92b814a854e.png)

Selected button block:
![Screen Shot 2020-04-13 at 19 24 06](https://user-images.githubusercontent.com/5323259/79142805-6466be00-7dbc-11ea-962f-1db4d23d75ed.png)

Non selected button block:
Does not show button.

**Comment by skorasaurus** [comment]
can confirm using a build from c3798f141028240312dc7e7d530ad82b38900151

**Comment by carolinan** [comment]
I am also experiencing a delay when typing the button text, both with and without editor styles, that does not happen with 7.8.

Win 10, WordPress 5.4, 7.9.0 RC 1, Chrome Version 81.0.4044.92,

**Comment by mapk** [comment]
I can also confirm this bug using:

Gutenberg 7.8
Twenty Nineteen theme

**Comment by jffng** [comment]
Looks like if `--wp--color-text` is not set, the button text fallbacks to white:

https://github.com/WordPress/gutenberg/blob/c3798f141028240312dc7e7d530ad82b38900151/packages/block-library/src/button/style.scss#L27-L32

**Comment by youknowriad** [comment]
Missed that variable, it should just be removed.
