### ISSUE TITLE
code editor width

### ISSUE THREAD

**Issue by caban13** [WordPress/gutenberg#21576]
I am using WordPress 5.4 (don’t know what version of Gutenberg is included), the question is:
**Why the code editor window is so narrow, only 580 px ?**

It only uses about one third of my screen, cannot be made wider ?
The normal Gutenberg editor uses 1160 px.

**Describe the solution you'd like**
Make the code editor window the same width as normal editor. 
(I think that is set up by the theme, I am not sure of this).

Posted in: https://wordpress.org/support/topic/code-editor-2/
I post here as suggested by @jasmussen

**Comment by jasmussen** [comment]
It seems like the code editor could use some love overall, including making the editing canvas wider as this ticket suggests. I'm the past, adding codemirror was suggested but abandoned, but it still seems like it can be a better code/editing experience by ensuring a good code font of a nice size and line height, that would probably go a long way.
