### ISSUE TITLE
Issue in Custom block: Copy from libre office word or MAC word to Custom block rich text editor

### ISSUE THREAD

**Issue by ronakganatra-multidots** [WordPress/gutenberg#21575]
**Describe the bug**
The issue looks similar to #9719, this issue is fixed in default WordPress blocks like Paragraph, Heading block but still, I am facing it on custom blocks RichEdit component.

**To reproduce**
1. Create a document in Word or LibreOffice, one heading and one paragraph (any text will do). Select all and copy.
2. Add custom Gutenberg block which you created using RIchText component
3. Paste content (Copied from Libreoffice word)
4. See Some styles are applied like: `@page { margin: 2cm } p { margin-bottom: 0.25cm; line-height: 115% }`

**Expected behavior**
Normal as working in other blocks.

**Screenshots**
![Custom block issue](https://user-images.githubusercontent.com/53076115/79221035-bb2ecf00-7e72-11ea-9881-73651d5285d2.gif)

**Desktop (please complete the following information):**
 - OS: Checked on Linux, mac
 - Browser Tried on chrome

**Additional context**
WordPress Version 5.4
Possibly duplicate of #16423, But mentioned full details here.

**Comment by kevin940726** [comment]
Mark as duplicated of #16986
