### ISSUE TITLE
Dropped blocks breaks Reusable Templates

### ISSUE THREAD

**Issue by BlogAid** [WordPress/gutenberg#21579]
The WP 5.4 update removed the Button block in favor of the new Buttons block.

Reusable templates/blocks that had the Button block could not longer be edited or converted to regular templates/blocks.

Before dropping blocks that may be in use, please check to ensure it does not break Reusable templates/blocks. And make clear documentation about what becomes of Reusable templates/blocks that are in use

**Comment by jorgefilipecosta** [comment]
Hi @BlogAid thank you for creating this issue.
I did a test and I was able to insert a reusable block that contains a button block. Maybe the issue just happens under some circumstances.
Could you share the "code/markup" of the block you are not able to insert?
To get the markup we can go to the inserter, open the reusable block section, then press "Manage all reusable blocks", then select the block om the "post list" open that post/block and switch to the code editor view where the code will be visible.
Thank you in advance for any help you may be able to provide!

**Comment by BlogAid** [comment]
Thanks for your quick response. I met with one of my clients today to get the code. She had already fixed the Reusable block and template where the Button block was used. 3 of my clients all reported the same thing - that when they replaced the Button block with the Buttons block they were able to edit the RB block again.

We also had a look at RBs that had been inserted into posts and not converted to Regular Blocks and all of them had updated.

Then we looked at RBs that had been inserted into posts and had been converted to Regular Blocks. They all still had the button block code, without the buttons wrapper and were still working.

So, all is working now, but all Reusable blocks and templates will need to have the Buttons blocks to work.

**Comment by jorgefilipecosta** [comment]
Hi @BlogAid, thank you for the additional information. After continuing the debugging it seems reusable blocks with the old button blocks work, but I'm noticing a bug "the convert to regular block option does not work for the old button blocks". Could you confirm if that's the issue you are facing?

**Comment by BlogAid** [comment]
Yes, that is the issue my clients first reported - no way to convert to
regular blocks if the old button block was in use

**Comment by ndiego** [comment]
Closing out this issue per the conversation in the linked PR: https://github.com/WordPress/gutenberg/pull/21688#issuecomment-1179246917. This issue is a great lesson for any future block updates and the need to consider backward compatibility when it comes to block validation.
