### ISSUE TITLE
Latest Posts block breaks when there are no intermediate image sizes

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/gutenberg#21582]
### **Description**
The "Latest Post" block is not usable if a site has disabled all intermediate image sizes.

### **To reproduce**
1. Add `add_filter( 'intermediate_image_sizes', '__return_empty_array' );` to your theme's functions.php
2. Create a new post & add the "Latest Posts" block.
3. Note the broken block: "This block has encountered an error and cannot be previewed."

### What's happening

```
Error: An error occurred while running 'mapSelect': Cannot read property 'width' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'width' of undefined
    at https://vip.test/wp-includes/js/dist/block-library.min.js?ver=f710d3cc99e7a55a0d6a5418f3cfe33c:9:209846
```
The noted error happens here: https://github.com/WordPress/gutenberg/blob/59324b9a8f95d68330aee110f3814a090a75cb1b/packages/block-library/src/latest-posts/edit.js#L478

Can replicate pretty easily with just this in the console:

```
const { getSettings } = wp.data.select( 'core/block-editor' );
const { imageSizes, imageDimensions } = getSettings();

// Is empty
imageDimensions
```
____________

**Editor version**
- WordPress version: 5.4
- Core WP version of GB, not the extra plugin.

**Comment by Chrico** [comment]
I want to extend this issue with some more information.

----

*imageDimensions*
The `imageDimensions` are set via localized script data here: https://github.com/WordPress/gutenberg/blob/2a5146f6a078ae4ebfb9b0b806daac17674e7a95/lib/compat.php#L67
 
--> Which means: They can actually be empty

----

*defaults*
The `SETTINGS_DEFAULTS`  are not containing `imageDimensions` as well https://github.com/WordPress/gutenberg/blob/2a5146f6a078ae4ebfb9b0b806daac17674e7a95/packages/block-editor/src/store/defaults.js

--> It's actually in 2 positions really possibilty to have *no* `imageDimensions` set without any fallback.

-------

For me it looks like a Bug in Gutenberg itself to rely on data which is not ensured via a default in JavaScript and is not localized when set.

The `latest-posts`-Block should be updated in a way, which does only use images when at least 1 `imageDimension` is set. Otherwhise the "image"-option shouldn't be visible at all.

**Comment by WPprodigy** [comment]
Oh, I missed https://github.com/WordPress/gutenberg/pull/21070. This can be closed!
