### ISSUE TITLE
Improve writing flow by not showing placeholders all the time

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2158]
Let's hide placeholders like "new paragraph" when an element is focused.

At the moment you can get in a pretty weird situation where the interaction seems backwards :)

![ezgif-4-832853d9b3](https://user-images.githubusercontent.com/548849/28875637-85066d42-7796-11e7-92a0-430b15369647.gif)

**Comment by jasmussen** [comment]
Oh, how lovely!

This feels like it truly solves the issue of empty paragraphs, which on the one hand should have placeholder text, on the other hand (in my opinion) should be allowed for oldschool spacing. 👍 👍

**Comment by iseulde** [comment]
#2133 fixes the problem when they don't show.
#2161 hides them on focus.

**Comment by iseulde** [comment]
Merged.

**Comment by mtias** [comment]
Thanks!
