### ISSUE TITLE
apiFetch 'path' works inconsistently if from enqueue vs NPM package

### ISSUE THREAD

**Issue by cliffordp** [WordPress/gutenberg#21592]
**Describe the bug**
I'm using `apiFetch()` outside of the block editor (not sure if that matters).

If I use `"@wordpress/api-fetch": "^3.11.0"`, the string I pass to `path` is taken literally, not prepending with `/wp-json` (or `/?rest_route=/`), which causes a 404.

However, if I enqueue `'wp-api-fetch'` and then use it via `const { apiFetch } = wp;`, it's no longer a 404, as if it _is_ prepending the correct bit of `path`.

**To reproduce**
`npm install @wordpress/api-fetch --save`

`import apiFetch from "@wordpress/api-fetch";`

[instead of]

`const { apiFetch } = wp;`

**Expected behavior**
For `path` to work the same, regardless.

**Editor version (please complete the following information):**
- WordPress version: `5.3.2`
- If the Gutenberg plugin is installed, which version is it? `N/A`

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome
 - Version 81.0.4044.92

**Comment by johngodley** [comment]
I think you may be missing the root URL middleware, shown here:

https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch

The one used via `wp` will already have this applied.

**Comment by cliffordp** [comment]
Interesting! I definitely didn't get that from the documentation you linked to. I assumed using the NPM package would let me use the code snippet out of the box, just how it is documented. All these little gotchas has been difficult to develop confidently (is it secure?) and rapidly (copy/paste to start).

This as an example: why does the doc recommend (prefer/advise?) that I use NPM but then the code snippet doesn't correspond with that? Why wouldn't the documentation suggest `const { apiFetch } = wp;` instead?

I appreciate your help and just wish all this was more polished. I'm sure _someday_ but oof it's not easy to get started yet.

**Comment by johngodley** [comment]
A lot of the components are designed to be used outside of Gutenberg so the npm route is generally shown.

I've created a new issue to fix the documentation example. Marking this as closed.

**Comment by cliffordp** [comment]
awesome, tyvm! (#21644)

Is there any security concern if not using the middleware? I thought that's where the built-in nonce happens so would think _yes_.

**Comment by johngodley** [comment]
What kind of security concern? If you are using it outside of the block editor then it's up to you to ensure that you use whatever is appropriate for the kind of request you are making, both in the client and on the server.
