### ISSUE TITLE
The navigation page replaces blocks when saving unnecessarily, causing selection loss

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21594]
**Describe the bug**
Discovered in  #21340

When saving a navigation menu, every block is recreated with a new client id. This can cause an issue with block selection suddenly being lost.

**To reproduce**
1. Use an existing menu.
2. Inspect the HTML of the first navigation link block
3. Take note of the client id of the (id attribute of the `li`) of the block
4. Add a new menu item at the end of the blocks
5. Save blocks. Observe that block selection was lost.
6. Inspect the first navigation link block again. Notice it has a new client id

**Expected behavior**
The block is not replaced unless it needs to be. Block selection is retained when saving.

**Comment by talldan** [comment]
I think this is still happening, but it's hard to pin down exactly what the issue is.

On first save there's a strange issue where when saving all the blocks disappear and then re-appear one-by-one.

I've also experienced an issue where when trying to edit a label and saving, the edits are undone. 

In both situations selection is lost.

**Comment by adamziel** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/22739
