### ISSUE TITLE
PluginDocumentSettingPanel initialOpen value

### ISSUE THREAD

**Issue by OksanaRomaniv** [WordPress/gutenberg#21601]
Hello,

Is it currently possible to render PluginDocumentSettingPanel in the initially closed state? It appears the initialOpen or open attributes don't have any effect on the rendering and the panel if rendered open by default.

**Comment by johngodley** [comment]
@OksanaRomaniv I don't see either `initialOpen` or `open` as attributes in [PluginDocumentSettingPanel](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/sidebar/plugin-document-setting-panel/index.js) 

Is that the component you are referring to? There is an `opened` and `isEnabled` property, which may be what you are looking for.

**Comment by talldan** [comment]
Closing as this seems to have been answered.

**Comment by bagusindrayana** [comment]
not work even i fill `opened` to true

`<PluginDocumentSettingPanel
        name="mycustom-panel"
        title="Tips"
        className="mycustom-panel"
        opened={true}
        onToggle={true}
        isEnabled={true}
        initialOpen={true}>
        this is tips to write better content
    </PluginDocumentSettingPanel>`

**Comment by amooreTO** [comment]
The following attributes don't seem to have any effect:

```
<PluginDocumentSettingPanel
	name="my-custom-panel"
	title="Custom Panel"
	isEnabled={ false }
	opened={ false }
>

```
The panel is always in an open state when the editor loads.
