### ISSUE TITLE
Are messages obvious enough?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2162]
We may need some testing to prove this, but as I was going through using Gutenberg today it struck me how easy it is to miss messages. For example:

![2017-08-02 at 18 43](https://user-images.githubusercontent.com/253067/28886763-7fa3d350-77b2-11e7-98ee-824f17adabef.png)

There is now a lot going on in this screen. That tiny, quiet 'Post published!' is awfully quiet and easy to not see.

**Comment by annaephox** [comment]
Hi! Had a think about this, and I wonder if it's the obviousness (is that a word?) or is it the placement of the message? If I just clicked Publish, my eye is in the top right corner, next to the lovely blue publish button. Perhaps creating a post status indicator up here would make the message more noticeable, for example:

![postpublished 001](https://user-images.githubusercontent.com/25762760/28905650-5323754e-7855-11e7-857d-2f4d80fa3a8d.jpeg)
![postpublished 002](https://user-images.githubusercontent.com/25762760/28905651-536961bc-7855-11e7-8a39-4a99b79e0b39.jpeg)

**Comment by karmatosed** [comment]
@annaephox interesting idea for placement. A few observations on what you suggest:

- What happens when that panel is closed? This is an option but messages still need to appear.
- Is removing the background color possibly not making the messages even less obvious? Although for those with color complications it of course won't matter.
- Is the user eye on the side panel? I feel the side has similar issues of vision line. I also think there may be issues because of how much content noise there is in that panel - easy to miss.

All those comments have a lot of 'thought' in it and some personal assumptions. Maybe we need a few variations to see. I really think what we have could work with some improvements to existing, without moving it.

**Comment by karmatosed** [comment]
More fuel for this are error messages:

![2017-08-03 at 15 14](https://user-images.githubusercontent.com/253067/28926027-814a775c-785e-11e7-907d-6a8f0d96a590.png)

**Comment by karmatosed** [comment]
I am closing this to focus on what feedback we get from tests. We are moving into a lot of usability testing and this will show ways forward.
