### ISSUE TITLE
New Button CSS breaks my website layout

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#21624]
The recent changes to simplify the button block html breaks the website styles. Simpler html is a good thing but the way it's been done isn't so hot.

You can see an example here from one of my themes:
<img width="732" alt="Screenshot 2020-04-15 at 19 44 32" src="https://user-images.githubusercontent.com/1004130/79376929-cf49fd80-7f52-11ea-80a3-c18c6f54d6a3.png">

Or this one from TwentyTwenty:
<img width="717" alt="Screenshot 2020-04-15 at 19 46 08" src="https://user-images.githubusercontent.com/1004130/79376937-d3761b00-7f52-11ea-94ac-344637315173.png">

The release post said some themes may need to change their styles but I don't think this will help. If you change the CSS then the existing content on every website using that theme will need to be updated as well.

If you have buttons on a site using TwentyTwenty then you will need to update every button else the div wrapping the link will get the buttons styles (which is what is shown in those screenshots).

The problem is that the default theme button styles are being applied to `.wp-block-button` which on old content is the div wrapper and not the button/ link itself.

One possible fix would be to change the block styles so that the style is applied to `wp-block-button__link` then only the link will be affected and we won't have styles applied to the div containers.

**Comment by youknowriad** [comment]
> the existing content on every website using that theme will need to be updated as well.

That's one of the reasons we kept the same class applied previously on the links, if you just use this class to style the blocks, it will work properly in both versions. Did you try that?

**Comment by youknowriad** [comment]
Oh I think I understand what you're saying now, you want the WordPress provided styles to apply ton the link classname too instead of `wp-block-button`, I think that makes sense.

**Comment by BinaryMoon** [comment]
Yeah - on existing content the styles are being applied to the div that wraps the link rather than the link itself. If you change the default styles so they target wp-block-button__link then it 'should' work on old and new content.
