### ISSUE TITLE
Div around Image block in Gutenberg 7.9

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/gutenberg#21628]
Hey, I just updated to the new version and noticed that the Image block is now wrapped in a div:

![PixelSnap 2020-04-15 at 23 22 25](https://user-images.githubusercontent.com/39319746/79390590-43df6500-7f70-11ea-8db6-6f1ed51ea4df.png)

I assume this is a bug?

**Comment by jasmussen** [comment]
I believe it is a result of efforts to actually reduce and simplify the DOM in the editor to better match the frontend. Per the discussion in https://github.com/WordPress/gutenberg/pull/21167/files#r398432208, there's still some work to do, and it has to do with refactoring how alignments work. In that vein, I'm going to close this ticket in favor of #20650, which has been created exactly to address this and related issues. 

Thanks for the ticket!

**Comment by dnnsjsk** [comment]
Why doesn't it have any classes though? How am I supposed to target this block now?
