### ISSUE TITLE
Plugin sidebar no longer pinned by default

### ISSUE THREAD

**Issue by IreneStr** [WordPress/gutenberg#21635]
**Describe the bug**
Up until 10 days ago, the Yoast SEO sitebar was pinned automatically on activation. While the [implementation on our side](https://github.com/Yoast/wordpress-seo/blob/422df565b8285fedf23d65add15db0679e8a0ba5/js/src/edit.js#L119-L139) is unchanged, this is no longer the case. 

**To reproduce**
1. Checkout the Gutenberg master branch.
2. Activate Gutenberg.
3. Install and activate Yoast SEO 13.5.
4. Start creating a new post in an incognito browser (to make sure all settings are default)
You see that Yoast is not pinned anymore:
<img width="298" alt="Screenshot 2020-04-06 at 08 13 55" src="https://user-images.githubusercontent.com/19681708/78527992-9c7b6900-77de-11ea-9223-b259f6180442.png">

5. Click Tools and see that Yoast appears in Plugin section:
<img width="277" alt="Screenshot 2020-04-06 at 08 14 36" src="https://user-images.githubusercontent.com/19681708/78528039-b9b03780-77de-11ea-9c9f-36e6cc3d50fc.png">

6. Click Yoast, and you get Yoast sidebar, but it is still not pinned in the toolbar:
<img width="308" alt="Screenshot 2020-04-06 at 08 15 23" src="https://user-images.githubusercontent.com/19681708/78528168-0eec4900-77df-11ea-8747-0f1bd548b59c.png">

7. Click to pin ("star") on top, then you get Yoast sidebar pinned in the toolbar:
<img width="317" alt="Screenshot 2020-04-06 at 08 18 18" src="https://user-images.githubusercontent.com/19681708/78528239-317e6200-77df-11ea-8599-fb3e66be3357.png">

**Expected behavior**
Plugin sidebars to be pinned by default on activation.

**Screenshots**
See above

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? master

**Desktop:**
 - OS: independent of OS
 - Browser: all browsers
 - Version: N/A

**Smartphone:**
 - Device: independent of device
 - OS: independent of OS
 - Browser: all browsers
 - Version: N/A

**Additional context**
- @afercia pinpointed this PR as the likely culprit: https://github.com/WordPress/gutenberg/pull/20698
- In the core editor chat of April 15, it was confirmed by @gziolo that this is a bug in the Gutenberg and the implementation on our side (see above) is correct.

**Comment by afercia** [comment]
See also https://github.com/WordPress/gutenberg/issues/21506

**Comment by manooweb** [comment]
Hello,
I reproduce the same issue with our Polylang Pro plugin sidebar and Gutenberg 7.9.0 installed.
No issue with Gutenberg 7.8.1 or WP 5.4 only.
Regards
