### ISSUE TITLE
Improve usability and do not default to uncategorized

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2163]
This may be opening a lot of core-side discussion, so I am aware of that in suggesting this. I realise also the way this happens is what core does right now. However, I would like to open discussion on how useful having 'uncategorized' is for users. Could we just have no default category?

![2017-08-02 at 18 45](https://user-images.githubusercontent.com/253067/28887016-77612b42-77b3-11e7-9ea3-f3a548209bf5.png)

**Comment by melchoyce** [comment]
+1 million. Though, this probably should be a core ticket.

**Comment by karmatosed** [comment]
Good idea, if we can change it there and Gutenberg gains it - even better! I added it to https://core.trac.wordpress.org/ticket/36228 as this felt right over a new ticket. I do wonder if this is controlled in Gutenberg we could speed along that as a fix for WP here.

**Comment by nylen** [comment]
Kill it :knife:

I am pretty sure "default category" doesn't play nice with the REST API anyway.

Should we still allow people to select Uncategorized as a category? This would also be a bit weird.

**Comment by melchoyce** [comment]
> Should we still allow people to select Uncategorized as a category? This would also be a bit weird.

In an ideal world it would be eliminated entirely, IMO.

**Comment by karmatosed** [comment]
+1 🔥 it :)

**Comment by karmatosed** [comment]
I've created a core ticket, so lets tackle this within core for now.
