### ISSUE TITLE
Build Tooling: Configure Webpack to skip Node polyfills

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21647]
Previously: #13386

**Context:**

Webpack will no longer polyfill Node modules automatically in the upcoming v5 release:

https://github.com/webpack/changelog-v5/blob/master/README.md#automatic-nodejs-polyfills-removed

**Task:**

Configure default Webpack configurations to disable `node` polyfills as `false`:

https://webpack.js.org/configuration/node/#node

**Motivation:**

Simplify a future upgrade to Webpack 5 by avoiding to put ourselves in the situation of migrating away from the automatic polyfills, by forbidding their introduction in the first place.

**Future Considerations:**

If we choose to upgrade to Webpack 5 before this task is implemented, the work would no longer be necessary.

**Comment by gziolo** [comment]
The up to date link to the related document from webpack is:
https://v4.webpack.js.org/configuration/node/#node

Defaults in v4:

```
module.exports = {
  //...
  node: {
    console: false,
    global: true,
    process: true,
    __filename: 'mock',
    __dirname: 'mock',
    Buffer: true,
    setImmediate: true

    // See "Other node core libraries" for additional options.
  }
};
```

**Comment by gziolo** [comment]
I tried to go with `node: false` in #22312 but it isn't straightforward. Should we maybe update this issue to target webpack v5 upgrade instead?

**Comment by aduth** [comment]
> Should we maybe update this issue to target webpack v5 upgrade instead?

Ultimately I think that should be the goal. By this, do you mean to put together a pull request using the Webpack 5.0 beta? Just to get ready for the impending release, or to actually start running on the beta?

**Comment by gziolo** [comment]
> Ultimately I think that should be the goal. By this, do you mean to put together a pull request using the Webpack 5.0 beta?

I was thinking about updating the title and description, for now, 😄 Opening PR with webpack v5 branch early might be a good idea as well. I would prefer to avoid running on beta 🤣

**Comment by aduth** [comment]
> I would prefer to avoid running on beta 🤣

Likewise. Having the pull request ready though, it may save us time down the line, and help identify all the possible incompatibilities.

**Comment by gziolo** [comment]
I closed #22312 as it isn't as simple as I anticipated. I hope it's going to be easier to address as part of webpack v5 with their official migration guide. Still, this PR is a good reference to look at when trying to land changes related to how Node polyfills are handed.

**Comment by gziolo** [comment]
Webpack 5 is out now:
https://webpack.js.org/blog/2020-10-10-webpack-5-release/

To v5 from v4 migration guide might be useful as well:
https://webpack.js.org/migrate/5/

**Comment by gziolo** [comment]
@jsnajdr is working on webpack 5 upgrade in https://github.com/WordPress/gutenberg/pull/26382 which is going to address this issue one way or another.
