### ISSUE TITLE
[Navigation] enqueue_block_editor_assets action is not fired

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#21648]
**Describe the bug**
I am attempting to follow this guide to add a button to the menu item toolbar:

https://developer.wordpress.org/block-editor/tutorials/format-api/1-register-format/

It appears that the "enqueue_block_editor_assets" action is not fired on the _/wp-admin/admin.php?page=gutenberg-navigation_ page.

**To reproduce**
1. Add the following to a plugin or your theme:

```
function my_custom_format_enqueue_assets_editor() {
    die("got here");
}
add_action( 'enqueue_block_editor_assets', 'my_custom_format_enqueue_assets_editor' );
```

2. Visit _/wp-admin/admin.php?page=gutenberg-navigation_

**Expected behavior**
I would expect to see the message "got here", but I do not as the action is not fired on the new Navigation page. If I edit a page or post I see the "got here" message.

**Editor version:**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 7.9

**Comment by noisysocks** [comment]
Possibly related to https://github.com/WordPress/gutenberg/pull/25826.

We likely need to add this code which is on `widgets-page.php` to `navigation-page.php` as well:

https://github.com/WordPress/gutenberg/blob/7f1fac93ffcfc8842b651b4448d301fb61caddcf/lib/widgets-page.php#L136-L144
