### ISSUE TITLE
Image block fails to revert to 'edit visually' after editing in 'edit as HTML'

### ISSUE THREAD

**Issue by adamdkirk** [WordPress/gutenberg#21640]
**Describe the bug**
When I convert an image block to 'edit as HTML' to add 'nofollow' to a link in the caption, the three dot handle for the block disappears. I am no longer able to move or delete the block or revert it back to 'Edit Visually'

**To reproduce**
1. Add an image block and insert an image
2. Add a caption which contains an external link
3. Select 'open in new tab' rocker switch for external link
4. Select 'Edit as HTML' from 3-dot menu for block
5. Add 'nofollow' to the rel="noreferrer noopener" code
6. Error occurs, 3-dot handle has gone

**Expected behavior**
I expect the block behavior to remain unaltered, i.e. I can revert back to visual editing.

**Screenshots**
n/a

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: chrome
 - Version: 80.0.3987.163

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
- n/a

**Comment by talldan** [comment]
@adamdkirk I'm not able to reproduce this issue. I can still see the menu after editing the HTML:
<img width="460" alt="Screenshot 2020-04-20 at 12 02 34 pm" src="https://user-images.githubusercontent.com/677833/79712978-04fa3800-82ff-11ea-9b18-54945c69d18a.png">

Do you have any plugins installed that might be causing the issue?

**Comment by talldan** [comment]
I was able to reproduce this when testing issue #21722 using the quote block, which seems like the same problem.

Lets track this issue on #21722 from now on.
