### ISSUE TITLE
dependency-extraction-webpack-plugin: `wp_register_script` doesn’t work with camel-cased script names

### ISSUE THREAD

**Issue by stephencottontail** [WordPress/gutenberg#21659]
**Describe the bug**
When using `@wordpress/dependency-extraction-webpack-plugin`, if a block depends on a script with a camel-cased name (e.g. `apiFetch`), the script doesn’t load when registered via `wp_register_script()`.

**To reproduce**
I created a test plugin at https://github.com/stephencottontail/reduced-test-case to demonstrate the issue. As it is now, `plugins/reduced-test-case/dist/block.js` does not load in the editor. If I manually edit `dist/block.asset.php` to change `wp-apiFetch` to `wp-api-fetch`, then the script does load in the editor.

**Expected behavior**
I expected my script to load in the editor

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Comment by gziolo** [comment]
https://github.com/stephencottontail/reduced-test-case/blob/40775f63755cba78efa9c8f11e889ed1555e5012/src/block.js#L1

The correct name of the package is `@wordpress/api-fetch`. See it on npm: 
https://www.npmjs.com/package/@wordpress/api-fetch

Can you check if it solves your issue?

**Comment by stephencottontail** [comment]
That does solve it,  thanks. It gets a little confusing remembering when you’re supposed to camel case and when not to

**Comment by gziolo** [comment]
I can see that being an issue but we can’t do much about it 🙁
