### ISSUE TITLE
Button / button link wrapper merged in editor

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#21657]
**Describe the bug**
In the editor the button element and button link element are both one element which has both the  `wp-block-button` and `wp-block-button__link` classes. In frontend however, the button is rendered nested, with a `wp-block-button` element and a `wp-block-button__link` child element. This causes problems with button related styles and complicates them because now there have to be two different selectors used for a button style.

**To reproduce**
1. Open editor with at least one style available for `core/button` block.
2. Ensure a `core/button` block is placed in the editor.
3. Select the button block and assign it a button block style.
4. Inspect the button block DOM and notice that `wp-block-button` and `wp-block-button__link` classes are assigned to same DOM element, there is no separate child `wp-block-button__link` element.
5. Save the post/page and view it on the frontend.
6. Notice that the block on the frontend is rendered with `wp-block-button` element and child `wp-block-button__link` element, existing block styles probably won't work anymore, either in backend or in frontend without adjusting them (and making them more complicated in the process).

**Expected behavior**
Same DOM structure for `core/button` block in backend and frontend.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 7.9.1

This new issue has been noticed after the last update of the Gutenberg plugin.

**Comment by youknowriad** [comment]
Hi there! there has been a markup change for the button block, but both in the frontend and the editor, the wrapper element has been removed. 

More details about the change has been highlighted on the release post. Can you check again your frontend and see whether the button show as a single link element? https://make.wordpress.org/core/2020/04/15/whats-new-in-gutenberg-15-april/

**Comment by strarsis** [comment]
@youknowriad: 
Frontend DOM HTML (after saving the editor):
```html
<div class="wp-block-buttons aligncenter">
  <div class="wp-block-button is-style-arrow"><a class="wp-block-button__link" href="#url">Buttontext</a></div>
</div>
````

Backend DOM HTML:
```html
<div class="wp-block-buttons">
    <div class="block-editor-inner-blocks">
        <div class="block-editor-block-list__layout">
            <div aria-label="Add text…" role="textbox" class="wp-block-button is-style-arrow wp-block block-editor-block-list__block is-selected rich-text block-editor-rich-text__editable wp-block-button__link" aria-multiline="true" contenteditable="true" id="block-<some id>" data-block="<some id>" data-type="core/button" data-title="Button" tabindex="0" style="white-space: pre-wrap; transform-origin: center center; transform: none;">Buttontext</div>
            <div tabindex="-1" class="block-list-appender">
                <button type="button" class="components-button block-list-appender__toggle block-editor-button-block-appender" aria-label="Add Button"><span class="components-visually-hidden">Add Button</span>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" role="img" aria-hidden="true" focusable="false">
                        <path d="M16 11.2h-3.2V8h-1.6v3.2H8v1.6h3.2V16h1.6v-3.2H16z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
</div>
````

**Comment by youknowriad** [comment]
I believe your frontend markup was probably generated using an old Gutenberg version, you can try to edit your reusable block/pots and save it again and check the markup.

**Comment by youknowriad** [comment]
> The button block in editor/backend contains a single div that has both classes,

That's expected even if the frontend is a "a" because RichText/contenteditable only supports "block" elements properly, I'm tempted to try to fix this somehow but it has always been the case.

**Comment by strarsis** [comment]
@youknowriad: Right, I re-saved everything. So the underlying issue is that a special element is used in backend, hence the classes are used for the same element. Well, I adjusted the styles to select for both DOM structures, frontend and backend, so if it is as it is, it would be also OK.

**Comment by youknowriad** [comment]
> So the underlying issue is that a special element is used in backend, hence the classes are used for the same element

No, let me clarify that now the classes should be used on a single element both for backend and frontend. That element is an "a" on frontend and a "div" on backend. That should be the only difference. If that's what you're saying, I think that's expected and we should close the issue.

**Comment by strarsis** [comment]
@youknowriad: So the reason was that the reusable block was updated but not the pages/posts that include it. I am still advocating for some kind of intermediate render layer and Gutenberg blocks that don't store any HTML but only the pure content. 😸 Anyway, after also updating the pages/posts the markup is consistent on back- and frontend now.

**Comment by strarsis** [comment]
Alright, the transition can be hard sometimes because there is one element (wrapper) less than before... But on the other hand the styles are simpler now.

**Comment by youknowriad** [comment]
I agree, this was a tough decision to make and we're still monitoring feedback and see how to address issues before the next WP 5.5.

**Comment by strarsis** [comment]
@youknowriad: Well, I figured out a wrapping mechanism on frontend (PHP) and backend (JS), so adding temporary wrappers by theme is no issue for me. I think this kind of mechanism should be added to Gutenberg - or an intermediate layer - which means the Gutenberg blocks are stored as XML entities/JSON/data-attributes or whatever in markup and are transformed to DOM in frontend and backend by some extra layers.
Using this approach themes can easily add/remove their own layers + decorative elements without ever changing the underlying content and the need for updating each and every reusable block/post/page.

**Comment by strarsis** [comment]
Frontend/editor wrapper:
```js
import classnames from 'classnames/dedupe';

const { createHigherOrderComponent } = wp.compose;
const { addFilter } = wp.hooks;

/**
 * Button block wrapper in editor
 *
 * @param {Object} settings Settings for the block.
 * @see https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/edit.js#L33
 *
 * @return {Object} settings Modified settings.
 */
const wrapButton = createHigherOrderComponent( ( BlockEdit ) => {
    return function wrapped(props) {
        if (props.name !== 'core/button') {
            return <BlockEdit {...props} />; // skip
        }

        return (
          <div className={ classnames(
            'wp-block-button__wrapper',
            props.attributes.className)
          }>

            <BlockEdit {...props} />
          </div>
        );
    };
} );
addFilter( 'editor.BlockEdit', 'core/button', wrapButton );
````

Backend wrapper:
```php
/**
 * Button block wrapper in backend
 */
function gutenberg_wrap_button(string $block_content, array $block) {
    if($block['blockName'] !== 'core/button') return $block_content; // skip

    $classes = 'wp-block-button__wrapper' . ' ' . $block['attrs']['className'];

    return '<div class="' . $classes . '">' .
                $block_content .
            '</div>';
}
add_filter( 'render_block', 'gutenberg_wrap_button', 10, 2 );
````
