### ISSUE TITLE
Stop adding paragraphs on 'enter' when my first paragraphs is empty.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#21668]
**Is your feature request related to a problem? Please describe.**
If you add a paragraph block and press enter multiple times, you get a very confusing view:

![Multiple paragraphs](https://d.pr/i/EbyQ9l.png)

This view makes sense if you are 'thinking' in terms of blocks (and as a developer) but it really isn't intuitive nor does it follow any conventions elsewhere. As an author I expect to be making room in my document by pressing enter, not instantiating new blocks (that's a technical feature).

**Describe the solution you'd like**
If I add a paragraph tag, and press enter, I should not see all the placeholders. It should appear as if it's one continuous block.

**Comment by jasmussen** [comment]
Thanks for the issue!

Begin able to create multiple paragraphs if that's what you really want feels fair enough. But I do agree that the repeated text above is not very helpful. You'll also find others agreeing with that in #10051, including some mockups and discussion on how to address that. So I'll close this one in favor of 10051 — if you like, you can subscribe to that ticket to receive updates when it gets addressed!
