### ISSUE TITLE
Block Library: Navigation: Refactor to use render_callback

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21660]
Previously: #21467, #19991

**Context:**

#21467 enables support for `render_callback` to receive the block instance as an argument. This had been needed for the Navigation block in referencing inner blocks, originally implemented in #16796 as an extra argument of `render_callback`, proposed for core enhancement at [Trac#48104](https://core.trac.wordpress.org/ticket/48104), then ultimately reverted to an alternative (admittedly more cumbersome) approach using filtering in #19991.

**Task:**

Revise the implementation of Navigation block to use `render_callback`, using the `$block` argument to reference inner blocks.

**Motivation:**

This is largely for code quality and maintainability of the block, since using the `render_block` filter is an unnecessarily complex means to customize the render output of a block, vs. the first-class `render_callback` callable setting of a block.

**Comment by talldan** [comment]
I can handle this as part of https://github.com/WordPress/gutenberg/pull/21075.

**Comment by talldan** [comment]
Closed by #21075
