### ISSUE TITLE
Build Tooling: Bring back Storybook deploy to GitHub pages

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#21669]
**Is your feature request related to a problem? Please describe.**

Related commit from @aduth:
https://github.com/WordPress/gutenberg/commit/edc4ac62abb3702e525d46476fa342f11e82b0fc#diff-354f30a63fb0907d4ad57269548329e3

> GITHUB_TOKEN is suspected cause of recent build failures if invalid. This is the only known usage. Plan is to remove this build stage, then remove the configured token from settings.

It's been over 3 weeks since we don't update https://wordpress.github.io/gutenberg/.

**Describe the solution you'd like**

Bring back integration to make it easy to explore available components or play with the block editor in isolation.

**Comment by aduth** [comment]
@youknowriad Do you recall the permission scopes necessary for the token?

**Comment by youknowriad** [comment]
@aduth https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token

It seems public_repo or repo

**Comment by aduth** [comment]
Hm, I might try to look briefly into whether this would be easy enough to set up using GitHub Actions. I have a feeling it would be, and might have some advantages:

- Action secrets are maintained as [settings of the repository](https://github.com/WordPress/gutenberg/settings/secrets), not by an individual user. The latter has an additional downside of not being repository-specific. I don't love the idea of tokens floating around that give access to all of my repositories.
- A GitHub Action to maintain GitHub Pages? Seems a "good fit", though I guess practically speaking there's probably not a whole lot of difference.

**Comment by youknowriad** [comment]
I'm almost certain you'd find some pre-made Github or community actions to do that

**Comment by youknowriad** [comment]
Exemple https://github.com/marketplace/actions/github-pages-action

**Comment by aduth** [comment]
Oh yes, I didn't plan to do anything custom.

**Comment by aduth** [comment]
This limitation appears both frustrating and blocking a direct use of the GitHub action:

https://github.com/marketplace/actions/github-pages#limitation

Related: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/26869

>The `GITHUB_TOKEN` that is provided as a part of GitHub Actions doesn't have authorization to create any successive events, such as GitHub Pages builds. So while you can push to the `gh-pages` branch using the `GITHUB_TOKEN`, it won't spawn a GitHub Pages build. You'll need to create a personal access token and supply it to your GitHub Action as a secret. 

I'm not personally comfortable to create a personal access token for this purpose. If someone else would like to, or if we can create a new custom user with access only to this repository, it may be fine as alternative.

**Comment by gziolo** [comment]
There is also https://github.com/marketplace/actions/github-pages-action

> Notes: Actually, the `GITHUB_TOKEN` works for deploying to GitHub Pages but it has still some limitations. For the first deployment, we need to select the `gh-pages` branch or `master` branch on the repository settings tab.

**Comment by aduth** [comment]
The wording is a bit confusing to me. If it's of the sort of "set up once and done", it'd be fine. It's contrary to what I would expect based on the previous support conversation, which seems to imply that the token fails to trigger a pages build, where builds are _per-commit_ and thus still relevant even after a first deployment. I guess it wouldn't hurt to try.

**Comment by aduth** [comment]
Experimenting with the aforementioned action at #22443.
