### ISSUE TITLE
Block Library: Post Title: Title should be editable

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21663]
Previously: #21467 (https://github.com/WordPress/gutenberg/pull/21467#discussion_r405213292), #19572

**Context:**

#21467 made minimal enhancements to the Post Title block to show a live title of the post. Ideally, this title block should be editable and mirror to and from the corresponding post entity.

There is prior art in #19572 for this, where the title was implemented as `RichText`.

**Task:**

Implement an editable field for the Post Title block.

**Implementation Specifics:**

The title inherits many of the same behaviors of a heading block, and may warrant some refactoring to better support a feature parity.

See also:

- #21087 
- #15450

**Comment by ntsekouras** [comment]
Implemented here: https://github.com/WordPress/gutenberg/pull/27240
