### ISSUE TITLE
Improve current revisions flow to and from Gutenberg

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2166]
Whilst #2165 looks at what Revisions could look like beyond v1, what can we do to improve the current flow as you go in and out of Gutenberg? This should be easy wins, currently the flow takes you out of Gutenberg and you end up back at the old editor.

**Comment by annaephox** [comment]
I think this video captures the above:

- Start in Gutenberg
- Look at revisions
- Select a revision
- End up back in old editor

![revisions](https://user-images.githubusercontent.com/25762760/28904221-a67c5cdc-784c-11e7-8989-bc8a7035a85f.gif)

What's interesting is that now if I save the file in the old editor, and open back up in Gutenberg, it looks like this:

![screen shot 2017-08-03 at 1 02 54 pm](https://user-images.githubusercontent.com/25762760/28904252-d44c9500-784c-11e7-9a37-27c703b13158.png)

**Comment by karmatosed** [comment]
Thanks for the video of this. The saving and then mangling of the post is a real pitfall for a user there.

**Comment by StaggerLeee** [comment]
Keep right sidebar when in revisions screen ?
For me personally it always felt as I left editor, post edit screen, TinyMce, when I go inside revisions screen.

**Comment by paaljoachim** [comment]
I was inspired by Stagger Lees comment so I made a wireframe based on the idea of having revisions show up in the content area. I have no idea if something like it would work. But it might inspires additional ideas as to how to handle the ui for revisions.

![gutenberg-revision](https://user-images.githubusercontent.com/5323259/29480030-dd063dce-8475-11e7-816e-35d21b553b32.jpg)

**Comment by karmatosed** [comment]
@paaljoachim an interesting approach. I think my initial thoughts are this is adding a bad UI into a good one we've improved. If we're honest, the current implementation of revisions is 'lacking' (I was involved in it so feel ok saying that). My concern is with squeezing all it's problems into the editor like this, we are not benefiting the user, we are causing more issues.

What I think would be best is just to have a more elegant path. I'll do some sketching this week and drop ideas in. Anyone else is also welcome to join in on that.

**Comment by StaggerLeee** [comment]
@karmatosed, do you plan to remove Ajax support from Gutenberg ? Now with React, that is whay I am asking.
Just to not lose time on Ajax ideas for revisions.

**Comment by karmatosed** [comment]
At this point I'd advise we think of easy to do ideas, none of those should involve redoing or doing any scripting.

**Comment by karmatosed** [comment]
As we have a 'return to editor' right now and it works now, let's close this up and consider iterations later. We have a closed flow now that's important.
