### ISSUE TITLE
E2E Test Utils: Add new openPreviewPage utility

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21678]
Previously: https://github.com/WordPress/gutenberg/pull/21467#discussion_r409977155

**Context:**

In end-to-end tests, it can often be useful to make assertions against the actual front-end content display of a published or previewed post.

This already occurs in two tests:

- [`packages/e2e-tests/specs/editor/various/preview.test.js`](https://github.com/WordPress/gutenberg/blob/0336a3417024537a58cab3114cfbb12a5adabc83/packages/e2e-tests/specs/editor/various/preview.test.js)
- [`packages/e2e-tests/specs/editor/plugins/block-context.test.js`](https://github.com/WordPress/gutenberg/blob/29c6a1b2a61539406a4d206b53a75722fc36d6eb/packages/e2e-tests/specs/editor/plugins/block-context.test.js)

**Task:**

1. Create a new `openPreviewPage` utility in `@wordpress/e2e-test-utils`
2. Update existing tests above to use this utility

**Implementation Notes:**

The utility may or may not make sense to port directly from these implementations.

Notably, managing an extra preview page tab adds some additional overhead in managing tabs, especially "bring to front" and "close" clean-up tasks. These are not particularly difficult to implement using Puppeteer APIs, but they must be known to be performed, and as such introduce a risk for human error. A good utility may seek to try to remove the need for these considerations.

For example, one of the following _may_ be an improvement:

- Refactor to preview the page in the same tab.
- Create some convention for "scoping" evaluation, in a way similar to [Puppeteer's `page.evaluate`](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args), which has the advantage of: The utility can manage clean-up tasks after the evaluation has completed.

**Comment by Mamaduka** [comment]
This was fixed via #26355.
