### ISSUE TITLE
Margin right unique button

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#21675]
In button block even if there is only one button we still have

.wp-block-buttons .wp-block-button.wp-block-button {
    display: inline-block;
    margin-right: 8px;
    margin-bottom: 8px;
}
could we have ?
.wp-block-buttons .wp-block-button.wp-block-button:only-child {
 margin-right: 0px;
}

**Comment by pascalknecht** [comment]
Yes please. This style also breaks centering in the backend as then there is only `margin-left: auto` but `margin-right: 8px` which breaks the centering.

**Comment by youknowriad** [comment]
closed by #23319
