### ISSUE TITLE
Add ability to transform between navigation styles

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21673]
There are 2 navigation blocks in a sense with the vertical and horizontal styling. It doesn't seem like you can easily transform between them, this would be a great enhancement to add. Currently, you can only transform to a group:

![image](https://user-images.githubusercontent.com/253067/79550320-17bb0580-8090-11ea-98bb-10bbe98165f2.png)

**Comment by mtias** [comment]
It's already on the roadmap: https://github.com/WordPress/gutenberg/pull/21296#issuecomment-608118280

**Comment by karmatosed** [comment]
@mtias ah thanks, sorry couldn't find an issue so dove into making one, happy to close this one up.
