### ISSUE TITLE
Styling Bug: Aligning content in editor

### ISSUE THREAD

**Issue by Sven74Muc** [WordPress/gutenberg#21679]
If  I align content (elements) left, center or right the Gutenberg editor is placing a box arround. This is causing issues if I place stylings like box shadow on the element using css.
Best to see is this image where I placed the box-shadow for just the image. This is not an image within a group!

![grafik](https://user-images.githubusercontent.com/27951109/79580124-d72bae00-80c8-11ea-8e06-f2127ece71a0.png)

Content should be alligned without a box arround, means the aligning should work for the element and not for the box which aligns everything within the box.

There is also a project to implement margin to elements. Think the current implementation of how elements will be aligned will cause issues there, too.

However it must be possible to ad a shadow arround images which isn't the case right now.

**Comment by Sven74Muc** [comment]
Looks like more and more that the base of Gutenberg is difficult and Gutenberg is years away from Elementor. Meanwhile I need to think of  switching to Elemntor not only for pages. Right now I use Gutenberg for  post, but if CSS styling is brocken through things like this...

**Comment by talldan** [comment]
> Best to see is this image where I placed the box-shadow for just the image. This is not an image within a group!

@Sven74Muc I haven't been able to reproduce this, though I note that it may be theme dependent. Which theme are you using? If you're able to share your custom styles that would also be useful.

In the editor, this is what I see for a centered image, the `img` tag dimensions are indicated by the dotted lines:
<img width="639" alt="Screenshot 2020-04-20 at 1 46 46 pm" src="https://user-images.githubusercontent.com/677833/79717969-907ac580-830d-11ea-9317-eb9271598dcb.png">

And in the post itself I'm seeing similar:
<img width="713" alt="Screenshot 2020-04-20 at 1 47 01 pm" src="https://user-images.githubusercontent.com/677833/79718007-ab4d3a00-830d-11ea-8e44-238cf075f787.png">

It seems like it should be perfectly possible to style this with a drop shadow.

**Comment by Sven74Muc** [comment]
@talldan I setup a fresh WP installation, no plugins and I use twenty-twenty theme. 

Whithin the customizer I added the following code:
.shadow {
  box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.5);
}

When I add a new post, place an image in, center it and then add the new class "shadow" to the image it looks like within my screen.

**Comment by talldan** [comment]
@Sven74Muc I think you want to make the selector for your style target the image element:
```
.shadow img {
box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.5);
}
```

Many blocks do have wrapping elements. On the image block the markup is wrapped in a `figure`, i.e.
```html
<figure>
  <img />
  <figcaption></figcaption>
</figure>
```

**Comment by Sven74Muc** [comment]
oh, my fault... thanks @talldan
