### ISSUE TITLE
Build Tooling: Configure PHPCS to forbid short array syntax

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21677]
Previously: https://github.com/WordPress/gutenberg/pull/21467#discussion_r410249043

For better or worse, the WordPress PHP coding standards [forbid the PHP short array syntax](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#declaring-arrays). There is currently no enforcement of this standard in our codebase. Thus, code which violates this standard is currently allowed to be merged to the codebase.

**Task:**

Configure PHPCS to forbid short array syntax.

**Implementation notes:**

Configuration is here: https://github.com/WordPress/gutenberg/blob/master/phpcs.xml.dist

It's unclear if any of the rules we inherit from (e.g. `WordPress-Core`) have this option available, including in more recent versions. Or if it makes sense to propose this first as an upstream change if it is not yet available.

**Comment by Soean** [comment]
We just need to update the composer packages.
