### ISSUE TITLE
If no block selected should it show?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2168]
I noticed that the block tab shows even if you have no block selected. Should this be the case? I would have expected it to just not appear unless you were in a block. Hiding and showing only when contextual like this adds to the feeling of a clean, magic interface.

![2017-08-02 at 19 06](https://user-images.githubusercontent.com/253067/28887653-e11e06de-77b5-11e7-9d9f-5ad2d3431f3b.png)

**Comment by aduth** [comment]
Related: #1100, #1343

**Comment by annaephox** [comment]
Possible also related to: #2167 (i.e. do we need two tabs?)

**Comment by karmatosed** [comment]
Going to close in relation to #1110. Thanks.
