### ISSUE TITLE
Adding block icon treatment within pattern different from outside pattern

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21689]
I was exploring patterns today and noticed that within the pattern the '+' treatment didn't have a background.

![image](https://user-images.githubusercontent.com/253067/79599174-f7fdfe80-80dc-11ea-86df-6b55979fbc7e.png)

I am not sure if this is intended, it might be and if so I can close this issue. However, it felt unexpected as other blocks or 'within' cases show it the same as outside.

**Comment by mtias** [comment]
That is the placeholder + of an empty column, with the column being 0 width. What doesn't make sense is to use an empty and collapsed column in the pattern.
