### ISSUE TITLE
Social Icon URLs default with incorrect protocol

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#21699]
**Describe the bug**
If you simply enter a social icon url without a protocol, such as `twitter.com`, the buttons default to using HTTP. All social media platforms use HTTPS so it should default the URLs to HTTPS.

Editing the block in the Dashboard
<img width="622" alt="screenshot_75" src="https://user-images.githubusercontent.com/2078245/79632378-1aa61b00-81a2-11ea-8ba8-8bdb93f5e2ea.png">

Viewing the page in the browser
<img width="764" alt="screenshot_76" src="https://user-images.githubusercontent.com/2078245/79632379-1c6fde80-81a2-11ea-8532-e8155333e771.png">

**To reproduce**
1. Insert Social Icons Block
2. Click on Twitter Icon and enter the url as `twitter.com`
3. Save the page and view in browser
4. Use the Browser dev tools to view that the url in the link is using the incorrect protocol.

**Expected behavior**
It should default all URLs to HTTPS if it's not specified

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: mascOS 10.15.4
 - Browser: Firefox 75.0

**Comment by jasmussen** [comment]
@mkaz is this one you can take a look at? Simply defaulting to https:// might e a good start.
