### ISSUE TITLE
Limit navigation depth to 5, to avoid submenus going off the editor canvas

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21691]
If you add multiple sub navigations it can end up going off the canvas. 

![image](https://user-images.githubusercontent.com/253067/79606739-f981f380-80e9-11ea-9cb4-d4783c52e62b.png)

_Edit:_ [Per discussion](https://github.com/WordPress/gutenberg/issues/21691#issuecomment-786240926), a good solution for starters would be to limit the navigation depth to 5.

**Comment by jasmussen** [comment]
Thanks for the ticket, you are the best tester! 

To an extent, though, some of this should be "allowed", insofar as if you really want to, you can break any layout with an unfortunate usage of the tools available, and by that I mean everything ranging from the spectrum of setting the font to 2px Comic Sans, to grouping a paragraph in 100 layers of groups.

What do you think, @shaunandrews?

**Comment by shaunandrews** [comment]
I think it is weird that the submenus can nest infinitely like this; I'd expect there to be some limit on the number of nested menus.

**Comment by jasmussen** [comment]
Good point. How about 5? That seems like it would be one more than anyone should ever need, and presumably we'd be able to easily increase that if someone wants it.

**Comment by shaunandrews** [comment]
Makes sense to me.

**Comment by jasmussen** [comment]
Tammie my friend, I took the liberty of editing the ticket here to make it about limiting the amount of nesting to 5.

**Comment by georgeh** [comment]
👀
