### ISSUE TITLE
Remove WordPress icon from default icons list in Social Icons block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#21700]
**Describe the bug**
The Social Icons block defaults with several default icons, including the WordPress icon. Not only that, it even defaults the url to `wordpress.org` so even if you don't add a URL to it, it automatically displays on the rendered page. What happened to the 80/20 rule? The majority of users wont want a WordPress icon so it forces an extra step upon them to have to remove it.

The Social Icons block should only default with the (current) most common platforms (Facebook, Twitter, Instagram, LinkedIn & YouTube).

WordPress icon displays even though I never entered a URL for it
<img width="665" alt="screenshot_77" src="https://user-images.githubusercontent.com/2078245/79632832-2810d480-81a5-11ea-85f3-ed1f04bf4432.png">

**To reproduce**
Steps to reproduce the behaviour:
1. Insert Social Icons block
2. Click on the Twitter URL and enter `twitter.com`
3. Save the page and preview it in the browser
4. View that the WordPress icon also displays even though you never entered any URL for it

**Expected behavior**
The WordPress icon should not be displayed by default, either in the Editor or on the front-end.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
- Browser: Firefox 75.0

**Comment by ZebulanStanphill** [comment]
I agree that the default link to WordPress.org isn't exactly useful.

However, there's currently a noticeable downside to removing it: if we remove the default URL from the WordPress icon, then the block will display nothing when unselected, making it appear almost invisible. (I think that's why that WordPress icon is there by default in the first place.)

Perhaps this is as an indicator that we need a proper placeholder state for this block. I'm not sure what it should look like, though.

**Comment by maddisondesigns** [comment]
Then that sounds like an issue with the block UI itself. It's definitely not a reason to keep the icon.

**Comment by karmatosed** [comment]
I personally quite like the WordPress option being there. I think you could argue it shouldn't be the first, but I don't think for me there is an issue it being a default as you can remove them.

**Comment by ZebulanStanphill** [comment]
@karmatosed If you almost always have to remove it, it isn't a good default. And in the case of a link to WordPress.org, that's definitely not something most people want in their list of social links.

**Comment by maddisondesigns** [comment]
@karmatosed You quite like it there because you're heavily involved in WordPress. You also have a WordPress dot org account, so of course, it's something that's relevant to you and something you're likely to want on your own site.

For the other 95% of people around the world who just use WordPress for their business site or blog, and don't have a dot org account, it makes zero sense for it to be there, and is going to be incredibly annoying having to remove it EVERY SINGLE TIME the block is inserted.

> The rule of thumb is that the core should provide features that 80% or more of end users will actually appreciate and use. If the next version of WordPress comes with a feature that the majority of users immediately want to turn off, or think they’ll never use, then we’ve blown it. If we stick to the 80% principle then this should never happen.

If you're going to have something like this in the WordPress Philosophy, you can't just pick and choose when you want to abide by it.

<img width="703" alt="screenshot_78" src="https://user-images.githubusercontent.com/2078245/79992387-c4650f00-84f6-11ea-81e7-12dcf52d7b7e.png">

**Comment by karmatosed** [comment]
Some great thoughts here regarding this and I want to be clear I am open to iterating. I guess to frame better my feeling, I think having it there is similar to our approach with 'Hello Dolly'; it is a little nod. Not everyone has every social link, so there will always be someone that has to remove at least one, no matter what default. Incidentally, I feel that way about Facebook (which I don't use) and Linkedin. That's a personal space though, let's move on from that and see how we can get a decision here.

I think what could be good is to get a few more thoughts from others here and then we can with that in mind look removing or not.

**Comment by maddisondesigns** [comment]
Sure, there are people who might not use Facebook so they may have to remove that every time as well, but the number of people who don't use Facebook are going to be significantly smaller, than the number of people who don't use WordPress (accts).

 While I can understand "little nod" to WordPress similar to Hello Dolly, the fact remains that all it's going to end up doing is frustrate people when they have to remove it every single time. It'll be even more annoying than the fact that Hello Dolly is still included in core. There's a huge number of people, myself included, who think it's time that was removed from core as well. It provides no benefit to sites, and it provides little to no benefit to new plugin developers as there's much better examples around if you're just starting out and want to learn how to create a plugin. And besides, it's not like the thing would be deleted, it would still be in the Plugin Directory for people to download it if they _really_ wanted it.

In the end, having this social block included by default, is just going to be more annoying than useful. Not to mention the fact that it has a default link as well. There is no reason to keep this icon as a default when a **HUGE** number of people are going to have to delete **every single time** they insert this block into their page.
