### ISSUE TITLE
Reduce Spacer Block's minimum height

### ISSUE THREAD

**Issue by Sven74Muc** [WordPress/gutenberg#21702]
Transfering this topic to github:
https://core.trac.wordpress.org/ticket/49862#comment:3

As discussed in the last editor chat ther is in issue in the backend with blocks with a smaller high then 20px.  Think this shouldn't stop changing the min high for the front end to 1px. Within the backend there could be 20px high to make a block usable.

**Comment by talldan** [comment]
Closing as a duplicate of #18906
