### ISSUE TITLE
reload section of gutenburg on post save

### ISSUE THREAD

**Issue by jackrobson** [WordPress/gutenberg#21705]
**Issue Overview**

If a post is saved the Featured Image panel does not change if changes of the post featured image via the "save_post" hook were fired.

My featured image is generated dynamically from other content inside the block editor. So I need it to appear after page is saved and save_post hook is fired.

**Steps to Reproduce**

    function test_save_post_hook( $post_id = 0 ) {
      // change the second parameter to an ID 
      // of an existing image in the media library
      set_post_thumbnail( $post_id, 44 ); 
    );
    add_action( 'save_post', 'test_save_post_hook', 10, 1 );

1. In the functions.php add an action on "save_post" which sets a featured image for the saved post; the WP core function "set_post_thumbnail()" helps. Imagine a code like above.
2. Create a post and save it as a draft.
3. Look at the Featured Image panel, you should see your image.
4. Remove the Featured Image and update the post.
5. Look at the Featured Image panel, the image is missing.
6. Open the post edit page again: the featured image is displayed.

**Expected Behavior**

It is expected that the Featured Image panel is updated on any change via the "save_post" hook after saving the post.

**Current Behavior**

The Featured Image panel is not updated on any change via the "save_post" hook after saving the post.

**Similar Previous Issue**
https://github.com/WordPress/gutenberg/issues/8474

**Comment by ashiishme** [comment]
I have tried to reproduce the issue, but the image is not displayed after editing the page again once the image has been removed.

- WordPress: v5.4
- Theme: TwentyTwenty v1.2
- Post Types: Post & Page

After opening the edit page, the removed thumbnail image is not attached to the post. 

Can you attach a GIF that reproduces the issue?

**Comment by jackrobson** [comment]
Apologies, that code does in fact work.

However, it's proving inconsistent once I start adding my other business logic in.

I'm going to close this and find a better way to describe the issue

Thank you for your help.
