### ISSUE TITLE
Tooltip for PluginSlot / PluginSidebar inconsistent between browsers

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#21704]
**Describe the bug**
If a new menu is created with a plugin a ToolTip is created with the menu title, the location of this ToolTip is below the menu icon in Chrome and Firefox but above the icon in Safari

**To reproduce**
1. Create or use a plugin that adds a new `PluginSidebar`
2. Visit the Block Editor in Safari, Chrome and FireFox
3. In each browser hover the mouse over the menu icon.
4. Note how the ToolTip is above the menu icon in Safari but below the icon in the other 2 browsers

**Expected behavior**
Tooltip location so be consistent across browsers

**Screenshots**
FireFox:
<img width="411" alt="Screenshot 2020-04-18 at 13 57 20" src="https://user-images.githubusercontent.com/1280733/79638240-8f665e80-817c-11ea-8d2a-41bee37ef38a.png">
Chrome:
<img width="414" alt="Screenshot 2020-04-18 at 13 57 12" src="https://user-images.githubusercontent.com/1280733/79638242-90978b80-817c-11ea-9c44-6a58dbe2a3d8.png">
Safari:
<img width="411" alt="Screenshot 2020-04-18 at 13 57 03" src="https://user-images.githubusercontent.com/1280733/79638243-91302200-817c-11ea-948e-9d14650e0a94.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5-alpha-47585
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari 13.1, Chrome 81.0.4044.113, FireFox 75.0

**Comment by mattyrob** [comment]
I had change to install the Gutenberg plugin at version 7.9.1 and this issue appears to have resolved.

Leaving ticket here for review by core developer.

**Comment by talldan** [comment]
@mattyrob It looks like this is dynamic, so if there's space above the button within the window, the tooltip might go above, and if not, it might go below. I'm not sure if you might have had the editor in fullscreen mode in some instance, but that might explain the difference.

**Comment by talldan** [comment]
I also just noticed the default was recently changed from above to below in #21476, so that explains why it now is resolved.

**Comment by mattyrob** [comment]
Thanks @talldan , I was not using full screen and it seemed crowded when displayed above, so good to hear a fix is in the code now.
