### ISSUE TITLE
Regression: the navigate region focus style is broken

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#21717]
**Describe the bug**
When jumping through the main ARIA landmarks in the editor (also known as "navigate-region" component) via the dedicated keyboard shortcuts, the focus style of the regions is broken, in slightly different ways on different browsers.

**To reproduce**
- Test in different browsers, also on Windows.
- Use the keyboard shortcuts to navigate through the landmarks.
- on macOS:
  - Ctrl+backtick
  - Shift+Ctrl+backtick
- on Windows (if I'm not mistaken):
  - Shift+Alt+N
  - Shift+Alt+P
- see the focus style is broken on some of the regions

**Expected behavior**
The focus style to always be clearly visible.

**Note**
This style broke a few times during the project history. Maybe worth considering a different, more solid, _testable_, implementation.

**Screenshots**

With Gutenberg plugin activated.

Chrome Windows: content region focused: the style is visible only in the part of the UI close to the browser scrollbar:

![Screenshot (95) content](https://user-images.githubusercontent.com/1682452/79695833-4b0cb880-8279-11ea-9618-2a9fc62b2de6.png)

Chrome Windows: sidebar region focused: the style is barely visible:

![Screenshot (96) sidebar](https://user-images.githubusercontent.com/1682452/79695840-53fd8a00-8279-11ea-8550-920e91574667.png)

Chrome macOS content region: no style visible:

<img width="1330" alt="chrome content" src="https://user-images.githubusercontent.com/1682452/79695978-38df4a00-827a-11ea-9edb-5f585ecf94ca.png">

Chrome macOS sidebar region: style barely visible:

<img width="1335" alt="chrome sidebar" src="https://user-images.githubusercontent.com/1682452/79695994-48f72980-827a-11ea-8813-f5f307bb1bfe.png">

Chrome macOS publish region: no style visible:

<img width="1326" alt="chrome publish" src="https://user-images.githubusercontent.com/1682452/79696001-54e2eb80-827a-11ea-8465-6f422ada15f7.png">

Firefox macOS sidebar region: style breaks but in a different way:

<img width="1333" alt="firefox sidebar" src="https://user-images.githubusercontent.com/1682452/79696022-6a581580-827a-11ea-844f-09c1341190f8.png">

**Editor version (please complete the following information):**
- can reproduce with slightly different results on both:
  - default editor shipped with WP 5.4
  - plugin version 7.9.1

**Comment by talldan** [comment]
I accidentally created a duplicate (#32758). When testing more recently it looks like the main editor area and publish panel link are the only two that don't have outlines.

For the main editor area, there are other elements overlapping the region. The CSS for the regions is here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/higher-order/navigate-regions/style.scss

It might be possible to use a pseudo-element with a higher z-index to solve the overlapping issue.

**Comment by afercia** [comment]
WOrking on a PR right now. Just to note that we already tried a pseudo-element and we changed it in https://github.com/WordPress/gutenberg/pull/8554. The problem with an absolutely positioned pseudo-element is that it scrolls when scrolling the post content.
