### ISSUE TITLE
A missing/unregistered block in a template crashes the post editor

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#21718]
## Describe the bug
If a post type block template references a block which is not registered, the editor crashes with a whitescreen.

## To reproduce
1. Create a post type template with a block that does not exist:
```php
register_post_type(
    // attributes
    'template' => [
        [ 'fake/block', [] ],
    ]
);
```
2. Create a new post for that post type
3. Observe white screen
4. See error: `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'n.attributes')` (full trace below)

## Expected behavior
While this is clearly an error, it would be nice if it were handled better. At the very least, a more descriptive console message would be great. Even better would be to show an error in the standard error boundary template so the rest of the core UI is available.

## Screenshots
<img width="1239" alt="Screen Shot 2020-04-19 at 5 20 30 PM" src="https://user-images.githubusercontent.com/1231306/79700197-15a8a080-8262-11ea-8233-d53cf80812eb.png">

## Editor version (please complete the following information):
- WordPress version: 5.3 branch
- Gutenberg plugin: 7.9.1

## Desktop (please complete the following information):
 - OS: macOS
 - Browser: Safari + Chrome tested

## Additional context
Stack trace, in the event that it's helpful:

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'n.attributes')
	dispatchException (wp-polyfill.min.js:1:97215)
	invoke (wp-polyfill.min.js:1:92747)
	(anonymous function) (index.js:1:5094)
	c (index.js:1:5232)
	t (index.js:1:5488)
	initializePromise
	Promise
	(anonymous function) (index.js:1:9537)
	(anonymous function) (index.js:11:177013)
	(anonymous function) (index.js:1:16699)
	r (index.js:11:166130)
	Ag (react-dom.min.js:63:113)
	Vg (react-dom.min.js:89:445)
	lh (react-dom.min.js:126:412)
	O (react-dom.min.js:121)
	O
	ze (react-dom.min.js:118)
	ze
	(anonymous function) (react-dom.min.js:53)
	unstable_runWithPriority (react.min.js:26:342)
	mg (react-dom.min.js:52:499)
	V (react-dom.min.js:52:434)
	Sb (react-dom.min.js:213:98)
	Mg (react-dom.min.js:85:83)
	Mg
	e (index.js:1:27494)
	(anonymous function) (index.js:1:27578)
	forEach
	o (index.js:1:21480)
	(anonymous function) (index.js:1:18707)
	p (index.js:1:11333)
	n (index.js:1:9451)
	some
	e (index.js:1:5181)
	(anonymous function) (index.js:1:5131)
	promiseReactionJob
```

**Comment by ntsekouras** [comment]
Hey thanks for reporting this! - This has been fixed with a specific error message here: https://github.com/WordPress/gutenberg/pull/24287

**Comment by ntsekouras** [comment]
I'll reopen this issue as this should be handled better other than having a better message.

**Comment by peterhebert** [comment]
Have run into this also, with a block template using a block provided by a plugin, when the plugin got disabled:
`Uncaught (in promise) Error: Block type 'coblocks/social-profiles' is not registered.`

Causes blank white screen. This really should fail more gracefully, and either just ignore the missing block or have message where block is placed in template that it does not exist. Should not block editor from loading.

**Comment by CreativeDive** [comment]
This same thing happened if I try to add a new "block template" in the block editor sidebar. In my case if have disabled the core block "`core/separator`" in the following way:

`wp.blocks.unregisterBlockType( 'core/separator' );`

But if the default template includes a "`core/separator`" block as a part of the template, this breaks all. The template editor dosen't work in this case. I get a white screen.

Removing `wp.blocks.unregisterBlockType( 'core/separator' );` solves that. But this is a bug in my eyes. The editor should not break if a not registered block was called.

**Comment by mauteri** [comment]
Hi! I create a PR in an attempt to improve the user experience with this issue. I see recent changes have removed the white screen, which is great. In my change I'm looking to mimic the experience of a post edit that is missing a block, and utilize the core/missing block in the createBlock function if a block isn't registered. This keeps the layout intact where blocks are registered, and calls out the block that is not registered within the editor with core/missing block.

This is my first contribution to the project, so I'm also looking to learn and open to making any adjustments to improve this code. Thanks! :-)

https://github.com/WordPress/gutenberg/pull/37646

**Comment by mauteri** [comment]
My PR above has been merged to trunk, so this ticket can probably be closed now. 

New user experience retains any registered blocks in a template and uses `core/missing` block for any unregistered blocks in a template. More notes about specifics handlings are provided in the comments of the PR. Thanks!

**Comment by amustaque97** [comment]
> My PR above has been merged to trunk, so this ticket can probably be closed now.

PR link: https://github.com/WordPress/gutenberg/pull/37646

Closing this issue!
