### ISSUE TITLE
Custom meta-box fields overflow on sidebar

### ISSUE THREAD

**Issue by ashiishme** [WordPress/gutenberg#21719]
**Describe the bug**

Some elements inside the custom meta-box added in the sidebar seems to be overflown. I was trying to add a select field using a meta-box and found that the select field width is larger than the parent wrapper when I wanted the width to be 100%.

**To reproduce**

1. Add a meta-box to any post type [post/page] and include a select field / button field.
2. The display context of the meta-box must be 'Aside'.
3. Set the select / button field width to 100%. 

The fields will be overflown from its parent container. 

**Expected behavior**

Select / Button fields to be full width to match their parent's width. Except for these two fields, other fields seem to fit perfectly and even the div element.

**Screenshots**

![image](https://user-images.githubusercontent.com/18111862/79723097-ed25b280-8304-11ea-9f81-9343aa17c084.png)

**Editor version:**

- WordPress 5.4 with default block editor.

Currently, I am fixing this issue for the `select` field using the `max-width` value of less than 90%.

**Comment by torounit** [comment]
@ashiishme 

What kind of code will cause problems? 
It would be very helpful share a snippet.

**Comment by ashiishme** [comment]
@torounit, I have attached the snippet. It causes the problem. If this is a valid issue, can I send the PR with fixes? 

```php
function ashiishme_add_meta_box() {

    add_meta_box(
        'meta-box-overflow',
        __( 'Select Field', 'ashiishme' ),
        'select_field_meta_box_callback',
		'page',
		'side',
		'high'
    );
}

add_action( 'add_meta_boxes', 'ashiishme_add_meta_box' );


function select_field_meta_box_callback( $post ) {
    ?>
    <p>
        <select style="width: 100%" name='ashiishme_select_field' id='ashiishme-select-field'>
            <option value="A">option 1</option>
	    <option value="B">option 2</option>
	    <option value="C">option 3</option>
	    <option value="D">option 4</option>
        </select>
    </p>
    <?php   
}
```

**Comment by youknowriad** [comment]
When you add a `width: 100%` to your meta box, you assume that its parent doesn't have any padding thus the issue. Wrapping with a div might work too.

**Comment by ashiishme** [comment]
I am already wrapping it with a block element as you can see in the example code & without adding `width`, the default size is too small. How can we make it a full width preventing the overflow?

**Comment by youknowriad** [comment]
The padding is there  by default, so you can try using a negative margin to "override that".
