### ISSUE TITLE
Column percentage widths no longer recalculate to equal 100% when changing a columns width %

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#21729]
**Describe the bug**
When using the columns block if you resize an individual column's width then the other columns in the block don't get their widths recalculated to fit 100%.

**To reproduce**
1. Add a columns block
2. Add 2 columns (50%/50%)
3. Resize one to 40%
4. The other column remains 50%, it used to resize to 60%

**Expected behavior**
Other columns within a columns block recalculate to fit 100%. This was the case before WordPress 5.4.

**Editor version:**
- WordPress version: 5.4 with default editor

**Comment by talldan** [comment]
@ninetyninew Thanks for reporting the issue. I followed your steps, but I wasn't able to reproduce it. The unset column seems to resize to fill up the available space. I tested both 5.4 and the latest version of the Gutenberg plugin:
<img width="781" alt="Screenshot 2020-04-21 at 11 47 48 am" src="https://user-images.githubusercontent.com/677833/79823291-fdea2d00-83c5-11ea-9b19-61d2fc59ebcc.png">

In the screenshot above (from 5.4) the second column is set to Auto, while the first is set to 19%.

In the latest version of the plugin, 'Auto' doesn't seem to be shown but the behavior is the same.
