### ISSUE TITLE
The entity being edited (postType, undefined) does not have a loaded config.

### ISSUE THREAD

**Issue by jackrobson** [WordPress/gutenberg#21731]
**Issue Overview**
I am unable to change any values via the editPost function.

**Steps to Reproduce**
Setup a custom plugin with two files:

```php
<?php
// wp-content/plugins/myguten-plugin/myguten-plugin.php
/* Plugin Name: Change Featured Image */
function cfi_enqueue() {
    wp_enqueue_script(
        'cfi-script',
        plugins_url( 'myscript.js', __FILE__ ),
        array( 'wp-data', 'wp-editor' )
    );
}
add_action( 'enqueue_block_editor_assets', 'cfi_enqueue' );
```

and...

```javascript
console.log("wp-content/plugins/myguten-plugin/myscript.js")
wp.data.dispatch( 'core/editor' ).editPost( { featured_media: 9 } );
```

**Expected Behavior**
When I open a post to edit, it should automatically set the featured image to media library item 9.

**Current Behavior**
I get the following console error:

```
core-data.min.js?ver=30bbd0e8996befdf7ce081c737c9c75c:2 
Uncaught (in promise) Error: The entity being edited (postType, undefined) does not have a loaded config.
    at core-data.min.js?ver=30bbd0e8996befdf7ce081c737c9c75c:2
    at tryCatch (wp-polyfill.min.js?ver=7.4.4:1)
    at Generator.invoke [as _invoke] (wp-polyfill.min.js?ver=7.4.4:1)
    at Generator.t.<computed> [as next] (wp-polyfill.min.js?ver=7.4.4:1)
    at redux-routine.min.js?ver=7b7d8224ca3d5f24509583833d71c388:2
    at redux-routine.min.js?ver=7b7d8224ca3d5f24509583833d71c388:2
    at redux-routine.min.js?ver=7b7d8224ca3d5f24509583833d71c388:2
    at Array.some (<anonymous>)
    at e (redux-routine.min.js?ver=7b7d8224ca3d5f24509583833d71c388:2)
    at redux-routine.min.js?ver=7b7d8224ca3d5f24509583833d71c388:2
```

**Comment by talldan** [comment]
@jackrobson This sounds a bit like a race condition—that your code is executing before `wp.data` has been initialized.

It might be worth trying to wrap your JavaScript in `wp.domReady`. e.g.:
```js
wp.domReady( function() {
    console.log("wp-content/plugins/myguten-plugin/myscript.js")
    wp.data.dispatch( 'core/editor' ).editPost( { featured_media: 9 } );
} );
```

There may also be other techniques commonly used by plugins to defer initialization, so it might be worth doing some research on that.

**Comment by M4N0JKUM4R** [comment]
I am getting the same error. I even tried wrapping inside domReady. How was this fixed?

![image](https://user-images.githubusercontent.com/11471878/180202363-510da906-f49f-42f5-82c7-c5d4e45793f4.png)

```JS      
if (!wp.data.select("core").hasEntityRecords("API_Kind", "API key")) {
	wp.data.dispatch("core").addEntities([
	{
	  label: "API key",
	  name: "API key",
	  kind: "API_Kind",
	  baseURL: "BaseURL",
	  value: apiKeyInput.current.value,
	},
	]);
     } else {
	domReady(() => {
		wp.data
			.dispatch("core")
			.editEntityRecord(
				"API_Key",
				"API_Key",
				"API_Kind",
				"BaseURL",
				apiKeyInput.current.value
			);
	});
}
```
Not sure if that's the right way because the Gutenberg documentation is limited.

**Comment by shadigaafar** [comment]
I'm encountering a similar issue. When I use `useEntityProps` and call `setMeta` within a function that is then executed by `useEffect`, I have also attempted to use `domReady`, but that approach hasn't resolved the problem for me.
@talldan
