### ISSUE TITLE
If caption is empty, hitting enter should work as down arrow

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2173]
Right now we create new lines, which is fine if there's some content already in the caption, but if it's empty we should treat it as a down arrow.

cc @iseulde

**Comment by youknowriad** [comment]
Per slack discussion, I'm going to try to make this consistent with headings and paragraphs:

`Enter` splits into two blocks (creating a paragraph block)
`shift+Enter` create `<br>`

**Comment by BE-Webdesign** [comment]
This could extend to how we deal with other semi nested blocks like quotes + citation and other figures with a caption. Potential use of enter behavior noted by Riad:

- Enter in the middle of a caption, create `<br>`
- Enter at the end of a caption, creates an new paragraph
- shift Enter always creates `<br>`

Potential addendum: if the caption/citation is empty only then create a new paragraph on Enter. If there is existing content in the citation maybe the user wants that extra whitespace.

**Comment by mtias** [comment]
I don't think we need to handle splitting, that's why I mentioned if it's empty. If the caption was at the top of the image, would you expect to create a new paragraph below? Or if a block has a few editable that are fixed, what would happen?

Also, this was before keyboard navigation, I think, and the main issue was getting stuck in the caption when you didn't want one.
