### ISSUE TITLE
Hide protocol from url in links to give more room

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2174]
![image](https://user-images.githubusercontent.com/548849/28919010-eb18c4a8-784b-11e7-845a-3f03cd9a799b.png)

(From @m)

Let's look at not showing the protocol to make more room for showing the actual url. We could also increase the max-width here.

**Comment by iseulde** [comment]
We should hide `www.` as well. Core currently hides the query string and hash as well, though I can see why you'd want to leave it there if it contains important info. Anyway, it will most likely be cut of anyway, so no need to bother.

**Comment by notnownikki** [comment]
How do we see this working? Should we hide the protocol and www. subdomain as soon as we recognise a URL in the input? What should the user expect to have to do if they want to edit that part of the URL?

**Comment by notnownikki** [comment]
nvm, figured it from looking at core behaviour :smile:

**Comment by notnownikki** [comment]
https://github.com/WordPress/gutenberg/pull/2401
