### ISSUE TITLE
Best practices: examples for plugin developers

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#21754]
**Is your feature request related to a problem? Please describe.**

We have good documentation for plugin developers https://developer.wordpress.org/block-editor/

But there are situations where it would be better to expect `sample source code` to understand feature and to understand best practices.

Even core maintainers don't understand some aspects of new editor: https://github.com/10up/insert-special-characters/issues/55

**Describe the solution you'd like**

It would be awesome to have some reference implementations. Simple but useful plugins to give developers ability to understand best practices.

For example I've used the [Advanced Rich Text Tools for Gutenberg](https://wordpress.org/plugins/advanced-rich-text-tools/) sources [advanced-rich-text-tools](https://github.com/ellatrix/advanced-rich-text-tools) from @ellatrix — a year ago it was awesome sample of good plugin.

But now it is too outdated and doesn't work at all https://wordpress.org/support/topic/wp-5-3-0-trying-to-get-property-base-of-non-object/ and https://github.com/ellatrix/advanced-rich-text-tools/issues/8

I think it would be nice to have **updated to latest API/capabilities** reference **simple** plugin/plugins to show developers good examples.

**Describe alternatives you've considered**

Better handbook https://developer.wordpress.org/block-editor/ but sample plugin would be awesome too. The same for themes https://github.com/WordPress/gutenberg/issues/21401

**Comment by nosolosw** [comment]
Hi @mahnunchik I don't see that you mentioned the https://github.com/wordpress/gutenberg-examples so I thought I'd share in case that's helpful and/or covers the need you suggested.

**Comment by mahnunchik** [comment]
Hi @nosolosw Thanks, yep it is helpful. I forgot to mention it 😢 

My idea is a little wider: to have sample plugin like [Advanced Rich Text Tools for Gutenberg](https://wordpress.org/plugins/advanced-rich-text-tools/) to receive feedback not only from developers but from usual users too.

**Comment by ryanwelcher** [comment]
The [Gutenberg Examples](https://github.com/WordPress/gutenberg-examples) repository is meant to serve this purpose so I am going to close this out.
