### ISSUE TITLE
Keyboard Shortcuts for Plugin Sidebars

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#21765]
Keyboard shortcuts were made available in WordPress 5.4 and in the future this functionality will be extended to allow users to remap the shortcuts themselves. As a result of this plan it's important to register and then implement the shortcuts via the available packages.

I have a sidebar registered via a plugin at the moment, I've attached significantly trimmed code below to give the basic outline. The shortcut is registered and shows in the shortcuts dialog.

What I have noticed is that the shortcut works fine to open and close the sidebar when the browser is focussed within the editor, but when the focus is within any block, so the title or a paragraph, the shortcut fails to work.

There are no console errors logged beyond those areal covered in other tickets that link to `WP_DEBUG` being set to true.

Is this a bug in the detection of shortcut usage within blocks or am I doing something wrong?

```
( function( element, plugins, i18n, editPost, data, keyboardShortcuts ) {
	var el = element.createElement;
	var Fragment = element.Fragment;
	var PluginSidebar = editPost.PluginSidebar;
	var registerPlugin = plugins.registerPlugin;
	var dispatch = data.dispatch;
	var select = data.select;

	data.dispatch( 'core/keyboard-shortcuts' ).registerShortcut(
		{
			name: 'test/toggleMenu',
			category: 'global',
			description: i18n.__( 'Show or hide Test sidebar.' ),
			keyCombination: {
				modifier: 'access',
				character: 'g',
			}
		}
	);

	function sidebarComponent() {
		return [			
			el(
				Fragment,
				{ key: 'test/sidebar' },
				el(
					PluginSidebar,
					{
						name: 'test-sidebar',
						title: 'My Sidebar'
					},
					'Sidebar Menu Content'
				)
			),
			keyboardShortcuts.useShortcut(
				'test/toggleMenu',
				element.useCallback(
					function ( event ) {
						var menuStatus = select( 'core/edit-post' ).isPluginSidebarOpened( 'test-plugin/test-sidebar' );
						if ( true === menuStatus ) {
							dispatch( 'core/edit-post' ).closeGeneralSidebar( 'test-plugin/test-sidebar' );
						} else {
							dispatch( 'core/edit-post' ).openGeneralSidebar( 'test-plugin/test-sidebar' );
						}
					},
					[]
				)
			)
		]
	}
	registerPlugin( 'test-plugin', {
		icon: 'admin-site-alt3',
		render: sidebarComponent
	} );
} )(
	window.wp.element,
	window.wp.plugins,
	window.wp.i18n,
	window.wp.editPost,
	window.wp.data,
	window.wp.keyboardShortcuts
);
```

**Comment by talldan** [comment]
@mattyrob `useShortcut` is a hook, so I don't think it should be returned as an element by your component:
```js
function sidebarComponent() {
    keyboardShortcuts.useShortcut(
        'test/toggleMenu',
        element.useCallback(
            function ( event ) {
                var menuStatus = select( 'core/edit-post' ).isPluginSidebarOpened( 'test-plugin/test-sidebar' );
                if ( true === menuStatus ) {
                    dispatch( 'core/edit-post' ).closeGeneralSidebar( 'test-plugin/test-sidebar' );
                } else {
                    dispatch( 'core/edit-post' ).openGeneralSidebar( 'test-plugin/test-sidebar' );
                }
            },
            []
        )
    );

    return [			
        el(
            Fragment,
            { key: 'test/sidebar' },
            el(
                PluginSidebar,
                {
                    name: 'test-sidebar',
                    title: 'My Sidebar'
                },
                'Sidebar Menu Content'
            )
        )
    ];
}
```

There's also a 'gotcha' when using shortcuts within a react component that if the component is not mounted then the shortcut won't be active. That might not be an issue with your usage as I think plugins are always mounted, but it's something to watch out for if you decide to call `useShortcut` in a child component.

**Comment by mattyrob** [comment]
@talldan 

Thanks for the response, I have amended the test code as you have suggested and while it still works as before, the shortcut still doesn't operate 'globally' - it fails to trigger when the focus is within a block element in the editor.

Could this be because plugin elements are not rendered when blocks are in focus? Or is it a bug in catching key presses in the core code? (The sidebar button is still visible in the top right menu)

**Comment by mattyrob** [comment]
A little more testing using code amended with your suggestion, the shortcut works for almost everywhere expect when a part of the editor is focussed that accepts text input - so a text containing block, even a block which allows text entry (the image block URL box), the Block Search tool also blocks detection of the shortcut.

Interestingly core shortcuts to show all shortcuts, tho the code editor, settings and navigation menu all continue to work in these places.

Implementation therefore seems to be different and registering a shortcut as 'global' is not working globally as core shortcuts do.

So, is this a bug or design feature? Listing the registered global shortcut in the same place as core shortcuts I would expect it to work in the same way.

**Comment by talldan** [comment]
@mattyrob There are also some extra options for useShortcut as seen in the focus toolbar shortcut. You'll probably need to specify `bindGlobal: true` as this one does:
```
	useShortcut(
		'core/block-editor/focus-toolbar',
		useCallback( () => setIsToolbarForced( true ), [] ),
		{
			bindGlobal: true,
			eventName: 'keydown',
			isDisabled: ! canFocusHiddenToolbar,
		}
	);
```

The `global` category in `registerShortcut` refers to the part in the keyboard shortcut modal that the description of the shortcut should show in.

**Comment by mattyrob** [comment]
@talldan 

Brilliant, that's what I've been looking for - so difficult to find, I've been looking for a few weeks. Thanks you very much for your help.
