### ISSUE TITLE
Consider a guiding NUX for Gutenberg

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2176]
This comes from both personal feelings on first load and from @helen's investigation via Tweets:

> I have no idea what I'm supposed to do now. Do I need to configure something? Is it already active? Thankfully I'm the only writer here.

Could we redirect on first activation to a NUX experience of some form? Even just a page saying what can be done now. As we want more people to use, guiding them would be a good thing. I am not sure just moving the menu to a more discoverable place solves this fully.

**Comment by karmatosed** [comment]
Another point worth noting that people shouldn't have to come to the GItHub FAQ to find out how to use Gutenberg. How can we avoid that with this better experience?

**Comment by helen** [comment]
Moving access links to be under posts and pages menus (#2145) and making some other links better (#2159 and #1797) would help mitigate some of this while this is still alpha-esque software. Once this reaches the point of a widely-testable 1.0, maybe it would make sense to have users be able to opt into using the "new editor" by default? The iOS app did something like this, where it had a top banner prompting you to try it, and then a setting to switch back and forth elsewhere if you changed your mind. That's not full onboarding but could be a part of it. I think this would also help with easing the worry that the editor is suddenly on for everybody on your site, although just activating the plugin to begin with is sort of nerve-wracking without much information on getting started in the readme (#2177).

**Comment by StaggerLeee** [comment]
48 = 1 star reviews
21 = 5 star reviews in plugin repository.
Few between.
(If you were real third party plugin and accounted for the same competition rules, your plugin would almost nobody use.)

As I said, on other side of balance is TinyMce and people will judge by it.

You need to start a Blog about Gutenberg and describe in articles only positive things, compared to what was possible with TinyMce, and old post edit screen. No matter if you miss, change minds, take another direction. Just strikethrough irellevant piece of Text (in Blog), and move on. Important is all infomation is there in one place, not spread around. Or as articles in "Make WP core".

**Comment by karmatosed** [comment]
@StaggerLeee I think the NUX and promotion are two similar but not the same aspects. Both would require different approaches. This issue specifically, I think it would be great to focus in on exact things we can do 'in' the software. For example, some of the steps @helen is saying.

**Comment by mtias** [comment]
Closing in favor of #3670.
