### ISSUE TITLE
core/navigation still uses useApiFetch

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#21771]
**Describe the bug**
Recently, `useApiFetch` was deprecated, but `core/navigation` block still uses it, also because of the that block is exported, it causes build problems when using the package in a standalone outside (create-react-app).

**Comment by chrisvanpatten** [comment]
@senadir I believe this was rectified in #21721, can you confirm?

**Comment by talldan** [comment]
I can't find reference to `useApiFetch` in master (beyond the deprecated function itself and some tests), so I'll preemptively close this.

**Comment by getdave** [comment]
> @senadir I believe this was rectified in #21721, can you confirm?

I can confirm cos I fixed it. Check the backstory and cross links on that PR to learn how and why it happened.

**Comment by senadir** [comment]
yeah, I can see that this issue was submitted within minutes from that PR being merged, possibly why I missed it.
