### ISSUE TITLE
Navigation block public vs editor view

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#21778]
**Describe the bug**
The navigation block, when set to full width, doesn't show as such in the editor. 
Public view - https://d.pr/i/Hb51yG
Editor view - https://d.pr/i/tXS7vI
(1) The navigation block was created inside a reusable block and looks much narrower than the full width
(2) This block was created outside of a reusable block as a block in it's own right. However when you also click the setting to make it full width it justifies to the left and leaves a gap at point (3)

URL: https://canimakeahitpodcast.com/wp-admin/post.php?post=35&action=edit

**Expected behavior**
In the editor show it as it would appear on the final page

**Editor version (please complete the following information):**
- WordPress version: 5.4
- All up to date A8C

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by jasmussen** [comment]
Hi, thanks for the ticket! I'd like to potentially work on this issue, but I need a little more information. I tried to reproduce in a few themes, and I see that there are some issues with how themes handle block max-widths that affect block renderings, and could affect the navigation block in the way you describe (but this issue goes beyond just the nav block and is worth looking at separately).

However looking at https://canimakeahitpodcast.com/, the menu in the frontend looks good/correct to me. Did you fix the issue? Did the problem solve itself? From what I can tell at the markup level, the navigation block uses the justification control to center the menu items, which appears to work. 

You mention reusable blocks, does the following issue seem like the cause?

https://github.com/WordPress/gutenberg/issues/8288
