### ISSUE TITLE
Remove block keyboard shortcut doesn't work in Windows

### ISSUE THREAD

**Issue by erhilse** [WordPress/gutenberg#21791]
**Describe the bug**
As title states, when trying to use the shortcut to delete a block on Windows a special character types instead of activating the shortcut. Tested in Edge, Chrome and Firefox. Windows 10 and 7.

**To reproduce**
1. Go to 'https://wordpress.org/gutenberg/'
2. Click on any block
3. Use shortcut 'Shift Alt Z'

**Comment by skorasaurus** [comment]
Sorry no one has responded to this before now; there's been a lot of changes to Gutenberg since your report and I'm unable to reproduce this; shift alt and z is removing selected blocks as I intended; not able to reproduce on Wordpress 6.0.0; in chrome and firefox, win 10.
