### ISSUE TITLE
Copy and pasting from site gives unexpected results

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2180]
I was trying to test another issue and as a result wanted usable text to make a large page. I turned to Lorem Ipsum generator and discovered an interesting effect on pasting. In used: http://www.lipsum.com/feed/html. I simply took the first paragraph, I also had a space at the end of the paragraph.

![screen](https://user-images.githubusercontent.com/253067/28921428-d3dce34e-784d-11e7-8d33-6866abecfdf2.gif)

**Comment by aduth** [comment]
Previously: https://github.com/WordPress/gutenberg/pull/2039#pullrequestreview-52480051

**Comment by georgeh** [comment]
I can repro, I'll work on a paste transformation to remove empty or whitespace paras

**Comment by iseulde** [comment]
#2271 fixes one paragraph created above the posted content and one below.

**Comment by jasmussen** [comment]
Closing in favor of #2147. Please reopen if this was a mistake.
