### ISSUE TITLE
Block Image uses wordpress CDN URLs in the post and database, instead of site's url

### ISSUE THREAD

**Issue by hubertnguyen** [WordPress/gutenberg#21806]
**Describe the bug**
I noticed that Gutenberg uses the wordpress.com CDN urls when I insert images ( "https://i1.wp.com/mydomain.com/", so I checked in the database, and sure enough, it's saved there in wp_posts. I thought that it was dynamically rewritten at first, but no.

That doesn't seem normal, because if I get my site off the Wordpress CDN (uninstalling jetpack), then things should break.

**To reproduce**
1. Have Jetpack installed. Enable site accelerator = ON. Speedup Image Load Time = ON. Speed Up Static Files Load Time = ON. Lazyload = OFF (I have my own) 

2. Create a new post
3. Add image and check image URL to see if it starts with https://i1.wp.com. In my case, it does

**Expected behavior**
I would expect the images URL to be from my domain https://www.mydomain.com/wp-content/... and they would be re-written dynamically at rendering to use https://i1.wp.com.www.mydomain.com or something like that

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Gutenberg plugin : not installed (using core)
- Classic Editor plugin: installed, lets users switch to Gutenberg on a per-post basis
- Jetpack: Version 8.2.3 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 81.0.4044.113

**Comment by talldan** [comment]
@hubertnguyen Gutenberg doesn't use the wp.com CDN, I imagine this is related to Jetpack plugin and so I'd recommend making an issue over on the Jetpack issue tracker:
https://github.com/Automattic/jetpack/issues
