### ISSUE TITLE
StepperControl crashes Webpack

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#21801]
Using @wordpress/components v9.4.1

Please see the live error here-

https://codesandbox.io/s/eloquent-bird-uzlyn?file=/src/App.js

**Comment by Soean** [comment]
There is no `StepperContol` anymore, please use the `RangeControl`. It was removed in #21465.

**Comment by Soean** [comment]
Normally it should be deprecated before it gets removed and added to the changelog.

**Comment by leidar-uk** [comment]
And should be removed from the components reference.
