### ISSUE TITLE
Display featured image (if set) as a thumbnail

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2181]
![image](https://user-images.githubusercontent.com/548849/28922417-5ed42a0a-785a-11e7-9138-cff28cb77c8b.png)

This would help in recognizing if a featured image is set for a post.

Implementation wise, we should look at moving away from local state in `sidebar/featured-image` and to push the image to redux state instead.

**Comment by StaggerLeee** [comment]
Looks very nice. Finally my default no-featured.jpg wont stretch to be gigantic. As you planned before.
Maybe to move it to the left ot Titile. It is most used case on Archive loops.

**Comment by karmatosed** [comment]
More fuel for this:

From @helen:

> I wish that the featured image showed as a block where the theme puts it, or maybe just always above the title. Not a side setting.

**Comment by StaggerLeee** [comment]
Leave it in sidebar too. Not a big deal, as they are collapsed.

Developers tend to add HTML inside this metabox (sometimes per custom post type) to announce something to Editors. For instance sometimes featured image is used as Team member Photo, and wording is different, as it is the HTML description added to Metabox.

Sometimes developers add image size limit as HTML description, etc...

It cannot look nice with same HTML added in Gutenberg content area.

**Comment by helen** [comment]
Isn't a featured image kind of like a pre-inserted immovable block of content rather than information about a post to be managed in a side setting? Actual theme usage varies but it's still much more content-esque than it's been treated. I imagine there's discussion about pre-defining a layout of blocks for people to fill out somewhere around here that has some parallels - #1684 looks like it might be that.

**Comment by StaggerLeee** [comment]
It is Helen, by old WordPress matrix. Blogging, blogging, blogging.
WordPress today is much more than this.

Here are just few examples, from memory, where I used featured image that would be illogical as "content" block only:

- Classifieds - No featured image will be inside content, from standard point of view.
- Portfolio Archive with few custom links as image overlay - No Post detailed view.
- Teams / Members - Fetaured image as (human) profile photo.
- Gallery/Galleries Archive from Posts - Difficult to explain Archive thumbnail above Gallery in editor (backend). Or any place, it would not fit this purpose.
- Custom ERP, Tasks management, Invoices, projects, organisations, clients. Not so easy to have Featured image for all those post types, inside Gutenberg content area.
- Testimonies custom post type - Allways better to have persons photo in sidebar than in content. My humble opinion.

Much more, more WP users, more versatile CMS cases. I mentioned only few I do.

**Comment by helen** [comment]
Sorry, was thinking about single views and previews (since you can't really preview a change in non-single context) and didn't specify. I'm aware of varying custom usages of featured images.

**Comment by StaggerLeee** [comment]
Not sure if I understand all this technical talk.

I am just saying Featured Images is in many cases not something User should click somewhere to invoke it.
It needs to be visible on all post edit screen refresh/reload. 

As you can see from very often used Team / Members custom post type. You can imagine Member face photo is crucial important to be visible all the time in post edit. As reference. No if, no click here, no context this or that. Just plain visible all the time.

You decided now to go with all sidebar tabs collapsed, but different story. Would be nice to remember open/close state, per User. Or it is generally step backward for Users. From previous drag & drop Metaboxes, remembering open/close state not they are forced to this.
On some news portals Excerpt sidebar tab, box is maybe of crucial importance and Editor want it open all the time. But, different story. No need to discuss it here. Maybe it is discussed here. https://github.com/WordPress/gutenberg/issues/2194 I dont get it all right now.

**Comment by hedgefield** [comment]
I second @helen's desire to have it moved it from the sidebar to the main content. There may be other usecases, but in general you'll want to use it as an image header above your post, so that's where it should be shown.

In the case of the mockup, I think I would prefer it on the left as well.

**Comment by mtias** [comment]
Moving to ideas.

**Comment by adamsilverstein** [comment]
What does 'moving to ideas' mean @mtias? Are we backlogging or tracking these 'idea' issues somewhere? This seems like a useful suggestion, can we leave the issue open?

**Comment by karmatosed** [comment]
@adamsilverstein all ideas are kept here: https://github.com/WordPress/gutenberg/projects/8. We totally aren't losing or removing anything.

**Comment by adamsilverstein** [comment]
@karmatosed Awesome, thanks for clarifying! I had no idea what putting something in Ideas meant :)

**Comment by alexmansfield** [comment]
For those of you who expressed interest in a featured image block that can be pre-inserted by a theme/plugin using Gutenberg templates, here is a simple plugin that does that: https://github.com/modularwp/gutenberg-block-featured-image

**Comment by kjellr** [comment]
> For those of you who expressed interest in a featured image block that can be pre-inserted by a theme/plugin using Gutenberg templates, here is a simple plugin that does that: https://github.com/modularwp/gutenberg-block-featured-image

Very cool. Here's a screenshot for reference:

<img width="1439" alt="screen shot 2019-01-23 at 9 39 26 am" src="https://user-images.githubusercontent.com/1202812/51614510-cc00c700-1ef3-11e9-97a2-6bd0c2b881dc.png"> 

Once page/post templates are represented a bit more visually in Gutenberg, I could see things working a bit like this: you'd select a post template that has a featured image, and then you'd have a position-locked featured image block you can edit.

**Comment by slowaways** [comment]
> Very cool. Here's a screenshot for reference:
> 
> <img alt="screen shot 2019-01-23 at 9 39 26 am" width="1439" src="https://user-images.githubusercontent.com/1202812/51614510-cc00c700-1ef3-11e9-97a2-6bd0c2b881dc.png">
> 
> Once page/post templates are represented a bit more visually in Gutenberg, I could see things working a bit like this: you'd select a post template that has a featured image, and then you'd have a position-locked featured image block you can edit.

"and then you'd have a position-locked featured image block you can edit"
How to do this?

**Comment by kjellr** [comment]
> How to do this?

It's not possible yet, but maybe something to explore in Phase 2 of Gutenberg.

**Comment by boemedia** [comment]
I like the fact that setting a featured image is now more visible to the content manager. However, not all themes require a featured image, so it may cause confusion. Maybe add a checkbox (as some themes do) by default, where people can disable the featured image? I also used to use a plugin where you could select an image in the post as featured image. This could maybe be a nice add-on to the image block: a selectbox to select an image in a post as a featured image too.
