### ISSUE TITLE
Pasting in FontSizePicker replaces the block itself

### ISSUE THREAD

**Issue by kirilzh** [WordPress/gutenberg#21810]
**Describe the bug**
Pasting a custom value in "Custom" size block replaces the block itself.
![image](https://user-images.githubusercontent.com/17088041/80065343-9dccc580-8542-11ea-8876-e8bcfe8da432.png)

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Pages and try to edit a page.
2. Click on text block and empty the custom field.
3. Paste a number in custom field.
4. See that your text block is replaced.

**Expected behaviour**
The size should be pasted in the field

**Screenshots**

**Editor version:**
- WordPress version: (5.5-alpha-47610)
- Gutenberg version: Version 7.9.1 default setting

**Desktop:**
 - OS: Mac OS
 - Browser Chrome 81

**Comment by talldan** [comment]
Is this related to https://github.com/WordPress/gutenberg/issues/21440?

**Comment by kirilzh** [comment]
Yes, it was pointed out to me in [here](https://github.com/WordPress/gutenberg/pull/21457#issuecomment-614243657) that pasting is not working correctly.
