### ISSUE TITLE
Button Block: Switching between Gutenberg plugin and Core causes invalid content

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#21828]
Switching between the Gutenberg plugin and Core causes invalid content in button blocks.

**To reproduce**
1. Activate the Gutenberg plugin
2. Add a button block
3. Deactivate the Gutenberg plugin
4. Button blocks added while the GB plugin is active now show invalid content.

We need to ensure backwards compatibility, because previously button blocks were wrapped in `p` tags and now they are not. This causes the color and alignment options to no longer work properly in the editor. I tested this in both Twenty Twenty and Twenty Nineteen.

**Screenshots:**
Buttons added when GB plugin was active, but is now inactive.
![button-block-issue](https://user-images.githubusercontent.com/34601694/80109980-2d2aa680-854c-11ea-8158-f523203d6794.png)

**Versions:**
- WordPress version: trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? both
- If the Gutenberg plugin is installed, which version is it? master and 7.9.1

**Environment:**
 - OS: Windows 10
 - Browser chrome, firefox
 - Version latest

**Related Issues:**
 - #21685 
 - #21747

**Comment by youknowriad** [comment]
Can you give the exact markup used in the previous version as I'm not able to reproduce with any markup, Thanks

**Comment by dreamwhisper** [comment]
@youknowriad I also saw this with Gutenberg 7.9.1 doing the following, but saw similar issues 

1. Create a button with WordPress 5.4.
2. Install and activate Gutenberg 7.9.1.
3. Edit the page containing the button and click update.
4. Deactivate Gutenberg.
5. Edit the page containing the button - you should see the invalid content warning for buttons.

Diff before/after:
<img width="1415" alt="Screen Shot 2020-04-28 at 9 11 26 AM" src="https://user-images.githubusercontent.com/1271053/80491193-62f6d300-8930-11ea-830e-564fac5269a3.png">

I also saw this happen for some headings and paragraphs.

<img width="1417" alt="Screen Shot 2020-04-28 at 9 50 40 AM" src="https://user-images.githubusercontent.com/1271053/80498530-d4874f00-8939-11ea-85f2-7bc025400465.png">

With the latest changes to master, it appears to occur when a custom color is used.
<img width="1420" alt="Screen Shot 2020-04-28 at 10 30 01 AM" src="https://user-images.githubusercontent.com/1271053/80499641-3dbb9200-893b-11ea-8c74-f40ceae2e845.png">

**Comment by youknowriad** [comment]
> Deactivate Gutenberg.

Oh sorry I misread the issue initially, and yeah the invalidation here is totally expected since an old block (Core) can't know about the updated markup of the same block (Plugin). That's *downgrading* and it's not supported for blocks.

I'd say there's nothing we can do here and that's expected behavior.
