### ISSUE TITLE
Using _embed and _fields query parameters in the same query

### ISSUE THREAD

**Issue by AnouarBenOthman** [WordPress/gutenberg#21834]
When performing a REST API request and adding the _embed and _fields query parameters. the API attempts to skip unneeded fields but does not embed resources that are linked with embeddable set to true.
In some cases we may need _embed and _fields in the same query.
I am requesting the feature to be added to allow the filtering of resources and embedding them (the embeddable ones) at the same time when specifying the _embed and _fields.

Example:
`http://<site>/wp-json/wp/v2/posts?_fields=title,author&_embed=author`

If implemented, the above request should only return title and author, and embed the author.

**Comment by talldan** [comment]
@AnouarBenOthman Thanks for reaching out. Which API is this?

REST API tickets are tracked over in core trac - https://core.trac.wordpress.org/, so this may need to be moved over there.

**Comment by AnouarBenOthman** [comment]
@talldan thanks for your interest. Yes this is concerning REST API

**Comment by talldan** [comment]
Would you be happy to make a ticket on trac? https://core.trac.wordpress.org/

**Comment by AnouarBenOthman** [comment]
yeah sure.

**Comment by w3l** [comment]
If someone else stumbles upon this the ticket is here: https://core.trac.wordpress.org/ticket/49985 and the workaround is using `_links`
