### ISSUE TITLE
[ LinkControl ] Bug with  position when closed

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#21835]
**Describe the bug**
The LinkControl box jumps to top left corner when the block that opened it is switched to edit as html.

**To reproduce**
1. Add a page
2. Add a Quote block
3. Add content to the Quote block
4. Select two words of the quote
5. Make them a link
6. Deselect then select the link you just made
7. With the LinkControl open go to block toolbar and click the dots and then edit as html
8. Observe error

**Expected behavior**
The Link control should disappear

**Screenshots**

![moving-control](https://user-images.githubusercontent.com/107534/80123656-df3b9000-8597-11ea-9b30-dbceb9ababc4.gif)

**Comment by paaljoachim** [comment]
Testing with
WordPress 5.7
Gutenberg plugin 10.1.1
Twenty Twenty One

I was able to follow the above steps and reproduce the error.

![Screen Shot 2021-03-11 at 21 00 36](https://user-images.githubusercontent.com/5323259/110847171-e1d8ce00-82ac-11eb-9241-bd0c97d2c8f4.png)

Adding in the Quote Block nesting PR which should fix this issue.
**Quote: convert to nested blocks**
https://github.com/WordPress/gutenberg/pull/25892

**Comment by fabiankaegy** [comment]
I also tested this and was only able to replicate it in Chrome (Version 94.0.4606.61 (Official Build) (x86_64)) and Firefox (90.0.2 (64-Bit)). Safari (Version 15.0 (16612.1.29.41.4, 16612)) does not appear to have the issue. Continuing to investigate 👍

**Comment by draganescu** [comment]
I retested this on Gutenberg trunk and it seems to not be a bug anymore 🚀
