### ISSUE TITLE
Social Icons do not wrap, prevent selection in certain cases

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#21842]
**Describe the bug**
This is related to #21395 but for the editor.

The social icons do not wrap when they exceed the width of their container.

![social icons in a 33%-width column overlap with content of next column](https://user-images.githubusercontent.com/1238696/80147660-afc15f00-8568-11ea-874f-e587a3591213.png)

In the screenshot above, the "Add Icon" button cannot be clicked because it is behind the block in the subsequent column.

This may be as easy as adding `flex-wrap: wrap` to `.wp-block-social-links .block-editor-block-list__layout` along with a bit of margin on icons (which still allows support for alignment via `justify-content`):

![image](https://user-images.githubusercontent.com/1238696/80147897-0f1f6f00-8569-11ea-94d6-055893742b50.png)

**Expected behavior**
Every block output is responsive.

Also, that's a lot of "+" symbols...

**Comment by annezazu** [comment]
Hey there! Thanks for reporting this. I tried to replicate but wasn't able to do so:

**WordPress 5.4 with TwentyTwenty theme (no other plugins installed):**
<img width="928" alt="Screen Shot 2020-04-23 at 3 34 39 PM" src="https://user-images.githubusercontent.com/26996883/80156130-04b8a180-8578-11ea-874c-2612e0c8d919.png">

**WordPress 5.4 with TwentyTwenty theme and Gutenberg 7.9.1:**

<img width="882" alt="Screen Shot 2020-04-23 at 3 39 44 PM" src="https://user-images.githubusercontent.com/26996883/80156402-adff9780-8578-11ea-8f0f-13c79aabdbfc.png">


@mrwweb can you provide exact steps I can take to replicate this? I seem to be missing something in my attempts! Further, what version of Gutenberg and WordPress are you using? I want to be sure my environment matches yours.

**Comment by mrwweb** [comment]
Just reconfirmed issue with WP 5.4, Gutenberg 7.9.1, and Twenty Nineteen or Twenty Twenty. Tested by placing Social Icon blocks in three-column layout so that need to wrap happens sooner.

@annezazu I don't see any icons wrapping in your screenshots either, so I can't quite tell what was being tested there.

Here's a GIF showing the whole setup:

![inserting social icon blocks into three columns. the blocks exceed the width of the column and icons/buttons beyond the column's width are unclickable](https://user-images.githubusercontent.com/1238696/80236305-d71f3700-860f-11ea-93cb-23eb988a960a.gif)

**Expected Behavior**
Social icons wrap within constraints of parent container.

**Comment by annezazu** [comment]
@mrwweb thanks so much -- this greatly helps clarify things. I'll update the labels here as I can confirm this issue on my end too.

**Comment by desrosj** [comment]
👋🏼 I did some testing on the front end for the default themes today. I found that the social block not wrapping is problematic in almost every one.

Every theme has an issue with mobile (related issue is #21395), but 9 is not always the number of icons. It depends on the block style (default, pill, etc).

![twentyseventeen](https://user-images.githubusercontent.com/359867/88813991-8e839680-d187-11ea-9fcc-19d4eb0510e5.png)
![twentysixteen](https://user-images.githubusercontent.com/359867/88814017-94797780-d187-11ea-9e9c-d2cb2e40960d.png)
![twentyfourteen](https://user-images.githubusercontent.com/359867/88814027-97746800-d187-11ea-8076-9d234dd93d64.png)
![twenty fifteen](https://user-images.githubusercontent.com/359867/88814035-9ba08580-d187-11ea-933e-caaee449aa99.png)
![twenty twelve](https://user-images.githubusercontent.com/359867/88814050-9f340c80-d187-11ea-96cb-5c0493311cde.png)
![twenty ten](https://user-images.githubusercontent.com/359867/88814079-a824de00-d187-11ea-85a8-47a7dc71ac01.png)

**Comment by jasmussen** [comment]
I can't reproduce this, so it seems recent wrapping changes fixes this:

![columns](https://user-images.githubusercontent.com/1204802/110446725-c65ca000-80bf-11eb-8c64-5a477392c524.gif)
