### ISSUE TITLE
Blog Posts Block Doesn't Show all Posts

### ISSUE THREAD

**Issue by ChrissiePollock** [WordPress/gutenberg#21841]
If I have seven posts and set the Number of Items to two and choose the "More" Button option I see two posts then "Load more Posts" then I see two more then I do that a third time and see two more then again and I see the seventh post. That is good.

If I change the Number of items to two or more and choose the "More" Button option, then I see three load and see the "Load More Posts" option. I see the next three but there is no option to see the final post. No more "Load More Posts" choices.

**Expected behavior**
I would expect a Load More Posts option until all the posts are shown.

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Default WordPress.com
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacBook Pro using Catalina 

This came in as a live chat issue, and I replicated it on my test site.

**Comment by annezazu** [comment]
@ChrissiePollock Thanks for reporting this! This block is specific to WordPress.com and I believe was brought over from work within Newspack. Can you report this here? https://github.com/Automattic/newspack-blocks/issues I'm going to close this for now as it's not a core block for Gutenberg.
