### ISSUE TITLE
Default Social Icon labels are inaccessible when used more than once on a page

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#21840]
**Describe the bug**
The default social icon accessible name is usually the name of the icon, e.g. "Mail", "Facebook", etc.

For a screen reader user, this is likely not enough information to understand who/what the icon link is for. This goes from a usability problem to an accessibility error when more than one Social Icons block is used on a page. In that case, we now have duplicate link text going to different pages.

While it is possible for the user to fix this, that is not an ideal solution, especially for a page like "Staff" that might have 30 social icon blocks.

**Expected behavior**
Social Icon accessible name / anchor text should include more contextual information.

- The crudest way to do this would to include the linked URL in the label: Facebook http://facebook.com/example. This is better but only a little.
- If the block can switch to only asking for usernames/handles or this can be derived, then the text could be, "Facebook: Example".
- Better yet, what if the Social Icons block had a "Owner" field (label TBD) that could prefill this for all icons: "Owner on Facebook", "Email Owner". etc.

**Editor version (please complete the following information):**
WordPress 5.4

**Comment by jasmussen** [comment]
Took a stab at this in #29659.
