### ISSUE TITLE
Handbook docs: how to keep them updated?

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#21858]
The [code that imports](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/inc/import-block-editor.php) the content from the Gutenberg repo to create the [Block Editor Handbook](https://developer.wordpress.org/block-editor/) has [recently been locked](https://meta.trac.wordpress.org/ticket/5020) to the stable WordPress branch (wp/5.4). Although there are things that shouldn't be published in the handbook until they are available in the last WordPress version, there are other things that will be a great addition such as general improvements to the docs (ex: [Block Transforms API](https://github.com/WordPress/gutenberg/pull/21734)).

I've got a few follow-up questions and thought that centralizing them in an issue would help with the conversation:

- **Would it be ok that doc updates are cherry-picked to the latest WordPress branch?** (`wp/5.4` as of now). I can't think why this would be problematic but prefer to ask first. cc @jorgefilipecosta @youknowriad 

- **How would we cherry-pick the doc updates? Not technically, but from a process point of view.** I'd say this would be great to have, given that WordPress releases happen on a 6-months scale. However, I'd like to find a compromise that works for us. cc @mkaz @chrisvanpatten 
  - Doing it on a pr-by-pr basis seems a lot of work to me (and prone to leave things behind).
  - A time-bound manner could work: one a month, or bi-monthly, etc. We'd need volunteers that can prepare a curated PR (take all the new additions and curate the ones that make sense leaving out what it's plugin-only).

- **How can we make sure the docs reflect the latest WordPress version?** Look at how some plugin-only docs ([patterns](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/)) have leaked into the handbook despite they not being available in the [wp/5.4 branch](https://github.com/WordPress/gutenberg/tree/wp/5.4/docs/designers-developers/developers/block-api). It's likely this was because the locking ([2020-04-02](https://meta.trac.wordpress.org/changeset/9678)) happened after they had landed ([2020-03-23](https://github.com/WordPress/gutenberg/commit/5956aee125770d3845e069af4b977d1038a5644d)), however, this kind of things are bound to happen again. I haven't looked into this deeply, but I presume we have other cases out there (experimental APIs, things that are plugin-only, etc). Given that core merges don't match exactly Gutenberg versions this is going to be tricky, so I wanted to start the convo about whether this is something we need to fix and how.

**Comment by jorgefilipecosta** [comment]
> Would it be ok that doc updates are cherry-picked to the latest WordPress branch? (wp/5.4 as of now). I can't think why this would be problematic but prefer to ask first. cc @jorgefilipecosta @youknowriad

I think when we are improving the documentation for something that already is part of a WordPress release it should be ok to cherry-pick these changes into the 5.4 branch. As long as we make sure the PR is purely documentation changes for things already part of the release we may even cherry-pick these changes directly instead of adding the label "Backport to WP Core".

**Comment by nosolosw** [comment]
Docs are now back to being pulled from the `master` branch since https://meta.trac.wordpress.org/ticket/5266 so closing this.
