### ISSUE TITLE
Add current post type being edited in Gutenberg

### ISSUE THREAD

**Issue by allysonsouza** [WordPress/gutenberg#21850]
Since Gutenberg became full screen, it's hard to figure out which kind of content are you editing, if it's a page, post, or custom post type. The easiest ways to see that is looking to browser tab or address bar.

Maybe in some place could be added which post type is being edited.

**Comment by skorasaurus** [comment]
This has been implemented in https://github.com/WordPress/gutenberg/pull/17311 

:) It's now listed in the upper right hand corner, for example: 
https://user-images.githubusercontent.com/2236554/64171068-0de3e980-ce95-11e9-83bc-c958aab2d562.png
