### ISSUE TITLE
Aligned cover block:  In the editor, the block width changes depending on the content.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#21855]
**Describe the bug**

If I align a cover block to the left or right, and start typing the first paragraph, the width of the block is reduced.
When I stop typing and save my post or page, the width of the block stays at that same width in the editor. 
It shows at the expected width on the front.

Now If I add a second block inside the cover block, below the first paragraph, but deselect the block without adding content, the cover block is returned to it's expected width.

Now if I remove the inserter/block placeholder, the block is again reduced in width.

**To reproduce**
1. Install and activate for example Twenty Nineteen. I choose this example because the issue is very obvious in this theme.
2. In the editor, add a cover block. Align it to left or right.
3. Start typing in the first paragraph block that becomes available.
4. See how the block width changes. _In Twenty Nineteen, each letter in the paragraph block are showing on their own line,  in a one character column, which is not awesome._
5. Press enter in the block so that a new paragraph placeholder shows.
6. See that the width of the cover block is returned to the original, expected width.

**Expected behavior**
I expect the cover block to stay the same width while typing.
I expect the cover block to stay the same width no matter if a block placeholder is present inside of it.
I expect the width of the cover block to be the same in the editor and in the front.

Themes handle the alignments differently, but I don't think it is a theme issue because I could not find a theme where the width stayed the same, as I expected it to.

**Screenshots**
Editor
![2019-right-align-cover-editor](https://user-images.githubusercontent.com/7422055/80177829-155f2b00-85fd-11ea-86f0-226841177262.png)

Editor with placeholder present:
![2019-right-align-cover-editor-placeholder-showing](https://user-images.githubusercontent.com/7422055/80177969-72f37780-85fd-11ea-9801-c8e6c2e423bc.png)

Front:
![2019-right-align-cover-front](https://user-images.githubusercontent.com/7422055/80177871-37f14400-85fd-11ea-9305-1cb4deb03909.png)

**Editor version (please complete the following information):**
- WordPress version: Version 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  
Tested both with and without Gutenberg with the same result.
- If the Gutenberg plugin is installed, which version is it? Version 7.9.1 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome Version 81.0.4044.122

**Comment by annezazu** [comment]
Thanks so much for this thorough report! I just wanted to note that this is similar to this open issue: https://github.com/WordPress/gutenberg/issues/21836

**Comment by paaljoachim** [comment]
Hi

I am testing with Twenty Nineteen. Gutenberg plugin 9.8. WordPress 5.6.
Added a Cover block. Aligned it right. Began typing. 

This is what I see:
![Screen Shot 2021-01-22 at 13 59 39](https://user-images.githubusercontent.com/5323259/105493773-20dda080-5cba-11eb-8cb9-6e3822bfaaf6.png)

It looks the same with another paragraph below it as well as on the frontend.

I will close this issue. If I am mistaken then please reopen.
