### ISSUE TITLE
The create new block placeholder is cropped

### ISSUE THREAD

**Issue by alshakero** [WordPress/gutenberg#21866]
**To reproduce**
Create a new post

**Expected behavior**
The placeholder shouldn't be cropped.

**Screenshots**
Notice the `g` and the `y`
![image](https://user-images.githubusercontent.com/17054134/80213241-2c237300-8639-11ea-9c18-1ac05183efea.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Gutenberg#master

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 81

**Further notes:**
I can't reliably reproduce this every time. Sometimes a different font shows without the cropping problem. Like this:
![image](https://user-images.githubusercontent.com/17054134/80214531-46f6e700-863b-11ea-845a-010b64c94055.png)

**Comment by karmatosed** [comment]
I am not seeing this unfortunately on the latest build, which means I would love to dive into why you are still.

![image](https://user-images.githubusercontent.com/253067/80234345-eb832400-864f-11ea-947f-357bd574caeb.png)

Just to confirm the above is what I see. Could you confirm you are still experiencing this issue?

**Comment by karmatosed** [comment]
For now, I am going to close this as it's waiting for more information. If extra details are added then this can always be reopened.
