### ISSUE TITLE
Reordering gallery images don't work on Safari

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#21863]
When trying to reorder Gallery block images using the small arrow buttons, the block wrapper gets selected but the images don't move.

It seems to work on Chrome but not on Safari.

cc @nosolosw

**Comment by nosolosw** [comment]
> It seems to work on Chrome but not on Safari.

Would you happen to know how a not macOS user would have access to Safari for testing? [This](https://developer.apple.com/safari/download/) didn't help, so I don't know how to repro :/

**Comment by youknowriad** [comment]
> Would you happen to know how a not macOS user would have access to Safari for testing?

I wasn't aware that you were not a Mac user :) don't worry, I'll try to debug later cause I don't really know how you could test.

**Comment by alshakero** [comment]
I'll debug this if that's OK.

**Comment by alshakero** [comment]
Oh I remember, I have a ready PR for this https://github.com/WordPress/gutenberg/pull/21772
