### ISSUE TITLE
G2: Apply 12px grid to top toolbar more consistently

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#21870]
The G2 efforts in #18667 introduce a new 12px grid to which the user interface and elements align. A visual grid helps create rhythm and balance, and helps guide where elements should land as the UI expands. The block toolbar is designed on such a grid:

![Grid](https://user-images.githubusercontent.com/1204802/80221220-42cfc700-8645-11ea-85b7-01495e31d522.png)

So as to not be overwhelming, the toggled state of buttons in the block toolbar are 32x32px:

<img width="798" alt="80192758-f7eb8a80-8617-11ea-9ec5-049c7ca9c847" src="https://user-images.githubusercontent.com/1204802/80221457-9d692300-8645-11ea-84bd-70a8d180e86c.png">

This is optically well balanced.

The top toolbar is partially adhering to that grid at the moment. It's 60px tall (divisible by 12), icons are 24x24 and have 12px spacing between them, and the inserter is 32x32. The spacing to the left of the inserter is there to balance out the inserter next to the heavy dark area. But the spacing isn't totally right. Here's a suggestion to tweak that:

<img width="861" alt="Screenshot 2020-04-24 at 16 05 03" src="https://user-images.githubusercontent.com/1204802/80221515-ad810280-8645-11ea-86b6-9bab810c8f2c.png">

Another inconsistency is that button hit areas are 36x36, except the inserter which is balanced to match the block toolbar. This causes a small jump when focus travels:

![one focus style](https://user-images.githubusercontent.com/1204802/80221810-1a949800-8646-11ea-9432-9f63b5ee5d3d.gif)

Additionally, buttons on the right, including the toggled state for sidebar(s), are 36px:

<img width="413" alt="Screenshot 2020-04-24 at 16 09 30" src="https://user-images.githubusercontent.com/1204802/80221855-2da76800-8646-11ea-9c1a-01547ee24a5e.png">

So there is an opportunity to not just adjust the margins and paddings to align better to the grid, but to explore whether unifying on either 32px for all buttons, or 36px for all buttons, would make sense here.

**Comment by karmatosed** [comment]
Love it and I am very keen on anything that provides more consistency.

**Comment by mapk** [comment]
Oooh, grids in the top toolbar! ❤️ Thank you for this.

I wanted to note one discrepancy I've noticed. There are two areas where an icon button can live next to another icon button that has an active background color. These two scenarios seem to be treated differently.

**Scenario 1 (left side)**

![81083509-875f2c00-8ea9-11ea-9ffc-6f0244b5a04d](https://user-images.githubusercontent.com/617986/81221139-480f0900-8f97-11ea-8faf-18feec2065e1.png)

**Scenario 2 (right side)**

![81083354-53840680-8ea9-11ea-8b45-062102cd6efb](https://user-images.githubusercontent.com/617986/81221172-53623480-8f97-11ea-8cf6-f0066050c296.png)

Is there a way we can align these two better? The left side is visually more appealing with the added space in between.

As noted in #22110, the ellipses icon is optically smaller in size, but it still feels awkward to have the click area of it adjacent to the background color of the Settings icon.

**Comment by jasmussen** [comment]
Through various refactors, I would consider this one mostly addressed. I think there are opportunities to refine this further in implementation, but as a standalone ticket this seems to have mostly been adressed!
