### ISSUE TITLE
bbPress - buddyPress - front-end comments & Inserter & Embeds

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2187]
Now in this initial prototyping phase dont be unwillingly selfish. 
Think how bbPress forum owner(s) would like to give Users option to insert Embeds in forum Topics, Replies. I cannot give any suggestion right now, because I dont have any,

Same is for front-end discussion/comments. Before WP core was not known precise to think about it, and mostly ignored this issue. We were left alone to try different snippets to see what worked. Most of them not.

**Comment by StaggerLeee** [comment]
Will just close it, not real issue in this meaning of word.

**Comment by youknowriad** [comment]
Thanks for the issue, with the generic block editor being worked on in #13088 use-case like this will be possible. It will provide a component to change the value of a block list, and it will be the responsibility of the user to "save/persist/do whatever" with the block list.
