### ISSUE TITLE
Theme's editor palette colours not previewing in editor

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#21881]
**Describe the bug**
As of 7.9, it looks like the editor colours provided by the theme don't preview in the editor; they used to be added inline on the element, but now are not. Custom colours seem to work as expected. 

I can reproduce this in Twenty Nineteen; Twenty Twenty includes its custom colours in the editor styles so it still works there; I thought it may be a change to move away from inline colours, but I couldn't find a related ticket; please close if that is the case, though! 

**To reproduce**
1. Start with a test site running Twenty Nineteen, and Gutenberg 7.9 or 7.9.1.
2. Add a paragraph block to a page or post.
3. Give the paragraph block a colour and a background colour, using the theme's colour palette.

**Expected behavior**
That the colours would be applied.

**Screenshots**
**Note:** it looks like the text is disappearing in Twenty Nineteen -- it's actually the white text colour coming from the theme when the background is set to a darker colour. It is applying the `.has-background` class, and the related padding, but no background colour.

![twenty-nineteen-colors](https://user-images.githubusercontent.com/177561/80258086-38a6cc00-8637-11ea-8d8c-7834c1c15ac9.gif)

![image](https://user-images.githubusercontent.com/177561/80258124-5116e680-8637-11ea-9ab2-6eeaab9c0306.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 7.9 and 7.9.1.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version 75

**Comment by skorasaurus** [comment]
I'm not able to reproduce this on 11.2 Gutenberg. 

If you're still able to reproduce this in the newest version of Gutenberg, please reopen.
