### ISSUE TITLE
Add @babel/plugin-proposal-class-properties to allow for class property assignment syntax

### ISSUE THREAD

**Issue by saramarcondes** [WordPress/gutenberg#21884]
**Is your feature request related to a problem? Please describe.**
Gutenberg's babel configuration does not allow for the class property assignment syntax. This prevents devs from using syntax that has been standard in most React projects for years. For example:

```jsx
class Foo extends Component {
  state = {
    // this is the default state for a component, no constructor necessary
    bar: 'baz',
  };

  static defaultProps = {
    // this is the default props, no need to push them to after the class is declared
    karma: 'chameleon',
  };

  handleClick = ( e ) => {
    // no need to remember to bind this function in the constructor
  };
}
```

**Describe the solution you'd like**
Adding the babel plugin `@babel/plugin-proposal-class-properties` will allow us to use this common syntax.

**Comment by gziolo** [comment]
It includes two stage 3 proposals:

- https://github.com/tc39/proposal-class-fields
- https://github.com/tc39/proposal-static-class-features

We enable usually stage 4 proposals. The current configuration is optimized for that. 

/cc @aduth and @adamsilverstein

**Comment by aduth** [comment]
@gziolo Correct, my understanding is alignment to "Finished" (stage 4) proposals only.

For third-party developers, I think it may still be possible to work around this by providing a custom Babel configuration which extends the WordPress preset to add the plugin. I believe it may just be a matter of adding `babelrc.js` to a project which uses `@wordpress/scripts`, where the configuration includes:

```js
module.exports = {
	presets: [ '@wordpress/babel-preset-default' ],
	plugins: [ '@babel/plugin-proposal-class-properties' ],
};
```

At least within Gutenberg, a main use-case for class properties (i.e. React class component state) is being superseded by function components and hooks ([`useState`](https://reactjs.org/docs/hooks-state.html)).

As action items, I might consider:

- Do we document this "policy" anywhere? If not, there should be.
- Close independent proposal requests in favor of specification update tasks, if and when applicable.
- Bring for discussion in a [weekly JavaScript chat](https://make.wordpress.org/meetings/) if there's any disagreement or questions about positions on language standards and proposals.

**Comment by aduth** [comment]
Closing in favor of task: #21978
