### ISSUE TITLE
Centre Aligned Image is no Longer Centre Aligned in Editor

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#21885]
The centre-alined image doesn't appear centre anymore. If the image is thumbnail or medium, it's easier to see the issue.

<img width="1366" alt="Screenshot 2020-04-25 at 01 53 51" src="https://user-images.githubusercontent.com/908665/80267198-a4208600-8697-11ea-8516-7a13fc586b91.png">

I initially thought a theme issue, but deactivating Gutenberg plugin made the image appear centred.

<img width="1366" alt="Screenshot 2020-04-25 at 02 03 05" src="https://user-images.githubusercontent.com/908665/80267609-cc10e900-8699-11ea-8d28-04d9c2d6c030.png">

Tested with Chrome 81.0.4044.113, Twenty Twenty theme.

**Comment by nfmohit-wpmudev** [comment]
Hey @iamtakashi !

I was able to replicate this issue. According to my initial investigation, I _think_ this issue might have been introduced in this [PR](https://github.com/WordPress/gutenberg/pull/21822), but I'm not 100% sure. I've [commented](https://github.com/WordPress/gutenberg/pull/21822#issuecomment-619412597) on that PR for some re-confirmation and I hope we can work on a PR to address this soon.
