### ISSUE TITLE
Add class to table row makes table block locked and unusable

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#21887]
**Describe the bug**
While editing the Table-block in HTML, I try to add a class by `class="xyz"` to any tr or td. Then the block is locked, and I can not continue editing the block as expected. When I then press the buttons "Konvertera till HTML" and "Lös upp" (Convert to HTML and Dissolve) nothing happens in the browser. I'm stuck.

**To reproduce**
1. Go to any page or post
2. Click on Add table block
3. Create a table with 2 column and 4 rows.
4. Add dummy content to all cells.
5. Click the "Edit as HTML-option" for the block
6. Add `class="xyz"` to any tr or td.
7. Click outside block.
8. See error in console.
9. Try to click the two buttons in the table-block. Nothing happens  

**Expected behavior**
I expect the editor to continue work without any problem, as I only add a class to tr/td.

**Screenshots**
Console error.
![image](https://user-images.githubusercontent.com/11491369/80275743-8d078580-86e3-11ea-8605-80ae44da7743.png)
The two buttons.
![image](https://user-images.githubusercontent.com/11491369/80275784-cf30c700-86e3-11ea-8bce-23ce13526baa.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: Macos 10.14.6
 - Browser Chrome 
 - Version 81.0.4044.92

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by karmatosed** [comment]
I can confirm this as a bug. I think being able to edit the HTML in that mode makes sense with adding a class, so let's flag this as a bug.

**Comment by talldan** [comment]
This isn't a bug related to the table block, it'll happen with any static block when modifying certain bits of HTML.

If we wanted to solve this just in the context of the table block, we'd need to be able to specify custom class names for table sections, rows, columns, which is pretty much impossible from a UI perspective without a way to select those regions.

Previous similar issues:
- https://github.com/WordPress/gutenberg/issues/8450
- https://github.com/WordPress/gutenberg/issues/8813
- https://github.com/WordPress/gutenberg/issues/14672

I think this is better related to the wider topic of block validation:
- https://github.com/WordPress/gutenberg/issues/7604
- https://github.com/WordPress/gutenberg/issues/21703

As such I'll close this issue in favour of the other discussions.
