### ISSUE TITLE
Text after gallery is really close to gallery

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2188]
This was reported by @helen:

> Why is the text right up under the gallery in the preview but not in the editor? Adding an extra line (entire block) doesn't fix it :(

I can replicate this using Twenty Seventeen:

![2017-08-03 at 14 46](https://user-images.githubusercontent.com/253067/28924865-068e289a-785b-11e7-81b5-c81278e81f85.png)

Whilst technically a front end theme issue, it would be good to at least avoid this on every theme - it's going to be common.

**Comment by mtias** [comment]
This is just a matter of providing default margins for gallery, should be a simple change if you want to go for it.

**Comment by mtias** [comment]
This was done in https://github.com/WordPress/gutenberg/pull/2291
