### ISSUE TITLE
Edit/Hide author selector inside Gutenberg editor

### ISSUE THREAD

**Issue by Semirxbih** [WordPress/gutenberg#21898]
Hi all,

How would one be able to edit the "Author" name and or hide the author picker completely from the Visibility and Status metabox?

**Comment by annezazu** [comment]
Hi @Semirxbih! Glad to see another soccer fan/player here (saw on your profile). This repository is dedicated to building Gutenberg and reporting bugs. As a result, your request is better suited for our forums: https://wordpress.org/support/forums/ Please share there for now but know this repository is here for any bug reports.
