### ISSUE TITLE
Add Block: Index

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#21893]
It would be interesting to have a block that builds a content index based on the headings.
When I need an index I use an anchor. But an automatic index made it much easier.

Example:
----------Block Index----------
**Index:**

- Heading 1
- Heading 2    _(when clicking it moves the page to the Heading 2)_
- Heading 3
--------------------------------

### Heading 1
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget ante tortor. Nulla auctor elit non purus auctor, nec dapibus nulla luctus. Nullam orci justo, rutrum quis auctor ut, semper congue lacus. Etiam ornare ut est sit amet suscipit. Nulla ut feugiat velit, a ultricies purus. Praesent eu lorem accumsan, tristique erat et, lobortis magna. Nam vitae accumsan nunc, luctus dapibus est.

### Heading 2
Curabitur ac nisi auctor lectus convallis aliquet. Proin eget pharetra lacus. Curabitur sed pulvinar eros. Nullam malesuada dapibus aliquet. Sed dictum leo in orci placerat, a pellentesque dui semper. Sed eu sollicitudin ipsum. Quisque eu massa arcu. Aliquam congue dignissim venenatis. Fusce quis lectus ante. Ut cursus dapibus risus. Cras eleifend dolor a nunc pretium condimentum.

### Heading 3
Aenean ornare risus sed arcu cursus, a rutrum libero fermentum. Proin semper elementum lacus, id tempor libero dapibus et. Donec pretium sagittis nibh, et tempus risus bibendum mollis. Maecenas posuere sollicitudin turpis in faucibus. Quisque maximus magna et iaculis sollicitudin. Suspendisse potenti. Ut consequat gravida ex eget congue.

**Comment by ricjcs** [comment]
I noticed now that in the Heading Block options you can already add an anchor, without having to add an html command, which was how I did it.

So this feature request is less relevant. However, it may have some utility. If not, let this issue be closed.

**Comment by Soean** [comment]
Hi @ricjcs, thanks for your feedback. We already have a ticket about a "Table of contents" block #11047. This is the same idea, so I close this ticket. Let's discuss this in the other one.
