### ISSUE TITLE
Adding class in editor to block created with @wordpress/block results in invalid block on editor reload

### ISSUE THREAD

**Issue by houblon** [WordPress/gutenberg#21897]
Steps to reproduce:
* npm init @wordpress/block test-block
* enable block plugin
* add block to post
* add class to block via the "Additional CSS class(es)" in the block inspector
* save post
* reload editor

Console error with example class "is-style-test":

```
Content generated by `save` function:

<p class="wp-block-create-block-test-block">Test Block – hello from the saved content!</p>

Content retrieved from post body:

<p class="wp-block-create-block-test-block is-style-test">Test Block – hello from the saved content!</p>
```

This error also occurs if classes are added via styles registered either in the block plugin or a theme.

**Comment by houblon** [comment]
Another thing, even if I don't change any of the code of the scaffolded block, if I add a style via the "Additional CSS class(es)" in the block inspector, I get the same error.

**Comment by gziolo** [comment]
It looks like it's a general issue with the order of loading core scripts. `@wordpress/block-editor` register all hooks that operate on the block registration so the custom block registration should trigger after they are in place. It isn't the case for the sample block scaffolded with `@wordpress/create-block` because it depends only on 'wp-blocks', 'wp-element', 'wp-i18n' and 'wp-polyfill'. I believe that the only way to fix it for good is to defer running all those registration-related hooks until the editor is about to get initialized. /cc @youknowriad @aduth

**Comment by kebbet** [comment]
Could https://github.com/WordPress/gutenberg/issues/21887 be a derived from this bug too?

**Comment by gziolo** [comment]
> Could #21887 be a derived from this bug too?

Nope, it's a different issue. Core blocks aren't affected by the issue I described.

**Comment by houblon** [comment]
@gziolo, thanks for the insight. With 'wp-editor' added as a dependency, the block loads without error.

Is there a reason 'wp-editor' isn't a dependency by default? I can imagine there being cases to exclude it, but am not familiar enough with the Block API to know.

**Comment by ugenegrg** [comment]
Hi there, is this issue still on progress or can anyone point me the correct place. As I am still getting this same issue after adding a class name and refreshing.
The process to replicate is exactly as mentioned above. 
Process
Ran npx @wordpress/create-block flipon
Activated the plugin
Added the newly created block. Added a classname "orange". Clicked on update and Refreshed the page.
Here is the screenshot link: https://tinyurl.com/yyv24o73
Thanks

**Comment by skorasaurus** [comment]
@gziolo was there PR for this since it had the in progress label?

**Comment by gziolo** [comment]
I tried with the latest version of `@wordpress/create-block` and I can't reproduce the issue anymore.

I get the following HTML saved:

```html
<!-- wp:create-block/test-block {"className":"is-style-test"} -->
<p class="wp-block-create-block-test-block is-style-test">Test Block – hello from the saved content!</p>
<!-- /wp:create-block/test-block -->
```

It validates every time I refresh.
