### ISSUE TITLE
Vertical navigation block is missing a class on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#21890]
**Describe the bug**
In the editor, the vertical variation of the navigation block can be identified with
`is-vertical` but this CSS class is not present on the front, so there is no way to tell the 
horizontal and vertical styles from the other.

**To reproduce**
1. Add a vertical navigation block to a post or page
2. Add a horizontal navigation block too, in case you wish to compare them.
3. Save
4. View the front

**Expected behavior**
I expect the CSS class and the existing styles to be applied to block.

**Screenshots**
![is-vertical-is-missing](https://user-images.githubusercontent.com/7422055/80283635-5fd5ca00-8719-11ea-96af-7ac9ab249c9d.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4
Gutenberg 7.9.1

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: Chrome Version 81.0.4044.122

**Comment by karmatosed** [comment]
Great catch @carolinan as that makes sense for me too.

**Comment by talldan** [comment]
Just changing this to a bug as currently the editor and front end versions of the block don't match (Navigation (vertical) is displayed horizontally in the post, but vertically in the editor) due to the missing classname.

**Comment by strarsis** [comment]
So I hope using `.wp-block-navigation:not(.horizontal)` as selector is a functional workaround.
