### ISSUE TITLE
Image uploading not refreshing all the time

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2189]
Reported via @helen:

>  Uploading an image does not seem to be working, however. I refresh the editor screen and then it works.

This doesn't happen all the time. I have managed to get it working a few times but also sticking others. I don't seem currently able to get it to stick. I have experienced it today on same freshly pulled latest version. I don't have a video as can't replicate it currently.

What I saw (which may be different) was:

- Upload an image
- It doesn't show a progress bar, nothing at all indicates this is happening
- Change to 'Media Library' tab and you get to see the image
- Tab back to 'Upload' and you see a progress

**Comment by helen** [comment]
FWIW I think there may have been some kind of JS error when that happened to me, because I also noticed that the admin menu scrolling/pinning behavior was broken. No idea what caused the error or what it was, I did not think to look at the time.

**Comment by karmatosed** [comment]
Thanks for the extra info. I think this probably can close, or at least reopen if it happens again. I've tried a few times to get it to happen to me again, but it's not.
