### ISSUE TITLE
Core themes compatibility with simplified Button block markup

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#21909]
The simplified Button markup introduced in https://github.com/WordPress/gutenberg/pull/21266 appears to require updates in the core themes so that the new buttons match the legacy button styling. In the following themes, if you add some new buttons (select a mix with outline styles), their styling doesn't match how the theme handles legacy buttons. After the fixes in https://github.com/WordPress/gutenberg/pull/21642 and https://github.com/WordPress/gutenberg/pull/21816, the legacy buttons are looking pretty good! Looks like it's now the new markup that needs addressing.

Some of the button styles below are closer than others (e.g. the difference might only be a lack of uppercase or underline, but for others like 2019, the difference is more pronounced). Note that in each of the screenshots under "New buttons", two of the buttons should be rendered with outline styles.

#### Twenty Nineteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80335617-26779880-8898-11ea-8b4e-d7c76027d4c0.png) | ![image](https://user-images.githubusercontent.com/14988353/80335490-c54fc500-8897-11ea-9993-b94ca6b95121.png) |

#### Twenty Seventeen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80335670-5cb51800-8898-11ea-989c-ab4be496d353.png) | ![image](https://user-images.githubusercontent.com/14988353/80335689-6c346100-8898-11ea-97eb-525da65bd386.png) |

#### Twenty Sixteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80335812-bb7a9180-8898-11ea-9870-72623d141108.png) | ![image](https://user-images.githubusercontent.com/14988353/80335763-a140b380-8898-11ea-922b-03ec83b4e79d.png) |

#### Twenty Fifteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80335878-f977b580-8898-11ea-90a0-2f889c9d228e.png) | ![image](https://user-images.githubusercontent.com/14988353/80335904-085e6800-8899-11ea-9155-983aec9152a4.png) |

#### Twenty Fourteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80335936-27f59080-8899-11ea-8e09-c9d98a3d06dc.png) | ![image](https://user-images.githubusercontent.com/14988353/80335984-393e9d00-8899-11ea-9bf4-04be619a1af8.png) |

#### Twenty Thirteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80336008-58d5c580-8899-11ea-868b-2d6582c664f3.png) | ![image](https://user-images.githubusercontent.com/14988353/80336016-65f2b480-8899-11ea-9dcb-80e98fe9d445.png) |

#### Twenty Twelve

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80336065-86bb0a00-8899-11ea-83a7-e32507161846.png) | ![image](https://user-images.githubusercontent.com/14988353/80336077-90dd0880-8899-11ea-94dd-d1f2cd8a55a3.png) |

#### Twenty Eleven

| Legacy buttons | New buttons |
| ------- | ------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80336108-a94d2300-8899-11ea-8827-3c013d5de0be.png) | ![image](https://user-images.githubusercontent.com/14988353/80336120-b23df480-8899-11ea-885e-2d2a874c32dd.png) |

I haven't included themes 2010 and 2020 in this list because they're looking pretty good to me so far.

Is this the best place to log this issue for these themes, or should individual tickets be opened separately? (I wasn't sure if there might be individual tracking issues already)

CC: @youknowriad

**Comment by youknowriad** [comment]
I'm not sure about whether we should have individual issues or tickets but it's definitely better to move this issue to Core Trac.
