### ISSUE TITLE
Where does featured image belong?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2190]
From @helen:

>  I wish that the featured image showed as a block where the theme puts it, or maybe just always above the title. Not a side setting.

This is a great point. Whilst in v1 I can see a sense in having it to the side, we have a chance to explore where the best place is for everything moving forward. Where could the best place be for featured images?

**Comment by mtias** [comment]
See https://github.com/WordPress/gutenberg/issues/2181 :)

**Comment by karmatosed** [comment]
Ah great! Closing this then.
