### ISSUE TITLE
In Full site editing mode, blocks additional CSS classes are not shown in frontend

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#21903]
**Describe the bug**
After adding an additional CSS class in a block in Full site edition page the class is not rendered in frontend.

**To reproduce**
1. Install and activate the Gutenberg Plugin.
2. Go to Gutenberg > Experiments, and enable "Full site editing" option.
3. Go to Gutenberg > Site Editor (beta), add a block and add a custom class to the block.
4. Save the templates and open the site in a new tab.

**Expected behavior**
The custom classes added to the blocks should be rendered in frontend.

**Desktop**
 - OS: Windows 10 Professional 1803
 - Browser: Firefox Developer Edition
 - Version: 75.0b11

**Additional context**
- WordPress 5.4
- Gutenberg 7.9.1

**Comment by apeatling** [comment]
Full site editing specific blocks will be fixed by https://github.com/WordPress/gutenberg/pull/23007

**Comment by noahtallen** [comment]
@JustinyAhin can you confirm if this was fixed by #23007?

**Comment by JustinyAhin** [comment]
> @JustinyAhin can you confirm if this was fixed by #23007?

@noahtallen I can confirm the issue is fixed.

**Comment by noahtallen** [comment]
:tada: glad to hear!
