### ISSUE TITLE
@wordpress/element package to avoid incompatibilities between versions

### ISSUE THREAD

**Issue by muhammedmagdi** [WordPress/gutenberg#21902]
Hi, I have a problem to understand one line at the docs.
One of the reasons for @wordpress/element package is to ensure that every plugin operates on a single centralized version of the code.
It is stated like that in the docs.
I need to understand this part.
Let's say I am using @wordpress/element 1.0.0 for example and another external plugin uses @wordpress/element 2.0.0 .. How @wordpress/element is aimed to have a single centralized version while the package itself will be updated every time React updates. 
I just would like to understand this part.
Thanks!

**Comment by muhammedmagdi** [comment]
@aduth Any explanation would be much appreciated.
Thanks!

**Comment by muhammedmagdi** [comment]
Does that mean one single centralized version for all packages in Gutenberg?
If I am creating another plugin, should I use it? or create my own `element` package?

**Comment by aduth** [comment]
In Gutenberg and in any plugin which uses [`@wordpress/scripts`](https://npmjs.com/package/@wordpress/scripts) to build their JavaScript (or at least the underlying [`@wordpress/dependency-extraction-webpack-plugin`](https://github.com/WordPress/gutenberg/tree/master/packages/dependency-extraction-webpack-plugin)), even though you have `import` statements in your code, it doesn't actually bundle the package code. Those import statements are transformed to equivalent on the global.

So:

```
import { createElement } from '@wordpress/element';
```

Is actually converted to:

```
var createElement = wp.element.createElement;
```

And `wp.element` is always assigned to the same value based on which version of WordPress you run, regardless of what version you define as a dependency in your `package.json`.

**Comment by muhammedmagdi** [comment]
@aduth If I am creating an individual system for WordPress far away from Gutenberg but built on React. Think of it like another Gutenberg (but it isn't).
This system is supposed to work with older WordPress versions. Should I use `@wordpress/element` or create my own element package.

**Comment by aduth** [comment]
If the code is run inside WordPress, then it's best if your script depends on the `wp-element` handle and uses the `wp.element` global. This is what the above `@wordpress/scripts` and `@wordpress/dependency-extraction-webpack-plugin` are configured to do, and what ensures that every plugin is using the same version of React.

If the code is run outside WordPress, then you can still use `@wordpress/element` directly, but you won't have the same guarantees about consistent version unless you create a similar system for whichever environment you are running in.

**Comment by muhammedmagdi** [comment]
@aduth Thanks a lot for the explanation. I got it now.
and I tried to use the `dependency-extraction-webpack-plugin` and `wp-script` and it yes extracts the wordpress dependencies and it generates php file contains the dependencies I need but there is one problem for me. 
> And `wp.element` is always assigned to the same value based on which version of WordPress you run, regardless of what version you define as a dependency
If the user is using wordpress version 4.x.x, wp.element will return undefined of course. I didn't try but I guess. So what are your thoughts about this? 
Should the WordPress version be checked and if it is less than 5 then the user should at least install "Gutenberg" as an individual plugin and activate it which I don't know really will cause issues with the older versions of WordPress or what should be the solution in this case?

**Comment by aduth** [comment]
I think, if anything, it may be a matter of documentation for `@wordpress/scripts` or `@wordpress/dependency-extraction-webpack-plugin` that any "extracted" dependencies rely on those scripts to be registered in the version of WordPress in which the plugin is run. I don't really see it as being a new issue, since technically this sort of problem can occur for any version of WordPress where a script was added (or even updated), including versions much earlier than WordPress 5.0. The main difference might be that these tools try to handle the dependencies transparently, without developer intervention. It's primary for a convenient developer experience, though it could be seen as reducing some of the visibility to what goes on behind the scenes.
