### ISSUE TITLE
Add a "lightbox" style for images.

### ISSUE THREAD

**Issue by fastpenguin91** [WordPress/gutenberg#21907]
**Is your feature request related to a problem? Please describe.**

The image block does not always display the desired size, but the optimal image size would disrupt the flow of the page.

**Describe the solution you'd like**

I think having a "lightbox" style as one of the styling options on the default image block would be the optimal.

**Describe alternatives you've considered**
Thought about extending the core image via coding a plugin - this is good too.
Just installing a separate plugin/block, but then you run into problems with having an extra plugin for a very minimal enhancement.

If you do decide on approving this ticket I'd like to try working on it myself.

**Comment by pwkip** [comment]
Just some random thoughts:
- I agree that clicking an image and opening it in a lightbox or modal is in 99% of cases a good idea
However, there are many ways to create and style a lightbox, and I don't think there is a HTML spec for this. This means that there are maybe hundreds of opinionated ways to create a lightbox, and I'm afraid that as long as there is no tried-and-true method of creating a lightbox, it does make more sense to just have a plugin for this. There are a couple of lightbox plugins right now that do a pretty good job. I have used some of them, and I must say that for a given site I prefer one, and for another I prefer another plugin.
- I'm not 100% sure about it, but I don't believe that WP actually loads any scipts and styles by default on the front-end of a website, unless maybe if it's some really essential stuff. I think loading extra styles and scripts to the front-end and forcing it on every WP website out there, has a pretty large impact and I'm not sure if this is the way WP should go.
- I think that, if we would add lightboxes in core, it should be very minimal.

**Comment by karmatosed** [comment]
Thanks for suggesting this @fastpenguin91. My first thoughts here are that this would make a great plugin addition. That said, I could potentially see it as a style variation or something specific to the theme. I don't think that having it without exploration theme or plugin options, in core fits, but that might be something to bring in overtime.

Let's get a label on this to get more insights and thoughts.

**Comment by enriquesanchez** [comment]
Hi @fastpenguin91!

I agree with @pwkip and @karmatosed. This feels more like theme/plugin territory.

**Comment by fastpenguin91** [comment]
Thanks for the feedback @enriquesanchez @pwkip @karmatosed . That does leave one quick question.

Would it be a bad idea to implement this feature as an extension to the core/image block? I'm still a bit new to the ecosystem, but It appears that generally it's recommended to create your own block. I've tried to extend the core/image but so far not able to without breaking existing blocks. I'm assuming it's just my lack of knowledge of the block filters, but maybe I'm trying to do something that's bad practice anyway?

**Comment by pwkip** [comment]
i'd say go for extending the core/image block. unless if you want to go really fancy, then a new block might make more sense

**Comment by karmatosed** [comment]
Extending for me makes sense as you can just hook into it. Even with a style variation perhaps. For now, let's close up this issue but we can always reopen.
