### ISSUE TITLE
Image Block: "Reset" button does not reset according to a new column context

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#21912]
GIF:

![cols](https://user-images.githubusercontent.com/1204802/80355154-03d58780-8878-11ea-85d6-acc41b7ba419.gif)

Here's what happens / steps to reproduce:

- Insert a columns block with an image in one column.
- Observe how the image block sizes correctly to fit its column, even as the number of columns changes.
- Resize the image block
- Change the number of columns
- Click the "reset" button for image dimensions, and observe how it doesn't actually reset the image dimensions to the new column.

Expectation: 

Reset button always resets to the dimensions of the context it's in, rather than what context it used to be in.

**Comment by karmatosed** [comment]
> Reset button always resets to the dimensions of the context it's in, rather than what context it used to be in.

This feels like the right expectation so 👍

**Comment by jasmussen** [comment]
This issue appears to have been fixed!

![hey](https://user-images.githubusercontent.com/1204802/128189935-d6c9f863-19d5-40e6-84c4-111a2c0dffed.gif)
