### ISSUE TITLE
Add Theme Support setting to turn off default wide alignment for all core blocks

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#21910]
**Is your feature request related to a problem? Please describe.**
I have come across it a view times now, that clients were very confused by the wide alignment being automatically turned on on the `media & text` block. It just behaves differently than the others from the gettgo and therefore needs one more click every time it gets inserted. 

**Describe the solution you'd like**
An option like `add_theme_support( 'disable-default-wide-alignement' )`

**Describe alternatives you've considered**
Another option would be to add hooks into the core blocks where I can change the behavior on a block level.

**Comment by annezazu** [comment]
Hey @fabiankaegy! Thanks for flagging this. It looks like you aren't the only one who has been frustrated by this as we have an open issue here for the same kind of scenario:  https://github.com/WordPress/gutenberg/issues/20941  I'm going to close this out in favor of that  prior issue but welcome you to comment there with your thoughts.
