### ISSUE TITLE
Add constrain proportions when modifying image size

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#21918]
**Is your feature request related to a problem? Please describe.**

When you add an image, you have the option to resize it - either manually by entering width/height, or by selecting a percentage.

When you are using manual resizing, sometimes (or maybe always) you'd want to keep the correct proportions, otherwise, your image will be squashed.

![Screenshot 2020-04-27 at 14 36 46](https://user-images.githubusercontent.com/8638515/80372917-9126d500-8894-11ea-8914-e1fa89e54f30.png)

**Describe the solution you'd like**

A good thing to have, above or below the `Image dimensions` option, would be to have a checkbox that says: Constrain Proportions. In Sketch, it's denoted by a lock (I think in Adobe products as well), and Figma has that on the right side as a lock.

**Describe alternatives you've considered**

I didn't think of alternatives as this should be added to the core IMO.

**Comment by karmatosed** [comment]
Interesting idea @dingo-d. My first thought is that because you have the ability to change size and percentage, it might be ok to allow more macro-control without constraint here. If that's not the case, then maybe we could take a slightly different approach to an option or lock and have it auto-resize once a width is put in, then you have to over-ride the constraint? Just an option to maybe iterate here.

**Comment by dingo-d** [comment]
More granular percentage option might work, current 4 options oftentimes don't cut it. 

I worry that auto-resizing, then override could be weird for users. The constraint lock is something that is widely used in design tools I think, so it's something that is known to many and seems to be a good UX.

I'd love to see more iterations on this definitely 🙂

**Comment by paaljoachim** [comment]
Constraining the image dimensions proportions is a very good idea!
Here is a quick sketch.

![Image-dimension-aspect-ratio-lock](https://user-images.githubusercontent.com/5323259/107532475-3c074600-6bbe-11eb-9936-166047fd98d0.jpg)

**Comment by kellychoffman** [comment]
A few thoughts:

The link icon is used more consistently across image editing tools. Lock could make it appear like you are unable to edit the dimensions. 

The interaction should clearly be a toggle. I don't believe we have any icon toggles, but we do have the toggle bar below with text. If we draw from that, an updated design suggestion would be: 

<img width="631" alt="Screen Shot 2021-02-10 at 9 25 54 AM" src="https://user-images.githubusercontent.com/5835847/107547365-35f37400-6b82-11eb-82af-4d84c357236c.png">

Using the current icon component, it would appear something like this, which is not as obvious but doable: 

<img width="632" alt="Screen Shot 2021-02-10 at 9 33 42 AM" src="https://user-images.githubusercontent.com/5835847/107548290-507a1d00-6b83-11eb-8c23-ad25626da91b.png">

Should also include a tooltip when hovered that says "Constrain proportions".

**Comment by mtias** [comment]
Also related: https://github.com/WordPress/gutenberg/issues/27331

**Comment by swinggraphics** [comment]
The current behavior is very confusing. If you change one value, the image resizes proportionally, but the value of the other field does not change. For example, if you start with an image that is 800x800 and change the width to 250, the image will actually be 250x250, but the Height value in the settings panel remains 800.

Edit: There's an additional bug: If you delete the value in one of the fields, it will cause an error when the block loads in the editor, outputting NaN, and causing the "This block contains unexpected or invalid content" message to appear.

**Comment by zero2webmaster** [comment]
Constrain image proportions is absolutely critical. Please add this functionality ASAP.

**Comment by mtias** [comment]
@richtabor I believe this should be done now

**Comment by richtabor** [comment]
> @richtabor I believe this should be done now

Yup, as part of the aspect ratio + height/width overhaul in https://github.com/WordPress/gutenberg/pull/51545. I'll close.
