### ISSUE TITLE
Feature request - Markdown block: convert Markdown to blocks

### ISSUE THREAD

**Issue by alshakero** [WordPress/gutenberg#21913]
This is a feature request. 

Yesterday I was moving some posts from Jekyll to WP.com. The Markdown block works brilliantly but _native_ Gutenberg blocks are far nicer to interact with and customize.

It seems like the MD block converts the Markdown to blocks anyways but once I click on it, the Markdown is shown again and I can't interact with the automatically-created blocks.

My workaround was to copy these blocks and paste them to get rid of the Markdown.

**Describe the solution you'd like**
It would be super nice to press a button in the Markdown block to have the generated blocks persisted and forget about the Markdown.

**Describe alternatives you've considered**
Copying and pasting.

**Comment by karmatosed** [comment]
I like this idea and think anything that improves importing is a good thing to think about implementing. Let me flag this as an enhancement for now and see about explorations there, I think having it explored in design makes sense for the flow, so let's get that label on this too.

**Comment by Soean** [comment]
The Markdown block is only available on wordpress.com and the Jetpack plugin. It's not a core block.

**Comment by phpbits** [comment]
Hmm, this is weird. I though Markdowns where supported on paste?

https://github.com/WordPress/gutenberg/blob/master/packages/blocks/src/api/raw-handling/readme.md

**Comment by alshakero** [comment]
Huh! This is awesome! I tried it but it didn't work because apparently when you copy from VS Code the code isn't copied as plain text hence it won't trigger the Markdown transform.
