### ISSUE TITLE
The editor has encountered an unexpected error - only with Safari

### ISSUE THREAD

**Issue by Odle98** [WordPress/gutenberg#21933]
I just updated my blog to WordPress 5.4.0

If I try to create/edit a blog post, WordPress returns a blank page with the following error:
"The editor has encountered an unexpected error. Attempt Recovery Copy Post Text".

This happens only with Safari, using Chrome the create/edit blog post page works perfectly.

The error in Safari is:
`
fn@https://www.mywebsite.com/wp-includes/js/dist/edit-post.min.js:7:184470
je@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:78:477
ph@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:215:175
lh@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:126:411
O@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:121:73
O@[native code]
ze@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:118:15
ze@[native code]
https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:53:50
unstable_runWithPriority@https://www.mywebsite.com/wp-includes/js/dist/vendor/react.min.js:26:341
mg@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:52:498
V@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:52:433
Sb@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:213:97
Mg@https://www.mywebsite.com/wp-includes/js/dist/vendor/react-dom.min.js:85:82
Mg@[native code]
e@https://www.mywebsite.com/wp-includes/js/dist/data.min.js:2:24643
https://www.mywebsite.com/wp-includes/js/dist/data.min.js:2:24727
forEach@[native code]
o@https://www.mywebsite.com/wp-includes/js/dist/data.min.js:2:18629
https://www.mywebsite.com/wp-includes/js/dist/data.min.js:2:15850
p@https://www.mywebsite.com/wp-includes/js/dist/data.min.js:2:7909
https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:9306
some@[native code]
e@https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:5180
https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:5130
https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:5727
some@[native code]
e@https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:5180
https://www.mywebsite.com/wp-includes/js/dist/redux-routine.min.js:2:5125
promiseReactionJob@[native code]
`

I am available for any additional info or tests
Thank you :)

**Comment by annezazu** [comment]
Hi @Odle98! Thanks for reporting this although I'm bummed to hear you're having issues with the latest release. This repository is in place to help develop Gutenberg and the future of WordPress. As a result, the best place to get help for your specific issue is in the support forums. I'd recommend sharing to this forum in particular: https://wordpress.org/support/forum/how-to-and-troubleshooting/

For context about this error in particular, check out this thread too as it might be helpful to understand what caused this: https://github.com/WordPress/gutenberg/issues/9556#issuecomment-610929328 

Hope this helps :)
