### ISSUE TITLE
getEditedPostAttribute('meta') with new meta type 'object' returns empty array as default

### ISSUE THREAD

**Issue by SamReciter** [WordPress/gutenberg#21938]
php:
```
register_post_meta('post_type','meta_key',array(
  'single'=>true,
  'type'=>'object',
  'show_in_rest'=>array(
    'schema'=>array(
      'type'=>'object',
      'properties'=>array(
        'key1'=>array('type'=>'number'),
        'key2'=>array('type'=>'string'))))));                        
```
js:
```
select('core/editor').getEditedPostAttribute('meta')['meta_key']
```
As default return value - if post meta with that 'meta_key' is not set before - you receive an empty array instead of an empty object.
That is very unconvenient.
Instead of an empty object - which would be okay - an object created out of the 'schema' with the property values beeing `undefined` or `null` would be even better.

**Comment by talldan** [comment]
@SamReciter It'd be helpful if you could use the templates provided when creating issues. There's not really a lot of information in this issue to go on.

**Comment by karmatosed** [comment]
For now, let's close this issue and we can reopen once there is more information.
