### ISSUE TITLE
WordPress embed block is not hiding the blockquote

### ISSUE THREAD

**Issue by david-binda** [WordPress/gutenberg#21945]
**Describe the bug**
WordPress oembeds provide a blockquote fallback for cases where the iframe cannot be rendered ( see https://build.trac.wordpress.org/browser/trunk/wp-includes/embed.php?rev=47325#L449 and https://build.trac.wordpress.org/browser/trunk/wp-includes/js/wp-embed.js?rev=43426#L50 ).

In classic editor, this feature works as expected, but in Gutenberg / Block editor the blockquote can still be seen.

**To reproduce**
1. Go to a new post screen in wp-admin
2. Enter an embeddable link of your own site 
3. Note the post title being above the iframe

**Expected behavior**
The blockquote should be hidden as it is in the classic editor.

**Screenshots**
<img width="1304" alt="classic-editor-with-hidden-blockquote" src="https://user-images.githubusercontent.com/3651036/80485569-f55f9c80-8959-11ea-9eed-9dde624047c7.png">
<img width="1306" alt="gutenberg-with-visible-blockquote" src="https://user-images.githubusercontent.com/3651036/80485576-f7296000-8959-11ea-96f7-a769e579d170.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5-alpha-47572
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Reprodubible in both, default and gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 4.8.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 81.0.4044.122

**Comment by davideprevosto** [comment]
Hello,

it seems to me this issue appears again on WordPress 5.9.

Am I doing something wrong or someone is catching the same problem?

Thank you

**Comment by xfechx** [comment]
Hello, 

I am getting all of the sudden automatic embeds in my site, when upgrading to Wordpress 5.9 and it is breaking things. Why is this not an option, why is it automatic? Such bad design choice!

Can someone help please?
