### ISSUE TITLE
Tag cloud block: Show more tags

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#21951]
Currently the tag cloud block shows the most used tags.

I wish the block could show more.

For example, in the tag cloud widget that can be placed on the side of the site, you have the option to choose the number of tags to display. That is a good option to have on the block.

**Comment by getsource** [comment]
I created #32201 to allow selecting the number of tags to be shown.
Right now, the range allowed is 3-100 tags.

Would this be enough for your purposes/use case?

**Comment by ricjcs** [comment]
If possible I would like it to show much more than 100, for example up to 1000, or have an option to display all tags.

I currently have over 500 tags on my website and I have an archive page where I show all categories and I also want to show all tags.

Thank you very much!
