### ISSUE TITLE
The plus icon has the same color as the background

### ISSUE THREAD

**Issue by truongwp** [WordPress/gutenberg#21956]
**Describe the bug**
The plus icon has the same color as the background when not hovering or focusing, cause the icon invisible.

**To reproduce**
1. Clone Gutenberg into a plugin and activate it.
2. Create a new post with Block Editor.

**Expected behavior**
The plus icon should have a different color from the background.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/19748318/80524839-79497100-89ba-11ea-9f82-fb5faf0bf1df.png)

**Editor version:**
- WordPress version: 5.4
- Gutenberg plugin installed, version: 8.0.0-rc.1

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Firefox 75.0, Chromium 81.0.4044.122

**Comment by youknowriad** [comment]
Hi There! thanks for the issue, this is a 2020 theme issue and it was already fixed on SVN. The fix will be included in the next theme update.
