### ISSUE TITLE
Add block: PDF

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2195]
Now when generating PDF thumbnails is in WP core.
Just to ask rest of you, what do you think about one new block like this ?

I know elements are few for 100% block width. But with some imagination it could be a nice and useful block.

- Left side of the block = PDF thumbnail.
- Right column (side) = ordered (or similar) list: Added by, PDF Title, Size, EXIF data (?), Date-time added, Attachment ID,  Filename, etc...

**Comment by StaggerLeee** [comment]
More or less whole style and feel from Media Library could be used. One PDF per line, possibility to add multiple PDF files per block. Preferably with much bigger PDF thumbnails.

![](https://s1.postimg.org/i0qdufkf3/2017-08-03_180822.jpg)

**Comment by StaggerLeee** [comment]
Something in this direction. Or maybe with alternate colors when block has multiple PDF.

![](https://s2.postimg.org/76usufomx/2017-08-03_185157.jpg)
![](https://s3.postimg.org/60h81sfkz/2017-08-03_184926.jpg)

**Comment by karmatosed** [comment]
I am going to comment for now on the idea, as we can then get into the design if everyone thinks it is worth investigating more.

In principle I think having the ability to view a PDF in a post is a good one. However, I am not totally sure this is something that fits a block. Interested in others' thoughts on this.

**Comment by StaggerLeee** [comment]
Sure. Design is not of importance right now. You allways did best regarding to it.

Can you please change Title to something more appropriate ? Dont know to what, chose something by your own imagination.
"Preview" is not right meaning. As this block would upload, edit PDF, and much more.

**Comment by karmatosed** [comment]
I think this feels very out of any v1 or any version. I've thought about this. I more see that documents just 'work' like images and can be attached and uploaded. But this would require work in the media library. I am not totally sold what this interface fixes that either a specialist plugin or having just a really good media library component in the future, wouldn't.

**Comment by StaggerLeee** [comment]
I meant with time, if there is interest, extend it to be something like this:
https://wordpress.org/plugins/download-attachments/

WP still has no uniform way for Users to show all mime document types, without risk they screw layout and lists. I mean to force them in a quarantine (block), and no way around.

**Comment by karmatosed** [comment]
I'm closing this as I still agree this isn't something the first version of Gutenberg will have. To me, it's more a plugin and/or iteration in later versions - maybe media library iteration. This would put it for me firmly in 'after merged' to core territory. I would love to see a plugin spun up exploring this in the meantime, we have that option and can't support everything in Gutenberg.

**Comment by grappler** [comment]
I found this issue as I was trying to insert a PDF in a post but could not find a way. Am I missing something?

@karmatosed Should I open a new issue or can we reopen this one?

**Comment by grappler** [comment]
This would be the core ticket to be able to add the PDF thumbnail to the content https://core.trac.wordpress.org/ticket/39618
