### ISSUE TITLE
Block Directory: Layout Improvement

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#21963]
**Is your feature request related to a problem? Please describe.**
When the Block Directory designs were conceived, they assumed a larger inserter width than we currently have today. As a result, the split installation/update icon layout that made sense in a wider inserter doesn't seem to work anymore. 

Note: Recently the inserter went from `400px` to `350px` wide, causing the layout issues.

With that in mind, I would like gather some ideas on how we can improve their layout.

## How we hoped they would look:
![Design](https://d.pr/i/mfa1Rr.png)

##  How they look today:
![Actual](https://d.pr/i/hV2vSd.png)

**Comment by StevenDufresne** [comment]
## One option would be to make the text smaller.

We would have to go pretty small to make it consistent. Probably `font-size: 10px`.

&nbsp;
### Screenshot
![Smaller Text](https://d.pr/i/qbvrlD.png)

**Comment by enriquesanchez** [comment]
Hi @StevenDufresne 👋

Considering that these labels could get much longer when translated to other languages, I think it's safe to say that we should look at alternatives. I don't think that having both in the same row will scale well.

I honestly wouldn't mind having them in two lines: active installations followed by last date of update.

What do you think?

**Comment by mapk** [comment]
Here's a quick revision accommodating the 350px width.

1. It expands the block container to the edges providing more room inside.
2. It butts up the blocks one after the other.
3. It stacks the stats on top of each other.

![block directory](https://user-images.githubusercontent.com/617986/80625386-fea44400-8a01-11ea-8231-2cfbf5206bcf.png)
