### ISSUE TITLE
Gutenberg 8.0 bug - Category Toggles in the block inserter are gone.

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#21979]
**Describe the bug**
As the title suggests, the Category Toggles in the block inserter are gone, resulting in a messier experience. The Categories are now simply Titles.

I hope this is not another "feature"...

**To reproduce**
1. Install Gutenbrg 8.0
2. Edit any page/post/cpt
3. Press Ctrl + F5 to refresh the cache
4. Press on the inserter to insert a block in the editor. The Categories are now just Titles and not Toggles.

**Expected behavior**
To see Category Toggles in the Block Inserter.

**Editor version (please complete the following information):**
- WordPress version:  5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  - Gutenberg 8.0 and no other plugins

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser Chrome - latest version

Thanks,
Nick.

**Comment by karmatosed** [comment]
Hi, @nick6352683 this is actually part of the iterations to the block library. You can read more about these changes in #21080. Hopefully, that brings more context as to why this happened.

**Comment by nick6352683** [comment]
Hi @karmatosed , thanks for pointing me in the right direction. After looking at issue #21080 I am very excited to see what the overall plans for the block inserter.
