### ISSUE TITLE
Block library iterations lead to unexpected behaviours

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21988]
I was testing the iterations and found the following:

![2020-04-29 22 22 11](https://user-images.githubusercontent.com/253067/80700451-ac345780-8ad5-11ea-9164-3b71fb270792.gif)

A few improvements I think could be made:

- Only allow one block library open at a time: having both seems a little much.
- I'm not convinced the resizing on scrolling is needed, perhaps leave it as a set size?

**Comment by youknowriad** [comment]
There are still some things unexplored from #21080 (especially related to the in between inserter) that I believe will address these issues.

Do you think we can continue discussing there?

**Comment by karmatosed** [comment]
@youknowriad ah yes, sorry my github-fu searching ability was low today. I'll pop up that image there. Thanks.
