### ISSUE TITLE
Set sizeSlug in core/image (Template) don't work.

### ISSUE THREAD

**Issue by jkwasniak** [WordPress/gutenberg#21989]
**Describe the bug**
I've developed a custom block with Template. 

```
const PROJECT_TEMPLATE = [
	[ 'core/image', { sizeSlug: 'full', align: 'wide' } ],
];

<InnerBlocks
	template={ PROJECT_TEMPLATE }
/>

<figure class="wp-block-image alignwide size-large"><img src="http://127.0.0.1:8080/wp-content/uploads/slider-1-1024x431.jpg" alt="" class="wp-image-1647" srcset="http://127.0.0.1:8080/wp-content/uploads/slider-1-1024x431.jpg 1024w, http://127.0.0.1:8080/wp-content/uploads/slider-1-300x126.jpg 300w, http://127.0.0.1:8080/wp-content/uploads/slider-1-768x323.jpg 768w, http://127.0.0.1:8080/wp-content/uploads/slider-1-1536x647.jpg 1536w, http://127.0.0.1:8080/wp-content/uploads/slider-1.jpg 1900w" sizes="(max-width: 1024px) 100vw, 1024px"></figure>
```

If you add an image then the image is added to the block at large size (it's default when I see that right) and the settings panel's Image Size select field shows the image size as large. I think that is wrong. Setting the align works correctly.

**To reproduce**
1. Add an image block
2. Select an image
3. In the block settings view the Image Size select field
4. The selected option is large

**Expected behavior**
As the image was added at full size (see Template) don't show the select field value as large. The class should also be set accordingly <figure class="wp-block-image alignwide size-full">

**Editor version:**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop:**
 - OS: mac
 - Browser chrome
 - Version 81

**Comment by talldan** [comment]
@jkwasniak There's some reports that the dropdown doesn't work correctly for gallery and image blocks in normal circumstances:
- https://github.com/WordPress/gutenberg/issues/21681
- https://github.com/WordPress/gutenberg/issues/21650

Does that sound like the same issue?

**Comment by jkwasniak** [comment]
In my view, this is another problem. It's about the init configuration of the dropdown from the template (dropdown work correctly, except for configuration from the template).

**Comment by crbadboy** [comment]
Made a comment here about what I think is going on: https://github.com/WordPress/gutenberg/issues/21650#issuecomment-647075759 (pls ignore that I posted under a different account...it's late :) )

**Comment by crbadboy** [comment]
Also posted what I think fixed the issue for me here: https://github.com/WordPress/gutenberg/issues/21650#issuecomment-647078031

**Comment by dsuryadi** [comment]
I agree with @jkwasniak. Since setting other attributes in templates (like stated [here](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-templates.md)) do work like this, I was expecting the same result when setting the sizeSlug. Unfortunately this is not the case (yet).

**Comment by ndiego** [comment]
In diving into this issue, I have discovered that the template is working correctly with the `sizeSlug`. If you switch over to the Code editor **before** inserting an image, you will see that the `sizeSlug` is set correctly. However, after you insert an image, the `sizeSlug` is updated. This has to do with the way image insertion works. 

There is already an issue opened up for this: https://github.com/WordPress/gutenberg/issues/39457. Once a fix for that is implemented, the issue you are experiencing here should be resolved. I am going to close this issue in favor of the other.
