### ISSUE TITLE
HTML block not recognized as HTML

### ISSUE THREAD

**Issue by asherber** [WordPress/gutenberg#21982]
**Describe the bug**
I have inserted HTML blocks with start and end `div` tags. When I reopen the page for editing, the blocks say "This block contains unexpected or invalid content", and I'm given the choice to Resolve or Convert to HTML.

**To reproduce**
1. Add a new Page
2. Insert an HTML block, enter `<div>`
3. Add a paragraph block with some text
4. Add an HTML block with `</div>`
5. Save a draft of the page and exit the editor
6. Go back to the editor, see that the blocks have been replaced as described

**Expected behavior**
HTML blocks should stay as HTML

**Screenshots**

![image](https://user-images.githubusercontent.com/5248041/80650426-fc61da00-8a41-11ea-8fee-db0bae83daae.png)

![image](https://user-images.githubusercontent.com/5248041/80650465-0a175f80-8a42-11ea-980a-aa0bfb16e10b.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044

**Additional context**

If I click "Convert to HTML", my original HTML appears. And whether I click that or leave it alone, the HTML does output correctly when I view the page.

**Comment by talldan** [comment]
@asherber A current limitation of the HTML Block seems to be that a single block in isolation needs to contain valid HTML. As your first block contains an unclosed opening`div` and the third block contains an unopened closing `div`, those are failing validation.

I think this makes sense in some ways as blocks are intended to standalone units that can be reordered in any desired way. Reordering blocks with HTML like that wouldn't make sense and could easily lead to a page having invalid HTML.

I understand the goal here is to put custom HTML around another block that still has rich text editing capabilities. Unfortunately I don't think that's currently possible without the creation of a custom block.

This was previously reported in https://github.com/WordPress/gutenberg/issues/15794, so will close in favor of that issue.

> If I click "Convert to HTML", my original HTML appears. And whether I click that or leave it alone, the HTML does output correctly when I view the page.

This sounds similar to what was reported in https://github.com/WordPress/gutenberg/issues/10889

**Comment by asherber** [comment]
Thanks, sorry for the duplicate.
