### ISSUE TITLE
Clicking on a component within a custom block does not select the block

### ISSUE THREAD

**Issue by microsoftoven** [WordPress/gutenberg#21983]
**Describe the bug**
When clicking on a component within a custom block while in the block editor, the block does not become 'selected' therefore shows no block settings panel, no selected borders, or no toolbar. This began when upgrading WP to 5.4 from 5.3.2. I'm not sure about 5.3.3 as I missed that update.

**To reproduce**

1. Create a custom block with JS via registerBlockType
2. Add a component with a textarea from wp.blockEditor (so far PlainText, URLInputButton, and URLInput pop up this bug for me)
3. Add the new block to a post/page
4. Click the textarea directly and see there is no block selection.

Extra things I did to ensure it wasn't my theme or plugins:

1. Deactivated all plugins
2. Activated the Twenty Twenty theme
3. Set up React and the custom block with two fields to test in the Twenty Twenty theme
4. Still didn't work
5. Downgraded WP to 5.3.2
6. After downgrading, everything was fine and dandy.

**Expected behavior**
The block should be selected when a child component is selected. This didn't occur prior to WP 5.4. 

**Screenshots**
Current behavior (focused text field with no parent block selection):
<img width="492" alt="Screen Shot 2020-04-29 at 6 37 42 PM" src="https://user-images.githubusercontent.com/38079128/80657209-9af13980-8a48-11ea-853f-dcf0011aac4c.png">

Behavior before 5.4 and 5.4.1 (focused text field with block selected as normal):
<img width="548" alt="Screen Shot 2020-04-29 at 6 37 35 PM" src="https://user-images.githubusercontent.com/38079128/80657243-b2302700-8a48-11ea-83d4-348b618dad61.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Block editor.
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: macOS Catalina, 10.15.3
 - Browser: Chrome
 - Version:  81.0.4044.129
 * Also occurs in Safari 13.0.5 and Firefox 74

**Comment by talldan** [comment]
Hey @microsoftoven. It'd be useful if you could include a code snippet, as any person trying to test/debug this issue will need to create their own block.

One thing worth noting is that some block borders were removed, so that would explain part of what you're seeing.

Just to double check as well - you definitely have the Top Toolbar option disabled?

**Comment by karmatosed** [comment]
I'm going to close this up for now as unable to replicate. If we can get some more information then this can be reopened.

**Comment by microsoftoven** [comment]
Sorry for the delay karmatosed and talldan, busy work week! Thank you for replying :) I narrowed it down to a class conflict. And yes, the top toolbar is enabled.

I found that if you add wp-block to a custom block's classes, it exhibits the behavior I posted about above. Looks like an error on my part as I shouldn't be using the class wp-block.

Test block code (JS file):
`const { __ } = wp.i18n; // Import __() from wp.i18n
const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks

const { 
    PlainText, 
    URLInputButton 
} = wp.blockEditor;

registerBlockType( 'test/text-field', {
	title: __( 'Test Field' ),
    icon: 'admin-links',
	category: 'test', 
	keywords: [
        __( 'text' )
    ],
    attributes: {
        text: {
            type: 'string',
            default: ''
        }
    },

	edit: function({setAttributes, attributes, className}) {
        return (
            <div className={`test-block wp-block ${className}`}>
                <URLInputButton
                    onChange={(url, post) => setAttributes({url: url, text: (post && post.title) || attributes.text })}
                    url={attributes.url}
                    ref={this.buttonRef}
                />

                <PlainText
                    value={attributes.text}
                    onChange={content => setAttributes({text: content})}
                    placeholder={__('Sample Text')}
                    keepPlaceholderOnFocus={true}
                />
            </div>
        )
    },

	save: function({attributes, className}) {
        return null;
	},
} );
`
