### ISSUE TITLE
New G2 icons

### ISSUE THREAD

**Issue by Garance91540** [WordPress/gutenberg#21995]
I've been working with @jameskoster and @jasmussen to create new G2 icons. (I'm currently working on the Woo app and noticed there were no current G2 icons equivalent for some existing icons). 

<img width="418" alt="Screen Shot 2020-04-30 at 2 54 00 PM" src="https://user-images.githubusercontent.com/28450084/80712647-8b2e2f80-8af2-11ea-9050-087d81b51ef0.png">

[svg files here](https://drive.google.com/open?id=10lDSV4mXr3Y-BigLOJV5GpIFaDr-0g8H)
[G2-icons.zip](https://github.com/WordPress/gutenberg/files/4559461/G2-icons.zip)

First time contributing to this project so don't hesitate if you need other formats. 

cc @pablohoneyhoney

**Comment by Soean** [comment]
@Garance91540 Looks good 👍, but I can't access the google drive link.

**Comment by Garance91540** [comment]
> @Garance91540 Looks good 👍, but I can't access the google drive link.

Sorry about this, I updated the sharing settings of this link and hopefully you can see them now. I can also share them in a different way, just let me know!

**Comment by Garance91540** [comment]
> @Garance91540 Looks good 👍, but I can't access the google drive link.

@Soean I added a zip file with the icons in the description

**Comment by Garance91540** [comment]
@pablohoneyhoney here are the icons with more context:

in grid system:
<img width="932" alt="Screen Shot 2020-04-30 at 5 59 03 PM" src="https://user-images.githubusercontent.com/28450084/80733768-6cd62d00-8b0e-11ea-8597-5bf12385c191.png">

in context of the Product screen of the Woo app. (The shapes icon will be used for product variations such as color or material):

<img width="491" alt="Screen Shot 2020-04-30 at 6 16 46 PM" src="https://user-images.githubusercontent.com/28450084/80734010-cd656a00-8b0e-11ea-82bd-d277be614518.png">

I'll work on a new iteration for the shapes icon!

**Comment by Garance91540** [comment]
Hi @pablohoneyhoney , 

Here are some new options for the "shapes" icon. Curious to hear your thoughts!

<img width="929" alt="Screen Shot 2020-05-04 at 1 40 49 PM" src="https://user-images.githubusercontent.com/28450084/80962241-f63a7780-8e0c-11ea-993e-03a2ce94928f.png">

**Comment by jameskoster** [comment]
I wonder if something more universal could work for the variations use case... something like 'layers' or 'swatches'? 🤔

<img src="https://cldup.com/I39-rxr8Ww-3000x3000.png" width="150" />

**Comment by Garance91540** [comment]
> I wonder if something more universal could work for the variations use case... something like 'copy' or 'swatches'?
@jameskoster I can't unsee "copy" when I see those :)

What about something like this?
<img width="546" alt="Screen Shot 2020-05-11 at 6 48 39 PM" src="https://user-images.githubusercontent.com/28450084/81588044-32934800-93b8-11ea-9e1e-5c2622b56522.png">

**Comment by jameskoster** [comment]
The vertical space between the triangle and the shapes below doesn't seem consistent with the horizontal space between the squircle and the circle. Otherwise that looks pretty good to me!

**Comment by Garance91540** [comment]
> The vertical space between the triangle and the shapes below doesn't seem consistent with the horizontal space between the squircle and the circle. 

<img width="604" alt="Screen Shot 2020-05-11 at 7 19 13 PM" src="https://user-images.githubusercontent.com/28450084/81591236-696b5d00-93bc-11ea-8ca9-df45a2c6b382.png">
updated

In that case it seems like we have this whole set of new icons finalized! 🎉🎉🎉


[New icons.zip](https://github.com/WordPress/gutenberg/files/4611125/New.icons.zip)

**Comment by Garance91540** [comment]
@pablohoneyhoney , did you still have feedback on these icons or are we good to go?

**Comment by pablohoneyhoney** [comment]
There’s something obscure about the different shapes together. My eye tries the decipher a few things at the same time and I don’t necessarily associate the 3 shapes with variations (color, materials). If it’s simply to convey _variants_, have you tried to only use four circles that transmit _choices_?  @Garance91540

**Comment by jameskoster** [comment]
I think that could work, as long as the circles are different some how.

But if all the objects have to be alike then we'd need to work out a way to illustrate the relationship between them. That being the concept of a common source with different variants. Maybe something like a "node" icon:

<img src="https://cldup.com/Kl8TUKGEnf-3000x3000.png" width="60" />
<img src="https://cldup.com/8FzDg6AWGb-3000x3000.png" width="60" />

**Comment by Garance91540** [comment]
If we'd like to create a shape composed of similar elements, then I think we could use the existing "product-categories" icon I'm seeing in the G2 design Figma file instead of creating this new "shapes" icon:

<img width="209" alt="Screen Shot 2020-05-26 at 3 13 49 PM" src="https://user-images.githubusercontent.com/28450084/82905066-a5c5be00-9f63-11ea-9e19-fe3ddfa874bb.png">

**Comment by pablohoneyhoney** [comment]
I think that works

**Comment by investmentgroupVenture** [comment]
Hi

**Comment by carolinan** [comment]
Removing the good first issue label because it is not clear what needs to be done here.

**Comment by annezazu** [comment]
Closing this out as, four years on, it's not clear what, if anything, is actionable still.
