### ISSUE TITLE
Inserter list not visible

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#21997]
**Describe the bug**
Although the block inserter is shown (the two tabs (Blocks, Patterns)), 
the selection list itself is not visible, but you can still find it in the DOM.

**To reproduce**
1. Ensure the latest WordPress + Gutenberg plugin installed + Gutenberg plugin enabled.
2. Open page in Gutenberg editor.
3. Click the plus icon to open the inserter and show the full list (in contrast to Shift + 7 shortcut).
Notice that the selection list is not visible, hence no block to be inserted can be selected.

**Expected behavior**
The selection list is displayed and a block can be selected from it.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Gutenberg plugin
- Gutenberg plugin version: 8.0.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044.129

**Additional context**
Maybe this issue is caused by the new Block/Patterns tab in inserter?

**Comment by youknowriad** [comment]
Hi there! thanks for the issue.

Can you clarify with a screenshot? Is the  inserter empty or something?

**Comment by strarsis** [comment]
Screenshot:
![inserter bug](https://user-images.githubusercontent.com/9271436/80731877-c38e3780-8b0b-11ea-943a-cfaeafe0f0df.png)

Yes, the inserter is empty, but the tabs are visible.
When the inserter is inspected, the DOM for the block list is still there, but not visible.

**Comment by youknowriad** [comment]
I'm not able to reproduce this by default.

 - Do you have any plugins, code that extend Gutenberg? Can you try disabling plugins to check the impact? 
 - Which theme are you using? Is it possible to try to use another theme to confirm it's  not the theme?

**Comment by strarsis** [comment]
Yes, the admin CSS from WooCommerce Bookings Availability Plugin caused the issue.
