### ISSUE TITLE
Add Gutenberg tab next to Text Editor tab.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2200]
I have a local site with various plugins among them Beaver Builder. In a new page Builder Beaver has a tab next to the Text Editor tab making it easier to switch between the two editing modes.
Should we also do something like this for Gutenberg/New Editor?

![gutenberg-new-page-content-tab](https://user-images.githubusercontent.com/5323259/28944045-55df5c02-78a1-11e7-9ffa-109f9fb19220.jpg)

I will connect this issue in with:
#2145

**Comment by nylen** [comment]
This tab doesn't exist in WP core.

An alternative would be to add a notice to the top of the editor.

Semi-related: #1797

**Comment by karmatosed** [comment]
A notice I would go over having a tab. In this case I would be against adding a new tab - I actually don't think that's a good way to do layout editing either. I don't really agree it's a good pattern when used by other plugins to be honest.

**Comment by paaljoachim** [comment]
The bottom line is should there be somekind of hint/notice telling people that they can use  the Gutenberg editor instead of the TinyMCE editor?

**Comment by paaljoachim** [comment]
I am thinking I should close this as I am off on the wrong track with this.
We should find a not intrusive method to softly let people know that they can use the Gutenberg editor instead of the TinyMCE editor.

**Comment by karmatosed** [comment]
No problem, lets do that :)
