### ISSUE TITLE
Open Office: versioning numbers

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2201]
There was a discussion during the 2nd August Open Office chat in regards to versioning.

As Gutenberg is getting close to 1.0 there were concerns that one should be careful in calling it 1.0 when it is not ready for production use.

A few alternatives came up:

1.0 beta
beta 1.0
0.1.0
beta 10
1.0.0-beta1
1.0.0-beta2
0.10

A few comments made:

Question: Who is the version number for?
Answer: it's primarily for us building it, setting milestones that we can work towards, with focus.

I think version number is more important for users than for us.

Version numbers are advertising and set expectations for people that aren't in the weeds. There is a reason people keep saying they use WordPress 4 and not WordPress 4.8.

Joen:
I do agree 1.0 will carry some extra meaning.
It’s important to note that 1.0 of the plugin does not equal ready for core.

Matias:
We'll keep this in mind as we get closer, and decide whether it's sufficient to put big red words at the top of the changelog stating :point_up:, or whether we should go to 0.9.1 and increment there.

**Comment by nylen** [comment]
Thanks for raising this issue.  I agree that "1.x" sets an expectation for users, agencies, clients, etc. that the product is "ready for production use" and we shouldn't jump to 1.x until we get a lot more testing.  It might be a good idea to create a "1.0.0" milestone as a next step.

**Comment by mtias** [comment]
We'll keep doing 0.x releases until we think a Beta 1.0 is called for.
