### ISSUE TITLE
"TypeError: Cannot read property 'parentNode' of null" in popover when using block-editor standalone

### ISSUE THREAD

**Issue by haszari** [WordPress/gutenberg#22013]
**Describe the bug**
I'm trying to use `@wordpress/block-editor` in a standalone react app (Create React App based). As soon as I click in the editor, there's a javascript error related to popover component (and then the error triggers in an infinite loop).

The error: `TypeError: Cannot read property 'parentNode' of null`, in [`popover/index.js`, when trying to find a "boundaryElement"](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/index.js#L332). 

My code looks like this, adapted from the [`block-editor` docs](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor):

```js
import React from 'react';

import {
  BlockEditorProvider,
  BlockList,
  WritingFlow,
  ObserveTyping
} from '@wordpress/block-editor';
import { Popover } from '@wordpress/components';
import { useState } from '@wordpress/element';

import '@wordpress/components/build-style/style.css';
import '@wordpress/block-editor/build-style/style.css';

import { registerCoreBlocks } from '@wordpress/block-library';
registerCoreBlocks();

function Editor () {
  const [ blocks, updateBlocks ] = useState( [] );

  return (
    <BlockEditorProvider
      value={ blocks }
      onInput={ updateBlocks }
      onChange={ updateBlocks }
    >
      <WritingFlow>
        <ObserveTyping>
          <BlockList />
        </ObserveTyping>
      </WritingFlow>
      <Popover.Slot />
    </BlockEditorProvider>
  );
}

export default Editor;
```

**To reproduce**
Not sure what the minimal steps to reproduce are - I'm guessing this occurs with a basic JS app (create react app or otherwise).

1. Set up a js project with `@wordpress` dependencies: `block-editor` `block-library` `components`. E.g. [create react app](https://create-react-app.dev), then npm install those dependencies.
2. Make an editor component as above, using block editor components and styles from Gutenberg 🎉 ❤️ 
3. Instantiate that component on a page/route so you can test it
4. Run & view the page, click ➕ block inserter or click/type in editor area.

**Expected behavior**
Can type and add paragraph and other blocks.

**Screenshots**

<img width="1474" alt="Screen Shot 2020-05-01 at 4 45 01 PM" src="https://user-images.githubusercontent.com/4167300/80782639-1c70d500-8bcb-11ea-9f51-48820b5992ea.png">

**Editor version (please complete the following information):**
- WordPress version: No WordPress
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Standalone, using `@wordpress` packages from npm
- Package versions (latest):
```
    "@wordpress/block-editor": "3.10.0",
    "@wordpress/block-library": "2.17.0",
    "@wordpress/components": "9.5.0",
```

**Additional context**
Note this is just an experiment - I'm [trying out using the block editor in a hobby project](https://github.com/haszari/bamdealist/pull/40). I'm super excited about the possibility of using Gutenberg standalone :)

**Comment by talldan** [comment]
Hey @haszari. I've encountered this issue before (when working on https://github.com/WordPress/gutenberg/pull/21340) and I think it's because a named slot for the toolbar is not being rendered.

Does it work ok if you try adding the following in the markup above `WritingFlow`?:
```jsx
<Popover.Slot name="block-toolbar" />
```

**Comment by talldan** [comment]
I'll label this as a needed documentation fix, as it looks like this is outdated since the block toolbar was moved to a popover:
https://github.com/WordPress/gutenberg/tree/master/packages/block-editor

**Comment by haszari** [comment]
> Does it work ok if you try adding `<Popover.Slot name="block-toolbar" />` in the markup above WritingFlow?:

That doesn't seem to fix it unfortunately. My component now looks like this:

```js
<BlockEditorProvider
  value={ blocks }
  onInput={ updateBlocks }
  onChange={ updateBlocks }
>
  <Popover.Slot name="block-toolbar" />
  <WritingFlow>
    <ObserveTyping>
      <BlockList />
    </ObserveTyping>
  </WritingFlow>
  <Popover.Slot />
</BlockEditorProvider>
```

And I get the same behaviour - JS error / loop if I click in ghost block or add a block from inserter.

I also tried a few different combinations – removing the other `Popover.Slot`, and moving the `block-toolbar` slot to different places in the markup (e.g. above below vs within `<WritingFlow />`).

**Comment by haszari** [comment]
Update – I've got this working, following the [`playground` example in the Storybook](https://github.com/WordPress/gutenberg/blob/master/storybook/stories/playground/index.js). 🎉 

I can add and edit blocks, just need to get the sidebar styles tidied up :)

<img width="1168" alt="Screen Shot 2020-05-02 at 2 51 50 PM" src="https://user-images.githubusercontent.com/4167300/80853372-784b6480-8c84-11ea-8258-90e20a24b610.png">

Leaving the issue open so we can update the readme/doc for standalone (maybe just link to playground?).

**Comment by talldan** [comment]
The error looks like it might have been fixed by https://github.com/WordPress/gutenberg/pull/22264.

**Comment by talldan** [comment]
I made a PR to update the docs - #22308.

@haszari I'm not sure we ever completely established what solve the issue. I notice the playground example has a `SlotFillProvider`, was it that?

**Comment by haszari** [comment]
> I'm not sure we ever completely established what solve the issue. I notice the playground example has a SlotFillProvider, was it that?

`SlotFillProvider` and a bunch of other components - maybe just need to update the docs to include all of it? 

```js
  return (
     <SlotFillProvider>
       <DropZoneProvider>
         <BlockEditorProvider
           value={ blocks }
           onInput={ updateBlocks }
           onChange={ updateBlocks }
         >
           <div className="editor-sidebar">
             <BlockInspector />
           </div>
           <div className="editor-styles-wrapper">
             <Popover.Slot name="block-toolbar" />
             <BlockEditorKeyboardShortcuts />
             <WritingFlow>
               <ObserveTyping>
                 <BlockList />
               </ObserveTyping>
             </WritingFlow>
           </div>
           <Popover.Slot />
         </BlockEditorProvider>
       </DropZoneProvider>
     </SlotFillProvider>
   );
```

**Comment by haszari** [comment]
Clearly I don't know what the minimal example looks like – maybe don't need all of this :)
