### ISSUE TITLE
Button align right in group

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#22025]
##**Describe the bug**
If a button group in a group is align-right it "moves out"
 
**To reproduce**
1. Create a groupe
2. give it a nice bg color
3. add a title and a button
4. Align the button right

**Screenshots**
![Capture d'écran 2020-05-01 13 46 12](https://user-images.githubusercontent.com/2622001/80803557-ef182d00-8bb2-11ea-977a-2b472776d18f.png)
 
**Editor version (please complete the following information):**
Gutenberg 8
wp 5.4.1 

#10299

**Comment by youknowriad** [comment]
Thanks for creating this issue. I think the question here is whether the group block should always clear floats by using `overflow: hidden` maybe? Alternatively, The decision could be left to the user like suggested in #10299 (a clear float advanced option for blocks)

**Comment by davouid** [comment]
I think when a user put an element in a group it is strange to see it move out for any reason.

**Comment by karmatosed** [comment]
I kind of like us moving towards a user decision on clearing as in #10299. It could also as @jasmussen noted in that issue be based on position, for example on centering.

**Comment by davouid** [comment]
I can't see a use case where it wouldn't need to be cleared.
As of right know it feel inconsistent.
And make creating a simple box with link kind of buggy.

<img width="693" alt="Capture d'écran 2020-05-01 20 49 47" src="https://user-images.githubusercontent.com/2622001/80832808-a16ce600-8bed-11ea-9331-c76a31f3faab.png">

Easy fix is to add a spacer at the end of the group... but...

**Comment by jasmussen** [comment]
Thank you for the report! 

I definitely agree this is inconsistent, but it does appear to be the correct behavior of floats, according to how CSS is supposed to behave. In that vein, and for all the reasons outlined in #10299, I'm going to close this one in favor of that, and hope that someone picks it up soon! 

And if this was closed in error, let us know and we can always reopen!
