### ISSUE TITLE
wp.data.select() is not working on the Experimental Navigation page

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#22022]
**Describe the bug**

I am attempting to retrieve the menu item ID (the underlying post ID) of the selected menu item. ~~On the Experimental Navigation page, I believe the menu item ID will be stored as the clientId on the block.~~

 I am using the following to get the clientId:

`wp.data.select( 'core/block-editor' ).getSelectedBlock().clientId;`

**On a standard post or page**

This works, the client ID is returned as expected:

<img width="843" alt="a" src="https://user-images.githubusercontent.com/63796393/80799508-ecabd800-8b9e-11ea-9e3c-1c2df178298d.png">

**On the Experimental Navigation page**

This doesn't work, the same code returns an error:

<img width="851" alt="b" src="https://user-images.githubusercontent.com/63796393/80799539-02210200-8b9f-11ea-84f7-e390a50afec2.png">

**To reproduce**

1. Go to Gutenberg > Navigation (beta)
2. Select a menu item
3. Paste the following into the console:

`wp.data.select( 'core/block-editor' ).getSelectedBlock().clientId;`

**Expected behavior**

The client ID of the selected block is returned.

**Editor version:**

- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? 8.0

**Comment by manmotive** [comment]
Screencast:

https://www.youtube.com/watch?v=nTOr6ncET7c

**Comment by manmotive** [comment]
Screencast:

https://www.youtube.com/watch?v=mB5kvC2hy0E

**Comment by noisysocks** [comment]
It looks like there's two separate issues here:

1. `wp.data.select( 'core/block-editor' ).getSelectedBlock()` should not return `undefined` on the Navigation screen. This is a bug.

2. As mentioned in https://github.com/WordPress/gutenberg/pull/21036#issuecomment-628353007, there's currently no way for third parties to get the ID of the underlying menu item given a Navigation Link's client ID.
   
   We probably should be using `@wordpress/data` in the Navigation screen. Props to @talldan for first suggesting this. We could then close this issue by adding e.g. a `getMenuItem` selector.

   ```js
   wp.data.select( 'core/edit-navigation' ).getMenuItem( clientId )
   ```

**Comment by talldan** [comment]
I wonder if this is because those selectors can only run within the scope of the `<BlockEditorProvider>`. Looks like the same thing happens on the experimental Widgets screen.

**Comment by youknowriad** [comment]
No, that's because by `BlockEditorProvider` is "scoped" which means it doesn't rely on the global 'core/block-editor' store. I'd argue that it's a good thing to start this way and see later if we really need to make it global. (it's just a prop)

**Comment by adamziel** [comment]
> As mentioned in #21036 (comment), there's currently no way for third parties to get the ID of the underlying menu item given a Navigation Link's client ID.

https://github.com/WordPress/gutenberg/pull/23033 solved this issue. It is now possible to use the following selectors:

```js
wp.data.select( 'core/edit-navigation' ).getNavigationPostForMenu( menuId );
wp.data.select( 'core/edit-navigation' ).getMenuItemForClientId( clientId );
```

**Comment by adamziel** [comment]
> wp.data.select( 'core/block-editor' ).getSelectedBlock() should not return undefined on the Navigation screen. This is a bug.

https://github.com/WordPress/gutenberg/pull/23675 will solve this problem - I encourage reviews and discussion.

**Comment by adamziel** [comment]
This issue is now solved in full. Feel free to reopen if anything comes up.
