### ISSUE TITLE
RangeControl Styles Incorrect

### ISSUE THREAD

**Issue by TwisterMc** [WordPress/gutenberg#22039]
**Describe the bug**
RangeControl doesn't appear the way the documentation shows.

**To reproduce**
1. Created a Gutenberg plugin with a RangeControl
2. View the RangeControl in the WordPress Admin
3. Compare it to the RangeControl documentation.

**Expected behavior**
They should appear the same.

**Screenshots**
<img width="1065" alt="Issue" src="https://user-images.githubusercontent.com/46997/80841446-07914300-8bc5-11ea-8798-2da63e621929.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Firefox 
 - Version 75.0 

**Additional context**
The issue seems to be this piece of CSS. The max-width specifically.
```
.components-panel__row label {
    margin-right: 10px;
    flex-shrink: 0;
    max-width: 75%;
}
```

<img width="1366" alt="CSS Issue" src="https://user-images.githubusercontent.com/46997/80841412-f9432700-8bc4-11ea-90b5-3920e205ef69.png">

I'm using Twenty Twenty with no plugins except my custom one.

**Comment by skorasaurus** [comment]
Hi,

Sorry for the delay in response. Somehow, this issue didn't show up in the list of unlabelled issues to be triaged. 
 
Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

I was actually using the RangeControl yesterday and didn't experience this.

**Comment by priethor** [comment]
Let's close this issue as we are unable to replicate and the activity has stalled. Feel free to reopen if the issue resurfaces.
