### ISSUE TITLE
Site editor: More menu is missing options

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#22035]
Can we make the more menu in the site editor match the post editor's more menu. It currently looks like this:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/1123119/80838832-22f55180-8bb7-11ea-9459-d0aec7b23676.png">

I would expect it to have these options:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1123119/80838790-0a853700-8bb7-11ea-9596-f7a1931957dd.png">

**Comment by mtias** [comment]
This falls within this issue: #21245.
