### ISSUE TITLE
Block Settings Menu : Is there a way to extend the Block settings by removing certain items?

### ISSUE THREAD

**Issue by josephjoice** [WordPress/gutenberg#22058]
[PluginBlockSettingsMenuItem](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-block-settings-menu-item) helps to add more items to the settings menu. But I am not finding  a way to remove certain items in the default settings like,  `Remove from Reusable blocks` for instance.

**Comment by elpuas** [comment]
I'm Busting my head trying to figure it out, to do exactly the same thing.

**Comment by josephjoice** [comment]
No I didnot. Thanks for pointing out, I closed the issue by mistake.

**Comment by youknowriad** [comment]
Hey there! at the moment there's no desire to offer an ad-hoc API to remove UI elements. We prefer semantic APIs instead. For instance if you don't want to allow the "convert to reusable" in your block, you can set `reusable: false` in your block `supports` config.
