### ISSUE TITLE
A Bug Occurred in Development Environment 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#22059]
After preparing the development environment, I am getting this message in the admin and also in the front-end: 
`Warning: filemtime(): stat failed for /var/www/html/wp-content/plugins/gutenberg/build/edit-navigation/style.css in /var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php on line 404 Warning: filemtime(): stat failed for /var/www/html/wp-content/plugins/gutenberg/build/edit-site/style.css in /var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php on line 413`

The issue is also preventing me from accessing Gutenberg Plugin Options in the admin. 

I would like to contribute to the repo, how I can I fix that to move forward? 

**To reproduce**
Follow the steps in:
https://developer.wordpress.org/block-editor/contributors/develop/getting-started/#step-1-installing-a-local-environment

**Screenshots**
![Screen Shot 2020-05-03 at 7 33 52 PM](https://user-images.githubusercontent.com/39377174/80922465-31896780-8d75-11ea-934b-f3180e94da92.png)
![Screen Shot 2020-05-03 at 7 33 59 PM](https://user-images.githubusercontent.com/39377174/80922468-34845800-8d75-11ea-9288-7829ae28fae9.png)

**Comment by talldan** [comment]
Hey @DOUARA, I think this is because the code for Gutenberg needs to be built. You can run `npm run build` to do that. If you're developing, `npm run dev` is usually the best option, that'll watch files in the codebase for changes and rebuild when changes occur.
