### ISSUE TITLE
Missing Options -> Tips checkbox since WP 5.4

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#22052]
**Describe the bug**
In WordPress 5.4 the option to uncheck Tips is not available anymore.

**To reproduce**
WordPress 5.4 / 5.4.1 = Navigate -> "More tools & options -> Options

**Expected behavior**
There should be the checkbox "Tips"

**Screenshots**

### **WordPress 5.3.2:**
![options_tips](https://user-images.githubusercontent.com/1585416/80912070-b3a86a80-8d3a-11ea-922e-ce1a9aea0a8a.jpg)

### **WordPress 5.4.1:**
![wp_5_4_missing_tips](https://user-images.githubusercontent.com/1585416/80912077-bdca6900-8d3a-11ea-9905-e78ab47d40fe.jpg)

**Comment by talldan** [comment]
@La-Geek The tips were removed, so that's why the option to disable them is no longer present. They were replaced with the welcome popover that can be seen when first opening the editor.

**Comment by La-Geek** [comment]
Yes and how you can disable the popover? It is enough, if I see it once, but not every time (after I have cleared caches and cookies)? Do you have a snippet for the functions.php?

**Comment by talldan** [comment]
@La-Geek How about I help you if you stop making duplicate issues?

**Comment by La-Geek** [comment]
Sorry, but is it not allowed to post a feature request? The first issue has been a bug report, this is a difference?

**Comment by La-Geek** [comment]
And every help to disable tips (Welcome Guide) and Inserter Help Panel (Popups) would be very appreciated, thank you.

**Comment by talldan** [comment]
Well, there have been three issues created now today for the same problem, which is a little frustrating for someone trying to manage issues in the repository.

The 'Inserter Help Panel' was a slightly confusingly named feature but refers to a quick way to insert commonly used blocks, so it's unrelated to your issue with the Welcome Guide. The feature has now been removed.

I had a look and unfortunately I don't think there is a way to disable the Welcome Guide permanently. 

Adding a setting in the editor preferences panel wouldn't help, as those preferences are stored in browser storage, so also reset when browser data is cleared.

It is acknowledged that this is an issue (https://github.com/WordPress/gutenberg/issues/15105 tracks the problem) and a fix has been worked on in https://github.com/WordPress/gutenberg/issues/15105.

**Comment by La-Geek** [comment]
> Well, there have been three issues created now today for the same problem, which is a little frustrating for someone trying to manage issues in the repository.

I do understand your point and I am sorry. I thought, bug report was not correct so I wrote a feature request.

However for me these are 2 issues: 1 is for the Welcome Guide (thank you for the links) and the other one is about the Pop ups, when you hover with the mouse pointer over the blocks (in inserter). This flackering is absolutely annoying. I could not find the pop ups in CSS (for a display: none), so I hope a snippet for functions.php could help?

**Comment by talldan** [comment]
I see. Actually, I'm wrong, the 'Inserter Help Panel' used to look like this part on the right:
![Screen Shot 2020-01-16 at 8 32 24 AM](https://user-images.githubusercontent.com/617986/72543685-f5201300-383a-11ea-9290-62c851c5a27f.png)

So it is similar to what your suggesting. It's been replaced with the preview.

**Comment by talldan** [comment]
I've reopened #22053 and changed the title to reflect that.
