### ISSUE TITLE
Bug: Gap between Gutenberg editor and Metabox area. (.block-editor-writing-flow__click-redirect))

### ISSUE THREAD

**Issue by camya** [WordPress/gutenberg#22055]
There is a large gap between the Gutenberg editor and the Metabox area. 

It looks like the class ".block-editor-writing-flow__click-redirect" sets the height to 0, but in order to close the gap, it has to set the min-height to auto instead.

### Fix

Replace height: 0; with min-height: auto;

```
.has-metaboxes .edit-post-visual-editor .block-editor-writing-flow__click-redirect {
    min-height: auto;
}
```
![gutenberg-gap_metabox](https://user-images.githubusercontent.com/827658/80913899-60d5af80-8d48-11ea-9693-a0f843252309.jpg)

**Comment by nderambure** [comment]
Still in Gutenberg ships with WP 5.5+.
Is there any feedback to this design choice ?
That's really weird, some people does not see the metabox when there is one.

**Comment by sparkbold** [comment]
Confirm, I also see the same issue. Not sure if this is cause by core or plugin. The fix from camya is still working though.

**Comment by talldan** [comment]
This doesn't seem to happen now, so closing the issue.
