### ISSUE TITLE
wp image caption format

### ISSUE THREAD

**Issue by brmuse** [WordPress/gutenberg#22066]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@brmuse Hmm, there doesn't seem to be an information in the issue description other than the template for issues.

I'll close this. Would you be able to open a new issue and make sure it has a description?
