### ISSUE TITLE
Navigation block: Dropdown menus/child menus are not following screen size which caused horizontal scrolling

### ISSUE THREAD

**Issue by retnonindya** [WordPress/gutenberg#22065]
**Describe the bug**
When the Navigation block has more than two child menus (parent > child > grandchild) and the site is viewed on mobile view, the menu items are displayed vertically which caused the screen to side-scrolling/horizontal scrolling.

**To reproduce**
1. Create a Navigation block on any pages (I used homepage on my test site).

2. Create a parent menu item with child menu items under it, try make it as parent > child menu > grandchild menu > grandchild's child menu (???)
![navigation block](https://cldup.com/bvgL0oS5Tr.png)
*Direct link: https://cldup.com/bvgL0oS5Tr.png*

3. Check the website on mobile view/resolution. You could see that the child menu items are displayed next to each other which caused horizontal scrolling.
![horizontal scrolling](https://cldup.com/ouKOfXCKnl.png)
*Direct link: https://cldup.com/ouKOfXCKnl.png*

**Expected behavior**
I expect the child menu items would be displayed under the child menu; maybe similar look as how TwentyTwenty theme displayed the child menus?

![twenty](https://cldup.com/FCQ8FDas8g.png)
*Direct link: https://cldup.com/FCQ8FDas8g.png*

The menu on TwentyTwenty theme in the screenshot is from the theme's main navigation, not from Navigation block, so it could be unfair to compare. However, it would be preferable to have Navigation block to display the child menus like that.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Block Editor

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome and Firefox
 - Version 81.0.4044.12 (Chrome) 75.0 (Firefox)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 13.3.1
 - Browser Chrome
 - Version 81.0.4044.124

**Comment by karmatosed** [comment]
There are a number of iterations for sub-navigation proposed in #22087. Scaling is absolutely something to consider with this. I would suggest in this case we focus on that issue over a particular theme styling. The idea here is to get a design that works as a default. Due to that, I am going to close this issue to try and focus discussion on that one, however, your input would be welcome there. How sub-navigation scales is definitely something to iterate on.
