### ISSUE TITLE
Link modal box z-index bug

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2206]
I noticed that when adding a link and having the link modal open that it showed up below the image further down.

![screen shot 2017-08-04 at 01 42 23](https://user-images.githubusercontent.com/5323259/28948487-48398676-78b6-11e7-8c11-fdd1cf941fd4.png)

**Comment by afercia** [comment]
Seems to me this happens only when an image is aligned. Doesn't happen on a default image block:

![screen shot 2017-08-04 at 13 11 24](https://user-images.githubusercontent.com/1682452/28966477-b86009b0-7916-11e7-9db5-785cb01f6c7a.png)

![screen shot 2017-08-04 at 13 14 31](https://user-images.githubusercontent.com/1682452/28966539-0a185f46-7917-11e7-9dc1-aefb6a50f3ee.png)

**Comment by mtias** [comment]
This is still the case:

![image](https://user-images.githubusercontent.com/548849/34572705-5698454c-f172-11e7-911c-8c8028e461fa.png)

**Comment by jaswrks** [comment]
Seems this has been fixed? Unable to reproduce in Chrome.

**Comment by paaljoachim** [comment]
I just checked again. Just playing around with aligning and text shows a few different things. (Testing in Chrome in High Sierra in Desktop Server using Gutenberg 2.0)

![screen shot 2018-01-15 at 14 33 11](https://user-images.githubusercontent.com/5323259/34944920-b34374fa-fa01-11e7-92f5-8776da8c92de.png)

![screen shot 2018-01-15 at 14 37 08](https://user-images.githubusercontent.com/5323259/34944966-dfe344f4-fa01-11e7-9fa2-c8f55bb14046.png)

![screen shot 2018-01-15 at 14 36 45](https://user-images.githubusercontent.com/5323259/34944985-ed318ecc-fa01-11e7-9b70-eec6d7d8c2f4.png)

**Comment by jaswrks** [comment]
I see. Thank you. I wasn't testing with aligned images.

**Comment by jaswrks** [comment]
Fixed in PR:  https://github.com/WordPress/gutenberg/pull/4503
