### ISSUE TITLE
No toolbar on empty paragraph block

### ISSUE THREAD

**Issue by tbradsha** [WordPress/gutenberg#22079]
The default empty block is a paragraph block:

![image](https://user-images.githubusercontent.com/32492176/80968039-89a38680-8dd4-11ea-8a6f-2c0577b21a7a.png)

![image](https://user-images.githubusercontent.com/32492176/80968183-c2dbf680-8dd4-11ea-8df8-20455483abad.png)

However, there's no toolbar available until there is text inside this block. Since empty Paragraph blocks aren't to be trimmed (#5185), there should be a clear way to remove this (e.g. the standard "remove block" option in the toolbar).

Also, this forces someone to write something prior to formatting it, editing it as HTML, etc.

**Comment by talldan** [comment]
@tbradsha You can press `backspace` to delete the empty block.

**Comment by karmatosed** [comment]
I can see both sides of styling before you write copy, but I do think as far as a default experience, just writing is natural. I would, as a result, recommend keeping as it is regarding that. As noted by @talldan, you can delete the empty block.
