### ISSUE TITLE
Show transforms as a vertical list rather than a grid

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#22073]
Let's try showing block transformations as a list (the same way they render in the `/` inserter) instead of the current grid pattern as it'd help with familiarity with other editors:

![image](https://user-images.githubusercontent.com/548849/80962047-8d52ff80-8e0c-11ea-99eb-f9a7ccb1ddd8.png)

And this instead:

![image](https://user-images.githubusercontent.com/548849/80962172-d014d780-8e0c-11ea-8f80-f5a885645c30.png)

**Comment by carolinan** [comment]
Wouldn't it be a lot of scrolling?
I am not savvy with shortcut commands. I am already struggling with this because if I for example add a block style (or a few) to the paragraph block, the block style is already expanded by default, and I have to scroll past it to reach the transform. If the transform I want is at the end, that is a lot of scrolling.

**Comment by mtias** [comment]
Styles are a bit of a problem right now, but ideally we can float them like this:

![image](https://user-images.githubusercontent.com/548849/80976901-4d981200-8e24-11ea-9b62-56a88e8946de.png)

Or make them also lists:

![image](https://user-images.githubusercontent.com/548849/80976935-5a1c6a80-8e24-11ea-9348-6c070f66c7c9.png)

We might also move them below transforms, as I think transforms are more important tools in most cases.

**Comment by karmatosed** [comment]
Here is a rapid mock on what this could look like:

<img width="845" alt="Frame 1" src="https://user-images.githubusercontent.com/253067/81083215-33296b80-8eec-11ea-92cc-b16a2b903cd2.png">

Personally, I prefer it for a few reasons:

- Easier to rapidly interact and scan.
- Creates a different mindset from picking a block.

**Comment by karmatosed** [comment]
Just exploring styles, I have to say I really like what was linked above. I brought that into the styling I did and for myself, I prefer the 2 levels:

<img width="845" alt="Frame 2" src="https://user-images.githubusercontent.com/253067/81086453-6e2d9e00-8ef0-11ea-8e89-363747b18abe.png">
