### ISSUE TITLE
FSE: Featured image block does not behave like an image block in the editor.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22081]
**Describe the bug**
With FSE enabled, you can add the featured image block to a post.

As seen in the screenshot below:
The size of the image is larger than expected. The actual size of the image that is added as
a featured image is 253x253px. In the editor it is showing at the max width for blocks which is 580px.
The image overlaps content that is above it
The image goes outside its "container"
Content below the image is displayed on top of the image.

**To reproduce**
1. Enable full site editing
2. Create a new post
3. Add a featured image
4. Add a featured image block in the editor
5. See the size of the image.

**Expected behavior**
I expect the image to be of the correct size, and I expect it to have the same
controls as other images, and to not overlap any other content.

**Screenshots**
![featured-image](https://user-images.githubusercontent.com/7422055/80972813-da3fd180-8e1e-11ea-9cf1-e303d4f13dee.png)

![featured-image2](https://user-images.githubusercontent.com/7422055/80975063-e6795e00-8e21-11ea-9c8b-f5ddf704adf7.png)

On the front it display as expected with its original size.

**Editor version (please complete the following information):**

WordPress version: 5.4.1
Gutenberg 8.0.0

**Desktop (please complete the following information):**

Windows 10
Chrome version: 81.0.4044.129
Firefox version 75.0

**Comment by ntsekouras** [comment]
Hey @carolinan - thanks for reporting this! This is fixed here: https://github.com/WordPress/gutenberg/pull/25412.
