### ISSUE TITLE
Full screen image pushes it below left WP sidebar and right Document settings ver 0.6

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2208]
I noticed that clicking full screen the image spreads out below the left WP sidebar and the right Document settings.

![screen shot 2017-08-04 at 01 49 07](https://user-images.githubusercontent.com/5323259/28948616-24ab1336-78b7-11e7-89e1-51573c7c6675.png)

**Comment by karmatosed** [comment]
I can't replicate on latest versions as the wide image is now up to the theme. In future if you could also mention what browser and resolution that would really help when trying to replicate.

**Comment by paaljoachim** [comment]
I will test again later after 0.7 is released and see if it is still there.

**Comment by paaljoachim** [comment]
Ahhh. Now I understand what you meant...
I noticed that in version 0.7 that the full screen / wide image icon has been removed. It seems your saying that it is up to the theme to do a wide image and not Gutenberg. Ok gotcha.
