### ISSUE TITLE
Old navigation block (without alignment) still offered in quick-inserter

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#22085]
**Describe the bug**
When the "quick" inserter is opened (`Ctrl` + `7`) hotkey, the old `core/navigation` block, 
without alignment (`horizontal`/`vertical`) is still offered to the user and can be selected and inserted.

**To reproduce**
1. Open the "quick" inserter (`Ctrl` + `7` hotkey or other means) and select the `navigation` block labeled `Navigation`. Notice that the block is inserted. If you hadn't inserted a `navigation` block recently, the "quick" inserter may not offer it. 
Also notice that old posts/pages, that had been edited before the introduction of the new `core/navigation` block types can still contain old `navigation` blocks.

**Expected behavior**
The old `core/navigation` block shouldn't be in the ("quick") inserter list anymore,
when the new `navigation` blocks (`horizontal`/`vertical`) are now offered in Gutenberg.
This could be a bug more related to the "quick" inserter feature and not specifically to the `navigation` blocks though.
It may also be a good idea to offer a transform to the old `core/navigation` blocks, 
or use the old `navigation` block as `horizontal` default, but this would require to remove the `Navigation (horizontal)` block and relabel the old `navigation` block to `Navigation (horizontal)`

**Editor version (please complete the following information):**
- WordPress version: `v5.4.1`
- Does the website has a Gutenberg plugin installed, or is it using the block editor that comes by default? `Gutenberg Plugin`
- If the Gutenberg plugin is installed, which version is it? `v8.0.0`

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro
 - Browser: Chrome
 - Version: 81.0.4044.129

**Additional context**

**Comment by talldan** [comment]
Hey @strarsis, the two navigation blocks are implemented using Block Variations. The inserter issue is known and tracked on https://github.com/WordPress/gutenberg/issues/20583, so I'll close this as a duplicate.
