### ISSUE TITLE
Clicking trash icon - no confirmation of deletion.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2209]
Clicking trash icon. No confirmation saying "do you want to delete this object?" It deletes the object right away. It would be good to have a dialog box asking about deletion as one might have made a mistake clicking the icon.

**Comment by jasmussen** [comment]
Good ticket, thanks for opening it.

I've labelled it "Question", because I'm not convinced we want this. We want to ensure that _undo_ works perfectly, every time, and that autosave and revisions work too. But I'm not sure we want any "are you sure" dialogs unless we're absolutely sure the action we are taking is destructive enough to merit it.

**Comment by iseulde** [comment]
@jasmussen I think the red trash icon for the whole post is meant? Then again undo works there too, and core doesn't warn either, so I agree there.

**Comment by jasmussen** [comment]
Argh you're right! Sorry for misunderstanding.

But also in that case I don't think we need a prompt, because the post should land in trash, where you can still recover it.

**Comment by paaljoachim** [comment]
I did not even think about the undo button. Making it very easy to undo the "ops I happened to press the trash icon". Lets leave the issue open for a bit and get some more feedback on it. But it seems that we can go ahead and close this issue soon.

**Comment by karmatosed** [comment]
I would also back not having a prompt. The post lands in trash, it's not removing it and never having it be able to be returned.

**Comment by karmatosed** [comment]
Closing as I think we have a consensus that this isn't needed currently.

**Comment by aduth** [comment]
>The post lands in trash, it's not removing it and never having it be able to be returned.

Gets interesting in the case of the [`EMPTY_TRASH_DAYS` constant](https://codex.wordpress.org/Trash_status#EMPTY_TRASH_DAYS_option):

```php
define( 'EMPTY_TRASH_DAYS', 0 );
```

...is equivalent to permanently deleting post immediately. In the current editor, the interface is updated to reflect this:

![Delete permanently](https://user-images.githubusercontent.com/1779930/28975913-db6ecf66-7909-11e7-89be-0f99650de421.png)

But even here, there is still no prompt to confirm the action.

**Comment by iseulde** [comment]
> Gets interesting in the case of the EMPTY_TRASH_DAYS constant

In that case, I would definitely add it.
