### ISSUE TITLE
Remove Block Inserter Tips

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#22091]
**Describe the bug**
Why are there Tips displaying at the bottom of the Block Inserter, and why can't I turn them off?

Editor Tips were supposedly removed in favour of the new Welcome Guide, but now you've added Tips back into the bottom of the Block Inserter, and what's worse, you haven't provided a way to turn them off.

<img width="1920" alt="screenshot_380" src="https://user-images.githubusercontent.com/2078245/81030195-4415b500-8ecb-11ea-9d9c-231b8c908416.png">

**To reproduce**
1. Edit a Page
2. Turn on the Block Inserter using the icon at the top-left of the page
3. View tips at bottom of Block Inserter

**Expected behavior**
Remove the Tips or provide an option to turn them off completely

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? 8.0.0

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Firefox 75.0

**Comment by karmatosed** [comment]
I think the Tips have some use, so if we are talking about iterating here then an option. would make sense. Perhaps providing hooks if nothing else to remove would be good, although they might already be there.

**Comment by mtias** [comment]
> Editor Tips were supposedly removed in favour of the new Welcome Guide

That's not the case :) The inserter tips are a separate API that was introduced mid last year in https://github.com/WordPress/gutenberg/pull/16813

And it aims to allow blocks to register their own tips:
- https://github.com/WordPress/gutenberg/issues/16979
- https://github.com/WordPress/gutenberg/issues/16595
- https://github.com/WordPress/gutenberg/issues/16594

The placement at the bottom of the inserter is not final as that area is undergoing work. It might still make sense to allow disabling these as an option.

**Comment by maddisondesigns** [comment]
It literally says in your 5.4 release post that
>Tips are gone. In their place, a Welcome Guide window you can bring up when you need it—and only when you need it—again and again.

<img width="737" alt="screenshot_383" src="https://user-images.githubusercontent.com/2078245/81132843-1c8a1f80-8f93-11ea-8a93-a09cbd5dda47.png">

Tips are annoying and take up valuable screen real estate. If you're going to keep them, then they need an option to allow users to turn them off. An option in the UI as well, to allow all users to be able to turn them off. Not just a hook that only developers know how to use.

**Comment by paaljoachim** [comment]
I do believe that an option could be added to preferences to turn off the tips. 

![Screen Shot 2021-02-23 at 17 18 03](https://user-images.githubusercontent.com/5323259/108873058-1d13a580-75fb-11eb-990c-a68bde720af0.png)

Perhaps placing a hide tips toggle directly in the General screen might be a good way to go.

**Comment by talldan** [comment]
There doesn't seem to be a lot of other feedback that the tips are annoying, so I'm going to close this as something that won't be implemented.
