### ISSUE TITLE
FSE blocks are missing additional CSS classes on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22097]
**Describe the bug**
The FSE specific blocks does not output the CSS classes added in the Additional CSS option on the front.
(The CSS class saves fine in the editor.)

I have tested: 
site title
post title
post content
post comments
post comments count
post comments form
post date
post excerpt
post featured image
post tags

I have not tested post author due to a PHP error.

**To reproduce**
1. Enable full site editing
2. Add any of the blocks listed above
3. Add a CSS class in the option in the block sidebar.
4. Save and view the source code of the front

**Expected behavior**
I expect the CSS class name to be available on the front.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Gutenberg: Master, _latest commit was: b73bb6d_

**Desktop (please complete the following information):**
Windows 10
Chrome version: 81.0.4044.129

**Comment by mtias** [comment]
This also reminds me we need to look at support for `post_class` and `body_class` in the appropriate wrappers.

**Comment by carolinan** [comment]
Closing this because it is a duplicate of https://github.com/WordPress/gutenberg/issues/21903
