### ISSUE TITLE
Embed block doesn't work, returns error "Sorry, you are not allowed to make proxied oEmbed requests."

### ISSUE THREAD

**Issue by ClementBallet** [WordPress/gutenberg#22104]
Hi, I having some troubles when I want to use the embed video block in Gutenberg : it shows error message "Sorry, this content could not be embedded". 
In the console, there is a 404 error on API url : 
![Capture d’écran 2020-05-05 à 14 52 41](https://user-images.githubusercontent.com/24383849/81068305-6fef6580-8ee0-11ea-8b17-00c03c76720f.png)
When I go to this url :
![Capture d’écran 2020-05-05 à 14 38 05](https://user-images.githubusercontent.com/24383849/81068584-e4c29f80-8ee0-11ea-8b55-c8c3384b6c4c.png)
I tried to update Gutenberg (8.0.0) and Wordpress (5.4.1).

I would really appreciate if you have any solutions.

**Comment by Otto42** [comment]
What browser are you using? Do you have any privacy software installed? Anything having to do with cookie blocking? 

Does it work if you use a different browser?

**Comment by annezazu** [comment]
To add two more additional thoughts:

- Can you share the video link you are trying to embed?
- Have you tried embedding with all other plugins deactivated to rule out a conflict?

Thanks for the additional information! For context, the error messaging for embeds failing isn't very robust so having more information helps get closer to the underlying problem.

**Comment by ClementBallet** [comment]
I am using mostly Chrome but I also tried on Mozilla. And with private navigation on both browsers.
I have adblock on Chrome but not on Mozilla.
I can share the video link but I've tried many other video and none of them works... All were hosted on YouTube.
Also tried with the embed link provided by YouTube and deactivate all plugins installed.

None of them works... 
Thanks for your help anyway.

Anyone had this bug before?

**Comment by ClementBallet** [comment]
Forgot to mention that but I also tried video link hosted on Vimeo. 
Same bug too.

**Comment by annezazu** [comment]
Previously, I explored an issue reported with vimeo links here but wasn't able to replicate: https://github.com/WordPress/gutenberg/issues/21752 

I tried once more and couldn't replicate using WP 5.4.1 & Gutenberg 8.0.0 with all other plugins deactivated:

![embed](https://user-images.githubusercontent.com/26996883/81351326-e6bf6680-9078-11ea-9597-9ca227f5be5e.gif)

As a next step, can you send me an example of a youtube link where you ran into these problems @ClementBallet ?

**Comment by karmatosed** [comment]
I also am unable to replicate, for now, let's close this but as soon as we have more information we can always reopen.

**Comment by marcingminski** [comment]
Hi, I came here from Google as I have the same issue when trying to Embed a link from another WordPress blog (that I also own):

`{"code":"rest_forbidden","message":"Sorry, you are not allowed to make proxied oEmbed requests.","data":{"status":401}}`

Embedding YouTube works fine though. 
I am looking for a guide on what to look for because I don't even know where to start

Thanks!

**Comment by calliaweb** [comment]
Just to add I have the same issue on a website. I've created a staging site, deactivated all plugins and enabled the twenty twenty-one theme and can't embed any youtube videos. I've cleared the oembed_cache and issue remains. I've then created a fresh install on the staging site and can't embed videos. I can use the youtube iframe code and that does work, so its not that YouTube are blocking my server IP address. Using a classic editor block or the classic editor does not work either.

**Comment by renatho** [comment]
It seems the mentioned issues are related to capability. That error is behind [this conditional](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/class-wp-oembed-controller.php#L149-L151):
```php
		if ( ! current_user_can( 'edit_posts' ) ) {
			return new WP_Error( 'rest_forbidden', __( 'Sorry, you are not allowed to make proxied oEmbed requests.' ), array( 'status' => rest_authorization_required_code() ) );
		}
```

**Comment by avibrazil** [comment]
I have same issue when on WP 6.1.1 when trying to embed a major newspaper link such as [this one](https://www1.folha.uol.com.br/poder/2022/12/bolsonaro-divulga-mensagem-dubia-em-evento-militar-e-silencia-sobre-vandalismo.shtml) into a blog post. Links to Twitter posts also do not work and will not get embedded into the WP post.

I was expecting the block to look like embeds on Facebook, but it fails. If I try to access the URL that appears on my webserver logs and cause the 403 error, I can see this JSON error message.

**Comment by avibrazil** [comment]
Apparently this was fixed on early Dec 2022 and will appear on WordPress post 6.1.1

https://github.com/WordPress/wordpress.org/commit/1c64698f3665092b3a6e4c33d96bcf6e22bd4365

**Comment by avibrazil** [comment]
WordPress 6.2 still struggles with this.
Problem persists on 6.2.
Can't embed anything.
My installation is WordPress checked out from github, then checked out on tag 6.2. So I'm on pure 6.2. Runs on Fedora Linux.

For example, can't embed a plain news page as [this one](https://www1.folha.uol.com.br/cotidiano/2023/03/promotor-de-mg-e-condenado-a-22-anos-por-feminicidio-mas-mantem-salario-de-r-336-mil.shtml). Gets embedded flawlessly in a Facebook post.
