### ISSUE TITLE
Increase input range component to show more than 4 digits at a time

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#22103]
Currently, the input box from the range component only displays 4 digits, it would be nice if it can adjust to at-least 6 digits. 

![Screen Recording 2020-05-05 at 05 55 PM](https://user-images.githubusercontent.com/5817882/81068727-480cfb80-8efa-11ea-8951-4e05476fdcd9.gif)

This was actually reported to my Gutenberg Forms plugin, but as I am using the core Gutenberg components, I am wondering if this can be improved in the core.
https://github.com/munirkamal/gutenberg-forms/issues/130

Thanks

**Comment by skorasaurus** [comment]
I believe this is controlled through https://github.com/WordPress/gutenberg/blob/14d80aa66819682118a73f3cb40485806b9b8c44/packages/components/src/input-control/input-base.tsx

It's applicable to all blocks that use the input-control component.

**Comment by skorasaurus** [comment]
This is still applicable through the rangecontrol component although you can work around this relatively easily by using a textcontrol component and setting its type to `number` which will allow for number inputs.
