### ISSUE TITLE
The post comments block displays a deprecated notice for comments.php

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22101]
**Describe the bug**
When full site editing is enabled and a post comment block is added to a post, 
the following message is shown on the front:

`Deprecated: Theme without comments.php is deprecated since version 3.0.0 with no alternative available. Please include a comments.php template in your theme.
`

It is to my understanding that full site editing themes will not include comments.php, and does not use comments.php if it is included?

The notice is still important for PHP based themes so I'd say this is a Gutenberg issue not a core issue?

**To reproduce**
1. Enable full site editing
2. Create a post and add a post comment block, save.
3. View the front
4. See the notice.

**Expected behavior**
I was actually confused by the block itself, not only the deprecated notice.
I expected it to _output my comments,_  or nothing, if the post has no comments: Not the comment form.
-There already is a separate block for the comments form, so in my test, the comment form was duplicated.

**Editor version (please complete the following information):**
WordPress version: 5.4.1
Gutenberg: Master, latest commit was: b73bb6d

**Desktop (please complete the following information):**
Windows 10
Chrome version: 81.0.4044.129

**Comment by youknowriad** [comment]
> It is to my understanding that full site editing themes will not include comments.php, and does not use comments.php if it is included?

Ideally yes, that said, I was not able to use the "default comments template" on that bloc without triggering this warning. 

As a second step, this block shouldn't be relying on these php templates and instead we'd need sub blocks like (comment author, comment message, comment date...) to compose  the comments list. But this approach won't be explored for the moment, we'll have to do  the same for posts first.

**Comment by carolinan** [comment]
_it won't be explored for the moment_

I fully understand that the team is small, there is not enough time, and that some things will just be easier to do when you have already perfected for example the post items. 
But this is why people hesitate to even test full site editing, it just feels like waste of time.

**Comment by carolinan** [comment]
What should I focus my testing on?

**Comment by youknowriad** [comment]
Yes, testing at this stage is not for everywhere, and there's no call for testing yet for this reason. You need to have an adventurous mind still :) and it's fine to hit these road blocks for the moment.

That said, here are some good questions that might be good to answer with testing:

 - What blocks are missing to achieve the desired theme templates?
 - What block options are missing for the existing blocks?
 - What custom CSS you had to write for your theme that should/can be replaced with block options instead.

The UI is still at a very early stage too but we can start thinking about UX and ways we can simplify it/ clarify it as much as possible (thinking about the Site Builder page)

**Comment by carolinan** [comment]
There has been multiple calls for testing actually.
My purpose is not to to stand in your way by littering Github with errors that you already know about :)
A _better_ working comments block would be one of the blocks that are missing.

**Comment by youknowriad** [comment]
> A better working comments block would be one of the blocks that are missing.

Can you clarify what do you mean by "better" here. (I mean aside the notice tracked in this issue)

**Comment by carolinan** [comment]
I only meant the notice and the duplication of the form.
The output of the actual comments, when they exist, works fine. 

But I have not attempted to filter the comments, change markup, or style them.
_It is not at all clear to me if a comment walker would still work._ 
_I have not tried to change any comment settings in the WordPress admin to see how they affect the block, including the number of comments to show on the first page, gravatar visibility, comment navigation etc._

**Comment by carolinan** [comment]
Closing in favor of  https://github.com/WordPress/gutenberg/issues/28045
