### ISSUE TITLE
export 'MultiBlocksSwitcher' (imported as 'RootMultiBlocksSwitcher') was not found in '@wordpress/block-editor

### ISSUE THREAD

**Issue by mrvea** [WordPress/gutenberg#22102]
Hello
I am not sure if this a bug, so I am using this option. 
I am make a angular wrapper for gutenberg.
I am using angular 9.1.4 and @wordpress/edit-post 3.16.0. 
I am getting this error
`export 'MultiBlocksSwitcher' (imported as 'RootMultiBlocksSwitcher') was not found in '@wordpress/block-editor`

I checked node_modules and the class is not there.
Do I need to download another package?
or Is it expected not to have this class there?
Any help would be appreciated!

side note: `Not Found - GET https://registry.npmjs.org/@wordpress/edit-widgets - Not found`

**Comment by youknowriad** [comment]
Hi There! do you think you can just use the `BlockSwitcher` component?

**Comment by mrvea** [comment]
I am just importing @wordpress/edit-post into one of my component. I am trying to use the `initializeEditor` function. I am getting this error when I compile my app, and compilation fails. I am not using this component explicitly.

**Comment by mrvea** [comment]
was the npm package updated?

**Comment by youknowriad** [comment]
@mrvea No, it will be next week hopefully. In general, it's done bi-weekly.

**Comment by mrvea** [comment]
ok, thank you very much.
