### ISSUE TITLE
Vimeo Embed Block: 4:3 Video Aspect Ratio Caption Alignment Issue

### ISSUE THREAD

**Issue by kriskorn** [WordPress/gutenberg#22111]
**Describe the bug**

Vimeo videos that have a 4:3 aspect ratio will align captions with a huge gap on screen. 16:9 videos are good and same issue is not reproducible for YouTube videos in my testing. 

**To reproduce**

1. Go to Pages -> Add New
2. Add Vimeo block
3. Use a 4:3 aspect ratio video ( https://vimeo.com/140234227 )
4. Caption is mis-aligned because of responsiveness padding - https://kriskorn.eu/jetpack-testing/video-block-caption/

**Expected behavior**

Checking this link - https://kriskorn.eu/jetpack-testing/video-block-caption/ we can see how captions for 16:9 Vimeo videos works correctly and for 4:3 videos it does not. 

**Screenshots**

<img width="708" alt="vimeo-block-4-3-aspect-ratio-caption-alignment-issue" src="https://user-images.githubusercontent.com/12064241/81094211-db9af800-8f0b-11ea-81e1-5454a3ccd70c.PNG">

**Editor version:**

- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Happens with both core editor and Gutenberg 8.0.0 plugin version.** 

**Desktop:**
 - OS: Windows 10 Pro
 - Browsers: 

1. Google Chrome 81.0.4044.129 
2. Mozilla Firefox 76.0
3. Microsoft Edge 44.18362.449.0
4. Internet Explorer 11.778.18362.0

**Smartphone:**
 - Device: OnePlus 5
 - OS: OxygenOS 9.0.11
 - Browser: Google Chrome
 - Version: 77.0.3865.92

**Comment by gwwar** [comment]
Are you still seeing this one @kriskorn? Captions appear to behave correctly for 16:9 and 4:3 vimeo embeds in Gutenberg trunk

**Comment by paaljoachim** [comment]
Hi

I am testing with WordPress 5.7.
Gutenberg plugin 10.1.1
Twenty Twenty One.

Used these videos to test with:
https://www.youtube.com/watch?v=mM5_T-F1Yn4
https://vimeo.com/251763826

Backend:
![Screen Shot 2021-03-11 at 20 31 09](https://user-images.githubusercontent.com/5323259/110843694-df747500-82a8-11eb-90cb-e7b94a14ce3d.png)


Frontend:
![Screen Shot 2021-03-11 at 20 31 21](https://user-images.githubusercontent.com/5323259/110843719-e56a5600-82a8-11eb-9be8-3f21d66f1374.png)
