### ISSUE TITLE
wp.i18n doesn't seem to work with blocks? 

### ISSUE THREAD

**Issue by rickyfang** [WordPress/gutenberg#22123]
**Describe the bug**
Even though site and user language is set as transitional Chinese and both zh_TW.po and zh_TW.mo exists in Languages folder, the blocks are still showing English only, it seems that wp.i18n is not translation the strings properly for some reason?  

**To reproduce**
1. Go to any editing page with gutenberg, click on add block icon
2. You will see although the categories are translated, the blocks are not. 

**Expected behavior**
All blocks to be translated into transitional Chinese 

**Screenshots**
![Screen Shot 2020-05-06 at 11 11 01 am](https://user-images.githubusercontent.com/6850471/81135333-4e4ab880-8f8a-11ea-8c6e-b1cd78d61ace.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: XOS
 - Browser: Chrome
 - Version: 81.0.4044.129

**Comment by ocean90** [comment]
The issue is that the current zh_TW doesn't contain the JavaScript translations. Please go to the wp-admin/update-core.php screen and click the update button for translations. This will get you the latest translations, including the ones for the block editor.

**Comment by rickyfang** [comment]
I did and still doesn't show up, does it mean that I need to translate those js myself? I thought it was using the same zh_TW.mo file?

**Comment by ocean90** [comment]
Was something updated? You can also try to manually download the language files from [here](https://downloads.wordpress.org/translation/core/5.4.1/zh_TW.zip) and copy all files (.po, .mo, .json) into wp-content/languages.

**Comment by rickyfang** [comment]
Yes something was updated but it was the same, I downloaded the files and it works!! Just wondering will I need to do this everytime when there is an update? 

Thanks for your help
!
