### ISSUE TITLE
Save colors in « Text Color » (toolbar) pro reuse, at least 5

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#22125]
**Is your feature request related to a problem? Please describe.**
I use some colors (pro I.P.A. negative : #800000 or positive #3366FF),
that I reuse many time,
but I have to type them to add their code each time,
and it's quite boring.

**Describe the solution you'd like**
It would be cool to save some of them here, in first or second panel.

<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_git-hub_issues_shared-pictures/master/VorzPremsh/issues/2020-05-06_-_save_colors.jpg">

**Describe alternatives you've considered**
I don't know if we need to save them I data‑base or in session cookie ?
Or any other way that I don't know.

Thank you.

**Comment by annezazu** [comment]
Hi @Nemzag! Thanks for flagging this idea. The good news is that this is being discussed in this open issue: https://github.com/WordPress/gutenberg/issues/19785 I'm going to close yours in favor of the discussion there but keep sharing things you'd like to see :)

**Comment by Nemzag** [comment]
@annezazu 

Ok, thank you,
and good continuation.

**Comment by Nemzag** [comment]
@annezazu 
Hi,
I have an other suggestion,
we can input HEX in second panel,
but it would be faster if we had also directly the HEX bar in first panel.
{The second panel could also have HEX bar, to show value we selecting color in choicer.}
Please add it. Good bye.

**Comment by annezazu** [comment]
Hey @Nemzag! Right now, it's on purpose that the HEX option is only available when selecting custom colors. This is being discussed in the issue I linked above but the gist is that it allows for a simpler and clearer interface for folks to pick colors without getting overwhelmed by options. I don't expect that will change as a result but I hope the context helps explain why it's setup that way.
