### ISSUE TITLE
Reusable blocks adding themselves break the editor.

### ISSUE THREAD

**Issue by Otto42** [WordPress/gutenberg#22131]
**Describe the bug**
Group Blocks, combined with Reusable Blocks, allow for infinite recursion.

**To reproduce**
1. Create a Group Block.
2. Put stuff in it. Anything will do.
3. Save it as a Reusable Block
4. Edit the reusable block
5. Add the reusable block to the end of the group (itself).
6. Save. This may take a couple clicks, it gets a bit jumpy here.

You have created a recursive block reference. 

When testing, I was unable to get this to actually save as the browser jumped to 100% of my CPU and started eating memory. Probably would have failed eventually, but I killed the tab.

Somebody else reported that they got it to save. I wasn't able to get this to occur:
https://www.reddit.com/r/Wordpress/comments/gedk48/created_a_reusable_block_that_had_itself_inside/

**Expected behavior**
Reusable group blocks should be smarter and not allow you to add them to themselves. 

**Editor version (please complete the following information):**
- WordPress trunk, plugin 8.0.0
- Windows 10, Chrome, latest dev track

**Comment by ntsekouras** [comment]
Related https://github.com/WordPress/gutenberg/issues/18704

**Comment by youknowriad** [comment]
Closing as duplicate
