### ISSUE TITLE
Page Break shows up at the top of the "Most used blocks" in the inserter

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#22137]
I've experienced this and other folks too. It seems that the "Page Breaks" block always shows up as the "most used" block even If I have no memory of me using this block at all :)

**Comment by mtias** [comment]
It also shows up as the first item in the `/` inserter, it's quite annoying :)

**Comment by talldan** [comment]
Duplicate of https://github.com/WordPress/gutenberg/issues/22137
