### ISSUE TITLE
Editor: Links may appear unstyled

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#22139]
**Describe the bug**

A `<style>` element injected by Gutenberg plugin that includes the following:

https://github.com/WordPress/gutenberg/blob/827a098b9b03b86147fa98b52fcaa9dc462c7dd4/packages/editor/src/editor-styles.scss#L148-L151

When combined with this rule: 

https://github.com/WordPress/gutenberg/blob/827a098b9b03b86147fa98b52fcaa9dc462c7dd4/packages/editor/src/editor-styles.scss#L11-L16

We effectively have the following rule:

```css
.editor-styles-wrapper a { color: #1e1e1e; }
```

If the theme does not specifically style `a` elements in the editor, they'll be share the text color (black). For example, in TwentyTwenty:

![Screen Shot 2020-05-06 at 14 17 57](https://user-images.githubusercontent.com/841763/81175966-b1494900-8fa4-11ea-969f-9235df337663.png)

This is especially bad for themes that remove the underline, for example Independent Publisher 2:

![Screen Shot 2020-05-06 at 14 19 42](https://user-images.githubusercontent.com/841763/81176304-45b3ab80-8fa5-11ea-99cf-54f97e48edf4.png)

Arguably, themes _should_ style links in the editor. The TwentyTwenty content looks like this previewed on the frontend, the editor styles should use this link color:

![Screen Shot 2020-05-06 at 14 24 46](https://user-images.githubusercontent.com/841763/81176429-6ed43c00-8fa5-11ea-9161-4828412c01e7.png)

However, a black default is surprising. Perhaps the spec for [suggested styling for phrasing content](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) could be used:

```css
.editor a { color: #0000EE; }
```

Change introduced in https://github.com/WordPress/gutenberg/pull/19837 (CC: @ellatrix, @jasmussen)
Reported in https://github.com/Automattic/wp-calypso/issues/41844

**To reproduce**
1. Activate Gutenberg (version 8.0.0) and TwentyTwenty.
2. Add a link in a paragraph.
3. Notice the link has the same color as the surrounding text.

**Expected behavior**

Links should use user agent styling.

**Editor version (please complete the following information):**
- WordPress version: `5.4.1`
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? `8.0.0`

**Comment by ellatrix** [comment]
Yes, we could use a different default colour rather than inheriting the color. Still, themes must style links in the editor stylesheet, which would be automatically prefixed with `.editor-style-wrapper`.

**Comment by jasmussen** [comment]
Good ticket, and very interesting conundrum! 

On the one hand we want to style the editing canvas to prevent inheriting wp-admin colors. On the other hand, the side effect you note here is very real. Putting the canvas in an iframe is a long term solution, if we can make that happen, and Ella is right, you should most definitely style the link color.

However this appears to be an issue even for legacy themes that do not style the editor at all:

<img width="666" alt="Screenshot 2020-05-07 at 09 02 44" src="https://user-images.githubusercontent.com/1204802/81264378-94168800-9041-11ea-81b6-4709a353905c.png">

In those cases, the links should at the very least be blue. I'll take a quick look.

**Comment by jasmussen** [comment]
Created a fix in https://github.com/WordPress/gutenberg/pull/22160. It's not the fix I wanted to make, but it's the only one I could think of.

**Comment by sirreal** [comment]
Thanks @jasmussen! I think #22160 is a good interim solution until we have true isolation for the editor canvas 👍
