### ISSUE TITLE
Including an apostrophe in an image's alt text causes the browser to hang

### ISSUE THREAD

**Issue by picocodes** [WordPress/gutenberg#22145]
**Describe the bug**
Including an apostrophe in an image's alt text causes the browser to hang

**To reproduce**
1. Add an image blog
2. Type an apostrophe in the ALT field

**Expected behavior**
I should be able to add an apostrophe to at ALT tag without any problems

**Screenshots**
![add-apostrophe-to-image](https://user-images.githubusercontent.com/19934448/81192398-db116880-8fc2-11ea-9248-a45b6b58ed16.png)

**Editor version:**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop:**
- OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by kirilzh** [comment]
could not reproduce:
 - OS: MacOS
 - Browser: Chrome

**Comment by talldan** [comment]
I couldn't reproduce either, tested using browserstack on Windows 10, Chrome.

@picocodes Any chance a plugin might be causing this?
