### ISSUE TITLE
Allow patterns to declare a "preferred" viewport for previews

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#22147]
Right now we set an arbitrary width for pattern previews, and attempt to scale things to fit. This handles multiple cases somewhat well enough. However, for some specific designs, it'd be desirable if the pattern could declare their preferred viewing width to avoid visual breakage. I don't expect most patterns to use this, but some could benefit from it.

Examples from @iamtakashi

![image (6) (6)](https://user-images.githubusercontent.com/548849/81195941-bb784100-8fbe-11ea-963c-1e0e52d09256.png)

**Comment by youknowriad** [comment]
The BlockPreview component used to render the patterns already has a "viewportWidth" prop, we just need to add a property to the patterns and pass it to the preview.

**Comment by mtias** [comment]
Yes, that's what I mean — support specifying it in the pattern declaration _as optional_.
