### ISSUE TITLE
Spacer height input steps in 10 not 1

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#22166]
**Describe the bug**
The spacer block height input steps in 10, why should the user be limited in increments of 10? What if they wanted a spacer that was 15px?

**To reproduce**
1. Add a spacer block
2. Use up/down arrows on number input
3. Notice it steps in increments of 10

**Expected behavior**
Steps of 1 to allow any height to be entered.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Comment by talldan** [comment]
I've labeled as a bug, but it'd be good to get some design feedback on how exactly this should work.

**Comment by ninetyninew** [comment]
I've also noticed this has a minimum value allowed of 20 applied - it's really limiting.

**Comment by MichaelArestad** [comment]
I'm really curious as to why it is in increments of 10 as well. I'm going to spin up a quick PR to resolve this in the meantime.
