### ISSUE TITLE
Insert / edit link inconsistencies across blocks

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2216]
The insert/edit link toolbar behaves differently on the text block, image block, and cover image block. While the blocks have different nature, the action of inserting / editing / removing a link is always the same. As a user, I just want to insert a link, change it, or remove it.

Text block insert:
- "Apply" button: ok
- "Unlink" button: I haven't inserted a link yet, maybe it should be disabled?

![screen shot 2017-08-04 at 11 55 27](https://user-images.githubusercontent.com/1682452/28964487-4160c39e-790d-11e7-80cf-c99bb7287ec0.png)

Text block edit:
- I can edit and unlink 👍 

![screen shot 2017-08-04 at 11 55 40](https://user-images.githubusercontent.com/1682452/28964488-416476ba-790d-11e7-93ff-4ec8ea9108fc.png)

Image block insert:

- the UI is different: the formatting toolbar disappears and there's a "Back" button to go back to it. I'd rather simplify and make it behave the same as the text block: show the formatting toolbar _and_ the link toolbar
- there's an "Apply" button but no "Unlink" button. This should be consistent: always show Unlink (disabled) or never show

![screen shot 2017-08-04 at 11 55 53](https://user-images.githubusercontent.com/1682452/28964491-416dcd78-790d-11e7-8486-d8a22aabd927.png)

Image block edit:

- this brings me directly in "edit mode", it should be consistent with the text block and show me an initial view with the "Edit" and "Unlink" buttons
- there's no "Unlink" button: the only way to remove the link is: empty the field and click "Back" or click outside

![screen shot 2017-08-04 at 11 56 08](https://user-images.githubusercontent.com/1682452/28964489-41699028-790d-11e7-8bae-3cbc8dba12fd.png)

Cover image insert:
- clicking on the image (not on the text): the UI allows me to insert a link; seems to me this doesn't produce any actual link, even if the UI shows me there's a link inserted... is this supposed to be used to add a link on the cover image _text_ or on the _image_ itself? both? Unclear.

![screen shot 2017-08-04 at 11 56 16](https://user-images.githubusercontent.com/1682452/28964490-416d7a1c-790d-11e7-976e-503f39195997.png)

Cover image edit:
- long links wrap in new lines (this doesn't happen on text and image blocks)

![screen shot 2017-08-04 at 11 57 27](https://user-images.githubusercontent.com/1682452/28964492-41ad713a-790d-11e7-924f-5c6c20837734.png)

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519320420000243)._

**Comment by karmatosed** [comment]
With all the work going on with links in #4909 lets close this and review after.
