### ISSUE TITLE
Translation for 'Custom' with context

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#22161]
**Is your feature request related to a problem? Please describe.**
Currently, at least in German we have a problem with translating the value of “Custom” in the Font Size Picker component. In general, it should be “Individuell” or “Benutzerdefiniert”. However, as you can see, these words are much more longer than “Custom”.

**Describe the solution you'd like**
I would love to see a custom context for the translation of 'Custom' in the Font Size Picker component:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/font-size-picker/index.js#L35

This way, we can use a custom translation for this particular string in order to make it more short (translate it to “Eigene”).

**Comment by KittMedia** [comment]
Also related to #21327

**Comment by Soean** [comment]
I fixed the issue with the button in https://github.com/WordPress/gutenberg/pull/22896#issuecomment-638950821, so I think we can close it. Please reopen, if we still need this context.
