### ISSUE TITLE
css media queries and preview-dropdown button in edit post

### ISSUE THREAD

**Issue by nonamich** [WordPress/gutenberg#22172]
**Describe the bug**
when changing a device using [preview-dropdown](https://i.imgur.com/8N9njes.png), the corresponding css media queries across the width of the screen are not applied. then remark generally need a [preview-dropdown](https://i.imgur.com/8N9njes.png) button?

**To reproduce**
1. Go to Edit Post
2. Click on [Preview Dropdown Button](https://i.imgur.com/8N9njes.png)

**Expected behavior**
I expected css media queries to apply

**Screenshots**
1. [Screenshot](https://i.imgur.com/gN0p26J.png)
2. [Screenshot](https://i.imgur.com/8N9njes.png)

**Editor version:**
- WordPress version: 5.4.1
- use gutenberg plugin
- gutenberg  version 8.0.0

**Desktop:**
 - OS: windows
 - Browser chrome
 - Version 81.0.4044.129

**Theme:**
- [gutenberg-starter-theme](https://github.com/WordPress/gutenberg-starter-theme)

**Comment by noisysocks** [comment]
This worked in my testing. I added a Columns block and, when selecting Preview → Mobile, it went from 3 columns to 2 columns.

@dimaeromin97: Is there a specific media query or CSS rule that's not working for you?

Note that the ongoing work in https://github.com/WordPress/gutenberg/pull/25775 will probably address this.

**Comment by leadclown** [comment]
i can confirm that. media queries are working fine in frontend and when i resize the window in backend too but not with the preview dropdown. columns are working but no own custom queries.

regardless if i add them with add_editor_style or enqueue_block_assets / enqueue_block_editor_assets.

css is loading correctly but queries are not working. really strange.

**Comment by stefanfisk** [comment]
I'm having the same issue, and the breakpoints are not modified no matter if I use `add_editor_style()` or `wp_enqueu_style()`. I'm using really basic stuff like:

How would I go about debugging this functionality?

```
@media (min-width: 1024px) {
  .editor-styles-wrapper .lg\:u-w-2\/5 {
    width: 40% !important;
  }
}
```

**Comment by stefanfisk** [comment]
Never mind, my issue was with my `#end-resizable-editor-section` being positioned incorrectly by a css-processor.

But still, where can I find the documentation for this feature? I've had two customers now who have been asking me why the preview buttons don't work, and even finding this issue took quite a bit of googling.

**Comment by jordesign** [comment]
With no further discussion on this issue I'm going to close it for now. If it does continue to be an issue please feel to re-open with updated testing/details.

**Comment by Mamaduka** [comment]
The issue should be fixed with iframed editors.
