### ISSUE TITLE
View Post button gone in full screen mode

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#22180]
With the new Gutenberg fullscreen mode view there is no way to get to view the page.
There is no button.
The link for that is gone and clients are annoyed they cannot find it. 
I need to show them that they can exit the full screen mode, and then click the 'view post' in the admin bar.

There is a preview button but it's not the same. It sometimes does not load or takes long and also, they don't want to see the preview, they want to see what the page looks like now.

I'm also a bit perplexed...
Any way to add a view page/post on the fullscreen mode??

**Comment by talldan** [comment]
Thanks for reporting @saltnpixels. This was reported in https://github.com/WordPress/gutenberg/issues/21739, so I'll close your issue.
