### ISSUE TITLE
Adding a link to Media+Text block breaks the background

### ISSUE THREAD

**Issue by julioas09** [WordPress/gutenberg#22187]
**Describe the bug**
When using the Media and Text block, setting a background color, and setting a link, the background breaks.

**To reproduce**
1. Create Media and Text block
2. Add Image and Text
3. Set background color
4. Add link to block

**Expected behavior**
The background consistency is maintained and the block correctly links to the desired URL.

**Screenshots**
In the editor:
![Annotation 2020-05-07 202835](https://user-images.githubusercontent.com/3543529/81331217-8abd0800-90a1-11ea-9ad8-94593723af6d.png)
In the web:
![Annotation 2020-05-07 202916](https://user-images.githubusercontent.com/3543529/81331235-914b7f80-90a1-11ea-8dec-580f225b0e11.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1–es_ES
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default editor
- If the Gutenberg plugin is installed, which version is it? -

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by talldan** [comment]
Thanks for the report @julioas09, would you also be able to share which theme you're using?

**Comment by julioas09** [comment]
I'm using Twenty Seventeen

**Comment by paaljoachim** [comment]
I can confirm. I am testing using 
Chrome, 
OSX,
Twenty Seventeen 
WordPress 5.4
(No Gutenberg plugin activated)

Backend:
![Screen Shot 2020-05-14 at 00 01 26](https://user-images.githubusercontent.com/5323259/81870430-1c32eb00-9576-11ea-8772-de195260ed6b.png)

Frontend:
![Screen Shot 2020-05-14 at 00 01 34](https://user-images.githubusercontent.com/5323259/81870447-2359f900-9576-11ea-93c1-214f67321a88.png)

Frontend: (when not linking the image to a page/post.)
![Screen Shot 2020-05-14 at 00 03 20](https://user-images.githubusercontent.com/5323259/81870551-60be8680-9576-11ea-8e0e-1c782293cd26.png)

**Comment by annezazu** [comment]
This issue seems related to this: https://github.com/WordPress/gutenberg/issues/21399 Just noting for whoever is able to dig into this!

**Comment by stokesman** [comment]
Quick aside, in case anybody want's a CSS workaround for Twenty Seventeen:
```CSS
.entry-content .wp-block-media-text__media a img{
  box-shadow:none;
}
```

Now to address the issue, I'd say it isn't with Gutenberg. The break in the background color is from Twenty Seventeen applying `box-shadow` to any images matching the selector [`.entry-content a img`](https://themes.trac.wordpress.org/browser/twentyseventeen/2.4/style.css#L1289). It would be overly opinionated of the block styles to specify box-shadow so as to prevent this.

That box-shadow will also appear on images in Image or Gallery blocks that have links applied. Those blocks are less likely to be problematic though. Here are examples:
Image block with link | Gallery block with links
------|------
![2017-image-w-link](https://user-images.githubusercontent.com/9000376/100056283-42193200-2dda-11eb-8b54-6e3cef5d62ca.png) | ![2017-gallery-w-link](https://user-images.githubusercontent.com/9000376/100056807-2a8e7900-2ddb-11eb-979e-1234dcf1725e.png)

I found this issue after creating #27211 and then looking for existing issues. If merged, that PR would incidentally prevent the display issue detailed here. Regardless, those box-shadow styles in Twenty Seventeen should be revisited. I looked into creating a ticket in Trac for Twenty Seventeen but failed to figure that out 😕 .

**Comment by stokesman** [comment]
I've made https://github.com/Automattic/themes/issues/3376 based on my evaluation that this stems from styling in Twenty Seventeen and while it could be prevented with styling in Gutenberg it seems like that'd be overly opinionated of the block styles. So I'm feeling like this would be okay to close now. In case someone has a good argument otherwise I'll leave it open.

**Comment by paaljoachim** [comment]
I will ping @laras126 @ryelle to give it a last nice test.
I am thinking we can then close this issue after they have looked through.

**Comment by ryelle** [comment]
The added border does seem to be a bug with Twenty Seventeen - I checked a few other twenty- themes and they appear the same whether the image has a link or not. I'm going to close this issue, in favor of a trac ticket for Twenty Seventeen (which I've asked for over on https://github.com/Automattic/themes/issues/3376).
