### ISSUE TITLE
Gallery Captions are centered in the editor, but not on the sites

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#22188]
**Describe the bug**
Galleries have a cool new caption feature. When editing the page or post, one can add a caption. That caption appears centered. But on every theme I've tested, the caption is left-aligned when viewing the site.

**To reproduce**
1. Insert a gallery into a page or post
2. Add a caption: note it is centered
3. View the page or post outside the editor: note the caption is not centered

**Expected behavior**
Ideally?  It'd be lovely if one could specify alignment for the caption. But since we can't right now, I think it'd be great to have consistency between what shows up in the editor and what appears in most themes.

**Screenshots**
Editor:
<img width="913" alt="Screen Shot 2020-05-07 at 1 08 34 PM" src="https://user-images.githubusercontent.com/3476361/81334862-ed8fae80-9063-11ea-891b-3f4c3967bd7d.png">

Live site:
<img width="801" alt="Screen Shot 2020-05-07 at 1 08 19 PM" src="https://user-images.githubusercontent.com/3476361/81334866-eec0db80-9063-11ea-899e-7fcb8cf504f7.png">

**Editor version (please complete the following information):**
- WordPress version:  5.4.1 as well as WordPress.com
- Gutenberg plugin is not active on my test .org instance.

**Desktop (please complete the following information):**
 Doesn't matter

**Smartphone (please complete the following information):**
 n/a -- happens on any browser. I've seen so far

**Comment by kjellr** [comment]
Just a quick additional note — these do inherit [the correct `theme.css` caption styles](https://github.com/WordPress/gutenberg/blob/1612debc1999a207962b29670ee42225b40ed2a1/packages/block-library/src/gallery/theme.scss), but the caption is not centered out of the box. Those styles are identical to the ones used on other blocks, so I'm not sure if there's something different about the way the gallery block is structured?

**Comment by KokkieH** [comment]
Noting the user reports the same thing happens with video captions as well.

**Comment by dreamwhisper** [comment]
This also happens with the image caption.

**Comment by annbingle** [comment]
Same issue reported here 23354786-hc However, this time the caption doesn't show the alignment option.

**Comment by kishanjasani** [comment]
I would like to take it over. Seems like a CSS issue in the Gutenberg.

**Comment by kishanjasani** [comment]
@dreamwhisper Image caption is already centered on frontend and backend.
