### ISSUE TITLE
Text Mode on a block basis

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2219]
Would like to ask for a toolbar button to switch to text mode per a block ?

Now when you guaranty blocks are isolated and comparted I think we can have it.
It would come handy for instance when Table block is giving problems to switch to text mode and inspect block. Or iframe, or anything. Troubleshoot what HTML a shortcode (block) display.

Before in TinyMce you never knew where it would end, and global Text mode had its logic. Now with all block separation we can switch to Text mode per a block.
One notice despite, it would need to be filterable to show Text mode button to Admins only.

**Comment by aduth** [comment]
This could be a neat alternative for Text mode altogether even.

**Comment by karmatosed** [comment]
I almost feel this is worthy of a user test, in the sense of how better is an all in one mode over having it per block? My gut says that per block is not needed, it's almost too much. Text mode is an advanced feature and seeing it there each time could be added noise for typical users.

**Comment by StaggerLeee** [comment]
Hi. That is why I said as button for Admins. I agree it would be stupid to force this button under Users noses unnecessary all the time. Probably would be one of the most unneeded buttons around.

Much of contradicting wishes here on Github could be solved by one new Settings Page for Gutenberg. Some options, decide what different roles see. We have to wait for some plugin as AdvancedTinyMce to come.

What to do now, you change revolutionary with Gutenberg. On other side you stay steadily as rock, to not make any new Settings page options.

**Comment by hedgefield** [comment]
Is the per-block Edit HTML option that was recently added sufficient to complete this request?

**Comment by aduth** [comment]
Yes, I think this can be considered closed by #2797.

Also: #2794

**Comment by StaggerLeee** [comment]
More than sufficient. Thank you.

Please reconsider to automatically  switch all HTML previews to default visual blocks when User click outside blocks.
I can bet in my arms and see already now how beginners edit directly HTML code, thinking they did something wrong by copy-pasting, or typing.
