### ISSUE TITLE
Copy / pasting media files, pictures

### ISSUE THREAD

**Issue by andreasdiehl** [WordPress/gutenberg#22205]
Until recently it was possible to copy / paste a text incl. graphics from let's say a gDoc to Gutenberg. Gutenberg handled all that and turned text into text blocks and pictures to picture block. Now all pictures are added as a text block.

I consider that a very important and nice feature as it allow to write all blog contents in a gDoc.

**Comment by annezazu** [comment]
@andreasdiehl thanks for reaching out here! I tried to replicate this using WordPress 5.4.1 and Gutenberg 8.0 but wasn't able to do so. Here's a video: https://cloudup.com/cj0XEqUdu5r

What version of WordPress and Gutenberg are you using?

**Comment by andreasdiehl** [comment]
Thanks. I was referring to graphics, they have recently been added as a graphic in Gutenberg as well, now as a text block:

https://www.dropbox.com/s/ch3k26d5lk7l2nz/2020-05-12_21-10-55.mp4?dl=0

I am running on the latest WP version  5.4.1

**Comment by annezazu** [comment]
@andreasdiehl ah ha! Thanks for clarifying. The video is super helpful. Can you tell me more about  the graphic you have in the Google Doc? Is it an image? How was it made? Any information you can provide will be helpful.  Right now, I'm finding with WordPress 5.4.1 that images from Google Docs move over just fine so I'm trying to narrow down the problem.

**Comment by andreasdiehl** [comment]
Standard PNG or JPEG. Usually I simply drag & drop them to my gDoc or (most often) I simply make a screenshot from a keynote (cmd+ctrl+shift+4) and paste them to the gDoc. This used to work perfectly, WP recognised them as a picture. Now as soon as it comes from a gDoc its a text block. Using the same image from my desktop it is recognised as a picture.

This show the two scenarios:
This is an image I have in a gDoc

**Comment by annezazu** [comment]
@andreasdiehl thank you for this video! Flagging this as a confirmed bug that I am able to replicate now although intermittently. Here's what I tried:

- Uploading JPEG files from GDoc to Gutenberg (this is the only time I ran into initial failures)
- Uploading PNG files from GDoc to Gutenberg
- Uploading GIF files from GDoc to Gutenberg
- Uploading various sized files to see if there was a file size issue at play (just a random guess). 

At first, I was able to replicate but, strangely, even with the same file I could both replicate and not replicate the problem!

Here's a video demoing this strangeness: https://cloudup.com/c8nfVYUAM30

Not sure what's going on here but changing the labels to make sure it's seen as a bug for now!

**Comment by andreasdiehl** [comment]
@annezazu thanks. Is there a correlation with the file type, did you notice any difference?

For me whatever the original file is (PNG, JPEG), copying them and pasting them to Gutenberg ends up as a text block.

**Comment by annezazu** [comment]
I couldn't find a correlation. I thought at first it might only be happening with JPEGs but disproved that in my testing. Very, very strange indeed!

**Comment by talldan** [comment]
This seems to have been resolved now. I can copy/paste text plus images fine from google docs.

Feel free to reopen if you're still experiencing the issue.
