### ISSUE TITLE
addFilter to hook into the block editor components-toolbar

### ISSUE THREAD

**Issue by elpuas** [WordPress/gutenberg#22203]
I'm trying to Hook into the block editor components-toolbar, but couldn't find any reference, my idea was to use a filter to remove some of the defaults block editor components toolbar items on all components.

![Screen Shot 2020-05-07 at 20 27 53](https://user-images.githubusercontent.com/3707088/81364515-0bc8cf00-90a3-11ea-9958-46baaeb2bc54.png)

Any hint is more than welcome, thanks

**Comment by phpbits** [comment]
You can use `PluginBlockSettingsMenuItem`. Here's the docs link : https://developer.wordpress.org/block-editor/developers/slotfills/plugin-block-settings-menu-item/ 👍

**Comment by elpuas** [comment]
Sweet! Thanks, @phpbits SlotFills of course!
