### ISSUE TITLE
 Instagram Embed Block not working with REST API

### ISSUE THREAD

**Issue by Koli14** [WordPress/gutenberg#22223]
**Describe the bug**
If I create an Instagram Embed Block in Gutenberg, it is displayed in my WP Theme, but retrieves this through the REST API:
[gunteberg-post-embed-insta-rest-api.txt](https://github.com/WordPress/gutenberg/files/4599131/gunteberg-post-embed-insta-rest-api.txt)
Formatted: 
[gunteberg-post-embed-insta-rest-api-formatted.txt](https://github.com/WordPress/gutenberg/files/4599132/gunteberg-post-embed-insta-rest-api-formatted.txt)
Screenshot:
![Screenshot_2020-05-08 teszt2](https://user-images.githubusercontent.com/400223/81409248-10db5c00-913f-11ea-92e0-4263084e0a7e.png)

**To reproduce**
1. Embed an instagram post in Gutenberg with Embeds -> Instagram
2. Watch it in REST API like: example.com/wp-json/wp/v2/posts/POSTID

**Expected behavior**
I expect that the REST API returns an iframe, as it returns it for WP Frontend, or as other embeds returns iframe for the REST API(I tried youtube and vimeo).

**Screenshots**
I get this:

![Screenshot_2020-05-08 teszt2](https://user-images.githubusercontent.com/400223/81410298-cb1f9300-9140-11ea-92b4-da69cf394ad5.png)

Instead of this:

![Screenshot_2020-05-08 Videóban kérik A mi kis falunk színészei, hogy mindenki maradjon otthon - Page 2 of 2](https://user-images.githubusercontent.com/400223/81410367-e094bd00-9140-11ea-86db-f1038b9378a7.png)

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? - Default

**Additional context**
If I use the Custom HTML block in Gutenberg, and embed the iframe what I found in WP Frontend, than it's working perfectly.

**Comment by annezazu** [comment]
@Koli14 Thanks for reporting this! I tried to replicate using WordPress 5.4.1 without Gutenberg installed and wasn't able to find the same problem.

I see you're using WordPress 5.3.2 rather than the latest version (5.4.1). Please try updating to the latest version as a next step. If you still experience problems, feel free to reopen this!
