### ISSUE TITLE
Edit Site: Add routes or query args to get URIs for individual templates

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#22238]
We're currently using the template selector dropdown to switch between individual templates (and template parts), which uses component [context](https://github.com/WordPress/gutenberg/blob/341ae68a225ee29553b0f7b0f39b48a31da7af48/packages/edit-site/src/components/block-editor/index.js#L54-L62) and [state](https://github.com/WordPress/gutenberg/blob/3fef78123bd518ebec0ad84da82d4a86cafaf4d3/packages/edit-site/src/components/editor/index.js#L48) to set the currently selected template, while the URL stays the same (`/wp-admin/admin.php?page=gutenberg-edit-site`).

I think we should provide a way to point to the Site Editor with a specific template selected, so that we can link to it e.g. from other parts of wp-admin, or other admin panels and contexts.

---

This _could_ be something like <code>/wp-admin/edit-site.php?template=page&amp;action=edit&amp</code>. We should take into account how to modify the route once we implement [context loading](https://github.com/WordPress/gutenberg/issues/19257) (and want to specify _which_ context/entity should be loaded). We could make it <code>/wp-admin/edit-site.php?template=page&amp;action=edit&amp;entity=123</code>, where <code>entity</code> is the ID of the page/post/category/... we're interested in. I'm not entirely sure if this route format can scale to all parts of the <a href="https://wphierarchy.com/" rel="nofollow ugc">template hierarchy</a>, even if we decide to leave out a few template types, since some template types cannot be specified via an ID (think a yearly archive). The most natural way to refer to an entity would be that entity's route, so maybe we should consider something like <code>/wp-admin/edit-site.php?template=page&amp;action=edit&amp;entity=/about</code>.</p>

(There's a point to be made that this route may be overdefined: The route to an entity already implies the part of the template hierarchy that matches it best; and some templates are incompatible with some entities (can't use a page template for a category archive). So we could theoretically drop the <code>template</code> arg from the route. But this gets us into somewhat deep waters where we might end up reasoning about <a href="https://github.com/WordPress/gutenberg/issues/21086">where to draw the line between site and content editing</a> :grimacing: )

**Comment by epiqueras** [comment]
The context is specified by `WP_Query` parameters.

>But this gets us into somewhat deep waters where we might end up reasoning about where to draw the line between site and content editing 😬 )

I don't see why.

**Comment by ockham** [comment]
> The context is specified by `WP_Query` parameters.

Not sure I understand -- how comes `WP_Query` into play in a scenario like #19257 (where we want to allow the user to pick context that we use to populate placeholders in a template)?

> > But this gets us into somewhat deep waters where we might end up reasoning about where to draw the line between site and content editing :grimacing: )
> 
> I don't see why.

Imagine a route to the Site Editor that specifies a context to render, but infers the corresponding template from that (such as `/wp-admin/edit-site.php?action=edit&entity=/about` -- where the relevant template is `page`). Now we point to the site editor showing the `page` template, with the About page content loaded. I think that this has the potential of making the corresponding post editor view -- that just shows the About page _content_ -- obsolete, since the user can now choose between editing both presentation and content at once, or only the content. Assuming that the UX would be great in both (and inline editing of the content would work in the site editor) -- why would a user still want to use the post editor to edit that page?

**Comment by epiqueras** [comment]
>Not sure I understand -- how comes WP_Query into play in a scenario like #19257 (where we want to allow the user to pick context that we use to populate placeholders in a template)?

```
?p=id
?category_name=name
```

>why would a user still want to use the post editor to edit that page?

If they don't have permission to edit the layout, for example, the editors could also merge in the future.

**Comment by vindl** [comment]
This has been added in https://github.com/WordPress/gutenberg/pull/27124.
