### ISSUE TITLE
Remove index.php with nginx?

### ISSUE THREAD

**Issue by Anti067** [WordPress/gutenberg#22243]
Hello,
when i open site.com/somedir it will return me automatic to index.php

How can i remove index.php from url? I mean i want to return 404 when dir is not exist.

My rules right now is;

location / {
try_files $uri $uri/ /index.php?$args;
}

**Comment by chrisvanpatten** [comment]
Hi @Anti067 — unfortunately this space is not intended for support requests. I'm also not totally sure how it relates to Gutenberg itself, which does not have an `index.php` at the root.

I'd recommend bringing your question to the ["advanced" forum at WordPress.org](https://wordpress.org/support/forum/wp-advanced/).

If you have further questions or anything which indicates this is connected to a Gutenberg bug, please let me know and we can reopen. Thanks!
