### ISSUE TITLE
Gallery Spacing toggles

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#22247]
**Describe the bug**
This is a UX bug. 

To remove the spacing the toogle is on. 
To add the spacing the toggle is off. 

**Expected behavior**
It should be the other way around. 

On = spacing
Off = No spacing. 

Simple. 

In addition, there's no indication on the block what the spacing status is. The toggle doesn't change anything. There should be something visual for spacing (on all blocks**). As it is, you have to make the block active and then open the Advanced panel to find out what the spacing settings are. That's two clicks too many. 

** I opened a previous issue about this and that was closed. smh

**Comment by talldan** [comment]
Hey @AlchemyUnited. I had a look at the gallery block, and it doesn't look like there are any spacing toggles. It might be that this is a feature added by a plugin, in which case there might not be much we can do here, you'd have to contact the plugin developer.

Could you drop a screenshot of the toggles into this issue? Thanks.

> I opened a previous issue about this and that was closed

Do you have a link to that?

**Comment by AlchemyUnited** [comment]
@talldan - Ahh. You're correct. Sorry about that. 

Looks like it was CoBlocks or FooGallery.

Again, my apologizes. You can close this. Thanks.

**Comment by AlchemyUnited** [comment]
p.s. FYI - Looks like it was CoBlocks.

**Comment by paaljoachim** [comment]
Hey @AlchemyUnited 
Can you add the CoBlocks toggles screenshot to this issue?
Just so when others come across it they will know right away the toggle looks like.

**Comment by AlchemyUnited** [comment]
@paaljoachim 

On is remove

Off is add

Feels like a duoble negitve to me ;)

![x-gallery-remove-spacing](https://user-images.githubusercontent.com/1966613/81730644-d7b32c80-945b-11ea-93ce-bce3e9c2b1ee.png)

**Comment by talldan** [comment]
Thanks @AlchemyUnited, I'll close the issue.
