### ISSUE TITLE
Publish this repo to packagist.org for other projects consumption

### ISSUE THREAD

**Issue by werfu** [WordPress/gutenberg#22248]
I know that Gutenberg is maintained by the Wordpress team and that this is your sole focus, but for those like me who'd like to support it into a different environment (Magento2 in my case), it would be very helpful if you could publish this repo to packagist.org. 

Thanks :)

**Comment by Soean** [comment]
All plugins and themes from the wordpress.org repository are available via https://wpackagist.org/. Maybe this is what you are looking for?

**Comment by werfu** [comment]
Soean, I know about wpackagist.org. The idea behind publishing to packagist.org is to allow usage of Gutenberg outside of Wordpress. I'd rather not add wpackagist as package source, this opens up possible package conflict. And there's already a Wordpress namespace on packagist.org so why not?

**Comment by ocean90** [comment]
> to allow usage of Gutenberg outside of WordPress.

Noting that this is already possible, see [Laraberg](https://github.com/VanOns/laraberg) or [Drupal Gutenberg](https://drupalgutenberg.org/) for example.

I'm wondering which parts of this WordPress plugin you'd need outside of WordPress? Most of Gutenberg - if not all - is written in JavaScript and thus available on npm.

**Comment by werfu** [comment]
Ocean90, from what I see the npm gutenberg-js repository lags behind the Wordpress/Gutenberg repo quite a bit. I'm aiming for Magento 2 integration, and it would be nice to be able to support somewhat of an integration using some glue code to provide the required basic features from the PHP functionalities, though I don't want to reimplement Wordpress inside Magento.

**Comment by ocean90** [comment]
That's because gutenberg-js is deprecated, you should use the Gutenberg packages directly like Drupal Gutenberg does.

This repo really only contains the source of the various npm packages which wouldn't allow you to integrate the editor via composer into another platform.

**Comment by ocean90** [comment]
Gutenberg has [several packages](https://github.com/WordPress/gutenberg/tree/master/packages), the main one is probably [@wordpress/block-editor](https://www.npmjs.com/package/@wordpress/block-editor).

**Comment by werfu** [comment]
That makes sense! Thank for the clear up, I'll have a look at those then.

**Comment by barryvdh** [comment]
@werfu  Did you get anywhere with Magento2 integration?
