### ISSUE TITLE
Custom component HTMLComment fails to render on save

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#22244]
Hi there!

I'm building a custom block to design HTML email templates. This is my edit function:
``` 
edit: ( props ) => {
  const { className } = props;
  return [
    <div className = {className} >
    ...
      <HTMLComment text={'[if mso]><table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;"><tr><![endif]'} />
      <HTMLComment text={'[if mso]><td valign="top" width="600" style="width:600px;"><![endif]'} />
      <table align={'left'} border={0} cellPadding={0} cellSpacing={0} style={{maxWidth:'100%', minWidth:'100%'}} width={'100%'} className={'bmTextContentContainer'}>
      ...
        <InnerBlocks
          allowedBlocks = { ['core/paragraph', 'core/heading', 'core/list', 'core/freeform'] }
          template = { [
            ['core/paragraph', { placeholder: __( 'Start writing your paragraph', 'boldermail' ) }],
          ] }
          templateLock = { false }
        />
      ...
      </table>
      <HTMLComment text={'[if mso]></td><![endif]'} />
      <HTMLComment text={'[if mso]></tr></table><![endif]'} />
    ...
    </div>
  ];
},
```
My block basically adds a bunch of tables around core blocks so the content can be displayed properly in an email. Most email templates have conditional HTML comments for Microsoft Outlook to display responsive content. Since React cannot include HTML comments, I added an HTMLComment component to my code based on [this repository](https://github.com/Zneider/react-html-comment).
```
const { createRef, useLayoutEffect } = wp.element;
import PropTypes from 'prop-types';

const HTMLComment = ({ text }) => {
  const ref = createRef();

  useLayoutEffect(() => {
    let el = null
    let parent = null
    let comm = null

    if (ref.current) {
      el = ref.current;
      parent = el.parentNode;
      comm = document.createComment(`${text.trim()}`);
      try {
        if (parent && parent.contains(el)) {
          parent.replaceChild(comm, el);
        }
      } catch (err) {
        console.error(err);
      }
    }

    return () => {
      if(parent && el && comm) {
        parent.replaceChild(el, comm)
      }
    }
  }, []);

  return <span ref={ref} style={{ display: 'none' }} />;
};

HTMLComment.propTypes = {
  text: PropTypes.string,
};
```
The comments render properly in the block editor:
```
<!--[if mso]><table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;"><tr><![endif]-->
<!--[if mso]><td valign="top" width="600" style="width:600px;"><![endif]-->
...
```
 but when I save my post, it fails to save anything. All the database displays is `<!-- wp:mynamespace/text /-->`. And once I refresh the page, the block has invalid content. Here is my save function:
```
save: () => {
  return (
    <table border={0} cellPadding={0} cellSpacing={0} width={'100%'} className={'bmTextBlock'} style={{minWidth:'100%'}}>
      ...
      <HTMLComment text={'[if mso]><table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;"><tr><![endif]'} />
      <HTMLComment text={'[if mso]><td valign="top" width="600" style="width:600px;"><![endif]'} />
      <table align={'left'} border={0} cellPadding={0} cellSpacing={0} style={{maxWidth:'100%', minWidth:'100%'}} width={'100%'} className={'bmTextContentContainer'}>
      ...
        <InnerBlocks.Content />
      ...
      </table>
      <HTMLComment text={'[if mso]></td><![endif]'} />
      <HTMLComment text={'[if mso]></tr></table><![endif]'} />
      ...
    </table>
  );
},
```
It's basically a copy of the edit function. If I remove the HTMLComment component from the save function, then my content saves properly. Could this be a bug in the serializer?

**Comment by chrisvanpatten** [comment]
@chvillanuevap I believe you can use the `RawHTML` component to handle the output in the `save` function. This is how the core pagination block works, for instance.

You can see a code example here: https://github.com/WordPress/gutenberg/blob/f63053cace3c02e284f00918e1854284c85b9132/packages/block-library/src/nextpage/save.js#L6-L8

As we don't typically handle support requests here, I'll close this issue but if the code I linked to above doesn't help you, it could indicate there's a bug and you are more than welcome to ask us to reopen the issue :)

**Comment by chvillanuevap** [comment]
I did try using the `RawHTML` component. The problem is that if you place a comment inside the component, `RawHTML` will add `<div>` tags around the comment because React does not consider comments as "children". And those `<div>` tags would break the display of the tables in Outlook.

I guess my question is whether forcing comments into the `save` function with my custom `HTMLComment` component breaks the Gutenberg serializer. My guess is that it does, since Gutenberg depends on HTML comments to save attributes, and having comments already in the block may confuse the serializer.

**Comment by chrisvanpatten** [comment]
@chvillanuevap I believe the issue with your comment component implementation is that save functions _must_ be pure, but your code is effectful.

Can I offer another suggestion — have you considered using server side rendering for this, instead of worrying about serializing directly into the block markup?

That would give you full control over the render output without worrying about the serializer.

Something like this would work, by filtering the block output before it's actually rendered to the front-end page.

```
<?php

add_filter(
    'render_block', 
    function (string $content, array $block) : string {
        if ($block['blockName'] !== 'custom/block') {
            return $content;
        }

        return $content . '<!-- custom comments -->';
    },
    10,
    2
);
```

**Comment by chvillanuevap** [comment]
I think that's the route I'm going for now. I'm placing a string placeholder in the save function, and then I'm doing a search and replace before output. Thanks for your help!
