### ISSUE TITLE
Allow users to insert/move blocks within an inner block but not move blocks outside

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#22242]
I was reading issue #11131 as I'm having a similar problem. I have an inner block that allows paragraphs to be added inside. I would like the user to be able to insert and delete blocks, but only be able to move blocks within the inner block. Right now there is not an option for that. "all" prevents inserting/deleting/moving blocks; "insert" prevents moving blocks outside the inner block, but does not allow inserting/deleting new blocks.

I would like to suggest a third option, something like "moveOut" where the user can insert/delete blocks, and move them, but only within the inner block. Does that make sense?

**Comment by chrisvanpatten** [comment]
Hi @chvillanuevap — I believe your request relates to #8112. To keep the conversation in one spot, I'd ask you to put a comment on that thread as there's a lot of related discussion there as well!
