### ISSUE TITLE
Change 

### ISSUE THREAD

**Issue by jaredsnider** [WordPress/gutenberg#22253]
**Is your feature request related to a problem? Please describe.**
The CSS on line 37 of gutenberg.css conflicts with the Bootstrap `.container` class when previewing blocks in the Gutenberg editor:

```
.container {
 margin:0 auto;
 width:650px;
 background-color:#eee;
 border:1px solid #eee
}
```

**Describe the solution you'd like**
Given the popularity and wide use of Bootstrap it would be great if you could adjust the `.container` class to be something more specific (for example `.wpgb-container` to avoid conflicts with the framework.

**Describe alternatives you've considered**
I have had to override the default styling so my custom theme (which uses the Understrap theme - and therefore Bootstrap) appears as expected in the Gutenberg editor, editing the framework's grid class name is simply not feasible. Thank you for all your hard work!

**Comment by chrisvanpatten** [comment]
Hi @jaredsnider —

I did some poking around the code and I wasn't actually able to find any use of the `.container` class name in Gutenberg outside of the React Native styles (which are for the WordPress iOS/Android apps, and are processed in isolation from web styles).

Typically in Gutenberg, we do prefix styles with `block-editor__*`, following a [BEM-style syntax](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#naming) to avoid these types of conflicts.

Is there any chance the class name is actually defined in your current theme, or in WordPress core itself?

**Comment by jaredsnider** [comment]
Hi @chrisvanpatten ! Upon further inspection, its actually a plugin that has a stylesheet called `gutenberg.css` which I took for granted as being from WordPress, so per usual I didn't look closely enough. Sorry to bother and thanks for taking the time!
