### ISSUE TITLE
Cover: Add option to desaturate background media

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#22278]
**Is your feature request related to a problem? Please describe.**
Often when selecting a background for a cover block, the overlay colors clash with the colors of the photo. I usually end up manually editing the photo so it's totally desaturated, then re-upload. Voila — beautiful cover overlay.

**Describe the solution you'd like**
It would be lovely if there could be an option to desaturate the image (or video? Is that possible?) using something like [CSS filters](https://css-tricks.com/almanac/properties/f/filter/), so users don't have to do this manually.

**Describe alternatives you've considered**
We could consider doing this automatically when an overlay color is used. Alternately, I could remember to desaturate my stuff before uploading 🙂

**Comment by mapk** [comment]
Good idea! We'll need a design for a Saturation scale control. Maybe it's as simple as adding it like this?

![saturation](https://user-images.githubusercontent.com/617986/81624561-51d7a880-93ab-11ea-9a3e-7877a2f59ccc.png)

**Comment by paaljoachim** [comment]
What an interesting idea!

Another area this would be great in would be in a hover effect.

**Comment by ItsJonQ** [comment]
Haii!! I think it's a great idea :)!

I looked into it briefly:
There is a trickiness to this...

For this to work properly, we'll have to create a dedicated element that renders the background image. That way, we can apply the CSS filters to that image (only). At the moment, adding a CSS filter to the Cover would affect the contents within (e.g. paragraphs, titles, etc...).

Doing what I'm describing above isn't difficult. However, it would change the HTML markup output of Cover moving forward. I'm guessing we'll need to setup deprecations if that were to happen.

Not blocking! Just leaving a note for future self (or for anyone who would like to give this a shot)

**Comment by ItsJonQ** [comment]
@melchoyce I didn't forget about this! I experimented with something today that I think will help 😊 

A new `FilterControl` component:

![2020-06-03 15-24-27 2020-06-03 15_27_00](https://user-images.githubusercontent.com/2322354/83680243-b652e580-a5ae-11ea-8fed-1638fdf22d8a.gif)

**Comment by ItsJonQ** [comment]
I got the initial integration of this new experimental control with the Cover block.

![filters-demo](https://user-images.githubusercontent.com/2322354/83692175-7cd7a580-a5c1-11ea-9c0f-13afca87aa27.gif)

It works for both images **and** video!

I'll draft a PR when it's a little bit more ready.
Pretty jazzed about this 😊 

@melchoyce Is this experience inline with what you were imagining? Would love to hear your thoughts!~

Thanks all! <3

Github branch:
https://github.com/WordPress/gutenberg/tree/try/cover-background-filters

**Comment by melchoyce** [comment]
Way more than I was expecting! This is great.

I wonder if we could drop hue, because that can be controlled by the overlay color?

Also wondering if we could create a few preset filters (black and white, black and white high contrast, sepia, vivid, custom etc.) in a dropdown or something, instead of automatically showing all of these sliders at once.

**Comment by ItsJonQ** [comment]
> Way more than I was expecting! This is great.

@melchoyce Yay!! I'm glad I'm on the right track.

> I wonder if we could drop hue

You got it!

> Also wondering if we could create a few preset filters

OoOOoo. That could be interesting... A bit more complex, but might be fun :)

**Comment by ItsJonQ** [comment]
@melchoyce How's this :D

![filter-preset-demo](https://user-images.githubusercontent.com/2322354/83785117-d80ba580-a65e-11ea-9162-cb12713894d5.gif)

I added some presets inspired by iOS's camera app.

Note: I didn't add color tinted presets, as that would involve the Cover background, which (at the moment) is a separate thing.

P.S. It's really fun to use these on Cover videos 😊

**Comment by mtias** [comment]
@melchoyce should we consider this done with access to duotone grayscales or were you hoping to have controls like sliders for it?

**Comment by melchoyce** [comment]
Yeah, I think we can close this 👍
