### ISSUE TITLE
Hooks are not serialized correctly into the registerBlockType's save() function

### ISSUE THREAD

**Issue by marcofugaro** [WordPress/gutenberg#22271]
**Describe the bug**
I am currently passing a react component to the `save()` function, I am expecting for it to be serialized into the post_content and be output to the frontend. However this doesn't happen when using hooks in any part of the component.

It looks like there is an issue with the serialization of the component into html string, any idea what might cause this problem?

**To reproduce**
Steps to reproduce the behaviour:
1. Follow the [Javascript build setup official tutorial](https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/)
2. Import the component `App` in the `save()` function
```js
import { registerBlockType } from '@wordpress/blocks';
import { App } from './App';

registerBlockType( 'myguten/test-block', {
    title: 'Basic Example',
    icon: 'smiley',
    category: 'layout',
    edit: () => <div>Hola, mundo!</div>,
    save: () => <div><App/></div>,
} );
```
3. Add the file `src/App.js` with the [minimal hooks example](https://reactjs.org/docs/hooks-state.html)
```js
import { useState } from '@wordpress/element'

export function App() {
  const [count, setCount] = useState(0)

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
         Click me
       </button>
    </div>
  )
}
```
4. `npm install @wordpress/element`
5. Enqueue the scripts like explained in the [official guide](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/writing-your-first-block-type/)
5. Create a new wordpress post ad add the block
6. Hit `Preview`
7. Nothing is rendered

**Expected behavior**
The HTML markup should be rendered, it would look like this:

<img width="231" alt="Screenshot 2020-05-11 at 16 40 20" src="https://user-images.githubusercontent.com/7217420/81574904-af1d2b00-93a6-11ea-8bb0-6c4fd4908488.png">

However, it works fine if we use a "classic" state approach:

```js
import { Component } from 'react'

export class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      count: 0,
    }

    this.setCount = this.setCount.bind(this)
  }

  setCount(count) {
    this.setState({ count })
  }

  render() {
    const { count } = this.state

    return (
      <div>
        <p>You clicked {count} times</p>
        <button onClick={() => this.setCount(count + 1)}>Click me</button>
      </div>
    )
  }
}

```

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Additional context**
I am attempting to use an "Isomorphic" Gutenberg blocks approach like described in [this article](https://pantheon.io/blog/isomorphic-gutenberg-blocks)

**Comment by chrisvanpatten** [comment]
@marcofugaro I can't speak exactly to why the class approach seems to work while the hooks version doesn't, but I can point you to this bit of documentation:

> Note: The save function should be a pure function that depends only on the attributes used to invoke it.
>
> It can not have any side effect or retrieve information from another source, e.g. it is not possible to use the data module inside it select( store ).selector( ... ).
> 
> This is because if the external information changes, the block may be flagged as invalid when the post is later edited (read more about Validation).
>
> If there is a need to have other information as part of the save, developers can consider one of these two alternatives:
>
> – Use dynamic blocks and dynamically retrieve the required information on the server.
> – Store the external value as an attribute which is dynamically updated in the block’s edit function as changes occur.

([source](https://developer.wordpress.org/block-editor/developers/block-api/block-edit-save/#save))

Based on that I'm even surprised that the class component version seems to work, as I wouldn't expect it to.

You can note as well in the tutorial you linked that the [author's example](https://gist.github.com/Shelob9/102944c6e33e1038e3fa7234e89cb3c4/raw/190c09059b99e0b08c19849fe14ce5164954d027/8.js) uses attribute data to hydrate the component, not internal state.

**Comment by chrisvanpatten** [comment]
Related discussion: #16843

**Comment by marcofugaro** [comment]
Thanks for the links @chrisvanpatten!

In my use-case, I need some interactivity with react on the frontend.

Solved for now in this way
```js
save: () => <div>{ReactDOMServer.renderToString(App)}</div>,
```

**Comment by youknowriad** [comment]
Yes, the "save" function is not meant to add interactivity to the frontend. It can serve to provide a "root" element and have a script loaded in the frontend to attach React apps to that root.
