### ISSUE TITLE
Create a selector/resolver pair for user / author details

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22270]
**Is your feature request related to a problem? Please describe.**
This idea appeared in the discussion on #19894 ([comment](https://github.com/WordPress/gutenberg/pull/19894#discussion_r417367216)). 

**Describe the solution you'd like**
We should have this selector as an effort to cover all WP endpoints in `core/data`, and also because getting author details looks like a common situation. 

**Describe alternatives you've considered**
Not adding this and continue to use apiFetch.

**Comment by Mamaduka** [comment]
Hi, @draganescu

I think we can close this one. A user details can be fetched via `wp.data.select('core').getUser(userId);` selector.

The code referenced in the original comment was later updated to use this selector.

**Comment by draganescu** [comment]
🆗
