### ISSUE TITLE
Trying to push a branch to the repository and pull request  

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#22284]
I have worked on an issue and fixed it, now I want to push the branch and add a pull request, 
When I push the branch I am getting this "permission" error: 
![Screen Shot 2020-05-12 at 1 06 20 AM](https://user-images.githubusercontent.com/39377174/81624091-3c836e00-93ed-11ea-869e-26a62ecaa113.png)

**Comment by talldan** [comment]
Hey @DOUARA. Thanks for working on an issue!

Push access to the repository is restricted to members of the project. The good news is, once you've worked on a couple of merged pull requests you can request to become a member (https://github.com/WordPress/gutenberg/blob/master/docs/contributors/repository-management.md#teams). 

For now, the workflow for a new contributor is to use a github fork to contribute. The steps would be:
- Click the Fork button in the top right corner of https://github.com/WordPress/gutenberg
- Add your fork as a remote in your local git repo using `git remote add` (https://help.github.com/en/github/using-git/adding-a-remote)
- Push your branch to your fork
- Create a pull request from your fork back on this repo - https://github.com/WordPress/gutenberg/pulls

There's some more detail here:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#git-workflow

And there's some more about the workflow in some github docs:
- https://guides.github.com/activities/forking/
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests
- https://help.github.com/en/github/getting-started-with-github/fork-a-repo

I've left lots of links so hopefully that's enough to help you move forwards. Let me know if you get stuck or need any help 😄

**Comment by joshiujjawal22** [comment]
> I have worked on an issue and fixed it, now I want to push the branch and add a pull request,
> When I push the branch I am getting this "permission" error:
> ![Screen Shot 2020-05-12 at 1 06 20 AM](https://user-images.githubusercontent.com/39377174/81624091-3c836e00-93ed-11ea-869e-26a62ecaa113.png)

It seems that you have not forked this repository yet.
- First fork the repository.
- Then Clone the repository after that make the changes in your local repository first.
- Then push it into your branch.
-Then perform a pull request in github web interface.

From this link you will get more info about , `creating a pull request` 
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
