### ISSUE TITLE
How to know if an InnerBlock is selected

### ISSUE THREAD

**Issue by plagioriginal** [WordPress/gutenberg#22282]
Is there anyway I can know, on the "edit" function of the parent block, if any of it's InnerBlocks are selected? I want to add a javascript function if a InnerElement is selected.

I've searched but couldn't find anything that helped. 
Thank you for your time

**Comment by talldan** [comment]
@plagioriginal You'll need to use a selector to get that information from the store (which is like a redux store if you're familiar with that).

Some approximate code would look like this using react hooks:
```jsx
edit( { clientId, attributes } ) {
  const isParentOfSelectedBlock = useSelect( ( select ) => select( 'core/block-editor' ).hasSelectedInnerBlock( clientId, true ) ):
  // ... rest of block edit function
```

The second argument `true` defines whether a deep search is used or a shallow one (the docs are here - https://developer.wordpress.org/block-editor/data/data-core-block-editor/#hasSelectedInnerBlock).

There's a small amount of documentation on `useSelect` here:
https://github.com/WordPress/gutenberg/blob/master/packages/data/README.md#useSelect

If you're using a class component for your block's `edit` you'd want to look at `withSelect`:
https://github.com/WordPress/gutenberg/blob/master/packages/data/README.md#withSelect

**Comment by plagioriginal** [comment]
Hey @talldan ,
Thank you for your quick answer. 

It actually worked for what I asked of you in the ticket, but in the end what I wanted was to change the css class of the BlockListBlock (which is the block that "wraps" my actual block in the editor), and that was done by the following piece of code (which I was only able to get to thanks to your answer): 

`
const { createHigherOrderComponent } = wp.compose;

const addColCssClassToColBlock = createHigherOrderComponent((BlockListBlock) => {
	return (attrs) => {
		const { block } = attrs;
		const { name, attributes } = block;

		if (name === blockKey) {
			const { numberOfColumns } = attributes;

			// eslint-disable-next-line react/jsx-props-no-spreading
			return <BlockListBlock {...attrs} className={`col col--${numberOfColumns}-cells`} />;
		}

		// eslint-disable-next-line react/jsx-props-no-spreading
		return <BlockListBlock {...attrs} />;
	};
}, 'addColCssClassToColBlock');

wp.hooks.addFilter(
	'editor.BlockListBlock',
	'custom-blocks/col-class-name',
	addColCssClassToColBlock,
);`

I know that this is "unrelated" to the initial ticket, but I'm leaving it here in case anyone comes by the same problem. 

Thanks again!
