### ISSUE TITLE
HTML block with no closed tag, in this blockquote end it automatically. And I do not want to.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#22299]
**Describe the bug**
Hi, because I can't add a « Reusable block » directly in « HTML block » or in « Blockquote », I use a trick, who is to create an HTML block with a starting &lt;blockquote&gt; tag before the Reusable or any block, and an other HTML block with &lt;/blockquote&gt; tag after that / these block’s.
But since few week, I noticed that after saving, reopening and saving again, the first HTML block, add at end of the code &lt;/ blockquote&gt;, and suppress the next in the second HTML block.
I don't want this to happen ! My HTML code should not be modified by automatic bot.

**To reproduce**
1. Go to 'editor"
2. Click on +, then create one HTML block, one block, then an HTML block, in the first use &lt;blockquote&gt;, in the last &lt;/blockquote&gt;, write something in second, then save, view the post, edit it again, normally in my case, the second HTML block will get is &lt;/blockquote&gt; erased, and added in the first one.

**Expected behaviour**
This auto‑closing & removal tag should not happen. Like before few weeks !

**Screenshots**
First edit :
<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_Git-Hub_Issues_shared-pictures/master/VorzPremsh/issues/bug/2020%E2%80%9105%E2%80%9112_-_19H20_-_WordPress_auto-closing_remove_tag_bug_1.JPG">

Saved, viewed, reopened to edit, tag changed automatically without consent :
<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_Git-Hub_Issues_shared-pictures/master/VorzPremsh/issues/bug/2020%E2%80%9105%E2%80%9112_-_19H20_-_WordPress_auto-closing_remove_tag_bug_2.JPG">

**Editor version (please complete the following information):**
- WordPress version: blog on wordpress.com

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FireFox 75

**Comment by talldan** [comment]
Noting that this was previously reported in #15794, so I'll close this issue.

There's an explanation of what's happening on that issue:
https://github.com/WordPress/gutenberg/issues/15794#issuecomment-595054330

**Comment by Nemzag** [comment]
Nothing, koon for you all.
