### ISSUE TITLE
env: Using Zip file URLs for plugins prevents their assets from being served

### ISSUE THREAD

**Issue by loranallensmith** [WordPress/gutenberg#22301]
**Describe the bug**
When I use `.zip` file URLs from WordPress.org for plugins in the `.wp-env.json` file, the mounted directory name contains characters that prevent WordPress from accessing the plugin's static assets.

**To reproduce**
1. Create a new blank project with a `.wp-env.json` file
2. Add `https://downloads.wordpress.org/plugin/woocommerce.4.1.0.zip` as a plugin dependency for the environment
3. Run `wp-env start`
4. Log in and browse to `http://localhost:8888/wp-admin/index.php?page=wc-setup`
5. The browser's dev tools show the requests for scripts and styles return a 404 response.

**Expected behavior**
I expected the browser to be able to access these assets the way it accesses the core static assets. 

**Screenshots**
<img width="1680" alt="Screen Shot 2020-05-12 at 10 04 00 AM" src="https://user-images.githubusercontent.com/3477155/81739899-236cd280-946a-11ea-8b80-675e6aead82c.png">
![Screen Shot 2020-05-12 at 4 11 49 PM](https://user-images.githubusercontent.com/3477155/81741805-1a313500-946d-11ea-94d2-b6d99a9500ec.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default (I think)
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Browser Firefox
 - Version 76.0.1 (64-bit)

**Additional context**
- I _think_ this might stem from the characters in the name of the mounted plugin directory.  If I download and unzip the file myself, I can specify the local path to the resulting folder,  and `wp-env` works as expected.
- Based on some cursory testing, it looks like the characters don't pose a problem locally; it's only when they're used as part of the virtual directory name on the container that they cause issues.

**Comment by noahtallen** [comment]
> I think this might stem from the characters in the name of the mounted plugin directory

I think this would solve it. For deps downloaded from an official source like this one, we should try to use the actual slug as the thing we map instead of a weird dirname
