### ISSUE TITLE
Spotify Embed Failures for Playlists

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#22302]
**Describe the bug**
Trying to embed a playlist in the Spotify embed block does not seem to work:

![Screen Shot 2020-05-12 at 1 55 18 PM](https://user-images.githubusercontent.com/28742426/81745624-215b4180-9473-11ea-8f8e-27a8a49498ee.png)

However, song and album imbeds continue to work as expected.

There have been a handful of reports noted from dotcom in the last few days regarding this.  I am also reproducing this error with my local Gutenberg docker environment on the current master branch.

There seem to have been some other intermittent Spotify embed issues in the recent past (#19604), but this specific outage for playlists specifically seems to be new.

**To reproduce**
1. Insert a Spotify embed block
2. Try to embed a playlist such as - `https://open.spotify.com/playlist/37i9dQZF1E4yfsPkqIMfve?si=8FODsM8nTFaQUKWmsuyHbA`
3. Verify it does not embed.

**Expected behavior**
The playlist to be embedded similarly as an album.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]
Reproduced with Gutenberg 8.0.0, 8.1.0-rc.1, and default/disabled.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.30
 - Browser: Chrome
 - Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by sirreal** [comment]
I believe this may be a problem on Spotify's end.

It was raised on a Spotify forum: https://community.spotify.com/t5/Spotify-for-Developers/Playlist-oembed-down-or-changed/m-p/4949867/highlight/true#M99 and I've commented there.

I've also reached out on Twitter: https://twitter.com/jonsurrell/status/1260608420396306432

Songs work fine: https://open.spotify.com/oembed?url=https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC?si=MKLA7hRCTTuhyiXhuqvXeA 

Artists work fine: https://open.spotify.com/oembed?url=https://open.spotify.com/artist/6ykfXAed2KOLOMI3R0TZdz?si=K4zmepbrSB6lH9elPxN9tg 

Playlists don't: https://open.spotify.com/oembed?url=https://open.spotify.com/playlist/37i9dQZF1DX1S1NduGwpsa?si=NFpoIkVtQMWYDlM-HGMPHg

**Comment by tbradsha** [comment]
Note that the `[spotify]` Jetpack shortcode seems to embed Spotify playlists successfully despite the Spotify embed block not working.

**Comment by sirreal** [comment]
> Note that the `[spotify]` Jetpack shortcode seems to embed Spotify playlists successfully despite the Spotify embed block not working.

Thanks 👍

Jetpack doesn't rely on oembed, but [builds its own `iframe` source](https://github.com/Automattic/jetpack/blob/1eb2865c66639a7c8a1f91834a052c06c5e1685e/modules/shortcodes/spotify.php#L56). It does demonstrate that playlists _should_ be embeddable.

**Comment by earnjam** [comment]
The code for handling oEmbed functionality is in core, so this would be better reported on Trac. There was a ticket opened there 8 days ago: https://core.trac.wordpress.org/ticket/50116

Unfortunately this is a problem on Spotify's end with their oEmbed endpoint, and not something we can really do anything about until/unless they fix it upstream. I'm going to close this since we're already tracking it on Trac and there aren't any actionable steps we can take here.
