### ISSUE TITLE
Limit Styles Placeholder Height

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#22315]
**Describe the bug**
If someone has a really long content for a block which has styles, the style area gets too messy. 

![Image 2020-05-13 at 2 51 36 PM](https://user-images.githubusercontent.com/5817882/81798256-43af9680-9529-11ea-9be3-d723a351c494.png)

The above example is for the styles of my [Gutenberg Forms](https://github.com/munirkamal/gutenberg-forms/issues/138) plugin. However, this may be issue for any other blocks which may have longer content.

Maybe we need to apply a max height for the style placeholders?

Thanks

**Comment by munirkamal** [comment]
Done.

And fixed the issue as well. ;)

**Comment by karmatosed** [comment]
@munirkamal I think you are saying this is now resolved? If that's case I am going to close this for now. If not, we can always reopen.
