### ISSUE TITLE
FSE: Featured image block is available when theme support is not declared.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22313]
**Describe the bug**
When full site editing is enabled, the featured image block can be selected in the list of available blocks, even if the theme does not add the theme support for featured image.
And without the theme support, there is no input field for adding a featured image.

I am not sure what the plan is, but these things could be considered:

1. - To make the featured image available for themes by default, without theme support.
2. - Let themes declare support via the global styles JSON settings file.
3. - Continue to require theme support by using a functions.php file

-Use the existing input field for featured images
-Use the same input as an image block

**To reproduce**
1. Enable full site editing
2. Create a new post or page
3. Choose to add a new block and search for the featured image.
4. successfully add the (blank) block.

**Expected behavior**
There are several options, but with the block available, I expect to be able to also add an image.
I would not mind if the featured image was enabled by default. 

**Editor version**
WordPress version: 5.4.1
Gutenberg: Master, latest commit was: 754c472

**Desktop**
Windows 10
Chrome version: 81.0.4044.138

**Comment by aristath** [comment]
Do we even want to keep the featured-image support for FSE themes? Does it make sense to keep it?
Non-FSE themes had to define the theme-support because they were adding the feature image usually without any user interaction. With FSE and users being able to just add the block in their templates I don't think it would make a lot of sense to keep around the theme-support :thinking:

**Comment by carolinan** [comment]
The reason why this was a problem was that without the theme support, there was no way to add a featured image.
Now the block itself has the image upload and image selection capability and this issue can be closed.
