### ISSUE TITLE
Featured image outline crashes into Set featured image text

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2232]
Featured image outline crashes into Set featured image text.
0.7 version. Using Twenty Seventeen. Local setup in Desktop Server. In Chrome.

![screen shot 2017-08-04 at 23 32 19](https://user-images.githubusercontent.com/5323259/28987858-6c306b1e-796d-11e7-9f1d-692afd68cca8.png)

**Comment by aduth** [comment]
Previously:

- https://github.com/WordPress/gutenberg/pull/1337#issuecomment-310687847
- https://github.com/WordPress/gutenberg/pull/1337#issuecomment-318464305
