### ISSUE TITLE
Add new category option

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2233]
0.7 version. Using Twenty Seventeen. Local setup in Desktop Server. In Chrome.

Right now I can not see a way to add a new Category.

Here is what it looks like in Gutenberg right now.
![screen shot 2017-08-04 at 23 53 58](https://user-images.githubusercontent.com/5323259/28988497-5a3758d4-7970-11e7-9a91-654fcf2a3891.png)

Here is what is looks like in WordPress today.
A few more options in place.

![screen shot 2017-08-04 at 23 54 39](https://user-images.githubusercontent.com/5323259/28988512-6d768082-7970-11e7-9158-afcdc1951866.png)

There are a few issues in regards to Category but I did not notice one that brought up this issue.

**Comment by karmatosed** [comment]
Currently there is no ability to add a category. I changed this to be more about adding in that functionality.
