### ISSUE TITLE
Media library shows "No items found" when creating a new gallery

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#22338]
**Describe the bug**
When I create a new page and add a gallery block, no media items are available for me to select. If I try to edit that new gallery, all items in my media library are already selected.

**To reproduce**
1. Add new page.
2. Insert gallery block.
3. Click "Media library"
4. See "No items found" in "Add to Gallery" section.
5. Click "Edit gallery"
6. See all items selected.

**Expected behavior**
* I would expect the images from the media library to be available for selection in the "Add to Gallery" area.
* I would expect only previously selected images to be selected in the "Edit gallery" area.

**Screenshots**
![empty-media-library-gallery](https://user-images.githubusercontent.com/286171/81878350-a65e5d80-953c-11ea-88fc-1afbaf284526.gif)

**Editor version:**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.1.0

**Desktop:**
 - OS: MacOS 10.14.6
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
* If I deactivate the Gutenberg plugin or downgrade the plugin to 8.0.0, the gallery works as expected.
* The `admin-ajax.php` call made by the media library returns some set of objects on that initial load. I did not dig into why they did not appear.
* During a couple attempts, I would briefly see a flash of the available media before it disappeared and "No items found" was displayed.

**Comment by cngodles** [comment]
This has happened to me today. What is happening is it's adding every single piece of media from your site to the gallery, thus there is nothing new to add. If you click Edit gallery, they are all selected in there.

**Comment by GlennMartin1** [comment]
Same here; I cannot create a new gallery :-(

**Comment by kristarella** [comment]
I have tested on several sites and can confirm.

**Comment by roo2** [comment]
Just adding, I can only reproduce this if I access the gutenberg editor directly via `wp-admin`, if I access the wrapped version on wp.com it uses the different media picker which doesn't have the issue. 
![upload to gallery](https://user-images.githubusercontent.com/22446385/82977081-264bf380-a024-11ea-9767-f2848f03db77.gif)

**Comment by cngodles** [comment]
This is still an issue for me. When I try to add a new gallery, it loads images for a second or two, and then it goes away. Upon inspection, the entire media library seems to be loaded into the gallery.

Running WP 5.4.1 and Gutenberg 8.2.0
Cleared cache and tested on both Firefox and Chrome latest. Windows latest.

![image](https://user-images.githubusercontent.com/5685764/83153831-66b37c00-a0cd-11ea-9c8a-433cf12426cc.png)


![wp-gallery](https://user-images.githubusercontent.com/5685764/83153453-f60c5f80-a0cc-11ea-9773-5d6d93ccc42a.gif)

**Comment by jeremyfelt** [comment]
@cngodles This has been merged for the upcoming 8.3.0 release. We should see the results soon!

**Comment by GlennMartin1** [comment]
@youknowriad  any possibility of an 8.2.1 to address this?
https://wordpress.slack.com/archives/C02QB2JS7/p1590658332400100

**Comment by youknowriad** [comment]
@GlennMartin1 yes, I'm releasing it right now.

**Comment by fazliddin** [comment]
Us usual solution is to disable all plugins. It took me a day to find the problem. It turns out PolyLab plugin separates images by language. So if all images are uploaded in English, they will not be shown in French.

Solution is to go to PolyLang settings and turn off media library support.
