### ISSUE TITLE
Table of Contents is missing

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2234]
Version 0.7

## Issue Overview
The table of contents is no longer being displayed in the sidebar. Since this wasn't mentioned in the [0.7 release notes](https://make.wordpress.org/core/2017/08/04/whats-new-in-gutenberg-4th-august/), I can only assume it is a bug in this release.

**Comment by StaggerLeee** [comment]
I see it in 0.7.1. In Demo, new Posts of course have no H tags yet.

**Comment by mtias** [comment]
@aaronjorbin it should appear if you have at least two headings in your content.

**Comment by afercia** [comment]
FWIW I'd be in favor of making it appear when there's at least 1 heading. Say users insert just one heading and its level is wrong (for example an h4): Gutenberg should display the TOC and warn about the incorrect hierarchy.

**Comment by karmatosed** [comment]
Can we get a fix in for this by making it appear if there is just one heading?
