### ISSUE TITLE
Deleted menus reappear when switching to Menu Locations tab and back again

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#22340]
**Describe the bug**
On the experimental navigation menu page, deleted menus reappear when switching to Menu Locations tab and back again.

**To reproduce**
1. Add some menus
2. Delete one
3. Select 'Menu Locations'
4. Go back to 'Edit Navigation'
5. Note that the deleted menu is back in the Select Navigation menu.

**Expected behavior**
The deleted menu doesn't reappear

**Comment by talldan** [comment]
I believe this is because the `stateMenus` react state is reset when the component is unmounted and remounted:
https://github.com/WordPress/gutenberg/blob/master/packages/edit-navigation/src/components/menus-editor/index.js#L18

**Comment by draganescu** [comment]
I thought I solved that :D Will take a look!

**Comment by draganescu** [comment]
The real problem is
```
const menus = useSelect( ( select ) => select( 'core' ).getMenus() );
```
this should know we deleted something and get a fresh copy ✅ 

It doesn't so we'll probably, for now, need to move the state out of the `menusEditor` component.

**Comment by talldan** [comment]
I also thought it might be good if instead of creating `stateMenus` that has the filtered out deleted menus, to instead retain a list of `deletedMenus` that can be used to filter out the menus.

At the moment it feels a little fragile as it relies on `menus` not repopulating.

The psuedocode would be something like:
```jsx
const menus = useSelect( ( select ) => omit( select( 'core' ).getMenus(), deletedMenus ), [ deletedMenus ] );
```

**Comment by draganescu** [comment]
🍾 @talldan I think your idea might work for #21282 as well!

**Comment by adamziel** [comment]
It's a good workaround for the purposes of thid experiment. In the longer run we should be addressing the root cause of the issue as in why are these items not getting removed from the store?

**Comment by talldan** [comment]
#22625 looks like the same sort of issue, but relates to menu selection.

**Comment by noisysocks** [comment]
What's the status of this?

> It's a good workaround for the purposes of this experiment. In the longer run we should be addressing the root cause of the issue as in why are these items not getting removed from the store?

Agreed.

**Comment by draganescu** [comment]
I don't think this happens anymore since merging #22428. I tested and it worked. Can anyone else confirm?

**Comment by noisysocks** [comment]
I wasn't able to reproduce it either.
