### ISSUE TITLE
Reducing window size while focusing block causes react error 185.

### ISSUE THREAD

**Issue by George-Grainger** [WordPress/gutenberg#22358]
**Describe the bug**
After updating to Gutenberg 8.1.0 when I click on a block then reduce the browser's width it causes  react error - [Minified React error #185](https://reactjs.org/docs/error-decoder.html?invariant=185).

This only appears to occur if you reduce the browser width while clicking on a block in my experience occurs  at the point of the block overlapping the edge of the window.

**To reproduce**
1. Go to the gutenberg demo page
2. Click on the first image
3. Reduce the width of your browser as far as possible

**Expected behavior**
In Gutenberg 8.0.0 the block just continued to resize.

**Screenshots**
Click on the top image block
![Resize Bug Img 1](https://user-images.githubusercontent.com/65354477/81953691-e5091c00-95ff-11ea-88eb-78c64f810e7c.png)

Shrink window from the right
![Resize Bug Img 2](https://user-images.githubusercontent.com/65354477/81953707-e9353980-95ff-11ea-9a61-33118204ae4e.png)

Logs
![Resize Bug logs](https://user-images.githubusercontent.com/65354477/81953803-023dea80-9600-11ea-87c0-3c4e57d1f7c2.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- gutenberg plugin
-  8.1.0

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome & Safari 
 - Version: 81 & 76 (respectively)

**Comment by karmatosed** [comment]
@George-Grainger oh that's a fun bug! I can also replicate:

![image](https://user-images.githubusercontent.com/253067/82056180-7ab4b200-96b9-11ea-947b-c50b4206799f.png)

**Comment by talldan** [comment]
Seems somewhat similar to https://github.com/WordPress/gutenberg/issues/22258, though I note it's a different error message, so it might be a different bug.

**Comment by George-Grainger** [comment]
Appears to have been fixed in 8.2.0
