### ISSUE TITLE
Detecting pages/posts authored via Gutenberg

### ISSUE THREAD

**Issue by WPDevHQ** [WordPress/gutenberg#2235]
Is there a way to detect if a page/post is authored via Gutenberg?

Styling older themes when the editor is finally release may prove to be a little bit of a nighmare for some authors. Perhaps a body class of gutenberg could be filtered in?

Right now I've had to create a custom template in order to allow for alignwide/alignfull to take up the full defined width instead of being contrained in the predefined content area width!
`

**Comment by westonruter** [comment]
There is a a `gutenberg_post_has_blocks` function proposed in #1797 which could be used in a theme to add a body class, and even without it you could do it manually in a theme via:

```php
function mytheme_add_gutenberg_body_class( $body_classes ) {
	if ( is_singular() && false !== strpos( get_queried_object()->post_content, '<!-- wp:' ) ) {
		$body_classes[] = 'gutenberg';
	}
	return $body_classes;
}
add_filter( 'body_class', 'mytheme_add_gutenberg_body_class' );
```

**Comment by WPDevHQ** [comment]
That worked perfectly, thank you @westonruter

**Comment by paaljoachim** [comment]
That is a very good idea Zulfikar.
Having an auto detect if a post/page is created in Gutenberg or the standard editor and giving a message or auto direct to open in the editor it has been created in seems like a very good idea.

**Comment by karmatosed** [comment]
As the solution for a theme has been given, I think for now closing this. I'm not sure the core Gutenberg needs to display a message at this point.
