### ISSUE TITLE
Border radius 0 in button block not working

### ISSUE THREAD

**Issue by hazuremon** [WordPress/gutenberg#22367]
**Describe the bug**
In the latest version, the button block is not able to set a square/rectanlge button, when border radius is set as 0, it results in a round corner instead of square/rectangle.

Previously, it will apply .no-border-radius class to button where it applies a border-radius: 0 css style, but the current version does not apply such CSS.

**To reproduce**
1. Add new button block
2. Change border settings, border radius to 0
3. Expect to see square/rectangle button

**Expected behavior**
When border-radius set as 0, expect to see a square/rectangle button instead of round corners.

**Screenshots**
<img width="949" alt="Screen Shot 2020-05-14 at 1 46 53 PM" src="https://user-images.githubusercontent.com/1413953/81984633-f21b1080-95e9-11ea-8f77-0e5f801a69cb.png">
Captured from https://wordpress.org/gutenberg/

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default wordpress, no gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] All browsers

**Comment by karmatosed** [comment]
I can confirm in testing this is an issue.

![image](https://user-images.githubusercontent.com/253067/82055697-ce72cb80-96b8-11ea-909b-9e78ddf0d6e3.png)

I see still a very small border radius myself with it set to 0.
