### ISSUE TITLE
Easier way to select columns

### ISSUE THREAD

**Issue by heylouise** [WordPress/gutenberg#22371]
Hi. My clients and I are doing a lot of work on sites with column layouts. I don't like that it's not easy to select a block of columns by clicking on it. (Usually clicking on the columns selects the nested block within.) I find it's down to guessing/luck to click on the right pixel that selects the columns section.

I would like an easy way to see that I am, and have, selected the columns (not the blocks within). Perhaps by a button when you nave a nested block selected, or a designated space/line/button you can click on to the left of the columns sections.

I know that it's possible to select the columns with the block editor, but that doesn't seem intuitive for my clients. I've shown them that they can type/move/manipulate blocks by clicking on them. Why not for columns?

Thank you for hearing my request. :)

**Comment by karmatosed** [comment]
Hi @heylouise this sounds interesting. I notice there has been a linked issue of exploring into how to work within child blocks. Similar iterations could happen in this too. I've put the design feedback label on to see about getting some thoughts here for you.

**Comment by shaunandrews** [comment]
@heylouise We've recently merged a new button that will appear when you hover over the block icon it the toolbar:

![](https://user-images.githubusercontent.com/191598/77200050-3691a080-6ac0-11ea-8d2b-ec657408c76f.gif)

When clicked, this button will select the current block's parent. This should hopefully make it easier to select the Column while working with any blocks it contains.

I'm going to close this issue, but feel free to comment or re-open if you have more thoughts. Thanks!
