### ISSUE TITLE
Editor crash on hover over block style

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22375]
**Describe the bug**
When hovering over block style in navigation 

**To reproduce**
1. Open a post
2. Add a navigation block
3. Select the block from the navigator
4. Click on the style selector in the block toolbar
5. Hover over the default style
6. Crash boom bang

**Expected behavior**
I expect to see the preview of the style.

**Screenshots**
![image](https://user-images.githubusercontent.com/107534/82019784-80e26880-9690-11ea-8af5-f34194cbf212.png)

**Editor version (please complete the following information):**
Current master: latest commit 7427369 .
FF and Chrome.

**Comment by talldan** [comment]
`TypeError: hoveredBlockType is null` is the error, seems to be happening in the `BlockSwitcher` component in the `Dropdown` component

**Comment by tellthemachines** [comment]
Removing the navigation block label because I can reproduce this in other blocks with style previews.

**Comment by tellthemachines** [comment]
Update: this was caused by #22266
