### ISSUE TITLE
Wrong style selected in block toolbar style selector

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22376]
**Describe the bug**
After applying a style, the currently applied style is selected in the inspector but not in the block toolbar style selector.

**To reproduce**
1. Open a post
2. Add a navigation block
3. Click on the block style selector in the block toolbar
4. Change style to "dark"
5. Deselect and reselect the block
6. Observe that in the inspector the selected style variation is dark but in the block syle selector toolbar menu the default "light" style is still selected.

**Expected behavior**
The currently active style to be selected.

**Screenshots**
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/107534/82020136-40371f00-9691-11ea-8e98-c3751c6c6953.png">

**Comment by talldan** [comment]
The blue outline is the focus ring. The black outline indicates the selected style. I realise that can be confusing, but the focus ring is required for accessibility reasons.

FWIW, it doesn't happen any longer because the transform menu is now before the styles menu.
