### ISSUE TITLE
Button renders invisible ")," in editor

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#2237]
There's a string ")," below the button, not sure where it's coming from.

http://i.imgur.com/nGRe8xO.png

It becomes visible when changing text color.

http://i.imgur.com/Yt6kwkq.png

Anyone else got it?

**Comment by StaggerLeee** [comment]
To hijack issue a bit.
Button goes over trash icon when button text is to long.

**Comment by swissspidy** [comment]
@StaggerLeee Can you create a separate issue for this? These are two very different things and I'm sure we don't want to miss such little bugs buried in some comment. Thanks!

**Comment by StaggerLeee** [comment]
https://github.com/WordPress/gutenberg/issues/2249

**Comment by iseulde** [comment]
Fixed in #2250.
