### ISSUE TITLE
Scripts: Upgrade ESLint to the new major version (7.x)

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#22385]
## Description

ESLint `v7.0.0` was released:

https://eslint.org/blog/2020/05/eslint-v7.0.0-released

We should update our packages to use the latest version. It has a few breaking changes as highlighted here:
https://eslint.org/blog/2020/05/eslint-v7.0.0-released#breaking-changes

One of the issues resolved (https://github.com/eslint/eslint/issues/11558) allows us to remove the following workaround added in https://github.com/WordPress/gutenberg/pull/17744:
https://github.com/WordPress/gutenberg/blob/605cb2bc2fd5906cec72c9ae357f5b3c6f0e00c5/packages/scripts/config/.eslintrc.js#L6-L10

## References

It might be helpful to look at previous PR where minor version upgrade for ESLint was applied: https://github.com/WordPress/gutenberg/pull/21424. The changes included:
- upgrade of ESLint package to the latest version
- bringing all ESLint plugins and configs used to the latest version
- listing all changes applied in the relevant changelog files
- fixing any new errors that might pop up

**Comment by aduth** [comment]
Somewhat related: https://github.com/WordPress/gutenberg/pull/16795#issuecomment-626978276

**Comment by ocean90** [comment]
@gziolo In #22771 I have started with the upgrade. We may have to wait for two dependencies getting their update to avoid the warning.

There are [some new JS lint errors](https://github.com/WordPress/gutenberg/pull/22771#issuecomment-636360580) which seem to be valid. Can you confirm that they are correct and should be fixed? I suppose a separate PR is preferred?

**Comment by gziolo** [comment]
> There are [some new JS lint errors](https://github.com/WordPress/gutenberg/pull/22771#issuecomment-636360580) which seem to be valid. Can you confirm that they are correct and should be fixed? I suppose a separate PR is preferred?

@ocean90, thank you for starting this PR. I left my detailed comment there. I think those are valid issues that need to be addressed and we definitely need to split into more PRs. How we proceed, it's up for debate :)
