### ISSUE TITLE
Allow columns to be moved left/right of next/previous column

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#22382]
**Is your feature request related to a problem? Please describe.**
If you are using the columns block there isn't a way to easily move a column to the left/right of the next/previous column, this means if you want to do this you need to create a new column and paste the column content then remove the old column content.

**Describe the solution you'd like**
Left/right button in the column toolbar to move the current column selected to the left/right of the next/previous column.

**Describe alternatives you've considered**
Copy and pasting of column content as described above.

**Comment by youknowriad** [comment]
Hi There! 

If you're using the Gutenberg plugin, this is already possible by selecting the "column" (singular) block.

Thanks.

**Comment by ninetyninew** [comment]
@youknowriad ahh, apologies - I am solely using WP core. Cool! Is it likely that particular functionality will be in the next core release?

**Comment by youknowriad** [comment]
@ninetyninew yes, in WordPress 5.5
