### ISSUE TITLE
Drop Cap Disappears

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2238]
## Issue Overview
I edited a newly created page in Gutenberg and added the first Paragraph. I then turned on Drop Caps and the first letter in the paragraph turned into a Drop Cap, as expected.

I previewed the page to confirm that it actually appeared as a Drop Cap on the front end, and that worked fine.

I then went back to the editor and added another paragraph, and then after clicking in the first paragraph again, the Drop Cap disappeared.

If I view the Text version of the page, I can see that the paragraph still has the class `has-drop-cap` but it doesn't display in the editor.

Sometimes when I switch from Visual to Text and back to Visual again, the Drop Cap appears, and sometimes it doesn't. When it does appear again, clicking on the paragraph again makes it disappear.

## Steps to Reproduce (for bugs)

1. Add paragraph text
2. Turn on Drop Cap
3. Add new Paragraph
4. Click back on first paragraph and see the Drop Cap disappear

## Expected Behaviour
Drop Cap should remain visible in editor, just like it does when you first turn it on.

## Current Behaviour
Drop Cap disappears from paragraph text

Using **Version 0.7.1** of Gutenberg plugin

**Comment by mtias** [comment]
@maddisondesigns the visual drop-cap is not displayed when the block is focused in the eiditor, as editing the text with the drop-cap visible is significantly buggy in browsers.

**Comment by maddisondesigns** [comment]
@mtias That's fair enough, but it still doesn't return when you stop editing that block (i.e. Click on another block)

**Comment by karmatosed** [comment]
Are you still getting this issue? I am currently unable to recreate @maddisondesigns. As this is the case, going to cautiously close - we can always reopen.

**Comment by maddisondesigns** [comment]
@karmatosed It seems to be working ok now for me as well. Thanks.

**Comment by dinhkhanh** [comment]
Whole paragraph which has drop cap turned on will be delete when press Delete key on Mac.

**Step to reprocedure**

1. Write a paragraph
2. Turn on Drop Cap
3. Keep writing 
4. Pres Delete key on Macbook keyboard
5. Whole paragraph is disappeared
