### ISSUE TITLE
New feature: Using Block Guide Outlines to get a different view of the page layout.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#22383]
**Is your feature request related to a problem? Please describe.**
In the new G2 interface it is harder to figure out the outlines of the various blocks.
It was easier before G2 as the outlines were visible when a block was selected.
(One can go to Tools (top toolbar) then select the Select icon and see the selected block outline.)

![Screen Shot 2020-05-15 at 15 07 28](https://user-images.githubusercontent.com/5323259/82053542-cff2c280-96bd-11ea-988d-d9b74afb7644.png)

**Describe the solution you'd like**
The more complex layouts get for instance using columns, groups and other blocks it would be very useful to be able to turn on a general outline of all the blocks on the page. Similar to how EditorsKit uses the "Block Guide Lines".

![Screen Shot 2020-05-15 at 15 09 55](https://user-images.githubusercontent.com/5323259/82053784-3081ff80-96be-11ea-8483-3ef87bb45f24.png)

I made a wireframe for how this could be added to Gutenberg. The one downside I see is that this View area can be crowded.

![Block-overview](https://user-images.githubusercontent.com/5323259/82055994-94f28e00-96c1-11ea-8a11-53914795170d.jpg)

**Comment by richtabor** [comment]
It would be interesting if it could be provoked via holding down a key or something - instead of a view you have to keep toggling on/off. Seems more of an "in the moment" thing.

**Comment by richtabor** [comment]
The real problem to solve here (and something we should stay focused on in regards to this issue) is that it is very difficult to select parent blocks.

**Comment by paaljoachim** [comment]
Here is a link to discussion during the [Gutenberg Design Triage](https://wordpress.slack.com/archives/C02S78ZAL/p1590510681080900).

**Comment by ZebulanStanphill** [comment]
> The real problem to solve here (and something we should stay focused on in regards to this issue) is that it is very difficult to select parent blocks.

Potential solutions to that particular problem:

- Button to select parent from current block: #21056
- Persistent block navigator: #22113
- Improvements to the Select tool: #22508, #22614

It's worth noting that #22508 in particular is very similar to the ideas proposed by this issue.

**Comment by youknowriad** [comment]
Since this issue was opened, we made a lot of improvements to ease selecting parent blocks (parent block selector, list view, breadcrumbs....).

I think we can close this issue now and we can reopen if we have new concrete proposals.
