### ISSUE TITLE
Plugin needs menu option to add New Page

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2239]
## Issue Overview
At the moment, the Gutenberg plugin provides the option to add a _New Post_. It doesn't provide the option to add a _New Page_ though, even though you can edit a page in Gutenberg.

## Expected Behavior
I should be able to add a new Page.

## Current Behavior
I have to add a new Page using the existing _Pages > Add New_ menu option. I then have to save as draft, browse browse back to the Dashboard and then re-edit the page using Gutenberg.

## Possible Solution
Simply add a _New Page_ option to the Gutenberg menu.

Plugin **Version 0.7.1**

**Comment by karmatosed** [comment]
I agree being explicit and adding 'new page' could be good for users.

**Comment by grantpalin** [comment]
I'd like to take this one on.

**Comment by karmatosed** [comment]
That's great @grantpalin, look forward to your pull request!

**Comment by grantpalin** [comment]
Added a PR. A couple of issues I have with it:

* Both subitems are bolded when one is active: ![image](https://user-images.githubusercontent.com/183909/31108546-dab10642-a7ae-11e7-95e7-0033b9a6325f.png)
I suspect that I need to distinguish the `menu-slug` attribute on the `add_submenu_page` calls, but trying that yields: 
![image](https://user-images.githubusercontent.com/183909/31108624-52c6ed9a-a7af-11e7-9b81-5af7bdc345b6.png) And in both cases the entry is saved as a post.
* Ensuring that Gutenberg knows it is doing a page and not a post - haven't yet found out how

**Comment by amarpathak** [comment]
I am New to Open Source Contribution world, can I contribute on this issue ?
I'd Like to take this issue.

**Comment by pento** [comment]
With bdf94e6 landing, we don't need this menu item anymore.

**Comment by maddisondesigns** [comment]
@pento Is this forcing Gutenberg to be the default editor when you click the _Add New_ button on the Posts and Page screens? I really hope that's not the case. The Gutenberg plugin shouldn't be making itself the default editor. It's a plugin for a reason and shouldn't be changing the default editing experience. If this is the case, is there a Github issue you can link to that is discussing this?

**Comment by grantpalin** [comment]
@maddisondesigns Discussed on https://github.com/WordPress/gutenberg/issues/2824
