### ISSUE TITLE
RichText component in InspectorControls closes Block panel when clicked

### ISSUE THREAD

**Issue by myleshyson** [WordPress/gutenberg#22392]
Arlight so here's the situation. We developed a block a while ago that includes a TextArea component in both the inspector and the editor (bosses wanted it that way) which worked great. Recently, we were asked to convert that TextArea component into a RichText component so that editors could add formatting to that section of the block. Switching over the TextArea component in the editor was easy enough, however I started running into issues trying to switch the the InspectorControls TextArea component over to RichText. Whenever I click on the the RichText Comopnent in the Inspector, it closes the block panel and switches me over to the Document panel. 

I realize that RichText component wasn't necessarily built for the inspector, but given that we don't really have a choice here (we can't take away an established ability to edit in both places) is there a way to keep this from happening? 

Using core Gutenberg WordPress 5.3.
Firefox: 77.0b6 (64-bit)

Here's a gif of what I'm running into.

![May-15-2020 15-38-55](https://user-images.githubusercontent.com/11747187/82089758-3ed21a80-96c2-11ea-9f98-d314bb61443f.gif)

**Comment by myleshyson** [comment]
Just to update on this, This isn't an issue with the most recent Gutenberg version, but is an issue on whatever version 5.3 and 5.4 is using.

**Comment by talldan** [comment]
@myleshyson Ah, so it's resolved?

Unfortunately the fix probably won't make it into 5.4 (unless there's a future minor release). 5.5 around July/August will be the next release into core:
https://make.wordpress.org/core/5-5/
