### ISSUE TITLE
Correct packages version numbers in Core release

### ISSUE THREAD

**Issue by iruzevic** [WordPress/gutenberg#22409]
I'm building the storybook for my project blocks was able to create complete Block editor outside of the WordPress environment. 
Every-time I update packages to the latest versions I usually get some kind of errors and fatal bugs that break stuff.

In the previous versions of WP Core you could get a exact version of the packages that were used to build the specific core release.

From a few releases ago this was changed and I can no longer find this inside the core.

Is there a way to find out the exact version of Npm packages that were used to build the last WP core release?

Here is a link to this storybook
https://infinum.github.io/eightshift-docs/storybook

**Comment by youknowriad** [comment]
Hi there! you should be able to check the packge.json file of the desired WP release to get the right versions. Example here https://github.com/WordPress/wordpress-develop/blob/5.4.1/package.json#L74-L121

**Comment by iruzevic** [comment]
@youknowriad Awesome you saved me, tnx so much
