### ISSUE TITLE
Gallery block in Gutenberg 8.1.0 selects all media library images by default

### ISSUE THREAD

**Issue by designbuildtest** [WordPress/gutenberg#22403]
**Describe the bug**
When I attempt to insert a new Gallery block, the default Editor behavior is to auto-select every image from my Media Library.

**To reproduce**
1. Add a Gallery block
2. Select Media Library

**Expected behavior**
No images are selected by default.

**Editor version**
- WordPress 5.4.1
- Gutenberg plugin installed
- Gutenberg 8.1.0

**Desktop**
 - MacOS High Sierra
 - Tested with Chrome, Firefox & Safari browsers

**Smartphone**
 - Untested

**Comment by talldan** [comment]
Looks like this was reported as part of issue #22338, so I'll close this as a duplicate.
