### ISSUE TITLE
Block: Cover Image Classes Not Applied On Frontend

### ISSUE THREAD

**Issue by WPDevHQ** [WordPress/gutenberg#2240]
The Cover Image classes for alignment are no longer being applied on the frontend i.e. alignwide/alignfull e.t.c are missing in the latest version.

The classes are applied correctly on the edit screen though!

**Comment by karmatosed** [comment]
Wide and full are now dependent on the theme. You can read more about that here:
https://github.com/WordPress/gutenberg/blob/master/docs/themes.md

**Comment by WPDevHQ** [comment]
@karmatosed - that is how I've had it from the onset and it worked initially but stopped when I upgraded to v0.7.1

**Comment by karmatosed** [comment]
Noting the following issue as possibly what is happening: #2274
