### ISSUE TITLE
Nav menus page only shows 10 menus for selection, ignoring others if the site has more than 10 menus.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#22404]
**Describe the bug**
Observed while working on #22309.

The nav menus page only displays 10 menus, resulting in some menus being unavailable when a site has more than 10 menus.

**To reproduce**
1. Create more than 10 menus
2. Visit the experimental nav page (wp-admin/admin.php?page=gutenberg-navigation)
3. Open the menu selection dropdown, and notice that only 10 menus are visible

**Expected behavior**
All menus should somehow be selectable

**Comment by noisysocks** [comment]
Related: https://github.com/WordPress/gutenberg/issues/21212 https://github.com/WordPress/gutenberg/issues/19266
