### ISSUE TITLE
Block icons are reordered when adding new blocks

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#22406]
**Describe the bug**
When selecting blocks from the block selector, the order of blocks changes unexpectedly.

![jumping blocks](https://user-images.githubusercontent.com/22446385/82180853-b99a7000-9924-11ea-873b-e14d69fddcc5.gif)

**To reproduce**
1. Open the gutenberg editor
2. Click on the New Block (+) icon
3. Scroll down to the Layout Grid block ( I tested with other blocks too )
4. Click on the block to add it to the page

**Expected behavior**
The block icon in the block selector panel stays in the same place

**Actual behavior**
The Block icon changes positions! moving further up the list of blocks

**Screenshots**

**Editor version (please complete the following information):**
- Tested with gutenberg v8.1.0 which is currently deployed to wordpress.com edge sites and also v8.0.0

**Desktop
 - OS: macos
 - Browser Chrome

I'm sorry if this is an existing issue already

**Comment by pablohoneyhoney** [comment]
“Most Used” or "Common Blocks" are a bit obscure and lack contextuality of the content or intent, more so with FSE.

It’d be ok to keep it as a functionality people opt-in, but hide it as a default. Which would solve this particular issue. 

If users want to activate those views, blocks directory shall not update in the same inserter session. If the inserter closes or the editing session closes, the blocks can be arranged to reflect the usage.

**Comment by roo2** [comment]
Hey thanks for looking into it! yea it's surprising behavior to me, also, this behavior doesn't only affect the "most used" and "common blocks" it affects other block categories too!

![Jun-01-2020 14-04-21](https://user-images.githubusercontent.com/22446385/83386470-7b29a880-a42e-11ea-985f-868bf6fb5e28.gif)

**Comment by kirilzh** [comment]
@pablohoneyhoney I agree that the inserter should not update in real-time. If we do the opt-in functionality, do you know of a similar behavior where I can look up how it is implemented?
