### ISSUE TITLE
Scripts: Upgrade babel-polyfill (or use core-js or alternative directly)

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22417]
Related: https://github.com/WordPress/gutenberg/pull/21492#discussion_r420198058

As noted at https://github.com/WordPress/gutenberg/pull/21492#discussion_r420192067 , the version of `wp-polyfill` shipped in WordPress today is associated with `@babel/polyfill@7.4.4`. The latest version of `@babel/polyfill` is `7.8.7`. It's assumed this would use a newer version of [`core-js`](https://github.com/zloirock/core-js) and thus, polyfills for more new language features in use today in Gutenberg.

A few cases have occurred where a desire or attempt is made to use new language features which are newer than are shipped in polyfills:

1. `Array#flat` (https://github.com/WordPress/gutenberg/pull/21492#discussion_r420037746)
2. `Object.fromEntries` (https://github.com/WordPress/gutenberg/pull/22164#discussion_r426040124)

This may become an increasingly common scenario, as the availability and usage of newer language features starts to increase.

**Implementation Notes:**

Note that `@babel/polyfill` is officially deprecated. This doesn't necessarily mean we couldn't still choose to upgrade from 7.4.4 to 7.8.7 (the latest and probably last version). 

Alternatively, at its core, `@babel/polyfill` is essentially a small wrapper around `core-js` ([source](https://unpkg.com/@babel/polyfill@7.8.7/lib/index.js)). We could choose to use `core-js` directly.

Since this is a script handle shipped already with Core, it would inevitably need an upstream patch. It could be done sooner in Gutenberg following the pattern such as in #14400 / [Trac#48121](https://core.trac.wordpress.org/ticket/48121).

**Comment by gziolo** [comment]
Let's try to mitigate the issue in WordPress core with upgrading `@babel/polyfill` to the latest version with https://github.com/WordPress/wordpress-develop/pull/367.

**Comment by gziolo** [comment]
It's being discussed in https://core.trac.wordpress.org/ticket/52854, so let's close this issue in favor on the WordPress trac ticket.
