### ISSUE TITLE
Z-index clash with autosave and text toolbars

### ISSUE THREAD

**Issue by rtpHarry** [WordPress/gutenberg#22416]
Sorry for the low quality bug report, but I'm working at the moment and I thought I would share this in case it helps. If not, just close it.

Seems there is a z-index clash with the autosave notification and the toolbars:

![image](https://user-images.githubusercontent.com/1038062/82211659-2273ef00-9909-11ea-858c-72aecfd5a105.png)

**Comment by talldan** [comment]
Just noting that I'm very certain this bug has already been reported, but I was unable to find the duplicate. I've labelled it in the meantime, but if anyone else can fine the duplicate, please close one of them.

**Comment by talldan** [comment]
This no longer happens, some new behavior was implemented where the notice scrolls away, so it doesn't seem possible to make a block toolbar overlap a notice.
