### ISSUE TITLE
Descriptions inside click/hover tooltips

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2242]
Those descriptions are generally of course of great help for Users at the beginning. But after Users see them few times they have to live with them in years to come.

Why not put a blue question icon somewhere, and set all descriptions there ?

Inside Inserter i dont know if it would look nice. To many question icons, ugly. Maybe if you go "one embed" field way, as description of all embeds.

Perhaps one new block toolbar button right at the end (question mark). Not there on default, and showed only if third party developers want to explain something to users of their block.

Some other areas maybe. I dont know right now, dont know how will Gutenberg end.

Unrelated to this, some default descriptions are really bad. 
First, Users will have to live with them for long time in the future. OK, not precise the torture, but.. :)
Second is, what the heck, better to stop because of respect to core coders.
- Worth a thousand words.
- Image galleries are a great way to share groups of pictures on your site.

![](https://tutorialzine.com/media/2014/07/inline_help_tooltip.png)

**Comment by karmatosed** [comment]
As we have an issue talking about help already and it's a similar approach. I will close this to focus discussion on #2191
