### ISSUE TITLE
Use hotkey + click to navigate pages in the site editor

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#22429]
As initially proposed in #19204, I think it would be a good idea to explore navigating pages within the site editor via hotkeys along with perhaps a visual indicator.

Here is a [prototype](https://www.figma.com/proto/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=4113%3A6696&viewport=501%2C526%2C0.5&scaling=min-zoom) showing what I mean.

![2020-05-18 11 23 18](https://user-images.githubusercontent.com/1123119/82242347-e8035580-98fa-11ea-9218-a5ed8a629aef.gif)

### Notes

I don't know what hotkey combo we should use. I particularly like the Slack Interface where, if a user holds down `Command`, the sidebar shows various numbers to let the user know what hotkey combinations do. I think for this purpose, perhaps just holding command could show the user the available links to navigate to by showing a border around them and then just let the user click on them. I'm open to ideas here and I'm no expert on the taken hotkeys or implementation.

### Screenshot
![image](https://user-images.githubusercontent.com/1123119/82242875-d2426000-98fb-11ea-9f18-3936a4e30f22.png)

[Source Figma file](https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=4113%3A6614)

**Comment by MichaelArestad** [comment]
[Related](https://github.com/WordPress/gutenberg/issues/13688)

**Comment by mtias** [comment]
Folding this into #23328 for easier tracking.
