### ISSUE TITLE
Block Editor: LinkControl: Remove Popover-associated styling

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22437]
Previously: https://github.com/WordPress/gutenberg/issues/18061#issuecomment-580480464

`LinkControl` is intended to be used as a standalone form field, much like other `*Control` input control components. As such, it should make no assumptions about the context in which it is rendered. Currently, there is styling applied to the `LinkControl` component which assumes that it would be rendered to appear within a popover modal. This should be removed from the underlying component.

Ideally, a generic component like this can "just work" when rendered within a popover. If popover styling is insufficient, it should be considered whether the default popover styling (e.g. padding) is adequate for intended usages. The idea here is: We should avoid the idea that these sorts of components are _special_ and instead aim to have a good set of base styling for popovers which can cover most all usage.

At worst, the styling could be moved to the component which renders the `LinkControl` within a `Popover`. As noted at https://github.com/WordPress/gutenberg/issues/18061#issuecomment-580480464, there is an option to explore to repurpose the (largely defunct) `URLPopover` to this end.

**Comment by richtabor** [comment]
@getdave Is this still relevant? Thanks.

**Comment by getdave** [comment]
I think it can be closed.
