### ISSUE TITLE
Update plugin demo page to properly reflect what Gutenberg can currently do

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2243]
## Issue Overview
The Gutenberg  plugin offers a Demo page which is supposed to obviously highlight what it can do. This page is misleading. There's numerous items on this page that can't currently be replicated using Gutenberg. As an example, unless I'm mistaken, there's currently no possible way to insert an image and make it go 'wide' like the following example.

![gutenbergdemo](https://user-images.githubusercontent.com/2078245/29001652-b8c54276-7ad3-11e7-841b-dc0fc7239fff.png)

The same goes for inserting a 'wide' Cover Image and an Image Gallery.

Whilst I can understand the need to show what Gutenberg can do, it's misleading to show things that it can't currently do. On top of that, it's also extremely frustrating for new users when trying to replicate that Demo page and not being able to.

The Demo page should reflect what Gutenberg can currently achieve, not what you plan or hope to have it do. When the time comes that Gutenberg can produce that exact same layout, then great, update the demo again to reflect that.

## Expected Behavior
I expect to be able to recreate that Demo page in Gutenberg

## Current Behavior
I'm unable to recreate the Demo page exactly as it currently shows.

**Comment by swissspidy** [comment]
> As an example, unless I'm mistaken, there's currently no possible way to insert an image and make it go 'wide' like the following example.

Are you using the latest version of the plugin? Because I see more options in the alignment toolbar, one of which lets me make the image take the full width, just like in the demo.

<img width="826" alt="screen shot 2017-08-06 at 16 36 38" src="https://user-images.githubusercontent.com/841956/29004302-8c80e5a2-7ac5-11e7-9310-2df30ed21b99.png">

**Comment by mtias** [comment]
The "wide" and "full wide" options will appear if the theme declares support for them. This was done because these options make sense if the theme is single column (at least for the post / page view).

See: http://gutenberg-devdoc.surge.sh/reference/theme-support/#wide-images

**Comment by maddisondesigns** [comment]
@mtias Thanks for clarifying that. I've added that to my theme and I can see those extra toolbar options now. It might be worth adding a sentence to the Demo text. Something along the lines of "_If you'd like to insert Wide images just like this demo, don't forget to add Theme Support for them in your theme. For more information, check out our documentation._". I doubt I'd be the only one who didn't know you had to specifically add support for them.

**Comment by hedgefield** [comment]
Agreed on that, I thought that feature had been removed, didn't realize it was due to the default TwentySeventeen setup not having support. The demo post does still show a full wide image 🙃

**Comment by mtias** [comment]
@karmatosed wonder if you have ideas for how to handle this as virtually every theme won't have support for this at first.

**Comment by karmatosed** [comment]
Ideally the demo page should only show what 'out of the box' Gutenberg supports. I think removing anything that requires add_theme_support is a good idea, I do see why people would want to showcase everything though.

If we did stick with everything in the copy saying it's 'theme dependent' would be the best route. I still think don't show unless it's supported out the box is a good idea. Does anyone want to rustle up a PR for this?

**Comment by karmatosed** [comment]
As the project moves towards a full vision, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
