### ISSUE TITLE
List block: confusing icons

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#22445]
**Describe the bug**

In my opinion, the icons for the list type look very similar to each other. Every time I want to change the list type it takes me some time to get the right one. The numbering could be a little bit bigger, or it could include also 2 and 3. I'm not sure what the purpose is of the upper line? Cc @jasmussen

<img width="277" alt="Screenshot 2020-05-18 at 23 40 46" src="https://user-images.githubusercontent.com/4710635/82262342-0603a100-9961-11ea-9c17-2a976c3f4466.png">

**Comment by ZebulanStanphill** [comment]
I also don't get the point of the upper line; I would think that the line should be on the bottom, not the top. But yeah, putting a 2 below the 1 would work as well.

**Comment by jasmussen** [comment]
I think we could explore replacing the top line with another bullet in both of those!

**Comment by ellatrix** [comment]
@jasmussen Thank you! I think it's an easier pattern to recognise when there's more than one bullet or number.

**Comment by ellatrix** [comment]
Fixed in #22593.
