### ISSUE TITLE
Heading block toolbar doesn't reflect all Heading levels

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2244]
## Issue Overview
When inserting a heading block, the popup toolbar only allows you to change the heading to H2, H3 or H4, whereas in the Settings panel, you're able to select all Heading levels (i.e. H1 - H6).

The toolbar should also display all Heading levels, just like the Settings panel.

![gutenbergheadingblock](https://user-images.githubusercontent.com/2078245/29001866-cc7c2f38-7ad7-11e7-955d-46aa4c72eb7e.png)

## Steps to Reproduce (for bugs)
Insert Heading Block and start typing a heading.

## Expected Behavior
The Heading Block toolbar should display all heading levels from H1 to H6

## Current Behavior
The Heading Block toolbar currently only displays H2 to H4

Plugin **Version 0.7.1**

**Comment by karmatosed** [comment]
You are totally correct it doesn't show in the tooltip. I am wondering though if it needs to. H5/H6 aren't as common and they are in the inspector. This makes me think if it is actually a decision that makes sense to leave as is. The toolbar doesn't after all have to contain all options for the block.

**Comment by maddisondesigns** [comment]
I think it's confusing having it in the settings panel but not in the toolbar. When you insert a new Heading Block, the Settings panel for the block (on the right-hand side) doesn't automatically appear. Only showing H2-H4 in the toolbar is going to confuse people as to why they can't insert an H1 (or H5/H6). Even when people know that those options are in the Settings panel, you're forcing them to have to make extra clicks, to switch to the Settings panel just so they can select one of these other heading types.

I don't see any valid reason for hiding these from the user. The extra three heading levels aren't going to clutter up the toolbar and it keeps the interface consistent (between what you can select in the toolbar and what you can select in the Settings panel).

When people choose to insert a Heading Block, they're going to expect to be able to select any heading (H1-H6). Only showing them a limited selection is going to be frustrating.

**Comment by hedgefield** [comment]
I can see how stopping at H4 makes the text block and heading block toolbars the same length, which I can appreciate as a designer. But all the other block types have a wildly varying toolbar layouts, so it's not like we'd break consistency by adding H5 and H6.

That said, H5 and H6 are indeed considered 'archaic' by some (not in the least by Michiel of Yoast, who discussed it in detail [in this blog post](https://yoast.com/headings-use/)).

So personally I agree with @karmatosed. I think we should remove H5 and H6 from both. But more generally I agree that there should at least not be a difference between toolbar and sidebar.

**Comment by karmatosed** [comment]
Closing this as we are ok having up to H4 right now. We can always come back to this and reopen after usability testing.
