### ISSUE TITLE
button placeholder text is unreadable

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#22457]
Hi - in my theme the button placeholder text is unreadable. This will happen on any theme that doesn't have dark coloured buttons. The reason is this very specific rule:

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/editor.scss#L17-L19

You can see a screenshot of the problem here:
<img width="1791" alt="XF6MRM6lFN" src="https://user-images.githubusercontent.com/1004130/82301086-a7b1df00-99af-11ea-8725-d7bbd8cfa57a.png">

and here:
<img width="713" alt="Screenshot 2020-05-19 at 08 58 18" src="https://user-images.githubusercontent.com/1004130/82300585-f3b05400-99ae-11ea-99d2-90c1c113f283.png">

If you change the colour from white to use the `currentColor` keyword then the element will inherit the buttons colour and so always be readable. The 0.8 opacity will help show it's a placeholder and not normal colour.

I have used this fix on the editor styles for the two themes screenshotted above and it seems to work fine.

**Comment by tellthemachines** [comment]
That line of code could certainly be less specific. The `:not(.has-text-color)` at least should be removed, as that classname is not applied to `.wp-block-button` but to its child `.wp-block-button__link`.

**Comment by carolinan** [comment]
Hi Ben! Can this issue be closed?, or can you provide any up to date information?
The CSS has changed over time and there are several ways for theme developers to style their buttons.

**Comment by BinaryMoon** [comment]
Hi Carolina - I'll close it. Thanks
