### ISSUE TITLE
Add function like remove_pattern() to remove specific pattern

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#22455]
There is currently no way to manage existing patterns. But I think doing this is very helpful. So I am asking for a feature request to add this future functionality. In relationship to the **register_pattern()** function, it would make sense to define a function like **remove_pattern()** to remove a specific pattern.

**Comment by Soean** [comment]
There is already a function to remove pattern.
https://github.com/WordPress/gutenberg/blob/505fc00393464a0226bb8f4dd9b43df0aadf7e45/lib/class-wp-block-patterns-registry.php#L131-L140

PS:
`register_pattern()` was renamed to `register_block_pattern()`.

**Comment by CreativeDive** [comment]
@Soean This is awesome, thank you very much! Please close this issue :-)
