### ISSUE TITLE
Update fails after inserting "latest post" Block

### ISSUE THREAD

**Issue by carstenheisterkamp** [WordPress/gutenberg#2245]
## Issue Overview
Update of a post repeatedly fails after inserting a Latest Post Block and the following error in the Editor 
`wp/wp-content/plugins/gutenberg/blocks/library/latest-posts/index.php on line 55`

## Steps to Reproduce (for bugs)

1. Create new post
2. Add Paragraph, Images, Gallery Blocks
3. Update -> Success
4. Add Latest Post Block 
5. Update -> fails
6. Remove latest post
7. Update -> success 

## Expected Behavior
Update succeeds after adding a latest post block

## Current Behavior
Update fails after adding latest post block

## Possible Solution
The latest post block seems to regard the currently edited post (where user is currently adding the latest post block) already as a latest post, since it is listet in the latest post preview which might create a loop.

**Comment by karmatosed** [comment]
I can replicate this, the update does fail as soon as you add the latest posts block.

It also fails just by simply adding a latest posts block to a new post and saving:

![2017-08-07 at 10 19](https://user-images.githubusercontent.com/253067/29020487-11fb8464-7b5a-11e7-9f74-345cace51dab.png)

**Comment by youknowriad** [comment]
🤔 Can't reproduce this weird

**Comment by karmatosed** [comment]
I still can at will recreate this and the messages stack up with auto saving.

![2017-08-07 at 14 41](https://user-images.githubusercontent.com/253067/29029169-a8bf2b98-7b7e-11e7-9bd9-1f9df1882329.png)

**Comment by karmatosed** [comment]
![2017-08-07 at 15 39](https://user-images.githubusercontent.com/253067/29031877-7faec412-7b87-11e7-92f5-bab587ed3c8b.png)

Adding more information to this ticket of what I see.
