### ISSUE TITLE
Centre Aligned Image is no Longer Centre Aligned in Editor Again

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#22461]
This issue was fixed once in #21885 and the PR #21911, but it seems we have the same issue now again.

A centred image is no longer centre-aligned in the editor if the latest Gutenberg is activated. It's easy to see a small image like a thumbnail. The image appears centred on the front of the site.

**With Gutenberg plugin:**
![Screenshot 2020-05-19 at 11 56 52](https://user-images.githubusercontent.com/908665/82318655-1e5ad680-99c8-11ea-838f-41c6c49ea1c9.png)

**Without Gutenberg Plugin:**
![Screenshot 2020-05-19 at 11 54 54](https://user-images.githubusercontent.com/908665/82318681-274ba800-99c8-11ea-93c5-e87825b2216f.png)

Tested with Mac Chrome, Twenty Twenty theme.

**Comment by annezazu** [comment]
@iamtakashi for clarity, was this image previously centered aligned before the update and then the 8.3 update unaligned the image? In trying to test this, I'm able to center align images without a problem.

**Comment by iamtakashi** [comment]
@annezazu, thanks for looking into this. 

I'm pretty sure there was a regression when I opened this issue, but as you noted, I now can make an image centre-aligned. 

However, I find it weird that selecting a centred image shifts the image left-aligned though. I'm not sure if this is intentional, but if you think this needs to be reported as a new issue, let me know.

![centred-image](https://user-images.githubusercontent.com/908665/85080921-62591b00-b1c2-11ea-903e-04e94aa96fd4.gif)

Tested with 8.3.0 with Twenty Twenty theme.

**Comment by annezazu** [comment]
Wow! That's super weird. I tried replicating using 8.3.0 with Twenty Twenty and WordPress 5.4.2. I weirdly couldn't replicate this: https://cloudup.com/cdMbOc3N0xj Do you have any other plugins on the site?

**Comment by iamtakashi** [comment]
Sorry, @annezazu. I found a third-party plugin causing the shifting issue. I should've disabled all the additional plugins before reporting the shifting issue. I'll make sure that next time.

Since I can't see the regression anymore, I'm closing this issue.

**Comment by annezazu** [comment]
All good here :) Thanks for finding the problem and closing.
