### ISSUE TITLE
Block Editor: blocks with align-full inside a reusable block exceed horizontal width of the container

### ISSUE THREAD

**Issue by dkoo** [WordPress/gutenberg#22479]
When using a reusable block with any block that has `data-align="full"` as an attribute nested inside of it, the nested block will exceed the width of the reusable block's container within the block editor.

This seems to be an edge case related to the fix from this change: https://github.com/WordPress/gutenberg/pull/21312

The fix normalizes margins/padding for reusable blocks on the front-end. In the editor, however, the reusable block's container has negative horizontal margins applied which are supposed to be offset by equal padding applied to the inner nested block. Setting that inner block to full alignment sets the horizontal padding to `0`.

**Steps to reproduce the behavior:**

Visible at larger viewport sizes.

1. Ensure that the theme has enabled support for full-width block alignment.
2. In the block editor for a page or post, create a Group. Set the background color to something visible for easier visual confirmation.
3. Inside the Group, add another block that supports the "full" alignment attribute. Set the alignment to full.
4. Convert the Group to a Reusable Block. The inner block gets wider than the width of the reusable block's container.

**Expected behavior**
The inner block should not exceed the parent's container, even if set to "full" alignment.

**Screenshots**
<img width="888" alt="Screen Shot 2020-05-19 at 2 50 50 PM" src="https://user-images.githubusercontent.com/2230142/82376995-32aacd80-99e0-11ea-9f84-822d1ea2c180.png">

**Environment**
WordPress v5.4.1 with built-in block editor.

**Comment by kathrynwp** [comment]
I'm not able to replicate this with:

WordPress 6.0.1
Gutenberg 13.7.3 active or inactive
Twenty Twenty-Two 
No other plugins active

@dkoo If you are still able to replicate, could you please let me know what theme you're using and confirm that you're using the latest version of WordPress and Gutenberg?

I'll go ahead and close this out but do feel free to comment if you can still replicate and I'll be glad to have another look.
