### ISSUE TITLE
Disable Minify JavaScript under Beta testing phase ?

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2247]
Can you do it until Gutenberg go stable version ?

For Us who would like to study JS code, reuse, edit code, and try to make own block(s).
Did my own by your docs, piece of cake. But it is simple text block. Anything more than that I need to see how you did it. Examples on Google are non existent.

**Comment by mtias** [comment]
You can change this by setting script debug on your end: https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG

Inspecting the source won't be the easiest to learn how to create blocks. We have some more examples here oriented to plugin/theme authors: http://gutenberg-devdoc.surge.sh/blocks/writing-your-first-block-type/

**Comment by StaggerLeee** [comment]
Thank you. I meant something to open in code/text editor.
Will close issue anyway.

**Comment by nylen** [comment]
FWIW `SCRIPT_DEBUG` doesn't quite work yet because we only ship the minified version of our code with the Gutenberg plugin.  However I'll leave this issue closed because it's a duplicate of #1026.
