### ISSUE TITLE
Make link navigation responsive

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#22497]
**Is your feature request related to a problem? Please describe.**

With a few levels of nesting and long labels, this is what we get on the experimental navigation screen:

<img width="1088" alt="Zrzut ekranu 2020-05-20 o 15 45 17" src="https://user-images.githubusercontent.com/205419/82453559-f6936d80-9ab0-11ea-873b-fc65d0fa003a.png">

Let's discuss how we could make it better.

**Comment by karmatosed** [comment]
I am going to tackle this in 2 design explorations. The first is going to be iterating on the block navigator to make it adapt easier and have lighter experience. The second will be looking at some little adjustments to make the sub-navigation experience on the navigation block refined. 

First, props to @mtias for pointing me towards Squarespace for inspiration here. In stepping through their navigation experience a few things struck me as iterations we could bring in:

- A lighter interface
- Having sub-navigation show and hide over be 'always on'

There are a lot of other possibilities, but for this issue, I am focusing on what could soothe right now. I will be adding some more mocks for other aspects.

I also reviewed existing components and took a wider screen that we use now for the library. This would technically mean increasing on this screen so it's a point to note in decisions as I look for feedback.

Before I dive in, I would love to know what is desirable for v1 and what we can work towards. I think quite a bit of what I am suggesting falls into iterations over adding new functionality, however, I would love to check on what we pull into actions.

## Iteration 1: A lighter interface

The first iterations shows a few things:
- '+' for top-level link adding goes by title.
- Unless sub-navigation no lines show.
- Remove repeating icons.
- Movers go to left side in a wider gutter.
- Ellipsis goes to the right side in the same wider gutter.
- Sub-navigation is indicated with a smaller tree, with a lighter shade.

<img width="350" alt="More Menu" src="https://user-images.githubusercontent.com/253067/82661380-ce784b80-9c23-11ea-9727-efbb108e7fac.gif">

Now, this does have a minimal '+' at top, we might want to bring in the darker one, that could look like this:

<img width="350" alt="More Menu" src="https://user-images.githubusercontent.com/253067/82661458-f5cf1880-9c23-11ea-8a63-8a8dd04e9e04.png">

Adding sub-navigation is done via a link from ellipsis in this version.

What does this look like on the above screen? Here is a very rough mock with the narrow width still, just to show how it could fit (although I do advise we go wider).

<img width="1435" alt="Frame 1" src="https://user-images.githubusercontent.com/253067/82661877-c240be00-9c24-11ea-9adc-f4a4c38cc7c7.png">

Of note, in my prototypes it doesn't highlight the current item like we do using a darker background, that could be added however in the examples I was working from this wasn't something implemented so I decided to see how light I could go.

## Iteration 2: + by sub-navigation
This takes sub-navigation adding out of the ellipsis and brings to the bottom of the tree view.

<img width="350" alt="More Menu" src="https://user-images.githubusercontent.com/253067/82662563-fec0e980-9c25-11ea-9800-225e46c3bcdc.gif">

## Iteration 3: inside ellipsis
One final iteration brings the ellipsis into the inside of sub-navigation indication.

<img width="350" alt="More Menu" src="https://user-images.githubusercontent.com/253067/82662643-21eb9900-9c26-11ea-9283-18be91aecaaf.gif">

## Hitches and hurdles: nesting sub-nav
There is still an outstanding problem with nesting sub-navigation. With this iteration and lighter interface we can get comfortably far more nesting. However, the problem at some point will raise its head. There are a few potential options:

- Bring in horizontal scrolling.
- Over a certain number of sub-navigation nesting don't show tree or indenting. This would be similar to nested comments.

My own feelings are that limiting over a certain number is acceptable behaviour within WordPress, however, I would love other insights.

## Feedback
I would like some specific feedback on a few things, more general thoughts and input is of course welcome.

- What tasks should be pulled out from this to move into development?
- What are things, for now, to put aside and focus on later?
- What doesn't work and shouldn't be implemented?
- Which iteration out of any do you feel is the one to pursue?
- Which sub-navigation nesting route would you prefer?
- Should the first levels of sub-navigation be closed or open by default?
- Is making the navigator wider a possibility within the nav-menus.php screen or is there a technical limitation there we need to keep it narrow for?

**Comment by karmatosed** [comment]
Along with some iterations to the block navigator I think a few small adjustments can be done to the navigation block itself to lighten up the interface. 

- Consider bringing the same arrow treatment in for sub-navigation in block navigator.
- Remove gap of sub-navigation.
- Reduce spacing around menus.

This is a small visual improvement but could link the two together more in experience through using same showing arrows and also allow for less visual density.

The same 'limit' on nesting might be something we want to consider as a visual here, but that's a point to decided in block navigator and see where we go here.

<img width="714" alt="subnav" src="https://user-images.githubusercontent.com/253067/82665339-89581780-9c2b-11ea-97e9-67f819bdd9b9.png">

## Feedback
Really these changes are pretty minor so I would ask for general feedback, along with these points:

- Is uniting the arrows a good step or step too far?
- What other things could be done to ease this screen as it grows in nesting of sub-navigation?

When thinking of other things, consider this an iteration and how can we within the existing interface ease this experience.

**Comment by karmatosed** [comment]
Adding a second iteration to block navigator work after some feedback and surfacing of the hit areas for icons that @jasmussen noted in ellipsis issue. Props to @mtias for feedback.

A few points to this iteration:

- Brings back icons which will be important as have different block types (future). I do wonder if we could indicate if post or page (later iteration).
- Brings sub-navigation opening to the menu itself.

<img width="350" alt="icons" src="https://user-images.githubusercontent.com/253067/82676816-e5786700-9c3e-11ea-9883-4c9446913c24.png">

## Increasing the size of hit area on movers
Here are a few variations on increasing spacing to increase the hit area. This will need tieing into the work there.

@jasmussen going to loop you in for feedback on spacing, movers and what iteration/line spacing works best based on the current direction. I think it's important it aligns.

<img width="1368" alt="spacing" src="https://user-images.githubusercontent.com/253067/82676861-f923cd80-9c3e-11ea-86fb-a6539bf1288c.png">

**Comment by manmotive** [comment]
I prefer all levels of the "Navigation structure" being visible by default, as they currently are. The option to collapse them could be useful, but I think it's important to have somewhere on this screen that shows a complete "data view" of the menu hierarchy (by default). The "visual view" is already covered by the "Navigation menu" side.

My suggestion would be to widen the Navigation structure area, wrap the text for long menu item names, and add a maximum nesting level after which point sub menus no longer get indented (ala comments).

**Comment by talldan** [comment]
One thing I've wondered is whether we need the connecting lines. There are some examples of tree like structures that are expandable don't have the connecting lines between parents and children and instead have the expand/collapse icon in that position.

e.g. Figma:
<img width="242" alt="Screenshot 2020-05-25 at 4 22 33 pm" src="https://user-images.githubusercontent.com/677833/82793767-08f01b80-9ea4-11ea-85d6-6b26e62b4a97.png">

I still think the hierarchy is clear in that screenshot without the connecting lines.

Usually it's down facing arrow for expanded and right facing arrow for collapsed. I know that's different to other WordPress UI (like panels), but maybe that's acceptable here. 

I quite like the highlighting of the selected item and its children (in a lighter tone) in the screenshot above as well. That makes sense to me, particularly in respect of duplicating/moving/removing, as it makes it clear those actions on the parent affect all children as well.

**Comment by jasmussen** [comment]
The reduction overall is very helpful. In that vein, @talldan, I think your instinct is right and it would be interesting to remove the lines entirely, and put the chevron on the left of items that have submenus, but otherwise rely only on the indentation to indicate the hierarchy.

I'd also use the same behavior — right facing chevron or arrow when collapsed, down-facing when open.

I think we should avoid up/down movers side by side. It takes up precious horizontal space, and it removes the connection it has to the block movers. I think it's okay to use a full 48px for each item, it sticks to the grid and affords some simplicity and space. 

I'd also put the ellipsis right-most. This is a pet peeve of mine, that "more" always comes at the end.

**Comment by karmatosed** [comment]
I took a little moment to try and mock this up to see if I am understanding clearly. @jasmussen and @talldan does this fit your ideas?

<img width="350" alt="More Menu" src="https://user-images.githubusercontent.com/253067/82918268-60f25500-9f6c-11ea-8b53-9a070445d63e.png">

**Comment by talldan** [comment]
@karmatosed Yep, that looks very much like what I had in mind. What do you think?

**Comment by karmatosed** [comment]
Just going to post some iterations that @jasmussen worked on and I gave some feedback. This is taking the current work and iterating.

<img width="906" alt="Navigation" src="https://user-images.githubusercontent.com/253067/83012100-dc0e4680-a012-11ea-91e4-3b7025c21731.png">

**Comment by mapk** [comment]
Things are coming together here! Thanks for iterating.

I could go either way with the tree connecting lines. I like them, but also understand that this little Navigator is getting cramped with UI elements. So if removing them helps keep things light, let's do it.

I'd like to see another iteration around those mover arrows. The balance of spacing in between them as compared to the spacing above or below them is awkward. They feel much too close to the edge and very far apart from each other. Using the [smaller arrows](https://github.com/WordPress/gutenberg/issues/21935) in this case may help this.

I think the images are just not zoomed at 100%, but nevertheless wanted to point out that the font size is extremely small. My guess is that zoom is the problem, not the actual font size. :)

The order of UI elements is strong. The smaller carrot on the left side and the movers and ellipses on the right side make for a good balanced layout.

I'm also glad to see the black `+` icon back in there because it's consistent with the Inserter icon elsewhere.

**Comment by jasmussen** [comment]
Great thoughts, Mark, thank you. 

The [mover PR is](https://github.com/WordPress/gutenberg/pull/22673) fast coming along, and is working reasonably well with the icons from the icon component, it might be worth trying to use the same icons there first, and if we decide they're too big in both places after trying it out, we can update both of them at the same time. I volunteer as tribute ✋

<img width="575" alt="Screenshot 2020-05-29 at 08 32 27" src="https://user-images.githubusercontent.com/1204802/83228926-565fd780-a187-11ea-8412-944d72b51081.png">

In the mean time, I can't believe I missed the off balance of those arrow — great eye. I adjusted them to match exactly the configuration of the new mover control you see above:

<img width="906" alt="Navigation" src="https://user-images.githubusercontent.com/1204802/83228957-67104d80-a187-11ea-8d53-b9d9ddd3145b.png">

What do you think? I think it strikes a good balance, and buttons remain 24x24!

**Comment by adamziel** [comment]
I'll have a PR for that today :-)

**Comment by adamziel** [comment]
Very first attempt available in https://github.com/WordPress/gutenberg/pull/22796

**Comment by draganescu** [comment]
Closed by #22796
