### ISSUE TITLE
Cover: Video - Add position controls

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#22509]
At the moment, the horizontal and vertical background positioning controls only work for Cover images. **Cover videos lack this feature**.

![Screen Capture on 2020-05-20 at 17-33-12](https://user-images.githubusercontent.com/2322354/82500041-b6d48200-9ac0-11ea-8a29-79576f1d7587.gif)

I think it would be helpful to add feature parity with video backgrounds.

To achieve the same positioning MATH, `<video />` styles can use [object-position](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position).

This will also give as an opportunity to improve the `FocalPointPicker` component a bit.

I've done some explorations! I've added couple of enhancements, including adding our new `UnitControl` components as well as a Grid overlay. It feels really nice!

![Screen Capture on 2020-05-20 at 17-19-09](https://user-images.githubusercontent.com/2322354/82500051-ba680900-9ac0-11ea-869c-6322bca1df5a.gif)

Note: This does not work on IE 11. However, `video` backgrounds **already use** `object-fit: cover`. So this update should not introduce a regression on IE 11.

**Comment by mtias** [comment]
This is great. I think the grid should always show up _while you drag_ instead of being a toggle.

**Comment by ItsJonQ** [comment]
@mtias Oh interesting!!! That makes it easier. We can do that ❤️ !

**Comment by ItsJonQ** [comment]
![focal-demo](https://user-images.githubusercontent.com/2322354/82586214-387deb80-9b65-11ea-9be1-4576fb89aeca.gif)

@mtias Aww yiss!

(Also in the demo, pressing keyboard arrows to adjust position. <kbd>Shift</kbd> jumping is supported)

**Comment by jasmussen** [comment]
Looks amazing, Jon! Here's a visual tweak to the field:

<img width="342" alt="Focal point picker" src="https://user-images.githubusercontent.com/1204802/82664585-49486300-9c32-11ea-83b0-5bcf93a2d36c.png">

What do you think?

**Comment by ItsJonQ** [comment]
@jasmussen Sure thing! I can give it a shot ✨

I opened a draft PR:
https://github.com/WordPress/gutenberg/pull/22531

We can collab and iterate there 😊

Since we're working on this component... I think it would be a good opportunity to explore any UI/UX ideas.

The "wouldn't it be cool if..."  ones.

I think the 9x9 grid as a good example of this. Made better by @mtias 's interaction suggestion

**Comment by whimsyniche** [comment]
This is neat when will it be added to gutenberg?
