### ISSUE TITLE
Block with modified align supports defaults to unavailable option

### ISSUE THREAD

**Issue by pinksharpii** [WordPress/gutenberg#22501]
Using the [documentation](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#blocks-registerblocktype) I wrote a filter to allow only Align full for Cover blocks on a site I'm building. 

**To reproduce**

`wp.hooks.addFilter(
        'blocks.registerBlockType',
        'vsmidwest/wordexpresso',
        function( settings, name ) {
            if ( name === 'core/cover' ) {
                return lodash.assign( {}, settings, {
                    supports: lodash.assign( {}, settings.supports, {
                        align: ['full'], 
                    } ),
                } );
            }
            return settings;
        }
    );`

**Expected behavior**
If align is limited to just full, the default should not be center.

**Screenshots**
[Adding new Cover block](https://snipboard.io/bNaWKJ.jpg)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Comment by gziolo** [comment]
It looks like you should also update the default value for `align` attribute which I think defaults to `undefined` that translates to don’t apply any class names to this block. So `alignfull` class isn’t there and thus it looks like this.

**Comment by pinksharpii** [comment]
Late response but here is my final working code for anyone else who needs it:

`
wp.hooks.addFilter(
    'blocks.registerBlockType',
    'bdc/wordexpresso',
    function( settings, name ) {
        if ( name === 'core/cover' || name === 'core/group' ) {
            return lodash.assign( {}, settings, {
                supports: lodash.assign( {}, settings.supports, {
                    align: ['full'], 
                    default: 'full'
                } ),
                attributes: {
                    align: {
                        type: 'string',
                        default: 'full'
                    }
                }
            } );
        }
        return settings;
    }
);`
