### ISSUE TITLE
How to sort inner blocks that use meta value?

### ISSUE THREAD

**Issue by lievikoff** [WordPress/gutenberg#22504]
Hi! I have a few inner blocks that i need to sort. How can i define that block was moved and where was moved (up or down) to sort my array before saving them?

**Comment by talldan** [comment]
@lievikoff I'm not sure I understand the question or from what perspective you're asking. 

Issues here are related to the development of the Block Editor itself, in particular bug reports or enhancement requests.

If there's a question the WordPress forums are a good place to ask:
https://wordpress.org/support/forums/

**Comment by lievikoff** [comment]
Solution: Use wp.data.subscribe function it will help to know when store is changed and then you can use select or dispatch depends on the state.
