### ISSUE TITLE
Columns Block: Full width setting prevents us from moving blocks up/down

### ISSUE THREAD

**Issue by xpurichan** [WordPress/gutenberg#22529]
**Describe the bug**
We can setup a column block to use the "full width" alignment setting. Once we do this we can continue adding blocks inside of each column, but the option to move blocks up/down on the leftmost column is cut off of the editor (because the content displays on the left edge of the screen with no margin for the block movement options to appear).

**To reproduce**
1. Visit https://wordpress.org/gutenberg/ or create a new post/page in the block editor on your test site.
2. Add a columns block
3. Set the columns block to "full width"
4. Add content to the leftmost column
5. Note that you can't see the option to move the block up/down within the column, we can see the option to move next blocks up/down on the other columns (such as the middle or rightmost columns) since they aren't cut off on the edge of the page.

**Expected behavior**
I would expect the editor to display some margin on the left and right side of the page. This would allow setting options such as this to display (without being cut off), it would look more natural, and it would be a better representation on the actual look of the page since we do display margins on the actual/preview version of the page.

**Screenshots**
Screenshot of the up/down option for the paragraph block in the leftmost column being cut off:
![Screen Shot 2020-05-21 at 12 36 19 PM](https://user-images.githubusercontent.com/33190975/82582355-eb4b4b00-9b5f-11ea-837c-526b242fe766.jpg)

Screenshot of the up/down option for the paragraph block in the middle column displaying properly, since it isn't cut off:
![Screen Shot 2020-05-21 at 12 37 06 PM](https://user-images.githubusercontent.com/33190975/82582389-fb632a80-9b5f-11ea-9d38-e208a542d17b.jpg)

Screenshot showing that the final version of the page (when previewed) does display margin; adding incentive for us to actually display margin on the editor of the page since this is more accurate to the final design and allows the up/down settings to display properly:
![Screen Shot 2020-05-21 at 12 37 29 PM](https://user-images.githubusercontent.com/33190975/82582460-12a21800-9b60-11ea-9c3d-88fba337022e.jpg)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? This problem is replicated with or without the plugin.
- If the Gutenberg plugin is installed, which version is it? N/A

**Comment by talldan** [comment]
I can reproduce. I think this might have been solved recently for the columns block itself, but it still seems to be an issue for blocks inside the columns.

Would be good to add automated tests for any fix, as I feel like this alignment issues have happened a number of times now.

**Comment by xpurichan** [comment]
I agree on the automated testing. Most notably I recall seeing issues where the user could setup a wide page layout (when creating a new page) on a theme that didn't support it, and it would cause part of the content to be cut off on the edges of the editor and on the actual page.

**Comment by youknowriad** [comment]
This is not valid anymore
