### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by SheElf** [WordPress/gutenberg#22527]
**Describe the bug**
The Gallery option seems to have changed overnight. Although I'm able to upload two images, they do not show up on my preview. I can use a single image, but not the gallery. I have to go to Picmonkey and put two images together and upload that way. 
![no gallery image](https://user-images.githubusercontent.com/17300848/82580512-71f62d00-9b4c-11ea-9712-74ab0ecc02dd.PNG)

**To reproduce**

**Expected behavior**

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by SheElf** [comment]
I was able to get two images on using the Gallery block, but there is a  HUGE gap below the images. 
![gap](https://user-images.githubusercontent.com/17300848/82583719-a79d1500-9b50-11ea-9aa4-a9fe292bc54b.PNG) Have you updated this?

**Comment by talldan** [comment]
@SheElf I wasn't able to reproduce the issue. But then there are no Steps to Reproduce again in the bug report.

Please could you update the issue description.

**Comment by talldan** [comment]
Closing as no further information has been posted
