### ISSUE TITLE
Block group‑image, Slide, should have an option in aside bar, to allow to launch each image as link in new tab or that page.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#22530]
**Is your feature request related to a problem? Please describe.**
I try to be able to open each image’s of my block group image’s : Slide’s,
in a new‑tab,
because the size of image’s in Slide is to small, in comparison with their real size. And the text is not readable properly.

**Describe the solution you'd like**
A new option or parameter in aside‑bar (Document | **Block**),
with a **check‑box** or **select** to decide if in "`_blank`" or else…

**Describe alternatives you've considered**
The possibility to edit the Slide in H.T.M.L. like other blocks.

Please, thank you, jood continuation.

**Comment by talldan** [comment]
@Nemzag There isn't a Slide Block in core WordPress. It might be that this is a block from a plugin, in which case you'd have to reach out to the plugin developer.

**Comment by Nemzag** [comment]
I use wordpress.com and in it, we have block Gallery, and many type, one is Slide.

**Comment by Nemzag** [comment]
@talldan 
Did you seen my previous response ?

**Comment by Nemzag** [comment]
@talldan 
Did you read it ? Can you unclose ?

**Comment by talldan** [comment]
@Nemzag WordPress.com is a separate commercial product that comes with some extra features, you'd have to reach out to WordPress.com support for help with your issue - https://wordpress.com/support/
