### ISSUE TITLE
Block variations missing from slash inserter

### ISSUE THREAD

**Issue by clarklab** [WordPress/gutenberg#22542]
**Describe the bug**
I've recently noticed that block variations aren't showing in the slash inserter (while showing just fine in the main "+" button inserter.

**To reproduce**
1. Create a block variation. I did so via an editor.js file, like so:
`wp.blocks.registerBlockVariation(
  'core/quote',
  {
    name: 'fancy-quote',
    title: 'Fancy Quote',
  },
);`
2. Check that the variation shows in the inserter "+" menu (that works for me)
3. Try to find the variation in the slash inserter (typing "/ [block name]")
4. Notice that it is missing (I tried variations on many core blocks and saw the same behavior again and again)

**Expected behavior**
All block variations should be listed inside the slash inserter.

If that's not the intended outcome, we should document it somewhere. I saw there is a "scope" param, but docs said if you leave it clear it should be scope to all available scopes. I couldn't find any values beside "inserter" and "block", and neither get it inside the slash inserter.

**Screenshots**
![image](https://user-images.githubusercontent.com/160409/82619698-3edb8a00-9b9c-11ea-9b45-d3fa589b848b.png)
![image](https://user-images.githubusercontent.com/160409/82619712-48fd8880-9b9c-11ea-8ce4-d2a1da8b2231.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser Chrome
 - Version 81.0.4044.129

**Comment by talldan** [comment]
Thanks for the ticket @clarklab. This one is being tracked on #20583, so I'll close this as a duplicate.

**Comment by clarklab** [comment]
Doh! I searched and couldn't find it. Glad it's being tracked!
