### ISSUE TITLE
Add a visual indicator for external images within the image block

### ISSUE THREAD

**Issue by timbutler** [WordPress/gutenberg#22545]
**Is your feature request related to a problem? Please describe.**
Related to #2515 but probably likely to remain an issue going forward.

When an external image is referenced in the image block, there's no easy indication that it's **not** from the local media library (ie, it wasn't uploaded). This can lead to accidental issues where the original source disappears (eg Google Docs cut and paste) or where the content has been pasted from a source which isn't public (Intranet / internal Wiki).

**Describe the solution you'd like**
I'd like to see some sort of visual indicator (maybe a flag / small label? a different border colour for the block?) to indicate that the image is different to others from the media library. 

**Describe alternatives you've considered**
Currently, each image needs to be individually checked. There's no indication in the toolbar nor is there any in the right hand options, which means they all need 3 clicks to perform a confirmation. This leads to inefficient editing as well as leading to publishing mistakes.

**Comment by talldan** [comment]
The easiest way to tell at the moment seems to be to click on the `Replace` button and check the URL, but that's not all that obvious.

This enhancement request probably applies to other blocks that can handle external media as well (video is another).

**Comment by bph** [comment]
I actually would appreciate if the images from Google Docs would be uploaded to the media library so the content pasted from Google is disassociated from the Google platform. Would we need to create a separate issue for this feature request?

**Comment by timbutler** [comment]
Hi @bph, if you see #2515 there's progress towards this being completely automated. At present however, it simply references a preview URL from Google which may or may not remain long term. 

Other than images, the cut and paste is so seamless (which is great!) you'd nearly not notice which is why I think some form of visual indicator is required just so that the user is aware.

**Comment by bph** [comment]
I think the visual indicator is a crutch at least for Google Docs. The much better solution would be to actually import the images to the media library and the external indicator wouldn't be necessary.

**Comment by timbutler** [comment]
Hi @bph while I agree that the import of images is a better solution specific to a cut and paste from Google Docs, the issue will still exist where content has been cut and paste from other platforms (as noted in the original submission).

This is why I figured it was worth raising as a separate feature request as there's always going to be a system where the images won't automatically be loaded or where they've been explicitly set as a remote image.

**Comment by bph** [comment]
Absolutely agree. I didn't mean to indicate that this wasn't a good issue to raise. Yes, there will also be a situation where an end user needs to know that some of their images are not in the media library and their display depends on the other entity to keep the current location active.

**Comment by mtias** [comment]
I think the work done in #46014 covers this scenario — the publishing flow now lists external images so you can double check. There's maybe other improvements to follow up on, like showing it directly in the image toolbar or the list view, but unless there's a concrete design proposal I think we can wrap this one.
