### ISSUE TITLE
Selecting blocks in block navigation is not possible on the Navigation Menu page

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#22544]
**Describe the bug**

**To reproduce**
1. Enable the Navigation Page experiment
2. Create a menu and add some navigation link blocks to it
3. Try selecting a navigation link from the Navigation Structure on the left.
4. Notice that it's only possible to edit the link

**Expected behavior**
The nav link block should somehow be selectable

**Comment by draganescu** [comment]
This is tied (or duplicate?) with #22705

**Comment by talldan** [comment]
I think this is now resolved by https://github.com/WordPress/gutenberg/pull/22629
