### ISSUE TITLE
Images placed in 2 colums are not displayed in full width of the page (Safari)

### ISSUE THREAD

**Issue by Robin9224** [WordPress/gutenberg#22547]
**Describe the bug**
I have experienced several times the situation that only in Safari two images which are placed in 2 colums next to each other do not fill the whole 100% width of the page. 

The two images are both 425px wide.

**Expected behavior**
The two images together should fill 100% width of the page. The page width is 850px

**Screenshots**
<img width="1283" alt="Bildschirmfoto 2020-05-22 um 09 52 20" src="https://user-images.githubusercontent.com/8388280/82644673-fced2b00-9c11-11ea-9835-637b3266efaf.png">

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Block editor

**Desktop (please complete the following information):**
 - Safari Browser 13.0.5

**Comment by annezazu** [comment]
@Robin9224 Thanks for reporting this! I tried to replicate this but wasn't able to. For starters, I took screenshots that are each roughly the same size (425px wide) and was able to do so in Safari. From there, I was also able to make the images take up the entire width of the page just to be safe:

https://cloudup.com/cQmLNYyTkiC

Can you share what WordPress and Gutenberg (if applicable) version you are using? What theme are you using? I am using WordPress 5.4.1 without Gutenberg for this testing to try to match the information you shared already.

**Comment by karmatosed** [comment]
I am going to close this for now until more there is a bit more information. It can be reopened once if that does surface.
