### ISSUE TITLE
Line height setting is no longer working on the front of the site

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#22555]
It seems the line-height setting is no longer reflected on the front of the site.

An extreme example to illustrate the issue:

**Editor**
<img width="1392" alt="Screenshot 2020-05-22 at 16 48 53" src="https://user-images.githubusercontent.com/908665/82685543-478b9900-9c4c-11ea-9dc2-46006cf6ec52.png">

**Front of the site**
<img width="1392" alt="Screenshot 2020-05-22 at 16 49 18" src="https://user-images.githubusercontent.com/908665/82685564-51150100-9c4c-11ea-9aaf-ad14e7d5c634.png">

It used to have an inline style for it, but I don't see it anymore.

**Comment by annezazu** [comment]
@iamtakashi Thanks for reporting this! I tried to replicate this issue but wasn't able to using Gutenberg 8.1.0, WordPress 5.4.1, and the TwentyTwenty theme. Here's what I tried:

- Tested with paragraph block
- Tested with heading block
- Tested with both heading and paragraph changing font size & line height

All displayed as expected in both interfaces. Here's a quick video of one of these tests: https://cloudup.com/cQN84x8Jmkb

Can you share more information about your particular setup? For example, WordPress version, Gutenberg version, theme, and any additional plugins on your site.

**Comment by iamtakashi** [comment]
@annezazu, thanks for your reply and looking into this. Much appreciated!

I was also using 8.1.0 and WordPress 5.4.1. But, after deactivating all the plugins and reactivating them seemed to resolve the issue for some reason, and I can't reproduce what I saw anymore :)

I'll keep an eye on it, I'll close this issue for now. Sorry about the noise!

**Comment by annezazu** [comment]
All good :D

**Comment by jamiepalatnik** [comment]
Reopening since I had a report of this in 21411419-hc and was able to reproduce on my test AT site using multiple themes. Could not reproduce on WordPress.com simple site. Reproduced on self-hosted site but deactivating plugins and reactivating seems to have resolved the issue.

Deactivating plugins and reactivating does not seem to resolve the issue on my test site, here are some screenshots: 

In editor: https://d.pr/i/T9g2Bz
Preview: https://d.pr/i/7ReB9e 

Discussed here: p1590528422405200-slack-wpcom-support

**Comment by iamtakashi** [comment]
@jamiepalatnik, after testing further, CoBlocks seemed to be the cause of this issue. When I disabled CoBlocks, the line-height setting start to work again. Is it possible to disable CoBlocks in AT site? 

I opened an issue in CoBlocks repo: https://github.com/godaddy-wordpress/coblocks/issues/1500

**Comment by jamiepalatnik** [comment]
Yes, it's possible. It looks like that fixed the issue for me too. Thanks so much!
