### ISSUE TITLE
Need class on PopUp Toolbar to detect if it has movers or editor has only one block.

### ISSUE THREAD

**Issue by ggedde** [WordPress/gutenberg#22558]
This is a Request to have some sort of class or css identifier on the popup toolbar to know if it is showing movers or not.

Maybe we add a class to is that says "has-movers"

Sure this can be done with JS, but adding the overhead and issues it might when updates get added is not the best solution. Instead this should be a simple css class on the toolbar.  Or possibly some css identifier on the editor when there is only one block shown which would indicate no movers.

I have been working on a Theme that utilizes Gutenberg and renders the editor exactly like the front-end to make the editing for the client extremely easy.  In doing so I needed to adjust the popup toolbar slightly, but when there is only one block shown the toolbar is not placed correctly now and I have no way with css to adjust it without it effecting other popup toolbars when there are multiple blocks.

https://github.com/WordPress/gutenberg/issues/22474

**Comment by youknowriad** [comment]
Did you consider using the `:has` CSS selector, I think it's now widely available.

**Comment by ggedde** [comment]
@youknowriad No, I didn't try that. I am no longer on that project, but if I get back to it I will try that now.
Thanks,
