### ISSUE TITLE
Table Block Frontend: Alignment classes are not added

### ISSUE THREAD

**Issue by carstenheisterkamp** [WordPress/gutenberg#2256]
## Issue Overview
In Version 0.7.1 adding a table Block and applying a layout / alignment via the block toolbar works in editor but not in the frontend. The according css classes are not added to the table class in the final frontend html.

## Steps to Reproduce (for bugs)
Assuming that some styling is applied to the css for the alignment styles (.alignleft etc.)

1. Add a table block to a post
2. Apply alignment (e.g. alignright or alignfull) to the table block.
3. Update or preview.

## Expected Behavior
The table gets the according class added in frontend html and is aligned according the selected alignment.

## Current Behavior
The tabel is not aligned  and the according class was not added to the frontend html

**Comment by WPDevHQ** [comment]
This is similar to what I'm having here: https://github.com/WordPress/gutenberg/issues/2240 - even though I've declared support as per docs: https://github.com/WordPress/gutenberg/blob/master/docs/themes.md

**Comment by karmatosed** [comment]
I think this goes a little deeper I am noticing this isn't happening for images and also for text backgrounds. I am going merge this into #2274
