### ISSUE TITLE
Queue up image edits to only apply once all edits are complete

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#22579]
Follow-up from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-623770557

> Wondering what would be a good way to handle multiple actions all at once, so normal editing operations do not have to "edit" the image and add new files. (The old image editor in WP "stores" the actions in an array (which also allows for easy undo/redo) and generates only a temp preview image. The actual changes are applied to the original image on save).

Similarly to the crop view, we might have an 'edit' view. We could apply each change on the frontend using the image transformations from #22566. Queue up the effects and have an apply button or even maybe only apply the transformations when the draft is saved or published. I'm not sure if it would be easy or even possible to have everything apply on save, but I think that could make for a better user experience.

**Comment by jasmussen** [comment]
Here are some designs. I don't love that they become "layered" like this, but it seems a good way to start the conversation.

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/1204802/83603724-36f4f000-a575-11ea-9d4a-bf98bea6ea1c.png">

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/1204802/83603760-483dfc80-a575-11ea-9954-909ee925652f.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/1204802/83603768-4b38ed00-a575-11ea-9377-8a5828cc93fa.png">
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/1204802/83603772-4c6a1a00-a575-11ea-980e-858f416d2e2a.png">

**Comment by ellatrix** [comment]
Done in #23284.
