### ISSUE TITLE
Apply image edits to largest available image size

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#22578]
Follow-up from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-623770557

> When saving, the changes should be applied to the largest image available, then all sub-sizes created. Currently changes seem applied to the "large" sub-size and cropped images end up only having "medium" and "thumbnail" sub-sizes, and being really small.

**Comment by Mamaduka** [comment]
I can no longer reproduce the issue. Probably fixed in the REST endpoint.
