### ISSUE TITLE
Columns block: No alignment classes in frontend

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#22584]
**Describe the bug**
The alignment options of the `core/columns` block aren't reflected by frontend classes.

**To reproduce**
1. Select a placed `core/columns` block.
2. Select wide or full align for that block.
3. Save and view the result in frontend.
Notice that the corresponding `alignwide` and `alignfull` classes are missing.

**Expected behavior**
Corresponding alignment classes (`alignwide`, `alignfull`) are applied on frontend.

**Editor version (please complete the following information):**
- WordPress version: `5.4.1`
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? `plugin`
- If the Gutenberg plugin is installed, which version is it? `8.1.0`

**Desktop (please complete the following information):**
 - OS: `Windows 10 x64 Pro`
 - Browser: `Chrome`
 - Version: `81.0.4044.138`

**Workaround:**
The `alignwide` or `alignfull` class has to be assigned manually to the block in the Gutenberg editor.

**Comment by carolinan** [comment]
Hi
I am not able to reproduce this. Did you try with a different theme and with all other plugins disabled?

**Comment by strarsis** [comment]
@carolinan: Well, it turns out that this was changed in a reusable block.
All posts/pages, that contain this reusable block must also be updated.
