### ISSUE TITLE
<img/> tags missing attribute filter

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#2258]
The <img/> HTML tags added to blocks are missing an attribute filter. The 'wp_get_attachment_image_attributes' filter should be applied to the image attributes for compatibility with WordPress.

**Comment by antpb** [comment]
From the media meeting yesterday @joemcgill mentioned "Gutenberg uses a different markup structure entirely with a different filtering process. I think we would be better off writing upgrade notes that explains how to do this correctly going forward, but am open to solutions that allow back-compat of the previous filter if we can come up with an approach."

I think with that, we can shift our focus on providing an upgrade path for folks that depend on the filter. What should they do now if we choose to not respect the filter?

**Comment by joemcgill** [comment]
Following up after we discussed this again in the Core Media meeting yesterday and after doing a bit more research this morning. Traditionally, image markup in the editor was composed server side, via `get_image_send_to_editor()` which uses `get_image_tag()` under the hood. Neither of these functions apply the `wp_get_attachment_image_attributes` filter, so this issue really isn't valid as described. The `wp_get_attachment_image_attributes` filter only applies to image markup that is dynamically generated on the front end, e.g., featured images, gallery shortcodes (see #1451), etc.

That said, supporting backward compatibility for filters like `image_send_to_editor`, `get_image_tag_class`, and `get_image_tag`, which previously _did_ provide a way for themes and plugins to modify the markup of images in the editor, would be a good goal for this ticket.

**Comment by danielbachhuber** [comment]
> That said, supporting backward compatibility for filters like `image_send_to_editor`, `get_image_tag_class`, and `get_image_tag`, which previously _did_ provide a way for themes and plugins to modify the markup of images in the editor, would be a good goal for this ticket.

For `image_send_to_editor`, see #8472

**Comment by joemcgill** [comment]
Ah, thanks @danielbachhuber, I'd missed that ticket. Since that already exists, I'm going to close this one and move the other to the 5.0 milestone for review.
