### ISSUE TITLE
Image editor as a `block-editor` component

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#22581]
In #21024 rich-image was implemented with block filters as its own "block" which modifies both the image block and the cover block.

Moving the feature as a `block-editor` component would allow the toolbar section to go wherever in each block it is applied to _and_ it would allow other block developers to take advantage of the rich image editing in their own blocks.

Doing it the old way had the benefit of being entirely decoupled from the block it is modifying. It was essentially an _overlay_ to the existing block. Unfortunately, this also meant that the editing tools could only be prepended or appended to the existing toolbar. It wasn't possible to put the rich image controls in-between the alignment and replace buttons. Furthermore, it limited the features to only the blocks which it specified. 

<p align="center"><img width="420" alt="image" src="https://user-images.githubusercontent.com/5129775/82717905-70b42580-9c5c-11ea-9eaf-ec7a2d05c5dc.png"></p>

**Comment by ellatrix** [comment]
Why does image editing have to be a component that wraps another block? It could be a component (controls, image etc.) to be used inside blocks?

**Comment by ajlende** [comment]
That's what I was trying to describe, but I wasn't very clear. The part about wrapping the block was to explain how it worked in #21024. I edited the description to hopefully make that more clear.

I added the `Discussion` tag to make sure that doing it as a component is preferable and that it should belong in the `block-editor` package.

**Comment by ellatrix** [comment]
It has now been moved to the image block in #23053.

**Comment by ajlende** [comment]
I still think the editor should be moved somewhere it can be reused. The original plan was for the image editor to also be in the cover block where it would also be useful, but I can imagine others using images wanting to be able to edit them as well. `@wordpress/block-editor` seemed like a reasonable place to put it rather than copying and pasting from one component to another.

**Comment by Mamaduka** [comment]
Resolved via #31607.
