### ISSUE TITLE
PHP notice related to register block style

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22587]
**Describe the bug**
if I register a block style using the PHP function [register_block_style,](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#register_block_style)
and I leave out the label property, there is a PHP notice:
`Notice: Undefined index: label in /var/www/html/wp-includes/script-loader.php on line 2557`

I believe the problem is in 
https://github.com/WordPress/gutenberg/blob/master/lib/class-wp-block-styles-registry.php#L43
where there is a check to see if the _name_ property is used, but not the _label_.

**To reproduce**
1. Activate the Gutenberg plugin
2. Register a block style in a theme or plugin file using register_block_style.
```
register_block_style(
    'core/quote',
    array(
        'inline_style' => '.wp-block-quote.is-style-blue-quote { color: blue; }',
    )
);
```
3. See the notice for the label, and the doing it wrong message for the name.

**Expected behavior**
Perhaps a doing it wrong message for the label would be suitable,
but, if I understand correctly, the label is not meant to be required. 
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#styles-optional

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Gutenberg plugin 8.1 or current master.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 83.0.4103.61

PHP version 7.3.13

**Comment by carolinan** [comment]
_I forgot to check without the plugin. -The notice is still there when Gutenberg is not active, so if anyone can confirm if the label is meant to be required or not, I can close and move the issue.

**Comment by skorasaurus** [comment]
label is required both in its [php form](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#server-side-registration-helper) as register_block_style and [in js](https://github.com/WordPress/gutenberg/blob/f2d3c09139ac13c17389dc5f12ca7fd45076abb1/packages/blocks/README.md) as registerBlockStyle .

What do you think should be the next action item for this issue?

**Comment by carolinan** [comment]
I have confirmed that the PHP notice is still present.

The label is also listed as required here: https://developer.wordpress.org/reference/functions/register_block_style/
-Docs could be improved since only style _or_ inline_style should be required.

Because the class is now in WordPress core, I opened a Trac issue instead, https://core.trac.wordpress.org/ticket/52592 and I am closing this issue.
