### ISSUE TITLE
Can't install WordPress Env in Manjaro

### ISSUE THREAD

**Issue by mewt** [WordPress/gutenberg#22616]
Hi I would like to test WP Env in my manjaro.

But I couldn't finish the installation because there is an error like below

npm install -g @wordpress/env
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/exaa/.npm/_logs/2020-05-26T05_19_13_389Z-debug.log

**Comment by talldan** [comment]
Hi @mewt. This seems like it might be a permissions issue with your `/usr/lib/node_modules` folder rather than something related to `wp-env` specifically.

Are you able to install other node packages using the `-g` flag?

**Comment by ajlende** [comment]
On Linux it's better to configure a different directory for global modules to be installed—one that you own. This can be done by using a node version manager (I use [n](https://github.com/tj/n), nvm will probably also work) or manually setting the npm's default directory.

More information at https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by youknowriad** [comment]
Closing as it seems to have received some good answers.

**Comment by mewt** [comment]
Thank you
