### ISSUE TITLE
editor.BlockDropZone filter removed

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#22618]
**Describe the bug**
#19514 converted the old `BlockDropZone` component to a hook (`useBlockDropZone`), but seems to have inadvertently removed the `editor.BlockDropZone` filter at the same time.

**To reproduce**
1. Try registering a filter for `editor.BlockDropZone`.
2. Observe that it is never triggered

**Expected behavior**
The filter continues to work as before

**Comment by youknowriad** [comment]
Seems like the ship has sailed for this one without real impact, I wonder if we should leave it as is.

**Comment by talldan** [comment]
@youknowriad #22619 removes it from the docs if we want to merge that and close this.

**Comment by youknowriad** [comment]
yes, i'm fine with that personally.
