### ISSUE TITLE
Switching between Edit Navigation and Manage Locations tab resets menu selection

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#22625]
**Describe the bug**
Switching between Edit Navigation and Manage Locations tab resets menu selection

**To reproduce**
1. Go to the new Navigation page
2. Select a different menu from the default one from the menu selector
3. Switch to the Manage Locations tab
4. Switch back to the Edit Navigation tab
5. The selected menu will revert back to the default (rather than the one selected in step 2)

**Expected behavior**
The previously selected menu remains selected

**Comment by talldan** [comment]
Sounds similar to #22340

**Comment by draganescu** [comment]
I think this is different from #22340 . The latter one is fixed by #22428 by using the correct operations to delete an entity. This here needs the selected menu state higher in the tree.

**Comment by annezazu** [comment]
Just nothing that I replicated this with Gutenberg 8.4.0 and WordPress 5.4.2. Changed to a bug rather than needing testing :)

**Comment by talldan** [comment]
Closing as the design has now changed. Manage Locations is now in a dropdown which resolves this issue.
