### ISSUE TITLE
Block: Title (2nd version)

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#22621]
### This issue creates a focus in relation to the older Block Title issue.

.
https://github.com/WordPress/gutenberg/issues/11553
There is a lot of discussion in the older issue that today is not valid any longer. Go to the above issue to see the history.

.

Associated issue.
Full Site Editing issue in relation to titles: 
Rethinking the "Current Document" display and settings
https://github.com/WordPress/gutenberg/issues/20877

----

Let's get the Post/Page title into a block. It is also one small step toward Full Site Editing, and how it uses the top bar for titles and drop downs. 

It could look similar to these mockups.

![Post:Page-Title-Block](https://user-images.githubusercontent.com/5323259/82881068-7f8e2700-9f3f-11ea-8e53-9bf3bd7cc14c.jpg)

![Post:Page-Title-Block-with-top-toolbar](https://user-images.githubusercontent.com/5323259/82881082-83ba4480-9f3f-11ea-8700-aa134c91bd2a.jpg)

**We still need to solve**
1. Getting the title into the top bar.

**Comment by mtias** [comment]
There is already a post-title block created: https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/post-title

It's used in contexts that can understand `wp_templates`.
