### ISSUE TITLE
Load last edited menu by default

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#22623]
**Describe the bug**
On the current nav-menus.php page, the last edited menu is selected by default when you load the nav-menus.php page. The same behaviour should be applied to the new experimental menus screen.

**To reproduce**
1. Go to Gutenberg > Navigation (experimental)
2. Select a different menu from the dropdown
3. Save the navigation
4. Leave the page
5. Return to Gutenberg > Navigation (experimental)

**Expected behavior**
The last edited menu should be selected by default

**Editor version (please complete the following information):**
- WordPress version: latest
- Plugin
- If the Gutenberg plugin is installed, which version is it? 8.2

**Comment by talldan** [comment]
It's debatable whether we want to replicate this behaviour, though I understand that it's a convenience feature for users.

Would be good to get some design feedback, and if we think it's a feature worth having it can be implemented.

**Comment by shaunandrews** [comment]
I'd expect it to work this way. Seems like it would be a solid improvement.
