### ISSUE TITLE
Explicitly state opt-in usage tracking is collected by Automattic on behalf of WordPress.org

### ISSUE THREAD

**Issue by christopherabalos** [WordPress/gutenberg#2262]
As of version 0.7.0, Gutenberg has opt-in usage tracking. I'm sure it's much needed for a project of this scope. However, can the "More info" tooltip be updated to explicitly state where the data is being sent and who owns it? I don't feel a Make WordPress Core blog post is sufficient disclosure, especially for users who never interact with the Core blog.

Also, can we define "completely anonymous"? Are IP addresses, referer and/or domains being stored? While technically considered anonymous data, they can be used in conjunction with other data to determine identity.

**Comment by aaronjorbin** [comment]
Additionally, is the collection code open source so people can verify that it is anonymous? If not, can it be?
