### ISSUE TITLE
There is no user feedback when the menu locations are saved

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#22627]
**Describe the bug**
There is no user feedback when the menu locations are saved

**To reproduce**
1. Go to Gutenberg > Navigation (beta)
2. Click the Manage locations tab
3. Click 'Save'
4. Notice there is no feedback to say the save process has been successful/failed

**Expected behavior**
A snackbar notice would appear to say the locations have been saved successfully (or otherwise)

**Editor version (please complete the following information):**
- Gutenberg 8.2 plugin

**Comment by alita-moore** [comment]
I'd like to solve this issue
