### ISSUE TITLE
Removing a Template Part dirties the entity state with inner content removed.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#22638]
**Describe the bug**
Removing a Template Part from a page results in the Template Part edited to clear all inner content.  This is a 'recent' regression in behavior.  @noahtallen mentioned this is likely related to a recent PR of his (#21368 ).

**To reproduce**
1. Go to an Edtior (shown below is page editor) with full site editing experiment enabled.
2.  insert a Template Part.
3. remove the template part.
4. notice the template part is 'dirty' in the save panel, and re-inserting will result in an empty template part.

**Expected behavior**
Expect the template part to not be dirtied on removal.

**Screenshots**

![deleting-template-part-bug](https://user-images.githubusercontent.com/28742426/82930194-fda7f900-9f52-11ea-9a9d-b21d2c02940b.gif)

**Comment by noahtallen** [comment]
Now that I think about it, #22586 wilil resolve this! 🥳 

This is what causes the bug:

1. Removing the block triggers the remove block action in the block-editor store
2. The block-editor store removes all inner blocks of the given block
3. The `useBlockSync` hook for the the template part sees all of its inner blocks being removed and syncs those changes to the controlling entity.
4. The template part entity's content is wiped, triggering the dirty state (and saving will persist the wipe)
5. The `useBlockSync` hook "unsubscribes" now that the block associated with it is not in the editor.

So the solution is to "unsubscribe" from the changes a lot earlier. @epiqueras caught this as well in #22586, which cleans up that lingering subscription before it has a chance to cause issues.

**Comment by Addison-Stavlo** [comment]
Oh Nice!  Im glad this has already been noticed and has a solution 😄
