### ISSUE TITLE
wp-scripts start exited with code 0 after npm run dev

### ISSUE THREAD

**Issue by mdmag** [WordPress/gutenberg#22645]
**Describe the bug**
After Removing `package-lock.json` and `node_modules` then `npm run dev`,  `wp-scripts` builds the files one time only and results in having this notice `wp-scripts start exited with code 0 ` .It doesn't watch the files any more.
**To reproduce**
1. `rm -rf package-lock.json`
2. `npm cache clear --force`
3. `rm -rf node_modules && npm install`
4. `npm run dev`
5. In terminal, a notice will appear: `wp-scripts start exited with code 0`

**Expected behavior**
`npm run dev` should still work and watch files correctly

**Screenshots**
<img width="931" alt="Screen Shot 2020-05-26 at 9 53 10 PM" src="https://user-images.githubusercontent.com/65375623/82944358-57ccac80-9f9b-11ea-8248-79a56acb38ac.png">

- If the Gutenberg plugin is installed, which version is it? [8.1.0]
**Desktop (please complete the following information):**
 - OS: [MacOs]

**Comment by ellatrix** [comment]
Have you tried restarting Docker? I remember having problems with `npm run dev` too caused by Docker.
