### ISSUE TITLE
Accessing Wordpress' Rest Api in development

### ISSUE THREAD

**Issue by creativiii** [WordPress/gutenberg#22648]
I'm developing a Gutenberg plugin. Currently running it locally with wp-env.

Everything seems to work fine but wp-env doesn't seem to have the usual Rest Api at `http://localhost:8888/wp-json/wp`.

Is this intended? Any way to activate it?

How do I know that my block's data is being saved and displayed properly? If there's a workaround to achieve this without looking at the Rest API that would also be good enough.

**Comment by talldan** [comment]
@creativiii This may be a configuration thing or an environment limitation, but it's not any area that I'm knowledgeable in.

I notice most REST API requests in wp-env when looking at the debugger are via `http://localhost:8888/index.php?rest_route=%2Fwp%2Fv2%2Fposts%2F597%2Fautosaves&_locale=user`

**Comment by creativiii** [comment]
> @creativiii This may be a configuration thing or an environment limitation, but it's not any area that I'm knowledgeable in.
> 
> I notice most REST API requests in wp-env when looking at the debugger are via `http://localhost:8888/index.php?rest_route=`
> 
> e.g. `http://localhost:8888/index.php?rest_route=%2Fwp%2Fv2%2Fposts%2F597%2Fautosaves&_locale=user`

You're a saint!
```
http://localhost:8888/index.php?rest_route=/wp/v2/posts/1
```
This works.
