### ISSUE TITLE
Allow themes to specify default font weight for headings.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#22641]
Currently, when using Gutenberg's default editor styles, the "Bold" option for the Header block has no effect: 

![Screen Shot 2020-05-26 at 2 17 05 PM](https://user-images.githubusercontent.com/1202812/82935963-db66a900-9f5b-11ea-99cc-3227962d3cf3.png)

![Screen Shot 2020-05-26 at 2 16 59 PM](https://user-images.githubusercontent.com/1202812/82935975-de619980-9f5b-11ea-88f1-ace12de8ae64.png)

This is because the heading is already bold by default. 

A similar issue exists in Twenty Nineteen and Twenty Twenty too — they both use bold headings by default. They both  have it so that when you select "Bold", the themes swap the default 700 weight for a 600 weight (effectively making the text _less_ bold when bold is turned on). 

Bold headings are a super-common pattern (it's even the browser default), so it would be excellent if Gutenberg could be smarter about this. Would it be possible to: 

- Default to "Bold" being active here, and have a class added if the text is _not_ bold? 
- Allow themes to specify somehow what their default weight is?

The resolution to this may be just to wait for Global Styles, but I wanted to highlight this specifically, since it's come up in many themes.

**Comment by getdave** [comment]
I just hit this issue when working on the WP.org Make Blog. I assume it's fairly complex to fix?

**Comment by mtias** [comment]
This is supported through global styles UI now.
