### ISSUE TITLE
A pull request didn't didn't pass a test 

### ISSUE THREAD

**Issue by DOUARA** [WordPress/gutenberg#22651]
It has been 12 days since I added a pull request for a feature that I have developed: 
https://github.com/WordPress/gutenberg/pull/22372 

It appears that the commit didn't pass a specific test here: 
https://travis-ci.com/github/WordPress/gutenberg/builds/166156925

It appears that it didn't accept adding a new attribute to the "latest posts" block, it was required for this feature so I have just added it 

I am new to contribution would someone explains to me what I can do about it?

**Comment by talldan** [comment]
I'll add some comments to the PR
