### ISSUE TITLE
CMB2 WordPress hooks (per: #952 #issuecomment-320523428)

### ISSUE THREAD

**Issue by jtsternberg** [WordPress/gutenberg#2265]
**CMB2**
---
Re: https://github.com/WordPress/gutenberg/issues/952#issuecomment-320523428, The relevant hooks for posts, not comments/users/other types supported by CMB2. I believe it is safe to assume that Gutenberg is only slated for post objects?

1. CMB2 initiation is hooked late to `init` 
2. Metaboxes are registered via: `add_meta_boxes`, or output directly via `edit_form_before_permalink`, `edit_form_after_title`, `edit_form_after_editor`
3. They are saved via the `save_post` hook.
4. Styles are registered/enqueued via `admin_enqueue_scripts` hook.
5. Scripts are registered/enqueued via `admin_enqueue_scripts` and `admin_footer`

Also important to note, `CMB2` relies on the `$pagenow` global to determine which context it is in.

**Comment by jeffpaul** [comment]
Per today's Gutenberg [bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1516295704000110), we're going to close this with a note that we can re-open it if there is still a problem.
