### ISSUE TITLE
Block Editor: Allow a theme to override settings per block for editor features

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#22657]
## Description

Related to #22622.

Follow up for #22291 where initial handling for block editor features were introduced.

Usage:

```js
// edit.js

const Edit = ( props ) => {
    const isDisabled = ! useEditorFeature( 'typography.dropCap' );
    // ...
};
```

Based on that idea, it included block level overrides for features using the following definition of the block:

```js
registerBlockType( 'my/block', {
    supports: {
        __experimentalFeatures: {
            typography: {
                dropCap: true,
            }
        },
    },
    // ... everything else
} );
```

The idea is to take it to the next level – a theme should be able to disable any editor feature for the selected block using `experimental-theme.json` config file specific for the theme.

The full proposal from @nosolosw in https://github.com/WordPress/gutenberg/pull/22291#pullrequestreview-418481941.

**Comment by youknowriad** [comment]
how is this different from #22655

**Comment by gziolo** [comment]
We can consolidate into one if your prefer. The difference is that:
- this PR – individual block level
- #22655 - global level - all blocks affected
