### ISSUE TITLE
Block Editor: Improve sharing setting for features between the client and server

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#22658]
## Description

Proposed in https://github.com/WordPress/gutenberg/pull/22291#pullrequestreview-418481941 by @nosolosw:

> See how we can consolidate `lib/experimental-default-theme.json` and `block-editor/src/store/defaults.js`.

There is some duplications between:

https://github.com/WordPress/gutenberg/blob/c31475afc9fc149262da67c7464d5f4a527eb93a/lib/experimental-default-theme.json

and

https://github.com/WordPress/gutenberg/blob/c31475afc9fc149262da67c7464d5f4a527eb93a/packages/block-editor/src/store/defaults.js

The concerning part is how we source default values in the block editor on the client. We literally duplicate the same settings that exist on the server. It's hard to tell if they are still in sync.

If we decide to use JSON format for the default global settings on the server, we could as well find a way to source them from the same file.

**Comment by gziolo** [comment]
@nosolosw – is it something that is already resolved and thus can be closed?

**Comment by nosolosw** [comment]
At the moment, we still duplicate the values because the server part won't be part of 5.6, hence the block-editor needs that data. Let's revisit for 5.7.
