### ISSUE TITLE
document setting to add class to post_class

### ISSUE THREAD

**Issue by cramdesign** [WordPress/gutenberg#22678]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
I would like an advanced section in the document settings sidebar, similar to the advanced settings for some blocks, that would allow for css classes to be attached to the page. These classes should output within the `post_class()` function.

**Describe alternatives you've considered**
The post class function already outputs several classes that are useful. Also, a page template could be used to get the specific class I want. However, having this option would be more useful and flexible.

**Comment by noisysocks** [comment]
Hi. Thanks for the issue. It's a nice idea, but I think the usage is too limited and technical to be included in Core where we try to design for the majority.

A plugin could add this functionality by making use of `PluginDocumentSettingPanel ` to add a new text field to the document sidebar, post meta to store the text that is entered, and then the `post_class` filter to output the text that is stored in post meta.

https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-document-setting-panel/
https://developer.wordpress.org/reference/functions/register_post_meta/
https://developer.wordpress.org/reference/hooks/post_class/
