### ISSUE TITLE
Gallery Block does not link to full image under some circumstances

### ISSUE THREAD

**Issue by mtoensing** [WordPress/gutenberg#22675]
**Describe the bug**
The Gallery Block does generate a list of images. Each image links to the image url, image page or nothing at all depending whats specified in the block settings. All my blocks link to the same image size that is specified in the blocks settings but not to the full image. 

If I add a new gallery block to the article and add all images again it works as intended: The specified image size is used and the link points to the full image. 

Settings for both galleries: 

- Link to media file
- medium image size

How can the use (e.g. me) change that behaviour for existing blocks? I use gallery blocks since the first release and maybe that is the reason I have that problem. 

Here is the HTML of a working and not working block: 
Added as file attachments.

[block html.zip](https://github.com/WordPress/gutenberg/files/4689011/block.html.zip)

<img width="1155" alt="Screen Shot 2020-05-27 at 15 30 06" src="https://user-images.githubusercontent.com/136737/83024645-fa823b00-a02e-11ea-8a46-d223c3874575.png">

**To reproduce**
1. Existing gallery block in any article. 
2. Add new gallery block
3. Add the same images
4. It works. Old block does not work

**Expected behavior**
Old gallery blocks should behave the same as newly added ones.

**Screenshots**
I provided html code of blocks

**Editor version (please complete the following information):**
Most recent Gutenberg version. No addiditonal plugins. Tested it in my local server with no plugins involved. 

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by skorasaurus** [comment]
This may be a duplicate of #13851 ; in that the existing gallery images do not link to full images, but news one do.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. If the gallery block isn't linking to the full image in older galleries that you made, and not ones as you stated; it is being tracked at #13851 where you can follow its progress.
