### ISSUE TITLE
Auto-save is unreliable

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2268]
## Issue Overview
I'm finding that the auto-save feature is not reliable. I just added some text to a Paragraph block and waited over 10 minutes (yes, I timed it with a stopwatch), and the page still hadn't auto-saved my changes.

## Steps to Reproduce (for bugs)
Add content to a Paragraph block.
Click out of the block and wait to see if page auto-saves

## Expected Behavior
I would expect the page to auto-save after adding content to a new block, or at the very least, at a set interval of less than 10 minutes.

## Current Behavior
Content not getting auto-saved regularly

Plugin **Version 0.7.1**

**Comment by aduth** [comment]
Since I'm not able to reproduce, could you share a few more pieces of information?

- When clicking out of the paragraph block, do you see the "Save Draft" link appear in the header?
- Are you editing a new post, or an existing post?
- What is the browser / operating system you're using?

**Comment by maddisondesigns** [comment]
> When clicking out of the paragraph block, do you see the "Save Draft" link appear in the header?

Nope. I was watching the page all the time and there was never any message displayed that indicated that the document had saved

> Are you editing a new post, or an existing post?

I was editing a Page (not a Post). The page was Published and was one that I created an hour or so earlier. I simply added another sentence to a Paragraph block.

> What is the browser / operating system you're using?

I'm using Firefox 54.0.1 (64-bit) on MacOS Sierra v10.12.1 (16B2657) and WordPress 4.8.1

**Comment by karmatosed** [comment]
@maddisondesigns hi there. I am having a little difficulty in replicating this myself. Would it be possible to show a video and maybe see if you get any console errors?

**Comment by aduth** [comment]
Is the page you're editing already published? Published autosave is not yet implemented, tracked at #1773 pending missing REST API requirements.

**Comment by maddisondesigns** [comment]
Ahhh ok. Yep, the page was already published so I guess that explains it.

Thanks.

**Comment by aduth** [comment]
In that case, going to close in favor of #1773. Thanks for the detailed report though.
