### ISSUE TITLE
Gutenberg uses all sockets in Chrome/Edge

### ISSUE THREAD

**Issue by lkhrs** [WordPress/gutenberg#22688]
**Describe the bug**
When editing a WordPress website using Gutenberg (using either the stock install or with the Gutenberg plugin installed) in Chrome or Blink-based Edge, refreshing any page on the site will cause the page to be stuck loading forever with a status message of "Waiting for available sockets" in the bottom left corner. The only solution is to restart the browser until it happens again.

Firefox works fine without any issues.

**To reproduce**
1. Open a page or post in Gutenberg
2. Save the post or page via the "Update" button 3-6 times
3. Refresh the editor or open the edited page
4. See error "Waiting for available sockets" status in the bottom left of the browser

**Expected behavior**
Load the page

**Screenshots**
![image](https://user-images.githubusercontent.com/1342461/83088512-8610c180-a059-11ea-98b1-5b7e90dfbc5c.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin" or "default"
- If the Gutenberg plugin is installed, which version is it? Latest 8.2.0 (and the default editor)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Manjaro Linux
 - Browser Chrome, Microsoft Edge using Blink
 - Version Stable and Dev

**Additional context**
I've searched and found a [reddit post](https://www.reddit.com/r/Wordpress/comments/ebo54b/constant_issue_with_waiting_for_available_socket/) and a [stackoverflow post ](https://stackoverflow.com/questions/60042585/chrome-waiting-for-available-sockets-firefox-is-fine)about the same issue.

Clearing socket pools does not solve the issue and I have to restart the whole browser to continue.

**Comment by lkhrs** [comment]
I will also note that I tested on a vanilla install with the same results. Server stack: Ubuntu 18.04 LTS nginx with php-fpm and MariaDB.

**Comment by talldan** [comment]
@lkhrs Thanks for reaching out. This isn't something that I've experienced over quite a long period of using the editor in Chrome. 

The editor only uses HTTP requests, so any socket connections would be short-lived.

Are there any plugins you have installed that might be causing this?

It's also worth checking for any suspect network activity in the browser dev tools? There's a guide here to debugging network requests if it's something you're not familiar with:
https://developers.google.com/web/tools/chrome-devtools/network/

**Comment by lkhrs** [comment]
@talldan I tried again this morning on my vanilla install and wasn't able to reproduce the issue, strange.

However, on one of my sites, disabling WooCommerce seems to have made the issue go away.

**Comment by macropin** [comment]
@talldan What information do you specifically require. I have a customer that is reporting this issue:

> "issue only seen in Chrome which occurs in most cases after/around the 6th save while editing a page. On the 6th/7th save, the website stalls and keeps loading with the message on the bottom left of the browser - waiting for available socket..."

**Comment by talldan** [comment]
@macropin I don't think it has yet been established that this is an issue with Gutenberg.

I think the next step is to do some more testing and try to establish what commonalities there are amongst the WordPress installs that have this issue.

Issues like this are often hard to track down, but it might be good if those with the issue could mention what plugins they have installed.

> It sounds like Gutenberg is not closing socket connections and eventually they are exhausted (limit of 6).

Not sure that could be possible. As far as I know, the code here uses `window.fetch` (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to make requests, generally to the WordPress REST API. That's a pretty high-level browser API that doesn't offer control over sockets.

**Comment by talldan** [comment]
@macropin Going on the WooCommerce mention from @lkhrs and the reddit conversation in the description, I did some more digging and found this issue:
https://github.com/woocommerce/woocommerce/issues/26474

This is describing the same problem (preview triggers a save). The reporter hints that this is a Chrome bug, but that changes to the request when saving a post by the WooCommerce plugin are specifically causing it to trigger.

I'd suggest moving the conversation over to that issue as it looks like nothing can be done here. I'll close this issue.

**Comment by caluwaek** [comment]
@talldan  I'm not using Woocommerce.  As for plugins installed : Akismet, Assec Cleanup, Classic Editor, Content Views Pro, Easy Digital Downloads, Polylang, Tablepress, WP Rocket, Yoast.

I should add that this only occurs on the test version of the site, not on our production copy.  The issues started occurring after I switched the settings of the classic editor to enable Gutenberg.

**Comment by talldan** [comment]
Ok, let me reopen this. This does sound like you have an issue with the requests for saving posts not completing in your test environment.

Potentially, the editor should also avoid making more save requests if there are already in progress requests, so there may be some improvements we can make to the code base.

**Comment by oxyc** [comment]
I can reproduce this with clicking Update ~6 times in a row my own test environment.

<img width="721" alt="Screen Shot 2020-06-19 at 10 47 04" src="https://user-images.githubusercontent.com/302736/85139442-cd364080-b21a-11ea-9dad-bed4d37864db.png">

Seems the sockets are not closed and afaik 6 is chromes limit. Might be some misconfiguration with my webserver though.

**Comment by oxyc** [comment]
I figured out it came from a custom Cache Control header I set on my test environments.

```apache
  <IfModule mod_expires.c>
    Header set Cache-Control "max-age=0, no-cache, no-store must-revalidate"
    Header set Pragma "no-cache"
    Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
  </IfModule>
```

Just removing the `no-store` fixes it for me (this has been bugging me for years on a bunch of projects). Do you have any custom additions to your `.htaccess`?

**Comment by caluwaek** [comment]
I've checked my .htaccess file.  Cache-Control is set to public in my case.

**Comment by oxyc** [comment]
Could you take a screenshot of the _Response headers_ of a XHR request while it's still succeeding?

<img width="1440" alt="Screen Shot 2020-06-19 at 12 26 49" src="https://user-images.githubusercontent.com/302736/85149934-45573300-b228-11ea-8a8e-c2c594c0512e.png">

**Comment by caluwaek** [comment]
Here is a screenshot.  I noticed I have the same cache-control no-store.  I just don't know where it comes from because I see it nowhere in htaccess.

![image](https://user-images.githubusercontent.com/22346073/85153225-3ab39280-b256-11ea-9baa-5f8fbf96fcd8.png)

**Comment by oxyc** [comment]
You could check if there's a plugin adding it by running this in the project:

```sh
grep -r --include '*.php' 'no-store' .
```

If there's any plugin setting it, try disabling the plugin.

**Comment by michaelignacio** [comment]
I've been experiencing this issue on Chromium based browsers (Google Chrome, Brave browser) for a long time now. I've already made a mental note to use Firefox everytime I'm making a lot of changes on the Wordpress backend, as it doesn't happen on Firefox.

It might be worth noting that everytime I experience this issue, it's:
- whenever I'm using Google Chrome or Brave
- working on a local website using [Local Lightning](http://localwp.com/)
- making a lot of Save/Publish actions on the backend

**Comment by AaronNewcomer** [comment]
I get the same issue as well. I use the default wordpress configuration Laravel Forge sets up using nginx.

**Comment by oxyc** [comment]
@AaronNewcomer @michaelignacio could you check the response headers for the requests and look for "no-store" in cache control. Like https://github.com/WordPress/gutenberg/issues/22688#issuecomment-646698231

So far this was the cause for 3 users in this issue.

**Comment by michaelignacio** [comment]
https://i.imgur.com/k95uD0A.png
https://i.imgur.com/6b9qcg4.png

**Comment by michaelignacio** [comment]
@oxyc Are you referring to this? 

https://i.imgur.com/k95uD0A.png
https://i.imgur.com/6b9qcg4.png

**Comment by oxyc** [comment]
Yes, that's what caused it here https://github.com/WordPress/gutenberg/issues/22688#issuecomment-646671233), https://github.com/WordPress/gutenberg/issues/22688#issuecomment-646711079 and also WooCommerce users https://github.com/woocommerce/woocommerce/issues/26474.

If you can figure what is setting it, it should get fixed.

**Comment by palbera** [comment]
Hi guys, is there any evidence in this issue?

I'm facing with the same problem here with this configuration:

1. Chrome - latest build - i tried even with Canary but the issue persists 
2. Gutenberg
3. Woocommerce

I checked these 2 scenarios:

1. Chrome + woocommerce disabled == the issue seems gone away
2. Brave + woocommerce enabled == everything worked fine

In my opinion is something related to **Chrome** and **woocommerce**

Best

**Comment by oxyc** [comment]
@palbera did you check if you have a `no-store` cache header? https://github.com/WordPress/gutenberg/issues/22688#issuecomment-653305147

**Comment by talldan** [comment]
WooCommerce modifies requests to add the `no-store` value as tracked in this issue - https://github.com/woocommerce/woocommerce/issues/26474

**Comment by palbera** [comment]
> @palbera did you check if you have a `no-store` cache header? [#22688 (comment)](https://github.com/WordPress/gutenberg/issues/22688#issuecomment-653305147)

Yep `no-store` is there in the header response

**Comment by zfeezy** [comment]
Thanks all @here, and fyi to anyone working on this -- the no-store issue from above was my culprit too, but it isn't only WooCommerce. In my case it was the WP Migrate DB plugin. So... check your plugins!

**Comment by caluwaek** [comment]
@zfeezy Thanks, for the tip.  I've disabled WP Migrate DB.  I couldn't pinpoint where this problem was on my end but I do have this plugin.  Let's hope deactivating it solves this frustrating issue.

**Comment by celik75** [comment]
Also have this problem, to prevent is use max 2 tabs of your website, if 1 tab is using gutenberg.
Happens only with gutenberg

**Comment by Mamaduka** [comment]
Hi, everyone

This issue came up during recent Editor bug scrubs.

I followed the testing instructions and couldn't reproduce the issue. However, based on recent comments, it looks like an issue caused by the `no-store` cache header added by third-party plugins.

I'm going to close the issue, but feel free to re-open it if this is something we can fix inside the Gutenberg plugin.
