### ISSUE TITLE
Reusable blocks allow nesting the identical block

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#22691]
**Describe the bug**
If you edit a reusable block, you are allowed to add this reusable block inside it. This leads to a recursion loop and breaks the whole editor.

**To reproduce**
1. Create a new reusable block with a simple paragraph.
2. Save the reusable block as “Test Recursion”.
3. Add a new block to this reusable block and select the “Test Recursion” reusable block.
4. Update the reusable block.

**Expected behavior**
An error occurs and the reusable block doesn’t update. Or even better in my opinion: Don’t allow inserting the identical block in a reusable block.

There is an error while updating, but as soon as you reload the edit page, you cannot access the post content anymore and instead, have either a blank page or the following error message:

```
Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting!
in /Users/matze/dev/webroot/wp/wp-content/plugins/query-monitor/classes/Backtrace.php on line 57

Call stack:

QM_Backtrace::__construct()
QM_Timer::start()
QM_Collector_Block_Editor::filter_render_block_data()
WP_Hook::apply_filters()
apply_filters()
render_block()
do_blocks()
render_block_core_block()
WP_Block_Type::render()
render_block()
do_blocks()
render_block_core_block()
WP_Block_Type::render()
render_block()
do_blocks()
render_block_core_block()
WP_Block_Type::render()
…
```

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Comment by ntsekouras** [comment]
Thanks for reporting this @KittMedia!

I'm closing this issue as is duplicate with this: https://github.com/WordPress/gutenberg/issues/22131. You can track the progress there.
