### ISSUE TITLE
Streamlining the process when making a website with post types that require meta data

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#22709]
We have been trying to adopt the Gutenberg ways now for a year and are still struggling to understand how to let our clients input certain data.

We make custom websites with custom themes and were happy with WordPress as a CMS. Gutenberg looks really cool and for simple articles and pages it works nicely. However it has become somewhat confusing to know what data should go where and how. The Gutenberg editor takes over the entire screen and becomes an experience that is great _when no extra metaboxes are needed_.

However suppose I have a new post type "event" where I need the client to enter a start and end date. We used to create metaboxes for this and have them show up right before the tinyMCE editor. Clients saw this and new what to do. It was simple and gave a good user experience.

Now it's not so simple. Creating metaboxes puts them out-of-site either at the very bottom of the screen or in a sidebar that is growing and growing with collapsable sections and a document tab and a block tab... and the start and end date are quite important for them to be some other collapsable tab.

**How about creating a block for them?**

We can do that, but does the start and end date belong in the content? We would somehow have to remind the client to add that block every time. (Although I am learning just now that I can force some blocks on some post types). And we can no longer just output the content using the_content(); we would have to loop through the blocks and skip over this block because it's not meant to show up here in the middle of the events text.

Should I be using the classic editor with this post type? Isn't WordPress moving away from even having the classic editor eventually? What is the proper way to do things like this?

**Comment by saltnpixels** [comment]
...I've posted in a few places... no one seems to know the right answer to this... 
how will WordPress deal with this when it comes to their own plugins like Woo Commerce? Where they have a product post type?

**Comment by azaozz** [comment]
> We used to create metaboxes for this and have them show up right before the tinyMCE editor. Clients saw this and knew what to do.
> ...
> Now it's not so simple. Creating metaboxes puts them out-of-site either at the very bottom of the screen or in a sidebar

Guessing the sidebar is a good place for such settings. You're right, the setting would not be "front and center", and would be hidden when a block is selected, but will show when starting a new post/event, and perhaps can add some CSS/background color to make is "stand up" more.

Alternatively, I believe (but may be wrong) you can make a dynamic block that is "required" for the post type. Then get it to save the data in post meta. Dynamic blocks are rendered on the server, so saving the data in different place(s) would work.

**Comment by saltnpixels** [comment]
I guess, but those feel like bandaids.

The problem is that not every post type is a straight down page or article. Some have and need custom meta data.

**Comment by tellthemachines** [comment]
> **How about creating a block for them?**
> 
> We can do that, but does the start and end date belong in the content? We would somehow have to remind the client to add that block every time. (Although I am learning just now that I can force some blocks on some post types). And we can no longer just output the content using the_content(); we would have to loop through the blocks and skip over this block because it's not meant to show up here in the middle of the events text.

@saltnpixels have you looked into using [block templates](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/) to pre-fill the editor with the necessary blocks? You could also create some custom blocks that don't render any content in the front end, just to save that data. That way you wouldn't have to hack the content loop at all.

Let me know if this helps!

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
