### ISSUE TITLE
Block Directory: Ensure scripts can depend on another script handles

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#22703]
## Description

As of today, it's possible to install blocks listed in the Block Directory using the scripts returned by the API. However, the limitation is that those scripts can depend only on script handles that are used by the block editor. The idea is that it should be also possible to use custom script handles for those scripts and there would be a way to inject them on the frontend.

## Related

Related Trac ticket: [Consider a solution/endpoint to lazy-load scripts and styles](https://core.trac.wordpress.org/ticket/48654)
Proposed REST API endpoints: https://github.com/WordPress/gutenberg/pull/21244

**Comment by spacedmonkey** [comment]
Something like this could work really well
```
add_filter( 'script_loader_tag', function( $tag, $handle ){
   $tag = str_replace( '<script ', '<script data-handle="'.handle.'" ', $tag );
   return $tag;
});
```

**Comment by StevenDufresne** [comment]
What would be an example scenario that we are prepping for?

**Comment by ryelle** [comment]
I think this is not an issue anymore after #22721/#23407 and #24117 — assets are pulled from a separate editor page so that all dependencies and inline scripts are loaded. If I'm misunderstanding the original issue, it can be reopened.

**Comment by gziolo** [comment]
Sounds good. I haven't seen some of the PRs referenced. If there is more work necessary, we can always file a more targeted issue.
