### ISSUE TITLE
Consolidate the style attributes of blocks

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#22700]
We're exploring a solution that allows a block to declare a set of style attributes it supports, which are usually referred to as the _style attributes_ of the block. The Block Editor uses this data to auto-generate InspectorControls for them, as well as enabling their use in `experimental-theme.json`.

A block would declare support for these style attributes via its `block.json`. See [example from the paragraph block](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/paragraph/block.json#L29):

```
{
  "name": "core/paragraph",
  // ...
  "supports": {
    "__experimentalColor": true,
    "__experimentalLineHeight": true,
    "__experimentalFontSize": true,
  }
}
```

which means that the paragraph block has support for color, line-height, and font-size.

This master issue keeps track of this work.

### Colors

| Context | Text | Background | Gradient | Link |
| --- | --- | --- | --- | --- |
| global https://github.com/WordPress/gutenberg/issues/21032 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/button | | | | |
| core/columns https://github.com/WordPress/gutenberg/pull/21038 https://github.com/WordPress/gutenberg/pull/21375 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/cover | | | |
| core/group https://github.com/WordPress/gutenberg/pull/21021 https://github.com/WordPress/gutenberg/pull/21375 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | ✔️ | ✔️|
| core/heading https://github.com/WordPress/gutenberg/pull/21039 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | | ✔️| 
| core/list https://github.com/WordPress/gutenberg/pull/21387 |  | | | | 
| core/media-text https://github.com/WordPress/gutenberg/pull/21169 https://github.com/WordPress/gutenberg/pull/21375 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/paragraph https://github.com/WordPress/gutenberg/pull/21037 https://github.com/WordPress/gutenberg/pull/22722 | ✔️ | ✔️ | | ✔️ |
| core/post-author https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/post-comments https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/post-comments-count https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | | 
| core/post-comments-form https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/post-content https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-date https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | | 
| core/post-excerpt https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/post-tags https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | ✔️ | 
| core/post-title https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | | 
| core/pullquote | | | |
| core/quote | | | |
| core/site-tagline | ✔️ | ✔️ | ✔️ | |
| core/site-title https://github.com/WordPress/gutenberg/issues/21087 | ✔️ | ✔️ | ✔️ | |

### Typography

| Context | Font Size | Font Family | Font Weight | Line Height |
| --- | --- | --- | --- | --- |
| global https://github.com/WordPress/gutenberg/issues/21030 https://github.com/WordPress/gutenberg/issues/21028 https://github.com/WordPress/gutenberg/issues/20773 | ✔️ |  |  |  |
| core/columns |  |  |  |  |
| core/cover |  |  |  |  |
| core/group |  |  |  |  |
| core/heading https://github.com/WordPress/gutenberg/pull/21215 https://github.com/WordPress/gutenberg/pull/21431 | ✔️ |  |  | ✔️ |
| core/list |  |  |  |  |
| core/media-text |  |  |  |  |
| core/paragraph https://github.com/WordPress/gutenberg/pull/20775 https://github.com/WordPress/gutenberg/pull/21153 | ✔️ |  |  | ✔️ |
| core/post-author https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-comments https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-comments-count https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-comments-form https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-content https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-date https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-excerpt https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-tags https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/post-title https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |
| core/pullquote |  |  |  |  |
| core/quote |  |  |  |  |
| core/site-tagline | ✔️ |  |  | ✔️ |
| core/site-title https://github.com/WordPress/gutenberg/issues/21087 | ✔️ |  |  | ✔️ |

### Spacing

| Context | Margin | Padding |
| --- | --- | --- |
| global https://github.com/WordPress/gutenberg/issues/20771 |  | |
| core/columns |  |  |
| core/cover https://github.com/WordPress/gutenberg/pull/21492 |  | ✔️ |
| core/group https://github.com/WordPress/gutenberg/issues/14747 |  | |
| core/heading |  |  |
| core/list |  |  |
| core/media-text |  |  |
| core/paragraph |  |  |
| core/post-author https://github.com/WordPress/gutenberg/issues/21087 | | | | | 
| core/post-comments https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-comments-count https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-comments-form https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-content https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-date https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-excerpt https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-tags https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/post-title https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/pullquote |  |  |
| core/quote |  |  |
| core/site-title https://github.com/WordPress/gutenberg/issues/21087 | | | | |
| core/site-tagline | | | | |

**Comment by jffng** [comment]
Thanks for opening this!

When you mark a block's style attribute ✔️in this issue, does that also mean that there's support for modifying those attributes via `experimental-theme.json` styles and features functions?

**Comment by nosolosw** [comment]
Yes, that's the idea. Although I've realized that, as of today, background (gradients) & background-color (solid) are missing from `experimental-theme.json`. TLDR: I forgot to add them when we had that manual list hard-coded.

The good news is that I'm now working on https://github.com/WordPress/gutenberg/pull/22698 which removes that manual list and pulls data directly from the blocks, which wasn't possible at the time, hence enabling backgrounds.

I've clarified the issue description.

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/22722 added support for link color the following blocks: paragraph, heading, columns, group, and media/text.

**Comment by nosolosw** [comment]
Padding for cover has landed in https://github.com/WordPress/gutenberg/pull/21492

**Comment by nosolosw** [comment]
We've seen a lot of progress and the API was deemed stable for 5.6 (dev note upcoming), so I think we can close this tracking issue and open individual ones as we need them.

**Comment by strarsis** [comment]
Coming from a related issue, does this now allow to give pieces of text in a block (e.g. `core/paragraph`) an individual background color?
