### ISSUE TITLE
Post Updated messages not auto-clearing. Multiple displayed.

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2270]
## Issue Overview
After making multiple updates to a page and clicking the Update button after each change, I end up seeing mulitple Post Updated messages on the screen.

![gutenberg-postupdatemsg](https://user-images.githubusercontent.com/2078245/29037361-b4f227cc-7be6-11e7-9ce5-742ccc93d50d.png)

I would've presumed that these would automatically clear themsleves after a certain period. Or at the very least, get cleared before displaying another identical message.

## Steps to Reproduce (for bugs)
Edit a published page multiple times, clicking the Update button after each change.
View the multiple messages being shown on the screen

## Expected Behavior
I would expect this Post Updated message to automatically clear after a cetain number of seconds, or when the user starts updating the document again.

Or alternatively, the message should be cleared prior to displaying another identical message so that there's not mulitple being displayed on the page. 

## Current Behavior
Multiple Post Updated messages are being shown on the screen at the same time.

## Possible Solution
Clear the message as soon as the user starts editing the document again.
Or, clear the message before displaying another Post Updated message so there's not multiple.

**Comment by aduth** [comment]
The [notice action creator](https://github.com/WordPress/gutenberg/blob/33542dd/editor/actions.js#L202-L227) accepts an optional "id" of the notice, in cases like this one where a single notice of the same type should only be shown. An alternative solution then is to [update the success dispatch](https://github.com/WordPress/gutenberg/blob/33542dd/editor/effects.js#L97-L111) to include an ID.
