### ISSUE TITLE
Editor detecting figure tag in custom class

### ISSUE THREAD

**Issue by SJNBham** [WordPress/gutenberg#22715]
When importing or pasting code into the block editor, the message "This block contains unexpected or invalid content" is displayed. When inspecting the "Resolve" option, it appears WordPress thinks there's supposed to be a `<figure>` tag. It seems to be finding the letters in a custom class that almost spell out figure:

`<div class="kadence-in**f**o-box-**i**ma**gure**-inner-intrisic">`

Whatever code is checking for figure tags, it should ensure all the letters for the tag are adjacent to each other and begin and end with <>. Because it thinks it found a figure tag, it's also injecting a closing </figure> tag and then moving the div with the custom class after the closing figure tag.

To reproduce, paste the attached code into the Code Editor view of a page and then switch back to the Visual Editor view.

[code-snippet.txt](https://github.com/WordPress/gutenberg/files/4697107/code-snippet.txt)
![figure](https://user-images.githubusercontent.com/11393597/83169832-75e3fb00-a0c8-11ea-8ae7-b67e71734adc.png)

Thanks for looking into this. It's preventing us from migrating sites into WordPress from other platforms. Also, if there's a quick workaround available (e.g. commenting out some lines of code) it would be very helpful to have that ahead of an official fix so we could proceed with our migrations.

**Comment by SJNBham** [comment]
I found some reference to the block editor adding <figure> tags around img tags automatically. This might be what's going on vs. it detecting the custom class. 

[https://stackoverflow.com/questions/54311510/gutenberg-block-validation-failed](https://stackoverflow.com/questions/54311510/gutenberg-block-validation-failed)

**Comment by SJNBham** [comment]
I tried adding an opening figure tag before the img tag and a closing figure tag after the img tag, but it still looks like WordPress is getting confused by the custom class name "kadence-info-box-image-inner-intrisic" and trying to detect figure from it. 

![figure-tag-added](https://user-images.githubusercontent.com/11393597/83173160-77fc8880-a0cd-11ea-98a2-80bf33081d65.png)

**Comment by youknowriad** [comment]
Thanks for the issue.

It looks like this is a validation error coming from  the "kadence/infobox" block. I'd suggest opening an issue on the plugin's tracker instead. https://github.com/kadencewp/kadence-blocks
