### ISSUE TITLE
Env: Starting a new env ends up with WordPress 5.2.2

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#22728]
**Describe the bug**

**To reproduce**
1. Use any WordPress plugin. I created one with `npm init @wordpress/block`.
2. Install `@wordpress/env` (`npm i @wordpress/env`).
3. Add config file:
  ```json
  {
	"core": null,
	"plugins": [
		"."
	]
  }
  ```

4. Run `npx wp-env start`.
5. Go to http://localhost:8888/wp-admin/index.php.

**Expected behavior**

The latest version of WordPress is installed.

**Screenshots**

![Screen Shot 2020-05-29 at 08 08 29](https://user-images.githubusercontent.com/699132/83227272-14816200-a184-11ea-9adb-cc5524ed3d5b.png)

/cc @epiqueras @noahtallen

**Comment by noahtallen** [comment]
> That's the version provided by the WordPress docker image.

This is provided by Docker, not the WP community, right? I wonder if we can have them update it.

**Comment by epiqueras** [comment]
The Docker community maintains it.

https://github.com/docker-library/wordpress

We could ask them if you think it's valuable. I think they suggest upgrading using the auto-updater in their tickets.

We could also fork it.

**Comment by noahtallen** [comment]
The image was updated to 5.5 a day or two after WordPress was publicly released this time, so I think this is ok to close. Additionally, I'm adding code in #24778 which will update the images during `wp-env start --update`, which will help consumers relying on the base image to stay up-to-date.
