### ISSUE TITLE
"Trying to get property 'ID' of non-object" when publishing or updating a post

### ISSUE THREAD

**Issue by arjendejong12** [WordPress/gutenberg#22720]
**Describe the bug**
Whenever I try to publish a new post, or update an existing post, I get the following error:
`"Trying to get property 'ID' of non-object"`

Deactivating Yoast SEO or rolling back Gutenberg to 8.0.0 fixes the issue.

**To reproduce**
1. Install Yoast SEO 14.1/14.2
2. Install Gutenberg 8.1.0/8.2.0
3. Create and publish, or update a post

**Expected behavior**
I should be able to publish or update a post without any error messages.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?: Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it?: 8.2.0 (also happens with 8.1.0 but not 8.0.0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Additional context**
See [this](https://github.com/Yoast/wordpress-seo/issues/15190) issue created for Yoast SEO.

**Comment by talldan** [comment]
Hey @arjendejong12, thanks for reporting. Would you able to point us to the line in the codebase that's causing the error?

On https://github.com/Yoast/wordpress-seo/issues/15190, the following link was shared:
https://github.com/WordPress/gutenberg/blob/master/lib/compat.php#L211

but `master` is a moving target, the code in that file has since changed and I'm not sure which line number the error is now happening on.

**Comment by stodorovic** [comment]
PHP notice is occurred in the method _gutenberg_render_block_with_assigned_block_context_ (you can look [stracktrace](https://github.com/Yoast/wordpress-seo/issues/15190#issuecomment-629118443) ). It should be  https://github.com/WordPress/gutenberg/blob/master/lib/compat.php#L261 in current code.

**Comment by talldan** [comment]
Thanks @stodorovic! Just posting the permalink for reference:
https://github.com/WordPress/gutenberg/blob/eab88a77d38ddd81a851f6c9619fe5248c2fed81/lib/compat.php#L261-L273

**Comment by bobbingwide** [comment]
I've got a similar problem in the same code. I've developed a workaround. 
See https://github.com/bobbingwide/oik-batch/issues/41

**Comment by talldan** [comment]
Labeling as a bug. 

I'm not sure under which circumstances `$post` is not defined. 

It seems unusual for it to not be defined.

Also unclear on how this might affect the block context feature.

**Comment by bobbingwide** [comment]
> I'm not sure under which circumstances `$post` is not defined.

In my case `$post` is not defined since it's a unit test case.
I also had the problem occur in other batch routines but did not backtrace those.

**Comment by dd32** [comment]
> I'm not sure under which circumstances $post is not defined.
>
> It seems unusual for it to not be defined.

Having plugins call `apply_filters( 'the_content' )` outside of the loop is not unexpected unfortunately, which [is exactly what is happening here](https://github.com/Yoast/wordpress-seo/blob/840d0d62a5379b3b421d19dbafd13f65f6661b61/admin/links/class-link-watcher.php#L144). In many cases the `$post` global IS set by accident, but may not actually refer to the content being passed to the filter (It may be an entirely different post, or content from an option/etc).  The filter is often used as a generic "Mark this content up for me" function call.

In this case, I think Gutenberg just needs to assume that if `$post` isn't set that post_id is 0 and the post_type is either `'post'` or unset.
