### ISSUE TITLE
It's been a really long time, still no shortcut key for Headings

### ISSUE THREAD

**Issue by brkykmsz** [WordPress/gutenberg#22738]
The classic mode has shift + alt + 1/2/3... for headings or shift + alt + c for center alignment. These are really useful if you are trying to avoid getting carpal tunnel syndrome. Gutenberg is pain in the hand so far.

**Comment by phpbits** [comment]
@brkykmsz You can use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin to use those shortcuts 👍

**Comment by talldan** [comment]
Duplicate of #7438
