### ISSUE TITLE
Drag and drop broken in Safari

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#22730]
While working on #22673, I noted that drag and drop did not work in Safari.

Steps to reproduce: 

- Use Safari
- Insert more than one block
- Hover the block switcher to revealthe mover
- Drag and drop the block

Observe that it doesn't work.

There's no error in the console.

**Comment by jasmussen** [comment]
CC: @WordPress/gutenberg-core

**Comment by jasmussen** [comment]
While you're here, I noticed this CSS: https://github.com/WordPress/gutenberg/blob/master/packages/components/src/draggable/style.scss#L1

```
body.is-dragging-components-draggable {
	cursor: move;/* Fallback for IE/Edge < 14 */
	cursor: grabbing !important;
}
```

The intent seems to be to show the "grabbing" cursor while you are performing a drag operation. But this doesn't work, and it seems like it's not possible to change the cursor _during a drag operation_ without JavaScript. [This SO](https://stackoverflow.com/questions/10119514/html5-drag-drop-change-icon-cursor-while-dragging) post suggests to use [dropEffect](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect), which appears to work in [this fiddle](http://jsfiddle.net/rseg3u8t/).

**Comment by diegohaz** [comment]
I've done some investigation and it seems that this is a regression introduced by the Reakit Toolbar. Working on it.

**Comment by ellatrix** [comment]
Duh, stupid of me :) Sorry for the false alarm
