### ISSUE TITLE
Scripts: Add support for postcss.config.js

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#22732]
## Description

This is a follow-up for #21730 and the comments from https://github.com/WordPress/gutenberg/pull/21730#issuecomment-621069349

> > Currently the `@wordpress/postcss-config` gets imported right into the `webpack.config.js` file. How can we make it as easy as possible to extend or override this config? It would be awesome if we could allow for just adding a `postcss.config.js` file to be root of the project and the script then referencing that one instead of the one from the `@wordpress/postcss-config` package.
> 
> I wasn't aware that `postcss.config.js` is a thing :) It looks like it's standardized: https://github.com/michael-ciniawsky/postcss-load-config. I'm more than happy to add support for it in a follow-up PR. It will be very similar to how we handle all other configs (Babel, ESLint, etc.) 👍

I was playing around with the new version and really like it. postcss.config.js was the only thing that's missing.

Here's an example of such a `postcss.config.js`:

```js
module.exports = ( ctx ) => {
	const config = {
		plugins: {
			'postcss-import': {} ,
			'postcss-mixins': {} ,
			'postcss-nested': {} ,
			'postcss-preset-env': {
				stage: 0,
				preserve: false, // Omit pre-polyfilled CSS.
				features: {
					'nesting-rules': false, /* Uses postcss-nesting which doesn't behave like Sass. */
				},
				autoprefixer: {
					grid: true,
				},
			} ,
			'postcss-hexrgba': {} ,
			'css-mqpacker': {
				sort: true,
			} ,
		}
	};

	if ( 'development' === ctx.env ) {
		config.map = true;
	} else {
		config.map = false;
		config.plugins['cssnano'] = {
			safe: true,
		}
	}

	return config;
};
```

@gziolo I'm assuming you haven't played with that yet? Happy to give it a try.

**Comment by gziolo** [comment]
@ocean90, thanks for converting those comments into an issue, much appreciated. The idea aligns very much with all other configs we provide with defaults, e.g.:

https://github.com/WordPress/gutenberg/blob/7b10c30f257f2b50c39955dff8e05ae8ed55d3f0/packages/scripts/config/webpack.config.js#L70-L80

Feel free to work on it, I'm happy to help with review and testing 👍

**Comment by codetot** [comment]
I found an error with compiled postcss source. https://github.com/WordPress/gutenberg/pull/22735
