### ISSUE TITLE
Start a pages block and move automatically add top-level pages to ellipsis or somewhere else

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22749]
Currently, based on the work done in #22697 there is a checkbox:

![image](https://user-images.githubusercontent.com/253067/83272034-92645e00-a1c2-11ea-92bc-5b51aab2e508.png)

I wonder if this would suit better as an option under ellipsis? There could also be other explorations around this but creating an issue to start the discussion.

**Comment by draganescu** [comment]
I would not hide this option initially since it will look as if the new screen does not support the feature.  This checkbox affects the entire menu, globally, so adding under a Link's ellipsis is not a good place.

**Comment by draganescu** [comment]
The best idea so far is @mtias 's Site pages block where this option would be that block's setting to track a website's page hierarchy and we can use this issue to start an exploration of that block.

**Comment by draganescu** [comment]
Closing in favor of #23689
