### ISSUE TITLE
Text in full-width columns hits the edges of the screen

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#22747]
**Describe the bug**

I'm not sure if this is a regression or not, but text blocks inside of a full-width columns block bump up against the edge of the page. I _think_ Gutenberg used to correct for this, but I could be mistaken (I'm adding the regression label just in case). 

**To reproduce**

1. Add a columns block, make it full width. 
2. Add a text-based block inside (paragraph, header, etc). 
3. Notice that the text block bumps up against the edge of the screen. 

**Expected behavior**

I'd expect that Gutenberg would prevent that from happening — it appears broken. It makes sense that users would like images to bump up against the edges in columns, but not text-based blocks. 

**Screenshots**

<img width="739" alt="Screen Shot 2020-05-29 at 9 26 22 AM" src="https://user-images.githubusercontent.com/1202812/83267553-616c3500-a192-11ea-89b3-99206d234833.png">

**Editor version (please complete the following information):**

- Gutenberg Version 8.2.1

**Comment by alaczek** [comment]
I opened a related issue for full-width block in general: https://github.com/WordPress/gutenberg/issues/20646
The conclusion there so far is that it should a theme responsibility.

There's also a related issue for adding gutter size controls to the Columns block (https://github.com/WordPress/gutenberg/issues/24058). If that one could encompass outer gutters it would be ideal.

**Comment by youknowriad** [comment]
I think that's the correct behavior. Padding and gutter options would allow better control over this. right now it's the theme responsibility to provide the right CSS.
