### ISSUE TITLE
Unable To copy Specific text from shortcode block.!

### ISSUE THREAD

**Issue by Dark-Cod3r** [WordPress/gutenberg#22743]
When i thought Gutenberg can't be worse , you people proved me wrong. Gutenberg literally deserve -1 star. 
After the recent update (i'm pretty sure this is intentional feature but this so called improvement not make sense at all). 
i am unable to select specific text from shortcode block. no matter what i do it always copy the whole block instead of that specific text which i meaning to copy.  Why you people making gutenberg worse with each update.? It seems like you people literally begging users to ditch wordpress and switch to other reliable user friendly CMS.
(Check this Video below).
https://streamable.com/r5ytdl

**Comment by paaljoachim** [comment]
Hey @Dark-Cod3r 

Thanks for reporting the issue!

Is this issue similar to what you are talking about?
https://github.com/WordPress/gutenberg/issues/22775

If so then you can close your issue as work is going on associated to the other issue.
Thanks!

**Comment by paaljoachim** [comment]
Great! Thanks.
