### ISSUE TITLE
Block Editor in Customizer is executed even before customizer blocks are open

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#22753]
**Describe the bug**
The block editor for customizer blocks is rendered and kept hidden before the customizer blocks section is open.
This may trigger requests to the widgets endpoint which may have some buggy side-effects even for users that did not choose to open the customizer blocks at all.

**To reproduce**
I went to the customizer.
I used the browser dom tools I searched for "block-editor-inserter" and I verified the block editor is already on the dom even before the customizer blocks section is open.

**Comment by draganescu** [comment]
Why would this actually be a problem?

> buggy side-effects 

Do we know of something in particular?

**Comment by noisysocks** [comment]
Closing this as we will be completely rearchitecting our implementation of how blocks work in the Customiser.

**Comment by jorgefilipecosta** [comment]
> Do we know of something in particular?

Hi @draganescu, yes previously we had an issue where if some user went to the customizer all the widgets were migrated to the CPT data structure even if there was no action from the user at all.
