### ISSUE TITLE
Iterate on 'add navigation link'

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22750]
Now the links are surfaced with labels the following appears for the navigation block:

![image](https://user-images.githubusercontent.com/253067/83272304-e3745200-a1c2-11ea-8811-4444ed321184.png)

I know there was discussion about having the block title changed, I do think that this is a rather long title and also because of the styling looks almost like a navigation link itself.

There are a few considerations to discuss:

- Should this have a different styling to stand out more?
- Could the title be shortened?

Along with this, it doesn't change based on background changed so you can get the following:

![image](https://user-images.githubusercontent.com/253067/83272487-1b7b9500-a1c3-11ea-922b-112e41b558c1.png)

![2020-05-29 15 43 35](https://user-images.githubusercontent.com/253067/83272546-2e8e6500-a1c3-11ea-9dfa-b77298fd81f4.gif)

**Comment by shaunandrews** [comment]
I question the need for a label to accompany the insert button — especially when/if this allows you to insert more than just a link.

--

That said, if we do think the label is necessary, perhaps we can both shorten in _and_ include it within the `button` element.

Excuse my text-based mockup, but something like this:  [ + Add link ]

**Comment by draganescu** [comment]
Initially the text was not there, it was added only when the inserter adds one kind of block directly on click, to minimize the surprise. The child of Navigation could be just called `Link`. 

So we could do three things here:

- [ ] Rename Navigation Link to Link
- [ ] Fix the dark style to include a correct display of the inserter along with the text

I don't think we want the inserter of the Navigation block to be different than the rest of the Editor and incorporating text into the button is a big departure.

**Comment by mtias** [comment]
> I question the need for a label to accompany the insert button — especially when/if this allows you to insert more than just a link.

This is a standard behaviour that needs to only happen if there's a single block to be inserted in a given area.

It inherits the name of the block, so any change in wording needs to happen in the block itself.

My main worry with the treatment above is that it looks like a new button style (icon + text).

**Comment by pablohoneyhoney** [comment]
I think at the moment it does look too much as the actual output. 
One solution could be to avoid the +, and only say _Add Link_ or _Add Button_

Curious is this new element will have any other application in other contexts, the sidebar comes to mind, or generally FSE interfaces. If it has, then it's worth trying.

**Comment by shaunandrews** [comment]
> This is a standard behaviour that needs to only happen if there's a single block to be inserted in a given area.

Sure, I get that.

> It inherits the name of the block, so any change in wording needs to happen in the block itself.

Yup, sorry if I was unclear — I'm suggested we rename the "Navigation Link" block to just "Link".

> My main worry with the treatment above is that it looks like a new button style (icon + text).

Sure, and it _is_ a new style, and I _am_ hesitant to introduce it. But, the alternative of having the label _outside_ the button shape (as we do now) is that the label could be confused for content and _not_ UI.

--

> One solution could be to avoid the +, and only say Add Link or Add Button

Here's what that could look like:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/191598/84390343-6b942780-abc5-11ea-8816-379818dfa970.png">


> Curious is this new element will have any other application in other contexts, the sidebar comes to mind, or generally FSE interfaces.

Hmmm, that's a good question. One thing that comes to mind is the site-level sidebar that I've been exploring:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/191598/84390308-5f0fcf00-abc5-11ea-930c-aa98aca58460.png">

**Comment by mtias** [comment]
> Yup, sorry if I was unclear — I'm suggested we rename the "Navigation Link" block to just "Link".

Yes, agreed with this.

> But, the alternative of having the label outside the button shape (as we do now) is that the label could be confused for content and not UI.

I think this is a bit specific to the navigation link case. How does it look for buttons? I think perhaps we should just revert to the + on its own.

Perhaps it's worth trying adding just the block type icon next to the + (within the dark container)?

**Comment by draganescu** [comment]
closed by #23163 and #23165
