### ISSUE TITLE
Unable to edit Reusable blocks after creation

### ISSUE THREAD

**Issue by eamcgill90** [WordPress/gutenberg#22769]
**Describe the bug**
Unable to edit Reusable blocks after creation

**To reproduce**
1. Create a paragraph block, add some text
2. Save block as reusable block
3. Publish content/save
4. Add the block again, to another page or same page.
5. Click edit to edit the block
6. Make some changes (like adding more text)
7. Try to save the changes and see this error: https://d.pr/i/3xuRhf

**Expected behavior**
You should be able to edit a reusable block. 

**Editor version (please complete the following information):**
- WordPress.com site - non-Atomic

**Desktop (please complete the following information):**
Happening across multiple devices

**Smartphone (please complete the following information):**
Happening across multiple devices

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by simison** [comment]
Let's continue at https://github.com/Automattic/wp-calypso/issues/40229
