### ISSUE TITLE
Error loading block: Invalid parameter(s): attributes

### ISSUE THREAD

**Issue by leandroberg** [WordPress/gutenberg#22773]
Hello everyone,

I'm facing this issue when trying to use "serverSideRender" Wordpress component, basically, I'm trying to render the same block between front and back end, but when I change the attributes, I got the error. Is anyone facing this same situation? Can you guys please provide some help? Thanks.

Here is my code:

### PHP
_functions.php_

`virtuepress_register_block("dynamic",array(
        'posts'=>array(
            'type'=>'array'
        )
    ));`

`function virtuepress_register_block($blockName,$attrs=false,$render=true){
    wp_register_script('virtuepress-block-'.$blockName,get_template_directory_uri().'/js/block-'.$blockName.'.js',array('wp-blocks','wp-element','wp-data','wp-editor','wp-i18n','wp-components'));
    $blockAttrs = array('editor_script'=>'virtuepress-block-'.$blockName,'editor_style'=>'virtuepress-blocks','render_callback'=>'virtuepress_block_'.$blockName);
    if($attrs) array_push($blockAttrs,array('attributes'=>$attrs));
    if($render) get_template_part('templates/block-'.$blockName);
    register_block_type('virtuepress/'.$blockName,$blockAttrs);
}`

### PHP
_block-dynamic.php_

`<?php function virtuepress_block_dynamic($attributes){
    ob_start();
    var_dump($attributes);
    return 'Attributes: ' . ob_get_clean();
}`

### JS
_block-dynamic.js_

`(function(blocks,blockEditor,components,element,serverSideRender){
    
    const { InspectorControls } = blockEditor;
    const { createElement } = element;
    const { PanelBody, SelectControl } = components;
    var ServerSideRender = serverSideRender;
    
    blocks.registerBlockType('virtuepress/dynamic', {
        title: 'Dynamic Content',
        icon: 'image-filter',
        category: 'common',
        attributes: {
            posts: {
                type: 'array'
            }
        },
        supports: {
            align: ["full"]
        },
        edit: function(props){
            return [
                createElement(
                    InspectorControls,
                    null,
                    createElement(
                        PanelBody, {
                            title: 'Settings'
                        },
                        [
                            createElement(
                                'p',
                                null,
                                createElement(
                                    'strong',
                                    null,
                                    'Select items to be displayed'
                                )
                            ),
                            createElement(
                                SelectControl,{
                                    label: 'Posts',
                                    options: [
                                        { label: 'Test 1', value: '1' },
                                        { label: 'Test 2', value: '2' },
                                        { label: 'Test 3', value: '3' }
                                    ],
                                    onChange: (selectedPosts) => props.setAttributes({ posts: selectedPosts })
                                }
                            )
                        ]
                    ),
                ),
                createElement(
                    ServerSideRender, {
                        block: 'virtuepress/dynamic',
                        attributes: props.attributes
                    }
                )
            ];
        },
        save: function(){
            return null;
        }
    });

}(
    window.wp.blocks,
    window.wp.blockEditor,
    window.wp.components,
    window.wp.element,
    window.wp.serverSideRender
));`

And here are some screenshots:

![Screen Shot 2020-05-30 at 15 18 38](https://user-images.githubusercontent.com/39140847/83336345-fb160e00-a288-11ea-86f3-770f131e9d47.png)
![Screen Shot 2020-05-30 at 15 19 17](https://user-images.githubusercontent.com/39140847/83336347-fc473b00-a288-11ea-80d4-25d1dcd45997.png)
![Screen Shot 2020-05-30 at 15 19 00](https://user-images.githubusercontent.com/39140847/83336348-fcdfd180-a288-11ea-976d-53445950365e.png)

![Screen Shot 2020-05-30 at 15 21 25](https://user-images.githubusercontent.com/39140847/83336394-75469280-a289-11ea-8bb1-64dd25200a93.png)
![Screen Shot 2020-05-30 at 15 20 23](https://user-images.githubusercontent.com/39140847/83336397-78418300-a289-11ea-99cd-a5fbda8c8734.png)

**Comment by craigrileyuk** [comment]
For anyone searching for this issue:

I was having the same problem. I fixed it by defining my block attributes in my `block.json` file instead of inside my `registerBlockType` settings.
