### ISSUE TITLE
Add an accordion (or FAQ) block

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#22772]
**Describe the solution you'd like**
Add an accordion style block to allow text to be clicked to reveal content - like an FAQ.

Example functionality: https://www.w3schools.com/howto/howto_js_accordion.asp

**Describe alternatives you've considered**
FAQ block plugins exist to do this but this form of functionality is something which could be used on a wide variety of websites or multiple purposes - not just for FAQs.

**Comment by paaljoachim** [comment]
Hey @ninetyninew 

We got this issue going:
https://github.com/WordPress/gutenberg/issues/21584
Head on over there and post..:)
I'll close your issue as a duplicate.
Thanks! We need this accordion. First we need a design idea what it would look like.
