### ISSUE TITLE
With Blocks editor, cannot insert block content inside list items

### ISSUE THREAD

**Issue by Pointedstick** [WordPress/gutenberg#22770]
**Describe the bug**
When I use the Blocks editor and insert a list Block, I cannot insert content inside individual list items that are implemented as other Blocks. For example, if I write some text in a list item, I can't add an image at the end of the text inside the list item itself, because the whole list is a Block, and the image is a Block, and Blocks cannot exist inside other Blocks..

**To reproduce**
1. Create a List block
2. Add at least two list items with some text
3. Realize that you'd like to add a picture inside the first list item
4. Try to do that

**Expected behavior**
Adding an Image block inserts it inside the list item where the text insertion point is located

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Default block editor, no plugin

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed Linux running KDE Plasma 5.19
 - Browser: Firefox
 - Version: 76

**Comment by talldan** [comment]
@Pointedstick It is possible to add an image to a list block. From the toolbar, there's an inline image option:
<img width="294" alt="Screenshot 2020-06-03 at 5 16 22 pm" src="https://user-images.githubusercontent.com/677833/83619128-fd94a280-a5bd-11ea-9973-b6c0a01f6513.png">

**Comment by Pointedstick** [comment]
But you can't use the gallery for that, and you have to write the code by hand. This wasn't a requirement in the old editor.

**Comment by talldan** [comment]
@Pointedstick Right, though that wasn't what the issue said though, it mentioned images.

I'm not really clear on what the use case is for galleries in a bullet pointed list, would you be able to share what you want to use this for?

**Comment by Pointedstick** [comment]
I write a weekly blog post summarizing notable software development activity within the KDE community: https://pointieststick.com/

Each post is structured with three main sections. Each section has a header and a bulleted list, with each notable change to the software from the past week having its own list item. I like to include pictures, and the logical place to add a picture for some UI change is right after the text for that item, i.e. at the end of the list item.

I used the old fashioned editor until https://pointieststick.com/2020/05/29/this-week-in-kde-all-about-the-apps/, which is the first post for which I used the Gutenberg editor. As you can see, in that post I abandoned the bulleted list paradigm due to my inability to figure out how to add images (and galleries, and videos) inside list items.

The post before that one hopefully showcases why one might want to put galleries and videos inside list items: https://pointieststick.com/2020/05/23/this-week-in-kde-we-have-migrated-to-gitlab/
