### ISSUE TITLE
Block validation failed for `core-embed/facebook`

### ISSUE THREAD

**Issue by AdrianMachado** [WordPress/gutenberg#22774]
**Describe the bug**
When trying to embed a facebook video via Facebook embed block, embed block, or video block - 
I see the following error in the console
```
Block validation: Block validation failed for `core-embed/facebook` ({name: "core-embed/facebook", icon: {…}, attributes: {…}, keywords: Array(1), save: ƒ, …}attributes: align: {type: "string"}allowResponsive: {type: "boolean", default: true}ampLayout: {type: "string"}ampNoLoading: type: "boolean"__proto__: Objectcaption: {type: "string", source: "html", selector: "figcaption"}className: {type: "string"}providerNameSlug: type: "string"__proto__: Objecttype: {type: "string"}url: type: "string"__proto__: Object__proto__: Objectcategory: "embed"deprecated: Array(1)0: attributes: {url: {…}, caption: {…}, type: {…}, providerNameSlug: {…}, allowResponsive: {…}, …}save: ƒ (e)__proto__: Objectlength: 1__proto__: Array(0)description: "Embed a Facebook post."edit: ƒ r()icon: {foreground: "#3b5998", src: {…}}keywords: ["social"]name: "core-embed/facebook"save: ƒ (e)supports: {align: true}title: "Facebook"transforms: {from: Array(1), to: Array(1)}__proto__: Object).

Content generated by `save` function:

<figure class="wp-block-embed-facebook wp-block-embed is-type-rich"><div class="wp-block-embed__wrapper">
https://www.facebook.com/NASA/videos/245765083275254
</div></figure>

Content retrieved from post body:

<figure class="wp-block-embed-facebook wp-block-embed is-type-rich">[facebook url="https://www.facebook.com/NASA/videos/245765083275254
&lt;/" /]</figure>
```
and the videos fail to embed on me page. https://adrianweiwei.wordpress.com/2020/05/30/another-vod/

**To reproduce**
1. Go to post editor
2. Search for the facebook block
3. Use a facebook video link (ex. https://www.facebook.com/NASA/videos/245765083275254)
4. See error in console
5. Publish the page
6. Visit page and no embed shows up

**Expected behavior**
The facebook video embed should show up

**Screenshots**
N/A

**Editor version (please complete the following information):**
- WordPress version: I can't find it anywhere, how do I check?
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?
Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 83.0.4103.61 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by AdrianMachado** [comment]
@talldan is there anything I can do to get this looked at. I did some digging and it seems that the main issue is that the URL has a left chevron added to it for some reason
![image](https://user-images.githubusercontent.com/11202679/84347394-496bbc80-ab67-11ea-940c-84eb89968d1e.png)

**Comment by swissspidy** [comment]
`[facebook url="https://www.facebook.com/NASA/videos/245765083275254
&lt;/" /]`

That's code specific to WordPress.com.

Embedding `https://www.facebook.com/NASA/videos/245765083275254` on my site in Gutenberg works just fine, so I think this issue is limited to WordPress.com / Jetpack.

**Comment by AdrianMachado** [comment]
@swissspidy Do you know how I could fix this problem, or where I should start looking to fix it? Is there somewhere else I should be asking about this?

**Comment by swissspidy** [comment]
Hmm opening an issue at https://github.com/Automattic/jetpack might make sense. They can assess whether it's a WP.com / Jetpack issue. Alternatives would probably be reaching out to WordPress.com support or an account manager there.

We can leave this one open for the time being until it's verified from their side.

**Comment by AdrianMachado** [comment]
Filed issue on Jetpack https://github.com/Automattic/jetpack/issues/16225

**Comment by AdrianMachado** [comment]
Fixed on wp side
