### ISSUE TITLE
Pullquote block missing "align center"

### ISSUE THREAD

**Issue by jaguarondi** [WordPress/gutenberg#22784]
**Describe the bug**
Adding a "Pullquote" block is by default in "align center" but this option isn't available in the lignment list so when changed, we can't go back to align center.

**To reproduce**
1. Add a Pullquote block
2. Change alignment

**Editor version (please complete the following information):**
- WordPress version: 5.4.1, default Gutenberg, no extra plugins
- Fresh install, nothing else added or imported

With a Pullquote Block, align center is missing:
![image](https://user-images.githubusercontent.com/5890314/83396483-53b9e800-a3fc-11ea-9ad6-e935ba947d19.png)

With an image, we have all options:
![image](https://user-images.githubusercontent.com/5890314/83397109-5d901b00-a3fd-11ea-90cf-caa0e00786ce.png)

**Comment by talldan** [comment]
Traced this back to https://github.com/WordPress/gutenberg/pull/9763, which removed the centre setting. I had a quick scan through the pull request but couldn't see why it was removed. 

@jorgefilipecosta just wondering if you remember why?

**Comment by jorgefilipecosta** [comment]
Hi @talldan, If I remember correctly, I think it was because one of the styles variations did not worked well with the align center styles.

**Comment by carolinan** [comment]
This has been solved, so I am closing the issue.
The block alignment does not use center, but "none" is available in the toolbar so it is possible to reset to default.
The block also has text alignments, including center.
