### ISSUE TITLE
Simple way to retrieve checkbox info in plugin from Gutenberg sidebar?

### ISSUE THREAD

**Issue by dandju** [WordPress/gutenberg#22781]
In older WordPress versions I have used `post_submitbox_misc_actions`. Now with the new Gutenberg editor, I'm struggling to achieve the same functionality with my existing WordPress plugin.

So basically I just need to add a simple checkbox in the "Post & Visibility" section/block in Gutenberg **that must not be permanently stored or pre-filled on page load. So no meta usage needed.**

I just need the information whether the checkbox has been checked or not in the (PHP) WordPress plugin to perform a simple cURL call.

I have managed to add the checkbox to Gutenberg:

```
function MyPlugin({}) {
    return el(
        PluginPostStatusInfo,
        {
            className: 'my-plugin'
        },
        el(
            CheckboxControl,
            {
                name: 'notify',
                label: __( 'Send notification' ),
            }
        )
    );
}

registerPlugin( 'my-plugin', {
    render: MyPlugin
} );
```
But I'm not sure how to "catch" the information if the checkbox was checked or not in my WP plugin when a user updates a post (eg. used `$_POST['checkbox-name']` pre-Gutenberg editor) - is there a simply way to achieve this?

Thank you!

**Comment by talldan** [comment]
@dandju Gutenberg uses the REST API to update posts, so `$_POST` variables won't be set in the same way.

You'd need to use an `onChange` callback to determine when the value changes, e.g.:
```js
function MyPlugin({}) {
    return el(
        PluginPostStatusInfo,
        {
            className: 'my-plugin'
        },
        el(
            CheckboxControl,
            {
                name: 'notify',
                label: __( 'Send notification' ),
                onChange: function( value ) {
                    // do something with the value
                }
            }
        )
    );
}
```

If you then only want to save the value when the post is updated, you'd then need to listen for changes. For that you'd use `subscribe` to listen for changes:
```js
var wasSavingPost = false;
var wasAutosavingPost = false;

wp.data.subscribe( () => {
    var isSavingPost = wp.data.select( 'core/editor' ).isSavingPost();
    var isAutosavingPost = wp.data.select( 'core/editor' ).isAutosavingPost();

    if ( ( isSavingPost && ! wasSavingPost ) || ( isAutosavingPost && ! wasAutosavingPost ) ) {
        // make a request to save the value
    }

    wasSavingPost = isSavingPost;
    wasAutosavingPost = isAutosavingPost;
} );
```
