### ISSUE TITLE
Gutenberg date can't go before UNIX time starts

### ISSUE THREAD

**Issue by ferdi2005** [WordPress/gutenberg#22782]
On the last version of Wordpress+Gutenberg with Safari 13.1.1 on macOS Catalina 10.5.5 (Italian locale, standard theme), I can't set the post date before UNIX time starts (1 Jan 1970) writing the year in the year field, because it takes me back on the date that was previously set. I can use without any problems the integrated calendar in Gutenberg (setting the date on the 1 Jan 1970 and then going back with the arrows) and the other WordPress edit systems (for example "Rapid edit" in the articles list).
The only thing that gives problems is the year form field, as you can see from this gif.
![Screenshot 2020-05-31 at 20 40 29](https://user-images.githubusercontent.com/19609180/83360117-17947200-a37f-11ea-944d-69740f8c620f.gif)

**Comment by annezazu** [comment]
Hi @ferdi2005! I wasn't able to replicate this using Gutenberg 8.3 on WordPress 5.4.2 using both English and Italian locale. I tested this in chrome and safari for good measure too:

![date](https://user-images.githubusercontent.com/26996883/85074008-b2a78d00-b170-11ea-8e04-a1fea7b8e019.gif)

Do you have any other plugins installed that might be interfering?

**Comment by ferdi2005** [comment]
I have this problem with Safari and also Firefox Developer Edition on my mac. @annezazu
<img width="949" alt="Schermata 2020-06-20 alle 11 23 17" src="https://user-images.githubusercontent.com/19609180/85198366-71d28400-b2e8-11ea-8b31-832348892f44.png">

But I have Wordpress 5.0.4 and it says it's the last version! I'll talk with my sysadmin... 
<img width="942" alt="Schermata 2020-06-20 alle 11 24 06" src="https://user-images.githubusercontent.com/19609180/85198381-90387f80-b2e8-11ea-905d-37ffc2ebe749.png">

**Comment by annezazu** [comment]
Oh interesting! Let me know if you can confirm you're using the latest version of WordPress and if it still happens there (5.4.2). Thanks for following up.

**Comment by youknowriad** [comment]
This is working as expected for me. Try upgrading your WordPress install and see if it fixes it.
