### ISSUE TITLE
Writing Flow: allow split out of Quote Block's citation on Enter

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#22791]
Similar to #22290, it would be better to split out citation on `Enter`. Thanks!

**Comment by talldan** [comment]
@phpbits It'd be great if you could write a proper description 😄

**Comment by phpbits** [comment]
@talldan Sorry about that. Yeah, it would be for Quotes block. When on citation area and press `ENTER` it should create another paragraph instead of new line on citation area. Thanks!

**Comment by talldan** [comment]
Thanks!

**Comment by mtias** [comment]
This was addressed in #25892.
