### ISSUE TITLE
Rename Block Navigation (AKA Block Navigator)

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#22814]
It's too confusing, right now, for folks new to the project to disambiguate between the Navigation Block, Navigation Screen and the Block Navigation popover (AKA Block Navigator). 

I think that we should rename the Block Navigation popover.

<img width="472" alt="Screen Shot 2020-06-02 at 10 10 11" src="https://user-images.githubusercontent.com/612155/83466056-4151b400-a4b9-11ea-982c-001e652d2f80.png">

**Comment by talldan** [comment]
Ideas:
- Block Overview
- Block Hierarchy 
- Block Tree

**Comment by ZebulanStanphill** [comment]
I like "Block Overview" and "Block Tree".

**Comment by mapk** [comment]
I'm pinging @shaunandrews here because I think he has some thoughts around this too. I believe he raised the idea of calling it simply the "List view". Please fill in if I'm mistaken, Shaun. 😄

**Comment by shaunandrews** [comment]
**List View** is my favorite. I believe it was a suggestion from @mtias

**Comment by ZebulanStanphill** [comment]
I really like the "view" terminology. I think either "List view" or "Tree view" would work great!

**Comment by adamziel** [comment]
Once the label PR lands, a good next step would be renaming the actual components. The old names should still be exported with a deprecation notice.
