### ISSUE TITLE
Styles cause lag on Block insertion and selection

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#22823]
**Describe the bug**
Inserting the Navigation block causes a perceivable lag in the editor interface before the block appears and is useable. This also happens when re-selecting the block having focused elsewhere.

The culprit appears to be the Block styles. This is likely due to the perf costs of rendering the `BlockPreview` component.

**To reproduce**

0. On `master` branch.
1. Create Post
2. Insert Nav Block
3. See lag before you are able to interact with the block/editor again.
4. Click away from Nav Block so it is no longer "focused".
5. Click on Nav Block again to re-select it. Again, notice the lag before it becomes interactive.

**Expected behavior**
There should be no perceivable lag.

**Screenshots**
Here are some videos to illustrate the issue.

* Lag visible with Block `styles` in place - https://d.pr/v/RSpTnJ.
* No lag visible with Block `styles` _removed_ - https://d.pr/v/kEV86x

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5]: **it's 5.5**
- **Plugin**
- If the Gutenberg plugin is installed, which version is it? **It's the version from `master`.**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser Chrome
 - Version [e.g. 22] 83

cc @draganescu

**Comment by draganescu** [comment]
It is interesting to note if this is visible to other blocks as well.

**Comment by adamziel** [comment]
Unfortunately I am unable to reproduce the visible lag. Still, the `BlockPreview` component is pretty slow indeed. Recently I added a `memo()` recently which helped avoid costly re-rendering - I wonder if it's failing somehow and it gets rendered multiple times?

**Comment by draganescu** [comment]
I will edit this issue to be more generic as Block styles, if the problem is observed consistently, are in all the blocks that support them, not just in navigation.

**Comment by getdave** [comment]
Note you must have the Block Settings sidebar open.

I also notice this on Buttons block. Try using dev tools to throttle your CPU.
