### ISSUE TITLE
[ Navigation Block ]  Make it Mobile Responsive

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#22824]
Hi,

I am using Navigation Block for creating Header Templates. I know it is still a WIP, just want to raise an issue that it is not mobile responsive yet.

From mobile responsive I mean to convert the menu items in a menu toggle icon for mobile screen sizes.

Is this something already in consideration?

Cheers.

**Comment by annezazu** [comment]
@munirkamal thanks for reporting this and sharing! Right now, work is in progress to improve responsiveness here: https://github.com/WordPress/gutenberg/issues/22497

Does this cover what you were hoping to see? If so, please close this out so we can focus efforts there. If not, definitely share more of what you'd like to see and know that the people working on this are doing their best to create a responsive experience.

**Comment by munirkamal** [comment]
@annezazu 

Thank you for reviewing this. I've checked the issue #22497 and that is not what this issue is about. That issue is to make the menu editing experience responsive.

In this issue, I want to raise it to devs attention that the menu itself is not responsive on the front-end. 

By Responsive I mean to make the menu items enclosed inside a menu toggle for mobile devices.

For example here are the screenshots of a simple header template I have created.

Desktop:
![Image 2020-06-04 at 1 12 55 PM](https://user-images.githubusercontent.com/5817882/83732296-45bad000-a665-11ea-93db-6bdf996f45a4.png)

Mobile:
![Image 2020-06-04 at 1 13 11 PM](https://user-images.githubusercontent.com/5817882/83732313-4bb0b100-a665-11ea-8ac5-0e2b23451db3.png)

Now for the mobile, I wish the menu block should be responsive and work something like this.
![Screen Recording 2020-06-04 at 01 32 PM](https://user-images.githubusercontent.com/5817882/83734041-de524f80-a667-11ea-8d8d-6d2a8799c07f.gif)

Do you get my point? Right now in the gif above I implemented it with a little JS and inserting the icon/div in an HTML block. 

let me know if you need more info.

**Comment by annezazu** [comment]
@munirkamal thanks for this GIF and further explanation - makes perfect sense. I've added this to the project board so the people working on this can take a look.

**Comment by jasmussen** [comment]
Here's a rough outline for what we could start with —

Make a toggle on the Navigation block that defaults to collapsing to a menu on mobile.

<img width="1440" alt="desktop" src="https://user-images.githubusercontent.com/1204802/109656098-56509600-7b64-11eb-9bf5-a564a1bc1575.png">

On mobile, with the navigation block unselected, you see the burger icon. 

<img width="375" alt="mobile unselected" src="https://user-images.githubusercontent.com/1204802/109656127-5fd9fe00-7b64-11eb-9d03-c859cf75d117.png">

Tap to edit. When you are editing (navigation block `is-selected` or `has-child-selected`), the block itself gets the same treatment as the modal dialog on the frontend. Click outside to deselect the block, and collapse the menu.

<img width="375" alt="mobile selected" src="https://user-images.githubusercontent.com/1204802/109656143-65374880-7b64-11eb-9921-9bcd883e12a7.png">

On the frontend it works: on mobile (f.ex. we <480px), you see the burger icon:

<img width="375" alt="frontend collapsed" src="https://user-images.githubusercontent.com/1204802/109656335-9a439b00-7b64-11eb-9804-26abc45924f1.png">

Click it and a modal dialog opens, trapping tab focus, and Esc or or the close icon closes the menu:

<img width="375" alt="frontend-expanded" src="https://user-images.githubusercontent.com/1204802/109656455-b9422d00-7b64-11eb-9580-bf694b1c081c.png">

We could potentially use [Micromodal](https://micromodal.now.sh/) for the dialog behavior, and this same behavior would benefit the burger menu whether it was a small dropdown, a fullscreen modal, an overlay sidebar, or most things in between.

It seems feasible to be able to offer both fullscreen modal menus, sidebar overlays, and inline dropdowns using the same markup and CSS only, as `position: fixed;` breaks out of any ancestors that apply `position: relative;`, therefore those three styles could simply be style variations.

**Comment by mtias** [comment]
Lovely. I think it might be worth allowing to both have an icon to trigger (default), but also the option of a text button (like "Menu"). Perhaps rather than text it's an actual _Button_ block with all its customization settings and some good defaults?

![image](https://user-images.githubusercontent.com/548849/109786975-08906800-7c0e-11eb-9fd5-97252ffe7afe.png)

**Comment by jasmussen** [comment]
I'll think about the best way to let you edit and configure such a button in the flow from both the desktop and mobile breakpoints, seems like we might need to show it on-select at both.

**Comment by mtias** [comment]
I think we can keep it just on the context it's actually shown. Another thing I think we really need to do is to allow the button -> overlay to also work on desktop as an option.

**Comment by vcanales** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/30047
Follow in https://github.com/WordPress/gutenberg/issues/31765
