### ISSUE TITLE
Consider showing the link url beside the icon when one is set in navigation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22836]
This feature might also expand to any link, but for now, I created a mock of what this might look like for navigation block.

<img width="496" alt="Frame 4" src="https://user-images.githubusercontent.com/253067/83551426-3e2de680-a500-11ea-83e6-172e6d64698f.png">

**Comment by richtabor** [comment]
What if instead the link was added to a `Tooltip` of the link icon instead? 🤔

**Comment by draganescu** [comment]
Exploring this in two "try" PR's would maybe give some direction?

**Comment by mtias** [comment]
Could also expand in place on hover / focus if we find it's too much expanded by default. I think the url should strip out protocol from display.

**Comment by draganescu** [comment]
I'll close this in favor of tracking #23375
