### ISSUE TITLE
Adding Advanced link to Options modul.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#22839]
**Is your feature request related to a problem? Please describe.**
There are a few issues where many are asking for the No Follow link option.
Such as:

**Add easy way to modify links and add toggle options.** 
https://github.com/WordPress/gutenberg/issues/17556

**Add nofollow option for links**
https://github.com/WordPress/gutenberg/issues/13542

**Make link selection consistent** 
https://github.com/WordPress/gutenberg/issues/17293

and there are probably other associated issues.

**Describe the solution you'd like**

Today we have this link dialog:
<img width="576" alt="Screen Shot 2020-06-02 at 21 39 25" src="https://user-images.githubusercontent.com/5323259/83562257-8c9baf00-a519-11ea-82e0-9ed7458c2dad.png">

I am wondering if we should add an Advanced Link option to the options modal similar to this mockup:
![Options-Panel-Add-Advanced-links](https://user-images.githubusercontent.com/5323259/83562304-a1784280-a519-11ea-9296-3c30cadaa2f4.jpg)

Clicking the Advanced links will then change the Link modul and add additional options to it like the No follow option.

**Describe alternatives you've considered**
Editorskit plugin already has additional link options included in it's link modul so the user can always choose to use that.

**Comment by richtabor** [comment]
I don't personally think it warrants a separate display option.

**Comment by paaljoachim** [comment]
Hey Rich @richtabor 
I am trying to look at different ways we can handle the additional link attributes. This was one way I thought of. I am hoping that it can inspire to figuring out even better ways. Suggest a way that will not work and then hope to create discussions in finding a way that does..:)

**Comment by richtabor** [comment]
What about a "more" trigger that when toggled on, reveals any additional controls?

[Here's a Figma prototype &rarr;](https://www.figma.com/proto/11zYmEHtoQ7mejqwzdLsIS/More-Link-Controls?node-id=1%3A7&viewport=-886%2C823%2C2&scaling=scale-down) 

<img width="576" alt="Frame 2" src="https://user-images.githubusercontent.com/1813435/83778127-48fb8f00-a658-11ea-872d-db77ea2eabe9.png">

**Comment by paaljoachim** [comment]
Looks good to me! That would work even better.
Let's close this issue and open a new issue suggesting it.
I'll close here, and if that's alright then you can open a new issue adding the Figma image.

**Comment by paaljoachim** [comment]
Thanks Rich.
I went ahead and opened this issue: Link Control: Add more controls.
https://github.com/WordPress/gutenberg/issues/23011
