### ISSUE TITLE
The toolbar behavior in the "Reusable Blocks" is buggy.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#22832]
When editing "Reusable Blocks", if you focus on "Reusable Blocks" itself after focusing on the blocks inside, the "block toolbar" will jump to "Reusable Blocks".

**Screenshots**
![the_bug](https://user-images.githubusercontent.com/31400297/83538001-49990600-a530-11ea-9109-777e198f8640.gif)

**Editor version**
- WordPress version: 5.4.1
- Gutenberg plugin version : 8.2.1

Note: It also occurs in WordPress 5.4.1 without Gutenberg plugin.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser : Chrome, Safari

**Additional context**
When there are multiple blocks inside, I can edit it by somehow moving the focus to another block.

**Comment by ddryo** [comment]
It was more serious when in "Top toolbar" mode.

In this case, the toolbars for the blocks in "Reusable Blocks" were not available at all.

![22832_02](https://user-images.githubusercontent.com/31400297/83539252-c4165580-a531-11ea-822f-668e83f98e71.gif)

**Comment by draganescu** [comment]
I was able to reproduce this.

**Comment by shaunandrews** [comment]
I’ve seen similar things happen with the Navigation block nested within a Group block.

**Comment by chrisvanpatten** [comment]
This is a duplicate/relates to #19436 and #18560. It would also be solved by #23601, which is blocked by #22639.
