### ISSUE TITLE
Legacy widget preview may not work as expected because it lacks front end assets

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#22838]
**Describe the bug**
Some widgets have a backend UI on the widget screen but don't provide the scripts/styles that render that content on the frontend.
In the editor, we don't load all the frontend assents so the preview may not work as expected.

A possible solution is to render the widget previews on an iframe with all the frontend assets. 
PR https://github.com/WordPress/gutenberg/pull/14643 implemented this solution but did not get much traction.

**To reproduce**
I installed https://wordpress.org/plugins/instagram-slider-widget/
I tested the widget with an Instagram hashtag and verified the widget preview does not contain the slider UI that appears on the frontend.

**Comment by noisysocks** [comment]
May be fixed by https://github.com/WordPress/gutenberg/pull/14643.
