### ISSUE TITLE
Featured Image Never Loads for user with Custom Role on a Custom Post Type

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#22847]
**Describe the bug**

I have a user with a Custom Role for specific custom post types. This user can do everything they need to. They can upload media, edit their posts etc. The one thing that's broken is that the Featured Image never actually loads,. I get the spinning ball of 'loading' and it never actually shows.

However the image DOES get properly saved and if I view the post, it's there.

This appears to be related to the following:

* https://github.com/WordPress/gutenberg/issues/12198
* https://core.trac.wordpress.org/ticket/46723

Looking in Console, I see "Unhandled promise rejection" which google-fu failed me hard :(

`Error] Unhandled Promise Rejection: [object Response]
	dispatchException (wp-polyfill.min.js:1:97215)
	invoke (wp-polyfill.min.js:1:92747)
	n (index.js:1:29339)
	a (index.js:1:29579)
	promiseReactionJob`

The user role is... a little messy to explain, but I'm happy to have a go at it.
**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? both
- If the Gutenberg plugin is installed, which version is it? 8.2.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 13.1

**Comment by Ipstenu** [comment]
Details on the role permissions:

```
			$capabilities = array(
				'read'          => true,
				'edit_posts'    => false,
				'delete_posts'  => false,
				'publish_posts' => false,
				'upload_files'  => true,
			);
			$result = add_role( 'data_editor', 'Data Editor', $capabilities );
```

And then for each of the three (yeah) CPTs:

```
		// The CPTs they work for
		$cpts  = array( 'actor', 'character', 'show' );

		// Loop through each role and assign capabilities
		foreach ( $roles as $the_role ) {
			// If the role exists (so it doesn't die later)
			if ( self::role_exists( $the_role ) ) {

				$role = get_role( $the_role );
				$role->add_cap( 'read' );
				foreach ( $cpts as $the_cpt ) {
					$role->add_cap( 'read_' . $the_cpt );
					$role->add_cap( 'read_private_' . $the_cpt . 's' );
					$role->add_cap( 'edit_' . $the_cpt );
					$role->add_cap( 'edit_' . $the_cpt . 's' );
					$role->add_cap( 'edit_others_' . $the_cpt . 's' );
					$role->add_cap( 'edit_published_' . $the_cpt . 's' );
					$role->add_cap( 'publish_' . $the_cpt . 's' );
					$role->add_cap( 'delete_others_' . $the_cpt . 's' );
					$role->add_cap( 'delete_private_' . $the_cpt . 's' );
					$role->add_cap( 'delete_published_' . $the_cpt . 's' );
				}
			}
		}
```

**Comment by Ipstenu** [comment]
I did some banging on this, and as soon as I enable `edit_others_posts` and `edit_posts` for the custom role, it can magically use featured images.

Of course I don't want this. I don't want them to be able to edit posts :) I can work around this by blocking them from those pages other ways, but something seems to be a little too hard-lined about this.

**Comment by skorasaurus** [comment]
@Ipstenu - Thanks for the thorough details.  

This appears to be the same issue discussed in https://github.com/WordPress/gutenberg/issues/18510 ; 
I've closed this to consolidate discussion.
