### ISSUE TITLE
Loading one stylesheet by default that affects front and backend.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#22851]
As one makes changes to the themes stylesheet one also expects to see the change in the frontend and backend. But right now it only shows up in the frontend.

Adding for instance 
`add_editor_style( 'style.css' );`
to the functions file the theme stylesheet is seen on the frontend will also be seen on the backend. Or if needed one can add another stylesheet especially for the backend.

How do we by default change the CSS in the style.css or in the customizer or other ways so we can see the changes instantly reflected in the frontend and backend?

How can we make it secure so that CSS that looks nice on the frontend does not ruin the backend? As there are two very different environments the same CSS will affect.

Today we have a safety precaution in having to add editor styles so when someone adds CSS it only affects the frontend, just to be sure it does not negatively affect the backend Gutenberg area.

**Comment by paaljoachim** [comment]
@carolinan Carolina do you know if this issue is still valid?

**Comment by skorasaurus** [comment]
I think this can be closed; 

if you add  add_editor_style( 'style.css' ); with the after_theme_setup hook; the styles should apply on the frontend and backend; although there are [plenty of issues](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+add_editor_style) with this approach.
