### ISSUE TITLE
Explore if a modal works for the link interface in navigation block when used in nav-menus.php

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22857]
This has been explored in #22829 and would be good to explore further in design so adding the 'needs design' label. A few points to consider:

- There are options in the editor to bring in and the modal could expose these.
- Is there another option besides having a modal?
- Under this section, an option to 'add all subpages' could appear. This could be super useful along with other settings per link.

Looping in @shaunandrews for exploring here also.

**Comment by draganescu** [comment]
Overall #22829 proved to not be a good direction. I will close this to save focus on design progress.
