### ISSUE TITLE
Lazy Import: Support path imports

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22869]
The `@wordpress/lazy-import` package introduced in #22684 allows for importing modules which may or may not be already installed. It's intended to be mostly interchangeable with a dynamic `import` or CommonJS `require` (aside from the fact that it returns a promise).

As part of the changes in #22684, existing usage of dependencies required in a benchmark script were ported to use `@wordpress/lazy-import`. One amongst these was the [`fbjs` package](https://www.npmjs.com/package/fbjs), which requires that a module be imported from its path within the package, even going so far as to throw an error when the root-level package is imported.

Currently, `@wordpress/lazy-import` does not support path imports, which required a unique workaround for the above scenario.

**Task:** Support path imports in `@worpress/lazy-import`

**Implementation Notes:**

Existing supported usage should not be impacted.

Path-based imports should be supported, as in the following example:

```js
await lazyImport( 'fbjs/lib/shallowEqual@^1.0.0' );
```

As noted at https://github.com/WordPress/gutenberg/pull/22684#discussion_r434796408 , the `npm-package-arg` package used in `@wordpress/lazy-import` does not support strings formatted this way. It may be required to extract the path separate from this existing process, or create a custom implementation for extracting the package, path, and version from a given string.

**Comment by gziolo** [comment]
It was implemented in #23751 but the final API was simplified to take advantage of all features that `npm-package-arg` offers:

```js
 lazyImport( 'fbjs@^1.0.0', {
	localPath: './lib/shallowEqual',
} );
```

We can always revisit and offer the API proposed originally. I'm closing the issue for now, but we can always reopen.
