### ISSUE TITLE
Too Many Inserters When Nesting Blocks

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#22873]
**Describe the bug**
I suspect there's already a bug for this, but I can't find it. There are simply too many inserters once you've nested a couple blocks.

**To reproduce**
The screenshot shows:

1. Group Block containing a 
1. 3-column Columns block each containing
1. a buttons block

**Expected behavior**
With so many space-consuming and distracting inserters, the promise of a WYSIWYG page fades away. I'm not sure the perfect solution, though I think certain blocks like Buttons should probably only show their inserters when they are focused/being interacted with.

Something like #22867 would be one possible way to reduce the need for persistently visible inserters.

**Screenshots**
![seven inserters visible due to block nesting](https://user-images.githubusercontent.com/1238696/83692133-44779d80-a5a8-11ea-995e-a28ff87b8346.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1

**Comment by richtabor** [comment]
> I think certain blocks like Buttons should probably only show their inserters when they are focused/being interacted with.

100%

**Comment by bobbingwide** [comment]
Is this too many inserters too? I've only got 3 empty paragraph blocks.
![image](https://user-images.githubusercontent.com/2474435/83810137-8ccdb300-a6af-11ea-9824-67b33d986662.png)

**Comment by mtias** [comment]
This is better now, though not great. Closing in favor of a broader issue trying to tackle the various contexts of [+] inserters: #26404
