### ISSUE TITLE
invalid hook call when using InnerBlocks

### ISSUE THREAD

**Issue by jhackett1** [WordPress/gutenberg#22888]
i've adapted an example from [this docs page](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/nested-blocks-inner-blocks/).

**when i try to use the block on a page, it crashes and i get an [invalid hook call](https://reactjs.org/warnings/invalid-hook-call-warning.html) error.**

i'm not using hooks anywhere in the component, as you can see, so i assume this has something to do with how i'm importing the javascript libraries?

i'm using [parcel](https://parceljs.org/) to bundle my js code and let me use jsx (with the `parcel watch` command to stop it launching a dev server).

any ideas what's going on here? this is proving very hard to debug. i can only find references to this error in a general react context which isn't too helpful here.

```
import { registerBlockType } from '@wordpress/blocks';
import { InnerBlocks } from '@wordpress/block-editor';
 
wp.blocks.registerBlockType( 'gutenberg-examples/example-06', {
    title: "Rainbow teaser",
    icon: "editor-table",
    category: "common",
 
    edit: ( { className } ) => {
        return (
            <div className={ className }>
                <InnerBlocks />
            </div>
        );
    },
 
    save: ( { className } ) => {
        return (
            <div className={ className }>
                <InnerBlocks.Content />
            </div>
        );
    },
} );
```

(seperate but possibly related issue is that i'm trying to use `window.wp.blocks` to register the block here, because when i use the imported `registerBlockType` function nothing happens at all!)

my npm dependencies:

```
    "devDependencies": {
        "@wordpress/block-editor": "^4.0.0",
        "@wordpress/blocks": "^6.17.0",
        "@wordpress/components": "^9.7.0",
        "gulp": "^4.0.2",
        "gulp-cli": "^2.2.1",
        "gulp-sass": "^4.1.0",
        "node-sass": "^4.14.1",
        "npm-run-all": "^4.1.5",
        "parcel-bundler": "^1.12.4",
        "sass": "^1.26.7"
    }
```

**Comment by jhackett1** [comment]
okay, i've solved it in this case by removing the npm dependencies and using the version that's on the window object instead.

it does leave me confused about when it makes sense to `npm install` these packages and use them that way, if it causes errors?

**Comment by tellthemachines** [comment]
To answer you question about the packages first: `npm install`ing the packages should work as long as you have a build process that transpiles your code to ES5 (which it sounds like you do as you're using Parcel). The `window.wp` object is meant to be used in a scenario where you don't have any build process, and are writing plain JS to run directly in the browser.

That invalid hook call error would happen if you had another version of React running on the project. Could that the case?

One other thing I notice is that `"@wordpress/block-editor"`,` "@wordpress/blocks"` and`"@wordpress/components"` should be in your `dependencies` array as opposed to `devDependencies`. Having them as `devDependencies` would cause them to not be included if you were importing your package in another project. Not sure if that's the reason they are not working though.

**Comment by bigaru** [comment]
It seems that this happens especially with parcel. 

As Rob Kendal describes the same problem in his [blog post](https://dev.to/kendalmintcode/solving-react-hooks-invalid-hook-call-warning-26c8):
> The solution? Stop using Parcel and switch to Webpack

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this one now.
