### ISSUE TITLE
Copy list from GDocs into Gutenberg with Firefox results in paragraphs instead

### ISSUE THREAD

**Issue by scheinercc** [WordPress/gutenberg#22880]
### Describe the bug
In Firefox copying & pasting an ordered list from GDocs into Gutenberg results into multiple paragraphs instead one list.
If I copy from Chrome (into Firefox / Gutenberg) it works fine.

### To reproduce
1. In Firefox
2. Create a GDocs file
3. Create a list with some items
4. Open a WP post editor
5. Paste the list into the editor

### Expected behavior
The copied GDocs list results in a list within the editor

### Screenshots
**GDocs List:**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/817856/83710312-c2e54580-a663-11ea-9f00-3ecc5899ba3b.png">
**Pasted into editor (from Firefox to Firefox)**
_results into two paragraph blocks_
<img width="727" alt="image" src="https://user-images.githubusercontent.com/817856/83710375-ef00c680-a663-11ea-9760-31cf43e52359.png">
**Pasted into editor (from Chrome to Firefox)**
_results into one list block, ordered list selected_
<img width="708" alt="image" src="https://user-images.githubusercontent.com/817856/83710522-51f25d80-a664-11ea-8da6-43a77213ca96.png">

### Editor version (please complete the following information):
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- ~~If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]~~

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox Dev Edition
 - Version 78.0b2

**Comment by annezazu** [comment]
Thanks for reporting this @scheinercc! I dug in and was able to replicate differences between how Firefox handles this vs Chrome. I was using Gutenberg 8.6.1 and WordPress 5.5 RC for context.

Chrome video: https://cloudup.com/cEcw0D92sLw
Firefox video: https://cloudup.com/c_biLNlCRoG

Removing the needs testing label and changing to a bug!

**Comment by kathrynwp** [comment]
Can confirm that this is still an issue with:

Firefox 103.0.1
macOS 12.2.1

WordPress 6.0.1
Gutenberg 13.8.0 active or inactive
No other plugins active

**Comment by Mamaduka** [comment]
I can no longer reproduce the issue. It was probably fixed with recent List block refactoring.

I'm going to close the issue.


Tested with:
* Firefox 112.0.2
* WordPress 6.2
* with and without Gutenberg 15.7
