### ISSUE TITLE
Widgets experimental: Block panel too high and goes under the top black admin bar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#22884]
**Describe the bug**
Twenty Twenty
Gutenberg plugin 8.2.1
WP 5.4
Chrome

Block panel is too high for the Widgets screen, and also goes under the top black admin bar:

<img width="1479" alt="Screen Shot 2020-06-04 at 08 30 17" src="https://user-images.githubusercontent.com/5323259/83722651-ae8e5200-a63d-11ea-8147-1885446e6e5a.png">

**To reproduce**
1. Turn on Widgets experimental.
2. Go to Gutenberg -> Widgets (beta)
3. Click to insert a block.
4. See result.

**Comment by mapk** [comment]
Initially I thought we can just use the new quick inserter now, but that "browse" button requires the Block Library panel to open and I know we don't have that on this page.

![Screen Shot 2020-07-17 at 4 05 47 PM](https://user-images.githubusercontent.com/617986/87837134-67ec6400-c847-11ea-86a9-2ba5bc9aa300.png)


So looks like this will just require some dev to position the quick Inserter nicely within the viewable area without it being cut off.

**Comment by noisysocks** [comment]
This seems to work now.

<img width="729" alt="Screen Shot 2020-08-14 at 14 48 51" src="https://user-images.githubusercontent.com/612155/90214887-47f79280-de3d-11ea-8872-8e0ed8fece00.png">

**Comment by noisysocks** [comment]
I read this issue wrong. The inserter appears underneath the black bar but should appear on top of it.

**Comment by mapk** [comment]
This happens in the Editor too, but I don't think it's a problem.

![Screen Shot 2020-08-17 at 3 35 00 PM](https://user-images.githubusercontent.com/617986/90450775-4a592700-e09f-11ea-90d5-5a9fddbce67f.png)

Looking at the elevation of elements, I would expect the top black bar to be at a higher elevation than anything in the Editor canvas. 

And with the smaller inserter popover now in the Widgets screen, it less likely this elevation collision 😄  will happen.

**Comment by paaljoachim** [comment]
I am thinking with a new widget design the problem will just go away..:)
