### ISSUE TITLE
IE11: Cover block - Overlay color does not work in IE11, Gradient does

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#22889]
**Describe the bug**
Using the Cover block with an image and an overlay, the set color of the overlay will not show in IE11 and IE10. Using gradients, these will show as there is a new span element added for the gradient. The regular overlay does not have this element.

**To reproduce**
1. Create a new post or page
2. Add cover block, select any image
3. Make sure a color overlay is added
4. Check in IE11, overlay color is not shown, only image is displayed

**Expected behavior**
When having an overlay color selected, it should be applied to the image. Otherwise text will be very hard to read in certain cases.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11, also tested with document mode to version 10

**Comment by getsource** [comment]
Hi! Thanks so much for the report, and I'm sorry it has taken as long as it has for a reply.

This ticket came up for conversation during today's [Gutenberg triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1606194343364000), and several folks were able to test.

It was tested and working, including under WordPress 5.5.3 and 5.6 RC, so it was decided to close this issue for now.
If you are still having the problem, please comment back, and the issue can be reopened.

Thanks again!
