### ISSUE TITLE
CSS Class issue with Spacer Block

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#22892]
Like all other blocks the CSS class is not applied to the spacer block inside Gutenberg Editor. It is applied on the front-end but not when inside Gutenberg editor.

**Comment by richtabor** [comment]
Confirmed.

Editor:
<img width="498" alt="Screen Shot 2020-06-04 at 12 37 41 PM" src="https://user-images.githubusercontent.com/1813435/83786074-384f1700-a660-11ea-9e46-994fe6af33be.png">
Frontend:
<img width="615" alt="Screen Shot 2020-06-04 at 12 37 29 PM" src="https://user-images.githubusercontent.com/1813435/83786082-3ab17100-a660-11ea-972d-cba6630963b4.png">

**Comment by thetwopct** [comment]
Related to this I presume, if I `register_block_style` for core/spacer (I have responsive spacers of different heights), the style is applied on the frontend, but not in the Editor as the class from the style is not added. Would be great to fix. Thanks!

**Comment by richtabor** [comment]
> Related to this I presume, if I `register_block_style` for core/spacer (I have responsive spacers of different heights), the style is applied on the frontend, but not in the Editor as the class from the style is not added. Would be great to fix. Thanks!

Very likely that this is related.

**Comment by oxyc** [comment]
https://github.com/WordPress/gutenberg/pull/23235 should fix all the issues mentioned here.

**Comment by thetwopct** [comment]
@oxyc how did you get on with the fix for this?
