### ISSUE TITLE
Show existing classes in "Advanced" 

### ISSUE THREAD

**Issue by 00travelgirl00** [WordPress/gutenberg#22895]
**Is your feature request related to a problem? Please describe.**

I have added a own class to a block and added some CSS in the style.css to it. Couple days later I forgot about it and added a similar class for the same purpose to a block. I wanted to styl it in my style.css and realized I have already creadet a similar class. 

**Describe the solution you'd like**

It would be great to view the already existing classes unter the field for "Additional CSS class(es)"

<img width="1106" alt="Bildschirmfoto 2020-06-04 um 16 36 20" src="https://user-images.githubusercontent.com/21318377/83770681-a48e4280-a681-11ea-9995-2fce68837dd6.png">

**Comment by Soean** [comment]
If you want to use a style on different blocks, then block styles are a better solution.

Add a style via PHP:
```php
register_block_style(
    'core/quote',
    array(
        'name'         => 'blue-quote',
        'label'        => __( 'Blue Quote' ),
    )
);
```

Add style to CSS
```CSS
.wp-block-quote.is-style-blue-quote { 
    color: blue; 
}
```

Result
<img width="934" alt="Bildschirmfoto 2020-06-04 um 21 03 37" src="https://user-images.githubusercontent.com/695201/83799961-e8e00980-a6a6-11ea-9831-e44f2c7a1417.png">

**Comment by talldan** [comment]
Thanks for creating the issue @00travelgirl00, this was also suggested on https://github.com/WordPress/gutenberg/issues/15077, so I'll close this as a duplicate.
