### ISSUE TITLE
Navigation: Split Link block into Post, Page, Category, Link, etc.

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22919]
Right now linking to a WordPress entity (post, page, category, etc.) is done by inserting a Link block. The user then selects the entity and the URL of the entity is stored in the Link block's `url` attribute. This is not ideal, though, as an entity's URL may change.

Instead of selecting a Link, we should allow the user to select a Post, Page, Category, etc. The ID of the entity would then be stored instead of the URL. The correct URL would still be rendered on the frontend using the block's `render_callback`.

This is necessary for the flow described in https://github.com/WordPress/gutenberg/issues/22096.

**Comment by draganescu** [comment]
Each innerBlock of the Navigation block could be a certain type (page, post, link, category etc.) and even showing their own icon? Maybe each of these is a variation of the Link block.

**Comment by noisysocks** [comment]
I updated the title and description to reflect that this is a subtask of https://github.com/WordPress/gutenberg/issues/22096.

**Comment by draganescu** [comment]
#21050 is also related to this by allowing LinkControl so store ID with no URL.

**Comment by noisysocks** [comment]
We could implement this using block variations. For example, Link could support a `type` attribute which is set to `"page"`, `"post"`, etc. Inserting a Page variation would insert a Link block with `{ type: "page", "id": null }`. This would make the Link block prompt the user to pick a page. Picking a page would set `id` and cause the `render_callback` to display the correct URL.
