### ISSUE TITLE
Hide Block Settings - should be Hide Settings

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#22920]
**Describe the bug**
Today, during WordCamp Europe Contributor Day I was reviewing the documentation for the items in the `More options` menu.  I was considering the documentation for Hide Block Settings and realised that it's not just the Block settings that are hidden, it's the whole of the Settings sidebar.
Ditto for the reverse action - Show Block Settings.

So I suggest the menu items be changed to reflect what they actually do.

From | To
---- | --- 
Hide Block Settings | Hide Settings
Show Block Settings | Show Settings

**To reproduce**
1. Go to the Toolbar for any block
2. Click on the More options tool
3. Click on Hide Block Settings
4. Notice that the Settings sidebar is hidden
5. Click on Show Block Settings
6. Notice that the Settings sidebar is redisplayed

**Expected behavior**
Unchanged. Just different labels.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Either
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 8.2.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 -

**Additional context**

**Comment by talldan** [comment]
I tested and agree that seems like a good idea 👍 
<img width="274" alt="Screenshot 2020-06-05 at 1 35 08 pm" src="https://user-images.githubusercontent.com/677833/83840538-6b151000-a731-11ea-855f-2217d82f20a3.png">
