### ISSUE TITLE
Classic block content not saved until block is blurred

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#22935]
Content in a classic block is not saved until the block is blurred. This is different behaviour to other blocks, where content is saved immediately (and by 'saved' I mean the block content is saved outside of the block).

This could lead to a loss of content if a classic block is used and something happens where the window is closed before a blur event happens (i.e. the user closes the window, or Gutenberg crashes).

This also affects the `beforeunload` protection, which is not enabled until the blur occurs.

This was tested in Gutenberg 8.2.1 using MacOS Chrome.

## Steps to reproduce

- Create a new post
- Add a classic block
- Enter some content into the block, but don't click outside of it
![image](https://user-images.githubusercontent.com/1277682/83877325-3f465a00-a732-11ea-8702-8df650f79b0e.png)
- Check the ‘application’ tab in the developer console and note that the Session Storage autosave does not contain content from the block
![image](https://user-images.githubusercontent.com/1277682/83877337-48cfc200-a732-11ea-845e-fbcc62c5a8b8.png)
- When the post is autosaved, note that the database contains a draft post with no content
![image](https://user-images.githubusercontent.com/1277682/83880033-7fa7d700-a736-11ea-954d-575e0bacddcc.png)

- Click out of the block and note that the session storage now contains the content of the classic block, and this is eventually saved to the database.
- Click the 'save draft' to save the post
- Re-edit the classic block and make some changes. Note how the save status still shows 'saved', and doesn't change to 'save draft'
- Click out of the block and note how the save status now changes to 'save draft'.
- Re-edit the classic block, make some changes, and then close the window - no browser `beforeunload` warning is shown

Contrast this to a paragraph block:
- Create new post
- Type into paragraph block and don't click out of the block
- Note the session storage contains the block content
- Note the database contains the content
- Save as draft
- Reedit the paragraph and don't click out of the block
- Note the save status is showing 'save draft'

**Comment by glendaviesnz** [comment]
Similar to #15577
