### ISSUE TITLE
Custom blocks cannot be edited, selected, or deleted after upgrade to 5.4.1

### ISSUE THREAD

**Issue by chrisbuck** [WordPress/gutenberg#22941]
A custom block type (via plugin) works as expected on WP 5.3.3 running "Twenty Twenty" (1.1).

However, the same custom blocks fail on 5.4.1. The failing blocks include forms and inputs, none of which can be selected or changed. And the block itself can't be deleted, though it can be added in the page editor.

Is there any reason for this difference in behavior between versions?

**Comment by talldan** [comment]
@chrisbuck That sounds unexpected. Which custom block is this happening with?

**Comment by talldan** [comment]
Closing, as there's not been any clarification on this issue.
