### ISSUE TITLE
ComboboxControl: Display all available options on focus

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#22950]
The behavior of the ComboBox implemented from https://github.com/WordPress/gutenberg/pull/19657 does not open the available options when the combobox is focused. Thus, there is no way to know what options are available to you to know what to search for in the combobox search.

The combobox may have many, many options which could be overwhelming. To prevent this, I suggest limiting the options list to show 5 - 10 items max. The rest of the options can be hidden via an overflow scroll container.

Further explanation and context here: https://github.com/WordPress/gutenberg/pull/19657#issuecomment-638412385

**Comment by adamsilverstein** [comment]
@jeryj This one is is not longer reproducible: the control shows it's available options on focus in my testing. 

Closing this as fixed, if you feel I missed something, please feel free to re-open.
