### ISSUE TITLE
Add aliases for block names so they're easier to find in search

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2295]
I was looking to add an `<hr />` to my post, and searched for a couple different things:
- hr
- Line
- Horizontal
- Divider

...And none of those worked. Eventually I just went and found it manually.

Could we add some aliases to blocks so they're easier to find through imprecise searches?

**Comment by youknowriad** [comment]
We already have the "keywords" property for this purpose. It's just a matter of defining which keywords to apply for each block. Noting that we limited this to 3 keywords per block to avoid abusing this feature by third party plugins.

**Comment by aduth** [comment]
>Noting that we limited this to 3 keywords per block to avoid abusing this feature by third party plugins.

I meant to follow-up on this in the other pull request: Is this something we really care to enforce? What is the scenario where a plugin abuses this?

**Comment by mtias** [comment]
We have added several keywords to blocks. Closing as done. (If we have more ideas let's open specific issues for them.)
