### ISSUE TITLE
Spacer Block: Add custom unit support for height control  

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#22956]
Just like the Cover block, it'd be nice to add custom unit support for Spacer height control.

Especially, the viewport relative units would be useful to accommodate different viewport sizes. In addition to `vw` and `vh`, it would be really nice if it also supports `vmin` and `vmax` as well.

<img width="133" alt="Screenshot 2020-06-06 at 00 08 45" src="https://user-images.githubusercontent.com/908665/83929059-ed312300-a789-11ea-8569-c6e819aaf8e7.png">

**Comment by mtias** [comment]
@ItsJonQ looks like we could just apply the work from the Cover block height resize here.

**Comment by ItsJonQ** [comment]
@iamtakashi Oo! We can do that 💪 

Also, we can add `vmin` and `vmax` units :)

**Comment by iamtakashi** [comment]
Yay, thank you in advance!

**Comment by ItsJonQ** [comment]
![spacer-units](https://user-images.githubusercontent.com/2322354/86972893-a7c59400-c141-11ea-9fc6-23576dd6fc48.gif)

Oh boy!

**Comment by iamtakashi** [comment]
@ItsJonQ Sorry for missing the ping. (I read the last update in the email notification that came before the ping was added :) )

> I have to flip the unit back to px the moment the user drags the Spacer height.

I've noticed the issue (the persistent unit with resizing handle) in Cover block the other day. Flipping back to `px` unit is definitely progress as at least it's accurate. Ideally, the user should be able to change the height using the handle without worrying the unit, but I was wondering if that can be tackled in a separate enhancement issue so that we can push this out. What do you think?

**Comment by ItsJonQ** [comment]
> Flipping back to px unit is definitely progress as at least it's accurate

I don't think there's a way to accurately accommodate non `px` units when dragging with the handle 🤔 .

For example, if the unit is set to `vh`. Let's say the current value is `20vh`.

Dragging the handle down `1px`, would bump it to `21vh`, causing the height to jump considerably more than what was dragged.

If that experience is okay, then that may be something we could try.

The other tricky thing is `rem` and `em`. These values will almost certainly be accurate when rendering on the front-end. This is based purely on how the WP-Admin + Theme styles are rendered. Unfortunately, I don't think there's a way to predictably calculate this (unless we do some really really funky stuff)

**Comment by iamtakashi** [comment]
Makes sense. I don't want that to hold this up, and flipping back to `px` unit when we use the handle makes sense to me 👍

**Comment by mtias** [comment]
Is there anything pending here @iamtakashi @ItsJonQ? :)

**Comment by kjellr** [comment]
Any chance we can pick this back up? I think this would be helpful for block patterns in Twenty Twenty-One (https://github.com/WordPress/twentytwentyone/pull/370)

**Comment by jasmussen** [comment]
Just ran into needing this one. It would really benefit responsive design as well.

**Comment by kjellr** [comment]
Does someone have a little time to pick this up again? Now that we use custom units for just about all other spacing tools, it seems really weird to disallow them for the spacer block.

**Comment by mghenciu** [comment]
++ for this.

Would be really helpful, **especially in a Mobile context**. Because most of the time a spacer used for Desktop view, is too large for the Mobile view. 
For example a Page Heading with 150px Spacer before & after, would look good on Desktop
![image](https://user-images.githubusercontent.com/52494172/139830271-f4186526-222a-4797-8a68-083fbf112cbe.png)
 but not on Mobile:
![image](https://user-images.githubusercontent.com/52494172/139830549-6e72c1ee-a8a6-431a-885f-e3df371e3864.png)

**Comment by apeatling** [comment]
Fixed in #36186
