### ISSUE TITLE
New properties for 'rich-text' component

### ISSUE THREAD

**Issue by rinkuyadav999** [WordPress/gutenberg#22965]
What if anyone want to add something like HTML or text before and after the value of RichText. Like:

```
<RichText
tagName={ 'h1' }
beforeValue = { holdHTMLbefore() }
afterValue = { holdHTMLafter() }
value={ myContent }
onChange={ ( value ) => setAttributes( { myContent: value } ) }
/>
```

If we will have these two new properties then output will be : holdHTMLbefore() myContent holdHTMLafter().

Now:

```
<RichText
tagName={ 'h1' }
value={ holdHTMLbefore() + myContent + holdHTMLafter() }
onChange={ ( value ) => setAttributes( { myContent: value } ) }
/>
```

holdHTMLbefore() and holdHTMLafter() //  functions holding HTML

It will not work because value will be pass in onChange and it will contents + HTML of both functions.

**Comment by ellatrix** [comment]
What is your use case?

**Comment by rinkuyadav999** [comment]
Hi @ellatrix 

Actually i want to add icon before the contents and in same tag h1 like:

```
<h1><span class="fa fa-thumb-up-o"></span> Rich Text Contents.</h1>
```

**Comment by ellatrix** [comment]
Would using before and after pseudo elements work?

**Comment by rinkuyadav999** [comment]
Hi

Do not know how to push using CSS but I want to push ```iconStyleValHTML``` after opening h1 tag / before rich text contents. like:

```
const iconStyleVal = ( iconStyle == 'solid' ? 'fas ' : 'fab' );

const iconStyleValHTML = function() {
	if( icon != '' && IconStatus ) {
		return '<span class="' + classnames( iconStyleVal, 'fa-' + icon, 'iconpadding' ) + '"></span> ';
	} else {
		return '';
	}
}
```

Like:

```
<RichText
tagName={ 'h1' }
value={ iconStyleValHTML() + myContent }
onChange={ ( value ) => setAttributes( { myContent: value } ) }
/>
```

**Comment by rinkuyadav999** [comment]
Seems ::before does not work because is adds contents as it is instead HTML. Like:

```
#clinet-id h1::before {
	content: "<span class='fas fa-fa'></span>";
}
```

**Comment by ellatrix** [comment]
Maybe this helps https://stackoverflow.com/questions/50559526/how-to-add-the-font-awesome-icon-in-after-before-elements

**Comment by rinkuyadav999** [comment]
Yes, i will need to use before pseudo element and pass icon unicode as content and set font-family base on style of icon.

I will try this method.

Thank you very much

**Comment by paaljoachim** [comment]
Should this issue be closed? Or are there some actionable items here?

**Comment by talldan** [comment]
Seems resolved. Let's close.
