### ISSUE TITLE
Image block open with RichText

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#22984]
When i open the Image Block in 8.2.1 then is open the RichText "Write caption" 
This is not in WP5.4 and not in Gallery Block.

![WPBug](https://user-images.githubusercontent.com/6922544/83976872-2a69f200-a8fd-11ea-904e-74c598ee9f61.png)

The Code:

![Bildschirmfoto 2020-06-07 um 20 24 21](https://user-images.githubusercontent.com/6922544/83976916-669d5280-a8fd-11ea-944d-99a309384bfd.png)

isSelected is "true" by open the Block. But why?

**Comment by aktasfatih** [comment]
When you add a new component, that component gets selected automatically. So, isSelected becomes true.

**Comment by Soean** [comment]
I think it was introduced in #22295. The caption should not be selected after the image block was inserted. Maybe @ellatrix can have a look?

**Comment by talldan** [comment]
Looks like this is fixed by #23027
