### ISSUE TITLE
Navigation Block: Consider rewording placeholder instructional text 

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#22987]
With the new features for creating Navigation blocks from Pages, Menus or Empty in https://github.com/WordPress/gutenberg/pull/18869 there has been a lot of discussion about wording for the instructional text.

This Issue tracks the need to revisit the pieces of text once https://github.com/WordPress/gutenberg/pull/18869 is merged.

This approach was suggested by [@talldan](https://github.com/WordPress/gutenberg/pull/18869#discussion_r435107636 ) and [@karmatosed](https://github.com/WordPress/gutenberg/pull/18869#pullrequestreview-424494445) in their reviews.

Some useful links to discussions about alternative wording:

- https://github.com/WordPress/gutenberg/pull/18869#discussion_r435107636
- https://github.com/WordPress/gutenberg/pull/18869#issuecomment-639487773

**Comment by talldan** [comment]
I left a few more comments than those mentioned above. The copy I felt could be improved:

- "Select where to start from…", doesn't seem like a very natural phrase. My suggestion was "Choose a starting point…", @paaljoachim also mentioned "Select an option…", which I think is better.
- "Create a navigation from all existing pages, or create empty.", 'create empty' sounded unusual to me, my suggestion was "Create an empty navigation or create from existing pages.".
- "Create a navigation from a menu or create empty.", similarly here my suggestion was "Create an empty navigation or use an existing menu."
