### ISSUE TITLE
React licensing

### ISSUE THREAD

**Issue by enjikaka** [WordPress/gutenberg#2298]
I searched through the issues and there seems to be none on the topic that React is not truly open source, and how this might very well become a problem for every one using WordPress if Gutenberg is merged into the main product.

Here's some links for reference.

VMware disallowed usage of it after their legal department looked at the licence:
https://discuss.reactjs.org/t/legal-department-did-not-allow-use-of-react/3309/5

Another lawyer evaluating the licence:
https://www.elcaminolegal.com/single-post/2016/10/04/Facebook-Reactjs-License

Apache recently banning use of React due to this licence:
https://www.theregister.co.uk/2017/07/17/apache_says_no_to_facebook_code_libraries/

> /.../ BSD-plus-Patents license includes provisions that mean if you, directly or indirectly, accuse Facebook of patent infringement, you lose the right to use and distribute Facebook's code.

**Comment by ntwb** [comment]
Facebook are currently considering re-licensing React (and many others)

See https://github.com/facebook/react/issues/10191

**Comment by grantpalin** [comment]
Looks like Facebook are not budging - https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

**Comment by cristeagc** [comment]
I don't understand something...
Facts:
1. WordPress/gutenberg and WordPress/WordPress is under GNU GPL (GNU General Public License) with "either version 2 of the License, or (at your option) any later version".
2. Facebook React is using Facebook BSD+Patents license.
3. 1 and 2 are both on [category-x](https://www.apache.org/legal/resolved.html#category-x)

So my question is, why is Wordpress affected by the apache license changes?

**Comment by dmccan** [comment]
It seems from the discussions I've seen on the Tavern and elsewhere that there are strong **opinions** on both sides.  

I think that if the React license is considered by the Free Software Foundation (GNU.org) as compatible with the GPL version 2 then it is OK. If the Free Software Foundation finds that the React license is not compatible then that's a deal breaker for including it in WordPress. 

On GNU.org they have a list of GPL-compatible and GPL-incompatible licenses: 

http://www.gnu.org/licenses/license-list.html

I've asked them if they would please take a look at the Facebook BSD+Patent license and give a judgment (add it to one of the lists). We will see if/what we hear from them.

**Comment by enjikaka** [comment]
Even without or without the licence, using the web platform - web components - seem like a way better solution. (It does not only drop the worries of the React licence for everyone, but also provides everything React has except the vDOM natively). 

Has there been discussion on using the web platform contra React? Polymer Summit 2017 just ended and there was some good talks on CMS and building enterprise UIs with web components.

Most relevant talks;

- Building UI at Enterprise Scale with Web Components
- End to End Apps with Polymer
- Web Components for CMS
- Web Components: Just in the Nick of Time

( .https://www.youtube.com/watch?v=0A-2BhEZiM4&list=PLNYkxOF6rcIDP0PqVaJxqNWwIgvoEPzJi&index=6 )

**Comment by dmccan** [comment]
I received a response from the Free Software Foundation that they are in the process of reviewing it for inclusion on their license list.

**Comment by timhibberd** [comment]
Caveat Emptor (my ass covering): The following post comment is an opinion. I am not a lawyer. Use this information at your own risk. I assume no liability for decisions based on this opinion.

Based on my review of the Facebook license IF WordPress.org chooses to include REACT components the consequence of the Facebook open source license for a user is as follows:

IF a user of WordPress has patents that Facebook infringes AND the user chooses to assert their patent against Facebook, they can...but any WordPress based solutions they are using (e.g. intranet, extranet or public website) would need to be decommissioned. This is not a show stopper for the user. They would simply migrate to another non-react based CMS assuming the anticipated value of the patent royalties is expected to exceed the migration cost.

NOTE: WordPress-to-Drupal migtrations may increase based on a WordPress decision to include REACT components (assuming Drupal does not include REACT components as well).

Unless my interpretation of the license is incorrect, for users who don't file patents or intend to file patents, this clause is a non-issue.

The most definitive discussion of the meaning / impact of the Facebook license can be found here:
https://github.com/facebook/react/issues/7293

If you are a supplier of managed WordPress I would suggest it would be good practice to inform your users of this consequence of implementing WordPress should WordPress.org choose to include REACT components or any other Facebook open source licensed in this fashion.

If you are a reseller of WordPress based software products AND you file patents or intend to file patents...you will have a decision to make. A patent assertion you make against Facebook may impact your customers depending on how you structure your product licenses (e.g. WordPress-based SaaS).

Just one man's two cents worth :-)

**Comment by gschoppe** [comment]
I think there is an issue beyond the question of whether it is ruled GPL-compatible or non-GPL-compatible. As VMWare proves, it is enough of a change from the standard terms of OSS licensing that some legal departments have ruled it unacceptable. That should be enough to give serious pause to the idea of integrating it into the core of the widest-used CMS every built.

The choices made by WordPress don't just have to be acceptable to WordPress. They need to be acceptable to the entire community, which certainly includes companies with cautious legal departments.

**Comment by stefanos82** [comment]
I came here after I read more about Gutenberg and found out it uses React.

I have the same concerns as you guys about the license and two things came in mind:

1. Why not move to Preact from React for the sake of compatibility, assuming you go with the use of `preact-compat`, that comes with a safer license (MIT)?
2. Why not move all together to Vue.js which is developed by a single person and not a company the same of FaceBook, plus it's under a safe license, that of MIT?

Thoughts?

**Comment by ntwb** [comment]
https://ma.tt/2017/09/on-react-and-wordpress/

> _"That post won't be published, and instead I'm here to say that the Gutenberg team is going to take a step back and rewrite Gutenberg using a different library. It will likely delay Gutenberg at least a few weeks, and may push the release into next year."_

**Comment by enjikaka** [comment]
I'm happy to help rewriting to web components and/or Vue.js!

**Comment by ntwb** [comment]
Please see #2733 for discussing alternatives 😄
