### ISSUE TITLE
Last element in "Latest Posts" block has wrong right margin

### ISSUE THREAD

**Issue by jasomdotnet** [WordPress/gutenberg#22991]
Last element in "Latest Posts" block has wrong right margin. See [picture](https://i.imgur.com/h1tOcPf.jpg). My block settings are [here](https://i.imgur.com/F6Gkak5.jpg).

There should be something like this:

```
li::last-child {
 margin-right: 0;
}
```
in `block-library/style.min.css`

**Comment by annezazu** [comment]
@jasomdotnet Thanks for sharing this! Of note, I was able to replicate this right margin issue  using Gutenberg 8.3 and WordPress 5.4.2 with the Twenty Twenty theme.

**Comment by carolinan** [comment]
I tested this and found that it was solved by #25688. I am closing this issue.
