### ISSUE TITLE
Post thumbnail in "Latest Posts" block is not clickable

### ISSUE THREAD

**Issue by jasomdotnet** [WordPress/gutenberg#22992]
Pretty simple to describe: Post thumbnail in "Latest Posts" block is not clickable. There should be option to add permalink to post.

This is not a "feature request", it is "bug report" :D

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; there's already an existing issue for this. Any progress can be tracked there https://github.com/WordPress/gutenberg/issues/21530

**Comment by jasomdotnet** [comment]
Ok, so I closed this.
