### ISSUE TITLE
Limit number of categories/tags checked

### ISSUE THREAD

**Issue by mdrick** [WordPress/gutenberg#23005]
Hi,

With the Classic WordPress interface I could limit the number of checkboxes checked (example 3 checkboxes maximum) easily with jQuery.

Now with Gutenberg it's much more complicated.

I tried to change classes in my jQuery code but without success. In what WP Data can I have the number of checkboxes checked ? Can I have some help please ?

```
jQuery(window).load(function() {
    var limit = 3;

    $('.edit-post-sidebar input.components-checkbox-control__input').on('change', function(evt) {
        if($(this).siblings(':checked').length >= limit) {
            this.checked = false;
        }
    });
});
```

**Comment by annezazu** [comment]
@mdrick Thanks for asking about this! However, this isn't the best place for general support. Issues opened here are dedicated to the development of Gutenberg. The best place to get help with the problem that you are experiencing is the [WordPress.org Support Forums](https://wordpress.org/support/). I'm going to close this issue as a result.
