### ISSUE TITLE
Autosave deletes contents of block if block has focus

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#2300]
If you are typing in a block, and autosave fires, contents of the block are deleted
Seems to happen only on the first firing of autosave in a new document

![autosavebug9aug2017](https://user-images.githubusercontent.com/25762760/29100284-fe95c5c0-7ced-11e7-9564-58f730d03f54.gif)

**Comment by aduth** [comment]
Suspected that regression was introduced in #2210.

Self-assigned.

**Comment by aduth** [comment]
Bisect reveals da5cbe7122b913e77efcefacf384f3466bf251cd as problematic commit.

**Comment by iseulde** [comment]
Also ran into this just now. The contents were not deleted, but I lost focus and the paged was scrolled to the top.
