### ISSUE TITLE
Buttons block not really center aligned.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23010]
**Is your feature request related to a problem? Please describe.**
The Cover Block contains a new grid alignment option icon.
Adding a title. Parent Block grid icon is at center point.
Child block with the title is also center aligned.

<img width="644" alt="Screen Shot 2020-06-08 at 23 27 01" src="https://user-images.githubusercontent.com/5323259/84082117-958bf500-a9df-11ea-9468-17bbed8159d5.png">

Adding a Buttons Block which is also centered aligned the result looks like this:
<img width="652" alt="Screen Shot 2020-06-08 at 23 29 59" src="https://user-images.githubusercontent.com/5323259/84082355-ffa49a00-a9df-11ea-80a0-cbc844d17c1c.png">

Selecting title and button:
<img width="649" alt="Screen Shot 2020-06-08 at 23 30 40" src="https://user-images.githubusercontent.com/5323259/84082412-164af100-a9e0-11ea-8392-f41259693391.png">

The buttons block is off center as can be seen above.

**Describe the solution you'd like**
I would like to have the button center aligned. So that for instance can be used in a Cover Block.

**Comment by jasmussen** [comment]
Yep, this frustrates me too. I could swear there was a ticket for this already, but I can't find it.

What it boils down to is that the appender takes up space vertically, which offsets the centering. To further complicate things, this appender only shows up when the preceeding block is not a text block. Observe how a paragraph is perfectly centered:

<img width="687" alt="Screenshot 2020-06-09 at 08 34 49" src="https://user-images.githubusercontent.com/1204802/84114272-5d5ed380-aa2c-11ea-904d-be18deaa82cc.png">

But a buttons block is not:

<img width="748" alt="Screenshot 2020-06-09 at 08 35 01" src="https://user-images.githubusercontent.com/1204802/84114278-60f25a80-aa2c-11ea-8ad2-57602b365f72.png">

At least we now hide the appender when the parent block isn't selected:

<img width="670" alt="Screenshot 2020-06-09 at 08 36 18" src="https://user-images.githubusercontent.com/1204802/84114299-694a9580-aa2c-11ea-82d7-56ce0ac78b72.png">

But it would be nice both if we could clean up and simplify the heuristic for when the appender shows up (I think @ZebulanStanphill may have a ticket for this?) and find a solution for making the appender not take up space. Can it be floated and absolute positioned to take it out of the flow? Would that cause bad overlap? Worth exploring.

**Comment by paaljoachim** [comment]
A little Buttons Block label search and I found this issue:
**Buttons Block: Centre aligned button isn't centre in the editor**
https://github.com/WordPress/gutenberg/issues/21805

I'll close the issue I made.

**Comment by ZebulanStanphill** [comment]
@jasmussen I think the issue you're thinking of is #13571.
