### ISSUE TITLE
Cut/copy and Paste broken within HTML  and Shortcode blocks

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#23040]
Affected Blocks

- HTML Blocks
- Shortcode blocks, and the 
- Edit as HTML option of Text and Image blocks.

When text is selected and copied, the entire block code is copied to the clipboard and not just the selected text. This runs contrary to established (and expected) UI rules.

**To reproduce**
1. Create a shortcode or HTML block
2. Attempt to copy and paste selected text from within the block
3. See the error, you cannot do it, it pastes the entire block.

**Expected behavior**
Only the selected text should be copied to the clipboard.

**Screenshots**
Not necessary this error is self-obvious.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin.
- If the Gutenberg plugin is installed, which version is it? 8.2.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 77.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by talldan** [comment]
Thanks for reporting @gsallman, looks like this was fixed by https://github.com/WordPress/gutenberg/pull/22793 and the fix should be in v8.3 of the plugin.
