### ISSUE TITLE
It is an Overlay Opacity and not a Background Opacity

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#23056]
Imo the term of this is not correct. Not the opacity of the background is changed. The opacity of the overlay is changed, so this is not background opacity. It is overlay opacity.

![overlay_opacity](https://user-images.githubusercontent.com/1585416/84273114-90898b80-ab2e-11ea-9561-7f7a9453142f.jpg)

**Comment by talldan** [comment]
It was probably intended to refer to the background of the overlay, but if that was the case I do think the distinction isn't needed and is confusing.

My feeling is that the setting is already in the 'Overlay'  panel, the label could be changed to just 'Opacity'.

**Comment by michelleweber** [comment]
For copy, +1 to simply "Opacity."
