### ISSUE TITLE
'Top Toolbar' not properly located contextually

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#23059]
**Is your feature request related to a problem? Please describe.**
Yes, it is a problem.

**Describe the solution you'd like**
The 'Top Toolbar' preference from the right top menu doesn't work as expected. A floating block menu is contextual and hangs near the current block being edited. When selecting 'Top Toolbar' the menu is placed in the very top menu bar. This is not the place for this menu. The top menu bar is for menu activities related to the overall article, not to the current block. 

Contextually, a block menu for the current block should attach to top of the block itself, like the floating menu. For each block selected, a menu will appear attached to the top of the block. It makes no sense to add a contextual menu to the top menu bar which isn't intended to be contextual in nature.

This is particularly a problem considering how Wordpress.com has implemented this. When no block is selected, it looks like 'No Menu' with nothing there. When you select a block, it appends the block's contextual menu to the end of the top menu. See images. 

This is wrong. If anything, it should place a contextual menu below the top menu bar so that it is shown to be distinctly different from the top menu bar. When it is appended to this existing bar, it doesn't make sense to be there and is easily missed. It took me minutes to find that this menu had been appended in this location. 

It doesn't make sense to be here and it's not intuitive. For a contextual menu, it's also too way far away from the block in terms of mouse movement. Ergonomics play a factor here and should be considered in contextual menu design.

![Screen Shot 2020-06-08 at 5 17 30 PM](https://user-images.githubusercontent.com/16678592/84276368-21d50f80-aae7-11ea-8abf-0f4e381e2534.png)
![Screen Shot 2020-06-08 at 5 18 41 PM](https://user-images.githubusercontent.com/16678592/84276371-226da600-aae7-11ea-9cc9-e16ef0439848.png)

**Describe alternatives you've considered**
There is no alternative to solving this problem without reworking this design.

**Comment by mapk** [comment]
There are further explorations happening here: https://github.com/WordPress/gutenberg/issues/20592. For this reason, this feels like a duplicate.
