### ISSUE TITLE
Editor: "More menu" improvements

### ISSUE THREAD

**Issue by joanrho** [WordPress/gutenberg#23076]
I was looking into the various links inside the More menu in the Editor and took a stab at simplifying, consolidating, and clarifying the items listed there. Here's a before/after screenshot of the current More menu alongside some proposed changes:

<img width="1003" alt="Screen Shot 2020-06-10 at 2 23 27 PM" src="https://user-images.githubusercontent.com/204742/84314887-0d643780-ab26-11ea-9c77-8a17f73bf646.png">

**Changes include:**
- Moving the "Block Manager" and "Manage all reusable blocks" links into the Block Inserter. The latter already exists at the bottom of the Block Inserter, so this change would remove this duplicate instance. IMO, we should just combine the two under a single "Block Manager" link that calls forth the existing block manager modal that contains the text link to the "Manage reusable blocks" page — I shared a screenshot below towards the bottom of this Issue.
- Removing the Welcome Guide link is still TBD as I'm working on early ideas around a more permanent contextual guidance system that can replace the need for this modal tour (most users tend to skim or skip these tours). Will share more on that in a separate Issue.
- "Copy all content" felt out of place here, as it relates to copying all of the content within the current document at hand. One idea could be to move it somewhere within the Document panel, which currently has "Document settings" options like "Status & visibility", "Permalink", "Categories" (on Posts), "Tags" (on Posts), "Featured Image", "Excerpt" (on Posts), "Discussion", "Page/Post Attributes". Copying all content feels more like a "Content Settings" option, so I wasn't sure if it made the most sense in the Document Panel as it exists today.
- Changing "Help" (which currently links to https://wordpress.org/support/article/wordpress-editor/) to "Help Center" and placing it in a separate "Support" section.
- Changing "Options" to "Panel Options" and moving this up to the "Tools" section.

Some adjacent topics these changes touch on that'll eventually need to get addressed (likely separate from this specific Issue) include figuring out how to make Blocks, Block Patterns, Reusable Blocks, and Template Parts easily accessible from/categorized within/managed from the Block Inserter. Screengrab GIFs of the [top bar block inserter](https://d.pr/i/gZHSur) and [inline block inserter](https://d.pr/i/RiAAAP) for context. To start, I think moving the Reusable blocks up in hierarchy makes sense since users will be creating these on their own and likely to reuse them with some frequency compared to other block group categories. As mentioned above, I also think we should bump up the "Manage blocks" link and nest a link to "Manage reusable blocks" within that modal:

<img width="376" alt="Screen Shot 2020-06-10 at 2 50 20 PM" src="https://user-images.githubusercontent.com/204742/84317289-c6784100-ab29-11ea-8ac1-d582e2600122.png">

Would love to continue the discussion here if folks think these changes make sense or not. These are only early ideas, nothing actionable at this point.

**Comment by MichaelArestad** [comment]
Thanks for writing this up!

> Moving the "Block Manager" and "Manage all reusable blocks" links into the Block Inserter. 

I'm glad you brought these up. I think both of these could have better naming and a better place to live. I'm not sure if the Inserter is the ideal/expected location or not, but the argument can be made.

As for the naming, they both are very similar:
* Block manager: enable/disable blocks
* Manage all reusable blocks: go to a custom post type list and... do something?

Both could likely be combined in a different interface. Likely best discussed in another issue.

> Removing the Welcome Guide link is still TBD 

Let's remove it. It's a one and done thing.

> "Copy all content" felt out of place here, as it relates to copying all of the content within the current document at hand. One idea could be to move it somewhere within the Document panel, which currently has "Document settings" options like "Status & visibility", "Permalink", "Categories" (on Posts), "Tags" (on Posts), "Featured Image", "Excerpt" (on Posts), "Discussion", "Page/Post Attributes". Copying all content feels more like a "Content Settings" option, so I wasn't sure if it made the most sense in the Document Panel as it exists today.

I think I would leave it in this menu for now. It does make me think it might be a good enhancement to invest in a custom alt-click menu like Google docs where something like this feature could better be served.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/1123119/84798325-0ae75f00-afb8-11ea-8df6-7185d52ee27e.png">


> Changing "Help" (which currently links to https://wordpress.org/support/article/wordpress-editor/) to "Help Center" and placing it in a separate "Support" section.

👍 

> Changing "Options" to "Panel Options" and moving this up to the "Tools" section.

I am unsure of that name change. It likely should be "Editor settings" or something along those lines.

> To start, I think moving the Reusable blocks up in hierarchy makes sense since users will be creating these on their own and likely to reuse them with some frequency compared to other block group categories. 

Can you create another issue for this? Reusable blocks are some of the most used blocks across sites so there is definitely value in moving them from the bottom of a list.

**Comment by joanrho** [comment]
@MichaelArestad Thanks for the feedback!

Re: Moving the "Block Manager" and "Manage all reusable blocks" links into the Block Inserter — The More menu just feels more relevant to the Editor and Editor Settings vs Block settings. The Block Inserter already contains a text link for "Manage all reusable blocks", so it felt intuitive to replace that link with "Block Manager" and then nest the "Manage all reusable blocks" within the Block Manager modal (as shown in my mock). I'm open to other suggestions on where this makes the most sense, so please feel free to share any other ideas you may have.

Great example with the GDocs custom right click menu. I could also see items like "Content Structure" (which currently lives in the top left toolbar), "Visual/Code Editor" modes and "Keyboard Shortcuts" (which currently live in the More menu) populating such a menu. Is this something that's been discussed for Gutenberg yet? If not, happy to open an Issue to start the discussions around it.

Re: separate Issue for the Reusable blocks placement in the Inserter, you got it. Will file that today.

**Comment by jordesign** [comment]
This issue still _could_ be valid - but given the number of interface changes (including the more menu) I'll close it. We can always re-open with new context if needed.
