### ISSUE TITLE
Group Block: Selecting the group block using the Parent button doesn't properly update the focus.

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#23071]
This might be a little confusing to explain, so stick with me. Import to note this appears to be only in Firefox.

1. Add a Group block to your document.
2. Add a Paragraph block _inside_ this new group block.
3. Select the Group block.
4. Set the Group block's width to Wide or Full, and give it a background color.
5. Now, select the Paragraph block and use the Parent Button to select the Group block.

Now, sometimes you'll end up with _both_ the Group block and the Paragraph block focused, but displaying the Group block toolbar:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/191598/84302118-d80a1a80-ab22-11ea-8e8e-cb89380d4821.png">

And sometimes you'll end up with _only_ the Paragraph block focused, but displaying the Group block toolbar. (/cc @MichaelArestad )

**Comment by talldan** [comment]
Seems to have been resolved in more recent versions, so closing the issue.
