### ISSUE TITLE
The new Gutenberg editor and the future of Meta Box

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#2308]
As discussed in #952, this lists all the hooks that are used in [Meta Box](https://metabox.io) plugin. I hope that can help making the plugin works with Gutenberg:

- Scripts, styles are enqueued using `admin_enqueue_scripts`. We do check for the current screen (via `get_current_screen`) to make sure scripts and styles are enqueued only for that pages. For the core plugin, it checks by post types. For extensions (term meta, user meta, settings page), it checks more for taxonomies, user profile page or settings pages.
- We also use `print_media_templates` to print Underscore templates.
- Scripts we use in the plugin includes: color picker, underscore, backbone, media scripts, tinymce (for the editor field)
- We use `init` to initialize all the hooks for the plugin.
- Meta boxes are registered using `add_meta_boxes` hooks.
- Hidden meta boxes use `default_hidden_meta_boxes`.
- We also hook to `post_edit_form_tag` to allow upload files.
- We use `save_post_{$post_type}` and `edit_attachment`, `add_attachment` to save meta values for posts and attachments.

**Comment by mtias** [comment]
Going to close so we have a single point of reference. Would you mind adding your comment on #952 again?
