### ISSUE TITLE
Buttons Block: Adjusting vertical alignment makes buttons jump up/down the page.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23087]
**Describe the bug**
Adjusting the alignments in the Buttons vertical block makes it jump up or down the page.

Regarding alignment.
It seems like it jumps up and down the page at the same time one clicks the alignment icons.
![Buttons-alignment](https://user-images.githubusercontent.com/5323259/83752875-8f0d1e80-a669-11ea-9856-bc2266c58134.gif)

For instance with alignment (none) 
![Screen Shot 2020-06-04 at 13 46 54](https://user-images.githubusercontent.com/5323259/83753092-ed3a0180-a669-11ea-88b6-f6dfaf7ed4dd.png)

Then switching to alignment right. Is lower than alignment none.
![Screen Shot 2020-06-04 at 13 47 14](https://user-images.githubusercontent.com/5323259/83753108-f9be5a00-a669-11ea-9fcd-ba4ac3978f5a.png)

**To reproduce**
1. Add a Buttons Block.
2. Add some buttons.
3. Make it vertical.
4. Change alignments left/center/right.
5. Notice how changing alignment also makes the block jump up/down the page. 

**Expected behavior**
Changing alignment should keep the Buttons Block evenly on the page. So it does not jump up/down.

Chrome
Twenty Twenty
WP 5.4.2
Gutenberg plugin 8.3

**Comment by kellychoffman** [comment]
@paaljoachim - I'm no longer able to replicate. Can you confirm this is still happening?

**Comment by paaljoachim** [comment]
Hey @kellychoffman 

You are right this has changed. The Buttons block has been modified since I made this issue.
Thank you for noticing! Closing the issue!
