### ISSUE TITLE
Lower/Uppercase Strings

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#23094]
**Describe the bug**
I started the translation of Gutenberg 8.3 for german and saw the new string 'Color Settings'. Because I was sure that we already translated this string, I looked where it came from:

```jsx
const title = isWebPlatform
		? __( 'Color settings' )
		: __( 'Color Settings' );
```
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/color-edit.js#L61-L63

Why are we doing this? So we always have 2 different translations for the strings. If we really need this, is there an anternative like using CSS?

**Comment by gziolo** [comment]
@pinarol or @hypest, any ideas why we use two different strings here?

**Comment by pinarol** [comment]
@iamthomasbishop Is this an intended thing on mobile side to use capitalized first letter per word for section titles? I think we should keep platforms same and use what web is using, which is `Color settings`. Wdyt?

**Comment by mtias** [comment]
I'm seeing this doesn't seem relevant anymore in the source code.

**Comment by hypest** [comment]
For context, [we're moving to Sentence case on mobile too](https://github.com/WordPress/gutenberg/pull/30075#discussion_r613371186) so yeah, thanks for closing this one as not relevant anymore @mtias 🙇
