### ISSUE TITLE
Awkward scrolling flow with block toolbar and editor toolbar

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#23107]
**Describe the bug**

When scrolling down the editor with a block selected and the block toolbar showing, it merges awkwardly with the editor toolbar in a way that's jarring. This seems to have been introduced in 8.3 as it works just fine in 8.2.1.

**To reproduce**
1. Create a new post or page
2. Create content that runs down the post/page
3. Select the top block and scroll down so the block and editor toolbar are forced to overlap
4. See strange interaction :)

**Expected behavior**

I'd expect the block toolbar to nicely fall behind the editor toolbar out of view. 

**Screenshots**

8.3 scrolling
![8 3 scroll](https://user-images.githubusercontent.com/26996883/84462933-21db2980-ac25-11ea-8caa-7776c85ff8f5.gif)

8.2.1 scrolling
![8 2 1 scroll](https://user-images.githubusercontent.com/26996883/84462992-4505d900-ac25-11ea-9720-00430816ea95.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg installed
- If the Gutenberg plugin is installed, which version is it? 8.3

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: 83.0.4103.61

**Comment by mapk** [comment]
@annezazu, I believe this is resolved? Can you double check? I was testing in Gutenberg 8.5.

![scrolling](https://user-images.githubusercontent.com/617986/87839644-99b5f880-c850-11ea-9937-59887d4bb01c.gif)

**Comment by annezazu** [comment]
Whew! Can confirm all good here. Closing :)
