### ISSUE TITLE
Disable rich image tools for external URLs

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#23100]
**Describe the bug**
Images with external URLs are not editable, so the rich image buttons shouldn't be visible.

**Comment by paaljoachim** [comment]
I am also not able to replicate.

I added this image: https://hometown-tourist.com/wp-content/uploads/2015/01/Manhattan-Neighborhood-Street-Scene.jpg

<img width="753" alt="Screen Shot 2021-02-10 at 15 55 28" src="https://user-images.githubusercontent.com/5323259/107526808-838ad380-6bb8-11eb-8b6c-09904bb12847.png">

@Soean 
I will go ahead and close this issue. If it is a mistake then please reopen.
