### ISSUE TITLE
Table Block - Adding More than One or Multiple Rows

### ISSUE THREAD

**Issue by cngodles** [WordPress/gutenberg#23103]
**Problem:**
After adding a table row with a mouse, the focus is removed from the table. Attempting to add a new row immediately, the option to add a new row disappears, as the table has lost focus in the editor.

**Describe the solution you'd like**

- After adding a new row to a table, the selection in the editing screen should be within that new row. That way, adding a second new row, it will work.
- An alternative is to allow the user to enter a number of rows they wish to add.

**Describe alternatives you've considered**

- I did a brief search for table row add shortcuts for Gutenberg, I did not immediately see any.
- I tried using a return to add a new row, however this only adds a content return within the table cell.

![gutenburg-table-row](https://user-images.githubusercontent.com/5685764/84433613-8f269480-abfc-11ea-8afe-ea482c326031.gif)

**Comment by annezazu** [comment]
@cngodles Thanks for reporting this! I just tested this with Gutenberg 8.3 and was able to replicate this odd flow. I dig your offered solutions and bet designers will have a great idea for how to improve this.
