### ISSUE TITLE
Block categories: Inconsistent legacy mappings

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#23118]
**Describe the bug**

When reviewing changes from https://github.com/WordPress/gutenberg/pull/19279, I noticed that the compatibility mappings for legacy block categories appear to have inconsistent mappings in PHP and JavaScript. In PHP `formatting` is mapped to `media`, whereas in JavaScript it's mapped to `text`:

https://github.com/WordPress/gutenberg/blob/84df4bd6082e7793a2befddb2a652cb42f445d21/lib/compat.php#L339-L355

https://github.com/WordPress/gutenberg/blob/84df4bd6082e7793a2befddb2a652cb42f445d21/packages/blocks/src/api/registration.js#L131-L135

I'm not sure how this bug manifests, but I'd expect these mappings to be consistent.

CC: @mtias

**Comment by mcsf** [comment]
The original PR's description does list Text as the destination for Formatting. I guess we should patch the PHP rules, then, and do it quickly so that no mistakes are carried over in the 5.5 PHP backporting process in #23210.

**Comment by gziolo** [comment]
There is no mapping in WordPress core. It’s a simple act of replacing categories 😃

**Comment by mcsf** [comment]
> There is no mapping in WordPress core. It’s a simple act of replacing categories 😃

Looking at https://github.com/WordPress/wordpress-develop/blob/24465974cd6333137490b55ab663f3d1f844a95e/src/wp-admin/includes/post.php#L2180-L2210, category Design still needs to be added.

**Comment by gziolo** [comment]
Design is already there in WordPress core:
https://github.com/WordPress/wordpress-develop/blob/24465974cd6333137490b55ab663f3d1f844a95e/src/wp-admin/includes/post.php#L2191-L2195

I examined code and I think everything looks good. The confusion comes from the fact that the compat layer in PHP only updates the list of default categories and JS does the mapping.

**Comment by mcsf** [comment]
> Design is already there in WordPress core:

Never mind, I don't know how I missed that. 😓
