### ISSUE TITLE
Failed to setup Gutenberg in both local wordpress or Docker - Windows 10

### ISSUE THREAD

**Issue by bilouStrike** [WordPress/gutenberg#23121]
I have tried to setup gutenberg for development, it works fine in macOS, but in windows 10 the two ways have failed (local wordpress enivrement and Docker ):

Here is my host configuration:

- Windows10 Pro 
- Node version: 12.18.0
- Docker : 2.3.0.3
  - Engine: 19.03.8
  - Compose: 1.25.5

Npm install passed fine 💯 

1-  **local WordPress environment**
  command: **npm run build**: failed and return:

![npm](https://user-images.githubusercontent.com/12693924/84534412-23225a00-acea-11ea-9eab-b4bf1363f63e.PNG)

**2- Using Docker :** 
     command:  **npx wp-env start**  return 

![docker](https://user-images.githubusercontent.com/12693924/84534317-fe2de700-ace9-11ea-905d-0a225dbbd382.PNG)

**Comment by paaljoachim** [comment]
See if this documentation which is still being created helps.
https://github.com/WordPress/gutenberg/pull/22831

**Documentation. View on the branch here:** https://github.com/WordPress/gutenberg/tree/add/docs-create-block/docs/designers-developers/developers/tutorials/create-block

**Comment by bilouStrike** [comment]
Thanks @paaljoachim , i've followed those documentations you mention, and this was the results that i posted above.

> See if this documentation which is still being created helps.
> #22831
> 
> **Documentation. View on the branch here:** https://github.com/WordPress/gutenberg/tree/add/docs-create-block/docs/designers-developers/developers/tutorials/create-block
> 
> See if this also helps:
> https://www.youtube.com/watch?v=Vr3KPykhzhw&t=1s

Thanks @paaljoachim , i've followed those documentations you mention, and this was the results that i posted above.

**Comment by paaljoachim** [comment]
Hopefully you'll be able to get some help soon.

**Comment by noahtallen** [comment]
I can try to debug the wp-env issue on my windows computer sometime this week. No promises; I'm kinda busy with other stuff at the moment! 

I've often had issues running node projects in Windows. As a workaround, WSL (windows subsystem for linux) might be able to get it working for you in the short term. Obviously we want to make sure that windows development is supported, so we'll need to try to fix these things.

**Comment by noahtallen** [comment]
I've tried using wp-env on Windows, and I used these instructions to install docker: https://docs.docker.com/docker-for-windows/install-windows-home/

It seems to be working ok for me, not seeing these issues. :thinking:

**Comment by t-hamano** [comment]
I have checked this issue and now believe that such errors don't occur anymore.
As seen in #37189 and #39388, I believe it is now possible to build correctly on the Windows host OS.

I don't know what was going on at the time this issue was reported, but now it should be fine with the latest version of Node 14.
However, as seen in this comment, you may need to use the latest minor version of Node for Gutenberg as well.

> 2- Using Docker :
> command: npx wp-env start return

For this, would the following command work?
```
npm run wp-env start
```

**Comment by noahtallen** [comment]
I'll close this issue now, then :)

And of course, please open another issue if anything starts failing on Windows!
