### ISSUE TITLE
When full-sized image is selected only the large size image is displayed

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#23128]
**Describe the bug**
I add an image to a post and select 'Full size' as the image size option. Neither the Gutenberg editor nor the final post display a full-sized image, only the large version is displayed, resulting in poor image quality. This bug has only recently been introduced. Previous posts with Full-sized images are rendering correctly.

**To reproduce**
1. Create a new post on a computer with a hi-res monitor
2. Load a high res image into a post that will display the image in full-screen width
3. Set the image size option to Full Size, note how the Gutenberg editor displays the large and not the full-sized image.
4. Publish the post and note that the full-sized image is not being displayed -- you can inspect the html to see that this is the case.

**Expected behavior**
I expect the full-sized image to be displayed.

**Screenshots**
You can inspect the rendered HTML on this page: https://www.breakfastinamerica.me/2020/back-at-the-bluffs/

Also, clicking on the image invokes a lightbox plugin that will display the correct image for comparison.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg plugin Version 8.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 77.0.1

**Smartphone (please complete the following information):**
 N/A.

**Comment by dnnsjsk** [comment]
I thought I was going crazy. Experiencing the same problem.

**Comment by annezazu** [comment]
@gsallman thanks for reporting this! I tried testing today with WordPress 5.5 RC and Gutenberg 8.6.1 using the TwentyTwenty theme. Here are posts where you can see each test (both are using the full width template):

Large image: https://annetest.mystagingwebsite.com/2020/07/large-imagee/
Full size image: https://annetest.mystagingwebsite.com/2020/07/2990/

When I inspect the page, I can see each has the right class (ie: wp-block-image size-large & wp-block-image size-full). Can you confirm this is still happening on your end?

**Comment by gsallman** [comment]
I noticed that this was fixed in a recent release. I seem to remember I had to go back and reset image sizes on the images I was originally having problems with. Sorry I didn't think to check the bug report to see if it was marked as cleared.


Gary
________________________________

  Davis-Allman, LLC | 610-A E Battlefield, Suite 102 Springfield, MO 65807 US
(417) 522-5151 | gary@davis-allman.com | www.davis-allman.com<http://www.davis-allman.com>



________________________________

**Comment by annezazu** [comment]
No worries at all, Gary 😄  Just am glad to hear it's fixed. I'll close this out but please do keep reporting as you find things. It's very appreciated!
