### ISSUE TITLE
Placeholders to look more like placeholders

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#23124]
**Is your feature request related to a problem? Please describe.**

With the direction of G2 styling, placeholders look a bit too much like the rest of the UI, with little distinction with it. I suggest modifying the placeholder component a bit to make it more apparent that its drag-and-drop capable (if the prop exists), and stands out as a placeholder more.

Some callouts: 
1. Currently we don't draw any attention to the drag-and-drop nature of the placeholder. It doesn't look, or say, the part. I added a dashed border to draw attention to that, as well as added language for it.
2. I noticed that "Browse" is used a good bit for referencing the uploading of assets online. 
3. I simplified the instructions + multiple call to actions by combining them and using the descriptive text as CTAs. 
4. I moved the Media Library action as the primary here, though we could move it to Browse/Upload if data suggests that's the primary action. 
 
**Current placeholder in full context:**
<img width="1601" alt="Screen Shot 2020-06-12 at 3 47 49 PM" src="https://user-images.githubusercontent.com/1813435/84540778-15f27480-acc4-11ea-80d3-cb7deaa78fb9.png">

**Current placeholder:**
<img width="889" alt="Screen Shot 2020-06-12 at 3 45 54 PM" src="https://user-images.githubusercontent.com/1813435/84540668-e7749980-acc3-11ea-90d1-b67e4e29494a.png">

**Suggested:**
<img width="872" alt="Screen Shot 2020-06-12 at 3 46 24 PM" src="https://user-images.githubusercontent.com/1813435/84540662-e3e11280-acc3-11ea-8201-3ee43693aca8.png">

Thoughts? :)

**Comment by NewJenk** [comment]
This looks great @richtabor .

P.S. Looking back I think the placeholders (and a few other bits of the Gutenberg UI) have regressed as they were better with a grey background and center aligned.

**Comment by MichaelArestad** [comment]
Perhaps there's a compromise that could be made here that's closer to the current design using higher contrast colors and almost identical patterns.

Forgive my in-browser mock:

![image](https://user-images.githubusercontent.com/1123119/86493668-9a6a6d00-bd2f-11ea-8adc-b6ac2be3566e.png)

**Comment by richtabor** [comment]
I agree the compromise is a big step in the right direction. How about a background color as well? 🙏

**Comment by mtias** [comment]
Closing as done, we can continue to refine these, particularly the hover affordances — it'd be nice if the moment we detect a dragging file event all the placeholders on the page switched to read "you can drag here".
