### ISSUE TITLE
Gutenberg 8.3.0 whitescreen and displaying several js errors

### ISSUE THREAD

**Issue by NewJenk** [WordPress/gutenberg#23123]
Gutenberg 8.3.0 displays a whitescreen along with a bunch of js errors when trying to view edit screen. No probs when using an older version of Gutenberg.

**To reproduce**
1. Set up a local WP install using MAMP
2. Install Gutenberg 8.3.0 plugin
3. Try and access edit screen of a post/page

**Expected behavior**
Not a whitescreen or js errors.

**Screenshots**
![gutenberg-8 3 0-js-errors](https://user-images.githubusercontent.com/17580973/84540648-c628a300-aced-11ea-9af1-71ac5e29c590.png)

**Editor version:**
- WordPress version: 5.4.2,
- gutenberg plugin
- 8.3.0

**Desktop:**
 - OS: Win10
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by richtabor** [comment]
Hey @NewJenk, do you have any other plugins activated?

**Comment by NewJenk** [comment]
> Hey @NewJenk, do you have any other plugins activated?

Hi @richtabor, there are only 3 plugins active (Gutenberg, Yoast and CF7). Just deactivated CF7 and Yoast and the culprit is Yoast (ver. 14.3).

**Comment by NewJenk** [comment]
Closing as issue seems related to Yoast rather than Gutenberg.
