### ISSUE TITLE
Launch Performance: Calypso vs Gutenberg

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#23131]
**Describe the bug**
It takes up to 10 seconds from the time you click 'edit' on the article until you're ready to edit in Gutenberg. With Calypso, this launch time is much faster and typically under 2 seconds. Most of the launch time waiting with Gutenberg is spent looking at a screen pulsating followed by a white screen, then the editor arrives (see screenshot).

**To reproduce**
1. Launch Calypso and time it
2. Launch Gutenberg with the same article and time it

Note, I do not know if the length of an article matters. If it does, you'll need to choose an article that's of average length. Length may increase editor launch time.

**Expected behavior**
This editor's launch performance time needs to be improved with the timing reduced to the same or better than Calypso. If Calypso can be ready to edit an article in under 2 seconds, Gutenberg needs to reach or exceed that same goal.

**Screenshots**
![Screen Shot 2020-06-13 at 7 36 48 AM](https://user-images.githubusercontent.com/16678592/84571556-c904b180-ad48-11ea-8aaf-64c16c9cb7ff.png)

**Editor version (please complete the following information):**
- WordPress version: See Wordpress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? See Wordpress.com
- If the Gutenberg plugin is installed, which version is it? See Wordpress.com

**Desktop (please complete the following information):**
 - OS: MacOS X Mojave
 - Browser: Firefox
 - Version: 77.0.1

**Additional context**
N/A

**Comment by talldan** [comment]
@commorancy I timed about 2-3 seconds on a fresh WordPress install in my local development environment. This is using the open source version of WordPress, though.

I get the feeling this issue related to the implementation of the editor in WordPress.com though, comparing to the calypso editor, in which case I'd recommend creating an issue over at:
https://github.com/Automattic/wp-calypso

I'll close this issue as there's not much that can be done to influence that from here.

If I'm wrong though, let me know!
