### ISSUE TITLE
How to access UrlInput component?

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#2313]
I'm looking at the core button block source and for accepting the URL it uses **UrlInput** and **IconButton** components

	{ focus &&
		<form
			className="blocks-format-toolbar__link-modal"
			onSubmit={ ( event ) => event.preventDefault() }>
			<UrlInput
				value={ url }
				onChange={ ( value ) => setAttributes( { url: value } ) }
			/>
			<IconButton icon="editor-break" label={ __( 'Apply' ) } type="submit" />
		</form>
	}

The **IconButton** I can access from **(window.)wp.components.IconButton**, but where is the **UrlInput**? Doesn't seem to be under **wp.blocks**, **wp.components**, **wp.editor**, **wp.element**, **wp.utils**...

Is it supposed to be internal only?

Thanks.

**Comment by aduth** [comment]
I don't believe this is intended to be internal-only, just missing as an export from [`blocks/index.js`](https://github.com/WordPress/gutenberg/blob/master/blocks/index.js).

Flagging as Task, Good First Task.

**Comment by youknowriad** [comment]
I still think we should be cautious about making components available for plugins because this means no BC anymore. I think most of these components should be in an npm module.

**Comment by mtias** [comment]
It is fine during the plugin stage to make them available. I'd rather give plugin authors a clear way of how they could build things, otherwise they need to develop from scratch.
