### ISSUE TITLE
Block Directory: Using the Inline inserter breaks searching in the left-sidebar inserter.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#23148]
**Describe the bug**
Opening the inline inserter clears block directory searches in the pinned left sidebar inserter and doesn't allow a search until its closed and reopened.

See Screenshot below. ⬇️

**To reproduce**
1. Open the left sidebar inserter
2. Search for 'p5'.
3. Expect the result to returned as expected
4. Open the inline inserter via the document
5. Notice the left sidebar inserter clears.

**Expected behavior**
The inserters appears to have their own contexts. The block directory flow should maybe follow the same path.

**Screenshots**
![Screenshot](https://d.pr/i/kuKFtU.gif)

**Editor version (please complete the following information):**
Testing using: master@https://github.com/WordPress/gutenberg/commit/f15b91ca9cbdf171448ebc1f23f55cc5b2748262

**Desktop (please complete the following information):**
 - OS: macOs(Catalina)
 - Browser: Chrome

**Comment by ryelle** [comment]
Is this still an issue with the latest inline inserter? The sidebar inserter closes when I click the inline + to open the small inserter.

**Comment by StevenDufresne** [comment]
No, this is no longer an issue.
