### ISSUE TITLE
DropZone component no longer provides x and y position

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#23149]
**Describe the bug**
(Originally reported in the Making WordPress slack: https://wordpress.slack.com/archives/C02QB2JS7/p1591999141128800)

The `DropZone` component no longer provides `x` and `y` position to its callback.

It looks like when `DropZone` was rewritten to use a hook an optional `withPosition` prop that defaults to a falsey was added, possibly as an optimization:
https://github.com/WordPress/gutenberg/blob/f15b91ca9cbdf171448ebc1f23f55cc5b2748262/packages/components/src/drop-zone/index.js#L24

The `DropZone` component doesn't have a way to set this value, so since this change `x` and `y` are not provided:
https://github.com/WordPress/gutenberg/blob/f15b91ca9cbdf171448ebc1f23f55cc5b2748262/packages/components/src/drop-zone/index.js#L67-L73

**To reproduce**
Reproduction is a little tricky, as it requires implementation of a drop zone.

**Expected behavior**
`DropZone` continues to provide `x` and `y` position data by default.

**Comment by ellatrix** [comment]
Do you mean this? https://github.com/WordPress/gutenberg/pull/19514#discussion_r365200634

Either way, I think this was part of the 5.4 release? https://github.com/WordPress/gutenberg/issues/20185#issuecomment-592485163

**Comment by talldan** [comment]
@ellatrix I think it was that PR. As you say, looks like it was already shipped in 5.4, so perhaps this isn't a 5.5 must have.

**Comment by talldan** [comment]
This looks like the line:
https://github.com/WordPress/gutenberg/pull/19514/files#diff-af960f1a0848b34c0c03399a679e8c4dR143

I think it should be a pretty easy issue to solve, we'd need to expose the `withPosition` prop for the `DropZone` component. Possibly default it to `true` for backwards compatibility.

I can put together a PR.

**Comment by talldan** [comment]
Oh wait (sorry for multiple messages), I see what you mean now, that this is a separate `position` object that only provided the edge being dropped to and was only used in the `drop` events.

So, looks like it needed a dev note and to be removed from the docs?

**Comment by talldan** [comment]
#23577 updates the DropZone readme.
