### ISSUE TITLE
Command-X (cut) cuts the entire block, not the selected text.

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#23141]
**Describe the bug**
When editing an HTML block and you attempt to drag highlight a section of text, then choose cut, the editor cuts the entire block and all of its content, it does not cut the selected text.

**To reproduce**
1. Create a block and convert it to HTML
2. Select a portion of text in the HTML block
3. Attempt to cut the text and notice the entire block disappear

**Expected behavior**
This is not expected. If the block is selected without any text and 'cut' is chosen, it should cut the entire block. If only a portion of text is selected within a block, it should cut ONLY the selected highlighted section of text for pasting later.

**Screenshots**
![gutenberg-cut-bug](https://user-images.githubusercontent.com/16678592/84597382-83171e80-ae18-11ea-9c76-95f125304522.gif)

**Editor version (please complete the following information):**
- WordPress version: Wordpress.com
- Does the website have the Gutenberg plugin installed, or is it using the block editor that comes by default? Wordpress.com
- If the Gutenberg plugin is installed, which version is it? Wordpress.com

**Desktop (please complete the following information):**
 - OS: MacOS X Mojave
 - Browser: Firefox
 - Version: 77.0.1

**Additional context**
N/A

**Comment by talldan** [comment]
I wasn't able to reproduce this against the latest code in the repo. Also using Firefox on Mac OS X as my primary browser.

It may be an issue that has already been solved, or could be something that only exists on WordPress.com. More testing welcome!

**Comment by talldan** [comment]
Tracked it down, this was a bug that was fixed recently here by #22793.
