### ISSUE TITLE
Autosave loses edits that happened during the save

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#2315]
## Issue Overview

Text blocks created quickly by typing, pressing enter, and typing again, can disappear.

## Steps to Reproduce (for bugs)

Reproduces in Chrome and FF:

1. New post
2. Quickly alternate between pressing 'x' and enter

## Expected Behavior

Should get a list of blocks, each with 'x' in them

## Current Behavior

Blocks go missing.

![missing](https://user-images.githubusercontent.com/3314354/29125647-3c532ad0-7d14-11e7-85b8-b926ccf62ab9.gif)

## Possible Solution

Possibly autosave related?

## Related Issues and/or PRs

Possible duplicate of #2314

**Comment by notnownikki** [comment]
Easier way of reproducing this:

1. Create a new post
2. Type something in the first text block
3. Press enter to create a second text block, then hold down a key so that the block is constantly being edited.
4. Wait for autosave to kick in.
5. Watch the block you were editing, disappear.

When autosave runs, it triggers a `REQUEST_POST_UPDATE` effect. 

In editor, effects, starting on line 56:

```
		new Model( toSend ).save().done( ( newPost ) => {
			dispatch( {
				type: 'RESET_POST',
				post: newPost,
			} );
```

This updates the post, and resets the post based on the post saved. But if someone is typing or creates a new block while the save was going on, their edits are lost, and if they've created a new block while the save was happening, their new block is lost and they lose editor focus.

I'm not sure what solution would be acceptable here. I don't think we should be resetting the post at all in this effect, but I'm not sure why we do. But, it is the culprit for losing edits, and Calypso had this same problem about 5 months ago (I was on my support rotation, and dealt with the poor guy who kept getting hit by it due to his slow internet connection!)

Paging @aduth and @youknowriad for more input here.

**Comment by youknowriad** [comment]
duplicate #2300 ?

**Comment by aduth** [comment]
Yes, appears to be a duplicate, but good reference text here too.
