### ISSUE TITLE
New G2 icon: barcode scannner

### ISSUE THREAD

**Issue by Garance91540** [WordPress/gutenberg#23167]
In the Woo app, we are adding a new feature that will enable users to scan barcodes directly with their device's camera. I created a new "barcode" icon following the G2 guidelines for this feature (I added it in our Figma file under "draft"):

<img width="491" alt="Screen Shot 2020-06-15 at 5 24 12 PM" src="https://user-images.githubusercontent.com/28450084/84675829-1477b500-af2d-11ea-8dc9-39e1578966bc.png">

[icon-barcode.svg.zip](https://github.com/WordPress/gutenberg/files/4781274/icon-barcode.svg.zip)

In context, here's where we'll see this icon in the app:

1. In the "SKU" row of the product page > inventory section

<img width="328" alt="Screen Shot 2020-06-15 at 5 32 57 PM" src="https://user-images.githubusercontent.com/28450084/84676909-49d0d280-af2e-11ea-9b56-c99cc349153f.png">

Selecting it will open the camera and scanning a barcode will automatically update the SKU with the scanned barcode numbers

2. On the top right corner of the product list:

<img width="352" alt="Screen Shot 2020-06-15 at 5 46 14 PM" src="https://user-images.githubusercontent.com/28450084/84678329-2a3aa980-af30-11ea-9816-b84c087066ce.png">

Selecting this icon will open the camera and users will be able to scan products to automatically update their inventory levels

Curious to hear your feedback on this! cc @pablohoneyhoney @jameskoster @jasmussen

**Comment by pablohoneyhoney** [comment]
Have you tried with squared forms? At least the camera. It feels too rounded and perhaps the squared corners can clarify a bit more what it is.

**Comment by Garance91540** [comment]
> Have you tried with squared forms? At least the camera. It feels too rounded and perhaps the squared corners can clarify a bit more what it is.

Do you mean with no corner radius? Here's a try:
<img width="456" alt="Screen Shot 2020-06-15 at 5 48 41 PM" src="https://user-images.githubusercontent.com/28450084/84678616-87365f80-af30-11ea-8879-06121e77e6d8.png">

**Comment by pablohoneyhoney** [comment]
I meant less rounded all together. And with more space that lightens up the tension between the lines. 

<img width="48" alt="barcode" src="https://user-images.githubusercontent.com/25516611/84679123-e11e3180-aefe-11ea-9a48-d9595b44ddf4.png">

**Comment by Garance91540** [comment]
>I meant less rounded all together. And with more space that lightens up the tension between the lines.

Your version looks good to me @pablohoneyhoney !
