### ISSUE TITLE
userData reducer test needs updating.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#2317]
## Issue Overview

One of the userData reducer tests in editor/test/state is not clearing out the global blockTypes correctly.
It "should populate recently used blocks with the common category", which it does, just not the expected result in the test suite. You can see the failing tests in the #2299, and #2309. Not sure if the test is expecting the wrong thing, or if the data is not being cleared. This issue has deeper roots as it is tied to the global blockTypes state.

## Expected Behavior

According to the tests only two blockTypes should appear in the array, instead 8 do. It is unclear what the expected outcome of the test should be, but based on the test suite it looks as though the tests are not cleaning up themselves properly.

## Current Behavior

It seems to be passing in other branches that are not adding new blocks.

## Possible Solution

A possible solution might be clearing out all registered types on the after hook. A better long term solution is to introduce blockType registries and have independent fixtures be used for tests that need a certain set of blocks. This would make our test suite run slightly faster as well. This will also make the ability to have selective sets of blocks for different contexts a lot easier to manage.

## Related Issues and/or PRs

#2309, #2299

**Comment by notnownikki** [comment]
I have an intermediate fix for this, which just makes sure that all the populated blocks are from the common category, but I'm not sure if it was merged, it's in one of @iseulde PRs which added a new block, but I can't locate it right now... Did it get merged?

**Comment by notnownikki** [comment]
Found it: https://github.com/WordPress/gutenberg/pull/2091

**Comment by notnownikki** [comment]
The test fix is https://github.com/WordPress/gutenberg/commit/eef52783b3e1f1ff9b0eb93f2da03c515f70e2eb I'll open a new PR with just that fix.

**Comment by notnownikki** [comment]
https://github.com/WordPress/gutenberg/pull/2365

**Comment by BE-Webdesign** [comment]
Fixed by #2365
