### ISSUE TITLE
Env: Improve install performance

### ISSUE THREAD

**Issue by noahtallen** [WordPress/gutenberg#23175]
**Is your feature request related to a problem? Please describe.**
Look at the install WordPress step of `wp-env start`:

https://github.com/WordPress/gutenberg/blob/db1c89b7f53aecf096f3bd013a85bfe8f2aa44d4/packages/env/lib/wordpress.js#L69-L149

There are two issues here:
1. We use `rm` on the docker run command, which means we start and stop the service for each command.
2. We run each WP command in a separate service run. For example, if you set 10 wp-config values, you'll start and stop the container 10 times.

As you can imagine, this has a big performance overhead.

**Describe the solution you'd like**

I tested some changes to this which decreased `wp-env start` from >30s to <10s. Essentially, we can join most of these commands together into one run command. This is how it would look in plain bash as an example; we'd just generate it in JS:

```
# Before:
docker-compose run cli wp config set THING1 foo1
docker-compose run cli wp config set THING2 foo2
docker-compose run cli wp config set THING3 foo3

# After
docker-compose run cli bash -c "wp config set THING1 foo1 && wp config set THING2 foo2 && wp config set THING3 foo3"
```

On top of that, we can remove the `rm` option for many of these commands, since there is no need to stop the service until we are done running everything.

The only challenge I noticed while testing this is that we may need to run the install portion of the script separately from the other commands. Otherwise, it seems to error out. 

**Describe alternatives you've considered**
Echo each wp-config value into the PHP file manually without going through wp-cil. (does not seem like a good idea)

cc @epiqueras

**Comment by epiqueras** [comment]
Nice, let's do it.
