### ISSUE TITLE
Some Block CSS contains too much specificity

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#23170]
If the accepted "rules" for BEM naming conventions are applied, the rules for a nested contained element shouldn't be wrapped by the parent class name. This is generally well-applied in the codebase, but there are rules which aren't conformant.

E.g. https://github.com/WordPress/gutenberg/blob/c19d2d908cba695960cf8407bd0b0afc181aa657/packages/block-library/src/media-text/style.scss#L44

Is: `.wp-block-media-text .wp-block-media-text__content {padding: 0 8% 0 8%;}`
Should be: `.wp-block-media-text__content {padding: 0 8%;}`

**Comment by oxyc** [comment]
I know https://github.com/WordPress/gutenberg/issues/11779 tracks some of these at least.

The specific example you provided I have a local branch for that I'll try and get in once https://github.com/WordPress/gutenberg/pull/23102 https://github.com/WordPress/gutenberg/pull/23062 are merged.

**Comment by markhowellsmead** [comment]
Thanks @oxyc.

**Comment by skorasaurus** [comment]
Thanks for reporting; marking it as closed since the specific issues you raised have been implemented thanks to @oxyc and I agree the CSS can be better scoped in several blocks; there's some issues that address this including but not limited to https://github.com/WordPress/gutenberg/issues/17702
