### ISSUE TITLE
[Navigation Block] Add Navigation Link overriding add new block functionality

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#23181]
**Describe the bug**

When trying to alter the navigation block by adding a new navigation link, the add new block link transforms to "Add Navigation Link" prompt instead of the option to add a new block. 

**To reproduce**
1. Enable FSE, Navigation screen, and FSE templates in Gutenberg > Experiments
2. Create a menu using the navigation block and a few other blocks. 
3. Go to add a new navigation link and scroll down to where you usually would see a + prompt to add a new block. 

**Expected behavior**

I expected to see a prompt to add a new block rather than add a navigation link at the bottom of the page. 

**Screenshots**

Here's a video recording as this is hard to explain otherwise: https://cloudup.com/chBs2YOY3L9

**Editor version (please complete the following information):**
- WordPress version: WordPress 5.4.2 
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg
- If the Gutenberg plugin is installed, which version is it?  8.3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.97

**Comment by annezazu** [comment]
To be safe, I replicated this on an additional test site from scratch with the same setup and was able to do so.

**Comment by talldan** [comment]
So I don't think this was a bug, but a really confusing experience. 'Add Navigation Link' is the block appender, and when clicking it automatically adds a Navigation Link (as that was the only type of allowed block). 

Looking at it again, this doesn't seem to be an issue any longer now that the block supports more than just links:
<img width="710" alt="Screenshot 2020-10-29 at 6 35 59 pm" src="https://user-images.githubusercontent.com/677833/97557585-e98e8900-1a15-11eb-9648-a898e9ee1b63.png">

**Comment by annezazu** [comment]
Thanks, @talldan ! I tested once more and can confirm this is not longer an issue.
