### ISSUE TITLE
Site editor: Remove "Add block" outline and inserter

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#23184]
**Describe the bug**
There's an "Add block" inserter at the bottom of the editor. It looks like this:

![image](https://user-images.githubusercontent.com/1123119/84714410-cf528380-af2a-11ea-83d8-9e0fbcb1f8bb.png)

I'd like to see it removed as there it isn't in the regular editor and we should be striving for a near identical experience.

**Comment by epiqueras** [comment]
Do we still want it when the template is empty? I think some sort of indicator might be warranted, especially when we have a grid showing. I feel like template editing is more about layout and structure than the copy.

**Comment by MichaelArestad** [comment]
> Do we still want it when the template is empty? 

Good question. I do think we need to work out an empty state for a template. We haven't explored much of that just yet.

> I feel like template editing is more about layout and structure than the copy.

I completely agree and will be something we pursue in the near future.

For now, I think something similar to the content editor could work:

![image](https://user-images.githubusercontent.com/1123119/84804062-c8c21b80-afbf-11ea-8e55-53e467962821.png)

What do you think?

**Comment by epiqueras** [comment]
Yeah, that works.
