### ISSUE TITLE
Iterate on the design of the checkbox

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#23185]
Currently, the checkbox looks like this:

![image](https://user-images.githubusercontent.com/1123119/84714584-569ff700-af2b-11ea-9fe7-d42ef5535b9a.png)

The icon is too close to the edges of the box and the weighting is too thin. I'd like to see us develop another icon just for the checkbox that fits a little better in context.

@jasmussen What do you think?

**Comment by jasmussen** [comment]
Yep. 

I think fundamentally the design is okay, in that it uses a single themed spot color that matches the chosen admin theme ([this one bug not withstanding](https://github.com/WordPress/gutenberg/pull/23048#issuecomment-644572536)). This white with a border in the unset state, themed-background with white contents in its set state, helps it match the radio button, and the toggle control.

There's a new checkbox in the G2 design figma file:

<img width="529" alt="Screenshot 2020-06-16 at 09 02 21" src="https://user-images.githubusercontent.com/1204802/84742168-61e93600-afb0-11ea-91de-aafb20337688.png">

But it may be too big, as you say it gets a little close to the edge. You may want to make a smaller version of that same checkmark, same as there's a small close icon.

**Comment by MichaelArestad** [comment]
> But it may be too big, as you say it gets a little close to the edge. You may want to make a smaller version of that same checkmark, same as there's a small close icon.

@jasmussen that's about what I was thinking. I don't want to resize the checkbox and I think the colors/styles work well. Perhaps just a slightly smaller checkmark could do the trick.

**Comment by mapk** [comment]
Here's how the checkbox looks with the new G2 checkmark. I then iterated further to show a smaller checkmark for the checkbox purpose.

![Screen Shot 2020-07-20 at 12 09 14 PM](https://user-images.githubusercontent.com/617986/87976361-d87ec500-ca81-11ea-8e9d-772e77cbe72e.png)

**Comment by jasmussen** [comment]
It's cool this has a design, but what happens next?

**Comment by mapk** [comment]
If the smaller design is agreed upon, I imagine we'd get this listed as a proposal in the Figma library (for checkboxes specifically since the new checkmark is in Figma already). After, we'd also need a PR to change this over in the code for both the regular checkbox (smaller checkmark) and for the new checkmark (regular size) because I'm not sure that's been swapped out either in the UI.
