### ISSUE TITLE
Site editor: Remove Home icon from the Page/Post dropdown

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#23182]
Currently, the page/post dropdown looks like this (when on a home page):

![image](https://user-images.githubusercontent.com/1123119/84713984-906ffe00-af29-11ea-9313-d88b28384b19.png)

I would like to see the home page icon only appear in the menu and not in the toolbar. More like this:

![image](https://user-images.githubusercontent.com/1123119/84714039-b85f6180-af29-11ea-84d4-7e8d74dd889e.png)

The home icon should still remain next to the home page in the menu/popover itself seen here:
![image](https://user-images.githubusercontent.com/1123119/84714112-f65c8580-af29-11ea-9ef4-ab79ebcc15a1.png)

**Comment by epiqueras** [comment]
Should we maybe just move this to the sidebar as has been explored recently?

**Comment by MichaelArestad** [comment]
> Should we maybe just move this to the sidebar as has been explored recently?

Perhaps! Do you have a link to the exploration/proposal?

**Comment by epiqueras** [comment]
I thought you were working on it. Maybe it was @shaunandrews.
