### ISSUE TITLE
Multi-select unconnected blocks

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2320]
This could be an obscure feature, but I think I'd make frequent use of it.

Use case:

I just typed some rough draft and I'm ready to start formatting. I want to convert quite a few pieces of text to a heading level 2. Right now I have to select each block in turn, and convert it. It would be really cool if I could just ctrl/cmd+click all the blocks I want to convert, and get an option to set them as headings. This wouldn't be unlike sublime multi select for Gutenberg. :)

We'd still need to iterate a bit on mobile selection, but I'd see it work a bit like the iOS photos app.

This is low priority stuff, but wanted to file an issue before I forget about it.

**Comment by mcsf** [comment]
→ #3584 for the non-contiguous selection aspect
→ #3535 is somewhat related, as both entail multi-block actions

**Comment by karmatosed** [comment]
For now closing as this isn't something going to get done in version one. Perhaps it could be later versions but let's focus on other aspects now and close - we can always reopen anything.
