### ISSUE TITLE
Enabling global styles to handle custom font declarations

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#23204]
To use a custom font, a theme today must do the following:
1. Enqueue it
2. Make a `@font-face` declaration in the theme’s stylesheet

As the current global styles mechanism is [described](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-json.md#specification), I think the steps would be:
1. Enqueue it
2. Make a `@font-face` declaration in the theme’s stylesheet
3. Add the font to `theme.json` in presets and styles, something like:
```{ global: { presets: { fonts: [ "my font", "other font", ... ] } } }```
 
Is it possible that `theme.json` processes font declarations, making at least step 2 unnecessary? I think this moves slightly beyond generating a CSS custom property.

cc @carolinan

**Comment by nosolosw** [comment]
I've linked this issue from the [tracking one](https://github.com/WordPress/gutenberg/issues/20331). Font family is one of style attributes we'd like to add but haven't gotten there yet. Ideally, I'd like to see if the block style system can manage this for the theme.

**Comment by jffng** [comment]
Closing this issue as theme.json should not enqueue any fonts, and the font family mechanism has been added.
