### ISSUE TITLE
Hyperlinks on Buttons not possible to toggle/deactivate

### ISSUE THREAD

**Issue by dbea3059** [WordPress/gutenberg#23205]
hi there. with the new gutenburg button blocks there is a hyperlink button to insert a link into a button. But when clicking the hyperlink button to deselect it the hyperlink is not cancelled but the user is prompted to enter a new link? i assume this was not the way it was intended to work?

To understand it easier you can say its like converting normal text on a site to a hyperlink by clicking the hyperlink button. Usually you can toggle between text and hyperlink. This feature does not appear to functioning with the gutenburg buttons.

But i have to say gutenburg is very fast overall and a joy to work with generally.

**Comment by ntsekouras** [comment]
Hi @dbea3059. Thanks for reporting this! I could verify this.
