### ISSUE TITLE
Adding background image to Cover block provides no feedback during upload

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#23206]
**Describe the bug**
When adding a background image to the Cover block there is no feedback provided to the user that an image is being uploaded.

**To reproduce**
1. Throttle network to Slow 3G (use devtools).
2. Add new Post
3. Add Cover block - see placeholder
4. Click "Upload" and upload an image.
5. See block UI in editor provides absolutely no feedback that an image upload is in progress.
6. Eventually, see background image set on Cover block.

**Expected behavior**
Once an image is selected, the Cover block UI should provide some feedback that an image upload is in progress. I would recommend some input from Design on what form this should take.

Please consider that the user may already have content within the Cover block so we can't simply switch the whole block to  a "loading" state as that would prevent the user editing their existing content whilst the upload takes place.

The upload process should be async and not blocking.

**Screenshots**

![Screen Capture on 2020-06-16 at 15-33-52](https://user-images.githubusercontent.com/444434/84788503-1a31d100-afe7-11ea-947e-055fb010e8be.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? 8.3.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by mapk** [comment]
It seems like this should just follow suit with the Image block. It should show the image with an overlay and a loading spinner.

![uploading](https://user-images.githubusercontent.com/617986/87976978-d406dc00-ca82-11ea-99c1-3e75112074bb.png)

**Comment by talldan** [comment]
This was also reported in trac:
https://core.trac.wordpress.org/ticket/45503

I've closed the ticket there in favor of this issue.

**Comment by cpapazoglou** [comment]
Initial attempt to tackle this in https://github.com/WordPress/gutenberg/pull/25401. 

**Known Issue:**
Cause we don't know whether the user uploads an image or a video, we fallback to an image type. Thus, when uploading a video they see a blank spinner rather than the video with the spinner.

Is there a chance we can distinguish whether it is image or video prior the upload?
