### ISSUE TITLE
SCSS: Undefined variable $theme-color (template-part/editor.scss)

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#23217]
In the latest `master` branch, I'm experiencing issues running `npm run dev`.
I get this error:

```
Build Progress: [                              ] 0%Error: Undefined variable: "$theme-color".
    at options.error (/Users/Q/Sites/@wordpress/gutenberg/node_modules/node-sass/lib/index.js:291:26) {
  type: 'Error',
  '$error': '$error',
  status: 1,
  file: '/Users/Q/Sites/@wordpress/gutenberg/packages/block-library/src/template-part/editor.scss',
  line: 67,
  column: 32,
  formatted: 'Error: Undefined variable: "$theme-color".\n' +
    '        on line 67 of packages/block-library/src/template-part/editor.scss\n' +
    '        from line 46 of packages/block-library/src/editor.scss\n' +
    '>> \t\t\tborder: $border-width solid $theme-color;\n' +
    '\n' +
    '   -------------------------------^\n'
}
Build Progress: [==============================] 100%
```

Taking a look at the file, it looks like it's using a `$theme-color` variable. I'm not too sure where that variable is defined though 🤔 . 

Would we be able to replace that with another value?

**To reproduce**
1. Pull latest `master` branch
2. Run `npm run dev`
3. See error in console

**Comment by Addison-Stavlo** [comment]
#23221 should fix this.

**Comment by Addison-Stavlo** [comment]
The fix is merged and master is building again.  This should be good to go!  Sorry about that 😅  .  Feel free to re-open if the issue persists.

**Comment by ItsJonQ** [comment]
@Addison-Stavlo No worries at all! 🤗 ❤️
