### ISSUE TITLE
Block Toolbar Disappears After Changing Alignment Settings

### ISSUE THREAD

**Issue by zdenys** [WordPress/gutenberg#23214]
**Describe the bug**
Changing the alignment options for a Block hides the toolbar until I click outside of the block and then select it again.

**To reproduce**
1. Add a Block that supports alignment options (such as Image, Cover, Group, Columns, Media & Text, Buttons etc.)
2. Click on `Change alignment` icon in the block's toolbar
3. Set it to a different value (Wide width, Full width etc.)
4. See the Block toolbar disappear
5. Click the block again (though it's still selected) and the toolbar doesn't appear until you click outside of the block and then click (select) the block one more time.

**Expected behavior**
See the Block toolbar re-appear again without the need to click away first or the Block not to lose focus at all (and hence the toolbar to stay visible all the time).

**Screenshots**

![Screen Capture on 2020-06-16 at 19-17-08](https://user-images.githubusercontent.com/39308239/84808104-7e18c180-b008-11ea-841b-e0a7bcdb1fdb.gif)

**Editor version:**
- Gutenberg plugin v8.3.0 at https://jurassic.ninja/

**Comment by jeyip** [comment]
I can reproduce this issue as well on atomic _and_ simple sites with Gutenberg v8.3.0.

**Comment by talldan** [comment]
I can reproduce the issue in 8.3.0, but not when checking out the code that's in the `master` branch, so it seems like it may have already been fixed.

I haven't been able to track down the pull request that fixed it though.

**Comment by oxyc** [comment]
This seems to have fixed it https://github.com/WordPress/gutenberg/commit/44f405435caf10962bc3ac25ea26aaa979758791. If I revert it I can reproduce.

**Comment by zdenys** [comment]
So it should be available in Gutenberg 8.4 as per https://github.com/WordPress/gutenberg/pull/23089, right?

**Comment by oxyc** [comment]
Yes

**Comment by oxyc** [comment]
I'll close this issue as should be fixed but feel free to reopen next week after the Gutenberg plugin release if it doesn’t work as expected.

**Comment by lsl** [comment]
Confirming this is now fixed - retested.
