### ISSUE TITLE
I can't use HR blocks, and doesn't have 'is-style-default` class

### ISSUE THREAD

**Issue by mukiwu** [WordPress/gutenberg#23224]
Here is my draft screenshot, I use hr blocks to show **default**, **wide**, and **dots**
it looks good, have styles and colors
![截圖 2020-06-17 10 55 10](https://user-images.githubusercontent.com/3794103/84850006-325a2c80-b089-11ea-8096-1015da64a859.png)

**But**, when I public the articles and see in the website, here is my screenshot:
![截圖 2020-06-17 10 57 08](https://user-images.githubusercontent.com/3794103/84850092-74836e00-b089-11ea-9d9d-277dc4ea2f26.png)

some problems are bother to me
* missing default color
* missing default length ( it's should not as wide)
* missing wide color
* missing top & bototm margin between hr blocks

only dot style is good.

and I find **wp-includes/css/dist/block-library/style.min.css?ver=5.3.3** doesn't has **is-style-default** class, was that correct?

thanks.

**Comment by youknowriad** [comment]
> and I find wp-includes/css/dist/block-library/style.min.css?ver=5.3.3 doesn't has is-style-default class, was that correct?

This is correct; I think it's possible that your theme is overriding the block styles. Do you have a public link to your page so we can check?

**Comment by talldan** [comment]
Closing the issue as there hasn't been a response.
