### ISSUE TITLE
Blocks: Moving focus outside editor should clear selected block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2322]
Related: #1079
Related: #1266

## Issue Overview

When editor region does not occupy full height of the page, clicking below or outside of the editor does not clear the currently selected block.

## Steps to Reproduce

1. Navigate to Gutenberg > New Post
2. Click the "Write your story" prompt
3. Click in the whitespace below the editor

## Expected Behavior

Block is deselected.

## Current Behavior

Block remains selected.

## Possible Solution

See #1266 for previous effort. Ideally we should not hardcode references to the root Gutenberg editor node in testing to deselect. See also #2301 for introducing root element into context, though in that case it's specific to Popovers.

Otherwise, we may consider styling the editor canvas so it occupies the full height of the page, so event handlers introduced in #1079 take effect.

Question also remains is: Should the block clear when clicking the admin sidebar? It should not in the editor header or sidebars, as these contain actions specific to managing the currently selected block.

**Comment by iseulde** [comment]
I think this issue conflicts with #2303.

**Comment by aduth** [comment]
Hmm, not sure how it conflicts?

**Comment by aduth** [comment]
Looks like this issue has resurfaced. Via `git bisect`, appears to be a regression introduced by 082f6cd81560f37452f0b5c22a6e87a22d0f95aa (#3147). cc @youknowriad

**Comment by youknowriad** [comment]
could this #3743 be the best way to solve this once and for all?

**Comment by aduth** [comment]
#3743 would be a fix, yes, if I can achieve a working implementation 😆
