### ISSUE TITLE
Site Title: A few styling option ideas

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#23228]
As we get closer to Full Site Editing, I wanted to suggest a few ideas for site title styling options:
* uppercase - is a very popular visual style for site title and navigation. Already brought up in a general context in #20801

Example design:
![image](https://user-images.githubusercontent.com/4550351/84859467-98a67580-b0b0-11ea-9150-646f084b9a77.png)

![image](https://user-images.githubusercontent.com/4550351/84859518-ae1b9f80-b0b0-11ea-9bef-ae82256b24ca.png)

* letter-spacing - already brought up in in general context in #20796
Example design:

![image](https://user-images.githubusercontent.com/4550351/84859540-b8d63480-b0b0-11ea-81ed-0270581e70c1.png)

![image](https://user-images.githubusercontent.com/4550351/84859593-d1464f00-b0b0-11ea-83ba-e9819d35e8cf.png)

* margin/padding - headers and footers are often the areas where tight control over spacing (especially vertical) is required, for example to create a compact header like this:

![image](https://user-images.githubusercontent.com/4550351/84859711-094d9200-b0b1-11ea-849c-1b0525920938.png)

* font-size / line-height

(hat tip to @iamtakashi for these header designs)

**Comment by Addison-Stavlo** [comment]
Nice suggestions and visuals!

I think the letter spacing is great style idea for this block.  We can save the site title in all caps to achieve that effect, but maybe there are cases where we would want standard casing in all other circumstances?

#23007 Is currently adding font and background colors, font-size, and line height.  The line height in this case seems to achieve the effect of vertical margin/padding.

Another odd style thing I have noticed, is that in being a `<h1>` element it can pick up styles supplied by themes for headings.  For example twentynineteen-blocks it gets this odd tick mark that are applied to headings:

![Screen Shot 2020-06-18 at 4 50 45 PM](https://user-images.githubusercontent.com/28742426/85071183-189e0f80-b185-11ea-90bd-1fc5c8e14c9e.png)

**Comment by alaczek** [comment]
> The line height in this case seems to achieve the effect of vertical margin/padding.

It might! But from my experience designing themes, I suspect margins and padding will play a part too. 

One more idea - adding support for bold and italics text styling options.

**Comment by ianstewart** [comment]
> One more idea - adding support for bold and italics text styling options.

+1. The full gamut of rich text would be valuable — plus, it'd be nice to have the option to have the title be a link as well.

**Comment by Addison-Stavlo** [comment]
> +1. The full gamut of rich text would be valuable — plus, it'd be nice to have the option to have the title be a link as well.

Definitely!  I think RichText itself is out of the question (https://github.com/WordPress/gutenberg/issues/21087#issuecomment-638150490 / https://github.com/WordPress/gutenberg/issues/21087#issuecomment-606042510) due to technical reasons for how the site title entity is saved and consumed - but it is possible to set up the same settings at a block wide level.

The difference being, with RichText we could select a section of the title to Bold, italic, make a link, etc (ex "My **Awesome** [Site](https://github.com/WordPress/gutenberg/issues/23228)".  But its possible set up block wide attributes to apply these settings across the entire title -  (ex "**[My Awesome Site](https://github.com/WordPress/gutenberg/issues/23228)**" )

**Comment by iamtakashi** [comment]
> But its possible set up block wide attributes to apply these settings across the entire title - (ex "My Awesome Site" )

Yes, that would be the majority of the use case. I think a simple checkbox that defaults to be a link to the homepage would be a good start. (potentially allowing a custom URL if we hear many requests)

--

I've been waiting for a letter-spacing control for some time #20796. Is it possible to start with the Site Title block, and eventually the setting to be ported to other blocks?

**Comment by apeatling** [comment]
Font size and line height should be in place now.

**Comment by apeatling** [comment]
Related on letter spacing: https://github.com/WordPress/gutenberg/issues/20796

**Comment by apeatling** [comment]
I do think that letter spacing and uppercase transforms could be generalized and apply to any block as part of font settings.

**Comment by alaczek** [comment]
>  Letter spacing and uppercase should be achievable using CSS classes and styles

Would this be theme dependent, or are there universal classes in Gutenberg we could start applying now?

**Comment by shaunandrews** [comment]
I believe most of the requests here are (and will be) solved as the Global Styles project progress: https://github.com/WordPress/gutenberg/issues/25139

The foundation is there, and @noahshrader is working on extending the design to support line-height, letter-spacing, font-family, font-size, and maybe even letter case. I spent a little time exploring one-off solutions to support line-height for the Site Title block, but Noah has already eclipsed my thinking — he's way ahead of me — and I wouldn't want to spend too much time creating solutions that might not make sense in the larger context of Global Styles.

Maybe there's a way we can all work towards improving the early stage Global Styles project? Would it make sense to start by creating a line-height control specific to Site Title, and then pushing to expand it elsewhere?

**Comment by iamtakashi** [comment]
I'm not fully up to date on the progress on Global Styles project, but would it allow, for example, a custom letter-spacing specifically for the site title block?

We see often site title and section headings are styled differently from the headings in the content of a post/ page.

**Comment by shaunandrews** [comment]
> I'm not fully up to date on the progress on Global Styles project, but would it allow, for example, a custom letter-spacing specifically for the site title block?

Yup, you'll have block-level controls. Here's how it works right now:

![global-styles-current](https://user-images.githubusercontent.com/191598/93381845-413eaf80-f82f-11ea-9608-48c1d2245c7f.gif)

**Comment by iamtakashi** [comment]
Thanks for the info! But, I still feel that it would be valuable to have the setting in the block from the pattern creation point of view. Like the examples at the top of this issue, I can imagine various header patterns having unique settings around letter-spacing or letter-casing to express different visual expressions.

I'm likely missing something obvious, but in my understanding, patterns should be able to override the style provided by Global Styles or theme in each pattern if necessary, right?

**Comment by ianstewart** [comment]
It would be useful to extend Letter case controls introduced in https://github.com/WordPress/gutenberg/pull/26060 to the Site Title Block as well.

**Comment by ianstewart** [comment]
https://github.com/WordPress/gutenberg/issues/28106

**Comment by priethor** [comment]
As a status update of this issue as of Gutenberg 10.4, half of the ideas proposed above are already implemented:
- [x] Letter-case
- [x] Letter-spacing
- [x] Margin and padding
- [x] Font size and line-height
- [x]  Font style and weight (https://github.com/WordPress/gutenberg/pull/31734)

**Comment by youknowriad** [comment]
I've just checked and all of the options are available now for the site title block including the "font weight and style" (appearance) and the letter spacing.
