### ISSUE TITLE
Can't set custom colors for ColorPalette component

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#2324]
Trying to use a **wp.blocks.ColorPalette** for a custom block like this:
```javascript
<ColorPalette
	value={color}
	colors={['#000000', '#ffffff', '#ff00ff']}
	onChange={colorValue => setAttributes({color: colorValue.hex})}
/>
```
While functional, it won't use my 3 specified colors.

I suspect it's because the component is exported as such
```javascript
export default withEditorSettings(
	( settings ) => ( {
		colors: settings.colors,
	} )
)( ColorPalette );
```
so the colors will get overridden.

Not sure if that's the intended behavior and I should import my own CirclePicker from react-color?
Or do I need to set the colors in "editor settings" somehow?

---

Another thing to note is that the ColorPalette imports the **value** prop and uses it as **color** prop for CirclePicker
```javascript
function ColorPalette( { colors, onChange, value } ) {
	return (
		<CirclePicker
			color={ value }
			colors={ colors }
			onChangeComplete={ ( colorValue ) => onChange( colorValue ) }
			style={ { marginBottom: '20px' } }
		/>
	);
}
```
but the core blocks Button and CoverText set the **color** prop instead of **value**, so the active color won't be visually indicated. 
```javascript
<ColorPalette
	color={ color }
	onChange={ ( colorValue ) => setAttributes( { color: colorValue.hex } ) }
/>
```
The blocks should set **value** prop to **color** or the ColorPalette should just take the **color** instead of **value** when destructuring the props.

**Comment by youknowriad** [comment]
Thanks for opening the issue, so two things here:

1- The colors of the `ColorPalette` component are not meant to be overridden for a specific block right now, it's the same palette for all the blocks and a theme can decide to change it by providing a palette for all the blocks (see http://gutenberg-devdoc.surge.sh/reference/theme-support/#colors)

I think if you want to fix the colors for a specific block, you may want to use `react-color` directly.

2- Good catch for the active color bug/

**Comment by mtias** [comment]
We could consider making the current behaviour a `defaultColors` prop, and let blocks force their own colors if needed.
