### ISSUE TITLE
Child Inserter: Remove allowed block label from child block inserter

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#23241]
There's a few example of blocks that allow other blocks to be inserter within them, like the Buttons block and the Navigation block. These block use an inline inserter button which includes a label that identifies the singular block that can be added. It looks like this:

<img width="176" alt="image" src="https://user-images.githubusercontent.com/191598/84912326-53ba1900-b087-11ea-9e2c-e8f68afcde1f.png">

<img width="129" alt="image" src="https://user-images.githubusercontent.com/191598/84912336-57e63680-b087-11ea-9fa2-5f227d55ee7a.png">

This label _can_ be helpful, but it also cause issues with the layout of the document. Take for example how the label affects the layout of the Navigation block in this GIF:

![inserter-label](https://user-images.githubusercontent.com/191598/84914667-da6ff580-b089-11ea-8172-cff0829cdd52.gif)

I think we should remove this label. Perhaps we could just add a tooltip instead? Here's a quick mockup of that:

<img width="161" alt="image" src="https://user-images.githubusercontent.com/191598/84915071-58cc9780-b08a-11ea-9b1e-a07229e9c109.png">

**Comment by mtias** [comment]
For context: https://github.com/WordPress/gutenberg/issues/20728

I agree this one is not feeling particularly good in practice. I'd be fine moving it to the tooltip only and keeping the + consistent. (It also seems the + has different border radius in some of these contexts?)

**Comment by ntsekouras** [comment]
Hey @mtias  , 

>keeping the + consistent. (It also seems the + has different border radius in some of these contexts?)

Where exactly have you spotted these inconsistencies? I checked many `appender` buttons and all seemed to have  `2px` border radius.

**Comment by jasmussen** [comment]
> Where exactly have you spotted these inconsistencies? I checked many appender buttons and all seemed to have 2px border radius.

I spotted one with Buttons, which I've since then fixed. So that is probably what he referred to.
