### ISSUE TITLE
Audit of block markup between frontend and editor

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#23256]
I thought it would be a good idea to keep track of the blocks with mismatching DOM elements between frontend and editor. Some of these are obviously not fixable (shortcode, html). I err on the side of caution (and need to log off) so just let me know and I can ~strike~ a block that's impossible to match.

Also I havent tested any of the FSE blocks, just let me know if I should mark something. Otherwise I'll get to them at some point I guess.

|   |Block          |     |
|---|---------------|-----|
|   |Archive        | Contains wrapper divs: `<Disabled>`, `<ServerSideRender>`, Block |
|   |Audio          | Contains an extra div from `<Disabled>`, is this fine? |
|   |Reusable Block | Multiple wrapper divs, can probably never match exactly but can it be improved? |
| x |Button         | Except `<div>` instead of `<a>` but that's fine since they share a class I think |
|   |Buttons        | InnerBlock wrapper. Fixed in #23222 but needs technical input |
|   |Calendar       | Contains wrapper divs: `<Disabled>`, `<ServerSideRender>`, Block |
|   |Categories     | Contains wrapper divs and generally wrong classes for elements|
|   |Classic        | Contains wrapper divs|
| x |Code           ||
| x |Column         ||
| x |Columns        ||
| x |Cover          ||
|   |Embed          |Contains one wrapper div (guess it just needs light block) |
|   |File           |Contains one wrapper div and extra inner `div.wp-block-file__content-wrapper`|
|   |Gallery        |Contains one wrapper div and missing `figcaption.blocks-gallery-item__caption`|
| x |Group          ||
| x |Heading        ||
|   |~HTML~         ||
|   |Image          |`<img>` is nested within one extra div|
|   |Latest Comments|Contains wrapper divs: `<Disabled>`, `<ServerSideRender>`, Block|
|   |Latest Posts   |One wrapper div|
|   |Legacy Widget  |_Havent tested_|
| x |List           |
|   |Media Text     |Multiple incorrect divs. Fixed in #23062 |
|   |~Missing~      |Does not apply|
|   |~More~         |Does not apply|
| x |Navigation     ||
| x |Navigation link|Except using `<div>` instead of `<a>` but that's fine I guess? |
|   |Next page      |_Havent tested_|
| x |Paragraph      ||
|   |Post Author    |_Havent tested_|
|   |Post Comments  |_Havent tested_|
|   |Post Comments Count|_Havent tested_|
|   |Post Content   |_Havent tested_|
|   |Post Date      |_Havent tested_|
|   |Post Excerpt   |_Havent tested_|
|   |Post Featured image|_Havent tested_|
|   |Post Tags      |_Havent tested_|
|   |Post Title     |_Havent tested_|
| x |Preformatted   ||
|   |Pullquote      |Contains wrapper div and one extra wrapper around the content, separating it from citation. Also not using `<cite>`|
|   |Query          |_Havent tested_|
|   |Query loop     |_Havent tested_|
|   |Query pagination|_Havent tested_|
|   |Quote          |Contains wrapper div and one extra wrapper around the content, separating it from citation. Also not using `<cite>`. Partially #23034 |
|   |RSS            |Contains wrapper divs: `<Disabled>`, `<ServerSideRender>`, Block|
|   |Search         |_Havent tested_|
|   |Separator      |Contains wrapper div|
|   |~Shortcode~    |Not feasible|
|   |Site title     |_Havent tested_|
|   |Social link    |Matches except it uses `<button>` instead of `<a>`, and as this has no class there's no common selector for it|
| x |Social links   ||
|   |Subhead        |_Havent tested_|
|   |Spacer         |Contains wrapper div and missing classnames on actual `<div>`. Classnames fixed in #23235 but need assistance about wrapper div|
|   |Table          |Contains wrapper div|
|   |Tag Cloud      |Contains wrapper divs: `<ServerSideRender>`, Block|
|   |Template part  |_Havent tested_|
|   |Text columns   |_Havent tested_|
| x |Verse          ||
|   |Video          |Contains an extra div from `<Disabled>`, is this fine?|
|   |Widget area    |_Havent tested_|

**Comment by gziolo** [comment]
@ellatrix should be able to help here as she is leading efforts to make the markup look as close as possible between the front-end snd the editor.
