### ISSUE TITLE
Editor: Move Reusable blocks section up within Block Inserter menu 

### ISSUE THREAD

**Issue by joanrho** [WordPress/gutenberg#23253]
Had mentioned this in my other Issue #23076 (More menu improvement suggestions), but posting again here so it can be addressed separately with some more detail:

I think we should move the Reusable blocks section up in hierarchy within the Block Inserter, since users will be creating these on their own and may more likely reuse them compared to other block types in the Inserter. This section should also still include the "Manage all reusable block" text link at the bottom of it.

Screengrab GIFs of the [top bar block inserter](https://d.pr/i/gZHSur) and [inline block inserter](https://d.pr/i/RiAAAP) for context.

**Before/After:**
<img width="798" alt="Screen Shot 2020-06-17 at 12 18 42 PM" src="https://user-images.githubusercontent.com/204742/84934687-eca36100-b094-11ea-9b76-f95dac035316.png">

**Comment by mtias** [comment]
These are generally used a lot less than other blocks, I don't think they deserve a top level placement. The display of reusable blocks in the inserter is also not finalized — there are some explorations about grouping block collections and reusable blocks together as well as having a special tab for them ("Saved").

**Comment by marceloaof** [comment]
Hi!
The category order is always an arbitrary choice. But somehow there is a difference between core-blocks-categories, and reusable-blocks-category, that turns reusable blocks into secondary. In the sense, that users may live without Reusable Blocks if they want inside the Block Editor. While no one can avoid the relevance of a Common-blocks-category, for example. 

Therefore, it is important to allow users to choose the order of the categories, before setting Reusable-Blocks-category as default on the second place.

--
To illustrate with my daily use: I use Reusable-blocks sporadically, to change custom header and custom footer. Writing posts, Reusable-blocks is okay at bottom, so I achive faster the blocks I want to use. Customizer, Patterns and block-settings deal better with variations of blocks (colors-fonts-margins-paddings).
