### ISSUE TITLE
[Project Management] Implement Tracking for GitHub Activity

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#23257]
**Background:**

Building off of this prior issue from @danielbachhuber https://github.com/WordPress/gutenberg/issues/13492, I wanted to loop back to suggest we explore using the following plugin created by @jeherve to pull insights out from the overall repository: https://github.com/Automattic/ghactivity

The goal would be that by getting more granular insights from GitHub, we can better direct efforts, spot problems, and maintain a healthy repo. 

**Possible use cases:**

- Better keep track of the flow of certain labels.
- Surface to contributors bottlenecks that are keeping the project from keeping on top of the incoming issues/pull requests. 
- Highlight wins for those helping triage or review issues.
- Gather statistics to help us identify what initiatives we take to eliminate bottlenecks are working.

We could then include these insights in the high level “What’s Next” posts and/or the Core Editor meetings to help better organize efforts. 

**Points of Concern**

These concerns are top of mind although I'm sure there are many more: 
- This might favor work of engineers over other types of work (for example designers) depending on what's track
- This might cause people to focus on numbers that we aim to optimize just because they’re public.
- The wrong numbers could be tracked causing us to focus on the wrong part of a problem/not see the problem fully. 

**Potential Data Points to Track**

While there is a list as part of this issue https://github.com/WordPress/gutenberg/issues/13492#issue-402877643 , here's what we can do for sure with the plugin:

- 7 day activity view of number of comments, reviews, issues opened, branches pushed, branches deleted, PR closed, issue closed, PR open, committed, and work done across the number of projects. 
- Average time of PRs with certain labels shown as a graph comparing number of issues to time waiting. 

Ideally, we could include data around Unreviewed PRs as mentioned in the previous issue: Total number of unreviewed PRs, Unreviewed PRs older than 2 business days, Number of unreviewed PRs older than 2 business days broken down by label. 

**Open Questions:**

- What other solutions are there out there that might accomplish the same end goal of getting more helpful data from GitHub? For example, would it be better to go back to this original issue https://github.com/WordPress/gutenberg/issues/13492 and implement a WP-CLI command?
- What data would we _ideally_ want to track? This may require commits back to the original plugin to accomplish.
- Where could this data "live" over time? 
- What concerns are missing that we should keep in mind as we exploring this?

**Comment by StevenDufresne** [comment]
@annezazu 
I love that we are interested in building 'project management' insight right into the repository. I think there are a lot of cool futures in store for us here :)

Maybe we can choose a specific improvement to run the initial experiment on. It will force us to practice implementing procedural updates. As more data comes in, we'll be quicker at actioning the data and avoid the "too much" data trap.

For Example:

**Goal:**
We want to speed up the time it takes to push high priority bug fixes.

**Assumptions: How will we know if we are on track?**
- If the time for pull requests that address high priority bugs is trending downwards
- If we are picking up high priority bugs quicker

**Metrics: How can we validate those assumptions?**
- Time to merge pull request for high priority bugs
- Time for issues to receive priority label
- Time for issues with high priority label to be assigned
- Etc 

Of course this is an exercise that can be applied on top of having all the data as well. I just think we don't need to nail the perfect metrics first go. It's more an exercise of putting the process in place, we can then focus in on gaining the most insight.

**Comment by annezazu** [comment]
I love this idea and approach! I'd be curious to hear what we'd like to focus in on. Right now, the priority labels aren't often in use which makes that hard to track but I think the general idea is apt. Because Full Site Editing is such a big focus, it might be neat to hone in there or, to get even more specific, to  focus in on labels for features listed here for 5.5: https://make.wordpress.org/core/2020/05/29/editor-features-for-wordpress-5-5/
