### ISSUE TITLE
[ Navigation screen ] Improve auto focus to make "go to" consistent for nested blocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23269]
Incoming once #22996 is merged we need to remove the selection using a call in this form:

```JS
await selectEditorBlock( null );
```

This is required because  Block List immediately applies focus when isSelected changes. Given we need to prevent this maybe there is a way to improve how preventing it works and update the effect here:

https://github.com/WordPress/gutenberg/blob/e1a6a78e60de39262cda7d96f0e905bb4f53679e/packages/block-editor/src/components/block-list/block-wrapper.js#L136-L140

It's not clear yet if it is really a problem. It may be that the same problem here is causing this:

![select-nested](https://user-images.githubusercontent.com/107534/85129473-d8e62f00-b23b-11ea-8fe0-fe113a264927.gif)

**Comment by draganescu** [comment]
It may be that the same problem here is causing this:

![select-nested](https://user-images.githubusercontent.com/107534/85129473-d8e62f00-b23b-11ea-8fe0-fe113a264927.gif)

**Comment by talldan** [comment]
@draganescu Was this fixed by https://github.com/WordPress/gutenberg/pull/25322? I'll close it, but feel free to reopen.
