### ISSUE TITLE
[ Navigation screen ] Let's have only one loading indicator

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23267]
Incoming after #23033 will land we'll have two spinners that show up:

- one spinner for loading the list of available menus
- one spinner for loading the menu items in the selected menu

Ideally we'd only want one spinner, as multiple loading indicators tend to crowd the visual information highway :) 

The idea, discussed with @adamziel is to wrap the page in another component which would know if any of it's children still is in a loading state.

Another option is to have one of those nice loading states where we have a skeleton of gray boxes until we can actually build the page. But this pattern should exist elsewhere as well I'd think.

**Comment by adamziel** [comment]
I'll spin a proposal PR once #23033 lands to show what I think would be the cleanest solution here - a picture says a thousand words :-)

**Comment by shaunandrews** [comment]
With the newly updated navigation screen, we now have a single spinner:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/191598/107553916-3e0fdb80-6ba3-11eb-9027-975d5a3a0ad7.png">
