### ISSUE TITLE
Chrome displays Not secure when Block inserter Patterns tab selected

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#23261]
**Describe the bug**
When the Patterns tab of the block inserter is selected the address bar changes from Secure ( with a padlock ) to Not secure. 

**To reproduce**
1. Click on Add New Post.
2. Click on the block inserter icon
3. Click on the Patterns tab
4. After a short while the address bar padlock is replaced by Not secure.
5. I believe it's the Testimonials  pattern's Gravatars that are the issue.
https://github.com/WordPress/gutenberg/pull/20894

**Expected behavior**
Site should remain secure.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/84988227-8ae90280-b139-11ea-84bd-3a91f65f6ff9.png)
![image](https://user-images.githubusercontent.com/2474435/84988262-9ccaa580-b139-11ea-87b1-2ecf4be112b3.png)

![image](https://user-images.githubusercontent.com/2474435/84988821-94269f00-b13a-11ea-9070-bfc556a08528.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 8.3.0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 83.0.4103.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by bobbingwide** [comment]
I confirmed the problem and resolved it by changing `http:` to `https:` in `lib/patterns/testimonials.php`

**Comment by skorasaurus** [comment]
That pattern has been removed from the plugin so closing this.
