### ISSUE TITLE
Load CSS Conditionally

### ISSUE THREAD

**Issue by askel45** [WordPress/gutenberg#23271]
**Is your feature request related to a problem? Please describe.**
The block editor loads all of its CSS in the front end rather than conditionally depending on the blocks being used

**Describe the solution you'd like**
Make the CSS load conditionally depending on the blocks being used and also on the pages and posts they are on, not the whole block CSS font everywhere.

**Describe alternatives you've considered**
None since this is a core feature. I load all my CSS files conditionally depending on where they are being used, and the block editor is adding two additional files per page! Hence, increasing page weight.

**Comment by oxyc** [comment]
This was recently fixed https://github.com/WordPress/gutenberg/pull/22754

**Comment by askel45** [comment]
@oxyc let me install the plugin and see.

**Comment by oxyc** [comment]
No it hasn't been released yet. If you want to test it you can either build the plugin locally from master or just manually change the files the commit does: https://github.com/WordPress/gutenberg/pull/22754/files

**Comment by askel45** [comment]
I tried adding the changes to the plugin but it seems nothing worked. My CSS is flagged as unused in the page insights and it is due to the block editor CSS. When I add disable Gutenberg plugin, the warning disappears. Very funny indeed! Let me see once the update is merged if it will work (I am not a developer, so some things I cannot do myself).

**Comment by gziolo** [comment]
> This was recently fixed https://github.com/WordPress/gutenberg/pull/22754

Yes, it should be addressed with this PR. Let’s close this issue. Feel free to reopen next week after the Gutenberg plugin release if it doesn’t work as expected.

**Comment by askel45** [comment]
@gziolo will do.

**Comment by askel45** [comment]
@gziolo I doubt it worked. Still, the plugin adds 56kb to my CSS and the block editor without the plugin adds about the same amount of CSS.

**Comment by askel45** [comment]
It does not work for core blocks.

**Comment by gziolo** [comment]
Yes, all core blocks have JavaScript and CSS code bundled together. We plan to optimize the whole approach later this year according to the plan shared by @saramarcondes in this comment https://github.com/WordPress/gutenberg/issues/2768#issuecomment-644313150. Once we have support for lazy loading blocks we will split core blocks into individual bundles that load only when necessary.

**Comment by askel45** [comment]
Will be on the lookout. All my (minified) CSS files are below 20kb and the core blocks add 56kb (minified) into my combined CSS file!
