### ISSUE TITLE
Style tag instead of classnames for background- and text color in the editor

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#23274]
At the moment colors registered via `add_theme_support( 'editor-color-palette', ... )` give us just the classname in the editor. 

```
add_theme_support( 'editor-color-palette', [
    ...
    [
      'name' => __( 'Envy', 'textdomain' ),
      'slug' => 'envy',
      'color' => '#87A38F',
    ],
    [
      'name' => __( 'Pink', 'textdomain' ),
      'slug' => 'pink',
      'color' => '#a6186f',
    ],
    ...
] );
```

That means as a Theme Developer you have to manually add a stylesheet in the editor containing the styles related to text- and background color. Otherwise the preview looks something like this:
![color](https://user-images.githubusercontent.com/41627893/85019287-dff33b80-b16e-11ea-8dfc-9c16df9429fe.PNG)

Imo it would be a better solution to add the color via style tag in the editor to make things easier.

**Comment by oxyc** [comment]
I think it's related to https://github.com/WordPress/gutenberg/issues/21931#issuecomment-624814695 https://github.com/WordPress/gutenberg/pull/22356

**Comment by tabrizwp** [comment]
I have the same problem

**Comment by bfiessinger** [comment]
I'm closing this as it looks like it should have this behaviour.
