### ISSUE TITLE
Patterns should not display if their blocks are not allowed

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#23275]
**Describe the bug**
In the current version of Gutenberg (8.3.0) and several earlier versions, block patterns display even if the blocks they are composed of are not "allowed" on the post type (via the `allowed_block_types` filter). Patterns should be hidden if they are composed of disallowed blocks.

**To reproduce**
1. Create a post type
2. Use `allowed_block_types` filter to limit blocks down to one or two
3. Observe patterns displaying

**Expected behavior**
Patterns should only display if all their constituent blocks are available.

**Screenshots**
<img width="508" alt="Screen Shot 2020-06-18 at 8 58 18 AM" src="https://user-images.githubusercontent.com/1231306/85022847-dd2e2180-b141-11ea-8717-d87ab1e6b980.png">

**Comment by chrisvanpatten** [comment]
There might also be an intersection with `template_lock`; if you have the inserter open at the top level of a post which is template locked, the inserter displays "No results found" for the blocks inserter, but the pattern inserter displays all the registered patterns. Then, it still allows you to click to insert but in fact the pattern is not inserted because of the lock. It's a bit of a confusing UX.

**Comment by chrisvanpatten** [comment]
Here's a brief/blurry demo of what I see:

![demo-23275](https://user-images.githubusercontent.com/1231306/85574024-66db6480-b604-11ea-8265-106df1276bb9.gif)

**Comment by chvillanuevap** [comment]
This issue also applies to Reusable Blocks.

**Comment by jeremyfelt** [comment]
I needed to solve this for a custom post type of mine and spun off the solution into a standalone plugin: https://github.com/jeremyfelt/unregister-broken-patterns

I don't have enough familiarity with "allowed" vs registered/unregistered block types and how to account for that in thinking of **where** a solution should be implemented. My guess is that `WP_Block_Patterns_Registry::get_instance()->get_all_registered()` could be passed a block types array, but it could also go further down in `edit-form-blocks.php`. 🤷🏻

All in all, +1 for fixing this. :)

**Comment by justintadlock** [comment]
I literally just came across this issue while testing your Shortnotes plugin, @jeremyfelt.  Came here to create a new issue.

**Comment by jeremyfelt** [comment]
@justintadlock If you haven't found it yet, this is a plugin in the repo now too: https://wordpress.org/plugins/unregister-broken-patterns

I'm still behind on documenting the quirks. :)

**Comment by jeremyfelt** [comment]
Via #30300:

> This implementation only works for top-level blocks in patterns. If a pattern contains a block deep inside somewhere in its block tree, then it will still show up in the inserter. We need to recursively check for all blocks in the pattern.

@ntsekouras @david-szabo97 This ticket was auto-closed when #30300 was merged. Can it be reopened until a more complete solution is in place? Thanks!

**Comment by melcarthus** [comment]
I move my comment here -> https://github.com/WordPress/gutenberg/issues/31706#issuecomment-1804007727
