### ISSUE TITLE
Allow image drag and drop without being in block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2327]
2 experienced users have now done this and become unstuck when it opens a browser screen over just adds an image. Would be great to implement as an enhancement.

**Comment by iseulde** [comment]
I don't follow. Could you elaborate a bit more? I'm also not sure what is meant by the title.

**Comment by karmatosed** [comment]
Apologies, this came from a usability testing report. What currently happens is you can't just drag an image to the editor and have it upload. You have to be 'in' or select the image block. The request was to just drop one.

**Comment by mtias** [comment]
Done in #2447.
