### ISSUE TITLE
Image Block: Changing alignment removes image resizing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#23288]
**Describe the bug**

After resizing an image and then setting the image size, if one chooses to change alignment on the image, the resizing is undone. 

**To reproduce**
1. Create a new post
2. Add an image block
3. Manually resize the image using the image controls
4. Try resizing the image using "Image size" options under the Block Settings
5. Set alignment in the block editor and see image return to full size

This seems to only happen the first time this alignment is given to an image. For example, after alignment is given to an image, I can change the alignment without impacting the image size. 

**Expected behavior**
 
I expected the image to just be aligned properly without impacting the size of the image. 

**Screenshots**

Video: https://cloudup.com/cEZsO5sCdk6

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin installed
- If the Gutenberg plugin is installed, which version is it? 8.3

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 83.0.4103.106

**Comment by bfiessinger** [comment]
Seems to be related to #23234 where you can't use image size controls in the new version of the editor.

**Comment by gsallman** [comment]
Also appears to be related to: When full-sized image is selected only the large size image is displayed [#23128 ](https://github.com/WordPress/gutenberg/issues/23128)

**Comment by deborah86** [comment]
The image block for me is resizing when using the alignment settings. I did not manually resize the image. I just placed a new image block. The only setting I changed was the image alignment.

**Comment by jordesign** [comment]
I can no longer recreate this in WP6.3 - so I'll close this as resolved.
