### ISSUE TITLE
Unable to in text mode change the height and width without getting convert message

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2328]
If you add an image, then go to edit the width and height in text mode. You get the following:

![2017-08-10 at 10 14](https://user-images.githubusercontent.com/253067/29163635-f9552c1e-7db4-11e7-8177-0cd30a945d08.png)

It adds weight to having some scaling but I also wonder if we should have this message? Is there any way around it?

**Comment by mtias** [comment]
The message would allow you now to preserve the HTML, so closing.
