### ISSUE TITLE
Incorrect test to see if 'test-two-columns' pattern is registered

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#23302]
**Describe the bug**
In client-assets.php, the logic to Register default patterns if not registered in Core already
uses the wrong pattern name on the test. 

```
if ( class_exists( 'WP_Block_Patterns_Registry' ) && ! WP_Block_Patterns_Registry::get_instance()->is_registered( 'text-two-columns' ) ) {
	register_block_pattern( 'core/text-two-columns', gutenberg_load_block_pattern( 'text-two-columns' ) )
```
The parameter to `is_registered` should be 'core/text-two-columns'.

The code currently works because
1. No one registers the 'two-col-columns' pattern
2. No one's actually had a chance to register any block patterns when this logic is invoked.

**To reproduce**
See the code.

**Expected behavior**
Correct the code.
```
if ( class_exists( 'WP_Block_Patterns_Registry' ) && ! WP_Block_Patterns_Registry::get_instance()->is_registered( 'core/text-two-columns' ) ) {
	register_block_pattern( 'core/text-two-columns', gutenberg_load_block_pattern( 'text-two-columns' ) )
```

See also #23301 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- If the Gutenberg plugin is installed, which version is it? 8.3.0

**Comment by talldan** [comment]
This code doesn't seem to exist any more, so will close the issue. Thanks for reporting.
