### ISSUE TITLE
[ Navigation screen ] After inital load nested items cannot be moved in the navigator

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23309]
After the Navigation Screen has loaded, if there are nested items expanded, hovering over them does now show the movers:

![no-hover-nested](https://user-images.githubusercontent.com/107534/85131801-34b2b700-b240-11ea-8398-ed26e0c750bc.gif)

Clicking on the parent item solves the problem

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/pull/23680 will fix this one
