### ISSUE TITLE
When adding featured image don't show fields it doesn't use

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2330]
The caption and description are not used for featured images, it would be great to not have as options when adding:

![2017-08-10 at 10 25](https://user-images.githubusercontent.com/253067/29164157-7b93c8ce-7db6-11e7-8ffb-10210775171b.png)

**Comment by kmplngj** [comment]
I would also need this fields to display. My authors need this field to add descriptions to the post image and specially for copyright notices. Yes, it this possible to add this in the media library but it is not very userfriendly to change screen to add a copyright notice.

**Comment by karmatosed** [comment]
You need this for featured images @kmplngj ?

**Comment by kmplngj** [comment]
@karmatosed Yes. I add the comment because of this 😄 
I output this text on my single post layout. (In most cases I have to display copyright notices).

**Comment by karmatosed** [comment]
Ah interesting, ok in light of that who else finds them useful?

**Comment by brianpiccione** [comment]
I find them useful too and have actually overridden the css in my own admin stylesheet to get around it..
