### ISSUE TITLE
upload_dir filter is not consistently applied within the image and gallery blocks

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#23317]
**Describe the bug**
I have a [plugin that changes the upload directory if a specified post_type is currently 
open within the editor](https://gitlab.com/cpl/custom-post-agendas/-/blob/8e9438555abda8ca6df34a93bbf1db519f2dffa0/post-types/filter-upload-path.php). 

There's inconsistent behavior in the image block whether `upload_dir is applied depending on how the image is uploaded within the image block and I'm not sure if this is intentional and if it is, whether this should be changed. 

**To reproduce**
I created a test case plugin at https://gitlab.com/cpl/cpl-gutenberg-23317 
which uses the post type of 'page'
While creating a new post (e.g. PATHTOsite.fr/wp-admin/post-new.php?post_type=page)): 

1. install, activate plugin - https://gitlab.com/cpl/cpl-gutenberg-23317 
1. create new image block 
1. press upload 
the uploaded image goes to the default upload directory and the 
upload_dir filter is not applied; 

However, if I: 
1. create new image (or gallery) block, 
2. first press media library 
3. upload the image there, the upload_dir filter is applied; 
and the image is uploaded into the intended directory. 

Is this inconsistency is intentional? 

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4.2
- Gutenberg 8.5.1

**Comment by jorgefilipecosta** [comment]
Hi @skorasaurus,

Gutenberg uploads the images using the rest API media endpoint.
On the rest API, https://developer.wordpress.org/rest-api/reference/media/ media endpoint, the post id of a media object is referred as "post". I guess if you update the code to also fallback to $_POST['post'] things should work as expected.


Feel free to reopen the issue if you are still facing problems.
