### ISSUE TITLE
Navigation Screen: make it clear links need to be added for menu to be functional

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#23326]
**Is your feature request related to a problem? Please describe.**

Right now, when you're using the new navigation screen, nothing is stopping you from adding essentially empty links. Thinking like a new user, it's not necessarily clear that I would need to go back and link to things in the menu for it to truly work. In comparison, the previous menu screen had a built in flow that wouldn't allow a user to add an item to the menu without it first existing. 

Here's a 1 minute long video where I walk through both screens to better demonstrate the issue: https://cloudup.com/cXDDOWFgJO4

**Describe the solution you'd like**

I'd like to see prompts in the UI that ensure when someone adds an item to the menu, it's clear that a link needs to be added for it to be functional. Right now, the current flow makes it almost too easy to create empty menus. 

**Describe alternatives you've considered**

Not quite sure :)

**Comment by paaljoachim** [comment]
Here is an example of adding a link (no link)

![Screen Shot 2020-08-26 at 11 00 59](https://user-images.githubusercontent.com/5323259/91283858-72294880-e78b-11ea-9933-48512268889a.png)


Clicking enter or pressing the enter key results in having the test no link (text) added to the navigation.
Some alternatives as I see it.

Alt 1.
An alternative approach is hiding the enter icon and not being able to click the enter key to just add the text. 
As it forces the user to select among the below links, or scrolling to find the create a new page.
![Screen Shot 2020-08-26 at 11 03 41](https://user-images.githubusercontent.com/5323259/91284185-dc41ed80-e78b-11ea-9e25-721aed5a5b06.png)



Alt 2. Adding a pink background and a broken link icon.
![Nav-screen-no-link](https://user-images.githubusercontent.com/5323259/91286744-1cef3600-e78f-11ea-9360-3e855d42babe.jpg)
Thinking about this issue where pink background is used.
https://github.com/WordPress/gutenberg/issues/23573
