### ISSUE TITLE
Discussion: Should theme.json support conditional logic like theme supports

### ISSUE THREAD

**Issue by itsjusteileen** [WordPress/gutenberg#23324]
Theme creators use `add_theme_support` to allow themes to access a variety of WordPress features. Currently, there are several [theme_supports for block-enabled themes](https://developer.wordpress.org/block-editor/developers/themes/theme-support/) in core and a few experimental supports for the Gutenberg plugin. As the project moves closer to a richer Full-Site-Editing (FSE) experience with Global Styles what will be the proposed hierarchy/relationship between [experimental-theme.json](https://developer.wordpress.org/block-editor/developers/themes/theme-json/) and `add_theme_support`? This issue seeks to encourage discussion and feedback around where the design decisions will live in themes built for FSE, what should the best practices be for progressive enhancements, and to propose a potential solution for the addition of logic-based filtering for `experimental-theme.json` as found in add_theme_supports.

Current best practices working with Gutenberg enabled themes use `add_theme_support`  to tap into functionality.  For example, themes can have “design styles” which manipulate which colors are provided in the ColorPalette components via add_theme_support('editor-colors'), which isn’t currently achievable using theme.json.  While add_theme_support is a familiar mechanism for theme authors, embracing theme.json should be a logical path for the future providing less technical overhead to work through in future theme implementations. This would only be possible, however, if the same logic found in `add_theme_support` could also be supported in `experimental-theme.json` and it was filterable allowing for logic & conditions.

What is the current status of `experimental-themes.json` and could it eventually support the same functionality present in add_theme_support and how can the theme community best plan for future enhancements?

@richtabor, @kjellr, @aristath, @carolinan, @jffng contributed to [the conversation](https://wordpress.slack.com/archives/C02RP4Y3K/p1592411694364600).

**Comment by itsjusteileen** [comment]
Edit: added link

**Comment by paaljoachim** [comment]
Comment from @youknowriad during the Core Editor meeting:
https://wordpress.slack.com/archives/C02QB2JS7/p1593010149219300
"I don’t think we need to add condition logic to theme.json aside block vs global specific settings but the editor settings are filterable whether they come from theme.json or not, so conditional logic is possible there."

**Comment by skorasaurus** [comment]
Is there anything actionable in this issue since theme supports are now included in theme.json ? https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#backward-compatibility-with-add_theme_support

**Comment by paaljoachim** [comment]
I believe this issue would be interesting for @nosolosw @jorgefilipecosta and @aristath to take a closer look at.

**Comment by youknowriad** [comment]
I'm going to close this issue for now per my comment above. Please feel free to open new issues if needed but more focused on actual use-cases.
