### ISSUE TITLE
@wordpress/block-editor does not work standalone

### ISSUE THREAD

**Issue by saas-developer** [WordPress/gutenberg#23332]
**Describe the bug**
`@wordpress/block-editor` does not compile/run outside gutenberg.

**To reproduce**
1. Go here: https://www.npmjs.com/package/@wordpress/block-editor
2. Look at the usage example and copy and paste the code in a simple react app
3. It does not compile.
4. Error is

```
./node_modules/@wordpress/components/build-module/alignment-matrix-control/index.js
Attempted import error: 'unstable_Composite' is not exported from 'reakit' (imported as 'Composite').
```

**Expected behavior**
A standalone gutenberg editor should be initialized

**Screenshots**
![Screen Shot 2020-06-19 at 11 09 41 PM](https://user-images.githubusercontent.com/58209961/85194258-00f88100-b282-11ea-8e60-e34b796aa0ab.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 83

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by gziolo** [comment]
The issue is caused by the fact that the block editor was using unstable API from Reakit that was promoted to stable API. It should get resolved in a few days when WordPress packages with related changes are published to npm. 

Related comment in Reakit library where I ask whether renamed API can be aliased gor backward compatibility: https://github.com/reakit/reakit/pull/667#issuecomment-647108385

**Comment by gziolo** [comment]
I think https://github.com/WordPress/gutenberg/issues/23236 resolves it on our end, @diegohaz can you confirm?

**Comment by diegohaz** [comment]
#23236 fixes this, but it doesn't help with older versions. 😕

I'll make a patch on Reakit to fix this asap.

Ideally, when using experimental modules from npm packages, we should use the exact version in our package.json (without `^`).

**Comment by diegohaz** [comment]
It should be fixed now!

**Comment by joaojoyce** [comment]
Sorry for the dumb question, but how can I "npm install @wordpress/block-editor" for this particular fix/branch?

**Comment by gziolo** [comment]
You only need to install a new version of Reakit.
