### ISSUE TITLE
Dynamically change the theme support in the editor

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#23331]
I am wondering if there is a way dynamically change the theme support (defined via ‘add_theme_support’) in the editor using the Blog editor API.

Also, does the Block editor has a special API to check:

-  If a specific widget area is active (for example, we can use is_active_sidebar() function in PHP);
- Currently selected template in the editor (in the Page Attributes pane);

Here is a case.

The theme comes with a support for a sidebar. Also, the theme has a support for full and wide alignment. 

But is it possible to disable (toggle) a support for full and wide alignment if the current page has a default template and the sidebar is active on the site?

**Comment by oxyc** [comment]
I'm not well versed with APIs but I know you could at least solve your use case with PHP using the [block_editor_settings](https://developer.wordpress.org/reference/hooks/block_editor_settings/) filter.

**Comment by dashkevych** [comment]
This filter looks interesting. I was not aware of it. Thank you Oskar!

Now I need to find out the way to set dynamically set a theme support via JS. I've found a way to get a list of all available theme supports using this `wp.data.select("core").getThemeSupports()` but I am not sure how to change it.

**Comment by tellthemachines** [comment]
> Now I need to find out the way to set dynamically set a theme support via JS. I've found a way to get a list of all available theme supports using this wp.data.select("core").getThemeSupports() but I am not sure how to change it.

Theme support can only be set in the theme's PHP files, there's no way to change it in the editor. What you can do is create a child theme and [remove theme support](https://developer.wordpress.org/reference/functions/remove_theme_support/) for a certain parent theme feature. However, that'll work on a global level, it won't be template-specific.

> The theme comes with a support for a sidebar. Also, the theme has a support for full and wide alignment.
> But is it possible to disable (toggle) a support for full and wide alignment if the current page has a default template and the sidebar is active on the site?

The new [layout configuration](https://make.wordpress.org/core/2021/06/29/on-layout-and-content-width-in-wordpress-5-8/) and the [template editor](https://make.wordpress.org/core/2021/06/16/introducing-the-template-editor-in-wordpress-5-8/) may provide another way of solving this problem. You may also want to check out the dev note for [theme.json](https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/).

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this as there hasn't been any discussion here for a while.

A note that the problem of disabling wide/full alignments on a template with a sidebar can now easily be solved with block themes: wide/full alignments are only available when the parent block has a constrained layout type, so creating a main content column with a flow layout ensures those alignment options won't be present on children.
