### ISSUE TITLE
Splitting a block by hitting enter should retain the block ID for the initial block.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#23335]
When splitting a block using "Enter". If we had a block with clientID "a", we end up with two blocks with two new clientIds "b", "c". I think this is not great. Any third party plugin assinging meta data to blocks. Ideally, the original block clientId is retained during the whole lifecycle of an editing session unless the block is explicitely removed. I'd also expect that transforming blocks retains the IDs which it already does properly.

cc @ellatrix for thoughts.

**Comment by ellatrix** [comment]
Sure, we can try to do this. Would you expect the client id to be preserved if the block type changes? In other words, do you expect block type and attributes to change for a given client id? This can sometimes be the case, for example if you split at the start of a heading. You could also argue that in this case the second block should get the client id, or even better, the block should remain unchanged and a new block should be inserted before it.

**Comment by youknowriad** [comment]
I think right now the transforms already retain the clientId when transforming. i don't think there's a magic rule that applies automatically, but a good tradeoff could be to just say the first block retains the id. Unless the first blocks is external (paste)

**Comment by ZebulanStanphill** [comment]
Did #28505 fix this?

**Comment by ellatrix** [comment]
Yes
