### ISSUE TITLE
Multiple stacking update mesaages easy to achieve

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2334]
When you are writing a post you can easily get:

![2017-08-10 at 11 27](https://user-images.githubusercontent.com/253067/29166608-062f951e-7dbf-11e7-8668-2e17719c28ec.png)

If one hasn't been dismissed not showing another one probably is a better way than easily getting a full screen of these.

**Comment by folletto** [comment]
Adding one bit: I feel that showing many is better than showing the same. We had this issue on .com as it's not clear if someone updates again after the update... did it actually update?

My advice would be to find an approach that does't duplicate the box, but adds some marker that the update happened. A way to do it would be either a counter (`Post updated! View post (2)`) or a timestamp (`Post updated 2 minutes ago! View post`), or similar approach.

**Comment by aduth** [comment]
It's my understanding this should have been fixed by #2282

Previously: #2270

**Comment by folletto** [comment]
I'm just using the plugin so it might not have been shipped there yet. However, if it just not update the box if it's already present I think it's worse than stacking them, as it won't make clear that the update was successful — which is more important.

**Comment by aduth** [comment]
@folletto It clears any existing notice _at the time of save_, then once save completes it will show another. Depending on internet / server speed, this can be quick, but enough time to detect the change in my opinion.

**Comment by folletto** [comment]
Ok! 👍

**Comment by karmatosed** [comment]
I am still getting this on latest version unfortunately.

**Comment by karmatosed** [comment]
I'm not sure it did because it was this morning. I just retested and the issue works. Going to close and thanks for working through what version this was on.
