### ISSUE TITLE
Architecture appears twice in side bar and is redundant

### ISSUE THREAD

**Issue by MisterAwesome23** [WordPress/gutenberg#23340]
**Describe the bug**
In the Block Editor Documentation ([link](https://developer.wordpress.org/block-editor/))
Under 'Project Overview' in the side menu, the 'Architecture' appears twice and is redundant.

Also, the "edit on GitHub button" redirects to an Error 404 Page Not Found.
It points to- https://github.com/WordPress/gutenberg/edit/master/docs/architecture/index.md
Instead of pointing to- https://github.com/WordPress/gutenberg/edit/master/docs/architecture/readme.md

**To reproduce**
1. Go to 'https://developer.wordpress.org/block-editor/'
2. Click on 'Project Overview'
3. See bug

**Expected behavior**
Architecture should appear only once.

**Comment by MisterAwesome23** [comment]
Hey, I would like to fix this actually can someone help me get started with documentation improvements. Thank you.

**Comment by glendaviesnz** [comment]
Thanks for the offer to fix this @MisterAwesome23 -  have you see the guidelines for contributing documentation changes at https://developer.wordpress.org/block-editor/contributors/document/#block-editor-handbook-process ? Let us know if you have any questions about how to proceed after reading through that.

**Comment by MisterAwesome23** [comment]
Hello @glendaviesnz. Thank you for replying and providing link to the documentation page. I've have read through it now.

The issue seems to be solved (not by me). Kindly confirm that and close this.

Also, I wanted to know how could I edit the sidebar and not the page contents/redirections. Where does the code controlling the left sidebar menu reside?

**Comment by JustinyAhin** [comment]
Hi @MichalKarbownik yes, this seems to have been fixed already.
