### ISSUE TITLE
Doc: Add Gutenberg plugin version number integrated into WP releases.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23344]
**Is your feature request related to a problem? Please describe.**
I have heard a few requests asking for ways to figure out which Gutenberg plugin version is added to a WordPress version.

**Describe the solution you'd like**
I would like to see Gutenberg plugin version inside the Site Health WordPress tab. 
https://core.trac.wordpress.org/ticket/48329#comment:18

Discussions in Site Health Slack channel here (requires registration)
https://wordpress.slack.com/archives/CKSU841L7/p1590422991269400

> @mapk 
> I believe it’s to know which version of the Editor is in use. Is that determined by a package? 

> @aduth 
> Even that is not super straight-forward unfortunately. The scripts are registered from here:
> https://github.com/WordPress/wordpress-develop/blob/6ec9c9c/src/wp-includes/script-loader.php#L234-L238
> But the version used for the script isn’t based on the published package, it uses a hash based on the file contents:
> https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/assets/script-loader-packages.php
> The most reliable reference is the version specified in package.json
> https://github.com/WordPress/wordpress-develop/blob/6ec9c9c/package.json#L85
> But that file isn’t included in WordPress distributions, so it would need to be part of some build task to be able to embed that version information in a file available to other screens.
> 
> I kinda question the value this would have, even going back to the original request at https://github.com/WordPress/gutenberg/issues/14708
> If the version of the package were shown, I don’t know that it really gives a whole lot more information than what could be known just by asking what version of WordPress the user is running (edited) 
> If you want to pin it to a plugin version, the most straight-forward way would probably just have a manually maintained array of “WordPress 5.x -> Gutenberg 7.x” (again noting all the caveats of cherry-picked bug fixes, just pointing to whatever the last “Feature release” is)
> It becomes yet another thing to manage in a release though.

It does not look like adding it to the WordPress Site Health tab will happen.

The next best would be to add information to the core editor docs.
There was a discussion in the core editor Slack channel.
https://wordpress.slack.com/archives/C02QB2JS7/p1592566587468200

igmoweb:
> Hello. It has happened to me many times that I'm trying to debug something in the editor in different WP versions but it's always hard to find the editor version that WP core is using so I wanted to propose some sort of list to match WP versions with Gutenberg releases versions. This would make things very easy when cloning Gutenberg and switching to the proper tag so a developer can debug by using the source code. Another option (both can live together I guess), is to include $editor_version = '...' in version.php so anyone can look up the version quick. What's the best way to propose this?

Kenshino:
> That being said, is there plans for a doc page to show which versions of Gutenberg plugin is in which core WordPress version? I know we write it in release posts but is there a unified spot?

Paal Joachim:
The simplest we can do is have a doc page mentioning releases and which Gutenberg plugin was included. It gives a kind of basic overview.

igmoweb:
> I think that could be a start, some reference page would help to debug.
> The source code changes a lot from one version to another so picking the right version is important when you're debugging

@nerrad 
> Part of the difficulty here (and likely mentioned in all the above places) is that it’s not just a matter of the plugin version being in the core release. It’s actually various package versions that are included in WordPress core releases. Those don’t always correspond to a specific GB release.
> 
> If you’re wanting to know whether a feature is in a version of WordPress that you support, one option is to go to the WordPress develop github mirror, select a branch corresponding to a WordPress version, and then look at the package.json file for that version to see what @wordpress/* package versions are in that release
> 
> Another option, is to look in the wp/* branch in the Gutenberg repository which includes all the files that should be included in the corresponding WP version (eg wp/5.3)

**Comment by annezazu** [comment]
Just noting that I'm working on creating a v1 of a standalone page listing out Gutenberg Versions in WordPress versions :)   Where would it be best for this to live?

**Comment by annezazu** [comment]
For now... [here's a video of the process](https://cloudup.com/cSYbh6btKpk) I followed to get the following version numbers. I also snagged version numbers from [release field guides](https://make.wordpress.org/core/2020/03/03/wordpress-5-4-field-guide/). Big thanks to @mcsf and @talldan for pointing me in the right direction to get this information 🥇 


Gutenberg Versions | WordPress Version
-- | --
6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5 | 5.4.2
6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5 | 5.4.0
5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5 | 5.3.4
5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5 | 5.3.3
5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5 | 5.3.2
5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5 | 5.3.1
5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5 | 5.3.0
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.7
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.6
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.5
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.4
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.3
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.2
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.1
4.9, 5.0, 5.1, 5.2, 5.3, 5.4 | 5.2.0
4.8 | 5.1.6
4.8 | 5.1.5
4.8 | 5.1.4
4.8 | 5.1.3
4.8 | 5.1.2
4.8 | 5.1.1
4.8 | 5.1.0
4.7.1 | 5.0.10
4.7.1 | 5.0.9
4.7.1 | 5.0.8
4.7.1 | 5.0.7
4.7.1 | 5.0.6
4.7.1 | 5.0.5
4.7.1 | 5.0.4
4.7.1 | 5.0.3
4.7.0 | 5.0.2
4.6.1 | 5.0.1
4.6.1 | 5.0.0

**Comment by paaljoachim** [comment]
This is awesome work, Anne! Thank you! That should be helpful for many who have asked.
I asked in the core-site-health Slack channel and received this response:
"I'd check in with #docs about that, but I would expect some kind of addendum to the block editor article."

**Comment by zzap** [comment]
Thank you @annezazu, this is great info to have. I already commented in #docs slack but I'll repeat it here as well. I'd give it a dedicated page under `Project Overview` section. It's already long, it will only be longer and having all Gutenberg versions listed in one page (let alone connected with core versions like this) is not to be found anywhere. Awesome work.

**Comment by annezazu** [comment]
Just noting that this page now lives here: https://developer.wordpress.org/block-editor/principles/versions-in-wordpress/ I

**Comment by paaljoachim** [comment]
The paragraph above the list here: https://developer.wordpress.org/block-editor/principles/versions-in-wordpress/

With each WordPress release cycle, various versions of Gutenberg are included. This has created confusion over time as people try to figure out how best to debug problems and report bugs appropriately. To make this easier for everyone to keep track of, this document serves as a canonical list of the Gutenberg versions integrated into each WordPress release. Of note, during the beta period for WordPress releases, additional bug fixes from later Gutenberg releases than those noted are cherry-picked into the WordPress release as necessary.

Rephrasing suggestion
With each major release of WordPress a new version of Gutenberg is included. This has caused confusion over time as people have tried to figure out how to best debug problems and report bugs appropriately. To make this easier we have made this document to serve as a canonical list of the Gutenberg versions integrated into each major WordPress release. Of note, during the beta period of a WordPress release, additional bug fixes from later Gutenberg releases than those noted are added into the WordPress release where it is needed.

**Comment by talldan** [comment]
@paaljoachim Those changes have already been merged now. I'd recommend making a pull request yourself for further proposed changes. As you're a member, you can do that directly in github using the edit button on the file:
<img width="267" alt="Screenshot 2020-07-15 at 5 04 44 pm" src="https://user-images.githubusercontent.com/677833/87526386-56775080-c6bd-11ea-8793-4d65601fea76.png">

... and choosing the pull request option at the bottom when committing:
<img width="1176" alt="Screenshot 2020-07-15 at 5 05 30 pm" src="https://user-images.githubusercontent.com/677833/87526470-70b12e80-c6bd-11ea-9bec-4585b49c3c8d.png">

Then request @annezazu's review. 👍

**Comment by talldan** [comment]
Lets also close this issue now that the request has been fulfilled.

**Comment by annezazu** [comment]
Looping back to say that when 5.5 launches, I'll update that paragraph text when I update the Gutenberg column to show 5.5 as including 8.5.1 :) You're welcome to open a PR in the meantime but happy to handle it later.
