### ISSUE TITLE
Redo Media & Text Block to use nesting.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23356]
**Is your feature request related to a problem? Please describe.**
We should redo the Media & Text Block so it becomes a parent Block consisting of an Image Block and a Group Block.

Consistency. Handling of images should be the same in the Image Block, Gallery and the Media & Text Block. 

**The Image Block**

![Screen Shot 2020-06-22 at 13 47 23](https://user-images.githubusercontent.com/5323259/85284225-1db5d400-b48f-11ea-83b4-d2dfa47f648c.png)

Can add captions.
Has Styles
Alt Text
Image Size
Image dimensions

**The Media & Text Block**

![Screen Shot 2020-06-22 at 13 47 42](https://user-images.githubusercontent.com/5323259/85284275-2c03f000-b48f-11ea-961f-0951f6ea5f42.png)

**Describe the solution you'd like**
I would like to see the Media & Text Block become a parent block with a nested Image Block and a Group Block. Nested/Child Blocks have their own options in the sidebar. Clicking the parent Block shows the parent Block sidebar settings.

Advantage:
Creating a more flexible user experience.
Child Block have their own sidebar options.
Parent Block has its own sidebar settings.
Consistency between various blocks that use images.

**Describe alternatives you've considered**
To wait for additional options to be added to the Media & Text Block.

Associated Media & Text Block issues:
**"Preserve caption when converting Image Block to Media & Text Block "**
https://github.com/WordPress/gutenberg/issues/22478
**"Allow image styles on the 'Media & Text' block"**
https://github.com/WordPress/gutenberg/issues/20896
**"Make editing image related blocks more consistent"**
https://github.com/WordPress/gutenberg/issues/18529
**"Media & Text block: media dimensions"**
https://github.com/WordPress/gutenberg/issues/16853
**"Image caption in Media & Text block"**
https://github.com/WordPress/gutenberg/issues/14604
**"Media & Text: Insert from URL"**
https://github.com/WordPress/gutenberg/issues/14397

**Comment by youknowriad** [comment]
We can only use a single InnerBlocks inside a parent block, and the Media&Text block already uses nested blocks for the content (not the image). So in order to do this, we'd have to introduce an intermediary internal block. It means we'd have to figure out how to transform from the existing blocks to this one...

For me this is too complex and not worth the effort.

**Comment by paaljoachim** [comment]
My thinking is that if we are able to break down a Block into smaller pieces it would be good to do so.
Creating a parent - child relationship which is reflected in the options the parent and child offers. These should use existing Block methods.

From how I understand this:
Media & Text Block 
- Image (does not use image block options)
- InnerBlocks for Text.

As the Block already uses innerBlocks for Text it is at present time difficult to also add the Image as an innerBlock based on the Image Block.

It seems at present time Gutenberg is not ready to handle such a use case. Let's leave the issue open for now to gain additional feedback.

**Comment by mapk** [comment]
I'm in agreement with @youknowriad here. The great thing about the Media+Text block is that it's more of a pattern than a block and provides users with a quick layout. If I wanted to recreate it, I could with the Columns block (bottom) as shown below. So while the Media+Text block isn't using a nested block for the image, I believe it's still valuable unless we want to remove the Core block in favor of a Media+Text pattern using Columns.

![Screen Shot 2020-07-20 at 12 38 58 PM](https://user-images.githubusercontent.com/617986/87979042-4927e080-ca86-11ea-875e-12b67e696883.png)

**Comment by paaljoachim** [comment]
I see the point of the Media & Text could actually just be two columns with content. Similar to a pattern.
I will go ahead and close this issue.
