### ISSUE TITLE
Add ability to specify the version a function was deprecated

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#23373]
In some cases, it is desirable to indicate the version that a function was deprecated.

For example, a function was deprecated in [Core changeset 48121](https://core.trac.wordpress.org/changeset/48121/trunk/src/js/_enqueues/wp/password-strength-meter.js). For WordPress Core, this function will need to remain for quite a while for backwards compatibility, so the current `version` parameter does not work, as specifying it will output ` and will be removed from WordPress in x.x.x`.

It would be nice if there was also an option to specify the deprecated version to output something like `was deprecated in x.x.x and will be removed in y.y.y`, where both are optional.

**Comment by Mamaduka** [comment]
This would be really nice extra information to have in logs.

Now it takes time to track down Gutenberg/WordPress version when the component or method was deprecated.

Question: Should "since"  point to a Gutenberg plugin version or a WP version?
