### ISSUE TITLE
How to filter search results of UrlInput component?

### ISSUE THREAD

**Issue by bstarr322** [WordPress/gutenberg#23379]
### Goal
When we try to link the text with UrlInput component, It shows all posts contains the search value.

- We want to show the posts only, that the post's title contains the search value.
- We don't want to show the posts if the post's title doesn't contains the search value.

**Comment by talldan** [comment]
@bstarr322 It should act as you describe, only showing posts that contain the search value. Would you be able to share some example code and more details of the behavior you're seeing?

**Comment by bstarr322** [comment]
@talldan Thanks for your reply.
Here is the screenshot of current behavior.
**Screenshot:** https://www.screencast.com/t/0QUdcBqKtr
**Keyworkd: ** upcoming

It filters the following links as the article content has the keyword called `upcoming`.
https://test-golf-com.pantheonsite.io/news/fan-free-ryder-cup-affect-outcome-justin-leonard/
https://test-golf-com.pantheonsite.io/news/viktor-hovland-makes-history-stories-missed/

What we want is to filter the articles with just article title.

Hope this clear enough now!
Let me know if you need more info.

**Comment by talldan** [comment]
Thanks for clarifying @bstarr322.

For `URLInput`, I don't think there's a supported way to do this, only `experimental` APIs that might be released at some point.

Is it behavior you want to apply site wide, or only to a specific block?

**Comment by talldan** [comment]
Closing the issue as there hasn't been a response.

**Comment by bstarr322** [comment]
@talldan I just saw your comment. Thanks for letting me know!

> Closing the issue as there hasn't been a response.
