### ISSUE TITLE
Gallery: issues when turning crop off

### ISSUE THREAD

**Issue by keoshi** [WordPress/gutenberg#2337]
## Issue Overview

There are a couple of weird things going on when cropping is turned off in a gallery:

- Images dimensions get reformatted without respecting their original aspect ratio. Especially obvious when a gallery contains both an horizontal and vertical images, where the former is shrunk.
- Padding of the gallery block is increased on the bottom portion.

## Steps to Reproduce (for bugs)
1. Insert gallery with at least two images.
2. Turn _Crop Images_ off.

Using Chrome on Mac Version 59.0.3071.115 (Official Build) (64-bit).

## Examples

![guten-01](https://user-images.githubusercontent.com/390760/29168874-6fb5c0ac-7dc0-11e7-8883-cdfa107252cb.gif)

![guten-02](https://user-images.githubusercontent.com/390760/29169027-5ec99d3a-7dc1-11e7-9563-932b86ca7b3a.gif)

**Comment by jasmussen** [comment]
Thanks so much for the report. I'll take a look. There are a whole ton of improvements we can make here.

**Comment by keoshi** [comment]
@jasmussen Here's the full flow of adding a new gallery.

### Chrome Version 59.0.3071.115 (Official Build) (64-bit)
![guten-05-chrome](https://user-images.githubusercontent.com/390760/29312858-359e0800-81af-11e7-8592-6317a8610b5b.gif)

### Safari Version 10.1.2 (12603.3.8)
![guten-04-safari](https://user-images.githubusercontent.com/390760/29312864-3c3ea584-81af-11e7-93fc-c85d7a2a309b.gif)

**Comment by keoshi** [comment]
Right after I posted these, updated Chrome to the latest _Version 60.0.3112.101 (Official Build) (64-bit)_ and can confirm the same issues reported above.
