### ISSUE TITLE
Improve 'search' message to add context

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2338]
Props @mtias for this. We currently have:

![2017-08-10 at 12 45](https://user-images.githubusercontent.com/253067/29169056-e7a71076-7dc9-11e7-88ce-de68d6d764bd.png)

We should at least say:

- Search all available blocks

We could go further and add context. For example, we could do it depending on which tab on:

- Search all available blocks
- Search all recent blocks 

Later we could see if we can iterate by adding something such as:

- Discover all the available blocks

This could be more human but it may not work for users as well. Lets at least have more than 'search' which is all we have now.

**Comment by mtias** [comment]
> We could go further and add context. For example, we could do it depending on which tab on

Search isn't affected by which tab is selected.
