### ISSUE TITLE
Remove the experimental flag for the Block Directory

### ISSUE THREAD

**Issue by tellyworth** [WordPress/gutenberg#23384]
**Is your feature request related to a problem? Please describe.**
The Block Directory is currently only enabled via an experimental flag. That means it's seeing only minimal testing.

**Describe the solution you'd like**
The flag should be removed, enabling the Block Directory by default.

**Comment by ellatrix** [comment]
Cc @TimothyBJacobs I think here as well, we can remove the experimental namespace on the endpoints and stabilise next release? Not sure if this feature will need adjustments after launch.

**Comment by TimothyBJacobs** [comment]
We need to land #23219 first before changing the namespace. I'm also going to push a change to change the `plugin` field to not have `.php` at the end.

**Comment by TimothyBJacobs** [comment]
I've opened #23395 for the `plugin` field change.

**Comment by ellatrix** [comment]
Fixed by #23389.
