### ISSUE TITLE
ADD block errors due to layout shift

### ISSUE THREAD

**Issue by bobeaston** [WordPress/gutenberg#23392]
Too often, I find myself adding the wrong block.  Just as I click a block, the layout changes and a different block takes the place of the target I was attempting to hit.  (Google calls it "Cumulative Layout Shift.")

Yes, I have more than a few reusable blocks (2 pages worth) and use many of them frequently.  When I start to add a block, especially the first since opening the edit session, the selection dances around a bit, bringing up recently used reusable blocks.  If I'm in a hurry and don't wait for the dancing to settle down, I frequently hit a target just as it is changing.

It would be a real good thing to reduce this lag.  I like dancing, but just not in web interfaces.

**To reproduce**
Not hard to reproduce on a site having 20 or more reusable blocks with some used very recently.
Just hit the add button and click the space for the middle of the top row and see what you get.  :)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Using the native G'berg block editor ... no plugins

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave 
 - Version 1.10.95 Chromium: 83.0.4103.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
- not using for editing

**Additional context**
Server: Dreamhost VPS hosting only 2 websites, barely busy.

**Comment by annezazu** [comment]
@bobeaston whew that doesn't sound like a fun experience. Thanks for reporting! If possible, it would be awesome to get a quick video of this behavior. Otherwise, I've labeled it so others can dig in.

**Comment by bobeaston** [comment]
Thanks for the interest.  I'll try to get a screen capture.

In the meantime, I think the best way to suggest recreating is to have several reusable blocks that are in frequent use, and therefore  candidates to be offered in the picker (discovery panel, or whatever it's called).  In my case, I have about 25 reusable blocks, but was going through a series of posts to add 2 particular blocks to each. I had not noticed this behavior before that editing run where I started using those blocks frequently.

**Comment by bobeaston** [comment]
Find attached a short video.
Background:  I have about 25 reusable blocks.  Just before opening this document for editing, I had reused the group block named "Related Lessons: written o"  and image block named "Thank You".

The video starts just after opening this document for editing. While adding a block, watched the object in the lower right corner of the picker.  The delay is long enough that I have sometimes chosen the first block and received the second that takes its place.

Thanks for any interest.  In the meantime, I know to wait.

[gutenberg objects dance.zip](https://github.com/WordPress/gutenberg/files/4857854/gutenberg.objects.dance.zip)

**Comment by bobeaston** [comment]
Thanks!  Yet another too-quick button press for someone who doesn't read the labels.  :)

**Comment by Mamaduka** [comment]
This probably was resolved after the Reusable Blocks moved into a separate tab - #23296.

I'm going to close the issue. @bobeaston, feel free to re-open it if you're still experiencing problems with Reusable block loading in the inserter.
