### ISSUE TITLE
Default webpack config excludes the CSS loader for `components` styles.css

### ISSUE THREAD

**Issue by pierlon** [WordPress/gutenberg#23402]
**Describe the bug**

When the `Button` component is imported from `@wordpress/components`, I receive the following error when compiling:

```
ERROR in ./node_modules/@wordpress/components/build-style/style.css 60:0
    Module parse failed: Unexpected token (60:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |  * Reset the WP Admin page styles for Gutenberg-like pages.
    |  */
    > .components-animate__appear {
    |   animation: components-animate__appear-animation 0.1s cubic-bezier(0, 0, 0.2, 1) 0s;
    |   animation-fill-mode: forwards; }
```

The issue seems to be with the [default Webpack config](https://github.com/WordPress/gutenberg/blob/bfcb18d89f14f4ffc77348dd44ab6e6869b4ec04/packages/scripts/config/webpack.config.js). It is configured to exclude the `node_modules` folder for the CSS module rule:

https://github.com/WordPress/gutenberg/blob/bfcb18d89f14f4ffc77348dd44ab6e6869b4ec04/packages/scripts/config/webpack.config.js#L116

This would mean that the CSS loader will not be used for `node_modules/@wordpress/components/build-style/style.css`, and so Webpack would not know what loader to use.

**To reproduce**
1. Import the `Button` React component from `@wordpress/components`
2. Build the project with the default Webpack config from `@wordpress/scripts/config/webpack.config`
3. See error

**Expected behavior**
Webpack should use the default CSS loader to compile `node_modules/@wordpress/components/build-style/style.css`.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by gziolo** [comment]
It sounds like something that should be updated.

@ocean90 do you think we should relax the `exclude` handling for `*.css` and leave it as is for SASS/SCSS?

**Comment by ocean90** [comment]
Are you saying that you include `@wordpress/components` in your own build file? I think that's out of scope for @wordpress/scripts and its default webpack config.

**Comment by gziolo** [comment]
It would work more or less like CSS file concatenation plus it would apply some optimizations when building for production. I guess you can always enqueue those files separately. Let's see what other folks think.

**Comment by gregrickaby** [comment]
Confirmed. 

Removing the `exclude: /node_modules/` line from [webpack.config.js](https://github.com/WordPress/gutenberg/blob/master/packages/scripts/config/webpack.config.js#L116) allows me to include and compile CSS from 3rd party libraries located in `/node_modules`.

![screenshot](https://dl.dropbox.com/s/f9ucv9luou7jvbb/Screenshot%202020-06-25%2009.50.34.png?dl=0)

**Comment by ocean90** [comment]
@gregrickaby Which 3rd party library are you using?
