### ISSUE TITLE
Metaboxes shrink in-editor mobile preview pane height to un-viewable size

### ISSUE THREAD

**Issue by claudiulodro** [WordPress/gutenberg#23404]
**Describe the bug**
When metaboxes are present, the in-editor mobile preview height shrinks down, often becoming unusable because it's so short.

**To reproduce**
1. Add some plugins that use metaboxes (e.g. CoAuthors Plus and Yoast SEO). This issue is most noticeable with Yoast SEO, as their metabox is so huge.
2. Click on Preview > Tablet or Preview > Mobile
3. Observe the preview pane is just a thin sliver.
4. Collapse the metaboxes using the little arrows. Observe the situation is better, but they are still squishing the pane somewhat.

**Expected behavior**
I think the mobile preview pane should be unnaffected by the presence of metaboxes, and should not get shorter by their presence.

**Screenshots**
<img width="1210" alt="Screen Shot 2020-06-23 at 1 33 06 PM" src="https://user-images.githubusercontent.com/7317227/85459435-03dfc400-b557-11ea-8641-1053bb74e91b.png">
<img width="1205" alt="Screen Shot 2020-06-23 at 1 21 08 PM" src="https://user-images.githubusercontent.com/7317227/85459453-07734b00-b557-11ea-9686-dac88204c869.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.3.0 (latest version at the time of this issue)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.106

**Smartphone (please complete the following information):**
n/a

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
Seems to be caused by `overflow-y: auto` being applied to the wrapping element for the editor (`.edit-post-visual-editor`).

That overflow rule does seem necessary for making the post content scrollable, but I think the container could also do with a min-height to make it not collapse.

**Comment by afercia** [comment]
Noting this has also been reported on Trac: https://core.trac.wordpress.org/ticket/50819
