### ISSUE TITLE
Add an error boundary to the experimental navigation page

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#23417]
**Is your feature request related to a problem? Please describe.**
When an exception is thrown on the experimental navigation page, things just break without the user being alerted. It usually results in a blank page.

**Describe the solution you'd like**
Add an `ErrorBoundary` component, like the post editor has:
<img width="876" alt="Screenshot 2020-06-24 at 4 38 15 pm" src="https://user-images.githubusercontent.com/677833/85523393-804ad380-b639-11ea-9393-b8c92ba8c9a3.png">

This component implements most of the behavior already:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/error-boundary/index.js

**Describe alternatives you've considered**
n/a

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/pull/23679 will solve it. A good follow-up would be creating a configurable/abstract error boundary for all `@wordpress/*` packages.

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/pull/23679 is now merged and so this issue is fixed
