### ISSUE TITLE
Custom block stylesheet loading order is wrong

### ISSUE THREAD

**Issue by npmDude** [WordPress/gutenberg#23411]
**Describe the bug**
When registering the stylesheet for my plugin and using it. The editor stylesheet is being loaded first before the base style.

**To reproduce**
1. Register base style and editor style on plugin.
2. On devtools you will see the editor stylesheet being loaded first.

**Expected behavior**
Based on the documentation
The stylesheets enqueued by style are the base styles and are loaded first. The editor stylesheet will be loaded after it.

**Screenshots**
![image](https://user-images.githubusercontent.com/37074771/85505729-ee879a00-b629-11ea-9450-226eda895bac.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg version: 8.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 83

**Comment by talldan** [comment]
> Based on the documentation

@npmDude Which documentation?
