### ISSUE TITLE
Highlight remains after selecting other block

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#23413]
**Describe the bug**

Probably caused by #20938. When you move a block and then select another, the highlight remains visible on the first block.

![highlight-bug](https://user-images.githubusercontent.com/4710635/85517234-bc654080-b607-11ea-8c86-0498fba6c72c.gif)

**Comment by ItsJonQ** [comment]
Thanks @ellatrix ! Will look into this 💪
