### ISSUE TITLE
Editor crashes to white page when toggling list to quote

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#2343]
## Issue Overview

![aug-10-2017 15-17-28](https://user-images.githubusercontent.com/5389513/29172083-126d26dc-7ddf-11e7-8e38-580db2404880.gif)

## Steps to Reproduce (for bugs)

1. Create a `New Post`.
2. Add a `List` Block.
3. Enter some text in your list item(s). 
4. Toggle to a quote block.

These are the console warnings:
<img width="837" alt="developer_tools_-_http___src_wordpress-develop_dev_wp-admin_admin_php_page_gutenberg" src="https://user-images.githubusercontent.com/5389513/29172336-f68c34e8-7ddf-11e7-80f4-3ede27018684.png">

Tested on:
Chrome - Version 60.0.3112.90 (Official Build) (64-bit)
Safari - Version 10.1.2 (12603.3.8)

Wordpress - 4.8.1
Gutenberg - 0.7.1

## Expected Behavior
Expect the block to switch to a quote and changing each bullet in the list to a new line in the quote.

## Current Behavior
Crashes the editor to a white screen.

**Comment by aduth** [comment]
Similar issue with simply creating a new Quote block. Assigning myself.

**Comment by Xyfi** [comment]
@aduth Yes, we noticed that later too.
