### ISSUE TITLE
Group block does not have alignment controls in the full-site editor

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#23431]
**Describe the bug**

The Group block does not include its alignment controls when used in the context of the full-site editor.

**To reproduce**

1. Open the full-site editor
2. Add a group block
3. Note that the block does not include alignment controls.

**Expected behavior**

I expected to be able to make the Group block full-width (or any width that it normally offers in the post/page editor). 

**Screenshots**

![group-block](https://user-images.githubusercontent.com/1202812/85623975-35c85780-b637-11ea-8d87-acb5b07dff2b.gif)

**Editor version (please complete the following information):**
Gutenberg v8.4 & `master`

**Comment by Copons** [comment]
@kjellr would you mind checking this again?
I've just tried on current master (71bf1b5146d5dd0fc15792c1a98fc19df25b062f) and I can see and use the Group block's alignment toolbar. 🤔 

<img width="1090" alt="Screenshot 2020-07-29 at 15 22 49" src="https://user-images.githubusercontent.com/2070010/88812220-63ad3880-d1af-11ea-9e1c-1c6e71916f62.png">

**Comment by kjellr** [comment]
Yep, this appears to be fixed now! I'll close — thanks for the ping.
