### ISSUE TITLE
Editor: Styling differences between inserter previews and editor content

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#23434]
**Describe the bug**
The styles applied to block pattern previews in the inserter are different than what is applied to editor content. For example, the collage-gallery block pattern preview displays a different layout than what is shown in the editor. (What is shown in the editor is the correct formatting)

**To reproduce**
1. Navigate to my sites -> posts -> Add new post
2. Open Gutenberg Inserter
3. Click on Block Patterns Tab
4. Add a `collage-gallery` block to the editor

**Expected behavior**
The collage-gallery block pattern preview looks identical to what is shown in the editor. (What is shown in the editor is the correct formatting)

**Screenshots**
<img width="1285" alt="Screen Shot 2020-06-24 at 2 49 28 PM" src="https://user-images.githubusercontent.com/5414230/85631238-07904b00-b62a-11ea-886e-39473eb80447.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Gutenberg Plugin v8.3.0

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: Chrome, Firefox, Safari

**Additional context**
This bug was identified while fixing block pattern preview scaling. It was determined that the issue we describe here was unique enough to warrant a separate pull request. 43362-GH-wp-calypso

**Comment by jeyip** [comment]
After some digging, I determined that the cause is a missing `box-sizing` property. The style is inherited by elements in the editor but **_not_** by elements in the block inserter. I verified the cause by adding box-sizing as an inline style for block pattern previews (see GIF) Once included, the preview matches the rendered output.

![block pattern preview](https://user-images.githubusercontent.com/5414230/85493589-0a3c6300-b58c-11ea-988f-144182714b13.gif)

Here's a link to the actual styles:
`gutenberg/packages/edit-post/src/style.scss:61`
`gutenberg/packages/base-styles/_mixins.scss:397`

Some remaining questions I have that can be addressed when we create a new issue:
1. My intuition says that global styles for previews and editor content should be as similar as possible. Was applying box-sizing styles to the editor and not the inserter deliberate?
2. Who would be the best person to consult about making changes to these global styles?

The alternative is to add box-sizing as an inline style to block pattern previews. That, however, seems susceptible to problems in the future if CSS styles continue to diverge.

**Comment by Addison-Stavlo** [comment]
> I determined that the cause is a missing box-sizing property. The style is inherited by elements in the editor but not by elements in the block inserter.

While this specific pattern doesn't exist here, I think this is the important thing to consider.  It looks like there is a mismatch in the styles that are used between the previews and the actual editor.

**Comment by youknowriad** [comment]
Yes, the box-sizing is added globally to the editor. I wonder why it's not being applied there. That said, ideally, the box-sizing is not something we add globally but more per component. I  don't think that's possible at the moment so we need to figure out why the global rule is not applied there.

**Comment by Addison-Stavlo** [comment]
it seems like this has been resolved after stumbling across this older issue and testing that pattern recently
