### ISSUE TITLE
Normalize colors for destructive elements

### ISSUE THREAD

**Issue by OksanaRomaniv** [WordPress/gutenberg#23455]
**Is your feature request related to a problem? Please describe.**
This is just a small suggestion for the UI design

**Describe the solution you'd like**
At the moment the "Move to trash" link has a different shade of red than the rendered `<Button isLink isDestructive>`. It would be better to have the same colors for all `isDestructive` links in the UI

[screenshot](https://drive.google.com/file/d/128o6HkGuIWFu4PGlIHnuP4qqtbVm-mQn/view?usp=sharing)

**Comment by paaljoachim** [comment]
Hi Oksana @OksanaRomaniv 

<img width="418" alt="Screen Shot 2020-12-15 at 17 12 29" src="https://user-images.githubusercontent.com/5323259/102240974-bf772480-3ef8-11eb-9d90-c20ed20528df.png">

The Warehouse Connection panel is from either from a theme or plugin you are using. It has nothing to do with the Gutenberg core plugin. + Todays version of Gutenberg looks different than from your screenshot.

<img width="340" alt="Screen Shot 2020-12-15 at 17 13 50" src="https://user-images.githubusercontent.com/5323259/102241205-fc431b80-3ef8-11eb-9443-776131602813.png">

This issue does not seem valid, so I will go ahead and close it.
