### ISSUE TITLE
When dropping a block (after drag), the page scrolls to a different location

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#23457]
**Describe the bug**

Mentioned in #23448.

Try dragging, then dropping a block somewhere. Page is scrolled away from the target.

**Comment by ellatrix** [comment]
@talldan Are you able to reproduce this?

**Comment by talldan** [comment]
@ellatrix I was actually just looking at this. 😄 

I remember being able to reproduce it, but I can't now.

On a different matter, I do sometimes see an error in the console when dragging, so will try to fix that separately:
<img width="650" alt="Screenshot 2020-07-02 at 4 56 50 pm" src="https://user-images.githubusercontent.com/677833/86338608-1cea2280-bc85-11ea-8092-fea54f15609a.png">

**Comment by ellatrix** [comment]
I also remember seeing it more often. I feel like it happens a bit more often with a multi block selection

**Comment by ntsekouras** [comment]
I can't reproduce it either. @ellatrix can you still reproduce it?

**Comment by youknowriad** [comment]
Closing for now.
