### ISSUE TITLE
z-index of current selected blocks

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#23451]
Currently working with columns can be quite hard when using many of them or nested columns. Elements inside that need more space can sometimes overlap. Especially when using ACF or another custom fields tool to create custom blocks.
The interface can be quite unusable.

An easy to implement fix would be to redefine the z-index of the current block and its parents higher than the unselected blocks.

![columns](https://user-images.githubusercontent.com/41627893/85692870-0ddc0100-b6d6-11ea-86c3-ff938dccb5ec.PNG)

**Comment by talldan** [comment]
Thanks for reaching out @bfiessinger. A similar issue was described in https://github.com/WordPress/gutenberg/issues/16647, so I'll close your issue as a duplicate.
