### ISSUE TITLE
Gallery (re)move buttons are looking strange

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#23469]
<img width="770" alt="Screenshot 2020-06-25 at 16 46 21" src="https://user-images.githubusercontent.com/4710635/85731801-7db4b080-b703-11ea-87a4-b0f68fc93f90.png">

**Comment by ellatrix** [comment]
They're not the way they look in #20776. Cc @ItsJonQ

**Comment by ItsJonQ** [comment]
Hmm! Not sure what happened here. I'll see what I can do! 💪

**Comment by ItsJonQ** [comment]
Update: I looks okay in Chrome and Firefox. It appears buggy in Safari

**Comment by ItsJonQ** [comment]
Hmm! Looks like a newer style is overridding the padding resets for the buttons.

<img width="304" alt="Screen Shot 2020-06-25 at 10 08 24 AM" src="https://user-images.githubusercontent.com/2322354/85736053-27784b00-b6cc-11ea-9863-aea546484d6f.png">

I have a fix. PR incoming
