### ISSUE TITLE
Custom outline button color not working

### ISSUE THREAD

**Issue by bradley2083** [WordPress/gutenberg#23481]
**Describe the bug**
If you add an outline button and customize the color, the default color is overwriting the custom color (see screenshot of the default color #32373c overwriting the custom purple color I've selected).

**To reproduce**
1. Add button block
2. choose outline style
3. Pick custom color
4. Preview 

**Screenshots**
<img width="1229" alt="Screen Shot 2020-06-25 at 11 12 46 AM" src="https://user-images.githubusercontent.com/1781226/85775999-2566ba00-b6d5-11ea-8a0a-0a8ce6f001ef.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Yes, has Gutenberg plugin installed
- If the Gutenberg plugin is installed, which version is it? 8.4.0

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 83.0.4103.97

**Comment by annezazu** [comment]
@bradley2083 thanks for filing this issue! I tried to replicate it using WordPress 5.5 RC and Gutenberg 8.6.1 but wasn't able to do so. Here's a video: https://cloudup.com/c-7Gnq3hc4I For context, I did this without any additional plugins installed using the twenty twenty theme.

I'm going to close this out as a result but you're welcome to re-open if this continues to be a problem with the more recent releases! I'd recommend ruling out a theme conflict first though (aka your theme is overriding these styles).
