### ISSUE TITLE
CSS style file from custom block plugin is not being enqueued after updating to v8.4.0

### ISSUE THREAD

**Issue by adsheyn** [WordPress/gutenberg#23485]
**Describe the bug**
I've made a custom block plugin and everything worked fine until I've updated Gutenberg plugin to version 8.4.0 from 8.3.0.
Now, CSS file from my plugin is not being enqueued on the frontend. On the post edit screen that css file is enqueued and look OK. 

**Editor version (please complete the following information):**
I'm using the latest WP version with the Gutenberg plugin installed.

**Comment by gziolo** [comment]
Does it enqueue properly when the block is included on the page? We are testing optimization that loads block’s CSS on the front-end only when it’s used.

**Comment by adsheyn** [comment]
Even if the block is on the page the CSS file is not included. Not sure how this new optimization works, maybe it works with single block plugins but not with multi-blocks plugins.

**Comment by gziolo** [comment]
Does it mean that multiple blocks share the same style and only one of them enqueues this this style? I’m trying to understand what use case are you describing.

**Comment by adsheyn** [comment]
I'm using the Create Guten Block by Ahmad Awais to make custom blocks, so there is only one CSS file and one js script that register all the blocks at once.

**Comment by gziolo** [comment]
Can you share the part of the code that registers and enqueues this CSS?

**Comment by adsheyn** [comment]
Here is the content of the init file:

`<?php
/**
 * Blocks Initializer
 *
 * Enqueue CSS/JS of all the blocks.
 *
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enqueue Gutenberg block assets for both frontend + backend.
 *
 * Assets enqueued:
 * 1. blocks.style.build.css - Frontend + Backend.
 * 2. blocks.build.js - Backend.
 * 3. blocks.editor.build.css - Backend.
 *
 * @uses {wp-blocks} for block type registration & related functions.
 * @uses {wp-element} for WP Element abstraction — structure of blocks.
 * @uses {wp-i18n} to internationalize the block's text.
 * @uses {wp-editor} for WP editor styles.
 * @since 1.0.0
 */

function mp_blocks_assets() { // phpcs:ignore

	// Register block styles for both frontend + backend.
	wp_register_style(
		'mp-blocks-style', // Handle.
		plugins_url( 'dist/blocks.style.build.css', dirname( __FILE__ ) ), // Block style CSS.
		array(), // Dependency to include the CSS after it.
		null // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.style.build.css' ) // Version: File modification time.
	);

	// Register block editor styles for backend.
	wp_register_style(
		'mp-blocks-editor-style', // Handle.
		plugins_url( 'dist/blocks.editor.build.css', dirname( __FILE__ ) ), // Block editor CSS.
		array( 'wp-edit-blocks' ), // Dependency to include the CSS after it.
		null // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.editor.build.css' ) // Version: File modification time.
	);

	// Register block editor script for backend.
	wp_register_script(
		'mp-blocks-editor-script', // Handle.
		plugins_url( '/dist/blocks.build.js', dirname( __FILE__ ) ), // Block.build.js: We register the block here. Built with Webpack.
		array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-editor' ), // Dependencies, defined above.
		null, // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.build.js' ), // Version: filemtime — Gets file modification time.
		true // Enqueue the script in the footer.
	);


	// WP Localized globals. Use dynamic PHP stuff in JavaScript via `cgbGlobal` object.
	wp_localize_script(
		'mp-blocks-editor-script',
		'cgbGlobal', // Array containing dynamic data for a JS Global.
		[
			'pluginDirPath' => plugin_dir_path( __DIR__ ),
			'pluginDirUrl'  => plugin_dir_url( __DIR__ ),
			// Add more data here that you want to access from `cgbGlobal` object.
		]
	);

	/**
	 * Register Gutenberg block on server-side.
	 *
	 * Register the block on server-side to ensure that the block
	 * scripts and styles for both frontend and backend are
	 * enqueued when the editor loads.
	 *
	 * @link https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type#enqueuing-block-scripts
	 * @since 1.16.0
	 */
	register_block_type(
		'mp/mp-blocks', array(

			// Enqueue blocks.style.build.css on both frontend & backend.
			'style'         => 'mp-blocks-style',

			// Enqueue blocks.editor.build.css in the editor only.
			'editor_style'  => 'mp-blocks-editor-style',

			// Enqueue blocks.build.js in the editor only.
			'editor_script' => 'mp-blocks-editor-script',

		)
	);

}

// Hook: Block assets.
add_action( 'init', 'mp_blocks_assets' );


/**
 * Add custom block categories
 */
function mp_register_block_categories( $categories, $post ) {
	return array_merge(
		$categories,
		array(
			array(
				'slug' => 'mp-blocks',
				'title' => __( 'MP Blocks', 'mp-blocks' ),
			),
		)
	);
}
add_filter( 'block_categories', 'mp_register_block_categories', 10, 2 );
`

**Comment by gziolo** [comment]
It must be related to #22754 where people started reporting similar issues after 8.4.0 release. I think the best way to go is to revert those changes and try a different approach in WordPress core.

**Comment by gziolo** [comment]
Now that #22754 was reverted, it shouldn't be an issue after the Gutenberg plugin release planned for later this week.
