### ISSUE TITLE
Docs: Add Block Directory to Create a Block tutorial

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#23484]
The final page in the Create a Block tutorial is for the finishing touches after creating your block. This is intended to be a spot to include the details for submitting the block to the block directory. PR #22831 is now merged so we can further iterate, note the tutorial is not yet linked to the Block Editor handbook. 

Next: We should get the block directory steps added to the [finishing page here](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/create-block/finishing.md) and the documentation work @StevenDufresne has done for auditing a block included throughout the tutorial

We also need to make sure @coreymckrill and @gziolo work for block.json in PR #23399 is included in the tutorial

cc: @annezazu 
Related: #22151

**Comment by paaljoachim** [comment]
Going through the Create a Blocking **Finishing Touches** page. 

The page contains a very useful collection of links!


Here are my typo/rephrasing suggestions.

"This tutorial covers the basic structure of building a block, and the general concepts for creating a basic blocks. This sets you up for creating numerous more complicated blocks iterating and adding to this."
-->
This tutorial covers general concepts and structure for creating basic blocks. 
(No need for this sentence: This sets you up for creating numerous more complicated blocks iterating and adding to this." )

--

"The InspectorPanel, the settings on the right for a block, and Block Controls have a standard way to implement."
-->
The InspectorPanel (the settings in the sidebar to the right for a block), and the Block Controls (toolbar controls) have a standard way to be implemented. 

--

"creat" -> create
NB. The Sidebar tutorial link goes to here: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/plugin-sidebar-0.md 
to a 404 error page.

--

"..see the Using InnerBlocks documentation" -> Add . after documentation.

--

"...and the code is available to browse."
-->
and you can browse the code. / person can view the code by doing so and so.....

--

"A good way is to find a core block doing something close to what you are interested, and read through its code to see how things are done."
-->
A good way to learn how things are done is to find a core block code that does something close to what you are interested in and then using the same approach for your own block.

**Comment by mkaz** [comment]
@paaljoachim Thanks for the feedback, I've created the PR #23654 and included these updates 👍
