### ISSUE TITLE
When 2 plugins are using the new CSS feature of wp-scripts an error happens.

### ISSUE THREAD

**Issue by npmDude** [WordPress/gutenberg#23498]
**Describe the bug**
This happened when a third party plugin I use updated to use the new feature of wp-scripts. I'm using the new feature also. An error happens when I try to import style.scss files on my block and use the build script. Using the start script is fine, only the build script is not functioning well. As it happens, some of the blocks from the other plugin also went missing.

**To reproduce**
1. Install [Bootstrap Blocks plugin](https://wordpress.org/plugins/wp-bootstrap-blocks/)
2. Create your own plugin with a block that has both editor and style stylesheets.
3. Run wp-scripts build
4. See error on console on refresh

**Expected behavior**
No error would pop up and no blocks from the other plugin will be missing.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg version: 8.3.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83

**Comment by gziolo** [comment]
Can you share which version of `@wordpress/scripts` are you using? Is it the latest one? There was an issue with CSS handling that was addressed in https://github.com/WordPress/gutenberg/pull/23127 (v11.0.0).

**Comment by tschortsch** [comment]
In the `wp-bootstrap-blocks` plugin we're using v11.0.0 of the `@wordpress/scripts` package (see: https://github.com/liip/bootstrap-blocks-wordpress-plugin/blob/master/package-lock.json#L2902)

**Comment by gziolo** [comment]
Can you share this dummy plugin? I’d like to investigate it locally.

**Comment by tschortsch** [comment]
Here you go: [wp-scripts-plugin.zip](https://github.com/WordPress/gutenberg/files/4868610/wp-scripts-plugin.zip)

**Comment by npmDude** [comment]
I was also using a v11.0.0 on my plugin but I guess you can reproduce the issue with the mentioned dummy plugin.

**Comment by gziolo** [comment]
I was able to reproduce it myself. Thanks for help 👍

**Comment by gziolo** [comment]
I have #23710 that fixes the issue at least for the example plugin shared.
