### ISSUE TITLE
Site editor: Inserter missing functionality

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#23492]
**Describe the bug**
The Inserter in the post editor was recently updated and some of the functionality is missing in the site editor's version of the Inserter.

1. The "Browse all" button is missing.

**Current:**
![image](https://user-images.githubusercontent.com/1123119/85793407-32de6d00-b6f2-11ea-9251-20e8f15c9bc1.png)

**Expected:**
![image](https://user-images.githubusercontent.com/1123119/85793385-2ce88c00-b6f2-11ea-8c95-b1aaba41bc0f.png)

2. Patterns are not showing when initiating a search.

**Current:**
![image](https://user-images.githubusercontent.com/1123119/85793280-04f92880-b6f2-11ea-9e50-22de91429bf3.png)

**Expected:**
![image](https://user-images.githubusercontent.com/1123119/85793292-09254600-b6f2-11ea-9343-85d158038863.png)

**Comment by epiqueras** [comment]
@gziolo @WordPress/gutenberg-core Why aren't the changes here part of the block editor and carry over?

**Comment by epiqueras** [comment]
@MichaelArestad Ahh, the post editor is using the new `__experimentalIsQuick` inserter option. Should we enable it in the site editor too?

**Comment by youknowriad** [comment]
There's also another setting on the block-editor settings to toggle the main inserter otherwise there's no way for  the quick inserter to know what  to do when you click "browse all". and yes, let's try to enable this.
