### ISSUE TITLE
Gradient control should show a horizontal representation of vertical and angular gradients

### ISSUE THREAD

**Issue by properlypurple** [WordPress/gutenberg#23503]
**Describe the bug**
When there is a vertical or angular/oblique gradient defined in the theme, the gradient control shows the gradient as-is. It should show a horizontal representation of the gradient

**To reproduce**
1. Add this code to your theme
```
add_theme_support( 
	'editor-gradient-presets', 
	array(
		array(
		'name'     => __( 'Gradient', 'themeslug'  ),
		'gradient' => 'linear-gradient(to bottom, #000000 10%, #cccccc 90%)',
		'slug'     => 'new-gradient'
		)
	)
);
```

2. Edit a post/page, add a block that supports gradients
3. Select the above gradient in the color settings.
4. The gradient shows as vertical, while the color stops work as normal.

**Expected behavior**
The control should show a horizontal representation of the gradient instead.

**Screenshots**
![Screenshot_2020-06-26 Edit Post ‹ purple-seedling — WordPress(1)](https://user-images.githubusercontent.com/40858144/85823874-0b43df00-b79c-11ea-8939-ed37e4021e22.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.4

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
 - Version. 77.0.1

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this issue @properlypurple! It is now fixed.

**Comment by kathrynwp** [comment]
Looks like this issue was fixed in 2021 but the never closed, so am closing it now.
