### ISSUE TITLE
Displaying a Gutenberg Block in functions.php file

### ISSUE THREAD

**Issue by neerishc** [WordPress/gutenberg#23502]
Hello,
I have created a new customs tab in WooCommerce and now would like to add a Gutenberg Block to it. For instance, if I am having the new Customs Tab as "Shoe Size Chart" and have already created a Gutenberg Block with slug name footwear-size-chart, I would like to know how can I echo / render this in my theme's functions.php file?

**Comment by alexvornoffice** [comment]
Is this an issue/problem? or you are searching for support? Because here all issues should be bug related or giving ideas/feaure requests...

**Comment by enriquesanchez** [comment]
Hi @neerishc 

The Gutenberg GitHub repo is for work related to the development of the block editor. For support, please refer to the[ Gutenberg Help forums](https://wordpress.org/support/plugin/gutenberg/).
