### ISSUE TITLE
@wordpress/scripts package, source-map-loader: Code doesn't compile when .ts files in dependencies not included

### ISSUE THREAD

**Issue by leoloso** [WordPress/gutenberg#23513]
**Describe the bug**
When compiling a block using the `@wordpress/create-block` package with `npm start`,  and having [this dependency](https://www.npmjs.com/package/graphql-request), it throws an error:

```
WARNING in ./node_modules/graphql-language-service-parser/esm/CharacterStream.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/CharacterStream.ts': Error: Can't resolve '../src/CharacterStream.ts' in '.../node_modules/graphql-language-service-parser/esm'
 @ ./node_modules/graphql-language-service-parser/esm/index.js 1:0-63 1:0-63
 @ ./node_modules/codemirror-graphql/variables/mode.js
 @ ./node_modules/graphiql/dist/components/VariableEditor.js
 @ ./node_modules/graphiql/dist/components/GraphiQL.js
 @ ./node_modules/graphiql/dist/index.js
 @ ./src/EditBlock.js
 @ ./src/index.js
```

This happens because the TypeScript sources were not included in the dependency, so the `source-map-loader` fails. The same error may happen with other libraries too, and I found it documented in [this issue](https://github.com/angular-redux/store/issues/64).

The problem happens in [this piece of code](https://github.com/WordPress/gutenberg/blob/master/packages/scripts/config/webpack.config.js#L160):

```js
if ( ! isProduction ) {
	// WP_DEVTOOL global variable controls how source maps are generated.
	// See: https://webpack.js.org/configuration/devtool/#devtool.
	config.devtool = process.env.WP_DEVTOOL || 'source-map';
	config.module.rules.unshift( {
		test: /\.js$/,
		use: require.resolve( 'source-map-loader' ),
		enforce: 'pre',
	} );
}
```

And the solution is just to exclude this rule from the `node_modules` folder.

Currently, to solve this issue, I'm overriding the `webpack.config.js` file in my block, with the following code:

```js
const config = require( '@wordpress/scripts/config/webpack.config' );
const isProduction = process.env.NODE_ENV === 'production';

if ( ! isProduction ) {
	/**
	 * Because that rule was added using "unshift" (in file node_modules/@wordpress/scripts/config/webpack.config.js) then it's on the first position of the array
	 */
	config.module.rules[ 0 ].exclude = [ /node_modules/, /build/ ];
}

module.exports = config;
```

But it would be much better if the `exclude` property could already be set-up in the original code.

**To reproduce**
1. Include the `graphql-request` dependency on `package.json`
2. Run `npm start` (using `@wordpress/create-block`)

**Expected behavior**
The error should not happen

**Editor version (please complete the following information):**
- `@wordpress/scripts` package version 12.0.0

**Comment by gziolo** [comment]
> But it would be much better if the exclude property could already be set-up in the original code.

It looks like the issue is on the side of 3rd party libraries but since it’s source maps it might be a good idea to exclude `node_modules` from processing. @ocean90, what fo you think since you removed excludes for CSS file types earlier this week 😃

**Comment by gziolo** [comment]
Opened #23711 with the fix proposed.
