### ISSUE TITLE
Table can't change to edit visually after selecting Edit as HTML and clicking out of the table

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#23511]
**Describe the bug**
After selecting `Edit as HTML` in `Table` block and clicking outside, you can't see the button with the options if clicking back in.

This has a similar effect on `Buttons` block, that errors when clicking out of the block, after having selected `Edit as HTML`.

This probably has to do with blocks that utilize `RichText` inside and if that's the case more blocks are affected by this.

**To reproduce**
1. Go to a post/page
2. Add a `Table` block
3. Select `Edit as HTML`
4. See that the options block is visible
5. Click outside and then back in the `Table`
6. The options block is not there..

For the `Buttons` block just select `Edit as HTML` and click outside

**Expected behavior**
The options button after `Edit as HTML` should be visible in `Table`.
The `Buttons` block should not result in error.

**Screenshots**
![Screenshot(2)](https://user-images.githubusercontent.com/16275880/85849826-5833af80-b7b4-11ea-928b-91d5d0417219.png)

**Editor version (please complete the following information):**
- Gutenberg version [8.4]

**Desktop (please complete the following information):**
 - OS: [Linux Mint]
 - Browser [chrome, firefox]

**Comment by mcsf** [comment]
Thinking about the similarities with #24331, do you observe anything strange in the editor breadcrumbs as well?

**Comment by ntsekouras** [comment]
It seems to be for `Quote` block as well and probably others. I haven't tested them all.

> do you observe anything strange in the editor breadcrumbs as well?

Breadcrumb is wrong too.

**Comment by ellatrix** [comment]
@mcsf Yes, the breadcrumb for table disappears as well. It's as if you cannot select the block. Not sure why it works for e.g. a heading but not for a table. 🤔

**Comment by ellatrix** [comment]
I think I know why :) They're not light blocks.
