### ISSUE TITLE
Embedding Gists fails to display in WordPress editor, even in Preview, fail to publish - Gists Broken

### ISSUE THREAD

**Issue by brucedkyle** [WordPress/gutenberg#23519]
**Describe the bug**
Gists do now work as expected. I may be missing something but for older posts they work as expected.

**To reproduce**
Use WordPress.com
Upgrade to the paid plan
1. Write blog post using classic editor (afaik, block fails too)
2. Inset a single line with your gist

https://gist.github.com/brucedkyle/23ee35fae7bfbf3863d882e5b757ab18#file-new-managementgrouproot-ps1 

**Expected behavior**
The gist should appear:
- in the editor
- when clicking preview
- when published

**Screenshots**
![image](https://user-images.githubusercontent.com/1649513/85879267-e85efe00-b78e-11ea-827c-fdcec63b1889.png)

Click Preview -- Result

![image](https://user-images.githubusercontent.com/1649513/85879321-0167af00-b78f-11ea-8208-7530a0085b38.png)

NOTE: This worked for previous posts, although (separate bug) you cannot have multiple periods in the name of the gist.

**Editor version (please complete the following information):**
- WordPress version: 5.2.0
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [as far as I know it is the "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Edge, Chrome fails too.]
 - Version

**Comment by talldan** [comment]
Hi @brucedkyle, WordPress core, as in the open source version of WordPress, doesn't have any support for embedding gists.

There's an open ticket for adding backend support to WordPress for gists (https://core.trac.wordpress.org/ticket/41206), and a closed issue for a gist block (https://github.com/WordPress/gutenberg/issues/1567), which may be revisited if the backend ticket is solved.

If this was something that was working before, it may be that it was functionality added by a plugin. You also mentioned you're using a paid plan on WordPress.com, which is a commercial product developed by Automattic—it might be worth reaching out to WordPress.com support for help with this issue (https://wordpress.com/support/).

I'll close this ticket, as it looks like there's nothing we can do within this project to help you. Hopefully you'll be able to solve the issue through WordPress.com support.
