### ISSUE TITLE
Inserter scrolling issue

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#23529]
**Describe the bug**

Search bar becomes see through after scrolling down.

**To reproduce**
1. Go to main block inserter (plus in top toolbar)
2. Scroll down enough and observe transparent search area at the top

**Expected behavior**

**Screenshots**

![151841FF-229A-4AD2-8306-76DE6C655E18](https://user-images.githubusercontent.com/4710635/85920737-84176980-b876-11ea-9198-cf3396fed5a7.jpeg)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] plugin
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 8.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Safari 

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ellatrix** [comment]
Cc @youknowriad @jasmussen Since I think you worked on the new inserter

**Comment by youknowriad** [comment]
I think this was triggered by the fact that the inserter uses Sticky positioning now for the tabs and search input.  
The issue though is that we can't come back to flex alignment as it was not possible to have both aa good popover implementation while relying on it. (It forces us to define the height of the popover  and  we just want it to be equal to content's height)  so I think we should try to fix this while retaining the sticky positioning.

**Comment by youknowriad** [comment]
Also, this works properly on Chrome.

**Comment by bph** [comment]
I noted something similar. The sibling inserter is cut off on the top, and covers partially the search field. 
<img width="445" alt="Screen Shot 2020-06-28 at 7 34 20 PM" src="https://user-images.githubusercontent.com/39980/86006621-3de01880-b9e4-11ea-8b5d-31f059e2f0f6.png">

OS: Mac 10.14.6
Browser: Chrome
Version: 83.0.4103.11

WP 5.4.2
Gutenberg 8.4

**Comment by ItsJonQ** [comment]
> I think this was triggered by the fact that the inserter uses Sticky positioning now for the tabs and search input

@youknowriad Ah.. that's probably it. I've experienced unexpected `position: sticky` issues on iOS previously - but it worked fine on Desktop browsers (and Android)

**Comment by youknowriad** [comment]
I'm not able to reproduce this anymore, not sure if it's because of Safari upgrade or a fix in the styles.
