### ISSUE TITLE
npm ERR! Unsupported URL Type: npm:wp-prettier@1.19.1

### ISSUE THREAD

**Issue by solvewp** [WordPress/gutenberg#23531]
Getting this error message with @wordpress/scripts version 7.0.0 and above
Though working with @wordpress/scripts version 6.2.0 and below

My pakage.json contains
This version doesn't show that error mentioned below when trying to install by command "npm install @wordpress/scripts --save-dev"
{
  "name": "react-app",
  "version": "1.1.0",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@wordpress/scripts": "^6.2.0",
    "@babel/core": "^7.10.3",
    "@babel/preset-env": "^7.10.3",
    "babel-loader": "^8.1.0"
  },

But this version won't work, will show that error message below. I have tried all @wordpress/scripts version from 7.0.0 to 12.0.0
The only version below 7.0.0 seems works for me.
{
  "name": "react-app",
  "version": "1.1.0",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@wordpress/scripts": "^7.0.0",
    "@babel/core": "^7.10.3",
    "@babel/preset-env": "^7.10.3",
    "babel-loader": "^8.1.0"
  },

Error message:

 npm install @wordpress/scripts --save-dev
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @wordpress/scripts@7.2.0: wanted: {"node":">=10","npm":">=6.9"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @wordpress/scripts@7.2.0: wanted: {"node":">=10","npm":">=6.9"} (current: {"node":"8.10.0",loadDep:webpack-livereloa ▀ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine npm-package-json-lint@4.6.0: wanted: {"node":">=8.0.0","npm":">=6.0.0"} (current: {"node":"loadDep:webpack-livereloa ▐ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:webpack-livereloa ▄ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @wordpress/prettier-config@0.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":loadDep:webpack-livereloa ▄ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:webpack-livereloa ▀ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Linux 4.15.0-108-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "@wordpress/scripts" "--save-dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! Unsupported URL Type: npm:wp-prettier@1.19.1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/public_html/wp-content/themes/twentytwenty/npm-debug.log

**Comment by ocean90** [comment]
Hello @solvewp, thanks for the report. You can see the actual error in this line:

> WARN engine @wordpress/scripts@7.2.0: wanted: {"node":">=10","npm":">=6.9"} (current: {"node":"8.10.0","npm":"3.5.2"})

This means that you node environment is too old. Please update node to at least v10 and npm to v6.9.
