### ISSUE TITLE
Allow section wrapper blocks to specify open and closing HTML tags

### ISSUE THREAD

**Issue by glenviewjeff** [WordPress/gutenberg#23541]
To solve the problem of being unable to surround multiple blocks by HTML, for instance a hyperlink anchor, add opening and closing markup tags for section blocks. It's unclear if [this is the same request](https://github.com/WordPress/gutenberg/issues/20376).

What spurred this is receiving a mobile usability warning about hyperlinks being too close together from Google Search Console. I have multiple hyperlinks to the same destination in a group of blocks.

**Comment by talldan** [comment]
@glenviewjeff Something similar was discussed on https://github.com/WordPress/gutenberg/issues/20997, with the idea that the group block could offer more semantic variations, like `section` or `footer`. That was also explored in a pull request - https://github.com/WordPress/gutenberg/pull/20218.

I don't think it'd work for your use case, as the group block doesn't have any link/href functionality.

https://github.com/WordPress/gutenberg/issues/15794 also seems somewhat related, as that requests a way to wrap arbitrary HTML around blocks.

**Comment by glenviewjeff** [comment]
I'm able to work around this by surrounding the blocks I want hrefs applied to with [custom HTML blocks](https://gogutenberg.com/blocks/custom-html/), but when I return to edit the page, Gutenberg complains that "this block contains unexpected or invalid content" because the tags aren't closed. 

![image](https://user-images.githubusercontent.com/334914/86081083-12981080-ba5a-11ea-814b-c647a503f67c.png)

**Comment by talldan** [comment]
Yep, that's the same issue as #15794.

As there are two other open issues covering the same topic as this one, I'll close this as a duplicate.
