### ISSUE TITLE
Support youtube-nocookies.com URL in video embedd block

### ISSUE THREAD

**Issue by stkjj** [WordPress/gutenberg#23549]
**Is your feature request related to a problem? Please describe.**
to overcome privacy unfriendly tracking when embedding youtube videos youtube itself offers a solution by using https://youtube-nocookies.com/ as a privacy enhanced way of embedding videos. 

see: [https://dri.es/how-to-remove-youtube-tracking](https://dri.es/how-to-remove-youtube-tracking)

ATM when entering the modified URL the Gutenberg block just offers to convert it to a link, rather than embedding the video.

**Describe the solution you'd like**
the respective Gutenberg block should allow both URL as valid entries for an embedd of videos.

**Describe alternatives you've considered**
To embedd youtube videos in a privacy friendly way I'm only aware of plugin solutions. Some of which paid like Borlabs Cookie, some not even listed on the WordPress repo like [https://github.com/michaelzangl/wp-video-embed-privacy](https://github.com/michaelzangl/wp-video-embed-privacy)

**Comment by Soean** [comment]
We had a ticket #12701 about this feature and closed it in favor of the core ticket https://core.trac.wordpress.org/ticket/44610

**Comment by skorasaurus** [comment]
Closing this ticket since it's already being tracked above at the core URL ^
