### ISSUE TITLE
FSE: When Creating Templates/Template Parts Rename Document in Inspector Tools

### ISSUE THREAD

**Issue by itsjusteileen** [WordPress/gutenberg#23560]
**Current Functionality**
When creating Templates and Template Parts in the new Full Site Editing experience, the post editor does not indicate to the user that a template is being created, the editing experience looks like a regular post.

<img width="1437" alt="Screen Shot 2020-06-29 at 8 43 24 AM" src="https://user-images.githubusercontent.com/6146600/86007532-88ae6000-b9e5-11ea-9618-79a6145d6db1.png">

**Describe the solution**
To make it clearer for the user, the editor window should indicate through text and/or visual UI elements that the user is working on a template or template part and not a regular post.

**Describe alternatives**

1. Text can be changed in the Inspector Controls, changing `Document` to `Template`.
2. `Document` can be changed (or added) to `Template` in the breadcrumb.

![Screen Shot 2020-06-27 at 7 10 13 AM](https://user-images.githubusercontent.com/6146600/86009978-cfea2000-b9e8-11ea-91fd-79f1ec56c77a.jpg)

Changing the tab text in the Inspector Controls provides the ability to add additional block template functionality to the control area like locking templates or template parts mentioned in [#23532](https://github.com/WordPress/gutenberg/issues/23532)

**Comment by paaljoachim** [comment]
@jameskoster and @aristath 
Is this issue still valid?

**Comment by jameskoster** [comment]
Yes, imo. I opened https://github.com/WordPress/gutenberg/issues/27470 recently which I now realise is a duplicate. I'll close that out.

**Comment by carolinan** [comment]
Why are Templates and Template Parts created from the Appearance sub menus created an edited in the post editor in the first place, and not the site editor?

**Comment by skorasaurus** [comment]
With the changes to the template editor, the first issue mention has been resolved; 
; the 2nd part of this issue: changing the in the lower left hand corner, is still valid in gutenberg 12.4
