### ISSUE TITLE
Title block is arrow key trap

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2357]
In version 0.7.1, navigating around blocks with the arrow keys works pretty alright, but if you press the up arrow enough to navigate through the content up into the title block, you cannot leave that block with the down arrow.

## Steps to reproduce:
- Create a post with a title and at least one paragraph block
- Focus on the paragraph and press the up arrow until you reach the title
- Press the down arrow and get no further than the end of the title block

When testing with the demo post, I noticed that I cannot even reach the title, because the arrow keys cannot get past the Read More block.

**Comment by karmatosed** [comment]
I am no longer getting this issue. Are you still? For now closing but if you are we can reopen.

**Comment by hedgefield** [comment]
Yep, fixed :)
