### ISSUE TITLE
[Mobile] Gallery image captions don't allow newlines when pressing [Enter]

### ISSUE THREAD

**Issue by mkevins** [WordPress/gutenberg#23575]
**Describe the bug**
On the mobile editor, gallery image captions do not allow newlines to be entered using the [Enter] key (note: they can still be pasted in). On web, pressing [Enter] in a gallery image caption creates a newline.

**To reproduce**
1. Create a gallery
2. Tap an image caption
3. Write some text and press [Enter]

**Expected behavior**
A newline should appear within the caption

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10

This is related to this issue: https://github.com/WordPress/gutenberg/issues/23574 but is specific to gallery image captions, and in this case, the web behavior is working as expected, and the mobile behavior deviates.

**Comment by pinarol** [comment]
Let's first make sure if this is a bug or this was intentionally made this way to workaround some issues related with RichText newline behavior.

**Comment by antonis** [comment]
[After investigating this issue I'm closing it since a universal solution with reasonable effort is not possible at this point.](https://github.com/WordPress/gutenberg/pull/25337#issuecomment-693341277)
