### ISSUE TITLE
Mark invalid menu items in Navigation editor and block

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#23573]
### Is your feature request related to a problem? Please describe.

In the `nav-menus.php` admin section, invalid menu items are flagged with a red background and an error message appears:

<img width="766" alt="Screen Shot 2020-06-30 at 1 29 43 pm" src="https://user-images.githubusercontent.com/8096000/86087875-98fb3380-bae8-11ea-958c-4e40440bbe48.png">

The Navigation screen should also have something like this.

(An invalid menu item can be created by deleting the page a menu item links to.)

### Describe the solution you'd like

Show an error message in the Navigation screen when there are invalid items, and indicate within the menu which items are invalid.

Whatever way we find of showing invalid menu items should perhaps also be applied in the Navigation block itself.

----

### Details from #34818

A nav menu_item object returned from calling [wp_setup_nav_menu_item](https://developer.wordpress.org/reference/functions/wp_setup_nav_menu_item/). This object contains a property called `_invalid`. It is used for the following. 

> Whether the menu item represents an object that no longer exists.

A menu item can be invalid for the following reasons. 
- Linked post is post status trash
- Linked term does not exist
- post_type_archive post type doesn't exist.
- Taxonomy archive, taxonomy doesn't exist.

The new navigation editor should handle this case. See the existing menu screens. 

<img width="468" alt="Screenshot 2021-09-14 at 18 29 03" src="https://user-images.githubusercontent.com/237508/133305634-8b46a5d2-93c9-4f25-a1b5-1161253a7c8e.png">
<img width="323" alt="Screenshot 2021-09-14 at 18 29 22" src="https://user-images.githubusercontent.com/237508/133305663-ba3687f5-8029-49db-bec0-999da860674a.png">

Related: https://github.com/WordPress/gutenberg/pull/34670

**Comment by enriquesanchez** [comment]
I agree these error messages should also appear on the Navigation screen. As for indicating an invalid block, we currently have the invalid content status for blocks, but I'm not sure it'll serve the same purpose here.

<img width="613" alt="Screen Shot 2020-08-18 at 11 15 50" src="https://user-images.githubusercontent.com/3276087/90538585-59de7b80-e144-11ea-9ae3-cdac2101b06a.png">

**Comment by enriquesanchez** [comment]
Here's an idea of how these error messages could look on the new navigation screen.

Given how small of a space we have for child items of the navigation block, I thought about adding a distinct error highlight that lets you make a correlation between the error notice and the specific block. The errored block is also highlighted in the navigation list on the right.

<img width="1148" alt="Layout1" src="https://user-images.githubusercontent.com/3276087/90658353-1863d400-e209-11ea-85e5-7410a384562f.png">

Once you select the errored block, the toolbar can describe the error in more detail and offer a way to fix it:

<img width="1148" alt="Layout2" src="https://user-images.githubusercontent.com/3276087/90658576-595be880-e209-11ea-994d-6ab841538833.png">

---

I also thought about how we can avoid getting to this state in the first place. I wonder if I should be able to delete a page without seeing some sort of warning that the page I'm about to delete is being used in my navigation?

Maybe if I really wanted to delete it, I could right then and there decide to also remove it from the navigation?

@shaunandrews Since you've been working on navigation a lot lately, I'd love to hear what you think.

**Comment by jasmussen** [comment]
Does the presence of a "Page List" block change the equation here?

The way I see it, the Page List is the solution to menu items staying in sync. As soon as the Page List block is converted into a list of individual menu items, they are essentially "just" normal hyperlinks. It would be nice with a "dead link checker" tool for such links, but it seems less urgent once the Page List block keeps things in sync automatically.

**Comment by tellthemachines** [comment]
Posts can also be deleted though, or categories. If we're aiming for feature parity with `nav-menus.php` we still need this feature.

**Comment by jasmussen** [comment]
A setup state recently landed for menu items:

![setup state](https://user-images.githubusercontent.com/1204802/110104007-e9790e00-7da6-11eb-9a2b-377fa5094aac.gif)

This setup state essentially handles "incomplete items". Currently, items without a link. 

But we are discussing in https://github.com/WordPress/gutenberg/issues/29417#issuecomment-790816305 whether it could also be used to handle draft pages. 

It seems like the same pattern could be extended to invalid items:

<img width="876" alt="Screenshot 2021-03-05 at 11 34 57" src="https://user-images.githubusercontent.com/1204802/110104207-26450500-7da7-11eb-8f13-6a417b2e4f6b.png">

The genesis of the idea was #28440 by @shaunandrews. In all cases, the key behavior, outside of the block-UI-like button, is that you cannot edit the title of the menu item until the item has been handled. That affords us the entire clickable area to invoke a popover where you can publish/repair/fix the menu item. I would encourage looking at Shaun's mockups in 28440, as they will very probably scale well to this.

What do you think?

**Comment by shaunandrews** [comment]
<img width="166" alt="image" src="https://user-images.githubusercontent.com/191598/113767279-7daefb80-96ec-11eb-97bd-8d0ef49401ff.png">

Perfect.

**Comment by getdave** [comment]
<img width="1278" alt="Screen Shot 2021-08-23 at 11 15 29" src="https://user-images.githubusercontent.com/444434/130431167-8065db35-df02-47e3-8487-65f6db70e29c.png">

Just noting that this is still not handled by the Nav Editor screen. Added to the tracking issue https://github.com/WordPress/gutenberg/issues/29102.

**Comment by getdave** [comment]
@jasmussen Is this still something we are going pursue?

**Comment by vcanales** [comment]
@getdave @jasmussen If so, [this PR](https://github.com/WordPress/gutenberg/pull/31716) is ready for review again. It has an approval, but it was granted way too long ago.

**Comment by tellthemachines** [comment]
Yes, this needs to be done for feature parity with classic menus, and for better UX.

**Comment by getdave** [comment]
Ok it's added to [the new tracking issue](https://github.com/WordPress/gutenberg/issues/38275).

**Comment by vcanales** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/31716
