### ISSUE TITLE
Handle heavily nested items in the Nav Editor screen

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23583]
We have a problem on the navigation screen when menus are deeply nested: the fixed size of the navigator will lead the nested items more and more to the right until they overflow. 

So far we've had some ideas like increasing the width of the navigator (to the detriment of the navigation block) or to enable/use horizontal scrolling inside the navigator (not a very popular pattern for understandable reasons).

A new approach that surfaced in our discussions is to add the option to drill down menu items so that we could limit the depth available at any moment in the navigator.

Would it be interesting to explore this either as an implementation experiment or as a mock-up?

This would be complementary to the expand and collapse leaves of parent branches (a feature to be implemented) as an option to make nesting manageable, or it could just as well replace the expand and collapse feature as the better way to handle nesting in horizontally constrained spaces.

cc @shaunandrews

**Comment by shaunandrews** [comment]
I also posted this in the larger design issue (#24029): Here's the design for how to handle deeply nested items in the list view:

![deeply-nested-list-view](https://user-images.githubusercontent.com/191598/90281223-4082ba00-de3a-11ea-8eb4-b4d7ec7796d6.gif)

**Comment by getdave** [comment]
Noting here for the purposes of prioritisation that the existing Navigation screen seems to have **a hard limit of 11 levels of nesting**. After that you cannot nest further.

https://user-images.githubusercontent.com/444434/130432001-ec2cbdc0-9b10-45aa-9bcd-719aa227bcc8.mp4

Now the new Navigation screen is in vertical orientation it _does_ in fact handle nesting but there are UI/UX refinements needed.

<img width="1117" alt="Screen Shot 2021-08-23 at 11 23 56" src="https://user-images.githubusercontent.com/444434/130432441-e9d1d3b3-3f1b-4cf5-afb3-01a12e68cb74.png">

Therefore @draganescu @javierarce  would you object to redefining this Issue to track the need to implement these refinements?

Or perhaps we can close this one out and create a new Issue to track the refinements?

**Comment by getdave** [comment]
Turns out if you know about the "list view" feature of the Nav block then you can see all nested levels:

https://user-images.githubusercontent.com/444434/130454977-a95e7d5b-9160-4a8c-b54e-1b17a8c93127.mov

<img width="1278" alt="Screen Shot 2021-08-23 at 14 23 17" src="https://user-images.githubusercontent.com/444434/130454830-ef7489a1-d6cd-403a-ba3d-91fe080b9303.png">

This makes me think the Issue is now "Make the list view more obvious" rather than solving the nesting issue.

I could be wrong - what say you @draganescu and @javierarce?

**Comment by javierarce** [comment]
> This makes me think the Issue is now "Make the list view more obvious" rather than solving the nesting issue.

As a big proponent of the top bar, I'd say that that could be the ideal place to put that icon (so +1 to your last suggestion). 

And I think we could address the "UI/UX refinements" of the menu items you mentioned [here](https://github.com/WordPress/gutenberg/issues/23583#issuecomment-903639516) in the issue https://github.com/WordPress/gutenberg/issues/34035

**Comment by draganescu** [comment]
I think we should close this issue as we'll just inherit what the listview supports.
