### ISSUE TITLE
Some Info about what many of Us will need to remove from website owners eyes

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2358]
All this is welcome by Admins, developers. My opinion anyway.

- Read More block
- Verse block (button !?)
- Preformatted button
- Heading button, options
- Image captions
- Button block
- Majority of embeds options
- Code block
- Gallery - Crop images (off) option
- Table block
- Custom HTML block
- All "widgets" blocks
- Excerpt textarea field
- Table of content tab
- Blocks descriptions
- Stupid Drop Cap option
- Additional CSS class option
- Gist block
- Shortcode block (Yes, we mortals do not give it to website owners, but we pesonally use it.)
- Columns block
- OpenGraph block
- Logo block
- Social Links block
- Custom Menu block (why on earth !?)
- Archive block
- Calendar block
- Chat block
- Remove add new category option
- Option to chose Post/Pages in link inserter
- Future configuration of "Metaboxes"
- Some code acrobatic to move featured image from content block to a "Metabox"
- Subtitle block
- Disable support for images in Lists
- Option to drag & drop images from PC right inside content area (Already now is very difficult to explain to them why gallery does not work, when they try to make it by Post images only. Over and over again.)
- Author Bio block (I know I asked for it. But out of 10 websites it will be used on max 2, theoretically.)
- Block: Bookmark/HTML Anchor
- Cover Image
- Snippets to decide what buttons are visible, and where
- Many others right now in current state. Difficult to orientate in this jungle of promises, wishes, etc...

- Multiply all this and expect it be more difficult when deciding how will users use Gutenberg inside bbPress and front-end comments.

Those native blocks will probably be disabled by single PHP snippet, and array. But still other work is huge.
I believe Gutenberg is yet not even 30% finished, as you Gutenberg coders "imagine", "hope" and "believe".

**Comment by karmatosed** [comment]
Thank you for your feedback. I feel that this is really a personal matter as to what you show or don't. For now, this is feedback but it's not an actionable issue, I am therefore closing it as we move to focus on things that have action.

Further down the road, I could see a reality where a snippet/plugin is created to turn on/off blocks. I do not personally feel that should be in v1 of Gutenberg in core. It's something to explore after merge.
