### ISSUE TITLE
Drag and drop for Navigation block on navigation screen

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23581]
We need to be able to use drag and drop on the navigation block that we use on the navigation screen to reorder items. However the challenge is that on the navigation screen the toolbar of the block is always fixed, so currently there isn't anything to drag from.

So far we've had three ideas to help this work:
 
- [x] Enable hovered when dragging as a state that shows sub-menus
- [x] Add the dragging chip functionality to the toolbar of the navigation item
- [ ] Bring in the press and [drag exploration](https://github.com/WordPress/gutenberg/pull/23497)

**Comment by draganescu** [comment]
This issue actually covers two problems:

- Any block that has that `__experimentalCaptureToolbars` setting has it's drag handle out of the visual context of the block that will be dragged. One result of this is the chip is offset.

- There is no clear way on how to drop something in an area that is hidden. This seems to require a separate issue as it looks like a bigger standalone problem to be solved for all editor instances.

**Comment by talldan** [comment]
#24707 fixes the offset of the draggable chip

**Comment by draganescu** [comment]
This seems to have been fixed with the addition of the drag handle to the Link block's toolbar
