### ISSUE TITLE
How do I add a link to flickr images within a wordpress gallery?

### ISSUE THREAD

**Issue by tijnsch** [WordPress/gutenberg#23597]
Hi,

I'm trying to make a gallery with externally hosted images using html code. So far, it is working with random images from google, but when I try to instert images from my flickr account, it isn't working anymore. Is there a way to make this work? I added an attachment with the code I'm using.
[code.txt](https://github.com/WordPress/gutenberg/files/4854768/code.txt)

Thanks!
Tijn

**Comment by talldan** [comment]
Hi @tijnsch, this github repo is generally for issues relating to the development of the block editor and associated code (bug reports, enhancements). 

Your post sounds more like a support request. I'd recommend reaching out on the WordPress forums (https://wordpress.org/support/).
