### ISSUE TITLE
Block preview doesn't go away when searching for blocks

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#23596]
**Describe the bug**
When searching for blocks to use (like from the block directory), hovering over a block button shows a preview. The preview then stays visible even if the block is filtered out of the list (unless another block is hovered over). If no blocks are found, there's no way to reset the hovered item, so the preview can't be closed.

**To reproduce**
1. Open the main block inserter +
2. Click into the search field
3. Hover over a block icon
4. See the preview
5. Start searching, the preview stays around, or maybe switches to another block preview
6. If no installed blocks are found, the preview never goes away
7. Same happens even if blocks are found in the block directory, which might be confused for a preview of the block directory result

**Expected behavior**
When the selected block is filtered out, the preview should disappear

**Screenshots**
Once i'm in the "no blocks found" state, there's no way to remove the preview - no matter where I click.

![](https://user-images.githubusercontent.com/541093/86183289-b1c31380-baff-11ea-99af-f32e62807be4.gif)

Recorded on 5.5-alpha + GB master; also happens on WP 5.4 & GB 8.4.

**Comment by ntsekouras** [comment]
Hey @ryelle. Thanks for reporting this!
