### ISSUE TITLE
Gallery Block > Media Library > This Post not Selectable

### ISSUE THREAD

**Issue by marcuswisecaesar** [WordPress/gutenberg#23594]
**Describe the bug**
User is trying to edit a gallery on an old post.
When they go to Gallery Block > Media Library they see a tab called `this post` but it's greyed out.
This means they have to scroll through all the images to find what they need.

**To reproduce**
1. Go to a post that has a gallery block with images in it and prepare to edit the gallery in the Block Editor. 
2. Click on the gallery block to select it.
3. Click on Media library to View images in the Media Library
4. Now try to discover what media are already being used on this post by clicking 'This Post' and you will most likely not be able to as the `This Post` option is greyed out an unselectable.

**Expected behavior**
When clicking Gallery Block > Media Library > This Post, the images selected in this post should be brought to the top or shown exclusively. 

**Screenshots**
![screenshot](https://woothemes.zendesk.com/attachments/token/XjycuTgQ6E4Be4gPDv6WjoNX0/?name=Screen+Shot+2020-06-30+at+11.44.43.png)
[Direct Link](https://woothemes.zendesk.com/attachments/token/3kIMsdcQe8iZnqV7vCT0j0C5b/?name=Screen_Shot_2020-06-30_at_11.44.43.png)

**Editor version (please complete the following information):**
Gutenberg: 8.3.0
CoBlocks: 1.23.0
wpcom-FSE: 140051995

**Desktop (please complete the following information):**
 - OS: OSX 
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by marcuswisecaesar** [comment]
zd-3100883

**Comment by talldan** [comment]
Hi @marcuswisecaesar The media library in the screenshot is provided by WordPress.com rather than Gutenberg, so I think this issue has been created in the wrong place. 

I note that you're Automattic staff, so I'd recommend reaching out internally to find the best place to raise this issue—possibly https://github.com/Automattic/wp-calypso, but I'm not completely sure.
