### ISSUE TITLE
Make wrapping tables in figure tags optional

### ISSUE THREAD

**Issue by SeanMcMillan** [WordPress/gutenberg#23617]
**Is your feature request related to a problem? Please describe.**
On iOS 12 (the last iOS for some iPhones,) tables wrapped in figure tags can't be scrolled. 

**Describe the solution you'd like**
I'd like to be able to choose to include the figure tag or not. Probably a toggle in the "Table settings" area would be appropriate

**Describe alternatives you've considered**
* One workaround would be to not care about users on older iOS versions -- this is fixed in iOS 13+.
* Another option is to do some kind of post-edit pass to remove the figure tag.
* Another option is to make a copy of the table block, remove the figure tag and tell my copy editors to use that one.
* In the other direction, maybe the choice of wrapping things in figure tags should be made at a higher level so it's optional for images and such as well.

**Extra Information**
It looks like the wrapper was added and changed from div to figure in this PR last year: https://github.com/WordPress/gutenberg/pull/16324#discussion_r300501594 . That comment suggests that it allows for a caption, but table tags have a caption element as an option anyway.

I need something for my iOS users on older phones, so I intend to make a PR for this. The guidelines suggest that it's best to start with an issue so people can give early feedback. Consider this an intent to implement, I guess.

**Comment by ellatrix** [comment]
It sounds like we should try to find a workaround for the iOS issue rather than add extra options. If it’s an older iOS version, does it still make sense to fix? I’m not convinced.

**Comment by SeanMcMillan** [comment]
Our team hasn't found a workaround for this case yet. There's no obvious CSS we could add or anything like that. (We certainly would have gone there first!)

It looks like iPhone models before the 6s can't update past iOS 12, and I know we have customers that are in that position. It's like IE8 all over again. (Well, not as bad as that.)

If there's a better way to fix this for the unupdatable phones, I'd love to hear about it!

**Comment by jordesign** [comment]
Hi @SeanMcMillan - just looping back to this older issue to see if it is still not possible to scroll tables on older devices?

**Comment by jordesign** [comment]
With no further comments or movement on this, I will close the issue.

If it is still a problem - a new issue can be opened with updated details on how to reproduce.
