### ISSUE TITLE
Inserter button can be unclickable

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#23629]
**Describe the bug**

The inserter button that appears between two blocks can be unclickable when the current focus is on the second block.

**To reproduce**

1. (Optional) Select "Top toolbar" mode so the inline toolbar doesn't get in your way.
2. Make two paragraphs, and click in the second paragraph.
3. Hover over the space between the two paragraphs.
4. The inserter button appears but is unclickable.

**Expected behavior**

The inserter button is clickable when it is visible.

**Screenshots**

<img src="https://user-images.githubusercontent.com/555336/86295315-41b4aa80-bc31-11ea-8145-ddda88018426.gif" alt="Unclickable inserter button" width="400">

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Gutenberg version: Reproduced on 8.3.0 and 8.4.0
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome 83.0.4103.97, Firefox 77.0.1

**Additional context**

I suspect this has something to do with the `is-inserter-hidden` class being added when it shouldn't be.

https://github.com/WordPress/gutenberg/blob/1bec21feb1ba8110fdd11b01c84dc2a3849884a1/packages/block-editor/src/components/block-list/insertion-point.js#L144-L147

https://github.com/WordPress/gutenberg/blob/c2c5aba6a0f31ff8593ac3e705fa11ea7bfc608b/packages/block-editor/src/components/block-list/style.scss#L403-L407

**Comment by oxyc** [comment]
I can reproduce in master and can confirm it's the `.is-inserter-hidden` class that's preventing the inserter from being clicked.

**Comment by oxyc** [comment]
Dug around some more and found it's actually supposed to be hidden https://github.com/WordPress/gutenberg/pull/19719. Not sure if this took into account using the top toolbar though. 

Currently the `opacity: 0;` is not respected because it gets animated to `1` at

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L443:L463

**Comment by sgomes** [comment]
Note that this can also happen when the second block is a classic block. In that situation, and if the classic block has the input focus, the block inserter won't do anything on click. If the non-classic block (such as a paragraph) has the focus, however, the button is clickable.

**Comment by mirka** [comment]
Not sure since which version exactly, but as of Gutenberg 9.0 this issue doesn't occur anymore.
