### ISSUE TITLE
Cannot copy over multiple blocks (Safari) Format is not copied when pasting (Chrome)／複数のブロックを跨いだコピーが出来ない（Safari）貼り付け時に書式がコピーされない（Chrome）

### ISSUE THREAD

**Issue by danyanjp** [WordPress/gutenberg#23644]
**Describe the bug**

Cannot copy multiple blocks in Safari on Mac.
Saving style (saving format) is not reflected when trying to paste multiple blocks in Chrome

MacのSafariで複数のブロックをコピーしようとするとできない。
Chromeでは複数のブロックをペーストしようとするとスタイルの保存（書式の保存）が反映されない

**To reproduce**
1. Open post page　投稿ページを開く
2. Make multiple blocks and copy　複数のブロックをしてしてコピー
3. An error sound (Beep) is heard and it is not copied エラー音(Beep)が出てコピーされない
**Expected behavior**

Can't copy multiple blocks
複数のブロックをしてコピーが出来ない

Cannot paste using style when using latest Chrome
最新のChromeを使用するとスタイル（書式）を使用してのペーストができない

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g:5.4.2–ja]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g:default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. macOS10.15.5]
 - Browser [e.g. chrome 83.0.4103.116（Official Build）, safari 13.1.1 (15609.2.9.1.2)]

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by kathrynwp** [comment]
It should now be possible to copy multiple blocks (formatted or not) at once.

I just tested in Chrome 103.0.5060.134 and it works as expected.

I'll close this report as fixed, but if you're still experience any issues, please add a comment with your steps to replicate and I'll be glad to have another look.
