### ISSUE TITLE
How to get the parent of the post being edited

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#23658]
I need to get the parent of the custom post type being edited in Gutenberg. I use the `post_parent` property to store the id of another related custom post type. Can the `getEditedPostAttribute` selector be used for this? Is the following snippet of code valid?

`select( 'core/editor' ).getEditedPostAttribute( 'parent' );`

Or is there a specific selector to retrieve the parent of a post? For some reason, when I call this selector I get an `undefined` value even though the `post_parent` property is set. (A custom meta box in the classic editor shows it correctly).

Thanks in advance

**Comment by mrleemon** [comment]
Apparently, if I set the `hierarchical` property in the custom post type to true, the selector works. Is this by design? Currently, many people use the `post_parent` property to create 1-to-n relationships between post types, and this quirk complicates things for us to adapt our plugins to Gutenberg (we have to use a custom meta field to store this data, instead).

Any solutions?

**Comment by TimothyBJacobs** [comment]
The REST API does not expose the `parent` property of a post unless the post type is hierarchical. That is by design, and as far as I know the same for the Classic Editor interface.

What is the issue with marking your post type as hierarchical?

**Comment by mrleemon** [comment]
> What is the issue with marking your post type as hierarchical?

Because the post type is not hierarchical. I just use the post parent to create a relationship with a different post type. An example: a Student post type is connected to a Class post type.

Anyways, I managed to expose the `parent` property using:

```
    function my_rest_api_init( $schema ) {
        register_rest_field( 'my_post_type', 'parent',
            array(
                'schema' => array(
                    'description' => __( 'The ID for the parent of the object.', 'rather-simple-relationships' ),
                    'type'        => 'integer',
                    'context'     => array( 'view', 'edit' ),
                )
            )
        );
    }
    add_action( 'rest_api_init', 'my_rest_api_init' );
```
