### ISSUE TITLE
Google docs don't embed

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#23653]
**Describe the bug**
URL: 1001albumsthendeath.com

PROBLEM:
User is trying to embed a google sheet but it doesn't work following the support docs

WHAT I TRIED
* They are using the steps here - https://wordpress.com/support/google-docs/#sheets
* They generated the following code

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQS29iH9lvGK0bueLkWSIf1lo_sO3D0geUawQMlCdjr1HUxv0HPDy5XasmQgx0F1aFv84PSb3hZWwoM/pubhtml?gid=1029332740&single=true&widget=true&headers=false"></iframe>

* Our docs say paste this in and it will embed but all it does is shows the code
* I did wonder about it being an iframe and this being on a personal plan but there is nothing in the support doc about plan limitations for iframes with Google docs
* Tried a classic block and pasted in the iframe code. This shows a form but to the hard left of the screen so not within the design of the page - https://1001albumsthendeath.com/the-league-table/

**Expected behavior**
The embed to work as per the support docs

**Comment by talldan** [comment]
@rickmgithub As far as I can tell, the open source version of WordPress doesn't support embedding google docs. This sounds like a WordPress.com specific issues.
