### ISSUE TITLE
Convert to blocks loses info about audio media

### ISSUE THREAD

**Issue by bobeaston** [WordPress/gutenberg#23664]
**Describe the bug**
Original page uses shortcode audio format:
`<p>[audio mp3="https://www.evaeaston.com/wp-content/uploads/th-vl-end-4-10.mp3"][/audio]</p>`

Convert to blocks produces an empty audio media block asking for information that was within the original code.

**Screenshots**
![classic](https://user-images.githubusercontent.com/61635317/86421155-f0470280-bca6-11ea-93b2-3df2e8add20b.jpg)
![html](https://user-images.githubusercontent.com/61635317/86421177-fe951e80-bca6-11ea-9581-0d789874d493.jpg)
![block](https://user-images.githubusercontent.com/61635317/86421183-05239600-bca7-11ea-9ecf-05725373f8c2.jpg)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, Native block editor

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Browser: Brave
 - Version:Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by getdave** [comment]
I tested this and can confirm the error is still occurring on WP 5.6 with the latest Gutenberg `Version 8.9.1`.

To replicate:

* Add new Post.
* Insert Classic Block.
* Paste in shortcode `[audio mp3="https://www.evaeaston.com/wp-content/uploads/th-vl-end-4-10.mp3"][/audio]`
* Validate Media will play in Editor.
* Select Classic Block and click "Convert to Blocks" on block toolbar.
* Classic Block is converted into an Audio Block with none of the original information from the shortcode.

**Comment by bobeaston** [comment]
THANKS Dave.
