### ISSUE TITLE
RichText "AllowedFormats" not working for links

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#23660]
**Describe the bug**
When using a custom block that has `allowedFormats={ [ 'core/bold', 'core/link', 'core/italic', 'core/strikethrough', 'core/text-color' ] }` the one for core/link does not show up.

**To reproduce**

1. Make a custom block using RichText
2. Set allowed formats to include 'core/link'
3. Add the block
4. Check the toolbar -- no links

**Expected behavior**
Links should remain a functional item

**Screenshots**

![Screen Shot 2020-07-02 at 1 53 10 PM](https://user-images.githubusercontent.com/807903/86408199-62015b00-bc6b-11ea-98d6-ddda5dbef83a.jpg)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Both 
- If the Gutenberg plugin is installed, which version is it? 8.4.0

**Comment by ocean90** [comment]
@Ipstenu Do you have Yoast SEO active on the site? See the linked issue or https://github.com/Yoast/wordpress-seo/pull/15617.

**Comment by Ipstenu** [comment]
Oh yeah that'd be it. That sucks. It broke my plugin and there's really no way for me to check "If you have Yoast SEO..." and call a different JS or anything :(

I can put in `yoast-seo/link` but now their plan is to take-over the link component and that sounds like it would really mess with people who have a plugin break on what appears to be a core component without an easy way to figure out where the code wasn't called from

**Comment by jdevalk** [comment]
@Ipstenu I completely agree. We've asked for the core component to be filterable several times and even submitted pull requests for that, those were denied so far. We want to fix this in a better way in core, so far the Gutenberg team doesn't allow us to.

**Comment by Ipstenu** [comment]
So perhaps this ticket should become "Make core/link and other components filterable so we don't kick the break can down the line" :)

**Comment by tellthemachines** [comment]
Closing this issue as adding link extension capabilities is being tracked in #11599.
