### ISSUE TITLE
Deleting the inital inner block in Media Text results in an empty block with no way to add inner blocks

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#23665]
**To reproduce**
1. Add a media text block
2. Click on the Heading that's added by default and press backspace (sometimes you have to do this twice)
3. Observe the block is empty but there's no way to insert a new block

**Expected behavior**
An appender is visible within Media Text when deleting the block

**Screenshots**
<img width="609" alt="Screenshot 2020-07-03 at 1 39 46 pm" src="https://user-images.githubusercontent.com/677833/86435503-af94cb00-bd32-11ea-945a-74f86de63ba0.png">

**Editor version (please complete the following information):**
- Gutenberg 8.4
- WordPress 5.4

**Comment by talldan** [comment]
Seems to be caused by this rule, but I can't work out why since the block has the `is-selected` class:
https://github.com/WordPress/gutenberg/pull/21142/files#diff-ee2ed3adbe2578628039530c717a9a93R474

cc @jasmussen.

**Comment by jasmussen** [comment]
Hmm. That's annoying. I have to work on something else right now, but do you think you have a path forward?

**Comment by talldan** [comment]
Yep, I've found a fix.
