### ISSUE TITLE
Page shows post formats

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2367]
The post format selection shouldn't be on pages, just on posts.

![2017-08-11 at 14 44](https://user-images.githubusercontent.com/253067/29215722-fe019d02-7ea3-11e7-931b-1e315e40a924.png)

cc @youknowriad in hope it's a fix we can get in.

**Comment by aduth** [comment]
Reopening as "just on posts" isn't entirely accurate. It applies to any post type which registers the `post-formats` supports.

https://developer.wordpress.org/reference/functions/add_post_type_support/
https://developer.wordpress.org/reference/functions/register_post_type/ (see `supports`)

cc @youknowriad re: #2372

**Comment by aduth** [comment]
There are quite a few post type supports which we currently do not account for:

- `title`
- `author`
- `excerpt`
- `revisions`
- `editor`

We may want to adapt this issue to tracking these, or break out into individual issues.

**Comment by aduth** [comment]
For reference, the implementation of Page Options sidebar correctly detects post type support:

https://github.com/WordPress/gutenberg/blob/bd502be463b89f0408a42a1e4feeaedc389fdb75/editor/sidebar/page-attributes/index.js#L34-L45

See: #1957

We may want to surface this more generally, for example in state.
