### ISSUE TITLE
Transform Buttons block to a Group breaks the editor

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#23687]
1. Add a Buttons block to your document. You can change the button text, or add more buttons.
2. Click on the block icon in the toolbar to open the transform menu, and select "Group."

You'll likely end up with something like this:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/191598/86489128-54160d80-bd31-11ea-80e7-ddf9bff3f45f.png">

If you then delete the block, the entire editor will break:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/191598/86489230-b5d67780-bd31-11ea-9664-354e20338abf.png">

**Comment by ntsekouras** [comment]
Hey @shaunandrews ! I've tried to reproduce with both 2020 and 2011 and everything seems ok..

Can you please provide more info about the version/theme or something that may be related?

**Comment by shaunandrews** [comment]
I'll close this one — I can't reproduce. Its possible I was mistakenly on a branch, or had some other issue. Thanks for double checking.
