### ISSUE TITLE
Image Block: Load for editing error if image not in the same FS

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#23686]
**Describe the bug**

We've observed that the loading is broken when images aren't stored on the local filesystem, for example when using certain file replication plugins. This line is returning a path to a non-existing file:
https://github.com/WordPress/gutenberg/blob/21709e3c533e78f9e63c583b6109caadc7cdf7be/lib/class-wp-rest-image-editor-controller.php#L114
There is already code in core that handles this case well, we can take inspiration from this patch: https://core.trac.wordpress.org/changeset/20384

**Comment by sirreal** [comment]
The [code from the referenced changeset](https://github.com/WordPress/wordpress-develop/blob/88c91eeaa6ab8d73bb3f5b301f9a0faf41e8e3e2/src/wp-admin/includes/image.php#L27-L37) set is battle tested and likely a good improvement here:

```php
	if ( is_numeric( $src ) ) { // Handle int as attachment ID.
		$src_file = get_attached_file( $src );


		if ( ! file_exists( $src_file ) ) {
			// If the file doesn't exist, attempt a URL fopen on the src link.
			// This can occur with certain file replication plugins.
			$src = _load_image_to_edit_path( $src, 'full' );
		} else {
			$src = $src_file;
		}
	}
```
