### ISSUE TITLE
Feature request: display version number in editor

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2368]
![add-version-number-gutenberg](https://user-images.githubusercontent.com/14795150/29218105-910b454e-7e68-11e7-9c8f-60ef98bc5e3b.png)

## Issue Overview

Since it's important for testers to include the version number with their bug reports or feedback, it would be great if you could actually display that within the editor (see attached screenshot). I've set up a Gutenberg test site with open registration, but the testers have the role "author" so can't actually look at the plugin screen in order to identify the version. (@aduth gave me some temporary code to put it at the bottom instead, and that would probably work, though on a small screen there isn't much space below the sidebar.)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Possible Solution

This is @aduth's code:

```
diff --git a/lib/register.php b/lib/register.php
index cf16006d..7aa07959 100644
--- a/lib/register.php
+++ b/lib/register.php
@@ -21,6 +21,9 @@ function the_gutenberg_project() {
 	?>
 	<div class="gutenberg">
 		<section id="editor" class="gutenberg__editor"></section>
+		<div style="position: fixed; bottom: 10px; right: 10px;">
+			Gutenberg <?php $data = get_plugin_data( dirname( __FILE__ ) . '/../gutenberg.php' ); esc_html_e( $data['Version'] ); ?>
+		</div>
 	</div>
 	<?php
 }
```

## Todos
- [ ] Tests
- [ ] Documentation

Thanks!
Sallie

**Comment by karmatosed** [comment]
Initially I thought this was a good idea, but the more I think about it maybe it's going to cause some users issues. 

Let me explain that as I do see the benefit and don't just want to dismiss. When someone is testing it's easy for distractions and things to come up in each test (like a bug for example). We want people to test without commenting each time about the 'number in the corner'. We want tests where we don't have to either write a comment each time or say in script about the number.

I get the benefit of having this, for bug fixing. However, with the pace and fact you can see on the plugin the number, for now let's close this. I totally see the benefits, I just can see the issues as we scale up testing.

**Comment by wpfangirl** [comment]
I was requesting it specifically because people who sign up on the East Bay WP test site only have author-level accounts, and thus can't see the plugins list and the version number there.
