### ISSUE TITLE
Doc: Create-block readme.md - no questions ask

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#23697]
[readme.md #QuickStart ](https://github.com/WordPress/gutenberg/tree/master/docs/designers-developers/developers/tutorials/create-block#quick-start)
It says: 
"The above command will ask you a few questions to customize, then will create a new directory called starter-block, installs the necessary files, and builds the block plugin."

After I ran `npx @wordpress/create-block flcharity`

There are the prompts 
![Screen Shot 2020-07-04 at 6 03 54 PM](https://user-images.githubusercontent.com/39980/86521636-4f308700-be21-11ea-96ae-c54b47627ea6.png)

**To reproduce**
1. use your Command line to navigate to the plugins folder of your local WordPress install
2. Type `npx @wordpress/create-block starter-block
3. wait for the questions. 

**Expected behavior**
Some questions for block name, namespace, and other information that needs to be use for a plugin. 

[On the package home page it says](https://www.npmjs.com/package/@wordpress/create-block) 

"Interactive mode - it gives a chance to customize a few most important options before the code gets generated.

`$ npm init @wordpress/block"`

The questions are: 
 ? The block slug used for identification (also the plugin and output folder name)
? The internal namespace for the block name (something unique for your products)
? The display title for your block:
? The short description for your block (optional):
? The dashicon to make it easier to identify your block (optional):
? The category name to help users browse and discover your block:
? The name of the plugin author (optional). Multiple authors may be listed using
 commas:
? The short name of the plugin’s license (optional):  - default entry ==>  "GPL-2.0-or-later"
? A link to the full text of the license (optional): - default entry ==> https://www.gnu.org/license
s/gpl-2.0.html
? The current version number of the plugin: 0.1.0

Here is an example: 

![Screen Shot 2020-07-04 at 6 27 12 PM](https://user-images.githubusercontent.com/39980/86521879-25c52a80-be24-11ea-8599-b3633323a70f.png)

**Comment by gziolo** [comment]
Good catch. As of today the interactive mode with all questions is triggered when you call:
```sh
$ npx @wordpress/create-block
```
or its alias that is shorter but uses the same package:
```sh
$ npm init @wordpress/block
```
More about `npm init` at https://docs.npmjs.com/cli/init.

If you pass the name of the folder, that is also the slug, then all default values are used.

@mkaz, I hope it clarifies everything. We should align documentation between those two linked documents.

In addition to that, I read that JSON support in webpack and it looks like it works out of the box for some time already. It seems like we can remove some duplication you mentioned between JavaScript and `block.json` for ESNext template in Create Block.

**Comment by mkaz** [comment]
👍 Good catch, I created a PR to address this issue and unifies commands in package and tutorial #23752 

@gziolo I opened an issue here to track the JSON update https://github.com/WordPress/gutenberg/issues/23753
