### ISSUE TITLE
List of Reusable Blocks suddenly empty

### ISSUE THREAD

**Issue by hporten** [WordPress/gutenberg#23699]
First experiments with Reusable Blocks worked perfectly. Suddenly, none of them is available via the editor toolbar anymore. And the "Manage all reusable blocks" page is empty.  While `All(8)` clearly shows that there should be 8 of them, no?

![noblocks](https://user-images.githubusercontent.com/3319974/86539743-53cb6d00-beff-11ea-9da1-7dc21d91a5c5.png)

I noticed the problem after add a new reusable block with a name that has a `/` in it. But the problem may have been present before that.

No JS or PHP error is spotted on the Blocks page. Any idea how to debug this?

**Comment by annezazu** [comment]
@hporten thanks for sharing this although I'm bummed you're running into this problem. To help others help you, can you share more information about your site including what version of WordPress you're using, if you're using Gutenberg and what version if so, etc? 

In terms of debugging this, I'd try ruling out a plugin conflict by disabling different plugins to start!

**Comment by hporten** [comment]
Hello, @annezazu, thanks for your response.

The WordPress version is the most recent stable version 5.4.2.

https://developer.wordpress.org/block-editor/principles/versions-in-wordpress/ says this means Gutenberg versions 6.6-7.5. How does one tell exactly? We use what got bundled with WordPress.

I cannot easily disable other plugins right now. But we'll check the database for reusable blocks and try disabling those one-by-one. Or try some debugging option like WP_DEBUG.

**Comment by hporten** [comment]
Turns out that the WPML plugin interfered here. After visiting the Reusable Blocks in the browser one-by-one (based on the id number found in the database) they appeared again. The screenshot shows that there are 9 English blocks now. And the list is complete again.

![works](https://user-images.githubusercontent.com/3319974/87418629-4a629480-c5d2-11ea-9e34-21d8d4811dca.png)

Since we have a workaround and cannot find out anymore which of the plugins is at fault I'll close this issue.

**Comment by annezazu** [comment]
@hporten thanks for sleuthing here and following up!
