### ISSUE TITLE
Image editor REST: Dispatched request 

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#23691]
**Describe the bug**

[The `/wp/v2/media/{{ ID }}/edit` REST endpoint](https://github.com/WordPress/gutenberg/blob/21709e3c533e78f9e63c583b6109caadc7cdf7be/lib/class-wp-rest-image-editor-controller.php#L17) makes a second REST request in order to produce the final response after editing the image:

https://github.com/WordPress/gutenberg/blob/21709e3c533e78f9e63c583b6109caadc7cdf7be/lib/class-wp-rest-image-editor-controller.php#L273-L283

This is problematic in the case endpoints are rewritten. There are various filters that allow REST customization, but in this particular case there appears to be no suitable filters. Consider the following:

- Rest paths are rewritten, so the `wp/v2/media/{{ MEDIA_ID }}/edit` becomes `myNamespace/media/{{ MEDIA_ID }}/edit`. `wp/v2/media/{{ MEDIA_ID }}` becomes `myNamespace/media/{{ MEDIA_ID }}`
- The edit request is properly sent to the edit endpoint.
- The endpoint dispatches a request to the rest server at `wp/v2/media/{{ MEDIA_ID }}`.
- This request fails with `rest_no_route`. No suitable filter appears to exist.

The details here are contrived, but do reflect issues observed in a production system with this endpoint.

Are the existing filters that can be applied to the `wp/v2/media/{{ MEDIA_ID }}` path before dispatching the request? Alternatively, could we avoid dispatching a second REST request altogether when constructing the response?

cc: @TimothyBJacobs  @azaozz

**Comment by TimothyBJacobs** [comment]
This won't be an issue when the endpoint is merged in Core because it will be part of the attachments controller. I'd recommend using the `rest_pre_dispatch` to dynamically rewrite requests in that case.

**Comment by TimothyBJacobs** [comment]
Closing this out as the merged endpoint in core is using `prepare_item_for_response()` https://github.com/WordPress/wordpress-develop/commit/e51a554f5da556804e05e0bb498f59473de8ce7d#diff-1eb39d6eeffe83b48eab8411d4aa5539R594.
