### ISSUE TITLE
Hero block adds a weird, empty button

### ISSUE THREAD

**Issue by codebykat** [WordPress/gutenberg#23701]
**Describe the bug**
We're using the "hero" block on simplenote.com (a WordPress.com site) without a button. This leads to a weird "pill" which is an empty button that cannot be removed, no matter how many times I delete it in the block editor. Deleting it in the code editor leads to the block being "invalid".

I have currently hidden it via CSS but it is still on the page.

What's odd is that this problem doesn't exist on the staging site where this content was created. I copy-pasted the Gutenberg code from that site to the live site. Looking at the code in each editor, it is the exact same, but on the staging site it doesn't show the "pill". It's very confusing.

Theme and CSS styles are identical on both sites.

This is the code:

```
<!-- wp:coblocks/hero {"paddingSyncUnits":true,"backgroundImg":"https://simplenoteblog.files.wordpress.com/2020/07/simplenote_hero.png","backgroundPosition":"","backgroundSize":"cover","focalPoint":{"x":"0.00","y":"0.00"},"heightTablet":300,"heightMobile":160,"maxWidth":400,"coblocks":{"id":"51110853771"}} -->
<div class="wp-block-coblocks-hero alignfull coblocks-hero-51110853771"><div class="wp-block-coblocks-hero__inner bg-cover has-background-image bg-no-repeat hero-center-left-align has-padding has-huge-padding" style="background-image:url(https://simplenoteblog.files.wordpress.com/2020/07/simplenote_hero.png);background-position:0% 0%;min-height:500px"><div class="wp-block-coblocks-hero__content-wrapper"><div class="wp-block-coblocks-hero__content" style="max-width:400px"><!-- wp:buttons {"align":"left"} -->
<div class="wp-block-buttons alignleft"></div>
<!-- /wp:buttons --></div></div></div></div>
<!-- /wp:coblocks/hero -->

```
**Expected behavior**
Being able to use the hero block without a callout.

**Screenshots**

<img width="496" alt="Screen Shot 2020-07-05 at 3 04 17 PM" src="https://user-images.githubusercontent.com/52152/86543149-d7219a00-bed0-11ea-82a7-2630c78895ed.png">

<img width="681" alt="screen-shot-2020-07-03-at-11 58 14-am" src="https://user-images.githubusercontent.com/52152/86542883-8315b600-bece-11ea-9eeb-fa8df0bb6f46.png">

<img width="520" alt="Screen Shot 2020-07-05 at 2 50 24 PM" src="https://user-images.githubusercontent.com/52152/86542924-e3a4f300-bece-11ea-8c11-924e10e96a29.png">

And like this in the editor:

<img width="527" alt="Screen Shot 2020-07-05 at 2 31 08 PM" src="https://user-images.githubusercontent.com/52152/86542805-eb17cc80-becd-11ea-8d94-7aa4fe1d1700.png">

<img width="606" alt="Screen Shot 2020-07-05 at 2 34 56 PM" src="https://user-images.githubusercontent.com/52152/86542811-ef43ea00-becd-11ea-8bd3-e5d0b8c3711a.png">

**Editor version (please complete the following information):**
- WordPress version: WordPress.com

**Comment by richtabor** [comment]
Looks to be related to https://github.com/WordPress/gutenberg/issues/17221.

**Comment by codebykat** [comment]
Thanks @richtabor, didn't see that in search. That does indeed look like the same bug. Happy to close this as a duplicate for now!
