### ISSUE TITLE
ThemeSupportCheck is not exported

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#23705]
In the `index.js` file of the editor package one can see:

`export { default as PostTypeSupportCheck } from './post-type-support-check';`

but no:

`export { default as ThemeSupportCheck } from './theme-support-check';`

Why is the `ThemeSupportCheck` component not exported? Is this by design?

Thanks

**Comment by mrleemon** [comment]
I see that there is a pull request for this already:
https://github.com/WordPress/gutenberg/pull/20506

**Comment by Mamaduka** [comment]
Closing this issue as #20506 is merged now.
