### ISSUE TITLE
Changing how blocks are loaded

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#2371]
## Issue Overview

Eventually we will need blocks in the editor to be different under different contexts. Currently our blocks variable is tied to whatever blocks are registered and stored in a loose semi-global variable `blocks`. This is fine as `blocks` itself is encapsulated from any changes without expressly using the API `registerBlockType`, and `unregisterBlockType`. This does lead to what I would argue as unexpected behavior in the test suite, as new blocks will magically appear in the test suite when they are added to Gutenberg. All of this is fine, but I think in the not too distant future this set up will meet its limit and become a giant mess. In a side project, I already had to revamp some of the code to make registering different blocks for different post types, and it was grueling.

## Possible First Steps

One of the first steps that can be done is to add blocks to the editorSettings object argument for `createEditorInstance`, then have getBlockTypes et al. ( our getters ) call the list of blocks for the particular editor instance. This will be a good first step towards isolating different block sets. The editor will only worry about the blocks that it instantiates with vs. every block that is registered to blocks.

## Downsides
It's a lot of work to revamp the code base, test suites etc. and should not necessarily be prioritized. I am also curious as to whether anyone else thinks this would be a bad idea, and why.

**Comment by youknowriad** [comment]
cc #2182

**Comment by danielbachhuber** [comment]
@BE-Webdesign Are there any actions we can take in this issue?

**Comment by BE-Webdesign** [comment]
Nope.
