### ISSUE TITLE
Inconsistencies with G2 select/focus states

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#23718]
I was testing the latest G2 styling and came up with a few small inconsistencies with focus/select states (border widths and radius) on items (screenshots below). I'm thinking we should have consistent border widths, colors and radii. Thoughts?

<img width="389" alt="Screen Shot 2020-07-06 at 1 19 13 PM" src="https://user-images.githubusercontent.com/1813435/86621046-7c994400-bf8b-11ea-8384-0ad62c890098.png">

<img width="542" alt="Screen Shot 2020-07-06 at 1 19 07 PM" src="https://user-images.githubusercontent.com/1813435/86621108-99357c00-bf8b-11ea-809e-47dbbbf24507.png">

<img width="161" alt="Screen Shot 2020-07-06 at 1 19 35 PM" src="https://user-images.githubusercontent.com/1813435/86621123-a2264d80-bf8b-11ea-9a18-9a858c0fa1ca.png">

<img width="270" alt="Screen Shot 2020-07-06 at 1 33 25 PM" src="https://user-images.githubusercontent.com/1813435/86622098-4f4d9580-bf8d-11ea-8fc5-27e5ac1d24f8.png">
 
<img width="275" alt="Screen Shot 2020-07-06 at 1 33 19 PM" src="https://user-images.githubusercontent.com/1813435/86622108-5379b300-bf8d-11ea-87a3-3cedfd939d57.png">

**Comment by noahshrader** [comment]
@richtabor Great finds! Seeing these also, though they're slightly different from yours. Mind providing which browser you're using in those screenshots, as well as the operating system you're on?

**Comment by richtabor** [comment]
Hey @noahshrader. These are from Safari on a 6k display.

**Comment by Mamaduka** [comment]
Probably fixed via #27968.
