### ISSUE TITLE
Performance issues with large galleries

### ISSUE THREAD

**Issue by slavicd** [WordPress/gutenberg#23714]
**Describe the bug**
Having large galleries (~100+ images in the case of my browser) makes it pretty much impossible to edit gallery settings and even post, bringing the page execution to a halt.

It looks like the problem arises due to multiple ajax requests per image to wp-admin.

**To reproduce**
1. install stock WP
2. upload 100+ images
3. create a gallery in a new post with all the 100+ images

**Expected behavior**
I expect to be able to edit the page/gallery without huge lags and crashes as possible before Gutenberg.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- default block editor

**Desktop (please complete the following information):**
 - Fedora Linux
 - latest Firefox

**Comment by annezazu** [comment]
This perhaps might be related to this: https://github.com/WordPress/gutenberg/issues/10994

**Comment by Mamaduka** [comment]
Hi, @slavicd

Are you still able to reproduce the issue with the latest WP version? The request number should now be reduced. See #34389.

**Comment by Mamaduka** [comment]
I'm going to close the issue. The fix (#34389) was shipped in WP a few versions back.

@slavicd, feel free to re-open the issue, if you're still experiencing the problem.

**Comment by slavicd** [comment]
> Hi, @slavicd
> 
> Are you still able to reproduce the issue with the latest WP version? The request number should now be reduced. See #34389.

I haven't had the chance to test on recent versions. I'm sure if no one else reported it must've been fixed.
