### ISSUE TITLE
Saving my Gutenberg block in any page it results in a malformed HTML

### ISSUE THREAD

**Issue by alvaroortegac** [WordPress/gutenberg#23723]
**Describe the bug**
We have our gutenberg block which has worked fine all this time. 

On Save it generates a component part of it is a script tag we need to execute. This component is generated by a react functional component. 

As part of an optimisation in our code we have added the property defer to the script generated. 

```
registerBlockType('forms-block', {
 ...props,
save: props => (
      <Fragment>
       {...}
        <div id={`form-${divUuid}`} />
        <script
          charset="utf-8"
          type="text/javascript"
          src={formsScript}
          defer="defer" // NEW LINE ADDED
        />
      </Fragment>
    );
```
when the block is added to the page and it is saved, the preview of the page works fine but the edit I get the block is malformed see image below.

the script is rendered as `<script charset="utf-8" type="text/javascript" src={...} defer></script>`

and the suggestion I get is to convert it to defer=""

**Expected behavior**
The script code ignores the value assign to the property defer, why does the block forces me to equal it to an empty string? What would it be the correct way to pass this property?

**Screenshots**
<img width="674" alt="Screenshot 2020-07-06 at 20 45 34" src="https://user-images.githubusercontent.com/66687686/86634601-f7814f80-bfc9-11ea-9bc2-b786cd560c01.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 83.0.4103.97

**Comment by talldan** [comment]
@alvaroortegac As far as I can tell, this is because defer is a boolean attribute:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

It should be written as follows:
```jsx
<script
          charset="utf-8"
          type="text/javascript"
          src={formsScript}
          defer // NEW LINE ADDED
        />
```

I tested a block and didn't get an invalidation when writing the attribute like this.

I think it'd be preferable to enqueue this script using `wp_enqueue_script()` rather than outputting it in each block within a post.
