### ISSUE TITLE
Sidebar controls: space after label is missing.

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#23724]
**Describe the bug**
In german we have really long words, so 35% for the label in the sidebar is not enough :D Introduced in #23578 
CC: @jasmussen 

![Bildschirmfoto 2020-07-06 um 22 14 32](https://user-images.githubusercontent.com/695201/86637684-4af99a80-bfd6-11ea-9566-b7a3422612bd.png)

**Comment by jasmussen** [comment]
Thank you for the ticket! I created #23738 to address this.
