### ISSUE TITLE
Navigation screen: Add support for advanced menu properties

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#23731]
The existing `nav-menus.php` page supports a bunch of advanced menu properties which can be found by enabling them in _Screen Options_ (top right).

<img width="1278" alt="Screen Shot 2020-07-07 at 12 32 26" src="https://user-images.githubusercontent.com/612155/86693325-eb3ed600-c04d-11ea-8135-a5aea8c31ae1.png">

To maintain backwards compatibility, our new Navigation screen will need to support these properties as well.

- Link Target
  - What it is: The link's `target` attribute.
  - Does Navigation block support it: Yes, via the  _Open in new tab_ checkbox when inserting a link.
  - Action required: None.
- Title Attribute
  - What it is: The link's `title` attribute.
  - Does Navigation block support it: No.
  - **Action required: Add a freeform text field to the Block Settings for a Link block.**
- CSS Classes
  - What it is: The link's `class` attribute.
  - Does Navigation block support it: Yes, via the _Additional CSS class(es)_ text field in Block Settings.
  - **Action required: Show Block Settings in the Navigation screen.**
- Link Relationship (XFN)
  - What it is: The link's `rel` attribute.
  - Does Navigation block support it: Partial. We support setting `rel="nofollow"` via the _Add nofollow to link_ checkbox.
  - Action required:
    - **Swap _Add nofollow to link_ checkbox for _Link rel_ text field (https://github.com/WordPress/gutenberg/issues/23153#issuecomment-654554337).**
    - **Show Block Settings in the Navigation screen.**
- Description
  - What it is: Used in some themes.
  - Does Navigation block support it: Yes, via the _Description_ text box.
  - **Action required: Show Block Settings in the Navigation screen.**

**Comment by noisysocks** [comment]
@shaunandrews: Any thoughts on how to show Block Settings in the Navigation screen?

**Comment by draganescu** [comment]
This issue ties in perfectly with adding an inspector in this screen. It's also required for customising the new blocks that can be added to navigation.

**Comment by shaunandrews** [comment]
I think all of this would be solved by introducing the block settings UI, like outlined in https://github.com/WordPress/gutenberg/issues/23934#issuecomment-674268745

**Comment by noisysocks** [comment]
Yep. Moving this to _Blocked_ as it relies on #23934 to be done first.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/24669 added Block Settings to the screen. We'll ned to wire up the various controls that Navigation supports, though. Right now setting them does nothing.

![](https://user-images.githubusercontent.com/107534/91038270-2b184780-e613-11ea-8052-6d625e3ee919.gif)

**Comment by talldan** [comment]
At the same time, there are some block inspector options that won't work in the navigation screen.

That mostly seems to be on the nav block itself (Typography, Show submenu indicator icons). I guess there's no plan to support these, so should they be removed?

I think we did the same for some of the toolbar options in the nav block, so it might be fairly straightforward to do the same.

**Comment by noisysocks** [comment]
> That mostly seems to be on the nav block itself (Typography, Show submenu indicator icons). I guess there's no plan to support these, so should they be removed?

Yes I think let's remove these, at least for now.

**Comment by tellthemachines** [comment]
Closing as all the required features have been implemented.
