### ISSUE TITLE
NPM package version

### ISSUE THREAD

**Issue by thomasmoors** [WordPress/gutenberg#23749]
**Is your feature request related to a problem? Please describe.**
I would like to use this beautiful edit in another project.

**Describe the solution you'd like**
Make this a standalone package please

**Describe alternatives you've considered**
/

**Comment by talldan** [comment]
@thomasmoors You are in luck, the editor can be used standalone.

The block editor package serves this purpose (and is published on NPM as `@wordpress/block-editor`:
https://github.com/WordPress/gutenberg/tree/master/packages/block-editor

There's a little bit of work to get it set up, but there's an example here in the storybook:
https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default

The code for that is here:
https://github.com/WordPress/gutenberg/blob/master/storybook/stories/playground/index.js
