### ISSUE TITLE
Block picker can appear behind the admin toolbar

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#23756]
**Describe the bug**

The block picker can appear partially behind the admin toolbar when full-screen mode is not in use. See attached screenshot.

**To reproduce**

1. Edit the default Hello World post included with WordPress
2. Disable full-screen mode in the tools & options menu
3. Click the block inserter button at the bottom of the post
4. Observe that, if your window is the right height and the inserter button is at the right position, the block picker modal appears partially behind the admin toolbar.

**Screenshots**

<img width="816" alt="" src="https://user-images.githubusercontent.com/208434/86798143-c14adb00-c070-11ea-9ceb-9fcc7715dff8.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5-alpha-47426-src
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 10.15

**Comment by talldan** [comment]
Most popovers are possibly using the same z-index, so it might be more of a global issue rather than something related to only the block picker.

**Comment by kathrynwp** [comment]
@johnbillion I tried many configurations, but am no longer able to replicate this issue. At all screen sizes I tested, the block inserter is never hiding under the admin bar:

![Edit_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/182949127-6f751c5e-bb1d-44a4-9860-9b00fecc74b8.jpg)

Tested with:

WordPress 6.0.1
Gutenberg 13.8.0 active or inactive
No other plugins active

Chrome 104.0.5112.79
Firefox 103.0.1 
macOS 12.2.1

I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.
