### ISSUE TITLE
Quick inserter width does not expand when the browser window width is below 782px

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#23755]
**Describe the bug**
When the browser widow width reaches 782 pixels or less, the inserter moves to cover the entire page.

The components-popover__header is full width, but 
the quick inserter content width is set to 350px:

```
.block-editor-inserter__quick-inserter {
    width: 350px;
}
```
It also, in comparison to the "add block sidebar", covers the WordPress admin bar.
The spacing around the header is inconsistent / smaller.

**To reproduce**
1. Activate Gutenberg version 8.5.0-rc.1
2. Open the block editor
3. Reduce the browser window width
4. Click to open the quick inserter

**Expected behavior**
I expect the width of the inserter to adapt and expand similar to the other inserters, sidebars etc.

**Screenshots**

Quick inserter:
![The quick inserter window is too narrow below 782px](https://user-images.githubusercontent.com/7422055/86794337-ae360c00-c06c-11ea-8b50-a309edf65bee.png)

The add block sidebar for comparison: 
![The add block sidebar expands to full width on smaller browser window widths](https://user-images.githubusercontent.com/7422055/86795527-f275dc00-c06d-11ea-9feb-18a8edba35db.png)

**Editor version (please complete the following information):**
- WordPress version:  5.5-alpha-48328
- If the Gutenberg plugin is installed, which version is it?   Version 8.5.0-rc.1

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome Version 83.0.4103.116

**Comment by allilevine** [comment]
Did #23896 resolve this issue?

**Comment by carolinan** [comment]
I have confirmed that this has been solved.
