### ISSUE TITLE
Consolidate typography and text settings panels within the Paragraph block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#23767]
**Describe the issue**
Currently the Paragraph block features a "Typography" panel within the Settings sidebar for font size and line height, as well as a separate "Text settings" panel for the drop cap ToggleControl. I propose that we consolidate these panels into one, as they're all typographic controls. 

**Suggested behavior**
Move the Drop cap control to the Typography panel within the Paragraph block's setting sidebar. This will simplify the sidebar by removing an unnecessary panel.

**Screenshots**
<img width="1017" alt="Screen Shot 2020-07-07 at 4 21 24 PM" src="https://user-images.githubusercontent.com/1813435/86839016-e0e10400-c06e-11ea-8d88-892dd87da62c.png">

**Comment by mapk** [comment]
This makes sense to me. I had a brief conversation with Rich in the Design Triage meeting today, and combining these could work if there is a way to hide certain settings from the component for blocks that don't require that particular setting. 

I'd like to see us more forward with this, but am unsure on the technical details. cc @ItsJonQ

**Comment by supernovia** [comment]
[Here's](https://wordpress.com/forums/topic/drop-cap-suggestions/) a vote for keeping the Drop Cap controls separate, but giving them the same options so there's less disparity. Someone might want a drop cap with a teal background and white text, for example, without having to use CSS.
