### ISSUE TITLE
Consider exposing the block list orientation through block context

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#23778]
**Is your feature request related to a problem? Please describe.**
A couple of use cases came up recently in the navigation block for adding spacing and separators:
- Add a way to control spacing (https://github.com/WordPress/gutenberg/issues/23294)
- Add separatator to the navigation block (https://github.com/WordPress/gutenberg/issues/23293).

The editor already has Spacer and Separator blocks, but one issue is that the Navigation block can work both horizontally and vertically, while spacer and separator blocks are currently limited to working vertical layouts.

**Describe the solution you'd like**
If `orientation` were exposed through block context, the spacer and separator blocks could potentially be written in such a way that they automatically work in both horizontal and vertical lists.

**Describe alternatives you've considered**
- A specific setting for changing orientation on the Spacer and Separator blocks

**Comment by tellthemachines** [comment]
Closing as this has been addressed in #29133.

**Comment by talldan** [comment]
@tellthemachines The idea here is to expose it automatically when it's specified on innerBlocks, not just for the navigation block.

**Comment by talldan** [comment]
This is a bit outdated and technically focused. I'll close it down.
