### ISSUE TITLE
Unable to Remove Background/Text Color from Blocks Once Applied in Inspector

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2377]
One thing I've run across in playing with this color picker is that there is no option to remove the color and go back to whatever the enqueued CSS files would produce.

This could be done obviously in the text editor but the problem there is that it first assumes the end-user will know to look there and know what to change and, even if they did, the block becomes frozen and uneditable with this message...

![image](https://user-images.githubusercontent.com/12448364/29197548-4a5624f6-7e0a-11e7-85cf-fb353241cf9c.png)

As a result, I have one of two options - to either delete the block and recreate it from scratch or I have to surrender my ability to edit the block visually.

My suggestion would be to add a link next to ***Text Color*** and ***Background Color*** that simply says **Remove Color** that will remove the `color:#xxxxxx` and `background-color:#xxxxxx` from the `style` attribute of the `<div>` element. Something along the lines of this:

![image](https://user-images.githubusercontent.com/12448364/29197628-e7fe692a-7e0a-11e7-963b-8d5d2d3fa728.png)

It would also need to check and see if removing the style would result in an empty style attribute and just remove it completely if so.

**Comment by youknowriad** [comment]
closed by #2406
