### ISSUE TITLE
Lock BlockList

### ISSUE THREAD

**Issue by joaojoyce** [WordPress/gutenberg#23791]
Hi,

I'm using gutenberg as a standalone editor in react (import "@wordpress/editor"). 
Is there a way to lock the BlockList so it only contains one block?

Explanation: 

In a certain page I want the user to be able to edit some content but not an header/footer block.
I've tried to achieve this by creating a Block wrapper that is locked and contains:

<HeaderBlock >
<ContentBlock >
<FooterBlock >

The ContentBlock is also a wrapper using InnerBlocks but I pass the allowed_blocks and templateLock=false.
So the WrapperBlock gets locked and the ContentBlock is free for the user to change.

This works perfectly well apart from the following facts:

- I can drag and drop blocks from ContentBlock to outside the WrapperBlock, effectively making the wrapper useless.
- I can select/drag/delete the WrapperBlock, which I would like to prevent as it is not usable for anything.

Is there a way to accomplish this?

**Comment by jasmussen** [comment]
You can do this using custom post types and templates:

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/#locking

Hope that helps!
