### ISSUE TITLE
Opened Link popover component changes position when pressing Bold or Italic keyboard shortcut 

### ISSUE THREAD

**Issue by ObliviousHarmony** [WordPress/gutenberg#23799]
**Describe the bug**
If the bold hotkey is pressed while the link popover component is open it causes it to move positions in a strange way. In 8.4 it floats off into the distance and in 8.5 if shifts position once.

**To reproduce**
1. Open the block editor
2. Select some text
3. Open the link popover
4. Press the ⌘B hotkey

**Expected behavior**
My first thought is that perhaps you shouldn't be able to use the hotkey while the link popover is active. I was also thinking it might just move more appropriately but I don't think this is a common situation in the first place.

**Screenshots**
8.4: https://d.pr/i/sGotGK
8.5: https://d.pr/i/JV3ppx

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Default Editor
- Also tested with 8.5

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 83

**Comment by ntsekouras** [comment]
Hey @ObliviousHarmony -- thanks for reporting this! I reproduced it and can confirm it's a bug.

**Comment by kathrynwp** [comment]
Hi @ObliviousHarmony @ntsekouras I haven't been able to replicate this anymore, either with command-b or command-i. 

When using those hotkeys with the link popover active in Chrome, nothing happens, as expected. (That said, the Droplr screenshot links no longer work so I can't confirm 100% what I should be looking for!)

Tested with:

WordPress 6.0.1
Gutenberg 13.8.0 active or inactive
No other plugins active

Chrome 104.0.5112.79
macOS 12.2.1

I'm going to go ahead and close this out, but if anyone is still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.
