### ISSUE TITLE
Automatically remove block patterns if one or more of the blocks has been unregistered using unregisterBlockType

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#23803]
If a block has been unregistered with `unregisterBlockType()`, patterns that use that block still show up in the "Patterns" tab of the block inserter. It shows an error message on the preview as well as when adding that pattern. 
It would be great if patterns that include a block that has been unregistered were automatically unregistered themselves (with `register_block_pattern()`).

**Screenshots**

<img width="346" alt="Screen Shot 2020-07-08 at 4 29 52 PM" src="https://user-images.githubusercontent.com/1783595/86967317-7d230d80-c138-11ea-9909-70dbdbcbb3c4.png">

**Editor version**
- WordPress version: 5.4.2
- Gutenberg plugin version: 8.5.0

**Additional Context**

I have a plugin that replaces the default columns block with a much more powerful version. I unregister the built in `core/columns` block so I don't confuse users with multiple blocks with the same name.

**Comment by jordesign** [comment]
@priethor Can I please get a gut check. It sounds like (based on the below comment from [#26607](https://github.com/WordPress/gutenberg/issues/26607)) that this may be resolved now?

> I'm not sure what I was thinking, but this is all possible via the block_editor_settings filter, which has been there all along. :)

**Comment by priethor** [comment]
@jordesign, as far as I understand, the filter doesn't solve this particular issue _automatically_, as you still need to disable the patterns apart from the blocks. However, there have been many recent changes in patterns, and it would be good to double-check whether this condition is already managed automatically or the issue still persists.

**Comment by qoorus** [comment]
<img width="820" alt="スクリーンショット 2024-02-28 20 59 22" src="https://github.com/WordPress/gutenberg/assets/41640222/734a370e-44f2-4907-968b-46d14e051ace">

I tested it on WordPress 6.4.3 and was able to reproduce it.
I think this error message is necessary.
This is because if you unregister a block and then register it again, if it has disappeared from the pattern, it becomes impossible to fix.

**Comment by youknowriad** [comment]
I don't think we should be unregistering the patterns automatically. There's a lot of different reasons for the block to not be available but maybe we should hide the message in "preview mode".

**Comment by youknowriad** [comment]
I found that this is a duplicate of #31706 which has more discussion in it. So I'm closing this one.
