### ISSUE TITLE
Add hook for tracking block pattern insertions

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#23812]
### Our use case
In calypso/wordpress.com, we have a desire to learn about how the 'block-patterns' feature is being used: 
i.e. are people actually using the feature? Which block patterns are being used and which ones aren't?
https://github.com/Automattic/wp-calypso/issues/40614

We explored different approaches, and couldn't find a sound way to record when block-patterns are used with only the existing hooks exposed by the inserter. https://github.com/Automattic/wp-calypso/issues/40614#issuecomment-655816612

### Why we can't use existing hooks
Block patterns are currently inserted as an array of the blocks that make up the pattern. https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inserter/hooks/use-patterns-state.js#L34
This causes the `core/blocks` store to dispatch a `insertBlocks` event with just the array of blocks from the selected pattern.
So in the wpcom-block-editor plugin, we intercept the `insertBlocks` event and apply our tracking 
https://github.com/Automattic/wp-calypso/blob/4537033c6794449ce0a10b69d72daf5fa658d553/apps/wpcom-block-editor/src/wpcom/features/tracking.js#L119
But we don't have any way of reliably determining which `block-pattern` the user chose to insert 🤔, we just get an array of the blocks that make up that pattern.

### My suggested implementation

Trigger another event here, https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inserter/hooks/use-patterns-state.js#L34
Hmmm I think `core/block-editor:insertBlockPattern` would be a decent name, `onInsert()` ends up raising `core/block-editor:insertBlocks`.

```
	const { insertBlockPattern } = useDispatch( 'core/block-editor' );
	const onClickPattern = useCallback( ( pattern, blocks ) => {
		onInsert( map( blocks, ( block ) => cloneBlock( block ) ) ); // actually inserts the blocks of the block pattern
                insertBlockPattern( { block_pattern_name: pattern.name } ); // creates a redux event that plugins can use to track/ intercept block pattern insertions
		createSuccessNotice(
			...
		);
                ...
```

What do people think?  cc @youknowriad

**Comment by mcsf** [comment]
👋 

> creates a redux event that plugins can use to track/ intercept block pattern insertions

Hm, I'm wary of introducing a Redux action that has no function in the editor, since every dispatch has effects and comes with a cost in performance across the render tree. It's also not a pattern that we have in Gutenberg to "signal" user actions* separately from the actual effects. Finally, this might be a case of a very WP.com-specific interface need that would not serve any other consumer/developer of the project.

With this, I don't mean to unquestionably shut down the idea, but I think it needs poking, and I think we'd need to discuss better solutions for the problem. In this case, "better" might mean: less invasive, simpler, less costly, more applicable for other people.

_*: the closest example could be very specific instances of how we use JS hooks._

**Comment by roo2** [comment]
hmm yea I understand your resistance to adding a dummy event just for us to track block pattern insertions. I do have a different idea.

I originally expected block patterns would be represented in the editor as a single top level *Block Pattern* block with children. But when you insert a block pattern, you just get all of the blocks that make up the pattern added to the page without being grouped together. 
e.g. when I insert a "Image with Titles" block, I get a *Layout Grid* with two images, then a *Spacer*, then another *Layout Grid* but there's no top level *Image with Tiles* block.

<img width="1136" alt="Screen Shot 2020-07-16 at 3 40 18 PM" src="https://user-images.githubusercontent.com/22446385/87632327-82a5d680-c77c-11ea-859a-a0651a52664c.png">


This is what makes is dificult for us to achieve our goal of tracking block pattern usage and also makes it difficult to do other things, for example, the user can't move or delete a block pattern all together.

It makes sense to me that a good solution would be to wrap block patterns in a *Block Pattern* block, that wpcom can use for tracking insertions, and that users can use for moving/deleting their block patterns more easily.

This change would be bigger at least in terms of impact and testing but I think useful overall for more than just our use case. What do you think about that approach?

**Comment by talldan** [comment]
Just noting that this ticket was commented on in the core dev chat (conversation here: https://wordpress.slack.com/archives/C02RQBWTW/p1595448722158900).

There were some concerns about privacy (and process), I've asked for a comment to be added here.

**Comment by mtias** [comment]
This approach seems wrong. The semantics are awkward to read: `onInsert` seems to insert the blocks and `insertBlockPattern` seems to handle just the name.

It looks simpler and more generally useful to augment `insertBlocks` / `onInsert` to include the fact blocks were inserted as a pattern and the namespace/slug of the pattern. This is information that could be useful to show in something like the undo history, for example. Plugins can do whatever they need with this information.

I think this should be closed and a separate task to improve the signature of insertion function explored. The tracking subject is irrelevant here as well.
