### ISSUE TITLE
NPM doesn't see the file

### ISSUE THREAD

**Issue by AnastasiaDv491** [WordPress/gutenberg#23814]
Need help!
Can't resolve the issue

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\nastj\Desktop\Repositories\d3\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\nastj\Desktop\Repositories\d3\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nastj\AppData\Roaming\npm-cache\_logs\2020-07-09T06_02_01_261Z-debug.log
PS C:\Users\nastj\Desktop\Repositories\d3>

**Comment by Soean** [comment]
Hi @AnastasiaDv491 Can you give us some more information? What were you trying to do?

**Comment by AnastasiaDv491** [comment]
Figured it out!
