### ISSUE TITLE
Gradient Tool: Color stops should be allowed to overlap or even switch places. 

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#23816]
The color stops in the gradient control currently can't overlap:

![gradients](https://user-images.githubusercontent.com/1204802/87014149-fb7cbf80-c1cb-11ea-82db-2bcd7895a02c.gif)

That means you can only ever create a _gradient_:

<img width="1074" alt="Screenshot 2020-07-09 at 10 07 26" src="https://user-images.githubusercontent.com/1204802/87014187-0a637200-c1cc-11ea-94b3-e80bb4d59c44.png">

However if we did allow them to overlap, you could create perfectly sharp color stops like this:

<img width="1225" alt="Screenshot 2020-07-09 at 10 08 47" src="https://user-images.githubusercontent.com/1204802/87014311-3ed72e00-c1cc-11ea-9dcb-e36b49c263ec.png">

That's a wonderful aspect of gradients that we should allow. 

[This online tool](https://www.colorzilla.com/gradient-editor/) to generate gradients allows color stops to overlap, and to even go to the other side. That feels powerful, and lets you create cool things easily:

![example](https://user-images.githubusercontent.com/1204802/87014479-8067d900-c1cc-11ea-8a4e-46ad5affa740.gif)

**Comment by munirkamal** [comment]
I was going to write about this. This is really a must needed improvement as this will open up a lot of design possibilities. Looking forward to this.

**Comment by webmandesign** [comment]
All for it!

Maybe an interface for inserting exact specific stop position (number) would be also great. Something like in screenshots of https://github.com/WordPress/gutenberg/issues/16662#issuecomment-514332686
Although, it would be impossible to tweak overlapping stops (the one covered with the other) even this way. The only way this would be possible, as far as I can see, would be to move the top-most stop away, edit the stop below and move the first one over again. Not sure if this is a good UX though...

**Comment by susurruses** [comment]
I agree it would be helpful to be able to set specific, precise color stop positions within gradients—even basic ones without these sharp transitions.

For the gradient bar itself, one idea would be to put colors that would overlap (such as two stops at 50%) inside a lozenge shape—this allows each color to still be clicked on. See below:

![Adding color stops](https://user-images.githubusercontent.com/53234521/90292339-8a69a100-de36-11ea-8440-e3950b265be3.png)

I also think it would be useful to be able to specify the exact position you want a spot to be at from within the color picker:

![Adding position with color](https://user-images.githubusercontent.com/53234521/90292388-a705d900-de36-11ea-953a-f007ef72aec7.png)

In these mockups I added an "Add Color Stop" button as well—this way, users can either edit the color stops from the current gradient bar area, as well as while editing the stops in the Gradient Stops area. Adding a stop in either of these areas would automatically update the stop position/color within the other.

**Comment by alaczek** [comment]
Yes, I'm all for it! It's already possible to define custom gradients with sharp color stops in themes. The problem is, without proper controls it's not possible to edit those gradients in the editor.
