### ISSUE TITLE
FSE: Switching between edited posts mixes the posts content

### ISSUE THREAD

**Issue by yupal** [WordPress/gutenberg#23819]
**Describe the bug**
In full site editor if you change the content on a post and then switch to another post the contents of the posts get mixed up

**To reproduce**
1. Go to Site Editor (beta)
2. Click on the page switcher and select a page like Sample Page
3. Click on the page switcher and select the Hello World post
4. Make changes on the default content of Hellow World post
5. Switch back to the Sample Page
6. The content displayed is the one that we just changed

**Expected behavior**
The Sample Page content should be displayed

**Video**
Here is a video of the problem https://iulian-extendstudio.tinytake.com/tt/NDQ0MDYzMF8xNDA0MTg1Mw

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- The Gutenberg plugin is installed
- Gutenberg version: 8.5.0

**Desktop:**
 - OS: Windows
 - Browser Google Chrome
 - Version 83.0.4103.116

**Comment by noahtallen** [comment]
This should be fixed by #24012, can you let me know if it is still an issue for you now with the latest changes? We can reopen if it is still a problem :)
