### ISSUE TITLE
Block Editor: Arrow up/down keys get intercepted by the block list when a block is selected

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#23822]
**Describe the bug**

This bug might be difficult to reproduce as presented in the screencasts recorded. It only happens when one fo the block is selected and in Edit mode.

**To reproduce**
The most possible steps to reproduce the behavior:
1. Open a post with multiple blocks.
2. Move focus to one of the blocks in the middle that is in Edit mode and move focus to the toolbar.
3. Use arrow keys to go to the toolbar item that has a dropdown menu, use arrows up/down and observe that the drodpown randomly closes and the focus moves to the block.

It might require several tries, but I'm able to reproduce it also in the header section with other dropdown menus.

**Expected behavior**
Arrow up/down never moves focus out of the toolbar when navigating in dropdown menu between items.

**Screenshots**

The issue exists for both the floating toolbar and when docked to the top.

![toolbar-arrows-dropdowns](https://user-images.githubusercontent.com/699132/87031137-efe8c300-c1e2-11ea-8d35-92612db13aa8.gif)

![toolbar-arrows-dropdowns-floating](https://user-images.githubusercontent.com/699132/87031127-e8c1b500-c1e2-11ea-9790-c2297854e3f4.gif)

**Editor version (please complete the following information):**
- WordPress version: WordPress 5.5.0-beta.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes? Gutenberg plugin, the latest `master` branch

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
- Version: 13.1.1

**Comment by youknowriad** [comment]
It seems that the issue comes from the fact that the window selection is not updated properly on safary on multi-selections, I confirmed that the code runs but for some reason the selection is "lost". cc @ellatrix 

I think this is not blocking for 5.5 though.

**Comment by youknowriad** [comment]
Actually, I commented on the wrong ticket, Sorry about that :P

**Comment by ntsekouras** [comment]
I can't reproduce this.. I've tried several times.

**Comment by ellatrix** [comment]
Same for me, not sure how to reproduce it

**Comment by youknowriad** [comment]
Ok let's close for now.
