### ISSUE TITLE
Block Editor: Can't copy 2 selected blocks with keyboard shortcut (Safari)

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#23820]
**Describe the bug**
There is some sort of edge case on Safari where two selected blocks aren't copied with the keyboard shortcut `cmd` + `c`.

**To reproduce**
1. Create a new post.
2. Add a few blocks.
3. Select two blocks with `shift` and `arrow up/down`.
4. Use keyboard shortcut `cmd` + `c`.
5. Blocks aren't copied.

**Expected behavior**
2 blocks are copied with the keyboard shortcut.

**Screenshots**

![copy-paste](https://user-images.githubusercontent.com/699132/87023809-8f548880-c1d8-11ea-88d7-9077f5fb6960.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.0-beta1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? The latest `master` branch.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.1.1

**Comment by youknowriad** [comment]
It seems that the issue comes from the fact that the window selection is not updated properly on safari on multi-selections, I confirmed that the code runs but for some reason the selection is "lost". cc @ellatrix 

I think this is not blocking for 5.5 though.

**Comment by gziolo** [comment]
It's no longer an issue in WP 5.8 🎉
