### ISSUE TITLE
Cover Text Block Produces Semantically Neutral HTML for Accessibility Readers

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2382]
## Issue Overview
Certain blocks offer no semantics to accessibility technologies such as `Cover Text` while having visual differentiation. The resulting HTML code produced are all semantically neutral and treated as any other text while the block denotes some kind of differentiation.

## Current Behavior
Currently creating a Cover Text block results in the following HTML:

```
<div class="wp-block-cover-text>
   <p>Text</p>
</div>
```

## Possible Solution

Add an ARIA Landmark role such as `"region"`, `"note"`, or whichever is appropriate to containing `<div>` elements.

```
<div role="region" class="wp-block-cover-text>
   <p>Text</p>
</div>
```

**Comment by samikeijonen** [comment]
I kind of disagree on this one. For me this block is more about "Call to action block" where background image is just a decorative image.

When nested blocks are reality this kind of block is perfect for heading, text, and a button.

**Comment by samikeijonen** [comment]
Aaaaaah I was talking about the Cover Image Block all the time. Well, still not sure about the extra role for this :)

**Comment by cedon** [comment]
When I see "Cover Text", I think more of the back of a book. What do most of us do first when we go into a book store and see a title that interests us? Flip it over and read the back. So, using that interpretation of the term "Cover Text", the block would have more semantic meaning beyond just another `<div>` element.

So I guess the issue would be would such text need more designation beyond a `class` attribute. I'm leaning towards adding `role="note"`. The [ARIA Specification](https://www.w3.org/TR/wai-aria/roles#note) provides this role for

> A section whose content is parenthetic or ancillary to the main content of the resource.

That would go along with at least my interpretation of what place in the universe the Cover Text block holds.

**Comment by jeffpaul** [comment]
This was [discussed](https://wordpress.slack.com/archives/C02QB2JS7/p1516295899000048) in today's Gutenberg bug scrub and as there is no longer a Cover Text block we will close this issue.
