### ISSUE TITLE
Hide core blocks in the root appender, keeping them usable in custom blocks.

### ISSUE THREAD

**Issue by ecdani** [WordPress/gutenberg#23839]
Hi,

I want to remove/hide all core block (like core/paragraph) from root appender/inserter, and only allow the users to use my own custom blocks, but keeping the core blocks usable inside my custom blocks.

I didnt find nothing related about this.

I tried to hide/show the blocks:

`wp.data.dispatch( 'core/edit-post' ).hideBlockTypes( [  'core-embed/youtube' ] );
wp.data.dispatch( 'core/edit-post' ).showBlockTypes( [  'core-embed/youtube' ] );
`

But i cant achieve coherent results: I can't found a way to know when im inserting in the root or in my custom block. Also, the default inserter oscillate improperly between the paragraph inserter and the non-paragraph inserter.

Also i tried to remove the core blocks:
`wp.blocks.unregisterBlockType( 'core/verse' )`
But then they cant be used inside my own blocks.

I will appreciate any help.

Im using gutenberg outside wordpress.

**Comment by talldan** [comment]
@ecdani I'm not sure what your use case is, but you'd probably have more luck filtering core blocks:
https://developer.wordpress.org/block-editor/developers/filters/block-filters/

and adjusting something like the `parent` for core blocks:
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#parent-optional
