### ISSUE TITLE
Add a store icon

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#23835]
A store icon would be handy for a project we're working on at WooCommerce, and in other applications I am sure.

Before opening a PR I wanted to kick off discussion around some initial design concepts.

We already have the [Home](https://github.com/WordPress/gutenberg/blob/master/packages/icons/src/library/home.js) icon in the set, so it makes sense to build upon that and ensure any new store icon feels like it lives in the same city as the home icon (as my pal @jasmussen so eloquently put it :D)

I borrowed concepts from the Noun Project to put these options together:

![store](https://cldup.com/DEFdww0hsY-3000x3000.png)

Option 1 is the simplest and most widely-used interpretation I think - a building with an awning and a door. It's also the most minimal execution I could come up with, which aligns with a core principle of this icon set. Options 2 and 3 are more expressive, seeking to solidify the metaphor in case option 1 doesn't clearly communicate it. Personally I think option 1 does the job, but would be keen to hear thoughts, or see alternative ideas before getting in to the code and polishing the designs.

Edit: Figma link [here](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=3234%3A24162) in case anyone would like to riff on these sketches.

**Comment by pablohoneyhoney** [comment]
Would a _cart icon_ be more encompassing and flexible than an explicit physical _store_? Or a _bag_ (a bit less _physical_).

**Comment by jameskoster** [comment]
I think a cart / bag / basket icon would be a nice in _addition_ to this icon. 

For context we're looking to use this on a "view my store" link, so an all-encompassing icon feels more appropriate that something specific like a cart.

**Comment by j111q** [comment]
I like Option 1 the best on its own, but next to the Home icon, I think I prefer **Option 3**, which feels like it's in the same neighbourhood but still a distinctly different building. Option 1 + the current Home icon is a little too similar IMO. 🤔

**Comment by Garance91540** [comment]
I agree with Jill! I think along with the current home icon, option 3 is the best match. The striped roof also reinforces the store component (makes me think of a commercial stand), whereas option 1 and 2 are more connected to a "house" for me.

**Comment by jameskoster** [comment]
Thanks y'all, I opened a PR for option 3. We can continue discussion there! :)
