### ISSUE TITLE
Revisions may show the wrong content

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2386]
I guess this is more an issue related to integration with the existing Revisions functionality that needs some investigation. See also #2385.

- go in the Gutenberg "New Post" page
- in the paragraph below the title, type "a"
- click outside of the paragraph
- wait a few seconds to have the first revision saved (it will appear in the sidebar)
- add a second paragraph and type "b"
- click outside of the second paragraph
- wait a few seconds for the second revision to get saved
- click the "2 Revisions" link to go to the Revisions screen

See in the screenshot below: the content highlighted in green is wrong, and goes across the first and second paragraphs:

![screen shot 2017-08-12 at 11 54 01](https://user-images.githubusercontent.com/1682452/29239802-2ceacc52-7f57-11e7-94b1-a0962ebd94e7.png)

I haven't tested with more complex content or checked what happens when adding blocks that aren't contiguous.

Of course, repeating the same process in the classic editor (press "Save Draft" to generate the revisions), the new content in the revisions screen is highlighted correctly:

![screen shot 2017-08-12 at 12 01 23](https://user-images.githubusercontent.com/1682452/29239816-7280251e-7f57-11e7-9354-5d68ea6e886c.png)

**Comment by mtias** [comment]
The link to latest revision was inversed at some point. it should be alright now.
