### ISSUE TITLE
FocalPointPicker: values incorrectly displayed when in TabPanel

### ISSUE THREAD

**Issue by rodrigodagostino** [WordPress/gutenberg#23860]
**Describe the bug**
I included the FocalPointPicker component in one of my custom blocks, and everything worked as expected. But once I upgraded it to be included in a TabPanel and save the values inside of a multi-level object, values of horizontal and vertical position are not being displayed correctly, even though the focal pointer is displayed in the correct position and the values (when the pointer is dragged to a new position) are being saved correctly too.

This is the object in which values are being stored:
````
"focalPoint": {
	"type": "object",
	"default": {
		"small": {
			"x": 0.5,
			"y": 0.5
		},
		"medium": {
			"x": 0.5,
			"y": 0.5
		},
		"large": {
			"x": 0.5,
			"y": 0.5
		}
	}
}
````
And this is a simplified version of my component:
````
<TabPanel initialTabName="small">
	{ ( tab ) => (
		<FocalPointPicker
			url={ mediaUrl[ tab.name ] }
			value={ focalPoint[ tab.name ] }
			onChange={ value => handleChanges( 'values' ) }
		/>
	) }
</TabPanel>
````
In the following image the focal point has `x: 0.18 y: 0.5` as coordinates, but, as you can see, those do not match the values in the input fields:
![Screenshot_2020-07-10](https://user-images.githubusercontent.com/8670793/87115557-05dd9e80-c24a-11ea-9da0-724c24d1e349.png)

I've used this panel in such way with multiple components that I've developed, using the same attribute structure as mentioned above, so I'm quite certain the issue is not related to either of those two.

I can't figure out what seems to be the issue, since (even though I'm working with a muti-level object) there shouldn't be any difference when handling the stored values.

- WordPress version: 5.4.2
- Gutenberg plugin version: 8.5.1

**Comment by talldan** [comment]
@rodrigodagostino Are you still experiencing this?

If so, would you be able to share a minimal working example of the code in order to help us debug the issue? Thanks!

**Comment by talldan** [comment]
Closing due to lack of response from reporter.
