### ISSUE TITLE
Disappearance of the button for selecting the author of the article in the "Visibility status" section on the latest version

### ISSUE THREAD

**Issue by rodolphebertozzo** [WordPress/gutenberg#23864]
Before:
![bug2](https://user-images.githubusercontent.com/56270626/87137988-056ef300-c29e-11ea-8b68-0372ac379003.PNG)

After:
![bug1](https://user-images.githubusercontent.com/56270626/87138013-10298800-c29e-11ea-84e2-85c6fb5320b1.PNG)

**Comment by talldan** [comment]
I couldn't reproduce the issue, testing with two users:
<img width="277" alt="Screenshot 2021-06-09 at 4 51 42 pm" src="https://user-images.githubusercontent.com/677833/121324146-09d6dc80-c943-11eb-9c62-8cdf8ca90d31.png">

@rodolphebertozzo How many users are on your site? There is some logic that hides the field if there's only one user, and also some logic that changes the field to a combobox for 25 or more users. It also might not display for users without certain capabilities.

**Comment by priethor** [comment]
Let's close this issue as we are unable to replicate and the activity has stalled. Feel free to reopen if the issue resurfaces.
