### ISSUE TITLE
ESLint plugin: improvements to the @wordpress/valid-sprintf rule for placeholders in _n

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#23875]
**Describe the bug**

In some cases, the rule flags missing placeholders in singular form for `_n`.

**To reproduce**

Consider this:

```js
return sprintf(
	/* translators: placeholder is a number. */
	_n(
		'This block will only appear to people who have visited this page more than once.',
		'This block will only appear to people who have visited this page more than %d times.',
		+this.props.attributes.threshold,
		'textdomain'
	),
	this.props.attributes.threshold
);
```

"Once" fits well here, and I think makes sense. Yet the rule returns the following error:

`error  sprintf format string must contain at least one placeholder  @wordpress/valid-sprintf`

**Expected behavior**

In this case, what do you think about relaxing the rule a bit, and check if any (instead of all) args fulfil the rule for `_n` calls?

**Comment by TimothyBJacobs** [comment]
As far I know, using `once` like that is incorrect. In some languages `1` is not the only singular value. For reference: https://core.trac.wordpress.org/ticket/34308

**Comment by swissspidy** [comment]
Yep, that's incorrect usage.

Better would be:

```js
if ( 1 === this.props.attributes.threshold ) {
  return __( 'This block will only appear to people who have visited this page more than once.', 'textdomain' );
}

return sprintf(
	/* translators: placeholder is a number. */
	_n(
		'This block will only appear to people who have visited this page more than %d time.',
		'This block will only appear to people who have visited this page more than %d times.',
		this.props.attributes.threshold,
		'textdomain'
	),
	this.props.attributes.threshold
);
```

Yes, the `This block will only appear to people who have visited this page more than %d time.` form will never be used in English. But it will be used in other languages.

**Comment by jeherve** [comment]
Cool, thank you! Closing this one now then.
