### ISSUE TITLE
Core blocks question

### ISSUE THREAD

**Issue by askel45** [WordPress/gutenberg#23879]
Which topic should I follow to be updated with the progress of when core blocks will support loading CSS conditional loading based on which pages the blocks are used?

**Comment by mtias** [comment]
Hello there. This issue covers that topic: #5445. But note that part of it is already implemented through https://github.com/WordPress/gutenberg/pull/22754

**Comment by askel45** [comment]
#22754 is not for core blocks. I am referring to core blocks. I use Kadence Blocks which already load their scripts conditionally. I use Underscores theme which I have split its stylesheet into different files which load conditionally based on where the CSS is used, but the block editor adds an additional 56KB per page while my CSS files are below 20kb.

**Comment by mtias** [comment]
The issue above is the one to track for core blocks
