### ISSUE TITLE
Image drag and drop broken with Gutenberg 0.7

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2388]
Using Gutenberg 0.7 and latest version of Safari (10.1.2) on latest stable version of macOS Sierra (10.12.6), I can’t drag and drop images inside an image block. The browser displays a warning indicating the page will be change, like this :

<img width="659" alt="capture d ecran 2017-08-12 a 18 25 05" src="https://user-images.githubusercontent.com/2078386/29242358-2781982e-7f8c-11e7-872b-9896f5b47f8e.png">

With previous versions of Gutenberg, it worked perfectly fine.

In the browser console, this error appears when I try to drop a picture inside an image block :

<img width="843" alt="capture d ecran 2017-08-12 a 18 33 03" src="https://user-images.githubusercontent.com/2078386/29242382-cb93bd98-7f8c-11e7-89ce-955b13c604d9.png">

Let me know if you need more informations.

**Comment by mikaelz** [comment]
Could reproduce also in Chrome, not just Safari.

`event.target` at https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L112 is not defined.

![screen shot 2017-08-14 at 06 48 28](https://user-images.githubusercontent.com/454800/29258779-c1a74878-80bc-11e7-8dc4-8744f07b7e10.png)

**Comment by shindevijaykr** [comment]
This is NOT fixed in the latest version as well.
I am using the latest Wordpress 5.1 and still see this issue.

See issue video.

[Gutenberg Image drag issue.zip](https://github.com/WordPress/gutenberg/files/2908605/Gutenberg.Image.drag.issue.zip)
