### ISSUE TITLE
Using Twenty Twenty theme: New Edit image feature creates many duplicates of the existing images.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23884]
**Describe the bug**
Using
**I made a new local test site where I am testing the 5.5 beta 1.
Gutenberg plugin 8.5.1.
Twenty Twenty theme.
Chrome
Desktop Server.**

I uploaded the image Colorful-forest.jpg to the media library.
Twenty Twenty made 8 duplicates.
Original: Colorful-forest which is 2480x2480

Duplicates:
Colorful-forest-150x150
Colorful-forest-300x300
Colorful-forest-768x768
Colorful-forest-1024x1024
Colorful-forest-1200x1200
Colorful-forest-1536x1536
Colorful-forest-1980x1980
Colorful-forest-2048x2048
Total of 9 images.

Editing the image with the new Image Edit tool. Testing the aspect ratio and changing it to 16:9.
<img width="1095" alt="Screen Shot 2020-07-11 at 21 08 54" src="https://user-images.githubusercontent.com/5323259/87231842-c3879f00-c3ba-11ea-9b30-dfe0eacd1120.png">

Clicking Apply.
<img width="1091" alt="Screen Shot 2020-07-11 at 21 10 13" src="https://user-images.githubusercontent.com/5323259/87231870-ee71f300-c3ba-11ea-91d7-06449f20b461.png">

Then checking the uploads folder.
![Screen Shot 2020-07-11 at 21 11 10](https://user-images.githubusercontent.com/5323259/87231887-11040c00-c3bb-11ea-8eef-8c93d08e9e7b.png)

There are now 18 images. 
1 original + the 8 duplicates. 
Editing. 1 edited image + 8 duplicate edit images. Example name: Colorful-forest-edited-300x169.jpg

Total 18 images.

-------------

Editing the edited image. By rotating it.

<img width="1099" alt="Screen Shot 2020-07-11 at 21 13 49" src="https://user-images.githubusercontent.com/5323259/87232299-0e56e600-c3be-11ea-8882-be12b4d552fb.png">

Example name of edit of an edit: Colorful-forest-edited-1-150x150
First the duplicates made by the theme. 8 + 1 original.
Then duplicates made by the first edit. 8 + 1 original.
Then duplicates made by the second edit. 8.
There are now 26 images based on 1 image.

Once again checking the uploads folder.
![Screen Shot 2020-07-11 at 21 14 44](https://user-images.githubusercontent.com/5323259/87232301-12830380-c3be-11ea-9f49-f2b248dac70c.png)

This will easily add a lot of images to any site that uses the new edit image feature in Gutenberg.
What if a user tests out some editing of multiple images. They will easily get hundreds of images based on just a very few images.

**To reproduce**
1. Add a high dimension image that automatically creates a lot of duplicates.
2. Add the image into a Gutenberg page/post.
3. Click to Edit the image and do something for instance adjust the aspect or rotate etc and click apply.
4. Check the uploads folder and how many duplicates have been added.
5. Do 1 through 4 again. Notice again the amount of duplicates have been added to the upload folder.

Now do the same edit procedure with 4-5 images. As a user will easily just play with editing images without even knowing that they are doubling the amount of the original and duplicates images.

**Expected behavior**
When an edited image is being edited again, that in some way the edited images are removed and replaced with the new edited image.

**Comment by paaljoachim** [comment]
I am wondering if it is time to rethink how we handle duplicate images. Perhaps something like this: https://github.com/getdave/wp-intervention

**Comment by TimothyBJacobs** [comment]
As I understand it, this is an intentional design decision, but could potentially be adjusted for 5.5.

cc @azaozz, @ellatrix, @ajlende, @spacedmonkey.

**Comment by azaozz** [comment]
> I am wondering if it is time to rethink how we handle duplicate images.

> Duplicates:
> Colorful-forest-150x150
> Colorful-forest-300x300
> ...

These are not "duplicates", they are sub-sizes that are used in the `srcset` to let the browser pick the right size on the front-end :)

> As a user will easily just play with editing images without even knowing that they are doubling the amount...

That's not the case. There is a change in how edited images are saved. Each edited image is handled separately. That means a new attachment post is created, and the image is shown in the media library. With the previous editor old edited images were not visible in the library (the attachment post was reused). Now if the user edits the same image 5 times, all 5 new images will be visible in the library. Then the user can decide what to keep and what to delete.

This is the "safest possible way", as an image may be edited, then used in a post, then in couple of months edited and used again. If WP deletes the previous edit, the old post will be with missing image. Was thinking WP can delete edited images when edited again whiting few minutes, but then there will be another edge case: a user may edit an image, insert it in the post, then edit it again and insert it again. We can't just delete the first and keep only the second :) Best is if the user can see and decide what to keep.

**Comment by paaljoachim** [comment]
Closing this issue for now.
If someone wants to keep it open, then please reopen.
