### ISSUE TITLE
Text insertion cursor can show up right-aligned

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#23882]
**Describe the bug**
The text caret can show up on the far right when clicking on an empty prompt.

**To reproduce**
1. Type two paragraphs.
2. Erase the first paragraph.
3. Click on the second paragraph.
4. Click on the prompt where the first paragraph was.
5. The caret appears on the right.

**Expected behavior**
The caret appears on the left.

**Screenshots**

![Text caret appearing on the far right](https://user-images.githubusercontent.com/555336/87196099-d8215400-c334-11ea-8431-e02f0e01c1d0.gif)

**Editor version (please complete the following information):**
Current `master` https://github.com/WordPress/gutenberg/commit/56eb4d7ada8c98970cb5658081f9c5b6d507f2cf

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome 83.0.4103.116

**Additional context**

May be related to #18342

**Comment by annezazu** [comment]
Thanks for reporting this @mirka ! I agree that this does seem related to the issue you shared but distinct enough for now to remain open. I'll let others decide if not.

**Comment by talldan** [comment]
Just noting that in Firefox (Mac OS) the result is slightly different and the caret isn't visible on the left or right:
<img width="670" alt="Screenshot 2020-10-05 at 4 47 11 pm" src="https://user-images.githubusercontent.com/677833/95058700-76516a00-072a-11eb-8e63-c2cc1407ad4b.png">

I can reproduce the same issue as the reporter in Chrome.

**Comment by talldan** [comment]
I did some debugging (well, more trial and error) on this issue.

In Firefox the missing caret could be related to the way placeholder text is applied in the block appender. Commenting out the `content: attr(data-rich-text-placeholder);` style makes it work again.

**Comment by tellthemachines** [comment]
I can reproduce this issue in Chrome, but not in Firefox or Safari (although I'm also seeing the same issue as @talldan in Firefox), as far back as 5.4.2. I'm removing it from the 5.6 must haves board as it's not a 5.6 regression.

**Comment by ellatrix** [comment]
Can anyone still reproduce this? I can't in Chrome.

**Comment by mirka** [comment]
Me neither, I don't think I've seen this glitch in a while.
