### ISSUE TITLE
Allow for a user-triggered search in Block Directory

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#23894]
When I was looking for a 'card' block, there wasn't one available on my site and it triggered automatically the Block Directory search. Once the Card block was installed and used on my site, it was always showing up for the 'card' search. But I found this card now a bit limiting and I would want to see what else is in the block directory and find another one, that I previously saw in the list offered. 

For now, a user would need to experiment with the keywords to actually trigger another Block Directory search and that would be quite cumbersome.  Sooner or later the automatic triggers won't cover all use cases. 

I did explored some possible placements for the "Search in Block Directory" link/button 

### 001 Link next to the search box
<img width="401" alt="SearchinBlockDirectory-001" src="https://user-images.githubusercontent.com/39980/87250635-341ed200-c434-11ea-8388-8238bb7b6538.png">
It would be a good place for discovery. It just feels a bit crowded.

### 002 bottom of the search results
<img width="404" alt="SearchinBlockDirectory-002" src="https://user-images.githubusercontent.com/39980/87250659-616b8000-c434-11ea-8fff-6a16c13035c4.png">
That's possible. Still has some issues. Mainly it's too disconnected from the search. 

Also, a link would indicate it'll take a user away and out of the block editor to a different site, and a user might be hesitant to use it for that reason. 

### 003 a button on bottom
<img width="415" alt="SearchinBlockDirectory-003" src="https://user-images.githubusercontent.com/39980/87250681-911a8800-c434-11ea-8fde-762a04f7b894.png">
This placement feels do able and reminded me on the "Browse all" button new to the canvas inserter

### 004 button area on bottom
<img width="410" alt="SearchinBlockDirectory-004" src="https://user-images.githubusercontent.com/39980/87250743-1140ed80-c435-11ea-8ce2-496e799d2b9a.png">
It feels like it was always there, haha... if you like the idea of a user-triggered Block Directory search. 

###005 a black button on the bottom
<img width="414" alt="SearchinBlockDirectory-005" src="https://user-images.githubusercontent.com/39980/87250822-8ca29f00-c435-11ea-8cd3-c5f1c626a798.png">
That last one is just a variation on the background color to be consistent with the "Browse all" button on the other inserter. 

###006 Blue button underneath search box
<img width="415" alt="SearchinBlockDirectory-006" src="https://user-images.githubusercontent.com/39980/87251070-08511b80-c437-11ea-85e7-8302a83bf817.png">
I had second thoughts about the placement on the bottom of the search result, as people might not find it. They might not scroll all the way through the list of results. It looks a bit heavy underneath the search box, but people won't miss it there.... haha. 

Those are just a few possibilities. I like number 006 if we can make it work, and number 005 if we have to go on the bottom. But honestly none of them feel right yet. Maybe I just need to give it time? What do you think?

**Comment by mapk** [comment]
Right on! Thanks for working through this flow, @bph. I do like the black button most because it aligns with the "Browse" button currently used. I put together a prototype to help convey this flow.

**Prototype**
![searchagain](https://user-images.githubusercontent.com/617986/87486188-97089880-c5ef-11ea-8729-57c816355799.gif)

**Mockup**
![Screen Shot 2020-07-14 at 4 36 26 PM](https://user-images.githubusercontent.com/617986/87486498-3ded3480-c5f0-11ea-8600-a1c92c71af8e.png)


### Feedback

Should the "Search Block Directory" button show the block directory blocks below what was already installed and searched for (as I have it in the prototype)? Or should it replace the entire inserter below the tabs as it does when the first search is performed?

**Comment by StevenDufresne** [comment]
Thanks for this!

There were some relevant conversions about this same problem here: 
https://github.com/WordPress/gutenberg/issues/22149

**Comment by bph** [comment]
Thanks @mapk That's a great prototype:-)  I like that the block directory results are displayed underneath already installed blocks that are available for this particular keyword search. Then the user can compare the various preview, if available, and decide if a new block is really better than what they have.

**Comment by bph** [comment]
Interesting discussion #22149 

1. - installed but inactive plugins
2. - blocks that have been disabled via the Block Manager. 

Both scenarios would play out somewhat in the inserter around search results.
They should have a flag and an action button (activate/enable) 

For block Directory to work / show up in the editor, we need to assume that the person using the search does have plugin install privileges.

**Comment by StevenDufresne** [comment]
>I favor. that the block directory results are displayed underneath already installed blocks that are available for this particular keyword search. Then the user can compare the various preview, if available, and decide if a new block is really better than what they have.

I agree. :)

> For block Directory to work / show up in the editor, we need to assume that the person using the search does have plugin install privileges.

Just noting: we check for privileges before we show any Block Directory results but that currently only happens when we don't find any blocks and the search is about to begin.

**Comment by shaunandrews** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/191598/88106793-0f350800-cb74-11ea-9c3d-3210449837a4.png">

I'm not sure this big button pattern works in the context of the sidebar inserter. Perhaps just a simple text-like link, or secondary button would work better.

**Comment by mapk** [comment]
You're right Shaun. A more subtle link would be better. Here's a go.

![Screen Shot 2020-07-21 at 3 20 38 PM](https://user-images.githubusercontent.com/617986/88113025-d55d0500-cb65-11ea-9265-f2afe562e57a.png)

Another thing to explore is what happens if a pattern or reusable block is listed in the results, but no blocks? Is there an automatic block directory search triggered still? If so do we show both the block directory results and the patterns or reusable blocks? Basically something like @shaunandrews [mocked up here](https://github.com/WordPress/gutenberg/issues/22149#issuecomment-662103407).

**Comment by maddisondesigns** [comment]
The ability to be able to search the Block Directory, even if results are returned, would be extremely useful. If I search for 'images' for example, the Block Inserter will simply show me the core image related blocks. What do I do if if I the core blocks aren't suited to my task and I want to explore other options?

I like the solutions proposed by @bph above, but would like to add another suggestion, based on #004. Have the button after the search results, but above the tip, in the block inserter.

![Search-Block-Directory](https://user-images.githubusercontent.com/2078245/92068040-2b6dcb00-ede9-11ea-80a2-8bb39cd36558.jpg)

**Comment by bph** [comment]
I love @maddisondesigns button idea for this. It really feels that not having the button, doesn't contribute well to discovery of more new blocks that are in the WordPress directory. What do you think? Do you have enough to get this into your development queue?  @ryelle @tellyworth

**Comment by ryelle** [comment]
I agree, having a button here would do a lot for discovery. I started [a PR a bit ago](https://github.com/WordPress/gutenberg/pull/25521) which does include a button to load more blocks from the block directory (the design there comes from #22149):

![](https://user-images.githubusercontent.com/541093/93825255-e47a3500-fc32-11ea-82bc-eb4cb6fd412e.png)

I want to revisit that in the next few days, I'll make sure to drop a comment here when it's ready for testing 🙂

**Comment by bph** [comment]
Oh, that's wonderful. Thank you @ryelle - Looking forward to testing this.
