### ISSUE TITLE
Drop down menu: uneven top and bottom spacing

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#23907]
**Describe the bug**
The "dropdown menu" component has uneven top and bottom spacing. See screenshot below:

<img width="651" alt="Screenshot 2020-07-13 at 17 42 05" src="https://user-images.githubusercontent.com/1682452/87324897-0cf9fa80-c531-11ea-832d-9c14e6f44425.png">

It's clear the vertical spacing between the _last_ button and the menu edge is bigger than the one at the top.

Actually, the menu container does have the same padding for all edges.

Instead, all the buttons within the menu had a bottom margin of 4 pixels. The margin of the last button should be reset to 0. 

Seems a good first issue that can be fixed with some simple CSS selector.

**Expected behavior**
The menu to have even spacing.

**Editor version (please complete the following information):**
- WordPress version: 5.5 trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Comment by afercia** [comment]
Seems there's also a small inconsistency between similar "dropdown" menus.

See in the screenshot below, where:
- buttons in the block "More rich text controls" menu do have a bottom margin
- button in the block "More options" menu don't

<img width="600" alt="Screenshot 2020-07-15 at 15 25 31" src="https://user-images.githubusercontent.com/1682452/87551367-88ce8100-c6b0-11ea-8902-9b9a8ae36a47.png">

https://github.com/WordPress/gutenberg/blob/7aacd09a832401629d4507b086d7ac3bbbe93e59/packages/components/src/dropdown-menu/style.scss#L11-L17

**Comment by noahshrader** [comment]
@afercia This is a great callout, and something I've noticed myself as well. The second screenshot you provided (without the margins) looks most in line with where it needs to go. I am assigning this to myself to address.

**Comment by allilevine** [comment]
Did #24227 resolve this issue?

**Comment by afercia** [comment]
Seems so. I can't reproduce the issue on lates plugin version 9.0.0. Closing. See screenshot:

<img width="406" alt="Screenshot 2020-09-19 at 16 31 50" src="https://user-images.githubusercontent.com/1682452/93669630-dd69f000-fa95-11ea-87ea-e9b75922d4b9.png">
