### ISSUE TITLE
Shouldn't user-specified colour stay all the time?

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#23914]
As a simple example, let’s say I want to have a black  `#000000` background for the media & text block because I like the look with the particular image.

![1](https://user-images.githubusercontent.com/908665/87335097-a3311f00-c537-11ea-946a-2bd37b26db1e.png)

---

So I added the hex value  `#000000` into the colour picker in the Custom colour option.

![2](https://user-images.githubusercontent.com/908665/87335317-fefba800-c537-11ea-996f-87c2c003b717.png)

---

For this test, I used Twenty Twenty theme that happened to have `#000000` as `Primary`, so the option automatically picks it up and highlights `Primary` as you can see below.

![3](https://user-images.githubusercontent.com/908665/87335706-a2e55380-c538-11ea-884a-d9e89d3d8983.png)

This makes sense and feels clever at first, but I find it a problem because when I switch to a theme that has green as `Primary` colour, the background becomes green...

![4](https://user-images.githubusercontent.com/908665/87415153-a6262100-c5c4-11ea-9d4f-b5f99eb87ebf.png)

If I was a user I would be confused to see the green at the place that I specifically added black before switching the theme. I would expect the black stays all the time even I switch the theme.

If the colour that I added wasn't exactly `#000000`, the option behaves a lot differently — let's say, I chose a slightly different colour `#040404`, the colour would stay after switching to the same theme that has the green as `Primary` because `#040404` wasn't one of the Twenty Twenty theme colours.

![5](https://user-images.githubusercontent.com/908665/87418342-6f9ed500-c5c9-11ea-8608-b53460aa1a90.png)

This is a big difference in outcome with a minor difference and seems to be a confusing experience. 

I can understand the intention, but I’m not sure if this is expected behaviour for the users — if the colour that they add matches with one of the theme colours, the colour will be overridden automatically if the new theme has the same colour name as one of the theme colours. But if the colour doesn’t match with any of the theme colours, it remains as it is after the theme switch.

Shouldn't a user-specified colour remain regardless of the activated theme? Or at least, shouldn't the colour specified by entering the colour value in Custom colours stay all the time?

<img width="257" alt="6" src="https://user-images.githubusercontent.com/908665/87338856-b0510c80-c53d-11ea-92e5-905e3e539c48.png">

It seems counter-intuitive that the user needs to make sure the specific colour is NOT one of the theme colours if they want the colour to stay all the time.

**Comment by mtias** [comment]
This is the problem with using notions like "primary" and "secondary" for palettes. There's no certainty a user is choosing a color for its pseudo-semantics reasons or because they want that color. So theme switches can break the user expectations. That's why I think we should recommend themes to register colors with color names in general (there can be a variation of tone, saturation, lightness, but it'd be still referred to as "red" and make sense).

**Comment by allancole** [comment]
Interesting. I do like more explicit color names but i’m not sure I understand how it would work in practice. 

Going with your example @mtias, if I choose “Red” from the editor palette for my Cover Block background-color, and then switch to a new theme that doesn’t include “Red” as a palette color, what will happen? Will it stay the same Red or just revert back to default? If it stays Red than color names is most definitely the best way to go :-).

**Comment by mtias** [comment]
Core already supplies those so in the case a theme doesn't specify one, it'd fallback behind the scenes to core. (Note that it won't be in the UI as an option, though.)

**Comment by allancole** [comment]
Excellent! 👍
