### ISSUE TITLE
Supporting editor API

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#2391]
Hi,

In the WordPress version 4.8, the new [editor API](https://make.wordpress.org/core/2017/05/20/editor-api-changes-in-4-8/) was introduced to help developers to create editors from JavaScript. Previously, this can be done only by calling `wp_editor()` function in PHP.

This helps a lot in working with the editor from JavaScript. We can transform a textarea into an editor, add buttons or remove them. Of course it supports only TinyMCE.

As the API was just added in version 4.8, I hope this API is considered in Gutenberg. Our team has worked on the new API and it turned out very well. A lot of unnecessary code is removed and the whole project looks cleaner.

**Comment by mtias** [comment]
This is a different editor and would offer different ways of reusing as distinct modules.
