### ISSUE TITLE
Edited classic block content removed when switching to Code Editor

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#23924]
**Describe the bug**
Any content added to the classic block seems to be deleted when switching to the Code Editor view.

**To reproduce**
1. Add a classic block and type in it
2. Click on the Code Editor view
3. Observe that classic block content is removed

**Expected behavior**
Classic block content is retained

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg version: 8.5.1

**Comment by ntsekouras** [comment]
This happens when you generally change the `Classic` block's content. If there is content and you just switch modes, the content is shown properly.

**Comment by talldan** [comment]
Thanks for the clarification @ntsekouras 👍
