### ISSUE TITLE
Navigation screen: Add support for advanced block properties

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23934]
As a continuation for #23731 this issue is about adding support in the navigation screen for an inspector or another way of customizing block properties. It is important that we have this option here since now the navigation block supports more block types and some of these have their settings accessible via the inspector only.

One of the challenges is that we already have the fixed navigator sidebar, so adding the inspector will constrain available space for visual menu building.

**Comment by shaunandrews** [comment]
I think we might want to consider adding the sidebar (like from the `Interface` package), but if we don't we could also add a button elsewhere in the UI and show the block settings in a popover:

![block-inspector](https://user-images.githubusercontent.com/191598/90291902-d58fae00-de4e-11ea-9241-b8221211c66b.gif)
