### ISSUE TITLE
RangeControl component doesn't adapt to the selected color scheme.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#23932]
I'm using the "modern" color scheme on my WordPress install and it seems this component doesn't adapt properly.

<img width="268" alt="Capture d’écran 2020-07-14 à 4 20 42 PM" src="https://user-images.githubusercontent.com/272444/87444072-39278100-c5ee-11ea-9ce2-e273c7a71b46.png">

I wonder if it's an issue for the components written using CSS in JS. They don't apply the CSS variables properly.

cc @ItsJonQ @jasmussen

**Comment by ItsJonQ** [comment]
@youknowriad The `RangeControl` uses various `wordpress.blue` color values. I've noticed that there's been an update to add `var(--wp-admin-theme-color)` in places. Is that the colour that should be absorbed? If so, I can make that update :)

**Comment by youknowriad** [comment]
yes, that's the one. There are some "darker/lighter" alternatives too but ideally, a single color should be enough.
