### ISSUE TITLE
Tracking Mobile E2E failures on Github Action CI

### ISSUE THREAD

**Issue by cameronvoell** [WordPress/gutenberg#23949]
**Describe the bug**
Following the Monorepo effort for making the native mobile version of Gutenberg available in the gutenberg repo, we added [Android](https://github.com/WordPress/gutenberg/blob/master/.github/workflows/rnmobile-android-runner.yml) and [iOS](https://github.com/WordPress/gutenberg/blob/master/.github/workflows/rnmobile-ios-runner.yml) Github actions to continuous integration on pull requests for catching issues. 

<img width="851" alt="Screen Shot 2020-07-14 at 10 33 34 PM" src="https://user-images.githubusercontent.com/1103838/87507343-1c0ca580-c622-11ea-835a-1fec3d800b39.png">

This Issue is for tracking any (hopefully rare) randomly occurring issues on those CI jobs so that the tests are reliable. If you see a failure on a mobile E2E test that is not related to changes in a PR, please add a comment below.

If known random failures that occur a meaninful amount of time are all fixed, this issue will be closed and any future issues can be resolved individually. 

Link to recent Android Failures: https://github.com/WordPress/gutenberg/actions?query=workflow%3A%22React+Native+E2E+Tests+%28Android%29%22+is%3Afailure

Link to recent iOS Failures: https://github.com/WordPress/gutenberg/actions?query=workflow%3A%22React+Native+E2E+Tests+%28iOS%29%22+is%3Afailure

**Comment by jordesign** [comment]
Checking through some older issues and wanted to check if this is still relevant?

**Comment by guarani** [comment]
👋 @dcalhoun, do you happen to have an answer to this one? I'm no longer on this project but I'm still subscribed to this issue. @\cameronvoell isn't working on this anymore either.

**Comment by dcalhoun** [comment]
Thanks for the ping, @Guarani. 

My perception is that no one actively considers this issue or its focus. Therefore, I do not believe its presence brings value and I closed it. If anyone disagrees, please feel free to reopen the issue. 

@WordPress/native-mobile moving forward, we could consider automating flaky test tracking, similar to the web project's [`packages/report-flaky-tests`](https://github.com/WordPress/gutenberg/tree/1d8202421dfcef6e46990f544a1751c34f303a69/packages/report-flaky-tests).
