### ISSUE TITLE
Full site editor issues

### ISSUE THREAD

**Issue by quadlayers** [WordPress/gutenberg#23957]
Hello guys

I'm experiencing some issues with the full site editor

**Describe the bug**
When the site editor is activated the loading message never ends
https://snipboard.io/tuboDQ.jpg
I see these errors in the logs

- include(wamplangues/index_english.php): failed to open stream: No such file or directory in C:\wamp64\www\index.php on line 91
- 1. {main}() C:\wamp64\www\index.php:0
-  Undefined variable: langues in C:\wamp64\www\index.php on line 104

**To reproduce**
1. Install Gutenberg 8.5.1
2. Go to Gutebenberg / Experiments
3. Activate full site editor -> https://snipboard.io/YowgRI.jpg
4. Go to full site editor

**Comment by quadlayers** [comment]
I'm using wamp64 in localhost
The site is under the folder C:\wamp64\www\test
The error logs are from the files in wamp root directory C:\wamp64\www\

**Comment by ehti** [comment]
Hi!

You'd need to "Enable Full Site Editing demo templates" for them to show up (under Gutenberg > Experiments).

You can also install a theme that uses block templates/supports Full Site Editing, like Twenty Twenty-Blocks: https://github.com/WordPress/theme-experiments/tree/master/twentytwenty-blocks 

Cheers
