### ISSUE TITLE
Can't make the last word a link and continue typing

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#2395]
## Issue Overview

If you make the last word of a block of text a link, you can't continue typing in the block without what you type being a link.

## Steps to Reproduce (for bugs)

In Chrome 60:

1. Start a new post
2. In a new text block, type "this is a link"
3. Double click the word "link"
4. Click the link button
5. Type in a valid url, and press enter or click the enter icon
6. Click back in the text block to try to make the URL input disappear
7. Try pressing escape, clicking out of the block and clicking inside the block to get the URL input to disappear
8. Try typing more text to try to make the URL input disappear

## Expected Behavior

After entering the URL and pressing enter, I should be able to continue typing.
I should be able to click in the text block after the link and be able to continue typing.

## Current Behavior

Everything I type becomes part of the link. Even if I press enter to start a new block, then press backspace to go back to the existing block, I'm still editing the link text.

![link editing](https://user-images.githubusercontent.com/3314354/29266156-9e9e942a-80db-11e7-8d55-9eb348735c24.gif)

**Comment by youknowriad** [comment]
duplicate #1246
