### ISSUE TITLE
Method to determine when media library is open

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#23963]
I am looking for a way to determine if the media library is open in the block editor. 

The problem I am running into is that I have a custom block that has both an image and link. I am using the `MediaReplaceFlow` to manage the image data. I am using a `Popover` to display the link editing tools when the block is selected (using the `isSelected` prop).

The issue is that the `Popover` displays above the media library popover. If there is a way to detect when the media library is being displayed, I can automatically hide the `Popover`.

**Comment by talldan** [comment]
@philbuchanan There isn't really a method to achieve this through any Gutenberg API. 

The media library is part of WordPress Core and written in backbone, and it's unfortunately not very well documented.

Probably your best option is to query the DOM and check for the element, though it looks like the element is set to `display: none` when closed, and there's also a bug where every block spawns a separate media library element.

I think something like this may work, but I haven't tested it:
```js
const isMediaModalOpen = some( document.querySelectorAll( 'media-modal' ), ( modalElement ) => modalElement.parent.style.display !== 'none' );
```
