### ISSUE TITLE
Blocks in Customizer: Adjust design of UI for single block area

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#23977]
**Is your feature request related to a problem? Please describe.**
Currently the widget-blocks experimental section in the Customizer shows all block areas at one time. This is being addressed in https://github.com/WordPress/gutenberg/issues/23975, but I found the design of a single block area still needs revision as well. This issue is to address the design of a single block area.

### Current

![Screen Shot 2020-07-15 at 5 07 43 PM](https://user-images.githubusercontent.com/617986/87611783-c38ae600-c6bd-11ea-9192-7b07560a10d8.png)

### Proposed Design
This design is based on initial design, but wasn't implemented yet in development.

**Prototype**

![slideout](https://user-images.githubusercontent.com/617986/87611817-d9001000-c6bd-11ea-9df3-4c7efe6878a8.gif)

**Mockup**

![Frame 5](https://user-images.githubusercontent.com/617986/87611873-fb922900-c6bd-11ea-8611-62061cda2c03.png)

**NOTES**

1. There should be a single block area noted in the Customizer header.
2. The editable area should fill the Customizer width and height. This means no gray empty space surrounding the editor.

Related: https://github.com/WordPress/gutenberg/issues/16606 and https://github.com/WordPress/gutenberg/issues/23975

**Comment by adamziel** [comment]
Blocked by https://github.com/WordPress/gutenberg/issues/25625

**Comment by noisysocks** [comment]
Closing this as we will be completely rearchitecting our implementation of how blocks work in the Customiser along the lines of https://github.com/WordPress/gutenberg/issues/26900.
