### ISSUE TITLE
Blocks in Customizer: Current flow is incorrect

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#23975]
**Is your feature request related to a problem? Please describe.**
Similarly to how widgets currently work in the Customizer, the experimental widget-blocks should also work. The widgets require two clicks to get into an individual widget area. When I click "Widgets" I get another menu showing the available widget areas. I click on one of those and then can start adding in widgets to that one area.

When I click on the experimental widget-blocks, it is one click to see both widget-block areas as accordions. I really think there should be another click to get into the individual widget-block area. 

**Screencast**

![widgets](https://user-images.githubusercontent.com/617986/87610149-60975000-c6b9-11ea-8417-aab34ded6bad.gif)

**Expectations**
I expect, when clicking into "Widget-blocks (experimental)" to see another slideout menu that displays each widget area.

**Comment by mapk** [comment]
Related: https://github.com/WordPress/gutenberg/issues/16606

**Comment by draganescu** [comment]
This flow makes less sense with the adoption of the single post for all areas editor. It was a good idea if we also were able to select one area in the editor as well. Should we close this?

**Comment by mapk** [comment]
I think it can still make sense here just as it does today (without Gutenberg). The Classic widget screen showed multiple widget areas, but when navigating in the Customizer, the user would select a particular widget area as above.

This works better for such a small, narrow space and provides more focus on the immediate area.

**Comment by adamziel** [comment]
Blocked by https://github.com/WordPress/gutenberg/issues/25625

**Comment by noisysocks** [comment]
Closing this as we will be completely rearchitecting our implementation of how blocks work in the Customiser. Also worth noting that this specific design detail was discussed in https://github.com/WordPress/gutenberg/issues/26900.
