### ISSUE TITLE
Link to Attributes page in block API has been lost from documentation

### ISSUE THREAD

**Issue by daledesilva** [WordPress/gutenberg#23978]
**Describe the bug**

**To reproduce**
1. Go to the [API Reference contents](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/README.md) in github.
2. Click on 'Attributes'
3. Go to the [API Reference contents](https://developer.wordpress.org/block-editor/developers/block-api/) on developer.wordpress.org
4. Click on 'Attributes'

Both contents pages come from the same github file but for some reason the one on the wordpress front end is mislinked to a different file. [This is the file](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/create-block/block-attributes.md) in github it's mistakenly linking to.

**Expected behavior**
The Attributes link on the API Reference contents page shown in wordpress should link to the Attributes page inside the API Reference folder, not in the tutorials folder.

**Additional context**
- This issue appeared in the last 24 hours of me posting this.

**Comment by talldan** [comment]
@daledesilva I'm not able to reproduce that. For me it links to https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/ on the developer.wordpress.org site.

Not sure if it could be a caching issue for one of us.

**Comment by daledesilva** [comment]
Thanks @talldan . I've cleared cache and tried in a an incognito window but it's definitely happening.

Both pages have a title of _Block Attributes_ (or _Attributes_) but they're not the same page - It makes it a little easy to miss.

Another way to see the error is...

1. Go to the link you posted.
2. Note that the menu and breadcrumb trail say that it is in the **Block API reference** section.
3. Now click on the _Edit_ button next to the title to go to its github page.
4. Note that the breadcrumb trail in github indicates it is actually a page from **tutorials/create-block/**, not from the _Block API reference_ section.

If this doesn't clarify, please post a screenshot of what you see after step 2 and step 4 in my first post.

**Comment by talldan** [comment]
Ah, yes, you're right. 

My bad, I wasn't looking at the page contents, just at the URL and breadcrumb.

**Comment by talldan** [comment]
The link looks like it goes to the right place, but it seems as thought the block-api/block-attributes page has possibly been overwritten when the docs were built, maybe because the two pages have the same slug in the manifest:
- https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json#L106
- https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json#L544

Probably an easy fix, so I'll label this a good first issue.

**Comment by donald-knieriem-temple** [comment]
Hi all, it appears there is a duplicate slug for block-attributes in the [docs manifest](https://github.com/WordPress/gutenberg/blob/5cef528f3d26f3a1b5cb7a4fa2d0104bb0a23de0/docs/manifest.json)

[The first](https://github.com/WordPress/gutenberg/blob/bd4a6b74a2109e9c63a4221891029a8cbdd95511/docs/manifest.json#L106) is the correct page for the [blocks API documentation](https://developer.wordpress.org/block-editor/developers/block-api/) Blocks Attributes page

[The second](https://github.com/WordPress/gutenberg/blob/5cef528f3d26f3a1b5cb7a4fa2d0104bb0a23de0/docs/manifest.json#L550) is from the ["Create Blocks" Tutorial ](https://developer.wordpress.org/block-editor/tutorials/create-block/)

I would love to help out, but I'm not sure how these slugs are generated

**Comment by dknieriem** [comment]
Hi all, it appears there is a duplicate slug for block-attributes in the [docs manifest](https://github.com/WordPress/gutenberg/blob/5cef528f3d26f3a1b5cb7a4fa2d0104bb0a23de0/docs/manifest.json)

- https://github.com/WordPress/gutenberg/blob/bd4a6b74a2109e9c63a4221891029a8cbdd95511/docs/manifest.json#L106
- https://github.com/WordPress/gutenberg/blob/5cef528f3d26f3a1b5cb7a4fa2d0104bb0a23de0/docs/manifest.json#L550

I'll make the slugs unique and submit a pull request
