### ISSUE TITLE
Button block: Color picked from the color palette don’t change the button’s color inside the editor (WP 5.5 beta2)

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#23987]
**Steps to reproduce**

1. Inside the editor, insert a button.
2. Change its background/text color by clicking on one of the color preset.
3. Observe that the button’s color isn’t changed.

![button-color](https://user-images.githubusercontent.com/44895380/87649721-f336fe00-c750-11ea-807e-c4c325acbd8c.gif)

Tried with Twenty Twenty, Twenty Nineteen & Gutenberg starter theme.
Tested using WordPress 5.5 beta 2 and WP 5.4.2 + Gutenberg 8.5.1.

**Comment by nickcernis** [comment]
This is also true in WordPress beta 3.

@youknowriad This seems to relate to the work done in https://github.com/WordPress/gutenberg/pull/22356/files but I haven't dug into it yet.
