### ISSUE TITLE
Cover block: Impossible to reset the minimum height value (WP 5.5 beta2)

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#23988]
**Steps to reproduce**

1. Insert a Cover block.
2. Set a minimum height: e.g. type 500 (px).
3. Delete the value that you’ve just typed to reset the minimum height.
4. Unselect the block.
5. Reselect the block to view its settings.
6. Observe that the minimum height text field isn’t empty.

![cover](https://user-images.githubusercontent.com/44895380/87650172-87a16080-c751-11ea-9c12-01d3dce03d8a.gif)

Tested using WordPress 5.5 beta 2 and WP 5.4.2 + Gutenberg 8.5.1.
This bug wasn’t inside WordPress 5.4.2.

**Comment by annezazu** [comment]
I was able to replicate this with WordPress 5.5 RC and Gutenberg 8.6.1. Removing the needs-testing label! Thanks for reporting @dianeco ❤️
