### ISSUE TITLE
Block move up/down buttons too small - too easy to move the wrong way

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#23983]
**Describe the bug**
More often than not, when attempting to move a block up by clicking on the Up arrow it moves the other way. I noticed this myself and mentioned it during the Manchester WordPress User Group’s meetup. Mike Little agreed and commented that the hand icon obscured the up / down icon we were trying to click. 

As an aside, other users have had quite different problems.
Some users of the heading block think the buttons are there to increase or decrease the heading level. 

**To reproduce**
1. Think about moving a block
2. Position mouse pointer as if you were going to move the block upwards
3. Click
4. See the block move the other way.

**Expected behavior**
It should be a lot easier to know which way the block will move. 

**Screenshots**
See Andrew's screenshot below https://github.com/WordPress/gutenberg/issues/23983#issuecomment-659466794

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]. Gutenberg
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 8.5

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
See also #23667

**Comment by AndrewMLeonard** [comment]
![image](https://user-images.githubusercontent.com/61053640/87686332-496d6680-c77c-11ea-93d1-c3d74b15aa19.png)
Here is a screen shot of the problem captured using Zoom on Herb's (Bobbingwide) screen

**Comment by ntsekouras** [comment]
Thanks for reporting this @bobbingwide! I can confirm it's a bug.
