### ISSUE TITLE
Accessibility regression: The "Remove tag" buttons focus style is cut-off

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#23992]
**Describe the bug**

In WordPress 5.5 Beta 2, the focus style of the "Remove tag" buttons is cut-off. 

Also, the tooltip that appears on hover / focus now partially hides the focus style.

Screenshots:

WordPress 5.5 Beta 2:

<img width="318" alt="Screenshot 2020-07-16 at 14 58 48" src="https://user-images.githubusercontent.com/1682452/87677195-c4814d80-c779-11ea-8aba-94bb9af7cc60.png">

WordPress 5.4: the focus style is fully visible:

<img width="318" alt="Screenshot 2020-07-16 at 15 26 29" src="https://user-images.githubusercontent.com/1682452/87677243-d4009680-c779-11ea-99a5-75d062a6a039.png">

**Comment by mapk** [comment]
I can confirm this issue.

![Screen Shot 2020-08-18 at 9 14 50 AM](https://user-images.githubusercontent.com/617986/90539620-ed0fb500-e134-11ea-99fe-21e41c3ac108.png)

Thanks, @noahshrader for picking it up. 😄
