### ISSUE TITLE
Site Title Block changes not saving

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24003]
**Describe the bug**
When updating the Site Title block in Full Site Editing, the changes don't save. 

**To reproduce**
1. Enable Full Site Editing and the demo content.
2. Head to Site Editor (beta) tab.
3. Edit the Site Title block
4. Select "Update Design"
5. Site title reverts back and changes aren't saved. 

**Expected behavior**

I expected the site title block to properly save the changes.

**Screenshots**

Video for good measure (30s): https://cloudup.com/cL4cQ7FnXfp

![rename](https://user-images.githubusercontent.com/26996883/87706875-0ea40800-c755-11ea-867b-953df6e64b70.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by jeyip** [comment]
I can reproduce this in all browsers in production and in the wpcom sandbox. 👍
