### ISSUE TITLE
Gutenberg adds duplicate instance of child block automatically

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#24016]
**Describe the bug**
I am not sure if this is actually a bug. I am building a custom Gutenberg block which has two child blocks.
- Parent Block
-- Child Block 1
-- Child Block 2

The `Child Block 1` is supposed to be placed only once into the parent block. So I have used the following:

```
supports: {
   multiple: false
}
```
The above restriction works fine and I am not able to place the block again in the same parent block.

However, I am having this issue. When I place the `Child Block 1` inside `Parent Block`, `Child Block 1` becomes disabled and I cannot place it any more, which is perfectly OK and works as desired. But, the problem is Gutenberg is adding another instance of `Child Block 1` automatically with the first instance. What is the reason behind this?

**About the blocks**
Parent Block: Allows `myblock/child-block-1` and `myblock/child-block-2`
Child Block 1: Allows: 'core/list'
Child Block 2: Allows: 'core/paragraph', 'core/image', 'core/list'

**Placement**
- Select Parent Block
- Select Child Block 1 - The block is placed and a duplicate instance is created automatically which should be there.
- Select Child Block 2 - The block is placed and a duplicate instance is created similarly as above.

**Expected behaviour**
Only one block should be placed and **duplicate instance should not come up automatically**.

**Screenshots**
Not available

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? Not Applicable

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser Chrome
 - Version 84

**Smartphone (please complete the following information):**
Not Applicable

**Comment by talldan** [comment]
Hi @emfluenceindia, apologies for the slow reply. Would you be able to provide a minimal code example for the blocks to help a developer replicate/debug this behavior? Thanks.

**Comment by emfluenceindia** [comment]
Thank you for your reply @talldan. Please allow me a couple of days to prepare the same.

**Comment by talldan** [comment]
Closing due to no follow-up from the reporter
