### ISSUE TITLE
The default editor styles are loaded after the core blocks' editor styles

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#24011]
## Description
The styles in [packages/editor/src/editor-styles.scss](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/editor-styles.scss) are loaded after [packages/block-library/src/editor.scss](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/editor.scss). I would expect them to be loaded before.

Because of the editor style wrapping that currently happens, style rules like `ul` become `.editor-styles-wrapper ul`, which has a specificity of 0-1-1, and so even a style rule in a core block's `editor.scss` like `ul.has-background` (which has the same specificity) will be overridden, because the default editor styles are applied after.

I discovered this issue while working on #21387, where I ran into the exact scenario described in the previous paragraph.

## Expected behavior
The editor styles provided by the core blocks would be applied after the default editor styles, not before.

## Environment
- WordPress 5.4.2
- Gutenberg plugin 8.5.1

**Comment by skorasaurus** [comment]
Is this a duplicate of https://github.com/WordPress/gutenberg/issues/21785 ?

**Comment by ZebulanStanphill** [comment]
@skorasaurus Yeah, it's a duplicate of #21785. I must have forgotten I made the earlier issue. Thanks for pointing it out.
