### ISSUE TITLE
Deeleting block at insert time, removes previous block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#24018]
**Describe the bug**
For some reason, pressing backspace when inserting a block removes the previous block. Probably while inserting the selection does not get updated.

**To reproduce**
1. Add a post
2. Add a block, set it up
3. Start inserting a block using the slash inserter, press ESC, press BACKSPACE
4. Observe block created at (2) is gone.

**Expected behavior**
I would expect to not lose something which is not selected.

**Screenshots**

![deleteRemovesWrongBlock](https://user-images.githubusercontent.com/107534/87775322-93af2000-c82e-11ea-8c79-a1e650cb084f.gif)

**Comment by ocean90** [comment]
Is this still an issue after #23808/#23901?

**Comment by draganescu** [comment]
No @ocean90 closing!
