### ISSUE TITLE
Accessibility regression: The block contenteditable aria-multiline value is now an empty string

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#24034]
**Describe the bug**

See https://github.com/WordPress/gutenberg/issues/19124#issuecomment-660495138

In https://github.com/WordPress/gutenberg/pull/23132 the default value for the `aria-multiline` attribute set to the blocks `contenteditable` was changed to empty string.

This attribute needs an explicit `true` string value so that is rendered as `aria-multiline="true"`. This was discussed long time ago, as there was some overlapping in the way the related prop was used. The issue was clarified at WordCamp US Nashville 2017. The implementation is now changed, not sure why.

Worth reminding once again that this attribute is only meant to be used for assistive technologies. Amongst other things, a `true` value allows screen readers to differentiate between a `textbox` role meant as equivalent of an input field, and a `textbox` role that needs to be perceived as a textarea element instead.

More details: https://www.w3.org/TR/wai-aria-1.1/#aria-multiline

Screenshots to clarify, testing with Safari + VoiceOver:

With an empty value `aria-multiline=""`, the block is announced as "text field":

<img width="949" alt="text field" src="https://user-images.githubusercontent.com/1682452/87855811-0990b580-c91b-11ea-90f7-0fae47fec60c.png">

With a value `aria-multiline="true"`, the block is announced as "textarea":

<img width="958" alt="text area" src="https://user-images.githubusercontent.com/1682452/87855814-0e556980-c91b-11ea-8c40-7b6c8227d38f.png">

I'm not sure if the related prop is still used internally also for other purposes. Regardless, what is needed for accessibility is that all the contenteditable elements (with the exceptions that were already implemented before the recent refactoring) have a non-empty `aria-multiline` attribute. The value needs to be set to `true`.

/Cc @ellatrix @youknowriad

**Comment by ellatrix** [comment]
Thanks for the report! Seems to have been removed accidentally.
