### ISSUE TITLE
[Documentation] Screenshot and explanation of Block Validation failure are old.

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#24032]
**Describe the bug**

Article [Edit and Save](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-edit-save.md) includes old screenshot and explanation of block validation failure.  
It should be synchronized with the current implementation as below:

<img alt="block-validation-error-1" src="https://user-images.githubusercontent.com/8876600/87852796-0825b400-c940-11ea-9a23-ba5e1f59d3b7.png">

**Comment by skorasaurus** [comment]
fixed inhttps://github.com/WordPress/gutenberg/pull/24033
