### ISSUE TITLE
Tooltip: Blinks on side buttons

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2403]
![aug-14-2017 15-27-20](https://user-images.githubusercontent.com/1204802/29273573-15c24d66-8105-11e7-830d-7425a2a27e35.gif)

Probably this is due to the hit area being on the SVG shape itself, instead of on the `a` hit area.

**Comment by aduth** [comment]
Are you seeing this on the latest master? This should have been fixed with #2366.

**Comment by jasmussen** [comment]
My apologies, you're right. This was on a branch.
