### ISSUE TITLE
Nav block: Block in the Inserter don't have equal padding

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24078]
**Describe the bug**
When clicking the Inserter `+` icon in the Navigation block, the blocks do not have equal padding within the popover. The padding should be adjusted.

**Screenshots**

**Current**

![insert-nav](https://user-images.githubusercontent.com/617986/87986025-6dd58580-ca91-11ea-94cb-b410b337e2b3.gif)

**Proposed Design**

![Screen Shot 2020-07-20 at 2 01 35 PM](https://user-images.githubusercontent.com/617986/87986134-8ba2ea80-ca91-11ea-8bde-b9df015e50f3.png)

**Comment by fabiankaegy** [comment]
Closing this issue since it a fix has been merged and approved by @mapk himself.
