### ISSUE TITLE
Moving a Sandbox component for HTML rendering and my own plugin seem to break when descending, but not ascending...

### ISSUE THREAD

**Issue by Lewiscowles1986** [WordPress/gutenberg#24093]
**Describe the bug**

When moving elements using SandBox below other elements, the contents of the iframe seem to disappear.

The really odd thing is that if you promote them towards the top this does not happen.

Also using react dev tools chrome extension I was able to look into state and find that the props are all passed to the sandbox component.

**To reproduce**

1. Using vanilla wordpress 5.4.2 with no plugins and the 2020 theme
2. Create a new post, or edit an existing one
3. Add some dummy blocks
4. Add a HTML block, with valid HTML
5. Select Preview option (does not happen outside of preview)
5. Promote that block towards the top of the page using the movement cursor handles or drag & drop
6. move it down. _Does not matter if using movement cursor handles, or drag & drop_

**Expected behavior**

Ideal HTML preserved

Less than ideal, the block to switch from `Preview`, to `HTML`, which would work-around the issue.

**Screenshots**

![Screenshot (2012)](https://user-images.githubusercontent.com/2605791/88055540-14378e80-cb57-11ea-9f41-458096b645b8.png)
![Screenshot (2013)](https://user-images.githubusercontent.com/2605791/88055542-14d02500-cb57-11ea-9736-ef5d780129a1.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser Chrome
 - Version Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

None I can think of.

**Comment by Lewiscowles1986** [comment]
This does not happen in the Storybook viewer when downloading and running Gutenberg. I may need to close this out and re-point at WordPress itself without a minimal replicable case outside of WordPress itself.

**Comment by talldan** [comment]
@Lewiscowles1986 I couldn't reproduce this, though I'm on Mac OS, so it could be platform specific. 

I was also testing using WordPress 5.5. Is it something you're still experiencing.

**Comment by Lewiscowles1986** [comment]
Hi @talldan 

Verified this AM on 5.4 on a mac, upgrade to 5.5 fixed, so whatever worked, I'm happy 🎉 

I am noticing the cursor / block toolbar looks a little different. Perhaps it was re-worked.

Thank you

**Comment by Lewiscowles1986** [comment]
I've also noticed the sandbox overlay when inactive has a short-refresh, and is now also working and preventing interaction for selection prior to the block being selected. Wins all round
