### ISSUE TITLE
Video information is not saved when adding URL via core/video block in a custom block

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#24108]
**Describe the bug**
I am building a custom block. I added `core/video` as one of the Allowed Blocks. When I place this block and add a Youtube URL nothing seems to happen. In the frontend, the video is not there at all. I checked the database and the video information was not there. Below is the saved HTML. The section `<figure class="wp-block-video"></figure>` has nothing inside. However, contents from other blocks like `core/paragraph` or components like `RichText` are saved OK.

```
<!-- wp:emfl/tab-control -->
<div class="wp-block-emfl-tab-control"><div class="guten-tab-holder"><!-- wp:emfl/tab-strip -->
<div class="wp-block-emfl-tab-strip"><div class="guten-tab-items"><!-- wp:list -->
<ul><li>Video</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:emfl/tab-strip -->

<!-- wp:emfl/tab-content {"textContent":"Some sample test to complement the heading above"} -->
<div class="wp-block-emfl-tab-content"><div class="guten-tab-content"><h3>Some Heading</h3><div>Some sample test to complement the heading above</div><!-- wp:video -->
<figure class="wp-block-video"></figure>
<!-- /wp:video --></div></div>
<!-- /wp:emfl/tab-content --></div></div>
<!-- /wp:emfl/tab-control -->
```
**Code Snippets**
Edit function:

```
edit: (props) => {

            const contentHeading = props.attributes.contentHeading;
            const textContent = props.attributes.textContent;

            function onChangeTextContent(content) {
                props.setAttributes({textContent: content});
            }

            function onChangeHeading(heading) {
                props.setAttributes({contentHeading: heading});
            }

            return (
                <div className={props.className}>
                    <div>
                        <RichText
                            TagName="h3"
                            value={contentHeading}
                            onChange={onChangeHeading}
                            placeholder={__('Add a heading (optional).')}
                        />
                        <RichText
                            TagName="div"
                            value={textContent}
                            onChange={onChangeTextContent}
                            placeholder={__('Add some text')}
                        />
                        <InnerBlocks allowedBlocks={['core/paragraph', 'core/shortcode', 'core/video', 'core/list', 'core/image']}/>
                    </div>
                </div>
            );
        }
```

Save function:
```
save: (props) => {
            return (
                <div className={props.className}>
                    <div className="guten-tab-content">
                        {props.attributes.contentHeading ?
                            <RichText.Content tagName="h3" value={props.attributes.contentHeading}/> : ""}
                        {props.attributes.textContent ?
                            <RichText.Content tagName="div" value={props.attributes.textContent}/> : ""}
                        <InnerBlocks.Content/>
                    </div>
                </div>
            );
        }
```

**To reproduce**
Currently, the development is underway and it is on my local development server.

**Expected behavior**
The video information should go into the database and render it on the frontend.

**Screenshots**

**The editor:**
![editor](https://user-images.githubusercontent.com/11072678/88141378-22e27c00-cc11-11ea-8424-5b13fe1942b7.png)

**Frontend:**
![frontend](https://user-images.githubusercontent.com/11072678/88141398-2bd34d80-cc11-11ea-90e2-1df75f53d556.png)

**Inspector output:**
![inspector](https://user-images.githubusercontent.com/11072678/88141554-781e8d80-cc11-11ea-954c-3dc1d2e09d69.png)

**Editor version (please complete the following information):**
- WordPress version: **5.4.2**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Default**
- If the Gutenberg plugin is installed, which version is it? **N/A**

**Desktop (please complete the following information):**
 - OS: Ubuntu **16.04 LTS**
 - Browser: **Chrome**
 - Version: **83**

**Smartphone (please complete the following information):**
 - Device: **N/A**
 - OS: **N/A**
 - Browser: **N/A**
 - Version: **N/A**

**Additional Information**
I already looked into [#19311](https://github.com/WordPress/gutenberg/issues/19311#issue-541875999) but since I am not getting the console error mentioned here and no real conversation is going on there I have decided to open a new one. It looks like I am not the only one having this issue. Please let me know what I am doing wrong!

**Comment by janeschindler** [comment]
I am also having this problem.

**Comment by jordesign** [comment]
Hi @emfluenceindia @janeschindler Just looping back to this older issue - is this something you're still seeing taking place?

**Comment by jordesign** [comment]
With no further comments or movement on this, I will close the issue.

If it is still a problem - a new issue can be opened with updated details on how to reproduce.
