### ISSUE TITLE
Cover Block: How I can disable the content position again?

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#24102]
Hey, 

if I use the content position matrix control to change the alignment of the cover block content, how I can disable the current position again? The cover block start with no additional "is-position-xy" class. After change the content position, a "is-position-xy" class was added. But how I can remove that, to switch to the start point without the "is-position-xy" class?

<img width="311" alt="Bildschirmfoto 2020-07-21 um 22 12 55" src="https://user-images.githubusercontent.com/31563167/88102132-5a184500-cb9f-11ea-9f6a-a2d7437bb06b.png">

**Comment by talldan** [comment]
Confirmed that the block reverts to `is-position-center-center`, it does seem like it should be possible to default to no additional class.

**Comment by CreativeDive** [comment]
@talldan I can see this was changed with the latest 8.6 version to a default value "center center".

**Comment by CreativeDive** [comment]
@talldan Now the default value is "center center", but at the frontend there is no default `is-position-center-center` class name found.

To solve this issue, the cover block should be contains the default class `is-position-center-center`, if there are no manually changes on the content alignment.

**Comment by talldan** [comment]
@CreativeDive I think this is something we disagree on, I don't it should add a class at all when the position is at it's default.

Otherwise the block ends up with a lot of unnecessary classes.

**Comment by CreativeDive** [comment]
@talldan I can not understand your opinion. The block contains the class "`is-position-center-center`" if I selected that. But if the block is positioned centered by default without manual selection, then it doesn't have the class? This is really inconsistent and can lead to display issues if the theme developer set CSS formatting for "`is-position-center-center`", but the cover block does not contain this class at the default start without manually select the centered position.

**Comment by talldan** [comment]
@CreativeDive The best I can explain it is that the default center option should be like there's no selected option, so therefore there should be no class added.

I think that's consistent with how other options work in the editor, for example if you re-select the default font size in a paragraph block, there's no class `has-default-font-size` added.

**Comment by CreativeDive** [comment]
@talldan Ok, I can understand this. But why the selected center center position get the class name `is-position-center-center`? This is really inconsistent and can lead to display issues if the theme developer set CSS formatting for "is-position-center-center".

The best practice would be, to add no additional class `is-position-center-center` in the case of position center center. This would be consistent and avoid future issues in designing themes.

**Comment by CreativeDive** [comment]
@talldan There are two ways to make this consistent.

1. A `is-position-center-center` class by default, if no position was manually selected.

2. No `is-position-center-center` class, if the position center center was manually selected.

One of the both ways is consistent, but the current way isn't.

**Comment by CreativeDive** [comment]
@talldan And yes the paragraph block is a good example. This works correct.

**Comment by youknowriad** [comment]
cc @ItsJonQ

**Comment by ItsJonQ** [comment]
@CreativeDive + @talldan 

Thank you for bringing this up! I can see the inconsistency here.
I agree that perhaps the default position (center center) shouldn't have a className to begin with.

> No is-position-center-center class, if the position center center was manually selected.

I can follow this up with a PR for that fix 🙌
