### ISSUE TITLE
@wordpress/scripts deletes files

### ISSUE THREAD

**Issue by Lewiscowles1986** [WordPress/gutenberg#24111]
**Describe the bug**

Following the instructions on `@wordpress/scripts` leads to files deleting themselves.

**To reproduce**
1. add the import and splats from the `@wordpress/scripts` npm (trying to reduce package size)
2. run `npm run build`
3. observe many missing files (not sent to recycle bin or trash, but permanently deleted... WTAF)

**Expected behavior**

Not deleting, reverting or modifying files without a prompt to confirm (minimize any user surprise)

**Additional context**

This is when using the `@wordpress/scripts` package at version `12.1.1` windows 64-bit using vscode & git bash.

**Comment by Soean** [comment]
This feature was added in #23135 to clean up the build folder. If you have other build scripts maybe use a subfolder for the output of this scripts.

@ocean90

**Comment by Lewiscowles1986** [comment]
What I've done instead (for now at least) is not used `@wordpress/scripts`, but rather `@wordpress/dependency-extraction-webpack-plugin` which was the part I wanted.

The files going missing were in `{repo}/src` and included:

- `lib`
- `media`
- `node_modules`
- `storybook`

**webpack.config.js**

```
const DependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );

var config = {
	entry: './index.js',
	output: {
		path: __dirname,
		filename: 'block.build.js',
	},
	module: {
		rules: [
			{
				test: /\/stories\/.+\.js$/,
				loaders: [ require.resolve( '@storybook/source-loader' ) ],
				enforce: 'pre',
			},
			{
				test: /.js$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
			},
			{
				test: /.scss$/,
				loader: 'sass-loader',
			}
		],
	},
	plugins: [],
};

module.exports = (env, argv) => {
	if (argv.mode === 'development') {
		config.devtool = 'source-map';
	}

	if(process.env.WP_NO_EXTERNALS) {
		config.plugins.push(
			new DependencyExtractionWebpackPlugin( {
				injectPolyfill: true,
				outputFormat: 'json'
			})
		);
	}

	return config;
};
```

It seems to have fixed the issue for-now. I may have to spend a lot more time to bring the repo (2017 I think) in-line with 2020 😁 )

**Comment by Lewiscowles1986** [comment]
I also can't think of why https://www.npmjs.com/package/clean-webpack-plugin would be the culprit. It's defaults and the usage seem to suggest this is something else.

**Comment by ocean90** [comment]
By default `clean-webpack-plugin` deletes everything defined in `output.path`. In your example it's `__dirname` so it deletes everything in the same directory as the config is. You should use a separate output directory. See the [default config](https://github.com/WordPress/gutenberg/blob/80e8f7da24cb97765288c9d3516372c18a4c49ab/packages/scripts/config/webpack.config.js#L56) for an example.

**Comment by gziolo** [comment]
It looks like there is no action left. I will close this issue. @Lewiscowles1986, did you manage to resolve your issue by following  the recommendation shared?
