### ISSUE TITLE
Add Cover Image Block Cropping/Scaling/Positioning

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2412]
When inserting an image into a Cover Image block, I am stuck with the image dimensions provided by the block and have no ability to crop the image, scale it to fit the block, or to position it as shown:

![image](https://user-images.githubusercontent.com/12448364/29287603-17fa2adc-8104-11e7-976c-d81df1c63cab.png)

Naturally in this cause I would want the text on paper to centered. But in order to do that it seems like I have to do a lot of trial and error cropping in the Media Library as opposed to in the editor.

What I would like to see is the ability to drag the image around in the frame to place it where I want with optional (or mandatory if needed) cropping, the ability to scale to fit. Barring that, at least some kind of guidance on how I should crop the image to get it to fit by providing pixel dimensions or aspect ratio.

**Comment by karmatosed** [comment]
I am not sure cover images need cropping or resizing. The idea for these is different as it would be a large image. I could see cropping being slightly useful.. but not sure about scaling. Interested in what others think.

**Comment by jasmussen** [comment]
Would agree with Tammie, that it would be hard to add cropping to the Cover Image block. We need good cropping for images, certainly, but Cover Image is built in a way that uses backgrounds, making the control of cropping more difficult. It'd be nice to see a parallax feature, though.

**Comment by karmatosed** [comment]
Let's close this as we focus in on what blocks have.
