### ISSUE TITLE
Buttons border radius is not defaulting correctly

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24128]
**Describe the bug**
When adding a button to the Buttons block, the default corner radius shows `5`. But when I make an adjustment to corner radius of 5, the corners change drastically. So the default setting isn't reflecting the actual radii.

**To reproduce**
1. Add a Buttons block
2. If using the Gutenberg-starter-theme, notice the default styling is completely rounded corners.
3. Observe the radius setting default only shows 5.
4. Change the radii and view the results.

**Expected behavior**
I expect the default radius in the settings sidebar to match the actual radii of the button corners.

**Screenshots**

![radius](https://user-images.githubusercontent.com/617986/88223253-026bef00-cc1c-11ea-98e2-3946f1a4fb52.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Gutenberg version: 8.5
- Chrome latest version

**Comment by mapk** [comment]
I tested this on Twenty Twenty too. Same issue.

![radius-problem](https://user-images.githubusercontent.com/617986/88223917-1bc16b00-cc1d-11ea-8fe9-78fa8d5cba5c.gif)

**Comment by CreativeDive** [comment]
@mapk I think how the default button looks is a theme decision. The best option would be a disabled border radius by default. Only if we change the radius, this should be affects the button. Because buttons could be squared or can have a larger radius by default theme settings.

**Comment by youknowriad** [comment]
Seems like there's a couple of related issues #17596 #4420

**Comment by mapk** [comment]
>I think how the default button looks is a theme decision.

Yes. I don't have any problem with there being various radii. The problem is that the numeric value isn't reflected in the settings. If the border-radius for a theme's button style is 50, it should be reflected in the settings. If it's 0, it should be that value.

**Comment by mapk** [comment]
I'm going to close this in favor of https://github.com/WordPress/gutenberg/issues/17596 and move my comments here to there.
