### ISSUE TITLE
Preview CSS in Visual Editor

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2413]
For a Verse Block, what I get in the editor and what I get in the actual post are radically different in terms of looks.

Editor:
![image](https://user-images.githubusercontent.com/12448364/29289866-2c740bd8-810c-11e7-95c8-def2ad1ef813.png)

Post:
![image](https://user-images.githubusercontent.com/12448364/29289908-4b17154e-810c-11e7-8434-c0f5a7270184.png)

This is kind of a minor annoyance, but in the editor, I have no clue what the result is going to look like in terms of color, font, etc. Granted there's the Preview option but would it be possible to use the theme's style.css file to get an approximate look within the block?

**Comment by karmatosed** [comment]
This styling comes from the theme. In the future yes there will be more consistency. However for now the styling is up to each theme.
