### ISSUE TITLE
The "Default" style is gone from WordPress 5.5.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#24147]
Thank you for always improving Gutenberg.

The "Default" style is gone from WordPress 5.5.

If you added your own block style from the theme or plugin side, the "default" style was displayed automatically until now.

Since this is gone, the block style cannot be undone.

Is this a specification?

If you add the "default" style for 5.5 or later, you will see two "default" styles before 5.4, which is a little troublesome.

I want to know why it was changed like this.

**Screenshots**

WordPress 5.4
<img width="274" alt="スクリーンショット 2020-07-23 13 03 47" src="https://user-images.githubusercontent.com/31400297/88251245-2810fb00-cce5-11ea-9bd6-e8dd97ea32b8.png">

WordPress 5.5
<img width="276" alt="スクリーンショット 2020-07-23 13 05 23" src="https://user-images.githubusercontent.com/31400297/88251260-3bbc6180-cce5-11ea-9f59-ba8b59539ee6.png">

**Comment by augustuswm** [comment]
Our organization ran in to the same issue. Mainly need to know if this is an intended change so we can take it into account.

**Comment by ocean90** [comment]
Confirmed the issue. You can reproduce it by simply running the following in the browser console:

```js
wp.blocks.registerBlockStyle( 'core/list', {
	name: 'test',
	label: 'Test',
} );
```

In 5.4 you automatically get the "Default" and "Test" style, in 5.5 only "Test.

The code for this is still seems to be there: https://github.com/WordPress/gutenberg/blob/b9de73ddb58b6b88faa4846d3f8294c815c9d4df/packages/block-editor/src/components/block-styles/index.js#L113-L119

#21973 might be related. cc @adamziel

**Comment by nosolosw** [comment]
According to git bisect https://github.com/WordPress/gutenberg/pull/22849 is the PR that introduced the regression.
