### ISSUE TITLE
Gutenberg 8.6. contains the PHP notice: Undefined property: WP_Block_Type::$supports

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#24149]
Hey,

after installed the gutenberg 8.6 plugin, I get this new PHP notice: Undefined property: WP_Block_Type::$supports

<img width="1258" alt="Bildschirmfoto 2020-07-23 um 08 42 54" src="https://user-images.githubusercontent.com/31563167/88258464-84adef00-ccc0-11ea-8889-93bda0704e82.png">

**Comment by claudiulodro** [comment]
I have a pull request open at https://github.com/WordPress/gutenberg/pull/24131 to solve the issue. In the meantime, the easiest solution is probably to [add `supports => []` to to the blocks throwing the error if possible.](https://github.com/Automattic/newspack-blocks/pull/549/files)

**Comment by youknowriad** [comment]
closed by #24131

**Comment by vjik** [comment]
The bug returned after refactoring: #24351

**Comment by vjik** [comment]
Added issue #24922
