### ISSUE TITLE
Blocks are dropped on the wrong position on multi-selections.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#24158]
When you have multiple blocks selected and you drag and drop them downwards, they are not dropped at the exact position you release the mouse. It seems like the dropping position right now is something like `position + draggedBlocks.lenght` 

cc @talldan @ellatrix

**Comment by talldan** [comment]
@youknowriad Good catch, I think that'd be this logic, which at the moment only accounts for one block:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/use-block-drop-zone/index.js#L293-L298

I'll put together a PR to fix.
