### ISSUE TITLE
Wordpress embeds not respect the multilingual(wpml) page/post content

### ISSUE THREAD

**Issue by sagarsdeshmukh** [WordPress/gutenberg#24150]
**Describe the bug**
When user embed a wp url in post for non-primary language post, the embedded content shows primary language post content

**To reproduce**
1. considering that we have a multilingual wordpress site (lets use wpml plugin here)
2. Add 2 post with english and french translations (here english is a primary language in site)
3. edit the post 1 in french and add wordpress embed gutenberg block with post 2 in french 
4. You will found that though we add a french post link in embedded input field the content will shows from primary  language

**Expected behavior**
The wordpress embed should show the same post from same language which pass in the input field.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  "gutenberg plugin", "default"

**Comment by ellatrix** [comment]
Hi! Is there any way to reproduce the issue without the WPML plugin? This is a paid plugin, so I'm not able to test. If it's WPML specific, it might be better to contact the plugin author.

**Comment by miminari** [comment]
In today's core-editor triage, we have determined that this issue seems to be a problem with the WPML plugin, so we are closing it.
