### ISSUE TITLE
request for woocommerce

### ISSUE THREAD

**Issue by robbisy** [WordPress/gutenberg#2416]
Would it possible in future releases to add woocommerce support ?
Thanks

**Comment by karmatosed** [comment]
Woocommerce blocks would be something up to the team and not something rolled in by default into Gutenberg. Thanks for the request though and I'm sure the team would love to know that people want this.

**Comment by lukecav** [comment]
@robbisy 

https://github.com/woocommerce/woocommerce/pull/16820
