### ISSUE TITLE
Console error after setting any custom timezone: Moment Timezone has no data for ...

### ISSUE THREAD

**Issue by BennyVL** [WordPress/gutenberg#24163]
Since Gutenberg 8.5, setting a custom time zone will result in a console error (by moment,js).

1. Activate Gutenberg 8.5/8.6
2. Go to Settings, 
2. Set TImezone to for example 'Amsterdam' + Save
3. Edit any page, show Developer Tools
4. See console error:
**Moment Timezone has no data for Europe/Amsterdam.** See http://momentjs.com/timezone/docs/#/data-loading/.

![console-error](https://user-images.githubusercontent.com/13752843/88302380-1429c100-cd06-11ea-9703-d27a4fd34579.png)

- Tested on fresh Local site with WP 5.4

**Comment by ocean90** [comment]
Thanks for the report, this is already being tracked in #22193.
