### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by gasova** [WordPress/gutenberg#24164]
They are situations where justified text is mandatory and perfectly readable? No-one should dictate what can or cannot be done justified text has to be enabled and implemented on gutenberg editor.  

Please stop that telling, justification is not working, hyphens incorrectly displaying, etc., etc,.  

It is nonsence to not include this feature. For you it can be useless for others it can be a must have. 

In our case I'm developing a wp plugin where the user has to create a page or post with dynamic fields,  (using the gutenberg editor). 

So when the visitor fills a form, the custom post is called and converted into a pdf. 

This document can be a contract having administrative  purposes with non-breakable formats given by the government and may contain justified text as well. 

Instead of forcing us to hack the editor, or google it, you should add it to the editor with the other alignment options. 

#wewantjustifiedtextback.

**Comment by talldan** [comment]
Your language in this post is against our code of conduct. I've edited out the offensive language, but want to warn you that it won't be tolerated and in future could lead to stronger action.

Previously this was discussed in https://github.com/WordPress/gutenberg/issues/18555, I don't think there needs to be any more detail than that, the reasoning is there for you to read. If you want to know more you'd have to look at WordPress 4.7, which predates Gutenberg.

> Instead of forcing us to hack the editor

You don't need to hack the editor, there's a public API for adding text formats:
https://developer.wordpress.org/block-editor/tutorials/format-api/

There are also third-party plugins that provide this behavior.

**Comment by gasova** [comment]
First of all I want to apologize my language, but at the moment I wrote it, I was frustrated. 

Everything I googled was directing to hundreds of posts and pages about that justified text was non-sense, not working etc. etc. and pages where the reasoning why WordPress or Gutenberg wont support Justified text, without any solution. 

So in a hurry I was angry because some folks, again in my opinion at the time I opened this issue, had decided what was "politically correct to use or not" instead of providing a solution  like you did here. So I'm grateful and thank you for your answer. 

Don't forget that there can be always use cases you can't always think nor imagine nor understand. Everything isn't black or white, they can be gray zones, and by deciding not supporting something that can be useful to others you omit those gray zones.

Sincerely, Kind Regards
