### ISSUE TITLE
Eslint prettier not auto-fixing/write

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/gutenberg#24160]
**Describe the bug**

When using https://www.npmjs.com/package/@wordpress/eslint-plugin it only reports all errors from prettier instead of directly auto-fixing them.
Since this package has a dependency for eslint-plugin-prettier, I assume the expected behavior is auto-fixing of prettier error (prettier --write)

**To reproduce**
run eslint with "plugin:@wordpress/eslint-plugin/recommended" on any js file with bad formatting.

**Expected behavior**
That it auto-fixes all prettier things instead of reporting them

**Editor version (please complete the following information):**
- WordPress version: all

**Comment by aduth** [comment]
Passing the `--fix` flag when running ESLint should automatically correct any issues reported by Prettier.

See: https://eslint.org/docs/user-guide/command-line-interface#-fix

It's supported by `eslint-plugin-prettier`:

>The rule is autofixable -- if you run `eslint` with the `--fix` flag, your code will be formatted according to `prettier` style.

https://github.com/prettier/eslint-plugin-prettier#options

**Comment by kkmuffme** [comment]
@aduth the issue seems to be that prettier conflicts with other (default) options of eslint, which undoes fixes it applies, ending up with a mess.

Do you require https://github.com/prettier/eslint-config-prettier ? As this would turn off all those by default, avoiding this issue in the future.
