### ISSUE TITLE
Slide Deck should be in an open source format

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2417]
The slide deck introduced in #2415 should be in an open source format. Right now, Keynote is required in order to use the deck or collaborate on it. Contributing to and collaborating on open source shouldn't require the use of closed source software.

**Comment by aaronjorbin** [comment]
[deck.js](http://imakewebthings.com/deck.js/) is available under the MIT license and could work well in this instance.

**Comment by karmatosed** [comment]
I do feel having a version that is .js limits for all users though. In light of this closing as we will offer example slidedecks but not a global one. The current one is a little out of date right now so needs revisiting.
