### ISSUE TITLE
Extra paragraph block is automatically added inside a group block

### ISSUE THREAD

**Issue by desaiuditd** [WordPress/gutenberg#24185]
**Describe the bug**
In the block editor, an extra paragraph block is automatically appended at the end inside a group block if the last block is of certain type such as List block, Image block etc.

**To reproduce**
1. Create a new post with block editor.
2. Add couple of paragraph blocks.
3. Add a group block.
4. Add couple of more paragraph blocks inside group block.
5. Now, add a list block or image block at the end inside the group block.
6. Observe that the block list appender (paragraph block) is automatically appended after the list/image block.

However, above doesn't happen with the paragraph block.

**Expected behavior**
The block list appender or the paragraph block should only appear at the end, if I press enter from the list block.

**Screenshots**
![2020-07-24 17 06 06](https://user-images.githubusercontent.com/2236554/88368249-fd03d580-cdd0-11ea-9051-da334fa67dd8.gif)

**Editor version**
- WordPress version: 5.3.2
- Gutenberg Plugin installed: Latest master branch at commit - 48ddf942c4025eb7114bee51a09d9b60bc9d0561

**Desktop**
 - OS: MacOS Catalina 10.15.5 (19F101)
 - Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
Related tickets and PRs:
- #21251
- #21318

**Comment by tellthemachines** [comment]
Closing as this is expected behaviour as per [this Slack conversation](https://wordpress.slack.com/archives/C02QB2JS7/p1595575337405300).
