### ISSUE TITLE
Docs: Attributes and Patterns in Block Editor Handbook

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#24181]
@mkaz 
This is question about new structure of Block Editor Handbook.

1. Attributes

Current [Block Attributes](https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/) page under Block API Reference is made from [Create Block Tutorial directory](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/create-block/block-attributes.md) not [the page uner the Block API Reference directory](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-attributes.md) that was original source of Attributes.
Furthermore, top page of [Create a Block Tutorial](https://developer.wordpress.org/block-editor/tutorials/create-block/) mentions above Block Attributes page but does not exist under the tutorial page.
Is it intentional or site construction failure?

2. Patterns

Can not find the source file of [Patterns](https://developer.wordpress.org/block-editor/designers/design-patterns/) page under the Designer Document in GitHub. Are you going to remove this page? Though there is another [Patterns page](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/), this is for developers how to.

**Comment by atachibana** [comment]
For above 2. I found #21562 changed the filename to user-interface.md.
Yes, it was confusion and it should be so.
Please remove the sub menu 'Patterns' from Block Editor Handbook.

**Comment by mkaz** [comment]
I created a PR to address block-attributes file rename, I have concerns with the publishing method if having the same name (but different path) causes the system confusion; but that can be addressed later.

I removed the old patterns page, when files are renamed, the old document needs to be cleaned up in wp-admin.

**Comment by ocean90** [comment]
Related/Duplicate: #23978/#24198
