### ISSUE TITLE
Undo image resizing doesn't work

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24199]
**Describe the bug**
The `Undo` and `Redo` buttons don't work in relation to image resizing when dragging the image resize node.

**To reproduce**
1. Add an Image block with an image.
2. Resize the image using the resize node.
3. Click the `Undo` button in the topbar.
4. Observe that nothing happens.

**Expected behavior**
I expect the `Undo/Redo` behavior to also apply to resizing an image after resizing with the image resize node.

**Screenshots**

**Media + Text block**

![undo](https://user-images.githubusercontent.com/617986/88420138-43d6d880-cd9b-11ea-95c7-443f8115510b.gif)

**Image block**

![undo-resize](https://user-images.githubusercontent.com/617986/88420151-49342300-cd9b-11ea-85fd-4bbe6a5eb8fc.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Gutenberg version: 8.6
- Chrome latest

cc Hat tip to @joyously for bringing this to my attention.

**Comment by david-szabo97** [comment]
Looks like the resizing operation is works like a transient edit. Once we change focus to other block then it creates an undo level correctly. But it doesn't if we just keep resizing without changing focus.

Looking into this!

**Comment by Thelmachido** [comment]
This was also reported in [#24199](https://github.com/WordPress/gutenberg/issues/24199)  I wasn't able to replicate the issue. The option to undo works after I resize the image as shown below:

https://user-images.githubusercontent.com/41231764/183102392-f9be0d22-d40f-46ef-b677-91b4eef2e075.mov

I am closing this issue. 

Gutenberg 13.8.0

WordPress 6.0.1

**Comment by Thelmachido** [comment]
I wasn't able to replicate the issue. The option to undo works after I resize the image as shown below:

https://user-images.githubusercontent.com/41231764/183102392-f9be0d22-d40f-46ef-b677-91b4eef2e075.mov

I am closing this issue. 

Gutenberg 13.8.0

WordPress 6.0.1
