### ISSUE TITLE
Video paste doesn't seem to work on Video block

### ISSUE THREAD

**Issue by programmin1** [WordPress/gutenberg#2419]
## Issue Overview
Gutenberg video block says to paste, but there is nowhere to paste into and pasting a Youtube url doesn't do anything.

## Steps to Reproduce (for bugs)
1. Start Gutenberg page
2. Insert "Video"
3. Paste Youtube url

Firefox 55, Gutenberg 0.8.

## Expected Behavior
It should allow "paste a URL below" as its description suggests.

## Current Behavior
Paste doesn't seem to do anything.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mikaelz** [comment]
Chrome the same. Description text is misleading. No input where to paste YouTube URL

![ss_2017-08-15-09-06-14](https://user-images.githubusercontent.com/454800/29305529-7697e9cc-8199-11e7-95a4-4b6d5122784d.jpg)

**Comment by karmatosed** [comment]
I have changed the copy. I think as we have embeds this probably works as a good option. Although we may want to consider at a later date. You can use the embed blocks right now.
