### ISSUE TITLE
Gradient RGBA/HSLA inputs are not wide enough in WordPress 5.5

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#24201]
**Description**
When adding a gradient with RGBA or HSLA color values to a block, the increment buttons of number inputs cover up the inputs' values. The design worked well enough with 3 inputs (RGB/HSL) in WordPress 5.4, but there is a fourth input now in 5.5.

Originally reported by MarkS99 on Trac: https://core.trac.wordpress.org/ticket/50689

**Steps to reproduce**
1. Create a Group block (or another block that supports gradient backgrounds).
2. Expand Color Settings and choose Gradient.
3. Click an existing gradient control point or create a new one (circles along the pill-shaped bar).
4. Click the chevron icon next to the hexadecimal input to see the RGBA or HSLA inputs.
5. Type any value in each input. If your browser/user agent has increment buttons, those likely will overlap the value.

**Screenshots**
1. Visible increment buttons overlap HSLA inputs in Windows Firefox
![HSLA inputs in Firefox](https://user-images.githubusercontent.com/17100257/88425934-ddab7f00-cdb5-11ea-9ea6-34aacae6ba5a.jpg)

2. RGBA inputs in Windows Chrome (hidden increment buttons show on hover/focus)
![RGBA inputs in Chrome](https://user-images.githubusercontent.com/17100257/88424816-d6837180-cdb3-11ea-9605-9a126ee860a5.jpg)

**Versions:**
- MarkS99 found the problem using WordPress 5.5-beta-2 on Mac OSX in Chrome, Safari & Firefox.
- My screenshots are from a more recent trunk version (still 5.5) on Windows 10, without the plugin, but I still see it with Gutenberg 8.6.0 activated.

**Comment by sabernhardt** [comment]
The simplest fix for the width might be to add a `min-width` on the container.

```
.components-color-picker__inputs-wrapper {
    min-width: 25em;
}
```

I like 25em for larger screens (medium breakpoint up), though it might need to be 20em or a similar pixel value for narrower screens.

**Comment by sabernhardt** [comment]
Also, the legends do not mention the alpha channel. 

Maybe they only need the "A" included ("Color value in RGBA" and "Color value in HSLA"). I'd prefer making it clearer—either in the individual visible labels or in the visually hidden legend—what the letters of the abbreviations mean, but it might be too late for that. A legend of "Color value in RGB with alpha transparency" is another option, too.

**Comment by sabernhardt** [comment]
As noted on the Trac ticket, this will need the `Backport to WordPress core` tag.

**Comment by ocean90** [comment]
Chrome, macOS, WordPress 5.4:
<img width="300" alt="chrome-osx-now" src="https://user-images.githubusercontent.com/617637/88479266-1f6f2d80-cf4e-11ea-86fc-048f5fbca076.png">

Chrome, macOS, WordPress 5.5:
<img width="281" alt="chrome-osx-before" src="https://user-images.githubusercontent.com/617637/88479264-1d0cd380-cf4e-11ea-9645-d444a38dfe89.png">
