### ISSUE TITLE
Alert the editor when trying to leave the Site Editor with unsaved changes

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#24209]
**Is your feature request related to a problem? Please describe.**
When using the Site Editor, sometimes I might click on the wrong place and leave the editor, withour being alerted that I have unsaved changes and asked whether I want to proceed or cancel, which results in my latest edition being lost.

**Describe the solution you'd like**
It would be very helpful to display the same browser-native popup that opens when trying to leave the page/post editing page with unsaved changes, so that the editor can confirm or cancel.

**Comment by ehti** [comment]
Hmm, yep, for the unsaved changes there doesn't appear to be a warning/popup if you navigate away.

I'm not sure if it's by design, but let's get feedback from the design folks on it!

**Comment by noahtallen** [comment]
Definitely not intentional to not have it yet -- just hasn't been implemented!

**Comment by ehti** [comment]
Thanks!

I guess the feedback label can be removed - going ahead with it.

**Comment by david-szabo97** [comment]
I'll give this one a try 😄

**Comment by ockham** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/24659 :slightly_smiling_face:
