### ISSUE TITLE
Categories and Tags gone in Gutenberg (ALL plugins deactivated) 

### ISSUE THREAD

**Issue by smiciulis** [WordPress/gutenberg#24213]
I am having issues with Gutenberg not displaying categories and tags in the backend. It works fine on the classic editor. I've disabled all other plugins (even woocommerce), changed the theme to storefront (the actual live theme is Ecommerce Gem) and the issue still persists. I've checked Rest API endpoints and I can get access. I am at a loss at this point, not sure whether I need to switch to a different editing method or is there a way to resolve this. Help?

![image](https://user-images.githubusercontent.com/68843910/88518620-acff5b80-cfe8-11ea-815e-a36c39a068ea.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg "default"

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version Chrome 84 on Windows 10

**Comment by ocean90** [comment]
It seems like you're editing a page which by default has no support for tags/categories. If you use custom code to assign them to pages too, make sure that it also runs in REST API context.

**Comment by smiciulis** [comment]
Well I have checked all the other pages and it is the same. I also cannot access categories and tags on product pages (I have Gutenberg enabled for product pages) as well. So I don't think that's the issue. I am not touching categories or tags with any custom code. Any other ideas?

**Comment by smiciulis** [comment]
Just for context, my database is running with a prefix as part of security measures. And this install is also currently nested as a folder under another wordpress website. Might that affect things?

**Comment by smiciulis** [comment]
Any ideas guys?

**Comment by smiciulis** [comment]
Bump, still trying to get this working. Any help would be much appreciated!

**Comment by paaljoachim** [comment]
Hey @smiciulis Saul.
I happen to come across this issue. Is it still valid?

**Comment by jasmussen** [comment]
Given the stalled conversation, I'm going to close this one assuming it to have been resolved.
