### ISSUE TITLE
Post Comments Form: Implementation Notes

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#24221]
The Post Comments Form block is currently implemented to be [rendered](https://github.com/WordPress/gutenberg/blob/6caa42a1eec58d8f97622be50447e4e08004995d/packages/block-library/src/post-comments-form/index.php#L22) by [`comment_form()`](https://developer.wordpress.org/reference/functions/comment_form/) on the frontend (which can be fairly complex, containing several different labels, messages, and the form itself in different versions for logged in and out users.

In the editor, it is just a [placeholder](https://github.com/WordPress/gutenberg/blob/6caa42a1eec58d8f97622be50447e4e08004995d/packages/block-library/src/post-comments-form/edit.js#L7).

We need to match what is editable in the editor with the output produced by the frontend, by replicating the logic of the `comment_form()` function (see also #22724 for a breakdown of other possible functions affecting the comment form).
All [its parameters](https://developer.wordpress.org/reference/functions/comment_form/#parameters) and the comment form filters ([`comment_form_default_fields`](https://developer.wordpress.org/reference/hooks/comment_form_default_fields/), [`comment_form_field_{$name}`](https://developer.wordpress.org/reference/hooks/comment_form_field_name/)) should be taken into consideration.

_Props to @ockham for #24101, which inspired this issue._

**Comment by karmatosed** [comment]
@Copons just checking what still needs doing design-wise here as this is a little older issue. I currently see:

![2021-09-10 at 17 57](https://user-images.githubusercontent.com/253067/132890234-01418f6a-89f8-4260-8e87-a59e10d60e98.png)

Which is very 'lacking' so my belief is that showing an actual 'form' makes a lot more sense. But, just checking that is still the intention here and if so I can mock that up to finally unblock this little task.

**Comment by carolinan** [comment]
I always pictured that this would be a block with inner blocks so that the field names, labels and position could be changed or  removed.
But that would mean no longer relying on comment_form() and its filters.

**Comment by youknowriad** [comment]
The block actually shows the form in the editor now. so I'm closing this issue.
