### ISSUE TITLE
`npx @wordpress/create-block` throws errors

### ISSUE THREAD

**Issue by cliffordp** [WordPress/gutenberg#24228]
**Describe the bug**

Links:
* https://www.npmjs.com/package/@wordpress/create-block
* https://developer.wordpress.org/block-editor/packages/packages-create-block/
* https://github.com/WordPress/gutenberg/blob/master/packages/create-block/README.md

**To reproduce**
Run `npx @wordpress/create-block`, enter values for the prompts, see a wall of error message text, including:

> npm ERR! Failed at the my-block@my-version build script.

If relevant, `nvm version` is `v13.6.0`

Full debug log: [2020-07-27T20_39_02_464Z-debug.log](https://github.com/WordPress/gutenberg/files/4984294/2020-07-27T20_39_02_464Z-debug.log)

**Expected behavior**
No terminal errors

**Screenshots**
GIF: https://share.getcloudapp.com/WnuJRnew

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.6

**Comment by talldan** [comment]
@cliffordp I wasn't able to reproduce any issues, though with a slightly more recent version of node, same Mac OS version:
<img width="789" alt="Screenshot 2020-07-29 at 11 46 22 am" src="https://user-images.githubusercontent.com/677833/88754415-2f2a8400-d191-11ea-83bc-d498a44f9cc7.png">

I'll leave the issue open to see if any other folks report issues, and then we may be able to work out some commonalities.

**Comment by cliffordp** [comment]
Thanks for testing. What if you just _Enter_ through the Dashicon as optional? Seems unlikely but that's the only bit I can guess is different usage than your screenshot.

**Comment by talldan** [comment]
I think `smiley` is the default value, which gets filled in when hitting enter. I tried a few different things and still not experiencing that error.

The only thing I can think of is either the different node version or something in your environment causing an issue.

If you run `npm list -g --depth=0` to list globally installed packages, do you have anything webpack related installed?

**Comment by youngmicroserf** [comment]
I'm not sure this is related, but it may be - but when I tried to run the package it also threw a lot of warnings and ended when the max call stack size was exceeded. It took me a long time to figure out the reason - I wasn't executing the command from a directory on the system drive (c:/ in my case (WIN10/x64) but from a directory on another drive (o:/). Turns out, when executed in a diretory on c:/, the block scaffolding finishes as intended.

If this error is related to anything in the package configuration, maybe it is possible to avoid it. If it is unrelated to the package and a bug/feature of npm, then maybe this information should be added to the documentation.

**Comment by gziolo** [comment]
It looks like an issue with `@wordpress/scripts` and with the `build` command. I have just tried with Node.js v12.9.0 (npm v6.14.8) and it all went as expected. I was also able to successfuly run `npm run build` inside the scaffolded block folder.

**Comment by cliffordp** [comment]
@talldan sorry for the delayed response - just saw your message.

![image](https://user-images.githubusercontent.com/1812179/96166023-0b025780-0ee3-11eb-946a-f2c550d07fbd.png)

**Comment by gziolo** [comment]
@cliffordp, does it work you with Node 12 and Node 14?
I noticed that some npm packages don’t define support for Node 13.x and 15.x for some reasons.

**Comment by gziolo** [comment]
Node.js v14 is going to become the minimum LTS version in about a week. Let's close this one as no longer actionable.
