### ISSUE TITLE
Block title in Select mode not shown fully

### ISSUE THREAD

**Issue by dariaknl** [WordPress/gutenberg#24220]
**Describe the bug**
Block title in Select mode is not fully shown.
Probably it is already known, but I did not manage to find an existing issue.

**To reproduce**
1. Go to create post
2. Click on click to add Media & Test block.
3. Switch to Select mode.
4. See screenshot:

<img width="818" alt="media and text" src="https://user-images.githubusercontent.com/19681708/88554789-36358300-d027-11ea-958a-b81ccee47a59.png">

**Expected behavior**
The full title is shown.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Default

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ocean90** [comment]
Hi @dariaknl, thanks for the report. This was fixed as part of the redesign and will be part of the upcoming [WordPress 5.5 release](https://wordpress.org/news/2020/07/wordpress-5-5-beta-3/).

Here's how it looks now:
<img width="319" alt="select-block-title" src="https://user-images.githubusercontent.com/617637/88558027-4d766f80-d02b-11ea-8140-85b0493af97b.png">
