### ISSUE TITLE
Move Image Block caption placeholder to below image - center

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#24238]
**Is your feature request related to a problem? Please describe.**

Todays Image Block caption:
<img width="772" alt="Screen Shot 2020-07-28 at 12 00 30" src="https://user-images.githubusercontent.com/5323259/88652566-4b63ed80-d0cb-11ea-9da7-89f0e90beabb.png">

**Describe the solution you'd like**

Let's move the placeholder "Write caption..." to the center area.

![Image-caption-below-image-center](https://user-images.githubusercontent.com/5323259/88652762-86feb780-d0cb-11ea-905c-cd353aa57f7e.jpg)

**Comment by talldan** [comment]
@paaljoachim That's a Twenty Twenty theme thing. In other themes it's in the center.

This could be changed in Twenty Twenty, but I believe it'd have to be a core trac ticket.

**Comment by paaljoachim** [comment]
Thanks for the info Dan! Have a great continued day.
