### ISSUE TITLE
Insert block before and after buttons disappear

### ISSUE THREAD

**Issue by wolfgegenlicht** [WordPress/gutenberg#24235]
Hey there,

I am not sure whether this is a known issue or intentional behaviour.

The insert-before and insert-after buttons disappear, as soon as i **do not** use the "core/paragraph" block.

**In this case the insert-before and insert-after buttons disappear**:

`
function mytheme_allowed_block_types( $allowed_blocks ) {
	return array(
		'core/block', 
		'core/image', 
		'core/audio'
	);
}
add_filter( 'allowed_block_types', 'mytheme_allowed_block_types' );
`

As soon as i add the 'core/paragraph' block to the list, they appear again.

Is this a known issue?

Cheers
Wolf

**Comment by talldan** [comment]
@wolfgegenlicht Thanks for reaching out. Yep, this is a known issue - https://github.com/WordPress/gutenberg/issues/23603

These buttons insert the 'default' block, which happens to be the paragraph:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/index.js#L166

Interesting that you have such a small subset of blocks. You could try using `setDefaultBlockName( blockName )` to set a different block to the default, and then the Insert Before/After options should insert that block, though I'm not exactly sure how well that's tested. Give it a go.

I'll close the issue, as I think the technical aspect is covered by #23603.
