### ISSUE TITLE
I18n: All JS strings are missing in translation.

### ISSUE THREAD

**Issue by jahrud** [WordPress/gutenberg#24236]
Seit dem letzen Plugin-Update werden alle Anleitungen und Funktionen nur mehr in Englisch angezeigt. Mein Wordpress ist aber auf Deutsch (German) eingestellt. Wie kann ich das wieder ändern??

**Comment by Soean** [comment]
@jahrud Danke, für die Meldung, wir schauen uns das Problem an. Da dies ein internationales Projekt ist, verwenden wir Englisch zur Kommunikation.

Currently not all translations from the plugin are processed correctly.

**Comment by Soean** [comment]
@jahrud if you update to 8.6.1 it should work again.

**Comment by Soean** [comment]
Fixed in #23926
