### ISSUE TITLE
Spotify Embed: Podcast Embeds Get Cut Off on Mobile

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#24231]
**Describe the bug**
Spotify's podcast embeds have a unique design. It works nicely with the Spotify embed block but the player is cut off on smaller screen sizes when "Resize for smaller devices" is selected.

**To reproduce**
1. Go to a page or post and add the Spotify embed block
2. Add the Spotify link to the podcast. Example: `https://open.spotify.com/episode/5oW6LD6AF7hDXp71dJGmNh?si=9MHsRRszSu25Tn1DR-Z42w`
3. Toggle on the "Resize for smaller devices" option in the block settings
4. Publish and view the page/post on different screen sizes, including a mobile device.
5. See that the embedded player is cut off.

**Expected behavior**
I expected the player to show in full on mobile. The "Resize for smaller devices" option makes it sound like it will resize to a mobile-friendly display.

**Screenshots**
<img width="270" alt="spotify podcast embed" src="https://user-images.githubusercontent.com/30727666/88602183-96730600-d0b5-11ea-9000-79c1c58be669.PNG">

**CSS**
Adding a minimum height will ensure it displays correctly:

```
/*  spotify embed minimum height on mobile */
@media screen and (max-width: 425px) { 
  .embed-spotify {
  min-height: 174px;
  }
} 
```

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10e
 - OS: Android 10
 - Browser Chrome
 - Version 84

**Comment by kathrynwp** [comment]
Hi @donalirl I just tested this and am no longer seeing a vertical scrollbar on the Spotify player on small devices.

I'll close this out as fixed, but if you're still able to replicate, please feel free to comment and I'll be glad to take another look!

Tested with:

WordPress 6.0.1
Gutenberg 13.7.3 active or inactive
No other plugins active

Firefox 103.0 - using browser inspector mimicking iPhone SE 2nd gen. / iOS 14.6
macOS 12.2.1
