### ISSUE TITLE
Please use "Smart quotes" for citations in sample content

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#24237]
Hi,

While working on translations for upcoming WordPress 5.5 I noted that the sample content in a few places contains citations, surrounded by straight quotes. Here you should use smart quotes instead `“quoted text”`. If the use-case would still work, core usually prefers html entities in these cases: `&#8220;quoted text&#8221;`

**Editor version (please complete the following information):**
- This is for the version that is being included with WordPress 5.5

**Comment by ocean90** [comment]
Core only uses HTML entities in the context of HTML. In JavaScript it's better to use the characters directly do avoid rendering the HTML entities as is since React escapes any HTML by default.

**Comment by tobifjellner** [comment]
@ocean90 So you mean that we should leave these strings with straight quotes?
