### ISSUE TITLE
Block editor cannot get back to visual edit

### ISSUE THREAD

**Issue by ACEkin** [WordPress/gutenberg#24240]
When in the block editor, I add a Vimeo embed block, it works fine. However, if I choose the option to edit it as HTML content from the block options, there is no way to get back to edit it visually anymore. Here is a screen capture that shows just the block frame but there is no block menu bar attached to it. This happens consistently, and I believe the same happens on YouTube blocks as well.

https://www.dropbox.com/s/woh4vmj39p5qkrb/vimeoblock.jpg?dl=0

I can leave the edit page, return to edit the content again, and the block returns. I tried choosing the “Code editor” from the More Tools & Options menu but returning to the Visual Editor does not bring the Vimeo block back.

Cemal

**Comment by ACEkin** [comment]
It actually happens to all my blocks in any of the post categories. Once I enter the HTML edit mode, the top block menu totally disappears. My browser is Firefox. WordPress is the latest version, all updates are applied to all the plugins and themes.

**Comment by annezazu** [comment]
@ACEkin thanks for reporting this! I can confirm this is definitely an issue with WordPress 5.4.2 but I tested 5.5 RC today and found it's fixed: https://cloudup.com/cG9TvT5maIH For context, I'm using Gutenberg 8.6.1. I'm going to close this out for now but if you find it's still broken after the 5.5 release coming up in August please re-open!

**Comment by ACEkin** [comment]
Thank you for the update and the good news.

**Comment by annezazu** [comment]
Happy to help. I'll check it out :)
