### ISSUE TITLE
Cover block spacing unit defaults to null

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#24245]
This issue is about the experimental custom spacing controls recently added to the cover block. 

The default unit of the padding input appears as "NULL", and changing this value doesn't affect the padding:

![Kapture 2020-07-28 at 10 15 31](https://user-images.githubusercontent.com/5375500/88677839-c4f3df80-d0bb-11ea-9302-fd184af80169.gif)

You can get around this by adding a unit (e.g. "100px"), but it could be nicer to default to some unit here.

**Comment by kjellr** [comment]
cc @ItsJonQ do you have any idea what's going on here?

**Comment by ItsJonQ** [comment]
Oo! Lemme take a looksy. Thanks!
