### ISSUE TITLE
Missleading example in storybook

### ISSUE THREAD

**Issue by vojtechportes** [WordPress/gutenberg#24247]
I am trying to use gutenberg as stand-alone editor and I am facing following issue.

In storybook example, there is Popover.Slot component used with name property.

```
<BlockEditorProvider
  value={ blocks }
  onInput={ updateBlocks }
  onChange={ updateBlocks }
>
  <div className="playground__sidebar">
    <BlockInspector />
  </div>
  <div className="editor-styles-wrapper">
    <Popover.Slot name="block-toolbar" /> <<====================================================
    <BlockEditorKeyboardShortcuts />
    <WritingFlow>
      <ObserveTyping>
        <BlockList />
      </ObserveTyping>
    </WritingFlow>
  </div>
  <Popover.Slot />
</BlockEditorProvider>
```

When I am trying to do the same in my project using typescript and therefore type definitions of `@wordpress/components`, there is no such property accessible.

Version of `@wordpress/components` I am using is 10.0.3

Any advice?

**Comment by talldan** [comment]
@vojtechportes Caveat that I'm not a typescript expert.

The component definitely has that prop:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/index.js#L601

There aren't any type definitions for this file so I'm not sure how that would work. Type definitions are a work in progress, tracked in this issue - https://github.com/WordPress/gutenberg/issues/18838.

As a non-typescript project, we're currently using JSDocs to provide type definitions.

From what I understand there are also third-party type definitions for some of the `@wordpress/` packages, which might be worth investigating.

**Comment by gziolo** [comment]
@sirreal, does the issue come from external types published on DefinitelyTyped?

**Comment by sirreal** [comment]
> does the issue come from external types published on DefinitelyTyped?

Yes, the types for `@wordpress/components` are external although we are working on first-party types generated from source (#18838). Any issues or fixes would need to go through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/wordpress__components) at this time.

**Comment by mirka** [comment]
I think we can consider this resolved, as the [published types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wordpress__components/slot-fill/slot.d.ts) are now up to date.
