### ISSUE TITLE
this.activateMode is not a function.

### ISSUE THREAD

**Issue by ZafarKamal123** [WordPress/gutenberg#24243]
![this-active-mode-is-not-a-function-error](https://user-images.githubusercontent.com/48084051/88673884-8f261980-d102-11ea-8c95-e5a4558584e6.jpg)

I am experiencing this issue with custom Gutenberg plugin, It's not always there but appears many times. When it occurs as a workaround, I am clearing the localStorage with this line.

``window.localStorage.clear()``

This clears the issue sometimes.Ofc it's not a permanent solution. According to this [Article](https://wpdevelopment.courses/articles/how-to-fix-activatemode-is-not-a-function-error-in-gutenberg/), this seems a conflict with the **Lodash dependency**. Therefore I've completely deleted Lodash from my plugin and using the one bundled with **Gutenberg** itself. But the issue is still not resolved. 

Any ideas, suggestions, workarounds will be much appreciated!
Thanks

**Comment by carolinan** [comment]
Hi!
Can you provide more information about when the error occurs?
Does this also happen _without the custom plugin installed?_  If not, then the issue is probably in the custom plugin.

**Comment by ZafarKamal123** [comment]
Yes, it may be related to my custom plugin but I need a little guidance to resolve it.

**Comment by youknowriad** [comment]
Unfortunately, there's nothing we can do here to help. Based on the error, there's nothing obvious especially since we don't have access to your code.
