### ISSUE TITLE
Adapting a custom list block to the latest Gutenberg version

### ISSUE THREAD

**Issue by Alexius08** [WordPress/gutenberg#24254]
I made a custom version of the list block sometime ago. In Wordpress 5.4.2, it still works. However, activating the latest version of Gutenberg or upgrading Wordpress to the 5.5 beta version breaks the indent functionality.

[The code I wrote using the RichText component](https://github.com/Ultimate-Blocks/Ultimate-Blocks/blob/90abddd3d6be722bb0daafabc47e56babc3b76ec/src/blocks/styled-list/block.js#L302) is very simple, and the indents are handled automatically. When it broke, I noticed that the indent functions for Gutenberg's native list block still worked, so I copied from it [the parts that seemed to handle indenting](https://github.com/WordPress/gutenberg/blob/a260cda069b1899399795062935f6e53555cf855/packages/block-library/src/list/edit.js#L129). I found making those parts work so troublesome, though, as I can't figure out where the value of the `controls` variable's arrow function argument is supposed to come from in the original code.

What else am I missing?

**Comment by youknowriad** [comment]
Hi There! I'm not sure I understand the issues at first sight maybe @ellatrix can.

That said, I'm curious why the regression happened. Do you think you can provide a very minimal block that works on 5.4 but not on 5.5 (ES5 if possible to allow pasting to the browser console)? I would like to understand if there's  something we broke inadvertently. 

Thanks.

**Comment by Alexius08** [comment]
Here's the minimum block that should be able to allow inputting items for an unordered list:

`wp.blocks.registerBlockType("cgb/block-newtest", {
	title: "newtest - CGB Block",
	icon: "shield",
	category: "embed",
	keywords: ["newtest — CGB Block", "CGB Example", "create-guten-block"],
	attributes: {
		content: {
			type: "string",
			default: "",
		},
	},

	edit: function (props) {
		return wp.element.createElement(wp.blockEditor.RichText, {
			multiline: "li",
			tagName: "ul",
			value: props.attributes.content,
			onChange: function (newContent) {
				return props.setAttributes({ content: newContent });
			},
		});
	},

	save: function (props) {
		return wp.element.createElement(wp.blockEditor.RichText.Content, {
			value: props.attributes.content,
		});
	},
});`

Everything else should work fine. Only the indents are broken.

**Comment by youknowriad** [comment]
Thanks for the example, I was able to reproduce the issue. Here's the JavaScript error on the console

<img width="780" alt="Capture d’écran 2020-07-30 à 10 19 31 AM" src="https://user-images.githubusercontent.com/272444/88905517-47aca400-d24e-11ea-8667-9618974ea60c.png">

**Comment by ellatrix** [comment]
It looks like you're missing the `__unstableMultilineRootTag`, which I think is necessary to perform indentations?

**Comment by ellatrix** [comment]
This was introduced in #20498. I guess we could fallback to the `tagName`.

**Comment by ellatrix** [comment]
#24324 should fix the issue
