### ISSUE TITLE
Adding an Order By field to the Blog Posts block

### ISSUE THREAD

**Issue by bborman22** [WordPress/gutenberg#24274]
**Is your feature request related to a problem? Please describe.**
There is currently not a way to change the order of the posts in the Blog Posts block. There may be use cases where the blog posts should be ordered from oldest to newest or ordered alphabetically by title. This functionality is already present in the Latest Posts block, but that block lacks some of the other options in the Blog Posts block, for example the display style, Tags filter, show "More" button, etc.

**Describe the solution you'd like**
I would envision two new fields under the Display Settings tab on the Blog Posts sidebar. One field for selecting the field to sort by, the options here to start could be: Publish Date and Title similar to the Latest Posts options. Then another field for ascending or descending. The default selection would be Publish Date, Descending.

**Describe alternatives you've considered**
The two alternatives right now are to use the Latest Posts blog and change the structure or categorization of the posts so that those filters can limit to what is needed or to use the Choose Specific Posts option to hand pick the posts in the order desired.

**Comment by talldan** [comment]
@bborman22 Just wondering what you mean by the 'Blog Posts' block? This doesn't seem to be a block that's present in WordPress core. 

It might be that this is a block provided by plugin in your installation.

If you're able to provide more information about the block that'd be great.

**Comment by bborman22** [comment]
Sorry about that, you are correct it's coming from WordPress.com. I'll close this ticket, thanks!
