### ISSUE TITLE
Adding Block Labels

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2428]
This is kind of an extension of #2413. Even though in my mind at the time I opened the ticket was that there was no visual approximation, the more I thought about it seemed to me that the real issue is that there is no visual identification of blocks.

Certain ones will be obvious (e.g. picture, video, list, etc.) but others like a regular Paragraph Block and Verse Block may not be so obvious to users. 

![image](https://user-images.githubusercontent.com/12448364/29326481-a8492826-81b9-11e7-99d7-a42597213fb9.png)

In looking at this screen shot above at first glance there really is no visual difference besides some slight indenting and what looks to be a darker typeface color. 

![image](https://user-images.githubusercontent.com/12448364/29326498-bc210b0c-81b9-11e7-8fa2-f4777243b34a.png)

There is some differentiation between them when selected with the option buttons different in a paragraph (above) and verse (below). But that relies on the user recognizing the difference and knowing "Oh, those options means this is an X block."

![image](https://user-images.githubusercontent.com/12448364/29326505-c96efb0c-81b9-11e7-9f88-2b921c664d27.png)

My proposal is to add a label to these options so that it only appears when the block is selected and hopefully does not add much noise to the UI as demonstrated below.

![image](https://user-images.githubusercontent.com/12448364/29327532-7740f8e0-81bd-11e7-9520-dd8f648bf3b3.png)

@nylen posted something like this in the Slack too which I like as well and would think would be an excellent solution since a simple mouse-over will make it appear.
![image](https://user-images.githubusercontent.com/12448364/29326804-f2a09908-81ba-11e7-9b9b-8a3c51b95870.png)

**Comment by karmatosed** [comment]
Thank you first for doing some mocks of this. I must say, I'm not sold this is something to add. That all said. I do think in testing we will find out if people are having an issue and we need to iterate by adding indications. I would suggest we pause on this, until we have testing feedback that indicates either direction.

**Comment by karmatosed** [comment]
For now, lets close this. We can iterate with user feedback, but we need to keep a focus on v1 and this issue has not come up enough in testing (so far) to implement. If this indeed does then we of course can open again.
