### ISSUE TITLE
Template Part E2E test inconsistently failing/passing

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#24281]
**Describe the bug**
I've noticed this test failing sporadically on CI jobs:
```
FAIL packages/e2e-tests/specs/experiments/template-part.test.js (49.087s)
  ● Template Part › Template part block › Should load customizations when in a template even if only the slug and theme attributes are set.

    TimeoutError: waiting for XPath "//button[contains(text(), "header")]" failed: timeout 30000ms exceeded

      46 | 				'.components-dropdown-menu__toggle[aria-label="Switch Template"]'
      47 | 			);
    > 48 | 			const switchToHeaderTemplatePartButton = await page.waitForXPath(
         | 			                                                    ^
```

Would be great to figure out what the issue is and fix the test.

**Comment by youknowriad** [comment]
cc @noahtallen @Addison-Stavlo

**Comment by noahtallen** [comment]
Replicated this issue here: https://github.com/WordPress/gutenberg/runs/960117693?check_suite_focus=true

**Comment by Addison-Stavlo** [comment]
This is interesting.  I can't seem to reproduce it locally after trying limited network and slowmo settings as well.  🤔 

I think @ockham and I saw this fail in CI when we were removing some initial state for edit-site, but iirc couldn't repro locally then either and it seemed to clear up in CI at the time. 🤷‍♀️   I wonder if @epiqueras has any ideas here as the original author for the test, but it does seem a bit strange.

**Comment by epiqueras** [comment]
The template part is not loading fast enough for some reason. What happens if you increase the timeout?

**Comment by noahtallen** [comment]
I'll open a PR for that

**Comment by noahtallen** [comment]
🤔 The timeout is: `timeout 30000ms exceeded` w.r.t finding the text "header" in the dropdown. Thing is, if I try this locally, it should be loading within 2 seconds. I feel it might not be this timeout.. Maybe the dropdown is not opening correctly?

**Comment by noahtallen** [comment]
has anyone noticed this recently?

**Comment by youknowriad** [comment]
It's been sometimes I haven't seen this particular test fail personally.

**Comment by youknowriad** [comment]
Actually, I just had this again.

**Comment by talldan** [comment]
Haven't seen this fail for a while, so closing.
