### ISSUE TITLE
Add a vendor pattern to the markdownlint ignore config

### ISSUE THREAD

**Issue by jshwlkr** [WordPress/gutenberg#24295]
**Is your feature request related to a problem? Please describe.**
If you have a vendor folder, from composer, `wp-scripts lint-md-docs` will lint all the readmes, etc. 

**Describe the solution you'd like**
Slip a `**/vendor/**` pattern in the lint-md-docs.js.

**Comment by gziolo** [comment]
Opened #26450 to address this issue, thank you for your report.
