### ISSUE TITLE
In wp-env installing plugin via ZIP, not from wp.org, creates an invalid file path for plugin

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#24291]
I am a WordPress plugin developer who is developing an add-on for a plugin on WordPress.org. I imagine this is a fairly common behaviour.

I'm using wp-env for local development. When I add a plugin, using a download from wordpress.org, it works as expected. When I use a link from Github -- I need to test with a beta version of the plugin -- the download link URL includes the 

## How To Reproduce

I am sorry that the source repo for this is private. I hope this is enough to understand isssue, I can provide more info if needed.

###  .wp-env.json Without Bug

Using latest -- released version of Ninja Forms from WordPress.org:

```json
{
	"plugins": ["https://downloads.wordpress.org/plugin/ninja-forms.zip", "."],
	"config": {
		"WP_DEBUG": true,
		"WP_DEBUG_LOG": true,
		"WP_DEBUG_DISPLAY": false
	}
}

```

This installs the plugin at /wp-content/plugins/ninja-forms. This expected behaviour.

###  .wp-env.json With Bug

Download a beta version of Ninja Forms, using a public Github link (yes I know it's in Caldera Forms' repo, we're moving things around right now)

```json
{
	"plugins": [
		"https://github.com/CalderaWP/Caldera-Forms/files/5002105/ninja-forms.zip",
		"."
	],
}
```

This installs the plugin at `/wp-content/plugins/github.com%2FCalderaWP%2FCaldera-Forms%2Ffiles%2F5002105%2Fninja-forms/`. That is fine for php files, but it doesn't create valid URLs for JS/CSS/images 

![Annotation 2020-07-30 113438](https://user-images.githubusercontent.com/1994311/88942911-dfaf8b00-d258-11ea-829f-476e9288234d.jpg)

## Expected behavior

I would expect the plugin to be installed with out the ZIP download in the file path

## Versions
- @wordpress/env: "^1.3.0",
- @wordpress/scripts: "^7.1.2",
- WordPress version: Version 5.4.2
- Does the website has Gutenberg plugin installed: NO, it does not.
 - OS: Windows
 - Browser: Chrome

**Comment by noahtallen** [comment]
Related: #22093
