### ISSUE TITLE
Feature requests for media rich long-form articles

### ISSUE THREAD

**Issue by carstenheisterkamp** [WordPress/gutenberg#2430]
Hi,

I hope this is the right place to put these feature requests and that they are not out of scope of Gutenberg plugin.  I would like to suggest some features especially for rich media long form articles that would make Gutenberg a great alternative to atavist, pageflow and other long form solutions. Some of them are already in, in a basic form (Cover Video, Cover Image, Video, Audio) but it would be great if the following additions could somehow make it as settings into the blocks.

As a reference and example for what could be achieved with this:
http://www.travelepisodes.com/reise/kirgisistan-tienschangebirge-nomaden/

1. Cover video 
A local video with (important) audio. Although some regard this as annoying it is a great way to set the mood of a story.

- Overlay for Title and Intro Text / Author / Date
- autoplay option, video stops when out of view
- option dim/fixed similar to Cover Image
- “mute” option to start with or without sound (but user can unmute it).

2. HTML5 Audio Block
for local audio files. Again I know that this can be annoying, but it is essential for telling media rich stories “on scroll”
- with a css option to style or hide controls
- “autoplay” option, can stopped manually by user
-  “autoplay in view” option. Starts / stops / continues when in / out of view
- “loop” option

3. HTML5 Video Block
Same as for Audio
- with a css option to style or hide controls
- “autoplay” option, can stopped manually by user
- “autoplay in view” option. Starts / stops / continues when in / out of view
- “loop” option
- Poster if set to autoplay off

4. Cover image Block
- add optinal Intro Text / Author / Date to. Its currently title only.

5. User settings / help Block
for autoplay and other settings for users reading experience and barrier free reading / accessibility
- autoplay on / off globally
-  Font size / Zoom
-Contrast

6. Table of content Block
A block which takes the h2 as article chapters and a link to them to access them directly e.g. scrollto.

Thanks, C.

**Comment by karmatosed** [comment]
I think we have most if not all of these right now in the latest version? Let's close this and review what we don't maybe? We can always reopen.
