### ISSUE TITLE
File block - Can't upload pdf file using Upload button but can using Media Library link 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#24315]
**Describe the bug**
The file block does not allow PDF uploads through the upload button but does through media library. 

**To reproduce**
1. create new post or page
1. add file block
1. Click upload 
1. select a pdf file 
1. See error - "Sorry, this file type is not supported here."  this error message is sourced at https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/media-utils/src/utils/upload-media.js#L143

**Expected behavior**
If repeat steps 1-2, but then upload through the media library, the file is successfully uploaded. 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4, 
- using gutenberg plugin; from master branch, most recent commit 456e1c4e13d38ca0b4365a8399c5678442d2bee0 from 2020-07-30

note, slightly different than #23510 (that error message is "the file type is not allowed for security reasons"

in my case, when I issue `wp.data.select('core/editor').getEditorSettings().allowedMimeTypes;` in the console, 
pdf is listed.

**Comment by annezazu** [comment]
Thanks for reporting this @skorasaurus! Confirming that I replicated this with Gutenberg 8.6.1.
