### ISSUE TITLE
Google Chrome doesn't allow fullscreen for Vimeo embed

### ISSUE THREAD

**Issue by justinlucaswatson** [WordPress/gutenberg#24319]
Using the Vimeo embed, the fullscreen icon is preserved in the preview but is removed on the frontend.

It appears that the Vimeo embed adds _allow="autoplay; fullscreen"_ and _allowfullscreen_. 

Using the Custom HTML block, I can insert the embed code straight from Vimeo and modify it for troubleshooting. If I remove  _fullscreen_ from the _allow=""_ and add _mozallowfullscreen webkitallowfullscreen_ before the _allowfullscreen_, the fullscreen icon is preserved on frontend and functions as expected. However, this method isn't helpful for the client and doesn't retain the great aspect ratio preservation that the Vimeo embed employs. 

Any chance for a fix or any way to extend embed block in functions.php?

**Comment by jordesign** [comment]
Closing this issue as I can no longer recreate it. Fullscreen button shows in the new style of Vimeo embeds.
