### ISSUE TITLE
Block Focused When Inserting New Block

### ISSUE THREAD

**Issue by timmyc** [WordPress/gutenberg#2432]
I searched existing issues and could not find this being mentioned, but honestly I'm not entirely sure this is a bug or not... but each time I encounter it, it feels a bit _off_ to me, so figured I'd open an issue and see what others thought.

__Steps__
- Focus a block, in the screen shot below, a text block
- Then click the (+) block inserter
- Note the old block remains in a focused state
- What I expected to happen, the block to be "un-focused"

![focus](https://user-images.githubusercontent.com/22080/29330196-4cd76360-81ad-11e7-8505-18ad30c7f171.gif)

So question is - is this intended behavior or something that should be changed to meet my expectation of the block being un-focused?

**Comment by youknowriad** [comment]
I think it's intended that the block remains "selected" (in terms of state value) but we should probably hide the selected UI somewhere (same behavior as if we were typing in a block)

**Comment by rachelmcr** [comment]
I had the same experience while trying out Gutenberg on my iPad. It felt "off" and a bit busy to see the format bar above the selected block while also seeing the "Insert Block" UI below it:

![photo 23-08-2017 17 56 02](https://user-images.githubusercontent.com/8658164/29630686-e9d5205c-8834-11e7-931c-0ccef074d037.png)

Tested on an iPad Mini, iOS 10.3.3, in Safari.

**Comment by karmatosed** [comment]
I would +1 to only focusing the action area someone is in.
