### ISSUE TITLE
Using `/code` blocks expand media

### ISSUE THREAD

**Issue by esquireofoz** [WordPress/gutenberg#24329]
**Describe the bug**
Using the `/code` block in the visual editor expands image links if the URL is on its own line and there is free text both above and below it

**To reproduce**
1. Create a new post
2. Type `/code` to produce a new code block
3. Produce text which matches the description of the bug - [here](https://bugsquashing.wordpress.com/2020/07/31/under-the-sea/) is an example of the behavior.
4. See the expanded images

**Expected behavior**
It is expected `/code` blocks only result in plain text representing code and do not embed media types.

**Screenshot**
![image](https://user-images.githubusercontent.com/1720231/89187725-a7b38b00-d56b-11ea-8703-b3f1daf5c7d2.png)

**Editor version (please complete the following information):**
- WordPress version: WordPress.com hosted blog
- Gutenberg: 8.3.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 84.0.4147.89

**Comment by talldan** [comment]
@esquireofoz I couldn't reproduce this in my local development environment, here's an example of a code block with image urls on new lines:
<img width="615" alt="Screenshot 2020-08-05 at 5 19 39 pm" src="https://user-images.githubusercontent.com/677833/89395517-04679f00-d740-11ea-9afd-a0dcf0fab918.png">

are you sure it's not a WordPress.com specific issue? I also left a comment on Automattic/p2tenberg#385

**Comment by esquireofoz** [comment]
@talldan - I also tested with on local development environments against the latest WordPress 5.x version branches and obtain the same results you do.  Due to this, I am going to close this issue.
