### ISSUE TITLE
Classic block: can't get out of HTML mode

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#24331]
**To reproduce**
1. Add a Classic block with some content inside.
2. Switch to _Edit as HTML_ via the block's toolbar.
3. Select a different block.
4. Select the Classic block again.

**Observed**
The block's toolbar is unavailable, and thus there is no way to return to Visual mode. Notice also how the block's name doesn't show in the editor's breadcrumbs (bottom-left corner of the page).

**Expected behavior**
The toolbar should remain visible as it was at the end of step 2.

**Recovery**
The only possible steps to recover from this failure are:
* Either delete the block with `Ctrl-Z`
* Switch to global Code Mode, edit the classic contents, and switch back to Visual.

**Environment**
Affects both the latest plugin version and WP core (5.5) as of today.

**Screenshots**
<img width="628" alt="Captura de ecrã 2020-08-03, às 14 48 59" src="https://user-images.githubusercontent.com/150562/89190433-5ae6a900-d599-11ea-8340-82b26f745bef.png">
<img width="461" alt="Captura de ecrã 2020-08-03, às 14 49 14" src="https://user-images.githubusercontent.com/150562/89190438-5d490300-d599-11ea-8559-673c1b1ddfcf.png">
<img width="387" alt="Captura de ecrã 2020-08-03, às 14 49 22" src="https://user-images.githubusercontent.com/150562/89190442-5de19980-d599-11ea-912b-884850b1c394.png">
<img width="303" alt="Captura de ecrã 2020-08-03, às 14 49 33" src="https://user-images.githubusercontent.com/150562/89190444-5e7a3000-d599-11ea-8468-e9db1fc33b36.png">

**Comment by ntsekouras** [comment]
Probably related: https://github.com/WordPress/gutenberg/issues/23511

**Comment by mcsf** [comment]
> Probably related: #23511

Seems definitely related.

**Comment by ntsekouras** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/24335
