### ISSUE TITLE
Applying Firefox spelling correction causes italicization to be removed

### ISSUE THREAD

**Issue by bluefuton** [WordPress/gutenberg#24344]
**Describe the bug**
In Firefox (v79.0), choosing a spelling correction in a block of italic text causes the italic styling to be partially lost.

![2020-08-04 12-31-45 2020-08-04 12_34_23](https://user-images.githubusercontent.com/17325/89240113-41a03400-d64f-11ea-8cad-6872c19177bf.gif)
 
**To reproduce**
1. Create a new paragraph block, enter text containing a spelling error, then select all of the text and make it italic. 
2. Right click on the misspelled word and choose the correct spelling.
3. The italic styling may have been removed from some of the text when the spelling correction was applied.

**Expected behavior**
Applying a spelling correction does not affect the styling of the text.

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] WordPress 5.6-alpha-48715 (nightly)
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Default

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.15
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 79

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I'm no longer able to reproduce this on Firefox using a newer version of Gutenberg; as shown in the video below. Please reopen this issue if you are still experiencing this. 

https://user-images.githubusercontent.com/955351/123996703-97837600-d99d-11eb-85db-7505757d09c2.mp4

**Comment by bluefuton** [comment]
Thanks @skorasaurus - looks fixed to me!
