### ISSUE TITLE
Gallery: Add option to crop according to image width

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2434]
Right now, the crop feature of the gallery crops images according to height. For example, if you have 4 images in a 2 column gallery, first is portrait, 2nd is landscape, 3rd is portrait, 4th is landscape, right now you get 4 vertical rectangles:

![crop-by-height](https://user-images.githubusercontent.com/1204802/29358224-86df4af0-827a-11e7-974b-ce8c94ff0d8a.png)

It would be nice if there was an option to let you crop _by width_ instead, so you got this:

![desired-crop-by-width](https://user-images.githubusercontent.com/1204802/29358245-98e32c26-827a-11e7-85d8-791544b95a5f.png)

There's a PR here that adds the toggle option, but the CSS isn't yet functional: https://github.com/WordPress/gutenberg/pull/2433

In https://github.com/WordPress/gutenberg/pull/2433 I've explored some CSS to make this happen, but it's not very functional.

Would appreciate CSS input on how to best accomplish this type of gallery.

**Comment by aduth** [comment]
This was discussed in the #core-editor weekly triage meeting: https://wordpress.slack.com/archives/C02QB2JS7/p1522944988000379

Own thoughts:

>Maybe `imageCrop` attribute shouldn’t be boolean, but rather enum of `width` or `height` ?

**Comment by jasmussen** [comment]
As a bit of repository management, I'm going to close this ticket and file it in the "Ideas" project so we can revisit this in the future: https://github.com/WordPress/gutenberg/projects/8
