### ISSUE TITLE
Image Block - Format Bug in Icon Aspect Ratio?

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#24358]
I tested the Image Block in WP 5.5RC2 with "Crop".

Then the Icon "Aspect Ratio" is not in the middle.
Also in Gutenberg 8.6.1
![Bildschirmfoto 2020-08-04 um 21 28 15](https://user-images.githubusercontent.com/6922544/89339958-4bea1e80-d69f-11ea-808c-7a50861421ea.png)

But in Gutenberg 8.7.0-rc.1 its fine.
![Bildschirmfoto 2020-08-04 um 21 45 09](https://user-images.githubusercontent.com/6922544/89340067-7340eb80-d69f-11ea-96ca-35e6ec085112.png)

Whats the new Pull Request?

**Comment by Soean** [comment]
The issue was fixed in #24343
