### ISSUE TITLE
Button block style preview has unintended vivid-green-cyan background color

### ISSUE THREAD

**Issue by mypacecreator** [WordPress/gutenberg#24365]
**Describe the bug**
﻿A preview of button block styles, each style has a 'has-vivid-green-cyan-background-color' class and an inline style 'background-color: rgb(0, 208, 132)'.

**Screenshots**
![button block preview style](https://user-images.githubusercontent.com/3164205/89371421-4a137000-d71e-11ea-882a-1c7aa83d2ad5.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5-RC1-48708
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? : default

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome 84, Firefox

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; this has already been reported at https://github.com/WordPress/gutenberg/issues/21954

**Comment by ellatrix** [comment]
Let's close duplicate issues.
