### ISSUE TITLE
wp-block paragraph renders empty <p> element if it has no content

### ISSUE THREAD

**Issue by StudioRATATA** [WordPress/gutenberg#24373]
Hey all,

This is new to me, so I hope I report this right. 

- The gutenberg block `paragraph` renders an empty `<p>` element if it has no content. 
- Would it be possible to save it conditionally?

If you change file: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/paragraph/save.js
 
And change line 19/26

From:
```	
        return (
		<RichText.Content
			tagName="p"
			className={ className ? className : undefined }
			value={ content }
			dir={ direction }
		/>
	);
```
To:
```
         return (
		{content &&
                <RichText.Content
			tagName="p"
			className={ className ? className : undefined }
			value={ content }
			dir={ direction }
		/>}
	);
```
It would only save if it has content to save, right? So, if no content, no p element.

**Comment by skorasaurus** [comment]
Thank you for reporting; this has already been reported at https://github.com/WordPress/gutenberg/issues/18297
