### ISSUE TITLE
Add a way to subscribe to style changes

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#24383]
When building different block styles it would be great to be able to make additional things in the editor happen when the block style gets changed. Therefore it would be great to add a way to receive the current active block style through the data api.

**Comment by ellatrix** [comment]
Wouldn't it be possible to retrieve the block attributes from the store?

**Comment by fabiankaegy** [comment]
Aren't the styles only stored in the className? So you probably can split `props.className` and retrieve the style name from looking for the `is-style-STYLENAME`. But this feels rather fragile and I feel like could be easier :) 

(Of course I could be missing something :) )

**Comment by ellatrix** [comment]
What's the use case for it?

**Comment by fabiankaegy** [comment]
@ellatrix The issue that I was having, is that I wanted to change defaults and attributes for a block based on the block style.

For example looking at the block styles of a core/button block I would want to change the current border radius when the square option is selected and vise versa. 

In my experience since opening this ticked I have leaned very heavily on the Block variations because it allows these attribute changes based on the variation change. But it would be nice to have the best of both worlds. The nice preview and UI from Styles with the API and flexibility of the variations api.

**Comment by fabiankaegy** [comment]
Block variations always were a better solution for this. Closing.
