### ISSUE TITLE
Table Block: Table Headers shouldn't default to break-word

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#24393]
**Describe the bug**
Table Headers (th tags) are explicitly set to break words, which can cause the table to look weird if the columns should have different widths. The screenshots say it best.

**To reproduce**
1. Create a new table in a post or page. For example, try "Workshop, Ages, Description, Times" as table headers. Add a few rows with data a table like that might have.
2. Make sure cells are not "Fixed" (as that for now means "evenly distributed" which would not be best for this table)
3. Publish (or preview) the page.

**Expected behavior**
In the editor, I see the expected behavior: 
![Screen Shot 2020-08-05 at 6 03 32 PM](https://user-images.githubusercontent.com/3476361/89475710-ff0d5300-d745-11ea-99a0-e48633544055.png)

The table columns adjust to fit the content.

But, depending on the theme's content width, the table headings may break in awkward ways. See screenshots below from a handful of themes.

**Screenshots**
![Screen Shot 2020-08-05 at 6 05 10 PM](https://user-images.githubusercontent.com/3476361/89475810-3c71e080-d746-11ea-9c70-be8a14c1b01a.png)

![Screen Shot 2020-08-05 at 6 08 13 PM](https://user-images.githubusercontent.com/3476361/89475987-b30ede00-d746-11ea-9725-b26100a4f772.png)

![Screen Shot 2020-08-05 at 6 12 21 PM](https://user-images.githubusercontent.com/3476361/89476168-3fb99c00-d747-11ea-8b36-b01ed0b1557a.png)

**Editor version (please complete the following information):**
Gutenberg plugin 8.3.0 (also happens without it)

**Desktop (please complete the following information):**
 - OS: MacOS Current
 - Browser: Chrome Current

(But break-word seems to happen regardless of browser, because we specified it in the CSS.)

**Additional context**
This came up in a support request on the .com forums. Normally we'd just tell them to edit the HTML to adjust the width for that cell, but right now the block doesn't want to accept any HTML editing.

I can see we explicitly opted to break-words, possibly to avoid long links making widths too wide if people paste long links in the table data. But, could we at least not break the headers? This fixes the issue nicely:

```
.wp-block-table.aligncenter th {
    word-break: normal;
}

```

**Comment by talldan** [comment]
When testing, I could only reproduce this if the table block has an alignment (e.g. align center). When not aligned the table block should be scrollable horizontally.

**Comment by supernovia** [comment]
Sorry I'm just seeing this. The table headers are aligned center by default, correct?

**Comment by t-hamano** [comment]
Hi @supernovia,

Sorry for the delay in my investigation into this issue.

In the table block, no text-align property is set for the cells. Therefore, the table header cell text will be centered according to the browser's default style. And `word-break: break-word` applies only when table cells are fixed or aligned left, center, or right.

https://github.com/WordPress/gutenberg/blob/4f94f097ecf52d145db4563e2da3352c19cb02e2/packages/block-library/src/table/style.scss#L30-L55

I think the default table would not have this problem. Here is the markup data used for the test.

<details>
<summary>Test Data</summary>

```html
<!-- wp:heading -->
<h2 class="wp-block-heading">Default</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Workshop</th><th>Ages</th><th>Description</th><th>Time</th></tr></thead><tbody><tr><td>Bag O'cells</td><td></td><td></td><td></td></tr><tr><td>Bee Safari</td><td>All</td><td>Join our facilitator outdoors to learn hou to spot and identify bees and others pollinators in local gardens.</td><td></td></tr><tr><td>Combinatorics</td><td></td><td></td><td></td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading -->
<h2 class="wp-block-heading">Center Aligined</h2>
<!-- /wp:heading -->

<!-- wp:table {"align":"center"} -->
<figure class="wp-block-table aligncenter"><table><thead><tr><th>Workshop</th><th>Ages</th><th>Description</th><th>Time</th></tr></thead><tbody><tr><td>Bag O'cells</td><td></td><td></td><td></td></tr><tr><td>Bee Safari</td><td>All</td><td>Join our facilitator outdoors to learn hou to spot and identify bees and others pollinators in local gardens.</td><td></td></tr><tr><td>Combinatorics</td><td></td><td></td><td></td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading -->
<h2 class="wp-block-heading">Left Aligined</h2>
<!-- /wp:heading -->

<!-- wp:table {"align":"left"} -->
<figure class="wp-block-table alignleft"><table><thead><tr><th>Workshop</th><th>Ages</th><th>Description</th><th>Time</th></tr></thead><tbody><tr><td>Bag O'cells</td><td></td><td></td><td></td></tr><tr><td>Bee Safari</td><td>All</td><td>Join our facilitator outdoors to learn hou to spot and identify bees and others pollinators in local gardens.</td><td></td></tr><tr><td>Combinatorics</td><td></td><td></td><td></td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading -->
<h2 class="wp-block-heading">Right Aligined</h2>
<!-- /wp:heading -->

<!-- wp:table {"align":"right"} -->
<figure class="wp-block-table alignright"><table><thead><tr><th>Workshop</th><th>Ages</th><th>Description</th><th>Time</th></tr></thead><tbody><tr><td>Bag O'cells</td><td></td><td></td><td></td></tr><tr><td>Bee Safari</td><td>All</td><td>Join our facilitator outdoors to learn hou to spot and identify bees and others pollinators in local gardens.</td><td></td></tr><tr><td>Combinatorics</td><td></td><td></td><td></td></tr></tbody></table></figure>
<!-- /wp:table -->
```

</details>

When the browser width is greater than the content width, header cell text will not wrap, except for the center-aligned table.

<details>
<summary>Screenshot</summary>

![screenshot-1](https://user-images.githubusercontent.com/54422211/216742240-620e3a3d-f295-4e48-9326-851ef5ff53d9.png)
</details>

When the device is narrow, the default table header cell text will not wrap and horizontal scrolling will occur.

<details>
<summary>Screenshot</summary>

![screenshot-2](https://user-images.githubusercontent.com/54422211/216742370-f177d4f7-8d56-4e05-b0be-a82557f2a2f1.png)
</details>

Are these the behaviors you expect?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏

**Comment by sabernhardt** [comment]
Whether the words break can depend on the theme's styles or template:
- The forum reporter's site assigns `word-wrap: break-word` to `.entry-content` and other containers in one of its stylesheets (possibly a WordPress.com addition to the Franklin theme).
- On [Trac 63721](https://core.trac.wordpress.org/ticket/63721), wwccscorer reported that `word-wrap: break-word` from the [Column block styles](https://github.com/WordPress/gutenberg/blob/7d045178de5879471793a627efeadfc1225073cb/packages/block-library/src/columns/style.scss#L94) affects tables. In that case the theme was Twenty Twenty-Three, but it could also happen in many other block themes and in block patterns.

The Columns block added `word-wrap` for 'back-compat' in #11904. Modern browsers might only need `overflow-wrap` for the original purpose, though people might like `word-wrap` now for _some_ content (not just tables) within a Column block.

**Comment by t-hamano** [comment]
Maybe it would be nice to be able to define `word-break` or `overflow-wrap` on a block-by-block basis.

See https://github.com/WordPress/gutenberg/issues/11956
