### ISSUE TITLE
Gallery block - Pagination

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2441]
Would like to ask for a new feature. Pagination for galleries with to many images. Can come handy in variation of cases.
As example when photographer follows one event, say music concerts, festivals, etc...To be able to split galleries with to many images end easy page load.

To not be forced to make several posts for same event, just to satisfy new Google rules.

PS: I know it is challenge, if not impossible, to make any javascript gallery slideshow to "jump" from one gallery paginated page to next and continue to slide. Without calling all images on page load, what would defeat purpose of pagination. But better anything than nothing (pagination).

**Comment by StaggerLeee** [comment]
I know <! --nextpage--> can be used, now as a block in Gutenberg. And pagination styling left to theme.
Sad truth is website owners do not care, or do not know how to use it, majority of them.

**Comment by karmatosed** [comment]
I don't think right now galleries need this. To me after thinking about this, it's plugin territory. I can see a really nice custom block / plugin to do this though.
