### ISSUE TITLE
Can't find a reference to the getUser function.

### ISSUE THREAD

**Issue by josephjoice** [WordPress/gutenberg#24412]
**Describe the bug**
In wordpress `5.4.2` I can see the function `wp.data.select('core').getUser(user_id)` works. I can see a reference to the same function in https://github.com/WordPress/gutenberg/blob/b0e6f41c1840f90a121e4aad6372983e165e8c88/packages/block-library/src/post-author/edit.js#L26 also. 

But in the `core-data` I don't see the function at all. What am I missing here? I see that `blocks-library` is referring to not any particular version, but relative path to the core-data folder.

Wordpress `5.4.2` is using `2.12.3` of core-data package, but that version is also not having the `getUser()` function. 

I am definitely missing something basic here or **magic is real** . Any help is appreciated.

**Comment by pvogel2** [comment]
May be it is added here: https://github.com/WordPress/gutenberg/blob/09f77300f17e77825ad8f131ea2f4474bf69ee73/packages/core-data/src/index.js#L26

Some default entity selectors are added generically via getMethodName I think. And user is one of the default entities.

**Comment by talldan** [comment]
@josephjoice, @pvogel2's comment is correct here, entity methods are generated using `getMethodName`. It is a little magical, and I think it has been discussed in the past about how these APIs are hard to search for (though I don't have any links to those discussions.

I'll close the issue as it seems the question has been answered.
