### ISSUE TITLE
wp_die - Messages

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2442]
One of the forgotten parts of WordPress. And not so apealing.
I do have some snippets for post edit screen using wp_die.

Now when you refurbish much, is it time to reconsider how wp_die messages are shown ? A bit more modern, in pace with time, not as separate screen, window.

I personally like how you show this error message:
![Image of Yaktocat](https://user-images.githubusercontent.com/12448364/29197548-4a5624f6-7e0a-11e7-85cf-fb353241cf9c.png)

Maybe it can be used for wp_die to, bigger modal box, unconditionally centered on screen, differentiate subtle background-color(s) for different errors, etc...

I know in this case context is a bit strange. User would need to stay on same page, opacity changed, modal wp_die showed. Do not know how much this "context" goes against your coding, design rules.

But at the other side, old wp_die is not much of context too, I personally could live without it.

**Comment by mtias** [comment]
This will be better to raise in core trac, as it applies to the whole project and not just gutenberg.
