### ISSUE TITLE
If user will not entered the text then link should not active on blank button.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#24441]
**Describe the bug**
If the user will not enter the text then the link should not active on the blank button.

**To reproduce**
1. Go to 'editor.'
2. Click on 'button 'block
3. Add the button block and add the link on the blank button.
4. Clicking on the preview button.
5. See the button.

**Expected behavior**
If the user will not enter the text then the link should not active on the blank button.

**Please find the below attached video**

https://www.loom.com/share/8f53eb75335c415d8e51eec1a917c2f9

**Editor version (please complete the following information):**
- WordPress version: [5.5 RC2]

**Comment by talldan** [comment]
Isn't the answer to not add an empty button?
