### ISSUE TITLE
ComboboxControl have not exported

### ISSUE THREAD

**Issue by javadsamiee** [WordPress/gutenberg#24443]
**Describe the bug**
I want to use ComboboxControl and I got error then after the check of components exports I found, it has not exported

**To reproduce**
Copy/past handbook example
https://developer.wordpress.org/block-editor/components/combobox-control/

**Editor version (please complete the following information):**
- WordPress version: 5.4.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.7.0

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser chrome
 - Version 84.0.4147.105

**Comment by talldan** [comment]
@javadsamiee I'm not sure what the final state of this component is, whether it's ready for public use.

Ideally the docs wouldn't have been published if it's still considered in development.

I left a comment on the PR that implemented the component - https://github.com/WordPress/gutenberg/pull/19657.

**Comment by adamsilverstein** [comment]
Hi @javadsamiee - thanks for raising this.

The component is now exported as of https://github.com/WordPress/gutenberg/pull/25442 (see https://github.com/WordPress/gutenberg/pull/25442/files#diff-5024897ca9c78ec120fc210faa8ab3adR33). Closing this as resolved. 

If I have missed something, please feed free to reopen.
