### ISSUE TITLE
Pullquote: when we change the main colour then the text of Pullquote is not visible 

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#24440]
**Describe the bug**
in Pullquote when we select the solid colour style and we set the main colour as black then text colour automatically set to cream colour and we unset the main colour then the text colour is not getting changed to default colour, because of that we are not able to view the text of Pullquote.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Pullquote'
5. Select the Style 'Solid color'
6 Set the main colour 'black'
7. Unset the main colour
8. See error

**Expected behaviour**
when we unset the main colour then the text colour should be the default colour so we can view the text of Pullquote.

**Screenshots**
https://prnt.sc/tvn4la
https://prnt.sc/tvn53e

**Video**
for more detail please view the attached video
https://www.loom.com/share/165a6ddfde9b4322be055068a57d6549

**Editor version (please complete the following information):**
- WordPress version: 5.5-beta1
- default

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by ntsekouras** [comment]
Thanks for reporting this @kmadhak!
