### ISSUE TITLE
[Full Site Editing] Block inserter randomly turns into a black box

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24449]
**Describe the bug**

While navigating around a FSE test, the block inserter turned into a black square rather than showing the + sign. 

**To reproduce**

I am not quite sure what caused this. I was able to easily replicate it by focusing on the block below the navigation block (empty text block) and backspacing back into the navigation block. However, it happens in more circumstances. Here's a GIF:

![black box](https://user-images.githubusercontent.com/26996883/89692376-5df6d780-d8c0-11ea-82f4-ea3e2bb5e5de.gif)

^ The flashing is me hovering over the box to show the disparity. 

**Expected behavior**

I expect the inserter to remain the same. 

**Screenshots**

Here's a video: https://cloudup.com/crgtYpk8UWq

Screenshots:

<img width="651" alt="Screen Shot 2020-08-07 at 4 09 23 PM" src="https://user-images.githubusercontent.com/26996883/89692269-07899900-d8c0-11ea-8ba0-d4441097938e.png">
<img width="647" alt="Screen Shot 2020-08-07 at 4 09 38 PM" src="https://user-images.githubusercontent.com/26996883/89692270-08222f80-d8c0-11ea-86b0-3e03a5c5b075.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5-RC2-48740.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg installed 
- If the Gutenberg plugin is installed, which version is it? 8.7

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 84.0.4147.105

**Comment by ntsekouras** [comment]
Hey @annezazu! I tried to reproduce but couldn't.. - Is this still happening? Can you share more info about reproducing it?

**Comment by annezazu** [comment]
Hmm I now can't replicate either but found another bug :D I'll close this out for now but will re-open if I stumble upon it again.
