### ISSUE TITLE
Separator: The effect of colour is only visible when we lost the focus from the Separator block to other block

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#24444]
**Describe the bug**
In Separator when we change the colour then it only affect the middle of the separator but when we lost the focus from Separator to other block then the colour effect is visible in whole Separator block

**To reproduce**
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Separator'
5. Select the style 'Default / Wide Line'
6. Set the colour 'brown/silver'
7. See error

**Expected behavior**
The effect of colour should be in whole block instantly not after the lost focus  

**Screenshots**
https://prnt.sc/tvncud
https://prnt.sc/tvncud

**Video**
for more detail please view the attached video
https://www.loom.com/share/3197ab90d1cd4468a1cbd37f117aa5b1

**Editor version (please complete the following information):**
- WordPress version: 5.5-beta1
- default

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by aristath** [comment]
I just tested this with the master branch and can't replicate the issue, it was fixed in https://github.com/WordPress/gutenberg/pull/24366

The change didn't make it in WP5.5 so it should be included in the next update :+1:
