### ISSUE TITLE
Cover Block: Block styles bleeding into nested image blocks

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#24458]
**Describe the bug**
When using cover block with top/bottom wave block style, the wave is also being applied to images nested inside the cover block. Related to #23198

**To reproduce**
1. Create a post/page and add a cover block. Apply top or bottom wave block style.
2. Inside the over block insert an image block.
3. Note how the image is inheriting the top/bottom wave.

**Expected behavior**
For the wave to not be applied to the nested image.

**Screenshots**
![image](https://user-images.githubusercontent.com/4550351/89750211-5c225380-db0e-11ea-8de7-49570dc6367e.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg: default
- Theme: TwentyTwenty

**Comment by kathrynwp** [comment]
@alaczek Hi! I'm not seeing any wave options for the Cover block at the moment. Could you please confirm whether those are coming from WP Core, Gutenberg, or a third-party plugin like CoBlocks? Thanks!

Tested with:

WordPress 6.0.1
Gutenberg 13.7.3 active or inactive
No other plugins active
Twenty Twenty 2.0 or Twenty Twenty-Two 1.2

**Comment by kathrynwp** [comment]
@alaczek I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.

**Comment by alaczek** [comment]
Yes, the wave style was coming from CoBlocks. The issue can be closed.
