### ISSUE TITLE
Editor unexpected error when opening menu, can't click to see the error

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#24456]
When I click the three dots at the top right I see the unexpected error message. None of the options work, attempt recovery, etc. Open console to see why and there are about 20,000 errors and climbing. Mainly this. 

```
TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList
    at t.exports (index.js?ver=74986d8e8b9b7cb95a57115692ed96d0:1)
    at e.value (index.js?ver=74986d8e8b9b7cb95a57115692ed96d0:1)
    at new e (index.js?ver=74986d8e8b9b7cb95a57115692ed96d0:1)
    at index.js?ver=74986d8e8b9b7cb95a57115692ed96d0:1
    at Vb (react-dom.min.js?ver=16.9.0:104)
    at Xi (react-dom.min.js?ver=16.9.0:151)
    at unstable_runWithPriority (react.min.js?ver=16.9.0:26)
    at Ma (react-dom.min.js?ver=16.9.0:52)
    at Yb (react-dom.min.js?ver=16.9.0:150)
    at react-dom.min.js?ver=16.9.0:140
```

If I pause the debugger, the visual error message disappears, it looks like it's just rapidly creating the dom over and over, like 1000 times a second, making it impossible to interact with. No Idea what could be causing the error, if I deactivate plugins and themes the error persists, until I deactivate the unrelated plugin Web Stories by Google (in beta). However, if I install the same combination of plugins and themes and copy the post content over to to a clean install, everything works fine, for now.

More info, everything works fine in a blank post, I can open the menu just fine. If I type one single letter and then try to open the menu, the error happens.

**Comment by talldan** [comment]
> until I deactivate the unrelated plugin Web Stories by Google (in beta)

@joshm33333 I'd recommend reaching out to the plugin developers:
https://github.com/google/web-stories-wp/issues

That the error goes away when that plugin is deactivated would indicate there's some kind of issue there.
