### ISSUE TITLE
Add block icon is disabled.

### ISSUE THREAD

**Issue by Anjalirai29** [WordPress/gutenberg#24464]
Description: The Add Block button that is + icon is disabled when we add carousel slider block.

**To reproduce**
1. Go to Add Block -  Carousel Block
2. Click on the result
3. Click on Add block icon again
4. It will be disabled.

**Expected behavior**
The Add Block icon should be enabled in order to add some another blocks.

**Screenshots**
https://prnt.sc/tx4jc4

Video: https://www.loom.com/share/f5f8b74e86b44aa78b27ea324c91983c

- WordPress version: 5.5 Beta version 5.5-RC2-48768

**Comment by ellatrix** [comment]
What plugin is adding the Carousel Block? Might be good to contact the plugin author.

**Comment by mtias** [comment]
Closing as the block doesn't come from core.
