### ISSUE TITLE
Having problems with utf-8

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#24477]
**Describe the bug**
I'm having problems with UTF-8 in last version 8.7. It's only in frontend. You can see it in this image:

It's the render of frontend of the plugin. I've deactivated or downgraded and it solves the problem.

**Expected behavior**
Render correctly utf-8 strings like é ó í ...

**Screenshots**
<img width="537" alt="Problems with utf8" src="https://user-images.githubusercontent.com/10096360/89866429-c8a15f00-dbaf-11ea-8dc1-9bf09bb99c3f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg plugin: 8.7

**Comment by aktasfatih** [comment]
This should be resolved in https://github.com/WordPress/gutenberg/pull/24447.

**Comment by ramonjd** [comment]
Was coming here to report the same issue but it looks to be fixed by https://github.com/WordPress/gutenberg/pull/24447

**Comment by davidperezgar** [comment]
Ok thanks.
