### ISSUE TITLE
Group Block: Add a ‘display horizontal’ option

### ISSUE THREAD

**Issue by rickybanister** [WordPress/gutenberg#24473]
When building patterns or trying to achieve a layout with multiple elements arranged horizontally it would help to have a parent block that would automatically arrange its children on a single line. Columns can be used to arrange things side-by-side, but they add quite a lot of extra nesting if you only need to arrange one set of blocks. 

We could leverage the Group block and add a ‘display horizontally’ or ‘act as a row’ option to it. It would wrap its children and act as a ‘flex container’ (`display:flex; flex-direction:row;`). Further `flex` parameters could be optional to align and distribute objects. 

The benefits:

Instead of the complexity and nesting of the first image below, one could achieve a simple horizontal layout like in the second image. 

![Frame 1](https://user-images.githubusercontent.com/437258/89830099-abc24880-db29-11ea-8204-63faab489271.png)

Another benefit would be simplifying the number of areas where a child block could potentially be added. 

![Frame 2](https://user-images.githubusercontent.com/437258/89830117-b250c000-db29-11ea-9b05-ee0159b0a807.png)

The width of the block and its contents would work a little different than columns, which have specified percentage widths. The wrapping block itself would be the full width of its container, but its contents will vary. We should embrace that and provide all the alignment/distribution attributes afforded by `flex`. 

![Frame 3](https://user-images.githubusercontent.com/437258/89830128-b67cdd80-db29-11ea-986f-5f0fdf141899.png)

**Comment by iamtakashi** [comment]
It'd be useful for headers for sure. 

A hover revealing appender with a nice animation applied to the rest of the elements would be cool :)

**Comment by shaunandrews** [comment]
Seems related to #21494

**Comment by simison** [comment]
@ItsJonQ's [Flex or Z/V/HStack components](https://github.com/ItsJonQ/g2/issues/22) could make an interesting technical basis for something like this.

**Comment by ItsJonQ** [comment]
@simison Indeed! Simplifying the CSS flexbox API into a component to accommodate common use-cases why I created the `Flex` component :)

`@wordpress/components` has this component btw:
https://github.com/WordPress/gutenberg/tree/master/packages/components/src/flex

Mileage may vary with that for the above use-cases. It should be able to do it though.

The layout components I have planned for the G2 components are a lot... "smarter"? (if that makes sense), with better defaults + layout detection mechanism:

https://github.com/ItsJonQ/g2/issues/22

**Comment by ianstewart** [comment]
@alaczek shared [an example in another issue](https://github.com/WordPress/gutenberg/issues/24953#issuecomment-688572358) that might be a related use for this.

**Comment by bongojules** [comment]
Would really welcome this feature.

Using flex to display grouped items horizontally (flex items that can simply wrap into a new row when they run out of space) is a common use case and it would be great if this could be reflected by the gutenberg editor... embracing the alignment/distribution attributes afforded by flex instead of stacking the grouped items vertically or separating them into columns (that don't behave in the same way).

**Comment by scruffian** [comment]
This would be very useful for themes

**Comment by youknowriad** [comment]
If some developer want to give this a try, we now have an experimental "layout" prop for InnerBlocks and a "layout" attribute in the Group block, meaning that the technical solution for this could like this:

 - Introduce a new type of layout (called "flex" maybe).
 - Add a UI to switch the layout type (in the existing layout panel) for the group block.
 - Generate the styles properly in `LayoutStyle` and the server layout block support.
 - Hide alignments for blocks inside containers with a "flex" type.
 - Potentially find a way to remove/reset the "align" attribute for blocks when they move (drag and drop or other) between containers with a different layout type and config.
