### ISSUE TITLE
Strange behaviour when adding hyperlinks on Android mobile

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#24482]
**Describe the bug**
This is a follow up of this Trac Ticket https://core.trac.wordpress.org/ticket/45609.

**To reproduce**
On an Android device, with WordPre.4.2 and a default theme activated (tested with Twenty Seventeen).

It's difficult to add hyperlinks to a word or a group of words selection. When the metabox to add the link opens, only one part is displayed in the screen view. The other part is not visible. And since the part of the metabox to validate the entered link is not visible, you have to do the validation with the phone keyboard.

Also, a click & hold on the metabox makes it move weirdly, making the whole process not very easy.

**Expected behavior**
The hyperlink metabox should fit in the screen view making it all visible. Also, it shoudn't move when clicking and holding.

**Version infos:**
- WordPress version: 5.4.2
- Theme: Twenty Seventeen 2.3

**Smartphone:**
 - Android 8.1.1
 - Chrome 84.0.4147.89

**Screenshots**
![Screenshot_20200811-131532](https://user-images.githubusercontent.com/33403964/89896371-41ff7880-dbd5-11ea-8b7a-6449bf3f8d77.png)

**Comment by david-szabo97** [comment]
Fixed by #27648
