### ISSUE TITLE
Limit block preview height.

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#24484]
Currently, blocks previews are shown as is, with no limits, causing very large previews for certain blocks, we should consider limiting the height.

Examples:

- Checkout block from the WooCommerce Blocks plugin (from a PR):
![image](https://user-images.githubusercontent.com/6165348/89905860-8e9d8080-dbe2-11ea-9512-f008fa781623.png)

- A long reusable block
![image](https://user-images.githubusercontent.com/6165348/89905946-a70d9b00-dbe2-11ea-859e-2cbd47b9264b.png)

**To reproduce**
1. Create a long reusable block, containing several large blocks.
2. Try to preview it.
4. Notice that the block is taking the whole page.

**Expected behavior**
The block height should be limited

**Screenshots**

![image](https://user-images.githubusercontent.com/6165348/89905705-64e45980-dbe2-11ea-84c5-9a58b3274640.png)

** Current workout **
Currently, I pass a `isPreview` attribute that adds `.is-editor-preview`, and I add some styles with it:
```css
.is-editor-preview {
	max-height: 1000px;
	overflow: hidden;
	position: relative;
}
```
See this [PR for examples.](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2992/)
**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg version: 8.7

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 84

**Comment by youknowriad** [comment]
I think for the style variations  at least, having a max-height is probably a good idea.

**Comment by MichaelArestad** [comment]
I agree with limiting the height. I wonder if we can leverage `vh` units to make it a percentage of the viewport height. Perhaps something like `calc(100vh - 84px)`. The second value is the height of the top toolbar plus 24px.

**Comment by aktasfatih** [comment]
I updated it to be as tall as the inserter minus the top position so it is symmetrical. Is this similar to what you have in mind? 
This is what it looks like now,
![download](https://user-images.githubusercontent.com/12985956/89956896-bde1db00-dc3e-11ea-8de8-855abb692702.png)

**Comment by youknowriad** [comment]
The vh works for the preview in the inserter but not for the style variations.
