### ISSUE TITLE
Consider merging Text and Cover Text

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2448]
The Cover Text block is super cool. It adds an optional background and text color to the plain paragraph block, as well as a sizing slider, allowing for some really nice expressive layouts. It's so cool, that we should consider merging it with the basic paragraph block. 

Also because as noted in [the design document](https://github.com/WordPress/gutenberg/blob/master/docs/design.md#advanced-settings):

> Don't put anything in the sidebar "Block" tab that is necessary for the basic operation of your block. Your user might dismiss the sidebar for an immersive writing experience. So pick good defaults, and make important actions available in the quick toolbar.

The only purpose of the Cover Text block is to add color and text sizing, and this is done in the sidebar, so it breaks with that design philosophy, making it less useful if a user decides to dismiss the sidebar.

On the other hand if it was part of the paragraph block, it would be exactly that — welcome, but advanced, additions to the basic text block.

As far as I'm concerned, the only blocker for merging the two, is ensuring that there's a "Reset" button next to colors and font sizes, so you can get back to an unstyled paragraph easily.

**Comment by mtias** [comment]
One thing to take into account is not applying any wrapper div unless a bg is added. (Even then, it may not be needed.)

**Comment by StaggerLeee** [comment]
Give some padding to text inside block when **Background Color** is chosen. Text is pressed against "walls", and looks ugly this way.

**Comment by youknowriad** [comment]
@StaggerLeee This could be a real bug, I noticed it but I thought I've already fixed when switching between Colored/Uncolored background doesn't update the styles properly unless you refresh.
