### ISSUE TITLE
Add options to offset block margins.

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#24504]
**Is your feature request related to a problem? Please describe.**

Here's a fairly popular pattern I've been trying to accomplish:

![image](https://user-images.githubusercontent.com/4550351/89970980-6888e680-dc9d-11ea-87ac-821299b5d913.png)

This is mostly possible with image and paragraph blocks (here nested inside a columns block), but there's no way to overlap the paragraph/heading with an image.

For comparison here's what I was able to put together in the editor right now:

![image](https://user-images.githubusercontent.com/4550351/89971522-c833c180-dc9e-11ea-9bce-fb09113d2db8.png)

(also, in addition to margin controls, we would need a way to limit block width)
 
I'm not sure what would be the best way to implement this - having an option of setting margins including a negative one maybe?

**Comment by ellatrix** [comment]
Hm, interesting. If a pattern were a block, you'd be able to add some styles specific for this block. But since it's just a pattern (and has no wrapper block), this is not possible. Adding margin attributes to every block etc. seems a bit like overkill. Maybe each block should have advanced CSS attributes? Or in this case, a custom block would be better? Cc @youknowriad @mtias

**Comment by youknowriad** [comment]
I don't think margin for every block is overkill personally but an advanced feature (opt-in potentially).

That said a "custom CSS" per block can also be a similarly good advanced feature. (I recall this being discussed in the past too).

**Comment by alaczek** [comment]
> Or in this case, a custom block would be better?

Not sure this is the way to go. Overlapping images with text is just one of the use cases. Ideally, we could overlap any two blocks. I do agree this would be a more advanced feature and I like the idea of "custom CSS". We could then build patterns to make those more advanced designs accessible to anyone.

**Comment by LevinMedia** [comment]
>I don't think margin for every block is overkill personally but an advanced feature (opt-in potentially).

I agree @youknowriad. However, I would say it's _not_ opt in, it's just there in the sidebar settings for a block if you want to use it. [I've been looking at the columns block](https://github.com/WordPress/gutenberg/issues/24874), and the child column blocks recently, and I came to the same conclusion: adding margin and padding controls to all blocks would be very useful. In particular, when you start using Gutenberg to build templates and template parts, or edit complex layouts, that level of control is necessary. IMO Having having to rely on custom CSS to get that level of control defeats the purpose of visual editing.

**Comment by iamtakashi** [comment]
> I came to the same conclusion: adding margin and padding controls to all blocks would be very useful. In particular, when you start using Gutenberg to build templates and template parts, or edit complex layouts, that level of control is necessary. IMO Having having to rely on custom CSS to get that level of control defeats the purpose of visual editing.

+1 👍👍👍

**Comment by ramonjd** [comment]
By removing the `min` attribute in the [margin control box](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/block-editor/src/hooks/margin.js#L102) (essentially setting `inputProps={ { min: undefined } }`) we can allow negative margins:

<img width="1227" alt="Screen Shot 2021-08-09 at 10 08 51 pm" src="https://user-images.githubusercontent.com/6458278/128703840-3983eb74-899b-44bc-81f3-4389aee50150.png">

The above effect uses a group block (is there another, more suitable block?), but note that I had to add position relative to create a new stacking context in order that it appears over its sibling elements.

**Comment by Mamaduka** [comment]
I think we can close this. Negative margins shipped in [Gutenberg 18.3](https://make.wordpress.org/core/2024/05/08/whats-new-in-gutenberg-18-3-8-may/#allow-negative-values-for-margin-controls) and should be part of WordPress 6.6 release.
