### ISSUE TITLE
Gutenberg shows private taxonomies in Categories & Tags

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2450]
It shouldn't. ;)

<img width="281" alt="window" src="https://user-images.githubusercontent.com/6073772/29410084-666f641e-834f-11e7-9e7c-7e9b1ba0fd7f.png">

Prominent Words is a private taxonomy that our plugin creates and fills automatically through analysis of the content. The user being able to edit this is not intended behaviour.

**Comment by youknowriad** [comment]
Tried to address this but it seems that there's no way to retrieve the `public` flag with the REST API :(

**Comment by youknowriad** [comment]
Same issue regarding the `show_ui` flag. Not available in the REST API yet.

**Comment by johnbillion** [comment]
Ref: https://core.trac.wordpress.org/ticket/42707

**Comment by danielbachhuber** [comment]
@WordPress/gutenberg-core Is it worthwhile to shim the visbility in to address the issue for WordPress `4.9.x` ?

**Comment by pento** [comment]
Yup, this should done shimmed in.
