### ISSUE TITLE
The block inserter on the left side of the screen closes each time I select a block.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#24502]
Congratulations on the release of WordPress 5.5.
I am always grateful for the development.

I tried WordPress 5.5 immediately, but the following problems occurred.

**Describe the bug**
The block inserter area, which should be fixed on the left edge of the screen, is closed every time a block or pattern is selected.

I tried deleting the cookies and browser cache and restarting the PC, but it didn't work.

**To reproduce**
I don't yet know why or in what environment it occurs.

**Screenshots**

![wp55_Inserter closes](https://user-images.githubusercontent.com/31400297/89966097-5ac96600-dc89-11ea-9598-3f63ab76043d.gif)

**Editor version (please complete the following information):**
- WordPress version:5.5
- No Gutenberg plugin
- I don't use any plugins.

**Desktop (please complete the following information):**
 - OS : Mac OS Catalina
 - Browser : chrome, safari

**Comment by ddryo** [comment]
additional information.

The inserter seems to be closed even if I select the text of the block already placed.

**Comment by chvillanuevap** [comment]
This is somewhat related to my issue [#24501](https://github.com/WordPress/gutenberg/issues/24501). The block directory disappearing prevents me from inserting blocks in an inner block.

**Comment by ntsekouras** [comment]
I'm closing this as this has recently changed here: https://github.com/WordPress/gutenberg/pull/24429.

Check the issue for the discussions about accessibility concerns/issues.
