### ISSUE TITLE
Block selector for block variations gets cut by admin bar

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#24507]
**To reproduce**
1. Add a lot of paragraphs to your post.
2. Add a social link block at the end of the post.
3. Click "+" sign to add a child block.
4. See error.

**Expected behavior**
The UI could be improved by not having the block selector go all the way up.

**Screenshots**
https://www.boldermail.com/wp-content/uploads/2020/08/Screen-Shot-2020-08-11-at-10.31.20-PM.png

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.105

**Comment by ellatrix** [comment]
Confirmed. Seems like we just need to increase the z-index? Cc @jasmussen

**Comment by jasmussen** [comment]
If the dialog doesn't get larger than the viewport, yes that would do it. I can look at a PR?
