### ISSUE TITLE
[Bug] Admin left sidebar navigation flyout submenu - not functional

### ISSUE THREAD

**Issue by whimsyniche** [WordPress/gutenberg#24509]
I updated to Wordpress 5.5
I updated Gutenberg to 8.7.1, then activated
I noticed some thing like site health doesn't work. the flyout submenus in admin doesn't flyout at all. I have to click on the navigation say plugins or appearance to see the submenus.

I disabled all other plugins that are gutenberg block add-ons:

- Atomic Blocks
- Ghost Kit
- Gutenberg Tile Block
- Stackable
- Ultimate Blocks

 Gutenberg plugin was activated and the flyout submenus and site health was not working.

I deleted the Gutenberg plugin, reactivated the block add-ons and it's all working fine.

**To reproduce**
1. Go to 'Plugins'
2. Click on 'add new'
3. Scroll down to 'Gutenberg' install and active
4. See how the menus behavior and site health

**Editor version (please complete the following information):**
- WordPress version: 5.5
- I had the default and gutenberg plugin installed but deactivated
- Gutenberg plugin version 8.7.1
**Desktop (please complete the following information):**
 - OS: iOS 13.6 and macOS 10.14.6
 - Browser Safari and Google Chrome
 - Version latest version 84

**Smartphone (please complete the following information):**
 - Device: na
 - OS: na
 - Browser na
 - Version na

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ellatrix** [comment]
<img width="1191" alt="Screenshot 2020-08-17 at 16 22 32" src="https://user-images.githubusercontent.com/4710635/90400892-dcfcc480-e0a5-11ea-80e5-77e0d50314a9.png">

Do you mean these fly outs? They seem to work fine for me. Could you try with only Gutenberg installed and the default theme active?

**Comment by whimsyniche** [comment]
I have exactly done what you mentioned. I have the default 2020 theme and Gutenberg and all that.

I done an uninstall of the Gutenberg plugin, and then install it back again. I'm not sure why the Horizontal Dropdown Menu in my Wordpress 5.5 update was not working when I toggled activate Gutenberg and then when deactivated it, it all worked fine.

Perhaps @dreamhost shared hosting issue with managed application's auto update script or WP 5.5 background process post install.
--
Side note unrelated to Gutenberg
I think I have a feature request or something to PR to WP, but I'll hold off until I have it working. I have to read the guidelines if any how to contribute

**Comment by whimsyniche** [comment]
Update: I updated Gutenberg 8.7.1 < 8.8.0
All seems to be working fine

**Comment by whimsyniche** [comment]
It's happening again. It's only to 1/2 of my WP sites which I have not updated Gutenberg 8.7.1 to 8.8.0 in WP 5.5.
I just learned something. I can activate the Horizontal Dropdown Menu if I right click on it. I've inspected the menu and submenu selectors. It's all there.

When I click on Site Health, it take hella long and it's no doing much to load results.

I tried on two different computers in Chrome in guest mode and Firefox in private mode.

I deactivate Gutenberg, all good.
I reinstalled WP 5.5 and activated Gutenberg and still there. I'm going into debug mode to see what's going on.

**Comment by whimsyniche** [comment]
The only messages I get when Gutenberg is deactivated:

Homepage:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WP_Categories_to_Tags has a deprecated constructor in /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php on line 31

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php:31) in /whimsycoll.com/wp-includes/pluggable.php on line 1296

Warning: Cannot modify header information - headers already sent by (output started at /whimsycoll.com/wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php:31) in /whimsycoll.com/wp-includes/pluggable.php on line 1299

In Admin:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WP_Categories_to_Tags has a deprecated constructor in /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php on line 31

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php:31) in /wp-includes/functions.php on line 6270

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php:31) in /wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/wpcat2tag-importer/wpcat2tag-importer.php:31) in /wp-admin/admin-header.php on line 9
I deactivated Categories to Tags Converter Importer plugin and then activated Gutenberg

Things are just go haywire. Oddly Categories to Tags Converter Importer plugin seems reactivated itself it's not. Can't see any debug messages above either.

I deleted Categories to Tags Converter Importer plugin, I used and I don't need it now.

I see now what's happening.

When guten is deactivated and I hover over 📌 Post
This happens to inline style of the submenu li class, it inserts `opensub`
`class="wp-has-submenu wp-not-current-submenu menu-top menu-icon-post open-if-no-js menu-top-first opensub"
`
```
<li class="wp-has-submenu wp-not-current-submenu menu-top menu-icon-post open-if-no-js menu-top-first opensub" id="menu-posts">
	<a href="edit.php" class="wp-has-submenu wp-not-current-submenu menu-top menu-icon-post open-if-no-js menu-top-first" aria-haspopup="true"><div class="wp-menu-arrow"><div></div></div><div class="wp-menu-image dashicons-before dashicons-admin-post"><br></div><div class="wp-menu-name">Posts</div></a>
	<ul class="wp-submenu wp-submenu-wrap"><li class="wp-submenu-head" aria-hidden="true">Posts</li><li class="wp-first-item"><a href="edit.php" class="wp-first-item">All Posts</a></li><li><a href="post-new.php">Add New</a></li><li><a href="edit-tags.php?taxonomy=category">Categories</a></li><li><a href="edit-tags.php?taxonomy=post_tag">Tags</a></li></ul></li>
```
![image](https://user-images.githubusercontent.com/2744219/90748016-a38fa900-e29f-11ea-8792-b8dec5836eca.png)

When guten is activated and I hover over 📌 Post
This happens, no insertion and various things are not functional, especially debug

```
<li class="wp-has-submenu wp-not-current-submenu menu-top menu-icon-post open-if-no-js menu-top-first" id="menu-posts">
	<a href="edit.php" class="wp-has-submenu wp-not-current-submenu menu-top menu-icon-post open-if-no-js menu-top-first" aria-haspopup="true"><div class="wp-menu-arrow"><div></div></div><div class="wp-menu-image dashicons-before dashicons-admin-post"><br></div><div class="wp-menu-name">Posts</div></a>
	<ul class="wp-submenu wp-submenu-wrap"><li class="wp-submenu-head" aria-hidden="true">Posts</li><li class="wp-first-item"><a href="edit.php" class="wp-first-item">All Posts</a></li><li><a href="post-new.php">Add New</a></li><li><a href="edit-tags.php?taxonomy=category">Categories</a></li><li><a href="edit-tags.php?taxonomy=post_tag">Tags</a></li></ul></li>
```
![image](https://user-images.githubusercontent.com/2744219/90747693-40057b80-e29f-11ea-98ca-ccb6e22ffd09.png)

**Comment by whimsyniche** [comment]
Gutenberg 8.8.0 fixed the issue

**Comment by aristath** [comment]
> Gutenberg 8.8.0 fixed the issue

Perfect! I assume this issue can be closed then?

**Comment by skorasaurus** [comment]
Hi, I'm closing this since the 8.8.0 update has fixed this; please reopen if you're still experiencing it.
