### ISSUE TITLE
Improve ServerSideRender UX

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#24519]
The ServerSideRender component is really handy, especially as a gateway for developers to get into building blocks however the constant reloading causes a lot of page resizing and a bit of a clunky experience.

David Gwyer has made a drop in replacement that is a lot nicer and I think it should be merged into core.

You can see the replacement here: https://github.com/dgwyer/server-side-render-x

And here's a gif showing it working:

<img src="https://user-images.githubusercontent.com/1482075/89642258-6395f280-d8ab-11ea-82b5-6cbba42ae72f.gif" width="700">

The code moves the spinner and only replaces the content once it's loaded making the experience feel less clunky.

**Comment by fabiankaegy** [comment]
I had a chat with @dgwyer in this issue: https://github.com/dgwyer/server-side-render-x/issues/2 and am digging into how his work could be merged into core. Therefore I'm assigning myself to this ticket.

**Comment by BinaryMoon** [comment]
@fabiankaegy Thats great - thanks for the update! Will be awesome to see this/ something like it in core.
