### ISSUE TITLE
Column blocks working with cover blocks

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#24512]
**Describe the bug**
When 3 narrow columns are added to the cover block, the effect is to push one of the columns underneath and out of bounds of the cover block, so that it draws the columns over the footer.

An example can be seen on this "test" site on the home page - rickspremiumtest.wordpress.com
Screenshot- https://d.pr/i/vuSe7K

A CSS solution was provided with the following code.

/* Services page column height | xxxxxx-hc (KK) */
.page-id-162 .wp-block-columns .wp-block-column>.wp-block-cover {
    height: 600px;
}
@media (max-width: 782px) {
.page-id-162 .wp-block-columns .wp-block-column {
    flex-basis: 100% !important;
}
}

**Expected behavior**
The footer area to be below the columns

**Editor version (please complete the following information):**
- WordPress version: Latest

**Desktop (please complete the following information):**
 - OS: ios
 - Browser Chrome
 - Version 84.0.4147.105

**Comment by alaczek** [comment]
Hmm... I use columns block inside a cover block quite often, and I don't think I've seen this issue. 
What theme were you using? Have you tried replicating with a different theme?
Your test site doesn't seem to have the columns block anymore, and it would be best to troubleshoot on live site.

**Comment by tellthemachines** [comment]
Closing as this isn't reproducible with the three latest default themes. It may be a theme-specific issue, in which case best report it to the theme devs.
