### ISSUE TITLE
Gutenberg Gallery block contributes to Cumulative Layout Shift

### ISSUE THREAD

**Issue by bobeaston** [WordPress/gutenberg#24527]
Not a good thing.  Google has announced its intent to use "[Core Web Vitals](https://blog.chromium.org/2020/05/introducing-web-vitals-essential-metrics.html)" as ranking factors in coming months.  One of those factors is [Cumulative Layout Shift](https://web.dev/cls/), a measure of how much things move around while a browser is painting a page. Google has announced that any of those factors falling outside their suggested ranges can negatively impact search ranking.

I first noticed a problem with the gallery block after adding several simple galleries to a post. My Chrome "Web Vitals" indicator flashes red for that page.

To understand what was happening, I launched a simple site with only 2 posts, my own version of the Genesis Sample theme and only 2 plugins.  (Antispam Bee and Classic Editor) One post was a Gutenberg constructed copy of the one that first caught my attention. Gutenberg, in this case was WP 5.4 core, no other Gutenberg plugins.  The post holds several paragraphs with 3 Gallery blocks and 1 Media and Text block interspersed.  I constructed an identical page using the Classic Editor plugin.
(As an aside, all of the images have been size optimized with squoosh.app and are about 1/10 their original size.)

I tested with the WebPageTest.org tool.  Results:
Classic version had CLS = 0.001 (attributable to using a Google font)
Gutenberg version had CLS = 0.078  (one set of tests showed a high of 0.184), definitely in the yellow zone.

Understanding why...
BOTH versions have nearly identical img code.  In fact they use exactly the same img url reference, the exactly the same 6 srcset references and widths.
Behavior is dramatically different and can be discovered by watching the videos that WebPageTest creates.

At about 1.5 seconds, the Classic version shows the first paragraph rendered and space below it reserved for the gallery images.  This space reservation is due to the loading="lazy" parameter that the Classic Editor included for the gallery code.

At the same time point, the Gutenberg version shows the top two paragraphs rendered with NO reserved space.  The gallery images paint later, moving the paragraphs apart, shifting the layout.  The reason is that the css in /wp-includes/css/dist/block-library/style.min.css?ver=5.4.2 uses display:flex to manipulate the content.   I have to really hand it to browsers being able to calculate the ramifications of 74 css rules for gallery-block, but am not at all pleased with the CLS result.

BTW... responsiveness can't be the reason for this excess manipulation.  The Classic version is just as responsive as the Gutenberg version without needing 10,000 bytes of CSS.

See for yourself at: 
[Classic version](https://www.bob-easton.com/gute-test/new-greenland-paddle-classic/)
[Gutenberg version](https://www.bob-easton.com/gute-test/new-greenland-paddle-gutenberg/)

WordPress = 5.4.2
Device: desktop 
OS: Windows10 
Browser = Brave 1.11.104, built on Chromium 84.0.4147.105

**Comment by billerickson** [comment]
I ran into this issue as well, and was able to fix it with:

```
.wp-block-gallery ul {
	flex-grow: 1;
}
```

**Comment by tellthemachines** [comment]
I can no longer reproduce this issue when testing with network throttling. On a page with a gallery and text below it, the space for the gallery is reserved while loading:

<img width="774" alt="Screenshot 2023-05-12 at 1 44 09 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/fd6e3f30-f5b3-449e-b28d-4ec4c398e4aa">

Running a page with multiple galleries through the Chrome lighthouse audit, the CLS score is a perfect 0. I think we're good to close this one 🙂
