### ISSUE TITLE
Help link in the editor 'more' menu doesn't indicate that it opens in a new tab

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#24539]
**Describe the bug**
The Help link in the editor more menu doesn't indicate that it opens in a new tab.

Links in the editor that open in a new tab usually have some visually hidden text for screen readers that says '(opens in a new tab)' so this one is inconsistent.

E.g.
- The preview button
- The Embed block's placeholder
- The View Post in the permalink panel

They either use the `ExternalLink` component for this or the `VisuallyHidden` component.

A second inconsistency is that the 'Manage all reusable blocks' link in the same menu doesn't open in a new tab.

**To reproduce**
1. Open the editor more menu (either with a screenreader, or use dev tools to inspect the markup)
2. Notice the help link doesn't indicate it opens in a new tab, but selecting it opens a new tab
3. Notice the Manage Reusable Blocks link doesn't open in a new tab

**Expected behavior**
- Links in the same dropdown menu should probably have the same behaviour in regards to opening a new tab.
- The links should indicate whether they open in a new tab or not.

**Screenshots**
<img width="271" alt="Screenshot 2020-08-13 at 4 43 33 pm" src="https://user-images.githubusercontent.com/677833/90113577-2686a000-dd84-11ea-9779-5d434da522e3.png">

**Editor version (please complete the following information):**
- 8.7

**Comment by mariohamann** [comment]
You seem to be absolutely right. Especially since there is already an existing icon for external links, but it was obviously not used here. I think a design feedback is less necessary than just the implementation?

![Screen Shot 2020-08-14 at 19 49 47](https://user-images.githubusercontent.com/26542182/90278405-b7827780-de67-11ea-9504-f74bcc582cbe.jpg)

**Comment by talldan** [comment]
Happy with that solution @mariohamann. I'll remove the label 👍
