### ISSUE TITLE
Link popover flickers on small screens (mobile)

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#24532]
**Describe the bug**

When adding a link to selected text in a Paragraph block, the link popover flickers as it tries to adjust to screen size:

![ezgif com-optimize](https://user-images.githubusercontent.com/8096000/90106607-04dce700-dd8b-11ea-9d21-0f5ff6bcae1f.gif)

**Expected behavior**

Expected popover to fit the screen and stay in one place.

**Screenshots**

**Editor version (please complete the following information):**
Latest from this repo.

**Smartphone (please complete the following information):**
iOS 13.3 on iPhone 11; Android 6.0.1 on Samsung S5.

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by rebeccahum** [comment]
Just wanting to note that I was able to reproduce on 5.5.1

**Comment by david-szabo97** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/27648
