### ISSUE TITLE
Can't access last item in post settings sidebar on mobile

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#24536]
**Describe the bug**

When any of the post settings sidebar sections is open, on a small screen, the last item on the list isn't accessible by scrolling down.

View with all sections closed:

![Screenshot_20200813-160052](https://user-images.githubusercontent.com/8096000/90108786-2d1a1500-dd8e-11ea-8ff7-dfa3d890400b.png)

View with sections open, scrolled to bottom. Notice that the "discussion" section is no longer visible:

![Screenshot_20200813-160104](https://user-images.githubusercontent.com/8096000/90108818-386d4080-dd8e-11ea-8e75-a0a6ecf0acf6.png)

**To reproduce**
1. Open post settings sidebar on mobile
2. Open any of the sections, and scroll down
3. Notice a section missing from the bottom.

**Expected behavior**

Expected all sections to be visible on mobile, whether open or closed.

**Screenshots**

**Editor version (please complete the following information):**
Latest from this repo.

**Smartphone (please complete the following information):**
iOS 13.3 on iPhone 11; Android 6.0.1 on Samsung S5.

**Comment by rebeccahum** [comment]
Hi, I'm unable to reproduce on iPhone 11 with iOS 14 on 5.5.1 currently:

<img width="439" alt="Screen Shot 2020-09-29 at 12 04 55 PM" src="https://user-images.githubusercontent.com/16962021/94598374-17808200-024c-11eb-9d55-49eb1850c708.png">

**Comment by noisysocks** [comment]
Also unable to reproduce this.
