### ISSUE TITLE
Idea: Apply raw transforms on unidentified content before creating fallback block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2454]
For existing post content which cannot be identified as a block, we create a fallback block initialized with the raw HTML:

https://github.com/WordPress/gutenberg/blob/de51e2415781b5c98ed6a566b7169423faec4ce8/blocks/api/parser.js#L160-L175

We also already have a mechanism in place for transforming pasted HTML to an appropriate block:

https://github.com/WordPress/gutenberg/blob/de51e2415781b5c98ed6a566b7169423faec4ce8/blocks/library/image/index.js#L73-L83

It seems a natural extension to run over these "raw" transforms using the unidentified content before passing it to the fallback block. In case there is a match, we can split on the matched content and initialize a new block of that type.

The thinking here is that this could be applied as a backwards-compatibility API for blocks which had previously been implemented as a shortcode, or other content which could be easily "upgraded" to an equivalent block (text, images).

For example, consider a gallery shortcode transform:

```js
from: [
    {
        type: 'raw',
        isMatch: wp.shortcode.regexp( 'gallery' ),
        attributes: ( text ) => { /* map shortcode attributes to block attributes */ } 
    }
]
```

_Aside: We could create a convenience layer on top of this specifically for shortcodes (think `{ type: 'shortcode' }`)_

_Aside: `isMatch` in the image example passes `node` as an argument. Is this something we need?_

Given an input content of:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

[gallery]

Donec purus tellus, tempus ac consectetur quis, ultricies vitae magna.
```

Currently we create a single Classic Text block:

```html
<!-- wp:core/freeform -->
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

[gallery]

Donec purus tellus, tempus ac consectetur quis, ultricies vitae magna.
<!-- wp:core/freeform -->
```

The user would only see the shortcode text.

Instead, the gallery transform could match the shortcode and upgrade it to a gallery block:

```html
<!-- wp:core/freeform -->
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
<!-- wp:core/freeform -->

<!-- wp:core/gallery /-->

<!-- wp:core/freeform -->
Donec purus tellus, tempus ac consectetur quis, ultricies vitae magna.
<!-- wp:core/freeform -->
```

So the user could interact with the shortcode as any other gallery block.

An assumption here is that the shortcode would be replaced with the gallery block in the next save. For compatibility between existing shortcodes and server-rendered (dynamic) blocks, a plugin author could extract the rendering logic and register both:

```php
function myplugin_render_map( $atts ) {
    return '...';
}

add_shortcode( 'map', 'myplugin_render_map' );
register_block_type( 'my-plugin/map', array(
	'render_callback' => 'myplugin_render_map',
) );
```

**Comment by iseulde** [comment]
I like it. Do you think we should call `paste` something like `handleRaw` then, and use that?

**Comment by aduth** [comment]
Much of paste's handling seems specific to the paste case (stripping attributes and unwanted nodes). Would we need all of it for this?

**Comment by iseulde** [comment]
Yeah, that's correct. I guess we can short cut that for existing content, and only handle shortcodes and wrap text in paragraphs.

**Comment by mtias** [comment]
Makes sense to enable this once we are ready. The purpose of starting with pasting was to have the handling in a more controlled environment. We have since expanded to "convert classic to blocks" which is pretty much the behaviour described here. Next step is looking at default handling — the only question is whether to do it automatically or on demand; for everything or for certain matchers.

**Comment by aduth** [comment]
To the on-demand need, should this be considered satisfied by #3179?

**Comment by mtias** [comment]
On demand would be satisfied by it. This is more about showing it more prominently when you load a post made entirely of freeform (meaning, an old post).
