### ISSUE TITLE
Gets warning when I try to give a color to selected words in paragraph block

### ISSUE THREAD

**Issue by kishanjasani** [WordPress/gutenberg#24543]
**Describe the bug**
Gets warning when I try to give a color to selected words in paragraph block.

**To reproduce**
1. Firstly take any post to edit or new one.
2. Then take new paragraph block. Write some content in it and select few word and select `Text Color` from `More rich text control` 
3. Now go to browser's developer console
4. See warning 
```Warning: React does not recognize the `isActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

**Screenshots**
![2020-08-13_15-14](https://user-images.githubusercontent.com/25550562/90119858-bbcf6780-dd77-11ea-82c9-649ecf36b1ac.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.0]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  => "default"

**Desktop (please complete the following information):**
 - OS - Ubuntu 20.04
 - Browser - chrome
 - Version - 84.0.4147.105

**Comment by jorgefilipecosta** [comment]
I was able to reproduce the issue.
