### ISSUE TITLE
Color is not set when i used Pullquote. 

### ISSUE THREAD

**Issue by wpamitkumar** [WordPress/gutenberg#24550]
**Describe the bug**
When I set the text color to the default listed color it will not be set.

**To reproduce**
1. Take Pullquote Block.
2. Add Some Text.
3. Select Text and choose `Text Color` from the text above the formatting menu.
4. Choose the default color, it does not affect over text. 

**Expected behavior**
Set color on the text.

**Screenshots**
![Text color not set](https://user-images.githubusercontent.com/18453994/90142424-f9dd8300-dd99-11ea-8649-a785ea80e38a.gif)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.0]
- Does the website has a Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]

**Desktop (please complete the following information):**
 - OS - Ubuntu 20.04
- Browser - chrome
- Version - 84.0.4147.105

**Comment by jorgefilipecosta** [comment]
Hi @wpamitkumar,

What theme are you using?
Does this issues only happens with pullquote or for example in a paragraph that text color is also not applied to parts of it?
If you press custom color button and select custom color do things work in that case?


Thank you in advance for this information!

**Comment by wpamitkumar** [comment]
Hello, @jorgefilipecosta 

I'm using twentynineteen theme.
I check this was happening with all blocks who gives color selection option like this.

**Comment by kishanjasani** [comment]
Hii @jorgefilipecosta @wpamitkumar , 

I have trace the issue. This is not an issue with gutenberg. It's actually problem with css classes of Twenty Nineteen theme. Gutenberg is applying it's classes to blockquote or paragraph but css classes from theme is not applied properly.

Please have a look at : https://core.trac.wordpress.org/ticket/51090

**Comment by kishanjasani** [comment]
Please close this issue from here.
