### ISSUE TITLE
Site Editing Milestones

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#24551]
We have been using long standing overview issues for handling the site editing project and it's time to get a bit more granular in how we structure the milestones. We also need to bring together several projects that might have appeared separate before. The goal is for each of these to have a proper task breakdown soon.

### Milestone:1 **Infrastructure and UI** 

**High**

- Part 1: #20791  ✅ _Completed_
- Part 2: #24818 ✅ _Completed_

The work on the first part covered the introduction of the `wp_template` and `wp_template_part` model, the `edit-site` package, multi-entity saving, and a set of site editing blocks (site-*, query, post-*).

**Normal:**
- Part 3: Template editing mode within the post editor. #27814 _In progress_

This section covers the integration of template editing into the post editor itself (that is, outside of `edit-site`).

### Milestone:2 **Browsing** — #24552 ✅ _Completed_

Groups the work related to navigating between pages, templates, parts, and the interface work around communicating what area is active, what entity is loaded, and so on.

### Milestone:3 **Styling** — #20331 _In progress_

Includes the global styles project, design tools in specific site editing blocks, and any further work around theme integration (palettes, gradients, content width, etc).

### Milestone:4 **Theme Blocks** — #22724 ✅ _Completed_

Covers the creation and prioritization of remaining theme related blocks. Needs coordination with theme group and community to determine priorities and gaps.

### Milestone:5 **Query Block** — #24762 ✅ _Completed_

An initial implementation of the _Query_ and _Loop_ blocks is in place. It's missing some next steps around customizing the query, sidebar controls, and particularly pattern integration for editing and handling different displays of post lists.

### Milestone:6 **Navigation Block** — #27593 _In Progress_

Editing a site's navigation menu, both in terms of structure and design. 

### Milestone:7 **Gradual Adoption** — #30662 ✅ _Completed_

Once more of the pieces are completed, there needs to be some room to structure how adoption might look for those that can't or don't want to restructure a full theme — intermix of block based templates and regular PHP templates, etc. Part of this is already being covered by separate projects like `edit-widgets` and the navigation block work, but keeping this noted here for visibility.

**Comment by jdevalk** [comment]
@mtias I'm trying to get a grip on what FSE's current status is. Is this Milestone overview up to date, in terms of statuses?

**Comment by mtias** [comment]
Yes, this is generally the best place to get an overview and status check. The big thing missing is the navigation block, which has been tracked in a separate project but I plan to list here as well

**Comment by mtias** [comment]
Incorporated Milestone:6 Navigation Block and renamed Milestone:2 to "Browsing" for clarity.

**Comment by priethor** [comment]
Created and linked an overview/tracking issue for _Milestone 7: Gradual adoption_ #30662

**Comment by mtias** [comment]
Most of the work outlined in this overview is now concluded or has its most important tasks covered. A more fine tuned scope for what's upcoming is continued to be tracked in this new issue: #33094.

A lot of wonderful work has gone into all these ambitious milestones, so kudos to all who contributed so far!
