### ISSUE TITLE
Inserter: Consider throttling block previews in the inserter

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/gutenberg#24565]
**Describe the bug**
If your cursor is hovering over the inserter as you scroll downwards, inertia is interrupted by an event on the block icon which is exacerbated by the block preview, which tries to render immediately. 

As a potential quick fix, throttle the block preview (and the `mouseover` on the icon maybe -- It may already be though). It appears that the problem gets worse after you repeatedly scroll up and down (which probably signals that the issue is the block preview and the queuing of more & more js tasks).

**To reproduce**
1. Open the Inserter from the top menu
2. Leave your cursor in the middle of the inserter
3. Scroll downward (via mouse wheel, touch pad, etc..)
4. Notice that your scroll inertia is interrupted

**Expected behavior**
Once my intention is clear, render the block preview.

**Screenshots**
Video: https://d.pr/v/ZvShmG

**Editor version (please complete the following information):**
- @https://github.com/WordPress/gutenberg/commit/bd954d248cbaeede699e217f15a577f398d1e5bb

**Desktop (please complete the following information):**
- Chrome (Version 84.0.4147.125 (Official Build) (64-bit) )
- MacOs Catalina (10.15.6)

**Comment by paaljoachim** [comment]
Hey Steven @StevenDufresne 

I took a look at your video and compared it to how it works today.
To me it feels like it is working better today then when you made the issue.
What do you think? If that is the case then we can close the issue, if not then we can continue the discussion.

**Comment by smwcollege** [comment]
I just tried replicating the issue on my site and I am not able to re-produce the issue, since the preview does not appear until the scroll inertia has stopped. I was also unable to replicate the preview boxes overlapping when scrolling the inserter quickly.

**Comment by joelyoder** [comment]
I just tried replicating the issue on my site and I am not able to re-produce the issue, since the preview does not appear until the scroll inertia has stopped. I was also unable to replicate the preview boxes overlapping when scrolling the inserter quickly.

**Comment by StevenDufresne** [comment]
Hey Yall. I noticed a PR floated by a month back that addressed this issue. Closing :)
