### ISSUE TITLE
Widget Editor: Design Updates

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24561]
Revisiting the new Widget Editor, I can see a few areas that require design updates.

## Widget areas
Currently, the widgets.php screen shows all theme-registered widget areas together. This is how the experimental Widget Editor works as well. 

![both](https://user-images.githubusercontent.com/617986/90177153-faa4f380-dd5e-11ea-877e-5250f1c201af.png)

### Overall improvements from widgets.php

- Any block can be used in a Widget Area.
- One global update button that pushes all changes live at one time (similar to the Block Editor). This no longer requires staging widgets in the Inactive Widget Area. The user can drop them into the specific area, then adjust settings and content, and then push them live.
- Brings the familiarity of the Block Editor into other parts of the admin.

----

### Multiple widget areas vs. Single widget area
I'm exploring whether or not we _should_ display all widget areas in one screen, or add a switcher that only allows one widget area to be visible at a time.

**Multiple widget areas in screen**
Remains closer to existing user expectations by presenting all widgets areas and blocks in the same screen.

![multiple](https://user-images.githubusercontent.com/617986/90183436-59bb3600-dd68-11ea-9369-8d7d71cbfbea.png)

PROS
- A user can drag and drop blocks between the widget areas easily.
- All blocks/widgets are visible at one time.

CONS
- The Global Block Inserter doesn't know which area to add a block to without that area being indicated somehow.

**Single widget area in screen**

![single-area](https://user-images.githubusercontent.com/617986/90183451-5e7fea00-dd68-11ea-9028-cca7eafc3fd4.png)

PROS
- The Global Block Inserter panel can default to open and allow adding easily into the widget area.
- Can inherit the full background similar to the Block Editor.

CONS
- No ability to drag and drop between widget areas. 
- Where do the Inactive widgets/blocks live? The Inactive Widget Area is used for widgets that no longer have a place after a theme switch and/or for staging a widget before adding it to an area causing it to go live.

**Single widget area + Inactive Widget Area**
To remedy the CON in the single widget area exploration, there's a possibility of always showing an Inactive Widget Area. This area would always be visible from whatever main area was being edited.

![single-and-inactive](https://user-images.githubusercontent.com/617986/90183464-62ac0780-dd68-11ea-9cb3-7a3a79d2b793.gif)

PROS
- Keeping this area always visible allows users to drag and drop the inactive widgets/blocks into another widget area to reactive them. 
- Inactive widgets/blocks retain their settings and visual appearance. 

CONS
- There is still some ambiguity around which area the Global Block Inserter should add a block to. I thought disallowing users from manually adding blocks to the Inactive area, but I'm aware of a use case that involves users adding moving blocks into this area for a time and then moving them back into an active area without losing the widget's/block's settings (ie. when a sale is happening on the site).

----

### Block Library
Similarly to the widgets.php screen, we can open the Block Library panel by default. 

----

### Widget area switcher
Moving toward a Single Widget Area, a switcher would be necessary to move users from one widget area to another.

![Screen Shot 2020-08-13 at 1 44 10 PM](https://user-images.githubusercontent.com/617986/90185217-36de5100-dd6b-11ea-9315-01bdd481c06d.png)

----

### Paragraph placeholder
Instead of showing a consistent "Add" button at the bottom of the widget area, we can make this more like the Block Editor by showing the Paragraph block's placeholder instead with the in-page Inserter `+` button.

![Screen Shot 2020-08-13 at 1 58 58 PM](https://user-images.githubusercontent.com/617986/90186567-31820600-dd6d-11ea-9831-24b9cdad87b0.png)

----

### Document Inspector
When the Document Inspector is open in the Widget Editor, it should display the Widget Area's name and include the description provided by the theme.

![Screen Shot 2020-08-13 at 2 13 36 PM](https://user-images.githubusercontent.com/617986/90187794-3f388b00-dd6f-11ea-9dbd-2ac7270de13e.png)

**Comment by noisysocks** [comment]
Love the exploration here, but just noting that we have 9 weeks until the code freeze for WP 5.6.

**Comment by paaljoachim** [comment]
Great job, Mark!

Having it as close as possible to the standard method of adding blocks in Gutenberg would be best as I see it so that we can keep a consistent method of adding a block (widget). That would mean either opening the inserter as a sidebar or having the + inserter icon directly in a paragraph block.

There could be as you mention an inactive area. So the user can drag blocks/widgets that one is not certain of using.

My suggestion would be to actually test out both methods. Using the inserter that opens as a sidebar and the inserter inside the paragraph block (user can choose which method to use). Today we already have the widget experimental screen inside Gutenberg -> Experiments. So this would actually be something that can quickly get in place so we can get some testing done. With feedback we can refine the experience.

**Comment by afercia** [comment]
> A user can drag and drop blocks between the widget areas easily

I may be wrong, but in the mockups / GIFs above I don't see controls to move / rearrange the widgets by using a keyboard. In the current admin screen, this functionality is available in the "accessibility mode".

**Comment by mapk** [comment]
>I don't see controls to move / rearrange the widgets by using a keyboard.

Great point! The same accessible keyboard interactions found in the block editor would be adopted here as well.

**Comment by mapk** [comment]
Based the feedback I've received, I've narrowed down the UX direction.

### Single widget area
Show only a single widget area at a time.

![Widget Editor i6 - 1](https://user-images.githubusercontent.com/617986/90815134-12402700-e2df-11ea-89a6-2e43be047ab0.png)

### Widget area switcher
There is a widget area switcher in the topbar that allows the user to jump to other widget areas.

![Screen Shot 2020-08-20 at 12 17 49 PM](https://user-images.githubusercontent.com/617986/90815220-3439a980-e2df-11ea-845d-d54806a93826.png)

### Widgets in the Inserter
Widgets have their own category in the Inserter panel.

- When in the **Widget Editor**, the Widget category is at the top of the Inserter.
- When in the **Block Editor**, the Widget category is at the bottom.
- The block preview of widgets work like blocks.

![Screen Shot 2020-08-20 at 12 20 43 PM](https://user-images.githubusercontent.com/617986/90815471-a01c1200-e2df-11ea-8e01-3e5f7ca6dd4d.png)

### Moving widgets to other areas
- Moving widgets between widget areas can still be done by copying and pasting blocks.
- In the case of the Inactive Widget area, there is a block toolbar option to "Activate in" with a list of widget areas. 
- In the Active Widget areas, there can be a block toolbar option to move the block to "Inactive Widgets".

![Screen Shot 2020-08-20 at 12 23 31 PM](https://user-images.githubusercontent.com/617986/90815733-fdb05e80-e2df-11ea-80d9-7fcbf66e41ac.png)


### Prototype 
This is how it all comes together. [Figma file](https://www.figma.com/file/rfovVm34ULtWr4hYaFlLtv/Widget-blocks-Editor?node-id=230%3A14466).

![widget-editor-flow](https://user-images.githubusercontent.com/617986/90815952-55e76080-e2e0-11ea-8ec5-0a159a03757e.gif)

**Comment by noisysocks** [comment]
Displaying legacy widgets in the inserter is a great idea.

> In the Active Widget areas, there can be a block toolbar option to move the block to "Inactive Widgets".

How would this look? Would it say "Activate in ... Inactive Widgets"?

**Comment by mapk** [comment]
@noisysocks, I have that outlined here: https://github.com/WordPress/gutenberg/issues/24698. I wrote it as "Move to Inactive Widgets"

**Comment by draganescu** [comment]
It's not a small mock-up, but I like it a lot. It does bring in a lot of new things:

- area switcher
- registering each widget as a variation of Legacy Widget
- previews for the variations
- the "activate in" action
- the "inactive widgets area" handling
- a new inserter category

Some of the stuff already exists, the question being if we can simply use them or will we find they're missing bits to enable this workflow. I am optimistic as it looks a lot like the flows the site editor mock-ups show.

**Comment by paaljoachim** [comment]
I am very hesitant about having a single widget screen, as it would by default hide the overview of the available widget areas. There can be some discoverability issues for the user when entering the widgets screen. There is also no way to drag and drop a widget from one area to another.

Pros and Cons of having a Single Widget screen.

Pro: 
As one can add multiple blocks into one widget area it would be nice to keep focus on the one area.

Cons: 
It is harder to get a quick overview of all widget areas. As one would need to click the widget area switcher.
It would not be possible to drag and drop widgets from one area to another. As one would need to click the 3 dots icon in the toolbar and choose to activate widget in a specific area.

------

I began exploring the Single Widget mode. 
It could actually begin with an All (Overview etc) mode showing all the widget areas.
Kinda like so:
![Gutenberg-Widget-Screen-wireframe](https://user-images.githubusercontent.com/5323259/90869637-ca7dd600-e398-11ea-9977-f6271b5d08b2.jpg)

The advantage here is the user can choose from seeing all the widget areas at once. It would also make it possible to drag a widget from one area to another.


![Widget-Switcher-All-wireframe](https://user-images.githubusercontent.com/5323259/90870688-3dd41780-e39a-11ea-8c59-4702027c6b8e.jpg)

**Comment by paaljoachim** [comment]
A perspective.
The existing Appearance -> Widgets 

![Widget-screen](https://user-images.githubusercontent.com/5323259/91039308-a32f3f00-e60c-11ea-9cc5-6623ec49d4b8.jpg)

User enters the widget screen and sees the available widgets and widget areas. 
Goal of the widgets screen as I see it: Is to make "different" content areas such as header, sidebars, footer and other unique content areas easily discoverable and available to be modified.
If we were going to transfer this into a Gutenberg version it would most likely look something like this:

![New-Widget-screen-multi-screen](https://user-images.githubusercontent.com/5323259/91039757-6d3e8a80-e60d-11ea-8489-53f9e519d470.jpg)

New widget screen has a similarity with the existing widgets screen.

If a user uses the Classic Editor plugin the new Widget screen should work nicely even though they are not using Gutenberg.

Full Site Editing in relation to the Widgets screen.
In a page or post screen.
User creates a page or post template and adds in specific sections. We might call these new sections for widget areas. But in relation to Full Site Editing these would just be user defined sections in a page/post template. 
These new sections should then show up in the Widget screen as new widget areas.

Single view widget page.
- Greater focus on one widget area at a time.
- More cumbersome to move a widget from one area to another. (No drag and drop)
- More difficult to get an overview of all widget areas. (One might see them in the widget area inserter.)

Multi view widget page.
- Looks similar to the existing widget screen. (making it easier to transition from existing to a new widget screen.)
- Overview of all widget areas.
- Working on one widget area one also sees the other widget areas.
- Drag and drop of widget from one area to another.

I do have a feeling that there is something I am not aware of affecting the way forward.

**Comment by afercia** [comment]
While I see the conversation on the ideal design is still going on, it is important to point out a very important thing for accessibility:

Whatever the final design will be, all admin pages need a good headings hierarchy:
- a main, _visible_, H1 heading to identify what the page is about
- other headings to identify the page main sections

I see that [some of the mockups above](https://github.com/WordPress/gutenberg/issues/24561#issuecomment-677858593) just reuse the edit post page design, which has a top toolbar and no visible main H1. At the time of the discussion around the Gutenberg edit post page, this was discussed at length and the accessibility team accepted a visually hidden H1 as a compromise between design and accessibility needs. In a way, the accessibility team considered that decision an "exception". I'm not sure the accessibility need would agree in re-using a visually hidden H1 as default pattern for the new admin pages. 

Visible headings benefit all users. To me, it's of fundamental importance that any admin page clearly communicates what its about with a main H1. Headings also allow easy content navigation, both visually, and with assistive technology. 

I'll bring this point to the next weekly accessibility meeting for broader discussion. In the meantime, I'd like to kindly ask to review the proposed mockups and add visible headings, including a visible main H1. This is even more important as I'm seeing the layout above being proposed as the "default" new look of all the new admin pages (menus, etc.)

**Comment by afercia** [comment]
Regarding the "widget area switcher in the topbar": I see that the visible text represent the _state_ and not the available action. Still unclear to me what this control will actually be when implemented:
- If it will be a sort of `select` element of some sort, it will need a label to clarify the action and the selected option can stay as illustrated in the design because this component will mimic a select element.
- instead, if it will be a button that opens a menu: the button can't be used to represent the state (the selected option). It needs to identify the _action_. The state needs to be communicated separately.

**Comment by afercia** [comment]
Headings in the current Widgets page:
- main H1 is visible
- H2 headings identify the page main sections 
- H3 headings identify each widget: maybe this could be changed to something else e.g. a list or any other HTML that is semantic enough to represent a set of widgets

<img width="1431" alt="Screenshot 2020-08-24 at 14 30 48" src="https://user-images.githubusercontent.com/1682452/91048400-eba22900-e61b-11ea-8576-769c1aa85da0.png">

**Comment by mapk** [comment]
>Probably that listing is easier, but a new screen to support?

Yes, @draganescu, it would be a new screen. But it would align with all the other list view screens in wp-admin (ie. posts, pages, comments). 

The hesitation I have about showing all widget areas in the Editor at one time is that it eliminates the need for individual widget areas and doesn't jive smoothly with showing one editor at a time. I'd like to get more feedback on that.

**Comment by noisysocks** [comment]
Personally I'd prefer the dropdown option as it's quicker. Going to an intermediary list screen requires a page load.

**Comment by mtias** [comment]
A few thoughts on the current progress:

- Agreed on having the block library panel open by default, similar to how the current screen works. I'd even consider removing the + toggle in the header entirely and having it always open.
- Without the + it might be fine to lead with page title "Widgets".
- I don't agree with moving the Widgets category to the top. All blocks are "widgets" from a general perspective, and text and images are some of the most common ones to add, so we should leave categories in their current order.
- Focusing on a single area and having a switcher in the header could eventually be a better solution, but not before the site editing project, in my opinion. Right now it's important to minimize changes and retain functionality like moving widgets from one area to another easily. I think this version is a better starting point in that regard:

![90183436-59bb3600-dd68-11ea-9369-8d7d71cbfbea](https://user-images.githubusercontent.com/548849/91302997-a6126700-e7a7-11ea-8d90-0d09880b595b.png)

Also worth considering on very large viewports to stack widget areas horizontally.

> The Global Block Inserter doesn't know which area to add a block to without that area being indicated somehow.

The active block area should have some indication. Also the inserter shows a blue line when focusing / hovering a block to indicate insertion point.

**Comment by adamziel** [comment]
Here's a first prototype of open-by-default global inserter: https://github.com/WordPress/gutenberg/pull/24822

**Comment by mapk** [comment]
Taking in the feedback from @mtias, here's another [prototype](https://www.figma.com/proto/rfovVm34ULtWr4hYaFlLtv/Widget-blocks-Editor?node-id=451%3A0&viewport=-8224%2C-8102%2C1&scaling=min-zoom).

## Multiple widget areas on screen
Every widget area the theme provides will be displayed on screen.

![Legacy Widget i4 - 1](https://user-images.githubusercontent.com/617986/91364394-78331f80-e7b3-11ea-8df1-f3029ffd1514.png)


## Display the page title
[As noted by the accessibility team](https://github.com/WordPress/gutenberg/issues/24561#issuecomment-679105169), we should continue to display the page title an an `H1`.

![Screen Shot 2020-08-26 at 3 49 03 PM](https://user-images.githubusercontent.com/617986/91364492-b16b8f80-e7b3-11ea-8d5e-7f7364896ebe.png)

## Widgets are at the bottom of the inserter panel
Although the prototype doesn't _really_ show this, it alludes to it. Widgets would reside at the bottom of the Inserter panel without disrupting the order of the Inserter categories.

![Screen Shot 2020-08-26 at 3 51 10 PM](https://user-images.githubusercontent.com/617986/91364616-027b8380-e7b4-11ea-9b5e-fb3bf613dd7e.png)

## 3rd party widgets as block variations
The Legacy Widget block will work much like the Embed block. A _container_ block that displays 3rd party widgets as a block variation. I'm still working through how the block's description should read. If the block still reveals itself as a Legacy Widget block as what I believe is being [suggested here](https://github.com/WordPress/gutenberg/issues/24663#issuecomment-680852958), than should the widget name be included on the same line as I have it in the prototype, or on it's own line? Or in the block toolbar?

![Screen Shot 2020-08-26 at 3 54 18 PM](https://user-images.githubusercontent.com/617986/91364813-70c04600-e7b4-11ea-9eef-80cdd4ed9028.png)

## Drag and drop between areas
Showing all areas on screen allows us to keep the drag and drop interaction between areas. Notice that when a block is dropped in a new area, that area is identified in the Document Inspector.

![Screen Shot 2020-08-26 at 3 52 49 PM](https://user-images.githubusercontent.com/617986/91364707-3787d600-e7b4-11ea-950b-6c3acbfa4857.png)

## Inserter panel 
Inserter panel is open by default, but can close and reopen as needed. This continues in alignment with #24822 

## Which area is active?
We need a way to identify which area a block will be dropped into when adding from the Inserter panel. If no block is selected, but the area is active, that area is outlined in blue in the prototype. If a block is focused, the block is blue and the system knows to just add the block below the focused block.

![Screen Shot 2020-08-26 at 3 58 02 PM](https://user-images.githubusercontent.com/617986/91365003-f04e1500-e7b4-11ea-8fbd-afbe1e7f96b1.png)

----

## Prototype
Here's how it all comes together.

![multi-area-drag](https://user-images.githubusercontent.com/617986/91365018-f9d77d00-e7b4-11ea-8264-c2d18214d892.gif)

**Comment by mtias** [comment]
> Although the prototype doesn't really show this, it alludes to it. Widgets would reside at the bottom of the Inserter panel without disrupting the order of the Inserter categories.

@mapk to clarify, we already have a "widgets" category that holds blocks and many of the core widgets we ported to native blocks. I'd expect we would just register these to that same category. This category shows above _Embeds_.

**Comment by afercia** [comment]
Thanks for adding the page title H1.

I may not be updated on the latest designs but I see a difference between the H1+top toolbar design for this Widgets page:

<img width="904" alt="widgets h1" src="https://user-images.githubusercontent.com/1682452/92003437-5270c200-ed41-11ea-902b-c95f43fe1312.png">

and the one proposed for the Navigation page in #24875 

<img width="916" alt="navigation h1" src="https://user-images.githubusercontent.com/1682452/92003496-63b9ce80-ed41-11ea-9348-588390a8b20f.png">

I guess exploring the same design for both pages is already in the works? Since these new pages will also set the new standard for all the new admin pages, I think consistency is key.

**Comment by mapk** [comment]
>I guess exploring the same design for both pages is already in the works? Since these new pages will also set the new standard for all the new admin pages, I think consistency is key.

Just for clarification, I don't think either of these pages are setting any standards for new admin pages. The focus is to bring in blocks without degrading the current experience (improving it ideally). As themes become more block-based, I imagine these screens will be deprecated (only used for older themes) because adding widgets/menus/blocks will happen in the full site editor.

**Comment by afercia** [comment]
I understand the reasoning but I think that these new admin pages, even if they're in a way "temporary", need to have a consistent design. They will live in the admin for several months, maybe years before they're deprecated. I'd definitely vote to have a consistent design in the admin. There are already too many different admin pages layouts and this isn't beneficial for users under many aspects.

**Comment by draganescu** [comment]
I think this overview issue reached it's end. We're deep into implementing the proposed designs and each open topic above has gone through their own issue / iteration so far. Can reopen if needed.
