### ISSUE TITLE
Unable to edit Classic block on mobile block editor

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#24563]
**Describe the bug**
On mobile, the Unsupported Block fallback mechanism does not work with the Classic block. 

**To reproduce**
1. Create a post (on the web) that contains a Classic block **and** any other block
2. Open the post inside the Gutenberg editor (on the WPiOS or WPAndroid apps)
3. The unsupported block placeholder will appear in place of the Classic block as expected
4. Tap the (?) button 
5. Tap the "Edit in web browser" button on the bottom sheet
6. The Unsupported Block editor will open but will be blank ⚠️
7. Tapping "Continue" to save and return to the block editor will erroneously remove the Classic block from the post ⚠️

**Expected behavior**
- The Unsupported Block editor should support editing the Classic block
- Tapping "Continue" to save inside the Unsupported Block editor should not remove the Classic block from the block editor

**Screenshots**

| iOS | Android |
| -- | -- |
| <img width="250" src="https://user-images.githubusercontent.com/1898325/90192842-bf6fe800-dd91-11ea-8dce-6c8de82947db.JPEG"> | <img width="250" src="https://user-images.githubusercontent.com/1898325/90192954-fa721b80-dd91-11ea-892e-94f13ea0d1d0.jpg"> |

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Smartphone (please complete the following information):**
 - Device: iPhone 11 or Samsung S10
 - OS: iOS or Android

**Comment by marecar3** [comment]
Thanks @guarani !

**Comment by guarani** [comment]
@etoledom or @marecar3, could either of you please confirm whether this can be closed now? I see https://github.com/WordPress/gutenberg/pull/24569 is merged.

**Comment by guarani** [comment]
Update: @etoledom or @marecar3 This was now closed but I see [a pending PRs for 1.32.1](https://github.com/WordPress/gutenberg/pull/24571) so not sure if this should actually be kept open now.
