### ISSUE TITLE
Block Directory: Installed blocks show up in the block directory results

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#24560]
**Describe the bug**
Blocks found in the block directory that are already installed are not treated differently than uninstalled blocks. If you search for a term that does not match the local block, but does match the criteria for the block directory, the installed block will appear as an option to install.

If the user clicks "Add Block", this technically works, but does show an error in console, trying to request a page that doesn't exist (ex: `http://trunk.wordpress.test/wp-admin/undefined`). I'm guessing that has to do with the [code to load new assets into the page.](https://github.com/WordPress/gutenberg/blob/e4931d8e536fb9ff69f0b9454e29139f9fe4ef5b/packages/block-directory/src/store/controls.js#L84-L89)

**To reproduce**
1. Install & activate [the "waves" block plugin](https://wordpress.org/plugins/waves/)
2. Edit a post, open the block inserter
3. Search for "gradients"
4. Waves and Starscape are both returned, but there's no indication that Waves is already installed

**Expected behavior**
Either the block in the regular block list should be shown, or the block directory entry should indicate that this is already installed. Or maybe nothing should change in the UI, and only the "add block" action should change?

Another approach could be finding out why "gradients" matches waves on wp.org, but not in the editor, and bringing that into line.

**Screenshots**
Waves is already installed, but it shows up to add here:

![Screen Shot 2020-08-13 at 4 21 51 PM](https://user-images.githubusercontent.com/541093/90184256-d1965a00-dd82-11ea-93ef-9b427fddb45a.png)

**Comment by MichaelArestad** [comment]
> Either the block in the regular block list should be shown, or the block directory entry should indicate that this is already installed. Or maybe nothing should change in the UI, and only the "add block" action should change?

I would expect the regular block should be shown. The block directory should not show up at all.

An exception to this could be down the road when a user can intentionally initiate a search of the block directory. Then, I would expect installed blocks would show something to indicate it's already installed. Like you mention, that could be as simple as changing the "Add block" button to "Insert." That will definitely need some design iteation.

> Another approach could be finding out why "gradients" matches waves on wp.org, but not in the editor, and bringing that into line.

I think that's also a good problem to solve early on if possible.

**Comment by tellyworth** [comment]
> Like you mention, that could be as simple as changing the "Add block" button to "Insert."

This seems like a great first step and easy to implement.

> An exception to this could be down the road when a user can intentionally initiate a search of the block directory.

Are there some small steps we can make towards this?

**Comment by dd32** [comment]
> Another approach could be finding out why "gradients" matches waves on wp.org, but not in the editor, and bringing that into line.

I believe `gradients` is matched in search as it's mentioned in the Readme Short Description & Readme Screenshots (Neither of which is present in Gutenberg).

Having the Install button swap for Insert is a reasonable middle ground I feel, we could also clear the search cache after installing, but that would result in the `gradients` search a second time only returning other blocks and no mention of the block we just installed.

Although I haven't tested it right now, searching for `Waves` should trigger the expected behaviour (which is how I always tested this block, and never thought of looking for gradients)

**Comment by StevenDufresne** [comment]
> > An exception to this could be down the road when a user can intentionally initiate a search of the block directory.
> 
> Are there some small steps we can make towards this?

I think #22149 is looking into solving that problem. The next step is probably to get a prototype going.

**Comment by MichaelArestad** [comment]
> Are there some small steps we can make towards this?

@tellyworth Possibly. I'm just starting to explore the options.

**Comment by StevenDufresne** [comment]
What about:


Block is filtered out of search result if block `title` or `name` matches the keyword.
 - Ideally, this logic would tie into Gutenbergs internal block filtering logic so it wouldn't need maintenance moving forward.

**Comment by StevenDufresne** [comment]
The one challenge I see is that if the block doesn't add the keyword to its keyword list, that specific block will behave differently from other installed block directory blocks _forever_. We may want to consider updating the inserter algorithm to contain more information about the block to widen the net.

Algorithm:
https://github.com/WordPress/gutenberg/blob/62673c977ca6b73330042dd82117db1121262fef/packages/block-editor/src/components/inserter/search-items.js#L99
