### ISSUE TITLE
Text link color doesn't change for Tag Cloud Block

### ISSUE THREAD

**Issue by khushbudesai1983** [WordPress/gutenberg#24568]
**Describe the bug**

**To reproduce**
- Add Tag Cloud Block
- Transform block into a group.
- From Block settings on the right side, change text link colour.

The text link colour in the tag cloud block won't change.
**Expected behaviour**
A text link colour should be changed as per the selected text colour of the block settings.

**Screenshots**

![Transform to group wp5 5 new #fcfbe1 bug](https://user-images.githubusercontent.com/66433333/90235641-475ffb80-de3f-11ea-9e75-179801dc65de.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser chrome

**Comment by annezazu** [comment]
Thanks for reporting this @khushbudesai1983! I replicated this with WordPress 5.5 & Gutenberg 8.7.1.

**Comment by kishanjasani** [comment]
@kirilzh Sorry I didn't see you have assigned yourself to it. I have added a PR for this issue please have a look. Thanks

**Comment by kirilzh** [comment]
@kishanjasani no worries. I was struggling myself to figure out what was the problem. Glad to see you handled it with CSS 🎉

**Comment by kishanjasani** [comment]
Thanks @kirilzh :slightly_smiling_face:

**Comment by youknowriad** [comment]
Hey there! thanks  for the issue.

But unless  I'm  missing something, this doesn't really make sense to me. These are links not text so they should get the link color (like they do now) and the text color shouldn't override them.
