### ISSUE TITLE
Changing gallery type leads to blank images

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#24588]
**Describe the bug**
When you change a tiled gallery block to a gallery and then back to a tiled gallery block again, the screen appears with grey images 
Screencapture - https://d.pr/v/GgkrMJ

**To reproduce**
* Original user report - #3229865-zd
* Create a tiled gallery
* Click to change it to a normal gallery and it changes fine
* Click to change it back to a "tiled gallery" again it all goes blank.
* I found that by clicking the mouse around the block that it updates

**Expected behavior**
For the gallery to change visually straight away

**Screenshots**
https://d.pr/v/GgkrMJ

**Comment by ntsekouras** [comment]
Hey @rickmgithub ! Could you please report this to Jetpack, as `tiled gallery` is a Jetpack block: https://jetpack.com/support/tiled-galleries/ 

Guide to report here: https://jetpack.com/contribute/#bugs
GH issues about this block: https://github.com/Automattic/jetpack/issues?q=is%3Aopen+tiled+label%3A%22%5BBlock%5D+Tiled+Gallery%22
