### ISSUE TITLE
Navigation Screen: Allow for editing a menu's name

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#24581]
When a navigation block is selected it's toolbar should display (#24580) the menu name. Pressing on the name would allow editing:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/191598/90284108-66f72400-de3f-11ea-9a71-ed94116ac387.png">

**Comment by noisysocks** [comment]
Makes sense. If we have this on the block as well we can use the name for the `nav` element's `aria-label`, too, which solves https://github.com/WordPress/gutenberg/issues/24369.

**Comment by tellthemachines** [comment]
> If we have this on the block as well we can use the name for the `nav` element's `aria-label`, too, which solves #24369.

This could work! What will be the initial state of the menu name field though? Can we make it so that it somehow prompts users to fill it in?

**Comment by aristath** [comment]
I love this idea!

> Can we make it so that it somehow prompts users to fill it in?

It should be possible to focus on the menu-name when the user adds a nav-block... The blinking cursor would indicate "hey, I can be changed".
Alternatively maybe a wiggly line if the title hasn't been altered, or some other familiar visual indicator that would make users click on the menu-title to change it?

**Comment by noisysocks** [comment]
Could the default not just be "Navigation" or "Site navigation"?

**Comment by draganescu** [comment]
In the navigation editor the toolbar does not show when the block is selected, the reason being that we don't have any block actions to put there. With this as the solution to renaming a menu, what would the ellipsis menu hold as items? Can we just not show that?

**Comment by shaunandrews** [comment]
> What will be the initial state of the menu name field though? Can we make it so that it somehow prompts users to fill it in?

> Could the default not just be "Navigation" or "Site navigation"?

I'd avoid using either of those, as they could too easily be confused with the actual components rather than an obvious placeholder name.

My first though is something like "(unnamed menu)". Its very descriptive, and the parenthesis hopefully enforce that this is something that can/should be changed.

**Comment by shaunandrews** [comment]
> With this as the solution to renaming a menu, what would the ellipsis menu hold as items? Can we just not show that?

This has come up before. I think we could simply remove it. However, I think there _could_ be items in there, like "Show block settings" and "Copy" at the very least.

**Comment by paaljoachim** [comment]
I really like the idea of being able to change the name seen in the toolbar.

One thing that came up....
Converting a block into a reusable block. At current it looks like this:

![Screen Shot 2021-01-22 at 13 19 56](https://user-images.githubusercontent.com/5323259/105490123-9ba3bd00-5cb4-11eb-8a5b-a3755400f69c.png)

Clicking the name "Convert to regular block" in the toolbar will not change the name of the block but convert it back to a regular block. Which means we should likely change how this functions today. Move the Reusable block name back into the toolbar and have it work in the same method as is being discussed in this issue. (I smell a new issue coming up....:)

**Comment by shaunandrews** [comment]
This has been superseded by https://github.com/WordPress/gutenberg/issues/28864
