### ISSUE TITLE
Post link is missing in the title block

### ISSUE THREAD

**Issue by ACEkin** [WordPress/gutenberg#24583]
Until this version, 5.5 the title block included a clickable link to take us to the actual post since the "View Post" display quickly disappears. I am not sure if this is intentional but to me it appears like a bug, a feature accidentally chopped.

If that feature was removed intentionally, could I ask you to consider this a bug?

**Comment by Soean** [comment]
This feature was removed in #21099. Now you can edit the permalink in the document sidebar.

**Comment by ACEkin** [comment]
But it makes it more cumbersome to access, lowers the user experience. The changes in this version increase the mouse clicks like the preview now needing two clicks. We will live with it but hard to understand the reason for more clicks. Oh, well ....

**Comment by Soean** [comment]
I am closing this issue as it is intentional and you opened #24584 for the UX enhancement.
