### ISSUE TITLE
Navigation Screen: Show block toolbar with menu name

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#24580]
When the Navigation block is selected it's block toolbar is not shown. In the screenshot below you can see the empty space above the block where I'd expect to see the Navigation block toolbar:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/191598/90282078-c3584480-de3b-11ea-9c61-7e41811792f5.png">

We should show the toolbar and have it display the menu's name:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/191598/90282220-f7336a00-de3b-11ea-9c01-7478688db3b2.png">

**Comment by tellthemachines** [comment]
The block toolbar was disabled in #23021 because none of its buttons were useful in the context of the Navigation screen. It does look a bit disconcerting now, but if we're going to bring it back we need to think carefully what needs to be displayed in it. There might not be anything useful in the "More options" dropdown for instance.

**Comment by shaunandrews** [comment]
At the very least, I'd expect to have the copy item:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/191598/90670737-9b912400-e221-11ea-81ec-488d3174804d.png">

If there's nothing to show, then I could see us just removing the button:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/191598/90670849-cda28600-e221-11ea-8088-d4a478ffa938.png">

**Comment by tellthemachines** [comment]
Hmm, "copy" for the Navigation block might be tricky in this context, because there's nowhere to copy it to. Creating a new menu always generates a new block, and we can't nest Navigation blocks. Option 2, without the button, seems good!

**Comment by draganescu** [comment]
I've [started working](https://github.com/WordPress/gutenberg/commit/376d597d9d6b773bb403caf35f7f0b597383ee92) on this and the only problem is that we don't have any menu details.

Worse is that the whole process assumed we'll never have "menu" properties to care about.

**Comment by talldan** [comment]
Superseded by https://github.com/WordPress/gutenberg/issues/28856.
