### ISSUE TITLE
Hooks in Fieldmanager

### ISSUE THREAD

**Issue by dlh01** [WordPress/gutenberg#2458]
Re. https://github.com/WordPress/gutenberg/issues/952#issuecomment-320523428, here's a summary of the hooks [Fieldmanager](https://github.com/alleyinteractive/wordpress-fieldmanager) uses by default for its meta boxes and enqueues.

- Fieldmanager fields for posts are initialized on `init`, but only after FM determines that the request is for `post.php` or `post-new.php`.
- `add_meta_box()` for these fields is called on `admin_init`.
- Field data is saved on `save_post` and by filtering `attachment_fields_to_save`.
- Additional miscellaneous functionality happens on `add_meta_boxes`.
- Support for `edit_form_after_title` is not technically built in, but we offer documentation about how to render fields there.

Scripts and styles are registered or printed on `admin_enqueue_scripts`, `wp_enqueue_scripts`, `admin_print_scripts`, and `admin_footer`. 

Fieldmanager's TinyMCE-powered field also uses `the_editor` and other editor-related filters.

**Comment by dlh01** [comment]
Additional notes from @davisshaver:

- Most plugins that extend Fieldmanager to provide more field types load on `after_setup_theme`.
- Fields that allow searching for a post, term, etc. to select use `wp_ajax_{$action}` endpoints.

**Comment by youknowriad** [comment]
Metaboxes support has been shipped, I'm closing this issue right now, if you find issues while testing your plugin with Gutenberg, please open specific actionable issues. Thanks for your help.
