### ISSUE TITLE
Provide more context for adding an image to gallery block within the block editor

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#24594]
_This was originally proposed on Core Trac by @ckoerner (https://core.trac.wordpress.org/ticket/50966)._

 When editing an existing gallery the user is presented with a preview of the gallery in the editor. This preview allows you to move and remove items. To add to the gallery the user is presented with two buttons. "Upload" and "Media Gallery" in a separate box beneath the gallery.

There is little context to these buttons to indicate that this is how you add items to the gallery. The other interface elements (X to remove, arrows to move an items position in the gallery) are common elements and easy to understand contextually. The placement of the "add" box is beneath the gallery and detached from the existing gallery itself.

Possible solution
Provide a header to this box that clearly states "Add Media" to indicate its purpose.

Consider making the tools to add media in-line with the gallery itself. Similar to how you can add a photo to an album in iOS. (Note the blue + symbol on the last row).

**Comment by JustinyAhin** [comment]
There are already several blocks that use a placeholder with instructions in this context. To maintain consistency in the editor, we could use them as a basis.

![Screenshot_2020-08-17 Edit Post ‹ one wordpress test — WordPress](https://user-images.githubusercontent.com/33403964/90366038-bbc4b580-e05e-11ea-864d-f372075862b0.png)

![Screenshot_2020-08-17 Edit Post ‹ one wordpress test — WordPress(1)](https://user-images.githubusercontent.com/33403964/90366052-c3845a00-e05e-11ea-9b08-9406804e0514.png)

![Screenshot_2020-08-17 Edit Post ‹ one wordpress test — WordPress(2)](https://user-images.githubusercontent.com/33403964/90366058-c7b07780-e05e-11ea-9433-7614c3f2c84b.png)

**Comment by jordesign** [comment]
Closing this issue as the interface for adding/managing galleries has changed from the initial report.
