### ISSUE TITLE
Column width is incorrect when using flex-basis percentages in the editor.

### ISSUE THREAD

**Issue by RCLStudio** [WordPress/gutenberg#24597]
As the blocks editor uses percentages to set flex-basis for column widths it is impossible to recreate an accurate column layout. Specifying equal width columns works fine. However when either an odd number of columns is specified or an equal number of columns but with different widths is specified the layout isn't accurate. This is due to the column width using percentages and not accurately taking account of any margins.

**Comment by aristath** [comment]
Related: https://github.com/WordPress/gutenberg/pull/24711

**Comment by youknowriad** [comment]
I think the crux of the issue is solved now that we can set custom units for columns.
