### ISSUE TITLE
Allow / Dissalow nested sub-blocks

### ISSUE THREAD

**Issue by Bysander** [WordPress/gutenberg#24596]
If I create a foo Block and want to use and allow core blocks in the editing experience - like core/columns - I feel there should be a way of allowing or disallowing certain nested blocks ie.
```
<fooBlock>
    <coreColumns>
        <coreColumn>
             <fooBlock> // <------ this shouldn't be allowed
```

Similarly - 
```
<fooBlock>
    <coreColumns>
        <coreColumn>
             <barBlock> // <------ this should only be allowed to be inserted within a foo Block
```

If I allow barBlock to have a parent of core/column then barBlock can be inserted anywhere with a column.

If I only allow barBlock in a fooBlock then the editor cannot insert them into a column layout within fooBlock in the interface.

It would be nice to be able to allow this via accepted formats similar to the below for example

`parent: [ 'foobars/foo > core/columns > core/column' ],`

to show exact structure or perhaps

`parent: [ 'foobars/foo.core/column' ],`

To show any column within a foo block??

foobars/foo could then have an allowed_blocks parameter of core/columns or foobars/bar depending on how the editor wants the layout.

**Comment by youknowriad** [comment]
Related #15682

**Comment by Bysander** [comment]
Another quick thought - could be to only allow blocks to sit within their own namespace... 

foobar/foo could sit anywhere but it's child or sub block foobar/bar can only sit within another foobar/* element.

**Comment by jordesign** [comment]
This appears to be resolved now (as best I can tell)
