### ISSUE TITLE
How can I change slug without saving the post to draft?

### ISSUE THREAD

**Issue by wpgaurav** [WordPress/gutenberg#24591]
Earlier I used to edit the slug by hovering over the Post title in Editor. But can't do that any more. 

Even sidebar doesn't have an option to do so.
![Screen Shot 2020-08-17 at 6 59 58 AM](https://user-images.githubusercontent.com/3599257/90349482-a435fe80-e057-11ea-98bc-b3f42943308d.png)

I will have to save the post to draft first to change the slug as I cannot publish it and then alter the slug later as it will cause harm to both my newsletter readers and social media followers.

**Comment by skorasaurus** [comment]
You should be able to edit the slug before saving the post to a draft. 

To do so: 
1. wp-admin/post-new.php?post_type=page
2. click the settings in the upper-right hand corner (

More importantly, do you still have this problem when all plugins are disabled? 

What it looks like for me before publishing a post
![Selection_007](https://user-images.githubusercontent.com/955351/90435279-c3a34a80-e09c-11ea-9bfc-c5a9b19cf471.jpg)

What it looks like for me after publishing a post
![Selection_008](https://user-images.githubusercontent.com/955351/90435274-c30ab400-e09c-11ea-9631-9aa63c895c3f.jpg)

In both cases, I'm able to edit the slug.

**Comment by wpgaurav** [comment]
Hi, this seems to be a problem with **post** post type only. 
![Screen Shot 2020-08-18 at 8 23 02 AM](https://user-images.githubusercontent.com/3599257/90465067-37d8ff00-e12c-11ea-8f57-92e930399e00.png)

For **snippet** post type it works exactly as you told me.
![Screen Shot 2020-08-18 at 8 23 40 AM](https://user-images.githubusercontent.com/3599257/90465091-42939400-e12c-11ea-9d8c-bdb705b75323.png)

**Comment by skorasaurus** [comment]
There could be many different reasons why this is happening and to rule some things out; 
temporarily disable all plugins if possible and seeing if you still have this issue.

**Comment by talldan** [comment]
Closing the issue as there's no further info from the reporter.

**Comment by wpgaurav** [comment]
Apologies for the delayed response. It seems it was a plugin that was interfering.
