### ISSUE TITLE
Right Aligned 1 column Gallery Block images Not Selectable components-button-group

### ISSUE THREAD

**Issue by carolynthrives** [WordPress/gutenberg#24605]
I have noticed with the latest version 5.5 the following situation loses the normal button options available for individual images within a gallery. They are visible (on the top image in the column but not able to be selected).

- I have a page with a title and several paragraphs of text.
- I have added a gallery, and update the settings of the gallery to show the gallery in 1 column and then aligned the gallery to the right (of the paragraphs).
- While aligned right, I am no longer able to select any of the images in the gallery and it is very difficult to select the gallery block at all. (Web Inspector reveals the only element select-able are the p tags so I can't click on the elements in the gallery.)
- The only option for me to select the gallery block in this situation is to select the _Gallery_ from the Block Navigator panel and then the only options available for editing the block is to add a caption at the bottom of the last image in the gallery. The components-button-group if clicked on selects the paragraph block instead.

If the gallery align right setting is removed the .components-button-group options are available on each image and able to be selected again. 

<img width="1468" alt="Screen Shot 2020-08-17 at 1 23 36 PM" src="https://user-images.githubusercontent.com/11789716/90440968-f7767400-e08c-11ea-9b69-1a8e3ae228dc.png">
<img width="1459" alt="Screen Shot 2020-08-17 at 1 22 45 PM" src="https://user-images.githubusercontent.com/11789716/90440976-fba29180-e08c-11ea-9ff3-3e05196afae6.png">
<img width="1453" alt="Screen Shot 2020-08-17 at 1 19 31 PM" src="https://user-images.githubusercontent.com/11789716/90440978-fcd3be80-e08c-11ea-8554-dc6d1c763612.png">

**Comment by nobleclem** [comment]
I am having the same problem.  My dirty hack for the time being is to add some css to the admin:

```
body.wp-admin .block-editor .wp-block-gallery.alignleft,
body.wp-admin .block-editor .wp-block-gallery.alignright {
    position: relative;
    z-index: 9999;
}
```

_Note: in no way should this be considered a real fix._

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this in the refactored gallery block:

![right-align](https://user-images.githubusercontent.com/3629020/132794019-76d61663-3f6a-4a6b-9f65-685448ba4617.gif)

Closing for now. Feel free to reopen if you can replicate in the new gallery format - enable the Gallery block experiment to test:
<img width="592" alt="Screen Shot 2021-09-10 at 3 08 14 PM" src="https://user-images.githubusercontent.com/3629020/132793243-932b8867-f437-47ee-93fa-cfabff98e405.png">

**Comment by nobleclem** [comment]
Where are you finding the "Experimental settings"?

**Comment by glendaviesnz** [comment]
sorry @nobleclem, I should have made that screenshot a bit wider. It is under the Gutenberg  menu when you have the plugin installed:

<img width="605" alt="Screen Shot 2021-09-13 at 9 48 22 AM" src="https://user-images.githubusercontent.com/3629020/133003827-8d10f449-ecf7-4d87-8fa1-996642441224.png">
