### ISSUE TITLE
Add light-weight extensions

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2460]
This ticket suggests a new type of light-weight editor extensions.

![extensions](https://user-images.githubusercontent.com/1204802/31618802-3599cb18-b293-11e7-8938-d1580b8de01f.png)

The ellipsis menu could hold light-weight extensions, such as:

- spell check
- share document for proof reading
- collaboration

... or indeed any other extension that might want to add actions that are global to all content on the page. These extensions would be very light-weight, and would _take an action on the page_, and then either present a modal with results/further actions, or be done. 

Thoughts?

---

This issue has been edited to focus on just extensions. The rearrangement has happened separately.

**Comment by jasmussen** [comment]
For comparison purposes, this is what the editor bar looks like today:

![screen shot 2017-08-18 at 11 44 42](https://user-images.githubusercontent.com/1204802/29453647-b14d3270-840a-11e7-8917-83e32d8e9a83.png)

**Comment by paaljoachim** [comment]
Hey Joen

This looks really nice:
![screen shot 2017-08-18 at 21 53 30](https://user-images.githubusercontent.com/5323259/29475381-bd6e7b54-845f-11e7-8f6e-c0945b116671.png)

The publish button becomes more prominent.
Settings words are removed to only show the icon (a tooltip could show up on hover with the words Settings.) It gives more space in the top right area.
An additional optional menu is added with the dots. It is much used in browsers. It can then also be extended as you showed in your example by plugin/theme authors.
What I am hesitant about is the Post Settings and Block Settings words. It creates repetition.
I would probably just have the word Post and Block and remove the word Settings.
Something like this:
![gutenberg-top-right-adjusted](https://user-images.githubusercontent.com/5323259/29475554-898a25bc-8460-11e7-9e11-a02762882f83.jpg)

**Comment by afercia** [comment]
The Settings toggle moved to the right of the publish button could help if there were no ellipsis button 🙂 . The a11y issue isn't solved yet. Ideally, a toggle that expands something should be immediately followed by the expanded "thing" in the source order. That would require to move the toggle to the last position in the sidebar and move the sidebar before the editor.

Having the toggle and the expandable panel contiguous in the source order feels very natural and intuitive to keyboard and assistive technologies users, as all they need to do is continue navigating content to find the sidebar.

If the toggle and the sidebar are _not_ contiguous, then there's the need to manage focus programmatically from the toggle to the sidebar. Also, when tabbing backwards from the sidebar, I'd expect to find the toggle. Instead, I'm forced to navigate through all the post content to finally land on the toolbar and have the ability to close/open the sidebar.

**Comment by jasmussen** [comment]
Your help is always appreciated, Andrea.

> That would require to move the toggle to the last position in the sidebar and move the sidebar before the editor.

If we wanted to have an ellipsis menu for plugins, where would it have to sit in the editor bar in order to not break the above? Would it be enough if it were to the left of the cog, right of the publish button?

**Comment by hedgefield** [comment]
Great work @jasmussen!

To the point of the ellipsis menu, it would seem natural to me to put it between preview and publish. After all, it contains extensions that affect what you are doing _within_ the post or page you are editing. It extends the options already visible in the toolbar with _more_ things you can do before publishing. Does that make sense?

The concept of a menu like that is great, it offers another hook for developers to put stuff into , without cluttering the toolbar more. 👌

**Comment by karmatosed** [comment]
I would love to see this implemented. I think we can reach a middle ground with the ellipsis menu, what do you think @afercia?

**Comment by afercia** [comment]
@karmatosed the a11y issue here is not solved yet. Considerations from my previous comment still stand.

**Comment by karmatosed** [comment]
Something to add into this would be a true distraction-free mode like this:

![1](https://user-images.githubusercontent.com/253067/31619022-7091036a-b28b-11e7-8db5-a0e62e13e70b.png)

I would like to work on a plugin for this, not sure about it being core. I also think as oppose to #2876 this is a true distraction free mode, enabled by this interaction.

**Comment by mtias** [comment]
Closing in favor of #3330 which has more context.
