### ISSUE TITLE
Add support for multiple blocks drag & drop

### ISSUE THREAD

**Issue by fr-laurentn** [WordPress/gutenberg#24624]
Hi, 

Presently, if you select multiple blocks, you can only move them up and down (unless you create a Group).

It would be great to be able to drag and drop multiple blocks wherever you want, the same way it is possible with a single block or a group.

What do you think about this enhancement?

**Comment by chthonic-ds** [comment]
Selecting multiple blocks and dragging them anywhere already seems possible in WP 5.5. Here I drag+drop 3 individual paragraph blocks together into a column:

![wp5-5-drag-drop-no-group](https://user-images.githubusercontent.com/29587253/90592719-5c230180-e23a-11ea-81fa-5d60b666b0d4.gif)

**Comment by fr-laurentn** [comment]
You're absolutely right!
I did not see that feature!

I guess I should close my ticket then. Sorry for the noise.
