### ISSUE TITLE
Template part placeholder button styles differ from other placeholders

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#24631]
**Describe the bug**
The Template Part block's placeholder's button styles have dark borders. It looks like this:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1123119/90554023-87322600-e152-11ea-87c9-3321fbe97774.png">

There are two reasons for this:
1. The Template Part's buttons are wrapped in a `buttonGroup` which, for some reason, adds a dark border around buttons. I recommend removing the button group in favor of doing what the Image placeholder does.
2. The "New Template" button should be a tertiary button.

**Expected behavior**
I expect it to look like this:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/1123119/90553948-6cf84800-e152-11ea-9105-f1de79d069fd.png">

**Comment by jeyip** [comment]
This looks like a quick win 👍 I'll work on this in my downtime and set up a PR by end of day here.
