### ISSUE TITLE
Navigation: Make Search block look nice when added to a Navigation

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24643]
Here's how the Search block looks when added to a Navigation:

<img width="635" alt="Screen Shot 2020-08-19 at 11 57 35" src="https://user-images.githubusercontent.com/612155/90583334-37676380-e213-11ea-8f0f-c4d9f90d378a.png">

And here's the frontend:

<img width="537" alt="Screen Shot 2020-08-19 at 11 58 09" src="https://user-images.githubusercontent.com/612155/90583349-41896200-e213-11ea-80ca-ef3a88e34112.png">

When added to a Navigation, we should give Search a simpler design treatment that flows nicely with the rest of the links.

**Comment by draganescu** [comment]
Related #22071

**Comment by aristath** [comment]
Isn't this something that a theme should do?

**Comment by noisysocks** [comment]
> Isn't this something that a theme should do?

Blocks come with base styles that a theme can then add to. We should ensure that the base styles are a good place for a theme to start from.

**Comment by shaunandrews** [comment]
The Search block is getting some customization options in #24666 — I'm not sure there's much the Navigation block needs to do here other than (maybe) toggle the Search label _off_ when added to a horizontal Navigation block.

**Comment by draganescu** [comment]
I updated this to reflect the work on updating the search block.
