### ISSUE TITLE
Gallery Columns not working

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#2465]
I was working on my talk about Gutenberg which is also built on Gutenberg, and I found an issue when I tried to add a gallery. It has 16 images, all of same size, and when I input the gallery to have 8 columns, here's how it looks:

![bug](https://user-images.githubusercontent.com/2649903/29476978-f8b12ac6-8483-11e7-8147-1e2fada8b770.png)

Up to 5 columns, it works properly. After 5, it starts breaking.

**Comment by mtias** [comment]
That's how it's supposed to work. If the items on the top row don't match the ones in the bottom, they'll have different sizes to accommodate the width.

The other aspect is we are setting `const MAX_COLUMNS = 8;` on galleries. We could change that, maybe, as there may be sensible reasons for having a larger count.

**Comment by HardeepAsrani** [comment]
All 16 images are of same with. So even then?

**Comment by gonzomir** [comment]
The issue with the uneven image sizes comes from the gallery styles, the items have `flex-grow: 1`. If `fle-gros` is zero, all images are the same size. I see a problem with gallery items' width calculations also. That's why with 16 images in 8 columns there aren't just two equal rows.
