### ISSUE TITLE
Vanilla Gutenberg blocks should be listed first

### ISSUE THREAD

**Issue by gmmedia** [WordPress/gutenberg#24651]
**Describe the bug**
If I use the `/` shortcut to access the blocks quickly, it shows the blocks of a Gutenberg add-on plugin first, instead of the vanilla Gutenberg blocks.
The behavior is since the update to WordPress 5.5.
I feel the original Gutenberg blocks should be listed first.

**To reproduce**
1. Install a third party block plugin. In my case Ultimate Add-Ons for Gutenberg.
2. Type `/li` (for the list block) in a new block editor line.
2. The list shows the third party blocks first.

**Expected behavior**
Show the vanilla blocks first.

**Screenshots**
![gutenberg-list](https://user-images.githubusercontent.com/7474702/90614815-7691b680-e20b-11ea-858d-f8cc777c5a8e.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- default

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 84

**Comment by mtias** [comment]
Also related #14868
