### ISSUE TITLE
Adding a fullwidth cover adds a class to the <html> element.

### ISSUE THREAD

**Issue by wolffe** [WordPress/gutenberg#24652]
**Describe the bug**
Adding a fullwidth cover adds a class to the <html> element:

`<html lang="en" class="alignfull">`

**To reproduce**
Use latest WordPress `5.6-alpha-48820`
Use Gutenberg `8.7.1`

1. Add a cover
2. Make it fullwidth
3. Check the `<html>` class

**Comment by wolffe** [comment]
Apparently, all sizes applied to a cover block get added as classes to the `<html>` element.

**Comment by aristath** [comment]
@wolffe I can't replicate this issue. :thinking: 
Have you tried disabling 3rd-party plugins and use the default theme?

**Comment by wolffe** [comment]
@aristath Yes, I have.

It's a JavaScript thing as if I inspect the HTML, I can see the class being added after half a second or so. This is a staging site, so I switched to Twenty Twenty theme and disabled all plugins except for Gutenberg.

I have the navigaton screen and the widget screen experiments enabled, if it matters.

**Comment by aristath** [comment]
Hmmm with those experiments enabled I still can't replicate (Firefox on Linux, tested 8.7.1 tag & master branch)
We'll need to wait and see if someone else can replicate the issue :+1:

**Comment by wolffe** [comment]
Very strange. If I disable Gutenberg it works, as in it doesn't add the class to the `<html>`. The downside for me is that all images on the page become stretched. I don't use Gutenberg in production, but I do use it to test the latest features, as I maintain one plugin and one theme for around 200 clients.

I'll keep testing, maybe I can find out more about this issue.

**Comment by getdave** [comment]
I also test this on the latest `master` build of Gutenberg Plugin and was unable to replicate. IN fact the `alignfull` class wasn't present on _any_ HTML element. I believe that the CSS applied to the Cover block actually hooks onto a selector such as

```css
.wp-block[data-align="full"] {
}
```

...so I suspect it might not be the Cover block that is causing your Issue. That said, the debugging you've done with disabling everything does seem to point to an issue.

Could you try a _clean_ WP install and then try the latest Gutenberg build from `master`?

**Comment by wolffe** [comment]
I have actually used a different method to achieve the fullwidth design, I used a custom class, so this issue can be closed. I use classes for alignment actually and disable the extra Gutenberg CSS.
