### ISSUE TITLE
PHP Notice:  Undefined index: host in wp-includes\l10n.php on line 1075

### ISSUE THREAD

**Issue by Pit37** [WordPress/gutenberg#24657]
**Describe the bug**
Try to install wp on local machine.

**Desktop (please complete the following information):**
windows 7
iis
php72
mysql8
wp5.5

**Comment by aristath** [comment]
@Pit37 that file is from WordPress-Core. It is not in the editor (which is what Gutenberg is).
For WordPress installation problems you can use the forums on https://wordpress.org/support/forum/installation/
I hope that helps!
