### ISSUE TITLE
Making settings bigger/smaller by dragging the border between content and settings.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2467]
It would be nice if a double arrow could show up when hovering over the line between settings and content. So a user can make the settings area bigger or smaller based on personal preference.

**Comment by karmatosed** [comment]
I think you are suggesting to be able to resize the Inspector? I would be against this - at least right now. I think it works being the size it is and for now would like to do testing with it as is.

Maybe at a later date we could consider what the feedback from testing is and iterate.

**Comment by paaljoachim** [comment]
I think I was saying a double arrow between blocks/settings area on the right and the content on the left. As it can sometimes feel like the settings column is a bit skinny. Having the option to make it thicker would be nice.
