### ISSUE TITLE
Media & Text: set image size

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#24688]
From the forum: https://wordpress.org/support/topic/set-image-size-within-media-text-block/

When otherwise choosing an image in a Gutenberg Block, you can choose which image size (medium, large, etc.). Yet within the Media & Text block, this isn’t possible, leading to the browser rendering a big sized image (e.g. 1950px) when I’d prefer to only use my medium 600px image. I might be overlooking something, happy to hear if that’s the case.

**Comment by bph** [comment]
For 🐝 -docs: Added to [Trello Card ](https://trello.com/c/wCU0qRld/6-mediatext-block)
