### ISSUE TITLE
FSE/Global-Styles mods for adminbar.

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#24682]
The adminbar currently has links to create new posts, pages etc, as well as a link to go to the customizer.
With FSE & global styles, some things won't make a lot of sense, while new additions will be necessary to make editing sites easier.

If the currently active theme supports FSE, then I propose the following modifications to the adminbar:

* **Customize**: The customizer can still be used in some cases but won't be as frequent. I propose we either remove it for FSE themes, or at least move it under the sitename link - which already has a submenu containing dashboard & themes.
* **Global Styles**: This could take the place of the current "Customize" item.
* **Edit Template**: When viewing a specific page, we could check if there's a specific template for that page/post. If there is one, we could add a top-level item in the adminbar to allow easier access to it, so users can edit it directly. 
* **New Template**: When viewing a specific page/post, if there is no template for this post, then we could add a new item under the "+New" menu to allow creating one. The benefit of having it there would be that on creation it would automatically add the correct title to allow for templates-hierarchy. User's won't have to think "now what do I need to call this?", it will be "post-25" and that's it.

**Comment by noahtallen** [comment]
I agree we should make some changes here! (maybe even also to wp-admin sidebar? 👻 )

> Global Styles: This could take the place of the current "Customize" item.

I think the goal is for this to be part of the site editor in general (see #24250). maybe this just opens the site editor?

> New Template: When viewing a specific page/post, if there is no template for this post, then we could add a new item under the "+New" menu to allow creating one. The benefit of having it there would be that on creation it would automatically add the correct title to allow for templates-hierarchy. User's won't have to think "now what do I need to call this?", it will be "post-25" and that's it.

This is interesting, but I'm not sure it's possible?? Like, in order for WordPress to render the page/post, there _must_ be a template to layout the page. A lot of times this wouldn't be specific to one page, but be general for several pages (like a `singular` template). Or are you talking more just an "override template" link?

**Comment by aristath** [comment]
> maybe this just opens the site editor?

Yes, that's what I was thinking

> there must be a template to layout the page

Yes, I usually start with a catch-all `index` and go from there.

> Or are you talking more just an "override template" link?

Pretty much yes. A link that would allow users to create a new template specifically for that page/post.

**Comment by aristath** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/27135
