### ISSUE TITLE
Editor loads slowly in Calypso and wp-admin

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#24692]
**Describe the bug**
When opening the editor in Calypso and wp-admin it is very slow to open.

**To reproduce**
Its a simple site, the pages/posts in Calypso and WP-Admin open incredibly slow. 
For one HE it took 30 seconds for a page/post to open after being clicked. 
Everything else opens fine though. 
They have 1000+ pages and 7000+ posts but File Tools shows their usage is 1194.98 Mb. 
User says the slowness started after the block editor was added
Happens on multiple browsers and systems

**Expected behavior**
Pages and posts to open promptly

LINKS:
#3217835-zd

**Comment by sirreal** [comment]
I believe this issue was opened in the wrong repository. @rickmgithub I believe this should be in https://github.com/Automattic/wp-calypso
