### ISSUE TITLE
Widget Editor: Activating/Deactivating widgets/blocks in a single area screen

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24698]
In the single area Widget Editor [I proposed here](https://github.com/WordPress/gutenberg/issues/24561#issuecomment-677858593), I still needed to outline how a user might activate/deactivate widgets from within the respective widget areas.

#### Activating a widget/block
When a widget is inactive, it appears in an Inactive Widget Area. This area can be accessed from the Widget Area Switcher in the topbar. To move an inactive widget to another area, the user can access the block's toolbar which includes a section for activating the block.

![Screen Shot 2020-08-20 at 2 08 38 PM](https://user-images.githubusercontent.com/617986/90826052-ae255f00-e2ee-11ea-9cb2-ae7dae83a930.png)

Once the block is activated, it leaves the the Inactive Widget area and pushes the user to the active widget area. Here's a prototype how that might work. [Figma file](https://www.figma.com/file/rfovVm34ULtWr4hYaFlLtv/Widget-blocks-Editor?node-id=231%3A0).

**Prototype**
![move-inactive-widget](https://user-images.githubusercontent.com/617986/90826564-84b90300-e2ef-11ea-977a-a22eba98c0e0.gif)

### Deactivating a widget/block
Sometime users want to deactivate a widget from their widget area by moving it to their Inactive Widget area. Within a single area editor, this can be done by also using the block's toolbar. In the toolbar, there is an option to "Move to Inactive Widgets". 

![Screen Shot 2020-08-20 at 2 17 50 PM](https://user-images.githubusercontent.com/617986/90826831-fb560080-e2ef-11ea-8142-5371472a1165.png)

**Prototype**
![move-active-widget](https://user-images.githubusercontent.com/617986/90826877-0c9f0d00-e2f0-11ea-83d3-c73b1c54a0b6.gif)

### Feedback
- Any thoughts around this particular flow?
- Did I miss anything?
- Did you have another way in mind?
- How does adding these options to the block's toolbar feel?

**Comment by youknowriad** [comment]
I think "Inactive widgets" is just another widget area technically, so why not just use #24703 to solve this instead of having a separate design?

**Comment by mapk** [comment]
I'm favoring that direction as well, @youknowriad. Now we need to figure out how to move widgets between areas as @noisysocks pointed out here: https://github.com/WordPress/gutenberg/issues/24703#issuecomment-677968463

I'm closing this issue as we focus more around moving blocks rather than activating/deactivating them.
