### ISSUE TITLE
Unable to edit Classic Block on regular (web) editor

### ISSUE THREAD

**Issue by claudiulodro** [WordPress/gutenberg#24696]
**Describe the bug**

This seems related to https://github.com/WordPress/gutenberg/issues/24563, however I didn't see an issue or patch for the regular web editor. After saving a post with a Classic Block, the contents of the Classic Block are not visible and the block encounters a JS error when used.

**To reproduce**
1. Create a new post with a Classic Block. Save the post.

<img width="793" alt="Screen Shot 2020-08-20 at 11 38 52 AM" src="https://user-images.githubusercontent.com/7317227/90811909-49600980-e2da-11ea-8ebb-df85bf7687b5.png">

2. Refresh the page. Observe the block content is missing from the Classic Block:

<img width="703" alt="Screen Shot 2020-08-20 at 11 39 26 AM" src="https://user-images.githubusercontent.com/7317227/90811951-5a107f80-e2da-11ea-9f74-5f1a8b9e2377.png">

3. With the JS console open, click on the block toolbar for the Classic Block (the gray bar that says "Classic"). Observe block encounters a fatal error and the JS console logs `Cannot read property 'getContent' of null`:

<img width="747" alt="Screen Shot 2020-08-20 at 11 39 39 AM" src="https://user-images.githubusercontent.com/7317227/90812317-c68b7e80-e2da-11ea-8c21-535348140161.png">

4. Go to code view. Observe content is still there:

<img width="760" alt="Screen Shot 2020-08-20 at 11 39 52 AM" src="https://user-images.githubusercontent.com/7317227/90812219-9e9c1b00-e2da-11ea-9bf6-3ba89a45ff97.png">

5. Go back to visual view. Observe block preview works correctly after coming from code view:

<img width="768" alt="Screen Shot 2020-08-20 at 11 40 00 AM" src="https://user-images.githubusercontent.com/7317227/90812226-a065de80-e2da-11ea-916c-aadd3b5e6bb2.png">

**Expected behavior**
I expected the block content of Classic Block to render correctly when editing a saved post.

**Screenshots**
See steps to reproduce above.

**Editor version (please complete the following information):**
- WordPress version: 5.5.0
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? I reproduced the error on a clean site using only WP 5.5.0 and Gutenberg 8.8.0
- If the Gutenberg plugin is installed, which version is it? 8.8.0. This bug seems to have been introduced in 8.8.0, as rolling back to 8.7.1 solves the issue.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.125

**Comment by Soean** [comment]
I can reproduce the issue on WP 5.5 with Gutenberg 8.8.0

**Comment by bobbingwide** [comment]
> I can reproduce the issue on WP 5.5 with Gutenberg 8.8.0

**In my opinion, this issue deserves more attention.** 
The problem has not been resolved with WordPress 5.5.1 and Gutenberg 8.9.1

To users who are editing content that was created a long time before the block editor was introduced it might appear that the content has been lost. They may not be aware of the workaround to switch to the code editor.

**To reproduce:**
1. Edit a post created before the block editor existed. It will appear to not contain anything at all.
2. Switch to the Code Editor and the content appears.
3. Switch back to visual and it's still OK.

Note: The Console log does not display the TypeError if you don't click on the Classic block.

**Comment by bobbingwide** [comment]
> The problem has not been resolved with WordPress 5.5.1 and Gutenberg 8.9.1

In my development environment the problem occurs when Jetpack 8.9 is activated and does not occur when it's deactivated. 
I haven't yet been able to isolate the changes needed to find a solution to the issue on the live site.

**Comment by bobbingwide** [comment]
> In my opinion, this issue deserves more attention.

I have reproduced the problem in a local development environment. 
Originally the problem only occurred for a custom post type, but now I can make it appear for posts and pages.

Theme: Twenty Twenty 1.5
Plugin: Gutenberg 8.9.1
WordPress: 5.5.1

Sometimes the problem doesn't occur on first edit, but does when you reload the editor with the Ctrl key pressed. 
Using: Chrome and Windows 10.  Server: Windows, Apache, PHP 7.4.0

### Possible workaround
If deactivating Gutenberg or Jetpack is not an option, then a possible workaround is to activate the Test jQuery Updates plugin (  wp-jquery-update-test ) and set the jQuery version to 3.5; jQuery Migrate can be Enable or Disable.

**Comment by skorasaurus** [comment]
I'm also encountering this error as well as [@bobbingwide confirmed](https://github.com/WordPress/gutenberg/issues/24696#issuecomment-688100141) although I am not able to consistently reproduce it and I can't determine why yet.

The content is still present when I view it through the code editor.  

I'm able to reproduce this across Gutenberg 8.9.0, 8.9.1 and 8.9.2 (I haven't tested anything earlier(. 
FWIW, I've had this occur on both servers using ngnix and apache.
