### ISSUE TITLE
Gutenberg editor much less responsive after writing ~300 words 

### ISSUE THREAD

**Issue by picajoso** [WordPress/gutenberg#24690]
After yesterday's update of Gutenberg to version 8.8.0, the editor seems to show some kind of problem when trying to write longer posts. 

**To reproduce**
1. Start writing a post
2. Keep writing, maybe after 300 words the editor starts responding more and more slowly.
3. If I keep writing, the latency becomes worse and worse, and characters seem to show long seconds after I type them. 

**Expected behavior**
No latency, fast response as always has been the case.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it? 8.8.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Firefox
 - Version 79.0 64 bits

**Comment by youknowriad** [comment]
Hi there! sorry for the trouble, our performance tests were not able to capture any meaningful difference. That said, I'd like to understand why the update to 8.8 triggers this. 

 - Do you have any active plugins besides Gutenberg? Would you be able to disable those to see if there's any impact?
 - Anyone able to share an example post where the issues happen?

Thanks.

**Comment by jeffersonrabb** [comment]
I can reproduce the issue consistently on sites with nothing but WordPress 5.5/Gutenberg 8.8, following these steps:

- Spin up a new Jurassic Ninja site.
- Activate Gutenberg 8.8
- Paste 5 paragraphs of Lorem Ipsum 10 times, so the post contains about 50 paragraphs. (For testing accuracy, I've pasted the Lorem Ipsum below)
- Begin typing. 
- After typing several paragraphs, observe long delays between keystrokes and text appearing in the editor. 
- Blocks of text tend to appear all at once after a delay. 
- Disable Gutenberg 8.8 and re-try the above. The stickiness/delays should be gone.

I was able to reproduce this in MacOS Chrome and Firefox. 

```Nullam quis ante. Praesent porttitor, nulla vitae posuere iaculis, arcu nisl dignissim dolor, a pretium mi sem ut ipsum. Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Praesent ac sem eget est egestas volutpat.

Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros. Ut varius tincidunt libero. Vestibulum fringilla pede sit amet augue. Fusce vulputate eleifend sapien. Fusce fermentum odio nec arcu.

Vestibulum fringilla pede sit amet augue. Praesent congue erat at massa. Fusce fermentum odio nec arcu. Donec orci lectus, aliquam ut, faucibus non, euismod id, nulla. Phasellus magna.

Morbi vestibulum volutpat enim. Cras risus ipsum, faucibus ut, ullamcorper id, varius ac, leo. Praesent venenatis metus at tortor pulvinar varius. In hac habitasse platea dictumst. Fusce vel dui.

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Vestibulum ullamcorper mauris at ligula. Aenean viverra rhoncus pede. Aliquam lobortis. Mauris sollicitudin fermentum libero.```

**Comment by youknowriad** [comment]
Thanks for the instructions @jeffersonrabb I did manage to reproduce, I wonder why the performance test didn't catch the regression. The good news is that the difference between Gutenberg 8.8 and WordPress 5.5 is not big, so it might help us figure out what PR introduced the regression.

**Comment by automattic-ian** [comment]
Similar symptoms have been longstanding for users on less powerful hardware and posts/or pages more than around 8k words long. ex #3251148-zen but has since gotten worse recently.
