### ISSUE TITLE
Widget Editor: Moving widgets between areas

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24703]
In the `widgets.php` screen widgets can be moved by dragging and dropping into different areas because all areas are available in the one screen. My proposal for a [single area screen](https://github.com/WordPress/gutenberg/issues/24561#issuecomment-677858593) will change this. That means users can no longer drag and drop widgets between areas. So I'm exploring alternative ways to move widgets.

### Block toolbar
I've iterated around the idea of bringing the ability to [activate/deactivate widgets using the block toolbar](https://github.com/WordPress/gutenberg/issues/24698). This is somewhat limited to that particular action though, so can we expand on that to move widgets to any area?

It might be better to get away from these "activate" and "deactivate" scenarios. Since I'm proposing to keep an Inactive Widget Area, we can just have the user "move" their widgets to any area. If the widget is moved to the Inactive Widget Area, the widget, of course, becomes deactivated. So how should we surface this to the user?

### Option 1 - Ellipses menu dropdown
We could add consistent block toolbar options (in ellipses menu) for the Legacy Widget block that wraps the widgets. However, this add a lot of options to an already long dropdown.

![Screen Shot 2020-08-20 at 2 38 49 PM](https://user-images.githubusercontent.com/617986/90828465-e62ea100-e2f2-11ea-8f18-9e628a238058.png)

### Option 2 - Top level in block toolbar
There is the option to surface these interactions in the top level of the block toolbar making them their own dropdown. This would only be available for the **Legacy Widget block**.

![Screen Shot 2020-08-20 at 2 37 34 PM](https://user-images.githubusercontent.com/617986/90828353-b54e6c00-e2f2-11ea-89e5-16c04cf349f8.png)

----

### Introducing problems?
I do see an obvious problem with this solution right now. Any changes to an Editor need to be saved. If I "move" a block from one area to another, how do these both get saved? Which editor should I be viewing after the move is complete?

**Possible options for this flow**
- Save the current screen automatically and push the user to the new screen where the widget now exists and require a save.
- Save both screens automatically, but keep the user in their current screen. This could require a prompt of some kind to ensure the user is aware of what's about to happen.
- Other ideas?

### Moving vs. Copy/Paste
"Moving" could also be going down a rabbit hole. This is how I landed earlier on active widgets only being allowed to move to the inactive widgets area, while inactive widgets could only be moved to active widget areas. Active widgets, initially as I thought about this, would not allow moving between widget areas using the drop down. The way that could be accomplished is by copy/pasting (existing ability) the block from one widget area into the other. That would be straightforward requiring the user to save their editor states before jumping to the next one and pasting it in.

### Feedback
I'm looking for feedback on whether or not this "move" ability feels like a good solution.

**Comment by noisysocks** [comment]
> - Save the current screen automatically and push the user to the new screen where the widget now exists and require a save.

This might cause unexpected updates to go live on the user's site.

> - Save both screens automatically, but keep the user in their current screen. This could require a prompt of some kind to ensure the user is aware of what's about to happen.

I imagine most users would just dismiss the prompt without reading it.

> - Other ideas?

This reminds me of the _if I cut a file, but then don't paste it anywhere, where does the file go?_ problem that Apple infamously solved by not adding _Cut_ to Finder 🙂

So, along those lines, we could have only _Copy to_ instead of _Move to_. 

Alternatively we could do something similar to the Site Editor where clicking _Save_ brings up an interface that lets you save multiple things at once.

<img width="1020" alt="Screen Shot 2020-08-21 at 10 16 14" src="https://user-images.githubusercontent.com/612155/90838127-5a228500-e397-11ea-8b23-3fe7134bbe9f.png">

**Comment by noisysocks** [comment]
I think I prefer leaning on the existing block copy and paste mechanism. _Copy_ already exists in the ellipsis menu. Could we the discoverability of _Paste_?

**Comment by mapk** [comment]
@noisysocks, I like those ideas! I'm working through those flows a bit more and closed the issue about activating/deactivating widgets in favor of this one. I'll get some prototypes on _Copy to_ posted soon.

>I think I prefer leaning on the existing block copy and paste mechanism. Copy already exists in the ellipsis menu. Could we the discoverability of Paste?

I've been thinking about this one as well, but it's just not as explicit. This may not be a problem, but thinking through edge cases where problems could arise is important.

**Comment by mapk** [comment]
Considering @noisysocks' feedback along with others, it's worth moving forward with the copy/paste functionality that comes with all blocks inherently. This would play out similarly to this prototype below:

[Prototype](https://www.figma.com/proto/rfovVm34ULtWr4hYaFlLtv/Widget-blocks-Editor?node-id=416%3A182&viewport=-4441%2C1502%2C1&scaling=min-zoom)

![copy-paste](https://user-images.githubusercontent.com/617986/91234328-dabee980-e6e7-11ea-878e-520f3d21a4d7.gif)

**Comment by mapk** [comment]
Looks like we're going to keep the multiple widget areas on screen. This means drag and drop will still work between them. I'm going to close this issue since we're going in that direction.

https://github.com/WordPress/gutenberg/issues/24561#issuecomment-681167207
