### ISSUE TITLE
Author Dropdown doesn't include all authors

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2470]
This is whatever version is currently on https://make.wordpress.org/core .  Maybe 0.9.0? 

## Issue Overview
The author drop down is limited to 100 users. This means that some authors default to writing a post in someone else's name 

## Steps to Reproduce (for bugs)
Add over 101 users to a site. Log in as one that isn't in the first 100 alphabetical. 

This can be seen on make.wordpress.org/core if your first name is after Peter.

**Comment by youknowriad** [comment]
Since the API is paginated we'll need some virtual scroll loading or a search input

**Comment by danielbachhuber** [comment]
Closing in favor of #4622

Also related: #4623 #4632
