### ISSUE TITLE
Buttons Block: Add full-width button style

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#24705]
It'd be nice to allow a button to be full-width of a parent. 

For example, full-width buttons are pretty common in a pattern like a pricing table.

![Frame 20](https://user-images.githubusercontent.com/908665/90840065-e52c5c80-e350-11ea-8a86-68baf78e24d1.jpg)

Full-width buttons can be seen in forms too, and it could be useful to add a block style for it.

**Comment by alaczek** [comment]
Yes, I agree. I'm wondering though if it wouldn't be more useful to be able to set the width of the button, which would cover full-width buttons too. This is the design I had in mind:

![image](https://user-images.githubusercontent.com/4550351/90996785-2481d400-e603-11ea-95e8-a6f0d8dcbc98.png)

**Comment by mtias** [comment]
cc @apeatling for thoughts. It seems like some predefined percentages could be useful as well — 50%, 25% etc

**Comment by apeatling** [comment]
I like the idea of setting percentages, an using flexbox having the columns sort themselves out based on width.

**Comment by iamtakashi** [comment]
The awesome work from @stacimc made this reality, thank you!
