### ISSUE TITLE
Site-Title should be a link

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#24716]
There are 2 basic blocks for branding a site using FSE: The site-logo block and the site-title block.
The site-logo block links to the frontage of a site as it should. The site-title however does not.
If design options from https://github.com/WordPress/gutenberg/issues/23228 get implemented, then the site-name block will be really usable and a lot of people will resort to that for branding. The issue is that they can't use it the way a sitename usually works in all themes etc, because it's not a link.

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/gutenberg/issues/23861
