### ISSUE TITLE
gutenberg remove non english word in slug (save and draft)

### ISSUE THREAD

**Issue by ShahramRahbari** [WordPress/gutenberg#24710]
You can see the bug in this video when the draft is saved.

https://youtu.be/vvllwawBljs

When we want save and draft a title include both english keyword next to non english keyword in gutenberg plugin, automatically the permalink register only english part and it will delete non english part of the title

Regards Shahram Rahbari

**Comment by nosolosw** [comment]
Hi, I've tested this is the same error reported in the forums [here](https://wordpress.org/support/topic/wordpress-5-5-permalink-bug/).

Both the block editor & the classic editor admit UTF-8 characters (I've tried with Chinese and emoji in the title) in WordPress 5.4. However, in WordPress 5.5, it only works in the classic editor.

**Comment by james58899** [comment]
PR https://github.com/WordPress/gutenberg/pull/21007 remove ALL non english characters.
I do not think should prevent user using non english characters.

**Comment by korynorthrop** [comment]
Are there any updates on fixing this bug? It's kind of a big deal for those of us that run multilingual websites with non-Latin languages.

**Comment by Veske** [comment]
Any updates on this ?

**Comment by aristath** [comment]
A pull-request was added in #32232 to allow non-latin characters in slugs :+1:
