### ISSUE TITLE
wp.domReady, editor-styles-wrapper ready?

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#24714]
When does the `wp.domReady` event/handler fire? Is it equivalent to the classic DOMReady?
How can I find out when the `editor-styles-wrapper` element becomes available? Do I have to use a `MutationObserver` for this?

**Comment by gwwar** [comment]
> When does the wp.domReady event/handler fire? 

It's a small wrapper around `DOMContentLoaded`

https://github.com/WordPress/gutenberg/blob/916606511c835dea94bc9786b379baed7c57a865/packages/dom-ready/src/index.js#L31-L41

> How can I find out when the `editor-styles-wrapper `element becomes available?

I'm relatively confident that it's tied to the block editor init, so DOM Ready might not be a bit early in some cases.

What are you trying to do? There might be a slotfill or some other hook that may be available.

**Comment by Thelmachido** [comment]
There hasn't been any movement on this in a while,  I will close this issue for now. Please feel free to open this @strarsis if you want to circle back to this

**Comment by strarsis** [comment]
Workaround for Gutenberg editor becoming ready, including its `iframe` element:
https://gist.github.com/KevinBatdorf/fca19e1f3b749b5c57db8158f4850eff?permalink_comment_id=4469942#gistcomment-4469942
