### ISSUE TITLE
Adding block is impossible when window witdh is less than 780px

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2471]
## Issue Overview

If I’m using Gutenberg at a small width, I can’t add a block using the pop-up. I have to enlarge the window of my browser to have access to the interface and select a block.

When I click on the « plus » button, the pop-up appears partially on the left side and at the top or the bottom of the page, repeatedly.  

![bug gutenberg mov](https://user-images.githubusercontent.com/2078386/29490204-1f1cebc6-8535-11e7-93b7-3953aa1a10c6.gif)

## Steps to Reproduce (for bugs)

1. Reduce window of the browser to 780 px or less ;
2. Click the plus button to add a block
3. You should not be able to access the whole interface.

I’m using latest stable versions of Gutenberg (0.9) installed on WordPress (4.8.1) and used in Safari (10.1.2) on macOS Sierra (10.12.6).

## Expected Behavior

I should be able to select and add a block for every window size.

## Current Behavior

I have to enlarge the window to gain access to block selection.

**Comment by aduth** [comment]
Noting while this is a valid bug, in the meantime you may have success using the inserter button from the header bar.

![Header inserter](https://user-images.githubusercontent.com/1779930/29792483-8d1cdd72-8c0e-11e7-9126-94a13417a3cf.png)

**Comment by nicolinuxfr** [comment]
No, it's the same problem for me under 780 px : 

![capture d ecran 2017-08-28 a 22 41 08](https://user-images.githubusercontent.com/2078386/29792847-1a23d4ea-8c42-11e7-8071-51d44787ee0c.png)
![capture d ecran 2017-08-28 a 22 41 00](https://user-images.githubusercontent.com/2078386/29792850-1c863c0a-8c42-11e7-8dfb-6e4d2b8057e5.png)

**Comment by aduth** [comment]
Additional context at https://github.com/WordPress/gutenberg/issues/2602#issuecomment-325980530

**Comment by karmatosed** [comment]
Closing as we now have a single place to include all issues for mobile inserter in #2691
