### ISSUE TITLE
Cursor inserted at the beginning of a paragraph instead of where the click happened

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2472]
## Issue Overview

Using Gutenberg 0.9, a click inside an existing paragraph places the cursor at the beginning of the text, instead of where I clicked. I have to click again at the same spot to place the cursor where I want it.

I made a video, maybe it will be easier to understand this way :

![gutenberg09-bug-cursor](https://user-images.githubusercontent.com/2078386/29490348-83effcf6-8539-11e7-9d1a-9657ef875aa6.gif)

I’m using latest stable versions of Gutenberg (0.9) installed on WordPress (4.8.1) and used in Safari (10.1.2) on macOS Sierra (10.12.6).

## Related Issues and/or PRs

I’m not sure, but maybe it has something to do with this bug, which I also experience from time to time.

https://github.com/WordPress/gutenberg/issues/1607

**Comment by annaephox** [comment]
@nicolinuxfr Just checking if this one has been fixed - we can't replicate. Thanks!

**Comment by nicolinuxfr** [comment]
No, it has not been fixed for me.

**Comment by litka** [comment]
I believe the issue is specific to Safari.
