### ISSUE TITLE
The block must have a registered category.

### ISSUE THREAD

**Issue by dadmor** [WordPress/gutenberg#24738]
**Describe the bug**
Editor js crashed

**To reproduce**
1. Install gutenberg plugin
2. Start edit or add new post
3. Open browser console 

blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/paragraph" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/image" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/heading" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/gallery" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/list" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/quote" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/audio" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/button" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/buttons" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/code" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/columns" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/column" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/cover" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/file" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/group" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/freeform" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/html" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/media-text" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/missing" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/more" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/nextpage" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/preformatted" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/pullquote" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/separator" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/spacer" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/subhead" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/table" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/text-columns" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/verse" must have a registered category.
we @ blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3
blocks.min.js?ver=423068d7079f57cf9f02458ccb4a6131:3 The block "core/video" must have a registered category.

**Comment by aristath** [comment]
@dadmor I just tested this and can't replicate...
Is this still an issue for you?
Do you have any other plugins that may be interfering with blocks & the editor?

**Comment by talldan** [comment]
Closing the issue as there's no response from the reporter.
