### ISSUE TITLE
Classic block image caption updates not reflected on first "Insert"

### ISSUE THREAD

**Issue by devNigel** [WordPress/gutenberg#24730]
**Site**: http://rhymingcoupletsblog.wordpress.com

**Describe the bug**
Caption updates for images inserted in Classic block are not reflected on the first `Insert` click. The updates to the caption are reflected only after clicking the edit icon for the image and `Insert` it again.

**To reproduce**
1. Go to Block editor and add Classic block.
2. Click on Add Media icon on the Classic block toolbar.
3. Select an image from Media library with no captions.
4. Add a caption.
5. Click on Insert
6. Observe caption is not added.
7. Click edit on the image and click on Insert button. The caption will be added.

**Expected behavior**
Updates to captions should be reflecting on the first `Insert` button click.

**Screenshots**

Here's a gif: 
![image](https://i.imgur.com/11pRBtA.gif)

**Editor version (please complete the following information):**
- WordPress version: latest version on WordPress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? - default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.135 (Official Build) (64-bit)

**Comment by talldan** [comment]
I couldn't reproduce this on a standalone WordPress install.

@devNigel It may have already been fixed, or it might be a WordPress.com specific issue (the WordPress.com media library is very different to the one in WordPress core).
