### ISSUE TITLE
Embeds: Spotify embed not working

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#24737]
**Describe the bug**
Embedding Spotify links fail in the editor with the error "Sorry, this content could not be embedded"

**To reproduce**
1. Create a new post
2. Either paste in a Spotify song, album or playlist link on a new line, or add a Spotify block and paste the link in there

**Expected behavior**
For the Spotify player to be embedded for that song/album/playlist

**Screenshots**

<img width="765" alt="Add_New_Post_‹_My_Core_Sandbox_—_WordPress" src="https://user-images.githubusercontent.com/11873759/90957070-e31ae880-e48b-11ea-9397-a5d86c1e0574.png">

The browser console shows a 404 error when trying to embed the link:

<img width="1030" alt="Add_New_Post_‹_My_Core_Sandbox_—_WordPress" src="https://user-images.githubusercontent.com/11873759/90957109-1a899500-e48c-11ea-89c1-01f9e93fd645.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Tested with both the default editor and Gutenberg plugin 8.8.0

Also tested this with the Classic Editor v 1.6, and the embed is failing there as well, just displaying the link as plain text (not hyperlinked) in the published post.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6
 - Browser Firefox
 - Version 79.0

**Additional context**
Reported in the WordPress.com forums at https://wordpress.com/forums/topic/spotify-embed-is-not-working/, and I've seen a few complaints about this on the WordPress.com Twitter account as well. It happens on both WordPress.com and Core.

**Comment by KokkieH** [comment]
> This is a 'Spotify' problem as their server is not responding via the oEmbed scripts

@bph I was afraid of that. Thanks for confirming, and for following up with them :)

**Comment by bph** [comment]
Testing it this afternoon it seems to be working again. 
![Screen Shot 2020-08-24 at 3 59 38 PM](https://user-images.githubusercontent.com/39980/91090312-dc72a980-e622-11ea-8fb2-d4a7770ec05d.png)
