### ISSUE TITLE
Site Editor doesn't show all template parts

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#24733]
**Describe the bug**
I followed the tutorial [Creating a block-based theme](https://developer.wordpress.org/block-editor/tutorials/block-based-themes/) (ref. #23698) and prepared `block-templates/index.html` that includes following lines:

```jsx
<!-- wp:template-part {"slug":"header","theme":"myfirsttheme"} /-->

<!-- wp:template-part {"slug":"footer","theme":"myfirsttheme"} /-->
```

But, Site Editor's template menu doesn't display `footer`. though `header` is displayed.

![image](https://user-images.githubusercontent.com/8876600/90945610-ddf47400-e460-11ea-8283-a5f6c576ea3c.png)

[In the  tutorial page](https://developer.wordpress.org/block-editor/tutorials/block-based-themes/block-based-themes-2-adding-blocks/), both template part are displayed under the index.

**To reproduce**
1. Follow Tutorial "Creating a block-based theme"
    [https://developer.wordpress.org/block-editor/tutorials/block-based-themes/](https://developer.wordpress.org/block-editor/tutorials/block-based-themes/)
2. Activate this theme from Appearance - Theme
2. Turn off Demo Template of FSE from Gutenberg - Experimental menu
3. Open Site Editor, and click Template menu in Toolbar.

**Expected behavior**
`footer` template parts also should be displayed.

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Gutenberg 8.8

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (Mojave)
 - Browser Chrome 
 - Version 84.0.4147.135

**Comment by aristath** [comment]
Just a note, could be relevant or not. I had the same issue earlier today, the WIP PR in https://github.com/WordPress/gutenberg/pull/24720 however fixed it for me. So I suppose there's a chance this could be related to the current meta query we're using... (or it could just be random that it got fixed on my end with that PR)

**Comment by atachibana** [comment]
@aristath 

Thank you the comment.
I'll retest this issue after merging of your fix.

**Comment by annezazu** [comment]
@atachibana I am going to close this out since the PR mentioned about has been merged and we haven't heard back from you. Feel free to reopen if needed upon retesting!
