### ISSUE TITLE
TextControl: label not connecting to input if props contains an id

### ISSUE THREAD

**Issue by truongwp** [WordPress/gutenberg#24749]
**Describe the bug**
If I passed an `id` to `TextControl`, the `<input>` tag uses that id but the `<label>` tag not. It makes the input is not focused when I click to the label.

**To reproduce**
Use this component in an app:

```
<TextControl
	id="my-custom-id"
	label="Test title"
/>
```

**Expected behavior**
Both the id of input and label should be `my-custom-id`.

**Solutions**
Add a prop for the label `for` or check if props contains an id, use that id for the label.

**Comment by talldan** [comment]
@truongwp From what I gather, `id` is not a supported prop. The component generates a unique `id` for you, so it doesn't have to be supplied as a prop.

Having said that, it does seem like a relatively simple change, but I think it should be done across all the `Control` components in `@wordpress/components` to be consistent.

**Comment by truongwp** [comment]
@talldan Sometimes I need to pass my own `id` so it will be great if we can improve this. Currently, I must create the similar WordPress components to achieve my need.

**Comment by andrewhayward** [comment]
I'd like to work on this, I'll be opening a PR soon // cc @ciampo
