### ISSUE TITLE
Change block type or style label

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#24746]
Hi, Just a little suggestion:

<img width="425" alt="label" src="https://user-images.githubusercontent.com/1785489/90975971-50388780-e539-11ea-9ae9-7bc3ca79f579.png">

This label is still "change block type or style"  but styles have moved to the right panel since a few version.

We should change string for "change block type" only. What do you think?

**Comment by maximebj** [comment]
Nevermind. Styles are still displayed for blocks like images

**Comment by ntsekouras** [comment]
> This label is still "change block type or style" but styles have moved to the right panel since a few version.

Actually they haven't been removed. It's just a generic message if you have selected only one block. It could be enhanced though to also check if there are available styles to make the message more specific.

Thanks for taking the time though to look into it 👍
