### ISSUE TITLE
markdown: # + space for H1 too?

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#24747]
In prior versions of WordPress, Heading blocks only showed H2, H3, H4 but it changed in WP 5.5

In markdown, it's impossible to fire a H1 with # + Space. It only works with 2 "#'. 
Should we had # + space to get an H1 too? 

Maybe there was a reason to not implement it. But I guess it was to limite H1 use in document. 
More and more themes add the feature to hide the page title, so we can use our own H1 wherever we want.

**Comment by getdave** [comment]
I tested this on WP 5.5.1 and was able to replicate. All the heading levels work except #1. To replicate:

* Use a site with WP 5.5.X
* Create a new Post.
* ✅ In the main post body content type `## Hello` - you will see this converted into a heading block with `h2` level.
* ✅ In the main post body content type `### Hello` - you will see this converted into a heading block with `h3` level.
* ❌ In the main post body content type `# Hello` - you will see this is _not_ converted into a heading block with `h1` level. Instead the raw text remains.

**Comment by aristath** [comment]
Created a PR for this in #25075
