### ISSUE TITLE
Block Directory: Explore linking to the block directory when a block is found in the content but now is not installed.

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#24759]
Currently, when in the content of post we find a block that is not installed, we don't provide a good fallback and just have a generic validation error.

I guess with the block directory we may search for a block and allow the user to install that block again.

**Comment by mcsf** [comment]
I believe this in the plans for @StevenDufresne and @tellyworth. No? Worth a link from #23378?

**Comment by ryelle** [comment]
There's this work in progress to allow installation from the missing block warning: https://github.com/WordPress/gutenberg/pull/22631#issuecomment-680296844 

<img width="645" alt="90553542-c744d900-e151-11ea-8a09-290449c21536" src="https://user-images.githubusercontent.com/541093/91233615-9b03fc00-e6ff-11ea-9332-372ec378865f.png">
