### ISSUE TITLE
Searching for Picture should insert an Image Block

### ISSUE THREAD

**Issue by dd32** [WordPress/gutenberg#24754]
**Describe the bug**
Attempting to insert a picture block causes the image block not to be matched.

**To reproduce**
1. Go to the editor
2. Attempt to insert a picture block
3. Watch it perform a block search

**Expected behavior**
The Image block should be suggested

**Screenshots**
<img width="353" alt="Screen Shot 2020-08-24 at 5 14 04 pm" src="https://user-images.githubusercontent.com/767313/91014714-3c6e4d80-e62d-11ea-9b28-5bc44c25765c.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha-48842
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default block editor
- If the Gutenberg plugin is installed, which version is it? N/A

**Comment by ntsekouras** [comment]
Thanks @dd32 for proposing this enhancement!
