### ISSUE TITLE
Allow turning off validation of HTML BLock

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#24752]
What is the point of a custom HTML block that forcefully overrides everything i do?
Open a tag without closing it? HTML gets straight up stripped out
Create an HTML attribute without a value? ="" gets added
Have a shortcode inside an HTML attribute? not only does it not execute, but the code gets completely mangled in the process
Use a symbol? HTML entities
Use various combinations of square brackets and angle brackets? Good luck cleaning up the mess afterwards

The most nonsensical part is, if you just write the code and hit update, it works, perfectly
It only gets destroyed when you return to the editor to make changes

Either stop this entirely, give an option to stop this entirely, or at least document the parsing and validation process so I don't spend 3 weeks designing a shortcode just to find out that I can't use it.

Here's a use case I want. Wrap a paragraph in the microdata for FAQ. No, i don't want to make a Gutenberg block for this, why should I have to do more complicated code for something so simple?
![image](https://user-images.githubusercontent.com/37098565/90989881-d620f680-e56a-11ea-83da-6fc25c3380b5.png)

This code always errors, and attempt block recovery totally wrecks it. Notice the itemscope="". Also notice the $amp;. This is not what I want when I enter "custom HTML". Custom HTML should give full control to the person using it. Or at least wordpress should have an option to switch between secure and full control modes.
![image](https://user-images.githubusercontent.com/37098565/90989920-17190b00-e56b-11ea-88f7-af6ac649a4ee.png)

**Comment by talldan** [comment]
I do wonder if disabling it might have some security implications, but I don't for sure the scope of the validation that happens on the HTML block.

I think it has been identified on another couple of issues that the validation is not clear at all and could be improved, but I don't have links to hand.

**Comment by joshm33333** [comment]
Honestly, even if the WordPress documentation covered this more clearly I'd be happy. It's just so discouraging when you make a big plan for how you'll build your website, just to find out there are seemingly random security sanitizations happening that make your plan impossible. I get that every sanitization has a good reason, but without proper documentation as to what and why those are, I just end up finding a potentially more dangerous work around.

**Comment by joshm33333** [comment]
@talldan Here's a question that would really help me if you could answer it.. Will more sanitization be introduced into Gutenberg going forward?

I'm a little stressed because yesterday I had many html blocks with <style>some css</style> all over multiple websites, because I thought I could trust them to work, and then suddenly I logged in and found the <style> and </style> had been removed from every one of them across multiple sites. I had to go back and add them manually, but now I'm afraid it will happen again.

**Comment by mtias** [comment]
Related #10889

**Comment by mcsf** [comment]
> I'm a little stressed because yesterday I had many html blocks with <style>some css</style> all over multiple websites, because I thought I could trust them to work, and then suddenly I logged in and found the <style> and </style> had been removed from every one of them across multiple sites. I had to go back and add them manually, but now I'm afraid it will happen again.

This appears to be a different issue. Client-side sanitisation in the HTML block is indeed likely to cause things like force-assigning `=""` to value-less attributes (something we ought to fix), but filtering based on the tag name smells like something KSES would do on the server depending on the current user's capabilities.

You can verify this as follows:

* Using the Custom HTML block, add a `<style>` node with CSS in it.
* Toggle between Preview and HTML and verify that the content is preserved (i.e. the client itself doesn't touch `style`).
* Save the post. As a bonus, examine the save request in the browser's Network panel. What does the response look like? It _should_ be fine if you're logged in as admin, but not otherwise.

Is there any chance that 1) you added `<style>` as a non-admin user, or 2) that you did add that markup as an admin but in the meantime a different user, with no admin privileges, edited the post?

**Comment by mcsf** [comment]
@joshm33333: is this issue relevant? If so, can you provide feedback per https://github.com/WordPress/gutenberg/issues/24752#issuecomment-686406436?

**Comment by joshm33333** [comment]
> @joshm33333: is this issue relevant? If so, can you provide feedback per [#24752 (comment)](https://github.com/WordPress/gutenberg/issues/24752#issuecomment-686406436)?

I've continued to work with Gutenberg since I started this issue, and I haven't seen the style tag removed since then. Seems to be safe to use. Perhaps when you use unsafe code in the HTML block it triggers a  more aggressive sanitization? I know for a fact I saw those styles tags stripped at some point but I'm unable to reproduce it.

I don't necessarily think anything is broken, it's probably just a lack of understanding of what sanitization happens to HTML blocks at each stage.

**Comment by mcsf** [comment]
> I've continued to work with Gutenberg since I started this issue, and I haven't seen the style tag removed since then. Seems to be safe to use. Perhaps when you use unsafe code in the HTML block it triggers a more aggressive sanitization? I know for a fact I saw those styles tags stripped at some point but I'm unable to reproduce it.
> 
> I don't necessarily think anything is broken, it's probably just a lack of understanding of what sanitization happens to HTML blocks at each stage.

Thanks for the feedback. I think we can close this issue. If something new comes up, we'll address it.
