### ISSUE TITLE
Number fields are not intuitive

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#24769]
Just a user here, and a developer of my own projects, with a serious issue with the number fields work. take for example the spacer. by default its 20, let say i want it to be 100.

the issue is that you can at any point have the number be less than 20, so here's the chain of events i generally see developers go through, and lay people just give up and ask for help.

click at the end, backspace, resets to 20
select all, type 1, resets to 20 again!
select just the 2, overwrite with a 1, resets to 20

click BETWEEN the 2 and the 0, type 1, type 0, then delete the 2... it works

this is a horrible way to handle a number field, and its unfortunate that the gutenberg project seems to driven to reinvent the wheel in so many areas. the number field is tried and true, 30 years of expert computer scientists working together to create a universal standard that works on all devices.

seriously, just say "hey that number isnt allowed" AFTER the user is finished typing

oh and while im at it, why the hell cant i make a spacer less than 20?

**Comment by talldan** [comment]
@joshm33333 Please could you be careful of your tone and language when creating issues.

This is a bug, it isn't working as intended. This was already reported, #24460, so I'll close your issue as a duplicate.
