### ISSUE TITLE
UnsavedChangesWarning: Turn into functional component, add JSDoc Typings

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#24767]
Carrying over from https://github.com/WordPress/gutenberg/pull/24719#discussion_r475496258. The `UnsavedChangesWarning` component should be turned into a functional component, and it'd be great if we could also add JSDoc typings while we're at it.

cc/ @david-szabo97

**Comment by david-szabo97** [comment]
👍 Working on it
