### ISSUE TITLE
Gutenberg Usability testing form page/post confusion

### ISSUE THREAD

**Issue by lupoair** [WordPress/gutenberg#2476]
## Issue Overview
Concerning the Gutenberg Usability testing Google form - 2nd page asks you in the 1st question to: "Add a new headline at the top of page [...]". This is confusing especially to unexperienced users/testers. Because if you got a fresh install of WP and installed Gutenberg it will only give you the option to add a new post and not a page. So it is really just about the wording but necessary since page/post vocabulary is already confusing enough. (Issue opend as per request by tammie @wordcamp brighton)

## Steps to Reproduce (for bugs)

1. Having a blank WP install with Gutenberg plugin
2. Opening the test form as described on https://make.wordpress.org/test/handbook/call-for-testing/gutenberg-testing/
3. 2nd page of Google form 1st question

## Expected Behavior

Should have said post.

## Current Behavior

Asks to open add title to page.

## Possible Solution

Wording switch to post.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by annaephox** [comment]
Can I suggest that the question is reworded as follows:

Add a new headline ~~at the top of page~~ titled “The Life of Einstein”. How easy would you rate that task? (please rate from 1-5, with 5 being excellent)

**Comment by karmatosed** [comment]
Iterated 👍
