### ISSUE TITLE
How to change the default color palette for __experimentalColor?

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#24765]
Since colors are not defined through attributes `add_theme_support` for `editor-color-pallete` is not working anymore.
Is there a new way to define the color palette or am I missing something?

**Comment by aristath** [comment]
@bfiessinger I'm afraid I don't understand... Does the `editor-color-palette` theme-support not work for you?

**Comment by bfiessinger** [comment]
unfortunately not. It worked before as long as I knew. But yesterday I checked the palettes and it was all back to default.
`editor-color-palette` is called as it should in `after_setup_theme`.

**Comment by aristath** [comment]
Seems to be working fine on my end... To test you can just enable the twentytwenty theme and check the editor palette.
If things still don't work with the twentytwenty theme, perhaps there's a plugin enabled that bypasses the palette?
