### ISSUE TITLE
Searching for Read More should insert the More block

### ISSUE THREAD

**Issue by dd32** [WordPress/gutenberg#24779]
**Describe the bug**
Attempting to insert the More block (whose default text is 'Read More' and often called the Read More link) should insert the More block.

**To reproduce**
1. Go to the editor
2. Start typing `/read` watch
3. Watch it not match anything

**Expected behavior**
The More block should be suggested

**Screenshots**
<img width="625" alt="Screen Shot 2020-08-25 at 6 09 38 pm" src="https://user-images.githubusercontent.com/767313/91149396-5c217680-e6fe-11ea-9c28-52964ea4b235.png">
<img width="680" alt="Screen Shot 2020-08-25 at 6 11 02 pm" src="https://user-images.githubusercontent.com/767313/91149411-617ec100-e6fe-11ea-9eb3-5f995c08a03b.png">
<img width="649" alt="Screen Shot 2020-08-25 at 6 09 57 pm" src="https://user-images.githubusercontent.com/767313/91149430-66437500-e6fe-11ea-94a9-53cc59f58d92.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha-48842
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default block editor
- If the Gutenberg plugin is installed, which version is it? N/A

**Comment by aristath** [comment]
PR in #24794 adds the keyword to the `more` block.
