### ISSUE TITLE
Navigation Component: Expose activeLevel prop

### ISSUE THREAD

**Issue by psealock** [WordPress/gutenberg#24775]
As suggested [here](https://github.com/WordPress/gutenberg/pull/24704#discussion_r475986548), we'd like to allow outside manipulation of internal state. Exposing a prop to is a good way to accomplish this.

Trac ticket: https://core.trac.wordpress.org/ticket/47012

**Comment by Copons** [comment]
#25057 exposes both the active item and menu (previously called level) for outside manipulation of internal state.
