### ISSUE TITLE
List selecting text snippet and hit enter doesn't work - no new list item

### ISSUE THREAD

**Issue by lupoair** [WordPress/gutenberg#2477]
## Issue Overview
Imagine copying text into a newly generated list (ul, ol) first item and now you'd like to mark a snippet not needed and hit enter to delete highlighted text and generate a new list item (standard behaviour) doesn't work.

![2017-08-20 12 33 33](https://user-images.githubusercontent.com/1473634/29494471-ed55c0cc-85a2-11e7-9fc8-117c73490828.gif)

## Steps to Reproduce (for bugs)

1. Create a list
2. Enter text 
3. Mark a few chars/words in between beginning and end of list item
4. Hit enter

Tested on mac os 10.11.6 and firefox 54.0.1. Freshly installed WP 4.8.1 and Gutenberg 0.9.0.

Reported from WordCamp Brighton.

## Expected Behavior

Regular editors would delete highlighted/select chars/words and create the next line/list item.

## Current Behavior

Gutenberg for now just deletes the selected chars/words.

## Possible Solution

Hitting enter in a list item should generate a new list item. Also if marked/selected text.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by EphoxJames** [comment]
This seems to be a problem in standard TinyMCE not just Gutenberg.

**Comment by annaephox** [comment]
cc @spocke

**Comment by lupoair** [comment]
Yes, that's also not working in TinyMCE.

**Comment by spocke** [comment]
This has been fixed and is part of the 4.6.6 release.
