### ISSUE TITLE
Inline Editable is not working

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2480]
![image](https://user-images.githubusercontent.com/548849/29496705-9241472a-85d8-11e7-9da1-0506a50ba6e0.png)

At least in captions formatting is not working.

**Comment by iseulde** [comment]
I'll bisect

**Comment by iseulde** [comment]
Apparently this broke it: 8a2f17038c751db95991251c5bd09393725641e7. 🤔
Cc @youknowriad.
