### ISSUE TITLE
Navigation screen: "Move to" in List View does nothing

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24807]
Split out from #24760.

We should remove the "Move to" button or add functionality to it.

![](https://user-images.githubusercontent.com/107534/91038278-2ce20b00-e613-11ea-85ac-c78ea98a0a6c.png)

**Comment by talldan** [comment]
There are some options to make this work. 

Once https://github.com/WordPress/gutenberg/pull/23952 is merged, this can use the same indicator as drag and drop to highlight the move position.
