### ISSUE TITLE
Blog Posts Block: Categories appear in Alphabetical Order, ignoring if parent category

### ISSUE THREAD

**Issue by kathleenjross** [WordPress/gutenberg#24801]
If the blog post block is set to show a category, it will pick the first category assigned to the post, in alphabetical order. However, this ignores parent and sub categories. In a recent chat, a user pointed out that they would prefer the parent category to be the category showing, which makes tracks with how users employ parent and sub categories.

For example, you can see in the link that two of the posts have the parent category "North America", and then one has a subcategory Mexico, the other has a subcategory United States:  https://d.pr/i/wmK4dT

You can see how "Mexico" appears as the category for the post (as it comes before North America), but United States is beaten out  by North America. It would be good for this to be consistent for users.

**Expected behavior**
It is expected that a parent category would take precedent.

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?: Default

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: current

**Comment by annezazu** [comment]
@kathleenjross thanks for sharing this! Can you quickly clarify the exact block you are using? For example, is this the latest post block? Or are you using WordPress.com and using [their Blog Post Block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/)?

**Comment by talldan** [comment]
Closing due to the lack of response.
