### ISSUE TITLE
Navigation screen: Clicking outside the Navigation block should close any open submenus

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24808]
Split out from https://github.com/WordPress/gutenberg/issues/24760.

When a submenu is open, clicking outside the Navigation block should close the submenu. This can be done by selecting the Navigation block.

![click-outside](https://user-images.githubusercontent.com/612155/91245817-be778700-e791-11ea-8f2b-a895aa9e475e.gif)

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/issues/24875 may make this unnecessary.

**Comment by talldan** [comment]
Duplicate of #22626
