### ISSUE TITLE
Navigation screen: 'Save navigation' is not centred properly

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24810]
Split out from https://github.com/WordPress/gutenberg/issues/24760.

In the experimental Navigation screen, the 'Save navigation' button's text is not centred properly.

<img width="1263" alt="not-centred" src="https://user-images.githubusercontent.com/612155/91246514-5a55c280-e793-11ea-8b33-f3955f8eb1ef.png">

**Comment by sbappan** [comment]
Hi. Can I work on this issue?

**Comment by noisysocks** [comment]
Go for it @sbappan! Let me know if you need any help. I'm `@noisysocks` on [WordPress Slack](https://make.wordpress.org/chat/).

**Comment by sbappan** [comment]
Thank you very much, @noisysocks!

**Comment by draganescu** [comment]
Hey @sbappan :) any progress on centering the button's label?

**Comment by sbappan** [comment]
I should be making a PR by today @draganescu.

**Comment by draganescu** [comment]
From my testing as well this also seems to have been fixed.
