### ISSUE TITLE
 Using "disable-custom-colors" does not remove all of the Color Settings UI

### ISSUE THREAD

**Issue by hrkhal** [WordPress/gutenberg#24812]
**Describe the bug**
In WP 5.5, using `add_theme_support( 'disable-custom-colors' );` to remove custom colour support now leaves an empty accordion in the inspector controls.

This is a regression and was not the case in WP 4.5.2.

**To reproduce**
1. Add  `add_theme_support( 'disable-custom-colors' );` into your theme
2. Start a new post
3. Insert a paragraph or heading block
4. Note the empty accordion title `Color settings` in the inspector controls.

**Expected behavior**
Complete removal of the colour settings UI.

**Screenshots**
<img width="392" alt="Screenshot 2020-08-26 at 08 25 01" src="https://user-images.githubusercontent.com/7547332/91274108-1f916180-e776-11ea-8724-80911975b29f.png">

**Editor version (please complete the following information):**
- WordPress version: **5.5**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **default**

**Comment by mtias** [comment]
cc @jorgefilipecosta

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I'm not able to reproduce that error using the newest version of the Gutenberg plugin (version 9.8.0) at https://wordpress.org/plugins/gutenberg/ 
The color menu does appear as expected with `add_theme_support( 'disable-custom-colors' );`
The hook only disables the ability for custom colors to be made;[ the default colors in the color palette are still provided. ](https://github.com/WordPress/gutenberg/blob/4b072556b8839c00921d2bd84b7f8960acaa03ce/docs/designers-developers/developers/themes/theme-support.md#disabling-custom-colors-in-block-color-palettes)

If you are still able to reproduce this, please reopen this issue.
