### ISSUE TITLE
Post Settings Sidebar Obscures Post in iOS Safari Portrait Mode

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#2481]
On an iPad, when editing in landscape and then switching to portrait, the Post Settings Sidebar takes over the entire screen, hiding the post editor. It took a moment to realize what had happened. I tried to scroll up and down the page, thinking maybe it had dropped below the editor like it does in the current editor. 

In the current editor, when you switch from landscape to portrait, the sidebar widgets (Publish, Format, Categories, Tags, etc) fall below the editor pane, ensuring that the edit space is still the focal point. 

In Gutenberg, when switching to portrait, I think it would make sense for the post settings sidebar to automatically close, rather than taking over the screen. 

In Gutenberg: 

![2017-08-20_20-01-29](https://user-images.githubusercontent.com/480667/29499604-71363d82-85e3-11e7-8725-3e61a4281780.gif)

vs. 

Current Editor: 

![2017-08-20_20-10-39](https://user-images.githubusercontent.com/480667/29499626-c0a6479a-85e3-11e7-8f9c-9e141fbd65ee.gif)

Plugin Version 0.9

**Comment by karmatosed** [comment]
Closing as discussed in https://github.com/WordPress/gutenberg/issues/1535
