### ISSUE TITLE
Editor: Using "orderby: rand" in getEntityRecords for CPT does not work

### ISSUE THREAD

**Issue by AdrianChudzynski** [WordPress/gutenberg#24816]
**Describe the bug**
Wen using a custom post type to get posts via (`wp.data.select('core').getEntityRecords('postType', 'CPT', {per_page: 5, orderby: 'rand' })`) in a random order, it wont work.

**To reproduce**
1. Make sure to have at least one post in a CPT
2. Open up the editor
3. Open up the console in the DevTool (F12)
4. Type in the console the following: `wp.data.select('core').getEntityRecords('postType', '[Inser CPT here]', {per_page: 5, orderby: 'rand' })`

**Expected behavior**
An array output of posts of the custom post type, in a random order.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/39830969/91291792-dbae5480-e795-11ea-8d56-2f1cc1de95b9.png)

**Editor version (please complete the following information):**
- WordPress version: **5.5**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **"gutenberg plugin"**
- If the Gutenberg plugin is installed, which version is it? **8.8.0**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  84.0.4147.135

**Comment by youknowriad** [comment]
Hi there! the "rand" orderBy argument is not supported by the WordPress REST API, please consider opening a trac ticket instead, thank you. 

https://core.trac.wordpress.org/newticket
