### ISSUE TITLE
A way to opt out of block style previews

### ISSUE THREAD

**Issue by AlpacaNox** [WordPress/gutenberg#24826]
**Is your feature request related to a problem? Please describe.**
Block styles update after every change made in the editor which sometimes makes the content in TinyMCE disappear. The previews don't work really well if the block has a lot of content which leads to preview having a big height. In my opinion the feature is too heavy on the editor for a small thing it tries to accomplish. I noticed that I orient mostly based on the title, not on the preview.

**Describe the solution you'd like**
I like the idea of block styles but I think preview doesn't really have to be that sophisticated. It can be just a list, or something similar to the way block directory displayed (icon + text). It would be really nice to be able to opt out with theme support command or something similar.

**Describe alternatives you've considered**
Adding classes manually.

**Comment by youknowriad** [comment]
Hi There! thanks for opening the issue.

There's some working going on in #24493 to limit the height of the previews in these situations (see #24484)
I'm tempted to close this in favor of that issue.

If you still want to remove the previews entirely, you can potentially target it with CSS?

**Comment by AlpacaNox** [comment]
CSS solution is great, that solved everything. Thanks a lot!
Adding this rule removed the previews:
```
.block-editor-block-styles__item-preview {
	display: none !important;	
}
```
