### ISSUE TITLE
Widgets editor: Is it "Block Areas" or "Widgets"?

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24838]
In some places we call the new block-based widgets editor screen _Widgets_ and in other places we call it _Block Areas_. We ought to settle on one name so as to avoid user confusion.

<img width="1552" alt="Screen Shot 2020-08-27 at 11 15 40" src="https://user-images.githubusercontent.com/612155/91372394-e381fd80-e856-11ea-8296-f868ca051b78.png">

**Comment by aristath** [comment]
"Block Areas" seems more future-proof than "widgets" considering widgets is basically legacy and we're moving away from them... Everything is a block.

**Comment by ZebulanStanphill** [comment]
Although "Block Areas" is a bit vague, I can't think of a more descriptive title, and "Widgets" is even more vague, and far less accurate of description, in my opinion. Using the "Block Areas" terminology could also help avoid confusing with the "Widgets" category in the inserter, which does not directly relate to this screen. So I'd definitely prefer the "block area" terminology.

**Comment by draganescu** [comment]
In the Widget editor I would use the same terminology that the current Widgets screen uses: "Widget Areas". Also I believe block areas are a feature which means more than placing blocks in the widget area, and are unrelated to widgets.

My opinion is to keep as close as we can with the copy, headings and concepts from the old editor: Widgets / Widget Areas / Sidebars

**Comment by mapk** [comment]
A lot of that UI should be changing, @noisysocks. I remember getting feedback on "Block areas" not being very adequate. This page is really used in relation to older themes that don't yet support block-based structures and still rely on widget areas. So with that in mind, keeping "Widgets" is the way to go. 

The UI should evolve into something like below.

1. "Widgets" is used in the topbar as a clear h1 heading for this page.
2. This helps communicate to users that this page is still used for widgets when it ultimately replaces that particular page.
3. The Inspector now only shows the widget area that is focused. In the example below, the "Sidebar".

![area 1](https://user-images.githubusercontent.com/617986/92500762-7ce3d480-f1b2-11ea-994e-f51aee8c2c4d.png)

**Comment by draganescu** [comment]
Should we close this then?

**Comment by draganescu** [comment]
Hey @mapk :) should we do anything here? Thank you!

**Comment by mapk** [comment]
As long as we're moving toward the desired UI, I don't think keeping this open is necessary. Unless, @noisysocks would like to keep it open until this has been implemented.

**Comment by annezazu** [comment]
Chatted with @noisysocks briefly about this and have moved this to needs dev. As Rob said to me, let’s not close this issue until this update is made.
