### ISSUE TITLE
Navigation: Add new block-based screen to Customizer

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24844]
Should we replace Appearance → Customizer → Menus with a slimmed down version of the Navigation editor?

This would match what the new block-based Widgets editor does.

| | WP Admin | Customizer |
| - | - | - |
| Widgets | ![Screen Shot 2020-08-27 at 15 55 59](https://user-images.githubusercontent.com/612155/91396369-8b5ef180-e87e-11ea-815e-b0e25edc07b7.png) | ![Screen Shot 2020-08-27 at 15 56 45](https://user-images.githubusercontent.com/612155/91396430-8f8b0f00-e87e-11ea-86de-6e8b9ad00e76.png) |
| Navigation |  ![Screen Shot 2020-08-27 at 16 02 38](https://user-images.githubusercontent.com/612155/91397048-be08ea00-e87e-11ea-8073-c6db92329d44.png) | What goes here? |

**Comment by shaunandrews** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/191598/107567358-96e77000-6bb3-11eb-81c4-9c83e29f18cc.png">

I think it could make sense, but its unclear to me if this is a priority.

**Comment by celloexpressions** [comment]
If #26012 goes in the direction of consolidating widgets into the customizer, we should strongly consider doing the same for menus. If it's a separate interface, we should make sure that menu management in the customizer and elsewhere is cross compatible.

The current menu management in the customizer works well in the sidebar. The ability to draft pages while building out a menu is extremely powerful. And we should probably maintain a slide-out UI for adding menu items.

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Editor project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. At the moment we have the navigation block, if this work is picked back up, issues can be revisited and reopened as needed.
