### ISSUE TITLE
"0 active installations" should say "Less than 10 active installations"

### ISSUE THREAD

**Issue by dd32** [WordPress/gutenberg#24842]
**Describe the bug**
Currently the Block Installer only has a plural `%s active installation(s)` where as [WordPress has 3 distinct states](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin-install.php#L685) for plugins:
 - 0 = Fewer than 10
 - over 10 = `%s active installation(s)`
 - over 1 million = `%d+ million active installation(s)`

https://github.com/WordPress/gutenberg/blob/799e3550f5f4c57a5f9475dffde2bceb70b04aa3/packages/block-directory/src/components/downloadable-block-info/index.js#L24-L32

Note: WordPress.org says "Fewer than" rather than "Less than".

**To reproduce**
1. Search for a block that's brand new and installed nowhere (or on less than 10 sites).
 2. Admire "0 active installations"

**Expected behavior**
It should state something like "Less than 10 active installations"

**Screenshots**
![searchResults](https://user-images.githubusercontent.com/767313/91383258-0cae8800-e86f-11ea-87d6-9107199d0395.png)
(Uh, the Emoji's work normally.. just don't work in the browser that screenshot came from..)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  default

**Comment by kartecianos** [comment]
Hi I would like to work on this issue, is it still open?

I saw vcanales pull request but it seems to have a problem with values 1-9 because it seems that it should be printed 'Fewer than 10'

**Comment by ryelle** [comment]
This is fixed with https://github.com/WordPress/gutenberg/pull/25084

@kartecianos The API rounds to 10, so it should never return 1-9. Are you seeing any block plugins that return a value in 1-9?
