### ISSUE TITLE
Video Embeds set to aligh left/right disappear in the editor 

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#24845]
**Describe the bug**
Reported in https://core.trac.wordpress.org/ticket/51053

**To reproduce**
1. Using the twentytwenty theme add a video in the editor
2. Align the block to the left
3. Save the post
4. Reload the page and watch as the video disappears.

**Editor version:**
- WordPress version: 5.5
- Both using Gutenberg as a plugin and when not installed

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 80.0

**Comment by rebeccahum** [comment]
Is this still occurring in 5.5.1? Attempted to reproduce on Chrome and couldn't.
