### ISSUE TITLE
Gutenberg Permalink Block

### ISSUE THREAD

**Issue by jonhopstra** [WordPress/gutenberg#24856]
Dear Team,

Since the latest 5.5. version for WordPress the **Permalink block** that was always **above the Title bloc**k in Gutenberg has been removed.

It may seem nice and clean but I and my students have some problems with this and a lot of WP user I know so I decided to make a post about it in the hope it would be changed back in the future update.

The previous version to 5.5. had the Permalink block when you clicked with the mouse above the Title block, this was really good as no one would forget to check the URL of the post. As you may know the URL of the post is pretty important when it comes to SEO and Google.

Once the URL is set and a user presses Publish the web-spiders and Google-bot will index that page or post but if you change the URL later for the same post it may take weeks before this is corrected in the Google index. You can see this happening in Search Console.

We now have the Permalink in Gutenberg only in the side panel options. You would think that is enough but because these document options are out of view the users need to remember to always check the words used in the post URL before publishing.

Also, it is hidden by default and needs to be expanded. This might give users the impression that the post Permalink URL is not of that importance but as you may know it is pretty vital to have this set up correct when publishing a post for the first time.

Also, when the user has a domain that is pretty long this document options on the right side of the Gutenberg editor cannot be expanded so there is no easy way to see the complete URL for the post before publishing.

I really hope that the team will consider **adding the Permalink block above the Title block** back into Gutenberg so that the people that I train to use WordPress keep a consistent workflow and especially do not forget to check the Post URL and keywords in the Slug before they press publish after the post is written for the first time.

Thanks a lot!

**Comment by mtias** [comment]
Hello there. Thanks for the feedback! Check out issue #20877, the permalink placement is a primary concern of that design. Agreed it's a bit too buried in the sidebar at the moment.

We should likely include the permalink prominently in the pre-publish panel as well, so that before publishing anything there's a reminder for it:

![image](https://user-images.githubusercontent.com/548849/91560464-308ad000-e93a-11ea-85c6-b514a74f8fc4.png)
