### ISSUE TITLE
Sidebars API - XSS or not XSS?

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#24863]
Let's talk about the experimental `/__experimental/sidebars` API endpoint.

As initially discovered in an [unrelated issue](https://github.com/WordPress/gutenberg/pull/24785#issuecomment-680852071), it is possible to send a POST request like:

```php
$request = new WP_REST_Request( 'POST', '/__experimental/sidebars/sidebar-1' );
$request->set_body_params(
	array(
		'widgets' => array(
			array(
				'id'           => 'text-1',
				'settings'     => array(
					'text' => '<script>alert(1)</script>',
				),
			),
		),
	)
);
```

And store a script that will be executed when the widget is rendered.

Initially I considered it to be a vulnerability, but then I tested `widgets.php` and discovered it exhibits the exact same behavior. That's perhaps unsurprising, considering that experimental endpoint reuses the exact same code:

```php
	$_POST[ $field ][ $number ] = wp_slash( $input_widget['settings'] );
	call_user_func( $update_control['callback'] );
```

The endpoint access is restricted to administrators and editors who, by design, are allowed to use custom scripts. Therefore it seems to me like it's not a bug, it's a feature. What do you think @draganescu @noisysocks @TimothyBJacobs ?

**Comment by aristath** [comment]
> The endpoint access is restricted to administrators and authors who, by design, are allowed to use custom scripts. Therefore it seems to me like it's not a bug, it's a feature

I'd have to agree with that assessment... The people that can use this are the people than should be able to use it.

**Comment by TimothyBJacobs** [comment]
Is this the built in text widget?

**Comment by adamziel** [comment]
@TimothyBJacobs it is

**Comment by draganescu** [comment]
Looks like a feature :)

**Comment by adamziel** [comment]
Before concluding this issue I will confirm whether or not `unfiltered_html` is in power here.

**Comment by adamziel** [comment]
It does, we're good to close this issue. I prepared some related unit tests in https://github.com/WordPress/gutenberg/pull/24886
