### ISSUE TITLE
[Widgets editor] Preload everything

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#24869]
In #24855 the widgets are preloaded on the editor. If the data travels slowly we get a blank screen for a while. Before this PR we saw the collapsed widget areas and by the time we clicked one the data was there. Now this is not the case anymore.

I think we should add a way to let the users know we're doing something.

<img width="1099" alt="Screenshot 2020-08-27 at 19 46 49" src="https://user-images.githubusercontent.com/107534/91470978-156a8280-e89e-11ea-946e-a15bb6699f89.png">

**Comment by mtias** [comment]
We should avoid this state in the first place

**Comment by adamziel** [comment]
Agreed with @mtias. One way to avoid it would be to store the results of the initial XHR.
