### ISSUE TITLE
Navigation component should not require onClick

### ISSUE THREAD

**Issue by joshuatf** [WordPress/gutenberg#24877]
**Describe the bug**
When clicking a menu item with an `onClick` prop in `NavigationMenuItem`, an error occurs.

**To reproduce**
1. Clone and checkout this PR from the wc nav - https://github.com/woocommerce/navigation/pull/63
1. Click on a menu item.
1. Note the console error.

**Expected behavior**
Expected to be able to just use a `href` for menu items.

**Screenshots**
<img width="656" alt="Screen Shot 2020-08-27 at 5 34 01 PM" src="https://user-images.githubusercontent.com/10561050/91499317-e964f680-e8c9-11ea-8f44-b1825295baa8.png">

**Comment by Copons** [comment]
This doesn't happen with #25057 ✨
