### ISSUE TITLE
Line Spacing Option Missing in Default Paragraph Block!

### ISSUE THREAD

**Issue by undertaker001** [WordPress/gutenberg#24887]
**Describe the bug**
Line Spacing Option Missing after the Latest Gutenberg Update.
**To reproduce**
1. Go to Gutenbeg.'
2. Click on 'edit post'
3. Check paragraph block settings
4. No line spacing

**Expected behavior**
Their should be an option for line spacing.

**Editor version (please complete the following information):**
- WordPress version: [5.4.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [ "gutenberg plugin"]
- If the Gutenberg plugin is installed, which version is it? [ 8.8.0]

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Edge]
 - Version [86]

**Comment by aristath** [comment]
@undertaker001 line-height is currently opt-in by the theme.
You can read more about how to add it here: https://developer.wordpress.org/block-editor/developers/themes/theme-support/#supporting-custom-line-heights
Once you add that in your theme you should have line-height controls :+1:

**Comment by mtias** [comment]
Closing as this is currently the status quo. The defaults for themes are going to be revised as we consolidate the add theme supports in the theme.json configuration.
