### ISSUE TITLE
Raw Handling: Text with colon incorrectly interpreted as a link

### ISSUE THREAD

**Issue by thomashigginbotham** [WordPress/gutenberg#24895]
**Describe the bug**
When pasting over existing text, if the new text has a colon in it without first having a space character, Gutenberg will assume you are pasting a link and will open the link insertion dialog box.

**To reproduce**
1. Add some text to a paragraph block.
1. Copy the following text to your clipboard: Bug: This text is not a link
1. Select the text you added to the paragraph block.
1. Paste the text you copied.
1. Notice that you are prompted to insert a link.

**Expected behavior**
The text should paste without inserting it as a link.

**Screenshots**
![paste-text-link-bug](https://user-images.githubusercontent.com/1651691/91583006-9c5f3f80-e91e-11ea-9940-d26fed938bf3.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84

**Comment by kirilzh** [comment]
Seems like the problem is in 
https://github.com/WordPress/gutenberg/blob/a4e381b0346b59b101a09eabdab1cfb87726db54/packages/url/src/is-url.js#L16-L25
`new URL` doesn't throw. Maybe we can use [valid-url](https://www.npmjs.com/package/valid-url) dependency?

**Comment by kishanjasani** [comment]
@kirilzh there is an issue with `isURL`.

Is there we are using any packages for the check URL is valid or not? or maybe we can create an additional check here for validating URL.

**Comment by mrclay** [comment]
I suggest just returning FALSE if the successfully parsed URL pathname begins with whitespace. Or the scheme begins with a capital letter but is not all caps. Otherwise you get in the business of the big list of established URI schemes.

**Comment by mrclay** [comment]
I can submit a PR on branch 7.7.0 but the master branch fails in attempt to patch xcode (I'm on linux).

**Comment by talldan** [comment]
There was a similar fix here that it might be possible to take inspiration from - https://github.com/WordPress/gutenberg/pull/32663

The difference here is that this problem is pasting something that looks like a link over an existing text selection, whereas that other issue fixed a problem when highlighting text that looks like a link and selecting the link button.

**Comment by ndiego** [comment]
I have been able to reproduce this.

**Comment by R33D3M33R** [comment]
Hi, 

what a horrible "feature". When you select text and paste something, you want to replace it with the pasted content. You have a **button** to make a link ...

**Comment by annezazu** [comment]
Noting that I can replicate this with 6.3 RC 1.
