### ISSUE TITLE
Missing anchor when editing media

### ISSUE THREAD

**Issue by RKWO** [WordPress/gutenberg#24913]
**Describe the bug**
When you edit an image, the text for the anchor is missing.

**To reproduce**
Steps to reproduce the behaviour:
1. Go edit any media file
2. Click on flip horizontally
3. See error (missing anchor text)

**Expected behaviour**
Text is supposed to show.

**Screenshots**
https://ibb.co/9NvGh0C
https://ibb.co/R4tsFRN

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Classic editor
- If the Gutenberg plugin is installed, which version is it? Latest from 5.5

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Google Chrome
 - Version Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by youknowriad** [comment]
I believe you're raising a problem related to an issue in the Media Library Modal. is that right? If that's the case, please consider opening a Core trac ticket instead as this is not maintained here. Thanks.

http://core.trac.wordpress.org/

**Comment by talldan** [comment]
Closing as there hasn't been a reply.
