### ISSUE TITLE
Edit header toolbar Tools button

### ISSUE THREAD

**Issue by zourbuth** [WordPress/gutenberg#24917]
While using the code editor mode, the **Add block** button and **Block navigation** is completely disable,
but the **Tools** button is still enabled. I believe it has nothing to do with the code editor.

![code-editor-view](https://user-images.githubusercontent.com/451977/91662535-56b49980-eb0d-11ea-9103-ffbf41573dea.png)

**Comment by kishanjasani** [comment]
Thanks  @zourbuth. Yes, It should be disabled while the code editor mode is active.
