### ISSUE TITLE
block.json: set color property individually

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#24927]
The implicit block attributes for colors we declare through block.json follow this logic:

CSS Property | block.json (check presence of) | Style attribute (block serialization) | theme.json
--- | --- | --- | ---
`--wp--style--color--link` | `__experimentalColor.linkColor` | `style.color.link` | `styles.color.link`
`background` | `__experimentalColor.gradients` | `style.color.gradient` | `styles.color.gradient`
`background-color` | `__experimentalColor` | `style.color.background` | `styles.color.background`
`color` | `__experimentalColor` | `style.color.text` | `styles.color.text`

Text and background colors are coupled, although some blocks may not require them both at once.

**Comment by jorgefilipecosta** [comment]
Hi @nosolosw, the API's are experimental I guess we can simply change to have two separate properties __experimentalColor.color for color and __experimentalColor.background for "background-color" right?

**Comment by nosolosw** [comment]
I'd think we want to consolidate `__experimentalColors` with the same subkeys that they have in the style attribute and theme.json: link, gradient, background, text (updated issue description for clarity).

For context, a related PR where I tried to do this (but was held off due to other things) https://github.com/WordPress/gutenberg/pull/24320

**Comment by kishanjasani** [comment]
@jorgefilipecosta I am a little confused with the naming convention of these colors and some properties like `__experimentalColors`. Is it only for experimental and may deprecated in future releases? Thanks :slightly_smiling_face:

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta I am a little confused with the naming convention of these colors and some properties like __experimentalColors. Is it only for experimental purpose and may deprecated in future releases? Thanks 🙂

Hi @kishanjasani, it is experimental because we are still developing and improving it so its shape and name could change in the future.
