### ISSUE TITLE
Problem with InnerBlocks wrapped in <a> tag on save

### ISSUE THREAD

**Issue by aslepchenko** [WordPress/gutenberg#24928]
**Describe the bug**
When i saving block, if the InnerBlocks is placed inside the ``<a>`` tag, on frontend occurs recursive duplicate of the link.
It happens if block like 'core/button' inside innerblocks has link
**To reproduce**
1. Create block with code:
```
import { registerBlockType } from '@wordpress/blocks';
import { InnerBlocks } from '@wordpress/block-editor';

registerBlockType( 'test/bug-replay', {
	title: 'Bug Replay',
	edit: ( { className } ) => {
		return (
			<div className={ className }>
				<a href="#bugreply">
					<InnerBlocks
						allowedBlocks={ [ 'core/buttons', 'core/paragraph' ] }
					/>
				</a>
			</div>
		);
	},
	save: ( { className } ) => {
		return (
			<div className={ className }>
				<a href="#bugreply">
					<InnerBlocks.Content />
				</a>
			</div>
		);
	},
} );
```
2. On editor add block "Bug Replay"
3. Inside the block add button block
4. Give the button a name 'test' and insert link inside button '/bug-replay'
5. Save block and go to frontend of page
4. See error:
```
<div class="entry-content">
  <div class="wp-block-test-bug-replay">
    <a href="#bugreply"></a>
    <div class="wp-block-buttons">
      <a href="#bugreply"></a>
      <div class="wp-block-button">
        <a href="#bugreply"></a>
        <a class="wp-block-button__link" href="/bug-replay">test</a>
      </div>
    </div>
  </div>
</div>
```

**Expected behavior**
```
<div class="entry-content">
  <div class="wp-block-test-bug-replay">
    <a href="#bugreply">
    <div class="wp-block-buttons">
      <div class="wp-block-button">
        <a class="wp-block-button__link" href="/bug-replay">test</a>
      </div>
    </div>
   </a>
  </div>
</div>
```

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Chrome
 - Version: 84

**Comment by kishanjasani** [comment]
@aslepchenko Thanks for reporting the issue. I am also able to reproduce this issue.

**Comment by aristath** [comment]
I'm not sure this is an issue...
The "expected behaviour" described above is actually invalid HTML, according to the W3C nested links are illegal.

**Comment by aslepchenko** [comment]
@aristath Thanks for the answer, I didn't pay attention to errors in the markup. 
I wanted to use core button block, but understood, that core button markup is does not fit.
But I still find the save serializer behavior is strange.
