### ISSUE TITLE
Remove deprecated __unstableMigrate function

### ISSUE THREAD

**Issue by senadir** [WordPress/gutenberg#24931]
`wp.data.plugins.persistence` has a deprecated function `__unstableMigrate` that should have been removed when WP 5.4 was released.
https://github.com/WordPress/gutenberg/blob/655475a10ae31cbb737b1b26b1bc057317b9e560/packages/data/src/plugins/persistence/index.js#L225-L294

**Comment by sbappan** [comment]
Hi. Can I work on this issue?

**Comment by senadir** [comment]
@sbappan absolutely! I assigned this to you.

**Comment by sbappan** [comment]
> @sbappan absolutely! I assigned this to you.

Thank you!

**Comment by BertAnthonyRochester** [comment]
https://github.com/WordPress/gutenberg/issues/24931#issue-689117138

**Comment by skorasaurus** [comment]
Per discussion in the PR, https://github.com/WordPress/gutenberg/pull/25023 ; waiting until the plugin requires 5.6.

**Comment by skorasaurus** [comment]
no longer blocked due to https://github.com/WordPress/gutenberg/pull/34536 ; 5.7 is the minimum version now

**Comment by t-hamano** [comment]
As this issue has been properly handled by #39795, so we closed the related PR #25023.
Therefore, we would like to close this issue as well 👍
