### ISSUE TITLE
Media Upload: Maximum File Size error showing when not enough space to upload

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#24948]
**Describe the bug**
When uploading an image to a site that has nearly maxed out the limited amount of storage space (Multisite site) and ` get_site_option( 'upload_space_check_disabled' )` is `true`, the error message will be ["The file exceeds the maximum upload size for this site."](https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/media-utils/src/utils/upload-media.js#L151-L161) instead of the more accurate "Not enough space to upload. [#]kb needed."

**To reproduce**
1. Create a multisite install
2. go to /wp-admin/network/site-settings.php?id=1 where `1` is your site ID and set `Upload Space Check Disabled` to `0` and `Site Upload Space Quota` to 5mb
3. Upload the same image several times until you're about to reach 5mb
4. When going over the limit, you'll see a "This file exceeds the maximum upload size for this site." error message even though the file is the same size as it was before.

**Expected behavior**
I expected the error message to be about maxing out the storage space rather than that a file size too large message.

**Screenshots**
You can check your existing upload space on the site dashboard: 
<img width="531" alt="At a glance dashboard widget showing storage space" src="https://user-images.githubusercontent.com/967608/91766988-0f77e880-eba1-11ea-8252-dd4ebd73eb43.png">

Incorrect error message for multisite
<img width="629" alt="Image block with This file exceeds the maximum upload size for this site error message" src="https://user-images.githubusercontent.com/967608/91767063-2cacb700-eba1-11ea-9052-960ecbdb2121.png">

**Cause**
- The uploader uses `maxUploadFileSize` to determine [if we should open a request or not to upload the file](https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/media-utils/src/utils/upload-media.js#L149-L160)
- It assumes that `maxUploadFileSize` will be consistent
- it uses [`wp_max_upload_size()` to set it](https://github.com/WordPress/gutenberg/blob/6b1999ef5ad3aded974bb311d0f72cd2eef134b1/lib/edit-site-page.php#L106)
- On multisites, `wp_max_upload_size()` is actually variable determined by the maximum file size OR the amount of space left after it gets filtered through this function:
```
function upload_size_limit_filter( $size ) {
	$fileupload_maxk = KB_IN_BYTES * get_site_option( 'fileupload_maxk', 1500 );
	if ( get_site_option( 'upload_space_check_disabled' ) ) {
		return min( $size, $fileupload_maxk );
	}

	return min( $size, $fileupload_maxk, get_upload_space_available() );
}
```
- Since `wp_max_upload_size is variable on multisites, it will reduce the maximum upload space available to the space left, which results in the incorrect error message.

**Comment by jordesign** [comment]
This appears to have been resolved by [this PR](https://github.com/WordPress/gutenberg/pull/25004) so closing the issue
