### ISSUE TITLE
Widgets page: the Settings button isn't labelled (no button text nor aria-label)

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#24943]
**Describe the bug**

In the new Widgets page, the "Settings" button isn't labelled. As such, it's announced by screen readers as just "button".

Also, it doesn't show a tooltip on hover/focus as the tooltips are based on the `aria-label` attribute.

For reference, in the block editor this button has an `aria-label="Settings"` attribute.

**Screenshots**

<img width="1288" alt="Screenshot 2020-08-31 at 17 45 31" src="https://user-images.githubusercontent.com/1682452/91739587-6df99280-ebb2-11ea-980b-172487a6d545.png">

**Comment by mapk** [comment]
Nice catch! cc @draganescu @talldan @adamziel let's make sure this gets carried over from the Post Editor too. Thanks Andrea!
