### ISSUE TITLE
TinyMCE Nightly: Caret moves to the end on paste

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2494]
I haven't been able to track down what commit causes it.

When I paste content in the middle of a block, the caret moves to the end right before content is pasted, so splitting the block fails and the new blocks are moved after the focussed block.

**Comment by spocke** [comment]
This has to do with an internal restructuring we did some things were not covered properly by tests. We are working on fixing this.

**Comment by spocke** [comment]
This one was corrected.
