### ISSUE TITLE
Navigation Component: Indicate fetching state with Spinner

### ISSUE THREAD

**Issue by psealock** [WordPress/gutenberg#24950]
As noted in https://github.com/WordPress/gutenberg/pull/24920#issuecomment-683796194, Navigation's badges are likely to be fetched asynchronously.

Restrict `badge` to numbers and add an `isFetching` prop to display a spinner.

**Comment by Copons** [comment]
I'm not sure if this is, or should be, a concern of the `Navigation`. 🤔 

When the consumer defines the navigation content (either with components or with the config prop), isn't it their responsibility to also fetch the badges number?

Or maybe we are only talking of badges as "children count" for items navigating to a nested menus?
In that case it should be yet another good use case for a tree abstraction to be kept in the `NavigationContext` as proposed in #25246.

**Comment by psealock** [comment]
I also don't think it should be the responsibility of this component to handle fetching.

Since a prop is provided for rendering a badge, this issue is better suited to explore allowing rendering of a spinner to indicate loading state. Right now, `badge` can be anything so we can restrict it to numbers and add an `isFetching` prop to display a spinner.

I'll change this issue to reflect this.

**Comment by shaunandrews** [comment]
I'm not sure a spinner is necessary. In https://github.com/WordPress/gutenberg/pull/25327#issuecomment-692739940 I left the following comment:

> I think it would be better to show nothing rather than this spinner; It feels too distracting for information that isn't really that important. Instead, I'd expect the badge to transition (probably just fade in) into place when the data is loaded. Otherwise, I worry we'll end up with half-a-dozen spinners in the sidebar.
