### ISSUE TITLE
Post Date: Block Enhancement Ideas

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#24957]
Here are some ideas to improve the Post Date block:
- [x] add support for text styling options (bold, italic)
- [x] a couple more date formats? For example, dd/mm/yyyy and or mm/dd/yyyy
- [ ] be able to include an icon - I know an icon could be inserted as a separate block, but that would require a columns block which feels like a bit much for such a simple thing?

**Comment by scruffian** [comment]
This should also be able to link to the post permalink.

**Comment by annezazu** [comment]
Related feedback came up in the [fifth call for testing for the FSE outreach program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1557):

> Comments count and post publish date are without labels? What I mean are post meta labels such as “Posted on:”, “Written by:” and “Comments count:”. It would be also great to hide these accessibly if possible (or maybe ability to set CSS class for them?).

Making sure to close the loop here as part of enhancements to consider :)

**Comment by mikeywil** [comment]
An idea based on how I thought the block was going to work before I used it:

- The 'Settings > General' page has an option for setting Date Format and Time Format for the site as a whole. Could this be factored into the Post Date block in some way? It might be the default setting, and/or one of the options.

**Comment by ohlauren** [comment]
Three things I would really like to see:

- an option to mimic the behavior of the_date(), where it is only displayed the first time a given date appears in the loop
- related, the ability to change wrap the <time> element in a heading tag
- more format options - relative times (ie "2 days ago"), full date format with weekday, maybe a text field that accepts any PHP date format string?

**Comment by noisysocks** [comment]
> The 'Settings > General' page has an option for setting Date Format and Time Format for the site as a whole. Could this be factored into the Post Date block in some way? It might be the default setting, and/or one of the options.
> maybe a text field that accepts any PHP date format string?

These two suggestions were implemented as part of https://github.com/WordPress/gutenberg/pull/39209.

**Comment by ramonjd** [comment]
> add support for text styling options (bold, italic)

Implemented in https://github.com/WordPress/gutenberg/pull/35422 and https://github.com/WordPress/gutenberg/pull/34064

**Comment by noisysocks** [comment]
>  be able to include an icon

Could you elaborate on this? An icon of what? I'm curious what @jasmussen thinks too.

I'm kinda thinking we can close this issue in favour of future smaller enhancement requests.

**Comment by alaczek** [comment]
Having an icon for the post-meta items is a popular design pattern. This is what I had in mind:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/4550351/202934026-dcbd403a-ad93-4697-8eb8-d6c7aada1500.png">
I think back when this issue was initially opened, we didn't yet have access to the row block, which makes it easier to achieve this than columns, so feel free to close if there are no other objections.

**Comment by noisysocks** [comment]
Thanks, that makes sense. I'll close this out for now.

**Comment by jasmussen** [comment]
Definitely a classic pattern. I like to think that at the moment, in-editor icon support is sparse and unrefined — you can choose one different alternative for menus, but that's it. Adding iconography across blocks is a valid enhancement, but one that probably needs a lot of careful thought, technical and designwise.
