### ISSUE TITLE
Image block's image can bleed out of the block

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#2496]
## Issue Overview

If you insert an image, resize it to full width, then edit it and select a taller image, the new image bleeds out of the block, covering other blocks.

## Steps to Reproduce (for bugs)

In Chrome 60

1. Insert a small, square image
2. Resize the image using the blue handles to full width of the block
3. Edit the image, replacing it with a tall rectangular image

## Expected Behavior

The block should resize, lower blocks should still be visible, caption should still be visible.

## Current Behavior

https://www.youtube.com/watch?v=qeoF7X_IldA

**Comment by karmatosed** [comment]
I don't seem able to reproduce this in 1.1.0. If you are able to, could you let me know please? Closing for now.
