### ISSUE TITLE
Interaction with AMP plugin causes an editor crash on long posts

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#24963]
See this issue for details https://github.com/ampproject/amp-wp/issues/5308

In long posts (over 120k characters), on sites with the AMP plugin installed, the gutenberg editor is unable to load the post.

Disabling the AMP plugin fixes the issue, but the error is actually thrown from within gutenberg code 🤔 

# To reproduce 
Install the AMP plugin on a test wordpress installation
Generate 120k Characters of text with this tool https://onlinerandomtools.com/generate-random-string
Create a post in the gutenberg editor, paste in the 120K characters
Reload the page

# Actual Behavior 
The editor fails to load with a javascript error on the console

![Sep-01-2020 18-34-12](https://user-images.githubusercontent.com/22446385/91827742-96e95880-ec82-11ea-96b9-15c23f3e0b5c.gif)

**Comment by westonruter** [comment]
The cause has been identified by @pierlon as a bug in the AMP plugin: https://github.com/ampproject/amp-wp/issues/5308#issuecomment-685082361

We'll fix in the next AMP plugin patch release (v2.0.1).
