### ISSUE TITLE
Console error when trying to open the aspect-ratio tool for images

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#24971]
**Describe the bug**

Trying to open the aspect-ratio tool for an image block throws errors in the console:

1st message:
> Warning: Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
<details>
<pre>
Warning: Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by e)
    in div (created by e)
    in e (created by Wt)
    in Wt (created by zi)
    in div (created by r)
    in r (created by ForwardRef(NavigableContainer))
    in ForwardRef(NavigableContainer) (created by ForwardRef)
    in ForwardRef (created by zi)
    in div
    in div
    in div (created by ForwardRef)
    in ForwardRef
    in Unknown (created by B)
    in r (created by WithFocusOutside(r))
    in div (created by WithFocusOutside(r))
    in WithFocusOutside(r) (created by B)
    in Unknown (created by f)
    in div (created by f)
    in f (created by Context.Consumer)
    in WithFocusReturn(Component) (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in div (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in WithConstrainedTabbing(WithFocusReturn(Component)) (created by B)
    in S (created by C)
    in C (created by B)
    in B (created by zi)
    in div (created by zi)
    in zi (created by xs)
    in xs (created by Gt)
    in Gt (created by ForwardRef(v))
    in ForwardRef(v)
    in ForwardRef(v) (created by ForwardRef)
    in ForwardRef (created by Ut)
    in div (created by ih)
    in ih (created by uh)
    in uh (created by Ut)
    in S (created by C)
    in C (created by BlockControlsFill)
    in BlockControlsFill (created by f)
    in f (created by Ut)
    in Ut (created by Zt)
    in Zt
    in figure (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef
    in Unknown (created by (Component))
    in (Component)
    in Unknown (created by WithToolbarControls(Component))
    in WithToolbarControls(Component) (created by WithInspectorControl(WithToolbarControls(Component)))
    in WithInspectorControl(WithToolbarControls(Component)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))) (created by WithFilters(Component))
    in WithFilters(Component) (created by cr)
    in cr
    in r
    in Unknown (created by (Component))
    in (Component) (created by ((Component)))
    in ((Component)) (created by WithFontSizeInlineStyles(((Component))))
    in WithFontSizeInlineStyles(((Component))) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))
    in WithSelect(WithDispatch(IfCondition(WithFilters(Component))))
    in Unknown (created by Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))))
    in Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))) (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by es)
    in es (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by mt)
    in div
    in Unknown (created by WithSafeTimeout(Component))
    in WithSafeTimeout(Component) (created by mt)
    in div (created by Ql)
    in div (created by Ql)
    in Ql (created by mt)
    in div (created by Cs)
    in Cs (created by mt)
    in div (created by r)
    in r
    in Unknown (created by WithSelect(r))
    in WithSelect(r) (created by mt)
    in div (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r)) (created by mt)
    in mt (created by In)
    in div
    in div
    in div
    in Unknown (created by NavigateRegions(Component))
    in div (created by NavigateRegions(Component))
    in NavigateRegions(Component) (created by In)
    in div (created by h)
    in h (created by In)
    in In (created by n)
    in r (created by n)
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component) (created by r)
    in Zn (created by r)
    in rr (created by r)
    in rr (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r))
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithSelect(WithDispatch(r))) (created by n)
    in div (created by r)
    in r (created by n)
    in k (created by r)
    in r (created by n)
    in StrictMode (created by n)
    in n (created by WithDispatch(n))
    in WithDispatch(n)
    in Unknown (created by WithSelect(WithDispatch(n)))
    in WithSelect(WithDispatch(n)) react-dom.82e849f1.js:82:32
</pre>
</details>

2nd message:
> Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

<details>
<pre>
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Wt)
    in div (created by e)
    in div (created by e)
    in e (created by Wt)
    in Wt (created by zi)
    in div (created by r)
    in r (created by ForwardRef(NavigableContainer))
    in ForwardRef(NavigableContainer) (created by ForwardRef)
    in ForwardRef (created by zi)
    in div
    in div
    in div (created by ForwardRef)
    in ForwardRef
    in Unknown (created by B)
    in r (created by WithFocusOutside(r))
    in div (created by WithFocusOutside(r))
    in WithFocusOutside(r) (created by B)
    in Unknown (created by f)
    in div (created by f)
    in f (created by Context.Consumer)
    in WithFocusReturn(Component) (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in div (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in WithConstrainedTabbing(WithFocusReturn(Component)) (created by B)
    in S (created by C)
    in C (created by B)
    in B (created by zi)
    in div (created by zi)
    in zi (created by xs)
    in xs (created by Gt)
    in Gt (created by ForwardRef(v))
    in ForwardRef(v)
    in ForwardRef(v) (created by ForwardRef)
    in ForwardRef (created by Ut)
    in div (created by ih)
    in ih (created by uh)
    in uh (created by Ut)
    in S (created by C)
    in C (created by BlockControlsFill)
    in BlockControlsFill (created by f)
    in f (created by Ut)
    in Ut (created by Zt)
    in Zt
    in figure (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef
    in Unknown (created by (Component))
    in (Component)
    in Unknown (created by WithToolbarControls(Component))
    in WithToolbarControls(Component) (created by WithInspectorControl(WithToolbarControls(Component)))
    in WithInspectorControl(WithToolbarControls(Component)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))) (created by WithFilters(Component))
    in WithFilters(Component) (created by cr)
    in cr
    in r
    in Unknown (created by (Component))
    in (Component) (created by ((Component)))
    in ((Component)) (created by WithFontSizeInlineStyles(((Component))))
    in WithFontSizeInlineStyles(((Component))) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))
    in WithSelect(WithDispatch(IfCondition(WithFilters(Component))))
    in Unknown (created by Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))))
    in Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))) (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by es)
    in es (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by mt)
    in div
    in Unknown (created by WithSafeTimeout(Component))
    in WithSafeTimeout(Component) (created by mt)
    in div (created by Ql)
    in div (created by Ql)
    in Ql (created by mt)
    in div (created by Cs)
    in Cs (created by mt)
    in div (created by r)
    in r
    in Unknown (created by WithSelect(r))
    in WithSelect(r) (created by mt)
    in div (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r)) (created by mt)
    in mt (created by In)
    in div
    in div
    in div
    in Unknown (created by NavigateRegions(Component))
    in div (created by NavigateRegions(Component))
    in NavigateRegions(Component) (created by In)
    in div (created by h)
    in h (created by In)
    in In (created by n)
    in r (created by n)
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component) (created by r)
    in Zn (created by r)
    in rr (created by r)
    in rr (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r))
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithSelect(WithDispatch(r))) (created by n)
    in div (created by r)
    in r (created by n)
    in k (created by r)
    in r (created by n)
    in StrictMode (created by n)
    in n (created by WithDispatch(n))
    in WithDispatch(n)
    in Unknown (created by WithSelect(WithDispatch(n)))
    in WithSelect(WithDispatch(n)) react-dom.82e849f1.js:82:32
    printWarning http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:82
    error http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:54
    validateProperty$1 http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5672
    warnUnknownProperties http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5718
    validateProperties$2 http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5742
    validatePropertiesInDevelopment http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5785
    setInitialProperties http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:6064
    finalizeInitialChildren http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:7622
    completeWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:19113
    completeUnitOfWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22324
    performUnitOfWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22300
    workLoopSync http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22265
    performSyncWorkOnRoot http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:21891
    flushSyncCallbackQueueImpl http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11224
    unstable_runWithPriority http://localhost/wp-content/plugins/gutenberg/vendor/react.af754d50.js:2685
    runWithPriority$1 http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11174
    flushSyncCallbackQueueImpl http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11219
    flushSyncCallbackQueue http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11207
    discreteUpdates$1 http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22028
    discreteUpdates http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:803
    dispatchDiscreteEvent http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4291
    addEventBubbleListener http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4150
    trapEventForPluginEventSystem http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4285
    trapBubbledEvent http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4256
    legacyListenToTopLevelEvent http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:3765
    legacyListenToEvent http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:3724
    ensureListeningTo http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5884
    setInitialDOMProperties http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:5951
    setInitialProperties http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:6149
    finalizeInitialChildren http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:7622
    completeWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:19113
    completeUnitOfWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22324
    performUnitOfWork http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22300
    workLoopSync http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22265
    performSyncWorkOnRoot http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:21891
    flushSyncCallbackQueueImpl http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11224
    unstable_runWithPriority http://localhost/wp-content/plugins/gutenberg/vendor/react.af754d50.js:2685
    runWithPriority$1 http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11174
    flushSyncCallbackQueueImpl http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11219
    flushSyncCallbackQueue http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11207
    scheduleUpdateOnFiber http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:21334
    dispatchAction http://localhost/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:15795
    e http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    t http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    o http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    o http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    h http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    p http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    e http://localhost/wp-admin/post.php?post=22&action=edit:1
    s Redux
    A http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    N http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    dispatch http://localhost/wp-content/plugins/gutenberg/build/data/index.js?ver=86e17756483edb79c5c2acf422ecb400:1
    Redux 32

</pre>
</details>

**To reproduce**

1. Add an image block
2. Add an image and open the aspect-ratio tool

**Screenshots**
![Peek 2020-09-01 14-39](https://user-images.githubusercontent.com/588688/91845106-47466500-ec61-11ea-9cad-224d81e15898.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Gutenberg plugin - master branch (at this time: https://github.com/WordPress/gutenberg/tree/33c83fa7bd917704cf23cfc7106598c11fd0c6e5)

**Desktop (please complete the following information):**
 - OS: Linux (Pop!_OS/Ubuntu)
 - Browser: Firefox - v80.0

---------------------
EDIT: Putting additional info from a later comment here to have everything in one place:
Only happens if I have `define( 'SCRIPT_DEBUG', true );` in my `wp-config.php`
Happens without the plugin installed too, so it's in wp-core too

**Comment by kishanjasani** [comment]
@aristath I not able to reproduce it. I have tried with the latest Gutenberg master branch.

**Comment by aristath** [comment]
Additional info:
Only happens if I have `define( 'SCRIPT_DEBUG', true );` in my `wp-config.php`
Happens without the plugin installed too, so it's in wp-core too

**Comment by kishanjasani** [comment]
Yes, Getting thanks :slightly_smiling_face:

**Comment by kishanjasani** [comment]
Not able to reproduces this issue in the Gutenberg plugin. But it's still alive in WordPress Core.

<details><summary>Details</summary>

```
Warning: Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by e)
    in div (created by e)
    in e (created by Wt)
    in Wt (created by zi)
    in div (created by r)
    in r (created by ForwardRef(NavigableContainer))
    in ForwardRef(NavigableContainer) (created by ForwardRef)
    in ForwardRef (created by zi)
    in div
    in div
    in div (created by ForwardRef)
    in ForwardRef
    in Unknown (created by B)
    in r (created by WithFocusOutside(r))
    in div (created by WithFocusOutside(r))
    in WithFocusOutside(r) (created by B)
    in Unknown (created by f)
    in div (created by f)
    in f (created by Context.Consumer)
    in WithFocusReturn(Component) (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in div (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in WithConstrainedTabbing(WithFocusReturn(Component)) (created by B)
    in S (created by C)
    in C (created by B)
    in B (created by zi)
    in div (created by zi)
    in zi (created by xs)
    in xs (created by Gt)
    in Gt (created by ForwardRef(v))
    in ForwardRef(v)
    in ForwardRef(v) (created by ForwardRef)
    in ForwardRef (created by Ut)
    in div (created by ih)
    in ih (created by uh)
    in uh (created by Ut)
    in S (created by C)
    in C (created by BlockControlsFill)
    in BlockControlsFill (created by f)
    in f (created by Ut)
    in Ut (created by Zt)
    in Zt
    in figure (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef
    in Unknown (created by (Component))
    in (Component)
    in Unknown (created by WithToolbarControls(Component))
    in WithToolbarControls(Component) (created by WithInspectorControl(WithToolbarControls(Component)))
    in WithInspectorControl(WithToolbarControls(Component)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))) (created by WithFilters(Component))
    in WithFilters(Component) (created by cr)
    in cr
    in r
    in Unknown (created by (Component))
    in (Component) (created by ((Component)))
    in ((Component)) (created by WithFontSizeInlineStyles(((Component))))
    in WithFontSizeInlineStyles(((Component))) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))
    in WithSelect(WithDispatch(IfCondition(WithFilters(Component))))
    in Unknown (created by Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))))
    in Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))) (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by es)
    in es (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by mt)
    in div
    in Unknown (created by WithSafeTimeout(Component))
    in WithSafeTimeout(Component) (created by mt)
    in div (created by Ql)
    in div (created by Ql)
    in Ql (created by mt)
    in div (created by Cs)
    in Cs (created by mt)
    in div (created by r)
    in r
    in Unknown (created by WithSelect(r))
    in WithSelect(r) (created by mt)
    in div (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r)) (created by mt)
    in mt (created by In)
    in div
    in div
    in div
    in Unknown (created by NavigateRegions(Component))
    in div (created by NavigateRegions(Component))
    in NavigateRegions(Component) (created by In)
    in div (created by h)
    in h (created by In)
    in In (created by n)
    in r (created by n)
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component) (created by r)
    in Zn (created by r)
    in rr (created by r)
    in rr (created by r)
    in r (created by WithDispatch(r))
    in WithDispatch(r)
    in Unknown (created by WithSelect(WithDispatch(r)))
    in WithSelect(WithDispatch(r))
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithSelect(WithDispatch(r))) (created by n)
    in div (created by r)
    in r (created by n)
    in k (created by r)
    in r (created by n)
    in StrictMode (created by n)
    in n (created by WithDispatch(n))
    in WithDispatch(n)
    in Unknown (created by WithSelect(WithDispatch(n)))
    in WithSelect(WithDispatch(n)) react-dom.82e849f1.js:82:32
```
</details>

**Comment by kishanjasani** [comment]
> Not able to reproduces this issue in the Gutenberg plugin. But it's still alive in WordPress Core.

I am not getting this error because each menu items are getting a unique id.

**Comment by aristath** [comment]
Seems to be fixed, yes. I'm getting all sorts of other errors but not related to this one, so I'll go ahead and close this ticket :+1:
