### ISSUE TITLE
Hi. Can I work on this issue?

### ISSUE THREAD

**Issue by BertAnthonyRochester** [WordPress/gutenberg#24972]
Hi. Can I work on this issue?

_Originally posted by @sbappan in https://github.com/WordPress/gutenberg/issues/24931#issuecomment-683839194_

**Comment by annezazu** [comment]
Hi @BertAnthonyRochester - Is there a reason you opened up an issue? It seems you already commented on the original issue which is the best way to get started. You might find this guide from @mkaz helpful to get started: https://mkaz.blog/code/good-first-issue-on-gutenberg/

For now though, I'm going to close this out as it doesn't need a new issue. Please continue chatting on #24931.
