### ISSUE TITLE
By default Experimental Link Color should not apply to buttons

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#24981]
**Describe the bug**

When a theme opts into `add_theme_support('experimental-link-color')`, the color chosen for a custom link color overrides custom text colors chosen for the button block. 

**To reproduce**
1. Create a Group Block
2. Assign it a custom link color. 
3. Add a button inside of that Group.
4. Assign the button a custom text color. 

**Expected behavior**

I expected that the button would have the custom text color that I assigned to it. Instead, the custom link color from the Group block is used. 

This is _technically_ overridable by the theme, but it takes some extra-specific CSS. Ideally, I'd expect that the custom link color wouldn't apply to buttons in general. 

**Screenshots**

Editor: 

![Screen Shot 2020-09-01 at 12 48 38 PM](https://user-images.githubusercontent.com/1202812/91882858-997f8a00-ec51-11ea-8b98-9db6cfc0b611.png)

Front-end: 

![Screen Shot 2020-09-01 at 12 49 11 PM](https://user-images.githubusercontent.com/1202812/91883161-0bf06a00-ec52-11ea-9601-deeb2d97bc37.png)

**Comment by aristath** [comment]
The only way I can think of to "fix" this would be to make the default CSS even more specific... So instead of `:root .has-link-color a` it would have to be `:root .has-link-color a:not(.wp-block-button__link)`
Obviously not a perfect solution, but I can't think of a better one :thinking:

**Comment by kjellr** [comment]
Yeah, same here. I spent about an hour digging in, but that seemed like the best solution I could find too.

**Comment by aristath** [comment]
On the other hand, perhaps it should be converted to `:root a:not(.wp-block-button__link)` or something like that... See comment on https://github.com/WordPress/gutenberg/pull/24250#discussion_r469925104 for something we should consider preferably before pushing a fix for this one since things might change a bit

**Comment by Mamaduka** [comment]
This is no longer an issue with block themes, and `experimental-link-color` support has been removed.

I'm going to close the issue.
