### ISSUE TITLE
Current performance renders Gutenberg completely unusable

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#24986]
After writing 2-3 paragraphs my Gutenberg (version 8.8.0) becomes so slow that using it is simply impossible. Is there _anything_ you're going to do with this (since you closed a number of similar bug ticket as there would be no problem)?

It is not a matter of fact that letters are appearing slowly. It is a matter of the fact that I **can write 2-3 long sentences** and **30-60 seconds** can pass since they actually appear on screen! During that time:

* entire Gutenberg is completely not responsive,
* Chrome is getting wako and
* I can clearly hear my laptop's fan speeding up with CPU consumption boosting up to 80-90%!

I have:

* a dual-core / 8 GB RAM laptop:
* _single_ tab with single Wordpress and Gutenberg instance in it,
* no other app running in my Windows 10 Pro,

thus I am using _one_ application (Chrome) with _one_ tab opened (Wordpress) and when I am writing a simple 3-5 paragraphs long post I have the feeling like I would be inside Boeing 747 powering up its engines shortly before take-off. My computer's fans starts to be so loud that my wife can hear them from another room and I am really surprised to find out that my laptop isn't actually flying.

I understand that this is a very general issue, but -- for the sake of God -- try to understand our frustration. You forced us to give up on Classic Editor giving us instead an editor that is bluntly slow from scratch and where writing a short text could take as long as half an hour.

In my every day work with Wordpress / Gutenberg I:

* open up Wordpress,
* create a new post and...
* ...go to Notepad to write my post body (!!!).

Because doing this in Gutenberg is simply impossible.

So let me ask again: **are you going to do anything with that except for closing yet another ticket (this one)**?

Since at number of related issues are closed:

- https://github.com/WordPress/gutenberg/issues/6466
- https://github.com/WordPress/gutenberg/issues/7498
- https://github.com/WordPress/gutenberg/issues/7623

and **nothing** is done so far, I am creating yet another one.

**Comment by mtias** [comment]
Hello! There was a regression introduced in 8.8 that has been fixed here https://github.com/WordPress/gutenberg/pull/24835 and should make it into 8.9, to be released very soon.

> and nothing is done so far, I am creating yet another one.

A lot is being done! The issues you linked are super old, performance is an ongoing effort, improvements are made and sometimes regressions happen. We hope we can catch them quickly and fix them. We have tests that check for performance regressions, but direct reports are always extremely useful.

**Comment by trejder** [comment]
Yes, I can confirm. My Gutenberg was updated to 8.9 and the editing experience is 200% better than before.

It is still far from the perfection, but at least now you can edit normally in the editor, instead of using Notepad, because Gutenberg itself hangs for 30-60 seconds after writing just a few paragraphs. That bad experience seems to be now over, with the update to 8.9.

Thank you for all your effort and support!

**Comment by mtias** [comment]
Thank you for the feedback and sorry for the hiccup there!
