### ISSUE TITLE
Cannot add image from device gallery when limited photo access is enabled

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#24989]
**Describe the bug**
When using Gutenberg within WordPress for iOS, attempting to add an image to an Image block results fails.

**To reproduce**

(Updated, see comment [here](https://github.com/WordPress/gutenberg/issues/24989#issuecomment-686512845).)

1. Open the WordPress for iOS app
2. Create a new post on a site using the block editor
3. Add an Image block
4. Tap ADD IMAGE
5. Select "Choose from device" or "Take a photo"
6. Ensure the app only has permission to selected photos — not all photos
    - If needed, go to Settings > Privacy > Photos > WordPress and select "Selected Photos" under ALLOW PHOTO ACCESS
7. Select an image
8. Notice that the image is not loaded into the block

**Expected behavior**
After selecting an image, the Image block placeholder should be replaced by the selected image.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14 beta
 - WordPress App Version 15.6 alpha ([1.36.0 mobile editor release build 34086](https://github.com/wordpress-mobile/WordPress-iOS/pull/14808))

**Additional context**
- This bug was found using the iOS 14 beta

**Comment by antonis** [comment]
I tried to reproduce this on an iPhone SE 2020 with iOS 14 beta 6 with a blog on WordPress.com.
I was not able to reproduce the issue.

|Choose from device|Take photo|
|---|---|
|![trim](https://user-images.githubusercontent.com/304044/92079861-4b8d9200-edc9-11ea-9bec-8e78e23dff4b.gif)|![Screenshot 2020-09-03 at 9 36 05 AM](https://user-images.githubusercontent.com/304044/92079716-0e290480-edc9-11ea-90ca-d7d326b1f896.png)|

Please note that the first time I opened the photo chooser a permission dialog appeared and I gave full permissions to the app.

**Comment by guarani** [comment]
@antonis apologies for missing an important step needed to reproduce: the app needs to be given to permission to only selected photos for this bug to occur.

Here's the updated steps to reproduce:


> #### To reproduce
> 
> 1. Open the WordPress for iOS app
> 2. Create a new post on a site using the block editor
> 3. Add an Image block
> 4. Tap ADD IMAGE
> 5. Select "Choose from device" or "Take a photo"
> 6. Ensure the app only has permission to selected photos — not all photos
>     - If needed, go to Settings > Privacy > Photos > WordPress and select "Selected Photos" under ALLOW PHOTO ACCESS
> 7. Select an image
> 8. Notice that the image is not loaded into the block

**Comment by antonis** [comment]
@guarani Thank you for the clarification. I should have tested this path anyway but I thought the behaviour would be the same with full photos access :|
I gave permission only to selected photos and managed to reproduce the reported issue. 
<details>
    <summary>See screen recording</summary>
    <img width="300" src="https://user-images.githubusercontent.com/304044/92124845-f2dcea00-ee06-11ea-9e2d-16a3cdff598f.gif">
    </details>
The test was performed again on iPhone SE 2020 with iOS 14 beta 6.

**Comment by frosty** [comment]
I can replicate this too. I'm also unable to add a photo taken with the 'Take a photo' action.

**Comment by marecar3** [comment]
Thanks for the feedback, I am working on this one as part of the hack week.

**Comment by guarani** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14940
