### ISSUE TITLE
REST API: Post types and taxonomies labels

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2499]
Related: https://github.com/WordPress/gutenberg/pull/2489#issuecomment-323789114

Relevant APIs:
- https://developer.wordpress.org/reference/functions/register_post_type/
- https://developer.wordpress.org/reference/functions/register_taxonomy/
- https://developer.wordpress.org/reference/functions/get_post_type_labels/
- https://developer.wordpress.org/reference/functions/get_taxonomy_labels/

Prior art:
- https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/post-types/%24post_type/taxonomies/

There's a need to show post type and taxonomy labels in the Gutenberg interface. This will enhance the experience of related workflows such as "Add New Genre" (for a genre custom taxonomy) in place of the generic "Add New Tag".

Potentially, this ties into a larger need for sharing localized strings between the server and client, but in these cases the strings are very dynamic (depending on which post types / taxonomies registered).

Potential solutions may include bootstrapping localized strings from the server using [`wp_localize_script`](https://developer.wordpress.org/reference/functions/wp_localize_script/), but it opens concerns of:

- How scalable is this approach for increasingly client-based interfaces? [Media library strings](https://github.com/WordPress/WordPress/blob/9db227ac071c73ca70f5c7ca9492e3fc63131fab/wp-includes/media.php#L3490-L3612) are the closest example and are already quite unwieldy.
- What solution is there for interfaces consuming from the REST API which don't have the option to bootstrap from the server (e.g. static single-page applications)?

**Comment by TimothyBJacobs** [comment]
Both the `wp/v2/types` and `wp/v2/taxonomies` endpoints should contain the labels.

**Comment by aduth** [comment]
On pointers from @rmccue and confirming in testing, I did find both the types and taxonomies endpoints include `labels` **when specifying `?context=edit`**
