### ISSUE TITLE
Consider how editor interacts with other inline apps

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25]
I use PopClip which whilst a stress case, I thought it was interesting to share what happened with the editor when I interacted. I use this app to help with my dyslexia amongst other things - it has spelling checks and a ton of other features - it's not just for that use case but it works really well for a lot of people.

![01](https://cloud.githubusercontent.com/assets/253067/22751668/617fc7b4-ee03-11e6-8013-2cdcbc9df1b6.png)

![02](https://cloud.githubusercontent.com/assets/253067/22751671/648dd946-ee03-11e6-9b51-ddd3a249309b.png)

In showing these, I really like having the editor 'just where I need it'. We just may have to adjust that in relation to some of apps. I think there are quite a few that do similar. Whilst not by any means majority of users will use these apps, we should allow for them.

**Comment by jasmussen** [comment]
Noting this as an argument for not using the inline popup toolbar for formatting. Inline toolbars aren't going to work on mobile regardless.

Here's a mockup showing how a UI could look where toolbars are docked to the block:

![formatting click](https://cloud.githubusercontent.com/assets/1204802/22922867/98f4ac3c-f29f-11e6-8325-051d23316a10.png)

**Comment by karmatosed** [comment]
For a visual record here is what currently is the case (I can do this each time to check):

![2017-02-20 at 11 43](https://cloud.githubusercontent.com/assets/253067/23123835/fafa3da4-f761-11e6-8063-a558995e3da8.png)

**Comment by jasmussen** [comment]
Closing as for now at least we've decided to go with controls all being docked at the top of the block.
