### ISSUE TITLE
Move theme location selection into the Navigation block's Inspector

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25011]
### Descripion

Part of #24875
Move the menu's theme location selection into the Navigation block's Inspector settings.

<img width="898" alt="Screenshot 2020-09-02 at 16 28 26" src="https://user-images.githubusercontent.com/107534/91989611-60224980-ed39-11ea-813a-f59e7e858d47.png">

**Comment by talldan** [comment]
Closing this as there's quite a lot of overlap with https://github.com/WordPress/gutenberg/issues/28864 which has the latest designs.
