### ISSUE TITLE
Add SocialLinks block to the Navigation block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25016]
### Description

Part of #24875

We should add the ability to place a `SocialLinks` block to a navigation block. Currently we can add a search block.

**Comment by talldan** [comment]
A first step for anyone interested in pick this up would be to update the `allowedBlocks` for the navigation block:
https://github.com/WordPress/gutenberg/blob/bd8bfeacae193b3c249b8baffd0248595b2a0d47/packages/block-library/src/navigation/edit.js#L182-L185

There may also be styling issues when social links is rendered in Navigation, but that can always be addressed in a separate PR.

**Comment by jordesign** [comment]
I'm happy to jump in and get my feet wet with this one.

**Comment by talldan** [comment]
That'd be great, thanks @jordesign!

**Comment by jordesign** [comment]
Allowing the nav block works well enough 👍

I'm wondering if we need to worry/think about the fact the alignment controls for the Social Links block don't make much sense in the context of a Nav Block?

At the moment you can set an alignment on the Social Icons which breaks the layout *in the editor*.

<img width="787" alt="Screen Shot 2020-09-13 at 3 28 06 pm" src="https://user-images.githubusercontent.com/1842363/93011017-fa09b200-f5d5-11ea-81e4-a5cebb5c6263.png">

This doesn't seem to impact things on the front-end (testing with TwentyTwenty) but it seems it needs to be a nicer experience in the editor?

**Comment by shaunandrews** [comment]
Is it possible to hide the alignment options when the Social Links block is place within the Navigation block?

**Comment by jordesign** [comment]
@shaunandrews That's essentially what I was thinking too. I'm not sure of the answer though 😂.

**Comment by draganescu** [comment]
@jordesign I assigned this to you. Be sure to mention the issue when you open a PR with your work above thank you 🙏

**Comment by talldan** [comment]
@jordesign That's an interesting one. I don't think there's a good way to achieve this at the moment.

The problem you've outlined is a bit higher level than this issue, and probably needs some discussion and potentially a new API for blocks. I think it'd be good to create your PR as is, and move the discussion on this on problem to a separate issue.

**Comment by jordesign** [comment]
PR is added ^

Will open a new issue regarding controlling whether alignment tools show when the block is inserted.

**Comment by draganescu** [comment]
Closed by #25357
