### ISSUE TITLE
Show Navigation block's children on hover

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25012]
### Description

Part of #24875
Update the behavior of Navigation block's interactivity:

1) When the Navigation block is selected, hovering over a menu item with children should display those children in a dropdown. 

2) Selecting a menu item with children will force the display of those children. If a block _other than_ the Navigation block is selected, hovering should have no affect on the display of children

**Comment by tellthemachines** [comment]
We definitely had this at some point in the past and then it was removed. Would be good to know the reasons for removal before re-implementing.

**Comment by noisysocks** [comment]
> We definitely had this at some point in the past and then it was removed. Would be good to know the reasons for removal before re-implementing.

I wonder if @getdave or @kovshenin remembers?

**Comment by obenland** [comment]
I don't, unfortunately. Do we know when it was removed?

**Comment by getdave** [comment]
I don't remember I'm afraid. Actually, I believe it was our good friend @retrofox who was heavily involved in this aspect of show/hide on children.

Please note however, that when we were working on the Navigation block you could only add one type of child. With lots of blocks in play things have probably changed.

**Comment by retrofox** [comment]
Hi, there. I remember we dealing with this issue, setting a proper box-model to don't lose the hovered stated among other pieces of the navigation, but not in detail, though :-(.
It's a fragile implementation in the sense if we aren't careful changing these values it could get broken.

>  it was our good friend @retrofox 

<3

**Comment by jasmussen** [comment]
Is this one done? #29756 landed recently which I believe addressed this one. @draganescu what do you think?

**Comment by draganescu** [comment]
The navigation block does not behave yet as described in this issue, particularly here:

>  If a block other than the Navigation block is selected, hovering should have no affect on the display of children

**Comment by jasmussen** [comment]
Oh! I can fix that. Thanks.
