### ISSUE TITLE
Update the Navigation block's description

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25013]
### Description

Part of #24875
Updated the Navigation block's description to "A collection of blocks that allow visitors to get around your site."

**Comment by devfle** [comment]
Hey @draganescu, If it is okay, I would be happy to work on it. 😄

**Comment by draganescu** [comment]
Howdy @devfle ! The block's description should b

**Comment by devfle** [comment]
Okay, i will work on this today :)

**Comment by draganescu** [comment]
Howdy @devfle I assigned this to you! Thanks so much :) Make sure to mention the issue when you open a PR 👋

**Comment by devfle** [comment]
Thank you! Sorry for keeping you waiting. I had much to do on work last week. But Today I have the time! :-) I will link later the issue on the PR.
