### ISSUE TITLE
Update the Navigation block's placeholder

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25015]
### Description

Part of #24875
Advances #23207

<img width="671" alt="Screenshot 2020-09-02 at 16 44 16" src="https://user-images.githubusercontent.com/107534/91991560-b42e2d80-ed3b-11ea-80ee-9c1cf6b7c296.png">

**Comment by noisysocks** [comment]
Should the Navigation block be updated to use this new placeholder design in both the Navigation editor and post editor? Or just the Navigation editor?

**Comment by draganescu** [comment]
> Should the Navigation block be updated to use this new placeholder design in both the Navigation editor and post editor? Or just the Navigation editor?

@shaunandrews I think both?

**Comment by shaunandrews** [comment]
Yea, I'd expect the placeholder to be the same in both scenarios.

**Comment by draganescu** [comment]
Closed by #27018
