### ISSUE TITLE
Update the "Create menu" flow

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25014]
### Description

Part of #24875
Creating a new menu flows more like the Core Menu's experience; A new Navigation block toolbar is displayed, with focus put on the menu name input. The rest of the UI is disabled until the menu is named and the button is pressed

![navigation-mvp](https://user-images.githubusercontent.com/191598/91492538-d4fe0b00-e883-11ea-89a0-e5ea8e8a5896.gif)

**Comment by noisysocks** [comment]
@shaunandrews: How should this look when there are no menus?
