### ISSUE TITLE
Cover Block: "Wave" styles feel very tall

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#25022]
The "Wave" styles on the cover block are very pronounced:

![image](https://user-images.githubusercontent.com/2846578/92021427-bf775e00-ed27-11ea-93e7-af061f742e36.png)

The height makes the waves feel especially opinionated, which makes it harder to justify using the alternate styles, from a design perspective. CoBlocks works around this by providing some customizations in their Shape Divider block, but we don't have anything similar in core. Perhaps we could consider making the waves shorter by default? Like:

![image](https://user-images.githubusercontent.com/2846578/92021819-580dde00-ed28-11ea-962d-8ba43524efec.png)

**Comment by talldan** [comment]
Hey @melchoyce. Is there a chance this is provided by a plugin you have active? I couldn't find this style in the codebase.

**Comment by melchoyce** [comment]
Good catch. Deactivated everything but Gutenberg and it's no longer an option. Nevermind!
