### ISSUE TITLE
Block group background color feature doesn't work with elements like image, table

### ISSUE THREAD

**Issue by knilkantha** [WordPress/gutenberg#25025]
**Describe the bug**
When we group two or more elements in block editor, we will get the option to set background color. If it is other than the text element (like image, table) it doesn't display any background color in frontend.
**To reproduce**
1. Add two or more images in the post.
2. Group all image [Select all image, then press three-dot, choose 'Group']
3. Go to block tab, click on 'Color settings'
4. Select any color from 'Background Color' section.
5. Publish post.

**Expected behavior**
Same background-color must be displayed in the frontend part. 

**Screenshots**
Block setting
![Screenshot_2](https://user-images.githubusercontent.com/13785872/92026927-8370e700-ed81-11ea-9d8b-cb3c1bcff410.jpg)
Frontend Output
![Screenshot_3](https://user-images.githubusercontent.com/13785872/92027079-c206a180-ed81-11ea-98cd-716d7eee1986.jpg)

- WordPress version: 5.5.1 
- Default block editor only

-  Environment: VVV
 - OS: Windows 10
 - Browser: Firefox
 - Version: 80.0.1 (64-bit)

**Fix**
Adding display:flex on wp-block-group__inner-container class 
`.wp-block-group__inner-container {
    display: flex;
}`

**Comment by knilkantha** [comment]
Centering group element in a row is recommended.

```
.wp-block-group__inner-container {
    display: flex;
    justify-content: center;
}
```

**Comment by kishanjasani** [comment]
@knilkantha Thank You for reporting. Which theme you are using?

**Comment by knilkantha** [comment]
@kishanjasani I have tested with multiple themes including twenty-twenty, Neve and others

**Comment by kishanjasani** [comment]
@knilkantha Background color is also applied in frontend as I have tested on twenty twenty theme. So that is not an issue from Gutenberg. The issue seems like in the theme. Please have a look at https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes

**Comment by knilkantha** [comment]
@kishanjasani Thank you for verifying. I will go look again if this is an actual or theme issue.
