### ISSUE TITLE
[Discussion] font-family stacks for the new font-family picker

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#25032]
Spawned from https://github.com/WordPress/gutenberg/pull/24868

A new font-family picker is getting introduced, and WordPress Core will need to provide some default options for that.
We need to come up with some reasonable, web-safe stacks and the current plan is to have 2 sans-serif, 2 serif and 1 monospace stacks (open for discussion, no decision has been made yet)

This is a blocker for #24868 and needs feedback from the design team.

(@jasmussen please feel free to edit the OP if we need more information)

**Comment by mtias** [comment]
Outside of maybe a systems font stack, WordPress doesn't necessarily need to provide any default choices. It can be left up entirely to the theme.

**Comment by jasmussen** [comment]
Thanks for the ticket. It seems like with Matías comment above, the other feature isn't blocked. The discussion can still be worth having. Most importantly I would just love us avoiding adding some font stacks that are really out of date.

**Comment by scruffian** [comment]
One thing we might want to consider adding is a "system font stack" option (e.g. https://css-tricks.com/snippets/css/system-font-stack/)

**Comment by scruffian** [comment]
> One thing we might want to consider adding is a "system font stack" option (e.g. https://css-tricks.com/snippets/css/system-font-stack/)

Oops, looks like that's already an option here: https://github.com/WordPress/gutenberg/pull/24868/files

**Comment by aristath** [comment]
Closing this one.
With the `theme.json` changes and the way FSE font-families now work, this doesn't seem to be relevant anymore.
