### ISSUE TITLE
getEntityRecord returns null instead of undefined when an entity does not exist.

### ISSUE THREAD

**Issue by herregroen** [WordPress/gutenberg#25045]
**Describe the bug**
in Gutenberg 8.8 `getEntityRecord` and it's related functions ( `getMedia` etc. ) functions would return `undefined` when an entity didn't exist.

In Gutenberg 8.9 this now returns `null`. This is a backwards incompatible change as the recommended method by [eslint](https://eslint.org/docs/rules/no-undefined) to check for undefined is to do `typeof value === "undefined"` which returns `false` for `null`.

This will cause any plugin that previously made this check to start throwing errors as they'll be attempting property access on `null`. This can even cause the entire editor to crash, see https://github.com/Yoast/wordpress-seo/issues/15989.

**To reproduce**
1. Install Yoast SEO 14.9
2. Install Gutenberg 8.9
3. Visit a post in the editor that has a featured image set
4. See that the entire editor doesn't load.
5. Install Gutenberg 8.8.
6. See that no errors occur.

**Expected behavior**
Backwards incompatible changes should not be made to functions without proper notice and deprecation.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.9

**Additional context**
- The relevant change was introduced here: https://github.com/WordPress/gutenberg/pull/19498/files#diff-ea600cd29f004c4af8849b3bd82f0342R122

**Comment by aristath** [comment]
Issue was identified and reported by others too on https://github.com/WordPress/gutenberg/issues/25033

**Comment by regevbr** [comment]
Thanks so much for the swift response! I can confirm that 8.9.1 solved the issue
