### ISSUE TITLE
Improve how left/right floated youtube videos appear

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#2504]
## Steps to Reproduce (for bugs)
1. Insert a new youtube embed from https://www.youtube.com/watch?v=dHg50mdODFM
2. Right align it using the toolbar

Chrome 60

## Expected Behavior

The block should float left or right resized. Embedding a tumblr url http://doctorwho.tumblr.com/post/164495411667/tillthenexttimedoctor-will-we-see-her-again and aligning right or left works as expected.

## Current Behavior

The block disappears completely

**Comment by karmatosed** [comment]
I think I'm seeing a similar thing in Chrome. It doesn't vanish but it is really small. I would say this is a bug and it shouldn't do this.

![2017-08-24 at 19 08](https://user-images.githubusercontent.com/253067/29681481-ab161008-88ff-11e7-81b1-01c1841cb5c9.png)

**Comment by Mathiu** [comment]
Sorry for the mess, here is a PR: #3636

**Comment by aduth** [comment]
Fixed by #3636
