### ISSUE TITLE
Gutemberg adds extra <p> tags wrapping a custom HTML block.

### ISSUE THREAD

**Issue by dazetoyo** [WordPress/gutenberg#25041]
**Describe the bug**
When adding a new HTML block, gutemberg wraps the content inside `<p>` tags. Or tries to. Chrome sees an open `<p>` tag and closes it immediately and then sees an closed `</p>` tag at the end of the html and opens it...

**To reproduce**
1. Go to any page or post.
2. Click on Add HTML block.
3. Insert html `<div class="hi"><p>hi</p></div>`
4. Inspect the page on view page source or the chrome inspector to see empty <p> tags wrapping the html.

**Expected behavior**
Don't wrap my HTML in `<p>` tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/62765799/92102133-78986f80-edde-11ea-892a-07e56298e662.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 85

**Comment by dazetoyo** [comment]
Later edit. It seems like this happens when the HTML is inside a container shortcode like this 
![image](https://user-images.githubusercontent.com/62765799/92103091-c2ce2080-eddf-11ea-92f1-33e12e321557.png)

**Comment by salimserdar** [comment]
Hi @dazetoyo, I've just investigated the point you reported on both the editor and code side. I realized that you might add an empty paragraph block before and after the HTML block. It seems nothing to wrap the HTML block.

If you switch from visual to the code editor, you'll probably see something like that -> 
![Screenshot1](https://user-images.githubusercontent.com/6022770/92414114-a693f180-f107-11ea-860c-70cfb911f5fe.png)

if you delete an empty paragraph block on your page, the empty p tag will not be there.
![Screenshot2](https://user-images.githubusercontent.com/6022770/92414172-e65ad900-f107-11ea-9a82-de5f3255c2e2.png)

If I am wrong, please let me know. I am happy to make a deep investigation to figure it out.

**Comment by dazetoyo** [comment]
Hi @salimserdar . Thanks for your response.

I actually managed to track down the issue to the shortcodes themselves. Using this snippet 

`function here_clean_shortcodes($content){
$array = array (
    '<p>[' => '[',
    ']</p>' => ']',
    ']<br />' => ']'
);
$content = strtr($content, $array);
return $content;
}
add_filter('the_content', 'here_clean_shortcodes');`

fixed the problem. Now the <p> and <br> tags appear only when using the classic block. Which is indeed working as it should.
This is  the article I came across explaining it https://www.wpexplorer.com/clean-up-wordpress-shortcode-formatting/

**Comment by aristath** [comment]
> I actually managed to track down the issue to the shortcodes themselves.

Thanks for the update!
I'll go ahead anc close this issue then since it doesn't seem to be coming from Gutenberg.
Feel free to reopen it if that is not the case :+1:
