### ISSUE TITLE
Expose the Global Styles precedence logic to an endpoint that native mobile editor can use

### ISSUE THREAD

**Issue by pinarol** [WordPress/gutenberg#25049]
`lib/global-styles.php` merges data from 3 sources:

- core defaults lib/experimental-theme.json
- theme defaults (experimental-theme.json found in the theme dir)
- user defaults (things the user saved through the global ui interface)

Later origins take precedence, so, for example, if the user has set up a font-size value for the paragraph block it'll take precedence from the value from the theme origin.

We need to extract the parts of lib/global-styles.php that makes sense for mobile to an endpoint.

**Prioritization:**

For the first iteration we are interested in supporting colors (text, background, links, gradients)

But it is important to keep an eye on spacing (margin, padding) settings for upcoming features, at least to make sure it is applicable on mobile.

More context: https://github.com/WordPress/gutenberg/issues/24165

**Comment by geriux** [comment]
Closing since this was implemented in https://github.com/WordPress/gutenberg/pull/29969
