### ISSUE TITLE
New PHP Warnings

### ISSUE THREAD

**Issue by ben72** [WordPress/gutenberg#25054]
**Describe the bug**
Since updating to 8.9 I get a lot of warnings from the gutenberg plugin. And it's the same in 8.9.1.
I get no warnings for the admin user though. But I do get them for woocommerce shop admin role.

For every pageload in admin I get this in the log:
`[03-Sep-2020 17:22:47 UTC] PHP Notice:  Undefined index: themes.php in /home/public_html/wp-content/plugins/gutenberg/gutenberg.php on line 58

[03-Sep-2020 17:22:47 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, null given in /home/public_html/wp-content/plugins/gutenberg/gutenberg.php on line 61

[03-Sep-2020 17:22:47 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/public_html/wp-admin/includes/plugin.php on line 1904`
The last line is repeated 18 times.

**To reproduce**
1. Login as shop admin
2. See log or on-screen warnings on every page in admin

**Expected behavior**
No warnings :)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- gutenberg plugin 8.9.1

**Comment by aristath** [comment]
It looks like there was a missing check, and when a user doesn't have access to the `Appearance` menu it throws an error.

Added a PR with a fix on https://github.com/WordPress/gutenberg/pull/25073 :+1:
