### ISSUE TITLE
Feature Request: jwplayer embed

### ISSUE THREAD

**Issue by carstenheisterkamp** [WordPress/gutenberg#2505]
[Jwplayer](https://www.jwplayer.com/) is a broadly used Video delivery platform which would be useful as an additional embed block. The default embed block can´t be used, since it provides Javascript as embed link or iFrame.

**Comment by youknowriad** [comment]
This is probably better raised as a Core Trac [ticket](https://core.trac.wordpress.org/).
AFAIK, adding an embed provider requires the provider to implement the `OEmbed` protocol and it should match these guidelines https://make.wordpress.org/core/handbook/contribute/design-decisions/#whitelisting-oembed-providers

**Comment by aduth** [comment]
This feels like plugin territory to me.

**Comment by iseulde** [comment]
@carstenheisterkamp Doesn't the Custom HTML block work for this? Maybe we need to make it a bit clearer that you can use it for embed codes too.

**Comment by carstenheisterkamp** [comment]
@iseulde yes, technically this works with both the js and the iframe embed code. But you won´t have a preview of the video in the Gutenberg editor and it doesn´t have the nice one click add usability.

**Comment by iseulde** [comment]
Does the preview button not work? Similar to the the embed block, you have to paste the code, then click preview? Maybe we should persist that though.

**Comment by carstenheisterkamp** [comment]
Just double checked it and honestly I totally overlooked the preview button... For iframe it works very well.  The js code doesn´t sho a preview. The JS looks like this
`<script src="//content.jwplatform.com/players/foUW87lp-e0pTZRtU.js"></script>`
Don´t know it has some advantages over the iframe.

Is a formatting left/right/center/wide/full  planned for the custom html block? This would help to define the width of the video. Currently it is full width only (or I am overlooking something again ;-) )

**Comment by iseulde** [comment]
Yeah, if we detect scripts we probably need to iframe it. This would work:

```html
<iframe srcdoc="&lt;script src=&quot;//content.jwplatform.com/players/foUW87lp-e0pTZRtU.js&quot;&gt;&lt;/script&gt;"></iframe>
```

Or we need a separate block for admins only that handles all of this.

**Comment by karmatosed** [comment]
I think this is dealt with the custom HTML block. If that is not the case, let me know and we can reopen.
