### ISSUE TITLE
InnerBlocks keep reverting to initial template when saving post

### ISSUE THREAD

**Issue by lmartins** [WordPress/gutenberg#25050]
**Describe the bug**
I'm setting a template on custom post type as follows:

```php
    $post_type->template = [
      [
        'gwm/product-main',
        [
          "className" => 'is-style-dark'
        ]
      ],
      [
        'gwm/product-claims'
      ],
      [
        'gwm/product-highlights'
      ]
    ];
    $post_type->templateLock = false;
```

The block `gwm/product-main`, the first one on the post template above, is set to have the following `InnerBlocks` template:

```js
const TEMPLATE = [['gwm/lifestyle-gallery'], ['gwm/media-panel'], ['gwm/product-tech']];
const ALLOWED_BLOCKS = ['gwm/lifestyle-gallery', 'gwm/media-panel', 'gwm/product-tech'];
```

And the `InnerBlocks` itself is called like this:

```js
      <InnerBlocks allowedBlocks={ALLOWED_BLOCKS} template={TEMPLATE} templateLock={false} />
```

The problem I'm seeing, and haven't seen this before in similar scenarios, is that if the user deletes some of the blocks inside `gwm/product-main`, those deleted blocks are brought back in automatically upon saving the post.

I assumed it could be something related to `templateLock`, but having set it to false on both the post type template, and this parent block properties, didn't changed this behavior.

**Editor version (please complete the following information):**
- WordPress 5.5.1
- Doesn't have Gutenberg plugin installed, is running the editor that comes with WP

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 85

**Comment by youknowriad** [comment]
I believe the sync behavior that can restore the template is only triggered if the templateLock is "all". I may be wrong though cc @jorgefilipecosta

**Comment by lmartins** [comment]
@youknowriad Sorry, I've figured out what was causing it. This particular block has InnerBlocks but also some attributes that render inline. The use case where this was happening was when the user removed all the blocks, but kept the inline elements with contents assigned to them. 
This would make the block look like it still had content, which it did, but the InnerBlocks was in fact empty, which triggered the system to reinstate the initial template.

So I believe this is expected behavior.

Thank you for looking into it though.
