### ISSUE TITLE
Classic block toolbar renders incorrectly when preceded by a left aligned image

### ISSUE THREAD

**Issue by cathymcbride** [WordPress/gutenberg#25059]
**Describe the bug**
Classic block toolbar renders incorrectly when preceded by a left aligned image

**To reproduce**
1. Start a new post
2. insert an image. 
3. Left align that image
4. insert the classic block - note toolbar

**Expected behavior**
Toolbar images are on the toolbar control

**Actual Behavior**
Toolbar images flow over the toolbar control onto the canvas

**Screenshots**
![image](https://user-images.githubusercontent.com/16654218/92155869-151a3c00-edf6-11ea-8c16-3d1b4bba4b09.png)
![image](https://user-images.githubusercontent.com/16654218/92160925-ca9cbd80-edfd-11ea-8a17-b4a29480fec6.png)
![image](https://user-images.githubusercontent.com/16654218/92161208-4a2a8c80-edfe-11ea-8e94-ef77b78be799.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 84.0.4147.125 (Official Build) (64-bit)

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ntsekouras** [comment]
Thanks for reporting this @cathymcbride ! I could reproduce it.

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this issue on the latest version of Gutenberg, please view the screenshot below:

<img width="716" alt="Untitled" src="https://user-images.githubusercontent.com/41231764/183715808-56599811-5ea4-4e19-89e6-ee512f176637.png">

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
