### ISSUE TITLE
Improve performance of List View drag and drop

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#25067]
**Describe the bug**
The performance for drag and drop in List View (currently enabled on the experimental navigation page) deteriorates significantly in relation to the number of blocks present, in contrast to the general editor canvas.

I've noticed a few things that can be improved. A big on seems to be that `useDropZone` is continually 

**To reproduce**
1. Open the experimental navigation page
2. Add lots of blocks (duplicating is the easiest way to do this)
3. Try dragging and dropping in list view

**Expected behavior**
Observe the updates to the drop zones and draggable chip become very laggy.

**Comment by StefanXhunga** [comment]
Hi All,
thank you for your help. Where can I find this? Open the experimental navigation page
Add lots of blocks (duplicating is the easiest way to do this)
Try dragging and dropping in list view
Please send me a link. I'm looking at [this](https://guides.github.com/features/mastering-markdown/)

**Comment by paaljoachim** [comment]
With the Gutenberg plugin installed.
Go to: Gutenberg -> Experiments. Enable Navigation screen.
Then go to Gutenberg -> Navigation (beta) screen.

Then in the Navigation screen click the black inserter + icon to add a block. In the Navigation structure or in the Navigation menu. I just clicked the + icon a bunch of times to insert empty links.

I am not able to drag and drop though. I can use the up and down arrows.

![Nav-screen-move-up-down](https://user-images.githubusercontent.com/5323259/92319317-e16a2c80-f016-11ea-8c52-481ad9261073.gif)

**Comment by talldan** [comment]
It'll be released in v9.0 of the Gutenberg plugin - https://github.com/WordPress/gutenberg/pull/23952.

In the meantime, I have begun working on optimizations in #25069. Let me know if there's any other info I can provide.

**Comment by priethor** [comment]
Hey @talldan, is this issue in your near future plans, or is it available to pick?

**Comment by talldan** [comment]
It can be picked up, not something that I plan on looking at soon.

Though, I did have a quick look at it recently but without success. I have a feeling a nice optimisation might be to switch to using an absolutely positioned separate element for the insertion point indicator, a bit like how the main block editor does now.

Currently dragging over the blocks updates each block to show a border to indicate where the block will drop and this seems quite slow.

**Comment by talldan** [comment]
Managed to get around to this now that widgets work has slowed down. #33320 is the PR.
