### ISSUE TITLE
Save post meta as an array or multidimensional array

### ISSUE THREAD

**Issue by christofervas** [WordPress/gutenberg#25070]
I am in the process of migrating meta boxes to block editor sidebars.

I have successfully followed this tutorial to create a sidebar for the block editor (https://developer.wordpress.org/block-editor/tutorials/plugin-sidebar-0/). 

My question is if there are any examples in the docs on how to save post meta as an array or multidimensional array? I searched on handbook and even online but I couldn't find any example.

**Comment by tellthemachines** [comment]
Hi there! The handbook only has the basic example with a string, but you can find examples of how to register meta as arrays or objects [here](https://make.wordpress.org/core/2019/10/03/wp-5-3-supports-object-and-array-meta-types-in-the-rest-api/).
