### ISSUE TITLE
Site Editor: Improve post content block and template visibility

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#25089]
**Note:**
When we say "template" in template visibility, we mean the part of the site editor template that doesn't belong to another entity. In other words, it's the area between our template parts and post content.

**Is your feature request related to a problem? Please describe.**
Related to this [issue](https://github.com/WordPress/gutenberg/issues/22064) and this [comment](https://github.com/WordPress/gutenberg/issues/24881).

It's difficult to discern where the post content block and template begins and ends in the site editor. It also seems unintuitive to navigate seamlessly between template parts, the template area, and post content in the site editor. 

It's important to call out that the editing experience may improve when Shaun's changes to the topbar are implemented (#25085) alongside a persistent block navigator (https://github.com/WordPress/gutenberg/issues/22113). As a result, this issue is acting as more of a placeholder to ensure that, when [template part visiblity is improved](https://github.com/WordPress/gutenberg/issues/22064), the template area and post content block editing experience are addressed as well.

**Comment by Addison-Stavlo** [comment]
**Post Content** I feel the needs of this block are very similar to that of the Template Part.  So whatever fits the needs of the template part should ideally fit the needs of the post content (whether persistent block navigator and breadcrumb names are sufficient on their own, or we need to add other indicators like borders, labels, scrims, spotlights, etc., my feeling is that these two blocks will require the same sort of indications).

**Template areas** may be a bit different though, as the two blocks mentioned above are children of the Template.  So if there is a need for visual indications (beyond block navigator and breadcrumb names), those visual indicators will definitely be a bit different.  Perhaps, if we do something like apply a very light border around template part and post content when working within them then a solution for the Template area could be to triggers those light borders to appear for the Template Parts/Post Contents on the page.  This kind of thing might make it more clear where you are working on the page.

That said:

>It's important to call out that the editing experience may improve when Shaun's changes to the topbar are implemented (#25085) alongside a persistent block navigator (#22113). As a result, this issue is acting as more of a placeholder to ensure that, when template part visiblity is improved, the template area and post content block editing experience are addressed as well.

It does sound like a good idea to assess this after we see where our weak point are after the above is implemented.

**Comment by annezazu** [comment]
I am closing this out after an immense amount of work has gone into clarifying the relationship between the content and the template: https://github.com/WordPress/gutenberg/pull/51366 https://github.com/WordPress/gutenberg/pull/51364 https://github.com/WordPress/gutenberg/pull/50857 There is no clarity both in terms of interfaces nudges when you click on a template while editing post content and to switch between the two. If I missed something here though, let me know and I'm happy to reopen!
