### ISSUE TITLE
Selecting an existing menu for the Navigation Block doesn't create links

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#25087]
**Describe the bug**

When adding the navigation block and choosing an existing menu, the block doesn't bring the links over into the menu causing the menu to be added without any links. 

**To reproduce**
1. Turn on all gutenberg experiments in Gutenberg > Experiments
2. Create a menu under Gutenberg > Navigation (beta) and make sure to link to items
3. Head to the Site Editor (beta)
4. Add the navigation block and choose to select from an existing menu
5. Hit publish and try to select menu items only to find nothing is linked. 

**Expected behavior**

I expected the navigation block to include the links I added in the navigation screen including after editing the menu items after adding the block. 

**Screenshots**

Here's a video of me talking through the experience: https://cloudup.com/cvhi8PkkoJZ

Here's a screenshot showing that I did indeed add links in the Navigation Screen before adding the navigation block to the Site Editor:

<img width="746" alt="Screen Shot 2020-09-04 at 1 07 11 PM" src="https://user-images.githubusercontent.com/26996883/92277712-cda4b600-eeb0-11ea-9948-363d3262d866.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.9.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 84.0.4147.135

**Comment by aristath** [comment]
I get the same thing on my end, bug confirmed :+1:

**Comment by carladoria** [comment]
reported in 3339235-zen

**Comment by LauraSWP** [comment]
Hi! I see this closed but it still doesn't work on AT sites

**Comment by talldan** [comment]
Hi @LauraSWP, the code for the fix has only just been merged as of an hour ago. The fix will be in the next Gutenberg release, v9.1. That should be released next Wednesday.

**Comment by LauraSWP** [comment]
Thanks!
