### ISSUE TITLE
REST API: Audit menus route filters.

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#25095]
We need to make sure that menus and menu items are having the correct filters applied when being saved.

Something that stood out to me was the `_save_pre` filters in `prepare_item_for_database`, https://github.com/WordPress/gutenberg/blob/458277c376d9b0402ea04034a055c98d7e18625e/lib/class-wp-rest-menu-items-controller.php#L516. To me it looks like those filters are duplicates, since they will eventually be applied when `wp_insert_post` calls `sanitize_post`. The `wp_update_nav_menu_item` function does takes care of moving `menu-item-title` and friends into their correct variable names for `wp_insert_post`. Of note, we don't apply these filters in the base `WP_REST_Posts_Controller` class.

There may be other instances, but I didn't find any in a cursory glance. It'd be good to have another set of eyes or two to look over the code path as well.

**Comment by spacedmonkey** [comment]
The lines are copied from [here](https://github.com/WordPress/wordpress-develop/blob/2382765afa36e10bf3c74420024ad4e85763a47c/src/wp-includes/customize/class-wp-customize-nav-menu-item-setting.php#L715-L722).
