### ISSUE TITLE
Problem with shortcode block inside reusable block

### ISSUE THREAD

**Issue by jvlianodorneles** [WordPress/gutenberg#25097]
**Describe the bug**
When Gutenberg plugin version 8.9.1 is active, when a shortcode is inserted, it and the rest of the content of the reusable block isn't shown.

**To reproduce**
1. Create a reusable block with some content and a shortcode block;
2. Insert reusable block in post.
3. See error

**Expected behavior**
Execute the shortcode inserted (script).

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg plugin version: 8.9.1

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 32)
 - Browser: Chrome (85.0.4183.83), Firefox (80.0.1).

**Comment by joshm33333** [comment]
can confirm. spent an hour trying to figure out what i did wrong, just to find out it was that i accidentally installed the plugin.

**Comment by annezazu** [comment]
@jvlianodorneles I tried to replicate this using the WP Call Button plugin as an example but wasn't able to do so. Every time the reusable block worked no matter the order. Can you share screenshots or explain which shortcode you were using that caused this? It'll help with testing. Thank you!

**Comment by annezazu** [comment]
@jvlianodorneles closing this out for now since I haven't heard back from you. Feel free to reopen with screenshots and/or more context!

**Comment by joshm33333** [comment]
Huh... I was waiting for an answer
I'll see if I can provide screenshots, maybe WordPress resolved this in an update.
