### ISSUE TITLE
Hebrew + Chrome. Galleries on Classic block disappear when you try to edit them

### ISSUE THREAD

**Issue by rantoncuadrado** [WordPress/gutenberg#25098]
**Describe the bug**
When you click the gallery inside a classic block to be able to edit it, the gallery disappears. 

You can click the pencil and make changes in the gallery (there are pop up windows for that) but the content does not show when I finish. only when you leave the page and go back again - the content appears

**To reproduce**
1. Set your account settings to Hebrew 
2. Click on a post with a gallery inside a classic block on it.
3. Click on the gallery to edit it.
4. The error happens

**Expected behavior**
I expected the gallery to be editable.

**Screenshots**
![screencast 2020-09-06 07-40-16](https://user-images.githubusercontent.com/6404071/92319133-a5829780-f015-11ea-9b50-ab51b33dd684.gif)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS:  OS X 10.15 
 - Browser Chrome v85 ( whatsmybrowser.org/b/FW6A1 )
Issue also reported on windows 10 home 1903 Ver. , google chrome Version 85.0.4183.83

The issue DOES NOT happen on Firefox 80 whatsmybrowser.org/b/5NJYN

**Comment by annezazu** [comment]
I was able to replicate this using Gutenberg 9.0 and WordPress 5.5.1. Here's a quick GIF showing me trying to click into the classic editor block: 

![hebrew](https://user-images.githubusercontent.com/26996883/94094966-fb10bf80-fddd-11ea-8e69-38fb222b5967.gif)

**Comment by tellthemachines** [comment]
I can reproduce this issue in English too, in both Chrome and Safari, but not Firefox:

<img width="707" alt="Screen Shot 2020-09-29 at 2 07 36 pm" src="https://user-images.githubusercontent.com/8096000/94511746-97631800-025d-11eb-899e-59fb1247683a.png">

**Comment by sophiegyo** [comment]
I'm also seeing this issue with English in Safari, but not Firefox:

https://user-images.githubusercontent.com/36608681/116221223-b3745c80-a74d-11eb-9bf1-2855b46ba335.mov

Tested with:

WordPress v. 5.71
Twenty Twenty-One v. 1.3
Safari v14.1
Mac OS v11.3
No extra plugins, including Gutenberg though

**Comment by ramonjd** [comment]
Is this issue still relevant? Looks like the classic block renders the gallery shortcodes fine in the overlay?

Just tested with latest Gutenberg on WordPress 6.5 (in Hebrew and English):


https://github.com/WordPress/gutenberg/assets/6458278/b5354693-45e7-43d8-ac92-a03e53d2211c

I'll close just in case, but please reopen if it's still an issue.
