### ISSUE TITLE
Editor: Format bar isn't available when you select more than 1 block

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/gutenberg#25091]
For writers, is vital to be able to apply formats to text in 2 or more blocks, but when you select more than 1 block the format bar isn't available.

Please, consider the writers with the changes to the "editor"

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/27221. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in that issue.
