### ISSUE TITLE
Embeds: pasting a non-embeddable Facebook URL throws a TypeError

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#25108]
**To reproduce**
Start editing a post and paste the following URL:
```
https://www.facebook.com/informationisbeautiful/
```
It's a link to a Facebook page that is not embeddable. The oEmbed Proxy REST request returns a response with `html: false`:

<img width="690" alt="Screenshot 2020-09-07 at 12 24 50" src="https://user-images.githubusercontent.com/664258/92377933-384e2f80-f105-11ea-9b24-c8581deb998e.png">

This then leads to an error being reported in console:

<img width="586" alt="Screenshot 2020-09-07 at 12 28 38" src="https://user-images.githubusercontent.com/664258/92378199-b579a480-f105-11ea-9a30-bb0f2699b82d.png">

The offending function is [isFromWordPress](https://github.com/WordPress/gutenberg/blob/84cbc5f04fb0585e40c6699f024d4899ca287e84/packages/block-library/src/embed/util.js#L65) that calls `html.includes()` on its `html` argument that is `false`.

The embed block UI then ends up like this:

<img width="620" alt="Screenshot 2020-09-07 at 12 24 59" src="https://user-images.githubusercontent.com/664258/92377949-3dab7a00-f105-11ea-8baa-bf42625fe40c.png">

**Expected behavior**
When testing on WordPress.com or on a self-hosted WordPress 5.4.2 with default editor, I see something more correct:

<img width="586" alt="Screenshot 2020-09-07 at 12 13 04" src="https://user-images.githubusercontent.com/664258/92377691-d261a800-f104-11ea-8ab8-07907a21b1c1.png">

The fact that this works correctly with older versions of Gutenberg that are not bleeding edge suggests the bug is a recent regression. Maybe the refactoring in #24090 by @ntsekouras is the cause?

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? built from `master`

**Comment by ntsekouras** [comment]
Hey @jsnajdr thanks for reporting this. This seems to need a bit more investigation but maybe the removal of support for facebook embeds here: https://github.com/WordPress/gutenberg/pull/24472 might be involved.

**Comment by jsnajdr** [comment]
> Also just pasting your provided url in creates a `code` block for me..

I'm simply copy&pasting a URL from the browser URL bar. The `code` block is triggered by the triple-backtick Markdown formatting I used to write the URL in the issue description. Maybe you're doing some rich-text copy&paste that copies the formatting, too? That looks like a plausible way how the `code` block could be triggered.

**Comment by ntsekouras** [comment]
>The code block is triggered by the triple-backtick Markdown formatting

Yes that was the case 👍, my bad, but it's the same as trying to create an `embed` block due to the embed block's transformations.

**Comment by jsnajdr** [comment]
@ntsekouras It seems to be caused by #24090 after all, namely the refactor that replaced Lodash `includes( html, x )` with `html.includes( x )`. See the fix in #25140.

**Comment by ntsekouras** [comment]
Thanks @jsnajdr for looking into it and for the fix! I approved your fix there 💯
