### ISSUE TITLE
Insert a block after Title

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#25119]
Is there some trick to make it ? I know how to insert block and "drag" it under Title.

**Comment by ntsekouras** [comment]
Hey @StaggerLeee. You can just press enter when you have clicked your title (focus is there), or you can use the main block appender on the top left of your screen. Does this answer your question or there was some other case?

![Screenshot](https://user-images.githubusercontent.com/16275880/92583748-79784800-f29b-11ea-9f60-02cb46273798.png)

**Comment by StaggerLeee** [comment]
Ah, "Enter", thank you. Make something for all those poor souls who work not with keyboard. If I could not find it it means I have to send screenshots to them and explain.

Show little plus icon above first block (under title). I don´t know what is the problem and you decided against it.
People use to put some story updates right after title when changing article with time.

**Comment by ntsekouras** [comment]
> Show little plus icon above first block (under title). I don´t know what is the problem and you decided against it.

I don't have all the context for these design decisions, but I can think that `title` shouldn't be confused for a `content like block`. Glad I could help!
