### ISSUE TITLE
Coding Standards: Naming conventions for abbreviated camel-case

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2511]
How should we capitalize [abbreviations](https://en.wikipedia.org/wiki/Abbreviation) and [acronyms](https://en.wikipedia.org/wiki/Acronym)? This is an area where Core [JavaScript Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#naming-conventions) are not prescriptive (but perhaps should be).

For example, in assigning a user ID variable, which is preferable:

- `userId`
- `userID`

The language / DOM are not especially consistent here:

- [`decodeURI`](http://www.ecma-international.org/ecma-262/5.1/#sec-15.1.3.1)
- [`getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)
- [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) :scream:

There was a similar discussion in developing adapted standards in Calypso, resulting in camel-case covering abbreviations and acronyms:

https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#naming-conventions

The reasoning being: It simplified the documentation and thought-process to recommend camelCase for _everything_, including abbreviations and acronyms.

In retrospect, the language itself is quite consistent on upper-cased abbreviations and acronyms (`getElementById` and `XMLHttpRequest` are browser-specific additions). Anecdotally, other libraries tend toward the same, e.g. `ReactDOM`, `TinyMCE`. I've started to adopt this in my Gutenberg work ([`withAPIData`](https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-api-data)), but I feel we should formalize one way or the other, and update inconsistencies ([`withInstanceId`](https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-instance-id)).

_Yes, this is a bikeshed._

**Comment by mtias** [comment]
Going to close this :)

**Comment by aduth** [comment]
Effectively closed by #7670.
