### ISSUE TITLE
Document how to disable the block-editor specifically for the widgets

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#25123]
**Describe the bug**

[The default interface for editing widgets is now the block-editor for Gutenberg plugin users](https://make.wordpress.org/core/2020/09/03/whats-new-in-gutenberg-2-september/); theme developer documentation should include how to disable this in a case a user wishes to use the classic interface. 

_["Themes and plugins are able to opt out of this screen by calling remove_theme_support( 'widgets-block-editor' ) or by using the gutenberg_use_widgets_block_editor hook"](https://make.wordpress.org/core/2020/09/03/whats-new-in-gutenberg-2-september/)_  - Jorge Costa

It is also been mentioned at that this can be done through `add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );` (REF https://github.com/WordPress/gutenberg/issues/25483)

**Expected behavior**

The [theme support page](https://developer.wordpress.org/block-editor/developers/themes/theme-support/) has become a defacto place where all of the `remove_theme_support` and `add_theme_support` issues that have been implemented with gutenberg are listed. 

Should/Could this be documented there or elsewhere? 

**Editor version (please complete the following information):**
- WordPress version: N/a
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin"]
- If the Gutenberg plugin is installed, which version is it? 8.9

**Comment by draganescu** [comment]
[This PR](https://github.com/WordPress/classic-editor/pull/137) aims to allow disabling via plugin. For other situations there is also a theme supports, that though seems to be limited when trying to disable things in the Customizer.

**Comment by noisysocks** [comment]
> The [theme support page](https://developer.wordpress.org/block-editor/developers/themes/theme-support/) has become a defacto place where all of the `remove_theme_support` and `add_theme_support` issues that have been implemented with gutenberg are listed.

Sounds good. Let's add documentation for `remove_theme_support( 'widgets-block-editor' )` to this page.

**Comment by draganescu** [comment]
I would to remove the theme supports. Having a filter is enough.

**Comment by adamziel** [comment]
@draganescu what should happen to this issue if we do that?

**Comment by draganescu** [comment]
It is still unclear how to best opt out.

**Comment by noisysocks** [comment]
> It is still unclear how to best opt out.

See https://github.com/WordPress/gutenberg/issues/26154#issuecomment-815436775.

**Comment by noisysocks** [comment]
Closing this as the docs added in https://github.com/WordPress/gutenberg/pull/31577 contains a page with a few different ways to disable the new editor.

We have not yet decided if the new editor will be opt in or opt out. That decision is tracked by https://github.com/WordPress/gutenberg/issues/26154.

**Comment by msshohan** [comment]
remove_theme_support( 'widgets-block-editor' ) is not restoring the classic widget editor screen for me. Any explanation why this may happen?
