### ISSUE TITLE
Media upload component does not select or highlight a file in the media library.

### ISSUE THREAD

**Issue by ThatStevensGuy** [WordPress/gutenberg#25129]
**Describe the bug**
I am using a duplicate of the Post Featured Image component for a Newsletter attachment which saves to its own post meta.

However I noticed that the value prop of [MediaUpload](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/media-upload) does not select the file in the media library.

The only way I could get this to happen is to use the unstableFeaturedImageFlow prop, but this is not ideal as it changes the modal to have the wording for a Featured Image - so I had to remove it and live with the file not being pre-selected.

I think this could be fixed by extending the MediaUpload component myself, but its a bit beyond my knowledge at this point. I also don't understand why it should be necessary when the [README](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/media-upload/README.md) for the Media Upload component says:

**value**
Media ID (or media IDs if multiple is true) to be selected by default when opening the media library.

**To reproduce**
Make a duplicate of the Post Featured Image component in your own custom sidebar panel. Remove unstableFeaturedImageFlow prop and rely on just the value prop to select the file in the media library.

**Expected behavior**
Value prop of MediaUpload should select the file in the media library using the ID.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Comment by tony47** [comment]
Hello @ThatStevensGuy , we are experiencing the same issue while having AMP plugin installed. If we disable it, MediaUpload block works as expected. 

Do you have AMP plugin installed too?

**Comment by ThatStevensGuy** [comment]
@tony47 You seem to be on to something! I am using AMP and this issue resolves when the AMP plugin is disabled.

But who is at fault here, is it AMP or WordPress/Gutenberg MediaUpload component?

**Comment by tony47** [comment]
@ThatStevensGuy , that's a good question. 

I'm not familiar with either Gutenberg or AMP internals, but I discovered that commenting-out this line in AMP plugin, resolves the issue:

https://github.com/ampproject/amp-wp/blob/d0cceb54d60f3a7cfaf68ad4584be4ced2d5d50e/assets/src/block-editor/index.js#L35

Hope it helps.

**Comment by westonruter** [comment]
AMP plugin issue: https://github.com/ampproject/amp-wp/issues/5379. Fixed via https://github.com/ampproject/amp-wp/pull/5412. This will be part of AMP plugin v2.0.4, which we are releasing today.
