### ISSUE TITLE
Try using transient attributes on global styles entity

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#25138]
Follow-up https://github.com/WordPress/gutenberg/pull/24250#discussion_r482224681

The idea would be that we store the transient edits as objects within the entity, so we don't have to serialize/deserialize from a string, which is how it's stored in the CPT.

**Comment by jordesign** [comment]
@oandregal @jorgefilipecosta Just looping back through some inactive issues - just wanted to see if this is still a task/enhancement that needs follow through?

**Comment by oandregal** [comment]
This API has changed quite a bit, so this can be safely closed.
