### ISSUE TITLE
How to absorb font size units

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#25137]
Follow-up https://github.com/WordPress/gutenberg/pull/24250#discussion_r470021463

In developing the Global Styles sidebar, we ran into the issue of having to convert to/from units the font size property. The issue is that font size values are [serialized](https://github.com/WordPress/gutenberg/blob/master/packages/element/src/serialize.js#L336) as px values in the post editor, so we did the same for the site editor.

This makes it so the global styles sidebar has to absorb that processing from theme.json data, which was done via [utility functions](https://github.com/WordPress/gutenberg/blob/5eed5c530a2deb04ebb775bf4663aa6a9951cd15/packages/edit-site/src/components/editor/utils.js#L22) `fromPx`/`toPx`.

This is to discuss further steps on how to best manage font-size units. Can we make it so that the UI component is responsible to absorb this complexity?

**Comment by nosolosw** [comment]
cc @ItsJonQ @jorgefilipecosta

**Comment by nosolosw** [comment]
Related issue https://github.com/WordPress/gutenberg/issues/23323

**Comment by jorgefilipecosta** [comment]
It seems like we should expand the font size picker to accept values containing units. Being back-compatible when a value is a number it assumes it is a pixel unit value.

**Comment by mtias** [comment]
Do we have anything pending here?

**Comment by jorgefilipecosta** [comment]
> Do we have anything pending here?

I don't think so. I'm going to close the issue.
