### ISSUE TITLE
Support custom gradients in Global Styles sidebar (edit-site)

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#25136]
Follow-up from https://github.com/WordPress/gutenberg/pull/24250

Add support for custom gradients to the global styles sidebar in edit-site. When enabled, it caused the gradients panel to stop working once the user interacted with it.

**Comment by jorgefilipecosta** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/25159.
