### ISSUE TITLE
Iterate on global styles sidebar (Site Editor)

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#25139]
Related https://github.com/WordPress/gutenberg/issues/20212

After landing https://github.com/WordPress/gutenberg/pull/24250 users can tweak and update theme styles via a sidebar in the site editor that looks like this:

![2007-28-2119-global-styles-edit-site](https://user-images.githubusercontent.com/583546/88711364-5e50df00-d118-11ea-905d-e3aa6a8b3431.gif)

This task is to iterate on the current screen.

**Comment by ItsJonQ** [comment]
👋 Haii! I'm happy to help with this one, especially if any of the designs/tools may involve G2 components :D

https://github.com/ItsJonQ/g2

**Comment by jorgefilipecosta** [comment]
I guess we can close this issue in favor of https://github.com/WordPress/gutenberg/issues/27473. That is more up to date.
