### ISSUE TITLE
When clicking into long blocks, the screen "jumps"

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2514]
Gutenberg v0.9

## Issue Overview
When clicking into the bottom of a longer block, the screen jumps around. This is best seen from a gif. 

![guten-jump](https://user-images.githubusercontent.com/622599/29635695-bf59d5ac-881b-11e7-85ad-8867072da1cc.gif)

## Expected Behavior
Clicking into a block shouldn't cause the screen to scroll at all.

**Comment by karmatosed** [comment]
I have been trying to recreate this and can't in 1.1.0. That doesn't mean it's simply me failing to recreate. Could you please try using the latest version and maybe we can dive into some steps otherwise. Was there a particular browser maybe?

**Comment by karmatosed** [comment]
I have tried again to recreate this using the latest build. I am unable to. In light of this, going to close but happy to reopen.
