### ISSUE TITLE
Warning: A non-numeric value encountered 

### ISSUE THREAD

**Issue by inessenceva** [WordPress/gutenberg#25146]
**Received warning in front page**
Warning: A non-numeric value encountered in /home1/stevenjklotz/public_html/wp-content/plugins/gutenberg/lib/block-supports/index.php on line 64

Did not expect anything to happen when updated the plugin

**Screenshots**

Version: 8.9.2
Author: Gutenberg Team
Last Updated: 20 hours ago
Requires WordPress Version: 5.3 or higher
Compatible up to: 5.5.1
Requires PHP Version: 5.6 or higher

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Google Chrome is up to date
Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by inessenceva** [comment]
GeneratePress

**Comment by pedro-rivera** [comment]
People, facing the same problem only in online test environment, locally works perfect. Using 9.0.0 the error is in the same file but in **line 66**. Using Blocksy theme.

**Comment by skorasaurus** [comment]
Hi, I'm unable to reproduce this using the blocksy theme with Gutenberg 9.8.1; could you report if you're still experiencing this issue with the latest release of Gutenberg?

**Comment by miminari** [comment]
This was discussed during [a triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1619503040354400).

Seeing no response, we feel it is okay to close this. Thank you!
