### ISSUE TITLE
Widgets: Dropdown Menu's background is transparent 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#25155]
**Describe the bug**
The dropdown menu of the is transparent; making it very difficult to read. 

**To reproduce**
1. Go to wp-admin/customize.php?return=%2Fwp-admin%2F
2. Click on Widgets (or Widget Blocks
3. Select widget area and open it
4. select a block that's already in the widget; open the widget's toolbar, select the three dots (I forget the name of this). 

**Expected behavior**
Dropdown Menu's background should not be transparent. 

**Screenshots**
![Selection_012](https://user-images.githubusercontent.com/955351/92490053-8410df80-f1be-11ea-95a4-fda92eacfd22.jpg)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.0+] (observed in 5.5.0 and 5.5.1)
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin 
- 8.9.2 of the plugin; I'm also able to reproduce this in a build from earlier today, 2020-09-08, last commit being f62d144575863e563424590440f27b211e054eb6

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]
 - Browser [firefox] (haven't tested other browsers)
- 80.0.1

**Comment by sbappan** [comment]
Hi. Could I please work on this issue?

**Comment by skorasaurus** [comment]
> Hi. Could I please work on this issue?

You're certainly welcome to and we'd appreciate it. 

If you haven't contributed to the block editor before, check out the https://github.com/WordPress/gutenberg/blob/master/docs/contributors/develop.md ; 
If you have additional questions or need guidance, you can reply in here.

You can also get live assistance in the WordPress slack; specifically the core-editor channel. https://make.wordpress.org/chat/

**Comment by kevin940726** [comment]
I think #25201 will makes this obsolete? Since there will no toolbar above the block anymore.

**Comment by annezazu** [comment]
I agree with @kevin940726 and am going to close this out while noting on #25201 that designs need to be built with the three dot items in mind (forgot the name of this too 😅).
