### ISSUE TITLE
Widgets: Unable to edit existing content of widgets in customizer

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#25157]
**Describe the bug**
I cannot edit the content of legacy widgets (within the customizer).

I had expected that content made using the old customizer widget screen would be able to be editable with the new block-based widget editor. 

I would suggest that: 

1. legacy widgets' content could be edited as a classic block and users given the option to convert content to modern blocks similar to how content written in TinyMCE appears as a classic block and then can be converted into individual blocks. 

2. Or failing that, the content would automatically be converted to blocks; 

**To reproduce**
1. Go to wp-admin/customize.php?return=%2Fwp-admin%2Fupdate-core.php
2. go to widget blocks
3. open an area that contains an existing widget

Possibly related to #15916, #25154

**Expected behavior**
Be able to edit widgets' content that already existed in the editor; this is especially imperative since users are currently 'stuck' with the new block-based widget editor ( #24949 )

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? using 8.9 and 8.9.1

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Workaround:** You are able to edit the widgets' contents if you visit: wp-admin/themes.php?page=gutenberg-widgets

**Comment by skorasaurus** [comment]
upon more searching, very similar to #25100 but I'm asking for the possibility to also edit the content of existing widgets as well.

**Comment by draganescu** [comment]
Related #25153

**Comment by adamziel** [comment]
Blocked by https://github.com/WordPress/gutenberg/issues/25625

**Comment by noisysocks** [comment]
We're redoing our implementation of how blocks work in the Customizer (see #26900) so that it will be possible to edit blocks including the Legacy Widget block in the Customizer. Going to close this out in favour of the other issues which track this effort.
