### ISSUE TITLE
Link color doesn't work for author role

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#25151]
How to test:

- Install the [Seedlet theme](https://wordpress.org/themes/seedlet/), or any other theme that has support for the [link color feature](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#experimental-%e2%80%94-link-color-control).
- As an author role, go to the post editor and add a paragraph with a link.
- Change the link color via the block settings.
- Publish post.

The expected result is that the paragraph, in the front-end, has the class `has-link-color` and also has inlined the style for the color such as `style="--wp--style--color--link:<some-color-here>"`. What happens instead is that the CSS custom property isn't present.

**Comment by nosolosw** [comment]
This probably needs checking against the `unfiltered_html` capability as different setups may have different role-capabilities mappings.

**Comment by mcsf** [comment]
Whatever the fix, I recommend adding an E2E test, however small. That way it's guaranteed to be tested by CI against both admin and author roles.

**Comment by oandregal** [comment]
Related https://github.com/WordPress/gutenberg/issues/31488 (will be fixed if/when that approach lands)

**Comment by oandregal** [comment]
This has been fixed by landing https://github.com/WordPress/gutenberg/pull/31524
