### ISSUE TITLE
Gallery Block: 2 columns showing stacked

### ISSUE THREAD

**Issue by jackiejade** [WordPress/gutenberg#25156]
**Describe the bug**
When a gallery block is added to a page or post and has 2 columns, the images are showing as stacked on desktop instead of side-by-side.

**To reproduce**
1. Go to Site > Posts (or Pages)
2. Click on + to add a Gallery block
3. Insert two images
4. Set columns to 2 in block settings

**Expected behavior**
Expect the images to display side-by-side (as they show in the editor) on the preview/live site.

**Screenshots**
In the editor:
![preview in editor](https://d.pr/i/EEJGoi+)

Live site:(the image is large so I couldn't get the full thing in a screenshot)
![live site](https://d.pr/i/PwZGs5+)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default block editor

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Browser Firefox
 - Version 80.0.1

**Additional context**
We have a temporary work around with CSS thanks to Ed!
```
/* fix 2-column gallery item display on larger screens | #XXXXXX-hc eD */
@media screen and (min-width: 560px) {
	.wp-block-gallery.columns-2 .blocks-gallery-grid {
		flex-wrap: unset;
	}
}
```

**Comment by RealCarFax** [comment]
I just had another report of this in #22546467-hc. I gave them the CSS work-around stated above. I was able to replicate this issue while I had Exford active on my testing site, but not while Aquene was active.

**Comment by ntsekouras** [comment]
Hi @jackiejade! Thanks for reporting this!

I wasn't able to reproduce this with some default themes like 2020 2019. Could it be some styles applied from the theme you're using? Can you please try this with another theme to verify the behaviour?

**Comment by jackiejade** [comment]
@ntsekouras I experienced this with Exford and Mayland.

Just tested in Balasana, Leven, Alves and it was not working (it displayed stacked)

Testing in Seedlet and Radcliffe2 the gallery block works as expected and displays correctly.

Perhaps this is something to do with the Varia themes. I can move it over to that repo. Thanks!

**Comment by jackiejade** [comment]
Moved here: https://github.com/Automattic/themes/issues/2437
