### ISSUE TITLE
File watcher not detecting changes

### ISSUE THREAD

**Issue by redstar504** [WordPress/gutenberg#25167]
**Describe the bug**
When running `npm run dev` on Ubuntu 18.04, the file watcher is not able to detect changes made to any source javascript.  It displays the standard webpack output and the `Waiting for changes...` message, however the expected re-build behaviour does not occur.

**To reproduce**
1. Clone wordpress/gutenberg to a local directory
2. Run `npm install` from cloned directory.
3. Run `npm run wp-env start`
4. Run `npm run dev`

**Expected behavior**
Changes made to package sources, such as `packages/block-library/src/latest-posts/index.js` should trigger a rebuild when saving the file's changes.  Changes do not appear to be detected and re-build does not occur.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- If the Gutenberg plugin is installed, which version is it? 8.9.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS

**Comment by mkaz** [comment]
@redstar504 Can you try increasing the max file count?

Per this documentation here:
https://dev.to/rubiin/ubuntu-increase-inotify-watcher-file-watch-limit-kf4

The command would be:

```
echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

**Comment by redstar504** [comment]
@mkaz Thank you for the reply.  It seems like it may have been package related.  When I updated the `node-watch` package to 0.6.4 (dev-master), it resolved my issue.  There seems to be a problem with file watching on some distros of Linux, and the node-watch package was throwing errors for unsupported environments.  These errors seemed to happen silently when used by the dev:packages function.  I am still not 100% sure on why it now works with the newer version of node-watch, however it looks like they stopped throwing errors for OSes that don't support recursive file watching, and instead passed the error handling on to lower level packages.
