### ISSUE TITLE
Conflict between Theme Customizer and Gutenberg plugin

### ISSUE THREAD

**Issue by jagy-2a** [WordPress/gutenberg#25166]
Hi!
The Theme Customizer will not load at all since the last Gutenberg plugin update. 
 
I deactivated all the plugins and reactivated them one by one and the problem is definitely the Gutenberg plugin.

I'm using Wordpress 5.5.1
There is no problem with the server.
the Gutenberg plugin is  Version 8.9.3 

I hope you have a solution.  Thanks!

**Comment by carolinan** [comment]
Hi, 
did you also try several different themes?

**Comment by jagy-2a** [comment]
Hi Carolinan,
Yes I tried several other themes, mostly Twenty... and I have the same problem.  The only thing that seems to work is deactivating Gutenberg but all my pages are built with it.  I also noticed several widgets disappeared.

**Comment by philrp** [comment]
Updating to Gutenberg 9.0.0 has caused serious customizer display issues under the Astra theme 2.5.5.

I tested a few other themes: the Twenties, Storefront and Neve, and none of those seem to have issues.

I have filed a ticket with Astra, but thought best to report here too.

Best

**Comment by bph** [comment]
@jagy-2a As the new widget screen is probably the culprit, I was wondering (and double-checking) if you added this to your theme functions page(s): `remove_theme_support( 'widgets-block-editor' );`

**Comment by jagy-2a** [comment]
@bph  Hi Brigit. No, I didn't add anything to my theme function page. 
Nevertheless, I deleted the Gutenberg plugin and everything is working fine now.  Thanks

**Comment by bph** [comment]
Ah ok. You are welcome.  @jagy-2a Let's  close this issue, them. We can always get back to it and open it again, if you run into this problem again.
