### ISSUE TITLE
wp-env: Enable to configure the PHP version

### ISSUE THREAD

**Issue by leoloso** [WordPress/gutenberg#25175]
**Is your feature request related to a problem? Please describe.**
My plugin requires PHP 7.4, so I can't use `wp-env` since it installs (I believe) PHP 7.3, and the `wp-env` configuration file does not allow to define the PHP version.

**Describe the solution you'd like**
Add entry `phpVersion` to `.wp-env.json` to specify the PHP version: `"8.0"`, `"7.4"`, `"7.3"`, etc. Then, the Docker container will install this PHP version.

**Comment by timnolte** [comment]
@leoloso I noticed this line in the setup: https://github.com/WordPress/gutenberg/blob/97dc7760c2655add01b5d81e22b460759b207c86/packages/env/lib/build-docker-compose-config.js which eludes to the fact that you could possibly set `LOCAL_PHP` to the PHP version you need. I'm not sure if putting that in the `.wp-env.json` file would possibly set that or not. The Docker setup is definitely configured to look for that. You might even just set that on your local machine as an Environment variable and it may in fact work as you need.

**Comment by timnolte** [comment]
@leoloso so actually that is only being used for the PHPUnit docker container. I can see various items here that I think I'm going to see about submitting PRs for unless something has already been submitted. It would be nice to have this available to also use these environments inside of Travis CI for example where I am also testing a matrix of WordPress & PHP Versions.

**Comment by timnolte** [comment]
@karmatosed can you add the "[Package] Env" label to this as well? Thanks!

**Comment by charanjit-singh** [comment]
Why was this closed?

**Comment by timnolte** [comment]
@charanjit-singh this feature was added which is why this was closed.

**Comment by charanjit-singh** [comment]
@timnolte  any links to the docs?

**Comment by timnolte** [comment]
@charanjit-singh have you looked at the package documentation? https://www.npmjs.com/package/@wordpress/env#wp-envjson

**Comment by charanjit-singh** [comment]
Thank you so much! I'm very new to Wordpress. I hop you understand.
