### ISSUE TITLE
Can't change selected text Font-size/Font-family in paragraphs.

### ISSUE THREAD

**Issue by zurashaa** [WordPress/gutenberg#25189]
The new Gutenberg editor doesn't allow changing selected text font-size, font-family and colors inline. It was easily possible in old classic editor. I found some plugins that provide changing colors/background-colors inline but none of them allow changes on Font-size and Font-family.

Does anyone have this issue resolved?

**Comment by skorasaurus** [comment]
(fwiw, I'm not sure if this should be enabled by default, it can lead to some really poor designs if implemented).

**Comment by jordesign** [comment]
I'd agree that this decision is by design - and as such this is a wontfix. Given the lack of activity on this issue over the last few years, I'm going to close it out.
