### ISSUE TITLE
The more menu in customizer is transparent

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25199]
Trying to edit a block in the Block Widgets section of the Customizer (with the new Widget editor on), I noticed the "more" menu of the blocks is transparent and also very wide:

<img width="503" alt="Screenshot 2020-09-09 at 22 31 59" src="https://user-images.githubusercontent.com/107534/92644653-5cb83080-f2ec-11ea-8dd0-a6b8c8e3077c.png">

**Comment by skorasaurus** [comment]
duplicate of https://github.com/WordPress/gutenberg/issues/25155 ; feel free to close this one or that :)

**Comment by draganescu** [comment]
Closed in favor of #25155
