### ISSUE TITLE
Widget screen: Widget area description is not present.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#25190]
**Describe the bug**
If I include a description for the widget area when I register it using register_sidebar, the description is not seen in the widget screen.

(-It is also not present in the customizer widget block panel.)

**To reproduce**
1. Enable a theme with a widget area and widget area description.
2. Enable Gutenberg 
3. Open the widgets screen
4. Try to figure out the difference between "sidebar 1" and "sidebar 2"

**Expected behavior**
A description is added to help the user learn where the widget area is visible on the front, or to give hints 
for what type of block and widget that is suitable.

The description needs to be visible in the UI.

**Editor version (please complete the following information):**
WordPress version: 5.5.1
Gutenberg: Version 8.9.3

**Desktop (please complete the following information):**
PC windows 10
Chrome Version 85.0.4183.83

**Comment by noisysocks** [comment]
Confirmed. You can see this by using Twenty Twenty. In the old screen you can see the widget area description right underneath the widget area title:

<img width="732" alt="Screen Shot 2020-10-02 at 11 22 23" src="https://user-images.githubusercontent.com/612155/94878756-a4704900-04a1-11eb-950d-01602c6ac426.png">

@mapk: Maybe we could show the description in the sidebar when the widget area is selected?

**Comment by mapk** [comment]
Ideally this will be implemented like this mockup below.

When a widget area is selected:

- The Settings will show only that widget area's name and description.
- The widget area name is reflected in the tab.
- The widget area itself is highlighted with a blue border.

![area 1](https://user-images.githubusercontent.com/617986/95108930-c0b5f500-06f0-11eb-9bee-33ab0f59a86c.png)
