### ISSUE TITLE
Caption short-code seems to break the conversion of other short-codes in classic post

### ISSUE THREAD

**Issue by mvdhoek1** [WordPress/gutenberg#25219]
**Describe the bug**
I've a classic post in a classic post block. Below the post in the code-editor view

![Schermafbeelding 2020-09-10 om 13 14 04 (2)](https://user-images.githubusercontent.com/11852816/92722383-ce819000-f367-11ea-8502-baa1e3b4f63b.png)

When I try to convert this post to blocks the result is:
![Schermafbeelding 2020-09-10 om 13 14 10 (2)](https://user-images.githubusercontent.com/11852816/92722546-0e487780-f368-11ea-866b-088e5df76eb7.png)

It seems that the caption short-code breaks the conversion of the first short-code in my post.
If I do the same without the caption short-code everything works just fine.

**To reproduce**
1. Paste the code below in a post via the code-editor, afterwards switch back to visual editor. Make sure the code is displayed in a classic block
```
In Utrecht zijn in 2020 de eerste twee danspleinen (Urban Dance Grounds) aangelegd. Eén dansplein bij het Centraal Station waar talentvolle dansers hun kunsten kunnen laten zien. En één in de wijk Kanaleneiland, specifiek gericht op de doelgroep meiden 12+. Ondernemer Petra Pluimers vertelt hoe ze te werk ging.

[yard_header title="Stap%201%3A%20Behoefte%20inventarisatie" sidebar_title="Behoefte%20inventarisatie" /]

[caption id="attachment_45015" align="alignright" width="95"]<a href="https://allesoversport-auteurs.accept02.yard.nl/wp-content/uploads/2020/05/Urban-Dance-Ground03-1.jpg"><img class=" wp-image-45015" src="https://allesoversport-auteurs.accept02.yard.nl/wp-content/uploads/2020/05/Urban-Dance-Ground03-1-211x300.jpg" alt="" width="95" height="135" /></a> Urban Dance Grounds, foto: Nijha[/caption]

Het schetsontwerp is samen met de jongeren uit de wijken afgestemd. Daarna zijn de vergunningen aangevraagd bij gemeente. Vervolgens zijn de plekken ingericht door het storten van de vloer, aanbrengen van coating en het plaatsen van bankjes, een informatiebord en de DJ-post. Het informatiebord is ontwikkeld samen met de doelgroep uit de wijk en geeft aan hoe de Urban Dance Ground te gebruiken.

[yard_header title="Stap%207%3A%20Stimuleren%20en%20monitoring%20van%20gebruik" sidebar_title="Stimuleren%20en%20monitoring%20van%20gebruik" /]
```
2. Now convert the classic block to blocks -> block controls -> 'convert to blocks'

**Expected behavior**
All of the shortcodes in my post should be converted to shortcode blocks

**Editor version (please complete the following information):**
- **WordPress version**: 5.5.1
- **Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default**: I've tried them both
- **If the Gutenberg plugin is installed, which version is it?** 8.9.3

**Desktop (please complete the following information):**
 - **OS**: IOS
 - **Browser**: Chrome
 - **Version**: 84.0.4147.135 (64-bits)

**Comment by kathrynwp** [comment]
Hi @mvdhoek1 – I've tested this with a standard audio shortcode (instead of your `yard_header` shortcode) but haven't been able to replicate. Converting to blocks from the Classic block works as expected, and the two audio players as well as the caption are all retained.

Here's my code:

```
[audio src="http://localhost:8888/WordPressDev9/wp-content/uploads/2012/07/test.mp3"]
[caption id="attachment_1770" align="alignnone" width="67"]<img class="size-medium wp-image-1770" src="http://localhost:8888/WordPressDev9/wp-content/uploads/2022/07/hH0upNX-67x300.jpg" alt="" width="67" height="300" /> here's a caption[/caption]
[audio src="http://localhost:8888/WordPressDev9/wp-content/uploads/2012/07/test.mp3"]
```

Tested with: 

WordPress 6.0.1
Gutenberg 13.7.3 active or inactive
No other plugins active
Theme: Twenty Twenty

I'll go ahead and close this out, but if you're still able to replicate with the latest version of WordPress, please feel free to add more details about how to replicate and I'll be glad to have another look.
