### ISSUE TITLE
Let's gutenberg.run working properly.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25225]
**Is your feature request related to a problem? Please describe.**
Many times I will go to gutenberg.run to test a PR. I will add the PR number and load, then sit and wait and wait and wait some more until either it works or is too often the case gives me an error. I then try to load it again....

**Describe the solution you'd like**
I know that gutenberg.run is a pet project of @aduth Andrew. As he is away, he is not available to adjust/fix/improve gutenberg.run.

It would be very helpful to have gutenberg.run working properly. As it makes testing a PR while a feature is being built so much easier, and makes it possible for non devs or really anyone to give feedback. The road to feedback is a lot simpler having gutenberg.run functioning.

**Describe alternatives you've considered**
Well.... This new documentation for setting up a Local WP Dev environment: https://developer.wordpress.org/block-editor/tutorials/devenv/ and this issue I am working on for testing/running PR's: https://github.com/WordPress/gutenberg/issues/25202 (I am getting lots of great help from Noah Allen..:)

Here is the gutenberg.run repo:
https://github.com/aduth/gutenberg.run

**Comment by youknowriad** [comment]
I think since the tool is not on Gutenberg itself, we should just close the repo. I also understand that @aduth works on that on his personal time so we need to be comprehensive there.

**Comment by paaljoachim** [comment]
Yeah. I was wondering about closing this issue as well. 
I am making a PR on how to test/run PR's locally, so that should help.
