### ISSUE TITLE
Bug with .mce-offscreen-selection left position in (at least) chrome

### ISSUE THREAD

**Issue by nderambure** [WordPress/gutenberg#25227]
OK this is not really easy to reproduce, but I'll try to explain.
I've a project which has some posts with only one images gallery inside.
I've updated the project to WP 5.5.1 and desactivated the plugin Classic Editor.
Now the galleries are inside a new block classic editor, exactly as expected.
Now, if I click inside a gallery (still inside the classic editor block), it works well in Firefox, but, weirdly, it disappears entirely in Chrome.

After investiating, I've found that the problem comes from the div tag inserted after the gallery, containing the gallery shorcode. This div tag has attributes :
* data-mce-bogus="all"
* class="mce-offscreen-selection"

The CSS is set with this rule : 
```
.mce-content-body .mce-offscreen-selection {
    position: absolute;
    left: -9999999999px;
    max-width: 1000000px;
}
```

In a screen with a width of 1500px (for demo), when decreasing the value of the ```left```property to around -33553750px, you can see the gallery being hidden from right. So the default value of -9999999999px hides it totally.

In firefox, the left value is maxed by the browser to -1.78957e+7px, but no problem occurs anyway.
Chrome seems to not maximize value.

My workaround is just to set a new rule in my editor.css file used in Gutenberg :
```
.wp-block-freeform .mce-offscreen-selection {
    left: -9999999px;
}
```

Feel free to ask for more info.

**Editor version :**
- WordPress version: 5.5.1
- default shipped Gutenberg

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome / Firefox
 - Version 85.0.4183.102 / 80.0.1

**Comment by talldan** [comment]
@nderambure I haven't been able to reproduce this, I don't see a div as you mentioned here:
> After investiating, I've found that the problem comes from the div tag inserted after the gallery, containing the gallery shorcode. This div tag has attributes :

Are you still experiencing the problem? If so any further steps you can help provide. Screenshots or screen recordings may also be helpful.

**Comment by nderambure** [comment]
Well, it seems this bug is no more relevant, and was probably originated from browser, not from WP.
Thx for noticing @talldan.
