### ISSUE TITLE
Add menu name to the top of the list view

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25233]
At the top of the List view in the reference mock-up for the Navigation editor (#24875) we have the current menu's name.

![image](https://user-images.githubusercontent.com/107534/92887061-df400d80-f41c-11ea-9df4-4311e0664798.png)

This is currently missing from the component. It also may have implications for the other editors that use the List View.

**Comment by Copons** [comment]
Hi! I'm removing the `[Feature] Navigation Component` label as it refers to the new [experimental Navigation component](https://github.com/WordPress/gutenberg/tree/668a710b3eb9c942b21eb5913fbe304b15ea71dd/packages/components/src/navigation).

**Comment by draganescu** [comment]
Howdy @shaunandrews, in #25343 I tried an edit in place approach to change a menu's name. However I tend to agree to @noisysocks 's [comment](https://github.com/WordPress/gutenberg/pull/25343#issuecomment-700352987) that this kind of control is not highly intuitive.

Could you please explore / think about how to edit a menu's name, in the context of the Navigation Editor (not block) and based on your design above?
A simple text field instead of the label in the block's toolbar seems the simplest way.

**Comment by draganescu** [comment]
Closing this as we no longer have a list view in the screen.
