### ISSUE TITLE
Add a "/widgets" endpoint

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25232]
With the recent advancements on the Widget editor, [it became apparent](https://github.com/WordPress/gutenberg/pull/24855#discussion_r478349689) that relying only on a "/sidebars" endpoint is insufficient.

We should therefore move widget related functionality from /sidebars to a new /widgets endpoint which also offers first class entity support for widgets.

**Comment by noisysocks** [comment]
I saw mention from @TimothyBJacobs and @spacedmonkey in the REST API chat that they might do this at the same time as moving the endpoints into `trunk` for 5.6. Is that right? Is there a ticket to follow?

**Comment by TimothyBJacobs** [comment]
No sorry if that was confusingly written. That'll have to happen in the Gutenberg repo.
