### ISSUE TITLE
Only display Featured Image field if theme supports post thumbnails

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2523]
A Featured Image field should only be available both if the current post type has `thumbnail` supports (available from [post types endpoints](https://developer.wordpress.org/rest-api/reference/post-types/)) **and the [theme supports post thumbnails](https://codex.wordpress.org/Post_Thumbnails)**. It is not currently possible to retrieve theme supports from the REST API. Alternatives exist, notably bootstrapping this data server-side on page load, but see #2499 for context on why this is not advisable.

**Comment by danielbachhuber** [comment]
After #6318 lands, we'll be able to use the `theme_supports` attribute on the index to expose this data into Gutenberg.

**Comment by danielbachhuber** [comment]
@aduth @youknowriad @gziolo I'm not quite sure the check itself lives within `PostFeaturedImageCheck` or `PostTypeSupportCheck`. Do any of you have an opinion?

And, on that note, it's odd that `PostTypeSupportCheck` accepts an array of `supportKeys`. I can't think of a use case for how `PostTypeSupportCheck` would process multiple values. Currently, it's only ever used in its singular form:

```
$ ack '<PostTypeSupportCheck'
post-author/check.js
26:	return <PostTypeSupportCheck supportKeys="author">{ children }</PostTypeSupportCheck>;
post-excerpt/check.js
7:	return <PostTypeSupportCheck { ...props } supportKeys="excerpt" />;
post-last-revision/check.js
16:	return <PostTypeSupportCheck supportKeys="revisions" >{ children }</PostTypeSupportCheck>;
```

**Comment by gziolo** [comment]
There is one use case where two values are necessary for `PostTypeSupportCheck` to render its content:
https://github.com/WordPress/gutenberg/blob/c2915d10899fe46287b32cc448c4a4f98b6c5fd3/edit-post/components/sidebar/discussion-panel/index.js#L17

`PostFeaturedImageCheck` only wraps `PostTypeSupportCheck` which provides the `supportKeys` value and handles the logic of conditional rendering of all `children` elements passed down.
