### ISSUE TITLE
Multiple InnerBlocks

### ISSUE THREAD

**Issue by mhimon** [WordPress/gutenberg#25239]
Assalamu Alaikum,
Hope you guys are well. I am a WordPress Developer, currently working on Gutenberg Block Development. I have been facing an issue with InnerBlocks. We can use InnerBlocks but not multiple :( I am waiting for a way like we use TextControl multiple times. Or if anyone has any good solution, please lemme know. Thanks in Advance.

**Comment by youknowriad** [comment]
Hi There!

That's a conceptual decision we made early one. InnerBlocks can only be used once inside a block. You can approach multiple inner blocks by relying on "intermediary blocks" like the columns -> column block.

**Comment by milanidavide** [comment]
Hi, there's a related discussion happening in Issue #6808. Some interesting points have been raised over the years that might be worth considering.
