### ISSUE TITLE
Navigation Component: Store the Navigation Tree in the Context

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25246]
Explore if we should keep an abstraction of the navigation tree (derived by the `Navigation` children) in the `NavigationContext`, in order to facilitate some automations that would otherwise require manually traversing the `Navigation` children.

Examples:
- Automatize the back button label for nested menus. (#25247)
- ~Automatically add an `ul` inside `NavigationMenu` if not provided by the consumer. (#25248)~
- Check that `setActiveItem` and `setActiveMenu` are targeting existing targets. (#25249)

**Comment by david-szabo97** [comment]
Taking this!
