### ISSUE TITLE
Post Author: Post becomes perpetually flagged as dirty ("Save Post")

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2524]
## Issue Overview

When assigning a user to a post, the post will forever be flagged as having unsaved changes, even after pressing Save Changes.

[Screencast](https://cloudup.com/cPtbdgVXBcE)

## Steps to Reproduce (for bugs)

1. (Prerequisite) Ensure there are two or more users on the site
2. Navigate to Gutenberg > New Post
3. Enter a title
4. Assign an author
5. Save the post

## Expected Behavior

The post is saved and reflected as such with a "Saved" label, and no option to Save.

## Current Behavior

The post saves, but immediately shows Save Draft again, indicating there are unsaved changes. Attempting to navigate away will prompt.

## Possible Solution

Cursory review shows that this is caused by the PostAuthor component assigning user ID as a string:

https://github.com/WordPress/gutenberg/blob/7a19916deed3e8c0f9d1944927bf17dc434cf2d7/editor/sidebar/post-author/index.js#L63

When the dirty detection compares against the saved post value (a numeric ID), they are not strictly equal.

**Comment by karmatosed** [comment]
I can replicate this too, good catch.
