### ISSUE TITLE
Navigation Component: Explore a Pagination Mechanism

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25253]
This is arguably a minor, nice-to-have, feature.

Should we add an optional mechanism that enables `NavigationMenu` pagination for longer menu (e.g. a list of all the site's post)?

Should it be a "load more"? "Next / previous" buttons? The whole numbered pages?

**Comment by mtias** [comment]
I'm not sure we should be scaling the sidebar navigation to accommodate all this. If we need pagination, it's likely that we are using the sidebar wrong and more space would be needed. Closing for now.
