### ISSUE TITLE
Navigation Component: Config Prop Support

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25257]
The original `Navigation` PR (https://github.com/WordPress/gutenberg/pull/24920) proposed passing the navigation tree in a  config prop.

We should explore if there's an easy way to extend `Navigation` to also accept a config prop, and internally convert it into the current components composition.

**Comment by david-szabo97** [comment]
Interesting. I like data driven components but for some reason I prefer declarative way here. Just like React Router. Do we really need this? 🤔

**Comment by Copons** [comment]
@psealock pinging you here since y'all proposed the config prop in the first place.
Do you think there's still a need for a data drive approach?
Considering that consumers will need to define the items `onClick` anyway, I think it's probably just easier (and even more readable maybe?) to write components directly.

**Comment by psealock** [comment]
We're happy with the component approach as it lends itself well to being rendered by looping over an array of items. I can't see a huge benefit to providing two mechanisms, so any solution would only be adding a way for bugs to creep in. Lets close this one.
