### ISSUE TITLE
Featured Image within the WordPress post embed is blurry on the frontend

### ISSUE THREAD

**Issue by danielpwaldschmidt** [WordPress/gutenberg#25263]
**Describe the bug**
When embedding a WordPress post using the WordPress embed block, the featured image is blurry on the frontend.

**To reproduce**
1. Go to https://y2y.net/blog/the-home-of-wildlife-crossings-banff-alberta/
2. Scroll down to the embedded WordPress post titled 'Wowed by wildlife crossings' (the last piece of content within the blog post).
3. See that the featured image within the embedded post is blurry.

**Expected behavior**
Expected the featured image to be clear. If you click on the embedded post to go to that post (https://y2y.net/blog/wowed-by-wildlife-crossings/), the featured image displays without issue (not blurry), so it's clear that the image is large enough so it should't be blurry when used as an embed.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 5.0.4183.83

**Additional context**
I've tried embedding the problematic post using a fresh WordPress install and the 2017 and 2019 themes, and the problem persists.

Any information about how the image size is being pulled in to use for the embed, why it's displaying blurry, and how this could be fixed would be greatly appreciated.

**Comment by mariohamann** [comment]
It seems that the embed block uses the "medium" size of an image. Per default maximum width/height of 'medium' is 300px, but in your current you need at least 548px to get the image without blur.

**Possible solution:**

1. Change the 'medium' width to e. g. `550px` in `WordPress > Admin > Settings > Media (/wp-admin/options-media.php)` (tested) OR add `update_option( 'medium_size_w', 550);` to `functions.php` of your theme ([untested source](https://developer.wordpress.org/reference/functions/add_image_size/#comment-1395)).
2. After that, you have to regenerate the thumbnails once, e. g. with the plugin [Regenerate thumbnails](https://de.wordpress.org/plugins/regenerate-thumbnails/).


Does this help? I would be happy about your feedback.

**Comment by danielpwaldschmidt** [comment]
Hey @mariohamann, thanks for weighing in.

I ended up using the [embed_thumbnail_image_size](https://developer.wordpress.org/reference/hooks/embed_thumbnail_image_size/) filter to change which image size is used for the post embed based on whether or not the width of the size WordPress chose is less than the global content width.
