### ISSUE TITLE
Site Editor: Attach the Navigation Component to the WP Button

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25260]
Replace the `FullscreenModeClose` button with a `Navigation` toggler.

https://github.com/WordPress/gutenberg/blob/668a710b3eb9c942b21eb5913fbe304b15ea71dd/packages/edit-site/src/components/header/index.js#L84-L86

The site editor navigation should slide in from the left, and contain a "back to the site" component to navigate back to the dashboard (only in fullscreen mode?).

![](https://user-images.githubusercontent.com/191598/88084303-34b11a00-cb52-11ea-8bab-0e5827c368b7.gif)

([Source](https://github.com/WordPress/gutenberg/issues/23939#issuecomment-662012836))

**Comment by david-szabo97** [comment]
@Copons I think this is safe to close now?

**Comment by Copons** [comment]
> @Copons I think this is safe to close now?

Yeah let's close this, since it's technically solved.

If we are not happy with the sidebar behaviour we can iterate on that eventually.
