### ISSUE TITLE
Site Editor: Extend the NavigationItem Components to Support Page and Template Previews

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25261]
The current page/template selector supports template (and theme) previews:

<img width="711" alt="Screenshot 2020-09-11 at 17 56 41" src="https://user-images.githubusercontent.com/2070010/92952635-36af9f00-f458-11ea-9fcf-abc225b76601.png">

https://github.com/WordPress/gutenberg/blob/668a710b3eb9c942b21eb5913fbe304b15ea71dd/packages/edit-site/src/components/header/index.js#L108-L127

We should replicate the same functionality in the new site editor navigation, by extending `NavigationItem` to support previews that show up on mouse over.

Depends on #25244.

![](https://user-images.githubusercontent.com/191598/88084303-34b11a00-cb52-11ea-8bab-0e5827c368b7.gif)

([Source](https://github.com/WordPress/gutenberg/issues/23939#issuecomment-662012836))

**Comment by david-szabo97** [comment]
Isn't this something that's the consumer's concern? 

We just need to make the component extensible so the consumer can show the preview. Which is kinda possible right now. We can add mouseenter and mouseleave event handlers on the NavigationItem.

I don't think we should add this to Navigation package. That would make it coupled with the block editor.

**Comment by david-szabo97** [comment]
Once we have the core implementations in place, then we can create a Navigation component in `edit-site` which implements this feature

**Comment by Copons** [comment]
> Isn't this something that's the consumer's concern?

@david-szabo97 agree!
That's why I named this PR as `Site Editor` 😛 

Although, there _could_ be a need of a standard item component with a preview panel.

> We just need to make the component extensible so the consumer can show the preview. Which is kinda possible right now. We can add mouseenter and mouseleave event handlers on the NavigationItem.

We probably not need to add the hover handlers to `NavigationItem`, but can simply add them to the Site Editor component.

**Comment by Copons** [comment]
@david-szabo97 I think there has been a regression on this, and previews are not visible anymore.
We might have caused it when we moved the sidebar around in the interface, or when we played around with overflows. 🤔

**Comment by david-szabo97** [comment]
Closing this, works fine on `master`.
