### ISSUE TITLE
Navigation Horizontal/Vertical - Not adding links from a menu

### ISSUE THREAD

**Issue by LauraSWP** [WordPress/gutenberg#25273]
**Describe the bug**
When adding a navigation block and selecting a menu, the menu links do not work as expected.

**To reproduce**
1. Go to Pages and edit or create a new page
2. Add the navigation block
3. Select a menu that has links
4. Save and try to click on the menu links. 

**Expected behavior**
Add the block, select the menu and the block adds the menu links correctly to the page.

**Screenshots**
Adding the block https://cdn-std.droplr.net/files/acc_1036796/kYYLlQ
At the website (GIF): https://d.pr/v/sKI5l3
Inspector: https://d.pr/i/Ss718O

**Editor version (please complete the following information):**
WordPress.com Simple and Atomic sites
Gutenberg active

**Desktop (please complete the following information):**
 - OS: Mac / Windows
 - Browser Chrome / Firefox

**Comment by aristath** [comment]
Thank you @LauraSWP 
Issue https://github.com/WordPress/gutenberg/issues/25087 is reporting the same behaviour so I'll go ahead and close this one as a duplicate :+1:
