### ISSUE TITLE
Updating failed. Invalid JSON body passed.

### ISSUE THREAD

**Issue by badmaghz** [WordPress/gutenberg#25278]
**Bug Description:**
When i try to publish or update a post which is longer than 3 or 4 pages then i get the following error message:
**Updating failed. Invalid JSON body passed.**
It works fine on a short posts.

**To reproduce**
1. Create a New Post.
2. Add content and then Click on Publish or Edit an existing post.

**Expected behavior**
It needs to publish or update the post.

**Editor Version:**
- WordPress version: **5.5.1**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? ["Gutenberg"]
- If the Gutenberg plugin is installed, which version is it? [Version 8.9.3]

**Desktop:**
 - OS: [Windows 10]
 - Browser [e.g. chrome, edge and firefox] on all Browsers
 - Version [Chrome 85, Edge 85 and Firfox version 80]

**Comment by youknowriad** [comment]
Hi there!

Do you think you can share with me an example of HTML (from the code editor) where the saving fails to see if I can reproduce?

In general, these issues are not directly related to Gutenberg but more consequences of issues on the server (REST API, PHP warnings, wrong server config or something else)

**Comment by badmaghz** [comment]
Hi @youknowriad the issue is resolved now. It could have been an issue on the webhosting side.

Thanks for your time anyway.
