### ISSUE TITLE
Rethinking the design of the Revisions Panel

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25270]
### Rethinking the design of the Revisions Panel.

The current revisions screen looks like this:
![Screen Shot 2020-09-12 at 11 33 20](https://user-images.githubusercontent.com/5323259/92992588-660feb80-f4ec-11ea-82f1-a56aa6594475.png)

--------

I took the above features and added them to the design versions below.

The following takes over the full screen in Gutenberg.
![New-Revision-Panel1](https://user-images.githubusercontent.com/5323259/92995191-754d6400-f501-11ea-9b5b-4d8aca944b55.jpg)

Here is screen overlay, so one can still be associated with the Gutenberg layout area.
![Revision-Panel-overlay](https://user-images.githubusercontent.com/5323259/92995340-08d36480-f503-11ea-8282-4363994a592f.jpg)

The left and right arrow seen between the versions can make it possible to move the line between both areas. Making one bigger than the other. For mobile the line could move a revision on top of another making it semitransparent. Idea came from @MDWolinski here: https://github.com/WordPress/gutenberg/issues/16053#issuecomment-673418951

Another idea would be to actually save an older revision as a new post/page/etc. So one would not need to choose between the current version and an older version. 

By default one only sees the top of each revision. It should be possible to scroll. Having a scrollbar on the right side. The top area above the revisions becomes fixed/stick to the top as one scrolls to compare both versions.

I forgot to add "Compare any two revisions" and the checkbox. As can be seen in the current version.

What are you thoughts?

-----------

Associated issues and a PR where either Auto save is mentioned or various revision controls mechanism are mentioned. 

I was inspired by @MichaelArestad , @enriquesanchez and @MDWolinski from the following issue.
https://github.com/WordPress/gutenberg/issues/16053

Here are other issues that touch upon revisions in one way or another:

https://github.com/WordPress/gutenberg/issues/23955

https://github.com/WordPress/gutenberg/issues/19226

https://github.com/WordPress/gutenberg/pull/20349

https://github.com/WordPress/gutenberg/issues/19149

https://github.com/WordPress/gutenberg/issues/12162

https://github.com/WordPress/gutenberg/issues/11067

https://github.com/WordPress/gutenberg/issues/14626

**Comment by manzwebdesigns** [comment]
I like it but wonder if there could be a kind of hover effect to show the code diffs as you move across the visual layout.  For example, when you hover over the spot where there is a diff between Previous and Next we could make the content changes show up on both sides of the compare window; using your example above `<!-- wp:spacer ...`

**Comment by paaljoachim** [comment]
Hi Bud. The slider should only affect the left version, as the right version should stay consistent showing the current design. The left version shows earlier designs. The visual designs in themselves should show when a change occurs. If there is a code difference and not visual then I believe there needs to be a visual signal/icon/etc that says something like "here is a difference" to give a clear hint to the user that there is a difference. A hover effect might be a bit hidden away. I am thinking some kind of icon perhaps top left of the left design to give the needed visual hint. Perhaps with a tooltip that says to click the code view button. As the user could become accustomed to when they see the visual hint to click the code view and see the code difference.

Thanks for the feedback!

**Comment by manzwebdesigns** [comment]
That is great!  I didn't think about the hover effect getting hid, but the idea of putting a visual hint like a dashed border around the changed element would be awesome!

**Comment by MDWolinski** [comment]
The designs look great.  Any thoughts on how this would work mobile?

**Comment by paaljoachim** [comment]
Hey Mark.

Good question!
The one thought I had about mobile was from your comment (linked to above). In relation to overlay of current version and earlier versions below. That could also mean being able to click between top (current) version and bottom (older) versions and select which one to use.

Using the slider or previous/next buttons the bottom overlay version would change (current top version stays the same). One could then select current or older version and make active and then click the restore button to restore the active version.

**Comment by karmatosed** [comment]
Whilst I understand taking the existing interface of revisions, I would also encourage exploring beyond what we have today. Don't limit to that as the only way to show revisions. How do other applications solve this now? Our current revisions implementation is older, it's not really been iterated much on for quite a considerable amount of time. What could be opened now reviewing?

**Comment by MDWolinski** [comment]
I can envision a world where revisions is down to the block level, think how you see Git commits by line, for example.  However, that would require changing the way the revision system is stored in the DB, since the current system is just a previously saved version of the post.

**Comment by paaljoachim** [comment]
Here is a tighter version. With a drop down next to the author so one can compare ones own version to other authors versions.

![New-Revision-Panel-version-2](https://user-images.githubusercontent.com/5323259/94816271-de870f80-03fb-11eb-84a8-fbd15e5e1d30.jpg)

Here is a version that shows switching to code. The pink background color gives a visual hint of variation between current and selected version.
![New-Revision-Panel-version3-showing-code](https://user-images.githubusercontent.com/5323259/94820440-c06fde00-0400-11eb-809d-b0a555728e22.jpg)

I still need to locate additional software that do revisions. My focus is on seeing two versions side by side. The current and earlier versions.

**Comment by kellychoffman** [comment]
@paaljoachim - This feels like a dupe of https://github.com/WordPress/gutenberg/issues/16053, especially this particular exploration: https://github.com/WordPress/gutenberg/issues/16053#issuecomment-673162147. Should we close this and continue the design + discussion in that issue so its a bit easier to follow and track?

**Comment by paaljoachim** [comment]
Heya Kelly @kellychoffman 

I added a comment to https://github.com/WordPress/gutenberg/issues/16053#issuecomment-843580886 and will close this issue.
