### ISSUE TITLE
Reusable blocks in Widget area

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#25279]
**Is your feature request related to a problem? Please describe.**
Hi, I just discovered (after updating the Gutenberg plugin/core) and tried out the new widget area.
However, no reusable block selection seems to be possible, only new blocks can be added.

**Describe the solution you'd like**
Reusable blocks should also be selectable.

**Describe alternatives you've considered**
The [Reusable Blocks Extended](https://wordpress.org/plugins/reusable-blocks-extended/) plugin.

**Comment by aristath** [comment]
Thank you @strarsis 
I found https://github.com/WordPress/gutenberg/issues/22875 which is about the same issue so I'll go ahead and close this one as a duplicate :+1:
