### ISSUE TITLE
Allow external preview links in Preview dropdown to be extended

### ISSUE THREAD

**Issue by westonruter** [WordPress/gutenberg#25309]
In the [AMP plugin](https://wordpress.org/plugins/amp/), we introduce a separate Preview button to be able to preview how the page appears in AMP. We had to put in place a bunch of hacks to get this to work in the block editor since the area around the preview button is not extensible. See https://github.com/ampproject/amp-wp/pull/4397. The button looks like this (screenshot courtesy of @simison):

> ![AMP Preview button](https://user-images.githubusercontent.com/87168/83613245-33b92e80-a58c-11ea-81be-54a8f85fc074.png)

Unfortunately, this broke in Gutenberg 8.8. But this is not surprising since it was implemented with hacks. We actually don't want to have a separate AMP preview button in the first place. Ideally the AMP preview link would be exposed in the relatively new device preview dropdown (https://github.com/ampproject/amp-wp/issues/4368#issuecomment-597943645), as also was suggested in https://github.com/Automattic/wp-calypso/issues/42896:

> ![Preview dropdown](https://user-images.githubusercontent.com/87168/83613064-edfc6600-a58b-11ea-9c86-c420496667a9.png) 

However, we weren't able to do so given that this dropdown is not extensible. 

So my request is that the Preview dropdown menu items be extensible. Plugins should be able to add their own preview links in addition to "Preview externally". This will be useful not only for AMP, but it could also be used by other plugins that may provide alternate representations of the content (e.g. FB Instant Articles, Apple News) or even as a way to link to preview the content on a site that is using WordPress headlessly.

This relates to https://github.com/WordPress/gutenberg/issues/21235 which is about extending the non-external preview options.

**Comment by simison** [comment]
Could be also used to preview:

- social media shares,
- dark mode for websites that implement it (while editor stays light mode)
- and additional display sizes for more exotic targets such as televisions.

**Comment by simison** [comment]
PR: https://github.com/WordPress/gutenberg/pull/25430

**Comment by fumikito** [comment]
+1 for this.

Custom post type with `public => false, show_ui => true` is commonly used.
Marketing mail plugin, eBook generator, and so on.

Creating a preview screen is responsible for plugin authors, but it's more agreeable with an extensible preview area.
