### ISSUE TITLE
Inline styles saved on the backoffice aren't passed to frontend.

### ISSUE THREAD

**Issue by LC43** [WordPress/gutenberg#25310]
**Describe the bug**

Applied custom color in the editor adds inline style correctly. However, it doesn't have it on the front:

![Screenshot_2020-09-14_18-00-13](https://user-images.githubusercontent.com/48201/93115803-4d523200-f6b4-11ea-93ca-2c26ae7ac38e.png)

on backoffice:
![Screenshot_2020-09-14_17-58-01](https://user-images.githubusercontent.com/48201/93115804-4e835f00-f6b4-11ea-86ca-727b92fd2d42.png)

**To reproduce**
1. Go to new post
2. add media block
3. create heading and change color.
4. See inline style with color
5. Save and view post
6. Don't see header with inline style.

**Expected behavior**
Expect to see header with inline style.

**Screenshots**

on front:
![Screenshot_2020-09-14_18-00-13](https://user-images.githubusercontent.com/48201/93115803-4d523200-f6b4-11ea-93ca-2c26ae7ac38e.png)

on backoffice:
![Screenshot_2020-09-14_17-58-01](https://user-images.githubusercontent.com/48201/93115804-4e835f00-f6b4-11ea-86ca-727b92fd2d42.png)
![Screenshot_2020-09-14 Add a New Post ‹ amgroup test — WordPress(1)](https://user-images.githubusercontent.com/48201/93116275-f7ca5500-f6b4-11ea-8297-4dafd5a6e3bd.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: linux
 - Browser : firefox ( any really )
 - Version 72.0.2

**Comment by youknowriad** [comment]
I'm not able to reproduce this. I think the issue is probably coming from another plugin. Do you have other plugins enabled on your site? Would you be able to disable them to check?

**Comment by LC43** [comment]
Hi @youknowriad , thanks for looking into this.

I tested in a clean installation, without any plugins.

To be clear, I didn't add new custom color. i used the one from the theme preset.

I'm missing a few steps to clearly explain this:
+ 0.1 Install twentysixteen theme
+ 0.2 Set custom color template ( i copied the one from twentytwenty ) in functions.php
   -  [function twentytwenty_block_editor_settings()](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentytwenty/functions.php#L479)
  - [function twentytwenty_get_color_for_area()](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentytwenty/functions.php#L635)

**Comment by youknowriad** [comment]
Oh i understand better! When you set colors from the palette, there's no inline styles added by Gutenberg to the frontend, it just applies classnames corresponding to the selected colors and  you need to load the stylesheet for these classnames manually on your theme's CSS. See here for details https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes

**Comment by LC43** [comment]
yes, it's inconsistent behavior. How can i enable the inline styles on frontend too? 
If there's no way to enable the inline styles, can i disable the inline styles on the backend? 
Either way, users ( and me! ) don't get confused why it works on the backend and not in the frontend.

Since the colors come from the customizer ( picked from the user's ), the theme doesn't have the class with the colors.

**Comment by youknowriad** [comment]
There's no way to enable inline styles on the frontend for custom palette colors. Inline styles are not considered a good practice here for SEO... And also when you change the palette colors (and keep the names), the update doesn't impact existing content.

In the future though, we have plans to automatically generate these classnames styles and load them on the frontend.

Thanks for your understanding.
