### ISSUE TITLE
Tiled Gallery showing 'Attempt block recovery' when within a different block

### ISSUE THREAD

**Issue by rachelwinspear** [WordPress/gutenberg#25326]
**Describe the bug**
When the Tiled Gallery is located within another Block, for example Column Block or Layout Grid, upon saving and returning to the page, the Tiled Gallery Bock shows the  'Attempt block recovery' message. 
Issue does not affect Tiled Gallery Block that are not within a different block.

**To reproduce**
1. Add a Column Block or Layout Grid to a page
2. Within the previous block created, add the Tiled Block and save the page
3. Exit the page and then go back/reload to the page, and you will see the 'Attempt block recovery' message on the Tiled Gallery Block that was added 
4. It is possible to recover the block by clicking on the message, but the 'Attempt block recovery' messages appears again when returning to the page. 

**Expected behavior**
I expected to save the page and to be able to reload it without the 'Attempt block recovery' message showing

**Screenshots**
![Screenshot](https://d.pr/i/mILS1J+)
If you are unable to see this image, please click [here](https://d.pr/i/mILS1J)

**Editor version (please complete the following information):**
WordPress.com - Premium plan
Gutenberg: 8.9.3
CoBlocks: 2.2.2
wpcom-FSE: 249255423

**Desktop (please complete the following information):**
https://www.whatsmybrowser.org/b/OYWJF

**Comment by youknowriad** [comment]
Hi There! the Tiled Gallery is not a Core block, I believe it's a jetpack block. You should open an issue on their Github issue tracker instead. Thanks https://github.com/Automattic/jetpack

**Comment by rachelwinspear** [comment]
> Hi There! the Tiled Gallery is not a Core block, I believe it's a jetpack block. You should open an issue on their Github issue tracker instead. Thanks https://github.com/Automattic/jetpack

Thanks, now reported here: https://github.com/Automattic/jetpack/issues/16514#issuecomment-693533144
