### ISSUE TITLE
Is there a filter to filter the output of the image tag in the frontend?

### ISSUE THREAD

**Issue by landwire** [WordPress/gutenberg#25325]
Hi there,
is there a way to use a filter to change the src attribute of images before they get rendered?
And ideally other attributes of the image too like class, sizes, srcset etc.

What data is available in that filter, if there is one?

**Comment by youknowriad** [comment]
Hi There!

you can check this thread for an answer to this question https://wordpress.stackexchange.com/questions/332762/change-wordpress-image-urls-via-filter

Note that ideally, the Gutenberg repository is not meant for help requests.
For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.
Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.
You may also ask for technical support at https://wordpress.stackexchange.com/.

Thanks.
