### ISSUE TITLE
How Add New Button to Gutenberg Editing Toolbar

### ISSUE THREAD

**Issue by artmaug** [WordPress/gutenberg#25368]
When i publishing a content using Gutenberg I miss a button to create a new post right there without leaving the editor and going back to this.

See the image to better illustrate the issue.

![gutenberg-add-new](https://user-images.githubusercontent.com/10658737/93325750-2a2b9d80-f7ee-11ea-94e4-374a23e9054a.png)

How can I create this button?

I thank you all for your help.

**Comment by youknowriad** [comment]
Hi There!

It is not possible to add custom buttons there. It's a design decision to avoid bloat. That said, there's a dedicated area where pinnable plugins can be accessed like the custom "G" icon you have at the top right of your screenshot.

You can do so by adding a "sidebar plugin" for instance. This tutorial should help https://developer.wordpress.org/block-editor/how-to-guides/plugin-sidebar-0

**Comment by sabernhardt** [comment]
The guide is now at this location:
https://developer.wordpress.org/block-editor/how-to-guides/plugin-sidebar-0/
