### ISSUE TITLE
Component Panel IDs/classNames

### ISSUE THREAD

**Issue by netzgestaltung** [WordPress/gutenberg#25360]
Hi there,

my goal is to hide/show a taxonomy box based on the selected page template on edit-post.php with the page post_type.

I challenged to add the selected template name to the admin_body_class:
```// add usefull classNames
// @param  $classes  string
function myPlugin_admin_body_class($classes){
  $classNames = '';
  $screen = get_current_screen();

  if ( $screen->base === 'post' && $screen->post_type === 'page' ) {
    $page_template = get_post_meta(get_the_ID(), '_wp_page_template', true);
    $classNames .= ' used-template-' . esc_attr(str_replace('.php', '', $page_template));
  }
  return $classes . ' ' . $classNames;
}
add_filter('admin_body_class', 'myPlugin_admin_body_class');
```

i then want to add some CSS to my admin.css file
```
.component-panel.edit-taxonomy-myTaxonomyName{
  display:none;
}
body.used-template-page-myTemplate .component-panel.edit-taxonomy-myTaxonomyName{
  display:block;
}
```
then i inspected the panels and there are specific classNames for the 1st and 2nd component-panel ```edit-post-post-status``` and ```edit-post-last-revision``` but there are no classNames or IDs for all the other component-panels. How can i filter the names into that markup?

Here is a screenshot of the firefox inspector:
![image](https://user-images.githubusercontent.com/2329947/93311674-931f0f80-f806-11ea-9ec8-514e3d36706b.png)

**Comment by tellthemachines** [comment]
Not 100% sure I'm understanding the question correctly, but if you're trying to add extra classnames to the components-panels, there's no way of doing that.

However, it is possible to remove some of those panels conditionally on the post template, using JavaScript.

Try these out in the browser console:

`window.wp.data.select('core/edit-post').getEditedPostTemplate()` - this will get you all the data on the current post/page template, and

`window.wp.data.dispatch('core/edit-post').removeEditorPanel('featured-image')` - this will remove the "Featured image" panel altogether. (I'm using Featured image as an example; for whatever panel you'd like to remove you'll need to know its slug. A little digging in the [sidebar component](https://github.com/WordPress/gutenberg/tree/trunk/packages/edit-post/src/components/sidebar) code should get you that info)

Hope this helps!

**Comment by tellthemachines** [comment]
@netzgestaltung I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
