### ISSUE TITLE
Incorrect response from custom getEntityRecords() route

### ISSUE THREAD

**Issue by Flynsarmy** [WordPress/gutenberg#25388]
**Describe the bug**
When adding a custom route through [addEntities()](https://developer.wordpress.org/block-editor/data/data-core/#addEntities) that returns an array, the corrosponding [getEntityRecords()](https://developer.wordpress.org/block-editor/data/data-core/#getEntityRecords) record returns the last element in the array repeated n times.

**To reproduce**
1. In functions.php define your custom route: 
```php
add_action('rest_api_init', function () {
    register_rest_route('my-api/v1', '/notices/', [
        'methods' => 'GET',
        'callback' => function ($data) {
            return [
                [
                    'status' => 'foo',
                    'content' => 'Foo message',
                ],
                [
                    'status' => 'bar',
                    'content' => 'Bar message',
                ],
                [
                    'status' => 'baz',
                    'content' => 'Baz message',
                ],
            ];
        },
        'permission_callback' => '__return_true'
    ]);
});
```
2. Confirm it works by visiting *https://yoursite.com/wp-json/my-api/v1/notices*
3. Go to the 'Add new Post' page *https://yoursite.com/wp-admin/post-new.php*
4. In web inspector console add our custom route with
```javascript
wp.data.dispatch( 'core' ).addEntities( [
    {
        name: 'my-api-notices', // route name
        kind: 'my-api/v1', // namespace
        baseURL: `/my-api/v1/notices`, // API path without /wp-json
    },
] );
```
5. Retrieve the data from this route with
```javascript
wp.data.select( 'core' ).getEntityRecords( 'my-api/v1', 'my-api-notices' )
```
6. Run the `getEntityRecords` line again now that the AJAX has finished processing. Incorrect results will be displayed.

**Expected behavior**
I expect a JSON array of the results returned from our REST route:
```javascript
[
    {
        'status': 'foo',
        'content': 'Foo message',
    },
    {
        'status': 'bar',
        'content': 'Bar message',
    },
    {
        'status': 'baz',
        'content': 'Baz message',
    },
];
```
I instead get:
```javascript
[
    {
        'status': 'baz',
        'content': 'Baz message',
    },
    {
        'status': 'baz',
        'content': 'Baz message',
    },
    {
        'status': 'baz',
        'content': 'Baz message',
    },
];
```

**Screenshots**
![Screen Shot 2020-09-17 at 11 18 22 am](https://user-images.githubusercontent.com/334808/93408297-9a621e00-f8d7-11ea-9605-dfae7dfe97ec.png)
<img width="697" alt="Screen Shot 2020-09-17 at 11 20 04 am" src="https://user-images.githubusercontent.com/334808/93408357-c2ea1800-f8d7-11ea-878d-12e430483a6e.png">
<img width="946" alt="Screen Shot 2020-09-17 at 11 20 38 am" src="https://user-images.githubusercontent.com/334808/93408431-d85f4200-f8d7-11ea-8011-1ee653c7150f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] default

**Desktop (please complete the following information):**
 - OS: OSX 10.15.6
 - Browser Chrome 85.0.4183.102

**Comment by youknowriad** [comment]
I think the entities should have a unique primary key, it seems to be "status"  in your entity, so you can add `key: "status"` to your entity config.

**Comment by Flynsarmy** [comment]
Thanks that worked, though I'd suggest adding documentation for the method. It currently has pretty much [none](https://developer.wordpress.org/block-editor/data/data-core/#addEntities). Key is mentioned nowhere besides [getEntityRecord](https://developer.wordpress.org/block-editor/data/data-core/#getEntityRecord) however that one doesn't mention `baseURL` which you need in `addEntities`.

**Comment by youknowriad** [comment]
@Flynsarmy yes, docs definitely need to be improved. Is this something you can help with?

**Comment by yoscbd** [comment]
Thank you @youknowriad ,

I wasn't sure where and how i need to add the "key" property but i got it after 10 min...


Here is my full sample code based on you solution for anyone who is puzzled with the "key":

PHP in function.php code ,
I register a new rout for getting post title and post permlink only - making a lighter server request with a lighter responds: 

```
add_action('rest_api_init', 'ybdRegisterPostTitleAndLink');

function ybdRegisterPostTitleAndLink()
{
    register_rest_route('ybd/v2', 'post', array(
        'methods' => WP_REST_SERVER::READABLE, // same and better way as using 'methods' => 'GET'
        'callback' => 'ybdResults',
    ));
}

function ybdResults()
{

    $threats = new WP_Query(array(
        'post_type' => 'post',
    ));

    $queryResults = array(); // create an empty array so later in the while loop we can push items in to it and return it in the end

    while ($threats->have_posts()) {

        $threats->the_post();
  

// push a new array to our "queryResults" array, this result with a single "queryResults" array that will hold an array for each post:
        array_push($queryResults, array( 
            'ybdtitle' => get_the_title(),
            'ybdpermalink' => get_the_permalink(),
        ));
    }

    return $queryResults;

}

```
and this is my react code (I'm using "useSelect()") :

```
   wp.data.dispatch('core').addEntities([
        {
            name: 'post',           // route name
            kind: 'ybd/v2', // namespace
            baseURL: '/ybd/v2/post', // API path without /wp-json
           key: "ybdtitle" // -----This is where i add the mentioned key
        }
    ]);



    const threats = useSelect(
        (select) => {

            return select('core').getEntityRecords('ybd/v2', 'post')
        },
        [numberOfPosts] // any change in the attributes listed here will triger the useSelect function
    );

    console.log(threats)
```

**Comment by Donovanrailway88** [comment]
https://lnkr.fun/f2d5dd1



I defined the answer
