### ISSUE TITLE
Normalize HTML Style Tags in Gutenberg Editor

### ISSUE THREAD

**Issue by cameronvoell** [WordPress/gutenberg#25389]
**Is your feature request related to a problem? Please describe.**
It is possible to edit HTML of a post in Gutenberg and stylize text using tags that are not expected by the editor but style changes still render in the editor. This can get us in a state where text is bold, but we can not unbold it using the bold toolbar for example.

Steps to reproduce:
1. Create new post and a sentence to a paragraph block
2. Go to HTML editor and surround some words with `<b></b>` tags, (gutenberg normally uses `<strong>`)
3. Exit HTML (code) editor and notice that the words are shown in bold
4. Select bold letters and note that bold button is not highlighted in toolbar unless you press it. Howver you can not unbold this text using the toolbar. 

Similar uneditable states can be created for italics and strikethrough. 

![bold](https://user-images.githubusercontent.com/1103838/93415691-f20d7480-f858-11ea-8d65-845694b75d15.gif)

**Describe the solution you'd like**

I think we should either

A) Remove tags like `<b> `that are not expected by the editor so they don't make visible changes in the editor that can not be updated as expected by the toolbar. 

or

B) Normalize `<b>` tags to `<strong>` and do the same for other examples so that they can be controlled by the toolbar as expected. 

**Describe alternatives you've considered**
A third option would be to allow the toolbar to handle multiple different types of tags, but I think normalizing them to the one we default to makes more sense, and would be more neat.

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this one, since the editor now has a "Clear Unknown Formatting" button to clear tags that aren't recognised from the toolbar:

<img width="716" alt="Screenshot 2023-05-12 at 2 32 29 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/8eaf25a4-ca82-4b67-afc6-e57b288583f1">

(the above screenshot has "tags" surrounded by`<b></b>`)
