### ISSUE TITLE
Show keyboard shortcuts in line for View modes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#25387]
**Is your feature request related to a problem? Please describe.**

While watching @helen's [twitch stream](https://www.twitch.tv/videos/742930054) today, she talked about Full Screen mode and expressed confusion around how to toggle it on/off (2:18-2:20:10 & 2:34-2:37). In it, she mentioned expecting to see the keyboard shortcut listed similar to what's in place for the Editor options with Code & Visual Editor:

![toggle options](https://user-images.githubusercontent.com/26996883/93402209-5a505c00-f841-11ea-95ae-0ee356d8d688.gif)

Here's what the mode settings look like right now: 

<img width="263" alt="Screen Shot 2020-09-16 at 5 28 48 PM" src="https://user-images.githubusercontent.com/26996883/93402482-16118b80-f842-11ea-902f-04a266fbca8d.png">

I agree with Helen's insight and wanted to follow up here to start a conversation about what it might look like to make the shortcut options more visible. 

**Describe the solution you'd like**

Ideally, the shortcut options can be visible when you have the View modes open so people can begin to learn the various shortcuts available. Currently, the only way it seems you can find the keyboard shortcut options is by looking under Tools > Keyboard Shortcuts. 

Thankfully, it seems like this can be done in a way that mimics what's in place for the editor options where the shortcut options are shown conditionally. Also, I imagine with a full site editing future this will be advantageous for those wanting to switch between different modes.

**Comment by mapk** [comment]
It appears this was solved with https://github.com/WordPress/gutenberg/pull/25395.
It now looks like this:

![Screen Shot 2020-09-23 at 7 50 27 PM](https://user-images.githubusercontent.com/617986/94095374-753d4600-fdd6-11ea-8477-0bb28c1e64f3.png)
