### ISSUE TITLE
How to enable media upload capabilities

### ISSUE THREAD

**Issue by capJavert** [WordPress/gutenberg#25403]
Hello,

I was looking extensively and I can not find example of enabling mediaUpload function to my Gutenberg editor instance. I am using standalone setup outside of wordpress (like one in storybook example).

When I try to upload image i get error:
`image.js:221 Uncaught TypeError: mediaUpload is not a function`

I understand why that happens but I can not find example of how to pass this function to my gutenberg instance. 

I found that it is placed inside settings for example I can see that it is `undefined` if I query `block-editor` settings:
```js
const { mediaUpload } = useSelect(select => {
    const { getSettings } = select('core/block-editor')

    return pick(getSettings(), ['mediaUpload'])
})
```

FYI: I do not expect that I will get classic wordpress UI when I somehow enable media upload capabilities (I can implement my on file manager).
Can someone point me in direction on how to set `mediaUpload` function.

Tnx!

**Comment by youknowriad** [comment]
hi there!

just pass a `mediaUpload` function to the `settings` prop of your `BlockEditorProvider`. See https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/provider/index.js#L199 

This is the implementation of this function for WP https://github.com/WordPress/gutenberg/blob/master/packages/media-utils/src/utils/upload-media.js#L67
