### ISSUE TITLE
Enabling Gutenberg breaks hook in the customizer

### ISSUE THREAD

**Issue by dimaeromin97** [WordPress/gutenberg#25417]
**Describe the bug**
Action `admin_enqueue_scripts` on customize.php does not work on the customizer admin screen when the Gutenberg plugin is activated.

**To reproduce**
1. Activate the Gutenberg plugin
2. Hook some script to `admin_enqueue_scripts`
3. Go to **Appearance** > **Customize**
4. Notice the script does not load.

**Editor version (please complete the following information):**
- WordPress version: 5.5.2-alpha-48959
- gutenberg plugin
- Gutenberg version: 9.0.0

**Desktop (please complete the following information):**
 - WINDOWS
 - Browser chrome
 - Version 85.0.4183.102

**Comment by youknowriad** [comment]
Hi there!

We'd need more information if you want us  to help you.
Can you give an example of not working hook?
How is this related to Gutenberg?

**Comment by dimaeromin97** [comment]
> Hi there!
> 
> We'd need more information if you want us to help you.
> Can you give an example of not working hook?
> How is this related to Gutenberg?

I connect some scripts on the admin_enqueue_scripts hook that I use on all admin pages, but when the gutenberg plugin is activated, this hook does not work for me on the Customize page (wp-admin / customize.php), but although it does work before activation

**Comment by youknowriad** [comment]
> , but when the gutenberg plugin is activated, this hook does not work for me on the Customize page (wp-admin / customize.php)

@dimaeromin97 Just to make sure I understand properly, is it the only script that doesn't work? or any hook loaded on `admin_enqueue_scripts` doesn't work? If it's specific to your own hook, would you mind explaining what it does or share it with us?


I wonder if this is related to the block-based customizer panel. cc @adamziel

**Comment by adamziel** [comment]
I wonder if it's related as well! I'll add it to to triaging queue. Here are two potentially related issues: https://github.com/WordPress/gutenberg/pull/25415 https://github.com/WordPress/gutenberg/issues/15644

**Comment by draganescu** [comment]
Blocked by #25625

**Comment by noisysocks** [comment]
We'll be completely rearchitecting our implementation of how blocks work in the Customizer, but in the meantime let's investigate this to see if this hook is not being fired when the Gutenberg plugin is active. If so then let's fix that asap.

**Comment by draganescu** [comment]
This is not blocked anymore. I think #25415 is related too.

**Comment by noisysocks** [comment]
I'm not able to reproduce this.

I created a plugin with the following files, activated Gutenberg, enabled the Widgets in Customizer experiment, navigated to Appearance → Customize, and saw the alert dialog appear.

```php
// my-plugin/my-plugin.php
/**
 * Plugin Name: My plugin
 */
add_action(
	'admin_enqueue_scripts',
	function() {
		wp_enqueue_script( 'my-script', plugin_dir_url( __FILE__ ) . 'my-script.js', array(), '1.0' );
	}
);
```
```js
// my-plugin/my-script.js
alert( 'hello!' );
```

Let me know if I've misunderstood and we can reopen.

**Comment by bajoski34** [comment]
is this still a thing?
