### ISSUE TITLE
Cover block: Improve block styles

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#25432]
**Is your feature request related to a problem? Please describe.**
Currently, the cover block offers two alternative styles - bottom and top wave. The extra styles are welcome, but these particular ones are a bit impractical. The waves are very dynamic, which means they require extra padding and end up being really tall if you want to put text inside of them. 

My proposal is to either modify the current styles and make the waves gentler. Here's roughly what I had in mind:
![image](https://user-images.githubusercontent.com/4550351/93545389-9d2a4500-f9a3-11ea-999a-36637305f314.png)

For comparison, here's how the style looks like now (I added a 100px high spacer above the text here, otherwise the text would be right next to the edge):
![image](https://user-images.githubusercontent.com/4550351/93545876-ddd68e00-f9a4-11ea-8beb-12cd0a259eed.png)

**Comment by fabiankaegy** [comment]
@alaczek The `core/cover` block currently doesn't have any Style Variations in core. My guess would be, that the two style variations you mentioned are added using the `registerBlockStyle` function in a plugin or theme. 

Because of that I am going to close out this issue.

**Comment by alaczek** [comment]
Ah, you're totally right! Sorry!
