### ISSUE TITLE
When resizing, image captions are not kept under the images.

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#2543]
To reproduce:
1. Add an image.
2. Add a caption.
3. Resize the image by dragging the corners.

Result: the caption in not under the image. 

---
![caption](https://user-images.githubusercontent.com/743931/29753069-01f04526-8b6a-11e7-928d-6477335afd89.png)

**Comment by karmatosed** [comment]
It's worth noting if you click alignment then this does make the caption fit properly. I do think it's fair to assume the caption would move and the caption align.
