### ISSUE TITLE
hiding block-list-appender inside of Buttons block when not selected

### ISSUE THREAD

**Issue by covertnine** [WordPress/gutenberg#25437]
**Describe the bug**
The block-list-appender takes up space in the dom from its margins, even when invisible and when the buttons block is not selected, causing buttons to shift left--even when the block alignment is to center. Display bug is more apparent visually in narrow containers or inside of group blocks.

Our themes have grid blocks, and inside of those are columns, and inside of those are group blocks, and inside of those are buttons blocks. Block-list-appenders should be set to display:none if the parent .wp-buttons-block is not selected.

I've done this on our themes with the following CSS code but was hoping this could be added as part of the buttons block CSS as that appender shouldn't be taking up any horizontal space when it's not visible.

`.wp-block-buttons:not(.is-selected)>.block-editor-inner-blocks .block-list-appender:last-child {
	display: none;
}`

**To reproduce**
1. Inside of a column, add a group block, and inside of the group block, add a buttons block with multiple buttons.
2. Click on the center alignment of the buttons
3. Buttons will break to separate lines or be misaligned on the backend while displaying centered on one line on the frontend.

**Expected behavior**
The CSS for the buttons block should have the appender hidden when the block isn't selected using existing CSS classes, as I've outlined above.

**Screenshots**
Here's after my CSS is applied in the backend:
<img width="1142" alt="editor-expected-display-buttons-block" src="https://user-images.githubusercontent.com/10245479/93562736-a04a1480-f954-11ea-896f-c8e2818238c8.png">

Before with the appender taking up space:
<img width="1124" alt="editor-actual-display-buttons-block" src="https://user-images.githubusercontent.com/10245479/93562749-a6d88c00-f954-11ea-8b68-71fb17bdaddb.png">

Here's the appender when the block is selected, and it should be taking up space cause it is visible. 
<img width="1170" alt="editor-selected-with-appender" src="https://user-images.githubusercontent.com/10245479/93562830-c374c400-f954-11ea-8cbb-7dd5f16667df.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? This is running one of our beta themes with the [C9 Blocks plugin](https://wordpress.org/plugins/c9-blocks) and the core buttons block.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version 85

**Additional context**
This may be unique to our theme cause we have container blocks that can get pretty narrow with 2-6 column grids, but this is bound to come up. We try to get the backends as close to the frontend as we can visually, and not being able to see buttons centered properly on the backend anytime they're in a narrow container like a dialog box is confusing for users.

Apologies for the chicken wings picture. They do look delicious.

**Comment by kathrynwp** [comment]
I haven't been able to replicate this issue with:

WordPress 6.0.1
Gutenberg 13.7.3 active or inactive
No other plugins active
Theme: Twenty Twenty 2.0 or Twenty Twenty-Two 1.2

Centering both button blocks individually _does_ cause them to go onto separate lines, but that seems like the expected behaviour, as a single button can't be centered unless it's on its own line. 

To centre both buttons together within the column, I can select the Buttons block and choose the "Justify items center" option.

I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to reopen with additional details, if needed.
