### ISSUE TITLE
Post Date Style Customization 

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#25456]
It feels less common to see this nowadays, but it could be nice to allow post date to be styled a little more interesting.

Examples:
![Screenshot 2020-09-18 at 15 26 16](https://user-images.githubusercontent.com/908665/93609117-5b10fb80-f9c3-11ea-9327-3cd4cd003428.jpg)

**Comment by aristath** [comment]
This should probably be handled by themes using block-styles.
We could however add `span` elements with the appropriate classes around the year, month, day etc to make styling these easier in themes...

**Comment by annezazu** [comment]
This came up in feedback as [part of the fifth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1501):

> can we provide an advanced option for “Format settings” which allows specifying a custom format perhaps using PHP’s date format https://www.php.net/manual/en/datetime.format.php#refsect1-datetime.format-parameters

&

>Can I make the date italics? I didn’t see many text styling options for the post date.

I wanted to include it here since it seems very related :)

**Comment by andrewserong** [comment]
For formatting the date, I wonder if we can do something similar to Google Sheets to enable constructing a custom date format:

| Selecting a part of the date | Customising the format of that part |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/128813804-d5493d2d-2430-4fc0-90b4-6bc66451309d.png) | ![image](https://user-images.githubusercontent.com/14988353/128813812-757997c2-159c-4e21-95ab-8931986c6c57.png) |

Then it'd be a matter of allowing each of those to be styled separately, perhaps? They could _almost_ be child blocks, but maybe that'd result in a little too much going on in the editor canvas.

**Comment by kjellr** [comment]
Here's another example of the sort of hyper-stylized query layout I'd like to see made possible (eventually) through post date format/style options: 

<img width="1200" alt="Frame 17" src="https://user-images.githubusercontent.com/1202812/130241513-af6cdd98-a4f1-49b3-a1b8-60ea30dc0fb8.png">

(Also relevant to https://github.com/WordPress/gutenberg/issues/34192)

**Comment by ramonjd** [comment]
https://github.com/WordPress/gutenberg/issues/24957 is a similar issue, though it adds ideas for other Post Date block enhancements.

This could be a bit free-wheeling, with _great-power comes-great-responsibility-type_ of stuff, but I was playing around with a free-text formatter:

https://user-images.githubusercontent.com/6458278/150456177-6a6a1a28-6f93-42b5-99ad-3a742b94f8a6.mp4

With the right validation and better UX, e.g., proper labels for the shortcode characters maybe...? :)

I like the idea of adding relative times, e.g., "Today or 3 days ago", as well mentioned in https://github.com/WordPress/gutenberg/issues/24957#issuecomment-985098831

**Comment by andrewserong** [comment]
> but I was playing around with a free-text formatter:

Awesome idea, @ramonjd! I might be getting ahead of myself, but I think if we can use something like that as the underlying data for it (and possibly allow a toggle for folks to edit it manually for advanced users) but then build an interactive WYSIWYG behaviour on top of it, it'd be pretty cool to have a reusable component that we could use anywhere where a date is presented? Maybe a `DateTimeFormatter` component in the components package?

+1 adding relative times would be very cool, too 😀

**Comment by mtias** [comment]
I believe this is completed in a general sense, but feel free to reopen if there's any specific that are missing.
