### ISSUE TITLE
Keyboard navigation in block toolbar is confusing

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#25465]
**Describe the bug**
In the screencast below, I found an odd interaction while using the keyboard for navigating through the block's toolbar. Clicking the right arrow takes me from the Block Transform icon to the up arrow, then I clicked the down arrow to navigate down to the down arrow in the toolbar, this jumped my cursor up to the Title but left the block I was on as selected. Very confusing.

**To reproduce**
1. In a block on the page, click `Shift + Tab` to keyboard navigate to the block's toolbar.
2. Click the `Right Arrow` to just to the up arrow icon in the toolbar.
3. Click the `Down Arrow` to move down to the down arrow.
4. Notice the cursor jumped to the Title but still left the other block highlighted as selected.

**Expected behavior**
I expect that clicking the `Down Arrow` I would not jump to the Title block, but drop down to the down arrow in the block toolbar. I know that if I click the `Right Arrow` again, that will move me to the down arrow. But that didn't make a whole lot of sense to me visually.

**Screenshots**

![keyboard](https://user-images.githubusercontent.com/617986/93635608-6fdf9600-f9a7-11ea-8074-b4a33855cb39.gif)

Tested on Firefox.

**Comment by mariohamann** [comment]
This is exactly the problem @afercia mentioned in https://github.com/WordPress/gutenberg/issues/24898#issuecomment-689031547 – and it seems to be another reason to position the buttons side by side.

- As far as I understand the toolbar's ARIA attributes describe its orientation as horizontal:` role="toolbar" aria-orientation="horizontal"`
- The UI does not match the keyboard's behavior – and I think in this case the UI should definitely follow the DOM.

**Comment by afercia** [comment]
Exactly, thanks for pointing that out @mariohamann. This is one more reason to revert the visual change that made the mover buttons stacked vertically. 

The toolbar has a horizontal orientation. The expected interaction is arrows navigation with right and left keys. The vertically stacked mover buttons visually break this expectation. I'd suggest close this issue in favor of #24898.

**Comment by mapk** [comment]
Thanks for catching that, @mariohamann.

>I'd suggest close this issue in favor of #24898.

Will do. Makes sense.
