### ISSUE TITLE
'Cover Image' this term is not defined

### ISSUE THREAD

**Issue by elurie** [WordPress/gutenberg#2546]
v. .09 Users may not know what a cover image is.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
Each block has a description showing up on the block inspector sidebar when the block is selected. In currently released versions, this was not working for the cover image block. It should be fixed in the next release (master) (see #2506).

If this doesn't answer your question, feel free to reopen.
