### ISSUE TITLE
Overlap issue when Image block is aligned left or right

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#25461]
I just noticed the Image block, when aligned left or right, overlaps a Columns block that is inserted above it. When hovering around the center of the Columns block, the Sibling Inserter appears causing another overlapping issue in relation to this right-aligned Image block.

![Screen Shot 2020-09-18 at 9 22 55 AM](https://user-images.githubusercontent.com/617986/93621765-e4f3a100-f990-11ea-85c8-94e08635a29a.png)

**To reproduce**
1. Add several paragraphs of text.
2. Add an Image block and set alignment to right-align.
3. Add a Columns block below the Image block.
4. See the overlap problem preventing interaction on the Columns block.

I imagine this is a problem caused by the right-aligned Image block when above a block that can't be formatted to adjust in width to accommodate that block. 

![Screen Shot 2020-09-18 at 9 28 17 AM](https://user-images.githubusercontent.com/617986/93622055-50d60980-f991-11ea-951a-2c134aa2b086.png)

**Comment by paaljoachim** [comment]
I just tested with WordPress 5.7 beta 1 and Twenty Twenty One theme.
Gutenberg plugin is not activated.
A local site.
Chrome
OSX 10.15.7

Test instructions:
1. Add several paragraphs of text.
2. Add an Image block and set alignment to right-align.
3. Add a Columns block below the Image block.
4. See the overlap problem preventing interaction on the Columns block.

I added a few paragraphs of text.
Added an image block and set it to right align.
Added a columns block below it.

Here is the result:
![Screen Shot 2021-02-10 at 17 36 55](https://user-images.githubusercontent.com/5323259/107540678-999f9080-6bc6-11eb-87ac-99a444416221.png)


I do not see an overlap of the columns block on the Image. So it looks like this has been fixed.
Thanks for creating the issue Mark!
