### ISSUE TITLE
FSE Feedback and some explorations: Test of Full Site Editing and demo templates.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25473]
Using Gutenberg 9.0 and the Twenty Twenty theme.
This is an initial test of Experiments ->
With Full Site Editing and Full Site Editing Demo Templates.

**Call the below a walk through of the current Full Site Editing feature.**
There are lots of changes happening...

There are likely issues I can create of the below feedback. As there are so many changes happening here, I will need to dig up issues to see what has been covered and not.

---------------

Meant as feedback and some brain storming along the way....

I go to Site Editor (beta) and see this page:

![Screen Shot 2020-09-19 at 13 15 55](https://user-images.githubusercontent.com/5323259/93665885-4b082300-fa7a-11ea-8383-ef29f9512b41.png)

I noticed the All Posts (text) and the house icon. (House icon feels out of place and should be removed.) / front-page
On the right Preview and greyed out Update Design button.
A settings icon and the 3 dot contextual drop down.

Looking at the top admin bar it just seems messy. Different contrast items, very little consistency. 

![Screen Shot 2020-09-19 at 13 17 56](https://user-images.githubusercontent.com/5323259/93665958-bce06c80-fa7a-11ea-9922-895b055b1fa6.png)

Black area with a W in it. A blue button. Some icons. All Posts + house icon. A kind of breadcrumbs / front-page.
The right side feels a lot cleaner. 
I wonder about the accessibility of this area....
If I got this right then accessibility should have the page/post title all the way to the left, and the Update/save button should be all the way to the right.

Here is just a sketch... to create some new ideas/inspiration.
![Adjusting-top-gutenberg-bar](https://user-images.githubusercontent.com/5323259/93666273-4002c200-fa7d-11ea-995c-1d34c26a9c55.jpg)

**Clicking some text.**

I click into the "Say Hello to the New New Editor"

![Screen Shot 2020-09-19 at 13 38 09](https://user-images.githubusercontent.com/5323259/93666310-7fc9a980-fa7d-11ea-85f8-12addfe48e53.png)

At first I do not know where in the hierarchy I clicked into. I have to look at the bottom breadcrumbs to realize that I clicked into a Paragraph block which is inside the Cover. This is a general problem for any inner block in relation to parent block.
Yes I can hover the left side of the toolbar and get this:
![Screen Shot 2020-09-19 at 13 43 20](https://user-images.githubusercontent.com/5323259/93666388-231abe80-fa7e-11ea-82bd-7dc6d1f3069a.png) but I am wondering if we need a better visual hint when clicking into something that contains a parent <-> inner block relationship.

I click into the navigation. Then look straight to the bottom breadcrumbs.
![Screen Shot 2020-09-19 at 13 57 52](https://user-images.githubusercontent.com/5323259/93666653-231bbe00-fa80-11ea-9933-cc8b507fa384.png)
 
I notice that I am located in a Template Part: Header -> Navigation -> Link: Try it out

I sure find the breadcrumbs useful.

I click the Navigation in the breadcumbs and notice all of the nav is selected. I then click the Template Part: Header in the breadcrumbs and notice a weird looking toolbar which is very different from the normal Gutenberg toolbars.

![Screen Shot 2020-09-19 at 14 00 24](https://user-images.githubusercontent.com/5323259/93666692-8148a100-fa80-11ea-8755-788c4761dbd0.png)

Lego icon. Drag handlebars. Up/down move arrows. Alignment. Name: Header which I can rename. Then an arrow icon that feels a bit strange. I notice the tooltip says "Choose Another" I click it and see this:

![Screen Shot 2020-09-19 at 14 02 43](https://user-images.githubusercontent.com/5323259/93666732-d389c200-fa80-11ea-91d9-34b44e500d29.png)

Which makes me think of patterns or styles. I wonder why a style is located here.... 
It seems this drop down is meant as a place to select another header template. But it is not clear what it actually is. As there is no description inside of it. Something like "Choose another Header template"

I click to adjust the alignment of the Header and select "Wide Width".
![Screen Shot 2020-09-19 at 14 05 31](https://user-images.githubusercontent.com/5323259/93666789-38451c80-fa81-11ea-826b-17370e6dbe26.png)

----

I click the site title.

![Screen Shot 2020-09-19 at 14 12 19](https://user-images.githubusercontent.com/5323259/93666902-287a0800-fa82-11ea-9d4d-e5830e4db019.png)

The only reason why I know it is the site title is that the bottom breadcrumbs tell me so. I would naturally have thought that it was the page title. Even though it at the top says front-page. So that can be confusing. As the site title sits on the same spot the page title usually is. 

(Sidetracking....) 

Moving the page/post title to the top bar and creating a post/page title block:
https://github.com/WordPress/gutenberg/issues/22621 
Moving the page title to the top bar will finally move it out of the content. Making it optional to show the page title in the content. (Sidetrack end.)

-----

Clicking All posts (in the top bar) and not knowing where it would go...
Ahh it opens a full drop down of options.
![Screen Shot 2020-09-19 at 15 11 45](https://user-images.githubusercontent.com/5323259/93668062-798dfa00-fa8a-11ea-92d9-c2bcc41d6817.png)

Pages text looks like one of the pages mentioned right below it such as Team, Product link control, About, Contact and Sample Page.
Categories - Uncategorized
Posts - various posts are seen.

Can we instead have a drop down showing just..
Pages -> (sub menu area) showing the various pages.
Categoreies -> same as above but showing categories.
All Posts (please remove the house icon. It is confusing seeing it there.) -> same as above but showing posts.

That means one just sees the three options, and side submenu opens when hovering over each.
![All-posts-drop-down](https://user-images.githubusercontent.com/5323259/93668287-b7d7e900-fa8b-11ea-8b99-2e41d5105eca.jpg)

As the drop down is fairly crowded in the current version.

**How to add a Header template?**

I click the Team page.

![Screen Shot 2020-09-19 at 15 21 44](https://user-images.githubusercontent.com/5323259/93668302-d8a03e80-fa8b-11ea-8cf4-aef31b9258cc.png)

I notice it says Team / Index in the top bar. I wonder why it says index.
I also wonder how I get back to the front-page...

I notice no header area here.
I wonder why I do not see the header here when I saw it in the front-page.
I start clicking around to see where and how I can add the header template.

I click Team and it opens the drop down I saw earlier.
I then click index and it opens this drop down.

![Screen Shot 2020-09-19 at 15 26 20](https://user-images.githubusercontent.com/5323259/93668544-28cbd080-fa8d-11ea-8e9e-ba490303d048.png)

I see a title: Template.
Ahh so index is a template.
Overwrite template.... that sounds serious. I click it and this happens. 
![Screen Shot 2020-09-19 at 15 37 24](https://user-images.githubusercontent.com/5323259/93668650-0be3cd00-fa8e-11ea-8f12-1bee2d63cd2e.png)

It looks like it changes from the index template to a page-team template. I can change back to the Parent (weird name) other template it looks like.
I have no idea why it below mentions the current theme. I do not see the relevance with templates.
I decided to revert back to the index template.
I click the index but nothing happens.

I continue looking for how to add a header template. 
I click the block inspector and as nothing is selected it does not show me any information.
It would be nice if it could show me some info when no blocks are selected....

I click the 3 dot contextual menu.
New items I notice are Block Inspector. (Which I wonder why is there.)
I notice a Tools area. (Why use the name Tools? As Tools seems a bit overused in Gutenberg.)
Export the template and parts.
Block manager (which I click and nothing happens.)
Manage all reusable blocks (which wants to leave the page to open a separate screen. Here it would be better with a boxed overlay.)
I notice that some sections have icons and others do not.

I see no way to add a header template to the Team page.

I will stop the walk through there. Hopefully my above comments will help in some way.
As it shows an initial test of Full Site Editing up to where it naturally stopped.

**Comment by mtias** [comment]
Hi @paaljoachim. Almost all the items you mention are either being changed or addressed in different issues. It'd be a lot more helpful if you could add your feedback on those specific issues since a lot of this is work in progress.
