### ISSUE TITLE
Creating a function where php tags close and open causes Reusable Blocks to not load

### ISSUE THREAD

**Issue by catherineconsiglio** [WordPress/gutenberg#25475]
**Describe the bug**
Creating a function where php tags close and open causes Reusable Blocks to not be loaded in the 'Add Block' menu. If that page or post had existing Reusable Blocks, only those blocks will load as options. If the page had a Shortcode block that called that function, it would treat it as if it were a deleted Reusable Block when the page reloaded. An example of the type of function that causes this is shown here.
``` 
function my_function() { ?> 
<p>One usually does something like this to include HTML within your PHP</p>
<?php
}
```
I've tried adding this code to functions.php in a child theme and as a plugin but both methods cause the same issue. The blocks still appear on the /wp-admin/edit.php?post_type=wp_block page.

**To reproduce**
1. Create some reusable blocks.
2. Add a function that closes and opens php tags like the one above to your theme's functions.php file or as part of a plugin
3. Create a post
4. When you try adding reusable blocks, they will not appear in the 'Add Block' menu

**Expected behavior**
Reusable Blocks appear regardless of whether you close and open php tags in a function

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Tested with both default block editor and with Gutenberg plugin version 9.0.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by vdwijngaert** [comment]
Hey @catherineconsiglio,  we were unable to reproduce this, I'm afraid. Are you still experiencing this issue? In order to get this sorted out, we'll need some more information. When you're talking about "adding a function", what exactly are you talking about? A hook? A shortcode?

**Comment by catherineconsiglio** [comment]
Hey there, this got lost in my inbox and I could have sworn I'd closed it.

It was an issue with the way I was implementing my code. I apologize for the confusion.
