### ISSUE TITLE
Provide the ability for  `wp-env` to support a `docker-compose.override.yml` file for plugins that need additional Docker environment customization.

### ISSUE THREAD

**Issue by timnolte** [WordPress/gutenberg#25486]
**Is your feature request related to a problem? Please describe.**
There is a need to support additional Docker local development customization for plugins when using the `wp-env` package. In the previous setup of the `env` command that was part of the `wp-scripts` package, a Docker Compose template could be provided that would be used in creating a `docker-compose.override.yml` file. My specific examples of this need are to provide additional Docker containers for integration testing against mock services. Another use case is trying to capture emails that WordPress sites send using a Mailhog container.

**Describe the solution you'd like**
The `wp-env` package should support the ability for plugins to include a `docker-compose.override.yml` file in their root directory. That file will be detected and used as the source for a new configuration variable `dockerComposeOverridePath`, to be included in the Docker startup. A default `docker-compose.override.yml` file could be provided/generated so that the NodeJS call to docker doesn't fail, or require logic to optionally include using an override file.

**Describe alternatives you've considered**
When advanced docker environment customization is required it seem infeasible to attempt to provide an extensive list of configuration properties that man not be using the majority of the time. Additionally, a large list of configuration properties to attempt to cover all use cases for all plugins seems unsustainable. I was considering providing a `.wp-env.config` property that could be set by the plugin/theme and/or override by a local `.wp-env.override.config` but I decided to keep this override capability more limited in scope and simplify the implementation.

**Comment by noahtallen** [comment]
cc @noisysocks, who I think might have an opinion about this :)

**Comment by noisysocks** [comment]
Hi!

Yes, I don't think this fits into `wp-env`'s goal which is to be a _minimal_ config tool for WordPress development. In particular I don't like that supporting `docker-compose.override.yml` means that we cannot change `wp-env`'s internal `docker-compose.yml` file without considering backwards compatibility. It also makes it harder to offer support for users of `wp-env` as we can make less assumptions about their setup.

Docker & Docker Compose are already very versatile, very well documented and very configurable tools. Developers needing more than a basic WordPress development environment should use Docker & Docker Compose.

**Comment by timnolte** [comment]
I don't understand why you wouldn't want to have this available? You are basically telling me that this environment is completely useless for any plugins that have anything to do with integrations outside of WordPress Core. It seems perfectly feasible to provide this as an advanced feature. I have already spent time working on a PR to support this, and to be clear adding this support doesn't restrict anything about the current docker-compose.yml generation.

**Comment by timnolte** [comment]
It feels like your stance is that this environment only exists to serve Gutenberg and you are not really interested in making this be the recommended local development environment for plugin development. What about the fact that there i snow support for a mail proxy using something like the mailhog Docker image in order to perform integration testing when generating email from WordPress? Again, by restricting this you basically make it impossible to use this for plugin development outside of WordPress Core functionality.

**Comment by noahtallen** [comment]
One counterargument to that is something like `wp-env` start relies on a lot of things to be available in the docker compose file (like the wordpress environment, wp-cli, a mapped wordpress source), etc which you couldn't guarantee with a custom docker compose file. I do agree with you that it seems that _just_ supporting the override file would make it difficult to break back compatibility, since the override file would always override anything.

I do like how awesome it would be to have a shared command syntax for wordpress instances, but it almost feels like a different mode from basic wp-env which does a lot of stuff by itself. Almost as if you could use wp-env syntax to run very basic docker commands against any docker-based WP image.

**Comment by timnolte** [comment]
My request is to only be adding support for the docker-compose.override.yml not a docker-compose.yml.

**Comment by noisysocks** [comment]
> I don't understand why you wouldn't want to have this available?

`wp-env` aims to be a minimal config tool tailored to WordPress plugin and theme development. It should provide an optimised experience for the 80% of environment setups that exist. By restricting scope in this way we can offer better support to (often non-technical) users. For example, it's pretty common that we can troubleshoot a `wp-env` user's issue in the WordPress Slack by getting them to run `wp-env` with `--debug`.

> It feels like your stance is that this environment only exists to serve Gutenberg and you are not really interested in making this be the recommended local development environment for plugin development.

`wp-env` is not intended to be a Gutenberg-specific tool. In fact, Gutenberg requires _far less_ functionality than what `wp-env` currently offers.

> What about the fact that there i snow support for a mail proxy using something like the mailhog Docker image in order to perform integration testing when generating email from WordPress?

Could you create a separate `docker-compose.yml` for the mail proxy and modify your environment's startup script to be `wp-env start && docker-compose up`? Combining the two tools could be a nice middle ground in between using `wp-env` and writing a custom Docker-based setup from scratch.

**Comment by timnolte** [comment]
Again, I don't understand why supporting starting up the `wp-env` environment with an optional `docker-compose.override.yml` affects anyone other than those that specifically configure this option? I would say that any plugin developer using this option should be provided with minimal support, if any. Which would be no different then normal WordPress support where users are instructed to ensure things work with no other plugins and a default WordPress theme. I guess perhaps I'll just have to fork `wp-env` and provide something for myself and others that is more suitable for advanced plugin development.

**Comment by timnolte** [comment]
I should point out that my whole reason for wanting to use `wp-env` is to provide something more "standard" for any contributors to the plugins I maintain.

**Comment by noisysocks** [comment]
This reminds me of the threads you see in [prettier](https://github.com/prettier/prettier) about whether the tool should be configurable or opinionated 🙂

You raise a good point about not having to support folks that use `.wp-env.override.json`, and I agree with you that, all else being equal, it would be nice if all WordPress plugins had a "standard" way to run and test them.

I'll re-open the issue. Happy to defer to @noahtallen as he's the most active maintainer of this package.

If we do add support for `.wp-env.override.json` then please let's dump the contents of this file when `--debug` is provided so that, when troubleshooting issues, we know something outside of our control may be affecting the environment.

**Comment by timnolte** [comment]
> This reminds me of the threads you see in [prettier](https://github.com/prettier/prettier) about whether the tool should be configurable or opinionated 🙂
> 
> You raise a good point about not having to support folks that use `.wp-env.override.json`, and I agree with you that, all else being equal, it would be nice if all WordPress plugins had a "standard" way to run and test them.
> 
> I'll re-open the issue. Happy to defer to @noahtallen as he's the most active maintainer of this package.
> 
> If we do add support for `.wp-env.override.json` then please let's dump the contents of this file when `--debug` is provided so that, when troubleshooting issues, we know something outside of our control may be affecting the environment.

@noisysocks actually in my pending PR I had already added code to dump the `docker-compose-override.yml` when debugging is turned on for that very reason.

Thank you for hearing me out. I hope to have a PR to submit soon once I get everything tested and working.

**Comment by timnolte** [comment]
I'm moving on and will no longer be contributing to this package. There are too many unreasonable maintainers that I'm tired of them shutting down legitimate concerns for all of these NPM packages. I don't have endless hours to attempt to get this package working when huge libraries of unrelated tests fail due to unrelated changes.
