### ISSUE TITLE
How to revert back to old legacy widget style.?!  

### ISSUE THREAD

**Issue by undertaker001** [WordPress/gutenberg#25483]
How to revert back to legacy widgets style page.?! 
![widget](https://user-images.githubusercontent.com/70372403/93711513-7ec17680-fb68-11ea-9892-e6af0014ac26.jpg)

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/issues/24949 is related. There's a PR here to make it possible using the classic editor plugin: https://github.com/WordPress/classic-editor/pull/137

**Comment by draganescu** [comment]
Wait :) There are two ways to get editor (screen) back:

- add to your theme's functions file 
```
add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );
```
or you can also access the old screen via the old url: SITE_URL + `/wp-admin/widgets.php`

Neither of the above won't bring back the old widgets panel in the customizer as long as the Gutenberg plugin is active. This is a bug and there is [work in progress](https://github.com/WordPress/classic-editor/pull/137) to disable that via the classic editor plugin.

**Comment by aristath** [comment]
Closing this one since there's nothing actionable here, and the response by @draganescu above provides solutions on how to get the old screens back :+1:

**Comment by saur8bh** [comment]
> Wait :) There are two ways to get editor (screen) back:
> 
> * add to your theme's functions file
> 
> ```
> add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );
> ```
> 
> or you can also access the old screen via the old url: SITE_URL + `/wp-admin/widgets.php`
> 
> Neither of the above will bring back the old widgets panel in the customizer as long as the Gutenberg plugin is active. This is a bug and there is [work in progress](https://github.com/WordPress/classic-editor/pull/137) to disable that via the classic editor plugin.

Hi, It's not working for me... Is there any new code to disable the trash block widgets?

**Comment by kevin940726** [comment]
@Mrskt We have an updated [doc](https://developer.wordpress.org/block-editor/how-to-guides/widgets/opting-out/) specifically for opting-out of Widgets Block Editor.
