### ISSUE TITLE
Cover Block: Nested inside grid layout can cause cover block to be too large

### ISSUE THREAD

**Issue by charliescheer** [WordPress/gutenberg#25487]
**Describe the bug**
If you are using the cover block and it is nested inside or a grid layout, the compounding styles can cause the height property of the cover block image to display in full size.  This will make the block huge, depending on the image. Check out:

<a href="https://d.pr/v/pbgivl">Example</a>

**To reproduce**
Nest a Cover block in a grid in a column:
<img src="https://cdn-std.droplr.net/files/acc_593859/anvHUc" />
Give that cover block a large image, but set the image to be some what small.

Then preview the page, it will be quite large (see example for more details)

**Expected behavior**
I would expect that the block is the same size on the published page as it was in the editor

**Screenshots**
Should be:

<img src="https://cdn-std.droplr.net/files/acc_593859/ZrlUx1" />

Rendered:

<img src="https://cdn-std.droplr.net/files/acc_593859/JHcJPw" />

**Editor version (please complete the following information):**
- WordPress version: WPCOM 5.5.1 simplesite

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version 85.0.4183.102

**Comment by StevenDufresne** [comment]
Clarifying does it only happen when this order exists: 
Layout Grid -> Column -> Cover?

**Comment by charliescheer** [comment]
That is how I was able to replicate it.

**Comment by StevenDufresne** [comment]
I wonder if this ticket should be moved to (https://wordpress.org/support/plugin/layout-grid), assuming that's the block in question.

**Comment by annacmc** [comment]
Encountered this issue again in 3461951-zen. Could replicate in themes Issue with: Maywood, Spearhead, Seedlet, Barnsbury
Rivington but the issue did not occur in Twenty Twenty or Venture.

**Comment by annezazu** [comment]
@charliescheer I'm going to close this out as this isn't related to the core editor functionality but seems to be a bug with the plugin Steven mentioned above. Looks like you can open a report here: https://github.com/Automattic/block-experiments/issues
