### ISSUE TITLE
Floating an image next to paragraph not intuitive

### ISSUE THREAD

**Issue by emailprotwk** [WordPress/gutenberg#2549]
My testing goal was to add an image and float it next to a paragraph. I added a paragraph first, but found there is no tool to add an image to the left or right of the image. 

I was told to add the image first, float it. Then to add the paragraph, which automatically floated the paragraph.

Also, I don't understand the box around the image. Is this margin or padding? How do we edit it?

**Comment by ammist** [comment]
To add to this:

I tried the following:

1.  Add an image.  This caused the image to fill up the space.  I added a caption below.
2. I added a paragraph below the image.
2. I wanted to make the image smaller than full-width, so I resized the image inside the image block.  
3. The caption continued to take up the full amount of space, the grey border remained around the image.
4. I click "float left" on the image.  The block did not float.  See screenshot.

![2017-08-27_14-01-50](https://user-images.githubusercontent.com/343197/29753932-4d1052d8-8b30-11e7-81e7-abec12faa010.png)

**Comment by iseulde** [comment]
Looks like this is a styling issue. The caption should not be wider than the image.

**Comment by ammist** [comment]
@iseulde Would you fix the styling by adding a max-width inline style to the "figure" container?  If you take a look at the linked ticket (#2555) I've pasted the HTML code that's generated by the caption both in the Gutenberg editor and in the HTML for the front-end.   After looking at the code I think I could do this (good first task!) but I'm not sure what the conventions are supposed to be for setting hard-coded widths (for things other than images)

**Comment by ammist** [comment]
It looks like this might be fixed in https://github.com/WordPress/gutenberg/pull/2682.  Will test again w/ @emailprotwk when that gets wrapped into a release.

**Comment by mtias** [comment]
Closing as fixed.

![image](https://user-images.githubusercontent.com/548849/33018745-e641fdb2-cdf7-11e7-838a-618180f5a496.png)
