### ISSUE TITLE
Navigation Block: Add alignment options for menu

### ISSUE THREAD

**Issue by mikeicode** [WordPress/gutenberg#25508]
**Is your feature request related to a problem? Please describe.**

The horizontal navigation block (and probably the vertical style also) should have options to allow you to set the menu to center or right alignment.

Currently the menu is left aligned:

![https://d.pr/i/8c8JyB](https://d.pr/i/8c8JyB+)

**Describe the solution you'd like**

Something like this could be used for a center aligned menu:
```

nav:not(.is-vertical).wp-block-navigation .wp-block-navigation__container {
  justify-content: center;
}
```

![https://d.pr/i/W1yi9q](https://d.pr/i/W1yi9q+)

And for a right alignment menu:

```
nav:not(.is-vertical).wp-block-navigation .wp-block-navigation__container {
  justify-content: flex-end;
}
```

![https://d.pr/i/EI6f58](https://d.pr/i/EI6f58+)

**Comment by talldan** [comment]
@mikeicode The block does have these settings but there's a bug that causes them to be hidden.

This should be fixed as part of #25329, so hopefully these options will return soon.
