### ISSUE TITLE
Gutenberg 9.0.0. contains the PHP notice: Notice: Undefined property: WP_Block_Type::$supports

### ISSUE THREAD

**Issue by vjik** [WordPress/gutenberg#25500]
**Describe the bug**
After update 9.0.0 appears errors on edit post screen and on site:

```
Notice: Undefined property: WP_Block_Type::$supports in \wp-content\plugins\gutenberg\lib\block-supports\colors.php on line 63
```
This bug was already in version 8.8.0 #24922

**To reproduce**
1. Enable WP_DEBUG
2. Go to edit post screen or page on site
3. See errors

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- gutenberg plugin 9.0.0

**Comment by aristath** [comment]
@vjik have you tried updating wp-core to its latest stable version? That should resolve the issue...
If that fixes the issue, then we'll need to test Gutenberg with WP 5.4 and fix any issues that may exist there (we still support WP 5.4)

**Comment by vjik** [comment]
@aristath No I not tested in latest stable version, my site planned update only on next version of WordPress :(
Hope you can fix it for WP 5.4.2...

**Comment by vjik** [comment]
@aristath in gutenberg 9.1.0 also has this problem.

**Comment by annezazu** [comment]
@vjik looping back here :) Does this still happen with WordPress 5.6?

**Comment by vjik** [comment]
Seems WP 5.6 + Gutenberg 9.5.2 no errors

**Comment by annezazu** [comment]
Going to close this out since the problem seems to now be resolved with more recent versions. Thanks for initially reporting!
