### ISSUE TITLE
Big icons of plugins in the editor bar difficult to use genuine editor options

### ISSUE THREAD

**Issue by Tesacu** [WordPress/gutenberg#25511]
Some plugins (like Gutentor, Elementor, etc.) insert very big icons in the editor bar that hide and/or difficult using genuine editor options like Save, Save as a draft or Preview. And that causes malfunctions and errors when using Gutenberg a lot of times.

There shoul be some kind of limitation that would not allow to include that big icons to plugins developers.
![iconos-builders-wp](https://user-images.githubusercontent.com/6785912/93783636-38355000-fc2c-11ea-88ea-13af65f70fe2.jpg)

**Comment by talldan** [comment]
@Tesacu Unfortunately the plugins are injecting the large style button elements into the web page, they're not using an official API (in fact, this is the exact reason there isn't an official API to do this).

There's not technically much that can be done to remove these, it's really up to the plugin author.
