### ISSUE TITLE
Insert Block 'Recent' tab would be better  if removed

### ISSUE THREAD

**Issue by elurie** [WordPress/gutenberg#2551]
What you see first is RECENT tab. This, if not looking closely would make you think that the items in RECENT are the only things you can add. A second, more careful look when I could not find what I needed, I noticed the second tab called BLOCKS. Better, to stick with Blocks, since this is the basis of the interface.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by azaozz** [comment]
I've encountered this too. IMHO the solution is to not use "real" tabs (only one visible at a time) but instead have all in a long list and scroll to the beginning of each subsection when clicking on the "Recent", "Blocks", "Embeds" buttons.

**Comment by karmatosed** [comment]
I think a solution 'could' be to reorder the tabs. What about having the recent as the last tab and therefore meaning it's not first things you see? I'm not sure if this simply hides a really useful thing though. To me it is useful and I have observed people using it.

I am not sure a long list helps from an experience perspective, it's unwieldily and difficult for some users to navigate.

**Comment by karmatosed** [comment]
For now closing this as I feel reordering doesn't always work for users. I've seen stronger work flows happen because of the recent and would like to see in testing if this keeps coming up. We can always reopen.
