### ISSUE TITLE
Feature request: Add CSS id or class to any block.

### ISSUE THREAD

**Issue by emailprotwk** [WordPress/gutenberg#2552]
This is extremely important. 

I added an H2 element to a post, but I couldn't add a class to the element. 

Please, please add this function to the block Heading Settings.

I see you have it on the image block. See Additional CSS Class.
<img width="1110" alt="screenshot 2017-08-27 13 41 10" src="https://user-images.githubusercontent.com/1005026/29753806-20504458-8b2e-11e7-8df8-e606acd80bff.png">

**Comment by youknowriad** [comment]
Additional CSS support is opt-out and the heading was opting out of this feature for now. There's this PR should resolve this issue #2507

**Comment by mtias** [comment]
@youknowriad might be ok to add it for headings now, specially since the "advanced" panel is collapsed by default.

**Comment by youknowriad** [comment]
This was blocked by the fact that the "generatedClassName" and the "custom ClassName" were using the same "support" key. This is now fixed. And the heading block already includes a custom className field
