### ISSUE TITLE
Block toolbar disappears when hovering over it in Firefox

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#25526]
**To reproduce**
1. Open the post editor
2. Ensure 'Top toolbar' mode is disabled
3. Add a block, any block
4. Try interacting with the block toolbar
5. Observe the block toolbar disappears

**Expected behavior**
The block toolbar stays visible

**Screenshots**
![toolbar](https://user-images.githubusercontent.com/677833/93846866-e64a0400-fcd7-11ea-9407-0ca3ac29ec17.gif)

Observed in `master` (latest commit was d2dfcffab6b75043d92c4a389a795816e4592210), using Mac OS Firefox

**Comment by talldan** [comment]
Noting that I couldn't reproduce this in Chrome.

**Comment by talldan** [comment]
On #25535, @aristath mentions the ticket that this was introduced by:
> Investigated using git bisect, the issue is a result of #23034

**Comment by ellatrix** [comment]
So strange that it's Firefox only. :) Looks like it has something to do with multi select since `contenteditable` is removed.

**Comment by noahtallen** [comment]
I also notice this. Just noting my reproduction steps, which are basically the same:

1. Click into a block for editing (like a paragraph block). Note the toolbar
2. Move your mouse away from the block quickly
3. Observe that the toolbar goes away and the block acts as if it is selected directly (i.e.  you loose your place)

It's almost as if you're clicking "escape"! For me, it happens any time you move the mouse quickly away from the block.
