### ISSUE TITLE
Update the default colour and gradients to come from theme.js for demo app.

### ISSUE THREAD

**Issue by enejb** [WordPress/gutenberg#25536]
Currently on mobile the default colors and gradients are not there any more in the demo app. 

https://github.com/WordPress/gutenberg/pull/25523 try to fix it by adding the colour back to the default settings that are mobile only. 

Where should we read the default color options? Should it be from the `theme.json` file?

The PR that removed the default settings was #25419.

**Comment by mtias** [comment]
This seems handled. Feel free to reopen otherwise.
