### ISSUE TITLE
Video block doesn't appear when searching for video in the small block picker

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#25534]
**Describe the bug**

When using the small block picker from the [+] button in between existing blocks, the Video block type doesn't show up if you search for the word "video".

I think this might be because this block picker is now restricted to six results, and there are many block types that support video.

**To reproduce**

1. Edit a post
2. Click the [+] button below an existing block
3. Search for "video"
4. Observe that the Video block type does not appear

**Expected behavior**

The Video block type really ought to appear

**Screenshots**

<img width="379" alt="" src="https://user-images.githubusercontent.com/208434/93885158-c0bef980-fcdb-11ea-8480-b895c507e97c.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6 alpa
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Comment by mtias** [comment]
This was improved generally in #25105 (prioritizes name matches). We should probably consider to back port it to a minor release as it can be pretty frustrating:

![image](https://user-images.githubusercontent.com/548849/93899097-42228600-fcf4-11ea-83ea-771076a4050f.png)

**Comment by tellthemachines** [comment]
I can no longer reproduce this on the master branch. Can we close this issue now?
