### ISSUE TITLE
Can't add a closing angle bracket in Custom HTML block.

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2553]
![blank-screen-after-typing-closing-angle-bracket](https://user-images.githubusercontent.com/14795150/29753889-57730cb2-8b2f-11e7-917f-0e4dcbc69a1c.png)

## Issue Overview
I was trying to insert html code (just a link with a class applied) into a custom HTML block. When I attempted to add the closing angle bracket, I was suddenly sent to a white page

## Steps to Reproduce (for bugs)
1. Add a custom HTML block
2. Start typing some HTML (in my case it was `<a class="button" href="https://gutenberg.eastbaywp.com/wp-login.php">Login or Register</a>`)
3. The first time you try to type a right angle bracket `>`, you'll be sent to a white page. Your changes will not be saved in the page or post.

Gutenberg 0.90, Chrome 60.0.3112.101 for Windows

## Expected Behavior
The right angle bracket should appear the same way the left angle bracket does.

## Current Behavior
As soon as I type a closing angle bracket, I get a blank page.
![inserting html block](https://user-images.githubusercontent.com/14795150/29753884-52cd4236-8b2f-11e7-9c19-1cae826e543d.png)

**Comment by karmatosed** [comment]
Testing this on 1.1 (the latest release) and in Chrome, I can't replicate. If you are able to please let us know, however for now closing.

**Comment by wpfangirl** [comment]
Let me update and check. I've been out sick for a couple of weeks, so I'm behind following up on these things.
