### ISSUE TITLE
Inspiration from various builders

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2554]
This is a post based on various layout and page builders that can inspire the development of Gutenberg.

https://wordpress.org/plugins/elementor/
https://elementor.com/
Uses a "customizer" like left sidebar to add and customize various blocks.
I have used Elementor for a few projects that find the customization options fairly easy to use.

https://www.verst.co/
Reminds me a bit about the block system that Gutenberg is aiming for.
I have not tested it but want to add it as inspiration.

https://craftcms.com/features/live-preview
It looks like a mix of edit in the left sidebar and in the content area.

**Comment by mtias** [comment]
These had been looked at at various points in time, specially during prototype phase. If there are specific things you want to discuss or propose, feel free to open issues with those.

**Comment by paaljoachim** [comment]
Ok. I can do that.

**Comment by mtias** [comment]
Thanks!
