### ISSUE TITLE
Document Actions: Polish Animation

### ISSUE THREAD

**Issue by noahtallen** [WordPress/gutenberg#25545]
An animation appears when selecting a template part in the editor:

![2020-09-17 15 27 12](https://user-images.githubusercontent.com/6265975/93535171-4b2de480-f8fb-11ea-81b9-9c0dc665629e.gif)

@jeyip said he had ideas about improving the performance of this animation, so I'm adding this issue to the backlog :) I think some other aspects could be improved as well. (like the way the text starts visible below the header)

**Comment by Addison-Stavlo** [comment]
Some more info on how the animation should look - https://github.com/WordPress/gutenberg/pull/25348#issuecomment-698516199

**Comment by jeyip** [comment]
For more context, we can probably create a fadeIn effect with `opacity` and `transform` CSS properties, which [would be more performant](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/) than the current implementation.  This, however, would probably be a smaller optimization and so is prioritized accordingly.

**Comment by noahtallen** [comment]
Also noting that we need to update the other visuals (like font style) per the linked comment
