### ISSUE TITLE
Image captions don't wrap, causing problems w/ left and right-aligned images

### ISSUE THREAD

**Issue by ammist** [WordPress/gutenberg#2555]
## Issue Overview
I added an image, and aligned it left.  The paragraph text floated next to it as expected.  I then started typing in the caption box, expecting it to wrap under the image.  Alas, it did not - it pushed the wrapped text over to the right.

## Steps to Reproduce (for bugs)
1. Add an image block.  Select "Left-align"
2. Add a paragraph block. The paragraph float nicely.
3. Add a long sentence as the image caption.
4. The paragraph is pushed below the image as the caption continues to grow.

## Expected Behavior
Once I've inserted and sized an image, the caption should not need manual line breaks to wrap inside its box.

## Current Behavior
Caption doesn't wrap until it hits the edge of the content area, pushing down any content floated to the side of the caption.

![2017-08-27_14-10-09](https://user-images.githubusercontent.com/343197/29754052-dc3d5454-8b32-11e7-8537-61effca3c150.png)

(that's a manual linebreak next to 'really').

## Related Issues and/or PRs
Might be a duplicate of this: https://github.com/WordPress/gutenberg/issues/2543
And this: https://github.com/WordPress/gutenberg/issues/2548
And this: https://github.com/WordPress/gutenberg/issues/2549

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ammist** [comment]
It looks like the code that's generated for the image + caption doesn't get a width and height in the HTML.  

Here's the "Text" view of the image + caption above. 

![2017-08-27_14-25-34](https://user-images.githubusercontent.com/343197/29754118-c1b225b4-8b33-11e7-95f5-74871c5874bb.png)

The HTML generated for the front-end:

![2017-08-27_14-30-45](https://user-images.githubusercontent.com/343197/29754154-783ac73c-8b34-11e7-8436-ba0c3c4aeca7.png)

There does not appear to be a way to correct this on the front-end using the stylesheet, since there's no class or style on the "figure" to tell it how wide to be.  To size the box according to the wishes of the person using Gutenberg would require some JavaScript based on the image size inside the "figure".  Oy.

**Comment by karmatosed** [comment]
I just tested this using Twenty Seventeen and the latest version 1.1.0. I used Chrome, incase that's the issue. I am unable to replicate and see this:

![2017-09-07 at 10 37](https://user-images.githubusercontent.com/253067/30156950-e824041e-93b8-11e7-809e-db1df5e4493c.png)

If you are still able to recreate, please report back and we can reopen though.

**Comment by youknowriad** [comment]
This is fixed by #2682 but I think it's not released yet.
