### ISSUE TITLE
"View Post" link is not available when editing previously published content in Gutenberg

### ISSUE THREAD

**Issue by ammist** [WordPress/gutenberg#2557]
## Issue Overview

When editing content, I frequently go back to the "live" version to compare what I've done.  There's usually a link in the admin bar (and via the post permalink) to allow you to view the live version of the post.  This link is missing in Gutenberg - only "preview" is available.

When making an "update" to a post, the "view post" appears in the update message, but it disappears when you start making more changes.

## Steps to Reproduce (for bugs)

1. Publish a post or page
2. Edit that post of page in Gutenberg by clicking the "Gutenberg" 
3. Look  on the Gutenberg page for a link to the "live" version of that post or page.

## Expected Behavior
Add a "view post / page" link in the admin bar when using Gutenberg, if the post/page is published.

**Comment by karmatosed** [comment]
Preview is showing the live view for Gutenberg. I don't see at this point as a result why having both would be better. Within Gutenberg viewing the post and page is 'Preview'.
