### ISSUE TITLE
Navigation Block - Add support for current-page-ancestor

### ISSUE THREAD

**Issue by nathanp** [WordPress/gutenberg#25575]
The navigation block currently supports the `current-menu-item` class, which is helpful when wanting to indicate the user is on a specific page.

What would make this even more useful is adding support for the `current-page-ancestor` and similar classes.

If there's a filter or something I could use in the meantime, that would be helpful.

Thanks!

**Comment by mtias** [comment]
Agreed all the standard menu classes should be supported.

**Comment by pauldrummond** [comment]
If the navigation block doesn't have link sub-menus `current-page-ancestor` class isn't added when viewing a child page. For example, if I'm currently viewing _www.mysite.com/books/book1/_ I want the link to _www.mysite.com/books/_ in the nav block to have the `current-page-ancestor` class.
I've written a simple plugin to handle this client-side with vanilla Javascript. Not sure how to handle it on the server side though.

**Comment by Marc-pi** [comment]
https://github.com/WordPress/gutenberg/pull/40778

**Comment by aristath** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/40778
