### ISSUE TITLE
Searching for previously created page does not show results in paragraph block on add/edit link

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#25577]
**Describe the bug**
Searching for previously created page does not show results in paragraph block on add/edit link.

**To reproduce**
1. Create/edit a paragraph block
2. Create a link on a word
3. Search for another page to link to
4. No results show
5. If you search for a space, all the pages show (including the ones you were looking for earlier)
6. The AJAX which gets the results responds 200

**Expected behavior**
Results shown for selection so can add the link to an existing page.

**Screenshots**
Searching:
![image](https://user-images.githubusercontent.com/56840277/94042274-436eb400-fdc3-11ea-91a4-9465db5d5031.png)

Searching for a space (notice purchase process page trying to find in previous screenshot does exist here):
![image](https://user-images.githubusercontent.com/56840277/94042335-597c7480-fdc3-11ea-9456-5e31a428a549.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? Not installed

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by mapk** [comment]
I just tested this with WP 5.5.1 and no Gutenberg plugin. It seems to work fine. The reason nothing shows up until you type a space is because nothing has been searched yet. Once the spacebar is hit, the results show anything with a space in it.

![link](https://user-images.githubusercontent.com/617986/94094607-c6e4d100-fdd4-11ea-9b13-f953731e7d32.gif)

**Comment by ninetyninew** [comment]
@mapk I'm seeing a completely different link editing box (see my screenshots compared to yours) and even the link icon on the block toolbar is different, why is this? I'm running 5.5.1 the same as you??
