### ISSUE TITLE
Document Actions: Make page name and page slug editable in the site editor topbar

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#25586]
### Description
As a user, I want to edit the page title and slug in the site editor (which currently isn't possible)

### Potential Mocks
**THESE ARE NOT FINALIZED DESIGNS**

![post-edit-document-menu](https://user-images.githubusercontent.com/191598/92275509-3560fe00-eebd-11ea-9df6-78b639b3182c.gif)

### Related Issues:
https://github.com/WordPress/gutenberg/issues/25546

**Comment by jeyip** [comment]
Currently on hold and awaiting further discussion @dubielzyk

**Comment by paaljoachim** [comment]
I believe the most important part right now is just moving the page/post title up into the top bar, and have a drop down with the permalink available. That seems to be the MVP at present time. At the same time we also need a page/post title block.

Getting this in a soon as possible would help us see how it functions with having the page/post title in the middle of the top bar. As one would be able to gain a lot of feedback from this.

**Comment by noahtallen** [comment]
@paaljoachim yep, we're working on the page/post title bits of this right now. We're waiting a few days for some more design iterations on the dropdown aspect of things, since the early design prototypes generated a lot of feedback and discussion. Jeremy has a PR open (#25386) which starts exploring the dropdown approach if you want to check it out

**Comment by shaunandrews** [comment]
I posted design updates GIFs over in https://github.com/WordPress/gutenberg/issues/20877#issuecomment-698466981

![document-details](https://user-images.githubusercontent.com/191598/94185649-8f793180-fe73-11ea-85f5-6c900c0ddea8.gif)

**Comment by dubielzyk** [comment]
If the label isn't clickable, I don't see why we wouldn't make the whole thing a button to increase click area. Like where this is heading

**Comment by noahtallen** [comment]
> I don't see why we wouldn't make the whole thing a button to increase click area

It addresses the accessibility feedback that if the text is going to be a button, it should describe the action the button will do. ([this comment](https://github.com/WordPress/gutenberg/issues/25085#issuecomment-694313931) explains why).

Though I do totally agree that the text being a button would be very helpful for one set of users, it seems that it would be a hindrance for another.

**Comment by jeyip** [comment]
We will not be making page name and page slug editable in the **site editor** for now. We'll return to this whenever "template editing" is better developed.

**Comment by noahtallen** [comment]
I vote to leave the issue open for now, just on hold :)

**Comment by paaljoachim** [comment]
This looks like a good way forward.
I do feel there is agreement of adding the permalink and the title to the drop down.
I would suggest going with @shaunandrews suggestion but leaving out the template part. That can be added in the next iteration.

**Comment by youknowriad** [comment]
The action bar has been redesigned entirely in 6.3 making this issue irrelevant IMO. If we want further iterations on the action bar, we should open new issues I think.
