### ISSUE TITLE
#feature-request Convert multiple paragraph blocks to list

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2559]
## Issue Overview
I'd like to be able to select multiple paragraph blocks and convert them into an ordered or unordered list, the way you can now in TinyMCE.

## Current Behavior
It's possible to select multiple paragraph blocks by clicking and dragging, but the only thing you can do with them is delete them. 

## Possible Solution
Haven't got the faintest idea how to code it, but it would be great if you convert multiple paragraph blocks into a single list block.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
duplicate #539?

**Comment by wpfangirl** [comment]
Sorry for the duplicate. I did try to search to see whether it had been reported.

**Comment by youknowriad** [comment]
@wpfangirl no problem, with your meetup friends, you'be been creating some great issues. Thank you for the feedback.
