### ISSUE TITLE
Text Columns, can't add an image. Feature request

### ISSUE THREAD

**Issue by emailprotwk** [WordPress/gutenberg#2560]
Love that I can add columns with WordPress core, but I can't add an image unless I copy HTML from some place else.

**Comment by youknowriad** [comment]
The Text Columns are only for text, adding images (or any other block) as columns is part of the customization focus. I expect this to come in a V2 of Gutenberg.

duplicate #219?

**Comment by clickbrain** [comment]
Gutenberg looks great over all, but.... 

Just my opinion, but I would move adding images/video to a column up on the priority list if it was my call. These are pretty standard layouts for web pages these days, especially when it come to landing pages, etc. I realize you have to make priorities, but this was one of the first things I tried to do and suspect many users will as well resulting in a negative response to Gutenberg and less likely to adopt when they can use Divi or some other plugin/theme of that type to get a much richer layout. This is all assuming that I will be able to use Gutenberg on pages. If not, then likely less a priority for Posts, but wanted to put in my 2 cents.

**Comment by youknowriad** [comment]
Thanks for the feedback @clickbrain @emailprotwk I understand this is a priority for a lot of users, but we need to make choices, let's move the discussion to #219.
