### ISSUE TITLE
Possible bug with accessing transferData in `Draggable` component

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#25602]
Hi 

So I've been working with the `Draggable` component, which was fairly straight forward to setup, however, I'm having trouble access the `transferData` prop.  Taking simplified version of the example in the docs and adding some console logs:

    const onDragStart = ( e ) => {
    	console.log( 'on drag start', e );
    	console.log( e.dataTransfer.getData( 'text' ) );
    	console.log( 'types: ' + e.dataTransfer.types );
    };
    const onDragEnd = ( e ) => {
    	console.log( 'on drag end', e );
    	console.log( e.dataTransfer.getData( 'text' ) );
    	console.log( 'types: ' + e.dataTransfer.types );
    };
    const MyDraggable = ( { onDragStart, onDragEnd } ) => (
    	<div id="draggable-panel">
    		<Draggable
    			elementId="draggable-panel"
    			transferData={ { test: 'reply' } }
    			onDragStart={ onDragStart }
    			onDragEnd={ onDragEnd }
    		    >
    			{ ( { onDraggableStart, onDraggableEnd } ) => (
    				<div
					className="example-drag-handle"
					draggable
					onDragStart={ onDraggableStart }
					onDragEnd={ onDraggableEnd }
    				>
    					<Icon icon={ more } />
						</div>
    			) }
    		</Draggable>
    	</div>
    );

I can't see any logical way to access that transfer data - all the console logs are coming out as empty...

Is this a bug, or am I just doing it wrong? 

Thanks!

**Comment by talldan** [comment]
Hi @rmorse, I'm not sure, it seems to work in the places it's used within the block editor itself. I tested by setting a breakpoint here:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-draggable/index.js#L75

And then in the browser console ran the following:
```js
JSON.parse( event.dataTransfer.getData( 'text' ) )
```

Which returned block data:
```js
{
  "type": "block",
  "srcClientIds": [
    "54e6189c-30a6-4cbe-8e1d-83f6ff1e6d85"
  ],
  "srcRootClientId": "40563926-7ec3-48ee-af01-12c7ae30990f"
}
```

There doesn't seem to be much difference to your code from what I can see.

**Comment by rmorse** [comment]
Hmmmm, that does make sense, I'll have another dig into the code and get back to you if I find anything...

**Comment by youknowriad** [comment]
Maybe this is due to a missing `<DropZoneProvider>` at the top of your application. Anyway, it seems to work properly, so I'm  closing.

**Comment by rmorse** [comment]
@youknowriad that was exactly it (although I never bothererd to get it working) - I've been using Gutenberg components in custom React apps
