### ISSUE TITLE
Site Editor: Rename LeftSidebar

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#25616]
Discussion: https://github.com/WordPress/gutenberg/pull/25506#discussion_r493768240

We should rename the `LeftSidebar` component to something generic. Left and right can be confusing, when the page is viewed in a RTL language, then the left sidebar will be on the right side.

Since we have another `Sidebar` component in `edit-site`, we need to come up with something else.

**Comment by mtias** [comment]
We should definitely move away from any visual location name. For the W menu I think we should call it `SiteNavigation` or `MainMenu`

**Comment by mattwiebe** [comment]
> We should definitely move away from any visual location name. For the W menu I think we should call it SiteNavigation or MainMenu

It's currently `NavigationSidebar`, what's currently `LeftSidebar` actually contains the Block Library, so I think I'll just call it `BlockLibrary`. I'd tend to leaving `NavigationSidebar` as-is.
