### ISSUE TITLE
Can't add column to tables

### ISSUE THREAD

**Issue by emailprotwk** [WordPress/gutenberg#2561]
Tested Tables in version 0.9, I can't add columns. The insert icon appears cut off as well.
<img width="720" alt="screenshot 2017-08-27 15 39 54" src="https://user-images.githubusercontent.com/1005026/29754633-01fc8a88-8b3e-11e7-84db-be8b05c74350.png">

**Comment by EphoxJames** [comment]
Caused by https://github.com/WordPress/gutenberg/pull/2443
Worked around by https://github.com/WordPress/gutenberg/pull/2492

**Comment by EphoxJames** [comment]
I have merged the workaround so this should now be fixed.
