### ISSUE TITLE
Color picker not showing Cancel and Apply buttons

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#25646]
**Describe the bug**

On the color picker bottom sheet that's displayed when choosing a custom Button block color, the "Cancel" and "Apply" buttons can sometimes disappear for no apparent reason.

While the following steps describe the scenario for Button Text Color, the same might apply for Gradient Color. Also, this likely affects the Cover block, not just the Button block.

**To reproduce**
1. Open the Gutenberg demo app for iOS
2. Add a Button block
3. Go to Block Settings
4. Tap Text Color 
5. Select Custom
6. Choose a color and tap Apply
7. Tap Custom again and notice the bottom sheet doesn't have a "Cancel" or "Apply" button

**Expected behavior**

The "Cancel" and "Apply" buttons should be available the second time the user enters the color picker, just as they were available the first time.

**Screenshots**

(The screen recording below doesn't show the default colors, but that's due to a different issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/2649 which is now resolved.)

<table><tr><td><img width="300" alt="Screen recording showing color palette missing Apply and Cancel buttons" src="https://user-images.githubusercontent.com/1898325/93826303-ee049c80-fc34-11ea-9431-62e4568795f8.gif"></tr></td></table>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14
 - Demo App Version `master` branch

**Comment by chipsnyder** [comment]
@guarani (Not Urgent) I'm pretty sure this issue has now been resolved (Tested in WP iOS 16.7) can you confirm if you're able to reproduce it or not?

**Comment by guarani** [comment]
> @guarani (Not Urgent) I'm pretty sure this issue has now been resolved (Tested in WP iOS 16.7) can you confirm if you're able to reproduce it or not?

Yes, this looks to have been fixed (checked WPiOS 16.7 beta). Closing this now 👍
