### ISSUE TITLE
Drag/drop sorting stopped working

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#25654]
(Originally noticed by @ellatrix)

It looks like drag/drop sorting in Gutenberg stopped working with the latest changes.

Pulling up `console.log` shows these errors:

<img width="728" alt="Screen Shot 2020-09-25 at 5 42 51 PM" src="https://user-images.githubusercontent.com/2322354/94318829-5dd99680-ff57-11ea-802b-60f17d14607e.png">

In my initial digging, it may be related to this update (but not yet confirmed):
https://github.com/WordPress/gutenberg/pull/25332

**To reproduce**
1. Check out `master` branch
2. `npm run dev`
3. View  post
4. Attempt to drag/sort posts

**Editor version (please complete the following information):**
Gutenberg `master` branch

**Comment by ItsJonQ** [comment]
Update: I tried reverting the `drop-zone/provider` file, but no luck 🤔 

```
packages/components/src/drop-zone/provider.js
```

**Comment by ItsJonQ** [comment]
Update: I was able to "fix" it by adding a quick return for the `isWithinElementBounds` method if `element` is `undefined`:

```js
const isWithinElementBounds = ( element, x, y ) => {
	if ( ! element ) return false;

	const rect = element.getBoundingClientRect();
	/// make sure the rect is a valid rect
	if ( rect.bottom === rect.top || rect.left === rect.right ) {
		return false;
	}

	return (
		x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom
	);
};
```

I'm not sure why a `dropZone` item would be undefined though 🤔 .

**Comment by ItsJonQ** [comment]
That's strange... after switching around some branches and rebuilding a couple of times.. it's working normally again?

Maybe this issue is isolated to my environment.

I'll leave it open for a bit, just in case anyone else is experiencing problems 🙏

**Comment by ellatrix** [comment]
The error is fixed, and I can now drag in Firefox, but I still cannot drag in Chrome or Safari.

**Comment by ellatrix** [comment]
Does anyone experience the same in Chrome?

**Comment by ItsJonQ** [comment]
@ellatrix That's interesting 🤔 . It's working for me again in my local Chrome. I'm not sure how to reproduce the bug :(.

The only thing I can think of is maybe I had some weird block configurations in my local Gutenberg post.

**Comment by tellthemachines** [comment]
I can't reproduce this on Chrome with the latest from this repo. Did it happen with any particular blocks?

**Comment by talldan** [comment]
Same here, unable to reproduce this (tested Firefox and Chrome on Mac OS).

**Comment by ItsJonQ** [comment]
This is so odd 🙈

**Comment by ellatrix** [comment]
![drag](https://user-images.githubusercontent.com/4710635/95068316-cec63e80-070d-11eb-9b39-4bf97eac176c.gif)

I see this since a while now 🤔

**Comment by merapi** [comment]
All fine for me in Chrome/Firefox, @ellatrix is that on current `master`? what Chrome version exactly (and OS)?

**Comment by ellatrix** [comment]
I figured out that the problem is the e2e test plugin that disables CSS animations. If that plugin is active, drag and drop stops working.
