### ISSUE TITLE
Add wide- and full-width support to headings

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#25655]
**Is your feature request related to a problem? Please describe.**
Using wide-width or full-width container blocks like columns, groups, and covers, you can create some great text layouts. However, there's no way to align headings, for example, to the left-most edge of the container width, without putting it inside a container of it's own (like a columns block). This creates both UI and markup bloat, when all I want to do is adjust the width of a heading, like so:

![image](https://user-images.githubusercontent.com/2846578/94320709-9b402300-ff5b-11ea-8b84-6a0248fb41b7.png)

**Describe the solution you'd like**
Add wide- and full-width support to heading blocks.

Note: this issue came up in relation to https://github.com/WordPress/twentytwentyone/issues/37.

**Comment by shaunandrews** [comment]
I'd expect to be able to use a Group block that contains the Heading and Columns block — and set the Group block to wide width. Here's some psuedo-code for how that'd work:

```
<!-- wp:group {"align":"full"} -->
    <!-- wp:heading -->

    <!-- wp:columns {"align":"full"} -->
        <!-- wp:column -->
            <!-- wp:heading {"level":3} -->
            <!-- wp:paragraph -->

    <!-- wp:columns {"align":"full"} -->
        <!-- wp:column -->
            <!-- wp:heading {"level":3} -->
            <!-- wp:paragraph -->

    <!-- wp:columns {"align":"full"} -->
        <!-- wp:column -->
            <!-- wp:heading {"level":3} -->
            <!-- wp:paragraph -->
```

This, however, doesn't work either. It seems like this could be a better problem to solve; Rather than adding width controls to every block, I expect that child blocks should observe the width of their parent block.

**Comment by melchoyce** [comment]
That gets problematic if you want, for example, to have some regular-width text inside a full-width background container, like a cover or group block 😕

**Comment by shaunandrews** [comment]
In this imaginary land in my mind, I think you could still do that with a nested group:

```
<!-- wp:group {"align":"full","backgroundColor":"secondary"} -->
    <!-- wp:paragraph -->

    <!-- wp:group {"align":"default"} -->
        <!-- wp:paragraph -->
```

The first Group sets it's width to full, and the first Paragraph block observes this and also displays full.

The second, nested Group sets it's width to default (which is imaginary and doesn't exist) and the second, nested Paragraph block observes this and also displays normal.
