### ISSUE TITLE
Broken plugins with color palette change

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#25652]
The changes introduced in #25419 break existing plugins that use the color palette. 

Two of the plugins that I maintain, [Starscape](https://wordpress.org/plugins/starscape/) and [Waves](https://wordpress.org/plugins/waves/), both break with this change.

I see that it was marked as a breaking change, but if possible it would be nice to maintain that backwards compatibility so that we're not breaking existing plugins.

cc @jorgefilipecosta @youknowriad

**Comment by nosolosw** [comment]
I think https://github.com/WordPress/gutenberg/pull/25738 fixen this one.
