### ISSUE TITLE
Why use writing flow for the navigation block editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25651]
In this [comment](https://github.com/WordPress/gutenberg/pull/25592#issuecomment-698269398) @afercia raises this issue:

### Question: Why the block view uses WritingFlow?

If it's actually used for some interaction on the list view, then there should be a user setting to disable it like it was done for the block editor. I'm not sure where it's actually used though, but maybe I'm missing something.

At 1st glance it could be disabled as the UI is all fixed and the blocks are quite discrete, this editor being so "structured" should not benefit from the enhancements writing flow offers.

**Comment by noisysocks** [comment]
I think I added `WritingFlow` as it's in the [example code for how to use `BlockEditor`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/README.md#usage).

**Comment by talldan** [comment]
Without `WritingFlow` there would be no way to navigate between blocks using the keyboard and navigation mode would also not work.

Feels like its needed to me, but perhaps the original question is more related to particular aspects of `WritingFlow` and disabling them.

**Comment by afercia** [comment]
Hm yep maybe I'm not updated about all the things WritingFlow actually does. To me, it's the thing that enables navigating through blocks sequentially with arrow keys to emulate a "unified canvas". Not sure if additional features were added to the component later.

**Comment by talldan** [comment]
closing this, as there don't seem to be any required actions here.
