### ISSUE TITLE
allowed_block_types filter is ignored for embeds

### ISSUE THREAD

**Issue by designbuildtest** [WordPress/gutenberg#25676]
The current version of Gutenberg that ships with WordPress enables developers to create a whitelist of allowed embed types. Declaring 'core/embed' removes all individual embed providers and leaves just a single global embed button. 

Under Gutenberg 9.0 however, this 'core/embed' declaration is ignored and all individual embed providers again appear in the inserter. However, if I open the Block Manager, just a single embed option appears (as anticipated).

`function mytheme_allowed_block_types() {
        return array(
                'core/embed', 
        );
}
add_filter( 'allowed_block_types', 'mytheme_allowed_block_types' );`

What is the expected behaviour here?

Tested with: macOS/Firefox

**Comment by talldan** [comment]
@designbuildtest Thanks for creating the issue. The relevant change is this one - https://github.com/WordPress/gutenberg/pull/24090.

The separate embeds are no longer each considered blocks, but now what we call 'variations' of the embed block itself. I realize this prevents you from being able to disallow those types of embeds from being inserted. I don't think using the `allowed_block_types` would have prevented the types of embeds completely though, they'd still be usable from the main embed block.

Was your goal just to remove the embed types from the inserter? If you'd like to remove them entirely there's also the oembed providers filter (https://developer.wordpress.org/reference/hooks/oembed_providers/), though I haven't tested it.

cc @ntsekouras.

**Comment by ntsekouras** [comment]
Hey @designbuildtest. Can you provide some more info about your goal?

If I understand correctly you want to `hide` other `embed` variations. If that's the case, you can unregister a block variation with the API https://developer.wordpress.org/block-editor/packages/packages-blocks/#unregisterBlockVariation.

Does that help?

**Comment by designbuildtest** [comment]
@ntsekouras @talldan 
Thank you. I was trying to remove/hide individual embed buttons from the inserter, rather than disable embeds completely. For my purposes, a single, global embed button is sufficient, as any provider link can be pasted using this global button. Having such a long list of individual embed providers adds significant visual clutter to the inserter (IMO). Thanks again.

**Comment by designbuildtest** [comment]
@ntsekouras @talldan
For completeness, I hid all core embed block variations, other than Vimeo, YouTube and the global Embed button, by placing the below code in a .js file and calling this file when the block editor loads. 

`function myguten_enqueue() {`
        `wp_enqueue_script( 'myguten-script', plugins_url( '/assets/js/reset.js', __FILE__ ), array( 'wp-blocks',  'wp-dom-ready', 'wp-edit-post' ), '1.0', false );`
`}`
`add_action( 'enqueue_block_editor_assets', 'myguten_enqueue' );`

This code was tested using the latest version of the Gutenberg plugin (9.1.0)

`wp.domReady(() => {`
	`wp.blocks.unregisterBlockVariation('core/embed', 'amazon-kindle');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'animoto');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'cloudup');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'crowdsignal');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'dailymotion');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'flickr');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'imgur');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'issuu');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'kickstarter');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'mixcloud');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'reddit');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'screencast');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'scribd');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'slideshare');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'smugmug');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'soundcloud');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'speaker-deck');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'spotify');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'tiktok');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'ted');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'twitter');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'tumblr');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'videopress');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'wordpress');`
	`wp.blocks.unregisterBlockVariation('core/embed', 'wordpress-tv');`
`});`

**Comment by artifex404** [comment]
Since the embed list might evolve over time, it's better to deregister all variations except the ones you'd like to activate @designbuildtest 

`// Remove all embed block variations except mentioned in the enabledEmbeds array
	var enabledEmbeds = ['youtube'];
	var embedBlock = wp.blocks.getBlockVariations('core/embed');
	if (embedBlock) {
		embedBlock.forEach(function(el) {
			if (!enabledEmbeds.includes(el.name)) {
				wp.blocks.unregisterBlockVariation('core/embed', el.name);
			}
		})
	}`

**Comment by paaljoachim** [comment]
Hey @artifex404 Igor

Can you create an example of your code that for instance includes Imgur etc embed variation? For instance hiding Imgur, Animoto and Amazon Kindle?
Can I add this as a code snippet to the functions.php file?

**Comment by paaljoachim** [comment]
Here is an interesting issue (which covers hiding embed variations):
Show 'inserter block' variations in the block manager and allow them to be toggled
https://github.com/WordPress/gutenberg/issues/27708
