### ISSUE TITLE
Form fields

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#2567]
Forms are until now plugin territory.

Is it planned to add common fields in Gutenberg in order to promote best practices and standardization?

**Comment by Soean** [comment]
You can find a "best practices" for Contact Forms in [Gutenberg Design Principles & Vision](https://github.com/WordPress/gutenberg/blob/master/docs/design.md)

**Comment by benoitchantre** [comment]
Thanks @Soean, I haden't seen this note.

**Comment by karmatosed** [comment]
Are you suggesting a form block gets added?

**Comment by benoitchantre** [comment]
I'm suggesting to have some standardized form blocks (input field, checkbox, ...) which would remain hidden until a plugin declares a support for these blocks.

The goal would be to have a similar UX with reusable blocks between forms plugins and maybe the same way to save the submitted data.

**Comment by karmatosed** [comment]
I feel this is out of scope for the v1 of Gutenberg, lets close this and we can always come back to it once merge has happened.
