### ISSUE TITLE
Welcome message appears every time I edit a document / page

### ISSUE THREAD

**Issue by DamianMalik** [WordPress/gutenberg#25685]
**Describe the bug**
Welcome Message Pop-up on Firefox 

**To reproduce**
Every time I want to edit a page, I get the pop-up "Welcome to Block Editor".  It's really getting on my nerves now. The pop-up appears only when I right-click the "Edit" link and select "Open link in new tab". I often practice right-clicking on "Open link in new tab", especially when I want to edit several posts one after the other from a search results list and don't want to miss anything.

This incorrect behavior can be observed under Linux Mint in Firefox 75.0. In the Cromium Browser (Linux) the popup appears only the first time, after that not anymore, as expected. In Firefox / Mac the behaviour cannot be observed either. Only the Linux / Firefox combination is affected. 

**Expected behavior**
Welcome message appears only once, at the very first start, then no more. 

**Screenshots**
![Wilkommen im Block-Editor](https://user-images.githubusercontent.com/31533791/94470900-959b4500-01c8-11eb-92d7-fd3653c687b5.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- If the Gutenberg plugin is installed, which version is it? 9.0.0 

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 81

**Additional context**
- see also: Wordpess.org 
https://core.trac.wordpress.org/ticket/50005

**Comment by skorasaurus** [comment]
Hi, 

I am able to reproduce this in Firefox (84) on Ubuntu in a fresh firefox profile using the default settings. 
(Directions for anyone else: create a new firefox profile by going to your terminal, `firefox --p -no-remote`; create a new profile and follow steps with creating new FF profile, login to your website, create new post; save draft; close browser; issue same command, go to the same profile then reopen the same website's wp-admin, login again and create new post). 

Could you go to your firefox settings ([directions are in this firefox help guide](https://support.mozilla.org/en-US/kb/storage))
once more and see if you're able to reproduce this issue if you follow the directions specifically under 
"Allow or block websites from storing information" at the above link and add your website's URL; close firefox; and then reopen?

**Comment by DamianMalik** [comment]
Hello @skorasaurus, 
I've added my website URL into "Allow or block websites from storing information". Now, the pop-up "Welcome to Block Editor" does not appear anymore. I am very happy with the suggested solution, (I'm closing this ticket now). Many thanks!
