### ISSUE TITLE
"Block-based Themes (Experimental)" Documentation is missing from the handbook

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#25707]
This appears to be still present here on GitHub: 

https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/block-based-themes.md

But it no longer shows up in the handbook for some reason: 

![Screen Shot 2020-09-29 at 11 55 00 AM](https://user-images.githubusercontent.com/1202812/94582764-9e345f80-024a-11eb-8207-a3a22e2c46e1.png)

**Comment by carolinan** [comment]
All tutorials are under the **Tutorials** section.
![tutorial](https://user-images.githubusercontent.com/7422055/108623619-30c6dc80-7440-11eb-939a-ac6d74d54ab8.png)

Did you mean that you want the link to be in two places?

**Comment by kjellr** [comment]
This appears to still be an issue.

This page does not appear in the handbook: https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/block-based-themes.md

<img width="234" alt="Screen Shot 2021-04-26 at 8 09 18 AM" src="https://user-images.githubusercontent.com/1202812/116080153-b3e5f800-a666-11eb-9634-f65fee1709b8.png">

**Comment by mkaz** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/31167

Here's the link: https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/
