### ISSUE TITLE
Widget Editor: Widget areas should open with one click

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#25709]
Currently, in relation to https://github.com/WordPress/gutenberg/pull/25681, when the Inserter is open and the user clicks on a collapsed widget area, it takes two clicks to open it. The first click should open that particular area immediately.

![click](https://user-images.githubusercontent.com/617986/94583029-d4191a00-0231-11eb-9ac4-4c69771814a0.gif)

cc @adamziel @draganescu

**Comment by kevin940726** [comment]
I can't reproduce it anymore. 🤔 

![Kapture 2020-09-30 at 14 01 06](https://user-images.githubusercontent.com/7753001/94648607-7a921780-0325-11eb-87cb-a5b514179920.gif)
