### ISSUE TITLE
Remove hardcoded Noto Serif in block editor.

### ISSUE THREAD

**Issue by vyskoczilova** [WordPress/gutenberg#25706]
**Is your feature request related to a problem? Please describe.**
Noto Serif is hardcoded as a locale font family in various places in wp-admin.
wp-admin\edit-form-blocks.php line 185
wp-includes\script-loader.php line 1441

**Describe the solution you'd like**
Add WP hook to disable/or modify its value. I know, we could overwrite that with selectors, but is the hardcoding really needed when the best editing experience should be available for users? We're trying to use the same code for FE and BE and these tricks make it hard. This is something more in theme capability than users/translators' choice.

**Comment by aristath** [comment]
Note: Also see trac ticket on https://core.trac.wordpress.org/ticket/46169

**Comment by aristath** [comment]
I'll go ahead and close this one as there is already a ticket in wp-core, so it would be better to keep the discussion in one place.
As a temporary solution you can use this snippet to remove the webfont:

```php
add_filter( 'wp_default_styles', function( $styles ) {

    // The style handle.
    $style_id = 'wp-editor-font';

    // Remove style.
    unset( $styles->registered[ $style_id ] );

    // Loop dependencies and remove the defined style handle from other styles.
    foreach ( $styles->registered as $key => $style_val ) {

        // The dependencies.
        $deps      = $style_val->deps;
        $style_pos = array_search( $style_id, $deps );
        
        // If the style-handle was located as a dependency, remove it.
        if ( false !== $style_pos ) {
            unset( $deps[ $style_pos ] );
            $styles->registered[ $key ]->deps = $deps;
        }
    }

    return $styles;
}, 999 );
```

Note: this same snippet will soon be available in the form of a utility plugin in wordpress.org to make it easier.

**Comment by vyskoczilova** [comment]
@aristath Sure, thanks a lot for your help. I didn't look to track (I hope they will get rid of it, it's super hard to get involved).

**Comment by aristath** [comment]
Just an update, the above snippet is now available as a plugin: https://wordpress.org/plugins/remove-core-editor-google-font/

Nothing extra, just that single code snippet to make applying it easier.
