### ISSUE TITLE
Consider to reset the sidebar panels state on the New Post page

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2571]
After #2533 the sidebar panels state is now saved in the browser's localStorage. That means, for example, if users expand the "Categories & Tags" panel (or any other panel), then switch to the Block setting, and then back again to the Post setting, they will find the panels in the same previous state.

Seems to me this is good when working on the same post, as it's the expected behavior.

However, there are scenarios where this may not be what users expect, for example:
- edit a post, expand the "Categories & Tags" panel, do some edit and save
- navigate away from the post editor
- go on the "New Post" page
- should users find the "Categories & Tags" panel expanded?

Maybe, in this case, the panels state should be reset to a sensible default (I guess with only the Status & Visibility panel open).

Not sure, but worth considering, if this applies also when navigating away from a post and then editing again the same post.

**Comment by youknowriad** [comment]
Well, this goes against #450 issue. Why do we bother to persist in localStorage, Redux state is enough in this case.

**Comment by youknowriad** [comment]
@jasmussen Should we close this issue? Do we want the persistence across page reloads and new posts or just when navigating in the same post?

**Comment by jasmussen** [comment]
I understand the use case, having a "fresh editor". But I do think it would be hard for a user to understand why sometimes the state is persisted, while other times it's not. As such, I do think that we should let the panels state be stored across edits and even posts.

I feel like this is something we can reopen if the use case becomes pressing in the future.
