### ISSUE TITLE
Block patterns not working with inner blocks that use templateLock

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#25718]
**Describe the bug**

I have a custom post type (`bm_block_template`) that I use to build HTML email templates for my [plugin](https://www.boldermail.com). In this post type, I only allow my own custom blocks to be usable. For example, I have `boldermail/paragraph`, `boldermail/heading`, `boldermail/list`, `boldermail/image`, `boldermail/columns`, etc. I need this level of control because most content does not play nice with email inboxes.

I further restrict how the user interacts with the post type by only allowing certain blocks to be inserted into other blocks. For example, `boldermail/paragraph` can only be inserted inside a `boldermail/template-part` block, which in turn can only be inserted inside a `boldermail/template` block. The `boldermail/template` serves as the container for the email template, whereas `boldermail/template-part` has variations to function as a preheader, header, body, or footer. So my default block structure looks like:
```
boldermail/template (generic template)
|
--> boldermail/template-part (preheader)
|   |
|   --> boldermail/paragraph
--> boldermail/template-part (header)
|   |
|   --> boldermail/heading
--> boldermail/template-part (body)
|   |
|   --> boldermail/paragraph
|   --> boldermail/image
|   --> boldermail/columns
|   --> boldermail/image
|       |
|       --> boldermail/column
|       |     |
|       |     --> boldermail/image
|       |
|       --> boldermail/column
|             |
|             --> boldermail/image
--> boldermail/template-part (footer)
    |
    --> boldermail/paragraph
```

The `boldermail/template` block is an `InnerBlocks` component with the attributes `templateLock={ 'insert' }` and `allowedBlocks={ [ 'boldermail/template-part' ] }`, and in the `supports` property it has the option `multiple: false`. So basically, you can only use it once, and you cannot insert more `boldermail/template-part` blocks into it.

Now, I'm having issues using the block directory to insert my block patterns into the correct spot. The behavior of where my patterns are available makes no sense. For example, if I click on `boldermail/paragraph` block inside my `boldermail/template-part` block and then on the global insert, no patterns show. If I click on the appender button inside a `boldermail/template-part` block, the patterns do show. However, once I click on my pattern, it says the pattern was inserted, except it actually wasn't. Then if I click on the `boldermail/template` block and then the global inserter, the patterns do show but I can't insert them because my pattern is of type `boldermail/columns` (`<!-- wp:boldermail/columns -->...<!-- /wp:boldermail/columns -->`), and `boldermail/template` only accepts `boldermail/template-part`.

I think this issue is related to #24403 and #24402.

**To reproduce**
I'm not sure how you can best reproduce this, since my setup is somewhat unique. I'm open to suggestions.

**Expected behavior**
Patterns should be available and inserted where expected.

**Screenshots**

![patterns](https://user-images.githubusercontent.com/3827771/94617633-258fcc00-0267-11eb-9f34-ced4c30a857d.gif)

**Editor version:**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin installed.
- If the Gutenberg plugin is installed, which version is it? 9.0

**Desktop:**
 - OS: macOS
 - Browser Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by chvillanuevap** [comment]
This is not a help request. It's a bug report. The patterns feature should not work like this.

**Comment by niklasp** [comment]
I have a similar issue in my plugin

**Comment by chvillanuevap** [comment]
I'm going to close this because I think my problem is a more complicated version of #26281.
