### ISSUE TITLE
Image block: Close the source selection dropdown once image is replaced

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#25722]
When using the "Replace" function of the Image block, after a different image is selected and the media modal is closed, the media source selection dropdown remains open, partially obscuring the image. This is a minor thing, but I found it quite annoying after a while, so I thought I'd report and see if this is something that could be changed. 

For comparison, when using one of the text formatting options of the Paragarpah block, for example, uppercase, the dropdown disappears as soon as an option is selected.

Here's a quick video of the issue:
https://cloudup.com/cFXviPSIYEW

**Comment by talldan** [comment]
@alaczek My understanding is that this is on purpose. When the media modal is closed using the keyboard, focus is returned to the 'Open Media Library' button. If the button were no longer visible there could be a focus loss issue, or focus would be returned to an unexpected place. There's an issue here from the accessibility audit that provides more background on why menus and modals behave this way - https://github.com/WordPress/gutenberg/issues/15321.

The formatting issue might be a bug. I'm sure I recall a ticket for this, but I can't find it now.
