### ISSUE TITLE
List block: Add typography options

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#25725]
List block is missing font size controls. I was thinking it would be useful to have the same typography options available as in the paragraph block.

Paragraph block typography settings for reference:

![image](https://user-images.githubusercontent.com/4550351/94643155-7d8f0700-0329-11eb-800f-3839d008c732.png)

**Comment by talldan** [comment]
I've added Needs Design Feedback as I'm not sure whether the lack of these options is for a reason, or whether it's just a missing feature. If design folks agree it's the latter then I think we can add the `Needs Dev` and `Good First Issue` labels to this one.

**Comment by paaljoachim** [comment]
Hmm I believe there was some discussion a while ago in relation to adding options such a typography to other blocks. I am pinging a few folks who might remember some more details than what I currently do.
@kjellr @ItsJonQ @karmatosed

**Comment by kjellr** [comment]
As discussed in https://github.com/WordPress/gutenberg/issues/8171, the list block should definitely have the same typography controls as the paragraph block.

**Comment by paaljoachim** [comment]
As you suggested Dan, I will go ahead and add a **Needs dev** and the **Good First Issue** label, and remove the **Needs Design Feedback** label.

**Comment by annezazu** [comment]
Closing this out since https://github.com/WordPress/gutenberg/pull/26257 has now been merged.
