### ISSUE TITLE
PostCSS Plugins Preset contains vulnerable dependency

### ISSUE THREAD

**Issue by jcush** [WordPress/gutenberg#25731]
**Describe the bug**
The latest version of the npm package `@wordpress/postcss-plugins-preset` (1.4.1) depends on `postcss-custom-properties@^9.1.1`. This dependency, before version 10, contains a dependency tree which includes `url-regex`, a package now not maintained but known to have a ReDoS vulnerability.

Source 1: https://www.npmjs.com/advisories/1550
Source 2: https://portswigger.net/daily-swig/unpatched-regex-bug-leaves-node-js-apps-open-to-redos-attacks

Versions of `postcss-custom-properties` from 10.0.0 onwards address this by updating dependencies such that url-regex is no longer included.

**To reproduce**
1. Install any NPM package depending on `@wordpress/scripts`, `@wordpress/postcss-plugins-preset` etc.)
2. Check your `package-lock.json` for a version of `postcss-custom-properties` prior to v10

**Expected behavior**
No un-rectifiable vulnerabilities

**Screenshots**
![image](https://user-images.githubusercontent.com/10184859/94668505-0ac16400-0308-11eb-953c-754d4bcbeace.png)

**Editor version (please complete the following information):**
- WordPress version: N/A
- Does the website have the Gutenberg plugin installed, or is it using the block editor that comes by default? N/A
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: OS X 10.15.6
 - Browser: N/A (Terminal, ZSH)
 - Version: N/A

**Comment by aristath** [comment]
This is an issue on node apps - which Gutenberg is not and therefore this is not a security issue.
I agree that at some point this will have to be updated, but it's not critical. :+1:

**Comment by jcush** [comment]
Thanks for acknowledging.

FYI the [npm page](https://www.npmjs.com/package/@wordpress/postcss-plugins-preset) for the affected package links to this repo under 'Homepage', which is why I raised this here

**Comment by gziolo** [comment]
I opened #26140 to address this issue, thank you for reporting 👍
