### ISSUE TITLE
Gutenberg on iOS Chrome: paragraphs don't scroll

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2573]
version 0.9
When typing a post in Chrome on iOS, the core/paragraph block doesn't scroll when you hit a new line.  Thus you can't easily follow along with what you type.

**Comment by aduth** [comment]
Prior art: https://github.com/Automattic/wp-calypso/pull/12346

**Comment by aduth** [comment]
Related: #353

**Comment by karmatosed** [comment]
I am not seeing this now, if you can still recreate please let me know. I tested using iPhone 7 plus and latest build.
