### ISSUE TITLE
Previewing a legacy widget shows error

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25749]
I was exploring the new widget interface and clicked an existing widget in my footer, which was a legacy block. On clicking preview, I got the following error.

![2020-09-30 18 37 15](https://user-images.githubusercontent.com/253067/94720327-3b2af180-034c-11eb-84f9-0046a1276b37.gif)

My recommendation I think would be to have preview working, but I am not aware of why it didn't work in this case. Perhaps something didn't activate with the legacy block?

**Comment by karmatosed** [comment]
Potentially some more details here, merging: https://github.com/WordPress/gutenberg/issues/25762

**Comment by noisysocks** [comment]
This works for me running latest `master`.

![it-works](https://user-images.githubusercontent.com/612155/94878417-9f5eca00-04a0-11eb-92fa-70c75f7ba78c.gif)

@karmatosed @paaljoachim: Could you check again? Are there any errors in the DevTools console?

**Comment by paaljoachim** [comment]
Another test using Twenty Twenty theme with Gutenberg plugin 9.1. This time using a live online test site.
![Widget-legacy-preview-error](https://user-images.githubusercontent.com/5323259/94904518-bcdd6500-049b-11eb-8165-a7f7ec512f09.gif)

DevTools console:
![Screen Shot 2020-10-02 at 10 41 43](https://user-images.githubusercontent.com/5323259/94904640-e7c7b900-049b-11eb-904c-c2a0f2c31db9.png)

**Comment by noisysocks** [comment]
Looks like this was fixed by https://github.com/WordPress/gutenberg/pull/25792 but let me know if you're still encountering the error and we can re-open.

**Comment by paaljoachim** [comment]
I am giving a confirmation that the error is now gone. Previewing works in 9.1.1..

![Screen Shot 2020-10-08 at 16 59 23](https://user-images.githubusercontent.com/5323259/95476583-ab0e2d00-0987-11eb-9941-4cad7e845159.png)
