### ISSUE TITLE
Confusing columns block variation naming (70 / 30)

### ISSUE THREAD

**Issue by keithdevon** [WordPress/gutenberg#25744]
**Describe the bug**
There are two column block variations that are inappropriately named. These are the "70 / 30" and "30 / 70" variations.

These actually produce columns set to 66.66% and 33.33% which is potentially confusing to the user.

**To reproduce**
1. Go to a post edit screen.
2. Add a 'Columns' block
3. Select either the "70 / 30" or "30 / 70" variation.
4. Inspect the "Percentage width" of the columns under the "Column settings" panel.

**Expected behavior**
One would expect these to produce columns at 70% and 30% width, but instead, these are set to 66.66% and 33.33%, i.e. two-thirds and one-third.

Possible fixes:

1. The variations could be renamed to "66 / 33" and "33 / 66"
2. The column widths could be set to 70% and 30%

**Screenshots**
<img width="1054" alt="Screenshot 2020-09-30 at 16 35 19" src="https://user-images.githubusercontent.com/970009/94707274-27c35a80-033b-11eb-81ea-98d332e34787.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Comment by jordesign** [comment]
Closing this as no longer recreatable - a 70/30 option is no longer offered in the Columns block.

<img width="709" alt="Screenshot 2023-08-17 at 2 50 26 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/e2fdd46b-3542-4ef3-bd12-ecba887ff0ee">
