### ISSUE TITLE
Navigation Component: Animation triggers when switching between different entity types

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#25743]
When we switch between different entity types, then the Navigation is rerendered. Actually, almost the whole tree is rerendered since the change is coming from `EntityProvider`.

We should only run the animation when we actually use the toggle button. This also causes the state of the `Navigation` to be lost, so we might need to move the state handling to the store.

**GIF**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2256104/94694619-53434680-0335-11eb-94be-be9121a73697.gif)

**Comment by Copons** [comment]
In the Post Editor, the Inserter state is handled by the `core/edit-post` store's `isInserterOpened` property.
I guess we could (should?) do the same for the Site Editor as well, and add the Nav state to `core/edit-site`.

**Comment by vindl** [comment]
> In the Post Editor, the Inserter state is handled by the core/edit-post store's isInserterOpened property.
I guess we could (should?) do the same for the Site Editor as well, and add the Nav state to core/edit-site.

I think this makes sense since we currently have other components like inserter tied to this property, and might need more in the future.
