### ISSUE TITLE
Add technical documentation

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#25759]
I'm creating this issue to keep track of all of the technical documentation that needs to be written for the widgets editor which is landing in WordPress 5.6.

Non-technical documentation is generally handled separately by the docs team.

Please feel free to add to this list!

---

**For plugin and theme developers**

- [x] How to opt your theme out of block widgets.
- [x] How to make it so that your widget doesn't appear in the Legacy Widget block dropdown.
- [x] How to make it so that your plugin's widget can be converted into your plugin's block.
- [ ] How to add custom UI to the sidebar. See https://github.com/WordPress/gutenberg/pull/25758.
- [ ] How to add custom UI to the top and bottom of the screen. See https://github.com/WordPress/gutenberg/pull/25758.
- [x] How to ensure compatibility with the Legacy Widget block using the `widget-added` event.
- [x] How to show "No preview available." message in Legacy Widget block.

**For core developers**

- [ ] Overview of the screen's architecture. Should live in `packages/edit-widgets/README.md`.
- [x] A dev note to go on Make/Core ahead of 5.8.

**Comment by annezazu** [comment]
Pulling from @justintadlock [recent post on the new screen](https://wptavern.com/are-block-based-widgets-ready-to-land-in-wordpress-5-6), I wanted to flag a few items he mentioned that aren't referenced here that seem great to address if possible: 

- What are the hooks to add custom styles for the Widgets screen?
- Can themes target specific sidebar styles on the Widgets screen?
- Is it possible to consistently style sections like traditional widgets on the front end?
- Can themes opt into wide and full-alignment within block areas, which could essentially be used similarly to the post content area?

**Comment by skorasaurus** [comment]
For how to opt out https://github.com/WordPress/gutenberg/issues/25123

**Comment by draganescu** [comment]
I am working on a dev note.
