### ISSUE TITLE
Gutenberg on iOS Chrome: Pressing return from title doesn't do anything

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2575]
Gutenberg 0.9

When I type a title, it doesn't move into the next block upon hitting "return"

**Comment by aduth** [comment]
Related: #2421, https://github.com/WordPress/gutenberg/issues/2279#issuecomment-320861452

**Comment by afercia** [comment]
See also #1650

**Comment by aduth** [comment]
Closing as duplicate of #1650
