### ISSUE TITLE
Hover on top of accordian in widget area is same as background color

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25752]
You can see here that on hover the colour is the same as the background. My recommendation is perhaps if this is the color options to be used, have a mid-grey for the hover, or at least something distinct from the background. You can see that on bottom of the image for a suggestion.

<img width="1527" alt="Frame 1" src="https://user-images.githubusercontent.com/253067/94728853-c7431600-0358-11eb-8231-8613d51ba496.png">

**Comment by mapk** [comment]
I don't think we need a hover indication here at all. Can we just remove that gray background?

Nothing in the post editor changes on hover, and I'd like to fall inline with that pattern as much as possible. When clicking the widget area, then it should highlight with a blue border. But that should be it.

Let's just remove the grey background on hover.
