### ISSUE TITLE
Widget Editor: Unable to move blocks between widget areas.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25766]
I am testing out how to move a widget from one widget area to another.

Test 1 
using the up and down move arrows.
![Moving-widget-to-another-widget-area](https://user-images.githubusercontent.com/5323259/94784488-85ed4d80-03ce-11eb-8f4d-c3d6b13f00fa.gif)

It goes to the bottom of the widget area. I am not able to use the down arrow to move it to the next widget area.

Test 2
Using the 3 dot drop down menu. Move to.
![Widget-Screen-Move-To](https://user-images.githubusercontent.com/5323259/94784896-22afeb00-03cf-11eb-8c96-715976ca593c.gif)

That does not at all work. I see a blue line but I do not know how it is associated with the Move to action.

I am not able to use the Move to action.

**Comment by noisysocks** [comment]
I agree we need a way to move a block to a different area without using drag and drop.

**Comment by noisysocks** [comment]
_Move To_ is working, albeit it's confusing. If you select _Move To_ you can then use <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> to move the blue cursor around.

**Comment by paaljoachim** [comment]
I do believe this might be the best option.
Adding a submenu to the Move To option. Like so just prettier.

![Widget-Screen-Move-Widget](https://user-images.githubusercontent.com/5323259/95191180-a6ebdf00-07d0-11eb-9d89-587ecb71e8c3.jpg)

**Comment by mapk** [comment]
So one way to do this is just cutting and pasting the block into another area like so:

![cut-paste](https://user-images.githubusercontent.com/617986/95262545-300b1200-07e1-11eb-8622-4ee4dfb5bf2a.gif)

I'm okay using "Move to" but it should change the behavior from the post editor. The behaviors should remain the same with an added "Move to" selected widget area.

**Comment by mapk** [comment]
I'm finding it very difficult to use the keyboard to jump between widget areas. If this was refined, the "Move to" could work much better. I'll create an issue around using the keyboard to jump between areas.

**Comment by paaljoachim** [comment]
So there is a Move to option in the post editor as well. Never really used it. It is a bit confusing and cumbersome to use.

Adding a cut & paste and drag of widgets between widget areas will help. 
The following issue of drag & drop of widgets between areas will also greatly help: https://github.com/WordPress/gutenberg/issues/25243

**Comment by mapk** [comment]
Related: #25911 

I think we have a good way forward by implementing these as you mention, @paaljoachim.

>Adding a cut & paste and drag of widgets between widget areas will help.

Let's get this to dev. :)

**Comment by talldan** [comment]
What's the thing that Needs Dev here? Cut, copy, paste should work, and drag and drop is tracked by other (now closed) issues.

**Comment by mapk** [comment]
@talldan, the Move To option just doesn't seem to work when trying to move one block/widget from one area to another. Here's a video of me trying the Move To without any success. I tried with a both a mouse and using the keyboard. I couldn't get it to happen.

![moveto](https://user-images.githubusercontent.com/617986/96510039-cc85d900-1211-11eb-8d6e-22216b4b28ae.gif)

### Problem
When I'm inside a widget area, I can't easily switch to another widget area using the keyboard. I did happen to see a grey line in between widget areas appear which was really weird.

![Screen Shot 2020-10-19 at 1 50 16 PM](https://user-images.githubusercontent.com/617986/96510218-0951d000-1212-11eb-8e80-8407e29ed850.png)

And in other cases,

**Comment by mapk** [comment]
Okay, tried this again, and there seems to be a really confusing requirement that a Move To needs to have two blocks in another area to actually move the new block between? Here's another video of me trying again. It wasn't consistent after clicking "Move To" what got highlighted. It would NOT move the block until I selected a block in the other area. 

![again](https://user-images.githubusercontent.com/617986/96510532-811ffa80-1212-11eb-9e30-e37e3c29335e.gif)

### Solution 
I should be able to select a widget area and drop the block inside it, at the bottom, without having to click into the widget area.

**Comment by garretthyder** [comment]
For myself this action is extremely confusing. The Move To button feels to have no action or tell as to what your next step is. 
I did like @paaljoachim idea of giving the moveto a direct action menu which is the current list of sidebars and widgets/blocks.

**Comment by talldan** [comment]
It is a bit difficult to understand, it was mostly implemented for screenreader users IIRC.

Anyway, my understanding is it primarily works using arrow keys, up/down for moving up and down, left/right for un-nesting/nesting.

There was a design somewhere showing some visible instructions for using move mode. @paaljoachim do you remember seeing that? I couldn't find it 😄

**Comment by paaljoachim** [comment]
Hey Dan @talldan 

I am not sure if I have seen any design of the **Move to** mode. As I had not noticed that the mode even existed earlier as I went and added the action menu mockup mentioned by @garretthyder which I commented about further above.

**Comment by talldan** [comment]
Ah, I was thinking of this issue - https://github.com/WordPress/gutenberg/issues/25126

**Comment by talldan** [comment]
So just to follow up, it seems like the action here would be to make the arrow keys used for Move To clearer. Does that sound correct @mapk @paaljoachim?

**Comment by paaljoachim** [comment]
**An overview**
I just went through this issue. A few things that have been brought up are...

1. Dragging & dropping a widget from one widget area to another works a lot better now than earlier versions.
Check.

2. Being able to move a widget/block between widget areas using the arrow icons is I believe on stand still for now. (One can move a block inside a widget area using arrow icons.) 
This is a broader issue related to the post editor and the widget screen. 

3. Cut & Paste of widget/block. Does not work on my Mac.

4. "Move to" inside the 3 dotted menu. Is still very confusing feature. 
@talldan I do believe the actionable item here would be to figure out an improved method for the "Move to" feature for the post editor and the widget screen. Looking at https://github.com/WordPress/gutenberg/issues/25126 to get some inspiration. The question comes up. What should happen when one clicks "Move To" ? 
Should it go into select mode with hit areas beside the label of each block/widget, so one can click the hit area and have the block/widget moved to the new location? Something similar to the below perhaps... I am sharing a possible concept. Where one activates the "Move to" feature and the layout changes to reflect an action is about to take place.

1. Select "Move To"
2. Goes into Select mode and shows an icon/hit area etc with the words move here.

![Widget-screen-Move-To](https://user-images.githubusercontent.com/5323259/103766003-588feb80-501e-11eb-8045-37f97f1ff673.jpg)

**Comment by shaunandrews** [comment]
I think this issue maybe got a little distracted.

The issue remains that the block movers and "Move to..." functionality do not allow for moving a block between widget areas.

For block movers, I expect that clicking the down arrow for a block at the end of an area would move the block to the next area, if one exists. If one doesn't exist, then the down arrow should be disabled.

With the "Move to..." functionality, hitting the down arrow on my keyboard should display the insertion guide in the next area, if one exists. If one doesn't exist, then an audible message should indicate that you've reached the end of the last area.

**Comment by talldan** [comment]
> For block movers, I expect that clicking the down arrow for a block at the end of an area would move the block to the next area, if one exists. If one doesn't exist, then the down arrow should be disabled.
>
> With the "Move to..." functionality, hitting the down arrow on my keyboard should display the insertion guide in the next area, if one exists. If one doesn't exist, then an audible message should indicate that you've reached the end of the last area.

This is probably another area where it might be confusing that widget areas are blocks. It's not possible to move blocks between other container blocks in that way, for example two adjacent groups. But @paaljoachim did make an issue proposing that here - https://github.com/WordPress/gutenberg/issues/24328.

The other option is to implement widget areas differently (make them not blocks, or make them 'passthrough' blocks) and have it work the way described.

**Comment by shaunandrews** [comment]
> It's not possible to move blocks between other container blocks

This feels like the root problem to solve.

**Comment by hedgefield** [comment]
Yes, and to me it makes sense to do that for the post editor also, as @paaljoachim suggests in https://github.com/WordPress/gutenberg/issues/24328. I think implementing that suggestion will solve this issue as well, right?

**Comment by talldan** [comment]
To summarise this issue, I think there are two things that have been noted as improvements:
- Improve using the block movers to move between container blocks (tracked in #24328)
- Improve the ease of use of the 'Move to' option from the block settings menu. I've made two issues for this—https://github.com/WordPress/gutenberg/issues/30899 and https://github.com/WordPress/gutenberg/issues/30898.

For the widget screens, https://github.com/WordPress/gutenberg/pull/30896 and https://github.com/WordPress/gutenberg/pull/30826 solve the issue of moving blocks between widget areas, so I think we can close this issue.
