### ISSUE TITLE
Widget screen: Previewing legacy widgets shows following errors

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25762]
**Describe the bug**
Previewing a legacy widget shows errors.

**To reproduce**
Click to preview one of the default legacy blocks in Twenty Twenty and the following error is seen.

Zoomed out to 50%
![Screen Shot 2020-10-01 at 09 14 04](https://user-images.githubusercontent.com/5323259/94782163-204b9200-03cb-11eb-97b4-e0860fcf9ba3.png)

![Preview-legacy-widgets-error](https://user-images.githubusercontent.com/5323259/94782128-175ac080-03cb-11eb-840a-2c4eb14623fd.gif)

**Expected behavior**
I expected a working preview.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg plugin: 9.1
- Theme Twenty Twenty.

**Desktop (please complete the following information):**
 - Mac
 - Chrome
 - local site using Desktop Server.

**Comment by karmatosed** [comment]
I think maybe this is the same as #25749 ?

**Comment by paaljoachim** [comment]
It probably is. They are just showing a different result. I added the issue as the error message is seen and can hopefully help the developer figure out what is wrong.

**Comment by karmatosed** [comment]
Ok then let's close up this one and we can focus attention on that issue. Thanks.
