### ISSUE TITLE
Gutenberg on iOS Chrome: Pararaph toolbar is too wide for the screen

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2576]
iPhone 6
Gutenberg 0.9

![img_6005](https://user-images.githubusercontent.com/622599/29783306-d6f56228-8bed-11e7-83c9-05af6722a9bf.PNG)

**Comment by karmatosed** [comment]
With the recent toolbar changes, closing this. We have mobile issues but this is no longer the existing UI.
