### ISSUE TITLE
Widget screen: Blue hover line in Widget area moves to the right when block content is present.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25761]
**Describe the bug**
With new block content added to the widget area the blue hover line is pushed to the right.

**To reproduce**
1. Add new block content to the first widget area.
2. Open the Inserter Panel.
3. Hover over a block.
4. Notice how far to the right the blue line is seen.

**Expected behavior**
I see this when no new block is added:
<img width="1193" alt="Screen Shot 2020-10-01 at 09 35 52" src="https://user-images.githubusercontent.com/5323259/94781000-87684700-03c9-11eb-9e13-a3565c7ac340.png">

But adding a new block I see this:
<img width="1201" alt="Screen Shot 2020-10-01 at 09 36 58" src="https://user-images.githubusercontent.com/5323259/94781091-aa92f680-03c9-11eb-9e3c-93166473a103.png">

![Widget-screen-Hover-block-with-existing-block-in-area](https://user-images.githubusercontent.com/5323259/94781123-b1ba0480-03c9-11eb-9750-108600d66b15.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin version: 9.1.0
- Theme Twenty Twenty.

**Desktop (please complete the following information):**
Mac
Chrome
Desktop Server local site

**Comment by noisysocks** [comment]
I was able to reproduce this.

**Comment by kevin940726** [comment]
Might be fixed by #25849.

**Comment by kevin940726** [comment]
Fixed by #25849, feel free to reopen if it didn't.
