### ISSUE TITLE
Gutenberg on iOS Chrome: Insert Block Box experience is subpar

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2577]
iPhone 6
Gutenberg 0.9

Pressing the + button does nothing on first press.  On second press I am scrolled to the top of the page. The 2 column overlay is too wide and scrolling into it is hard. 

Overall, this seems like something that is still undesigned.

**Comment by karmatosed** [comment]
This seems fixed now so going to close.
