### ISSUE TITLE
Viewing legacy widgets in the Customizer shows a lot of errors

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25776]
I am unsure if this relates to the errors already reported for the legacy widget, but even if it does, then perhaps there could be an experience iteration win here along with fixing. I saw the following:

![image](https://user-images.githubusercontent.com/253067/94822448-93b8c800-03fa-11eb-95ce-3e122edbb70d.png)

Now, firstly, if this isn't going to be working in the Customizer then disabling makes sense. One thing that could also be explored is where multiple errors using the same widget for example occur, show only one, or perhaps show a notice. With such a small screen, reducing the repeating loading errors would be a relief. This of course might be a stress case and not typical, but it came to mind on seeing this.

**Comment by noisysocks** [comment]
We're now just showing a very simplified UI in the Customizer, so this issue doesn't happen anymore:

<img width="307" alt="Screen Shot 2020-10-02 at 11 48 39" src="https://user-images.githubusercontent.com/612155/94880171-97555900-04a5-11eb-9394-92b855ceb97b.png">

Not sure if the simplified UI is a temporary solution, though. I'll keep this issue open in case.

**Comment by karmatosed** [comment]
I now see this:

![image](https://user-images.githubusercontent.com/253067/95100212-c8918b80-0728-11eb-8337-96543dbfff5d.png)

Much better, however, it does probably need some clarification over just saying 'block'. I can make another issue however for that and close this.
