### ISSUE TITLE
Widgets screen: style adjustments for the block areas hover and font face

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#25777]
**Describe the bug**
Not sure whether this has been already reported. In the new widgets screen I see a couple of style inconsistencies:

The block areas accordion headers get a grey background on hover, which is not that nice to see against a grey background and should probably be changed:

<img width="933" alt="Screenshot 2020-09-30 at 14 56 29" src="https://user-images.githubusercontent.com/1682452/94822238-b6e77580-0402-11eb-87ee-b265afa5f569.png">

The accordion titles and also the content within the block areas (e.g. the placeholder text "Start writing...") use a serif typeface:

<img width="750" alt="Screenshot 2020-10-01 at 16 20 32" src="https://user-images.githubusercontent.com/1682452/94822344-d383ad80-0402-11eb-82c7-d393a3c79290.png">

The serif typeface is also applied to the actual content entered in a block areas:

<img width="748" alt="Screenshot 2020-10-01 at 16 34 32" src="https://user-images.githubusercontent.com/1682452/94825460-843f7c00-0406-11eb-9af2-42f419f58124.png">

Note: my active theme is Twenty Twenty, which uses a sans-serif typeface so the Widgets preview is also non-WYSIWYG

To my knowledge, WordPress doesn't use serif typefaces in its user interface anywhere. Seems to me this style is inehrited from the editor styles wrapper which uses the scss variable `$editor-font: "Noto Serif", serif;`. this shoul dprobbly be changed, as it sets a serif typeface on all the elements in the page.

Ideally, the parts of the Widgets screen that are user interface should use the WordPress "system font stack". Instead, to be truly WYSIWYG, the content within the block areas should use the font used by the theme. 

**To reproduce**
- I tested it on latest master 16e98d49ffbd32e231099aa687bdc1bbc933c411 but I guess it's the same on the latest plugin version 9.1.0 
- go to Appearance > Widgets 
- see the hover and typeface styles

**Comment by mapk** [comment]
It looks like the UI has been cleaned up with other PRs. Tested on Twenty Twenty.

![ui](https://user-images.githubusercontent.com/617986/96656302-5e661280-12f4-11eb-9847-3f7c866183bb.gif)


- No more serif fonts in the Heading.
- Hover affect has been removed, but kept the highlighting for the focus state.
