### ISSUE TITLE
Block insertertion point blue line isn't visible when inserting at end of block list

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#25785]
**Describe the bug**
When inserting blocks using the main block library, usually a blue line displays where the block will be inserted.
<img width="500" alt="Screenshot 2020-10-02 at 10 42 42 am" src="https://user-images.githubusercontent.com/677833/94882968-0928a500-049c-11eb-833c-51fd9c082f4c.png">

This blue line doesn't appear when a block is being inserted at the end of a list of blocks.
<img width="500" alt="Screenshot 2020-10-02 at 10 41 51 am" src="https://user-images.githubusercontent.com/677833/94882980-0e85ef80-049c-11eb-8f88-9741e2c91fef.png">

Debugging:
It looks like this is because the `InsertionPoint` shows above the block it'll insert before:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/insertion-point.js#L110

But not after the last block.

**To reproduce**
1. Add multiple paragraphs to a post
2. Select a block that's not the last block
3. Try inserting a block using the Add Block button in the header
4. Observe the blue line is displayed
5. Select the last block
6. Try inserting a block using the Add Block button in the header
7. Observe no blue line is shown

**Expected behavior**
The blue line appears consistently

**Comment by mtias** [comment]
Somewhat related, but there's also a discrepancy when it does show: https://cloudup.com/coYihvr_oVN

**Comment by talldan** [comment]
@mtias Yeah, the css for that indicator is applied as a pseudo-element to the trailing appender which takes up the full width, so it probably just needs some styling adjustments.

It'd be nice if these two bits of similar functionality used the same system.
