### ISSUE TITLE
Can't add button in Gutenberg 0.90, Chrome for Windows

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2578]
## Steps to Reproduce (for bugs)

1. Insert a button block
2. Attempt to add link
3. Attempt to add text
4.

Chrome 60.0.3112.101 64-bit on Windows 10
Gutenberg 0.90

## Expected Behavior

I checked this on Firefox and it works there, so I'm assuming that what should happen is that when you insert the button block, you see a cursor inside the blue circle and can type the link text, and that when you paste in a URL and click the "apply" button, it applies. (Mind you, that link button with the arrow still shows once you apply it, which is kind of confusing.)

## Current Behavior

What happens in Chrome is that there is no cursor in the blue circle and the URL appears not to be applied (perhaps because there is nothing to apply it to).
![insert button error](https://user-images.githubusercontent.com/14795150/29788760-a352e044-8be8-11e7-9aa1-e07111e63aef.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I can replicate .. well sort of. There is some really odd behaviour going on here. I can add a link, but sometimes when click then can add text to button. Sometimes I can't. It seems very random. This is in Chrome.
