### ISSUE TITLE
SpeakerDeck (generic embed) caption looks different from other embed captions on front of site

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2580]
## Issue Overview

I embedded a slideshow from SpeakerDeck easily using the generic Embed block (since there is no SpeakerDeck block [yet]). Within the editor, the caption looks like other captions. On the front of the site, the caption looks like the caption in the editor, and not like the other captions, which are indistinguishable visually from paragraph text. I suspect this is actually more a lack in the theme style for Gutenberg caption display than a bug in the generic embed display, but the captions should all be consistent.

## Steps to Reproduce (for bugs)

[https://gutenberg.eastbaywp.com/post-with-all-the-blocks](https://gutenberg.eastbaywp.com/post-with-all-the-blocks)

Chrome for Windows, Gutenberg 0.90

## Expected Behavior

Captions should be consistent across embed/block types.

## Current Behavior

![speakerdeck embed caption displays differently on front of site](https://user-images.githubusercontent.com/14795150/29791875-733ce278-8bf3-11e7-9a86-96c7e8ca3356.png)
![speakerdeck embed in gutenberg editor](https://user-images.githubusercontent.com/14795150/29791876-733e83b2-8bf3-11e7-8369-52dfc11c3c91.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
This is interesting, I probably am missing a step :) When I try and reproduce I get this:

![2017-08-30 at 19 51](https://user-images.githubusercontent.com/253067/29889598-a1c7479e-8dbc-11e7-91e0-a1f522be16b4.png)

I was using the embed block and the link you gave above. Could you please maybe provide some steps as I would love to recreate.

**Comment by karmatosed** [comment]
As I can't recreate, lets close this for now. We can always reopen if we have more information.

**Comment by wpfangirl** [comment]
I'm guessing it's been fixed in a recent version. I'll test it again when I get the chance.
