### ISSUE TITLE
Add empty or existing category: error 500

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2581]
To reproduce:
- open the "Add New Category" form in the sidebar
- submit testing all these 3 cases:
  - leave the new category field empty
  - enter only spaces
  - enter an already existing category
- observe your browser console
- POST ... `500 (Internal Server Error)`

As far as I zee, there is a response, for example:
`{"code":"empty_term_name","message":"A name is required for this term.","data":null}`
but maybe it's not handled correctly

Also, the UI doesn't give any feedback in both cases. At the very least, I'd consider to:
- don't allow user to submit an empty term name or made of only spaces
- handle the already existing term correctly: the UI should display a proper message and also send an audible message to the ARIA live region
-

**Comment by youknowriad** [comment]
Adding an existing category has been fixed, it's now selected. We can't get rid of the 500 because of an API limitation where we can not fetch an existing term before trying to create It.
