### ISSUE TITLE
Nofollow and Sponsored links not working

### ISSUE THREAD

**Issue by SheElf** [WordPress/gutenberg#25811]
**Describe the bug**
When I click on the options to add a nofollow and sponsored link, it does not stick. It reverts back to 'open to a new page' only. I've tried to fix it a dozen times and it won't stick. All my links are dofollows and I cannot have [this.](url
![Link errors](https://user-images.githubusercontent.com/17300848/95006903-9536eb80-05c6-11eb-963a-2738ce7340d0.PNG)
)

**To reproduce**
1. Go to '...' https://pausitiveliving. 
2. Click on '....'any link and you will see they are all dofollows. 

**Expected behavior**

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]  I'm using version 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] No
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari] Chrome and Firefox
 - Version [e.g. 22] Newest

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
Hi @SheElf, these options are added by a plugin you're using, they're not part of this codebase. This is possibly an SEO plugin you're using, I'd recommend reaching out to the plugin developer.

**Comment by SheElf** [comment]
Hi, yes, turns out it's a Yoast issue. Thanks for responding and nailing
your theory.
Have a lovely day.
