### ISSUE TITLE
Review render flow when switching template view

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#25819]
Switching from a template view to a template part view on the sidebar re-renders the interface's root tree (tools like sidebar and global styles are refreshed unnecessarily so, causing a flicker).

**Comment by Mamaduka** [comment]
@mtias, is this still an issue after recent Site Editor refactoring?

**Comment by youknowriad** [comment]
It's not perfect in my testing but it's decent. I'm going to close the issue for now. Please consider reopening if you have concrete tasks in mind here.
