### ISSUE TITLE
Focal point picker drag handle sets incorrect coordinates in macOS Safari

### ISSUE THREAD

**Issue by shadow351** [WordPress/gutenberg#25814]
**Describe the bug**
When using macOS Safari and attempting to set a focal point for Cover Block media via the drag handle, it incorrectly sets the coordinates to (0, 0) regardless of where you drag your cursor.

**To reproduce**
1. Navigate to create a new post.
1. Add a Cover Block.
1. Set the media for the Cover Block.
1. Click the Cover Block to reveal the media settings in the right sidebar.
1. Click and drag within the "Focal point picker" media settings section.
1. Focal point coordinates are set to (0, 0) regardless of where you drag your cursor.

**Expected behavior**
The focal point is correctly updated as you drag. The "Left" and "Top" input fields display the correct X and Y coordinates to match the position of your drag. The Cover Block rendering updates accordingly to position the media relative to the focal point coordinates.

**Screenshots**
| Safari | Chrome |
| --- | --- |
| ![focal-point-picker-safari](https://user-images.githubusercontent.com/438664/95015621-80cd1000-0613-11eb-91b0-c2effcf329b1.gif) | ![focal-point-picker-chrome](https://user-images.githubusercontent.com/438664/95015655-b245db80-0613-11eb-960f-a7ce58000342.gif) |

**Editor version (please complete the following information):**
- WordPress version: WordPress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? n/a
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Safari
 - Version: 14.0

**Additional context**
- This behavior does not occur while using macOS Chrome.

**Comment by tellthemachines** [comment]
I can only reproduce this intermittently on Safari, with Gutenberg 9.1. I haven't been able to repro with latest master. It only seems to happen when clicking anywhere on the image outside of the picker. Picking up and dragging the picker works fine.

**Comment by haszari** [comment]
I can reproduce this every time in Safari with latest Gutenberg plugin (9.4.1), or with WordPress 5.6 RC1. This is pretty frustrating, can't drag a focal point in Safari!

![Screen Capture on 2020-11-24 at 13-07-57](https://user-images.githubusercontent.com/4167300/100029519-5c90f100-2e56-11eb-8412-801453d18cb6.gif)

Seems fine in Firefox and Chrome.

**Comment by youknowriad** [comment]
I can reproduce this one consistently as well.

**Comment by ItsJonQ** [comment]
I just created a PR for the disappearing Focal Point UI. 
Will look into the Safari interaction issues 🙏
