### ISSUE TITLE
Add a filter that can disable the Widgets editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25823]
The Classic Editor plugin should support disabling the Widgets editor. To do that I propose we add a filter that enables / disables the new editor. This way the plugin only has to hook into that filter and return `false`.

Say a condition like `apply_filters( 'use_widgets_block_editor', true ) !== true`  is all it takes for a plugin to easily disable the new experience. The default recommendation will be the Classic Editor plugin but any other plugin could hook into this filter.

I think this is a better option than using theme supports. Theme supports should only be used for features that require theme opt-in due to required implementation of said feature on the theme's side. In this case the Widgets editor is an admin functionality and it should be filtered like all the other admin places.

**Comment by draganescu** [comment]
There is a filter that defaults to the theme supports for widgets, named `gutenberg_use_widgets_block_editor`

**Comment by noisysocks** [comment]
This was discussed briefly during triage: https://wordpress.slack.com/archives/C02RQBWTW/p1602054740405700

We didn't arrive at a consensus on whether or not to change from the current implementation which is that there is a filter which can override what the theme says it supports. 

@draganescu: Are you suggesting we remove the theme supports? 

@youknowriad: Any opinions?

**Comment by draganescu** [comment]
Yes I suggest we remove the theme supports, keep the filter. If anybody wants to opt out they can use the filter.

**Comment by noisysocks** [comment]
One problem that comes to mind is: what if a theme doesn't have the CSS to style blocks in widget areas and wishes to opt out instead of investing in updating the theme?

**Comment by draganescu** [comment]
The theme can use the filter instead of theme supports to opt out, can't it?

**Comment by draganescu** [comment]
I'll close this since we do have the required filter in place.

**Comment by skorasaurus** [comment]
Worth noting that this filter, when added, will also remove all core blocks (custom html, recent posts, shortcodes, recent comments, search bar, RSS, social icons, maybe 1-2 more) that have the widget category from appearing in the editor, even when using the block-editor outside of the widget editor.
