### ISSUE TITLE
Hide "show submenu indicators" if the menu doesn't have nested items

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#25821]
The “show submenu indicator icons” should not be available if the menu doesn’t have sub-items.

**Comment by jasmussen** [comment]
This is fixed:
<img width="1392" alt="Screenshot 2021-12-23 at 13 01 56" src="https://user-images.githubusercontent.com/1204802/147237739-ad293e2c-3bd5-4866-b7eb-93594be0e72f.png">
