### ISSUE TITLE
The widgets link in admin top bar is wrong

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25828]
### To reproduce:

- have Gutenberg plugin installed and updated to 9.1
- be sure you're logged in
- visit the website's front-end
- on the black top bar hover over the website's name
- in the menu click on Widgets
- notice you are in the old editor

### Expected:

- when enabled the widgets editor should be linked from all the places we refer to it

### Screenshots:

<img width="1350" alt="Screenshot 2020-10-05 at 14 49 09" src="https://user-images.githubusercontent.com/107534/95076400-734e7d80-071a-11eb-96a8-b05edb1f814a.png">

**Comment by kishanjasani** [comment]
Please close this issue. It's already created by you. check #25827 .

**Comment by draganescu** [comment]
Thank you @kishanjasani I closed the other one. Can't tell how that happened :)
