### ISSUE TITLE
Try to reuse classes from core widgets in the blocks that replace them

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25822]
#25670 added the same wrappers for widgets on the areas edited in the new editor.
As a next step, add the same classes from the core widgets that blocks replace to the block widgets that use them.

For example, the archive widget is replaced by the archive block. The archive widget when rendered has a class on it's root container of `widget_archive` but the block replacement has `widget_block`. The problem is that the different widget blocks should be differentiable via root element classname.

The Archives block:

```
<div class="widget widget_block">
	<div class="widget-content">
		<ul class="wp-block-archives-list wp-block-archives">
			<li><a href="http://localhost:8889/?m=202009">September 2020</a></li>
			<li><a href="http://localhost:8889/?m=202004">April 2020</a></li>
		</ul>
	</div>
</div>
```

The Archives widget:

```
<div class="widget widget_archive">
	<div class="widget-content">
		<ul>
			<li><a href="https://test.local/2020/08/">August 2020</a></li>
			<li><a href="https://test.local/2020/07/">July 2020</a></li>
		</ul>
	</div>
</div>
```

So the archives block should preserve the `widget_archive` classname, along with the `widget_block` one. If possible this should only happen when the block is rendered in an widget area. This hints to a solution where we could inject this classname at render time on the server to get:

```
<div class="widget widget_archive widget_block">
	<div class="widget-content">
		<ul class="wp-block-archives-list wp-block-archives">
			<li><a href="http://localhost:8889/?m=202009">September 2020</a></li>
			<li><a href="http://localhost:8889/?m=202004">April 2020</a></li>
		</ul>
	</div>
</div>
```

This should be achieved for all the core widgets which have been replaced by blocks.

**Comment by noisysocks** [comment]
This was discussed briefly during triage: https://wordpress.slack.com/archives/C02RQBWTW/p1602054388395000

Let's investigate what we can do here.

**Comment by mtias** [comment]
This is super important to get a good baseline on. Why is the `widget_block` class needed?

**Comment by noisysocks** [comment]
I explored setting the classname dynamically depending on the block that's within the block widget in https://github.com/WordPress/gutenberg/pull/26375. Let me know what you think.

> This is super important to get a good baseline on. Why is the `widget_block` class needed?

I think it's helpful to leave this class here so that CSS authors can tell when it's a block that's pretending to be a widget as opposed to an actual widget.
