### ISSUE TITLE
Improvements to block navigator in navigation block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#25820]
We should rename the modal to “edit navigation” or something to that effect. It needs to allow adding new items. Currently, selecting an item closes the overlay, which makes interacting with it difficult.

**Comment by Thelmachido** [comment]
Hi @mtias not entirely sure what is being overlayed when you try to select a new item on the navigation block. Would it be possible to add more information or screenshots?

**Comment by mtias** [comment]
This referenced a moment in time when the navigation list was being rendered in a modal. No longer relevant.
