### ISSUE TITLE
Newly added categories should be added on top of the list and be checked

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2582]
In the classic editor, when adding categories, they're added on top of the categories list regardless of the alphabetical order. This is to give users the ability to easily check the new added categories.

They're also checked by default:

![screen shot 2017-08-28 at 23 15 17](https://user-images.githubusercontent.com/1682452/29794155-1385992a-8c47-11e7-8232-235800d2c237.png)

In Gutenberg, the newly added categories are not added to the list at all. Not sure how this feature is even usable this way.

**Comment by youknowriad** [comment]
> In Gutenberg, the newly added categories are not added to the list at all. Not sure how this feature is even usable this way.

This was working, could be a regression, investigating
