### ISSUE TITLE
Drag and drop of legacy widgets into blocks works but doesn't render

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25834]
### Reproduce:

- have the Gutenberg plugin installed and updated to 9.1
- have some non-core widgets (e.g. Astra widgets)
- login into admin and go to Appearance > Widgets
- Add a columns block
- In one of the columns add some text
- Add a legacy widget and pick one of the non-core widgets
- Drag the legacy widget in the columns block
- Save the widgets
- Go to the front-end
- Notice the legacy widget does not show up in the columns

### Expected

One of:

a) Can't drag and drop legacy widgets as nested blocks in blocks
b) Legacy widgets render when they're nested inside other blocks

**Comment by adamziel** [comment]
While it would be awesome to make drag and drop work here, widgets are not really designed for nesting. Let's prevent drag and drop as an easy fix and keep the discussion open.
