### ISSUE TITLE
[Widgets Editor] The blue line indicator below a legacy widget doesn't have enough margin

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#25848]
**Describe the bug**
As per https://github.com/WordPress/gutenberg/pull/25727#issuecomment-703526524.

The blue line indicator shown when inserting a block via DnD or the global inserter doesn't have enough margin below a legacy widget block. See the screenshot below for more information.

**To reproduce**
1. Go to 'Widgets Editor'
2. Create a legacy widget
3. Open the global inserter
4. Observe that the blue line indicator doesn't have enough margin below the legacy widget

**Expected behavior**
There should be enough margin so that the blue line indicator is clear enough.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/205419/95065196-ffec4200-0700-11eb-8f5d-43542f0f0cb0.png)

**Comment by kevin940726** [comment]
Seems like it's not only a problem of the Legacy Widget block, any block could have this issue, just that the borders of the Legacy Widget block make it obvious.

![image](https://user-images.githubusercontent.com/7753001/95175864-acf0b880-07ee-11eb-9c20-fd07dcef9e24.png)

Here's a screenshot of the same issue happening in the Cover block. There's a blue line indicator at the bottom of the image, just that it's very hard to see.

Currently, the blue line indicator is using `margin-top: -28px` to move itself 28px up from the anchor block it's attached to. The margin between 2 adjacent blocks is also 28px long. Maybe we can increase `margin-top` of the blue line indicator to `-14px`? So that it can place itself in the middle of 2 adjacent blocks.

Here's what it would look like in the Widgets editor.

![image](https://user-images.githubusercontent.com/7753001/95176356-5b94f900-07ef-11eb-9541-0beeddfc5906.png)

Thoughts? Caveats?

**Comment by talldan** [comment]
> Maybe we can increase margin-top of the blue line indicator to -14px? So that it can place itself in the middle of 2 adjacent blocks.

@kevin940726 The drop indicator also uses a similar calculation to make its blue line appear mid-way between blocks:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L101

It's not perfect, I think in an ideal world both systems would be consolidated and calculate the exact position between blocks using `getClientBoundingRect` on the two DOM elements (unless they're first or last).
