### ISSUE TITLE
Dropdown menu options not read by JAWS (screenreader)

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#25847]
**Describe the bug**
As noted a couple of times in a talk for WP Accessibility Day 2020 (https://youtu.be/-fKkptFna9E?t=20368, https://youtu.be/-fKkptFna9E?t=20887), dropdown menus options don't seem to be read by JAWS.

I'm not sure if this relates to just these two menus or other menus as well. Looking at the markup for these menus, I can't see any obvious issues.

**To reproduce**
I haven't tested this myself, but judging by the video:

**Block transform menu**
1. Add a paragraph block
2. Shift tab to the toolbar
3. Press space to open the menu
4. Use up/down arrow keys to cycle through the options

**Preview menu**
1. Add some content to a post
2. Navigate to the Preview button
3. Press space to open the menu
4. Use up/down arrow keys to cycle through the options

**Expected behavior**
The screenreader reads the menu options

**Screenshots**
See the video examples at these links:
- https://youtu.be/-fKkptFna9E?t=20368
- https://youtu.be/-fKkptFna9E?t=20887

**Comment by afercia** [comment]
@talldan what browser were you testing with?

Chrome has a known but (actually a regression) that I already reported and it's fixed, will be released with Chrome 86. See https://bugs.chromium.org/p/chromium/issues/detail?id=1114712#c4

Inspecting the menuitem accessible name in the Chrome dev tools > Accessibility tab, you should see that's it's wrongly exposed as an empty string.

**Comment by talldan** [comment]
Thanks @afercia, yes it was Chrome, good to see a fix is now merged 🎉

**Comment by afercia** [comment]
For history: I just got my Chrome updated to Chromium 86 and the bug is fixed, as expected (it could be reproduced with all screen readers). Screenshot of VoiceOver reading out the Block transform menuitems:

<img width="893" alt="Screenshot 2020-10-07 at 16 58 56" src="https://user-images.githubusercontent.com/1682452/95348866-c06b5480-08be-11eb-9908-03bf8554c5da.png">
