### ISSUE TITLE
Refactor reusable blocks to not depend on the editor module

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25853]
If we want the widgets editor to allow reusable blocks we need to refactor the reusable blocks functionality to not depend on `@wordpress/editor` as the widgets editor does not use this module.

@jorgefilipecosta added a few PRs to remove the dependency on `@wordpress/editor` from the Widgets editor and other places as sometimes the module is used as a convenience instead of for a real need.

**Comment by adamziel** [comment]
Solved by #25859
