### ISSUE TITLE
Unify help or description text styling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25851]
This is a small pickup and I am going to spin up a PR to go with this issue. Currently, there are a few variations in our help text. Some have italics, some don't. The default style has italics. What this small PR looks to start is unify where we have help styling and try and bring in one style. 

## Classes impacted.

The following is a list of classes impacted:

`.components-base-control__help
.components-form-token-field__help`

## In action
The following images show the idea of what trying to work towards in unifying the styling. Currently these don't have the same styling. Here are before:

![image](https://user-images.githubusercontent.com/253067/95175588-9a0cc280-07b3-11eb-8681-4ee0eabfd071.png)

![image](https://user-images.githubusercontent.com/253067/95175629-a7c24800-07b3-11eb-8a08-f7c1922bcd50.png)

Here hopefully with unification:
![image](https://user-images.githubusercontent.com/253067/95174666-4a79c700-07b2-11eb-9e10-3a7ab3dc091e.png)

![image](https://user-images.githubusercontent.com/253067/95175216-118e2200-07b3-11eb-9b8a-27bb9eb015b6.png)

## Feedback
I am looking for feedback around this styling. Looping in @jasmussen here and giving big props for the nudge to clean this up along with work being done in options iterations.

**Comment by jasmussen** [comment]
This looks like a nice win.

**Comment by karmatosed** [comment]
Looks like this didn't close with the PR so closing as this is now merged.
