### ISSUE TITLE
Cover Block: Wave Styles Cover Up Text

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#25866]
**Describe the bug**
The wave styles make text unreadable, by hiding it underneath a wave. 

**To reproduce**
1. Create a page.
2. Add a Cover Block, give it a background color, and add some text to it, for example:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
3. Click the Cover Block - Styles, and choose Top Wave or Bottom Wave.
4. The styles do not adjust to the amount of text displayed, and the waves will cover up text.

**Expected behavior**
The block styles to adjust depending on the text added to the block.

**Screenshots**
![coverblockstyles](https://user-images.githubusercontent.com/30731356/86847691-9442fc00-c061-11ea-874c-637919f8b509.gif)

**Editor version:**
v9.1.0

**Comment by paaljoachim** [comment]
Hey

It looks like you have another block plugin installed. In addition to Gutenberg. As there are no wave styles in the Cover Block.

Gutenberg plugin 9.1
![Screen Shot 2020-10-07 at 11 04 23](https://user-images.githubusercontent.com/5323259/95310622-ec6de200-088c-11eb-8cac-0cc3c2ca9233.png)

It looks like your using the CoBlocks plugin. Here is the support forum for CoBlocks: https://wordpress.org/support/plugin/coblocks/

I will go ahead and close this issue.
