### ISSUE TITLE
On Firefox when 'Top toolbar' is enabled, some editor toolbar options are missing

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#25863]
**Describe the bug**
When using Firefox and with the 'Top toolbar' enabled, the 'Modes', 'Undo/Redo', 'Details’' and 'Outline' buttons are missing.

**To reproduce**
1. Open the block editor in Firefox
2. Enable 'Top toolbar' from the 'Options' menu
3. Look for the 'Modes', 'Undo/Redo', 'Details’' and 'Outline' buttons

**Expected behavior**
I expected those options to be present regardless of toolbar setting

**Screenshots**
<img width="736" alt="Screen Shot 2020-10-06 at 9 30 05" src="https://user-images.githubusercontent.com/3276087/95216891-3638c880-07b8-11eb-80b5-e86806e392f7.png">

**Editor version (please complete the following information):**
- WordPress version:
**5.5.1**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?
**Plugin**
- If the Gutenberg plugin is installed, which version is it?
**9.1.0** 

**Desktop (please complete the following information):**
 - OS: 
**MacOS 10.15.6**
 - Browser :
**Firefox 81.0**

**Comment by nosolosw** [comment]
I cannot repro this. Tested in:

- WordPress 5.5.1 with Gutenberg 9.1 activated
- WP 5.5.1 with Gutenberg latest master activated
- WP 5.5.1

It was in Ubuntu 20.04 (OS) and Firefox 81.

**Comment by enriquesanchez** [comment]
Thanks @nosolosw 

It was an error on my side. I had the new 'Compact interface' option turned on: 

<img width="358" alt="Screen Shot 2020-10-06 at 14 05 05" src="https://user-images.githubusercontent.com/3276087/95248535-0b14a000-07dd-11eb-84af-03eebd951e50.png">

🙂
