### ISSUE TITLE
List Block: Add ability to sort list in numbered/alphabetical order or reverse order

### ISSUE THREAD

**Issue by claytoncollie** [WordPress/gutenberg#25871]
**Is your feature request related to a problem? Please describe.**
My client wants to sort their ordered list from top to bottom (1 -> 10) and from bottom to top (10 -> 1). 

They also would like to sort their lists alphabetically with the same logic as described above.

**Describe the solution you'd like**
There is a plugin, [Lazy List](https://wordpress.org/plugins/lazy-lists/), that inserted a toolbar button. This is a clean solution. The plugin is archived. Here is the [Github repository](https://github.com/sortabrilliant/lazylists).

**Comment by bahia0019** [comment]
Came here to submit this. Definitely a need for Alpha. There is a spec in HTML for OL Type Attributes.
https://www.w3schools.com/tags/att_ol_type.asp 

If it's in the HTML spec, this should be a default option for the List block.

**Comment by skorasaurus** [comment]
Hi, 

Reversing an ordered list when the marker is a number is possible in Gutenberg. 

Having alphabet letters as markers in a list been requested at https://github.com/WordPress/gutenberg/issues/13888 ; you can subscribe to that issue to track its progress and share your feedback there.
