### ISSUE TITLE
Cannot run demo Android app from the command line

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#25883]
**Describe the bug**
The Gutenberg mobile demo app fails to build using `npm run native android`.

**To reproduce**
1. Run `npm run native android` and let it open a separate window with the packager
2. Notice a red screen in the emulator (500 packager error)

**Expected behavior**
Running `npm run native android` should fire up the packager and run the demo app successfully

**Screenshots**

<img width="500" alt="Screenshot showing 500 packager error" src="https://user-images.githubusercontent.com/1898325/95270475-ebe43580-0811-11eb-83ba-0ecf6a9493db.png">

**Smartphone**
 - Device: Android Emulator
 - OS: Android API 29
 - Demo App Version https://github.com/WordPress/gutenberg/commit/c2ea1b27df08117dbf53200630e8a627f4479df1

**Additional context**
A workaround is to run `npm run native start:reset` in one window and `npm run native android` in another.

**Comment by hypest** [comment]
👋 @cameronvoell , assigned this to you as it looks like something we need to fix soon. Thanks!

**Comment by kathrynwp** [comment]
@hypest @cameronvoell Hi there, just circling back to see if this is still an issue. Thanks!

**Comment by dcalhoun** [comment]
Hey @kathrynwp. 👋🏻 I tested this now and was unable to reproduce the issue with the latest `trunk` branch and a Pixel 3a (API 33) emulator. Following the [Getting Started for the React Native based Mobile Gutenberg](https://github.com/WordPress/gutenberg/blob/88f80c6254f469ccd7dd81d8bf0ddb4386905526/docs/contributors/code/react-native/getting-started-react-native.md) steps appear to succeed. Closing this, but feel free to reopen if needed. Thanks! 🙇🏻

**Comment by kathrynwp** [comment]
@dcalhoun Thanks very much!
