### ISSUE TITLE
Navigation Block:  Colors selections display differently between editor and frontend

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#25889]
**Describe the bug**
Color selections for the navigation block using named CSS color classes, appear different between the editor and frontend.

When the color palette differs between the editor and frontend, or when the theme doesn't provide a color palette at all, the color the user selects is not reflected on the frontend.

Further discussion, background, and an ad-hoc approach to forcing this consistency ( https://github.com/WordPress/gutenberg/pull/25691/commits/8b84c42ef3955624cc2efad65a78bfb2afe717ab ) was originally included in https://github.com/WordPress/gutenberg/pull/25691.

**To reproduce**
This is an issue across multiple themes ( TwentyTwenty, Maywood etc ) however is best observed in a theme that doesn't provide a full colour palette to the editor such as Varia.

1. Start with Varia theme active
2. Create a post and add a navigation block to it
3. Select different color combinations for the navigation block and notice some do not display correctly in the editor.
4. Save the post and view on the frontend and see a completely different set of colors displayed.
5. Switch themes and repeat steps 2-4. There will still be inconsistent behaviour.

**Expected behavior**
The color I select in the editor to be the one shown on the frontend.

**Screenshots**
| Varia |TwentyTwenty | Maywood | 
|------|---------------|-----------|
| ![NavigationBlockColors-Varia-Bug](https://user-images.githubusercontent.com/60436221/94518379-27f52480-026d-11eb-93f0-bdca36e8c178.gif) | ![NavigationBlockColors-TwentyTwenty-Bug](https://user-images.githubusercontent.com/60436221/94518366-24619d80-026d-11eb-8ca7-09570506e94a.gif) | ![NavigationBlockColors-Maywood-Bug](https://user-images.githubusercontent.com/60436221/94518351-1d3a8f80-026d-11eb-8683-c9c3bd87f189.gif) |

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg plugin 9.1

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browsers: Chrome, Safari, Firefox
 - Versions: Latest

**Comment by tellthemachines** [comment]
Hi @aaronrobertshaw, I can only reproduce this bug in the Navigation block. Have you found it in any other blocks?

**Comment by aaronrobertshaw** [comment]
Thanks for taking the time to look at this one @tellthemachines 

I'd previously seen it in another dynamic block, social links, when using the colors hook in a separate PR. I've rebased that one though and cannot replicate the issue there now. I'll take a closer look at the navigation block and see if I can spot something specific causing this problem, then update this issue accordingly.

**Comment by aaronrobertshaw** [comment]
It looks like recent improvements to block supports has fixed up a few of these issues. I currently have a PR (https://github.com/WordPress/gutenberg/pull/25691) that will address the navigation block. If it is accepted I think it will close this issue.

**Comment by tellthemachines** [comment]
Is this still an issue? I notice the attached PR was closed, so can we close this one as well?

**Comment by aaronrobertshaw** [comment]
Yes, my mistake. Closing this now. Thanks 🙂
