### ISSUE TITLE
ButtonBlockAppender component in /block-editor is exported with incorrect name

### ISSUE THREAD

**Issue by daledesilva** [WordPress/gutenberg#25885]
**Describe the bug**
Inside the components index file in block-editor, The ButtonBlockAppender is exported as ButtonBlock**er**Appender

This file:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/index.js

**ie. line 25 is:**
`export { default as ButtonBlockerAppender } from './button-block-appender';`
**but should be:**
`export { default as ButtonBlockAppender } from './button-block-appender';`

**Expected behavior**
It should be exported as it's expected name.

**Editor version:**
- WordPress version: 5.5.1
- Default block editor

**Comment by daledesilva** [comment]
Related issue that could cause confusion:
https://github.com/WordPress/gutenberg/issues/25886

**Comment by talldan** [comment]
Oh dear! I think it's been like this for a while, too. 😄 

Should be an easy fix and would be happy to see a contribution that fixes it.

We may have to leave the incorrect export in the codebase to ensure backwards compatibility.

**Comment by gaavar** [comment]
@talldan I created a pull request to fix this. I also noticed that the pull request requires some form of testing. I need some guidance on how to test this change.

**Comment by Mamaduka** [comment]
Fixed via #32580.
