### ISSUE TITLE
Classic Text widget throws error

### ISSUE THREAD

**Issue by BackuPs** [WordPress/gutenberg#25891]
Inserting a classic text widget throws this message in any theme

![afbeelding](https://user-images.githubusercontent.com/6078370/95294450-93df1a80-0875-11eb-9a87-7c5a92fa1521.png)

**Comment by skorasaurus** [comment]
The classic block is not supported in full-site editing/block themes; any existing classic text widgets should automatically be converted to HTML blocks. (ref https://github.com/WordPress/gutenberg/pull/48129 and https://github.com/WordPress/gutenberg/issues/48938). 

Please reopen if you are still experiencing this issue in current version of Gutenberg and WordPress.
