### ISSUE TITLE
Widgets screen: PHP notices with the legacy Recent Posts widget and possibly other legacy widgets

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#25910]
**Describe the bug**
While testing the new Widgets screen, I noticed a blank space at the top of the admin menu:

<img width="714" alt="Screenshot 2020-10-07 at 17 23 15" src="https://user-images.githubusercontent.com/1682452/95351886-f4944480-08c1-11eb-8d5e-c391ca86378b.png">

this space is added by the core `php-error` CSS class set on the body when some PHP notice/warning/error is detected. Its purpose is to make the notice/warning/error text fully visible. However, there was no output so this was a bit difficult to debug.

Turns out it happens when a Recent Posts widget is already in use.

**To reproduce**
- on 5.6. trunk, active theme: Twenty Twenty
- make sure `define( 'WP_DEBUG', true );` is set in your `wp-config.php` file
- deactivate the Gutenberg plugin
- go to the legacy Widgets page and add a Recent Posts widget in the Footer #1 area 
- save
- navigate away from the Widgets page
- activate the Gutenberg plugin
- go to the new Widgets screen
- notice the space at the top of the admin menu
- enable the Query Monitor plugin
- see it lists 4 "Undefined index" notices related to the arguments `before_widget`, `before_title`, `after_title`, `after_widget`

Screenshot:

<img width="947" alt="Screenshot 2020-10-07 at 17 13 29" src="https://user-images.githubusercontent.com/1682452/95352704-c6fbcb00-08c2-11eb-86fe-9c0eef891e3c.png">

I tested only with the Recent Posts widget but likely these notices are triggered also with other legacy widgets.

**Expected behavior**
To not have PHP notices.

**Editor version (please complete the following information):**
- WordPress version: 5.6  trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1

**Comment by afercia** [comment]
Props to @fklein-lu for reminding me to use Query Monitor and to @johnbillion for making it 😄

**Comment by johnbillion** [comment]
Possibly https://core.trac.wordpress.org/ticket/51383 ?

**Comment by johnbillion** [comment]
Hmm no because those aren't suppressed errors. Same result, different cause.

**Comment by talldan** [comment]
I was also seeing this issue previously, but not anymore. Anyone else?

**Comment by noisysocks** [comment]
I still see this whitespace locally.

**Comment by kevin940726** [comment]
I'm not seeing this error on WordPress 5.6, Gutenberg 9.7.0, and following all the above reproduction steps. 🤔

**Comment by noisysocks** [comment]
I am no longer able to reproduce this in `trunk`. Thanks for the detailed reproduction steps @afercia.
