### ISSUE TITLE
Site Editor: patterns are not available in inserter for template parts

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#25915]
Currently the patterns tab in the inserted is only visible in site editor when top level `Document` or `Document -> Group` are selected. As soon as we focus template parts, post content, or any more deeply nested block it disappears. This shouldn't be he case and we should be able to use patterns to fill out these areas too (at a minimum top-level template part insertion should be supported).

**Comment by jeyip** [comment]
Where the conditional logic to render the patterns tab lives
- [packages/block-editor/src/components/inserter/menu.js:147](https://github.com/WordPress/gutenberg/blob/b3620b550f79e0aaa112d8c6320ab4f7b69c5ec5/packages/block-editor/src/components/inserter/menu.js#L146)
- [packages/block-editor/src/components/inserter/menu.js:61](https://github.com/WordPress/gutenberg/blob/b3620b550f79e0aaa112d8c6320ab4f7b69c5ec5/packages/block-editor/src/components/inserter/menu.js#L61)
