### ISSUE TITLE
Widgets screen: PHP fatal error when switching a Legacy widget to Preview

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#25912]
**Describe the bug**
The Legacy widgets in the new Widgets screen trigger a fatal error when switching to Preview.

In the Legacy widgets there are two buttons: Edit and Preview to switch the widget to different modes:

<img width="914" alt="Screenshot 2020-10-07 at 17 59 39" src="https://user-images.githubusercontent.com/1682452/95357132-c9145880-08c7-11eb-89fa-afac507808b3.png">

When clicking "Preview" a PHP fatal is triggered:
`Uncaught Error: Call to undefined function get_current_screen() in /srv/www/wordpress-develop/public_html/build/wp-content/plugins/gutenberg/lib/widgets-page.php:136`

<img width="1005" alt="Screenshot 2020-10-07 at 17 59 46" src="https://user-images.githubusercontent.com/1682452/95357209-dfbaaf80-08c7-11eb-8446-8d7590e4e23f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6 trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1

**Comment by draganescu** [comment]
I stumbled upon this as well.

**Comment by talldan** [comment]
I couldn't reproduce this. @draganescu would you be able to re-test?

**Comment by draganescu** [comment]
No fatal error anymore but I can't see a preview either (using recent posts)

**Comment by talldan** [comment]
Hmm, yeah, that's what i'm seeing as well, though it does seem intermittent.

**Comment by sirreal** [comment]
I came across a fatal error that seemed to be related. The context was a plugin that split a template file from a functions file. The function file defined a helper `my_plugin_is_single`, and the template file called this function in a `body_class` filter function.

The plugin requires the template file on all requests, but the functions fire only on non-admin requests. This was fine, I believe `body_class` filter is not usually applied on admin requests. However, with the legacy widget preview this is no longer true:

https://github.com/WordPress/gutenberg/blob/c4102618dfc90d5428009e5fbd553668117fa3ee/lib/widget-preview-template.php#L31

Example code:

```php
// plugin entry point
if ( is_admin() ) {
	require_once( __DIR__ . '/inc/class-templates.php' );
} else {
	require_once( __DIR__ . '/inc/class-templates.php' );
	require_once( __DIR__ . '/inc/functions.php' );
}

// inc/functions.php
function my_plugin_is_single() { /* … */ }

// inc/class-templates.php
class My_Plugin_Templates {

	public function __construct() {
		add_action( 'body_class', array( $this, 'my_body_class' ) );
	}

	public function my_body_class( $classes ) {
		if ( my_plugin_is_single() ) {
			$classes[] = 'single';

		}
		return $classes;
	}
 }

 new My_Plugin_Templates();
```

**Comment by noisysocks** [comment]
I'm unable to reproduce this.
