### ISSUE TITLE
Widget Editor: Tabbing through widget areas does not scroll the page

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#25927]
**Describe the bug**
When tabbing between widget areas the page scroll position does not follow keyboard focus, and so it's hard to tell where my focus is:

![2020-10-07 16-36-46 2020-10-07 16_38_40](https://user-images.githubusercontent.com/3276087/95391631-fdcee280-08bc-11eb-9f4c-b0eba8ac6a40.gif)

**What was expected**
I expected to see the page scroll follow my keyboard focus.

**Comment by draganescu** [comment]
I think the tabbing should move the scroll. It's virtually impossible to discern what happened when focus moves below the fold. What kind of Accessibility Feedback is needed?

**Comment by enriquesanchez** [comment]
> What kind of Accessibility Feedback is needed?
