### ISSUE TITLE
Click on "Open in new tab" control causes hyperlink creation UI popover to close 

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#25946]
**Describe the bug**
When creating a link on a portion of text in a paragraph block you may wish for the link to open in a new tab. There is a control in the hyperlink creation popover UI which allows you to toggle this feature on/off. However, when it is clicked the hyperlink creation UI popover closes. 

This is undesirable as you may wish to toggle this feature on/off several times or you may have made a mistake. In this case the fact that the UI disappears each time a change is made is quite frustrating. I assume this is due to a re-render of the `LinkControl` component but I could be wrong.

**To reproduce**
1. Create new Post
2. Add some text in a paragraph block
3. Highlight some of the text and create a link.
4. Now use the toggle control for "Open in new tab".
5. Notice how clicking/toggling the control will cause the link UI to disappear.

**Expected behavior**
The link creation UI should not close when the toggle control is interacted with. It should remain open until it is dismissed.

**Screenshots**

![Screen Capture on 2020-10-08 at 09-27-05](https://user-images.githubusercontent.com/444434/95434235-e9d0c280-0948-11eb-907c-1a2f677a8f22.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? 9.9.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by willRicard** [comment]
Hello, I would very much like to help investigate and/or fix the problem. I can reproduce since I'm running on the same software, I'll update if I find anything.

**Comment by willRicard** [comment]
I got to reproduce the bug, now I am in the process of getting the React DevTools to work with Gutenberg to find out what dependency is triggering the close.

**Comment by guarani** [comment]
FWIW, the modal doesn't close when the "Open in new tab" button is toggled during link creation, only when editing an existing link can I reproduce this bug.

| <img width="600" alt="screen recording showing open in new tab not closing modal when link is being added" src="https://user-images.githubusercontent.com/1898325/96451761-7489ab00-11ee-11eb-993d-a38c40a3b09c.gif"> |
| - |

**Comment by getdave** [comment]
Closing in favour of more comprehensive issue in https://github.com/WordPress/gutenberg/issues/45741
