### ISSUE TITLE
The Rich text component throws react warnings in the console

### ISSUE THREAD

**Issue by pavel-mailpoet** [WordPress/gutenberg#25950]
**Describe the bug**

I am building a plugin with Gutenberg and when using the Heading component I get React Waringns in the console:

```
Warning: React does not recognize the `textAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textalign` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

There are currently 4 warnings for those props: `shouldBlurOnUnmount`, `textAlign`, `blockIsSelected`, `onCaretVerticalPositionChange`

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- I am using npm packages and the block editor is version 5.0.0

![Screenshot 2020-10-08 at 14 10 48](https://user-images.githubusercontent.com/29194603/95456782-27951180-0970-11eb-84e2-60db165215b1.png)

**Comment by noisysocks** [comment]
Hey @pavel-mailpoet, could you please provide a code sample which shows how your plugin is using the Heading component? That will help us figure this one out.

**Comment by pavel-mailpoet** [comment]
Hey @noisysocks, thanks for the answer. We are using the Heading like this:
https://github.com/mailpoet/mailpoet/blob/master/assets/js/src/form_editor/blocks/heading/heading.jsx
And it is registered later here: https://github.com/mailpoet/mailpoet/blob/master/assets/js/src/form_editor/blocks/blocks.jsx#L54

**Comment by pavel-mailpoet** [comment]
It seems to be fixed in the new version.
