### ISSUE TITLE
Standalone Block Editor - Library Popover Not Working 

### ISSUE THREAD

**Issue by TeamDNK** [WordPress/gutenberg#25967]
**Describe the bug**
I am implementing a new standalone block editor based on the documentation [tutorial](https://developer.wordpress.org/block-editor/developers/platform/custom-block-editor/). The block editor loads in well except when I attempt to add a new block by hitting the plus button. The block-editor goes blank and the following error gets thrown: 

`TypeError: undefined is not an object (evaluating 'patterns.length')`

I had first assumed that my block settings were not setup correctly or had missing props. But after looking into it the following line from [dist/block-editor.js::25907](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/dist/block-editor.js) is what is throwing the error:

`var showPatterns = !destinationRootClientId && patterns.length && !!filterValue;`

I spent a lot of time trying to figure out what's going on here but I am not very familiar with the blocks editor development. 

**To reproduce**
1. Implement Standalone Editor
2. Click on the [+] button to add new block
3. See error

**Expected behavior**
The blocks library popover should trigger to allow selecting a block.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Core block editor

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser: Safari
 - Version: 14

**Comment by talldan** [comment]
@TeamDNK I think this has already been fixed by this pull request - https://github.com/WordPress/gutenberg/pull/24554.

Are you using an up-to-date version of the block editor package? v5.0.0 was released very recently on npm.

I checked using the standalone block editor in the storybook that's part of this project:
https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default

The library works there. Unfortunately there's now a separate bug:
https://github.com/WordPress/gutenberg/issues/25975

**Comment by talldan** [comment]
Ah I realize now the library might not be implemented on the example I linked to above. Anyway, let me know if you're still experiencing issues after updating packages. A code example of how the library has been implemented would be great too.

**Comment by TeamDNK** [comment]
@talldan Thanks for the help. I am not using node so basically everything is enqueued using standard wordpress enqueued dependencies. 

`$deps = array( 
	'wp-block-editor',
	'wp-block-library',
	'wp-blocks',
	'wp-components',
	'wp-core-data',
	'wp-data',
	'wp-dom-ready',
	'wp-element',
	'wp-format-library',
	'wp-media-utils',
);`

So everything should be using the latest versions. I am still trying to flush this out, but I think I may be having a similar issue as https://github.com/WordPress/gutenberg/issues/23885. Here is what the BlockEditorProvider component looks like:


```
wp.element.createElement(
	BlockEditorProvider,
	{
		value: blocks,
		onInput: handleUpdateBlocks,
		onChange: handlePersistBlocks,
		settings: settings,
	},

	wp.element.createElement(Sidebar.InspectorFill, null, wp.element.createElement(BlockInspector, null)),

	wp.element.createElement(
		'div',
		{
			className: 'edit-post-visual-editor editor-styles-wrapper',
		},
		wp.element.createElement(BlockEditorKeyboardShortcuts, null),
		wp.element.createElement(
			WritingFlow,
			null,
			wp.element.createElement(
				ObserveTyping,
				null,
				wp.element.createElement(BlockList, {
					className: 'block-editor-blocklist',
				})
			)
		)
	)
)
```

And then my Block Editor settings are constructed and localized:

```
$settings = array(
	'disableCustomColors'   	=> get_theme_support( 'disable-custom-colors' ),
	'disableCustomFontSizes' 	=> get_theme_support( 'disable-custom-font-sizes' ),
	'disableCustomGradients'	=> get_theme_support( 'disable-custom-gradients' ),
	'isRTL'                  	=> is_rtl(),
);
list( $color_palette, ) = (array) get_theme_support( 'editor-color-palette' );
list( $font_sizes, )    = (array) get_theme_support( 'editor-font-sizes' );
if ( false !== $color_palette ) {
	$settings['colors'] = $color_palette;
}
if ( false !== $font_sizes ) {
	$settings['fontSizes'] = $font_sizes;
}

return $settings;
```

**Comment by talldan** [comment]
Hey @TeamDNK, If you add the following to your settings, does it resolve the issue?
```
 __experimentalBlockPatterns: array(),
__experimentalBlockPatternCategories: array(),

**Comment by TeamDNK** [comment]
@talldan After defining those settings, it did in fact resolve the error we were experiencing. We will leave these settings in there for the time being until https://github.com/WordPress/gutenberg/pull/24554 is shipped to core. Thank you for your help.
