### ISSUE TITLE
Block tools not responding

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#2597]
Using Gutenberg 1.0, I was inserting an image into a post and wanted to adjust the layout. I dragged and dropped the image into Gutenberg image block (awesome), but when I tried to edit the layout using the toolbar, it wasn't responding.

![image-layout](https://user-images.githubusercontent.com/617986/29849723-8a8280ce-8cdd-11e7-9d62-27719562cb8e.gif)

This seems to be happening for all blocks.

**Comment by karmatosed** [comment]
@mapk were you using a specific browser for this? I'm trying to replicate to test the PR @youknowriad made. I'm having no luck recreating this in Chrome.

**Comment by mapk** [comment]
It was either FF or Chrome. Looking back right now, it appears that it's working fine for both browsers. Not sure if it has to do with reopening the post in Gutenberg again or what.

**Comment by mapk** [comment]
@karmatosed Okay, I just ran another test. This is what you need to do to recreate the problem.

1. Make sure to have a couple blocks of content already created.
2. While in Gutenberg hover over the `insert block` icon at the bottom and click `image` when it appears.
3. Drag and drop an image into the block.
4. Try adjusting the image block or any other blocks from their respective toolbars. None, except the very top block, will work.
