### ISSUE TITLE
search-block color and size not correct.

### ISSUE THREAD

**Issue by rolf-yoast** [WordPress/gutenberg#25978]
**Describe the bug**
The color of the icon and the search text are not the right color.
It also gives an notice output

The search button in the editor seems to small
**To Reproduce**
1. Go to edit a post.
1. Add a search-block.
1. Edit the block and select `use button with icon`
1. You should see the 2nd screenshot. You notice the button with the search icon is not correctly sized.
1. Go to the frontend and you'll see the 1st screenshot. You'll notice the color of the icon is wrong and doesn't match the rest.

for the third image you can only see the button when hovering over it. else you won't see it. On the front-end it seems fine!

**Expected behavior**

**Screenshots**
front-end:
1. ![Screenshot 2020-10-08 at 16 22 39](https://user-images.githubusercontent.com/49080649/95471740-8bc0d100-0982-11eb-9d46-774ef2b99672.png)

Editor:
2. ![Screenshot 2020-10-08 at 16 23 33](https://user-images.githubusercontent.com/49080649/95471899-b14dda80-0982-11eb-864f-8992a94ed8e5.png)

3. ![Screenshot 2020-10-08 at 17 05 12](https://user-images.githubusercontent.com/49080649/95477296-79e22c80-0988-11eb-903f-5c4949693aaf.png)
Editor version (please complete the following information):

4. notice output
![Screenshot 2020-10-09 at 10 10 58](https://user-images.githubusercontent.com/62988563/95559348-e22c1f00-0a17-11eb-826f-338589baec48.png)

WordPress version: [ 5.6]
Gutenberg plugin [ 9.9.1 ]
Desktop (please complete the following information):

OS: [ iOS]
Browser [ chrome ]
Version [85.0.4183.121 ]

**Additional context**

**Comment by tellthemachines** [comment]
I can only reproduce the button misalignment in the editor with Twenty Twenty One; Twenty Twenty and Twenty Nineteen are aligning it correctly. The icon is quite small in the front end across all themes though.
