### ISSUE TITLE
[Release Tool] Add support for creating multiple RCs for the same version

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#25970]
**Is your feature request related to a problem? Please describe.**

Currently, we can't generate multiple RCs for the same Gutenberg version. It always assumes the RC will be the first (RC1) for the next major version. This is problematic if bugs appear in RC1 and we're not confident enough to release the stable version, as right now it's not possible to quickly iterate and release multiple RCs. RCs then become expensive.

**Describe the solution you'd like**

The release tool should be able to generate multiple RC versions - in sequence - for the same version, and we should use as many RC versions as we need. I think the logic can be simple and the tool CLI UI* can be kept the same: as long as the last version is an RC, then the next RC generated will be based in this version plus that RC number + 1. If it's not an RC, then we fallback to the current flow for creating the RC1 for the next major version.

*`./bin/plugin/cli.js rc`

**Comment by ockham** [comment]
WIP PR by @fullofcaffeine: #25971
