### ISSUE TITLE
Update button doesn't become active until you click outside of current block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2598]
## Issue Overview
After editing some Post content (adding text to a Paragraph block), the Update button wont become active/clickable until you click outside of the block.

## Steps to Reproduce (for bugs)
1. Add text to existing Paragraph block
2. Wait for Update button to become active (it never does)

## Expected Behaviour
I would expect that as soon as you change the page in any way, whether that's by one character or a whole paragraph, the Update button should enable. I shouldn't have to click outside of the current block for it to become active.

## Current Behaviour
Update button wont become active until you actually click outside of the current block that you've just edited, which is really annoying if you just want to make a quick text update and click Save/Update.

## Possible Solution
Make the Update button active as soon as any content has been changed, regardless of whether the user has clicked outside of the current block.

_Using Firefox 55.0.3 (64-bit) on OSX 10.12.1
Gutenberg plugin Version 1.0.0_

**Comment by aaronjorbin** [comment]
Duplicate #1240

**Comment by aduth** [comment]
Pending improvement at #2418
