### ISSUE TITLE
allowed_block_types breaks if array keys become non-sequential

### ISSUE THREAD

**Issue by gyrus** [WordPress/gutenberg#25980]
When the blocks array is filtered using `allowed_block_types`, I want to remove some blocks.

Using a loop and a combination of `array_search()` and `unset()`, I remove the blocks I need to remove.

However, it seems that this results in all blocks being available (the same as returning `true` for `allowed_block_types`).

This can be easily averted by using `$blocks = array_values( $blocks )` to reset the array keys so they're sequential again.

However, this seems like a minor bug worth fixing for anyone else removing blocks this way (apply `array_values()` to the array if an array is returned by the `allowed_block_types` filter).

**Comment by noisysocks** [comment]
Hey @gyrus. The call to `apply_filter( 'allowed_block_types' )` exists in WordPress Core, not Gutenberg. Could you please [open a new ticket in WordPress Core Trac](https://core.trac.wordpress.org/newticket) for this? Thanks so much.
