### ISSUE TITLE
Controlling the height of the Separator block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25989]
**Is your feature request related to a problem? Please describe.**
Today we are not able to control the height of the Separator block.

![Screen Shot 2020-10-09 at 13 36 54](https://user-images.githubusercontent.com/5323259/95578678-92a81c00-0a34-11eb-8452-ebf6a0eac39d.png)

Sometimes we might want the block to be shorter and other times taller. To have less or more space in the design.

**Describe the solution you'd like**
It would be helpful to duplicate the settings "height in pixels"  from the Spacer block to the Separator block, so one can control the height. By controlling the height one would be able to create a greater flexibility in the design. 

Here is an example from the Spacer block.

![Screen Shot 2020-10-09 at 13 39 03](https://user-images.githubusercontent.com/5323259/95578836-dac73e80-0a34-11eb-81cc-fac45a69301d.png)

**Describe alternatives you've considered**
Using the Spacer block before/after the Separator block to give more space.
Spacer block
Separator block
Spacer block

Here is also an example from CoBlocks that @richtabor shared here: 
https://github.com/WordPress/gutenberg/issues/16483#issuecomment-509744343

Associated overview issue: https://github.com/WordPress/gutenberg/issues/16483

**Comment by paaljoachim** [comment]
The question comes up...
What if the user wants the line border close to the below content but wants more space above the line?

It could be possible to have two controls.
1 - Add space above border line.
2 - Add space below the border line.
This would control where the line is located in relation to the space added.

**Comment by richtabor** [comment]
> What if the user wants the line border close to the below content but wants more space above the line?

I feel like that could get quite messy. Perhaps something akin to the spacing/dimensions control?

**Comment by paaljoachim** [comment]
Yeah. I agree. The extra control I mentioned with adding space above and below can be as you say messy. Keeping it simple would be helpful. 

I am not sure what you mean when you say spacing/dimension control.

**Comment by simison** [comment]
I had an old branch around for this so I just draft-PRed it: https://github.com/WordPress/gutenberg/pull/26764

I won't have time in the near future to work on it but anyone feel free to take over! It's mostly there if I can remember right.

**Comment by paaljoachim** [comment]
@richtabor 
Would this be something for you to take over?

**Comment by stokesman** [comment]
>Perhaps something akin to the spacing/dimensions control?

>I am not sure what you mean when you say spacing/dimension control.

That would be the approach taken in #28451 🔌

**Comment by tanjoymor** [comment]
Width and thickness controls, in addition to spacing above and below would be amazing, and super useful. The Separator and Dynamic blocks are super limited at the moment.

**Comment by stokesman** [comment]
I wonder if this should be close given that margin support seems to be available as long as the theme has a theme.json and the support isn't disabled by said theme.json.

**Comment by paaljoachim** [comment]
Yeah. As we now can add margin one can then also control the height. So I will close this issue.
