### ISSUE TITLE
Unable to save cropped images from Media Library Edit functionality

### ISSUE THREAD

**Issue by rohanraha156** [WordPress/gutenberg#25981]
**Describe the bug**
When we click in the Edit option in the Media Library and crop the image using the "Crop" button then at first we are unable to Save the image as the "Save" button is disabled.

Secondly, when we are cropping and saving the image, then the cropped image is not getting saved  

**To reproduce**
1. Go to Media -> Library -> Click and edit one of the image 
2. Click on "Edit Image" button. Different Editing options will be available.
3. Select "Crop" button and change the cropping parameters and try to Save the cropped image
4. Save button is disabled and we are unable to save.
5. Click twice on the "Flip Horizontal" button and click on "Crop" button
6. Change the cropping parameters and click on "Save".
7. Successfully saved message is displayed but we are unable to see the cropped image.

**Expected behavior**
At first when we click on the "Crop" Button and change the Cropping paramters then the "Save" button should be enabled
Secondly when we are saving the cropped image, then the newly cropped image should get saved.

**Screenshots**
https://drive.google.com/file/d/184-hOyOt55JZ78OhdFacQajeftOVF5QV/view

**Editor version (please complete the following information):**
- WordPress version:  5.5.1

**Desktop (please complete the following information):**
 - OS: Windows: 10
 - Browser: Chrome
 - Version: 85.0.4183.121

**Comment by talldan** [comment]
Hi @rohanraha156, at step 3 in your instructions above you have to click the 'Crop' button again after resizing to finish cropping. I know it's not particularly intuitive.

The media library isn't part of the Gutenberg code base, it's implemented in WordPress core, so if you'd like to request a change to this you'd have to create a ticket on trac:
https://core.trac.wordpress.org/

It's worth looking through existing tickets to see if anyone else has reported issues related to this too:
https://core.trac.wordpress.org/search?ticket=on&q=crop&page=1&noquickjump=1
