### ISSUE TITLE
Navigation Component: Add Support for RTL Languages

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#25997]
The Navigation component relies on horizontal movement for navigating through nested menus.

Currently, menus slide in from the right when entering a submenu, and from the left when going back to the parent.
The direction should be the opposite on RTL languages.

In the same way, there are several arrow symbol that need to be adjusted (or even moved) according to the RTL directions.

### Note for i18n testers

It's possible to test the Navigation component directly in the storybook, by running `npm run storybook:dev`, and searching for it in the components list.
There are several examples showcasing different features.

**Comment by jeyip** [comment]
@mattwiebe and I were working on RTL support and we saw that animations for the sidebar and submenus already seemed to be behaving as expected.
