### ISSUE TITLE
Move focus of user when clicking to add content block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#26]
It's easy to not notice the selection panel when at bottom of a page. It doesn't load as it's off the screen. Found in Safari.

![03](https://cloud.githubusercontent.com/assets/253067/22751755/c91aa448-ee03-11e6-8206-25e2521bcbce.gif)

**Comment by mtias** [comment]
I think this should open to the top-right.

**Comment by karmatosed** [comment]
@mtias Would perhaps top-left work? My thinking is there are actions on the left already. Although I'm cautious they won't overlap.

**Comment by jasmussen** [comment]
If we are talking about the pop-out media insertion dialog, it's probably good for it to not overlap the text, but worth trying to move it around and seeing how it feels.

Another angle: lots of good discussion yesterday about inserting content _between_ two blocks. This is worth exploring too — perhaps such an exploration will yield a different interface that might solve both issues. I know Ella had a pattern for this in her front-end editor plugin.

**Comment by mtias** [comment]
My main concern for now is that a menu opening to the bottom can be cut-off given window scroll position. Why do you think overlapping on the content above could be problematic?

**Comment by jasmussen** [comment]
> My main concern for now is that a menu opening to the bottom can be cut-off given window scroll position. Why do you think overlapping on the content above could be problematic?

Mostly same concern as has been voiced for the inline popup dialog. Also, I like the idea of the search field being close to the caret when you use `/` on a new line to invoke the dialog. But this is not an objection to showing the dialog above, just a preference. If we test _above_ and that feels better, 👍 from me. Incidentally I just posted this new inserter mockup in #core-editor:

<img width="370" alt="inserter" src="https://cloud.githubusercontent.com/assets/1204802/22780533/5e0d15fc-eebf-11e6-922f-f9b5d5de700b.png">

If "above the plus" feels better, we can just switch out the positions of the search box and category tab strip, have the former at the bottom, and the latter at the top maybe.

**Comment by mtias** [comment]
> Mostly same concern as has been voiced for the inline popup dialog

I think the context is rather different when you are inserting new blocks compared to inline formatting on an individual block.

**Comment by mtias** [comment]
> Also, I like the idea of the search field being close to the caret when you use / on a new line to invoke the dialog.

We could auto-focus search.

**Comment by mtias** [comment]
Let's close this one as we are a few iterations in on the menu.
