### ISSUE TITLE
Dragging image into image block makes block appear at top of page

### ISSUE THREAD

**Issue by rowroll** [WordPress/gutenberg#26009]
**Describe the bug**
This has happened twice recently, both times goes away when I deactivate Gutenberg.  I think I reactivated it because it auto-updated, and I hoped this had magically gone away.  I was wrong.  I write a blog post, it's mostly image blocks, and I drag each image in from file explorer.  After about 7 images in (11 blocks total) I add an image block, align-center it, drag an image in, and the image block shoots up to the top of the page, landing under the title of the page.  The image is visible.  I muck about a bit, deleting the offending block, the next 1-2 blocks go ok.  Then when I make a new image block, center align it, drag an image in, the menu box for the image block goes wonky, shoots off to the side, and adds an align token that's not the same alignment as the original image.  (See screenshot)   Half the image is visible in the preview of the Styles menu, but not visible in the box itself.  Drag it again and it works ok.  It all feels a bit random.

**To reproduce**
1. Keep adding image boxes, center-aligning them, and dragging an image in, (I add text too) until unstable behavior begins.

**Expected behavior**
Image block should not move when an image is dropped into it, it should stay put.
Image should show when an image is dropped into the image block, the block menu should be on top of the block, and there should not be an extra align visible.  The image should be fully visible in the Styles preview.

**Screenshots**
<img width="960" alt="weirdImageBehavior" src="https://user-images.githubusercontent.com/12249954/95681321-a5565880-0bce-11eb-8c5d-a267da232fda.png">

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
WordPress 5.5.1 running Gridsby theme.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
Has plugin installed
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]
Version 9.1.1

**Desktop (please complete the following information):**
Windows 10 Pro
Chrome 
Version 85.0.4183.121 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
It took a lot of images, but I was able to reproduce this a couple of times.

**Comment by rowroll** [comment]
Whatever this bug is, it's now made it into WordPress proper (WordPress 5.6, Gutenberg Deactivated), and writing posts is an absolute pain.  Dragging and dropping images is essentially a lottery, will it work or will I have to remove, retry, reload?

**Comment by glendaviesnz** [comment]
I couldn't replicate this in WP 6.2 so closing. Feel free to reopen it if you can still replicate it.
