### ISSUE TITLE
Cover text image blurry in iOS Safari

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2600]
The image in the cover text block (try demo) appears blurry and unresized. Sound like an unsupported CSS rule, maybe?

![img_0480](https://user-images.githubusercontent.com/4710635/29860923-7f78116c-8d5f-11e7-92e3-3d1e8c60af64.PNG)

**Comment by samikeijonen** [comment]
Yeah, unfortunately `background-attachment: fixed` have issues on mobile browsers.

**Comment by aduth** [comment]
Code:

https://github.com/WordPress/gutenberg/blob/32647cd2075c8549d39c6982c7742270f584792e/blocks/library/cover-image/style.scss#L21-L23

Can I Use: http://caniuse.com/#feat=background-attachment

Mentions iOS Safari does not support `background-attachment: fixed`, but separately mentions in Known Issues a conflict (with workaround) between `background-attachment: fixed` and `background-size: cover`.

Could be worth exploring workaround: https://stackoverflow.com/questions/21476380/background-size-on-ios

**Comment by iseulde** [comment]
This seems to be fixed now... Though I can immediately find a confirmation on the internet. Works fine on iOS 10.3.3.

**Comment by iseulde** [comment]
Also works perfectly on the iPhone. Checked out https://github.com/WordPress/gutenberg/pull/2860 because some sources mention an issue with smooth scrolling, but it works fine with that too. The image just doesn't scroll smoothly, it's a bit choppy...

Closing for now then.

**Comment by laurelfulford** [comment]
I'm currently seeing this issue on my iPhone 6 (iOS 11.2), when the background is set to fixed. Not sure if it's a regression in iOS or something else.

For comparison:

Here's a cover block, no fixed background:

![Without](https://cldup.com/AvN0NuF-ym-3000x3000.png)

And a cover block, using the exact same photo, with a fixed background:

![With](https://cldup.com/S82PG6qv2a-3000x3000.png)
