### ISSUE TITLE
Template Part Not Found message from gutenberg_render_block_core_template_part() on Windows server

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#26010]
**Describe the bug**
I'm following the instructions to develop a theme for Full Site Editing at
https://developer.wordpress.org/block-editor/tutorials/block-based-themes/
and received the following message "Template Part Not Found" on my Windows server.

I discovered that `validate_file()` returns 2 for a fully qualified file e.g.
`C:/apache/htdocs/wp56/wp-content/themes/fizzie/block-template-parts/header.html`.

gutenberg_render_block_core_template_part() doesn't cater for this value.
So the function fails to load the template part.

**To reproduce**
1. On a Windows server
2. Follow instructions to develop a theme for Full Site Editing
3. View some content. e.g. Visit site.
4. See the `Template Part Not Found` as part of the output.

**Expected behavior**
Code should be able to load template part files in a Windows server environment.

I suggest either change the logic to support a return value of 2 from validate_file().
or don't call validate_file() and validate the value for the `slug` attribute.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/95687042-24608680-0bf9-11eb-8d5d-a724e1d6b341.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg 5.5.1 with Full Site Editing selected.
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

I've implemented a local fix
```
$valid = validate_file( $template_part_file_path );
if ( ( 0 === $valid || 2 == $valid )  && file_exists( $template_part_file_path ) ) {
	$content = file_get_contents( $template_part_file_path );
}
```

**Comment by annezazu** [comment]
@kjellr might this be something you can dig into?

**Comment by kjellr** [comment]
It sounds like this is not so much an issue with the tutorial (or a block based theme itself), but instead its an issue with how Gutenberg determines that templates are valid. I'd bet that @youknowriad may have a better idea how this should work.

**Comment by youknowriad** [comment]
@bobbingwide I wonder if we can just remove that "validate_file" call entirely. I'm not really sure what was its original purpose.

**Comment by bobbingwide** [comment]
> I wonder if we can just remove that "validate_file" call entirely. I'm not really sure what was its original purpose.

I believe the file is validated for security purposes. If not validated then the file could be loaded up from anywhere. 
Maybe we can just check that the returned value is not 1 - i.e. directory traversal.

**Comment by bobbingwide** [comment]
Question: Should it be possible for a child theme to use template parts from the parent theme? If so, how?

**Comment by youknowriad** [comment]
@bobbingwide I think child themes is not something we looked at yet, remains to be seen if/how that abstraction translate to FSE themes.

**Comment by bobbingwide** [comment]
> Or perform the validate_file() against $attributes['slug'].

Just to let you know that I'm currently using this as my workaround and problem determination aid.
```
			if ( 0 === validate_file( $attributes['slug'] ) && file_exists( $template_part_file_path ) ) {
				$content = file_get_contents( $template_part_file_path );
			}
		}
	}

	if ( is_null( $content ) ) {
		$html = 'Template Part Not Found: ' . $attributes['slug'];
		$html .= 'Theme: ' . $attributes['theme'];
		$html .=  empty( $attributes['postId'] ) ? '' : 'PostId: ' . $attributes['postId'];
		return $html;
	}
```

I've encountered situations where each of these values can be wrong. See the comments in https://github.com/bobbingwide/fizzie/issues/1
