### ISSUE TITLE
How to use getMediaItems() with withSelect() to retrieve selected images using MediaUpload

### ISSUE THREAD

**Issue by davy440** [WordPress/gutenberg#26027]
Hello everyone,
Basically, I am trying to create an image uploader block where multiple images can be uploaded using the gallery uploader. I referred to the following article-

[https://awhitepixel.com/blog/wordpress-gutenberg-add-image-select-custom-block/](https://awhitepixel.com/blog/wordpress-gutenberg-add-image-select-custom-block/)

The whole thing is explained very nicely and has made life easier. Now, I want to extend this functionality for a multiple image uploader. Currently, only single image support is there. I managed to modify the <MediaUpload> component to support gallery modal by modifying the `gallery` prop.

The only issue I'm facing is with the higher order component `withSelect()`. I tried to modify it by replacing `getMedia()` by `getMediaItems()` but on selecting multiple images from the Gallery module, the media prop gets filled 10 latest images instead of the selected ones. Here, is my code for `withSelect()`-

```
edit: withSelect((select, props) => {
		return { media: props.attributes.mediaId.length > 0 ? select('core').getMediaItems(props.attributes.mediaId) : undefined };
	})(BlockEdit)
```

Now, I am asking is what to do with the getMediaItems() in order to make it work for Galleries. I have attached the complete code for blocks with the request.

Any help in the right direction is highly appreciated!

[gallery.zip](https://github.com/WordPress/gutenberg/files/5365245/gallery.zip)

Thanks

**Comment by talldan** [comment]
@davy440 The plural functions work slightly differently. For singular items I think being able to pass ids directly is just a convenience shorthand.

You can use pass an object to entities like getMediaItems with any of the rest parameters defined in the docs:
https://developer.wordpress.org/rest-api/reference/media/

So for fetching multiple specific media items you can use the `include` property:
```js
select( 'core').getMediaItems( { include: [ 1623, 1617 ] } )
```

Just note that for multiple items you'll have to handle paging (`per_page`, `page` properties), I think the default is 10 items per page.

**Comment by davy440** [comment]
Worked Perfectly! And the best thing, prop is an array. So, iterating through it is easy compared to objects. Objects are a pain to iterate over. Any easy method I'm not aware of to iterate over object will be highly appreciated!
