### ISSUE TITLE
Error on my site

### ISSUE THREAD

**Issue by CarolynVTW** [WordPress/gutenberg#26032]
*Use of undefined constant LIBXML_HTML_NODEFDTD - assumed 'LIBXML_HTML_NODEFDTD' (this will throw an Error in a future version of PHP) in /var/www/wp-content/plugins/gutenberg/lib/block-supports/index.php on line 66

Warning: A non-numeric value encountered in /var/www/wp-content/plugins/gutenberg/lib/block-supports/index.php on line 66

**Comment by talldan** [comment]
This was reported previously -  #25122, so I'll close this issue as a duplicate.
