### ISSUE TITLE
Aligning paragraphs errors in iOS Safari 

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2603]
I click on a paragraph in the demo and align right:

![img_0484](https://user-images.githubusercontent.com/4710635/29862200-cd28bcb4-8d63-11e7-9940-21790e8ae38b.PNG)

**Comment by aduth** [comment]
[`TypeError: Attempted to assign to readonly property.`](https://github.com/WordPress/gutenberg/blob/32647cd2075c8549d39c6982c7742270f584792e/blocks/editable/tinymce.js#L35)

cc @youknowriad re df1b993046c99f1a7ddd30a1053565585609e100

**Comment by aduth** [comment]
- First thought: Iterating `element.style` keys and resetting.
   - Downside: This iterates _all_ keys, not just assigned values, perhaps excessive
- Second thought: Assign the [CSS `all` property](https://www.w3.org/TR/css3-cascade/#all-shorthand)
   - Downside: http://caniuse.com/#feat=css-all
- Third thought: Iterate style of `this.props` (the "previous" props) and unset them specifically before applying new incoming styles
   - This is probably a good direction
