### ISSUE TITLE
Social Icons: Browse all option is confusing

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#26046]
I wasn't sure if this would be a feature request or a bug, so feel free to re-categorize.

**Describe the bug**
When browsing all the social media icons available via Social Icons block, there's a "Browse all" button at the bottom of the list. Clicking the button opens the "Insert block/pattern", which does not make sense in the context of browsing available social media icons.

**To reproduce**
1. Create a new post or a page and add _Social Icons_ block.
2. Click on the **+ button** within the block. Scroll through the list of available icons to the **Browse all** button at the bottom.
3. Click the **Browse all** button. It will open left sidebar with the list of all available blocks, **not a full list of available social media icons**, which I expected while being within the context of Social Icons block.
4. At the bottom of that sidebar is a list of available embeds, and I got a little confused there, whether those are the social media icons I was looking for.

**Expected behavior**
Clicking the **+ button** to add more social media icons opens a modal with a pretty long list of services. If this is a full list of available icons, maybe the **Browse all** button is not needed at all? Or if there are in fact more icons available, I would expect the **Browse all** button to open a list of those specifically.

**Screenshots**
![EGT63K9MBm](https://user-images.githubusercontent.com/4550351/95804993-00fc1f80-0d50-11eb-92e4-f2b8ea3f4660.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1. Gutenberg default

**Comment by talldan** [comment]
This was previously reported in #25474, so I'll close as a duplicate.

It's effectively the same issue as #24403, that when 'Browse all' is clicked, the menu that opens will insert blocks after Social Links instead of inside Social Links.
