### ISSUE TITLE
Enhance Theme Compatibility With Widget Areas

### ISSUE THREAD

**Issue by wball1** [WordPress/gutenberg#26040]
**Describe the bug**
**After the Gutenburg widget blocks updated, I can no longer edit or preview my widgets under each block.**

**Screenshots**
![image](https://user-images.githubusercontent.com/14005633/95787169-d0ec4800-0c8d-11eb-8b90-e222052263b0.png)

**Editor version (please complete the following information):**
- WordPress version: **I've updated to WordPress 5.5.1 running Refined Theme theme. Using Genesis 3.3.3.**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] **I believe the Gutenberg plugin has been installed**
- If the Gutenberg plugin is installed, which version is it? **Version 9.1.1**

**Desktop (please complete the following information):**
 - OS: PC
 - Browser Chrome
 - Version 

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
Hi @wball1 To help us reproduce the issue, do you know what widgets you had active? Also any particular plugins you use for widgets?

**Comment by wball1** [comment]
I don't know the names of all widgets, however my home page template is made up with widgets. 
![image](https://user-images.githubusercontent.com/14005633/95901087-abbc1000-0d47-11eb-9577-52632374f198.png)

Have the Widget Importer & Exporter plugin that was added with my Refined Theme I believe.

**Comment by paaljoachim** [comment]
As I have an account at StudioPress I downloaded Genesis 3.3.3 and Refined Pro theme.
Installed it locally.
In Chrome.
Desktop Server.
Use WP 5.5.1
Gutenberg plugin 9.1.1 installed.

This is what I see in the customizer (just to compare to the Widget screen)

![Screen Shot 2020-10-14 at 01 00 37](https://user-images.githubusercontent.com/5323259/95924867-b367cd00-0db8-11eb-80f9-aae2fa4a170f.png)

In the Widget screen I see a blank Inserter panel.

![Screen Shot 2020-10-14 at 01 03 44](https://user-images.githubusercontent.com/5323259/95925075-2cffbb00-0db9-11eb-8a79-e00ae3714155.png)

I see no Widget areas. 
![Screen Shot 2020-10-14 at 01 02 12](https://user-images.githubusercontent.com/5323259/95924967-f164f100-0db8-11eb-9189-c031a3ccc33a.png)

I did notice this error when right clicking inside the widget screen and selecting Inspect -> Console
(@wball1 see if you can follow the same steps as I am doing so we can get the error message you get in the Console screen, as it might be a little different from what I have.)


Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at v (index.js?ver=7533721b7d38f164f2c33401c3fd69be:1)
    at b (index.js?ver=7533721b7d38f164f2c33401c3fd69be:1)
    at p (index.js?ver=7533721b7d38f164f2c33401c3fd69be:1)
    at Fr (index.js?ver=d87002844aa02dc6b9ba6eac75ea77e2:13)
    at N (index.js?ver=467fe5c057c7af899bac37ad7f0f60a7:1)
    at index.js?ver=467fe5c057c7af899bac37ad7f0f60a7:1
    at tryCatch (wp-polyfill.min.js?ver=7.4.4:1)
    at Generator.invoke [as _invoke] (wp-polyfill.min.js?ver=7.4.4:1)
    at Generator.t.<computed> [as next] (wp-polyfill.min.js?ver=7.4.4:1)
    at index.js?ver=f0c7423d9d652387f8468f6108a9930e:1

**Comment by wball1** [comment]
This is what mine looks like. Is this the correct view? Sorry I don't know much about this 

![image](https://user-images.githubusercontent.com/14005633/95926026-1b45f580-0d70-11eb-8339-abae03db1839.png)

**Comment by wball1** [comment]
Errors From the beginning

![image](https://user-images.githubusercontent.com/14005633/95926143-62cc8180-0d70-11eb-8b58-62e2f69cfff3.png)

**Comment by annezazu** [comment]
I was able to replicate with Gutenberg 9.1.1 and WordPress 5.5.2 using the "Classic editor" block and Calendar block.

**Comment by wball1** [comment]
Is there a resolution for this problem. I'm unable to edit my website front page because of this! Thanks

**Comment by paaljoachim** [comment]
Hey @wball1 I believe one temporary work-around is to while logged in go to the frontend.
Select the site name -> Widgets.

![Screen Shot 2020-10-18 at 15 09 24](https://user-images.githubusercontent.com/5323259/96368393-f2e53f00-1153-11eb-8f13-ee3c86a1733c.png)

One then enters the old widget screen.

**Comment by wball1** [comment]
How do I view this screen? How can I view Local Dev Site to click Widgets?

![image](https://user-images.githubusercontent.com/14005633/96385445-db548900-1148-11eb-974f-37414899d650.png)

**Comment by wball1** [comment]
This is how I get to my widget page now and it takes me to the problem page.

![image](https://user-images.githubusercontent.com/14005633/96385701-6f732000-114a-11eb-9e23-8b9b94eee324.png)

**Comment by paaljoachim** [comment]
"Local dev site" is just the name of a test site I use. It looks like you are using a wordpress.com site. In general I use download WordPress from wordpress.org and create a freestanding site outside of wordpress.com. I did not even know that wordpress.com uses the new widget screen.

Appearance -> Widgets will take you to the new widgets screen. A better work around would be to add code to the functions file.

**Disabling the new Widgets Screen**
Users of the plugin who do not want to test the new Widgets Screen or who require the old screen, can use a simple filter to disable the new Widgets Screen. Just place this in your theme’s functions.php file:

`add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );`

https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/

Hopefully you will be able to add the code to disable the new widget screen.

**Comment by wball1** [comment]
I just click on WP Admin tab to get to my wordpress.org site  
Do I place this filter at the beginning of the theme's functions.php file? I don't want to mess anything up! :) Yes I just want to go back to the old way of accessing my widgets!

**Comment by paaljoachim** [comment]
I would likely do something like this, and add a comment first.
/* The following code brings back the original Widgets screen. */
add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );

Then add it to the end of the Refined Pro theme functions file. Add the code and save the file. Then test to see that it brings back the original widget screen.

**Comment by wball1** [comment]
*/add_filter( 'gutenberg_use_widgets_block_editor', '__return_false', 100 );*/

Do I add this above to the end of it? 
What do you mean by adding a comment /* here is the code */

**Comment by wball1** [comment]
I finally got it to work! Thanks so much for your help. I really appreciate it.

**Comment by dreamwhisper** [comment]
I've been doing some testing on this screen and there appears to be many widgets that cause this issue.

For example, one that uses a `wp-color-picker` results in `wpColorPicker is not a function`. Example plugin used as basis: https://core.trac.wordpress.org/attachment/ticket/25809/color-picker-widget.php

**Comment by paaljoachim** [comment]
@wball1 I think we need to leave this issue open as a few developers will need to dig into it and figure out what is going on.

**Comment by wball1** [comment]
Ok no problem! I wasn't aware.

**Comment by draganescu** [comment]
I edited the title of this issue. I thing that maybe it could be split into multiple things. In either case it's a prime example of back compat work that still is required.

**Comment by noisysocks** [comment]
How do I reproduce this bug? I don't have access to the Refined Pro theme.

**Comment by paaljoachim** [comment]
I reached out to StudioPress so that they could take a closer look at this issue.

**Comment by paaljoachim** [comment]
Resting using WordPress 5.7.2

Gutenberg plugin 10.7.1
Genesis 3.3.3 and the child theme Refined theme.

Going to Widgets:
(The Macbook Pro fan turned on and I am seeing the status bottom left area in Chrome is saying Waiting for 2121.dev.cc over and over again. Going in a loop. Closing the test screen/tab when I finished testing the fan quieted down again.)
```

Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.7.2:2)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Function.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.<anonymous> (heartbeat.min.js?ver=5.7.2:2)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
(anonymous) @ wp-auth-check.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
c @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
fireWith @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
l @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
load (async)
send @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
s.ajax.s.ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:5
l @ heartbeat.min.js?ver=5.7.2:2
d @ heartbeat.min.js?ver=5.7.2:2
v @ heartbeat.min.js?ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
wp-auth-check.min.js?ver=5.7.2:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.7.2:2)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Function.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.<anonymous> (heartbeat.min.js?ver=5.7.2:2)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
(anonymous) @ wp-auth-check.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
c @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
fireWith @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
l @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
load (async)
send @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
s.ajax.s.ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:5
l @ heartbeat.min.js?ver=5.7.2:2
d @ heartbeat.min.js?ver=5.7.2:2
v @ heartbeat.min.js?ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
wp-auth-check.min.js?ver=5.7.2:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.7.2:2)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Function.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.<anonymous> (heartbeat.min.js?ver=5.7.2:2)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
(anonymous) @ wp-auth-check.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
c @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
fireWith @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
l @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
load (async)
send @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
s.ajax.s.ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:5
l @ heartbeat.min.js?ver=5.7.2:2
d @ heartbeat.min.js?ver=5.7.2:2
v @ heartbeat.min.js?ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
wp-auth-check.min.js?ver=5.7.2:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.7.2:2)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Function.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.<anonymous> (heartbeat.min.js?ver=5.7.2:2)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
(anonymous) @ wp-auth-check.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
each @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
trigger @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
c @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
fireWith @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
l @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
load (async)
send @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
s.ajax.s.ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:5
l @ heartbeat.min.js?ver=5.7.2:2
d @ heartbeat.min.js?ver=5.7.2:2
v @ heartbeat.min.js?ver=5.7.2:2
(anonymous) @ heartbeat.min.js?ver=5.7.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
v.handle @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2
wp-auth-check.min.js?ver=5.7.2:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.7.2:2)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.v.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at HTMLDocument.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Function.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.each (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at s.fn.init.trigger (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)
    at Object.<anonymous> (heartbeat.min.js?ver=5.7.2:2)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7.2:2)


```

![Screen Shot 2021-05-31 at 12 04 42](https://user-images.githubusercontent.com/5323259/120177757-0c318c00-c209-11eb-8bab-c15358fa51de.png)

I went ahead and added a post to the Facebook group for Genesis WordPress. Mentioning this issue as well as testing the widget editor for WP 5.8.

**Comment by draganescu** [comment]
To get the open source (free) Genesis Framework you have to register with an email. However, to get Refined Pro, it's impossible? The Link to refined pro from the [Genesis Themes](https://www.studiopress.com/themes/) [page](https://www.studiopress.com/themes/refined/) is a [404 page](https://shop.restored316designs.com/product/refined-feminine-wordpress-theme/) from Restored 316.

It looks like this version of Refined (based on Genesis) is [not active/supported anymore](https://shop.restored316designs.com/feminine-wordpress-themes/) as there is a [Kadence based Refined Pro](https://shop.restored316designs.com/product/refined-theme-kadence/) theme now.

@paaljoachim did you ever hear back on the FB support forum or the StudioPress contact?

**Comment by draganescu** [comment]
Testing with the Genesis framework alone:

- the widget editors work
- there are some Notices and Warnings that show up b/c of `WP_DEBUG`:

<img width="752" alt="Screen Shot 2021-06-16 at 12 56 42" src="https://user-images.githubusercontent.com/107534/122199147-78b3b880-cea2-11eb-92b7-dfc13ae87291.png">

These seem unrelated to the Widgets editor or the rest API widget endpoints.

**Comment by dreamwhisper** [comment]
I work with the Genesis team and was originally able to replicate the reported issue independent of Genesis/Refined by activating various plugins.

The issue no longer displays `This block has encountered an error and cannot be previewed.` for all widgets, but there are some script errors associated. From the OP's screenshots at the time, I installed and tested https://wordpress.org/plugins/social-proof-testimonials-slider/ with Twenty Twenty-One and found the same error for all widgets so the issue was independent of the theme.

As I [mentioned](https://github.com/WordPress/gutenberg/issues/26040#issuecomment-712166088) above, this [sample color picker widget](https://core.trac.wordpress.org/attachment/ticket/25809/color-picker-widget.php) also caused `This block has encountered an error and cannot be previewed.` for all widgets. I apologize for not adding more detail at the time.

The two plugins above now result in a repeated script error on the widgets screen in place of `This block has encountered an error and cannot be previewed.`

![Screen Shot 2021-06-16 at 1 39 53 PM](https://user-images.githubusercontent.com/1271053/122267085-7bb1a780-cea8-11eb-8fc5-20520de26fbb.png)

![Screen Shot 2021-06-16 at 1 40 34 PM](https://user-images.githubusercontent.com/1271053/122267063-77858a00-cea8-11eb-90ab-78c476b0925b.png)

Our team will be reviewing options for [Simple Social Icons plugin](https://wordpress.org/plugins/simple-social-icons/) next sprint as it uses the color picker in the example widget above and has 200k installs.

**Comment by dreamwhisper** [comment]
Also adding that the above tests were with the Gutenberg Version 10.8.1 on WP 5.7.2. The color picker appears to be working in WP 5.8 Beta 2.

**Comment by draganescu** [comment]
@dreamwhisper hi! I didn't realize you actively work on this. Thank you!

**Comment by noisysocks** [comment]
I tested the color picker widget linked to above and everything seems okay. Running latest `trunk`.

https://user-images.githubusercontent.com/612155/151302252-9676bdb0-1a27-46c7-8282-82dd3c025b62.mp4
