### ISSUE TITLE
1.0.0 "Read more" button via functions.php stopped working after update

### ISSUE THREAD

**Issue by carstenheisterkamp** [WordPress/gutenberg#2605]
After updating to 1.0.0 my "read more" excerpt button that is added via functions php vanished. 
It only happens to the posts published with 1.0.0 under the older posts it is still present.

I use it as described in 

> https://codex.wordpress.org/Excerpt

```
function new_excerpt_more( $more ) {
	return ' <a class="read-more" href="'. get_permalink( get_the_ID() ) . '">' . __('Read More', 'your-text-domain') . '</a>';
}
add_filter( 'excerpt_more', 'new_excerpt_more' );
```

Steps to reproduce
- add above to functions.php
- check old posts if read more is available
- update to 1.0.0 
- create new post
- add excerpt to the excerpt section
- publish
- check if read more link

**Comment by aduth** [comment]
I'm having trouble reproducing the issue, and will need a few more details:

- Which theme are you using?
- What pages are you looking at where you expect to see the excerpt and Read More button?

**Comment by carstenheisterkamp** [comment]
It is a minimal custom wordpress theme to test. 

I am using  `the_excerpt()` in the loop on the frontpage to display the latest posts with the post thumbnail and an excerpt of the content. The wordpress reading settings are set to "summary".

When I remove the manual excerpt, the "read more" link is displayed again. So the automatic excerpt works and uses the first 55 words of the posts text for the excerpt on the frontpage. 
I assumed, that it automatically uses the manual excerpt, when I fill in the excerpt. 

So  either the bug sits in front of the computer (and can be closed) and I am misunderstanding the function or the mechanism is not working correctly.

**Comment by justintadlock** [comment]
`excerpt_more` is not fired when displaying a manual excerpt.  It's only fired for automated excerpts.

**Comment by karmatosed** [comment]
I can't replicate this and think it's potentially something to do with the theme being used over Gutenberg. For now, closing this.
