### ISSUE TITLE
Site Editor: Navigation Drawer inconsistent focus shapes

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#26069]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/191598/95891855-a5cc2c00-0d53-11eb-8d04-ed845acba0d3.png">

The shape of the "< Dashboard" button is different from the other buttons, and causes the `;focus` state to be different. The back button should be rounded and having some left/right margins. Also, I believe the horizontal line below the button is unnecessary. Here's how I'd expect it to look:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/191598/95892384-779b1c00-0d54-11eb-8052-0b78f2093cf5.png">

**Comment by jordesign** [comment]
With the updated Back/Dashboard/Design button in the Site Editor - this errant style is no longer evident.
