### ISSUE TITLE
Post Author selector: use native `<select>` element for a small number of authors.

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#26077]
**Is your feature request related to a problem? Please describe.**
In https://github.com/WordPress/gutenberg/pull/23237 we improved the post author selector by adding an accessible autocomplete searchable selector, building on the `<ComboboxControl>` component. _This works especially well for a large number of possible authors when a select becomes unwieldy._ 

On the other hand, when a site has only a small number of potential post authors, a native select element similar to [what we had previously](https://github.com/WordPress/gutenberg/pull/23237/files#diff-e7e4d9714c2a071d3f0cb931f1be6e8e178ea48b683e23a522375159553b9787L36-L50) would be better for users: simpler, even more consistently accessible, and faster. Worth noting that when sites have only one author, we don't show the selector at all.

**Describe the solution you'd like**
First: pick the number of users we want have be the "cutoff" when we start using the searchable select element vs the simpler native select element? Is it when we have 20 users, or 50 or more? Some design feedback would be useful here, and ideally some user studies, accessibility guidelines or other data. I couldn't find much in my brief search.

For sites that have [CUTOFF] or fewer fewer potential authors, show the same `select` element we were showing previously. Only show the new `ComboboxControl` when sites have more than [CUTOFF] authors.

As mentioned in https://github.com/WordPress/gutenberg/pull/23237#issuecomment-694306451,  https://github.com/WordPress/gutenberg/pull/25267#issuecomment-703665207.

**Questions**
Should [CUTOFF] be developer controllable, and if so, how?

**Comment by adamsilverstein** [comment]
@youknowriad when working on this I have noticed that chrome tries to autofill the input field which interferes visually with the search feature of the ComboboxControl:

![image](https://user-images.githubusercontent.com/2676022/97014011-018e7600-1507-11eb-983c-acfa80b6ab5f.png)

I think we can fix that by adding `autocomplete="off"` to the input field. What do you think?

**Comment by youknowriad** [comment]
yes, it makes sense 👍

**Comment by adamsilverstein** [comment]
> yes, it makes sense 👍

Will address in a separate PR.

**Comment by adamsilverstein** [comment]
@youknowriad  Took a pass at addressing this in https://github.com/WordPress/gutenberg/pull/26426 - the code is slightly complicated by the fact that we need to make sure we don't display a select when the combobox result count falls below the threshold.

**Comment by adamsilverstein** [comment]
@youknowriad I addressed the autocomplete issue in https://github.com/WordPress/gutenberg/pull/26427.
