### ISSUE TITLE
Widget screen Undo button is active before any actions are taken

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26073]
**Describe the bug**
Undo button is active before any actions are taken

**To reproduce**
1. Go to widgets screen
2. Click on undo button
3. There is nothing to be undone

**Expected behavior**
Undo button should become active only once an action has been taken.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- If the Gutenberg plugin is installed, which version is it? 9.1.1

**Additional context**
Originally reported [here](https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40042)

**Comment by noisysocks** [comment]
Hey @kevin940726, are you still looking into this?

**Comment by tellthemachines** [comment]
I can no longer reproduce this in latest trunk, can anyone else?

**Comment by kevin940726** [comment]
Nope, can't reproduce it anymore.
