### ISSUE TITLE
Shortcode is hidden

### ISSUE THREAD

**Issue by benecia1111** [WordPress/gutenberg#26075]
Search first! Your issue may have already been reported.

For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/.

You may also ask for technical support at https://wordpress.stackexchange.com/.

Please make sure you have checked the Handbook at https://wordpress.org/gutenberg/handbook before asking your question.

Thank you!

**Comment by talldan** [comment]
@benecia1111 Would you be able to provide information on the issue you're having?

In the meantime I'll close this issue as there's nothing we can do.
