### ISSUE TITLE
Feature Request: Allow Pages and Posts to be 'geotagged' with a location

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#26083]
**Is your feature request related to a problem? Please describe.**
Until recently WordPress.com made it  possible to 'Geotag' posts and pages  so they would have a location associated with them:
https://wordpress.com/support/geotagging/

> The location is added to your post or page in various machine-readable formats: geo microformat, geo.postion meta tag and ICBM meta tags, and GeoRSS and W3C geodata in feeds.

It's also useful metadata that themes and plugins could potentially hook into

**Describe the solution you'd like**
It would be great to add an option in the Document settings to allow users to select/pin a location for the page/post. 

**Describe alternatives you've considered**
There appear to be a few plugins related to similar ideas:

* https://wordpress.org/plugins/simple-location/
* https://wordpress.org/plugins/geo-my-wp/

**Comment by noisysocks** [comment]
It's a neat feature but feels like plugin territory to me. Why should Core add this functionality?

**Comment by aristath** [comment]
I agree, this does feel like plugin territory...
It should be possible to add a block that saves post-meta instead of content, and use that to store geolocation data, but I haven't seen such a block in the w.org repo 🤔

**Comment by noisysocks** [comment]
I'll close this out as `wontfix` for now. It would be a cool block to see in the block directory!
