### ISSUE TITLE
Correct column widths

### ISSUE THREAD

**Issue by lukewalczak** [WordPress/gutenberg#26096]
**Describe the bug**
After using `UnitControls` in `Columns introduced in the [PR](https://github.com/WordPress/gutenberg/pull/24711) there is a regression in distributing columns width.

Basically some functions such as [hasExplicitColumnWidths](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L99) or [toWidthPrecision](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L14) from `columns/utils.js` cannot work since there is a check `Number.isFinite(value)`. Value always comes with the unit, so the result is `false`. Unfortunately it has an effect on columns width distribution (_please notice that on presented gif, the third column width is different_)

before PR | after PR
--- | ---
![before_pr](https://user-images.githubusercontent.com/22746080/95740021-1576e400-0c8c-11eb-881c-5761fb3a7fe0.gif) | ![after_pr](https://user-images.githubusercontent.com/22746080/95740026-1871d480-0c8c-11eb-8192-4b8d73410b3b.gif)

Function called `getTotalColumnsWidth` used within `getRedistributedColumnWidths` sums the width attribute of the individual column defined in % (correct me if I'm wrong). With the approach where width can be defined in different units, function mentioned above should take into account somehow.

**To reproduce**
1. Open a post
2. Add columns block
3. Choose variation `30/70`
4. Add third column
5. Observe width is not distributed properly

**Expected behavior**

Width should be distributed properly as before introducing the `UnitControls`

**Screenshots**

Added above

**Editor version (please complete the following information):**
- Gutenberg 9.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by aristath** [comment]
I assume this one can be closed now that https://github.com/WordPress/gutenberg/pull/26095 was merged?
