### ISSUE TITLE
Remove WP_REST_Widget_Utils_Controller class and form-renderer method

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#26092]
**Describe the solution you'd like**
Remove `WP_REST_Widget_Utils_Controller` and `get_widget_form` method from `WP_REST_Widget_Types_Controller`, as rendering form is handled by the widget controller. 

**Describe alternatives you've considered**

**Comment by spacedmonkey** [comment]
Current code to render lives in the three places. 

- Widget utils endpoints
- Widget type 
- Widgets endpoint. 

It needs to decide the best place for this code to live.

**Comment by TimothyBJacobs** [comment]
The widget utils endpoint should be removed, it should stay in the other two places. The client needs to be updated to reference the widget type endpoint.
