### ISSUE TITLE
File block: Add color selector

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#26094]
**Is your feature request related to a problem? Please describe.**

While various blocks allow selecting both the font and the background color, the file block does not have that option yet.

**Describe the solution you'd like**

To have consistency throughout all blocks, it would be good to add the color selector.

**Describe alternatives you've considered**

n/a

**Comment by annezazu** [comment]
@nielslange thanks for reporting this. This is eventually the goal with Global Styles and has already been reported here: https://github.com/WordPress/gutenberg/issues/18989 I'm going to close this out as a result :) If you believe it should be reopened, let me know!

**Comment by nielslange** [comment]
Thanks for closing this issue, @annezazu. I haven't noticed #18989 and having this issue twice in the backlog makes no sense.
