### ISSUE TITLE
Widgets Feedback

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#26101]
Collecting some feedback on the widgets screen:

- The page title "Widgets" seems disproportionately sized.
- What's the value of having this "widgets area" panel? If it had more helpful text explaining things I could see it being more useful.

![image](https://user-images.githubusercontent.com/548849/95979169-83054a80-0e1b-11eb-8dac-f2830337baf0.png)

- The placeholder text could be customized a bit around how all blocks are now available as widgets "Insert any block into widget areas"...

![image](https://user-images.githubusercontent.com/548849/95979350-c8c21300-0e1b-11eb-9c3f-70b666a9b724.png)

- It feels like "inactive widgets" could be part of the inserter (as a tab) instead of a fake widget area.
- Is there value in having the widget area container selectable when it doesn't seem to have attributes?
- It might be nice to include a block count next to the widget area title.
- Unclear why all block categories disappear in favor of a single "Widget Area" group in the inserter when no widget area is in focus.
- What's the status of patterns in the inserter?

**Comment by talldan** [comment]
> What's the value of having this "widgets area" panel? If it had more helpful text explaining things I could see it being more useful.
It comes from this issue (https://github.com/WordPress/gutenberg/issues/25190) and PR (https://github.com/WordPress/gutenberg/pull/25943), looks like a way to get the widget area (sidebar) description to show.

> It feels like "inactive widgets" could be part of the inserter (as a tab) instead of a fake widget area.

Yeah, I think there's some improvements that could be made here too. An option in the more menu to make a widget inactive without having to drag it could be nice too.

> Is there value in having the widget area container selectable when it doesn't seem to have attributes?

Widget areas being blocks has been somewhat problematic in some ways, helpful in others.

The area being part of the tab order isn't great, inserting from the library had to be hacked a bit, and the parent selector isn't useful for its children. Making it a 'passthrough' block (and actually implementing this feature) seems like an option. One thing I'm unsure about is how this would work in List View. Maybe clicking the Widget Area selects the first nested block?

> Unclear why all block categories disappear in favor of a single "Widget Area" group in the inserter when no widget area is in focus.

Feels like a bug!

> What's the status of patterns in the inserter?

This probably needs to be captured as an enhancement and given a priority. I don't think I've seen an issue for it.

**Comment by bph** [comment]
@talldan @mtias I just created the feature request to allow bock patterns in the widget screen. https://github.com/WordPress/gutenberg/issues/26170

**Comment by talldan** [comment]
Thanks @bph! I've added those tickets to the project.

**Comment by mtias** [comment]
I'll close this now because these long-form issues are not very useful to remain open. Feels like the biggest item is the use of blocks for the widget area containers, which needs to more work.
