### ISSUE TITLE
[RNMobile] Post content changes not persisited when switching from HTML Mode to Visual

### ISSUE THREAD

**Issue by Tug** [WordPress/gutenberg#26109]
**Describe the bug**
In the native demo app (tested on Android), switching from HTML mode to Visual does not persist changes. This is not occurring in WPAndroid.

**To reproduce**
Boot the demo app on android: `npm run native android`
1. Shake your device to open the debugger menu and press "HTML Mode"
2. Change some content inside the HTML (make sure it's valid)
3. Open the debugger menu again and switch back to visual
4. Notice your changes were discarded

**Expected behavior**
Expecting to see the changes in the markup be persisted and applied in the visual mode

**Comment by kathrynwp** [comment]
@hypest Hi, is this still applicable and on the radar to be fixed? If not, I'll go ahead and close as stale/not planned. Thanks!

**Comment by hypest** [comment]
👋 @kathrynwp! Thanks for the ping! I'm actually not directly working on the Gutenberg/gutenberg-mobile at this stage, please feel free to ping @fluiddot instead. Sorry for the forward 🙂

**Comment by dcalhoun** [comment]
Hey @kathrynwp. 👋🏻 I was unable to reproduce this issue on the latest `trunk`. Closing this, but feel free to re-open if needed.

**Comment by kathrynwp** [comment]
Much appreciated, @dcalhoun!
