### ISSUE TITLE
Empty paragraphs show up as empty blocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#26110]
**Describe the bug**
If a user leaves an empty line in the block editor that is an empty paragraph block. This empty paragraph block will show up as an empty BlockWidget in the old editor and the customizer.

**To reproduce**
1. Have the Gutenberg plugin installed
2. Go to Appearance > Widgets
3. Add some blocks and widgets
4. Add an empty paragraph block
5. Save
6. Go to Appearance > Customize

**Expected behavior**
I'd expect empty space to be trimmed, or at least not to show up as an empty item.

**Screenshots**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/107534/95998739-d8525380-0e3d-11eb-981d-925478ed3db3.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/107534/95998751-db4d4400-0e3d-11eb-9452-0ee7e0e094e9.png">

**Comment by talldan** [comment]
@draganescu The way this is phrased makes it sound like a solution for the existing issue #26072. That one already has some discussion. Can we combine them?

**Comment by mapk** [comment]
I agree. It appears that if we implement the solution provided in #26072, we should resolve this issue here. This is because in #26072, the Inserter button requires intentional decision to add a Paragraph block.
