### ISSUE TITLE
Removing width from .wp-block-cover__inner-container may cause contents to shrink

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#26126]
**Describe the bug**

Removing the calculated width from `.wp-block-cover__inner-container` as discussed [here](https://github.com/WordPress/gutenberg/pull/24523#discussion_r484325314), can cause the contents of the container to change width compared to the original.

**To reproduce**
1. Activate Twenty Nineteen with WP 5.5.1
2. Add a full-width cover block.
3. Inside the cover block, add a columns block and set it to 2 columns, then add a paragraph to each.
4. Note the width of the block. It should match front end to editor.
5. Update to 5.6-alpha or Gutenberg 9.9.1.
6. Note the width of the content on the front end. It no longer matches the width in the editor. It also has shrunk compared to the original

**Expected behavior**
Width of content will not change when updating WordPress from 5.5.x to 5.6.

**Screenshots**

Original:

<img width="1486" alt="Screen Shot 2020-10-14 at 3 48 59 PM" src="https://user-images.githubusercontent.com/1271053/96038269-e18af280-0e34-11eb-8399-c4d66597b88d.png">

New:

<img width="1488" alt="Screen Shot 2020-10-14 at 3 48 42 PM" src="https://user-images.githubusercontent.com/1271053/96038340-fc5d6700-0e34-11eb-90fc-fd32b7d8ccfe.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha w/o Gutenberg
- If the Gutenberg plugin is installed, which version is it? 9.9.1

Notes:
- Doesn't impact Twenty Twenty because it sets a max width using `[class*="__inner-container"]`.

**Comment by jasmussen** [comment]
Thank you for the ticket. I believe #26143 fixes this one.

**Comment by talldan** [comment]
Closing as fixed by #26143

**Comment by dreamwhisper** [comment]
Thanks for the quick fix @jasmussen!
