### ISSUE TITLE
Site Editor: navigation sidebar is not visible outside of fullscreen mode

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#26125]
It's not possible to open navigation sidebar when fullscreen mode for site editor is turned off:

<img width="507" alt="Screenshot 2020-10-14 at 21 45 49" src="https://user-images.githubusercontent.com/1182160/96037844-a4d7ef00-0e66-11eb-985d-305bc3ab49d9.png">

**Comment by Copons** [comment]
Related: #26021

**Comment by creativecoder** [comment]
PR to address this at https://github.com/WordPress/gutenberg/pull/29489

**Comment by creativecoder** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/29489
