### ISSUE TITLE
Vimeo undefined

### ISSUE THREAD

**Issue by eshannon3** [WordPress/gutenberg#2612]
WP 4.8.1 with Gutenberg 1.0.0

## Issue Overview

When a Vimeo block is added, but no Vimeo link entered, the front end public view is showing "undefined"

## Steps to Reproduce (for bugs)

1. Add two text blocks, then a Vimeo block between them
2. Leave the Vimeo URL input blank
3. Publish the post
4. View the published post which contains "undefined" where the Vimeo block should be

## Expected Behavior

If a video block URL is left blank, I'd expect nothing to appear for that block - I would just see the block above and the block below, no Vimeo block at all.

## Current Behavior

Vimeo block displays "undefined" instead of not appearing.

## Possible Solution

On the block display end, first check for a valid video URL. If one doesn't exist, simply do not display the block.

## Todos
- [ ] Tests
- [ ] Documentation

Issue visible on test site at: http://s20923.p221.sites.pressdns.com/2017/a-fancy-news-story/

**Comment by aduth** [comment]
Somewhat related to discussion of how to handle empty blocks: #1181
