### ISSUE TITLE
Adding a Block category drop down to the inline inserter.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#26130]
**Is your feature request related to a problem? Please describe.**
The inline inserter:
![Screen Shot 2020-10-14 at 23 25 40](https://user-images.githubusercontent.com/5323259/96046962-9f81a100-0e74-11eb-8633-c11f319a34e6.png)

Only shows the 6 currently used blocks. One needs to click the Browse all button to open the top left inserter panel to see all the options.

**Describe the solution you'd like**
My suggestion creates a dropdown of category options.

Shows the current option preselected.
![Modified-Inline-Inserter-closed](https://user-images.githubusercontent.com/5323259/96047161-f9826680-0e74-11eb-8915-d3f62acbbb31.jpg)

One is able to choose another option in the drop down.
![Modified-Inline-Inserter-open](https://user-images.githubusercontent.com/5323259/96047180-fe471a80-0e74-11eb-8ec8-14eb8382f9bc.jpg)

**Describe alternatives you've considered**
Clicking Browse all to open the full Inserter panel.

Related to **Adding a Block category drop down in the Inserter Blocks panel.**
https://github.com/WordPress/gutenberg/issues/26028

**Comment by paaljoachim** [comment]
Here is a suggestion in relation to having widget preselected in the Inline inserter in the widget screen.
![Inline-Inserter-Widget-Screen](https://user-images.githubusercontent.com/5323259/96047855-02c00300-0e76-11eb-92e4-dbd0e6429343.jpg)

**Comment by paaljoachim** [comment]
Another suggestion. With focus on the Widget screen.

![Inline-Inserter-Widget-Screen-ver2-closed](https://user-images.githubusercontent.com/5323259/96052541-12dbe080-0e7e-11eb-9c3f-03c1bf0ae75e.jpg)

![Inline-Inserter-Widget-Screen-ver2-open](https://user-images.githubusercontent.com/5323259/96052552-18d1c180-0e7e-11eb-9b2c-e808567062a3.jpg)

**Comment by SchneiderSam** [comment]
The 2nd suggestion looks muuuuuuuch better

**Comment by mapk** [comment]
This feels like adding a lot of UI to solve an edge case scenario. But please correct me if I'm wrong. I agree that the sibling inserter is limiting, but I believe that's the intent. It's meant to be something minimal. When the user wants more, they open up the Inserter panel. 

That being said, I've seen several bits of feedback that wish the Inserter panel would remain open when adding blocks/widgets, but due to accessibility requests and keyboard interactions, we treat that panel as a modal, so when focus moves away from it, it closes.

And while I realize that's challenging when trying to add block after block or widget after widget. I also realize that these widget areas are more about displaying certain things (ie. latest posts, latest comments, etc) rather than writing content. But I still think that between the Inserter panel, mini-inserter, and quick-inserter `/` that's probably enough to get done what needs doing.

**Comment by paaljoachim** [comment]
Many good points! I have been hesitant in exploring but had a feeling that I might be onto something so I continued.

I made this prototype.

https://www.figma.com/proto/CKBzHGzQ6g9CcliwemEiBg/Untitled?node-id=1%3A2&scaling=min-zoom
Just to see how a drop down would function inside the inline inserter.

Here is a gif of how it works.
![Inline-Inserter-drop-down-Widget-Screen](https://user-images.githubusercontent.com/5323259/96167652-04de9c00-0f20-11eb-9da8-e3b5c3c85f99.gif)

**Comment by bph** [comment]
@mapk I understand the reasoning behind why the left bar Inserter needs to close when focus changes. Would there be a way to add a 'stay open' property to the modal, users can switch on and off? Default is "off". 

As for the Sibling inserter, it's rather arbitrary what is shown in it. All the examples in this issue. Show blocks that are familiar from the post edit screen. What happens on the Widget screen is that it's filled arbitrarily with Widgets that may or may not be important to the user. 
![Screen Shot 2020-10-15 at 9 59 41 AM](https://user-images.githubusercontent.com/39980/96185146-78c07a80-0f07-11eb-8795-38b41598556e.png)

I mentioned in [another issue](https://github.com/WordPress/gutenberg/issues/26159) that the left bar Inserter doesn't seem to display any categories for the user to narrow down the view. Both screens right now a quite cumbersome to use.

**Comment by mapk** [comment]
> I understand the reasoning behind why the left bar Inserter needs to close when focus changes. Would there be a way to add a 'stay open' property to the modal, users can switch on and off? Default is "off".

I think that's totally possible! Maybe it resides as a setting in the new "Preferences" section?

**Comment by mapk** [comment]
Thanks for these mockups, @paaljoachim! I still hold that the Sibling Inserter here is too small to introduce more UI. It should function as a quick insertion point. Something that can help solve this, [which I commented here](https://github.com/WordPress/gutenberg/issues/25959#issuecomment-713200305), is that searching "widget" should reveal any Core widget-like blocks AND 3rd party widgets installed. By improving the search, we can improve this experience. The "Browse all" is more for browsing then which works much better in the larger Inserter panel.

**Comment by paaljoachim** [comment]
For the sake of clarity and for a better inline inserter to be much more efficient to be used. I also added what my design mockup would look like in Gutenberg.

![Improved-Inline-Inserter-Gutenberg](https://user-images.githubusercontent.com/5323259/97268955-0156e900-182d-11eb-8828-d0f246adf2df.gif)

Prototype:
https://www.figma.com/proto/CKBzHGzQ6g9CcliwemEiBg/Inline-Inserter-w-drop-down-Widget-screen?node-id=64%3A141&scaling=min-zoom

**Comment by paaljoachim** [comment]
We had a long and really good discussion of this issue during the joint accessibility and design Open Office/meeting.
Here is a link: https://wordpress.slack.com/archives/C02S78ZAL/p1603811546082700

**Comment by mapk** [comment]
I'm not sure what resulted from that conversation, but I tend to agree that the search is the strongest feature in this small inserter. @paaljoachim I really appreciate your explorations and they helped us talk it through, however, I'm going to close this in favor of the existing UI that is both simple and searchable.
