### ISSUE TITLE
Neighbour block jumping if above is aligned block

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#2613]
## Issue Overview

When setting an align block option to a basic paragraph, the next block dancing around, not sure if to go beside or below. 

![gutenbernalignment](https://user-images.githubusercontent.com/1996370/29886688-ce5b57a2-8d6f-11e7-8c49-d69b4cd5667d.gif)

## Steps to Reproduce (for bugs)

1. paragraph type, set block align left
2. add new block below, type content
3. blocks jump around while typing and un/focus

**Comment by karmatosed** [comment]
What browser are you using? I am not getting bouncing, although I do get a situation where it's hard to see what block is what - that's maybe an expanded/another issue to raise. Let's first try and replicate the dancing though.

**Comment by davidsword** [comment]
sorry I meant to write that. I'm on safari 10.1.2, macOS

**Comment by karmatosed** [comment]
I am unable to replicate this using the latest build. I'm going to close but if you can, let's reopen.
