### ISSUE TITLE
Allow expanding and collapsing of nested blocks in List View

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26141]
Nested blocks can get quite complicated in List View. The list view shows the structure of your content. It is present in a few places, it's in the post editor, it works as a persistent sidebar in the site editor, and it exists as a tool for the navigation block. 

Allowing users to expand and collapse parent blocks to reveal or hide the inner blocks would be a good feature.

## What is your proposed solution?

Add a small chevron to the left of blocks that feature nesting:

<img width="465" alt="Screenshot 2021-03-10 at 15 56 02" src="https://user-images.githubusercontent.com/1204802/110648693-39960d00-81b9-11eb-9b1f-b7f7cd129aaf.png">

**Note:** This change should apply to anywhere we use the List View component.

**Comment by jasmussen** [comment]
I took the liberty of updating this ticket with mockups from the duplicate #29726.

**Comment by gwwar** [comment]
I can take a look at this one, seems like we might be able to get some perf wins here too with the feature.

**Comment by gwwar** [comment]
https://www.w3.org/TR/wai-aria-practices/examples/treegrid/treegrid-1.html looks like a nice example/resource

**Comment by jasmussen** [comment]
On behalf of Kerry who did all the work, this one is now fixed! 🎉
