### ISSUE TITLE
Consider more theme friendly approach to caption styling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2615]
Captions are styled with a color and this may not be friendly to different themes. How can we explore a design that is a little bit better for more themes? 

The easiest option may be to remove the color, but is there another way?

**Comment by mtias** [comment]
Many blocks will have slightly opinionated styles, I think that's the nature of it. I would expect themes to provide styles for core blocks as needed. It is also possible for a theme to not load any gutenberg styles at all if they want to go from scratch.

**Comment by karmatosed** [comment]
For now, lets close this in light of testing what those styles do. I've had a bit of a think about this and whilst think it needs working on, there's not a direct suggestion right now. So, it's worth closing.
