### ISSUE TITLE
Getting lot's React warnings in the console for core blocks

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#26151]
**Describe the bug**

When the Gutenberg (v9.1.1) plugin is active I'm getting loads of "React does not recognize the `xx` prop on a DOM element" type console errors for all blocks (including core ones too).

I'm getting around 14 of these errors when testing the core heading block but it's the same for other blocks too.

**To reproduce**
Add a block to the editor and open the console window.

**Expected behavior**
No console errors.

**Screenshots**
![gb-block-errors](https://user-images.githubusercontent.com/1482075/96122894-0ab98a80-0eea-11eb-833b-514e1c354b59.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg plugin version: 9.9.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 85

**Comment by skorasaurus** [comment]
Hi, 
if you are still able to reproduce this without any plugins (besides gutenberg) activated or still can still reproduce this with the newest version of Gutenberg; please let us know so we can help you more. :)

**Comment by talldan** [comment]
I'm unable to reproduce, but there's not too much to worry about, these are more warnings for the developer and shouldn't affect the editor's functionality.

If they are caused by Gutenberg, then it's something we should fix, so any steps for reproducing the warnings would be welcome.
