### ISSUE TITLE
When themes don't support widgets the editor looks broken

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#26153]
In the classic widgets editor when a theme has no widget support we see a message. In the new widgets editor we get one widget area with inactive widgets and no message.

To reproduce:

1. Have Gutenberg plugin installed
2. Install a no widget theme such as Fonts
3. Go to Appearance > Widgets notice there are no widget areas, except "Inactive widgets"
4. Manually go to /wp-admin/widgets.php, notice the message

Screenshots:

*Classic widgets editor*

<img width="1491" alt="Screenshot 2020-10-15 at 15 44 58" src="https://user-images.githubusercontent.com/107534/96128271-ce902500-0efd-11eb-9c62-089392f59122.png">

*Block-based widgets editor*

<img width="1705" alt="Screenshot 2020-10-15 at 15 45 15" src="https://user-images.githubusercontent.com/107534/96128342-e2d42200-0efd-11eb-9d82-4620f1111560.png">

**Comment by mapk** [comment]
I just tested this with the Fonts theme. Is there a reason we show the Widgets menu item in the wp-admin menu if a theme does not support widget areas? Can we just hide that menu option?

**Example of Fonts theme & Widgets menu option still visible**

![Screen Shot 2020-11-09 at 12 06 14 PM](https://user-images.githubusercontent.com/617986/98590824-3bd87100-2284-11eb-9f31-0886e412bec1.png)

If there remains a reason to keep this option available even if the theme doesn't support widgets, we might be able to make use of the existing notifications in Gutenberg.

**Existing notifications**

![Screen Shot 2020-11-09 at 12 43 58 PM](https://user-images.githubusercontent.com/617986/98594324-5c56fa00-2289-11eb-881f-483c0209a1bb.png)

**Mock up of proposed design**

![No widget areas](https://user-images.githubusercontent.com/617986/98595059-56ade400-228a-11eb-8aa0-8dfc9402ae04.png)

**Comment by noisysocks** [comment]
Noting that https://github.com/WordPress/wordpress-develop/pull/1308 contains a fix for this.
