### ISSUE TITLE
When switching themes some block color settings are lost

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#26160]
To reproduce:

1. Have the Gutenberg plugin installed and 2020 theme active
2. Go to appearance > widgets 
3. Add a quote block
4. Customize the block to have green background and white foreground, save.
5. Switch theme to 2019
6. Go to appearance > widgets 
7. Notice the quote block has no color settings

I would expect to have the colors saved as all the other widget settings.

**Comment by talldan** [comment]
> Add a quote block

Quote doesn't have colors

> Customize the block to have green background and white foreground, save.

A custom color or a 'named' color?

**Comment by draganescu** [comment]
It does have color, 

<img width="571" alt="Screen Shot 2020-12-01 at 16 11 10" src="https://user-images.githubusercontent.com/107534/100751633-3fc56200-33f0-11eb-8155-6d4849063b88.png">


But now it seems I can't reproduce the problem - re tested with headings and quotes and when switching themes the colors are preserved
