### ISSUE TITLE
After adding a Query Block: Set focus on Query Block instead of Post Title Block

### ISSUE THREAD

**Issue by mariohamann** [WordPress/gutenberg#26167]
Description:
> After adding a Query Block automatically the first "Post title" block was focused. In my opinion the Query block itself should be focused, not its content.

_coming from the PR by @ntsekouras – https://github.com/WordPress/gutenberg/pull/26025#issuecomment-709363235_

I have to admit when I inserted it for the first time, I wasn't even sure if I have correctly added it. Forcing users to switch to the parent of the parent of the currently focused block to see the settings of the last inserted block is not the best UX, I think. :)

If I use a Query Block, I first want to see what this Block does and maybe how I am able change it, like the amount of posts, categories etc. We should not forget: This Query Block is a quite complex one and maybe some people even don't know what it does when they add it for the first time. We shouldn't make it even more complicated to use it.

**Comment by ntsekouras** [comment]
Thanks @mariohamann - great suggestion! Actually I think this will lead to less confusion as well!
