### ISSUE TITLE
Render widgets in the editor with the same style as in the theme

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#26163]
**Enhancement**
While the classic widgets editor did not have any preview functionality, the current preview really doesn't match the front end for blocks used as widgets.

Is there any way to bring over the styles used for the sidebars (widget areas) in themes?

**To reproduce**
0. Make sure to have the Gutenberg plugin active and the 2020 theme
1. Go to Appearance > WIdgets
2. Add a quote and customize it to have a green background, save.
3. Go to front end
4. See the style of the Quote

**Expected behavior**
I would love to see the same styles that the theme applies to the widget when rendered.

**Screenshots**
<img width="755" alt="Screenshot 2020-10-15 at 17 40 05" src="https://user-images.githubusercontent.com/107534/96145121-942e8400-0f0d-11eb-9a6c-5fcfc2db4c3c.png">

<img width="1346" alt="Screenshot 2020-10-15 at 17 40 12" src="https://user-images.githubusercontent.com/107534/96145145-98f33800-0f0d-11eb-9d17-7dd9b49c5b34.png">

**Comment by noisysocks** [comment]
I am wondering if we should implement this enhancement for v1 of the widgets editor?

**Comment by draganescu** [comment]
Well, for one I am thinking of how the same thing in the customizer looks, once in the sidebar once in the preview. 
It does not look like a critical issue but it is a great enhancement. 

Also, overall, we should aim to solve this problem wherever we use block editors. It is a great opportunity to bump into limitations of Gutenberg and fix them. The block editors try very hard to be as close as possible an approximation of the front end and are only getting better at it.

**Comment by noisysocks** [comment]
If we can do it easily then I'm very keen. It would be a really nice UX. I don't think this enhancement is necessarily a priority for WordPress 5.8, though.

**Comment by noisysocks** [comment]
See also discussion in https://github.com/WordPress/gutenberg/issues/32449#issuecomment-856233696.

**Comment by noisysocks** [comment]
Closing in favour of https://core.trac.wordpress.org/ticket/53344.
