### ISSUE TITLE
Gutenberg breaks WooCommerce Analytics and Customers pages

### ISSUE THREAD

**Issue by davoraltman** [WordPress/gutenberg#26169]
**Describe the bug**
When the Gutenberg plugin is installed and activated, the WooCommerce Analytics Dashboard doesn't get displayed.

**To reproduce**
1. Install and activate both WooCommerce and Gutenberg plugins
2. Go to WP Admin -> WooCommerce -> Analytics (/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview)
3. See error
4. Go to WP Admin -> WooCommerce -> Customers (/wp-admin/admin.php?page=wc-admin&path=%2Fcustomers)
5. See error.

**Expected behavior**
This only happens when the Gutenberg plugin is activated. I also tested with 9.0 version and got the same results.

**Screenshots**

<img width="882" alt="Screen Shot 2020-10-15 at 7 48 46 PM" src="https://user-images.githubusercontent.com/10340370/96167290-766a1a80-0f1f-11eb-82b9-7aac3e9d9a7e.png">

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]. Gutenberg plugin installed.
- If the Gutenberg plugin is installed, which version is it? 9.1.1 but the error is reproduced with 9.0 as well.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.15.5
 - Browser: Chrome
 - Version: 86.0.4240.80

**Comment by JoshuaGoode** [comment]
Should be fixed in Woo Admin 1.6.2: https://github.com/woocommerce/woocommerce-admin/issues/5385
