### ISSUE TITLE
 'Start writing' placeholder text doesn't appear consistently.

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26177]
**Describe the bug**

When you first open up the widgets screen on a new site, the padding for the first widget area appears to be off. 

**To reproduce**
1. Create a new test site. 
2. Install Gutenberg and activate.
3. Go to Appearance > Widgets
4. See padding is off :) 

**Expected behavior**

I expect each widget area to look the same. 

**Screenshots**

GIF: 

![widget spacing](https://user-images.githubusercontent.com/26996883/96195419-f71e1c00-0f09-11eb-8a7b-58669ce01e8c.gif)

Screenshot for good measure:

<img width="776" alt="Screen Shot 2020-10-15 at 5 16 34 PM" src="https://user-images.githubusercontent.com/26996883/96195515-2df43200-0f0a-11eb-81da-1108d2932ad7.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by mapk** [comment]
@annezazu it looks like your accordion arrow isn't toggling to show when the accordion is open. And so I wonder if that state is when the accordion is actually open but without any blocks. So the extra padding that you see is actually an open and empty widget area.

If I'm off here, I totally agree that these should be the same height/padding when they are in the same closed state.

**Comment by talldan** [comment]
I think that's right, this is an empty widget area. Seems like an issue that 'Start writing' placeholder text doesn't appear consistently.

**Comment by annezazu** [comment]
Ah yes! That sounds like the underlying problem in that case.

**Comment by noisysocks** [comment]
This might be incidentally addressed if we switch to the button block appender. See https://github.com/WordPress/gutenberg/issues/26072.

**Comment by draganescu** [comment]
To reproduce consistently:

- have a theme with multiple widget areas 
- make sure one of the areas is empty (select all widgets and blocks, delete and save)
- collapse all widget areas
- expand the empty one, the prompt appears
- expand the one above it, the prompt disappears from the one below
- collapse the one above, the prompt is missing from the one below
