### ISSUE TITLE
Improvements when Inserting a Query block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#26189]
Let's correct the following two behaviours:

- [x] Don't show "No results" while posts are being loaded.
- [ ] Avoid focusing the first block contained within the Loop template. The container Query should be in focus.

**Comment by mtias** [comment]
If we add a "loading posts" message it should also include the count.

**Comment by ntsekouras** [comment]
>If we add a "loading posts" message it should also include the count.

That would not be possible without getting the results first, because we could show the `posts_per_page` but the actual results could be less or none.

Alternative would be to show `loading at least {posts_per_page}`, but doesn't feel very useful IMO.

**Comment by mtias** [comment]
Right, good point. We could say "Querying 5 posts from category x..." (essentially describe the query we are doing).

**Comment by mtias** [comment]
But as a start, of course, just "loading post_type..." seems fine.
