### ISSUE TITLE
[Widgets Screen] Cover Block stretches across widget area if height left unspecified 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26181]
**Describe the bug**

If you add a cover block to the new Widgets Screen without specifying height, it stretches in a fairly dramatic way on the front end of the site. 

**To reproduce**
1. Install Gutenberg and activate.
2. Go to Appearance > Widgets.
3. Add a Cover Block.
4. View on the front end of the site to see it overtake the widget area. 

**Expected behavior**

I expect the Cover Block to not take up so much space vertically. 

**Screenshots**

Video here: https://cloudup.com/cFRDApT8p2Z

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by talldan** [comment]
I wasn't able to reproduce. Just for comparison:

@annezazu result:
<img width="1488" alt="Screenshot 2020-10-16 at 2 24 34 pm" src="https://user-images.githubusercontent.com/677833/96220476-5f790600-0fbb-11eb-8e89-07690123c6ed.png">

My result:
<img width="1273" alt="Screenshot 2020-10-16 at 2 23 46 pm" src="https://user-images.githubusercontent.com/677833/96220488-6738aa80-0fbb-11eb-8fe2-d50a0c0ff7ef.png">

I tried a few different things, but wasn't able to get the cover to overlap.

**Comment by annezazu** [comment]
@talldan I found the key variable! Add more content to footer #2 that stretches down and you'll find the cover block fills in the space. Here's a video to demonstrate as this is a bit hard to explain: https://cloudup.com/csMl6wf_6pT

**Comment by talldan** [comment]
I still can't reproduce this, I have plenty of content in the second footer and the cover block still looks the same:
<img width="1187" alt="Screenshot 2021-06-10 at 3 58 49 pm" src="https://user-images.githubusercontent.com/677833/121487574-cba1f180-ca04-11eb-84f0-b7b35f37c57f.png">

**Comment by Mamaduka** [comment]
I followed the steps and also not able to reproduce the issue.

Cover block has the default `min-height` defined in block styles. So not specifying min-height shouldn't be an issue.

**Comment by draganescu** [comment]
I also could not reproduce this. It may be one of the incipient problems which have been solved in the meantime. Given the date of the issue and the number of attempts to repro I'll close.
