### ISSUE TITLE
Data not saving/loading correctly on the widget screen.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26186]
**Describe the bug**
When saving from the widgets screen, I'm seeing lots of issues. I may have a messed up install, but I thought I'd see if anyone else can reproduce.

Something I noticed when looking at HTTP requests is that often widgets would have the same `id` and `number`.

**To reproduce**
1. Go to the customizer widget screen and remove all widgets from all widget areas
2. Reload to make sure all widgets are gone
3. Go to the new widget screen and add two paragraphs with different text (e.g. 'test 1' and 'test 2')
4. Click Update, observe the notification says 'There was an error'.
5. Notice after updating, the update button can still be clicked.
6. Click update a few more times.
7. Reload the page.
8. Note that the blocks displayed are not those created (for me I ended up with multple paragraphs with the text 'test 1').

**Expected behavior**
Data is saved correctly.

**Comment by TimothyBJacobs** [comment]
I think this is because the current code doesn't update the client ID to widget ID mapping after new widgets are created. It only does it when the sidebars are initially loaded. That might be the issue. That's fixed in #26086. I'm curious if you can reproduce that issue on that branch.

**Comment by helen** [comment]
Testing with #26086 and everything seems to save correctly (if slowly), including the workaround ability to insert blocks in between legacy widgets by switching into the customizer. The one thing I noticed was that the first time I tried to save after applying #26086 I got `There was an error. can't access property "id", g is undefined`, after that I got the correct `Widgets saved.` message.

**Comment by TimothyBJacobs** [comment]
Even with #26086 applied, you might see a similar bug due to #26252.

**Comment by noisysocks** [comment]
Possibly the same bug as #26252 or https://github.com/WordPress/gutenberg/issues/27173.

**Comment by noisysocks** [comment]
Does this still happen?

**Comment by talldan** [comment]
I think it's ok to close this now, I haven't noticed it for a while.
