### ISSUE TITLE
[Navigation Panel] Untitled Posts don't show up in navigation panel

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26183]
**Describe the bug**

When using the new navigation panel, any untitled posts don't show up in the sidebar.

**To reproduce**
1. Install and activate Gutenberg
2. Head to Gutenberg > Experiments > Enable full site editing and starter content.
3. Create some untitled posts. 
4. Try to use the navigation panel to view all posts. 
5. See untitled posts show as empty.

**Expected behavior**

I expect to see "Untitled Posts" listed rather than an empty space.

**Screenshots**

<img width="301" alt="Screen Shot 2020-10-15 at 6 56 04 PM" src="https://user-images.githubusercontent.com/26996883/96201019-ae219400-0f18-11eb-9fd3-d69a63dd5ea6.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by ntsekouras** [comment]
Resolved by this PR: https://github.com/WordPress/gutenberg/pull/27280
