### ISSUE TITLE
`0` Not properly recognized as default block attribute value.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#2619]
## Issue Overview

*Edit*: Verison 1.0.0

Couldn't find if this was already reported so hopefully not a duplicate, `0` is not properly recognized as a default block attribute value. For example: If a block has a attribute tacosToOrder, and the default value is set at `0` the block will not instantiate with that default attribute.

```js
attributes: {
  tacosToOrder: {
    type: 'number',
    default: 0
  }
}
```

Does not work right.

## Steps to Reproduce (for bugs)

1. Create a block.
2. Create an attribute with a default value of `0`. With type `'number'` (probably applies to other types)
3. Verify that the attribute is not carried into block instance by default when inserted in the editor.

## Expected Behavior

The block should instantiate with a value of `0`.

## Current Behavior

The attribute is not included in the list of attributes and needs to be set after instantiation of a block of that type.

## Possible Solution

Not familiar with how the default attributes were instantiated/ too lazy to look right now, but I imagine it has to do with 0 being a falsy value.

**Comment by youknowriad** [comment]
closes by #4088
