### ISSUE TITLE
Add a Posts List

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#26193]
The first variation we should have for the Query block is a "Posts List", which sets custom post type to "posts", number of posts to something like 4 or 5, and likely excludes sticky posts (doesn't reorder them). I know this is fairly equivalent to "Latest Posts".

**Comment by aristath** [comment]
Does it also use `<ul><li>` elements to format the list so it's actually - semantically - a list?

**Comment by mtias** [comment]
@aristath sorry missed your question :) I was using "List" in the name loosely. It probably makes sense for this to be configurable during setup and / or afterwards.
