### ISSUE TITLE
Selection Mode and "Escape Levels"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#26196]
Currently pressing escape engages "Select" mode, but it's not intuitive to move between levels (from Button to Buttons). Doing shift-tab moves to the correct container, but selection is broken (the name of the block doesn't show, and arrows no longer work for traversing). I think pressing escape again while on select mode should try to move selection one level up in the tree.

**Comment by Mamaduka** [comment]
@mtias, I believe the issue with arrow traversing has been fixed.
