### ISSUE TITLE
[ Widgets editor ] confusing option to change block type for widget

### ISSUE THREAD

**Issue by dariaknl** [WordPress/gutenberg#26207]
**Describe the bug**
Bug found during testing new widget editor in the version which was provided [here](https://gutenbergtimes.com/need-a-zip-from-master/)

**To reproduce**
1. Go to Widget editor.
2. See that you can change block type for widgets:
<img width="194" alt="Screenshot 2020-10-16 at 16 29 29" src="https://user-images.githubusercontent.com/19681708/96272967-15018480-0fcf-11eb-8b44-0b691b392ae3.png">

**Expected behavior**
As an end user I cannot see any use case behind this functionality: how changing of the block type is supposed to work for widgets? Especially “transform to group” option. Either it should be clear how it works for widgets, or it should be removed. 

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [from here](https://gutenbergtimes.com/need-a-zip-from-master/)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by paaljoachim** [comment]
I think at this stage we should just disable the feature. Perhaps at a later time activate it again (if needed).
Thoughts? @mapk @enriquesanchez

**Comment by mapk** [comment]
>As an end user I cannot see any use case behind this functionality: how changing of the block type is supposed to work for widgets? Especially “transform to group” option. Either it should be clear how it works for widgets, or it should be removed.

"Transform to group" works the same way it does in the post editor. This allows the user to create a group block around this block which they can then apply a class to, or style a bit differently like changing the background color. Keeping consistency with the post editor is a good goal here IMO.

**Comment by talldan** [comment]
Looks like a bug though, another way to reproduce https://github.com/WordPress/gutenberg/issues/25834.

**Comment by mapk** [comment]
So keeping the use case is still valid, and identifying the bug is done in the other issue. Shall we close this one? @talldan ?

**Comment by talldan** [comment]
@mapk The other issue is closed now, so I think we can keep this open.

**Comment by mapk** [comment]
When I said, "keeping the use case" I meant that we should keep the Transform option for the Legacy Widget block. So since we're keeping this feature, and the bug is identified elsewhere, I'll go ahead and close this issue.
