### ISSUE TITLE
Hello Dolly plugin causes screen breakage

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26219]
**Describe the bug**

The text from Hello Dolly causes strange overlap with the new Widgets Screen and also creates a new pathway to scroll up/down. [According to wp.org](https://wordpress.org/plugins/hello-dolly/), the plugin is used on 800k+ sites and is managed by wp.org so reporting here to be safe :D 

**To reproduce**
1. Install and Activate Gutenberg and Hello Dolly.
2. Head to Appearance > Widgets
3. See hello dolly text hidden behind update button. 
4. Click into the top toolbar and scroll up/down to see more breakage. 

**Expected behavior**

**Screenshots**

20s Video: https://cloudup.com/cMMxkpVqcb1

Screenshot: <img width="209" alt="Screen Shot 2020-10-16 at 1 04 06 PM" src="https://user-images.githubusercontent.com/26996883/96298675-153e5780-0fb0-11eb-8fd6-1e3c9f579472.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by noisysocks** [comment]
Let's do whatever the block editor does here.

**Comment by getsource** [comment]
It looks like this is currently accounted for with the editor within the Hello Dolly plugin itself, which is included with WordPress core.

That looks to happen here: https://github.com/WordPress/wordpress-develop/blob/master/src/wp-content/plugins/hello.php#L85

Thinking it'd make sense to do the same in that plugin for the new Widgets screen, in that case.

**Comment by getsource** [comment]
The closest class I can find is `.appearance_page_gutenberg-widgets`.

This works in the [Hello Dolly plugin](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-content/plugins/hello.php#L85):
```
	.block-editor-page #dolly,
	.appearance_page_gutenberg-widgets #dolly {
		display: none;
	}
```

@noisysocks Since the class has Gutenberg in the name, do you think it makes sense to make a ticket + path and add to core at this point, or should it get added on the Gutenberg side first? 

If Gutenberg, I'm not completely sure where it should be -- [packages/edit-widgets/src/style.scss](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/style.scss), maybe?

**Comment by noisysocks** [comment]
Is `.block-editor-page` a class that's added to the `<body>`? Maybe the widgets screen should add it. It is, after all, a page containing a block editor and nothing else.

**Comment by lukecarbis** [comment]
If we're going to start slowly phasing the Hello Dolly message out with `display: none` on any Gutenbergish pages… maybe it's time to reassess whether we still need it?

**Comment by noisysocks** [comment]
That's probably a decision better suited for a future DevChat. I know there's some strong feelings (good and bad) in the project about Hello Dolly 😀

**Comment by getsource** [comment]
> Is `.block-editor-page` a class that's added to the `<body>`? Maybe the widgets screen should add it. It is, after all, a page containing a block editor and nothing else.

Yes, it is! I don't know if anything else targets it that might not be preferred to apply to the Widgets screen as well, but I like that idea.
