### ISSUE TITLE
[Widgets Screen] Content added in blocks are removed if you deactivate Gutenberg

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26217]
**Describe the bug**

If you activate Gutenberg, add a few blocks to the Widgets Screen, and then deactivate Gutenberg all the block content is lost. If you reactivate Gutenberg, the content returns inconsistently. Sometimes it works, sometimes it doesn't. I'm not sure what the ideal pathway is here but I imagine if people are trying out this screen that it would be helpful to somehow convert blocks into legacy options and the consistency across deactivation/activation needs to be updated. 

**To reproduce**
1. Install Gutenberg and activate.
2. Head to Appearance > Widgets. 
3. Add a few blocks. 
4. Head to Installed Plugins > Deactivate Gutenberg.
5. Head to Appearance > Widgets and see all blocks gone.
6. Head to Installed Plugins > Activate Gutenberg.
7. Make more changes to blocks.
8. Head to Installed Plugins > Deactivate Gutenberg.
9. Head to Appearance > Widgets and see all blocks gone.
10. Head to Installed Plugins > Activate Gutenberg.
11. Head to Appearance > Widgets and see weird results :D 

**Expected behavior**

I think I would expect some blocks (like paragraph) to be converted to text widgets. I would expect reactivating Gutenberg wouldn't cause the blocks I did add to get altered in any way (should be able to activate/deactivate and still have same block content). 

**Screenshots**

2 min video showing block's disappearing but consistency in the blocks returning upon reactivating Gutenberg:

https://cloudup.com/cU2UZzN-VE5

1 min video showing inconsistency in block content returning (also ran into weird perms issue that I think is unrelated):

https://cloudup.com/cBdKQMUJK-y

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by noisysocks** [comment]
I can't test this until https://github.com/WordPress/gutenberg/issues/27173 is fixed 🙂

**Comment by draganescu** [comment]
I think that with the Gutenberg plugin deactivated it's normal to not have the blocks in the old widgets screen as the update that enables their preview [depends on the plugin being active](https://github.com/WordPress/gutenberg/pull/24899/files#diff-76fac7db1b7772599af289762f685104abc1dd80bd4d63f2d07eb29c08936148R36).

cc @noisysocks to confirm, but I am closing this for now.
