### ISSUE TITLE
Refine the timing of when block decorations appear

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#2621]
This issue is related to the recommendations made in [The Gutenberg editor: Success lies in the timing](https://go.tinymce.com/blog/gutenberg-editor-success-lies-timing/)

Could we try the following **changes to the timing of visual elements**
1. Block outline* ON on mouseover (*only the outline: no toolbars, no cogs, no bins, no arrows)
2. Block outline OFF when mousing over another block (totally off, even the block outline)
3. Block decorations ON only on selection of block, i.e. when I “click” on the block (or keyboard equivalent)
4. Block decorations OFF when I am no longer in a block

The effect of this is that only the block outline would appear when we are navigating between blocks. The remaining decoration will only appear when a block is selected. We may need to refine this further, but let's start here and see how it feels

**Comment by karmatosed** [comment]
Can we scale back a little and keep the arrows for now. I feel the arrows are worth taking into user testing as we enter that. I would like to focus on how with the arrows we can iterate. What would our options be in that case?

**Comment by annaephox** [comment]
Absolutely - we'll definitely need to iterate and user test as we fine tune this.

So, let's start with:
- arrows + block outline on mouseover // disappear on mouseout
- cog + bin + toolbar on block select // disappear when block focus is lost

**Comment by karmatosed** [comment]
Do you have a mock-up for that? Even a small thing it would be good to ensure we have mocks.

**Comment by karmatosed** [comment]
@annaephox are you working on this issue?
