### ISSUE TITLE
Verse Block doesn't delete on backspace

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26220]
**Describe the bug**
Verse block should be able to delete with backspace and move focus to previous widget. Currently the widget is not deleted but the focus does change

**To reproduce**
1. Create a new post or edit an existing one.
2. Add a few blocks with content and an empty verse block in 2nd or later block.
3. Type into verse block and then backspace one time more than enough to clear content.
4. Widget in focus will return to previous block, empty Verse widget will remain.

**Expected behavior**
Similar to Paragraph block the widget should be deleted when backspacing far enough to remove all content.

**Screenshots**
[Demo](https://d.pr/i/AsnAjJ)

**Comment by ntsekouras** [comment]
Hey @DaisyOlsen - thanks for reporting this. After a quick test it seems that this happens after a `Cover` block (at least), it doesn't happen after a `paragraph` and you are 'locked' there if you are after a `Heading` block, no matter how many times you press backspace.

So it needs more testing to find the inconsistent behavior, that seems related to the previous block.

**Comment by rafaelgallani** [comment]
I managed to reproduce it locally, can I look at this one?

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7.
Gutenberg plugin 10.1.1.
Twenty Twenty One.

Backspacing to delete the verse block leaves it in the layout even though I have "deleted" it and even the content in blocks before it.

**Comment by gwwar** [comment]
A quick way of getting into this state is navigating to the code editor, and updating content with:
```
<!-- wp:verse -->
<pre class="wp-block-verse"></pre>
<!-- /wp:verse -->
```

Go back to the visual editor. Backspace won't remove the verse block and add a default paragraph.

**Comment by rafaelgallani** [comment]
https://github.com/WordPress/gutenberg/issues/26220#issuecomment-711812917 was extremely helpful! 
This behavior indeed was depending on the previous block, and the reason for that is that the verse block was firing the `onMerge` event when the backspace key was pressed, hence it was being _merged_ (but not deleted) on the previous paragraph blocks. 

All I had to do was add the `onRemove` handler, so the block would also fire this event when needed. I'll open the PR right away.
