### ISSUE TITLE
Inserter search field just says "search for a block" but should suggest more

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26222]
### Problem
The search field in the Inserter on the Widget screen suggests searching for a block, but people are also interested in widgets in this particular screen.

**Existing example**
![Screen Shot 2020-10-16 at 1 15 15 PM](https://user-images.githubusercontent.com/617986/96304818-aa8e1b80-0fb1-11eb-8bed-439ca1484fff.png)

### Solution
Change the text to read "Search for blocks and widgets"

**Comment by carolinan** [comment]
In the inserter code, how can I use a condition for `searchFormPlaceholder` that only changes the text for the widget screen?
I don't know how to identify that the widget screen is being used.

**Comment by noisysocks** [comment]
You might have to update `Inserter` so the tit accepts a `placeholder` prop which `edit-widgets` can then provide.

**Comment by tellthemachines** [comment]
The inserter now says only "Search" (both in the post and the widgets editor), because it now searches through blocks, patterns and reusable blocks all at once. Is this still worth changing here?

**Comment by noisysocks** [comment]
Just "Search" is fine in my opinion.
