### ISSUE TITLE
Provide ability to Clear Inactive Widgets

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26232]
**Is your feature request related to a problem? Please describe.**
Stemming from - https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40072
> Provide ability to clear inactive widgets, this was available in legacy.
> | - Does “clear” mean delete them from the area? If so, this can be done by selecting them all and clicking delete.

This would bring feature parity with the legacy widget editor;
<img width="303" alt="Screen Shot 2020-10-16 at 5 23 06 PM" src="https://user-images.githubusercontent.com/8726005/96324033-6fe9aa80-0fd4-11eb-8058-663c366dfd18.png">

This is useful when there's alot of inactive widgets from switching themes. You currently can remove them one at a time in the new Widget Editor, but a button to clear them all would be helpful.

**Describe the solution you'd like**
Add a button to 'Clear Inactive Widgets' to the Inactive Widgets section of the new Widget Editor.

**Comment by garretthyder** [comment]
If we do add the clear button maybe it can be in the sidebar settings and thus available to any sidebar not only the inactive widgets allowing users to clear a sidebar and start from scratch.

**Comment by mapk** [comment]
In the case of adding this feature to all widget areas, here's an example of how that might work using the Browser's notification modal.

![remove](https://user-images.githubusercontent.com/617986/101407909-6ff97e80-3890-11eb-883f-a8592440eebe.gif)

**Comment by garretthyder** [comment]
That's awesome @mapk, and looks great. Is saving the current widgets to session/local a huge overhead? Just thinking even with the AYP message that storing in browser memory the previous state will allow an undo.

**Comment by mapk** [comment]
Oh maybe? I'm not entirely sure. 
I noticed the original message when removing them from the Inactive area indicated that the customizations could not be restored. 
How that applies here requires some technical feedback.

**Comment by kevin940726** [comment]
Maybe worth noting that if we fix https://github.com/WordPress/gutenberg/issues/28267 then it could be done by selecting all the widgets and delete them at once.

IMHO, the widgets editor is a complete different editing experience, it requires the users to hit "Update" manually rather than relying on auto-saving as in the original screen. We should provide a shortcut to allow them to delete all widgets in a widget area at once, but I don't think that we should auto-save it. A benefit of this approach is that the users could preview the changes and potentially restore back before updating.

**Comment by noisysocks** [comment]
I agree with @kevin940726. Could we use existing block editor patterns (select all) here? cc. @critterverse

**Comment by noisysocks** [comment]
Closing this in lieu of #28267. I think selecting multiple blocks and pressing _Remove blocks_, or pressing <kbd>Cmd</kbd>+<kbd>A</kbd> and then <kbd>Del</kbd> is a much more natural way to do this.
