### ISSUE TITLE
[Widgets Screen] Can't navigate between widget areas on smaller screen using the settings menu

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26235]
**Describe the bug**

When using a smaller screen, the settings don't allow me to navigate between block areas. 

**To reproduce**
1. Install and activate Gutenberg. 
2. Head to Appearance > Widgets
3. Make your browser smaller to under 780px and below. 
4. Click on the gear icon to pull up the block area settings.
5. Select different areas and find nothing happens. 

**Expected behavior**

I would expect on smaller screens that the experience would allow me to navigate through the block area and, upon selecting one, would then take me back to the main widget screen to continue with edits instead of nothing happening. 

**Screenshots**

![image4](https://user-images.githubusercontent.com/26996883/96326684-ed6ee400-0fef-11eb-8a22-18e82d2aa763.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by noisysocks** [comment]
Widget areas are no longer listed in the sidebar, so closing this.
