### ISSUE TITLE
Widgets Screen: Backspace on empty Verse block doesn't remove it.

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26230]
**Describe the bug**
In the new Widget Editor the Verse block doesn't get removed when it's empty and you hit backspace in the block. It will change focus to the prior block but it should remove the block. It does remove in Page/Post Editor it seems. 

**To reproduce**
1. Go to new Widget Editor
2. Add a Verse block
3. Type 'Backspace'.
4. It should normally remove the block as it's empty.

**Expected behavior**
When a Verse is empty then upon backspace it should be removed and focus moved to the prior block. 

**Screenshots**
![358dfb6e192b7c9466bc838845db8197](https://user-images.githubusercontent.com/8726005/96323605-aaeade80-0fd2-11eb-930e-6fd777638508.gif)

Editor:
WordPress version: trunk
Gutenberg version: 9.1.1

Desktop:
OS: Mac 10.15.7
Browser: Chrome 86.0.4240.75

**Comment by draganescu** [comment]
I tested and was able to reproduce this bug.

**Comment by tellthemachines** [comment]
I can no longer reproduce this issue on latest trunk. Closing for now. Feel free to reopen if needed!
