### ISSUE TITLE
Widget Screen: Introduce Preview of all sidebars or have widgets default to preview mode.

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26231]
**Is your feature request related to a problem? Please describe.**
Stemming from - https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40072
> It would be nice to introduce a preview capability to the sidebar sections as a whole so you can preview the entire sidebar to see how the widgets interact visually without having to click each one’s Preview individually.
> | - Ideally, once the widget form is filled in, I’d like it so that the widget defaults to the Preview mode when unselected. This would provide more of a Gutenberg feel.
It would be nice to either default the widget blocks to preview mode, or provide a preview ability to view ALL blocks in preview.

**Potential Solutions**
Either;
1. A Preview button that switches all blocks on the widgets screen to preview.
2. Make all blocks default to preview and return to preview when not in focus.

**Comment by annezazu** [comment]
Thanks so much for testing and reporting this. I definitely agree this would be an ideal option. Thankfully, this was reported already: https://github.com/WordPress/gutenberg/issues/26182 Closing out as a result. I will include the text above in that first issue to be safe.
