### ISSUE TITLE
[Widgets Screen] Duplicating a block with keyboard shortcuts causing both blocks to be selected

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26233]
**Describe the bug**

When duplicating a block using keyboard shortcuts, both blocks are selected after the fact (the copy and the current block). I wasn't able to find the same behavior in the main editor experience nor when using the menu item for duplicating a block so wanted to report to be safe!

**To reproduce**
1. Install and activate Gutenberg. 
2. Head to Appearance > Widgets
3. Add a few blocks. 
4. Duplicate a block using keyboard shortcuts ⇧⌘D
5. Find both blocks are selected. 

**Expected behavior**

I expect only one block to be selected. 

**Screenshots**

Video of widget editor experience: https://cloudup.com/c6xMjfJQSGr
Video of experience in a post editor: https://cloudup.com/cy1ez1mr6gk

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by noisysocks** [comment]
This works the same as it does in the post editor for me when I test locally. The second block is selected. Closing, but please re-open if I missed something.

**Comment by annezazu** [comment]
I was able to replicate using Gutenberg 9.6.2 and WordPress 5.6. Here's a quick video! https://cloudup.com/cbZweXRmUTT

**Comment by kevin940726** [comment]
I can't seem to reproduce it, here's a quick video.

https://user-images.githubusercontent.com/7753001/103859491-184f6c80-50f5-11eb-8188-5892725fdebb.mp4

Using WordPress 5.7-alpha-49941 (wp-env) and Gutenberg on master branch.

**Comment by annezazu** [comment]
@kevin940726 Since you're using the absolute latest, I'll close this out again :)
