### ISSUE TITLE
[Widgets Screen] Preview doesn't capture changes to legacy text widget

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26237]
**Describe the bug**

The preview option doesn't show changes made to a legacy text widget. 

**To reproduce**
1. Go to Appearance > Widgets and add at least one text widget with some text. 
2. Install and activate Gutenberg. 
3. Head to Appearance > Widgets
4. Make a change to the legacy text widget in the body of the text.
5. Try to preview to see changes. See no update. 

**Expected behavior**

I expect any changes I make in the legacy widget to show in the Preview. 

**Screenshots**

![preview gif](https://user-images.githubusercontent.com/26996883/96327231-f615e900-0ff4-11eb-9340-83578195c2fa.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by draganescu** [comment]
I will close this one as #26474 is more general and about the same thing.
