### ISSUE TITLE
[Widgets Screen] Block Areas don't open upon selecting "Edit" in the sidebar

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26234]
**Describe the bug**

Clicking on a given widget area on the sidebar will not expand the selected widget, which is something that users may expect.

**To reproduce**
1. Install and activate Gutenberg. 
2. Head to Appearance > Widgets
3. Close all widget areas. 
4. Use the sidebar to view block areas and click "edit".
5. Find that the closed widget areas don't open up to be edited. 

**Expected behavior**

I expect to be able to have the widget area open when I select "edit" in the sidebar. 

**Screenshots**

![image9](https://user-images.githubusercontent.com/26996883/96326598-35413b80-0fef-11eb-9f3a-8fe860015b2e.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by mapk** [comment]
This sidebar interaction has been removed. I don't think this is an issue anymore.
