### ISSUE TITLE
Block Widgets in Customizer: Indicate what type of block it is.

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26242]
**Is your feature request related to a problem? Please describe.**
With the new widgets setup you can have blocks are widgets. These are displayed in Customizer > Widgets as just 'Block'. It would be nice to indicate what block each item is.
<img width="287" alt="Screen Shot 2020-10-17 at 12 32 13 AM" src="https://user-images.githubusercontent.com/8726005/96331199-359dfe80-1010-11eb-8bce-6471a6b3c40f.png">

**Describe the solution you'd like**
Along with 'Block' indicate what it is so maybe 'Block: Paragraph'.

**Comment by draganescu** [comment]
Hi @garretthyder and thanks for the great issues. This as well will be covered as part of #27343. There the aim is to have the block editor instead of these "previews". Closing in favor of #27343.
