### ISSUE TITLE
Widgets Screen: Order of Appearance menu changes with Gutenberg installed

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26245]
**Describe the bug**
The order of the Appearance menu changes when the gutenberg plugin is installed to test the Widgets Screen.

Before:
<img width="189" alt="Screen Shot 2020-10-17 at 1 13 22 AM" src="https://user-images.githubusercontent.com/8726005/96331948-2a4dd180-1016-11eb-931f-834e3675b990.png">

After:
<img width="203" alt="Screen Shot 2020-10-17 at 1 13 42 AM" src="https://user-images.githubusercontent.com/8726005/96331952-2e79ef00-1016-11eb-94de-a17f9af3a118.png">

**To reproduce**
1. Install clean WP.
2. Hover over view the Appearance menu.
3. Widgets is third just before Menus.
4. Install Gutenberg
5. View the Appearance menu.
6. Widgets is now 5th after Background.

**Expected behavior**
The order of the Appearance menu shouldn't change.

**Editor version:**
- WordPress 5.6 trunk
- Gutenberg 9.1.1

**Comment by skorasaurus** [comment]
Reproducible with Gutenberg 9.8.2
