### ISSUE TITLE
Widgets Screen: Updating widgets should set the dirty flag so going to Customizer doesn't load the starter content.

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26241]
**Describe the bug**
With the original Widgets screen when a modification is made the dirty flag is set. This means that when you navigate to the Customizer and the dirty flag is set starter content isn't loaded.
The new Widgets screen doesn't adhere to this behaviour.

**To reproduce**
Steps to reproduce original behavior:
1. On a clean install.
2. Go to the legacy Widget Editor.
3. Add and save a widget.
4. Navigate to Customizer.
5. The starter content shouldn't load.

Steps to reproduce current behavior:
1. On a clean install. (If you dirtied the install already reset it)
2. Go to the new Widget Editor.
3. Add and save a widget.
4. Navigate to Customizer.
5. The starter content loads.

**Expected behavior**
Modifying widgets should set the dirty flag and thus disable starter content.

**Editor version:**
WordPress version: trunk

**Desktop:**
OS: Mac 10.15.7
Browser: Chrome 86.0.4240.75

**Comment by draganescu** [comment]
Hi @garretthyder  😄  What is "starter content"?

**Comment by garretthyder** [comment]
Hi @draganescu,
Starter Content is content supplied by themes that will load into Customizer if the site isn't a 'fresh_site' to prepopulate with data often an About/Content page and can contain pages, widgets, etc.
https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/
If you go to the Customizer on a fresh install with TwentyTwenty or a theme with starter content you'll find what I mean.
A community article on setting it up in your custom theme;
https://www.ibenic.com/create-starter-content-wordpress-themes/

The 'fresh_site' option controls if the Starter Content is loaded. There's a _delete_option_fresh_site method to turn it off and it employed through hooks on things like publish_post;
Function - https://github.com/WordPress/wordpress-develop/blob/d4b2126f07818e094c6423a3229151f1d27c74db/src/wp-includes/functions.php#L4261-L4269
Actions - https://github.com/WordPress/wordpress-develop/blob/910c2db68aef58ba14353e8c771dc3cfcd5ee9b5/src/wp-includes/default-filters.php#L245-L248

Hope that helps, I assume the wp_ajax_save-widget isn't being run with the block widget editor so just need to fire that or create a new hook and add it to the list of actions that disable the fresh_site flag.

**Comment by noisysocks** [comment]
Closing in favour of https://core.trac.wordpress.org/ticket/53317.
