### ISSUE TITLE
Migrating Block to InnerBlocks leads to "Cannot be previewed"

### ISSUE THREAD

**Issue by AntonioLeutsch** [WordPress/gutenberg#26249]
I've recently updated my code, to use InnerBlocks instead of an Array of Elements.
For that I wrote a Migration in my block, after some work it migrated as expected.

But if I Demo a Plugin Update, my InnerBlocks show me the Message of "This block has encountered an error and cannot be previewed. After Saving + Reloading my Page inside the Block Editor, all works and the Blocks get previewed. 

Here is my Migration.

```jsx
deprecated: [
        {
            attributes: {
                elements: {
                    type: 'array'
                },
                question_tag: {
                    type: 'string'
                },
                ...blockAttributes,
            },

            isEligible(attributes, innerBlocks) {
                return typeof attributes.elements !== 'undefined' && innerBlocks.length === 0;
            },

            migrate(attributes) {

                let x = [];

                attributes.elements.forEach(element => {
                    x.push(createBlock('structured-content/faq-item', {
                        question: element.question,
                        imageAlt: element.imageAlt,
                        thumbnailImageUrl: element.thumbnailImageUrl,
                        visible: element.visible
                    }, [
                      createBlock('core/paragraph', {
                        content: element.answer,
                        fontSize: 'large',
                      })
                    ]))
                });

                return [
                    {
                        ...attributes,
                        title_tag: attributes.question_tag
                    },
                    x,
                ];
            },

            save(props) {
                return null
            }
        }
    ]
```

Thank you!

**Comment by talldan** [comment]
> This block has encountered an error and cannot be previewed.

@AntonioLeutsch Would you be able to share what the error message is in the console?

**Comment by talldan** [comment]
Closing due to lack of response

**Comment by AntonioLeutsch** [comment]
@talldan Hey Sorry for the lack of response! 

My error messages are changing if i update the post.
<img width="902" alt="Bildschirmfoto 2021-02-14 um 11 24 32" src="https://user-images.githubusercontent.com/6033840/107874075-44f66100-6eb7-11eb-9461-dbafb814efcc.png">
<img width="898" alt="Bildschirmfoto 2021-02-14 um 11 24 11" src="https://user-images.githubusercontent.com/6033840/107874076-47f15180-6eb7-11eb-8177-da44492d5095.png">

**Comment by talldan** [comment]
@AntonioLeutsch The error message points to something unexpected related to a `setState` call in your block's edit function. Anything that looks like it my cause that?

**Comment by AntonioLeutsch** [comment]
@talldan Thank you.

I noticed that run setState on a new Prop. After that I saw that I merged the old attributes with the new one. After removing the merge, It worked! 🤙

**Comment by talldan** [comment]
Great, glad you managed to solve it. 😄
