### ISSUE TITLE
Editor automatically creates links for phrases that look like URLs

### ISSUE THREAD

**Issue by msaari** [WordPress/gutenberg#26266]
**Describe the bug**
When you paint some text and add a link to it, if the text vaguely looks like an URL, the editor will use the text as an URL.

**To reproduce**
1. Create a new post.
2. Type "magic: the gathering" or something else starts with a word followed by a colon.
3. Paint the text.
4. Click the link button to create a link.

**Expected behavior**
I would expect the editor not to assume the non-URL text to be an URL, and instead ask for the link target like it usually does. Perhaps the editor should check better for the URL pattern and only assume URLs where the protocol matches an actual protocol (perhaps use the list of permanent protocols as defined in the standards).

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg version: 9.1.1 (this happens also with the default editor)

**Desktop (please complete the following information):**
The problem is independent of browser or OS.

**Additional context**
I'm interested in providing code to fix this, but could use some pointers on where this behaviour happens – it's a big codebase and this isn't terribly easy to search for.

**Comment by msaari** [comment]
A bit of digging, and looks like the main problem here is that `isValidProtocol()` which checks if the protocol part of the URL is valid, doesn't really check if it's a real protocol or not. It just checks if the format is valid or not.

Now this makes some sense and it doesn't make sense to change `isValidProtocol()`. I would suggest creating a function `isCommonProtocol()` that would check for the most common protocols used (`http`, `https`, `mailto`, `tel`, `ftp`, etc.). In the link creation, this could be then checked and only URLs with these common protocols would be considered a link.

**Comment by talldan** [comment]
> I'm interested in providing code to fix this, but could use some pointers on where this behaviour happens – it's a big codebase and this isn't terribly easy to search for.

Thanks @msaari, looks like you found the place in your follow up comment. It'd be great to see a PR exploring this if you're still interested. Drop a comment if you need any help contributing, here's a link to the docs:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/develop.md

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/38497
