### ISSUE TITLE
Widget area block toolbar being displayed

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26261]
**Describe the bug**
When a widget area is selected, the toolbar is displayed with some options that don't seem to be completely supported within the screen:
<img width="472" alt="Screenshot 2020-10-19 at 4 32 19 pm" src="https://user-images.githubusercontent.com/677833/96420949-ba636500-1228-11eb-96d9-9bc27650fc0c.png">

I don't recall this being visible previously. It seems like the toolbar isn't useful.

**To reproduce**
1. Go to the widgets screen
2. Click on a widget area block
3. Observe the toolbar

**Expected behavior**
No toolbar?

**Comment by mapk** [comment]
I tested this and found the same thing. Some really odd overlapping happens too.

![toolbars](https://user-images.githubusercontent.com/617986/96654758-d92d2e80-12f0-11eb-8393-1cc181e453ea.gif)

**Comment by noisysocks** [comment]
Might be good to fix this at the same time: https://github.com/WordPress/gutenberg/issues/31021
