### ISSUE TITLE
Add Top Toolbar to Block Widget Screen

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26297]
**Is your feature request related to a problem? Please describe.**
Feedback extracted from [WPTavern Post](https://wptavern.com/are-block-based-widgets-ready-to-land-in-wordpress-5-6)
I am not a fan of not having an option for the top toolbar, which is available on the post-editing screen. One of the reasons for using this toolbar is because I dislike the default popup toolbar on individual blocks. It is distracting and often gets in the way of my work.

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/issues/27564 is related in that it adds the menu which contains the setting for Top Toolbar.

**Comment by noisysocks** [comment]
@critterverse: Do you foresee any problems with having the Top Toolbar in the Widgets screen?

**Comment by critterverse** [comment]
I think this would be a good addition! 👍

**Comment by noisysocks** [comment]
https://github.com/WordPress/gutenberg/pull/31926 added this.
