### ISSUE TITLE
Can edit in Classic Editor, Block Editor Crashes

### ISSUE THREAD

**Issue by ACEkin** [WordPress/gutenberg#26302]
Started editing a JetPack project in the classic editor, I switched to the block editor with no changes made. I converted the content to blocks. Deleted a couple of unneeded blocks and then I received an error I had never seen before. It said that the editor crashed or something to that effect and gave me the option to try to recover, copy the content, or copy the error. I saved the error and it is below for information. I could open the same project in the classic editor but have not since tried to push it to the block editor.

The copied error is below:

r@https://www.testbed.biz/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_block/static/build/post-thumbnail.min.js?ver=3.3.20:14:5541
Ag@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:63:107
Vg@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:89:442
ph@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:217:70
lh@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:126:411
O@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:121:71
ze@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14
mg/<@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53:49
unstable_runWithPriority@https://www.testbed.biz/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340
Ma@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:280
mg@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:498
V@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:431
Sb@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:213:96
Mg@https://www.testbed.biz/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:85:82
e@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:27833
Fe/</t<@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:27917
o/<@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:21839
o@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:21811
$/b</<@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:19038
p@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:11067
s/</</<@https://www.testbed.biz/wp-includes/js/dist/redux-routine.min.js?ver=9c464c6fba42fc0112f5feedb4939fa6:2:9797
I/</<@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:13059
N/</</<@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:13494
dispatch@https://www.testbed.biz/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:12792
n@https://www.testbed.biz/wp-includes/js/dist/redux-routine.min.js?ver=9c464c6fba42fc0112f5feedb4939fa6:2:9472
e/<@https://www.testbed.biz/wp-includes/js/dist/redux-routine.min.js?ver=9c464c6fba42fc0112f5feedb4939fa6:2:5224
e@https://www.testbed.biz/wp-includes/js/dist/redux-routine.min.js?ver=9c464c6fba42fc0112f5feedb4939fa6:2:5199
u/<@https://www.testbed.biz/wp-includes/js/dist/redux-routine.min.js?ver=9c464c6fba42fc0112f5feedb4939fa6:2:5153

**Comment by talldan** [comment]
@ACEkin The error message shows the error coming from the nextgen gallery plugin.

**Comment by ACEkin** [comment]
@talldan thank you for decoding the error message. One more thing to add to the original post is that this problem happens ONLY when editing JetPack Portfolio items whether there is any NextGEN Gallery attached or not. I can edit any post or page with or without NextGEN Gallery in them. If it is still not related to the block editor or JP Portfolios, I will report it to NextGEN team.
