### ISSUE TITLE
Remove Edit as HTML options from Toolbars for Legacy Widgets

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26300]
**Describe the bug**
Switching to HTML editing when there are legacy widgets shows nothing, and switching back causes the legacy widgets to lose their entire inner contents so they cannot be edited.

Reported in comments on [Widget Screen Call for Testing post](https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40089) by @helen

**Comment by draganescu** [comment]
I tried to test this but I can't find how to Switching to HTML editing. cc @helen any help would be appreciated.

**Comment by draganescu** [comment]
Actually I will close this as there is no "Edit as HTML options from Toolbars for Legacy Widgets" to remove:

<img width="894" alt="Screenshot 2020-11-10 at 12 49 35" src="https://user-images.githubusercontent.com/107534/98664634-4a418e00-2353-11eb-8483-d075ca4d4c95.png">
