### ISSUE TITLE
Remove Post Type Support not reflected in Gutenberg UI

### ISSUE THREAD

**Issue by designbuildtest** [WordPress/gutenberg#26306]
When I declare the below action, the "Custom fields" option is still accessible when choosing "Options" (vertical ellipsis) > "Options" > "Advanced panels".

```
function mytheme_remove_page_post_custom field_support() {
        remove_post_type_support( 'post', 'custom-fields' );
        remove_post_type_support( 'page', 'custom-fields' );
}
add_action( 'init', 'mytheme_remove_page_post_custom field_support' );
```

If I switch to the Classic Editor, this declaration is correctly honoured with all Custom fields UI removed.

Is the hook I'm using incorrect, or is this a bug? 

Gutenberg version 9.1.1

![remove-post-type-support-custom-fields-options-panel](https://user-images.githubusercontent.com/7623221/96859435-fd8a3600-14bd-11eb-99f6-cf92ef87d47f.jpg)

**Comment by skorasaurus** [comment]
confirmed in Gutenberg 9.5.2.

**Comment by jordesign** [comment]
I'm no longer able to recreate this in WP6.3. Option to show Custom fields is no longer shown in the preferences when they're disabled for post types.

Accordingly I'll close this as resolved.
