### ISSUE TITLE
Drag and drop: no indicator shows for images

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#26318]
**Describe the bug**
No indicator shows when dragging images into the Editor  

**To reproduce**
1. Go to file manager 
2. Drag files into the editor 
3. Observe absence of indication while dragging the images around the page

**Expected behavior**

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? Master

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by noisysocks** [comment]
I wasn't able to reproduce this. When I drag an image into the editor I see a horizontal blue line indicating where it will be placed.

**Comment by ellatrix** [comment]
Hm, I can't reproduce anymore either. Thanks!
