### ISSUE TITLE
Decouple Query/Post Block Experiment from Site Editor Experiment

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#26316]
It looks like the Query Blocks and suite of Post Blocks are currently gated behind the same experiment as Full-Site Editing. I'd like to propose that we decouple those two experiments allowing users to experiment with those separately.

I can see this being advantageous for users in at least one possible future scenario: the Query/Post Blocks being ready to leave their experimental status before the Site Editor, allowing users to create static pages with clever Post Loop layouts in the Block Editor.

**Comment by mtias** [comment]
This makes sense to me. There could be value in releasing some of these blocks in 5.7 as well ahead of site editing.

**Comment by simison** [comment]
Totally! For example people who build single-page sites using page editor might find this useful.

**Comment by GlennMartin1** [comment]
Any progress on this? I'd love to be able to use the Query block while keeping experiments turned off. Perhaps 9.4?

**Comment by skorasaurus** [comment]
Highly agree; I'm considering using the query block on my site but am not ready to go to FSE it.

**Comment by GlennMartin1** [comment]
@mtias What's the timeframe for moving forward on this?

(hopefully soon!)

**Comment by rmorse** [comment]
Just thought I would add on here some ideas about the query building UI - and if we decouple the this from FSE, does that introduce new use cases.

Would it be safe to say, users of FSE are advanced users, and therefor can handle more advanced query controls (and possibly *need* them)?

And would it be a fair assumption that blocks available for general use (ie intalled everywhere), might *need* to be more accessible, and possibly simpler, for most use cases (but of course, we'll still need the advanced stuff for advanced users)?

I see a query builder UI - one that in the end has most options of `WP_Query` - as an essential for site builders and FSE in the long run (you may disagree, I'm just thinking out loud), but I can see that being totally full on and overwhelming for most uses cases everywhere else.

Perhaps Im overthinking it - at the end of the day a Query is quite an advanced concept already...  But I'm starting to lean towards the idea that this will need to fullfill two use cases:

1) Site builders need more options and more technical query controls
2) The current query builder UI is probably technical enough (and pretty much functional enough) as it is for a most use cases and shouldn't get much more complicated

I think this could still be captured all in one block (by having a drill down to "advanced" controls or something similar) but thought I would mention on here as I think FSE implies advanced users will be using this, and bringing it out of there would surely target another set of users.

---

**Update**: I see this was somewhat touched on here:
https://make.wordpress.org/core/2021/04/15/full-site-editing-go-no-go-april-14-2021/

> This is potentially too powerful for users—you can edit everything from the blocks in this block. Flag was seconded.

I'll be keeping my eyes peeled on updates around this!

**Comment by ntsekouras** [comment]
Closing as this is tracked/handled here: https://github.com/WordPress/gutenberg/issues/28744
