### ISSUE TITLE
Widget Editor: "Widget Area" shown as the only category in the Inserter

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26329]
### Problem
I just noticed a weird experience when opening the Inserter panel. 

![Screen Shot 2020-10-20 at 9 34 40 AM](https://user-images.githubusercontent.com/617986/96616775-a0bd2e80-12b7-11eb-85ef-40f2bb8c3626.png)

I see a "Widget Area" category section there with an icon next to it, and I seem to have lost all other Inserter categories.

**Comment by mtias** [comment]
I ran into this as well here https://github.com/WordPress/gutenberg/issues/26101

**Comment by kevin940726** [comment]
Seems like a duplicate of #26159.

**Comment by draganescu** [comment]
This is a duplicated of #26159.
