### ISSUE TITLE
I should be able to drag and drop to replace media uploaded to the Media & Text block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#26320]
**Is your feature request related to a problem? Please describe.**
While we allow drag and drop functionality to image and gallery blocks, the Media & Text block does not allow it. 

**Screenshot**
![github](https://user-images.githubusercontent.com/1813435/96610736-f8649580-12c9-11eb-89fc-6e79614ef194.gif)

**Describe the solution you'd like**
A dropzone component that exists within the Media & Text block (only covering the media, not the text) where I can drag and drop an image, or video, to replace it. 

**Describe alternatives you've considered**

**Comment by paaljoachim** [comment]
This is pretty straight forward. I think we can go straight to needs a developer to get working.
I will also remove the "Needs Design Feedback" label.
