### ISSUE TITLE
Concurrency control in core-data

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#26325]
# The problem

While investigating https://github.com/WordPress/gutenberg/issues/22127, I discovered what appears to be a massive problem with API interactions in core-data.

**There seems to be no concept of concurrency control.**

A very simple example is that if I call `saveEntityRecord` twice on the same record, and it will spark two concurrent POST requests. One of them wins, but the client doesn't know which one. Similarly, I can trigger `saveEntityRecord` and `deleteEntityRecord` at the same time and the result will vary depending on the exact timing. That's not very common at the moment, but obvious in #22127.

Let's talk about a common problem. Consider this minimal component that renders some data retrieved using `getEntityRecords` and saves changes using `saveEntityRecord`:

https://github.com/samueljseay/gutenberg/blob/c852bee7ce33498c3ee7faca743fac9e473bb03c/test-plugins/core-data/js/index.js#L1-L57

## Fetching data

How does the resolution flow look like? To answer that question, I will use a chart since reasoning about timing issues without one is just too hard. Time flows **downwards**:

<img width="1353" alt="Zrzut ekranu 2020-10-21 o 11 07 15" src="https://user-images.githubusercontent.com/205419/96698675-b3a23280-138d-11eb-89cb-2c41029f4a44.png">

Easy peasy, first withSelect only gets an empty list because nothing is stored yet, then resolver kicks in asynchronously, talks to the API, updates the store, and the store re-runs withSelect handler once the data is available.

## Saving data

Each time the user clicks a checkbox, the component dispatches `saveEntityRecords()` and triggers the following chain of events:

<img width="1366" alt="Zrzut ekranu 2020-10-21 o 11 14 29" src="https://user-images.githubusercontent.com/205419/96700066-48596000-138f-11eb-92e6-8b2bdc99c399.png">

There's already a problem here, `saveEntityRecord()` calls `getRawEntityRecord()`, which doesn't consider the record with a specific id to be resolved even though a list of records from `/wp/v2/books` was loaded earlier on. Instead, a resolver is triggered, and an explicit GET request is issued to `/wp/v2/books/1` - that happens around the same time as the `PUT` request to persist changes. Depending on the timing of both, GET results could override the last `RECEIVE_ITEMS` triggered by `saveEntityRecord()`. In that case, the user would see some flickering on the screen, and the store would end up with stale data.

## Fetching and saving data combined

What is really interesting, though, is what happens when we combine fetching AND saving. Let's take a look:

<img width="1351" alt="Zrzut ekranu 2020-10-21 o 11 19 11" src="https://user-images.githubusercontent.com/205419/96700075-4abbba00-138f-11eb-9256-f151c5ee43bb.png">

Woah, that's a lot of arrows and boxes! What happens on that chart is:

1. We fetch the data first - just like on the very first chart in this issue.
2. The user triggers a save after the data is loaded - same as the second chart.
3. Transparent boxes are the interactions with `withSelect` as well.

This is pretty fragile - there are multiple requests started around the same time, and they may be resolved in any order. If  `GET /wp/v2/books` is resolved last, the store is stuck with stale data until the page is refreshed.

Batch processing is affected tenfold as more entity records in the mix means more timing issues.

# Possible solutions

## Atomic operations

I really don't like how `saveEntityRecord()` triggers a bunch of side effects while everything is still up in the air. And even if `saveEntityRecord` didn't, the user could. The point is that writes and reads mix together in unpredictable ways.

**A quick, immediate solution**

We could prevent concurrent conflicting operations:
* By not resolving while write operation is in progress
* Using locking (`shared lock` and `exclusive lock` maybe?). Selectors would "just work", but API reads (resolvers) and API writes would never run clashing operations at the same time.

Also, to reduce the number of factors in the mix we could apply optimistic updates a bit differently. Namely, instead of using `receiveEntityRecords`, we could leverage `editedEntityRecord` by just adding one more edit signifying a "checkpoint". It would work like this: 1. Edits before the checkpoint are frozen as long as the checkpoint is in place, 2. Successful save discards all the edits before the checkpoint and replaces the entity record with the server response 3. Failed save simply removes the checkpoint, no rollback is needed.

One other solution is to assume `core/data` is a low-level API that just does what it's told and shift the burden of concurrency control onto the consumer. As in: assume it's the developer's responsibility to avoid conflicting `select()` and `dispatch()` calls. Even in this scenario, `core/data` gets in its own way by triggering resolvers when it shouldn't. Also, the pitfalls are very generic so the logic implemented by each and every consumer would be almost the same. An alternative would be to build a higher-level API on top of `core/data` that would understand locking and concurrency.

**Long term considerations**

The above would solve the problem for now and may even suffice for a bit longer. It has some downsides though:

1. **Stacking multiple conflicting operations may take a long time to process**
2. It doesn't address conflict resolution, e.g. server receiving conflicting updates from another user. This would be really nice to address but it doesn't seem to be a blocker for now. These explorations could part of multi-user concurrent editing project too - it's a closely related problem and could potentially require rethinking how core data works. Here's a bunch of related acronyms that cold come handy later on: [MVVC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control), [OT](https://en.wikipedia.org/wiki/Operational_transformation), [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type).

While 1 could potentially be addressed by 2, there is another simple solution: squash enqueued operations when possible. E.g. if there are two updates waiting to be processed, we could perform just one. Thee updates and a delete? Perform only the delete.

## Re-use fetched data

* Selecting specific entity record could re-use one fetched earlier from the list API endpoint. As in `getEntityRecords( 'postType', 'book' );` followed by `getEntityRecords( 'postType', 'book', 4 );` could ideally trigger just a single request - the first one to `/wp/v2/books`. Ideally that would be the case even if the list request is still in progress.
* Alternatively, resolving a list of entity records could also resolve specific records, although I'm not sure if it would fix it entirely.

cc @youknowriad @mcsf @gziolo @draganescu @noisysocks @talldan @tellthemachines @kevin940726 @jorgefilipecosta @mtias @samueljseay @ellatrix @TimothyBJacobs

**Comment by adamziel** [comment]
Also, I'm acting as a reporter here, but I'm also happy to spin up a PR exploring a solution (or many PRs). But let's discuss first.

**Comment by adamziel** [comment]
I considered how different types of API interactions behave when concurrent:

### Concurrent API operations on two entity records

#### Same type, different IDs
<img width="536" alt="Zrzut ekranu 2020-10-21 o 12 26 11" src="https://user-images.githubusercontent.com/205419/96707777-9b83e080-1398-11eb-80dd-b405d6cbd8b6.png">

#### Same type, same ID
<img width="438" alt="Zrzut ekranu 2020-10-21 o 12 27 48" src="https://user-images.githubusercontent.com/205419/96707964-db4ac800-1398-11eb-8e9a-e92c58056ed2.png">

### Record operations vs list operations
<img width="647" alt="Zrzut ekranu 2020-10-21 o 12 27 05" src="https://user-images.githubusercontent.com/205419/96707889-bbb39f80-1398-11eb-9f3e-e037f939fe6a.png">

Conflicting as in we need to re-request the data after writes are finished:

<img width="523" alt="Zrzut ekranu 2020-10-21 o 12 27 14" src="https://user-images.githubusercontent.com/205419/96707912-c53d0780-1398-11eb-8000-3eb2b623ba4e.png">

**Comment by noisysocks** [comment]
Tough problem! Thanks for the clear write-up, though.

Are there any other libraries that we can look to for inspiration?

It sounds like we need to make it so that, instead of calling `apiFetch()` directly, actions like `getEntityRecord()` and `saveEntityRecord()` add an `apiFetch()` request to a queue. Each entity has its own queue. Requests in the queue are performed one at a time. Some subsequences of requests in the queue can be done in parallel, e.g. multiple `GET` requests. Some subsequences of requests in the queue can be collapsed into one request, e.g. multiple `PUT /books/1` requests.

> Stacking multiple conflicting operations may take a long time to process

How common is this? Maybe it's not such a bad trade-off.

**Comment by adamziel** [comment]
@noisysocks my thoughts exactly! Only I wouldn't enqueue just network requests, but everything asynchronous in the mix. If only network requests themselves are stacked, there are less possible outcomes, but there are still many possible outcomes when we consider concurrent operations. For example:

<img width="968" alt="Zrzut ekranu 2020-10-22 o 14 21 41" src="https://user-images.githubusercontent.com/205419/96870955-ec1b3c80-1471-11eb-86f8-d6aa5b695248.png">

Note how the failed operation overwritten the result of the successful one. I can come up with more example like that. The point is that to get rid of interferences. I would considering entire segments of code as "critical sections" or "atomic operations":

<img width="926" alt="Zrzut ekranu 2020-10-22 o 14 33 22" src="https://user-images.githubusercontent.com/205419/96872167-8def5900-1473-11eb-8722-3baa49fabfd2.png">

This makes things conceptually simple by taking all the asynchronicity out of the equation - interfering operations are always executed serially and the outcomes are easily predictable as nothing updates parts of the state they depend on.

**Comment by adamziel** [comment]
I'm exploring the idea of atomic operations and locks in https://github.com/WordPress/gutenberg/pull/26389

**Comment by adamziel** [comment]
Surfacing [this comment](https://github.com/WordPress/gutenberg/issues/22127#issuecomment-721067994) here:

> https://github.com/WordPress/gutenberg/pull/26627 and https://github.com/WordPress/gutenberg/pull/26575 improved the situation here. There is much less flickering, although there is still some of it as seen below:
> 
> ![core data issue](https://user-images.githubusercontent.com/205419/97978252-988fe380-1dcd-11eb-9d45-cb39d66b21ea.gif)
> 
> I think locks would be the ultimate solution here. The downside is that they would add a layer of complexity to an already complex core-data so I'm still trying to come up with some alternatives. But for reference, see the same interaction with https://github.com/WordPress/gutenberg/pull/26389 applied:
> 
> ![2020-11-03 12-41-39 2020-11-03 12_41_59](https://user-images.githubusercontent.com/205419/97981160-266dcd80-1dd2-11eb-8d52-71be2ef2957c.gif)

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/pull/26389 addressed the bulk of this problem. It would still be amazing to implement a lock-less solution or be more "optimistic" about different operations, but the bug part of this issue is now fixed 🎉
