### ISSUE TITLE
Gutenberg templates - Ability to restrict removal of template blocks

### ISSUE THREAD

**Issue by sc0ttkclark** [WordPress/gutenberg#2632]
I'd really like to be able to ensure a Gutenberg template is locked from modification. I'd like them to be able to add blocks around the template as necessary, but the template itself I'd like to have those blocks locked from being removed themselves.

Is there a config I should use for that, or is it not supported?

**Comment by mtias** [comment]
It's not yet supported, but makes total sense. I'd imagine it would be a `locked: true` prop during registration. The block would not get `movers` nor be deletable, but its content still editable. Would that match your need?

**Comment by BE-Webdesign** [comment]
I've been working on this for a client, and think I have come up with some reasonable ideas to implement block templates.

**Comment by sc0ttkclark** [comment]
Exactly! Also, the ability to lock the the whole template down from adding any new blocks. But that may be separate from this.

**Comment by sbangnielsen** [comment]
Great idea. What would be really superb though is if something like `position: bottom` or `position: top` could be added.

If it was possible to add obligatory, non-deletable, non-moveable blocks either above or below the content area it would be a big step towards enabling the replacement of all metaboxes with blocks.

**Comment by BE-Webdesign** [comment]
> position: bottom or position: top could be added.

This is not necessary.

**Comment by youknowriad** [comment]
I'm closing this in favor of #1684
