### ISSUE TITLE
Writing flow: Column: Horizontal multi-selection starting from text fails

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#26321]
**Describe the bug**
Column specific issue. Horizontal multi-selection fails.
**To reproduce**
1. Create a columns block
2. Add paragraph in both columns
3. Try to select from paragraph to paragraph 
4. Observe absence of multi selection

**Expected behavior**

**Screenshots**
<img width="798" alt="Screenshot 2020-10-20 at 17 28 18" src="https://user-images.githubusercontent.com/4710635/96611093-a4bf6f80-12fc-11eb-8670-19ba1a309c9f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? Master

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome & Firefox
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by Thelmachido** [comment]
I can reproduce this on Gutenberg 13.7.3 & WordPress 6.0.1

You can't select text from both paragraphs at the same time as shown below: 

https://user-images.githubusercontent.com/41231764/182572142-07bc540b-e0f1-43db-8207-38ab561a8abf.mov

**Comment by youknowriad** [comment]
I can't reproduce this anymore. The multi-selection triggers properly for me. There's no partial multi-selection though but I think that's ok.
