### ISSUE TITLE
No redirect to the "Revision Workflow" page after a revision is submitted

### ISSUE THREAD

**Issue by jduiella** [WordPress/gutenberg#26331]

**Comment by annezazu** [comment]
@jduiella I noticed you listed WordPress 5.4.1 as the version you ran into this problem with. Can you confirm that you can replicate this with WordPress 5.5.1?

**Comment by jduiella** [comment]
@annezazu The issue was actually caused by the Revisionary plugin. **Updating the Revisionary plugin to version 2.4.3 solved the issue**

**Comment by annezazu** [comment]
Amazing! Thank you for testing and following back up @jduiella. Great job sleuthing.
