### ISSUE TITLE
Image Block: Replacing a resized image from URL doesn't reset dimensions 

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#26333]
**To reproduce**
1. Create image block with external image
2. Resize the image
3. Replace with uploaded image
4. Observe old image dimensions are still applied

**Editor version (please complete the following information):**
- WordPress version: 5.5.1.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? Master

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by daddou-ma** [comment]
I made a PR which fixes this issue. [#26879](https://github.com/WordPress/gutenberg/pull/26879)
