### ISSUE TITLE
block patterns causing crash

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#26342]
**Describe the bug**
Hey, I'm trying to register a block pattern but the editor crashes when I open the block pattern menu
 
**To reproduce**
This is the pattern I'm registering:

```
register_block_pattern(
    'my-plugin/my-awesome-pattern',
    array(
        'title'       => __( 'Test', 'test-pattern' ),
        'content'     => "<!-- wp:paragraph -->\n<p>(Optional) Replace this text with a short description or remove it</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:list {\"ordered\":true} -->\n<ol><li>do this</li><li>then this</li><li>and this</li></ol>\n<!-- /wp:list -->",
    )
);
```

This is the error I'm getting:

TypeError: Cannot read property 'includes' of undefined
    at http://sitename.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=453327616318b3d4c6ae91099faa7134:32:1791
    at Array.some (<anonymous>)
    at http://sitename.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=453327616318b3d4c6ae91099faa7134:32:1753
    at Array.filter (<anonymous>)
    at http://sitename.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=453327616318b3d4c6ae91099faa7134:32:1724
    at Object.useMemo (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:216:441)
    at d.useMemo (http://sitename.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:32:231)
    at Kl (http://sitename.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=453327616318b3d4c6ae91099faa7134:32:1702)
    at we (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at zj (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:226:496)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
-Gutenberg v 9.1.1

**Desktop (please complete the following information):**
 - Centos
- Chrome

Cheers

**Comment by devfle** [comment]
Hi there 👋 

you also have to pass the keywords.

'keywords' => ['one', 'two'],

then it should work

**Comment by slimmilkduds** [comment]
Hey, thanks for the suggestion! Unfortunately it still leaves me with the same error, I've also updated to 9.2 since creating this issue

**Comment by slimmilkduds** [comment]
I've also tried disabling all plugins and custom things in function.php

**Comment by talldan** [comment]
@slimmilkduds I tried your demo code. It's working ok for me. Here's the pattern in the inserter:
<img width="347" alt="Screenshot 2020-10-22 at 4 01 27 pm" src="https://user-images.githubusercontent.com/677833/96842742-022ff980-1480-11eb-84be-96cb38ad572b.png">

I'll leave the issue open for a bit to see if anyone else can reproduce it.

**Comment by slimmilkduds** [comment]
Interesting, this is really strange I must say, it must be something on my end, but I can't for the life of me figure out what :)

**Comment by slimmilkduds** [comment]
Interesting, I found a tutorial online with a random pattern that I tried which worked, I can't tell the difference between what I have done but there's something, anyhow, I'll close this as it's obviously an issue on my side! Thanks for the help!

**Comment by skorasaurus** [comment]
A categories object is now required; I believe; for what it's worth.
