### ISSUE TITLE
Package `@wordpress/edit-post` assumes it will be installed at the same level than `@wordpress/interface`.

### ISSUE THREAD

**Issue by scinos** [WordPress/gutenberg#26343]
**Describe the bug**
Package `@wordpress/edit-post` assumes it will be installed at the same level than `@wordpress/interface`.

This is the problematic line https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/style.scss#L1

When the structure is

```
myApp
    - node_modules
        - @wordpress/edit-post
        - @wordpress/interface
```

Everything works as expected. However, this structure is also valid, specially in a monorepo (for example, if there are multiple versions of `@wordpress/edit-post`):

```
myApp
    - package
        - node_modules
            - @wordpress/edit-post
    - node_modules
        - @wordpress/interface
```

In that case, the path `"../../interface/src/style.scss";` won't resolve to anything.

**Comment by kathrynwp** [comment]
@scinos Hi! I see there's a PR that looks like it was merged a while back. Can this issue be closed now? Thanks for taking a look.

**Comment by kathrynwp** [comment]
And if that PR is not related, if you wouldn't mind confirming whether the original issue is still valid, that would be super helpful. Thanks!

**Comment by youknowriad** [comment]
I think the main issue here is that you're trying to load the "source" of "edit-post" component rather than the output where "interface" style is included (and not imported).

That said today, it's the editor package that depends on interface and not edit-post, so this issue is not relevant anymore.
