### ISSUE TITLE
Image block missing drop down menu

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#26354]
**Describe the bug**
The dropdown menu described in the documentation here - https://wordpress.com/support/wordpress-editor/blocks/image-block/#resize-images
Screenshot - https://d.pr/i/QCs2cc
Appears sometimes in the block settings for some images but not others
Screenshot - https://d.pr/i/2fzDyF

**To reproduce**
* Go to https://wordpress.com/post/learnxtravel.com/5128
* Scroll down to the final 2 images
* One of these shows the dropdown menu, the second one doesn't
* Both appear to be identical in default image blocks
* I copied the entire page code to a test site and neither images now shows the drop down menu at all.
* Could it be related to - https://github.com/WordPress/gutenberg/issues/12762

**Expected behavior**
The dropdown menu to appear

Theme: Karuna

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@rickmgithub Thanks for reporting. The site you linked in steps to reproduce appears to be for a WordPress.com account. I'm not sure how that's supposed to be accessible for members of the WordPress community that contribute to this project.

When uploading an image, WordPress creates different size variations of an image, and this dropdown is what allows users to switch between them. If those variations aren't created the dropdown won't be shown.

That can happen if the uploaded image is already a small size (and so there aren't any smaller sizes that can be created), but could also happen if the images are created another way (like via an import).

As an example, I took a tiny screenshot of my desktop and uploaded that and the dimension options were missing:
<img width="271" alt="Screenshot 2020-10-22 at 3 49 15 pm" src="https://user-images.githubusercontent.com/677833/96841370-4de1a380-147e-11eb-891a-c13127759420.png">

I'll close the issue given the explanation
