### ISSUE TITLE
Limited to 10 reusable blocks in 9.2.0

### ISSUE THREAD

**Issue by IrishTom** [WordPress/gutenberg#26352]
I've just updated to 9.2.0 and now I can only see the 10 most recent reusable blocks in my page/post editor. 

If I disable the plugin they all appear again.

**Comment by khristiansnyder** [comment]
I ran into this today as well, with only 10 blocks showing in the editor.

**Comment by fashuvo** [comment]
A user reported this in #3444312-zen.

**Comment by talldan** [comment]
@fashuvo What's a #3444312-zen?
