### ISSUE TITLE
 Use of undefined constants STYLESHEETPATH and TEMPLATEPATH PHP warning

### ISSUE THREAD

**Issue by david-binda** [WordPress/gutenberg#26359]
**Describe the bug**
The Gutenberg's Global Styles feature is throwing following PHP warnings in curtomizer context on some requests:

```
Warning: Use of undefined constant STYLESHEETPATH - assumed 'STYLESHEETPATH' (this will throw an Error in a future version of PHP) in /srv/www/wordpress-default/public_html/wp-includes/template.php on line 663
Warning: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' (this will throw an Error in a future version of PHP) in /srv/www/wordpress-default/public_html/wp-includes/template.php on line 666
```

This is caused by the call of the `locate_template` in

https://github.com/WordPress/gutenberg/blob/9ce9380681c5c02caed074fbe1539b2174b18319/lib/global-styles.php#L14

which is being hooked to the `wp_enqueue_scripts` action via some function chain in

https://github.com/WordPress/gutenberg/blob/9ce9380681c5c02caed074fbe1539b2174b18319/lib/global-styles.php#L979

However, the WordPress customizer may call the `wp_enqueue_scripts` prior setting up a theme and defining the templating constants ( `STYLESHEETPATH`, `TEMPLATEPATH` ) in case a user w/o necessary capabilities for switching theme is attempting to review a customizer changeset. Customizer is hooking the `setup_theme` action and eventually dying. See:

https://github.com/WordPress/WordPress/blob/a7d6e929c96f2d1e6e0307e781d36c338b8bf877/wp-includes/class-wp-customize-manager.php#L366 and https://github.com/WordPress/WordPress/blob/a7d6e929c96f2d1e6e0307e781d36c338b8bf877/wp-includes/class-wp-customize-manager.php#L505

**To reproduce**
1. Go to a customizer screen of your site under a user account with all appropriate caps needed for making changes in customizer
2. Make any changes ( does not really matter which ones ), but don't publish those
3. Copy the customizer preview iframe URL ( should be something like: `?customize_changeset_uuid=c0af4551-5b8c-4260-ad4e-368af589c737&customize_theme=twentyseventeen&customize_messenger_channel=preview-0` )
4. Open the copied URL while logged in as a subscriber (or any other user w/o switch_themes capability)
5. Notice the PHP warning

**Expected behavior**
No PHP warning

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it? 920

**Comment by ockham** [comment]
This _might_ have been fixed by #27021. I'll defer to @Addison-Stavlo as to whether we can close this issue.

**Comment by Addison-Stavlo** [comment]
I think this is unrelated.  My change didn't touch the functions noted above, also I don't think the function I changed even existed 29 days ago.

is this still happening?

**Comment by nosolosw** [comment]
This was discussed in [this thread](https://github.com/WordPress/gutenberg/pull/28410#discussion_r568727198) and there's a [path forward](https://github.com/WordPress/gutenberg/pull/28410#discussion_r572847813) to fix it, in case anyone is interested in picking this up.

**Comment by nosolosw** [comment]
I couldn't repro this error. However, in https://github.com/WordPress/gutenberg/pull/28942 we're replacing `locate_template` by something else, so it arguably fixes this.
