### ISSUE TITLE
Inspector disappears when the block inserter is opened

### ISSUE THREAD

**Issue by thatdevgirl** [WordPress/gutenberg#26363]
**Describe the bug**
When editing a page or post, the Inspector Panel disappears when the block inserter is opened. The Inspector Panel does not reopen when the block inserter is closed. This behavior is confusing. I would expect that the Inspector Panel should stay open unless it is intentionally closed by the user. 

**To reproduce**
1. Edit or add a new page or post.
2. Add content to the page. Open the Inspector Panel by toggling the "Settings" icon in the upper right corner of the editor, if the Inspector Panel is not already open.
3. Open the block inserter. 
4. Note that the Inspector Panel is closed.
5. Close the block inserter.
6. Note that the Inspector Panel is still closed. (You can reopen it manually, but it does not automatically come back.)

**Expected behavior**

I expect that the Inspector Panel remains open when the block inserter is opened. Opening one should not close the other.

**Screenshots**
![Inspector-close-issue](https://user-images.githubusercontent.com/5687778/96740353-c2d5b000-138e-11eb-9969-1ed2e3daf9a9.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- No plugins are activated
- TwentyTwenty theme is activated.

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina (10.15.7)
 - Browser: Chrome (latest)

**Comment by talldan** [comment]
There are some previous reports, #22525 and #23968, so I'm going to close this one as a duplicate. Thanks for reporting the issue, though.
