### ISSUE TITLE
Adding a Gallery block breaks the editor's undo button

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#26367]
**Describe the bug**

Adding a Gallery block breaks the editor's undo button.

**To reproduce**
1. Add a gallery block
2. Try to use Undo

**Expected behavior**
Undo should revert the addition of the gallery block

**Screenshots**

| <img width="500" alt="gallery block not undone on web" src="https://user-images.githubusercontent.com/1898325/96758510-3f778700-13ad-11eb-8a03-13338daa7042.gif"> |
| - |

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Firefox
 - Version 81.0.2

**Comment by talldan** [comment]
This seems like a pretty bad bug, so I've added it to the 5.6 Must Haves board.
