### ISSUE TITLE
Get InnerBlocks content in the render function in php

### ISSUE THREAD

**Issue by rosa-hai** [WordPress/gutenberg#26384]
Hi,
I'd like to use InnerBlock in my custom plugin created dynamically. I'm using the edit function in js to render in the editor and the render function in the php file to render in front. I can pass attributes between the two functions but I don't know how to pass the InnerBlock content to the php file. I searched and only found answers using the save function in js. Is it possible to pass the InnerBlock content to php?

Thanks

**Comment by talldan** [comment]
Hi @rosa-hai,

I don't think this is documented yet, but you should be able to use a third `$block` argument in your render callback. An example of this is the navigation block in the Gutenberg plugin:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation/index.php#L106

You can then loop through the `inner_blocks` property and render each block:
https://github.com/WordPress/gutenberg/blob/b0a5e0680158bc6dc3ee6c6aeb0c1eaa1e290702/packages/block-library/src/navigation/index.php#L137-L140

**Comment by rosa-hai** [comment]
Oh yes I'll have a look thanks!
