### ISSUE TITLE
I should be able to drag and drop an image as the Cover block's background

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#26388]
**Is your feature request related to a problem? Please describe.**
We currently have a few inconsistencies with media uploaders, one of which is the dropzone upload/replace flow that exists within the core image/gallery and soon to be Media & Text block. We should consider adding that same drop zone/replace functionality to the Cover block, as it exists in each other instance of media blocks.

**Screenshot**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/96867003-27017e00-143a-11eb-860a-e162f0654d9d.gif)

**Describe the solution you'd like**
When dragging an image/video over the left or right area of the cover block (the areas not managed via InnerBlocks component), I can drop it in and the media is assigned as the Cover block's background media.

**Describe alternatives you've considered**
None, other than having to different edit flow for this block, compared to other image/gallery blocks.

**Comment by aristath** [comment]
Hmmm an image block, a gallery and text/media all have 1 thing in common: They have a single image.
The cover block however can have multiple. You can add a background image to the block itself, and then add a nested image block inside it to create cool effect when using images with transparencies etc.
I don't think that dropping an image to the cover block should add that image as its background... It's equally reasonable to expect that dropping an image to the cover block will create a new image block inside the cover container.

**Comment by mtias** [comment]
@ItsJonQ @jasmussen perhaps you have some thoughts on how we could communicate different drop zones here. We'd need to clearly discriminate between:

- Changing the background.
- Inserting a new image block within the cover (the blue horizontal lines).
- Replacing an existing block image or adding to an existing gallery block within _Cover_.

**Comment by jasmussen** [comment]
Cool.

We have this big blue and obvious background change for Image blocks:

<img width="998" alt="Screenshot 2020-10-26 at 09 40 13" src="https://user-images.githubusercontent.com/1204802/97151066-4b799500-176f-11eb-8a1f-96c69fabe48e.png">

And in this specific case of the Cover image, the contents inside don't actually take up all the space — so we could presumably know fairly well what's background and what's content:

<img width="1016" alt="Screenshot 2020-10-26 at 09 31 53" src="https://user-images.githubusercontent.com/1204802/97151151-63e9af80-176f-11eb-9dfd-930dc2dd8d56.png">

So we could do this:

![Screenshot-2020-10-26-at-09 33 10](https://user-images.githubusercontent.com/1204802/97151178-6cda8100-176f-11eb-8ae7-809b5150b640.png)

👆 that is, when you drag/drop an image over the cover block and aren't touching any of the dropzones near the content, a thick 48px stroke animates in and shows a little message in the top left corner, that you can drop to set the background.

**Comment by richtabor** [comment]
I like that idea!

**Comment by paaljoachim** [comment]
Here is an animated version.

![Cover-block-drop-images](https://user-images.githubusercontent.com/5323259/97276811-fc4b6700-1837-11eb-8b5c-209c5275f8be.gif)

Made in Figma.
https://www.figma.com/proto/4jfqewskR78oPiWUcEdW8k/Untitled?node-id=1%3A2&scaling=min-zoom

**Comment by jasmussen** [comment]
Thanks for the animated GIF. Outside of some of the metrics/font sizes/border widths, the general behavior was the one I was thinking!
