### ISSUE TITLE
Prefix and suffix handling in template tag blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26393]
A consistent pattern for handling the manipulation of plain text around the data in blocks like the Post Categories, Post Tags, Post Comments Count, etc is looking like something we might need for theme development.

Let's look at Post Tags for an example. Inserting this block will display all the post tags on the Canvas like so:

<img src="https://cldup.com/eool3gyAW6-3000x3000.png" width="200">

Now lets zoom in on the design of the Post template in Twenty Twentyone:

<img src="https://cldup.com/P3BGzV4s1P-3000x3000.png" width="200" />

Here we see a need to add a "Tagged" prefix/label on this block.

### What we have now

The Post Author block currently includes an affordance similar to this, for adding a byline:

![1](https://cldup.com/vDdfrQfMXh.gif)

It's a little clunky to use (things jump around when you select the block), and perhaps too opinionated in terms of design (what if I want the byline below the username?).

Since so many of these blocks will require this functionality – see "Categorized as" in the twentytwentyone screenshot above for another example – it might be beneficial to design a consistent pattern that can be used by all.

It should be noted that there is a delicate balance to be struck here between giving folks an acceptable level of control, whilst avoiding the need to create innerblocks.

**Comment by jameskoster** [comment]
Possibly a duplicate of #25448 🙈

**Comment by annezazu** [comment]
Agreed that #25448 seems similar enough for this to be considered a duplicate :D Mind commenting with your feedback there to consolidate? Going to close this out for now unless you think it's different enough that it should remain open!
