### ISSUE TITLE
I should be able to preview block transforms before applying them

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#26399]
**Is your feature request related to a problem? Please describe.**
The only way to know what a block transform does to your block is to apply it, then undo the transformation if it doesn't work out. This is not an idea experience, and what could have been delightful has instead turned into a frustration moment. 

**Describe the solution you'd like**
A preview of the transform is available by hovering over each transform. This way I can see what my block will look like before I transform it. 

![ScreenFlow](https://user-images.githubusercontent.com/1813435/96913846-2edd1480-1472-11eb-9403-6effbb91c279.gif)

**Describe alternatives you've considered**
None.

**Comment by fabiankaegy** [comment]
This would actually be a great improvement :) Thanks for the suggestion! Would love to see this becoming implemented.

**Comment by gravnetic** [comment]
I feel that the current implementation of transform objects in the aside is awkward for users.  Not only do the standard image transforms look unpolished, they do not inform the intent well, take up way too much UI real-estate, and results often don't reflect the change without adjustment (a second or third action) by the users in the editor.

**Comment by conanliuhuan** [comment]
Some block transform may lost attributes data, we should have some hooks such as "before_transform" to give users some alerts so that they could choose transform or not.
