### ISSUE TITLE
Add documentation for dynamic blocks

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26409]
**Is your feature request related to a problem? Please describe.**
The editor handbook is currently very brief on how dynamic blocks work.

Adding some extra documentation would be helpful for developers. In particular:
- When should a dynamic block be used?
- How to register a dynamic block?
- How to use `inner_blocks`?
- Some extra detail on particular aspects like block context.

**Comment by skorasaurus** [comment]
started at https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/creating-dynamic-blocks/
