### ISSUE TITLE
Excessive minimum 200px height in Shortcode block

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#26410]
Hey

I actually thought this was an issue with my theme, but it appears to be a - maybe deliberate - design choice. There is a 200px min height on the shortcode block. Please see attached screenshot. That does appear odd, especially in context with other blocks that have a height that fits their content. Removing the min-height style, looks a lot nice in my opinion. 

![excessive height on some blocks](https://user-images.githubusercontent.com/17141205/96975741-31477900-151b-11eb-95cc-8ac9205164d2.png)

Kind regards
Bjarne

**Comment by ntsekouras** [comment]
Hey @oldrup - thanks for the suggestion! Maybe @jasmussen is better to share his thoughts here.

**Comment by jasmussen** [comment]
Nice one! I created #26456 to fix it.
