### ISSUE TITLE
When pasting content in table cell it ends up in incorrect cell

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2643]
## Issue Overview
You can double-click on a table cell to highlight it's content. When doing this though, with the intention of pasting content over the top of the highlighted text, the content you paste ends up in the top-left cell (i.e. the first cell), rather than the cell you actually highlighted. In other words, when pasting content, it doesn't go into the correct cell.

The behavious seemed inconsistent too. A couple of times pasting text worked as expected, but for about 98% of the time it didn't.

## Steps to Reproduce (for bugs)
1. Copy some text from somewhere (doesn't matter where from, just have some content in your clipboard)
2. Create a table (my gif example was 3x2)
3. Double click on a cell (other than the very top-left cell) to highlight all the content in that cell
4. Hit Command-V (Ctrl-V) on your keyboard to paste over the highlighted content
5. Pasted text ends up in top-left cell rather than in the cell where the text was highlighted (i.e. It ends up in the wrong cell)

## Expected Behavior
Pasted text should always replace the currently highlighted text

## Current Behavior
Pasted text ends up in a completely different cell to the text that was actually highlighted

![tablecopypaste](https://user-images.githubusercontent.com/2078245/29993777-efd45ab4-9003-11e7-8c64-b5bcce6820d8.gif)

_Using Firefox 55.0.3 (64-bit) on osSierra 10.12.1
Gutenberg Version 1.0.0_

**Comment by karmatosed** [comment]
I am unable to replicate this on the current version, it may be this is resolved - it also may not be. For now, I am going to close but if you are still experiencing this please let us know.

**Comment by maddisondesigns** [comment]
@karmatosed This is still happening. Can you please reopen this one. Thanks.

**Comment by karmatosed** [comment]
Ah ok, was there a particular browser you were using?

**Comment by maddisondesigns** [comment]
I was using Firefox 55.0.3 (64-bit) on macOS Sierra v10.12.1 when I retested this issue earlier today.

When I originally submitted the issue I would've been using a slightly earlier FF version

**Comment by mtias** [comment]
I cannot reproduce this either.

**Comment by maddisondesigns** [comment]
I've just retested this and it now seems to be working ok. Obviously some change you've made in the background seems to have fixed the issue. Feel free to close it if you want and I'll re-open if I come across the issue again.
