### ISSUE TITLE
Dynamic blocks no longer rendering with their wrapper classnames on the frontend

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26441]
**Describe the bug**
Since https://github.com/WordPress/gutenberg/pull/26356 was merged, dynamic blocks no longer render with the `wp-block-blockname` class on their wrappers

**To reproduce**
1. Add a dynamic block (like Search)
2. Preview the post
3. Inspect the block and notice that the `wp-block-search` classname is missing.
4. Some blocks may not be styled correctly due to the missing classname

**Expected behavior**
The `wp-block-search` classname is retained.

**Screenshots**
#### Search block with the wrapper class
<img width="651" alt="Screenshot 2020-10-26 at 2 19 29 pm" src="https://user-images.githubusercontent.com/677833/97139839-572c8200-1796-11eb-9744-523237efbd74.png">

#### Search block without the wrapper class
<img width="470" alt="Screenshot 2020-10-26 at 2 19 12 pm" src="https://user-images.githubusercontent.com/677833/97139860-67dcf800-1796-11eb-81da-7519b16b0ede.png">

**Comment by talldan** [comment]
This is possibly fixed by https://github.com/WordPress/wordpress-develop/pull/640, but I'm not completely sure.

**Comment by talldan** [comment]
Just to confirm why it was closed, this is fixed by WordPress/wordpress-develop#640.

**Comment by nosolosw** [comment]
@tellthemachines for awareness.

As far as my testing goes, this error was only reproducible with WordPress 5.6 beta1 + Gutenberg master. The variations I've tested are:

WP 5.6 beta1, no gutenberg plugin => fine.
WP 5.6 beta1, gutenberg 9.2.1 => fine.
WP 5.6 beta1, gutenberg master => no class attached + errors.

WP 5.6 beta1 + https://github.com/WordPress/wordpress-develop/pull/640, no gutenberg => fine.
WP 5.6 beta1 + https://github.com/WordPress/wordpress-develop/pull/640, gutenberg 9.2.1 => fine.
WP 5.6 beta1 + https://github.com/WordPress/wordpress-develop/pull/640, gutenberg master => fine.

WP 5.5, no gutenberg => fine.
WP 5.5, gutenberg 9.2.1 => fine.
WP 5.5, gutenberg master => fine.

**Comment by nosolosw** [comment]
For full context: it turns out that in the widget screen (preview widgets) the issue can be reproduced with 5.5.1 and Gutenberg 9.2.1, see https://github.com/WordPress/gutenberg/issues/26420 For this to be fixed it needs https://github.com/WordPress/gutenberg/pull/26417

**Comment by tellthemachines** [comment]
Thanks, @nosolosw !
