### ISSUE TITLE
widgets don't appear on my widgets page

### ISSUE THREAD

**Issue by Lauralia** [WordPress/gutenberg#26449]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by annezazu** [comment]
@Lauralia thanks for reaching out although I'm bummed you're having problems with the widget screen. Looking over the information you provided, I'm afraid I don't have enough to make this actionable. Can you please provide steps to replicate as well as specific widgets you aren't seeing? If possible, screenshots would be very helpful to include as well. [Here's information](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) about how to include screenshots in this issue. Thanks in advance!

**Comment by draganescu** [comment]
I will close this issue based on having too little information and no reporter feedback. @Lauralia please feel free to comment and we can reopen it.
