### ISSUE TITLE
Gutenberg doesn't allow for pages with Sidebars

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2645]
Gutenberg seems to be only targeted towards full width, or single column layouts.

Besides the fact that you can't currently select a different page template (and yep, I know there's a discussion about this in another ticket), if you have a typical blog page with two columns (main content & sidebar), it's most likely not going to be of any use to be able to select _Wide_ or _Full Width_ images, for example.

Are there currently any discussions going on about how this is going to be handled? Are we going to be able to limit what controls each block has, based on the page template selected and/or Post/Page type currently being edited?

For the average single column Page, the ability to be able to select _Wide_ or _Full-Width_ images that extend outside the main column width, makes sense. When it comes to the blog layout though, there's an awful lot of themes out there that allow you to select different types of layouts. From single column layouts to multi-column layouts where you have the main content area and one or more sidebars. There needs to be an easy way for theme developers to be able to limit what controls are available for every block otherwise what people see when editing their content is going to completely different to what they actually see when they view the published page.

Most page builders out there handle this type of situation as you can create multi-row, multi-column layouts. You can choose whether you want the page to be 60/40 or 25/25/25/25 or 100% widths, giving you the flexibility to be able to have some pages with one or more sidebar columns and others with more complex layouts.

Gutenberg seems to be stuck in the middle of not being a proper "page-builder" because it doesn't have multi-column support, and at the same time, making it messy when themes want to provide multiple types of page layouts. At least with the current editor, you have a pretty good idea how the page will look based on the template you choose. Unless we can easily change how each block operates, then it's going to be very hit and miss with regards to what you see when editing your content and what you see on the front-end.

**Comment by samikeijonen** [comment]
> Are there currently any discussions going on about how this is going to be handled?

There is already `add_theme_support` method for this. You're absolutely correct, Gutenberg by default can't really know the theme design.

Here is [example for wide images](https://github.com/WordPress/gutenberg-theme/blob/master/functions.php#L66).

**Comment by maddisondesigns** [comment]
@samikeijonen Yeah, I know about the `add_theme_support()` functionality. What about when the template option is (finally) available when edting pages. If you switch from a full-width template to one that has a sidebar, unless there's some way to turn that support off, then the `after_setup_theme` hook isn't going to run again until the page actually refreshes (as it obviously doesn't currently run when simply changing template names in a dropdown).

On a side note: Setting `'wide-images' => true` with `add_theme_support()` when that option actually applies to other controls such as tables (as well as images), makes no sense. It should be something more generic like `'wide-controls' => true`.

**Comment by karmatosed** [comment]
A few things to note on this.

- Gutenberg is focusing on the editor not the page building part. That will come with the Customization focus.
- Any theme that has >1 column is totally supported right now. It's what happens to elements.
- Right now it's up to the themes for supporting the extra 'theme support' pieces.

With all this said, I think closing this issue makes sense. That's not saying we don't need to still explore and work on more/easier theme support. But, it does work on themes with >1 column.
