### ISSUE TITLE
Indicate customized templates in the site editor navigation

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26451]
Let's use the blue dot + tooltip pattern to indicate whether a theme template has been customised by a user:

<img src="https://cldup.com/PEd3OAMsRf.png" width="180" />

This will align with the latest designs we have for other areas of the UI. E.G. [Template Reverting](https://github.com/WordPress/gutenberg/issues/23421#issuecomment-711960167).

**Comment by vindl** [comment]
Closing this based on the discussion and decision here https://github.com/WordPress/gutenberg/pull/27041#issuecomment-731074109. We'll replace this work with https://github.com/WordPress/gutenberg/issues/23421#issuecomment-711960167.
