### ISSUE TITLE
Starting a drag in a widget area jumps me to the middle of that area

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26467]
### Problem
When beginning a drag in a widget area that has lots of blocks, the drag jumps me to the middle of that area instead of just staying where I began the drag.

**Example of problem**
![drag](https://user-images.githubusercontent.com/617986/97216517-31e24880-1783-11eb-98f6-d0214c5e8462.gif)

### Solution
Don't force the user to jump to the middle of the area.

**Comment by kevin940726** [comment]
I can't reproduce this anymore on master.
