### ISSUE TITLE
Bogus undo and unsaved changes notification

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26468]
### Problem
After updating the Widget Screen, I then reloaded the page (SHIFT + CMD + R) and got a notification that any unsaved changes will not be saved. But I already saved everything when I updated, right? But even though I reload the screen, I still see my change was indeed saved. So I'm not sure which changes the notification is implying.

**Example of problem**
![not-saving](https://user-images.githubusercontent.com/617986/97217109-0318a200-1784-11eb-9bbe-544b0f260c3c.gif)

### Solution
The "Update" button should save all changes and reloading a newly updated screen should not prompt the notification that there are unsaved changes.

**Comment by draganescu** [comment]
I can confirm that the "dirty" state is sometimes triggered even if no change happened such as trying to drag some widget but quitting in the middle of the action.

**Comment by Mamaduka** [comment]
Sometimes I've to double click the "Update" button for it to be disabled and indicated that changes were saved. It is probably related to "dirty" state issues.
