### ISSUE TITLE
Drag to select doesn't kick in until the third block

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2646]
## Expected Behavior
When I start selecting text inside a paragraph block and drag down, into the next block, that block should become selected as well.

## Current Behavior
This doesn't happen until you reach the third block while dragging. If you then drag up again without letting go of the mouse button, you can reduce the selection to two blocks, but you cannot start with just two blocks selected.

![select](https://user-images.githubusercontent.com/6073772/29994440-77b09892-8fcf-11e7-8497-e22b84e3b7f1.gif)

**Comment by karmatosed** [comment]
I can replicate this in Chrome. Thanks for reporting!
