### ISSUE TITLE
Text issues when switching a widget in the Legacy Widget block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26469]
### Problem
After clicking the "Change widget" button in the Legacy Widget toolbar, the Placeholder screen displays some text issues.

1. The block's description appears to be cut off ending in an ellipses.
2. A "g" is being cut off at the bottom in the selectbox.
3. After clicking the "Change widget" button, any highlight indicating focus is also lost. This should either remain on the block still, or highlight the selectbox as the next action to take.

**Example of problem**

![switch-widget](https://user-images.githubusercontent.com/617986/97218315-c3eb5080-1785-11eb-83cc-b37642b63d7a.gif)

**Comment by tellthemachines** [comment]
I can no longer reproduce the label text issue. The bottom of the "g" getting cut off happens also when adding a new Legacy Widget but it's not specific to this block; see #27194. Closing as widgets-relevant issue is fixed.
