### ISSUE TITLE
When widget form is empty the Legacy Widget "Preview" doesn't have enough info to display anything

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26473]
### Problem
Many 3rd party widgets require a form to be filled out before the widget can output anything. But the Legacy Widget block offers a "Preview" button even if nothing is filled out. Clicking this "Preview" button just shows an empty preview. This doesn't help explain to the user what needs to be done.

**Example of problem**
![blank-preview](https://user-images.githubusercontent.com/617986/97220920-7a046980-1789-11eb-8bda-5c401a587a20.gif)

### Solution
We could try a couple different things here.

1. Disable the "Preview" option until there is enough information filled out to display something.
2. Provide some messaging in the Preview that tells the user that it requires more info before displaying anything.

**Comment by paaljoachim** [comment]
Hey Mark. @mapk 

Good idea!
The "Preview" button can initially be disabled. Greyed out perhaps when there is nothing to preview. When the user adds something the button stops being greyed out giving the signal to the user that there is now some content that can be previewed.

**Comment by shaunandrews** [comment]
I touched on the "empty widget" issue in this comment: https://github.com/WordPress/gutenberg/issues/26179#issuecomment-765631524

Basically, I think an "empty" widget should just default to always showing its editing UI until any requirements are met to display a widget. In the scenario where there would never be a widget (is this a real scenario?) then it would always display the editing UI.

**Comment by draganescu** [comment]
I think https://github.com/WordPress/gutenberg/issues/26179#issuecomment-765631524 closes this by solving it in the proposal.
