### ISSUE TITLE
Still takes two clicks to open a Widget Area

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26470]
### Problem
When a block is selected in a widget area, it still takes two clicks to open another widget area. 

Tested on Chrome browser.

**Example of problem**
![two-clicks](https://user-images.githubusercontent.com/617986/97219550-6526d680-1787-11eb-80f6-cfd2c35d14e8.gif)

### Solution
It should only ever take one click to open a widget area.

**Comment by kevin940726** [comment]
I can't reproduce it on master anymore. Feel free to reopen this if this still happens, or suggesting that we should create tests for it (as it keeps coming back regularly).
