### ISSUE TITLE
Previewing the Legacy Widget does not work

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26474]
### Problem
I can't seem to preview anything in the Legacy Widget block while in the Widget Editor.

Tested on Chrome with Twenty Twenty theme.
Related: https://github.com/WordPress/gutenberg/issues/22838, https://github.com/WordPress/gutenberg/issues/26237

**Example of problem**
![previewing](https://user-images.githubusercontent.com/617986/97222015-f186c880-178a-11eb-80a1-6712f7c73dbb.gif)

**Comment by kevin940726** [comment]
Should be fixed in #29111.
