### ISSUE TITLE
Insertion indicator (blue line) is different weights in different areas

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26471]
### Problem
The insertion indicator (blue line) appears to be different weights in different widget areas.

Tested on Chrome browser with the Twenty Twenty theme.

**Example of problem**
![insertion-line](https://user-images.githubusercontent.com/617986/97220374-9eac1180-1788-11eb-878c-b3004ac4784a.gif)

**Comment by draganescu** [comment]
This does not seem to be a problem anymore. Thanks @mapk 🙇
