### ISSUE TITLE
Change Video block to allow Video embeds as well

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2648]
Currently the Video block only allows you to insert a video that you've uploaded to your site. This is going to be extremely confusing for people. 

One of the most common tasks that people do when blogging nowadays is inserting videos. A lot of the time, this is done by inserting a YouTube/Vimeo url.

The first thing that people are going to see after clicking +Insert and switching to the Blocks tab, is the Video block, when what they should actually be inserting is the Video Embed block. Most people aren't going to know the difference between the two, and they shouldn't have to either. All they want to do is to be able to insert a video.

The Video block should allow people to either select an uploaded video or insert a video URL.

**Comment by JoshuaMckendall** [comment]
I second this. Tumblr does this really well, maybe use their video upload/embed form as inspiration for the block?

**Default:** Upload or add from web
![video-upload-embed](https://user-images.githubusercontent.com/7562755/30006956-c72d05b8-90c9-11e7-9a8c-4056c42a2663.png)

**Add from web:**
![video-upload-embed-paste](https://user-images.githubusercontent.com/7562755/30006957-cceb087e-90c9-11e7-8a4f-00b304422e7c.png)

**Comment by notnownikki** [comment]
We do something similar with the audio block already, you can either insert from your media library, or enter a URL. Makes sense to have video work this way too.

**Comment by karmatosed** [comment]
I would +1 making it like the audio block, it makes sense to unify.

**Comment by mtias** [comment]
Closing in favor of #3386.
