### ISSUE TITLE
Button component: button size is not the same as default WordPress buttons

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#26493]
Hi,

I'm using Gutenberg components to create a custom settings page, and I notice that the `Button` component is larger than the default WordPress buttons. Here is the screenshot:

![](https://i.imgur.com/6XWDFku.png)

(Above is the `Button` component, below are 2 normal WordPress buttons).

It's best to make it the same size as in other places. In the Gutenberg editor, we still can use some CSS to adjust the buttons in some places.

**Comment by talldan** [comment]
WordPress core buttons are pretty inconsistently sized, there's 26px, 30px, and 32px buttons that are fairly prominent, so I'm not sure what the default is 😅. Gutenberg seems to use 36px in most cases. 

I've added the `Needs Design Feedback` label, as I'm not aware of the full background on this.

**Comment by rilwis** [comment]
@talldan I got it. I think the standard size for WP button is either of these:

```
<button type="button" class="button button-primary">Button text</button>
<button type="button" class="button button-secondary">Button text</button>
```

`button`, `input` or `a` with class `button` have the same size - 30px. Maybe they're changed in some special locations, but in general, I think it's 30px.

**Comment by jordesign** [comment]
With no movement on this issue in almost 3 years, and lots of interface and component changes in that time I'm going to close this issue.

If it _is_ still a concern, it can be re-opened with a new comparison of current interface screenshots.

**Comment by rilwis** [comment]
@jordesign 

This is still a problem. Here is the screenshot of the 6.3 version:

![1](https://github.com/WordPress/gutenberg/assets/668274/4b2797c7-4969-4e81-92a8-4d4e7c4524be)

I request to reopen this issue.

**Comment by jordesign** [comment]
Thanks for following up @rilwis - I've re-opened it now.

**Comment by mirka** [comment]
The Button sizes in the Gutenberg have been considered in great detail (the latest which is #46734). You're right that component sizing has been all over the place (not just buttons), but we're now on the path to more consistency within the ecosystem. If anything, the Gutenberg design system is in the process of "trickling up" into WordPress core, for example with the [Data Views project](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+data+views+label%3A%22%5BFeature%5D+Data+Views%22).

There will continue to be some inconsistencies in the meantime, but we'll get there eventually 🙂
