### ISSUE TITLE
Site Editor: detect themes that support FSE

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#26503]
We need a way to detect whether currently active theme supports FSE. Based on this we can determine whether we want to show Site Editor menu item and probably other things that will depend on this down the road.

One way to do this would be to check for the presence of `block-templates` folders, and `index.html` template file, since I think this is a bare minimum needed to run the site editor.

In addition to this, themes could declare FSE support via tags.

**Comment by fklein-lu** [comment]
This is covered by #26500, see https://github.com/WordPress/gutenberg/pull/26500/files#diff-712eed50059e933caa20b56aa2ff8764eb05a7c19ae6f000aff72f4e44655d03R13
