### ISSUE TITLE
OptGroup in SelectControl

### ISSUE THREAD

**Issue by raghavnarang** [WordPress/gutenberg#26505]
**Description of feature request**
By checking the code of the SelectControl component. It seems that it doesn't support Optgroup tag to group the options of the select HTML element. 

**OptGroup Reference Link**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup 

**Proposed Solution**
It would be nice if we have OptGroup support in SelectControl component, by passing an array of groups and fields as a nested array in their respective Group.

https://github.com/WordPress/gutenberg/blob/38de8447fb00392bf7e43274a5714ced19e4d33b/packages/components/src/select-control/index.js#L112-L126

**Comment by talldan** [comment]
@raghavnarang The issue description is a bit brief, would you mind updating it with more information? Thanks.

**Comment by raghavnarang** [comment]
> @raghavnarang The issue description is a bit brief, would you mind updating it with more information? Thanks.

@talldan Issue description updated

**Comment by talldan** [comment]
Thanks!

**Comment by JohnRDOrazio** [comment]
I'm thinking something along these lines should introduce the possibility of optgroups:
https://github.com/JohnRDOrazio/gutenberg/pull/4/files

Usage would be like this:
```js
const MySelectControl = withState( {
    size: '50%',
} )( ( { size, setState } ) => (
    <SelectControl
        label="Size"
        value={ size }
        options={ [ 
            {
                label: 'Fruits',
                value: [
                    { label: 'Apples', value: 'apple' },
                    { label: 'Pears', value: 'pear' },
                    { label: 'Bananas', value: 'banana' }
                ]
            },
            {
                label: 'Vegetables',
                value: [
                    { label: 'Celery', value: 'celery' },
                    { label: 'Cucumber', value: 'cucumber' },
                    { label: 'Carrots', value: 'carrots' }
                ]
            }
        ] }
        onChange={ ( size ) => { setState( { size } ) } }
    />
) );
```

If the changes in the code look right, I could start a PR. But since I'm no expert in React, and I can't quite fully wrap my head around it yet not having much experience with it, I'm not sure if all the changes are right and I haven't tested them (since that would require compiling and whatnot, I don't have all that set up on my end).

**Comment by skorasaurus** [comment]
This has been fixed in https://github.com/WordPress/gutenberg/pull/29540 with an example at https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/select-control#development-guidelines 

Please reopen and comment if this incorrect.
