### ISSUE TITLE
Cover image block missing align classes

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2650]
When theme add support for `'wide-images' => true,` also Cover image block have setting to align block wide and full. But I don't see classes like `alignwide` or `alignfull` in the front end like I do for image block for example.

Am I missing something?

**Comment by karmatosed** [comment]
As cover-image is different (it would be full width by default), there is a style here you can use: .wp-block-cover-image. It doesn't have the alignment options because of that.

**Comment by samikeijonen** [comment]
But in the editor it has setting to be full width, wide, or same as content. Same should be possible in the front end.

**Comment by samikeijonen** [comment]
@karmatosed Can you re-open this?

1. If the cover image should always be full width and has only class `wp-block-cover-image` in the front end, in the back end there should not be options for Align right/left/center, Wide width, Full width
1. I'd still like to have option to have Wide width, Full width, and "Content" width for cover image also. And this would need classes in the front end.

**Comment by karmatosed** [comment]
I don't agree that a cover image should to be honest. We have that option with images.

**Comment by samikeijonen** [comment]
Then back-end options should be removed. I disagree though:)

**Comment by anarieldesign** [comment]
Hi,

I think this is important issue that needs some more attention, as it isn't user friendly. If, in the back end, users have options to choose from then these options should do something in the front end, if they don't, user will think that it is a bug. It'd be great to have the same options like for the Image, to be able to style it differently for the front end. If not, than it would be useful to remove the options from the back end.

Thanks,
Ana

**Comment by youknowriad** [comment]
Yep, I think this is probably just a small bug where the classes are not added in the `save` method of the cover image.

**Comment by anarieldesign** [comment]
That would be great, just to add different classes like for the Image feature :), this way we can style it differently within the theme
