### ISSUE TITLE
Empty paragraph in text column block

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2651]
When I add text column block (2,3, or 4 columns) I always get empty (`<p></p>`) paragraph in the front end. No matter how I try to write text in the admin.

**Comment by Kuckovic** [comment]
I have the same issue!
How can we get rid of this??

**Comment by youknowriad** [comment]
I can't reproduce this, can we have more context? steps to reproduce?

**Comment by samikeijonen** [comment]
1. Add Text Columns block.
1. Write text in the columns.
1. Save.
1. Check front end, and there are emply `<p>` tags.

```php
<section class="wp-block-text-columns alignundefined columns-2">
  <div class="wp-block-column">
    <p>This is it for me.</p>
    <p></p>
  </div>
  <div class="wp-block-column">
    <p>This is it for see.</p>
    <p></p>
  </div>
</section>
```

**Comment by afercia** [comment]
I'd also argue a `<section>` element is not appropriate in this case. Even a quick reading of the spec clarifies it pretty well: https://www.w3.org/TR/html51/sections.html#the-section-element

> The section element represents a generic section of a document or application. A section, in this context, is a **thematic grouping of content**. Each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element.
> ...
> Examples of sections would be chapters, the various tabbed pages in a tabbed dialog box, or the numbered sections of a thesis. A Web site’s home page could be split into sections for an introduction, news items, and contact information.

**Comment by samikeijonen** [comment]
In #2908 we are discussing about markup and changing to `<div>`.

But I still see the original issue, which is empty `<p></p>`.

**Comment by jorgefilipecosta** [comment]
This issue seems a bug in WordPress core, for example in the classic editor if we add this content:
  <div>
    <p>test</p>
  </div>
In the browser we get: 

<div>
 <p>test</p>
 </p></div>

Then the browser adds the missing opening tag. This seems like the root cause of this problem.

**Comment by noisysocks** [comment]
I'm unable to reproduce this bug in Gutenberg 2.7.

**Comment by samikeijonen** [comment]
Now `Enter` doesn't create new `<p>` but `<br>`.

Markup looks like this in the front end:

```html
<div class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>This is it.<br><br>And another one.<br>What, one line.</p>
	</div>
	<div class="wp-block-column">
		<p>This is it.<br>This is it.<br><br>It is.</p>
	</div>
</div>
```

That's not correct either.

**Comment by samikeijonen** [comment]
Is the above markup correct or should we close this? I personally feel it's weird that pressing `Enter` creates `<br>` and not new `<p>`.

**Comment by youknowriad** [comment]
In my testing, shift + Enter creates `<br>` but regular `Enter` creates new paragraphs.

**Comment by samikeijonen** [comment]
I was testing the plugin version, could be resolved in the master.

**Comment by ajitbohra** [comment]
Tested on master `Enter` creates `<br>`

**Comment by samikeijonen** [comment]
I confirm what @ajitbohra noted, this is still issue.

**Comment by samikeijonen** [comment]
> My gut feeling is to leave this as is because, hopefully, Columns will soon be stable enough for us to simply remove the Text Columns block.

That make sense.

**Comment by scamba** [comment]
To remove empty `<p></p>` i am positioned my cursor inside this possible paragrah and i pulse delete key until to get my real last element. Sorry for my english i hope this help anyone
