### ISSUE TITLE
Connect Gutenberg to Jetpack Publicize

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/gutenberg#2652]
## Issue Overview
Allow Gutenberg posts to be shared socially via Jetpack's Publicize

## Expected Behavior

Add the Jetpack Publicize options to the Gutenberg post settings

## Current Behavior

Currently this is not possible. I appreciate that this is probably not a priority now, but I'm logging it so that it's somewhere on the radar ;-)

**Comment by aaronjorbin** [comment]
Should this be opened in https://github.com/automattic/jetpack instead?  Gutenberg shouldn't be responsible for updating 3rd party plugins.

**Comment by jonathanbossenger** [comment]
@aaronjorbin good point, sorry I'm just trying to test Gutenberg as much as possible to help find issues. Will raise it there.
