### ISSUE TITLE
Gutenberg visual parser does not support style= CSS tag in figure tag and should

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#26536]
**Describe the bug**
When you create an image in Gutenberg and place it, the caption text shows to be centered. When previewed, the text is left aligned. You can even see this in the generated HTML:

`<figure class="alignleft size-large is-resized">`

Changing "alignleft" to "aligncenter" causes the HTML block to fail to parse and then be reverted. However, I quickly realized this alignment was for the image, not the text. So, I needed to style the text with CSS.

Adding the CSS `style=` tag to the `<figure>` tag also fails for the same parsing reason. However, the `<figure>` tag does and should support `style=` like so:

`<figure style="text-align: center" class="alignleft size-large is-resized">`

This CSS styling is valid and actually works correctly when previewed, but the Gutenberg visual parser will not convert the HTML block back into visual editing if `style=` is present.

Alternatively, because Gutenberg is supposed to be visually editable, it would be better to allow the text captions below the image block to be aligned and styled visually... which text alignment is not possible for captions today.

It seems that the alignment of the image in the article is likewise applied to the caption text and shouldn't be.

**To reproduce**

1. Create an image block
2. Align the image left
3. Add a caption
4. Notice that the caption is centered in the editor
5. Preview the image and notice the caption text is left aligned
6. Attempt to add `style=` to the`<figure>` tag to center this misaligned text
7. Click to convert back to visual editing and see a parsing failure

**Expected behavior**
All tags that support CSS inline styling should support them in Wordpress, including the `<figure>` tag. Better, have Gutenberg allow visual styling of all text elements whether within an image or in any other block type.

**Screenshots**
Image in Editor:
![Screen Shot 2020-10-28 at 2 09 35 AM](https://user-images.githubusercontent.com/16678592/97415683-c7382680-18c2-11eb-95b4-179c7642b3f7.png)

Image Previewed:
![Screen Shot 2020-10-28 at 2 10 00 AM](https://user-images.githubusercontent.com/16678592/97415675-c606f980-18c2-11eb-8e8c-1d99d378f23e.png)

Image Previewed with `style="text-align: center"`
![Screen Shot 2020-10-28 at 2 30 38 AM](https://user-images.githubusercontent.com/16678592/97418072-9c9b9d00-18c5-11eb-8a75-932845601fb5.png)

**Editor version (please complete the following information):**
- WordPress version: Wordpress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Wordpress.com
- If the Gutenberg plugin is installed, which version is it? Wordpress.com

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 81.0.1

**Comment by talldan** [comment]
> When you create an image in Gutenberg and place it, the caption text shows to be centered. When previewed, the text is left aligned. You can even see this in the generated HTML

This is really dependent on the theme. Some themes left align captions, but the default is for it to be centered. The default styling for centering the caption under the image is somewhat problematic though as discussed a bit on https://github.com/WordPress/gutenberg/pull/26376.

**Comment by commorancy** [comment]
Hi @talldan,

You've already established that this is a bug simply by your comment. Because themes may contain independent CSS that chooses how to style a given line of text, this runs counter to the WYSIWYG nature of the Gutenberg editor. To ensure that the styling that is shown within Gutenberg is properly reflected in whatever theme has been chosen, text should be explicitly styled to ensure that text justification (for example) appears as it does in the Gutenberg editor. In other words, Gutenberg shouldn't leave styling to chance through leaving it up to the theme. Unless Gutenberg can become theme CSS aware and import that theme's CSS styles from the theme for WYSIWYG viewing in the editor, then Gutenberg should always explicitly set styling of text to avoid these theme variance mishaps.

**Comment by talldan** [comment]
@commorancy My comment wasn't clear, so apologies for that. I meant that whether the caption is left aligned or centered is down to the theme. Using core themes as an example, Twenty Twenty left aligns the caption left, while Twenty Nineteen uses the default central alignment. But the result should be consistent with what you see in the editor and the front-end of your site.

It could be a theme CSS issue if you're seeing inconsistent results.

> Gutenberg shouldn't leave styling to chance by leaving it up to the theme. 

This is how WordPress works though. A theme styles content.

> Unless Gutenberg can become theme CSS aware and import that theme's CSS styles for a true WYSIWYG editing and viewing experience

There has been a lot of movement in this direction. The theme's CSS styles have always been used since the beginning. What wasn't working so well previously is that blocks often had different HTML markup between the editor and the front-end. That's now largely solved, but there are sometimes inconsistencies with the styles in elements that wrap the main list of blocks in the editor and front-end, and that sometimes causes an inconsistency.

**Comment by commorancy** [comment]
Hi @Talldan,

Yes, I understood what you were saying. If there is no styling present at all, then the theme's CSS styling dominates. However, when Gutenberg is showing a specific style in the editor, then GB should explicitly style that text based on what's being shown, which will then override the theme's styling. It makes no sense to have the editor show centered text and have the theme show right or left justified text. That's an inconsistent user experience.

The point to all of this is to offer a solid high quality user experience when editing in Gutenberg... that means explicitly styling whenever necessary to avoid the ambiguities of various theme styling.

If you are arguing the point that the theme's styling should rule, then I counter by saying that Wordpress needs to add a user preference to allow the administrator to allow Gutenberg to make the specific styling choices when editing:

- Use the theme's styling
- Use Gutenberg styling

The point is, if Gutenberg is showing centered text as a style in the editor, the editor does need to explicitly style some of its text to ensure that what's being seen in editor is mirrored within the post and to avoid a lower quality user experience.

**Comment by commorancy** [comment]
This issue is no longer needed.
