### ISSUE TITLE
Locking Patterns

### ISSUE THREAD

**Issue by pjsachdev** [WordPress/gutenberg#26544]
Patterns are a great feature for content editors. However, there are occasions when it would be nice to lock a pattern so that the content editor can only add content and not add/remove blocks.

Does this functionality already exist or are there an plans to implement a feature like this?

**Comment by talldan** [comment]
I don't think so, this would be an enhancement, similar to the template lock.

It'd be a little harder to implement as templates are html snippets rather than block declarations. I wonder if it could be an attribute of the group block (locking its inner blocks).

I'll label as an enhancement

**Comment by mtias** [comment]
This is already supported on groups and columns as of https://github.com/WordPress/gutenberg/pull/26128

```
<!-- wp:group {"templateLock":"all"} -->
```
