### ISSUE TITLE
Add regression test for the GB 9.2 empty reusable block issue

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#26548]
### What

Add a unit test on GB and or a regression E2E test that makes sure reusable blocks are correctly parsed without throwing errors.

### Why

Gutenberg 9.2 introduced a [bug](https://github.com/WordPress/gutenberg/issues/26485) that manifested itself when reusable blocks with empty contents (i.e blank strings) were present. It has been fixed [here](https://github.com/WordPress/gutenberg/pull/26484).

To avoid any future regression, a regression unit test and or E2E test should be added to test that this scenario now works without throwing exceptions.

**Comment by fullofcaffeine** [comment]
Already started working on this one, got a (draft) PR here: https://github.com/WordPress/gutenberg/pull/26913.

**Comment by ntsekouras** [comment]
Resolved here: https://github.com/WordPress/gutenberg/pull/26913
