### ISSUE TITLE
Cover Block: Overlay background possible regression

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#26545]
**Describe the bug**

The style of Cover block background overlays has changed in Gutenberg 9.2. This is likely a regression from https://github.com/WordPress/gutenberg/pull/26133.

Specifically, this section changes the style of the overlay:

Before https://github.com/WordPress/gutenberg/pull/26133, there was a `background-color: $black;` rule which was inherited by the `::before`:
https://github.com/WordPress/gutenberg/blob/ee85a7d04fdb880d84244de02d133cf32f247ae0/packages/block-library/src/cover/style.scss#L37-L44

After, there is just an `inherit`:
https://github.com/WordPress/gutenberg/blob/68419b4973367e83148b210e2ff1d76a43100958/packages/block-library/src/cover/style.scss#L37-L40

**To reproduce**
1. Use Gutenberg 9.1 ([download link](https://downloads.wordpress.org/plugin/gutenberg.9.1.1.zip))
1. Create a post with a Cover block and an overlay.
1. View the post on the frontend and notices the background overlay.
1. Upgrade Gutenberg to 9.2 ([download link](https://downloads.wordpress.org/plugin/gutenberg.9.2.1.zip))
1. View the same post on the frontend and notice that the background overlay is different.

**Expected behavior**
I expected the same block to render the same across 9.1 - 9.2 Gutenberg versions.

**Screenshots**

![Screen Shot 2020-10-28 at 16 02 34](https://user-images.githubusercontent.com/841763/97458784-55e88a00-193b-11eb-8899-d4967a532705.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.1 ➡️  9.2

**Comment by sirreal** [comment]
Pinging a few folks who interacted on https://github.com/WordPress/gutenberg/pull/26133 to verify: @jasmussen @mkaz @stokesman

**Comment by stokesman** [comment]
I was aware that #26133 would create this difference and perhaps I should have highlighted that point in my PR. Just to be clear it only affects cover blocks that have no color selected. I'd say the change is worth keeping and maybe there's a way to preserve the old presentation for this particular case without going back to the old CSS since that is problematic in other ways. I actually have a couple of ideas but I'll look into that.

Thanks, @sirreal for bringing this up. It made me realize an oversight in #26133 was that the [`useCoverIsDark`](https://github.com/stokesman/gutenberg/blob/4e8281f48a2f478ddb64e00cfa112b12f61556c7/packages/block-library/src/cover/edit.js#L219-L221) hook should have been revised to not assume the black color when no color has been selected.  How do you make those rad little file excerpts of particular line numbers, btw?

**Comment by inaikem** [comment]
I'm seeing this issue in 3447224-ZD with several hundred posts affected by this change.

**Comment by sirreal** [comment]
> I was aware that #26133 would create this difference and perhaps I should have highlighted that point in my PR. Just to be clear it only affects cover blocks that have no color selected. I'd say the change is worth keeping and maybe there's a way to preserve the old presentation for this particular case without going back to the old CSS since that is problematic in other ways. I actually have a couple of ideas but I'll look into that.

Please see https://github.com/WordPress/gutenberg/pull/26569 for the proposed fix.

> Thanks, @sirreal for bringing this up. It made me realize an oversight in #26133 was that the [`useCoverIsDark`](https://github.com/stokesman/gutenberg/blob/4e8281f48a2f478ddb64e00cfa112b12f61556c7/packages/block-library/src/cover/edit.js#L219-L221) hook should have been revised to not assume the black color when no color has been selected.

With https://github.com/WordPress/gutenberg/pull/26569 would that be an issue? (I'm unfamiliar with `useCoverIsDark`).

> How do you make those rad little file excerpts of particular line numbers, btw?

😉  You can reference code inline from the same repository. Highlighting some lines in the repo and selecting "Copy Permalink", then put that URL on its own line and they'll show up as snippets.

**Comment by stokesman** [comment]
@sirreal, in #26569, `useCoverIsDark` will be fine as is. Thanks for the tip on the code refs. Funny cause I was trying that but it wasn't showing in the preview so I thought it wouldn't work.
