### ISSUE TITLE
Table block: default CSS does not match the generated markup

### ISSUE THREAD

**Issue by gonzomir** [WordPress/gutenberg#2656]
## Issue Overview
The default styles of the table block don't match the generated markup.

## Steps to Reproduce (for bugs)
1. Create table block in the editor
2. Look at the markup in the front-end

## Expected Behavior
The CSS selectors should match the generated markup.

## Current Behavior
Currently the CSS expects the table to be wrapped in a `div` with `wp-block-table` class, while the saved markup is a `table` with the class. This also causes the table in the front-end to have `display: block;` applied to it.

## Possible Solution
Apply the current set of styles only to the editor and eventually add another default styles for the block for the front-end.

## Related Issues and/or PRs
#2620 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mtias** [comment]
Closing in favor of #2620.
