### ISSUE TITLE
Separator Block: HR preview in sidebar is different than actual HR

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#26570]
**Describe the bug**
With a separator block selected, in the block editor sidebar, the "Styles" panel with `Default` selected, the separator is showing as being left-aligned.

However, the actual separator is centered. 

I believe this is because of this margin setting here:
https://github.com/WordPress/gutenberg/blob/e259fd03b7ba4852ef6b01be06ad4f5c4a100eec/packages/interface/src/components/complementary-area/style.scss#L65

Which is in opposition to the default styling for the separator element here:
https://github.com/WordPress/gutenberg/blob/e259fd03b7ba4852ef6b01be06ad4f5c4a100eec/packages/block-library/src/separator/theme.scss#L4

**To reproduce**
1. Activate a theme that does not add any custom styling to the Block Editor, like twentyseventeen.
2. Add a separator block to a page
3. In the sidebar, set the Style to be `Default`.
4. Notice the actual block is showing the separator in the center.
5. Notice the preview of that option shows it left aligned. 

**Expected behavior**
The preview and the actual default styles for the separator block match.

**Screenshots**
<img width="1792" alt="Screen Shot 2020-10-29 at 10 36 21 AM" src="https://user-images.githubusercontent.com/7538525/97588333-c2fb2e80-19d2-11eb-8371-a9b9a3116012.png">

**Comment by talldan** [comment]
Thanks for reporting. 

> I believe this is because of this margin setting here

Looks like it! A good reason for using component-based classes for styling rather than elements. Though I understand these styles will have been added to make it easy for plugins to add sidebar content.

Not sure what the best option would be. Separator could reset the style, but I personally think the element selectors should be removed where possible.

**Comment by johnstonphilip** [comment]
This seems to be falling back now to this line:
https://github.com/WordPress/gutenberg/blob/e259fd03b7ba4852ef6b01be06ad4f5c4a100eec/packages/block-editor/src/components/block-list/style.scss#L303

Which (inadvertently?) fixes it. Closing for now.
