### ISSUE TITLE
Improve the creation flow of navigation block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#26571]
Currently the navigation block flow involves you having to select from the drop down the option before you can select how to fill out (or not). You can see that flow here:

![2020-10-29 13 49 30](https://user-images.githubusercontent.com/253067/97584289-c81aa680-19ef-11eb-8059-af2b75217aba.gif)

## The problem
There are a few issues with this current flow:

- It looks like on first click you should be able to just confirm and go, because you're selecting the same information.
- There is a visual issue with hover states not fully going across all of the drop-down selections.

## Suggestion
For now, I have a suggestion that is a minor work around and if agreed I think deeper exploration into this section needs to be done, that is to activate the 'create' button and only have one link per type, not to repeat in drop-down.

![image](https://user-images.githubusercontent.com/253067/97585218-cd2c2580-19f0-11eb-9289-046628d79698.png)

For example in above case, the drop-down would only show "Create from all top-level pages".

## Future
I think there is certainly a lot more room for work on this section, but those few changes should soothe a little flow here to then lead to deeper iterations. I'll also work on a PR to try and ease the hover state as a compliment to these iterations.

**Comment by kellychoffman** [comment]
This Navigation block needs a lot of work. Scoping is good, but would suggest picking one direction:

1. If we're focusing this to fixing the creation flow: this proposal only includes the first step in that flow. 
2. If this is is a shorter term, visual bug fixing / clean up: I think we should clean up all the out of place ui elements in the creation flow, like the drop down text. (Edit: I see this was mentioned in the corresponding PR.)

**Comment by karmatosed** [comment]
Thanks for the thoughts @kellychoffman. 

> If we're focusing this to fixing the creation flow: this proposal only includes the first step in that flow.

Yes, that's very true. I totally agree there is much deeper exploring to go here. I wanted to connect in one particular thread I found in another PR that seems relevant regarding this (props to @jasmussen for showing me it):

https://github.com/WordPress/gutenberg/pull/26947#issuecomment-728253011

What this does which really interests me in, is simmers down the placeholder and instantly allows you access to 'create and go'. Looping in @shaunandrews as created the idea over in the PR.

**Comment by jasmussen** [comment]
Good thoughts in this ticket. I wonder if recent enhancements mean we can close it? 

- The Page List block makes it that much easier to create in one step
- The new placeholder state has landed
- There's a new individual menu item placeholder state

**Comment by karmatosed** [comment]
@jasmussen totally into this being closed - so let's do just that!
