### ISSUE TITLE
Why can I only replace content and not just edit it?

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26585]
### Problem

**Edit vs. Replacing content**
I noticed while testing the Query block that I was able to click into the Post Excerpt block as if I could edit the content. After clicking into the block, it turned grey as if disabled. Rather than editing the content, it appears I was able to replace it completely. Is this right? 

**Publishing panel changes are unclear**
The changes then also showed in the Publish panel, but denoted that a "Page" changed and gave me the page ID, I think? Seeing a number there was not very helpful. I was confused if it was alerting me to the page I had just replaced content on, or what?

**Example of problem**

![editing](https://user-images.githubusercontent.com/617986/97628828-7a4f6f80-19ea-11eb-85ba-e97b39475673.gif)

### Expectation
I expect that if I'm able to click into a block, I should be able to edit the content, and not just replace it. Replacing it felt really odd. If I can't edit the content in place, then I shouldn't be able to click into it, IMO.

**Comment by ntsekouras** [comment]
Hey @mapk!

>Rather than editing the content, it appears I was able to replace it completely. Is this right?

This behavior was for posts that didn't have the `excerpt` field explicitly set and is extracted from `post content`. I believe the proper behavior is to edit this extracted excerpt and edit it, if you want to change it, as you propose. After the `update` any change in the `excerpt` is synced with the `excerpt` field in the respective post. 

>Publishing panel changes are unclear

This is an issue of its own and I agree with you. I'll look into it.

**Comment by mapk** [comment]
>This behavior was for posts that didn't have the excerpt field explicitly set and is extracted from post content.

Ah! Okay, I was very worried that my changes were eliminating the post content. I don't think the user will notice that they're editing the Post Excerpt in this case and feel relieved. So we probably need to design a solution that doesn't leave the user feeling like they've changed their entire post.

**Comment by ntsekouras** [comment]
I think it's clear that in `Post Excerpt` block we are editing the `excerpt`, no?

**Comment by mapk** [comment]
@ntsekouras yes! I dropped a comment on the PR.
