### ISSUE TITLE
Focus moves away from <TextControl /> on debounce

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#26589]
I'm trying to create a block that generates output from a text control. Here's my code

```
const MyText = class extends Component {
      constructor(props) {
        super(props);
        this.state =props.data;
        this.debouncedSync = debounce(() => {
          sync(this.state);
        }, 1000);
      }
      render() {
        const TempText =
          <TextControl
            placeholder={'my placeholder'}
            help={controlOptions.help_text}
            value={this.state[property]}
            onChange={(val) => {
              const newState = {
               text: val};
              this.setState(newState);
              this.debouncedSync.bind(this)();
            }}
          />
        return <TempText />;
      }
    };
```

At the completion of debounced time interval, focus moves away from the text control to the block, and so the cursor inside disappears.. how can I prevent this? (the sync function sets some attributes and makes API calls etc.). How do I prevent this?

**Comment by talldan** [comment]
@navxio Hard to tell without knowing what `sync` does.

**Comment by navxio** [comment]
@talldan `sync` is an auxiliary function that looks like this -
```
function sync(data) {
   this.props.setAttributes({ data });
   this.state.priorityQueue.add({a: 'b'}, this.anotherFunction(data));
}
```

Is this info enough?

**Comment by talldan** [comment]
It's still very obscure, sorry! This isn't really an appropriate forum for troubleshooting, so I'm going to close the issue.
