### ISSUE TITLE
Site Editor: Distinguish Template Parts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26599]
One of the unique properties of template parts when compared to regular blocks is that they can be edited locally in the context of a document / template, and yet those edits will be applied globally, affecting other parts of a site.

It therefore seems reasonable to consider distinguishing them somehow in the UI, in order to establish a pattern that indicates that these blocks are 'different', and to provide familiarity when dealing with them.

If anyone has used Figma components, or Sketch symbols (similar concepts to Template Parts), you'll be familiar with how they use color to illustrate when you're working with one of these special items versus a regular layer, which works well. Figma uses purple:

<img width="700" alt="Screenshot 2020-10-30 at 11 28 10" src="https://user-images.githubusercontent.com/846565/97700015-058c3c00-1aa3-11eb-98bd-1cb47104360e.png">

Template parts not only behave differently to regular blocks, but different _types_ of template parts will – eventually – be swappable based on their assigned type. As an example, a site may have multiple Header template parts, and a user should be able to quickly switch between those different iterations while editing a template. It may therefore be useful for the UI to indicate not only _when_ a user is interacting with a template part, but also what _type_ of template part it is.

As an initial exploration, I think we might be able to use the existing "Layout" icon to achieve this:

<img width="887" alt="Screenshot 2020-10-30 at 12 11 52" src="https://user-images.githubusercontent.com/846565/97703789-1dff5500-1aa9-11eb-9ec6-c80d17ba6362.png">

Putting all this together we might create something like:

<img width="1394" alt="Screenshot 2020-10-30 at 12 23 30" src="https://user-images.githubusercontent.com/846565/97704667-c1049e80-1aaa-11eb-976e-a8f1bf96fe1a.png">

Note that the Header template part is also outlined with a matching color, to further instill the notion that one is editing a template part.

I think there is a discussion to be had around which color to use for this. In the example above I'm using the primary color from the active color scheme. I'm also wondering if there is any additional treatment we might apply to the toolba, settings panel, and Inserter to strengthen the concept.

**Comment by mtias** [comment]
Great, thanks for starting this! In context, I really like highlighting template parts in the list view — it helps give a quick sense of structure. I think we should initially only treat header and footer differently. The generic template part feels a bit off, since it seems to imply "main" or "content" based on the icon. I think we can try using the default template icon with no specific area highlighted.

**Comment by jameskoster** [comment]
> The generic template part feels a bit off, since it seems to imply "main" or "content" based on the icon.

Good point.

> I think we can try using the default template icon with no specific area highlighted.

Yes that can probably work, as long as we don't list the template itself, alongside that same icon, and create confusion.

Just to spitball, another approach – similar to Figma – could be to use a more abstract collection of shapes. You lose the traditional 'layout' metaphor, but the generic TPs (which are likely to outnumber the specific ones) are perhaps less ambiguous?

<img width="1114" alt="Screenshot 2020-11-12 at 10 15 54" src="https://user-images.githubusercontent.com/846565/98927151-12ac2080-24d0-11eb-8a5f-efea5831091d.png">

<img width="1255" alt="Screenshot 2020-11-12 at 10 16 22" src="https://user-images.githubusercontent.com/846565/98927198-235c9680-24d0-11eb-8a68-c9668d198471.png">

**Comment by shaunandrews** [comment]
I think trying to tie the icon to some spacial placement of a template part is a nice idea, but breaks down in practice. We don't know if a "header" is at the top of the screen visually; A header could just as easily exist visually as a sidebar and serve the same purpose.

I like the idea of a more abstract icon, but I think the diamond pattern is still trying _too hard_ to visually represent the placement of the template part.

My first thought would be to try and build something based on the existing Group block icon:

<img width="123" alt="image" src="https://user-images.githubusercontent.com/191598/99553745-7af57900-298c-11eb-85c7-6eec68190556.png">

**Comment by jameskoster** [comment]
> We don't know if a "header" is at the top of the screen visually; A header could just as easily exist visually as a sidebar and serve the same purpose.

In that case it would be a sidebar? :D Either way that's kind of why I like the abstract nature of the icons above. It _hints_ at the location/purpose in a less prescriptive way than the layout icons.

I hear you on questioning the value in actually having separate icons though. If we deem that value inadequate then I would agree, something like the group block icon could work.

**Comment by mtias** [comment]
Mmm, I think I like the initial ones more. They are already an abstract representation but there's nothing performative about the icon, it just illustrates the most common layout. I don't mind something more abstract, but the template icon already achieves the goal of communicating the concept of a template and the concept of a template part fairly well.

**Comment by jameskoster** [comment]
No strong feelings here, both work for me. Happy to go with the layout icon(s).

**Comment by mtias** [comment]
Thinking about how to break this into steps:

- [ ] Define header, footer, sidebar terms as variations of template part. Hide the variations in the inserter.
- [ ] Apply specific icons to those variations.
- [ ] Color template parts and selection state in the block tree and icon in block description.
- [ ] List these template parts more prominently in the W sidebar.
- [ ] Include specific descriptions in the sidebar inspector and "current template dropdown" for header, footer, sidebar to give context.

**Comment by jameskoster** [comment]
PR to add the icons here: https://github.com/WordPress/gutenberg/pull/27378

**Comment by carolinan** [comment]
Just adding a note that color alone should not be used as identifiers.
I prefer the first icons, I think they are easier to understand.

😄  A header is called a header because it is usually the top-most part, where we have our head. Usually.

**Comment by Addison-Stavlo** [comment]
At this point with the different block variations and icons applied within the editor, I think we are good to close this issue?  Obviously, feel free to reopen for further discussion if I am mistaken. 😁

**Comment by jameskoster** [comment]
Yup, we can continue refining Template Parts in https://github.com/WordPress/gutenberg/issues/31750
