### ISSUE TITLE
Inconsistent capitalisation in "Site" blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26606]
The "Title" in "Site title" should be capitalised.

<img width="393" alt="Screenshot 2020-10-30 at 16 24 08" src="https://user-images.githubusercontent.com/846565/97730985-7b58cd80-1acc-11eb-8f46-7c051b759184.png">

**Comment by ntsekouras** [comment]
Hey @jameskoster - thanks for reporting this!

Where did you encounter this with not a capital `T`? Because I made a quick check(both UI and code) and it is capitalized.

**Comment by jameskoster** [comment]
Interesting, yes I see that too now that I look at the code. 

On further investigation it seems to be a localisation issue, I was using en-gb.
