### ISSUE TITLE
You cannot copy or cut a single block. You must have multiple blocks selected or the copy/cut command does not work.

### ISSUE THREAD

**Issue by frogdesk** [WordPress/gutenberg#26616]
**Describe the bug**
When copying blocks in Gutenberg, you can only copy or cut if you have multiple blocks selected. If you select a single block, you cannot copy or cut it.

**To reproduce**
1. Make a page.
2. Create two blocks with content in them.
3. Select one of the blocks.
4. Type control-c or control-x
5. Nothing happens

**Expected behavior**
The block should be copied to the clipboard (and removed from the art board in the case of cut).

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- default editor

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.111

**Comment by ntsekouras** [comment]
Hey @frogdesk - thanks for reporting this.

I just tested this in macOS Catalina and works as expected. Maybe something going wrong when in `windows`?

**Comment by frogdesk** [comment]
I just tested on my laptop with Mojave, and indeed it works there. My Windows 10 machine version 20H2 (19041.572) is where it doesn't work.

**Comment by frogdesk** [comment]
Actually, it works fine in FireFox too. So I guess this is a Chrome issue. Version 86.0.4240.183

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7
Gutenberg plugin 10.1.1
Twenty Twenty One.
Newest version of Chrome. Version 89.0.4389.82 (Official Build) (x86_64)
OSX 10.15.7

Added two blocks with content.
Selected the content of the first. Did a cmd+x and cut out the content. Went to another block and pasted it back in.

It looks like it is working fine. I will go ahead and close the issue. It can of course be reopened if need be.
