### ISSUE TITLE
The attributes for initial states in an InnerBlocks template

### ISSUE THREAD

**Issue by davy440** [WordPress/gutenberg#26619]
Hello all,
I am creating a custom block in which InnerBlocks are used. I have been following the official documentation -
[https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks)

Everything is working perfectly. I have just one question though, in the `template` prop, when the [MY_TEMPLATE] const is defined, what are the attributes for the blocks defined. In the example, only `placeholder` is defined. I have a feeling there is a lot more to it. Especially for blocks such as `core/columns`.

Looking forward to some awesome people for awesome responses...

**Comment by talldan** [comment]
Hi @davy440. Not 100% sure I understand the question, but I'll do my best to help. Each block in a template can be defined as an array, with the first item the block name, the second the attributes, and the third an optional array of the inner blocks:

```js
[ 'core/columns', { backgroundColor: 'yellow' }, [ [ 'core/column', {} ] ]
```

In terms of knowing what the  valid attributes for blocks are, they're not presently very thoroughly documented. There's a project here that lists them, but doesn't detail what the correct values are:
https://youknowriad.github.io/blockbook/block/core---cover

Another option is to dive into the code and have a look:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/block.json

And a third option (probably the easiest way to get exactly what you want) is to create the blocks you want in the editor and then try running something like this in the browser console:
```js
wp.data.select( 'core/block-editor' ).getBlocks()
```
Which will print out an array of the blocks in the post and associated data, like attributes and inner blocks.

I'll close the issue, hopefully this helps.

**Comment by davy440** [comment]
@talldan yes, it helped a lot. I was unaware of the fact that a block can be defined as an array. It has helped a lot. Thanks!

Now, one more question arises out of this. I was setting InnerBlocks and noticed that there is no way to set alignment of Inner Blocks as it cannot be done through attributes. 

Is there any way to set alignment of blocks in a template?

**Comment by talldan** [comment]
@davy440 Usually it requires an`align` attribute. e.g:
```js
[ 'core/heading', { align: 'full' } ]
```

**Comment by davy440** [comment]
@talldan yes, it worked for the heading but what to do in case of a button block. It does not accept align as an attribute.
[https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/block.json](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/block.json)

**Comment by davy440** [comment]
@talldan nevermind, it was done! 😅
I used `['core/button', { align: 'center' } ]` and it worked.
It got a bit confusing as align is not mentioned as an attribute in [https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/block.json](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/block.json). It is in the `supports` prop which got me a little confused.

Thanks a lot, mate! You are EPIC!

**Comment by talldan** [comment]
Oh yeah, I guess those attributes added by `supports` won't be in the `block.json`. Glad you managed to get it sorted 😄
