### ISSUE TITLE
Gutenberg doesn't work at all with iThemes Sync plugin

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2661]
From review:

>  Wouldn’t work at all until I switched off a plugin (iThemes Sync) that was conflicting. Can see there being a lot of similar problems.

**Comment by jasoncsking** [comment]
iThemes Sync is not a free plugin, so might be difficult to test. Here is the error you get when Sync is switched on and you click Gutenberg > Demo:

`
Fatal error: Uncaught ArgumentCountError: Too few arguments to function ithemes_sync_duplicate_post_addon_default_post_title(), 1 passed in /home/kingjaso/public_html/wp-includes/class-wp-hook.php on line 298 and exactly 2 expected in /home/kingjaso/public_html/wp-content/plugins/ithemes-sync/duplicator.php:67 Stack trace: #0 /home/kingjaso/public_html/wp-includes/class-wp-hook.php(298): ithemes_sync_duplicate_post_addon_default_post_title('') #1 /home/kingjaso/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array) #2 /home/kingjaso/public_html/wp-content/plugins/gutenberg/lib/client-assets.php(724): apply_filters('default_title', '') #3 /home/kingjaso/public_html/wp-includes/class-wp-hook.php(298): gutenberg_editor_scripts_and_styles('gutenberg_page_...') #4 /home/kingjaso/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #5 /home/kingjaso/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/kingjaso/public_html/wp-admin/admin-header.php(97): do in /home/kingjaso/public_html/wp-content/plugins/ithemes-sync/duplicator.php on line 67`

Tested on Gutenberg 1.1.0.

**Comment by TimothyBJacobs** [comment]
Looks like the issue is calling [the `default_title` filter without a post object](https://github.com/WordPress/gutenberg/blob/81f50eaf8acceb04ca3705822caeb42999ea7b34/lib/client-assets.php#L724).
