### ISSUE TITLE
Cannot find module 'has' when using create-block npm package

### ISSUE THREAD

**Issue by NicestRudeGuy** [WordPress/gutenberg#26617]
**Describe the bug**
npx or npm script not working anymore.  I tried yesterday it was working fine .
also tried with older version like 0.17.0, 0.16.0 
still getting cannot find module 'has' error . 
my node version : 11.10.1 & 14.15.0
my npm version : 6.4.8

**To reproduce**
1. npx @wordpress/create-block todo-list

**Expected behavior**
a boilerplate block to be created. 

**Screenshots**

![image](https://user-images.githubusercontent.com/9863419/97771401-7fcfc580-1b62-11eb-92a9-011ff1472345.png)

![image](https://user-images.githubusercontent.com/9863419/97771403-8cecb480-1b62-11eb-88ae-4be607c6e5e1.png)

![image](https://user-images.githubusercontent.com/9863419/97771470-43509980-1b63-11eb-9233-7955dfd4a42d.png)

**Comment by NicestRudeGuy** [comment]
@gziolo  i found that i started working now, i tried this on several machines mac , windows . 
now getting this warning instead **(node:7225) ExperimentalWarning: The fs.promises API is experimental**

**Comment by talldan** [comment]
Closing as issue now resolved.

**Comment by gziolo** [comment]
I'm wondering if it was somehow related to #26547. Good to see it works now.

> now getting this warning instead (node:7225) ExperimentalWarning: The fs.promises API is experimental

Promises API for `fs` was added in Node 10.0.0:
https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api

Node 14.x is now considered the most expected version to use. I'm sure it was tested with Node 12.x and Node 10.x and I don't remember seeing such warnings. If you could share more details, I would be happy to try to reproduce.

**Comment by NicestRudeGuy** [comment]
@gziolo my colleagues faced that #26547 issue and i didnt but i faced this cannot find module 'has' issue .
with node 14.x there are no warnings , only have them with node version less than 14
and that cannot find module 'has'  issue is not there anymore , so i guess it got fixed.
