### ISSUE TITLE
HTML special characters in 'New Post' emails

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/gutenberg#2663]
## Issue Overview
Users who are subscribed to my blog see HTML special characters in the excerpt that is sent in the 'New Post' email

See an example here https://www.dropbox.com/s/ts74j7qzecuf96y/Screen%20Shot%202017-09-03%20at%206.44.45%20PM.png?dl=0

Gutenberg version 1.0.0
Using Chrome Browser on Linux

Email client is OSX mail app

**Comment by nicolinuxfr** [comment]
I have experienced this bug, not only for the excerpt by the way. I’m using Safari on macOS and I have to search/replace this string for each post since 1.0.0.

**Comment by karmatosed** [comment]
Are you still both getting this with the latest version of Gutenberg?

**Comment by nicolinuxfr** [comment]
Sorry for the late answer. I just tried Gutenberg again and I still have the issue :

<img width="685" alt="capture d ecran 2017-10-11 a 18 56 33" src="https://user-images.githubusercontent.com/2078386/31454494-e88364d2-aeb5-11e7-9b6e-885a73a377c5.png">

**Comment by karmatosed** [comment]
I am still unable to recreate in latest version of Gutenberg. If you can please reopen this.
