### ISSUE TITLE
Full Site Editing: Block group label

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26639]
Many blocks that are most likely to be used in the Site Editing context are currently grouped in to a "Design" category in the Inserter:

<img width="350" alt="Screenshot 2020-11-02 at 17 05 46" src="https://user-images.githubusercontent.com/846565/97896937-abeb7200-1d2d-11eb-9c6f-5eb84fb34df5.png">

While I understand the intention behind this label, it doesn't feel quite right looking at this group of blocks holistically. Dynamic blocks like Post Title / Site Tagline, and more technical blocks like the Query Loop transcend what I think the average user would interpret as "Design".

Framing the Site Editor as a visual theme builder, we might consider renaming this group to "Theme", or "Template". This would feel like a natural evolution given that many of the Site Editing blocks are direct ports of theme [Template Tags](https://github.com/WordPress/gutenberg/issues/22724).

Another option would be to split these blocks in to multiple groups – there are a great number of template tags for us to create... Perhaps there is scope for separate "Template – post",  "Template – category", "Template – comment", and "Template – site", etc. block groups?

My instinct tells me a single "Theme" or "Template" group would be a good starting point from which we can refine over time. What do y'all think?

**Comment by mtias** [comment]
I'd be fine with a "Theme" category, though how would we describe the difference between "Widgets" and "Theme"? Maybe we could merge everything on widgets and rename the title to "Widgets & Theme".

**Comment by priethor** [comment]
I feel "Widgets & Theme" gives a better context without being too long, as I believe "Theme" can lead to confusion and users may understand "Theme" blocks are specific to the current theme.

**Comment by kjellr** [comment]
> I believe "Theme" can lead to confusion and users may understand "Theme" blocks are specific to the current theme.

Yeah, I could see that point of confusion too. Maybe the category would be called "Site"? Or Even "Site Building" or "Site Editing"?

**Comment by priethor** [comment]
I was also thinking of the "Site" term, especially since some of these blocks are Site title and Site logo. However, "Site Editing" sounds too similar to "Full Site Editing" and might cause even more confusion. I think grouping them with "Widgets" ("Site & Widgets", maybe?) can help users conceptually differentiate between classic site-building, even if with blocks, and Full Site Editing.

**Comment by mtias** [comment]
Also relevant https://github.com/WordPress/gutenberg/issues/26316 and https://github.com/WordPress/gutenberg/pull/27822.

We already have "Latest Posts" in widgets so it makes sense to combine "Query" there.

**Comment by carolinan** [comment]
I would prefer "Site & Widgets" over "Theme"

**Comment by overclokk** [comment]
My 2 cent, I think "Site" is good, not widget because they are different kind as I can see.

**Comment by aurooba** [comment]
In general, I find the term 'widgets' awkward within the Block Editor context.

Widgets are often a way to display content dynamically – latest posts, categories, calendar, archives, search, RSS, etc – these are all dynamic content blocks. The exception would be the Social Icons block, which I don't see as dynamic. Personally, I'd prefer to see a term like 'Dynamic' or 'Dynamic Content' encompass both the FSE specific blocks and the Widgets.

**Comment by mtias** [comment]
Most of these are in a "theme" category now.
