### ISSUE TITLE
Name missing when taking over post

### ISSUE THREAD

**Issue by oddevan** [WordPress/gutenberg#26645]
**Describe the bug**
When a user takes over a post from another user, the editor will show the picture of the user taking over but not their name, causing unnecessary confusion.

**To reproduce**
1. With one user, create a post.
2. Save the post as a draft.
3. In another browser or private/incognito window, log in as a different user with the ability to edit others' posts
4. Find the post from step 1 and edit it.
5. When prompted, "Take over" the post.
6. Within 90 seconds, the first window should show that "someone else" has taken over the post. It may show the Gravatar of the user.

**Expected behavior**
More identifying information of the user taking over is expected, especially their name.

**Screenshots**
![Screen Shot 2020-11-02 at 7 58 59 PM](https://user-images.githubusercontent.com/1427716/97935215-ec56ea00-1d45-11eb-8ae0-0a82fa0d7488.png)

Note that the Gravatar is correctly shown, but the user's name is not.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Safari
 - Version: 13.1.2

**Comment by trinadin** [comment]
@talldan This issue is being addressed in https://core.trac.wordpress.org/ticket/56197 and slated for a 6.0.1 release.

**Comment by Mamaduka** [comment]
The issue was fixed in #37914 and should be part of the WP 6.0 release - https://core.trac.wordpress.org/ticket/55238.

**Comment by trinadin** [comment]
Again, the issue was not corrected in that original ticket. This particular issue mentioned here was not fixed until ticket [#56197](https://core.trac.wordpress.org/ticket/56197), and will not be present in 6.0. You need 6.0.1 for this fix to be applied.

**Comment by trinadin** [comment]
> The issue was fixed in #37914 and should be part of the WP 6.0 release - https://core.trac.wordpress.org/ticket/55238.

The issue was not corrected in that original ticket. This particular issue mentioned here was not fixed until ticket [#56197](https://core.trac.wordpress.org/ticket/56197), and will not be present in 6.0. You need 6.0.1 for this fix to be applied.

**Comment by Mamaduka** [comment]
Thanks for the clarification, @trinadin!
