### ISSUE TITLE
Possibility to move blocks left and right

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#26640]
**Is your feature request related to a problem? Please describe.**
You can't move blocks left and right inside columns in any way besides dragging.

**Describe the solution you'd like**
A possibility to move blocks left and right similar to how you can move it now up and down.

**Comment by annezazu** [comment]
Hey @Arskrigitsioniets! Thanks for reporting this. I've added some labels and just want to note that this feels similar to the conversation taking place in #24328

**Comment by youknowriad** [comment]
Let's close as a duplicate #24328 to consolidate
