### ISSUE TITLE
Removing core pattern category and core block patterns doesn't remove them

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#26667]
**Describe the bug**

I'm trying to remove all the core block patterns so that I can add my own, for the client to use. I'm not using core blocks so this could be a problem if they try to use core patterns.

The core blocks are just put in the uncategorized category, and if you click on them they are not used (the notice will go off in the editor).

**To reproduce**

1. Remove core patterns and categories

```php
add_action('init', 'removeCorePatterns');

function removeCorePatterns() {
        remove_theme_support('core-block-patterns');

	unregister_block_pattern_category('buttons');
	unregister_block_pattern_category('columns');
	unregister_block_pattern_category('gallery');
	unregister_block_pattern_category('header');
	unregister_block_pattern_category('text');
	unregister_block_pattern_category('uncategorized');
}
```

2. Register your pattern and category
3. Open the editor
4. Check the patterns

![patterns](https://user-images.githubusercontent.com/8638515/98014895-7f525b80-1dfc-11eb-9809-2f763b78ceaf.png)

**Expected behavior**

There should be only one registered category with my patterns. The core patterns should be removed, not put in an uncategorized category that is shown instead.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7 (19H2)
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (x86_64)

**Comment by dingo-d** [comment]
A trick, by @acosmin, is to filter the `block_editor_settings` array and remove them there. The example uses a class to hold all the functionality in, but the procedural way should work too:

```php
class BlockPatterns
{

	public const PATTERN_CATEGORY = 'category-name';

	/**
	 * Register all the hooks
	 *
	 * @return void
	 */
	public function register(): void
	{
		add_filter('block_editor_settings', [$this, 'removeCorePatterns']);
	}

	/**
	 * Remove core block patterns
	 *
	 * @param array $settings Array of block editor settings to filter out.
	 *
	 * @return array Filtered array.
	 */
	public function removeCorePatterns(array $settings): array
	{
		$patternsToKeep = array_filter($settings['__experimentalBlockPatterns'], function($pattern) {
			return $pattern['categories'][0] === self::PATTERN_CATEGORY;
		});

		$settings['__experimentalBlockPatterns'] = array_values($patternsToKeep);

		return $settings;
	}
}
```

This works, but still, the above should work too.

**Comment by JakeFrost92** [comment]
I may be a little late to the party but for anyone coming to this like me:
Change
`add_action('init', 'removeCorePatterns');`

To
after_setup_theme

**Comment by JakeFrost92** [comment]
Changing when the action is called from 'init' to 'after_setup_theme' resolved the issue for me:

`add_action('after_setup_theme', 'removeCorePatterns');`

**Comment by skorasaurus** [comment]
Hi @dingo-d ; 

These, along with other [theme supports](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/) are intended to be activated or deactivated through the `'after_setup_theme'` hook, not the `'init'` hook.

**Comment by tcmulder** [comment]
Thanks @skorasaurus! When using `'init'`, the buttons and query categories were still available under the Patterns tab (everything else was gone), and they went away only after switching to `'after_setup_theme'`. So if someone else is noticing some patterns sticking around and not others, check the hook.

**Comment by pgooch** [comment]
Thanks @tcmulder dropping that knowledge in the issue, I was wondering why the were sticking around.

**Comment by sjoerdlinders** [comment]
The WP core block patterns are constructed on the `'init'` event in file `/wp-includes/default-filters.php`,
 with the default priority **10**:
 `add_action( 'init', '_register_core_block_patterns_and_categories' );`

Use for example following code with priority **9** to prevent these WP core patterns from getting constructed:
```
add_action('init', function() {
    remove_theme_support('core-block-patterns');
},  9  );

```
Within a plugin you just add this code in your `__construct` function:
```
if ( is_admin() ) {
    remove_theme_support('core-block-patterns');
}

```
Not adding core block patterns to the construction tree to begin with, is a far better way then removing them afterwards.

**Comment by ShahriarKh** [comment]
Thanks to https://fullsiteediting.com/lessons/introduction-to-block-patterns/, I want to add some details for future wanderers:
- Removing the category doesn't remove the blocks inside it, and you'll end up with a bunch of `uncategorized` blocks.
- `Uncategorized` is a fallback, so it's not possible to remove it with `unregister_block_pattern_category`

**Comment by ghost** [comment]
I would like to reopen this issue, cause the original bug still applies for `add_filter( 'should_load_remote_block_patterns', '__return_false' );` and I think it's a good thing to have this information all in one place.

Changing the priority doesn't help, so this should probably be resolved by changing the place this filter is executed. Right now it's being called in `_load_remote_block_patterns()`, but I haven't found the place this function get's called.

**Comment by ghost** [comment]
Update: I noticed this filter is already being called by using the theme support for core patterns, so that might solve the issue. Would be a nice addition to the documentation, though.
