### ISSUE TITLE
Clear All / Remove All

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#2666]
How about adding a possibility to clear all blocks from the page/post a user is creating? A use case may be someone writing along with a post and added bunch of blocks and for whatever reason, he/she wish to remove all. Currently, I don't see an option to do it. I know we can select multiple blocks and then delete them, but a clear all option may be useful. 

How about adding a button/text which says Clear between the Undo/Redo icons. 
![clear-all](https://user-images.githubusercontent.com/5817882/30058483-adda3414-9254-11e7-85b6-df2f40c3b8e3.png)

**Comment by karmatosed** [comment]
I am a little concerned about adding more options to an already getting crowded area. I'll be honest, I'm not sure how useful this is, but maybe we can see from comments. I don't feel the position in-between would make sense though.

**Comment by iseulde** [comment]
You can also use CTRL/CMD+A and then press BACKSPACE/DELETE to remove all blocks, if no block is selected.

**Comment by karmatosed** [comment]
I standby my concern adding more to the toolbar. Let's close and see what feedback we get in tests.
