### ISSUE TITLE
Custom spacing control is no longer appear in the editor

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#26662]
**Describe the bug**
I no longer see the custom spacing control for Cover and Group blocks. The theme I'm testing with has the theme support `add_theme_support( 'experimental-custom-spacing' );` or the new `add_theme_support( 'custom-spacing' );`

**To reproduce**
1. Make sure the theme has the theme support for custom spacing.
2. Add a cover or group block
3. See if you see the spacing panel in the sidebar.

**Expected behavior**
The spacing panel to be in the sidebar.

**Screenshots**
![Screenshot 2020-11-03 at 14 41 24](https://user-images.githubusercontent.com/908665/97999058-c3d0fd80-1de2-11eb-88c1-c51db8643a23.jpg)

**Editor version:**
- WordPress version: 5.5.3
- Gutenberg plugin version: 9.9.2

**Desktop:**
 - OS: Mac
 - Browser: Chrome

**Comment by nosolosw** [comment]
I've got a fix for this at https://github.com/WordPress/gutenberg/pull/27045
