### ISSUE TITLE
Clearer Block Editor documentation

### ISSUE THREAD

**Issue by dankellett** [WordPress/gutenberg#26666]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I read the WordPress Developer Documentation, specifically the Block Editor area.
https://developer.wordpress.org/block-editor/architecture/data-flow/

**Describe the solution you'd like**
Clear and concise documentation that doesn't use analogies that use jargon only understood by a small subset of readers.

**Describe alternatives you've considered**
Looking elsewhere for better documentation.

**Comment by talldan** [comment]
@dankellett You'll have to be more specific. You can't expect contributors to revamp documentation based on only three sentences of feedback.

**Comment by dankellett** [comment]
In the case of this page the typesetter's chase and sorts analogy only adds to what needs to be learned to understand the concept for a lot of people.

**Comment by dhruvkb** [comment]
I disagree with the assessment that the 'chase' and 'sorts' analogy is counterproductive. While the line provides additional help to those who are (or want to be) familiar with the terms, those who are not can safely ignore the analogy and move on. Understanding the analogy is not essential to the understanding of the rest of the article.

**Comment by annezazu** [comment]
Looping back on this and am going to close this issue out as, beyond an analogy that isn't critical to understanding the documentation, there's not much more to go on here. With that said, I'd love to have more insight into what else could improve this specific page :) so, if anything else comes to mind, please share here and I'll be happy to re-open.
