### ISSUE TITLE
Migrate wp-env to use simple-git instead of nodegit

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#26660]
With the new LTS upgrade (14.15.0), the `nodegit` prebuilt binary is not yet available and requires being built from source. This is an extra complication to require everyone using wp-env to have all the dependencies installed.

This also highlighted that we probably don't need all the features of `nodegit` and could probably switch over to use `simple-git` that does have a requirement that git be installed locally, but that is safe tto assume and require for the project, since you need git to check out the project.

**Comment by gziolo** [comment]
It might also work if we upgrade to the latest version of `nodegit`:

https://github.com/nodegit/nodegit/releases/tag/v0.27.0

> Prebuilds for Node 14, deprecate Node 8

**Comment by mkaz** [comment]
I'm not sure how important it is or not, but it looks like converting to simple-git will lose the progress indicator when cloning the repo. The current NodeGit provides a callback with progress, simple-git does not have that feature.

Used here: https://github.com/WordPress/gutenberg/blob/master/packages/env/lib/download-sources.js#L111-L121

With the upgrade in #26712 this issue is fairly low priority, I think it would lighten the overall package, so probably still worth doing.

**Comment by gziolo** [comment]
I see this issue in `simple-git` repository:

https://github.com/steveukx/git-js/issues/265

It isn't impossible but this would require some time investment to refactor. I'm wondering how much time it takes to install each library and what is the size difference on the disk. Maybe it's fine to keep `nodegit`.

**Comment by noahtallen** [comment]
I agree that it's probably not a big issue for us. One nice thing is that wp-env can be used outside of Gutenberg, so it might not be safe to assume git is available. (Though to be fair, I do agree it's very likely available most places.)

**Comment by noahtallen** [comment]
I'm thinking we should get this done. When installing via `npm i -g @wordpress/env`, it continues failing if I don't have a specific Node version available (`nvm use 14` makes it work.) I think it's worth supporting current NodeJS, as well as the LTS version, and as far as I can tell, nodegit is the only thing preventing us from doing so. If they updated more quickly to address this issue, maybe we could stick with it... But as is, I don't see a new release since the one we have installed.

But yeah, I agree that simple git would be simpler (ha) for us to maintain.

**Comment by ockham** [comment]
Here's one more reason to migrate to `simple-git` (https://github.com/WordPress/gutenberg/pull/28741#issuecomment-774166903):

> I think the underlying issue is that `nodegit` is a rather low-level API wrapper for `libgit2` -- where things like `checkout` have a rather different meaning from their `git` CLI counterparts we all are used to.
>
> I've noticed that for the GB release tools, we use a different git library, [`simple-git`](https://github.com/steveukx/git-js): https://github.com/WordPress/gutenberg/blob/8d1d96d6945c03a5759586b7ab7903e99164765a/bin/plugin/lib/git.js#L4
OTOH, `nodegit` is only used by `wp-env`'s download script.
>
> So I think that he fact that `nodegit` is low-level and complex, and that there's `simple-git`, and that we're already using it :smile: is a good indicator that we might want to migrate the `wp-env`'s download script to `simple-git`, too :grimacing:

**Comment by ockham** [comment]
As for the progress meter, there's another upstream issue which seems to have more information (and a recipe?): https://github.com/steveukx/git-js/issues/529

**Comment by noahtallen** [comment]
nice. I also don't think that progress should block this move 😅 

Btw, I did start poking around at switching, but never pushed the branch. I'll see if I can find it today :)

**Comment by noahtallen** [comment]
Here's what I started a couple weeks ago: #28804. I didn't make a ton of progress, but I think it at least will clone the repo. Needs a lot of polished around other cases though. I don't know how much time I have to continue working on it in the next week, but feel free to continue with it if you have time ;)
