### ISSUE TITLE
Duplicate generated classNames when using useBlockProps.save()

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#26672]
**Describe the bug**
When using the `useBlockProps.save()` function like this:

```js
save: () => {
    return (
        <div {...useBlockProps.save()}>
            Example Block New
        </div>
    )
}
```
with `color` in the block `supports` I get all the auto generated classNames output twice: 
```html
<div class="wp-block-example-example-new alignwide has-background has-background" style="background-color:#a26a79">Example Block New</div>
```

**To reproduce**
You can replicate it with this Block setup: 
```js
import { registerBlockType } from '@wordpress/blocks';
import { useBlockProps } from '@wordpress/block-editor';
import { __ } from '@wordpress/i18n';

const NAMESPACE = 'example';

registerBlockType( `${ NAMESPACE }/example-new`, {
    title: __( 'Example Block (New)', NAMESPACE ),
    description: __( 'Example Block', NAMESPACE ),
    icon: 'smiley',
    category: 'common',
    example: {},
    supports: {
        html: false,
        lightBlockWrapper: true,
        align: true,
        anchor: true,
        color: {
            link: true
        },
    },
    attributes: {},
    transforms: {},
    variations: [],
    edit: () => {
        return (
            <div {...useBlockProps()}>
                <p>Hello World</p>
            </div>
        )
    },
    save: () => {
        return (
            <div {...useBlockProps.save()}>
                Example Block New
            </div>
        )
    }
} );
```

**Expected behavior**
The classes should only be generated once. 

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [ gutenberg plugin ]
- If the Gutenberg plugin is installed, which version is it? 9.2.2

**Comment by talldan** [comment]
I could reproduce using both `lightBlockWrapper` and the newer `apiVersion: 2`.

**Comment by talldan** [comment]
Seems I made a mistake in my previous testing, `apiVersion: 2` doesn't have this issue.

#27189 should fix the issue for blocks still using `lightBlockWrapper`.
