### ISSUE TITLE
render_callback arguments (add name?)

### ISSUE THREAD

**Issue by determin1st** [WordPress/gutenberg#26678]
Imagine multiple block types with a single `render_callback`.. each one has different attributes parameter, but single, basic renderer, which creates similar item (html markup), so, it's hard to guess block type (name) from:

```
<!-- wp:sm-blocks/view-modifier {} /-->
```

in a common callback:

```
function renderBlock($attributes, $content) {...}
```

one way to create closures or put additional attribute with name (either in JSON markup or in PHP attributes array), but  the straight-way solution is to add one more accepted argument to the callback itself:

```
function renderBlock($attributes, $content, $name) {...}
```

where name will be `view-modifier`, very nice design solution, what you think :]

**Comment by talldan** [comment]
@determin1st There is a third argument for the `render_callback`. The third argument is a `$block` object that has a name property `$block->name`, so what you propose should already be possible.

I don't think it has been very well documented yet, there a task here for documenting some features of dynamic blocks:
https://github.com/WordPress/gutenberg/issues/26409

In the existing document there's a brief mention in the block context documentation:
https://developer.wordpress.org/block-editor/developers/block-api/block-context/#php
