### ISSUE TITLE
Custom HTML Embed for Instagram ignoring the remove Captions option

### ISSUE THREAD

**Issue by kujain** [WordPress/gutenberg#26679]
**Describe the bug**
I am using the custom html block to be able to embed an instagram post without including a caption. But the output still displays the caption.

**To reproduce**
1. Go to an instagram post and get the embed code.
2. Uncheck Include caption.
3. Copy this code into a custom html block in the editor
4. Save and view in editor and frontend.

**Expected behavior**
The instagram post should show up without the caption since the code copied has no reference to it.

**Screenshots**
Insert:
![image](https://user-images.githubusercontent.com/120631/98056976-3061f180-1e0f-11eb-99d2-aad84f2c1b77.png)
![image](https://user-images.githubusercontent.com/120631/98057036-4f608380-1e0f-11eb-83bb-938631da6202.png)
Display: 
![image](https://user-images.githubusercontent.com/120631/98057329-078e2c00-1e10-11eb-8181-f6d8fb0fbdfa.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it? 8.9.1

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 86

**Additional context**
- This may be related to the change in the oembed architecture at Facebook and Instagram end. We are using Jetpack 9.0.1 for the updated instagram embeds, but we have been using the custom html approach when we want to customize the caption removal, since the simple embed tool provides no options. This used to work earlier, but now it has stopped working.

**Comment by theoneamradio** [comment]
I'm experiencing the same issue.

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7
Gutenberg plugin 10.1.1
Twenty Twenty One

Went to Instagram found a post which had captions.
Clicked the 3 dots and then embed and unchecked the caption.

![Screen Shot 2021-03-18 at 20 26 05](https://user-images.githubusercontent.com/5323259/111685427-31c51100-8828-11eb-8ba1-064e95acae4d.png)

Went to Gutenberg page.
Added a custom HTML block.
Added the Instagram embed code.
Clicked Preview and noticed no caption.

![Screen Shot 2021-03-18 at 20 26 38](https://user-images.githubusercontent.com/5323259/111685566-5d47fb80-8828-11eb-80e0-180b73997e86.png)


Checked the frontend and noticed no caption.

![Screen Shot 2021-03-18 at 20 28 33](https://user-images.githubusercontent.com/5323259/111685707-87012280-8828-11eb-82aa-15422439342a.png)

I would say that this issue has been fixed and will go ahead and close it. The issue can always be reopened if need be.

**Comment by mattyrjackson** [comment]
This only shows without caption in 'edit page' mode. When viewing preview, or the actual webpage, you get a black rectangle where the post should be.

Looking on https://wordpress.org/support/topic/show-instagram-post-without-captions/ , it seems this caption 'issue' cannot be resolved.

Note, this Github thread is from an earlier date than the wordpress counterpart, so I am inclined to trust their is still a remaining 'issue'.
