### ISSUE TITLE
Gutenberg Gallery block does not center in Full Width Template.

### ISSUE THREAD

**Issue by PHuhn** [WordPress/gutenberg#26674]
**Describe the bug**

Gutenberg **Gallery** block does not center in **Full Width Template**.

**To reproduce**

Add a new page.
In page Title enter Gallery
In the **Document** Settings tab in the _Page Attributes_ select the **Full Width Template**
Click in the **+** sign and navigate to the _Media_ group and select the **Gallery** block.
Select an image in the media library.
In the Gallery menu bar, click on the Change alignment icon and select **Align center**.
Click the Publish and Public again.
View the page
It appears flush left

**Expected behavior**

The image should appear in the center.

**Screenshots**

![image](https://user-images.githubusercontent.com/4923355/98040635-95f1b600-1dee-11eb-9dfa-6c02529c96f2.png)

** Page Source **

```
<!-- wp:gallery {"ids":[21],"align":"center"} -->
<figure class="wp-block-gallery aligncenter columns-1 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="http://localhost:9137/wp-content/uploads/2020/06/cv-165px.jpg" alt="Connected Vehicle" data-id="21" data-full-url="http://localhost:9137/wp-content/uploads/2020/06/cv-165px.jpg" data-link="http://localhost:9137/cv-165px/" class="wp-image-21"/></figure></li></ul></figure>
<!-- /wp:gallery -->
```

**Editor version (please complete the following information):**

- WordPress version: 5.5.3
- No Gutenberg pluggin

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome

**Additional context**

This is from:
[Gallery with Full view template](https://wordpress.org/support/topic/gallery-with-full-view-template/)
hmanley (@hmanley)
When I use gallery with the Standard template the Gallery is fine on the center. If I change to Full view template the Gallery goes to the left side of the page.

**Comment by talldan** [comment]
I could reproduce, seems easiest to repro when only one image is used in the gallery, and that image is a smaller size.

**Comment by carolinan** [comment]
Since you are mentioning _In the Document Settings tab in the Page Attributes select the Full Width Template_
Is this only an issue with Twenty Twenty?
Were you able to reproduce this with other themes?

**Comment by PHuhn** [comment]
I did not try any other theme.

**Comment by PHuhn** [comment]
The 2019 theme does not have a full width template.  In the default template for 2019 theme, it does not center the image or images.

**Comment by glendaviesnz** [comment]
I couldn't replicate this in TwentyTwenty theme with the new version of the Gallery block (WP 6.0, GB 13.6). With single images in the Gallery for me the image expands to fill the available width now, so is naturally centered.
