### ISSUE TITLE
simplified JSON parameter (renderer attributes)

### ISSUE THREAD

**Issue by determin1st** [WordPress/gutenberg#26677]
not convenient to type strict JSON as an argument:
```
<div>
  <!-- wp:sm-blocks/base {

    "class":      "view-modifier",
    "parameter1": 20,
    "param2":     "someString"

  } /-->
</div>
```

compared to the simplified ideal:

```
<div>
  <!-- wp:sm-blocks/base {

    class:          "view-modifier"
    parameter1:      20
    param2:          "someString"
    "this-has-dash": null
    thisHasCamel:    true

  } /-->
</div>
```

looks better, right? probably some parsers are already available

**Comment by talldan** [comment]
@determin1st I'm not completely sure what you mean by this, when would you have to type the json?

**Comment by determin1st** [comment]
> @determin1st I'm not completely sure what you mean by this, when would you have to type the json?

Well, i'm designing some blocks (for WordPress) and they don't have design frontend yet, because i didn't fully sure which attributes and names they will have, so, to speedup the process i pass parameters right in HTML markup of the page..

```php
$o = <<<EOD

<div class="view-config">
  <!-- wp:sm-blocks/limit-selector {

    "limits":  [16,32,64],
    "current": 0

  } /-->
  <!-- wp:sm-blocks/mode-selector /-->
</div>

EOD;
echo apply_filters('the_content', $o);
```

these parameters (specified in JSON) then come to the attributes of the `render_callback`:

```php
function renderLimitSelector($attr, $content)
{
  var_dump($attr['limits']); # will be [16,32,64]
  return '';
}
```

registered previously with `register_block()`, so the one case i would prefer typing it is to speedup my test cycles while making those blocks, the second may be a pre-designed template php file (so it's designed in the text editor, not gutenberg designer controls).

**Comment by talldan** [comment]
Thanks for the suggestion, but given this seems to be a very rare use-case I don't think there would be value in overhauling the parsing aspect of the block editor.
