### ISSUE TITLE
Consider having only one inserter for mobile

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2668]
My test so far is only with an iPhone 7 plus, part of this is we need to run some extensive testing. However, initially anyone I think will get the same issues. The inserters (top and one in content) both have unpredictable behaviour. For example, they jump and are hidden behind various sections. Just some of these 'interesting' positions include:

![img_1437 png](https://user-images.githubusercontent.com/253067/30073005-18124ea2-9264-11e7-93f1-bdf420275ba0.png)

![img_1438 png](https://user-images.githubusercontent.com/253067/30073010-1a7be342-9264-11e7-96f9-90df7db60763.png)

At one point the entire screen zoomed - without me zooming....

![img_1436 png](https://user-images.githubusercontent.com/253067/30073024-295327d6-9264-11e7-9f3e-c9c529691e32.png)

What I think we need to do is maybe consider just one inserter for mobile. Why this approach? I feel we can be consistent then and when you have a small screen, it just doesn't need both. I would suggest in this case the top one maybe the best option. I am not fully against the bottom one being used but you can easily get this:

![img_1446 png](https://user-images.githubusercontent.com/253067/30074060-f14b42de-9267-11e7-8ceb-d71fbaed5645.png)

Along with this, some work will need to be done on the visual tidy for the top inserter, it can go very 'unusual' in places. That said, reducing to one for mobile I think will limit the issues with this experience. What do people think?

**Comment by aduth** [comment]
Also #2471, #1280, #2602

**Comment by aduth** [comment]
Specifically at https://github.com/WordPress/gutenberg/issues/2602#issuecomment-325980530 I propose one option which is to open inserter not as anchored to the button, but as a modal of sorts in smaller screens.

**Comment by karmatosed** [comment]
Thanks for context. I feel we should condense these into one issue. What do you think? I'm fine with this one being that or closing this and doing with others.

Before we step into the best design option. What are the limits placed on this from a code view? Am I right there are some?

**Comment by aduth** [comment]
Yes, it would be good to consolidate the issues. The technical challenges are best summarized at https://github.com/WordPress/gutenberg/issues/2602#issuecomment-325980530, specifically around how to handle the case that there's no suitable opening direction for a popover, which is the issue here.

**Comment by karmatosed** [comment]
Closing as we now have a single place to include all issues in #2691
