### ISSUE TITLE
When I use a Gutenborge editor editing a “Media & Text”block, it won't work.

### ISSUE THREAD

**Issue by kuanos** [WordPress/gutenberg#26681]
The problem is : I want the image on the left and text on the right and they are on the same horizontal line, so I use the “Media & Text” style block.
It looked good on the editing screen, but when I publish the post, I checked the post, it showed a regular looking, the image was above the text. 
<img width="1140" alt="截屏2020-11-04 下午1 30 28" src="https://user-images.githubusercontent.com/10093751/98072915-10c7d900-1ea2-11eb-87aa-424e5747426f.png">
<img width="760" alt="截屏2020-11-04 下午1 32 04" src="https://user-images.githubusercontent.com/10093751/98072941-26d59980-1ea2-11eb-8f0a-fce900673ea6.png">

I have tested the other function of the editor(not all), it works very well.
I have created a new user(author) to test if it's my user's fault, and it's not.

how can I put the image and the text on the same line? thank you very much!

**Comment by talldan** [comment]
@kuanos Thanks for reporting. This could be a theme issue, would you be able to share what theme you're using?

**Comment by kuanos** [comment]
@talldan Thanks for helping, my website is using Impreza 7.10 theme, I will try another theme to test again.

**Comment by kuanos** [comment]
@talldan Yes, it's the theme problem, thank you very much!
