### ISSUE TITLE
Editor Scroll issue when no block patterns are defined

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#26688]
**Describe the bug**
When removing the theme support for 'core-block-patterns' `remove_theme_support( 'core-block-patterns' );` and not having any custom Block Patterns the editor scrolls past the content area into a white void.

<img width="1621" alt="Screen Shot 2020-11-04 at 10 58 03" src="https://user-images.githubusercontent.com/20684594/98096957-a0628d00-1e8c-11eb-86f8-9817fe01f2e9.png">

**To reproduce**
add `remove_theme_support( 'core-block-patterns' );` to a theme.
make sure no other patterns are there 
navigate to the editor 
scroll down and see the overflow.

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? no plugin

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Safari
 - Version 14.0

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting. 

I'm unable to reproduce this as shown in the video. 

https://user-images.githubusercontent.com/955351/103415809-c1282580-4b51-11eb-8100-36d8551a96af.mp4

Could you verify this is still an issue for you using the latest version of WordPress as well as installing and activating the Gutenberg plugin?

**Comment by fabiankaegy** [comment]
@skorasaurus  I just tested it with a clean new wordpress install that has no plugins installed, runs WordPress 5.6 and has a custom theme that does nothing expect `remove_theme_support( 'core-block-pattern' )`.

https://user-images.githubusercontent.com/20684594/103417263-50e9c600-4b8a-11eb-9503-023edbf8fcfb.mov

`functions.php`
```php
<?php

add_action( 'after_setup_theme', function() {
    remove_theme_support( 'core-block-patterns' );
} );
```

`index.php`
```php

```

`style.css`
```css
/**
 * Theme Name:  example
 * Description: The only thing this plugin does is remove_theme_support( 'core-block-patterns' )
 * Author:      fabiankaegy
 * Version:     1.0.0
 * Tags:
 * Text Domain: example
 */
```

<details>
<summary>Here is all of the site info:</summary>
`
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: undefined
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 43.22 MB (45321076 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 348.00 B (348 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 28.00 B (28 bytes)
database_size: 2.13 MB (2228224 bytes)
total_size: 45.35 MB (47549676 bytes)

### wp-active-theme ###

name: example (demo)
version: 1.0.0
author: fabiankaegy
author_website: (undefined)
parent_theme: none
theme_features: undefined
theme_path: /var/www/html/wp-content/themes/demo
auto_update: Disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 8
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.121-linuxkit x86_64
httpd_software: Apache/2.4.38 (Debian)
php_version: 7.4.13 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.5.8-MariaDB-1:10.5.8+maria~focal
client_version: mysqlnd 7.4.13

### wp-constants ###

WP_HOME: http://localhost:8888/
WP_SITEURL: http://localhost:8888/
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`
</details>

**Comment by skorasaurus** [comment]
Thanks for all of the details and the theme, I've duplicated your theme and I'm still not able to reproduce (using gutenberg 9.8.1); perhaps this is a browser issue exclusive to safari? Could you test on another browser? (I only have access to chrome, firefox).

**Comment by fabiankaegy** [comment]
I have just tested this again on Chrome and on Firefox and it appears on both like I showed in the video. 

I am however like mentioned in the previous comment using core. So no Gutenberg plugin.

**Comment by skorasaurus** [comment]
Could you try using the gutenberg plugin? (available at wordpress.org/plugins/gutenberg

**Comment by skorasaurus** [comment]
Thanks for the clarification on the plugin, I missed that earlier, silly me. I still can't reproduce it, even when disabling gutenberg plugin; I'm using a vanilla site - just recreated my db and install; and used your theme. Unfortunately, i can't spend any more time on this today.

**Comment by fabiankaegy** [comment]
I am no longer able to replicate this in Gutenberg 13.0 :)
