### ISSUE TITLE
Spacer block does not accept typed in height values in the Spacer settings input field

### ISSUE THREAD

**Issue by korynorthrop** [WordPress/gutenberg#26693]
**Describe the bug**
The input field in the _Spacer settings_ panel does not properly set values that are typed in. 

**To reproduce**
1. Add a Spacer block to a post
2. Click on the block to access the _Spacer settings_ panel
3. Click on the height input field and select the current value
4. Type in a new value (e.g. 65)
5. Notice that the typed in value is not set, instead the input shows a different value

**Expected behavior**
I expect the input field to set the typed in height value and then see the new value reflected in the Spacer block itself in the Gutenberg editor.

**Screenshots**
Here is a screenshot of the issue, the values I typed into the height input field were "65" and then "30" which resulted in "205" and "200" respectively.

![spacer height](https://user-images.githubusercontent.com/5252550/98123439-b65d5700-1e66-11eb-874a-774d7fef97d2.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.3.3
- Using the default block editor that comes with this version of WordPress

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version 82.0.2

**Comment by talldan** [comment]
Thanks for reporting @korynorthrop. 

This issue has been fixed in recent versions of the Gutenberg plugin. A fix will be in the upcoming WordPress 5.6 release.

This is the changed that fixed it if you're interested - https://github.com/WordPress/gutenberg/pull/25528. In that change the minimum height of the spacer was also reduced to 1px.

**Comment by korynorthrop** [comment]
@talldan thanks for the follow-up, sorry I didn't see the other issues that addressed this bug. Glad to see that it'll be sorted out in the upcoming releases.
