### ISSUE TITLE
Allow Cyrillic letters in URL input box

### ISSUE THREAD

**Issue by savevjr** [WordPress/gutenberg#26694]
**Is your feature request related to a problem? Please describe.**
Hi, everyone! I have difficulties setting up URLs with cyrillic letters in it. The input box in Document settings always cleans up the cyrillic letters **on blur**.

**Describe alternatives you've considered**
Currenlty I'm changing the URL on `/wp-admin/edit.php` via **Quick edit** option.

---
I saw a cleaning RegEx in file `clean-for-slug.js` which removes all non Latin letters.
https://github.com/WordPress/gutenberg/blob/004a32ec09d5b789be694d85725fe49cca385f08/packages/url/src/clean-for-slug.js#L29

**Comment by jordesign** [comment]
Closing this in favour of #26694
