### ISSUE TITLE
Unable to select a slash commands on mobile

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2669]
I was testing mobile to start with an iPhone 7 plus and tried slash commands, unfortunately they don't seem to work. My thinking on this was that they actually could be pretty useful for mobile users. Of course it is an advanced feature but as you got used to it having them on mobile could really help the flow.

![img_1444 png](https://user-images.githubusercontent.com/253067/30074215-96dab220-9268-11e7-89c4-961fcdbc3420.png)

Try as I might, I simply couldn't select the command.

**Comment by EphoxJames** [comment]
This might have been because of the blur code (which was hiding the buttons as you clicked them) so it is possible that this has already been fixed.

**Comment by karmatosed** [comment]
This is still an issue for me in testing.

**Comment by aduth** [comment]
This will be fixed by #3235, still pending review.
