### ISSUE TITLE
Improve discoverability of reordering and deleting of blocks for mobile

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2670]
Currently there is no way to reorder or delete blocks on mobile. I tested on an iPhone 7 Plus. Adding something in to allow this would be great.

![img_1445](https://user-images.githubusercontent.com/253067/30074377-41cf69dc-9269-11e7-82df-ec934d8eceec.PNG)

What do people think about adding something in for this? I at least think deleting a block should work.

**Comment by mtias** [comment]
There is: select block, click on ellipsis button in the block toolbar.

**Comment by karmatosed** [comment]
Changing title to discoverability as that totally was the issue here. I did not find them and as a result assumed they weren't there! Could we add in swipe or something over the block to make it at least top level discoverable?

**Comment by karmatosed** [comment]
This feels better now so closing and we can review after 1.7 the mobile changes.
