### ISSUE TITLE
Video block: Full width mode not working in Editor

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#26700]
**Describe the bug**
In the editor the video block doesn't display correctly when in full width mode

**To reproduce**
1. Go to the editor
2. Insert a video block
3. Make the block full width
4. Notice that the video itself doesn't stretch to the full width of the browser
5. Open the post in the front end
6. Notice that the video does fill the whole window.

**Expected behavior**
I expect the frontend to match the editor

**Screenshots**
Editor:
<img width="1071" alt="Screenshot 2020-11-04 at 16 51 11" src="https://user-images.githubusercontent.com/275961/98141219-4aa6d880-1ebe-11eb-92a7-172ac36d6b0d.png">

Frontend:
<img width="1440" alt="Screenshot 2020-11-04 at 16 51 25" src="https://user-images.githubusercontent.com/275961/98141226-4c709c00-1ebe-11eb-9ead-0a313ca5b9b9.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? running development version - master branch
- I don't see the problem on my wordpress.com site

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 86

**Additional context**
- Originally reported here: https://github.com/Automattic/themes/issues/2333

**Comment by tellthemachines** [comment]
Hmm, I can't reproduce this on any of the default themes that support full width for the Video block. Which theme did you test this on?

**Comment by scruffian** [comment]
This was in twentytwenty

**Comment by tellthemachines** [comment]
Hmm, I can't reproduce this on Twenty Twenty with the latest master and WP 5.6 RC1. Did you have any other plugins enabled?

**Comment by scruffian** [comment]
No. Maybe it depends on the video file? I'm using this one:

https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4

**Comment by tellthemachines** [comment]
Correct, it's the file size: I can reproduce the issue with the above video. Changing [this line](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/video/style.scss#L7) to `width: 100%` seems to fix it.

**Comment by scruffian** [comment]
I'd guess we should only do that in the case where the video is set to 100% wide...

**Comment by tellthemachines** [comment]
> I'd guess we should only do that in the case where the video is set to full width.

It's fine to do it globally, because the actual width for different alignment options is set on the parents (either the `figure` or its wrapping `div`), so the `video` will only ever be 100% of whatever width is defined there 🙂

**Comment by scruffian** [comment]
Fix here: https://github.com/WordPress/gutenberg/pull/27328

**Comment by carolinan** [comment]
Hi, can this be closed?

**Comment by scruffian** [comment]
Thanks
