### ISSUE TITLE
Auto Draft set as post title in email updates (redux)

### ISSUE THREAD

**Issue by pauljacobson** [WordPress/gutenberg#26718]
**Describe the bug**

A user reported that they receive email updates for new posts that have empty content, and an "Auto Draft" post title. This is not occurring consistently for all posts, although it seems to be a recurrence of #17628

**To reproduce**

Steps to reproduce the behavior (according to the user):

1. I copy the post from the same week last year. I mark all the words and press copy (Ctrl + c)
2. I create a new post and add a title
3. I insert the copied text
4. I choose a featured picture
5. I press publish

The user indicated that they follow the same approach with every post (those that manifest the issue, and those that don't), with the only real difference being the choice of image for the featured image.

**Expected behavior**

When creating a new post, even with copied content from a previous post -

- the published post should contain the post title that the user sets, and 
- the title and content should be conveyed in email updates for that post.

**Screenshots**

<img width="750" alt="Markup 2020-11-05 at 09 26 03" src="https://user-images.githubusercontent.com/2912202/98210708-a5d1dd00-1f49-11eb-8127-0d59982a35fc.png">

**Editor version (please complete the following information):**

- WordPress version: 5.5.1
- Block editor by default on a WordPress.com site running Gutenberg v9.2.2

**Desktop (please complete the following information):**

 - OS: TBC
 - Browser: TBC
 - Version: TBC

**Smartphone (please complete the following information):**

 - Device: TBC
 - OS: TBC
 - Browser: TBC
 - Version: TBC

**Comment by SBATHOMPSON** [comment]
Users device information:

Device: Laptop // macOS High Sierra (did not include version)

Browser: Safari version 13.1.2

User did not use an app or report Smartphone information

**Comment by kriskarkoski** [comment]
This issue can be closed as it's WordPress.com-specific and has been moved to our repo.
