### ISSUE TITLE
Reusable block confirmation message is not translated

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#26714]
From https://core.trac.wordpress.org/ticket/47917.

---

The confirmation message displayed when deleting a reusable block is not translated.

/wp-includes/js/dist/block-editor.js:17631
{{{
var hasConfirmed = window.confirm(Object(external_this_wp_i18n_["__"])('Are you sure you want to delete this Reusable Block?\n\n' + 'It will be permanently removed from all posts and pages that use it.'));
}}}

This message is translated in the Gutenberg plugin.

I think there is a problem with extracting text for translation.

**Comment by noisysocks** [comment]
The problem is that we're concatenating the string given to `__()` here:

https://github.com/WordPress/gutenberg/blob/b34ecc23f89066e3e7bb710136efa46e29ebe025/packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-delete-button.js#L80-L83

We need to remove the `+`.

**Comment by wallstead** [comment]
I'm going to try this as my first issue.

**Comment by wallstead** [comment]
@noisysocks I'm running into a problem fixing this, I'm wondering if you can help. I have a local WP environment running with wp-env as [mentioned here](https://developer.wordpress.org/block-editor/contributors/develop/getting-started/#using-wp-env-to-install-a-local-environment). I have the Gutenberg plugin building correctly, and the plugin is activated. 

My problem is that _none_ of the i18n translations are running through the plugin. If I deactivate the plugin, I can see the correct translations and lack of this specific translation, but once activated all JS-based i18n translations are not running.

My hunch is that I may need to use `wp_set_script_translations()` to set up translations as [mentioned here](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/internationalization.md), but I'm wondering if there is an obvious solution I'm missing.

**Comment by wallstead** [comment]
Ahh it was just a matter of going to /wp-admin/update-core.php and clicking update translations. I wonder if this should be added to a doc? I couldn't find that anywhere.  

Anyway, I'm unblocked!

**Comment by wallstead** [comment]
With no code changes, I am seeing the correct translation for "Are you sure.." in French.

![image](https://user-images.githubusercontent.com/9662992/98852249-4160c300-240c-11eb-9c72-5b8a8f53f91a.png)

This must have already been fixed?

**Comment by noisysocks** [comment]
Hm, odd. I wonder if plugin translations treat the `+` differently to how Core treats it? I can't think of why else https://core.trac.wordpress.org/ticket/47917 is a problem.

To be safe, I'd probably just remove the `+` even if it seemingly makes no difference...

**Comment by Mamaduka** [comment]
I think we can close this issue since we removed the string in question via #27026.
