### ISSUE TITLE
Image Block Settings column scroll bar goes psychotic at 1080p

### ISSUE THREAD

**Issue by JasonWoof** [WordPress/gutenberg#26711]
The Block Settings column for Image blocks flickers out forever in Chrome when the browser window is a certain height. It looks like this:

![flicker](https://user-images.githubusercontent.com/31515/98185728-3a512680-1edb-11eb-9260-4fb3a9f7418b.gif)

The hard solution would be figuring out how the content of that thing gets shorter when the available space gets narrower.

Or you could just set the scrollbar to always be visible by putting this in the right place: `overflow-y: scroll;`

I recommend always making the vertical scrollbar visible, because then you get the added benefit of the sidebar content not changing width when it's contents get taller (eg when clicking the expandable sections).

A note on reproducing: You need to get the _content area_ (ie not including the border, title bar, resize handles, etc whatever yours has) of the chrome browser window to be about 1080px tall. This may be difficult or impossible in your windowing environment if your screen is 1080px tall or less. This cannot be reproduced in the chrome developer tools responsive/mobile emulator thing because the scroll bars in that mode do not push the content over to make room.

**Comment by talldan** [comment]
Thanks for reaching out and reporting this @JasonHoffmann. This was already reported in #24611, so I'll close your issue as a duplicate. I've also noticed this more and more recently, current theory is that the block previews in the Styles panel are the cause because they dynamically resize.
