### ISSUE TITLE
Setting Default Style in Button block doesn't make post dirty

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#26716]
From https://core.trac.wordpress.org/ticket/48750.

---

When I change the Default style of the button after the update button still **Disabled**.

if change other properties after the update button enabled but not updated button's Default style value.

edit the same post in another browser or private browser and Button Default style value appear as `Not Set`.

![button-default-style-issue](https://user-images.githubusercontent.com/612155/98201915-e69b1780-1f84-11eb-9b53-26fdaa76916e.gif)

**Comment by noisysocks** [comment]
According to the reporter in the ticket this also affects the Image and Table blocks.

**Comment by jasmussen** [comment]
I'm seeing this solved in trunk:
![dirty](https://user-images.githubusercontent.com/1204802/150105059-4598fb51-8435-49f5-b127-644b8e08d318.gif)

Is this one good to close?
