### ISSUE TITLE
WP 5.3 can't longer use editPost to change content

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#26717]
From https://core.trac.wordpress.org/ticket/48813.

---

Since WP 5.3 and also in the newest development version of WordPress.
It's impossible to change the content of the editor with:

```
wp.data.dispatch( 'core/editor' ).editPost( { title: 'My awesome title, will be set.', content: 'My awesome content will no longer be set :c' } );
```

in all versions before it just worked perfectly but since 5.3 it's broken.
The title and everything else can still be changed only the content is inaccessible now.

Why is this and how can I fix it? Respectively what is the new way to change the content?

**Comment by gwwar** [comment]
I'm guessing this is mostly an internal implementation change. I'm not sure if this is a bug. If we inspect the redux actions, content is being updated in the post object, however the editor isn't parsing that updated content to update blocks. Does that sound about right @youknowriad @ellatrix ?

| It is updated in state, just not re-parsed |
|-----|
| <img width="1215" alt="Screen Shot 2021-03-11 at 8 24 59 PM" src="https://user-images.githubusercontent.com/1270189/110891985-07afa400-82a8-11eb-88e7-70e4c689d62f.png"> |

### The alternative would be something like the following:
```js
const blocks = [ wp.blocks.createBlock('core/paragraph', { 'content': "Hello" } ), wp.blocks.createBlock('core/paragraph', { 'content': "World" } ) ];
wp.data.dispatch( 'core/editor' ).resetEditorBlocks( blocks );
wp.data.dispatch( 'core/editor' ).editPost( { title: 'New Title' } );
```

https://github.com/WordPress/gutenberg/blob/f8052e179a740642b56653968135990bb298d5b3/packages/editor/src/store/actions.js#L587-L629

**Comment by kathrynwp** [comment]
@youknowriad @ellatrix Would either of you be able to take a peek at @gwwar's question above ? I've marked this as stale in the meantime, since there's been no movement in over a year. Thanks!

**Comment by Mamaduka** [comment]
Hey, @noisysocks

Can we close this issue? It seems this hasn't caused any issues in the last ten releases.

**Comment by priethor** [comment]
Let's close this issue for now, as @Mamaduka suggests, and open it again if necessary 🙏

**Comment by frougeot2** [comment]
I used in WP 5.5 the code wp.data.dispatch( 'core/editor' ).editPost( { excerpt: ...
but it does not work anymore in WP 5.6. How should i change it to modify the excerpt now ?
