### ISSUE TITLE
Vertical Alignment Toolbar: Consider rewriting align options

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#26729]
**Describe the bug**
I think now the options description should be reduced.
I think removing the `Vertically`word from there could work. Also, we should remove the uppercase for not-first words.

**Expected behavior**
See the vertical options as `Vertical top`, `Vertical middle` and `Vertical bottom`

**Screenshots**
<img src="https://user-images.githubusercontent.com/77539/98256205-0ae2fe00-1f5d-11eb-8216-fd0897415547.png" width="500px" />

**Comment by khoipro** [comment]
Good catch! I think the word should be shorter and your feedback is same like my idea!

**Comment by gaavar** [comment]
- Hi! I am new to open source and was interested in the task. Can I work on it?

**Comment by retrofox** [comment]
> * Hi! I am new to open source and was interested in the task. Can I work on it?

yes, definitely you can!. I leave the [designers/developers support page](https://github.com/WordPress/gutenberg/tree/master/docs/designers-developers/developers), just in case.

**Comment by simono** [comment]
Hi @retrofox, could you please clarify your proposed solution? Should the text be something like "Vertical top" or "Align top"? Thanks 😄

**Comment by retrofox** [comment]
> Hi @retrofox, could you please clarify your proposed solution? Should the options be something like "Vertical top" or "Align top"? Thanks 😄

Actually, I'm not sure! I just created the issue 😅 . @mapk, do you have some advice here? Thanks in advance

**Comment by simono** [comment]
The Button in the toolbar has the label "Change vertical alignment". So maybe "Top, Middle, Bottom" would suffice.

**Comment by mapk** [comment]
👋  Great idea, @retrofox. Let's drop the word "vertically" from each of the options. So instead it will read, 

- Align top
- Align middle
- Align bottom

And it would _align_ (pun intended) better with the text alignment selections.

![Screen Shot 2020-11-16 at 3 50 12 PM](https://user-images.githubusercontent.com/617986/99321848-985b0380-2823-11eb-973f-2a49a8ce4599.png)
