### ISSUE TITLE
"Add Block" pop-up menu crashes

### ISSUE THREAD

**Issue by mcampal** [WordPress/gutenberg#26735]
**Describe the bug**
When adding a new block through the plus button over a page or post content, and you try to choose from all available blocks, you are supposed to type some text in a search field. If the first character you type is either a, e, g, l, s, w or 8 the popup disappears.

**To reproduce**
1. Edit any page or post
2. Click on the "+" button to add a Block
3. Type any of the following characters: a, e, g, l, s, w or 8 
4. The pop-up menu crashes

**Expected behavior**
The filter should apply and display the available Block's list

**Screenshots**

![Popup_menu_dissapears](https://user-images.githubusercontent.com/72819905/98263658-d9226500-1f65-11eb-901a-008efdc111da.gif)

**Editor version (please complete the following information):**
- WordPress Version 5.5.3
- Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS Mojave
 - Browser: Chrome
 - Version: 86.0.4240.111

**Comment by talldan** [comment]
I've just tested and I couldn't reproduce the issue. @mcampal Are there any third party blocks or patterns you have installed that might trigger from a search using those letters?

**Comment by annezazu** [comment]
Closing this out since we haven't heard back. If you replicate with the latest version of Gutenberg without any additional plugins installed, please re-open. For now, I was unable to replicate with Gutenberg 9.6.2 and WordPress 5.6.
