### ISSUE TITLE
REST API error when getting users with non-admin role

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#26747]
**Describe the bug**

```
GET http://localhost:8888/gutenberg/index.php?rest_route=%2Fwp%2Fv2%2Fusers&who=authors&context=edit&_locale=user 403 (Forbidden)
{
  "code": "rest_forbidden_context",
  "message": "Sorry, you are not allowed to list users.",
  "data": {
    "status": 403
  }
}
```

**To reproduce**
1. Visit a post as a user in e.g. an editor or author role.
3. Check the console for the error.

**Comment by ellatrix** [comment]
This actually happens when you load any post.

**Comment by youknowriad** [comment]
@ellatrix This is being worked on here #26554

**Comment by ellatrix** [comment]
Ah, thanks! I'll close this one since there's another issue for it.
