### ISSUE TITLE
Button: Add in ability open link in new window

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#2674]
So now as we got the ability to set the link to open in new window for text links, how about adding same option for Button block as well.

**Comment by karmatosed** [comment]
I think that would be a good idea +1

**Comment by munirkamal** [comment]
@karmatosed 

Cool, just like to add further it should be consistent throughout all blocks where link icon appears like image Block also has the link icon. Shouldn't that also allow to set the link to open in new window?

**Comment by danielbachhuber** [comment]
Closing in favor of #4597
