### ISSUE TITLE
Add a support file to repository to help new contributors

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26758]
**Is your feature request related to a problem? Please describe.**

In looking through GitHub's docs, I found this option: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-support-resources-to-your-project

Essentially, you can add a support file to help people get familiar with the repository when new. This seems like a high impact, low effort way to perhaps help with engagement and help guide people towards our best practices. 

**Describe the solution you'd like**

I'd love to see a support file created that includes links to these two references:

https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md
https://github.com/WordPress/gutenberg/blob/master/CODE_OF_CONDUCT.md

fyi to @mkaz  :) I'll try to get to this in the future but wanted to open the issue for now.

**Comment by skorasaurus** [comment]
done in https://github.com/WordPress/gutenberg/pull/27524 :)
