### ISSUE TITLE
Site Editor: Nav Sidebar Toggle Button Disappears in Smaller Viewports

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#26754]
**Describe the bug**
More context [here](https://github.com/WordPress/gutenberg/pull/26021#pullrequestreview-524001455)

At smaller viewport widths, we can open the Navigation sidebar by clicking on the name of the current template then clicking on "Browse templates". This opens the sidebar but there is no way to close it.

**To reproduce**
1. Enable the site editor locally
2. Navigate to the site editor
3. Shrink the viewport <782px
4. Click on the document title
5. Click on "browse all templates"

**Expected behavior**
If we want to include the nav sidebar for smaller viewports, then we should render the hide nav sidebar button. Otherwise, we could remove the "browse all templates" button from the document title dropdown at smaller viewports.

**Screenshots**
<img width="540" alt="Screen Shot 2020-11-05 at 3 03 35 PM" src="https://user-images.githubusercontent.com/5414230/98306349-7f776600-1f78-11eb-8c63-044eec236a91.png">
<img width="540" alt="Screen Shot 2020-11-05 at 3 05 01 PM" src="https://user-images.githubusercontent.com/5414230/98306352-81412980-1f78-11eb-9ced-ad264832990d.png">

**Comment by mattwiebe** [comment]
Fixed in #27310 but GitHub doesn't like to close multiple issues with one line

Why do you hate efficiency, Github
