### ISSUE TITLE
Add an intro banner message to GitHub repo

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26756]
**Is your feature request related to a problem? Please describe.**

If you check out https://github.com/Homebrew/brew/issues, you'll see this lovely intro message shown:

<img width="1263" alt="Screen Shot 2020-11-05 at 6 01 37 PM" src="https://user-images.githubusercontent.com/26996883/98313399-f587c700-1f90-11eb-98cb-570f4e9b8d56.png">

I tried to dig [through GitHub docs](https://docs.github.com/en) but couldn't figure out what exactly powers this. 

**Describe the solution you'd like**

I'd love to see a similar simple statement to greet people upon viewing the issues tab in this repo. cc @mkaz  for thoughts!

**Comment by stokesman** [comment]
I think this repo already has one. I see a similar one on the issues page of any repo which I haven't contributed to. Variations of it are probably shown based on if the repo has a root CONTRIBUTING file and if it has any issues labeled "Good First Issue". I notice the link for "we've collected some good first issues for you" is one that can be applied to any repo. Here it is for this one: https://github.com/WordPress/gutenberg/contribute

**Comment by annezazu** [comment]
Hey @stokesman! Thanks for following up. Ah ha! I honestly hadn't seen that link before. I'd honestly love to clean that up too as it would be great to help direct people a bit more than the two line intro allows and to be a bit more encouraging. 

When I head to https://github.com/WordPress/gutenberg/issues in a private window, this is what I see:

<img width="1429" alt="Screen Shot 2020-11-16 at 10 40 33 AM" src="https://user-images.githubusercontent.com/26996883/99288005-3b962380-27f8-11eb-90b0-8c9dbd0941ee.png">

What do you see? I'd love for there to be something similar to what I linked above with homebrew.

**Comment by stokesman** [comment]
> What do you see? I'd love for there to be something similar to what I linked above with homebrew.

I see the same in a private window. Though if you check homebrew (or any repo) in a private window and it'll be the same. Github apparently only shows that banner to signed-in visitors (and only signed-in visitors without some form of contribution history for the repo). So if you know of anyone with an account that fits that criteria you can ask them what they see (or make an extra account just to test).

**Comment by annezazu** [comment]
How strange. I just had a teammate test this who hasn't contributed to this repo and they sent me this screenshot: https://d.pr/i/kuhjNJ It mimics what I'm seeing too! For now, I'll keep this open and either way will see if we can get it added or, if already added, updated :)

**Comment by stokesman** [comment]
To test, I opened a new account, and here's what I see:
![image](https://user-images.githubusercontent.com/9000376/99431093-0d2f4b80-28bf-11eb-9f7e-9db609dae81a.png)

🤔  Is your teammate a member of the WordPress organization? That could be another factor in the display of the banner. Otherwise, I'm not sure if by "hasn't contributed" you mean commits, but where I've mentioned contribution I was meaning in a broader sense including opening issues or perhaps even just commenting on issues.

It would be great if GitHub had documentation on this but I'd not been able to find it.

**Comment by annezazu** [comment]
Ha! This is absolutely bizarre. My teammate hasn't opened any issues, commented on any, or done any commits. Agreed on the documentation front. I haven't found anything either but might try reaching out to them. Based on the screenshot you shared, seems this is just simply an automatically generated message that I doubt can be edited. I'll close this out for now. Appreciate you being with me on this journey ;)
