### ISSUE TITLE
Issue with save_post action with gutenberg editor

### ISSUE THREAD

**Issue by axelseaa** [WordPress/gutenberg#26760]
I have a save_post hook setup that calls `wp_schedule_single_event`.  Using the classic editor, this works fine - and the event is successfully saved in the cron array.

However, using the exact same process using the gutenberg block editor, the event never actually gets stored into the cron array.

I've been trying to seek out additional information and have been doing debugging but so far I've just ended up at dead ends.  I apologize if this is not the correct place to ask, but I'm hoping someone may have some additional thoughts for me!

Thank you in advance.

**Comment by fklein-lu** [comment]
Could you please post the most important parts of the code that you are using?

**Comment by adamwoodnz** [comment]
Closing following triage policy
