### ISSUE TITLE
Block editor completely gone for second of two super user

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#26775]
## Describe the bug

Two super users in a blog network. 15 sites. When second user logs-in block editor is gone. I can see Gutenberg > Demo menu item, I can open "Welcome to Gutenberg Editor" demo page, but this page (as well as all other pages and posts in all 15 sites in entire blog network) is rendered using regular code editor. For first user everything works as expected.

## To reproduce
This is how I am reproducing this issue in my blog network. At this moment I don't know, if this is some kind of weird general bug or "is it only me".
1. Have at least two Super User-class users in any kind of Wordpress blog network.
2. Install Gutenberg plugin separately. Version 9.3.0 or older.
3. Login with first super user and navigate to any page where Gutenberg editor should appear (i.e. try to edit any page or post within any site in your network or i.e. click on click Gutenberg -> Demo in site's sidebar).
4. Observe that everything works as expected.
5. Log-off and log-in again using second super user's credentials.
6. Click on Gutenberg -> Demo in any site's sidebar.
7. Observe that page loads with Gutenberg editor completely disabled / not existing.

## Expected behavior
Block editor / Gutenberg should work normally and as expected for each and every user in given blog network.

## More details
Before filing a bug report in here, I tried to seek help in [Wordpress site at Stack Exchange](https://wordpress.stackexchange.com/questions/377729/block-editor-completely-gone-for-second-of-two-super-user) and in [Gutenberg plugin's support forum at Wordpress.com](https://wordpress.org/support/topic/gutenberg-completely-gone-for-second-user/). The below is pretty much copy-paste of both of these URLs.

### Overview

I have a blog network with 15 sites. I am using Gutenberg editor for editing my posts on every of these sites. I have Gutenberg plugin installed separately. Auto-updates enabled. Now version 9.3.0.

I also have two users in my blog network and they are both Super Users:

[![enter image description here][1]][1]

But the second one is actually inactive, used once per year or less. I post most of my posts via first user.

Gutenberg is installed, network activated and available on each site without any problems:

[![enter image description here][2]][2]

### Problem

When I login as first user (admin, the one that I use the most) then everything is OK:

[![enter image description here][3]][3]

When I login with second user, on each and every site Gutenberg is simply… gone:

[![enter image description here][4]][4]

### Details

As you can see in linked images, when I am logged-in as second user, I can still see that plugin is enabled and available, I can still see “Gutenberg” option in my side bar, I can still even click Gutenberg -> Demo, but when I click it… there’s no Guteberg at all. The same for all posts and pages and for each and every site.

Tested on PC, under newest version of Chrome and Edge under Windows 10 and on mobile phone under newest version of Chrome available for Android 8.0 Oreo. Tested on each and every of 15 pages that are part of my blog network. Everywhere exactly the same effects. All is working fine and dandy for the first user + Gutenberg is completely gone for the second user.

For a short period of time I have enabled SCRIPT_DEBUG mode as instructed [here](https://wordpress.org/support/article/debugging-in-wordpress/#SCRIPT_DEBUG) and [here](https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/), but DevTools console under Microsoft Edge showed nothing alerting:

* A suggestion to download the React DevTools for a better development experience
* An intervention that images are loaded lazily and replaced with placeholders and load events are deferred
* An error that WebSocket connection to ‘wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data’ failed due to 403 response
* A DOM warning that 2 elements are found with non-unique id #_wpnonce
* And a Mixed Content warning that page at ‘/wp-admin/post-new.php?gutenberg-demo’ was loaded over HTTPS, but requested an insecure favicon so this request has been blocked, as the content must be served over HTTPS

So… nothing unusual, if I am not mistaken.

### Conclusion

This is as weird as it can be and I am completely lost on where to even start looking for any source of this issue or any solution or workaround for it. Please, help, if you can.

  [1]: https://i.stack.imgur.com/v4C2T.png
  [2]: https://i.stack.imgur.com/a9FCc.png
  [3]: https://i.stack.imgur.com/fz4Uo.jpg
  [4]: https://i.stack.imgur.com/LZGzh.png

## Editor version

- WordPress version: **5.5.3**
- Does the website has Gutenberg plugin installed: **yes**
- If the Gutenberg plugin is installed, which version is it? **9.3.0 by Gutenberg Team | Auto-updates enabled**

## Desktop

 - OS: **Windows 10**
 - Browser: **Chrome** + **Edge**
 - Version: **86.0.4240.183** (64-bit) + **86.0.622.63** (64-bit)

## Smartphone

 - Device: **Motorola Moto Z2 Play**
 - OS: **Android 8.0.0 Oreo**
 - Browser **Chrome**
 - Version: **86.0.4240.185**

**Comment by talldan** [comment]
@trejder Do you have this setting enabled for the second user in the user profile:
<img width="586" alt="Screenshot 2020-11-09 at 3 19 21 pm" src="https://user-images.githubusercontent.com/677833/98511019-13aa3b80-229f-11eb-96fa-6c9a72cb33fe.png">

**Comment by trejder** [comment]
@talldan OMfG! :| Thank you...

The user in question was created 2012, so eight years ago and so was its options set. And that is the only explanation (I hope so) that may explain my ignorance. Sorry for bothering you and thanks for help in solving my issue. Closing.
