### ISSUE TITLE
Gallery: 'X' button overlap with top bar

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#2677]
Delete 'x' button is overlapping with the top bar, I suppose z-index needs to be adjusted. 
![abdc0900-ebf2-4025-bb43-a3343a37bbd4](https://user-images.githubusercontent.com/5817882/30075966-e3fe91f2-9290-11e7-8bba-d425b6b2b7bf.jpg)

**Comment by karmatosed** [comment]
I can also replicate in Chrome. Thanks for reporting!

**Comment by munirkamal** [comment]
@karmatosed 

Yeah sorry, i missed to mention the browser, I test it earlier on chrome. Btw I just tested it on Safari and Firefox on Mac and got the same issue.
