### ISSUE TITLE
Block search doesn't load all search results

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#26787]
I discovered this in Firefox and if you have a long list of search results it cuts off at a certain point.

![2020-11-06 20 08 20](https://user-images.githubusercontent.com/253067/98410120-f9d4e280-206b-11eb-961c-80fb8971a5ad.gif)

My recommendation would be to either have a loading limit and say "load more" or continue the scrolling - preference being to continue, but I suspect there might be a load weight there. If continuous loading can't happen, this is a very simple mock-up, but it prevents the issue of a half-loading image:

![image](https://user-images.githubusercontent.com/253067/98410436-95665300-206c-11eb-83b8-853461e61ae4.png)

A nice addition to this might be to say load more and show the number to load, but that goes beyond solving the bug here.

## Next steps
As this is a bug, I will put on feedback labels as ideas around this would be great along with input. However, I do think it's something to move to a solution on even if it's just a text link. For now, it does appear broken to those experiencing this.

Looping in @tellthemachines incase this could slip into the release, but I also don't expect everything to so very fine if it does not.

**Comment by StevenDufresne** [comment]
Hi @karmatosed!
Can I get some more information? (Operating System, Browser Version, Gutenberg Version) 
I'm having a hard time reproducing this issue. 

Here is what I tried: 
- Turned off "Quote" in the block manager
  - I wasn't able to search for 'block' in the directory because the quote block was being returned.
- Search for "block"
- Scrolled to the bottom expecting to see the overlap.

**I wasn't able to reproduce using:**

**OS**: Windows 8 or Windows 10
Firefox: 81

**OS**: MacOs Catalina (10.15.6)
**Firefox**: 81.0.2

**Gutenberg**: master@707540c6cf44679c865a5188ec57b00eda0c2a75;

**Comment by karmatosed** [comment]
@StevenDufresne well that's unexpected. I also don't see this today! Here is what I see now:

![image](https://user-images.githubusercontent.com/253067/98535499-1fd1d100-227e-11eb-8909-6cec32964d75.png)

As you can see in my gif above it certainly was an issue Friday, so let's celebrate that's fixed and close this up. Apologies for flagigng something apparently was fixed, but it was previously broken.

I do think there's an iteration here for infinite scroll but this is no longer considered by me a bug to fix for this release, thanks.

**Comment by StevenDufresne** [comment]
👍 

Additionally, that tooltip probably shouldn't be displayed when there are block directory results unless the tip applies to the block directory results ("Did you know you can search based on block slugs?"). Otherwise, it's pretty unexpected.

**Comment by karmatosed** [comment]
@StevenDufresne that makes a lot of sense to conditionally load tooltips, would you like me to make an issue for that or have you?

**Comment by StevenDufresne** [comment]
@karmatosed I have not. Feel free to add it!

**Comment by karmatosed** [comment]
This looks resolved on latest version.
