### ISSUE TITLE
Social Links Block needs different icons

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#26780]
**Describe the bug**

Social Links as the term and functionality is used, provides links to social profiles of the user. 

In other apps the same icon is actually used for sharing a post/image/podcast/ to the social networks. 
![Screen Shot 2020-11-06 at 9 07 38 AM](https://user-images.githubusercontent.com/39980/98387569-902ee700-201f-11eb-9a6a-21f089795cdd.png)

As these are two different concepts, it would help if there would be a different icon used for the Social Links Block. . 

As soon as the user download a Social Sharing block, the icons will get mixed up. 

Here are some example screenshots of various apps on my phone and on computer of the usage of the same icon. 
Sharing a podcast episode: 
![Screen Shot 2020-11-06 at 10 48 14 AM](https://user-images.githubusercontent.com/39980/98386398-206c2c80-201e-11eb-87c8-68a13eb8c6cb.png)

Sharing an image 
![Screen Shot 2020-11-06 at 10 48 33 AM](https://user-images.githubusercontent.com/39980/98386400-2104c300-201e-11eb-9f93-4570a96387dc.png)

Sharing a screenshot
![Screen Shot 2020-11-06 at 10 48 44 AM](https://user-images.githubusercontent.com/39980/98386402-2104c300-201e-11eb-8bb9-46d1988ee9d1.png)

Sharing a post from a feed reader
![Screen Shot 2020-11-06 at 10 48 59 AM](https://user-images.githubusercontent.com/39980/98386407-2104c300-201e-11eb-8751-c2a6309956b1.png)

Sharing an image in Google Photps. 
![Screen Shot 2020-11-06 at 10 39 02 AM](https://user-images.githubusercontent.com/39980/98386601-645f3180-201e-11eb-8fca-2638dd142308.png)

**What are good icons to convey links to the profiles pages?**
I took a trip around the net and found these... 
![Screen Shot 2020-11-06 at 10 57 41 AM](https://user-images.githubusercontent.com/39980/98387300-3af2d580-201f-11eb-8ff8-454e2f245699.png)
![Screen Shot 2020-11-06 at 10 57 50 AM](https://user-images.githubusercontent.com/39980/98387301-3b8b6c00-201f-11eb-91bb-4af9cfbfddea.png)
![Screen Shot 2020-11-06 at 10 58 12 AM](https://user-images.githubusercontent.com/39980/98387302-3b8b6c00-201f-11eb-9b86-5be484829472.png)
![Screen Shot 2020-11-06 at 10 59 13 AM](https://user-images.githubusercontent.com/39980/98387303-3b8b6c00-201f-11eb-8eeb-b7e60d739cd7.png)
![Screen Shot 2020-11-06 at 10 59 21 AM](https://user-images.githubusercontent.com/39980/98387306-3b8b6c00-201f-11eb-9f40-6873a8434772.png)

Also: 
Both the parent block as well as the child block are using the same icon which by itself is also confusing. 
![Screen Shot 2020-11-06 at 9 07 38 AM](https://user-images.githubusercontent.com/39980/98383350-5f987e80-201a-11eb-8765-7aef978d4151.png)

**To reproduce**
1. Edit post
2. Add Social Links Block
3. Add a WordPress link
4. Navigate to parent block

**Expected behavior**
A clear distinction between social media profile links and sharing links block, as well as between parent block and child block.

**Comment by mapk** [comment]
I really think this is a good point you raise, @bph! 👍 

That icon we use is more of a "sharing" icon than a "find me here" icon. It's worth exploring some new icons for this block.

**Comment by mapk** [comment]
Thinking about how this icon should reflect other places that you inhabit, I created a Globe icon and also pulled out the G2 "people" icon for review too.

![social](https://user-images.githubusercontent.com/617986/98583193-d468f400-2278-11eb-807e-72bc317178ea.png)

**Comment by mapk** [comment]
Here's a few more iterations.

![Screen Shot 2020-11-09 at 3 32 39 PM](https://user-images.githubusercontent.com/617986/98608801-d6df4400-22a0-11eb-989d-c4e2a0527e3d.png)

**Comment by jasmussen** [comment]
I tried my hand with https://github.com/WordPress/gutenberg/pull/28588. I like that it remains a share icon, which is what you'd look for in the inserter, but it's an actual "box" suggesting it could also be a container of icons. What do you think?

Alternatively, we could use a different "arrow out of box" icon, without the box:

<img width="82" alt="Screenshot 2021-02-08 at 13 07 31" src="https://user-images.githubusercontent.com/1204802/107217651-c01acb80-6a0e-11eb-95be-8b9d039aca41.png">

Ultimately I don't think we can get this perfect. The icon you look for in the inserter is one thing, the icon when it's inserted and has other share icons, is another. I think it will be hard for us to find a good "Share" metaphor that accurately describes the block, without having at least a little overlap with the icons already in wide usage.

**Comment by bph** [comment]
On FSE Testing Call 2: [Comment by  by Courtney Engle Robertson](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1369)
"I learned how to use the social icons area and fill the links in. I didn’t realize they were not sharing buttons, but follow buttons. I needed to configure the links as well as adding the various platforms." 

People really have trouble working with it, as the icon would make it a sharing block instead of a social profile block. Hence, the problem to understand the need to add blocks for each network. Social Sharing links wouldn't need that.

**Comment by bph** [comment]
On FSE Testing Call 2: [Comment by Andy Sitt: ](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1365)"It wasn’t obvious to me that the Social Icons block then needed to have individual social media blocks added. I couldn’t figure out why they weren’t showing up and looked in the settings and in my user profile to figure out where to add my social media links. I saw social icons in the footer and then clicked on the blocks and saw that the individual icon blocks needed to be added."

**Comment by ravishanker** [comment]
Is there a decision to definitely change the current icon to another one?  If so, which one and where is the icon asset?

**Comment by richtabor** [comment]
Wanted to follow up here. We have individual social link icons for each child block now — which does make it much clearer when editing. Does the current state of the social blocks resolve this issue @bph? 

<img width="334" alt="CleanShot 2023-02-27 at 09 27 55" src="https://user-images.githubusercontent.com/1813435/221590198-55c276ca-e35f-468f-bd9a-c46e3d78e708.png">

**Comment by bph** [comment]
Thanks for at least asking and not close the issue outright, @richtabor - And thank you, @annziel to tackle this as your first contribution. I am sorry your PR didn't move forward. 

In above image of the block, it still uses the wrong icon in the parent block. That icon has been adopted by any other app on the Internet to indicate "sharing" rather than profile links. I gave ample examples. Is has been brought up by community leaders in the FSE outreach program, see above.  

As sharing links on the social web, is a learned method to bring in traffic from all over the web, back to one's website, this icon promises what the block can't keep. If you want to close this issue, is fine with me, but this could be such an easy win. 

>I think it will be hard for us to find a good "Share" metaphor that accurately describes the block, 

Apparently, I wasn't able to make myself clear enough to @jasmussen that in fact, the issue is not looking for a 'better' sharing metaphor but for a profile metaphor as **the block doesn't deliver** sharing on Twitter or on Facebook functionality, but only **provides links to the profiles** at social networks. 

WordPress doesn't have a sharing block. To understand the difference, you could use the [Social Sharing block plugin ](https://wordpress.org/plugins/social-sharing-block/)by @ndiego

**Comment by richtabor** [comment]
I'm not sure I draw such a difference between social iconography for _links to profiles_ v. social _sharing_; the icon is representative of the term `social`. 

I wouldn't want to change it to something less "social", pulling away from the necessary context the generic social iconography provides. And the smaller social icons previously suggested are rather tiny.

**Comment by bph** [comment]
As it hasn't been fixed for 2 1/2 years, closed.
