### ISSUE TITLE
Duplicating a separator block places the block on top of the first in the editor.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#26808]
**Describe the bug**
When duplicating a separator block, the second block looks like it is in the same position as the first.
If the inserter below the block is then used to add a second separator block, that block is also placed in the same position.

On the front, the block is presented correctly.

This is easiest illustrated with the gif below.

**To reproduce**
1. In the post editor, add a separator block.
2. In the block toolbar, click on More Options and select duplicate (or use the shortcut)
3. See that the new copy is not placed below the first block, but that the line becomes thicker.

Repeating step 2 and duplicating the block more than once, eventually makes it difficult 
to select the block/ the block toolbar.

**Expected behavior**
The block should be placed below the previous block.

**Screenshots**
![separator](https://user-images.githubusercontent.com/7422055/98468261-05deb280-21da-11eb-90c0-4e7de4465a34.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta3-49486
- Tested with and without Gutenberg 9.3.0.
-Tested with multiple themes including Twenty Twenty and Twenty Twenty-One.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 86.0.4240.183

**Comment by tellthemachines** [comment]
Adding it to the 5.6 board as this is a regression from 5.5. Should be easy to fix by editing or removing [this line](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/separator/editor.scss#L6) that no longer applies correctly since block wrappers were removed in the editor.
