### ISSUE TITLE
Gutenberg .min.js and Git

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/gutenberg#26819]
Is there a guide somewhere on how to handle the .min.js process of gutenberg blocks in a multi-dev environment?

The situation:
Dev A and Dev B both modify a gutenberg block in a plugin they develop.
They work on separate branches.

Since the gutenberg .min.js is created by each dev separately, this means that after merging the branches of both devs, the gutenberg .min.js only includes the changes of the branch that was merged later (& all features/functions/changes from the branch that was merged earlier are removed).

Atm this means that all branches have to be rebased before merging, then manually set up npm things again to create new gutenberg .min.js and then merge immediately.
While this is possible, it's a real PITA when working in a bigger team (5+ devs, or god forbid even more) as one has to rebase all the time and also pull requests need to be merged almost immediately to avoid having to rebase again.

Would love to hear some suggestion on how to easily handle this

**Comment by talldan** [comment]
@kkmuffme Any build files are ignored by git in this project so are not committed to the repo:
https://github.com/WordPress/gutenberg/blob/cdd9b9efd41e5acc534a60cc79877c96afb32b10/.gitignore#L2-L5

And that's generally the practice in most projects from my experience.

**Comment by kkmuffme** [comment]
Thanks, but I think I didn't properly phrase my question.

I have a WP plugin with a plugin-sidebar block, located in assets/js/gutenberg/plugin-sidebar.js (unbuilt), respectively assets/js/gutenberg/plugin-sidebar.min.js (built version)

Now 2 developers in 2 separate branches modify something in plugin-sidebar.js and build it.
Since conflicts in .min.js files cannot be resolved, after merging we end up with the .min.js of who/whichever branch is merged AFTER. The only way to circumvent this, is to rebase and then build again and then merge.

Is this the only way or am I missing something?

**Comment by aristath** [comment]
You could add the `.min.js` files in your `.gitignore`. This way they will be omitted from commits and devs can just run `npm run build` or whatever other processes you have to generate these files. Other than that there is no easy solution for minified files as far as I know.

**Comment by talldan** [comment]
Yep, not committing build files is common practice for this reason (and that the build can end up outdated if someone forgets to commit it.)

I'll close the issue as the question has been answered.
