### ISSUE TITLE
Gutenberg editor not showing content while Classical Editor does

### ISSUE THREAD

**Issue by karunshakya** [WordPress/gutenberg#26843]
When using the Gutenberg editor, I am unable to see the content apart from the title. I have the option to add in a new block, however, the existing content of the page is not there. When I activate the classical editor, I can see the content in the TinyMCE editor. When I roll back to Gutenberg, it's gone again.

See image here for the Gutenberg http://prntscr.com/vggtmv
See image here for the Classic Editor http://prntscr.com/vggu7f

**Comment by mapk** [comment]
I just tested this using WP 5.5.3 and the latest Gutenberg plugin, 9.3. It appears to work fine for me. 

![Screen Shot 2020-11-10 at 9 44 24 AM](https://user-images.githubusercontent.com/617986/98711107-6e907100-2339-11eb-9c14-ccea865b00de.png)

@karunshakya which WP version are you using? Do you have the Gutenberg plugin installed at all?

**Comment by karunshakya** [comment]
Hi @mapk 
Thanks for this.

We are currently on WP 5.4.2 and Gutenberg 7.9.0.
We do have an addon for Gutenberg as well. 

I think I'll try to update WP and the plugins and see if it resolves the issue for us.

Thanks again :)

**Comment by talldan** [comment]
@karunshakya Which theme are you using?

**Comment by karunshakya** [comment]
@talldan It's a custom theme based on underscores.
