### ISSUE TITLE
RichText Component - Disable 'Users' Autocompleter?

### ISSUE THREAD

**Issue by mduschak** [WordPress/gutenberg#26870]
Question:
Is it possible to disable the 'users' autocompleter for the RichText component?

What I have found:
There is an '[autocompleters](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/rich-text/README.md#autocompleters-arraycompleter)' property for the RichText component.

Documentation states the following for the property:
'A list of autocompleters to use instead of the default.'

I have tried two things: 
1. Make an empty array for autocompleters
2. Make a new autocompleter to force overriding of the defaults to use my new autocompleter instead.

Results:

1. Making an empty array for autocompleters has no effect - the 'users' autocompleter' is still active in the RichText component.
2. When I create my own autocompleter for use instead of the default, instead of replacing the default and using my new autocompleter, what I see happening is that my new autocompleter is instead added as an additional autocompleter. So I end up with both 'users' and my new autocompleter available in the RichText component.

**Comment by talldan** [comment]
@mduschak It looks like RichText uses the Autocomplete component, which uses the `editor.Autocomplete.completers` filter.

Within Gutenberg that filter is used to add the user autocompleter:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/hooks/default-autocompleters.js#L18

So you should be able to use the filter to replace it.

**Comment by mduschak** [comment]
@talldan exactly what I needed.

Thank you!
