### ISSUE TITLE
Pullquote: when we select the solid color style then the " (Quote) gets overlap with placeholder

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#26885]
Describe the bug
in Pullquote when we select the solid color style then the " (Quote) get overlap with placeholder, so because of that we are not able to view the first character of the text of Pullquote.

To reproduce
Steps to reproduce the behaviour:

Go to 'Editor'
1. Add new page
2. Click on 'add block'
3. Select the block 'Pullquote'
4. Select the Style 'Solid color'
5. View the placeholder 
6. See error

Expected behaviour
when we select the solid colour style the we have to view the full placeholder and text of Pullquote.

Screenshots
https://prnt.sc/tvn4la
https://prnt.sc/tvn53e

Video
for more detail please view the attached video
https://www.loom.com/share/051a4b5a408049979bc99274924a5fba

Editor version:
WordPress version: 5.6-beta3-49560

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by talldan** [comment]
Thanks for reporting. I couldn't reproduce this issue. When I tested I don't see a quote at all, so it could be a theme issue:
<img width="853" alt="Screenshot 2020-11-12 at 11 04 24 am" src="https://user-images.githubusercontent.com/677833/98890429-e942c300-24d6-11eb-96a2-b276ffbc66b4.png">

Were you testing with Twenty Twenty One?

**Comment by kmadhak** [comment]
Thank you for your quick response, Yes this issue is generating with the theme **Twenty Twenty One**

**Comment by kmadhak** [comment]
Thank for 

> Thanks for reporting. I couldn't reproduce this issue. When I tested I don't see a quote at all, so it could be a theme issue:
> <img alt="Screenshot 2020-11-12 at 11 04 24 am" width="853" src="https://user-images.githubusercontent.com/677833/98890429-e942c300-24d6-11eb-96a2-b276ffbc66b4.png">
> 
> Were you testing with Twenty Twenty One?

**Comment by talldan** [comment]
@kmadhak As I can't reproduce this with other themes, I've created an issue for you on the Twenty Twenty-One repo - https://github.com/WordPress/twentytwentyone/issues/835
