### ISSUE TITLE
Quote: When we add a Quote Block in the page then it is always left align instead of centre align

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#26887]
Describe the bug
When we add a Quote Block in the page then it is always left align instead of centre align as compare to other blocks in twenty twenty theme 

To reproduce
Steps to reproduce the behaviour:

1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Quote'
5. See error

Expected behaviour
when we select the Quote block then its position should be centre as per other blocks.

Screenshots
https://prnt.sc/vhbrtn

Video
for more detail please view the attached video
https://www.loom.com/share/8de56a5924ed48a7a681f19d859bd23f

Editor version:
WordPress version: 5.6-beta3-49560

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by talldan** [comment]
Thanks for reporting @kmadhak. This was fixed by https://github.com/WordPress/gutenberg/pull/26680, which will be in WordPress 5.6 beta 4.
