### ISSUE TITLE
Limit text characters 

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2689]
Would like to ask for this function.

I remembered you plan to replace native widgets with Gutenberg blocks, so function like this would be very handy. And for excerpts blocks too.

Additionaly it would reduce themes usage of excerpt code hacks to achieve uniform design & layout.
No problem with it by itself, but they tend allways to "forget" to make (custom) excerpt function hookable and filterable.

**Comment by karmatosed** [comment]
I'm not sure this shouldn't stay down to the theme, over the editor. I feel this is stepping into plugin territory also. I wouldn't think it would be a bad little addon plugin.

**Comment by StaggerLeee** [comment]
I am afraid you moved it from "plugin territory" to the core. By insisting to replace all widgets with editor blocks.

**Comment by aaronjorbin** [comment]
At a minimum, this should be a documented example of how to extend `<editable>` for this.

Two use cases that I can think of off the top of my head:

1) A "Tweetstorm" block that is filled with repeatable `<editbale>` components that together appear on the site as a paragraph, but each component is tweeted out separately
2) Pull quotes that are limited in size to better work with the site aesthetic.

**Comment by StaggerLeee** [comment]
- Widgets. Given to clients/owners and limited how much text they can put inside and ruin layout.
- Almost all Archive templates not listed in one row, Post listed in columns. There is no point in huge empty space, no matter if columns are equal. When characters limit kicks in, user see / knows directly how to reduce text.

**Comment by karmatosed** [comment]
Let's go with adding a documentation label and getting this in docs over in the code.

**Comment by karmatosed** [comment]
As the project moves towards a full vision, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
