### ISSUE TITLE
Inserter: Expand view to view patterns in a larger overlay.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#26905]
This issue came about as I read: https://wptavern.com/wordpress-com-drops-over-100-block-patterns-carving-a-path-the-design-community-should-follow 

Viewing a lot of patterns in the small inserter panel does not work to well. It gets tiring needing to scroll one pattern at a time. Having a larger view will help the user to compare multiple patterns at once.

Here is an example from WordPress.com. (The following is a mix of Norwegian and English language.)
We see the Inserter panel.
A user needs to scroll to see one pattern at a time.

![Screen Shot 2020-11-11 at 21 10 00](https://user-images.githubusercontent.com/5323259/98859336-4fd9c980-2462-11eb-88b3-d2c56938c1cf.png)

--

![Inserter-panel-scrolling-patterns](https://user-images.githubusercontent.com/5323259/98859644-c70f5d80-2462-11eb-9c38-b15cdc7d448e.gif)

Going from the narrow Inserter panel to a larger overlay will make it possible to see multiple patterns at once.

I added an expand icon the user can click to open an overlay.

![Patterns-overlay-gallery-mode-1](https://user-images.githubusercontent.com/5323259/98859877-1e153280-2463-11eb-8894-a1f51850424a.jpg)

--

![Patterns-overlay-galleri-mode-2](https://user-images.githubusercontent.com/5323259/98859915-2e2d1200-2463-11eb-9c07-70b792841449.jpg)

The result is more space to view patterns.

**Comment by hedgefield** [comment]
Great idea! It makes a lot of sense, also for style variations and such. First thing I would suggest is to add some kind of outline around the pattern preview image - these examples have some wild layouts with intense whitespace, makes it hard to see what belongs where. Putting some kind of outline will make it immediately clear and bring the grid feeling you're going for.

**Comment by paaljoachim** [comment]
Hey Tim! 

Yeah. I see your point. I removed the default outline and instead added it to the hover state.

Here is a Figma prototype:
https://www.figma.com/proto/TuDKX6ckaecNARP2B8NWp4/Expand-to-view-patterns-in-a-larger-overlay-window?node-id=3%3A49&scaling=min-zoom

An animated gif.
![Pattern-expand-to-overlay-screen](https://user-images.githubusercontent.com/5323259/99002124-46249480-253c-11eb-83bd-7524790f3b66.gif)

The prototype I made is one piece of a bigger puzzle.

**Next Steps on the Inserter**
https://github.com/WordPress/gutenberg/issues/21080
Which we also need to take into account.

As well as these issues that have the Inserter label.
https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Inserter

**Comment by skorasaurus** [comment]
+1 with this; we're starting to run into this (users having to scroll down) as well even with just a handful of block patterns.

**Comment by paaljoachim** [comment]
Adding in Justin's article from WPTavern: https://wptavern.com/proposal-to-create-an-expanded-view-or-overlay-for-the-block-patterns-inserter

**Comment by ntsekouras** [comment]
I'm closing this as the first iteration has landed here: https://github.com/WordPress/gutenberg/pull/35773
