### ISSUE TITLE
What is the purpose of adding the data-type and data-id attributes to internal links?

### ISSUE THREAD

**Issue by wpjames** [WordPress/gutenberg#26911]
When creating an internal link to another post on my site, Gutenberg is adding the data-type and data-id attributes to the `<a>` tag, as shown in the example below.

`<a href="URL" data-type="post" data-id="xxx">Text</a>`

Links created with the classic editor do not have these attributes. Certain plugins that hook into the link module (Rankmath, Editorskit, etc) are removing these attributes as well.

Why does Gutenberg add these? What will happen when some of the internal links on a site are missing these (created in classic editor or created while one of those plugins was activated)?

If these attributes are useful then shouldn't all of the links have them? If they are not useful, then why add them in the first place?

**Comment by talldan** [comment]
> Why does Gutenberg add these?

Looks like this was added in this change - https://github.com/WordPress/gutenberg/pull/22543 - to support navigating between pages in the full site editor.

**Comment by wpjames** [comment]
> Looks like this was added in this change - #22543 - to support navigating between pages in the full site editor.

Thanks, I was going crazy trying to find an answer to this question!

As I understand it, there should be an option in the new full site editor to directly open a linked post to edit that post instead of the current one? I can't seem to be able to get this option to work.

I tried installing the latest nightly version of Wordpress and installed the Gutenberg plugin and then tried some of the themes from [here](https://github.com/WordPress/theme-experiments).

The full site editor looks completely different from the video posted in [#22543](https://github.com/WordPress/gutenberg/pull/22543).

There is no "page switcher" on the top. I can select pages using the menu on the left hand side. But when I click on an internal link that has the data-type and and data-id attributes, there is no option to edit that page like shown in the #22543 video.

Here is what it looks like.

![site editor](https://user-images.githubusercontent.com/74336866/99005418-bc94b700-257b-11eb-91e5-9d0cad9a88a7.JPG)

**Comment by hannes-dolde** [comment]
i was relying on this data
but now its gone - i am still selecting posts from a dropdown

seems something changed 

any way to check why/where this happens  - apart from randomly deactivating plugins
or add these parameters to links again

seems to be default behaviour though
dont recall doing any plugin update recently

did not find much
https://wordpress.org/support/topic/strange-behavior-when-creating-links-with-gutenberg-when-rank-math-is-enabled/

ok Yoast does the same
why would you remove those tags .....

thanks
for any hints

**Comment by ElementMedia** [comment]
> 

This is a known issue in Yoast:
https://github.com/Yoast/wordpress-seo/issues/17035

I am also depending on the data type fields and haven't found a workaround yet.

**Comment by t-hamano** [comment]
Hi @wpjames,

> As I understand it, there should be an option in the new full-site editor to directly open a linked post to edit that post instead of the current one? I can't seem to be able to get this option to work.

This page switcher does not seem to be implemented in the current site editor.

> Links created with the classic editor do not have these attributes. Certain plugins that hook into the link module (Rankmath, Editorskit, etc) are removing these attributes as well.

It appears that these plugins do not hook into the core links, but instead implement their own link function.
Therefore, it seems more correct to say that the plugins are not removing those attributes, but rather not implementing them.

- [Rank Math SEO has removed the core/link format and registered its own format type](https://github.com/rankmath/seo-by-rank-math/blob/ca14e5ce7c85b44798936cf808017e02bac551f9/assets/admin/src/gutenberg/formats/index.js#L14)
- [Editorskit has its own link feature](https://github.com/CakeWP/block-options/blob/master/src/extensions/formats/link/index.js)

And I could not identify what these attributes are currently being used for, so we are awaiting advice if anyone has more information.

**Comment by jordesign** [comment]
I'm also not seeing the page navigating/switching functionality as something implemented from WP6.3 onwards - so I'd consider this to be an issue we can close.

**Comment by dossy** [comment]
As someone who landed on this issue because I need to find-and-replace a bunch of links from old URLs to new URLs, and noticing these `data-id` attributes, can someone at least explain what the consequence is of updating the URL without updating the IDs that correspond with the correct ID of the new URLs?

What am I breaking by doing this/by not updating the IDs?
