### ISSUE TITLE
Template navigation: Remove "All" panel

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26925]
The Templates panel in the navigation current includes a superfluous "All" section. Since all templates are listed already (albeit categorised), this section isn't helpful.

**Comment by Copons** [comment]
While the "all" section might not be helpful for the end-user, it's very useful for the development of the Site Editor.

I've got a PR open that improves the actual Templates wp-admin list to display all templates (right now it hides the theme-provided ones).
If/when that PR goes in, we'll have a good enough "source of truth" for templates, and I'd say we could remove the "all" section from the sidebar. 🙂

**Comment by jameskoster** [comment]
Fair enough. Another condition upon which we might remove it is when all the other panels in the navigation have been built.

**Comment by jeyip** [comment]
Adding some visuals for context:

![2020-11-30 14 55 14](https://user-images.githubusercontent.com/5414230/100675748-6619cd80-331c-11eb-99bb-6be5658353bb.gif)

**Comment by Addison-Stavlo** [comment]
Noting this may also require polishing up which templates show up in which sections of that menu.  Currently from creating from the add template ("+") icon in the menu:

* a `Post` template only seems to show up under the "All" menu.
* Only `Page` ends up under the "Pages" menu.  Front Page, Singular, Index do not - although Im not sure which should? 🤔

**Comment by jameskoster** [comment]
> although Im not sure which should? 🤔

I'm thinking the generic Page template should probably be top-level as it is one that folks are likely to interact with more frequently. 

The "Pages" section could contain any page-specific (`page-$id`) templates.

**Comment by Addison-Stavlo** [comment]
> I'm thinking the generic Page template should probably be top-level as it is one that folks are likely to interact with more frequently.

I assume the same should be true about `Post` ?

**Comment by jameskoster** [comment]
I think so, yes. 

At this point it may be worth revisiting https://github.com/WordPress/gutenberg/issues/26264 so that we don't end up clogging the top level too much.
