### ISSUE TITLE
Template navigation: Reverse menu order of drilldowns / links

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26926]
I've received some good feedback around the order of the menu items in the template navigation – it would be good to try flipping the order of the drilldowns / links in the Templates panel.

Current:
<img width="497" alt="Screenshot 2020-11-12 at 12 29 01" src="https://user-images.githubusercontent.com/846565/98940556-0b424280-24e3-11eb-8d58-9fb07482ffe7.png">

Proposed:
<img width="449" alt="Screenshot 2020-11-12 at 12 30 29" src="https://user-images.githubusercontent.com/846565/98940565-1006f680-24e3-11eb-91cf-d14e0fccd7fd.png">

This change should cascade through all panels.

**Comment by ntsekouras** [comment]
Hey @jameskoster!

>This change should cascade through all panels.

What other panels are you referring to? I checked and the `Templates` section was the only one I found with such behavior.
