### ISSUE TITLE
In WordPress Editor the interface-skeleton__footer and inserter__tips gets overlap

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#26929]
Describe the bug
in WordPress Editor due to interface-skeleton__footer the inserter__tips gets overlap at the bottom

Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Move at the bottom in the list of blocks
5. See error

Expected behaviour
the interface-skeleton__footer and the inserter__tips should not get overlap with each other 

Screenshots
https://prnt.sc/vhzx6q

Editor version:
WordPress version: 5.6-beta3-49560

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by kmadhak** [comment]
Hello @talldan talldan,

After the release of WordPress version 5.6, I have checked this issue and still it is not resolved, so please look into it.

Screenshot: https://prnt.sc/w4g5ny

Thank you.

**Comment by talldan** [comment]
Thanks for testing @kmadhak. I've since found out that this was fixed in the Gutenberg plugin, but didn't make it into 5.6. The fix is here:
https://github.com/WordPress/gutenberg/pull/26432

It's currently targeted for WordPress version 5.6.1. I'll close this issue given the fix has been made and there's a trac ticket to ensure this makes it into 5.6.1 (https://core.trac.wordpress.org/ticket/51920)

**Comment by jesus-yael** [comment]
I have this problem right now, any body else? 
WP 5.8
<img width="1680" alt="Captura de Pantalla 2021-08-06 a la(s) 6 58 26 p m" src="https://user-images.githubusercontent.com/47003523/128580976-acb9998d-4fad-4e25-8ca2-9f1dc2dd6d0a.png">

**Comment by koganas** [comment]
> I have this problem right now, any body else?
> WP 5.8
> <img alt="Captura de Pantalla 2021-08-06 a la(s) 6 58 26 p m" width="1680" src="https://user-images.githubusercontent.com/47003523/128580976-acb9998d-4fad-4e25-8ca2-9f1dc2dd6d0a.png">

I am having the same issue from @jesus-yael. It seems related to Gutenberg (Visual Editor) when using plugins that add metaboxes. Some plugins that I use and could check the conflict:
- Advanced Custom Fields
- Accelerated Mobile Pages

For now, I could get 2 workarounds:
- Disable the visual editor in the user options, but only the code will be editable in the screen.
- Downgrading the wordpress core to **5.5.5**.

**Possible solution**
It seems that this part of the css should be reviewed to prevent the element with the `.interface-interface-skeleton__footer` class from overlaping all the interface.

![image](https://user-images.githubusercontent.com/24597006/128595724-60e5744b-a913-469f-ba61-cc8dbacb0a94.png)

**Comment by talldan** [comment]
@jesus-yael @koganas I'd recommend making a [new bug report](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.yml&title=%3Ctitle%3E) if the issue has come back. Thanks.
