### ISSUE TITLE
Improve Guidance When Adding Blocks

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#26946]
When adding a block it can be difficult to know _where_ in the document the block will be inserted. As nested blocks become more common this difficulty is compounded, as you have more containers next to other containers its hard to know in _which container_ your adding blocks.

 Here's an example:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/191598/98970912-7dfcef00-24de-11eb-9d17-17545a35bb0e.png">

In the image above I have a Columns block with three Column blocks, each containing a Paragraph block. Below the Columns block is a Cover block which contains a Paragraph block. Thats a lot of blocks, and they're nearly all contained _within another block_.

When I hover my cursor between the Columns block and Cover block a [+] button appears which I can click to show the Quick Library and select a block to add. However, the [+] button is visually confusing; Does this [+] button add a block into the center Column block, between the Columns and Cover blocks, or inside the Cover block?

## Insertion Indicator

There's a few places where the editor shows an indicator to signify _where_ a block is going to be placed within the document. 

1. When dragging a block the drop zone is shown as a blue line letting you know where you're about to drop the block:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/191598/98970431-ef886d80-24dd-11eb-92b9-0c3a99c77fd0.png">

2. When hovering over a block in the Block Library sidebar a (thinner for some reason) blue line lets you know where the new block will be added:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/191598/98980386-8b1fdb00-24ea-11eb-9179-9349c35fb4e0.png">

We should unify these two indicators, and consider adding the indicator to the In-Between add button. Here's how that could look:

![Inbetween Inserter](https://user-images.githubusercontent.com/191598/98981387-dedef400-24eb-11eb-9c5e-401c9b10f6ea.gif)

In the GIF above, I move my pointer between two blocks and after a split second the [+] and blue line appear to let me know _where_ I'm about to add a block. When the new block would be inserter _within a container_ spotlight mode is triggered fading the other blocks to emphasis the container.

The GIF helps tell the story, but you can get a better feel for the interaction in this HTML/JS prototype: https://shaunandrews.github.io/static-prototypes/inbetween-add-button/

**Comment by MichaelArestad** [comment]
I like where this is headed. It feels fairly predictable. I might reduce the delay, but once I was trained to hover on the “in-between” spots, it worked. The temporary “spotlight” animation is also nice.

**Comment by shaunandrews** [comment]
> I might reduce the delay

I spent way too much time on the delay 🙃 Without it, you end up seeing flickers of the [+] and blue line as you move your mouse around. With it, the in-between inserter is very hard to discover.

There's a fine line between annoying and completely hidden.

**Comment by jasmussen** [comment]
Yep, good thought. I think getting the delay right is the only tricky thing. If it shows up too soon, it affects the writing experience. If it takes too long, it's not very discoverable. I trust you to find a good balance here!

**Comment by paaljoachim** [comment]
Thank you for brainstorming this issue Shaun! This is going in a really good direction!
I do believe Mark @mapk  would likely also want to take a look at this issue.

**Comment by mtias** [comment]
I like this step focusing on the insertion indications, if we can improve upon all of them (I'd include some other drag operations, like an image from desktop).

**Comment by mapk** [comment]
>I like this step focusing on the insertion indications, if we can improve upon all of them (I'd include some other drag operations, like an image from desktop).

I was thinking this same thing. Maybe we can pull some learning from the Image drag to implement with an inserter point?

**Comment by youknowriad** [comment]
Haha, just found this issue after opening #27842
