### ISSUE TITLE
Class Name with editor-font-sizes not working

### ISSUE THREAD

**Issue by leadclown** [WordPress/gutenberg#26940]
when i use names like h1 or h2 as slug for add_theme_support(editor-font-sizes) i get the class name has-h-1-font-size in frontend not like expected has-h1-font-size. 

h-1 as slug works fine and i get has-h-1-font-size but its ugly.

so i think the first one is much better for naming but bugged.

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7.
Gutenberg plugin 10.1.1
Twenty Twenty One.

I added into the functions file in the add_theme_support array section:

```
array(
					'name'      => esc_html__( 'H1', 'twentytwentyone' ),
					'shortName' => esc_html_x( 'H1', 'Font size', 		'twentytwentyone' ),
					'size'      => 16,
					'slug'      => 'h1', //slug name
				),
```

Frontend showed:

![Screen Shot 2021-03-18 at 21 02 39](https://user-images.githubusercontent.com/5323259/111690302-4eb01300-882d-11eb-8c28-695b0bbab379.png)

**Comment by gwwar** [comment]
It looks like we also allow upper and lowercase slug values that will collide with one another on the frontend class:

`h1` -> `has-h-1-font-size` , `H1` -> `has-h-1-font-size`

In general it looks like we break on a numerical value:  `foo1bar` -> `has-foo-1-bar`.

If folks do take this one on, let's be careful to not break existing classnames for folks who might be depending on this.

**Comment by oandregal** [comment]
Thanks for the report @leadclown Going to consolidate this into https://github.com/WordPress/gutenberg/issues/32347 as the issue is a bit larger than numbers (also affects camelCased slugs).

**Comment by oandregal** [comment]
There's a fix at https://github.com/WordPress/gutenberg/pull/32352
