### ISSUE TITLE
Block variation transforms with InnerBlocks and custom transforms

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#26962]
The problem that needs solving here is having a way to 'update' a block to another block variation, after its creation. 

The first step was to handle the 'simple' block variations, and by 'simple' I mean the variations that were applying specific attribute values only. In this step the feature was introduced to `Navigation` block. (issue: https://github.com/WordPress/gutenberg/issues/25231, PR: https://github.com/WordPress/gutenberg/pull/26687)

Now we need to implement a way of handling all block variation transforms. This means we have to handle blocks with InnerBlocks as well, like `Query`, `Columns` etc..

Another thing is that there will be a need for extending variations API to support custom transforms. For example changing a `Columns` block of 3 columns to 2 columns. This might be a separate issue and step 3 of this problem though...

Block variations reference: https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#variations-optional

**Comment by mapk** [comment]
Aligning with the Navigation block, I imagine the Query block would look similar to this:

![transform-variations](https://user-images.githubusercontent.com/617986/100005418-c7222e00-2d7d-11eb-9de9-6866239db8d0.png)

There's some oddly repeated description text for each of these options though. It will most likely need a copy review.

**Comment by mapk** [comment]
Here's how this would look without descriptions.

![without-desc](https://user-images.githubusercontent.com/617986/100028400-b4225480-2da3-11eb-8eb9-4fef59748906.png)

**Comment by youknowriad** [comment]
This issue is a bit unclear to me? Is it still relevant?

**Comment by ntsekouras** [comment]
It is relevant, but probably the best solution would be schemas (https://github.com/WordPress/gutenberg/issues/41606).
