### ISSUE TITLE
Edit site: Changes to html files are not reflected in the site editor or front-end. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#26967]
Similar to https://github.com/WordPress/gutenberg/issues/23106, except that only effected block-template-parts. 

Using the latest on `master`, if I edit the HTML `block-template` files of a block-based theme, and then refresh the site editor (or the front end of the site), the new changes do not appear. 

## To reproduce: 

1. Activate a block-based theme.
2. Open the full-site editor.
3. Open the front-end of the site. 
4. Edit one of the theme's `block-template` HTML files. 
5. Refresh the full-site editor, see that the changes are not reflected there. 
6. Refresh the front end of the site, see that the changes are not reflected there either.

**Comment by skorasaurus** [comment]
ref https://github.com/WordPress/gutenberg/issues/22469

**Comment by carlomanf** [comment]
Those other issues are very outdated. This is currently being worked on at #26383.

**Comment by noahtallen** [comment]
@kjellr can you verify that the issue has been fixed now that #26383 has been merged?

**Comment by kjellr** [comment]
Yes, it appears to be working now. Thank you!
