### ISSUE TITLE
Docgen: Some types omitted

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#26971]
Some types may be omitted from docgen output. For example:

```js
/** @type {Record<string,true|undefined>} */
```

https://github.com/WordPress/gutenberg/blob/0545e7d009316338e14e11e53e865723165ce6b8/packages/deprecated/src/index.js#L6-L12

Was rendered as:

```md
_Type_

-   `Record<string,(|undefined)>` 
```

_Originally posted by @sirreal in https://github.com/WordPress/gutenberg/pull/26429#r515412062_

**Comment by saramarcondes** [comment]
@sirreal @gziolo  What do you think about us trying to re-write `docgen` using the TypeScript parser? We'd ditch `babel` and `doctrine` altogether and _just_ use TS to parse the source and the JSDoc comments. It does a really good job on JavaScript files: https://astexplorer.net/#/gist/5931456cb14f4dfbeef6a824c04cacce/2ae696cccaedc016a032ff636f4b2aaf977f2514

It'd be a lot of work (basically a full re-write of the entire `docgen` utility) but it would solve this problem and let us ditch the deprecated `doctrine` library.

If this a desirable path forward for the `docgen` package, I'm super excited to work on this and would be happy to do so.

**Comment by gziolo** [comment]
> Update: Actually it looks like this exact solution was already proposed in #18045. Shall we close this issue and revive the topic over there?

I think that @nosolosw would be the best person to answer your question but I believe that you are correct. #28615 should resolve two issues at once 🎉
