### ISSUE TITLE
How to remove console.log statements from production build?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#26981]
I tried to use `terser-webpack-plugin` but it seems there's an uglifier in place in the default gutenberg webpack config? How can I tap into it to enable the desired behaviour?

**Comment by talldan** [comment]
@navxio Your request is a little bit brief, please could you provide more info on what you're trying to achieve and whether there's any specific tooling you're using (e.g. create-block).

**Comment by navxio** [comment]
@talldan I created a block plugin using @wordpress/create-block. I want to drop all the console.log statements which I use for debugging in the production build. I've been trying to use the webpack-terser-plugin

```
const defaultConfig = require("@wordpress/scripts/config/webpack.config");
const webpack = require("webpack");
const TerserPlugin = require("terser-webpack-plugin");

module.exports = {
  ...defaultConfig,
  module: {
    ...defaultConfig.module,
    rules: [
      ...defaultConfig.module.rules,
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: ["file-loader"],
      },
    ],
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: {
            drop_console: true,
          },
        },
      }),
    ],
  },
};
```
What am I missing?

**Comment by navxio** [comment]
Looks like the new version of @wordpress/scripts ^12.5.0 includes terser-webpack-plugin, so I was able to modify the config to suit my needs.
