### ISSUE TITLE
Can't paste text into editor on IE 11

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#26988]
When editing a post on IE 11, copying text from either the current document or an external source and then attempting to paste it, no text is pasted.

This seems to be a very recent regression, as I can reproduce it with the latest master branch but not with WP 5.5.3 with Gutenberg 9.3 or with WP 5.6 Beta 4 without the plugin.

**To reproduce**
1. Open post editor in IE;
2. Copy some text from somewhere;
3. Try pasting text in editor and verify that nothing happens.

**Comment by carolinan** [comment]
I am able to reproduce this but after testing I am no closer to a solution.

**Comment by steve6375** [comment]
Using Chrome, I can paste in small html doc text but very large pages won't past in - it just returns with a timeout pop-up at  1-2 minute intervals saying it is taking too long - Continue or Cancel.
If I use Elementor Editor, I can paste same large text into the Text Editor panel instantly.

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
