### ISSUE TITLE
Uncaught TypeError: r is not a function

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#26985]
I tried to get help in the WP forums with no success, so I have to resort posting this here in the hopes to find a fix for my problem. I'm running WP 5.5.3 and the latest versions of all the plugins I have installed and I have the `SCRIPT_DEBUG` constant set to true.

I built a plugin that registers a block that prints a simple Mailchimp form. The plugin works with no issues. But, if I activate Jetpack and try to edit any page or post, I get a blank screen and multiple `Uncaught TypeError: r is not a function` console errors such as this one with little variations:

```
editor.js?ver=9.1:6 Uncaught TypeError: r is not a function (https://domain.com/wp-content/plugins/jetpack/_inc/blocks/editor.js?ver=9.1)
    at editor.js?ver=9.1:6
    at Array.forEach (<anonymous>)
    at e.exports (editor.js?ver=9.1:6)
    at f (editor.js?ver=9.1:6)
    at Module.<anonymous> (editor.js?ver=9.1:18)
    at o (editor.js?ver=9.1:1)
    at Object.<anonymous> (editor.js?ver=9.1:18)
    at o (editor.js?ver=9.1:1)
    at editor.js?ver=9.1:1
    at editor.js?ver=9.1:1]
```

The `index.js` file in my Mailchimp block plugin imports two SCSS files so the build process can create the corresponding CSS files:

```
import './editor.scss';
import './style.scss';
```

I found that if I comment out the `import './editor.scss'` line, Jetpack stops throwing the console errors. So, it seems there's something in my plugin that is conflicting with Jetpack. Am I importing the SCSS files the wrong way in my code? Can someone help me, please? I'm completely lost. 

Thanks

**Comment by noahtallen** [comment]
@mrleemon given that the error is coming from Jetpack, I would suggest opening an issue with jetpack here: https://github.com/Automattic/jetpack. Since this repository is not associated with Jetpack, it's unlikely we'll be able to get to the bottom of your problem!
