### ISSUE TITLE
wp-scripts: "Conflict: Multiple assets emit different content to the same filename"

### ISSUE THREAD

**Issue by EdwardBock** [WordPress/gutenberg#26989]
**Describe the bug**

If you use import 'style.css' in your gutenberg.js source file this will transpile to a gutenberg.js and a gutenberg.css file in your build folder. Both of them try to generate a gutenberg.map file which results in a webpack warning:

```
WARNING in Conflict: Multiple assets emit different content to the same filename gutenberg.map
```

You will only get one of the two sourcemap files.

**To reproduce**
1. Create src/style.css
2. Create src/gutenberg.js
3. Import style in gutenberg.js `import './style.css'`
4. Transpile with `wpscripts start`
5. See warning in terminal

**Expected behavior**
There should be two sourcemaps. One for the gutenberg.js file and one for the gutenberg.css file.

**Editor version:**
- WordPress version: 5.5.3

**Desktop:**
 - OS: Mac OS Catalina

**Comment by gziolo** [comment]
Can you try again with the latest version of `@wordpress/scripts` - v13 as of now. It got several improvements that try to address this type of issues. We are also trying to update webpack from v4 to v5 that has bet handling for CSS but it might take another couple of weeks.

**Comment by EdwardBock** [comment]
Looks good to me with version 13.0.2 👍 

Thanks!

**Comment by gziolo** [comment]
@EdwardBock, thank you for getting back so quickly 🙇‍♂️
