### ISSUE TITLE
Simple API for defining a block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#27]
We need a simple tool to let us quickly define a block (root element, custom attributes) to speed up the prototyping.

**Comment by aduth** [comment]
Should this issue encompass the final API for registering blocks, or is it merely for iterating on the UI prototype with a basic block structure ([which already exists to an extent](https://github.com/WordPress/gutenberg/blob/17cb3140ad3eaca3efee2f6f595c4a1b5a1699c4/blocks.js#L22-L88))?

**Comment by mtias** [comment]
This was for the UI only, so let's close it.

**Comment by aduth** [comment]
Should we create another issue for discussing requirements for a final block API?

**Comment by mtias** [comment]
Yes, feel free to start one.

**Comment by aduth** [comment]
See #104.
