### ISSUE TITLE
Add ability to have header column and row for tables

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2700]
This came up with John Parkinson as he did a mini-walkthrough of Gutenberg with me. He requested a feature of having a header/title like you have in spreadsheets. Being able to color/ style this would be great also. It's not a v1 probably, but it could be a great addition to users.

**Comment by afercia** [comment]
See also #1470, seems to me it's about the same thing. Table column (and rows) headers are `<th>` elements.

**Comment by jwold** [comment]
Agreed, on #1470 I created a mockup for how the header could be added in. Would LOVE to see us expand on what tables can offer.

**Comment by karmatosed** [comment]
Lets take the discussion there then :) Thanks for surfacing that.
