### ISSUE TITLE
Update @wordpress/scripts to use PostCSS 8

### ISSUE THREAD

**Issue by andrewstaffell** [WordPress/gutenberg#27028]
Many PostCSS plugins are now requiring PostCSS 8, and so resources using `@wordpress/scripts` are failling to `npm run build` with latest module versions, throwing errors like:

```Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-import requires PostCSS 8.
```

I think it's enough to bump the version of `postcss-loader` in `@wordpress/scripts` to  >= 4.0.3.

**Comment by ocean90** [comment]
To make sure we can use PostCSS 8 we have to wait a bit I think

* [`@storybook/core`](https://github.com/storybookjs/storybook/tree/master/lib/core) requires `postcss-loader@3`, see also https://github.com/storybookjs/storybook/issues/12668.
* [`@wordpress/postcss-themes`](https://github.com/WordPress/gutenberg/tree/master/packages/postcss-themes) has a hard requirement on `postcss@7`. This should probably be changed to `peerDependencies`, see also https://evilmartians.com/chronicles/postcss-8-plugin-migration.
* [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties/blob/master/package.json), used by `@wordpress/postcss-themes` has also a hard requirement on `postcss@7`. Open pull request at https://github.com/postcss/postcss-custom-properties/pull/229.

**Comment by andrewstaffell** [comment]
Thanks for the update @ocean90. Is there any known workaround for this issue in the meantime? As it stands resources are failing to compile with `@wordpress/scripts`... and plugins like `postcss-import` are pretty basic and hard to avoid. I tried npm shrinkwrap around the time I filed the issue but without success.

**Comment by ocean90** [comment]
Don't update plugins which require PostCSS 8. 🙈
I'm not aware of any workarounds but what I'd try is to use npm package alias and a custom webpack config. Something like `npm install postcss-loader-4@npm:postcss-loader@4` and `loader: require.resolve( 'postcss-loader-4' )`.

**Comment by gziolo** [comment]
https://www.npmjs.com/package/postcss-custom-properties v11 is now listing PostCSS v8 as a peer dependency 🎉

**Comment by shivapoudel** [comment]
@gziolo Any updates regarding PostCSS v8 implementation?

**Comment by gziolo** [comment]
We could give it a try and find a way to make Storybook work with PostCSS 7 and everything else with PostCSS 8.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/pull/27821 is now updated and everything seems to work with PostCSS v8. The only caveat is that we have Strorybook set to the prerelease version: `v6.2.0-rc.2`, but it works so personally think it's a good trade-off.

**Comment by gziolo** [comment]
Reverted in #30320 by @noisysocks due to issues with `wp-scripts start` in Gutenberg. It was also reported in https://github.com/WordPress/gutenberg/pull/27821#issuecomment-808925495 by @stokesman.

**Comment by gziolo** [comment]
Another attempt in #30347.

**Comment by interglobalmedia** [comment]
Hi, POSTCSS 8.3.0 is not working for me. Have no errors, but when I updated all npm packages yesterday including webpack to 5.38.1, my styles are not being added to the head in html. So No styling and no JS that depends on the styles to work. No errors in the console, though.
