### ISSUE TITLE
Full Site Editing: "Post Title" block should be view-only when template editing

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27029]
Until content has been loaded, it should not be possible to interact with the contents of the Post Title block. Currently, I am able to do this:

![no](https://user-images.githubusercontent.com/846565/99307452-6f039d00-284e-11eb-8fa4-c2292c39cfe5.gif)

Combined with the block description this is particularly confusing as it may trick users in to believing that they are creating a post while editing their template.

Instead I should see un-editable placeholder text (related: https://github.com/WordPress/gutenberg/issues/26856). Otherwise block controls (e.g. width and alignment) should still be interactive.

**Comment by karmatosed** [comment]
I'm going to swap out to needs dev as to me this just needs implementing as makes total sense.
