### ISSUE TITLE
Rerender core/image block after "Select or Upload Media" is closed

### ISSUE THREAD

**Issue by andrenakazato** [WordPress/gutenberg#27033]
I have a filename editor inside of "Select or Upload Media" modal.
Right now, I disable the "Select" btn when the filename ajax runs else the core/image will take the previous filename.

### Problem
Select the core/image added and try to replace the image: If you change the name of the image on the "Select or Upload Media" filename editor, after pressing "Select", it wont rerender (I think Gutenberg thinks it still the same image, hence no need of it), staying with the old image name and sending to the db the old image name instead.

![image](https://user-images.githubusercontent.com/5948306/99385874-e2022780-28d1-11eb-84a4-4566b5d8c8e5.png)

![image](https://user-images.githubusercontent.com/5948306/99385939-f7775180-28d1-11eb-8e49-be8ebdc2b2b2.png)
Changing name from image-test to image-unicorn

![image](https://user-images.githubusercontent.com/5948306/99385523-64d6b280-28d1-11eb-9292-c615c8c34ff3.png)
Log showing previous filename to new one in the db

![image](https://user-images.githubusercontent.com/5948306/99386161-4d4bf980-28d2-11eb-9701-6a5ed75dc5aa.png)
It still inserts with old filename

![image](https://user-images.githubusercontent.com/5948306/99386107-3c02ed00-28d2-11eb-8154-f4ac836a5820.png)
Even if you change the size, it does not search and insert the new filename

![image](https://user-images.githubusercontent.com/5948306/99386033-1d9cf180-28d2-11eb-985b-6ca6ce3051f0.png)
After "Update", the image still remains with old filename

Would like to know how to trigger the rerender the core/image block after "Select or Upload Media" is closed, fixing my current issue.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. Could you share your code that you use to create metabox and to edit the file name?
This will help the developers have a better understanding of the issue.

**Comment by kellychoffman** [comment]
Closing this due to lack of inactivity. Feel free to reopen if the issue resurfaces.
