### ISSUE TITLE
Posts List block: Update the block icons

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#27044]
## Problem 1: Block's toolbar icon
Currently, the Posts List block (a Query block variation) is displaying incorrect icons that represent both the Query block and the Posts List block. 

**Example of problem**

![Screen Shot 2020-11-17 at 7 56 35 AM](https://user-images.githubusercontent.com/617986/99413623-d51e0d80-28aa-11eb-9048-1ebad2225e3c.png)

It should mimic the Twitter Embed block that is a variation of the Embed block. Notice the Embed block icons remains in the block's toolbar, but the Twitter icon is next to the block's name in the block Placeholder.

![Screen Shot 2020-11-17 at 7 56 18 AM](https://user-images.githubusercontent.com/617986/99413616-d2bbb380-28aa-11eb-85e9-1aee02e9eeee.png)

### Solution
In the Posts List block toolbar, we should display the Loop icon.

![Screen Shot 2020-11-17 at 8 01 30 AM](https://user-images.githubusercontent.com/617986/99413906-1dd5c680-28ab-11eb-985a-565b7766884c.png)

I believe the goal is to still combine the Query and Loop blocks, so this loop icon would become the icon to represent the Query block.

## Problem 2: Block variation icon
For the Posts List block icon, we should consider how its best used. That particular icon represents the Latest Posts block and is temporarily being used as the settings icon for the Query block. 

**Query block**
![Screen Shot 2020-11-17 at 8 05 05 AM](https://user-images.githubusercontent.com/617986/99414439-ab191b00-28ab-11eb-8a51-eecb27d76cd2.png)

**Latest Posts block**
![Screen Shot 2020-11-17 at 8 05 19 AM](https://user-images.githubusercontent.com/617986/99414468-b3715600-28ab-11eb-927f-28469bd0f419.png)

### Possible solutions
There's only so many ways an icon can be designed to represent a feed.

**Option 1**
We use the same icon for every variation of the Query block. Since they're all lists with roughly similar content, this might be okay. It doesn't feel like a strong solution and doesn't provide a unique identity for the block.

**Option 2**
Use a new icon for each variation. This will increasingly become more and more difficult because designing a set of horizontal lines can only be done a few ways.

Any other options here? 
cc @ntsekouras

**Comment by ntsekouras** [comment]
> That particular icon represents the Latest Posts block and is temporarily being used as the settings icon for the Query block.

Wow, I totally missed that :slightly_smiling_face: . (https://github.com/WordPress/gutenberg/pull/26990#discussion_r523979472)

We should change either the variation icon or the settings icon. Thanks for spotting that @mapk !

>I believe the goal is to still combine the Query and Loop blocks, so this loop icon would become the icon to represent the Query block.

Let's keep these separate for now. 

Regarding problem 2
>We use the same icon for every variation of the Query block. Since they're all lists with roughly similar content, this might be okay.

This could be okay for now, since it will be only used in the init Placeholder of the Query and there is no other similar variation yet. We can revisit if we need to.

**Comment by mapk** [comment]
Okay, I propose that because the Loop block doesn't really make sense outside of the Query block, it acts like a child-block to the parent Query. That being said, let's align with both the Social Links block and the Buttons block that use the same icon for both the parent and child blocks.

**Social Links block**
![Screen Shot 2020-11-17 at 10 16 41 AM](https://user-images.githubusercontent.com/617986/99430405-22f04100-28be-11eb-8cd4-00148ed41ada.png)

**Buttons block**
![Screen Shot 2020-11-17 at 10 17 14 AM](https://user-images.githubusercontent.com/617986/99430417-271c5e80-28be-11eb-975f-b807a97f0a49.png)

So this is what the Query and Loop blocks should reflect:

![Screen Shot 2020-11-17 at 10 19 15 AM](https://user-images.githubusercontent.com/617986/99430564-5df27480-28be-11eb-9369-ca110c88422f.png)

**Comment by mapk** [comment]
When the two aforementioned PRs get merged (#27048 and #27057), the Query block's toolbar will look like this:

![toolbar](https://user-images.githubusercontent.com/617986/99466333-15a07a00-28f1-11eb-8c8d-182417df7e7d.png)

**Comment by ntsekouras** [comment]
Resolved with the two @mapk 's PRs. Thanks!
