### ISSUE TITLE
core/query block only offering a choice of 4 post types

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#27049]
**Describe the bug**
In the Query block's Settings the Post Type field is a selection list. 
In my development environments I could only get a maximum of 4 different post types listed.
In one environment it should have been 20.

The problem is that the logic that populates the drop down list uses an API returns a maximum of 10 items by default.
And 6 of these get filtered out. 

The 4 returned are:
- Post
- Page
- and two public custom post types

These are normally:
1. Attachments ( Media ) - which are specifically Excluded
2. Navigation menu items
3. Reusable blocks - not normally public ( `viewable` )
4. Templates
5. Template parts
6. Global styles

**To reproduce**
Pre-requisites:
- A Full Site Editing theme, such as Twenty Twenty-One Blocks.
- At least three custom post types which support the REST API and are `viewable`.

1. Add a new post
2. Add a Query block - choose any variation
3. View the Query block's settings - Filtering and Sorting panel
4. Select the Post Type drop down.
5. See a maximum of 4 post types listed.

**Expected behavior**
- The drop down should list all possible _viewable_ post types. 

See the full list of post types in the inspector. 
```
wp.data.select('core').getPostTypes( {per_page: -1 });
```

**Screenshots**
![core-query-loop-block-settings](https://user-images.githubusercontent.com/2474435/99435844-9cad1c80-2908-11eb-8809-b94fb6111a9b.jpg)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg 9.3.0 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**
- While investigating the problem I came across an issue on which I had already commented.
- https://github.com/WordPress/gutenberg/issues/15413
- The solution I proposed there is also applicable in this case.  

### Additional requirements

To be discussed in a separate issue.

- The list should include Attachments.
- It should include post types which do not support the REST API but which can be displayed to the end user.
- The list should be a multiple selection list.

**Comment by ntsekouras** [comment]
Thanks for raising this @bobbingwide ! I'll see your PR 👍
