### ISSUE TITLE
Gutenburg blocks damage SEO

### ISSUE THREAD

**Issue by Kattastick** [WordPress/gutenberg#27046]
Link attributes inside Gutenburg blocks unreadable by WP Meta SEO and I'm assuming search engines. What is the point of a website builder that can't be read or ranked by search engines? That's the antithesis of even having a website.
![image](https://user-images.githubusercontent.com/74616477/99422663-00a9f380-28bd-11eb-925c-a457e6549b59.png)

**Comment by bfiessinger** [comment]
@Kattastick The output of gutenberg pages that is readable by search engines is good old HTML. If the block you are using is not using a strange JavaScript technique that is delivering the content in any weird way search engines will be able to read the title Attributes.

Anyways the tooltip here says that the block "does not have any title attribute". Maybe you missed entering this attribute.

**Comment by talldan** [comment]
@Kattastick It'd be appreciated if you could use the issue templates when creating an issue.

As it is, the bug report is a bit vague, anyone attempting to look at this would need to know what WP Meta SEO does or is trying to do with links. I personally don't really understand it, but I'm not an SEO expert. Why does a link need a title attribute?

**Comment by talldan** [comment]
Closing due to lack of response.
