### ISSUE TITLE
Update button stays disabled for posts without title support

### ISSUE THREAD

**Issue by barryceelen** [WordPress/gutenberg#27040]
Post types without title support do not enable the "Update" button when only updating the featured image.

Likewise, the "Update" button is not automatically enabled if the post edit screen contains meta boxes.

**To reproduce not updating on featured image change:**
1. Register a post type without 'title' support
2. Create a new post
3. Open post edit screen for new post
4. Update featured image
5. The "Update" button stays disabled

**To reproduce not enabling update button if meta box is present:**
1. Register a post type without 'title' support
2. Register a meta box for that post type
3. Create a new post
4. Open post edit screen for new post
5. The "Update" button stays disabled

**Expected behavior**
The "Update" button should become enabled:
- when only editing the featured image
- if any meta boxes are present on the edit screen

**Editor version:**
- WordPress version: 5.5.3
- Gutenberg plugin version: 9.3.0

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

**Comment by skorasaurus** [comment]
I can reproduce this that the publish button is not enabled when ONLY adding a featured image 
on Gutenberg 9.6.2, Wordpress 5.6 ; Here's [a small test case](https://gist.github.com/skorasaurus/b279a99c74675eccf468295c57a88574) made with generatewp.

I can't find it at the moment, but I think there's an issue that's really closely related or directly addresses this.

**Comment by barryceelen** [comment]
Thanks for finding the duplicate @skorasaurus ! ❤️
