### ISSUE TITLE
Inconsistent string capitalization.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27085]
**Describe the bug**
I've noticed some inconsistent strings in the UI that could be improved.

The guide we're using is here - https://developer.wordpress.org/block-editor/contributors/document/copy-guide/#five-pay-attention-to-capitalization. It mentions that feature names are capitalized. It says 'feature labels' are sentence case. It doesn't show a feature name in a feature label, so this situation is unclear and open to interpretation.

In some places in the UI, features are capitalized:
- Welcome Guide (in the editor options menu)
- Block Manager (in the editor options menu)
- Reusable Block (the block's name. This also seems to be the only block suffixed 'Block', if that were dropped the use of 'Reusable block' elsewhere would seem to be ok)

In other places, they're sentence case (see almost everything in the editor options menu). Many of these seem as much 'features' as the Welcome Guide and Block Manager, especially the last four:
- Top toolbar
- Spotlight mode
- Fullscreen mode
- Visual editor
- Code editor

When used in sentences, feature names are handled inconsistently:
- Manage all reusable blocks
- Add to Reusable blocks
- Show More Settings

Then there are some that are easy fixes:
- Insert Before (should be 'Insert before')
- Insert After (should be 'Insert after')
- Move To (should be 'Move to')

**To reproduce**
1. Visit various parts of the UI

**Expected behavior**
Consistent capitalization.

**Comment by talldan** [comment]
Lots of these were changed in https://github.com/WordPress/gutenberg/pull/18758, but I think that probably didn't go far enough, so it'd be good to iterate again.

**Comment by talldan** [comment]
Some of these were changed in #28486 to be more consistent:
- Insert Before (changed to 'Insert before')
- Insert After (changed to 'Insert after')
- Move To (changed to 'Move to')
- Show More Settings (change to 'Show more settings')

So I think that mainly leaves the Reusable Blocks copy as being inconsistent:
- Manage all reusable blocks
- Add to Reusable blocks

**Comment by ntsekouras** [comment]
Closing as the remaining `Reusable` related labels have been changed here: https://github.com/WordPress/gutenberg/pull/29040, https://github.com/WordPress/gutenberg/pull/27026
