### ISSUE TITLE
Improve documentation for withNotices HOC in components package

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27091]
I want to create notices other than Error. How can I?

`noticeOperations.createSuccessNotice` doesn't work, neither does `noticeOperations.createNotice`

**Comment by talldan** [comment]
@navxio There's the `wp.data.dispatch( 'core/notices' ).createInfoNotice( 'My Message' )` API for general messages, is that what you're looking for?

**Comment by navxio** [comment]
@talldan that is correct but I wish to access wp.data outside of the gutenberg editor, which is why I'm trying to use `withNotices`

**Comment by talldan** [comment]
`noticeOperations.createNotice` should work, something like this:
```jsx

**Comment by talldan** [comment]
The statuses are listed in the docs for `Notice` (which you could also use directly yourself for your own notice system):
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/notice/README.md#props

The docs for `withNotice` are lacking, so I'll relabel and retitle this as an issue for a documentation improvement.
