### ISSUE TITLE
Query block variations switch

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#27117]
When I create a Query Block I have these different variations:

<img width="1711" alt="Screenshot 2020-11-19 at 17 46 04" src="https://user-images.githubusercontent.com/275961/99703546-24249800-2a8f-11eb-96e9-359782910f4f.png">

Once the block is inserted these options are gone. I'd like a way to change my selection here without editing it manually.

**Comment by ntsekouras** [comment]
Hey @scruffian - this will be handled with this issue: https://github.com/WordPress/gutenberg/issues/26962

**Comment by scruffian** [comment]
Thanks @ntsekouras. Closing as a duplicate of #26962
