### ISSUE TITLE
HTML preview doesn't update styles upon updates

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#27112]
See https://github.com/WordPress/gutenberg/pull/27065#issuecomment-730346444

In the site editor, users can update styles ―such as font family at the global level. Upon these changes, the HTML preview should be updated but it's not.

## How to test

- Install and activate TwentyTwentyOne blocks theme.
- Go to the site editor and add an HTML block with some content in uppercase.
- Preview: check that the font used is sans-serif.
- Open the global styles sidebar and update the font-family to a serif one.

The expected result is that the text previewed by the HTML should also change to serif.

**Comment by kathrynwp** [comment]
@oandregal Hi there - this appears to be working as expected now, so I'll go ahead and close this out. If anyone is still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.

Tested with:

Twenty Twenty-Two
WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
