### ISSUE TITLE
"Bold" uses font weight not available in Noto Serif font set

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2712]
## Issue Overview

Gutenberg uses `font-weight: 600` in many elements as a bolder font weight:

https://github.com/WordPress/gutenberg/search?utf8=%E2%9C%93&q=font-weight%3A+600&type=

Where not explicitly assigned, like post title, headings also fall back to the `font-weight: 600` default from WordPress admin styles:

https://github.com/WordPress/WordPress/blob/4.8.1/wp-admin/css/common.css#L310-L318

But the Noto Serif font pulled from Google Fonts does not include this weight:

https://github.com/WordPress/gutenberg/blob/fbb2d42032a8a333369dc073a176984785ffb4ee/lib/client-assets.php#L813-L816

The default behavior in most browsers to handle this is to try to emulate the weight, which can have undesirable effects:

https://alistapart.com/article/say-no-to-faux-bold

We should decide one of:

- Close this issue as "wontfix", and continue to use the emulated font weight
- Use Noto Serif at `font-weight: 700` for bold effects 
- Use a different font family

**Comment by mjchamplin** [comment]
I think using a typeface with a larger range of weights (or at least more than two) would be a good solution. There are lots of great options on Google Fonts that have a full range of weights.

**Comment by iseulde** [comment]
See also #2782.

**Comment by karmatosed** [comment]
I'm closing this as we have a discussion about fonts in #2782.
