### ISSUE TITLE
Save Fullscreen mode setting to database

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#27129]
**Describe the bug**
Apologies if this has already been created but I couldn't find a specific issue about this.

When is _Fullscreen mode_ going to be fixed so that it actually saves the setting to the database and doesn't constantly get reset every time the browser cache is cleared or WordPress is updated?

This option was forced onto everyone by default, with no adequate solution for being able to permanently turn it off.

**To reproduce**
1. Turn off  _Fullscreen mode_
2. Update WordPress
3. _Fullscreen mode_ is turned back on 

**Expected behavior**
If I turn an option off (or on), I expect it to remain that way and not magically get reset constantly

**Screenshots**
N/A

**Editor version (please complete the following information):**
- WordPress version: 5.6-RC1-49667
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin v9.4.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Firefox 82.0.3

**Comment by talldan** [comment]
https://github.com/WordPress/gutenberg/issues/15105 is the current issue tracking this, it's and described from a technical standpoint, which probably makes it tricky to find.
