### ISSUE TITLE
Find out if block has parent in save function on block validation

### ISSUE THREAD

**Issue by phmasek** [WordPress/gutenberg#27137]
I've been searching quite a lot to figure out how to determine if a block is within another block during block validation. 

The challenge I'm facing is that I want to wrap a block in a container if it's not inside any other block. This works fine if I know the `clientId` which is easy enough on edit/save as suggested [here](https://wordpress.stackexchange.com/a/346863). 

However, the save function is triggered on block validation when entering "edit page" throwing me a validation error because the save function does not hold the `clientId` on validation, thus not allowing me to determine if it's within another block.

Here's my code:

```javascript
const { addFilter } = wp.hooks;

export const blockHasParent = (clientId) =>
clientId !==
wp.data.select("core/block-editor").getBlockHierarchyRootClientId(clientId);

const modifyHeading = (settings) => {
  if (settings.name !== "core/heading") {
    return settings;
  }

  const newSettings = {
    ...settings,
    edit: (props) => {
      const hasParent = blockHasParent(props.clientId);
      // Pass the clientId to the save function
      props.attributes.clientId = props.clientId;

      if (hasParent) {
        return settings.save(props);
      }
      return <div className="container">{settings.save(props)}</div>;
    },
    save: (props) => {
      // props.attributes.clientId is undefined on block validation
      const hasParent = blockHasParent(props.attributes.clientId);

      if (hasParent) {
        return settings.save(props);
      }
      return <div className="container">{settings.save(props)}</div>;
    },
  };

  return newSettings;
};

addFilter(
  "blocks.registerBlockType",
  "my-plugin/modify-core-heading",
  modifyHeading
);

```

**Comment by talldan** [comment]
> The challenge I'm facing is that I want to wrap a block in a container if it's not inside any other block.

@phmasek That's a tricky one, this is a very particular use case, so it'd be interesting to find out more about why you need to do this, as there may be other options.

For static blocks, the block `save` function is supposed to be deterministic based only on a block's attributes. Checking a parent during save is circumventing that idea, which I think is why you're struggling to find a solution—there probably isn't one that uses `save`

**Comment by phmasek** [comment]
Thanks for your reply @talldan!
Yeah, you're probably right. I might be approaching this problem from the wrong angle. Here's a quick explanation of what I'm trying to achieve.

I'm building a custom theme in which most of the blocks will be bespoke. However, the plan is to reuse a few of the core blocks for "layouting" such as `core/paragraph`, `core/heading`, `core/columns`, etc.

I was previously thinking to create a custom block type that would act as a "section" block to which all other "layouting" blocks would refer to as their (only) parent. However, the UX of having to add a container block to be able to add any other block just seemed a bit off. 

The plan with this solution was thus to improve the UX so that the user don't have to manually wrap each part and let the theme wrap all "root blocks" through a hook.

**Comment by landwire** [comment]
@phmasek: did you find a solution yet? I am just looking to implement the same kind of thing. At the moment I am wrapping all blocks, but that can cause some problems with nested blocks. Therefore I am also looking for a way to only wrap the "top level" blocks.

**Comment by phmasek** [comment]
@landwire I went with an implementation using [ACF blocks](https://www.advancedcustomfields.com/resources/blocks/) instead. Running with a solution altering the core blocks became quickly out of budget.

The other solution comes with its own caveats so nothing is perfect. However, it was way faster and more intuitive to use than the core blocks.

**Comment by landwire** [comment]
@phmasek Thanks. I have not looked closely at ACF blocks yet, but is it possible with the ACF blocks to get the data of the ACF parent block(s)? If yes, could you share or point me to the direction on how to do it? 

Basically if I have an acf block "columns" with a 50% column, would my ACF block image which is inside that column somehow know that it is inside an ACF column block? Obvioulsy that is important to output the correct srcset and sizes for that ACF image block.

**Comment by phmasek** [comment]
I abandoned the idea completely and just went for a different architectural approach with nested custom blocks. Sorry that I can't help you any further.

**Comment by justingolden21** [comment]
Is this still not possible? Saw something online using `isset($block['attrs']['hasParent'])` but `hasParent` doesn't seem to be set in any of my elements, neither parent nor child.

**Comment by justingolden21** [comment]
I was able to use this `count($block['innerBlocks']) !== 0` to check for child blocks.

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this one as there's nothing actionable here. Thanks for contributing to the discussion, folks!
