### ISSUE TITLE
templateLock prevents programatic manipulation via useDispatch

### ISSUE THREAD

**Issue by Bysander** [WordPress/gutenberg#27139]
I'm looking for a way to lock a block template from human manipulation however allow the block logic to programmatically remove or add other blocks. Not being a react guru I thought I'd ask here in case I'm missing something before posting a bug report.

Issue: 

When setting templateLock to "all" with an example template like this 

(Not code syntax)

```
<Block> 
    <innerBlocks>
        <p>Number one</p>
        <p>Number two</p>
    </innerBlocks>
</Block>
```

1.
Get innerBlocks via `select( 'core/block-editor' ).getBlocksByClientId( clientId )[ 0 ].innerBlocks;`

2.
Get eg. paragraph 1 clientId through innerblocks returned in (1)

3.
Get removeBlock via `const { removeBlock } = useDispatch( 'core/block-editor');`

4.
using removeBlock and  clientId from (2) and (3) 

If templateLock is set to anything but false the removal of the block is not possible programmatically.

Am I missing something here?

**Comment by tellthemachines** [comment]
That is as expected:`removeBlock` is the function used under the hood when a user deletes a block manually, so if there's a template lock in place it's not called. 

I'm curious about the use case of having blocks add or remove blocks from their own inner blocks (if I'm reading your question correctly). Can the problem not be solved by offering multiple templates?

**Comment by Bysander** [comment]
Yeah multiple templates are a possible solution however in my case here it's preferable here to edit the block content ourselves as the number of templates required for my use case would be quite high and a lot of inserter "pollution" would occur for relatively minor changes to the template - a dropdown on the one block settings area with a radio select would be "tidier" and allow a large number of template options with only one entry in the inserter. The example above wasn't the intended implementation - just to highlight the issue. 

For anyone interested I got around these issues by using the `replaceInnerBlocks` function and having the template lock as "insert" rather than "all". It's not perfect as the editor can still move blocks out of place.

You can then also take the old content from the old blocks before the replace is called to build your new innerBlocks with `createBlock` 

Thank you for your time @tellthemachines

**Comment by ddryo** [comment]
@Bysander 
Thank you for the information.

I was also worried about the problem that `removeBlock()` could not be used when using `templateLock`, but I found this page and solved it by using `replaceInnerBlocks()`.

**Comment by ddryo** [comment]
@tellthemachines 
However, I would like to have an option that can force `removeBlock()` and `removeBlocks()` to be executed, so I will present it here as a functional request.

**Comment by nelsonamaya82** [comment]
I'm also trying to use `removeBlock()` to remove an inner block but it doesn't work, not even with `templateLock` set to false.

I'm getting the `clientId` of the inner block I want to remove, and passing it to `removeBlocks( clientId )`, but it just doesn't work.

I'm getting this response from this function:

`[[PromiseState]]: "fulfilled"
[[PromiseResult]]: undefined`
