### ISSUE TITLE
Navigation block: Item spacing

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#27132]
It would be nice to be able to add spacing between items in the Navigation block without custom CSS, like this:

<img width="925" alt="Screenshot 2020-11-20 at 10 01 20" src="https://user-images.githubusercontent.com/275961/99787512-be302300-2b17-11eb-8f8f-760176d7975c.png">

This would probably be done by using `space-between` in the CSS. It would work nicely with https://github.com/WordPress/gutenberg/issues/27131

**Comment by mkaz** [comment]
Fixed in #28169
