### ISSUE TITLE
How do I customise the move Block up / down behaviour?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27151]
Can I control what happens when you press up/down button on the block toolbar?
<img width="809" alt="image" src="https://user-images.githubusercontent.com/9297865/99817404-e0a35a00-2b72-11eb-9386-103cc8c82268.png">

**Comment by tellthemachines** [comment]
Toolbar up/down buttons can only be used move the block up or down within the same nesting level; there's no way of customising their behaviour. Is there anything in particular you are trying to do?

**Comment by navxio** [comment]
@tellthemachines hi! I mount the block as a react component on a static div.. moving the block up/down with arrows is causing the component to remount, and that too not properly. Any pointers?
Can I get an event when a block was moved ?
