### ISSUE TITLE
Updating Settings > General loses Your homepage displays setting  ( Settings > Reading )

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#27167]
**Describe the bug**
I recently noticed that when I changed the **Site Title** on **Settings > General**
the values I'd chosen for **Your homepage displays** on **Settings > Reading** were lost.

The unexpected result was that the template being used by Gutenberg FSE changed from `front-page.html `to `home.html`.

On deeper investigation I determined this be an upstream bug in Gutenberg 9.3+.
The version of WordPress is immaterial.

**To reproduce**
1. Ensure you have Gutenberg 9.3.0 or 9.4.0
2. Visit **Settings >Reading** and set values for **Your homepage displays**. eg Static page: Home and Blog
3. Visit **Settings > General**
4. Save Changes
5. Revisit **Settings > Reading**.
6. The values you set in step 2. have gone. The radio button isn't set. 

**Expected behavior**
Changing anything on the **Settings > General** page should not affect the **Your homepage displays** settings on Settings > Reading.

**Screenshots**
Step 2.
![image](https://user-images.githubusercontent.com/2474435/99876672-2a7e5580-2bf0-11eb-854e-6bcd695360d5.png)

Step 6.
![image](https://user-images.githubusercontent.com/2474435/99876713-58fc3080-2bf0-11eb-9aec-0b5ce250d450.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta4, but WordPress version is not applicable.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] 9.3.0 and 9.4.0 
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
- Screenshots copied from https://github.com/bobbingwide/fizzie/issues/40

**Comment by tellthemachines** [comment]
I can reproduce this on the latest master.

**Comment by ntsekouras** [comment]
Thanks for spotting and reporting this @bobbingwide 👍
