### ISSUE TITLE
Uploaded to this post

### ISSUE THREAD

**Issue by iamkingsleyf** [WordPress/gutenberg#27168]
Hi,

The UPLOADED  TO THIS POST feature in classic editor is missing from the BLOCK editor, now its IMPOSSIBLE to find images uploaded to article plenty months ago.

Thanks

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This has already been reported at https://github.com/WordPress/gutenberg/issues/12753
You can follow that issue for any updates.

**Comment by iamkingsleyf** [comment]
> Hi,
> 
> Thanks for reporting. This has already been reported at #12753
> You can follow that issue for any updates.

Since 2018?

**Comment by skorasaurus** [comment]
@iamkingsleyf 

Unfortunately, yes :(
