### ISSUE TITLE
Site Editor - Fix NavigateToLink component

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#27165]
The `NavigateToLink` component enhances the link-control to allow a user to navigate to that links context within the site editor when applicable.  This component seems to have broken at some point in time, as it doesn't seem possible to get it to appear in the link-control (it only appears if it can resolve a context to navigate to).

* Set a NavLink to a post entity in the site editor.
* Open the link control and verify there is no `NavigateToLink` component (edit icon) in the popover.

Upon quick inspection, it seems the props this component is dependent (`type` and `id`) on are coming in as `undefined`.

**Comment by kathrynwp** [comment]
@Addison-Stavlo Hi there! Are you still able to replicate this with the latest version of WordPress? If so, would you be able to clarify the steps to replicate in a little more detail? Thanks!

**Comment by Addison-Stavlo** [comment]
Oh wow, this is an old one! IF I am remembering the context correctly:

[This](https://github.com/WordPress/gutenberg/blob/59a3b775646f02ac610d6d74424cac36ebbd7cb5/packages/edit-site/src/components/navigate-to-link/index.js) `NavigateToLink` component was set up so that when a selects a link within the site editor (like a page in their navigation menu), it would provide an "Edit Page Template" option in that dropdown at the time to navigate the site editor to the template that that page/post would be viewed on. At some point the props to the component got messed up and the option to navigate to that template stopped showing up.

This is a couple years old at this point and it seems this functionality has been broken for a while. This component is still [filled into the site editor](https://github.com/WordPress/gutenberg/blob/c7c4858525e2ff2cca39bd68e4e2665c004b0826/packages/edit-site/src/components/block-editor/index.js#L161) but that "Edit Page Template" option on a link never shows up.

So IIRC you would repro by:
* Enter the Site Editor
* Select a page link
* open the link control popover (where you would edit the link URL, or open in new tab option)
* notice there is no "Edit Page Template" option showing up.

**Comment by kathrynwp** [comment]
@Addison-Stavlo Ah, thanks for those steps. I just tested and see what you mean, and there is no "edit page template" option showing. 

@talldan Would you happen know if this is a feature that's actually meant to be working, since as Addison points out, it's still referenced in the code? Thanks!

**Comment by Mamaduka** [comment]
The component is no longer used in the core after #47454.

@draganescu, @getdave, should we remove it?

**Comment by getdave** [comment]
I don't see a reason why we need it. We can deprecate it.

**Comment by Mamaduka** [comment]
@getdave, it's not a public component, so we can just remove it. I'll create a PR. Thanks for the confirmation.
