### ISSUE TITLE
How to set font sizes with EM instead pixel

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#27169]
Hi, I am working on my website theme and I realized that Gutenburg does not set font sizes with EM it uses pixel.
It causes some problem for me how can I handle this? Is there any feature to **change the default unit for font size**?

**Comment by tellthemachines** [comment]
Hi @amirmp3 , I'm afraid it's not possible to change the default font-size unit. 

There is work ongoing to replace `px` units with `em`, started in #24523. Eventually all uses of `px` units should be replaced, as that's the only way to fix #15356, but it might take a while to get there.
