### ISSUE TITLE
Font-Size Control not set at the actual font-size

### ISSUE THREAD

**Issue by 00travelgirl00** [WordPress/gutenberg#2716]
When a user want to change the font-size and starts to use the controler, the font-size will be really large and you the user has no information about the default font-size. 

For a better UX it would be nice, to start the controler at the actual font-size and also the information in the text-box about the font-size. 

![font-schieber](https://user-images.githubusercontent.com/21318377/30298265-0d35dde6-974b-11e7-9b5e-1616f33b8a1e.gif)

**Comment by iseulde** [comment]
Not the same issue, but certainly has some overlap: #2610.

**Comment by jasmussen** [comment]
This was fixed by @jorgefilipecosta recently! 

<img width="925" alt="screen shot 2018-04-17 at 11 39 09" src="https://user-images.githubusercontent.com/1204802/38861940-ff3bfd3a-4233-11e8-98b9-9213abad1e88.png">
