### ISSUE TITLE
Docs: Add note in @wordpress/eslint-plugin about min version for npm

### ISSUE THREAD

**Issue by evasoek** [WordPress/gutenberg#27161]
When installing @wordpress/eslint-plugin I get the error:

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:wp-prettier@2.0.5

I'm just running the command:
`npm install @wordpress/eslint-plugin --save-dev`

**Comment by gziolo** [comment]
Can you check which version of node and npm you have?

**Comment by evasoek** [comment]
> Can you check which version of node and npm you have?

Yeah NPM was outdated, updating fixed the issue. Thanks for your reply!

**Comment by gziolo** [comment]
We should include a note in the package description with requirements, just in case someone runs into the same issue 😃

**Comment by evasoek** [comment]
> We should include a note in the package description with requirements, just in case someone runs into the same issue 😃

Yes definitely haha! Great idea 😁

**Comment by gziolo** [comment]
Opened https://github.com/WordPress/gutenberg/pull/27203 that documents requirements.
