### ISSUE TITLE
Block float is broken

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#2717]
When writing a post with blocks that float left and right, editing is really confusing as the blocks jump around, as in this video: note how clicking in the first paragraph shifts the paragraph to a different spot, etc

![blockfloatbroken](https://user-images.githubusercontent.com/25762760/30309540-3046d4e6-97cf-11e7-8d1e-ee5b86d4e67e.gif)

**Comment by karmatosed** [comment]
Hmm that doesn't look great, let's see what we can do to fix it. Was there any particular browser you saw this in?

**Comment by mtias** [comment]
I don't see this happening anymore.
