### ISSUE TITLE
Consider a way to allow/disallow alignment for InnerBlocks

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#27179]
**Problem**

Currently, when a block is allowed to be inserted as an InnerBlock it will default to having the same alignment options as normal. In some instances - this isn't appropriate.

Example. In enabling the 'Social Links' block to be included in the Navigation block - the alignment options were still available despite the fact contextually the social links should effectively appear inline with the other menu items. Selecting an alignment for the Social LInks block can break the appearance of the Navigation block altogether

![](https://user-images.githubusercontent.com/1842363/93011017-fa09b200-f5d5-11ea-81e4-a5cebb5c6263.png)
[link to image](https://user-images.githubusercontent.com/1842363/93011017-fa09b200-f5d5-11ea-81e4-a5cebb5c6263.png)

Ref: #25016

**Proposed Solution**

It would be great if there were a way to define the alignment support for blocks contextually - or be able to overide it when the block is used as an InnerBlock. Anything above that general idea is above my pay grade ;)

**Comment by talldan** [comment]
This sounds similar to what was introduced in #26380 with the `layout` prop:
https://github.com/WordPress/gutenberg/pull/26380/files#diff-1ec6503d5cd2292d6fd7edfbea747f6a9211a16c4c63bd6d894446603776beacR23-R26

Now when a button block is used within the buttons block the alignment option is not displayed, but if it's used outside buttons (I think this is currently only possibly by copy/pasting a button block in the code editor) it still does support alignment.

**Comment by jordesign** [comment]
Thanks @talldan  - does that mean a similar approach could be used with the Social Links block?

**Comment by talldan** [comment]
@jordesign Yep, I believe it could be defined on the navigation block to stop inner blocks having alignment.

**Comment by jordesign** [comment]
Thanks for the direction @talldan - I was able to open a PR with the same approach as that used on the Buttons block.

**Comment by talldan** [comment]
Fixed by #27365
