### ISSUE TITLE
Doubled image when pasting from clipboard

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#27190]
**Describe the bug**
When pasting image from clipboard, while having already empty `/image` block inserted, another block of the same type is added and pasted image lands in two copies in current post.

**To reproduce**
1. Start editing any post
2. Start a new block, type `/image` or otherwise add image-type block
3. Paste any image
4. See that image was pasted twice. Once into existing empty image-type block and second time to newly created block of the same type.

**Expected behavior**
Image should be always pasted into its very own, newly created block. Existing empty image-type block should not be affected in anyway.

**Screenshots**
![Example](https://user-images.githubusercontent.com/2903392/99952284-af4ba980-2d7f-11eb-9f0a-be4a6b34bf98.jpg)

**Editor version (please complete the following information):**
- WordPress version: **5.5.3**
- Gutenberg plugin: **Version 9.4.1 | By Gutenberg Team**

**Desktop (please complete the following information):**
 - OS: **Windows 10**
 - Browser **Chrome**
 - Version **86.0.4240.198**

**Comment by ntsekouras** [comment]
Tested and I confirm is a bug. Pasting an image creates two `Image` blocks. You can test this in a post without content.

The case in the issue is different because the empty (Placeholder state) Image block was selected. It copies once on the Image block and creates a new one.
