### ISSUE TITLE
Saving a gutenberg block in widget area fails

### ISSUE THREAD

**Issue by digitalverint** [WordPress/gutenberg#27197]
**Describe the bug**

I want to use Gutenberg blocks in the widgets area.  When I try to save, I get an error

**To reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65187522/99963575-fb86f180-2d5f-11eb-83be-36a2a4f8df22.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] gutenberg plugin is installed.  Block editor is enabled in theme
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 9.4.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 83.0

**Additional context**
Here are the console errors
Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://helloworldshirts.com/wp-admin/themes.php?page=gutenb…e%5D%5Bnav_menu%5D=8&widget-preview%5BsidebarId%5D=sidebar-1", lineNumber: 13, columnNumber: 0, data: null, stack: "l@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=BROWSE%20DESIGNS&widget-preview%5Binstance%5D%5Bnav_menu%5D=8&widget-preview%5BsidebarId%5D=sidebar-1:13:385\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=BROWSE%20DESIGNS&widget-preview%5Binstance%5D%5Bnav_menu%5D=8&widget-preview%5BsidebarId%5D=sidebar-1:13:1110\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=BROWSE%20DESIGNS&widget-preview%5Binstance%5D%5Bnav_menu%5D=8&widget-preview%5BsidebarId%5D=sidebar-1:13:1788\n" }
themes.php:13
    l https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview[widgetClass]=WP_Nav_Menu_Widget&widget-preview[name]=Navigation Menu&widget-preview[idBase]=nav_menu&widget-preview[number]=3&widget-preview[instance][title]=BROWSE DESIGNS&widget-preview[instance][nav_menu]=8&widget-preview[sidebarId]=sidebar-1:13
    <anonymous> https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview[widgetClass]=WP_Nav_Menu_Widget&widget-preview[name]=Navigation Menu&widget-preview[idBase]=nav_menu&widget-preview[number]=3&widget-preview[instance][title]=BROWSE DESIGNS&widget-preview[instance][nav_menu]=8&widget-preview[sidebarId]=sidebar-1:13
    <anonymous> https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview[widgetClass]=WP_Nav_Menu_Widget&widget-preview[name]=Navigation Menu&widget-preview[idBase]=nav_menu&widget-preview[number]=3&widget-preview[instance][title]=BROWSE DESIGNS&widget-preview[instance][nav_menu]=8&widget-preview[sidebarId]=sidebar-1:13

 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://helloworldshirts.com/wp-admin/themes.php?page=gutenb…nce%5D%5Bexclude%5D=&widget-preview%5BsidebarId%5D=sidebar-1", lineNumber: 13, columnNumber: 0, data: null, stack: "l@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Widget_Pages&widget-preview%5Bname%5D=Pages&widget-preview%5BidBase%5D=pages&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bsortby%5D=post_title&widget-preview%5Binstance%5D%5Bexclude%5D=&widget-preview%5BsidebarId%5D=sidebar-1:13:385\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Widget_Pages&widget-preview%5Bname%5D=Pages&widget-preview%5BidBase%5D=pages&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bsortby%5D=post_title&widget-preview%5Binstance%5D%5Bexclude%5D=&widget-preview%5BsidebarId%5D=sidebar-1:13:1110\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Widget_Pages&widget-preview%5Bname%5D=Pages&widget-preview%5BidBase%5D=pages&widget-preview%5Bnumber%5D=3&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bsortby%5D=post_title&widget-preview%5Binstance%5D%5Bexclude%5D=&widget-preview%5BsidebarId%5D=sidebar-1:13:1788\n" } 
Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://helloworldshirts.com/wp-admin/themes.php?page=gutenb…Bnav_menu%5D=10&widget-preview%5BsidebarId%5D=sidebar-footer", lineNumber: 13, columnNumber: 0, data: null, stack: "l@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=5&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=10&widget-preview%5BsidebarId%5D=sidebar-footer:13:385\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=5&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=10&widget-preview%5BsidebarId%5D=sidebar-footer:13:1110\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=5&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=10&widget-preview%5BsidebarId%5D=sidebar-footer:13:1788\n" }
 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://helloworldshirts.com/wp-admin/themes.php?page=gutenb…Bnav_menu%5D=11&widget-preview%5BsidebarId%5D=sidebar-footer", lineNumber: 13, columnNumber: 0, data: null, stack: "l@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=6&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=11&widget-preview%5BsidebarId%5D=sidebar-footer:13:385\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=6&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=11&widget-preview%5BsidebarId%5D=sidebar-footer:13:1110\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=6&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=11&widget-preview%5BsidebarId%5D=sidebar-footer:13:1788\n" } 

Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://helloworldshirts.com/wp-admin/themes.php?page=gutenb…5Bnav_menu%5D=9&widget-preview%5BsidebarId%5D=sidebar-footer", lineNumber: 13, columnNumber: 0, data: null, stack: "l@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=4&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=9&widget-preview%5BsidebarId%5D=sidebar-footer:13:385\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=4&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=9&widget-preview%5BsidebarId%5D=sidebar-footer:13:1110\n@https://helloworldshirts.com/wp-admin/themes.php?page=gutenberg-widgets&widget-preview%5BwidgetClass%5D=WP_Nav_Menu_Widget&widget-preview%5Bname%5D=Navigation%20Menu&widget-preview%5BidBase%5D=nav_menu&widget-preview%5Bnumber%5D=4&widget-preview%5Binstance%5D%5Btitle%5D=&widget-preview%5Binstance%5D%5Bnav_menu%5D=9&widget-preview%5BsidebarId%5D=sidebar-footer:13:1788\n" }

**Comment by ilenejohnson** [comment]
any progress on this?

**Comment by Aljullu** [comment]
This is probably the same issue as https://github.com/WordPress/gutenberg/issues/27173. Closing this one as a duplicate, but feel free to reopen if I got it wrong.
