### ISSUE TITLE
Tricky/fiddly to drag Cover block opacity slider from 100% (Safari specific) 

### ISSUE THREAD

**Issue by haszari** [WordPress/gutenberg#27215]
**Describe the bug**
When dragging the slider thumb for the cover block, I need to carefully move my mouse from the thumb across to the slider line. If I drag the thumb normally, it's usually "stuck" at 100%.

![Screen Capture on 2020-11-24 at 13-16-57](https://user-images.githubusercontent.com/4167300/100030009-69621480-2e57-11eb-8d9d-1f7752691b67.gif)

**To reproduce**
In Safari only…
1. Go to editor.
2. Add a cover block.
3. Open sidebar.
4. Click cover block. 
4. Expand overlay options panel.
4. Set opacity to 100%.
4. Drag the thumb back down from 100%. In my experience it's very tricky!

**Expected behavior**
Easy to drag the slider thumb around on any setup – e.g. with tired old wrists, on a sloping desk, with a badly mounted trackball, at night, while drunk :)

**Editor version (please complete the following information):**
- WordPress & Gutenberg version(s): Saw this in WP 5.6 RC1 (no Gutenberg) and WP 5.5.3 + Gutenberg 9.4.1

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1 (20B29)
 - Browser: Safari 
 - Version: 14.0.1 (16610.2.11.51.8)

**Comment by stokesman** [comment]
To me, this looks like a more specific description of #25345 (which coincidently just got closed a bit earlier today when a fix for it was merged as part of #26745). I see in the screen recording the drag that finally worked was started on the inside half of the knob/thumb/doohickey which is as detailed in the earlier issue.

**Comment by tellthemachines** [comment]
Tested and seems to be fixed now. Ok to close this issue?

**Comment by haszari** [comment]
@tellthemachines - Happy if you're happy – I haven't personally tested but looks like this is sorted, thanks :)
