### ISSUE TITLE
Button Block: the Default Border radius is 5 but not visible the effect in button

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#27218]
Describe the bug
in Button Block the Default Border radius is 5 but not visible the effect in button

Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Button'
5. View the option 'Border radius'
6. See error

Expected behaviour
if we have default border radius 5 then it should affect in button border else we have to set the default border radius 0 instead of 5

Screenshots
https://prnt.sc/vovj99

Video
for more detail please view the attached video
https://www.loom.com/share/1175a0d540bb48078fb02949c796434f

Editor version:
WordPress version: 5.6-RC1

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by talldan** [comment]
Thanks for reporting, it looks like #17596 was created for the same issue so I'll close as a duplicate.
