### ISSUE TITLE
Donations Block within a Layout Grid causes contents to collapse into one column

### ISSUE THREAD

**Issue by adelineyaw** [WordPress/gutenberg#27216]
Adding a Donations Block within a Layout Grid, (assuming there are multiple columns), causes all contents within the Layout Grid to collapse into the first column.

**To reproduce**
1. Edit any post/page
2. Click on + Layout Grid, then select 'two column'
3. Add a Donations Block in the first column
4. Within the second column, add any block
5. Preview post/page, and you will see the error, ie. all contents collapsed in one column.

**Expected behavior**
We should expect to see the same results within the Editor, appear when previewed on the front-end.

**Screenshots**
1). List view of Layout Grid used: ​https://d.pr/i/An0lhO
2). Editor view: https://d.pr/i/QPO3Dc
3). Video (of front-end preview): ​https://d.pr/v/5Mwdiq

**Comment by talldan** [comment]
Hi @adelineyaw, there isn't a layout grid block or a donation block in WordPress core so I'll close the issue.

Was this block provided by a plugin?

**Comment by adelineyaw** [comment]
@talldan I was of the understanding that these blocks are native on WordPress.com. The customers site is on a Personal plan so no plugins are allowed. And I was able to replicate the issue on a Premium plan site (which doesn't allow for plugins to be installed either).

![Description of image](https://d.pr/i/iPorzo+)
Image link: https://d.pr/i/iPorzo

![Description of image](https://d.pr/i/bOYW6x+)
Image link: https://d.pr/i/bOYW6x

**Comment by adelineyaw** [comment]
Thanks @talldan - it's part of Jetpack so I've moved the issue here: https://github.com/Automattic/jetpack/issues/17894
