### ISSUE TITLE
DatePicker closes after clicking AM/PM or calendar date

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27222]
**Original report by codedread**
https://core.trac.wordpress.org/ticket/51639

**Description**
> The date/time editor for scheduling blogs used to be you could click and set the month/day, time, AM/PM before closing it. Now if you select AM/PM or if you select a day, the picker closes, meaning I have to open it 3 times to set the date/time!

This happens with WordPress 5.5, but not version 5.4.

**To reproduce**
1. Open the DatePicker to schedule a post.
2. Activate the unselected AM or PM button (by clicking or using spacebar) to switch the time.
3. After the dialog closes, re-open the DatePicker to select one of the dates in the calendar table.
4. Each time, the dialog closes with a single (partial) edit.

Plus, when using the keyboard (Enter or space), the focus is not anywhere near the sidebar to re-open the datepicker for adjusting another part of the date.

**Expected behavior**
Allow selecting all parts of the date and time before closing the dialog.

**Editor versions**
- WordPress 5.5.2 with Gutenberg 9.2.2
- WordPress 5.6 RC1 with Gutenberg 9.4.1

**Desktop**
 - OS: Windows 10
 - Browsers: Firefox 82, Chrome 86, and Edge 86

**Comment by ocean90** [comment]
Related/Duplicate: #24206

**Comment by tellthemachines** [comment]
Closing this in favour of #24206.
