### ISSUE TITLE
Global Styles: Should we Allow CSS properties that we don't manage at the moment?

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#27231]
In theme.json should we generate styles for properties we don't manage or provide an explicit UI control?
E.g. if a theme passes:
```
"core/paragraph": {
	"styles": {
		"textShadow": "2px 2px pink";
	}
}
```
Or
```
"core/paragraph": {
	"customStyles": {
		"textShadow": "2px 2px pink";
	}
}
```

Should we generate text-shadow styles for the paragraph or not?

**Comment by aristath** [comment]
YES!!!
If we do this then we're getting closer to a full JSON-based theme. Technically there's nothing stopping us from doing this... If we don't do it, then theme-authors will just add them to a stylesheet. which is fine, but not as good as having a single-source-of-truth in the JSON file :heart:

**Comment by pagelab** [comment]
> If we do this then we're getting closer to a full JSON-based theme

I would be truly awesome to see that happen.

**Comment by carolinan** [comment]
This would be great or even necessary :)

**Comment by samanthaberkley** [comment]
We say yes, just like [jazz](https://make.wordpress.org/design/2023/03/30/why-jazz/)!

**Comment by youknowriad** [comment]
I think this is largely addressed with the "css" property today. Please let me know if this is not enough.
