### ISSUE TITLE
Scrollbar appearing in inspector sidebar

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#2723]
![pasted_image_at_2017_09_13_11_15_am_480](https://user-images.githubusercontent.com/191598/30393596-8ab0193c-9875-11e7-8a2a-1814b51a8563.png)

In Safari (Version 10.1.2 (12603.3.8)) I'm seeing an unnecessary scrollbar in the inspector sidebar.

**Comment by karmatosed** [comment]
I think it's the same issue as https://github.com/WordPress/gutenberg/issues/1899 - so going to close and merge them together.
