### ISSUE TITLE
Plugin Conflict with Ultimate Addons for Gutenberg

### ISSUE THREAD

**Issue by sarah-kp** [WordPress/gutenberg#27248]
**Describe the bug**
There is a plugin conflict with Gutenberg plugin and the [Ultimate Addons for Gutenberg](https://www.ultimategutenberg.com/). We've going through steps with the UAG plugin developers to find out what was causing the confilct and have determined it's the Gutenberg plugin. 

UAG allows us to create reusable blocks that we use on different pages. When the Gutenberg plugin is installed and active, we are not able to access the full library of reusable blocks. 

**To reproduce**
1. Go to 'http://bundillapestc.staging.wpengine.com/wp-admin'
httaccess: bundillapestc/f622ddfa
/wp-admin login: web@kickpoint.ca/7ytR)yD2n)1ogOaD
2. Click on 'Pages > About Bundilla Pest Control'
3. Scroll down to 'Add new block, select Browse All and then select the Reusable tab'
You'll see 10 reusable blocks and then a link that says Manage all reusable blocks.

**Expected behavior**
 There should be more than 10 resuable blocks. We have 30 blocks that should be displayed here. 

**Screenshots**
1Shows what we see. There should be 30 reusable blocks there, not 10. When we disable your plugin all resuable blocks are shown. 
<img width="352" alt="UAG Resuable Blocks - Results" src="https://user-images.githubusercontent.com/74982909/100135845-7119bd00-2e47-11eb-9572-d0c0aabbde13.png">

**Editor version (please complete the following information):**
- WordPress version: Version 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 86.0.4240.198 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@sarah-kp Thanks for reporting. This issue has been fixed in version 9.3 of the Gutenberg plugin, https://github.com/WordPress/gutenberg/pull/26486 is the change that fixed it.
