### ISSUE TITLE
Paragraph block color swatches misaligned

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#2725]
When viewing the inspector sidebar for a paragraph block (and maybe others?), the list of color swatches has some misbehaving circles:

![pasted_image_at_2017_09_13_11_16_am_480](https://user-images.githubusercontent.com/191598/30394169-270a4220-9877-11e7-8fad-49f12fdd4334.png)

**Comment by afercia** [comment]
@shaunandrews would you mind checking if https://github.com/WordPress/gutenberg/pull/2680 fixes this issue (among other things)?

Aside: Not sure why there are 5 colors per line in your screenshot, I have 6 colors per line.

**Comment by shaunandrews** [comment]
> Aside: Not sure why there are 5 colors per line in your screenshot, I have 6 colors per line.

Maybe 'cause of #2723 — the extraneous scrollbar in safari is stealing some space.

**Comment by mtias** [comment]
Safari looks fixed to me.
