### ISSUE TITLE
Make notices in Gutenberg within an AJAX running

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#27258]
Hello,
I've a PHP running with AJAX, and I'm wondering how to make notices in Gutenberg.

I've a JS with this code to run the notice:

```
    ( function( wp ) {
    	
    	wp.data.dispatch('core/notices').createNotice(
    		'error',
    		'Message of error',
    		{
    			isDismissible: true,
    			actions: [
    				{
    					url: '#',
    					label: 'Button'
    				}
    			]
    		}
    	);
    } )( window.wp );
```

But I don't know how to make it run, maybe with a variable or something.
How could make it work?

**Comment by tellthemachines** [comment]
Hi @davidperezgar! Are you running this code in the context of a theme or a plugin? If so, the best place to look for help is the [support forums](https://wordpress.org/support/forums/). This repo is for reporting issues with Gutenberg itself.

**Comment by annezazu** [comment]
@davidperezgar going to close this issue out as this does seem best for the support forums. Feel free to re-open if you think otherwise!

**Comment by davidperezgar** [comment]
ok! ;)
