### ISSUE TITLE
“Schedule” displaying instead of “Publish” on new posts/pages

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#27251]
**Describe the bug**
When creating a new post or page, the "Schedule" button is displaying instead of "Publish".  First reported by @melchoyce .

**To reproduce**
This is occurring locally and on https://wordpress.org/support/.

1. Go to 'Posts.'
2. Click on 'Add New'

**Expected behavior**
Should display the "Publish" button.

**Screenshots**
![Screen Shot 2020-11-24 at 12 49 12](https://user-images.githubusercontent.com/7284611/100137079-88f63e80-2e51-11eb-88f0-e092b8690cc3.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6-RC1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.4.1

Timezone: Set to UTC+0, but Tammi notes timezone is actually UTC -4.

**Additional context**
- A similar issue was reported in https://github.com/WordPress/gutenberg/pull/26212 which was resolved and merged Oct 19th and backported. This PR changed `dateI18n` to `format` in packages/editor/src/components/post-schedule/label.js
- But then this change was reverted in https://github.com/WordPress/gutenberg/pull/25782 and merged Nov 10th.

Props to @desrosj and @karmatosed.

**Comment by talldan** [comment]
I wasn't able to reproduce. I tried 5.5.3, latest 5.6 and also latest 5.6 with the latest code from the Gutenberg plugin active.

Not sure if it's related to timezones, I tried a few different settings for that.

I'll leave it open so it can get some further testing/debugging.

**Comment by talldan** [comment]
Possibly fixed by #26276.

**Comment by paaljoachim** [comment]
Testing. 

Locally using Desktop Server and Chrome.
Theme: Twenty Twenty One
WordPress version: 5.6 RC 1
Plugins activated: Gutenberg 9.4.1 and WordPress Beta Tester.
Timezone: UTC+0

Creating a new page. I click Publish. Go to the next step and the Publish button is seen.
Creating a new post. Same results as for new page. 

Switched to UTC-4. Results are the same.

From the above testing I was not able to see any error where the word "Publish" was switched out with the word "Schedule".

**Comment by ockham** [comment]
FWIW, we've seen this reported by a number of users (and have been able to reproduce ourselves, albeit not consistently) on WordPress.com after upgrading to Gutenberg 9.4.1. See this issue: https://github.com/Automattic/wp-calypso/issues/47938

**Comment by sirreal** [comment]
I've been able to reproduce this by creating a site with the latest Gutenberg release. When the site timezone is set with a greater UTC offset than my browser time, the bug manifests. For example, browser time is UTC+1 and site time is UTC+14.

If the site time matches or has a lesser UTC offset than the browser, the bug does not manifest.

**Comment by david-szabo97** [comment]
✔️  Fixed in #27550
➕ Regression tests are being added by #27558
