### ISSUE TITLE
Figma: Button component using wrong typeface?

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#27265]
We were doing some work with the Figma library "WordPress Components" and we noticed that the Button component is marked as using SF Pro Display:

<img width="401" alt="Screenshot 2020-11-25 at 10 21 06" src="https://user-images.githubusercontent.com/4389/100214631-054b5900-2f08-11eb-8fc5-de23be44124c.png">

However, per [SF Pro guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/typography/), "Display" is to be used only of sizes 19px+, while "Text" should be used for anything smaller.

—

### Meta

It seems there are multiple Figma libraries. From earlier conversation and the [documentation](https://make.wordpress.org/design/handbook/get-involved/gutenberg-contribution/wordpress-components/) we started using WordPress Components, but there's a bit of a confusion WHICH master should be used for all new WP Admin / Gutenberg designs. 

These are the current libraries:

* WordPress Design Library https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library
* WordPress Components https://www.figma.com/file/ZtN5xslEVYgzU7Dd5CxgGZwq/WordPress-Components

There are others, but these two _seem_ to be the ones that were intended to be used at some point.

→ Would be useful to have only one, or at least have a clarification and some clear guidance on which to use.

**Comment by jameskoster** [comment]
My understanding is that WordPress Design Library was created to serve as a single asset for all designers to use, is the more active project, and supersedes WordPress Components & co.

The WordPress Components file is an older initiative. Iirc there were additional libraries for colors and text styles as well. Perhaps these are the "others" you mention. As far as I know none of these are any longer maintained, whereas the WordPress Design Library is.

**Comment by karmatosed** [comment]
I went also on some exploring here and the problem seems to be documentation. There is a post which notes about the libraries being combined, however the documentation wasn't updated. I have taken a few steps to tie a few pieces together on this:

- Created an archive folder in Figma and put the 3 extra libraries into it.
- Updated handbooks: https://make.wordpress.org/design/handbook/get-involved/tools-figma/ and https://make.wordpress.org/design/handbook/get-involved/gutenberg-contribution/wordpress-components/

I will also update the #design channel so contributors are aware of these changes. Just to close the communication loop.

**Comment by folletto** [comment]
Ok. So the "WordPress Design Library" is the reference, got it. 

I guess then we should:
1. Make that official
2. Mark the old ones in some way as deprecated

:) 

As for the button issue, that's already solved in "WordPress Design Library", so that would automatically be sorted out. Ref:

<img width="327" alt="Screenshot 2020-11-25 at 11 02 32" src="https://user-images.githubusercontent.com/4389/100219322-bd2f3500-2f0d-11eb-8cc4-2bd0c3c03c62.png">

**Comment by jeffgolenski** [comment]
@karmatosed Thanks for wrangling those updates. How would I go about acquiring access to the new Design Library? I'm unable to view it

**Comment by karmatosed** [comment]
@jeffgolenski I reached out to give you acces.
