### ISSUE TITLE
RangeControl's tooltip overlaps label

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27261]
**Describe the bug**
When `RangeControl` has a visible label, the tooltip from the slider overlaps the label.

**To reproduce**
1. Add an image to an image block
2. Select the crop option
3. Select the zoom option
4. Observe the tooltip overlaps the label.

**Expected behavior**
The tooltip is below the slider

**Screenshots**
<img width="131" alt="Screenshot 2020-11-25 at 4 52 01 pm" src="https://user-images.githubusercontent.com/677833/100204417-d0a6c400-2f3e-11eb-9d81-529a382d8458.png">

(The screenshot also shows the separate issue with the zero width slider https://github.com/WordPress/gutenberg/issues/27126)

**Comment by Tonnie-Exelero** [comment]
Can I look into this @talldan?

**Comment by talldan** [comment]
@Tonnie-Exelero That would be great, thanks!

**Comment by kishanjasani** [comment]
@talldan I am not able to reproduce. There is no label on the zoom option.
![screenshot-guten local-2020 11 28-14_56_37](https://user-images.githubusercontent.com/25550562/100498682-f4aa1580-3189-11eb-9b6e-e3cee888207d.png)

**Comment by talldan** [comment]
@kishanjasani Thanks for testing. The change that added the label was only just merged - https://github.com/WordPress/gutenberg/pull/24574 - it'll be in Gutenberg 9.5.

**Comment by Tonnie-Exelero** [comment]
@talldan Thanks for sharing this PR ([#24574](https://github.com/WordPress/gutenberg/pull/24574)) in your previous comment. Going by the discussion there, as I have planned to work on the issue this weekend, it looks like a good idea to push the tooltip to the bottom, or rather just below the Range control. I'll put up the change.
