### ISSUE TITLE
Navigating the block inserter with keyboard plays games with :focus

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#2726]
![what the what](https://user-images.githubusercontent.com/191598/30394672-9f76f87e-9878-11e7-9d41-955fc4567b95.gif)

This ones a little hard to describe, but in the GIF above, I opened the inserter and then used my keyboards arrow keys to navigate between blocks.

I expected that using the arrow key would move the focus between the options in the inserter — and it does, but it then also moves focus to the existing block above the inserter. This breaks keyboard navigation for adding new blocks.

**Comment by youknowriad** [comment]
closed by #2706
