### ISSUE TITLE
Replace the WordPress logo top left of editor to something more intuitive or add filter to allow a developer to amend it

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#27289]
**Is your feature request related to a problem? Please describe.**
The WordPress logo top left is used to navigate back to the WordPress dashboard from the editor, in my opinion this isn't intuitive to a user to know you need to click this to get back to the dashboard.

**Describe the solution you'd like**
Either replacement of the logo to some form of back to dashboard button or a filter to enable developers to amend this as needed.

**Comment by talldan** [comment]
@ninetyninew There's some docs here on how to do this:
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/slotfills/main-dashboard-button.md

It looks like they're missing from the block editor handbook, will get them published as soon as possible.
