### ISSUE TITLE
Adding image align left/right then adding paragraph -bug-

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2729]
I do think this issue has been added here but I am not able to find it right now.

Add an image align it left or right. Then add a paragraph. It might look something like this:

![screen shot 2017-09-14 at 00 49 57](https://user-images.githubusercontent.com/5323259/30404399-caadcdb0-98e6-11e7-897c-8e06aa6620bf.png)

Add another paragraph and it too might go below the image similar to the first paragraph block.

Btw
I would suggest to begin working on the column feature that is planned for later sometime... As we need a process to easily create 2-3 column layouts.

**Comment by fisicx** [comment]
I'm having exactly the same problem. Pre-gutenburg you used to be able to float images left/right and have the content wrap around the image. This could be mixed content as well: headers, paragraphs and lists.

**Comment by karmatosed** [comment]
As you are floating content this actually sort of is what it would do. I agree that columns fixes this, but for now I think we need to close this issue as the solution is already planned.

**Comment by paaljoachim** [comment]
That is good to hear Tammie!

**Comment by fisicx** [comment]
Columns won't fix the issue. The content should wrap around the image - that's how floats work. If you have columns the content won't wrap.

**Comment by paaljoachim** [comment]
Yeah we do also need a good wrap along with the columns.

**Comment by fisicx** [comment]
And it's not just a single block that needs to wrap.

Imagine a post with a paragraph, H2, paragraph and list with a tall image floated right. All the content needs to wrap around the image. You don't want the H2 to clear the float and display below the image.
