### ISSUE TITLE
Inaccurate error message when registering a block.

### ISSUE THREAD

**Issue by georgestephanis** [WordPress/gutenberg#2730]
## Issue Overview
Inaccurate error message when registering a block.

https://github.com/WordPress/gutenberg/blob/7a05235e38efbcfcf5421f393f93ab4dd07873fc/lib/class-wp-block-type-registry.php#L65-L70

If I were to `register_block_type( 'mynamespace/my_block_type', ...` it kicks an error saying

> Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type

even though the conditional that failed is a regex match against `/^[a-z0-9-]+\/[a-z0-9-]+$/` -- so the error message should be more broad, as there are a number of other potential errors that could trigger that message.

**Comment by youknowriad** [comment]
The error message has been changed. It says `Block names must contain a namespace prefix, include only lowercase alphanumeric characters or dashes, and start with a letter. Example: my-plugin/my-custom-block`

I think this addresses this issue.
