### ISSUE TITLE
Allow making text flushed left or justified

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#27300]
Justified text was removed from the WordPress text alignment options in [version 4.7](https://href.li/?https://make.wordpress.org/core/2016/10/28/editor-changes-in-4-7/) due to concerns with readability. In building the block editor, we didn’t add this back, mostly because the reason for removing it in the first place remained valid, but also because adjusting the alignment of multiple paragraphs at once did not exist at that time. It was added to WordPress.com as an extra option, but the experience of applying it is bad, for the reasons you’ve outlined.

Legibility problems aside, there are cases where people need justified text; it could be due to a newspaper styleguide, or just a request from a teacher. In both those cases, justified text should arguably be a global toggle, a change to the default text alignment, so it applies to every post and page there ever was, as opposed being a property you apply to one paragraph at a time, every time you write.

A potential approach we can take is to add that feature in the “Global Styles” sidebar.

<img width="356" alt="screenshot-2020-11-26-at-09 56 19-1" src="https://user-images.githubusercontent.com/583546/100356048-01483580-2ff3-11eb-95a0-72430fb6bcd2.png">

**Comment by jorgefilipecosta** [comment]
@jasmussen, @nosolosw, Is this something we need for v1 or it is something we can ship after v1?

**Comment by nosolosw** [comment]
I don't have a strong opinion, although would think it doesn't, no. FWIW, it's already listed in the "Backlog" section of the tracking issue https://github.com/WordPress/gutenberg/issues/20331 (did it this morning while updating the second iteration to reflect our current focuses).

**Comment by aleone89** [comment]
Many thanks for pulling this together @nosolosw :) and having this in global styles makes sense - mainly because of the reasons stated and because, when this is requested, CSS is employed to make everything Justified throughout. 

Just my additional two-cents here - instead of having "Left Aligned" as the wording, I would consider replacing this with something like "Default" as to show that the default would be what is set, when content is created in pages/posts. What do you think? I hope that is useful :)

**Comment by jasmussen** [comment]
> Just my additional two-cents here - instead of having "Left Aligned" as the wording, I would consider replacing this with something like "Default" as to show that the default would be what is set, when content is created in pages/posts. What do you think? I hope that is useful :)

Thanks for sharing. 

It reminds me that we have to consider countries that default to writing right to left. The question then becomes whether we show all three options, left aligned, right aligned, and justified, or whether we simply show left aligned and justified for LTR languages and right aligned and justified for RTL languages.

**Comment by aleone89** [comment]
> It reminds me that we have to consider countries that default to writing right to left. The question then becomes whether we show all three options, left aligned, right aligned, and justified, or whether we simply show left aligned and justified for LTR languages and right aligned and justified for RTL languages.

RTL is usually set when a language is set via wp-admin > Settings > Language. This is also a universal setting, much like global styles.

**Comment by jasmussen** [comment]
> RTL is usually set when a language is set via wp-admin > Settings > Language. This is also a universal setting, much like global styles.

Absolutely. But we can't show a "Left aligned" icon and label when someone has that setting enabled, can we?

**Comment by aristath** [comment]
> The question then becomes whether we show all three options, left aligned, right aligned, and justified, or whether we simply show left aligned and justified for LTR languages and right aligned and justified for RTL languages.

I'd say default/justified would be a lot better ("default" being left for LTR and right for RTL). Alternatively we'd need 4 options not 3 (there's also center so it would be left/center/right/justified) and it would probably be a little overkill. Besides, if we see that we _need_ more we can always add them as we go. But once they're in it's almost impossible to remove them, so I'd say we start with the absolute essentials and add more options if and when that becomes necessary.

**Comment by jasmussen** [comment]
Yep, great thought, start simple and add once it's clear it's necessary. So:

> I'd say default/justified would be a lot better ("default" being left for LTR and right for RTL).

Let's go with that for the first version 💯

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/48202
