### ISSUE TITLE
Allow customizing the no-results behavior of the query block

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#27302]
Came up in https://github.com/WordPress/gutenberg/issues/25790
We should allow users to customize the behavior of the query block when no results are found.

**Comment by annezazu** [comment]
Pulling from the [FSE Outreach Program's latest call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1362), wanted to mention this piece of feedback as this issue is considered: 

> when a Query block has been inserted but is empty (i.e. no post content), markup for the block is still output to the front-end: `<ul class=”wp-block-query-loop”></ul>`. This will likely also create additional white-space on the front-end, due to a top margin being applied to the `<ul>` tag.

**Comment by ntsekouras** [comment]
>when a Query block has been inserted but is empty (i.e. no post content), markup for the block is still output to the front-end: `<ul class=”wp-block-query-loop”></ul>`. This will likely also create additional white-space on the front-end, due to a top margin being applied to the `<ul>` tag.

Thanks for reporting this @annezazu! I created a small PR to fix this: https://github.com/WordPress/gutenberg/pull/29521

**Comment by ramonjd** [comment]
Here is a duplicate issue, which provide some elaboration on the challenge: https://github.com/WordPress/gutenberg/issues/36609

**Comment by annezazu** [comment]
I am going to close this out with the introduction of @carolinan no results block: https://github.com/WordPress/gutenberg/pull/38806 If I missed something, let me know. Happy to reopen.
