### ISSUE TITLE
The scroll bar of the right sidebar is appearing and dissipating when the height of a browser window between 775-787 px

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#27319]
Reported by @OlaIola here: https://github.com/WordPress/twentytwentyone/issues/891

**Describe the bug**
The scroll bar of the right sidebar is appearing and dissipating when the height of a browser window between 775-787 px

**To reproduce**
1. Go to page or post
2. Click to add block pattern
3. Resize your window to size between 775-785
4. Video: https://yadi.sk/i/Ytk0qlzyObB96g

**Comment by carolinan** [comment]
Hi
There are several related issues in the Gutenberg GitHub repository, (https://github.com/WordPress/gutenberg/issues/26936).

I am able to reproduce it with the columns blocks:

- **It only happens when the outer columns block is selected.**
- It does not matter if the column is from a block pattern or not.
- The height of the content inside the columns does not matter, it also happens if the block is empty.
- **If I delete the registration for the columns block style, the problem disappears, so this narrows it down for further testing.**
- It does not matter if the block style that is registered by the theme is used or not.
- **Deleting the CSS that is used by the registered style did not change anything**
- It does not matter if the CSS in the block style is inline or not.

Tested with:
Development version of Twenty Twenty-One
With and without Gutenberg Version 9.4.1, with and without Gutenberg master
WordPress 5.5.3, WordPress 5.6 RC 1

**Comment by talldan** [comment]
Seems to be quite easily reproducible with a very long word that doesn't wrap that's wider than the editor canvas. Increasing font size with a longer word also makes it easier:
<img width="821" alt="Screenshot 2020-11-27 at 2 39 14 pm" src="https://user-images.githubusercontent.com/677833/100418821-59983980-30be-11eb-9404-6e40e70b2681.png">

Because the font sizes are a bit bigger in Twenty Twenty One it's more noticeable there.

Seems to have been an issue in 5.5.3 as well.

**Comment by OlaIola** [comment]
WordPress 5.6.2., clear installation, the problem is still here (see video):
https://disk.yandex.ru/i/M333wgttKivy6g

**Comment by carolinan** [comment]
I am not able to reproduce this with 5.8, with and without Gutenberg 11.2.1

**Comment by carolinan** [comment]
I am not able to reproduce this in 6.3 RC1, chrome, macos.
