### ISSUE TITLE
Search block: Remove 'Button only' option. 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#27329]
**Describe the bug**
When testing the Search block, I was going through all the options and found that the button only option doesn't have any action tied to it. It doesn't do anything as it doesn't have a search term to look for. It just reloads the same page. 

See also comment https://github.com/WordPress/gutenberg/pull/24666#issuecomment-729924598

**To reproduce**
1. Add a search block
2. Select the "Button only" option
3. Save & preview
4. click on the Search button. 

**Expected behavior**
I don't think there is an expected behavior. The "Button only" option feels foreign to the search functionality, unless an additional action is tied to it. 

I can imagine for instance,  a form field to slide out on button click  for a visitor to enter a search term and on the second click it initiates the search. Describing it still feels a bit awkward, though. 

**Screenshots**
![Screen Shot 2020-11-27 at 9 36 37 AM](https://user-images.githubusercontent.com/39980/100460010-7586e580-3094-11eb-819a-d01592392469.png)
![Screen Shot 2020-11-27 at 9 36 45 AM](https://user-images.githubusercontent.com/39980/100460016-77e93f80-3094-11eb-9159-139d6f4954b2.png)

**Editor version (please complete the following information):**
- WordPress version: WordPress 5.6-RC1-49694

**Desktop (please complete the following information):**
 - OS: 19.15.7
 - Browser: Chrome
 - Version 87.0.4280.67

**Comment by scruffian** [comment]
I'd prefer to update the behaviour so that in the button only version, when the user clicks the button the search field shows.

**Comment by cguntur** [comment]
I like the option to just display the button. Showing the field when the button is clicked gives a better user experience.

**Comment by apeatling** [comment]
Left a comment here with the intention https://github.com/WordPress/gutenberg/pull/24666#issuecomment-734901436

**Comment by bph** [comment]
At this late stage in the release removal seems to be best way to handle this, to avoid more bug reports about a feature not working. Confusions are to be avoided 😋😂

**Comment by tellthemachines** [comment]
I'm removing the Backport label as we only use it for PRs, but adding this issue to the 5.6 must haves board. Agree that this late in the release, the best fix for now is to remove that option altogether. 

If anyone would like to do a PR for that, I'm happy to backport it 🙂 but if we're aiming for RC2 then it'll have to be done in the next 12 hours or so.

**Comment by apeatling** [comment]
Working on a PR.
