### ISSUE TITLE
Add an embedded block editor to the customizer - for widgets 

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#27343]
After the iterations and discussions in #26900 (Managing blocks in the Customizer), the idea exchange in the [hallway hangout](https://make.wordpress.org/core/2020/11/18/hallway-hangout-summary-managing-blocks-in-the-customizer/) on the same subject, there resulted a few paths to explore:

- [x] build [a layer](https://github.com/WordPress/gutenberg/issues/26900#issuecomment-725767437) that allows the block editor to talk to the customizer (solves #25818)
- [ ] Make it look like this:

https://user-images.githubusercontent.com/191598/105537781-6d2bdf00-5cc0-11eb-99fb-85af854c0a94.mp4

These options went unexplored:

- ~[ ] attempting to [embed a block's edit view in the preview](https://github.com/WordPress/gutenberg/issues/26900#issuecomment-729103511) and see what are the main technical issues we encounter~
- ~[ ] improving the experience of using the editor in the sidebar with [accessible resizing options](https://github.com/WordPress/gutenberg/issues/26900#issuecomment-728539175)~
- ~[ ] improve the desktop experience of using the block editor in a constrained viewport size (starting with the block toolbar #25640)~
- ~[ ] attempting [a more fluid experience](https://github.com/WordPress/gutenberg/issues/26900#issuecomment-733257656) of using the editor in the sidebar with using the customizer's drawer UI (like the one for changing themes or adding classic widgets)~

**Comment by celloexpressions** [comment]
For `attempting to embed a block's edit view in the preview`, transforming customize partials between the preview and the editor could happen at the `sidebar` (widget area) level. Clicking the edit icon transforms the customize `partial` to a frontend-embedded editor (within an iframe?). A similar icon, or navigating elsewhere, would transform the partial back to the preview with a selective refresh (using the current API that also triggers all hooks). Communication between the customize controls (top level) and preview (iframe) happens via `postMessage`.

This is a "modal" approach, but one that is inline and contextual. It keeps ample space for supplementary sidebar controls. Maybe the sidebar also allows quicker actions like reordering widgets without toggling into edit mode.

**Comment by shaunandrews** [comment]
Here's how I could see using the block editor to manage Widgets (well, Sidebars, really) within the Customizer:

https://user-images.githubusercontent.com/191598/105537781-6d2bdf00-5cc0-11eb-99fb-85af854c0a94.mp4

**Comment by noisysocks** [comment]
I think we can close this. A lot of this exists in the plugin now and we are already using https://github.com/WordPress/gutenberg/issues/24687 as an overview issue for the remaining bits and pieces.
