### ISSUE TITLE
RTL bug in gradient bar: adding new step

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27352]
**Original report by hamedmoodi**
https://core.trac.wordpress.org/ticket/49531

**Describe the bug**
When adding a gradient (to a group block) in RTL, the button for adding a new step does not show at the cursor position (as it does in LTR). It is about 200 pixels to the right of the cursor.

Animated image of effect in WordPress 5.3:

![step button does not match the cursor position](https://core.trac.wordpress.org/raw-attachment/ticket/49531/ezgif-3-84e3ca7fc1d9.gif)

**Also**, the buttons for default step points do not match LTR visually.

LTR gradient with default end points (WordPress 5.6 RC1, Gutenberg plugin not activated):
![Gradient editing in English, with start and end points matching the ends of the container](https://user-images.githubusercontent.com/17100257/100520081-9bc68700-3161-11eb-8be0-31c18784e6db.png)

RTL gradient with default end points (WordPress 5.6 RC1, Gutenberg plugin not activated):
![Gradient editing in Arabic, with start and end points that do not match the ends of the container](https://user-images.githubusercontent.com/17100257/100520116-c87a9e80-3161-11eb-9298-491b87f4e597.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 83

**Comment by mapk** [comment]
I ran into the same problem.

![rtl](https://user-images.githubusercontent.com/617986/100686966-41c9eb00-3334-11eb-918a-2a9f12b74f9d.gif)
