### ISSUE TITLE
Improving the grid feature inside the Cover block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27359]
**Is your feature request related to a problem? Please describe.**
An example. https://wordpress.org/support/

Creating a Cover block with a background blue color.
Heading block: where it says WordPress Support.
Paragraph block: "We’ve got a variety of resources to help you get the most out of WordPress."
Search block: Search documentation.

<img width="1138" alt="Screen Shot 2020-11-29 at 17 03 53" src="https://user-images.githubusercontent.com/5323259/100547024-e3820700-3264-11eb-8a5b-9b8bb4e83265.png">

Centering all three objects with the current Cover block grid feature is difficult.

This is the design I was able to create:
![Screen Shot 2020-11-29 at 17 06 09](https://user-images.githubusercontent.com/5323259/100547100-41aeea00-3265-11eb-8540-90c576c8b895.png)

All three objects are now in a center area.
If I want the Search area smaller and adjust to 50% alignment. It stops being centered aligned and becomes pushed to the left:

![Screen Shot 2020-11-29 at 17 09 09](https://user-images.githubusercontent.com/5323259/100547187-9eaaa000-3265-11eb-82be-b0fcde269932.png)

A better solution would be to use something similar to the Automattic Layout Grid plugin https://wordpress.org/plugins/layout-grid/ feature as a grid inside the Cover block.

Here is an example to having a stronger control of placing items.

![Screen Shot 2020-11-29 at 17 10 40](https://user-images.githubusercontent.com/5323259/100547240-ecbfa380-3265-11eb-9435-f1e76bdc79f6.png)

The above shows 3 grid layouts. One for the first row, one for the second and one for the third.
One idea is to click the grid icon in the Cover block toolbar and have a grid show up in the full area of the Cover block. Being able to push and pull boundaries up and down, and left and right. To create cells where one adds blocks.

Using a stronger grid feature inside the Cover block could also be a good introduction in using grids in Gutenberg.
Kinda like a test ground for a new feature.

@shaunandrews @ItsJonQ @jasmussen @mapk

**Comment by mapk** [comment]
I gave this a quick run and was able to create something really close with our current features.

![Screen Shot 2020-11-30 at 5 00 46 PM](https://user-images.githubusercontent.com/617986/100683676-b8171f00-332d-11eb-99b5-269e050fbb43.png)

While I think working in a grid to Gutenberg would be a dream come true, I believe there are issues created around this already. I'm not sure adding a grid to the Cover block is the solution, or maybe just working in a grid to the overall experience instead.

**Comment by paaljoachim** [comment]
That sounds even better Mark! Working in a grid to the overall experience would really help. 

I added the issue thinking about how to incorporate grid into Gutenberg in a more subtitle way. If the issue helps than great, if there really is no point to this issue than I can go ahead and close it.
