### ISSUE TITLE
Gutenberg Plugin V 9.3.0 - WooCommerce Admin  YTD Report Page Blank

### ISSUE THREAD

**Issue by gwensmithx** [WordPress/gutenberg#27354]
**Describe the bug**
Gutenberg plugin version 9.3.0 causes a WooCommerce Report Page (YTD) to be blank if its activated. Once deactivated the page shows.

Example of blank page: (domain here)/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts&period=year&compare=previous_year

**To reproduce**
1. Make sure Gutenberg plugin 9.3.0 is active on your site 
2. Visit this page on your site: (domain here)/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts&period=year&compare=previous_year
3. You'll see the page is blank.
4. Deactivate the gutenberg plugin and visit the page again - content will show

**Expected behavior**
I expected to be able to see the YTD report page

**Screenshots**

Screenshot with Gutenberg activated:
<img width="1614" alt="Screen Shot 2020-11-28 at 1 47 46 PM" src="https://user-images.githubusercontent.com/5779512/100525758-7dbc4f00-3180-11eb-9e68-5904a938587f.png">

Screenshot with Gutenberg deactivated:
<img width="1591" alt="Screen Shot 2020-11-28 at 1 47 10 PM" src="https://user-images.githubusercontent.com/5779512/100525778-988ec380-3180-11eb-9f89-9316ee8346a1.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? Gutenberg plugin 9.3.0

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.6
 - Browser: Chrome 86

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@gwensmithx Have you touched base with WooCommerce about this? It might be easier for one of the folks from there to debug this seeing as the error is happening within that plugin.

**Comment by samueljseay** [comment]
Hi @gwensmithx I think https://github.com/woocommerce/woocommerce-admin/issues/5728 looks like the issue you're describing here. 

I believe this issue is fixed in wc-admin 1.7.2 and there are instructions in the issue on how to work around it for now: https://github.com/woocommerce/woocommerce-admin/issues/5728#issuecomment-733226750

Please do reopen that issue and discuss there if you have further problems.

**Comment by talldan** [comment]
Thanks @samueljseay, I'll close this issue given the problem seems to no longer be present.
