### ISSUE TITLE
Image block zoom control overflowing position

### ISSUE THREAD

**Issue by Tonnie-Exelero** [WordPress/gutenberg#27364]
**Describe the bug**
When Image block zoom control popup is visible in the editor, it overflows either to the right or the left on mobile devices viewports.

**To reproduce**
1. Add an image to an image block.
2. Select the crop option.
3. Select the zoom option and ensure you see the zoom control popup.
4. Inspect the page and change viewport to mobile. 
5. Notice the overflowing of the zoom control popup to either the left or the right on different mobile devices viewports.

**Expected behavior**
The zoom control popup should be positioned proportionately at the center on all mobile viewports and fully visible.

**Screenshots**
<img width="417" alt="Screenshot 2020-11-30 at 02 51 45" src="https://user-images.githubusercontent.com/23191929/100558591-13aac380-32c0-11eb-9d23-f57d8d88989a.png">
<img width="378" alt="Screenshot 2020-11-30 at 02 52 09" src="https://user-images.githubusercontent.com/23191929/100558597-186f7780-32c0-11eb-9b49-ff40e0714403.png">

**Comment by mapk** [comment]
I tested and got the same problem on the mobile web.

![Screen Shot 2020-11-30 at 5 39 15 PM](https://user-images.githubusercontent.com/617986/100686375-0aa70a00-3333-11eb-8d44-d21d76bcf116.png)

**Comment by Tonnie-Exelero** [comment]
@mapk I can look into this issue. Is that okay?

**Comment by mapk** [comment]
Thanks @Tonnie-Exelero! You've been assigned. :)

**Comment by mtias** [comment]
This appears to be working correctly to me now.
