### ISSUE TITLE
wpautop is applied to server-side rendered block output

### ISSUE THREAD

**Issue by lamosty** [WordPress/gutenberg#2736]
While working on creating a block for the Jetpack subscription functionality, I stumbled upon an issue: if the output from the `render_callback` function contains inline JS ([like this](https://gist.github.com/lamosty/8c9b9d18e087ec0c3c24e1c8347f4dae)), `wpautop` will add paragraphs to the JS code so it won't work:

![screen shot 2017-09-15 at 14 56 24](https://user-images.githubusercontent.com/4988512/30504890-1814f958-9a26-11e7-8833-3746e3c3f643.png)

If I return early from `wpautop`, no `<p>`s are added.

#gutenbug

**Comment by georgestephanis** [comment]
Related: #1244

**Comment by aduth** [comment]
Additional context / proposed solutions at https://github.com/WordPress/gutenberg/pull/2708#issuecomment-329632867
