### ISSUE TITLE
Style Modifyer to go with Styles

### ISSUE THREAD

**Issue by nickfmc** [WordPress/gutenberg#27384]
Currently we have the block Styles setting which is just applying a class. For good reason to not have any conflicting styles we only allow one Style per block to be selected.  It would be really nice if there was another group option we could add for Style Modifiers, that allowed users to select multiple options per block.

Take to column block for instance, I usually register a block style for a "No gutter" version then I also have one for "break early" that goes to stacked columns earlier than the default.  Now there is no way for my client to click No gutter and Break Early so I have to manually add classes to make it work.

If there was a "Style" that only allows either or and and then an additional option for "Style Modifiers" a lot more could be done out of the box with the current blocks making them a lot less limiting.

**Comment by mapk** [comment]
Related: https://github.com/WordPress/gutenberg/issues/19367

I'd like to just open this up to adding multiple classes.

**Comment by nickfmc** [comment]
perhaps, however for the client using a theme the styles are so easy. having a style modifier would allow the developer to only have options available on a per block basis and gives you a user friendly name to use associated with your class. Across a site just using classes it's not very end user friendly.

**Comment by mapk** [comment]
In that case, should the developer just provide "Style variations" for the client if they want to restrict the ways in which the block is displayed?

I think the Advanced section should allow more advanced configuring. Like adding classes for CSS that maybe you wrote yourself.

**Comment by nickfmc** [comment]
right, I'm just thinking a lot of developer workflow is to create a site that is going to be built out by an end user.  style variation only allow one per block to be selected, taking the Column block for instance I would register the following "style modifies" attached to the Column block type

- No Gutter
- Stack Early
- Reverse Order on Mobile

My Client may need any combination of these for what they are doing.  currently giving them a page full of class names and which blocks they work on is a messy process.  With a Style modifier even simple blocks would become a lot more flexible for developers to provide a nice user experience for their clients.

**Comment by mtias** [comment]
Closing as overlapping with #14598.
