### ISSUE TITLE
getEntityRecords comes back with null

### ISSUE THREAD

**Issue by mikebhart** [WordPress/gutenberg#27389]
Hi there

Im having problems with getEntityRecords. If I run in the chrome console It comes back with null first time you use it, then the second time it comes back with data.  This trying first time way of getting the data doesn't work in my project. 

All I want to do is run something like this 

wp.data.select( "core" ).getEntityRecords( 'postType', 'research',  { 'location' : 26 });

and get the results back first time.

Pleas help.

**Comment by talldan** [comment]
@mikebhart The selector is asynchronous and it should be making an HTTP request in the background to fetch the data.

The `null` in this case represents that the data has not yet been received. A robust way to check whether a request is in flight is to use the `isResolving` and `hasFinishedResolution` selectors:

```js
wp.data.select( 'core' ).isResolving( 'getEntityRecords',  [ 'postType', 'research', { 'location' : 26 } ] );
wp.data.select( 'core' ).hasFinishedResolution( 'getEntityRecords',  [ 'postType', 'research', { 'location' : 26 } ] );
```
