### ISSUE TITLE
Do multiple instances of the same block share the attributes?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27396]
If I were to add my custom block with its own attributes and then add the same block again, will the latter start with the former's custom attributes or the default attribute values?

**Comment by aristath** [comment]
Every time a block is added to the editor, it uses the defaults.
You can test this quite easily: Add a paragraph block, and change its properties (background-color, text-color etc). Now add a 2nd paragraph and you'll see it does not use the props you used on its previous instance. It starts fresh.
