### ISSUE TITLE
Performance Issues Experienced

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#2739]
## Issue Overview
Am suffering from terrible performance issues when using Gutenberg to edit a specific post. I have had to resort to the old editor.

## Steps to Reproduce (for bugs)
It's hard to nail down but my post had a lengthy amount of text and a few full width images. I added one 3-image gallery and all was fine. It wasn't until I added another 3-image gallery that editing became an issue. This included trying to move one of the blocks around, for which they was a large delay between requesting this and it occurring.

I am happy to share the post for anyone who would like to look into this further.

**Comment by karmatosed** [comment]
Hey there, that sounds like not a lot of fun @dartiss. What set up are you using to write the post? For example, what is your browser and platform? Sharing the post would also be helpful, thanks for that offer.

**Comment by dartiss** [comment]
Hi @karmatosed. Yes, happy to provide - just thought I'd scout out first whether I'm just repeating something from elsewhere ;)

So, I'm running a self-install on Pressable. It's in Safari, MacOS (all latest versions of both).

I was going to provide a link to the post, but that will display the front-end version, which probably won't help you much. What I could do is cut/paste the post field content into a private pastebin and share that with you via Slack, if you'd prefer? Hopefully that would then recreate the issue on a test site.

**Comment by karmatosed** [comment]
Sure, if you can do a private pastebin that would be great.

**Comment by karmatosed** [comment]
@dartiss do you have any update on this?

**Comment by dartiss** [comment]
Ah, sorry Tammy, forgot about this 😬

I ended up losing the content in my attempt to try and get to the bottom of the issue. Basically, I was wondering if it was purely my post content rather than Gutenberg itself - transferring the post over to the standard editor (and removing the Gutenberg markup to ensure it didn't interfere at all) showed that it was still slow, just not as bad. I think, though, it was the amount of gallery and image data in my post causing the slowdown but the performance in Gutenberg was just that little bit slower (particularly when it came to trying to move blocks which were pretty slow to the point of being near-unresponsive).

I'm happy to try and recreate on another post, if you wish, or feel free to close this if you feel it's not going anywhere.

One question - if the Gutenberg markup is left in a post does it have any impact on the standard editor or, even, front end?

**Comment by mtias** [comment]
@dartiss we had some important performance issues around revisions that could have been the culprit here—it only affected the Gutenberg editor. The markup of the post was not relevant, it was more about having multiple revisions.

I'll close this as it was fixed, but please, re-open if you run into it again.
