### ISSUE TITLE
Documentation: Improving the intro page of the Block Editor Handbook

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27400]
As one enters https://developer.wordpress.org/block-editor/ one sees the following:

![Screen Shot 2020-12-01 at 15 19 32](https://user-images.githubusercontent.com/5323259/100753112-ab580100-33e9-11eb-8404-48177e55352b.png)

Instead of a moving animated gif, it would be helpful to just show Gutenberg screens where different areas are marked similar to these screens. Each image having short text with links to documentation pages that address these areas.

![Sections-in-the-Gutenberg-screen](https://user-images.githubusercontent.com/5323259/100754814-c9266580-33eb-11eb-93fe-76e2703b01d9.jpg)

![Gutenberg-blocks](https://user-images.githubusercontent.com/5323259/100755533-9335b100-33ec-11eb-9afc-7791778b592a.jpg)

![Patterns-Gutenberg](https://user-images.githubusercontent.com/5323259/100755860-eb6cb300-33ec-11eb-835f-2dd136ac7b67.jpg)

![Options-Gutenberg](https://user-images.githubusercontent.com/5323259/100756027-16ef9d80-33ed-11eb-902c-2a47b7a36bf4.jpg)

Having a kind of "road map" or "turist map" showing locations of Gutenberg areas and links to where these areas are addressed in the documentation, can be a good start location for a user who enters the Block Editor Documentation looking for some specific information. Instead of having to search one can look at the initial landing page get the "road map" to the correct documentation page and click the link to get to the information.

**EDIT:** As Marcus mentioned further below. The above example would be better to add to another page. As in not having it as part of the landing page. I do agree on this. In my next comment I share various web sites and how they handle their landing pages.

**Comment by paaljoachim** [comment]
Here are some intro pages to other web sites. We can gain some additional inspiration from on how to form the intro page.


Example from other documentation sites:
https://www.gatsbyjs.com/docs/

![Gatsby-docs-intro](https://user-images.githubusercontent.com/5323259/100759729-3ee10000-33f1-11eb-9ac5-c382b0a21f1f.jpg)



https://doc.rust-lang.org/stable/rust-by-example/index.html

![Rust-doc-intro](https://user-images.githubusercontent.com/5323259/100759720-3c7ea600-33f1-11eb-9b0b-8e61c7e2d688.jpg)



https://docs.github.com/en

![Github-docs-intro](https://user-images.githubusercontent.com/5323259/100759709-3983b580-33f1-11eb-9bcc-51e06c59cf29.jpg)



https://get.foundation/sites/docs/

![Zurb-docs-intro](https://user-images.githubusercontent.com/5323259/100759697-3688c500-33f1-11eb-99e4-3790fdb53249.jpg)

**Comment by mkaz** [comment]
I do like the idea of better introduction to the documentation for Gutenberg, and like the idea of highlighting sections of the editor to take people to that documentation. However, I'm not sure the first page is right for it.

The main segmentation that I've seen for docs is:

1. User or author centric docs "How do I use the editor to create blog posts?"

2. Developer centric docs, "How do I create a plugin to extend the Block Editor?"

3. Contributor centric docs, "How do I contribute back to the Block Editor?"

There is some overlap between (2) & (3) because the Block Editor is built using the same components and pieces used to extend. So I think the mapping exercise showing users what pieces are what, would fall under these segments.

**Comment by paaljoachim** [comment]
I was kinda wondering in the back of my mind if highlighting sections would be natural to have as part of the landing page or if it would be better to include in another page.

For the landing page/introduction page I think we need to include various informative links perhaps like an index of a book to highlight pages in the documentation. So users can quickly click the links and move onward to the information they need.

**Comment by paaljoachim** [comment]
Hi Justin. It looks like a good beginning.

**Comment by paaljoachim** [comment]
There are a few limits to what we can do as the WordPress theme in use has CSS that is a bit messy. Let's aim for what we want to go with and then figure out how close we can get it.

The important part is going through figuring out which links to add to create a good overview of the handbook.

**Comment by paaljoachim** [comment]
As we now have an adjustment in place for the intro page for the Block Editor here: https://developer.wordpress.org/block-editor/ I will go ahead and close this issue. It can of course be used as inspiration for a future iteration. But for now it has served it's purpose.
