### ISSUE TITLE
Documentation: Improving the design of the Handbooks documentation.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27403]
I am looking into improving the design used for the Handbooks. 
Here I am focusing in the Block Editor handbook. It should also be brought over to other Handbooks so that we have a common design style between the various Handbooks.

![Screen Shot 2020-12-01 at 16 05 57](https://user-images.githubusercontent.com/5323259/100758019-5323fd80-33ef-11eb-92b7-8ade224beba8.png)

--------------

Example from other documentation sites:

### Gatsby
https://www.gatsbyjs.com/docs/

![Gatsby-docs-intro](https://user-images.githubusercontent.com/5323259/100759729-3ee10000-33f1-11eb-9ac5-c382b0a21f1f.jpg)

### Rust
https://doc.rust-lang.org/stable/rust-by-example/index.html

![Rust-doc-intro](https://user-images.githubusercontent.com/5323259/100759720-3c7ea600-33f1-11eb-9b0b-8e61c7e2d688.jpg)

### Github
https://docs.github.com/en

![Github-docs-intro](https://user-images.githubusercontent.com/5323259/100759709-3983b580-33f1-11eb-9bcc-51e06c59cf29.jpg)

### Zurb Foundation
https://get.foundation/sites/docs/

![Zurb-docs-intro](https://user-images.githubusercontent.com/5323259/100759697-3688c500-33f1-11eb-99e4-3790fdb53249.jpg)

**Comment by mtias** [comment]
For improving the handbook design in general, the discussion should probably be moved to another repository not in the gutenberg one

**Comment by mapk** [comment]
Yea, I think this would be something discussed in the #meta channel on Making WP Slack.

**Comment by paaljoachim** [comment]
I will followup and create a trac issue. Then close this Github issue.

**Comment by paaljoachim** [comment]
Well I found this trac ticket: https://meta.trac.wordpress.org/ticket/5353
In regards to increasing the font size.
That is atleast a good beginning. After the font size has been increased I will again look at the design.
I will close this issue
