### ISSUE TITLE
Text color toolbar button doesn't open color picker

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#27412]
**Describe the bug**
Color toolbar behaves strangely when used without a text range selected. It seems to work fine when a text range is selected.

**To reproduce**
1. Select a text color from the paragraph toolbar _without_ a text range selected.
2. Click on the text color button that appears.
3. See that the color dropdown doesn't open.
4. Continue typing to see that the dropdown only opens then.

**Expected behavior**
Color dropdown should open on button press.

**Screenshots**
![text-color-bug](https://user-images.githubusercontent.com/5129775/100794359-b2c3de00-33da-11eb-85cb-e017bc5e46d7.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? master (fbb000fcb4)

**Comment by rafaelgalani** [comment]
@ajlende I gave it a try... Is this the correct behavior?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/18705930/101424177-5892b380-38d9-11eb-8f3d-d0ded91d4b61.gif)

**Comment by ajlende** [comment]
I think it's acceptable for the white text to remain white since it isn't range selected. Any new text typed should be the new color, and that's what this is doing. 👍

Do you have a PR open that I can review to get your fix reviewed and merged?

**Comment by rafaelgalani** [comment]
Sure! Checks are running for it, here it is: https://github.com/WordPress/gutenberg/pull/27596. Sorry for taking so long to reply.
