### ISSUE TITLE
Steps to move from React

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2741]
There is a discussion thread here: https://github.com/WordPress/gutenberg/issues/2733. Let's now move this into practical steps that are needed. What do we need to do to progress forward? Try and keep the discussion to practical examples and progress. A good idea would be to get a task list to follow.

**Comment by dmccan** [comment]
@karmatosed, I would suggest:

1. Open a repository/project for a sandbox.

2. Commit a design document that serves as a reference with requirements for a partial implementation. 

3. Have the team create the reference project using Angular, Ember, Preact, and Vue.  

4.  Discuss the experience and review the code to see what best meets the WordPress goal to democratize publishing.

**Comment by montogeek** [comment]
Facebook just announced that they will relicense React under MIT https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

Maybe this change will make a difference in this decision?

**Comment by achun** [comment]
Hi everyone.
I recommend a new javascript template engine for the WP, the [PowJS](https://github.com/powjs/powjs). 

Its introduction is written in Chinese. Here are a few important features, I hope this is what PW need.

1. Use native javascript syntax
2. Simple 11 instructions to implement branch and loop statements
3. Can be compiled and rendered in the browser
4. Prototype can be extended

PowJS is just a template engine that does not involve application logic.
If PW is interested, I can write some simple presentations for PW.

In addition, I have been trying to improve my English ability :)

**Comment by karmatosed** [comment]
Closing as not an actionable issue right now.
