### ISSUE TITLE
[Project Automation] Add hints for PRs to suggest labels

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27415]
Use hints from a pull request to suggest labels, for the purpose of improving the accuracy of tools which depend on pull request labels (changelog generator):
- If a pull request title includes "Fix", suggest to add "[Type] Bug" label.
- If a pull request includes only edits to Markdown files (or files within `docs`), suggest to add "[Type] Documentation"

**Comment by annezazu** [comment]
Pulling in a comment from @talldan: 

> Automatically add the appropriate `[Type]` label to an issue based upon the template selected when the issue is created. Labelling PRs based on the branch prefix might also be an option: https://github.com/TimonVS/pr-labeler-action

**Comment by annezazu** [comment]
Pulling in yet another comment from @talldan: 

> Assign package labels to PRs automatically. This existing action might be useful in implementation: https://github.com/banyan/auto-label

**Comment by talldan** [comment]
Another nice automation would be adding the labels from a linked issue to a pull request. 

Would probably want to avoid a subset (maybe all the ones beginning with 'Needs' or '[Status]', which generally indicate a status on the issue but might not be relevant to the PR).

**Comment by gziolo** [comment]
I wouldn't mind if labels were automatically added if there was no label provided when creating PR (some users should see this option were sending PR), a bot might wait a couple of minutes if possible. To ensure those labels aren't misleading, we could add another label giving a clear signal that they need to be confirmed during triage.
