### ISSUE TITLE
[Automated Testing] Automate the creation of any artifacts

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27419]
Automate the creation of any artifacts, or remove them from the repository (`npm run docs:build`). There should ideally be no "Build artifacts" Travis job.

**Comment by gziolo** [comment]
We don't use Travis anymore, but to to the point. In fact we could create a bot that tries to fix some common issues reported:
- `npm run docs:build`
- `npm run lint-js -- --fix`
- `npm run format:js`

Those 3 commands when missed locally could improve the experience.
