### ISSUE TITLE
Remove Border Radius for Blocks

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#27410]
When a block is selected (or, in a few other scenarios) a blue outline is displayed:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/191598/100769160-aaaf7280-33c9-11eb-836f-580fdcbfb3cb.png">

This outline displays with a 2px border radius. I assume this is to visually connect the block outline to the block toolbar. Or perhaps its some sort of "brand" element for the block editor.

However, it's slightly confusing as the _actual_ shape of most blocks is a rectangle; In the case of the Button block — which supports the border radius setting — the outline mis-represents the shape of the block:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/191598/100787932-5f558e00-33e2-11eb-8936-2586b3a590a0.png">

The width of the outline affects the visual perception of the rounded corners, often causing them to appear to be _more rounded_ then the toolbar. Some outlines are shown inside (`inset`) and some are shown outside the shape, which adds to the visual difference and creates the appearance of different border radii across the editor's UI.

The current outline requires some extra CSS to work, using box-shadow (rather than `border`, which affects the layout; or `outline`, which doesn't support border-radius) and an `::after` pseudo-element. There are considerations for the outline width issue mentioned above, but we still end up with mis-aligned outlines:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/191598/100770976-dcc1d400-33cb-11eb-9630-6bd3b39fdd0b.png">

If we can agree to remove the default 2px border-radius and show the _true_ shape of blocks we can...

- ...simplify the CSS and start using `outline`, which also allows us to use `dotted` and `dashed` border styles for things like hover, general block highlighting, and template part highlighting — all without affecting the layout of the document.
- ...support a border radius setting for more blocks (like Cover, or Group) and not confuse people with a competing UI radius.
- ...better represent background colors and images, especially when combined with a border radius setting.

**Comment by jameskoster** [comment]
Using `outline` also means we have additional flexibility via `outline-offset` which may be useful for some states.

**Comment by jasmussen** [comment]
I'm not sure about this one. I don't see that many upsides to changing this, but I see a few downsides.

In building this outline, I tried doing it without a pseudo element, but failed given the numerous contexts. I'd welcome a successful refactor to remove the pseudo element, but `outline` or `box-shadow` aren't the blockers there. 

While the outline enables dotted and dashed lines, those styles haven't been succesful in my mockups, serving instead to [add noise](https://cloudup.com/iWXlqbaz2K1). The `box-shadow` on the other hand, gives us some opportunities that outline does not, in addition to letting us keep the border radius: 

- it allows subpixel rendering which enables the use of the same stroke width as icons have
- it is able to be both inset and outset in a stack, enabling it to be painted centered on the block footprint

Most importantly, by sharing the 2px border radius, it shares DNA with every focus style, with buttons, checkboxes, inputs, and the block toolbar. When the UI was reduced to just a white box with a border, every detail matters:

![Untitled-1](https://user-images.githubusercontent.com/1204802/100881357-1f5bdd00-34ae-11eb-80d7-e9e713e25d26.png)

If the select/focus style is misaligned, it's a bug somewhere. It's meant to be exactly as big as the footprint of the block, so if something misaligns, there's either a rogue padding in a container, or there's some CSS moving the style that shouldn't be there.

The best argument is that the select/focus style border radius potentially competes with the border radius visual control. This is valid. But before removing what I'd argue is an important detail, it seems worth trying to fade it out while you're customizing things in the sidebar. This shouldn't be any different from typing, where we fade out everything as well.
