### ISSUE TITLE
[Project Automation] Automatically close issues that do not follow the issue template

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27428]
Automatically close bug report issues that do not follow the issue template. Rationale: Poorly written bug reports are a big time sink, but most humans are too kind to do this :)

**Comment by noisysocks** [comment]
Perhaps I'm unnecessarily cruel but I think this is a really good idea. In an open source project, onus should be on the reporter to do a little bit of upfront investigative work.
