### ISSUE TITLE
[Project Automation] Automate Applying "Good First Review" label 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27421]
Apply "Good First Review" label based upon some heuristic (Only touches `.md` files? Few lines of change? Only changes inline code comments? Changes occur in "less risky" packages?)

**Comment by gziolo** [comment]
Labeling is tricky as you can have one line change in documentation that is very technical and only a handful can correctly review it. It might be helpful to create a few labels that classify PRs based on automated rules that are used by a human to take the final decision. Another idea I had recently is to introduce `Needs triage` label that would indicate that such issue should be checked again.

Assuming the triage process starts with issues without labels, you could assign labels using automation plus an additional label that indicates that they need be validated.
