### ISSUE TITLE
[Project Automation] Slack summary post of "needs review" PRs

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27427]
A 'Needs Review' daily (or weekly?) slack post that mentions pull requests that meet a specific criteria:

- a certain number of days have passed since last commit OR has the high priority label
- doesn't have the 'In Progress' label
- Title isn't prefixed with 'WIP'.

Perhaps can align the timing of the bot with core-editor meeting timing.

**Comment by gziolo** [comment]
> Title isn't prefixed with 'WIP'.

There is an option to revert PRs to draft that can be used for filtering. Should we promote it instead?
