### ISSUE TITLE
Image caption filter?

### ISSUE THREAD

**Issue by captainbri** [WordPress/gutenberg#27443]
Is there a filter to change where the field the image caption comes from when inserting and image into the post body?

For example, we may want to use the description field instead of the caption field, and add additional data from a field like an image credit?

**Comment by talldan** [comment]
@captainbri There's no specific filter for image captions, but there are filters available for blocks generally:
https://developer.wordpress.org/block-editor/developers/filters/block-filters/

This is a very specific use case so I haven't tested anything out, but `blocks.getBlockAttributes` might be one to investigate, or `editor.BlockEdit` could also be used to add an additional feature to the image block for setting a caption, like a button in the sidebar that sets the value.
