### ISSUE TITLE
In ver. 5.6, the "HTML block" style has disappeared.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#27455]
Thank you for your continuous development.

I'm sorry if an issue has already been raised.
While testing version 5.6RC2, I found something like a bug, so I'll report it.

Styles such as borders that were previously applied to "HTML blocks" have disappeared.

The display in 5.5 is as follows.

<img width="539" alt="html_block_on_wp55" src="https://user-images.githubusercontent.com/31400297/100976542-07a25880-3583-11eb-9f54-ce95cadcc104.png">

However, the display in 5.6 is as follows.

<img width="556" alt="html_block_on_wp56" src="https://user-images.githubusercontent.com/31400297/100976546-096c1c00-3583-11eb-98bb-ed17d546779c.png">

Therefore, it is difficult to understand "which block is being edited".

I personally reported it because it looked like a bug, but is this a new specification?

## My testing environment:

OS: macOS Catalina 10.15.7
Browser: Chrome
WordPress: 5.6 RC2
Language: Japanese, English

**Comment by ddryo** [comment]
Since `max-height` is no longer specified, if you write long HTML, it will squeeze the body area.

**Comment by tellthemachines** [comment]
I can reproduce this and it is, in fact, a bug. Thanks for reporting!

**Comment by wolffe** [comment]
Same here - 
![html-block-5 5 3](https://user-images.githubusercontent.com/910240/101667202-f0fa7680-3a46-11eb-9289-4451186e6e2f.PNG)
![html-block-5 6](https://user-images.githubusercontent.com/910240/101667204-f1930d00-3a46-11eb-8d7d-f8f76cee8b9c.PNG)
