### ISSUE TITLE
Gutenberg v9.5.0 not working with WP Multisite Network

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#27457]
After updating to Gutenberg plugin to the latest version 9.5.0, I am unable to work with the "Site Editor'. It just gets stuck and keep showing 'loading'.

**To reproduce**
1. Go to 'Site Editor'
2. See error

**Expected behavior**
It was working earlier, and I've just double confirmed it by re-installing the Gutenberg plugin v9.4.0' and it still works fine with that.

**Screenshots**

![Image 2020-12-03 at 12 24 52 PM](https://user-images.githubusercontent.com/5817882/100998540-7977a380-357d-11eb-85a0-cc6b3c2aaa80.jpg)

**Editor version (please complete the following information):**
- WordPress version: [5.5.3]
- Gutenberg plugin version that has issue is 9.5.0

**Desktop (please complete the following information):**
 - Tested on MacOS and Windows both
 - Browser: Chrome v87.0.4280.67

**Comment by youknowriad** [comment]
cc @Addison-Stavlo @noahshrader @david-szabo97 @aristath in case you have an idea here.

**Comment by munirkamal** [comment]
Just updated the screenshot (it was a wrong one earlier).

**Comment by david-szabo97** [comment]
I think this might be relevant to the meta -> taxonomy transition. We moved some data from post metas to taxonomy and it isn't backward compatible as far as I know.

**Comment by aristath** [comment]
> We moved some data from post metas to taxonomy and it isn't backward compatible as far as I know.

Yeah, it's not backwards-compatible. A migration was not deemed necessary because of the experimental nature of FSE themes. On a fresh install it _should_ be OK though

**Comment by Addison-Stavlo** [comment]
We have noticed this as well, it doesn't seem to be related to the taxonomy change (in our case at least).  @jeyip has started investigating.

**Comment by jeyip** [comment]
@Addison-Stavlo Thanks for the ping Addie!

@munirkamal @aristath @youknowriad We were made aware of a bug with fresh installs on the horizon flow a few days ago. I've been debugging since then, leaving updates about my progress here https://github.com/Automattic/wp-calypso/issues/47931

**Comment by aristath** [comment]
I'm unable to replicate this issue... I'm testing using the master branch of Gutenberg, along with this theme: https://github.com/aristath/q on WordPress 5.6-RC4
I tested on the main site as well as a new site in local multisite installation.
If this only occurs with a specific theme, which theme is that? If it's not a theme issue, does it only happen with the stable versions of of WP/Gutenberg? If that is the case then maybe this has already been fixed in the dev versions?

**Comment by munirkamal** [comment]
Hey @aristath 

I tested it with Stable latest WP + Gutenberg Plugin v9.5.0 + Q theme on a Multisite Network (not fresh).

**Comment by aristath** [comment]
@munirkamal I'm still unable to replicate using stable versions for everything (WP:5.6, Gutenberg:9.5.2, Q:0.6).
Please note I don't have an pre-existing multisite installation so I'm only able to test on a fresh install

**Comment by mtias** [comment]
What's the status here?

**Comment by aristath** [comment]
It's been a long time and a lot of things have changed since then, I don't believe this is relevant any longer

**Comment by mtias** [comment]
I'll close then, but please feel free to open if there are any lingering issues.
