### ISSUE TITLE
How to get internal link suggestions to a custom taxonomy?

### ISSUE THREAD

**Issue by tomkeysers** [WordPress/gutenberg#27460]
Right now I'm only able to get link suggestions in the editor to posts, pages and cpt's (if the cpt is open to the rest api) but I can't find a way to get link suggestions to custom taxonomies of a cpt.

I'm building a product site in which the Product Categories are a custom taxonomy of the custom post type Product, and I use the archive pages of the custom taxonomies as the overview pages of the sorted products. Therefore it would be great to let the content writers be able to link to those categories with the means of a handy suggestion when writing blog posts, without having to look for the page and copy the url (being complexed further by a multilingual setup).

Is there a way to do this or should this be a feature request?

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I'm not sure if there's a way to do this with custom code but this feature is not built into Gutenberg yet, has reported and is being tracked at https://github.com/WordPress/gutenberg/issues/22288
