### ISSUE TITLE
Site Editing: Add a "Template" tab in the Inspector when editing a template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27470]
When editing a template, it would be useful to have a "Template" tab in the inspector. For now this can just display the template details. In the future it can be a home for revisions (like posts), and other template settings / options.

Here's an exciting screenshot:

<img width="263" alt="Screenshot 2020-12-03 at 14 21 37" src="https://user-images.githubusercontent.com/846565/101036307-e5a0da00-3572-11eb-9fab-977618fdb22d.png">

**Comment by paaljoachim** [comment]
A question comes up....
Do we want to have three tabs?
Post/Page - Block - Template

Clicking the Template tab would bring focus to template parts in the post or page one is in. (As a switcher.)

**Comment by jameskoster** [comment]
One problem with that suggestion – imo – is that it doesn't create _enough_ separation between the document (post/page) and template. If template details are accessible through a tab in the Inspector, I worry that users would perceive the template to be _a part of the document_ somehow, rather than a separate entity in its own right.

I appreciate the desire to reduce friction, but sometimes I think a little friction can be good. It makes the user pause momentarily so that they can understand the scope of the exercise.

> Yes there is an edit template today, but it is not obvious how to bring focus back to the post content editing.

We should perhaps discuss this in isolation, but in #27848 a "← Return to post" link is suggested when you move from editing a post to a template:

<img width="783" alt="Screenshot 2021-02-01 at 15 29 52" src="https://user-images.githubusercontent.com/846565/106479551-59436280-64a2-11eb-9e8f-5125edf0eec1.png">

Keynote employs a similar pattern with their "Done" button that becomes visible when you edit a master slide. It works quite well:

<img width="760" alt="Screenshot 2021-02-01 at 15 30 37" src="https://user-images.githubusercontent.com/846565/106479675-7d9f3f00-64a2-11eb-88a7-050b0b40e1c4.png">

**Comment by paaljoachim** [comment]
Yeah. Let's keep it to two tabs.

In template mode. The tabs:
Template - Block

The template panel could show some other options or additional options in the Status & visibility. As right now it becomes too similar to the same panel in the post editor screen. Thinking of which options would be natural to have more visible.
