### ISSUE TITLE
Integrate the concepts of block styles and Global Styles/theme.json

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#27476]
Currently, the block styles are just a class that can apply any style using CSS.
Global Styles/theme.json allows users and themes to apply styles to blocks and globally.

There is no connection between the two systems.

@mtias suggested the two systems should be connected. For example, allow the user to register the style changes made as a block style variation. Allow themes to create block styles using theme.json etc.
In fact, the typographic presets shown on https://github.com/WordPress/gutenberg/issues/27331 could be just a block style that is only changing typographic attributes.
We should not implement any additional presets before this exploration is done.

Previously in a conversation with @youknowriad, it also seemed that block styles could be the semantic nesting element we need. E.g., If we allow controlling the styles of blocks nested inside a specific block style. Controlling the style of paragraphs inside a template area would be a matter of controlling the designs of paragraphs inside a specific block style and applying that style to a template part.

We are not totally sure about what mixing the two concepts will bring but it seems something we should explore right after having the design ready https://github.com/WordPress/gutenberg/issues/27473.

**Comment by youknowriad** [comment]
While not solved fully, we're in a better position today. These two things share the same UI, same "style" object (to a certain level because of backwards compatibility), we can define block style variation using theme.json config.

I think what's left is probably A unified style generation engine but that's tracked separately.
