### ISSUE TITLE
More inline formatting

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#2747]
I was trying to use Gutenberg to write a blog post, the overall experience is quite nice. The only thing I couldn't achieve is highlighting some inline text with a different color.

 - Should we provide this built-in?
 - How can we provide an API to add inline formatting (highlighting, underlining, tweak text size ...)?

**Comment by karmatosed** [comment]
I would say no for now to this. Adding different color to text feels like we are opening issues. We already can do bold, italics. Maybe we look into this for v2 but I do not think for a v1 this is the right addition - now. It totally could be something we come back to and even look at based on how nesting goes and usability test feedback, though.
