### ISSUE TITLE
Implementing Core Systems modules for a Component System

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#27485]
This is an extension of [Implementing a Component System](https://github.com/WordPress/gutenberg/issues/27484)

---

A Component System is built on top of many other core systems - just like how Gutenberg (the editor) is built on top of many core packages.

From the [next iteration of `@wordpress/components` project](https://github.com/ItsJonQ/g2), there are 5 core systems/modules we'll need to integrate (in order):

* [ ] `utils`: A collection of shared utilities (https://github.com/WordPress/gutenberg/issues/27485)
* [ ] `substate`: A component library optimized state management system
* [ ] `create-style`: Architecture that creates the Style System
* [ ] `style`: The Style System
* [ ] `context`: The Context System

These systems form the foundations of which the Component System can be constructed.

**Comment by jordesign** [comment]
@annezazu Wanted to check with you if this overview/tracking issue is still relevant - or if we have Component work tracked in another issue somewhere?

**Comment by annezazu** [comment]
Let's close this out as I think the work has moved on _enough_ at this point.
