### ISSUE TITLE
Creating and Spliting Lists

### ISSUE THREAD

**Issue by fisicx** [WordPress/gutenberg#2748]
I wrote some copy using Returns and realised this would be better as a list

There doesn't appear to be a way to select a number of paragraph blocks and convert them into a list (something easy to do in a non-Gutenburg post).

When I split the list by hitting Return twice Gutenburg added a paragraph as expected but I then couldn't backspace to merge the list again. I know there is the trash can but using this isn't intuitive to someone used to writing and editing copy.

**Comment by aduth** [comment]
Related: #539

Merging behaviors exist, but apparently not covering the behavior you describe: merging from a paragraph block into a list.

**Comment by fisicx** [comment]
The initial problem seems to be that you can't highlight a group of blocks.

I've also discovered you can't create rich media lists. I have a list on one site where each LI comprises an H3, paragraph content and an image. Gutenburg baulks at this even though it's part of the W3C spec in that an LI can contain any flow content: http://www.w3.org/TR/html5/grouping-content.html#the-li-element

**Comment by aduth** [comment]
>The initial problem seems to be that you can't highlight a group of blocks.

Block multi-selection exists, though in the use case of lists specifically, there is presently an issue where selecting single lines of text doesn't always take effect until the third block selection. This is tracked at #2646 with a pending fix at #2695.

It's also an open question as to whether selecting across paragraphs and converting to a list is the _desired_ behavior, or if this should be done by Shift-Enter creating single lines within the same paragraph block, then transforming to a list with each single line as a list entry.

**Comment by fisicx** [comment]
Maybe block multi-selection exists but I haven't yet discovered how to do this. The normal method in all text editor is to place the cursor at the start point and use the keyboard or a mouse to move to the endpoint. Gutenburg does not appear to allow this.

The desired behavior is to select all the content (in any format) and convert it to a list.

Shift Enter isn't how people do things, They write chunks of content and then manipulate it to reach a desired layout. I should be able to do this when editing a post.

My mum writes recipies. She adds all the steps to her posts, add images where appropriate and then converts the whole lot to an ordered list once she is happy. Gutenburg just doesn't allow this.

**Comment by mtias** [comment]
Consolidating in #539.
