### ISSUE TITLE
Block Selection: Partial block multiselection

### ISSUE THREAD

**Issue by mogmarsh** [WordPress/gutenberg#27481]
This request was discussed in https://github.com/WordPress/gutenberg/issues/3629 but that issue has been closed with the note "We should open follow up issues for additional enhancements like partial block selection...". I'm not finding a follow up issue on Partial Block selection, so I am opening a new one.

The basic request is to be able to select some content from one block and some content from the next block, without it selecting all of both blocks. This would allow an Editor to combine two paragraphs by deleting the end of the first paragraph and the beginning of the second paragraph. 

The animation in https://github.com/WordPress/gutenberg/issues/3629#issuecomment-627651714 demonstrates the issue well: 
![example animation of selecting blocks](https://user-images.githubusercontent.com/617986/81755058-937c5800-946c-11ea-88e1-31f355f4a0e4.gif)

**Comment by gziolo** [comment]
This feature has just landed in Notion:
https://twitter.com/notionhq/status/1483884489235255297

They are still working with the Mozilla team to enable it in Firefox.

**Comment by mtias** [comment]
Curious if there are any implementation details worth sharing!

**Comment by Mamaduka** [comment]
Looks like it took a lot of work to add this feature - https://twitter.com/jitl/status/1483918085384028163.

**Comment by ellatrix** [comment]
This feature was added with https://github.com/WordPress/gutenberg/pull/38892. Would be good to get more testing in trunk before it's in the next Gutenberg release and the next WP release.
