### ISSUE TITLE
Improve layout shift caused by pattern previews loading in the inserter menus.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27494]
**Is your feature request related to a problem? Please describe.**
Related #27493

Using the search input in inserter menus can cause quite a lot of layout shift as the pattern previews load asynchronously.

This seems more noticeable in the Quick Inserter menu which has a smaller space. It's particularly noticeable when the popover is positioned above the inserter button, as the patterns cause everything above them to shift up and down.

Try:
1. Adding enough content so that the trailing appender button is at the bottom of the screen.
2. Clicking the trailing appender and then searching for random terms
3. Notice how pattern previews don't display immediately, and when there's more than one the content can shift up and down a couple of times.

**Describe the solution you'd like**
Add some kind of loading placeholder to patterns. While we don't know ahead of time what size the preview will be, an approximate sized placeholder would help. Currently the preview is zero height when loading, and then it shifts to potentially 100-200px. The amount of shift could be reduced. 

The placeholder aspect ratio could also be part of a pattern config if we'd like to be more precise, or alternatively the previous size could be cached and used for the placeholder so that the shift only happens the first time searching.

**Describe alternatives you've considered**
Couldn't think of any.

**Comment by mapk** [comment]
@talldan Is this a good example of the problem you're experiencing? My patterns load quickly, but I see the popover jumping up and down.

![inserter](https://user-images.githubusercontent.com/617986/101403471-273ec700-388a-11eb-9ff0-8b5b04b830a7.gif)

**Comment by talldan** [comment]
@mapk Yep, your patterns are loading a bit faster than I experience. I see more up and down movement as things pop into existence:
![pattern-load](https://user-images.githubusercontent.com/677833/101430740-94149880-3940-11eb-8bba-bb0d8012db53.gif)

This might be related to me using a development build of the plugin, it does seem a bit quicker using a production version. 

Do you think there's any room for improvement? Happy to close this if it looks like there's not much that can be done.

**Comment by mapk** [comment]
@talldan I see the hiccup now. Your proposal sounds like an idea to try if it's not too difficult.

I imagine it would be similar to this below. I'm using our general loading icon. On detection of patterns, show the loading icon until the patterns are ready to be displayed.

![loading](https://user-images.githubusercontent.com/617986/101957607-9849eb80-3bb6-11eb-8038-67d4ec041c4e.gif)

**Comment by paaljoachim** [comment]
I am really not sure what can be done here. 
It does move up/down to show patterns that can be added.
We might need to think of a broader solution.

**Comment by talldan** [comment]
I think this can be closed, as the UI is quite different now.
