### ISSUE TITLE
Date: Tests are false-positive, assumes it is ran in GMT timezone and en_US locale

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#27500]
**Describe the bug**
1. Date package assumes the environment is in `GMT` all the time. This causes false positives in the CI (since the tests are passing). In real use-case, the Date package might be returning wrong results. Which might cause several other bugs.

2. Date package tests assume your locale is `en_US`. Runs on CI fine, but my locale is set to `en_GB` so one particular test is failing for me. (`should support "T" to obtain the timezone abbreviation for the given date`)

**To reproduce**
1. Run `npm run test-unit packages/date/src/test/index.js` (Run tests in your local timezone, if your local timezone is GMT, use the TZ environment variable to change it to something else)
2. See 3-4 tests are failing
3.  Run `TZ='GMT' npm run test-unit packages/date/src/test/index.js` (Run tests in GMT, should be the same as running in the CI)
4. Tests should pass or see one test failing (depending on your locale): `should support "T" to obtain the timezone abbreviation for the given date`

You can fake your timezone and locale to mimic the CI environment: `TZ='GMT' LANG="en_US.UTF-8"  npm run test-unit packages/date/src/test/index.js`. Running the unit test like this will make sure your tests are passing. (Though it's obviously false-positive)

**Comment by ockham** [comment]
:wave: @david-szabo97 I think that @vcanales is working on a fix in #27398, ICMYI :blush:
