### ISSUE TITLE
Rename the query block

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#27501]
The name `query` doesn't quite convey what the block does or how it can be used... It might make sense to a WordPress developer, but not to a **user**. 
Even to a WordPress developer, it's not clear what it does. Is it a query that gets taxonomies? terms? users? posts? Something else?
The scope of this block however is pretty specific: It gets **lists of posts**, and displays them in a customizable fashion. So perhaps we should consider renaming it to something that would make more sense for the end user?

cc @ntsekouras @youknowriad @gziolo @jasmussen

**Comment by ntsekouras** [comment]
I'm not opposed to that. A name like `Query Posts` could work and be more informative. Even if it supports other post types, I think a WordPress user makes that mental mapping of Posts -> Entities, post types. We also make use of some other Query variations in the future as we did with `Posts List`.

**Comment by jasmussen** [comment]
My immediate instinct is that it's fine that the query block has a technical name, because the way I see it it isn't necessarily meant to be manually inserted like that very often, whereas more specialized blocks that might leverage it, like Latest Posts, or even patterns that include it, might would be the primary mechanisms for inserting it. 

This is not a strong opinion against a rename. I just don't have any good suggestions that would really move the needle on this one.

**Comment by mcsf** [comment]
I think the question is good, but my opinion is the same as Joen's (https://github.com/WordPress/gutenberg/issues/27501#issuecomment-738686394). Query itself is a low-level / advanced block for advanced users, and I expect less experienced users to interact with it implicitly through other blocks. But I also don't feel strongly about this. :)

**Comment by carlomanf** [comment]
What about "Posts" for core/query and "Post" for core/query-loop? This would better convey the difference between those two blocks, and is similar to [what was proposed early on](15623). That said, it has been brought up in #26856 that it might be better to switch out "post" in block names for something more post type agnostic.

**Comment by javiercasares** [comment]
Content(s) Block? The Query block can load "any kind of content" (post, page or whatever the user created -CPT-) so, a generic like "Contents" (or Content); for example, in Spanish will be "Bloque de Contenidos" (this is very clear for me, for example). I think that's very generic, but you know you will fin that: "your content".

**Comment by mtias** [comment]
Query is meant to be a lower level tool for theme building from which different user-facing blocks can be made (like Posts List) and it's meant to be able to query posts, or WooCommerce products, or portfolio items, etc.

In that sense it's similar to the generic "Embed" block. Users will in most cases interact with YouTube Embed, or Twitter Embed, and so on.

**Comment by annezazu** [comment]
Looking this issue over, it seems like this can be closed out as it's come to the surface that the query block has to play a larger role and the name right now best reflects that. What do you think, @aristath ?

**Comment by aristath** [comment]
Agreed, closing this one :+1:
