### ISSUE TITLE
Add editor setting to toggle Breadcrumb UI on/off.

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#27515]
At the bottom of the editor there is a white toolbar that lists a breadcrumb-like trail of the currently selected block:

<img width="173" alt="image" src="https://user-images.githubusercontent.com/191598/101187755-c3669500-3622-11eb-8cbe-7be911b77670.png">

The intention of this toolbar is to make it easier to traverse from a child block to its parent(s). However, I've rarely seen users interact with this UI; Its generally "invisible" unless pointed out, and even then its not always obvious what this list of blocks shows.

I suggest we add an option to the editor preference to control the display of this toolbar. Here's how the appearance preferences look now:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/191598/101188032-25bf9580-3623-11eb-9e38-bee8dfda2687.png">

We could add a new option for "Display block breadcrumbs" and/or integrate the display of the breadcrumb toolbar with the existing "Reduce the interface" setting.

I think we should also consider disabling the breadcrumb toolbar by default.

**Comment by shaunandrews** [comment]
Alternatively, we could also consider simply removing the breadcrumb UI outright.

**Comment by chthonic-ds** [comment]
For myself, the breadcrumb UI is still the only way to consistently select the block I want. The editor will be frustrating to use if it is completely removed.
