### ISSUE TITLE
WP 5.6 RC3 unclear dropdown for Author setting

### ISSUE THREAD

**Issue by dariaknl** [WordPress/gutenberg#27513]
**Describe the bug**
In current Gutenberg master branch version and in WP 5.6 RC3 the Author does not appear to be clear drop down:

<img width="282" alt="Screenshot 2020-12-04 at 15 54 19" src="https://user-images.githubusercontent.com/19681708/101178196-fd4a9200-3648-11eb-9b62-12cd89e4c819.png">

Please compare this drop-down with WP 5.5:
<img width="281" alt="Screenshot 2020-12-04 at 15 51 35" src="https://user-images.githubusercontent.com/19681708/101178223-05a2cd00-3649-11eb-9557-3ed21b962ef3.png">

**To reproduce**
1. Install WP 5.6 RC3.
2. Go to create a post.
3. Check Post Status and visibility settings.

**Expected behavior**
A clear drop down field for Author.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.6 RC3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by kjellr** [comment]
Noting that [a question about this came up in the forums](https://github.com/WordPress/gutenberg/issues/27513) as well: 

> The ‘Author’ dropdown in wp-admin/post seems to have changed. If I recall it was previously larger, with larger font, and easy to quickly scroll and select required author. Now it’s a small box in small font requiring a lot more clicking and finessed scrolling to achieve what used to be done in a simple operation. Is there any way to restore previous function?

**Comment by adamsilverstein** [comment]
In addition to some style improvements, some related issues that might help this issue:

* https://github.com/WordPress/gutenberg/issues/26077 - use a standard `select` (dropdown) element when the number of users is small -  instead of the new accessible searchable selector.
* https://github.com/WordPress/gutenberg/issues/25798 - add a loading indicator during searches.

**Comment by skorasaurus** [comment]
Hi, 
This appears to have been fixed in WordPress 5.7. Please reopen if you're still experiencing this. 
![image](https://user-images.githubusercontent.com/955351/122965345-16513100-d356-11eb-96b9-ea8bc4e6f083.png)
