### ISSUE TITLE
Site editor sidebar: z-index issue with wrapped toolbar options

### ISSUE THREAD

**Issue by rickybanister** [WordPress/gutenberg#27525]
**Describe the bug**
The block toolbar in 'top toolbar' mode has a z-index that is higher than the editor sidebar, obscuring the link to the dashboard:

<img width="837" alt="Screen Shot 2020-12-04 at 4 24 39 PM" src="https://user-images.githubusercontent.com/437258/101217567-92508980-364f-11eb-9fc5-400944b237cd.png">

**To reproduce**
1. Go to the site editor
2. Toggle on the 'mobile' view from the preview dropdown
3. Make your browser viewport < 1200px wide
4. See the block toolbar options wrap below the primary toolbar
5. Open the W menu sidebar and see the z-index issue.

**Expected behavior**
The sidebar to be above the rest of the editor UI

**Editor version (please complete the following information):**
Gutenberg Plugin 9.5.0

**Comment by kathrynwp** [comment]
@rickybanister Hi! I can no longer replicate, so I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it. Thanks!
