### ISSUE TITLE
Theme Options for own Social Link List

### ISSUE THREAD

**Issue by mkkeck** [WordPress/gutenberg#27527]
I'm always frustrated when using the Social Link Block from WordPress Core. There are many links to social platforms, which are useless or not really often used.
Removing these useless or not needed social links and of course their icons and styles would result in smaller asset files.

It would be nice, to have the option to define social link settings wich would update der Social Link Block and Social Link Widget based on theme-support, like colors and font sizes do.

It would be also nice to make output theme able with server side rendering the social link blocks and widgets.

**Comment by talldan** [comment]
> Removing these useless or not needed social links and of course their icons and styles would result in smaller asset files.

@mkkeck I don't think there's much cause for concern over asset sizes. The icons are svgs, they're tiny in size. The icons are rendered server-side, so only the icons used are loaded on the front-end of a site.

If you want to remove an individual icon from the editor, you can use the following JavaScript:

```jsx
wp.blocks.unregisterBlockVariation( 'core/social-link', 'behance' );
```

Does that help answer your question? Let me know if I've misunderstood.

For your other points, I'm not completely sure I understand the points about theme-support and server-side-rendering. Would you be able to expand on what you're hoping to achieve? If you're able to create a new issues and use the feature request template that would be great.
