### ISSUE TITLE
Make the Block Editor Styles Panel Collapsed State Sticky

### ISSUE THREAD

**Issue by Protohominid** [WordPress/gutenberg#27538]
There are blocks that have a collapsible panel that is expanded by default. For example, the image block has a new "Styles" panel that is always expanded. If the user collapses a  @panel, shouldn't that preference be saved in a cookie so they don't have to do it every time they edit a post? It's really annoying, especially when that expanded panel takes up the entire sidebar. I'd argue that the Styles panel is far from necessary and should possibly be collapsed by default. 

If this isn't feasible, is there at least a way for me to do this on my sites using a hook or custom snippet of some kind?

**Comment by talldan** [comment]
@Protohominid This isn't possible. Please could you use the Feature Request template when creating a new issue if you'd like to request this as a feature.
