### ISSUE TITLE
Flow Content in list elements

### ISSUE THREAD

**Issue by fisicx** [WordPress/gutenberg#2753]
The W3C spec states that an LI can contain any flow content: http://www.w3.org/TR/html5/grouping-content.html#the-li-element

No matter how I try I cant do this with Gutenberg.

I want a  list where each LI has an H3, content and an Image. I can create this list in text view but once the post has updated everything gets stripped  - even the list content disappears

**Comment by mtias** [comment]
There's a blocker for this in how we approach handling nested content (which includes the UI flow for inserting things within a list, like images, headings, etc).

We might still make it work if you edit HTML directly in the meantime.

**Comment by mtias** [comment]
Related #2747.

**Comment by fisicx** [comment]
I was editing the HTML - that's how I added the content to the list elements. The post saved correctly but switching between text/visual strips the markup

**Comment by mtias** [comment]
Consolidating in #539.
