### ISSUE TITLE
Block API: Allow blocks to specify attributes that map to meta fields

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2754]
At the moment a block's attributes can come from two places: sourced from HTML, or serialized as JSON in HTML comments.

We want to allow attributes that can be retrieved and saved in post meta. Such attributes won't exist in the HTML, meaning they rely on server rendering through `get_post_meta()`.

**Comment by mtias** [comment]
Added in #2740.

**Comment by aduth** [comment]
Related: #2751

**Comment by aduth** [comment]
Related: #2759

**Comment by aduth** [comment]
Closed by #2740
