### ISSUE TITLE
Can not convert a classic block with multiple links to blocks. Can't even paste multiple links

### ISSUE THREAD

**Issue by wpgaurav** [WordPress/gutenberg#27551]
**Describe the bug**
Whenever I try to:
1. Paste multiple URLS (like a list of sites)
2. Convert a classic editor block with multiple URLs.

It tries to embed those URLs as a single link.
Please see the screenshot:
[https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif](https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif)
**To reproduce**
- Paste multiple links at once, like these:
`The List of Sites:
https://addthis.com
https://elegantthemes.com
https://generatepress.com
https://woocommerce.com
https://backlinko.com
https://elementor.com
https://elmastudio.de
https://wptavern.com`

- OR if a Classic Block already has a list of links, Convert that to blocks.

**Screenshots**
[https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif](https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.3]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] : Gutenberg is Installed.
- If the Gutenberg plugin is installed, which version is it?: 9.4.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version : 86

**Comment by talldan** [comment]
I can reproduce the issue when pasting into a paragraph block, it does indeed converted to an embed, and that embed then can't be transformed back into the original content using the 'Convert to Link' option as the spaces are removed.

I think this is the relevant code, it seems like `isMatch` should only return `true` if there's a single link in the textContent:
https://github.com/WordPress/gutenberg/blob/873f94106a11e11bfab0184998421907dc6370c5/packages/block-library/src/embed/transforms.js#L19-L29

This could be a fairly simple fix, so will label as Good First Issue.

Converting from a classic block worked ok for me. That might need further testing.

**Comment by gaavar** [comment]
- Hi! I am a first-time contributor. Can I take up this issue?

**Comment by talldan** [comment]
That would be great @gaavar, let me know if you need any assistance!

**Comment by gaavar** [comment]
@talldan thank you so much! I got stuck with some failures while setting up the dev environment on WSL2 Ubuntu. Is there a slack channel or similar for gutenberg where I can ask for assistance on this?

**Comment by talldan** [comment]
@gaavar What was the error?

There is a slack instance (https://wordpress.slack.com/signup#/), and it's the #core-editor channel for Gutenberg development.

Might also be worth searching the issues here to see if anyone else has had the same problem.

**Comment by gaavar** [comment]
My dev environment is all set up! Here's what I noticed: when I use a classic block and copy-paste a list of links (each on a new line),
the classic block doesn't carry over the new line and hence every link from the list appears to be concatenated together and when trying to use `Convert to blocks`, the embed feature gets triggered but treats everything as a single link. I am guessing the embed feature is supposed to be triggered for each link separately. Is that the correct expected behavior? @talldan @wpgaurav

**Comment by gaavar** [comment]
As a follow-up, examining the code portion I think the regex can be modified a bit to return True only if there's one URL in the `node.textContent`.

**Comment by talldan** [comment]
@gaavar Glad you got it all set up 🎉 

Yep, I think modifying the regex as you describe looks would be a good thing to try first. 👍
