### ISSUE TITLE
Can I use the default webpack config (wp-scripts) to mount elements in DOM?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27557]
I'm trying to build my plugin dashboard/admin using React, so I figured it would be worthwhile to use the block-plugin webpack config. It'd provide access to many optimizations and it feels somewhat extraneous/wasteful to install react/react-dom and maintain a separate config for them. I gave it a [shot](https://glitch.com/edit/#!/join/38ffef78-5b61-4bf3-82d9-19f702af7162) but I get this error

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/9297865/101390936-94ce1000-38e9-11eb-878c-432152ba0dfe.png">

Am I missing something?

**Comment by stokesman** [comment]
It looks like your script is executing before the core WP stuff it depends on is available. You'll want to make sure it comes after those. Here's the relevant [part of the docs](https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/#dependency-management).

**Comment by stokesman** [comment]
> I gave it a shot

I didn't see that was a link when I first replied. To use wp-scripts for a standalone (outside of WP) context, the `start` or `build` scripts need to be invoked with the `--webpack-no-externals` option. You can find the bit about this in the docs toward the end of [this section in the docs](https://developer.wordpress.org/block-editor/packages/packages-scripts/#start). Without that option any of the core WP packages will not be included in the bundle and that's the cause of the error in this case.

I tried it on the glitch project you linked. It can work. I also tried importing from '@wordpress/components'  at which point the bundle size gets rather large and the build nears the limits of the default environment they provide. You might like to try this [codesandbox template for standalone wp-scripts usage](https://codesandbox.io/s/wp-scripts-for-use-outside-wordpress-oyzst).
