### ISSUE TITLE
Inserter: Remove "global" (toolbar) inserter

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2755]
Related (blocked by): #2752 

With an exploration of nested blocks pending (#2743), the usability of the global block inserter is being called into question. As an example, consider the case that the quote block allows nesting text or image blocks. If while focused within the quote text I decide to use the global inserter to insert an image block, would I expect it to (a) be inserted within the quote or (b) be inserted as a new top-level block after the quote? While the insertion point highlight helps, it is not shown until after the user has made the conscious decision to use the inserter (assuming they had already decided the effects of said insertion).

__Proposal:__

Remove the global inserter.

**Comment by jasmussen** [comment]
I can follow your reasoning and I appreciate the work you have done with the "hover between blocks", but I disagree with your conclusion that usability is improved by removing the global toolbar inserter.

Consider the case where you create an empty quote block first, and want to insert content other than a single paragraph of text. The hover inserter is not going to make things more obvious here. While always showing a trailing inline inserter plus may help, I'm unconvinced this is going to be a better solution than improving the toolbar inserter. 

The most common pattern for inserting content is to put the text caret where you want the content, and then click the inserter. While we don't yet support inline insertion of images, we get close to this by showing the blue indicator after the block that has the caret. Can this not be made to work in a nested context?

**Comment by aduth** [comment]
>The hover inserter is not going to make things more obvious here. 

It may have been in earlier conceptions that these adjacent inserters were more obvious; always visible for the currently selected block, more similar to as implemented in #2890. However, the visual noise in such an approach is certainly not ideal.

>The most common pattern for inserting content is to put the text caret where you want the content, and then click the inserter.

I can see this, sure. As far as clarity is concerned, there may be a point to be made around having three different options for inserting: via the global inserter at the caret point, via adjacent block hover inserters, and finally the end-of-content inserter. Is this too many options?

>Can this not be made to work in a nested context?

It should be able to work, sure.

**Comment by jasmussen** [comment]
> I can see this, sure. As far as clarity is concerned, there may be a point to be made around having three different options for inserting: via the global inserter at the caret point, via adjacent block hover inserters, and finally the end-of-content inserter. Is this too many options?

That's absolutely a possibility. Redundancy is okay to a point. We may indeed find that we don't need the inserter in the editor bar — certainly would be nice to remove it from a space/visuals point of view. But even then we'd still need it for mobile, and I'm not sure we could make a call in the near future. So definitely worth having this ticket open, so we can re-review in the future.

But given how important the inserter is to the whole project — previously it was an "insert image" tool, now it's _insert anything_ — it seems like a decision that shouldn't be made lightly. (Not that I'm implying you suggested to take this lightly, just explaining why I think we might want to sit on this for a bit.)

**Comment by mtias** [comment]
Closing as this doesn't seem as problematic as before. We can revisit once we have nesting UI.
