### ISSUE TITLE
Widget Editor: Missing ellipses Options menu from topbar

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#27564]
**Describe the bug**
It appears the Options menu was removed from the Widget Editor.

![Screen Shot 2020-12-07 at 1 33 47 PM](https://user-images.githubusercontent.com/617986/101408341-22c9dc80-3891-11eb-9e84-1b43918651a8.png)

**Expected behavior**
There are items there that are still beneficial in this screen such as: 
- Copy all content
- Help
- Preferences

I'd also like to add a preference options for keeping the Inserter panel open after selecting a block as indicated here: https://github.com/WordPress/gutenberg/issues/26223#issuecomment-724282755
Before we can do that, can we add back the Options menu first?

**Comment by critterverse** [comment]
Seconding this menu as important functionality to add for both of the Widget editors. Opened a companion issue for the Customizer Widgets screen in #30886!

**Comment by draganescu** [comment]
I've drowned myself in questions thinking about this:

- Which options will we still need for the screens? Does fullscreen make sense? Code editor should not be available. Help, welcome guide and keyboard shortcuts, maybe but would probably need their own edits.
- Is that the best place for some of the options? For example, copy all content, must  not copy widget areas, and if we copy all widgets and blocks from all areas, all at once, what do we do it for?
  - How do some of the options apply in the Customizer? Copy all content means something else there as one can only edit one widget area at a time. This suggests copy all content should default to copying all current widget area content in both places.
- The prefferences are also different, e.g. we don't have a pre-publish checklist.

Should we dive in these before we add it? Or add it and incrementally fix the problems?

**Comment by critterverse** [comment]
I would vote for starting with a condensed version of the ellipses menu that only contains a few relevant options. This would allow for a few important accessibility/usability options to start, and then more things could potentially be added later as needed. For example, what if it only contained these options for now?

![ellipses-menu](https://user-images.githubusercontent.com/77359364/118564984-61689a80-b73f-11eb-82d1-d13798d8787e.jpg)

Re: Preferences menu, I don't think we need the entire modal but it would be nice to include the option for containing the text cursor inside blocks that usually appears within the "blocks" submenu. I could see this option being extracted from the Preferences modal to appear inline with other options in the ellipses menu.

**Comment by talldan** [comment]
@critterverse This sounds good. I think 'Show Icon Labels' and 'Block Manager' could also be useful. I can look into how easy they would be to implement.

If it's mostly just re-using existing components, what do you think about those two?

edit: don't worry about this, looked into it and it turned out those two options are complicated 👍

**Comment by talldan** [comment]
As part of this, I think we need a dedicated widget editor user support page for the 'Help' link. This is what the post editor links to:
https://wordpress.org/support/article/wordpress-editor/

Lots of the content there isn't relevant.
