### ISSUE TITLE
Env: Unable to resolve twentytwentyone-blocks on start

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#27567]
**Describe the bug**
I am receiving a `failed to resolve path` on `Repository.open` when trying to start `wp-env`: 
```
failed to resolve path '[LOCAL PATH]/theme-experiments/twentytwentyone-blocks': No such file or directory
```

From the debug output I see that it's trying to resolve an invalid git repo : 
```
"themeSources": [
		{
				"type": "git",
				"url": "https://github.com/WordPress/theme-experiments/twentytwentyone-blocks.git",
				"ref": "master",
				"path": "[LOCAL PATH]/theme-experiments/twentytwentyone-blocks",
				"basename": "theme-experiments/twentytwentyone-blocks"
		}
]
```
`https://github.com/WordPress/theme-experiments/twentytwentyone-blocks.git` returns a 404

**To reproduce**

1. Run `wp-env start --debug`
2. Note that the `ThemeSource` config in the debug output points to an invalid git repo
3. Process fails with a `Repository.open` error

**Expected behavior**
Expect docker image to start successfully with `twentytwentyone-blocks` available to the local WP install.

**Desktop (please complete the following information):**
 - maxOS Big Sur

**Comment by skorasaurus** [comment]
The user reported [they're no longer able to reproduce this issue in a newer version of env](https://github.com/WordPress/gutenberg/pull/27569#issuecomment-758974130); closing
