### ISSUE TITLE
Support wide/full alignments for the query block container

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#27589]
The query block currently appears full-width in the editor by default, but it doesn't actually include standard/wide/full width controls for itself:

![Screen Shot 2020-12-08 at 1 25 45 PM](https://user-images.githubusercontent.com/1202812/101525302-1d37c980-3959-11eb-8e84-f53e8828965b.png)

This should potentially behave like a group block or template part, where it has its own width settings as a parent block.

**Comment by carolinan** [comment]
Compared to the template part and group block, the query does not have an HTML element on the front, and I believe that is intended.
Would the alignment be passed to the inner block using _context_?

**Comment by kjellr** [comment]
Right, sorry. I think the Query Loop block is the one that would need this control... It does wrap things in a `ul` on the front end right now: 

![Screen Shot 2021-01-04 at 9 07 54 AM](https://user-images.githubusercontent.com/1202812/103543335-57b75800-4e6c-11eb-962a-8a1061c0a57d.png)

In any case, the root of the issue is that in my testing (Using TT1 Blocks), setting wide/full for blocks inside of the Query Loop block doesn't make them appear wide/full in the editor:

![Screen Shot 2021-01-04 at 9 05 56 AM](https://user-images.githubusercontent.com/1202812/103543211-250d5f80-4e6c-11eb-9e66-f9d48557cefe.png)

(same thing happens in the front end, but that's the theme's responsibility to fix until there's a resolution to https://github.com/WordPress/gutenberg/issues/26633.)

**Comment by ntsekouras** [comment]
@kjellr is this PR: https://github.com/WordPress/gutenberg/pull/30804 enough to close this issue?

**Comment by kjellr** [comment]
Yes, I believe that would solve this specific issue. Now that the Query block has its own container, we were also discussing [the ability for it to have its own layout controls](https://github.com/WordPress/gutenberg/pull/30506#issuecomment-813900134). Is that still the plan?

**Comment by ntsekouras** [comment]
>we were also discussing the ability for it to have its own layout controls. Is that still the plan?

Yeah it is, although this might be a bit trickier due to some technical details with existing `layout` property and internal consumption of this prop.
