### ISSUE TITLE
Fix and re-enable Navigation Block e2e tests

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#27588]
The Navigation Block e2e tests were skipped in #27018 as we iterate on the experimental Nav block. This is a tracking issue so we don't forget to circle back and fix the tests once the interface stabilizes. We are working on iterations of the placeholder interface and markup and the tests are quite dependent on the final state.

**Comment by gwwar** [comment]
I plan on updating this in https://github.com/WordPress/gutenberg/pull/29543
