### ISSUE TITLE
Layout of some Standardblocks in some Standardthemes is broken in Gutenberg

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#27599]
Tested with WP 5,6 and latest Update of Themes:

[Repair of List block](https://github.com/WordPress/gutenberg/issues/24780) with latest Theme Update works, but there are some other blocks like (sometimes) Quote and (in many cases) Code, Preformatted and Verse with the same problem of breaking the Layout in Gutenberg Editor on the left side. (Resulting webpage is always OK.)
The problems with Quote-block (in Twenty Sixteen and Twenty Twenty) seems based on WP 5.6 (OK with WP 5.5.3)

Twenty Fourteen:
![TwentyFourteen - Layout Problems](https://user-images.githubusercontent.com/32030147/101607992-7eb57200-3a05-11eb-9bc9-cbac7d3da7a8.jpg)

Twenty Fifteen:
![TwentyFifteen - Layout Problems](https://user-images.githubusercontent.com/32030147/101608776-701b8a80-3a06-11eb-8e0f-1cee4372115d.jpg)

Twenty Sixteen:
![TwentySixteen - Layout Problems](https://user-images.githubusercontent.com/32030147/101608814-7c074c80-3a06-11eb-8497-e8aa8d972549.jpg)

Twenty Seventeen:
![TwentySeventeen - Layout Problems](https://user-images.githubusercontent.com/32030147/101608847-87f30e80-3a06-11eb-83cc-8dc03157672e.jpg)

Twenty Twenty:
![TwentyTwenty - Layout Problems](https://user-images.githubusercontent.com/32030147/101608887-96412a80-3a06-11eb-9f79-e97ec4dd5edd.jpg)

**To reproduce**
1. Make a testpage with different standardblocks
2. change Theme
3. check layout in Gutenberg
4. See the problem

**Expected behavior**
All WP Sandardblocks in WP Standardthemes should work with Gutenberg Block editor without breaking the visible layout in the editor!

**Screenshots**
If applicable, add screenshots to help explain your problem. => see above

**Editor version (please complete the following information):**
- WordPress version: 5.6 + 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? without Gutenberg

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox + Chrome
 - Version: latest

**Comment by talldan** [comment]
@burnuser Like the other issue you linked to, this should be reported in trac, as the bundled themes aren't part in this project, they're part of WordPress core.

Thanks for reporting though, I moved the issue over to https://core.trac.wordpress.org/ticket/52009 and will close this issue.
