### ISSUE TITLE
Block API: Allow blocks to specify attributes that map to site options

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2759]
Related: #2754

At the moment a block's attributes can come from two places: sourced from HTML, or serialized as JSON in HTML comments.

**Edit:** As of #2740, it is also possible to source attributes from post meta ([see documentation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-attributes/#meta))

We want to allow attributes that can be retrieved and saved as site options. Such attributes won't exist in the HTML, meaning they rely on server rendering through `get_option()`.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519320164000551)._

**Comment by mtias** [comment]
**Update**: this is being handled through entities now. Example: https://github.com/WordPress/gutenberg/pull/17207
