### ISSUE TITLE
Classic block duplicates content to other blocks when selecting both a paragraph and a classic block

### ISSUE THREAD

**Issue by wp-seopress** [WordPress/gutenberg#27601]
Classic block duplicates content after moves / selection to other blocks.

1. Create a new page.
2. Add a classic block.
3. Enter some text.
4. Add a paragraph block.
5. Enter some text.
6. More the paragraph block to first position.
7. Move the paragraph block to second position.
8. Make a selection of all your content from the bottom of the page.
9. All you classic content is duplicated to all your blocks!

Video showing the issue:
https://seopress-my.sharepoint.com/:v:/g/personal/seopress_seopress_org/EXSBj0PlcRlLkdvqU24w0gcBeLUyYBP8Gw0jjmSGDSPt9w?e=K623Km

WP 5.6, fresh install, no plugins, PHP 7.3
Chrome 87, MacOS Big Sur

**Comment by talldan** [comment]
Very hard to reproduce this, but I managed a couple of times. 

Most of the time the two blocks don't seem selectable, or when dragging a selection the classic block becomes selected (without the bug occuring).

**Comment by kathrynwp** [comment]
@talldan I'm no longer able to replicate this following the steps above. I'm going to go ahead and close this out, but feel free to reopen it if you can still replicate and think it's worthwhile to reopen. Thanks!
