### ISSUE TITLE
Update Quick Start GIF for Create Block Docs 

### ISSUE THREAD

**Issue by zzap** [WordPress/gutenberg#27602]
This is not really a bug but there's no type for updating the docs (maybe create one :) ).

In .gif animation for [create block package readme file](https://github.com/WordPress/gutenberg/blob/master/packages/create-block/README.md) we still have this command for creating a block:

```
npm init @wordpress/block todo-list
``` 

However, code snippet below is up to date and show different command:

```
npx @wordpress/create-block todo-list
```

Also, animation clearly shows this command should be executed in `plugins` folder:

```
cd wp-content/plugins
```

This is not mentioned anywhere in text and I think it should be.

**Comment by gziolo** [comment]
To be clear, both commands work exactly the same. `npm init @wordpress/block` is shorter but for some reasons we use `npx @wordpress/create-block` now in the documentation. This demo is hosted on nake.wordpress.org so it could be updated there if it isn't used in some old post. Otherwise we should still upload it to make.wordpress.org and update the reference in the README file.

**Comment by zzap** [comment]
>Next week we are publishing packages to npm so we could record new demo just after it happens to have the latest version.

Awesome. Thank you.

**Comment by gziolo** [comment]
There is a new version of `@wordpress/create-block` available so we can record a new GIF presenting how this tool looks in action.

**Comment by gziolo** [comment]
I recorded a new GIF that contains more details and uses interactive mode:
![wordpress-create-block](https://user-images.githubusercontent.com/699132/103872910-4de15f00-50cf-11eb-8c74-67ca91a8c1a4.gif)

**Comment by gziolo** [comment]
> Also, animation clearly shows this command should be executed in plugins folder:

It isn't a strong requirement. You can run it anywhere, but then you probably will want to move somehow your plugin to test with WordPress. I removed that part from the demo to avoid confusion.

**Comment by zzap** [comment]
Thank you so much @gziolo it looks great :)

Yes, of course you can run it anywhere and it will build files but every next step need that folder to be inside plugins dir. I don't think people just build custom blocks (or anything for that matter) without checking how it works until it's done.

As this is documentation for building blocks as WordPress plugins, I'd argue we should note somewhere that plugins should be working directory for initiating the whole process.

**Comment by gziolo** [comment]
> As this is documentation for building blocks as WordPress plugins, I'd argue we should note somewhere that plugins should be working directory for initiating the whole process.

Good point, I will open another PR that includes a note in the Quick Start section. 👍🏻

**Comment by gziolo** [comment]
Another PR is ready #28052.

**Comment by zzap** [comment]
That's awesome. Thank you so much :100:
