### ISSUE TITLE
Negative values in column's width redistribution

### ISSUE THREAD

**Issue by lukewalczak** [WordPress/gutenberg#27616]
**Describe the bug**

During the sanity testing before mobile release @chipsnyder noticed that we are able to get negative percentages in `Columns` and mentioned about it in the [comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2874#issuecomment-741859770). Since the logic for width redistribution is shared the same occurs on web editor. 

**To reproduce**
1. Create a new Blog Post
2. Add A Columns block
3. Select 70/30
4. Change column 1 to 90%
5. Set Column 2 to 10% (or around there)
6. Add a third column

Result: 
With those numbers I got: 73.34%, -6.66% and 33.33%.

![columns_web_negative](https://user-images.githubusercontent.com/22746080/101654633-07053880-3a41-11eb-8761-a80b93d24b74.gif)

_The same will happen when adding new column to the following columns: `90/5/5` and many other._

The problem is the wrong math within the function called `getRedistributedColumnWidths` located in [columns utils](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L86-#L98). 

```
export function getRedistributedColumnWidths(
	blocks,
	availableWidth,
	totalBlockCount = blocks.length
) {
	const totalWidth = getTotalColumnsWidth( blocks, totalBlockCount );
	const difference = availableWidth - totalWidth;
	const adjustment = difference / blocks.length;

	return mapValues( getColumnWidths( blocks, totalBlockCount ), ( width ) =>
		toWidthPrecision( width + adjustment )
	);
```

Mentioned method is assuming that **difference** _(difference between available width and new columns width sum)_ is divided equally between columns and subtracted from each of them. As a result we can get negative values, since **adjustment** has higher value than width. 

Let's consider it on the example from reproduction steps:

* Two columns: 90% and 10%
* New column will have width equal 33% _(100 / 3)_
* `availableWidth` refers to the sum of first two columns after adding the third one: 66.67 (100 - 33)
* `total width` refer to the sum of all columns: 100
* `difference` is -33.33 (_66.67 - 100)_
* `adjustment` is -16.665 _(-33.33 / 2)_

Finally we have
* first column: 90 - 16.665
* second column: **10 - 16.665**
* third column: 33.33

**Possible problem solution**

Imo the mechanism should be a bit different and width should be calculated proportionally to the **totalWidth**:

```
export function getRedistributedColumnWidths(
	blocks,
	availableWidth,
	totalBlockCount = blocks.length
) {
	const totalWidth = getTotalColumnsWidth( blocks, totalBlockCount );

	return mapValues( getColumnWidths( blocks, totalBlockCount ), ( width ) => {
		const newWidth = ( availableWidth * width ) / totalWidth;
		return toWidthPrecision( newWidth );
	} );
}
```

As a result we get positive values, divided proportionally:

* first column: 60
* second column: **6.67**
* third column: 33.33

<img src="https://user-images.githubusercontent.com/22746080/101658118-fd7dcf80-3a44-11eb-902a-c3b39f5523fb.gif" width="300" />

**Expected behavior**

Columns shouldn't have negative width values

**Screenshots**

Attached above.

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by chipsnyder** [comment]
Hey @tellthemachines and @gziolo, I saw that you two had worked in this area somewhat recently with the PR for fixing some [unit tests](https://github.com/WordPress/gutenberg/pull/26757). I was wondering if you two had enough context here to review @lukewalczak's plan.

**Comment by gziolo** [comment]
I don’t know how `getRedistributedColumnWidths ` should work but what you shared makes a lot of sense. It definitely seems buggy to calculate negative values. I checked unit tests and they cover only 2 columns. I’m sure adding test cases that verify use cases you identified for 3 (or even more) columns as needing changes would be a good start here.

**Comment by lukewalczak** [comment]
@gziolo thanks for your answer, I'm planning to prepare the PR with the fix along with additional test to cover _edgy_ cases
