### ISSUE TITLE
useSelect crashes blocks if a registered store doesn't implement unsubscribe

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#27631]
**Describe the bug**

`useSelect` might bubble up a `TypeError` _(`unsubscribe` is not a function)_ that ends up crashing a block in the editor. This happens because it [calls](https://github.com/WordPress/gutenberg/blob/master/packages/data/src/components/use-select/index.js#L202) `unsubscribe` unconditionally without taking into account stores that **do not** return `unsubscribe` from their `subscribe` function.

This can happen with custom generic stores, where the custom `subscribe` function implementation might not return the `unsubscribe` function since, by definition, it's optional ([see docs](https://developer.wordpress.org/block-editor/packages/packages-data/#generic-stores)).

**To reproduce**

1. Clone the [CoBlocks](https://github.com/godaddy-wordpress/coblocks), switch to the `2.5.3` tag;
1. Build your local version of CoBlocks by running `yarn && yarn build`;
1. In another top-level directory, clone Gutenberg, set it to the `v9.5.1` tag, build it;
1. Go back to the CoBlocks directory and add this `.wp-env.json`: https://gist.github.com/fullofcaffeine/aa4c76e5fad53f3ac52366bff3a85e44;
1. Make sure you have `wp-env` [installed](https://make.wordpress.org/core/2020/03/03/wp-env-simple-local-environments-for-wordpress/) globally;
1. Start your local WordPress instance with CoBlocks 2.5.3 and Gutenberg 9.5.1 by running `wp-env start .`;
1. Start a new post (http://localhost:8889/wp-admin/post-new.php);
1. Add or focus a paragraph block, type something, deselect it by clicking something else;
1. You should see the block crash and the error in the browser's JS console.

This seems to happen with other blocks too. I smoke-tested columns, quote, list, and they all crashed.

**Expected behavior**

Blocks don't crash and work when the user adds/sets them up if a generic wp-data store that doesn't implement an `unsubscribe` function is registered.

**Screencast**

![gbcoblocksissue](https://user-images.githubusercontent.com/81248/101703845-096b9080-3a49-11eb-9da5-4addb7057c52.gif)

**Editor version (please complete the following information):** 
- WordPress version: `5.5.3`
- Does the website has Gutenberg plugin installed or is it using the block editor that comes by default?: `gutenberg plugin`
- If the Gutenberg plugin is installed, which version is it? `9.5.1`

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Browser: Firefox `84.0b8 (64-bit)` and Chrome `87.0.4280.66 (Official Build) (64-bit)`

**Additional context**
- Originally reported in the CoBlocks repo, here: https://github.com/godaddy-wordpress/coblocks/issues/1772;
- Related to the changes in https://github.com/WordPress/gutenberg/pull/26724.

**Comment by ockham** [comment]
cc/ @kevin940726 @adamziel @youknowriad

**Comment by kevin940726** [comment]
I indeed didn't take generic store into account, thanks! I'll submit a PR soon.

**Comment by youknowriad** [comment]
I believe the issue here is not in Gutenberg itself. The unsubscribe is mandatory for stores. That said, since this was not forced in code previously, we should be more permissive but this is a case where a warning might be good to potentially remove the check in the future.

**Comment by sirreal** [comment]
> The unsubscribe is mandatory for stores.

The [documentation clearly states that `unsubscribe` is optional](https://github.com/WordPress/gutenberg/blob/77be77c60fc8bedc9c930d3c89a783a1b0f4be2f/packages/data/README.md#generic-stores) for generic stores:

> Behaves as Redux subscribe with the following differences:
> - Doesn't have to implement an unsubscribe, since the registry never uses it.

Changing that is a breaking change and definitely needs some notice and warning, probably a dev note.

**Comment by youknowriad** [comment]
Mmm :) Good catch, I wasn't aware of that and it doesn't really make sense for me :P but you're right if we do change, we need all the docs and communication.
