### ISSUE TITLE
Block height drops to 0 on alignment set to left or right

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27636]
**Describe the bug**

**To reproduce**
It happens on my custom block as well as the core gallery block.
1. Go to a new post page
2. Click on + icon to add a Gallery block
4. Set block alignment to left/right

**Expected behavior**
The block to maintain its default height

**Screenshots**
If applicable, add screenshots to help explain your problem
<img width="875" alt="image" src="https://user-images.githubusercontent.com/9297865/101737846-6ddf2c00-3aeb-11eb-9f61-aed03f96db38.png">

The blue area represents the selection border, which is overlapping itself since the block height is 0. As a result, one is unable to select the block using the mouse cursor.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser: Chrome
 - Version: 87.0.x

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by annezazu** [comment]
Thanks for reporting this! Here's a video replicating the oddness this seems to create for anyone curious:

https://cloudup.com/c79-yZr6bd8

Of note, this only happens with the default state before any images are added.

**Comment by navxio** [comment]
@annezazu It also happens with a block plugin we're developing..

**Comment by navxio** [comment]
@annezazu in the meantime, can we ask for a workaround so we can submit our block plugin?

**Comment by annezazu** [comment]
I'm afraid I can't personally offer a workaround to this but perhaps someone can. I'll add a new label to try to draw attention :)

**Comment by glendaviesnz** [comment]
This appears to be fixed in WP 5.8 and Gutenberg 11.3, with and without the gallery refactor experiment enabled:

![align](https://user-images.githubusercontent.com/3629020/131268806-ea2454a9-622a-4959-b0fd-10de100075a1.gif)

**Comment by carolinan** [comment]
I have not been able to reproduce this with WordPress 6.0.1.
