### ISSUE TITLE
Get current post ID in save function returns NULL

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#27635]
Not sure if this is a bug or intended behaviour.

I have a block that save post ID as attribute. The block is working but the console show me an error reporting "Content generated by save function:" is different from "Content retrieved from post body:".

The problem is that the post ID returns null at first glance and then retrieve the correct ID.

This is my code:

```
const { getCurrentPostId } = wp.data.select("core/editor");

export default function save( { attributes, className, props } ) {
    const post_id = getCurrentPostId();
    return (
        <form class={ className }>
            <input name="_form_id" type="hidden" value={ post_id } />
            <div style="display: none;">
                <input type="text" name={ '_secret_h' + post_id } value="" />
            </div>
            <InnerBlocks.Content />
        </form>
    );
}
```

Outputting in the console I got two times NULL and then I got the id. So the block display correctly at the end, however the error message remains.

How can I be sure that the ID is correctly retrieved?

**Comment by talldan** [comment]
@Tropicalista For static blocks the save function should only really depend on the block's attributes, incorporating other outside data like the post id is likely to cause validation errors. For example, if someone copied your block from one post to another, the `post_id` in your HTML would be incorrect and trigger the validation error (like the one you're receiving). Or another case would be if you ever exported/imported your site it would then also be incorrect if the post received a different id.

So I would say what you're trying to do is unsupported.

I think the solution would be to make this a dynamic block. That would make the block server-rendered, so the post_id would always be correct, the block also wouldn't be validated, so no validation issues.

I'll close the issue, does what I've shared help?

**Comment by Tropicalista** [comment]
Thanks for clarification. I've not thought about export issues. Thanks for your help. I will refactor my save function.

**Comment by Tropicalista** [comment]
I was tempted to use post meta to store my ID. However it seems tha "wp_block" type doesn't support meta. Is this correct? or is thre another way to add meta to blocks?

At the moment I've tried this:

```
    register_meta( 'wp_block', '_formaster_settings', array(
        'single' => true,
	    'auth_callback' => function() {
	        return true; // current_user_can( 'edit_posts' );
	    },
	    'type' => 'object',
	    'show_in_rest' => true,
   ...
```

**Comment by talldan** [comment]
`wp_block` is the post type for a reusable block, so I don't think this would do what you expect.

**Comment by Tropicalista** [comment]
So if reusable blocks does not support meta, the option on editor should be disabled. Here's the related issue: https://github.com/WordPress/gutenberg/issues/27662
