### ISSUE TITLE
Permalink incorrect for Scheduled Posts

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#2764]
## Issue Overview

When creating a schedule post the permalink that shows is incorrect. It is showing as `/?p=9160` but when published it will become a pretty permalink `/2017/09/23/title`

Tested out in the old editor because I thought it might of been an issue there and it works as expected, see screenshots below. The old editor updates the permalink after you type the detail and then updates it again after clicking "Schedule". Note it did not get updated when changing the date.

I have two scheduled posts. I want to add a link in the second post to the first post. I can not copy and paste the permalink from the first. 

## Steps to Reproduce (for bugs)
1. Create post
2. Change Publish date
3. Click Schedule
4. Check permalink, should be pretty permalink

### Old Editor Permalink 

<img width="667" alt="screen shot 2017-09-21 at 9 38 10 am" src="https://user-images.githubusercontent.com/45363/30707865-b3908b9c-9eb1-11e7-9060-f1db5d554147.png">

### Gutenberg Permalink

<img width="689" alt="screen shot 2017-09-21 at 9 40 54 am" src="https://user-images.githubusercontent.com/45363/30707876-b78ed8de-9eb1-11e7-8c23-4bce936f9cc3.png">

**Comment by mtias** [comment]
Closing in favor of #1285.

**Comment by steffanhalv** [comment]
```
// post, page post type
add_filter( 'post_link', 'future_permalink', 10, 3 );
// custom post types
add_filter( 'post_type_link', 'future_permalink', 10, 4 );

function future_permalink( $permalink, $post, $leavename, $sample = false ) {
	/* for filter recursion (infinite loop) */
	static $recursing = false;

	if ( empty( $post->ID ) ) {
		return $permalink;
	}

	if ( !$recursing ) {
		if ( isset( $post->post_status ) && ( 'future' === $post->post_status ) ) {
			// set the post status to publish to get the 'publish' permalink
			$post->post_status = 'publish';
			$recursing = true;
			return get_permalink( $post, $leavename ) ;
		}
	}

	$recursing = false;
	return $permalink;
}
```

**Comment by RayHollister** [comment]
> **To correct permalinks on frontend:**
> 
> ```
> // post, page post type
> add_filter( 'post_link', 'future_permalink', 10, 3 );
> // custom post types
> add_filter( 'post_type_link', 'future_permalink', 10, 4 );
> 
> function future_permalink( $permalink, $post, $leavename, $sample = false ) {
> 	/* for filter recursion (infinite loop) */
> 	static $recursing = false;
> 
> 	if ( empty( $post->ID ) ) {
> 		return $permalink;
> 	}
> 
> 	if ( !$recursing ) {
> 		if ( isset( $post->post_status ) && ( 'future' === $post->post_status ) ) {
> 			// set the post status to publish to get the 'publish' permalink
> 			$post->post_status = 'publish';
> 			$recursing = true;
> 			return get_permalink( $post, $leavename ) ;
> 		}
> 	}
> 
> 	$recursing = false;
> 	return $permalink;
> }
> ```
> 
> **To make scheduled posts published:**
> 
> ```
> add_action( 'pre_get_posts', function ( $q )
> {
>     if (!is_admin()) {
>         $q->set( 'post_status', ['publish', 'future'] );
>     }
> });
> ```

THANK YOU! This was driving me crazy! I had users that were trying to copy the permalink. If they clicked it, it took them to the "/?p=458" address, and if they right-clicked it and copied, they'd get a URL with "(opens in a new tab)" at end of it!

I dropped your code into my child theme's functions.php and it worked like a charm!
