### ISSUE TITLE
Add button to cover image

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2765]
This brings the button and options into the cover image block. It takes exactly the settings, including text and background color. The styling of the button is the same but as a default should be white background, black text - to reflect the header styling.

![coverimage-button](https://user-images.githubusercontent.com/253067/30747239-7d52c272-9fa4-11e7-842d-de9de1a2fa19.png)

**Comment by samikeijonen** [comment]
Yes! Very common design pattern. Is this first step towards nested blocks?

**Comment by mtias** [comment]
@samikeijonen hah, sort of, but not quite. This is more of a setting of the block. The first step for nesting is going to be #2743.

**Comment by samikeijonen** [comment]
Thanks for the info @mtias, will look the other ticket also.

**Comment by jorgefilipecosta** [comment]
Submitted PR https://github.com/WordPress/gutenberg/pull/3047.

**Comment by Soean** [comment]
@iseulde The PR for this ticket #3047 was closed because of nested blocks, should this ticket really stay in the 2.0 milestone?

**Comment by karmatosed** [comment]
@Soean this still would be a setting aside from nesting blocks. It should be a setting on cover image as a lot of people want it.

**Comment by melchoyce** [comment]
I'd maybe consider "Include button" instead of "Show button" here — what do you think?

**Comment by SuperGeniusZeb** [comment]
If #5452 is merged, this issue could probably be closed, as it would be trivial to insert a Button block into a Cover Image block via nesting.

**Comment by mtias** [comment]
Yes, that's the plan.

**Comment by karmatosed** [comment]
I am closing this as we are moving on with nested blocks which will include this.
