### ISSUE TITLE
InputControl Block causing React Error

### ISSUE THREAD

**Issue by AmandaMayfieldp202** [WordPress/gutenberg#27657]
**Describe the bug**
When attempting to use the InputControl Block, with the onChange referencing a function, I instead get an error

**To reproduce**
1. Inside a wordpress application, create a page
2. Add a block to that page and inside the block, put an InputControl
`<InputControl
  label='Search Input'
  value='Initial value'
  onChange={onSetSearch}
  />`
3. Have onChange reference a function of any kind
4. Look at the console on the edit page, where the error has been appearing. The error directs to a react page stating: "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object."

**Expected behavior**
I expect the InputControl to be able to recognize the function without the error, as it is not an object.

**Screenshots**
<img width="1587" alt="Screen Shot 2020-12-10 at 2 06 45 PM" src="https://user-images.githubusercontent.com/43324379/101824026-45f2c700-3af1-11eb-870a-6ef9cbcdf1bf.png">
<img width="922" alt="Screen Shot 2020-12-10 at 2 06 51 PM" src="https://user-images.githubusercontent.com/43324379/101824033-48edb780-3af1-11eb-8b22-d01185855f76.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? It's using the Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser: Chrome
 - Version 86.0.4240.198

**Comment by talldan** [comment]
@AmandaMayfieldp202 It looks like `InputControl` is experimental at the moment, so not recommended for use.

The error message is a bit obtuse, but when it occurs it's generally related to how the component is imported. Would you be able to share that bit of your code to help troubleshoot?

**Comment by priethor** [comment]
Let's close this issue as we are unable to replicate and the activity has stalled. Feel free to reopen if the issue resurfaces.
