### ISSUE TITLE
Custom fields on reusable block cannot be activated

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#27662]
**Describe the bug**
Custom fields on reusable blocks cannot be activated.

**To reproduce**
1. Go to '/wp-admin/post-new.php?post_type=wp_block'
2. Click on 'Preferences'
3. Scroll down to 'custom fields'
4. You can enable the custom fields but it seems isn't supported.

**Expected behavior**
If I click on enable custom fields I expect that they are enabled. If this is not supported, that option should be removed because is causing misleading and confusion.

**Editor version (please complete the following information):**
- WordPress version: [5.6.6]
- "default"

**Desktop (please complete the following information):**
 - OS: ['Windows']
 - Browser ['Chrome]
 - Version [ 87.0.4280.88 ]

I'm not sure why custom fields aren't supported on reusable block, however if they aren't supported the option should be removed in my opinion.

**Comment by jordesign** [comment]
Testing in WP 6.3 - patterns (replacing reusable blocks) _do_ support Custom fields, so this behaviour is now correct. Accordingly I'm going to mark this issue as resolved.
