### ISSUE TITLE
Add background and text coloring to button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2766]
Currently you can change the background on the button, this adds in the ability to add text or background. Note, this uses the same pattern as the paragraph block uses and the cover image will use when has a button.

![button-iterate](https://user-images.githubusercontent.com/253067/30745325-8bc1cba2-9f9d-11e7-920c-8aaf5e038e12.png)

**Comment by nic-bertino** [comment]
If this is to use the same UI pattern as paragraph, can we please get some consideration/feedback on changes proposed in #2381? There remain some accessibility concerns with the palette UI as it stands.

**Comment by karmatosed** [comment]
For now, I think adding then in a different issue working on that makes sense @nic-bertino

**Comment by jorgefilipecosta** [comment]
I can take care of adding this feature :)

**Comment by aduth** [comment]
@jorgefilipecosta Can this be closed now as of #3034?
