### ISSUE TITLE
Preformatted block collapses new lines when pasting in text

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#27660]
**Describe the bug**

Text copied in from outside sources is often wrapped in (hidden) HTML tags. When pasting this content into Preformatted or Verse blocks, the hidden tags seem to cause the text to lose its new lines and get pasted as a single line.

**To reproduce**
1. Copy a block of text from a lyrics site that contains hidden tags (on example is [here](https://www.lyrics.com))
2. Create a Preformatted or Verse block
3. Paste in the content
4. Notice that new lines are lost and the content is all on a single line (especially noticeable when previewing)

For reference, this is the output I see in the browser console:

```
 <pre id="lyric-body-text" class="lyric-body wselect-cnt">
If I woke up without ya
I don't know what I would do
Thought I could be single forever 'til I met you
Usually don't be fallin', be fallin', fallin' first
You got a way of keeping me comin' back to back
I just found out the only reason that you lovin' me
Was to get back at your ex lover but before you leave
Usually I would never, would never even care
Baby, I know she creepin' I feel it in the air</pre>
```

**Expected behavior**
New lines in pasted content should be preserved

**Screenshots**

| <img src="https://user-images.githubusercontent.com/1898325/101835093-07253700-3b1a-11eb-9560-49c354ee3513.gif" alt="">  |
| - |

**Editor version (please complete the following information):**
- WordPress version: `master` branch latest commit at time of writing e5b9df164254b1c1b08c082ae6659a0f8510dd79
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.5

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 83.0

**Comment by settenop** [comment]
The problem seems to be in this line:
https://github.com/WordPress/gutenberg/blob/138288fe58af451bcabc5d048cdcc8ebe5da6e62/packages/block-editor/src/components/rich-text/index.js#L471
content (as returned from pasteHandler) is a string in which lines are separated by newlines, the newlines are lost when content is passed to the create function as html.

Passing content as text could fix the bug (`let valueToInsert = create( { text: content } );`) for this specific case but I suspect we need a way to pick the right parameter (text or html).

**Comment by kathrynwp** [comment]
Looks like there was a PR fixing this issue early in 2021. @draganescu could you please confirm that this issue can be closed? Thanks very much!

**Comment by draganescu** [comment]
It's fixed to me! :)
