### ISSUE TITLE
get_block_wrapper_attributes checks for outdated __experimentalColor support

### ISSUE THREAD

**Issue by rafhun** [WordPress/gutenberg#27670]
**Describe the bug**
Serverside rendered blocks with support for colors do not generate the appropriate classes if colors are set.

**To reproduce**
1. Create any block with server side rendering, add support for color in its metadata.
2. Use `get_block_wrapper_attributes` in the render callback.
3. Check generated classes/styles

**Expected behavior**
Appropriate classes/styles should be generated.

**Reason**
`wp_apply_colors_support` checks for `__experimentalColor` instead of `color` when determining block support for color. See here: https://github.com/WordPress/WordPress/blob/master/wp-includes/block-supports/colors.php#L66
The classes get generated correctly if I add the `__experimentalColor` flag additonally in my `block.json` file.

```json
"supports": {
  "color": true
}
```
Above does not work, below works.
```json
"supports": {
  "color": true,
  "__experimentalColor": true
}
```

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Comment by nosolosw** [comment]
I prepared a fix for this at https://github.com/WordPress/wordpress-develop/pull/1068

**Comment by noisysocks** [comment]
Since the fix is in Core I've moved this to https://core.trac.wordpress.org/ticket/52709.
