### ISSUE TITLE
Improved UX for viewing saved page

### ISSUE THREAD

**Issue by bradley2083** [WordPress/gutenberg#27688]
**1) Update snackbar placement or change "preview" link to open preview on initial click**
Maybe I'm missing it somewhere, but after saving a page or post, the snackbar appears at the bottom left of the screen (when the save (update/publish) button appears opposite (upper right).  This UX drives me nuts.  Not sure why there isn't an obvious single button to click to preview / view the page.  The "preview" link in the toolbar requires the user to then make an additional click to see the actual front-end view of the page.

**2) Create keyboard shortcut to preview / view page**
Add a keyboard shortcut to preview or view the page and to open the edit screen so you can easily toggle between front-end and Gutenberg views with keyboard shortcuts.

**Comment by annezazu** [comment]
@bradley2083 Thanks for submitting this! You aren't the only one who agrees. This was previously opened here: https://github.com/WordPress/gutenberg/issues/25021 I'm going to close this out as a result in favor of that prior issue.
