### ISSUE TITLE
Add collapsing to block inspector

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2769]
We are starting to get a bit of an information river going on in the block inspector. This could get more and more as blocks grow, becoming more complex. I took some time this afternoon spurred to iterate. This design has props going out to @mtias and @folletto for the help.

The design takes what we have on the document inspector and iterates a little more minimally. Here for example is a mock up of the paragraph block:

![iteration-issue-sidebar-a-i](https://user-images.githubusercontent.com/253067/30759148-fb3d1a48-9fcc-11e7-9634-5665844a2e60.png)

**Comment by aduth** [comment]
Ideally this be implemented as part of the block's inspector rendering using existing [`<Panel>` components](https://github.com/WordPress/gutenberg/tree/master/components/panel) (same as used in the "Document" settings).

**Comment by mtias** [comment]
@aduth I was expecting that would just work. The only thing is that "advanced settings" (class name, anchor) should be already grouped under one.

**Comment by folletto** [comment]
One note: for space efficiency would be nice that collapsed adjacent elements had a smaller margin between them, while when open the gap gets bigger to signify better the panel margin.
