### ISSUE TITLE
Post title block: Enabling the link changes the position of the block.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#27694]
**Describe the bug**
When the "Make title a link" setting for the post title block is enabled, the block changes position
and is aligned all the way to the left in the editor.

This is because compared to the heading tag, the blocks `<a>` element is missing `display: block.`

**To reproduce**
1. Enable a theme that has support for full site editing, for example Twenty Twenty-One blocks.
2. In either the site or block editor, add a post title block-
3. In the block sidebar enable "Make title a link"
4. See that the block changes position.

**Expected behavior**
The blocks position should not be changed.

**Screenshots**

![The post title is aligned to the left in the editor](https://user-images.githubusercontent.com/7422055/101977029-f0323200-3c4a-11eb-833a-8839868bdaee.png)

**Editor version (please complete the following information):**
- WordPress version: Version 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg version 9.5.2.

**Desktop (please complete the following information):**
 - OS: Windows 10, PC
 - Browser: Chrome Version 87.0.4280.88

**Comment by settenop** [comment]
`display: block` on the `a` element would solve this problem, but i think the missing rule isn't the root of this problem.
What is displayed in the editor is different from what is rendered in the frontend, if the `post-title` attribute `isLink` is true the editor will show it as `a > tagName` (`tagName` can be any of `p, h[1-6]`) while the frontend will render as `tagName > a`.

In my opinion applying `display: block` to the `a` element would add inconsistence to an already inconsistent behaviour, the problem should be solved rendering as `tagName > a` in the editor too, is it possible? It seems that the `PlainText` component used by the `post-title` block can't be used to type in inline tags, also, having it inline would require a way to focus it when the user interacts with a surrounding `display: block` element.

**Comment by jasmussen** [comment]
Potentially related: #29619
