### ISSUE TITLE
Pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior

### ISSUE THREAD

**Issue by jd-alexander** [WordPress/gutenberg#27690]
**Describe the bug**
When you create a Pullquote or Quote and you press enter multiple times in the middle of the block's content it starts moving the cursor a character forward and then it puts that character on a new line. 

**To reproduce**
1. Open the Mobile Editor. 
2. Add a Quote or Pull Quote block to the canvas. 
3. Enter a paragraph of text. 
4. Place the cursor in the center of the content. 
5. Press enter multiple times. 
6. Notice that each time you press enter and a new line is created, the cursor is moved after the character. 

**Expected behavior**
The cursor shouldn't be moved at all. When you press enter in front of any text and the new line is created the cursor should be in front of the content. 

**Screenshots**
Pullquote | Quote 
--------|-------
<kbd><img src="https://user-images.githubusercontent.com/1509205/101722952-42bbf480-3a79-11eb-9cb5-1181b35a0295.gif" width="320"></kbd>        | <kbd><img src="https://user-images.githubusercontent.com/1509205/101722959-48b1d580-3a79-11eb-889b-ee9acce6c0e5.gif" width="320"></kbd>

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 11
 - Version : WP Android alpha-261 - Gutenberg Mobile 1.43

**Comment by fluiddot** [comment]
👋 I'm not sure if it's related to the device but I can't manage to reproduce it on my device, here is a video capture:

https://user-images.githubusercontent.com/14905380/106909551-b2103680-6700-11eb-9008-d17e36df4d69.mp4

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S20 FE 5G
- OS: Android 10
- Version: WordPress for Android - Pre alpha - Build 94309

**Comment by AmandaRiu** [comment]
Tested on a physical device (pixel 4) on Android 11 using the Gboard. Issue is no longer happening:

Tapping each letter:

https://user-images.githubusercontent.com/5810477/125337526-1de47400-e31d-11eb-9a5d-f2d42ec6b195.mp4

Swiping words:

https://user-images.githubusercontent.com/5810477/125337547-2472eb80-e31d-11eb-9f8a-d34239cd00b8.mp4

I think we are good to close this one.
