### ISSUE TITLE
Color picker iteration

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2770]
We have currently 2 different color pickers: the paragraph users one and button another. They vary a little enough that it spurred thinking about what iterations could happen with the color picker. Design props go to @folletto and @mtias for helping.

A few points:
- You can see the color selected easily without digging into things.
- Removed the word 'color' as it's obvious from title.
- With moving 'clear' and the picker to text we have space for 2 more colors in the palette for themes.

An attempt was made to merge the colors to background / text, however this label could get complicated for non-English languages. Splitting colors like this works.

This mock shows the iteration on sidebar noted in #2769 and the cover image improvements in #2766 

![iteration-issue-picker-a-i](https://user-images.githubusercontent.com/253067/30759426-022cde50-9fce-11e7-9cfc-0229eef7c0f2.png)

![iteration-issue-picker-a-ii](https://user-images.githubusercontent.com/253067/30759442-1049e15e-9fce-11e7-9925-3c9804d9b597.png)

**Comment by jorgefilipecosta** [comment]
Given the merge of https://github.com/WordPress/gutenberg/pull/3054, I think this one can be closed.
