### ISSUE TITLE
Columns number reset to 3 in gallery settings

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#27706]
**Describe the bug**

[Reported on Trac](https://core.trac.wordpress.org/ticket/52000)

When number of columns in Gallery block is changed before images have uploaded, it gets reset to 3 columns.

**To reproduce**
1. Add a gallery block
2. Upload 12 images at once
3. Before they finish uploading, open block settings and set number of columns to 8
4. See number of columns reset to 3 while images are still uploading

Note: it doesn't happen if the images are added from the media library, only during upload.

**Expected behavior**

Expected column number to not change after being set.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? with or without plugin; can reproduce in latest master.

**Comment by lukecarbis** [comment]
I've tested this problem in Gutenberg 9.5.2 and WordPress 5.6, and can replicate the issue in both.

**Comment by glendaviesnz** [comment]
This still happens with the [new gallery format merged](https://github.com/WordPress/gutenberg/pull/25940).

**Comment by Salimoh** [comment]
I am having similar problem. I set columns to 3. After publishing they become two.

**Comment by glendaviesnz** [comment]
> I am having similar problem. I set columns to 3. After publishing they become two.

@Salimoh I wasn't able to replicate this. Can you please provide some details about the version of GB and WP that you experience this issue on, and also a screen recording of the workflow if possible.

**Comment by glendaviesnz** [comment]
@tellthemachines I wasn't able to replicate this now on GB trunk:
![gallery-columns](https://user-images.githubusercontent.com/3629020/149681894-f0f3fe77-ab8c-467c-a196-24f303582ac3.gif)


Do you still see it on trunk?

**Comment by tellthemachines** [comment]
I can no longer reproduce it either; closing.

**Comment by amitsarkerr** [comment]
The worst editor is Gutenberg.
I started hating WordPress after using this full of bugs editor functions.
