### ISSUE TITLE
[Know-how] Images with button + text

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#27701]
What existing Gutenberg blocks can be used for achieving this?

Multiple images that are aligned in a grid, each with a button.
Images and containing buttons should be aligned vertically, for the images in the same row.

**Comment by kjellr** [comment]
Hi there! Can you explain a little more about what you're trying to achieve here? It sounds something like this, which is achieved by placing image and button blocks inside of a columns block: 

![Screen Shot 2020-12-14 at 11 59 08 AM](https://user-images.githubusercontent.com/1202812/102111324-3da5cf00-3e04-11eb-85d7-9b2eeff58341.png)

Each column has a setting to help align its inner content that would come in handy here: 

![Screen Shot 2020-12-14 at 12 03 27 PM](https://user-images.githubusercontent.com/1202812/102111457-6a59e680-3e04-11eb-8d3f-d3242f8eac48.png)

**Comment by Thelmachido** [comment]
There hasn't been much movement on this issue in a while and it has been stale for a few months. I’m going to go ahead and close out this issue since there hasn’t been any activity on it in If anyone feels it should still be looked at, please feel free to re-open the issue.
