### ISSUE TITLE
Method to get the template directory URI in Gutenberg

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#27719]
I've searched all over and can't seem to find how to do this. Maybe I'm missing something obvious.

I’m creating a custom Gutenberg block. I’m looking for a way to get the template directory URI within that Gutenberg block. Specifically I want to use an image in the theme directory as part of an [`example`](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#example-optional), but for obvious reasons I don’t want to hard code the full site URLs. Essentially I am looking for a Gutenberg equivalent to [`get_template_directory_uri()`](https://developer.wordpress.org/reference/functions/get_template_directory_uri/).

**Comment by JordanPak** [comment]
It'd be cool to have this sanity-checked, but I had to gather some information like this and make it accessible within my editor scripts too. I ended up localizing a global variable containing the information that I needed, like this:

1. Register and enqueue your editor/block JS:
```php
wp_enqueue_script(
    'whatever-plugin-editor',
    'path/to/your/editor/js/whatever.min.js',
    [ 'wp-blocks', 'wp-whatever', 'wp-whatever-else' ], // or your asset.php thing if using @wordpress/scripts
    PLUGIN_VERSION_CONST_OR_SOMETHING // or your $asset['version'] thing if using @wordpress/scripts
);
```

2. Localize your var (this can be right after your script registration/enqueue but I don't think it matters as long as it's called before your actual script gets printed)
```php
wp_localize_script(
	'whatever-plugin-editor',
	'yourPluginsLocalizedVariableName',
	[
		'templateDirectoryUri' => get_template_directory_uri(),
	]
);
```

3. Use the var in your editor/block JS
```javascript
const { templateDirectoryUri } = yourPluginsLocalizedVariableName;

console.log( `Ok G the template directory URI is ${ templateDirectoryUri }` );
```

For reference, I had to localize an object containing:

- the plugin's directory path
- the plugin's directory URI
- the current post's top level parent post ID
- some custom post type keys

**Comment by annezazu** [comment]
@philbuchanan this is more of a support request than bug or enhancement request. As a result and, since @JordanPak  so helpfully replied, I'm going to close this out! The best place to get help for these sorts of things going forward is the forums: https://wordpress.org/support/forums/
