### ISSUE TITLE
Ability to add featured images by URL

### ISSUE THREAD

**Issue by Nic-Sevic** [WordPress/gutenberg#27711]
**Describe the solution you'd like**
A customer would like to be able to add featured images to their site by linking the URL rather than uploading the image to the media gallery.

**Describe alternatives you've considered**
They are aware that they can use image blocks to link to a URL but specifically want to be able to do so through the featured image.

**Is your feature request related to a problem? Please describe.**
I believe the customer is wanting to save on media gallery space by not uploading the images.

**Comment by talldan** [comment]
Previously reported in https://github.com/WordPress/gutenberg/issues/15039
