### ISSUE TITLE
Add padding controls to core/latest-comments

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#27723]
**Is your feature request related to a problem? Please describe.**
In order to fully support the [Latest Comment Style in TT1-blocks](https://github.com/WordPress/theme-experiments/issues/122) regarding the Global Style Editor the [Latest Comments block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/latest-comments) should support padding controls.

**Describe the solution you'd like**
* The support.spacing.padding value set on the block to allow Block Editor to control padding values.
* The BoxControlVisualizer added to the block's 'edit' module so the spacing can be visualized.

**Comment by carolinan** [comment]
I am not sure if we want to do this?
It may be solved by https://github.com/WordPress/gutenberg/pull/29402/files, 
because this is what the style in Twenty Twenty-One overrides.
