### ISSUE TITLE
Audit acessibility of BoxControl component used for controlling padding

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27728]
**Description**
I noticed a few accessibility issues with this component (#27727 adds some labels to inputs/buttons), and I think there's more that can be done.

Some of my thoughts:
- Is it clear enough what the 'Link/Unlink Sides' button does? How can this be improved?
- The Top / Left / Right / Bottom buttons all have labels, but is it clear enough what they all do?
- The enclosing `div` has `aria-labelledby`, which in VoiceOver leads to the text 'Padding' being announced as a group label, even though it does. Is there a more semantic option, like using a `fieldset` to provide more context to the individual fields?
- When discussing this, @tellthemachines mentioned that the 'PX' text is quite small.

**To reproduce**
1. Add a Group block
2. Navigate to the Padding setting in the block settings sidebar.

**Comment by tellthemachines** [comment]
One other thing we might want to change is the position of the "Reset" button. It makes more sense to have it after the other controls, and that's also more consistent with its placement in the typography and color settings panels.

**Comment by talldan** [comment]
Closing as outdated. I think other issues have been made that supercede this.
