### ISSUE TITLE
Formatting Icons

### ISSUE THREAD

**Issue by fisicx** [WordPress/gutenberg#2772]
This may have already been raised but I couldn't find a thread.

When authoring and moving between blocks the floating iconbar displays above each block and hides the preceding content. There doesn't appear to be a way to disable the bar until I want to change the content format.

There no longer appears to be a 'more' icon

To change a block to a header now takes 3 actions where it used to be just two.

Ideally I wold like the option to disable the floating iconbar and have a fixed icon bar at the top of the editing area - the same as just about every other authoring tool.

**Comment by mtias** [comment]
There is now a fixed toolbar for blocks.
