### ISSUE TITLE
Navigation Block overwrites link text on selection from search

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#27738]
I created a menu within a page to add anchor links for readers. I added a button and typed the link text, and then search for the right page to link to. Once I made the selection it also replaced the link text with the whole title of the page, and I had to add the text again. 

1. Add a navigation block
2. Add a link and type the link text
3. Now use the link button from the toolbar 
4. Search for the right page 
5. it will replace your already added text. 

I expect the block to respect the existing text and not replace it. 

![navigation-link-overwrite-text](https://user-images.githubusercontent.com/39980/102219001-dd1e9c80-3eac-11eb-867d-5397b97de9af.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg 9.5.2

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser : Google Chrome 
 - Version: 87.0.4280.88

**Comment by rafaelgalani** [comment]
I was able to reproduce it locally, but when debugging, I found out that the overwriting was due to #19461 (which closed its parent issue)... So I'm not sure if this is the intended behavior. 
However, https://github.com/WordPress/gutenberg/issues/18695#issuecomment-558738947 pointed out: 
>_If I’d manually changed the label, I’d see maybe keeping it._

If that's the intended behavior, then it's a bug. Otherwise, no. @tellthemachines @melchoyce WDYT?

**Comment by mkaz** [comment]
From testing, I think this can be closed as the flow for adding a Custom Link has changed. Now when adding the link, you get first prompted to select the page or URL, before adding the text.

![navigation-block-link](https://user-images.githubusercontent.com/45363/126190641-86944739-de5d-4b24-bebe-433607075f9f.gif)

Can you confirm it is resolved from latest versions ? Thanks!

**Comment by bph** [comment]
Sorry, I am traveling and didn't get to retest this yet. @mkaz it's on my to-do list, though

**Comment by bph** [comment]
The new user flow of adding a custom link seem to work well. It prevents the idea to add the link text before the URL. I could edit the link text after I added the Custom link to a navigation menu. 

Closing this issue as fixed.
