### ISSUE TITLE
A missing/unregistered block in a template crashes the post editor

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27731]
**Describe the bug**
This bug was spotted on the WordPress forums - https://wordpress.org/support/topic/block-templates-using-reusable-blocks/#post-13785833

If a template references a missing block (e.g. one provided by a plugin that was installed and then uninstalled), the post editor crashes (with a blank screen, no error message), with a console message that states:
```
Uncaught (in promise) Error: Block type 'core/dan' is not registered.
    createBlock factory.js:50
    synchronizeBlocksWithTemplate templates.js:117
    Lodash 2
    synchronizeBlocksWithTemplate templates.js:59
    setupEditor$ actions.js:54
    tryCatch wp-polyfill.js:6517
    invoke wp-polyfill.js:6746
```

Seems like this should probably just show the Missing block

**To reproduce**
1. Create a template referencing a block that doesn't exist. For this I used the custom post type example from the block editor handbook and changed one of the block names to 'core/dan':
```php
function myplugin_register_book_post_type() {
	$args = array(
		'public'       => true,
		'label'        => 'Books',
		'show_in_rest' => true,
		'template'     => array(
			array(
				'core/dan',
				array(),
			),
			array(
				'core/heading',
				array(
					'placeholder' => 'Add Author...',
				),
			),
			array(
				'core/paragraph',
				array(
					'placeholder' => 'Add Description...',
				),
			),
		),
	);
	register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```
2. Create a new 'book' post type
3. Observe a blank screen

**Expected behavior**
I think ideally the 'missing' block could be shown. 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? 9.5.2

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox

**Comment by ntsekouras** [comment]
Duplicate of: https://github.com/WordPress/gutenberg/issues/21718

@talldan should we close this one as the other have more context?

**Comment by talldan** [comment]
Thanks Nik, I searched by somehow didn't find that one. I'll close this.
