### ISSUE TITLE
Rename main branch to `trunk`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/gutenberg#27741]
### Background

The decision to rename the main branch of WordPress git repositories from `master` to `trunk` was made in this make post: https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/

This issue is not to discuss whether this should be done or what new name to use. Those discussions should stay in the make post linked above 🙂

This issue is, however, meant to propose a step-by-step process for updating the WordPress Gutenberg repository to use `trunk` as its main branch name.

### Prior Art

https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/

https://github.com/github/renaming

https://github.com/Automattic/wp-calypso/tree/trunk/packages/retarget-open-prs

### Approach

There are two approachs that can be taken. One I'm calling the "manual" approach (described below) and the other is the "wait for Github" approach. The "wait for Github" approach will require the same prerequisites, however we would wait for [Github to release the magic tools they write about here](https://github.com/github/renaming). Unfortunately there is no timeline for those tools other than "the end of the year" which is quickly approaching. I don't think we should bank on these tools becuase we don't know how Github is prioritizing their creation. Furthermore, we can do the process ourselves with little extra effort (at least given that we have a script to retarget open PRs).

#### Prerequisites

1. We need a PR that updates all references from `master` to `trunk` in CI and other scripts
2. We need to select a date to perform this migration
3. We need to delegate someone (or multiple people to pair on it) with the required repository permissions to perform the steps below. One person should be delegated to run the git commands for creating and deleting the master branch.

#### Steps

1. On the selected date, freeze merges to the Gutenberg repository's main branch by requiring the maximum of 6 reviewers to merge a PR into the main branch. This effectively blocks anyone from merging during the period of time where we're performing the migration. We need to do this in order to prevent the new `trunk` branch from falling behind the HEAD of the repository's main branch.
2. Run `git branch -m master trunk`. This creates a new `trunk` branch with the same history as `master`.
3. Run `git push -u origin trunk`. This pushes the new `trunk` branch to Github.
4. Add a new rule to the Github branch protection settings for the new `trunk` branch and copy all the settings from the `master` branch configuration over to the `trunk` branch's rules. This will be done here: https://github.com/wordpress/gutenberg/settings/branches (requires appropriate repository permissions to access the link)
5. Change the default branch in Github (https://github.com/wordpress/gutenberg/settings/branches) to be the new `trunk` branch.
6. [Run the script to retarget PRs open against `master` to `trunk`](https://github.com/Automattic/wp-calypso/tree/trunk/packages/retarget-open-prs). Example: `node retarget-open-prs/cli.js -o=WordPress -r=gutenberg -f=master -t=trunk --access-token=<ACCESS_TOKEN>`
7. Merge the PR updating references from `master` to `trunk` into `trunk`.
8. Unprotect the `master` branch in Github.
9. Delete the `master` branch by running `git branch -D master; git push origin --delete master`
10. Unfreeze the repository's merges by removing the approval requirements from `trunk`.

After this the `master` branch will no longer exist. Contributors will need to run the following script to fix their existing local clones:

```
$ git checkout master
$ git branch -m master trunk
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/trunk
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/trunk
```

Open PRs may have to be rebased against `trunk` if CI is failing.

This process mirrors the process I followed to successfully update the rather large and complex Automattic/wp-calypso repository for the same change. During that change, the `retarget-open-prs` script was used to safely retarget nearly 300 open PRs.

**Comment by gziolo** [comment]
> We need a PR that updates all references from master to trunk in CI and other scripts

I think it also includes documentation which might require some work to make it happen. 

There are 569 open PRs, but many of them aren't up to date anyway. If we want to run some automation that comments on all PRs and explains the steps planned. It should include the deadline for updating the branch with the latest changes from `master`. I would seriously consider ignoring all PRs that won't get updated on time preventing the automated branch retargeting to happen.

It might get more tricky with all PR submitted from forked repositories as it seems to be a manual process, but as long as we are able to include a note in the comment that helps people to run those commands, it should be fine.

**Comment by saramarcondes** [comment]
> I think it also includes documentation which might require some work to make it happen.

Is that some work with docgen in particular or do you just mean links like these:

https://github.com/WordPress/gutenberg/blob/69bf4e6aea0f64b26537ff1cc59857b5167a48f3/packages/block-editor/src/components/block-preview/index.js#L51

From my experience links of this nature, pointing to a specific branch, are actually unnecessary. We can update links like that to point to HEAD instead:

https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/block-preview/README.md

This can be done at any time before the migration.

> There are 569 open PRs, but many of them aren't up to date anyway. If we want to run some automation that comments on all PRs and explains the steps planned. It should include the deadline for updating the branch with the latest changes from master. I would seriously consider ignoring all PRs that won't get updated on time preventing the automated branch retargeting to happen.

I think it's a good idea to also include a comment on the retargeted branches saying something along the lines of "Hi! You might have noticed that your PR was automatically updated. Don't worry, this is intentional. Please visit <link to an issue describing steps to rebase branch and fix local clones> for more information. Thanks!"

Why is it necessary to create a deadline though? Retargeting those PRs is completely free and PRs that are up to date with the latest `master` won't need to be rebased against `trunk` at all. Out of date PRs probably need a rebase and some other love regardless. I'm not fully understanding the goal in mind with the deadline 🙁 

Should I submit a PR to update the `retarget-open-prs` utility to support leaving a comment on the PRs for this purpose?

**Comment by gziolo** [comment]
> Why is it necessary to create a deadline though? Retargeting those PRs is completely free and PRs that are up to date with the latest `master` won't need to be rebased against `trunk` at all. Out of date PRs probably need a rebase and some other love regardless. I'm not fully understanding the goal in mind with the deadline 🙁

The goal would be to close PRs that are very old and weren't updated as abandoned. Nothing more than that.

> Should I submit a PR to update the `retarget-open-prs` utility to support leaving a comment on the PRs for this purpose?

I'm personally fine with that, but I would wait to hear from other folks first. It's something that might need to be discussed during the weekly Core Editor chat.

**Comment by saramarcondes** [comment]
@gziolo Do you mind bringing this up at the core editor chats? They happen a little too early in the day for me to be able to attend (and be lucid).

**Comment by ceyhun** [comment]
I just saw this new feature and thought it might be helpful: https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

**Comment by aristath** [comment]
> I just saw this new feature and thought it might be helpful: https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/. Maybe it can help eliminate some of the steps.

I think it would eliminate **all** steps... Even redirects are now automatic so it looks like we can move forward with this? Can anyone see anything missing from that github post?

**Comment by gziolo** [comment]
Can we wait with everything until we are ready with WordPress 5.7 beta 1, it's in 2 weeks or something like that 😄 

It's great to see that now the process is automated by GitHub 💯

**Comment by saramarcondes** [comment]
In the mean time I’ll try it out on my own repositories and see how it works. Do we truly not even have to update the branch references in CI scripts? That would ease the process an incredible amount (though I would still advocate for removing that language from those scripts as much as possible).

@gziolo shall we open a separate ticket for cleaning up very old staled PRs? It seemed like you were hopeful we could address that as the same time as this but if we’re not running a script to modify every open PR anymore (no need with the GH provided utility) then I don’t think that can be part of this project anymore.

**Comment by gziolo** [comment]
> shall we open a separate ticket for cleaning up very old staled PRs? It seemed like you were hopeful we could address that as the same time as this but if we’re not running a script to modify every open PR anymore (no need with the GH provided utility) then I don’t think that can be part of this project anymore.

No worries, there's been discussion on the same topic in the official WordPress Core blog: https://make.wordpress.org/core/2021/01/14/stale-issues-in-gutenberg-repository/. I hope it will end up with some actions that will help identify those stale PRs that won't merge without refreshing the branch.

**Comment by saramarcondes** [comment]
@gziolo Are we able to do this now?

**Comment by gziolo** [comment]
I would prefer to confirm with @noisysocks who is leading the editor side of the WP 5.7 release. It feels like we could run the process now 👍

**Comment by noisysocks** [comment]
I'm OK with doing this now.

**Comment by saramarcondes** [comment]
Wonderful! Who has the correct permissions to do this and what's the best way to coordinate this change at this moment?

**Comment by gziolo** [comment]
Do we have PRs that update all GitHub workflows, release scripts, documentation pages and other code references to use `trunk`?

We might also need to point the Block Editor handbook to the new branch. @mkaz or @chrisvanpatten  should know the exact place where to check it. 

I can't think of anything else but I guess we will learn about it soon. 

I will check if I have access to this feature and let you know.

**Comment by saramarcondes** [comment]
Yes, I opened a draft PR here to update all scripts and everything else that was left over from my two link update PRs: https://github.com/WordPress/gutenberg/pull/28433

**Comment by mkaz** [comment]
The script that imports to the developer handbook is here: https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/inc/import-block-editor.php

Or at least that is a mirror of the script, a Trac ticket or request in #meta, can get it updated.

**Comment by saramarcondes** [comment]
@gziolo Do you have access to the branch rename feature, do you think we could do this this week?

**Comment by gziolo** [comment]
@sarayourfriend, I asked in the #core-editor channel on the WordPress Slack if someone wants to take care of it (link requires registration at https://make.wordpress.org/chat/):

https://wordpress.slack.com/archives/C02QB2JS7/p1613138723496800

**Comment by sarayourfriend** [comment]
@gziolo It doesn't seem like anybody raised their hand to work through the process. Any chance we can bug someone in particular who may be able to do it?

**Comment by sarayourfriend** [comment]
To close the loop, @youknowriad has volunteered to coordinate the process with me. We'll be performing the branch renaming at 1430 UTC, 1 March 🎉
