### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by fisicx** [WordPress/gutenberg#2774]
While not necessarily a Gutenburg issue, if the way posts are being created in future becomes content blocks can we not have a way to add SEO page titles and descriptions. It's pretty much core functionality for any SEO activity and sadly missing from WP

**Comment by ManuelSLemos** [comment]
It's a good idea!

**Comment by karmatosed** [comment]
Whilst I can see the need for this, Gutenberg is just the editing experience as a focus. To add things like SEO and other functionality already in plugins, is out of the v1 spec. This is not saying it can't be added by a plugin (like now) or at some point be looked at as an enhancement to core (which would be more appropriate than adding to Gutenberg.
