### ISSUE TITLE
Comments Form: Convert button to Button Block

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#27740]
**Is your feature request related to a problem? Please describe.**
Buttons within the Comment Form block need custom CSS because they can't be styled using Global Styles. See https://github.com/WordPress/theme-experiments/issues/114

**Describe the solution you'd like**
I think the button in the Comments Form should be an implementation of a Button block.

**Comment by mtias** [comment]
This should be absorbed with the elements API for buttons.
