### ISSUE TITLE
Heading Icon causing confusion in editor

### ISSUE THREAD

**Issue by thewebprincess** [WordPress/gutenberg#27750]
**Is your feature request related to a problem? Please describe.**
I find the use of the bookmark icon to denote the heading to be super confusing. I had cause to want to change an errant heading back to a paragraph and almost had to google how to do it because this icon does not say heading to me, it says 'save' or 'bookmark' - It wasn't until I looked at another block and noted the pilcrow denoting the paragraph block that I realised my mistake. 

![Screen Shot 2020-12-16 at 5 16 54 pm](https://user-images.githubusercontent.com/2251377/102312419-cb2f1d80-3fc2-11eb-9579-e8ad88da0463.png)

**Describe alternatives you've considered**
It seems to me than in every other instance in which we're talking about headings they're denoted with a capital **H** While I realise this is specific to English - it is also specific to HTML I feel like there ought to be a way to do it without co-opting an icon that is commonly used in other contexts and therefore causes confusion when being used in this way.

**Comment by ocean90** [comment]
This was also mentioned in #24168.

**Comment by hedgefield** [comment]
Good point. I tried to put together a few ideas - there aren't a lot of icons out there that scream "heading"! I tried two from Material that kind of evoke the semantic hierarchy, but maybe in the end 'H' is still the clearest.
I wasn't a super big fan at first, since as you said: it's an english letter, but it's true that the HTML spec uses H1-H2-H3 etc explicitly, as do we in the UI already to specify the heading level actually, so it should be fine. Inspired by [this icon](https://material.io/resources/icons/?search=size&icon=format_size&style=baseline) I also tried a variation of the H to indicate the levels a little more.

![headings](https://user-images.githubusercontent.com/6073772/105158462-48900580-5b0e-11eb-8a41-95d92d2c6c9e.jpg)

**Comment by thewebprincess** [comment]
Thanks @hedgefield -Reinventing the wheel and making users have to think about what they're trying to do instead of just getting on with it is alienating. While creating a new icon to represent a heading in something like WordPress given its marketshare could in fact eventually usher in a new default (much the same as the bookmark/save icon has become), I strongly suggest sticking with the status quo. Using an H has become synonymous in other apps (Notion for example) and either of your options related to that would, from my perspective, reduce the ambiguity I was frustrated by. Thank you.

**Comment by hedgefield** [comment]
I agree. I think the H is pretty commonplace and safe to pick, let's go with that then :) @noisysocks can you tell us what is needed to carry out this icon replacement? Do you think it's possibly to get it in before 9.9?

**Comment by paaljoachim** [comment]
Adding in some older and closed Heading discussion issues/PR:
https://github.com/WordPress/gutenberg/issues/522
https://github.com/WordPress/gutenberg/pull/9159

Joen @jasmussen  will likely have some comments on this issue.

Hmm I am not able to find an issue from 2-3 years back where I added a lot of different Heading icons.

**Comment by jasmussen** [comment]
Thanks for the ticket. "H" is for "Heading", which works well for english, but is meaningless outside english speaking countries, and as Paal notes, we also tried it in the past. The bookmark harkens back to the table of contents usage of headings as anchors across a web-page. 

The feedback is valid, and if we find a better design than the bookmark, I'd be happy to change it.

So as to consolidate things, though, I'm going to close this one in favor of #24168. I'll label both with "Icons" so they don't disappear.
