### ISSUE TITLE
Media Replace Popover overflows in Chrome

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#27753]
**Describe the bug**
When trying to change the image in a the`core/image` block the `MediaReplaceFlow` component has a horizontal scroll bar and is overflowing the popover. 
<img width="644" alt="Screen Shot 2020-12-16 at 10 03 04" src="https://user-images.githubusercontent.com/20684594/102327602-42928c00-3f86-11eb-8c6f-75aac7eaa64e.png">

**To reproduce**
1. Go to any page / post
2. Click on insert and add an image block 
3. Choose an image
4. Click "Replace Media" in the toolbar. 
5. See the component overflowing. 

**Expected behavior**
The Popover should not have any horizontal scroll and should not be clipped of.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser Google Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by talldan** [comment]
Thanks for reporting, this was already reported in #27186, so I'll close this one.
