### ISSUE TITLE
Cannot undo image resizing

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2775]
Once I have resized an image, there is no way to remove the fixed size to let it be responsive again. I guess I would expect there to be an option responsive/fixed, that automatically switches to fixed if you start resizing.

Similarly, with image resizing enabled, I'm a bit afraid that users will resize an image back to what looks like full-width and then think it's full-width. In reality that won't be the case if the image is displayed in a box that has a different width. I wonder if it might be more interesting to have preset responsive sizes.

**Comment by mtias** [comment]
This works now.

**Comment by aduth** [comment]
In what way is this working? It's unclear to me how to remove custom sizing from an image which had been previously resized.

Raised by @bobbingwide 

Reopening in case it's still not possible; unsure if the original issue was related specifically to Undo/Redo, but it seems reasonable to me we should want to allow a user to unset the custom size when editing a post at a later date (i.e. when Undo history doesn't apply).

**Comment by mtias** [comment]
Using alignment buttons can reset the resizing. Might be worth adding a button on the inspector for it. cc @jasmussen

**Comment by jasmussen** [comment]
It doesn't seem like you can unset the resizing in the classic editor, or at least I couldn't find a way:

![imagesizing](https://user-images.githubusercontent.com/1204802/37082631-55a510d8-21ed-11e8-8795-3c8cd8458cbe.gif)

That's not to say we can't do better in Gutenberg, we certainly can. Here are some mockups [created for a pull request](https://github.com/WordPress/gutenberg/pull/5269#issuecomment-369154750):

<img width="901" alt="screen shot 2018-03-07 at 09 53 42" src="https://user-images.githubusercontent.com/1204802/37082712-884e6034-21ed-11e8-8ddc-b2dc0e77a915.png">

In this, you have additional inspector options for images. There are explicit dimension input fields, quick shortcuts to set scaling sizes, and a button to reset the size.

**Comment by mtias** [comment]
Yes, let's go with that.

**Comment by bobbingwide** [comment]
I  must be missing something here.
1. Joen said he couldn't find a way with the classic editor. Even though the image does not appear to change inside the editor, saving and viewing shows that the image size does get changed. Switch to text view.
2. What does "Let's go with that" mean? 

Perhaps you could explain to me what a status of Closed means for this project.

**Comment by jasmussen** [comment]
@bobbingwide Matías was a bit brief in his comment there. He forgot to suggest the reason for closing, which was to consolidate tickets. Turns out there's already a ticket that touches on this same issue: https://github.com/WordPress/gutenberg/issues/4914
