### ISSUE TITLE
Cannot view/edit images on demo page

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2776]
Apologies if already posted.

When I'm on the demo page, there is no way to view/edit the images. If you click the edit button, the image does not appear in the list. I see in the DOM tree it's a hot-linked Cloudup image, but I'm not able to see the URL either.

**Comment by perandre** [comment]
I am able to click the pencil icon to replace the image. https://cloudup.com/cgVwQFfVWyG

**Comment by iseulde** [comment]
@perandre Yes, but I don't see a way to edit the URL or see the image in the media library.

**Comment by mtias** [comment]
I say let's close this as the demo is only a tool during the plugin phase.
