### ISSUE TITLE
Improve call to write on add button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2777]
Currently the button says:

![2017-09-24 at 16 14](https://user-images.githubusercontent.com/253067/30783931-825ce0c2-a143-11e7-9a63-09be3dce6240.png)

It would be better to have something like:

![2017-09-24 at 16 13](https://user-images.githubusercontent.com/253067/30783929-792576b8-a143-11e7-8fe4-e86216956c93.png)

**Comment by ChrissiePollock** [comment]
This is picky, but the Add text button is still not intuitive. It would be helpful if the words disappeared when a write clicks in the Add Text section. People are clicking and don't see the cursor (black on black) so they don't try to type to see that their new text will override.
