### ISSUE TITLE
Quick Inserter: use inset border and rbga color value

### ISSUE THREAD

**Issue by rickybanister** [WordPress/gutenberg#27772]
The quick inserter has a standard border (outset) that is #ccc.

With the addition of the 'browse all' button in black at the bottom it creates an unfortunate fuzz between the black button, the gray border, and the black box shadow:

![image](https://user-images.githubusercontent.com/437258/102415836-df751980-3fc6-11eb-916d-dbe828f47cf3.png)

We should instead use an inset border like `border: 1px inset rgba(0,0,0,.05);` (or some other decimal value of black that's close to #ccc). The inset border overlaps the black button and the alpha property makes the border invisible on top of it.

Which looks like this:

<img width="174" alt="Screen Shot 2020-12-16 at 5 44 26 PM" src="https://user-images.githubusercontent.com/437258/102415870-ec920880-3fc6-11eb-8d1a-f7845abfe39e.png">

It's just a bit cleaner.

**Comment by pablohoneyhoney** [comment]
Makes sense. The darker area should not have the #ccc border visible, it wasn't intended that way initially, anyhow.

**Comment by sonu-mittal** [comment]
Can I work on this @talldan?

**Comment by himanshu211raj** [comment]
Is this task assign to me?
