### ISSUE TITLE
 getEntityRecords() for 'attachment' post type no longer works with Wordpress 5.6

### ISSUE THREAD

**Issue by korynorthrop** [WordPress/gutenberg#27771]
**Describe the bug**
I have been making use of getEntityRecords() to fetch image data to display in some custom Gutenberg blocks. They worked fine until I upgraded to Wordpress 5.6. Now when I make calls with getEntityRecords() I get the following errors:
"Uncaught TypeError: fe(...) is null"
"Uncaught (in promise) TypeError: fe(...) is null"

However, I can successfully fetch image data by using getMedia(). This was the behavior I experienced on my live and staging sites. I deactivated all plugins and changed to Twentytwentyone theme and still had the issue. So I installed a fresh copy of Wordpress locally and went through the following steps, which produced the error as well.

**To reproduce**
1. Make a clean Wordpress installation
2. Upload an image to the media library and take note of it's post_id (let's say it's `6`)
3. Open the page editor and the Javascript console then type in `wp.data.select('core').getEntityRecords('postType', 'attachment', { include: 6 })`
5. Instead type in `wp.data.select('core').getMedia(6)` (you'll likely get 'undefined' the first time while it's fetching the media item, but if you re-enter you should be able to see the details for that image)

**Expected behavior**
I expected to be able to continue using getEntityRecords() within my custom blocks like I did before. I noticed that a similar error would occur fetching pages (e.g. `wp.data.select('core').getEntityRecords('postType', 'page', { include: 3912 } )`) but if I passed the post_id as a string in the query parameter it works (e.g. `wp.data.select('core').getEntityRecords('postType', 'page', { include: '3912' } )`. However, passing the attachment ID as a string always returns `null`

**Screenshots**
Firefox console error:
<img width="984" alt="Screen Shot 2020-12-16 at 13 31 47" src="https://user-images.githubusercontent.com/5252550/102408963-30731680-3fa3-11eb-9c12-6762c63541e7.png">

Chrome console error, slightly different message:
<img width="658" alt="Screen Shot 2020-12-16 at 13 54 12" src="https://user-images.githubusercontent.com/5252550/102411206-6ebe0500-3fa6-11eb-8be9-d851c0bd205a.png">

This screenshot shows the successful getMedia() call for the same image id:
<img width="640" alt="Screen Shot 2020-12-16 at 13 54 43" src="https://user-images.githubusercontent.com/5252550/102411260-83020200-3fa6-11eb-80b4-44c591a3c171.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Default block editor
- OSX 10.15.7
- Firefox 83 and Chrome 83

**Comment by talldan** [comment]
Thanks for reporting. I got different results. Using a string works:
```js
wp.data.select('core').getEntityRecords('postType', 'attachment', { include: '12' })
```

This returned `null` first, and then the second time the attachment data after the request had resolved.

It seems like the intention is that you should use an array:
```js
wp.data.select('core').getEntityRecords('postType', 'attachment', { include: [ 12 ] })
```

The idea seems to be that a string can support multiple values like this:
```
'12,13,14'
```

And an array can support multiple values like this:
```
[ 12, 13, 14 ]
```

And both can also support a single value.

I'll label as a bug, as it seems like a backwards compatibility issue.

**Comment by korynorthrop** [comment]
Thanks, on my fresh install I am able to get the string working as well as the array. For some reason on our production and staging sites both of those options consistently produce `null`. So, I'm not sure what to make of _that_, I'll have to try disabling plugins and changing the theme again to see if there are any conflicts. Do you have any theories on what would lead to a consistent `null` response for a valid ID of an image that exists in the Media Library?

**Comment by korynorthrop** [comment]
@talldan I've chased the issue down to a conflict with the **WP REST Cache** plugin. I had suspected earlier that this plugin _might_ be a partial cause, but I was clearing its cache while testing, assuming that would alleviate any potential conflicts with these `getEntityRecords()` calls. However, it seems that when WP REST Cache is active it cause all of the getEntityRecords responses to come back `null`. I'll report it to the plugin author(s).

**Comment by AdamSoucie** [comment]
I can confirm this is still an issue in 5.6.1, at least with pages. Using the "include" parameter fails, provided the value for the ID is passed as an integer. When I pass the value in as a string, as @talldan did in their example, it worked as expected. In 5.5.3, I didn't need to convert to a string first.

**Additional info**:
Unlike @korynorthrop, I am not running any caching plugins, so while that may be causing a separate issue, that is not the root cause of this problem.

**Comment by mahammedzkhan** [comment]
I'm having the same issue with WordPress 5.7.1, using an integer for `include` doesn't work but a string works.
