### ISSUE TITLE
Decreased performance when using theme editor styles and Custom HTML block

### ISSUE THREAD

**Issue by nk-o** [WordPress/gutenberg#27785]
When we use styles for an editor from the theme and insert a Custom HTML block in any page, we will see the performance decrease while typing.

The problem is also visible with the default **Twenty Twenty One** theme. I have added more CSS (20k lines) to see more performance decrease for testing purposes.

**To reproduce**
1. Install and activate the theme with editor styles - https://github.com/nk-o/test-gutenberg-custom-html-block-performance
2. Open any page and insert Custom HTML to the editor
3. Try to type something inside it
4. See how freezing editor

**Screenshots**
I just type "Test" in the Custom HTML block. See on the screenshot how the Perforformance Chrome tab looks like:

![image](https://user-images.githubusercontent.com/14810891/102521187-ad86b480-40a5-11eb-9995-835378102413.png)

**Editor version (please complete the following information):**
- WordPress version v5.6
- Also tried with Gutenberg plugin v9.5.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 87

**Comment by maddisondesigns** [comment]
I'm also finding that as soon as you insert a Custom HTML Block into your page, the whole page performance slows down, and it becomes very sluggish when typing or even just trying to select other blocks.


- OS: macOS Big Sur 11.0.1 (20B29)
- Browser: Firefox 84.0
- Theme: TwentyNineteen
- WP 5.6 (no Gutenberg plugin)

**Comment by mwidmann** [comment]
Our users have reported the same issue. Seems to be a new thing happening since updating to WP5.6. Haven't tried installing the Gutenberg Plugin.

Seems to occur in every browser, operating system we tried it on.

**Comment by mwidmann** [comment]
Our users have reported the same issue. Seems to be a new thing happening since updating to WP5.6. Haven't tried installing the Gutenberg Plugin.

Seems to occur in every browser, operating system we tried it on.

**Comment by mwidmann** [comment]
Just tested with _WP 5.6.1_ and the issue isn't resolved. Tried it out in _WP 5.7 beta 1_ and there the issue doesn't occur. Either this release uses an older version of Gutenberg (which I hope isn't the case as that would mean this bug is going to be ported to 5.7 eventually, or it has been fixed downstream.

At first I thought that this could possibly be related to [this fixed bug in Core](https://core.trac.wordpress.org/ticket/52394), but this didn't solve the problem. 

So far our only option is to stay on 5.5.3 until this is resolved.

**Comment by mwidmann** [comment]
As a follow up. I just tested it with the freshly released WordPress 5.7 and the issue seems to be gone.

**Comment by skorasaurus** [comment]
Thanks for following up @mwidmann. 

Please reopen if you're you still experiencing this issue.
