### ISSUE TITLE
9.6 RC1: LinkControl creates error when accessed after edit and save.

### ISSUE THREAD

**Issue by hawkmusician** [WordPress/gutenberg#27782]
**Describe the bug**
Running Gutenberg 9.6 RC1 in FSE, the `LinkControl` component `__experimentalLinkControl` seems to have an issue when saving the design when a link has been entered.

The following error appears: 
`Cannot read property 'path' of undefined`

If one gets out of FSE and edits the template in the normal editor, the LinkControl seems to go back to normal and one can open it again in FSE.

**To reproduce**
1. Go to FSE
2. Create a Button and add a link, save the design.
3. Refresh the page and try to edit the button. 
5. Edit template directly outside FSE. Button is editable again, with no error. 
6. Go back to FSE, button editable again with no error. 
7. Repeat and same error happens again. 

Showed up using 9.6 RC-1 on a fresh site

**Comment by annezazu** [comment]
@hawkmusician thanks for reporting this. I was able to replicate with Gutenberg 9.6.2:

https://user-images.githubusercontent.com/26996883/103305027-5b0f9700-49c7-11eb-981d-aa1d3e7a4d14.mov

This might be related to https://github.com/WordPress/gutenberg/issues/27773 Flagging this as a regression and high priority.

**Comment by noisysocks** [comment]
Removing `[Priority] High` as FSE is a beta feature.

**Comment by hawkmusician** [comment]
This no longer seems to be an issue. LinkControl now behaving properly.

**Comment by hawkmusician** [comment]
Well hello again. I closed this issue a couple of days ago having tried it on a few installs and the bug seemed to have disappeared, but the issue has come back while testing today... Reopening.

**Comment by annezazu** [comment]
Thanks for testing and reopening!

**Comment by jasmussen** [comment]
Coming back to this, it appears fixed, so closing:

![bug](https://user-images.githubusercontent.com/1204802/193261465-53fbc120-671d-4a0e-b2e9-c8bbd59d34b1.gif)
