### ISSUE TITLE
Aligning image right pushes toolbar under sidebar settings.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27789]
**Describe the bug**

Toolbar is underneath the right sidebar settings.
![Screen Shot 2020-12-17 at 21 45 07](https://user-images.githubusercontent.com/5323259/102541954-5f77ae00-40b1-11eb-8ea8-d9e501b7488c.png)

![Screen Shot 2020-12-17 at 21 50 29](https://user-images.githubusercontent.com/5323259/102542329-ec226c00-40b1-11eb-8254-a1812b1f8b32.png)

**To reproduce**
1. Add Image block.
2. Add image.
3. Align the image right.
4. Resize the window so it becomes smaller.
5. See toolbar below right sidebar.

**Expected behavior**
Toolbar needs to shift into a position to be fully visible even though an image is right aligned.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Yes
- If the Gutenberg plugin is installed, which version is it? 9.5.2
- Theme in use: Twenty Twenty

**Desktop (please complete the following information):**
local dev site
chrome

**Comment by jasmussen** [comment]
I'm seeing this working as intended in both post and site editors:
<img width="1392" alt="Screenshot 2022-01-19 at 10 45 50" src="https://user-images.githubusercontent.com/1204802/150105658-b9eea6f4-75d9-48b0-b85a-fa54ed644c06.png">
<img width="1392" alt="Screenshot 2022-01-19 at 10 46 24" src="https://user-images.githubusercontent.com/1204802/150105668-27e0d1a6-24dd-4d3b-90c7-f7496435cf47.png">

Is this one good to close?

**Comment by paaljoachim** [comment]
Hey @jasmussen Joen

I checked it out as well. It now looks correct.
Closing issue.
