### ISSUE TITLE
Unable to Crop Image when click Crop button

### ISSUE THREAD

**Issue by PHuhn** [WordPress/gutenberg#27787]
**Describe the bug**

While on the _Edit Image_ form click the **Crop** button and the and the 8 anchor squares do NOT appear. The **Rotate right** and **Rotate left** button work, but the **Crop** button does not work.

**To reproduce**
1. Go to 'Media -> Library'
2. Click on 'an image'
3. On the _Attachment details_ form, click the **Edit Image** button at the bottom of the form.
4. On the _Attachment details_ form, click the **Crop** button above the image and nothing happens.
5. No error message and no 8 anchor squares.

**Expected behavior**

While on the _Edit Image_ form click the **Crop** button and the and the 8 anchor squares appear. The anchor squares allow one to crop the image.

**Editor version (please complete the following information):**
WordPress version: 5.6.0

Installed Plugins:
- Display Posts Version 3.0.2
- Font Awesome Version 4.0.0-rc21
- WordPress Importer Version 0.7

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by PHuhn** [comment]
Hey:
I do not know what is happening but I was just now able to crop an image.  I was going to go back a version, but it appears not necessary.
Phil

**Comment by PHuhn** [comment]
Hey All:
Been able to reproduce the issue.
Start the cropping process and then click on the image, then the 8 squares will disappear.  The only way to get the cropping to work again is to click the **Cancel** button.  Weird.

**Comment by annezazu** [comment]
I wasn't able to replicate this! Here's a quick video:

https://user-images.githubusercontent.com/26996883/103305597-c4dc7080-49c8-11eb-93bb-4d4db8bf4837.mov

If this happens again, I'd recommend reporting here https://meta.trac.wordpress.org/ as the Media Library is a Core WordPress feature. For now, going to close this out.

**Comment by PHuhn** [comment]
1. Go to 'Media -> Library'
2. Click on 'an image'
3. On the _Attachment details_ form, click the **Edit Image** button at the bottom of the form.
4. On the _Attachment details_ form, click the **Crop** button above the image and 8 anchor squares appear.
5. Drag the bottom anchor up half way.
6. In the darkened space below the bottom crop line click and all crop lines disappear.
7. Click the **Crop** button again and nothing happens.
8. Click the **Cancel** button.
9. On the _Attachment details_ form, click the **Edit Image** button at the bottom of the form.
10. On the _

Attachment details_ form, click the **Crop** button above the image and 8 anchor squares appear.

**Comment by annezazu** [comment]
@PHuhn thanks for writing back! I tried to replicate this and found that the cropping functionality still appears. Here's a video: https://cloudup.com/c3hdV1X1R5h It seems what might be confusing is how small the selection becomes after clicking into the darkened space. Even with that though, one can still drag across the image to create a new selection area. Check out the video I made and let me know if that helps clear things up! If not, definitely report the request here: https://meta.trac.wordpress.org/  as this repo is specifically for the Core Editor which is separate from the Media Library.

**Comment by PHuhn** [comment]
Hey Annezazu:
I think what I see in your last video/movie is what I was experiencing happening to me.  When you clicked below the image, the 8 square anchors did disappear.  I contend that I did not know how to recover from the square anchor disappearing.  I just happened onto my solution.  I have been programming, for a long time, but a basic end-user is not going to understand how to overcome this situation.  I have not read the user documentation and the basic end-user is also not going to have read the documentation.  Phil

**Comment by annezazu** [comment]
Hey @PHuhn I totally get why it's a confusing experience and how it might help to have some gentle nudges to help people get back on track with cropping when this happens. I definitely think it's worth opening a request in the appropriate place: https://meta.trac.wordpress.org/

**Comment by PHuhn** [comment]
Hey Annezazu:
The meta-trac link in your last message seems to be for issues for wordpress.org site.  I will repost this as a feature and also point back to this thread.  I am assuming that cropping is not a part of Gutenberg.
Phil

**Comment by annezazu** [comment]
Ah! So sorry - silly copy/paste failed me. You're right. This is the correct link: https://core.trac.wordpress.org/ I'll update the previous comments to lessen confusion.
