### ISSUE TITLE
Insert Link: updating the options deletes custom CSS class

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#27790]
**Describe the bug**
Currently, the only way to add a class to a link in the Gutenberg editor is to edit the block as HTML, insert the class name (and then return to editing visually).

However, if you then click on the link in Gutenberg, and update any option - eg toggle the 'open in a new tab' option, the class name gets completely deleted.

**To reproduce**
1. Add a paragraph block with a link inside.
2. Edit the block as HTML
3. Add class="test" to the link
4. Edit the block visually
5. Click on the link and select 'Open in a new tab'
6. Edit the block as HTML to see the class gone.

**Expected behavior**
The UI should not override a custom class. It had been previously requested to add a class field to the UI in https://github.com/WordPress/gutenberg/issues/13368 , but that was closed with the suggestion that it wasn't useful enough and the HTML option would work.

If a UI option won't be provided, the workaround should at least be viable without unrelated changes breaking it.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Comment by annezazu** [comment]
@smerriman thanks for reporting this! I found a previous report of the same issue here: https://github.com/WordPress/gutenberg/issues/27345 As a result, I'm going to close this out.
