### ISSUE TITLE
Shortcode block not working in Widgets screen

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#27793]
**Describe the bug**

When used in the Widgets screen, a shortcode block won't render the content but instead shows the shortcode text as a paragraph.

From [this forum topic](https://wordpress.org/support/topic/shortcode-needs-html/).

**To reproduce**
1. Go to Widgets screen.
2. Add a shortcode block, with a shortcode in it.
3. Save and view site.
4. Verify the shortcode text appears instead of expected content.

**Comment by carlomanf** [comment]
Kind of related: #19278, #21397
