### ISSUE TITLE
 Enhancement in gallery block with coming WP 5.5 to Enhancement in gallery block

### ISSUE THREAD

**Issue by kevinkovadia** [WordPress/gutenberg#27805]
I wish the gallery block has the following enhancement with coming WordPress.

- In media, if images also have the category then we can select use galley block to showcase portfolio on the website.
- It would be great if we have an AJAX-like filter option in gallery blocks so that end-user can see category-wise images as per their wish.
- It would be great if all the images in the gallery block have a custom URL. (as recently added in media + text). It will be useful for showcasing a website portfolio with url in the site.
- Currently, I am using a visual portfolio (by nk) to showcase portfolio work.
Looking forward to witnessing in upcoming WP.

**Comment by annezazu** [comment]
@kevinkovadia Thanks for sharing these ideas! Can you clarify a bit what you mean by the first two items in your list referencing categories? I'm not quite sure I'm following what you want there. 

> It would be great if all the images in the gallery block have a custom URL. 

This has been requested previously here: https://github.com/WordPress/gutenberg/issues/10057 I'd recommend commenting there to express interest :)
