### ISSUE TITLE
Timeline block

### ISSUE THREAD

**Issue by kevinkovadia** [WordPress/gutenberg#27804]
can we have a default timeline block in Gutenberg block editor? this block will be helpful in highlighting the timeline /journey on the website.

**Comment by aristath** [comment]
@kevinkovadia could you please elaborate? What would a `timeline` block look like? What would its purpose be? :thinking: 
I don't think I've seen a "timeline" anywhere which makes me think this would be too niche to include in wp-core, but perhaps I just don't understand what you mean by `timeline`?

**Comment by mkaz** [comment]
I would agree that a Timeline block is likely too niche to include in core.
There is a timeline block included with the [Editing Toolkit plugin](https://wordpress.org/plugins/full-site-editing/) you can try that. The [source is also available here](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline)  if you want to play with it and modify to fit your needs.
