### ISSUE TITLE
Outline blocks in edit mode

### ISSUE THREAD

**Issue by crgeary** [WordPress/gutenberg#27808]
**Is your feature request related to a problem? Please describe.**

It's very difficult to work out where to click when trying to select a block in edit mode. It's extremely frustrating to mock up anything other than a simple blog post. The moment you start nesting blocks this becomes a tedious case of hovering over multiple elements until you find the area you're supposed to be clicking.

I can spend more time working out where to click, than I do building the block I need.

**Describe the solution you'd like**

I'd like to see a way of enabling an outline that is permanently visible around all (or most) blocks to identify block boundaries and where to click the mouse.

```css
.wp-block {
    outline: 1px dotted rgba(#222222, .25);
    outline-offset: 5px;
}
```

This will produce something like this:

![image](https://user-images.githubusercontent.com/3949335/102610728-938cb680-4125-11eb-8027-9962518a4924.png)

**Describe alternatives you've considered**

I've tried to use "select mode" but it still requires me to know where the block is in order to get an outline, and I have to switch modes each time.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting and I personally am frustrated by this as well. 

https://github.com/WordPress/gutenberg/issues/23892 shares other users with your concerns and has a lengthy discussion about it. 

If you don't think that issue covers your issue; please reopen this.
