### ISSUE TITLE
HTML Block: Match the editor to the front end

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#27803]
**Is your feature request related to a problem? Please describe.**
The HTML block doesn't look the same in the editor and the frontend.

**Describe the solution you'd like**
We should update the CSS so that the block looks the same in both places. We should also add some customizations to the blocks:
- Colors
- Custom spacing
- Border controls

**Describe alternatives you've considered**
We could just do this in CSS first

Partly addressed in #9129

**Comment by mtias** [comment]
Can consider it a duplicate of #9129?

**Comment by scruffian** [comment]
I think that PR will help but we also want to add some support for Global Styles

**Comment by mtias** [comment]
I mean it's just a case of loading generated styles in the iframe, which is what that issue means to cover

**Comment by scruffian** [comment]
I mean we want to add `supports` to the block.json for color, spacing, border radius, etc.

**Comment by mtias** [comment]
To the HTML block? That seems weird

**Comment by scruffian** [comment]
Well for example if a theme had a dark background it might want to set the background color of the HTML block to match the theme rather than using the default that the editor provides.

**Comment by carolinan** [comment]
But the HTML is for using code, not to display a visual presentation of code or the content in the block

I think the block works as intended, if the user wants the content of the HTML block to be styled, they add the style.
This gives the block content the flexibility it needs.

**Comment by scruffian** [comment]
Ok, let's close as a duplicate of #9129
