### ISSUE TITLE
Make Gutenberg more CMS agnostic

### ISSUE THREAD

**Issue by perandre** [WordPress/gutenberg#2780]
Coming from a company building websites using both WP and Drupal, we are quite excited about Gutenberg. While D8 has it's own initiatives for similar purposes, Gutenberg solves some issues Drupal hasn't touched on yet (and where they overlap, Gutenberg has a better UX). 

Currently, Gutenberg and WP code is closely knit. But architecturally, it needn't be so. Imagine if the project structure separated JS code from the PHP, and the naming was universal and with non WP-use cases in mind! This could make Gutenberg the "content editor for the web", not just for WP. And: upstream contributions can't be bad.

A good analogy would be CKEditor or TinyMCE. However, that would require a full rewrite. The only fundamental steps that would need to be taken, are:

- Make the core framework (no blocks) available in a separate folder
- Avoid WP'isms in core JS files

Maintaining a Drupal fork would still be a bit messy, but it would only require smaller parts of the lib, and some actual dev could happen. 

What are your thoughts?

**Comment by youknowriad** [comment]
I would love to have this personally, I already have some use cases in personal projects but I don't think it's a use-case we're focused on right now. Though, we'll be close to this after solving #2761

**Comment by perandre** [comment]
Good input. And I agree on the focus; a stable release should be hi pri. For later versions a lot of architectural decisions must be made however, and and it would be awesome if Gutenberg as "page builder for the web" would be part of the roadmap. From the FAQ:

> But a rough roadmap is: v1) post and page editor v2) page template editor, v3) site builder.

If there is enough interest, I think abstracting it into a semi standalone lib would make sense as a v4. It could influence decisions from the start, with very few downsides.

**Comment by karmatosed** [comment]
I am closing as whilst an interesting idea it doesn't relate directly to the work going on with the project and it's goals.
