### ISSUE TITLE
enhancement in "recent post block"

### ISSUE THREAD

**Issue by kevinkovadia** [WordPress/gutenberg#27806]
It would be great if this block has category based some filter (like AJAX) options so that end-user/reader of the website can select his/her favourite post easily.

**Comment by aristath** [comment]
You can use the query block which contains filters for categories :)

**Comment by annezazu** [comment]
@kevinkovadia as Ari mentioned above, this is possible with the Query block. Here's a previously opened issue that matches what you're looking for too referencing the Query block once more: https://github.com/WordPress/gutenberg/issues/13027 For now, I'm going to close this out as a result :)
