### ISSUE TITLE
Option to enable front-end CSS for true WYSIWYG

### ISSUE THREAD

**Issue by perandre** [WordPress/gutenberg#2781]
To control the look of your post, it is helpful to instantly view it as it will be rendered to the end user, while editing. This is of course the killer feature of the Customizer, and I think it should be for Gutenberg as well.

This is of course hard to do, as no iframe is used, and a global CSS file can't easily be added to a portion of the site. There are however hacky ways to solve it – and perhaps less obvious ones.

This approach has proved successful with tools like Squarespace and the like. Also, I think this feature will be more and more useful, as Gutenberg will potentially replace third party page builders. 

Has anyone done any thinking on the subject (I'm sorry if I've missed it)?

**Comment by mtias** [comment]
Take a look at the videos in https://make.wordpress.org/core/2017/08/31/gutenberg-themes/ for a demo of how this could work.

**Comment by perandre** [comment]
Wow. That is truly brilliant. Are there already commits on this?

**Comment by westonruter** [comment]
Bringing Gutenberg _into_ the Customization experience is one of the things that I'm eager to experiment with. In that way, you'd get true WYSIWYG automatically. However, in an initial integration it would look like Gutenberg being opened in a lightbox or covering the preview window, with then allowing you to close the Gutenberg editor to then see the changes rendered in the actual frontend of the site. In order support inline editing of Gutenblocks on the frontend of your site, I believe there's going to need to be quite a bit of work done in the theming system, with a shift from relying on server-side rendering to instead facilitating client-side rendering.

**Comment by mtias** [comment]
@perandre thanks for the enthusiasm :) It's a very simple approach that enqueues block styles via:

```php
function gutenbergtheme_editor_styles() {
    wp_enqueue_style( 'gutenbergtheme-blocks-style', get_template_directory_uri() . '/blocks.css' );
}
add_action( 'enqueue_block_editor_assets', 'gutenbergtheme_editor_styles' );
```

**Comment by perandre** [comment]
Excellent, I think this solves the main use cases for now. Thanks for the quick replies!
