### ISSUE TITLE
Jotform Embeds - Cannot Submit Form

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#27819]
**Describe the bug**
Jotform has a native integration in that you can paste a Jotform link and it renders as an embedded form. However, embedded forms from Jotform cannot be submitted at the moment. The embed displays properly on the front end, but after filling out the form, the submit button does not respond.

**To reproduce**
1. Go to Jotform and create a form
2. Get the Jotform link that looks like https://form.jotform.com/123456789876543210
3. Paste it in a new line in the editor and publish the page/ post
4. Visit the page and attempt to submit the form

Note as well that I tried the shortcode option on a WordPress.com site but it was the same result https://www.jotform.com/help/299-how-to-embed-a-form-to-wordpresscom

**Expected behavior**
I expected the form to submit successfully.

**Screenshots**
Screenshot showing the form stuck on "please wait" upon submission:
<img width="575" alt="jotform" src="https://user-images.githubusercontent.com/30727666/102642239-7e5d6980-41b1-11eb-816f-ba4100695395.PNG">

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
Windows 10, Chrome 87

**Comment by annezazu** [comment]
@donalirl this doesn't appear to be an issue related to Gutenberg and more to do with Jotform! I am going to close this out as a result particularly after seeing the appropriate follow up directly on the forums with Jotform: https://www.jotform.com/answers/2775518-Jotform-WordPress-forms-do-not-submit
