### ISSUE TITLE
File Block: Allow selecting multiple files.

### ISSUE THREAD

**Issue by wwdes** [WordPress/gutenberg#27823]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when doing a list of multiple files.

**Describe the solution you'd like**
When selecting file from media library, it would be great if one could select multiple files at once and the block would create a list from those files.

**Comment by skorasaurus** [comment]
Hi, Thanks for reporting. This has already been reported at https://github.com/WordPress/gutenberg/issues/19951 and you can follow its progress there.
