### ISSUE TITLE
Remove Noto Serif and use system fonts

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2782]
We are using Noto Serif for the editor, if we remove this and go for system fonts we can make some speed gains. It will remove some personality, but the gains would be good to have. WordPress itself uses system fonts, so there is a precedent.

**Comment by samikeijonen** [comment]
Sounds good. For the block content we'd naturally use the same font as in the front end. Haven't looked yet is that easy or not.

**Comment by iseulde** [comment]
Worth noting that core does not use system fonts for the editor. For that it uses Georgia. Would be great to stick to a serif font. :)

**Comment by aaronjorbin** [comment]
SInce ideally this is usually overridden by a theme's stylesheet, I think that avoiding loading an external resource that won't be used is a good idea.

**Comment by hugobaeta** [comment]
Agree with @iseulde, would be great to keep a serif stack. If it's system fonts (georgia, times, etc) it shouldn't add any weight. Either way, also agree with @aaronjorbin - the themes should be overwriting this anyway :D Let me know if help is needed there @karmatosed

**Comment by NewJenk** [comment]
Giving the editor a little separation from the rest of the admin definitely feels quite natural, so not sure if using system fonts would improve things from a UI perspective. But making it super-easy to use front-end fonts is essential (IMO).

**Comment by karmatosed** [comment]
@hugobaeta I'd be interested in Georgia, what do you think?

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519321555000428)._

**Comment by jeffpaul** [comment]
Discussion in today's Gutenberg bug scrub was to close this keeping Noto Serif for now and we can revisit if necessary.

**Comment by aristath** [comment]
I know this one was closed, but still... my 2 cents: WP-Core was for a long time using Open-Sans for the dashboard and then in [font-natively](https://make.wordpress.org/core/features/font-natively/) we reverted to system fonts.
I agree that Noto is prettier, but at the same time there's precedence and I wouldn't want us to use Noto now only to remove it next year.
