### ISSUE TITLE
Crash when deleting nested blocks after resizing browser

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#27833]
**Describe the bug**

![101600302-6a6c7780-39fb-11eb-8c48-8339301aacb3](https://user-images.githubusercontent.com/22446385/102724643-afc66880-435c-11eb-8620-256b94f1ffc2.gif)

**To reproduce**
Make the browser full screen
Add a "Columns" block
Add an image block to one of the columns
Resize the browser to a mobile size
Delete the image using the delete key on the keyboard

**Expected behavior**
Image is deleted

**Screenshots**
Editor crashes with js error
<img width="1604" alt="101600132-2a0cf980-39fb-11eb-8491-fc5c752dfaeb" src="https://user-images.githubusercontent.com/22446385/102724670-e4d2bb00-435c-11eb-9130-2f5b8f10029c.png">

**Editor version (please complete the following information):**
- Tested on the master branch of gutenberg in local wordpress install

**Context**
Originally discovered with the Layout Grid block, with this block the browser resizing step is not neccessary
https://github.com/Automattic/block-experiments/issues/158

**Comment by noisysocks** [comment]
I was able to reproduce this.

**Comment by noisysocks** [comment]
The Columns block part of the reproduction step isn't necessary here. If you delete _any_ block after resizing the viewport from desktop to mobile then there is a crash.
