### ISSUE TITLE
FSE: Template Editing option only visible after saving

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27853]
**Describe the bug**

Using the [Gutenberg Times nightly zip](https://github.com/bph/gutenberg/releases/tag/9.6.0-nightly), I found that when trying to use the template editing mode that there's a delay in getting the option to show.  cc @youknowriad in case this is just me :) 

**To reproduce**
1. Use a FSE theme like twenty twenty-one blocks. 
2. Add a new page by going to Pages > Add New.
3. Check the page settings and don't see a mention of templates.
4. Add in a title and brief content, click save draft, and then see the template editing option show after saving.

**Expected behavior**

I expect to see the option to edit the template from the start when creating a new page not after saving a draft or publishing.

**Screenshots**

Gif:

![template edit](https://user-images.githubusercontent.com/26996883/102828038-f342c600-43a0-11eb-9dd8-65d8fe76f535.gif)

Video:

https://user-images.githubusercontent.com/26996883/102827750-5f70fa00-43a0-11eb-94c6-ec8b3b06d8d4.mov

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg. 
- If the Gutenberg plugin is installed, which version is it?  [9.6 nightly release](https://github.com/bph/gutenberg/releases/tag/9.6.0-nightly)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 87.0.4280.88 (latest)

**Comment by youknowriad** [comment]
Thanks for the issue @annezazu This is a known bug due to a Core limitation for now. See #27391 for more technical details.

**Comment by annezazu** [comment]
Ah! Thank you. I tried to do due diligence before filing but missed that :)
