### ISSUE TITLE
Site Editing: In the W navigation, utilise drilldown pattern to organise semantic template parts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27877]
Once we have semantic template part categorisation in place, we can utilise the drilldown pattern in the W navigation to better organise template parts therein:

<img width="1078" alt="Screenshot 2020-12-23 at 13 44 01" src="https://user-images.githubusercontent.com/846565/103001513-10a09d00-4525-11eb-812f-272e2cd71cce.png">

**Comment by mtias** [comment]
It might be interesting to render this in the sidebar directly (like the block patterns sidebar).

**Comment by jameskoster** [comment]
> It might be interesting to render this in the sidebar directly (like the block patterns sidebar).

You mean display the preview _in_ the sidebar? I agree that would be good to try. I'm torn on whether that, or displaying the preview on hover, would be best though. 

The text-based list is arguably easier to scan, especially if there are only subtle differences between template parts. Also, by displaying the preview on hover we have more flexibility wrt size which may be important. 

I think that displaying the preview directly in the sidebar might work better when there are fewer template parts.
