### ISSUE TITLE
Site Editing: Display contextual description, name and category switching for selected template part

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27875]
When I select the Header template part in the Site Editor, here's what I see in the Inspector:

<img width="280" alt="Screenshot 2020-12-23 at 11 37 03" src="https://user-images.githubusercontent.com/846565/102992535-48064e00-4513-11eb-894f-c814443dd85b.png">

## Contextual names 
~If the selected template part has a name, we should display that and inline the "template part" label as a suffix only. So if I select the "Header" template part, I should see "Header (template part)" as the block name in the Inspector, along with the appropriate icon and [colorisation](https://github.com/WordPress/gutenberg/issues/26599).~

Dedicated issue for this here: https://github.com/WordPress/gutenberg/issues/27876

## Add description
I think it would be helpful to include a brief description that outlines the general template part concept.

> Template parts can be inserted in to multiple documents and will always display the same configuration of blocks.

We might consider placing this inside an informational `Notice`.

If the template part has its own description (excerpt) that should appear here as well.

## Template part category
Once it is possible to determine the template part category (https://github.com/WordPress/gutenberg/issues/27337) we should display that here too, and include an option to switch the category.

## Putting it all together
Circling back to the original screenshot, when I select the Header template part I should now see something like this:

<img width="1724" alt="Screenshot 2020-12-23 at 13 49 47" src="https://user-images.githubusercontent.com/846565/103001873-c10ea100-4525-11eb-9142-386fb53b345c.png">

I'm sure we can optimise the labels / descriptions so I would welcome any suggestions there. Otherwise I think this could serve as an adequate starting point.

**Comment by Addison-Stavlo** [comment]
This makes sense to me and should be implementable after https://github.com/WordPress/gutenberg/pull/28410 lands.

Q: Should there be generic descriptions for the base categories (header, footer, sidebar)?  Or maybe something like that would make sense to use in place of excerpt if excerpt happens to be blank? 🤔

**Comment by jameskoster** [comment]
I suppose that would be most useful when you're actually selecting a category? Maybe something like...

<img width="323" alt="Screenshot 2021-02-03 at 10 51 47" src="https://user-images.githubusercontent.com/846565/106739955-b7428800-6611-11eb-9fb2-94b689a684f6.png">

(But with actual descriptions, obviously :D)

**Comment by Addison-Stavlo** [comment]
That makes sense!

Another side thought - with the prominence of the excerpt here a later follow up would probably be to allow theme supplied template parts to supply a default excerpt for the template part? 🤔

**Comment by jameskoster** [comment]
Yes good point, I think themes should be able to supply descriptions for template parts and custom templates.

**Comment by Addison-Stavlo** [comment]
With the upcoming removal of the renaming input from the toolbar and the suggestion to have it in the block inserter, I am wondering what that might look like here.  Do you have any thoughts on that?

Perhaps the title we have in the block inspector (where you have "Header Inline" in your designs), it could be a renaming input similar to the search input in the nav panel:
![renaming toolbar](https://user-images.githubusercontent.com/28742426/107095057-22d55280-67d6-11eb-9f54-0e5f2b3dfde0.gif)
(but with an edit icon instead of a search icon).

Otherwise we could put it further down in the block navigator, but I think incorporating it with that top title in the inspector might be a good place.

**Comment by jameskoster** [comment]
Yeah I actually mocked that up at some point in the past 😄

Shall we address that in a separate issue?

For now it is still possible to rename a template part via Appearance > Template Parts.

**Comment by mtias** [comment]
Now that we also have the name in the sidebar, how should we present the panels? It seems we might not need the "category" panel and could be combined.

**Comment by Addison-Stavlo** [comment]
>Now that we also have the name in the sidebar, how should we present the panels? It seems we might not need the "category" panel and could be combined.

Relaying from https://github.com/WordPress/gutenberg/pull/29159#issuecomment-783354982 - the suggestion to put the category, tag, and renaming all under "Advanced" may make sense. 👍 

It looks like that PR *should* resolve this issue, so adding @david-szabo97 as the assignee here.

**Comment by vindl** [comment]
This has been completed in https://github.com/WordPress/gutenberg/pull/29159.
