### ISSUE TITLE
Site Editing: Contextual template part icon and name

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27876]
With #27378 merged, we should update any component that displays the template part name + icon.

### Icons

* For genetic template parts use the `layout` icon.
* For Header template parts, use the `templatePartHeader` icon
* For Footer template parts, use the `templatePartFooter` icon
* For Sidebar template parts, use the `templatePartSidebar` icon

### Name

If the selected template part has a name, we should display that instead of the generic "Template Part" label. So if I select the "Header" template part, I should see "Header" as the block name in the Inspector, along with the appropriate icon and [colorisation](https://github.com/WordPress/gutenberg/issues/26599).

Off the top of my head, the only other location we'll need to update this is the block navigator. If the inserter / quick inserter exposes specific template parts we'll need to update that as well.

### Examples:

<img width="1590" alt="Screenshot 2020-12-23 at 13 56 17" src="https://user-images.githubusercontent.com/846565/103002371-abe64200-4526-11eb-8bc6-c17b9995ba61.png">

**Comment by david-szabo97** [comment]
How are we distinguishing  between generic template parts and header/footer/sidebar? Should we just check for template part name? Something like "if template part name contains 'header" then use "template part header" icon.

**Comment by jameskoster** [comment]
Good question, I suppose https://github.com/WordPress/gutenberg/issues/27337 is a blocker to this being fully implemented.

**Comment by vindl** [comment]
> Should we just check for template part name? Something like "if template part name contains 'header" then use "template part header" icon.

We should define canonical template parts types that core supports. It will then be possible to assign these types to template parts and customize some parts of the experience accordingly (filtering patterns etc.).

> I suppose #27337 is a blocker to this being fully implemented.

Yes.

**Comment by mtias** [comment]
It seems this is wrapped now. We'll have a separate issue to explore the colors.
