### ISSUE TITLE
How to manage block editor native component deprecation ?

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#27888]
Hello,

We are using three times the old IconButton component in our user interface. As you know this component is deprecated since Gutenberg 7.2 - if I'm right - and then WordPress 5.4. We would like to use the recommended Button - with an icon - component instead. However we need to keep a backward compatibility with older WordPress versions less than 5.4.

What is the best way to manage this case ?

I searched about deprecation in the handbook but unfortunatelly it talks about block deprecation and not about native component deprecation.

Thanks

**Comment by gwwar** [comment]
Hi @manooweb! Looking at the code, at the moment it doesn't look like there's a specified date set for ButtonIcon being removed from code. https://github.com/WordPress/gutenberg/pull/19299/files#diff-52d111e30e8e1982f4567d3b3df8c2cf3dc53102b3faf7cbcfc63d527ee4d0e5R19 or https://github.com/WordPress/gutenberg/blob/3e498b2bb82476c927f32140009818977c1131a3/packages/components/src/button/deprecated.js#L13-L15

cc @youknowriad in case y'all had a specific migration path in mind.

In general we might approach a component being deprecated in two ways:

### Maintain multiple plugin versions

As a plugin developer we might choose to maintain multiple plugin versions that support different WordPress version ranges. For example if we have new feature available in WordPress 5.5+ but not in WordPress 5.4

If the WP feature is important, we might break our own code out to:
- Plugin version 1.x line supports WP 5.4
- Plugin version 2.x line supports WP 5.5

This does add overhead for taking care of multiple release lines, but we can avoid lots of checks in code which is hard to maintain.

### Feature detection

Another common approach, especially for something pretty minor like a component is to do [feature detection](https://en.wikipedia.org/wiki/Feature_detection_(web_development)). This is somewhat similar to see if a browser has some capabilities before trying to use it. 

So in our example we might check for:

```js
import { Button, IconButton } from '@wordpress/components'; 
if ( typeof Button !== 'undefined' ) {
   // use button
} else {
   // otherwise use IconButton
}
```

To keep code tidy we might decide to register one script to run over another using the same feature check.

As an aside, It also looks like there's some experimentation with block editor features in https://github.com/WordPress/gutenberg/blob/27bab471e7b5e1e5997a2a034947f71da220bf95/packages/block-editor/src/components/use-editor-feature/index.js#L17-L50 but **this is experimental (not recommended to develop against)** and related to the block editor itself.

**Comment by manooweb** [comment]
Thanks @gwwar for this detailed answer.

🤔 we will have to discuss inernally about that but it seems to me that `Feature detection` could be a good solution.

Indeed after each of our release we don't maintain our older versions. We try to maintain only one version to be compatible with the latest WordPress version. However users don't update to major versions as soon as they are released. So we need to stay compatible with some older versions.

**Comment by gwwar** [comment]
Happy to help. When using this approach, one thing to track is when your plugin no longer support an older WP version. When that happens, the feature checks can be removed from code.

**Comment by manooweb** [comment]
> Happy to help. When using this approach, one thing to track is when your plugin no longer support an older WP version. When that happens, the feature checks can be removed from code.

Sure! We're cleaning it up regurarly to remove code become useless

**Comment by gwwar** [comment]
I'm going to close this one for now, but I'll update this again if I find a better approach.

**Comment by manooweb** [comment]
> I'm going to close this one for now, but I'll update this again if I find a better approach.

No problem, we talked about yesterday and it's an approach we already have with our PHP code to maintain backward compatibilities.
So it's clear for us.

Thanks again for your time on this issue 😉
