### ISSUE TITLE
Fullscreen mode: clicking the WP icon should toggle the admin menu

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#27882]
I like the fullscreen mode. However, it's hard to navigate to other parts of the admin area. When clicking the WordPress icon on the top bar, it goes to the dashboard page, which makes me loose the current editing screen.

I suggest clicking on the WordPress icon don't redirect the page to the dashboard, but toggle the admin menu. This way, when users want to go to another part of the admin area, they can simply click the menu item while still keeping the editing screen open.

**Comment by mtias** [comment]
This is planned, but doesn't quite work with the current state of things (see #22191) and needs a bit more thought. You can see a practical example in the site editor where it open the templates context as a first step.

**Comment by talldan** [comment]
I think the previous issues https://github.com/WordPress/gutenberg/issues/22178 and #21739 adequately cover the problem, so I'll close this as a duplicate.
