### ISSUE TITLE
Site Editing: Make it clearer how to get back into post/page editing mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#27899]
**Describe the bug**

When one switches into template editing, it's not clear how to get back to solely editing the page or post without hitting cancel. While one can continue to edit the page/post within the template editing experience, this may not be preferred if trying to do focused writing. 

**To reproduce**

1. Install Gutenberg 9.6+ and a FSE ready theme.
2. Go to Posts > Add New or Pages > Add New
3. Make some changes to the post > Publish or Save Draft
4. Use the option to edit the template to switch into template editing mode in the document settings section.
5. Try to go back to just editing the page or post. The only option to do so is to hit "Cancel". 

**Expected behavior**

I expected there to be a clear spot where I could switch back to just editing the page/post rather than the full template.

**Screenshots**

Here's a video of me talking through the experience: https://cloudup.com/czZzMdnmg4I

Perhaps for now as a V1, it could be as simple as re-using the template editing flow but, when editing the template, have the option to switch back to the page.

To enter the template editing experience:
<img width="281" alt="Screen Shot 2020-12-25 at 1 59 50 PM" src="https://user-images.githubusercontent.com/26996883/103141959-9ce3c900-46b9-11eb-8d0a-9537d56da9d9.png">

An imagined version of how to switch back to page/post editing experience: 
<img width="281" alt="Screen Shot 2020-12-25 at 2 00 22 PM" src="https://user-images.githubusercontent.com/26996883/103141960-9d7c5f80-46b9-11eb-8beb-1d1977c0e546.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg
- If the Gutenberg plugin is installed, which version is it? 9.6.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version:87.0.4280.88

**Comment by mtias** [comment]
There are a few tasks in #27814 that would cover this

**Comment by paaljoachim** [comment]
Here is another way to handle the switcher.

Having for instance a toggle to go between full site editing <-> content.


![FSE-content-switcher](https://user-images.githubusercontent.com/5323259/106936776-45effb80-671d-11eb-836a-233606e37ec5.gif)

Test the prototype:
https://www.figma.com/proto/D3cBEOq7I7pemOoJ823Etb/FSE-Content-Switcher?node-id=1%3A3&scaling=min-zoom

Btw the name Page: Template will likely not mean much for the average user. Perhaps we should instead here use Full site, or something else that describes where the user is about to enter.

**Comment by annezazu** [comment]
Noting for posterity that the current flow now offers a back option:

<img width="1154" alt="Screen Shot 2021-07-07 at 3 04 36 PM" src="https://user-images.githubusercontent.com/26996883/124828561-ab4a5180-df34-11eb-9259-d9a6d516cd30.png">

While this is a step in the right direction, I do think more thought can be put into making this switching process easier and more distinct so folks know what they are editing.

**Comment by annezazu** [comment]
Going to close this out as other issues cover this dynamic in a more comprehensive and up to date way (like https://github.com/WordPress/gutenberg/issues/27847)
