### ISSUE TITLE
TinyMCE Single - Multi-selection of paragraphs loses the toolbar

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#279]
When selecting multiple parargaphs, the toolbar disappears. This doesn't feel right to me. 

![lost-toolbar](https://cloud.githubusercontent.com/assets/617986/23965323/da22ae3e-0974-11e7-9c5a-b40ad5fdd464.gif)

Shouldn't I be able to apply **bold**, or _italic_, or whatever to multiple text selections at one time?

**Comment by iseulde** [comment]
Also still need to make drag and drop work for multiple selection.

**Comment by mapk** [comment]
Well ideally, it should act just like it does when I'm highlighting a single block. In the example above, the toolbar should remain the same b/c they're both paragraph blocks.  When it comes to highlighting different block types, then I'm not too sure how that would work.  Maybe the same?

**Comment by jasmussen** [comment]
I tend to agree that whenever a block is selected, all formatting controls for that block should be visible until you select something else, like a caption, or another block. 

Blockquotes and lists are the tricky ones. The pattern that people are used to is: select a lot, the click list/blockquote as a formatting button. One of the aspects of this block-first UI experiment, though, is that we show block level type selection in the switcher, not as part of the block alignments bar, and not as part of inline formatting either. In that way it'd be just like how you make multiple paragraphs into preformatted text in the current editor. 

I think that's what we should try for now, even if I have a hunch it's not going to be as user-friendly. Then we can test it, see if it works for people, and if it doesn't, we'll cross that bridge. A button is a fine plan B. 

**#testreminder** 👈 let's use this tag in github and slack as something we can write down on things we want to be part of usertests. Then it's easier to search for when we put together instructions.

**Comment by jasmussen** [comment]
See also #62

**Comment by mtias** [comment]
My take is that whenever you select across blocks you let go of the notion of block, so anything block specific should be removed. The main action for selecting across block should be to delete or cut/copy. This applies to both prototypes.

**Comment by joyously** [comment]
> My take is that whenever you select across blocks you let go of the notion of block, so anything block specific should be removed. The main action for selecting across block should be to delete or cut/copy. This applies to both prototypes.

I agree with letting go of the block context, but I don't agree with the main actions. Especially for text, how often do you type a few paragraphs and then want to delete or cut/copy?  I suggest that main actions would be formatting such as float right, or centered text, or bigger font, or group into a box with a border and background.

**Comment by jasmussen** [comment]
As this was related to the prototype and we're working on the plugin now, I'm closing this in favor of #62.
