### ISSUE TITLE
Incredibly difficult to select Custom HTML Block in preview mode

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#27901]
**Describe the bug**
Once you insert a Custom HTML Block and then view it in Preview mode, it's incredibly difficult to re-select that block.
Clicking on the block doesn't allow you to select it. There's only a very small gap below the embedded iframe where you can click that will actually select the block.

Vid: https://share.getcloudapp.com/WnulmbNY

**To reproduce**
1. Insert a Custom HTML Block
2. Insert some html into the Block
3. Select Preview from the Block Toolbar
4. Click out of the block and then try to reselect the Custom HTML Block

**Expected behavior**
It shouldn't be this difficult to select blocks

**Screenshots**
See vid above

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? 

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1 (20B29)
 - Browser: Firefox 84.0

**Comment by annezazu** [comment]
Replicated this with Gutenberg 9.6.2 and WordPress 5.6! Thanks for reporting @maddisondesigns.

**Comment by kujain** [comment]
I can confirm that this is happening for embed blocks as well. Here's a video showing an embed (youtube) block not being selectable initially. The only way I am able to get it to work is to drag-select across multiple adjoining blocks first and then it becomes selectable!

https://user-images.githubusercontent.com/120631/111035828-30d84d80-83ea-11eb-9baa-81d7c9d05d2f.mov

OS: macOS Catalina 10.15.7
Browser: Chrome 89
Gutenberg: 9.6.2
WP: 5.7

**Comment by carolinan** [comment]
I am not able to reproduce this in WordPress 6.0.1, chrome, on mac os:


https://user-images.githubusercontent.com/7422055/180151297-76df4aeb-6f61-4fba-b8af-3d72fea8347b.mov

**Comment by carolinan** [comment]
Nor with a Youtube embed:

https://user-images.githubusercontent.com/7422055/180152039-00f71fa7-8b52-45df-9d01-754d58387260.mov

**Comment by maddisondesigns** [comment]
@carolinan It seems to be working a lot better now than when I originally raised this issue

**Comment by alexstine** [comment]
Looks like this issue can be closed out or is further work needed here?
