### ISSUE TITLE
ComboboxControl convert label to text not pure HTML.

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#27917]
Hi, currently I am working on an icon block for Gutenberg.
As we have "ComboboxControl" there is a great feature to build this block simply.
However, a problem that I have is simple I need its label to be respective to HTML; now whatever I put in this "ComboboxControl" as option label convert to a string instead of being pure HTML.
I need the "ComboboxControl" options label to be HTML to show how the icon will be, like a preview.

This is options array:
`  
options={
 [
                                                    {
                                                        value: 'person',
                                                        label: '<i class="icons">person</i>',
                                                    },
                                                    {
                                                        value: 'event',
                                                        label: '<i class="icons">event</i>',
                                                    },
                                                ]
                                            }
`

- This is what happens in the page source:

![wrong](https://imgupload.io/images/2020/12/29/19056e714c420bc96.jpg)

- This is what it should be:

![correct](https://imgupload.io/images/2020/12/29/2f7a90073182be1e7.jpg)

- This is what should be and should not be:

![correct](https://imgupload.io/images/2020/12/29/3.jpg)

So is there any solution for this?

**Comment by annezazu** [comment]
@amirmp3 this is more of a support request than bug or enhancement request. As a result, I'm going to close this out! The best place to get help for these sorts of things going forward is the forums: https://wordpress.org/support/forums/

**Comment by amirmp3** [comment]
I think there is a lack of the practical feature, a function called `r.label.toLocaleLowerCase()` give me the error when I write JSX for labels.
 **r.label.toLocaleLowerCase is not a function**
So there will be a feature like this for customized select (ComboBox) to the developer be able to put pure HTML for labels.

**Comment by noisysocks** [comment]
`ComboboxControl` will insert the `label` attribute as-is so you should be able to provide a React element.

```
options={ [
	{
		value: 'person',
		label: <i className="icons">person</i>,
	},
	{
		value: 'event',
		label: <i className="icons">event</i>,
	 }, 
] }
```

**Comment by amir2mi** [comment]
@noisysocks Thanks! that worked for the list but when an item is selected input does not show text:
![combo](https://user-images.githubusercontent.com/64708228/118877545-d2f14600-b903-11eb-95ad-e8a580d06d2c.png)

**Comment by seothemes** [comment]
Why closed?
