### ISSUE TITLE
Site Logo block: additional unnecessary "a" tag

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#27918]
**Describe the bug**
The Site Logo block has unnecessary additional "a" tags, resulting in invalid markup.

**To reproduce**
1. Insert the Site Logo block in a post/page and preview/publish
2. View source code of post/page
3. See error: `<a href="http://my-dev-site" rel="home" title="Site Title"><a href="http://my-dev-site/" class="custom-logo-link" rel="home" aria-current="page"><img loading="lazy" width="90" height="45" src="http://my-dev-site/wp-content/uploads/2020/12/logo.jpg" class="custom-logo" alt="Site Title" /></a></a>`

**Expected behavior**
 `<a href="http://my-dev-site/" class="custom-logo-link" rel="home" aria-current="page"><img loading="lazy" width="90" height="45" src="http://my-dev-site/wp-content/uploads/2020/12/logo.jpg" class="custom-logo" alt="Site Title" /></a>`
or
`<a href="http://my-dev-site" rel="home" title="Site Title"><img loading="lazy" width="90" height="45" src="http://my-dev-site/wp-content/uploads/2020/12/logo.jpg" class="custom-logo" alt="Site Title" /></a>`

**Location of issue:**
'build/block-library/blocks/site-logo.php':
L25: `$custom_logo = get_custom_logo();`

L36: `$html = sprintf( '<div %s><a href="' . get_bloginfo( 'url' ) . '" rel="home" title="' . get_bloginfo( 'name' ) . '">%s</a></div>', $wrapper_attributes, $custom_logo );`

The issue is that `get_custom_logo()` is already wrapped with "a" tag, so the extra link to the homepage is not needed.
`$html = sprintf( '<div %s>%s</div>', $wrapper_attributes, $custom_logo );` at L36 would be all that is needed.

**Editor version :**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.6.2

**Comment by Soean** [comment]
I can reproduce the bug and will try to fix it.
