### ISSUE TITLE
Unable to remove block when plugin is no longer installed or activated

### ISSUE THREAD

**Issue by vertizio** [WordPress/gutenberg#27916]
**Bug description**
When a plugin with blocks is disabled, it is not possible to remove the blocks from that plugin inside the editor. You have to install or activate the plugin again and then remove the block. However when the plugin causes fatal errors it is not recommended to reinstall or reactivate the plugin.

**To reproduce**
1. Install plugin which has blocks
2. Open editor and use the block from the plugin and publish page/post
3. Disable plugin from step 1
4. Open page/post from step 2, an error will be visible "Your site doesn't include support for the PLUGIN block. You can try installing the block or remove it entirely."
5. Try to remove the block: there is no handle or way to select the block and remove it.

**Expected behavior**
Handle that allows removing the block without having to reactivate the plugin.

**Screenshots**
![Selection_331](https://user-images.githubusercontent.com/2759239/103280582-11c44500-49d1-11eb-97f6-9c08bb975cb5.png)

**Editor version:**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **default**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 84.0.1

**Comment by annezazu** [comment]
@vertizio thanks for reporting this! I tried three different plugins to get a sense of what might happen in each case. As you can see in the screenshot below, the results are different each time:

<img width="1375" alt="Screen Shot 2020-12-29 at 10 45 27 AM" src="https://user-images.githubusercontent.com/26996883/103303365-066a1d00-49c3-11eb-917f-7d55b74a7f56.png">

Here are links to the respective plugins with blocks that I used:

- https://wordpress.org/plugins/luckywp-table-of-contents/ (installed from Plugins > Add New; the one you mention in your issue)
- https://wordpress.org/plugins/details-summary-block/ (installed from the block directory)
- https://wordpress.org/plugins/jetpack/ using the contact info block (installed from Plugins > Add New)

The result was as follows:
- LuckyWP: only able to reinstall the plugin. 
- Details & Summary Block: able to reinstall or convert to HTML. No option to outright delete until taking one of those initial actions.
- Jetpack: able to delete outright.

Here's a video showing the Jetpack block being easily removed:

https://user-images.githubusercontent.com/26996883/103303070-53012880-49c2-11eb-93d3-ac30b0612880.mp4

@tellyworth is this perhaps related to the block directory functionality? What should be expected here?
