### ISSUE TITLE
When a formatted hyper link of an oEmbed provider is pasted, ask the user whether to paste or embed 

### ISSUE THREAD

**Issue by mipon** [WordPress/gutenberg#27915]
**Is your feature request related to a problem? Please describe.**
A recent version of Microsoft Edge has the built-in functionality that automatically creates a hyper link by copying a URL in the address bar ([for details](https://support.microsoft.com/en-us/microsoft-edge/improved-copy-and-paste-of-urls-in-microsoft-edge-d3bd3956-603a-0033-1fbc-9588a30645b4)). The problem is for embeddable URLs. If the user unknowingly pastes it in the editor, a plain hyper link appears instead of an embedded iframe. The confusing part of this behavior is that if the copied URL is pasted in notepad, a plain URL is pasted instead of a hyper link normally. In fact, I mistakenly created [an issue](https://github.com/WordPress/gutenberg/issues/27911) by thinking this is a bug.

This Microsoft Edge behavior affects the user experience regarding automatic embedding functionality that WordPress provides. End users with little experience with Microsoft Edge might think it is a fault of WordPress or never notice WordPress has such a feature that enables to embed contents by just pasting a single URL.

**Describe the solution you'd like**
1. Monitor paste events.
2. Do nothing if the pasted text includes multiple URLs.
3. When a hyper link with a single URL is pasted and it is one of the oEmbed providers, do either of: 
 a. only allow the URL to be pasted so that the automatic embedding process starts.
 b. ask the user to paste the hyperlink or the URL

**Comment by jasmussen** [comment]
Thank you for the ticket! Is this related to https://github.com/WordPress/gutenberg/issues/21789? Potentially a duplicate?

**Comment by mipon** [comment]
Looks like it.

**Comment by jasmussen** [comment]
Mind if I close that one in favor of the other? I'll be sure to link to yours from there so the feedback doesn't get lost.

**Comment by mipon** [comment]
No, I don't mind.
