### ISSUE TITLE
Fullscreen mode keyboard shortcut not working consistently

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27923]
The fullscreen mode keyboard shortcut Ctrl+Shift+Alt+F is not working for me, but I can use the Visual/Code editor shortcut Ctrl+Shift+Alt+M.

**Original report by urvik1, with screenshots**
https://core.trac.wordpress.org/ticket/52053

https://www.screenpresso.com/=MS16c
Version: https://www.screenpresso.com/=NDvyc
microsoft edge: https://drive.google.com/file/d/1OoVlRZFZi4-tJ5GWIoBgXhqEN6gdaFCW/view?usp=drivesdk
chrome: https://drive.google.com/file/d/1ch-dCHV6VICgGqZhHHJqxXPzF1-V7bmp/view?usp=drivesdk

**Editor version (mine):**
 - WordPress version: 5.6, both with default block editor and with plugin version 9.6.2

**Desktop:**
 - OS: Windows 10
 - Browsers: Firefox 84.0.1, Chrome 87.0.4280.88

**Comment by youknowriad** [comment]
I can't test on windows but I have no issues on Mac on any browser, I wonder if it's a conflict with a particular windows shortcut or if it's specific to your own setup?

**Comment by sabernhardt** [comment]
I could have run a search before moving the report here. It apparently is a Windows shortcut since version 1903, and I was using 1909.
https://superuser.com/questions/1445551/what-does-ctrlaltshiftf-key-combination-in-windows-10-pro-version-1903-do

I'm upgrading to 20H2 and I'll see if Windows has un-reserved the shortcut.

**Comment by sabernhardt** [comment]
It works for me now with Windows 10 version 20H2. I think we can close this.
