### ISSUE TITLE
ENV: Error when trying to map the uploads folder

### ISSUE THREAD

**Issue by skrichten** [WordPress/gutenberg#27922]
**Describe the bug**
Error when trying to map the uploads folder in .wp-env.json...
Duplicate mount points: [X:\uploads:/var/www/html/wp-content/uploads:rw, phpunit-uploads:/var/www/html/wp-content/uploads:rw]

**To reproduce**
1. try to map the uploads folder with .wp-env.json
```
{
  "mappings": {
    "wp-content/uploads": "/somefolder/uploads"
   }
}
```
2. Try to start the environment with `wp-env start`

**Expected behavior**
The environment starts with the local uploads folder mapped.

**Editor version:**
- WordPress version:  default from wp-env

**Desktop:**
 - OS: Windows

Seems like wp-env hard codes the uploads folder for phpunit so when a mapping is created for the environment it is now a duplicate.  from the generated docker-compose.yml...
```
      - 'X:\uploads:/var/www/html/wp-content/uploads'
      - 'phpunit-uploads:/var/www/html/wp-content/uploads'
  ```

**Comment by timnolte** [comment]
Hmm, I'm wondering if this is a regression related to the work I did with #25268 I will try to look into this.

**Comment by noahtallen** [comment]
> Seems like wp-env hard codes the uploads folder for phpunit so when a mapping is created for the environment it is now a duplicate.

Yeah, this would also be my intuition. Probably not related to the PHP version stuff, hopefully!
