### ISSUE TITLE
Combobox control "u" is not a function

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#27921]
There is a problem since I started working around Gutenberg **Comboboxcontrol**.

I just copy and paste example code from [the handbook in WordPress.](https://developer.wordpress.org/block-editor/components/combobox-control/#usage) 
Everything works fine and also value saves without any problem but on the focus (Focus on Comboboxcontrol), an error will be shown in the browser console:
![error firefox](https://s17.picofile.com/file/8419392692/Annotation_2020_12_29_231507.jpg)

And this is also the error in Chrome 87:
![error chrome](https://s16.picofile.com/file/8419396468/Annotation_2020_12_29_235007.jpg)
After installing the Gutenberg plugin in WordPress error "u" changed to "l", so why does this error happen?

 - OS: Windows 10
 - Browser Firefox 
 - Version 84.0.1 (64-bit)

**Comment by youknowriad** [comment]
I'm trying to the Combobox control here in Storybook and I don't reproduce https://wordpress.github.io/gutenberg/?path=/story/components-comboboxcontrol--default  

There might be something specific to your own usage?

**Comment by amirmp3** [comment]
This story page is great I was searching for something like this!
Unfortunately, I had this problem and did not find the reason so I created something like this myself.
