### ISSUE TITLE
Reusable Block: Multiple blocks in one posts fail

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#27932]
**Describe the bug**
If I add a reusable block multiple times to a post, save and reload the editor, the rendering fails.

Tested in Mac/Chrome with 9.7.0-rc.1

@youknowriad

**Comment by youknowriad** [comment]
Quickly tested this, I was not able to reproduce but I'll test deeper tomorrow.

**Comment by youknowriad** [comment]
Ok, so I was able to reproduce from time to time, it seems like some kind of race condition, I'll take a deeper look.
