### ISSUE TITLE
Full site editor renders blank page with WooCommerce activated

### ISSUE THREAD

**Issue by hsingyuc** [WordPress/gutenberg#27938]
**Describe the bug**
When activating WooCommerce, the full site editor will render a blank page.

**To reproduce**
1. Use any full site editor capable theme
2. Activate WooCommerce
3. Click on the site editor
4. See blank page

**Expected behavior**
To see the full site editing page

**Screenshots**
Looks like it's hidden by this css
<img width="1440" alt="blank page" src="https://user-images.githubusercontent.com/56378160/103388506-5508db80-4ad7-11eb-97a1-bb23df13ac4f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg plugin version 9.6.2

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version 87.0.4280.88

**Comment by hsingyuc** [comment]
This might be where the issue is coming from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3219

The issue is that `wp-edit-post-css` is being loaded which hides various elements and should not be loaded.

`wp-edit-post-css` is not an actual dependency of WC Blocks, but is used to load the editor css before the blocks css.  One solution might be to remove this dependency and fix the ordering of the stylesheets in a different way.

Another option would be to not add this dependency on site editor pages.

**Comment by youknowriad** [comment]
Thanks for testing WooCommerce and FSE.

I think this is better raised in the woocommerce tracker instead, there's nothing we can do from Gutenberg side.

**Comment by Aljullu** [comment]
Thanks for the report @hsingyuc, I opened an issue in WC Blocks repo to investigate this: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3626.

**Comment by strarsis** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/45170
