### ISSUE TITLE
Gutenberg list block RTL support

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#27937]
Hi, recently I used Gutenberg list block also I checked it in RTL as I found it has a problem with padding and margin for first depth and nested lists.
The main problem is the list properties are not inverted for RTL.

The below image show this obviously:
![list block problem in rtl](https://s16.picofile.com/file/8419525850/Annotation_2020_12_31_023937.jpg)

**Comment by guarani** [comment]
Hi, thanks for reporting! Judging by the screenshot, this looks like Gutenberg web (perhaps on a mobile device), so I'll go ahead and remove the `Mobile App Android/iOS` label since we use that exclusively for Gutenberg Mobile, which is a native mobile variant of Gutenberg. If you think this is incorrect, please leave a comment.

**Comment by amirmp3** [comment]
> 
> 
> Hi, thanks for reporting! Judging by the screenshot, this looks like Gutenberg web (perhaps on a tablet), so I'll go ahead and remove the `Mobile App Android/iOS` label since we use that exclusively for Gutenberg Mobile, which is a native mobile variant of Gutenberg. If you think this is incorrect, please leave a comment.



> 
> 
> Hi, thanks for reporting! Judging by the screenshot, this looks like Gutenberg web (perhaps on a tablet), so I'll go ahead and remove the `Mobile App Android/iOS` label since we use that exclusively for Gutenberg Mobile, which is a native mobile variant of Gutenberg. If you think this is incorrect, please leave a comment.

No there is no problem since I am a noob in GitHub that was my wrong :)

**Comment by youknowriad** [comment]
Hi There! do you mind sharing which theme you're using?

**Comment by amirmp3** [comment]
Hi again as I see this is a problem for RTL I have checked this with 2017, 2019, 2020, WordPress themes and I would say the problem is the same.

2017:
![2017](https://s17.picofile.com/file/8419848542/2017.jpg)

2019:
![2019](https://s17.picofile.com/file/8419848676/2019.jpg)

2020:
![2020](https://s16.picofile.com/file/8419848768/2020.jpg)

The problem is really simple and I solved this for my case with these lines of CSS:

we have these codes for LTR:
```
.editor-styles-wrapper ol, 
.editor-styles-wrapper ul {
	padding-left: 1.3em;
	margin-left: 1.3em;
}
```

This is what I have done:
```
body.rtl .editor-styles-wrapper ol, 
body.rtl .editor-styles-wrapper ul {
	padding-right: 1.3em;
        padding-left: 0;
}

body.rtl .editor-styles-wrapper ol ol, 
body.rtl .editor-styles-wrapper ol ul, 
body.rtl .editor-styles-wrapper ul ol,
body.rtl .editor-styles-wrapper ul ul {
	margin-right: 1.3em;
        margin-left: 0;
}
```
