### ISSUE TITLE
Backspace lags behind

### ISSUE THREAD

**Issue by Micu22** [WordPress/gutenberg#27959]
**Describe the bug**
When writing blog posts you often need to delete the last couple of letters or words.
You use `backspace` for deleting letters and `ctrl + backspace` to delete words. In both cases holding backspace for longer than the time to delete three letters/words results in a lag: no words are deleted until you release `backspace`, but when you do so, many words are deleted at once.

It is hard to delete when you don't know how much have you already deleted. Only way for now is to delete one letter or one word at a time by tapping `backspace` – pressing and holding results in a lag.

**Editor version (please complete the following information):**
- WordPress version: 5.6

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser chrome
In other editors like Evernote for web or github bug report the issue is not present, so it cannot be a browser problem.

**Comment by Micu22** [comment]
I have tested it more, and I have another thing to add.
The bigger the post, the bigger the lag.

It still shouldn't be present. for example I can easily write and edit text in Evernote web even if the note has 50.000 characters.
In gutenberg editing is starting to lag on notes with less than 2000 characters.

**Comment by youknowriad** [comment]
Hi there! we did several performance improvements since WP 5.6, It depends on the computer of course just tried in Safari with 1000 blocks, it's decent enough. Of course, performance never stops and we'll continue monitoring and making improvements.
