### ISSUE TITLE
Please add « Definition list block » {Semantic list}.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#27953]
Hi,
I would like that you a new block,
to be able to easily create Definition list (`<dl>` `<dt>` `<dd>`).

Each enter-key will change `<dt>` to `<dd>`, then `<dt>` `<dd>`,
two enter‑key will add a space an new `<dl>` `<dt>` `<dd>`.

Etc.

Please, Dê‑vêlo‑pr’s.
thank you and jood job & continuation.

**Comment by Soean** [comment]
Hi @Nemzag, thanks for your proposal. We already have an issue for this kind of block, see #4880. So I close this one, please use the existing for further discussions.
