### ISSUE TITLE
Multisite support for @wordpress/env

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#27961]
Setting up a multi-site WP install for WordPress is a not so simple multi-site process and doing so based on containers... is even more complex. It would be awesome if we were able to do so using `@wordpress/env` by enabling a flag or some config.

**Comment by jonnynews** [comment]
Now that WordPress supports custom ports in mutlisite, this work should be much easier - https://github.com/WordPress/wordpress-develop/commit/7750458133663a8bae9a36cc36ab29e563675620

**Comment by davidperezgar** [comment]
Awesome news!
