### ISSUE TITLE
Inline custom block styles are not visible in the site editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#27962]
**Describe the bug**
In the site editor, custom block styles that are [registered using `inline_style`](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#register_block_style) are selectable but the styling is not visible in the sidebar preview or in the editor.

**To reproduce**
1. Activate a full site editing theme with inline custom block styles _-Not TT1 Blocks, it adds the custom styles directly in the editor style._
2. Open the site editor
3. Select or add a block that has custom block styles.
4. See that the style is not applied to the block.

**Expected behavior**
The inline custom styles must work.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- If the Gutenberg plugin is installed, which version is it? 9.6.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 87.0.4280.88

**Comment by carolinan** [comment]
To test this you can add this inline style to any FSE theme, a columns block, and preview and select the style.

```
	register_block_style(
		'core/columns',
		array(
			'name'         => 'test',
			'label'        => __( 'test' ),
			'inline_style' => '.is-style-test {border:1px solid red;}',
		)
	);
```

**Comment by aristath** [comment]
I tracked this down to the `wp_should_load_block_editor_scripts_and_styles` function in wp-core.
It is used to determine if the styles will be loaded or not, and it currently only checks for the post-editor screen.
In the Gutenberg plugin we add filters on `should_load_block_editor_scripts_and_styles` and we load the styles on the navigation & widget pages, but not on the site-editor.
I don't know if that is on purpose or an omission... 🤔 
@youknowriad do you have any idea why we don't load it in the site-editor? Could this be related to the recent issue we were discussing about stylesheet priorities etc?

**Comment by youknowriad** [comment]
I think it's omission yes, I'm not sure it's related to the stylesheet priorities.

**Comment by aristath** [comment]
PR in https://github.com/WordPress/gutenberg/pull/30448

**Comment by eri-trabiccolo** [comment]
Hello, looks like this issue has back. I'm using WordPress 6.1 here.

**Comment by stellarwebworks** [comment]
This is still an issue in WP 6.3.1. The block styles show up in the sidebar when adding a new columns block, but when editing an existing column the Styles section is missing in the sidebar.
