### ISSUE TITLE
Add an option for the Group block to set the inner blocks as inline-blocks

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#27978]
**Is your feature request related to a problem? Please describe.**
I'm trying to place some text next to a button. I want to use the core paragraph block and the core buttons block. I'm placing them inside a Group block, and I would like to make the inner blocks (the paragraph and the button) be displayed as `inline-block`.

**Describe the solution you'd like**
A style that allows the blocks inside the Group block to be displayed as inline blocks, similar to the Social Icons or the Navigation block.

**Describe alternatives you've considered**
Adding my own class with custom CSS.

**Comment by talldan** [comment]
@chvillanuevap Thanks for reporting this. There are a few issues that touch upon the general subject of the layout of inner blocks:
- https://github.com/WordPress/gutenberg/issues/24473
- https://github.com/WordPress/gutenberg/issues/21494
- https://github.com/WordPress/gutenberg/issues/27324

And there are probably more, that was just a quick search. I think this is something on the radar.

I'm going to close this one. Would you be able to comment on the most relevant issue? I think the first one looks the closest.
