### ISSUE TITLE
List Block: Add option to use "checkbox" symbol

### ISSUE THREAD

**Issue by davipontesblog** [WordPress/gutenberg#27976]
The list block currently allows users to use two options for their lists:
- Unordered list
- Ordered list

<img width="1146" alt="Screen Shot 2021-01-04 at 15 27 19" src="https://user-images.githubusercontent.com/31009008/103576631-708e3080-4ea1-11eb-8c6e-e81f6f20a4f6.png">

This is a proposal to add an option for a "checkbox" style to the "unordered list". It can be accomplished with CSS the following way:

```
.checkbox {
	list-style: none;
}
.checkbox li:before {
	content: '☑';
	margin-right: .5em;
}
```

**Comment by Soean** [comment]
Hi @davipontesblog, thanks for opening this issue.
We already have #15005 as an open issue for this feature. I am closing this one, please use the existing one for further discussions.
