### ISSUE TITLE
Enable Gutenberg editor for category/taxonomy

### ISSUE THREAD

**Issue by Wohlfarth** [WordPress/gutenberg#27971]
**Description of the problem**
Editing categories and/or taxonomies (name, slug, description, etc) can currently only be done with the MCE editor.

In our case, the taxonomy "category" is used as main section entries where categories have a content layout similar to pages.

**Preferred solution**
From our perspective, it would be very useful to have the possibility to enable the Gutenberg Editor in such a case, similar to custom content types that are enabled using that sort of parameters:
  'supports' => array( 'title', 'editor'),
  'show_in_rest' => true,

**More comments**
I have been following this issue https://github.com/WordPress/gutenberg/issues/12511. That issue was unfortunately closed with the mention that it would be placed into the "Ideas project" for future enhancements. There seems not much going on for now with this feature. Any alternative solution would be very appreciated.

Thanks much for your feedback.

**Comment by Soean** [comment]
Hi @Wohlfarth,
thanks for opening this issue. I would also like to have this feature in WordPress. 
We already have #17099 as an open issue for this feature. I am closing this one, please use the existing one for further discussions.
