### ISSUE TITLE
Kindle embed loses captions on edit

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#27980]
**Describe the bug**

If I edit a post created prior to the WordPress 5.6 update, Kindle Embeds all show an error: This block contains unexpected or invalid content. If I hit the Attempt Block Recovery button, it recovers the block and keeps the caption, thankfully. So it's annoying to have to do on every single Kindle Embed block on old content, but it's not the end of the world.

However...
If I edit an existing post that was either created or updated after 5.6, the Kindle embeds all automatically refresh upon edit post pageload. (&action=edit) Not something I want to happen. It's as though their URLs have just been added, but the page just loaded, so it's not caused by something I did. Unfortunately, all the blocks refresh so fast I can't grab a screenshot except after the damage is done. After that automatic refresh, the Kindle embeds lose their captions. This has only begun happening since the most recent wordpress update 5.6 using the default Guten Kindle embed block.

Originally reported [here](https://core.trac.wordpress.org/ticket/52077)

**Comment by kathrynwp** [comment]
Hi @tellthemachines - if this is still an issue in the latest version of WordPress, could you please provide steps to replicate, along with a sample URL for embedding? I don't have a Kindle so I'm not sure what the URL format is supposed to look like. Thanks very much!

**Comment by jordesign** [comment]
Hi @tellthemachines  - as there's been no further information on this issue in about a year - I'm going to close it out.

If this issue _is_ still in place - please feel free to re-open along with any further details on recreating the issue.
