### ISSUE TITLE
Popover position should be calculated based on is-from-[origin]

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#27993]
Popover menus are currently always centered according to the width of the opener element.

At the same time, for animation purposes, a `'is-from-' + origin` can be applied. For most menus in block toolbar, that happens to be `is-from-left`. 

Currently it looks right in most cases:

![with compensation](https://user-images.githubusercontent.com/1204802/103641237-be627180-4f51-11eb-90bf-3d610d6b81d0.gif)

But this is smoke and mirrors! The following CSS rule compensates for it:

<img width="371" alt="Screenshot 2021-01-05 at 12 27 36" src="https://user-images.githubusercontent.com/1204802/103641255-c6221600-4f51-11eb-8c84-1b72bdd8c0d6.png">

Those 25px happens to be the icon size of 24 plus the borderwidth of 1. Without this compensation margin, you can see what's up:

![without compensation](https://user-images.githubusercontent.com/1204802/103641305-d934e600-4f51-11eb-9abc-68bd8331871f.gif)

The problem with this hack is that it falls apart for anything that isn't a 24px icon button:

<img width="693" alt="Screenshot 2021-01-05 at 12 20 58" src="https://user-images.githubusercontent.com/1204802/103641372-f5388780-4f51-11eb-9699-2f001ce66a0c.png">

This is further exacerbated for buttons that are wider than a "Replace" button:

<img width="665" alt="Screenshot 2021-01-05 at 12 21 13" src="https://user-images.githubusercontent.com/1204802/103641413-01244980-4f52-11eb-9d0c-709e85e244b8.png">

In other words, the popover centering math could use a little enhancement:

1. If the popover opens `is-from-center`, the current behavior is correct. See document outline:

<img width="509" alt="Screenshot 2021-01-05 at 12 32 56" src="https://user-images.githubusercontent.com/1204802/103642068-eef6db00-4f52-11eb-90dd-533e05dd7562.png">

2. If the popover opens from `is-from-left`, the popover needs to calculate its position based on the top left button of the opener. So, instead of this:

<img width="635" alt="Screenshot 2021-01-05 at 12 39 56" src="https://user-images.githubusercontent.com/1204802/103642242-2bc2d200-4f53-11eb-8cd5-0381dbf02a0e.png">

It should be this:

<img width="664" alt="Screenshot 2021-01-05 at 12 40 12" src="https://user-images.githubusercontent.com/1204802/103642282-33827680-4f53-11eb-899b-47da8c788992.png">

**Comment by jasmussen** [comment]
CC: @ellatrix — do you have any insights on how hard this might be to address? There's some related code in https://github.com/WordPress/gutenberg/blob/master/packages/components/src/animate/index.js#L40 that the popover positioning should probably be aware of.

**Comment by tellthemachines** [comment]
Related: #21275 where there has been a bit of back and forth about this already.

**Comment by jasmussen** [comment]
Oh wow, thank you.

Closing this one in favor of #21275.
