### ISSUE TITLE
Change content position (Cover). Each time the position is reset.

### ISSUE THREAD

**Issue by mupic** [WordPress/gutenberg#27994]
**Describe the bug**

**To reproduce**
1. Go to https://wordpress.org/gutenberg/
2. Click on "add block" and select "Cover".
4. Try changing the position of the content, remove focus from that button and click on it again.

**Expected behavior**
When you press the button to change the position of the content, each time the initial position (top left) is selected.

**Screenshots**
![bug-cover-position-change](https://user-images.githubusercontent.com/15020351/103644790-5f602500-4f70-11eb-88dc-bf3189b4253f.gif)

**Editor version (please complete the following information):**
- Gutenberg 7.6.2

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce the issue. Fixed via #27945.

https://user-images.githubusercontent.com/240569/162888565-fda93289-d016-472c-b846-d5bc3e86b8da.mp4
