### ISSUE TITLE
gutenberg_pre_init() does not prevent plugin from loading

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#27998]
**Describe the bug**

When using Gutenberg on WP < 5.3, `gutenberg_pre_init()` will trigger an admin notice and won't load `lib/load.php` because of that.

However, the rest of the code in `gutenberg.php` is still executed, including all the `add_action` calls, like `gutenberg_menu()`.

That function in turn calls `gutenberg_use_widgets_block_editor()`, which only exists if `load.php` is loaded.

Because of that, on WP < 5.3 you will not get any admin notice, but instead this fatal error:

```
Fatal error: Call to undefined function gutenberg_use_widgets_block_editor() in /var/www/html/wp-content/plugins/gutenberg/gutenberg.php on line 47
```

**To reproduce**
1. Try to activate Gutenberg on WP < 5.3 (e.g. by using wp-env)
2. See fatal error

**Expected behavior**

Admin notice instead of fatal error

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: Anything below 5.3
- Gutenberg version: 6.2

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by noisysocks** [comment]
We don't support versions less than 5.3.

https://github.com/WordPress/gutenberg/blob/35a94fd636076acdad00d663eca684191151e8fb/gutenberg.php#L6

**Comment by swissspidy** [comment]
@noisysocks I think you misunderstood the purpose of this ticket. I'll try to explain it differently :)

I **know** that Gutenberg does not support WP < 5.3.

There's even this function that should warn the user about it:

https://github.com/WordPress/gutenberg/blob/35a94fd636076acdad00d663eca684191151e8fb/gutenberg.php#L139-L151

However, **it does not work** as intended. Neither does `gutenberg_build_files_notice` run as intended.

That's because there's a **fatal error** happening before this code can even run.

This ticket is about this fatal error and how this logic needs to be fixed so that this notice is being displayed as intended.

**Comment by noisysocks** [comment]
Ah! Thanks for clarifying 🙂

**Comment by xavortm** [comment]
I have just installed WordPress-Develop and on latest master + latest master Gutenberg repository, I am still getting this fatal error after activating the plugin :/ 

```
Fatal error: Uncaught Error: Call to undefined function gutenberg_use_widgets_block_editor() in /var/www/src/wp-content/plugins/gutenberg/gutenberg.php:128 Stack trace: #0 /var/www/src/wp-includes/class-wp-hook.php(292): modify_admin_bar(Object(WP_Admin_Bar)) #1 /var/www/src/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #2 /var/www/src/wp-includes/plugin.php(551): WP_Hook->do_action(Array) #3 /var/www/src/wp-includes/admin-bar.php(95): do_action_ref_array('admin_bar_menu', Array) #4 /var/www/src/wp-includes/class-wp-hook.php(292): wp_admin_bar_render('') #5 /var/www/src/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) #6 /var/www/src/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #7 /var/www/src/wp-includes/general-template.php(3037): do_action('wp_body_open') #8 /var/www/src/wp-content/themes/twentytwentyone/header.php(24): wp_body_open() #9 /var/www/src/wp-includes/template.php(730): require_once('/var/www/src/wp...') #10 /var/www/src/wp-includes/template.php(676): in /var/www/src/wp-content/plugins/gutenberg/gutenberg.php on line 128
```

So the WP version is 5.7, not <5.3; Gutenberg v.9.7.1

I might be missing something obvious, it's my first time setting up the two. Considering how the fatal error showed up right after doing the latest pull from both, I guess I might be wrong as I am not finding it reported, but still, posting if it helps. Apologies if this needs a separate ticket

**Comment by swissspidy** [comment]
@xavortm Since you are using Gutenberg master Have you built Gutenberg properly? `npm install && npm run build`

**Comment by xavortm** [comment]
Apologies :( I did `npm install` and then `npm run build`, the same error shows up. It was after the `npm run dev` that worked. Sorry!

**Comment by bph** [comment]
>Call to undefined function register_block_type_from_metadata() points to the WP version being older than 5.5.x, because that function was added to Core in 5.5. (@tellthemachines )

The call to the undefined function will still not be in older versions and cause and error right?  Unless older versions receive an update the block-editor code that uses the function that gets merged into the core would need to check for the function and unless the core team patches older versions… ? 

Roughly 27.14 + 22 50% of all WordPress installs are on 5.5 and 5.6. Another 26.8 % are on 5.2 - 5.4 - What will happen to their editor experience when this will be merged into 5.7? 

_It's very likely, I am missing something essential, though. Please for give my ignorance. _

**Comment by gziolo** [comment]
The mix of #30230 and #29938 should address this issue.

**Comment by gziolo** [comment]
> The mix of #30230 and #29938 should address this issue.

Both PRs landed a while ago. Let's close this issue.
