### ISSUE TITLE
TinyMCE multi-instance - The dropnav for the type of block doesn't go away when clicking other items

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#280]
I opened the block  type dropdown nav list, but changed my mind and decided to just click over in the other toolbar options, but the dropdown nav didn't disappear.

![hide-dropnav](https://cloud.githubusercontent.com/assets/617986/23971652/05c156b4-098c-11e7-9328-30ed18a1bce5.gif)

Can we make that disappear once I click on some other item in the toolbar?

**Comment by jasmussen** [comment]
Having moved on to the plugin, I think this is an okay bug to not fix in the prototypes.
