### ISSUE TITLE
Allow filtering the default value of the post excerpt length.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28001]
**Is your feature request related to a problem? Please describe.**
When using a post excerpt block, the default value is set to 55.

To change this default value in the editor, the block can be filtered.
But this updated default value is not used on the front, because the number 55 is hard coded in index.php:
```
	$filter_excerpt_length = function() use ( $attributes ) {
		return isset( $attributes['wordCount'] ) ? $attributes['wordCount'] : 55;
	};
```
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/post-excerpt/index.php#L24

To update the default value both in the editor and the front, one would have to use both
a block filter, and the [excerpt_length](https://developer.wordpress.org/reference/hooks/excerpt_length/) filter.

**Describe the solution you'd like**
The current default value should be used if the setting has not been changed, the number should not be hard coded.

**Comment by ntsekouras** [comment]
Hey @carolinan 👋 

I was looking at this issue and couldn't understand 100% what you propose. If I understand correctly you use a hook in editor and set the default value `20` let's say. Then use that value in php?

What hook are you using for this, in the editor?

**Comment by carolinan** [comment]
And I did not understand the question.

When using a post excerpt block, the default value is set to 55.
What I want is to change the default value.

I can filter the block with JS (wp.hooks and addFilter) and update the attribute.
But when I do that, the change only affects the editor.

On the front, the block uses PHP, and the value 55 is hard coded. _That is the code example above._

So if I wanted to change the default value, I would have to filter the block using both JS and PHP, and I would like to avoid having to do that.

**Comment by carolinan** [comment]
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-excerpt/index.php#L24    
I don't think that there is any scenario where $attributes['wordCount'] is not set? I'd like to remove the hardcoded value (55) because it is already set as the default for the attribute in block.json.
