### ISSUE TITLE
Editor doesn't handle scroll position correctly when keyboard focus changes

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#28004]
**Describe the bug**

On a long post, if a block has keyboard focus while off-screen, and I tap text in an on-screen block, instead of just showing the keyboard and allowing me to type into the on-screen block, the editor scrolls all the way down to the off-screen block that previously had keyboard focus.

**To Reproduce**
1. Open a long post (two or more screens of content)
2. Put keyboard focus (not block focus) on a block near the bottom of the editor content
3. Manually scroll to the top of the post
4. Tap a block that allows keyboard input and notice that instead of simply showing the keyboard, the editor scrolls down to the block whose input lost focus

**Expected behavior**
The editor should maintain the scroll position if an already visible input gains keyboard focus.

**Screenshots**

| <img src="https://user-images.githubusercontent.com/1898325/101707379-ddacd280-3a69-11eb-95b1-fa9fe8cc22f2.gif" alt="Screen recording showing editor jumping when changing keyboard focus" width="350"> |
| - |

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14
 - Version 1.43.0 and 1.44.0 releases of Gutenberg Mobile

**Comment by mchowning** [comment]
Thanks for reporting this @guarani . I tried this on Android, and it appears this is only an issue on iOS. Just let me know if you think I'm wrong about that.

**Comment by dcalhoun** [comment]
@Guarani I arrived here from wordpress-mobile/gutenberg-mobile#3085. I am no longer able to reproduce this issue on WordPress iOS 16.7. Are you still able to re-produce this issue or should we close this? I'm wondering if it this was fixed by #28352.

**Comment by guarani** [comment]
> @guarani I arrived here from [wordpress-mobile/gutenberg-mobile#3085](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3085). I am no longer able to reproduce this issue on WordPress iOS 16.7. Are you still able to re-produce this issue or should we close this? I'm wondering if it this was fixed by #28352.

Thanks for checking! Yep, I can't reproduce this either on WPiOS 16.7.1 or WPAndroid 16.7 (although I don't think it was ever an Android issue) – closing this.
