### ISSUE TITLE
Moving through block toolbar after pressing alt+F10 hides the toolbar

### ISSUE THREAD

**Issue by diegohaz** [WordPress/gutenberg#28016]
**Describe the bug**

After pressing <kbd>alt+F10</kbd> to focus on the block toolbar, moving through the toolbar items with arrow keys will unexpectedly hide it.

**To reproduce**
1. Create a new post
2. Create a paragraph and write some text
3. With the block toolbar hidden, press <kbd>alt+F10</kbd>
4. Move through the toolbar items using arrow keys

**Expected behavior**

The toolbar shouldn't hide when using arrow keys.

**Screenshots**

![Using the block toolbar](https://user-images.githubusercontent.com/3068563/103775265-95eb7d80-500c-11eb-89f6-6c59976308f2.gif)

**Editor version (please complete the following information):**

master

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Browser: Chrome
 - Version: 87

**Comment by alexstine** [comment]
I can confirm this is a bug.

The toolbar completely loses focus after using either arrow key.

Tested with NVDA screen reader in Firefox on Windows 7.
