### ISSUE TITLE
New button

### ISSUE THREAD

**Issue by nabi009** [WordPress/gutenberg#28010]
Please add a "new button" for posts after publishing the existing post for entering a new one, like the below picture.
![WhatsApp Image 2021-01-06 at 2 31 56 PM](https://user-images.githubusercontent.com/3170831/103755805-0ce43e80-502c-11eb-9e62-f5aa2aaecb81.jpeg)

**Comment by paaljoachim** [comment]
We talked about this issue during a design triage on Slack: https://wordpress.slack.com/archives/C02S78ZAL/p1612887554344500

Bottom line is that your idea is good only that we believe that this section needs a redesign to make it more useful.
Discussed by
@melchoyce @kellychoffman and myself.

**Comment by kellychoffman** [comment]
One idea: 

<img width="318" alt="Screen Shot 2021-02-12 at 6 28 20 PM" src="https://user-images.githubusercontent.com/5835847/107839358-377a9300-6d60-11eb-9fed-489bbbe64537.png">

**Comment by paaljoachim** [comment]
Hey @nabi009 

I happen to create a duplicate here: https://github.com/WordPress/gutenberg/issues/32099

We can keep both issues open for now.

**Comment by mtias** [comment]
@paaljoachim let's keep a single issue open, please :)

There's also this one which should be a duplicate #25611.

**Comment by paaljoachim** [comment]
Hey @mtias I totally agree..:)
It just happen to become that way for this issue.

If you could take a quick look at: 
**Add a new page/post button on publish panel**
https://github.com/WordPress/gutenberg/pull/33276 and do a code review then we can close all of these issues. It is a small PR. Thank you!

**Comment by mtias** [comment]
Closing in favor of #32099.
