### ISSUE TITLE
File block + top toolbar shows a misaligned button

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#28018]
If you have the top toolbar mode enabled and add a file block, the 'replace' button is misaligned in the toolbar:

![image](https://user-images.githubusercontent.com/1277682/103790566-47080d00-5039-11eb-83d1-a79c45d4d729.png)

**To reproduce**
1. Switch to top toolbar mode
2. Add a file block
3. Assign media to the block
4. Note the toolbar 'replace' is misaligned

**Editor version :**
- WordPress version: 5.6
- Gutenberg: 9.6.1

**Comment by JustinyAhin** [comment]
I can effectively reproduce this on WordPress 5.6 and Gutenberg 9.6.1. Working on a fix.

**Comment by JustinyAhin** [comment]
This has been fixed in the plugin in #29247.
<img width="985" alt="CleanShot 2021-04-01 at 13 33 33@2x" src="https://user-images.githubusercontent.com/33403964/113294545-02fe6e80-92ef-11eb-9f62-316857810500.png">


WordPress version: 5.8-alpha-50510
Gutenberg: 10.3.0
