### ISSUE TITLE
Query Pagination Block warning

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#28014]
**Describe the bug**
When the perPage attribute is removed from the block it throws a warning (https://github.com/WordPress/theme-experiments/pull/149#issuecomment-755154097). We should default this to the WordPress setting when it's missing.

**Comment by ntsekouras** [comment]
Query Pagination in general doesn't work well with all the new changes in Query. I plan to work on it these weeks.

**Comment by ntsekouras** [comment]
Closing this as QueryPagination has been changed here: https://github.com/WordPress/gutenberg/pull/28125
