### ISSUE TITLE
[RNmobile] Multiline Pullquote using break instead of p tag

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#28021]
**Describe the bug**
On Android only, new lines with out trailing whitespace on Pullquotes use `<br>` to separate the lines when it should use a `<p>` tag

**To Reproduce**
1. Add a new Pullquote block
2. Start typing and make sure there are no trailing whitespace characters 
3. Press enter to create a new line
4. Add a second line of text
5. Switch to HTML view and note that the lines are split by a `<br>` tag 
6. Add a new Pullquite block
7. Start typing and add trailing whitespace
8. Press enter to create a new line
9. Add a second line of text
10. Switch to HTML view and note that the lines are split with `<p>` tags

**Expected behavior**
Multiple lines in a Pullquote without trailing whitespace should be split by `<p>` tags

**Screenshots**
![2021-01-06 07 11 51](https://user-images.githubusercontent.com/744755/103802437-faeea580-5003-11eb-9f99-2595f882f761.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11
 - Version 16.4-rc-3

**Comment by jhnstn** [comment]
originally posted here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2967

**Comment by mchowning** [comment]
> originally posted here: wordpress-mobile/gutenberg-mobile#2967

My understanding from reading ^that^ original issue is that this is only an issue on Android. Let me know if that's not right @jhnstn .

**Comment by mchowning** [comment]
Marking this as low priority because it sounds like this isn't hurting the user experience at this time. It's probably just a matter of time until something breaks because of this though (or something is already broken and we haven't found it yet), so it would certainly be good to address this. If we find that this is directly impacting the user experience in some way, let's revisit the priority.

**Comment by jhnstn** [comment]
> > originally posted here: [wordpress-mobile/gutenberg-mobile#2967](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2967)
> 
> My understanding from reading ^that^ original issue is that this is only an issue on Android. Let me know if that's not right @jhnstn .

Correct, this is Android only. I could not reproduce on iOS ( or web for that matter )

**Comment by ellatrix** [comment]
Pull quote is no longer using multiline rich text (#43210), so this issue seems no longer relevant. Please reopen if I'm wrong.

**Comment by dcalhoun** [comment]
From testing the outlined steps now, a `<br>` is inserted on both iOS and Android regardless if a trailing space is present. I am uncertain if something changed in the code or if the original report was mistaken. 

Additionally, our [Pullquote test case](https://github.com/wordpress-mobile/test-cases/blob/315f301247c94d110982685ef171b2f2ee9bfe76/test-cases/gutenberg/writing-flow/multiline-components.md#tc001) asserts that a `<br>` should be used, not a `<p>` tag. We [automated that test case](https://github.com/WordPress/gutenberg/blob/3edb5a6b7bf8097461075323ab12b0889d44c0be/packages/block-library/src/pullquote/test/edit.native.js#L25-L72) recently. 


All that said, I believe it is safe to keep this issue closed.
