### ISSUE TITLE
Reusable blocks: width settings not retained when full-width block made reusable.

### ISSUE THREAD

**Issue by rickybanister** [WordPress/gutenberg#28024]
**Describe the bug**
I added `columns` to my document, put some things inside them, decided I wanted my layout to be full width and changed that setting on the parent columns block. I then converted it to 'reusable' for use elsewhere. In the process my width setting was lost and my reusable block became the standard document width. 

**To reproduce**
1. Create a new page.
2. Add a columns block and put content inside it.
3. Set the columns parent alignment to 'full width'.
4. Convert it to 'reusable'.
5. See the width jump back to default.

**Expected behavior**
I expected the 'reusable block' to just be a dumb wrapper and retain all my inner settings. I could get those back by 'converting to regular blocks', but then I'd lose the advantage of having cascading changes to the inner blocks. Perhaps another solution would be to provide alignment options for the reusable block wrapper, but I'm not sure that would solve the issue. 

**Screenshots**
Columns block set to 'full width':
![image](https://user-images.githubusercontent.com/437258/103809168-1f0fae00-5027-11eb-9233-a1281936e176.png)

After converting to reusable:
![image](https://user-images.githubusercontent.com/437258/103809261-38185f00-5027-11eb-8234-3f32e9d6c4e4.png)

**Comment by talldan** [comment]
I think this issue is covered by https://github.com/WordPress/gutenberg/issues/17640, adding an alignment option to the reusable block toolbar would solve the problem, so I'll close this in favour of that issue.
