### ISSUE TITLE
Add in a feedback option to plugin

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2802]
Whilst in development, maybe we could add a quick, simple feedback mechanism to the interface. This could something super simple, but I think it's important to consider adding something at this stage. There is a movement to get Gutenberg onto more sites, for example WordCamp.org is considering activating it.

I think having a link to a simple form, as an option here would work:

![2017-09-26 at 21 28](https://user-images.githubusercontent.com/253067/30882711-c618b038-a301-11e7-9f6a-db0232ff125b.png)

It would be a single form with option for people to select if feedback or a bug. There would be an option for people to add their GitHub username (if have one) and WordPress username (if have one) for follow ups. Not all will be followed up, of course but it could help for bugs and digging deeper. Then a simple textform which would allow them to write anything. This is not tracking anyone, it's a simple form that is hosted on service like Polldaddy/ Google forms and does not track anything from the click.

What do people think? I personally feel this will help feedback wise.

**Comment by andreamiddleton** [comment]
I think that if we're interested in getting more feedback from folks that don't know how to navigate trac or github (or even that such things exist!), that this would be a great way to do that.

**Comment by missjwo** [comment]
+1. I think this is a great non intrusive method of collecting feedback and having it be fresh and useful to people. 

Please make sure the form has the ability for people to add images and attachements to the form so that people can add screenshots if needs be. 

I think the option for someone to get in touch and ask questions is a good one but I wouldnt count on everyone having a WP.org user name or Github username. Might just want a input field with contact details as an option.

**Comment by buzztone** [comment]
I think it's a good idea provided you have the time to read each submitted form. Great if you can also triage the responses and provide feedback summaries to others on the team.

I also think it's always good to send an email to people who submit the form to thank them and provide info on other points of contact via Github etc. 

I know it seems old fashioned, but I've found people submitting forms on our sites respond well to personal looking emails. They will often reply to these emails when they want to contact us again even months later.

**Comment by androb** [comment]
We have been using Wootric lately and found it is doing everything we need for tracking and responding to feedback (and NPS score). They have a free plan that would probably meet our needs: https://www.wootric.com/pricing/
(I am sure they could also do a deal for an open source project).

**Comment by karmatosed** [comment]
@androb for this case, I feel keeping it simple makes sense. We also have free use of Polldaddy should we need it. https://polldaddy.com/

**Comment by androb** [comment]
Agreed, makes sense for now

**Comment by karmatosed** [comment]
Here is the form: http://wordpressdotorg.polldaddy.com/s/gutenberg-support to add. It's just a start and can be iterated on.
