### ISSUE TITLE
Author role unable to set featured image (Error 403)

### ISSUE THREAD

**Issue by yewzy** [WordPress/gutenberg#28047]
**Describe the bug**
Users with the role of author are unable to set featured images in posts. I am able to replicate this in a fresh installation of WordPress (no plugins, 2021 theme).

2 errors are shown in the console:

`api-fetch.min.js?ver=5f98b08f212ba8fa8b4685ad2e1b1378:2 GET https://dev.msiachild.org/wp-json/wp/v2/media/16?context=edit&_locale=user 403`

`Uncaught (in promise) 
{code: "rest_forbidden_context", message: "Sorry, you are not allowed to edit this post.", data: {…}}
code: "rest_forbidden_context"
data:
status: 403
__proto__: Object
message: "Sorry, you are not allowed to edit this post."
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()`

**To reproduce**
1. Log on to site as an author.
2. Add new post -> Set featured image

**Expected behavior**
The featured image can be selected and shown as preview.

**Editor version (please complete the following information):**
- WordPress version: [5.6]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? ["default"]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 87.0

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ntsekouras** [comment]
Thanks for reporting this @yewzy - I'll close this though as is duplicate of https://github.com/WordPress/gutenberg/issues/18510.
