### ISSUE TITLE
Video Block: when uploading, block width extends to the full width of the editor

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#28057]
**Describe the bug**

When uploading a video using the Video block, the width of the block in the editor changes. This doesn't seem to be common practice with other blocks, such as the image block.

**To reproduce**
1. Go to Posts > Add New
2. Type `/video` to insert a video block
3. Select a video to upload. At this point, here is the block looks like:
![image](https://user-images.githubusercontent.com/426388/104014732-d33e3f80-51b3-11eb-8d5d-c1439048dd0a.png)

4. Once the upload starts, the width changes:
![image](https://user-images.githubusercontent.com/426388/104014767-e3561f00-51b3-11eb-9b2b-4bb8cf6a80ec.png)

**Expected behavior**
I would expect the block to retain its original width during the upload.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by talldan** [comment]
@jeherve Thanks for reporting. I couldn't reproduce:
<img width="660" alt="Screenshot 2021-01-12 at 4 37 41 pm" src="https://user-images.githubusercontent.com/677833/104289814-8ed4db80-54f4-11eb-9dbf-7a18ad7e88c7.png">

Anything special about the video being uploaded that might cause this?

**Comment by jeherve** [comment]
> Anything special about the video being uploaded that might cause this?

It seems to happen regardless of the video I upload. It's worth noting that the width only changes during the upload process, and then revert back to the correct width. Here is a video of the upload process for that Big Buck Bunny video you tested with:

https://user-images.githubusercontent.com/426388/104291618-09353980-54bc-11eb-9749-f3d7085f0e1c.mov

And some screenshots that may make it easier to compare:

**Before uploading**

![image](https://user-images.githubusercontent.com/426388/104291782-43064000-54bc-11eb-9454-a15b0268a94c.png)

**During uploading**

![image](https://user-images.githubusercontent.com/426388/104291807-4d283e80-54bc-11eb-99b1-4e90e67ab386.png)

**After uploading**

![image](https://user-images.githubusercontent.com/426388/104291836-574a3d00-54bc-11eb-94a5-e2e82d77c86f.png)

**Comment by talldan** [comment]
@jeherve We discussed this in a triage session in slack (https://wordpress.slack.com/archives/C02QB2JS7/p1618291685276800)

It looks like this issue is related to Jetpack, the core block doesn't have an uploading state like in your screenshot. This seems to be implemented in the jetpack code base here:
https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/videopress/edit.js#L417-L424
