### ISSUE TITLE
Opinionated color on cover > buttons > button

### ISSUE THREAD

**Issue by megphillips91** [WordPress/gutenberg#28063]
**Theme author nor user can effectively control the button __link color**
The style is in the styles.css for a:visited and finds itself in a weird limbo between user control, block control, and theme control. 

**To reproduce**
1. Create a cover block with #eeeee background color
2. add a buttons block
3. put two buttons - one red background and one #eeeeee background
4. click the buttons from the front end of the site
5. observe the font color of the buttons compared with background color
4. See error - try to fix with theme code - try to fix with editor

**Expected behavior**
This visited color cannot be forced on the user. AND particularly not on the theme developer. In theory the theme developer can create a system of defaults but that is onerous at best and not in keeping with the new spirit of theme development wherein a UX designer should be able to do much of that work in "low code" mode. 

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.6]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] NO
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] NA

**Desktop (please complete the following information):**
 - OS: Big Sur 11.1
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
- While I appreciate the importance of making good accessibility default, I think that ultimately the user must be responsible as to prevent unexpected behaviors. If color controls are provided at the button level, the user is expecting to have control over that setting. 
- Why are we not making more use of the "advanced" tab within the block settings? IMHO this is a great place to throw settings such as active, hover, visited button colors. Set sensible defaults such as making these match the button font color selected by the user and allow users who want to add a contrast for those button states can do so within "advanced".

**Comment by talldan** [comment]
@megphillips91 Would you be happy to update with some screenshots showing the issue? I think that would help those reading the issue.

**Comment by eSilverStrike** [comment]
This issue is driving me nuts. (at least I think it is the same issue she is having)

Here is my case:

For the Gutenberg Editor I created a new style of block using register_block_style for core/button

In Gutenberg for button colors you can only specify the text color and the background color (no hover color and no visited color)

With the css for the button there is no way for me to set the visited color to the same color as the text. Therefore it is always white unless I hard code it to another color which looks like crap depending on the original color of the text for the button and the background.

**Comment by TheFlowerEmpowered** [comment]
I am having the same issue. Is there a way to select the color for a button once it has been clicked? It's changing the text to white on my button which makes it almost invisible. Also, I am only seeing the issue on safari. On chrome, all is ok.

**Comment by jasmussen** [comment]
Pseudo styles can now finally be adjusted in theme.json. Instructions from [this post](https://make.wordpress.org/core/2022/09/01/whats-new-in-gutenberg-14-0-31-august/):

```
"styles": {
    "elements": {
        "button": {
            ":hover": {
                "color": {
                    "background": "blue",
                    "text": "hotpink"
                }
            },
            ":active": {
                "color": {
                    "background": "red",
                    "text": "yellow"
                }
            }
        }
    }
}   
```

Because of that, I'm going to close this one as fixed. If that's not the case, we can reopen!
