### ISSUE TITLE
Change RichText caret place

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#28069]
Hi, I am just trying to figure out how to move RichText caret.
For example, if `getSelectionStart` has offset 123 I wanna change it to 125, it is not like a plain HTML element and does not move with` \t` or space before it.
I've read Gutenberg RichText documentation but it has no example or anything to help me with this case.

**Comment by talldan** [comment]
@amirmp3 I haven't tried this, but RichText is a standard `contenteditable`, have you attempted to use the native functions for achieving this?

Something like this SO question/answer came up when I searched for it:
https://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div

**Comment by amirmp3** [comment]
Hi, thanks I think it will solve my issue somehow.
