### ISSUE TITLE
Update to minimum 5.5 of WordPress to be able to run Gutenberg plugin version 9.7 and newer.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28075]
**Describe the bug**

I went to rootingagents.com and noticed this:

![Screen Shot 2021-01-10 at 16 15 36](https://user-images.githubusercontent.com/5323259/104126831-21437680-535f-11eb-8659-ec7485460486.png)

I received this e-mail:
"[Rooting Agents] Your Site is Experiencing a Technical Issue" 

**content:**

"Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Gutenberg.

First, visit your website (https://rootingagents.com/) and check for any visible issues. Next, visit the page where the error was caught (https://rootingagents.com/wp-login.php) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://rootingagents.com/wp-login.php?action=enter_recovery_mode&rm_token=8J07gwAlSNGjTpa0eAm1YF&rm_key=wnPre2mUMnoVEFpN0TO0E3
"

**I clicked the recovery link and went to the plugin screen.**

![Screen Shot 2021-01-10 at 16 13 46](https://user-images.githubusercontent.com/5323259/104126798-e4777f80-535e-11eb-93c6-2ef2cb10a52e.png)

Printing since 1440. This is the development plugin for the new block editor in core.

Version 9.7.0 | By Gutenberg Team | View details
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_ERROR was caused in line 124 of the file /home/rootibyy/public_html/wp-content/plugins/gutenberg/lib/blocks.php. Error message: Uncaught Error: Call to undefined function register_block_type_from_metadata() in /home/rootibyy/public_html/wp-content/plugins/gutenberg/lib/blocks.php:124 Stack trace: #0 /home/rootibyy/public_html/wp-includes/class-wp-hook.php(287): gutenberg_reregister_core_block_types('') #1 /home/rootibyy/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/rootibyy/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/rootibyy/public_html/wp-settings.php(540): do_action('init') #4 /home/rootibyy/public_html/wp-config.php(91): require_once('/home/rootibyy/...') #5 /home/rootibyy/public_html/wp-load.php(37): require_once('/home/rootibyy/...') #6 /home/rootibyy/public_html/wp-login.php(12): require('/home/rootibyy/...') #7 {main} thrown

-------

I noticed another e-mail yesterday telling me about another customer site with the same error. 
(I am glad that both these sites are sites not often used. This means I will need to quickly check my other customer sites.)

### Additional information

EDIT:
WordPress version: 5.4.4
Theme: eStar
Various plugins.

Upon updating to WordPress 5.6, and deactivating and reactivating the Gutenberg plugin the fatal Gutenberg error also goes away.

**Comment by annezazu** [comment]
Of note, found a support forum with the same reported issue: https://wordpress.org/support/topic/erro-fatal-gutenberg/

**Comment by noisysocks** [comment]
I installed WordPress 5.5.3 and Gutenberg 9.7 on a local environment and did not see this error. I also checked with WordPress 5.5.0.

Maybe a plugin conflict?

**Comment by tellthemachines** [comment]
`Call to undefined function register_block_type_from_metadata()` points to the WP version being older than 5.5.x, because that function was [added to Core](https://github.com/WordPress/wordpress-develop/commit/5f6ab44340e7ecd4e99bbf5841e2f0689c4f8d1d) in 5.5. The fallback was removed from Gutenberg in #27807, which went into the 9.7 plugin version so that would make sense. @paaljoachim could you double-check that the version is indeed 5.5.x? I can't reproduce this issue with 5.5.3 and 9.7 either.

**Comment by ridiculoid** [comment]
I just experienced the same error updating to Gutenberg 9.7 while on WP 5.4.4. The plugin page says WP 5.3 or higher is required, but based on the previous comment this is incorrect: https://wordpress.org/plugins/gutenberg/.

**Comment by paaljoachim** [comment]
I went ahead and updated the site. I could have made a mistake thinking/assuming it was running 5.5.x as it could have been an earlier version.

**Comment by youknowriad** [comment]
I'm going to close this issue as it's an explicit change that Gutenberg 9.7 doesn't support WP versions priori to 5.5. Thanks.

**Comment by paaljoachim** [comment]
Hey @youknowriad Riad.

@ridiculoid has a very good point.
"I just experienced the same error updating to Gutenberg 9.7 while on WP 5.4.4. The plugin page says WP 5.3 or higher is required, but based on the previous comment this is incorrect: https://wordpress.org/plugins/gutenberg/. "

I will reopen this issue and mention that we need to write that to use the newest version of Gutenberg one needs to use minimum 5.5 version of WordPress. Or else a fatal error will happen.

**Comment by swissspidy** [comment]
Duplicate of #2778

there is some logic in place to display a better error message, but it doesn‘t work correctly

**Comment by tellthemachines** [comment]
@swissspidy is that the right issue? 

@paaljoachim the change to the readme file that updates the plugin page with the correct info has already been made, and it'll be updated with the next release (9.8). We should be good to close this issue now.

**Comment by paaljoachim** [comment]
That sounds great!
Thanks for the heads up Isabel!

**Comment by swissspidy** [comment]
@tellthemachines argh, typo. #27998 is the correct ticket

**Comment by gziolo** [comment]
In the plugin repository https://wordpress.org/plugins/gutenberg/, it says WordPress 5.3 and up are supported.

<img width="478" alt="Screen Shot 2021-01-13 at 07 47 32" src="https://user-images.githubusercontent.com/699132/104416170-9daea300-5573-11eb-98d1-893bd8dc2204.png">

It was changed in the repository, but it won't get fixed until the next plugin release scheduled for next week.
