### ISSUE TITLE
Custom Roles with ONLY Custom Post Type Capabilities Hangs Editor

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress/gutenberg#28071]
**Describe the bug**
When defining a custom post type and defining a custom user role with capabilities for that post type, Gutenberg editor hangs...

I am on WordPress 5.6. When I add the `'edit_posts'` capability, the Gutenberg editor works fine. But this is not ideal since I only want the custom role to access this specific post type.

This worked fine on WordPress 5.5.3.

Here is the code I used to create the conditional. 

```
add_action( 'init', 'yks_register_kittens' );
function yks_register_kittens() {

	$names = array(
		'name'          => 'Kittens',
		'singular_name' => 'Kitten',
	);

	$args = array(
		'labels'              => $names,
		'description'         => 'Add Kittens for Adoption',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'menu_icon'           => 'dashicons-pets',
		'capability_type'     => 'kitten',
		'map_meta_cap'        => true,
		'query_var'           => true,
		'has_archive'         => true,
		'supports'            => array( 'title', 'editor' ),
		'show_in_rest'        => true,
	);

	register_post_type( 'yks-test-kittens', $args );
}

add_action( 'init', 'yks_add_kitten_manager_role' );
function yks_add_kitten_manager_role() {
	add_role(
		'kitten_manager',
		'Kitten Manager',
		array(
			'read'                 => true,
			'edit_kitten'          => true,
			'read_kitten'          => true,
			'delete_kitten'        => true,
			'edit_kittens'         => true,
			'edit_others_kittens'  => true,
			'publish_kittens'      => true,
			'read_private_kittens' => true,
			'create_kittens'       => true,
		)
	);
}
```
**To reproduce**
1. Add above code to create a custom post type and custom user role
2. Create new user with custom user role. 
3. Login as new user with custom user role.
4. Create a new post for the custom post type.

**Expected behavior**
Gutenberg editor is functional. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20868511/104102831-d2b5af80-526c-11eb-8586-b69c59c1d33c.png)

https://user-images.githubusercontent.com/20868511/104102800-9da95d00-526c-11eb-93ec-8254e6c64de2.mov

**Editor version (please complete the following information):**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **default**
- If the Gutenberg plugin is installed, which version is it? **N/A**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting and also for including the screenshots and detailed code to reproduce this. This has been reported at #27854 and I'll reply more to your comment there.
