### ISSUE TITLE
The navigation editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#28076]
**Describe the bug**
When enabling and opening the (experimental) Gutenberg Navigation editor, 
it doesn't load with an error popup being shown: `The navigation editor has encountered an unexpected error.`
'Attempting recovery' using the provided button doesn't change anything.
The JavaScript error console logs an error that could be the underlying cause:
````
react_devtools_backend.js:2430 TypeError: Cannot read property 'icon' of null
    at e (index.js?ver=97fffcbb2ca23799ffea84ef0015b694:58)
    at we (react-dom.min.de439aae.js:84)
    at nh (react-dom.min.de439aae.js:96)
    at zj (react-dom.min.de439aae.js:230)
    at Th (react-dom.min.de439aae.js:152)
    at tj (react-dom.min.de439aae.js:152)
    at Te (react-dom.min.de439aae.js:146)
    at react-dom.min.de439aae.js:61
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)
````

**To reproduce**
1. Install and enable latests Gutenberg plugin; go to the Gutenberg experiments page (Admin area; item "Gutenberg" in sidebar; sub-item "Experiments"), check "Navigation view" and save the settings.
2. Go to the Gutenberg Navigation view admin page (Admin area; "Gutenberg" in sidebar; sub-item "Navigation (Beta)").
The navigation view seems to initialize, but then it doesn't load and an error popup is displayed: `The navigation editor has encountered an unexpected error.`.
(3.) Select the `Attempt recovery` button, notice that nothing changes.

**Expected behavior**
The Gutenberg Navigation view should load and be usable.

**Editor version (please complete the following information):**
- WordPress `5.6`. 
- Gutenberg plugin `9.7.0`.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome (`87.0.4280.141 (official build) (64-Bit)`)

**Comment by noisysocks** [comment]
Confirmed.
