### ISSUE TITLE
Verse block: Missing typography controls

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28099]
**We are adding typography and color controls to the text blocks that still do not have these features.**

This issue is focused on the Verse block that still needs typography controls.

![Screen Shot 2021-01-11 at 13 51 35](https://user-images.githubusercontent.com/5323259/104184699-26163200-5414-11eb-9151-dadb11f12ee7.png)

Associated issue:
**Consider adding color and text size customizations to all text-based blocks.**
#8171

**Comment by juanfra** [comment]
Hi @paaljoachim,

I've been checking this one and apparently it was fixed here: https://github.com/WordPress/gutenberg/pull/27735

Do you feel we should close this one?

Best,
Juan.

**Comment by paaljoachim** [comment]
Hey @juanfra Juan

Thank you for discovering this!

![Screen Shot 2021-01-20 at 16 18 08](https://user-images.githubusercontent.com/5323259/105195679-282a7000-5b3b-11eb-8634-bcc554ae92b5.png)

We can now close this issue!
