### ISSUE TITLE
Preformatted block: Missing typography controls

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28097]
**We are adding typography and color controls to the text blocks that still do not have these features.**

This issue is focused on the Preformatted block that still needs typography controls.

![Screen Shot 2021-01-11 at 13 39 34](https://user-images.githubusercontent.com/5323259/104183666-9a4fd600-5412-11eb-990d-367b6cf059ec.png)

Associated issue: 
**Consider adding color and text size customizations to all text-based blocks.**
https://github.com/WordPress/gutenberg/issues/8171

**Comment by donnapep** [comment]
@paaljoachim Looks like font size is [already supported](https://github.com/WordPress/gutenberg/pull/27584). Presumably we don't want to add font family. Perhaps this can be closed?

**Comment by paaljoachim** [comment]
Ahhh yes. Thank you Donna @donnapep !
I will close the issue.
