### ISSUE TITLE
Site Title Block: Add text-transform with Letter case settings

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28106]
It would be useful to extend Letter case controls introduced in #26060 to the Site Title Block. See also this discussion about TT1 Blocks. https://github.com/WordPress/theme-experiments/issues/163

**Comment by paaljoachim** [comment]
Hi Ian

My initial thought on this is to start with the default casing: "Site Title"
Then text letter case can be changed to upper: "SITE TITLE" or lower "site title"

I was going to make this all fancy with a mockup in Figma, but I have yet to find the Letter case controls that will be used..:)

**Comment by paaljoachim** [comment]
Btw here is a PR that uses the new typography options.
https://github.com/WordPress/gutenberg/pull/29623

**Comment by carolinan** [comment]
This was solved by https://github.com/WordPress/gutenberg/pull/29622.
