### ISSUE TITLE
Problem with incompatible npm packages and current versioning

### ISSUE THREAD

**Issue by avillegasn** [WordPress/gutenberg#28104]
**Describe the bug**
I am using the npm packages `@wordpress/block-library` and `@wordpress/blocks` to create blocks programmatically and serialize them so that the output string can be loaded into the post content of a post in WordPress (as part of a content migration process running on Node.js). I was using strict versions `"@wordpress/block-library": "2.26.6"`and `"@wordpress/blocks": "6.25.0"` of these two packages, which are the ones producing compatible outputs with WordPress 5.6 release.

However, recently `@wordpress` packages were updated in npm to new minor versions. Since I still want to be compatible with WordPress 5.6 and the included block editor version there, I didn't update the package versions I use. Unfortunately, the serialization of blocks is failing after the update of `@wordpress`packages.

**To reproduce**
1. Create the file `index.js` with the following content:

```js
// Setup environment to simulate a browser.
require( 'browser-env' )();
window.matchMedia = window.matchMedia || function() {
	return {
		matches : false,
		addListener : function() {},
		removeListener: function() {}
	};
};

const { registerCoreBlocks } = require( '@wordpress/block-library' );
const { serialize } = require( '@wordpress/blocks' );

registerCoreBlocks();

const block = {
	name: "core/paragraph",
	validationIssues:[],
	attributes: {
		content: "Lorem ipsum dolor sit amet.",
		dropCap: false
	},
	innerBlocks: [],
	isValid: true
};

console.log( serialize( block ) );
```

2. Create the file `package.json` with the following content:

```js
{
	"name": "test",
	"version": "1.0.0",
	"description": "",
	"author": "",
	"license": "ISC",
	"main": "index.js",
	"dependencies": {
		"@wordpress/block-library": "2.26.6",
		"@wordpress/blocks": "6.25.0",
		"browser-env": "3.3.0"
	}
}
```

3. Execute `npm install && node index.js`
4. The output is: `<!-- wp:paragraph /-->`

**Expected behavior**
The proper output should be as follows:
```html
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet.</p>
<!-- /wp:paragraph -->
```

After further investigation, I found that inside `node-modules/@wordpress/block-library/package.json` the  `@wordpress/*` dependencies are defined using semantic versioning indicating that [minor releases are also supported](https://docs.npmjs.com/about-semantic-versioning), as in `"@wordpress/block-editor": "^5.1.5"`. However, executing the previous steps installs version 5.2.1 of `@wordpress/block-editor` which is the last one released, and the one that makes my tiny example fail.

I was able to **fix the issue by adding `"@wordpress/block-editor": "5.2.0"` as a dependency in my `package.json` file**, forcing npm to install that version instead of the newest one (5.2.1 at the moment of writing this issue). I was lucky to find out that the problem was caused by that dependency, but still, I think that something should change when defining the versions required as dependencies in `@wordpress/*` packages. The version 5.2.1 still matches `"^5.1.5"`, but execution fails. Maybe version definition should be fixed (as in `"@wordpress/block-editor": "5.1.5"`) instead of allowing compatibility with new releases. Or maybe new releases should be compatible with previous minor releases (which is not the case, as depicted in the example steps). Or packages should define dependencies compatible with only patch releases (as in `"@wordpress/block-editor": "~5.1.5"`).

Also, I found it very difficult to know which version of `@wordpress/*` packages were added inside each new WordPress release. It ended being a trial/error process until I found the combination of latest package versions that worked and produced serialized content compatible with WP 5.6. Fortunately, I only use two packages, but that could have been a nightmare in case I used more or there were more incompatibilities. Maybe there is some documentation location that I missed, but more help/clarifications here for future releases should be really appreciated.

I know my use case is a little bit out of your scope, but I believed it was worth to mention the versioning thing just in case other developers are also doing weird things like me and are facing the same issue :-)

Thanks for your support and guidance on this.

**Comment by gziolo** [comment]
I don't know what your use case is, but you can check all the version for the given WordPress release using `wordpress-develop` repository and git tags, example for WordPress 5.6.0:

https://github.com/WordPress/wordpress-develop/blob/96a6969aab5f0b9362cbc984af230bdfc93022e8/package.json#L82-L129

I'm closing this issue as the recommended approach is to use `@wordpress/scripts` and the `build`/`start` command that reference all WordPress packages as `wp.*` globals. This way your code runs with whatever WordPress exposes.

There is also a related issue where hardcoded versions for packages are proposed: https://github.com/WordPress/gutenberg/issues/16623. That could also help when someone would like to check the versions .

**Comment by davilera** [comment]
Hi, @gziolo.

I'm one of @avillegasn's colleagues. Thanks for replying.

> I don't know what your use case is (...). [T]he recommended approach is to use `@wordpress/scripts` and the `build/start` command that reference all WordPress packages as `wp.*` globals. This way your code runs with whatever WordPress exposes.

Our code doesn't run on a WordPress installation - instead, we implemented a service that runs on AWS and relies on `@wordpress` packages.

Unfortunately, I feel like what you're proposing is a workaround and not an actual solution. I feel like it's important to [keep semantic versioning into consideration](https://docs.npmjs.com/about-semantic-versioning) when publishing `@wordpress` packages on NPM, as this would prevent the issue originally reported. That is, if one package (e.g. `@wordpress/block-library`) has `@wordpress/block-editor` as a dependency, use a new major release when there are changes that break backward compatibility. If we fail to do this, we'd be publishing potentially-broken packages.

Now, I don't know if this issue in particular is the right place to have this conversation... but, as @avillegasn said:

> I believed it was worth to mention the versioning thing

**Comment by gziolo** [comment]
> I feel like it's important to keep semantic versioning into consideration when publishing @wordpress packages on NPM, as this would prevent the issue originally reported. That is, if one package (e.g. @wordpress/block-library) has @wordpress/block-editor as a dependency, use a new major release when there are changes that break backward compatibility.

Thank you for your clarification. I was totally unaware of that. In theory, we commit to keeping semantic versioning. We do it pretty well for development tools, but for the client-side code, it looks like we failed several times in the past. There is a process that tries to guess the version bump based on the entries in the CHANGELOG.md file for the package. However, when the person who authors PR doesn't add an entry to the changelog, then the tool does `patch` version update ... I guess this is what happened in this case. See also:

https://github.com/WordPress/gutenberg/tree/master/packages#maintaining-changelogs

**Comment by davilera** [comment]
That's great news! As long as we (try to) keep semantic versioning, everything should work as expected. I guess we simply had "bad luck" in this particular instance.
