### ISSUE TITLE
Verse Block: Broken line wrapping

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#28108]
**Describe the bug**
#27734 has introduced a bug where the Verse block renders lines incorrectly in the frontend of the page. Disabling the `nowrap` rule for the block fixes the issue.

**To reproduce**
1. Add a Verse block
2. Write some text with random indentation, like this:
   ```
   This
     should
       be 
         indented.
   ```
3. Preview/publish the page.
4. See that the text is just a single line.

**Expected behavior**
The text arrangement should be respected in the frontend.

**Screenshots**
| Expected | Got instead |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/841763/104212034-0f340780-5435-11eb-88d5-1e81e3025fa3.png) | ![](https://user-images.githubusercontent.com/841763/104211918-f0357580-5434-11eb-83a6-b733a50a71e3.png) |

**Editor version:** v9.6.2

**Comment by ItsJonQ** [comment]
Thanks for the heads up! I have a fix coming up!
