### ISSUE TITLE
Browse All block panel closes when clicking on vertical scroll bar 

### ISSUE THREAD

**Issue by SJNBham** [WordPress/gutenberg#28113]
**Describe the bug**
![scrollbar-closes](https://user-images.githubusercontent.com/11393597/104228330-89499980-53ff-11eb-89ba-d98c73a78803.gif)

**To reproduce**
1. Click the Add Block button in the description field of a page.
2. Choose [Browse All]
3. Try to click on the vertical scroll bar to scroll through the available blocks.
4. The Block panel closes.

**Expected behavior**
The Block panel should remain open and the vertical scroll bar should allow scrolling through the blocks.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg plugin version: 9.7.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge (Chromium)
 - Version: 87.0.664.75 (Official build) (64-bit)

**Comment by talldan** [comment]
Thanks for reporting. I wasn't able to reproduce this:
![block-menu-edge](https://user-images.githubusercontent.com/677833/104287731-d312ac80-54f1-11eb-9e45-32c4522d1ac6.gif)

Tested in BrowserStack, Edge 87, Windows 10.

Any plugins active that might cause this?

**Comment by SJNBham** [comment]
We tried it on a fresh site without plugins and the TwentyTwenty theme active. When we disable the Gutenberg plugin, it works as expected. When we activate the Gutenberg plugin, the scrollbar closes the blocks catalog panel. We also tried an inPrivate window and clearing the browser cache. We tested it in FireFox with the same results. Here is the console output from FireFox:

![Uploading console-output.png…]()

Not sure if that reference in the console output to scrolling effects could be related:

https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by carinapilar** [comment]
I also got a report for this and was able to replicate it, with only Gutenberg active and using TwentyTwenty too. As @SJNBham shared above, it only happens when Gutenberg plugin is active, it works as expected once deactivated.

**Comment by sirreal** [comment]
I've just confirmed this with the lastest Gutenberg release 9.7.1.

**Comment by kriskarkoski** [comment]
I noticed a similar issue yesterday I was planning to report but I suspect is the same issue. If you click anywhere in the panel that's not a clickable element ex. between patterns the panel closes.

**Comment by sirreal** [comment]
I believe this is fixed by https://github.com/WordPress/gutenberg/pull/27946, which was just included in the 9.7.2 patch release.

**Comment by SJNBham** [comment]
Confirming this appears to be fixed in 9.7.2. Thanks!
