### ISSUE TITLE
In-between Inserter is Unreliable

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28123]
![Inbetween Inserter](https://user-images.githubusercontent.com/191598/104264843-63051780-545a-11eb-8dde-06bd19049d30.gif)

I can get the in-between inserter to appear between _widget areas_, which seems like a mistake.

Also, unless there are multiple widgets in a sidebar area, I'm unable to get the in-between inserter to appear.

**Comment by draganescu** [comment]
That inserter should not be visible as we cannot insert a new widget area, these are defined by themes.

![widgets-weird-inserter](https://user-images.githubusercontent.com/107534/104590362-e64d8580-5673-11eb-95a8-1bf19c925c12.png)

**Comment by talldan** [comment]
Yeah, I think the template should be locked down for widget areas, so the bug might be that the indicator is displaying in locked template areas.

**Comment by noisysocks** [comment]
@ellatrix: Are you working on this?

**Comment by talldan** [comment]
#32576 should fix the issue in locked widget areas, and I saw there's #31896 that covers everything else.
