### ISSUE TITLE
Make unique block id (not html id)

### ISSUE THREAD

**Issue by dikium** [WordPress/gutenberg#28137]
### What is this about?
Hi! I'm creating plugin which adds comment section to each block of article. So i need a unique id of an each block, stored in a database. How can i achieve this? Maybe i can somehow add extra attribute {"blockId": 1} to each block, but how can i do this, so it would not be deleted by gutenberg? Thanks!

**Comment by aristath** [comment]
Do you want the comments on the editor, or on the frontend?
If on the frontend then a block-ID is not necessary and it could be done via PHP filters on `render_block`.
I would advise against adding a new custom `blockId` prop to existing blocks as that would break all blocks in case your plugin gets disabled.

**Comment by dikium** [comment]
Yes, i want add comments to frontend. But i need identificate blocks because articles can be edited and blocks can be rearranged, so i need comments to conform own blocks.
And is this a problem if blocks will have additional non active attribute? If it Will break editor i can remove it when i disable plugin. And may be i can somehow add metadata to Block?

**Comment by tellthemachines** [comment]
@dikium you can add attributes to blocks with the [registerBlockType ](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-registerblocktype) filter..

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
