### ISSUE TITLE
Removing the Paragraph Block Text Color Formatting Option

### ISSUE THREAD

**Issue by danielpwaldschmidt** [WordPress/gutenberg#28145]
It looks like in WordPress 5.6, Text Color has been added as a formatting control to the Toolbar of the Paragraph block. For example, when editing a paragraph block, it now includes the ability to choose the text color.

Is there a way to disable the Text Color formatting control globally for the Toolbar, or at least for the Paragraph block?

**Comment by talldan** [comment]
@danielpwaldschmidt This was actually introduced in WordPress 5.4. It's registered as a format and `wp.richText.unregisterFormatType( 'core/text-color' );` will remove it.

**Comment by danielpwaldschmidt** [comment]
That's interesting. We're running a bunch of sites on 5.5.3 and the Text Color formatting option isn't available on those sites. In our 5.6 testing environment, however, it is.

Anyway, thanks for the code to remove it.
