### ISSUE TITLE
Editor sidebar clipped when block content is too wide

### ISSUE THREAD

**Issue by adekbadek** [WordPress/gutenberg#28140]
**Describe the bug**

With wide enough block, the sidebar is clipped.

**To reproduce**

Add a Heading block, input a long space-less string. Observe the block content pushes the sidebar to the side, clipping it. This happens on screen widths between 780px and 1070px.

**Expected behavior**

The sidebar should not be clipped.

**Screenshots**

https://d.pr/i/thsAt5

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Default Gutenberg editor

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 87

**Comment by talldan** [comment]
Thanks for reporting. I'm sure this issue has been reported before, I remember commenting on it, but I couldn't find another ticket. The cause of this seems to be the same as https://github.com/WordPress/gutenberg/issues/27622.

**Comment by adekbadek** [comment]
Yes, this seems similar to #27622. In our testing we've found that connecting Jetpack solves the issue 🤷
