### ISSUE TITLE
Inspector: Show fallback text when no block description assigned

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2814]
Related: #2023, #1343

If no description or inspector is provided by a block, we should show some text there, such as "This block has no description."

See #1343 for a previous related attempt at this behavior, which surfaced the challenge of detecting whether a [slot](https://github.com/camwest/react-slot-fill) has any fills assigned.

**Comment by youknowriad** [comment]
This should be closed by #4159  since it also shows the block Icon and the block title in the inspector for all blocks removing the need to a mandatory description.
