### ISSUE TITLE
Recent regression - Site Editor - Spinner component not visible / missing CSS.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#28153]
**Describe the bug**
The loading spinner does not show up as expected in the site editor.  It seems to be missing CSS.

Currently - the spinner component is not visible and seems to be missing styles:

![Screen Shot 2021-01-12 at 6 19 19 PM](https://user-images.githubusercontent.com/28742426/104386886-ff372900-5503-11eb-8a16-ce2d86e302df.png)

As compared to previously when it did show up, these styles were present:

![Screen Shot 2021-01-12 at 6 20 49 PM](https://user-images.githubusercontent.com/28742426/104386911-08c09100-5504-11eb-8fa2-1964fca08990.png)

I noticed this as a recent regression while testing related to the bug where template parts would not resolve when themes are installed in subdirectories - https://github.com/WordPress/gutenberg/pull/28088.  Drafted Sunday evening, this PR was showing the spinner.  After rebasing `master` this afternoon, the spinners seem to have disappeared as their CSS is no longer present - so it seems a recent change has caused this.

The specific spinner I have noted comes from https://github.com/WordPress/gutenberg/blob/9c9617d20d4ebd1d1e7edf3f6019a58a17bdc90d/packages/block-library/src/template-part/edit/index.js#L127 - but adding other spinner components to blocks in the block-library seems to have the same issue.

**Comment by Addison-Stavlo** [comment]
I wonder if it may be related to the new Iframe? #25775

**Comment by ellatrix** [comment]
Sorry for the late reply. What stylesheet should be loaded that isn't loaded right now?

**Comment by ellatrix** [comment]
Sorry for the late reply. What stylesheet should be loaded that isn't loaded right now?

**Comment by Addison-Stavlo** [comment]
> Sorry for the late reply. 

No worries, thanks for taking a look!

> What stylesheet should be loaded that isn't loaded right now?

After poking around briefly, it looks like it is the styles defined in JS that correspond to what were missing in the screenshots above:
https://github.com/WordPress/gutenberg/blob/c6b43a03b640a56156304c9762004353b295d9d5/packages/components/src/spinner/styles/spinner-styles.js#L27-L34

**Comment by ellatrix** [comment]
@ItsJonQ Did you know more about these generated styles and how to insert them into a different document?

**Comment by ItsJonQ** [comment]
Haiii!!! Sorry for the late reply @ellatrix .
Yes! I may be able to help with this.

For these styles, what needs to happen is they need to be rendered in a `Provider`.
This provider tells them which `document` to insert their styles into.

Previously, I created a library to help with this exact problem:
https://github.com/ItsJonQ/styled-providers#frameprovider

We can use the same technique for the iFrame editor as well
