### ISSUE TITLE
Some theme templates missing from site editor

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#28154]
**Describe the bug**
Since the auto-draft templates were removed, I notice that some templates are missing from the site editor. I am testing using Ambitious theme and notice that the `archive` and `404` templates are missing from the list, while other ones like `front-page` and `index` are successfully listed.

**To reproduce**
1. Install a FSE-theme
2. Go to site editor
3. See some templates missing

**Expected behavior**
All theme templates should be there.

**Editor version (please complete the following information):**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **plugin**
- If the Gutenberg plugin is installed, which version is it? **13 Jan 2021 commit on master branch**
- Theme: Ambitious

**Comment by carlomanf** [comment]
When I cloned the theme into a new folder, the templates appeared again. This might be a similar issue to #28054.

**Comment by skorasaurus** [comment]
Hi, 

I am not able to reproduce this with version 12.2 of Gutenberg; all templates of ambitious load in the site editor; I am assuming this and hoping this was fixed a while back with the site editor. 

Please reopen if you're still experiencing this.
