### ISSUE TITLE
Database migration didn't work properly

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#28155]
**Describe the bug**
The database migration introduced in #27910 did not erase all of the data it was designed to erase.

* Auto-drafts are correctly erased but their term relationships didn't get erased. In other words, you end up with "orphan" entries in the term relationships table.

* The `_wp_file_based` term didn't get erased.

* The `gutenberg_last_synchronize_theme_template_checks` option didn't get erased.

* The `gutenberg_last_synchronize_theme_template-part_checks` option didn't get erased.

**Expected behavior**
Either the migration needs to be complete, or don't bother including a migration at all.

**Editor version (please complete the following information):**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **plugin**
- If the Gutenberg plugin is installed, which version is it? **13 Jan 2021 commit on master branch**

**Comment by talldan** [comment]
Pinging @youknowriad as the author of #27910 for feedback.

**Comment by youknowriad** [comment]
I assumed the "delete_term" does remove the relationships but it seems that it doesn't. and I forgot about the options.

**Comment by carlomanf** [comment]
> I assumed the "delete_term" does remove the relationships but it seems that it doesn't.

I think it is meant to. I can't work out why it doesn't here, but I'd guess it's the auto-draft status causing trouble again.

**Comment by youknowriad** [comment]
Do you have an idea on how we could overcome that?

**Comment by carlomanf** [comment]
If you were desperate you could always write out the queries through `$wpdb`, but identifying the cause of the migration failure might uncover a better solution.

**Comment by ockham** [comment]
`wp_delete_object_term_relationships` looks promising :thinking: I'll see if that's supposed to be automatically run by `wp_delete_term` (and under what circumstances), or if it always needs to be manually run.

**Comment by ockham** [comment]
Hmm, while `wp_delete_term` doesn't seem to invoke `wp_delete_object_term_relationships`, it does look like it should remove term relationships no less: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/taxonomy.php?rev=49947#L1935

**Comment by carlomanf** [comment]
> Hmm, while `wp_delete_term` doesn't seem to invoke `wp_delete_object_term_relationships`, it does look like it should remove term relationships no less: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/taxonomy.php?rev=49947#L1935

It's more complicated than that. The call to `wp_delete_term` actually had no effect at all, so it didn't even delete the term, let alone the relationships. `wp_delete_post` was also meant to delete the relationships for the given post, and didn't.

It might be wise to write some unit tests for this, if it's possible to do so.

**Comment by ockham** [comment]
I might have a promising lead :grimacing: 

Compare https://github.com/WordPress/gutenberg/pull/27910/files#diff-d8826d0f767301135f001ac1a09905bf32198b6604bf6a3fdf15799ea4c7ea48L119 to https://github.com/WordPress/gutenberg/pull/27910/files#diff-25417a675fde0cd7653118033809d3692e62da2788c4ac63d2f8d42eca4a29a8R52

We're setting `wp_theme`, but attempting to delete `wp-theme`.

Maybe it's as simple as that :crossed_fingers:

**Comment by ockham** [comment]
The other problem seems to be that `get_term_by` doesn't seem to find any `wp_theme` terms. The reason for this might be that we're attempting to do so from the `_gutenberg_migrate_database` method, which is hooked into [`plugins_loaded`](https://developer.wordpress.org/reference/hooks/plugins_loaded/). However, the `wp_theme` taxonomy is registered in `gutenberg_register_wp_theme_taxonomy`, which is hooked into `init`. And `init` comes after `plugins_loaded`.
