### ISSUE TITLE
New templates endpoint not working

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#28152]
**Describe the bug**
The new REST API endpoints added in #27910 are returning the following for me, when logged in as a super admin on multisite.

```
{"code":"rest_cannot_manage_templates","message":"Sorry, you are not allowed to access the templates on this site.","data":{"status":401}}
```

**To reproduce**
1. Log in as an admin
2. Observe that site editor etc are available because they pass the capability check
3. Go to `/wp-json/wp/v2/templates/` or `/wp-json/wp/v2/template-parts/`

**Expected behavior**
The error message should only load if the user lacks the capability. For admins, there is no reason for this error to be denying them the data.

**Editor version (please complete the following information):**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **plugin**
- If the Gutenberg plugin is installed, which version is it? **13 Jan 2021 commit on master branch**

**Comment by kasperaamodt** [comment]
Are there any updates on this problem? I'm running the latest version of everything, and I'm still getting the error:

```
{
  "code": "rest_cannot_manage_templates",
  "message": "Sorry, you are not allowed to access the templates on this site.",
  "data": {
    "status": 401
  }
}
```

Editor version (please complete the following information):
WordPress version: 5.7.2
Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
If the Gutenberg plugin is installed, which version is it? 10.6.2

**Comment by Bowriverstudio** [comment]
Same here, I am using Postman to access the endpoint.

**Comment by anton-vlasenko** [comment]
A nonce has to be specified in order to use some REST API endpoints.
This [document](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#cookie-authentication) states, that
> For developers making manual Ajax requests, the nonce will need to be passed with each request. The API uses nonces with the action set to wp_rest. These can then be passed to the API via the _wpnonce data parameter (either POST data or in the query for GET requests), or via the X-WP-Nonce header. If no nonce is provided the API will set the current user to 0, turning the request into an unauthenticated request, even if you’re logged into WordPress.

You need to either add a nonce as a request parameter
http://your.wordpress.site/wp-json/wp/v2/templates/?_wpnonce=your_generated_nonce
or add the `X-WP-Nonce` header to the request.
I had no issues with the `wp/v2/templates` endpoint when I used the correct nonce.

**Comment by carlomanf** [comment]
Thanks, I guessed there was some authentication step missing but couldn't find the documentation.
