### ISSUE TITLE
Can't select navigation block if first clicking canvas

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28166]
Steps to reproduce:

1. Insert a navigation block. Vertical or horizontal, doesn't matter.
2. Click "Start Empty". 
3. Click outside the editing canvas, for example to the right of post content, to deselect all blocks.
4. Click the navigation block to select it.

Observe that the navigation block receives `focus` (as indicated by the blue border), but is not _selected_. So neither the block toolbar appears, or the `is-selected` CSS class is present.

Note that if instead of clicking outside the editing canvas, you select a different block, you _can_ select the navigation block. 

I wasn't able to reproduce this issue with any other blocks than Navigation, it doesn't seem like this would be limited to just this block. But it does appear to be related to nesting. 

GIF showing the above:

![Jan-12-2021 13-11-43](https://user-images.githubusercontent.com/1204802/104439012-ecb70100-5590-11eb-8566-89b395449d90.gif)

Chatted yesterday with @gziolo, @ellatrix and @retrofox, and it was suggested that `AsyncModeProvider` could theoretically be related to the cause of the issue. It's the cause of this adjacent Safari-only bug: #19454.

**Comment by ZebulanStanphill** [comment]
I recently ran into a very similar (if not the same) issue after rebasing #21234: my Table of Contents block PR. Notably, both blocks use `<nav>`, `<ul>`, and `<li>` elements, so maybe that's related somehow?

**Comment by jasmussen** [comment]
I had the same thought, and in a shotgun debugging session, I tried replacing all those with divs. Alas, no change.

**Comment by ntsekouras** [comment]
@jasmussen I couldn't reproduce this. Is this still happening?

**Comment by jasmussen** [comment]
Hallelujah, no, it appears fixed!

**Comment by jasmussen** [comment]
Ack, I'm seeing it again. Reopening. Same steps to reproduce.
