### ISSUE TITLE
Gutenburg reusable block detachment options

### ISSUE THREAD

**Issue by blachawk** [WordPress/gutenberg#28178]
With the latest version of WordPress, I plan go into a page and create a block and convert it to a reusable block. When I re-use that block, either on the same page, or another page, is there a hook, an action, or a setting anywhere in my WordPress system that can **allow reusable blocks to be detached from other blocks by default**? Rather than clicking the link every time, to convert to regular block.

**Comment by ntsekouras** [comment]
Hey @blachawk 👋 - What do you mean by `detached from other blocks by default`? Can you provide a bit more information about your use case?
