### ISSUE TITLE
Site Editing: Make notice about switching to template editing "sticky" & dismissible 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#28175]
**Describe the bug**

When switching from post editing to template editing, there's a notice that pops up to explain template editing but it disappears quite rapidly. Because this is such a big switch to be making, it seems smart to make this "stickier" and perhaps consider force people to dismiss it upon first switching over. I imagine this will be annoying if you're doing lots of edits back and forth so perhaps it would be good to make it a bit more intelligent ;). I'll leave this to design to think about the implications of. 

From @priethor who helped test this: "Also, when switching from the Post editor to the Template Editor, the “Editing template” notification at the bottom was easy to miss on bigger screens."

**To reproduce**
1. Install Gutenberg 9.6+ and a FSE ready theme.
2. Go to Posts > Add New
3. Make some changes to the post > Save Draft or Publish. 
4. Use the option to edit the template to switch into template editing mode in the post settings section.
5. See the notice pop up.

**Expected behavior**

I expect the notice to stick around for longer and/or to be more "in the user's face". 

**Screenshots**

<img width="625" alt="Screen Shot 2021-01-13 at 12 44 19 PM" src="https://user-images.githubusercontent.com/26996883/104501528-16762500-559d-11eb-95fe-9118dacead20.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg
- If the Gutenberg plugin is installed, which version is it? 9.7.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 87.0.4280.141

**Comment by annezazu** [comment]
Noting here too that this might be bandaiding a root issue that, when the root issue is addressed (making post vs template editing clearer), this then becomes irrelevant :)

**Comment by priethor** [comment]
> Noting here too that this might be bandaiding a root issue that, when the root issue is addressed (making post vs template editing clearer), this then becomes irrelevant :)

I totally agree with this point of view, my feedback was based on the fact that the popup is actually the main way for users to understand they have switched to template editing mode, which is otherwise easy to miss. With a clearer distinction between editing modes, the popup discreetness would be absolutely fine, in my opinion.

**Comment by jasmussen** [comment]
I would agree with the commentary here — I think the real solution is a **very clear visual change** from editing the post to editing the entire template. I've been discussing **literal** zooming out, when you enter template mode, with @jameskoster. I believe once that shift is noticable enough, we won't need to change the snackbar component to afford a dismiss button. 

Furthermore, any changes you actually make to the template, you have to confirm again before saving, with the "Apply" button, which lists every change before you publish it.

**Comment by priethor** [comment]
I believe this that we are talking about would be solved in #27849.

**Comment by ridesirat** [comment]
> I believe this that we are talking about would be solved in #27849.

I think so too

**Comment by annezazu** [comment]
Closing this out as the current notice does stick and, if you click on it, you can dismiss it :)
