### ISSUE TITLE
Navigation Screen - delete menu button hard to find

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28184]
## What problem does this address?
This is just my opinion, but having spent some time with the Navigation Screen again after a bit of time away, I found this button a little hard to find and use effectively.

Currently, the user has to select the parent navigation block, open up the block inspector, and then select delete menu.

Explaining why I think this is a hard place to find it:
- My initial expectation would be for Delete Menu to be located in the same area as the Add Menu button at the top of the screen, as they're both related operations: <br/><img width="479" alt="Screenshot 2021-01-14 at 1 23 58 pm" src="https://user-images.githubusercontent.com/677833/104548516-f19cb300-566b-11eb-8494-91d9884a8330.png">
- When the navigation block is selected, it has two main icons, the block's 'More options' and the 'Block Inspector' dropdown. Both of these aren't quite in the same place as they'd usually be in the normal editor, it takes a bit of re-learning to interact with the Block Inspector in this format: <br/><img width="149" alt="Screenshot 2021-01-14 at 1 25 37 pm" src="https://user-images.githubusercontent.com/677833/104548664-3d4f5c80-566c-11eb-849f-362cd56020d8.png">
- Usually when deleting a block, that option appears in the block's more menu, so I've found myself often opening up that menu first expecting it to be there, but instead this menu is fairly empty: <br/><img width="222" alt="Screenshot 2021-01-14 at 1 28 28 pm" src="https://user-images.githubusercontent.com/677833/104548754-6d96fb00-566c-11eb-8b84-9ce26df42250.png">

## What is your proposed solution?
My instinct would be to add the button somewhere on the top bar, but I think moving to the block More options menu could be a second choice.

**Comment by shaunandrews** [comment]
I believe this is resolved now with the new persistent inspector sidebar:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/191598/107554140-8af3b200-6ba3-11eb-8434-3716a81ee127.png">

Along with that #28864 will likely make it more obvious, too.

**Comment by talldan** [comment]
Yep, agreed, thanks for closing it Shaun.
