### ISSUE TITLE
Error when saving widgets

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#28186]
## Description

There's an error when saving widgets from editing a clean state in the new widgets screen. Found when writing tests in #28160.

## Step-by-step reproduction instructions

1. Go to the new widgets screen.
2. Delete **all** widgets, including widgets in the **inactive widgets** section.
3. Save, reload, and confirm that there's no widgets left.
4. Add a new block (e.g. paragraph block) in the first widget area.
5. Toggle to open the second widget area (could be inactive widgets or others).
6. Add another block to the second widget area.
7. Hit "Update", see the error pops up in the snackbar.

## Expected behaviour

There shouldn't be any errors.

## Actual behaviour

There's an error and the widgets are not correctly saved.

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/7753001/104557507-5102bf00-567c-11eb-95b2-d66a824206e6.png)

## WordPress information
- WordPress version: 5.7-alpha-49956
- Gutenberg version: master branch
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested in both Twenty Twenty-One and Twenty Twenty

## Device information
- Device: Desktop
- Operating system: macOS
- Browser: Chrome 87

**Comment by Soean** [comment]
Thanks for reporting this issue, but I think we already have #27173 and #27171 about this problem.

**Comment by kevin940726** [comment]
@Soean I believe they are fixed in #28078. This issue is still happening after merging #28078.

**Comment by draganescu** [comment]
I was able to repro, getting this:

```
{code: "rest_invalid_param", message: "Invalid parameter(s): widgets",…}
code: "rest_invalid_param"
data: {status: 400, params: {widgets: "widgets[0] is not of type object,string."}}
message: "Invalid parameter(s): widgets"
```

from 

`https://gutenberg.wp.vagabond.andreidraganescu.info/wp-json/wp/v2/sidebars/wp_inactive_widgets?_locale=user`

with the request payload being 

```
{"id":"wp_inactive_widgets","widgets":[null]}
```

So it appears that when adding widgets to multiple areas and save them all, sometimes we send the wrong data.

**Comment by paaljoachim** [comment]
I was also able to reproduce using Gutenberg 9.8 RC.

![Screen Shot 2021-01-14 at 11 30 31](https://user-images.githubusercontent.com/5323259/104579176-ed689980-565b-11eb-95b1-92b0a2edbbb3.png)

Error seen: `{"code":"widgets_cannot_access","message":"Sorry, you are not allowed to access widgets on this site.","data":{"status":401}}`
