### ISSUE TITLE
Reusable block doesn't change in normal block

### ISSUE THREAD

**Issue by tinickel** [WordPress/gutenberg#28199]
Hi there,
the button "convert to normal block" doesn't work for me. (To convert a reusable block again.)

Does anyone have a solution for this problem?

WordPress version 5.6
Theme Astra

**Comment by ntsekouras** [comment]
Hey @tinickel 👋  - What doesn't work? I could convert it to regular blocks. Did you expect for it to be deleted? If that's the case you have to go to `manage reusable blocks` through the more options in block toolbar.

**Comment by tinickel** [comment]
It was a bug of the Plugin Ultimate Addon for Gutenberg. I contacted the developers and got a solution. Thank you for your help.
