### ISSUE TITLE
User-generated templates should be deletable

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#28195]
Templates supplied by the theme, that have been customised can be [reverted](https://github.com/WordPress/gutenberg/pull/28141) back to their original state.

Templates that have been user generated via the [+] button in the site editing W panel should be deletable.

This flow needs some design exploration to determine where folks should be sent post deletion.

**Comment by jameskoster** [comment]
First pass at this:

<img width="1878" alt="Screenshot 2021-01-14 at 12 08 34" src="https://user-images.githubusercontent.com/846565/104589075-4129b180-5661-11eb-8202-0534508547f7.png">

The language in the modal can probably use some optimisation :)

As for where users get sent after deleting the current template, in the future I think they should be sent to the [mosaic view](https://github.com/WordPress/gutenberg/issues/20477) – this would be consistent with deleting a post which sends you back to the post list.

Until we have the mosaic view implemented, returning them to the last-edited template seems most sensible to me.

**Comment by youknowriad** [comment]
I'm about to make things more complex :) 

What If I actually want to delete a theme's template? Say theme provides "single.html" but I just want to rely on its ancestor "index.html" ? Maybe not a common-use case and potentially something that can come later though.

**Comment by jameskoster** [comment]
> I'm about to make things more complex :)

Thanks :D 

It probably shouldn't be possible to literally delete a theme .html template in the UI, so this might be better framed more as a "Disable" than "Delete". I can certainly see a use case for that though... you might want to temporarily disable a template while you work on it, or as you said, permanently exclude one specific theme template.

Probably worth opening a new issue for this, since the affordance could theoretically be applied to both theme-supplied and user-generated templates.

**Comment by jameskoster** [comment]
Closing this as it's essentially a duplicate of https://github.com/WordPress/gutenberg/issues/31076
