### ISSUE TITLE
Z-index CSS top widget area toolbar bug.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28193]
## Description

In the widgets screen when no widgets are present the widget toolbar is partly below the top toolbar.

![Widgets-area-partly-below-top-toolbar](https://user-images.githubusercontent.com/5323259/104578606-3835e180-565b-11eb-9c63-19eee8051d86.gif)

## Step-by-step reproduction instructions
Widgets screen.
1. Go to the widgets screen
2. Remove all widgets also inside the Inactive widgets area. Update/Save. Refresh.
3. Click the first widget area. 
4. Notice the CSS index issue in the first widget area. The widget area toolbar is partly hidden by the top toolbar.

## Expected behaviour
Having the widgets area pushed far enough down the page so the widget area toolbar would not be partly below the top toolbar.

## WordPress information
- WordPress version: 5.6
- Gutenberg version:  9.8 RC. 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OSX 10.15.6
- Browser: Chrome

Ps
Somewhat associated issue: https://github.com/WordPress/gutenberg/issues/28186

**Comment by draganescu** [comment]
I'll close this in favor of #26261 as that toolbar should now show up.
