### ISSUE TITLE
Reverting a template should require user confirmation and/or offer an undo action

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#28194]
If a user has made substantial customisations to a template then [reverting](https://github.com/WordPress/gutenberg/pull/28141) it could have significant ramifications for their site. This action should ask the user to confirm that they actually want to revert, or offer an undo option in case they revert by mistake. Perhaps it should have both :)

**Comment by jameskoster** [comment]
Since reverting a template isn't quite as extreme as [deleting](https://github.com/WordPress/gutenberg/issues/28195) one, I think a Snackbar confirmation with undo action will probably be adequate here.

<img width="2008" alt="Screenshot 2021-01-14 at 12 28 38" src="https://user-images.githubusercontent.com/846565/104591112-29076180-5664-11eb-8a96-7361d21a111f.png">

**Comment by david-szabo97** [comment]
@jameskoster Is this safe to close? #28141 added an undo action in the snackbar.

**Comment by jameskoster** [comment]
Yes 🎉
