### ISSUE TITLE
The editor's breadcrumb trail goes beyond the content of the page

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#28192]
## Description
The editor's breadcrumb trail goes beyond the content of the page. It continues to the sidebar. 

This means that it can hide some options in the right sidebar, the breadcrumb trail can hide some of them.

![Capture d’écran 2021-01-14 à 10 33 48](https://user-images.githubusercontent.com/33403964/104572790-69f77a00-5654-11eb-9143-4f65a0116139.png)

The same happens when you open the left sidebar.

![Capture d’écran 2021-01-14 à 10 36 05](https://user-images.githubusercontent.com/33403964/104572810-6ebc2e00-5654-11eb-9a7b-165c4dd015a8.png)

## Step-by-step reproduction instructions
1. Open a new post or page
2. Open the right options sidebar and the left blocks sidebar
3. You should notice that the breadcrumb hide some of their elements.

## Expected behaviour
The breadcrumb should be contained inside the post content body.

The `div` with the class `interface-interface-skeleton__footer` should be in the one with the class `interface-interface-skeleton__content` 
https://github.com/WordPress/gutenberg/blob/master/packages/interface/src/components/interface-skeleton/index.js#L139

Also, to avoid the breadcrumb to be above metaboxes added by plugins, it should be moved upper in https://github.com/WordPress/gutenberg/blob/d9646be47c1850697f9398be254ba956fded7b8f/packages/edit-post/src/components/layout/index.js#L270.

## WordPress information
- WordPress version: 5.7-alpha-49957
- Gutenberg version: 9.8.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: MacBook pro
- Operating system: macOs Big Sur 11.0
- Browser: Firefox Developer Edition v77

**Comment by youknowriad** [comment]
I believe this is expected. At least I remember that when we initially added the footer we considered both options before doing that.

**Comment by jasmussen** [comment]
Thank you for the ticket and work!

As Riad suggests, though, this is intentional insofar as it is a global interface element that is permanently visible, just like the top toolbar. I would keep it as is. There has been discussions on looking for an alternative to the breadcrumbs entirely, though, as the bottom toolbar is very rarely discovered by people.

**Comment by youknowriad** [comment]
Let's close this for now.
