### ISSUE TITLE
Content in a verse block isn't constrained by the block container

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2821]
## Issue Overview
When you type in a verse block the text overflows the container. If you keep typing, the whole editor scrolls off the left-hand side of the page.

## Steps to Reproduce (for bugs)
1. Add a Verse block
2. Type something long

## Expected Behavior
Content should be constrained to the actual block

_Firefox 55.0.3 (64-bit)
macOS Sierra 10.12.1
Gutenberg 1.2.1_

![screenshot_498](https://user-images.githubusercontent.com/2078245/30961794-d42ab862-a48a-11e7-81d0-850c34eb9f15.png)

**Comment by iseulde** [comment]
Yeah, I guess we should make it scrollable.
