### ISSUE TITLE
RTL/LTR button missing from Paragraph block

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#28221]
## Description

The LTR button has gone missing from paragraph blocks in sites with RTL locales.

This button was added in https://github.com/WordPress/gutenberg/pull/10663
This seems to be a regression from https://github.com/WordPress/gutenberg/pull/27838

The `isRTL` check returns false, causing the LTR button not to render:
https://github.com/WordPress/gutenberg/blob/8b30eda7b12f881eb0befaed7ed44fedf0414207/packages/block-library/src/paragraph/edit.js#L33

The following can also be observed in the JavaScript console, which suggests the issue is related to the locale:

```js
wp.i18n.isRTL()
// false
// isRTL checks this under the hood
wp.i18n._x( 'ltr', 'text direction' )
// "ltr"
```

Yet, the locales I've tested appear to have the correct "ltr" setting, for [`ar`](https://translate.wordpress.org/projects/wp/dev/ar/default/?filters%5Bterm%5D=ltr&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and [`he`](https://translate.wordpress.org/projects/wp/dev/he/default/?filters%5Bterm%5D=ltr&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).

## Step-by-step reproduction instructions
1. Create a site with Gutenberg 9.7 installed
1. Set the site language to an RTL language, e.g. `ar` or `he`.
1. Ensure translations are updated from the site dashboard
1. Open the post editor
1. Add a paragraph block
1. The LTR button is missing

![no-ltr](https://user-images.githubusercontent.com/841763/104707678-02593180-571d-11eb-9331-a3137dd5eada.png)

There should be an LTR button like this (installed Gutenberg 9.6 on the same site):

![ltr with 9 6](https://user-images.githubusercontent.com/841763/104708129-93c8a380-571d-11eb-80f8-2aa3f15ba6c9.png)

## Expected behaviour
LTR button should be present

## Actual behaviour
LTR button is missing

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.7.1 (latest)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by youknowriad** [comment]
`wp.i18n._x( 'ltr', 'text direction' )`

It seems this should be returning "rtl" for these languages but when looking in glotpress, I don't see the string in the Gutenberg plugin https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/ar/default/?filters%5Bterm%5D=ltr&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Could this be a bug with the string extraction. cc @swissspidy

**Comment by swissspidy** [comment]
While files like `block-library/dist/index.js` will have strings like `Object(we.__)("Image caption text")` that can be detected, in `i18n/dist/index.js` it looks like this:

```js
// ...
isRTL:function(){return"rtl"===i("ltr","text direction")}
// ...
```

There's no way string extraction can know that this is a translation call. Maybe you can tweak the webpack config to not mangle function names there or something?

**Comment by youknowriad** [comment]
Interesting, I guess it's because the function is defined in the same module.

**Comment by sirreal** [comment]
We came across an issue like this in Calypso and solved it [by reserving translation functions from mangling.](https://github.com/Automattic/wp-calypso/blob/0a6aa433220ae1b211f82e0c2790bb7a401d04fc/packages/calypso-build/webpack.config.js#L103-L107) It would be a good idea for `@wordpress/scripts` to do the same.

```jsonc
// webpack config
optimization: {
	terserOptions: {
		mangle: { reserved: [ '__', '_n', '_nx', '_x' ] },
	},
}
```

**Comment by sirreal** [comment]
I'll file a PR to reserve the names.

**Comment by sirreal** [comment]
The fix in https://github.com/WordPress/gutenberg/pull/28231 appears to have been insufficient. Although strings are now correctly extracted and translations have been updated and published with the appropriate translations for Gutenberg in `he` and `ar` locales, the `wp-i18n` script never appears to have translations attached in my testing and this issue remains.

**Comment by sirreal** [comment]
These lines may be related:

https://github.com/WordPress/gutenberg/blob/9b323e81b4a133e09b08c4e4975c933b384d45ce/lib/client-assets.php#L87-L97
