### ISSUE TITLE
Finer control is needed with add_theme_support functionality

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2823]
At the moment, to be able to see the _Wide width_ and _Full width_ toolbar controls (such as when you insert an image), you need to `add_theme_support` for `gutenberg` and then specify `'wide-images' => true`.

This is not enough control for theme developers. For starters, it makes no sense in calling this key `wide-images` when it also turns on/off the  _Wide width_ and _Full width_ toolbar controls on Tables as well.

What if theme developers don't want to support both wide and full widths? We shouldn't be forced to support both. We should be able to turn them on/off individually, for both images and tables (and also any other future blocks that you plan to include that would use these controls as well).

Something like the following:
```
add_theme_support( 'gutenberg', array(
   'images-wide' => true,
   'images-full' => true,
   'tables-wide' => true,
   'tables-full' => true,
 ) );
```

**Comment by youknowriad** [comment]
I may be wrong but I sincerely think this might not be as useful as it seems. If a theme is able to show wide images, It can probably show wide tables, wide blocks in general. The `CSS` should be quite similar for all of these. Though, I think we may want to rename it "wide-blocks" or something.

Did you encounter the need of this in one of your themes? Could you elaborate on the "why" if so? 

Thank you.

**Comment by maddisondesigns** [comment]
I don't have a specific case of my own, but so many times there's a need to create a site with boxed content (e.g. the main content is constrained to 1400px, for example),  but then you also want to include a full with call-to-action section with say, a button and some text.

Having an image (wide width), that is part way between full-width and the rest of the content, is not always that useful. Which also means that having a toolbar button there for an image size that is not going to be used, is kinda pointless.

Likewise, what if I don't want the layout to have a table that expands full width. Why should I be forced to show those buttons on Table Blocks, when they're not going to be used in the design. Whilst renaming it to `wide-blocks` fixes the naming issue, it doesn't fix the overall lack of control that theme devs are left with.

**Comment by karmatosed** [comment]
I'm not too sure this is the right approach to things. Users have been crying out for the ability to add themes and do what they want in them. As a theme developer limiting, is to be honest a little how we all used to think and we need together to move a little beyond that. It's time we opened up our thinking with regards to what a theme does/doesn't do and how it limits a user.

I personally, do not think the solution is more granularisation to theme_support, I think that creates an issue going forward. If you travel a little to where page layouts are a thing (beyond 5.0), themes are going to have to adapt and learn that being more like a stylesheet is the way forward.

I get it, it's a little scary to give users control, but it's not giving them total control, you are still setting the borders - they won't fall off a cliff. I would encourage you to think less about setting limits and look more at experimenting no main content constraints. I did this with the Gutenberg theme demo and it really was eye opening.

**Comment by maddisondesigns** [comment]
Users have also been crying out for the ability to create multi-columns layouts, but you seem to have no issue with not providing that functionality in the first version. I have no issues in giving end uses more control to do whatever they want, but you guys need to decide whether you're actually creating a flexible page builder, or you're not. One minute you say you aren't, and then someone else comes along and says that you are.

**Comment by karmatosed** [comment]
@maddisondesigns the Customization focus (after 5.0) is totally going to be looking into page layouts, that was always the plan.

**Comment by lxqueen** [comment]
While perhaps not splitting them into wide supports for each block (as @youknowriad mentioned, the CSS is pretty similar for each block, as well as it being tedious to manually enable/disable for theme authors when new blocks come out), being able to specifically enable wide vs full would be useful.

If a change like this was made, perhaps for compatibility's sake you could have `wide-images` take an array or boolean - if its value is `true` (like how it is today) then both wide & full are supported, or you can specify in the array `['wide', 'full']`.

**Comment by youknowriad** [comment]
Let's close this in favor of #4133

**Comment by maddisondesigns** [comment]
@youknowriad How is this related to #4133?

**Comment by youknowriad** [comment]
Oh sorry I meant #4113

**Comment by maddisondesigns** [comment]
Fair enough. It's a good idea to get rid of the 'gutenberg' name from it
