### ISSUE TITLE
Docs: Adjusting the Development Environment documentation

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28236]
### ---Draft----

I am creating this issue to followup on a few things.

1. Current nvm 0.37.2 version seems to not be working correctly. I will be retesting earlier versions of nvm. I found a releases page here: https://github.com/nvm-sh/nvm/releases. 
At the end when going to localhost:8888 one ends up at a WP login screen. Not in this case. Here one ends up at a WP install screen.
I made a video. At the 7.40 mark you can see that instead of it going to the login screen it goes to a WP install screen: https://youtu.be/X5_ORY5Uyck?t=456

I went back to an earlier version of nvm: 
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash `
The result was the same. I did not get a finished site at the end but ended up at a new install WP screen.
I am wondering if the error in which the site not automatically installing is connected with wp-env which was updated a few weeks ago.

2. In the Quick Start guide it would be helpful to add 1A, 1B etc to make it even more clear in which step one is on.

3. Before going to step 2. I added some information about if one is using something else than Docker then one should not continue following the documentation but instead go and install the software one uses. There are a few steps after that which needs to be done. I am not totally sure yet how to integrate that. I do have the notes.

4. Consolidating various WordPress core and the Gutenberg development environment setup into one document?
Below the setup of development environment. I added a rough testing environment setup to show how it possibly can be done.
https://core.trac.wordpress.org/ticket/51414

--------

### 1. **Install Node development tools**

1A.
Download and install [Node Version Manager](https://github.com/nvm-sh/nvm) (nvm) 

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash`

Quit and restart terminal

1B.
Install the long-term support (lts) version of node.

`nvm install --lts`

If you plan on using the WordPress environment command and Docker then continue to step 2.
If you plan on using for instance Local/MAMP/WAMP/Desktop Server or another graphical user software go to step - **2. Alternative - Using a graphical user interface software.**

### 2. **WordPress Development Site**

2A.
First download, install, and start [Docker Desktop](https://www.docker.com/products/docker-desktop) following the instructions for your OS.

2B.
Install the WordPress environment tool. (NEW) Which makes it easier to work with Gutenberg or any other plugin. 

`npm -g install @wordpress/env`

(NEW) The WordPress environment wp-env is mainly used for developing themes, plugins, blocks, etc.

2C.
Start the environment from an existing plugin or theme directory, or a new working directory:

`wp-env start`

You will have a full WordPress site installed, navigate to: http://localhost:8888/ using your browser, log in to the WordPress dashboard at http://localhost:8888/wp-admin/ using Username “admin” and Password “password”, without the quotes.

-

### 2. **Alternative - Using a graphical user interface software.** 
Continued from step 1B.

Download, install and create a local site using your chosen software.

-
-
---------------------------
-
-

Here is an example of a testing environment. The development environment + testing environment can hopefully be consolidated for WordPress core + other areas + Block editor to create one documentation. The testing environment would be another tutorial. Making the development environment a prerequisite to the testing environment.

### **Testing Environment**
(It needs work. It shows an example.)

We will be setting up a testing environment for WordPress core (Trac tickets) or 
for the Gutenberg plugin ( Pull Requests).

1A. For testing WordPress trac tickets.
Download the WordPress develop Github repository.
For WordPress go to: https://github.com/WordPress/wordpress-develop
Click the green Code button. Select HTTPS and copy the link.

Or

1A. For testing the Gutenberg plugin Pull Requests (PR)
Download the Gutenberg Github repository to the plugins directory of your local site or install it in the root if you installed Docker and WordPress environment. You can install into any directory you choose.
Go to: https://github.com/WordPress/gutenberg Click the green Code button. Select HTTPS and copy the link.

Switching to the local site plugin directory.
Open terminal. Switch to the plugin folder directory. In terminal add `cd` then outside of terminal.
If using Local open Local Sites -> site name -> app -> public -> wp-content and drag the plugin folder into the terminal to see the path. 
`cd /Users/paaljoachimromdahl/Local\ Sites/testinggutenberg/app/public/wp-content/plugins`
Click enter in terminal to go to the plugins folder.

2.
In terminal add the following:
`git clone https://github.com/WordPress/gutenberg.git`
or
`git clone https://github.com/WordPress/wordpress-develop`

3.
Quit and reopen terminal. 
Go to the directory where you cloned the repository. (Example cd wordpress-develop, cd gutenberg or the plugin directory where you cloned the gutenberg respository to.)

4.
For WordPress:
```
npm install
npm run build:dev
npm run env:start
npm run env:install
```

For Gutenberg:
`git pull`
`git checkout `(PR example update/navigation-editor-design) `update/navigation-editor-redesign `
`npm run build`

`wp-env start`

5.
Go to your local site if testing WordPress go to: http://localhost:8889/.
If testing Gutenberg and using Docker go to: http://localhost:8888/.
Login with username: “admin” and password: “password”

Or just login to your own local site made in another way.

@mkaz and @noahtallen

**Comment by ryanwelcher** [comment]
@paaljoachim just wanted to follow up on this to see if we can move it forward.

**Comment by paaljoachim** [comment]
Hey Ryan

I am not able to followup here. Should we go ahead and close it?

**Comment by paaljoachim** [comment]
As the issue is old. There are likely better approaches out there.
