### ISSUE TITLE
Cover Block: Positioning regression

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#28242]
## Description

Cover block has a visual regression in 9.8 RC1 with positioning in the editor.

Expected (9.7)
![Screen Shot 2021-01-15 at 17 07 10](https://user-images.githubusercontent.com/841763/104750262-1f5d2700-5754-11eb-9e79-ac1ff09bd98c.png)

Actual (9.8 RC1)

![Screen Shot 2021-01-15 at 17 06 22](https://user-images.githubusercontent.com/841763/104750190-0785a300-5754-11eb-9ce7-be14dab1d0a6.png)

## Step-by-step reproduction instructions
1. Use Gutenberg 9.8 RC1
2. Add a Cover block
3. Change the background position
4. Observe the visual regression

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.0-rc.1
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? yes

**Comment by sirreal** [comment]
CC @ajlende

**Comment by sirreal** [comment]
The issue is not limited to the editor. See the published post:

Expected (9.7)  

![Screen Shot 2021-01-15 at 17 21 28](https://user-images.githubusercontent.com/841763/104751849-38ff6e00-5756-11eb-8d32-d0de00340883.png)

Actual (9.8 RC1)

![Screen Shot 2021-01-15 at 17 21 18](https://user-images.githubusercontent.com/841763/104751856-3b61c800-5756-11eb-9790-f98ca0068d49.png)

**Comment by jasmussen** [comment]
I recall a very recent PR that removed a height: 100%; value from cover, that seems potentially related. I can't recall which PR, but I recall pinging @senadir, do you recall and/or think this might be related?

**Comment by ockham** [comment]
> I recall a very recent PR that removed a height: 100%; value from cover, that seems potentially related. I can't recall which PR,

@jasmussen This one? https://github.com/WordPress/gutenberg/pull/28114

**Comment by jasmussen** [comment]
That's the one! Thank you. I've reproduced an issue:

<img width="1332" alt="Screenshot 2021-01-18 at 13 39 30" src="https://user-images.githubusercontent.com/1204802/104916668-ad265580-5992-11eb-8c1a-c7a8386fff2c.png">

Adding back `height: 100%;` fixes it, but so does `overflow: hidden;`, so I'm going to try a PR with that.

**Comment by jasmussen** [comment]
I believe that #28287 fixes this issue. I'm not completely sure, so would appreciate your eyes!
