### ISSUE TITLE
Reduce UI Setting removes Breadcrumb bar, but leaves empty space.

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28244]
When you enable the "Reduce the interface" feature (using `Options` -> `Preferences`) the block breadcrumb bar at the bottom of the viewport is removed. However, this leaves an awkward empty space at the bottom of the browser:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/191598/104760588-9207db80-572f-11eb-9354-ec5056289d09.png">

Its hard to notice unless you're using theme styles, and have a colored canvas, like with the 2021 theme.

**Comment by ntsekouras** [comment]
Hey @shaunandrews - I think this is fixed with: https://github.com/WordPress/gutenberg/pull/28133.

I couldn't reproduce it in master. Can you verify?

**Comment by shaunandrews** [comment]
Yup this seems like its been fixed.
