### ISSUE TITLE
InnerBlocks.ButtonBlockAppender blockpicker malfuction

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#28259]
## Description
Block picker vanishes as soon as mouse is not hovered over plus sign. It is almost impossible to pick block. Picking block is only possible if mouse is very quickly transfered to block images. This happens when using InnerBlocks.ButtonBlockAppender as block appender.

## Expected behaviour
Normal block picking.

## Actual behaviour
Block picker disappears upon moving mouse away from "+" sign / block appender (depending where it was clicked).

## WordPress information
WordPress version: 5.6.0

## Device information
Windows 10, Firefox developer edition 85

**Comment by Lovor01** [comment]
While investigating the issue I found import:
`import BaseButtonBlockAppender from '../button-block-appender';`
in button-block-appender.js, however file to import from does not exist, does that even compile?

**Comment by talldan** [comment]
@Lovor01 An import statement like that imports the default export, so in this case it's importing this exported component:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/button-block-appender/index.js#L94

Please could you fill out the required parts of the issue template. If you're able to provide a working code example, that would be appreciated. I've tested the places `ButtonBlockAppender` is used in core blocks (columns, group) and that seems to work ok still. Your implementation may be different though, so that's why a code example would be useful.

**Comment by ballstateumc** [comment]
I've also run into this issue. I'm pretty new to block development so maybe I'm missing something in my code. I'm building on the examples.

I've attached a zip of my code for my test block.

I've noticed that I can use the mouse on the quick inserter if I open it using the default appender when hovering over one of the inner blocks I've already added. I can also use the keyboard to select a new inner block.

[08-myblock-esnext.zip](https://github.com/WordPress/gutenberg/files/5851013/08-myblock-esnext.zip)

**Comment by talldan** [comment]
@ballstateumc You can just define it as:
```jsx
<InnerBlocks renderAppender={ isSelected ?  InnerBlocks.ButtonBlockAppender : undefined } />
```

Which is beneficial as essentially by using an inline function a new component is being declared on every render.

Code looks good though considering you're just starting! I tested and couldn't see an issue:
![render-appender](https://user-images.githubusercontent.com/677833/105437885-ddc10480-5c9c-11eb-83cc-953b3665495f.gif)

I wonder what might be causing your issue. Do you have any other plugins active?

**Comment by ballstateumc** [comment]
Changing that line of code solved the problem. Interesting. Thanks very much for your help, talldan!

**Comment by talldan** [comment]
Hmm, I wonder if @Lovor01 has the same issue. Glad it was solved. I'm going to close the issue, but can always re-open if it's a different problem.

**Comment by Lovor01** [comment]
Hello, 
I had probably the same calling to appender as @ballstateumc. I used following example from 
[Innerblock github readme](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks):
// Utilise a predefined component
<InnerBlocks
	renderAppender={ () => (
		<InnerBlocks.ButtonBlockAppender />
	) }
/>
If this is incorrect, then documentation should be updated! Should I open an issue to fix this in documentation?

I tested your fix and it works.

My original code before using your fix is attached below (just edit component, I think it is sufficient)
[edit.zip](https://github.com/WordPress/gutenberg/files/5856399/edit.zip)

**Comment by talldan** [comment]
Thanks for testing @Lovor01, glad the issue was solved.

If you're happy to put together an issue or PR to update the docs, that would be greatly appreciated.
