### ISSUE TITLE
Editor Freezes Up while Transforming a Block and hovering over Premium Content Block Option

### ISSUE THREAD

**Issue by druesome** [WordPress/gutenberg#28258]
## Description

While transforming an existing block to a different block, as the mouse hovers over the Premium Content block, the editor freezes up.  Problem occurs in Simple and Atomic sites.

## Step-by-step reproduction instructions

1. Create a new post or page on a site with a paid plan
2. Type in some text into a paragraph block
3. On the toolbar above the paragraph, click the P icon to transform it to a different block
4. Hover mouse over different choices without clicking anything.  Hover over the Premium Block option a few times until editor freezes up and becomes unresponsive.

## Expected behaviour

To be able to choose which block to transform to without the editor freezing up.

## Actual behaviour

Editor freezes up after hovering over Premium Content option.

## Screenshots or screen recording

In this screencast I start off with a regular paragraph.  As I 'm transforming the paragraph, I'm avoiding the Premium Content block on purpose.  I transform the paragraph to a list, then to a heading, before I finally over the Premium Content option.  You will see that the editor freezes up afterwards.

Link to screencast: https://d.pr/v/Gt74q3

## WordPress information
- Gutenberg version: 9.7.3

## Device information
- Browser: Chrome and Firefox

**Comment by talldan** [comment]
@druesome There's no Premium Content Block in WordPress core, so I'll close this issue.

**Comment by andrewserong** [comment]
Moved the issue over to https://github.com/Automattic/wp-calypso/issues/48984
