### ISSUE TITLE
RangeControl problem is RTL

### ISSUE THREAD

**Issue by amirmp3** [WordPress/gutenberg#28252]
Hi, there is a problem with RangeControl in RTL it is obvious (ThumbWrapper goes reverse):

![Gutenberg range control for rtl](https://s17.picofile.com/file/8421511368/bandicam_2021_01_16_02_06_32_693_gif.gif)

**Comment by amirmp3** [comment]
I do not know why but sometimes it wrongly adds "Mobile App Android/iOS" to my Gutenberg issues.

**Comment by mchowning** [comment]
> I do not know why but sometimes it wrongly adds "Mobile App Android/iOS" to my Gutenberg issues.

I'm not sure why that would happen. 🤔 I removed the label though.

**Comment by youknowriad** [comment]
Couuld  this be related to #28221
