### ISSUE TITLE
Safari issue on color palette

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2826]
This is what you see in Safari:

![2017-09-28 at 15 41](https://user-images.githubusercontent.com/253067/30972795-83d62b2a-a463-11e7-946d-f4bf4339c641.png)

**Comment by afercia** [comment]
This should already be addressed in https://github.com/WordPress/gutenberg/pull/2680, if only someone could review the PR :)

**Comment by karmatosed** [comment]
Ace, thanks.
