### ISSUE TITLE
Beginning to type too quickly in a new paragraph may cause some characters to be lost

### ISSUE THREAD

**Issue by JDGrimes** [WordPress/gutenberg#2827]
## Issue Overview

I often get to the end of a paragraph, think about what to write next, suddenly get an inspiration, and quickly begin typing the next paragraph.

When I do this in Gutenberg, I often have the very frustrating experience of there being a small delay after hitting return before the new paragraph is added and operable. This means that the characters typed immediately after hitting return are lost.

(This experience is made even worse by the fact that I have Firefox's "Search for text when you start typing option" enabled. So instead of the characters being lost, Firefox picks them up and starts searching the page for them, meaning that I'm whisked away to a different context in a jarring manner. And just when I had my train of thought together!)

## Steps to Reproduce

1. Open the editor.
1. Insert the cursor into the first paragraph.
2. Hit the return key, immediately followed by other characters.

Tested on Firefox 55.0.3 (64-bit) and macOS Sierra 10.12.6.

## Expected Behavior

Whatever is typed immediately after hitting return should appear in the new paragraph.

## Current Behavior

The characters entered immediately after hitting return may be lost.

**Comment by youknowriad** [comment]
This seems fixed probably by #2758
