### ISSUE TITLE
Site Editor: Can't save changes or reload

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28271]
Using Twenty Twenty One Blocks from https://github.com/WordPress/theme-experiments. I cannot save any changes in the Site editor:

<img width="1270" alt="Screenshot 2021-01-18 at 09 48 28" src="https://user-images.githubusercontent.com/1204802/104892612-b1427b00-5972-11eb-8733-afe00ab7b0b5.png">

Pressing the "Update Design" button briefly shows the candybar, then stops. Pressing reload shows the document still dirty:

<img width="372" alt="Screenshot 2021-01-18 at 09 48 34" src="https://user-images.githubusercontent.com/1204802/104892707-cddeb300-5972-11eb-96dd-f79e5d0f20c5.png">

Upon reload, I see a gray screen:

<img width="1270" alt="Screenshot 2021-01-18 at 09 50 12" src="https://user-images.githubusercontent.com/1204802/104892723-d3d49400-5972-11eb-8370-cdd41ffa1a6a.png">

Along with the gray screen comes this console error:

<img width="836" alt="Screenshot 2021-01-18 at 09 48 47" src="https://user-images.githubusercontent.com/1204802/104892770-dd5dfc00-5972-11eb-8ef8-c4dcb45ae04a.png">

This is running latest master branch as of Jan 18th, after a fresh `npm ci && npm run dev`.

**Comment by david-szabo97** [comment]
I can't reproduce this issue. I used to have this problem when we were working on how file-based templates are treated.

Can you try a fresh WP install?

**Comment by jasmussen** [comment]
I tried:

```
rm -rf ./node_modules
npm run wp-env destroy
npm install
npx wp-env start
```

That's as fresh an install as I could muster, and no change. Here's what I see:

![Jan-19-2021 08-22-28](https://user-images.githubusercontent.com/1204802/105001162-a39efb00-5a2f-11eb-943a-3e0d264acd0d.gif)

By the way this is the same issue on two separate environments.

**Comment by david-szabo97** [comment]
Just copy-pasted your commands and run `npm run dev`. Everything works fine. Do you have `.wp-env.override.json`? Can you share it?

**Comment by jasmussen** [comment]
No overrides:

<img width="812" alt="Screenshot 2021-01-19 at 09 53 15" src="https://user-images.githubusercontent.com/1204802/105010565-2e85f280-5a3c-11eb-8a8c-77c32f1c5c27.png">

Thank you for looking.

**Comment by david-szabo97** [comment]
Reproducing gray screen issue:
1. Open site editor
2. Open navigation panel
3. Navigate to "Pages"
4. Open "Sample page" (or any page you have)
5. Press refresh
6. Gray screen 😢  (parameters are removed from the URL after loading on refresh)

**Comment by jasmussen** [comment]
Alright, thanks to excellent help by David above, I was able to nuke my environment using `npx wp-env destroy` and start fresh.

**Important, be sure to type `y` to confirm nuking your environment. If you just press Enter, it doesn't actually nuke it.**

<img width="1261" alt="Screenshot 2021-01-19 at 10 25 52" src="https://user-images.githubusercontent.com/1204802/105015898-511b0a00-5a42-11eb-899c-cb6c77d6cac6.png">

After doing that and restarting, things appeared to work fine again. 

During the debuggin session, David noted that the ID of the footer I was editing was "definitely corrupt". So the issue here, outside of the gray screen issue, is _probably_ due to the fact that my environment had been running for a long time, over a great deal of iterations on the site editor, therefore containing a great deal of junk in the database. For that reason, I'll close it again!

Thank you David.
