### ISSUE TITLE
Reusable blocks: Display outlines

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#28285]
In the Site Editor we've been using outlines to help illustrate the boundaries of a template part when it or its children have been selected. 

Since template parts and reusable blocks are very similar, it might be worth creating UX alignment between these features. Especially since some of the changes in https://github.com/WordPress/gutenberg/issues/27890 degraded the UX a little.

Here's how the outlines would work if we copied the current template part implementation.

### Reusable block hovered

<img width="1216" alt="Screenshot 2021-01-18 at 12 29 43" src="https://user-images.githubusercontent.com/846565/104915652-de9a2380-5988-11eb-8bf8-5c556cef602c.png">

A 1px outline in the theme color appears on hover.

### Reusable block selected and focussed

<img width="1147" alt="Screenshot 2021-01-18 at 12 30 30" src="https://user-images.githubusercontent.com/846565/104915734-fc678880-5988-11eb-961d-fc22e28dd115.png">

The hover outline is increased to 1.5px.

### Reusable block selected, not focussed

<img width="1158" alt="Screenshot 2021-01-18 at 12 31 02" src="https://user-images.githubusercontent.com/846565/104915782-0d17fe80-5989-11eb-88da-576bfad827db.png">

A 1px outline in `$gray-900` appears.

### Reusable block child selected

<img width="1174" alt="Screenshot 2021-01-18 at 12 37 26" src="https://user-images.githubusercontent.com/846565/104916417-f7ef9f80-5989-11eb-93b2-0a75906c2b67.png">

A 1px outline in `$gray-900` on the reusable block persists when child blocks are selected.

**Comment by jasmussen** [comment]
Good ticket, I did some initial work in #28285, and am happy to tweak to expand it.

**Comment by mtias** [comment]
Marking this as done now that we have the overlay support.
