### ISSUE TITLE
Holding backspace across paragraph blocks does not delete text

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2829]
__Steps to reproduce:__

1. Navigate to Gutenberg > New Post
2. Insert many paragraph blocks, each with some text
3. From the last paragraph block, press and hold backspace

__Expected result:__

All text is deleted.

__Actual result:__

Text from the removed paragraph appears to be appended to the previous block.

![backspace](https://user-images.githubusercontent.com/1779930/30988497-7785407c-a468-11e7-8e5e-e9de1f9ada2e.gif)

**Comment by iseulde** [comment]
Maybe related: At the end of a paragraph, press ENTER twice fast. Two paragraphs are created, but the caret ends up in the top one.

**Comment by iseulde** [comment]
Reproducing the GIF, you can even feel that there is a delay and that it's not done in the same call stack.

**Comment by EphoxJames** [comment]
I have a PR for this issue in #3450 . It was caused by the React state not being in sync with TinyMCE's state which in turn was caused by the `isDirty` function returning an out of date response.
