### ISSUE TITLE
Allow Paragraph Block to Transform to a Buttons Block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#28298]
## What problem does this address?

Especially when transforming content from the Classic Editor or other CMSes to blocks, I am often faced with a paragraph that contains only a link and should be a button.

## What is your proposed solution?
If a paragraph only contains a link, allow it to be transformed to a button with the existing link and anchor text.

![Diagram of the transform. A paragraph block with "Link in Paragraph" link text followed by a transformed button block with "Link in Paragraph" label](https://user-images.githubusercontent.com/1238696/104948535-4bee8a00-5972-11eb-87da-94b5de6bb609.png)

![Screenshot of Paragraph block transform options with "Button" written in at end of transform options](https://user-images.githubusercontent.com/1238696/104948724-996af700-5972-11eb-994b-93f591928bc4.png)

**Comment by mtias** [comment]
Makes sense!

**Comment by hsingyuc** [comment]
I'll give it a shot
