### ISSUE TITLE
Error in HTML anchor field description

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/gutenberg#28296]
## Description of HTML anchor in settings sidebar of blocks

Currently, the HTML Anchor field is described as follows: "Enter a word or two — without spaces — to make a unique web address just for this heading, called an “anchor.” Then, you’ll be able to link directly to this section of your page." 
Link to string on translate: https://translate.wordpress.org/projects/wp/dev/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8431365&filters%5Btranslation_id%5D=66590331

The problem lies in the use of the term "heading" which is inappropriate since it is possible to define an HTML anchor on all the blocks (with a few exceptions) whereas the term "heading" refers only to the Heading block.

## Proposed solution

I propose to simply replace the term "heading" by the term "block" in these string.
"Enter a word or two — without spaces — to make a unique web address just for this block, called an “anchor.” Then, you’ll be able to link directly to this section of your page." 

Thus there will be no more inaccuracy on the element to which the anchor is applied.

Thank you for your attention to this enhancement request.

![HTML-anchor-field-description](https://user-images.githubusercontent.com/75045144/104943970-d1942900-59b6-11eb-8b76-1f87178982a5.png)

**Comment by jennydupuy** [comment]
Hi,
I would be interested in making the modification. How do I proceed?

**Comment by 96RadhikaJadhav** [comment]
@talldan @jennydupuy Is this issue already taken or can I work on it?

**Comment by jennydupuy** [comment]
> @talldan @jennydupuy Is this issue already taken or can I work on it?

Sorry I didn't see your message until after I made the change.
