### ISSUE TITLE
Interactive blocks: Map, Contact Form, Audio, Playlist

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#283]
Here are a stack of new blocks that depict slightly more complex blocks. Working on these blocks raised a few questions that @j-falk also raised in Slack: where does configuration happen? While we have many ideas, there's no place like mockups to hash them out, so here goes.

### Map

Empty:

![map empty](https://cloud.githubusercontent.com/assets/1204802/23994335/d6015514-0a44-11e7-8526-8bf1aa0f51b9.png)

Empty, Hover:

![map empty hover](https://cloud.githubusercontent.com/assets/1204802/23994342/de362a7a-0a44-11e7-889f-4ca5afc07993.png)

Neutral:

![map neutral](https://cloud.githubusercontent.com/assets/1204802/23994350/e32c7cbe-0a44-11e7-94e4-447d1130e736.png)

Hover:

![map hover](https://cloud.githubusercontent.com/assets/1204802/23994355/e6e9334c-0a44-11e7-95ed-fbd909776a42.png)

Selected:

![map selected](https://cloud.githubusercontent.com/assets/1204802/23994359/ea52ae3c-0a44-11e7-9678-ade478abac3c.png)

Caption:

![map caption](https://cloud.githubusercontent.com/assets/1204802/23994367/ef13ba42-0a44-11e7-92f0-edf539360060.png)

---

### Contact Form

Neutral:

![contact form](https://cloud.githubusercontent.com/assets/1204802/23994396/19a8fbd2-0a45-11e7-830d-722e8767f37a.png)

Hover:

![contact form hover](https://cloud.githubusercontent.com/assets/1204802/23994404/1fcb349e-0a45-11e7-86a2-229179f89c0a.png)

Selected:

![contact form selected](https://cloud.githubusercontent.com/assets/1204802/23994407/241dcd68-0a45-11e7-97e1-b366d0e49c80.png)

---

### Audio Shortcode

Empty:

![audio empty neutral](https://cloud.githubusercontent.com/assets/1204802/23994424/36876fae-0a45-11e7-809b-4ba2fc147073.png)

Empty, Hover: 

![audio empty hover](https://cloud.githubusercontent.com/assets/1204802/23994435/3bad2b9a-0a45-11e7-80ef-096592abae8a.png)

Neutral:

![audio neutral](https://cloud.githubusercontent.com/assets/1204802/23994438/3f992222-0a45-11e7-9968-b4d04da13e50.png)

Hover:

![audio hover](https://cloud.githubusercontent.com/assets/1204802/23994441/42f2dc38-0a45-11e7-83d5-f3530a17f4dc.png)

Selected:

![audio selected](https://cloud.githubusercontent.com/assets/1204802/23994445/4823f34a-0a45-11e7-82f0-c05326c729a2.png)

Caption:

![audio caption](https://cloud.githubusercontent.com/assets/1204802/23994452/4b91bc42-0a45-11e7-887b-048a5ebda439.png)

---

### Playlist Shortcode

Empty:

![playlist empty](https://cloud.githubusercontent.com/assets/1204802/23994488/6a96bf3e-0a45-11e7-9602-a74b114a8e38.png)

Empty, Hover:

![playlist empty hover](https://cloud.githubusercontent.com/assets/1204802/23994491/6d7bd04a-0a45-11e7-86c0-d774139d870f.png)

Neutral:

![playlist neutral](https://cloud.githubusercontent.com/assets/1204802/23994495/70e1264a-0a45-11e7-8cae-5806c20f0865.png)

Hover:

![playlist hover](https://cloud.githubusercontent.com/assets/1204802/23994498/752c0d32-0a45-11e7-9385-5332e45d0871.png)

Selected:

![playlist selected](https://cloud.githubusercontent.com/assets/1204802/23994502/796884d4-0a45-11e7-9a4f-fa1bbbb972f4.png)

Caption:

![playlist caption](https://cloud.githubusercontent.com/assets/1204802/23994506/7dc57e24-0a45-11e7-9c00-088847aa0ad4.png)

---

### Questions

Some issues arise that need discussing:

- What do we do with the type switcher when the block can't be converted into something else, or there isn't yet any compatible block types installed via plugins? Do we still show it as a type indicator?
- It is tempting, like on the Playlist, to show a "Edit Contact Form" button on the block placeholder itself, to open the modal where editing the form will likely happen. Is that a better UI than the edit button on the toolbar?

**Comment by youknowriad** [comment]
Do you think showing a "preview" of the Contact Form is worth it? I mean, can't we just show the form for adding/editing the fields instead (to avoid having to click on a button to open a modal or something)?

**Comment by jasmussen** [comment]
> Do you think showing a "preview" of the Contact Form is worth it?

Not sure. The contact form is probably not going to be a core block, and so it's more of a "this is what a plugin could add" concept block. It's tricky because should the form be enabled or disabled in this view? How do you select "just the block" (same problem as with an embedded YouTube video, how do you select it without pressing play). 

On the flipside to this argument, perhaps the form is disabled until you click into the block. Then it becomes editable right there. I like that.

**Comment by joyously** [comment]
To avoid "using" the block while editing, perhaps these types of blocks should stay in the mode of data entry, and the control block could have a Preview button. This would help in verifying the inputs, such as comparing two videos that look similar, and selecting and moving the block.

**Comment by inhll** [comment]
> It is tempting, like on the Playlist, to show a "Edit Contact Form" button on the block placeholder itself, to open the modal where editing the form will likely happen. Is that a better UI than the edit button on the toolbar?

I would say the edit button remaining on the toolbar is the best option. Clicking the edit button could pop up a modal to allow form editing in a context that is clearer than having to remove and re-add the block.

![map](https://cloud.githubusercontent.com/assets/406182/24152657/4f65ac74-0e1a-11e7-8486-409857f3980a.png)

**Comment by mtias** [comment]
Let's create individual issues so we can assign them.

**Comment by jasmussen** [comment]
> Let's create individual issues so we can assign them.

On it.

**Comment by jasmussen** [comment]
Closing in favor of #803, #804, #805. Contact Form was always meant to be an example of how a plugin could add such a block, not an effort we should pursue.
