### ISSUE TITLE
Post Locking: Alert is not implemented

### ISSUE THREAD

**Issue by munyagu** [WordPress/gutenberg#2830]
Classic editor has post locking alert.
I noticed it when I saw the ticket [#42023](https://core.trac.wordpress.org/ticket/42023), post lock alert is not displayed in Gutenburg.
Was it to be deleted in Gutenberg?

**Comment by mtias** [comment]
We haven't looked at it yet. We are also working on collaborative editing features that might change how this is handled, as we can lock per block instead of the whole post.

**Comment by munyagu** [comment]
Thank you for reply.
Issue should be issued for the collaborative editing, not the lock alert.
I close this issue.
