### ISSUE TITLE
Site Editor: Refreshing when editing a post or page is causing a gray screen

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#28315]
## Step-by-step reproduction instructions
1. Open site editor
2. Open navigation panel
3. Navigate to "Pages"
4. Open "Sample page" (or any page you have)
5. Press refresh
6. Gray screen 😢  (parameters are removed from the URL after loading on refresh)

## Expected behaviour
Page to load

## Actual behaviour
Nothing is loaded

## Code
https://github.com/WordPress/gutenberg/blob/97f0a489276c85af2bf3c764bc1fb315b5ecb0bd/packages/edit-site/src/components/url-query-controller/index.js

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/2256104/105016576-1796ce80-5a43-11eb-8034-7d698522b579.mov

**Comment by mattwiebe** [comment]
After investigating a bit further, it looks like a `fetch` call to `wp-admin/admin.php?p=6&_wp-find-template=true` is returning an empty result but with a `200` response code. This makes `res.json()` [here](https://github.com/WordPress/gutenberg/blob/ec839611b9958568ac9d3d1a04fd27e09696cc25/packages/core-data/src/controls.js#L11) fail.
