### ISSUE TITLE
Social Icons: Move color options to block toolbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28314]
In #28084, social icons landed the ability to change foreground and background colors of icons.

This happens in the sidebar, but it's such a useful action, it should happen in the toolbar. Like this, perhaps:

<img width="1083" alt="105010409-f67eaf80-5a3b-11eb-8a61-7cc55e4df323" src="https://user-images.githubusercontent.com/1204802/105012086-0a2b1580-5a3e-11eb-8122-e6292f881730.png">

This mockup is inspired by [this original design](https://github.com/WordPress/gutenberg/issues/21605#issuecomment-692928358), but expanded with a little influence from #27331.

**Comment by carolinan** [comment]
Is this still something we want to implement?

**Comment by jasmussen** [comment]
The design is a bit out of date, but in my mind it still makes sense to do this, including for other blocks where the color plays a prominent role, such as Cover.

**Comment by jasmussen** [comment]
I'll close this for now. As out of date as the visuals are, let's revisit separately.
