### ISSUE TITLE
Site Editor: Double scrollbar (mispositioned Top toolbar) and laggy drag/drop

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#28327]
## Description

**Video Recording**
https://d.pr/v/WUJKxU

Haiii! I noticed these interaction issues this morning when I poked around the Site Editor.

#### Double Scrollbar

<img width="1243" alt="Screen Shot 2021-01-19 at 8 56 04 AM" src="https://user-images.githubusercontent.com/2322354/105044262-8587c980-5a34-11eb-867f-4c9f56665bc7.png">

When previewing a block in the inserter, I noticed a double scrollbar happening in the canvas.

I believe it may be from the mispositioned Top Toolbar UI (which is at the bottom)

<img width="1426" alt="Screen Shot 2021-01-19 at 8 55 54 AM" src="https://user-images.githubusercontent.com/2322354/105044314-946e7c00-5a34-11eb-96ff-f77ae3019404.png">

#### Laggy Drag/Drop

<img width="721" alt="Screen Shot 2021-01-19 at 8 56 16 AM" src="https://user-images.githubusercontent.com/2322354/105044391-a9e3a600-5a34-11eb-9e0e-488aa4bd00bf.png">

The drag/drop experience from the Block Inserter is also really laggy. (Better seen in my video clip)
In the screenshot above, you can see the draggable chip UI isn't close to where my mouse cursor.

In a prior test (before my video recording), my browser (Chrome) literally crashed when I was dragging around an item from the Block Inserter. However, I'm not sure if it's related or not. I did have the Developer Inspector open, which does slow things down a bit more. (Note: My computer has been acting very odd as of last. So this may be an isolated issue)

## WordPress information
- Gutenberg version: `master`

## Device information
- Device: Desktop
- Operating system: Mac OS
- Browser: Chrome Version 87.0.4280.141

**Comment by annezazu** [comment]
This was replicated by [someone testing for the FSE Outreach program](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1387).

![b82dbf38-9694-4302-9a16-2ab9aa25ed62](https://user-images.githubusercontent.com/26996883/110046670-b3398100-7d09-11eb-8b41-53372e97e40a.gif)

 They tested with Windows 10, Docker Desktop/WSL2 and Chrome 88.0.4324.190 using Gutenberg 10.0.

**Comment by annezazu** [comment]
Going to close this out since there's slightly more information in this duplicated issue: https://github.com/WordPress/gutenberg/issues/30055
