### ISSUE TITLE
Spotify Embed: Aspect ratio incorrectly identified

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28347]
Steps to reproduce:

- Paste an amazing song from Spotify into the editor, for example this one: `https://open.spotify.com/track/7b4yGtR0rujvLi5EBfKKJ2`
- Observe how the embed is way taller than it should be

<img width="714" alt="Screenshot 2021-01-20 at 10 26 12" src="https://user-images.githubusercontent.com/1204802/105154535-ee8d4100-5b09-11eb-973d-adcb1ab4aba1.png">

If we look under the "Advanced" panel, we can see these classes are applied:

`wp-embed-aspect-9-16 wp-has-aspect-ratio`

Looking at the Spotify embed, it appears to calculate the height it needs to show and apply that directly to the iframe. So there's probably a bit of a race condition going on there. 

Some potential solutions:

- Except the Spotify embed from the aspect ratio correction, just allow it to be 100% width.
- Improve the aspect ratio detection to detect the spotify embed as 1:1 aspect ratio.

**Comment by kjellr** [comment]
Possibly related to #27720
