### ISSUE TITLE
Spotify Embed: Can't select block after saving/reloading

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28348]
Steps to reprocuce:

1. Paste an amazing song into the block editor, such as `https://open.spotify.com/track/5atQ2haKP5LT65WM0KUts3`
2. Save, reload
3. Try to click the embed to select it. Observe it doesn't work.
4. You can select the embed if you use the block navigation dropdown. 

<img width="816" alt="Screenshot 2021-01-20 at 10 35 53" src="https://user-images.githubusercontent.com/1204802/105155784-48dad180-5b0b-11eb-8432-a07ed3a45d54.png">

Potentially related to https://github.com/WordPress/gutenberg/issues/28166

**Comment by ntsekouras** [comment]
This seems to affect `embed` block in general and other blocks probably.  

Related PR with some more info: https://github.com/WordPress/gutenberg/pull/28658

**Comment by ntsekouras** [comment]
Closing this in favor of: https://github.com/WordPress/gutenberg/issues/28880, as it's about the embed block in general.
