### ISSUE TITLE
More Menu: Doesn't close if opening a modal first

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28345]
If you click the More menu, the right most ellipsis in the top toolbar, and then click outside, or on another menu item, it closes as it should.

If you open a modal from the ellipsis menu, such as the welcome guide, or preferences, then the ellipsis menu no longer closes if you click outside it. GIF showing this:

![Jan-20-2021 08-38-44](https://user-images.githubusercontent.com/1204802/105142762-41abc780-5afb-11eb-80de-d869cab4d1a0.gif)

**Comment by talldan** [comment]
Looks like a duplicate of https://github.com/WordPress/gutenberg/issues/28089

**Comment by jasmussen** [comment]
My apologies, and thanks so much for the triage!
