### ISSUE TITLE
Social block icons misshapen when used in navigation block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28340]
## Description
When adding a social icon in a navigation block, the icons are oblong instead of circles.

## Step-by-step reproduction instructions
1. Add a navigation block.
2. Start with an empty nav block
3. Add a Social block within the nav block
4. Add some social icons

## Expected behaviour
The icons appear as circles, like they do when the block is used outside of navigation

## Actual behaviour
The icons are oblong

## Screenshots or screen recording (optional)
<img width="423" alt="Screenshot 2021-01-20 at 10 42 02 am" src="https://user-images.githubusercontent.com/677833/105119887-27c6b080-5b0c-11eb-803a-b734fec722e6.png">

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8rc1 (on the master branch)
- Are all plugins except Gutenberg deactivated? Y
- Are you using a default theme (e.g. Twenty Twenty-One)? Y (2021)

## Device information
- Device: Desktop
- Operating system: Mac OS
- Browser: Brave

**Comment by Arash-11** [comment]
Hey! I'm a newbie to open source but I'm going to take a stab at this issue.

**Comment by talldan** [comment]
That'd be great, thanks @Arash-11. Let us know if you need any assistance along the way.

**Comment by Arash-11** [comment]
Thanks a lot @talldan, I'll definitely let you know.

**Comment by Arash-11** [comment]
Hi @talldan. I apologize for the newbie question but I was wondering how long it usually takes for a pull request to get reviewed/merged? I'm just curious as this is my first main contribution :)

**Comment by jasmussen** [comment]
Hi @Arash-11, thank you for your work. From looking at https://github.com/Arash-11/gutenberg/commit/d6b39014ec6bb4b8d3fafa886ea77bb393feb78e, the code seems like it might work, though I'd like to test it a bit more deeply. Have you made it into a pull request, though? I wasn't immediately able to find a pull request attached to your commit. That would make it easier to test. Thank you.

**Comment by Arash-11** [comment]
Hi @jasmussen, I am happy to have been able to work on it. I did do a pull request: https://github.com/WordPress/gutenberg/pull/28448#issue-560504477

But I _might_ have done it wrong then, I didn't do a PR on my forked copy but on the original repo. Please let me know if I did this incorrectly.

**Comment by Arash-11** [comment]
I apologize, looks like I missed the following step and did it wrong.

> Step 7: Go to your forked repository on GitHub -- it will automatically detect the change and give you a link to create a pull request.

Should I do a pull request now, in my own forked copy?

**Comment by jasmussen** [comment]
> Should I do a pull request now, in my own forked copy?

Yes, exactly! That will allow me to check out your fork, and compile the pull request to test it. Thank you!

**Comment by Arash-11** [comment]
Got you! I did a new pull request: https://github.com/Arash-11/gutenberg/pull/1#issue-565160695. Thank you so much for the help!

**Comment by talldan** [comment]
@Arash-11 Sorry for missing your pull request. Looks like you followed the right process when you made the PR #28448. It can sometimes take a little while for code to be reviewed, and other times it happens quickly.

To help link the issue and the PR together, it's good to write 'Fixes #28340' in the PR description instead of the title. Github automatically then links the issue and the PR together (https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).

**Comment by Arash-11** [comment]
@talldan No worries. Good to know I followed the correct process, and thanks for the information about the code review process.

Also, thanks for letting me know about how linking the issue and the PR works in GitHub - I didn't know this.

**Comment by jasmussen** [comment]
I reviewed your PR, thanks again! Take a look, let me know how I can help.

**Comment by Arash-11** [comment]
Thank **you** for reviewing my PR!
