### ISSUE TITLE
dev and build scripts intermittently hang

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#28369]
## Description

The `dev` and `build` commands intermittently hang after reaching 100%:

```
> gutenberg@9.8.0-rc.1 build:package-types /home/fullofcaffeine/workspace/code/gutenberg
> node ./bin/packages/validate-typescript-version.js && tsc --build
Build Progress: [==============================] 100% << stays here forever
```

The issue is intermittent, sometimes it does work fine. In the case of `dev`, it might work in the first compile, but fail when incrementally compiling (watching), even though there's no visual feedback of any error.

## Step-by-step reproduction instructions

This is more of a heisenbug. I've asked other GB developers and they _don't seem_ to experience it. Maybe it's related to my env. It happens intermittently when I run: `npm run dev` or `npm run build` as I described above.

I've tried to debug it and found the culprit, though I can't explain the reason why it happens, yet. It seems to be related to the usage of the prefix increment operator [here](https://github.com/WordPress/gutenberg/blob/master/bin/packages/build.js#L250), though I haven't investigated any further. I did manage to fix it locally with the following diff: 

```diff
diff --git i/bin/packages/build.js w/bin/packages/build.js
index f2a9e38187..82f59a2ade 100755
--- i/bin/packages/build.js
+++ w/bin/packages/build.js
@@ -243,11 +243,17 @@ stream
                                // process does exit, it exits with a non-zero code to reflect the
                                // fact that an error had occurred.
                                process.exitCode = 1;

                                console.error( error );
                        }
 
-                       if ( ended && ++complete === files.length ) {
+                       complete = complete + 1;
+
+                       console.log( 'complete: ', complete );
+                       console.log( 'files.length: ', files.length );
+                       console.log( 'ended: ', ended );
+
+                       if ( ended && complete === files.length ) {
+                               console.log( 'finished' );
                                workerFarm.end( worker );
                        }
                } )
```

By incrementing with `complete = complete+1` and removing the prefix `++` op from the condition expression, it seems to finish consistently with the `complete` number always being eql to `files.length` 🤔 

## Expected behaviour

I expect the build script to finish successfully, consistently; the same goes for dev, which should also watch and compile changed files without failing silently.

## Actual behavior

The `dev` and `build` commands intermittently hang after reaching 100% in the progress bar.

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 18.04
- NodeJS: `14.15.4`
- NPM: `6.14.11`

**Comment by fullofcaffeine** [comment]
If this happens to be a bug and the diff is a suitable fix, let me know and I'll create a PR. Thanks!

**Comment by kathrynwp** [comment]
Hi @gziolo - please let me know if you think this should be kept open, since there's been no movement on it in over a year, no further reports, and the original reporter found a workaround. Thanks!

**Comment by gziolo** [comment]
@fullofcaffeine, do you still encounter the same issue?

@kathrynwp, let's wait for confirmation. There aren't any more reports for the same issue.

**Comment by gaambo** [comment]
Not OP, but I encountered the issue a few times, but could track it down to a problem in WSL (with Ubuntu as well) - happens in other projects with large npm tasks as well.

**Comment by kathrynwp** [comment]
Thanks, @gaambo – so just to be clear, this issue not specific to Gutenberg, is that right?

**Comment by gaambo** [comment]
> Thanks, @gaambo – so just to be clear, this issue not specific to Gutenberg, is that right?

Yes, at least in my case, that's true!

**Comment by Thelmachido** [comment]
Since this is not specific to Gutenberg I will be adding the not applicable label.

**Comment by jordesign** [comment]
Given the lack of further activity on this issue - I'm going to close it out. @fullofcaffeine  if you still have the intermittent issue and feel it needs looking at - please feel free to re-open.
