### ISSUE TITLE
Navigation block children not inheriting inline styles

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#28374]
## Description

When setting custom color or background-color on the Navigation block, its child blocks aren't receiving the `style` attribute as they should. This mainly has repercussions for `background-color` that, unlike `color`, isn't inherited, so submenu dropdowns aren't getting the correct background color.

Looking at [this code](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation-link/edit.js#L263) for the editor view, and [this code](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation-link/index.php#L126) for the front end, I would expect any `style` attribute on the `nav` to also be attached to the `li` element in Navigation link, but nothing is coming through:

<img width="499" alt="Screen Shot 2021-01-21 at 1 43 41 pm" src="https://user-images.githubusercontent.com/8096000/105273094-ba3f8080-5bee-11eb-9cc6-9ce3ea34679a.png">
<img width="605" alt="Screen Shot 2021-01-21 at 1 43 49 pm" src="https://user-images.githubusercontent.com/8096000/105273103-bca1da80-5bee-11eb-8ac9-96d7fce7f5d8.png">

## Expected behaviour

Expected inline styles to apply to children of the Navigation block.

## Screenshots or screen recording (optional)

Front end:

<img width="690" alt="Screen Shot 2021-01-21 at 1 23 09 pm" src="https://user-images.githubusercontent.com/8096000/105273476-7d27be00-5bef-11eb-908b-feed86828711.png">

Editor with theme styles (background color is not applying at all, I think due to a theme styling issue):

<img width="625" alt="Screen Shot 2021-01-21 at 1 24 10 pm" src="https://user-images.githubusercontent.com/8096000/105273512-89138000-5bef-11eb-96ff-303b5c49943b.png">

Editor without theme styles:

<img width="786" alt="Screen Shot 2021-01-21 at 1 24 29 pm" src="https://user-images.githubusercontent.com/8096000/105273548-9e88aa00-5bef-11eb-99e3-498da481a806.png">

**Comment by talldan** [comment]
Just to add a couple of extra things, when choosing a predefined (non-custom) background color, the `has-colorname-background-color` class is being added but not the `has-background-color` class within the editor:
<img width="269" alt="Screenshot 2021-01-21 at 11 13 16 am" src="https://user-images.githubusercontent.com/677833/105275400-3bd8e380-5bda-11eb-99db-cc128181080d.png">

Also here you can see I set the text color (`has-yellow-color`), which worked ok initially in the editor, but as soon as I set a background the text color changed back to the default dark gray (as seen in the screenshot below).

On the frontend things look ok though.

The `li` that contains the appender also doesn't have a background:
<img width="406" alt="Screenshot 2021-01-21 at 11 10 02 am" src="https://user-images.githubusercontent.com/677833/105275458-5e6afc80-5bda-11eb-9dec-d6aa87801c5d.png">

Which makes me wonder if the background style should be set on the `ul`?

**Comment by tellthemachines** [comment]
> Which makes me wonder if the background style should be set on the ul?

Ideally all the submenu `ul`s should have their `background-color` set to `inherit`. The only exception is if there's no background set on the Nav block, in which case we should set it to the default editor background color/themes should set it to their background color.

**Comment by tellthemachines** [comment]
Fixed by #28868.
