### ISSUE TITLE
PHP notice in the Comments screen

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2838]
On current master:

To reproduce:
- go in the Comments screen
- click on "quick edit" or "reply" to open the related forms

![screen shot 2017-09-29 at 18 28 12](https://user-images.githubusercontent.com/1682452/31026706-b3f6bf74-a547-11e7-9713-f7430f2a2148.png)

**Comment by notnownikki** [comment]
Fix on the way... thanks!

**Comment by notnownikki** [comment]
https://github.com/WordPress/gutenberg/pull/2853

**Comment by karmatosed** [comment]
Fixed in #2853 and tested.
