### ISSUE TITLE
Delete key deletes all content in paragraph block, when drop-cap is turned on

### ISSUE THREAD

**Issue by richardtape** [WordPress/gutenberg#2839]
## Issue Overview
My very first time using Gutenberg, so apologies if this is known (I tried to look for similar issues, but came up empty).

I'd typed a paragraph of text, ish, got distracted, and the block (I'm guessing) auto-saved. When I gave that tab focus again, the block itself had lost focus. So I click in. Noticed a typo, and pressed the delete key (backspace). This deleted all the text in the block. `cmd-z` worked well. I then tried moving left/right with the arrow keys and then pressing the `delete` key again - same result, all text in block disappeared. Tried a few other things like pressing `return` and then `delete` - same result. Also tried moving cursor position with the mouse and then pressing `delete` - same result.

## Steps to Reproduce (for bugs)

Video of issue: https://www.dropbox.com/s/tctemhb48gvvt5m/delete-key-deletes-block.mp4?dl=0

Gutenberg version: Version 1.2.1
WordPress version: 4.8.2
PHP: 7.1
O/S: Mac 10.12.6
Browser: Chrome 61.0.3163.100 (Official Build)
No other plugins enabled other than https://gist.github.com/pento/19b35d621709042fc899e394a9387a54 (but disabling this doesn't affect this behaviour shown).

## Expected Behavior

I expected pressing the `delete` key would delete the character to the left of the cursor.

## Current Behavior

Pressing the `delete` key deletes all content in the paragraph block

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by richardtape** [comment]
Update: It seems related to the drop-cap. With this turned on, the last character in the block is misaligned with the cursor and using the backspace/delete key removes all the text. Without the drop-cap, the delete/backspace key works as expected.

**Comment by mtias** [comment]
Confirmed bug (new behaviour).

**Comment by youknowriad** [comment]
I can't seem to reproduce this anymore. Closing let me know if I missed something
