### ISSUE TITLE
[eslint-plugin] Error: ESLint couldn't find the plugin "eslint-plugin-import"

### ISSUE THREAD

**Issue by marekdedic** [WordPress/gutenberg#28391]
## Description
Hi, after updating `@wordpress/eslint-plugin` to version 8.0.0, I am getting the error `ESLint couldn't find the plugin "eslint-plugin-import".` I don't have this package installed and do not use it. This seems to me like `@wordpress/eslint-plugin` depends on `eslint-plugin-import` but does not have it listed in its dependencies (as confirmed by looking at its `package.json`).

## Step-by-step reproduction instructions
Please do see https://github.com/skaut/skaut-google-drive-gallery/pull/814/checks?check_run_id=1740746218

## Expected behaviour
Linting works...

## Actual behaviour
Eslint crashes with the aforementioned error.

## Device information
- Device: Desktop
- Operating system: Debian testing

Please let me know if additional info is needed.

**Comment by gziolo** [comment]
`@wordpress/eslint-plugin@8.0.1` is available on npm with the fix included.

**Comment by marekdedic** [comment]
Thanks!
