### ISSUE TITLE
Allow showing default palettes in addition to theme ones

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#28416]
There are several plans for improving the handling of color tools as part of #27331.

However, a small initial task that can be done before the refactor takes place is allowing for gradient presets to coexist with theme defined gradients unless a theme specifically disallows them. Right now, a theme might register their own gradients for specific effects like:

![image](https://user-images.githubusercontent.com/548849/105484821-42d02680-5cac-11eb-9b5c-2392dfa544ce.png)

And that means the user loses access to the default presets. It'd be nice to be able to have one after the other. We need to figure out what disabling / enabling means from a theme.json perspective.

cc @nosolosw @ItsJonQ

**Comment by mtias** [comment]
@jorgefilipecosta I believe we have done this already, can you confirm?

**Comment by jorgefilipecosta** [comment]
Yes, this task is complete!
