### ISSUE TITLE
Latest Post block: Not able to select block after leaving and returning to the page.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28417]
## Description
Not able to select Latest Post block after having saved the page it is located in.

## Expected behaviour

I expected to be able to select the Latest Post block after having saved and refreshed the page.

## Actual behaviour

Not able to select Latest post block after having saved and refreshed the page.

## Screenshots or screen recording (optional)

![Not-able-to-select-latest-post-block-after-save](https://user-images.githubusercontent.com/5323259/105485527-53cd6780-5cad-11eb-8a03-91b445d309d7.gif)

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Twenty Twenty One)

## Device information
Local site using Desktop Server.
Chrome
Mac OSX 10.15.7

@ntsekouras Nik I believe you would like to know about this bug.

**Comment by mcsf** [comment]
Do we know what introduced this bug? @ntsekouras

**Comment by ntsekouras** [comment]
> Do we know what introduced this bug? @ntsekouras

I haven't pinpointed but it seems relevant to the recent refactors: https://github.com/WordPress/gutenberg/pull/27503, https://github.com/WordPress/gutenberg/pull/27572 and the other ones from Riad.

**Comment by paaljoachim** [comment]
I believe this issue is the same as I reported.
https://github.com/WordPress/gutenberg/issues/28536
