### ISSUE TITLE
Site Editor: cover block overlay color not passed thru

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#28427]
## Description
In the Site Editor, if a page contains a cover block with a background overlay color (either palette color or custom color), the color is not passed to the cover block.

## Step-by-step reproduction instructions
Add or edit a post/page.
Add a cover block, and set the overlay color to a palette color or a custom color.
Close post editor and navigate to the Site Editor.
Select relevant template that will display the post/page created above.
The cover block with the custom overlay color does not contain the required inline background-color style.
If you change/add an overlay color while in the Site Editor, the inline style is rendered correctly, but not with cover blocks that were previously edited in the post editor.
The other inline style (min-height) is passed thru correctly, but not the overlay color.

## Expected behaviour
Block cover should have the same background color as defined in the post editor.

## Actual behaviour
In Site Editor the inline background-color is missing from the cover block.

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes - TT1 Blocks

**Comment by stokesman** [comment]
I believe this was fixed by the changes in #28565. I've tested with the plugin built off master. It looks like those changes are going to be in 9.9 so could be verified then.

**Comment by brentswisher** [comment]
I checked and also am not getting this error anymore. I'm closing the issue but @Sandstromer if you are still seeing it on your end with the latest version, just leave a comment here and I can open it back up. Thanks for reporting!
