### ISSUE TITLE
getEntityRecords returns nothing if one of the included IDs doesn't exist

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#28429]
## Description
When using the `include` parameter with `getEntityRecords`, if one of the specific posts to include doesn't exist, it never returns anything.

## Step-by-step reproduction instructions
See code below.

## Expected behaviour
I would expect an array with objects for the IDs that do exist.

## Actual behaviour
As far as I can tell, nothing is ever returned.

## Code snippet (optional)
I am using this in the `edit` function of a custom block:

```js
const ids = [ /* media IDs */ ];
const images = useSelect( ( select ) => {
	return select( 'core' ).getEntityRecords( 'postType', 'attachment', {
		include: ids,
	} );
} );
```

If the `ids` array contains only media item IDs that exist, it returns an array of media objects as expected. However, if the `ids` array contains an ID of a media item that doesn't exist (for example, you permanently delete that media item), it never returns anything—the `images` variable never gets updated.

If I use `apiFetch` instead, it does return an array of media objects, with the invalid one removed:

```js
apiFetch( {
	path: addQueryArgs( '/wp/v2/media', {
		include: ids.join( ',' ),
	} ),
} )
```

I would expect `getEntityRecords` to behave similar to `apiFetch` in this regard.

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No (my custom block where I am seeing the issue is in a custom theme)

## Device information
- Device: Desktop
- Operating system: MacOS 11.1
- Browser: Safari 14.0.2

**Comment by talldan** [comment]
Thanks for reporting this. From what I can see, the REST API returns the items that exist, but then `getEntityRecords` at some point filters them out. Seems like an unexpected result, so I'd consider it a bug.

**Comment by Mamaduka** [comment]
I think this line is the culprit for this issue:

https://github.com/WordPress/gutenberg/blob/29cd8eda717ec20a33ab4b95855652be758dd58d/packages/core-data/src/queried-data/selectors.js#L70-L72

This check will abort the loop and return `null` when we have itemId (from includes) but not the actual item in the state.

The fix seems easy, but I want to do more tests before creating PR to avoid regressions.

**Comment by Mamaduka** [comment]
The PR is ready for review #34034.

**Comment by studionenontwerp** [comment]
Also wp.data.select( 'core' ).getMediaItems( {include: ids } ) returns NULL if one of the ids does not exist any more.

**Comment by Mamaduka** [comment]
Hi, @studionenontwerp

This issue should be fixed in the latest Gutenberg plugin and will ship with WP 5.9.

P.S. `wp.data.select( 'core' ).getMediaItems( {include: ids } )` might return `null` on first invocation, if data isn't in state. Calling it second time will return results. This is automatically handled by `useSelect` hook.
