### ISSUE TITLE
Navigation Screen: Show a persistent inspector sidebar

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28434]
Currently, the Navigation screen has a toolbar button that toggles the display of the block inspector, but within a popover:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/191598/105550722-b8012300-5ccf-11eb-8395-3e541d4ca985.png">

Its a little clumsy.

Instead, I think it might be better to just always show the sidebar:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/191598/105550611-9ef87200-5ccf-11eb-89fd-cb2be424d090.png">

**Comment by talldan** [comment]
This was tackled in #28675, so closing.
