### ISSUE TITLE
Image resizing vs image size in inspector is not intuitive

### ISSUE THREAD

**Issue by ChemicalSailor** [WordPress/gutenberg#2843]
I can fluidly resize the image in an image block with dragging. Great. So what is the 'Size' dropdown in the sidebar/inspector for. Turns out it's more like image quality (but not quite in reality). Is it worth labelling it as such?

Ideally automatically selecting the best image size based on the dimensions it's been dragged to? Or use <picture> and <srcset> to help out?

**Comment by mtias** [comment]
I agree this is potentially confusing, and comes from the way WP has handled images historically. There's going to be a bigger focus on media flows in the following year, but looping @joemcgill in case there are things we'd want to avoid from the get go, or at leats make more "advanced" so regular (new?) users are not exposed to the complexities unnecessarily.

**Comment by ChemicalSailor** [comment]
Even knowing the background behind the dropdown it's confusing. I was at least expecting the image displayed in the editor to dynamically resize to a thumbnail if I selected that from the dropdown, but it just loads the thumbnail size which gets stretched to the current image dimensions, i.e. a perceived lower quality. It will be even more confusing for users with limited knowledge of how WordPress handles images behind the scenes.

**Comment by joemcgill** [comment]
I agree that this dropdown is confusing it its current form, and mainly unnecessary. See this related discussion in [#1727](https://github.com/WordPress/gutenberg/issues/1727#issuecomment-318742544).

**Comment by mellis32** [comment]
Without a 'custom' option in the in Gutenberg image scaling dropdown, the tool is useless and frustrating.

**Comment by jasmussen** [comment]
See also #4914

**Comment by jasmussen** [comment]
Closing as fixed by the image dimension inspector in 2.4! 🎉
