### ISSUE TITLE
Navigation Screen: Remove List View and display vertical Navigation variant

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28435]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/191598/105550988-1a5a2380-5cd0-11eb-8b38-7ad8a09c237a.png">

The current Navigation screen shows a horizontal Navigation block alongside the List View. Essentially, this displays the same things twice, and the only discernible difference is that one is a horizontal list and the other is a vertical list.

I think it might make more sense to remove the List View (maybe bringing it back as a popover or optional sidebar) and default to showing the Navigation block's vertical variant.

**Comment by MarvelMoe** [comment]
I agree that it should be an optional view ... if you have a few menu items it might not be needed. But it comes in handy when you have a large amount of sub menu items and want them expanded by default. See screenshot for example:
<img width="1187" alt="Screen Shot 2021-01-24 at 9 31 39 PM" src="https://user-images.githubusercontent.com/16159545/105665355-b67c5a00-5e8b-11eb-8212-460b24b80763.png">

**Comment by talldan** [comment]
This was done in #28675
