### ISSUE TITLE
`update-api-docs.js` doesn't support union types with string literals

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#28443]
## Description

Adding a type like `{('foo' | 'bar')}` to a type in jsdoc results in `(||)` in the generated doc. It should be supported by jsdoc, see [#](https://github.com/jsdoc/jsdoc/issues/629#issuecomment-58766768).

## Step-by-step reproduction instructions

To make things easier, I'll just take an existing jsdoc. Let's take [this](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/store/defaults.js#L14) one, then:

1. Add a new `@property` in a new line, like so: `@property {(''|'foo'|'bar'|undefined)} foo some description`;
2. Force the generation of the doc in the respective REaDME for the package by running `node ./bin/api-docs/update-api-docs.js` from GB's root dir;
3. Run `git diff` and you'll see the generated line in the README looks like: ` _foo_ (|||undefined): some description`.

## Expected behavior

I'd expect the API doc generator tool to generate something like: `(''|'foo'|'bar'|undefined)`.

## WordPress information
- Gutenberg version: e4eb4be3a9

**Comment by talldan** [comment]
There's a dicussion issue here -  https://github.com/WordPress/gutenberg/issues/22062. Seems related so thought I'd link it.

**Comment by kathrynwp** [comment]
@talldan looks like there hasn't been any movement on this in a while, let me know if you think it should be left open or not. Thanks!

**Comment by talldan** [comment]
Seems to no longer be an issue. I found an example here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/README.md#deletealltemplates
