### ISSUE TITLE
Block toolbar inconsistencies

### ISSUE THREAD

**Issue by ChemicalSailor** [WordPress/gutenberg#2844]
It seems from playing around that as blocks have developed independently the toolbar decoration for each has gone it's own way somewhat, and for me (not having tested Gutenberg for a while) it's uncomfortable. I'm particularly thinking about which controls are available where in each toolbar. For instance, no alignment buttons on a heading block, but they do exist on a paragraph. I'm finding that the controls available are constantly changing so you can never be sure where to find something.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1519320251000560)._

**Comment by karmatosed** [comment]
The toolbar has been iterated a lot recently, that in mind closing this.

**Comment by mtias** [comment]
Also related #3785.
