### ISSUE TITLE
Link description support in Navigation Link block is needed

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#28446]
## What problem does this address?
In the Navigation Link block, there is a field for "Description" in the Link Settings. This was likely added to reflect the description field in the Menus link settings in non-FSE WordPress. Unfortunately, the current Description setting (attribute) does nothing, and there are no filters available in the render function of the block that would allow developers to add support for descriptions. So while the help text indicates that some themes might support descriptions, there does not appear to be a way (currently) for themes to actually support descriptions 😉

![image](https://user-images.githubusercontent.com/4832319/105607419-9a35cb80-5d6c-11eb-8ac4-ea751bd760f9.png)

## What is your proposed solution?
There are a couple solutions that I am happy to explore, but would like feedback from the community on the best path moving forward. 

### Option 1

In core themes, like Twenty Twenty One, link descriptions are not supported, but since the link output is filterable, developers can add support for descriptions as needed. Something as simple as the following would do the trick. 

```
function prefix_nav_descriptions( $item_output, $item, $depth, $args ) {
    if ( ! empty( $item->description ) ) {
        $item_output = str_replace( $args->link_after . '</a>', $args->link_after . '</a><p class="menu-link_description">' . $item->description . '</p>', $item_output );
    }

    return $item_output;
}
add_filter( 'walker_nav_menu_start_el', 'prefix_nav_descriptions', 10, 4 );
```

The simplest approach would be to add similar filters to the navigation-link → index.php file. We could also provide a filter for the submenu icon so it could easily be swapped out. The current implementation is a bit of a headache if you want a different icon.

The problem with this approach is that all the modifications that are made via filters would not be available in the Site/Block Editor. So, while this would be the quickest solution, it is probably not ideal in the long run. 

### Option 2

An alternative approach would be to just make descriptions natively supported in the block. This would take more thought and design, but one implementation could looks something like this. Enabling link descriptions could also a setting in the theme.json file that theme developers could disable as needed. 

![image](https://user-images.githubusercontent.com/4832319/105608016-72943280-5d6f-11eb-963c-b7349f368a42.png)

The link description could also be its own block, but that might start getting too convoluted. 

Let me know what everyone thinks, thanks!

**Comment by carolinan** [comment]
Hi
I tihnk it would make more sence to do it the other way, 



Twenty twenty/

**Comment by ndiego** [comment]
Yeah that makes sense. I assume then we would need an additional filter(s) in the edit.js file for the block so the descriptions also appear in the editor, if the theme supports it. This would also open the doorway to adding additional content like icons to navigation links...

**Comment by paaljoachim** [comment]
@aristath Ari has made a PR here: https://github.com/WordPress/gutenberg/pull/39808
I am adding this as a comment as anyone who adds a comment to an issue will not get an alert when a PR is created.
I assume that Carolina @carolinan would like to test out the PR.

**Comment by paaljoachim** [comment]
I went ahead and added a mockup based on first clicking a toggle to display the description. Then seeing the description field and the additional toggle below. https://github.com/WordPress/gutenberg/pull/39808#issuecomment-1085714019
Let me know of adjustments that should be done.
