### ISSUE TITLE
Adjust right margins for buttons that are set at 25%, 50%, and 75% widths

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#28468]
When a user combines button blocks of varying preset widths (25%, 50%, 75%), they will never actually take up 100% of the available space. There's always an extra margin on the right side:

![Screen Shot 2021-01-25 at 12 01 40 PM](https://user-images.githubusercontent.com/1202812/105738524-1bc06180-5f05-11eb-9442-6afebb0a4ff0.png)

This may get pretty unweildy, but we should work out a way to ensure that various combinations of these blocks end up taking up the full 100% width when placed together.

Related: https://github.com/WordPress/gutenberg/pull/28467

**Comment by carolinan** [comment]
When the buttons block is centered, and you add one 75% button followed by 50% and 25%, it is easy to see that the right margin makes the positioning uneven.

**Comment by laras126** [comment]
This was tested and verified in the #core-css Slack bug scrub! One idea - what about using the `gap` property with a feature query? `gap` is not supported in IE11 or Safari, but perhaps it would be okay to use a progressive enhancement approach for this?

More [about `gap` here](https://developer.mozilla.org/en-US/docs/Web/CSS/gap). One thing to be aware of [is partial support which breaks the feature query](https://notlaura.com/beware-the-gap-property/) in Chromium, but I haven't verified if this is an issue (I encountered it over a year ago).

**Comment by kjellr** [comment]
Thanks for the recommendation, @laras126! I gave that a try in #29165. I left the existing implementation there as a fallback, but didn't encounter any issues in either Safari or Chrome — they seem to see and use the `column-gap` alternative just fine. 👍
