### ISSUE TITLE
Image block: Toolbars not present when dragged from columns or refactored gallery block

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#28474]
## Description

If an image is dragged out of a columns block the block toolbar does not display the first time the block is selected. If block is deselect and reselected it does appear.

A react warning is thrown on the first selection:

```
react_devtools_backend.js:2430 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

The source of this error is the state update at https://github.com/WordPress/gutenberg/blob/master/packages/components/src/tooltip/index.js#L115

## Step-by-step reproduction instructions
1. Add a columns block and add an image block within it
2. Drag the image out of the columns and drop somewhere else on the page
3. Select the Image - no block toolbar appears
4. Deselect and select again and toolbar appears

## Expected behaviour
Toolbar should appear on first block selection

## Actual behaviour
Toolbar only appears after a deselection and reselection

## Screenshots or screen recording (optional)
![tooltip-error](https://user-images.githubusercontent.com/3629020/105762285-1290cc80-5fb9-11eb-8ca3-420888538aab.gif)

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by frontdevde** [comment]
Just noting that I'm seeing the React state update error as well for both the Gallery block as well as the Media & Text block upon insertion in the editor.

**Comment by glendaviesnz** [comment]
I couldn't replicate this on 13.1 on WP 5.9 so closing.
