### ISSUE TITLE
Fill component throws state update warning

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#28478]
## Description
In some circumstances the bubbles-virtually fill throws a ` Can't perform a React state update on an unmounted component.` warning at https://github.com/WordPress/gutenberg/blob/master/packages/components/src/slot-fill/bubbles-virtually/fill.js#L13. 

This warning can be seen when dragging an image out of the refactored [gallery PR](https://github.com/WordPress/gutenberg/pull/25940).

## Step-by-step reproduction instructions
1. Check out the [gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940)
2. Add a Gallery and add images
3. Drag and image from the gallery and drop somewhere else on page
4. Notice state update warning in the console

## Expected behaviour
No react state update warnings

## Actual behaviour
State update warning show

## Screenshots or screen recording (optional)

![fill-error](https://user-images.githubusercontent.com/3629020/105771348-4c67d000-5fc5-11eb-9515-abc97308655e.gif)

**Comment by glendaviesnz** [comment]
@diegohaz do you have any thoughts on how to prevent this issue? I struggled to see an easy way to check if the component was still mounted before running the setState in Fill.

**Comment by senadir** [comment]
We're also seeing this issue on our SlotFill usage.

**Comment by nerrad** [comment]
@glendaviesnz #30667 just got merged that should fix this. Do you want to try it and confirm?

**Comment by glendaviesnz** [comment]
Thanks for the ping @nerrad. This appears to be fixed by #30667, no longer happens after rebasing the gallery refactor PR.
