### ISSUE TITLE
HTML Block: Do not auto-insert unwanted paragraph tags.

### ISSUE THREAD

**Issue by trev-dev** [WordPress/gutenberg#28473]
## Description

Paragraph tags are being added to HTML blocks.
## Step-by-step reproduction instructions

1. Add a new HTML Block
2. Paste HTML code, or write HTML Code
3. Save your page and/or preview it
4. Observe all the paragraph tags you didn't explicitly type.
## Expected behaviour

In an HTML block I expect to see paragraphs only where I specify them.
## Actual behaviour

WordPress pollutes the HTML with paragraph tags
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; I'm unable to reproduce this; could you share a code snippet of the block as well as what versions of Gutenberg (the plugin, if you're using) as well as the version of WordPress?

**Comment by trev-dev** [comment]
I made some bad assumptions when I posted this issue, sorry! The "page" is a custom post type for a pop-up creator in WordPress.

After receiving your reply, I tested my HTML in a normal page type and there were no resulting implicit paragraph tags.

Thanks for looking into it @skorasaurus
