### ISSUE TITLE
As plugin developer, I would like a clear process to update post content in JS

### ISSUE THREAD

**Issue by Malaiac** [WordPress/gutenberg#28488]
Right now we have :
`wp.data.dispatch( 'core/editor' ).editPost( { title: new_title} )` to update post title
`wp.data.dispatch( 'core/editor' ).editPost( { excerpt: new_excerpt } )` to update post_excerpt
but no clear way to update post_content

The topic is not clear on the general WP support forum ( https://wordpress.org/support/topic/getting-and-modifying-gutenberg-post-content-with-javascript/ )

Is there a simple way to update the whole post content in Gutenberg ?
If not, is there an agnostic way to insert new blocks (some of them being paragraphs, others not)

Solutions: 
`wp.data.dispatch( 'core/editor' ).editPost( { post_content: new_content } )` would be great

PS : editPost is from https://developer.wordpress.org/block-editor/packages/packages-edit-post/

**Comment by Soean** [comment]
You can reset the post and insert only strings.
```JS
wp.data.dispatch( 'core/editor' ).resetBlocks( wp.blocks.parse( 'My content' ) );
```

You can create blocks and inset them after the content.
```JS
const newBlock = wp.blocks.createBlock( "core/paragraph", {
    content: 'This is the content',
});
wp.data.dispatch( "core/editor" ).insertBlocks( newBlock );
```

**Comment by Malaiac** [comment]
`wp.data.dispatch( 'core/editor' ).resetBlocks( wp.blocks.parse( 'My content' ) );`
That was brilliant !
Please keep this topic publicly available for the next one who's gonna lose hairs on the same problem
