### ISSUE TITLE
Why does @WordPress/components point to built out react components?

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#28493]
Most of the WordPress React Components seem to use things like forwardRef(<component_name>), and props completion in most editors doesn't currently work for React component with HOCs 

```import { SelectControl } from '@wordpress/components';```

Usually editors are smart and shows hints of what that component expects. Unfortunately because the components are all using HOC it does not work.

<img width="655" alt="Screen Shot 2021-01-26 at 9 59 53 AM" src="https://user-images.githubusercontent.com/11615474/105861958-4241d380-5fbd-11eb-9a8d-730047e79b76.png">

## What is your proposed solution?

Change them all to use React Custom hooks? 

```import { SelectControl } from '@wordpress/components/src/select-control';```

<img width="772" alt="Screen Shot 2021-01-26 at 10 07 46 AM" src="https://user-images.githubusercontent.com/11615474/105862936-5afeb900-5fbe-11eb-8f6d-919e69ae2807.png">

**Comment by talldan** [comment]
I don't think the props inference system that's described can be made to work reliably. Some HOCs like `forwardRef` are also still necessary, as far as I know there isn't a hooks alternative. Components can also do clever things with props like destructure them in different parts of the component body, or pass them straight on to children.

There are already efforts to replace class components and HOCs (https://github.com/WordPress/gutenberg/issues/22890), so I think that covers your proposal.

Better still is a focus on documentation, which most editors can also use for autocompletion and type hinting/validation. That's covered by https://github.com/WordPress/gutenberg/issues/18838.
