### ISSUE TITLE
Extended settings visible when settings are hidden

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2849]
When the normal settings are hidden, extended settings remain visible.

**Comment by DevinWalker** [comment]
I'm attempting to contribute and resolve this issue but with a lack of screenshot or further description it's difficult for me to understand the exact problem needing to be resolved.

**Comment by DevinWalker** [comment]
After further examination, I see the issue that is described in this issue.

**Comment by gziolo** [comment]
@iseulde or @DevinWalker can you provide a screenshot? It will help reviewing the fix :)

**Comment by youknowriad** [comment]
> When the normal settings are hidden, extended settings remain visible.

Do we really need those two panels to be tied together. My personal opinion would be no but curious why do you think they should be?

**Comment by iseulde** [comment]
I don't think the _have_ to be tied together, but on the other hand, I also don't want to see extended settings when I hide "normal" settings... I would hid normal settings to have a clear screen for writing, but then there's still this box on the bottom of the screen in my way.

**Comment by aduth** [comment]
I'm inclined to agree with @youknowriad that these are two separate panels and closing one shouldn't necessarily close the other.

**Comment by iseulde** [comment]
Okay, what the best way to hide this panel then? @jasmussen Any ideas? 😊

**Comment by DevinWalker** [comment]
My first preference would be to have the Extended Settings tied to the normal settings' show/hide button. Another option would be to have another toggle within the settings panel like so:

![2017-10-12_14-26-49](https://user-images.githubusercontent.com/1571635/31520185-e4a6f8fc-af59-11e7-9b5c-9be258a78dda.png)

However, this is harder to find and would require two clicks to access the panel and maybe even three clicks if the panel is not toggled open when displayed.

**Comment by jasmussen** [comment]
I like @DevinWalker's 2nd mockup. 

I know the metabox project is ongoing, but the side drawer and the bottom drawer are all in the same category of settings, and so they should both be toggled by the same. This seems at the very least worth trying, so we can decide if we dig this. If we don't, there are many other things we can explore.

Additionally, if there are no metaboxes in the Extended Settings drawer, we should probably not show that panel at all.

**Comment by hedgefield** [comment]
To clarify, that's the one with the text below the metaboxes in the sidebar?

This issue gets to something I also explored with a distraction-free toggle that hides all the toolbars at once (#2876). We already have a toggle for the sidebar and one for the menu, adding a third step to clear the clutter seems like overkill. At the very least including the extended settings in the settings toggle seems like the best idea.

**Comment by jasmussen** [comment]
> To clarify, that's the one with the text below the metaboxes in the sidebar?

No, it's this panel at the bottom:

![screen shot 2017-10-18 at 13 25 54](https://user-images.githubusercontent.com/1204802/31716394-db480474-b407-11e7-8e13-eafe842ed688.png)

Re: distraction free, I personally feel like the ability to toggle off the sidebar, and collapse the navigation menu on the left, counts as the most discoverable type of distraction-free feature. Mostly, though, I feel like if an interface needs a distraction-free toggle (that's labelled as such), it indicates more fundamental problems with the interface. That goes for Gutenberg too, so I'd rather we fix those issues that makes us want a distraction free toggle ;)

However Tammie recently posted a new idea here: https://github.com/WordPress/gutenberg/issues/2460#issuecomment-336915515 — that is, making a distraction free extension that goes further.

**Comment by hedgefield** [comment]
@jasmussen ah you changed your reply, it said option 2 but I see (and expected) you meant option 1, then we are in agreement :)

**Comment by jasmussen** [comment]
Haha I do apologize, I must've been tired when I wrote the previous version.

Glad to hear agreement. I think I can pr this one pretty quick
