### ISSUE TITLE
Heading Block: Discrepancy in Text Colors via Editor and Live Site

### ISSUE THREAD

**Issue by allykmyta** [WordPress/gutenberg#28507]
## Description
Heading Block in the Editor does not show the correct text hyperlink color as what is assigned in the Customizer. When a background color is applied to the heading block text, the hyperlink styling applied in the Customizer is removed. 

## Step-by-step reproduction instructions

1. Go to WordPress.com > My Sites > Design > Themes > select Exford (or any theme that provides custom colors via customizer) > Activate theme
2. Go to Customizer and set custom colors for the link and secondary color and save changes: ![Screenshot](https://d.pr/i/gL3W7k/GlO1tdDGEw+)
Original screenshot link: https://d.pr/i/gL3W7k/GlO1tdDGEw
3. Navigate to the home page editor, add a heading block, link the heading block
4. Apply text color to heading block linked text and publish

## Expected behaviour
It's expected that even though the Heading Block text color won't be applied to the hyperlinked text, it should display the colors assigned in the customizer for consistency in the editing process.

Also expected that when a background color is applied to the heading block that the hyperlink text color should be applied on the live site.

![Screenshot](https://d.pr/i/2K046g/6pDRTifWAU+)
Original screenshot link: https://d.pr/i/2K046g/6pDRTifWAU

## Actual behaviour

No color is applied to the hyperlinked text in the editor, so must preview to ensure that the correct link color and hover color are applied.

Adding a background color to the hyperlinked text in the Header Block overwrites the custom style added through Customizer. No hover cover is provided even though it is set correctly in the Customizer.

## Screenshots or screen recording (optional)
https://d.pr/v/4UM2yp/tetzjn2QvA

## WordPress information

- Are you using a default theme (e.g. Twenty Twenty-One) Yes, Exford and tested on Alves.

## Device information
- Device: Desktop
- Operating system: Mac Version 11.1
- Browser: Chrome Version 87.0.4280.141

**Comment by talldan** [comment]
@allykmyta Please could you fill out the 'Step-by-step reproduction instructions' part of the issue description.

**Comment by allykmyta** [comment]
@talldan Looks like I had it commented it out - sorry about that! reproduction instructions updated!

**Comment by annezazu** [comment]
@allykmyta this appears to be a WordPress.com theme specific issue. Can you please report with them? I'm going to close this out for now :)
