### ISSUE TITLE
Site Editor: TT1 theme provided templates don't load content

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#28504]
### Description
For the TT1-blocks theme, the page template and single post template don't load properly in the site editor

### Steps to Reproduce
1. Select the tt1-blocks theme to enable the site editor
2. Navigate to the site editor
3. Open the navigation sidebar and select _Templates > Pages > Page_ 
4. Verify that the template doesn't load properly
5. Open the navigation sidebar and select _Templates > Posts > Single_
6. Verify that the template content doesn't load properly

### Screenshots
<img width="644" alt="Screen Shot 2021-01-26 at 11 00 27 AM" src="https://user-images.githubusercontent.com/5414230/105894317-ff85f880-5fc8-11eb-8ae7-803ecda1cb36.png">
<img width="643" alt="Screen Shot 2021-01-26 at 11 00 46 AM" src="https://user-images.githubusercontent.com/5414230/105894322-00b72580-5fc9-11eb-8ecb-3c1234f01a50.png">

**Comment by david-szabo97** [comment]
This doesn't seem like a bug. In the site editor we are using placeholders for all the context based blocks. See how post content and post title block behaves in this case. Most of the other blocks don't have a placeholder state yet, like post comments.

**Comment by jeyip** [comment]
> This doesn't seem like a bug. In the site editor we are using placeholders for all the context based blocks. See how post content and post title block behaves in this case. Most of the other blocks don't have a placeholder state yet, like post comments.

Oh interesting. I still think this is still a bug, in the sense that users wouldn't expect this on a fresh instance of the Full Site Editor. After some searching, placeholder states are, however, already on our radar (see https://github.com/WordPress/gutenberg/issues/26856). Thanks for the info @david-szabo97! I'll close this issue out.
