### ISSUE TITLE
Media modal tests failing due to non-refreshing media list

### ISSUE THREAD

**Issue by leewillis77** [WordPress/gutenberg#28500]
## Description
A number of the e2e tests are failing on master due to an issue where the media list doesn't refresh to show the most recently updated media item. See for example:
- `packages/e2e-tests/specs/editor/plugins/image-size.test.js`
- `packages/e2e-tests/specs/editor/various/adding-inline-tokens.test.js`
- `packages/e2e-tests/specs/editor/various/adding-inline-tokens.test.js`

## Step-by-step reproduction instructions
- Temporarily add `jest.setTimeout(500000);` to one of the affected scripts (e.g. image-size.test.js)
- Run the test script interactively, e.g. 
  - `wp-scripts test-e2e -- --puppeteer-interactive packages/e2e-tests/specs/editor/plugins/image-size.test.js`
- Note that the test hangs waiting for the uploaded media to appear in the media list

As far as I can tell, this doesn't actually affect the end-user experience, it seems to be something to do with how the e2e framework is interacting with that dialog. 

## Expected behaviour
Media uploading during tests triggers a refresh of the media list, and as a result, e2e "admin 2" tests pass. 

## Actual behaviour
Media uploading during tests does not trigger a refresh of the media list, and as a result tests fail as they cannot detect the uploaded media. 

## Screenshots or screen recording (optional)
Example screenshot from a failed run:
![Screenshot 2021-01-26 at 17 21 38](https://user-images.githubusercontent.com/1097338/105881476-7983a500-5ffc-11eb-9bf0-b307df843c37.png)

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: git SHA c31555d4cec541db929ee5f63b900c6577513272, but the bug exists prior to this.
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

**Comment by talldan** [comment]
Thanks for reporting this @leewillis77. From what I can tell it's related to the following core change:
https://core.trac.wordpress.org/ticket/50025

I've alerted those that worked on the ticket and hopefully there'll be a fix in core soon.
