### ISSUE TITLE
Drag'n'drop image to medialibrary add image also to content

### ISSUE THREAD

**Issue by vjik** [WordPress/gutenberg#28512]
## Description

I'm install clear WP and add Gutenberg plugin.
On page:
- add image block
- click on "Media library" button into image block
- drag'n'drop image to library and click "Select"

In content add image to image block and add yet one image bottom image block.

This bug not only with image block, but in any blocks, when use media library + drag'n'drop.

If I don't use plugin - then all it's OK.

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system:  Win10
- Browser: Chrome 87.0

**Comment by gwwar** [comment]
Hi @vjik thanks for the report. Do you mind adding a few screenshots of each step? I'm not sure I understand the issue.

**Comment by vjik** [comment]
Image block:
![image](https://user-images.githubusercontent.com/525501/106905997-c9a1ec00-670d-11eb-913a-6ee6ecad76b4.png)

Open medialibrary and drag'n'drop image to medialibrary and select image.

Result:
![image](https://user-images.githubusercontent.com/525501/106906090-e3dbca00-670d-11eb-8696-0ec57778ebcc.png)

**Comment by gwwar** [comment]
😄 I think I found a different bug while testing this: https://github.com/WordPress/gutenberg/issues/28746

@vjik maybe a video will help? I still don't quite understand the behavior you're seeing. A video of steps similar to https://github.com/WordPress/gutenberg/issues/28746 would be super helpful.

**Comment by paaljoachim** [comment]
This issue seems associated:
https://github.com/WordPress/gutenberg/issues/25805

**Comment by paaljoachim** [comment]
This issue seems associated:
https://github.com/WordPress/gutenberg/issues/25805

**Comment by vjik** [comment]
https://user-images.githubusercontent.com/525501/107044917-fb7e8580-67d5-11eb-8a31-860c24c09af4.mp4

**Comment by paaljoachim** [comment]
Ahhh now I understand! Thank you @vjik 

I am repeating what you did and noticed the error again.
This is what I did.
Went to a published page such as Sample Page. 
Added the Image block.
Clicked to add an image from the Media Library.
Dragged an image into the media Library.
Selected and added it into the page.
Noticed 2 sets of images show up.

NB! Sometimes I get the error here: https://github.com/WordPress/gutenberg/issues/25805
Sometimes I see the error you mentioned.
Sometimes it works normally.

I believe this has to do with the error in 25805.

**Comment by paaljoachim** [comment]
Robert @noisysocks here is another error. I believe it is associated with https://github.com/WordPress/gutenberg/issues/25805
We also need to add this one to the WP 5.7 Must Haves Project Board.

**Comment by noisysocks** [comment]
Were you able to reproduce it?

**Comment by paaljoachim** [comment]
I was able to reproduce it but it varied. I have not been able to reliably reproduce the issue. Which means whomever is able to reliably reproduce the issue here needs to post the steps to do so.

I believe by fixing #25805 we will also be fixing this issue.
As they seem very much interrelated. The dev fixing 25805 also needs to be aware and consider this issue as well.

**Comment by ntsekouras** [comment]
Related: https://github.com/WordPress/gutenberg/issues/28935

**Comment by dgdb1** [comment]
Do you know any solution to this problem?

I use:
- Wordpress 5.7
- Gutenberg 10.1.1

The problem still exists.

**Comment by paaljoachim** [comment]
Hi @dgdb1 Damian

I tried the steps I outlined but at the moment I am not seeing the error. Using WordPress 5.7 and Gutenberg 10.1.1.
The merged PR https://github.com/WordPress/gutenberg/pull/29567 should fix the error. It will be included in Gutenberg 10.2 which will be released next week.
