### ISSUE TITLE
Image Block Caption Alignment

### ISSUE THREAD

**Issue by danielpwaldschmidt** [WordPress/gutenberg#28528]
I'm simply wondering if there's been any discussion to adding the ability to left, center, and right align the captions within the Image block?

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; this has been requested and discussed in issues https://github.com/WordPress/gutenberg/issues/12997 and https://github.com/WordPress/gutenberg/issues/19975 where you can follow its progress.
