### ISSUE TITLE
Improve parent/child selection behavior in the Quote block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28522]
The Quote block is about to receive nesting support (#25892). This benefits transformations, and solves basic issues like being able to have images inside a quote.

The nesting change also makes it slightly harder to select the parent block. This ticket suggests that we build a system that allows the quote block to always show its "select parent" button, even when an inner-block is selected. GIF showing how this could work:

![gif](https://user-images.githubusercontent.com/1204802/105990434-bdc98080-60a2-11eb-9fd0-e2c9c89c37d1.gif)

This behavior could benefit blocks where the parent and immediate child are highly tied together, such as Quote, Navigation, Social Links, perhaps even Gallery.

**Comment by mtias** [comment]
Thanks for sharing the gif. The blocks that would immediately benefit form this are Quote, Navigation, Buttons, Social Icons, and (soon) Gallery. It's not clear if other more generic nested blocks would benefit from it (Columns, Cover, Group). My initial impression is that they wouldn't.

To control the difference without introducing yet another prop to innerblocks I think we could look into whether explicit child blocks are allowed.

I like this ticket is focused on a single step. Later on we need to look at how "absorb toolbar" needs to expand to allow easier changes of a parents attributes, etc.
