### ISSUE TITLE
Plain quote style (indent)

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#28524]
There's been a few request in the past for the ability to block-indent text. This is generally used in quote heavy contexts (academic contexts, essays, etc). Traditionally the styling for these quotes has been just a margin on a paragraph. This is not great since it sacrifices semantics for visual styling.

What I think we can provide instead is a new block style for Quote called "Plain" that removes the default border and only indents the text while preserving the blockquote element.

![image](https://user-images.githubusercontent.com/548849/106001455-44d12580-60b0-11eb-972f-ec75e1a2de67.png)

Thoughts?

**Comment by aristath** [comment]
It makes perfect sense... Indenting text without the semantics of a quote is less than ideal. A "plain/indented" style for quotes would work nicely :+1:

**Comment by paaljoachim** [comment]
Here is another indent issue: 
No ability to indent
https://github.com/WordPress/gutenberg/issues/14554

Another thought as we are right now holding a design triage. Can we add a style to the Paragraph block?
Where indent would be a style to choose from.

**Comment by mtias** [comment]
@paaljoachim that's the thing we want to avoid, because the indent would carry no semantic meaning there and would degrade the document a bit.

**Comment by paaljoachim** [comment]
It was brought up during a [design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1612886825333800). Here are some comments:

@paaljoachim 
I would say that @matias suggestion above is a good one, and can be very helpful.
It would be a "simple" way to create a paragraph that needs to be indented. One just switches it over to a quote block and changes the style. One might expect to be able to indent in the paragraph block though. 

@draganescu  
I also think @matias’s suggestion makes perfect sense.

@hedgefield 
True, although it feels like a workaround. There was discussion before about not being able to indent in general I believe?

@paaljoachim  
Yes. It seemed tricky.  (Indent issue: https://github.com/WordPress/gutenberg/issues/14554 )

@hedgefield 
And that classic could etc
It'll probably take longer to fix the entire problem, but at least maybe connect those two issues so the bigger effort isn't ignored in case we do this quick fix

@kellychoffman 
it might be a step in the right direction, but i don’t think most people will look for quote when they want to indent.

**Comment by paaljoachim** [comment]
As we discussed this issue during a design triage. We agreed it was a good idea to get implemented.
As adding a style seems like a good simple approach that can be done fairly quickly.
Then at a later time figure out an even better way of handling this issue.

I removed the "Needs Design Feedback" label and added a "Needs Dev" label. I am also thinking it might be a good first issue.

**Comment by danyork** [comment]
Hi all! Just curious about the status of this - any estimate on when this might be available? I see there is pull request #29856 but that is now flagged as stale. I had a case today where we wanted to indent four paragraphs in a blog post and the regular blockquote was not appropriate. And, it turned out we haven't styled the Classic block appropriately so I couldn't use that workaround.

**Comment by mtias** [comment]
It's a simple patch that just needs a nudge along the way :)

**Comment by mkaz** [comment]
Closed in #29856
