### ISSUE TITLE
Query Block: Add alignment controls

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28532]
It could be useful to have alignment controls in the Query Block (or the nested Query Loop Block) for wide and full-width.

![image](https://user-images.githubusercontent.com/545779/106058080-60d7c580-60b6-11eb-8a2c-cbe71d46d170.png)

**Comment by ntsekouras** [comment]
Duplicate of: https://github.com/WordPress/gutenberg/issues/27589
