### ISSUE TITLE
Latest Posts block inside Group block not selectable

### ISSUE THREAD

**Issue by hazuremon** [WordPress/gutenberg#28536]
## Description

When Latest Posts block is within a Group block, Latest Posts block is not selectable and block settings will not display.

## Step-by-step reproduction instructions

1. Add a Group block
2. Add a Latest Posts block within the group block
3. Save Draft or Publish
4. Refresh page and click on Latest Posts block

## Expected behaviour

Latest Posts block to be selected with Block settings display

## Actual behaviour

Latest Posts block is not selected and cannot access block settings

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1413953/106074993-aa79dd80-60c1-11eb-8d61-2bda2746427d.mov

## WordPress information
- WordPress version: 5.6.0 
- Gutenberg version: 9.8.1 and up
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Tested on Twenty Twenty-One and with same results) 

## Device information
- Device: Desktop 
- Operating system: OSX 
- Browser: Chrome 88

**Comment by talldan** [comment]
Thanks for reporting this, @hazuremon.

**Comment by paaljoachim** [comment]
Hi @hazuremon Michael

I reported the same issue here: 
https://github.com/WordPress/gutenberg/issues/28417

It is being worked on here:
https://github.com/WordPress/gutenberg/pull/28445

I believe we can keep both issues open for now, as a fix should soon be added. 
Then we can close both issues.
