### ISSUE TITLE
Block code added to the HTML code block leaks into the frontend

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#28537]
## Description

_By "Block code/markup" I mean the markup / textual representation that Gutenberg uses internally to store the blocks in the editor, the one you can see/modify if you switch to the Code Editor._

Block code/markup is not supposed to be added to the HTML block, but if it is, it ends up leaking from it and is rendered in the frontend. 

## Step-by-step reproduction instructions

1. Start a new page or post;
2. Add any block to the editor, switch to the code editor, copy its markup;
3. Start a new post/page and add an HTML block to the editor;
4. Paste the code;
5. Publish and view the page -- you'll see the rendered contents from the block you pasted into the HTML block;
6. Go back to the editor and reload. The HTML block is now empty.
7. If you switch to the code editor now, it seems to "clean itself" and you'll see that there's only the markup for an empty HTML block (`<!-- wp:html /-->`). If you update the page, you'll see the blocks you pasted won't render anymore.

Interestingly enough, the leaked markup won't show if you switch to the code editor. If you try the same thing but from the code editor - by surrounding your block markup by `<!-- wp:html -->` and `<!-- wp:html /-->` and updating the post, you'll see that that it will clean itself from the markup you just added, and become a single/empty `<!-- wp:html /-->` block markup.

## Actual behavior

The block markup "leaks" into the page and is rendered in the frontend and when the HTML block is reloaded in the editor, the contents are not part of it anymore and are shown as empty.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/81248/106080611-0c940c00-60dd-11eb-90b8-5a8062eac342.mp4

## WordPress information
- WordPress version: 5.7-alpha-49963 (wp-env)
- Gutenberg version: HEAD (0d4e1fb1e)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 18.04
- Browser: Firefox 86.0b2 (64-bit)

**Comment by talldan** [comment]
> Block code/markup is not supposed to be added to the HTML block, but if it is, it ends up leaking from it and is rendered in the frontend.

@fullofcaffeine What do you mean by leaking? I initially thought this would mean that the delimiter comments are rendered, but that doesn't seem to be the case, just the HTML content. Really it feels like the block should just render anything that's valid HTML, but handling block markup might be tricky.

> If you switch to the code editor now, it seems to "clean itself" and you'll see that there's only the markup for an empty HTML block (). If you update the page, you'll see the blocks you pasted won't render anymore.

I think what's happening is that when markup like this is present:
```
<!-- wp:html -->
<!-- wp:paragraph -->
<p>test</p>
<!-- /wp:paragraph -->
<!-- /wp:html -->
```
The wp:paragraph comment is parsed as an inner block. Because the HTML block doesn't support inner blocks the content is thrown away and so disappears when switching from the code editor to the visual editor. The same doesn't happen when purely editing visually because there isn't a parse of the content.

> Also: At second 58, you'll see that trying to type the markup for the HTML block and updating the post results in it being cleared out to a single markup for an empty HTML block, for some reason. Not sure if it could be considered normal, related, or a different bug.

In the screencast, when you try to manually add an opening wp:html delimiter comment, there's no matching closing comment. The other wp:html comment is self-closing. If there's a matching closing tag the other content is retained.

**Comment by fullofcaffeine** [comment]
> @fullofcaffeine What do you mean by leaking? I initially thought this would mean that the delimiter comments are rendered, but that doesn't seem to be the case, just the HTML content. Really it feels like the block should just render anything that's valid HTML, but handling block markup might be tricky.

Yeah, this is perhaps a bit tricky to explain, maybe it wasn't the best term. I tried to explain from an end-user's perspective: The block code ended up disappearing from the HTML block, but it "leaks" into the frontend. 

I understand that valid HTML code should be rendered. Maybe this is not a bug but more of a misunderstanding / UX issue, i.e the end-user assumed they could paste block code into it. However, it just ignored all the actual block code and ended up rendering the underlying HTML. Still, the fact it doesn't load the code as part of its contents upon loading the editor is quite confusing.

**Comment by jordesign** [comment]
Just looping back through some older issues - it's unclear to me if this is still an issue. Do you still see it present @fullofcaffeine ?

**Comment by jordesign** [comment]
With no further comments/activity on this issue I'll close it for now. We can always revisit/open if needed.
