### ISSUE TITLE
Pinned items should remember their place, at least the Settings sidebar should

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28546]
#28526 fixed an issue where plugins that add a sidebar and pin items to the toolbar would show up on mobile. That was a regression from a past behavior where it was decided that pinned items are only accessible from the More menu on mobile (see also #14457).

While the issue is fixed, the solution isn't solid. If you unpin a plugin sidebar, then pin it again, it's now the first pinned item, which is problematic as the Settings cog should always be the first icon:

![106005578-a4c9cb00-60b4-11eb-98c6-bd731ce38582](https://user-images.githubusercontent.com/1204802/106115601-3b4bca00-6151-11eb-9221-52d23e29e22c.gif)

The fact that upon a page reload, the pinned item is back where it "should" be, suggests it's a bug.

There are some thoughts to ponder as far as solutions go:

- The cog could be moved out of the "pinned items" group, that would always make it first.
- However in https://github.com/WordPress/gutenberg/issues/27847 it's being explored how you can move from editing a post, to editing a template. When that shift happens, pinned items should fade out, and things such as the global styles panel could fade in. 

Both of those use cases need to be considered when finding a good solution.

**Comment by ridesirat** [comment]
Hi guys
sorry, I know it's not exactly related but you decide where it's best.
I think the order of this is RTL, so, shouldn't the "Preview + Publish + Cog" be always on the right?
It's a reflexive thing, go to the right to Publish, etc.
For the pin, there could be an icon (star?  :) for pinned items and a way to reorder them by user choice. That way, as the screen size changes, the preferred ones will always be visible until they all collapse to the pin icon.
When you press the icon, a drop down (Google style) with all of them appears. Or a right bar (Adobe style).
