### ISSUE TITLE
Buttons inside columns has no horizontal spacing in the editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28549]
## Description

When a buttons block with more than one button is placed inside a column, there is no horizontal spacing between the individual inner button blocks, _unless you justify the buttons block to the right._

When viewing the same combination of blocks on the front, there is spacing.

## Step-by-step reproduction instructions

1. Go to the editor and add a columns block.
2. Inside a column add a button block with two or more buttons.

3. Test the following with all 3 width options: default, wide and, full:
4. Justify the content to the left: See that there is no spacing between the buttons.
5. Save and view the front: See that there is spacing between the buttons.

6. In the editor, justify the content to the center: See that there is no spacing between the buttons.
7. Save and view the front: See that there is spacing between the buttons.

8. In the editor, justify the content to the right: See that there is spacing between the buttons.
9. Save and view the front: See that there is spacing between the buttons.

## Expected behaviour

I expect there to be spacing and I expect the front and editor to match.

## Actual behaviour

The front and editor only match if the buttons block is justified to the right. 
(I only tested on LTR)

## Screenshots or screen recording (optional)

Center justification, no spacing:
![button-inside-column](https://user-images.githubusercontent.com/7422055/106129888-faf44800-6160-11eb-967f-4b4d03ceca6a.png)

Front:
![button-inside-column-front](https://user-images.githubusercontent.com/7422055/106130294-75bd6300-6161-11eb-9f67-43f713ff3015.png)

Right, with spacing visible:

![button-inside-column-right](https://user-images.githubusercontent.com/7422055/106130100-44449780-6161-11eb-9a2b-83d0c5daf601.png)

## Code snippet (optional)

The following code is affecting the margins of the button block when they are inside the column:
```
.wp-block-columns .wp-block {
    max-width: none;
    margin-left: 0;
    margin-right: 0;
}


```
## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: _current master_
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested on Twenty Twenty-One version 1.1, and Twenty Twenty with the same result.

## Device information
- Device: Desktop, PC
- Operating system: Windows 10
- Browser: Chrome 88.0.4324.104

**Comment by thetwopct** [comment]
I'm also seeing this issue in WordPress 5.7. Also tried with Gutenberg 10.1.1 and the issue remains.

**Comment by carolinan** [comment]
Button blocks now have a column-gap style and this issue is solved. Tested with WordPress 5.8, with and without Gutenberg 11.2.1.
