### ISSUE TITLE
Image Block: add 'wp-caption-text' class in order to be backwards compatible with image captions inserted in Classic Block/Editor

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#28551]
This issue is a quick stub - with more details to be added

## Description
Currently image captions which are inserted in a Classic Block (or from the Classic Editor) include the class `wp-caption-text` which is used for styling by many themes. This results in inconsistent styling of image captions depending on how the image was added.

## Step-by-step reproduction instructions

1. Start a new page/post.
2. Insert an Image Block and select an image which has a caption applied.
3. Insert a Classic Block and insert an image which has a caption applied.

## Expected behaviour

I expect the captions for both images to display consistently.

## Actual behaviour

Depending on the theme's styling - there will be a discrepancy in the styling of the captions.

## Screenshots or screen recording (optional)

Example: https://lamontjordan.wordpress.com/testing-captions-in-the-sapor-theme/

<img width="776" alt="Screen Shot 2021-01-28 at 11 50 20 pm" src="https://user-images.githubusercontent.com/1842363/106141040-af26ba80-61c3-11eb-92bd-2525a32dd522.png">

-->

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested in default themes - their styling is non-specific enough that it works. But the code is still inconsistent.

## Device information
- Device: Desktop
- Operating system: Mac OSX
- Browser: Chrome 87.0

**Comment by scruffian** [comment]
We decided to fix this in the theme...
