### ISSUE TITLE
Block attributes do not save

### ISSUE THREAD

**Issue by jtrost** [WordPress/gutenberg#28566]
## Description
The code for the [Block attributes tutorial](https://developer.wordpress.org/block-editor/tutorials/create-block/attributes/) does not load block attributes after they have been saved.

## Code snippet 
````javascript
import {TextControl} from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';

import './style.scss';
import './editor.scss';

registerBlockType('landing-page/container', {
  apiVersion: 2,
  title: 'Landing Page',
  description: 'Landing Page content',
  category: 'landing-page',
  icon: 'smiley',
  supports: {html: false},
  edit: function({attributes, className, setAttributes}) {
    return (<div className={className}>
      <TextControl
        label={'Message'}
        value={attributes.message}
        onChange={(val) => setAttributes({message: val})}
      />
    </div>);
  },
  save: function({attributes, className}) {
    return(<div className={className}>{attributes.message}</div>);
  }
});
````

## Step-by-step reproduction instructions
1. Add the block to the editor, and enter a message, such as "Hello".
2. Save and reload the page
3. In place of the block is a message that says "This block contains unexpected or invalid content." You are given the option to convert the block's contents to html.
4. In the Javascript console you will see this error:
````javascript
Block validation: Block validation failed for `landing-page/container`
{
  "name": "landing-page/container",
  "icon": {
    "src": "smiley"
  },
  "keywords": [],
  "attributes": {
    "className": {
      "type": "string"
    }
  },
  "providesContext": {},
  "usesContext": [],
  "supports": {
    "html": false
  },
  "styles": [],
  "title": "Landing Page",
  "description": "Landing Page content",
  "apiVersion": 2,
  "category": "landing-page"
}
Content generated by `save` function:
<div></div>
Content retrieved from post body:
<div>Hello</div>
````

## Expected behaviour
The block will load with the content that was saved.

## Actual behaviour
The block does not load.

## WordPress information
- WordPress version: 5.6
- Gutenberg version: Does not appear in /wp-admin/site-health.php?tab=debug
- Are all plugins except Gutenberg deactivated? Yes (except for the plugin to add the block)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: OS X
- Browser: Firefox & Chrome

**Comment by talldan** [comment]
@jtrost It looks like you're missing this bit from the tutorial (your block has no attributes declared):

> Add this to the index.js file within the registerBlockType function. The attributes are at the same level as the title and description fields.
