### ISSUE TITLE
Can't import scss with img or svg - missing loader

### ISSUE THREAD

**Issue by GregoireSailland** [WordPress/gutenberg#28567]
## Description
Custom Block development
Error while importing SCSS

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. npm install slick-carousel
2. in scss file 
import "slick-carousel/slick/slick";
import "slick-carousel/slick/slick-theme";
//require("slick-carousel/slick/slick");
//require("slick-carousel/slick/slick-theme");
3. console error:
ERROR in ./node_modules/slick-carousel/slick/slick-theme.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\loader-runner\lib\LoaderRunner.js:205:4
    at C:\laragon\www\gutenberg\wp-content\plugins\un-block\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ ./src/blocks/slider/index.js 7:0-46
 @ ./src/index.js

## Expected behaviour
working out of the box

## Actual behaviour
Error in console

## Screenshots or screen recording (optional)
none, see Step-by-step reproduction instructions 3)

**Comment by talldan** [comment]
@GregoireSailland This issue is missing some context. Is it related to @wordpress/create-block or something else?

**Comment by GregoireSailland** [comment]
Yes it is related to the webpack config of the wordpress/create-block package.
I think some loaders are missing when importing other libraries with svg or img in scss/css
I am not an expert in webpack config so maybe I am wrong, but I failed 2 times in importing css from different libraries because of non supported content
It could be nice if the package wordpress/create-block supports it by default.
I had also trouble adding secondary js script compilation to the jetpack config
I found the documentation poor about it
Here is my block attempt:
https://github.com/nextweb-ch/slideshow
You can see in webpack.config.js How Iadded a secondary js script for front end
You can also find my issue in https://github.com/nextweb-ch/slideshow/blob/main/src/style.scss
to import an external slider css library
//@import 'slick-carousel/slick/slick-theme';
I also tried with owl carousel package

**Comment by gziolo** [comment]
> I think some loaders are missing when importing other libraries with svg or img in scss/css

Support for images and fonts were added in the recent major version of `@wordpress/scripts` - v13. I see you are on an older version:

https://github.com/nextweb-ch/slideshow/blob/ba8634d518f9087b62f044bc2cb9917c9ccf50ba/package.json#L23

Can you check if upgrading this package solves this issue?

**Comment by GregoireSailland** [comment]
Yes it is solved, many thanks for the help!
