### ISSUE TITLE
FocalPointPicker unit controls are to small for Swedish translations

### ISSUE THREAD

**Issue by stefanfisk** [WordPress/gutenberg#28582]
## Description

`<FocalPointPicker>` hardcodes the width of `<UnitControl>` to `100px`, which is not enough to fit the Swedish translations of `left` and `top` (`vänster` and `toppen`).

https://github.com/WordPress/gutenberg/blob/502f79a6e0aa65c68562efade58aadc7ab334d4b/packages/components/src/focal-point-picker/styles/focal-point-picker-style.js#L55

## Step-by-step reproduction instructions

Switch to Swedish and try adjusting the focal point of a cover block.

## Expected behaviour

The strings should fit.

## Actual behaviour

The labels are not wide enough to fit the strings.

## Screenshots or screen recording

![image](https://user-images.githubusercontent.com/827773/106269032-390a6e00-622c-11eb-8e83-e055fb07a25f.png)

## WordPress information

- WordPress version: 5.6
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: Desktop
- Operating system: macOS 11.1
- Browser: Chrome  88.0.4324.96

**Comment by ockham** [comment]
cc/ @ItsJonQ :wave: :smile:

**Comment by paaljoachim** [comment]
I believe is only needs some CSS adjustments of the space where we see the percentage numbers.

**Comment by ItsJonQ** [comment]
Apologies! I forgot to follow up on this one. We had a similar issue with the FontSizePicker.
Will see what I can do.

I'm just leave a note saying that I believe this is a symptom of a larger design issue in that we're missing a standardized way to render UI - specifically using grids, horizontal stacking elements, and/or responsive containers.

I don't have an immediate solution. However, the recent inclusion of various [layout primitives for the new Component System](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Aclosed+hstack) may help us here.

**Comment by lukecarbis** [comment]
This appears to be fixed in Gutenberg 10.0.0. (Tested using the RC1 build)

<img width="273" alt="Screen Shot 2021-02-12 at 7 50 16 am" src="https://user-images.githubusercontent.com/1097667/107703152-015cf500-6d07-11eb-87ad-c302b962d585.png">

**Comment by ItsJonQ** [comment]
Thanks @lukecarbis !!

The underlying `Flex` layout component was recently updated:
https://github.com/WordPress/gutenberg/pull/28609.

It's better at adapting to inner content.
It should help for now 👍 

P.S. Control labels like that one will be improved some more with this update:
https://github.com/WordPress/gutenberg/pull/28568

**Comment by paaljoachim** [comment]
Tested with WordPress 5.7 RC1
Gutenberg 10.0.2
Twenty Twenty One.


https://user-images.githubusercontent.com/5323259/109217993-d9fe3180-77b6-11eb-9a14-8978d78b1c96.mp4


Issue has been fixed and I will close the issue.
