### ISSUE TITLE
Add the "Add Page/Post" buttons to full screen editor

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#28597]
## What problem does this address?
Since the editor now opens full screen by default we lose the "Add Post" / "Add Page" buttons from the header. This means once a page has been published we have to click the WordPress logo (which in itself isn't obvious to get back to the dashboard), and then click the add buttons from the top of the page/posts list or from the left menu.

## What is your proposed solution?
Include the buttons to add a new post/page when editor is full screen.

**Comment by talldan** [comment]
Thanks for creating the issue. This was previously reported in #22178, so I'll close this as a duplicate.
