### ISSUE TITLE
FontSizePicker is not responsive with longer labels

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#28612]
The FontSizePicker is not responsive, when I change the language for example to german (yes, we have long words 😄 ). 

English
<img width="286" alt="Bildschirmfoto 2021-01-30 um 11 12 52" src="https://user-images.githubusercontent.com/695201/106353640-49821d80-62ec-11eb-95eb-739478cca8f2.png">

German
<img width="287" alt="Bildschirmfoto 2021-01-30 um 11 12 24" src="https://user-images.githubusercontent.com/695201/106353642-4a1ab400-62ec-11eb-8fdf-be147b44a106.png">

Ping @ItsJonQ

**Comment by ItsJonQ** [comment]
@Soean Thank you for the heads up! Looking into this..

**Comment by talldan** [comment]
@ItsJonQ Just wanted to check, is this a G2 only issue?

I noticed it was added to the WordPress 5.7 board, but if it's the G2 component, those won't be shipped in 5.7, so it seems like this could be removed from the project board.

**Comment by ItsJonQ** [comment]
> ...so it seems like this could be removed from the project board.

Heya @talldan ! That sounds correct to me :)

**Comment by talldan** [comment]
Thanks, I'll do that now.

**Comment by mtias** [comment]
We have a new font size picker now that shouldn't have this issue
