### ISSUE TITLE
Some input fields appear on top of fixed sidebar tab panels when focused

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#28642]
When sidebar dropdowns are in their focused state, their z-index appears to be greater than that of the fixed tab panels. This is visible in the document sidebar, as well as in the block pattern picker:

![Kapture 2021-02-01 at 15 28 06](https://user-images.githubusercontent.com/1202812/106514801-b93a0900-64a2-11eb-98c5-b72a9241f03c.gif)
 
![focus-bug-2](https://user-images.githubusercontent.com/1202812/106514740-a58ea280-64a2-11eb-963b-3c82a9d67782.gif)

---

Safari 14.0.2
Gutenberg 9.9.0-RC1

**Comment by kjellr** [comment]
This also appears to happen with the unit control field: 

![Kapture 2021-02-01 at 15 39 43](https://user-images.githubusercontent.com/1202812/106515599-eb983600-64a3-11eb-9406-aa9009c21de2.gif)

**Comment by shaunandrews** [comment]
I did some digging, and I think this might be the culprit:

https://github.com/WordPress/gutenberg/blob/004a32ec09d5b789be694d85725fe49cca385f08/packages/components/src/input-control/styles/input-control-styles.js#L21

**Comment by shaunandrews** [comment]
Might also be related: https://github.com/WordPress/gutenberg/pull/28003

**Comment by stokesman** [comment]
A few days ago I made #28562 to take care of this on the Inspector Controls. I didn't realize there's an issue in the Inserter but it'd maybe be worth fixing in that same PR.
