### ISSUE TITLE
Simplify template part toolbar and align with reusable blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#28659]
The latest work done to improve the reusable block UX yielded an update to the toolbar:

<img src="https://user-images.githubusercontent.com/548849/105178308-21463200-5b28-11eb-9471-f352c1c7d511.png">

These updates can be ported to template parts as well to promote consistency across similar site building components:

<img src="https://user-images.githubusercontent.com/846565/106589428-eb4f7780-6543-11eb-9ec6-f8e81d790a69.png">

For now I think it makes sense to restrict template part switching so that it is only possible to switch one template part for another. Transformations introduce further complexities and questions that I do not think we're quite ready to answer yet. 

I begun work on this in #27397 and there is more context in the discussion there.

**Comment by mtias** [comment]
Also noting that the dropdown would need to account for patterns once we have them https://github.com/WordPress/gutenberg/issues/27575

**Comment by Addison-Stavlo** [comment]
Noting we should probably have the renaming input that is currently in that toolbar moved somewhere accessible like the block inspector sidebar.  Left a comment/idea on that issue for updating the block inspector - https://github.com/WordPress/gutenberg/issues/27875#issuecomment-774318883

**Comment by mtias** [comment]
Yes, it should align with reusable blocks there too.

**Comment by mtias** [comment]
With the decision that the "switching of template parts to another template part" is not a common path to warrant such a prominent space, this can be considered finished.
