### ISSUE TITLE
Editable placeholders visible when there is text

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2865]
## Issue Overview
I noticed this a few times before, but can now reproduce consistently. Sometimes the placeholders are left even if there's text in the editable field.

## Steps to Reproduce (for bugs)
1. Create a pull quote.
2. Add some text in both section.
3. Put the caret in another block.
4. Placeholders are visible.

## Expected Behavior
Placeholders are not visible when there is text in the editable field.

## Current Behavior
They are.

<img width="749" alt="screenshot 2017-10-03 11 38 58" src="https://user-images.githubusercontent.com/4710635/31119096-1fcaed02-a830-11e7-85a1-b2aa77b5227c.png">

**Comment by hedgefield** [comment]
Found this too today

- opened demo post.
- selected a sentence from the first paragraph block and cut it out.
- inserted a new paragraph and pasted the sentence in there.
- clicked outside the block to deselect and the placeholder became visible again. The outline of the block also adhered to the length of the placeholder, not the length of the pasted text.

![bleh](https://user-images.githubusercontent.com/6073772/31177332-fe7cd0a2-a915-11e7-80bd-085e6afff03e.jpg)

**Comment by iseulde** [comment]
So far tracked it seems to be only the case for newly initialised editors. For those the `selectionchange` event stops firing.

**Comment by iseulde** [comment]
I can't seem to figure out the problem immediately. Maybe @ephox-mogran or @EphoxJames understand more about this? :) If not, can dig into it further later. If I use `document.addEventListener( 'selectionchange', this.onSelectionChange );` instead of `editor.on( 'selectionChange', this.onSelectionChange );` everything suddenly works properly.

**Comment by iseulde** [comment]
https://wordpress.slack.com/archives/C0UCMQP0F/p1508429892000502

**Comment by ephox-mogran** [comment]
Have you been able to test the latest version, like Spocke said? Does it look like it's fixed?

**Comment by iseulde** [comment]
Yes, it's gone with the latest nightly. This bug should be fixed then next time we bump the version.

**Comment by melchoyce** [comment]
![pasted_image_at_2017_10_26_12_49_pm_1024](https://user-images.githubusercontent.com/2846578/32066525-1535eefc-ba4e-11e7-9106-a2a51dc50741.png)

Saw this again, on 1.5.1.

**Comment by nylen** [comment]
I also saw this issue yesterday on Gutenberg 1.7.0 and WP 4.9.0 though I'm not able to find a clear way to make it happen again.

**Comment by mtias** [comment]
I haven't seen this in a bit. @iseulde have you seen this lately?

**Comment by iseulde** [comment]
I have neither. But I've also not seen cases before where the placeholder is not in the right place.

**Comment by iseulde** [comment]
I can't reproduce the original issue with the steps provided (as MCE version has been bumped), so I'm going to close this issue. Would be good to have a separate issue with steps to reproduce.
