### ISSUE TITLE
HTML-Block problems with  "<table>" element and shortcode

### ISSUE THREAD

**Issue by vtad** [WordPress/gutenberg#28652]
## Description
Reeditingwith the Visual Editor a HTML-Block with a `<table>` element and a shortcode like [xxx] [/xxx]
generates a "Attempt Block Recovery" button

## Step-by-step reproduction instructions
Following code:
```
<table><tbody>
<tr><td>
[su_spoiler title="Spoiler title" open="no" icon="plus" anchor="" ]
Hidden content
[/su_spoiler]
<td>xxxxxxxxxxxxxxxxxx</td>
</tr>
</tbody></table>
```
Works fine and generates the wished output.

## Actual behaviour
But editing it again with the visual editor I get

![image](https://user-images.githubusercontent.com/10612817/106583824-cbb94e80-6545-11eb-846d-fa31f53b270c.png)

selecting Selecting Resolve or convert to Block corrupts this block,
Only the change to html option allows to edit it.

The problem does not occur with `<ul><li>` Elements

## Expected behaviour
No error when editing again

## Code editor list
```
<!-- wp:html -->
<table>
<tbody>
<tr><td>
[su_spoiler title="Spoiler title" open="no" icon="plus" anchor="" ]
Hidden content
[/su_spoiler]
<td>xxxxxxxxxxxxxxxxxx</td>
</tr>
</tbody></table>
<!-- /wp:html -->
```

## WordPress information
- WordPress version: "5.6.0"
- Gutenberg version: "9.8.3"
- Are all plugins except Gutenberg deactivated?  "No"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: "Desktop" 
- Operating system:  "Windows 10"
- Browser:"Chrome 88.0.4324.104"

**Comment by talldan** [comment]
@vtad There's a validity issue with your HTML:
```html
<td>
[su_spoiler title="Spoiler title" open="no" icon="plus" anchor="" ]
Hidden content
[/su_spoiler]
```
This `<td>` is missing a closing `</td>` tag.

Ideally though that would be flagged earlier by the HTML block and the options to resolve the problem should be a bit clearer.

In my testing, when I clicked 'Attempt Block Recovery' the editor fixes that problem. Though weirdly it requires two clicks, the block seems a bit jumpy.

There's an issue here about removing the Convert to HTML button (https://github.com/WordPress/gutenberg/issues/10889), and I think 'resolve' might also be part of that, as this option converts the content into a different block type, which it seems like a user would never want.

I've made a separate issue about improving the experience here - https://github.com/WordPress/gutenberg/issues/28683.

Given there are other issues covering the usability of the block and your problem can be resolved by fixing the HTML, I'll close this issue.
