### ISSUE TITLE
Slugs: numeric URLs are not allowed

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#28662]
## Description

While trying to create a 404 template in an FSE theme from the dashboard I came across an interesting issue:
If I use `404` as the title, the slug became `custom_slug_60194c2e24403`.
When trying to change the slug to any numeric value I get an error: `Updating failed. Invalid parameter(s): slug`
Apparently numeric values are not allowed for slugs. Changing it to `404a` works, any random number doesn't.

## Step-by-step reproduction instructions

* Using an FSE theme try to create a 404 template from Appearance -> Templates.

If I try this on a post (using postname as permalink structure) and use `8888888888` as slug, it changes to `8888888888-2` which is acceptable since it adds the dash.

## WordPress information
- WordPress version: 5.6.
- Gutenberg version: 9.9
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme Doesn't matter, any FSE theme will do.

## Device information
- Device: Desktop
- Operating system: Ubuntu
- Browser: Firefox

**Comment by Mamaduka** [comment]
This should be fixed now. See #37579.
