### ISSUE TITLE
Sometimes legacy widget data is not saved properly

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#28672]
Woo's Products and Products by Rating widgets are saved as having 1 product visible if the default value (5) is left unmodified before saving.

![image](https://user-images.githubusercontent.com/107534/106651777-4a8da600-659d-11eb-87f8-255f6231766d.png)

**Comment by noisysocks** [comment]
When I test this I get a `widget is undefined` error when I press save.

**Comment by noisysocks** [comment]
OK I see the problem. We need to submit the widget's form when creating a new Legacy Widget as sometimes the widget's default values are encoded in the form's `value`s. I'm not yet sure how to do that elegantly with `useFormData`.

**Comment by noisysocks** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/31249.
