### ISSUE TITLE
Widgets: Offer option to disable preview or a static placeholder

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#28671]
Some core widgets are only rendered in certain pages, like filters. 

They depend on the current page having some products in the loop or some other conditions: for example, Woo's Active Product Filters is only rendered if the shopper has already selected a filter. That means that when they are previewed in the widgets editor, they look empty.

This would mean that we should have a kind of a static placeholder? What would be a nice default for developers and users alike?

Can we offer developers a way to hide the preview button?

**Comment by shaunandrews** [comment]
I posted an updated design that I _think_ would resolve this: https://github.com/WordPress/gutenberg/issues/26179#issuecomment-776293331

![Legacy Widgets, Take 2](https://user-images.githubusercontent.com/191598/107438220-2894a600-6afe-11eb-885a-e03845daf1d3.gif)

**Comment by paaljoachim** [comment]
The issue was discussed during a Design triage on slack: https://wordpress.slack.com/archives/C02S78ZAL/p1612888120354200

**Comment by noisysocks** [comment]
#30889 will close this and the way that a widget can choose to render a static "Preview is not available." placeholder is by rendering no output in its implementation of `WP_Widget::widget()`.
