### ISSUE TITLE
Best approach for dynamic block rendering in the editor

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#28684]
## What problem does this address?

Currently, core dynamic blocks use one of two different approaches to rendering in the editor: 

* server-side rendering with `ServerSideRender`, which reproduces the markup defined in the block's `index.php` (e.g. Archives, Latest Comments)
* client-side rendering with the REST API and reconstructing the markup defined in `index.php` in JS. (e.g. Categories, Latest Posts)

The [developer docs](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/) recommend client-side rendering:

> Server-side render is meant as a fallback; client-side rendering in JavaScript is always preferred (client rendering is faster and allows better editor manipulation)

However, it's not clear that client-side rendering does in fact work better:

*  Performance-wise, blocks using `ServerSideRender` load faster than blocks using JS to render the same amount of content. 
* Duplication of markup between PHP and JS files makes things messy to maintain and error-prone.

## What is your proposed solution?

I'd love to see us leverage `ServerSideRender` on all our dynamic blocks, but in order to do so we'll need to improve it:

* It shouldn't have to wrap its content in an extra piece of markup;
* It should be able to work with block context (this will also require changes to the REST API endpoint)

Thoughts and ideas welcome!

(This issue was prompted by work on #28265 , where I opted to use to use `ServerSideRender` but ran into the issue of not being able to use block context to customise markup output.)

**Comment by mtias** [comment]
We recommend client-blocks because it's intrinsic to how the editor is meant to work: direct manipulation with instant feedback for all manipulations, which we can only ensure client side. `ServerSideRender` should generally be avoided outside of very naive cases that won't require much interaction or are supposed to work as embeds. I would not recommend it for the pages block because the moment we start supporting the customization tools (typography, colors, sizing, possibly reordering, etc) the roundtrip becomes a hindrance to the UX. Server-side blocks are also not suitable for the mobile apps.

**Comment by gziolo** [comment]
What if one day we would have [React Server Components](https://pl.reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html) implemented in PHP? 😄 

I guess it's far in the future to see it enabled in React, but they are working on the serialization layer so, in theory, it could work with any language. As far as I understood the idea, it would address most of the concerns with the code duplication between `Edit` in JS and `save` in PHP. The use case for the mobile apps is probably more difficult to address though.

**Comment by mtias** [comment]
The streaming protocol would indeed be cool to explore given we already have the block abstraction established. It wouldn't be too out there to consider passing component state through it. We briefly discussed this with @luisherranz in the context of Frontity and how it could consume blocks in the front-end in the future.

But that also points to another important distinction of server-client, which is `edit()` is meant to tailor its component for editing / interaction while `server || save()` is meant to render the best representation for the front-end. We don't have the concept of `edit` on the server.

**Comment by gziolo** [comment]
> But that also points to another important distinction of server-client, which is `edit()` is meant to tailor its component for editing / interaction while `server || save()` is meant to render the best representation for the front-end. We don't have the concept of `edit` on the server.

This is a good reminder. It's easy to fall into a trap of wanting to share code between `edit` and `save`. We often see reports that React hooks don't work with `save` on the client. This is a good thing as it helps to understand that `save` isn't interactive and only translates components into HTML output. It's all interesting, but also extremely hard to communicate to the folks writing blocks.

**Comment by youknowriad** [comment]
Seems like we don't want to change our current recommendation for now. So I'm closing this.

**Comment by mtias** [comment]
There's one use case I thought could be useful for themes that want to keep a template part in PHP but still render it in the editor visible (but not editable).

**Comment by NazimHAli** [comment]
> Currently, core dynamic blocks use one of two different approaches to rendering in the editor:
> - server-side rendering with ServerSideRender, which reproduces the markup defined in the block's index.php (e.g. Archives, Latest Comments)
> -  client-side rendering with the REST API and reconstructing the markup defined in index.php in JS. (e.g. Categories, Latest Posts)

Has anyone come up with a good way, pattern to handle this? It bothers me that we have to build the same UI twice, in php and js. 

For simple blocks, I was thinking of parsing a shared js template.

**Comment by NazimHAli** [comment]
> This is a good reminder. It's easy to fall into a trap of wanting to share code between `edit` and `save`. We often see reports that React hooks don't work with `save` on the client. This is a good thing as it helps to understand that `save` isn't interactive and only translates components into HTML output. It's all interesting, but also extremely hard to communicate to the folks writing blocks.

@gziolo so `save` only outputs static compiled html?

**Comment by gziolo** [comment]
> so save only outputs static compiled html?

Yes.

**Comment by NazimHAli** [comment]
@gziolo thanks for the confirmation, that is definitely not how I understood the docs/tutorials :disappointed: 

>but also extremely hard to communicate to the folks writing blocks.

My understanding was:
- All the JS/CSS/HTML for `edit` will be served in the admin UI
- All the JS/CSS/HTML for `save` will be served client side

**Comment by alanef** [comment]
I have just come across this too.

To me it is obvious you want the same output in edit as you do in the front end.

Creating two sets of code one in REACT and one on PHP or if the front end is truely dynamic (e.g. near real time data display ), one in REACT and one in JS / JQuery ( or go through hoops and hoops to get REACT working on the front end ) seems 'fail'.

If the desire is to have dynamic in the editor then surely an easy way to have dynamic / interactive in the front end should be considered.

I was very disappointed to not be able to just put the same react component into my edit as save. My assumption was the same as Nazim and until it didn't work for an explanation on stackexchange.
