### ISSUE TITLE
WP-Env: `dockerComposeConfigPath` with spaces causes errors during commands

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#28680]
## Description
Running `@wordpress/env` version `3.0.2`.

The [`wp-env start`](https://github.com/WordPress/gutenberg/blob/537412fd439c0c8a9befcf99e8bbbc2fdc8c1147/packages/env/lib/commands/start.js#L187) command attempts to start up the mySQL container, but passes the path to the `docker-compose.yml` as an argument (via the config option of `dockerComposeConfigPath`), this is also referenced in other locations like [`wp-env run <container>`](https://github.com/WordPress/gutenberg/blob/537412fd439c0c8a9befcf99e8bbbc2fdc8c1147/packages/env/lib/commands/run.js#L54) for example, but possibly elsewhere as well.

This causes an error if the path contains spaces, essentialyl splitting the path into an invalid path, and an unrecognized argument. The use of spaces in user home directories is fairly common in Windows host systems at least.

As an example, a fresh `wp-env start` causes the following command to be ran:
```
docker-compose -f C:\\Users\\Marius Jensen\\.wp-env\\d0b03975b6f44b57d988f261e33c8d81\\docker-compose.yml port mysql 3306
```

Resulting in this error:
```
No such command: Jensen\\.wp_env\\d0b03975b6f44b57d988f261e33c8d81\\docker_compose.yml
```

A simple fix for `start.js` is to wrap the path in quotes as 
```
`docker-compose -f "${ dockerComposeConfigPath }" port mysql 3306`
```

Unfortunately this does not help with scenario like `run.js`, where the arguments are dynamically built from an array, so I'm not sure how it would be solved in that case.

## Device information
- Operating system: Windows 10 (10.0.18363 Build 18363)
- Node: 12.16.1
- NPM: 6.14.2
- Docker Desktop: 3.1.0

**Comment by noahtallen** [comment]
I filed an upstream issue here: https://github.com/PDMLab/docker-compose/issues/129. I think it will need to be fixed there.

**Comment by Steveb-p** [comment]
In the upstream library (linked) we weren't able to reproduce the issue with argument escaping.

Could you please confirm that mentioned `run.js` script is affected by the space in path issue?

Your initial description sounds like it's just an assumption, not an actual execution issue, hence my question.

**Comment by noahtallen** [comment]
I'm working on replicating it on Windows PowerShell (Docker WSL2 backend):

```ps
mkdir 'Spaces Dir'
$env:WP_ENV_HOME = 'C:\path\to\Spaces Dir'
mkdir test
cd test
wp-env start
```

This replicates the problem instantly. I'm doing more debugging to figure out exactly where this is going wrong!

**Comment by Steveb-p** [comment]
@noahtallen please do note that `start.js` command does not actually run the `docker-compose` npm package. And actually, neither does `run.js`.

**Comment by noahtallen** [comment]
> @noahtallen please do note that start.js command does not actually run the docker-compose npm package. And actually, neither does run.js.

Could you clarify that? Maybe I misunderstand what this does: https://github.com/WordPress/gutenberg/blob/9f4c68623f5882f35e8f77edb16792db8e17184d/packages/env/lib/commands/start.js#L4

**Comment by noahtallen** [comment]
The problem was a direct call to docker-compose, fixed here: #30692. I should have investigated this further before creating the upstream issue, sorry about that!

**Comment by Steveb-p** [comment]
The line in question that you were refering to in the issue description does make direct call to `docker-compose` (that is, docker - not npm) binary.

`run.js` does not make use of `docker-compose` npm package (which threw me off just a second ago). `start.js` does indeed use it, but all those calls should properly work with spaces in directories. Tests done in the library indicate that they should (unless we made some sort of mistake).

> I should have investigated this further before creating the upstream issue, sorry about that!

No worries there. I actually wasn't sure if the docker-compose npm lib would handle this or if it's something that needs escaping, so it helped grew some more confidence in it :stuck_out_tongue:

**Comment by noahtallen** [comment]
Yeah, we needed to call docker-compose directly in `run.js` to support running bash or other interactive commands inside of the services. IIRC, there were some problems getting it to work right when we did not call it directly.

**Comment by Steveb-p** [comment]
> Yeah, we needed to call docker-compose directly in `run.js` to support running bash or other interactive commands inside of the services. IIRC, there were some problems getting it to work right when we did not call it directly.

It's a long standing issue in the npm lib. We were unable to get interactivity to work, and I'm not a JavaScript specialized developer so I wasn't sure how to approach it. Maybe I'll try again :stuck_out_tongue_winking_eye: 

It was after all some time ago and maybe I'll get the streams right this time.

**Comment by noahtallen** [comment]
Yeah, it was definitely tricky when I looked into it too. 😬 This is how we handled it: https://github.com/WordPress/gutenberg/blob/cdf70c2692619cc83d25206c2366d0bcbc54f714/packages/env/lib/commands/run.js#L51-L84

I think possibly passing `stdio: 'inherit'` as an option was the important thing.
