### ISSUE TITLE
Edit Post menu makes it impossible to select CLASSIC editor in mobile

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#2869]
## Issue Overview

If viewing your site on mobile/iPad, the edit link for an individual post will show up as the pencil with a dropdown for editing in Gutenberg. The problem is that on a TOUCH device, you can't click the pencil link to go to the classic editor.

## Steps to Reproduce (for bugs)
1. Log in to a site with Gutenberg on a mobile device
2. Navigate to a page you can edit
3. Click the pencil to edit

![screen shot 2017-10-03 at 10 24 02 am](https://user-images.githubusercontent.com/807903/31139043-36dcb530-a825-11e7-83d7-53c85adde5da.png)

## Expected Behavior

I should be able to edit in classic mode.

## Current Behavior

I can only edit in Gutenberg

## Possible Solution

The dropdown should show BOTH classic _and_ Gutenberg, or the pencil should allow a new click to edit. Frankly I think the former would be better.

**Comment by mtias** [comment]
@karmatosed what is the status of this after we have made Gutenberg the default?

**Comment by karmatosed** [comment]
I am unable to recreate. If you can @Ipstenu please reopen and we can deal with this.

**Comment by Ipstenu** [comment]
Now I go straight to Gutenberg, however that happens EVEN on a non-Gutenberg post. Is that supposed to be expected behavior, because if so it's rather problematic.
