### ISSUE TITLE
Allow dynamic blocks to be used in php templates.

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#28702]
## What problem does this address?

There are a number of blocks only available in "FSE themes" that replace logic previously managed with [template tags](https://codex.wordpress.org/Template_Tags).

These blocks are a requirement for "FSE themes", however a classic PHP-based theme might benefit from migrating away from the PHP template tags and begin using these new blocks instead.

There has been discussion regarding these tags "being available in certain situations" (such as a user switching away from a FSE theme where those tags are used in block templates for example).

However there is value in ANY theme being able to use these blocks as a way to migrate towards using the technologies available to "FSE" themes.

The attempt to replace a template tag with a new block is outlined (simply) in [this theme experiment](https://github.com/WordPress/theme-experiments/pull/194).

There are [another](https://github.com/WordPress/gutenberg/issues/24803) issues that discuss the relationship between "classic" and "block-based" themes, so this topic has likely already been discussed.  

## What is your proposed solution?
I haven't been able to determine if the blocks not working for these templates is due to a technical limitation or operational decision.  If it is an operational decision I propose making these blocks more widely available (perhaps behind a "theme supports flag" for the time being) to themes beyond "FSE themes".

**Comment by talldan** [comment]
There's also this issue which might have some overlap - https://github.com/WordPress/gutenberg/issues/24313.

**Comment by pbking** [comment]
Closing as this as #28744 poses the same question in a more complete way with better discussion.
