### ISSUE TITLE
Navigation link server renderer tries to `get_post` on links with types other than post/page causing links to not render

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#28712]
## Description

The `get_post` [here](https://github.com/WordPress/gutenberg/pull/27207/files#diff-96cfb99105116cdbf48eface8e7ac4dff062da11f291996bf5748d5a8b90f3e0R109) doesn't work with categories _(and possibly other link types different from post/page?)_, and (might) end up returning an empty string, resulting in the inner link block not rendering in the frontend.

It seems that this went unnoticed because, in a testing environment _(i.e when testing manually using a fresh WP org install)_, the IDs of post/pages and categories are small enough that they overlap, and that ends causing the link to be rendered, causing the false impression it's working as expected.

## Step-by-step reproduction instructions

1. Add a new post or page. We're also assuming there's a post with ID = 1 in your WP instance already; you'll also use the default "Uncategorized" cat (which also has 1 as the ID);
2. Add a horizontal or vertical Navigation block to the page. Add any number of links you'd like, but be sure to add at least one of type "Category" and select the "Uncategorized" cat;
3. View the published page. You'll see that the navigation link for "Uncategorized" is shown;
4. Now edit the post with ID = 1 and set it to private;
5. Go back to and view the test post/page you created earlier. You'll see that the nav link for "Uncategorized" is now gone!

## Expected behavior

I expect any navigation links with a type other than page or post to not be influenced by settings from posts / pages and to show as expected.

## Actual behavior

Navigation links with type other than page / post are not rendered if there's not a post/page with the same ID and or if there is and it's private.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/81248/106830994-c1d24100-6654-11eb-97a3-41cb5a9ed843.mp4

## WordPress information
- WordPress version: 
- Gutenberg version: `9.8.3` and `master` (`537412fd43`)
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes.

## Device information
- Device: Desktop.
- Operating system: Ubuntu Linux 18.04.
- Browser: Firefox 86.0b5 (64-bit).

**Comment by ockham** [comment]
@draganescu @talldan Could y'all look into this one? Seems like it'd be good to get it fixed for GB 9.9 (and by extension, WP 5.7), since it can break the nav block apparently quite badly.

**Comment by ockham** [comment]
Let's also add some test coverage (e.g. PHP unit test for `render_block_core_navigation_link`) when we fix this, to avoid regressions :slightly_smiling_face:

**Comment by gwwar** [comment]
I can try taking a look 👍 Let me know if folks already have a patch, I can help review otherwise

**Comment by draganescu** [comment]
Just saw this, I wont be able to work on it for this week. If it's still up next week I can come back to it, otherwise, thank you in advance, @gwwar ! :)
