### ISSUE TITLE
Navigation Block/FSE: Empty state in block based themes

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#28711]
This feels like something in between the editor and block-based themes. Basically, I found it very confusing that the links inside the navigation block are “dead” - they don’t link to actual pages. 

Secondly, even though I had a nav menu created on the site when I opened the site editor the "dummy" menu was used (the one hard-coded in the header block template part of the theme). I'm not sure what the future of old nav menus created via the Customizer is, so maybe this is expected?

## Step-by-step reproduction instructions
1. Activate the Gutenberg plugin and a block-based theme, for example, [TT1 Blocks](https://github.com/WordPress/theme-experiments).
2. Open Site Editor and note the Navigation block with "Home", "Blog, "Work, and "Contact" items.
3. Click on each link. It's not clear that the menu items need to be set up in any way (and how?).
![image](https://user-images.githubusercontent.com/4550351/106826511-289a3d80-66db-11eb-83a4-a5aa2a9a6622.png)
4. Preview the site. Hover over the nav menu items. Note they don't lead anywhere.

## Expected behaviour
I expected some sort of guidance around editing the nav menu, and/or not having the example menu items in place. I know those are defined in the theme, but there doesn't seem to be an empty state for the Navigation block either that would allow to insert it without any links.

## Screenshots or screen recording (optional)
This might be a separate issue, but note how the navigation block toolbar is sticking to the left side.
![QBCQNRTGH0](https://user-images.githubusercontent.com/4550351/106827923-6e580580-66dd-11eb-9a75-d893864fd9bd.gif)

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.8.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No (TwentyTwentyOne Blocks)

## Device information
- Device: Desktop
- Operating system: macOS 10.15.7
- Browser: Chrome 87.0

**Comment by talldan** [comment]
I think the Home, Blog, Work, Contact 'links' come from the template part, but don't know for sure. Is that defined in TT1-blocks?

**Comment by alaczek** [comment]
Yep, they are defined in TT1 blocks. The way things are, you have to include some menu items in the navigation block, if you're going to use it, because there is no empty state for the block (as I understand). In the issue, I tried to explain how confusing those links that go nowhere are.

**Comment by alaczek** [comment]
I just noticed that the navigation block has an interesting initial state right after it's inserted in the editor:
![image](https://user-images.githubusercontent.com/4550351/108443509-042e8b80-72ad-11eb-8ffb-961060f17cf8.png)

This is more useful because it lets me select from existing nav menus, and does not include "ghost" links. I think it would make more sense if block-based themes could just indicate where the nav menu would be in the header without defining specific links (basically use this initial state).

**Comment by jordesign** [comment]
Hey @alaczek  - with the Navigation block now defaulting to using the Page List - is this issue still relevant?

**Comment by jordesign** [comment]
With no further comment here for now - I'm going to close the issue.
