### ISSUE TITLE
Block movers incorrectly styled in Top Toolbar mode

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28717]
## Description
When Top Toolbar mode is activated, the block movers in the toolbar don't look the same, with extra spacing between the arrows.

## Step-by-step reproduction instructions
1. Add some blocks
2. View the block movers normally
3. Activate top toolbar
4. See that the movers look different

## Expected behaviour
<img width="321" alt="Screenshot 2021-02-04 at 12 01 05 pm" src="https://user-images.githubusercontent.com/677833/106843298-af054e00-66e0-11eb-955b-d4e24015fae7.png">

## Actual behaviour
<img width="293" alt="Screenshot 2021-02-04 at 11 56 11 am" src="https://user-images.githubusercontent.com/677833/106843265-9b59e780-66e0-11eb-89af-850cc2903b21.png">

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.9
- Are all plugins except Gutenberg deactivated? Y
- Are you using a default theme (e.g. Twenty Twenty-One)? 2021

## Device information
- Operating system: Mac OS
- Browser: Brave

**Comment by mtias** [comment]
I think this one regressed a couple times, was going to report it as well.

**Comment by lukecarbis** [comment]
Just tried replicating the problem. I could see the issue in Gutenberg 9.9, but it seems fixed in the 1.0.0 release candidate.

**Comment by talldan** [comment]
I'm seeing that too, a mysterious fix 😄  

Thanks for testing @lukecarbis, will close this issue.

**Comment by mtias** [comment]
Leave a codebase alone for a bit and it fixes itself :)
