### ISSUE TITLE
Drag-selecting blocks selects in the wrong direction

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#2873]
## Steps to Reproduce (for bugs)
1. Open demo post
2. Put the cursor in front of the `The goal of this new editor...` sentence, hold down left mouse button and drag down to select the text in the block.
3. When you reach the end of the block, keep going into the next one
4. Instead of selecting the current block and the next block (how it used to work), it selects the current block and _all_ blocks above that one.

![selectup](https://user-images.githubusercontent.com/6073772/31177066-23383cca-a915-11e7-9706-ee5b89516c75.gif)

chrome on mac
vagrant development environment
wordpress 4.8.2
gutenberg 1.2.1

**Comment by iseulde** [comment]
It's fixed in #2858 and therefore today's release. :)
