### ISSUE TITLE
Enabling Full Site Editor blocks in classic themes

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#28744]
With the upcoming inclusion of Full Site Editing in WP 5.8, many of the site-editing-oriented blocks currently enabled only with FSE should also be available to use in classic themes. The goal of this issue is to list all these blocks and determine whether each of them should also be enabled in non-FSE contexts.

Block | Should be enabled without FSE? | Related Issue
------------ | ------------- | -------------
siteLogo|✅| #30406 
siteTagline|✅|#30921
siteTitle|✅|#30918
templatePart|❌
query|✅| #26316, #30910
queryLoop|✅ |#26316
queryPagination|❌|
postTitle|✅|
postContent|✅|
postAuthor|✅|
postComment|❌|
postCommentAuthor|❌|
postCommentContent|❌|
postCommentDate|❌|
postComments|❌|
postCommentsCount|❌|
postCommentsForm|❌|
postDate|✅|
postExcerpt|✅|
postFeaturedImage|✅|
postHierarchicalTerms|✅|
postTags|✅|
archiveTitle|❌|
termDescription|❌|
loginOut|✅|

These blocks will be categorized in the block inserter as defined in #26639

**Comment by skorasaurus** [comment]
There's an issue about this for the Query Block at https://github.com/WordPress/gutenberg/issues/26316

**Comment by carolinan** [comment]
I would find the post excerpt useful.
A use case would be to have a custom excerpt showing in an archive, and then be used as lead text for the individual post.

**Comment by priethor** [comment]
All in all, it seems we kind of need most blocks except the "template part" block, which only makes sense in a Site Editing context.

**Comment by priethor** [comment]
As far as the Query block is concerned, we need to include all individual block variations built on top of the main Query block (e.g., "Posts block", "Pages block", which are the ones that end-users will be facing in the inserter, as well as Query block patterns (#28891)

**Comment by mtias** [comment]
Updated the issue to exclude the "comments" related ones, since those make more sense for `single` page templates and need a bit more work.

**Comment by priethor** [comment]
Added to the list the 3 new theme blocks that landed in [10.3](https://make.wordpress.org/core/2021/04/02/whats-new-in-gutenberg-10-3-31-march/) (Login/Out, Term Description, and Archive Title) for tracking purposes, although they don't seem to make a lot of sense with the Landing page scope of 5. Moreover, without #30679 the archive blocks can be used in any template even if they are not meant to.

**Comment by priethor** [comment]
Added the Login/Out as it can indeed be useful if added to a Widget Area thanks to the Widgets Editor project.

**Comment by youknowriad** [comment]
Reopening because there are some blocks left that we'd want to reconsider.

 - Terms blocks after #31422 
 - LoginOut

**Comment by grappler** [comment]
The postAuthor block was not included in WP 5.8 https://github.com/WordPress/gutenberg/pull/31983
