### ISSUE TITLE
Android - Keyboard not showing up after closing the BottomSheet

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#28748]
## Description
While working on this [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3057) I found an issue on Android where opening a BottomSheet from a focused text block (Paragraph, Heading) would cause the keyboard to not show up after the BottomSheet has been closed and the block was still selected. It was found using the Link picker but it happens with the block settings as well.

## Step-by-step reproduction instructions

**On an Android device/simulator**

1. Open the editor
2. Add a Paragraph block
3. Type some text
4. Tap on the three dots to open the block settings
5. See the keyboard getting dismissed and the BottomSheet opening
5. Close the settings
6. See the block is still selected but the keyboard didn't come back after closing the block settings BottomSheet

## Expected behaviour
The Keyboard should be shown after the BottomSheet has been closed when the block is still selected. As it happens on the iOS platform.

## Actual behaviour
The Keyboard stays hidden when the BottomSheet has been closed and the block is still selected.

## Screenshots

<kbd><img src="https://user-images.githubusercontent.com/4885740/106932163-b136cf00-6717-11eb-9542-5c2bb3197c1a.gif" width=250 /></kbd> <kbd><img src="https://user-images.githubusercontent.com/4885740/106932170-b3009280-6717-11eb-981d-75419c4f739f.gif" width=250/></kbd>

## Device information
- Device: Pixel 3 Simulator and Redmi Note 8T
- Operating system: Android 10

**Comment by kathrynwp** [comment]
Hi @dcalhoun -  circling back to this issue, is it still occurring with the latest version of Gutenberg and WordPress? Thanks!

**Comment by dcalhoun** [comment]
@kathrynwp yes, I was able to reproduce this on an Samsung Galaxy S20 (Android 12) with the WordPress 20.5 app.

**Comment by fluiddot** [comment]
Close this issue as it has been fixed in https://github.com/WordPress/gutenberg/pull/57069.
