### ISSUE TITLE
Ref property of TextControl is not returning a reference to DOM object

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#28756]
## Description
Ref property of TextControl does not point to DOM element, instead it is set to null

## Step-by-step reproduction instructions
I copied Edit component of my custom gutenberg block. I believe aTextControl.ref which is outputted to console should be other than null

## Expected behaviour
ref should point to DOM element, input tag, so I could manipulate it (set focus)

## Actual behaviour
ref is null

## Code snippet (optional)
Full file is attached, but only references are missing in code snippet which is given below.
[edit.zip](https://github.com/WordPress/gutenberg/files/5928245/edit.zip)

```
export default function Edit({ attributes, setAttributes }) {
	const innerTemplate = [
		[ 'core/heading',
			{
				'placeholder' : 'Naslov',
				'className' : 'naslov-izloska'
			}
		],
		[
			'core/heading',
			{
				'level': 3,
				'placeholder' : 'Podnaslov'
			}
		],
		[ 'core/paragraph',
			{
				'placeholder' : 'Kataloški broj'
			}
		]
	]

	const aTextControl = <TextControl
									autoFocus
									label="Broj izloška"
									value={ attributes.exhibitNumber }
									onChange={ (val) => setAttributes({ exhibitNumber: val }) }
									className="exhibit-number"
									tabIndex="0"
								/>
	useEffect(() => {
		console.debug(aTextControl.ref);

	}, []);

	return (
		<div { ...useBlockProps() }>
			{aTextControl}
			<div className="exhibit-text">
				<InnerBlocks
					template={ innerTemplate }
				/>
			</div>
		</div>
	);
}
```

## WordPress information
WordPress 5.6.1, embedded gutenberg

## Device information
Desktop
Windows 10
Firefox Developer edition 86.0

**Comment by gwwar** [comment]
If this needs a ref, see updates to the React API in https://reactjs.org/docs/refs-and-the-dom.html. Pretty sure this needs a `createRef` call.

In the Gutenberg project, we wrap calls to React using the "WordPress/element" package, so all examples there would still apply, but instead we import using:

```jsx
import { createRef } from '@wordpress/element';
```

**Comment by Lovor01** [comment]
I am pretty sure it needs ref, because I want to give focus to input box upon loading. This is one of rare cases where you do use ref. I tried also with createRef, but with no success. I imported it just like you mentioned. (You can still see it referenced in file I attached).

**Comment by Lovor01** [comment]
If you take a look at the TextControl source, whole function is exported so ref is forwarded, so that was in mind.
`export default forwardRef( TextControl );`

**Comment by gwwar** [comment]
@Lovor01 try extending Component. Pure functions can't have refs

> By default, you may not use the ref attribute on function components because they don’t have instances:
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by gwwar** [comment]
> If you take a look at the TextControl source, whole function is exported so ref is forwarded, so that was in mind.

Oh sorry, you're right that was added in https://github.com/WordPress/gutenberg/pull/26209

Related documentation is in https://reactjs.org/docs/forwarding-refs.html just a sec I'll see if I can get a small example up.

**Comment by gwwar** [comment]
Here's a small example of just the ref behavior:

```jsx
import { TextControl } from '@wordpress/components';
import { useEffect, createRef, useState } from '@wordpress/element';

const TextControlExample = () => {
	const [ value, setValue ] = useState( '' );
	const refTextControl = createRef();

	useEffect(() => {
		console.log( 'hello', refTextControl );
	}, []);

	return (
		<TextControl
			label="Hidable Label Text"
			help="Help text to explain the input"
			type="text"
			value={ value }
			onChange={ setValue }
			ref={ refTextControl }
		/>
	);
};
```

<img width="516" alt="Screen Shot 2021-02-04 at 3 07 11 PM" src="https://user-images.githubusercontent.com/1270189/106966797-e08b1300-66fa-11eb-9516-fe6438e0cdcf.png">

**Comment by Lovor01** [comment]
My mistake, after looking better into block editor code, I discovered latest version is not merged into WordPress 5.6.1. Instead, version of the code where ref is not given (forwarded) is embedded [https://github.com/WordPress/gutenberg/blob/wp/5.6/packages/components/src/text-control/index.js](url).
So, your example does not work in this version. How to get ref now?
What comes to my mind is taking this code in the mentioned link above and converting it into class component, and attaching ref. Is there any easier way? Some way of just inheriting this code?

**Comment by gwwar** [comment]
>  converting it into class component,

If the forward ref is not available, yes, this is what I'd try next.

**Comment by stokesman** [comment]
You might try using `InputControl` instead. It's still marked experimental but it does forwards refs and it's in 5.6.
https://github.com/WordPress/gutenberg/tree/wp/5.6/packages/components/src/input-control#usage

**Comment by Lovor01** [comment]
I ended up with copying new `TextControl` code (*index.js* from master repository), where `ref` from input control is forwarded, and using this code
```
const myRef = createRef();
const aTextControl =
		<TextControl
			label="Broj izloška"
			value={ attributes.exhibitNumber }
			onChange={ (val) => setAttributes({ exhibitNumber: val }) }
			className="exhibit-number"
			tabIndex="0"
			ref={myRef}
		/>

	useEffect(() => {
		myRef.current.focus();
	}, []);
```
for giving focus to input control upon rendering. Changing functional component to class component was not needed, as it obviously works.
Thanks to all for suggestions.
