### ISSUE TITLE
Nested ordered list gets corrupted using classic editor

### ISSUE THREAD

**Issue by PawanjitAhluwalia** [WordPress/gutenberg#28754]
## Description

The title says it all.

## Step-by-step reproduction instructions

Please see the following post:

https://wordpress.org/support/topic/nested-ordered-list-gets-corrupted/#post-14004340

- Insert a classic block with nested ordered lists
- switch to visual editing and modify a value

Example markup:
eg:
```html
<ol>
<li>
<ol>
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
</li>
<li>
<ol>
<li>four</li>
<li>five</li>
<li>six</li>
</ol>
</li>
</ol>
```

Expected: List is updated 
Actual: outer list styling is disabled:

```
<ol>html
<li style="list-style-type: none;">
<ol>
<li>one</li>
<li>edited</li>
<li>three</li>
</ol>
<ol>
<li>four</li>
<li>five</li>
<li>six</li>
</ol>
</li>
</ol>
```

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1270189/106951440-a0b93100-66e4-11eb-95fd-cb9666ab748f.mp4

## WordPress information
- WordPress version:5.6.1 
- Gutenberg version:Not Installed 
- Are all plugins except Gutenberg deactivated?Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system:Windows 10 
- Browser: Firefox

**Comment by gwwar** [comment]
Thanks for the report @PawanjitAhluwalia ! I've verified that this happens and updated the issue summary to reflect what was noted in the support post.

**Comment by kathrynwp** [comment]
@PawanjitAhluwalia I'm no longer able to replicate this bug with:

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active

I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.
