### ISSUE TITLE
Project automation: Nudge PR authors to add a [Type] label

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#28760]
## What problem does this address?

`npm run changelog` is not able to categorise PRs that have no `[Type]` label which makes it difficult to create Gutenberg release posts.

## What is your proposed solution?

It would be neat if we had a bot that reminds PR authors to add an appropriate `[Type]` label. It can do this if a PR is merged with no `[Type]` label.

A related problem is the overuse of `[Type] Enhancement`. Many PRs should instead be labeled `[Type] Experimental` or `[Type] Feature`. This is harder to detect automatically, though 🙂

Lastly, but not really related, is that it could also be useful if a bot detects that a PR with `[Type] Enhancement`, `[Type] Feature`, etc. is merged with no updates to any `CHANGELOG.md` files. This would help with npm package publishing.

**Comment by noisysocks** [comment]
Maybe it's too noisy but could even have it so that the bot illustrates how the PR will appear in the changelog so that the author can make tweaks as necessary. For example:

---

Hi $author! Congrats on getting this merged. This is how your PR will appear in the 10.0 releases notes:

```
Tools

- Run the load time indicator computation multiple times. (28419)
```

Please update the title of this PR and/or the `[Type]` labels if that doesn't look right.

**Comment by Mamaduka** [comment]
This has been implemented.
