### ISSUE TITLE
Allow other alignements for the Media & Text block

### ISSUE THREAD

**Issue by marekdedic** [WordPress/gutenberg#28776]
## What problem does this address?
The Media & Text block does not respect content padding and the overflows into it. This is expected with the "Wide" alignment, but there is no other alignment than "Wide" and "Full width"

Basically, I want to have an image with a text side-by-side and  not have it creep into the padding. I can't use the columns block because it works differently on mobile.

## What is your proposed solution?
Add another alignment to the Media & Text block - I don't know how it would be called.

**Comment by Mamaduka** [comment]
Hi, @marekdedic

You can remove the default alignment by clicking on the selected one. Then block should fit the content width and respect the padding.

There's already an issue about default alignment for the "Media & Text" block - #20941.

**Comment by marekdedic** [comment]
Hi,
yes, I found that out later and forgot to close this. However, I find the UI of "toggle, one, toggle other or *deselect* both" incredibly confusing. Should I open a new issue for that?

**Comment by Mamaduka** [comment]
I agree it is a little confusing. There's a similar issue - #30782, so no need to create a new one.

P.S. I think I also saw mockups somewhere for "None" or "No alignment" options.
