### ISSUE TITLE
Allow previewing unsaved changes before saving template-parts in the site-editor

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#28778]
Came up during a contributors day, from users testing FSE for the 1st time.

In the site-editor, try to make changes to the content, the header etc.
When it's time to save, hit the publish button and options appear saying "Are you ready to save:", followed by a list of things that changed with checkboxes.
If we don't want to save the header, then de-selecting the header template-part should change the preview to show the difference between new and old, allowing users to make an informed decision about whether they actually want to save it or not.

**Comment by ntsekouras** [comment]
Do you have something in mind for this design wise? For example with a small preview popover or in the editor `undoing` the changes?

Also it would be kind of tricky to handle the `root` changes preview, like Site Title, if it exists in a Template Part etc..

**Comment by aristath** [comment]
Users testing FSE were expecting the main view to simply change and show the previous (saved) version of the header when deselecting the header template-part from the save list. No popup etc... I don't know how easy that would be to accomplish though :thinking:

**Comment by annezazu** [comment]
Closing this out in favor of this current issue just to prevent any confusion: https://github.com/WordPress/gutenberg/issues/28208 

P.S. Thank you all so much for testing <3
