### ISSUE TITLE
Global styles sidebar: Changing the root background color requires two clicks

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28785]
## Description

In the Global Styles sidebar, in the Root tab,
I have to click twice to change the background color.
The first click selects the color in the palette, but it does not change the body background color.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Enable a full site editing theme with a color palette, for example TT1 Blocks.
2. Go to the site editor.
3. Open the Global Styles sidebar, select the Root tab.
4. Under background color, select any of the palette colors.
5. See that the color is selected -it has a visible border, but that the body background does not change.
6. Click any color, and see that the background color is changed.

To compare the behavior, select a new color for the text, see that the text color changes on the first click.

## Expected behaviour

I expect the color to change on the first click

## Actual behaviour

The color only changes if I click twice.

## Screenshots or screen recording (optional)

![background-global-styles-root](https://user-images.githubusercontent.com/7422055/107034182-a717dd80-67b6-11eb-8593-4a4ea9f207a4.gif)

## WordPress information
- WordPress version: 5.7-beta1-50172)
- Gutenberg version: Master branch: https://github.com/WordPress/gutenberg/commit/1f1bcc64a19d53e1b1b243c2c4b3eafba6798599
- Are all plugins except Gutenberg deactivated? No, the beta tester plugin is installed
- Are you using a default theme (e.g. Twenty Twenty-One)? No, TT1 Blocks version 0.4.3

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 88.0.4324.104, Firefox 85.0

**Comment by nosolosw** [comment]
Thanks for reporting, I can repro this. The weirdest thing is that I can only repro it _the first time_, subsequent clicks work fine for me. 

This is probably best looked at when https://github.com/WordPress/gutenberg/pull/28837 lands, as it fixes some related things.

**Comment by carolinan** [comment]
Confirmed that this is still an issue with WordPress 5.8 and Gutenberg 11.2.1.

**Comment by carolinan** [comment]
I am no longer able to reproduce this, closing.
