### ISSUE TITLE
Site-Editor: Selecting a gradient preset should update the control and add points so users can then finetune it

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#28781]
Came up during a contributors day, from users testing FSE for the 1st time.

When selecting a gradient preset, the control should be updated with the preset's points so that users can then finetune it and edit it.
This is possible in the post-editor, but not in the site-editor.

https://user-images.githubusercontent.com/588688/107030724-b64c5a80-67b9-11eb-85e4-49e7404c911b.mp4

cc @moorscode

**Comment by kathrynwp** [comment]
Hi @aristath - if I'm  understanding the issue correctly, I haven't been able to replicate this in the current version of WordPress. I'm able to edit the gradient in the same way on a Group block both in the Site Editor and Page Editor. 

I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details on how to replicate and I’ll be more than glad to reopen it. Thanks!

Tested with:

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
Twenty Twenty-Two 1.2
