### ISSUE TITLE
Combined wp-components JS/CSS add unnecessary delays

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#28797]
## What problem does this address?

When a plugin wants to use a component like `<Button>`, they have to enqueue the entire `wp-components` JS and CSS dependencies. 

Those files are huge -- _670k and 108k minified on disk!_ -- and I'm guessing that most of the contents aren't even used in most cases. 

In the plugin I'm currently working on, I'm using `Button, Card, CardHeader, CardBody, Icon, Notice, RangeControl, Spinner, Tooltip`, and Chrome dev tools says that 64% of the JS and 98% of the CSS are unused.

## What is your proposed solution?

The existing combined files would need to continue existing for back-compat, but we could distribute additional files for the  individual modules, like `wp-components-button`, so plugins can enqueue only what they need.

In the case of JS, that would also set the stage for a future enhancement that would allow individual components to be imported as ES modules.

## Alternative solution

There could also be a middle ground, where related components are grouped together, like "input" (for `Textarea`, `FormToggle`, etc), "inspector" (for `Panel*`), "colors", "icons", etc.

That might be more convenient to maintain and use, and wouldn't add too much unnecessary code. If you're using `Card`, then you'll be using `CardBody` most of the time too.

## Downsides

Having both `wp-components` and `wp-components-*` files will sometimes create a situation where plugin `A` is enqueueing `wp-components-button`, but plugin `B` is enqueueing the entire `wp-components`, making the situation even worse than before.

I'm guessing that things would still be faster on the whole, though, since many plugins only load on individual screens.

We could mitigate the impact by calling a `_deprecated_dependency()` function (similar to `_deprecated_function()` when the combined asset is enqueued.

**Comment by iandunn** [comment]
Actually, `WP_Scripts` could detect if one plugin is enqueueing `wp-components-button` and another plugin is enqueueing all of `wp-components`. If that happens, then it could just ignore the `wp-components-button` request and serve the entire bundle.

**Comment by gziolo** [comment]
It's very similar to what @nerrad propsoed in https://github.com/WordPress/gutenberg/issues/28797. Should we consolidate?

**Comment by nerrad** [comment]
I _think_ you meant #17079 @gziolo?

**Comment by iandunn** [comment]
That sounds good, thanks for pointing it out 👍🏻
