### ISSUE TITLE
Enable template part specific block patterns.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#28802]
## What problem does this address?

As noted in https://github.com/WordPress/gutenberg/issues/27337 - we should enable special block patterns that only show up when specific template part types are selected (such as header or footer).

Also related to - https://github.com/WordPress/gutenberg/issues/27575

## What is your proposed solution?

Once https://github.com/WordPress/gutenberg/pull/28410 lands, we should have a way to distinguish what section type a template part corresponds to.  This should open up the ability to link block patterns to them.

**Comment by david-szabo97** [comment]
I wonder what would be the best way to tackle this implementation-wise. Should we add a filter and use that to manipulate the patterns array in the `usePatternsState` hook?
https://github.com/WordPress/gutenberg/blob/6d3c4b3ad825e96beac333f7d466fb349f37827e/packages/block-editor/src/components/inserter/hooks/use-patterns-state.js#L35

What should happen to template part-specific block patterns? Should they appear on top of the list? Or a bit separated from the others? 🤔 @jameskoster What do you think? Do we have a mock-up for this?

**Comment by jameskoster** [comment]
> What do you think? Do we have a mock-up for this?

There are some ideas over in #28737 for on-canvas pattern suggestions. Inserter changes will be explored in #28739.

**Comment by Addison-Stavlo** [comment]
I think a good first step for this would be to find a way to enable this 'recommendation' in the existing UI.  That is, when we are selected inside a template part the normal sidebar patterns inserter should show patterns corresponding to template parts of that 'area' as the first results.  This will allow us to have a better technical understanding of what we need in place and how to best enable this recommendation feature (what filters, hooks, data structures, etc. make the most sense to enable this).

That exploration should make creating 'new UI' areas specifically for recommendations easier to implement once those designs are more finalized and ready to be created.

**Comment by Addison-Stavlo** [comment]
> What should happen to template part-specific block patterns? Should they appear on top of the list? Or a bit separated from the others?

I wonder if we could conditionally add an item to this dropdown in that case.  If a header is selected (and header patterns exist), have a 'header' option in this dropdown and have the patterns inserter default to that when it opens:

![Screen Shot 2021-02-22 at 4 15 02 PM](https://user-images.githubusercontent.com/28742426/108771255-6693c000-7529-11eb-897d-7727233ed931.png)

**Comment by Addison-Stavlo** [comment]
> I wonder if we could conditionally add an item to this dropdown in that case.

We hacked up a quick PR to see what that would feel like - https://github.com/WordPress/gutenberg/pull/29595 just to test.  But the current inserting behavior of appending beneath the currently selected block makes it feel quite clunky though. 🤔

**Comment by Addison-Stavlo** [comment]
Closing this as we have used the `blockTypes` array in pattern registration to link template part variations to patterns. https://github.com/WordPress/gutenberg/pull/31155
