### ISSUE TITLE
broken reusable blocks

### ISSUE THREAD

**Issue by worldofwyld** [WordPress/gutenberg#28803]
We have a number of reusable blocks that keep popping up as broken, we also are experiencing a certain amount of blocks that are becoming groups in the editor. Has anyone else had any of these problems?

**Comment by talldan** [comment]
@worldofwyld This seems like a question that would be best asked on the WordPress forums - https://wordpress.org/support/forums/.

If you'd like to submit a bug report, please could you use the issue templates. I'd also recommend searching to see whether anyone else has created a similar issue.

**Comment by MickeyMick00** [comment]
Same here , afterall reusable blocks are not usable at all.
