### ISSUE TITLE
Wordpress inadvertantly publishes article when specific error presents

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#28805]
## Description
Wordpress.com unexpectedly and immediately publishes article after error is presented... even when scheduling and other metadata is assigned.

## Step-by-step reproduction instructions
I do not have a means to absolutely reproduce this issue. However, the best I can offer is a the tenuous set of circumstances to when it occurs. Note, I have had this issue occur at least 3 times on 3 different articles.

1. Edit an article in Gutenberg
2. Leave the article editor open in your browser for an extended period of time (at least a day)
3. After at least 24 hours have elapsed, attempt to add one or more new categories
4. Add key words to the article
5. Set a featured image
6. Set a scheduled date and time
7. Click schedule

At this point after clicking 'Schedule', I receive a red error panel that says something like "unable to assign requested terms". This error panel remains consistent with each _schedule_ button press.

## Expected behaviour
The schedule button shouldn't do ANYTHING to a post if any red error presents. All errors of any type should **_always_** prevent publishing an article until the error is cleared.

## Actual behaviour
What I've come to find is that when this error panel presents, Wordpress has actually immediately published the article ignoring the scheduling, ignoring category assignments, ignoring key word additions and ignoring pretty much all other metadata that's been set on the article in the right side panel. This bug also follows through by publishing the article to Twitter (and other social networks) if linked.

I've also found that the article metadata editor becomes unresponsive in places (i.e., you can't click on much of the metadata area and have it respond). I've found that to solve this unresponsiveness problem, I have to close out of the browser tab entirely, reload the entire article editor in a brand new browser tab, change the article back to draft and go to Twitter and remove the Twitter post.

Oh, I forgot to mention that after opening a new browser tab, almost all of the assigned metadata has been lost, with the exception of the created categories which appear to have been successfully created, but they are no longer assigned to the article.

I've found no workaround to this issue as there's no way to know when it might present.

This is a pretty huge and serious bug.

## Screenshots or screen recording (optional)
Screenshots not easily possible because of the difficulty of reproducing.

## Code snippet (optional)
N/A

## WordPress information
- WordPress version: Wordpress.com
- Gutenberg version: Wordpress.com
- Are all plugins except Gutenberg deactivated? Unknown
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: MacOS X Mojave 10.14.6
- Browser: Firefox 85.0

**Comment by talldan** [comment]
> Wordpress.com unexpectedly and immediately publishes article after error is presented...

@commorancy This is a project managed by the open source WordPress foundation. This isn't the place to raise WordPress.com issues. Please reach out to WordPress.com support.

I believe I've mentioned this to you before, please take the advice this time

**Comment by commorancy** [comment]
@talldan This is a Gutenberg issue. Did you even bother to read the bug report?

**Comment by talldan** [comment]
@commorancy As a user, WordPress.com support should still be your port of call if you are experiencing a bug with WordPress.com.

WordPress.com is a commercial project by Automattic, contributors to the open source WordPress foundation projects may not be employed by Automattic and so do not support it.

While WordPress.com uses the Gutenberg as an editor, it does so as any commercial software project might use any open source software. You cannot ask contributors here to subscribe to WordPress.com in order to try to reproduce this issue.

Now if WordPress.com support manage to discover that the bug does lie in Gutenberg, they may report it to us with details of their findings.

Does that make sense?

**Comment by commorancy** [comment]
I have been repeatedly told multiple times by multiple Wordpress.com representatives to report Gutenberg bugs directly to this Github project and not report them to the Wordpress.com's support team. Now, since you're telling me to go over there and they're telling me to come over here, you've got a bigger problem to work out. You'll need to work that logistical problem out between Wordpress Foundation and Wordpress.com. I don't work for any portion of Wordpress at all, I just use the product.

Since you guys can't work out a functional method for users to report bugs, I have no intention of reporting any further bugs anywhere. It's not my job to fix any of Wordpress's pass-the-bug-report problems.

Now, since you don't value that we users are spending valuable time coming here to report bugs, I have no intention of spending even one more minute here reporting bugs or in playing your inane pass-the-buck games. The buck (or bug) has to stop somewhere, but since no one really seems to care that they exist, I don't either.

**Comment by talldan** [comment]
@commorancy I'm sorry, I didn't realise you were being asked to report bugs here. I can understand why you're frustrated now, so apologies if I wasn't understanding before.

It's disappointing, I would've expected that the support staff would help diagnose issues and pass onto the necessary technical staff themselves.

**Comment by commorancy** [comment]
Again, what you suggest is a type of bug reporting workflow that the Wordpress Foundation and Wordpress.com need to explicitly work out and agree to. If this Github project is closed but to only Wordpress.com and Wordpress Foundation staff bug reporting, then this Github project needs to be set up in this way. After being setup, Wordpress.com then reports its Gutenberg bugs directly to you through Wordpress.com staff channels directly.

Part of the problem with Wordpress.com support is that it is manned by volunteers who appear to be free to choose whatever method best serves the situation, including them sending the person directly to Github to report bugs. If that's not the desired method to collect bug reports, see the first paragraph above for a functional design approach.

I've already spent way too much time designing a workflow system for you, so I'll leave it here.

**Comment by talldan** [comment]
@commorancy It isn't manned by volunteers, should all be paid staff. Out of interest, where are you going to report issues?

**Comment by commorancy** [comment]
I'm not planning to report any further bugs for any Wordpress projects. Not to Wordpress.com, not to Wordpress Foundation. You'll have to uncover the bugs on your own.
