### ISSUE TITLE
Down arrow should not be rendered on SelectControl when multiple = false

### ISSUE THREAD

**Issue by JohnRDOrazio** [WordPress/gutenberg#28818]
## Description
A down arrow / chevron is rendered on all SelectControl components, whether or not the `multiple` property / attribute is set to `true`. It should not be needed when `multiple:true` because there is no dropdown in this case.

## Step-by-step reproduction instructions

Create a SelectControl component, and set the `multiple` property to true.

## Expected behaviour
No down arrow should be rendered.

## Actual behaviour
A down arrow is rendered.

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.0
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: 
- Operating system: 
- Browser: 

I created PR #28817 to fix this. (not tested, needs review and testing)

**Comment by talldan** [comment]
This is easy to reproduce in the storybook - https://wordpress.github.io/gutenberg/?path=/story/components-selectcontrol--default.

**Comment by talldan** [comment]
I see this is already tracked in https://github.com/WordPress/gutenberg/issues/27166, so will consolidate the issues by closing this as a duplicate.
