### ISSUE TITLE
README for the SelectControl component confusing when it comes to multiple attribute

### ISSUE THREAD

**Issue by JohnRDOrazio** [WordPress/gutenberg#28812]
The README for the SelectControl component contemplates the possibility of using the `multiple` attribute on the component, allowing for multiple selections from the list.
However, the README also states a number of times that the component should only be used for a single selection from a list.
This can be confusing.
PR #28811 fixes the wording to foresee cases of either single or multiple selection from the component's list of options.

**Comment by mkaz** [comment]
Closed in #28811
