### ISSUE TITLE
Make Transformer more consistent between various text blocks

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2881]
## Issue Overview
The Transformer drop-down is a "surprise button". It's like a box of chocolates... you never know what you're going to get.

## Expected Behavior
As a user, I expect the Transformer to work in similar ways between blocks.

## Current Behavior
It feels a bit random:
* When you are in a Paragraph you can transform it into a Heading, Quote, List, Preformatted or Verse.
* When you are in a List, you can transform it into a Paragraph or Quote.
* When you are in a Heading you can transform it into a Quote or a Paragraph (note different order)
* When you are in a Quote you can transform it into a List, Paragraph or Heading.

Even if we get more transformations implemented (which I presume we will), there are some small changes that would make it behave more like a Styles dropdown and thus be much more intuitive to your average user.

## Possible Solution
a) expand the list of possible transformations on each block... particularly for text blocks
b) always have the transformations in the same, consistent order

**Comment by androb** [comment]
Rough mock-up:
![image](https://user-images.githubusercontent.com/2160304/31255807-a4907a0c-a9e3-11e7-9690-9ca56dfd1914.png)

**Comment by androb** [comment]
Rough sketch

![image](https://user-images.githubusercontent.com/2160304/31255927-5973ffac-a9e4-11e7-8d18-1c7010a4ccf2.png)

**Comment by androb** [comment]
Updated this issue to be more single purpose.

**Comment by jasmussen** [comment]
Since October, lots of changes have happened to the editor, and transforming blocks using the switcher hasn't come up a ton in feedback. Given that it's easy to reopen tickets if they become pressing, I'm going to close this one for now, and revisit if the issue comes up.
