### ISSUE TITLE
FSE: Template parts included in template parts are not found

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28814]
## Description

When a template part includes another template part, the "Template part not found" message is displayed on the front.

In the site editor, the template part is visible as an empty selectable template part block. There is no content in the template part. The console shows:
```
index.php?rest_route=%2Fwp%2Fv2%2Ftemplate-parts%2Fundefined%2F%2Fmeta&context=edit&_locale=user:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.php:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

The template part slug is meta:
https://github.com/WordPress/theme-experiments/pull/199/files#diff-655c9902613a59b3d9282cbfcc4a4efbd7dec8dd16a77b0911a0a0bbf181e297L3

The theme folder is in the  wp-content/themes/ folder, not a subfolder.
If I add the theme attribute to the template part, the template part works as expected.

## Step-by-step reproduction instructions
1. Activate a full site editing theme that has been updated to work with 9.9.0, or you can try Armando from the theme experiments repo.
2. Add a template part inside a template part.
3. View the template in the site editor, see that the template part is empty.
4. View the template on the front, see the error message.

## Expected behaviour

I expect the template part to display without errors.

## Actual behaviour

The template part is not found.

## Screenshots or screen recording (optional)

Site editor, template part without content:
![template part](https://user-images.githubusercontent.com/7422055/107148581-46bea280-6954-11eb-939f-d636ac981a4d.png)

## WordPress information
- WordPress version: WordPress 5.7 Beta 1.
- Gutenberg version: Tested with 9.9.0 and current master.
- Are all plugins except Gutenberg deactivated?  No, the beta tester plugin is installed
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Armando: 
https://github.com/WordPress/theme-experiments/pull/199/files#diff-655c9902613a59b3d9282cbfcc4a4efbd7dec8dd16a77b0911a0a0bbf181e297L3

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 88.0.4324.150

**Comment by annezazu** [comment]
@Addison-Stavlo flagging for you as you helped with some template part oddness previously!

**Comment by Addison-Stavlo** [comment]
It looks like this works for saved / CPT template parts, and the issue seems to be with file based / theme supplied ones.

This could be a side effect of when we moved away from using auto-drafts to just loading from the file directly.  cc @youknowriad

**Comment by youknowriad** [comment]
First question that come to my mind is whether we need to support this or not.

Other than that, it seems related to the behavior we added to automatically set the "theme" attribute for template-parts somehow. cc @david-szabo97

**Comment by david-szabo97** [comment]
It would make sense to support nested template parts. I'll look into this soon. So far I noticed `meta` template parts doesn't even show up in the template parts menu. And when I try to open `content-single` then the editor freezes.

**Comment by david-szabo97** [comment]
We are only injecting theme attribute into `wp_template` content.

https://github.com/WordPress/gutenberg/blob/1a29dbdecb6222a62ff66fa1eb5e3bb66ede44a4/lib/full-site-editing/block-templates.php#L187-L189

@jeyip Was there any particular reason to only run this for templates and not template parts? IMO, it makes sense to nest template parts in template parts.

**Comment by david-szabo97** [comment]
Here is a PR that fixes the looping issue: https://github.com/WordPress/gutenberg/pull/29041

Let's wait for more feedback regarding why the `theme` attribute is not injected into template parts.

**Comment by Addison-Stavlo** [comment]
> We are only injecting theme attribute into wp_template content.
> Let's wait for more feedback regarding why the theme attribute is not injected into template parts.

Oh!  That makes sense.  I think this is an oversight and we need to check template parts for injecting this attribute as well in order to support nested template parts from themes.

Im assuming the reason we only parse template files for injecting the attribute is that in the **general** case that is where the template part block declarations live (while their content is contained in the file).  For a nested template part, its block declaration could be in a template part file, so it would make sense to also check template part files for nested template part block declarations in order to inject this theme attribute if necessary.

**Comment by david-szabo97** [comment]
Just opened a PR to enable the injection for template parts too. I couldn't find any hiccups by removing the check. Let's see how the tests react and I'm still looking forward @jeyip 's response.

**Comment by jeyip** [comment]
> IIRC the reason we only parse template files for injecting the attribute is that in the general case that is where the template part block declarations live (while their content is contained in the file)

@Addison-Stavlo has it spot-on. Defining theme attributes in theme-provided template part files (for nested template parts) is a use-case we didn't account for.

https://github.com/WordPress/gutenberg/pull/29080 looks good to me. +1 from me after I spin up an instance with the Armando theme to see the use case for nested template parts.

**Comment by youknowriad** [comment]
I haven't been able to follow here but that's all for your work solving this.

**Comment by jeyip** [comment]
@carolinan https://github.com/WordPress/gutenberg/pull/29080 should solve the problems you were seeing with nested template parts in the Armando theme. Feel free to reopen the issue if things still aren't working as expected

**Comment by carolinan** [comment]
It has stopped working again. It does not work with the 10.1 RC1 zip or current master (at https://github.com/WordPress/gutenberg/commit/da8555d258edbe676fa079fb51252f918ae032e1).

**Comment by annezazu** [comment]
Can confirm on my test site as well.

**Comment by jeyip** [comment]
Quick update -- this is in Cylon's backlog and we're aware of the issue. To set expectations, it might take us a little while to investigate this more.

I'll try and pick this up again when I have free time, and will update this issue when I do.

**Comment by youknowriad** [comment]
@jeyip What is Cylon? ;)

**Comment by jeyip** [comment]
@youknowriad Ah thanks for catching that 😅 Corrected the language in my comment, but left the intention the same.

**Comment by Addison-Stavlo** [comment]
I just tested this out on the current trunk branch for gutenberg + `update/armando` branch for themes-experiments.

I insert the 'content-single' template part on a page, and the internal template part 'meta' renders as expected:

![Screen Shot 2021-03-09 at 5 49 31 PM](https://user-images.githubusercontent.com/28742426/110549395-fd52a600-80ff-11eb-8743-8cb8941e252b.png)

Its not in the context of a post, so the placeholders are expected.  But more importantly it seems the template part block itself is not errored or broken. 🤔

**Comment by carolinan** [comment]
The theme attribute is injected here:
https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/block-templates.php#L148

But it is only injected if the parent block is the template part. It does not check if the template part is an inner block / child block.

Here is how far I got:
https://gist.github.com/carolinan/d71b683026647d6a30b2ca07f2d3d9fc#file-gistfile1-txt-L155

**Comment by MaggieCabrera** [comment]
This is happening for me when the template part is inside a group block (it's not inside another template part): https://github.com/Automattic/themes/pull/3592/files#r604835733

**Comment by david-szabo97** [comment]
Working on it 👍
