### ISSUE TITLE
Experimental-theme.json: Move pageTemplates to settings

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28810]
## What problem does this address?

With the update to theme.json, there are two new sections: settings and styles.
But pageTemplates is also on the root level, _-not to be confused with the root block selector:_

```
{
	"settings": {
	},
	"styles": {
	},
	"pageTemplates": {
	}
}

```
## What is your proposed solution?

Because the settings section configures the editor,
it would make sense to move pageTemplates to settings.

**Comment by carolinan** [comment]
Might as well update the name at the same time: 
https://github.com/WordPress/gutenberg/pull/28783#discussion_r570935335

**Comment by nosolosw** [comment]
:wave: The way I see this, `settings` and `styles` configure blocks, not the editor ― hence, why they have `core/paragraph`, `core/group`, etc as subkeys.

I think it makes sense to me adding the othe theme metadata as top-level keys. Said this, I'm not sure whether `pageTemplates` should be its own key or bundled together with other data about templates, etc. Haven't looked deeply into it, so I'll leave others to comment.

**Comment by carolinan** [comment]
Got it, it made sense to me to have settings in the same place, because I read the docs as if there were only two main sections.

But I don't feel strongly about it and I see that the docs were updated to indicate this 20 hours ago: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-json.md

**Comment by lukecarbis** [comment]
I like the idea of including a third root key called something like `theme` or `meta` which contains `pageTemplates` as a subkey.
