### ISSUE TITLE
Table Block: Remove hard coded style from table cells

### ISSUE THREAD

**Issue by Intervik** [WordPress/gutenberg#28819]
## What problem does this address?
Styling tables for backend are limited by the style="white-space: pre-wrap" added by editor on table column elements. If the values where applied from stylesheet, we dont need the use of !important. When stylesheets are shared by the front end, aggersive values is not recommended, not allowed in envireoments such as Google news

## What is your proposed solution?
Use stylesheets, stop adding inline styles on elements that not part of the editor GUI, or in use on front end. We cant keep on making 2 versions all the time, as long as Gutenberg doesnot separate the context in back-end.

**Comment by talldan** [comment]
@Intervik This is added by the RichText component, which is the editor's way of handling `contenteditable`. You'll also see it on the paragraph block as well as other blocks. Removing it would cause the problems described here:
https://github.com/WordPress/gutenberg/blob/68237f674078fbc47fcfbbc8b5de30e479f4e344/packages/rich-text/src/component/index.js#L62-L82

I don't think there's a way to safely move this to a stylesheet, so will close the issue.

**Comment by Intervik** [comment]
So the answer is that styling tables with fundamentional CSS on table cells can not be done in Gutenberg. White space in tables are important property when control the tabular content in a document. The problem described in index.js can be solved by cleaning up by script, as the block is re-rendering all the time in Gutenberg.

**Comment by talldan** [comment]
I think the code comment I shared is clear in mentioning that this is the recommended approach within the HTML spec. You could always take your comments to the WHATWG if you disagree with that.

> The problem described in index.js can be solved by cleaning up by script, as the block is re-rendering all the time in Gutenberg.
Not sure what you mean by 're-rendering', that seems unrelated to white space in a contenteditable.

**Comment by Intervik** [comment]
re-rendering is that when you click on a block to edit, the interfce is loading by script, on blur/ focus of the block etc, done by script. So, right now we hack on blur, after gutenberg render the block, to remove the style attribute. "is the recommended approach within the HTML spec." - why dont y keep the style attribute on front end then?

**Comment by talldan** [comment]
> why dont y keep the style attribute on front end then?

Because the front-end isn't a contenteditable element.

**Comment by Intervik** [comment]
An editor should not have one "approach" for the results when editing, and another "approach" for final presentation. If the edit contenteditable elements doesnt support consistance, a good idea is to solve with a checkup - in this case problems described in the section you refer to - with cleaning up script with react. So, still, the answer is that styling table layout (cells) white space properties can not be done in Gutenberg as it uses contenteditable for the table-block, and this is a compromise becouse of the lack of constistnace in browser handling of contenteditable functionalities?
