### ISSUE TITLE
Clicking a latched list button should convert it to a paragraph block

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2882]
## Issue Overview
As a user, I expect to be able to click on a list button that is latched/selected and have it convert back to a paragraph

## Steps to Reproduce (for bugs)
1. Focus on an ordered or unordered list item 
2. (The relevant list button will be selected)
2. Click the list button

## Expected Behavior
The list item to be converted to a paragraph as this is what happens in word processors.

## Current Behavior
Nothing

## Possible Solution
Convert the list item to a paragraph

**Comment by karmatosed** [comment]
As we can do this, I am closing this for now.

![2018-01-03 at 19 09](https://user-images.githubusercontent.com/253067/34535449-b623e80e-f0b9-11e7-964f-0aca3b90795e.png)
