### ISSUE TITLE
Block preview when adding a block is not working in WordPress 5.6.1

### ISSUE THREAD

**Issue by blankart** [WordPress/gutenberg#28823]
## Description

Block preview when adding a block is not working in WordPress 5.6.1

## Step-by-step reproduction instructions

Click the "add block" button. Hover one of the block entry buttons.

## Expected behaviour

A popover with block preview should be visible

## Actual behaviour

The popover is not visible

## Screenshots or screen recording (optional)

![Screen Shot 2021-02-08 at 10 29 53 AM](https://user-images.githubusercontent.com/24480990/107169355-9bb3f480-69f8-11eb-8385-eaeff8efc5fe.png)

## WordPress information
- WordPress version:  5.6.1
- Gutenberg version:  Not installed
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Desktop
- Operating system:  MacOS Big Sur
- Browser:  Chrome

**Comment by paaljoachim** [comment]
Thank you for the report @blankart 

Testing. 
Theme: Twenty Twenty One.
WordPress version: 5.6.1
No plugins activated.
Chrome
Mac OSX 10.15.7 (Catalina)

I open an existing page (draft).
![No-preview-blocks](https://user-images.githubusercontent.com/5323259/107215945-54376380-6a0c-11eb-8fbd-e7675fbb0b57.gif)

Twenty Nineteen and Twenty Twenty theme also contains the same lack of block preview error.
The same as with TT1 theme.
Tested with estar theme. Same error.

-----------

Activating the Gutenberg plugin 9.9.1 the Block preview works.

![Screen Shot 2021-02-08 at 12 56 41](https://user-images.githubusercontent.com/5323259/107216500-243c9000-6a0d-11eb-89d0-64d8787e57f7.png)

--------

Testing 5.6 version of WordPress.
No plugins activated.

![Screen Shot 2021-02-08 at 13 00 48](https://user-images.githubusercontent.com/5323259/107216891-b47ad500-6a0d-11eb-8823-e8a66fcc905c.png)

Block preview works in 5.6.

---------

My conclusion is that the 5.6.1 update has caused an error so that Block previews are not seen.

**Comment by noisysocks** [comment]
@paaljoachim: Could you confirm if this happens in 5.7 beta 1?

**Comment by paaljoachim** [comment]
Good call, Robert!
@noisysocks 

Testing.
Theme: Twenty Twenty One.
WordPress version: 5.7 beta 1
Only the WordPress Beta Tester plugin is activated.
Chrome
Mac OSX 10.15.7 (Catalina)

Opening Sample Page. Changed it to a draft.
Block previews work fine in 5.7 beta 1.

![Block-preview-5-7-beta1](https://user-images.githubusercontent.com/5323259/107333937-653caf00-6ab6-11eb-8a04-78991a943136.gif)

Tested:
Existing page and post.
New page and post.
Draft page and post.
Block preview works nicely.

**Comment by tobiasger** [comment]
I'm having the same issue with Wordpress Version 5.6.1.

**Comment by bobbingwide** [comment]
Ditto. But shouldn't there be a TRAC issue since this problem occurs when Gutenberg is **not** activated.

**Comment by paaljoachim** [comment]
Hi Riad and Greg. I am just informing you about this issue.

@youknowriad @gziolo

**Comment by youknowriad** [comment]
Do we know if there will be a 5.6.2 before 5.7. It's not clear at this point? and this is already fixed ini 5.7 so.
It would also be good to try to find what fixed this issue.

**Comment by paaljoachim** [comment]
There are talks about a 5.6.2 release before the release of 5.7. 
I asked in core for an official P2 post about this release.

**Comment by desrosj** [comment]
I'm working on preparing a 5.6.2 RC, and hoping to get that out at some point today (the 16th). Has anyone been able to locate the change that fixed this issue? I'll take a look, but without being able to find that, we may have to skip this one in 5.6.2.

**Comment by ockham** [comment]
@desrosj The [`wp/5.6` branch](https://github.com/WordPress/gutenberg/commits/wp/5.6) has a list of commits that should allow narrowing the search down (as to what _broke_ block preview). Given the release dates of WP 5.6.1 (Feb 3) and 5.6.0 (Dec 8), I believe that that commit must be one of the top 8 ones that were apparently cherry-picked on Jan 28.

**Comment by ockham** [comment]
#26432 seems like a likely candidate; #26583's PR desc says

> The fix in #26432 accidentally broke block previews in the Inserter due to a naïve use of `overflow: hidden` to fix the overscroll with the block library open in the site editor.

While it only refers to the site editor (and not the post editor), the files that it touches seem editor agnostic.

cc/ @mattwiebe for confirmation :blush: 

Maybe someone (@desrosj or @paaljoachim? :pray: ) could give this a try. (It's a bit late here, I'm already after hours :wink: )

**Comment by desrosj** [comment]
Thanks for the assist, @ockham! #26583 does indeed restore the previews in the 5.6 branch! I've gone ahead and added that to #29042.

**Comment by tellthemachines** [comment]
I just tested #26583 on the 5.6 branch and it works well, though I see @desrosj beat me to it 😄

**Comment by ockham** [comment]
Filed https://github.com/WordPress/gutenberg/issues/29073 to request an e2e test for block preview visibility.

**Comment by desrosj** [comment]
This was merged in #29058 and will be shipped in the upcoming 5.6.2.

**Comment by mattwiebe** [comment]
> While it only refers to the site editor (and not the post editor), the files that it touches seem editor agnostic

Yes, you are correct, this touched the interface skeleton that is used to construct both post and site editors.
