### ISSUE TITLE
Sibling Inserter: Broken positioning on Site Editor

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28827]
The sibling inserter shows up when you hover between two blocks, whether in the post or site editor:

![before-commit](https://user-images.githubusercontent.com/1204802/107197273-f9920d80-69f3-11eb-9868-5961c0cf6948.gif)

This still works fine on the post editor, but regressed on the site editor, where it's offset about 60px upwards:

![after commit](https://user-images.githubusercontent.com/1204802/107197313-06166600-69f4-11eb-9efe-1d03540a7338.gif)

The precise amount of vertical offset does not appear to be constant, and appears to depend on which blocks are present on the page. With a few cover and spacer blocks, it's very offset. With just paragraphs, it's almost correct.

In trying to figure out how this regressed, I walked back in time on the commits page (https://github.com/WordPress/gutenberg/commits/master?before=e843e5484e2087d1ef546564c09254cc60dc5170+230&branch=master), and from this digging (I really need to learn to bisect), this appears to have been caused by #27860.

**Comment by youknowriad** [comment]
Is it the same as ##28457 ?

**Comment by jasmussen** [comment]
It is. My apologies!

**Comment by youknowriad** [comment]
No worries, just saw it mentioned in a potential PR that can fix it.
