### ISSUE TITLE
Add subject to "mailto:" links

### ISSUE THREAD

**Issue by EricDu** [WordPress/gutenberg#28850]
## What problem does this address?
Add a subject line to emails to more easily filter submissions by subject.

## What is your proposed solution?
Add a "more options" drop-down to the email link dialog box. That would expose a subject field. It could also include body, cc and bcc for additional customization.
On confirming the link, it would be sanitized ("?" and "&" added, spaces replaced by %20, etc.).

**Comment by Quintis1212** [comment]
Hello ) I can implement this enhancement )

**Comment by getdave** [comment]
Thanks for raising.

This feels like a fairly specific enhancement. I wonder if this is best left to be plugin territory. 

Interested in more opinions.

**Comment by richtabor** [comment]
> This feels like a fairly specific enhancement. I wonder if this is best left to be plugin territory.

I agree. I don't think this should be a core feature, but would make a nifty small plugin.
