### ISSUE TITLE
Expose block structure

### ISSUE THREAD

**Issue by EricDu** [WordPress/gutenberg#28852]
## What problem does this address?
It is often difficult to know where one block ends and the other begins, especially when working with columns or nested blocks.

## What is your proposed solution?
I usually use something like the following in my theme's editor styles to expose the block structure in a subtle way:
`.wp-block {
  padding: 2px;
  border: 1px dotted #eee;
}
.wp-block.is-hovered {
  border: 1px dotted #ccc;
}
.wp-block.is-selected {
  border: 1px dotted #888;
}`
My suggestion is to add an option to Gutenberg for "Show block structure" with 3 possible values: none (default), subtle, and strong.

Selecting one of the visible option would add a class to the block editor and CSS similar to what I'm currently using (but more thorough to account for different block types) would be applied.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. I personally encounter this as well and use the `block outlines` feature in the editorskit plugin. 
There's a couple different issues related to this that have requested this to be built into Gutenberg: https://github.com/WordPress/gutenberg/issues/22383 , https://github.com/WordPress/gutenberg/issues/25133, and https://github.com/WordPress/gutenberg/issues/23892 

You can follow their progress by subscribing to those issues. If you feel that this issue isn't covered by one of those issues, please reopen.
