### ISSUE TITLE
Cover Block: Make Focus Settings Image-Specific

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28859]
## What problem does this address?

Focus settings for background images are not currently image-specific. When creating patterns that use focus settings in a background image the "cropping" of an image may appear confusing to users who have not yet encountered this block setting.

![2021-02-08 14 45 55](https://user-images.githubusercontent.com/545779/107279932-4b9b5900-6a1d-11eb-8f56-db09ccce303e.gif)

## What is your proposed solution?

It may make sense to make focus settings specific to an image and reset to a neutral position when a new image is uploaded. This appears to already be what happens when one _removes_ media from a cover block and _then_ re-adds media.

**Comment by Quintis1212** [comment]
Hello  ) I think I can implement this enhancement ) see you soon here )

**Comment by Quintis1212** [comment]
Hello ) I make enhancement  for this issue ) checkout it here - https://github.com/WordPress/gutenberg/pull/29231

**Comment by paulopmt1** [comment]
Thank you for reviewing and merging it, @stokesman and @Mamaduka!
