### ISSUE TITLE
Navigation Screen: Update Navigation block inspector

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28864]
On the Navigation Screen, the Navigation block's sidebar inspector includes controls for auto-adding new pages and deleting the menu. Here's how it looks now:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/191598/107290754-1864c400-6a35-11eb-9ab2-0d56e0604ba7.png">

I think we should improve the display of the auto-add option and the delete button, along with adding theme locations. Here's an updated design:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/191598/107290938-611c7d00-6a35-11eb-8b8a-d359b34f6b18.png">

The new "Theme locations" accordion allows you to choose where the current menu will appear. Clicking the "Manage locations" button opens a modal that allows you to choose a menu for all theme locations at the same time. Each location allows you to either choose an existing menu, edit an existing menu, create a new menu, or select no menu. Here's a look at how it could work:

![Manage Locations](https://user-images.githubusercontent.com/191598/107291242-dd16c500-6a35-11eb-9ab3-e4a336cad636.gif)

**Comment by talldan** [comment]
This is a really nice improvement. 👏 

If there's already a menu assigned to one of the locations, do you think we need to inform the user that using the checkbox in the sidebar would overwrite the previous assignment?

**Comment by shaunandrews** [comment]
> If there's already a menu assigned to one of the locations, do you think we need to inform the user that using the checkbox in the sidebar would overwrite the previous assignment?

Perhaps we can take a cue from the existing Menu's screen, and add a byline to areas that already have an assigned menu:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/191598/107562003-3f460600-6bad-11eb-891a-ad3b29f69318.png">

**Comment by shaunandrews** [comment]
It seems ([for the time being, at least](https://github.com/WordPress/gutenberg/pull/29012#discussion_r576741369)) we'll also add the menu name as an input to the sidebar. Here's how that could look:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/191598/108114505-e40d8b00-7066-11eb-86e2-08d2da8f5a45.png">

The block toolbar could still display the menu's name, and when clicked could highlight the input in the sidebar:

![Click Menu Name to Focus Input](https://user-images.githubusercontent.com/191598/108115212-cdb3ff00-7067-11eb-948f-7c222b37071a.gif)
