### ISSUE TITLE
Navigation Block: Missing "Insert Before/After" options in more menu

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28865]
When a link block is selected, I normally expect to see options to insert a block before or after, but I don't see it on the Navigation block:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/191598/107293517-ba86ab00-6a39-11eb-979f-601e01683d82.png">

Other blocks have these option, like the Paragraph block:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/191598/107293584-e3a73b80-6a39-11eb-9a1b-9179dfa8b5ec.png">

**Comment by talldan** [comment]
Lets move #23603 onto the navigation project board to track this, your suggestion there sounds like a good thing to explore.
