### ISSUE TITLE
Navigation Screen: Combine Menu Switcher with Add Menu

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28863]
The new Navigation screen currently has buttons at the top to switch menu and to create a new menu:

![Select Menu and Add New](https://user-images.githubusercontent.com/191598/107289351-e3f00880-6a32-11eb-8549-7b480a254db0.gif)

I think it makes sense to combine these into a single menu:

![Switch Menu](https://user-images.githubusercontent.com/191598/107289642-55c85200-6a33-11eb-9dae-8cc88392519f.gif)

Creating a new menu opens a modal with an input to give the new menu a name.

--

For longer lists of menus, or menu names that wrap, the switcher should adjust:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/191598/107290384-6fb66480-6a34-11eb-9287-669faff030b3.png">

**Comment by paaljoachim** [comment]
Having 3 text links and then a button has a visual clutter to it.
-
Having a Switch menu showing the various menus and a "Create new menu" on the bottom feels tighter and easier to relate to. If a user has not created a new it might be a bit confusing to see the Switch menu drop down and the Save menu button. As the user might not know where to click to create the first menu.

**Comment by shaunandrews** [comment]
The experience of creating a sites first menu is being handled here: https://github.com/WordPress/gutenberg/pull/28767
