### ISSUE TITLE
Block styles not loading in navigation editor when using an FSE theme (e.g. TT1 Blocks)

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28874]
## Description
Block styles don't seem to be loading in the navigation editor when TT1 blocks is used as the theme.

Several issues can be seen, like empty submenus taking up space.

## Step-by-step reproduction instructions
1. Use the theme TT1-Blocks
2. Add multiple links
3. Observe the space between links

## Expected behaviour
There is no empty space

## Actual behaviour
There is empty space

## Screenshot
<img width="445" alt="Screenshot 2021-02-09 at 6 40 50 pm" src="https://user-images.githubusercontent.com/677833/107352193-85945a00-6b06-11eb-824a-18132a98fe63.png">

**Comment by tellthemachines** [comment]
Could this be related to #27995?

**Comment by talldan** [comment]
It seems like none of the block styles are loading in the navigation editor, which also explains why the page list block looks different.

**Comment by talldan** [comment]
Just discovered by complete accident that this bug only happens when TT1-Blocks is the active theme. With regular Twenty Twenty One it works as expected.
