### ISSUE TITLE
Navigation Editor block toolbar disappears on small screen sizes

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28875]
## Description
The navigation editor's block toolbar disappears on small (mobile) screen sizes.

This bug is a result of https://github.com/WordPress/gutenberg/pull/28769, which removed the 'fixed' toolbar. Apparently at small screen sizes the editor should fall back to the fixed toolbar.

## Step-by-step reproduction instructions
1. Open the navigation editor
2. Add some blocks
3. With a block selected, resize the editor to a mobile viewport

## Expected behaviour
The toolbar remains visible and behaves responsively.

## Actual behaviour
The toolbar disappears

## Screenshot
<img width="338" alt="Screenshot 2021-02-09 at 6 49 59 pm" src="https://user-images.githubusercontent.com/677833/107353115-a27d5d00-6b07-11eb-846c-944b9d9f4c9b.png">

**Comment by grzim** [comment]
@talldan can you please confirm the issue is still relevant? I cannot reproduce it

**Comment by talldan** [comment]
@grzim Still seems to be an issue:
![disappearingtoolbar](https://user-images.githubusercontent.com/677833/109130428-aefee800-778c-11eb-8899-f8a99b285d57.gif)
