### ISSUE TITLE
Cover Block: Make it clear that content has not disappeared when the background is removed

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28888]
## What problem does this address?

When content is nested inside a cover block with a background image and the background image is removed it can make it appear as if the nested blocks have "disappeared". Prompting a "where'd my stuff go?" response.

![2021-02-09 09 56 10](https://user-images.githubusercontent.com/545779/107390593-75a45800-6abd-11eb-93fa-e11647cbd6a4.gif)

## What is your proposed solution?

Defaulting instead to a background colour may be more ideal in this case.

**Comment by stokesman** [comment]
Relabeled this as a bug since I think #31253 makes it clear just how confusing this can be.
