### ISSUE TITLE
Embeds are not selectable by mouse after reloading the page

### ISSUE THREAD

**Issue by Azragh** [WordPress/gutenberg#28880]
## Description
If I embed something (tested with Twitter & Youtube) everything works as expected. I can move the embed around, create some other blocks and then click on the embed again to change settings and so on. But if I reload the page with F5 (dev tools open - so caching disabled), I can't select it again by mouse - a blue border appears but no toolbar. If I want to change something, I need to select it in the blocks list (from there on it works again).

## Step-by-step reproduction instructions
1. Create an embed
2. Save post
3. Reload post with caching disabled
4. Try to select the embed by mouse

## Expected behaviour
Embeds should always be selectable by mouse.

## Actual behaviour
Embeds are only selectable by mouse after selecting them in the blocks list. 

## Screenshots or screen recording (optional)
Directly after pasting a URL:

![image](https://user-images.githubusercontent.com/15014142/107364867-494c0400-6adc-11eb-978d-f77d6eb86cca.png)

After reloading page / clicking on the embed:

![image](https://user-images.githubusercontent.com/15014142/107365021-844e3780-6adc-11eb-9125-631ba574d352.png)

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.1
- Are all plugins except Gutenberg deactivated? "Yes" 
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: "Desktop"
- Operating system: "Windows 10" 
- Browser:  "Chrome"

**Comment by ntsekouras** [comment]
Related PR with some more info about the problem: #28658

**Comment by ddryo** [comment]
I can reproduce the same problem.


![wp57-embed-bug](https://user-images.githubusercontent.com/31400297/108035179-edecb980-7079-11eb-899c-0aae0f3d7004.gif)


## WordPress information
WordPress version: 5.6.1 & 5.7 beta-2
Gutenberg version: 9.9.3
Are all plugins except Gutenberg deactivated? "Yes"
Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
Device: "Desktop"
Operating system: MacOS Catalina
Browser: "Chrome"
