### ISSUE TITLE
Double inserter button showing at the end of some block lists

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28907]
## Description
In some block lists (like the navigation block) the trailing appender shows as well as a sibling inserter.

This was introduced by #28418. The solution is probably that the insertion point can be displayed after the last block when hovering over blocks in the block library or quick inserter menu. It shouldn't display when there's a trailing appender already.

## Step-by-step reproduction instructions
1. Add a navigation block
2. Add some menu items
3. Hover around the trailing edge of the last menu item

## Expected behaviour
Only one inserter

## Actual behaviour
It's very insertery

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/107534/106244522-af4ea680-6213-11eb-8525-9991aed82213.mp4

**Comment by jom** [comment]
This seems to happen [also?] with `InnerBlocks` that have its own appender.

<img width="312" alt="Screen Shot 2021-03-10 at 7 30 45 pm" src="https://user-images.githubusercontent.com/68693/110686240-25610880-81d7-11eb-9b88-7a16d510cfeb.png">

**Comment by ocean90** [comment]
Just noticed the same with a custom block with InnerBlocks which only allows one block via `allowedBlocks` and uses `renderAppender: () => <InnerBlocks.ButtonBlockAppender />`. It's also odd that using the additional appender sometimes if not always adds the block to the first position.

@youknowriad Do you have some ideas how we could fix this?

**Comment by talldan** [comment]
#29920 should fix it.

**Comment by ocean90** [comment]
Added to the WordPress 5.7.x project, would be nice to include the fix in a minor update.
