### ISSUE TITLE
"Navigation editor > allows creation of a menu" e2e test failing inconsistently

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28903]
## Description
I've seen this test fail a few times, when it does it involves a timeout on this line:
https://github.com/WordPress/gutenberg/blob/a5eb7fe4084ee410fef22a770f6a36a619775394/packages/e2e-tests/specs/experiments/navigation-editor.test.js#L129

The failure implies the h2 element isn't present, but curiously the test failure image shows it is present in the top-left corner:
![navigation-editor-allows-creation-of-a-menu-2021-02-09t08-05-05](https://user-images.githubusercontent.com/677833/107458541-3a725980-6b8f-11eb-93ca-82e7471e0edd.jpg)

And inspecting the HTML from the failure shows that the test should pass.

I've spent a bit of time debugging this, but don't have an answer yet to why it suddenly has become inconsistent.

**Comment by tellthemachines** [comment]
Not sure if this is useful: when running locally this test almost always fails, but if I run it in interactive mode it consistently passes.
