### ISSUE TITLE
Navigation block submenu appender glitches positionally

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#28906]
## Description
When hovering over a navigation block submenu, the appender can visually move if the block doesn't have focus.

## Step-by-step reproduction instructions
1. Add a navigation block
2. Add a submenu with some blocks
3. Make sure a block in the submenu is selected
4. Click somewhere in the sidebar/block inspector
5. Hover back over the submenu

## Expected behaviour
The appender glitches positionally

## Actual behaviour
The appender is solid as a rock

## Screenshots or screen recording (optional)
This screenshot also shows menu items glitching, but that's fixed by #28904

![glitch](https://user-images.githubusercontent.com/677833/107479745-82f13d80-6bb6-11eb-9d57-4bdbc97a36e3.gif)

**Comment by jasmussen** [comment]
In addition to the fix that's slipstreamed into #28904, I also created a separate followup in in #28908, which cleans up things a little bit.
