### ISSUE TITLE
Feature to core request: multilingual support

### ISSUE THREAD

**Issue by mad1111111** [WordPress/gutenberg#28919]
#core #wordpress-core
Since we live now in a world where internationalization is part of everyday's life I would appreciate, if wordpress would go with the time and would implement by default the support of multilingual sites.

I really love wordpress and I love to build sites with, I love how flexible it is and how many diffrent things you can create with it. 
But even though it is so flexible, it really lacks a proper multilingual feature. And to complete a really poper multilingual functionallity on a professional level, I think you only have one option: make it a core feature of Wordpress.

All the troubleshooting after updates, by using third-party-plugins etc. are not up to date anymore.
I really hate to change platform when I need to accomplish multilingual sites, multilingual shops and so on... for a professional website with focus on a solid, stable environment you cannot really rely on third party plugins.
Well, one exception there is: WooCommerce. But even if you want to start a WooCommerce store with more languages you reach the limits very fast. Too fast in years, where the e-coomerce is booming like never before.

I think in long-term Wordpress needs to support natively a multilingual setup. The faster it gets it implemented, the better and the more it will gain market share.

I am an Italian-German developer and I hate it to see, that over the last 5 years Wordpress/WooCommerce is losing its clients in my zones, because people want a multilingual business website with shopping cart functionality. Web developers decide to switch to Prestashop, Shopware (german solution, which gained an incredible popularity in Europe) or Magento (which will be less relevant over the next years, because it was purchased by Adobe) or Shopify and even Typo3. 

The problem to the core is always the third-party plugin problem when it comes to setting up a multilingual environment. Europe is small and each buisiness site wants at least 2 languages.... with the trend to sell online a lot of companies will decide in favour of another system. Well, the blog could remain on wordpress, but still you need to rely on third-party plugins to make your site multilingual.
On the other hand, if you dive into the story of Shopware, you will see its success is based on a simple shopping cart system (like WooCommerce) with the functionality to create shops with more languages by default (and to setup more shops/storefronts in a single installation, but that would be a topic for WooCommerce ;-)).

The solution to keep Wordpress up to date and to gain massive market share over the (near) future is to implement multilingual functionality to the Wordpress core. I think for the future it is really needed. At least in my zones it will be the biggest knock-out criterion for it.

**I could immagine that you are already discussing the multiple language support for Wordpress by default since years, but at the same time since years there is nothing happening.** And I really could immagine you are facing problems with the developer teams of the popular multilingual plugins (like WPML) too. But I am confident there could be a solution with them together...

The gutenberg editor, well that was a small revolution in the wordpress cosmos, but together with the multilingual feature by defaultWordpress would be by far the most powerful tool you can ever immagine. 
I would love to hear one day, it finally kept up with the times and is multilingual by default! I swear, this would be the best day in my developer life.
Since then I will push forward to keep this feature request relevant, hoping one day it will be like this. Soon. Because it is really time for it. Now.

Best regards,
matt

PS: feel free to move this to the right topic. I was a bit confused and do not know where it should belong.

**Comment by talldan** [comment]
@mad1111111 This is something that is on the long-term roadmap - https://en-au.wordpress.org/about/roadmap/.

It's listed on that page as Phase 4 of the Gutenberg project, and the project is currently in Phase 2. There's not a lot of detail right now because it's still very early. As the project moves closer to that phase I'd expect more discussions to begin.

If you want to find out more, this is something that Matt Mullenweg discussed in the State of the Word 2020 keynote address (https://www.youtube.com/watch?v=QI3qCoiuG3w). By searching the web for reports of that talk you may also find some further discussion.
