### ISSUE TITLE
Image Block: Link drop-down left margin too small

### ISSUE THREAD

**Issue by mikeicode** [WordPress/gutenberg#28928]
## Description

The left margin on the link drop-down is too close by the text.

## Step-by-step reproduction instructions

1. Add an Image block to a page
2. Click the link icon
3. View left margin by text

## Expected behaviour

The margin by the text “Media File” should be the same as the margin on the right side of the drop-down.

## Actual behaviour

The text is too close to the left.

## Screenshots or screen recording (optional)

![https://d.pr/i/edanDo](https://d.pr/i/edanDo+)

## WordPress information
- WordPress version:   5.6.1 
- Gutenberg version: 9.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: iOS 10.15.5 
- Browser: Firefox: 85.0.1

**Comment by paaljoachim** [comment]
This should be a quick fix...
@tellthemachines @jasmussen

**Comment by simison** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/29384
