### ISSUE TITLE
Image block caption to become an inner/child block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28920]
## What problem does this address?

At the moment we are not able to align the Image block caption. Currently it looks like this when changing the Image size from Full to Medium.

![Screen Shot 2021-02-10 at 13 36 21](https://user-images.githubusercontent.com/5323259/107510942-16217780-6ba5-11eb-9f00-a18079e869bd.png)

It will need to be fixed. 

## What is your proposed solution?

One way to fix the problem and also give additional design options might be to change Image block captions into an inner/child block.  So that one can for instance style the caption alignment similar to what @melchoyce Mel is suggesting here: **Introduce explicit caption positioning** https://github.com/WordPress/gutenberg/issues/12997

Associated issues:

Image block selecting medium or thumbnail does not relocate caption - caption centered in relation to boundry box. (bug)
https://github.com/WordPress/gutenberg/issues/17162

Important comment: https://github.com/WordPress/gutenberg/issues/13684#issuecomment-465473023

Missing text-align for image caption
https://github.com/WordPress/gutenberg/issues/19975

**Comment by mtias** [comment]
I think we should add caption positioning, but I don't think it should be turned into a child block.

**Comment by kellychoffman** [comment]
@paaljoachim: Should we close this in favor of https://github.com/WordPress/gutenberg/issues/12997 and the associated issues you mentioned? Or add further info re: child block.

**Comment by paaljoachim** [comment]
Heya @kellychoffman 

Sure why not..:)
