### ISSUE TITLE
Image upload in columns uploads image twice

### ISSUE THREAD

**Issue by websupporter** [WordPress/gutenberg#28935]
## Description
Uploaded an image through the media dialog to fill an image block in a column, the image gets uploaded twice. It populates the selected image block but also creates a new image block and populates this one as well.

## Step-by-step reproduction instructions
1. Clean installation
2. Activate current Gutenberg plugin
3. Create a columns block
4. Insert an image block in one column
5. Open the media dialog
6. Upload an image
7. Select
8. See two images in the content
9. Open media dialog again
10. See image has been uploaded twice

## Expected behaviour
The image gets uploaded once and only the selected image block gets filled with an image

## Actual behaviour
When I upload the image, the image gets uploaded twice. Gutenberg populates the selected image block bot also creates a new image block and populates this block as well.

Sometimes, but I am not quite sure how to reproduce that, when uploading the media dialog gets white (only close-cross is left) and only the newly created block gets populated. i guess both are related.

## Screenshots or screen recording (optional)
![bug](https://user-images.githubusercontent.com/6458412/107607805-f2147380-6c42-11eb-9b98-cdab44533381.gif)

## WordPress information
- WordPress version:5.6.1
- Gutenberg version: 9.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu 18.04
- Browser: Firefox 84.0.2

**Comment by ntsekouras** [comment]
Thanks for reporting @websupporter ! I could reproduce this, although in my case it inserted the image in the second column - probably has to do with the drop and drag.

**Comment by Sandstromer** [comment]
I can reproduce this too.

This issue also occurs when replacing a **cover block** image. Didn't want to open a new issue as it seems exactly the same, with a duplicate image uploaded and then added as a separate image block above the cover block.

**Comment by paaljoachim** [comment]
Thank you for the detailed rapport @websupporter David!
This is a highly visible bug that we will need to get fixed and backported to WP 5.7.

We also have another rapport here:
https://github.com/WordPress/gutenberg/issues/25805

I will leave both open to create additional visibility.

**Comment by noisysocks** [comment]
Closing as duplicate. The other issue already has Priority High and is in the 5.7 board.
