### ISSUE TITLE
"Manage locations" in Navigation screen only showing 10 items

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#28933]
## Description

In the experimental Navigation screen, the "Manage locations" select shows a maximum of 10 items. 

## Step-by-step reproduction instructions

1. Go to Navigation screen
2. Create more than 10 menus
3. Verify only the first 10 menus appear in  "Manage locations" select.

## Expected behaviour

Expected all menus to be available for selection.

**Comment by talldan** [comment]
See also #22404, which lifted the limit for other places where we request menus. There's a benefit to using the same request parameters, as manage locations would be able to use the cached result.

Also https://github.com/WordPress/gutenberg/issues/21212, which suggests raising the default limit.
