### ISSUE TITLE
Custom font sizes are not working properly

### ISSUE THREAD

**Issue by DarkChris86** [WordPress/gutenberg#28937]
## Description
Custom font sizes are not working yet with the newest release neither:

WordPress: 5.6.1.
Gutenberg: 8.6-9.2

## Expected behaviour

- shortName parameter work as expected
- when I click any of custom sizes than the selected font size name appear in the ul selector.

## Actual behaviour

- shortName parameter is not working
- when I click any of custom sizes always keeps the default font size

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/18347405/107612964-ad3f0b80-6c47-11eb-8f4e-049039a3bf15.png)

## Code snippet (optional)
```

add_action( 'after_setup_theme', 'custom_setup' ) 
...
// Disable custom font sizes
add_theme_support( 'disable-custom-font-sizes' );

// Editor Font Styles
add_theme_support( 'editor-font-sizes', [
	[
		'name'      => __( 'small', 'test' ),
		'shortName' => __( 'S', 'test' ),
		'size'      => 18,
		'slug'      => 'small'
	],
	[
		'name'      => __( 'normal', 'test' ),
		'shortName' => __( 'M', 'test' ),
		'size'      => 22,
		'slug'      => 'normal'
	],
	[
		'name'      => __( 'large', 'test' ),
		'shortName' => __( 'L', 'test' ),
		'size'      => 25,
		'slug'      => 'large'
	],
]);
```

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 8.6-9.2
- Block type: Pharagraph
- Are you using a default theme Yes - Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome newest

**Comment by talldan** [comment]
Thanks, this was already report - https://github.com/WordPress/gutenberg/issues/28738. I'll close this as a duplicate.
