### ISSUE TITLE
Custom unit support should be opt-out or default

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#28963]
## Description

From #20888 it appears that you are meant to be able to select a unit (px, %, vh) from the Cover block min-height selector.

This appears to be broken, as there's no way to click the unit selector, or tab into it:

![unitcontrol](https://user-images.githubusercontent.com/1204802/107744766-9239cd80-6d13-11eb-95c5-c62becde7192.gif)

## Step-by-step reproduction instructions

1. Insert a cover block, choose a background
2. Open the sidebar, add a min-height value
3. Click the unit selector

Note that nothing happens, when instead, a unit dropdown should appear.

**Comment by jasmussen** [comment]
@ItsJonQ Do you know what might have caused this?

**Comment by brentswisher** [comment]
@jasmussen Which theme are you using? It looks like that needs to be [enabled in the theme](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#support-custom-units) to show up.

**Comment by paaljoachim** [comment]
I am testing Gutenberg RC 10.0 https://github.com/WordPress/gutenberg/releases/tag/v10.0.0-rc.1
5.7 beta 2.
Twenty Twenty One.
Chrome
A local site.
OSX 10.15.7

This is what I see:

https://user-images.githubusercontent.com/5323259/107797071-cf757e00-6d5a-11eb-9e28-faa1f49b1e6a.mp4

----

I also 
Tested with WP 5.6.1
Gutenberg plugin 9.9.2
Twenty Twenty One.

Unit selector worked for me there as well.
What did not work in this version is the click into the number box and use the scroll wheel to change the values. Which I did at the end of the above video using Gutenberg 10.0.

**Comment by jasmussen** [comment]
Ah, that's almost certainly it, thank you @brentswisher!

That said, I think we should revisit this decision, and either make the feature an opt-out instead of an opt-in, or just graduate it for all. Themes won't know to opt in to this, and the inert selector feels especially broken when it can be switched to "vw" units by using the button in the toolbar.

**Comment by paaljoachim** [comment]
Perhaps we should look through various settings be it example full width alignment etc etc that should now be taken out of the experimental phase. To make these visible in various themes by default.

**Comment by jasmussen** [comment]
I'm not seeing the need for custom-units opt in through functions.php in my own theme anymore. But in any case, it also seems like #33470 is a better and more specific ticket for discussing this, so closing this one in favor of it! Thank you.
