### ISSUE TITLE
@wordpress/create-block throws TypeError: Invalid Version: 0.32

### ISSUE THREAD

**Issue by raaaahman** [WordPress/gutenberg#28965]
## Description

While trying to follow the [Create a block tutorial](https://developer.wordpress.org/block-editor/tutorials/create-block/), I ran into an issue trying to use the command `npx @wordpress/create-block starter-block`.

## Step-by-step reproduction instructions

1. Type the following command in a terminal: `npx @wordpress/create-block starter-block`

OR

1. Type the following command in a terminal: `npm init @wordpress/block tutorial-block`

## Expected behaviour

I expected to scaffold a WordPress plugin directory with a custom block.

## Actual behaviour

I had the following issue:

> npx : 226 installé(s) en 12.698s
> /home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/node_modules/semver/semver.js:323
>    throw new TypeError('Invalid Version: ' + version)
>    ^
>
> TypeError: Invalid Version: 0.32
>    at new SemVer (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/node_modules/semver/semver.js:323:11)
>    at SemVer (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/node_modules/semver/semver.js:313:12)
>    at /home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/index.js:118:33
 >   at module.exports (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/map-values/index.js:9:18)
 >   at /home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/index.js:112:22
 >   at end (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/run-parallel/index.js:21:15)
>    at done (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/run-parallel/index.js:25:10)
>    at each (/home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/run-parallel/index.js:31:7)
>    at /home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/run-parallel/index.js:41:43
>    at /home/sylvain/.npm/_npx/14594/lib/node_modules/@wordpress/create-block/node_modules/check-node-version/index.js:59:14

I can't figure out which version this `0.32` refers to.

## Code snippet (optional)

Here are the output of some commands:

```bash
$ node --version
v14.15.4
$ npm --version
6.14.11
$ nvm --version
0.33.11
$ npx --version
6.14.11
$ npm list -g --depth=0
/home/sylvain/.nvm/versions/node/v14.15.4/lib
├── @wordpress/env@3.0.2
├── npm@6.14.11
└── serve@11.3.2
```

## Device information
- Device: Desktop
- Operating system: Ubuntu 18.04.5

Thanks!

**Comment by gziolo** [comment]
It should work with your versions of Node.js and npm. It's a very strange error that I see for the first time.

**Comment by gziolo** [comment]
I tried to reproduce with the exact same versions of node and npm. Everything finished without any issues. The only difference is that I use macOS Big Sur v11.2.1. It looks like it's OS-specific then.

**Comment by raaaahman** [comment]
Thank you for checking out.

Meanwhile, I have found the troublemaker, by running the command:

```bash
$ npx check-node-version --print
npx : 13 installé(s) en 1.685s
node: 14.15.4
npx: 6.14.11
yarn: given version not semver-compliant
npm: 6.14.11
```

It appears that yarn version was the causing the TypeError: 

```bash
$ yarn --version
0.32
```

Except... it's not the right yarn![This yarn is part of the [cmdtest debian package](http://git.liw.fi/cgi-bin/cgit/cgit.cgi/cmdtest/tree/README.yarn) that is installed by default on Ubuntu 17, and 18 as it appears. A [related issue](https://github.com/yarnpkg/yarn/issues/3189).

So I had to uninstall it from my system (I don't plan on testing Unix commands in a near future):

```bash
$ sudo apt remove cmdtest
```

And now I am able to use `@wordpress/create-block`... At last!

I'm closing the issue, since this is not a problem with Gutenberg.

**Comment by gziolo** [comment]
Thank you for reporting back your findings. I'm surprised that `yarn` is part of the validation when only `npm` and `node` are listed with minimum versions. Maybe we could find a way to skip that check.

**Comment by gziolo** [comment]
I found where the issue comes from:

https://github.com/parshap/check-node-version/blob/e669f3223a5378d6d006af12c3da8e676dad559c/index.js#L98L101

It probably errored when checking the version of yarn as it iterates over all programs supported. In the latest version they fixed it - it only uses the listed programs. I will update the dependency.

**Comment by gziolo** [comment]
I have a patch ready in #29066 that might improve things, thank you again @raaaahman 💯
