### ISSUE TITLE
Add wp-block class to all core blocks (editor and saved HTML)

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#28966]
## What problem does this address?
CSS using element selectors or descendant selectors can lead to specificity problems, hence the recommendation that developers prefer class names over more specific combinations of selectors.

The current lack of the `.wp-block` class name on some core blocks - for example `core/heading` - means that these elements have to be targeted by other means, for example `.c-blocks > *`.

## What is your proposed solution?
Ensure that every Core Block receives the class name `wp-block` in the editor and in the saved HTML.

**Comment by paaljoachim** [comment]
Hi this looks like a good fix to get included. Thank you for the issue @markhowellsmead Mark!

Isabel. This sounds like a good fix to get in place.
@tellthemachines

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting.
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/6639. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
