### ISSUE TITLE
Preserve Gutenberg user preferences across sites in a MultiSite Network

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#28971]
## What problem does this address?
In a Multisite environment, with sites on different domains (or even subdomains), Gutenberg user preferences (such as Full Screen Mode and Top Toolbar) set on one site are not reflected when editing another site, as these preferences are stored in Local Storage.  I would really expect these preferences to be tied to the user alone; not to the user/site combination.

## What is your proposed solution?
I believe it would be great if these user preferences were stored in the wp_usermeta table so they could be taken into consideration by the UI regardless of which site or subsite the user is editing.

**Comment by talldan** [comment]
Thanks for mentioning this @MadtownLems, there is an issue already tracking the problem - #15105.

There's been some progress looking into this (https://github.com/WordPress/gutenberg/pull/19177), but it requires someone to take it over again.

I'll close your issue as a duplicate of that one.
