### ISSUE TITLE
Handling overflow in the quick toolbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2898]
This topic has come up a number of time, but hasn't been opened in a separate ticket. All discussions will be referenced from this ticket.

The question for the day: **how do we handle overflow in the quick toolbar?**

Overflow refers to when there isn't enough available space to fit the buttons inside the quick toolbar. This might happen on mobile, or it might happen if you float a block.

As the quick toolbar decreases in width, there are a number of ways to handle the overflow, including:

1. "pop off" buttons and move them to an overflow menu
2. let the quick toolbar scroll horizontally
3. allow multiple stacked toolbars

Solution 1 is good for the desktop, as scrolling horizontaly is not a good experience.

Solution 2 is good on mobile, as swiping horizontally feels natural. But it makes the code complex when it comes to dropdowns in the quick toolbar.

Solution 3 is what the Classic Text block does, and should ideally be avoided.

**Note:** there _is_ an overflow menu on mobile, there to handle the mover, cog, trash buttons. As we look for a solution to the quick toolbar overflow, we should keep this in mind, for example by moving these buttons to the quick toolbar on the mobile breakpoint.

## Mockups

Here's how Google Docs handles it on the desktop:

<img src="https://user-images.githubusercontent.com/1204802/31162827-bf0088aa-a8df-11e7-9645-7428143eb9e0.gif">

Here are various mockups that illustrate potential solutions:

Desktop breakpoint:

![desktop toolbar overflow](https://user-images.githubusercontent.com/1204802/31164080-d55eaa18-a8e5-11e7-9703-7cb6ccc6030c.png)

Mobile breakpoint version 1, toolbar scrolls:

![mobile overflow scroll](https://user-images.githubusercontent.com/1204802/31164089-df17d98a-a8e5-11e7-8d18-69299a96f653.png)
![mobile overflow scrolled](https://user-images.githubusercontent.com/1204802/31164091-e24bd174-a8e5-11e7-9862-dd263a069b97.png)

Mobile breakpoint version 2, "More" button appears (like Docs):

![mobile overflow more button](https://user-images.githubusercontent.com/1204802/31164112-f7c0af34-a8e5-11e7-8a8c-08550b324f89.png)

![mobile overflow more popout](https://user-images.githubusercontent.com/1204802/31164117-fade3b5a-a8e5-11e7-9736-df6402215467.png)

## Tickets where this has come up:

- #2797
- https://github.com/WordPress/gutenberg/issues/2287
- https://github.com/WordPress/gutenberg/issues/2670
- https://github.com/WordPress/gutenberg/issues/2156

**Comment by androb** [comment]
FWIW we found Version 1 (a horizontally scrollable toolbar) worked better on mobile than a "more drawer." (Version 2) in Textbox.io. The "more drawer" covered up too much screen real estate.

**Comment by jasmussen** [comment]
@androb Nice, thanks for the info. How did you handle dropdown menus inside a scrolling toolbar?

**Comment by hedgefield** [comment]
I'd go for a horizontal scroll too, it's a pattern that [Google also uses in Material](https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs) when a tab/toolbar is wider than the screen 👍

As a side note, I wouldn't show a scrollbar like the second screenshot shows, you wouldn't be able to grab that with your finger on a mobile device anyway, and as a visual cue there's probably something better(-looking), like a fade or an arrow on the end of the bar (or nothing, like in Material, but I don't know if enough people are familiar with that pattern yet).

**Comment by jasmussen** [comment]
> I'd go for a horizontal scroll too, it's a pattern that Google also uses in Material when a tab/toolbar is wider than the screen 👍

I like the horizontal scroll, but the two problems with it remain — it's very difficult to get a dropdown button to work when it can also scroll horizontally. And it also doesn't work on the desktop, whereas an ellipsis or a "more" button would work on both.

> As a side note, I'd hide the scrollbar (seen in the second mobile mockup), you wouldn't be able to grab that with your finger on a mobile device anyway

Totally — that was just an artifact of the mockup, to indicate the auto hiding scrollbar that shows up on mobile when you drag.

**Comment by hedgefield** [comment]
Ah hm, I wasn't paying attention to the fact that overflow could also be an issue on desktop... Then I would prefer the more button too yeah. My only concern with that on mobile is to make sure there won't be any of the standard, commonly-used features hidden behind that button due to lack of space. From the mockups it looks like that won't be an issue, but if it ever does become one, maybe we could also offer a way to customize which elements go on the main toolbar and which are inside the more dropdown, like Apple sometimes offers for apps with a bottom drawer?

**Comment by androb** [comment]
@jasmussen we had a different interaction on mobile vs. desktop. Horizontal scroll worked better on mobile and a "more" button worked better on the desktop.

As for scrolling horizontally with a drop down, I am not sure what the issue is? Is that the drop-down doesn't move in sync with when the toolbar gets scrolled?

**Comment by jasmussen** [comment]
> As for scrolling horizontally with a drop down, I am not sure what the issue is? Is that the drop-down doesn't move in sync with when the toolbar gets scrolled?

No, just wondering whether you solved the technical challenges (sounds like you did), like syncing up the x position of where to show the dropdown, etc.

**Comment by jasmussen** [comment]
I'm going to close this ticket in favor of #4084, which offers a different approach to some of the issues this ticket tried to address.

That doesn't mean the inherent issue here is fixed, but it is mitigated both by the horizontal scrolling of the quick toolbar, and when 4084 happens, by a more obvious and discoverable place to find the trash button and movers.
