### ISSUE TITLE
Request add title to a tag

### ISSUE THREAD

**Issue by MatinBeigiWP** [WordPress/gutenberg#28986]
## Ability to define a title for links (a tag)

This feature is very effective in SEO
example : <a href="/" title="HOME - HTML Code Tutorials">Click to visit home page.</a>
Get inspect from the link above

**Comment by talldan** [comment]
@MatinBeigiWP It'd be appreciated if you could use the provided issue templates when creating issues.

Link titles have been requested before, but they are not considered good practice. Here's a link to some other past discussions:
- https://github.com/WordPress/gutenberg/issues/17212
- https://core.trac.wordpress.org/ticket/24766
- https://github.com/WordPress/gutenberg/issues/20198
