### ISSUE TITLE
Site title: Different markup in the editor and on the frontend

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#28997]
## Description

The Site Title block is an `h1` in the editor. But on the frontend it's an `h1 > a`. This makes it impossible to style this block in the Site Editor.

## Step-by-step reproduction instructions

1. Add a Site Title block to any template.
2. Save the template.
3. Preview on the frontend.
4. See the difference.

## Expected behaviour

The markup should be the same in the editor as it is on the frontend.

## Actual behaviour

The markup and therefore the display is different in the editor as it is on the frontend.

## Screenshots or screen recording

**In the editor:**
<img width="285" alt="site-title-editor" src="https://user-images.githubusercontent.com/1221942/107921034-31f29800-6f6e-11eb-99e3-3681677eb885.png">

**On the frontend:**
<img width="244" alt="site-title-frontend" src="https://user-images.githubusercontent.com/1221942/107921036-328b2e80-6f6e-11eb-9688-5748b857ed6b.png">

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, using TT1

**Comment by gziolo** [comment]
I can confirm the issue by looking at the current implementation.

**Comment by aurooba** [comment]
Just a note to say, I'm working on a fix for this. :)

**Comment by paaljoachim** [comment]
Hi @aurooba I assigned the issue to you.

**Comment by paaljoachim** [comment]
Do we need to backport this fix to WP 5.7.1?
@carolinan
