### ISSUE TITLE
Gallery: Add e2e tests to make sure captions can be edited

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#29001]
We just had a [regression](https://github.com/WordPress/gutenberg/issues/28989) in GB 9.9.2 (fixed by https://github.com/WordPress/gutenberg/pull/28992). As always, we should cover the desired behavior with an e2e test to make sure this won't happen again :slightly_smiling_face:

**Comment by rafaelgalani** [comment]
Can I take this one? 😸

**Comment by ockham** [comment]
> Can I take this one? 😸 

Yes! That'd be great! :partying_face:
