### ISSUE TITLE
[core/navigation] Create empty navigation: Inactive despite preselected default

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#29007]
## Description
The `core/navigation` (horizontal/navigation) blocks have the default selection `Create emtpy navigation`. However, block creation is not possible unless opening the dropdown selection and explicitly selecting `Create empty navigation`.
As `Create empty navigation` is already selected as default value, the user would be confused as the user can't proceed with block placement unless the default option is reselected.

## Step-by-step reproduction instructions
1. Place new `core/navigation` (horizontal or vertical) block.
2. Notice the block options, try to proceed with default values, it won't work, the primary button is disabled.
3. Explicitly select `Create empty navigation` from dropdown menu.
Notice that block placement works afterwards.

## Expected behaviour
User should be able to proceed with block placement with default value for navigation source.

## Actual behaviour
User can't proceed with default value for navigation source.

## WordPress information
- WordPress version: `5.6`
- Gutenberg version: `9.5.2`
- Are all plugins except Gutenberg deactivated? "No"
- Are you using a default theme (e.g. Twenty Twenty-One)? "No"

## Device information
- Device: PC
- Operating system: Windows 10 x64
- Browser: `Chrome` `88.0.4324.150`

**Comment by talldan** [comment]
@strarsis I see you're on an old version of the plugin. The block has been updated and the placeholder now looks like this with a dedicated 'Start empty' button:
<img width="609" alt="Screenshot 2021-02-16 at 9 53 07 am" src="https://user-images.githubusercontent.com/677833/108009068-d216f280-703c-11eb-8839-48ca99d25b65.png">

Does that solve the issue for you?

**Comment by strarsis** [comment]
Right, in recent Gutenberg version the selection works correctly.
