### ISSUE TITLE
Can I use the old class name in the heading of the new widget feature?

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#29019]
Thank you for your development.

I'm testing a new blocked widget feature, but I have questions, so let me ask you a question.

In the previous widget area, you could specify the widget title tag and class name with the `"before_title"` option of `register_sidebar()`.

The themes we have already distributed are designed based on those class names.

However, the new widget feature seems to only allow you to place "Heading" blocks.

You also cannot set a title for each widget block.

This makes it very cumbersome to support both new and old widgets.

At least I want you to provide a block like the "Widget title" block.

**Comment by ddryo** [comment]
Or, I think that each widget block should have a setting item related to "Title".

@talldan 
I'm sorry, I personally feel that this is a serious problem, so I mentioned it.

**Comment by talldan** [comment]
I don't really know the answer to this, but I've added the issue to the widget editor board for the folks who work on that project to answer.

**Comment by draganescu** [comment]
This is interesting @ddryo thanks for raising the issue.

The new block based editor should not interfere with the `before_title` option of `register_sidebar()` and rendering these sidebars should work as before. The fact that you can _also_ add headings is an extra feature.

Does your theme not render the `before_title` option when you activate the Gutenberg plugin?

**Comment by ddryo** [comment]
@talldan Thanks!

@draganescu 
Ah, I'm sorry, my explanation is a little bad.
I'm writing Japanese through Google Translate, so it may not be transmitted well.

It has no effect on traditional widgets that have been installed in the past.

However, in the past widget function, the class name of the title part could be unified by "before_title".

For example, you can use the following code to unify the DOM of the title part to `div.c-widget__title`.

```php
```

This was very useful when unifying the design of widget titles on the theme side or when changing the design with the customizer.

But,

New block-based widgets can't have this uniformity.

The user may use the h2 or h3 tag as the title of the widget, using the heading block.
Or it could be just a p tag using paragraph blocks.

Unless the user manually inputs it, it cannot be unified in the class `.c-widget__title`.

**Comment by draganescu** [comment]
Ah! I think get it!

Well, blocks, when used as widgets and else, have no "title", only "content". The headings or paragraphs are considered standalone content units. If we want to a ensure style unity in a theme, CSS needs to be added to style these core blocks in their sidebar container. We cannot identify that a heading is before some other block and automagically apply a widget title to that.

> At least I want you to provide a block like the "Widget title" block.

So, just to make 💯 % sure I got this, the "Widget title" block would only be used "before" blocks and be basically a paragraph that always is wrapped by whatever the theme set as `before_title` in the sidebar registration?

**Comment by ddryo** [comment]
@draganescu 
Sorry, perhaps there is still a gap in perception.

Once again, let me try to organize my thoughts.

## About the problems I feel.

Currently, I can do the following,

- I was able to use hooks on the theme side to give the "widget title" its own class. (For example, a class like `.c-widget__title`.)
- The user would not get confused because there was only one place to enter the "widget title".
- Therefore, a common design could be applied to the "widget title".

In contrast, I feel that the new block-based widget feature has the following problems,

- There is no block or input field that can be used as a "widget title".
- Users are not sure what to do when they want to place a "widget title" as they have in the past.
- Therefore, it depends on the user's decision as to which block to use as the "widget title". (For example, some users will use `h2` or `h3` tags, while others might choose `p` tags.
- Since we don't know which block the user will place as the "widget title" and in what state, we can't make the theme apply a common design.(It might be possible if we wrote tons of CSS for every case...)


## My request

Let me describe my proposal from here.

**I would like to see something like a "Widget title block".**

If that "Widget title block" has a class like `.wp-block-widget-title`, the theme will be able to make the design consistent as before.

Also, if there is a block that can be easily understood to be for the "widget title", there will be no confusion for the user.

Of course, it is possible to implement such a block on the theme side, and it is possible to prepare a "block style" for "widget title" in the heading block, etc.

However, if you leave it up to the theme to decide how to implement the "widget title", users will get lost when they change the theme they use.

Therefore, it is better to have a core block that is clearly identified as the one to be used for "widget title" so that users can use it without confusion since the operation is the same in all themes.


Translated with www.DeepL.com/Translator (free version)

**Comment by noisysocks** [comment]
Thanks for explaining @ddryo!

Another idea could be to add a "Widget Container" block which has a title plus the ability to add inner blocks.

But my problem with either "Widget Title" or "Widget Container" is that it fragments the block editor. Ideally the same layout blocks would exist in all block editors regardless of whether it's the widget block editor or a post block editor. Is there a generic layout block that could be used to implement these types of theme designs? Could we add one?

**Comment by ddryo** [comment]
@draganescu

I'm testing the 5.8 beta.

I noticed that all the blocks I placed in the widget area are wrapped with  `.widget_block`

The `.c-widget` class specified in the `'before_widget'` of `register_sidebar()` is given to this `.widget_block`.

But there is a problem here.

In the past, specifying `'before_title'` would output the widget title with the structure of `.c-widget > .c-widget__title`, but now it is impossible to reproduce this structure.

**Comment by ddryo** [comment]
@draganescu

I have shown the problem in the image.

<img width="857" alt="スクリーンショット 2021-06-16 12 57 18" src="https://user-images.githubusercontent.com/31400297/122155704-80735d00-cea2-11eb-81de-e92cd47a2489.png">


Currently, I can use group blocks to handle titles and content as a set, but this is very different from the previous structure.

<img width="906" alt="スクリーンショット 2021-06-16 13 01 38" src="https://user-images.githubusercontent.com/31400297/122156045-258e3580-cea3-11eb-8406-61c1dfd4257b.png">

**Comment by ddryo** [comment]
For example, how about implementing a block that can be titled with a name like "**Widget Box**"?

Then, within the block editor of the widget area, limit the number of blocks that can be placed directly under the area to only two.

And in the block editor of the widget area, limit the number of blocks that can be placed directly under the area to two: the "**Widget Box**" block and the "**Legacy Widget**" block.

Of course, the "**Widget Box**" block is an inner block that can be placed freely.

**Comment by noisysocks** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/32723.
