### ISSUE TITLE
Quote block markup in the front-end

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2901]
For semantic HTML5 see issue #2647 and PR #2859.

**Current markup**:

```html+php
<blockquote class="wp-block-quote blocks-quote-style-1">
	<p>This is quote with nothing to say</p>
	<footer>From Xami K.</footer>
</blockquote>
```

- Many themes already have styles for `blockquote` so there will be overlapping with styles.
- Footer color `#8f98a1` [doesn't meet the color contrast ratio 4.5:1](http://leaverou.github.io/contrast-ratio/#%238f98a1-on-white) even on white.

## Conclusion and proposal
- I would not put any styles on fron-end from Quote block. Theme already have styles for them.
- There could be `add_theme_support` for blockquote, and after that you could see option to set two different styling.
- If nothing else, default footer (or cite) color should meet the WCAG AA 4.5:1 ratio.

**Comment by karmatosed** [comment]
On this one for the styling I would 👎  changes you suggest. We can't rely on themes having a blockquote style. Themes can dequeue the styles, so that is enough of a step as a start. What we can do is do wider testing though.

It's worth noting, stacking up a lot of add_theme_supports is not a robust method either and leads us down a slippery slope that a lot of frameworks have fallen into. Let's do our best to avoid that.

On the agreeing side, lets up that footer color.

**Comment by samikeijonen** [comment]
> We can't rely on themes having a blockquote style.

That's true. I'm fine with the decision that Gutenberg output styles for all blocks. As long as we are aware that that some blocks will mess with the theme styles. Many theme developers don't have time to update their themes before Gutenberg lands. That's why I was concerned.

> Themes can dequeue the styles

That's seems to be the best solution at the moment.

**Comment by mtias** [comment]
@samikeijonen if we make sure our blockquotes are targeted with the `wp-block-quote` class, we can try to minimize leaks from `.entry-content blockquote` and such. That said, once these classes are finalized we do need to coordinate a "Here's what themes should be aware of with the coming of Gutenberg". There will be many new blocks to style and test with, there's not going to be a way around that.

If we find truly problematic cases we can always shield them behind `add_theme_support`.

**Comment by mtias** [comment]
@samikeijonen forgot, but one thing I do want to clean up here is the `blocks-quote-style-1` class. This should be removed in favor of:
- No class for default style.
- `is-large` or equivalent for alt style, paired with `.wp-block-quote.is-large {}` for definition.

**Comment by samikeijonen** [comment]
> No class for default style.

+1

> "Here's what themes should be aware of with the coming of Gutenberg"

+100

**Comment by karmatosed** [comment]
There have been some changes here recently, does more adjustment need to happen @samikeijonen?

**Comment by samikeijonen** [comment]
I can take a look this week more of all of the issues I started, including this one.

**Comment by samikeijonen** [comment]
Notes from version 1.6.1.

**Markup**:
```html+php
<blockquote class="wp-block-quote blocks-quote-style-1">
   <p>I'm here for a reason</p>
   <footer>Sami Keijonen</footer>
</blockquote>
```

- Footer color #8f98a1 is still there which doesn't have enough color contrast even on white.
- I'm not exactly sure what's the status about using `<footer>` and/or `<cite>` when looking at #2647 and PR #2859.

**Styles**:
```css
.wp-block-quote {
	margin: 0 0 16px;
	box-shadow: inset 0px 0px 0px 0px $light-gray-500;

	footer {
		color: $dark-gray-100;
		margin-top: 1em;
		position: relative;
		font-size: $default-font-size;
		font-style: normal;
	}
```

Is there need for `box-shadow: inset 0px 0px 0px 0px $light-gray-500;`? I'd remove it.

**Comment by afercia** [comment]
Markup was already improved in previous changes, color contrast improved in #3437.
