### ISSUE TITLE
The response is not a valid JSON response, behind Loadbalancers

### ISSUE THREAD

**Issue by jimlundblad** [WordPress/gutenberg#29029]
Issues on sites behind AWS Loadbalancers.

for example:
**Cloudflare -> AWS ELB -> EC2**
When the save button is clicked you'll get "The response is not a valid JSON response"

**Comment by talldan** [comment]
@jimlundblad Please could you use the provided templates when reporting issues. This also seems like a server configuration issue, I'd recommend reaching out to the support forums for assistance - https://wordpress.org/support/forums/.
