### ISSUE TITLE
[Block: Post Navigation Link] Add the ability to have both the text title and the label be a part of the link

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#29032]
## What problem does this address?
It is a common pattern on themes to have the Previous/Next links show both a label and the title of the post while both being part of the link to said post. Usually when using [get_the_post_navigation()](https://developer.wordpress.org/reference/functions/get_the_post_navigation/) this is a possibility but it's not an option when doing so using this block.

## What is your proposed solution?
I'm not sure what the best implementation would be for this, but thinking about how this is done on _classic_ themes I believe if would help if it would be possible to show a placeholder for the title in place with the label when the block has the flag to show the title. Then both the Label and the Title are part of the block and can be positioned using the editor (such as having a line break between the two)

That way we can achieve something like this:

<img width="812" alt="Screenshot 2021-02-15 at 14 58 07" src="https://user-images.githubusercontent.com/3593343/108056452-8f134a00-7051-11eb-8d08-df84d63f78c6.png">

**Comment by mtias** [comment]
This seems like it should be a toggle with a default design in place?

**Comment by MaggieCabrera** [comment]
> This seems like it should be a toggle with a default design in place?

Mmh, that's a possibility, but it would be more flexible if we could edit both the label and the title within the editor, so we could not only decide on the line break but also if we want the text to be bold or not (like my example above). I was thinking of something like the "Read more" link on the excerpt block, for this case:

<img width="476" alt="Screenshot 2021-02-25 at 10 55 16" src="https://user-images.githubusercontent.com/3593343/109136081-0767c280-7758-11eb-9850-154dc5086098.png">

**Comment by ntsekouras** [comment]
>I was thinking of something like the "Read more" link on the excerpt block, for this case:

The difference is that `title` is dynamic. Something similar is needed here: https://github.com/WordPress/gutenberg/pull/27989 for `Search Title`.

>Search title - a title that can be used in search templates, augmented with text replacements like %search% will be replaced by the search query in php.

I'm not sure how will handle this design wise though and if we should allow inline formatting then, as it could be done with css 🤔

**Comment by mtias** [comment]
It seems like the "next post" and "previous post" being rich text could support that kind of formatting and the titles are just the block typography settings. It'd be fine to also start with the above design as a baseline and then figure out how to add further tools.

**Comment by MaggieCabrera** [comment]
For reference, my screenshot up top is from Mayland (Varia), and this is how Seedlet and TT1 does this:

<img width="858" alt="Screenshot 2021-02-25 at 14 08 28" src="https://user-images.githubusercontent.com/3593343/109158122-3dff0680-7773-11eb-9d6d-8627c16b38ef.png">

<img width="1382" alt="Screenshot 2021-02-25 at 14 09 48" src="https://user-images.githubusercontent.com/3593343/109158130-3fc8ca00-7773-11eb-80a8-ce99403f54bd.png">
