### ISSUE TITLE
FSE: Unable to select Block Manager from Options

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29049]
## Description

The Block Manager cannot be selected and blocks cannot be managed as a result. 

## Step-by-step reproduction instructions

1. Go to the Site Editor experience
2. Click on Options > Block Manager
3. Notice the block manager doesn't open

## Expected behaviour

I expect to be able to use the block manager

## Actual behaviour

Nothing happened

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/108121948-c89f8180-7060-11eb-833c-7a3047432bf9.mov

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: main branch on local site, tested against Gutenberg 9.9.3 too on a test site and confirmed there. 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 blocks

cc @ntsekouras since I see you're doing some block manager work!

**Comment by Quintis1212** [comment]
Hello ) I can not reproduce yours bug 
![Снимок экрана от 2021-02-26 19-40-24](https://user-images.githubusercontent.com/34488718/109335319-8baa6a80-786a-11eb-8f07-2185c9d8de0b.png)
Can you show your  browser console ? Maybe there is an errors that I can fix

**Comment by annezazu** [comment]
@Quintis1212 Please try this using the Full Site Editing experience by using a block theme like TT1 Blocks and the Gutenberg plugin. This is a FSE specific issue and, based on your screenshot, you're not using that experience when testing!

**Comment by Quintis1212** [comment]
after installing TT1 I can reproduce this bug ) I think I can fix it)

**Comment by Mamaduka** [comment]
@annezazu, I think this particular issue got resolved when the "Block Manager" menu item was removed. But the "Block Manager" still isn't available in the "Preferences" modal.

Should we close this issue and create a new one?

**Comment by annezazu** [comment]
Just tested once more to get a lay of the land. Sounds good :) Will do that now.
