### ISSUE TITLE
Android keyboard is not displayed when adding a block

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#29048]
## Description
When adding a new block, both while having the keyboard open or closed, the Android keyboard ~~occasionally~~ will not display open, even though the cursor is shown to be in the newly added block. Contrastingly, iOS always appropriately open the keyboard.

**UPDATE (made by @fluiddot ):** As outlined in [this comment](https://github.com/WordPress/gutenberg/issues/29048#issuecomment-1088497094), this issue is happening more often so it should no longer be considered an occasional.

## Step-by-step reproduction instructions
1. Launch Android app.
2. Add new post.
3. Add a paragraph block with text.
4. Add another text block.

## Expected behaviour
The Android keyboard is open to match the fact the cursor is placed in the new block and ready for text entry.

## Actual behaviour
Occasionally, the Android keyboard is closed, even though the cursor is within the new block.

### Android

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/438664/108118624-41540d00-7064-11eb-8356-39b4701bb76a.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/438664/108118643-487b1b00-7064-11eb-94ce-d9af26d2738a.MP4

</details>

## WordPress information
- WordPress version: WP.com
- Gutenberg version: TBD
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Samsung Galaxy S20 5G FE
- Operating system: Android 11
- WordPress app version: 16.6

**Comment by dcalhoun** [comment]
This may be related or duplicative of #28748.

**Comment by fluiddot** [comment]
I'm experiencing this issue every time I insert a text block from the block picker in the latest version `19.6-rc-1`, so maybe it shouldn't be considered as an occasional issue 🤔.

@mchowning I see we marked this issue as Low priority, however, since it's happening more often we might consider increasing the priority, wdyt?

**Comment by mchowning** [comment]
> @mchowning I see we marked this issue as Low priority, however, since it's happening more often we might consider increasing the priority, wdyt?

That makes sense. I'll go ahead and bump it up to high priority in light of "I'm experiencing this issue every time I insert a text block from the block picker", but go ahead change that if you think that something else is more appropriate.

**Comment by fluiddot** [comment]
> That makes sense. I'll go ahead and bump it up to high priority in light of "I'm experiencing this issue every time I insert a text block from the block picker", but go ahead change that if you think that something else is more appropriate.

Thanks for updating it @mchowning, I think high priority makes more sense as it's happening more often 🙇 . I'm also going to update the title and description of the issue to reflect this change.

**Comment by annezazu** [comment]
I'm doing a sweep of [high priority issues for the Gutenberg repo ](https://wordpress.slack.com/archives/C02QB2JS7/p1702996696603749) and noticed this issue has greatly stalled out despite the label. To keep these issues actionable and relevant, I've removed this high priority label. Feel free to add back if you all are able to replicate, confirm the widespread nature of the problem, and believe quick action is needed.

**Comment by dcalhoun** [comment]
👋🏻 @fluiddot @geriux. Do the recent usability improvements in https://github.com/WordPress/gutenberg/pull/57069 and https://github.com/WordPress/gutenberg/pull/57070 improve this absent Android keyboard on block insertion issue at all?

**Comment by geriux** [comment]
Hey @dcalhoun 👋  this should be fixed with those recent changes so I'll close this ticket 🚀
