### ISSUE TITLE
FSE: Site Editor returns WSoD with WooCommerce active

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#29050]
## Description
When Gutenberg and WooCommerce are active visiting the Site Editor returns a blank page. This occurs with a clean install of WordPress, Gutenberg and WooCommerce.

Console error:
```
TypeError: Cannot read property 'tinymce' of undefined
    at index.js?ver=9fea52b9fae58fce07c7a28038354ffa:58
    at Bh (react-dom.min.de439aae.js:126)
    at Dj (react-dom.min.de439aae.js:162)
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)
    at xb (react-dom.min.de439aae.js:162)
    at react-dom.min.de439aae.js:162
    at U (react.min.e713ea3b.js:16)
    at MessagePort.B.port1.onmessage (react.min.e713ea3b.js:24)
```
No errors reported with WP_DEBUG enabled.

## Step-by-step reproduction instructions
1. Install WordPress 5.6.1 with TT1 Blocks theme
2. Install Gutenberg 9.9.3
3. Install WooCommerce 5.0.0
4. Visit Site Editor
5. Observe blank page

## Expected behaviour
My expectation is the Site Editor will be available when WooCommerce is installed.

## Actual behaviour
The Site Editor is unavailable due to the page being blank.

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.3 (also observed with 9.9.2)
- Are all plugins except Gutenberg deactivated? No, WooCommerce is also active.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 88.0.4324.150, Firefox Developer 86.0b9

**Comment by Sandstromer** [comment]
This seems to be a WooCommerce issue.

Is it related to [27938](https://github.com/WordPress/gutenberg/issues/27938)?

**Comment by chthonic-ds** [comment]
Yep, currently looks like the solution is to either roll back a change on the WooCommerce side or wait for the editor to be iframed. https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3626
