### ISSUE TITLE
Mobile - Add new endpoint to get global styles settings through the REST API

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#29063]
## What problem does this address?
In order to add support for Global Styles on the mobile editor, there should be an endpoint to be able to fetch [this data](https://github.com/WordPress/gutenberg/blob/master/lib/global-styles.php#L191) through the REST API.

## What is your proposed solution?
There's an [opened PR](https://github.com/WordPress/gutenberg/pull/25226) with an exploration of this so we'd need to either continue that effort to use it as a reference.

**Comment by chipsnyder** [comment]
@geriux It looks like we might already have these values in the endpoint `/wp/v2/themes?status=active` Can we leverage this existing endpoint? Would that endpoint be missing any data that we might need?

https://github.com/WordPress/WordPress/blob/019bc2d244c4d536338d2c634419583e928143df/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L17

**Comment by geriux** [comment]
> @geriux It looks like we might already have these values in the endpoint `/wp/v2/themes?status=active` Can we leverage this existing endpoint? Would that endpoint be missing any data that we might need?
> 
> https://github.com/WordPress/WordPress/blob/019bc2d244c4d536338d2c634419583e928143df/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L17

Hey @chipsnyder  👋 

Unfortunately, that endpoint doesn't return the values that we need (contents of theme.json). I guess we could add the `theme.json` values but there are other things like `__experimentalGlobalStylesUserEntityId` logic which we'll need to bring any changes of the Global styles settings from the user.

So I think we should create a new endpoint that pulls the data from [lib/global-styles.php](https://github.com/WordPress/gutenberg/blob/master/lib/global-styles.php), my only concern now is that it is filtering to only work if you're[ editing a site page](https://github.com/WordPress/gutenberg/blob/master/lib/global-styles.php#L228-L230) so we'd need to figure out a way to make it work for both cases, on the web when you're editing your site (as it is now) and returning these settings without any `gutenberg_is_edit_site_page` checks through the REST API.

**Comment by chipsnyder** [comment]
Thanks @geriux for confirming. Diving in more I realized I was confusing `theme_support` with `theme.json`
