### ISSUE TITLE
Invalid HTML in search block

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#29061]
## Description
The search block has invalid HTML:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/search/index.php#L83

```html
<button type="submit"class="wp-block-search__button ' . $button_classes . '">%s</button>
```

## Expected behaviour
A space is added before the `class` attribute.

## Actual behaviour
There is a space missing before the `class` attribute.

## WordPress information
- WordPress version: 5.6
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: every device
- Operating system: every system
- Browser: every browser

**Comment by GRboss** [comment]
Hi @MatzeKitt ,

I've raised this [pull request](https://github.com/WordPress/gutenberg/pull/29086). It's my first ever on GitHub and in open source in general! Once small step for a man...

Regards,
Stefanos

**Comment by MatzeKitt** [comment]
Damn, I thought if I have time, I can create one by myself. 😂
