### ISSUE TITLE
Bug where tags disappear when adding tags in the create post view

### ISSUE THREAD

**Issue by jdc91** [WordPress/gutenberg#29077]
## Description
There seems to be a bug when adding tags. The tag is momentarily shown and then disappears for a second and reappears. This can be a less than ideal user experience.

## Step-by-step reproduction instructions
1. Go to create new post
2. Throttle internet to fast 3G using chrome dev tools
3. Add tags 

## Expected behaviour
Tags should appear as you type and hit enter

## Actual behaviour
Tags appear, but disappear briefly, and then reappear

## Screenshots or screen recording (optional)
https://www.youtube.com/watch?v=6IczA2miTpg

## WordPress information
- WordPress version: Version 5.6.1 
- Gutenberg version: Gutenberg Updates for WordPress 5.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme? Twenty Twenty-One

## Device information
- Device: Desktop 
- Operating system: macOS Catalina - 10.15.7 
- Browser: Chrome 88.0.4324.150

**Comment by Mamaduka** [comment]
I was able to reproduce the issue.

I just had to switch to "Slow 3G" throttling. Also noticed that issue mostly affects cases when a new tag is created on the fly.

**Comment by Thelmachido** [comment]
On a test site,  I switched to "Slow 3G" throttling:

1. Added already created tags
2. Created new tags 

I wasn't able to reproduce the bug, as shown in the video below:

https://user-images.githubusercontent.com/41231764/183868036-3c5f3786-8209-4358-97f5-37423c7012af.mov

WordPress 6.0.1

Gutenberg 13.8.1 

No other plugins active

Closing this issue
