### ISSUE TITLE
Cover Blocks with a light background color have a UI border around them

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#29082]
Starting in Gutenberg v9.9.0 or so, Cover blocks that use a light background color (and no image) have a light single pixel border around them in the editor: 

![Screen Shot 2021-02-17 at 10 50 00 AM](https://user-images.githubusercontent.com/1202812/108229874-2f2ea900-710e-11eb-8019-571fcf7c6378.png)
![Screen Shot 2021-02-17 at 10 50 11 AM](https://user-images.githubusercontent.com/1202812/108229875-2fc73f80-710e-11eb-95d1-bae81ef3dd8e.png)

I'm not sure when this began showing up, but it doesn't appear to happen with any other block. 

From what I can tell, this appears to be intentional, so marking as a bug for now. Even if it is intentional, it doesn't match the front-end so it seems like a bug.

**Comment by jasmussen** [comment]
I accidentally created a duplicate of this issue in #29440, but found a solution:

> It appears the border comes from there technically being an `img` in the markup, it's just unset:
> 
> ```
> <div class="... wp-block-cover">
> 
> 	...
> 
> 	<img class="wp-block-cover__image-background" alt="">
> 	<div class="wp-block-cover__inner-container block-editor-block-list__layout">
> 		...
> 	</div>
> </div>
> ```
> 
> It appears Chrome adds a gray border around such empty `img`s, as you can see in this codepen: https://codepen.io/joen/pen/gOLzOWR
> 
> If I add this, the border disappears:
> 
> ```
> img:empty {
> 	visibility: hidden;
> }
> ```
> 
> However it seems like a better solution would be to not output any img at all, if possible.

I'm happy to close that other ticket and edit the solution into this one? 

Either way, what fixes this one also fixes the other one :)

**Comment by kjellr** [comment]
Good catch! Let's close this issue, since you found the culprit over in #29440. 👍
