### ISSUE TITLE
Text column block markup in the front-end

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2908]
**Markup**:

```php
<section class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>Cras vel nunc auctor massa iaculis scelerisque in semper libero. Pellentesque tincidunt auctor egestas. Quisque a ligula vehicula, condimentum dui pretium, imperdiet erat. Aliquam molestie nisi a metus rhoncus pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
	</div>
	<div class="wp-block-column">
		<p>Cras vel nunc auctor massa iaculis scelerisque in semper libero. Pellentesque tincidunt auctor egestas. Quisque a ligula vehicula, condimentum dui pretium, imperdiet erat. Aliquam molestie nisi a metus rhoncus pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas</p>
	</div>
</section>
```

- I'm not sure is the `<section>` correct here since there is no heading inside it and it's just for styling the grid. Should probably  be `<div>`.
- Grid is not responsive. I'd even go that far that we use CSS Grid here with solid flexbox markup.

**Comment by mtias** [comment]
Switching to a div sounds good. As context, this block was going to be a foundation for general columns, which will support any nested block inside, which means also headings. We need to figure out how we'd want to handle that.

@samikeijonen how would you approach this with CSS grid? I'm happy for gutenberg to explore using it if there are people willing to plan and implement it.

**Comment by samikeijonen** [comment]
@mtias I can do PR how I'd implement CSS Grid. Similar CSS could be used other places like latest posts in a grid.

My initial idea was going without breakpoints like this:

```css
wp-block-text-columns {
   display: grid;
   grid-gap: 8px;
   grid-template-columns: repeat( auto-fit,minmax( 300px,1fr ) );
}
```

But based on value `300px` and what is the content width for columns CSS above could mean 1-4 columns. Even if user have chosen 3 columns for example.

So we might still need some breakpoints.

**Comment by afercia** [comment]
`<section>` elements are not identified by just the presence of a heading. They're meant for **thematic grouping of content** and intended for big chunks of content (e.g. chapters) so they're probably not appropriate here.

Quoting: https://www.w3.org/TR/html51/sections.html#the-section-element

> The section element represents a generic section of a document or application. A section, in this context, is a **thematic grouping of content**. Each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element.
> ...
> Examples of sections would be chapters, the various tabbed pages in a tabbed dialog box, or the numbered sections of a thesis. A Web site’s home page could be split into sections for an introduction, news items, and contact information.

**Comment by samikeijonen** [comment]
Let's go with `<div>`. I play around with the styles also.
