### ISSUE TITLE
Make possible to use wp-env config file as a JS file

### ISSUE THREAD

**Issue by nicolad** [WordPress/gutenberg#29092]
## What problem does this address?
Currently we can use only `.wp-env.json` file for configuration.

## What is your proposed solution?
Would be nice to be able to use a JavaScript file. The same way other libs are doing, like for example ESLint:

> Configuration Files - use a JavaScript, JSON, or YAML file to specify configuration information for an entire directory and all of its subdirectories. This can be in the form of an .eslintrc.* file or an eslintConfig field in a package.json file, both of which ESLint will look for and read automatically, or you can specify a configuration file on the command line.

![image](https://user-images.githubusercontent.com/1477453/108269773-29b97900-7177-11eb-95a5-25673cc3ff9b.png)

**Comment by noahtallen** [comment]
I don't think we'll implement this unless there is more support for adding it. At least for now, we want to keep wp-env more minimal, especially from a maintenance point of view (there are not very many wp-env contributors at the moment). It'd be super helpful to know your use case for this, though!
