### ISSUE TITLE
Gutenberg for custom post type without revisions creates JS error

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#2910]
If we enable Gutenberg for a custom post type that doesn't support revisions, the `revisions` object here https://github.com/WordPress/gutenberg/blob/master/editor/sidebar/last-revision/index.js#L26 is undefined and `revisions.data` is thoughing an `Uncaught TypeError: Cannot read property 'data' of undefined`.

Shouldn't we check for revisions before trying to access `data`?

**Comment by aduth** [comment]
If I recall correctly, a prop injected by the `withAPIData` higher-order component should _always_ be an object, even if `data` is not necessarily available. There must be an issue with this behavior.

**Comment by kmgalanakis** [comment]
It's very easy to reproduce this issue.

Just create a custom post type using either code or some plugin and don't forget to set `show_in_rest => true` and to keep `revisions` out of the `supports` array. Then try to load the Gutenberg editor for this custom post type. There you should see the above mentioned JS error. Enable `revisions` and see that the error is gone.

**Comment by aduth** [comment]
Pending fix at #2938
