### ISSUE TITLE
Navigation Screen: Page List block styling is inconsistent with navigation link styling

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#29101]
## Description
The page list block and the navigation screen re-design were both merged at around the same time.

The re-design change the way navigation links appear on the navigation screen—they no longer use a flyout menu for submenus, instead using an accordian style expandable/collapsible submenu.

The page list still renders submenus as flyout menus though, it needs to be brought in line with the way navigation links look.

## Step-by-step reproduction instructions
1. Create some pages for your site, and create a hierarchy using the parent page option
2. Visit the navigation screen and create a menu
3. Use the add all pages option on the placeholder
4. View the submenus
5. Add some navigation links to the block including creating a submenu.
6. Compare the way navigation link submenus look to page list submenus

## Expected behaviour
Page list submenus look like navigation link submenus

## Actual behaviour
They look different

## Screenshots or screen recording (optional)
<img width="450" alt="Screenshot 2021-02-18 at 1 53 18 pm" src="https://user-images.githubusercontent.com/677833/108311837-ae94a900-71f0-11eb-8f04-c1b1809e6668.png">

**Comment by jasmussen** [comment]
Potentially related: https://github.com/WordPress/gutenberg/issues/28575

**Comment by talldan** [comment]
I think @shaunandrews mentioned something somewhere (I can't find it now). Potentially the issue here is that the vertical Navigation Block should show submenus in the accordion style that the navigation editor implements. Page List's styles could then follow suit and things would work as expected.

So it might be a case of updating the navigation block.

**Comment by jasmussen** [comment]
I'd suggest that flyouts and accordions both could benefit both vertial and horizontal versions of the navigation block. I've seen horizontal menus that pushed content downwards, intentionally, when a submenu was opened, and I could see a table-of-contents like vertical menu where submenus are best shown in flyouts. 

That would still make it a block-related thing, to your point.

**Comment by jasmussen** [comment]
I noticed I wasn't able to insert the "Page List" block at all on this screen, and that there's a horizontal scrollbar:

<img width="447" alt="Screenshot 2021-03-17 at 09 39 33" src="https://user-images.githubusercontent.com/1204802/111438588-b880cd80-8704-11eb-9983-7caf74c8715f.png">

The search field also appears missing. Was that intentional?

**Comment by jasmussen** [comment]
I also added #28575 to the tracking issue. The above two screenshots illustrate the difference in markup, and making that markup be the same will substantially simplify the CSS.

**Comment by jasmussen** [comment]
I'm tracking down this issue, and found out that the `style.scss` file which is responsible for handling basic hover styles for submenu items is not loaded in the separate navigation editor screen. Is this intentional?

I'd be happy to take a look at writing some CSS specific for just the navigation screen to handle this expand/collapsing, perhaps even to an extent on the Page List block. But I want to be sure the missing style.scss file is intentional, before I start duplicating/tweaking the content. A review of https://github.com/WordPress/gutenberg/pull/29869 would also be a great help.

**Comment by jasmussen** [comment]
Looks like #28874 answers my question above: style.scss files _should_ be loaded in the navigation editor, but aren't being at the moment.

**Comment by talldan** [comment]
> I noticed I wasn't able to insert the "Page List" block at all on this screen

@jasmussen Yeah, this is intentional. It isn't an allowed block unless the theme has opted in to support blocks in menus (the option detailed in https://github.com/WordPress/gutenberg/pull/24503).

I don't think there's a way to support it that's backwards compatible with the way menus work in core, so I don't think it can be included in the screen by default.

More blocks can be enabled by adding the theme opt in `add_theme_support( 'block-nav-menus' );` somewhere locally. At the moment the block can also still be added via the navigation block's placeholder (which seems like a bug).

> and that there's a horizontal scrollbar.

Hmm, that looks new. Most likely a bug with the quick inserter as this uses the same component as the other editors.

> The search field also appears missing. Was that intentional?

I don't think it shows unless there are more than six blocks. That's implicit behavior of the quick inserter. I'm not sure why you have Post Link twice in your screenshot, though.

> Looks like #28874 answers my question above: style.scss files should be loaded in the navigation editor, but aren't being at the moment.

Only for FSE themes, but it can still be tested perfectly fine in Twenty Twenty One.

> I can't reproduce the original issue reported here

I can still reproduce it:
<img width="451" alt="Screenshot 2021-03-17 at 7 07 44 pm" src="https://user-images.githubusercontent.com/677833/111458185-1d174900-8754-11eb-8f39-635beaa05f6a.png">

I think it'd be best to remove the custom nav block (accordion) styles from the navigation editor and make them part of the block as a first step - I made this issue https://github.com/WordPress/gutenberg/issues/29747.

I'd be happy to try that at some point

**Comment by talldan** [comment]
Also wondering why your screenshots looks so different? Is that with a particular theme?

**Comment by jasmussen** [comment]
> I don't think there's a way to support it that's backwards compatible with the way menus work in core, so I don't think it can be included in the screen by default.

Thank you for clarifying. Just noting that I was able to insert it if it's the first block I insert. I just click the "Add all pages". That explains the blue links — that and https://github.com/WordPress/gutenberg/issues/28575.

> Hmm, that looks new. Most likely a bug with the quick inserter as this uses the same component as the other editors.

I can take a look.

> I don't think it shows unless there are more than six blocks. That's implicit behavior of the quick inserter. I'm not sure why you have Post Link twice in your screenshot, though.

Makes sense if the Page List has been omitted. I'll be sure to check if that's the cause of the hoz scrollbar.

> I'm not sure why you have Post Link twice in your screenshot, though.

I noticed the icon uses an asterisk, which suggests it may be a custom post type. I just so happen to have one such defined for the theme I'm running, like so:

```
// Create a custom post type.
function myplugin_custom_post_type() {
	register_post_type( 'podcast',
		array(
			'labels' => array(
				'name' => __( 'Podcasts' ),
				'singular_name' => __( 'Podcast' )
			),
			'public' => true,
			'has_archive' => true,
			'rewrite' => array('slug' => 'podcast'),
			'show_in_rest' => true,
			'supports' => [
				'title', 'editor', 'custom-fields', // Custom fields must be supported for meta handling to function.
			],
		)
	);
}
add_action( 'init', 'myplugin_custom_post_type' );

// Assign a post template to our custom post type
function myplugin_register_template() {
	$post_type_object = get_post_type_object( 'podcast' );
	$post_type_object->template = array(
		array( 'core/heading', array( 'level' => 3, 'content' => 'Description', ) ),
		array( 'core/paragraph', array( 'placeholder' => 'Add description', ) ),
		array( 'core/heading', array( 'level' => 3, 'content' => 'Heading', ) ),
		array( 'core/paragraph', array( 'placeholder' => 'Add show notes', ) ),
	);

	// Lock the template from being rearranged or items deleted.
	$post_type_object->template_lock = 'all'; // Can be "all" or "insert", the latter allows moving blocks around.
}
add_action( 'init', 'myplugin_register_template' );
```

I'm not sure why the label calls it "post" — can you glean from the code above? Also CC: @gwwar as I recall she worked on that recently.

> Only for FSE themes, but it can still be tested perfectly fine in Twenty Twenty One.

Yep, I'll take a look. 

> I think it'd be best to remove the custom nav block (accordion) styles from the navigation editor and make them part of the block as a first step - I made this issue #29747.

That would help us avoid code written just for the screen, makes sense. I'd love to pair with you on that if you can use my help. I'll take a look at the page list background now though.

> Also wondering why your screenshots looks so different? Is that with a particular theme?

Most of the time I test running "Empty Theme" from https://github.com/WordPress/theme-experiments, which is a super barebones FSE theme. That makes it easier for m to know whether the theme influences feature styles or not.

**Comment by jasmussen** [comment]
PR to fix the horizontal scrollbar here: https://github.com/WordPress/gutenberg/pull/29930

**Comment by gwwar** [comment]
> I'm not sure why the label calls it "post"

As requested, I added a new post label for this. For i18n it's best not to build strings using parts of translated strings. See discussion in https://github.com/WordPress/gutenberg/pull/29095#discussion_r581769179

To see the right labels, we can edit the plugin and add `item_link` and `item_link_description` to the taxonomy or post-type definition.

<img width="944" alt="109557321-cbe93300-7a8c-11eb-87d5-e7c169b88581" src="https://user-images.githubusercontent.com/1270189/111481243-fcb5a300-86ef-11eb-961f-958e08d70d3d.png">
