### ISSUE TITLE
Buttons block: Missing typography controls

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#29112]
**We are adding typography and color controls to the text blocks that still do not have these features.**

This issue is focused on the Buttons block that still needs typography controls.

![Screen Shot 2021-02-18 at 13 22 04](https://user-images.githubusercontent.com/5323259/108356365-552a7b00-71ec-11eb-9ea7-9a384e00e4f7.png)

Associated issue:
Consider adding color and text size customizations to all text-based blocks.
#8171

**Comment by paaljoachim** [comment]
Typography controls in the Buttons block has now been merged!

**Comment by mhbManchester** [comment]
The buttons block module is pretty primitive.  It isn't possible to change the fonts - the preferred theme font gets overridden by a horrible serif font.  Adding html usually results in an error.

**Comment by paaljoachim** [comment]
Hey @mhbManchester 

It would be great if you can open a new issue for this.
Thanks.
