### ISSUE TITLE
Full Site Editing: WSOD when WooCommerce plugin is enabled

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#29132]
## Description

The site editor renders a white screen of death when the the WooCommerce plugin is installed and activated on the WordPress instance

## Step-by-step reproduction instructions

1. Provision a local WordPress instance with Gutenberg
2. Navigate to Plugins > Add New from wp-admin
3. Install and activate the WooCommerce plugin
4. Enable a block theme like TT1 or Seedlet-blocks
3. Navigate to the site editor
4. Verify that the screen is blank and remains blank

### WooCommerce Enabled
<img width="1344" alt="Screen Shot 2021-02-18 at 6 13 10 PM" src="https://user-images.githubusercontent.com/5414230/108447622-0d6c1980-7215-11eb-8ccb-2d3d41f78936.png">

### Site Editor WSOD
<img width="1344" alt="Screen Shot 2021-02-18 at 6 10 18 PM" src="https://user-images.githubusercontent.com/5414230/108447512-dc8be480-7214-11eb-96ca-f19cd3309fbd.png">

**Comment by chthonic-ds** [comment]
Earlier reports: https://github.com/WordPress/gutenberg/issues/29050 and https://github.com/WordPress/gutenberg/issues/27938

**Comment by jeyip** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3626
