### ISSUE TITLE
[Button block] Link rel can be interpreted as the button URL

### ISSUE THREAD

**Issue by jarekmorawski** [WordPress/gutenberg#29141]
## The issue
👋 Hi there!

I'm not sure if this has been reported somewhere already but I've identified a potential usability issue with editing links in the button block. I discovered it after posting a blog post with a broken button link.

**It's not entirely clear that rel is not the same thing as the actual button URL which can result in confusion and misunderstanding.**

In the sidebar, in the "Link settings" section, we've got an input labelled as "Link rel". To people not proficient in HTML who do not understand what `rel` is, this may mean the target URL linked to the button (especially since many blocks have more or less basic configuration in the sidebar and cannot be manipulated directly using the toolbar).

![image](https://user-images.githubusercontent.com/79307566/108519423-e6bbea80-72c9-11eb-93b7-4ab3c692b449.png)

## Proposed solution
This problem requires a more in-depth design attention. From the top of my head, I can suggest adding:

- a field description to explain that link rel is not the same as the button URL,
- a link to the docs,
- a help tip to point users toward editing the actual button URL,
- moving this setting to the Advanced section,
- a spotlight appearing after adding the block for the first time.

**Comment by skorasaurus** [comment]
I encountered this as well at my workplace when we first began using button blocks. 

This has been reported on trac as well https://core.trac.wordpress.org/ticket/50803

**Comment by SukcesStrony** [comment]
What is actually missing is the `href` field (with a `Link URL` description) in the Settings panel for the Button Block. We need it and then the `rel` field will be clear, although that field should be moved to the `Advanced` section in my opinion.

**Comment by jarekmorawski** [comment]
@SukcesStrony Thanks for the comment! Adding a `href` field was my first thought too but given that currently users can edit the URL from the toolbar, duplicating this functionality in the sidebar would only introduce more confusion, I think. 🤔

**Comment by SukcesStrony** [comment]
@jarekmorawski No, it wouldn't. What is more confusing is having all but 1 (main) field in the settings area. There's even an "Open in a new window" toggle which is duplicated from the tooltip. The settings area should have the main setting in it.

**Comment by jameskoster** [comment]
I would err towards _not_ duplicating toolbar options in the Inspector if we can help it. Here are two small adjustments we might make to address this issue:

1. Move the "Link rel" input to the "Advanced" section as mentioned above
2. Add helper text to clarify what this input is actually for

With reduced prominence, and improved clarity I hope that users will be less likely to mistake the rel input for the destination url.

**Comment by skorasaurus** [comment]
There's an existing issue for this at https://github.com/WordPress/gutenberg/issues/20208 

How about we continue the conversation at #20208 and follow its progress there.
