### ISSUE TITLE
Buttons with Borders

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#29149]
## Description
Due to this recent change (#28514) button blocks not receive a border style by default. 

I see that this was to ensure that buttons WITH borders and buttons WITHOUT borders were the same size, but the result is that any theme that does not supply a border color for buttons receives this default black border.

Note that this is also ONLY an issue in the view as the editor does not appear to receive those stylistic changes.

## Step-by-step reproduction instructions

With Gutenberg 10 activated,
Activate the theme 'Dara'.  Add a button to a page.  Note the style of the button in the EDITOR and in the VIEW.  The button in the VIEW has an black border around the button.

Note that themes that supply a border color for stock buttons don't have this issue.

## Expected behavior

Buttons should either have no border defined by default.

## Actual behaviour

Buttons that did not have a border defined in their theme have one now.

## Screenshots or screen recording (optional)

View (before this change)

![image](https://user-images.githubusercontent.com/146530/108523354-cc6b1800-729b-11eb-9358-b11578d010cd.png)

View (after this change)
![image](https://user-images.githubusercontent.com/146530/108518374-78aa0000-7296-11eb-8a26-808c7eda4105.png)

![image](https://user-images.githubusercontent.com/146530/108523405-dc82f780-729b-11eb-937d-1e715bb23819.png)

Editor (change agnostic)
![image](https://user-images.githubusercontent.com/146530/108523451-eb69aa00-729b-11eb-9e2d-c393da7eb0fb.png)

## WordPress information
- WordPress version: Latest
- Gutenberg version: 10.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Alva (likely others)

**Comment by talldan** [comment]
@jasmussen - just making you aware of this one.

**Comment by jasmussen** [comment]
Thanks for the report, and thank you for the ping. I created a hotfix in #29206, and will look separately at a PR to fix the heights.
