### ISSUE TITLE
Isolated template part editing view could use some refinement

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29148]
Here's what editing a template part in isolation (via the sidebar menu in the Site Editor) looks like currently:

<img width="1782" alt="Screenshot 2021-02-19 at 15 04 03" src="https://user-images.githubusercontent.com/846565/108521535-ba9d6b00-72c3-11eb-9b14-f4486688c541.png">

Here are a couple of opportunities for improvement I see:

- The boundaries of the template part are not clear.
- The template part occupies the entire width of the canvas, parts that render in narrower containers look odd in this context. Now that the canvas is inside an iframe perhaps we can add resize handles?
- The "Template" tab in the sidebar should read "Template part" and contain an option to set the name and area.

Any other thoughts?

**Comment by mtias** [comment]
A while ago we had this, with the separation on the backgrounds.

![image](https://user-images.githubusercontent.com/548849/108528510-ca24b000-72d3-11eb-8cdf-8a6360042fd6.png)

We should constrain the iframe to signal you are editing just a part. It'd be neat to support resizing the canvas to see how a unit scales responsively cc @ItsJonQ 

![image](https://user-images.githubusercontent.com/548849/108528689-f7715e00-72d3-11eb-9055-b85165a1e9ae.png)

**Comment by ItsJonQ** [comment]
> The boundaries of the template part are not clear...

@jameskoster I agree with you and @mtias in that the Template Part editing view should focus on the part only. Not unlike seeing a single "frame" in Figma (or "Artboard" in some other apps like Illustrator)

I think having iFrame + resize handlers would be good for site editing in general :)

**Comment by jameskoster** [comment]
> I think having iFrame + resize handlers would be good for site editing in general :)

One extra thing to consider here is the relationship between the desktop / tablet / mobile views in the "Preview" menu, and a user-specified width on the iframe.

**Comment by jameskoster** [comment]
Related: A loose "isolated" view for editing Reusable blocks was shared in https://github.com/WordPress/gutenberg/issues/29337. Perhaps we can reuse some of the ideas there in our explorations here.

**Comment by annezazu** [comment]
Wanted to include some feedback [from the second FSE call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1360):

> I see the isolated view. Header area in the main layout. Header name in the top toolbar. An empty Block Inspector in the sidebar settings. Instead of an empty Block Inspector when first entering isolated view. A message saying “Viewing Header template” could come up in the empty Block Inspector area. As it would bring a confirmation that one is only seeing the Header template.

Perhaps adding in some sort of notice similar to the template editing notice would help here so people don't accidentally start building out a template in a template part for example. Ideally, similar to the template editing notice, it would be sticky: https://github.com/WordPress/gutenberg/issues/28175

**Comment by jameskoster** [comment]
Realistically I don't think there's anything we can do to 100% stop folks from making this mistake, but general chrome optimisations will hopefully help.

On the subject of the block inspector, when you're editing something like a Template Part in isolation, I think the primary tab (normally "Post" or "Template") should be titled "Template Part" and contain all the relevant controls.

I'm working on designs for this at the moment and will hopefully have something to share soon :)

**Comment by jameskoster** [comment]
Here's an initial take on this:

https://user-images.githubusercontent.com/846565/109802968-5f9b3a80-7c18-11eb-91c4-d2e6f02b1426.mp4

The isolated editing view can be accessed from two locations:

1. The "Template Parts" section of the Sidebar Menu in the Site Editor
2. The ellipsis menu in the Template Part (and possibly Reusable Block) toolbar, as seen in the video

Once in isolation mode, the UI around the Template Part adapts in a number of ways:

<img width="1538" alt="Screenshot 2021-03-03 at 12 25 14" src="https://user-images.githubusercontent.com/846565/109805567-87d86880-7c1b-11eb-869e-1fe351fdd8d6.png">


1. In the Inspector, the "Block" tab from template editing view becomes a "Template Part" tab, akin to the Post / Page / Template tab, and the controls are migrated accordingly. This is potentially something we can expand upon in the future.
2. The Top Bar indicates that the Header is being edited.
3. A "< Back" button is revealed on the canvas which when clicked returns the user to the referring context
4. The Template Part is inset on the canvas, clearly indicating its boundaries
5. An input on the border of the Template Part allows users to test how it behaves at specific widths
6. A drag handle provides a looser equivalent of the above for quick-checks
7. A "Custom" option is added to the view options. This could even be something we bring to post and template editing in the future.

Thoughts and feedback:

* Do we need a cancel button along with the <Back button, so that folks can return to the thing they were editing and discard any changes to the Template Part?
* I based the drag handle styling on the block toolbar. Totally open to other suggestions there.
* Likewise the width input is a g2 unitinput, which hasn't been merged yet. So we may need a standard input in lieu of that.

**Comment by jameskoster** [comment]
Noticing a few other designs building around the concepts shared here. Might be time to assemble a draft PR since there hasn't been much design feedback.

**Comment by jameskoster** [comment]
Probably worth considering the part patterns will play in this environment, particularly some of the ideas we explored in https://github.com/WordPress/gutenberg/issues/28737#issuecomment-782052856.

Edit: Also whether one might access isolated tp editing via the new persistent list view.

**Comment by jameskoster** [comment]
> Also whether one might access isolated tp editing via the new persistent list view.

We could potentially include an action on the row to enable this:

![access isolated view](https://user-images.githubusercontent.com/846565/113879451-6e928100-97b2-11eb-968b-59abde148d8d.gif)

**Comment by talldan** [comment]
A question about the button in List View ... how do we reconcile that with the desire to also have block movers and other UI (like editable block names) in List View?

It feels like trying to cram a lot in. I'm also ignoring the past resistance from the accessibility team when it comes to introducing grid keyboard interaction patterns in List View.

Could it be worth trying the list view toolbar idea again (https://github.com/WordPress/gutenberg/pull/21372)? In the past some design contributors have been keen on this, some not so much, but it seems like every option explored has trade-offs.

----

Something separate that I've been thinking about—is there a reason to limit this feature to just Template Parts? Maybe template parts are where the feature is explored first, but it could also have value for other blocks (reusable, group). Almost an extension of the spotlight mode.

**Comment by mtias** [comment]
@talldan yes, starting with template parts because it's the one that needs it the most, but we should extend it to reusable blocks which are the other kind of symbol. I'd avoid adding it to normal blocks.

It's not yet clear what items would be exposed (movers, ellipsis, locking, spotlight/focus mode, insert before/after, delete, etc). The toolbar for list view feels quite disconnected from the item it handles. Actions on the item is a very common pattern in software that relies on layers, so i think we need to do our outmost to build something usable there.

**Comment by noisysocks** [comment]
Hi! @kevin940726 and I were just discussing this. 

We're wondering about how the isolated template part editor that this issue refers to ties in with the **isolated template editor** that you can get to from the post editor. This one:

<img width="1692" alt="Screen Shot 2021-09-08 at 15 49 29" src="https://user-images.githubusercontent.com/612155/132453585-88e339e3-5ed5-4364-8ca0-704031bca959.png">

- Should both isolated editors look the same?
- Should a user be able to access the isolated template part editor via the isolated template editor?

**Comment by mtias** [comment]
We are not calling the template editor "isolated" because it has nothing to isolate: it's just the full template. They should converge visually in terms of the background color and the navigation ("<- Back").

> Should a user be able to access the isolated template part editor via the isolated template editor?

Possibly yes, it's not yet established how exhaustive the template editor you invoke from a post / page view is going to be, but the ability to focus on a template part or reusable block should be indistinct regarding context.
