### ISSUE TITLE
Link popover appears "above" modals

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#29158]
If you click a link in a paragraph, a little popover appears that displays the link's URL and an button to edit the link. While this popover is open, you can then _also_ open a modal. When both a popover and a modal are displayed at the same time, their z-index conflicts:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/191598/108543032-7f467080-72b2-11eb-8e3f-904426770f31.png">

This is because both the popover and modal components have the same z-index of 1000000:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/191598/108543137-a9982e00-72b2-11eb-9e2e-04cbf998585e.png">

I suggest we update the z-index for the modal component (found here: https://github.com/WordPress/gutenberg/blob/6b89639c8cd5f75498272052a932d578b97fe75e/packages/base-styles/_z-index.scss#L122) to 1000001.

**Comment by annezazu** [comment]
From what I can see, this is no longer the case with the new preferences modal (tried with keyboard shortcuts and the welcome guide too):

<img width="1413" alt="Screen Shot 2022-02-07 at 12 17 09 AM" src="https://user-images.githubusercontent.com/26996883/152750172-437595b6-9a11-45ea-ae7a-12687ef5b213.png">

Going to close this out as a result!
