### ISSUE TITLE
Add a UI element that enables template parts to be assigned to areas

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29152]
Now that we have an "area" taxonomy for template parts (#28410) we'll need to update the UI so that users can assign template parts to these areas. This is mentioned briefly in #29148 but I think warrants its own exploration, as it may be possible to set the template part area while editing a regular template _and_ when editing the template part itself in isolation.

**Comment by david-szabo97** [comment]
Just noting we already have some exploration here as well.
https://github.com/WordPress/gutenberg/issues/27875

**Comment by jameskoster** [comment]
Ah yes, this one:

<img width="322" alt="Screenshot 2021-02-22 at 10 19 22" src="https://user-images.githubusercontent.com/846565/108694890-8dd19980-74f7-11eb-8b6b-473bffa5970b.png">

Let's refine the copy in the PR :)

**Comment by jameskoster** [comment]
Jeez I've been going in circles this week 😂 Closing this in favor of #29295.
