### ISSUE TITLE
Site Editor: theme styles are not applied in template previews

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29166]
If you use tt1-blocks theme and hover over template or template part previews, you'll notice that styling line background color is missinig.

<img width="645" alt="Screenshot 2021-02-19 at 22 07 36" src="https://user-images.githubusercontent.com/1182160/108561833-2bae4400-72ff-11eb-86bf-739efe8c4e2f.png">

**Comment by Mamaduka** [comment]
Hi, @vindl

I think we can close this issue, the recent design iteration doesn't include template previews.
