### ISSUE TITLE
Post Excerpt: Read more link/button

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#29168]
By default the  excerpt block doesn't output a read more link. In the editor I see:

<img width="647" alt="Screenshot 2021-02-19 at 21 26 29" src="https://user-images.githubusercontent.com/275961/108563387-47aee700-72f9-11eb-9f55-a994b5a2275f.png">

But in the front end the "Read more" link isn't output. 

When I edit the read more link the cursor is a pointer, but I think it should be a caret.

Also in themes we often add the post name after the read more link but hidden with the screen-reader-text class, for accessibility, so it would be good to do the same in this block.

**Comment by annezazu** [comment]
This was also reported as [part of the fifth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/) by Justin Tadlock [in this article](https://wptavern.com/fse-outreach-round-5-venturing-out-a-query-quest), [by Susan here](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1490), by [Kristen here](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1509), by [Jonas here](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1519), and by [Oliver here](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1552):

> For the more-link, it simply did not appear on the front end. When viewing the source code, the wrapper HTML was there, but the actual text was nowhere to be found.

>I did find the Read More button confusing because it looks like a button in the editor, but I couldn’t find any way to style it and it doesn’t work as a button on live. I looked for a block I could add to the query for this too, but didn’t see one.

>The “Read more” button has no function. The link to the post is missing, right?

>“Read more” link is not intuitively editable. There is no cursor caret displayed when clicking the link in editor, only after you start typing something. Plus it outputs HTML on front-end even if there is no text set for the “Read more” link.

It's unclear if this is meant to be a placeholder but, in the current iteration, one expects it would show up on the front end. If it's meant to be a placeholder, we should update it to make it clear that action is needed for it to work. Right now, if you do change the text of the link, it does appear on the front end as well:

<img width="519" alt="Screen Shot 2021-04-16 at 12 13 04 PM" src="https://user-images.githubusercontent.com/26996883/115066677-1bed4f00-9ead-11eb-8d28-274bd819f283.png">

**Comment by carolinan** [comment]
I don't think it is possible to correctly add a title after an unknown text, and there may be problems with translations.

**Comment by carolinan** [comment]
<del>The heading placeholder says:
`Write heading...`
the quote placeholder says
`Write quote...`
`Write citation...`
and the post author byline placeholder says:
`Write byline...`
</del>
So I think the text should be "Write read more text..."
Or "Write read more link text...

The current aria-label is "Read more link text"

Edit: Ignore all of the above, I refreshed my page and it now says " Add quote" not "Write".
See https://github.com/WordPress/gutenberg/pull/30404

**Comment by carolinan** [comment]
I am not able to reproduce the part where the cursor is a pointer, please confirm.

**Comment by ntsekouras** [comment]
This seems to have been resolved with the above PR: https://github.com/WordPress/gutenberg/pull/30959, as it makes it clearer to the user that they see a placeholder there, no? @scruffian should we close this one?

**Comment by scruffian** [comment]
Yes, we can close now :)
