### ISSUE TITLE
Replacing image of Image block - size of menu problem

### ISSUE THREAD

**Issue by ash-f** [WordPress/gutenberg#29161]
"Replace" menu of Image block is shown incorrectly.
I need to scroll the menu content in order to use it.
https://share.getcloudapp.com/GGu6Erzb

This seems to happens on Chromium browsers such as  Chrome/Edge.

**Comment by ash-f** [comment]
I noticed:
WordPress with Gutenberg plugin = ok
WordPress without Gutenberg plugin = problem

So this is fixed in  Gutenberg plugin and coming to WordPress core?

**Comment by talldan** [comment]
> So this is fixed in Gutenberg plugin and coming to WordPress core?

Hi @ash-f Yes, this should be fixed in WordPress 5.6.2
