### ISSUE TITLE
Site Editor: missing preview for Content submenu items

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29164]
If you open the Browsing Sidebar and hover over template or template parts entries, the preview will be displayed on the right side. 

<img width="645" alt="Screenshot 2021-02-19 at 22 07 36" src="https://user-images.githubusercontent.com/1182160/108561658-e8ec6c00-72fe-11eb-8568-906e6b95aa9d.png">

The same thing is not happening when hovering over Content submenu entries like Pages or Posts.

**Comment by Addison-Stavlo** [comment]
https://github.com/WordPress/gutenberg/pull/29225 should resolve this
