### ISSUE TITLE
Noto Serif Font Missing in GB 10.0

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#29177]
## Description

When no editor style is defined, the default styling uses Noto Serif via Google. _However, the font is not included, and no attempt is made to load it_, so the browser falls back to Times New Roman

## Step-by-step reproduction instructions

On a site that uses the default block editor styling, install and activate the Gutenberg plugin, then create a post

## Expected behaviour

The text appears in the Noto Serif typeface as specified in the default stylesheet, or falls back to system fonts

Note that the problem is not that Noto Serif fails to load, it's that it is never attempted. There is no failed request, because it was never requested.

## Actual behaviour

The typeface is specified, but not present. The browser uses the default font instead ( Times New Roman ) of the system font stack

## Screenshots or screen recording (optional)

<img width="846" alt="Screenshot 2021-02-20 at 13 48 11" src="https://user-images.githubusercontent.com/58855/108597710-66a58b80-7382-11eb-934d-7eb433714542.png">
<img width="846" alt="Screenshot 2021-02-20 at 13 48 45" src="https://user-images.githubusercontent.com/58855/108597712-673e2200-7382-11eb-9c42-5d6c29f7394c.png">

expected:
<img width="562" alt="Screenshot 2021-03-02 at 13 24 58" src="https://user-images.githubusercontent.com/58855/109655087-c9550f00-7b5a-11eb-9193-d7aa69d30379.png">

actual:
<img width="562" alt="Screenshot 2021-03-02 at 13 24 28" src="https://user-images.githubusercontent.com/58855/109655105-ce19c300-7b5a-11eb-96cc-d51d6dc315a2.png">

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 10.0.0
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No, but I reproduced using multiple themes from different vendors

## Device information
- Device: MBP 13" Intel
- Operating system: MacOS 11.2 Big Sur
- Browser: Chrome 88

**Comment by tomjn** [comment]
This snippet hot-fixes the problem:

```php
add_action( 'enqueue_block_editor_assets', function () {
        wp_enqueue_style( 'wp-editor-font' );
} );
```

Without this, themes that do not register an editor stylesheet have broken typography, as well as themes that do not specify a font family in their editor stylesheets

**Comment by tomjn** [comment]
I believe this PR is related https://github.com/WordPress/gutenberg/pull/26822

**Comment by talldan** [comment]
@tomjn What's a good theme to test this with?

Separately I did some digging, it looks like the noto serif font is/was defined in WordPress core. It was removed here, which will be a change that goes into WP 5.7:
https://github.com/WordPress/wordpress-develop/commit/d041904a7d68078d307f0c7e679b5acc1aed6d9b

This is the associated trac ticket - https://core.trac.wordpress.org/ticket/46169.

Will need to ascertain how this will work for those using Gutenberg with older versions of WordPress.

**Comment by tomjn** [comment]
hmmm it sounds like this needs retesting but on WP v5.7

Currently this impacts my own sites theme at https://github.com/tomjn/tomjn.com, I have't tested elsewhere yet given time available

**Comment by talldan** [comment]
I'm not too familiar with the change. There is a comment in #26822 which mentions that falling back to system fonts is accepted as a reasonable consequence - https://github.com/WordPress/gutenberg/pull/26822#issuecomment-738818402

@jasmussen I think you've been involved in this change, any thoughts?

**Comment by talldan** [comment]
Also cc @aristath as the reviewer.

**Comment by aristath** [comment]
Thanks for the ping :)
Yes, Note Serif will no longer be loaded by default. It was decided to remove it for improved performance and privacy since system fonts are acceptable and loading a google-font raises GDPR questions & concerns.
It always was a pretty, but opinionated font-family and was used as a fallback in case the theme was not defining any font-families on its own when Gutenberg was just starting.
Nowadays most themes add their own styles and font-families which is why it was deemed the right time to remove it from core. Not a bug 👍

**Comment by tomjn** [comment]
@aristath @talldan **but it does not fallback to system fonts.**

There's a font stack for system fonts available, but that styling rule is overriden by a font-family directive that says only Noto Serif can be used.

So instead of nice system fonts such as Arial or Helvetic, we get the default unstyled font.

<img width="506" alt="Screenshot 2021-03-02 at 13 17 23" src="https://user-images.githubusercontent.com/58855/109654054-a5dd9480-7b59-11eb-9eb4-af6e577b16f9.png">


Honestly, I don't care if it uses Noto Serif or system fonts, but right now it uses neither.

**Comment by tomjn** [comment]
Note that this is not a feature request that Noto Serif be restored.

This is a request that the `font-family: 'Noto Serif';` rule be removed when Noto Serif is not enqueued.

**System fonts are not used when falling back to system fonts**

**Comment by aristath** [comment]
My apologies, I misunderstood the issue 😅 

Checking it now

**Comment by aristath** [comment]
This is indeed caused by this change: https://github.com/WordPress/gutenberg/pull/26822/files#diff-27913c4345b92dfdf4a82588f72fcf266a13ed255f723a63966b5d70dba4e79a and happens on WP5.6 + Gutenberg10. On WP5.7 there is no issue.

The only solution I could find to allow both new and old versions to work was adding this snippet:
```php
add_filter( 'gettext_with_context', function( $translation, $text, $context, $domain ) {
    if ( 'default' === $domain && 'CSS Font Family for Editor Font' === $context && 'Noto Serif' === $text ) {
        return '-apple-system, BlinkMacSystemFont,"Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell,"Helvetica Neue", sans-serif';
    }
    return $translation;
}, 10, 4 );
```

It works, but feels very hacky. 🙊 
@jasmussen we could use your feedback on this one, any ideas?

**Comment by jasmussen** [comment]
Tricksy. Let me be sure I get this matrix right:

- WP 5.6 vanilla: Noto Serif, works well
- WP 5.6 + Gutenberg 10: Noto Serif, but broken
- WP 5.7 vanilla: System fonts, works as intended
- WP 5.7 + Gutenberg 10: System fonts, works as intended

If this is right, then it's 1 out of 4 cases that's broken, and broken in a way that is temporary until WordPress is upgraded to 5.7, correct?

I'm unsure how widespread the issue is given the matrix, would a temporary solution be to suggest your hack be added to the functions.php file on the affected site?

**Comment by aristath** [comment]
> If this is right, then it's 1 out of 4 cases that's broken, and broken in a way that is temporary until WordPress is upgraded to 5.7, correct?

Correct.

> I'm unsure how widespread the issue is given the matrix, would a temporary solution be to suggest your hack be added to the functions.php file on the affected site?

It would be best if we could find some other solution, I consider that snippet an ugly last resort. 😅 
We can use it in tickets as a temporary solution, or we could add something similar to that in the `compat.php` file wrapped in a WP version-check so it only runs for those that need it 🤔

**Comment by jasmussen** [comment]
I don't have a strong opinion. Does this affect classic themes that do not add an editor style, but run the 5.6 + plugin combination? If yes, then you approach might be good as a tightly scoped hack perhaps?

**Comment by aristath** [comment]
PR in #29501

**Comment by bantilan** [comment]
> This is indeed caused by this change: https://github.com/WordPress/gutenberg/pull/26822/files#diff-27913c4345b92dfdf4a82588f72fcf266a13ed255f723a63966b5d70dba4e79a and happens on WP5.6 + Gutenberg10. On WP5.7 there is no issue.

I see, that is why I no longer see the "Noto Serif" on the editor.

**Comment by bantilan** [comment]
@aristath, please check my comment on your PR.

**Comment by tomjn** [comment]
Now that WP 5.7 is out, I'm closing this. Anybody encountering this issue should upgrade to WP 5.7

**Comment by tomjn** [comment]
@bantilan you should update to WP 5.7 or stick to the block editor version that came with 5.6 until you can upgrade

**Comment by bantilan** [comment]
Hi @tomjn, I am already using WP 5.7, this issue happen after upgrading Gutenberg to 10.2.1. 

Here is my Gutenberg editor look like right now (Or is this the new update?):
![image](https://user-images.githubusercontent.com/1697297/111854589-f1b27b00-895a-11eb-83c5-2a05f5c2fac4.png)

**Comment by tomjn** [comment]
@bantilan you claimed on the PR you were running the GB plugin with 5.6, and that it does not happen on 5.7:

> happens on WP5.6 + Gutenberg10. On WP5.7 there is no issue.

If this is happening on WP 5.7 for you then you need to open a new issue. Confirm first that this happens in a default theme, it's possible your themes editor style does not declare a font family.

**Comment by bantilan** [comment]
Hi @tomjn , 

I was able to fixed it after uninstalling the Gutenberg plugin.. _( I have this plugin since the first launch of Gutenberg )_

I guess the problem is when using both the built-in plugin of WP 5.7 and the plugin version of Gutenberg.

**Comment by tomjn** [comment]
That sounds like a new issue, you should open a new issue and reference this one as similar but not the same
