### ISSUE TITLE
Please upgrade babel-eslint to @babel/eslint-parser in @wordpress/eslint-plugin

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#29179]
## What problem does this address?

`babel-eslint` module is deprecated and will no longer receive updates.

https://github.com/WordPress/gutenberg/blob/e3d64f5eb6f213b73c58f1a60b30c2577dc0da85/packages/eslint-plugin/package.json#L35

## What is your proposed solution?

Update to `@babel/eslint-parser`

**Comment by simonhammes** [comment]
I think this issue can be closed since it was fixed by https://github.com/WordPress/gutenberg/pull/36244.
