### ISSUE TITLE
Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#29180]
## Description

Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

## Step-by-step reproduction instructions

1. Install latest stable WP 5.6.1
2. Do not install any plugins
3. Go to Gutenberg editor

## Expected behaviour

No errors in the JS console

## Actual behaviour

Errors in the JS console:

```
Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```

## Screenshots or screen recording (optional)

<img width="1280" alt="Снимок экрана 2021-02-20 в 17 58 23" src="https://user-images.githubusercontent.com/780935/108601453-53f07e00-73a5-11eb-9b51-06d1eef352c1.png">

## WordPress information
- WordPress version:  5.6.1
- Gutenberg version:  Bundled
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  
Twenty Fifteen 

## Device information
- Device:  MacBook
- Operating system:  macOS Big Sur
- Browser:  Chrome 88.0.4324.182

**Comment by talldan** [comment]
@mahnunchik It looks like this is from the Yoast plugin. The `SnippetEditorFields` component isn't in gutenberg, but searching wpdirectory shows Yoast:
https://www.wpdirectory.net/search/01EZ4DCRPD8XXZ9PSXNNJMYSCQ
