### ISSUE TITLE
Add more advanced formatting documentation

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#29181]
## What problem does this address?

It is not clear how to show `Popover` on `RichTextToolbarButton` click?

* https://github.com/WordPress/gutenberg/blob/e3d64f5eb6f213b73c58f1a60b30c2577dc0da85/packages/block-editor/src/components/rich-text/toolbar-button.js#L7
* https://developer.wordpress.org/block-editor/components/popover/

## What is your proposed solution?

It would be useful to have sample here: https://developer.wordpress.org/block-editor/tutorials/format-api/2-toolbar-button/

**Comment by talldan** [comment]
@mahnunchik the RichTextToolbarButton is a shortcut for adding simple formatting, but the edit function when registering a format can be any react component. 

The easiest option is to use a `Dropdown` or `DropdownMenu` component and make the `renderToggle` prop return a `ToolbarButton`.

The Link format is probably the only one in the gutenberg codebase that's a bit more advanced:
https://github.com/WordPress/gutenberg/blob/master/packages/format-library/src/link/index.js

Agree that this is something the docs could expand on, so will leave this ticket open as a documentation enhancement.

**Comment by mahnunchik** [comment]
There are issues related to `RichTextToolbarButton` position in the Toolbar:

* How to add a toolbar button in toolbar but not in dropdown menu #14881
* Add filter to allow other formats to be placed outside the dropdown menu in RichTextToolbarButton #22663

**Comment by talldan** [comment]
Right, I see, the formats that appear on the main toolbar are hard-coded. 

And a dropdown in a dropdown may be undesirable.

**Comment by ryanwelcher** [comment]
This looks to have been addressed with https://github.com/WordPress/gutenberg/pull/43581 so I'll close it. If there are further issues, please feel free to open a new issue.
