### ISSUE TITLE
Site Logo Block: Add the same dimensions settings as the Image block

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29217]
## Description

The Site Logo block only has a "Image width" setting which not only can malfunction, it's also different than the dimensions settings of the Image block.

Since both blocks are used to render an image, they should have the same settings available.
For example, the Site Logo block should probably use the same `ImageSizeControl` component to handle its dimensions as the Image block.

## Step-by-step reproduction instructions

1. Insert a Site Logo block (add an image if needed), followed by a Paragraph block. 
2. Resize the logo using the resize handlers around the image itself.
3. Then, try resizing the logo using the slider in the block settings sidebar.

## Expected behaviour

The Site Logo wrapper resized along with the image.

## Actual behaviour

The Site Logo wrapper didn't resize appropriately, and the image was either overlapping the following block, or smaller than the wrapper.

## Screenshots or screen recording (optional)

| Original | Resize to Small | Resize to Large |
| - | - | - |
| <img width="622" alt="Screenshot 2021-02-22 at 12 11 41" src="https://user-images.githubusercontent.com/2070010/108706940-45ba7300-7507-11eb-9aee-b41b331b887b.png"> | <img width="666" alt="Screenshot 2021-02-22 at 12 11 17" src="https://user-images.githubusercontent.com/2070010/108706969-510d9e80-7507-11eb-8c9f-327332cd31ef.png"> | <img width="626" alt="Screenshot 2021-02-22 at 12 11 27" src="https://user-images.githubusercontent.com/2070010/108706993-55d25280-7507-11eb-851c-0a8133db8c98.png"> |

## WordPress information
- WordPress version: 5.7-beta2-50343
- Gutenberg version: 10.0.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Chrome 88.0

**Comment by annezazu** [comment]
This seems similar to this issue with the general Image block: https://github.com/WordPress/gutenberg/issues/12168

In terms of resizing, the current experience with the site logo is pretty bizarre using the Site Logo Settings so it would be great to create some consistency here across the two blocks in terms of how adjustments are made: 

https://user-images.githubusercontent.com/26996883/109567456-99e2cb80-7aa2-11eb-9317-fa7418467e66.mov
