### ISSUE TITLE
Create template part flow: Add "Area" selection input to modal.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29222]
When manually creating a template part from a selection of blocks, the following modal appears:

<img src="https://user-images.githubusercontent.com/846565/108350267-f0ffbb00-71db-11eb-957f-69d8ff971ce4.png">

Along with the template part name, we should also provide an affordance to specify the template part `area` (Header, Footer, etc).

We might use the dedicated icons for template parts in a segmented control arrangement to achieve this.

**Comment by aristath** [comment]
Should we also add `aside`? (not `sidebar`)

**Comment by jameskoster** [comment]
I think the input here should expose all `area`s. So if `aside` exists, it would appear as an option. I wonder if that's better left to the HTML element option though? 🤔

**Comment by jameskoster** [comment]
Blocked by https://github.com/WordPress/gutenberg/issues/29295

**Comment by jameskoster** [comment]
Removing the "Needs design" label since the "design" for this should be entirely informed by #29295.

**Comment by jameskoster** [comment]
On second thoughts, perhaps there is a case to be made for a more elaborate design here, since it may be the first time a user encounters the "area" concept.

![Create template part](https://user-images.githubusercontent.com/846565/110114209-28f62900-7dac-11eb-9f5b-0dae043b5110.png)

**Comment by paaljoachim** [comment]
I like the latest design. 
Clicking to "Create Template Part"
Shows Name and "category" for the part.
Such as Header, Footer and General. Perhaps Sidebar should be added as well.
So it becomes Header, Sidebar, Footer and General.

Thinking broader. A similar method can be used when creating a Pattern. User selects a name and the category the Pattern should be in.

**Comment by Addison-Stavlo** [comment]
>  Perhaps Sidebar should be added as well.

Once we are ready to support the 'sidebar' area it should definitely be part of the list.  Once we support a larger amount of options, perhaps that 'area' selection should have a max-height and scroll? 🤔
