### ISSUE TITLE
Block API: Icon (required or optional)

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#2922]
## Issue Overview
I updated the Block API docs in #2906. @youknowriad added in his review https://github.com/WordPress/gutenberg/pull/2906#pullrequestreview-67685542 that Icons shouldn't be optional. Let's discuss it in this ticket.

## Possible solutions
1. Optional without fallback (Current implementation)
2. Optional with default fallback icon
3. Required with check in `registerBlockType`

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Soean** [comment]
I think we should do it like the Custom Post Types and add a default icon.

**Comment by mtias** [comment]
Yes, a default icon is the most sensible.
