### ISSUE TITLE
Navigation block: Trying to add link results in block error when editing in Template Parts

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29237]
## Description

In trying to use the navigation block, I'm unable to add Page links and encounter an error message: "This block has encountered an error and cannot be previewed." This ONLY happens when in the Template Parts editing section. It works just fine in the Site Editor. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to Site Editor 
2. Use the W Menu to browse to the Header Template Part (Template Parts > Header)
3. Add a navigation block
4. Use the "start empty" option
5. Try to add a link and see error. 

## Expected behaviour

I expected to be able to edit the navigation block within the template parts screen. This works just fine when in the site editor experience but breaks when viewing the template part specifically. 

## Actual behaviour

Run into a block error. 

## Screenshots or screen recording (optional)

Video:

https://user-images.githubusercontent.com/26996883/108778544-bf138f00-7522-11eb-94ff-6f084be85b54.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

**Comment by ndiego** [comment]
I can confirm and I am getting a similar issue when trying to add links to any navigation item that is in a template part. Again, this only seems to be an issue when editing/viewing a template part directly. If you edit the template part while viewing an entire page in the Site Editor, this issue doesn't seem to occur.

**Comment by annezazu** [comment]
I'm not able to replicate this anymore with 10.2.1 and WordPress 5.7. @ndiego can you? :D If not, I'll close.

**Comment by annezazu** [comment]
Ah looks like there is a PR too in progress to fully fix any remnants of this as well. I'll wait until that's handled!
