### ISSUE TITLE
Site Logo Block: removing block with a selected image does not remove, only resets

### ISSUE THREAD

**Issue by mattwiebe** [WordPress/gutenberg#29234]
## Description
The Site Logo block reverts to its empty state (choose an image) when trying to remove the block with an active logo (save or not).

## Step-by-step reproduction instructions
1. Add a Site Logo block
2. Upload/choose an image from your library
3. Remove the block
4. See that the block has merely reverted to its empty state but hasn't been removed

## Expected behaviour
Block is removed when block is removed

## Actual behaviour
Block is reset to empty state rather than removed

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Chrome 88

**Comment by ntsekouras** [comment]
Hey @mattwiebe - I tried to reproduce but couldn't. Can you provide some more info or a screen recording of the problem you're facing? 

Thanks!

**Comment by david-szabo97** [comment]
I think we are talking about the Trash button in the toolbar when selecting a Site Logo. It removes the image selection so we can select a new image for the logo. This button is very confusing and in my opinion it shouldn't be there at all. We don't have this feature for the Image block so I don't think we should have this for Site Logo.

![image](https://user-images.githubusercontent.com/2256104/109000556-260c8180-76a4-11eb-8727-463cccc3731c.png)


cc @jameskoster

**Comment by jameskoster** [comment]
The only reason I can think to include this, is that it acts as a pseudo delete-all-site-logo-blocks tool. Since if there is no logo, any instance of that block will render nothing on the frontend.

That said, I don't think it is very effective, and overall it should probably just match the regular Image block (IE no "Delete" option in the toolbar).

**Comment by mattwiebe** [comment]
> I think we are talking about the Trash button in the toolbar when selecting a Site Logo

Ahh, yes, that's it. Very confusing.

I haven't dug into the code, but I assume that what it's doing is to delete the theme mod that's backing the site logo. In practice I don't know if this is important since it's not used anywhere else AFAIK. A better flow would be "pick a different image" or even something like "reset block" but delete is super confusing
