### ISSUE TITLE
Add ability to preview revisions

### ISSUE THREAD

**Issue by StuartFeldt** [WordPress/gutenberg#2923]
## Issue Overview
The ability to preview revisions can be very useful for editors to view what a revision looks like before they apply the revision.  This is especially important for published posts. 

## Related Issues and/or PRs
May help in a solution to #2544

**Comment by karmatosed** [comment]
What to do with revisions has been discussed before. For now, at least in what we propose for merge in Gutenberg though, we'll make sure the flow isn't broken, but not add in revision previewing. As a result going to close this.
