### ISSUE TITLE
- Design issue with Gradient Picker in Column Block for a RTL website.

### ISSUE THREAD

**Issue by RajkiranBagal** [WordPress/gutenberg#29245]
## Description
If a site is an RTL site then in the Columns Block > Color Settings > Background Color > Gradient option the settings gets messed up. 

## Step-by-step reproduction instructions
1. Make the site RTL.
2. Go to 'Columns Block > Color Settings > Background Color > Gradient'
3. The options design will be messed up.

## Screenshots or screen recording (optional)
https://a.cl.ly/6quQz95q

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: "Desktop"
- Operating system: macOS Catalina
- Browser: "Chrome 86.0"

**Comment by stokesman** [comment]
@RajkiranBagal, this definitely needs to be fixed. There's an existing for this #27352. I'll close this one as a duplicate.
