### ISSUE TITLE
Patterns: switching pattern category closes the pattern inserter on iOS (mobile web)

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#29243]
## Description

On mobile (tested with Chrome on iOS), when you switch pattern categories in the pattern inserter, when you tap `Done`, the inserter is closed.

I suspect that tapping Done in this context causes the inserter to lose focus, which would then trigger the inserter to be closed.

## Step-by-step reproduction instructions

1. On a real mobile device (in this case, I'm testing on an iPhone), go to add a pattern using the inserter.
2. From the pattern inserter, tap the category to open up the select options.
3. Select a different pattern category and tap Done to select it.
4. The pattern inserter will close.

Note: I could only recreate this issue on a real mobile device, as it worked fine in Chrome desktop when previewing at a mobile resolution.

## Expected behaviour

The pattern category to be switched, and for the pattern inserter to remain open.

## Actual behaviour

After switching pattern categories, the pattern inserter closes immediately.

## Screenshots or screen recording (optional)

| Inserter opened while selecting a category | After selecting the category the inserter is closed|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/108803119-fe5ae200-75ed-11eb-8c75-d17aa320359e.png) | ![image](https://user-images.githubusercontent.com/14988353/108803121-01ee6900-75ee-11eb-874a-d3233d9ec87d.png) |

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Twenty Twenty-One)

## Device information
- Device: iPhone 8
- Operating system: iOS
- Browser: Mobile Chrome

**Comment by talldan** [comment]
I tried testing in browserstack, but for some reason iOS doesn't work with my local environment.

I managed to test android, and can't reproduce there.

**Comment by andrewserong** [comment]
Thanks for testing and confirming that it's specific to just iOS!

**Comment by apeatling** [comment]
I was able to reproduce this in the iOS simulator.

**Comment by glendaviesnz** [comment]
If a breakpoint is inserted in iOS simulator then the panel remains open as expected, even if script is just continued as soon as breakpoint is hit, so maybe some sort of weird timing issue that the breakpoint interupts

**Comment by andrewserong** [comment]
Possible fix in: https://github.com/WordPress/gutenberg/pull/30717
