### ISSUE TITLE
Paragraph blocks don't have focus when added

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#29259]
## Description

Not sure since when, adding a paragraph block no longer moves the focus to the input itself, but rather a "parent"-ish block wrapper. Pressing <kbd>Enter</kbd> can no longer continue the writing experience either. See the below screencast for more info.

I haven't bisected the exact commit that causes this issue, but this feels unintentional and seems like a regression to me. It might be related to some focus-related work being done recently like #28191 and #28962. Pinging @youknowriad here for more insights 😉 .

## Step-by-step reproduction instructions

1. Go to the post editor by adding a new post
2. Add the first paragraph
3. Hit <kbd>Enter</kbd> to start a new paragraph
4. Type something and observe that the focus is not within the input hence no characters are being typed to the screen.

## Expected behaviour

Should be able to add/edit content more smoothly.

## Actual behaviour

The writing flow is blocked by unfocused inputs.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/7753001/108857525-25350a80-7626-11eb-8657-4d53380bc430.mp4

## WordPress information
- WordPress version: trunk 
- Gutenberg version: master 
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Desktop
- Operating system:  macOS
- Browser:  Chrome

**Comment by youknowriad** [comment]
I'm pretty sure we have e2e tests for this that would have caught it. Could you have another thing that could impact this.

**Comment by kevin940726** [comment]
Not that I'm aware of, no 🤔.

**Comment by stokesman** [comment]
I'm not seeing this either. One time, when I was seeing what I thought was a regression, it resolved when I restarted `npm run dev` (which clears the build directories).

**Comment by kevin940726** [comment]
Seems like this has already been fixed by https://github.com/WordPress/gutenberg/pull/29279, closing it now.
