### ISSUE TITLE
Image block: popup menu flickers when colliding with bottom edge of viewport

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#29255]
## Description

The popup menu flickers when colliding with bottom edge of viewport #29255

## Step-by-step reproduction instructions

1. Make sure that scrollbars are visible in your browser
2. Add an image in the editor
3. Click on the image block icon to reveal the popup menu
4. Scroll down until the popup menu "touches" the bottom of the viewport
5. Notice how the popup menu starts flickering and scrolling up is not possible

## Expected behaviour

The popup menu doesn't flicker, and scrolling works as expected

## Actual behaviour

The popup menu starts flickering and scrolling up is not possible

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1083581/108848392-3ad41100-75e1-11eb-8b94-f71b96c947c2.mp4

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? Yes (only Jetpack and Akismet are active)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device:  Desktop
- Operating system: MacOS BigSur 11.2.1
- Browser: Chrome 88.0.4324.182 (Official Build) (x86_64)

**Comment by gwwar** [comment]
Potentially related to https://github.com/WordPress/gutenberg/issues/24611

**Comment by paaljoachim** [comment]
I was not able to produce the same thing, but with a bit of resizing the Chrome browser on my Mac OSX 10.15.7, with WP 5.7 and Twenty Twenty One I was able to produce this (This has been speeded up to make the file size smaller):

https://user-images.githubusercontent.com/5323259/112537360-ddcda580-8dae-11eb-90ae-75067b1646fc.mp4

**Comment by gwwar** [comment]
I was able to reproduce something similar by very slowly resizing the browser near the style previews:

https://user-images.githubusercontent.com/1270189/112537716-4182af00-8d6c-11eb-894f-f89e042e232d.mp4

**Comment by miminari** [comment]
We discussed the issue in a triage session on slack today(https://wordpress.slack.com/archives/C02QB2JS7/p1624339362341100).

And reproduction was observed in several environments.

This Issue seems similar #31943 #24611.
We'd like to continue with #24611. Thank you!
