### ISSUE TITLE
Editor crashes when title support removed from "post" post type

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/gutenberg#29266]
## Description

When title support is removed from the "post" post type, the editor crashes when first clicked.

The crash appears to happen here:
https://github.com/WordPress/gutenberg/blob/0596f1ba178e6e01f987fc89e9f098f2896206d9/packages/editor/src/components/post-title/index.js#L68

## Step-by-step reproduction instructions

Using a test site, add an mu-plugin with the following code:
```php
<?php
function gh_crash_repro_remove_post_title_input() { remove_post_type_support('post', 'title'); }
add_action('init', 'gh_crash_repro_remove_post_title_input');
```

Try to create a new post with Gutenberg, click the editor after it loads, and observe the crash.

## Expected behaviour
The editor would be usable without title support.

## Actual behaviour
The editor crashes without title support.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/530877/108893157-c304e700-75de-11eb-9536-983f9ba5f296.mp4

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No -- Using TwentyTwenty

## Device information
- Device: Macbook
- Operating system: macOS Big Sur 11.2.1
- Browser: Brave, Chrome, and Firefox

**Comment by skorasaurus** [comment]
Thanks for reporting. 
Worth noting that this maybe something specific to the post type of 'post' and 'page' (I'm able to replicate this error on the page post type as well) since registering a custom post type without title capabilities will load the editor as expected. - ref https://github.com/WordPress/gutenberg/issues/26239

**Comment by ntsekouras** [comment]
Fixed by: https://github.com/WordPress/gutenberg/pull/29922
