### ISSUE TITLE
Site Editor + "/" slash inserter popover not visible when at template level.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29262]
This seems like it may be a more recent regression.  In the site editor, if we try to add a block at the template level and search via the `/` shortcut, the suggestions popover is not visible.  It is visible when in the scope of a template part or post content however.

Unexpected Behavior:
<img width="814" alt="Screen Shot 2021-02-23 at 11 06 56 AM" src="https://user-images.githubusercontent.com/28742426/108872573-4c5cef00-75c8-11eb-92da-b34c79528d50.png">

Expected Behavior:
<img width="677" alt="Screen Shot 2021-02-23 at 11 07 27 AM" src="https://user-images.githubusercontent.com/28742426/108872606-54b52a00-75c8-11eb-99bc-615ac65379f5.png">

**Comment by stokesman** [comment]
This the same but uglier version of what is reported here: https://github.com/WordPress/gutenberg/pull/28917#issuecomment-781996219. I say it's the same because it too is resolved with #29188.
