### ISSUE TITLE
No clear method to convert Reusable block back to regular blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#29268]
## Description

I see no method how to take a Reusable block and convert it back to a regular block.

## Step-by-step reproduction instructions
1. Create or add an existing reusable block to a page or post.
2. Figure out how to convert to regular blocks.
3. I am not able to see a method on how to do so.

## Expected behaviour
Earlier the toolbar contained a button to convert to regular blocks. It has been removed, and it looks like it has not been added any place.

I would expect to see it in the 3 dot menu drop down as an option to "Convert back to regular blocks". 

## Actual behaviour
No method to convert back to regular blocks.

## Screenshots or screen recording (optional)

(The reusable block is named Heading..)
![Screen Shot 2021-02-23 at 20 22 18](https://user-images.githubusercontent.com/5323259/108896442-3a556d80-7615-11eb-8e45-a3448deffd64.png)

## WordPress information
- WordPress version: 5.7 beta 3.
- Gutenberg version: 10.0.2
- Are you using a default theme (e.g. Twenty Twenty-One)? Using Twenty Twenty One.

Tracking issue: https://github.com/WordPress/gutenberg/issues/27890

@youknowriad

**Comment by mtias** [comment]
It's the button on the toolbar:

![image](https://user-images.githubusercontent.com/548849/108904143-6d502f00-761e-11eb-9db6-955e57b128bd.png)

**Comment by ranthonysteele** [comment]
That does appear to work now. It did not work at the time that I wrote the article https://ranthonyings.com/2021/02/gutenberg-editor-bug/ I tried clicking everything in sight the first few times I needed to access my code snippets saved as reusable blocks.

**Comment by paaljoachim** [comment]
The icon in use will need to be changed. Making it more clear what it does.
