### ISSUE TITLE
Template Navigation: previews are rendered but not shown on smaller screens

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#29278]
## Description

Previews of [templates](https://github.com/WordPress/gutenberg/pull/25739) and [content](https://github.com/WordPress/gutenberg/pull/29225) in the navigation sidebar seem to be rendering on smaller screens, even though they aren't shown.

<img src="https://user-images.githubusercontent.com/1699996/108924342-13d90780-7600-11eb-9618-d0f1376257d6.gif" width="750" />

## Step-by-step reproduction instructions

1. Open the site editor on a smaller screen
2. Click to show the template details at the top of the screen
3. Click "Browse all templates"
4. Hover over a template

## Expected behaviour

Nothing, really... possibly a preview, but I suspect it's better to omit this when screen space is limited.

## Actual behaviour

It appears that all the network calls used to render the preview are being made, so I assume it's being rendered but isn't visible.

## WordPress information

- WordPress version: 5.6.2
- Gutenberg version: 10.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: macOS
- Browser: Firefox

**Comment by mt8** [comment]
I tested this issue. Reproduced in the latest version. It is not displayed on small screens when editing "Templates > All Archives".

## WordPress information
WordPress version: 6.4.1
Gutenberg version: 17.0.2
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? Yes Twenty Twenty-Four

**Comment by tellthemachines** [comment]
@creativecoder is this still an issue? Clicking on the template name at top of screen no longer shows template details, and I think the former "Browse all templates" view has been replaced by "Manage templates" which seems to work reasonably well at small screen sizes:

<img width="568" alt="Screenshot 2024-04-05 at 1 48 16 PM" src="https://github.com/WordPress/gutenberg/assets/8096000/194dcee0-3b36-4c3b-9dc0-57bed9dbc0df">

**Comment by creativecoder** [comment]
No, this doesn't appear to be an issue since the UI has changed; I'll close it.
