### ISSUE TITLE
Incorrect usage of sprintf in block validation error logging in test

### ISSUE THREAD

**Issue by tmdk** [WordPress/gutenberg#29291]
## Description
While setting up some tests utilising `isValidBlockContent` outside of Gutenberg, I encountered a TypeError caused by the sprintf usage in `createLogHandler`. The TypeError went away after updating the sprintf-js to the same version used by Gutenberg, but the console messages generated while running the test still shows some substitutions that are probably not working as intended.

The problem seems to be caused by sprintf-js attempting to format a `%o` specifier as an octal number, instead of pretty-printing an object as expected by the validation functions.

A possible fix would be replacing the sprintf usage with `util.format` (see https://github.com/WordPress/gutenberg/commit/fbdd183b569d2fa63a80c555e6f55c14176e7917), but I wonder if that's actually more helpful than not preprocessing the message at all, since pretty-printing produces very noisy output in the terminal for some of the larger objects, as opposed to in the browser where these object are collapsed in the console output. I'm not sure what the original intent was of preprocessing the log messages specifically for test environments?

## Step-by-step reproduction instructions
1. Clone this demo repo: https://github.com/tmdk/gutenberg-block-validation-log-formatting-demo
2. Run `npm install && npm test`

## Expected behaviour
Test logs messages containing pretty-printed objects.

## Actual behaviour
Test logs messages containing `0` instead of pretty-printed objects.

## Screenshots or screen recording (optional)
![Screenshot 2021-02-24 at 10 07 27](https://user-images.githubusercontent.com/690621/108977803-382cf680-7689-11eb-8991-f15f20d2c700.png)

## WordPress information
- WordPress version: N/A
- Gutenberg version: @wordpress/blocks@7.0.4
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by talldan** [comment]
Thanks for reporting.

This is unusual as I'd fixed this previously in https://github.com/WordPress/gutenberg/pull/16173.

Looks like it regressed in this commit - https://github.com/WordPress/gutenberg/commit/3c85086ee4b2e2b2d1174c94b71e5802b8cd80f4#diff-41c68710601af56ef14c160b1bfde4c47b47de9f59be3c89763573a5ae7e7c9d.

I can't see a pull request associated with that commit, the commit went straight to `master`?

cc @gziolo.

**Comment by gziolo** [comment]
> Looks like it regressed in this commit - 3c85086#diff-41c68710601af56ef14c160b1bfde4c47b47de9f59be3c89763573a5ae7e7c9d.

Related PR: https://github.com/WordPress/gutenberg/pull/16862

Based on the screenshots from the browser I assume that #16173 fixed the output in tests but the handling is incompatible with what browsers expect which I changed while testing.

**Comment by talldan** [comment]
Thanks for finding the PR, I stand corrected.

**Comment by tmdk** [comment]
Thanks for looking into this, somehow I overlooked the earlier fix.

I've created a PR replacing the `sprintf` usage with `util.format`.
