### ISSUE TITLE
npm ERR! prepareGitDep  on npm ci script

### ISSUE THREAD

**Issue by Quintis1212** [WordPress/gutenberg#29303]
Hello ) I cloned gutenberg repo and  trying to run npm ci script in gutenberg folder ,but there is an errors :
![Снимок экрана от 2021-02-24 18-05-04](https://user-images.githubusercontent.com/34488718/109029275-587da500-76cb-11eb-9c06-50a57d70c713.png)
![Снимок экрана от 2021-02-24 18-05-26](https://user-images.githubusercontent.com/34488718/109029282-59aed200-76cb-11eb-853e-f48d5afae393.png)
![Снимок экрана от 2021-02-24 18-05-48](https://user-images.githubusercontent.com/34488718/109029287-5a476880-76cb-11eb-8f82-dda675de3913.png)
![Снимок экрана от 2021-02-24 18-06-09](https://user-images.githubusercontent.com/34488718/109029290-5adfff00-76cb-11eb-9bcc-1a1d181f1305.png)
![Снимок экрана от 2021-02-24 18-06-27](https://user-images.githubusercontent.com/34488718/109029294-5c112c00-76cb-11eb-8f66-19528c7f8a0e.png)
OS - Fedora 33 (Workstation Edition)
Can anyone help me ?

**Comment by talldan** [comment]
I haven't experienced anything like this, but I'm on Mac OS.

Out of interest, why use `sudo` when running `npm ci`? I'm not a regular linux user, but I thought that was generally regarded as bad practice. Might be worth searching for ways to do this without `sudo`, doing a quick search of the web it looks like there are quite a few articles that offer help on that matter.

**Comment by Quintis1212** [comment]
Hello talldan) It seems you are right , in another catalog it is all right , but I did  not find recomendatition about running scripts not with sudo

**Comment by talldan** [comment]
Did that solve the issue? I'll close anyway as we don't generally leave help requests open.

A few articles about sudo came up in a search when I checked: https://duckduckgo.com/?q=should+i+use+sudo+with+npm%3F&t=h_&ia=web
