### ISSUE TITLE
Template part block: Choose another dropdown is confusing

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29300]
Template part block's toolbar includes a dropdown button which is called "Choose Another".
![image](https://user-images.githubusercontent.com/2256104/109016751-c4094780-76b6-11eb-9bf8-27c97a7c32db.png)

It would make sense to replace this with **Replace** or with a more meaningful icon.

We use Replace in a couple of places, for example the Image block:
![image](https://user-images.githubusercontent.com/2256104/109017031-1185b480-76b7-11eb-9061-5dd02e874db7.png)

**Comment by mtias** [comment]
@jameskoster is looking at this here https://github.com/WordPress/gutenberg/pull/29257

**Comment by jameskoster** [comment]
Alternatively, might we consider removing this altogether for now? It is as yet unclear how important this behaviour will be compared to something like selecting a pattern inside a Template Part, see: #28737. 

Since it would still be possible to "switch" a template part by deleting and re-inserting the block, it seems fairly safe to remove this for now, if we want to.

Thoughts?

**Comment by mtias** [comment]
Yes, or keep it as an "advanced" action. I don't think it warrants a prominent placement. The integration of patterns in template parts is a much more important flow.

**Comment by jameskoster** [comment]
I think that being able to switch the template part 'variant' and change the area in the "Advanced" section of the Inspector could lead to some confusing interactions.

<img width="339" alt="Screenshot 2021-02-26 at 13 41 12" src="https://user-images.githubusercontent.com/846565/109307320-59801500-7838-11eb-8792-103af3df9992.png">

Imagine you change the area to "Footer". Suddenly the variant you selected is no longer valid... what would happen here?

I'm going to chalk this one up as another argument for not having these controls available at all, until you're editing the template part in isolation. It feels too confusing.
