### ISSUE TITLE
Navigation Screen: Adapt or hide notices

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#29311]
With the new Navigation screen we have a persistent right sidebar. This causes some strangeness when notices are displayed:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/191598/109053448-b352d480-76aa-11eb-803d-01f0e90f666c.png">

I have two solutions in mind:

1) Adapt the notices to fit within the available space.
2) Hide all notices like we do in the other editors.

**Comment by talldan** [comment]
The noticed have now been hidden by #29926, which I think is a good solution. It seems enough to have these notices show in the main admin interface. 

Closing this issue.
