### ISSUE TITLE
Gallery Block: Align uncropped items to the top of the block

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#29316]
## What problem does this address?

When I'm using the gallery block to display images with different orientations or heights, I'll often want to display them uncropped. However, the images are then aligned to the bottom of the block, which can get quite awkward:

![image](https://user-images.githubusercontent.com/2846578/109066660-63303e00-76bb-11eb-91c8-c90dd534a6b8.png)

![image](https://user-images.githubusercontent.com/2846578/109067013-f49fb000-76bb-11eb-89ff-49322589b651.png)

## What is your proposed solution?

Two suggestions:
1. Default to aligning the gallery items to the top of the container
2. Add the alignment setting to the gallery toolbar, when images are uncropped

![image](https://user-images.githubusercontent.com/2846578/109067136-1d27aa00-76bc-11eb-9bd7-db402ac698a4.png)

**Comment by mtias** [comment]
But gravity!
