### ISSUE TITLE
Undo level created for every character typed in textarea

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2932]
## Issue Overview
Textareas and inputs sync their state continuously, so for every change, a new undo level is created. This is unexpected as it is unlikely one would want to undo changes character by character. Additionally, this requires a lot of memory.

## Steps to Reproduce (for bugs)
1. Create a code block, or any other block with a `textarea` or `input` element.
2. Type some text.
3. Undo changes and observer they happen character by character.

**Comment by mtias** [comment]
Going to close this as sometimes this might be a good consequence. For most cases, we should provide primitives that either handle PlainText or input with better undo logic.

**Comment by iseulde** [comment]
> For most cases, we should provide primitives that either handle PlainText or input with better undo logic.

Does this mean we still want action here?

> Going to close this as sometimes this might be a good consequence.

What's the good consequence?
