### ISSUE TITLE
W button in the top left corner isn't visible on smaller screens (tablet, mobile)

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29339]
Below 782px viewport width we lose the "W button" from the top left corner. This makes it almost impossible to access the browsing sidebar on mobile and tablet in the Site Editor. Almost, because we can still access it from the Document Settings dropdown.

This also makes it impossible to leave the block editor without turning off fullscreen mode.

After all, we can rely on the admin bar but why do we have the button on the desktop then? I think it would make sense to keep the W button visible all the time to avoid confusion.

Editing a page:
![image](https://user-images.githubusercontent.com/2256104/109160784-879d2080-7776-11eb-967e-36ad044269ad.png)

Site editor:
![image](https://user-images.githubusercontent.com/2256104/109160878-abf8fd00-7776-11eb-905f-d3145967af32.png)

**Comment by david-szabo97** [comment]
Somewhat related https://github.com/WordPress/gutenberg/issues/26125

**Comment by annezazu** [comment]
I can confirm this issue using Gutenberg 10.0.2 and WordPress 5.6.2. I'll see what I can do to flag for those who worked on this milestone! Thank you for reporting this.

**Comment by Addison-Stavlo** [comment]
This button is tied to fullscreen mode (inheriting historically from the fullscreen mode close button predecessor).  If you turn fullscreen mode off, it disappears and the wp-admin nav is available.  Similarly, fullscreen mode is disabled on small width viewports and the wp-admin navigation is available via that hamburger icon you see in the top left.

**Comment by vindl** [comment]
One way to solve this would be to just have fullscreen mode without the option to toggle it off. That would deal with the problem in #26125. After that we can fix the display issue described here by making sure that fullscreen mode is shown properly on smaller screens.

Site Editor is a Customizer replacement after all, and that doesn't have windowed mode either.

**Comment by Addison-Stavlo** [comment]
I agree, forcing fullscreen mode in the site editor seems much better than having this awkward wp-admin bar forced in at lower screen widths.  What we need to consider though is how to fit that 'W' button into the top bar real-estate on small widths.. there is not much room:
![Screen Shot 2021-02-26 at 3 21 55 PM](https://user-images.githubusercontent.com/28742426/109350929-5db32f00-7846-11eb-9c46-a9f28c322fc7.png)

**Comment by Addison-Stavlo** [comment]
^^ My mistake above as that screenshot is of the post editor, not site editor.  In the site editor there is plenty of room to keep this button:

![site-editor-top-bar](https://user-images.githubusercontent.com/28742426/109353473-69a0f000-784a-11eb-8820-75a05a6a1f13.gif)

Although as a separate issue we may want to consider trying to keep some of these removed controls at lower screen widths.

**Comment by creativecoder** [comment]
PR to address this at https://github.com/WordPress/gutenberg/pull/29489

**Comment by creativecoder** [comment]
Resolved by https://github.com/WordPress/gutenberg/pull/29489
