### ISSUE TITLE
Can't click on the fixed block toolbar if a group block is behind it, affects smaller screens only (mobile, tablet)

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29343]
## Description
In the post editor whenever I try to click on any button in the block toolbar while a `Group` block is "behind it", the Group block takes the click instead of the Block Toolbar.

## Step-by-step reproduction instructions
1. Create an empty post/page
2. Create a group block
3. Create a paragraph block and make it as "tall" as possible by creating new lines. Once the block toolbar overlaps the Group block you are good to go.
4. Try to click on one of the block toolbar buttons.
5. Group block is selected :(

## Expected behaviour
I should be able to use the block toolbar.

## Actual behaviour
Group block is selected.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/2256104/109165734-2f691d00-777c-11eb-8f08-caa6d68a7ddf.mov

## WordPress information
- WordPress version: 
- Gutenberg version: `master`
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1B

## Device information
- Device: Macbook Pro
- Operating system: macOS
- Browser: Chrome

**Comment by Mamaduka** [comment]
I've no longer able to reproduce this issue. Tested with WordPress 6.0 and Gutenberg 13.3.
