### ISSUE TITLE
Pixel gap in the modal component header

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#29341]
## Description
This is a little difficult to trace, but I recorded a video (attached below) that shows a minor gap in the header of the modal component in Gutenberg.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/5817882/109162799-72d28400-779a-11eb-995b-ef663d4d8fc0.mp4

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: "Not installed"
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: Desktop
- Operating system: "Windows 10"
- Browser: "Chrome 88.0"

**Comment by thomashigginbotham** [comment]
I can confirm this behavior in 5.6.2. However, the design of the preferences dialog has been changed in the latest Gutenberg version, and I'm not able to duplicate this issue with the new UI.

![image](https://user-images.githubusercontent.com/1651691/109325733-46fbe080-7824-11eb-8cb5-c25e37529a21.png)

**Comment by annezazu** [comment]
As @thomashigginbotham mentioned, [this design recently changed](https://make.wordpress.org/core/2021/02/11/core-editor-improvement-new-preferences-experience/) so I'm going to close this out.

Thank you for reporting!
