### ISSUE TITLE
Site Editor: Quickly deleting all content

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#29353]
## Description

In the post editor, if the user wants to quickly remove placeholder content, they can use use `cmd` / `ctrl` + `a` hotkey twice. Then they can use the `delete` key to wipe everything away.

![2021-02-25 11 20 59](https://user-images.githubusercontent.com/5414230/109206043-3b44e700-775c-11eb-9ad8-85c817722c43.gif)

This functionality, however, doesn't exist in the site editor. It would be convenient to be able to support this behavior somehow.

![2021-02-25 11 22 01](https://user-images.githubusercontent.com/5414230/109206057-3f710480-775c-11eb-8c82-c1808be28868.gif)

## Step-by-step reproduction instructions

1. Navigate to the post editor with existing content
2. Use the `cmd` + `a` hotkey twice to select all content
3. Verify that delete removes all the content
4. Navigate to the site editor. Ensure that there is existing content.
5. Use the `cmd` + `a` hotkey twice to select all content
6. Verify that delete _does not_ remove all the content

## WordPress information
- WordPress version: v5.6
- Gutenberg version: v10.0.0
- Theme: TT1-Blocks

## Device information
- Device: Desktop
- Operating system: macOS Big Sur
- Browser: Chrome

**Comment by Sandstromer** [comment]
I'm not so sure this would be a good idea.
Quickly deleting all content from a single post or page is one thing, but to quickly remove all content from the template in the site editor should not be so easy.
Wiping the template to an empty state should require more steps, and a much more considered approach.

**Comment by annezazu** [comment]
https://user-images.githubusercontent.com/26996883/198494472-ef3e3352-e44f-4649-aa03-12abc33774a1.mov

Closing this out as in 6.0.3 this is possible :)
