### ISSUE TITLE
Column block: vertical alignment not reflected instantly

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29351]
In some cases the vertical alignment of the column block is not reflected instantly after it's applied. It's position will only be updated once another block is selected.

I was not able to reproduce this consistently in Site Editor, but here's the recording of the report I got:

https://user-images.githubusercontent.com/1182160/109204704-f9409300-77a5-11eb-9d0f-9711ca30c100.mp4

**Comment by jeyip** [comment]
Hmmmm...tried reproducing this with no luck. I played around with the following:

- Different column proportions, like 50/50, 25/50/25, 70/30, and 33/33/33
- Columns nested in a template part
- Columns nested within other columns
- Columns with no nesting
- Varying content blocks in each column, like images, nav blocks, paragraphs, site titles, and quotes.
- Chrome, Firefox, and Safari

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this as well, vertically alignment takes effect immediately as shown in the video below: 

https://user-images.githubusercontent.com/41231764/183874033-0714d370-10de-4cf8-8842-22abaf767229.mov

WordPress 6.0.1

Gutenberg 13.8.1 active 

No other plugins active

Closing this issue, for now
