### ISSUE TITLE
Slider bottom cell becomes un-selectable by iOS VoiceOver 

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#29359]
## Description
When interfacing with a slider in the bottom sheet with iOS' VoiceOver accessibility feature, a cell becomes un-selectable/focusable after the first time you focus the cell's child slider.

This issue does not appear to occur for Android's TalkBack accessibility feature.

## Step-by-step reproduction instructions
1. Launch the iOS app.
2. Edit a post and add Columns block.
3. Enable iOS VoiceOver.
4. Open the inspector for the new block by tapping the settings button.
5. Tap a Column cell (A).
6. Double tap the same Column cell (A).
7. Tap a different cell (B).
8. Tap the first Column cell (A).

## Expected behaviour
The entire cell is selected. "Column \<index\>. Current value is \<value\>. Double tap to change the value using slider." is read aloud.

## Actual behaviour
The cell's child slider is selected. "\<value\>. Adjustable. Swipe up or down with one finger to adjust the value." is read aloud.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/109231974-0c933480-778d-11eb-9b34-ba2d31fbacbe.MP4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: iPhone SE
- Operating system: iOS 14.4
- WordPress app version: 16.7.1

**Comment by dcalhoun** [comment]
This issue may be caused by an [accessibility state](https://github.com/WordPress/gutenberg/blob/a0ec0232a06b2dd20ac033bf04ff56496cb948a6/packages/components/src/mobile/bottom-sheet/range-cell.native.js#L55) that is set when the cell is first pressed. It doesn't appear to be reset at any point while the component is mounted.

**Comment by hypest** [comment]
Added the "Priority High" label as this is a big "broken window" for a11y flows. Also, added it to the "Site Editing" project as folks there have worked closer to the column Slider controls.
