### ISSUE TITLE
Site Editor: Selecting a block when Settings sidebar is open, it should switch to Block tab

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29372]
To be more consistent with Post Editor, we should consider automatically switching the sidebar between tabs based on context. We already have a feature in place that automatically switches to Block tab when opening the settings sidebar while a block is selected.

In the post editor, when we select a block (while nothing is selected), then the sidebar automatically switches from Page to Block. And vice-versa: when we remove our selection then it switches from Block to Page. I'm not sure if this is intentional though. So it might be a bug in the post editor instead of a feature. cc @mtias @jameskoster 

For reference, here is how the post editor works: (Note: It doesn't switch to Block tab if we just keep changing our selection between blocks. But it does if we have nothing selected then we select something)

https://user-images.githubusercontent.com/2256104/109292643-fb006a00-782a-11eb-921d-b2e84edf0224.mov

And here is how the site editor works:

https://user-images.githubusercontent.com/2256104/109292660-005db480-782b-11eb-9973-650d177a0210.mov

**Comment by jameskoster** [comment]
Agreed. Also somewhat related: https://github.com/WordPress/gutenberg/issues/29254

**Comment by jeyip** [comment]
It appears as if the tab switching functionality now applies to the block editor as well. I believe we can close this ticket.

![2021-11-04 12 24 24](https://user-images.githubusercontent.com/5414230/140406460-a9f6c4f7-04a9-40ba-a1b5-919000008bad.gif)

cc @creativecoder @zaguiini

**Comment by jameskoster** [comment]
> It appears as if the tab switching functionality now applies to the block editor as well.

Yep it's working fine for me too. Let's close this.

**Comment by mtias** [comment]
Yes, makes sense. I'd also like to consider switching to the block inspector when global styles is open and you select a block in the canvas.
