### ISSUE TITLE
Site Editor: browsing sidebar and template previews shown below block toolbar

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29392]
Template previews are covered by block toolbar in the Site Editor. To reproduce, try hovering over a template when a block toolbar is in the area where it usually renders:

![Screenshot 2021-02-26 at 23 04 26](https://user-images.githubusercontent.com/1182160/109360204-15683100-7887-11eb-800f-ce303a63721e.png)

**Comment by paaljoachim** [comment]
I just noticed this as well during the FSE call for testing I just finished earlier today.
The solution [I suggested](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1360)  as I see it is when Toggling the Navigation area that any selected block in the layout is automatically deselected.  This way the block preview would not be blocked by any selected block toolbar.

**Comment by vindl** [comment]
It also overlaps the browsing sidebar in general, more info in https://github.com/WordPress/gutenberg/issues/29615.

**Comment by creativecoder** [comment]
PR to address this at https://github.com/WordPress/gutenberg/pull/29918. Taking a simple approach of updating the z-index, at least for now.

**Comment by vindl** [comment]
Resolved in #29918.
