### ISSUE TITLE
Site Editor Navigation Panel - Doesn't show 'draft' pages/posts.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29397]
The Navigation Panel in the site editor only shows published pages/posts, not drafts:

![Screen Shot 2021-02-26 at 8 12 13 PM](https://user-images.githubusercontent.com/28742426/109370668-4b99b680-786f-11eb-9734-17c46fdfa44f.png)

This can be problematic since there are flows to create a draft post inside the editor (such as navigation -> page link -> create draft).  After creating a draft page from within the site editor, one would expect they would then be able to navigate to that page via the nav panel.

How should drafts be distinguished in the nav panel compared to published posts?

**Comment by paaljoachim** [comment]
What about just below the magnificy glass having a column where one adds a mention of draft/private etc.
Published pages/post would not show anything there.

I am thinking something like this:
![FSE-Navigation-Draft-Private-posts](https://user-images.githubusercontent.com/5323259/109402267-d9030680-7954-11eb-9a63-af158a588484.jpg)

**Comment by Addison-Stavlo** [comment]
I think its safe to close this issue given content navigation has been removed from this panel for a long while now.
