### ISSUE TITLE
Add a subtle animation to toolbar buttons

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#2939]
Adding some subtle transitions to the toolbar buttons goes a long way towards giving Gutenberg it's own personality. Here's my initial suggestion for hover and active:

![toolbar buttons](https://user-images.githubusercontent.com/191598/31353038-fb339bd2-acfe-11e7-8527-d6bd8b2f8b57.gif)

**Comment by karmatosed** [comment]
Closing this to focus on a unified approach in one issue over on #8029.
