### ISSUE TITLE
Unable to paste plain text URL in empty paragraph block

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#29409]
## Description

It is not possible to paste a plain text URL in an empty paragraph block when other (likely embed) blocks have been removed via the `allowed_block_types` filter for a custom post type.

## Step-by-step reproduction instructions
1. Filter `allowed_block_types` so that only `core/paragraph` is allowed for a post type.
2. Create a new post of that post type.
3. Attempt to paste a URL (e.g. https://make.wordpress.org) in an empty paragraph block.

## Expected behaviour

I expect the plain text representation of the URL to appear in the paragraph block.

## Actual behaviour

Nothing happens in the block, it remains empty.

The browser's console log shows:

```
Received plain text:

 https://make.wordpress.org/

Processed HTML piece:

 <p>https://make.wordpress.org/</p>
```

## Code snippet (optional)

https://gist.github.com/jeremyfelt/92167d2bce99eaa87f6f42a6f1dc735a

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes (except for the code in the gist)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Laptop
- Operating system: MacOS 11.2
- Browser: Firefox 86.0

**Comment by stokesman** [comment]
Seems that #27835 is the same.

**Comment by jeremyfelt** [comment]
Ahh, thanks! My searching did not turn that one up for some reason. :)
