### ISSUE TITLE
Page List: missing current-menu-item (and others) classes

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29422]
## Description

The new "Page List" block which you can insert in the Navigtion block to have page menus stay in sync with content created, is missing CSS classes for current pages or page ancestors.

## Step-by-step reproduction instructions

The easiest way to see CSS classes traditionally applied to menu items, is to use a non-block based theme, such as Twenty Twenty One.

Create a menu in the menu screen, with submenu items. 

- Navigate to a page in menu. Observe that it has CSS classes such as these: `menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-451 current_page_item menu-item-1172`
- Navigate to a subpage in a menu. Observe it has classes such as these: `menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current-menu-parent current-page-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-1171`

## Expected behaviour

Similar CSS classes, or at least a subset, would be nice to have for the Page List block, so that active menu items can be styled. Here in TwentyTwentyOne, the "Home" item is the current page:

<img width="461" alt="Screenshot 2021-03-01 at 10 12 10" src="https://user-images.githubusercontent.com/1204802/109476923-b74e7000-7a77-11eb-8f77-7fb1fc665bd6.png">

Probably a subset of CSS classes would make for an excellent start, and then additional classes could be added as necessary. For a current page item, probably `current-menu-item` would be plenty, and for a menu item that has a subpage active, `current-menu-ancestor` would be great.

**Comment by mtias** [comment]
@draganescu I remember we discussed this several times. Do you remember if it was tracked separately?

**Comment by jasmussen** [comment]
Note that when you manually insert a Page Link, in my testing at least the `current-menu-item` was correctly output, so this is more specific to the new Page List block.

**Comment by mtias** [comment]
Ah, ok. We should be applying the same requirements to each.

**Comment by georgeh** [comment]
👀

**Comment by glendaviesnz** [comment]
@georgeh are you still looking at this? I am happy to pick it up if not.

**Comment by georgeh** [comment]
@glendaviesnz I've been stuck on #31149, if you have the bandwidth feel free to grab it. I assigned this when I thought that was almost done, turns out it needed deeper changes than I had thought.
