### ISSUE TITLE
Updating Gutenberg failed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2942]
Reported from feedback form:

"Hi,Team!  Just now i installed and tested the plugin.It is not working within site.It is showing updating failed and while i click on preview it is showing blank.Even i tested it by shifting themes in that case also i got the same error!"

GitHub user: @basamrajesh reported this. Could you provide please more information on what happened and if possible an image?

**Comment by hedgefield** [comment]
Seems like a duplicate of #2544?
