### ISSUE TITLE
Embed block silently fails when target resource has same-origin frame policy

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#29429]
## Description

The Embed block doesn't correctly handle failure to embed when the resource behind the provided URL has a same-origin policy (`SAMEORIGIN`) as set by the [`X-Frame-Options` HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).

## Step-by-step reproduction instructions
1. Find the URL for a page whose response headers include `X-Frame-Options: SAMEORIGIN`. For instance, as of this writing, `https://woocommerce.com/experts/neuralab/`.
2. In a new post, paste the URL to trigger its embedding.

## Expected behaviour
The Embed should react to the browser's failure to access the resource, inform the user and let the user provide a different URL. This is what happens when attempting to embed an inexistent resource (e.g. `https://example.org/404`).

## Actual behaviour
An Embed block appears containing either a blank rectangle or a browser-rendered failure canvas. The Embed block itself isn't aware of the failure and offers the user no way to recover.

In Safari, the following error is reported in the console:

> Refused to display 'https://w...' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

## Screenshots
Safari | Chromium
-|-
<img width="1026" alt="Captura de ecrã 2021-03-01, às 11 52 41" src="https://user-images.githubusercontent.com/150562/109495500-44e58c00-7a87-11eb-93af-952277aae80a.png">|<img width="1119" alt="Captura de ecrã 2021-03-01, às 11 55 43" src="https://user-images.githubusercontent.com/150562/109495526-4f078a80-7a87-11eb-8328-9c7d8ad0723d.png">

**Comment by Thelmachido** [comment]
Hi @mcsf ! 

There hasn’t been any movement on this particular issue in a year, if this was related to [#29374](https://github.com/WordPress/gutenberg/issues/29374) we can close it. 
In the meantime, I've marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by kathrynwp** [comment]
@mcsf I'm going to go ahead and close this out, but if you think it should be reopened, feel free to add a comment with additional details and I’ll be glad to reopen it.
