### ISSUE TITLE
Spacer Block: Allow background color choice

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29420]
## What problem does this address?

The Spacer block is currently a primary layout tool, there to space out elements on a page. Aspects of this utility are likely to be augmented by, or taken over, by the addition of margin controls to more blocks.

But the spacer can still serve a purpose on its own, by allowing easily editable editorial spacing inside content.

An additional utility could be to allow a background color, so you could create empty colored areas. Many patterns do this already by adding an empty Cover block with a dummy spacer block inside. By enabling colors on the spacer block directly, this would simply that flow.

## What is your proposed solution?

Add a color swatch tool to the Spacer toolbar:

<img width="696" alt="Spacer empty" src="https://user-images.githubusercontent.com/1204802/109472420-64be8500-7a72-11eb-84e8-353313221594.png">

<img width="696" alt="Spacer with color" src="https://user-images.githubusercontent.com/1204802/109472427-65efb200-7a72-11eb-81c7-478c4d561ea9.png">

**Comment by mtias** [comment]
I'm not sure this makes much sense, especially if we end up transforming the spacer into adjacent margins in the future.

**Comment by jasmussen** [comment]
Excellent point. I created this ticket inspired by a personal use case, _behold_:

![punch](https://user-images.githubusercontent.com/1204802/127839688-aec96ef4-aff7-46c5-b68a-ee02e6dbe75b.gif)

Since then I haven't had much use for changing the color, though, which suggests that even if there was a use case for it, it might be better handled through extensibility or other blocks, like the separator.

**Comment by sunildevbang** [comment]
Hey How can we add custom background color
