### ISSUE TITLE
Global Styles: Opening a "by block type" group, it scrolls too far and hides the block name

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29427]
## Description
Global styles overscrolls when opening a block styles group.

## Step-by-step reproduction instructions
1. Open site editor
2. Open global styles sidebar
3. Change to "by block type" tab
4. Click on any Heading group

## Expected behaviour
I'd expect it to not scroll at all OR if it scrolls then the block's name should stay in the viewport.

## Actual behaviour
It scrolls too far and hides the block name

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/2256104/109490725-eb7e5c80-7a88-11eb-80ee-a74d7c5e6dc7.mov

## WordPress information
- WordPress version: 
- Gutenberg version: `master`
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1B

## Device information
- Device: MacBook Pro
- Operating system: macOS
- Browser: Chrome

**Comment by mtias** [comment]
I think this is no longer an issue with the new design.
