### ISSUE TITLE
wp-env: increase default upload size limit

### ISSUE THREAD

**Issue by guoyunhe** [WordPress/gutenberg#29430]
## What problem does this address?

I run `wp-env start` form a fresh block editor plugin project. When I try to upload an audio file to the site, I got "file exceeds the maximum upload size".

## What is your proposed solution?

It would be great to increase the limit, so that plugin developers can test audio/video related plugins without extra efforts. Maybe 500MB?

**Comment by skorasaurus** [comment]
related https://github.com/WordPress/gutenberg/issues/28703

**Comment by johnbillion** [comment]
Related for core: https://core.trac.wordpress.org/ticket/52668

**Comment by t-hamano** [comment]
#50490 seems to have raised the default upload size to 1GB. Additionally, you can change various settings by mapping the `.htaccess` file. Please refer to [this comment](https://github.com/WordPress/gutenberg/pull/32363#issuecomment-1858688415) for the specific code.

Therefore, I would like to close this PR.
