### ISSUE TITLE
Consider adding easier ways to add anchors to links

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2944]
@imath had a suggestion through the feedback form and it could be something useful to consider:

"It's  not possible to simply add an anchor into the link control. eg: <a href="#content">Go to content</a>. You need to enter in text mode to achieve it. Using the classic editor it's possible to add an anchor from the link control. I think it can be problematic for people writing long posts and including a table of content to navigate in it."

I can see a strong user case for this myself.

**Comment by youknowriad** [comment]
Isn't this already fixed by #2870 ?

**Comment by imath** [comment]
Hi, thanks a lot Tammie :)

Yes #2870 shoukd fix it. I can’t see it yet as i’m using the WP.org latest stable release.

Thanks for your great work!

imath.
http://profiles.wordpress.org/imath/
