### ISSUE TITLE
Site Editor: template management

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29449]
Currently in the Site Editor we can only insert templates from a predefined list, provided that they are not already included in the theme:

<img width="552" alt="Screenshot 2021-03-01 at 22 36 49" src="https://user-images.githubusercontent.com/1182160/109562437-af75e680-7ade-11eb-988d-6a912a03dff3.png">

This leaves a couple of missing options. We should consider whether it would make sense to add some of the following functionalities:

- [ ] Delete existing templates
  - [ ] Deleting user created templates - this amounts to deleting the corresponding CPT
  - [ ] Deleting theme provided templates - we probably don't want to delete the actual files, since that won't persist through theme updates. Instead we can mark these templates as deleted and use that to skip them in template resolution
- [ ] Change the currently assigned template for the page
- [ ] Create a new template that's targeting a specific page (`page-{ID}.php` or `page-{slug}.php` equivalent). We can consider allowing the creation of arbitrarily named (unassigned) templates, but it's not clear whether that will be necessary in addition to the previous flow

**Comment by mtias** [comment]
I hope we could explore a more focused modal flow for the "create new template" where we can afford more room to explain things, and could show the templates that already exist next to the missing ones.

**Comment by Addison-Stavlo** [comment]
im going to close this issue as stale as the interface has been redone and includes a lot of the requested tools.
