### ISSUE TITLE
Navigation block: Changing the orientation isn't straightforward

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29441]
Navigation block doesn't have any visible options to change between vertical and horizontal orientation. The only way is to use "Transform to variation" which is unfriendly for beginner users.

We should add an option to the block's toolbar or to the inspector.

![image](https://user-images.githubusercontent.com/2256104/109517688-d1a14180-7aa9-11eb-9ddb-d8fcb3449e19.png)

**Comment by jasmussen** [comment]
I know we intentionally kept it separate from the block switcher. But here's how that might look like:

<img width="892" alt="transform" src="https://user-images.githubusercontent.com/1204802/109987266-c434c300-7d06-11eb-8b67-7186cd682b22.png">

**Comment by eduardozulian** [comment]
@jasmussen do you know if there is a particular reason why we ended up with two separate blocks (horizontal and vertical) rather than a setting on a broader Navigation Block? I think it might work if we turn the "Transform to variation" option into a setting under "Display".

Thank you!

**Comment by jasmussen** [comment]
> do you know if there is a particular reason why we ended up with two separate blocks (horizontal and vertical) rather than a setting on a broader Navigation Block?

I know the key bit here is to ensure that the mover control points in the right direction based on context, so primarily a technical consideration. @ntsekouras please correct any bits I might be missing here. 

> I think it might work if we turn the "Transform to variation" option into a setting under "Display".

Keeping in mind that more blocks than Navigation (currently Buttons) are likely going to need a user-friendly interface for changing orientation, it's important we think in terms of an interface that will work for any block. Also specifically for Navigation, as additional design tools (padding, margin, more color options, overlay menus, #30370) become available, we remain careful with relying on the inspector as the primary interface for transforms.

**Comment by ntsekouras** [comment]
>I know the key bit here is to ensure that the mover control points in the right direction based on context, so primarily a technical consideration. @ntsekouras please correct any bits I might be missing here.

That's true but this was the first exploration about block variations transforms and I totally agree with Joen's comment:

>Keeping in mind that more blocks than Navigation (currently Buttons) are likely going to need a user-friendly interface for changing orientation, it's important we think in terms of an interface that will work for any block.

**Comment by annezazu** [comment]
Closing this out as this is the current experience in 6.3 RC3 :) 

<img width="299" alt="Screen Shot 2023-08-03 at 12 24 49 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/47164a02-d730-4703-a09e-20e3a35f106a">
