### ISSUE TITLE
Cover: Solid-color only cover has small gray border in the editor only

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29440]
## Description

A Cover block with no image background, just a solid color, has a 1px gray border all around. Only in the editor:

<img width="765" alt="Screenshot 2021-03-01 at 16 03 06" src="https://user-images.githubusercontent.com/1204802/109515759-bd5c4500-7aa7-11eb-8350-1a854dbee074.png">

## Step-by-step reproduction instructions

Insert a Cover block, choose a background color that is relatively light. I used Chrome, it may be different in other browsers.

Observe that there's a 1px gray border around the image. 

## Expected behaviour

No border.

It appears the border comes from there technically being an `img` in the markup, it's just unset:

```
<div class="... wp-block-cover">

	...

	<img class="wp-block-cover__image-background" alt="">
	<div class="wp-block-cover__inner-container block-editor-block-list__layout">
		...
	</div>
</div>
```

It appears Chrome adds a gray border around such empty `img`s, as you can see in this codepen: https://codepen.io/joen/pen/gOLzOWR

If I add this, the border disappears:

```
img:empty {
	visibility: hidden;
}
```

However it seems like a better solution would be to not output any img at all, if possible.

**Comment by mtias** [comment]
Is the empty image also showing up on the front?

**Comment by jasmussen** [comment]
Purely an editor artifact.

**Comment by stokesman** [comment]
First reported in #29082. This report is valuable since the assessment of the cause and suggested solution sound right.

**Comment by jasmussen** [comment]
Thank you!
