### ISSUE TITLE
FSE: Unable to save changes & repeated Update Design notice

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29452]
## Description

When trying to edit and save within the site editor experience, I get stuck in a repeated "Update Design" flow that doesn't seem to result in changes actually being saved. This is a new bug that wasn't present when I've done prior testing so I'm not quite sure what's changed and I wasn't able to find any open/closed related issues.  This is being done as part of work for the FSE Outreach program. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Use a block based theme and the latest version of Gutenberg to setup the FSE experience.
2. Go to "Site Editor (beta)"
3. Make any change to the site
4. Select "Update Design" and save changes.
5. Notice "Update Design" is still clickable. Go through saving changes again.
6. Try to navigate back to wp-admin and get a notice about confirming you're okay with losing changes.
7. Navigate back to the Site Editor experience and notice changes aren't saved.

## Expected behaviour

I expect the Update Design notice to grey out when changes aren't made. I expect changes to stick upon saving them. 

## Actual behaviour

Update Design repeatedly shows as a call to action and the changes don't seem to save despite going through the saving flow. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/109564795-c98fd480-7a9e-11eb-9378-63e7d9622009.mov

Of note, this is very randomly inconsistent. For example, here's where a simple change to a post title stuck followed by the error recurring: 

https://user-images.githubusercontent.com/26996883/109565131-402cd200-7a9f-11eb-953d-fd6e93894431.mov

Here's me editing the post title in the same exact why but the strange saving behavior recurring:

https://user-images.githubusercontent.com/26996883/109565281-78ccab80-7a9f-11eb-9356-8de0c6da778c.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by jasmussen** [comment]
Reminds me of this one: https://github.com/WordPress/gutenberg/issues/28271

I closed it because destroying and recreating my environment fixed the issue for me.

**Comment by annezazu** [comment]
Ah thanks for connecting the dots here. I have to ask though, you say this in your issue:

> So the issue here, outside of the gray screen issue, is probably due to the fact that my environment had been running for a long time, over a great deal of iterations on the site editor, therefore containing a great deal of junk in the database. For that reason, I'll close it again!

It worries me to close this out without investigating as ideally the Site Editor is stable enough at this point to be used across time. This was a more recent test site as well that I created on December 14, 2020. I'll close it out but curious what the thought process is as I imagine part of testing should be trying to snag problems like this.

**Comment by jasmussen** [comment]
Sorry I did not necessarily mean you should close this one. In fact since it's happening again, I would agree it needs a little investigation.

**Comment by annezazu** [comment]
Ah! I made an assumption there. I'll re-open. Thanks again for connecting dots :)

**Comment by jasmussen** [comment]
In testing out #28141, I encountered this issue again. It was then fixed again when I checked out trunk. Not quite sure what caused it, but as I had some dev environment issues with testing that PR (needing to `rm -rf ./node_modules && npm install && npm run dev`) it's possible that had a role to play.

**Comment by mcsf** [comment]
Were you able to look at the browser's Network dev tool and grab any info on which/how requests may be failing?

**Comment by jasmussen** [comment]
> Were you able to look at the browser's Network dev tool and grab any info on which/how requests may be failing?

Back in https://github.com/WordPress/gutenberg/issues/28271 I did in fact record a video of the process when chatting with @david-szabo97:

https://user-images.githubusercontent.com/1204802/110626722-60e0e000-81a1-11eb-8b99-6d414cbe6403.mov

However note that I can't easily reproduce this anymore. For me it happens sporadically and mostly on older pull requests.

**Comment by annezazu** [comment]
Ah yes! Apologies. Forgot to share that here.

https://user-images.githubusercontent.com/26996883/110654508-6dead880-817b-11eb-82a3-8a7bd49821bd.mov

I don't see anything noteworthy.

**Comment by annezazu** [comment]
This seems to have magically resolved itself at some point. I stopped using the test sites impacted by this, revisited them this week with the latest GB version, and everything works as expected now. I am closing this out a bit bummed the root problem wasn't determined but happy the issue is no longer present it seems.
