### ISSUE TITLE
Social Icon: Yelp icon retains BG color even when "logos only" is set

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#29456]
## Description
When you add a Yelp icon to your social icon set, the background color always shows, even if "logos only" is set.

## Step-by-step reproduction instructions
1. Add a social icon block to your post or page
2. Add some icons, including Yelp
3. Change your social block to the "logos only" style
4. See that the Yelp icon still has its background.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2846578/109569260-264ab980-7ab6-11eb-9362-d29b59a5d5e3.png)

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Operating system: macOS 10.15.7
- Browser: Chrome 88.0.4324.192

**Comment by lephleg** [comment]
@aristath what's wrong with the original PR? Messed something? (sorry, newcomer)

**Comment by jasmussen** [comment]
@lephleg my apologies, I did not see that original PR. Seems like we both made them around the same time. I'll see if I can edit my PR description to give you props.

**Comment by jasmussen** [comment]
Sometimes it goes fast and things get missed in the shuffle. Thank you for your work. If you have another PR that needs reviewing, please feel free to assign me reviewer (@jasmussen) and I'll see if I can help you land it. In the mean time, I've edited my original PR to give you props.

**Comment by aristath** [comment]
@lephleg There was nothing wrong with the original PR... Github notifications is what I use to work through issues & reviews, so @jasmussen's PR just appeared first and I reviewed it.
A rare mixup where 2 people submit PRs relatively close to each other and the github notifications put the newer one first. My apologies, I missed it. ❤️
