### ISSUE TITLE
Navigation: Add alignment option to vertical variant

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#29459]
Navigation block offers two variants - horizontal and vertical. The vertical variant is missing alignment options. Space-between will probably not apply, but it would be useful to introduce the left/center/right.

Here are the settings in horizontal variant:
![image](https://user-images.githubusercontent.com/4550351/109577784-4e83f800-7b4a-11eb-8b55-03eb15482ba6.png)

**Comment by jasmussen** [comment]
Makes sense, I could see centered navigation items in a fullscreen modal menu (https://github.com/WordPress/gutenberg/issues/22824#issuecomment-788916109). @mkaz do you want to pair on this one?

**Comment by mkaz** [comment]
Yes, I can take a look at adding the controls and see if the existing CSS would work as expected.
