### ISSUE TITLE
Save Panel - Add template descriptions.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29463]
## What problem does this address?

In the save panel, saving a template gives us the name of the template but no description of when that template will be used.  If a user loads the Site Editor, edits the template, and goes to save: they are not easily able to tell what the thing they are saving is used for.

![Screen Shot 2021-03-01 at 7 09 24 PM](https://user-images.githubusercontent.com/28742426/109582850-e216e380-7acc-11eb-91e2-e8a6e8638fbe.png)

## What is your proposed solution?

Maybe we should show the template description here, similar to what is done in the navigation panel:

![Screen Shot 2021-03-01 at 7 15 37 PM](https://user-images.githubusercontent.com/28742426/109582790-c8759c00-7acc-11eb-834e-ce753f48b201.png)

**Comment by mtias** [comment]
Good idea! It'd be nice to use the header icon and avoid the "template part" terminology if possible.

**Comment by Addison-Stavlo** [comment]
> It'd be nice to use the header icon and avoid the "template part" terminology if possible.

I could definitely see adding the semantic icon next to the entity being saved, but I am a bit confused about avoiding the 'Template Part' terminology.  Are you saying we should change from having a "Template Part" collapsable panel that shows all template parts being saved to instead having a separate panel for each semantic type?  

I would assume in most cases a user wouldn't be editing more than 1 header, 1 footer, 1 sidebar at a time meaning those collapsable panels would 99% of the time only contain 1 item each which may seem a bit of an excessive segmentation of those items.  

Also, is it worth avoiding 'Template Part' terminology here?  It fits the terminology used in the navigation panel on the left, and reminds/educates the new user that their header or footer falls under that broader category which can ease in use of other UI that surfaces the term 'template part'.

**Comment by carolinan** [comment]
For what its worth, during user testing on April 9, where the FSE outreach program call for testing was used, 
many participants found the term "template part" confusing.
It was not obvious how or if the template part is different from other blocks, or how it related to the header and footer.

At the same time, header and footer were terms they expressed no concerns about.

**Comment by mtias** [comment]
@javierarce has also been looking at the save flow and presentation a bit. It's calling them "areas" here:

![image](https://user-images.githubusercontent.com/548849/114531947-a5521680-9c4c-11eb-96ea-45bb60206785.png)

The icons would also help make a connection.

**Comment by javierarce** [comment]
We may not even have to use Areas or Template parts in the Save sidebar. We could arrange the templates under a Templates label, and it would still be easy to understand (plus we make the column a little more compact)

Here's a before and after design:

![parts](https://user-images.githubusercontent.com/4933/114556221-c7f22880-9c68-11eb-9d68-13cd31b3e0ff.png)

**Comment by javierarce** [comment]
Regarding the main topic of this issue: I think we could try to add a tooltip to show the template description. I've seen that this general idea [has been explored here recently](https://github.com/WordPress/gutenberg/pull/30005).

I think that adding the full description "in plain sight" would be a bit redundant since we already show it in the Template tab and the navigation panel. 

In general, I feel that if users don't know what a template does at this point in the flow, the problem should be addressed long before that.

**Comment by carolinan** [comment]
Tooltips are less accessible than plain text.

There are so many flows that for some this will be the first time they see the term template.
It is fully possible to click "edit site", make changes to a block, and go into the save Panel.

**Comment by Addison-Stavlo** [comment]
Circling back to this old issue, I think we can close this.

The design has been updated a bit, and while we don't include the individual template descriptions there has been other descriptor notes added for template items to help inform the user.

<img width="282" alt="Screen Shot 2022-11-09 at 11 31 03 AM" src="https://user-images.githubusercontent.com/28742426/200912156-142ab522-164e-4d18-9a56-a61d058ff08e.png">

Its definitely interesting to consider more specific template descriptions surfaced here, but given the age and level of activity on this specific issue I think its fair to close.
