### ISSUE TITLE
Site Editor (or post editor as well) - show block inspector by default.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29461]
## What problem does this address?

Currently when the Site Editor is loaded with no local storage settings, the block inspector starts closed.  With block toolbars being simplified and more options being added to the block inspector, new users will likely overlook and miss out on helpful tools and options provided by this sidebar when first starting out.

![Screen Shot 2021-03-01 at 6 52 20 PM](https://user-images.githubusercontent.com/28742426/109581631-a1b66600-7aca-11eb-9297-8b4817f15483.png)

## What is your proposed solution?

Set the show block inspector setting to start off as `true` (instead of `false`) when there is no setting saved in local storage.

We may want to consider this for the post editor as well.

**Comment by mtias** [comment]
I think I'd prefer to have List View open by default in the site editor.

**Comment by Addison-Stavlo** [comment]
> I think I'd prefer to have List View open by default in the site editor.

The list view is definitely an important item as well, and having multiple panels open is probably not a great way to start off on most viewport sizes.  However I feel some of the most common interactions of new users in the editor are to click on a block to edit the properties of it.  They could click on a heading, site title, paragraph, etc. and select it with ease, but be completely lost on how to accomplish the action they set out to (change the font size, color, background color, etc.) since all those controls are hidden in a panel that starts off closed and their attention is drawn to the toolbar.

I wonder if a potential solution would be to add a button at the end of all block toolbars whose purpose would be to open the block inspector (and potentially not even show that button when the block inspector is already open). 🤔

**Comment by Addison-Stavlo** [comment]
Im going to close this issue related to a more specific solution, as this is a wider more general problem being discussed and addressed elsewhere.
