### ISSUE TITLE
Site Logo - block doesn't respect parent boundaries.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29460]
When the site logo is an image larger than the parent container, adding the site logo block to this container will look/act as expected in the editor but be unrestricted and bleed into other elements on the front end.

### To Reproduce

In the Site Editor:
* Add a site logo block
* Apply a site logo using an image whose pixel size is larger than the parent container.  In this example the site logo is inside a column block with site title and site description:

![Screen Shot 2021-03-01 at 7 25 04 PM](https://user-images.githubusercontent.com/28742426/109580839-49329900-7ac9-11eb-9884-5d1b98e9084b.png)

* Save and view the front end.  Notice the image is not contained and bleeds into other blocks:

![Screen Shot 2021-03-01 at 7 25 36 PM](https://user-images.githubusercontent.com/28742426/109580866-53ed2e00-7ac9-11eb-87c3-2c81c17a8eae.png)

**Comment by Thelmachido** [comment]
I couldn't replicate this issue, the site editor reduces the site logo to fit the header as shown below: 

https://user-images.githubusercontent.com/41231764/183908950-102696ac-9a5b-4e56-956a-dc1f75f1093f.mov

WordPress 6.0.1

Gutenberg 13.8.1

Closing this issue
