### ISSUE TITLE
(Android) Splitting and merging a Paragraph/Heading block doesn't work correctly

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#29478]
## Description
While running the writing flow tests on the Mobile editor release `1.48.0` an [issue was found](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3205#issuecomment-788782331) regarding splitting and merging content in a Paragraph/Heading block.

## Step-by-step reproduction instructions
1. Open the mobile editor
2. Write (or paste) a paragraph with a few lines
3. Set the caret by the half of the paragraph
4. Press Enter (Intro) to split the block into two. (if using the simulator, use the **device keyboard**)
5. Move the caret a few words.
6. Delete all those words until the blocks merge.
7. See that the original content of the first Paragraph block shows up causing the content to be duplicated.

## Expected behaviour
The two blocks should merge without any content duplication.

## Actual behaviour
After emerging the two blocks the original content of the first Paragraph block returns causing content duplication.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/4885740/109671778-ac2d3a00-7b74-11eb-99b8-f7ae5097b7b4.mp4

## Device information
- Device: Redmi Note 8T (Or Pixel simulator)
- Operating system: Android 10

**Comment by geriux** [comment]
This is a regression from https://github.com/WordPress/gutenberg/pull/28505.

**Comment by cameronvoell** [comment]
@geriux I was taking a look at this and don't have a solution yet but I did find some simpler steps to reproduce:
1. Paste text
2. move cursor halfway and use emulator keyboard to press enter
3. Switch to HTML mode
4. Notice incorrect text
*Note if you use those same steps with the physical keyboard to press enter, the correct text will show in html mode.
![broken-text](https://user-images.githubusercontent.com/1103838/109765559-e49b3b00-7ba9-11eb-8f38-0f1ee8f5bee3.gif)

**Comment by geriux** [comment]
Reopening since the first approach to[ fix it](https://github.com/WordPress/gutenberg/pull/29587) didn't work.

**Comment by geriux** [comment]
I just reverted the [PR](https://github.com/WordPress/gutenberg/pull/29587) I made to try to fix it but ended up not working.
