### ISSUE TITLE
Block API: useBlockRef( clientId, ref )

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#29475]
Would replace the `BlockNodes` context and `getBlockDOMNode`.

We have some components that need access to the block node, for example the block toolbar, inserter, writing flow...

The idea is to have a `useBlockRef( clientId, ref )` hook that would add the given ref to the block props in `useBlockProps` for a given client ID. The ref can be either a ref object or callback, that doesn't matter.

Internally, we'd need some kind of store to keep track of all the refs that need to be added. Maybe we kan use `addFilters`? In `useBlockProps`, we'd can use `applyFilters` to get all the refs by client ID. `applyFilters` would need to be reactive though, meaning if a new filter is added, the hook is called again and the block is re-rendered.

Cc @youknowriad @gziolo

**Comment by youknowriad** [comment]
I think you mean `useBlockRef( clientId )` right? (or maybe I'm not understanding the purpose of that hook).

A use-case I've actually noticed for this is to render "UI" that is relative to the block position but without polluting the markup. We do so for the BlockToolbar in an adhoc way but for instance I wanted to do that for the "Padding Visualizer" for the group block in #29335 and was wondering whether we'd need something like `<BlockPopover>Any random UI</BlockPopover>` as a component to render something by the block visually but actually outside the canvas in the DOM.

**Comment by ellatrix** [comment]
I mean `useBlockRef( clientId, ref )` where `ref` is the ref to attach to the block with the specified client ID. We should allow both types of refs, which means you create the ref and then pass it to `useBlockRef`.

```js
const ref = useRef();
useBlockRef( clientID, ref );
```

or

```js
const refCallback = ( node ) => {};
useBlockRef( clientId, refCallback );
```

or

```js
const refCallback = useRefEffect( ( node ) => {}, [] );
useBlockRef( clientId, refCallback );
```

**Comment by youknowriad** [comment]
Why not just retrieve the block ref (since there's already one by default) and return it?

**Comment by ellatrix** [comment]
How would you be able to use a ref callback?

**Comment by youknowriad** [comment]
> How would you be able to use a ref callback?

Yeah, I guess you can't :)

**Comment by ellatrix** [comment]
We also need a mechanism to insert refs from outside the block list component, for example for the skip to selected block component. The PR I created solves all use cases.
