### ISSUE TITLE
Invalid Page address displayed when a future page is first scheduled

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#29477]
## Description
When creating a new page with the published date in the future the Page address displayed below **What's next**? is incorrect - 
eg `https://cwiccer.com/%pagename%/`

It's not visitable.

## Step-by-step reproduction instructions

1. Add a new page
2. Set the published date to the future
3. Schedule the page.
4. Confirm Schedule

## Expected behaviour

To see the Page address (  permalink ) that will be valid in the future.

Note:
- The page author will be able to see the page.
- Due to its scheduled status ( post_status = 'future' ) other visitors may not be able to see it...
Unless 'future' is one of the post statuses for the query used to retrieve the page.

Note: When this panel is closed the URL slug is correctly displayed.

## Actual behaviour
The Page address is incorrectly displayed as `https://example.com/%pagename%/`
It's the last part of the URL that's wrong. Here's the Page address when the parent page is Future WordPress Birthdays
`https://cwiccer.com/future-wordpress-birthdays/%pagename%/`
![image](https://user-images.githubusercontent.com/2474435/109658625-b80e0180-7b5e-11eb-8a56-2dd41c9705b3.png)

## WordPress information
- WordPress version: 5.6.2 
- Gutenberg version: Not installed 
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty 

## Device information
- Device: Desktop 
- Operating system: Windows 10 
- Browser: Chrome 88

**Comment by getsource** [comment]
Folks in a [triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1626757587323700) were able to reproduce this issue, so labeling as a bug.

@talldan noted that the bug only seems to happen with Pages, and not Posts.

**Comment by yahilmadakiya** [comment]
This happens with custom post type registration as well.

During debugging I found something
----

In post publish panel. It replace `%postname%` with Slug [if post status is future](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-publish-panel/postpublish.js#L96). which is working fine with POST.

But for page and other CPT `%postname%` is not available to it [returns as it ls](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-publish-panel/postpublish.js#L34-L42).

I checked post permalink using this snippet: wp.data.select( 'core/editor' ).getCurrentPost().permalink_template

**Comment by shreyasikhar** [comment]
Hello everyone,

I have a PR that fixes the permalink issue which appears with pages and CPT posts, when scheduled in the future. Please take a look at it and let's get it fixed.
