### ISSUE TITLE
Several FSE Comments blocks assume the commentId attribute is valid - leading to Warnings / Notices when not

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#29472]
## Description

While writing some documentation for the Comments related blocks I noticed several instances of Warnings and Notices produced when the `id` attribute for the block did not refer to a valid comment.  

eg For https://blocks.wp-a2z.org/block/post-comment-author-core-post-comment-author/
where I had documented the `core/post-comment-author` block, when the `commentId` was incorrect the following notices were produced.

Notice: Trying to get property 'user_id' of non-object in /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/comment-template.php on line 28

Notice: Trying to get property 'comment_ID' of non-object in /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/comment-template.php on line 48

Notice: Trying to get property 'comment_content' of non-object in /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/comment-template.php on line 971

Notice: Trying to get property 'comment_date' of non-object in /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/comment-template.php on line 557

This issue summarises the problems.

The **workaround** is to use a valid comment ID (`commentId` ).

## Step-by-step reproduction instructions

Pre-requisites
- Set `WP_DEBUG` true in order to get Notices.
- Use a Full Site editing theme such as TT1-blocks.
- Enable comments for the post type you're going to use

1. In a new post create the comment blocks.
2. Use the code editor manually edit comment blocks to set an invalid value for the `commentId` attribute. 
3. Attempt to save and view the results.
4. Warnings and /or Notices will be displayed. - See actual behaviour

Note: 
- The commentId must be a non-zero numeric value eg a negative value
- For any other value and the attribute is removed on Update.

## Expected behaviour

There shouldn't be any Warnings or Notices when the commentId is not a valid comment ID.

## Actual behaviour

Blocks which produce Warnings and/or Notices when WP_DEBUG is true, and the `commentId` is not a valid comment id, are:

- `core/post-comment-author` - see above
- `core/post-comment-date`

Warning: Attempt to read property "comment_date" on null in C:\apache\htdocs\wp-a2z\wp-includes\comment-template.php on line 557

Warning: Attempt to read property "comment_date" on null in C:\apache\htdocs\wp-a2z\wp-includes\comment-template.php on line 557

- `core/post-comment-content`

Warning: Attempt to read property "comment_content" on null in C:\apache\htdocs\wp-a2z\wp-includes\comment-template.php on line 971

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2474435/109649612-12559500-7b54-11eb-8ed0-a2f85171f7cf.png)

## WordPress information
- WordPress version:  5.6.2  / 5.7-beta3
- Gutenberg version: 10.0.2 
- Are all plugins except Gutenberg deactivated? No. 
- Are you using a default theme (e.g. Twenty Twenty-One)? No. I'm using Fizzie 

## Device information
- Device: Desktop 
- Operating system:  Windows 1-
- Browser: Chrome 88

**Comment by carolinan** [comment]
Hi Herb!
Some time has passed, do you know if this issue is still valid?

I can see that the PHP files for these blocks only checks if the `commentId `is set, it does not check its format.
But I can't find any comment related block that expose the commentId as an attribute in the block markup.
I don't think it is possible to manually edit the comment id in the comment blocks, not anymore?

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
