### ISSUE TITLE
Incorrect error handler used when dragging a replacement image

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#29480]
## Description

When drag and drop is used on the media manager to replace an existing image and an error is returned, the error is not shown in the media manager. It is shown in the block behind the media manager instead and is not visible to the user.

## Step-by-step reproduction instructions

Put the following code into place to force the media upload process to return an error:

```php
add_filter( 'wp_handle_upload_prefilter', function( $file ) {
	$file['error'] = 'Error!';
	return $file;
} );
```

1. Edit or create a post containing an image block with a valid image in it
2. Click the Replace toolbar button
3. Click the Open Media Library menu item
4. Drag and drop a file into the media library
5. Observe the media library modal goes blank
6. Close the modal and note that the error message is shown in the block instead

## Expected behaviour

The error message should be shown in the media manager sidebar. This is the case in all other media workflows that I've tested, it appears to be just this specific workflow that is broken.

## Actual behaviour

The media library modal goes blank and the error message is shown in the underlying block instead.

## WordPress information
- WordPress version: 5.7 RC1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? yes

**Comment by getsource** [comment]
@johnbillion As always, thanks for the report!

I tested this today, and unless I missed a step, it looks like this may have been fixed.

Can you please test again to see if it works for you?

Here's a screencast:

https://user-images.githubusercontent.com/1034160/126603359-fb767dfb-71f2-4779-8fe4-90fb2df34df2.mov

**Comment by johnbillion** [comment]
Also looks good to me.

<img width="296" alt="" src="https://user-images.githubusercontent.com/208434/126642837-c2273bd6-911d-4824-ace7-eb79a3e3ac40.png">
