### ISSUE TITLE
SiteEditor: Listview content does not always show all blocks on the page

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#29486]
## Description
While going through the call for testing in the FSE project, there was a task to use the Listview in the index template, to jump to a position outside the header. When I opened the listview, I could only see the Header blocks. Only after clicking a bit aimlessly on other sections of the index template, I could also see other items in the Listview. 

## Step-by-step reproduction instructions

1. Use TT1-Blocks Theme
2. Open the Site Editor
3. Use the Template: Index 
4. Modify the Site title 
5. use the Listview to jump to the footer. 

## Expected behaviour
Independently from the last block selected, I expected to see all items on the page listed in the listview. 

## Actual behaviour
When a block in the header section is selected, the Listview only shows the blocks of the header template part. Same is true when I select a block in the Footer section. When I click in the content section of the index template, I see all elements on the page in the Listview. 

## A Screen recording (optional)

https://user-images.githubusercontent.com/39980/109706375-df68cc80-7b66-11eb-8c86-284e89c660ce.mp4

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1.0.20210301 (GB-Nightly)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No - TT1-Blocks

## Device information
- Device: Desktop
- Operating system: MacOS 10.14.6
- Browser: Chrome: 88.0.4324.192

**Comment by Addison-Stavlo** [comment]
Hi @bph !  A new list view component was added to the site editor in the last day.  I believe it should solve the issue.  You can distinguish it from the old version as it is now a side panel similar to the block inserter:

![Screen Shot 2021-03-02 at 6 34 18 PM](https://user-images.githubusercontent.com/28742426/109729527-fc60c800-7b85-11eb-885e-cb828516feb6.png)


As far as I can tell it solves the problem, so I am going to close this issue.  As always, feel free to reopen this issue if this problem persists.

**Comment by bph** [comment]
Thanks. @Addison-Stavlo - [I assume you are referring to this PR? ](https://github.com/WordPress/gutenberg/pull/28637)
