### ISSUE TITLE
Global Styles: User-customized Preset Colors not respected everywhere.

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#29487]
## Description
When a user customizes a preset palette color the value isn't respected in the editor or in .has_{preset}_color and the like.

## Step-by-step reproduction instructions
* Use a theme with support for Global Styles.
* Define a custom color palette value in `settings.defaults.color.palette[]` such as `sandwich` with a recognizable color such as `#FF0000`
* Define another custom color palette value in `settings.defaults.color.palette[]` such as `pickle` with a recognizable color such as `#00FF00`
* Assign the palette color `pickle` as the default text color of the paragraph block in the theme.json
* Load the Page editor and create two paragraph blocks. Assign one of those blocks the color palette value (`sandwich`) that was just created and leave the other one to be the default.
* Load the view.  Note that everything is groovy and the color it should be.
* Load the FSE and using the Global Styles panel change the color value of the sandwich swatch to something else recognizable such as `#0000FF` and the value of pickle to be another recognizable value (such as `#FF00FF`);
* Return to the Page Editor and note that the value being shown for the `sandwich` palette value is the original value assigned in theme.json (`#FF0000`) and not the value assigned in the FSE Global Styles customizer.
* Return to the View of the page with the paragraph assigned the value of `sandwich` as the text color.  Note that it is still the color of the original value of `sandwich` as defined in theme.json and not as the user defined it.
* Note that the color of the default paragraph has changed to be the color that the user defined in the FSE Global Style panel.

Note that the inline styles rendered from the theme.json includes:
a `:root{` section that has all of the values from theme.json.
followed by a second `:root{` section that repeats the same color values that have been changed.  Therefore anything that is leveraging the `--wp--preset--color--SLUG` CSS variable will be provided the correct value.
Following that, however, is a collection of `.has-SLUG-color .has-SLUG-background-color` classes.  These are also repeated (once for theme.json and once for the customized values).  Because these selectors are identical the last one rendered wins (in this case the classes created from the values in theme.json and not the values customized by the user).
Addressing this issue (possibly just changing the order those two sets of classes are generated and added to inline styles) will correct what is rendered in the view.

## Expected behaviour
The color swatches in the Page/Post editor should represent what has been customized via Global Styles Panel.
The colors assigned by using the classes .has-SLUG-color or .has-SLUG-background-color should be the values as customized via the Global Styles Panel.

## Actual behaviour
They do not.

## Screenshots or screen recording (optional)
```
{
	"settings": {
		"defaults": {
			"color": {
				"palette": [
					{
						"slug": "sandwich",
						"color": "#FF0000",
						"name": "Sandwich"
					},
					{
						"slug": "pickle",
						"color": "#FF00FF",
						"name": "Pickle"
					}
				]
			}
		}
	},
	"styles": {
		"core/paragraph": {
			"color":{
				"text":"var(--wp--preset--color--pickle)"
			}
		}
	}
}
```
Initial View:
![image](https://user-images.githubusercontent.com/146530/109707364-14295380-7b68-11eb-8ee6-15e5ff0e7b10.png)

Initial Color Values in the Editor:
![image](https://user-images.githubusercontent.com/146530/109707445-2c996e00-7b68-11eb-873e-e12dcab8b2be.png)

Initial Color Values in FSE Global Styles Panel:
![image](https://user-images.githubusercontent.com/146530/109707541-476be280-7b68-11eb-9396-8be0aa66f718.png)

(so far so good)

Modify colors in FSE Global Styles Panel:
![image](https://user-images.githubusercontent.com/146530/109707825-a2053e80-7b68-11eb-82ba-6abc78dfcca7.png)

Color Values in the Editor (after changing via GS Panel):
![image](https://user-images.githubusercontent.com/146530/109707937-c4975780-7b68-11eb-84c4-4008e885c4d9.png)

(no change)

View (after changing via GS Panel)
![image](https://user-images.githubusercontent.com/146530/109708061-e55fad00-7b68-11eb-96f8-4cc152e2331b.png)

(note that the 'default' color changed but the 'assigned' color did not)

## WordPress information
- Gutenberg version: 10
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by kathrynwp** [comment]
Hi @pbking just circling back, is this still an issue in the latest version of WordPress and/or Gutenberg? (I started to try to replicate, but am not finding `settings.defaults.color.palette` in theme.json in Twenty Twenty-Two, so it's very likely that Global Styles works different now and the testing steps would need updating.) Thanks in advance for having another look to see if this issue is still relevant or if it can be closed out.
