### ISSUE TITLE
<InnerBlocks /> markup

### ISSUE THREAD

**Issue by aminta** [WordPress/gutenberg#29482]
Using <InnerBlocks /> in a block, Wp Gutenberg automatically creates this markup in editor between the block and its content

```
<div class="block-editor-inner-blocks">
 <div class="block-editor-block-list__layout">
     // [...here the content ]
```

However looking at the code generated by the core columns block, the columns are direct children of their container.

Is it possible implement this feature?

**Comment by stokesman** [comment]
See the use of `useInnerBlocksProps` in the Buttons block (or any of the other core blocks that use it).
https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-library/src/buttons/edit.js

**Comment by talldan** [comment]
The `useInnerBlocksProps` feature is still experimental, so not recommended right now for plugins as the API may change.

It should hopefully be something that stabilises soon and at that point there will be docs on how to use it.
