### ISSUE TITLE
Site Editing & Responsiveness - Breakpoint specific block settings (especially navigation block).

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29493]
Note - Il initially note this as for 'navigation block' as it seems to be one of the most necessary places for this sort of control.  But in general we probably need a way to enable something like this across the board? 🤔 

### The Problem

In the Site Editor we allow editing content in device previews such as mobile and tablet:

<img src="https://user-images.githubusercontent.com/28742426/109732705-af7ff000-7b8b-11eb-90a9-55fed6beca94.png" alt="image of mobile preview editing" width="420px" />

This could lead users to believe that the settings their apply inside these device previews should apply specifically to that device size, while in actuality it effects the design at all screen widths.

### An example

Lets use the navigation block as an example.  At full screen with it may look best when set to the 'horizontal' variation:

![Screen Shot 2021-03-02 at 3 18 22 PM](https://user-images.githubusercontent.com/28742426/109733103-7b58ff00-7b8c-11eb-9f7d-b36ca4baae1c.png)

But as soon as we get to tablet and mobile, it is clear we would want to use the 'vertical' variation at these screen widths:

<img width="1372" alt="Screen Shot 2021-03-02 at 7 12 01 PM" src="https://user-images.githubusercontent.com/28742426/109733170-94fa4680-7b8c-11eb-9ba5-4a86e0c572f5.png">

<img width="687" alt="Screen Shot 2021-03-02 at 7 12 54 PM" src="https://user-images.githubusercontent.com/28742426/109733183-975ca080-7b8c-11eb-9d63-7c8dffd793b6.png">

### Potential solutions

Allowing block settings set in these modes to be specific to that screen size only may help empower creation of well responsive site layouts and content.

**Comment by mtias** [comment]
Closing in favor of #22824. The approach we want to take with these is one of "better defaults" rather than per breakpoint settings, which can get rather complicated (as seen in #19909).
