### ISSUE TITLE
useAnchorRef From @wordpress/rich-text Package Returns Undefined

### ISSUE THREAD

**Issue by TeamDNK** [WordPress/gutenberg#29496]
## Description
Unable to import `useAnchorRef` from `@wordpress/rich-text` package. When I attempt to import the function it returns undefined. Currently I am importing it on a newly registered format type into the `Edit` component. It will then be used in a custom `Popover` component. 

## Step-by-step reproduction instructions
1. Import useAnchorRef
2. Log useAnchorRef to the console

## Expected behaviour
To return the anchor reference when executed.

## Actual behaviour
Returns undefined

## Package Information
 - @wordpress/rich-text@3.24.7
 - @wordpress/components@12.0.7
 - @wordpress/scripts@13.0.3

## Code snippet (optional)
```
import { 
	registerFormatType, 
	getActiveFormat, 
	useAnchorRef 
} from '@wordpress/rich-text';

function ModalEdit( { ...props } ) {
	
	const anchorRef = useAnchorRef({ ref, value, settings})
	
	// Returns undefined
	console.log( useAnchorRef )
	
	return (
		<>
			<RichTextToolbarButton
				title="Modal Link"
				icon={ modalLinkIcon }
				onClick={ openModal }
			/>
			{ isOpen && (
				<ModalPopover
					name={ formatName }
					value={ value }
					anchorRef={ anchorRef }
				/>
			) }
		</>
	);
}

registerFormatType( 
	formatName, 
	{
		title: 'Modal Link',
		tagName: 'a',
		className: 'modal-link',
		edit: ModalEdit,
	} 
);
```

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: macOS Big Sur
- Browser: Safari 14.0.3

**Comment by talldan** [comment]
This is exported here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/index.js#L35

It definitely is exported correctly, I just checked in a CodePen. It's also used throughout this codebase in the way you describe.

@TeamDNK I'd recommend checking what version of `@wordpress/rich-text` you have in your node_modules folder. It could be that you have an outdated dependency.

**Comment by TeamDNK** [comment]
@talldan 

I found out what's going on here. Turns out useAnchorRef does not ship with WordPress 5.6.2. Installed the Gutenberg plugin in order to develop with this function until it is merged into the WordPress standalone.
