### ISSUE TITLE
Site Editor - rough loading states and broken styles in loading process.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29492]
When using the site editor on a poor connection and/or limited cpu, the loading of content in the editor is a bit of a mess.  

![slow-connection-load](https://user-images.githubusercontent.com/28742426/109730539-a1c86b80-7b87-11eb-9408-29da827ff607.gif)

There is quite a bit going on and its difficult to parse, but some thoughts:
* Add consistent loading placeholders for blocks that need to load (template parts, post contents, site blocks, etc.).
* If block variations effect the visual styles, we should consider not showing the block until its variation has had a chance to be identified.
* Ensure styles for editor and blocks are loaded before blocks are shown (we can notice some styles, spacing, padding, etc. changing throughout the loading process).
*  Consider hiding the content section of the editor behind loading UI until it has actually loaded the majority of the content.

**Comment by mtias** [comment]
Related:
- Review render flow when switching template view #25819
- Loading state of blocks with entities #22072
- Present "placeholder" blocks clearly #19256

**Comment by annezazu** [comment]
In my mind this issue is covered nicely by the above items along with this overall one around improving the loading state https://github.com/WordPress/gutenberg/issues/35503 As a result, I'm going to close this out but am happy to re-open if folks would prefer.
