### ISSUE TITLE
Enable two+ word block searches with the slash command

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29495]
## What problem does this address?

Currently, if you are trying to search for a block that has more than 1 word with the `/` command, you're unable to complete the search. For example, you can't type `/site logo` as the second you add a space the `/` command goes away. This came up in the latest [FSE Outreach Program's call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/) particularly as many of the Site Editor blocks have two words in their name. 

https://user-images.githubusercontent.com/26996883/109734878-0206df80-7b7f-11eb-8bbf-b1ca9e0d6e07.mov

## What is your proposed solution?

Enable the ability to search for multiple words when using the `/` command :) Some of this likely touches on this currently open issue: https://github.com/WordPress/gutenberg/issues/22194

**Comment by gziolo** [comment]
I have just opened #29939 that attempts to fix this issue.

**Comment by annezazu** [comment]
Amazing! Testing it now.
