### ISSUE TITLE
Query Block: allow for the ability to undo setting changes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29494]
## Description

As part of the [second FSE call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1362), a person who responded with feedback found that they were unable to undo changes to the settings when using the Query block after initially selecting how the block should display.

## Step-by-step reproduction instructions

1. Use a block based theme and the latest version of Gutenberg to setup the FSE experience.
2. Go to "Site Editor (beta)"
3. Add a query block
4. Select an initial setup (Post title with excerpt, etc)
5. Try to undo the selection. Find out that you can't!

## Expected behaviour

I expected to be able to undo setting changes. 

## Actual behaviour

I was unable to undo changes to the initial query block setup. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/109733591-a3406680-7b7c-11eb-96ce-8bd7bb6dcb9a.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by annezazu** [comment]
@ntsekouras reopening this as the undo option seems to be slightly broken if you choose "Start Blank" but then want to go back to choose from the new pattern selector. Here's a video:

https://user-images.githubusercontent.com/26996883/117335527-7cdac800-ae58-11eb-97af-5d7075afdd84.mov

This is using 10.6 RC

**Comment by ntsekouras** [comment]
This not actually about Query because in this case we haven't yet created anything, so `undo` works properly. It's a combination of `__experimentalBlockPatternSetup` and `__experimentalBlockVariationPicker` to add conditionally a `back` button.

I've created an issue that describes the problem better here: https://github.com/WordPress/gutenberg/issues/31593
