### ISSUE TITLE
Header: What does the WP icon means?

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29509]
While testing the Site Editor, we noticed that the fullscreen mode's WP icon usage isn't immediately clear.

The icon is used to either close the editor and navigate back to the dashboard (in the Post Editor), or to open the Navigation sidebar (in the Site Editor).

In the Post Editor it might be slightly clearer: the WP icon could subtly hint that it's a link back to the WP dashboard.
Although, when a site icon is set, that subtle hint ceases to exist.

Neither a WP icon nor a site icon are semantically connected to either "close" or "menu" meanings, which are more commonly referred to with the "X" (or "back arrow") and "hamburger" icons respectively.

**Comment by mtias** [comment]
There's some context and discussions on this topic at #20579 and all the issues related to using arrows, etc. There's also the explorations at #22191 and #18387. See also #22178 and #21739 for more usability considerations. 

The use of tooltips is important as well in handling missing context. I disagree though that the site icon doesn't offer a hint. It can be much better than any single icon in conveying the "home" nature of opening it. It can take some time to establish and refine a core navigation pattern, though.

Going to close so we can keep the discussion in the existing issues and not fragment the conversation.
