### ISSUE TITLE
Template part block: Last Paragraph block is acting strange (crashes the editor and/or other blocks)

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29508]
## Description
Firefox and Chrome both result in a different bug but it happens by doing the same reproduction steps.

## Step-by-step reproduction instructions
1. Open site editor
2. Add template part block
3. Remove the temporary paragraph block that's added at the end of the template part
4. Move your cursor around
5. Firefox: WSOD :( / Chrome: Blove above pargraph crashes :(

## Expected behaviour
Paragraph is removed

## Actual behaviour
Editor crashes. The paragraph block is removed but it still appears in the editor, but not in the list view.

## Screenshots or screen recording (optional)

**Firefox**  Deleting the Paragraph using backspace/delete then move the cursor around which results in crash: (Notice how Paragraph disappears from the list view)

https://user-images.githubusercontent.com/2256104/109799038-cd953100-7c1b-11eb-989c-0feb0ee328cb.mov

https://user-images.githubusercontent.com/2256104/109799267-1fd65200-7c1c-11eb-83e4-e25ab4b145b8.mov

**Chrome** Deleting the Paragraph using backspace/delete then move the cursor around. Navigation block above the Paragraph errors.

https://user-images.githubusercontent.com/2256104/109799874-cfabbf80-7c1c-11eb-84ed-6fdf3ca30897.mov

Error:
![image](https://user-images.githubusercontent.com/2256104/109798861-8d35b300-7c1b-11eb-860f-caf7cb6bb81c.png)

## WordPress information
- WordPress version: 
- Gutenberg version: `master`
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1B

## Device information
- Device: MacBook Pro
- Operating system: macOS
- Browser: Firefox and Chrome latest

**Comment by Addison-Stavlo** [comment]
Im unable to repro on either browsers, are you still seeing this issue?  Im wondering if it has been resolved elsewhere in the meantime.

**Comment by david-szabo97** [comment]
Yep, can't reproduce this anymore. Closing it.
