### ISSUE TITLE
Social Icons: Show the URL inserter after adding an icon

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29507]
Inserting an icon doesn’t prompt anything, to the point that users might be tricked into assuming that the button is working as-is, even though in fact it needs a URL to function.

Users need to click again on the just-inserted icon, and the URL picker will pop up.

I think it makes more sense to show the URL picker immediately after an icon is inserted.

**Comment by jasmussen** [comment]
I created https://github.com/WordPress/gutenberg/issues/29505 for this exact problem. What do you think?

**Comment by Copons** [comment]
> I created #29505 for this exact problem. What do you think?

@jasmussen Ha! Missed this notifications!
Yes that would definitely help.
I'll close this issue in favour of yours. 👍
