### ISSUE TITLE
Global Styles: Is the "root" term too technical?

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29512]
Global Styles can be applied on a per-block type basis, or to the "root", which means that custom styles will affect all content that doesn't have a more specific style applied (e.g. the "by block type" Global Style, or block styles).

While Global Styles in general could use a warning about how style specificity works, being a programmer, the meaning of the term "root" is clear to me.
But is it as clear for general users too?

**Comment by mtias** [comment]
Definitely not! The current global styles panel should be seen as a "developer debug" tool for theme.json. The final user-facing design is going to be more along these lines, with no trace of "root":

![image](https://user-images.githubusercontent.com/548849/109813463-ac3d4080-7c2d-11eb-9edb-41c2f3cc2f7f.png)

**Comment by Copons** [comment]
Thanks, I haven't followed the dev of GS and had no idea there were plans to iterate on the UI!
I'll close this as not needed. 👍

**Comment by mtias** [comment]
Yes, it needs a lot of updates :)
