### ISSUE TITLE
Site Editor Navigation Panel - Allow 'esc' to close the panel.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29530]
## What problem does this address?

The site editor navigation panel has no keyboard shortcut to close the panel.  In keyboard flows a user must navigate back to the toggle button to close the panel.  For reasons noted in https://github.com/WordPress/gutenberg/issues/29529 the interaction with that toggle button may also be confusing.

![Screen Shot 2021-03-03 at 1 06 34 PM](https://user-images.githubusercontent.com/28742426/109852158-7a72ac80-7c22-11eb-9a4e-1d023d776bac.png)

## What is your proposed solution?

Allow 'esc' key to close the navigation panel while it is focused.

**Comment by Quintis1212** [comment]
Hello ) I think I can implement this )

**Comment by Quintis1212** [comment]
Hello ) I created PR to your issue

**Comment by Addison-Stavlo** [comment]
closed with the above PR
