### ISSUE TITLE
Post Tags/Categories Blocks: clicking on block navigates to archive page

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#29539]
## Description

The Post Tags and Categories block jump to the top of the page when clicked in the site editor.

Additionally, an un-styled wpadminbar appears before the content.

## Step-by-step reproduction instructions

1. Activate a block theme like TT1 Blocks and load the site editor.
2. Select a template or content that contains a Post Tags and/or Categories block(s), such as the index template.
3. Click on one of the those blocks.

## Expected behaviour

I start editing the block

## Actual behaviour

It appears that I navigate to the archive page for that tag or category (within the site editor iframe).

## Screenshots or screen recording (optional)

![click-post-tag-block](https://user-images.githubusercontent.com/1699996/109876682-a8aeb700-7c37-11eb-86f0-9b4dac143ec8.gif)

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (TT1 Blocks)

## Device information
- Device: Desktop
- Operating system: macOS
- Browser: Firefox

**Comment by carolinan** [comment]
I am able to reproduce this.
I believe that for the linked post title and also the site logo, `onClick={ ( event ) => event.preventDefault() }` is added to the link to prevent this.
-Maybe there is a better way than doing it per block.
