### ISSUE TITLE
Link color doesn't work anymore in 10.1.0

### ISSUE THREAD

**Issue by BKnapen** [WordPress/gutenberg#29535]
Setting the "Link color" in the paragraph block editer doesn't work anymore.! prevous versions links color was working since 10.1.0 not any more.

**Comment by annezazu** [comment]
@BKnapen thanks for reporting this! I tried to replicate by adding a paragraph, adding a link, and then changing the color. I found I was able to do so. Can you provide exact replication steps to reproduce this as well as any screenshots? Thanks in advance!

**Comment by carolinan** [comment]
In a traditional/PHP based theme with `add_theme_support( 'experimental-link-color' );` ,
the link color option is available, but the selected color is not applied in the editor or the front.
I tested in a few default themes by adding the theme support. (Twenty Twenty-One also has support for this feature)

When I activate TT1 Blocks and try the link color option in the post editor, the link color option works because a color is assigned to 
`--wp--style--color--link`

Gutenberg Version 10.1.1  and current trunk https://github.com/WordPress/gutenberg/commit/7047eac082274494ed88f30a10572d08db8b0cf4

WordPress 5.7-RC3-50503
Windows 10
Chrome version 88.0.4324.190

**Comment by youknowriad** [comment]
@nosolosw do you know what changed recently that might have impacted this?

**Comment by nosolosw** [comment]
It looks like this goes back to 9.6 when [the logic was updated](https://github.com/WordPress/gutenberg/pull/27779/files#diff-0b8e98dead5542e95159bd3c482158111d3f16637e7eef9af13373358fa42dedL164) to not enqueue the Global Styles CSS if the theme declared theme.json ― which includes the colors as CSS vars, a requirement for the link color feature to work.

I see two paths forward here:

1. We don't enqueue any CSS for themes without theme.json support => the link color feature should be disabled for these themes.
2. We enqueue the presets declared by the theme as CSS variables for themes without theme.json support => the link color can still work for them.

I remember that change aimed to address reports of theme authors in core-editor that found it weird that their themes would have some CSS they can't control and can conflict with its own CSS. I presume that rationale is still valid so I'd go with 1.

**Comment by carolinan** [comment]
This is a theme support add_theme_support( 'experimental-link-color' ); expected to work without a JSON file.
So I don't think we can go with 1?

**Comment by carolinan** [comment]
Can't we add a color for the variable in the theme support? I mean similar to the color palette.

**Comment by oandregal** [comment]
In https://github.com/WordPress/gutenberg/issues/29891 we're converting the link to an element ― it'll be no longer a simple color for links, it'll be able to have many more things (color background, typography, etc).

Additionally, `add_theme_supports('experimental-link-color')` only works with the plugin active and is experimental. I'm thinking that the path forward should be removing the `add_theme_supports('expelimental-link-color')` a couple of releases after the elements PR lands and embrace the fact that the link API is tied to theme.json.

**Comment by youknowriad** [comment]
So I've checked this a bit as well and for me it seems the solution is as simple as adding:

```
a {
color: var(--wp--style--color--link, blue ); // blue is the default color here 
}
```

to your theme's stylesheet. I think that's a decent fix for an experimental API. Am I missing something?

**Comment by youknowriad** [comment]
Oh I guess the presets styles are not generated anymore. For me this should be fixed and presets styles (CSS variables or not) should be generated properly regardless of how the theme is providing them. (theme.json or theme support flag)
