### ISSUE TITLE
Site Editor: Enhance the "Add template" flow.

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29558]
Currently the add-template experience is a little lacklustre:

<img width="635" alt="Screenshot 2021-03-04 at 10 56 25" src="https://user-images.githubusercontent.com/846565/109953692-4eb1fe00-7cd8-11eb-8b13-7aefb13e8c76.png">

The popover menu reduces what could potentially be a visual exercise to something that is very text-heavy, and potentially difficult to grok for folks who are unfamiliar with templates.

An interface that visually displays the templates might be more intuitive. Especially if we consider that [block patterns associated with templates may exist](https://github.com/WordPress/gutenberg/issues/28739#issuecomment-785051750).

**Comment by jameskoster** [comment]
We should concentrate on templates initially, but it's worth keeping in mind how the design we produce here could potentially be used for adding posts / pages from the Sidebar Menu in the Site Editor as well.

**Comment by jameskoster** [comment]
Here's an option for this:

https://user-images.githubusercontent.com/846565/110111355-1a0d7780-7da8-11eb-8a2c-9ae451c50eeb.mp4

After clicking the + icon to add a template, a full-screen modal (#28574) appears to present the options, including thumbnail previews.

If block patterns that are associated with the chosen template exist, they are presented as layout options. In the video above I select the Single Post template, after which I am presented two layout options – one including a sidebar and one omitting it. There's an option to skip this step and "Start blank".

After choosing a layout the template is created with a Snackbar confirmation.

I suspect there is a balance to be struck here with regards to whether we present these as two discrete steps, or whether they could somehow be combined. One issue with combining the steps could be information overload when there are many patterns to choose from.

---

For fun I decided to see how this concept might work for content flows as well. Here's adding a page:

https://user-images.githubusercontent.com/846565/110111826-d2d3b680-7da8-11eb-84c6-36033b002c5f.mp4

In this case we can skip the template selection step from the process above, since that is governed by the post type. But we can re-use the layout/pattern selection interface to present pre-configured page layouts (block patterns) that could help folks get started more quickly.

We'll need to consider adding search/filter functionality to the layout/pattern selection step in both cases as the pattern library expands.

**Comment by aristath** [comment]
Nice, I love it! Amazing work @jameskoster

**Comment by paaljoachim** [comment]
Hey James. It would be great to see what this would look like in a modal.
Thanks.

**Comment by jameskoster** [comment]
Closing in favor of #37407
