### ISSUE TITLE
Wordpress site crashed after upgrade of Gutenberg

### ISSUE THREAD

**Issue by 3dflip** [WordPress/gutenberg#29551]
I just deactivated plugin for now, but can someone help me ? Regards.

 👍 WordPress version 5.3.6
Thème actuel : Wallstreet-Pro (version 1.7.7) Extension actuelle : Gutenberg (version 10.1.0) PHP version 7.3.17

Détails de l’erreur
======================
Une erreur de type E_ERROR a été causée dans la ligne 129 du fichier /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-content/plugins/gutenberg/lib/blocks.php. Message d’erreur : Uncaught Error: Call to undefined function register_block_type_from_metadata() in /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-content/plugins/gutenberg/lib/blocks.php:129
Stack trace:
#0 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-includes/class-wp-hook.php(288): gutenberg_reregister_core_block_types('')
#1 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-settings.php(523): do_action('init')
#4 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-config.php(89): require_once('/srv/data/web/v...')
#5 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-load.php(37): require_once('/srv/data/web/v...')
#6 /srv/data/web/vhosts/www.xxxxxx.fr/htdocs/wp-admin/admin-ajax.php(22): require_once('/srv/data/web/v...')
#7 {main}
  thrown

**Comment by talldan** [comment]
Hmm, it does say 5.3 is supported on the plugin page, but I thought it should be 5.4 (two versions back) - https://wordpress.org/plugins/gutenberg/

**Comment by talldan** [comment]
Oh, 5.5 is two versions back, oops. I confirmed on slack that this should be the minimum supported version (https://wordpress.slack.com/archives/C02QB2JS7/p1614856290064700). The plugin page is wrong for some reason.

@3dflip Apologies for that. I'd recommend either downgrading your Gutenberg plugin, or upgrading your WordPress installation.
