### ISSUE TITLE
Rename "Classic Text" to "Classic"

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2956]
## Issue Overview

Whenever you load a post written before Gutenberg, or if you prefer this way of editing, you use the block currently called "Classic Text". This block is/aims to be the current WordPress editor, in block-form. It supports/should support everything the editor in WordPress today supports, but other blocks can live before and after it. 

We previously called this "Freeform", it's also been nicknamed "Writer's Block" ;). "Classic Text" was given to ambiguate it from the Paragraph block which was previously called "Text". 

With all the changes and the behavior of Gutenberg currently, calling it "Classic Text" seems like a disservice. Should we call it, just, "Classic"?

**Comment by iseulde** [comment]
Yeah the text part seems strange as it's not just text.

Maybe even "Classic Editor" or "Classic Editor Block"?

**Comment by jasmussen** [comment]
It's tricky, because although it's an Editor, it's an editor within an editor. We're also struggling with how to phrase the descriptive text as you can see in https://github.com/WordPress/gutenberg/pull/2919. 

"Classic" so far is perhaps not descriptive, but would it be more confusing to have an "Editor" be a block?

**Comment by androb** [comment]
Rich Text?

Mulitparagraph?

TinyMCE?

There probably needs to be a discussion about whether It has utility beyond legacy compatibility. If so a name other than Classic would possibly help.

**Comment by iseulde** [comment]
@androb Gutenberg is all of those too, so that doesn't make much sense? I think "Classic ..." captures it well. "Classic" sounds good to me, but I also don't see a problem with "Classic Editor" or "Classic Editor Block" as  it is really an editor within an editor, and anything can be a block right? 😉 Don't see how it could be confusing, on the contrary, it illustrates the power of it.

**Comment by androb** [comment]
Classic is good with me if the vision for it is about backwards compatibility.

It's purpose has moved around a bit during the course of the project so if Classic still makes sense, all well and good.

**Comment by karmatosed** [comment]
+1 for Classic.
