### ISSUE TITLE
FSE: Add ability to set favicon

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29578]
## What problem does this address?

As part of the [second FSE call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1369), the ability to set a site's favicon was raised as currently this is set using the Customizer. With FSE, there seems to not currently be a way to set this up!

## What is your proposed solution?

Enable a place to set the favicon. This might work nicely in Global Styles as a start as I imagine that would be a natural place where users might look.

**Comment by carolinan** [comment]
I am closing this as it is a duplicate of https://github.com/WordPress/gutenberg/issues/29126

**Comment by annezazu** [comment]
Ah! Icon :D Should have searched for that as well as favicon. Thank you.
