### ISSUE TITLE
Custom block registration fails due to capitalized letters in the name?

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg#2958]
## Issue Overview
Custom block name can only contain numbers, dashes, and **lowercase** letters - capital letters will cause WordPress to barf with an inappropriate error.

## Steps to Reproduce (for bugs)
`registerBlockType("testing/editableBlockTesting", {...`

## Expected Behavior
I expect the block to be registered

## Current Behavior
Console error 'Block names must contain a namespace prefix. Example: my-plugin/my-custom-block'

## Possible Solution
The following works perfectly:
`registerBlockType("testing/editable-block-testing", {...`

If there's a reason for forcing lowercase, both document that and set up a more appropriate error message when this situation arises.

Otherwise, I'd think updating the regex to `/^[A-Za-z0-9-]+\/[A-Za-z0-9-]+$/`
would take care of it.

**Comment by pento** [comment]
Thanks for the bug report, @maxxwv! I've added a more relevant error message for uppercase characters in #2950 to address this.

**Comment by maxxwv** [comment]
@pento - Thanks!

I wonder, though, because the naming convention is so strictly limited, should the error message be a bit more encompassing? Perhaps run a test against "[^a-z0-9-]" to test for the existence of any characters _other_ than those allowed and let the user know? Right now, using an underscore instead of a dash will still display the namespace error, which is less than ideal in this situation.

**Comment by pento** [comment]
That's a good point, @maxxwv. On further inspection, I noticed [some more inconsistencies](https://github.com/WordPress/gutenberg/pull/2950#issuecomment-335990930) between the code and the parser, so it's probably worth having a separate PR to tackle these problems.

**Comment by youknowriad** [comment]
The message is more preciese now `Block names must contain a namespace prefix, include only lowercase alphanumeric characters or dashes, and start with a letter. Example: my-plugin/my-custom-block`. I'm closing. Feel free to reopen if I missed something.
