### ISSUE TITLE
No option to add a block above the 1st block

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#29594]
## Description

Unable to add a block above the first block in a post. There's not a + icon when hovering at the top of the first block (see gif).

- First reported in [support forums](https://wordpress.org/support/topic/the-top-add-block-option-is-missing-no-plus-mark/)
- and then with a [core track ticket](https://core.trac.wordpress.org/ticket/52706).

## Step-by-step reproduction instructions
1. Add any block to a post
2. Hover over the first block and attempt to add a new first block

## Expected behaviour
When hovering over the first block, a + icon appears to allow adding a block before it.

## Actual behaviour
No option appears to add a block before it.

## Screenshots or screen recording (optional)
![52706](https://user-images.githubusercontent.com/7284611/110162579-8bebbe00-7db4-11eb-83d3-4b617bd5fcc8.gif)

## WordPress information
Me:
- WordPress version: 5.6.2 and 5.7 RC2
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? No plugins are active
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

Original reporter:
- WordPress version: 5.7 RC2
- No plugins
- Twenty Twenty-One theme

## Device information
Me:
- Device: Desktop
- Operating system: Mac Big Sur
- Browser: Chrome 88.0.4324.192, Firefox 86.0, and Safari 14.0.3 

Originally reporter:
- Device: Desktop
- Operating system: Edition Windows 10 Pro
- Browser: Chrome 88.0.4324.190, Firefox 86.0, and Microsoft Edge 88.0.705.81

**Comment by mtias** [comment]
Just for completeness:

![image](https://user-images.githubusercontent.com/548849/110169670-50bfae00-7df9-11eb-8147-1ae486eb7583.png)

**Comment by a4jp-com** [comment]
Thank you @hellofromtonya and @mtias. Looks like the horizontal line doesn't show up at all on Macs. I'll check my site on Safari, on an iPad and MacBook tonight. On a PC there is a long horizontal line which makes it easier to find the plus mark.

**Comment by mtias** [comment]
Closing since there are a few ways now to insert a block before the first (the ellipsis menu in both the block and the list view).

**Comment by a4jp-com** [comment]
I don't think it's good at all. Just leaving this broken.

**Comment by a4jp-com** [comment]
Why hide the top one only in a menu? We don't even have a plus mark between short codes. Please fix Gutenberg.
