### ISSUE TITLE
Framework: Find a better way to provide the scrollable container

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#2959]
Context in this PR https://github.com/WordPress/gutenberg/pull/2953

- Either use a prop and pass it down to the VisualBlock component
- or use the context, maybe include this in the Editor settings.

**Comment by jasmussen** [comment]
Is there any relation between potential solutions to this ticket, and #2420?

**Comment by aduth** [comment]
Closed by #3546
