### ISSUE TITLE
Suggest Block templates, add unique identifier upon Custom Post Type registration to blocks

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#29604]
When using Gutenberg in a Wordpress environement, the ability to target a specific block content could be greatly improved.

Upon registering a new Custom Post Type, currently we have the ability to set a [blocks template](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/) by specifying an array of blocks.

If we could somehow set a secondary unique identifier for any Gutenberg blocks, functions like [parse_block()](https://developer.wordpress.org/reference/functions/parse_blocks/), ease of use, would be greatly improved and it would open new ways to use any blocks content data. 

Something along the lines of:
```php
function myplugin_register_book_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Books',
        'show_in_rest' => true,
        'template' => array(
            array( 'core/image', array(
                'identifier' => 'custom-template-hero', //for example 
                'align' => 'left',
            ) ),
            array( 'core/heading', array(
                'identifier' => 'custom-template-author', //for example 
                'placeholder' => 'Add Author...',
            ) ),
            array( 'core/paragraph', array(
                'identifier' => 'custom-template-description', //for example 
                'placeholder' => 'Add Description...',
            ) ),
        ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

thank you in advance for your consideration.

**Comment by talldan** [comment]
> functions like parse_block(), ease of use, would be greatly improved and it would open new ways to use any blocks content data.

@amarinediary Would you be able to go into more detail about the above part. What would use the extra identifier for?

**Comment by amarinediary** [comment]
Sure thing @talldan, right now you can easily target blocks using their blocks name ( core/paragraph, core/freeform ... ), but when you're using multiple paragraph blocks, for example, you can't target one specifically easily.

Let say I have a Wordpress custom post type using a block template, locked or unlocked. I want to repeat the content from a specific block somewhere else in my Wordpress custom post type page, outside the architecture of the content itself.

Right now, beside targeting the `blockName` ( core/paragraph, core/freeform ... ) and the iteration number, there is no real easy handy way to achieve that, and even that solution wouldn't be consistent.

This is where our unique identifier would come into play, and would let us use something along the line of the following script, on the front end, to target and display the block content:

```php
<?php
//...
foreach ( $blocks as $block ) {
	if ( $block['uniqueIdentifier'] == 'myIdentifier' ) {
		echo render_block( $block );
	};
}; ?>
```

**Comment by ntsekouras** [comment]
Would adding a specific `className` help?

**Comment by amarinediary** [comment]
Yes indeed. @ntsekouras 
Now the real question is how did I not see that... Anyway suggestion closed.
Thank you to both of you.
