### ISSUE TITLE
Plugin Menu Icons are not aligned to centre of parent box

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#29603]
## Description
Icons are not centre aligned in the plugin menu button area

## Step-by-step reproduction instructions
1. Edit a new post in the Block editor
2. Open browser Inspector
3. In Console paste in the example code below
4. Note the new menu at the top right with an envelope icon that is slight aligned to the left of the parent box
5. Note also that the 'Settings' seems correctly aligned

## Expected behaviour
Icon should be centrally aligned

## Actual behaviour
Item is aligned more to the left than the right

## Code snippet (optional)
```js
( function( plugins, element, i18n, editPost, components ) {
	var registerPlugin = plugins.registerPlugin,
		el = element.createElement,
		__ = i18n.__,
		Fragment = element.Fragment,
		PluginSidebar = editPost.PluginSidebar,
		PluginSidebarMoreMenuItem = editPost.PluginSidebarMoreMenuItem,
		PanelBody = components.PanelBody,
		PanelRow = components.PanelRow;

	var testsidebar = function() {
		return el(
			Fragment,
			{ key: 'test/test-sidebar' },
			el(
				PluginSidebarMoreMenuItem,
				{
					target: 'test-sidebar',
					icon: 'email'
				},
				__( 'Test Sidebar' )
			),
			el(
				PluginSidebar,
				{
					name: 'test-sidebar',
					title: __( 'Test Sidebar' ),
					icon: 'email'
				},
				el(
					PanelBody,
					{
						title: __( 'Filler Panel' ),
						initialOpen: true
					},
					el(
						PanelRow,
						{},
						el(
							'div',
							null,
							__( 'Filler text')
						)
					)
				)
			)
		);
	};

	registerPlugin(
		'icon-test',
		{
			render: testsidebar
		}
	);
} )(
	window.wp.plugins,
	window.wp.element,
	window.wp.i18n,
	window.wp.editPost,
	window.wp.components
);
```

## WordPress information
- WordPress version: 5.7-rc3
- Gutenberg version: Bundled and also plugin v10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOS 11.2.2
- Browser: Safari 14.0.3 and FireFox 86.0

**Comment by mattyrob** [comment]
The same issue happens with the sidebar tutorial code:
`( function( wp ) {
	var registerPlugin = wp.plugins.registerPlugin;
	var PluginSidebar = wp.editPost.PluginSidebar;
	var el = wp.element.createElement;

	registerPlugin( 'my-plugin-sidebar', {
		render: function() {
			return el( PluginSidebar,
				{
					name: 'my-plugin-sidebar',
					icon: 'admin-post',
					title: 'My plugin sidebar',
				},
				'Meta field'
			);
		},
	} );
} )( window.wp );`

<img width="419" alt="Screenshot 2021-03-07 at 08 57 20" src="https://user-images.githubusercontent.com/1280733/110234609-56191780-7f23-11eb-9f8d-4385549f8030.png">

**Comment by talldan** [comment]
Thanks for the awesome code snippet. I fixed the formatting (use three opening and closing backticks for multiline code blocks). 

I can confirm the issue:
<img width="380" alt="Screenshot 2021-03-08 at 1 50 08 pm" src="https://user-images.githubusercontent.com/677833/110280158-509bfa00-8015-11eb-9d74-2722ab846675.png">
