### ISSUE TITLE
Site Editor: Block toolbar overlaps browsing sidebar when screen's width is between 600px and 781px

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#29615]
Block toolbar overlaps the browsing sidebar when the screen's width is between 600px and 781px (tablet?)

![image](https://user-images.githubusercontent.com/2256104/110303560-cf376e00-7ffa-11eb-8e40-3727311055b4.png)

There is an empty white bar at the top when reaching 782px wide screen:

![image](https://user-images.githubusercontent.com/2256104/110303719-03129380-7ffb-11eb-8cf8-e04b11b20e13.png)

**Comment by vindl** [comment]
I think this is effectively the same as https://github.com/WordPress/gutenberg/issues/29392.

**Comment by creativecoder** [comment]
PR to address this: https://github.com/WordPress/gutenberg/pull/29918
