### ISSUE TITLE
Support for border properties 

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#29616]
Part of https://github.com/WordPress/gutenberg/issues/20331
Related https://github.com/WordPress/gutenberg/issues/21540

In https://github.com/WordPress/gutenberg/pull/25791 added support for border-radius at both globally (theme.json) & locally (block atts, both client & server), as well as UI controls. https://github.com/WordPress/gutenberg/pull/28049 added global support for border width, style, and color.

Tasks:

- [ ] Add UI for border width, style, and color. Pending decision from design https://github.com/WordPress/gutenberg/issues/27331#issuecomment-792618660
- [ ] Add support for block atts:
  - [ ] width
  - [ ] style
  - [ ] color

**Comment by aaronrobertshaw** [comment]
Some further background and discussion on support for border properties can be found in https://github.com/WordPress/gutenberg/issues/21540

**Comment by aaronrobertshaw** [comment]
PR: https://github.com/WordPress/gutenberg/pull/30124
