### ISSUE TITLE
TRY: hide inline formatting buttons when there is no selection

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2962]
To simplify the Gutenberg experience we could try hiding inline formatting buttons of bold, italic, strikethrough and link until there is a selection.

Quick mock-up:
![image](https://user-images.githubusercontent.com/2160304/31405317-852c3844-adb3-11e7-816f-80e1d63ac84b.png)

This is a suggestion to try in a branch. It would probably need some basic user testing to see the gain of a simpler UX is worth the harder feature discovery.

**Comment by karmatosed** [comment]
I will admit, I have concerns about this jarring the users. Do you have evidence this would be better for users?

**Comment by jasmussen** [comment]
Thank you for the mockup! Love that we're all rallying around simplifying the silhuette.

However I have to agree with Tammie, if we do this, we might as well go all-in and go with a popup toolbar to hold it all, and _drastically_ reduce the silhuette. While that is also an option, the problems with both this mockup, and the popup toolbar are the same — they are arguably less discoverable, you can't press bold with a mouse and then start typing, and the toolbar itself covers content above it. Admittedly that last part is also a problem with the current implementation of docking the toolbar to the block.

I think the next thing to try could possibly be https://github.com/WordPress/gutenberg/pull/2148.

**Comment by mtias** [comment]
We have made some changes so that toolbars don't show until you do text selection or disengage writing mode which I think solve the main issues.
