### ISSUE TITLE
Multi entity save panel - dynamic copy translation issues.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29635]
### Problem

In the Multi-entity save panel, there is a dynamic copy that adapts based on which items types (and how many) have been edited:

![Screen Shot 2021-03-08 at 10 38 42 AM](https://user-images.githubusercontent.com/28742426/110356326-1f68fd00-8008-11eb-80c1-69a54cf79e06.png)

this copy will adapt to different variations of the form: "Changes have been made to your " +:
"template part."
"template parts."
"site and template part."
"site and template parts."
"site, template, and template part."
"site, templates, and template parts."
etc. etc. putting in single or plural values in that sentence based on what was set to be saved.

This was set up with a translation paradigm that will not work for all languages (more info in slack convo https://wordpress.slack.com/archives/C02QB2JS7/p1614943169163900).  For this to work for all languages, we would need a static translation for every possible variation (and corresponding logic for every variation).  Given a lot of possible variations, this seems like it would get a bit messy.

### Proposed Solution

We should replace the dynamic copy with a static copy, along the lines of "The following changes have been made:".

Historically, we wanted a dynamic copy because items in this panel were hidden behind an interior toggle.  All the user would be able to see without triggering the toggle would be the dynamic sentance telling them the type of item(s) that have been edited.  Now that there is no toggle and all items are visible in the save flow, there is no reason for this copy to be dynamic anymore anyways.

cc @tobifjellner @youknowriad @jameskoster

**Comment by jameskoster** [comment]
The proposed solution seems fair to me. I wonder if we could make the label language a little more pro-active:

<img width="357" alt="Screenshot 2021-03-08 at 17 51 23" src="https://user-images.githubusercontent.com/846565/110360704-f7dd5900-8036-11eb-976a-4ab27c1feb8b.png">

**Comment by Addison-Stavlo** [comment]
> I wonder if we could make the label language a little more pro-active:

We definitely could update it that way.  I wonder if the phrase should be more of a prompt to review/select.
 some other possibilities (including yours first):

<hr/>

**Save the following changes:**

<hr/>

**Select the following changes to save:**

<hr/>

**Are you ready to save?**

Review and select the following changes to save:

<hr/>

**Are you ready to save?**

The following changes have been made:

<hr/>

I am a fan of the third option, but am happy to go with whatever you think makes the most sense.

**Comment by tobifjellner** [comment]
If the user can tick/untick various parts, then the third option really sounds good.

**Comment by clucasrowlands** [comment]
Editorial here! I agree that the third option works nicely. You could also trim the second line a bit (but it's not necessary):

> **Are you ready to save?**
>  Review and select the changes to save:

> **Are you ready to save?**
> Select the changes to save:

And a different option if you want just one line:

> Which changes would you like to save?

**Comment by kellychoffman** [comment]
I think it's important to communicate that some of the changes will effect other areas of the site. Having trouble eloquently relying that info. A stab: 

> Are you ready to save?
> Review and select the changes to save, some of which effect other areas of your site.

I think Jay is right in that we should also (separately, to not hold this up) look at improving the list below in terms of content and organization. This could be an additional way to help users understand that this is a list of changes made to this page/post as well as changes that effect other areas. We could also use this to better communicate the relationships between the concepts/terms we'd like people to understand in an eaiser-to-consume way: pages+posts vs. templates, templates vs. template parts, etc. 

**This page/post**
Changes that only effect this page/post.
- [ ] This page stuff
- [ ] This post stuff

**Templates**
Changes that will also effect other pages and posts.
- [ ] Pizza planet template
- [ ] Pizza planet: Header
- [ ] Pizza planet: Footer

**Comment by clucasrowlands** [comment]
If you go with Kelly's wording, change _effect_ to _affect_:

> Review and select the changes to save, some of which affect other areas of your site.

Another option to avoid the "some of which" phrasing:

> Select the changes to save. Some changes will affect other areas of your site.

**Comment by Addison-Stavlo** [comment]
Great input here, thanks all!

> Select the changes to save. Some changes will affect other areas of your site.

Im liking where this is going.  Id suggest with 'may' instead of 'will'.  I also have an urge to add "the following" in there, but can't really think of a way to fit it in that doesn't feel clunky:

> Select which of the following changes to save.  Some changes may affect other areas of your site.

</hr>

> If you go with Kelly's wording, change effect to affect:

Im so bad at getting these right, even when I google them. 🙃

**Comment by clucasrowlands** [comment]
A few more options that may be less clunky:

> Select the following changes you want to save. Some changes may affect other areas of your site.

> Select the changes you want to save. Some changes may affect other areas of your site.

**Comment by Addison-Stavlo** [comment]
> Select the following changes you want to save. Some changes may affect other areas of your site.

Sounds pretty good to me, tried it out on the PR here (https://github.com/WordPress/gutenberg/pull/29637):

![Screen Shot 2021-03-09 at 1 41 30 PM](https://user-images.githubusercontent.com/28742426/110521059-4ba27d80-80dd-11eb-9168-5a80c6d0cdd5.png)

**Comment by jameskoster** [comment]
Could we omit the "Are you ready to save?" line?

> **Select the changes you want to save**
> Some changes may affect other areas of your site

**Comment by jameskoster** [comment]
Eek that text is looking a little funky visually. Removing the "following" helps I think:

<img width="295" alt="Screenshot 2021-03-09 at 19 14 25" src="https://user-images.githubusercontent.com/846565/110524881-dbf7b700-810b-11eb-9337-955cc5f8815b.png">

Agreed on the colon – this feels like a heading to me.

**Comment by Addison-Stavlo** [comment]
Yeah i think that looks much better too!

**Comment by Addison-Stavlo** [comment]
> Eek that text is looking a little funky visually. Removing the "following" helps I think:

While it does look better (and I updated the PR to do this suggestion currently), it wont save it from looking 'funky' in other translations if we are referring to wrapping onto the next line.

**Comment by Addison-Stavlo** [comment]
closed with https://github.com/WordPress/gutenberg/pull/29637
