### ISSUE TITLE
Only show block borders and controls on focus

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2963]
Currently, there is quite a lot of editor chrome shown on hover.

It would be worth having a branch to experiment that only shows the block borders, block mover and block settings ellipses on focus.

This would take one extra click to start moving a block or accessing the settings, but these seem to be less common activities. An extra click might make it worth the decrease in distraction. It would be worth testing in UX tests.

**Comment by mtias** [comment]
This is done with the latest design tweaks.
