### ISSUE TITLE
FSE: Unable to select Keyboard Shortcuts from Options 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29640]
## Description

The Keyboard Shortcuts cannot be selected from the menu which blocks the ability to see what shortcuts work with the site editing experience. This was found as part of the [second call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1398). 

This is likely related to this issue: https://github.com/WordPress/gutenberg/issues/29049

## Step-by-step reproduction instructions
1. Go to the Site Editor experience
2. Click on Options > Keyboard Shortcuts
3. Notice the block manager doesn't open

## Expected behaviour

I expect to be able to view the Keyboard Shortcuts

## Actual behaviour

I'm unable to navigate to that menu item and see the keyboard shortcuts

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/110371812-b931a980-800a-11eb-829c-fdc0709d8c29.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by mtias** [comment]
It's tracked as unfinished in #21245

**Comment by annezazu** [comment]
Ah ha. Thank you. My searching didn't pull that up. Should this be kept open in that case?

**Comment by mtias** [comment]
I think we can close this one and ensure the other one doesn't fall through the cracks!
