### ISSUE TITLE
⌘+ENTER to create a separator

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2964]
⌘+ENTER (and whatever the equivalent is on Windows) is a handy shortcut key to create a separator and an easy win.

**Comment by prototypo** [comment]
foo

**Comment by EphoxJames** [comment]
Maybe Ctrl+Enter for Windows?

**Comment by mtias** [comment]
Related #71.

**Comment by jeffpaul** [comment]
Per today's Gutenberg bug scrub, we're going to close this and add it to the listing on #71.
