### ISSUE TITLE
Mobile App: Issues reported in the development environment

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#29653]
## Description 

I run the command:

```bash
npm run native start:reset
```

I saw the following issues reported:

```
Setting RN platform to: default (android)
● Validation Warning:

  Unknown option "haste.providesModuleNodeModules" with value ["react-native", "react-native-svg"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "haste.providesModuleNodeModules" with value ["react-native", "react-native-svg"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

```
> @wordpress/react-native-editor@1.47.0 clean:watchman /Users/gziolo/Projects/gutenberg/packages/react-native-editor
> command -v watchman >/dev/null 2>&1 && watchman watch-del-all; true

dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/watchman/4.9.0_2/libexec/bin/watchman
  Reason: image not found
sh: line 1: 96132 Abort trap: 6           watchman watch-del-all
```
## Device information
- Operating system: macOS Big Sur 11.2.2

**Comment by hypest** [comment]
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
>  Referenced from: /usr/local/Cellar/watchman/4.9.0_2/libexec/bin/watchman

Hmm, I wonder if [this approach](https://stackoverflow.com/a/66399852) will help there Greg.

**Comment by gziolo** [comment]
> > dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
> > Referenced from: /usr/local/Cellar/watchman/4.9.0_2/libexec/bin/watchman
> 
> Hmm, I wonder if [this approach](https://stackoverflow.com/a/66399852) will help there Greg.

I have sorted it all out with a series of brew updates. Thank you @hypest 🙇🏻
