### ISSUE TITLE
Mobile App: Fix warning reported in the terminal when running the test app

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#29655]
## Description

There are several warnings reported in the terminal when testing Gutenberg on the mobile app. When I run:

```bash
npm run native start:reset
```

I see the following warnings (some were printed multiple times):

```
 WARN  [MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 151 currentModeChanged listeners added. Use emitter.setMaxListeners() to increase limit]
 WARN  Removing lineHeight style as it's not supported by native AztecView
 WARN  Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/
 WARN  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.
```

There is also a minor issue with the content used that has a deprecated version of the cover block:

```
 INFO  Block successfully updated for `%s` (%o).

New content generated by `save` function:

%s

Content retrieved from post body:

%s core/cover {"apiVersion": 2, "attributes": ...
```

It might be also useful to improve the message printed as for some reason it doesn't print the HTML of the block.

## Device information
- Device: "iPhone 11" (simulator)
- Operating system: macOS Big Sur 11.2.2

**Comment by hypest** [comment]
> WARN  Removing lineHeight style as it's not supported by native AztecView

Some context on that particular one, we introduced it [in this PR](https://github.com/WordPress/gutenberg/pull/23507), as a reminder that the feature is not supported in AztecAndroid.

**Comment by gziolo** [comment]
#31936 temporarily removes the `data-no-store-string-literal` check for React Native files. It should be enabled again once this issue gets resolved.

**Comment by gziolo** [comment]
There is nobody actively working on it so let’s close it as non-applicable anymore.
