### ISSUE TITLE
Unwanted placeholder text overlays content

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2965]
## Steps to Reproduce (for bugs)

1. use the inserter to insert a block (e.g. separator or image)
2. press enter to create a new paragraph after the block
3. type "test"
4. press enter to create another new paragraph
5. "New Paragraph" placeholder shows up behind the word "test"

![image](https://user-images.githubusercontent.com/2160304/31406889-d3d68324-adb7-11e7-9603-9125c9041cf9.png)

Tested on Chrome 61 on Mac. Replicated on MASTER.

## Expected Behavior
The placeholder should never appear on a block that has content in it.

**Comment by mtias** [comment]
This should be fixed now.
