### ISSUE TITLE
Include sourcemaps in packages published to npm

### ISSUE THREAD

**Issue by jsnajdr** [WordPress/gutenberg#29658]
When using e.g. the `@wordpress/warning` package in my app, I see the following warning in my console in dev mode:

<img width="874" alt="Screenshot 2021-03-09 at 9 49 18" src="https://user-images.githubusercontent.com/664258/110443926-c018f480-80bc-11eb-9c0d-34aeee77cc22.png">

That's because the published JS file contains a sourcemap declaring comment:
```
//# sourceMappingURL=index.js.map
```
But the `index.js.map` file is nowhere to be found.

Could we generate the sourcemaps during build and include them in the npm package?

There is a somewhat related issue in #15732 that requests sourcemaps to be part of the published WordPress plugin.

**Comment by noahtallen** [comment]
Related: #15732

**Comment by noahtallen** [comment]
I just examined the download of `@wordpress/warning`, and `index.js.map` now exists there. Not sure when it was added though!
