### ISSUE TITLE
RangeControl is too wide

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#29665]
## Actual behaviour
With the latest WordPress RC3 the RangeControl is too wide and creates a horizontal scrollbar when `withInputField` prop is `false`.

I'm rendering it inside BaseControl:

```js
return (
	<wp.components.BaseControl
		label={label}
		help={help}
	>
		<wp.components.RangeControl
			withInputField={false}
			showTooltip={false}
			help={SIZE_NAMES[value]}
			value={sizes.indexOf(value)}
			onChange={onSizeChange}
			min={0}
			max={sizes.length - 1}
		/>
	</wp.components.BaseControl>
);
```

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/6892634/110452499-e98e4c00-80cd-11eb-9994-3ac69423aec2.png)

## WordPress information
- WordPress version: 5.7-RC3
- Gutenberg version: No
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 88

**Comment by talldan** [comment]
@ktmn RangeControl already has its own BaseControl, so you shouldn't render it in another one:
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/range-control/index.js#L194

The components that have the suffix Control should all be like this.

**Comment by ktmn** [comment]
No difference if I unwrap it.

**Comment by talldan** [comment]
I couldn't reproduce an issue, this is what I see when testing (I made the browser a bit shorter so that there's a vertical scrollbar):
<img width="311" alt="Screenshot 2021-03-15 at 12 26 30 pm" src="https://user-images.githubusercontent.com/677833/111103573-c2ca8c80-8589-11eb-985c-dae1c6f2f6f4.png">

**Comment by talldan** [comment]
@ktmn Are you able to look at the styles to see what's making it wider for you?

**Comment by ktmn** [comment]
> couldn't reproduce an issue

Same here :S

I don't know what the issue was, but 

```css
.components-range-control__slider {
  max-width: 100%;
}
```

fixed it. But now it's no longer needed either.
