### ISSUE TITLE
Fix broken links on developer.wordpress.org/block-editor

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#29662]
## Description
After merging the new table of content of the block editor developer handbook and changing the files/folders structure (https://github.com/WordPress/gutenberg/pull/28665), there are some broken links that were not caught during the process.

This issue track these links to fix them.

The list of the broken links can be found here https://docs.google.com/spreadsheets/d/11-AnXMjwjt7k2LGm2uLr-UlTemTxuCg_UUEb6lFsaXM/edit?usp=sharing. Anyone feel free to report if you spot one.

**Comment by JustinyAhin** [comment]
Cc @paaljoachim

**Comment by priethor** [comment]
I've added a couple of broken links I spotted to the doc. As the spreadsheet was empty, I took the freedom of adding some columns; please change them at your preference 🙂

**Comment by matmccabe** [comment]
I have also added a section on links which dont appear redirect. Please let me know if I was using them incorrectly, the feedback is much appreciated!

**Comment by skorasaurus** [comment]
Thanks for submitting these. These all appear to be functioning as intended. Please reopen if there are additional broken links or I misunderstood the issue.
