### ISSUE TITLE
Dashicon improperly aligned in ToolbarButton without label

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#29666]
## Description
Since 5.7-RC3 a dashicon in ToolbarButton without any label text has right margin. This wasn't the case before and is also different from how a svg icon works.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/6892634/110454947-894cd980-80d0-11eb-8b52-fb3d5bb67715.png)
![image](https://user-images.githubusercontent.com/6892634/110456540-5c99c180-80d2-11eb-887c-0123565fe7e6.png)

## Code snippet (optional)
```js
const CONTROLS = [
	{
		icon: 'editor-alignleft',
		title: __('Left aligned'),
		value: 'left',
	},
	{
		icon: 'editor-aligncenter',
		title: __('Center aligned'),
		value: 'center',
	},
	{
		icon: 'editor-alignright',
		title: __('Right aligned'),
		value: 'right',
	},
];
...
<wp.blockEditor.BlockControls>
	<wp.components.ToolbarGroup>
		{CONTROLS.map(control => {
			const {value} = control;
			const isActive = (textAlign === value);
			return (
				<wp.components.ToolbarButton
					{...control}
					isActive={isActive}
					onClick={() => setAttributes({textAlign: isActive ? undefined : value})}
				/>
			);
		})}
	</wp.components.ToolbarGroup>
</wp.blockEditor.BlockControls>
```

## WordPress information
- WordPress version: 5.7-RC3
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 88

**Comment by talldan** [comment]
Hi @ktmn, thanks for reporting this. I tested your code snippet using the latest Gutenberg `trunk` and this seems to have been fixed now:
<img width="318" alt="Screenshot 2021-07-20 at 1 14 09 pm" src="https://user-images.githubusercontent.com/677833/126265809-993c7cf8-9c45-47b5-846d-356e55e3b807.png">

Hopefully this fix will be in WordPress 5.8 as well, but I haven't been able to verify that, if you still experience it in 5.8 do let us know.
