### ISSUE TITLE
Full Site Editing: Template label in top bar is not correctly centrally aligned

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29673]
Due to `justify-content: space-between;` being applied to `.edit-site-header` and the difference in width between `.edit-site-header_start` and `.edit-site-header_end`, `.edit-site-header_center` is not correctly centrally aligned:

<img width="1641" alt="Screenshot 2021-03-09 at 13 21 41" src="https://user-images.githubusercontent.com/846565/110477163-be5e2980-80da-11eb-8833-2d460c54a2ce.png">

**Comment by TimBroddin** [comment]
I'll pick this one!

**Comment by bangank36** [comment]
I'll take over this issue

**Comment by jordesign** [comment]
Closing this issue as the design of the top toolbar has changed now.

**Comment by jameskoster** [comment]
It's still not centrally aligned though 🙈 

<img width="1076" alt="Screenshot 2023-09-08 at 10 22 09" src="https://github.com/WordPress/gutenberg/assets/846565/3aeccf8c-b4f0-4c7e-874f-f0fbc2b93e5b">

(Red line in the screenshot above is center).

**Comment by colorful-tones** [comment]
I just wanted to post verification, and it still needs to be centered.

![Screenshot 2023-11-20 at 12 07 36 PM](https://github.com/WordPress/gutenberg/assets/405912/3beaaefe-e65f-4fd5-89c9-c5743096c3e8)

**Comment by Sirjazzfeetz** [comment]
3rd year anniversary coming up... 

![Image](https://github.com/WordPress/gutenberg/assets/118427845/991c484a-9879-4914-ba88-d243e50f4f97)
