### ISSUE TITLE
Suggest, Block template, Switching ability in a locked template

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#29671]
## What problem does this address?
Currently when creating a **locked, block template**, you have to define specific blocks for the user to use.

There is no options to leave a free will block so that the user can choose what he would like in that instant. 

For example, In some situations you might want a List block or a Paragraph block, depending on the situation.

Even tho the Freeform block exist, the instability of it make it currently unusable. (For example, 2 or more Freeform distinct block in a row, will merge on save, modifying the block template).

## What is your proposed solution?
Giving a switch ability to blocks in a locked template, by introducing a new attribute called `switch`, where you could define an array of available blocks for the user to choose from.

```php
/...
'template' => array(
    array( 'core/image', array(
        'align' => 'left',
    ) ),
    array( 'core/heading', array(
        'placeholder' => 'Add Author...',
    ) ),
    array( 'core/paragraph', array(
        'switch' => array(
            'core/list',
            'core/table',
            /...
        ),
    ) ),
),
/...
```

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/8112. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
