### ISSUE TITLE
Background color behind multiple paragraph blocks.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2967]
Lets say that I have multiple lines of text. Using the paragraph text block it would then create multiple p tag blocks. Is there a way to select multiple blocks and then add a background behind all of them?

Right now it looks like this.

![screen shot 2017-10-10 at 22 08 44](https://user-images.githubusercontent.com/5323259/31408087-9bc5f6fe-ae07-11e7-914c-a3f41cb9207d.png)

Selecting multiple blocks adding a background color would make it look something like this.
![gutenberg-background-color-multi-blocks](https://user-images.githubusercontent.com/5323259/31408297-5284629a-ae08-11e7-91d6-c6ebfc9d920f.jpg)

**Comment by youknowriad** [comment]
Seems like a nesting issue (related #219). This is a use-case for a container block adding a background.

**Comment by mtias** [comment]
Yes, this is a nesting issue.
