### ISSUE TITLE
Safari: Site editor block outlines remain after block is deselected

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#29677]
## Description

In Safari, clicking around the site editor sometimes results in a buildup of gray block outlines. They appear when a block has been selected, and some of them don't seem to go away until the page is refreshed. 

I've only experienced this issue in Safari. 

## GIF

Note the buildup of gray block outlines in the Navigation block below:

![safari-clicks](https://user-images.githubusercontent.com/1202812/110491279-20a93100-80bf-11eb-8170-efb2b68339e6.gif)

## WordPress information
- WordPress 5.6.2
- Gutenberg 10.1.1

## Device information
- Device: Desktop
- Operating system: Mac OS 11.2.2
- Browser: Safari 14.0.3

**Comment by jasmussen** [comment]
I've seen this also. @ellatrix do you have any insights into what might cause this? I'm seeing also the sibling inserter sometimes lingering, though I don't know if that's related. 

I see this also in Chrome, by the way.

**Comment by ellatrix** [comment]
Should be fixed after #30995. Please reopen if that's not the case :)
