### ISSUE TITLE
Safari: Block toolbar doesn't always appear for the selected block

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#29678]
## Description

In Safari, selecting a block does not always result in the block's contextual toolbar being displayed. The block does receive the blue "selected" outline, but the toolbar does not appear. I notice this issue most frequently when working with nested blocks, though I'm not sure if it's restricted to that scenario. 

I've only experienced this issue in Safari.

## GIF

Note the missing toolbar after some of the clicks below: 

![safari-clicks-2](https://user-images.githubusercontent.com/1202812/110492113-e4c29b80-80bf-11eb-9c7b-6ab6acf95670.gif)

safari-clicks

## WordPress information

WordPress 5.6.2
Gutenberg 10.1.1
Device information

## Device Information

Device: Desktop
Operating system: Mac OS 11.2.2
Browser: Safari 14.0.3

**Comment by ellatrix** [comment]
Should be fixed after #30995. Please reopen if that's not the case :)
