### ISSUE TITLE
Post updated! View post blocks blocks Allow tracking button.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2968]
The Post updated! View post box blocks the Allow tracking button.

![screen shot 2017-10-10 at 22 16 13](https://user-images.githubusercontent.com/5323259/31408402-affe7f6e-ae08-11e7-9998-014b4d3e8610.png)

Local site with Desktop Server in Chrome.

**Comment by youknowriad** [comment]
>  Allow tracking button

Where do this tracking button come from? a plugin? I recall that we removed our tracking button.

**Comment by karmatosed** [comment]
I am closing this as doesn't seem an issue in the latest version with no plugins.
