### ISSUE TITLE
"Open in new tab" relationship values are overwritten when user first enters a different relationship value

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#29690]
While reviewing PR #29664 ; I encountered this but it also applicable in Gutenberg.

## Description
This is a bit of an edge case, but when a user first enters a [valid 'rel' value](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) in the "link rel" field (which is ambiguously named, visit [this issue](https://github.com/WordPress/gutenberg/issues/2020) for more information on the ambiguity; and then toggles, the value of the is overwritten. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. create new page
2. create a button 
3. enter a link
4. go to the advanced settings or the link settings of that block's sidebar, enter in a [valid 'rel' value](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel). I typed in `external` in my test cases.
5. go back to the button, enable the toggle for the "open in new tab" 
6. click publish

## Expected behaviour
rel value to the button's link to be `noreferrer noopener external`

## Actual behaviour
the rel's value of the button's link was 'rel="external noopener"

## Screenshots or screen recording

The screen recording shows the intended behavior if you 

https://user-images.githubusercontent.com/955351/110532635-18ff8180-80eb-11eb-8f4a-f1bb7f41f4e7.mp4

I've verified that this behavior occurs both when the user clicks the 'open in new tab' toggle in the sidebar or if they click the toggle in the link UI. 

The more important part is that the rel field in the sidebar has values entered in it BEFORE the toggle is clicked. 

I am NOT able to reproduce this if you **first** click the 'open in new tab' toggle and then add an additional rel value into the 'link rel' field (likely because 'external and noopener' are added first). 

## Also worth noting:
there is a PR to remove the `noreferrer` value - https://github.com/WordPress/gutenberg/pull/26968
so this issue may be moot; I haven't tried if you enter multiple ref value first.
There's an [issue to overhaul the entire link UI](https://github.com/WordPress/gutenberg/issues/24099)

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 10.1.1 
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? tested on twentytwenty and twentytwentyone. 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by Mamaduka** [comment]
Hi, @skorasaurus

I'm no longer able to reproduce this issue, at least with the button block.

**Comment by skorasaurus** [comment]
Thanks for checking; although I'm still able to reproduce it on gutenberg 13.3.0.

**Comment by Mamaduka** [comment]
@skorasaurus, sorry, I think I missed the step in testing. Now I'm also able to reproduce this.

**Comment by skorasaurus** [comment]
no longer able to reproduce this in gutenberg 17.7.0.

**Comment by Mamaduka** [comment]
Thanks for the follow-up, @skorasaurus!
