### ISSUE TITLE
Categories & Tags

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2969]
It looks like Categories are in place. Yayyy!

Why does Tags have a different approach?
It seems natural that this too would have a similar layout as Categories. Meaning an overview of all the available tags similar to available categories.

![screen shot 2017-10-10 at 22 24 10](https://user-images.githubusercontent.com/5323259/31408714-c79cb194-ae09-11e7-911a-c8607aa6fe1a.png)

Hmm. I am thinking the response would be. Lets get things in as similar as they are today and then later go back and adjust...

**Comment by youknowriad** [comment]
This is the same as the old editor, Categories are hierarchical and tags not, This makes adding new tags easier.

**Comment by paaljoachim** [comment]
I am just thinking a kind of simple clickable list of tags that show up below the tag box so see which tags are available. So one can click the various tags and have them added into the tag box.

**Comment by StaggerLeee** [comment]
Can you use ideas from block inserter and split categories "metabox" in 2 tabs. One for most used categories in this particular post type, and second tab for less used categories ?

This list tends to be very long vertically in some cases.

**Comment by karmatosed** [comment]
This is the same as the old editor so closing for now. We can look at iterations maybe in the future but it's right we have the same UI for now.
