### ISSUE TITLE
Provide a simple way to know that we're editing a reusable block

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#29694]
## What problem does this address?
At the moment there's not a simple way to know if I'm editing a reusable block. With the new version I don't need to click on "Convert to normal block" to start editing a reusable block. This can be confusing.

## What is your proposed solution?
I propose to provide a filter or pass a prop that clearly states that current block is reusable.

**Comment by mtias** [comment]
This is being tracked in a few items here #27890.
