### ISSUE TITLE
Stabilizing the gradient picker!

### ISSUE THREAD

**Issue by mdmag** [WordPress/gutenberg#29697]
The gradient picker component has been experimental for more than 1 year!
There is no development here done from 11 months: 
https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/gradient-picker
Is there any reason why this component is still experimental ?!

**Comment by annezazu** [comment]
@brentswisher seems like you were the last person who committed about this here! Might you be able to chime in?

**Comment by brentswisher** [comment]
Ah, I was just adding the storybook integration so I am not sure about the experimental status of the component itself. Personally, I don't see any reason why it needs to be, but @ellatrix or @jorgefilipecosta would probably know more.

**Comment by tellthemachines** [comment]
Gradient picker is stable as of #31440, so I'm going ahead and closing this issue.
