### ISSUE TITLE
Hire a UI/UX expert

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#29709]
Hello,

I really love Gutenberg and the ideas behind. But please hire some expert for UI/UX.

- The inconsistent UI (3 different block inserters??) and the ever-changing behavior with every WP release is really annoying.
- (opinion: icons that look like the Comic Sans of icons…)

Feels like the team working on Gutenberg is still trying things out with every release and changing too much...
But as of now, there probably should just be a "fixed" UI pattern, which only slightly changes or improve with every release. 

(Opinion 2: beside the fantastic things about Gutenberg, I think this is the major issue people have, Gutenberg stills feels like a beta instead of a final product, which is just improving and gets better)

Thanks,

Adrian

**Comment by mtias** [comment]
I respectfully disagree! There are several UI/UX experts already involved with the project. I'd suggest reading the following issues and engaging in the design conversations there to contribute other ideas and perspectives:

- Advancing the Block Interface #18667
- Regarding the block inserter (closed, but provides good background). #21080
- About the new icons. #20284

WordPress is indeed not a final product. It gets better through the efforts of all, so thanks for participating on the conversation.

**Comment by scrobbleme** [comment]
Thanks for your reply, my report was provocative by intention, not meant to be offensive ;)

I'm working with Gutenberg everyday, migrating all the "old" sites build with page builder XY to Gutenberg, really like it, so I'am more a Gutenberg advocate...
It is just annyoing/frustrating with every release to have some small thing "fundamentally" changed... again. This time, the reuseable blocks... whats next? It would just be nice to have some time to learn and stick to a pattern... 

I didn'nt wanted to say the product should be final, what I really meant is, that the shipped product (Gutenberg) should be somehow solid from a users point of view. (I'm not sure how to say this in English).

From an end users perspective it is the "final" product, with every WordPress release. But it also is a final product, which just changes tooo many things with every WordPress release. With every release something just feels, looks and behaves different and that every ~3 months... this is not how a "productive" product should work.

I just thing the basic patterns how the editor behaves and works should be more or less final - after ~2 years in production. Its not about new features.

**Comment by mtias** [comment]
No offense at all :) I appreciate the candor and very much sympathize with the feedback. I hope we get into a tune of refining well established patterns rather than changing them. Reusable blocks are good example, there are a lot of tweaks that are aimed at improving the clarity and resiliency of working with them: #27890. It's still not quite done, though.

The nature of rolling out things incrementally makes it so that sometimes it's not the final vision the one shipping. (There are a few pending improvements on reusable blocks that I really think should happen. Would be curious to hear your thoughts on them.)
