### ISSUE TITLE
Cover media?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2970]
Cover image. Is it possible to instead of image having a video from the media library or from youtube?

At the same time. What about clicking the image brings up the media browser? To quickly change the image.

**Comment by youknowriad** [comment]
Part of this issue is a duplicate of #2007

**Comment by paaljoachim** [comment]
Thanks Riad!

**Comment by karmatosed** [comment]
We have a cover video block already being offered. I do not think in this case adding to the cover image block makes sense.
