### ISSUE TITLE
Problem with images and text besides it. (Enters dissapear)

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#29708]
## Description
The enters go missing when you update a post when you use the classic block. Especially, when the text is next to an image. 

## Step-by-step reproduction instructions
Perfect example: https://arpegi.wordpress.com/2021/02/27/review-pokemon-pinball-gameboy/ 
When I editted this through the block editor / Gutenberg, all the enters I placed to only have text next to the image in a classic block, the enters went poof as soon as I clicked the publish or update button. When I used the classic editor, this behaviour didn't occur. 

The issue occured when using the phone and the desktop version. 

## Expected behaviour
Just like the classic editor, classic blocks should keep the lay-out and especially the enters. 

## Actual behaviour
The enters where deleted and the images got next to each other and became a mess. An example (where thankfully it looks nice) can be seen here where the author talks about the different skins of the Pokémon Mini: https://arpegi.wordpress.com/2021/02/27/review-pokemon-pinball-mini-pokemon-mini/

## WordPress information
- WordPress version: WordPress.org site, on my hosted WordPress sites, I haven't encoutered a situation to see this bug.
- Gutenberg version: Latest at the time of writing.
- Are all plugins except Gutenberg deactivated? Yes, since I have a free WordPress.com account where I noticed this issue.
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Twenty Sixteen

## Device information
- Device: Phone = Asus Zenphone 7 + Desktop is selfbuilt. 
- Operating system: Android 11 // Windows 10 20H2
- Browser: Opera 74.0.3911.203 (Also tested it in the latest version of Firefox and Chrome, same result)

**Comment by youknowriad** [comment]
@jasmussen youu might know where this was discussed before.

**Comment by priethor** [comment]
Is #17366 the issue you are referring to, @youknowriad ?

**Comment by youknowriad** [comment]
That is definitely one related issue. Let's consolidate there for now. Thanks @priethor

**Comment by NekoJonez** [comment]
> That is definitely one related issue. Let's consolidate there for now. Thanks @priethor

I agree. While it's not 100% the same issue but it's highly related and I think the solutions provided in that ticket might avoid issues like I mentioned in this ticket. 
Thanks for the help @priethor  and @youknowriad ... Crossing my fingers a nice fix/update can come from the other ticket. :)
