### ISSUE TITLE
List View: Allow drag and drop to reorder items

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29727]
## What problem does this address?
We have numerous tools to reorder blocks. The List View provides a glancable tool of your site structure, and is used in a few places, it's in the post editor, it's in the post editor, it works as a persistent sidebar in the site editor, and it exists as a tool for the navigation block. 

We could offer an additional drag and drop affordance in this tool, which might be useful for very long posts, or for the navigation which might feature complex nesting in menus.

## What is your proposed solution?

**Note:** This change should apply to anywhere we use the List View component. Here shown for the Navigation block:

<img width="1440" alt="list view" src="https://user-images.githubusercontent.com/1204802/110657255-f6d83300-81c0-11eb-9d45-50aad95a20fb.png">

Make the entire list view item draggable:

<img width="1440" alt="list view hover" src="https://user-images.githubusercontent.com/1204802/110657281-fe97d780-81c0-11eb-8cad-e809b7a9de60.png">

You'd still be able to focus the item itself, or the ellipsis, individually:

<img width="1289" alt="focus" src="https://user-images.githubusercontent.com/1204802/110657287-022b5e80-81c1-11eb-8c1c-fc82f0ad6033.png">

The ellipsis menu contains a "Move to..." item that duplicates the move action.

**Comment by talldan** [comment]
Yep, as mentioned drag and drop should hopefully still be working, it needs to be enabled. 

One thing that was hard to achieve in #23952 was the drop indicator styling. I think that may have regressed as well with styling changes to List View. It should show a blue line that's as wide as the item when dropping as a sibling, and a slightly indented line when dropping as a child (handled by dragging on the right side of the item).

And I never quite came up with a way to un-nest items through drag and drop. That could still be worked on.

Finally, I think it may also need some optimisation. 😄

**Comment by jasmussen** [comment]
What will it take to enable drag and drop for all instances of the list-view?

**Comment by priethor** [comment]
Right now the drag and drop is behind a [`__experimentalFeatures flag`](https://github.com/WordPress/gutenberg/blob/5d99e6ce5a334987dbf4f0117333781ee1956656/packages/block-editor/src/components/block-navigation/context.js#L7) in the `BlockNavigation` component. However, other instances might add their own experimental flag to control it, as the Persistent List View does in #29729

**Comment by jameskoster** [comment]
I've been exploring this a bit in [figma](https://www.figma.com/file/VaNb38S2OOihqSu2lAIIhN/List-view-Drag-and-drop?node-id=603%3A3798). Here are the various flows I worked on so far:

1. Arranging blocks at the same level
2. Dragging a block down a level in the tree (IE from the root level in to a group), accounting for when the target container is either open or closed
3. Dragging a block up a level, IE from a group to the root level of the doc.
4. Dragging a block to an incompatible area of the document, IE dragging a Column block to the root level

The second one feels most complex, so I put a prototype together to demonstrate how that could work:

https://user-images.githubusercontent.com/846565/120647790-e27b9d80-c472-11eb-8e6f-aa6f6709d61d.mp4
