### ISSUE TITLE
List View: Allow folding of nested items

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29726]
## What problem does this address?

The list view shows the structure of your content. It is present in a few places, it's in the post editor, it works as a persistent sidebar in the site editor, and it exists as a tool for the navigation block. 

To better handle nesting, nested blocks should be foldable, so you can collapse deep nesting trees.

## What is your proposed solution?

Add a small chevron to the left of blocks that feature nesting:

<img width="465" alt="Screenshot 2021-03-10 at 15 56 02" src="https://user-images.githubusercontent.com/1204802/110648693-39960d00-81b9-11eb-9b1f-b7f7cd129aaf.png">

**Note:** This change should apply to anywhere we use the List View component.

**Comment by priethor** [comment]
This issue is very closely related to #26141, it might be worth combining them into one.

**Comment by jasmussen** [comment]
Very good point. I'd be happy to integrate the contents of this one in #26141?

**Comment by jasmussen** [comment]
Closing in favor of #26141.
