### ISSUE TITLE
Persistent List View: Enable Drag and Drop

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29729]
_This issue is about the Persistent List View experiment (#28637), currently only available in the Site Editor._

The `BlockNavigation` component which powers the List View has some experimental features, namely the drag and drop reordering of the list items and corresponding blocks, which are currently disabled by default, and are controlled by a `__experimentalFeatures` flag.

There are a number of issues open on this feature, e.g. https://github.com/WordPress/gutenberg/issues/25067, https://github.com/WordPress/gutenberg/issues/29727.

Once the feature is consolidated and stable enough, we should enable it on the Persistent List View.

As a heads up: the Persistent List View introduces its own `__experimentalPersistentListViewFeatures`.
Let's be careful in the off chance there are overlaps or incompatibilities between the two experimental features sets.

**Comment by jasmussen** [comment]
@Copons the persistent list view is now available also in the post editor. Additionally, I see no reason we shouldn't also enable drag and drop in any other place where the list view is used, such as inside the Navigation block dialog:

<img width="562" alt="Screenshot 2021-05-21 at 08 25 22" src="https://user-images.githubusercontent.com/1204802/119092269-847c9e00-ba0e-11eb-99f6-3e8459dd5d03.png">

Would you mind if I change the title/edit the post to reflect that it's for all the instances of the list view?

**Comment by Copons** [comment]
@jasmussen feel free to do anything you want! 🙂

**Comment by jasmussen** [comment]
I'm going to close this one in favor of #29727. If that was in error, please do reopen.
