### ISSUE TITLE
Parser: Move support for the <!--more--> tag out of the parser

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#2973]
`<!--more-->` (and its cousin, `<!--noteaser-->`) are currently handled as special cases in the parser.

To keep the parser Gutenberg-focussed, these should be moved to the legacy paste handler, where they can be transformed into a `<!-- wp:more -->` block.

**Comment by mtias** [comment]
The noteaser can become an attribute of `wp:more`, which makes a lot more sense as well.

**Comment by mcsf** [comment]
Will open a PR tomorrow, but here’s a working branch:
https://github.com/WordPress/gutenberg/compare/remove/parser-more-and-noteaser-exception?expand=1
