### ISSUE TITLE
Improvements to List View

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#29733]
This issue aims to track the progress of improvements made to the List View feature towards advancing the [Navigation Block](https://github.com/WordPress/gutenberg/issues/27593) and the Site Editor's [Persistent List View](https://github.com/WordPress/gutenberg/issues/29736).

**High Priority**
- [x] #11711
- [ ] #29864

- [x] #25067
- [x] #29727
- [x] #29636
- [x] #26141
- [x] #24029 (partially covered, will need to be broken down further).

**Low Priority**
- [ ] #22287
- [ ] #16296
- [ ] #34690
- [ ] https://github.com/WordPress/gutenberg/issues/36583
- [x] #16307
- [x] #30109

**Comment by jasmussen** [comment]
On behalf of Kerry, I've checked the "Allow folding" task. Great work Kerry! 🎉

**Comment by mtias** [comment]
Closing this as there's not much left that is actionable right now.
