### ISSUE TITLE
While in a LOCKED block template, a Freeform block can be converted to a block, then disappear

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#29743]
## Description
While in a LOCKED block template, a Freeform block can be converted to a block, then disappear

## Step-by-step reproduction instructions
1. Register one or multiple Freeform block in a new or existing, default or custom, post type.
```php
//...
'template' => [
    [ 'core/freeform' ],
    [ 'core/freeform' ],
    [ 'core/freeform' ],
],
'template_lock' => 'all',
//...
```
2. Add a new post.
3. Click on a Freeform block
4. A task bar should pop out with a "Convert to blocks" button
5. Click on the "Convert to blocks" button
6. The Freeform block will disappear forcing the user to refresh the template or undo

## Expected behaviour
As we are in a locked template, the option "Convert to blocks"  for a Freeform block shouldn't even appear or do anything.

## Actual behaviour
Upon clicking the "Convert to blocks" button, the Freeform block vanishes, forcing the user to either refresh or undo. 

## Screenshots or screen recording (optional)
![kTqTddF6XG](https://user-images.githubusercontent.com/7512732/110714909-894df600-8204-11eb-9880-01bef8e4dd75.gif)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 9.3-9.9
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: MacBook Air (13-inch, 2017)
- Operating system: macOS Mojave
- Browser: Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by talldan** [comment]
Thanks for reporting.

Convert to blocks modifies the template (changes which blocks are in the template), which the template lock prohibits. When the templating system sees these blocks that aren't supposed to be there it removes them.

Perhaps the 'Convert to blocks' option shouldn't be visible when a template lock is active.
