### ISSUE TITLE
Rename "Insert" to "Add"

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2975]
In Gutenberg, every bit of content is inserted into the page or post using the same unified inserter interface. 

It's an important interface for users to learn. Is "Add" a simpler term to grok, than "Insert"?

Penny for your thoughts. And if there's agreement that "Add" is a better term, we also need to find a better name for the component we call "Inserter". "Adder", alas, doesn't work.

**Comment by folletto** [comment]
I originally went for insert as it's what Google Drive, Sketch, Keynote, Word, all do:

![screen shot 2017-10-11 at 10 29 47](https://user-images.githubusercontent.com/4389/31432708-25e6e3a4-ae6f-11e7-8039-21ccfe52a442.png)

![screen shot 2017-10-11 at 10 28 41](https://user-images.githubusercontent.com/4389/31432649-fa801640-ae6e-11e7-80ac-089c6721cb0a.png)

![screen shot 2017-10-11 at 10 29 07](https://user-images.githubusercontent.com/4389/31432674-0b5d205c-ae6f-11e7-9a26-d430c4435c6f.png)

![cap-word-animation-bar](https://user-images.githubusercontent.com/4389/31432637-f29dc04e-ae6e-11e7-8585-bf3f169c4b2f.gif)

So, "Insert" would keep consistency across platforms.

On the other hand, "Add" seems more straightforward.

**Comment by jasmussen** [comment]
As a point of note, although "Add" is shorter, this benefits only english speakers as in German we'd have to write "hinzufügen"

**Comment by megsfulton** [comment]
The reason why I originally brought this up was because it feels more natural to use the word "Add" to describe things in conversation or through writing (ex: support docs). In the case of the current editor "Add" is a better verb for the actions in the dropdown, but that may not be true of all the available actions for Gutenberg. 

>“I want to insert photos to my post” vs “I want to add photos to my post”
“To insert a simple payment button on your page” vs “To add a simple payment button to your page”
“To insert a contact form, press the ‘+ Insert’ button” vs “To add a contact form, press the ‘+ Add’ button”

Across most editing / content creation applications "Add" and "Insert" are used somewhat interchangeably. Professional tools tend to favor the word "Insert" while social apps favor the word add, perhaps because it's more approachable for a broader audience.

**Comment by folletto** [comment]
> Professional tools tend to favor the word "Insert" while social apps favor the word add, perhaps because it's more approachable for a broader audience.

This is a good way to frame this. :)

**Comment by karmatosed** [comment]
+1 to add, I feel it's more accessible to people and I agree with @megsfulton it does feel more natural.

**Comment by jasmussen** [comment]
Great conversation. It seems like there's, if not concensus, then at least a desire to try "Add". I can do a PR.

Two followup questions:

1. Should the component we call "Inserter" be renamed, or are we fine with keeping that label for now? I'm talking for design docs and UI vernacular.

2. Should we look at what "Add" translates to in other languages, compare it to how "Insert" translates?

**Comment by megsfulton** [comment]
>Should we look at what "Add" translates to in other languages, compare it to how "Insert" translates?

Yeah, seems like it can't hurt although I'd be more interested to know if the meaning holds up for native speakers when translated?

**Comment by hedgefield** [comment]
Great idea, `Add` feels better. I think we can keep the name Inserter, it still does what it says and no user will be confronted with the terminology if all goes well, right?

**Comment by mcsf** [comment]
Notwithstanding the merits of _add_, I'll point out the semantic nuance between _insert into_ and _add to_; the former is a more precise term, the latter is more ambivalent insofar as it can cover the meaning of _insert into_ but also of _appending_, _i.e._ adding to the end of a document.

IMO, in English the ambivalence of _add_ lies a bit in the eye of the beholder, but then again English has a long-standing culture of taking the pragmatic approach to UI language (and, in the analog world, all kinds of _signage_). However, we must consider i18n. This leads me to my point: 1) there might be a reason for the preference for _insert_ out there, and 2) I suspect that _insert_ translates better into all the languages out there (I can mostly speak for a few Romance languages, but I'm biased, and also _insert_ is a Latin word 😄).

**Comment by rileybrook** [comment]
@jasmussen this issue can be closed. I forgot to add "fixes #2975" to my original pull request.

**Comment by aduth** [comment]
Closed by #4393
