### ISSUE TITLE
Template parts created in the site editor have the wrong slug when exported

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#29763]
## Description

If I create a template part in the site editor and add a title to it,
the title is not used as a slug when the files are exported.

I am not sure if this is a bug or enhancement.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Enable a full site editing theme
2. Create a new template part in the site editor. Add a title to the template part.
3. (Make sure template part is saved)
4. Export the templates
5. View the file name in the folder, and in the code where the template part is included.

## Expected behaviour

I expect the slug and file name to be the title I selected.

## Actual behaviour

In my test, the title was "export-test" but the file name turned out to be "template-part-2.html"
In the code, the slug was template-part-2:
`<!-- wp:template-part {"slug":"template-part-2"} /-->`

## WordPress information
WordPress version: 5.7.
Gutenberg version: current trunk (5d99e6c)
Are all plugins except Gutenberg deactivated? yes
Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks.

## Device information
Device: Desktop
Operating system: Windows 10
Browser: Chrome Version 89.0.4389.82

**Comment by bobbingwide** [comment]
I found the fact that I couldn't name template parts very unsatisfactory. 
When I first exported my second FSE theme I had 11 template parts, 10 of which gave no indication of their purpose. 

I found it far easier to copy the HTML directly from the Template part Code editor, part by part, than to work with the extracted HTML files.  

I also note that the export doesn't (yet) include any changes to `experimental-theme.json`

**Comment by carolinan** [comment]
There is a separate issue for exporting global styles.

**Comment by carolinan** [comment]
I started looking at the code for the export but the problem is bigger than the export. 
When new template parts are created, the saved slug is `template-part-incremented-number`
https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/block-templates.php#L542

**Comment by carolinan** [comment]
Retested with WordPress 6.0, and the problem has been solved.
