### ISSUE TITLE
Page List inside Navigation block does not respect justification selection

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#29767]
## Description

When creating a menu with the Navigation block and the Page List block, the navigation alignment choice is not passed through to the Page List.

## Step-by-step reproduction instructions

Add a Navigation block.
Toggle the "Justification" icon, select a justification option e.g. 'Justify items right'
In the navigation block, add the Page List block to build a menu.

## Expected behaviour

The menu should respect the justification selection.

## Actual behaviour

The menu built from the Page List does not respect the justification of the parent Navigation block.

## Code snippet (optional)

With the extra UL of the page list, the justification is only applied to the first UL of the navigation block
```
<nav class="items-justified-right wp-block-navigation">
  <ul class="wp-block-navigation__container">
    <ul class="wp-block-page-list">
```
```
 .items-justified-right > ul {
    justify-content: flex-end;
}
```

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox & Chrome

**Comment by jasmussen** [comment]
Thanks for the report! I took a stab at this one in #29771.

Though, justifications left, center and right work fine for me. I just need to unselect the navigation block to see the change.

**Comment by Sandstromer** [comment]
Sorry, I should have clarified it is on the frontend that the justifications do not work.

In the editor, it looks okay:
![nav-block-editor](https://user-images.githubusercontent.com/76742815/110791593-4cb4e580-826a-11eb-84b1-4aa3bf0e40dd.png)

On the frontend, all navigation blocks with page list are displayed the same, regardless of the justification:
![nav-block-frontend](https://user-images.githubusercontent.com/76742815/110791720-753cdf80-826a-11eb-8973-96da37498f63.png)

**Comment by jasmussen** [comment]
Ah, that appears to be a TwentyTwentyOne bug. I am not seeing that in my own theme:

<img width="826" alt="Screenshot 2021-03-11 at 14 18 00" src="https://user-images.githubusercontent.com/1204802/110793195-a15d5e00-8274-11eb-95b3-b0ba12255343.png">

CC: @kjellr @scruffian any thoughts?

**Comment by Sandstromer** [comment]
@jasmussen I have now tested with other themes and it does appear to be an issue with TT1 so I'll close this.

**Comment by jasmussen** [comment]
I'm keeping my PR open as I think the space-between issue is worth looking at. Thanks again for the report!
