### ISSUE TITLE
Can't insert specific reusable block

### ISSUE THREAD

**Issue by rfischmann** [WordPress/gutenberg#29768]
## Description
I have a specific reusable block for related posts that I've created and have been using for a long time, but it stopped working on WordPress 5.7 + the current Gutenberg version.

## Step-by-step reproduction instructions
1. Create a reusable block.
2. Paste this code: https://gist.github.com/rfischmann/0dddb466bb9f1519ecbe4a654a17ba79
3. Try to insert the reusable block in any post.

## Expected behaviour
The reusable block should show up in the post.

## Actual behaviour
Freezes/crashes the browser, tried in both Edge and Safari for macOS.

**Comment by hellofromtonya** [comment]
**Test 1:**

Environment and Setup:
- Mac: OS Big Sur
- Browsers: Chrome, FIrefox, and Safari
- WordPress: 5.7
- Theme: Twenty Twenty-One theme
- Plugins: none

Results:
- Works as expected, i.e. did not freeze or crash the browsers.

See in action with Safari:

![gb29768-safari](https://user-images.githubusercontent.com/7284611/111004929-827fca00-834f-11eb-8378-d4a70fa4f184.gif)

**Test 2:**

Environment and Setup:
- Same as above installed and activated Gutenberg 10.1.1 plugin

Results:
- Works as expected, i.e. did not freeze or crash the browsers.

**Comment by hellofromtonya** [comment]
Welcome @rfischmann,

Thank you for the report and the reusable block code. Very helpful. 

Using the steps and code, I was unable to reproduce the problem. To investigate further, check your site set up to see if the problem persists when no plugins and a default theme is used (ie to check for any conflicts).

Does your site have any plugins (besides Gutenberg) activated? If yes, please deactivate all of the plugins and then try to insert the reusable block. What happens? Did it insert successfully? Or did it still freeze/crash the browser? 

If no, please switch to a default theme such as Twenty Twenty-One and then try to insert again. What happens?

**Comment by rfischmann** [comment]
Sorry for the delay, @hellofromtonya. You're right, I did test with the default theme before opening this issue, but I didn't consider the fact that one of my plugins could do that — and sure enough, it's from a plugin.

The developer is already working on a fix. Sorry for this.
