### ISSUE TITLE
Classic Text: Set keyboard focus on input upon inserting

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2977]
If you insert a text-related block, whether using the inserter or the slash command, focus is set on the input field so you can start typing. 

This is not the case with classic text.

GIF:

![focus](https://user-images.githubusercontent.com/1204802/31427872-1aab6560-ae69-11e7-8608-5b78c3384a4d.gif)

Can we set focus on the Classic Text input field upon inserting? Should work with both the inserter and the slash command.

**Comment by mtias** [comment]
This works for me.
