### ISSUE TITLE
A bug with drag n drop functionality

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#29777]
## Description
The new drag n drop functionality from the block inserter to the editor is great, but, we can also drop into the pattern's live preview currently. That is causing errors/issues. 

## Step-by-step reproduction instructions
1. Open block inserter window
2. Go to Patterns
3. drag a pattern and drop in another pattern's live preview instance.

## Expected behaviour
I suppose we should not be able to drop in the live preview instances at all.

## Actual behaviour
Currently, it is allowed that causes issues.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5817882/110794776-eba40680-8297-11eb-86d9-6b1ba814cf21.mp4

## WordPress information
- WordPress version: Latest 5.7
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty twenty-one

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by talldan** [comment]
Amazing bug 😄

**Comment by munirkamal** [comment]
> Amazing bug 😄

Yeah, I laughed hard when this happened. This could lead to a new feature maybe. 😀

**Comment by Quintis1212** [comment]
@talldan  Hi ) I made a PR for this bug , but there is no rewivers and comments in PR , can you help me ?

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce this issue.

https://user-images.githubusercontent.com/240569/162048934-35f90765-146c-426d-a77c-d0b1e6423d96.mp4

**Comment by adamwoodnz** [comment]
Closing following triage policy
