### ISSUE TITLE
theme.json spec: use block names for settings & block selectors for styles

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#29773]
The current [theme.json spec](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) allows theme authors to change settings & styles for specific blocks by addressing them by "block selectors" `core/paragraph`, `core/group`, etc.

Some blocks are special in that they represent different HTML markup. An example of this is the Heading block whose name is `core/heading`. In theme.json, it's addressed by block selectors that represent the different HTML markup combination the block can have: `core/heading/h1`, `core/heading/h2`, etc. Themes can't address `core/heading`, for example.

In practice, these block selectors have proven useful for styles. However, for settings, there has been no use in practice. Which holds the question: does it makes sense that themes can provide settings for different configurations of the same block (the same block with different block attributes)? For example, does it make sense that the heading block can have a different color palette depending on whether it's an H1, H2, etc? This is actually an issue: themes can't provide a specific color palette for the header block, they need to provide the same color palette for all configurations of the block (`core/heading/h1`, `core/heading/h2`, etc).

Given this rationale, it seems proper that we do the following:

- Use "block selectors" for blocks with multiple HTML elements: `core/paragraph`, `core/heading/h1`, `core/heading/h2`, etc. As it is currently.
- Use block names for settings: `core/paragraph`, `core/heading`. Change of behavior for two core blocks: heading & post title. It doesn't look like themes are targeting them on settings.

**Comment by carolinan** [comment]
Having to target each heading level individually does feel like it bloats the .json file.

I think the number of FSE themes is too low for us to know what theme authors will do 😄 So, I hope they reply.

**Comment by nosolosw** [comment]
I'm closing this as it is superseded by https://github.com/WordPress/gutenberg/issues/29891
