### ISSUE TITLE
Post Title Block: The outline doesn't have height and width

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29783]
Commonly, blocks have a `box-shadow` outline, located in their `::after` pseudo element, that shows up when they are hovered or selected.

The Post Title block has the outline as well, but instead of having the same width and height as its content, it's just 0x0.

<img width="272" alt="Screenshot 2021-03-11 at 14 55 03" src="https://user-images.githubusercontent.com/2070010/110806629-27c86e80-827a-11eb-8259-7101885ea242.png">
 
The outline can be seen by hovering over the block. It's the small dot in the top-left corner (which is the 1px outset box shadow).

<img width="385" alt="Screenshot 2021-03-11 at 14 52 48" src="https://user-images.githubusercontent.com/2070010/110806733-40d11f80-827a-11eb-9a68-47dbfd11ab0e.png">

**Comment by carolinan** [comment]
I not able to reproduce this using WordPress 6.0.1. The post title shows a box shadow with the correct size when the block is selected and you hover over the block toolbar, and also when you hover over the block in the list view.
It does not have a box shadow when the block itself is hovered over when it is not selected.
