### ISSUE TITLE
Dark mode - Styles are not updated after switching dark mode on/off (only on Android)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#29786]
## Description

After switching dark mode on, new blocks added have the styles of the light mode. The same happens the other way around, blocks have dark mode styles when switching dark mode off.

## Step-by-step reproduction instructions

1. Add some blocks.
2. Switch dark mode on.
3. Add more blocks.
4. Observe that the new blocks have light mode styles instead of dark mode.

## Expected behaviour

Blocks should use the specific styles according to the device's dark mode status.

## Actual behaviour

Blocks are not using the proper styles when dark mode is on/off.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/110788902-863c1f80-826f-11eb-852f-aab5fe7f1c26.mp4

## WordPress information
- WordPress version: 16.9
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? <N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 10
- WordPress app version: 16.9

**Comment by mchowning** [comment]
👋  @fluiddot ! Do you think https://github.com/wordpress-mobile/gutenberg-mobile/issues/2209 is the same as this issue, or are they a bit different in your opinion?

**Comment by fluiddot** [comment]
> 👋 @fluiddot ! Do you think [wordpress-mobile/gutenberg-mobile#2209](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2209) is the same as this issue, or are they a bit different in your opinion?

Yeah, I'm checking it and it looks like it's exactly the same issue. We can close this one in favour of [wordpress-mobile/gutenberg-mobile#2209](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2209).
