### ISSUE TITLE
Docs: Dead link to developer resources

### ISSUE THREAD

**Issue by lephleg** [WordPress/gutenberg#29795]
## Description
Reading more about the editor walked into a dead link in the main README.md file in the [Developing for Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/README.md#developing-for-gutenberg) section.

This most probably was missed from #29663.

## Step-by-step reproduction instructions
1. Open the repository page.
2. Scroll to the Developing for Gutenberg section.
3. Click on the Developer Documentation link.

## Expected behaviour
Most probably the link should forward the user to [Develop for the block editor](https://developer.wordpress.org/block-editor/#develop-for-the-block-editor) section of the guide, as it lists all the required resources described.

## Actual behaviour
A [404](https://developer.wordpress.org/block-editor/developers/) page.

**Comment by zackkrida** [comment]
I believe this can be safely closed as it was fixed via #29796.

**Comment by jasmussen** [comment]
Excellent! Thanks everyone.
