### ISSUE TITLE
While in a LOCKED template, a core/group block set to `'templateLock' => false` will lose priority, upon publishing

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#29799]
## Description
While in a LOCKED template, a core/group block set to `'templateLock' => false` will lose priority/reset to true, upon publishing preventing the user from modifying any child block under the core/group block.

## Step-by-step reproduction instructions
1. Define a `'template' => [ ... ]` on an existing or new post type, custom or not.
2. Locked out the template PRIOR to calling the `'template'`.
```php
//...
'template_lock' => 'all',
'template' => [ ... ]
//...
```
2. Add a core/group block to the template and set `'templateLock' => false`.
3. Add multiple core/paragraph blocks or else.
```php
//...
'template_lock' => 'all',
'template' => [
    [ 'core/group', [ 'templateLock' => false, 'className' => 'myCustomClass', ], [
        [ 'core/paragraph', ],
        [ 'core/paragraph', ],
        [ 'core/paragraph', ],
    ], ],
],
//...
```
4. From the admin panel, navigate to your post type and add a new post.
5. You should be able add blocks or switch existing core/paragraph blocks to any blocks. Add a title publish, leave and come back.
6. You won't be able to add a new block nor to switch to an existing one. A warning will be displayed that the template as change.

## Expected behaviour
Ideally, core/group blocks should have their own environment, and not be affected by the global template behaviour. The ability to insert or switch blocks within the core/group block should remain if set to `'templateLock' => false`. Behaviour within a core/group should only depend on the `'templateLock'` attribute.

## Actual behaviour
Upon publishing, the `'template_lock' => 'all'` takes priority over the core/block `'templateLock' => false`. You won't be able to add a new block nor to switch to an existing one. A warning will be displayed that the template as change.

## Screenshots or screen recording (optional)
![Vv3z9ZnFBF](https://user-images.githubusercontent.com/7512732/110843982-337f5980-82a9-11eb-96f2-02f585303cb6.gif)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 9.3-9.9
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: MacBook Air (13-inch, 2017)
- Operating system: macOS Mojave
- Browser: Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by amarinediary** [comment]
Additionally, if `'template_lock' => 'all',` is set AFTER `'template'`, the core/group `'templateLock' => false` attribute will just get ignored.

**Comment by talldan** [comment]
@amarinediary Ah, right, I think this is because `template_lock` in the group block needs to be a string:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/block.json#L11

Does it work if you use the value `'false'`?

**Comment by amarinediary** [comment]
@talldan With `'template_lock' => 'all'` and `'templateLock' => 'false'` the block is permanently locked. `'templateLock' => 'false'` is just getting ignored.

**Comment by talldan** [comment]
Ok, thanks for reporting, this seems like a bug then.
