### ISSUE TITLE
Navigation Editor: Navigation links added to menu only preserve url and label attributes

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#29793]
I'm not sure if this is intentional or not, but we only preserve the label and url attributes of a navigation link, when we save this in the navigation editor.

This means saving in the navigation editor is a bit lossy. For example, draft links will render on the frontend because id and type is not available to check. This may also be an issue for any future functionality that's added to navigation links.

Post links and other types of links added in customer or nav-menu also lose information when saved in the navigation editor and get turned into custom links.

#### Enabling the Navigation Editor

To enable the Navigation Editor:
- Install and activate the Gutenberg plugin
- Visit experiments /wp-admin/admin.php?page=gutenberg-experiments
- Check "Enable Navigation screen" and save
<img width="1083" alt="Screen Shot 2021-03-11 at 9 56 52 AM" src="https://user-images.githubusercontent.com/1270189/110832458-2d10c380-8250-11eb-9e36-308bb75aeb27.png">

### Post links from customizer/nav menu turning into custom links

https://user-images.githubusercontent.com/1270189/110835076-318aab80-8253-11eb-9aeb-22a4057bc42b.mp4

- Add a post link in customizer (/wp-admin/customize.php) or menu nav (/wp-admin/nav-menus.php) and save
- Load the menu in the Navigation Editor (/wp-admin/admin.php?page=gutenberg-navigation) and Save
- Load it again in customizer or menu nav

Expected: Menu contains a single post link
Actual: Menu contains a custom link

### Losing Properties When Loading a Menu into the Navigation Block

https://user-images.githubusercontent.com/1270189/110828911-6b0be880-824c-11eb-866b-53431a063559.mp4

As a quick example here's a navigation block loaded from a menu:
```
<!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Metal Cats","url":"http://wordpress.local/metal-cats/"} /-->
<!-- /wp:navigation -->
```

And here's one built in the post editor:
```
<!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Metal Cats","type":"post","id":43,"url":"http://wordpress.local/metal-cats/"} /-->
<!-- /wp:navigation -->
```

If I spotted this correctly serialization/hydration occurs in:

https://github.com/WordPress/gutenberg/blob/b7f341628facdc4b5c46aaf9c8745039dc6aa774/packages/edit-navigation/src/store/utils.js#L132-L147
https://github.com/WordPress/gutenberg/blob/b7f341628facdc4b5c46aaf9c8745039dc6aa774/packages/edit-navigation/src/store/resolvers.js#L146-L155
We might also need server changes if menu items cannot save arbitrary properties.

**Comment by getdave** [comment]
@gwwar This is related. I found the same issue.

https://github.com/WordPress/gutenberg/pull/30956

Perhaps we can try and persist the relevant fields from the block to those on the Nav Menu object.

https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L786

For example, `object` and `object_id` should be ideal for storing some of the data you refer to. Then when we hydrate the menu item back into a block form we can decide on the type of block based on the data we have available.

**Comment by getdave** [comment]
Just noticed that there is just a single `core/navigation-link` block and that has several variations. So that should make this easier 🤞

**Comment by getdave** [comment]
@gwwar I have [a PR up which I believe will address this](https://github.com/WordPress/gutenberg/pull/31004) but I'd be interested in your advice.

Essentially we have two places in code where we are creating `core/navigation-link` blocks from _menu objects_ stored in the database (as opposed to as serialized blocks as we do with standard blocks):

1. In the Navigation Editor:
https://github.com/WordPress/gutenberg/blob/b7f341628facdc4b5c46aaf9c8745039dc6aa774/packages/edit-navigation/src/store/resolvers.js#L146-L155

2: In the Navigation _Block_ itself:
https://github.com/WordPress/gutenberg/blob/14209355ea83567398bb30c35f9a0ec7f3b8da12/packages/block-library/src/navigation/placeholder.js#L40-L83

There is some lack of consistency between these approaches and we are also missing a number of opportunities to parse all the available data from the menu objects in the database when we convert to blocks. That is what you noticed in your Issue report.

[My PR addresses some of this](https://github.com/WordPress/gutenberg/pull/31004). But I wonder whether you think a good follow up might be to create a single source of truth for the act of parsing database menu objects into blocks? The current code is not DRY and has proven to be a maintenance issue - therefore I believe it is a good candidate for a refactor.
