### ISSUE TITLE
How to test it ?

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#298]
You dont make it easy for mass testing and reporting back about issues, feature, bugs.
I installed it as plugin and what next ?

Is there library dependencies involved ?

**Comment by jasmussen** [comment]
You caught us at an awkward time where we have just started work on the actual plugin, and are wrapping up the prototypes. The plugin isn't functional yet. 

You can test the prototypes here: https://wordpress.github.io/gutenberg/

Feel free to report in #core-editor on Slack, or as comments here in Github. 

Did that answer your question?

**Comment by StaggerLeee** [comment]
Thank you

I have been there. Got somehow impression all of you are using it as separate installation on your localhost:
https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+label%3ADesign

Will close it. Dont give up, it is so fine project. Maybe shortcodes in text will be soon matter of distant past.

**Comment by jasmussen** [comment]
> Will close it. Dont give up, it is so fine project. Maybe shortcodes in text will be soon matter of distant past.

Thank you for those words ❤️
