### ISSUE TITLE
Global colors

### ISSUE THREAD

**Issue by mayan62** [WordPress/gutenberg#29802]
Hello i am testing full site editing and trying to get used to it . I wonder how i can have the global colors also in the Gutenbergeditor When i set the global colors *tested several blockbased Themes in the root colors the look of the site changes but when i go to Gutenbergblocks default ones i have still all the default theme colors. When i try to change the global colors for the block the root colors witch back to the original theme colors. Without Full site i have on one page the Kadence theme nd there i can choose global colors and they show up everywhere. I wonder if this is a bug or a future request.... seems somehing with Gutenberg i have the newest version installed. Thanks a lot!

**Comment by simison** [comment]
cc @nosolosw

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; there's additional discussion on this in https://github.com/WordPress/gutenberg/issues/29818 where you can follow its progress.
