### ISSUE TITLE
FSE - edited global styles not available in post editor

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#29818]
## Description

With a FSE enabled theme, user edited global styles are not available in the post editor.

## Step-by-step reproduction instructions

1. Activate a FSE theme e.g. TT1Blocks
2. Go to the Site Editor
3. Select the Global Styles panel
4. Rename a color, or add a new color to the color palette
5. Click Update Design and then Save to update the global styles
6. Exit site editor, go to edit/add new post
7. Add any block with color controls
8. Change the color/background of the block and notice the renamed color and/or the new color are missing
9. Go back to Site Editor and notice how the edited global styles are present

## Expected behaviour

Edited global styles should be available in the post editor

## Actual behaviour

Edited global styles are not available in the post editor

## Screenshots or screen recording (optional)

**Site Editor** - rename 'Blue' color to 'New Name', and add a 'New Color'
![site-editor-color-rename-ok](https://user-images.githubusercontent.com/76742815/110930413-fd7dbc00-8320-11eb-86f3-2652df1adb01.png)
![site-editor-new-color-ok](https://user-images.githubusercontent.com/76742815/110930447-07072400-8321-11eb-84e5-4757c2826907.png)

**Post editor** - edited global styles are missing
![post-editor-color-rename-not-ok](https://user-images.githubusercontent.com/76742815/110930523-1e461180-8321-11eb-8509-4c5c390b7f7b.png)
![post-editor-new-color-not-ok](https://user-images.githubusercontent.com/76742815/110930543-23a35c00-8321-11eb-9904-306ea7d72585.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1Blocks

## Device information
- Device: Dekstop
- Operating system: Windows 10
- Browser: Chrome & Firefox

**Comment by Sandstromer** [comment]
Think it may be same as described in https://github.com/WordPress/gutenberg/issues/29802

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this on the latest version of Gutenberg, the custom colors I created in Site Editor `Red Test` + `Blue Test` are displayed in the editor. 

https://user-images.githubusercontent.com/41231764/183931429-6b16790c-e676-4dbc-97f7-a227ab24d9e9.mov

WordPress 6.0.1
Gutenberg 13.8.1 active

I'm going to close this issue
