### ISSUE TITLE
Confuisong block aligment selection

### ISSUE THREAD

**Issue by asafm7** [WordPress/gutenberg#29822]
I don't know if it is considered a bug but couldn't find a better category.

In some cases, the alignment selection for a block omits one of the possible options.

See this image:
![image](https://user-images.githubusercontent.com/14274769/110947204-c1a22100-8337-11eb-8679-6c0b558a7bfd.png)

Seemingly there are only 2 alignment types (two options in the dropdown, and two types of icons).

But clicking the selected Wide width option unselects it and reveals a third, unnamed, icon (the one in blue):
![image](https://user-images.githubusercontent.com/14274769/110947504-29f10280-8338-11eb-84b0-c822c59a293c.png)

I clicked the selected Wide width option by chance. I think clicking a selected option to unselect it isn't a typical dropdown 
behavior (and so, not intuitive).

Thought it might interest you.

**Comment by priethor** [comment]
Hi @asafm7, thanks for submitting this!

The third icon you mention is the "default alignment", and as such appears not only when you unselect the current alignment but also before selecting any alignment. For example, if you create a new "Group", you can see that same icon representing "alignments" in general, when no alignment has been selected.

**Comment by asafm7** [comment]
Thanks @priethor.

Yes, I figured it is some kind of a default option. Still, it is confusing I believe. What does "default alignment" mean? (or "no alignment"?) And why isn't it listed in the options to enable the user to easily go back to default?

The fact that the icons are very similar doesn't help here either (and so I didn't remember what was the icon when I first created the "Group").

Anyway, it confused me :)

**Comment by sabernhardt** [comment]
Themes can have a standard (or default or no-special) alignment for an element or block. If you want to change a Group block to wide or full alignment, then you select one of the options. Including a "Standard" option in the dropdown could help.

The alignment selection gets more confusing with media blocks, where the same icon is used for both the default state and Align center (no option is selected in the screenshot):

![image alignment options with none selected](https://user-images.githubusercontent.com/17100257/111197657-b98eef00-858c-11eb-9d17-08a728e1af75.png)

(Does the media block alignment icon belong in a separate issue, or should [Trac #52803](https://core.trac.wordpress.org/ticket/52803) point here?)

**Comment by talldan** [comment]
I believe this is resolved because there's now a 'None' option, and the options can't be deselected:
<img width="243" alt="Screenshot 2021-11-24 at 10 39 57 am" src="https://user-images.githubusercontent.com/677833/143161655-4941eedb-d197-4a10-bb79-384fb3da5a47.png">
