### ISSUE TITLE
Wordpress 5.7 - Reusable Block: Convert to Regular Block Missing

### ISSUE THREAD

**Issue by TheSimArchitect** [WordPress/gutenberg#29826]
## Description

Hi!

Since Wordpress 5.7 update I can't convert reusable blocks to normal blocks, so I can unlink them from their source and make changes as I used to before.

I see you mention on your "features updated" list that you changed / improved reusable blocks, but you don't go into details there and, as of right now, this essential feature is missing, since sometimes we want to paste a reusable block, then change its content for the specific place I pasted it, not for the rest of the website wherever that block is used (whenever I use it as a template, which is most of the time).

Please let me know how the result is achieved after the update or if the feature is missing. I just can't work with the editor without that feature and I will be forced to downgrade to Wordpress 5.6.x otherwise, since a considerable amount of my content is repetitive and I use those blocks as templates for segments of each post I publish (and I guess many other people must do the same)

## Step-by-step reproduction instructions

Hover or select a reusable block. No "Convert to regular block" option available, anywhere.

## Expected behaviour

To have "edit block / save block" and also "convert to regular block" instead. 

## Actual behaviour

No "convert to regular block" option available anywhere. I get you want to allow people to edit in line, no problem with that, but we must have a way to break the dynamic link of a reusable block that is there into a regular one, so w can customize its contents to the post we're editing without interfering with other copies of the block used elsewhere.

## Screenshots or screen recording (optional)

https://prnt.sc/10jqejc

## WordPress information
- WordPress version:  5.7
- Gutenberg version:  I don't know, the Site Health does not show that information.
- Are all plugins except Gutenberg deactivated?  No. The feature is not dependant on plugins and I don't use plugins that modify the editor.
- Are you using a default theme (e.g. Twenty Twenty-One)?  No, I use PErsonal Blogily.

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Chrome Dev 64

**Comment by Tropicalista** [comment]
You must click on the 2 squares icon. Hover on it to see the tooltip.

**Comment by TheSimArchitect** [comment]
> You must click on the 2 squares icon. Hover on it to see the tooltip.

Thank you so very much!!!! Sorry for my lack of competence.

I wish you have a great day! Stay safe and well!

**Comment by Tropicalista** [comment]
You're welcome.

However I think it should be made more visible. I had same problem and took me  time to understand where they put the button.

**Comment by TheSimArchitect** [comment]
> You're welcome.
> 
> However I think it should be made more visible. I had same problem and took me time to understand where they put the button.

You're absolutely right! Plus it's missing the save button, we can only save our modifications if we publish, just saving the preview does not update the blocks. It would be nice if they added a "save" button right besides that "copy" one, which converts the block into regular.

**Comment by Julianoe** [comment]
Is there an open issue about this interface problem? Displaying only the icon creates some troubles for users to identify what the button is made for. At least before the labelled button was clear about what it did. The choice of icon is very very confusing. It could totally be a button to duplicate the block. If the icon needs for people to be hovered every time to see what it does, then it does do a good job at conveying the information.

**Comment by Tropicalista** [comment]
@Julianoe I agree with you. There's a discussion on improve that interface here: https://github.com/WordPress/gutenberg/issues/29871#issuecomment-808010739

**Comment by TheSimArchitect** [comment]
I am also having issues to select the entire reusable block. It is VERY hard to do that, I need to keep trying and trying to avoid editing inside a reusable block when I want to move/remove/convert it entirely.

It would be nice it if were easier to select the entire thing easily like before.
