### ISSUE TITLE
Actions unavailable after selecting an image within a gallery block

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#29835]
## Description
In WordPress 5.7, it is impossible to select any editing options for a gallery image immediately after clicking the pencil icon in the top right of the image.

## Step-by-step reproduction instructions
1. Create a new post
2. Drag the Gallery pattern (two images side by side)
3. Select one of the images
4. Click the pencil in the top right of that image.
5. Try to click Upload, Media Library, or Insert from URL and notice they cannot be selected.

In order to select these options, you have to remove focus from the gallery block and then re-select the block.

## Expected behaviour
You should be able to click those items immediately after clicking the pencil icon on an image.

## Actual behaviour
You cannot click any of the options for editing a gallery image.

**Note:** This does not just happen when gallery blocks are inserted using the pattern, it also happens when using the block inserter. It also happens when following these steps to edit when an actual site specific image is in the gallery.

No console warnings were present.

## WordPress information
This seems to happen in:
- WordPress 5.7
- WordPress `trunk`
- Regardless of which theme is active
- With no plugins active.
- Having the Gutenberg plugin active does not solve the issue.

## Device information
- Device: Desktop
- Operating system: MacOS Catalina
- Browser: Firefox nightly

Discovered researching a separate issue [reported on Trac](https://core.trac.wordpress.org/ticket/52789) by @mikelittle.

**Comment by paaljoachim** [comment]
Thanks for creating the issue, Jonathan!

In WordPress 5.7.
No plugin active.
Twenty Twenty One.

Here is a visual of the above test.

https://user-images.githubusercontent.com/5323259/110997719-18cae480-837e-11eb-9513-845fc9b490b3.mp4

@aaronrobertshaw @jasmussen 

Issue came up in the Core Editor channel.
https://wordpress.slack.com/archives/C02QB2JS7/p1615573947128700
