### ISSUE TITLE
Add UI for setting ID (anchors) on list items (<li>)

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#29838]
## What problem does this address?

I often find myself needing to specify anchors on individual list items (`<li>`) but the list block does not support this, although it does allow specifying anchors on the list itself (`<ul>` or `<ol>`).  It would be *very* helpful if that were possible.

## What is your proposed solution?

I'm not sure what the backend JS would be, but from a UI perspective, when the cursor is within the text of a `<li>`, then the `HTML anchor` field in the `Advanced` panel should apply to the list item (instead of the list as a whole).

Of course, that may introduce some ambiguity about how to specify an anchor for the list as a whole, so I'm open to almost *any* UI that would allow me to specify anchors on list items.

**Comment by mtias** [comment]
The main change to unlock this would be to turn list items into child blocks.

**Comment by pbiron** [comment]
@mtias how much work would that be, and what are the BC implications?

**Comment by mtias** [comment]
It's not trivial, but we are getting there tool-wise. See #6394.

**Comment by adamwoodnz** [comment]
The http://w.org/about/security page has links in the content to footnotes which are in a list, using ids like `#footnote1` on the list items. As part of the redesign we are building this content in blocks. This is what it looks like:

![Screen Shot 2023-01-25 at 4 58 26 PM](https://user-images.githubusercontent.com/1017872/214476696-157a038f-8598-4b77-b664-79bf1f2867f2.jpg)

Unfortunately the best I can do is link to the list element at present. For now I have changed to a non-list solution with paragraph tags.

**Comment by pbiron** [comment]
> The main change to unlock this would be to turn list items into child blocks.

List items are now child blocks (or at least, they appear to be in the editor, not sure whether they truly are under the hood).  It's now possible to set a CSS class on list items.

@mtias are things now at the stage and anchors could be added to list items?
