### ISSUE TITLE
From WordPress 5.7, the cursor of the custom color picker cannot be moved.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#29848]
Thank you for your development.

## Description

1. Select "Text Color" from the toolbar when editing text.
2. Select "Custom Color".
3. Attempts to move the cursor in the color palette.
4. The cursor cannot be moved and the panel will be closed automatically.

## Screenshots

The following video shows the behavior in v.5.6.

<img src="https://user-images.githubusercontent.com/31400297/111018039-1c03b600-83fa-11eb-8b85-b823c61a1589.gif" width="600px">

And the following video shows the problematic behavior in v.5.7.

<img src="https://user-images.githubusercontent.com/31400297/111018075-43f31980-83fa-11eb-82c7-380fc328d426.gif" width="600px">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: "Not installed"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: MacBook Pro
- Operating system: MacOS Catalina
- Browser:Chrome

**Comment by paaljoachim** [comment]
Testing.

WordPress 5.7
No plugin activated.
Twenty Twenty One.

Testing instructions posted above.
1. Select "Text Color" from the toolbar when editing text.
2. Select "Custom Color".
3. Attempts to move the cursor in the color palette.
4. The cursor cannot be moved and the panel will be closed automatically.

-----------

Went to an existing page.
Wrote some text in a paragraph block.
Selected a word and then selected the inline color icon.
Selected custom color. 
Upon moving the cursor inside the color area the color selector screen is closed.
I am getting the same result as @ddryo showed in his post.

**Comment by Quintis1212** [comment]
I found the source of problem , when you comment fn( data, e ) in throttle function you can not close the color picker on mouse click : 
path - gutenberg/packages/components/src/color-picker/saturation.js
`
    		this.throttle = throttle( ( fn, data, e ) => {
			console.trace()

			//fn( data, e );
		}, 50 );
`

![Знімок екрана з 2021-03-17 22-19-19](https://user-images.githubusercontent.com/34488718/111532923-e00c8000-876e-11eb-9683-cbff8dd2e73b.png)

Who can explain , where is source code of fn function from throttle function ?

**Comment by Quintis1212** [comment]
It seems  bug is from  lodash functions :

`
        	commitValues( data ) {
		const { oldHue, onChangeComplete = noop } = this.props;
		console.log(partial)
		if ( isValidColor( data ) ) {
			const colors = colorToState( data, data.h || oldHue );
			this.setState(
				{
					...colors,
					draftHex: toLowerCase( colors.hex ),
					draftHsl: colors.hsl,
					draftRgb: colors.rgb,
				},
				debounce( partial( onChangeComplete, colors ), 100 )
			);
		}
	}

`
	debounce( partial( onChangeComplete, colors ), 100 ) - this is source of bug , I will try to fix this

**Comment by kwight** [comment]
This quick close of the color control also happens if trying to use the [slider at the bottom](https://github.com/Automattic/wp-calypso/issues/51768).

**Comment by kwight** [comment]
![2021-04-09 08 26 00](https://user-images.githubusercontent.com/349751/114204225-cbef1500-990d-11eb-94e2-4f4f25efbd09.gif)
