### ISSUE TITLE
Implement a way to wait until an action is dispatched to the store

### ISSUE THREAD

**Issue by aminta** [WordPress/gutenberg#29841]
## What problem does this address?

I'm building a Carousel Block in Gutenberg with `InnerBlocks`, each child it's a slide.

When I set to `true` the `preview` state in parent, the script that inits the Carousel is launched, otherwise I see the slide as simple `<div>`s, stacked one over the other.

I'm using `dispatch('core/blockEditor').updateBlockAttributes(childClientId, {preview: true)` to update the children of my parent component when I set to `true` the `preview` state in parent.

In this way, the children will have the markup my script needs for each slide.

But there is a problem: when the Carousel script starts, I'm not sure that all my children's markup are updated!

So, knowing that `dispatch('core/blockEditor').updateBlockAttributes` returns a Promise, I've tried with something like:

```
// async function

let promises = [];
// for
let promise = await updateBlockAttributes(childClientId, {preview: true))
promises.push(promise);
 } 
await Promise.all(promises).then{ allPromises => launchTheScriptThatInitsTheCarousel() }
// end for

```
but it doesn't work.

## What is your proposed solution?
Can you implement a hook / method to rely on so one developer can be sure that an action is dispatched and the store/dom are updated?

**Comment by talldan** [comment]
@aminta Is `preview` only used within the editor? If so, then I don't think using an attribute is the right approach. Attributes should primarily be used for data that the block's save function depends on.

For this, I think you could consider using React state for storing the preview value, and context for sharing the value with child blocks.
