### ISSUE TITLE
Improve the block settings menu, give it a background

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2984]
The ellipsis menu introduced in 1.4 to hold the trash and configure settings is a bit flimsy on the side. We can improve this by making it an actual popout menu. Currently:

<img width="170" alt="screen shot 2017-10-11 at 13 04 10" src="https://user-images.githubusercontent.com/1204802/31437311-1d57b4d2-ae85-11e7-9a2c-f5e2291ffb95.png">

Suggested design:

<img width="304" alt="screen shot 2017-10-11 at 13 07 01" src="https://user-images.githubusercontent.com/1204802/31437316-20f9ab54-ae85-11e7-99e2-de552b136341.png">

See also #2983. 

This would also be a good opportunity to show shortcut keys, see #2980.

**Comment by karmatosed** [comment]
I really like this! Let's get this into a PR so we can experience it. Great work.

**Comment by shaunsantacruz** [comment]
This would also fix #3000

**Comment by shaunsantacruz** [comment]
Another issue this would fix #3021

**Comment by hedgefield** [comment]
Love it.

**Comment by mtias** [comment]
Closing as done.
