### ISSUE TITLE
[FSE] Add a notice after Updating Design to confirm changes 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29846]
## What problem does this address?

Currently, saving in FSE is a two step process where one first clicks "Update Design" before being presented with options to select which changes to save. After confirming what you want to save though, there's no additional notice or indication in the UI that changes have been captured beyond the "Update Design" button greying out. Here's the experience: 

https://user-images.githubusercontent.com/26996883/111007030-21ee8e00-834b-11eb-9da0-4aac4c2431b4.mov

This came up as part of the [third call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1411):

> Once the design is saved, there is no confirmation but the button is no longer operable. The interface could communicate this better.

## What is your proposed solution?

I think we should re-use the messaging for saving a post in the core editor: 

https://user-images.githubusercontent.com/26996883/111007106-519d9600-834b-11eb-9041-78317a7370bc.mov

This could include an additional link to view the front end of the site but that likely will be too tricky considering multi-entity saving complexities. Here's a pretend mockup with a dismissible notice:

<img width="1426" alt="Screen Shot 2021-03-12 at 4 03 19 PM" src="https://user-images.githubusercontent.com/26996883/111007618-7fcfa580-834c-11eb-82da-9a625318bddd.png">

The verbiage is purposefully vague as I'm not sure if we could get specific enough to go through each specific change (template part, template, post, global styles, etc). 

This issue overall somewhat relates to this open issue around the saving flow in general: https://github.com/WordPress/gutenberg/issues/29577

**Comment by javierarce** [comment]
+1 to adding a snackbar.

If I'm not mistaken, looking [at the code of the save function](https://github.com/WordPress/gutenberg/blob/a9622b81bc2066c5d38c6726678349618ebbda6b/packages/editor/src/components/entities-saved-states/index.js#L62) we do have access to the kind, name, and key information of the saved entities, so I think we could be pretty specific with the message we show. 
 
I think we could use these rules:

- If the user saves just a specific element, we inform about it: 'Header updated' or 'Page updated'.
- If the user saves several elements of the same type (e.g.: 'Header' and 'Footer' areas), we refer to that instead: 'Templates updated'.
- If the user saves several elements of different types (e.g.: Page, Header, and Footer), we show a generic message: 'Changes saved' or 'Design saved'.

**Comment by annezazu** [comment]
I dig that approach!

**Comment by annezazu** [comment]
Closing this out! It now send a notice of "Site Updated" after changes our made :)
