### ISSUE TITLE
HTML view of "Read More" link is not intuitive.

### ISSUE THREAD

**Issue by themightymo** [WordPress/gutenberg#2985]
This isn't a bug, but it is a UI issue/question...

I was trying Gutenberg for the first time today, and first of all, mad props to y'all.  It's awesome.

But a couple of weird things struck me as odd about the "Read More" block:

1. It exists in the content by default.
2. It has an html view.

It seems like both of those things should be "false" instead of "true", because, respectively:

1. The last time I used the "Read More" functionality in the editor was 2004.
2. Why do I need to edit html on the Read More block?

<img width="1280" alt="read more" src="https://user-images.githubusercontent.com/179105/31437676-b040be68-ae4b-11e7-903e-05f27474f03d.png">

Thanks for all your hard work on Gutenberg!

Toby

**Comment by mtias** [comment]
Agreed it doesn't make sense for this block. Also, it doesn't make sense for the `HTML` block 😀 

cc @youknowriad

**Comment by Soean** [comment]
Also for the `Latest Post` and `Categories` block. We should add a property in the `registerBlockType` function.
