### ISSUE TITLE
Mobile: Pullquote and Quote Block: Inconsistent Markup for Newlines on Android

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#29862]
## Description

There is some inconsistency in the markup that's generated for new lines in the Quote and Pullquote blocks on Android devices.

## Step-by-step reproduction instructions

1. Add a new Pullquote block to the post editor in the Android app.
2. Enter a few lines of text into the block, pressing enter to create a new line each time.
3. Manually add another Pullquote block, and enter the exact same text you'd previously added to the first block.
4. Switch to HTML mode and compare the markup that was generated for each block.

## Expected behaviour

I would expect the generated markup to be the same for the two blocks, especially as the content is the same. 

I would also expect the markup to match what's generally generated when following the same steps on the web and iOS app i.e. a `<p>` tag surrounding each individual line. 

## Actual behaviour

The `<p>` tag is sometimes used for each individual line, as expected. In some cases, a `<br>` tag is used to generate a new line instead.

I tested and confirmed I wasn't able to replicate a `<br>` tag appearing when following these steps on either the web and iOS. This seems specific to the Android app.

Possibly related to these other open issues related to new lines in blocks with multiline components in Android: https://github.com/WordPress/gutenberg/issues/29861, https://github.com/WordPress/gutenberg/issues/27690

## Screenshots or screen recording (optional)

You'll see from the screenshots that I added the same content to two different Quote blocks. The first wrapped new lines with `<p>` tags, as expected. The second included a `<br>` tag the second line:

| No `<br>` tag  | `<br>` tag |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/111134811-e1be2400-8573-11eb-8816-a9e4c18b77a4.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/111135195-45485180-8574-11eb-9823-7e2c4fe50b00.png" width="100%"> |

## WordPress information

Tested using a simple (no plugins) WordPress.com site.

- WordPress version: 5.7
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: Pixel 5
- Operating system: Android 11
- WordPress app version: 16.8.1

**Comment by mchowning** [comment]
👋  @SiobhyB ! Thanks for the issue report. I think this may be the same issue [reported here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1396). What do you think? Admittedly they don't perfectly overlap since the earlier issue only discusses the quote block.

**Comment by SiobhyB** [comment]
@mchowning, ah, thank you for pointing that out, I missed it! I agree it's the same and will close this one as a dupe, in favour of the one you originally reported. I've also updated the reference I'd added to this issue in the test cases [here](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md). 🙇‍♀️
