### ISSUE TITLE
Mobile: Multiline Components: Loss of Previous Lines when Starting Multiple New Lines

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#29861]
## Description

When entering multiple new lines in a block that has a multiline component, the cursor sometimes behaves in an unexpected way (either moving to the top of the block or moving to a brand new block) and this can lead to lines being wiped/lost. 

I have been able to replicate this on Android devices only and with the following four blocks: _Quote_, _Verse_, _Preformatted_, _Pullquote_

This is similar to the issue described in https://github.com/WordPress/gutenberg/issues/27690, but I'm creating a separate issue as it's slightly different in that I've been able to replicate this while the cursor is at the end of the block and there is a loss of lines/content in this scenario.

Similar to [this issue](https://github.com/WordPress/gutenberg/issues/27690), there are times where the steps work as expected and it can be tough to reliably reproduce this. You'll see in [this thread](https://github.com/WordPress/gutenberg/pull/29683#issuecomment-797558908) that I had mistakenly thought this was specific to a new branch as I'd had difficulty replicating on the main branch. I've since been able to replicate this on the latest alpha version of the Android app.

## Step-by-step reproduction instructions

The most reliable way I have found to replicate this issue is as follows:

1. In the post editor on an Android device, add a new Quote or Pullquote block.
2. Enter a line of text and then tap the enter key _twice_ in succession. 
3. Notice how the second empty line is removed.

## Expected behaviour

In the steps provided, I would expect the block to contain three lines, with the second line being empty and my cursor being in the third line.

## Actual behaviour

The second (empty) line is removed in the above steps. The user in this scenario _should_ be typing into the third line, but this ends up being the second line:

https://user-images.githubusercontent.com/2998162/111130026-a8cf8080-856e-11eb-9f72-7c09b87608a5.mov

Although trickier to reliably reproduce, I have been able to replicate what you see in the following video on the latest version of app, where actual text (rather than just an empty line) is removed when entering multiple lines in a multiline component:

https://user-images.githubusercontent.com/2998162/111130353-0663cd00-856f-11eb-8462-9e3962bfd1a0.mov

## WordPress information

Tested using a simple (no plugins) WordPress.com site.

- WordPress version: 5.7
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: Pixel 5
- Operating system: Android 11
- WordPress app version: 16.8.1

**Comment by mchowning** [comment]
I initially overlooked that it was possible to lose content beyond an empty line here, so updating the priority to be `High`.

**Comment by AmandaRiu** [comment]
FYI: This is still an issue as of `1.57.0`. I was in here already completing writing flows tests so I thought I'd make a note of it. 


https://user-images.githubusercontent.com/5810477/125338154-d7434980-e31d-11eb-8ba9-e3485084b65c.mp4

Tested on physical Pixel 4 running Android 11 w/ Gboard

**Comment by SiobhyB** [comment]
I tested this in the most recent production build (23.8.1) and have not been able to reproduce. As there have been no other reports since July, 2021, I assume this has been resolved. Going ahead to close this issue 🎉
