### ISSUE TITLE
Use of registerBlockStyle crashes editor if example parameter not defined in registerBlockType

### ISSUE THREAD

**Issue by rnlmedia** [WordPress/gutenberg#29876]
## Description
Use of registerBlockStyle crashes editor if an _example_ parameter not defined in registerBlockType with `block.innerBlocks is undefined` error

## Step-by-step reproduction instructions
1. Create a simple block, eg by using [create-guten-block](https://github.com/ahmadawais/create-guten-block)
2. Modify the block to add block styles/variations with the [registerBlockStyle](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/) filter (code snippet example given below)
3. The style switcher in the block inspector works fine (green arrow in screenshot below), but the inline style switcher (red arrow in screenshot below) will not load a preview, instead it crash the editor with an error when the desired style is hovered over.
4. The way to stop the issue is to pass an empty (supposedly optional) _example_ object in the [block registration object](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/) (code snippet workaround is given below)

## Expected behaviour
Editor should display the preview for the block, even if the _example_ object is not defined during block registration or the example object should be made mandatory.

## Actual behaviour
Editor crashes with error
![gutenberg-styles-issue-eg](https://user-images.githubusercontent.com/1689871/111176962-b4886a80-85a1-11eb-9b6b-540931c8ec81.png)
![gutenberg-editor-crash](https://user-images.githubusercontent.com/1689871/111176989-b9e5b500-85a1-11eb-8160-593a987d31fc.png)

## Code snippet
To add block styles:-
`wp.domReady( () => {
	registerBlockStyle( "cgb/block-test-block", [
		{
			name: "default",
			label: "Default",
			isDefault: true,
		},
		{
			name: "boxed",
			label: "Boxed",
		},
	] );
} );`

Adding an empty _example_ object during the Block registration to fix the issue with:-

`registerBlockType( 'cgb/block-test-block', {
	...
	example: {
    },
...
}
`

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Only example plugin - test-block — CGB Gutenberg Block Plugin to demonstrate issue.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty One

## Device information
- Device: Desktop
- Browser: Firefox 81.0

**Comment by talldan** [comment]
@rnlmedia Would you be able to share the error message and stack trace?

**Comment by gziolo** [comment]
I was able to reproduce the issue by commenting out `example` in the definition for the Query block.

**Comment by rnlmedia** [comment]
Sure @talldan, stack trace below. Not sure how best to identify the mapped src file(s), but hopefully the below is helpful and do let me know if you need any more information:- 

`Uncaught TypeError: block.innerBlocks is undefined`
in
`cloneBlock@https://develop.local/wp-includes/js/dist/blocks.js?ver=9ed25ffa009c799f99a4340915b6dc6a:7852:5
BlockStylesMenu@https://develop.local/wp-includes/js/dist/block-editor.js?ver=7bc2f41a2f2e0da426f12f29b2139cae:23825:51
renderWithHooks@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:14938:29
updateFunctionComponent@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:17169:22
beginWork@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:18745:18
callCallback@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:182:16
invokeGuardedCallbackDev@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:231:18
invokeGuardedCallback@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:286:33
beginWork$1@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:23338:30
performUnitOfWork@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:22292:14
workLoopSync@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:22265:24
performSyncWorkOnRoot@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:21891:11
flushSyncCallbackQueueImpl/<@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11224:26
unstable_runWithPriority@https://develop.local/wp-includes/js/dist/vendor/react.js?ver=16.13.1:2685:14
runWithPriority$1@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11174:12
flushSyncCallbackQueueImpl@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11219:26
flushSyncCallbackQueue@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11207:5
batchedEventUpdates$1@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:22012:9
batchedEventUpdates@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:792:14
dispatchEventForLegacyPluginEventSystem@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:3691:26
attemptToDispatchEvent@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:4390:46
dispatchEvent@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:4312:43
unstable_runWithPriority@https://develop.local/wp-includes/js/dist/vendor/react.js?ver=16.13.1:2685:14
dispatchUserBlockingUpdate@https://develop.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:4295:20`

@gziolo Yes, that's probably a more succinct way of replicating the issue. A couple of plugins I did check from the plugin directory did not implement the [example parameter](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#example-optional) during block replication, so would also be subject to the same issue if one was to use [registerBlockStyle Block Filter](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/).

**Comment by gziolo** [comment]
I have a fix ready in #29894.
