### ISSUE TITLE
Category and tag blocks: Add option to prepend text

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#29909]
## What problem does this address?

A common pattern in themes is to display categories and tags prepended with a text. This is the case for _all_ default themes, including TwentyTwentyOne.

<img width="631" alt="twentytwentyone-categories" src="https://user-images.githubusercontent.com/1221942/111365702-1b398100-8693-11eb-95b5-d12efa931d31.png">

Currently this pattern cannot be replicated using blocks, because:
1. The only way to add any text is using a paragraph. This brings its own challenges, as paragraphs have their own styles-- an important one being the bottom margin. This means relying on CSS, which would go against the proclaimed goals of the FSE MVP, which is not to use any code.
2. The Post Categories and Post Tags blocks can't be placed inside of a paragraph block.
3. The Post Categories and Post Tags blocks are `div` elements. They therefore can't be placed in a `p` tag from a semantic standpoint.
4. Even if you manage to piece together the desired display using blocks and CSS, you'll run into the issue that the prepend text gets displayed even if there are no categories or tags.

## What is your proposed solution?

The Post Categories and Post Tags blocks should accept a prepend text. This would work similarly to how the Post Author block accepts a byline.

**Comment by Quintis1212** [comment]
Hello ) I will fix this bug )
