### ISSUE TITLE
Gutenberg plugin breaks Widgets in Customizer

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#29904]
## Description
The Gutenberg plugin (v10.1.1) seems to be breaking the Widget panel in the Customiser, instead of a graphical user interface, serialised JSON seems to be dumped to the screen.

## Step-by-step reproduction instructions
1. Place some widgets in the Widget screen, or with Gutenberg plugin deactivated.
2. Activate Gutenberg plugin if needed
3. Navigate to Customizer screen and open un the Widgets panel
4. Not the unusual content

## Expected behaviour
The Widget section of Custmizer should work the same with Gutenberg active or not.

## Actual behaviour
See step to reproduce above and left panel in image below.

## Screenshots or screen recording (optional)

<img width="1676" alt="Screenshot 2021-03-16 at 17 14 06" src="https://user-images.githubusercontent.com/1280733/111351434-136de280-867b-11eb-9f35-23398eae6e5e.png">

## WordPress information
- WordPress version: 5.8-alpha-50535
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes: Tested in TwentyFifteen and Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: MacOS 11.2.3
- Browser: Safari 14.0.3

**Comment by talldan** [comment]
@mattyrob You can disable this on the Gutenberg experiments plugin screen:
<img width="885" alt="Screenshot 2021-03-17 at 9 14 47 am" src="https://user-images.githubusercontent.com/677833/111399922-4490f600-8701-11eb-87d3-c877e549ca5b.png">

I think this is disabled by default, so it was possibly enabled by someone on your site? I can't say for certain though (cc @kevin940726, @noisysocks).

**Comment by mattyrob** [comment]
@talldan 

Thanks for the pointer, that got it working again but I was on a localhost testing site anyway so logged the ticket for debugging.

I'm trying to get a Widget Color Picker working on the legacy Widgets page, in the Customizer and in the new Gutenberg page - two out of three working perfectly. I guess as this is still experimental I can afford time to let the code soak a little first - upstream changes may fix my issues.
