### ISSUE TITLE
Image block overlapping Table Dropdown

### ISSUE THREAD

**Issue by irelandpaul** [WordPress/gutenberg#2991]
Using version 1.4.0

Images overlap table dropdown (components-dropdown-menu__menu) from block above. 

![image](https://user-images.githubusercontent.com/641691/31467612-32a11c1e-aea0-11e7-8c85-a338d9958483.png)

z-index for the image block is 10. If the preceding table block is set to z-index: 11, the dropdown displays properly.

![image](https://user-images.githubusercontent.com/641691/31467706-84679b86-aea0-11e7-810f-32992f107e92.png)

**Comment by youknowriad** [comment]
This should probably be fixed by #2989

**Comment by irelandpaul** [comment]
@youknowriad You're right thank you!
