### ISSUE TITLE
Code editor view crashes block editor when post type has no title support

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#29921]
## Description

If a post type does not have title support and I switch to the code editor view when editing the post, the block editor crashes with a `TypeError: Cannot read property 'ownerDocument' of undefined` because `ref.current` [is undefined in the post title component](https://github.com/WordPress/gutenberg/blob/7f58c19d47e0dc7225d4c0d7f4ae0d9dfb1a08c7/packages/editor/src/components/post-title/index.js#L67).

## Step-by-step reproduction instructions
1. Register a post type with no title support.
2. Add a new post of that post type.
3. Try to visit the code editor.

## Expected behaviour

:)

## Actual behaviour

`TypeError: Cannot read property 'ownerDocument' of undefined`

## Screenshots or screen recording (optional)

![title-crash](https://user-images.githubusercontent.com/286171/111418593-31503d00-86a5-11eb-823d-5a2ba0fc1a32.gif)

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? Everything except for the plugin that registers the post type.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Laptop
- Operating system: MacOS 11.2
- Browser: Chromium 89.0.4389.90

**Comment by jeremyfelt** [comment]
Also (maybe) related #29407 - I'm not familiar enough to be sure, but it's possible this error wouldn't occur if the post title component wasn't used at all in a post type with no title support.

**Comment by talldan** [comment]
Also #29266, which I think is similar.

**Comment by ntsekouras** [comment]
Fixed by: https://github.com/WordPress/gutenberg/pull/29922
