### ISSUE TITLE
`mappings` configuration incompatible/breaks on default WP installs for `wp-env`

### ISSUE THREAD

**Issue by nerrad** [WordPress/gutenberg#29929]
## Description

I noticed after updating the `wp-env` package locally that if my `.wp-env.json` file has a `mappings` property defined with no `core` property (or explicitly setting `core` to `null`), that executing `wp-env start` (installed as a package) results in the following error:

```
No container found for wordpress_1
```

I'm not sure of the cause yet but I'm guessing that it's a race condition where the container isn't ready for any mapped files/directories to be set.

As a temporary workaround, explicitly defining the WordPress version to use on the `core` property works fine with `mappings`.

## Step-by-step reproduction instructions

Define a custom `.wp-env.json` file with something like this.

```json
{
    "core": null,
    "mappings": { "filename.txt": "some/actual_local_file.txt" }
}
```

Execute the equivalent `wp-env start` for the environment installed as a local package (likely reproduces installed globally as well).

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur
- Browser: n/a

**Comment by nerrad** [comment]
Could be related to #29814

**Comment by noahtallen** [comment]
@nerrad can you test to see if #30053 fixes your issue? I'm unfortunately unable to reproduce :/

Edit: now that #30053 has been merged, it'd be worth testing with trunk.

**Comment by nerrad** [comment]
Yeah I'll try to do this sometime today or over the weekend and let you know.

**Comment by nerrad** [comment]
Sorry for the delay, it looks like this fixed this issue 👏
