### ISSUE TITLE
How to sort out images by newest first with Gutenberg gallery

### ISSUE THREAD

**Issue by Fingolfin75** [WordPress/gutenberg#29934]
Hello, I am making a website for a friend that has no experience at all and in order to keep things simple, I used just a basic theme and Gutenberg. I set up a gallery but I would like images to be sorted out automatically so that the newest entries will automatically go on top of the grid. Found no way to do that other than add other gallery plugins.
Am I missing something or there is a way through code to achieve this? Thanks!

**Comment by jordesign** [comment]
Closing this issue in favour of a duplicate covering gallery sort orders.
https://github.com/WordPress/gutenberg/issues/24578
