### ISSUE TITLE
Navigation Block: Start empty and add link keyboard navigation

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#29948]
For folks 👀 , also let me know if certain behavior is expected or if there's alternative keyboard movement controls. (I am aware of keyboard shortcuts, though any richtext or text areas will capture keyboard input).

1. From the placeholder navigation menu, press <kbd>enter</kbd> on the "start empty" element.

Navigation doesn't appear to be selected, I need to <kbd>tab</kbd> again.

https://user-images.githubusercontent.com/1270189/111501019-d698fe80-8701-11eb-89cf-c5c83717632f.mp4

2. After adding a link, pressing <kbd>enter</kbd> then <kbd>tab</kbd> opens publishing settings?

https://user-images.githubusercontent.com/1270189/111500336-1d3a2900-8701-11eb-9049-0fdc85dff52e.mp4

Other keyboard shortcuts for reference.
<img width="529" alt="Screen Shot 2021-03-17 at 9 23 40 AM" src="https://user-images.githubusercontent.com/1270189/111501849-8cfce380-8702-11eb-98b8-b3e576bf3b2a.png">

**Comment by kathrynwp** [comment]
Hi @gwwar, I'm circling back to this issue and wondering if it's still valid. Could you please let me know when you have a moment, thank you!

I started testing, but am not able to replicate at this step:

> Navigation doesn't appear to be selected, I need to tab again. 

Clicking my "enter" key at that step did create an empty menu, as expected. 

Tested with:

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
Twenty Twenty-Two 1.2

**Comment by jordesign** [comment]
With no further movement here, and given that the placeholder state of the nav has changed - I'll close this as no longer needed.
