### ISSUE TITLE
Extended Settings are on top of the quick block changer

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2994]
Gutenberg version: 1.4

## Issue Overview
<img width="202" alt="screen shot 2017-10-11 at 11 04 52 pm" src="https://user-images.githubusercontent.com/622599/31477210-b0f97bd2-aed8-11e7-9fd1-3076d9c6499b.png">

## Steps to Reproduce (for bugs)

1. Have a paragraph block at the bottom of the page close to the "Extended Settings"
2. Try to change it using the first button

## Expected Behavior

The Changer appears on top of everything else.

## Current Behavior

<img width="202" alt="screen shot 2017-10-11 at 11 04 52 pm" src="https://user-images.githubusercontent.com/622599/31477210-b0f97bd2-aed8-11e7-9fd1-3076d9c6499b.png">

## Possible Solution

World War Z-index ? 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
Could this be resolved by #2989

**Comment by mtias** [comment]
This should be fixed now.
