### ISSUE TITLE
Navigation Block: Add ability to create a post draft

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#29951]
## What problem does this address?

As part of the third call for testing with the FSE Outreach Program, [feedback was given](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1416) that it would be great for there to be an option to add a post draft similar to the current drafting process with adding a new page:

<img width="450" alt="Screen Shot 2021-03-17 at 4 48 04 PM" src="https://user-images.githubusercontent.com/26996883/111548599-9311b500-8740-11eb-9dfe-568026b4a5fe.png">

## What is your proposed solution?

Add the ability to create a draft of a post to add as a menu item. Reusing the same flow it could look like this. cc @shaunandrews as an fyi in case you have thoughts :)

<img width="718" alt="Screen Shot 2021-03-17 at 4 49 10 PM" src="https://user-images.githubusercontent.com/26996883/111548746-c48a8080-8740-11eb-95c9-6953a3ef4e12.png">

**Comment by shaunandrews** [comment]
This is already possible, but you have to insert a Post Link block:

<img width="127" alt="image" src="https://user-images.githubusercontent.com/191598/115048414-88fde600-9ea7-11eb-99b9-7bb1e78e3953.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/191598/115048445-91eeb780-9ea7-11eb-8187-1ae75ecdee00.png">

If you insert the Page Link block or the Custom Link block, then the option is to create a page.

I guess we could allow for both options when using the Custom Link block, but the thinking is that its very uncommon to add a link to a post within a Navigation block.

**Comment by annezazu** [comment]
Ah ha got it! Makes sense. I'll close this out then as it does seem like, in general, most people will want to add a page and it's better to have some friction around adding a post.
