### ISSUE TITLE
Navigation: Line-height setting missing

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#29959]
Could we have a line-height setting for the navigation block? This would give us more fine-grained control and enable header designs such as these, where the vertical alignment is essential:

![image](https://user-images.githubusercontent.com/4550351/111576026-c36e5780-8803-11eb-81a7-3d1b3149272e.png)

![image](https://user-images.githubusercontent.com/4550351/111576036-c9fccf00-8803-11eb-950c-a57099147d33.png)

![image](https://user-images.githubusercontent.com/4550351/111576106-f0bb0580-8803-11eb-8c5a-e35e07b69134.png)

I think this could also be useful in the case of vertical navigation where tightening the vertical spacing is currently impossible:

![image](https://user-images.githubusercontent.com/4550351/111576407-8fdffd00-8804-11eb-9827-3aed327c6775.png)

**Comment by jasmussen** [comment]
PR here: https://github.com/WordPress/gutenberg/pull/30010
