### ISSUE TITLE
Gutenberg 10.2.0 Locked caused a fatal error

### ISSUE THREAD

**Issue by bradhouser** [WordPress/gutenberg#29977]
After updating to 10.2.0 I got an email about a technical issue with the plugin:

Error Details
=============
An error of type E_ERROR was caused in line 59 of the file /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php. Error message: Uncaught Error: Class 'WP_Block_Supports' not found in /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php:59
Stack trace:
#0 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-content/plugins/gutenberg/lib/load.php(117): require()
#1 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-content/plugins/gutenberg/gutenberg.php(213): require_once('/homepages/44/d...')
#2 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-content/plugins/gutenberg/gutenberg.php(20): gutenberg_pre_init()
#3 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-settings.php(377): include_once('/homepages/44/d...')
#4 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-config.php(92): require_once('/homepages/44/d...')
#5 /homepages/44/d675584201/htdocs/clickandbuilds/WordPress/Production/wp-load.php(37): require_once('/homepages/44/d...')
#6 /homepages

I was able to de-activate the plugin via ftp. Now I don't want to activate it until I know this has been addressed.

**Comment by davidkryzaniak** [comment]
I've noticed the same thing. (Docker Image: andreccosta/wordpress-xdebug, PHP 7.4.9, MySQL 5.7)

![image](https://user-images.githubusercontent.com/1409191/111641701-63f45580-87cb-11eb-9dee-306b9357e52d.png)

**Comment by davidkryzaniak** [comment]
I was running WordPress 5.6. After the upgrade to 5.7, everything started working as expected.

**Comment by bradhouser** [comment]
Thanks for letting me know about 5.7.  I hadn't updated WP either, now I can re-activate Gutenberg.

**Comment by youknowriad** [comment]
Anyone can confirm the WordPress version causing the issue., AFAIK WP_Block_Supports is present on 5.6 as well so it shouldn't cause this.

**Comment by davidkryzaniak** [comment]
😬  Oops, I was actually on WordPress 5.4.2.

**Comment by youknowriad** [comment]
Ok Thanks, closing for now.
