### ISSUE TITLE
Post Comments Count Block: Duplicate class attribute

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#29970]
## Description

In the `gutenberg_render_block_core_post_comments_count()` function, `get_block_wrapper_attributes()` is used to get the attributes to output on the block wrapper.

By default the `get_block_wrapper_attributes()` will return `class="wp-block-post-comments-count"`. Keep note of the `class` attribute name.

These attributes are then output this way:
```php
	return sprintf(
		'<div class="%1$s">%2$s</div>',
		$wrapper_attributes,
		get_comments_number( $block->context['postId'] )
	);
```

Note the extra `class="%1$s"`. This results in broken markup: `<div class="class=" wp-block-post-comments-count""="">1</div>`.

## Step-by-step reproduction instructions

1. Add a Post Comment Count block to any template or page, and save it.
2. View the frontend and inspect the block markup to see the broken output.

## Expected behaviour

The block should produce proper markup with a single `class` attribute.

## Actual behaviour

The block should produces broken markup due to the duplicate `class` attribute.

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: 10.1.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1

**Comment by ntsekouras** [comment]
Thanks for reporting this @fklein-lu!
