### ISSUE TITLE
Fatal error in Gutenberg plugin 10.2.0

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#29972]
## Description

I received a "Your website is having technical difficulties" e-mail (The e-mail is in Norwegian, and am just directly translating to English.)

Web site looked like this (again this is Norwegian):

![Screen Shot 2021-03-18 at 11 44 10](https://user-images.githubusercontent.com/5323259/111613895-4c26cc80-87df-11eb-8c8e-164c98b7b2d9.png)

With the recovery link I was able to login and noticed that the Gutenberg plugin had been deactivated.

![Screen Shot 2021-03-18 at 11 45 13](https://user-images.githubusercontent.com/5323259/111614025-6e204f00-87df-11eb-9db9-c1901836500a.png)

 Denne utvidelsen kunne ikke lastes riktig og er derfor midlertidig stoppet under gjenopprettingsmodus.

En feil av typen E_ERROR ble forårsaket i linje 59 i filen /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php. Feilmelding: Uncaught Error: Class 'WP_Block_Supports' not found in /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php:59 Stack trace: #0 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/load.php(117): require() #1 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/gutenberg.php(213): require_once('/home/edwiegjz/...') #2 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/gutenberg.php(20): gutenberg_pre_init() #3 /home/edwiegjz/religionskritikk.no/wp-settings.php(377): include_once('/home/edwiegjz/...') #4 /home/edwiegjz/religionskritikk.no/wp-config.php(68): require_once('/home/edwiegjz/...') #5 /home/edwiegjz/religionskritikk.no/wp-load.php(37): require_once('/home/edwiegjz/...') #6 /home/edwiegjz/religionskritikk.no/wp-login.php(12): require('/home/edwiegjz/...') #7 {main} thrown

## Expected behaviour
No fatal error in the Gutenberg plugin. That the site just works as normal.

## Actual behaviour
Fatal error.

## WordPress information
- WordPress version: 5.5.3
- Gutenberg version: Versjon 10.2.0
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**I assume that the Gutenberg plugin version 10.2.0 will not work in the older WordPress version 5.5.3. Upon perhaps autoupdating that the update caused a fatal error.**

**Comment by paaljoachim** [comment]
I deactivated the Gutenberg plugin 10.2.0.
When I tried to reactivate the plugin the fatal error came back.

Fatal error: Uncaught Error: Class 'WP_Block_Supports' not found in /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php:59 Stack trace: #0 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/load.php(117): require() #1 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/gutenberg.php(213): require_once('/home/edwiegjz/...') #2 /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/gutenberg.php(20): gutenberg_pre_init() #3 /home/edwiegjz/religionskritikk.no/wp-admin/includes/plugin.php(2297): include('/home/edwiegjz/...') #4 /home/edwiegjz/religionskritikk.no/wp-admin/plugins.php(191): plugin_sandbox_scrape('gutenberg/guten...') #5 {main} thrown in /home/edwiegjz/religionskritikk.no/wp-content/plugins/gutenberg/lib/block-supports/generated-classname.php on line 59

**Comment by youknowriad** [comment]
There's nothing we can do here. That version is incompatible with WP 5.5. It just shouldn't be used there.

**Comment by paaljoachim** [comment]
That is what I thought.
It should not be possible for autoupdating Gutenberg plugin on an older WP site. As the result seems to create a fatal error. As there can be a lot of sites that will come across this problem. 

@desrosj @audrasjb

**Comment by youknowriad** [comment]
I think we had an issue where the required version was duplicated in both `gutenberg.php`  and `readme.txt`. So the auto-updater might have been relying on the wrong one. This is was fixed recently in #29646 and will be active in the next version.

**Comment by paaljoachim** [comment]
Great! Thanks Riad!
