### ISSUE TITLE
Exiting a scheduled post triggers "Do you want to leave"

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2997]
Gutenberg version: 1.4

## Issue Overview

When I schedule a post for later and then attempt to leave the page, I get a warning asking if I want to leave despite not having any unsaved changes

## Steps to Reproduce (for bugs)

1. write a post
2. schedule it for later
3. Try to leave the page
4.

## Expected Behavior

Scheduling a post should be considered the same as publishing it and no warning should be triggered.

**Comment by vladanost** [comment]
Gutenberg version 1.4
I followed recommended steps and I'm not able to reproduce the issue.

**Comment by youknowriad** [comment]
I'm not able to reproduce either.

**Comment by karmatosed** [comment]
Closing as unable to reproduce in latest version of Gutenberg.
