### ISSUE TITLE
Page Link block appears to be missing from the inserter

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#29984]
When running the latest `trunk`, it appears that the "Page Link" block is missing from the Navigation block's inserter. This happens in both the Site Editor and the Post editor. 

## To reproduce

1. Add a Navigation block, hit "Start empty". 
2. Select the plus icon to add a child block.
3. See that the Page Link block is missing. 

## Screenshot

![Screen Shot 2021-03-18 at 11 26 49 AM](https://user-images.githubusercontent.com/1202812/111654178-e5a1ae80-87de-11eb-80ff-4d9f60d18a5e.png)

---

Tested with WordPress 5.7, Gutenberg `trunk` (Version 10.2.0)

**Comment by bobbingwide** [comment]
I assume the fix for this will also reinstate the other missing variations: Post Link, Category link and Tag link.

**Comment by gwwar** [comment]
Yes, that's correct @bobbingwide
