### ISSUE TITLE
Embed editor problems

### ISSUE THREAD

**Issue by imation4430** [WordPress/gutenberg#29995]
HI: Dear friends. I have observed that when using (since the update to WordPress 5.7 in the editor the embed option to url, it is seen from the dasbohar, but when publishing it you only see the link and not the entire box. Please give me a solution or confirm if it is a bug:

I leave a link for you to better understand what I say

https://paucompany.es/Wocommerce

The first image would correspond to the front, as the user sees it (until the update it looked like this)

and the second image what I see in the editor when inscribing the url

![image](https://user-images.githubusercontent.com/1832087/111702233-3c89a100-883c-11eb-8796-25a7d02aec84.png)
![image](https://user-images.githubusercontent.com/1832087/111702284-4f03da80-883c-11eb-9a89-304b79deb648.png)

**Comment by obulat** [comment]
Thank you for reporting this, @imation4430! 
The good news is that Gutenberg editor shows embedded posts correctly, just as you see in the second screenshot. The bad news is that there is a bug in rendering the WordPress post embed blocks. The issue has been reported on Trac: [WordPress post URL oEmbed rendering blocked by iframe lazy-loading](https://core.trac.wordpress.org/ticket/52768). You can follow that ticket to see when it gets fixed.

**Comment by jasmussen** [comment]
Thanks for ticket and thanks for the triage @obulat! I'm going to go ahead and close this ticket in favor of the trac counterpart, as that's the one to follow for a solution.

**Comment by imation4430** [comment]
Thanks to you I have solved the problem by adding the code:
function disable_post_content_iframe_lazy_loading ($ default, $ tag_name, $ context) {
     if ('iframe' === $ tag_name && 'the_content' === $ context) {
         return false;
     }
     return $ default;
}
add_filter (
     'wp_lazy_loading_enabled',
     'disable_post_content_iframe_lazy_loading',
     10,
     3
);
as you indicated to me in the link that you attached to me in the functions.php in the child-theme
