### ISSUE TITLE
Tooltips do not preserve position on scroll

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2999]
## Issue Overview
Tooltips do not scroll with the element they're supposed to attached to.

## Steps to Reproduce (for bugs)
1. Hover over or focus something with a tooltip.
2. Scroll. The tooltip won't scroll with the page.

## Possible Solution
I assume the tooltip is fixed positioned. Maybe absolute positioning works out better?

**Comment by youknowriad** [comment]
Experiencing the same issue with dropdowns here #2987

**Comment by youknowriad** [comment]
I see two options:

 - Track all parent scrollables scroll event
 - Provide a way ( a prop or something) to opt-in absolute positioning instead of fixed positioning
