### ISSUE TITLE
Gallery block refactor: selecting parent gallery does not show blue selection outline

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#29998]
## Description
Normally when select the parent of grouped blocs a blue outline is show around the selected block, this doesn't currently happen with the refactored gallery. It appears to be due to the fact the the caption rich text field immediately steals focus

## Step-by-step reproduction instructions

1. Check out [gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940) and turn on refactored gallery experiment
2. Add a new gallery block with images
3. Select parent gallery block
4. Notice the block is not outlined

## Screenshots or screen recording (optional)

![no-oultine](https://user-images.githubusercontent.com/3629020/111707383-d129e880-88a8-11eb-9730-d0cdcbb9a6c9.gif)

**Comment by paaljoachim** [comment]
Hey Glenn

I am adding this in here as well: https://github.com/WordPress/gutenberg/issues/30198

**Comment by glendaviesnz** [comment]
This issue is no longer present so assume something changed on trunk  that resolved this.

![selected](https://user-images.githubusercontent.com/3629020/116153224-19a3b400-a73b-11eb-9411-21cf9b6fa8f1.gif)

**Comment by glendaviesnz** [comment]
Fixed by #31216
