### ISSUE TITLE
Gallery block refactor: image link is lost when crop is applied

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#29996]
## Description
If an Image block nested in the refactored gallery block has a link applied and then is cropped the link is lost and needs to be re-added, but the user gets no indication that the link has been removed.

## Step-by-step reproduction instructions

- Check out Gallery refactor PR and enable refactored gallery experiment
- Add an Image block
- Add a link to the Image, either custom or Media/Attachment
- Use the Image toolbar to crop the image and apply change
- Check link and notice it is gone

## Expected behaviour
The link should be copied to the new image

## Actual behaviour
Link is removed without any indication/warning that this has happened.

## Screenshots or screen recording (optional)

![link-gone](https://user-images.githubusercontent.com/3629020/111704269-bacd5e00-88a3-11eb-91ec-939997c79004.gif)

## WordPress information
- Gutenberg version: 10.1.1

**Comment by Quintis1212** [comment]
Hello @glendaviesnz ) I can not reproduce this bug , can you share more details ?

**Comment by glendaviesnz** [comment]
> Hello @glendaviesnz ) I can not reproduce this bug , can you share more details ?

Thanks for testing, looks like it is only happening if the Image is nested in the refactored gallery block - have updated the issued to indicate this.

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/30550
