### ISSUE TITLE
Gallery block refactor: it is not possible to replace an image with drag and drop

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#29999]
## Description
It is not currently possible to replace an existing image within a library with drag and drop as is it with an individual image - images dragged onto an existing image in the gallery are added as new images between the existing images.

## Step-by-step reproduction instructions
Check out [gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940) and turn on refactored gallery experiment
Add some images to the gallery
Try dragging an image onto an existing image - it does not replace that image but is added as a new image to the gallery

## Expected behaviour
The individual image replace dropzone was turned off after an initial round of testing as it was thought to be a little confusing, particularly if multiple files were dropped on an image and only one was uploaded to replace the single image. 

However additional testing has indicated that some users expect that since a gallery image is now a standard image block the drag and drop replacement should work the same as an individual image, so the UX around this should be revisited.

**Comment by glendaviesnz** [comment]
User testing feedback has differed on this point, with users initially finding it confusing that sometimes image drag and drop added the image and sometimes it replaced depending on exactly where it was dropped, so the replace option was disabled in the gallery context.

Because this issue really required some detailed design input and a rethinking of how drag and drop works in the gallery context, and because it is no a regression because the current gallery does not allow drag and drop replacement of single images, this is being deferred until after the first release of the refactored gallery.

**Comment by kathrynwp** [comment]
Hi @glendaviesnz Circling back to this issue, could you please let me know if it's still on the radar or more of a "maybe later" situation? Thanks very much!

**Comment by glendaviesnz** [comment]
Would be good to circle back on this one, so let's leave it in the Gallery project backlog for now.

**Comment by annezazu** [comment]
Tested with 6.3 RC1 and found I can drag & drop an image to replace an item in a gallery: 

https://github.com/WordPress/gutenberg/assets/26996883/15b6ad83-3793-43ca-a531-a8a37bc2c193

Closing this out as a result, unless I've missed something!
