### ISSUE TITLE
“Select All” behavior

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#3]
Should ⌘+A/Ctrl+A select only the current block or the whole text?

In the current prototype I am looking at, it selects the whole text.

**Comment by jasmussen** [comment]
I think this is undecided, and may depend on whether we go with a TinyMCE-is-a-parent vs. TinyMCE-is-a-child approach. If the latter is a really good experience in every other aspect, we'll probably be okay with having Ctrl + A selecting the contents of the selected block, and asking people to go to the markup editor to copy/paste it all.

**Comment by melchoyce** [comment]
FWIW, this is a flow I do pretty frequently when writing a post — I'll write the draft in WordPress, copy and paste it into Hemingway to edit, then copy/paste it back into WordPress.

**Comment by jasmussen** [comment]
> I'll write the draft in WordPress, copy and paste it into Hemingway to edit, then copy/paste it back into WordPress.

To clarify: do you use the visual or HTML editor for this?

**Comment by melchoyce** [comment]
Visual. I only use the HTML editor to fix formatting issues like leftover markup.

**Comment by mapk** [comment]
In regards to the single TinyMCE editor, I feel the _command+A_ should select all content on the page... not just within the block.

**Comment by websupporter** [comment]
Hi,
just dropped in and tested it a bit. From the experience in the prototype here (https://wordpress.github.io/gutenberg/) for me it felt CMD+A should mark only the section. You can see it in this small screencast I've made https://www.youtube.com/watch?v=ZFBxYIoBMvU

Hope this helps :)

**Comment by jasmussen** [comment]
Multi block select is in master. So you can select across blocks. 

It would be nice if, when you are inside a text block, ⌘A selected all the text inside that block. When you do not have a block selected, you select all blocks on the page, as what Multi Select does. CC: @iseulde

**Comment by iseulde** [comment]
@jasmussen I like that idea. Together with the copy PR, you could easily copy all the content then. In case the distinction is confusion, we could even select all when all then content in a single block is already selected. So you can also select all from inside a block by doing it twice.

**Comment by jasmussen** [comment]
I do think we should postpone any and all copy paste efforts for the time being though.
