### ISSUE TITLE
Building Gutenberg 10.2.1 fails with error "could not resolve dependency: peer @wp-g2/create-styles@"^0.0.154" from components@13.0.0"

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#30003]
## Description
When I run `npm ci` on a local clone of Gutenberg, the install fails and I see the following error:

`could not resolve dependency: peer @wp-g2/create-styles@"^0.0.154" from components@13.0.0`

## Step-by-step reproduction instructions
1. Fork and clone local copy of Gutenberg
2. Run `npm ci` in terminal
3. The install should fail after a few moments and display the error message noted above in the description.

## Expected behaviour
Build tools for Gutenberg to install successfully.

## Actual behaviour
Build tools install failed.

## Screenshots or screen recording (optional)
![gutenberg-npm-ci-failure](https://user-images.githubusercontent.com/29587253/111716982-012eb700-88bc-11eb-8041-5d25b8c23ff6.png)

## WordPress information
- WordPress version: n/a
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? n/a
- Are you using a default theme (e.g. Twenty Twenty-One)? n/a

## Device information
- Device: Desktop
- Operating system: WSL2 on Windows 10
- Browser: n/a

**Comment by talldan** [comment]
@chthonic-ds Which version of node and npm are you using?

**Comment by chthonic-ds** [comment]
@talldan

- node 15.3.0
- npm 7.0.14

**Comment by talldan** [comment]
From what I understand, npm 7 isn't compatible at the moment. There are a few issues open:

https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Build+Tooling%22+npm

Using node 14 and npm 6 should resolve the problem.

**Comment by chthonic-ds** [comment]
For anyone in future experiencing this issue, can confirm running node 14 with npm 6:

- resolved _this_ issue
- was followed by a new one
 
If you experience a bunch of errors of the nature, "ENOENT: no such file or directory...", try the solution in this comment, worked for me:  https://github.com/WordPress/gutenberg/issues/9474#issuecomment-420107785
