### ISSUE TITLE
Hover UI can overlap with selected UI

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#3000]
## Issue Overview
If a block is not very tall, and the right menu is opened, it will overlap with the hover UI of the next block.

<img width="728" alt="screenshot 2017-10-12 10 37 42" src="https://user-images.githubusercontent.com/4710635/31487003-922da776-af39-11e7-908c-5be3c67c6711.png">

**Comment by mtias** [comment]
This should no longer be a concern with the ellipsis menu.
