### ISSUE TITLE
User can alter typography of block placeholder in the navigation block

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30008]
## Step-by-step reproduction instructions
1. Add a navigation block and select it
2. Select some typography options like font weight and strikethrough

## Expected behaviour
The placeholder is not affected
-- or --
The typography options are not visible while the placeholder is shown

## Actual behaviour
The user can adjust the typography of the placeholder (fortunately not font size)

## Screenshots or screen recording (optional)
<img width="863" alt="Screenshot 2021-03-19 at 2 17 44 pm" src="https://user-images.githubusercontent.com/677833/111739561-36d49f80-88be-11eb-8cdc-79b02ec9b674.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2

**Comment by jasmussen** [comment]
Fix in https://github.com/WordPress/gutenberg/pull/30011
