### ISSUE TITLE
InputControl (and all components using InputControl) label alignment is broken 

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30026]
## Description

As shown in the screenshot (from storybook), the `SelectControl` component does not render the label with regard to the selected label position. No matter which position is set it always displays the label on the left side

## Step-by-step reproduction instructions

1. Go to storybook
2. Find InputControl or any other component using InputControl (i.e. SelectControl component `story/components-selectcontrol--default`)
3. Change the `labelPosition` property and see that the label remains in the same position

## Expected behaviour

Label positioning should change according to `labelPosition` property

## Actual behaviour

label remains in the same position
## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/8398557/111795595-a438fe00-88c7-11eb-9b41-41dc676aac10.png)

## WordPress information
- Gutenberg version: 10.0.0-rc.1

## Device information
- Device: MacBook 
- Operating system: MacOS Big Sur 
- Browser: Chrome 89.0

**Comment by skorasaurus** [comment]
can this be closed since you mentioned in https://github.com/WordPress/gutenberg/pull/30033#issuecomment-805796254 that it's being taken care of?

**Comment by skorasaurus** [comment]
closing this since I'm not able to reproduce in the storybook - https://wordpress.github.io/gutenberg/
