### ISSUE TITLE
Site Editor: Long post titles are centered.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30059]
## Description

In the site editor, you can click the W to access the site menu. Here, you can choose posts, pages, templates. 

If you have a post with a long post title, one that spans two or more lines, it will be centered:

<img width="332" alt="Screenshot 2021-03-20 at 19 18 15" src="https://user-images.githubusercontent.com/1204802/111881571-3f59d280-89b1-11eb-85fc-8b60e6ec5cbb.png">

This is because the `NavigationItem` is a `button` element, and those have `text-align: center;` applied by default.

## Expected behaviour

Text should be left aligned.

**Comment by jasmussen** [comment]
CC: @david-szabo97, I saw you touch pieces of this code recently, but feel free to point me in the wrong direction if there's a better one to talk with.

**Comment by david-szabo97** [comment]
Thanks! Opened a PR
