### ISSUE TITLE
Blog Posts Block: Post Excerpt Length Not Applied

### ISSUE THREAD

**Issue by kspilarski** [WordPress/gutenberg#30058]
## Description

In WordPress.com sites (with or without plugins / default or non-default theme), using the Blog Posts block, the "Max number of words in excerpt" length is not getting applied. 

## Step-by-step reproduction instructions

1. Go to Posts and create a new post.
2. In the post, add an excerpt and Update / Publish.
3. Go to Pages and create a new page , then insert Blog Posts block.
4. In Blog Posts block "Max number of words in excerpt", set the length of excerpt. 
5. Update / publish page. 
6. Check the length of the excerpt displayed in the editor and published page. 

## Expected behaviour

The length of words set in "Max number of words in excerpt" will be set. 

## Actual behaviour

The length of words set in "Max number of words in excerpt" is not applied. 

## Screenshots or screen recording (optional)

<img width="1539" alt="Screen Shot 2021-03-20 at 6 04 21 PM" src="https://user-images.githubusercontent.com/36863633/111878134-17657180-89a7-11eb-893f-ce6667fb5942.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Version: 10.2.1 
- Are all plugins except Gutenberg deactivated? No 
- Are you using a default theme (e.g. Twenty Twenty-One)? Either default / non-default theme, the issue remains.  

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1 
- Browser: Firefox, Chrome

**Comment by carolinan** [comment]
Hi
This is a custom block for WordPress.com, it is not part of Gutenberg.

Please see https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/.
