### ISSUE TITLE
Widgets screen blocks lack font families

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#30051]
## Description

Blocks on the widget screen lack styling. I'm unsure of the scope but the font family is definitely missing

## Expected behaviour

Block text font family to match the post editor

## Actual behaviour

Blocks are missing the font family:

<img width="485" alt="Screenshot 2021-03-19 at 23 05 53" src="https://user-images.githubusercontent.com/58855/111850243-b044b000-8907-11eb-8bca-7c4d409ead5a.png">

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 10.2.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: MBP 13" Intel
- Operating system: MacOS Big Sur 11.2.2
- Browser: Chrome 89

**Comment by Azragh** [comment]
Would be awesome if the editor-styles stylesheet would affect the widgets-screen (scoped in .editor-styles-wrapper of course). I really wonder why they weren't included from the beginning.. (isn't the goal of Gutenberg to provide a "real" WYSIWYG experience?)

**Comment by draganescu** [comment]
I think this is fixed by a recent unification of styles between editors (in #30076). In my testing the font family is correct so I will close this one :) Thank you!
