### ISSUE TITLE
Widgets screen undo button non-functional

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#30050]
## Description

The undo button in the toolbar is non-functional, clicking it does not undo the last action ( it doesn't do anything ass far as I can tell )

## Step-by-step reproduction instructions

1. Go to the experimental widgets screen
2. Make a change
3. Click the undo button

## Expected behaviour

The change is undone

## Actual behaviour

Nothing occurs

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: 10.2.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: MBP 13" Intel
- Operating system: MacOS Big Sur 11.2.2
- Browser: Chrome 89

**Comment by noisysocks** [comment]
Confirmed. Interestingly, it looks like <kbd>cmd</kbd>+<kbd>z</kbd> works.
