### ISSUE TITLE
Site Editor / iframe: Occasional double scrollbar.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30055]
## Description

When using the site editor, you will occasionally see a double scrollbar. The scrollbar appears to be caused by the sibling inserter being positioned outside of the iframe, but below the content:

<img width="1297" alt="bug" src="https://user-images.githubusercontent.com/1204802/111873082-eaa56000-898e-11eb-8dbd-62de10ad5f91.png">

## Step-by-step reproduction instructions

Preriquisites:

- Make sure you do not have auto-hiding scrollbars in MacOS
- Use a block theme, such as TT1 Blocks
- Open the web-inspector so it's ready to go

Steps to reproduce:

- Go to the site editor, and **while the template is still loading, hover the content to try and invoke the sibling inserter**
- If you're successful, the sibling inserter will be positioned incorrectly, due to being positioned according to content still loading. 

**Note:** If you mange to reproduce, be careful to not invoke the sibling inserter again, or the scrollbar will disappear. One thing that might help: as soon as you reproduce the double scrollbar, move the mouse to the inspector, then open the JS console and paste: `setTimeout(function(){debugger;}, 2000);`, then wait two seconds. This will lock the content, so you can now scroll down to see the sibling inserter sitting in a gray area outside the content.

## Expected behaviour

Only ever a single scrollbar, that of the iframe.

## Screenshots or screen recording (optional)

It's super fiddly to get this right, but if you use MacOS auto hiding scrollbars, you'll never see this. So you have to turn that off first.

![repro](https://user-images.githubusercontent.com/1204802/111873278-d877f180-898f-11eb-84ec-f7a0d3f4fe59.gif)

## Code snippet (optional)

One _potential_ fix is to change the CSS as shown in the GIF above, to specifically set `overflow: hidden;` on `.interface-interface-skeleton__content`. But because content is placed in the popover container outside the iframe, I'm not convinced that this will actually fix it.

**Comment by jasmussen** [comment]
CC: @ellatrix as I recall you having worked on the iframe.

**Comment by annezazu** [comment]
Noting that this has come up with WordPress 5.9 as part of the [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2346). You can see it replicated at 01:46 in this video: https://app.koofr.net/links/481d3053-4fd1-4756-60ef-5db5b25d0ed2

**Comment by jasmussen** [comment]
@ciampo do you know if #43332 fixed this issue? It seems like it might have! 🙏

**Comment by ciampo** [comment]
I believe it should have! It would be great if you could also confirm that you can't repro this issue anymore.

**Comment by jasmussen** [comment]
I haven't seen it in a while! Wonderful, I'll close this one. Thanks again 🙏
