### ISSUE TITLE
Unable to add InnerBlocks markup to `block-renderer` rest endpoint

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#30064]
## What problem does this address?

It is currently not possible to pass `innerBlocks` html to the `block-renderer` rest api endpoint. Technically the `block-renderer` endpoint just calls the `render_block` function https://github.com/WordPress/WordPress/blob/d3d78e755b815e1be5e15d8644dcd0688736dea1/wp-includes/rest-api/endpoints/class-wp-rest-block-renderer-controller.php#L186

and passes an empty string to the `innerHTML ` https://github.com/WordPress/WordPress/blob/d3d78e755b815e1be5e15d8644dcd0688736dea1/wp-includes/rest-api/endpoints/class-wp-rest-block-renderer-controller.php#L180
I've come across multiple instances where it would be beneficial to have the full power of the `render_block` function exposed to the API. That way headless sites would be able to utilize it to render any kind of nested blocks.

## What is your proposed solution?
Either adding an additional query param that allows passing the `innerHTML` or adding the option to make it a `POST` request where the  request `body` is the `innerHTML`.

**Comment by talldan** [comment]
@fabiankaegy Would you be able to create a trac ticket for this, as the code is in WordPress core. Thanks.
