### ISSUE TITLE
Wordpress 5.7 includes hidden character in empty paragraph CSS

### ISSUE THREAD

**Issue by StuartKent17** [WordPress/gutenberg#30063]
It seems like there's a hidden character in the CSS file causing paragraph tags to render even if they're empty.
This has caused a number of rendering issues in my sites.

/wp-includes/css/dist/block-library/style.min.css?ver=5.7

Copying from the Edge dev tools into the customiser, I expect:
```
p:empty:before {
    content: "​";
}
```
What I get is the below (There's an invisible symbol in there).
Running it through a converter; p:empty:before { content: "â"; }
​​​​​​​​​​​​​​​​​​​
```
p:empty:before {
    content: "​";
}
```
![Screenshot 2021-03-21 132012](https://user-images.githubusercontent.com/35883424/111889199-3d8f1e00-8a48-11eb-8c6d-dbc2324c0f1e.png)

**Comment by carolinan** [comment]
Hi! 
This was reverted in https://github.com/WordPress/gutenberg/pull/29809
The solution will be included in Gutenberg 10.3 and a future version of WordPress.
Because of this, I am closing the issue.
