### ISSUE TITLE
Site Editor/Navigation sidebar: Custom post types do not show up under "Content"

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30060]
## Description

In the site editor, you can click the W, the site menu, to load templates, pages or posts. But you can't load posts with a custom post type, these don't show up:

<img width="283" alt="no cpts" src="https://user-images.githubusercontent.com/1204802/111881760-53ea9a80-89b2-11eb-9503-0f3e3d3baa95.png">

## Expected behaviour

When a custom post type is registered, an additional menu item should show up in the site menu, letting you load content from that type.

## Code snippet

Registere a custom post type, for example by pasting the following in your theme functions.php file:

```
/**
 * Custom post type and template.
 */

function myplugin_custom_post_type() {
	register_post_type( 'podcast',
		array(
			'labels' => array(
				'name' => __( 'Podcasts' ),
				'singular_name' => __( 'Podcast' )
			),
			'public' => true,
			'has_archive' => true,
			'rewrite' => array('slug' => 'podcast'),
			'show_in_rest' => true,
			'supports' => [
				'title', 'editor',
			],
		)
	);
}
add_action( 'init', 'myplugin_custom_post_type' );

// Assign a post template to our custom post type
function myplugin_register_template() {
	$post_type_object = get_post_type_object( 'podcast' );
	$post_type_object->template = array(
		array( 'core/cover', array( 'content' => 'Description', ) ),
		array( 'core/gallery' ),
	);

	// Lock the template from being rearranged or items deleted.
	$post_type_object->template_lock = 'all'; // Can be "all" or "insert", the latter allows moving blocks around.
}
add_action( 'init', 'myplugin_register_template' );
```

Now a "Podcasts" post type will show up in the admin sidebar. But published posts of the post type do not show up in the sidebar.

**Comment by bobbingwide** [comment]
I would have assumed this is a basic requirement. 
Ditto for custom taxonomies.
And one day someone's going to remember to add Media to the list of things to be editable using the block editor.

**Comment by annezazu** [comment]
The content section was removed for 5.9 and it's unclear to me where this work is headed (will the content section return or will this work https://github.com/WordPress/gutenberg/issues/36667 take over?). For now though, this issue is technically no longer applicable! I'm fine keeping it open for now but wanted to share a quick snapshot for future triage efforts.

**Comment by youknowriad** [comment]
yeah let's close this issue. It might become relevant again if we restore "content" in the site editor but it's still very unclear at the moment.
