### ISSUE TITLE
Dead link in Gutenberg Release Process documentation

### ISSUE THREAD

**Issue by ribaricplusplus** [WordPress/gutenberg#30061]
The first link to "gutenberg-core team" is dead on the gutenberg release process docs page: https://developer.wordpress.org/block-editor/contributors/code/release/

The same link is referenced multiple times throughout the page.

I'm not sure if documentation issues are allowed. This issue seemed appropriate because the link is relatively important. I'd fix it myself but I don't know what to link to instead.

**Comment by Soean** [comment]
The link works for me, but only when I am logged into GitHub. I think the link is correct, but the team page is only visible for members of the organization.
I am not sure if it's possible to make this page public, otherwise we have to remove the links.

**Comment by JustinyAhin** [comment]
I agree with @Soean, the team page is displayed for logged in users. When not logged in the link goes to the GitHub login page.

@ntsekouras, is it possible to make the page public?

**Comment by ntsekouras** [comment]
Hey 👋 - I couldn't find any info on making this public. Any ideas of how it could be replaced here @ockham ? I think it would be good enough to write on docs to ping in `#core-editor` in wordpress.slack 🤔

**Comment by mkaz** [comment]
I added a PR to remove the link and suggest to ping in Slack.

A bit unrelated, but I noticed when searching for a list of members that Editor should probably be a project on this [Team Reps page](https://make.wordpress.org/updates/team-reps/) and the team reps added there.
