### ISSUE TITLE
Site Logo Block: The icon color shouldn't be hardcoded

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#30087]
The Site Logo icon's color is hardcoded as black.

https://github.com/WordPress/gutenberg/blob/82054044571f7073010a1aae77e7ee3f0335e5bf/packages/block-library/src/site-logo/icon.js

This is generally fine, but there are cases where it's used against a dark background, and we need to change its color.
See for example the List View, when the block is selected:

<img width="302" alt="Screenshot 2021-03-22 at 11 19 29" src="https://user-images.githubusercontent.com/2070010/111982640-1ba5a200-8b01-11eb-8c9c-5ebe5a9ced72.png">

**Comment by ntsekouras** [comment]
Whoever picks this up, has to fix the line's `stroke` color as well.

**Comment by mtias** [comment]
The icon as a whole should be changed cc @pablohoneyhoney

**Comment by pablohoneyhoney** [comment]
Here two first tries.

<img width="336" alt="site logo2" src="https://user-images.githubusercontent.com/25516611/112224969-74a92f00-8c02-11eb-863a-0fbfd29104bf.png">

<img width="336" alt="site logo" src="https://user-images.githubusercontent.com/25516611/112224972-74a92f00-8c02-11eb-8b78-132be3874bb5.png">

Full disclosure I haven't tried in context, so worth passing that test. Quick design is vailable in the regular open Figma file of icons, on the explorations board. https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8%3A13
