### ISSUE TITLE
stylelint error on 1st line of every CSS/SCSS file

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#30086]
## Description

I've just set up the [@wordpress/stylelint-config/](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-stylelint-config/) package for an existing plugin to lint CSS/SCSS files.

All works well apart from an error which is triggered on the very first line of every single CSS/SCC file. It doesn't matter what the content of the first line is. It can even be a blank file and the error still persists.

Error: `Unknown rule declaration-property-unit-allowed-list.`

## Step-by-step reproduction instructions

1. Install the [@wordpress/stylelint-config/](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-stylelint-config/) package as per the instructions.
2. Install the [stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) VS Code extension.
3. Open a CSS or SCSS file in the editor and view the PROBLEMS panel to display the error: `Unknown rule declaration-property-unit-allowed-list.`

## Expected behaviour

Not to show this unexpected error:  `Unknown rule declaration-property-unit-allowed-list.`

## Actual behaviour

Error is always displayed, even for blank CSS or SCSS files: `Unknown rule declaration-property-unit-allowed-list.`

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/1482075/111977310-7c7dac00-8afa-11eb-930e-46b15a56d202.png)

## WordPress information

n/a.

## Device information
- Device:  Desktop
- Operating system: Windows 10
- Browser:  n/a

**Comment by gziolo** [comment]
`declaration-property-unit-allowed-list` replaced the same rule with a different name in #27810. Have you tried updating `stylelint` to the more recent version?

Gutenberg uses the version `^13.8.0`.

**Comment by dgwyer** [comment]
Brilliant, that fixed it! Thanks for the quick feedback.
