### ISSUE TITLE
register_taxonomy with a non-sequential array index of post_types causes crash

### ISSUE THREAD

**Issue by hyperionjrw** [WordPress/gutenberg#3009]
## Issue Overview

When using register_taxonomy for a taxonomy that is to be shown in REST and to more than one post type the post type array must be sequential and 0 indexed otherwise Gutenberg will fail to load. This came to my attention as a plug-in had popped out an entry from the middle of an array of post_types and left the array with a gap in its sequence.

This seems to be browser independent as it happens in Chrome:61 and FireFox:56. My guess, I've not dug into the code to find the offending article, is that something is being thrown into json_encode without being sanitised first. A sequential 0 indexed array will result in an array in json whereas the other will result in an obj. 

## Steps to Reproduce

This causes crash:
```
register_taxonomy(
    'taxonomy_name',
    array( 0 => 'post', 2 => 'page' ),
    array( 'show_in_rest' => true )
);
```
But this works:
```
register_taxonomy(
    'taxonomy_name',
    array( 0 => 'post', 1=> 'page' ),
    array( 'show_in_rest' => true )
);
```

**Comment by Soean** [comment]
Hey @hyperionjrw, I think this is not an Gutenberg issue.

The error in PostTaxonomies:
`TypeError: taxonomy.types.indexOf is not a function`

The REST API returns an object instead of an array. See Schema: https://developer.wordpress.org/rest-api/reference/taxonomies/
Crash:
```
"types": {
            "0": "post",
            "2": "page"
        },
```
Works:
```
"types": [
            "post",
            "page"
        ],
```


So you should open an trac ticket for core: https://make.wordpress.org/core/reports/

**Comment by aduth** [comment]
Inclined to agree with @Soean . Considering the schema of the taxonomies endpoint as its contract, this is an issue of the REST API not returning the correct type.
