### ISSUE TITLE
Table block: Add controls for font sizes

### ISSUE THREAD

**Issue by davipontesblog** [WordPress/gutenberg#30096]
## What problem does this address?

This adds the ability to control font size options for the block text contents.

## What is your proposed solution?

I propose we add the default font size functionality, as found in the Paragraph, Heading, or Verse blocks, for example:

<img width="276" alt="Screen Shot on 2021-03-22 at 12-53-05" src="https://user-images.githubusercontent.com/31009008/112027616-b7d5a600-8b0d-11eb-9dea-898b61a159ab.png">

**Comment by deborah86** [comment]
I would like to see this too.

**Comment by t-hamano** [comment]
Thanks for the suggestion. Also, sorry for the very late reply.
The table block currently supports all typographies:

- Font Size, Font Style, Font Weight, Letter Spacing, Text Transform: #34064
- Font Family, Text Decoration: #43974

Therefore, I would like to close this issue.
