### ISSUE TITLE
Navigation Component: better connect template preview while hovering

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30108]
## What problem does this address?

Apologies for the title of this issue - feel free to update it. I found this a bit hard to describe concisely. This came up as part of the [third round of testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430): 

>Not clear that template preview (popup) is associated with the template I’m hovering over. Needs additional visual affordance to connect it – https://d.pr/i/B2vE6j/KvrZ4LJbUc

Essentially, right now, the preview shown on hover isn't quite clearly connected enough. Here's a quick video:

https://user-images.githubusercontent.com/26996883/112049744-a55f6a80-8b15-11eb-891f-6bef9c111411.mov

## What is your proposed solution?

I'm not quite sure! The simplest could be having the preview more clearly "follow" as you hover on different templates. I'll leave this to designers :)

**Comment by javierarce** [comment]
My proposal [in this comment](https://github.com/WordPress/gutenberg/issues/30015#issuecomment-811137136) addresses (and hopefully solves) the problem mentioned here.

**Comment by annezazu** [comment]
This last week, a core contributor streamed themselves going through the FSE experience and felt that the previews weren't robust enough. If they aren't robust/accurate enough, it might be better not to have them at all potentially unless work can be done to make them more stable. I wanted to connect this feedback here as more explorations happen for these previews!

**Comment by paaljoachim** [comment]
What about making the previews bigger as right now showing a full page template the contents of it can get very small. Having bigger previews would make these more obvious and easier to notice the details of each template.

**Comment by javierarce** [comment]
Oh, I think that wasn't the original intention of this issue, @paaljoachim, which was just about moving the preview closer to the highlighted element. Maybe a new issue would be more appropriate to discuss your suggestion?

**Comment by paaljoachim** [comment]
Here is a new issue:
Full Site Editing: Bigger and easier to see previews
https://github.com/WordPress/gutenberg/issues/36043

**Comment by jordesign** [comment]
Closing this issue as the template preview is no longer present in the Site Editor browse view as at WP6.3
