### ISSUE TITLE
List View: Add ability to remove items 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30109]
## What problem does this address?

As part of the [third call for testing with the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430), this came up in the feedback:

>Needs power features including a re-order and delete feature for each block.

This was previously discussed here a few years ago https://github.com/WordPress/gutenberg/issues/10984 but List View was determined to be a bit too new at the time to be explored further. It was then subsequently closed out. 

This might be relevant for @priethor as I see you're gathering a list of improvements here: https://github.com/WordPress/gutenberg/issues/29733

## What is your proposed solution?

Allow the ability to remove items from the List View. When considering this, I do want to bring in feedback from the previous discussion from @afercia:

>Multiple actions on a single UI controls are (maybe) a pattern best suited for mobile applications. On the Web, good semantics is key. An Ui control should have only one, clear, available action. From an accessibility perspective, I'm not opposed to explore extending the functionalities available in the Block Navigation menu, but I'd strongly recommend a separate control (another button) to delete a block. Also, when deleting an item, focus must be managed programmatically, as the previously focused element gets removed and focus must land in the most logical place.

**Comment by talldan** [comment]
The block more menu is implemented in list view but inactive currently and that allows deletion - https://github.com/WordPress/gutenberg/pull/22427

When I looked at adding this to the post editor, the accessibility team were concerned about the complexity of grid navigation in List View for users, which is needed if we place a more menu or delete button in the row of the list view item: https://github.com/WordPress/gutenberg/pull/25034#issuecomment-688452447

**Comment by annezazu** [comment]
Ah ha! Thank you for sharing the wider context and concerns around accessibility 🙌🏼

**Comment by carolinan** [comment]
This was also mentioned during user testing on April 9.

**Comment by gwwar** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/35170 props @noisysocks
