### ISSUE TITLE
Ability to select authors has vanished

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3010]
This was reported on the support forums. The ability to change the author of a post has disappeared.

**Comment by iseulde** [comment]
This should probably not be edit context, as we only want to select users, not edit them. https://github.com/WordPress/gutenberg/blob/v1.4.0/editor/sidebar/post-author/index.js#L92

**Comment by aduth** [comment]
Specifically, this appears to be an issue in environments where the user does not have permission to request from:

`/wp-json/wp/v2/users?context=edit`

>This should probably not be edit context, as we only want to select users, not edit them.

This is really only considering the symptom of the problem. Also, the `edit` context adds the `capabilities` property a user entity which we use to determine whether a user should be shown in the dropdown:

https://github.com/WordPress/gutenberg/blob/63cb94275e85f68d3b0c0d216d708018f7017577/editor/sidebar/post-author/index.js#L34-L44

https://github.com/WordPress/WordPress/blob/a1879766ed4e95eab66ac4694aea3a5d4a9c9030/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L1247-L1252

**Comment by iseulde** [comment]
How so, only considering the symptom?

https://github.com/WordPress/wordpress-develop/blob/8cda3a2f550f95d4b52d394a2eb2f7ff6aeae0a3/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L181

**Comment by iseulde** [comment]
Only admins have the `list_users` capability, unless roles are changed by a plugin.

**Comment by aduth** [comment]
I mean in the sense that it didn't offer an explanation to why the issue exists.

With consideration of https://github.com/WordPress/gutenberg/issues/3010#issuecomment-336181834, one could argue this is "working as intended" so far as the REST API intends. Obviously leaves us in a bad situation for building an editor though...

**Comment by iseulde** [comment]
I'm not sure what you mean? This seems to be working as intended indeed, and also for Gutenberg. If you don't have right capabilities, you shouldn't be able to access the users in edit context. They should be retrieved in normal/view content, and be filtered server side. In this case the right approach seems to be removing the context argument and adding the role (author) argument.

https://developer.wordpress.org/rest-api/reference/users/#arguments

**Comment by aduth** [comment]
Role is not sufficient for querying the users which should be included in the dropdown. Related: #2157

**Comment by iseulde** [comment]
You're totally right, somehow I thought that was equivalent to `who` and would show higher roles too. I guess ideally the API should let us query by capability (`publish_posts`)? How about using `role=author,editor,administator`? Also not ideal since plugins could add new roles and change caps.

**Comment by iseulde** [comment]
Well, I guess we should also create a core ticket for it, otherwise it will always stay a hack.

**Comment by iseulde** [comment]
Created https://core.trac.wordpress.org/ticket/42202.

**Comment by aduth** [comment]
Noting that this can also be an issue for sites which have configured plain permalinks. 

Related:

- #3215
- https://core.trac.wordpress.org/ticket/42382

**Comment by bobbingwide** [comment]
### Actual output
This is the Status & Visibility block when permalinks are plain. 
![image](https://user-images.githubusercontent.com/2474435/35194798-2fb4d084-feb1-11e7-9ddb-8d1a8880d403.png)
### Expected output
This is how the Status & Visibility block appears when permalinks are set to post name ( `/%postname%/` ).  
![image](https://user-images.githubusercontent.com/2474435/35194818-7c32e824-feb1-11e7-93d8-f6f52b6af7e1.png)

Note: For the author selection drop down to appear there need to be at least two users with the capability to edit the post. 


### Workaround
- Use pretty permalinks

**Comment by bobbingwide** [comment]
Just to summarise the ability to select Authors based on the editing user's role 

User's role | Classic | Block editor
------------- | -------- | -------------
Contributor | n/a | n/a 
Author | works | 403 response 
Editor | works | 403 response
Administrator | works | works - up to a point- see  below

The response message for the 403 is 

```
{"code":"rest_forbidden_context","message":"Sorry, you are not allowed to list users.","data":{"status":403}}
```

Note: The data in the drop down information has changed. 

Was "display name (username)". Now just "display name".  
![image](https://user-images.githubusercontent.com/2474435/35533348-23b35870-0535-11e8-8ed8-5f2977dd0b7f.png)
![image](https://user-images.githubusercontent.com/2474435/35533565-d866e610-0535-11e8-8488-9ab5e1a31e42.png)

**Comment by danielbachhuber** [comment]
In addition to https://core.trac.wordpress.org/ticket/42202, the underlying problem here is that the REST API limits `GET wp/v2/users?context=edit` to WordPress users with the `list_users` capability.

However... WordPress' UI permits Editors to see other WordPress users when assigning the post author in Edit Post. Furthermore, Contributors and Authors can see (i.e. discover the existence of) other WordPress users in the Manage Posts view.

We can't grant `list_users` to Editors though, because that would expose email addresses where they aren't currently exposed. Unless we decide it's acceptable to do.

I don't have a great suggestion at this point. One idea, which I don't particularly like, is to permit `GET `GET wp/v2/users?context=edit` for all users with `edit_posts`, but nullify the private information (email address, role, etc.) unless they have `list_users` too. Then, furthermore, `capabilities` and other super private information would be nullified unless the user could edit the viewed user.

**Comment by danielbachhuber** [comment]
> I don't have a great suggestion at this point.

With #6515 and #6529, I think we can get away with `GET /wp/v2/users?who=authors&context=view` for our immediate need.

Although, in principle, we should be using `context=edit`, I don't think it makes a difference in practice. Our current alternatives (nullifying values or introducing some `context=admin` with a limited subset of `context=edit` data) are more complex and don't offer any significant benefit.

**Comment by lizkarkoski** [comment]
There's a request to add this feature from the Gutenberg forums:

https://wordpress.org/support/topic/how-to-change-post-author-2/

**Comment by danielbachhuber** [comment]
@lizkarkoski This was already sorted out with Gutenberg, so the forum thread may be a plugin conflict, etc.

**Comment by lizkarkoski** [comment]
Got it. Thank you.

**Comment by rilwis** [comment]
Hey guys,

I see this issue is marked as closed, but I've just trying to create a post in the latest version of WordPress and still don't see any author dropdown? I'm on localhost with admin role.

This is my screenshot:

![](https://i.imgur.com/jGpOupS.png)

**Comment by frafor1988** [comment]
Same issue here. No author dropdown...

**Comment by paulshryock** [comment]
Any traction on this? Still seems like there's no way to change a post author from within the post.
