### ISSUE TITLE
Site Editor - Regression - Alignment styles are broken.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#30112]
## Description

Load the site editor with a block based theme and we will see that items that were center aligned are now pushed up against the left side of the editor regardless of width/alignment setting.

Below we see all post content and blocks aligned up against the left of the editor:

![image](https://user-images.githubusercontent.com/28742426/112059611-6db2eb80-8b32-11eb-9290-2d5ff4641ba9.png)

Below is the spacer block that also was once centered:

![image](https://user-images.githubusercontent.com/28742426/112059644-77d4ea00-8b32-11eb-8ab3-8e45d48859de.png)

This is reproducable with (but not limited to) the tt1-blocks theme.

**Comment by carolinan** [comment]
Please note that TT1 Blocks has not been updated yet to match the alignment changes, so at the point this issue was opened you would expect them not to work.

**Comment by mtias** [comment]
Closing in favor of https://github.com/WordPress/theme-experiments/pull/236

**Comment by Addison-Stavlo** [comment]
> Please note that TT1 Blocks has not been updated yet to match the alignment changes, so at the point this issue was opened you would expect them not to work.

As was the case with all other block based themes I tried.  Curious the reasoning behind adding alignment changes that break all current block based theme implementations requiring them all to be updated individually.
