### ISSUE TITLE
Social Icon: strange behavior when List View is open & trying to add a link

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30120]
## Description

When editing social icons, if you have the List View open, the link control ends up being quite separated out from the block itself:

<img width="1336" alt="Screen Shot 2021-03-22 at 4 26 18 PM" src="https://user-images.githubusercontent.com/26996883/112066078-5a505200-8b2b-11eb-9ee9-9ef6bad0aed8.png">

This came up as part of the [third call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430). 

## Step-by-step reproduction instructions

1. Add the Social Icon Block
2. Open List View
3. Add a new link to the social icon block
4. See the link control separated out from the block itself. 

## Expected behaviour

I expect the link control to be in line with the block I'm editing. 

## Actual behaviour

The link control is all over the place including bleeding into the List View if the block is close by or extending beyond the editor.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/112065824-f9287e80-8b2a-11eb-9b09-5642644c358b.mov

Further, if you move the block closer to the List View, it then bleeds into the List View itself:

<img width="755" alt="Screen Shot 2021-03-22 at 4 27 08 PM" src="https://user-images.githubusercontent.com/26996883/112066188-853aa600-8b2b-11eb-9e10-93a0ac276479.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 88

**Comment by annezazu** [comment]
This is still a problem with 10.6.1:

<img width="922" alt="Screen Shot 2021-05-17 at 1 31 30 PM" src="https://user-images.githubusercontent.com/26996883/118545737-39177680-b714-11eb-889e-d1c5d9724b4a.png">

**Comment by Mamaduka** [comment]
I think this issue was fixed via #32525.
