### ISSUE TITLE
Image Block: Updating after removing width and height results in "This block contains unexpected or invalid content."

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30131]
## Description
If you empty the "Width" and "Height" fields on an image block, update the post and refresh the page, the block gets the "This block contains unexpected or invalid content" notice.

## Step-by-step reproduction instructions
1. Edit or create a post.
2. Insert an image block and upload an image or select one from the media library.
3. Empty the "Width" and "Height" fields in the block settings in the right toolbar.
4. Update the post.
5. Refresh the page, and you get the "This block contains unexpected or invalid content" notice.

## Expected behaviour
The width and height of the image block are reset to their initial values.

## Actual behaviour
The block gets the "This block contains unexpected or invalid content" notice. When you click on "Attempt Block Recovery", update and refresh, the height and width values are reset.

## Screenshots or screen recording (optional)
![block-editor-image-block-bug](https://user-images.githubusercontent.com/8181091/112124756-0002d000-8bc3-11eb-841c-9e27dbeec22c.gif)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested in Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Safari 14.0.3

**Comment by skorasaurus** [comment]
Thanks for reporting and the clear directions to reproduce; confirmed in 10.5.3.

**Comment by Mamaduka** [comment]
Fixed via #32524.
