### ISSUE TITLE
Do not create revisions for the GlobalStyles CustomPostType

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#30132]
We use a CustomPostType to store user data for global styles. The CPT post_type is `global-styles` and the post name is `wp-global-styles-<theme-stylesheet>`.

In https://github.com/WordPress/gutenberg/pull/30088#issuecomment-804508602 @jeyip shared that he was seeing revisions stored for the CPT. 

We're not using these revisions yet, so we should look into how/whether we can prevent them from being created.

## How to test

- Activate the TT1-blocks theme and go to the site editor.
- Update something in the global styles sidebar and save (e.g.: change the root background).
- Go to the database and sort the `wp_posts` table by the `post_modified` field in descending order.
- Verify that the user changes have updated the global styles CTP: `wp-global-styles-tt1-blocks` as `post_name` and that a revision was created as well (post_name along the lines of `<post_type_id_of_global_styles_cpt>-revision-v1`.

**Comment by oandregal** [comment]
Added it to the backlog at https://github.com/WordPress/gutenberg/issues/20331

**Comment by oandregal** [comment]
There's https://github.com/WordPress/gutenberg/pull/30133 to close this.

**Comment by mtias** [comment]
Mmm, even if we are not using them, I don't think we should stop creating them. It'd be nice once we add UI to manage them that they are there already. This is a free rollback feature for the most part.
