### ISSUE TITLE
Navigation mode: strange arrow key behaviour in nested blocks

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#30155]
Create a column block with a paragraph in one of the columns and leave the paragraph selected. Press Esc to enter navigation mode. 

* Arrow up and down don't do anything.
* Arrow right doesn't do anything.
* Arrow left selects the column, which seems reasonable.

Now that the column is selected:

* Arrow down selects the next column... This is strange. I expect something downwards to be selected.
* Arrow right selects the paragraph inside the column. I expect the column to the right to be selected.
* Arrow up doesn't do anything.
* Arrow left selects the columns block, which again seems reasonable.

I would expect navigation mode to work more similarly like edit mode. Maybe we should reuse writing flow to also handle arrow navigation for navigation mode?

**Comment by ellatrix** [comment]
Cc @youknowriad since you know most about navigation mode. :)

**Comment by youknowriad** [comment]
I think the nested behavior was implemented as a v2 by @tellthemachines if I'm not wrong.  For me at least, down and right should work the same and up and left as well because we shouldn't assume container orientation. and I expect like you to first go through the nested blocks before going to the next one.

**Comment by youknowriad** [comment]
Potentially we could leverage "orientation" config to be more precise but not sure if worth the complexity.

**Comment by ellatrix** [comment]
We don't need to look at container orientation if we just reuse the existing logic in writing flow. Instead of moving focus only the block selection would move.

**Comment by youknowriad** [comment]
Navigation mode has been removed.
