### ISSUE TITLE
Navigation Block: make limitations around which blocks can be added clearer

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30159]
## What problem does this address?

Right now, the navigation block has inherent limits to what can be added to it which makes sense. However, the current flow is a bit confusing as it nudges a user to browse all blocks and then doesn't show any indication that only certain blocks can be used:

https://user-images.githubusercontent.com/26996883/112212663-df4a7280-8be2-11eb-8f71-a08e31703934.mov

## What is your proposed solution?

Either the `browse all` option needs to be removed for now or there needs to be some sort of messaging that says only specific blocks can be added. 

This is somewhat related to this other issue around adding some introductory text to better guide a user: https://github.com/WordPress/gutenberg/issues/24007

**Comment by talldan** [comment]
Possibly Browse All shouldn't be shown when the quick inserter already shows all the available options (though it should take into account patterns and reusable blocks).

Just also wanted to mention there's a bug in play here (https://github.com/WordPress/gutenberg/pull/30117). Usually there would be more options available, but the Link block variations aren't working in the screen recording.

**Comment by jasmussen** [comment]
> Possibly Browse All shouldn't be shown when the quick inserter already shows all the available options (though it should take into account patterns and reusable blocks).

That does seem the simplest solution, though an alternative could be a different label. I wonder if just "Browse" would work, or actually make it worse? The point is, it opens the inserter on the left, showing you the available blocks in a different interface.

**Comment by jasmussen** [comment]
I just created #33278 to expand the range of blocks allowed in navigation.

**Comment by jasmussen** [comment]
Coming back to this ticket, a few things feel like they will address this ticket together:

- #34041 defaults to just inserting page links, which will make it vastly simpler to make basic menus.
- The expanded range of blocks allowed (including site logo as well as title) means more items you might intuit to be available, are.
- The introductory text you suggested yourself and [mocked up here](https://github.com/WordPress/gutenberg/issues/24007#issuecomment-916669153) should surface the last bit of context.

**Comment by annezazu** [comment]
Agreed completely. Thanks for looping back. Happy to close this out if you think it's no longer relevant?

**Comment by jasmussen** [comment]
Oh I think it's relevant enough! Just making a note to self that once the three items above are addressed, this one very probably is too.

**Comment by annezazu** [comment]
The UI has come so far since I opened this issue and I find it to be MUCH more intuitive. I'm going to close this out as a result. I also believe the wider work around making blocks more context aware will inherently continue to trickle down into this experience.
