### ISSUE TITLE
Cannot remove logo in Theme Customizer once it's been added

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#30152]
## Description
My guess is this is a core WP issue, but not sure where to post it if it is.  In either case, I've noticed on all sites I have admin access to that are on the latest versions of WP that if you add a custom logo in Theme Customizer, save, then view, the logo is there.  However, if you then open up the customizer menu and remove the logo, the real-time update works, but when you Publish and view the site, the old logo is still there. 

I've been able to replicate this with no plugins and just the default theme installed across multiple different sites.  If I completely delete the logo file from the media, then nothing appears (i.e. not even the text version of the site name).

## Expected behaviour
Should be able to remove logo in Site Identity theme customizer menu.

## Actual behaviour
Somehow the custom_logo is still there regardless if you remove it or not.

## Screenshots or screen recording (optional)
Quick video showing that I add a logo successfully, then try to remove it and save but the logo continues to appear:
https://soapbox.wistia.com/videos/VMOWaROoWo

## WordPress information
- WordPress version: 5.7
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? yes

## Device information
- Device: desktop
- Operating system: iOS
- Browser: Chrome

**Comment by talldan** [comment]
Hi @bradley2083. Thanks for reporting. You're right that this looks like a core issue.

Core trac is the bug tracker for core — https://core.trac.wordpress.org/. It requires a WordPress.org account, which you can create here — https://login.wordpress.org/register.

Would you be happy to create a ticket there?

**Comment by bradhogan** [comment]
Hey, @talldan I've gone ahead and submitted the ticket in the core WP tracker.  Thanks for sharing that!

**Comment by talldan** [comment]
Thanks—I'm just sharing the ticket reference here to connect things together:
https://core.trac.wordpress.org/ticket/52902

**Comment by bradhogan** [comment]
Hey @talldan I just realized this issue only occurs IF the Gutenberg plugin is active.  So I suppose this is an issue with Gutenberg (and not core WP).  Are you able to re-open this ticket?

**Comment by hellofromtonya** [comment]
As @bradley2083 noted, the problem occurs when the Gutenberg plugin is active. I was able to trace it to here:

https://github.com/WordPress/gutenberg/blob/e7369c09f468158e42851ba2a5b1b58efbd4ca88/packages/block-library/src/site-logo/index.php#L76-L81

If the `$custom_logo` is `0` or `'0'`, then updating the `sitelogo` option is skipped. Just above that logic is another callback that defaults to use the `'sitelogo'` option when it exists.

A fix here is to delete the option like this:

```php
function gutenberg_sync_site_logo_to_theme_mod( $custom_logo ) {
	if ( ! empty( $custom_logo ) ) {
		update_option( 'sitelogo', $custom_logo );
	} else {
		delete_option( 'sitelogo', $custom_logo );
	}
	return $custom_logo;
}
```

This issue should be reopened. I'll submit a PR with the above fix.

**Comment by ockham** [comment]
(For xref purposes: Noting here that this issue was a duplicate of sorts of #25173.)
