### ISSUE TITLE
Enhancement: Include Block Type on hover

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30160]
## What problem does this address?

As part of the [third call for testing for the FSE Outreach program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1435), this piece of feedback was shared:

> While trying to build something for the test (but also when I currently use Gutenberg ) I often find myself hovering on the block icon several times, in order to double-check what kind of block I’m interacting with. In this case, the tooltip says “change block type or style”, which makes sense, but doesn’t help in immediately identifying a block type. Has there ever been an option for a visible label near blocks?

<img width="475" alt="Screen Shot 2021-03-23 at 4 44 02 PM" src="https://user-images.githubusercontent.com/26996883/112230001-aec20300-8bf9-11eb-9e2f-1b7fd8594c0f.png">

## What is your proposed solution?

While the block type can be found using List View and Breadcrumbs, it would be great to have the block type be more readily available when you're in the flow of things rather than needing to either open up a new tool or look elsewhere on the screen. Here's my super fancy mockup ;)  to kick things off fully pulling from an idea from @shaunandrews 

<img width="619" alt="Screen Shot 2021-03-23 at 5 14 08 PM" src="https://user-images.githubusercontent.com/26996883/112230834-33f9e780-8bfb-11eb-80cd-63f31adaeaac.png">

This would obviously be cumbersome with longer block titles but hopefully it inspires some ideas:

<img width="609" alt="Screen Shot 2021-03-23 at 5 14 43 PM" src="https://user-images.githubusercontent.com/26996883/112230882-4d029880-8bfb-11eb-9c8b-d5b18ee2fd5b.png">

**Comment by talldan** [comment]
This would also be a nice improvement for screen reader users. I think @ZebulanStanphill has mentioned something similar in the past about the transform menu working a bit like a `<select>` input, but the user has no idea what the current value is.

**Comment by paaljoachim** [comment]
I met the same issue. I was in a block and I was not sure what the name of the block was. Hovering over the "Change block type or style" and having the block name first as you are showing Anne, would be very helpful. The more complex blocks get the more this also would help. 

Btw hovering over the block icon should actually also show the block name. That seems like a given to me. Let's get this in, even though the tooltip will get longer it is very helpful to have the block name mentioned.

Thank you for the issue Anne!

Perhaps @alexstine or @joedolson could give some feedback here.

**Comment by annezazu** [comment]
Can't take credit! All Shaun for the idea :D

**Comment by alexstine** [comment]
I can't really provide much feedback as I'm unaware of what is being discussed. However I am always in favor of more descriptive information both visually and for screen readers. Just have to represent it in a reasonable way. E.g. tooltips/hover probably not going to work for accessibility which may lead to longer but necessary dev time.

Thanks.

**Comment by joedolson** [comment]
Hover only would be a problem, but if it's available on hover & focus, that's OK. 

But I generally agree with @alexstine - any way to show textual information that increases awareness and confidence in the user's current context is a big plus.

**Comment by Mamaduka** [comment]
It looks like a11y improvements were merged as part of #26135.

I can see `aria-label` and description in the Accessibility pane. Tested with VoiceOver tool as well, and best to my knowledge, labels are announced correctly.

I can create PR and update the description label text.
