### ISSUE TITLE
Navigation Block: Sub menu items do not adopt template part color changes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30165]
## Description

If you add the navigation block to a template part and change the template part colors, the sub menu items do not adjust in the same way the overall navigation block does. @carolinan not quite sure if this is possibly a TT1 blocks problem or not!

## Step-by-step reproduction instructions

1. Add a template part
2. Add a navigation block inside template part
3. Add a few menu items including some sub menu items
4. Change the colors of the template part text and background. 
5. Notice the sub menu items do not change color. 

## Expected behaviour

I expect the sub menu items to match the changes I made to the template colors. 

## Actual behaviour

The sub menu items remain at their default state. 

## Screenshots or screen recording (optional)

Editor view:

<img width="1387" alt="Screen Shot 2021-03-23 at 7 04 09 PM" src="https://user-images.githubusercontent.com/26996883/112238586-91496500-8c0a-11eb-94e8-30730ec98742.png">

Front end view:
<img width="922" alt="Screen Shot 2021-03-23 at 7 07 24 PM" src="https://user-images.githubusercontent.com/26996883/112238836-06b53580-8c0b-11eb-82f8-1b634d80a410.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 88

**Comment by carolinan** [comment]
Sub menus are not transparent, they have a white background by default and do not "inherit" the parent block background color.
If they were transparent the menu item would not be readable when it overlapped other content.

Changing the **navigation block** background color will change the sub menu background color.

**Comment by jasmussen** [comment]
Carolina explains it well. 

I have this ticket that might serve as a solution: https://github.com/WordPress/gutenberg/issues/29963

**Comment by annezazu** [comment]
Heh yes! Apologies. I was opening one too many issues yesterday. Transparent wasn't the right word. I saw that ticket as well!

Should this be closed? It's unclear to me what's expected but the current experience is a bit frustrating regardless.

**Comment by jasmussen** [comment]
> Should this be closed?

The same PR will fix both tickets. But this one perhaps has better SEO :) So it has value for people searching. But that may be the case whether open or closed.

**Comment by carolinan** [comment]
Hi, can this be closed?

**Comment by annezazu** [comment]
Looks like it :) Closing.
