### ISSUE TITLE
Blocks that link: Provide a split label/URL control and placeholder state

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30170]
## What problem does this address?

Splitting this one out from, and basing the design on https://github.com/WordPress/gutenberg/issues/28440.

When you insert a link block such as a Menu Item or a Button (to a lesser extent, a Social Link), for the block to be functional it needs to have _both a URL_ and a _label_ configured. At the moment, this happens in a single link dialog interface.

If you type arbitrary text, you are meant to be searching for a page or post that you can choose from the dropdown, or create a draft with that title. For example if you type "WordPress", if you just press Enter, you will create a menu item labelled "WordPress" which links to `WordPress`:

![title alt](https://user-images.githubusercontent.com/1204802/112126180-7bb14c80-8bc4-11eb-92ac-9d5114bbb43d.gif)

But if you use the arrow keys to highlight an existing page, the input field will become the label, and the selected item will become the URL.

![title](https://user-images.githubusercontent.com/1204802/112126241-8b309580-8bc4-11eb-914e-e5819bbb5ec1.gif)

If you just paste a hyperlink and press Enter, you get a link item that correctly links to that hyperlink, and with a label that's an "educated guess" based on the URL, but still not a good label:

![link](https://user-images.githubusercontent.com/1204802/112126537-d3e84e80-8bc4-11eb-91fe-696941c87052.gif)

In other words, the same input field is used to provide both a label and a link destination, but it's not consistent which one you get. This is causing a number of headaches:

- An "add link" prompt, when in fact it's the label that's missing: https://github.com/WordPress/gutenberg/issues/30163
- We're not sure when/how to HTML encode entities and when not to: https://github.com/WordPress/gutenberg/issues/30111
- Mostly, and this was a key reason for adding the menu item placeholder (#28440) in the first place, a button with a label but no link, or link but no label, is quite useless. 

## What is your proposed solution?

Keep button blocks, menu items, social links in their placeholder states until both a URL and a link has been added, and split the link dialog to enable it.

These designs are courtesy of @shaunandrews from https://github.com/WordPress/gutenberg/issues/28440#issuecomment-767803476:

**Adding a Link**

https://user-images.githubusercontent.com/191598/105900359-ec375500-5fe9-11eb-81fd-0bfbdd70e1f8.mp4

**Adding a Page Link**

https://user-images.githubusercontent.com/191598/105900398-fa857100-5fe9-11eb-8c9e-586c104fe4b2.mp4

See also: 

https://github.com/WordPress/gutenberg/issues/29505
https://github.com/WordPress/gutenberg/issues/30116

**Comment by jasmussen** [comment]
Here are some fresher mockups for how a split URL/Label dialog could look.

<img width="2263" alt="Setup states   appenders" src="https://user-images.githubusercontent.com/1204802/123941459-766d5600-d99a-11eb-8968-7b032c655976.png">

**Comment by getdave** [comment]
@jasmussen I found a PR I worked on which tackled this very concept 

https://github.com/WordPress/gutenberg/pull/19413

**Comment by jasmussen** [comment]
I'd be happy to pair with you on a resurrection of this one!

**Comment by getdave** [comment]
💯 lets do it!

**Comment by jasmussen** [comment]
Per conversation in https://github.com/WordPress/gutenberg/pull/33849#issuecomment-892478325, I explored a few additional designs for split label/URL dialogs. The following remains a work in progress, there are some details that need to be hashed out. 

1. For page links, show an explicit "select page" button, which slides the contents sideways to show the list of pages as a screen 2 choice:
<img width="1952" alt="With Select Page button" src="https://user-images.githubusercontent.com/1204802/128681564-0e0147c7-6ff3-4320-8c1b-afcc6259b8cb.png">

This is meant to be a future exploration that will be dependant on components from [the global styles work](https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866) to land first.

2. Text, link and "recently updated" list of results:

<img width="988" alt="With suggestions" src="https://user-images.githubusercontent.com/1204802/128681841-a4dd8f40-7789-4ffd-bf42-904b5cc0afee.png">

This is mostly a small refresh of the work in progress in #33849. It feels a bit heavy.

3. A minimal version that only shows search results when you start typing:

<img width="988" alt="Minimal" src="https://user-images.githubusercontent.com/1204802/128681749-23021b95-89a5-408f-9860-4a124a624e8b.png">

Things we likely need to discuss in order to move forward on one of these is:

- What is the value of keeping an identical URL dialog across pages, custom links? As a reminder, [this mockup shows how the dialog could adapt to its context](https://github.com/WordPress/gutenberg/issues/30170#issuecomment-871263693).
- How valuable are the "recently updated" suggestions? At the moment they aren't contextual to the block type, and I find they don't change that often and therefore have somewhat dubious value.

**Comment by getdave** [comment]
Good to see this evolving. I'm keen to progress https://github.com/WordPress/gutenberg/pull/33849 so please do let me know if/when I can do that.

> 1. For page links, show an explicit "select page" button, which slides the contents sideways to show the list of pages as a screen 2 choice:

This is great if you don't remember the page name but less optimal if you do (when search really shines). Have you seen @javierarce's exploration with [bulk adding of links](https://github.com/WordPress/gutenberg/issues/31667#issuecomment-887526463)?

> Text, link and "recently updated" list of results:

This is the simplest "next step" towards improving the link editing UI across the editor. We can always ditch the "Recently updated" or at least toggle the default prop so it's off by default.

> What is the value of keeping an identical URL dialog across pages, custom links? 

I'd say simplicity. Once you've learnt one UI you've learnt it. Whilst I think we as regular contributors will adapt quickly to varying UIs based on context ,I'm not so sure users will feel the same. See for example the UX problems with the different variations in the Nav Link block where users now need to understand the difference between a Post and a Page in order to add a link. We _should_ be able to construct a UI that does the 80% of cases and provide other mechanics to ease the UX for those who require the 20%.

> How valuable are the "recently updated" suggestions? At the moment they aren't contextual to the block type, and I find they don't change that often and therefore have somewhat dubious value.

I doubt they are that useful. They were added when I originally created the `<LinkControl>` component but there's been a lot of water under the bridge since then. Honestly I suspect most folk would just search and ignore those items.

**Comment by jasmussen** [comment]
> This is great if you don't remember the page name but less optimal if you do (when search really shines). Have you seen @javierarce's exploration with bulk adding of links?

Very nice work. I'd prefer to avoid tabs here, and keep the dropdown fairly compressed if we can. Just as an experiment:

<img width="603" alt="Screenshot 2021-08-10 at 15 19 42" src="https://user-images.githubusercontent.com/1204802/128874142-02085cda-210e-45c4-aca7-9ae97ab5cd4a.png">

> I'd say simplicity. Once you've learnt one UI you've learnt it. Whilst I think we as regular contributors will adapt quickly to varying UIs based on context ,I'm not so sure users will feel the same. See for example the UX problems with the different variations in the Nav Link block where users now need to understand the difference between a Post and a Page in order to add a link. We should be able to construct a UI that does the 80% of cases and provide other mechanics to ease the UX for those who require the 20%.

Good argument. However I do feel like the fact that everything just becomes generic URLs might do a disservice to the taxonomies we know of, like tags, categories, pages, etc., as well as the leaner way we can potentially display those. @shaunandrews since you basically originated the design ideas in https://github.com/WordPress/gutenberg/issues/28440, do you have any thoughts to add?

> I doubt they are that useful. They were added when I originally created the <LinkControl> component but there's been a lot of water under the bridge since then. Honestly I suspect most folk would just search and ignore those items.

👍 👍

**Comment by getdave** [comment]
> the fact that everything just becomes generic URLs might do a disservice to the taxonomies we know of

Let's say for arguments sake we were able to retain the "taxonomy" part once the link is added (ie: we don't just use the URL) would that help?

I also dislike this behaviour although it's different in Nav Block vs in RichText.

**Comment by jasmussen** [comment]
I think we may be arguing in favor of the same thing. Basically that _most of the behavior of the box_ is identical across rich text and any block that might link to destinations, but just that the _destination interface_ might be optimized for each type. Sort of like this somewhat simplified version:

<img width="1237" alt="Screenshot 2021-08-10 at 15 51 01" src="https://user-images.githubusercontent.com/1204802/128879128-1dc8a94e-87b7-4316-9afe-f9be6154982d.png">

**Comment by jasmussen** [comment]
An important conversation about a more basic menu building experience is happening in #34041. Mockups to address that show [a simpler URL picker as part of that flow](https://github.com/WordPress/gutenberg/issues/34041#issuecomment-919934521):

<img src="https://user-images.githubusercontent.com/1204802/133423715-8c247334-5437-44ed-a2a1-c4300ce10890.png">

While putting those together, it became clear that when you link to pages on your site, choosing the page and adopting its title is the primary action. However the split title/link dialog might still be useful after the fact:

<img width="2680" alt="split dialog" src="https://user-images.githubusercontent.com/1204802/133425671-aa4f9889-db31-4be6-a28c-e8cdcd680861.png">

This dialog already exists — you get it when you press the Link button on a menu item. But the above overhauls it slightly to include the split title/link interface. By showing the ability to edit the label in context of _unlinking_ the item, if paired with #33091, we can enable pattern designers to create opinionated menu patterns that come with predefined label suggestions, but which don't link anywhere.

Consider that patterns already exist which output Buttons that have labels:

<img width="1436" alt="Screenshot 2021-09-15 at 13 37 26" src="https://user-images.githubusercontent.com/1204802/133426436-ec2f7ff1-8be3-42ba-8dff-cf5eccbba631.png">

"Learn more" in the above screenshot doesn't link anywhere, but it's not easy to notice. The navigation block implements a "squiggly underline" pattern to indicate that _the link is missing_. In that vein, the squiggly line paired with a unified split dialog which opened on links or buttons that have labels but don't link anywhere, we would be embracing the ability to create such patterns, and hopefully lower the likelyhood of users accidentally publishing dead links.

**Comment by getdave** [comment]
@jasmussen Thanks for the update. Looking good ❤️ 

Can I confirm you're proposing redoing the design of the Link UI across Gutenberg to use this new layout (which also happens to utilise split text/URL)?

If so I'd be in favour of this. We should probably account for "Rich URL Previews" in the designs however.

In terms of the custom "Page" dropdown version - do you see this a unique to the Nav block? `<LinkControl>` has some ability to be extended to accommodate different designs of suggestions, but I wonder whether if we're going to start stretching this component we ought to revisit it at a more fundamental level? It's starting to grow fairly complex, partially due to the reliance on `<URLInput>`, and I wonder whether we should consider re-writing before we add yet more complexity to the existing component.

That's longer term though - in terms of the new design you propose we should proceed.

**Comment by jasmussen** [comment]
> Can I confirm you're proposing redoing the design of the Link UI across Gutenberg to use this new layout (which also happens to utilise split text/URL)?

Yes, from exploring the mockups further, that seems to be the right interface for the split dialog.

> If so I'd be in favour of this. We should probably account for "Rich URL Previews" in the designs however.

Definitely, and in fact it might be worth lowering the priority of this one. It seems a good enhancement, but by virtue of being secondary, it seems less urgent. 

> In terms of the custom "Page" dropdown version - do you see this a unique to the Nav block? <LinkControl> has some ability to be extended to accommodate different designs of suggestions, but I wonder whether if we're going to start stretching this component we ought to revisit it at a more fundamental level? It's starting to grow fairly complex, partially due to the reliance on <URLInput>, and I wonder whether we should consider re-writing before we add yet more complexity to the existing component.

The proposal for the lighter navigation in #34041 is to add a feature to the inserter where if the parent block has a default block defined, the plus inserts that, and adds a "Transform" option to the bottom of the URL dialog. At the moment this feature is definitely inspired by the navigation block, but I could see it making sense in other container blocks as well.

The second half of the equation is whether to show a generic "Recently updated" list of items in the URL dialog across all links, or whether to tailor it to each item type. I think the answer here depends on how much effort we want to put into it. At a minimum I think there's notable value in having a _page selector_ in addition to the default "recent items" filter. But the idea is that if you insert a category link, a suggestion of recent posts published isn't that useful. Here's a mockup just putting the puzzle pieces on the table:

<img width="2080" alt="URL dialogs" src="https://user-images.githubusercontent.com/1204802/133583080-6218219e-3605-4fe6-bbc2-5675a494a95e.png">

We still need to piece them together to form a compelling picture. But the idea is to filter the labels and queries based on the block type inserted.
