### ISSUE TITLE
FSE: theme data for Global Styles and Templates

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#30191]
We are storing templates and template parts in `wp_template` and `wp_template_parts` CPTs respectively. In order to associate them with their corresponding themes, we added `wp_theme` taxonomy in which the theme stylesheet is saved for each post. ([ref](https://github.com/WordPress/gutenberg/blob/da8555d258edbe676fa079fb51252f918ae032e1/lib/full-site-editing/templates.php#L86))

For storing Global Styles data, we similarly have `global_styles` CPT, but the corresponding theme info is saved in the post name (`wp-global-styles-<theme-stylesheet>`). ([ref](https://github.com/WordPress/gutenberg/blob/f79664c0125516438bb4eca17bec2c829d021dbc/lib/class-wp-theme-json-resolver.php#L346))

Would it make sense to align these approaches for consistency? 

cc @nosolosw @mtias @youknowriad

**Comment by oandregal** [comment]
I've added this to the list of things to do for 5.8 at https://github.com/WordPress/gutenberg/issues/20331 (see 3rd wave, theme.json group).

**Comment by oandregal** [comment]
This has been closed by https://github.com/WordPress/gutenberg/pull/31436
