### ISSUE TITLE
Use modal to manage templates, reusable blocks, patterns etc

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30192]
I have made a few different issues that are related to managing reusable blocks and patterns. 

I believe we should have a common UX method to edit/manage be it templates, reusable blocks, patterns etc.

Using one big modal. Associated PR: 
Add a full screen modal component
https://github.com/WordPress/gutenberg/pull/28574

**Here are some examples. These leave some breathing space outside the modal so the user still feels connected to the screen behind the modal.**

Manage Reusable blocks without leaving Gutenberg
https://github.com/WordPress/gutenberg/issues/26408

Inserter: Expand view to view patterns in a larger overlay.
https://github.com/WordPress/gutenberg/issues/26905

Rethinking the design of the Revisions Panel
https://github.com/WordPress/gutenberg/issues/25270

**Comment by mtias** [comment]
Closing as this is covered by other issues.
