### ISSUE TITLE
Gallery block refactor: Adding captions in the Select og Upload Media screen does not show caption in gallery

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30196]
https://make.wordpress.org/core/2021/03/23/gallery-block-update-call-for-testing/

@glendaviesnz 

## Description
Adding caption to images during the Create or "Select or Upload Media" will not show the caption in the gallery.

## Step-by-step reproduction instructions

1. Use the new Gallery block.
2. Create a Gallery and add some captions.
3. Captions not seen in the Gutenberg layout screen or in the frontend.

## Expected behaviour
I expected to see the caption added.

## Actual behaviour
No captions seen.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5323259/112337493-3ec98080-8cbe-11eb-98f7-82506169b419.mp4

## WordPress information
- WordPress version: 5.7
- Downloaded the special Gutenberg plugin that contains the new Gallery PR.
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

Using Chrome.
A local site.

**Comment by glendaviesnz** [comment]
fixed by https://github.com/WordPress/gutenberg/pull/30784
