### ISSUE TITLE
Navigation Block: Unable to edit block after adding & removing blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30201]
## Description

If you start from an empty navigation block and quickly add & remove a page list block you are unable to then edit the navigation block further. This seems somewhat similar to this bug: https://github.com/WordPress/gutenberg/issues/29237 

## Step-by-step reproduction instructions

1. Add a Navigation Block.
2. Start empty. 
3. Add a Page List block
4. Remove the same block.
5. Try to edit the Navigation Block and find you can't.
6. Open List View > select Navigation Block and find you then can! 🙃 

You can also go through the same steps by adding and removing a Link Block to replicate. 

## Expected behaviour

I expect to still be able to edit the Navigation Block.

## Actual behaviour

I'm unable to edit the Navigation Block unless, for some reason,  I open List View and select the block once more.

## Screenshots or screen recording (optional)

This video just shows the problem with the Page Link Block but this also occurs with the Link Block.

https://user-images.githubusercontent.com/26996883/112347801-cd250e80-8c8c-11eb-921a-bf0321bc3219.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 88

**Comment by ntsekouras** [comment]
Hey @annezazu - I couldn't reproduce this.. 🤔 . I even tried with `Navigation` in `Columns` and `Template Parts` like your video. Is this still happening for you?

**Comment by annezazu** [comment]
@ntsekouras Yes! Just replicated again this morning. Are you using the latest from trunk though? Right now, my test site is still using 10.2.1 so you might have a more up to date snapshot. I need to reset my local site after running into a larger FSE issue 😬

**Comment by ntsekouras** [comment]
>Are you using the latest from trunk though?

Yes 😄

**Comment by annezazu** [comment]
Awesome :D Let me close this out in that case and I can re-open if it happens again with future calls for testing.
