### ISSUE TITLE
wp-env: start --update fails on `pecl install xdebug`

### ISSUE THREAD

**Issue by tlindig** [WordPress/gutenberg#30213]
every update of an existing docker wordpress image fails.
wp-env 4.0.0

Error message:
```
Service 'wordpress' failed to build: The command '/bin/sh -c apt-get -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug' returned a non-zero code: 1
```
the problem is `pecl install xdebug`. if it does not install a new version, it fails with error code 1. 

I checked it in the docker container:
```
$ docker exec -it 32a15c70fb72 bash
root@32a15c70fb72:/var/www/html# pecl install xdebug
pecl/xdebug is already installed and is the same as the released version 3.0.3
install failed
root@32a15c70fb72:/var/www/html# echo $?
1
```
that will break this:

https://github.com/WordPress/gutenberg/blob/trunk/packages/env/lib/init-config.js#L110
```
RUN apt-get -qy install $PHPIZE_DEPS \\
	&& pecl install xdebug \\
	&& docker-php-ext-enable xdebug
```

**More details:**
My System: 
Kernel: 5.8.0-48-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6, wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal  

I created a new block project with:
```
npx @wordpress/create-block my-block
cd my-block/
npm run build
npm i @wordpress/env --save-dev
```
add script target to package.json
```
"wp-env": "WP_ENV_HOME='wp-env-home' wp-env"
```

first run of wp-env, it downloads xdebug, and the build will successful finished.
```
npm run wp-env -- start --debug
```

```
Step 2/6 : RUN apt-get -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug
 ---> Running in 663555919e33
⠏ Starting WordPress.Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-11).
dpkg-dev is already the newest version (1.19.7).
file is already the newest version (1:5.35-4+deb10u2).
g++ is already the newest version (4:8.3.0-1).
gcc is already the newest version (4:8.3.0-1).
libc6-dev is already the newest version (2.28-10).
make is already the newest version (4.2.1-1.2).
pkg-config is already the newest version (0.29-6).
re2c is already the newest version (1.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
⠦ Starting WordPress.downloading xdebug-3.0.3.tgz ...
Starting to download xdebug-3.0.3.tgz (215,952 bytes)
```

start and stop works fine. 

But first run with `--update` or `--xdebug` or what ever trigger the update of the image will fail.

```
npm run wp-env -- start --update --debug
```
or
```
npm run wp-env -- start --xdebug --debug
```

```
Step 2/6 : RUN apt-get -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug
 ---> Running in 069dd240350b
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-11).
dpkg-dev is already the newest version (1.19.7).
file is already the newest version (1:5.35-4+deb10u2).
g++ is already the newest version (4:8.3.0-1).
gcc is already the newest version (4:8.3.0-1).
libc6-dev is already the newest version (2.28-10).
make is already the newest version (4.2.1-1.2).
pkg-config is already the newest version (0.29-6).
re2c is already the newest version (1.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pecl/xdebug is already installed and is the same as the released version 3.0.3
install failed
Building wordpress
Service 'wordpress' failed to build: The command '/bin/sh -c apt-get -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug' returned a non-zero code: 1
```

only if I remove the last docker image, so that pecl will download xdebug again, it could be finished successful again. 

Possible Fix:

If I change the  init-config.js so content of Dockerfile is changed, it works also fine. I am not a bash expert, so I do not know, if it is a secure solution, but adding `|| true` works:
```
RUN apt-get -qy install $PHPIZE_DEPS \\
	&& pecl install xdebug || true \\
	&& docker-php-ext-enable xdebug
```
I am not sure what the `||` does in bash, if `&&` has higher priority or whether brackets helps.

**Comment by tlindig** [comment]
I find out, the problem is the docker-compose 1.25.0-1, the default version in debian package from Ubuntu 20.04

With new docker-compose version 1.28.6 all things run fine.

**Comment by brylie** [comment]
Specifying the `phpVersion` as `"7.2"` resolved this issue for me.

```json
{
    "core": null,
    "phpVersion": "7.2",
    "plugins": [],
    "themes": []
}
```

**Comment by brylie** [comment]
However, rebuilding the exact image fails with the initial error.

I have opened issue https://github.com/WordPress/gutenberg/issues/34320 to indicate this is a recurring issue when changing the project configuration in `.wp-env.json`
