### ISSUE TITLE
Add input with save button

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30215]
## What problem does this address?

In Navigation Editor, when a menu name is changed, a user needs to hit the `save` button in order to apply the change. This is not obvious action and is not UX-friendly. 

## What is your proposed solution?

As proposed by @shaunandrews we can add a component with a save button inside an input. This will make a saving action more straightforward.
![image](https://user-images.githubusercontent.com/8398557/112391688-95ec4700-8cf8-11eb-9a4b-005fdd6b539e.png)

**Comment by paaljoachim** [comment]
What about adding in a button that says save?

**Comment by grzim** [comment]
@paaljoachim currently we have a `save` button that saves configuration from the navbar.
However, as mentioned in [comment](https://github.com/WordPress/gutenberg/pull/29012#issuecomment-785308585), it is not obvious for a user, they need to click on `save` therefore it would be better to introduce this component.

But on the other hand, we would end up in the situation, when only menu rename has its own button to save, whereas the rest of the config in the same area is saved all with one button. 
This could lead to confusion as well. 

@shaunandrews I will be grateful if you can share your thoughts on this.

**Comment by talldan** [comment]
I noticed there's one just like this in the LinkControl component when editing a link:
<img width="380" alt="Screenshot 2021-03-26 at 9 10 20 am" src="https://user-images.githubusercontent.com/677833/112562840-320a7100-8e13-11eb-9c4c-08ccfb9c3f34.png">

But it doesn't look particularly easy to extract this into a general purpose component. There's quite a bit going on.

**Comment by shaunandrews** [comment]
I think if we improve our handling of unsaved changes as outlined in #30322 we won't need to have a discrete save button for the menu name.

**Comment by grzim** [comment]
Thanks for your feedback @shaunandrews
