### ISSUE TITLE
Custom Posts without Support for Title Crash the Visual Editor

### ISSUE THREAD

**Issue by clwill** [WordPress/gutenberg#30214]
## Description
Custom post type with supports array that does NOT include 'title' crashes the editor in 5.7. 

## Step-by-step reproduction instructions
`register_post_type` with args that includes

        'supports'				=> array('editor', 'thumbnail', 'excerpt')

but notably does not include 'title' will crash the editor when creating a new post of that type. New post is created into the visual editor, but any click on the editor will produce

    the editor has encountered an unexpected error.

and exit. If you add 'title' to the supports arguments it doesn't crash.

## Expected behaviour
This worked fine in 5.6.2.

## Actual behaviour
Editor gives 'the editor has encountered an unexpected error.'

## Code snippet (optional)
The javascript debugger shows this error stream:

```
[Error] TypeError: null is not an object (evaluating 'ref.current.ownerDocument')
	(anonymous function) (editor.js:11734)
	commitHookEffectListMount (react-dom.js:19866)
	commitPassiveHookEffects (react-dom.js:19904)
	callCallback (react-dom.js:182)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.js:231)
	invokeGuardedCallback (react-dom.js:286)
	flushPassiveEffectsImpl (react-dom.js:22988)
	unstable_runWithPriority (react.js:2685)
	performSyncWorkOnRoot (react-dom.js:21872)
	performSyncWorkOnRoot
	(anonymous function) (react-dom.js:11224)
	unstable_runWithPriority (react.js:2685)
	flushSyncCallbackQueueImpl (react-dom.js:11219)
	flushSyncCallbackQueue (react-dom.js:11207)
	flushPendingDiscreteUpdates (react-dom.js:21982)
	flushDiscreteUpdates (react-dom.js:21962)
	flushDiscreteUpdatesIfNeeded (react-dom.js:826)
	dispatchDiscreteEvent (react-dom.js:4290)
	dispatchDiscreteEvent
[Error] The above error occurred in the <PostTitle> component:
    in PostTitle (created by VisualEditor)
    in div (created by VisualEditor)
    in div (created by WritingFlow)
    in WritingFlow (created by VisualEditor)
    in div (created by VisualEditor)
    in div (created by VisualEditor)
    in VisualEditor (created by Layout)
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in ForwardRef(InterfaceSkeleton) (created by Layout)
    in Layout (created by Editor)
    in ErrorBoundary (created by Editor)
    in BlockEditorProvider
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(BlockEditorProvider) (created by EditorProvider)
    in BlockContextProvider (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EditorProvider
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(EditorProvider) (created by Editor)
    in DropZoneContextProvider (created by Editor)
    in slot_fill_provider_SlotFillProvider (created by SlotFillProvider)
    in SlotFillProvider (created by Editor)
    in StrictMode (created by Editor)
    in Editor

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
	logCapturedError (react-dom.js:19662)
	logError (react-dom.js:19699)
	callback (react-dom.js:20879)
	callCallback (react-dom.js:12625)
	commitUpdateQueue (react-dom.js:12646)
	commitLifeCycles (react-dom.js:19993)
	commitLayoutEffects (react-dom.js:22938)
	callCallback (react-dom.js:182)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.js:231)
	invokeGuardedCallback (react-dom.js:286)
	commitRootImpl (react-dom.js:22676)
	commitRootImpl
	unstable_runWithPriority (react.js:2685)
	commitRoot (react-dom.js:22516)
	finishSyncRender (react-dom.js:21942)
	performSyncWorkOnRoot (react-dom.js:21928)
	performSyncWorkOnRoot
	(anonymous function) (react-dom.js:11224)
	unstable_runWithPriority (react.js:2685)
	flushSyncCallbackQueueImpl (react-dom.js:11219)
	flushSyncCallbackQueue (react-dom.js:11207)
	flushPendingDiscreteUpdates (react-dom.js:21982)
	flushDiscreteUpdates (react-dom.js:21962)
	flushDiscreteUpdatesIfNeeded (react-dom.js:826)
	dispatchDiscreteEvent (react-dom.js:4290)
	dispatchDiscreteEvent

```

## WordPress information
- WordPress version: 5.7
- Gutenberg version: ?
- Are all plugins except Gutenberg deactivated? Tested with and without. No change.
- Are you using a default theme (e.g. Twenty Twenty-One)? No.

## Device information
- Device: Desktop
- Operating system: MacOS 10.15.7
- Browser: Tested in Firefox, Chrome, Safari. Same results.

**Comment by skorasaurus** [comment]
Confirmed; I'm able to reproduce this using WordPress nightly and Gutenberg 10.2.1

**Comment by skorasaurus** [comment]
This appears to have been fixed; I'm not able to reproduce this in the latest build of Gutenberg from the trunk branch yesterday. You can download the latest version of gutenberg at https://gutenbergtimes.com/need-a-zip-from-master/#nightly

(I think the PR that fixed this was https://github.com/WordPress/gutenberg/pull/29922

**Comment by skorasaurus** [comment]
Please reopen if you are still experiencing this with the nightly version. The fix should be in the next release of the gutenberg plugin.

**Comment by clwill** [comment]
Thank you, this nightly does appear to fix it. Any idea when this will be rolled into WP proper? I don't know how that part works...

Thanks!

**Comment by barryceelen** [comment]
Seeing a related issue for posts without title support. (Note that we're creating a title based on other fields)

- Title not used in preview

Got around this issue by adding title support when registering the post type if `is_preview()`.

- Title not used in the editor sidebar confirmation after publishing. The notification says "(no title) is now live.", even though the post has a title.

Used to be able to get around this issue by adding title support if `! is_admin()`. Adding title support if `! is_admin()` now causes the error mentioned above.
