### ISSUE TITLE
Feedback: Resetting global styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30226]
During a contributor day on February 5 2021, one of the tasks were to reset the styles in the global styles sidebar in the site editor.

User feedback included:
- When clicking the reset styles button, there needs to be a confirmation before resetting.
- It is difficult to see the style reset text
- The reset button is too close to the button that closes the sidebar, it is easy to click on it by mistake. The button could be placed at the bottom of the sidebar instead.

A screenshot for reference:
![The reset to default button has a very small text size, looks like plain text and is positioned close to the close button ](https://user-images.githubusercontent.com/7422055/112451208-87804880-8d55-11eb-9b6c-68c748aa9686.png)

**Comment by mtias** [comment]
Regarding the placement, the latest round of design concepts is placing these "meta" tasks (also things like revisions, etc) in the bottom of the panel:

![image](https://user-images.githubusercontent.com/548849/112629254-59256a80-8e34-11eb-85e8-bbdc28bcd58a.png)

**Comment by mtias** [comment]
The reset action is now in the ellipsis menu at the top.
