### ISSUE TITLE
Navigation Block: Make initial configuration state look more like buttons

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30257]
## What problem does this address?

As part of the [third call for testing for the FSE Outreach program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430), this piece of feedback was shared: 

>the two placeholder options don’t look like call to action buttons elsewhere in the UI. I understand they need to be in keeping with the Nav items style but it wasn’t clear they were options without actually reading the text. Could we improve this?

Specifically, these setup options:

<img width="625" alt="Screen Shot 2021-03-23 at 09 20 12" src="https://user-images.githubusercontent.com/26996883/112532369-5b24f600-8d6e-11eb-8fbb-de38fbbfb731.png">

## What is your proposed solution?

Inspired by the Query block, here's a very quick and poor mockup 😅  in hopes it gets someone else thinking about this!

Query Block:

<img width="994" alt="Screen Shot 2021-03-25 at 1 41 11 PM" src="https://user-images.githubusercontent.com/26996883/112533683-d4711880-8d6f-11eb-8c84-b168ecdc8e6e.png">

Navigation Block idea:

<img width="622" alt="Screen Shot 2021-03-25 at 1 41 00 PM" src="https://user-images.githubusercontent.com/26996883/112533685-d509af00-8d6f-11eb-8113-634643832a7b.png">

cc @jasmussen as we've talked about placeholders across various issues!

**Comment by jasmussen** [comment]
Good ticket, thank you.

It is quite important for page templates that the initial setup state for the navigation block is _not_ tall, like those of the Query or Image block. Consider that it may be pre-inserted in a Header template, and if it were large, it would [break the layout](https://github.com/WordPress/gutenberg/issues/20853#issuecomment-621030013).

In https://github.com/WordPress/gutenberg/pull/30281 I created an alternative that adds a block label, and more actionable buttons.

**Comment by annezazu** [comment]
Love your iteration!
