### ISSUE TITLE
Gallery block refactor: Image styles should persist when added to a Group block

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#30250]
## Description
I added a few headshots to a gallery and turned the first row into round images, using the default block styles. 
Then I added the gallery to a group block and on that action the image styles went back to default. (not round) 
The screenshot shows the result of what I tried to do. At the bottom you see the nested breadcrumbs. 
![Screen Shot 2021-03-25 at 10 48 58 AM](https://user-images.githubusercontent.com/39980/112492947-18f0ba00-8d58-11eb-84cb-03fc2c3f17e5.png)

Document > Group > Gallery > Image

## Step-by-step reproduction instructions

1. Create a new gallery
2. add a few images
3. select an image and set it to "Rounded" from the Image styles in the sidebar
4. Got to the Gallery Block's toolbar 
5. Select from the 3-dot menu "Group" 
6. You'll see your image to turn back to the default style. 

Here is a video. (you only need to watch the frist 24 seconds... :-)

https://user-images.githubusercontent.com/39980/112494081-1c387580-8d59-11eb-81f8-e2cb933adb1d.mp4

## Expected behavior
I expected that my choice of block style for a particular image persists. 

## Actual behaviour
I had to do the settings again after add it to a group block. 

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Zip from Call for Test ([PR Refactor](https://glendaviesnz.files.wordpress.com/2021/03/gutenberg-gallery-refactor-1.zip)) 
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes Twenty-Twenty-one

## Device information
- Device: Desktop
- Operating system: MacOS 10.15.7
- Browser: Chrome Version 89.0.4389.90

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/31068
