### ISSUE TITLE
Adding blocks by pressing enter removes `__internalWidgetId`

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#30268]
Adding blocks by pressing enter made the content of the starting block disappear from the preview.

https://user-images.githubusercontent.com/107534/112444902-36715400-8d57-11eb-8681-299832031e22.mp4

_Originally posted by @draganescu in https://github.com/WordPress/gutenberg/pull/30221#issuecomment-806462827_

Inspecting into the nextBlocks, it turns out that `__internalWidgetId` got removed when pressing Enter.

**Comment by noisysocks** [comment]
Closing as fixed by #30399.
