### ISSUE TITLE
Gallery block refactor: Copy "alt" text from media library when adding images

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#30263]
## What problem does this address?
The refactored gallery currently does not copy the `alt` text from the media library when adding images. It might help to avoid repetitive typing if we can provide this.

## What is your proposed solution?
There might be two approaches here:
- When adding images via the media library, copy their alt text 
- Provide a setting at the gallery level that would allow the user to choose whether that alt text is copied into the gallery

**Comment by aaronrobertshaw** [comment]
Thank for the suggestion @bph. 

I've created this issue so you can track it here. It has also been added to the gallery block refactor project board.

**Comment by glendaviesnz** [comment]
Switched this to a bug as it was working, and does so in the current gallery. The alt text is copied to from the media library to the initial image block that is inserted but is then lost during a subsequent component rerender.

**Comment by glendaviesnz** [comment]
fixed by #31066
