### ISSUE TITLE
Failing to update posts

### ISSUE THREAD

**Issue by ToxicTree** [WordPress/gutenberg#30278]
## Description
It's not possible to update posts.

## Step-by-step reproduction instructions
Press update on a post that has some normal content like text and images.

## Expected behaviour
A nice "Post updated" response.

## Actual behaviour
Post can't be updated. A message is shown: "Failed to update post, the response is not a valid JSON-response".

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OSX 11.2.3
- Browser: Chrome, Safari

(It works in Windows)

This error is shown in console each time the editor is opened:
Unhandled Promise Rejection: [object Object]
dispatchException - wp-polyfill.min.js

**Comment by youknowriad** [comment]
Hi there! this is not the case in regular Gutenberg installs. I'd suggest you debug your install a bit further and provide more information about it.

 - did you try disabling some of your plugins too check whether it's coming from one of them?
 - Did you check your PHP logs to check whether you have php errors.
 - You can also check the result of the API request (the POST request) in the network tab of your browser. It can contain more information.
