### ISSUE TITLE
Block Editor Link control search doesn't work for Author Role

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#30288]
## Description
The Gutenberg Block Editor > Link Control doesn't list the topic names for specified search keywords. This issue occurs for the user with Author role. However, the control works fine for a user with Administrator Role.

## Step-by-step reproduction instructions
1. Go to Editing a custom post/ Add new custom post.
2. Click the "link" icon on the Gutenberg Editor Quick toolbar or press Ctrl+K.
3. Search for a topic name (of an existing topic)

## Expected behaviour
It should display a list of topics matching the search keyword.

## Actual behaviour
No topic list appears.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Default with 5.7.
- Are all plugins except Gutenberg deactivated? Not required as the issue is occurring only for user with specific Role.
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by torounit** [comment]
Hello @quickdraft

The issue was tested during Core Editor [Today's Triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1626759686349000) and wasn't able to reproduce it.

I'm going to close this issue for now, but feel free to re-open if you reencounter it.
