### ISSUE TITLE
Mobile: Icon button gap with explicit width

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3028]
The `IconButton` component assigns an explicit width (36px) at small resolutions. Because the `Dashicon` itself renders with a different width (20px) which does not match padding of the IconButton (4px), a gap is visible while focused:

![Icon button](https://user-images.githubusercontent.com/1779930/31628401-8fb8611e-b27e-11e7-869c-cdb3c5f71839.png)

This should be updated to one (or more) of...

- Increase the width / height of the icon
- Increase the width of the icon button padding
- Decrease or eliminate the explicit width from the icon button
- Center the icon within the icon button

**Steps to reproduce:**

A little tricky, and in my testing does not appear to affect all icon buttons? (Maybe others are assigning their own specific styles to resolve, which should be consolidated)

1. On a mobile (or emulated) display, tap at the area between two blocks
2. The inserter button should become visible
3. Press the inserter button
4. Press the inserter button again to dismiss
5. The inserter button should now be focused

**Miscellany:**

Possibly related: In iOS, pressing the inserter button appears to zoom in the screen. This may be related to input zoom behavior on iOS for smaller font sizes, which _cannot be overridden_ and would require a size increase. ([reference](https://stackoverflow.com/a/6394497))

**Comment by afercia** [comment]
Remove `padding: 4px`.  Or, adjust the width to `28px`. depending on the desired size.

These buttons should have the same computed values for width and height, in other words they should be "squared".

Default icon buttons use a `padding: 8px;` that summed with the icon size 20px gives an height of 36px, same as the width (which is set explicitly).

In this case instead, the width is always 36px but the height is 28px:

<img width="637" alt="screen shot 2017-10-17 at 17 11 41" src="https://user-images.githubusercontent.com/1682452/31672999-53c614f4-b35e-11e7-9114-f07cb6a75e83.png">

and the border-radius is actually rounding a rectangle.


On a side note, especially on mobile, an UI control with a "touchable" area of just 28x28 is too small. I'd say that also 36x36 is too small. Many best practices suggest 44x44.

Worth noting this will probably be also an official recommendation in the upcoming new WCAG 2.1 (Web Content Accessibility Guidelines), not just for mobile but for any screen size:
https://www.w3.org/TR/WCAG21/#target-size
> The size of the target for pointer inputs is at least 44 by 44 CSS pixels

**Comment by mtias** [comment]
This should be fixed with the latest releases.
