### ISSUE TITLE
Add templateLock attribute to core/cover.

### ISSUE THREAD

**Issue by Locheed** [WordPress/gutenberg#30296]
## What problem does this address?
core/column and core/group did get the templateLock attribute. However, it would be good to have this option with other blocks too. e.g. **core/cover**. This block is awesome but cannot be really used on the client's site because it cannot be locked.

This however does work as a top-level block with inheriting templateLock from InnerBlocks.  But now there does not have inheritance any more with core/columns > core/column > core/cover.

https://github.com/WordPress/gutenberg/pull/26128

## What is your proposed solution?
Add possibility to use the templateLock attribute directly with core/cover.

**Comment by paaljoachim** [comment]
General locking is being worked on these days.
Here is a Locking tracking issue: 
**On Locking and TemplateLocking**
https://github.com/WordPress/gutenberg/issues/29864

**Comment by Mamaduka** [comment]
Fixed via #29916.
