### ISSUE TITLE
Navigation Editor - make all config from InspectorControl saved on clicking the save button

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30307]
## Description

Currently, Theme Locations settings and `add new pages` toggle are being saved immediately on click.
This is probably not desired and should rather be saved on clicking the `save` button as it can lead to strange quirks for users visiting the site while it is being configured by the owner.

However, we have also other elements in Inspector Addition, which could be also misleading.
First is Theme Location modal window

![image](https://user-images.githubusercontent.com/8398557/112684940-1daa9080-8e74-11eb-8b90-a7f30359b949.png)

Currently, it is saved immediately, when a value in the dropdown is selected. It also should not work in this way.
Nevertheless, it can be confusing for a user to remember to click on the save button (placed in the header) after making changes in a modal.

The second problem is with the delete button. Currently clicking the delete button and then in the confirmation dialog, it will delete a menu immidietly. This behavior is very straightforward from the UX perspective, nevertheless, it could be confusing as it will be the only element in this part of the app, which works without clicking on the 'save' button.

## Step-by-step reproduction instructions

1. Go to Navigation Editor
2. Select menu (create one if none exists)
3. Make a change in Theme Location
4. See it affects the menu immidietly

## Expected behaviour

Consistency across Inspector Addition menu (sidebar menu) when it comes to caving options. Remove the possibility of strange quirks for site visitors, when an owner does some changes without saving them with the `save` button.

## Actual behaviour

Options are saved immidielty.

## WordPress information
- Gutenberg version: "10.3.0-rc.1"

**Comment by grzim** [comment]
How about adding a message, that will appear when a user makes any change that will inform them, they need to save their work?

![image](https://user-images.githubusercontent.com/8398557/112891135-0e2b8180-90d8-11eb-9dd3-da14ec13b736.png)

**Comment by talldan** [comment]
@grzim Other editors do have systems in place for handling unsaved changes. I made a separate issue for that in the navigation editor - https://github.com/WordPress/gutenberg/issues/30322.

So I think we can consider this as two distinct problems to solve.

**Comment by grzim** [comment]
So I guess https://github.com/WordPress/gutenberg/pull/30340 is closing this issue then.
