### ISSUE TITLE
Provide named export in ServerSideRender

### ISSUE THREAD

**Issue by paulschreiber** [WordPress/gutenberg#30316]
## What problem does this address?
Current behaviour:
```
WORKS: import ServerSideRender from '@wordpress/server-side-render';
WORKS: import { ServerSideRender } from '@wordpress/editor';
FAILS: import { ServerSideRender } from '@wordpress/server-side-render';
```

Since importing from `@wordpress/editor` is deprecated, it'd be nice to be able to import from `@wordpress/server-side-render` in the same way.

Right now, `server-side-render` only provides a named export, not a default export.

Debugging this took quite a while.

**Comment by talldan** [comment]
> Right now, server-side-render only provides a named export, not a default export.

@paulschreiber I think it's the other way around, right?

It is documented correctly, so I don't really see this as an issue. A default export is perfectly legitimate and plenty of npm packages do this.

I'm going to close this. If you feel like contributing a PR with the change, then that may be considered, but I don't think there's value for the project in keeping this kind of issue open.

**Comment by paulschreiber** [comment]
@talldan Going from:
```
import { ServerSideRender } from '@wordpress/editor';
```

to
```
import { ServerSideRender } from '@wordpress/server-side-render';
```

and getting:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a
class/function (for composite components) but got: undefined. You likely forgot to export your
component from the file it's defined in  or you might have mixed up default and named imports.
```

and hundreds of lines of backtraces, all of which is in library code … is no fun. I'd be happy to make a PR, but I am not sure which file(s) to change. Can you point me in the right direction?

**Comment by talldan** [comment]
The file that has the default export is https://github.com/WordPress/gutenberg/blob/trunk/packages/server-side-render/src/index.js#L53

**Comment by paulschreiber** [comment]
Would I want to add this?
```js
module.exports.ServerSideRender = ExportedServerSideRender;
```

**Comment by talldan** [comment]
I think it'd be:
```jsx
export { ExportedServerSideRender as ServerSideRender };
```
