### ISSUE TITLE
npx: command not found: create-block - when using pnpx

### ISSUE THREAD

**Issue by meglio** [WordPress/gutenberg#30312]
## Description

Cannot use pnpx instead of npx:

`pnpx @wordpress/create-block wp-test`

...throws an error:

> npx: command not found: create-block

## Step-by-step reproduction instructions

Run `pnpx @wordpress/create-block wp-test`

## Expected behaviour

Expect it to work the same as if when `npx` is called:

`npx @wordpress/create-block wp-test`

## Actual behaviour

Throws an error:

> npx: command not found: create-block

## WordPress information

Not applicable. I am following the [Create a block tutorial](https://developer.wordpress.org/block-editor/handbook/tutorials/create-block/).

- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: Laptop Mac Book Pro 2015
- Operating system: Mac OS Big Sur
- Browser: Firefox Latest

**Comment by talldan** [comment]
@meglio I'd recommend raising this with the pnpx project. If the goal is for it to be compatible with npm, then it seems more like a bug there than here.

If the command is failing with `npx` then that's something that would be considered a bug.
