### ISSUE TITLE
Navigation screen: consider automatically selecting navigation block when switching menus

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30325]
## What problem does this address?
When switching or creating menus, currently the new menu is loaded, but nothing on the screen is selected, which possibly makes the user question what to do next. 

## What is your proposed solution?
It might be expected that the navigation block is selected so that a user can see the settings for the menu they've created or switched to.

**Comment by shaunandrews** [comment]
Additionally, perhaps we incorporate tabs in the sidebar; One for the menu (navigation block) and another for its child blocks, similar to the way the block editor works:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/191598/113043153-09171280-916a-11eb-8dda-b85650837d57.png">
