### ISSUE TITLE
Navigation screen: Possible to edit a non-existent menu from Manage Location dialog button

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30329]
## Description
The manage locations dialog has an edit button that allows the user to edit the specified menu.

If the user has no menu selected in the dropdown, it has the weird behavior of allowing the user to edit a menu that has not yet been created.

## Step-by-step reproduction instructions
1. Add a menu
2. Select the navigation block
3. From the block inspector, select the Manage Locations button
4. Ensure one of the locations has no menu selected
5. Click the edit button next to it

## Expected behaviour
The button is greyed out. Additionally, the navigation screen has stronger systems in place to prevent editing of a `null` menu.

## Actual behaviour
The navigation screen shows 'No menus available', but displays a menu that can be edited.

**Comment by talldan** [comment]
I haven't been able to reproduce this in testing again, so I'm not sure what happened.

**Comment by getdave** [comment]
Couldn't replicate either @talldan. Happy to close if you are.
