### ISSUE TITLE
Navigation screen: The 'Open in new tab' setting is not saved

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30323]
## Description
In the navigation screen, using the 'Open in new tab' option on a link has no effect.

## Step-by-step reproduction instructions
1. Add a menu item with a link and enable the open in new tab option
2. Save and reload
3. View the link for menu item just added
4. Observe the option is disabled again
5. View the menu on the front end of the site
6. Click the link—it doesn't open in a new menu.

## Expected behaviour
The option should be retained when saving. The link in the frontend should open in a new tab.

The old menu screen had this option (under advanced screen options), so it should be possible to save the setting.

**Comment by getdave** [comment]
FYI looks like the data being returned from the API might be missing the attribute. Maybe it's not being persisted on save. Wrapping my head around the saving mechanics via a quick refresher on the @wordpress/data API.

**Comment by getdave** [comment]
Ok I have a fix. PR incoming.
