### ISSUE TITLE
Navigation screen: Block toolbar contains uncentered icons

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30324]
## Description
The block toolbar contains some uncentered icons.

This seems like an extension of the issue seen at https://github.com/WordPress/gutenberg/pull/30284. The block toolbar has some styles that are applied to specific screens.

See https://github.com/WordPress/gutenberg/issues/29965 for some of the issues with implementing block toolbars.

For now, it's probably worth putting in a quick fix for this.

## Step-by-step reproduction instructions
1. Select the navigation block and view the toolbar on desktop
2. Observe the block icon has uneven side padding
3. Resize the browser to mobile size
4. Observe the focus ring for some buttons is uneven and the block icon still has uneven padding

## Screenshots or screen recording (optional)
<img width="434" alt="Screenshot 2021-03-29 at 3 17 44 pm" src="https://user-images.githubusercontent.com/677833/112800286-08b34480-90a2-11eb-8653-b19b2de817dd.png">

**Comment by sabernhardt** [comment]
That specific button has different padding on each side at narrower than 782:
` {
    min-width: 42px;
    padding-left: 6px;
    padding-right: 11px;
}`

And the padding is even at larger sizes:
`{
    min-width: 48px;
    padding-left: 12px;
    padding-right: 12px;
}`

**Comment by getdave** [comment]
Just tested and can no longer replicate. Assume fixed elsewhere at source.

![Screen Capture on 2021-05-05 at 16-59-10](https://user-images.githubusercontent.com/444434/117171969-443cdf00-adc3-11eb-8278-0b9b2a06c215.gif)
