### ISSUE TITLE
General Template Part icon can be confusing

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#30338]
At the moment Template Part blocks assigned to the "General" `area` utilise the "Layout" icon, which is the same icon we use for the "top level" templates like Index. 

This is problematic because the UI hints that these two site building elements are the same thing. It gets especially confusing when a general Template Part is nested inside a header template part:

<img width="346" alt="Screenshot 2021-03-29 at 11 48 30" src="https://user-images.githubusercontent.com/846565/112827124-d267cc00-9085-11eb-9a87-a479bec60d7c.png">

They are related of course, but the differences warrant identification to the user.

**Comment by jameskoster** [comment]
We have the following icons for templates, and the other template part `area`s:

<img width="625" alt="Screenshot 2021-03-29 at 11 59 39" src="https://user-images.githubusercontent.com/846565/112827469-4bffba00-9086-11eb-95bc-94f3ebd21436.png">

Perhaps the "General" Template Part could use an inverse of the `layout` icon?

<img width="143" alt="Screenshot 2021-03-29 at 11 56 17" src="https://user-images.githubusercontent.com/846565/112827541-63d73e00-9086-11eb-93be-faa3fcb008d1.png">

<img width="349" alt="Screenshot 2021-03-29 at 12 02 15" src="https://user-images.githubusercontent.com/846565/112827717-a13bcb80-9086-11eb-9186-479a7fc16e86.png">

**Comment by paaljoachim** [comment]
Hey James

Looking at the current Template part icons such as you are showing the Header template. A black area in the top. Another would be columns where there is a black area in the middle between two column areas. The Footer show the black area in the bottom. Using the logic here it feels natural to have the General Template icon show black in each area.

> Perhaps the "General" Template Part could use an inverse of the layout icon?

Based on the logic used it feels natural to do so.

**Comment by pablohoneyhoney** [comment]
If we need to use a special icon with an inversed style, worth refining the below as it doesn't share the same DNA at the moment. It's smaller and has fully squared corners. 

![](https://user-images.githubusercontent.com/846565/112827541-63d73e00-9086-11eb-93be-faa3fcb008d1.png)

**Comment by jameskoster** [comment]
DNA is shared in the sense that the template part icon fits perfectly inside the template icon, which has some conceptual value:

<img width="252" alt="Screenshot 2021-03-31 at 09 23 02" src="https://user-images.githubusercontent.com/846565/113114004-d53bfb80-9202-11eb-99c4-0df388491e7e.png">

That said I have no objection to making them the same size so that the icon fits in better alongside others in the set:

<img width="242" alt="Screenshot 2021-03-31 at 09 27 56" src="https://user-images.githubusercontent.com/846565/113114605-67440400-9203-11eb-8a2c-c2dd70a3e801.png">

**Comment by mtias** [comment]
The inverted icon feels conceptually weird and obscure to me. I think we should consider using the block-sidebar one given it's likely we won't have a semantic template part called sidebar. Sidebar depends on surrounding layout. Widget areas are generally used in multiple places, not always sidebars. I'd consider template-parts to be somewhat equivalent to widget areas.

**Comment by jameskoster** [comment]
> I'd consider template-parts to be somewhat equivalent to widget areas.

I agree with this, but for me the sidebar icon is too prescriptive. As you said, these areas are not always placed in a "sidebar" and so the icon loses some relevance in many cases.

There is also the scenario where a general template part is nested inside a Header or Footer. This doesn't really feel right to me:

<img width="1356" alt="Screenshot 2021-03-31 at 11 58 08" src="https://user-images.githubusercontent.com/846565/113134312-8a2ce300-9218-11eb-9b16-73ec5d39e396.png">

**Comment by mtias** [comment]
> There is also the scenario where a general template part is nested inside a Header or Footer. This doesn't really feel right to me:

It seems alright to me considering it's a scenario that doesn't seem super common?

**Comment by jameskoster** [comment]
I don't know, I can see advanced sites making more frequent use of this functionality. A WooCommerce store / theme for example might want to display a cart summary in various locations like the checkout page, a navigation dropdown, sidebar, etc. Or to create a product summary template part for use in category archives, related product grids, cross-sells etc.

Edit: The sidebar icon is definitely an improvement, but I'm not sure it captures the versatility of a general template part.

**Comment by ntsekouras** [comment]
Fixed by: https://github.com/WordPress/gutenberg/pull/34002
