### ISSUE TITLE
Navigation screen: Manage location edit button misaligned

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30331]
## Description
The manage locations dialog in the nav screen has a misaligned dialog

## Step-by-step reproduction instructions
1. Visit the nav screen
2. Select the nav block
3. Select manage locations
4. View the dialog

## Expected behaviour
The Edit button is aligned correctly.

## Actual behaviour
The Edit button is misaligned

## Screenshots or screen recording (optional)
<img width="371" alt="Screenshot 2021-03-29 at 4 14 01 pm" src="https://user-images.githubusercontent.com/677833/112806847-cf7ed280-90a9-11eb-92e5-d962e48d32ff.png">

**Comment by priethor** [comment]
Hi there! Let's reopen the issue as the misalignment still appears in Gutenberg 10.5.2. cc @javierarce.
