### ISSUE TITLE
Navigation screen: regression of improved menu locations select placeholder

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30330]
# Description
The improved placeholder from https://github.com/WordPress/gutenberg/pull/29908 has regressed.

This change will need to be reimplemented.

## Step-by-step reproduction instructions
1. Open the nav screen
2. Select manage locations
3. View the locations menu select elements

## Expected behaviour
The improved placeholder is visible

## Actual behaviour
The improved placeholder is not visible, the feature has regressed.

**Comment by Quintis1212** [comment]
Hi @talldan  ) The bug is that "— Select a Menu —" is not visible in manage location list  ? I will try to fix this
