### ISSUE TITLE
Blocks: Add isDefault to server side block styles registry

### ISSUE THREAD

**Issue by xavivars** [WordPress/gutenberg#30356]
## What problem does this address?
[As documented here](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/filters/block-filters.md#block-style-variations), block styles can be registered both server side (using PHP method `register_block_style`) and client side (using `wp.blocks.registerBlockStyle`).

While server-side registration is a convenient method to easily register new block styles, it lacks the ability to register a style as the default one.

As an example, something that could easily be achieved like this in JS, is not doable in PHP

	wp.blocks.registerBlockStyle( 'core/heading', [ 
		{
			name: 'default',
			label: 'Default',
			isDefault: true,
		},
		{
			name: 'alt',
			label: 'Alternate',
		}
	]);

## What is your proposed solution?
Extend `register_block_style` to also accept `isDefault`. 
(it would probably require to change core code in https://github.com/WordPress/WordPress/blob/59d32bfe24cee58554ac82573d8a69dd6b6749ab/wp-includes/script-loader.php#L2311 )

**Comment by skorasaurus** [comment]
Thanks for reporting. It's worth noting that [there has been discussion on reconceptualizing what 'default' means when registering a block style and removing the isDefault property](https://github.com/WordPress/gutenberg/issues/20706) although no decision has been made.

**Comment by gziolo** [comment]
Yes, it needs an upstream change in WordPress core. We should move it to WordPress trac.

**Comment by gziolo** [comment]
Ticket in WP trac filed: https://core.trac.wordpress.org/ticket/53006. I will close this one. Let's continue there.
