### ISSUE TITLE
When I activate 'add text over image' content goes to a gray section and I can't access it or continuing working on next sections below

### ISSUE THREAD

**Issue by DenisFlorin** [WordPress/gutenberg#30354]
## Description
When I activate 'add text over image' content goes to a grey section and I can't access it or continuing working on the next sections below

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go create a new page
2. Click to add new block -> Patterns -> Columns
3. Scroll down to two columns of texts and images and add them to your page.
4. Click one of the images and add the option 'add text over image'

## Expected behaviour
The grey section should not appear.

## Actual behaviour
The content goes over the line and is visible under a grey section

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/38504865/112877958-0a93fc80-90d0-11eb-9e71-a6f7350deb0a.png)

![image](https://user-images.githubusercontent.com/38504865/112877977-0f58b080-90d0-11eb-956f-64a2de10a275.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Default from WordPress
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? No, I'm using Twenty Twenty

## Device information
- Device: Desktop
- Operating system: Linux
- Browser: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by Mamaduka** [comment]
Hello, @DenisFlorin

The issue was tested during Core Editor Triage Session [today](https://wordpress.slack.com/archives/C02QB2JS7/p1626758143330000) and wasn't able to reproduce it on WP 5.8 or Gutenberg 11.0.

PR #32747 removed the grey background displayed in the screenshot.

I'm going to close this issue for now, but feel free to re-open if you reencounter it.
