### ISSUE TITLE
Query Block: Allow for alternating and irregular layouts

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#30380]
While thinking through block patterns for the Query block, I quickly ran into the fact that the block currently requires every single post to have the same layout. This is fine for standard post lists, but it's not clear how irregular or alternating layouts would be made possible yet. For example: 

Alternating Layout|Irregular Layout
---|---
![Screen Shot 2021-03-30 at 10 22 30 AM](https://user-images.githubusercontent.com/1202812/113005087-259f5480-9142-11eb-9a0e-8df8779179e4.png)|<img width="1200" alt="Frame 11" src="https://user-images.githubusercontent.com/1202812/113006192-27b5e300-9143-11eb-94aa-0f069ef7f5e9.png">

**Comment by mtias** [comment]
The tradeoffs here are between flexibility, clarity, and ease of creation. For "irregular" layouts, the easiest would probably be to use separate queries with offsets, or even individual posts (latest post with offset 1, latest post with offset 2, etc). For "alternating" layout, it seems like it should be among the options you choose from (like grid or masonry).

We could also have a template per item, or per condition (like 2n), but it can get extremely convoluted quickly. Any operation like that feels like it would need a bit more of a focused environment like the one proposed in #26190.

cc @jeffersonrabb in case you have thoughts on what has felt most intuitive from your work on post-list-blocks.

**Comment by aristath** [comment]
Since alternative/irregular layouts like these will be pretty theme-specific, this _could_ be a block-style...
The theme could for example do something like this:
```php
register_block_style(
	'core/group',
	[
		'name'         => 'alternating-columns',
		'label'        => __( 'Alternating', 'my-theme' ),
		'inline_style' => '
			.wp-block-group.is-style-alternating > .wp-block-columns:nth-child(odd),
			.wp-block-group.is-style-alternating > .wp-block-group__inner-container > .wp-block-columns:nth-child(odd) {
				flex-direction: row-reverse;
			}',
	]
);
```

**Comment by mtias** [comment]
@kjellr this seems the same as #25462. Going to close so that we can consolidate conversation there.
