### ISSUE TITLE
InnerBlocks Inserter doesn't insert if child block with changing height has focus

### ISSUE THREAD

**Issue by SeanMcMillan** [WordPress/gutenberg#30389]
## Description
A block using InnerBlocks doesn't insert a child block when you click the [+]. This only is a problem when the child block has additional content when it is selected (isSelected.) Instead of inserting a new block, the [+] takes the focus. Once the [+] has the focus, you can then click it and the block will be inserted.

This worked correctly in WordPress 5.6.

To trigger this behavior, You need a container block that is vertically oriented, and a child block that changes height. I've made a minimal test case here: https://github.com/SeanMcMillan/min-block

## Step-by-step reproduction instructions
1. Clone the repository into a wordpress/wp-content/plugins directory.
2. `npm install`
3. `npm run build`
4. Activate the plugin
5. Edit any post
6. Insert the Min Test block
7. Click on the [+] button inside the Min Test block a few times.

## Expected behaviour
The child block should be inserted on the first click.

## Actual behaviour
The [+] takes the fous, but no insert happens.

## Code snippet (optional)
https://github.com/SeanMcMillan/min-block

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 86.0.1

**Comment by kathrynwp** [comment]
Hi @SeanMcMillan - belated thank you for the issue report, and for the test plugin!

I'm trying to see if this can still be replicated.

I skipped test steps 1-3 and started by installing your plugin. I don't think I'm able to replicate, but I'd love for you to confirm if you have a moment to take a look. Thank you!

**Tested with:**

WordPress 6.0.1
Testing plugin active
No other plugins active
Twenty Twenty-Two 1.2

**Screencast:**

https://user-images.githubusercontent.com/7662449/184244469-927e9b7b-91aa-4a2f-8bbf-e26ce7ce7f8a.mov

**Comment by kathrynwp** [comment]
@SeanMcMillan Hi - just checking in one last time to see if the issue is still valid, otherwise I'm going to close it out. Thanks!

**Comment by SeanMcMillan** [comment]
I've been pulled away from my Wordpress project for a while, but I expect to be back on it next week and I'll see if it still happens in 6.0.1

**Comment by kathrynwp** [comment]
@SeanMcMillan Thank you so much, looking forward to hearing whether you can replicate it, when you have a chance!

**Comment by ndiego** [comment]
@SeanMcMillan just checking in. Are you able to check if you are still seeing this issue in WordPress 6.1.1 and the latest version of Gutenberg? I was not able to replicate the issue. Thanks

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. I am still unable to replicate it and therefore am going to close this ticket. That said, if anyone still experiences this issue, please feel free to reopen with additional information and replication steps.
