### ISSUE TITLE
Navigation Editor - Detect unsaved changes, and only enable the save button when there are unsaved changes

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30391]
## What problem does this address?

In order to better handle https://github.com/WordPress/gutenberg/issues/30322 let's divide it into separate issues, each with a corresponding PR.

Currently, the way a user saves their changes is confusing.  Options in the navbar are saved with a save button placed in the header. Moreover, there is no visible clue, helping a user to understand they need to hit the save button to save their changes (to inform, that the changes are not saved immediately). 

## What is your proposed solution?

As described by @shaunandrews the desirable solution is to
- add a dot to every element that has been changed and unsaved (solution similar to  site editor) with a tooltip
- add a save button in the navbar which will be
      - disabled as long as no change is made
      - have a tooltip explaining why it's disabled
      - when enabled, having a dot to indicate it will save elements marked with dots

![113044880-2816a400-916c-11eb-9732-64858da545f7](https://user-images.githubusercontent.com/8398557/113060190-9d0bcd00-91b0-11eb-8284-3ceeeef5e842.gif)

**Comment by talldan** [comment]
> add a save button in the navbar which will be

I don't think we need to add a save button. Lets modify the existing one in the header first.

**Comment by Mamaduka** [comment]
Fixed via #31119.
