### ISSUE TITLE
[Full Site Editing] Editing Field expands when both List View & Block Settings are open

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30398]
## Description

When using the Site Editor, if you open both the List View and Block Settings while editing a block near the edge of the editing field, it expands showing strange grey space. This might be related to this but unclear: https://github.com/WordPress/gutenberg/issues/30120

## Step-by-step reproduction instructions
1. Setup a site with TT1 Blocks & latest version of Gutenberg
2. Head to the Site Editor experience.
3. Open List View. 
4. Open Block Settings. 
5. Select an individual block near the edge of the editing field and try to scroll to the side. 
6. You'll see the editing field accidentally expands exposing a strange grey area. 

## Expected behaviour

Expect nothing to happen :D 

## Actual behaviour

The editing field expands/breaks. 

## Screenshots or screen recording (optional)

Note that this happens whether it's a button, paragraph block, navigation block, etc:

<img width="1324" alt="Screen Shot 2021-03-30 at 8 44 59 PM" src="https://user-images.githubusercontent.com/26996883/113083092-d33d5280-9198-11eb-8928-8a27096e0a8c.png">
<img width="1315" alt="Screen Shot 2021-03-30 at 8 44 51 PM" src="https://user-images.githubusercontent.com/26996883/113083106-d8020680-9198-11eb-9ef1-1fa81e543955.png">

https://user-images.githubusercontent.com/26996883/113083440-72624a00-9199-11eb-9a11-d2c534db5199.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOs
- Browser: Chrome 88

**Comment by sabrina-zeidan** [comment]
I encountered not exactly the same, but a similar issue. 
Everything looks good in the Editor (with both List View and Block Settings open, too). But there is some area on the frontend though (both for logged-in and non-logged-in). I wasn't able to define the specific element causing it. 
Gutenberg 10.5.2 

https://user-images.githubusercontent.com/5646904/116611236-cd28c600-a93e-11eb-8b50-153a2845ec8e.mp4

**Comment by annezazu** [comment]
Noting that this happens with WordPress 5.8RC2 in the template editor: 

https://user-images.githubusercontent.com/26996883/124978871-8e268900-dfef-11eb-9544-7d1747d5fa07.mov

**Comment by Mamaduka** [comment]
I'm no longer able to reproduce this issue. Probably fixed via #35082.

## Screencast

https://user-images.githubusercontent.com/240569/167793102-9b5a527c-3136-4a6e-bdfb-0742ba2ff67f.mp4

**Comment by annezazu** [comment]
Fantastic! Closing out.
