### ISSUE TITLE
List author: console error for editors

### ISSUE THREAD

**Issue by marcorroma** [WordPress/gutenberg#30402]
Hello,
today i updated WordPress to version 5.7 and i have this problem.
If logged in as administrator, in the “new post” page I have no console errors.
If I am logged in as Editor, in the “new post” page I have this error in console:

{“code”:”rest_forbidden_context”,”message”:”Non hai i permessi per l’elenco degli utenti.”,”data”:{“status”:401}}
Message translated into English: “You do not have permissions for the user list.”

Screenshot:
https://i.ibb.co/GCJk9Zw/1.jpg

This error does not show the complete list of authors (if there is a long list), to users logged in as editor. And it does not allow you to search for authors by typing the name/surname, this function works only if you are logged in as an administrator.

I have checked this problem on three sites (2 test sites) with three different themes. I tried to deactivate all plugins, to change theme (without any active plugin), I tried to clear the cache (even in incognito mode). I also tried to activate the “maintenance” mode with the “Health Check & Troubleshooting” plugin.

It does not solve the problem.

I think it is a WordPress 5.7 bug.
With version 5.6 I didn’t have this problem.

I await a reply. My “Editors” fail to work properly.
Thanks

PS. Four other users (on a famous italian facebook group) have the same problem.
We are waiting for a solution. Thanks.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 

This has been reporting in https://github.com/WordPress/gutenberg/issues/30360. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
