### ISSUE TITLE
Text mode toolbar not visible on mobile screen 

### ISSUE THREAD

**Issue by ShreyaSingh10** [WordPress/gutenberg#3041]
## Issue Overview

When you change the screen resolution the Text Mode toolbar becomes partially visible
## Steps to Reproduce (for bugs)

1.Change the screen size to that of the mobile resolution
2.Change to Text Mode

## Expected Behavior

Text Mode toolbar should be visible entirely

## Current Behavior

Text Mode toolbar is not visible entirely
## Possible Solution

I am working on the fix

## Todos
Fix the appropriate css

![wp](https://user-images.githubusercontent.com/16452519/31671310-539157f0-b377-11e7-932f-9f2e96a7ace5.png)

**Comment by youknowriad** [comment]
Closing as the Text Mode Toolbar has been removed for now.
