### ISSUE TITLE
Tooltip element acting weird on disabled button

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30422]
## Description

When a `Tooltip` element is used with the disabled `Button`, it adds `,` at the end and also makes a button clickable

Can be related to https://github.com/WordPress/gutenberg/pull/27529
## Step-by-step reproduction instructions

Wrap disabled `Button` in `Rooltip`
## Expected behaviour

`Button` is not clickable

## Actual behaviour

`Button` is clickable, and comma is added

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/8398557/113205775-f1758200-926e-11eb-9e9d-bce65411f647.png)

## WordPress information
- Gutenberg version: 10.3.0-rc.1

**Comment by talldan** [comment]
#35247 only partially fixed by removing the stray comma, so reopening.
