### ISSUE TITLE
Navigation Editor - update delete menu button

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30426]
## What problem does this address?

As described in https://github.com/WordPress/gutenberg/issues/30307 we want all the data in the sidebar to be saved on the `save button` click rather than being saved immediately on change.
Nevertheless, as pointed in https://github.com/WordPress/gutenberg/issues/30322 `Delete button` is behaving in a different way - it deletes the menu upon clicking on it (and then confirming) and we would rather leave it this way.
Therefore, in order to avoid confusions, it would be good to place it in a different area, to make it clearer that it will work without the need of hitting the `save button`

## What is your proposed solution?

Place the `Delete menu` button under `Manage locations` or in a different place to make distinguished from other options that are saved on hitting `save button`

**Comment by javierarce** [comment]
I think it's a good idea to place the delete button at the end of the sidebar, not exactly because of the possible confusion with the Save flow (which is addressed by the dots and the disabled state of the save button in [this issue](https://github.com/WordPress/gutenberg/issues/30322)), but because of its destructive nature (and also because "Delete menu" is not really a setting).

Here's my proposal (maybe too dramatic?) 

![delete](https://user-images.githubusercontent.com/4933/114154960-3eb5bb80-9921-11eb-9321-a7280dea0695.png)

Another thing I'd improve is the message in the alert box. We are currently saying: "Are you sure you want to delete this navigation?" I would add: "This action cannot be undone"

What do you think, @shaunandrews?

**Comment by shaunandrews** [comment]
I'm not sure it needs to have it's own accordion or all the copy around it. Here's a few ideas:

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/191598/114214050-d4594700-9931-11eb-8018-eba4e3faac17.png">

**Comment by javierarce** [comment]
The button would be placed at the bottom of the screen, right? 

I agree with you about not needing the accordion and the text around. I'd go for the last option you suggested and update the alert box to remind the user there's no undo: "Are you sure you want to delete this menu? This action cannot be undone"

**Comment by shaunandrews** [comment]
Sounds good to me.

**Comment by getdave** [comment]
@shaunandrews Coming to this all with fresh eyes as a "new" user, I was struggling to find where to delete my menus. Personally I think it's not helpful to divorce the primary action buttons, even if the intent here is to avoid making destructive actions too easy to find.

Looking at the existing Menus screen the `Delete` action is placed in the same plain as the `Save` action. 

<img width="1094" alt="Screen Shot 2021-04-21 at 09 48 37" src="https://user-images.githubusercontent.com/444434/115525721-419c9e80-a287-11eb-8d66-03a575bd2c4d.png">




I'm not saying we need to mirror everything the old screen did, but perhaps some continuity would be nice.

I see the `Delete` action as a primary action and thus it should be in the header next to the `Save` and `Switch` buttons. We already have the "Are you sure?" confirmation which will avoid users accidentally taking a destructive action.

Interested in your thoughts and also @critterverse.

**Comment by javierarce** [comment]
I think the screenshot is contradicting the idea of the Delete action being primary 😅  

Moving the button to the bottom of the screen is good: it's easily accessible and helps remove noise from the top elements of the sidebar.

A counter-argument could be that the Trash button in the Page editor is always visible and it's placed on top of the screen, so users will naturally expect it to be there:

![Screenshot 2021-04-22 at 12 34 45](https://user-images.githubusercontent.com/4933/115700770-52bcdc80-a367-11eb-8102-265b929fc169.png)
