### ISSUE TITLE
Scroll to show the selected block in List View when selecting a block in the editing canvas

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30432]
## What problem does this address?
The persistent list view is very handy. Though, with a really long list of blocks, it can take a bit of scrolling to find the selected one.

I noticed if you select a block in list view that's not in the viewport of the main editor canvas, the canvas scrolls to show the selected block.

When doing the reverse—selecting a block in the editor canvas that's not in the viewport of list view, this doesn't happen, but I think it'd be very helpful if it did.

## What is your proposed solution?
Always scroll to show the selected block in list view.

**Comment by andrewserong** [comment]
Potential fix: https://github.com/WordPress/gutenberg/pull/46895
