### ISSUE TITLE
Mobile: Image Block: Overflow Visible When Entering Multiple Lines of Alt Text on Android

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#30457]
## Description

In https://github.com/WordPress/gutenberg/pull/29670, we introduced the option of entering multiple lines of alt text in the image block's settings.

When entering multiple lines of text on Android, some of the overflow can be viewed at the top:

![113318424-1224f280-92d6-11eb-9df5-cb0a49fa8cff](https://user-images.githubusercontent.com/2998162/113332663-61d8dd80-9319-11eb-858f-5734532f01d4.png)

It'd be great to hide this overflow completely from view.

## Device information
- Device: Pixel 
- Operating system: Android 11

**Comment by kathrynwp** [comment]
Hi @davidcalhoun or @SiobhyB, I'm just circling back to this issue to check whether it's still valid. Let me know if you'd like it to be kept open or not. Thanks!

**Comment by SiobhyB** [comment]
👋 @kathrynwp, I'm still able to replicate this issue, but will label it as low priority. I plan to circle back to this at some point in the future to determine whether this is something that can be addressed or a "wontfix". It's not high on my "to do" list, but it's there! :)

**Comment by SiobhyB** [comment]
After reflecting on this issue, I don't believe there's necessarily a bug. I think it's acceptable to see some clipped text when actively typing into a multiline text area. We're also using a general React Native component that would behave in the same manner for any app. I don't think it's necessary to change that default behaviour. Going ahead to close this issue, but open to other perspectives.
