### ISSUE TITLE
Editable: Rename wrapperClassname prop to wrapperClassName

### ISSUE THREAD

**Issue by donnapep** [WordPress/gutenberg#3046]
## Issue Overview
It's likely better to use `wrapperClassname` as the name of the `Editable` prop, especially given the fact that React uses `className`. It's a very easy thing to specify `wrapperClassName` and then wonder why the class isn't being added.

## Expected Behavior
The `wrapperClassname` prop of the `<Editable>` component should be renamed to `wrapperClassName` in order to adhere to lower camel case naming, and to be more consistent with React's `className` prop.

Gutenberg Version: 1.4.0

**Comment by gziolo** [comment]
Closed with #3053. Thanks @vladanost 👍
