### ISSUE TITLE
Post Featured Image block: Change element from paragraph to figure

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30475]
Currently, the Post Featured Image block outputs the featured image wrapped in a paragraph element:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/8181091/113431071-7a113100-93db-11eb-9ce4-54ec3f47e0bc.png">

A figure element would be more semantic, and match the structure of the gallery and image blocks.

**Comment by annezazu** [comment]
This was raised in the [fifth call for testing for the FSE Outreach program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1552) as well as a point of confusion.
