### ISSUE TITLE
theme.json: theme_has_support() might cache wrong value

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#30478]
Discovered here: https://github.com/WordPress/gutenberg/pull/30045#issuecomment-812643945. See that PR for instructions on how to repro.

---

Since #28786 (and later #28788, which renamed and moved the relevant function), we've been caching the return value of `WP_Theme_JSON_Resolver::theme_has_support()`:

https://github.com/WordPress/gutenberg/blob/ddccfab16a8e2e350bf975077700b8acb148959b/lib/class-wp-theme-json-resolver.php#L500-L511

This makes sense at first glance, since, as was stated in #28786:

> It is very unlikely the readability of the file will change during the execution time.
> Doing file-system requests isn't free of charge, storing the result in memory is much cheaper.

This seems to work fine in a "normal" WordPress environment; however, it seems to pose a problem for unit tests: `WP_Theme_JSON_Resolver::theme_has_support()` is first called while the current theme [is still set to the default theme](https://github.com/wp-phpunit/wp-phpunit/blob/fefaaf8d086c0401d887661e21dc9e9afdfc0411/includes/bootstrap.php#L138-L145) -- which of course _doesn't_ have an `experimental-theme.json` file -- so we're erroneously caching `false` as return value for `WP_Theme_JSON_Resolver::theme_has_support()`.

Even if an individual unit test later sets the current theme to one that has an `experimental-theme.json`, `WP_Theme_JSON_Resolver::theme_has_support()` will continue to return the cached `false` value.

## Steps to reproduce

Check out `trunk`, and apply the following patch on top of it:

```diff
diff --git a/lib/class-wp-theme-json-resolver.php b/lib/class-wp-theme-json-resolver.php
index 31ecb553a2..8b2248a0cb 100644
--- a/lib/class-wp-theme-json-resolver.php
+++ b/lib/class-wp-theme-json-resolver.php
@@ -460,10 +460,12 @@ class WP_Theme_JSON_Resolver {
         * @return boolean
         */
        public static function theme_has_support() {
+               debug_print_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS, 2 );
+               echo get_stylesheet_directory() . "\n";
                if ( ! isset( self::$theme_has_support ) ) {
                        self::$theme_has_support = (bool) self::get_file_path_from_theme( 'experimental-theme.json' );
                }
-
+               echo "theme_has_support: " . self::$theme_has_support . "\n";
                return self::$theme_has_support;
        }
 
```

Then, run

```
npm run test-unit-php -- /var/www/html/wp-content/plugins/gutenberg/phpunit/class-block-templates-test.php
```

This should give something like 

<details>
<summary>Output</summary>

```
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php:364]
#1  gutenberg_register_packages_styles() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/../data/themedir1/default
theme_has_support: 
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/global-styles.php:163]
#1  gutenberg_experimental_global_styles_register_user_cpt() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/../data/themedir1/default
theme_has_support: 
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.16
Configuration: /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist

....#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:60]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 
..                                                              6 / 6 (100%)#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:109]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:109]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 


Time: 1.44 seconds, Memory: 36.50 MB

OK (6 tests, 70 assertions)
```
</details>

Note that for the first two callsites of `theme_has_support`, which happen during bootstrapping -- `lib/client-assets.php:364` and `lib/global-styles.php:163` -- the output for `echo get_stylesheet_directory() . "\n";` is

```
/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/../data/themedir1/default
```

i.e., the default theme.

In later calls, it is `/var/www/html/wp-content/themes/tt1-blocks`; but in all cases, the return value of `theme_has_support()` is `false`.

cc/ @moorscode @nosolosw @Addison-Stavlo @david-szabo97 @WordPress/gutenberg-core

**Comment by ockham** [comment]
The most straight-forward remedy is to add a cache key -- the theme slug comes to mind:

```diff
diff --git a/lib/class-wp-theme-json-resolver.php b/lib/class-wp-theme-json-resolver.php
index 6815dc68ec..e312fe8b38 100644
--- a/lib/class-wp-theme-json-resolver.php
+++ b/lib/class-wp-theme-json-resolver.php
@@ -31,7 +31,7 @@ class WP_Theme_JSON_Resolver {
 	 *
 	 * @var boolean
 	 */
-	private static $theme_has_support = null;
+	private static $theme_has_support = array();
 
 	/**
 	 * Container for data coming from the user.
@@ -503,11 +503,12 @@ class WP_Theme_JSON_Resolver {
 	 * @return boolean
 	 */
 	public static function theme_has_support() {
-		if ( ! isset( self::$theme_has_support ) ) {
-			self::$theme_has_support = (bool) self::get_file_path_from_theme( 'experimental-theme.json' );
+		$theme_slug = get_stylesheet();
+		if ( ! isset( self::$theme_has_support[ $theme_slug ] ) ) {
+			self::$theme_has_support[ $theme_slug ] = (bool) self::get_file_path_from_theme( 'experimental-theme.json' );
 		}
 
-		return self::$theme_has_support;
+		return self::$theme_has_support[ $theme_slug ];
 	}
 
 	/**
diff --git a/lib/full-site-editing/block-templates.php b/lib/full-site-editing/block-templates.php
index d0bcab00c9..324570b30d 100644
--- a/lib/full-site-editing/block-templates.php
+++ b/lib/full-site-editing/block-templates.php
@@ -124,7 +124,7 @@ function _gutenberg_get_template_files( $template_type ) {
  * @return array Template.
  */
 function _gutenberg_add_template_part_area_info( $template_info ) {
-	if ( WP_Theme_JSON_Resolver::theme_has_support() ) {
+	if ( WP_Theme_JSON_Resolver::theme_has_support( $template_info['slug'] ) ) {
 		$theme_data = WP_Theme_JSON_Resolver::get_theme_data()->get_template_parts();
 	}
 
```

I'll file a PR.

**Comment by moorscode** [comment]
Hi @ockham 

Sounds like a good approach to me.
Don't forget to **not** apply the `lib/full-site-editing/block-templates.php` change though ;)

In efforts of improving things that are touched, I've got a related question; Is there a reason the cache property is not defined in the method itself?

```php
private static $theme_has_support = array();
```

vs

```php
public static function theme_has_support() {
     static $theme_has_support = array();
     ...
}
```

It would keep property close by, which shouldn't be used anywhere else, as you want the method to be the one source of truth.

This paradigm is also used elsewhere in the file:

https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver.php#L145-L146

**Comment by oandregal** [comment]
I left at https://github.com/WordPress/gutenberg/pull/30045#issuecomment-813329780 another thread to look at, in case it's related to that issue.

> However, it's possible that WP_Theme_JSON_Resolver::theme_has_support() is called before any theme is set up

How can I test this? I mean, in isolation, not by running [this](https://github.com/WordPress/gutenberg/pull/30045#issuecomment-812506641). I'd like to understand how to break this code before changing it.

For testing, this is what I've done: hook into an action that runs before the theme is setup: `add_action( 'plugins_loaded', ['WP_Theme_JSON_Resolver', 'theme_has_setup'] )` and add some log statements within the method. Also tried with `setup_theme` hook. Everything looks fine for me (testing with `tt1-blocks` and other default themes and every time they returned the proper value for that particular theme).

Also, by looking at the code of `get_stylesheet_directory` I don't see that it needs the theme loaded: it uses `get_option('stylesheet')` which returns the active theme and then builds a path based on some other checks that don't seem to need any theme loaded either.

**Comment by ockham** [comment]
> I left at [#30045 (comment)](https://github.com/WordPress/gutenberg/pull/30045#issuecomment-813329780) another thread to look at, in case it's related to that issue.
> 
> > However, it's possible that WP_Theme_JSON_Resolver::theme_has_support() is called before any theme is set up
> 
> How can I test this? I mean, in isolation, not by running [this](https://github.com/WordPress/gutenberg/pull/30045#issuecomment-812506641). I'd like to understand how to break this code before changing it.

Yeah, apologies for that -- I didn't see the relevant info being rendered anywhere else, so it was a bit hard to repro otherwise 😅 

Here's a way to repro (albeit through running a unit test -- so there's potentially a chance that the unit test is flawed):

Apply the following diff, and run `npm run test-unit-php -- /var/www/html/wp-content/plugins/gutenberg/phpunit/class-block-templates-test.php`:

```diff
diff --git a/lib/class-wp-theme-json-resolver.php b/lib/class-wp-theme-json-resolver.php
index 31ecb553a2..8b2248a0cb 100644
--- a/lib/class-wp-theme-json-resolver.php
+++ b/lib/class-wp-theme-json-resolver.php
@@ -460,10 +460,12 @@ class WP_Theme_JSON_Resolver {
         * @return boolean
         */
        public static function theme_has_support() {
+               debug_print_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS, 2 );
+               echo get_stylesheet_directory() . "\n";
                if ( ! isset( self::$theme_has_support ) ) {
                        self::$theme_has_support = (bool) self::get_file_path_from_theme( 'experimental-theme.json' );
                }
-
+               echo "theme_has_support: " . self::$theme_has_support . "\n";
                return self::$theme_has_support;
        }
 
```

That gives me:

```
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php:364]
#1  gutenberg_register_packages_styles() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/../data/themedir1/default
theme_has_support: 
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/global-styles.php:163]
#1  gutenberg_experimental_global_styles_register_user_cpt() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/../data/themedir1/default
theme_has_support: 
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.16
Configuration: /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist

....#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:60]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 
..                                                              6 / 6 (100%)#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:109]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:127]
#1  _gutenberg_add_template_part_area_info() called at [/var/www/html/wp-content/plugins/gutenberg/lib/full-site-editing/block-templates.php:109]
/var/www/html/wp-content/themes/tt1-blocks
theme_has_support: 


Time: 1.44 seconds, Memory: 36.50 MB

OK (6 tests, 70 assertions)
```


> For testing, this is what I've done: hook into an action that runs before the theme is setup: `add_action( 'plugins_loaded', ['WP_Theme_JSON_Resolver', 'theme_has_setup'] )` and add some log statements within the method. Also tried with `setup_theme` hook. Everything looks fine for me (testing with `tt1-blocks` and other default themes and every time they returned the proper value for that particular theme).
> 
> Also, by looking at the code of `get_stylesheet_directory` I don't see that it needs the theme loaded: it uses `get_option('stylesheet')` which returns the active theme

Yeah, so in the tests above, it seems to return the default theme (during tests setup?), sets that as the cache value for `self::$theme_has_support`, and later returns that (even when `get_stylesheet_directory` actually returns TT1 Blocks).

**Comment by ockham** [comment]
So judging from those call stacks, it seems the relevant callsites for `WP_Theme_JSON_Resolver::theme_has_support()` that happen when `get_stylesheet_directory()` still returns the default theme are

https://github.com/WordPress/gutenberg/blob/b6272d9d36b99aa10abcfe815aa407c89d2ef359/lib/client-assets.php#L364

and 

https://github.com/WordPress/gutenberg/blob/b6272d9d36b99aa10abcfe815aa407c89d2ef359/lib/global-styles.php#L163

**Comment by ockham** [comment]
If I load WP in the browser with the above patch, both "early" callsites (`lib/client-assets.php` and `lib/global-styles.php`) actually do "see" TT1 Blocks, rather than the default theme. So it's arguably an issue with unit tests.

**Comment by ockham** [comment]
> If I load WP in the browser with the above patch, both "early" callsites (`lib/client-assets.php` and `lib/global-styles.php`) actually do "see" TT1 Blocks, rather than the default theme. So it's arguably an issue with unit tests.

I tracked the stacktrace for those two back a bit further: It goes back to https://github.com/WordPress/gutenberg/blob/2aefc5b0a587e0839ec67615e2c7fb94f89af6dc/phpunit/bootstrap.php#L84 which I think loads this file from `wordpress-develop`: https://github.com/WordPress/wordpress-develop/blob/234c2b52ccf584cb93dce0eaf17431310b1d7458/tests/phpunit/includes/bootstrap.php

Edit: The latter file comes from `wp-phpunit`: https://github.com/wp-phpunit/wp-phpunit/blob/fefaaf8d086c0401d887661e21dc9e9afdfc0411/includes/bootstrap.php

**Comment by ockham** [comment]
This could be relevant?
https://github.com/WordPress/gutenberg/blob/2aefc5b0a587e0839ec67615e2c7fb94f89af6dc/packages/env/lib/wordpress.js#L86-L110

**Comment by ockham** [comment]
I wonder if that means that the [phpunit container](https://github.com/WordPress/gutenberg/blob/2aefc5b0a587e0839ec67615e2c7fb94f89af6dc/packages/env/lib/build-docker-compose-config.js#L241-L257) isn't using the `phpunit-wp-config.php` copy of `wp-config.php` (without the `require_once ABSPATH . '/wp-settings.php'` call) [as it apparently should](https://github.com/WordPress/gutenberg/blob/2aefc5b0a587e0839ec67615e2c7fb94f89af6dc/packages/env/lib/wordpress.js#L86-L110), but uses `wp-config.php`?

```
npm run test-unit-php -- /var/www/html/wp-content/plugins/gutenberg/phpunit/class-block-templates-test.php

[...]

Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
#0  WP_Theme_JSON_Resolver::theme_has_support() called at [/var/www/html/wp-content/plugins/gutenberg/lib/client-assets.php:364]
#1  gutenberg_register_packages_styles() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
#2  WP_Hook->apply_filters() called at [/var/www/html/wp-includes/class-wp-hook.php:316]
#3  WP_Hook->do_action() called at [/var/www/html/wp-includes/plugin.php:551]
#4  do_action_ref_array() called at [/var/www/html/wp-includes/class.wp-styles.php:135]
#5  WP_Styles->__construct() called at [/var/www/html/wp-includes/functions.wp-styles.php:24]
#6  wp_styles() called at [/var/www/html/wp-includes/functions.wp-styles.php:132]
#7  wp_register_style() called at [/var/www/html/wp-content/plugins/gutenberg/lib/blocks.php:175]
#8  gutenberg_register_core_block_styles() called at [/var/www/html/wp-content/plugins/gutenberg/lib/blocks.php:129]
#9  gutenberg_reregister_core_block_types() called at [/var/www/html/wp-includes/class-wp-hook.php:292]
#10 WP_Hook->apply_filters() called at [/var/www/html/wp-includes/class-wp-hook.php:316]
#11 WP_Hook->do_action() called at [/var/www/html/wp-includes/plugin.php:484]
#12 do_action() called at [/var/www/html/wp-settings.php:560]
#13 require_once(/var/www/html/wp-settings.php) called at [/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/bootstrap.php:191]
#14 require(/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/bootstrap.php) called at [/var/www/html/wp-content/plugins/gutenberg/phpunit/bootstrap.php:84]
#15 include_once(/var/www/html/wp-content/plugins/gutenberg/phpunit/bootstrap.php) called at [phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php:57]
#16 PHPUnit\Util\FileLoader::load() called at [phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php:45]
#17 PHPUnit\Util\FileLoader::checkAndLoad() called at [phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:1058]
#18 PHPUnit\TextUI\Command->handleBootstrap() called at [phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:863]
#19 PHPUnit\TextUI\Command->handleArguments() called at [phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:173]
#20 PHPUnit\TextUI\Command->run() called at [phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:162]
#21 PHPUnit\TextUI\Command::main() called at [/usr/local/bin/phpunit:620]
```

cc/ @noahtallen Can you weigh in if that's the expected behavior?

**Comment by ockham** [comment]
Ah no, that seems unrelated: `wp-env` only removes the `wp-settings.php` import from `phpunit-wp-config.php`, whereas in the call stack, `wp-settings.php` is imported from (`wp-phpunit`'s) `includes/bootstrap.php`.

**Comment by ockham** [comment]
Default theme fallback set here: https://github.com/wp-phpunit/wp-phpunit/blob/fefaaf8d086c0401d887661e21dc9e9afdfc0411/includes/bootstrap.php#L138-L145

**Comment by ockham** [comment]
Maybe this could help? https://github.com/wp-phpunit/wp-phpunit/blob/fefaaf8d086c0401d887661e21dc9e9afdfc0411/includes/bootstrap.php#L177-L188

I.e. using the `wp_tests_options` global to set the theme somehow? We're already using it here: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/phpunit/bootstrap.php#L73-L78

**Comment by ockham** [comment]
Yeah, so this seems to do the trick:

```diff
diff --git a/phpunit/bootstrap.php b/phpunit/bootstrap.php
index 8315c12292..1767a33748 100644
--- a/phpunit/bootstrap.php
+++ b/phpunit/bootstrap.php
@@ -75,6 +75,8 @@ $GLOBALS['wp_tests_options'] = array(
                'gutenberg-widget-experiments' => '1',
                'gutenberg-full-site-editing'  => 1,
        ),
+       'stylesheet' => 'tt1-blocks',
+       'template'   => 'tt1-blocks'
 );
 
 // Enable the widget block editor.
```

However, that'd mean we'd hard-wire the theme (initially) used for testing to TT1 Blocks. I'm not totally sure that's okay, but I guess it is?

**Comment by ockham** [comment]
> Yeah, so this seems to do the trick: [...]

PR: https://github.com/WordPress/gutenberg/pull/30686

**Comment by ockham** [comment]
Updated the issue description to reflect the findings, and to provide better instructions for reproducing.

**Comment by noahtallen** [comment]
> Can you weigh in if that's the expected behavior?

It's definitely weird because we're using the phpunit library instead of the one from core. But it sounds like you figured it out. Related issue about improving phpunit: #23171

**Comment by oandregal** [comment]
Thanks for the [instructions](https://github.com/WordPress/gutenberg/issues/30478#issuecomment-816630565), Bernie. If I understood this correctly, it looks like there's an issue when a theme is switched _programatically_ but doesn't happen on a normal WordPress request. I understand this can be an issue beyond unit tests theoretically, although I'm not sure under what practical conditions.

Anyway, it sounds like what we need to do is cleaning all the cached values upon a theme switch so they can be recalculated. Prepared https://github.com/WordPress/gutenberg/pull/30830
