### ISSUE TITLE
Documentation: Unclear sentence of Code Implementation

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#30474]
@janw-me  @mkaz 
https://github.com/WordPress/gutenberg/blob/trunk/docs/getting-started/tutorials/create-block/block-code.md

> This function handles that all style en js files in the build folder get handles that are passed on to the wp_register_style function.

Above sentence was added recently, but is difficult for me to follow it.

1. Is the 'en' 'and' or 'in'?
2. What is the subject of "get handles"?

By the way, the updates of tutorial were great work. Thank you!

**Comment by janw-me** [comment]
'en' is the Dutch wordt for 'and' so my bad ;)

But the whole sentence was a bit unclear, I've rephrased it.

**Comment by mkaz** [comment]
Closed en #30487 ;-)
