### ISSUE TITLE
Global styles classes comes all with "!important" declaration in Gutenberg plugin 10.3

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#30489]
Hey,

after updating to Gutenberg plugin 10.3 the global style classes which are added inline to the HTML document are all declared with "!important":

<img width="737" alt="Bildschirmfoto 2021-04-03 um 11 09 12" src="https://user-images.githubusercontent.com/31563167/113474004-657d7900-946d-11eb-93a4-2703ed323758.png">

That leads to issues.

An example:

I have the class "has-huge-font-size" with a size of 35px on the desktop.

Before, I was able to display such a large heading in CSS smaller if the screen width is less than 768px.

Now none of this works anymore because these classes are all delivered with "!important".

Please remove "!important" from this inline styles again.

**Comment by skorasaurus** [comment]
Thanks for reporting; 
This has been reported in https://github.com/WordPress/gutenberg/issues/29985. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
