### ISSUE TITLE
Site Title letter case not working in Gutenberg plugin 10.3

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30485]
## Description

Site Title block - Letter case is not working in the latest Gutenberg 10.3.1 plugin.

## Step-by-step reproduction instructions
1. Use TT1
2. Try can change the Letter case to one of the options.
3. Does not work.

## Expected behaviour
For it to work.

## Actual behaviour
No reaction when clicking lower or mixed case options.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5323259/113470849-d23a4880-9458-11eb-9eaf-8ced1218ffa5.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1

**Comment by carolinan** [comment]
I found that the options inline style is only applied to the heading element, while the style from the theme.json file is applied
to both the heading and the link element.
This is also breaking the font size option.

**Comment by youknowriad** [comment]
It doesn't make sense to apply the theme.json style to the inner a IMO.
