### ISSUE TITLE
Font size errors with Site Title block in Gutenberg plugin 10.3

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30484]
## Description

I wanted to make two specific changes to the Site Title block.
Change the Font size or adjust the Custom size

## Expected behaviour
I expected both to work correctly.

## Actual behaviour
Font did not change in size. Only the container area changed.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5323259/113470597-13315d80-9457-11eb-97c4-1da1c01fd928.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1

**Comment by youknowriad** [comment]
Judging by the screenshot, it seems to work as intended for me, I'm not sure I understand the issue?

**Comment by paaljoachim** [comment]
Click the play button Riad..:)

**Comment by youknowriad** [comment]
I did :)

**Comment by youknowriad** [comment]
Oh it's not changing the font size at all 🤯

**Comment by youknowriad** [comment]
So this is basically the same issue as #30485

**Comment by paaljoachim** [comment]
It seems like it.
