### ISSUE TITLE
Bug with select of styles via select list 

### ISSUE THREAD

**Issue by Quintis1212** [WordPress/gutenberg#30495]
Hi ) I found out that I can not change default styles of quote via select if selected item in the block menu.
![Знімок екрана з 2021-04-04 20-28-59](https://user-images.githubusercontent.com/34488718/113516974-f6e00e80-9585-11eb-891a-5c80ae90de9b.png)

Steps to reproduce : 
1) Create quote block and type a string to it 
2) Change a style of block by selecting item from select list under string "Default Style" in block menu

Notice that there is no changes

**Comment by Quintis1212** [comment]
My fix - https://github.com/WordPress/gutenberg/pull/30494

**Comment by stokesman** [comment]
The select list isn't meant to change the style of the selected block. It's meant to change the style of any new blocks added afterward.

That setting is unlike everything else in the block settings sidebar so I see the potential for misunderstanding. Maybe a better place for that setting could be found.

**Comment by jordesign** [comment]
The default select box for Quote blocks is no longer available in the sidebar, so closing this issue.
