### ISSUE TITLE
Error on delete nav item

### ISSUE THREAD

**Issue by Quintis1212** [WordPress/gutenberg#30492]
Hi , I founded bug , that if you delete last nav item fom nav menu you will get error :
![Знімок екрана з 2021-04-03 14-55-04](https://user-images.githubusercontent.com/34488718/113477774-f9127200-948c-11eb-99ce-f6f9ca64b934.png)
![Знімок екрана з 2021-04-03 15-00-36](https://user-images.githubusercontent.com/34488718/113477826-61615380-948d-11eb-9f58-ec33c8eff0ce.png)

Steps to reproduce : 
1 Create nav block
2 Click on add all pages button
3 Delete pages one by one
4 When you wll end to delete last page you will get error

I do not know how to fix this . Console error says that "Cannot read property 'mode' of undefined" , but when I pressed on delete key  mode constant was logged in the console as in the picture above. Who can help me whith this issue ?

**Comment by paaljoachim** [comment]
Hi

Check out this issue. I believe it is the same you are encountering:
https://github.com/WordPress/gutenberg/issues/29498

If so then you can close your issue.
Have a great Easter Sunday!

**Comment by Quintis1212** [comment]
Hi @paaljoachim  , it seems it is the same issue , I close this issue .Have a great Easter Sunday too !
