### ISSUE TITLE
Revisit the bundled Query Block patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#30508]
@jasmussen [and I worked on a few initial Query block patterns](https://github.com/WordPress/gutenberg/pull/28891#discussion_r575489669) to be bundled with Gutenberg as part of https://github.com/WordPress/gutenberg/pull/28891:

Large|Medium|Small
---|---|---
<img width="657" alt="107961753-5487af80-6f74-11eb-886e-9cb84f330031" src="https://user-images.githubusercontent.com/1202812/113591324-bde57f80-9601-11eb-8871-9f6bb88e8224.png">|<img width="682" alt="107961775-5782a000-6f74-11eb-9dc2-61815b06f104" src="https://user-images.githubusercontent.com/1202812/113591326-be7e1600-9601-11eb-8b37-cd81dcf3985f.png">|<img width="668" alt="107961784-5baebd80-6f74-11eb-8bb7-cbad36c9f45b" src="https://user-images.githubusercontent.com/1202812/113591328-be7e1600-9601-11eb-9bfb-7c515b2aa545.png">

Those were always meant to be temporary to start with. Let's take another look at these, both to replace the current ones for now, but also so that we eventually have a nice set of WordPress community-designed query block patterns to add to the [Pattern Directory](https://make.wordpress.org/design/2021/03/30/wordpress-org-patterns-directory/) at launch. 

Let's use this thread to brainstorm possible designs. 🌟

**Comment by kjellr** [comment]
Here are a handful of explorations to start us off. Most of these are a bit non-traditional, so we'd want to balance with some more standard layouts too I imagine. Also, note that the bottom one would need some direction forward on https://github.com/WordPress/gutenberg/issues/30380. 

![block-patterns-query](https://user-images.githubusercontent.com/1202812/113596673-a78ef200-9608-11eb-8d10-1de6d3efcf1a.png)

**Comment by paaljoachim** [comment]
Here are lots to get inspired by....


https://www.harvestmagazine.no/

A Card View (somewhat similar to how Media&Text Block)

![Harvestmagazine-post-preview-styles](https://user-images.githubusercontent.com/5323259/113712529-88ff2880-96e6-11eb-821a-ab769a5182a8.jpg)

A variation to the above Card view.

![Image-Text-Custom-Post-Preview](https://user-images.githubusercontent.com/5323259/113712555-91effa00-96e6-11eb-952c-396907ebd19b.jpg)

Image view.
![Image-view-alt-Custom-Post-Preview](https://user-images.githubusercontent.com/5323259/113712664-b0ee8c00-96e6-11eb-890b-134702f90613.jpg)

Originally posted here:
https://github.com/MediaRon/post-type-archive-mapping/issues/72

------

A few additions.

https://www.wired.com/

![Wired-magazine](https://user-images.githubusercontent.com/5323259/113713745-f95a7980-96e7-11eb-8942-8bb42dc13a32.jpg)


https://pixelgrade.com/themes/portfolio/gema/ref/3/

![Gema-Blog-page](https://user-images.githubusercontent.com/5323259/113713861-14c58480-96e8-11eb-9356-ca1390591b15.jpg)


https://www.helpscout.com/blog/

![Helpscout-blog](https://user-images.githubusercontent.com/5323259/113714757-075cca00-96e9-11eb-8267-ca593360e868.jpg)

https://blog.hubspot.com/blog/tabid/6307/bid/34143/12-Inspiring-Examples-of-Beautiful-Blog-Homepage-Designs.aspx

http://www.fubiz.net/


![fubiz-blog](https://user-images.githubusercontent.com/5323259/113715237-8e11a700-96e9-11eb-82da-ce24355e016c.jpg)

---

![fubiz-blog2](https://user-images.githubusercontent.com/5323259/113715232-8c47e380-96e9-11eb-9a58-c7c210f31b8f.jpg)

-

https://www.brit.co/

![Brit-co-blog](https://user-images.githubusercontent.com/5323259/113715826-3a538d80-96ea-11eb-98f9-1f289856d25e.jpg)

------------

![Brit-co-blog2](https://user-images.githubusercontent.com/5323259/113715835-3c1d5100-96ea-11eb-80af-f3ad25c70705.jpg)


----
-----------------
-----



![Tesco-blog-old](https://user-images.githubusercontent.com/5323259/113716043-74249400-96ea-11eb-9ddb-3fa11d161b8c.jpg)


---------------
---



https://johnnycupcakes.com/


![Johnnycupcakes](https://user-images.githubusercontent.com/5323259/113716564-075dc980-96eb-11eb-83df-a5281b47f899.jpg)

**Comment by paaljoachim** [comment]
Even more.

I searched for card view designs and happened to come across this site. Lots of nice designs there.
https://bashooka.com/cms/beautiful-card-based-wordpress-themes/

![Grand](https://user-images.githubusercontent.com/5323259/113717977-7982de00-96ec-11eb-993d-a3d9715960f0.jpg)

-

![Beatstone](https://user-images.githubusercontent.com/5323259/113717955-725bd000-96ec-11eb-8611-a16de606456c.jpg)

-

![Bizly](https://user-images.githubusercontent.com/5323259/113717959-74259380-96ec-11eb-8f67-0acdb1f3f7ea.jpg)

-

![La-Madone](https://user-images.githubusercontent.com/5323259/113718020-89022700-96ec-11eb-9e27-1b9bf0416d3c.jpg)

-

![Linetime](https://user-images.githubusercontent.com/5323259/113718122-9f0fe780-96ec-11eb-860b-1be8a3018236.jpg)

-

![Home-grid](https://user-images.githubusercontent.com/5323259/113718131-a2a36e80-96ec-11eb-8fd5-7ece1d1f8a97.jpg)

**Comment by beafialho** [comment]
Here are a few query block patterns I've been working on as well:

<img width="1199" alt="Captura de ecrã 2021-04-06, às 14 50 14" src="https://user-images.githubusercontent.com/65220155/113721427-6faaac00-96e7-11eb-8df4-091aaede1ac7.png">
<img width="1208" alt="Captura de ecrã 2021-04-06, às 14 48 44" src="https://user-images.githubusercontent.com/65220155/113721270-48ec7580-96e7-11eb-8b08-784ad082c28c.png">
<img width="1207" alt="Captura de ecrã 2021-04-06, às 14 48 57" src="https://user-images.githubusercontent.com/65220155/113721283-4be76600-96e7-11eb-8b8b-5b0564a8fd4f.png">

**Comment by melchoyce** [comment]
A couple more generic ideas:

![query blocks](https://user-images.githubusercontent.com/2846578/113915557-ec538e00-97ac-11eb-97c3-27e32cd7d394.png)

**Comment by georgeolaru** [comment]
A while ago, we designed a [block](https://github.com/pixelgrade/nova-blocks/issues/190) that uses a set of parametric variables to generate a variety of layouts and put cards together in a visual hierarchy. It might be outside the scope of this issue as it relates to the overall layout, but I leave it here as it could spark some ideas for someone.

Here is the [full video](https://pixelgrade.com/wp-content/uploads/2020/09/posts-collection-on-pixelgrade-blog-1.mp4)  with a demo:

![Screenshot 2021-04-08 at 12-06](https://user-images.githubusercontent.com/1632775/113999933-2c754800-9863-11eb-9a31-27a8a8ed4288.gif)

**Comment by aadi704** [comment]
Here are some of the ideas :
![Frame 7Blue](https://user-images.githubusercontent.com/47731436/114195057-c32e2b80-996d-11eb-87c6-5f343030cbdc.png)
![Frame 8Orange](https://user-images.githubusercontent.com/47731436/114195178-dd680980-996d-11eb-85ed-8d34a3ebd823.png)
![Frame 9Green](https://user-images.githubusercontent.com/47731436/114195304-f96bab00-996d-11eb-9f06-44966199ae94.png)

**Comment by aaditya704** [comment]
Here are some more ideas:
![Frame 7Blue](https://user-images.githubusercontent.com/40461868/114196251-d1c91280-996e-11eb-830a-e86e42db1957.png)
![Frame 8Orange](https://user-images.githubusercontent.com/40461868/114196298-dbeb1100-996e-11eb-9713-fb03523c35d7.png)
![Frame 9Green](https://user-images.githubusercontent.com/40461868/114196328-e3aab580-996e-11eb-986e-599c3034049c.png)

**Comment by ntsekouras** [comment]
Hey 👋 - just keep in mind the the pattern integration is still experimental and is being worked on with the various issues/PRs about this, like patterns in Placeholder, transforms etc..

Latest update is that the experimental `scope` was removed and `blockTypes` has taken its place (https://github.com/WordPress/gutenberg/pull/30471). The rationale behind this is that every pattern should be available in the `Inserter`.

See the PR's description for more details.

**Comment by markhowellsmead** [comment]
Not every post has a featured image; over half of our agency clients either don't have imagery or don't want to spend time trying to find stock imagery for their posts. It would be great if the layouts worked both with and without images in every post, either using a configurable fallback image, background color or pattern.

**Comment by mtias** [comment]
This has been revised already.
