### ISSUE TITLE
Site Editor: <style> elements in groups complicates CSS targeting

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30500]
This one was tricky to search for, so apologies in advance if this has already been discussed somewhere. If it has, feel free to link to it and close this issue.

The Site Editor outputs inline `<style></style>` elements with layout styles after group blocks, like this:

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/8181091/113572645-ed53b680-9618-11eb-8f3a-329de9c8b4ce.png">

(This section has two nested group blocks: an outer wide group with a background, and an inner group with "Inherit default layout" checked to center it within the outer group and match its width to the content width.)

I frequently remove the bottom margin of the last descendant of certain blocks, like the group block, to keep the inner spacing even. However, with the <style> element appended to the bottom of the element, I can't target the last descendant using `.wp-block-group > *:last-child`. The result is that the outer div has more spacing in the bottom than in the top, as you can see in the image (the extra space beneath the button). I could target `.wp-block-group > div:last-of-type`, but that would hit the last div in the group even if that div is followed by other, non-<style> elements.

_Edit, side note: The style element is included in the Block Editor as well, but prepended instead of appended, so in the editor, `> *:last-child` works but `> *:first-child` doesn't._

## What is your proposed solution?
The only solution I can think of is to move the <style> elements out of the groups and collect them somewhere else, but I'm assuming they have been put where they are with good reason, so this is mostly a heads-up that it will complicate certain CSS targeting.

**Edit:** See [comment below](https://github.com/WordPress/gutenberg/issues/30500#issuecomment-813938781) for a suggestion on a different solution.

**Comment by andersnoren** [comment]
I've thought a bit more about this, and it would be possible to work around the `<style>` element if it was added to the beginning of the `.wp-container-[xxx]` wrapper instead of to the end, with the added benefit that it would match the behavior in the block editor (where it is added to the beginning of the wrapper already).

If the <style> element was prepended, like in the block editor, you could target the first non-<style> descendant like this:

```
[class*="wp-container-"] > *:first-child,
[class*="wp-container-"] > style:first-child + * {}
```

...which sure isn't pretty, but works.

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/8181091/113682423-6c052e00-96c3-11eb-8245-2b28d21f99c6.png">

**Comment by aristath** [comment]
If I understand correctly the issue is that `.block-group > *:last-child` doesn't work as expected?
Would `.block-group > *:not(style):last-child` work? 🤔

**Comment by andersnoren** [comment]
> If I understand correctly the issue is that .block-group > *:last-child doesn't work as expected?

Yeah. Groups, and any container block (group, cover, column etc.) that ends with a group with `Inherit default layout` checked in the layout settings. The `<style>` is added directly after the group with that setting checked. (I think group is the only block that has that setting.)

`*:not(style):last-child` will hit the last child if the last child isn't a `<style>`, but if the last child is a `<style>`, it won't hit anything.

**Comment by ellatrix** [comment]
I completely agree. I'll look for a solution.

**Comment by ellatrix** [comment]
Solution in #32083.
