### ISSUE TITLE
Post Comments & Post Comments Form Block: Provide HTML5 markup by default

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#30502]
As noted by @andersnoren in https://github.com/WordPress/theme-experiments/issues/245, the Post Comments block will only output the HTML5 semantic version of the comments markup if themes opt-in via the following `add_theme_support()`:

```
add_theme_support( 'html5', array( 'comment-form', 'comment-list' ) );
```

Considering HTML5 is over 6 years old now, it seems reasonable for block based themes to output the HTML5 version by default without requiring the `add_theme_support` opt-in.

**Comment by jordesign** [comment]
Closing this issue as the Legacy Comments block has been deprecated.
