### ISSUE TITLE
[FSE] Quick Inserter not always available after adding Paragraph Block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30516]
## Description

This is feedback from the [fourth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/25/fse-program-testing-call-4-building-a-restaurant-themed-header/#comment-1467):

> Pressing return within a paragraph block doesn’t add a new block or even create a line break.
> I am able to create before/after blocks using the buttons, but unable to do so with keyboard only navigation. Here’s a quick screencast showing that: https://share.getcloudapp.com/2NuwAX0N

## Step-by-step reproduction instructions

1. Set up a test site with the latest version of Gutenberg and the TT1 blocks theme.
2. Head to the Site Editor (beta) tab.
3. Add a paragraph block underneath the Site Title Block using the + button from the Quick Inserter.
4. Notice that the Quick Inserter disappears and you're only able to add new blocks using the Slash Inserter (`/`). 

## Expected behaviour

Expect to still see the quick inserter available for use. 

## Actual behaviour

The quick inserter (mostly) disappears/isn't visible. 

## Screenshots or screen recording (optional)

This is a bit of a longer video showing the inconsistency:

https://user-images.githubusercontent.com/26996883/113638848-0d916e80-9635-11eb-8e9e-ada4e00df546.mov

Here's a shorter, more to the point video showing the exact problem:

https://user-images.githubusercontent.com/26996883/113639359-36feca00-9636-11eb-922e-a5a74435aab1.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 88

**Comment by costdev** [comment]
See [Trac 54687](https://core.trac.wordpress.org/ticket/54687) for similar behaviour in other editors and in multiple themes. Reported by @alanjacobmathew.

**Comment by kathrynwp** [comment]
I'm still able to replicate this with:

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
Twenty Twenty-Two 1.2

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this in 6.2.2 and GB  15.9.0-rc.2:

https://github.com/WordPress/gutenberg/assets/3629020/b391d32b-d911-42d7-ab82-11b62f0fba21

**Comment by annezazu** [comment]
Can no longer replicate with 6.6.1. Closing out. Thanks, past Anne.
