### ISSUE TITLE
Query Pagination block is output when empty

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30522]
## Description
The wrapping div of the Query Pagination block is output when there are no previous/next/number links to display in it, which can result in extra margins on the page. It's extra noticeable if the block has a custom block style, like this one with vertical borders:

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/8181091/113678081-88eb3280-96be-11eb-8a78-b1757b8f7f14.png">

The screenshot shows a custom theme with a custom block style applied, but it behaves the same in TT1 Blocks without the block style.

## Step-by-step reproduction instructions
1. Activate TT1 Blocks.
2. Set the "Blog pages show at most" option in Settings → Reading to a higher number than the number of posts on the site.
3. View the blog and inspect the Query Pagination block.

## Expected behaviour
The wrapping div of the Query Pagination block shouldn't be output when empty.

## Actual behaviour
The wrapping div is output when the block is empty.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Safari 14.0.3

**Comment by alaczek** [comment]
I wasn't able to reproduce but I might be missing something. 

> View the blog and inspect the Query Pagination block.

How exactly did you create/set up the blog?

**Comment by Mamaduka** [comment]
It should be fixed via #33635.

**Comment by Mamaduka** [comment]
Hi, @andersnoren

I just merged PR that fixes this issue.
