### ISSUE TITLE
Further group the changelog in subcategories using PR name prefixes or labels.

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#30538]
## What problem does this address?

Currently, the automatically generated changelog groups merged PRs depending on some of their labels (bug, enhancement, etc.), grouping unmatched PRs under a "Various" category that needs to be manually worked on when making a release. Moreover, in the final changelog, there is a second grouping level by functionality (Block Library, Global Styles, Customizer, etc.) under each main category, done manually, with the added difficulty that merged PRs sometimes don't have consistent enough naming to do so.
## What is your proposed solution?

In preparation for the [Gutenberg 10.4 RC](https://github.com/WordPress/gutenberg/milestone/146?closed=1), triage of the PRs that will ship with this release is underway, prefixing each of them with the corresponding subcategory (Block Library, Global Styles, etc.). This will allow the release manager to more easily group PRs. Ideally, the final changelog could take into account these new prefixes or other labels used. However, there are some hindrances:
- Labels are not mutually exclusive, so nothing prevents a single PR from having contradictory labels (both as the main category and as a subcategory, e.g. pertaining to different blocks).
- Subcategory prefixes should be defined and documented so that contributors know how to properly (re)name PRs.
- Some subcategories currently have a special treatment, such as the "Navigation Editor and block": Navigation block PRs are not cataloged under "Block Library / Navigation" but under this special subcategory.

**Comment by gziolo** [comment]
Awesome ideas, thank you for opening this issue. It greatly aligns with the experience I had during my last plugin release.

Bonus points for sorting all entries in the section by the name like in https://make.wordpress.org/core/2021/04/02/whats-new-in-gutenberg-10-3-31-march/, examples:

> ### Enhancements
> 
> -   Add `since` versions to the deprecated features. ([30072](https://github.com/WordPress/gutenberg/pull/30072))
> -   Blocks: Add "theme" category and better present Template Parts in the inserter. ([30020](https://github.com/WordPress/gutenberg/pull/30020))
> -   Block Editor:
>     -   Add drag handle to select mode. ([28815](https://github.com/WordPress/gutenberg/pull/28815))
>     -   Improve block inserter keyboard navigation. ([26938](https://github.com/WordPress/gutenberg/pull/26938))
>     -   Open admin sidebar menu over editor on small screens. ([29955](https://github.com/WordPress/gutenberg/pull/29955))
> -   Block Library:
>     -   Cover: Allow drag and drop media replacement. ([29813](https://github.com/WordPress/gutenberg/pull/29813))
>     -   File: Make the editor markup match the frontend. ([30148](https://github.com/WordPress/gutenberg/pull/30148))
>     -   Social Links: Improve selected state of empty block. ([29756](https://github.com/WordPress/gutenberg/pull/29756))
>     -   Standardize the groups in the block toolbar. ([30012](https://github.com/WordPress/gutenberg/pull/30012), [29247](https://github.com/WordPress/gutenberg/pull/29247), [29863](https://github.com/WordPress/gutenberg/pull/29863))
>     -   Verse block: Add support for the padding to the verse block. ([29820](https://github.com/WordPress/gutenberg/pull/29820))

> ### Bug Fixes
> 
> -   Block Library:
>     -   Cover: Improve disabled media buttons check for placeholder. ([29858](https://github.com/WordPress/gutenberg/pull/29858))
>     -   Embed:
>         -   Fix overzealous aspect ratio scaling for embeds. ([29510](https://github.com/WordPress/gutenberg/pull/29510))
>         -   Embed: Fix select on focus. ([29431](https://github.com/WordPress/gutenberg/pull/29431))
>     -   Gallery: Fix gallery item clicking. ([29860](https://github.com/WordPress/gutenberg/pull/29860))
>     -   Image:
>         -   Fix block reset sizes on external URL change. ([26879](https://github.com/WordPress/gutenberg/pull/26879))
>         -   Fix undo step with temporary URL. ([30114](https://github.com/WordPress/gutenberg/pull/30114))
>     -   Social Link: More accessible labels. ([29659](https://github.com/WordPress/gutenberg/pull/29659))
>     -   Video: Fix kind attribute missing subtitle value in video text track. ([30040](https://github.com/WordPress/gutenberg/pull/30040))


The file with the code that generates the changelog is in:

https://github.com/WordPress/gutenberg/blob/trunk/bin/plugin/commands/changelog.js

There are also some unit tests that should make the whole process more enjoyable:

https://github.com/WordPress/gutenberg/blob/trunk/bin/plugin/commands/test/changelog.js

**Comment by getdave** [comment]
> It greatly aligns with the experience I had during my last plugin release.

Agreed. This also aligns with my experience. This would be a great upgrade.

**Comment by getdave** [comment]
I believe this has been addressed by https://github.com/WordPress/gutenberg/pull/33229. I'm going to close out as suggested by @gziolo https://github.com/WordPress/gutenberg/issues/33719#issuecomment-889127547.
