### ISSUE TITLE
Width issue on the editor sidebar calendar help popover

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#30532]
## Description
There's a width issue the editor sidebar calendar help popover; causing this popover to have a very small width.

## Step-by-step reproduction instructions
- Open a post or a page in the editor
- In the editor sidebar, click on the date near the "Publish" option
- Click on the "Calendar help" link

## Expected behaviour
The calendar help popover should have a consistent width with the date/time picker.

## Actual behaviour
The calendar help popover has a very tiny width.

## Screenshots or screen recording (optional)
![CleanShot 2021-04-06 at 15 38 00](https://user-images.githubusercontent.com/33403964/113728688-36296f00-96ee-11eb-9d5b-8849e9effab2.gif)

## WordPress information
- WordPress version: 5.8-alpha-50663
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS Big Sure 11.3
- Browser: Firefox Developer Edition

**Comment by JustinyAhin** [comment]
A possible solution for this would be to add `width: max-content;` to the calendar help popover.
But it'll overflow a bit the sidebar width and enters the editor content, and also causes some issues on mobile.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/33403964/113729222-b94ac500-96ee-11eb-9a9f-477be36e4197.png">

![CleanShot 2021-04-06 at 15 44 35](https://user-images.githubusercontent.com/33403964/113729634-18a8d500-96ef-11eb-88aa-73f988da462a.gif)

What I found the most viable would be to define a fixed width for the popover, based on the width of the date/time picker; but I'm not very sure about how fixed width are handled in Gutenberg.

**Comment by jordesign** [comment]
Closing this issue as we no longer show the 'calendar help' option in the date picker.
