### ISSUE TITLE
Proposal: New `@wordpress/types` package

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/gutenberg#30536]
## What problem does this address?
Currently there's no where for general core types to live that aren't owned by or make sense to be owned by a specific package.

For example, the DefinitelyTyped version of `api-fetch` exports a `Schema` namespace that is consumed by several packages to generate their type definitions.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wordpress__api-fetch/index.d.ts#L62

However, I don't think that it makes sense for `api-fetch` to house these types as they're not at all related to `api-fetch` in any way. It seems that it was just a convenient place to house them in order to share them across multiple packages without introducing a new one.

I don't think that's the right solution though. We could, for example, shoehorn those types into the `api-fetch` package, but it misdirects the dependency tree in that case if a package only needs the `Schema` types but doesn't consume the actual `api-fetch` package's runtime.

## What is your proposed solution?
I'd like to propose adding a new "types only" `@wordpress/types` package that would contain _only_ TypeScript types and nothing else. It would have zero runtime and only export types.

This could house any and all "general" shared types, especially things like the types for `Post` `User` `Category` etc, things that are core to building strictly typed interfaces for WordPress packages but don't have any business being owned by any of the existing packages.

The package would only ever be consumed in the Gutenberg repo using the `import type` declaration (given our rules require this type of import for types) so I don't think it would expose a new `wp` global namespace but I'm not sure about that (/cc @youknowriad @gziolo who may know more about the infrastructure of that).

## How do other projects solve this problem?

Reakit has a `reakit-utils` package with a `types` module (accessible by importing from `reakit-utils/types`). However we don't really have a "utils" package aside from `compose` and I don't think it makes sense for `Schema` to live there either.

I'm not sure how other projects solve this aside from Reakit (as I have experience consuming those types). I think this may be a specifically "monorepo" flavor of problems too, and I don't have much experience with monorepos aside from Gutenberg.

## Background

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52205#issuecomment-814116843

**Comment by youknowriad** [comment]
Hey there! thanks for the issue, while I don't have a particular issue against a "types" package holding generic things like that, it seems to me, that most of the types in the link you shared are things that are meant to be in `@wordpress/core-data` instead. 

Most of these looks like "Entities related data" and while we still have some adhoc usage of apiFetch, the plan has always been to consider `@wordpress/core-data` as the middleware between the backend and the frontend for packages that require access to this data.

**Comment by sarayourfriend** [comment]
> the plan has always been to consider @wordpress/core-data as the middleware between the backend and the frontend for packages that require access to this data.

That makes sense to me. Are there other packages that could depend on this that wouldn't depend on `core-data`'s runtime though? I think that's the crux of it for me, as far as answering whether we should have a new package or not just for types.

**Comment by youknowriad** [comment]
> Are there other packages that could depend on this that wouldn't depend on core-data's runtime though?

I can't think of any like that, but an exception is always possible but I guess it should be treated as an exception if it's the case.

**Comment by sarayourfriend** [comment]
Cool, so is the correct solution to move these types into the `core-data` DefinitelyTyped package for now then with the expectation that once `core-data` is typed that it will export these types as well?

**Comment by youknowriad** [comment]
@sarayourfriend this makes sense to me yes.
