### ISSUE TITLE
Mobile: Splitting a Quote block citation results in nested cite tags

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#30548]
## Description
When I split a Quote block citation (type some text in the citation and split it in the middle with a new line), two new lines are created.

## Step-by-step reproduction instructions

1. Add a quote block
2. In the citation section, type a few words
3. In the middle of the citation, hit return
4. Notice that two new lines are created instead of a single one

## Expected behaviour

Typing enter in a quote citation should just create a new line.

## Actual behaviour

Typing enter in a quote citation create what looks like two new lines. Inspecting the editor HTML contents reveals that extra `<cite>` tags – and extra `<p>` tags – are added.

```
<!-- wp:quote -->
<blockquote class="wp-block-quote">
   <p></p>
   <cite>
      <p><cite>This is </cite></p>
      <p><cite><br></cite></p>
      <p><cite>a citation</cite></p>
   </cite>
</blockquote>
<!-- /wp:quote -->
```

## Screenshots or screen recording (optional)

<img width="426" alt="Screen Shot 2021-04-06 at 17 50 37" src="https://user-images.githubusercontent.com/1898325/113782714-9e814c00-9700-11eb-81e5-348a9199b82a.png">

## Device information
- Device: iPhone 11
- Operating system: iOS 14
- WordPress app version: 17.1.0.0 (also seen in Gutenberg demo app commit e7369c09f468158e42851ba2a5b1b58efbd4ca88)

I haven't tested Android or other block yet to see if they are affected.

**Comment by jd-alexander** [comment]
I did a test of this with Android and I did not notice this behavior. I tested using `17.1-rc-1`

**Comment by guarani** [comment]
Adding more info (thanks to @ceyhun for digging into this): The change that caused this regression is https://github.com/WordPress/gutenberg/commit/54d6668d3b9b374bb45a837cd1f771e6c34ffe50 (part of https://github.com/WordPress/gutenberg/pull/30190). Specifically it's this prop that's now passed to the `<RichText>` component that powers the quote citation:

https://github.com/WordPress/gutenberg/blob/9c09a52f34822c61b264d25f3e8e87c3f3a2d3c5/packages/block-library/src/quote/edit.js#L85
