### ISSUE TITLE
Alignment control is missing from Group within another Group

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#30543]
## Description

When inserting group block(s) within another group block, the width control is missing from the inner group block(s).

## Step-by-step reproduction instructions

1. Edit/add a post/page
2. Insert a group block
3. Insert another group block (or any block with width control such as columns block) somewhere inside the first group block
4. Notice the width control (Wide width or Full width selection) is missing from the inner group block

## Expected behaviour

All group blocks (or other block with width control such as columns) should have width control, regardless of whether inside another group or not.

## Actual behaviour

Any block that should have width control when placed inside another block with width control is missing the width control.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks

## Device information
- Device: Desktop
- Operating system: W10
- Browser: Chrome and Firefox

**Comment by talldan** [comment]
My results from testing on `trunk`

- TT1 Blocks: The group block doesn't have alignment options at all (regardless of whether it's in another group):
<img width="629" alt="Screenshot 2021-04-07 at 12 27 10 pm" src="https://user-images.githubusercontent.com/677833/113810340-9d056180-979c-11eb-9180-7d5909f64b54.png">

- TT1 (normal): The group block does have alignment options, and the reported issue couldn't be reproduced
<img width="847" alt="Screenshot 2021-04-07 at 12 30 01 pm" src="https://user-images.githubusercontent.com/677833/113810510-008f8f00-979d-11eb-88f1-a9833a8f9afb.png">

**Comment by Sandstromer** [comment]
This is my results testing with TT1-Blocks

First "outer" group (pink background) with Full and Wide width controls present:
![group-block-1](https://user-images.githubusercontent.com/76742815/113838834-12fece00-9787-11eb-9a0b-f16432c05d23.jpg)

Within the first group, added a group block (black background), alignment control is missing.
Also a cover block, Full and Wide options are missing from the alignment control:
![group-block-1-ab](https://user-images.githubusercontent.com/76742815/113839343-84d71780-9787-11eb-8df8-4d58087007d5.jpg)

Using the new "Inherit default layout" option on the inner group block.
We can see that there are issues with this;
1. the group does not inherit the default width, only the group's content (paragraph in this case) inherits the default width
2. there is no way to make the inner blocks full width, this leads to issues such as not being able to add a full width cover inside a wide or default width group or template
![group-block-inherit](https://user-images.githubusercontent.com/76742815/113840067-34ac8500-9788-11eb-9d19-28dd557c7629.jpg)

**Comment by carolinan** [comment]
I thought this is how it was intended.

The inner block only has width controls if the parent block has **Inherit default layout** enabled or has a specific width set to either the Content or Wide. Is that correct @youknowriad ?

**Comment by youknowriad** [comment]
This is intended, unless you define a layout for a container block, its children won't have these options because we don't know how to style them.

**Comment by Sandstromer** [comment]
Previously we could have _group (wide or default)_ > _group (full width)_ with the inner group being able to go full width even though it was inside a narrower block.

Now though the full width option is missing, this is not possible, we can only have inner blocks that max out at the width of the parent block.

Are there any plans to bring this functionality back in some way? Without this, a lot of previously designed templates/patterns etc will not function as before.

**Comment by youknowriad** [comment]
> Previously we could have group (wide or default) > group (full width) with the inner group being able to go full width even though it was inside a narrower block.

I think you can still do that, just define the layout of the inner "group" block in its sidebar or check the "inherit layout"

**Comment by Sandstromer** [comment]
> 
> 
> > Previously we could have group (wide or default) > group (full width) with the inner group being able to go full width even though it was inside a narrower block.
> 
> I think you can still do that, just define the layout of the inner "group" block in its sidebar or check the "inherit layout"

The full width option is not there, so this is not possible.

Defining the inner group block width to say 100% (or even 200%) gives a width of 100% of the parent block, and selecting "inherit layout" gives a width of the theme defined default width. None of these are full width.

Also the cover block does not have the "Layout" control in the sidebar, and now the only alignment options available are align left/center/right with the full (and wide) alignment options no longer present.

**Comment by youknowriad** [comment]
I'm not sure I understand what you're trying to do to be honest, can you give a screenshot of the result?

**Comment by Sandstromer** [comment]
> 
> 
> I'm not sure I understand what you're trying to do to be honest, can you give a screenshot of the result?

The pink background is the parent group block with a default width.

For example, previously we could have a cover block within the pink group block, and give it a "Wide" width:
![cover-wide-width](https://user-images.githubusercontent.com/76742815/113872373-b9f56100-97ab-11eb-9616-23b42c8c3e62.jpg)

Or a "Full" width:
![cover-full-width](https://user-images.githubusercontent.com/76742815/113872429-c974aa00-97ab-11eb-980a-b374c177bb94.jpg)

But now we are limited to the cover block being a maximum width of the parent block (minus the padding because of the background color):
![cover-missing-wide-full-widths](https://user-images.githubusercontent.com/76742815/113872614-f032e080-97ab-11eb-9f75-085fcafa574b.jpg)

**Comment by youknowriad** [comment]
Do you want the child block to exceed the parent block's boundaries or is it just for illustration? 

Anyway, let's assume we have `A > B > [ C, D, E ]` 

 - A is the grand parent
 - B às the parent
 - C need to be centered
 - D need to be wide
 - E need to be full

I'm going to assume that we're in the post editor (which means we already have a layout defined coming from theme.json by default)

So you have to do this:

 - A need to be full width (because by default it gets centered since in the post editor there's a layout defined by default)
 - A shouldn't have any layout defined that way its inner blocks just take the available space (full width by default).
 - B need to define a layout (or inherit the global one)
 - Now you can do what you want to do with C, D, E (align them as you want)

Say you want `A` in the example above to also have a layout (because for some reason it can contain another block F that you want wide aligned), that's fine, you can define a layout for it, by doing so `B` becomes center aligned by default, so you need to aligned it "full" in order for the "default layout" to apply properly

**Comment by Sandstromer** [comment]
If I am understanding correctly, in your example A can be defined as full width but with the "Inherit default layout" also toggled on, and then any subsequent inner groups will default to the default width and can then go to full or wide width if needed?

The "Inherit default layout" option is not so easy to understand what it does, I think for the average WP user.

**Comment by youknowriad** [comment]
your understanding is right

> The "Inherit default layout" option is not so easy to understand what it does, I think for the average WP user.

I agree with that, it's not easy at all but I have yet to find an alternative approach that allows the same flexibility while being declarative.

**Comment by Sandstromer** [comment]
@youknowriad thank you for taking the time to explain this.

I think I was assuming - incorrectly - that "Inherit default layout" was applied to the group upon which it was selected, whereas it is actually applied to that group's inner elements.

I don't know how to make it more easily understandable, but I will go away and give it some serious thought.

**Comment by Sandstromer** [comment]
Is the general consensus that this new way of doing the alignments is going to be more or less how it will be when FSE lands in core?

**Comment by youknowriad** [comment]
It is at the moment unless there's some feedback suggesting that it doesn't work or that there's a better alternative.
