### ISSUE TITLE
Parsing: Empty paragraph blocks are ignored

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3055]
__Steps to reproduce:__

1. Navigate to Posts > Add New
2. Click "Write your story" to create a new empty paragraph block
3. Save the post
4. Refresh the page

__Expected result:__

The paragraph block created in step 2 is reflected in the saved post after refresh.

__Actual result:__

The post is empty.

__Additional context:__

The post, as saved in the database, contains the actual paragraph block content. It may be that the parser is ignoring the block because it consists of an empty paragraph.

**Comment by youknowriad** [comment]
It works as expected to me, don't you think it was related to #3064

**Comment by aduth** [comment]
Hmm, I am not able to reproduce now. At a glance it wouldn't seem #3064 is related. Might have been something specific to the branch I was on.
