### ISSUE TITLE
Group Block: Vertical margins are removed from groups with background

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30556]
## What problem does this address?
In block-library/theme.css, the vertical margins of group blocks with backgrounds are removed:

```
.wp-block-group.has-background {
    padding: 1.25em 2.375em;
    margin-top: 0;
    margin-bottom:0
}
```

Due to the high specificity, themes that have vertical margins set on group blocks need to target both `.wp-block-group` and `.wp-block-group.has-background` to overwrite the margin reset. Also, in themes that set a vertical margin on blocks based on their alignments, like this:

```
.alignwide {
	margin-bottom: 48px;
	margin-top: 48px;
}

.alignfull {
	margin-bottom: 64px;
	margin-top: 64px;
}
```

...those vertical margins get overwritten by the `.wp-block-group.has-background` margin styles, which can result in this:

<img width="1801" alt="image" src="https://user-images.githubusercontent.com/8181091/113846421-bd322200-9796-11eb-93a4-f7599da35aec.png">

## What is your proposed solution?
Remove the `margin-bottom: 0;` and `margin-top: 0;` from `.wp-block-group.has-background` in block-library/theme.css.

**Comment by carolinan** [comment]
I am able to reproduce this, but I did not find any information about why the margin style was first added, what the intention was.
The template part has the same CSS.

**Comment by jordesign** [comment]
Closing this as no longer reproducible - when I check block-library/theme.css those Margin values are no longer included for `wp-block-group.has-background`.
