### ISSUE TITLE
Paragraph block: Inline text colour picker does not stay static

### ISSUE THREAD

**Issue by aleone89** [WordPress/gutenberg#30561]
## Description

The inline text colour spectrum picker does not stay static. 

## Step-by-step reproduction instructions

1. Go to Posts/Pages > Add New
2. Add a title
3. Add a paragraph block > Add text
4. Highlight text > click the more options arrow button
5. Select Text Colour
6. Select Custom colour
7. Move the colour spectrum picker bar to change colour spectrum
8. Text Colour options close

## Expected behaviour

For the Text Colour box to stay open and I can change the colour.

## Actual behaviour

The Text Colour closes and I am unable to select a colour.

## Screenshots or screen recording (optional)

https://d.pr/v/ryhtWx

## WordPress information
- WordPress version: 5.5.
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Not theme specific. 

## Device information
- Device: Desktop
- Operating system: IOS 
- Browser: Chrome

**Comment by Mamaduka** [comment]
This issue was fixed via #30039.
