### ISSUE TITLE
Left and right alignments missing in the block editor when running FSE themes

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30568]
## Description
When running TT1 Blocks or the [Empty Theme](https://github.com/WordPress/theme-experiments/tree/master/emptytheme), the left and right alignments are not available for images, galleries, covers, etc.

## Step-by-step reproduction instructions
1. Install TT1 Blocks and create a new block.
2. Add any block that usually supports left/right alignments, and click the "Change Alignment" button.

## Expected behaviour
Left and right alignments should be there.

## Actual behaviour
They aren't :)

## Screenshots or screen recording (optional)
<img width="915" alt="image" src="https://user-images.githubusercontent.com/8181091/113882255-6db31c80-97bd-11eb-9988-311b073c0fdb.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Safari 14.0.3

**Comment by skorasaurus** [comment]
confirmed with gutenberg 10.4.1

**Comment by carolinan** [comment]
If you place the image block inside a group block (or query, or template part), the options depend on the layout settings in the parent block.

- Without changes to the layout settings, you can only align the image to the left, center, or right.
- When the layout setting inherits the width from experimental-theme.json, you can only set the image's width to default, wide or full width.
- When the content width and wide width have been specified, the image's width is adjusted and can only be set to default, wide or full width.

It is not possible to set the parent block to inherit the default width, and align the inner block to the left, center or right **inside that width constraint.**
This is the part I am not sure about if it is a bug or not.

I am not able to place an image, align it, and have a text next to it without columns.
This is no longer possible:
Twenty Twenty-One, without Gutenberg active
![Aligned image and text](https://user-images.githubusercontent.com/7422055/117238524-53f10d80-ae2d-11eb-9560-199f8b228384.png)

Empty theme, with Gutenberg (current trunk) active:
![image is not aligned](https://user-images.githubusercontent.com/7422055/117238684-ae8a6980-ae2d-11eb-8893-44bf6cb7903a.png)

**Comment by kjellr** [comment]
This definitely seems like a bug to me. @jasmussen / @youknowriad, can you confirm though? I don't know why left/right/center alignments would need to disappear regardless of the layout settings.

**Comment by youknowriad** [comment]
The reason we removed these alignments from containers with a layout defined is because "float left" and "float right" here will behave differently than what folks are used to: the blocks will be aligned completely at the left or right of the container and not at the left of the "content size" area. If that's something folks are ok with, we can bring these back, it's a small change.

**Comment by kjellr** [comment]
I think we might as well include it — some themes handle floats like that anyway, and I found it confusing to see these options missing.

**Comment by jasmussen** [comment]
I don't have a strong opinion, but wanted to note that if we are able to bring some CSS grid to the block editor at some time in the future, floats will have to be wrapped in containers such as group in order to work. So it's something to revisit in case the `layout` becomes aware of that.
