### ISSUE TITLE
FSE: "home" template results in WSOD

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#30565]
## Description

In a FSE theme when making use of a "home.html" template, results in an empty page.

It looks like Gutenberg is trying to load the "header.php", "content.php", and "footer.php" templates which would previously have been included in a classic theme, or the corresponding fallback WP templates, when attempting to load the FSE "home.html" template.
As these old school templates don't exist in FSE, the result is a WSOD on the frontend.

## Step-by-step reproduction instructions

1. using TT1-Blocks theme, rename the "index.html" template to "home.html"
2. view the site frontend and notice the empty blank page

## Expected behaviour

The home.html template should be called and displayed as appropriate.

## Actual behaviour

The home.html template does not display.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks

## Device information
- Device: Desktop
- Operating system: W10
- Browser: Firefox

**Comment by aristath** [comment]
Assigning to myself.
Also related to https://github.com/bobbingwide/fizzie/issues/58
This seems to be coming from PR #29026

**Comment by aristath** [comment]
This PR should fix the issue: https://github.com/WordPress/gutenberg/pull/30599 👍
