### ISSUE TITLE
Comment Reply Link Block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#30576]
Here is an initial take on the design for the Comment Reply Link block. This block should only be available in the Site Editor, and potentially only when editing certain templates (Index, Single, Singular, Page).

![comment-reply-link](https://user-images.githubusercontent.com/846565/113897492-d3ee6e00-97c2-11eb-9132-f98d01cb1d83.png)

Design feedback is politely requested for all aspects:

* Icon
* Toolbar actions
* Inspector settings
* Name
* Description

Figma link [here](https://www.figma.com/file/AagoBClTm0AgpfYCSKQl0m/Comment-blocks?node-id=501%3A1247).

**Comment by SantosGuillamot** [comment]
Hello! 👋   I would like to wrap up all the issues related to the Post Comments block to start working on a Comment Loop block as explained in [this tracking issue](https://github.com/WordPress/gutenberg/issues/34994). I'd like to make a quick summary to ensure we are aligned on this one:

## Description

Displays a link to reply to a comment.

## Potential Settings

- **Typography**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).
- **Color Settings**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).

As pointed in this [tracking issue](https://github.com/WordPress/gutenberg/issues/34994), I think we can start creating a first version with just a link to the already working [Post Comments Form block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/post-comments-form), and implement the inline form in the future.

## Requirements

- There is a [Discussion Setting](https://wordpress.com/support/settings/discussion-settings/#other-comment-settings) to select how many levels deep users want to allow for nested comments. We should take into account this and not show the Reply button if the limit is reached.
- There is a [Discussion Setting](https://wordpress.com/support/settings/discussion-settings/#other-comment-settings) to set that users must be registered and logged in to comment. It would be nice to change the text if the setting is enabled and the user isn't logged. Something like this:

![Screen Shot 2021-09-21 at 10 30 31](https://user-images.githubusercontent.com/34552881/134158080-ea121863-99f3-4763-9632-6ff1918c869a.png)

- There is another global setting to allow new comments in posts. This can also be overwritten per post. We have to take this into account and not show the reply button if this is disabled.

Of course, any feedback is welcome 🙂

**Comment by DAreRodz** [comment]
Hey, @SantosGuillamot, I'm working on this issue, could you assign it to me while I create a PR? Thanks! :grin:
