### ISSUE TITLE
Make Permalink/View Post easier to access

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30579]
## What problem does this address?

Currently, if you edit a published post and try to view the permalink, it's a bit buried in the settings and the UI appears to be pretty disjointed with odd amounts of spacing. This makes a common action difficult to find and interact with. This came up during a stream @helen did exploring FSE but applies to the core editor. 

Video:

https://user-images.githubusercontent.com/26996883/113908669-08970100-9794-11eb-9179-dd3e4429d4f6.mov

Screenshot:

<img width="289" alt="Screen Shot 2021-04-07 at 11 25 24 AM" src="https://user-images.githubusercontent.com/26996883/113908690-0e8ce200-9794-11eb-8e71-8817954f6468.png">

## What is your proposed solution?

I leave this to designers. Even if it stays under Permalink and isn't moved into the "Status & Visibility" section, the design itself could use a refresh :) Apologies if this might be a duplicate. I searched but didn't find this exact problem reported.

**Comment by javierarce** [comment]
I agree with you: the link is a bit buried in there. I think the reason for that is because it's part of a component that includes the input above (i.e. if you update the URL Slug the link is updated), so I'm not exactly sure how easy it would be to decouple both elements and move the View Post link elsewhere.

**Comment by sabernhardt** [comment]
There's a [Trac ticket for the admin toolbar link](https://core.trac.wordpress.org/ticket/53948) when not in Fullscreen mode. Either the link would need to show when the page loads, or I would need help showing the link after publish/save (removing the `hidden` class).

**Comment by noisysocks** [comment]
I think we can mark this as find by https://github.com/WordPress/gutenberg/pull/42033 which made the URL more prominent by displaying it in the _Summary_ panel.

<img width="297" alt="Screen Shot 2022-07-15 at 12 40 25" src="https://user-images.githubusercontent.com/612155/179136560-2cb05351-53af-4b85-a0f0-63e81313d07f.png">
