### ISSUE TITLE
Comment Author Block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#30572]
Here is an initial take on the design for the Comment Author block. This block should only be available in the Site Editor, and potentially only when editing certain templates (Index, Single, Singular, Page).

![comment-author](https://user-images.githubusercontent.com/846565/113897309-a5709300-97c2-11eb-89c1-a2b9ad26ef30.png)

Design feedback is politely requested for all aspects:

* Icon
* Placeholder when there is no context present
* Toolbar actions
* Inspector settings
* Name
* Description

Figma link [here](https://www.figma.com/file/AagoBClTm0AgpfYCSKQl0m/Comment-blocks?node-id=501%3A1235).

**Comment by paaljoachim** [comment]
Hey James

It looks like a good first iteration!
I think we can bring it over to "Needs dev" label.

**Comment by carolinan** [comment]
A basic version of this block as "Post Comment Author" was added in https://github.com/WordPress/gutenberg/pull/24824

**Comment by SantosGuillamot** [comment]
Hello! 👋   I would like to wrap up all the issues related to the Post Comments block to start working on a Comment Loop block as explained in [this tracking issue](https://github.com/WordPress/gutenberg/issues/34994). I'd like to make a quick summary to ensure we are aligned on this one:

## Description

Add the author of the specific comment.

## Potential Settings

- **Typography**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).
- **Color Settings**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).
- **Link Settings**:
    - Link to Authors URL: Clicking the name will take the user to that URL.
    - Open Author URL in a new tab.

## References

- This should be similar to the [Post Author Block](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/post-author).
- There is already a basic version of the Post Comment Author Block: [Pull Request](https://github.com/WordPress/gutenberg/pull/24824) and [GitHub code](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/post-comment-author).

Of course, any feedback is welcome 🙂

**Comment by cbravobernal** [comment]
May I take this one @SantosGuillamot?
Thanks!

**Comment by SantosGuillamot** [comment]
> May I take this one @SantosGuillamot?

Sure! I've just assigned you the issue 🙂
