### ISSUE TITLE
Edit Comment Link Block

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#30577]
Here is an initial take on the design for the Edit Comment Link block. This block should only be available in the Site Editor, and potentially only when editing certain templates (Index, Single, Singular, Page).

![edit-comment-link](https://user-images.githubusercontent.com/846565/113897514-db157c00-97c2-11eb-90ad-2497365e31cf.png)

Design feedback is politely requested for all aspects:

* Icon
* Toolbar actions
* Inspector settings
* Name
* Description

Figma link [here](https://www.figma.com/file/AagoBClTm0AgpfYCSKQl0m/Comment-blocks?node-id=501%3A1231).

**Comment by SantosGuillamot** [comment]
Hello! 👋   I would like to wrap up all the issues related to the Post Comments block to start working on a Comment Loop block as explained in [this tracking issue](https://github.com/WordPress/gutenberg/issues/34994). I'd like to make a quick summary to ensure we are aligned on this one:

## Description

Displays a link to edit the comment in the WordPress Dashboard. This link is only visible to Administrators and Editors.

## Potential Settings

- **Typography**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).
- **Color Settings**: It should be the same as the [Paragraph block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph).
- **Link Settings:** Open link in a new tab.

Of course, any feedback is welcome 🙂

**Comment by jameskoster** [comment]
It's a shame the edit link will have to take folks to the existing comment management screens in wp-admin. In the future it would be nice to send them to an instance of the block editor where they can edit the comment visually.

**Comment by cbravobernal** [comment]
@SantosGuillamot may I take this one? Thanks!
