### ISSUE TITLE
Improve Post Date Block UI

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30581]
## What problem does this address?

It's unclear to me if this should be seen as a bug or an enhancement request but currently the Post Date Block shows this UI when you click to edit the date: 

<img width="446" alt="Screen Shot 2021-04-07 at 11 06 17 AM" src="https://user-images.githubusercontent.com/26996883/113923788-32f1ba00-97a6-11eb-8536-31886a86af90.png">

This is using Gutenberg 10.3.2. 

## What is your proposed solution?

Fix the spacing/formatting and make the options clearer (Reset & Calendar Help).

**Comment by javierarce** [comment]
If I'm not mistaken, it seems this was inadvertently broken [by this fix](https://github.com/WordPress/gutenberg/commit/3848806ccc7b8a65778366e80af7ea63258538d4?branch=3848806ccc7b8a65778366e80af7ea63258538d4&diff=unified#diff-ae55a6ec543d38a6eb50a20cd99a9bef8efa84fc50832086360fe4afb5454c92L8) (from [this issue](https://github.com/WordPress/gutenberg/pull/20824)) that improved the style of the component inside the sidebar.

**Comment by javierarce** [comment]
@annezazu @jasmussen do you want me to open a new ticket for this or is it ok to use this one to report the problem?

**Comment by jasmussen** [comment]
Oh, thanks for the ping! This seems like one that I should just go ahead and fix as is, no need for new tickets. I can't today, but I'll put it on my list for tomorrow.
