### ISSUE TITLE
SelectControl with multiple prop set uses fixed height of 30 pixels

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#30582]
When using the [`<SelectControl/>`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/select-control) with the [`multiple`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/select-control#multiple) prop, the height of the output `<select>` element is fixed at 30 pixels which results in the select input looking broken:

<img width="272" alt="Screen Shot 2021-04-07 at 4 19 02 PM" src="https://user-images.githubusercontent.com/1783595/113928603-0a28ef00-97bd-11eb-88a8-2539dcf384a3.png">

Example code (this is added in a `<PanelBody>` inside `<InspectorControls>`):

```js
<SelectControl
	label={ __('Select Label') }
	value={ [] }
	options={ [
		{
			value: 'option-1',
			label: 'Option 1',
		},
		{
			value: 'option-2',
			label: __('Option 2'),
		},
		{
			value: 'option-3',
			label: __('Option 3'),
		},
	] }
	onChange={ (values) => console.log(values) }
	multiple={ true }
/>
```

I would expect this to output something closer to this:

<img width="272" alt="Screen Shot 2021-04-07 at 4 19 25 PM" src="https://user-images.githubusercontent.com/1783595/113928694-1e6cec00-97bd-11eb-957b-297a5bbc889a.png">

**Comment by talldan** [comment]
Previously reported in #27166, so will close as a duplicate. Thanks for reporting.
