### ISSUE TITLE
Template Editor: Hide fields that are not yet functional in the template editing context

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#30584]
## Description

The Visibility, Publish, and Excerpt fields are not currently functional in the template editing context.

![image](https://user-images.githubusercontent.com/45363/113938268-32a9ec80-97af-11eb-80b5-7e08a5104fe3.png)

## Step-by-step reproduction instructions

1. Use a block theme, for example TT1 blocks
2. Modify one of the templates or template parts
3. Open the template in the template editor from Appearance > Template Parts

## Expected behavior

Only the fields that are functional should show.

## Actual behavior

Additional fields are shown that do not work yet in the template context.

**Comment by carlomanf** [comment]
What evidence is there that these features "do not work or make sense" or "not needed"?

The Visibility and Publish features can be used to schedule a template or template part to take effect in the future, to save it as a draft before it is ready for use, or to retire a template or template part from use without deleting it from the database.

The Excerpt, if I'm not mistaken, is already being used to store descriptions of the templates and template parts, to appear in other parts of the UI.

Why would you want to ban users from accessing features that were perfectly functional to start with? It would be nice if more time was spent on real bugs and less time on silly attempts to police users. (see also: #25787)

The sidebar here actually needs more features, not less. If I remember right, Revisions is missing and should be available.

**Comment by bobbingwide** [comment]
I definitely think supporting Revisions is a good idea.
Plus the ability to change the slug.
Agree with @Carlomanf that the Excerpt could be useful.

**Comment by mkaz** [comment]
@carlomanf It is not a matter of trying to ban users from doing something or strip functionality, it is a matter of only showing UI that works in the interface and adding it back in when it is properly functional.

I agree that it would be nice to draft and schedule pieces, there's [a ticket for that here](https://github.com/WordPress/gutenberg/issues/29575), but we should wait to show those fields until it's ready.

The Excerpt does not show the description, right now if you type in the excerpt and click update and refresh the text is removed and not shown anywhere. Also, if the intent is for it to be a description we should update the label for the field.

I know the editor is inheriting a lot of these from the Block Editor, and this is merely an issue to highlight a few pieces we need to address. Opening a new issue is not a prioritization of what is important to work on or not. 

I've updated the title to more properly reflect the issue.

**Comment by carlomanf** [comment]
> I agree that it would be nice to draft and schedule pieces, there's [a ticket for that here](https://github.com/WordPress/gutenberg/issues/29575), but we should wait to show those fields until it's ready.

I wasn't saying it would be nice to be able to do it, I was saying it's already fully possible to do it. Can you show any evidence that it's not? The ticket you linked to appears to be about the site editor, which is not what we're talking about here.

> The Excerpt does not show the description, right now if you type in the excerpt and click update and refresh the text is removed and not shown anywhere. Also, if the intent is for it to be a description we should update the label for the field.

That might be a regression? I remember a PR being merged last year that started using the excerpt for descriptions.

**Comment by mkaz** [comment]
Closing as this ticket is no longer relevant, since these screens are no longer available in the template editors.
