### ISSUE TITLE
Quote & Pullquote blocks: Unify citation element on the front-end and in the editor to simplify styling

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30596]
## What problem does this address?
In the Block Editor, the citation element in the Pullquote block is a div with the class `wp-block-pullquote__citation`, and the citation element of the Quote block is a div with the class `wp-block-quote__citation`. On the front-end, the citation element of both blocks is a cite element without class. 

Since they are using different elements and the `wp-block-pullquote__citation`/`wp-block-quote__citation` classes are only used in the Block Editor, themes that enqueue the same styles for the front-end and for the Block Editor styles currently has to target the Block Editor and front-end citation elements separately.

## What is your proposed solution?
Add the `wp-block-pullquote__citation` and `wp-block-quote__citation` classes to the cite elements on the front-end as well, and change the citation element in the block editor from a `div` to a `cite`. That way, themes can use the same targeting for both the front-end and the editor.

---

**Edit**: I realized that both the Quote and Pullquote blocks have this problem, so I've updated the name and description of the issue.

**Comment by carolinan** [comment]
Would there be any negative side effects if both the editor and front used the cite element?

**Comment by andersnoren** [comment]
Not for themes, I think. At least not any major ones. If the element was changed from a `div` to a `cite`, it might inherit some styles from `cite` that aren't overwritten by `.wp-block-pullquote__citation` specific styles, so the styling of pullquote citations in the block editor might change slightly in themes that have block editor styles. But that seems like a worthwhile tradeoff for consistency.

Also, the targeting of the Core styles for the pullquote citation element looks like this:

```
.wp-block-pullquote__citation, 
.wp-block-pullquote cite,
.wp-block-pullquote footer {}
```

...so any themes that have replicated that targeting are already targeting both `.wp-block-pullquote__citation` and `.wp-block-pullquote cite` when styling the element in the editor.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This is being discussed and/or requested in https://github.com/WordPress/gutenberg/issues/19847. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
