### ISSUE TITLE
Spacer block can only be expanded horizontally in navigation block submenus

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30590]
## Description
The spacer block can only be expanded horizontally in navigation block submenus. It seems like it should instead work vertically—the same orientation as a submenu.

## Step-by-step reproduction instructions
1. Add a navigation block (horizontal)
2. Add a link and create a submenu with some more links
3. Try adding a spacer to a submenu

## Expected behaviour
The spacer can be used to space out links in the submenus

## Actual behaviour
The spacer can only be used to make the submenu wider

## Screenshots or screen recording (optional)
![spacer-submenu](https://user-images.githubusercontent.com/677833/113957129-43ab3a00-9851-11eb-88f4-c06aa7a17f71.gif)

**Comment by annezazu** [comment]
Seeing as the spacer block isn't included in blocks allowed for the navigation block after the ligher navigation work https://github.com/WordPress/gutenberg/issues/34041, does this issue still make sense to leave open?

**Comment by talldan** [comment]
It's a long story!

Spacer can still be added to the nav block, it has to be added via the Global Inserter like other non-link blocks. It can't be used in submenus anymore by the looks of it, but it can still be used at the root of the nav block in a vertical layout.

It looks like the issue is fixed though since #36340. So I'll close this.

It's worth mentioning that the row block still has the same bug, you can't space items you can just make the row taller. That's described in https://github.com/WordPress/gutenberg/issues/36197, so it still seems valid to close this issue.
