### ISSUE TITLE
Welcome Popup appears every time

### ISSUE THREAD

**Issue by napolitano** [WordPress/gutenberg#30618]
## Description
If a browser is configured to be privacy and data protection friendly so that it automatically discards cookies after closing, the Welcome popup dialog in the editor is always displayed the first time it is used within a session. Because the dialog is modal, the user must interact with it.

There is no global and/or persistent switch to effectively and permanently disable this dialog. 

At the same time, this dialog offers little to no benefit - especially for more experienced users, so a global disable is desirable for many users to avoid unnecessary hindrances when using WordPress.

## Step-by-step reproduction instructions
1. Open your browser
2. Clear all cookies (or use a browser were cookies will be discarded on close)
3. Open your WordPress page
4. Sign into the admin dashboard
5. Open any page or post for editing

## Expected behaviour
The welcome popup should be globally disableableable and/or persistent remember its state - so if it was ever clicked away, it should not show up again. Not even when WordPress is updated.

- There is a switch or configuration option to disable the welcome popup globally
- The state is persistently stored (not as a cookie, but as an attribute/parameter on the user record) and respected

## Actual behaviour
If a browser is configured to be privacy and data protection friendly so that it automatically discards cookies after closing, the Welcome popup dialog in the editor is always displayed the first time it is used within a session.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Bundled
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Linux Mint 20.1
- Browser: Firefox 87.0

**Comment by talldan** [comment]
@napolitano Thanks for reporting this. There's an issue tracking a better way of storing these kind of preferences - https://github.com/WordPress/gutenberg/issues/15105.

I'll close yours as a duplicate.
