### ISSUE TITLE
The `text` prop is missing from the button component documentation

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#30621]
## Description

The `Button` component has a `text` prop which is missing from [the documentation for the button component](https://developer.wordpress.org/block-editor/reference-guides/components/button/).

There may be other missing props for this, I've not checked in depth.

**Comment by talldan** [comment]
@johnbillion It looks like you're right that the `Button` react component does indeed have an undocumented text attribute.

However it's unrelated to do with the `core/button` block, which is implemented as a `RichText` anchor tag. Would you be able to update the issue description to remove mention of the block?

**Comment by johnbillion** [comment]
Looks like I got confused here. Thanks Dan. I've updated the issue.
