### ISSUE TITLE
Shortcodes don't work in a new Gutenberg post

### ISSUE THREAD

**Issue by miljushm** [WordPress/gutenberg#3062]
## Issue Overview

Shortcodes don't work / render on the front-end (shows nothing for the shortcode) when adding a new shortcodes in a new Gutenberg post via visual editor (plugin version: 1.4.0) however, it works if you add it via HTML editor.

## Steps to Reproduce
1) Add a new post via Gutenberg editor
2) Add a shortcode via visual editor (in a paragraph block for instance) - I've tested with one of the Tickera shortcodes [tc_ticket id="19"]
3) Save post
4) View the post on front-end

## Expected Behavior
To render shortcode added via visual or HTML view in a same way

## Current Behavior
You'll notice that after saving a post, in the HTML view, Gutenberg formats the shortcode added to something like this <p>[tc_ticket id=&quot;19&quot;]</p>

This happens when:
1) Create a new post via Gutenberg (visual view)
2) Create a new post or page without a content (in a standard WordPress editor) then edit it via Gutenberg visual view.

It doesn't happen when you add a new post / page via standard WordPress editor WITH SOME CONTENT and then edit it via Gutenberg and add a shortcode. 

In the other words: if you add a new post with some content (with or without a shortcode) via standard WordPress editor, edit it via Gutenber after and add some shortcode(s) in the visual or HTML view, everything works like a charm.

**Comment by robmcclel** [comment]
I second and could replicate.

For me, it saved the brackets and any interior quotation marks at HTML symbols and not as actual characters.  When I added via HTML editor, it all worked fine, as it saved each character as a character.

**Comment by kmgalanakis** [comment]
This works OK, but what about shortcodes inserted manually (not pasted) inside a paragraph block?

If for example, I insert the gallery shortcode inside a paragraph block right after some typed text, the last photo is not displayed on the frontend.

Again the double quotes are replaced with their HTML entities.

**Comment by mcsf** [comment]
@kmgalanakis, correct, but:

> If for example, I insert the gallery shortcode inside a paragraph block […]

Gutenberg's primary method for content insertion is native blocks. This is why there is such emphasis on automatic behaviors, like converting pastes to blocks, converting Classic Text content to blocks, block-to-block transforms, recognizing shortcodes, Markdown, and other basic markup elements.

The point of handling pastes, one could argue, is to make it easy to _import_ content, whether that's whole classic posts, or snippets copied from other sources. Manually inserting content should be achieved with native blocks—in this case, that would be inserting a native Gallery, or a series of Image blocks. If native blocks for one's use case aren't available, and one would like to manually type in a shortcode, the Shortcode block can be used to that effect.

**Comment by mcsf** [comment]
To clarify, this doesn't _a fortiori_ stop us from implementing a better handling of manually provided shortcodes in Paragraphs, but it does lower the need to make that happen now. There will always be a trade-off between feature completion and, in this case, performance and logical complexity (implications of continuously monitoring Paragraph input).

**Comment by kmgalanakis** [comment]
@mcsf there is nothing wrong with the way you convert shortcodes pastes to blocks. Actually, this is really cool.

The problem is that apart from shortcodes that can be transformed to blocks, like the Gallery shortcode, there are other shortcodes that are used inline on the content of a paragraph. Imagine a shortcode that returns the post title, or the name of the logged in user or whatever that you want to use it inside the paragraph content. How can you achieve this if when pasting the shortcode, it is transformed to a block? Of course, you can type the shortcode by yourself, but what kind of end user does it this way?

We can create mechanisms to inject shortcodes inside the paragraph block but if those shortcodes have arguments, they cannot be used because the double and single quotes are transformed to HTML entities. Really why did you choose to go with `contenteditable` instead of a plain `textarea`.

I can see there is this ticket https://github.com/WordPress/gutenberg/issues/3806. What are the plans for it?

**Comment by mcsf** [comment]
> The problem is that apart from shortcodes […]

I agree that there is still a need to address inline shortcodes. As you pointed out, #3806 should be the place to carry that discussion forward. In the meantime, I'll rename this issue to make it clear that what has been fixed is support for *blockwise shortcodes* and not inline.

> Is there any way to prevent this? Really why did you choose to go with `contenteditable` instead of a plain `textarea`.

Are you referring to what's under the `Editable` abstraction? A lot of thought has gone into the decision to use `contenteditable`. It provides flexibility and solves a number of requirements that `textarea` wouldn't have handled well—rich-text formatting being the most obvious one, along with all the features provided by TinyMCE. The main difficulty here lies at the interface between React and the Gutenberg serializer. Let's continue this discussion in #3806.

**Comment by kmgalanakis** [comment]
@mcsf thank you for your prompt answer. As far as this ticket is concerned, I'm covered. 

Let's move the discussion about inline shortcodes on https://github.com/WordPress/gutenberg/issues/3806.
