### ISSUE TITLE
Reusable blocks and Template Parts isolated editing view: Add menu in top toolbar for navigating to usage locations

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#30622]
Hi all, this idea was proposed as a part of [#30357 (comment)](https://github.com/WordPress/gutenberg/issues/30357#issuecomment-813594421) but I'm splitting it off into a separate issue. This functionality is originally stemming from an item on the Improvements to Reusable blocks tracking issue (#27890), but could also work nicely when applied to Template Parts.  

Within the isolated editing view for Reusable blocks and Template Parts*, it would be great if one could easily navigate to locations where the items are in use to make sure that any changes made work well in all contexts. This is sort of a reverse counterpart to the proposed popover menu shown for Templates (#29147), which has a menu of Template Part areas leading to their isolated editing views.

_*Discussions around the isolated views are for each are ongoing: see #29148 and [#29337, comment](https://github.com/WordPress/gutenberg/issues/29337#issuecomment-801201496)_

Here’s how this might work for Reusable blocks:

![RB-menu](https://user-images.githubusercontent.com/77359364/114052902-7575ce00-985c-11eb-871d-502bd3ceb6be.jpg)

And for Template Parts:

![TP-menu](https://user-images.githubusercontent.com/77359364/114052927-7a3a8200-985c-11eb-9efb-9b2acaeb4bf2.jpg)

Quick look at if the list could scroll in instances where there are a lot of items:

https://user-images.githubusercontent.com/77359364/114054195-a1de1a00-985d-11eb-8290-b69618e3aae5.mov

Questions:

The design of these popover menus mirrors [recent changes](https://github.com/WordPress/gutenberg/pull/29439) to the way Template descriptions are working but I wonder if we should revisit the title appearing in both the top toolbar and at the top of the popover menu so it isn't repeated twice (although probably less of an issue when the top bar is displaying the document information as well)

Does it feel like including the number with the section headings such as "Post (2)" helps with clarity, or does the "Used in 4 locations" at the top of the popover seem clear enough on its own? 

[Figma file here!](https://www.figma.com/file/kU6o4HZ1BBluRM9lqFINsj/Reusable-Blocks-and-Template-Parts-Top-toolbar-menu-in-isolated-view?node-id=510%3A20781) :)

**Comment by critterverse** [comment]
A relevant top bar menu exploration for Templates was shared here: https://github.com/WordPress/gutenberg/issues/30357#issuecomment-820285264

**Comment by jameskoster** [comment]
The Editor UI has changed a bit since this issue was opened making the designs a little outdated. Rather than updating this one, I'm going to close it out in favor of the more recent https://github.com/WordPress/gutenberg/issues/58990 which brings the data views element into consideration.
