### ISSUE TITLE
Mobile: The app crashes on slider container selection in VoiceOver/TalkBack accessibility mode

### ISSUE THREAD

**Issue by antonis** [WordPress/gutenberg#30625]
## Description
The app crashes on slider container selection in VoiceOver/TalkBack accessibility mode. The issue has been replicated for the slider setting the height of the spacer block and the slider setting the opacity of the cover block.

**Note** that the crash is observed both on iOS and Android

### Spacer
1. Open the editor with VoiceOver/TalkBack ON
2. Add a spacer block
3. Open the block settings
4. Navigate to the height container
5. Double tap
6. Notice that the app crashes
### Cover block
1. Open the editor with VoiceOver/TalkBack ON
2. Add a cover block
3. Add an image
4. Open the block settings
5. Navigate to the opacity container
6. Double tap
7. Notice that the app crashes

## Expected behaviour
The application does not crash when selection the slider container in VoiceOver/TalkBack accessibility mode

## Actual behaviour
The app crashes on slider container selection in VoiceOver/TalkBack accessibility mode

### iOS Slider Crash
https://user-images.githubusercontent.com/304044/114063921-ca880300-98a1-11eb-9ccf-faeb8b40fb5d.mov||

### Android Slider Crash
https://user-images.githubusercontent.com/304044/114064337-34081180-98a2-11eb-9099-56a505943394.mp4

## Device information
- Device: Pixel 5 and iOS
- Operating system: Android 11.0 and iOS 14.0
- WordPress app version: 17.1

**Comment by mchowning** [comment]
Is this a regression since the last release @antonis ? @AmandaRiu, could this be related to your accessibility work?

**Comment by AmandaRiu** [comment]
> Is this a regression since the last release @antonis ? @AmandaRiu, could this be related to your accessibility work?

Yup, definitely is. Looks like @dcalhoun already submitted a PR with the fix. I'll take a look at those.
