### ISSUE TITLE
e2e Tests: Cover user auto-completer

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#30632]
We should add an e2e test to cover the _user_ autocompleter (triggered by entering `@`). AFAICS, we don't have any such tests yet, so we'll likely need to add a new file.

Specifically, we should make sure that the following scenarios (raised by @gziolo in https://github.com/WordPress/gutenberg/pull/30540#issuecomment-814636881) work:

> As a follow-up, It would be great to add [...] test scenarios that cover:
> - `@Noah Allen` in the middle of the sentence
> - `@noahtallen @WunderBart` at any position

In other words: We need the e2e test to create a test user with a first and last name (e.g. `John Doe`), and need to make sure that typing `@John Doe` resolves to their username (e.g. `@johndoe`).

Furthermore, we need to make sure that entering _two_ usernames (each time starting with `@`) works.

cc/ @gziolo @fullofcaffeine @WunderBart

**Comment by vdwijngaert** [comment]
Looks like part of this is already covered: [mentions.test.js](https://github.com/WordPress/gutenberg/blob/7063d86a06dd259a02cfafe33f3f7920957c72f6/packages/e2e-tests/specs/editor/various/mentions.test.js). 

The way I see it, for this test to work, we'll need two things:

* Ability to create a user before the test runs
* Delete all users (aside from admin)

Should the deleting happen before all test suites, like trashAllPosts() in [setup-test-framework.js](https://github.com/WordPress/gutenberg/blob/7063d86a06dd259a02cfafe33f3f7920957c72f6/packages/e2e-tests/config/setup-test-framework.js)?

**Comment by ockham** [comment]
> Looks like part of this is already covered: [mentions.test.js](https://github.com/WordPress/gutenberg/blob/7063d86a06dd259a02cfafe33f3f7920957c72f6/packages/e2e-tests/specs/editor/various/mentions.test.js).

Ah, nice find -- I hadn't seen that one! 👍 

> The way I see it, for this test to work, we'll need two things:
> 
> * Ability to create a user before the test runs
> * Delete all users (aside from admin)
> 
> Should the deleting happen before all test suites, like trashAllPosts() in [setup-test-framework.js](https://github.com/WordPress/gutenberg/blob/7063d86a06dd259a02cfafe33f3f7920957c72f6/packages/e2e-tests/config/setup-test-framework.js)?

IMO, creating and trashing posts is a much more recurring scenario in our e2e tests, so it makes sense to have it there. Creating and deleting a user seems like something that's only required for very few tests, so I'd lean towards doing that right in the autocompleter test -- i.e. `mentions.test.js`.
