### ISSUE TITLE
[FSE] Hide Preview Button when Updating Design

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30633]
## What problem does this address?

When saving changes in the Site Editor, the preview button is still visible and hangs out slightly awkwardly behind the saving flow. If you save changes in the Post Editor, the preview button folds underneath the saving flow creating a smoother experience: 

Post Editor: 
<img width="400" alt="Screen Shot 2021-04-08 at 10 54 11 AM" src="https://user-images.githubusercontent.com/26996883/114080201-5715cf80-9868-11eb-99d6-ad2949f01eb0.png">

Site Editor:
<img width="367" alt="Screen Shot 2021-04-08 at 10 53 23 AM" src="https://user-images.githubusercontent.com/26996883/114080206-5846fc80-9868-11eb-86d3-7f6003b21190.png">

This came up during a hallway hangout for the FSE Outreach program!

## What is your proposed solution?

Have the Site Editor saving experience match what's done in the Post Editor causing the preview button to fall behind the saving prompt:

<img width="350" alt="Screen Shot 2021-04-08 at 12 48 34 PM" src="https://user-images.githubusercontent.com/26996883/114080550-c12e7480-9868-11eb-83fa-46d64d7d346d.png">

**Comment by karmatosed** [comment]
I might be wrong but I don't seem able to replicate this as an issue right now on the latest build:

![2021-09-10 at 17 47](https://user-images.githubusercontent.com/253067/132888834-93292783-0adb-449d-a31c-0543d52af24f.png)

If this is a case that it's been fixed that's great, however, if it's a case I am just missing some steps to replicate I would happily do that @annezazu. For now, I will remove the needs design label as firstly, I think your solution works as a fix and what I see seems to have been implemented (unless I am mistaken).

**Comment by annezazu** [comment]
Cannot replicate either! Closing this out 🥳 Thanks for checking back in.
