### ISSUE TITLE
[Global Styles] Color palette changes in Root should propagate to the By Block settings

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30644]
## What problem does this address?

If you remove or change the default color palette options in Global Styles (delete a default or change the name), those changes aren't propagated to the By Block settings. Here's a video showing this:

https://user-images.githubusercontent.com/26996883/114106684-8b02ec00-988c-11eb-8bd7-7fe3cf210d90.mov

## What is your proposed solution?

Have the color palette changes properly adjust across all global styles settings. cc @nosolosw

**Comment by Sandstromer** [comment]
Maybe related issues: https://github.com/WordPress/gutenberg/issues/29802 https://github.com/WordPress/gutenberg/issues/29818

**Comment by Thelmachido** [comment]
I wasn't able to reproduce this on the latest version of Gutenberg, the custom colors I created in Site Editor `Red Test` + `Blue Test` are displayed in the editor. 

https://user-images.githubusercontent.com/41231764/183931429-6b16790c-e676-4dbc-97f7-a227ab24d9e9.mov

However, I don't see the option to default color names.

WordPress 6.0.1
Gutenberg 13.8.1 active
