### ISSUE TITLE
[FSE] Show Template Part color settings when in isolated mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30641]
## What problem does this address?

Currently, if you are viewing an isolated template part, the usual block settings for that template part aren't viewable. You're not able to select the overall template part either to make specific changes to styling. Considering this is an isolated view, it seems one should actually be able to edit the entire template part even more directly including setting colors. This came up as part of [the fourth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/25/fse-program-testing-call-4-building-a-restaurant-themed-header/#comment-1479):

> I guess what came to mind for me was – why in the “Template Parts –> Headers –> header” can’t I set a background color for my header there? (This is where I expected to find it as a second time FSE user) Here is a screenshot of my header template: https://snipboard.io/PCOXqB.jpg Related, I found I had to set the background color for my header 3 times, once for the index template (like in your video), once on the page home template (screenshot – https://snipboard.io/2iGhOU.jpg), and once on the page template (screenshot – https://snipboard.io/s69bFW.jpg). I was kind of wondering if I could just set it once in the header template itself, but maybe that’s not how this was designed. I also tried to set the header background color on the index template only, but I think because I had set up a homepage and pages, the header color didn’t show up on the homepage and pages with only the index page having the header background color. Anyway, just wanted to share where my head was at as a user 🙂

**Template View**

Opening the site editor > opening a specific template > selecting the Header template part

<img width="1416" alt="Screen Shot 2021-04-08 at 4 21 54 PM" src="https://user-images.githubusercontent.com/26996883/114103552-9521ec00-9886-11eb-8dc0-770261b978e7.png">

**Isolated Template Part View**

Opening the site editor > using the navigation component to navigate to a template part > viewing the template part. 

<img width="1416" alt="Screen Shot 2021-04-08 at 4 18 33 PM" src="https://user-images.githubusercontent.com/26996883/114103452-660b7a80-9886-11eb-9b16-89a8ec64cf60.png">

Note that you're unable to even select the parent template part block while in this view. 

## What is your proposed solution?

When one navigates to the isolated template part, enable the ability to modify the entire template part rather than just showing the contents of the template part.

**Comment by carolinan** [comment]
The styles for the template part are saved in the template that includes the template part.
Only the content inside the template part can be changed with the template part itself.

I wonder if we need to rethink template parts and remove all styling and layout options from them and only let them be a container for the content.

Related: https://github.com/WordPress/gutenberg/issues/30732

**Comment by kevin940726** [comment]
Agree. I don't think this is possible with the current architecture. We could perhaps solve this only for the template part focus mode though (when there's a back button), but I'm not sure if it's worth the effort.

**Comment by noisysocks** [comment]
I agree. These settings are stored in the _template_, it doesn't really make sense for the _template part_ editor to have them. Is there another way of addressing the confusion here? What do you think @mtias?

**Comment by jameskoster** [comment]
We removed the ability to apply style to Template Part blocks directly in https://github.com/WordPress/gutenberg/pull/36571. This should eliminate the confusion around being able to style them in the regular editor, but not in focus mode (and the relationship thereof).

Do you think we can close this issue @annezazu?

To be clear, it should still be possible to edit template part properties like name and area in focus mode (https://github.com/WordPress/gutenberg/issues/37220).

**Comment by annezazu** [comment]
Yes :) Thanks for following up here. If this gets added back, we can revisit.
