### ISSUE TITLE
[FSE] Update "Customize" link from Appearance > Theme page for block themes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30643]
## What problem does this address?

Currently, the customizer shouldn't be accessible when using a block theme. However, if you head to Appearance > Themes > Hover over current theme and you'll see the option to select "Customize" which will open the customizer:

<img width="580" alt="Screen Shot 2021-04-08 at 4 50 22 PM" src="https://user-images.githubusercontent.com/26996883/114105726-876e6580-988a-11eb-9450-af8f15705c08.png">

## What is your proposed solution?

I think this should be updated to link to the Site Editor itself or the most appropriate section if it's a hybrid/universal theme. 

cc @kjellr @carolinan in case this might actually be a TT1 blocks/theme specific issue!

**Comment by aristath** [comment]
> cc @kjellr @carolinan in case this might actually be a TT1 blocks/theme specific issue!

Not a TT1 issue, I can confirm this applies to all block-based themes.
I haven't looked at it, but maybe some things are just easier done in WP-Core instead of running in circles with filters from the plugin 😆

**Comment by danielmilner** [comment]
I may need to create a new issue for this, but themes aren't the only thing that put settings in the Customizer. Plugins also put their display output settings in the Customizer screen. When testing Full Site Editing, I noticed that there is not longer a way to get to those settings.

**Comment by jameskoster** [comment]
<img width="1375" alt="Screenshot 2021-11-16 at 16 58 10" src="https://user-images.githubusercontent.com/846565/142033022-ed9dd2be-4a30-44ae-a7fa-c04099b65ac1.png">

We need to update the big blue button here as well – it could link to Appearance > Editor when a block theme is active.

**Comment by noisysocks** [comment]
> I haven't looked at it, but maybe some things are just easier done in WP-Core instead of running in circles with filters from the plugin 😆

Yeah probably best to move this issue to Trac and fix it directly in Core.

**Comment by jameskoster** [comment]
Trac ticket opened: https://core.trac.wordpress.org/ticket/54460

**Comment by mtias** [comment]
I expanded more about it in #36578, but it's not just updating the big blue button, it's about revising the welcome guide in the context of what the new features are — blocks, patterns, styles. Several of the side links could be modified as well (like menus).

**Comment by jameskoster** [comment]
Oh I agree we should do all of that. But atm the the button(s) feel like a bug when you have a block theme active, and so perhaps warrant a dedicated effort?

**Comment by noisysocks** [comment]
Thanks @jameskoster. Closing in favour of https://core.trac.wordpress.org/ticket/54460. Let's continue discussion there.
