### ISSUE TITLE
Post title special characters are encoded in Site Editor

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#30657]
## Description

When creating a post with special characters in the title, for example: three dots (...)
It will not be displayed as dots in the Site Editor menu when navigating to the posts list.

This is also true for taxonomies.
There is a difference between adding it on the category overview page and saving it afterwards.
As described in the reproduction steps below.

### Post

1. Create a new post
2. Enter a title which contains three dots like in the screenshot
3. Open the Full site editor
4. Navigate to the Posts list
5. See the post title not being displayed as expected

### Category

1. Go to the category overview of posts
2. Create a category with the name "hello &#34; there"
3. See the category in the list being displayed with a `"`
3. Open the full site editor
4. Navigate to the content > categories section
5. See the category name being displayed as entered

_After saving the category the name will be "flattened" to `"` and will display correctly._

## Expected behaviour
The three dots should be rendered as such.

## Actual behaviour
HTML encoded version is being displayed.

## Screenshots or screen recording (optional)
<img width="1179" alt="Screen Shot 2021-04-09 at 11 34 02" src="https://user-images.githubusercontent.com/2005352/114161143-082f6f00-9928-11eb-87e8-867abdb40eaa.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No --> TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by aristath** [comment]
Related PR: #30661
