### ISSUE TITLE
Full Site Editing Gradual Adoption

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#30662]
Milestone 7 of the [Site Editing project](https://github.com/WordPress/gutenberg/issues/24551) comprises a series of subprojects aiming for its gradual adoption, allowing classic themes to make use of some new block features without the need of fully migrating to block themes all at once. This reduces the gap between classic and block theme experiences, while at the same time providing classic themes an upgrade path to enjoy the full block experience.

### Navigation Editor
The Navigation Editor's goal is to allow building menus using blocks in classic themes, covering the same features as the classic Menu Editor but with the editing experience of the Navigation Block.

- Tracking Issue: #29102
- [Project Board](https://github.com/WordPress/gutenberg/projects/31)

### Widgets Editor
Similar to the Navigation Editor, the Widgets Editor is available in classic themes as a way to manage widget areas with blocks. This implies the need to view and edit blocks in the Customizer as well.

- Tracking Issue: #24687
- [Project Board](https://github.com/WordPress/gutenberg/projects/27)

### Allowing block templates in classic themes
As an intermediate migration step for themes from classic to block, classic themes should be able to use block templates, resulting in a hybrid state.
- [x] Add do_block_template_part function #30345
- [x] Allow creating custom block templates in classic themes #30438

**Comment by mtias** [comment]
Marking this as closed. The only lingering project (navigation screen) we can continue to track separately.
