### ISSUE TITLE
Reusable blocks can't be inserted in the Site Editor

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#30669]
## Description
As of 10.4-RC1, Reusable blocks can't be inserted in the Site Editor.

This issue is related to #30668, which presents the opposite logic for template parts. Original discussion in #30308

## Step-by-step reproduction instructions

1. Go to the post editor.
2. Select any block and click on "Add to reusable blocks"
3. Go to the Site Editor.
4. Open the inserter and look for the recently created reusable block.

## Expected behaviour
The recently created reusable block should be available in the site editor.

## Actual behaviour
The recently created reusable block is not available in the site editor.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.4-RC1
- Are all plugins except Gutenberg deactivated? Yes
- Theme used? TT1 Blocks

**Comment by lwangdu** [comment]
I am using Wordpress 5.7.1 with Genesis theme. When I insert reusable block, it blank. It to used work fine before 5.7 updates. Could someone looking into this issue? Please see the screen shot 
![Screen Shot 2021-04-23 at 9 53 12 AM](https://user-images.githubusercontent.com/24829573/115904748-0383b400-a41a-11eb-81fb-5c7d3a8826a1.png)
Thanks

**Comment by getdave** [comment]
It looks like `__experimentalReusableBlocks` is not available on the editor settings in the Site Editor at the moment.

Try running this in Console on Site Editor to check:

```
wp.data.select('core/block-editor').getSettings().__experimentalReusableBlocks
```

However, I checked and running `wp.data.select('core').getEntityRecords('postType','wp_block')` _does_ return results so I hope it's just a case of wiring things up for the Site Editor.

I can take a look tomorrow.
