### ISSUE TITLE
Youtube and Vimeo embeds do not work in the site editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30663]
## Description

Youtube and Vimeo embeds that are added in the site editor does not work.
The video is not showing.

In Firefox, the caption toolbar is sometimes overlapping the block toolbar.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a full site editing theme
2. Open the site editor
3. Add a youtube or vimeo embed. See the result in the editor and front.

## Expected behaviour

The embeds should work.

## Actual behaviour

The videos do not work.

## Screenshots or screen recording (optional)
<img width="668" alt="site_editor__beta______contrib_____wordpress" src="https://user-images.githubusercontent.com/7422055/114181481-d925f700-9941-11eb-9ede-620acedc012e.png">

## WordPress information
WordPress version: 5.7, 5.8 beta
Gutenberg version: trunk
Are all plugins except Gutenberg deactivated? yes
Are you using a default theme (e.g. Twenty Twenty-One)? TT1 blocks

## Device information
Device: Desktop
Operating system: Windows 10, Mac OS
Browser: Chrome Version 89.0.4389.114, Firefox.

**Comment by danstramer** [comment]
I am also experiencing this, here: https://github.com/WordPress/gutenberg/issues/31521

**Comment by ellatrix** [comment]
This should be fixed by #32057.
