### ISSUE TITLE
Social Icons Block: Unexpected double border when inserting icon

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#30682]
## Description

When inserting an icon using the Social Icons Block an unexpected double-border appears.

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Create a new page.
2. Insert the Social Icons Block via / command.
3. Select an Icon.

## Expected behaviour

- A square border wrapping around the boundary of the icon.
- Or a rounded border around the perimeter of the round icon.

## Actual behaviour

Two borders — round and square — surround the icon.

**Twenty Twenty One**

![image](https://user-images.githubusercontent.com/545779/114216684-d8369a80-992c-11eb-8ada-33125fa743dd.png)

**Neve Theme**

![image](https://user-images.githubusercontent.com/545779/114217448-c9041c80-992d-11eb-8dc1-86a4bba34907.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One. Reproducible in other Themes. (see above.

## Device information
- Device: Desktop.
- Operating system MacOS 11.2.3.
- Browser: Chrome 90.0.4430.51.

**Comment by jasmussen** [comment]
Great ticket, thank you. Fixed in #30721.
