### ISSUE TITLE
wp-env doesn't include plugin files

### ISSUE THREAD

**Issue by thomashigginbotham** [WordPress/gutenberg#30685]
## Description
When using the _.wp-env.json_ file to specify a plugin to install and activate, the plugin's files are not downloaded to the source folder like the default WordPress plugins are (e.g. Akismet).

## Step-by-step reproduction instructions
1. Create a .wp-env.json file with the following:
   ```
   {
     "plugins": [ "WordPress/theme-check" ],
     "mappings": {
       "wp-content/plugins": "./plugins"
     }
   }
   ```
2. Run `wp-env start`.
3. Check your files, and notice that a _plugins_ folder has been created with the following files and folders:
   * akismet
   * theme-check
   * hello.php
   * index.php
4. Notice that the _theme-check_ folder is empty.

## Expected behaviour
The _theme-check_ folder (or any plugin specified in the _plugins_ array) should contain the plugin's files.

## Actual behaviour
The plugin files are missing and are only available in the _%userprofile%\.wp-env_ folder.

## Screenshots or screen recording (optional)
<img width="86" alt="missing-files" src="https://user-images.githubusercontent.com/1651691/114225496-60726b00-9940-11eb-8514-be1ddae4775d.png">

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: N/A

**Comment by talldan** [comment]
Hi @thomashigginbotham, apologies it took so long to reply to you here.

Just want to check, what's your goal here? To do local development on `theme-check`?

If so, I think the best option would be to clone the theme-check repo locally and then specify a path to the local folder in the plugins array. That's how local development for gutenberg works.

**Comment by thomashigginbotham** [comment]
I've found a workaround for my specific scenario; however, it seems strange that when using the wp-env configuration I posted above, the files for `akismet` are downloaded to my project's source folder, but the files for `theme-check` are not, resulting in both an "akismet" folder that contains its source files and a "theme-check" folder that is empty.

I'm just curious as to the reasoning why it would result in an empty folder. I would assume that either both folders (with their files) would be included in my project or both folders would not be included. I can see that the developers who would prefer those files in their project would be wondering why they're missing when `akismet` is there.

**Comment by talldan** [comment]
It's not something that I have full knowledge of, though I think the goal of mappings is to mount a local folder in the docker instance, so it might not be intended to work the other way around.

**Comment by noahtallen** [comment]
Yep, so the intention of mappings is to map any local source you like! However, this means you're in charge of managing and updating those sources.

The plugins/themes settings are for basically defining dependencies that wp-env manages for you, and they are downloaded to a hidden directory (shown with `wp-env install-path`)
