### ISSUE TITLE
Buttons Block: Justify right and clicking right button the toolbar goes outside the layout screen,

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30693]
## Description
When "Justify items right" and the button moves to the right clicking the right button the toolbar goes outside the canvas/layout area.

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Add a Buttons Block.
2. Click to Justify items right.
3. Click the right justified button.
4. Notice that the toolbar goes outside of the canvas area.

## Expected behaviour
To see the toolbar within the canvas area.

## Actual behaviour
Toolbar goes outside the canvas area.

## Screenshots or screen recording (optional)

![Screen Shot 2021-04-10 at 00 32 52](https://user-images.githubusercontent.com/5323259/114246966-50847680-9994-11eb-9d86-cb2b24f60ae9.png)

https://user-images.githubusercontent.com/5323259/114246927-364a9880-9994-11eb-87c0-408f9a074d52.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

**Comment by annezazu** [comment]
[As part of the ninth call for testing for the FSE Outreach](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/), this experience of right aligning the button block came up. However, in this case, the problem is that if the buttons block is aligned right, upon clicking on it, it reverts back to being aligned left as shown below:

> Focusing on the “Covid” button when it’s aligned-right makes it jump back to aligned left.

https://user-images.githubusercontent.com/26996883/129629511-6b8508be-843d-40a7-91cb-bec2fafcc488.mov

I'm wondering if this might be due to some fix that addressed this original issue so I wanted to tie the two together here. Happy to open a new issue if that works better!

**Comment by annezazu** [comment]
Ah ha, I found a fix for the issue I mentioned here: https://github.com/WordPress/gutenberg/pull/33739. I then replicated the issue originally described here and can still replicate:

<img width="776" alt="Screen Shot 2021-08-16 at 5 18 38 PM" src="https://user-images.githubusercontent.com/26996883/129630788-f390bf42-9d72-4fac-bcb6-220a57e56214.png">

**Comment by jasmussen** [comment]
Is this still an issue?

![resizing](https://user-images.githubusercontent.com/1204802/193262557-423ac3e3-e5aa-4ede-b2e3-4b6d9f31319f.gif)

**Comment by annezazu** [comment]
I can replicate a _version_ of this but it has more to do with this issue IMO https://github.com/WordPress/gutenberg/issues/34466 


https://user-images.githubusercontent.com/26996883/193492379-096cd5f9-c8f0-47a8-a353-02197fdc39ae.mov

**Comment by annezazu** [comment]
I'd prefer to close this out as a result and leave an updated comment there. Does that work for you @paaljoachim or are you still able to replicate this?

**Comment by jasmussen** [comment]
Yep, that issue is definitely about block toolbar width, so I think we can close this one.

**Comment by paaljoachim** [comment]
It works for me (mostly I do notice this #34466). The issue I mentioned has been fixed.
