### ISSUE TITLE
Any way to disable the console log comments

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#30697]
## Description

Although useful, it's sometimes annoying to **always** have the log comments display in the console when the Gutenberg plugin is active.

## Step-by-step reproduction instructions

Install the Gutenberg plugin and open up a page in the editor and view the console.

## Expected behaviour
A way to optionally disable this.

## Actual behaviour
No obvious way to disable this.

## Screenshots or screen recording (optional)

![gb-log-messages](https://user-images.githubusercontent.com/1482075/114265592-8acc3300-99e9-11eb-9146-e7d721d0faad.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (2021)

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome

**Comment by Quintis1212** [comment]
Hi @dgwyer  ) I will try to implement yours enhansement )

**Comment by Mamaduka** [comment]
Hi, @dgwyer

I think this is similar to #33148. There was a proposal to remove logs from the production builds (#33153), but eventually, we grouped them to reduce the noise - #34163.

Let me know if we can close this issue.

**Comment by dgwyer** [comment]
Seems much better now. Thanks for the heads-up.
