### ISSUE TITLE
Columns block: Dropping blocks below existing content.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30700]
## What problem does this address?

One can not drop content below the existing Column block content.
One needs to drop above and then use the arrow keys to move the content below.

https://user-images.githubusercontent.com/5323259/114276414-c9341300-9a26-11eb-8270-b16ebfe9fe70.mp4

## What is your proposed solution?

One should be able to drop blocks above OR below the existing content in the Columns block.

@shaunandrews

**Comment by shaunandrews** [comment]
Funny enough, I have the opposite problem; I can't drop a block at the top of a Column:

![column-block-dropping](https://user-images.githubusercontent.com/191598/115046605-a6ca4b80-9ea5-11eb-8a10-584d835fb3f8.gif)

**Comment by paaljoachim** [comment]
That is weird.
It has a mind of its own. 
It looks like a general fix is needed here.

**Comment by annezazu** [comment]
@priethor thoughts on whether this is an enhancement request or a bug? To me, this feels like a bug :D

**Comment by priethor** [comment]
I _could_ see this being limited on purpose but... it does seem like a bug to me, the dropzones are a bit hard to find 😅

**Comment by paaljoachim** [comment]
Here is a suggestion for adding drop zone to the Columns block: https://github.com/WordPress/gutenberg/issues/30699

**Comment by paaljoachim** [comment]
I want to also mention this issue is valid for the Widgets screen as well.
I just now tried to drop a block above the current blocks in the Widget screen, but was not able to do so.

https://user-images.githubusercontent.com/5323259/118543922-3be68b80-b755-11eb-83dd-2433c50f5b4a.mp4

@draganescu

**Comment by talldan** [comment]
I think the original issue has been solved, I could definitely drag to the bottom of a column. Dragging to the top works as well, but the blue indicator doesn't show.

I also can't reproduce the widgets issue, just the thing I mentioned before—the blue drop indicator doesn't show at the top and the area that can be dragged into is smaller than expected (see https://github.com/WordPress/gutenberg/issues/26049).

**Comment by paaljoachim** [comment]
I noticed a very thin line when dropping below content in a columns block. So the issue I mentioned here has been taken care of. There are various other drag and drop blue lines missing for other circumstances but those have perhaps been addressed in other issues.
