### ISSUE TITLE
Heading block: Show all headings under "Change Heading Level" without scrolling

### ISSUE THREAD

**Issue by jerrysarcastic** [WordPress/gutenberg#30707]
When adding a heading in Gutenberg, to select the H6 level the user must "side scroll" to see it.  It is not shown in the popover due to the current width not being adequate.  Screenshot:

![Screen Capture on 2021-04-11 at 11-01-11](https://user-images.githubusercontent.com/1967448/114321203-4c9c4580-9ab5-11eb-9d4f-1ee7e033d844.gif)

Possibly a regression?  I see older screenshots of the heading block show options H1-H6 without the need to scroll, but now cuts off at H5 (and you must scroll to see the H6) options.

Tested in Chrome 89.0.4389.114  and Safari 13.1 on MacOS 10.15.4

**Comment by philhoyt** [comment]
![wtf gut](https://user-images.githubusercontent.com/1392406/120693741-659ef280-c477-11eb-9f07-a2bf8ceadadb.gif)
Any movement on this?
