### ISSUE TITLE
Button Block seems  Unremovable

### ISSUE THREAD

**Issue by Hubdeb** [WordPress/gutenberg#30702]
## Description
The Button Block inside a Group block is non-removable. So after delete, the next time I open the post in the admin, the button appears again. I can probably work around it by starting a group afresh without a button in the setup, but it's better to have it fixed,

## Expected behaviour
No buttonif  it is deleted

## WordPress information
- WordPress version: Current version: 5.7
- Gutenberg version: I don't know it comes along
- Are all plugins except Gutenberg deactivated?No
![Pluginsactivated](https://user-images.githubusercontent.com/45826492/114298413-99cce700-9ab6-11eb-8c63-f70972ab42e4.jpg)
![Schermafbeelding 2021-04-11 110447](https://user-images.githubusercontent.com/45826492/114298439-b701b580-9ab6-11eb-9cf0-0045d27426fb.jpg)

- Are you using a default theme (e.g. Twenty Twenty-One):  Twenty Twenty

## Device information
Desktop Windows 10 Google Chrome

**Comment by talldan** [comment]
@Hubdeb This sounds like a similar issue to https://github.com/WordPress/gutenberg/issues/28217.

Does the comment I left here help you remove the button?  https://github.com/WordPress/gutenberg/issues/28217#issuecomment-761967769

**Comment by Hubdeb** [comment]
Yes, I wasn't aware of the container. Removed it and the bug has disappeared. Thanks for the quick reply.
