### ISSUE TITLE
Make regular blocks more distinct from template parts in inserter menus

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30712]
## What problem does this address?
For the average user who is unaware of full-site editing and just wants to update a post, seeing template parts with similar names to regular blocks may be a confusing experience:
<img width="247" alt="Screenshot 2021-04-12 at 11 43 19 am" src="https://user-images.githubusercontent.com/677833/114337906-92740f00-9b84-11eb-9c7c-d834069215a2.png">

Here, seeing Heading and Header made me pause for a moment. I think for many users this may be a confusing experience.

## What is your proposed solution?
Not sure I have one right now, but I think it'd be good to optimise for regular blocks in the post editor.

**Comment by karmatosed** [comment]
I'm torn on this, on one hand I see it all 'as content' which makes me think it is all the same. As a user I add them both and use them pretty much the same. However, I totally understand they are different. I wonder though if they are to an end user and therefore if making them distinctly different would be useful or confuse? This is where I am torn on this and could go either way.

**Comment by talldan** [comment]
You now can't add template parts in the post editor, so I'd consider this fixed.
