### ISSUE TITLE
Feedback: Color options could be grouped for better consistency

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30719]
## What problem does this address?

This was brought up during a contributor day at Yoast on April 9;
When a block has a link color option, the color options in the block settings sidebar are displayed in the following order:

Text color
Background color
Link color

And when a block has a link color option but no text color option, the order is 
Background color
Link color

## What is your proposed solution?

Text color and link color options should be grouped together, they both add color to the text.

**Comment by annezazu** [comment]
@carolinan can you clarify a bit here what you want to see? Do you want a different order of color options? I'm not quite following this issue or the problem.

**Comment by carolinan** [comment]
Yes, I interpreted it as the user wondering why the order of the color options is different for different blocks.

A more consistent order would be:
Background color
Text color
Link color

When there is no link color:
Background color
Text color

When there is a link color but no text color:
Background color
Link color

**Comment by mtias** [comment]
I think this is more clear with the latest implementation:

![image](https://user-images.githubusercontent.com/548849/146515932-efc41882-0ed2-4cf8-8b9e-b8217fc3d966.png)

**Comment by mtias** [comment]
Though inconsistent capitalization, and "color" feels redundant :)

**Comment by jorgefilipecosta** [comment]
> Though inconsistent capitalization, and "color" feels redundant :)


Fix proposed at https://github.com/WordPress/gutenberg/pull/37493.
