### ISSUE TITLE
Gallery refactor: Arbutus theme compatibility

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#30711]
The [Arbutus](https://wordpress.org/themes/arbutus/) theme as a number of incompatibilities with the gallery block refactor as [outlined here](https://make.wordpress.org/core/2021/03/23/gallery-block-update-call-for-testing/#comment-41032).

- .wp-block-gallery.blocks-gallery-grid.has-nested-images figure.wp-block-image img { width: auto; } breaks the layout/widths for some reason
- Custom theme styling for captions is completely missing because the markup and selectors are different. (this applies to all themes tested)
- This theme styles captions to not overlap images, because it’s designed to work with longer captions.
- Theme authors should not need to make any changes to accommodate existing use cases with the revised gallery implementation. It would be reasonable to require themes to update to allow the new features that the change enables.
- Custom gallery excerpts are broken. Core PHP functions get_post_gallery() and get_post_gallery_images() still don’t work, and fallbacks for current block galleries don’t work because images are missing the data-id attribute.

**Comment by carolinan** [comment]
Pinging @celloexpressions in case you missed this

**Comment by celloexpressions** [comment]
Thanks for the ping. Noting that I observed most of these issues in multiple themes that I tested. All of the theme-specific issues noted above occurred with the Arbutus theme, so it's a good one to test with.

**Comment by glendaviesnz** [comment]
@celloexpressions in order to try and limit the impact of the gallery refactor on themes that customise the gallery layout we are leaving all existing gallery content untouched with the initial release. The structure of the content and the default css for all existing gallery content will remain the same, even when the gallery is edited, eg. 

Artubus gallery on Gutenberg trunk in editor and frontend:
<img width="400" alt="Screen Shot 2021-08-17 at 3 29 07 PM" src="https://user-images.githubusercontent.com/3629020/129659742-91933847-a265-43f8-abea-f61afa79eaa2.png">

<img width="400" alt="Screen Shot 2021-08-17 at 3 29 36 PM" src="https://user-images.githubusercontent.com/3629020/129659785-b1371ed0-cfc6-4733-86d9-e1e02dbd6c37.png">

Existing Artubus gallery on Gutenberg Gallery refactor branch with gallery refactor experiment enabled:
<img width="400" alt="Screen Shot 2021-08-17 at 3 30 31 PM" src="https://user-images.githubusercontent.com/3629020/129659908-eac6aebd-9906-463d-82b1-e327af4e85c2.png">

<img width="400" alt="Screen Shot 2021-08-17 at 3 30 19 PM" src="https://user-images.githubusercontent.com/3629020/129659948-92ad3f83-9de8-40b5-ae5f-93a70824290a.png">

When a new gallery is added with the gallery refactor in place, it will inherit the new default styles for the new gallery format. While this means the layout will be different to the custom style layout, taking this approach means that at least the layout is not broken by the new structure, and gives theme authors time to add some additional selectors in order to apply their custom styling to the new structure:
<img width="400" alt="Screen Shot 2021-08-17 at 3 32 17 PM" src="https://user-images.githubusercontent.com/3629020/129660196-f5db1786-c6b4-4534-aeb9-6d17401d30f2.png">

<img width="400" alt="Screen Shot 2021-08-17 at 3 32 33 PM" src="https://user-images.githubusercontent.com/3629020/129660259-106fec72-ace4-480d-bfbc-03c57cb7cae1.png">

With just the addition of a couple of extra selectors to the arbutus theme css I was able to get the old and new gallery format looking pretty close, eg. the addition of:

```diff
.wp-block-gallery .blocks-gallery-item figure,
.wp-block-gallery .blocks-gallery-item image,
+ .wp-block-gallery .wp-block-image,
+ .wp-block-gallery .wp-block-image image {
	display: block;
	height: fit-content;
}

.gallery-caption,
.wp-block-gallery .blocks-gallery-image figcaption,
.wp-block-gallery .blocks-gallery-item figcaption,
+ .wp-block-gallery.blocks-gallery-grid.has-nested-images figure.wp-block-image figcaption {
	box-sizing: border-box;
	color: hsl(220, 0%, 100%);
	background: hsl(220, 10%, 13%);
	font-size: 14px;
	line-height: 1.2;
	margin: 0 0 8px;
	padding: 7px;
	position: relative;
	bottom: 0;
	left: 0;
	text-align: left;
	width: 100%;
}
```
<img width="983" alt="Screen Shot 2021-08-17 at 4 38 22 PM" src="https://user-images.githubusercontent.com/3629020/129664531-2cc70356-20c3-426a-b47a-b77abbc1b4a4.png">

With a bit of extra tweaking it should be possible to bring the heights exactly into line also I think.

**Comment by celloexpressions** [comment]
Thanks for working through this @glendaviesnz. The required CSS updates are much more involved than what you show above to address different post formats and customization options that this theme supports; however, that is a helpful starting point.

From the original testing report:

> Custom gallery excerpts are broken. Core PHP functions get_post_gallery() and get_post_gallery_images() still don’t work, and fallbacks for current block galleries don’t work because images are missing the data-id attribute.

The most substantial backwards compatibility issue still present is stemming from the disappearance of the `data-id` attributes on images. The theme includes a fallback for `get_post_gallery_images()`, which is also still broken. You would need to test the theme with gallery post formats to see that with the Arbutus theme. I thought that was fixed in a previous issue but will open another one - that causes severe breakage for a few themes, plugins, and sites that I maintain.
