### ISSUE TITLE
When the screen width is not large enough, the blocks toolbars can exceed the editor's container

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#30728]
This was reported by a user during a contributor day at Yoast on April 9.

## Description
When the screen width is not large enough, the blocks toolbars can exceed the editor's container.
This happens for instance when both the inserter panel and the block options panel are opened, and the block is near the right side of the screen.

## Step-by-step reproduction instructions
1. Create a new page / post
2. Add a three columns block
3. In the third column, add a paragraph, an image or a button block

## Expected behaviour
The block toolbar should be inside the editor container

## Actual behaviour
The block toolbar exceed the editor's container

## Screenshots or screen recording (optional)
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/33403964/114369919-cc3e1900-9b76-11eb-9b77-e28c22ce8b0c.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?Yes

## Device information
- Device: MacBook Pro
- Operating system: macOS 11.3
- Browser: Firefox Developer Edition 88.0b9 (64 bits)

**Comment by annezazu** [comment]
Thanks for opening :) Closing this though as it's already been reported here! https://github.com/WordPress/gutenberg/issues/30398
