### ISSUE TITLE
Site tagline should have options to make the text bold and italic

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#30738]
This was reported by a user during a contributor day at Yoast on April 9.

## What problem does this address?
The site tagline is basically a paragraph which display the tagline. So, it makes sense that it has the options to make it bold and italic, like paragraph block.

## What is your proposed solution?
Add options to make site tagline bold and italic

**Comment by mtias** [comment]
Closed in #33983.
