### ISSUE TITLE
Feedback: The sidebars in the site editor are confusing. Options are difficult to find.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30737]
During user testing on April 9, several users tried to follow the instructions from the FSE outreach program calls for testing, but
the tasks failed because the sidebars, mainly the global styles sidebar and the block settings sidebar, got mixed up.

Several users tried to change colors of the site title, but were not able to because:
- The block settings sidebar did not open when they selected the block.
- All users did not know how to manually open the block settings sidebar.
- The global styles sidebar was opened, and even though they found the text color setting, this did not affect the **link** color of the site title block. This was confusing, because the tagline block, which was not selected, did change color.

This is not helped by each sidebar having multiple tabs:
Template/block
Root/by block type

Comments:
_When you are new to this, you are really wondering if you need to find the settings in the list overview left sidebar, or the cogwheel right sidebar or on the block itself, all the options are all over the place._

_The List View is kind of mandatory given all the unclear and confusing visual feedback given in the main area - very hard to get hold of the right area without the List View!_

_It's a shame that the list view sidebar disappears when clicking on blocks_

_Perhaps this settings bar to the right should open up automatically if no bar is present to the right. Help the user out here - it’s not that clear that this bar is needed._

Regarding site title:
_It’s not clear that I have to go to the Settings and change the Text, font size etc. there._

**Comment by carolinan** [comment]
Related:
https://github.com/WordPress/gutenberg/issues/29461
https://github.com/WordPress/gutenberg/issues/29372

**Comment by annezazu** [comment]
More anecdotal feedback from the [FSE Outreach Program's sixth call for testing to pass along](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/):

> Alignment settings, as well as some other (Full Width settings) hiding in places I would have never guessed, if not going checking one by one all the elements in the toolbar.

> I always forget to toggle between page and block. I spent a few minutes wondering why the template selector wasn’t showing. I opened settings cog, wondered if I’d activated a writing preference in /settings … all before I remembered the very subtle white on white tabs to toggle between page and block... The main Side-bar holds the very important Block and Page controls, including “publish”. These controls are not really the “cog type” broad ranging “settings” we might see in the main Settings section of WP-admin we see true settings. The sidebar contents are more like “Edit controls” and we might more usually expect a pen icon, or a sidebar show./hide icon for this sidebar show/hide. The actual “settings” for the Gutenberg editor are under 3 vertical dots. Titled (invisibly) “Options”. This terminology and labelling or lack of it is confusing. “Settings” should be a sidebar icon, and labelled “show edit controls” and the 3 dots icon should be a cog icon.

>The UI isn’t clear. The weight on the “headings” should follow the structure’s weight. Hard to explain but “Template / Bolck” is a h1 in the sidebar. Advanced a h2? Link settings a h2, Description a h3, etc. They should feel that way. We loose to much time searching for them. They are all very similar.

**Comment by youknowriad** [comment]
What's remaining in that feedback? Is there any issue that reflect better the action items that need to be taken based on this?

**Comment by carolinan** [comment]
I think user testing is needed, especially to user test the site editor navigation which has added more sidebars.
I am not able to say if users find it easier now, I do not have a lot of contact with users.
