### ISSUE TITLE
List view does not update until autosave triggers

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30735]
## Description

Originally reported by @hedgefield.

When you change the number of columns in a column block, the list view does not update until the autosave is triggered, this is confusing.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a full site editing theme.
2. In the site editor, add a column block
3. Open the list view
4. Make changes to the column block. See that the list view does not update.

## Expected behaviour

The list view should be updated when changes are made.

## Actual behaviour

The list view does not update until the autosave is triggered.

WordPress information
WordPress version: 5.7
Gutenberg version:  10.3.2
Are all plugins except Gutenberg deactivated? yes
Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

Device information
Browser: Firefox 87.0
Operating System: MacOS Big Sur 11.2.1

**Comment by annezazu** [comment]
Tested this with Gutenberg 11.0, 5.7.2, and TT1. Couldn't replicate: 
https://user-images.githubusercontent.com/26996883/124832937-9e306100-df3a-11eb-9c5b-15b3f9178b47.mov

Closing this out for now but feel free to reopen if you're able to!
