### ISSUE TITLE
Use the block name in the "remove block" text in the toolbar setting

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30740]
This was suggested during a contributor day at Yoast on April 9;
_When I want to delete a column it’s called "remove block" instead of "remove column". It would make more sense to have the same name._

**Comment by andrewserong** [comment]
Just adding from #34863 that this feature could be helpful in many kinds of situations with container blocks where it can be challenging for a user to discern whether or not they'll be deleting an individual block or a container. E.g. Button with a Buttons block, or Image within the refactored Gallery block. For quick reference here's a screenshot of the Remove block button in the refactored Gallery block:

![image](https://user-images.githubusercontent.com/14988353/133567850-ebf68008-7ff5-407e-aab6-1939df688921.png)
