### ISSUE TITLE
Add Checkbox in Link Panel to Set Links as nofollow

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30742]
## What problem does this address?

It is difficult to set links as nofollow. The user has to edit as HTML to make the adjustment.

## What is your proposed solution?

My proposed solution is to have a checkbox in the link panel under the "Open in New Tab" option that lets users set their links as nofollow.

![image](https://user-images.githubusercontent.com/12677420/114402258-7eb2b380-9b58-11eb-821a-d69e6c0cc654.png)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/13542. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

In the mean time, the yoast SEO plugin and [the editorskit plugin](https://wordpress.org/plugins/block-options/) both offer this functionality; there may be other plugins that add this functionality to Gutenberg.
