### ISSUE TITLE
Dragging the navigation block causes errors

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#30743]
This was reported by a user during a contributor day at Yoast on April 9.

## Description
Dragging the navigation block around the editor causes errors

## Step-by-step reproduction instructions
1. Create a new page / post
2. Add a navigation block and menu items
3. Add others blocks as paragraphs
4. Try to drag the navigation block to another location

## Expected behaviour
The block should be in the new location without errors

## Actual behaviour
The block is in the new location with this error message : **This block has encountered an error and can not be previewed.**

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/33403964/114398713-04098880-9b98-11eb-92be-1194ab0a47a1.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?Yes

## Device information
- Device: MacBook Pro
- Operating system: macOS 11.3
- Browser: Firefox Developer Edition 88.0b9 (64 bits)

**Comment by jasmussen** [comment]
CC: @talldan @vcanales does this ring any bells? I think we encountered something similar recently with submenus.

Thank you for the ticket!

**Comment by talldan** [comment]
I can't reproduce it, it worked fine for me (Chrome and Firefox, Mac OS). 

Would be good to get some more specific steps to reproduce. Maybe if you can share the post content @JustinyAhin.

**Comment by talldan** [comment]
Ah, the fix only went into 10.4, so I think it's the same issue - https://github.com/WordPress/gutenberg/pull/30311

I'll close, but we can reopen if this can be reproduced in 10.4.

**Comment by jasmussen** [comment]
Thank you for looking Dan!
