### ISSUE TITLE
Search Block: Change Button Position Does Not Show Indication of What is Selected

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30746]
## Description

The change button position on the search block doesn't show any indication of what option is selected.

## Step-by-step reproduction instructions

1. Add a search block to the editor
2. Select either no button, button inside, or button outside, 

## Expected behaviour

The icon of the selected option to have a dark background to indicate that it has been selected.

## Actual behaviour

The backgrounds don't change for any of the options selected.

## Screenshots or screen recording (optional)

[https://1drv.ms/u/s!Agz9k3UFAizZig5eE0CWwaq9bdYR?e=4mNAZ3](url)
![image](https://user-images.githubusercontent.com/12677420/114401764-1532a500-9b58-11eb-9b51-d1235b4894b9.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

- WordPress version: 
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes, no other plugins are installed
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes Twenty Twenty-One

## Device information
- Device: 
- Operating system: 
- Browser: 

- Device: Desktop
- Operating system: Windows 10
- Browser: Microsoft Edge Version 89.0.774.68

**Comment by priethor** [comment]
Thanks for reporting @deborah86 ! I can reproduce this issue with Gutenberg 10.4-RC1 as well.

**Comment by javierarce** [comment]
Also, shouldn't the icons be aligned to the left?

**Comment by javierarce** [comment]
I found this issue is pretty similar to this older one: [Search Block: Button options needs indicator which option is active. #27330](https://github.com/WordPress/gutenberg/issues/27330).

@karmatosed's solution [here](https://github.com/WordPress/gutenberg/issues/27330#issuecomment-736023520), makes sense to me… so maybe we should close this issue?

**Comment by priethor** [comment]
I agree @javierarce, let's close it as duplicate.
