### ISSUE TITLE
Search Block: Add More Styling

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30747]
## What problem does this address?

It is difficult to style the search block to match certain aspects of a theme.

## What is your proposed solution?

Add additional options to customize the search block:

**Search Bar**
- Color Settings
- Border Settings

**Button**
- Fill and Outline Styles
- Color Settings
- Border Settings

![image](https://user-images.githubusercontent.com/12677420/114405345-74de7f80-9b5b-11eb-965b-7e283d32fe5a.png)

**Comment by annezazu** [comment]
@deborah86 thanks so much for opening this up! I'm going to close this out though as this is currently being tracked in this issue: https://github.com/WordPress/gutenberg/issues/22071 If you believe this issue should still be open though, just let me know :)
