### ISSUE TITLE
[Feedback] Navigation Component doesn't reflect what is currently edited

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#30741]
## Description

Came up as feedback during an internal contributors day at Yoast, by users testing FSE.
The "Content" section in the main navigation was a source of a lot of confusion and frustration, nobody understood exactly how it works and explaining it was troublesome. If we need to spend 10 minutes explaining what the menu does, then we're doing something wrong...

## Step-by-step reproduction instructions
* Open the site editor
* From the main navigation go to `Content` -> `Pages` -> `Sample Page` (or any other page)
* Once the page loads, open up the main navigation again
* Notice that it's on `Theme` -> `Templates` -> `Page` instead of what we previously selected.

## Expected behaviour
If the user clicks on something in the navigation, they expect that to be selected.

## Actual behaviour
Not what is expected.

**Comment by annezazu** [comment]
Updated the title to match the feature :)

**Comment by youknowriad** [comment]
The navigation changed a lot in the site editor. This issue is not valid anymore.
