### ISSUE TITLE
Navigation editor: it shouldn't be possible to add a menu to itself

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#30745]
Currently, it's possible to create a menu and add it to itself when selecting the menu from the "Existing menus" dropdown. 

I think this could be a minor bug since the backend seems to ignore the recursion, returns a 200 status, and the menu doesn't get broken. 

## Step-by-step reproduction instructions

1. Create a menu using the Navigation (beta) option in Gutenberg.
2. Click on the placeholder.
3. Click on the "Existing menu" dropdown.

## Expected behaviour

If the user has several menus, the name of the current one shouldn't appear on the list. If this is the first menu, the dropdown shouldn't appear or at least it shouldn't contain the current menu as an option.

## Actual behaviour

The list contains the name of the current menu.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/4933/114398987-b7767b00-9ba0-11eb-8f17-6d96f75a3288.mov

## WordPress information
WordPress version: 5.7
Gutenberg version: 10.3.2
Are all plugins except Gutenberg deactivated? Yes

**Comment by getdave** [comment]
This seems like something that needs to be fixed. Thanks @javierarce.
