### ISSUE TITLE
Add a Contact Form Block

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30754]
## What problem does this address?

This is frustrating because a lot of blogs use forms as a way to communicate with users. There is no basic form block that adds a contact form to the website. There are only a handful of plugins that add a contact form to a website. This is something basic that should come with WordPress.

There is not a native form block in WordPress. 

## What is your proposed solution?

A native form block to be added to Gutenberg with basic styling features.

**Comment by Soean** [comment]
Hey @deborah86,
thanks for opening this feature request. We already have a ticket about this feature, see #21443. So I am closing this one, please use the existing one for further discussions.
