### ISSUE TITLE
The Matrix Alignment Control Component toolbar icon does not show up in ACF Pro blocks after Gut. v10.3.0 update.

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#30759]
ACF pro has added support for the Matrix component from the beginning and it worked like a charm, until Gutenberg 10.2.1.

When updating Gutenberg to v10.3.0 or newer, the Matrix Alignment Icon on the toolbar for the ACF Pro created blocks simply does not show up.

This is how ACF Pro is referencing the component:

const BlockAlignmentMatrixToolbar = ( wp.blockEditor.BlockAlignmentMatrixToolbar || wp.blockEditor.__experimentalBlockAlignmentMatrixToolbar );

I checked all the 10.3.0 released notes to see the changes for it, but there was nothing documented there (that I could see).

Can anyone please point us in the right direction?

Here is the full conversation with Elliot Condon (Developer of ACF Pro).

https://github.com/AdvancedCustomFields/acf/issues/481#issuecomment-817390086

Thanks in advance.

**Comment by CreativeDive** [comment]
I love the response time here.

**Comment by annezazu** [comment]
Hey @nick6352683 @CreativeDive! Thanks for bringing this to the GitHub repo. From what I can see, this is relying on an experimental API and is referenced here as part of a quality control effort with experimental APIs leading up to 5.8: https://github.com/WordPress/gutenberg/issues/31416 @youknowriad  might you be able to chime in here?

**Comment by nick6352683** [comment]
@annezazu , Thanks a million, we would appreciate any help here to point us in the right direction.

**Comment by vdwijngaert** [comment]
Actually, this is an issue that needs fixing in ACF Pro. I made a pull request to accommodate the change of `__experimentalBlockAlignmentMatrixToolbar` to `__experimentalBlockAlignmentMatrixControl`. Elliot will be able to handle the rest!

**Comment by annezazu** [comment]
Thanks so much @vdwijngaert for jumping in here :)

**Comment by CreativeDive** [comment]
@elliotcondon

**Comment by nick6352683** [comment]
ACF Pro v5.9.6 fixed this issue... thanks for all who made this happen !

**Comment by annezazu** [comment]
So happy to hear that. Thanks for looping back to let us know :)
