### ISSUE TITLE
Button Block: Gap Not Showing When Inserted into Form Block in Editor

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30756]
## Description

The button block does not show the gap between two blocks inserted side-by-side when you are in the editor view if you place them in a column. The blocks are not aligned correctly in the editor.

## Step-by-step reproduction instructions

1. Add a column 50/50
2. On one side of the column add text
3. On the other side of the column add a button block
4. Add a second button block next to the first button block

## Expected behaviour

I expect there to be a gap between the two button blocks. The way it looks in the editor matches the way it looks on the front-end. The blocks to be aligned correctly to the column in the editor.

## Actual behaviour

There is no gap between the button blocks displayed in the editor.

## Screenshots or screen recording (optional)

**Editor**

![image](https://user-images.githubusercontent.com/12677420/114420647-5a130780-9b69-11eb-8c47-c29b2301182c.png)

**Front-End of Website**

![image](https://user-images.githubusercontent.com/12677420/114420752-71ea8b80-9b69-11eb-920f-f2017f78b1cb.png)

## WordPress information
- WordPress version:  5.7
- Gutenberg version:  Not Installed
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes, Twenty Twenty-One

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Microsoft Edge Version 89.0.774.68

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; I think this may have been fixed; the gap appears for me in the editor as well as on the front end. 

![Selection_161](https://user-images.githubusercontent.com/955351/159080181-d43fa287-0cc9-4a46-941a-b023cc1a85dd.jpg)
 
Using WordPress 5.9.2. and gutenberg 12.7.1, twentytwentyone 

Please reopen if you are still experiencing this issue.
