### ISSUE TITLE
Table Block: Background Color Styles from Theme not Showing

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30751]
## Description

The correct background colors from the theme are not present. It is just showing general background colors.

## Step-by-step reproduction instructions

- Insert a table
- Click on the tab for the block styles
- Click on the color dropdown

## Expected behaviour

I expect to see the background colors from the theme.

## Actual behaviour

Only 4 background colors are shown. They are not inherited from the theme.

## Screenshots or screen recording (optional)

Showing
![image](https://user-images.githubusercontent.com/12677420/114408374-326a7200-9b5e-11eb-834b-e950b499b7a8.png)

Should See
![image](https://user-images.githubusercontent.com/12677420/114408561-62b21080-9b5e-11eb-963c-856740998358.png)

## WordPress information
- WordPress version:  5.7
- Gutenberg version:  Not Installed
- Are all plugins except Gutenberg deactivated?  Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Microsoft Edge Version 89.0.774.68

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/19659. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
