### ISSUE TITLE
Feature request: Global Styles - allow modifying alignment widths

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#30761]
## What problem does this address?

In FSE global styles, it is possible to edit the typography and colors but some styles such as alignments are not available for editing.

## What is your proposed solution?

Open up global styles editing to more styles such as alignments, for example in TT1-Blocks theme, _contentSize_ is _610px_ and _wideSize_ is _1240px_.

Users should be able to change these alignment widths.

**Comment by skorasaurus** [comment]
Does https://github.com/WordPress/gutenberg/issues/29506 cover what you're looking for?

**Comment by Sandstromer** [comment]
I think "Allow modifying the default values in Global Styles -> Spacing." does yes.

**Comment by skorasaurus** [comment]
thanks, could you edit your title to reflect that so it's easier to find?

**Comment by carolinan** [comment]
The ability to change the content width and wide width values is already possible under the layout panel in the styles
sidebar ( so only for themes that support the global styles)

**Comment by skorasaurus** [comment]
This has been implemented for a while in theme.json 

e.g. 

```
"layout": {
      "contentSize": "75 vw",
      "wideSize": "85 vw"
    },
```
