### ISSUE TITLE
In-between inserter should not show during multi-select

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3076]
We should disable the inserter between blocks when multiselect is engaged:

![image](https://user-images.githubusercontent.com/548849/31813947-68473198-b588-11e7-9930-61cb7df75b8f.png)

**Comment by iseulde** [comment]
Should it be removed entirely when there is a selection, or just inside the selection? It might be a bit strange that you can no longer insert anything in between blocks, not sure if a selection should affect that as it anyway just disappears.

**Comment by mtias** [comment]
I think if you select multiple blocks it doesn't make much sense to insert in between.

**Comment by iseulde** [comment]
So should we leave them outside of the selection then?

**Comment by mtias** [comment]
Not sure I understand. You mean before / after the multiselect block?

**Comment by iseulde** [comment]
Right, outside the selected blocks. I'm just wondering what would happen if someone selects some blocks, then scrolls down and tries to insert a block somewhere else. Normally a selection does not block these actions/UI.

**Comment by mtias** [comment]
@iseulde ah, I see what you mean. Yes, I only mean we should not show the sibling inserter _within_ the selection group. Outside of it it should be fine.
