### ISSUE TITLE
Latest Comments Block: Spacing Without Excerpt is Different in the Editor

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30771]
## Description

When you add a comment block to the editor and remove the excerpt the spacing is not correct. It shows correct on the website preview.

## Step-by-step reproduction instructions

1. Add a Latest Comments Block
2. Toggle the Display Excerpt Option off

## Expected behaviour

The layout of the block not to change drastically and to display like it does in the website preview.

## Actual behaviour

There is no padding between the comments.

## Screenshots or screen recording (optional)

**Block in Editor**
![image](https://user-images.githubusercontent.com/12677420/114450869-660fc100-9b8b-11eb-9e4e-45fffe748f03.png)

**Block in Website Preview**
![image](https://user-images.githubusercontent.com/12677420/114451078-ae2ee380-9b8b-11eb-9f04-30ac81f37e4f.png)

## WordPress information
- WordPress version:  5.7
- Gutenberg version:  Not Installed
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes, Twenty Twenty-One

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Microsoft Edge Version 89.0.774.68

**Comment by kathrynwp** [comment]
Hi, @deborah86! I'm no longer able to replicate this, so I'm going to go ahead and close this out. If you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be very glad to reopen it!

![Add_New_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/184248429-8f357595-9e34-4c64-8e40-c9db9137a94c.jpg)

**Tested with:**

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
Twenty Twenty-Two 1.2 and Twenty Twenty-One 1.6

Firefox 103.0.1
macOS 12.2.1
