### ISSUE TITLE
Add Block:  Uncategorized Should Be Hidden if There are No Blocks

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30776]
## What problem does this address?

It is frustrating that uncategorized is available when it doesn't contain any blocks.  It led me to believe there were missing blocks.

## What is your proposed solution?

Have the option to be disabled if there are no blocks under the category.

![image](https://user-images.githubusercontent.com/12677420/114457861-5f854780-9b93-11eb-9d0f-4464f7044f3e.png)

**Comment by skorasaurus** [comment]
I think this has been implemented; I do not see the uncategorized category when I open the add a prompt. 

Please reopen if you are still experiencing this and thank you for reporting.
