### ISSUE TITLE
Query Block won't render when placed in 404 Template

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30781]
## Description

When adding a Query Block to the 404 template, it doesn't show up on the front end of the site. I tried moving it around to different parts of the template but it simply won't render. 

## Step-by-step reproduction instructions

1. Setup a site with FSE and TT1 blocks
2. Open the Site Editor.
3. Use the Navigation component to go to the 404 template.
4. Add a query block into the 404 template. 
5. Save changes and view the 404 page. 

## Expected behaviour

I expect to see the Query block results appear. 

## Actual behaviour

The Query block doesn't not show up on the front end. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/114465493-6cf6fd80-9ba4-11eb-892d-2a787a2a0ea4.mov

Front end:

<img width="1342" alt="Screen Shot 2021-04-12 at 3 33 43 PM" src="https://user-images.githubusercontent.com/26996883/114465551-7da77380-9ba4-11eb-82ed-99207e3e3349.png">

Editor:

<img width="1272" alt="Screen Shot 2021-04-12 at 3 34 01 PM" src="https://user-images.githubusercontent.com/26996883/114465577-87c97200-9ba4-11eb-9453-c32ff2ce6ed7.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.4.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome v 89

**Comment by ntsekouras** [comment]
It has to do with context detection and previews. If we have a Query block with `inherit:true` to a `404` will not have any posts to output from the loop. If we do set `inherit:false` , Query will have output.

Related: https://github.com/WordPress/gutenberg/issues/30369

**Comment by mtias** [comment]
Also something we could do is add some more text when the setting is toggled on describing that it's reading from the current template, and what that template is.

**Comment by annezazu** [comment]
I am going to close this out since it seems as though this is covered in the issue around context detection and it seems wise to consolidate currently.
