### ISSUE TITLE
[Columns Block] Make it clearer how to return to original width option after insertion

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30782]
## What problem does this address?

Currently, if you try to insert a column into the Site Editor, you're able to set two different width options: Wide or Full.  However, you're not able to return to the initial state a column block was in. This makes for a confusing experience if you just wanted to try out Wide & Full but decided to return to the initial setup. Here's a video to explain:

https://user-images.githubusercontent.com/26996883/114473364-4db29d00-9bb1-11eb-8d4f-1f9498b8ab57.mov

Initial width:

<img width="1258" alt="Screen Shot 2021-04-12 at 5 06 00 PM" src="https://user-images.githubusercontent.com/26996883/114473424-70dd4c80-9bb1-11eb-9c98-36811ddbbbf3.png">

Wide width:

<img width="1336" alt="Screen Shot 2021-04-12 at 5 06 05 PM" src="https://user-images.githubusercontent.com/26996883/114473426-733fa680-9bb1-11eb-9a74-f474c745db4c.png">

Full width:
<img width="1395" alt="Screen Shot 2021-04-12 at 5 06 09 PM" src="https://user-images.githubusercontent.com/26996883/114473433-763a9700-9bb1-11eb-844e-d8d66316257a.png">

Because you only have two options (wide & full), you're not able to get back to the original state unless you use the undo button or delete & readd. 

## What is your proposed solution?

Allow for an option to return to the initial width setting.

**Comment by Mamaduka** [comment]
You can go back to the original width by click the currently selected width. But I also find this UX a little confusing.

**Comment by annezazu** [comment]
@Mamaduka can you clarify perhaps with a video or screenshot of how you might get back to the original width? I'm not able to find a way back.

**Comment by Mamaduka** [comment]
@annezazu Sure thing.

Here's a screencast:

https://user-images.githubusercontent.com/240569/114659803-4b615780-9d05-11eb-8b45-ccc2d12a9e89.mp4

**Comment by javierarce** [comment]
Interesting discovery, @Mamaduka!

I did a little research and I noticed that the column block [doesn't support](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/columns/block.json#L12) the `center` alignment property. The funny thing is that if I add it, I'm able to select the "Align center" option… but just for themes that aren't FSE ready (!) 

For themes that support the FSE, this doesn't seem to work consistently. For instance, I can add the `left` and `right` properties, but then it's only available for some themes and not for others 😅

That said, I agree with your solution @annezazu, and would also expect to have an "Align center" property to return to the initial state the block was in.

**Comment by annezazu** [comment]
Wow! Mind blowing. That's definitely not intuitive 😆 so I'm going to leave this open but edit the title to make it a bit clearer that it's less about _allowing_ the option and more about making it clearer.

**Comment by Mamaduka** [comment]
Maybe we can add the "Remove Alignment" menu item at the bottom of the list.

Example from the CoBlocks animations menu.

![CleanShot 2021-04-20 at 07 44 46](https://user-images.githubusercontent.com/240569/115334583-b64eda80-a1ac-11eb-95c8-31e1bb4530e3.png)

**Comment by Mamaduka** [comment]
I just noticed "None" and "No alignment" options in mockups for "Dimensions Panel."

What do you think about adding this option?

![](https://user-images.githubusercontent.com/1204802/105170673-9102ef80-5b1d-11eb-912d-e0cf6095f43e.png)

**Comment by annezazu** [comment]
Great thinking - I really like this :)
