### ISSUE TITLE
Various Gutenberg elements flicker on Safari 14.1

### ISSUE THREAD

**Issue by eduard-co** [WordPress/gutenberg#30803]
On the latest Safari 14.1 the Gutenberg elements flicker while moving the mouse.

https://user-images.githubusercontent.com/25321905/114554928-e3146680-9c6f-11eb-89d6-3bf172ee6c01.mov

**Comment by kjellr** [comment]
I'm seeing a lot of flickering as well: 


![test-back](https://user-images.githubusercontent.com/1202812/116280871-21715180-a757-11eb-8ba9-3ab4fe1a61d5.gif)

For reference, this is how that looks in the front end: 

![test-front](https://user-images.githubusercontent.com/1202812/116281009-436ad400-a757-11eb-9460-230fe909ecb4.gif)

I'm able to reproduce across multiple sites, by using the following test content: 
https://gist.github.com/kjellr/9d86099ada72ef2db6591f141d793445

**Comment by eduard-co** [comment]
Should be fixed asap. I don't want to use Chrome/Firefox.

**Comment by gwwar** [comment]
Background color flashing should be fixed by https://github.com/WordPress/gutenberg/pull/32747

I'm working on the flickering text fix in https://github.com/WordPress/gutenberg/pull/32824

**Comment by gwwar** [comment]
This one should be fixed by #32824

**Comment by jasmussen** [comment]
Excellent work!

**Comment by eduard-co** [comment]
Thank you so much for this!

But, pardon my ignorance. When is this actually gonna ship?

**Comment by gwwar** [comment]
Fixes should land in Gutenberg 11, not sure if https://github.com/WordPress/gutenberg/pull/32824 will make it into WP 5.8. What do you think @ellatrix @youknowriad?

**Comment by youknowriad** [comment]
Is this the last PR for these safari fixes? I can try to add the backport label and include in RC2.

**Comment by gwwar** [comment]
@youknowriad Yes, this is the last one that I'm aware of!

**Comment by gwwar** [comment]
I ended up filing 3 seperate WebKit bugs:

Background Flashing: https://bugs.webkit.org/show_bug.cgi?id=227532
Flickering elements/text: https://bugs.webkit.org/show_bug.cgi?id=227705
Scrollbar is wrong color: https://bugs.webkit.org/show_bug.cgi?id=227545

**Comment by eduard-co** [comment]
> Is this the last PR for these safari fixes? I can try to add the backport label and include in RC2.

is this still on track for inclusion in rc2?

**Comment by youknowriad** [comment]
RC2 is already released but it will be included in RC3
