### ISSUE TITLE
Question: Should block type title be displayed in block inspector more prominently (separately)?

### ISSUE THREAD

**Issue by vladanost** [WordPress/gutenberg#3081]
When you select a block its properties appear on the right in the inspector. 

Inside the inspector you first have a small description of the block which does include the block title but it’s not obvious what is the current block type.
Next comes the title in the form of {Block title} Settings. At that point I’m still not sure what is the title of the block. I could maybe figure it out but some blocks like Paragraph have several section (Text Settings, Background Color, Text Color, Block Alignment) and I feel I’m still not sure about block name.

Another problem I see is the inconsistency in naming best shown in Paragraph block where in inspector it is called “Text”.

I think clear (and unique) block type title will simplify user experience.

**Comment by jasmussen** [comment]
I like this. Perhaps we can even show the block icon next to the title. Want to do a mockup? Otherwise I can look at it.

**Comment by vladanost** [comment]
Thanks, maybe you could do the mockup, I'm a developer, design is not really my thing :)

**Comment by jasmussen** [comment]
Will do!

**Comment by maddisondesigns** [comment]
Totally agree. There needs to be some sort of indicator or label for each block. Currently, when I look at a page, I have no idea what each block is.

**Comment by jasmussen** [comment]
Here's a quick mockup:
 
![editor w sidebar block selected](https://user-images.githubusercontent.com/1204802/33883660-e575c9d0-df3c-11e7-9c09-ea9011ef71fe.png)

**Comment by vladanost** [comment]
@jasmussen Great work. I like the idea to show block type indicator in several places.

**Comment by maddisondesigns** [comment]
@jasmussen I really like the block title and short description added to the sidebar, but can we make the descriptions a little more meaningful. Saying _"Great things start here."_ is cute, but isn't actually a useful description for the user and doesn't tell them anything about the block. Something like _"This is a simple text only block for inserting a single paragraph of content."_ would be much more useful and descriptive.

**Comment by Soean** [comment]
@maddisondesigns Same was mentioned here: https://github.com/WordPress/gutenberg/issues/3375

**Comment by jasmussen** [comment]
Apologies I didn't respond sooner. I absolutely agree — the descriptions as they are now were churned out _fast_ because _every block should have a description_, but they should absolutely be improved. I like the Separator description, for example:

> Use the separator to indicate a thematic change in the content.

Your suggestion sounds good to me. If we can improve all the descriptions by adding comments to #3375, I can PR'em once we're satisfied.

**Comment by karmatosed** [comment]
I think showing in the sidebar is good and it solves another issue we've had for a while about fixing the descriptions so 👍 for me to getting this in.

**Comment by jasmussen** [comment]
#4103 improves the text description for now.
