### ISSUE TITLE
Maintain Block Options When Transforming To/From Heading & Paragraph

### ISSUE THREAD

**Issue by eric-michel** [WordPress/gutenberg#30815]
## What problem does this address?
It's not unusual that we need to transform a Paragraph to a Heading block, or vice versa. When doing so, all block options are reset to default (unless I'm missing an option to keep them). It would be nice to take a Paragraph block with a set font size, color, and custom class, anchor, etc and convert it directly to a Heading block while maintaining those options.

## What is your proposed solution?
Ideally, all block options in common between block transformations would be maintained. Realizing that may be harder than it sounds, at least having the Heading and Paragraph blocks maintain options during transformation would be a huge upgrade.

**Comment by eric-michel** [comment]
This PR (https://github.com/WordPress/gutenberg/pull/37596) accomplishes most of what I was looking for (thanks @jorgefilipecosta!), but still doesn't maintain the `Additional CSS class(es)` after transformation. I'm wondering if that is an option?

**Comment by jorgefilipecosta** [comment]
Hi @eric-michel, this is a good point in my view classes should also be kept during transforms but it may not be something consensual and for some cases, it may not expected. I will try to put a PR for that and we will see what others think.
Thank you for bringing this issue to my attention 👍

**Comment by eric-michel** [comment]
Sure thing @jorgefilipecosta! And thanks so much for the works you've done on this already! Makes things way easier.

In my personal workflow, I only ever use transforms on items that are going to look and function the same, but just need to use a different tag (like `p` to `h#` or vice versa) or be added to a group. So maintaining classes is a no-brainer there. Getting feedback from others who may use transforms differently is a great idea. Perhaps some transforms should maintain classes, and some shouldn't, depending on how similar they are.

**Comment by jorgefilipecosta** [comment]
> Sure thing @jorgefilipecosta! And thanks so much for the works you've done on this already! Makes things way easier.
> 
> In my personal workflow, I only ever use transforms on items that are going to look and function the same, but just need to use a different tag (like `p` to `h#` or vice versa) or be added to a group. So maintaining classes is a no-brainer there. Getting feedback from others who may use transforms differently is a great idea. Perhaps some transforms should maintain classes, and some shouldn't, depending on how similar they are.

Hi @eric-michel now classes are kept during the transforms https://github.com/WordPress/gutenberg/pull/38964. I'm closing this issue. Thank you for all the insights you provided 👍

**Comment by eric-michel** [comment]
@jorgefilipecosta that's fantastic! Much appreciated!

**Comment by eric-michel** [comment]
@jorgefilipecosta I just started updating my sites to WP 6.0, and this transformation works flawlessly. This will make my users' lives soooo much easier. Thanks again for your amazing work!

**Comment by jorgefilipecosta** [comment]
Thank you for the feedback, that's good to hear :)
