### ISSUE TITLE
Multi-selection triggers for font size slider

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#3082]
## Issue Overview
First reported by @mtias. Moving the font size slider in the block inspector for the paragraph block triggers multi-selection.

## Steps to Reproduce (for bugs)
1. Select a paragraph block.
2. Open the block inspector.
3. Make sure that the font size slider is not at the same height as the block. Scroll it a bit up or down.
4. Move the slider. Multi-selection should trigger between the block and height of the slider.

## Expected Behavior
Nothing should trigger multi-selection in the inspector.

## Possible Solution
This is caused by event bubbling in the inspector portal. See https://reactjs.org/docs/portals.html#event-bubbling-through-portals. Cc @aduth, this might be interesting to know. :)

**Comment by iseulde** [comment]
Another interesting side effect is that typing in fields in the inspector will hide the block UI. :)

**Comment by iseulde** [comment]
I can start adding `this.node.contains( event.target )` checks, but I'm not sure if that's a good way to fix this. We'll need to add this to every event handler... Drag should also not be prevent etc. Might have unexpected consequences in `WritingFlow`.

**Comment by iseulde** [comment]
This happens since c0cd4a560f5c4c01f8353422214d75d563d2f527.

**Comment by aduth** [comment]
Should this be closed given #3083? We should probably create a canonical issue for how to move forward with Slot Fill implementation.

**Comment by iseulde** [comment]
Sure, if it stays in the back of our finds for future PRs. :)

**Comment by aduth** [comment]
Also related: #3075
