### ISSUE TITLE
props.toggleSelection doesn't work

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#30829]
## Description

Issuing `props.toggleSelection(true);` does not select the block.

## Expected behaviour
`props.isSelected = true;`. And block should be focused.

## Actual behaviour
`props.isSelected` remains unchanged. Block does not focus.

## WordPress information
- WordPress version:  5.7.0
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS 11.2.3
- Browser: Chrome 89.0

**Comment by dhruvkb** [comment]
Hey @navxio, could you please provide additional information such as which block you were trying to select that was not being selected?

**Comment by navxio** [comment]
@dhruvkb trying to use this in my own custom block.

**Comment by annezazu** [comment]
@navxio since this is more of a help request for a custom block rather than related to core Gutenberg functionality, I'm going to go ahead and close this out. For future related help like this, I would head to https://wordpress.stackexchange.com/
