### ISSUE TITLE
MEDIA_TYPE_VIDEO only defined in Gutenberg native

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#30832]
I'm using Gutenberg in a setting outside of WordPress and where all the Gutenberg modules are bundled together, as opposed to being external.

I'm running into this compile warning (with a similar one for `MEDIA_TYPE_IMAGE`)

`WARNING in ./node_modules/@wordpress/block-library/build-module/cover/shared.js 36:52-68
export 'MEDIA_TYPE_VIDEO' (imported as 'MEDIA_TYPE_VIDEO') was not found in '@wordpress/block-editor'`

Looking at `@wordpress/block-editor` these constants are only defined in the `.native.js` file https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/media-upload/index.native.js

As far as I can tell this is not exported by the non-native module, and so causes the warnings. The problem doesn't seem to happen when the modules are used externally (I'm not sure why, though)

I'm not entirely sure how the native modules work, or why the problem doesn't exist when everything is used externally, but should these two constants be made available outside of the native file as they are used by a non-native file (the cover block)?

**Comment by johngodley** [comment]
You can recreate this with a dummy project:

`package.json`
```
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "wp-scripts build"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@wordpress/block-editor": "^5.3.1",
    "@wordpress/block-library": "^2.29.1",
    "@wordpress/scripts": "^14.1.0"
  }
}
```

`src/index.js`
```
import { registerCoreBlocks } from "@wordpress/block-library";

registerCoreBlocks();
```

`webpack.config.js` <== this disables the dependency injection plugin
```
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

module.exports = {
  ...defaultConfig,
  plugins: [],
};
```

If you `npm run build` you will see the warning:

```
WARNING in ./node_modules/@wordpress/block-library/build-module/cover/shared.js 36:52-68
"export 'MEDIA_TYPE_VIDEO' was not found in '@wordpress/block-editor'
 @ ./node_modules/@wordpress/block-library/build-module/cover/transforms.js
 @ ./node_modules/@wordpress/block-library/build-module/cover/index.js
 @ ./node_modules/@wordpress/block-library/build-module/index.js
 @ ./src/index.js
```

**Comment by gziolo** [comment]
The same issue was reported by @sarayourfriend on WordPress Slack in the #core-js channel:

https://wordpress.slack.com/archives/C5UNMSU4R/p1618497029294800

I can confirm that this issue exists. The constant shouldn't be exposed from `@wordpress/block-editor` in the first place.

**Comment by sarayourfriend** [comment]
What's the correct way to solve this? Remove the import from `block-library` and just duplicate the constant across the packages? Just want to make sure it's clear before someone dives into fixing this.

**Comment by gziolo** [comment]
> What's the correct way to solve this? Remove the import from `block-library` and just duplicate the constant across the packages? Just want to make sure it's clear before someone dives into fixing this.

Yes.  The constant shouldn't be exported from `@wordpress/block-editor` in the first place. The simplest approach would be to duplicate them for the Cover block.
