### ISSUE TITLE
Previews are broken for block patterns and block styles

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30856]
## Description
The previews for block patterns and blocks styles appear to be empty/broken.

## Step-by-step reproduction instructions
Block styles
1. Add a block with a style, like a quote
2. View the sidebar, note that the previews are empty

Block patterns
1. Click the + button in the top left of the screen
2. When the inserter sidebar opens, click the patterns tab
3. Note that only text is displayed for each pattern, the preview is empty

## Expected behaviour
Previews work

## Actual behaviour
Previews don't work

## Screenshots or screen recording (optional)
Block styles
<img width="252" alt="Screenshot 2021-04-15 at 10 30 31 am" src="https://user-images.githubusercontent.com/677833/114805961-81bad780-9dd6-11eb-9a0f-f5881442841f.png">

Block patterns
<img width="343" alt="Screenshot 2021-04-15 at 10 31 06 am" src="https://user-images.githubusercontent.com/677833/114805975-867f8b80-9dd6-11eb-99cc-f63b8c8cf9b8.png">

## WordPress information
- WordPress version: 5.7ish
- Gutenberg version: 10.4ish
- Are all plugins except Gutenberg deactivated? Y
- Are you using a default theme (e.g. Twenty Twenty-One)? Y (TT1)

## Device information
- Device: Desktop
- Operating system: Mac OS
- Browser: Brave

**Comment by ntsekouras** [comment]
This is happening for me as well from yesterday and I asked some folks, but had no problem with the previews.

It seems that `useResizeObserver` which is import `useResizeAware from 'react-resize-aware';` returns `null heights/widths`. I didn't find any changes in the react-resize-aware recently..

Also I tried with Firefox and previews work okay.. In latest chrome the problem is there.. 🤔

**Comment by ntsekouras** [comment]
I just nuked my dev environment and restarted and Previews are back... 🤔

**Comment by ntsekouras** [comment]
@talldan is this still a problem for you? I think we can close this, as it seems it had to do with dev environment problems, no?

**Comment by talldan** [comment]
Seems fixed now after `npm install`ing  and rebuilding. Maybe a dependency update?
