### ISSUE TITLE
Change documentation references of Block Style Variations to Block Styles

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#30850]
Since the Block Variations API has been implemented it is somewhat confusing to refer to Block Styles as Block Style Variations.

I recommend that the docs be updated to reflect the change in terms. It will help to distinguish them from Block Variations as more documentation is added to support that feature.

**Comment by skorasaurus** [comment]
Thanks! closing since https://github.com/WordPress/gutenberg/pull/30911 has been merged

**Comment by mkaz** [comment]
Thanks @skorasaurus !

@DaisyOlsen If you include `Closes #30911` in the description it would've auto closed, I saw you had it in a comment, but it appears it has to be in the description. [GitHub docs on it](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), looks like in a commit message will also do it.

**Comment by DaisyOlsen** [comment]
Thanks I'll remember that for next time!
