### ISSUE TITLE
Image Block: Drag and drop from desktop shows placeholder when processing

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30858]
## Description

If you insert an image block first and drag an image onto the placeholder, you see the placeholder pushed down below while the image is being uploaded:

![placeholder bug](https://user-images.githubusercontent.com/1204802/114836878-63071180-9dd3-11eb-82a8-d5b215aef7e0.gif)

While being uploaded, this placeholder should be invisible as it's no longer needed.

## Step-by-step reproduction instructions

1. Insert an image block
2. Drag an image from your desktop onto the placeholder

**Comment by jasmussen** [comment]
CC: @Mamaduka — probably unrelated, but I recall us chatting about a similar Cover issue, so in case you have any insights. Thank you for looking!

**Comment by Mamaduka** [comment]
@jasmussen happy to have a look.

**Comment by jasmussen** [comment]
Thanks, let me know if I can help. Happy to review.
