### ISSUE TITLE
New template flow in the post editor: Ask the creator whether the template should be reusable or specific

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#30865]
In the current flow...

https://user-images.githubusercontent.com/846565/114849153-656b6a80-9dd7-11eb-94aa-517632d0b167.mp4

... $custom templates (that can be applied to any content) are created. But in some cases a user might want the new template to only be used by the post / page being edited. E.G a cart or checkout template.

It also seems plausible that a specific template could be the expected result in this flow, so we might make that the default behaviour.

Specific templates do not exist yet, and present some architectural requirements:

* It should not be possible to select a specific template in the template selector, unless editing the associated post / page
* When editing a post / page that has a specific template, the user must be made aware that changing this template will result in the specific template being deleted

**Comment by carlomanf** [comment]
> Specific templates do not exist yet, and present some architectural requirements:

They do exist, through the single-$posttype-$slug pattern.

**Comment by jameskoster** [comment]
Sorry I meant they do not exist in the site editing UI. Unless I am mistaken there is no way to create a specific template yet, outside of manually creating a .html file in your theme?

**Comment by carlomanf** [comment]
The latest version of trunk does expose the template post type in the Appearance menu, but there is also a long-unsolved bug that prevents the user setting their own slug, so on a practical level you are right. I do still like the added convenience of this proposal, but the single-$posttype-$slug pattern should definitely be used to implement it rather than any other means.

**Comment by jameskoster** [comment]
I don't think this needs a dedicated issue, we can explore it generally as a part of https://github.com/WordPress/gutenberg/issues/31591.
