### ISSUE TITLE
Incorrect position of "add new block/block list" in rtl mode

### ISSUE THREAD

**Issue by man4toman** [WordPress/gutenberg#30867]
In rtl version of WordPress 57, there is a problem with **add new block/block list** position.
Please check the screenshot.

![block-editor-block-list](https://user-images.githubusercontent.com/935397/114856908-e721bf00-9dfc-11eb-93b8-0c6cb068dbd7.png)

- WordPress version: 5.7
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
- Operating system: Windows 10
- Browser: Latest version of Firefox and Chrome

**Comment by sunnyssr** [comment]
I was able to reproduce this error too. 👍 

Here is the link to WordPress.org ticket which is related: https://core.trac.wordpress.org/ticket/52809

**Comment by kathrynwp** [comment]
The user in [this forum thread](https://core.trac.wordpress.org/ticket/52809) is reporting that this bug has returned in Gutenberg 15.3.1.

**Comment by kathrynwp** [comment]
Here's a screenshot showing the issue:

<img width="1287" alt="ویرایش_برگه_‹_Testing_Testing_123_—_وردپرس_and_Sarah_Snow_-_A8C_-_Slack" src="https://user-images.githubusercontent.com/7662449/225747974-73bde9f3-2d7d-46da-b76e-63f2b3fcf17e.png">

### Testing Conditions

WordPress 6.1.1
Gutenberg 15.3.1
No other active plugins
Twenty Twenty-Three
A RTL language set (in my test, it's Farsi)
