### ISSUE TITLE
Site Editor background color does not align with the frontend

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#30874]
## Description

WordPress applies a background color to `body` through `common.css`. This style is not reset by Gutenberg, nor is `common.css` prevented from being enqueued in the site editor.

Therefore the site editor always has a grey background.

## Step-by-step reproduction instructions

**Option 1**
1. Open the site editor with any theme that does not set a background-color.
2. See that the background is grey, instead of white.

**Option 2**
1. Open the site editor with the TT1 theme.
2. Remove the background-color set by Global Styles.
![Screen Shot 2021-04-15 at 14 03 00](https://user-images.githubusercontent.com/1221942/114866096-71652580-9df3-11eb-9f9e-580b3312a95a.png)

3. See that the background is grey, instead of white.

## Screenshots or screen recording (optional)

See `body` styles

![Screen Shot 2021-04-15 at 13 58 10](https://user-images.githubusercontent.com/1221942/114865787-0e738e80-9df3-11eb-8c21-1bf063557c09.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version:10.4
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Bug is theme independent.

**Comment by hsingyuc** [comment]
@fklein-lu  hi Fränk, I couldn't reproduce this issue but I found this PR https://github.com/WordPress/gutenberg/pull/27188 and it might have fixed the applied issue?

**Comment by fklein-lu** [comment]
@hsingyuc This is not fixed, and the PR referred above is for something unrelated.

See https://youtu.be/9CEdVyYa83w for a demo on how to reproduce.

**Comment by youknowriad** [comment]
I can't reproduce this anymore.
