### ISSUE TITLE
Customizer Widgets: Add missing ellipses Options menu in top bar

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#30886]
Opening this issue to discuss adding the ellipses menu that's available in the top bar of the post editor to the Customizer Widgets screen. This is a companion issue to #27564, which is focused on the standalone Widgets screen.

The ellipses menu contains several accessibility/usability additions to the editor experience (like the ability to access Keyboard shortcuts and the Welcome Guide) so it would be great to add some of these options, even if in a condensed format for now.

Taking a look at the existing options (left), the "Tools" section is the one that feels most high priority:

![Tool Options: Block Manager, Manage Reusable blocks, Keyboard shortcuts, Welcome Guide, Copy all content, Help](https://user-images.githubusercontent.com/77359364/114965154-08ef6600-9e3e-11eb-9b4c-d4063883e04f.jpg)

**Comment by karmatosed** [comment]
> The ellipses menu contains several accessibility/usability additions to the editor experience (like the ability to access Keyboard shortcuts and the Welcome Guide) so it would be great to add some of these options, even if in a condensed format for now.

I think keyboard shortcuts are an absolute win here but as you allude in your post it's important to maybe consider what is needed in this interface over bring everything. I'm not totally sold on all the tools as a result. What impact would only having keyboard shortcuts have? Is that a solid improvement and how much are the others needed? My thinking here is widgets are very confusing as they are and this interface is a lot, so adding less here is better.

**Comment by critterverse** [comment]
>I'm not totally sold on all the tools as a result. 

Thanks @karmatosed! I'm not convinced we need everything in the Tools section either but I think this section contains most of the features of interest for the Customizer experience. If we were going to break down the options in that section further, I would vote for trying to include the items that are directly accessibility/usability related:

1. Keyboard shortcuts
2. Welcome guide
3. Copy all content
4. Help

("Block Mananger" and "Manage Reusable blocks" seem like nice-to-haves potentially but not high priority)

Also worth mentioning that there's some discussion around the "Top toolbar" option for block toolbars (within the View section) ongoing in #30720.
