### ISSUE TITLE
`.nvmrc` file incorrect in some older WordPress branches

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#30883]
## Description

The branches `wp/5.1` - `wp/5.4` specify `lts/*` in the `.nvmrc` files.

During a commit run yesterday, I noticed this causes the build to fail in both the 5.3 and 5.4 branches and I needed to force version 10 (`nvm install 10`) for the builds to be successful.

I wasn't committing to the 5.0, 5.1 or 5.2 branches so these may also be affected. 

## Step-by-step reproduction instructions

1. Ensure you have `nvm` installed per developer documentation
2. Checkout an affected branch `git fetch; git checkout wp/5.3`
3. Observe nvm will switch to the current lts version, 12 at the time of writing
4. Ensure the branch is clean of built files (warning, this will also delete your IDE's config directory, so back it up) `git clean -f -d -X`
5. Run npm commands required to build `npm i; npm run build`
6. Observe failure.

## Expected behaviour

nvm uses correct version of node/npm and builds successfully.

## Actual behaviour

specified version of node/npm can't build in affected branches

## WordPress information
- WordPress version: N/A
- Gutenberg version: `wp/5.4` and earlier.
- Are all plugins except Gutenberg deactivated? N/A, development issue
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Desktop
- Operating system: macOS Big Sur, 11.2.3
- Browser: N/A
- Shell: zsh using oh my zsh.

**Comment by dhruvkb** [comment]
@peterwilsoncc what should be the correct Node version to be mentioned in `.nvmrc` for these branches?

**Comment by swissspidy** [comment]
Probably whatever the LTS version was at the time. Which I suppose is `10` because that's what he needed to use according to the description :-)

**Comment by gziolo** [comment]
@dhruvkb, do you plan to take care of it?

We should also check `5.5` and `5.6, which might require Node 12.

**Comment by dhruvkb** [comment]
@gziolo I can surely give it a try. The process would involve trying to build the project on the branch with the specific Node version, right?

**Comment by gziolo** [comment]
Yes, you install `nvm` locally and then you update `.nvmrc` in every branch following the instructions shared in the description.

**Comment by gziolo** [comment]
All branches updated:

- `wp/5.7` set to v14 in https://github.com/WordPress/gutenberg/commit/bc1c2608b705f479f95c4fa1ade52fd8ad30e0fe
- `wp/5.4` set to v10 in https://github.com/WordPress/gutenberg/commit/5368fbda4cd8bf2e7c21779a8c384c3e139f7825
- `wp/5.3` set to v10 in https://github.com/WordPress/gutenberg/commit/0b1cebf56f7c7499f7b51941b5473db8d7f8ea60
- `wp/5.2` set to v10 in https://github.com/WordPress/gutenberg/commit/883ff4f56c737dabf22fafb730537db30c72c098
- `wp/5.1` set to v10 in https://github.com/WordPress/gutenberg/commit/ed54b39ae2d847a6d9ae72a41530583cf9d3644e
