### ISSUE TITLE
Make block highlight/focus when clicking the pencil button or when moving to a different widget area

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30897]
## What problem does this address?
When using the block in widget customizer experiment, there are some situations where we want to focus or highlight the selected block.

- When clicking this thing in the preview area:
<img width="59" alt="Screenshot 2021-04-16 at 4 55 32 pm" src="https://user-images.githubusercontent.com/677833/115000967-d729de00-9ed5-11eb-8d17-9b4f57d5abf0.png">

- When moving a block between widget area, the destination panel should be opened and the block focused in its new location (#30896).

At the moment this doesn't work.

## What is your proposed solution?
Make it work?

This seems to mostly be a technical challenge. The customizer uses the `wp.customize.Widgets.focusWidgetFormControl( widgetId )` and `wp.customize.Widgets.highlightWidgetFormControl( widgetId )` functions. Internally, these functions expect to find a 'Control' object for the widgetId, but for blocks there are no controls. I suppose we need to create and register controls for blocks? I haven't investigated entirely what would be involved, but this issue can be used to discuss the implementation.

**Comment by noisysocks** [comment]
Marking this as a bug since it's probably why the pencil icons don't work.
