### ISSUE TITLE
Global styles: confusing as to which color is the one showing when closed menu

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#30905]
## Problem
The menu for colors when closed simply shows:

![image](https://user-images.githubusercontent.com/253067/115009721-7afa9600-9ea4-11eb-9d2e-9acab69f15ae.png)

Whilst this is great, it is very confusing when you see even in a simple theme other options:

![image](https://user-images.githubusercontent.com/253067/115009683-72a25b00-9ea4-11eb-8fc7-10a1b07008aa.png)

## Solution
I am cautious suggesting another way around this as I know that there are explorations that include iterating this interface, I did want to surface the problems though with the current implementation and how if sufacing color it needs to be clear at a glance what it relates to.

**Comment by mtias** [comment]
The new presentation of collapsed colored items with their location addresses this problem.
