### ISSUE TITLE
Global styles: Root as a term is too technical

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#30903]
## Problem
Global styles currently has the terms 'root' and 'by block type' exposed. I would like to propose that these are iterated to be a little more non-technical user friendly. You don't find many people that don't code saying root unless talking about plants or haircuts.

## Recommendation
I would suggest framing this as 'site' and 'block' probably works better for translation and also understanding, but there are a lot of options in language to explore that are more relatable.

**Comment by pablohoneyhoney** [comment]
Agreed with using more natural verbiage. There's a scenario where that term isn't visible.

https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866

**Comment by mtias** [comment]
This has been removed.
