### ISSUE TITLE
`Last Modified` date shows the scheduled date for scheduled draft posts

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#30929]
## Description

`Last Modified` date shows the scheduled date for scheduled draft posts.

## Step-by-step reproduction instructions
1. Create a new post
1. Add some text
1. Change the date in the calendar to a future date
1. And click Save Draft

## Expected behaviour

I'd expect the `Last Modified` date to be the timestamp for the last time I saved the post *or* for it to show `Scheduled` instead of `Last Modified`?

## Actual behaviour

The end result is a Draft, as I’d expect, but the post’s meta when I view all posts shows “Last Modified” as the date that I set in the calendar.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/81248/115095546-4f4ccf80-9ee7-11eb-9180-d6e0385b27e3.mp4

## WordPress information
- WordPress version: 5.8-alpha-50689
- Gutenberg version: 10.4.1 or trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 18.04
- Browser: Firefox 88.0b9 (64-bit)

**Comment by talldan** [comment]
Thanks for the bug report, though this is a WordPress core issue, and being tracked in this ticket - https://core.trac.wordpress.org/ticket/32386.

**Comment by doodirock** [comment]
Was this fixed?  We're still seeing this of the latest version of WordPress.  I want to make sure it isnt something else causing the problem.
