### ISSUE TITLE
Page Templates: Remove Site Title, Tagline and Separator and move template title to top bar.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30938]
The very first version of Page Templates have been merged into the Gutenberg plugin and will be seen in version 10.5.
https://github.com/WordPress/gutenberg/pull/30438

Testing out the newest build.

1. In the Status & visibility panel.
Clicking new (Template) opens a name modal.

2. One then enters into the Template area.

It currently looks like this:

![Screen Shot 2021-04-17 at 18 28 40](https://user-images.githubusercontent.com/5323259/115119991-5dfcba80-9fab-11eb-8069-eeac549995b2.png)

For whatever reason the Site Title, Tagline and a Separator is added to the page (content) template.

It should not be included. As the Page template should only show the in page content, and the template title in the top bar.
A page template is something that should be added to the current page it is used in.

There are two operations here:
1. Remove Site Title, Tagline and a Separator.
2. Move the Template name to the top bar, and prefix it with the word Template. 

![Page-Template-Top-bar-title](https://user-images.githubusercontent.com/5323259/115120869-0ad93680-9fb0-11eb-97a3-2956de6fd6ee.jpg)

Associated: 
Move post/page title to the top bar.
https://github.com/WordPress/gutenberg/issues/27093

**Comment by carolinan** [comment]
> ...the Page template should only show the in page content, and the template title in the top bar.
> A page template is something that should be added to the current page it is used in.

It is not a "page (content) template.", the template mode shows the website. 
The site title, tagline and separator were placed there temporarily to indicate that you can edit the header.

**Comment by paaljoachim** [comment]
Ahh.
The page template covers the full page. Header, sidebars and footer.
Great. Thanks!

I will go ahead and close this issue.
