### ISSUE TITLE
Searching in the FlatTermSelector can cause the editor to crash

### ISSUE THREAD

**Issue by lakrisgubben** [WordPress/gutenberg#30932]
## Description
A specific type of search in the FlatTermSelector component can cause the block editor to crash with the JS-error `TypeError: undefined is not an object (evaluating 'elem.ownerDocument')`. It happens if you have selected a term from the dropdown list with the keyboard after searching and then type a letter in the search box which is not the next letter in the selected term.

The issue exists in both latest WP and GB.

## Step-by-step reproduction instructions
1. Create a tag called "Test" (it can be called anything)
2. Go to the block editor.
3. Type "tes" in the tag meta box.
4. Press down on the keyboard to "select" the tag named test
5. Continue to type, but type another letter than "t" (i.e. any letter which is not the next letter in the tag name).
6. This'll cause the editor to crash with the JS-error `[Error] TypeError: undefined is not an object (evaluating 'elem.ownerDocument') getClientPosition (components.js:13432)`

## Expected behaviour

The editor should do a new term search, not crash.

## Actual behaviour

The editor crashes and is unrecoverable.

## Screenshots or screen recording (optional)
![flattermselector-crash](https://user-images.githubusercontent.com/1754954/115105559-10a72b80-9f60-11eb-83dc-c58f1d393303.gif)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Mac OS 11.2
- Browser: Tested on both Safari 14 and Chrome 90.

**Comment by talldan** [comment]
Thanks for reporting this, I tested to confirm the issue.

**Comment by Mamaduka** [comment]
It looks like the error is triggered by the `dom-scroll-into-view` package, which is used by `SuggestionsList`.
