### ISSUE TITLE
Make it easier to select "Edit visually" when in "Edit as HTML" mode

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30930]
## What problem does this address?

After selecting the Edit as HTML option for a block, you have to open the 3 dot menu to find the Edit visually option, and this option does not have a keyboard shortcut.

![The edit visually option is hidden under a menu](https://user-images.githubusercontent.com/7422055/115103617-907ac900-9f53-11eb-87d7-82bdbbbe8300.png)

## What is your proposed solution?

When in Edit as HTML mode, move the Edit visually option to the toolbar for easier and faster access.
This is not a design proposal, I just mocked it up in Photoshop quickly, but I mean something like this:

![The edit visually option is placed in the block toolbar](https://user-images.githubusercontent.com/7422055/115103753-a9d04500-9f54-11eb-868b-374ec465a16d.png)

**Comment by carolinan** [comment]
It may also be a good idea to still show the information about which block your are editing.

**Comment by carolinan** [comment]
I wonder if this needs a designer? It would be good to have some UX opinions on this.

**Comment by javierarce** [comment]
This thing bugs me a lot too and fixing this issue would make switching between modes super easy, thanks for reporting it! 

I agree with your solution, but I would put the "Edit visually" before the ellipsis button since that's the most common position.

**Comment by adambasa-dp** [comment]
@adamziel @carolinan Could you take a look at my PR, please?
