### ISSUE TITLE
elements flipping around, random nonsense interactions, and generally bad CSS

### ISSUE THREAD

**Issue by ballerburg9005** [WordPress/gutenberg#30937]
These issues are a thing that I generally have experienced with all sorts of standard themes for Wordpress and Firefox or Chrome all alike. They always pop up in some form or the other. They are by no means exclusive. What I recorded in the videos was just whatever I experienced in this particular installation in this particular moment.

Generally it is not a question of whether or not a theme could solve these issues with additional custom CSS (so to speak, a bugfixing CSS). The issue is that the editor essentially breaks at the first sight of any piece of CSS that wasn't used by the devs while testing. This is not the way to go. The theme is not to blame here. And this is by all chances not a CSS-exclusive issue (see below).

The theme I used in the videos is Twenty Nineteen from 5.6 and I upgraded to 5.7, but I don't think it matters. I did fix a few formatting issues with custom CSS, but by no means I could ever catch and foresee everything that is going wrong here. CSS is probably too limited for that as well.

https://user-images.githubusercontent.com/50874674/115116217-d1e19780-9f98-11eb-8864-163535091f81.mp4

Here I try to make text bold in the image description. But it flips back to regular and back to bold from unrelated input events, and it flips back and forth also in the wrong place, not where it was selected. It undoes the selection without corresponding user events and it also unfocuses the current block from unrelated user events. 

Stuff exactly like this doesn't just happen in this particular situation. It is a general pattern in the new Gutenberg editor, that unrelated and even random input events (such as pressing backspace twice) sometimes cause unrelated effects (such as page scrolling to bottom), which are often not even reproducible even if exactly repeated.

https://user-images.githubusercontent.com/50874674/115116222-d3ab5b00-9f98-11eb-9212-89c37aa95d8b.mp4

Here you see that the text is flipping around in all directions just by clicking on things. The paragraphs sometimes shift three lines down, sometimes they don't. Sometimes things shift left or right or up and down by a few pixels and sometimes they don't. Pair this with the fat inline editor menu bar blocking the sights, and you totally get confused where things are. You just click twice in the same place, but because of elements flipping around you click the one below and suddenly the page flips 500 pixels upwards because you clicked on an image and you used the arrow keys to mistakenly navigate forward in the text you clicked on. Why is the editor bar even inline?; I don't know a single program that does this. That is what menu bars are for. This is just generally a very poor and bugged experience that annoys the shit out of you.

https://user-images.githubusercontent.com/50874674/115116441-c773cd80-9f99-11eb-84f3-69fcce0d0562.mp4

Here I edit a list and suddenly from pressing the arrow keys or something it scrolls down to the bottom at random. Then I change the list to unordered and it moves totally outside of the paragraph's block to the left side of the document.

I hope you can see the problem and fix this poor shape that the editor is in, instead of blaming it on other components. I have given this one a serious shot, but it annoys the hell out of me and also makes me waste all my time trying to figure out some custom CSS to bugfix it.

**Comment by talldan** [comment]
@ballerburg9005 I've closed the issue—if you can't use professional and responsible language then you're not welcome.

If you'd like to act more responsibly you can fill out individual bug reports for each of the issues. Making sure to use the bug report template we have will lead to more chance of the issue being looked at.
