### ISSUE TITLE
FSE Query block: Adding additional options to the placeholder screen.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30942]
## What problem does this address?

Customizing the Query block can be fairly tricky. 
It is also difficult to know which blocks would be natural to add to the Query block.

## What is your proposed solution?

Adding additional options to the placeholder screen. Making it even easier to begin with the Query block.

![Query-block-placeholder-screen](https://user-images.githubusercontent.com/5323259/115129197-278f6180-9fe4-11eb-868d-7b8df03c8572.jpg)

What are we seeing:
Top row I have added Style Filter icons. Hover over an icon and see its tooltip name. Click to activate the icons and notice the previews will reflect which icons are clicked.

Previews are the same size but show different types of styles. (Image size should be adjustable inside the Query block Featured Image block.) Keeping the previews the same size makes it easier to visually see the different styles. Having different size styles becomes visually distracting, and takes the attention away from the styles.

Below is an empty visual square for Starting empty.

One of the things I noticed when working with the Query block was knowing which blocks were associated with it.
I added the Include blocks area (not sure about this one). So the user can decide in the placeholder screen which blocks to be included. They would not need to hunt and then guess which blocks to include later on.

Btw I turned off the "Inherit query from URL" toggle. As it is best that it begins off so that the various options are not hidden. A user can later on if needed toggle it back on.

I am hoping the above can inspire. The FSE test here: https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/ got me to really go ahead and test the Query block to see where it is at right now.

Associated merged PR: 
https://github.com/WordPress/gutenberg/pull/30763

**Comment by ntsekouras** [comment]
Hey Paal 👋 !

I think the direction for `Query` block is here: https://github.com/WordPress/gutenberg/pull/29602. Since is a quite complex block, initialization through patterns might be helpful and will be tried. Please share your thoughts there as it's very related to your issue here.

Also check this issue for future improvements: https://github.com/WordPress/gutenberg/issues/30910 and this one: https://github.com/WordPress/gutenberg/issues/30369 for `inherit` and the context detection.

**Comment by paaljoachim** [comment]
Hey Nik!

I copied the full comment over to the PR you mentioned.
Should I close this issue?

**Comment by ntsekouras** [comment]
>Should I close this issue?

I think we can keep it open for now for some discussion, probably after the landing/testing of the Query with patterns in `carousel`.

**Comment by mtias** [comment]
Going to close this so we can focus on the carousel / modal presentation.
