### ISSUE TITLE
Inserter Panel: Going between Patterns drop down and then scrolling causes bug.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30947]
## Description
Opening the Inserter Panel. Selecting Patterns. Switching to another drop down option and then back again to default drop down option. Then scrolling causes bug.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Open a page.
2. Click the Inserter icon. Select Patterns.
3. Switch from the Twenty Twenty-One option to buttons and then back again to Twenty Twenty-One option.
4. Scroll.

## Expected behaviour
That it would look correct.

## Actual behaviour

This:
![Screen Shot 2021-04-18 at 15 18 29](https://user-images.githubusercontent.com/5323259/115147020-5d226200-a059-11eb-90cb-da8f6d03be9b.png)

https://user-images.githubusercontent.com/5323259/115146992-43811a80-a059-11eb-9e08-a64bfe4e4a58.mp4

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: Not active
- Are all plugins except Gutenberg deactivated? All plugins are deactivated.
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

## Device information
- Device: Desktop
- Operating system: OSX 101.5.7
- Browser: Chrome

Initially reported here: https://core.trac.wordpress.org/ticket/52957

**Comment by jasmussen** [comment]
Despite excellent steps to reproduce and video proof, I can't actually reproduce this:

![here](https://user-images.githubusercontent.com/1204802/116216166-9e48ff00-a748-11eb-9ffb-a3b614bd5106.gif)

This is on latest trunk, but also on my personal website running the latest version of the plugin. 

Can you still reproduce it?

**Comment by paaljoachim** [comment]
Retesting with WordPress 5.7.1. Gutenberg plugin 10.5 RC. https://github.com/WordPress/gutenberg/releases/tag/v10.5.0-rc.1  Twenty Twenty One.

Following the procedure I am not able to reproduce.
I will post on the ticket asking @ramizmanked to retest using 10.5 RC.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue as we am not able to reproduce the error in Gutenberg 10.5.
The issue can always be reopened if need be.
