### ISSUE TITLE
Removing custom post type title support partially hide first block floating option's menu

### ISSUE THREAD

**Issue by amarinediary** [WordPress/gutenberg#30945]
Might be related to #30938.

## Description

Removing title support from a custom post type partially hide the first block option's menu.

## Step-by-step reproduction instructions

1. Create a custom post type.
2. Remove title support.
```php
// ...
'supports' => array( 
    'editor', 
    'comments', 
),
// ...
```
3. Create a new post.

## Expected behaviour

The first block floating option's menu should be fully visible and not outside the current window.

## Actual behaviour

The first block floating option's menu is partially outside the current window.

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/7512732/115139248-1456b300-a031-11eb-8e1c-3aa5f4190f00.png)

## WordPress information
- WordPress version: `5.7.1`
- Gutenberg version: `10.4`
- Are all plugins except Gutenberg deactivated? `Yes`
- Are you using a default theme (e.g. Twenty Twenty-One)? `No`

## Device information
- Device: `Desktop`
- Operating system: `Windows 10`
- Browser: `Version 89.0.4389.128 (Build officiel) (64 bits)`

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been reported in https://github.com/WordPress/gutenberg/issues/26239. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
