### ISSUE TITLE
Query Block: Don't add patterns when the block is unsupported

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#30965]
## Description
On a site running the Twenty Twenty-One theme, if you search for `Query` in the block-inserters, you are only shown the three Query Block patterns, but the Query block is unsupported.

This leads to both the preview, and if you insert the pattern, only showing a message saying the `core/query` block is unsupported on your site.

## Step-by-step reproduction instructions
- Click to add a new block
- Search for "query"
- No block appears, but patterns are shown

## Expected behaviour
Query block, and patterns, should not be exposed when the block for them is missing.

## Actual behaviour
Query block remains disabled, but the patterns are exposed and insertable.

## Screenshots or screen recording (optional)
![block inserter showing pattern results](https://user-images.githubusercontent.com/468735/115256096-37678c80-a12f-11eb-94bc-918cbd338e21.png)

## WordPress information
- WordPress version: 5.8-alpha-50769
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 89.0.4389.114

**Comment by Gumbino** [comment]
Thank you for documenting it. We saw the same issue and couldn't understand what was causing it.

**Comment by jordesign** [comment]
Looping back to this issue I can no longer repro it. Query looped is supported in themes back to T20 (including TT1) in my tests so there's no need to have those patterns removed - I'll close this issue.
