### ISSUE TITLE
docgen: Lacks support for TypeScript exported static variable documentation extraction

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/gutenberg#30970]
## What problem does this address?
The following is unsupported by docgen when using TypeScript but is supported when using JSDoc:

```ts
/**
 * Some important documentation about this string
 */
export const foo: string = 'a string';
```

In JSDoc TypeScript this is supported via the `@type` annotation:

```js
/**
 * Some important documentation about this string
 * 
 * @type {string}
 */
export const foo = 'a string';
```

In the TypeScript example, nothing will be extracted, just the description. In the JSDoc case, the type will be extracted as well.

## What is your proposed solution?
I think we need to update `docgen` so that when it detects a JSDoc block with zero annotations being used to describe an exported node, we need to treat that node correctly.

I believe we can detect this when a the `jsdoc.tags` is `length === 0`. In that case we just have a description of the variable. We should be able to still call `getTypeAnnotation` and generate a `type` tag:

```js
jsdoc.tags = jsdoc.tags.map( ( tag ) => {
	// ... do what we do today
} );

if ( jsdoc.tags.length === 0 ) {
    jsdoc.tags.push( {
        tag: "type",
        name: "",
        type: getTypeAnnotation( { tag: 'type' }, node, null ),
}
```

And then update `getTypeAnnotation`:

```js
function ( tag, token, index ) {
	// If the file is using JSDoc type annotations, use the JSDoc.
	if ( tag.type ) {
		return tag.type;
	}

	switch ( tag.tag ) {
		case 'param': {
			return getParamTypeAnnotation( tag, token, index );
		}
		case 'return': {
			return getReturnTypeAnnotation( token );
		}
		case 'type': {
			return getVariableTypeAnnotation( token );
		}
		default: {
			return '';
		}
	}
};
```

Where `getVariableTypeAnnotation` is something like this:

```js
function getVariableTypeAnnoation( token ) {
    const identifier = // find the identifier node through the exports and named exports wrapping node, similar to how we unwrap the function nodes.
    return getTypeAnnotation( identifiter );
}
```

I _think_ something along those lines should work.

**Comment by gziolo** [comment]
I assume it can be closed now that #30971 landed.
