### ISSUE TITLE
Changing opt-in options on the Experiments screen in the Gutenberg plugin

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#30978]
Hi all, opening this issue to discuss making some tweaks to the Experiments screen in the Gutenberg plugin. 

A couple of small changes we might consider making:

- Having options to opt-in/opt-out for each of the block-based Widget editors (opted-in by default)
- Adding “beta” tags to the experiments

![experiments-new](https://user-images.githubusercontent.com/77359364/115295617-f28c2780-a127-11eb-8fd8-535181516175.jpg)

The beta labels could also appear on menu items for both Widget editors:

![beta](https://user-images.githubusercontent.com/77359364/115304853-77c90980-a133-11eb-9df6-8ab297e7bc0d.jpg)

While it's a given that the items appearing on the Experiments screen are "beta," it feels like a nice opportunity to visually tie these experiments to their menu items by using the label in both places.

cc @javierarce who is taking a look at the Navigation experiment, which has opt-in from this screen as well.

Related: see #30922 for a blue sky idea about where this screen might head in the future :)

**Comment by noisysocks** [comment]
Love this. Let's do this as the next step towards merging the Widgets editor and Widgets Customizer panel into Core.

**Comment by draganescu** [comment]
Um, what is the use of this now? I think for Widgets this is not the best next step, instead we should try and get the opt out plugin up as the way to opt out. I also added this to the Navigation project as it's a good moment to build this there (and also for future experiments).

**Comment by noisysocks** [comment]
Yep, let's focus on building a Classic Widgets plugin instead.
