### ISSUE TITLE
Blocks in customize widgets screen: Contextual block toolbar goes offscreen

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#30988]
## Description
For blocks that have a slightly longer block toolbar, a lot of the important toolbar options end up being off-screen due to the toolbar being right-aligned.

<img width="301" alt="Screenshot 2021-04-20 at 4 26 23 pm" src="https://user-images.githubusercontent.com/677833/115363587-2d0fc600-a1f5-11eb-887b-8b2cb50dfb33.png">

I'm not sure what the desired behavior is here, I've seen side-scrolling mock-ups and mock-ups where the toolbar extends outside of its sidebar area

## Step-by-step reproduction instructions
1. Enable the blocks in customize widgets experiment
2. Edit a paragraph block

## Expected behaviour
The whole toolbar is viewable and accessible

## Actual behaviour
The toolbar is partially offscreen and can't be scrolled.

**Comment by noisysocks** [comment]
The toolbar should be left-aligned and allowed to overflow into the right hand preview area. See https://github.com/WordPress/gutenberg/issues/27343.

<img width="1054" alt="Customizer toolbar" src="https://user-images.githubusercontent.com/612155/115479825-9f7fb500-a28c-11eb-9456-8dddcb32c5b9.png">
