### ISSUE TITLE
Please re-add menu entry for converting a reusble block to a regular one

### ISSUE THREAD

**Issue by scrobbleme** [WordPress/gutenberg#30993]
After the latest update users started to complain, that they can't convert reusable blocks to regular blocks anymore...

At first we thought this was a bug...
The new icon is neither descriptive nor intuitive to use... we needed to search for this functionality. No one just clicked the icon...

→ why not just leave an explicit "written" menu entry (at the dot menu)?

If there is an icon button for converting to regular, why is there no one for converting to reusable?

**Comment by skorasaurus** [comment]
Thanks for reporting. Even as a pretty experienced Gutenberg user, I ran into this as well.

**Comment by paaljoachim** [comment]
Good idea! As I have been going over Reusable blocks again I do believe it would be helpful to add it like so:
(Added a light blue background color to emphasize the location. Edited: Added another image...:-)

![Adding-text-link-Convert-to-regular-blocks](https://user-images.githubusercontent.com/5323259/116320010-bd32aa00-a7b7-11eb-8aca-e237c4d08c11.jpg)

**Comment by scrobbleme** [comment]
@paaljoachim You should highlight the "Convert to regular blocks". Your image looks like, you want to tell something with "Copy" ;)

**Comment by paaljoachim** [comment]
Let's look at a few things. 

1-
The icon to "convert to regular blocks"

![Reusable-block-toolbar](https://user-images.githubusercontent.com/5323259/116320072-de939600-a7b7-11eb-8406-fe2c52c0311f.jpg)

should be switched out with another icon.

--

2-
Having the "Convert to regular blocks" in the 3 dot (Options) drop down should also help.

---

**Comment by paaljoachim** [comment]
A PR to add a text link to the ellipsis (3 dot) drop down has been added through this PR:
https://github.com/WordPress/gutenberg/pull/32310 It was just merged, so we can go ahead and close this issue.

Switching the current toolbar icon to a more suitable icon is something we will need to get back to at a later time.
