### ISSUE TITLE
Text formatting menu disappears on mouseover in block editor

### ISSUE THREAD

**Issue by samtuke** [WordPress/gutenberg#31009]
## Description
See video. It's impossible to use the contextual menu buttons as they constantly disappear.

## Step-by-step reproduction instructions
1. create a new post
2. create a paragraph
3. enter some text
4. highlight a word
5. try to add a link using context menu

## Expected behaviour
menu remains visible, link button clickable

## Actual behaviour
menu disappears when cursor moves, menu isn't clickable

## Screenshots or screen recording (optional)
![Peek 2021-04-20 18-07](https://user-images.githubusercontent.com/695422/115430158-6865c100-a204-11eb-9d3b-64af83072115.gif)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: ?
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Fedora 33
- Browser: Chrome 90.0.4430.72 (Official Build) (64-bit)

**Comment by ntsekouras** [comment]
Hey @samtuke 👋 - I can't reproduce this..

>Are all plugins except Gutenberg deactivated? No

Can you try with disabling the plugins and report?

**Comment by getdave** [comment]
I also tested this and cannot reproduce.

https://user-images.githubusercontent.com/444434/115894884-b02d5800-a451-11eb-8085-39dc7a33f838.mp4

**Comment by samtuke** [comment]
> Hey @samtuke 👋 - I can't reproduce this..
> 
> > Are all plugins except Gutenberg deactivated? No
> 
> Can you try with disabling the plugins and report?

Yes I disabled all plugins which would not bring down the production site but the problem remained. I will try and reproduce locally on a development server setup in order to disable 100% of plugins.

**Comment by kellychoffman** [comment]
Let's close this issue as we are unable to replicate and activity has stalled. Feel free to reopen if issue resurfaces.
