### ISSUE TITLE
Add Additional Colors from (Adobe Illustrator: System Windows)

### ISSUE THREAD

**Issue by arcmicro** [WordPress/gutenberg#31000]
## What problem does this address?
The Gutenberg Blocks lack versatility with premade colors, the custom colors are good but not useful when you create allot of posts with the same needed colors, it is a pain to made them again.

## What is your proposed solution?
I have found out that the best colors which i prefer to use are in Adobe Illustrator under (Swatches > Library > System (Windows) colors, it would be very good to add a drop down when editing post with such premade colors, I m sure many people will benefit from this, also i can tell you that many colors are copied from my website so now i tell you their name from where i add them.
It is very possible to add allot more such premade colors, there are available Macintosh ones but i not use them, and allot of others.
The users would be able to select between Default colors, System Windows and others if you decide to add more.

Hope you understand what I wrote if not let me know, cause EN is not my native. 
Thank you.

**Comment by mtias** [comment]
It is possible to register custom color palettes using the `add_theme_support( 'editor-color-palette' )` API https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#block-color-palettes

This can be added in your theme's functions.php file and they will becomes available across blocks.

Alternatively, in the future, the default color palette will be editable directly in the global styles panel using the interface (no code).

**Comment by iTesla13** [comment]
To bad that i can't tell you, that you are a dickhead moron.

On 2021-04-20 17:08, Matias Ventura wrote:

> It is possible to register custom color palettes using the add_theme_support( 'editor-color-palette' ) API https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#block-color-palettes 
> 
> This can be added in your theme's functions.php file and they will becomes available across blocks. 
> 
> Alternatively, in the future, the default color palette will be editable directly in the global styles panel using the interface (no code). 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/WordPress/gutenberg/issues/31000#issuecomment-823304278
[2]

**Comment by arcmicro** [comment]
Hello, i know about custom codes in the theme, i have used them.
The problem with this is if i change the theme, those colors are lost and everything i added is gone, no colors.
This will require editing every post again to add colors by default method, which is a pain.
Thanks.

**Comment by mtias** [comment]
You can also register a color palette with a plugin so that it's independent of the theme. (That's what global styles will also allow.)

**Comment by arcmicro** [comment]
HI, what type of plugins?
Not sure if i heard of such plugins.
Thanks.
On a side note, Where i can post different issues i face with blocks editing, there are many minor issues i find but to open here a topic fore each is too much time consuming.

**Comment by aristath** [comment]
> HI, what type of plugins?

You can create your own plugin. `add_theme_support()` doesn't necessarily need to be in a theme, you can just as easily add it in a plugin. You can read more about creating plugins in the [w.org docs](https://developer.wordpress.org/plugins/intro/)

>  On a side note, Where i can post different issues i face with blocks editing, there are many minor issues i find but to open here a topic fore each is too much time consuming.

Creating issues in this repository is the only method currently available. It is time-consuming, I agree, but it's also the only way you can be sure that someone will see the issues you creat and if something needs to be fixed it will :+1:
