### ISSUE TITLE
Widgets editor: HTML entities appear in Legacy Widget's description

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#31023]
## Description

HTML entities appear in the Legacy Widget block's description.

## Step-by-step reproduction instructions

1. Navigate to `wp-admin/widgets.php`. (The old screen.)
2. Insert an Archives widget.
3. Navigate to Appearance → Widgets. (The new screen.)
4. Select the Legacy Widget block corresponding to the Archives widget.
5. Open the block inspector.

## Expected behaviour

The widget description in the block inspector should say "A monthly archive of your site’s Posts."

## Actual behaviour

It says "A monthly archive of your site&#8217;s Posts."

## Screenshots or screen recording (optional)

<img width="285" alt="Screen Shot 2021-04-21 at 12 29 28" src="https://user-images.githubusercontent.com/612155/115488234-816e8080-a29d-11eb-8124-37df91f6d197.png">

**Comment by noisysocks** [comment]
You can see that the HTML entity is coming down in the REST API response. We should run the description through `htmlspecialchars_decode` on the server.

https://www.php.net/manual/en/function.htmlspecialchars-decode.php

```
$ http -a admin:password GET http://wp-git-build.test/wp-json/wp/v2/widget-types/archives
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages, Link
Allow: GET
Cache-Control: no-cache, must-revalidate, max-age=0
Connection: Keep-Alive
Content-Length: 325
Content-Type: application/json; charset=UTF-8
Date: Wed, 21 Apr 2021 02:32:17 GMT
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Keep-Alive: timeout=5, max=100
Link: <http://wp-git-build.test/wp-json/>; rel="https://api.w.org/"
Server: Apache/2.4.46 (Unix) PHP/8.0.3
X-Content-Type-Options: nosniff
X-Powered-By: PHP/8.0.3
X-Robots-Tag: noindex

{
    "_links": {
        "collection": [
            {
                "href": "http://wp-git-build.test/wp-json/wp/v2/widget-types"
            }
        ],
        "self": [
            {
                "href": "http://wp-git-build.test/wp-json/wp/v2/widget-types/archives"
            }
        ]
    },
    "classname": "widget_archive",
    "description": "A monthly archive of your site&#8217;s Posts.",
    "id": "archives",
    "is_multi": true,
    "name": "Archives"
}
```

**Comment by JustinyAhin** [comment]
Hello @noisysocks, I want to tackle this one. Just to be sure, this should be fixed in Core right?

Also, looks like it is the [html_entity_decode](https://www.php.net/manual/fr/function.html-entity-decode.php) that should be used instead.

**Comment by noisysocks** [comment]
Hi @JustinyAhin, thanks for volunteering!

Right now the code for this REST API endpoint is in the Gutenberg plugin so you'll need to open a PR in this repo.

https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-rest-widget-types-controller.php

**Comment by talldan** [comment]
@JustinyAhin Just following up, do you still plan to work on this?

I think the endpoints will soon be ported to WordPress core, so where this is fixed may change.

**Comment by ramonjd** [comment]
I created (what I think is) a fix over here: https://github.com/WordPress/gutenberg/pull/32503

Wasn't sure whether it's still fixable in Gutenberg given that the [plans were to move it to core](https://github.com/WordPress/gutenberg/issues/31023#issuecomment-845640716).

Also I don't want to muscle in on any work @JustinyAhin has already done. I couldn't find a linked PR however.

Happy to close my PR in any case. Thanks!

**Comment by noisysocks** [comment]
> Wasn't sure whether it's still fixable in Gutenberg given that the [plans were to move it to core](https://github.com/WordPress/gutenberg/issues/31023#issuecomment-845640716).

Yes you'll need to fix this in Core. Please open up a ticket and submit a patch! We can still merge https://github.com/WordPress/gutenberg/pull/32503 however as it fixes the issue in the plugin for sites running WP 5.7.

**Comment by ramonjd** [comment]
~Looks like there was already a [core patch proposed.](https://core.trac.wordpress.org/ticket/53138)~ That was reverted I believe.

I have [thrown mine up](https://core.trac.wordpress.org/ticket/53407) as well just in case, since I've taken a different approach.
