### ISSUE TITLE
List block: Provide option to change the bullet point

### ISSUE THREAD

**Issue by retnonindya** [WordPress/gutenberg#31024]
## What problem does this address?
More like an enhancement on the [List block](https://wordpress.com/support/wordpress-editor/blocks/list-block/), I guess? Just throwing ideas here 😅 

I wonder if we can have some kind of option to change the bullet point to other symbols -- most notably, checkmark. Currently, the List block use bullet point-look (or numbers, on ordered list.) 

This might be useful for folks who want to display their features/services to their potential market/customers/clients. Something like this:

> ✔️  Competitive pricing
> ✔️  After-sales services
> ✔️  24/7 Support
> ✔️  Highly skilled field team

As of now, the only workaround I can found is to use Paragraph block and use the checkmark symbol or the emoji. Design-wise, miiight be not super awesome (compared to the neat alignment that list usually has.) 

We can also use CSS, but this is not ideal for WordPress.com users without Premium plan subscription and above (CSS support only available on Premium plan and above.)

---

Please let me know if this is not the correct repo and I can move it to other area. Thank you!

**Comment by paaljoachim** [comment]
Hey @retnonindya Retno

There are actually a few issues related to this. Here is one of these:
https://github.com/WordPress/gutenberg/issues/17738

No one has worked on it yet.

I will mark your issue as a duplicate.

**Comment by retnonindya** [comment]
Oh, thank you, @paaljoachim! Yep, I can close this issue too. Thanks again!
