### ISSUE TITLE
Site Editor / iframe: unwanted scroll when block settings panel overflows

### ISSUE THREAD

**Issue by hawkmusician** [WordPress/gutenberg#31034]
## Description
When using the site editor, if the blocks setting panel overflows vertically, when the user scrolls to access different settings in that overflow, the iframe scrolls at the same time. This makes it nearly impossible to edit in FSE since one has to adjust all the time the iframes vertical position.

## Step-by-step reproduction instructions

- Use a block theme, such as TT1 Blocks
- Insert a block that has an overflowing settings panel (or resize your window with inspector). For example, the navigation block.
- Put your mouse on a tab panel title (like "Color Settings), or expand all tabs so that a scrollbar appears in the sidebar. 
- Scroll

## Expected behaviour
The iframe content should not scroll when the user is using the settings panel.

## Actual behaviour
If the user scrolls inside the block settings panel, the iframe content will scroll at the same time.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/23136551/115534879-867d0100-a298-11eb-994b-127c1f7b1871.mp4

**Comment by ellatrix** [comment]
This was fixed by #31395.
