### ISSUE TITLE
Safari: "Sticky" inserters appear all over the site editor canvas sometimes

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#31046]
I've been seeing this one regularly, but only in Safari:

When loading the site editor and moving the mouse around, I'll get a pile-up of inserters. Sometimes they go away after a while, but sometimes they stick around until I refresh. It's not clear that they're lining up with space where an inserter should actually even be appearing: 

![inserters](https://user-images.githubusercontent.com/1202812/115570598-3f890e80-a28c-11eb-8982-efde5892a2fc.gif)

Tested with WordPress 5.7.1, Gutenberg 10.4.1

**Comment by annezazu** [comment]
This was also reported in the [sixth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/):

> You can also see yet-another-example of the in-between inserter getting in the way; That blue [+] and line? That’s the “in-between inserter” and its always trying way too hard.

![selecting-multiple-blocks](https://user-images.githubusercontent.com/26996883/119078596-be6c8680-b9b3-11eb-9315-22830b706c7c.gif)

**Comment by Thelmachido** [comment]
I don't think this is an issue anymore, I tested on Safari with TT2 enabled. 

The inserter behaves as expected when I move around the cursor in Site Editor. You can see this in the video below: 

https://user-images.githubusercontent.com/41231764/184350129-5ff437cf-2b4e-463e-b6d5-cb2917152b2b.mov

WordPress 6.0.1
Gutenberg 13.8.1 

I will close this, for now.
