### ISSUE TITLE
Column width control labels are not translated in the Column block edit bottom sheet 

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#31051]
## Description
The input label for each column within the Column block are not translated and always read `Column <index>` in English. 

## Step-by-step reproduction instructions
1. Use a device with language other than English. 
1. Launch the block editor on WPiOS or WPAndroid.
1. Add a Column block.
1. Open the block Settings bottom sheet (i.e. tap gear icon).
1. Select a column layout.

## Expected behaviour
The column width input labels are translated to the current device language. 

## Actual behaviour
The column width input labels are in English. 

## Screenshots or screen recording (optional)
![img_9658](https://user-images.githubusercontent.com/438664/115581830-fc2f9f80-a28d-11eb-8d75-46c21b490974.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: v10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone SE
- Operating system: iOS 14.4.2
- WordPress app version: 17.1

**Comment by mchowning** [comment]
Marking this as a high priority issue for the time being because it may be an issue that affects more than just these column strings. If this issue only involves these strings, then it could probably be reclassified as low priority.

**Comment by fluiddot** [comment]
Most of the strings on the columns block are now translated but we still have the `Column X` string untranslated.

<img src=https://user-images.githubusercontent.com/14905380/125108120-e2aa3100-e0e1-11eb-9c0e-098fa1695b15.png width=320>
