### ISSUE TITLE
Page List: Add parent parameter to show all child pages of current page

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#31063]
## What problem does this address?

The goal is to allow a page to create a menu/list of posts of all the children page, sorted by menu_order.

The solution in PHP could something like this:

```php
$args = array(
    'post_type'      => 'page',
    'posts_per_page' => -1,
    'post_parent'    => $parent_id,
    'orderby'        => 'menu_order',
    'order'          => 'ASC',
 );

$child_pages = new WP_Query( $args );
```

An issue with pages is there is no means to add additional tag or category information as another means of limiting what is returned by the query. 

Possible this should just be added to: https://github.com/WordPress/gutenberg/issues/24934

**Comment by mkaz** [comment]
For my case of trying to show a listing of all child pages, this might be a better for the Page List

**Comment by talldan** [comment]
I've closed #33883 as a duplicate. That suggests being able to specify the parent page for filtering the results as well as the option to use the current page. The two requests are so similar that I think it would make sense to combine them in this issue.

**Comment by AddoSolutions** [comment]
+1 for this – would be very helpful and solve several other issues.  Are there any workaround for this as of yet?

**Comment by scruffian** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/45861!
