### ISSUE TITLE
Group Block HTML Element Selector Removes Inner Container When Not Div

### ISSUE THREAD

**Issue by eric-michel** [WordPress/gutenberg#31061]
## Description
The standard Group Block includes the primary container with class `wp-block-group`, and an inner container with the class `wp-block-group__inner-container`. All `InnerBlocks` are contained within `wp-block-group__inner-container`.

When using the new HTML Element select drop-down, any options that aren't `Default <div>` do not have the inner container. They simply display all `InnerBlocks` directly within the main `wp-block-group` container. This will likely cause problems with CSS selectors in many themes.

## Step-by-step reproduction instructions
1. Add a Group Block to a test page
2. Use the `HTML element` drop-down under `Advanced` to choose any element option that is not `Default <div>`
3. Save and view source on the frontend

## Expected behaviour
Maybe this is intended(?) but I would assume these elements are for semantic purposes only, and the inner container should be preserved no matter the tag.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Twenty Twenty-One)

**Comment by fsimmons** [comment]
is .wp-block-group__inner-container dead??

**Comment by AlecRust** [comment]
Is this workaround really what's necessary to bring back this inner container my layout relies on?

https://epiph.yt/blog/2021/wordpress-5-8-wp-block-group__inner-container-wieder-hinzufuegen/

**Comment by chthonic-ds** [comment]
> Maybe this is intended(?) but I would assume these elements are for semantic purposes only, and the inner container should be preserved no matter the tag.

My understanding is `div.wp-block-group__inner-container` was intentionally removed some time ago, though there's a check that restores it if there's no theme.json file. In core, the function that handles this is in wp-includes/block-supports/layout.php: `wp_restore_group_inner_container()`.

Looking at the regex in that function, it assumes `div.wp-block-group` will be the parent. If you have a different element set for the parent (e.g. `article`), it appears the inner container won't be restored.

**Comment by eric-michel** [comment]
@chthonic-ds based on my testing, I think you're exactly right. I'm going to close this issue since it seems `inner-container` is going away.
