### ISSUE TITLE
It should be possible to delete new custom block  templates, and revert customised block templates in the template editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31076]
In the post editor it is now possible to:

* Create a new custom block template on the fly
* If a block template is used, edit it visually in the template editor

<img width="306" alt="Screenshot 2021-04-22 at 10 13 29" src="https://user-images.githubusercontent.com/846565/115689184-c2c16780-a353-11eb-8ca2-6effc0299a9c.png">

In the case of user-generated block templates, the UI should provide a way for users to delete that template.

In the case of customised block theme templates it should be possible to revert those customisations and re-instate the theme default.

The Site Editor already offers a way to revert customised block theme templates:

<img width="1726" alt="Screenshot 2021-04-22 at 10 18 34" src="https://user-images.githubusercontent.com/846565/115689579-1fbd1d80-a354-11eb-97be-150197e683e4.png">

This is something we can consider bringing to the template editor (albeit without the "Browse all templates" button for now). The same design can be utilised for deletion. Here's a rough mockup:

<img width="390" alt="Screenshot 2021-04-22 at 10 27 20" src="https://user-images.githubusercontent.com/846565/115690852-5e070c80-a355-11eb-92a7-2a39944a0f79.png">

Since this would be a destructive action, we might want to expose a confirmation dialog that briefly explains the consequences of this action, something like:

> Delete "My Custom Template"?
> All posts that use this template will be affected.
> [Cancel] [Delete]

It we could provide a count of how many posts would be affected, that would be even better :) 

- [ ] Provide a way to revert customised theme-supplied block templates in the template edior
- [ ] Provide a way to delete custom block templates in the template editor

**Comment by karmatosed** [comment]
I think the line seperates the action from it's connection a bit too much perhaps:

![image](https://user-images.githubusercontent.com/253067/115694277-9d832800-a358-11eb-86a4-db0055582330.png)

I really like the idea of at least the first time someone does this adding in a confirmation, but perhaps only the first time otherwise it could get a little much.

**Comment by jameskoster** [comment]
Yeah without the template description (and other actions) the separator does seem a little heavy-handed. I included it because I believe it is already built in to the popover style in the site editor. It should be easy to remove though.

Another option would be to add some template  meta data in lieu of a description. I'm not sure how useful that would be?

<img width="411" alt="Screenshot 2021-04-22 at 12 17 03" src="https://user-images.githubusercontent.com/846565/115705633-b1348b80-a364-11eb-8bff-f84c82c22f08.png">


> I really like the idea of at least the first time someone does this adding in a confirmation, but perhaps only the first time otherwise it could get a little much.

We could certainly add a "Don't ask me again" checkbox.

**Comment by paaljoachim** [comment]
Here is a variation (Ratio is off).

![Screen Shot 2021-04-23 at 16 32 54](https://user-images.githubusercontent.com/5323259/115886940-b6233900-a451-11eb-9d84-f571d74edea3.png)

https://github.com/WordPress/gutenberg/issues/31147

**Comment by kellychoffman** [comment]
I like adding the meta info in there, as it acts like a pre-emptive "are you sure?". It could be a bit more compact. My only thought is the nearly empty Template tab in sidebar. That is the location where you delete/trash a post. It might make more sense to stick it there.

**Comment by jameskoster** [comment]
> My only thought is the nearly empty Template tab in sidebar. That is the location where you delete/trash a post. It might make more sense to stick it there.

I acknowledge this is a bit "in the clouds", but if we move more document attributes to the top bar then maybe we don't actually need the "Template" tab at all?

https://user-images.githubusercontent.com/846565/117319700-76ae1100-ae83-11eb-8fac-e0e5732ca827.mp4

**Comment by youknowriad** [comment]
We have this in place now. Should we close this issue or keep it for potential improvements?

**Comment by jameskoster** [comment]
We can close once https://github.com/WordPress/gutenberg/pull/32042 is merged.
