### ISSUE TITLE
Site Editor: CSS-in-JS regression in v10.5.0 RC 1 for components in the sidebar

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#31070]
## Description

In Gutenberg 10.5.0 RC 1 there appears to be a regression in the CSS-in-JS styles within the sidebar of the site editor. Components using Emotion for CSS-in-JS don't appear to be applying their styles (thought they do in the regular post editor). The recent changes in https://github.com/WordPress/gutenberg/pull/31010 supports rendering these styles within the editor canvas, however the sidebar exists outside of the site editor iframe, so I was wondering if there's an issue where the CSS is only being rendered in the iframe and not the parent document? (I believe it'll need to be rendered in both places).

Possibly related to: https://github.com/WordPress/gutenberg/pull/31010 or https://github.com/WordPress/gutenberg/pull/31048

CC: @sarayourfriend @youknowriad

## Step-by-step reproduction instructions

1. Using the FSE-capable TT1-blocks theme, go to the site editor
2. Insert a block that uses components relying on CSS-in-JS into a template part (e.g. the Blog Posts block uses a range control that demonstrates the issue)
3. Look at the sidebar and see if the components are rendering as expected (screenshots below)
4. Compare with adding the some block in the regular post editor

## Expected behaviour

This is how it looks prior to 10.5.0 RC 1

![image](https://user-images.githubusercontent.com/14988353/115671647-13ee4d00-a38e-11eb-9dbf-7aad27b4309c.png)

## Actual behaviour

This is how it looks running 10.5.0 RC 1

![image](https://user-images.githubusercontent.com/14988353/115671619-0df86c00-a38e-11eb-8fca-d0478249b1bc.png)

## WordPress information
- Gutenberg version: GB 10.5.0 RC 1, testing in a wpcom environment
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-blocks

## Device information
- Device: Desktop
- Operating system: MacOS 11.2.3
- Browser: Chrome 90

**Comment by andrewserong** [comment]
Thanks for fixing this up, Riad! 🙇

**Comment by youknowriad** [comment]
👍 Let me know if you find anything weird, this is a tricky one.
