### ISSUE TITLE
Framework: Update dependencies to match the latest version of React

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3107]
## Issue Overview

Raised by both @youknowriad and @aduth when upgrading React's version.

Reposting the comment from @aduth (https://github.com/WordPress/gutenberg/pull/3079#issuecomment-338214643):

> Noting that many of our dependencies define a React peer in the 15.x line, so warnings are logged when installing a new version of a package:
> 
> ```
> npm WARN react-autosize-textarea@0.4.8 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-autosize-textarea@0.4.8 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-datepicker@0.46.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-datepicker@0.46.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-slot-fill@1.0.1 requires a peer of react@^15.5.8 but none is installed. You must install peer dependencies yourself.
> npm WARN react-transition-group@1.2.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-transition-group@1.2.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
> ```
> 
> I imagine at least some of these should have updated versions available which define React 16 as a valid peer.

I noticed also another package `babel-loader` which expects an older version of Webpack.

I did some research already and here are my findings:
* there are breaking changes introduced for `react-transition-group`. See [Migration Guide from v1 to v2](https://github.com/reactjs/react-transition-group/blob/master/Migration.md).
* `react-datepicker` has peer dependency updated in the master branch, but they haven't been published as a new version yet. I'm anticipating to see them soon in the upcoming `0.57.0` version. 

## Expected Behavior

No warnings from `npm install`.

## Current Behavior

```
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@0.4.8 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@0.4.8 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.46.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.46.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slot-fill@1.0.1 requires a peer of react@^15.5.8 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@1.2.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@1.2.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by aduth** [comment]
>I noticed also another package `babel-loader` which expects an older version of Webpack.

This is not as much related to the React version bump as it was a Webpack version bump a few weeks back in #2841 (specifically https://github.com/WordPress/gutenberg/pull/2841#issuecomment-333878096).

**Comment by mtias** [comment]
@gziolo are you still looking at this?

**Comment by gziolo** [comment]
`react-transition-group` is tricky to update because they changed public API, but I can tackle it this week.
