### ISSUE TITLE
Page template: Adjust snackbar notification text.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31087]
After having created a template one is moved into the Template editing mode.

![Page-Template-mode](https://user-images.githubusercontent.com/5323259/115896329-97c23b00-a45b-11eb-8deb-1c2add624684.jpg)

A few things.
1- Top bar: Should have the template name title. New issue here: https://github.com/WordPress/gutenberg/issues/31147
2- Adjust the snack bar text.

Adjustments:

3- Snack bar notification to go from "Custom template created. You're in template mode now." -> 
**"Template created. You are in template mode."**

**Comment by jameskoster** [comment]
> 1- Add Template name to the top bar.

We already have this in the Site Editor, it may be worth opening a dedicated issue to transplant it across to the template editor?

> 2- Adjust the sidebar movie template name.

I think when you switch to template editing, the document tab (Post or Page) should be replaced with the template details. This is how it works currently on trunk so I wonder if you're running the latest version? A snackbar already appears as you switch too:

https://user-images.githubusercontent.com/846565/115747993-ab9f6b80-a38d-11eb-8553-5fa981d95e1f.mp4

**Comment by paaljoachim** [comment]
I should open an issue for adding the template name to the top bar as you mention. When entering the template mode the name is not seen in the top bar, but when saving the template name is suddenly seen there.

Thanks for sharing what is now in trunk! I am not running the RC version of Gutenberg, so it looks like I missed out on a few things.

**Comment by paaljoachim** [comment]
I edited the original comment. I am focusing this issue only on the snackbar notification.

I have also added a new issue for Page template: Add template name to top bar
https://github.com/WordPress/gutenberg/issues/31147

**Comment by annezazu** [comment]
@paaljoachim what are you suggesting here? I fear I'm misunderstanding! As Jay pointed out, this is already in place and I haven't seen any feedback from the outreach program that this is a confusing experience currently or that the language needs more clarity :D

**Comment by paaljoachim** [comment]
Heya @annezazu 

I am closing out this issue. No need to to anything here at the moment.
Thanks for noticing!
