### ISSUE TITLE
Admin editor page blank when custom post type named "sidebars"

### ISSUE THREAD

**Issue by Big-wolf** [WordPress/gutenberg#31080]
## Description
I have created new custom post type named 'sidebars'. When trying to edit or create new item  i've got 404 error in console.

## Step-by-step reproduction instructions
1. Create custom post type in functions.php your current theme:

```
function test_post_type_init() {
	
		register_post_type('sidebars', 
			array(
				'labels' => array(
					'name' => __('Sidebars'),
					'singular_name' => __('Sidebar')
				),
				'public' => true,
				'exclude_from_search' => true,
				'show_in_nav_menus' => false,
				'show_in_rest' => true,
				'hierarchical' => false, 
				'has_archive' => false,
				'menu_position' => 5,
				'supports' => array(
					'title',
					'editor',
					'revisions'
				), 
				'can_export' => true,
				'menu_icon' => 'dashicons-welcome-widgets-menus',
	
			));
		}
				
add_action( 'init', 'test_post_type_init' );
```

2. Activate Gutenberg plugin
## Expected behaviour
Regular gutenberg block editor page 

## Actual behaviour
White page - console 404 error with requested url: .../wp-json/wp/v2/sidebars/17?context=edit&_locale=user

Failed to load resource: the server responded with a status of 404

![image](https://user-images.githubusercontent.com/33028315/115703717-c01e3c80-a36a-11eb-88f5-d0a87eb1a959.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 90.0.4430.85

**Comment by skorasaurus** [comment]
Hi (nice avatar of the dog!)

Thanks for reporting; I'm able to reproduce this in Gutenberg 10.5.4. 

The specific error message that I obtain is: 
```
XHRGEThttps://plain.test/wp-json/wp/v2/sidebars/56?context=edit&_locale=user
[HTTP/2 404 Not Found 487ms]

	
code	"rest_sidebar_not_found"
message	"No sidebar exists with that id."
data	Object { status: 404 }
status	404
```
It looks like 'sidebars' is a term used by the REST API now and probably should not be used by custom post types. 

This led me to https://github.com/WordPress/gutenberg/blame/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/lib/class-wp-rest-sidebars-controller.php#L46  and https://core.trac.wordpress.org/ticket/51460

This maybe more of a Core WordPress issue than one exclusive to Gutenberg? 
cc @noisysocks @adamziel  @TimothyBJacobs 

Nonetheless, it probably should be documented on the [register_post_type ](https://developer.wordpress.org/reference/functions/register_post_type/) page what names are reserved in WordPress.

**Comment by TimothyBJacobs** [comment]
Yep that's exactly right @skorasaurus. Also from the `register_post_type` page:

> In general, you should always prefix your post types, or specify a custom `query_var`, to avoid conflicting with existing WordPress query variables.

If you can't change your CPT slug, you can set a custom `rest_base` when registering your CPT.
