### ISSUE TITLE
Site Editor: When editing a template part is NOT editing a template part

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#31098]
Not sure whether to describe this as a bug, a feature request, or just a general discussion.

The issue is when editing a _template_ and making changes to a _template part_ (e.g. header), or what I think the average user may assume is they are making changes to a template part, the changes are not actually applied to the template part. The changes are actually applied to the template containing said template part.

For example, when the Site Editor first loads, the user is generally presented with the _page template_.
The user then edits the header template part (change background color, add padding etc.), and would naturally assume they have made the changes to the header site-wide.
In fact the changes are only applied to the template part wrapper in the page template, and not the header template part.

To make changes site-wide to the header, the user has to navigate away from the template, and through 'Theme' > 'Template Parts' > 'Headers' > 'header' to select the header template part.
The issue here is that the template part wrapper is not editable, only the blocks within.

My opinion is that a non-dev user would find this confusing.

Hope I have managed to explain what I mean. If not please ask and I'll attempt to explain my thinking further.

**Comment by carolinan** [comment]
I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/30732

**Comment by Sandstromer** [comment]
Oops! My quick scan was too quick. I'll close this in favor of #30732
