### ISSUE TITLE
Page template: Show template parts

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31090]
Entering the Template mode one will see the Site title and the tagline.
It would be helpful to add the Header, Content, Footer and other sidebars into template part blocks.

Going from (mockup from: https://github.com/WordPress/gutenberg/issues/31087 )
![Entering-page-template](https://user-images.githubusercontent.com/5323259/115721800-ab4ba400-a37e-11eb-803c-8bdccda241b9.jpg)

To:

https://user-images.githubusercontent.com/5323259/115720774-a9cdac00-a37d-11eb-83a9-42518ea9af03.mp4

**Comment by jameskoster** [comment]
I can't find the PR now, but I recall suggesting that we spawn new Header and Footer template parts in this flow if they do not already exist.

@youknowriad had some good feedback as to why that was not a good idea, but since I can't find the PR, I can't remember what his points were 😅

**Comment by youknowriad** [comment]
My main point is that we might want to ship the template mode before actually shipping template parts in Core. That said, it's still a good idea to rely on the semantic "header" and "footer" template parts if they exist for a theme instead of creating random ones. So it would be a good follow-up to do at some point.

**Comment by paaljoachim** [comment]
Ahhh....
Ship the template mode first.
Then later add template parts.

So the first version we are focusing on being able to edit the full page - header, content and footer etc are mixed into one. I do wonder if there should be included some nuance between the various areas..... or maybe not...

**Comment by jameskoster** [comment]
> My main point is that we might want to ship the template mode before actually shipping template parts in Core.

But if a block theme is active, you'll get access to template part editing as soon as you engage the template editor. I'm not sure I quite understand the concept of shipping template mode without template parts 🤔 

> That said, it's still a good idea to rely on the semantic "header" and "footer" template parts if they exist for a theme instead of creating random ones. So it would be a good follow-up to do at some point.

Agreed, we should check if the parts exist in this flow, and include them if they do.

**Comment by youknowriad** [comment]
> But if a block theme is active, you'll get access to template part editing as soon as you engage the template editor. I'm not sure I quite understand the concept of shipping template mode without template parts

Block themes are not being shipped in 5.8. Template mode for classic themes is considered.

**Comment by carolinan** [comment]
Please clarify this. It won't be possible to **activate** a theme like TT1 Blocks without Gutenberg in 5.8?

**Comment by carolinan** [comment]
Please understand that this type of information is **crucial** and **greatly** affects how contributors choose to spend their time.
For example, how the WordPress.org themes team, and the meta team to some extent, allocates volunteer time to make sure that block themes can be uploaded to the theme directory.

**Comment by youknowriad** [comment]
> Please clarify this. It won't be possible to activate a theme like TT1 Blocks without Gutenberg in 5.8?

Yes, that's my understanding, I see no mention of block themes in https://make.wordpress.org/core/2021/04/20/full-site-editing-go-no-go-next-steps/ (I  mean anything aside theme.json)

**Comment by paaljoachim** [comment]
Should I go ahead and close this issue?
I am circling back into some of my older issues trying to figure out if I should close them or leave them open and ask for somekind of status update.

**Comment by jameskoster** [comment]
Thanks @paaljoachim. I'm trying to remember when this occurs, is it when you have a non-block theme active and engage the template editor in the post editor?

Instead of just displaying the site title / tagline, it might now make sense to insert an empty Header template part. That would expose the 'Choose' UI where folks can select a header from contextual patterns:

<img width="1295" alt="Screenshot 2023-04-04 at 10 00 06" src="https://user-images.githubusercontent.com/846565/229742196-02c5860c-c29e-4c38-830c-e4ee1158fb83.png">

**Comment by paaljoachim** [comment]
Hey James @jameskoster 

I have a feeling what I am talking about is different compared to what was discussed in this issue...

Retesting.
Using Twenty Twenty Three.
WordPress 6.2
Gutenberg plugin 15.4

### The Site Editor
The current page template shows a header, Post Featured Image, Post Title, Post Content, Comments and a Footer.

Entering a template it would be easier to have 3 main template parts as the header, content (Post Featured Image, Post Title, Post Content, Comments) and the footer. It would give a clarity to how the template is put together. How it is made by the 3 template parts.

Header
Content
Footer

### In Page template
Editing the current Page template inside a page.
The difficult part here is that it looks different from editing a template in the site editor. It should have a smooth transition between in page template editing and the Site Editor editing template experience. 

The in page template editing also has the template split up into many parts. It would be helpful to have the main template parts be Header, Content and Footer.

**Comment by jameskoster** [comment]
I'm not 100% certain, but what you're describing sounds similar to what's being explored in https://github.com/WordPress/gutenberg/pull/49292. 

It feels like we're approaching a point where the post and site editors will converge, which would be preferable, rather than attempting to keep two separate editors 'in sync'.

**Comment by paaljoachim** [comment]
Yeah it is fairly similar to the issue you mentioned.
Should I close this issue?

**Comment by jameskoster** [comment]
Up to you 👍

**Comment by paaljoachim** [comment]
We can always circle back to this if needed again at a later time.
