### ISSUE TITLE
Add Block: Quote

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#311]
## Attributes

- Alignment: None, Left, Right, Center, Full Bleed.
- Alternative style of quote.
- Cite (fixed field).

## Markup

```html
<!-- wp:quote -->
<blockquote>
    <p>The quick brown fox jumps over the lazy dog.</p>
    <cite>Author</cite>
</blockquote>
<!-- /wp -->
```

## States ([see all](https://wpcoredesign.mystagingwebsite.com/gutenberg/#quote))

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Quote,%20Citation.png)

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Quote%202,%20Selected.png)

**Comment by BE-Webdesign** [comment]
Going to try to do a PR for this.

**Comment by iseulde** [comment]
Can blockquotes have things like headings and lists? If so, how can they be added and changed?

**Comment by joyously** [comment]
> Can blockquotes have things like headings and lists?

Yes, HTML is fairly liberal about nesting. Since a blockquote is an extended quotation, it can have lots of different HTML elements that are [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content).

And did you know that there is a `cite` attribute for the [blockquote element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)? It is distinct from a separate `cite` element.

**Comment by iseulde** [comment]
@joyously I know it's possible in HTML and the current editor. Asking about this particular block. I think that some blocks might need to act as "container blocks". Blockquote is a good example, and there are plenty of sites that have stuff like an aside/explainer.

**Comment by joyously** [comment]
I was talking about this particular block also. It's similar to what I commented on the Text block: "do you parse it as they edit and make it into other blocks or let them put whatever they want?".
As stated, the markup for this _block_ can contain other HTML elements. But the `<p>` tags cannot. I think those should be removed.

**Comment by mtias** [comment]
In my research, markup for quotes is not trivial. Some use `<footer>` instead of cite, for instance.

Also keep in mind the second style of block is similar to the purpose of the quote post-format. Interestingly, shortcake shows a very [similar example](https://i0.wp.com/plugins.svn.wordpress.org/!svn/bc/1615947/shortcode-ui/trunk/screenshot-2.png?strip=all&ssl=1) where the need for a [separate source attribute](https://i2.wp.com/plugins.svn.wordpress.org/!svn/bc/1615947/shortcode-ui/trunk/screenshot-3.png?strip=all&ssl=1) is clearer.

**Comment by youknowriad** [comment]
Closing this. All quote features are there I think. And we can open specific issues anyway.
