### ISSUE TITLE
Fix error notice appearing underneath the modal screen overlay on the Navigation editor screen

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#31100]
If you create a menu using the name of an already existing one, an error notice appears under the modal screen overlay, making it difficult to see and impossible to close independently.

The error notice also appears partially covered by the left sidebar.

## Step-by-step reproduction instructions

1. Create a menu with the name you want
2. Create another one with the same name

## Screenshots or screen recording (optional)

![Screenshot 2021-04-22 at 17 53 27](https://user-images.githubusercontent.com/4933/115745765-0936b680-a394-11eb-83a3-834075e1c80e.png)

![Screenshot 2021-04-22 at 17 53 54](https://user-images.githubusercontent.com/4933/115745760-08058980-a394-11eb-938f-4ba7ea3d6148.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Browser: Chrome, Firefox & Safari

**Comment by javierarce** [comment]
A good fix for this issue could be to integrate the error message inside the "Create a new menu" modal screen.

**Comment by javierarce** [comment]
Also important to fix: in the mobile version is impossible to see the error message, because it's behind the modal. 

![Screenshot 2021-04-26 at 11 15 30](https://user-images.githubusercontent.com/4933/116059027-b9e8d280-a680-11eb-8e14-39c7ed3ffb7f.png)

**Comment by JustinyAhin** [comment]
Something we can start doing about this could be to move the notice `div` above the modal screen by increasing its `z-index`

**Comment by JustinyAhin** [comment]
> Something we can start doing about this could be to move the notice `div` above the modal screen by increasing its `z-index`

Not really sure about this any more. This will likely close the form to add menu on click on the notice.

@aristath , when you're back, I'll be happy to tackle this with your help

**Comment by Mamaduka** [comment]
@javierarce, do you have mockups for the error inside the modal? Or should I use existing error notice styles?

**Comment by javierarce** [comment]
I'm trying to see how we have solved this problem in other places, but I haven't found anything. 

My initial idea was to use the existing error notice and show it above the modal (which would also fix the problem we have in Desktop mode)… would that be possible?

**Comment by Mamaduka** [comment]
The only component I can remember is the `MediaPlaceholder` that displays errors locally.

![media-placeholder-error](https://user-images.githubusercontent.com/240569/133579921-b795692a-d072-440c-aeaf-9590322a7894.png)

> My initial idea was to use the existing error notice and show it above the modal.

It can be problematic because of the stacking context. Currently, even Snackbar is covered by modals overlay.

**Comment by javierarce** [comment]
> It can be problematic because of the stacking context. Currently, even Snackbar is covered by modals overlay.

Ok, the solution you mentioned works for me. We could have something like this:

![image](https://user-images.githubusercontent.com/4933/133584800-0e3e66e1-2fa7-40d3-8557-e40ef9123aff.png)

[Figma file](https://www.figma.com/file/xvnD8SOGhQYvnHJLGXYWGJ/?node-id=1173%3A13251)
