### ISSUE TITLE
Page template: Automatically refresh page to add template drop down when there are multiple page templates available.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31101]
Template now has it's own panel outside the Page Attributes panel.

![Screen Shot 2021-04-23 at 16 42 39](https://user-images.githubusercontent.com/5323259/115888437-372f0000-a453-11eb-8614-9032f024b67a.png)

But when creating multiple page templates. I see no drop down to select which page template I would like to use.
The old Template section under Page Attributes had a drop down to select from various page templates. This new method does not yet have a drop down even when multiple page templates has been created.

![Screen Shot 2021-04-23 at 16 47 02](https://user-images.githubusercontent.com/5323259/115888733-8d03a800-a453-11eb-81c1-b8c48a91e319.png)

**Comment by paaljoachim** [comment]
This issue is not valid any longer, as the Template has been moved in Gutenberg 10.5.

![Screen Shot 2021-04-23 at 16 42 39](https://user-images.githubusercontent.com/5323259/115888208-f33bfb00-a452-11eb-9d10-1fc15eb8465a.png)

**Comment by paaljoachim** [comment]
I noticed that leaving the page and entering another page that the drop down showed up.

![Screen Shot 2021-04-23 at 17 16 09](https://user-images.githubusercontent.com/5323259/115892655-a6a6ee80-a457-11eb-85a2-168fde7ab59c.png)


Related issue:
https://github.com/WordPress/gutenberg/issues/31142

**Comment by kellychoffman** [comment]
Dropdown now always appears. Closing this.
