### ISSUE TITLE
Navigation Screen: long menus get cut

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#31104]
I'm not sure if this could be considered an edge case, but if a user creates a reeeally long menu and then scrolls down to the bottom of the page, the menu gets cut by the navigation header, and the toolbar disappears. 

Another minor detail: the menu doesn't have a bottom margin, and it touches the border of the page.

## Screenshots or screen recording (optional)

![Screen Capture on 2021-04-22 at 18-19-46](https://user-images.githubusercontent.com/4933/115749951-ead2ba00-a397-11eb-8602-6cc89fcc77ab.gif)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes

## Are you using a default theme (e.g. Twenty Twenty-One)? Yes
- Device information
- Browser: Chrome, Firefox & Safari

**Comment by javierarce** [comment]
There's a related issue regarding the padding here: https://github.com/WordPress/gutenberg/issues/31543

**Comment by javierarce** [comment]
This issue has been partially solved thanks to #34225 by @getdave and the introduction of the top bar, and I think we should just add some top and bottom margins. 

Should we close it and open a new ticket to address that problem?

**Comment by getdave** [comment]
If the menu still gets cut off then this Issue is still valid but we should/could update the main description with up to date info so it can be addressed.

Otherwise if it's now "UI margin tweaks" then let's go for a new issue.

Thanks!

**Comment by javierarce** [comment]
I'm closing this issue since the navigation screen is no longer actively developed.

Related: https://github.com/WordPress/gutenberg/issues/43620.
