### ISSUE TITLE
Post Title: Add text styling options

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#31117]
## What problem does this address?
Currently, the Post Title block does not have any text styling options, like bold (or make the text normal weight if bold is the theme default), italics, uppercase. It would be nice to have those as an option for creating more interesting blog pages.

Some visual examples:
![image](https://user-images.githubusercontent.com/4550351/115827176-4613b380-a44f-11eb-8ea0-b61bcfafcfe1.png)

![image](https://user-images.githubusercontent.com/4550351/115827279-6f344400-a44f-11eb-81b1-93a7b3945edf.png)

![image](https://user-images.githubusercontent.com/4550351/115827587-d81bbc00-a44f-11eb-8326-9aa54cf8117d.png)

![image](https://user-images.githubusercontent.com/4550351/115828060-86276600-a450-11eb-8df4-e04926f564b6.png)

**Comment by paaljoachim** [comment]
@creativecoder Grant has made a PR here: https://github.com/WordPress/gutenberg/pull/31623
It can use some feedback.

**Comment by annezazu** [comment]
This was mentioned in the [seventh call for testing for the FSE Outreach program as a desired feature](https://make.wordpress.org/test/2021/05/26/fse-program-testing-call-7-polished-portfolios/#comment-1715):

> I also expected the post title heading blocks to have a bold setting, which I couldn’t find. I was able to get some styling using Global Styles, but that made a whole lot of other titles bold, regardless their H level.

**Comment by mtias** [comment]
Closing as #31623 got merged. There are still a few lingering aspects that didn't get consensus yet. We can revisit those in time.
