### ISSUE TITLE
Move to widget area available for innerBlocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31129]
In @talldan 's #30826 a button was added that allows moving a between widget areas. The problem is that we should not be able to move inner blocks only root blocks.

## To reproduce

1. Have latest Gutenberg `trunk`
2. Go to Appearance > Widgets
3. Add a buttons block
4. Add a second button
5. Notice that  in the second buttons toolbar there is a "Move to widget area button"
6. Click the "Move to widget area button" and select a widget area
7. Nothing happens

The problem is at (6), as the button should only appear for root blocks.

## Screenshots:

<img width="603" alt="Screen Shot 2021-04-23 at 14 21 06" src="https://user-images.githubusercontent.com/107534/115864223-41470380-a43f-11eb-9aa6-5fff7dfe4520.png">

**Comment by talldan** [comment]
> In @talldan 's #30826 a button was added that allows moving a between widget areas. The problem is that we should not be able to move inner blocks only root blocks.

Good spot. I don't think that's the right assumption though, there's no reason to disallow moving a paragraph in a group.

I think we need to check `canInsertBlockType` for the proposed move and not show the button if that check fails.
