### ISSUE TITLE
Add transform between post-content and post-excerpt blocks and vice versa

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#31137]
## What problem does this address?
I was working with a brand new FSE theme that starts with the absolute minimim. 
In order to create some content for `index` I used the site editor and inserted the Medium Query pattern.
This used the `post-excerpt` block.
A while later I realised that I needed the `post-content` block.
I had to add the `post-content` block then delete the `post-excerpt` block.

It would have been nice if I could have easily converted the `post-excerpt` block to a `post-content` block,
and vice versa. 

This screenshot shows the intermediate stage. The post excerpt is not formatted. The post content is. 

![thisis blog excerpt and content just one post](https://user-images.githubusercontent.com/2474435/115867754-5f0e6b80-a433-11eb-82b0-5b8aa181367b.jpg)

## What is your proposed solution?
- [ ] Add transforms between `post-content` and `post-excerpt`.

- [ ] Consider adding other transforms that make sense:
eg 
- site-title to site-tagline
- query pagination previous, next and numbers
- post-date to post-updated-date ( missing block )
- post-tags and post-hierarchical-terms

- [ ] Consider adding support for multi step transforms
eg Code to paragraph to list

for when you paste in something like this
```
* Added: This
* Changed: That
* FIxed: Something else
* Deleted: Redundant stuff
```

**Comment by vdwijngaert** [comment]
Transforming `post-content` into `post-excerpt` and vice versa seems reasonable indeed. 

I tried simply converting to `post-excerpt` using block transforms, but this results in the excerpt not being properly aligned: 
![image](https://user-images.githubusercontent.com/772137/115912773-0a3d1600-a470-11eb-9ecf-953f6e283d3e.png)

The `post-excerpt` block does not have the `layout.inherit` attribute, unlike `post-content` this option makes sure the block is properly aligned. The post meta blocks seem to be wrapped inside a group block (which _does_ support `layout.inherit`).

Not sure how to proceed. Is it possible to convert the `post-content` block into a group block containing the `post-excerpt` block? Or does the excerpt block need a layout attribute, too?

**Comment by gziolo** [comment]
> The post-excerpt block does not have the layout.inherit attribute, unlike post-content this option makes sure the block is properly aligned. The post meta blocks seem to be wrapped inside a group block (which does support layout.inherit).

@youknowriad, should Post Excerpt block also have `layout.inherit` attribute?

**Comment by youknowriad** [comment]
> should Post Excerpt block also have layout.inherit attribute?

No, since it doesn't have any child block.
