### ISSUE TITLE
Redesign text mode and include CodeMirror when it lands in 4.9

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3113]
Text mode in Gutenberg needs a lot of love. It's been largely untouched as we focused on the visual editor instead. 

![screen shot 2017-10-24 at 09 25 31](https://user-images.githubusercontent.com/1204802/31929791-87c0d110-b89d-11e7-8a6f-18f4f4c59012.png)

There are responsive issues, the toolbar isn't hooked up, and in general the experience just isn't up to snuff. 

Since CodeMirror is about to land in 4.9, let's both include that when we can, and use it as an opportunity to redesign/improve text mode in Gutenberg. 

There are a number of tickets and PRs that will be affected by this, mostly in https://github.com/WordPress/gutenberg/labels/Text%20Mode. See also:

- https://github.com/WordPress/gutenberg/issues/1837
- https://github.com/WordPress/gutenberg/issues/569
- https://github.com/WordPress/gutenberg/issues/761
- https://github.com/WordPress/gutenberg/issues/979
- https://github.com/WordPress/gutenberg/pull/3043
- https://github.com/WordPress/gutenberg/issues/3041

**Comment by mtias** [comment]
Duplicate of #1733?

**Comment by jasmussen** [comment]
Sort of. I'll port the "redesign" comments to the other thread and close this one!
