### ISSUE TITLE
Buttons block looks bad in the Customizer

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31140]
When using the buttons block in the Customizer I noticed that the buttons had no background or button shape. Here is a screenshot:

<img width="486" alt="buttons-terrible-shape" src="https://user-images.githubusercontent.com/107534/115870134-80795280-a447-11eb-9535-d73b83b90df1.png">

- [ ] The "Google" text is actually a button and shown it looks like body text
- [ ] The link UI is clipped for some reason

**Comment by JustinyAhin** [comment]
I'm testing this on WordPress 5.8-alpha-50761 and Gutenberg  10.5.3.

It seems to have been fixed already.

**Comment by draganescu** [comment]
Yep thanks for the heads up @JustinyAhin! Tested and it's fixed now.
