### ISSUE TITLE
Page template: Add template name to top bar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31147]
Creating a new page template and entering into the page template mode we see this:

![Page-template-mode](https://user-images.githubusercontent.com/5323259/115835548-ae926e80-a416-11eb-9a53-93c7316f5715.jpg)

It would be great if we can get it using the same method as is seen in the Site Editor.
![Site-Editor-screen-FSE](https://user-images.githubusercontent.com/5323259/115835871-15b02300-a417-11eb-9947-54cdcef81afe.jpg)

I believe that clearing customizations should bring the user back to the Page screen using the default page template.
At present time Browse all template might not be used.

Here is an exploration by @jameskoster 
https://github.com/WordPress/gutenberg/issues/31076

![Screen Shot 2021-04-23 at 16 32 54](https://user-images.githubusercontent.com/5323259/115886817-98ee6a80-a451-11eb-935f-4272f90a07f1.png)

**Comment by vdwijngaert** [comment]
You're talking about the post editor that opens after adding a template using Appearance > Templates, right?

I could be mistaken, but I would think that this functionality would eventually move to the Site Editor all together. Related: https://github.com/WordPress/gutenberg/issues/29449. 

edit: https://github.com/WordPress/gutenberg/issues/31114 seems to suggest a nice intermediate solution. https://github.com/WordPress/gutenberg/issues/29558 looks promising as well!

**Comment by paaljoachim** [comment]
Yes I am thinking about the Appearance -> Templates.
Clicking browse templates (seen in the mockup above) could open a modal or what has also been called a mosaic view.

Thanks for sharing @vdwijngaert Koen!

**Comment by carolinan** [comment]
The image above is not from the Appearance -> Templates, it is from the block editor > edit template link.
The Appearance -> Templates edit view does not have the padding and the back link.

**Comment by vdwijngaert** [comment]
> The image above is not from the Appearance -> Templates, it is from the block editor > edit template link.
> The Appearance -> Templates edit view does not have the padding and the back link.

Ah, I see it now. It's from the block editor > new template link. The edit link does show the template name, though. Editing a template that was newly created from the "create template" modal, does not show it. 

![image](https://user-images.githubusercontent.com/772137/115998023-a0467d00-a5e5-11eb-9063-3c093e035afc.png)

**Comment by paaljoachim** [comment]
Creating a new template also adds the Template information to the top admin bar.
Clicking to Edit a template also show the template information in the top admin bar.

Issue has been fixed.
