### ISSUE TITLE
Template dropdown in the post editor sometimes switches unpredictably

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31142]
It may happen in other flows, but this one particularly:

1. Edit post
2. Click "New" link in the Template panel in the Inspector
3. Give the new template a name
4. Click the "Back" button to return to the post
5. Notice the new template you just created has been replaced with another on the site

Video demo:

https://user-images.githubusercontent.com/846565/115873462-deec0400-a43a-11eb-8679-5da2389a2950.mp4

cc @youknowriad 

Edit: If you click the "Edit" link you're taken to the correct template. So it would appear that the dropdown is just set to the wrong value.

**Comment by youknowriad** [comment]
yes, I'm aware of this issue, basically the template list is a static list that is never refreshed and now with the template mode and the possibility to create templates, that list becomes dynamic. Refreshing the page should fix the issue for you temporarily :).

**Comment by Thelmachido** [comment]
This is no longer an issue, the template I created wasn't replaced as shown in the video below:

https://user-images.githubusercontent.com/41231764/184377576-8c8b956c-0c37-49c3-bd59-18da0d4682fc.mov

WordPress 6.0.1
Gutenberg 13.8.1 
Theme TT2
