### ISSUE TITLE
Switching allowedTypes in MediaUpload is not reflected.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#31143]
Passing MediaUpload's `allowedTypes` as a variable and switching it to match other settings will not be reflected immediately.

For example, the following code will cause this problem if `allowedTypes` changes according to other settings.

```
<MediaUpload
    allowedTypes={allowedTypes}
/>
```

## Screenshot.
Please see the following video.

![mediaUplaoder-bug](https://user-images.githubusercontent.com/31400297/115873861-6c9d1300-a47e-11eb-9727-f09d0eb934a5.gif)

**Problematic behavior**: I specify media type as "image" or "video", but I can select both image and video.

**Expected behavior**: When I specify the media type as "image" or "video", I want to be able to select only images or only videos according to the media type.

## How to reproduce the bug.

I've created a plugin that allows you to add the test block used in the screenshot above.

[media-uploader-error.zip](https://github.com/WordPress/gutenberg/files/6365428/media-uploader-error.zip)

The source code can be found at the following page.

https://github.com/ddryo/Error-Reproducer/blob/main/media-uploader-error/src/blocks/test/index.js

- Please download the plugin.
- Either upload the downloaded zip file in your test environment, or answer the downloaded file and `wp-env start` in the plugin directory.
- Upload images and videos to the appropriate media.
- Add a block called "TEST". (You can call it with `/test`.)
- Mimic the screenshot.

## When am I in trouble?

This problem occurs when I have a setting for desktop media and smartphone media, and if the desktop media is an image, I want the smartphone to select the image as well.

## WordPress information
- WordPress version: "5.7.1"
- Gutenberg version: "Not installed"
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)?  "Yes"

## Device information
- Device: "Desktop
- Operating system: Mac OS Catalina
- Browser: Google Chrome

**Comment by Mamaduka** [comment]
Hi, @ddryo

You can specify the `key` property on the `MediaUpload` component. React will recreate the component when the `key` changes or keep re-rendering as long as the `key` is the same.

Here's an updated part of the code from your example:

```jsx
<MediaUpload
    key={ allowedTypes.join('-') }
    value={ mediaId }
    onSelect={ ( media ) => {
	    if ( media ) {
		    setImage( media );
	    } else {
		    removeImage();
	    }
    } }
    allowedTypes={ allowedTypes }
    render={ ( { open } ) => (
	    <Button isPrimary onClick={ open }>
		    { mediaUrl
			    ? 'Change media'
			    : 'Select media' }
	    </Button>
    ) }
/>
```

The change in action:

https://user-images.githubusercontent.com/240569/156586041-c017e6f8-0c2e-4d76-b3fd-7494fe03c7af.mp4

**Comment by Mamaduka** [comment]
Hi, @ddryo

I'm going to close this issue. Feel free to re-open it if my example code doesn't work for you.
