### ISSUE TITLE
Clicking on the preview should deselect the block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31141]
When a block is selected, because the block toolbar and other UI flows out of the sidebar like this:

<img width="486" alt="buttons-terrible-shape" src="https://user-images.githubusercontent.com/107534/115870371-d64dfa80-a447-11eb-9a72-801dea0ee671.png">

... it would be nice that clicking in the preview could hide the overflowing block UI by deselecting the selected block. I marked this as an enhancement but, for all practical purposes it's very annoying on smaller screen real estate.

**Comment by kevin940726** [comment]
I believe this should have a higher priority as it basically block anything under the toolbar from being clicked.

Apart from clicking the preview, IMO clicking on anywhere outside the editor should clear the selection, like the section title or the empty space below the editor for instance.
