### ISSUE TITLE
Inserter menu: Visual glitch when activating search (only on Android)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#31151]
## Description

On Android when tapping on the search form, the device's keyboard shows up. This produces a visual glitch on the inserter menu at the end of the transition when the keyboard is fully displayed. The same happens when hiding the keyboard.

### Max height calculation on keyboard show/hide transition

The component used for rendering the inserter menu is the `BottomSheet`, this component checks if the content and keyboard's height exceeds the screen's height. If this happens when the keyboard is shown/hide, the content's height is changed to prevent the overflow. For this purpose, it listens to the keyboard events and recalculates the max height by that time.

The glitch is produced due to this logic, as you can see in the attached video, the view does flickering when the max height is changed at the end of the keyboard transition.

Here are some code references:
- [Keyboard events listeners](https://github.com/WordPress/gutenberg/blob/164bef81386e96330128c6218a66f29c9ed8e865/packages/components/src/mobile/bottom-sheet/index.native.js#L92-L102)
- [Max height calculation](https://github.com/WordPress/gutenberg/blob/164bef81386e96330128c6218a66f29c9ed8e865/packages/components/src/mobile/bottom-sheet/index.native.js#L164-L191)

### Potential solutions

One idea I tried to explore is to use the `LayoutAnimation` so when the max height is updated, it changes the content's height smoothly. Actually, it's even possible to synchronize the animation with the keyboard one, on iOS, this is working perfectly but not on Android 😞 .

### Caveats

There're [different keyboard events](https://reactnative.dev/docs/0.61/keyboard#addlistener) depending on when they're triggered:
- `keyboardWillShow`: Triggered at the **beginning** of the keyboard's show transition.
- `keyboardDidShow`: Triggered at the **end** of the keyboard's show transition.
- `keyboardWillHide`: Triggered at the **beginning** of the keyboard's hide transition.
- `keyboardDidHide`: Triggered at the **end** of the keyboard's hide transition.

Unfortunately, not all events work on both platforms (iOS & Android), in fact on Android, the events `keyboardWillShow` and `keyboardWillHide` are not triggered. This is a potential problem because if we want to prevent the glitch, the best would be to animate the content's size when the keyboard transition starts not at the end.

## Step-by-step reproduction instructions

1. Open the inserter menu
2. Tap on the search input
3. Observe the visual glitch
4. Tap on the back button located at the left side of the search input
5. Observe the visual glitch

## Expected behaviour

The inserter menu shouldn't produce visual glitches that make the experiences poor.

## Actual behaviour

The inserter menu produces visual glitches.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/115909970-83d30500-a46c-11eb-8fec-7702a7104b99.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 10
- WordPress app version: rnmobile/add/2575-reusable-blocks-inserter

**Comment by fluiddot** [comment]
I haven't managed to fix the original problem but I introduced layout animations in this [PR](https://github.com/WordPress/gutenberg/pull/28495) to prevent flickering. Here you can see how it looks like now:

iOS|Android
--|--
<video src=https://user-images.githubusercontent.com/14905380/116588986-79a58080-a91c-11eb-9992-40f6e993d984.mp4>|<video src=https://user-images.githubusercontent.com/14905380/116589802-50d1bb00-a91d-11eb-8eca-17f5cde8e259.mp4>

**EDIT:** I've just applied a couple of extra fixes to reduce some of the jumping issues.

**Comment by dcalhoun** [comment]
I played around with [the current explorations](https://github.com/WordPress/gutenberg/pull/28495) to fix this. I didn't find a solution, but here are a couple of things I took away. 

* The latest iteration isn't attempting to animate the keyboard events for Android, [as `duration` is always `0`](https://github.com/WordPress/gutenberg/blob/663cc8c8e224d4df4e6675cfc272fdbfb843066a/packages/components/src/mobile/bottom-sheet/index.native.js#L126). This may have set intentionally while debugging, but I reinstated [animations for Android](https://github.com/WordPress/gutenberg/commit/663cc8c8e224d4df4e6675cfc272fdbfb843066a#diff-7c783d6dab99fab7810467451bf92877850e8c2f4808af9dd836ca828fdd9821L122-L127) while exploring. 
* We attempt to set the max height for the bottom sheet in callbacks for two events: header `onLayout` and keyboard show/hide. It looks like often times the order of these two events flip-flop, which appears to make it operate differently in each occurrence. I was wondering if we might could/need to combine these two events so that a single callback is triggered to animate the height, or possibly leverage a debounce — not sure. 
* Currently, the first time I focus the search field, the keyboard is shown and then immediately hidden. I haven't determined why that is just yet. Subsequent focusing of the search field work as expected. 
* The keyboard events definitely appear to be "too late" for the calculation and animation we are attempting to do. The lack of _will_ events (e.g. `keyboardWillHide`) on Android appears to be a significant hurdle. 
* I started to explore replacing `LayoutAnimation` with `Animated` for animating `maxHeight`. I didn't make it far, but I may come back to explore further. 

Hopefully I can find more time to spend on this later.

**Comment by fluiddot** [comment]
**Thank you very much @dcalhoun for taking a look into this 🙇 !**

>The latest iteration isn't attempting to animate the keyboard events for Android, as duration is always 0. This may have set intentionally while debugging, but I reinstated animations for Android while exploring.

Yep, I make that change on purpose because it was fading out the content sometimes, my impression is that triggering the layout animation in the last iteration, stops the previous animation (the one that fades the content).

Did you experience that when testing?

>We attempt to set the max height for the bottom sheet in callbacks for two events: header onLayout and keyboard show/hide. It looks like often times the order of these two events flip-flop, which appears to make it operate differently in each occurrence. I was wondering if we might could/need to combine these two events so that a single callback is triggered to animate the height, or possibly leverage a debounce — not sure.

Right, they're dispatched at different times so it introduces a bit of inconsistency regarding the animations.

I'm not sure how we could combine the two events since they're dispatched at different places, do you have any idea?.
Debouncing option would be great, I'll try to explore it.

>Currently, the first time I focus the search field, the keyboard is shown and then immediately hidden. I haven't determined why that is just yet. Subsequent focusing of the search field work as expected.

Surprisingly this is only happening on Android, I think it's not really related to the inserter menu but the implementation of the search form, I'll post the issue in the original PR.

**EDIT:** Here's the [comment](https://github.com/WordPress/gutenberg/pull/30595#issuecomment-829987984) for following this up.

>The keyboard events definitely appear to be "too late" for the calculation and animation we are attempting to do. The lack of will events (e.g. keyboardWillHide) on Android appears to be a significant hurdle.

Totally agree, this is the root cause of the issue but I haven't found a workaround for this 😞 .

>I started to explore replacing LayoutAnimation with Animated for animating maxHeight. I didn't make it far, but I may come back to explore further.

I thought about this option but I left it as the last option because it would imply an interesting refactor, although it might be the only solid solution 💪 .

**Comment by fluiddot** [comment]
@dcalhoun I added the fixes for this issue in a different [PR](https://github.com/WordPress/gutenberg/pull/30291) where I'm only adding improvements to the header of the bottom-sheet.

Surprisingly after testing that PR, the visual glitches are less noticeable 😄, the only one that is still happening is the jump on Android related to the lack of the `will` events of the keyboard.

**Comment by dcalhoun** [comment]
> Yep, I make that change on purpose because it was fading out the content sometimes, my impression is that triggering the layout animation in the last iteration, stops the previous animation (the one that fades the content).
> 
> Did you experience that when testing?

@fluiddot yep, I did notice the erroneous opacity issue as well. I didn't debug what was occurring. I would think we could find a way to address it if we ultimately rely upon `LayoutAnimation`. 

> I'm not sure how we could combine the two events since they're dispatched at different places, do you have any idea?.
> Debouncing option would be great, I'll try to explore it.

My ideas would be disappointedly complex, but potentially necessary due to the lack of `keyboardWill*` events. 😞 I thought we could either (A) debounce the callback for each event allowing the latest arriving event to drive the animation or (B) build a system leveraging a `Promise` resolution where the animation begins once both events firing resolves the promise or the promise resolves after one event after a period of time (i.e. pseudo-debounced). 

I'm not sure which approach would be better at this point. The former would be vulnerable to a second event showing up "late." The latter would potentially be complex, I also do not know if it will deliver more value. Both may cause a odd delay in the UI updating after user input, hopefully one short enough to where the user does not notice. 

> > I started to explore replacing LayoutAnimation with Animated for animating maxHeight. I didn't make it far, but I may come back to explore further.
> 
> I thought about this option but I left it as the last option because it would imply an interesting refactor, although it might be the only solid solution 💪 .

I am still not sure if it is achievable or effective, but may be worth exploring if other options do not succeed.

**Comment by fluiddot** [comment]
>@fluiddot yep, I did notice the erroneous opacity issue as well. I didn't debug what was occurring. I would think we could find a way to address it if we ultimately rely upon LayoutAnimation.

The tricky part regarding layout animations is that they behave a bit differently on Android than iOS, particularly when dispatching multiple at the same time.

>My ideas would be disappointedly complex, but potentially necessary due to the lack of keyboardWill* events. 😞 I thought we could either (A) debounce the callback for each event allowing the latest arriving event to drive the animation or (B) build a system leveraging a Promise resolution where the animation begins once both events firing resolves the promise or the promise resolves after one event after a period of time (i.e. pseudo-debounced).
>
>I'm not sure which approach would be better at this point. The former would be vulnerable to a second event showing up "late." The latter would potentially be complex, I also do not know if it will deliver more value. Both may cause a odd delay in the UI updating after user input, hopefully one short enough to where the user does not notice.

I'm afraid that on Android unless we implement a native solution for notifying RN right before the keyboard will be shown/hide, we can't really do much to work around it.

Regarding how to synchronize the layout animations dispatched by keyboard and header layout changes, since the root cause is related to dispatching multiple layout animations on Android, I thought of a potential solution by recording when the animations are dispatched and when they finish, this way we could prevent running multiple at the same time.

I read the [API docs of `LayoutAnimation`](https://reactnative.dev/docs/layoutanimation#configurenext) and I found out that there's a callback to know when the animation finishes (`onAnimationDidEnd`) so we would have everything for this option, wdyt?

>I am still not sure if it is achievable or effective, but may be worth exploring if other options do not succeed.

From my experience, `Animated` is more reliable and customizable than `LayoutAnimation` but it could be complex to use it when there are a lot of changes. Another library that I've heard good things about lately is [Reanimated](https://docs.swmansion.com/react-native-reanimated/), I saw that [we already have it in the project](https://github.com/WordPress/gutenberg/blob/c5871c93fa9a96ce1ee84744cee4ac38ed3812a2/packages/react-native-editor/package.json#L69), maybe it worths a try 🤔 .

**Comment by dcalhoun** [comment]
> Regarding how to synchronize the layout animations dispatched by keyboard and header layout changes, since the root cause is related to dispatching multiple layout animations on Android, I thought of a potential solution by recording when the animations are dispatched and when they finish, this way we could prevent running multiple at the same time.
> 
> I read the [API docs of `LayoutAnimation`](https://reactnative.dev/docs/layoutanimation#configurenext) and I found out that there's a callback to know when the animation finishes (`onAnimationDidEnd`) so we would have everything for this option, wdyt?

👍🏻 This approach makes the most sense to me. It leverages the API provided by React Native, rather than building complexity into our source. 
 
> From my experience, `Animated` is more reliable and customizable than `LayoutAnimation` but it could be complex to use it when there are a lot of changes. Another library that I've heard good things about lately is [Reanimated](https://docs.swmansion.com/react-native-reanimated/), I saw that [we already have it in the project](https://github.com/WordPress/gutenberg/blob/c5871c93fa9a96ce1ee84744cee4ac38ed3812a2/packages/react-native-editor/package.json#L69), maybe it worths a try 🤔 .

Yeah, `Animated` may possibly worth exploring at some point to see if we can smooth out the remaining jumps on Android.
