### ISSUE TITLE
Bug in Update Post

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#3115]
i create a new Post in 4.9-beta3-41983 and then change a images. Then the Update Button dont updated the post with error in Chrome console.

<img width="528" alt="bildschirmfoto 2017-10-24 um 10 52 15" src="https://user-images.githubusercontent.com/6922544/31934404-51e19ff2-b8ac-11e7-8ead-3b8b87c9a01d.png">

**Comment by Soean** [comment]
Hey Reiko,
thanks for your error report. I can't reproduce the issue.

Do you have any other plugins active?
Can you describe step by step what are you doing before the error?

**Comment by RickorDD** [comment]
I go to Mainpage and to my Gutenberg Post and "Edit". Then in this Editview remove my "Featured Image" from the post before and "Update" then comes the react-dom Error.

**Comment by Soean** [comment]
Thanks, I can reproduce it and have the same Issue with the featured image.

**Comment by RickorDD** [comment]
sounds good. I comes from the Java world and currently little experience with JS/React. Can you show me later when fixed where the problem?

**Comment by aduth** [comment]
@RickorDD The description of #3127 includes an explanation of the issue.
