### ISSUE TITLE
Keyboard shortcuts modal does not appear in Site Editor

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#31173]
## Description
I was trying to refamiliarise myself with Keyboard shortcuts in order to attempt to complete Call 5 - Query quest using keyboard only. Imagine my surprise to discover I couldn't find what the keyboard shortcuts were.

## Step-by-step reproduction instructions

1. Open Site Editor
2. Click on "More tools & options"
3. Click on "Keyboard shortcuts"

or, on Windows, press `Shift + Alt + H` 

## Expected behaviour
- Keyboard shortcuts modal dialog should appear, like it does in the block editor.
- With some of the shortcuts included
- And some taken out eg
  - Switch between visual editor and code editor
  - Toggle fullscreen mode
 

## Actual behaviour
- No dialog appears.
- No messages in the console.

Note: Some of the keyboard shortcuts, such as `Shift + Alt + O` to open **or close** the block list view, do work.

## Screenshots or screen recording (optional)
The first part of what I might have expected to see:

![image](https://user-images.githubusercontent.com/2474435/115994789-5bfcb200-a5d0-11eb-8929-a9fa40e73238.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes. TT1 blocks

## Device information
- Device:  Desktop
- Operating system: Windows 10 
- Browser: Chrome - Version 89.0.4389.128 (Official Build) (64-bit)

**Comment by mtias** [comment]
This is being tracked in https://github.com/WordPress/gutenberg/issues/21245. Should be picked up soon.
