### ISSUE TITLE
Customizer widget editor does not publish changes

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31177]
## Description
When having a legacy widget added in the standalone editor saving works. However, when moving to the Customizer and editing the legacy widget, publishing changes fails with the error `Unable to save due to 1 invalid setting.`

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk` and TT1 theme active
1. Install and activate the Site Origin widgets bundle.
2. Go to Appearance > Widgets
3. Add a heading block.
4. Add a legacy widget, pick Site Origin Button Widget
5. Edit the legacy widget - set button label - and save the changes
6. Go to Appearance > Customize > Footer
7. Edit the legacy widget - change the button label
8. Publish
9. Notice the error on top of the sidebar `Unable to save due to 1 invalid setting.`

## Expected behaviour
Changes are published.

## Actual behaviour
Changes are not published.

## Screenshots or screen recording (optional)
<img width="1300" alt="invalid-setting" src="https://user-images.githubusercontent.com/107534/116042241-d7b13a00-a676-11eb-8f79-e1327a6bb04b.png">

**Comment by talldan** [comment]
The error from the ajax request when publishing is is:
`widget_sow-button[2]: {invalid_value: {message: "Invalid value.", data: null}}`

Comparing the same request from the current widget screen to the new screen, it looks like none of the SiteOrigin Button widget settings are being passed to the endpoint. All of these are missing in the request in the new screen:
<img width="473" alt="Screenshot 2021-05-04 at 5 13 02 pm" src="https://user-images.githubusercontent.com/677833/116983081-3e2ffb00-acfc-11eb-9319-1a94006ac806.png">
