### ISSUE TITLE
Edits to legacy widget blocks in the block widget editor don't get previewed

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31190]
## Description
As mentioned in #31094 legacy widgets do not show up in the Customizer embedded widget editor. But, if a legacy widget is added in the standalone editor, then it can be customized in the Customizer. I don't know if this bug is related to #31094 but, when values are updated in the legacy widget's form the changes are not previewed in the preview panel.

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk` and a theme with sidebars
1. Install Site Origin widget bundle
2. Go to Appearance > Widgets
3. Add the accordion widget from Site Origin to any widget area (sidebar)
4. Save
5. Go to Appearance > Customize > Widgets > [your widget area]
6. Notice the accordion widget is perfectly editable
7. Change the title of the widget or some of the panels
8. Notice the preview of the Customizer does not show the changes
9. Notice the legacy widget preview does show the changes

## Expected behaviour
The legacy widget preview and the customizer preview should be in sync and show the same updated view.

## Actual behaviour
The customizer preview does not get any updates when customizing a legacy widget, but the legacy widget block's preview is up to date.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/107534/116077266-f545ca00-a69d-11eb-883c-76f2a7648eb8.mp4

**Comment by noisysocks** [comment]
This appears to be working fine for me, although the widget is a little difficult to use without #31194.
