### ISSUE TITLE
Add Block: Text

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#312]
## Attributes

- Alignment: Left, Right, Center.
- Formatting bar.

## Markup

```html
<p>The quick brown fox jumps over the lazy dog.</p>
```

## States ([see all](https://wpcoredesign.mystagingwebsite.com/gutenberg/#text))

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Text,%20Selected.png)

**Comment by joyously** [comment]
Is the Text block for when you already know you have text? Or a generic block that anything can be typed into?  The reasoning is that paragraphs can contain phrasing content only, not flow content. So if you know it's only text, use `<p>`. But if there is flow content, (`<table>`, `<pre>`, `<blockquote>`, `<div>`, `<hr>`, `<h1-6>`, etc.), you better use `<div>` or split these to separate blocks as they are entered.

**Comment by mtias** [comment]
The idea is all those would be separate blocks, but remains to be seen in implementation how it works.

**Comment by aduth** [comment]
How should the markup look if the text is aligned?

Currently it's applied as an inline style attribute (`style="text-align: center;"`).

We may want to consider moving away from this, or at least allow themes to define support for a better alternative (styles applied via class?) not too much unlike the [`html5` theme support](https://developer.wordpress.org/reference/functions/add_theme_support/#html5).

**Comment by joyously** [comment]
Typically, if you select a portion of the text to style, it would be by adding a `<span>` wrapper with an inline style. Much as I don't like inline styles, for text alignment and bold and italic, I think they are okay.
If no text is selected, I assume the block _is_, and the inline style would go on the block's tag.

**Comment by jasmussen** [comment]
As a small update on this, we should explore two approaches for writing and wrangling text in the editor:

1. a paragraph is a single block with controls docked at the top of this block
2. multiple paragraphs in succession is a single block, with controls docked at the top of the block

We should build both, see which one works best, and keep only the one that works best. See https://github.com/WordPress/gutenberg/issues/447#issuecomment-296982374 for a mockup.

**Comment by jasmussen** [comment]
Closing as fixed 🎉
