### ISSUE TITLE
Uncaught (in promise) Error with many taxonomies registered to custom post type

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#31208]
## Description
This report has been copied over from [Trac-52952](https://core.trac.wordpress.org/ticket/52952).

>  I get a "Uncaught (in promise) Error: The entity being edited (postType, undefined) does not have a loaded config." error message when trying to edit a custom post type with lots of taxonomies registered. When the number of registered taxonomies reaches 67, the error is triggered. At less than 67, the error is not present.
> 
> Taxonomies and CPT were registered with Custom Post Type UI, but the error is still there if I switch to registering via code.
> 
> This error is present with latest version of WP (5.7) with the twentytwentyone theme. Using the Classic editor does not trigger the error, even with more than 67 taxonomies.

## Screenshots or screen recording (optional)
<img width="1115" alt="Screen Shot 2021-03-31 at 12 33 53 PM" src="https://user-images.githubusercontent.com/359867/116136539-6dad8a80-a6a0-11eb-9421-d53470e2c81b.png">

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Not sure.
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty-One

**Comment by kathrynwp** [comment]
Hi @dsutoyo Would you be able to confirm if this issue is still occurring in the latest version of WordPress, with the latest version of Gutenberg active or inactive? 

Also, would you be able to answer the question from the Trac ticket that @desrosj had asked last year:

> One question you could answer that would be helpful is whether there were any other plugins active, or if you were able to reproduce the behavior on a fresh install with no active plugins.

Thanks for your help!

**Comment by dsutoyo** [comment]
@kathrynwp thanks for following up. I believe we can close this one. The issue was caused by me using a reserved word for a CPT.
