### ISSUE TITLE
not delete posts in german

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#3121]
when my WP Settings in German the can not delete a post in Gutenberg View. Is this a problem with translation file?

<img width="760" alt="bildschirmfoto 2017-10-24 um 14 29 22" src="https://user-images.githubusercontent.com/6922544/31943133-fb915eb4-b8c7-11e7-8da4-eb39555230b9.png">

**Comment by Soean** [comment]
The language is not the problem. Can you describe step by step what are you doing before the error?

**Comment by RickorDD** [comment]
change to "Deutsch"

<img width="617" alt="bildschirmfoto 2017-10-24 um 20 52 47" src="https://user-images.githubusercontent.com/6922544/31962310-86999f14-b8fd-11e7-99b7-337911bedca6.png">



click to "Bearbeiten" 

<img width="348" alt="bildschirmfoto 2017-10-24 um 20 53 13" src="https://user-images.githubusercontent.com/6922544/31962313-87436a6c-b8fd-11e7-81a2-2debeb24d403.png">



"Move to trash"

<img width="1110" alt="bildschirmfoto 2017-10-24 um 20 53 40" src="https://user-images.githubusercontent.com/6922544/31962314-87678870-b8fd-11e7-96ce-3da7bd81290d.png">

**Comment by Soean** [comment]
I can't reproduce the bug. Looks like the REST API is not working. Maybe you have to reset the permalinks once.

**Comment by RickorDD** [comment]
only DELETE has no route.
Other RESTs running.
Whats the correct DELETE?

<img width="682" alt="bildschirmfoto 2017-10-25 um 21 46 29" src="https://user-images.githubusercontent.com/6922544/32019697-4e9e55ba-b9ce-11e7-9bdd-39521fd2796d.png">

**Comment by RickorDD** [comment]
the bug is also in Francais and Dansk.

<img width="505" alt="bildschirmfoto 2017-10-27 um 07 36 20" src="https://user-images.githubusercontent.com/6922544/32089328-a09acc7e-bae9-11e7-95bb-b9d218492c49.png">

**Comment by RickorDD** [comment]
i tested with
curl -X DELETE http://52.212.255.218/wordpress/index.php?rest_route=/wp/v2/posts/11245?force=true
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

but
curl -X DELETE http://52.212.255.218/wordpress/index.php?rest_route=/wp/v2/posts/11245
{"code":"rest_cannot_delete","message":"Sorry, you are not allowed to delete this post.","data":{"status":401}}

Why is in all languages except English (United States) add the "**?force=true**"?
