### ISSUE TITLE
Width in pixels is not applied at search block

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/gutenberg#31213]
## Description
The width in pixels for search block is not applied.

## Step-by-step reproduction instructions
1.Create 2 search blocks.
2.For the first, set the width to 150px.
3.For the second, set the width to 100%.
At front-end (and also in editor), these blocks have the same width (see screenshot 1).
![screenshot-01](https://user-images.githubusercontent.com/75045144/116156757-2f3dbd00-a6ec-11eb-8b14-b93cb1c732f0.png)

4.Change the alignement to center for the first block.
5.Then change the alignement to left for the first block.
The width is applied to the block.

![screenshot-02](https://user-images.githubusercontent.com/75045144/116156849-55635d00-a6ec-11eb-9735-d9d33257cb01.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? no plugin installed
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes TTO

## Device information
- Device: Desktop
- Operating system: Win 10
- Browser: Chrome 90 or Firefox 88

**Comment by jordesign** [comment]
I can no longer repro this in WP6.3 so I will close this issue.
