### ISSUE TITLE
Gutenberg Plugin 11.0.0 - Editor changing line-height and color, not WordPress's default

### ISSUE THREAD

**Issue by cngodles** [WordPress/gutenberg#31211]
## Description
The Block Editor font has had its `line-height` and `color` altered from its default. There appear to be modifications in `reset.css` that affect the editing experience only when the plugin is enabled. This is affecting at the very least the Paragraph, the List, and perhaps the Header block.

`reset.css` seems to be effecting the `color`

![image](https://user-images.githubusercontent.com/5685764/116143242-e57fb300-a6a8-11eb-842c-ad95a59c0ee4.png)

And the `line-height`.

![image](https://user-images.githubusercontent.com/5685764/116143281-f3cdcf00-a6a8-11eb-9045-518f32432c07.png)

I originally reported this in #30046 with the primary callout being the displayed font. That appears to have been corrected, however since the `line-height` and `color` are still an issue, I am opening up this separate issue.

When I deactivate the plugin, the fonts show correctly.

Here are Chrome's computed values for the paragraph block. The enabled plugin (top) vs the disabled plugin (bottom).

![image](https://user-images.githubusercontent.com/5685764/116095647-9ae54300-a676-11eb-9d7f-c1b1c1f669f7.png)

## Step-by-step reproduction instructions
1. Update/Enable Gutenberg Plugin 10 (10.4.1)
2. Open the WordPress Gutenberg editor for any page or post.

## Expected behavior
The values for `line-height` and `color` should be the same as the WordPress 5.7.1 experience, without the Gutenberg plugin installed and enabled.

## Actual behavior
Fonts are appearing using the default system serif font.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? No.
- Are you using a default theme (e.g. Twenty Twenty-One)? No. Using the Dollah Theme.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Latest. Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by cngodles** [comment]
Retested in 10.6.2, the issue still exists.

**Comment by skorasaurus** [comment]
still exists in 11.

**Comment by cngodles** [comment]
I'm going to say that this has made it into WordPress 5.8. I am running into this on two very different installs. One has the template I originally described, the other is a custom template that makes no use of any sort of special font formatting.

This issue now occurs without the plugin enabled. It's a highly critical degradation of the intended Gutenberg editing experience.

## line-height

I am getting this `line-height`, which I think takes away from the WordPress editing experience the most.

![image](https://user-images.githubusercontent.com/5685764/128110074-a5eeae33-b2df-47c6-8d85-0eaac78205da.png)

The original editor-style `line-height` was the 28.8px style, which I felt was the heart of the default Gutenberg editing experience.

## color

Also the color. It has been set to `rgb(0,0,0)`, whereas the original experience was `rgb(30,30,30)`.

![image](https://user-images.githubusercontent.com/5685764/128110503-1affc911-1279-402b-ac37-10480e250894.png)

**Comment by cngodles** [comment]
This is fixed by #34439. The problem still exists in the core, but it looks like a solution is coming with 5.9.
