### ISSUE TITLE
Design bundled Template Part patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#31231]
Paired with the work in #31155, we should consider exploring various patterns for Template Parts. Let's use this thread to brainstorm possible designs.

Like the Query patterns explored in #30508, these patterns would likely be bundled with Gutenberg for a short time, and then would shift over to the Pattern Directory.

As per #29159, these would map to a few categories: 

- Headers
- Footers
- General

**Comment by carolinan** [comment]
I think this needs to be solved first because if the template part block **itself** has styling options it will change how the pattern looks.
https://github.com/WordPress/gutenberg/issues/30732

**Comment by kjellr** [comment]
To get this started, I spent a little time on potential Header & Footer patterns. These are thematically based on the new patterns, however most of the blocks here would use dynamic blocks and would reflect the actual site they're previewed on. 

I ran into a few issues while creating these: 

- Lack of fine-tuned spacing controls between blocks (#28356)
- Lack of bold or italic styles for the Site Title block (https://github.com/WordPress/gutenberg/issues/30918#issuecomment-832038843)
- Right-aligned search field appears incorrectly. (https://github.com/WordPress/gutenberg/issues/31517)
- Search block missing icon-only option. (https://github.com/WordPress/gutenberg/issues/31128)
- Twenty Twenty-One imposes a background color on the Nav block, and this doesn't appear to be fully changeable. ([53161-Trac](https://core.trac.wordpress.org/ticket/53161))

The footer patterns could use the most work — I think it would be helpful to include an option that uses a typical blog footer with latest posts, categories/tags, etc. 



## Header

![header](https://user-images.githubusercontent.com/1202812/117028542-d1047180-accb-11eb-8bd4-d66d373f15af.png)


## Footer

![Screen Shot 2021-05-05 at 11 24 55](https://user-images.githubusercontent.com/1202812/117028566-d5c92580-accb-11eb-8421-09fa8be1c0a9.png)

**Comment by carolinan** [comment]
Yeah aligning a paragraph and site title to create a copyright or credit text in the footer isn't possible without additional CSS to force them to be inline.

**Comment by mtias** [comment]
This a great start!

**Comment by kjellr** [comment]
Adding a couple more issues that I ran into, specifically around getting these to work responsively: 

- Specifying alternate alignments for small screens. (https://github.com/WordPress/gutenberg/issues/19909#issuecomment-833575572)
- Declaring that columns should not wrap on mobile. (https://github.com/WordPress/gutenberg/issues/31248#issuecomment-833568210)

**Comment by carolinan** [comment]
For general template parts, it would be great to be able to use post meta information in template parts.
But it is not possible to place post date, post title, post author, tags etc in a template part because it will only show the information for the current item, it does not use context so it can not be used in a loop.

**Comment by Sandstromer** [comment]
![gutenberg-pattern-header](https://user-images.githubusercontent.com/76742815/117437441-1f15b100-af28-11eb-905e-ef50852bf444.png)

### Blocks used in this pattern

![gutenberg-pattern-header-blocks-view](https://user-images.githubusercontent.com/76742815/117438322-4faa1a80-af29-11eb-8abf-563a9682ac94.png)

**Comment by carolinan** [comment]
I think it would be good to have social icons in at least one of the footers?

**Comment by kjellr** [comment]
> I think it would be good to have social icons in at least one of the footers?

Yeah, definitely. I realized I didn't include a site tagline in any of the headers either. 😄 I'll iterate a bit as I try building these out.

**Comment by mtias** [comment]
This is in place already.
