### ISSUE TITLE
Adding a legacy widget and saving right away fails

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31249]
## Description
Adding a Woo Product Tag Cloud and savind directly fails with the messahe `There was an error. f. is undefined.` I think it applies to any widget that does not need any configuration and you just want to save it,

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk`
1. Install Woo
2. Go to Appearance > Widgets
3. Add a Woo Product Tag Cloud
4. Save
5. See error

## Expected behaviour
The added widget should be saved and just work

## Actual behaviour
It appears that if you edit the defaults AND preview the widget the save function works again.

https://user-images.githubusercontent.com/107534/116288554-4dfa8d00-a79a-11eb-8d8d-08feb68add48.mp4

**Comment by noisysocks** [comment]
This has the same root cause as https://github.com/WordPress/gutenberg/issues/31249:

> OK I see the problem. We need to submit the widget's form when creating a new Legacy Widget as sometimes the widget's default values are encoded in the form's values. I'm not yet sure how to do that elegantly with useFormData.

This issue has better steps to reproduce so I'll close the other issue.
