### ISSUE TITLE
Feedback: color settings for Post Title Block are confusing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31255]
## What problem does this address?

[This feedback came up as part of the fifth call for testing](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1501) for the FSE Outreach Program:

>when adding a dark background color I tried to set the text color to a light color and was surprised when changing it had no effect. Only after thinking this through did I realise I needed to alter the Link Color in order to have the text color change. If the heading is a link then we should just have a single color control for Text color which changes both text and link colors. Users shouldn’t have to understand CSS inheritance – https://d.pr/v/kF8f75/jrq1PIYMYE

Speaking personally, I've also fallen prey to this as it's not quite intuitive that it's a link. This might be one of those things to adjust to in the query block context but feels worth passing along. 

## What is your proposed solution?

As suggested above, one possible solution is to have a single color control for Text color which changes both text and link colors.

This is semi related to https://github.com/WordPress/gutenberg/issues/30719

**Comment by carolinan** [comment]
I am not sure how this would work since some blocks will have both regular text and links.
Especially not if the link setting is expanded to include hover and focus colors and text decorations 🤔

**Comment by carolinan** [comment]
There is a suggestion to allow removing the link, so this block would have both text color and link color options.
I don't know if that is more or less confusing, because the link color option is always available even if the link option is disabled.

**Comment by annezazu** [comment]
Noting that this came up in the [seventh call for testing and caused additional confusion](https://make.wordpress.org/test/2021/05/26/fse-program-testing-call-7-polished-portfolios/#comment-1703) as it seemed as though one should be able to change the color of the post title using the text color options.

**Comment by annezazu** [comment]
This came up in the [tenth call for testing as well](https://make.wordpress.org/test/2021/09/29/fse-program-testing-call-10-pattern-party/#comment-2099):

> when selecting the text color and link color, the color that would actually show would depend on the link settings if you were to ‘make title a link’ or not, which I found to be a bit confusing.

**Comment by annezazu** [comment]
Closing this out in light of the more comprehensive issue here: https://github.com/WordPress/gutenberg/issues/36972
