### ISSUE TITLE
Navigation Link stores url as id

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#31254]
After adding a custom link, the block id attribute is set to the url value. In this case we'd expect no id attribute to be set for a custom link.

With work in https://github.com/WordPress/gutenberg/pull/31004 we may also want to add the a `kind` value of `custom`

https://user-images.githubusercontent.com/1270189/116308559-7b284a80-a75c-11eb-98fd-0c8b462cba3b.mp4

**Comment by gwwar** [comment]
Looks like it's coming from https://github.com/WordPress/gutenberg/blob/d74e04714b3860a4a960daeca2d3ca47bcdb7c01/packages/block-editor/src/components/link-control/use-search-handler.js#L22-L47

The type value for a custom link can be `URL`, `mailto`, `tel` or `internal`

**Comment by getdave** [comment]
> we'd expect no id attribute to be set for a custom link.

That's 💯 . We definitely do not need an ID for custom. Indeed I've specifically guarded against that case in https://github.com/WordPress/gutenberg/pull/31004
