### ISSUE TITLE
Featured Image Block: Unable to upload featured image if import broken image link

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31256]
## Description

This is an edge case bug that was found as part of the FSE Outreach Program's fifth call for testing. Essentially, if you import content using the WordPress importer but the featured image links are broken, the featured image block doesn't allow you to replace/act on adding an image in any way. 

## Step-by-step reproduction instructions

1. Setup a site with FSE
2. Using the WordPress importer, upload demo content that has broken image links like so: https://cloudup.com/c8pPIugGZd9
3. Head to the Site Editor
4. Add a query block and see featured image error

## Expected behaviour

Expect to still be able to add/remove featured image. For example, in the post editor, it just shows as loading but you're able to still remove and re-upload a new image.

## Actual behaviour

Unable to act in any way on featured image block. 

## Screenshots or screen recording (optional)

<img width="1103" alt="Screen Shot 2021-04-27 at 3 40 04 PM" src="https://user-images.githubusercontent.com/26996883/116316235-dbc08300-a76e-11eb-82cd-32dcc919cc1b.png">

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

**Comment by kathrynwp** [comment]
Hi @annezazu do you happen to recall what the error said or looked like at this step?

> Add a query block and see featured image error

I haven't been able to spot any error in the Site Editor after importing your test file, but maybe I'm not looking in the right place? Here's a screenshot of the Query Loop block in the Index template, for example:

![Editor__beta__‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/184935877-0c7d0f99-706a-44a7-9dc8-cb4810999eed.jpg)

And in the post editor, I was able to remove the bad featured image from the import and add a new one, as expected:

![Edit_Post_“On_top_of_the_world”_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/184936222-b167fcf4-2037-45ec-a94a-a8575ae188e5.jpg)

I'm going to close this out as fixed, but if you can still replicate, please let me know!

**Tested with:**

WordPress 6.0.1
Gutenberg 13.8.2 active or inactive
No other plugins active

Twenty Twenty-Two 1.2

**Comment by annezazu** [comment]
This is SUCH an edge case and I'm going to keep it closed, since now the placeholder at least shows up: 

https://user-images.githubusercontent.com/26996883/185018018-f2d88b9f-7b80-48d8-9d98-94962859d428.mov

Thank you for triaging!
