### ISSUE TITLE
Inconsistent Pattern Insertion between Page Editor and Site Editor

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#31251]
## Description

The site editor has a pattern insertion experience inconsistent with the page editor. I think, likely, due to what happens when one opens the top inserter in the site editor.

## Step-by-step reproduction instructions

Compare the following pattern insertion experiences.

**Page Editor**

![insert-pattern-into-page-small](https://user-images.githubusercontent.com/545779/116293636-ba569b80-a75c-11eb-8c8d-26bb79f3d229.gif)

**Site Editor**

![insert-pattern-into-template-small](https://user-images.githubusercontent.com/545779/116293680-c17da980-a75c-11eb-88d6-e1208d2bcf97.gif)

## Expected behaviour

One would be able to see the pattern they just inserted into the site editor.

## Actual behaviour

When inserting a pattern into the bottom of a template I was not able to see the pattern I just inserted without scrolling down.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? No. (Jetpack active.)
- Are you using a default theme (e.g. Twenty Twenty-One)? No. (Hansen.)

## Device information
- Device: Desktop
- Operating system: MacOS 11.3
- Browser: Chrome 91.0.4472.19

**Comment by ntsekouras** [comment]
Hey 👋 I couldn't reproduce on latest `trunk`...

![patterns](https://user-images.githubusercontent.com/16275880/116410101-1e509100-a83d-11eb-9682-63b43693e286.gif)

**Comment by david-szabo97** [comment]
I can reproduce the issue.

https://user-images.githubusercontent.com/2256104/116858201-473aa280-abfe-11eb-858b-cbeca5fc5fed.mov
