### ISSUE TITLE
Sidebar opens itself when clicking widget areas

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31250]
https://user-images.githubusercontent.com/107534/116289118-e0029580-a79a-11eb-9716-7a58ff75381b.mp4

**Comment by noisysocks** [comment]
I'm able to reproduce this.

**Comment by tellthemachines** [comment]
Pretty sure this has been fixed by  #32450, could you double check?

**Comment by Mamaduka** [comment]
I tested on the trunk, and I'm no longer able to reproduce this issue.
