### ISSUE TITLE
Query Block: ensure focus is on Query Block after insertion

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31252]
## What problem does this address?

This came up during the [fifth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1501):

>I tried inserting one of the block’s patterns called Large title and upon insertion, the editor focused the Group block and not the Query block. This was very disconcerting. I inserted a Query Block so I didn’t expect to see a Group block. I guess the group is used to wrap the pattern but we need to make sure we’re focusing on the block the user chose to insert and not the wrapper of the pattern 

https://user-images.githubusercontent.com/26996883/116304817-356d8100-a760-11eb-9fbf-03362931bdb7.mp4

## What is your proposed solution?

Ensure the focus is put on the Query Block rather than the Group Block as it immediately adds a hurtle to customizing the Query Block. Of note, @kjellr this seems to mainly be related to the new patterns added in with this PR as it does not happen with 10.4.1 but does when I use this PR: https://github.com/WordPress/gutenberg/pull/30763

**Comment by ntsekouras** [comment]
Hey 👋 - this is not related to `Query` specifically but to the `Pattern suggesting in placeholder` functionality.

This new functionality allows the usage of more complex patterns that don't necessarily include only the blocks from which are shown. While there could be a way to fine tune this for Query, it would also create confusion when patterns contain more than one `Query` blocks like the `Offset` bundled pattern in GB.

**Comment by annezazu** [comment]
Thanks for the wider context! I wonder what the best solution is here or if this is a "won't fix".

**Comment by kjellr** [comment]
Yeah, I'm not sure. I bet we could technically shift focus to the first Query block in the pattern when it's inserted? Might be worth a PR to see if it feels natural.

**Comment by ntsekouras** [comment]
I'm not sure either, although I lean to a `won't fix` a bit more :). On the other hand most `Query` patterns will probably include one `Query` block so it doesn't hurt to make a PR for exploring this.
