### ISSUE TITLE
Query Block: Allow term addition from user case-insensitive input

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31258]
## Description

When customizing the query block results, one cannot use a comma to separate out categories to include. [This was discovered as part of the fifth call for testing](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1513) for the FSE Outreach Program:

> Worked as expected except under QueryBlock>Filters>Categories there is a note that says "Separate with commas or the Enter key." If you type "hikes," with the intent of adding "travel" as soon as you add the comma, the field goes blank. If you start typing “hi..” and select the category everything works as expected. 

## Step-by-step reproduction instructions
1. Create a site with FSE capabilities 
2. Head to the site editor
3. Add a query block
4. Go to the Block Settings sidebar
5. Unselect "inherit global query"
6. Under Categories, try to add two categories separating with commas and find you can't. 

## Expected behaviour

Expect to be able to add commas to separate out categories. 

## Actual behaviour

The first category you add gets erased when you add a comma. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/116318880-bd5c8680-a772-11eb-948c-2feca243c271.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by ntsekouras** [comment]
Currently `FormTokenField` which is used in Query block for adding categories and tags, shows suggestions that are case insensitive. The actual addition though was performed by trying to find a case sensitive match and that resulted in not adding a term if the user pressed Enter or tried to separate with comma.

I've linked a PR that adds an extra check for entered terms in a non case sensitive way, to better match user expectations.

**Comment by annezazu** [comment]
Huzzah! Amazing! Thanks for figuring out what was going on there.
