### ISSUE TITLE
Cover block hides content if color variable is not set

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#31253]
## Description
A user created a cover block with fairly complex content. When they switched themes, there were no obvious errors in the editor, but none of the content appeared either. I took video so you can get a better idea what's happening:
https://cloudup.com/cHLs8znxI1n

HT @akirk for figuring out what was causing the user's content to go missing!

## Step-by-step reproduction instructions
- Activate a theme that has theme-based color support (this user had Hever active)
- Start a post or page. Add a cover block and pick a background color from the theme's palette
- Add content to the cover block and publish
- Switch themes to one that does not have the same type of color support
- Edit the post; note the visual editor does not display the content, even though it is still there in "Code"  as well as on preview.
 
## Expected behaviour
I would expect the cover block to display, perhaps with default colors selected.

## Actual behaviour
The cover block shows a color selection option and does not display the content.

## Screenshots or screen recording (optional)
https://cloudup.com/cHLs8znxI1n

## WordPress information
- WordPress version: Sorry I'm not finding this, but it's on a WordPress.com free site, so everything is fairly current.

## Device information
- Device: n/a, it happens on various devices, OSs, and browers.
- Operating system: n/a
- Browser: n/a
- User report here: https://wordpress.com/forums/topic/visual-editor-doesnt-function/#post-3669988

**Comment by supernovia** [comment]
Noting this possibly related discussion: https://github.com/WordPress/gutenberg/issues/29568

**Comment by stokesman** [comment]
This is another way to reproduce #28888. Switching themes and having the content not show seems like it would be especially confusing.
