### ISSUE TITLE
Floating URL bar not appearing near bottom of block

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#3126]
I'm on WordPress 4.8.2, Gutenberg 1.5.0.

I've just been using Gutenberg to edit a post on my site and was using a block to enter a long list of items. However, after getting so far down the list, when highlighting text and clicking on the link icon, the URL bar no longer appears. The link icon darkens, to indicate that it's in use, however.

I've tried it since with a large text block too and the same occurs - so long down the text the ability to add a link suddenly breaks.

Attached is an animated GIF of a screencast I did showing the issue. Let me know if you want to see the original .mov file, which is higher quality.
![gutenberg link issue](https://user-images.githubusercontent.com/14928971/31946133-eaecdeb6-b8c8-11e7-95cf-59e1ad7a6af5.gif)

**Comment by mtias** [comment]
This should be fixed now. Please, reopen if you still reproduce.
