### ISSUE TITLE
Widgets editor: Deleting a block should delete it, not move it to Inactive Widgets

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#31263]
## Description
Right now if you delete a block in the Widgets editor screen then that widget will be moved to the Inactive Widgets area. It should be deleted permanently.

## Step-by-step reproduction instructions
1. Navigate to Appearance → Widgets.
2. Delete a block from a widget area.
3. Press _Save_.
4. Refresh the page.
5. Expand Inactive Widgets.

## Expected behaviour
The block you deleted should not be there.

## Actual behaviour
It's there!

**Comment by noisysocks** [comment]
I'm 80% sure that this is because we need to pass `?force=1` to the REST API when deleting.

**Comment by talldan** [comment]
Wow, good catch, never noticed this 😄

**Comment by tellthemachines** [comment]
I can reproduce this, and not only the deleted block ends up in Inactive but any blocks I created and saved immediately before deleting will be copied over to Inactive too. Not sure if that's the same or a different issue.
