### ISSUE TITLE
Site Editor: show More Settings in Block Toolbar

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#31286]
The More Settings option is not present in the Block Toolbar and it may not be obvious how to get to the Inspector Controls. We should probably align this with the Post Editor.

Post editor:

<img width="645" alt="Screen Shot 2021-04-28 at 4 07 58 PM" src="https://user-images.githubusercontent.com/1182160/116417844-edbc2780-a83b-11eb-9f65-0ef0086bc406.png">

Site editor:

<img width="697" alt="Screen Shot 2021-04-28 at 4 06 56 PM" src="https://user-images.githubusercontent.com/1182160/116418000-0af0f600-a83c-11eb-981f-75e37bbe553f.png">

**Comment by creativecoder** [comment]
Draft PR up at https://github.com/WordPress/gutenberg/pull/31305
