### ISSUE TITLE
Select mode: Allow the entire block to function as a drag-handle

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31284]
In select mode, the selected block can be re-arranged by dragging the block chip:

https://user-images.githubusercontent.com/846565/116413320-68327a80-a82f-11eb-8207-165c1d9c01ac.mp4

It might be nice to extend that interaction to the block itself, so that there is a larger hitbox for drag and drop. Clicking the block should still switch to edit mode.

https://user-images.githubusercontent.com/846565/116414002-0292be00-a830-11eb-8dbe-2303d3d31bd4.mp4

**Comment by paaljoachim** [comment]
Being able to drag the full block chip and the block itself while in Select Mode sounds like a very good idea!

**Comment by mtias** [comment]
Before supporting the entire block as drag handle we should allow the entire toolbar in select mode to be draggable.

**Comment by youknowriad** [comment]
Select mode has been removed and it's now possible to drag non textual blocks by just clicking and dragging them.
