### ISSUE TITLE
Base Block Styles Loaded Differently for PHP templates than Block-based HTML templates.

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#31293]
## Description
When a block-based HTML template is used to render a page base block styles are loaded inline, and are loaded prior to the styles generated based on theme.json.
i.e.
```
<head>
...
<style id='wp-block-button-inline-css' type='text/css'>
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;cursor:pointer;display:inline-block;font-size:1.125em;padding:calc(.667em + 2px) calc(1.333em + 2px);text-align:center;text-decoration:none;overflow-wrap:break-word;box-sizing:border-box}.wp-block-button__link:active,.wp-block-button__link:focus,.wp-block-button__link:hover,.wp-block-button__link:visited{color:#fff}.wp-block-button__link.aligncenter{text-align:center}.wp-block-button__link.alignright{text-align:right}.wp-block-buttons>.wp-block-button.has-custom-width{max-width:none}.wp-block-buttons>.wp-block-button.has-custom-width .wp-block-button__link{width:100%}.wp-block-buttons>.wp-block-button.has-custom-font-size .wp-block-button__link{font-size:inherit}.wp-block-buttons>.wp-block-button.wp-block-button__width-25{width:calc(25% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-50{width:calc(50% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-75{width:calc(75% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-100{margin-right:0;width:100%}.wp-block-button.is-style-squared,.wp-block-button__link.wp-block-button.is-style-squared{border-radius:0}.wp-block-button.no-border-radius,.wp-block-button__link.no-border-radius{border-radius:0!important}.is-style-outline>.wp-block-button__link,.wp-block-button__link.is-style-outline{border:2px solid;padding:.667em 1.333em}.is-style-outline>.wp-block-button__link:not(.has-text-color),.wp-block-button__link.is-style-outline:not(.has-text-color){color:currentColor}.is-style-outline>.wp-block-button__link:not(.has-background),.wp-block-button__link.is-style-outline:not(.has-background){background-color:transparent}
</style>
...
<style id='global-styles-inline-css' type='text/css'>
...
</head>
```
When a php-based template is used to render a page the base block styles are loaded from CSS files instead, and are loaded at the bottom of the body.
```
<style id='global-styles-inline-css' type='text/css'>
...
</head>
<body>
   ... content ...
   <link rel='stylesheet' id='wp-block-button-css'  href='http://localhost:4759/wp-content/plugins/gutenberg/build/block-library/blocks/button/style.css?ver=1619619707' type='text/css' media='all' />
...
</body>
```
The result is incorrect application of styles as the 'base' supersedes the 'generated global styles' in most scenarios.

## Step-by-step reproduction instructions
Load (or create) a theme that leverages Global Styles via theme.json but renders PHP templates.  ([Here is a simple theme as an example.](https://github.com/WordPress/theme-experiments/tree/example/try-broken-php-global-styles/try-broken-php-global-styles))
Ensure button styles are expressed in the theme.

## Expected behavior
Ideally the block base classes would be provided rendered inline in the same fashion for PHP rendered templates as block-based HTML templates.
Ensure a 'button' style is applied (such as background color)
Load a page rendered from a PHP template and observe the styles on a button block in the view.
![image](https://user-images.githubusercontent.com/146530/116462886-01fe2580-a838-11eb-98ad-1b1aced18e38.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/146530/116462939-15a98c00-a838-11eb-9d2a-5183d6aea88e.png)

## WordPress information
- WordPress version: latest
- Gutenberg version: trunk (10.5.0)
- Are all plugins except Gutenberg deactivated? yes

This appears to work as expected on `10.4.1`.

Also note that disabling block support in the theme also causes it to operate as expected.

`remove_theme_support( 'block-templates' );`

**Comment by pbking** [comment]
It seems that the culprit is somewhere in [this commit](https://github.com/WordPress/gutenberg/commit/7c134eb66f1e5ed67db646e19234d9edf6e3090e) adding support for block templates.

**Comment by jffng** [comment]
cc @aristath for any clues 🙏

**Comment by aristath** [comment]
@pbking I pushed PR https://github.com/WordPress/gutenberg/pull/31309
I tested with your test theme and that tweak fixes the issue. Can you please confirm that works? Thanks :+1:

**Comment by MaggieCabrera** [comment]
> @pbking I pushed PR #31309
> I tested with your test theme and that tweak fixes the issue. Can you please confirm that works? Thanks 👍

It does fix it for me on my test site!

**Comment by jffng** [comment]
Thank you @aristath !
