### ISSUE TITLE
Add Block: Heading

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#313]
## Attributes

- Alignment: Left, Right, Center.
- Heading sizes.

## Markup

```html
<!-- wp:heading -->
<h*>Heading</h*>
<!-- /wp -->
```

## States ([see all](https://wpcoredesign.mystagingwebsite.com/gutenberg/#heading))

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Heading,%20Selected.png)

**Comment by iseulde** [comment]
Just like text, would it be necessary here to add the delimiters?

**Comment by mtias** [comment]
Depends how the parsing shapes up to be. Once things are a bit more settled I'd love to have a dummy post with a few complicated combinations of markup with and without hints, and test reliability and performance.

The rendering of hints is something that could be a boolean attribute of the block definition, depending on implementation.

**Comment by aduth** [comment]
How should the heading appear if not focused and contains no text? I suppose it's the same concern for a text block as well. Currently it shows as blank nothingness, and given we've decided against block identifiers on hover, the block's identity only becomes known when selected. Do we want a placeholder? Another more obvious indicator of block type?

**Comment by jasmussen** [comment]
> How should the heading appear if not focused and contains no text?

First thought: some placeholder text. Like "Write heading...", or "Write text..." or something in that vein. 

But I do agree that an empty block like that does seem a bit weird if you insert, say, 5 heading blocks in a row. I will think further on this. It could also be an argument in favor of #447

**Comment by iseulde** [comment]
I think a placeholder is fine? It feels a bit like having image block placeholders inserted. For text maybe we shouldn't do anything? It again feels like a special case.

**Comment by jasmussen** [comment]
> I think a placeholder is fine? It feels a bit like having image block placeholders inserted. For text maybe we shouldn't do anything? 

Good point. It's also not necessarily that different from picking a headline in the current editor, on a line on which you've typed nothing.

**Comment by iseulde** [comment]
Looking into adding alignment, that will also need grouping. Other than that, what's left here for prototype parity? I also see that this block has formatting now?

**Comment by jasmussen** [comment]
> Looking into adding alignment, that will also need grouping. Other than that, what's left here for prototype parity? I also see that this block has formatting now?

Yeah it probably should not have formatting. That seems like a regression. There has also been a regression in the hover styles for the formatting buttons, which shouldn't be blue, but be outlined. But I'll take a look at that tomorrow. 

The prototype technically does have formatting, but not alignment, whereas this ticket suggests the heading should have alignment, but not formatting. Confusing indeed.

Personal opinion: switching a right aligned paragraph with lots of bolds and italics inside should left align and strip out the inline formatting, and the heading should not have either alignments or formatting.

**Comment by iseulde** [comment]
> Personal opinion: switching a right aligned paragraph with lots of bolds and italics inside should left align and strip out the inline formatting, and the heading should not have either alignments or formatting.

These may be edge cases, but I do think alignment is useful for headings. Often you'll see people who want to centre a heading, but maybe others feel too that this should be up to the theme.

I also sometimes add formatting to headings, mostly italic, which is valid, even in a WP post title.

**Comment by iseulde** [comment]
Then I think we can close this issue, and have a look at the (_looks for word that is like dropdown but different_) drop**right** in a separate issue?
