### ISSUE TITLE
Recent update erases page content

### ISSUE THREAD

**Issue by Hilary1L** [WordPress/gutenberg#31329]
## Description

updated the gutenberg plugin this morning and all content except background image disappeared from the front end, though visible in the rear-end. also, main nav menu developed scroll for drop-down items. only deactivating the plugin works to bring back content.

## Step-by-step reproduction instructions

immediately at loading home page and on any pages edited with the plugin before update

## Expected behaviour

show content
## Actual behaviour

page content hidden or missing except background image and main nav menu
## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.0 UPDATED just now to 10.5.2 and the same problem occurs!
- Are all plugins except Gutenberg deactivated? no
- Are you using a default theme (e.g. Twenty Twenty-One)? no

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox

**Comment by Hilary1L** [comment]
working now. maybe the update did the trick.

**Comment by carolinan** [comment]
Thank you for confirming, I will close the issue.
