### ISSUE TITLE
Components: Consolidate Slot Fill approaches

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3132]
Previously: #2966
Related: #3082, #3075

In #2966, a [Portal](https://reactjs.org/docs/portals.html)-based [Slot Fill implementation](https://github.com/WordPress/gutenberg/tree/master/components/slot-fill) was written in a refactor targeting the [Popover](https://github.com/WordPress/gutenberg/tree/master/components/popover) component. This replaced all usage of the [react-slot-fill](https://github.com/camwest/react-slot-fill) library in the process. However, due to specific behaviors of event bubbling differences between portals and react-slot-fill, several issues were observed (#3082, #3075) and it was later partially reverted in #3083.

The React documentation includes a section on the specific event bubbling behavior for portals:

https://reactjs.org/docs/portals.html#event-bubbling-through-portals

Effectively, the difference between portal events and react-slot-fill events is that:

- In portals, events bubble to their React parent, regardless of where the element is rendered in the DOM
- In react-slot-fill, events bubble as per their DOM position

Neither of these is necessarily "correct", and both can be desired in specific circumstances. At this time, it does not appear that we have use for the React default event bubbling behavior of Portals, but given #3082 and #3075 we clearly do have need for the DOM event bubbling behavior (toolbar containers capturing events from slotted content).

Therefore, we should decide one of:

- Enable a developer to opt in to one or the other event behaviors 
- Try to emulate the behavior of react-slot-fill DOM event bubbling with portals
- Revert to react-slot-fill entirely

Another unrelated consideration for react-slot-fill is that we have observed multiple issue where lifecycle of slot content is not always predictable since component updates are [reflected only after a subsequent state change](https://github.com/camwest/react-slot-fill/blob/f4087870aa3f74b86cb55f882e9f398586800256/src/lib/components/Slot.ts#L53). Therefore, we are motivated to either move away from the library or find a suitable fix for this issue.

**Comment by jorgefilipecosta** [comment]
I think the problem in slot-fill that makes lifecycle of slot content not always predictable is related with the library automatically assigning keys. More details in https://github.com/WordPress/gutenberg/pull/3054#issuecomment-341859255. One solution to that problem is using wrappers the library does not assign new keys to the children this may make lifecycle predictable.
