### ISSUE TITLE
Image: BlockDescription is hidden with no URL

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#3133]
## Issue Overview
If an image block has no URL, the BlockDescription is hidden.

## Steps to Reproduce (for bugs)
1. Add image block: BlockDescription is hidden
2. Choose image from library: BlockDescription is visible

## Expected Behavior
BlockDescription is visible on every block state

## Current Behavior
BlockDescription is hidden with no URL

**Comment by gziolo** [comment]
I can confirm that this error still exists

**Comment by jorgefilipecosta** [comment]
This should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3756. Thank you for your report @Soean 👍
