### ISSUE TITLE
Add a plugin to disable the block based Widgets editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31331]
## Description
We currently have ways to programatically opt out of the Widgets editor but there is no user facing feature. While themes and plugins can simply `remove_theme_support('widgets-block-editor')` but a user has no setting to turn off.

I suggest we add a setting-less plugin that when activated acts as if the theme support is removed. So, if a user needs for instance an incompatible plugin (providing essential widgets that do not work in the new block editor) they can simply install this plugin and activate it for everything to be back to "normal". 

Activating this plugin should restore:

- the Appearance > Widgets link should go to the legacy widgets editor
- the top bar [Site Name] > Widgets link should go to the legacy widgets editor
- the Appearance > Customize > Widgets should show the legacy Widgets section in the Customizer
- the Dashboard > Manage widgets should go to the legacy widgets editor.

Deactivating the plugin restores the default block based Widgets editor.

This plugin should be developed in its own repository.

**Comment by noisysocks** [comment]
I see that @hellofromtonya has created https://github.com/hellofromtonya/classic-widgets which looks great so assigning this issue to her.

Let's get that plugin published to the w.org plugin directory and transfer the repo to the WordPress organisation.

**Comment by paaljoachim** [comment]
Hmm what about a switch in the sidebar. 
As a lot of people might be using a Widget plugin that might or might not work in the new Widget screen.
There should be an obvious and easy option to switching to using the classic widget screen.
Perhaps something similar to this?

![Switch-to-Classic-Widgets-screen](https://user-images.githubusercontent.com/5323259/117043509-9cb1a500-ad0d-11eb-933f-b85344c8b41d.jpg)

This also will require a switch to the new Widget screen in the Classic Widget screen environment. 

@annezazu @bph @DaisyOlsen

**Comment by hellofromtonya** [comment]
The Classic Widgets plugin now lives in the WordPress GitHub repo https://github.com/WordPress/classic-widgets.

**Comment by hellofromtonya** [comment]
>Hmm what about a switch in the sidebar.
>As a lot of people might be using a Widget plugin that might or might not work in the new Widget screen.
>There should be an obvious and easy option to switching to using the classic widget screen.
>Perhaps something similar to this?

@paaljoachim Activating the Classic Widgets plugin disables the new block editor widgets management. No settings. Only need to install and activate. Then the previous ("classic") widgets UIs work. Does this address the concern?

**Comment by hellofromtonya** [comment]
## Testing the Classic Widgets plugin

### Testing Environment

- Classic Widgets plugin:
     - downloaded it from the GitHub repo (soon will be available through the plugins UI as I submitted it today)
     - version 0.1
- Gutenberg plugin version: 10.5.3
- WordPress version: 5.7.1
- OS : macOS Big Sur
- localhost: WP Local

Then ran a side-by-side comparison with the plugin activated and deactivated while using the Gutenberg plugin version 

### Results

![31331](https://user-images.githubusercontent.com/7284611/117070493-6e26d080-acf3-11eb-81d4-7482ad340ece.gif)

With the plugin activated: 

- [X] the Appearance > Widgets link should go to the legacy widgets editor ✅  Works
- [X] the top bar [Site Name] > Widgets link should go to the legacy widgets editor  ✅  Works
- [X] the Appearance > Customize > Widgets should show the legacy Widgets section in the Customizer  ✅  Works
- [X] the Dashboard > Manage widgets should go to the legacy widgets editor  ✅  Works

With the plugin deactivated:
- [X] restores the default block based Widgets editor  ✅  Works

## Notes

>This plugin should be developed in its own repository.

- [X] Settings-less plugin. Install and activate to use ✅  Done.
- [X] It lives here https://github.com/WordPress/classic-widgets ✅  Done.
- [X] Submit to WP.org plugins ✅  Done.

**Comment by paaljoachim** [comment]
I brought up this issue during the Open floor of the Core Editor Meeting.
Link to Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1620226617289300

What is very helpful is adding information to the Welcome panel in the Widget Screen that one can switch to using the Classic Widget screen by installing the Classic Widget plugin. As there will very likely be a lot of people who want to stick with they are used to. It gives a clear option for users. 

I believe my concern is mostly addressed.

**Comment by hellofromtonya** [comment]
Classic Widgets plugin is now available for download https://wordpress.org/plugins/classic-widgets/ 🎉

**Comment by draganescu** [comment]
Excellent news @hellofromtonya and @azaozz 🕺🏻
