### ISSUE TITLE
Nav block Post type variations display as Post link in the block sidebar (screenshot). They should probably use the title of the Custom Post Type (eg: Portfolio link)

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#31346]
> Post type variations display as Post link in the block sidebar (screenshot). They should probably use the title of the Custom Post Type (eg: Portfolio link)

These are new post type labels `item_link` and `item_link_description` and should be added during CPT registration. If we glue together two translated strings, the translation is often very poor for specific languages. CPTs with missing labels fallback to the default post or category label.

_Originally posted by @gwwar in https://github.com/WordPress/gutenberg/issues/31004#issuecomment-827740040_

**Comment by Mamaduka** [comment]
Closing the issue since the editor is no longer maintained and has been removed from the project.
