### ISSUE TITLE
Cannot add pattern within a block

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#31342]
If the user has a cover block, for example, and they want to add a pattern within that cover block, it is not an option.

I can understand if all blocks shouldn't allow patterns (the button block, for instance), but the cover block should at least be one exception as it would be useful to add column patterns within it.  

<img width="899" alt="Screen Shot 2021-04-29 at 9 32 54 AM" src="https://user-images.githubusercontent.com/1781226/116577899-bdb96680-a8c5-11eb-95e1-dc7541adab54.png">

**Comment by ntsekouras** [comment]
Hey 👋 - many blocks that have inner blocks (like Cover) can insert a pattern inside. In the gif below you can see that this is possible. One thing worths noting though is that there is a (not in depth) check that checks if pattern's blocks are allowed based on where they are going to be inserted. For example if we have in our settings/preferences some blocks that are not allowed, the patterns that include those blocks are not shown as an option. Could be that the case of the issue you're having?

![cover](https://user-images.githubusercontent.com/16275880/116684017-0ef65280-a9b9-11eb-940e-d1b7b4957782.gif)

**Comment by bradhogan** [comment]
Hey. Is there a setting that needs to be added to registered patterns to
allow them to appear as an option within blocks?

**Comment by ntsekouras** [comment]
>Is there a setting that needs to be added to registered patterns to
allow them to appear as an option within blocks?

No. The default is to show the allowed patterns where possible - there is a (not in depth) check that checks if pattern's blocks are allowed based on where they are going to be inserted.

If patterns are shown in top level and are not removed by [this filter](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#disabling-the-default-block-patterns) for example, there should be patterns available inside other blocks as well.

Of course this depends on a couple more things about what pattern is being allowed. For example in a `Buttons` block you can insert only `Button` block, so a pattern with anything else will not be shown. Also you should check the `allowed blocks` you have in `Block manager` that could affect what patterns are shown.

**Comment by bradhogan** [comment]
I guess back to the original issue though.. I do not see the pattern tab when using the Cover block, for example (see below).  This happens with just the default theme and no plugins as well.  

![bb807257-adda-4c43-8b6f-639d41075de4](https://user-images.githubusercontent.com/1781226/116898682-8ad7e100-abeb-11eb-99f0-372d18c18c02.gif)

**Comment by ntsekouras** [comment]
>and no plugins as well.

The functionality for showing patterns inside a block was added here: https://github.com/WordPress/gutenberg/pull/28459. (GB plugin v. 10.0)

Maybe you have an older WP version that doesn't contain this code?

**Comment by bradhogan** [comment]
I'm using the most recent version of WordPress (5.7.1) with no plugins active and the default Twenty TwentyOne theme (see below).  Other ideas? 

![7d54253b-aa7e-45c6-aa56-23ceeed57be9](https://user-images.githubusercontent.com/1781226/117032579-70b70500-acb6-11eb-9ef9-d34833efd318.gif)

**Comment by ntsekouras** [comment]
Yeah, as noted above this functionality was implemented in GB version 10.0.
WordPress 5.7.1 has GB versions `9.3-9.9`.

Reference: https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/

I'm closing this issue as it will be resolved with the new WP version (5.8)
