### ISSUE TITLE
Nav block/editor - can't save a post-format 

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#31348]
Currently you cannot save a post-format in navigation editor. It is very much related to https://github.com/WordPress/gutenberg/issues/31380.

Essentially we are storing an non-numeric `object_id`  because the REST API endpoint returns non-numeric IDs for post-format search results. 

As per the existing menus screen we should store the taxonomy term ID (which backs the post-format) as the `object_id` for nav_menu_items. 

<img width="608" alt="Screen Shot 2021-05-04 at 10 25 10" src="https://user-images.githubusercontent.com/444434/116984594-546d9500-acc3-11eb-8bbf-5f07e8b4e5ed.png">

To do this we need to make sure the `/v2/search` endpoint returns the term ID for us to work with. See https://github.com/WordPress/gutenberg/issues/31380 which shows what the REST API currently returns.

### How to replicate
This takes a bit of setup:

1. Activate a theme that supports post-formats, like Twenty Thirteen
2. Create some posts that use a post format like quote or gallery
3. Enable the navigation editor and create a new menu
4. Insert a post-format link (points to the post format archive). Note that this should be using the post-format variation:

https://user-images.githubusercontent.com/1270189/116439517-7e771100-a804-11eb-9a54-8ba904284db0.mp4

A custom link works out okay but we should avoid the 500 here:

| 500 | Sent values |
|-----|-----|
| <img width="1250" alt="Screen Shot 2021-04-28 at 9 30 31 AM" src="https://user-images.githubusercontent.com/1270189/116440165-0f4dec80-a805-11eb-84ae-442f20c1f928.png"> | <img width="842" alt="Screen Shot 2021-04-28 at 9 26 46 AM" src="https://user-images.githubusercontent.com/1270189/116440293-30164200-a805-11eb-91db-5c1f92a9929b.png"> |

_Originally posted by @gwwar in https://github.com/WordPress/gutenberg/issues/31004#issuecomment-828601727_

**Comment by Mamaduka** [comment]
Closing the issue since the editor is no longer maintained and has been removed from the project.
