### ISSUE TITLE
SVN Upload Workflow: `Stable tag:` isn't set in `readme.txt`

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#31357]
While releasing GB 10.5.1 and 10.5.2 today, @youknowriad noticed that the `Stable tag:` field isn't being set in the plugin's `readme.txt` in the WP.org plugin repo (SVN) anymore.

I looked at previous versions and found that the last version that had it set was [10.2.1](https://plugins.trac.wordpress.org/browser/gutenberg/trunk/readme.txt?rev=2498924) -- starting from [10.3.0](https://plugins.trac.wordpress.org/browser/gutenberg/trunk/readme.txt?rev=2506930), the `Stable tag:` was empty.

Fortunately, this seems rather low-impact, as WP.org apparently falls back to what it determines to be the latest version (probably based on release date, or version comparisons -- both of which work for GB, as per our current release procedure).

For reference, this is the code that's supposed to set the `Stable tag:`: https://github.com/WordPress/gutenberg/blob/f3c599df33c1255b43ddcbec86b504adee123de9/.github/workflows/upload-release-to-plugin-repo.yml#L149-L154

**Comment by ockham** [comment]
This seems to coincide with #28138 (or maybe #30212).

**Comment by ockham** [comment]
Upon closer inspection of the SVN log (note the `Committing version x.y.z` vs `Releasing version x.y.z` commit messages, and to which steps of the workflow they relate), I think it's probably this step that didn't work: 

https://github.com/WordPress/gutenberg/blob/f3c599df33c1255b43ddcbec86b504adee123de9/.github/workflows/upload-release-to-plugin-repo.yml#L123-L127

**Comment by ockham** [comment]
Yeah, I think I've tracked it down to here: https://github.com/WordPress/gutenberg/runs/2239867087?check_suite_focus=true

![image](https://user-images.githubusercontent.com/96308/116607667-8f25a500-a932-11eb-9a31-a0b64a76d706.png)

**Comment by ockham** [comment]
Seems like `steps.get_previous_stable_version.outputs.stable_version` was empty 🤔 

https://github.com/WordPress/gutenberg/blob/cec7a6817ac2ec37e1e7a3b314fee0b909e7bd7d/.github/workflows/upload-release-to-plugin-repo.yml#L105-L109

Could it be an issue with escaping? 🤔

**Comment by ocean90** [comment]
This needs to get fixed since currently the plugin directory simply falls back to trunk. See https://api.wordpress.org/plugins/info/1.0/gutenberg.json?fields=stable_tag,short_description where `stable_tag` is set to `trunk`.

This prevents using the [dev and stable projects for translations](https://translate.wordpress.org/projects/wp-plugins/gutenberg/) as currently only dev is used.

**Comment by ockham** [comment]
I'll look into fixing this 👍
