### ISSUE TITLE
Navigation Block: Placeholder text squished in template editing mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31352]
## Description

When using template editing mode and a new navigation block that hasn't yet been configured, the placeholder texts is squished. cc @jasmussen 

## Step-by-step reproduction instructions

1. Create a post. 
2. Enter template editing mode with a template that does not have a navigation block configured. 
3. Click into navigation block and see the text is squished

## Expected behaviour

Expect the placeholder text to be more responsive in template editing mode. 

## Actual behaviour

The text doesn't scale well/getes smushed 

## Screenshots or screen recording (optional)

<img width="795" alt="Screen Shot 2021-04-29 at 12 45 20 PM" src="https://user-images.githubusercontent.com/26996883/116602739-5a413000-a8e9-11eb-9862-b8ae2b6f61a5.png">

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by annezazu** [comment]
Working on a demo so running into more oddities and noting that this happens too:

<img width="554" alt="Screen Shot 2021-04-29 at 12 50 47 PM" src="https://user-images.githubusercontent.com/26996883/116602915-8c529200-a8e9-11eb-9207-842dbc3c4bfa.png">

**Comment by jasmussen** [comment]
Thank you. For a little more context, the placeholder lacks the responsive classes other placeholders can leverage to minimize the content when shown in constrained contexts. I'll take a look!

**Comment by jasmussen** [comment]
There's a fix for this one in #31371.

**Comment by annezazu** [comment]
Noting for now that I am seeing this in 10.6 RC:

<img width="1311" alt="Screen Shot 2021-05-06 at 12 25 15 PM" src="https://user-images.githubusercontent.com/26996883/117347283-24aac280-ae66-11eb-9fc4-be250cf4a4bc.png">

**Comment by jasmussen** [comment]
Yep, I'm afraid the PR didn't land in time for 10.6. It's milestoned for 10.7:

<img width="351" alt="Screenshot 2021-05-07 at 09 28 48" src="https://user-images.githubusercontent.com/1204802/117413794-aeb26400-af16-11eb-930d-ff2db8289f19.png">

**Comment by annezazu** [comment]
Ah! Bummer. I thought it was in for 10.6. Apologies!

**Comment by jasmussen** [comment]
Not at all. Pity we missed it!
