### ISSUE TITLE
e2e Tests: Add test for inserter drag-and-drop

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#31356]
GB 10.5.0 had a small regression related to the inserter's drag-and-drop feature (see #31319). Let's try adding some e2e test coverage for that feature (maybe to https://github.com/WordPress/gutenberg/blob/cec7a6817ac2ec37e1e7a3b314fee0b909e7bd7d/packages/e2e-tests/specs/editor/various/inserting-blocks.test.js?).

Note that it has been previously [thought to be impossible](https://github.com/WordPress/gutenberg/pull/31319#issuecomment-829042542) to cover drag-and-drop behavior with an e2e test. However, there is some prior art for blocks' drag-and-drop feature, see #26869.

**Comment by talldan** [comment]
Puppeteer now seems to support drag and drop (v10.1.0):
https://github.com/puppeteer/puppeteer/pull/7150

However, I can't get it to work 😄 

edit: got it working. The bit I was missing is that you have to do `await page.setDragInterception( true );` before any drag and drop.

**Comment by kevin940726** [comment]
I can work on this next, as now we can also test dragging files in Playwright too (#42722).
