### ISSUE TITLE
Navigation Block: Typography of placeholder changes based on Global Styles settings

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31353]
## Description

When adjusting the site's typography settings, the navigation block placeholder text also changes. 

## Step-by-step reproduction instructions
1. Use a site with FSE capabilities. 
2. Enter the site editor 
3. Add a new navigation block but do not make any changes to configure the block and keep the placeholder text open.
4. While open, make changes to the global styles typography settings and see the navigation block typography also changes. 

## Expected behaviour

Expect placeholder typography to remain the same. 

## Actual behaviour

Typography changes

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/116603504-39c5a580-a8ea-11eb-9946-41499ccdf924.mp4

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOs
- Browser: Chrome

**Comment by jasmussen** [comment]
Great ticket. Fixed by #31410.
