### ISSUE TITLE
Improve additional classes field

### ISSUE THREAD

**Issue by coreyworrell** [WordPress/gutenberg#31360]
## What problem does this address?

Makes adding custom classes more user friendly for styling options that may not fit into the other options offered by Gutenberg already.

## What is your proposed solution?

Allow user to select from available classes that the theme offers along with adding custom. Similar to how [EditorsKit](https://jeffreycarandang.com/introducing-editorskit-block-styling-utility-classes/) plugin does it by using a token field. 

![](https://mk0jeffreycaranlitd1.kinstacdn.com/wp-content/uploads/2019/08/utility-classes.png)

Having the theme provide (via JSON and/or PHP) a list of classes (with labels) and possibly by group could make this very easy.

Utility classes for padding, margin, maximum widths, etc could take advantage of this. A label could be used with the underlying value being the class itself.

![Screenshot from 2021-04-29 13-19-23](https://user-images.githubusercontent.com/162595/116613531-9d9d9d80-a8ed-11eb-8d8b-28aee2d168f6.png)

**Comment by CreativeDive** [comment]
@coreyworrell This is a fantastic idea !

**Comment by mtias** [comment]
There are several items for iteration on style variations that relate to the class field in #7551. Would you mind transferring this request there?

**Comment by coreyworrell** [comment]
@mtias okay done. thank you.
