### ISSUE TITLE
Writing flow/FSE: Clicking in the canvas padding doesn't always deselect

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#31369]
## Description

When you select a block, it's important to be able to click outside to deselect it. That generally works, but if you click right on the edge, the cursor turns to the text caret, and you actually set focus in the bottom appender:

![click](https://user-images.githubusercontent.com/1204802/116664968-74d2e200-a999-11eb-9da2-dbbbeaa8224d.gif)

This is very jarring when it happens in the post editor, as you lose your place. But more importantly in the site editor which uses all the space available, it can make it very hard to deselect any blocks at all.

The clickable space that focuses the last appender is actually the padding on `editor-styles-wrapper` — click that, and you scroll to the end of the page:

<img width="1270" alt="Screenshot 2021-04-30 at 09 52 14" src="https://user-images.githubusercontent.com/1204802/116665247-d430f200-a999-11eb-90cd-722ead1d60f4.png">

How much padding is there will vary from theme to theme, of course, but simply clicking there shouldn't make you lose your place.

## Step-by-step reproduction instructions

Go to the post or site editor, insert a bunch of content.

- Select a block and click outside, left or right to deselect it.
- Try again, but carefully move the cursor to the edge of the screen and see if it changes to the text editing caret. Click there, and observe how you're now focused in the bottom appender.

**Comment by jasmussen** [comment]
@ellatrix @youknowriad do you think this could be related to one of the recent padding refators?

**Comment by ellatrix** [comment]
I'll look into it
