### ISSUE TITLE
FSE: Impossible to set up blocks at the very top of the editor

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#31363]
## Description
I found that it's very hard or sometimes impossible to add content or configure a block placed at the very top of the page because the block toolbar is obscuring the block content. I know this is probably an edge case and something that can be fixed by adding a spacer block on top, but I thought it's still worth reporting as it makes it impossible to set up Navigation block specifically.

## Step-by-step reproduction instructions
1. Setup: a site with Gutenberg plugin and TT1 Blocks theme active.
2. Open Site Editor. Remove all the elements from the Header template part.
3. Add the Navigation block.
4. See how the toolbar obscures the block and makes it impossible to set it up add links.
5. Add Site title block above the Navigation block.
6. Note that this time the block toolbar is partially obscured, making it hard to access the controls, while it also obsures the content of the block (although in this case, you should still be able to edit the content)

## Screenshots or screen recording (optional)
Navigation block:
![MNnPoyCiwq](https://user-images.githubusercontent.com/4550351/116636136-ec0d7380-a9a3-11eb-85ff-cf7dbafedc03.gif)

Site Title block:
![image](https://user-images.githubusercontent.com/4550351/116636185-06475180-a9a4-11eb-9272-14dfdb365c5e.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: macOS 10.15.7
- Browser: Chrome 90

**Comment by Sandstromer** [comment]
Same or similiar issue to  #31008

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in #31008 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
