### ISSUE TITLE
Word Count is unreadable when there's no headings

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3136]
## Issue Overview
Clicking on the i icon to show the Word Count when there's no headings in the content, shows unreadable, overlapping text.

## Steps to Reproduce (for bugs)
1. Add a new post and don't add any headings (apart from the Post Title).
2. Click the i icon (top-right of page) to view Word/Block Count

![wordblockcountunreadable](https://user-images.githubusercontent.com/2078245/31975767-2800137a-b97f-11e7-98f8-df6848da857f.png)

_macOS Sierrra 10.12.1
Firefox 56.0 (64-bit)
Gutenberg 1.5.1_

**Comment by Soean** [comment]
Solved by #3125
