### ISSUE TITLE
Patterns: Manage Patterns similar to Reusable blocks.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31367]
## What problem does this address?

We need a way to manage Patterns and categories.

![Screen Shot 2021-04-30 at 09 22 17](https://user-images.githubusercontent.com/5323259/116662090-a053cd80-a995-11eb-94f3-3f37c3efbf36.jpg)

## What is your proposed solution?

At first to just duplicate the current Reusable block manage approach over to Patterns.

![Screen Shot 2021-04-30 at 09 24 26](https://user-images.githubusercontent.com/5323259/116662336-f32d8500-a995-11eb-8fc6-3b2d42d2b3f7.jpg)

Second iteration perhaps do something like these modal approaches I have listed here:
https://github.com/WordPress/gutenberg/issues/30192

Dependent issue:
Patterns: Create a pattern in a similar way to have we create a Reusable block.
https://github.com/WordPress/gutenberg/issues/31298

Associated:
Reusable blocks: Convert a Reusable block to a pattern. 
https://github.com/WordPress/gutenberg/issues/31296

@kjellr @melchoyce

**Comment by mtias** [comment]
This is not a priority in the immediate roadmap since patterns are moving from bundled resources to be served through the pattern directory. In the future, user stored patterns might make an appearance, but it's not at the top of the list.

**Comment by paaljoachim** [comment]
An example from Learn.
Today Learn uses a Reusable block to create a kind of layout template. To where the Workshop or Lesson plans creator will fill out the template. This is risky as one could easily overwrite the Reusable block with the contents one has added.

Being able to create a Pattern block to create a kind of layout template. There is no risk of saving the change of a pattern on top of the "global" pattern as each instance is independent of other patterns.

**Comment by mtias** [comment]
There's definitely use cases for it. Reusable blocks or patterns could be just a taxonomy of `wp_blocks` but as I mentioned elsewhere, it needs a more comprehensive overview.

**Comment by mtias** [comment]
Done in #51144.
