### ISSUE TITLE
Long date display in another language

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#3138]
## Issue Overview

The date display too long if using Vietnamese language version.

## Steps to Reproduce (for bugs)

1. Install a fresh WordPress with the Vietnamese language package.
2. Install a Gutenberg language.
3. Try to edit any post using Gutenberg editor.

## Expected Behavior

The date should be shorter and keep left spacing in almost screens.

## Current Behavior

<img width="283" alt="screenshot at oct 25 10-05-01" src="https://user-images.githubusercontent.com/10395311/31978624-6e97ee56-b96c-11e7-8cab-9b9c55311f18.png">

## Possible Solution

Try to override the short version's date. (I mean replace Month with short if possible).

**Comment by Soean** [comment]
Same problem with german.

![publish](https://user-images.githubusercontent.com/695201/31987693-e336168e-b96c-11e7-982d-9d46072f3b42.png)
