### ISSUE TITLE
Notices are obscured by the block toolbar on mobile

### ISSUE THREAD

**Issue by david-szabo97** [WordPress/gutenberg#31384]
## Description
The first notice is obscured by the block toolbar on small screens.

## Step-by-step reproduction instructions
1. Open block editor
2. Run the following code in your browser's console
```js
wp.data.dispatch( 'core/notices' ).createNotice('success', 'Hello World!')
```

## Expected behaviour
Notice should be below the block toolbar

## Actual behaviour
Notice is obscured by the block toolbar

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/2256104/116708282-d6ae3e80-a9cf-11eb-930c-acf4d75f53bf.png)

https://user-images.githubusercontent.com/2256104/116654862-4ac5f380-a98a-11eb-9096-af3e5a246302.mov

## WordPress information
- WordPress version: 
- Gutenberg version: `trunk` branch
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1B

## Device information
- Device: MacBook Pro
- Operating system: macOS Big Sur 11.3
- Browser: Google Chome latest

**Comment by Mamaduka** [comment]
Hi, @david-szabo97

I'm no longer able to reproduce this issue.

![CleanShot 2021-07-14 at 15 46 16](https://user-images.githubusercontent.com/240569/125616892-4db2e0f6-42b3-457e-bd37-2b7463c990a8.png)

**Comment by david-szabo97** [comment]
Looks like this is already fixed. Closing it.
