### ISSUE TITLE
Navigation block: allow extending the list of allowed inner blocks

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#31387]
The Navigation block has a hard-coded list of allowed inner blocks:

https://github.com/WordPress/gutenberg/blob/d77994e89c260ae09b1e4e3ffdd50871bc0b2c7d/packages/block-library/src/navigation/edit.js#L32-L38

But plugins might want to add more blocks to that list. For example, WooCommerce could add a _Product Search_ block or a minicart block (ie: a link to the Cart which shows the number of products in the cart).

If I'm not wrong, there is no way plugins can do that right now, so this issue is about making the `ALLOWED_BLOCKS` list filterable or introducing some other API so plugins can extend the list of allowed blocks inside the Navigation block.

**Comment by jasmussen** [comment]
Good ticket. There's some overlap with https://github.com/WordPress/gutenberg/issues/23745, perhaps specifically it's sort of blocked until we can take a stab at that one since the interface and rendered markup needs to be able to handle the added blocks available.

[Here's an exploration of what happens if we just allow other blocks inside](https://github.com/WordPress/gutenberg/issues/23745#issuecomment-813965553), and [here's a mockup of future menu editing](https://github.com/WordPress/gutenberg/issues/23745#issuecomment-820267638).

**Comment by mtias** [comment]
Would it make sense for the mini-cart case to define `parent: 'core/navigation'`?

**Comment by Aljullu** [comment]
> Would it make sense for the mini-cart case to define `parent: 'core/navigation'`? 

I wasn't aware that this option would work, thanks! It seems to work with Gutenberg `trunk`, but for some reason I couldn't get it to work on the latest released version (11.6.0).

The only issue of this approach, is that it doesn't allow blocks to be added inside the navigation _and_ outside of it. Ie: a _Product Search_ block could be displayed as part of the navigation or as a widget in the sidebar.

**Comment by gziolo** [comment]
> The only issue of this approach, is that it doesn't allow blocks to be added inside the navigation _and_ outside of it. Ie: a _Product Search_ block could be displayed as part of the navigation or as a widget in the sidebar.

It's an array so you could define several parent blocks where it can be inserted:

```json
"parent": [ "core/navigation", "something/else" ],
```

We discussed that the current implementation is very strict, and it would be great to provide a way to support also "grandparents, "grandgrandparent", and so on 😄 Related issue: https://github.com/WordPress/gutenberg/issues/30679.

**Comment by gziolo** [comment]
By the way, this is how allowed blocks are handled for the Columns block with `attributes`:

https://github.com/WordPress/gutenberg/blob/01ac2cfde21682b30524f5e42d8e9f734e6202c4/packages/block-library/src/column/block.json#L16-L18

Related PR: #35342.

**Comment by Aljullu** [comment]
Thanks for the links @gziolo!

> It's an array so you could define several parent blocks where it can be inserted:
> 
> ```json
> "parent": [ "core/navigation", "something/else" ],
> ```

That wouldn't still work for the usecase of the a block that I want to make available inside the Navigation block + anywhere else like the _Product Search_ block, right? Or is there a way to say that any parent is allowed (something like `"parent": [ "core/navigation", "*" ]`)?

**Comment by gziolo** [comment]
> Or is there a way to say that any parent is allowed (something like "parent": [ "core/navigation", "*" ])?

No, you need to list all parent blocks you want to support. It should be more flexible.

**Comment by kubiqsk** [comment]
Can we just add a filter hook?
Using `parent` is very limitating...
Imagine language switchers, dynamically generated category lists, more complex elements like minicarts, etc...
This is really needed, something like:
```js
...
allowedBlocks: wp.hooks.applyFilters( 'navigation_allowed_blocks', ALLOWED_BLOCKS ),
...
```
in https://github.com/WordPress/gutenberg/blob/44e3a64e6e3e453cae644ff8ebd3ffd0f2963caa/packages/block-library/src/navigation/edit/inner-blocks.js

But it would be cool to have full control over the whole menu and stop limiting block, because then you can create megamenus and more complex structures...

**Comment by gziolo** [comment]
We discuss finding a general solution to customize the list of allowed blocks for inner blocks with block attributes in https://github.com/WordPress/gutenberg/issues/15682. So far, the handling was added whenever it was requested for blocks with inner blocks. You can see it in action for the following core blocks:
- Group (https://github.com/WordPress/gutenberg/pull/49128).
- Media & Text (https://github.com/WordPress/gutenberg/pull/49981).
- Columns (https://github.com/WordPress/gutenberg/pull/25183).
- Cover (https://github.com/WordPress/gutenberg/pull/31326).

It should be fine to replicate the same approach for the Navigation block, too. It's something we definitely should support by default whenever there are inner blocks involved, as we do it for the template lock. I'm sure there are more features that would benefit from similar pattern.

**Comment by getdave** [comment]
> It should be fine to replicate the same approach for the Navigation block

The Nav block has some additional complications in that it actively manages the output of it's inner blocks in the PHP server render of the block.

https://github.com/WordPress/gutenberg/blob/01b527dae85f2e19adcc23e102cf5b9b37f163b3/packages/block-library/src/navigation/index.php#L617

**Comment by fabiankaegy** [comment]
@gziolo I tried your approach of defining `parent` on a custom block which works great for allowing you to insert that custom block into the navigation block. 

However the issue we are now running into is what @getdave described above. The navigation block does some magic to move _some_ inner blocks into a special wrapper. The list of the blocks that get this treatment is again hardcoded in PHP. 

Ideally I would love for this Array in PHP to either be filterable or for the solution to not check for the block name but instead the markup produced by the block. If the merkup is an `li` element then it should get moved into the ul. If not, it shouldn't :)

**Comment by getdave** [comment]
@fabiankaegy I think a PR which utilises the Tag Processor to find the `<li>` (rather than rely on the hardcoded list of blocks) might work well as you suggest.

**Comment by fabiankaegy** [comment]
@getdave I created a draft PR for that here: #55551 doing some final testing on my end but wanted to add it to your radar still :) Thanks for confirming

**Comment by annezazu** [comment]
Is this solved by this recent PR that adds an allowedBlocks field to block.json to specify allowed children? https://github.com/WordPress/gutenberg/pull/58262

**Comment by fabiankaegy** [comment]
@annezazu I would say so  👍 Though as mentioned in other places there still is an issue that I think needs adressing regarding the feature: https://github.com/WordPress/gutenberg/pull/55551

**Comment by Aljullu** [comment]
Oh yes, that's solved for our use case. I'm going to close this issue. Thanks for the heads-up, @annezazu!
