### ISSUE TITLE
Page Template Dropdown Disappears in wp-admin 

### ISSUE THREAD

**Issue by mmizwicki** [WordPress/gutenberg#31392]
## Description

Gutenberg Version 10.5.3 removed the Page Template drop down from the Page Attributes section on wp Pages
## Step-by-step reproduction instructions

1. Create a fresh WP install with 2021 active
2. Install Gutenberg Version 10.5.3 and activate
3. Open the Sample Page to edit and the Page Template drop down will be gone
4. Deactivate Gutenberg and the Page Template drop down will return

## Expected behaviour

Page Template drop down should be visible when Gutenberg is active
## Actual behaviour

Page Template drop down disappears when Gutenberg is active

## Screenshots or screen recording (optional)
![Screenshot](https://image.prntscr.com/image/TJ90hgZxSBCcki2Ir-t9qg.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur 11.3
- Browser: Chrome Version 90.0.4430.93

**Comment by carolinan** [comment]
Hi!
If you look on the right image you will see the template section above the permalink section. Is that section not populated?

**Comment by mmizwicki** [comment]
Ahhh...thank you @carolinan. I did not see that. You're correct. It is there and populating correctly. It's breaking my custom templates on one of my sites, but I'm unable to reproduce using 2020. So I've got something else going on I'll need to sort out. Thanks again for pointing out the new Template area.
