### ISSUE TITLE
Reusable block: Clicking name/title should bring focus to sidebar name field similar to the Navigation editor.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31391]
## What problem does this address?

Clicking the title/name opens a Transform to drop down.

https://user-images.githubusercontent.com/5323259/116752552-0841fc80-aa06-11eb-8244-76cbaf3c76e9.mp4

Other blocks one clicks the block icon to open the Transform to drop down.

https://user-images.githubusercontent.com/5323259/116755015-0aa65580-aa0a-11eb-83f2-add80425c6f9.mp4

## What is your proposed solution?

Comparing to the Navigation Editor screen.

https://user-images.githubusercontent.com/5323259/116752118-51458100-aa05-11eb-85a5-d388dcaaca6e.mp4

We see the icon to the left and clicking the "All Pages" brings focus to the Name "All Pages" in the sidebar.

For Reusable blocks:
Consistency with other blocks. 
Clicking the Reusable blocks icon should open the Transform to drop down.

Following the same method as Navigation Editor.
Clicking the name should bring focus to the sidebar name field.
It would also use a similar method as Reusable blocks work in WordPress 5.7 when the Gutenberg plugin is not activated.

Navigation Editor: Allow menu renaming
https://github.com/WordPress/gutenberg/pull/29012

@jameskoster

**Comment by jameskoster** [comment]
This is an interesting one. In many ways I see overlap with the idea of [putting post attributes in the top bar](https://github.com/WordPress/gutenberg/issues/27093).

In the short term the proposal here seems to be worth a try. But long term I think we should follow what happens with document attributes closely, and align where we can.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue. As it feels more like a sidetrack.
