### ISSUE TITLE
Gallery Block: Consider option to turn off captions on thumbnails

### ISSUE THREAD

**Issue by jerrysarcastic** [WordPress/gutenberg#31403]
## What problem does this address?

It's not the case that everyone wants image captions to appear over the individual thumbnails in the grid, and in some situations it can distract from the imagery itself.

## What is your proposed solution?

Offer a block setting for caption visibility, so captions can be turned on/off for thumbnails.  This could be considered alongside the caption options discussed in https://github.com/WordPress/gutenberg/issues/8030

**Comment by mtias** [comment]
Wouldn't just not adding a caption work?

**Comment by jerrysarcastic** [comment]
But then there would be no caption in the carousel, no?  I understand that currently they are not displayed there but I assume it's a parity issue, since captions appear in the carousel if set up using the classic editor/classic block.

Edit:  Adding to that, this was inspired by a user who wanted captions to appear in the carousel but NOT on the thumbnails

**Comment by mtias** [comment]
When you say "carousel" I assume you have something like Jetpack's feature in mind since core doesn't have any carousel functionality?

**Comment by jerrysarcastic** [comment]
Doh!  That's my bad, I had forgotten that feature is not in core.  Feel free to close this 🤦

**Comment by mtias** [comment]
No worries! :)
