### ISSUE TITLE
Important Custom Field content is hidden behind Extended Settings section

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3141]
## Issue Overview
When developers build sites for clients and utilise something like Advanced Custom Fields (ACF), the custom field content isn't considered as just secondary content. It's typically important page/post content that needs to be filled out when creating that particular page/post. This type of content shouldn't be hidden behind an _Extended Settings_ panel, especially one that is initially closed as the end user isn't going to notice it.

The user should be able to view all their custom fields upon editing their page/post.

On top of this the _Extended Settings_ section isn't scrollable which means that not all the custom fields are displayed.

The other annoying thing about having an _Extended Settings_ section that simply opens and close is that it ends up covering the rest of the Gutenberg content.

![gutenbergcustomfields1](https://user-images.githubusercontent.com/2078245/31984707-3d0c63fc-b9ae-11e7-8c3f-612f0f28f609.png)

## Steps to Reproduce (for bugs)
1. Install ACF
2. Create multiple custom fields that get added to either a Page or Post
3. Create new Page/Post or Edit existing Page/Post

## Expected Behaviour
I should be able to scroll the page to view all my custom fields

## Current Behaviour
Important page/post content is hidden from user

## Possible Solution
Add Custom Fields to bottom of editor, just like it is currently, so that it can be viewed properly and isn't hidden from the user

_macOS Sierrra 10.12.1
Firefox 56.0 (64-bit)
Gutenberg 1.5.1_

**Comment by nicolinuxfr** [comment]
Same thing here, for custom fields I created myself (using the interface in the classic editor). I thought I would see these fields in the new meta box section of Gutenberg 1.5, but I only see what plugins are adding.

Is this standard behaviour ? Should I create a plugin for these fields ? 

Here's what I have for a post, for instance :

![capture d ecran 2017-10-25 a 12 08 10](https://user-images.githubusercontent.com/2078386/31993368-36315fbe-b97d-11e7-92f0-8d116f9ee2fe.png)

**Comment by lukecav** [comment]
You can see a similar issue if you use Gutenberg with WooCommerce, when you add a new product the product data metaboxes are not visable until you click on Extend Settings, as well as the Product short description metabox not displaying.
![new product extend settings wc](https://user-images.githubusercontent.com/5797332/32001242-7307c008-b956-11e7-9a22-8847b9666520.png)

**Comment by kevinwhoffman** [comment]
I don't see the Extended Settings wrapper serving a purpose other than to obfuscate meta boxes. The appearance of an expanded Extended Settings panel looks cluttered and confusing as multiple arrows are pointing up and down at each other while sidebar arrows point right.

![image](https://user-images.githubusercontent.com/1938671/32061627-269aa04c-ba40-11e7-8a5a-728e49554496.png)

Through WordPress 4.9, the user's expectation is to see expanded meta boxes when they open the editor. We could meet that expectation by displaying the meta boxes in their expanded state as top-level sections (not buried inside the ambiguous "Extended Settings" drawer).
