### ISSUE TITLE
Featured Image: Allow free-form resizing & scaling properties

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#31418]
## What problem does this address?

The Featured Image block when used on archive pages (as part of the Query block) can help make such views much more interesting:

![115060270-aafe6500-9eb5-11eb-96db-c6e67f591226](https://user-images.githubusercontent.com/1204802/116860936-9f73a380-ac02-11eb-8346-2c14ce238d32.gif)

_GIF courtesy of @kjellr from [here](https://github.com/WordPress/gutenberg/issues/25505#issuecomment-821330496)._

However the the lack of dimension controls on the featured image block means individual image aspect ratios are unchanged, causing a bit of a jumpy layout:

<p align="center">
<img width="300" alt="Screenshot 2021-05-03 at 11 28 55" src="https://user-images.githubusercontent.com/1204802/116861118-e3ff3f00-ac02-11eb-9b49-dce08cc6d02c.png">
</p>

## What is your proposed solution?

If we enable dimension controls and allow [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) properties to be configured (defaulting to `cover`), we can enable some much more coherent and nice layouts. Shown here with some custom border radii applied as well:

<p align="center">
<img width="300" alt="Screenshot 2021-05-03 at 11 13 35" src="https://user-images.githubusercontent.com/1204802/116861278-258fea00-ac03-11eb-8860-b0a3542e01f2.png">
</p>

Here's what the featured image inspector controls could look like:

<img width="1440" alt="Featured Image" src="https://user-images.githubusercontent.com/1204802/116861641-b5ce2f00-ac03-11eb-8f47-cbe922909199.png">

**Comment by kjellr** [comment]
This might be a duplicate of https://github.com/WordPress/gutenberg/issues/27620? It's similar at least. 

I definitely like the idea of the scale control. 👍

**Comment by jasmussen** [comment]
There's definitely DNA shared between those, sorry I didn't find that older one. I'm happy to close this one in favor of it, but it might be worth doing a merge of sorts? This ticket specifically embraces the image element and object-fit property, which should be conducive to the current markup.

**Comment by kjellr** [comment]
Yeah, I think that makes sense. We can port this idea over to that issue — in general the issue is that we need _any_ sort of image controls for the featured image. 🙂

**Comment by jasmussen** [comment]
Cool I'll take a stab as soon as I have a moment, and I'll close this one. (Or feel free if you have bandwidth now)

**Comment by jasmussen** [comment]
Closing this one in favor of #27620.
