### ISSUE TITLE
Updated css of block separator introduces double lines on themes

### ISSUE THREAD

**Issue by rolf-yoast** [WordPress/gutenberg#31424]
## Description

Because of the block separator has a border on the bottom and top it can introduce doubles lines on themes that has a padding or something in the hr.

## Expected behaviour

Double lines in hr's

## Actual behaviour

A single line in hr's

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/62988563/116871907-4eb97600-ac15-11eb-9200-1f57e507517d.png)

![image](https://user-images.githubusercontent.com/62988563/116872115-a2c45a80-ac15-11eb-95fa-de62b11bfdd0.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.5.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: MacOs
- Browser: Chrome 90.0

**Comment by bobbingwide** [comment]
Reproduced on Windows with Chrome Version 91.0.4472.124 (Official Build) (64-bit)
Doesn't happen with Firefox.

Here I've got 3 separators, all defined the same, style wide.

Which line(s) appear as a double separator varies depending on the zoom level.
![image](https://user-images.githubusercontent.com/2474435/124471235-8919cd80-dd94-11eb-9b72-3f53d799d9aa.png)

**Comment by bobbingwide** [comment]
### Workaround
In  `style.css`
```
hr.wp-block-separator {
    border-bottom: 0px;
}
```

**Comment by talldan** [comment]
There is definitely top and bottom border:
https://github.com/WordPress/gutenberg/blob/a9fd325b18b2366331327e9d8d5c2811da9ffdbf/packages/block-library/src/separator/style.scss#L2-L3

Most themes I tested seem to override it or use the default block styles which seem to override it:
https://github.com/WordPress/gutenberg/blob/a9fd325b18b2366331327e9d8d5c2811da9ffdbf/packages/block-library/src/separator/theme.scss#L2-L3

@youknowriad from what I can tell the change was introduced in #30255, just wondering if you can recall what the background was?

**Comment by youknowriad** [comment]
@talldan That PR was about keeping the styles as they were but rewriting them in a way that the editor and the frontend look similarly for themes that don't provide any styles (emptytheme). So themes that add customizations, will see them also similarly in both frontend and backend. I think it's fine if we want to change these styles, we just need to make sure it's similar between frontend and editor.
