### ISSUE TITLE
Rename Post Tags block to PostNonHierarchicalTerms block and make a Post Tags variation instead.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#31422]
Right now we have two post taxonomies blocks:

 - postHierarchicalTerms
 - postTags

The former is generic and support post categories variations, the latter is specific to tags. We should consider renaming the latter and make a variation for tags to match the behavior of the hierarchical terms block.

I think this is important to do before shipping these blocks to Core. 

cc @carolinan @mtias

**Comment by mtias** [comment]
It sounds good to me though I'm a bit confused why it's called `hierarchichalTerms` when tags are not hierarchichal. Should the base block be just `postTerms`?

**Comment by youknowriad** [comment]
I was actually suggesting tags to be a variation of `postNonHierarchicalTerms` or something like that (just like categories is a variation of `postHierarchicalTerms` right now). 

Now, looking at the output of the two blocks and comparing them (categories and tags), it seems that the output is very similar regardless of whether the taxonomy is hierarchical or not. So yeah in that case a single `postTerms` block with two variations makes more sense.
