### ISSUE TITLE
adjust the margin

### ISSUE THREAD

**Issue by bakoorahnin** [WordPress/gutenberg#31437]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- WordPress app version:

**Comment by talldan** [comment]
@bakoorahnin Seems like this issue is lacking any detail, so I'm closing it down.
