### ISSUE TITLE
Extending the core/link Format

### ISSUE THREAD

**Issue by TeamDNK** [WordPress/gutenberg#31432]
## What problem does this address?
Currently there is no way of extending the core/link format. In any rich-text block such as the paragraph block, there is no way of adding a target, rel, class, or data attributes that is necessary for anything beyond a simple link. Being able to extend the core/link popover would allow for much needed attributes on the <a> element. This would also be beneficial in blocks such as the image block where we may want the image to have additional attributes.

## What is your proposed solution?
Introduce a new block filter that allows extending the Popover of the core/link format as well as the link function on the other blocks such as the image block.

**Comment by skorasaurus** [comment]
Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/16929 and https://github.com/WordPress/gutenberg/issues/23011. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
