### ISSUE TITLE
ACF Plugin settings exposed when editing page/post content

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3143]
## Issue Overview
When using a plugin like Advanced Custom Fields (ACF), it has its own edit screens for setting up and defining the custom fields that you want to display on your page/post. When editing your page/post content, you then see the custom fields that you defined.

When editing your page/post in Gutenberg, it's exposing functionality that would allow the user to edit the actual custom fields, rather than just allowing them to add content into those fields.

![gutenbergcustomfields2](https://user-images.githubusercontent.com/2078245/31985103-a5ff1a0c-b9af-11e7-9155-65d920497e66.png)

As shown in the above image, the Edit field group icon should never get displayed in the actual page/post where the custom fields are being displayed. After clicking this icon, you end up with the plugin settings being displayed in an iframe on the edit page/post screen.

![gutenbergcustomfields3](https://user-images.githubusercontent.com/2078245/31985340-7c056e80-b9b0-11e7-96f1-f6ca56291297.png)

## Steps to Reproduce (for bugs)
1. Install ACF
2. Create multiple custom fields that get added to either a Page or Post
3. Create new Page/Post or Edit existing Page/Post
4. Click Edit field group icon

## Expected Behaviour
I should never be able to edit the actual custom fields from within the page/post edit screen

## Current Behaviour
Displays plugin setting pages within page/post edit screen

_macOS Sierrra 10.12.1
Firefox 56.0 (64-bit)
Gutenberg 1.5.1_

**Comment by tmconnect** [comment]
As I know this has nothing to do with Gutenberg. It's a standard button of ACF and is shown on classic editor as well. The only strange behavior is that the Edit Field Group page is opened in an iframe (in classic mode it's loaded on a new page)

**Comment by maddisondesigns** [comment]
@tmconnect Ahhh you're right about that. I've been using ACF for years and I've honestly never noticed that Edit field group icon was available. So yep, the main issue here is that it opens the settings in an iFrame rather than navigating to that page. Thanks for pointing that out.

**Comment by youknowriad** [comment]
Let's close this in favor of #3242
