### ISSUE TITLE
Block editor

### ISSUE THREAD

**Issue by bakoorahnin** [WordPress/gutenberg#31435]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by annezazu** [comment]
Similar to your other issues, please provide more context as to what you are reporting. Currently, these are not actionable issues and will be closed out unless you can provide more information. Thank you!
