### ISSUE TITLE
Gutenberg plugin 

### ISSUE THREAD

**Issue by bakoorahnin** [WordPress/gutenberg#31434]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by annezazu** [comment]
@bakoorahnin hey there! Can you please provide more information here (what the problem is? what version you're using? etc)? Otherwise, we'll need to close this out :)
