### ISSUE TITLE
Use of the 'main' wrapper element in group block causes invalid blocks when no unfiltered_html rights

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#31443]
## Description
With the addition of a `main` element wrapper in https://github.com/WordPress/gutenberg/pull/28576, and also in the query [block pattern template](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-patterns.php#L91), it is possible for a user without `unfiltered_html` permissions to add a group block, or query block in fse, and have the block show as invalid when the page is reloaded.

## Step-by-step reproduction instructions

- In an WP env with Gutenberg plugin installed add a user with `author` permissions
- Log in as that user and add a group block and set the wrapper as `main` under Advanced settings
- Save the post and reload

<img width="964" alt="Screen Shot 2021-05-04 at 4 49 02 PM" src="https://user-images.githubusercontent.com/3629020/116961906-aa106480-acf8-11eb-9df7-de999228e586.png">

The same things happens by default for site admins on multiuser sites where admins do not have unfiltered_html rights.

## Expected behaviour
Either the main tag should not be used on user modifiable blocks, or it should be added to `wp_includes/kses.php` `$allowedposttags`.  

It seems like having `main` as an option on group makes it possible to go against its purpose in accessibility terms of being the 'single' main container of content on the page. While it is hidden under advanced in group, it is currently the default setting in the query blocks which makes it easier for a user to inadvertently add in multiple places on a page, or for a multisite admin user to add it and wonder why it invalidates.

Raising here first to see if it is intended to keep this as a user definable wrapper for group blocks before opening a ticket to see if it should be added to `$allowedposttags`.

**Comment by youknowriad** [comment]
Hi there! is there any reason why this tag is not allowed in Kses? Aside maybe the fact that it didn't exist when these rules were written?

It sounds to me that the path forward is a ticket in Core to allow this tag.

**Comment by glendaviesnz** [comment]
> is there any reason why this tag is not allowed in Kses?

Good question, I was hoping someone here would know. I will go ahead and open a ticket in Core and see what the response is.

**Comment by glendaviesnz** [comment]
Core ticket added at https://core.trac.wordpress.org/ticket/53156

**Comment by glendaviesnz** [comment]
Will close for now, will re-open if any issues with getting the tag added in Core.
