### ISSUE TITLE
Creating a reusable block inside group in group block crashes the block

### ISSUE THREAD

**Issue by leutrimhusaj** [WordPress/gutenberg#31457]
## Description
If you have a group block inside a group block and want to convert a block inside those to a reusable block, it crashes the created reusable block.
When you save the page the reusable block is created and the reference inside the page is correct but the crash after saving seems like a bug.

## Step-by-step reproduction instructions
1. Create a group
2. Create a group inside the group
3. Create a heading/paragraph block in side the nested group
4. Save the page and reload it!!! If you try the next step without saving it will work!
5. Now try to convert the heading/paragraph block to a reusable block
6. The block will crash

## Expected behaviour
The created reusable block shouldn't crash!

## Actual behaviour
The reusable block on a saved page crashes after creation but everything has been created correctly!

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/5269059/116999694-44b07980-ace0-11eb-884c-34022e82291f.mov

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: 10.5.0
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOS BigSur 11.3 
- Browser: Chrome 90.0

**Comment by carolinan** [comment]
Hi
I have not been able to reproduce this with WordPress 5.7.1 and 10.6 RC 1 of Gutenberg with Twenty Twenty-One

**Comment by leutrimhusaj** [comment]
Oh wow yes, it seems like the bug is fixed with 10.6-RC1.
I still can reproduce this with 10.5.3 for example.
But then i will close this and wait for the new release :) Thank you for retesting @carolinan
