### ISSUE TITLE
Navigation Screen: add new pages indicator

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#31451]
When a user clicks the "Add new pages" toggle to add future pages to their menu, there isn't an immediate reflection in the preview. I'd like to propose adding a message at the bottom of the navigation to indicate that new items will be appended there.

Here's a possible solution for this improvement:

https://user-images.githubusercontent.com/4933/116981311-9bf62000-acc7-11eb-832b-fe673084716b.mov

**Comment by mtias** [comment]
How would this one work on the horizontal navigation block in the site editor?

**Comment by javierarce** [comment]
That's a good question. I didn't address it here because I wasn't thinking about touching the Page List block. If I'm not mistaken, in the Site Editor the only way to auto add new pages is through that block, while here there's also the option to check the "Add new pages" toggle.

Maybe I'm rationalizing this too much to suit my argument 😅, but I also think that the nature of this menu (which works more as an abstraction than a WYSIWYG sort of thing) allows for this type of element, whereas the Site Editor tends to work as a reflection of the final product.

**Comment by javierarce** [comment]
I'm closing this issue since the navigation screen is no longer actively developed.

Related: https://github.com/WordPress/gutenberg/issues/43620.
