### ISSUE TITLE
Minimize mouse interactions with extended / "slash commands"

### ISSUE THREAD

**Issue by greenphp** [WordPress/gutenberg#3145]
It's already possible to change the type of a gutenberg block using the / slash command autocomplete.
The following idea extends the function with the possiblity to append blocks and insert blocks between content. This could help to minimize the time, the user have to use the mouse to interact with the GUI.

**Usecase 1: "Convert gutenberg block type" (already implemented)**

- User writes: "/paragraph"
- Result: If the user selects "Paragraph" from the "slash commands" dropdown, it sets current block to "wp:paragraph"

**Usecase 2: "Append gutenberg block"**

- User writes: "This is the first paragraph. Following I plan to add an image! /image"
- Result: If the user selects "Image" from the "slash commands" dropdown, it appends a new "wp:image" block and sets the focus to the new image block upload button!

**Usecase 3: "Split gutenberg blocks"** (See screenshot)

- User writes text: "This is the first paragraph. /paragraph Following I plan to add an image!"
- Result: If the user selects "Paragraph" from the "slash commands" dropdown, the block is splitted into: 1: wp:paragraph (This is the first paragraph.), 2: wp:paragraph (Empty + FOCUS), 3: wp:paragraph (Following I plan to add an image!)

![idea-slash-autocomplete](https://user-images.githubusercontent.com/827658/31993430-64b035f4-b97d-11e7-9ea1-69cece16f12c.jpg)

**Comment by Soean** [comment]
Hey @greenphp,
thanks for your ideas, but I think the use cases are already possible with the keyboard.

**Usecase 2**: You can press "tab" and "enter" to open the inserter.

**Usecase 3**: If the user press "enter" in a paragraph block, it creates a new paragraph block.

**Comment by greenphp** [comment]
Hi @soen.
Thank you for the hints. I'm not sure, if these can really accomplish the goals.

**Usecase 2:** 

I was not aware of this _"tab -> enter -> search -> select-with-mouse"_ (try "image") combo, but it feels a little bit strange and not really intuitive for me. The benefit of the "slash commands" is, that you can complete navigate them by keyboard. With this "tab" feature, you have to use the mouse at some point.

I thought, it's nice to use the same "slash command" technique to insert, append and split blocks, so it's easier for users to adapt.

**Usecase 3:**

In my simple example I inserted a paragraph-block, but the idea is, that you can insert **any kind of blocks** with this function. Example text: "This is the nice youtube video: _/youtube_ Some additional text about ...."

**Comment by greenphp** [comment]
@Soean 

Ok, I have to admit, that your suggested "tab" inserter is a really good solution. 👍 This works fine for me now. Usecase 3 is indeed an edge case and could be accomplished like you suggested.

Thank you again for the hint.

**Comment by mtias** [comment]
Thanks for the feedback. Seems the use-case can work already — you can also just hit enter two times to create an empty block and use the auto-complete there. Feel free to open new issues if you have further suggestions.
