### ISSUE TITLE
Issues with creation of custom block templates in classic themes

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#31479]
## Description
In https://github.com/WordPress/gutenberg/pull/30438, `add_theme_support( 'block-templates' );` was added by default for all themes.

For a theme, especially those that are custom developed for customers/clients, block templates may _not_ display properly or have the same functionality.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Enable Twenty Eleven (useful example)
2. Create a page and a custom block template for that page.
3. View the page and compare the styles and markup to a page not using the template. 
4. Note the main stylesheet doesn't load and markup is not the same as the default page.

## Expected behaviour

My inclination is that `block-templates` will not be available in "classic" themes by default.

## Actual behaviour

- Stylesheet doesn't load in all themes resulting in a mismatch of front end and back end styles. Is the intent that the theme style sheet (and any that use that as a dependency) should load on pages using a custom block template? It does not load in Twenty Ten or Twenty Eleven. It does not load in Genesis Framework child themes at present. (We currently enqueue our style sheet on `genesis_meta`.)
- Even if the above is fixed, selectors may have been necessary to override an opinionated style. Theme styles that are dependent on a container that isn't present on block-templates don't display as expected on the front end. 

Based on my limited testing so far, it could be a heavy lift to test and update for this feature. It isn't feasible to remove theme support in every theme where it isn't desirable.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes & No

**Comment by youknowriad** [comment]
The template editing mode is now disabled by default. You can opt-in into it with two ways:

 - Add the theme support flag
 - Embrace the theme.json config
