### ISSUE TITLE
Full site editing enabled with no way disabling it (recent Gutenberg plugin)?

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#31474]
## Description
After updating the Gutenberg plugin to latest release, Full Site Editing seems to be enabled by default.
The site doesn't work anymore, all pages result in a `no matching template found` error message.
How can I disable Full Site Editing again? I can't find an option in the Gutenberg experiments option page.

## Step-by-step reproduction instructions
1. Ensure that the latest Gutenberg plugin is installed and enabled.
2. Notice that now any page results in the `no matching template found` error message.

## Expected behaviour
Site doesn't completely break after Gutenberg plugin update.

## Actual behaviour
Site completely breaks after Gutenberg plugin update.

## WordPress information
- WordPress version: `5.7.1`
- Gutenberg version: `10.5.3`
- Are all plugins except Gutenberg deactivated? `No`
- Are you using a default theme (e.g. Twenty Twenty-One)? `No`

**Comment by vdwijngaert** [comment]
Hey @strarsis, I think this might be related to https://github.com/WordPress/gutenberg/issues/31399. I encountered the same errors as you have while troubleshooting that issue. A fix is under way in https://github.com/WordPress/gutenberg/pull/31478, and should be published asap. Can you see if the PR fixes it for you?

**Comment by vdwijngaert** [comment]
Can see if the last update fixes your issue?

**Comment by strarsis** [comment]
@vdwijngaert: Yes, issue is fixed when I install the Gutenberg plugin built from `trunk`.

**Comment by vdwijngaert** [comment]
Great! We already pushed a [new version](https://wordpress.org/plugins/gutenberg/) of the plugin, so I'd suggest using that one, as trunk can be unstable.
