### ISSUE TITLE
Feedback on extending core blocks documentation

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#31475]
## What problem does this address?
There is no trivial mechanism to extend a core block.

## What is your proposed solution?
Add an API mechanism to extend an existing core block.

Example: Custom block that should have the same features as a `core/cover` block (alignment, content position, ...) but custom/complex background content.

**Comment by grogou** [comment]
Hi @strarsis  

It maybe can helpful for you.

https://jeffreycarandang.com/extending-gutenberg-core-blocks-with-custom-attributes-and-controls/

**Comment by strarsis** [comment]
@grogou: Thanks, yes, this goes into the right direction.
However, I want to add something as sibling to the `InnerBlocks` element, like an element as a complex/custom background.
The encapsulation approach doesn't appear to add this is a sibling. But I need to try, maybe it still works in the DOM...

**Comment by grogou** [comment]
IDK i have one issue opened. https://github.com/WordPress/gutenberg/issues/31505

**Comment by mkaz** [comment]
> There is no trivial mechanism to extend a core block.

Though it may depend on your definition of trivial, see [Block Filters documentation](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/) as a means to extend core blocks.

However, your example makes me think you really want to use standard components, see the [supports documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/) for implementing some standard block toolbars.

Let us know if that answers what you are looking for, or add some more specific info on what you are trying to do and we can help.

**Comment by annezazu** [comment]
@strarsis Hope it's okay I jumped in to rename the issue and add in some new labels to move this forward. As @mkaz said, any additional context you can give here for what you'd like to see would be great. Additionally, I welcome your thoughts on this overview issue around block documentation: https://github.com/WordPress/gutenberg/issues/22151 The work has stalled out a bit there but it would be great to have you share.

**Comment by priethor** [comment]
Let's close this issue as we are unable to move forward and the activity has stalled. Feel free to reopen if the issue resurfaces.
