### ISSUE TITLE
Post featured image overflows sidebar controls

### ISSUE THREAD

**Issue by ribaricplusplus** [WordPress/gutenberg#31470]
## Description

Uploading a big featured image causes it to overflow sidebar controls.

## Step-by-step reproduction instructions

1. Download this image that I used: https://unsplash.com/photos/hSh_X3kJ4bI
2. Setup a clean WordPress installation and open a post. You'll need to be able to upload big files which `wp-env` doesn't allow by default (for now). You can use [my fork](https://www.npmjs.com/package/@ribarich/wp-env) of `wp-env`, or make it possible to upload big files in some other way.
3. Set the image downloaded in step 1 as featured image
4. See that it overflows 

## Screenshots or screen recording (optional)

Screenshot of controls being overflown:

![2021-05-04_19-18](https://user-images.githubusercontent.com/43731400/117044673-fd8dad00-ad0e-11eb-929d-1bd7a2285da1.png)

## WordPress information

- WordPress version: 5.7.1
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information

- Device: Desktop
- Operating system: Debian
- Browser: Chromium 89

**Comment by skorasaurus** [comment]
I've experienced this in Gutenberg 10.9.2.

**Comment by ntsekouras** [comment]
👋 - I can't reproduce this... Is this still happening for you?

**Comment by ribaricplusplus** [comment]
Couldn't reproduce it anymore either on WordPress 5.9-alpha-51415 no Gutenberg installed.

Closing.
