### ISSUE TITLE
Font Family: make it work like any other block support with presets

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#31489]
The block supports mechanism works by attaching classes (when the property has preset values such as colors or font-sizes) or inline styles (when it doesn't such as line-height or when the user selects custom values for colors or font-sizes).

The link color was an exception to this model because it addresses the inner markup of a block. We experimented with using CSS Custom Properties for that one but that approach had some issues and we're now exploring an alternative at https://github.com/WordPress/gutenberg/issues/31488

The font family also uses CSS Custom Properties but there's no reason it shouldn't work like the rest of the block supports with presets. We should make it work like the rest in preparation for stabilizing it https://github.com/WordPress/gutenberg/issues/31416#issuecomment-831904219

**Comment by youknowriad** [comment]
I think this one is still experimental right? So we can remove it from the 5.8 must haves?

**Comment by oandregal** [comment]
Yes, forgot about the board (had already triaged it at https://github.com/WordPress/gutenberg/issues/20331).

**Comment by ockham** [comment]
(Some WIP here: #31910)
