### ISSUE TITLE
Link editor: Show full URL in picker

### ISSUE THREAD

**Issue by richardmtl** [WordPress/gutenberg#31482]
## What problem does this address?

I have several URLs that start the same on my site. 

<img width="378" alt="Screen Shot 2021-05-04 at 6 54 11 PM" src="https://user-images.githubusercontent.com/3676359/117079621-22cbec80-ad0a-11eb-98a4-c37c775eb9d9.png">

I'm looking for one in particular, but how do I know which one to pick between the 3 different `/metro/metro-line...` options? Trial and error is my only choice at this point.

## What is your proposed solution?

At the very least, I'd like to see the full URL if I hover over it. Another possible solution is to expand the box to show the full URL no matter how long it is (you can impose a width limit and have it word-wrap, maybe?).

**Comment by vdwijngaert** [comment]
I agree. This needs to have a tooltip while hovering the URL. At first sight, this could be implemented by adding a `title` attribute to the element containing the URL: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/block-editor/src/components/link-control/search-item.js#L46

I'm not sure about the accessibility best practices on this, so some feedback on that is welcome.

**Comment by skorasaurus** [comment]
related https://github.com/WordPress/gutenberg/issues/21100 ; perhaps could adopt some logic from this.

**Comment by getdave** [comment]
This should no longer be an Issue as it was fixed in https://github.com/WordPress/gutenberg/pull/33753
<img width="693" alt="Screen Shot 2021-09-23 at 10 36 15" src="https://user-images.githubusercontent.com/444434/134485494-7db81bf2-cdb2-4272-bf62-1b5b50e46366.png">
