### ISSUE TITLE
Add Font Family Select to Headings

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#31481]
## What problem does this address?
Many sites we support require a different font family for headings than paragraphs. There is currently no font-family selector for headings.

## What is your proposed solution?
Add a "Font Family" selector for headings, like the buttons block has a Font Family selector.

**Comment by vdwijngaert** [comment]
Hey @bbertucc, good news: work is already under way to implement in Gutenberg, with the _global styles_ feature.
