### ISSUE TITLE
Convert a Classic Block into Multiple Blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3149]
Let's leverage the pasting instructions we have for converting WordPress content into blocks, to add an action to the "Classic Block" that would transform a single legacy post into multiple blocks:

![image](https://user-images.githubusercontent.com/548849/32002282-6a80ac6a-b99c-11e7-8701-771f7a62d64f.png)

**Comment by aduth** [comment]
Related: #2454

**Comment by ephox-mogran** [comment]
This might be the kind of action that you may want a preview for (before it executes). Allow the user to see how the block identification is going to work, or whether they will lose a lot of their content.

**Comment by vedranmiletic** [comment]
This is available (at least) in 1.7.0, but YouTube embed gets lost during conversion. Is that a known issue? I know this is rather specific issue; I tried searching before reporting this, but found nothing related.

**Comment by aduth** [comment]
Should this be closed by #3179?

Maybe creating a separate issue for the problem described by @vedranmiletic in https://github.com/WordPress/gutenberg/issues/3149#issuecomment-345456370.

**Comment by iseulde** [comment]
@vedranmiletic This should be fixed by #3326 in the next version.

**Comment by vedranmiletic** [comment]
@iseulde Wow, before I even reported it. Thanks!
