### ISSUE TITLE
Navigation block should always be selected.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#31508]
## Description
On the Navigation editor screen you can only add a `core/navigation` block at the root level. This is by design.

However, it is possible to end up with no block selected and `No block selected` being shown in the right hand side sidebar.

## Step-by-step reproduction instructions

* Go to `/wp-admin/admin.php?page=gutenberg-navigation`.
* Create Menu and add items.
* Click in the gray area around the outside of the Nav block.
* See block becomes unselected and `No block selected` shown in sidebar.

## Expected behaviour
Navigation block remains selected/active at all times. 

## Actual behaviour
It is possible to be in a state where no blocks are selected.

## Screenshots or screen recording (optional)

<img width="1118" alt="Screen Shot 2021-05-05 at 16 54 48" src="https://user-images.githubusercontent.com/444434/117171257-9fba9d00-adc2-11eb-9111-ae84516bced2.png">

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by Mamaduka** [comment]
Related #30325.
