### ISSUE TITLE
Add best practice guidance for the group block element selector

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#31502]
## What problem does this address?
#28576 introduce an element selector to the group block to allow a user to change the container element within a user created template.

![106254186-19217d00-6221-11eb-892d-a35f4d2e2757](https://user-images.githubusercontent.com/359867/117145870-9d841e80-ad81-11eb-8270-f27b3d0645ba.png)

While this is great for flexibility, there is no guidance around purpose or proper use of each element and could lead users to construct pages with bad structure and accessibility.

For example, each document must not have more than one `<main>` element. Another example is that the `<header>` element could also be easily confused with the page's actual "header" area, but it's not meant to designate a new section on the page (it will not be reflected as a new section in the outline). Instead it should represent a header for the surrounding section.

## What is your proposed solution?
At the minimum, I think a description of the selected element (potentially with suggested best practices) should be added to the selector. This would provide the user with some clarity and guidance as to how the element can be properly utilized.

At the most, I think we could explore adding some contextual hints to the user. Something that came to mind for me was when a user is warned that the selected colors for a block could potentially be hard for people to read. For the `<main>` element, a warning like this could be displayed if more than 1 `<main>` tag is detected in the page.

![Screen Shot 2021-05-05 at 09 19 43](https://user-images.githubusercontent.com/359867/117147302-1f287c00-ad83-11eb-9bf3-02cd10694c0e.png)

**Comment by desrosj** [comment]
Related: #31421.

**Comment by getdave** [comment]
This sounds like a reasonable idea to me. Different descriptive text per element with links to further information - ideally on WP.org but otherwise on another site.

**Comment by carolinan** [comment]
This is used in 3 blocks, but with different elements available.
In case of the template part, the `<header>` element is not meant to be inside another element, it is meant to be the banner role, the site header. And the footer is for the site footer, the contentinfo role.
Since template parts are not always available, the header element is also available for the group.
