### ISSUE TITLE
Change blocks markup

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#31505]
Hi guys. You do amazing plugin, thx for that so much.
## What problem does this address?
I need to understand, can we somehow change core blocks markup, both sides ( editor, front ).
## What is your proposed solution?
Do we have some filter to do that or it is not possible.

for example we have an image block.
```
<figure class="wp-block-image size-large">
     <img loading="lazy" src="" alt="" class="wp-image-1382" srcset="" sizes=""/>
</figure>
```

can I chnage it like 
```
<figure class="wp-block-image size-large">
     <div class="example_class">
           <img loading="lazy" src="" alt="" class="wp-image-1382" srcset="" sizes=""/>
     </div>
</figure>
```

I know we have `editor.BlockEdit` and `blocks.getSaveContent` but i cant do it with this filters, maybe i am wrong and it is possible. If it is true, can you plz help me with this problem. 

I just think it is Wordpres, we can change everyting and it is Wordpress main advantage․

**Comment by mkaz** [comment]
Yes, you can alter the core blocks using block filters, ([documentation](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/)), though this can be a bit tricky and maybe dangerous.

For example, hooking into the `blocks.registerBlockType` function you can alter any settings of a core block, allowing you to override attributes, edit, and save functions. I do this for my code-syntax-block by extending the core/code block and adding additional attributes and altering the edit/save functions. You can [see the code here for an example](https://github.com/mkaz/code-syntax-block/blob/trunk/src/index.js).

**Comment by grogou** [comment]
Thank you @mkaz it will be helpful for me. But yes it is dangerous. We need to watch every block update to have up to date overridden block. Is you have plans to have some filters or something else to not override block in future?

**Comment by mkaz** [comment]
For my code block, the other option would be to create my own block, instead of overriding core, there are benefits to that but I prefer the core method because it allows a fallback if the plugin is removed, plus easier to add the feature to existing code blocks. This isn't always the case, it'd depend on your needs.

**Comment by annezazu** [comment]
Since Marcus chimed in with some context, I'm going to go ahead and close this out! Happy to re-open if anyone feels there's anything left to be addressed. Thanks for the kind words about the Gutenberg plugin :)
