### ISSUE TITLE
remove_theme_support('core-block-patterns') ignored

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#31510]
I have the following in my theme functions file: 

```
add_action( 'after_setup_theme', 'my_theme_setup' );
function my_theme_setup(){
	remove_theme_support( 'core-block-patterns' );
}
```

And all of the Patterns still appear. 

WP: 5.7.1
Gutenberg: 10.5.4
Macbook Pro 
Chrome 90.0.4430.93

Cheers,
Brad

**Comment by skorasaurus** [comment]
confirmed on 
WP: 5.7.1 and gutenberg: 10.5.4 with twenty-twenty theme.

**Comment by youknowriad** [comment]
This sounds related to the addition of the new block patterns cc @MaggieCabrera

**Comment by MaggieCabrera** [comment]
> This sounds related to the addition of the new block patterns cc @MaggieCabrera

Thanks! I'll have a look
