### ISSUE TITLE
YouTube embed block not editable in Custom post type

### ISSUE THREAD

**Issue by danstramer** [WordPress/gutenberg#31521]
## Description
After inserting a YouTube embed block, clicking it does not open the editing options (to replace the embed URL)

## Step-by-step reproduction instructions
1. Go to a CPT in the site
2. add a YouTube embed block
3. add url to the block
4. Click embed
5. Update/publish page
6. Refresh the page
6. Go back to the block and click it in order to edit the embed link
7. block does not allow to edit the url

The only way to edit the block is via the block navigation

## Expected behaviour
when clicking on the block, will be able to edit the url

## Actual behaviour

clicking on the block does not allow to edit the URL

## Screenshots or screen recording (optional)

See video screen recording here:
https://www.dropbox.com/s/wfuwwyy2ig5k3lc/embed-block.wmv?dl=0
## WordPress information
`
### wp-core ###

version: 5.7.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/dermaspark/public_html/academy
wordpress_size: 48.94 MB (51314649 bytes)
uploads_path: /home/dermaspark/public_html/academy/wp-content/uploads
uploads_size: 2.16 MB (2263071 bytes)
themes_path: /home/dermaspark/public_html/academy/wp-content/themes
themes_size: 5.67 MB (5944238 bytes)
plugins_path: /home/dermaspark/public_html/academy/wp-content/plugins
plugins_size: 65.31 MB (68480845 bytes)
database_size: 6.50 MB (6815744 bytes)
total_size: 128.57 MB (134818547 bytes)

### wp-active-theme ###

name: DermaSpark Academy (ds-academy)
version: 0.1
author: Thomas Usborne
author_website: http://edge22.com
parent_theme: GeneratePress (generatepress)
theme_features: core-block-patterns, automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, custom-logo, menus, editor-style, widgets
theme_path: /home/dermaspark/public_html/academy/wp-content/themes/ds-academy
auto_update: Disabled

### wp-parent-theme ###

name: GeneratePress (generatepress)
version: 3.0.3
author: Tom Usborne
author_website: https://tomusborne.com
theme_path: /home/dermaspark/public_html/academy/wp-content/themes/generatepress
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (15) ###

Advanced Custom Fields PRO: version: 5.9.5, author: Elliot Condon, Auto-updates disabled
Contact Form 7: version: 5.4.1, author: Takayuki Miyoshi, Auto-updates disabled
Custom Post Type UI: version: 1.9.1, author: WebDevStudios, Auto-updates disabled
GenerateBlocks: version: 1.3.3, author: Tom Usborne, Auto-updates disabled
GP Premium: version: 2.0.2, author: Tom Usborne, Auto-updates disabled
Kadence Blocks – Gutenberg Blocks for Page Builder Features: version: 2.0.3, author: Kadence WP, Auto-updates disabled
MainWP Child: version: 4.1.6.1, author: MainWP, Auto-updates disabled
Members: version: 3.1.5, author: MemberPress, Auto-updates disabled
SVG Support: version: 2.3.18, author: Benbodhi, Auto-updates disabled
Ultimate Member: version: 2.1.19, author: Ultimate Member, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.16.56, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
Wordfence Security: version: 7.5.2, author: Wordfence, Auto-updates disabled
WPS Hide Login: version: 1.8.5, author: WPServeur, NicolasKulka, wpformation, Auto-updates disabled
WP Show Posts: version: 1.1.3, author: Tom Usborne, Auto-updates disabled
Yoast Duplicate Post: version: 4.1.2, author: Enrico Battocchi & Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-1160.11.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.76.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.34
client_version: mysqlnd 7.4.16

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/dermaspark/public_html/academy/wp-content
WP_PLUGIN_DIR: /home/dermaspark/public_html/academy/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: Windows 10
- Operating system: 
- Browser: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by annezazu** [comment]
@danstramer Thanks for reporting this! While looking at your video, it looks like you have some additional plugins interacting with this YouTube embed and adding a container around that seems to likely be conflicting with the embed block. Can you try disabling all plugins temporarily to see if the problem persists?

**Comment by danstramer** [comment]
Hi, I have also tried this on a twenty twenty fresh install. Without plugins in a CPT. 

Dan Stramer 
www.dmdesign.co.il
647-544-2912

**Comment by danstramer** [comment]
Any updates? Thanks

**Comment by annezazu** [comment]
@danstramer No updates yet! I am going to change the labels though thanks to your additional information. Thanks for following up.

**Comment by zachatkinson** [comment]
I'm not able to edit these either, not even in CPT.  Just a normal page.  If I have a caption I can click on that, then select the video. If there is no caption there is no way to select the video. Strange!

**Comment by annezazu** [comment]
This appears to be the same problem as described in this issue: https://github.com/WordPress/gutenberg/issues/30663 I imagine the underlying problem is the same: the embed block is having issues in other contexts. I'm going to close this out as a result but feel free to re-open if this doesn't match.

**Comment by danstramer** [comment]
The problem described in https://github.com/WordPress/gutenberg/issues/30663 is that videos are not showing. Here, the problem is different. The videos are showing, but cannot be edited (the embed url) when clicking on the block. As you can see in the screen recording: https://www.dropbox.com/s/wfuwwyy2ig5k3lc/embed-block.wmv?dl=0

**Comment by zachatkinson** [comment]
Agreed with @danstramer. The behavior I'm seeing is exactly the same as his video.  Video shows and not editable unless I use the block explorer button.

**Comment by annezazu** [comment]
Looking at the video once more, can you share whether you all are using any additional plugins alongside Gutenberg? I ask because there appears to be a container block interfering with the functionality that seems separate from the Embed block.  Thanks for following up <3
