### ISSUE TITLE
Some items listed in changelog for v15.0.0 of @wordpress/scripts package not in release

### ISSUE THREAD

**Issue by pierlon** [WordPress/gutenberg#31526]
The following items listed in the [changelog](https://github.com/WordPress/gutenberg/blob/5fb790205a706cd69dca6cfd4d760d40a5d6b0b6/packages/scripts/CHANGELOG.md) for the `@wordpress/scripts` package are not included in the latest release (at the moment v15.0.1):

> - Include a Jest Reporter that formats test results for GitHub Actions annotations (#31041).
> - The e2e tests are now using [`jest-circus`](https://github.com/facebook/jest/tree/master/packages/jest-circus) as the test runner. This enable us to capture screenshots at the time the tests failed. The unit tests are also using the same test runner for consistency (#28449, #31178).
> - ~Rename format-js script to format (#30240).~

(Edit: Last item quoted above is confirmed to be in release)

There might be more but I haven't checked.

## Expected behaviour
To see the items listed in the changelog under the 15.0.0 release for `@wordpress/scripts` to be available.

## Actual behaviour
Items listed in changelog not available.

**Comment by talldan** [comment]
@pierlon I just checked and it seems fine. I tested by installing the latest version locally in a new project and trying the format command:
<img width="571" alt="Screenshot 2021-05-06 at 2 14 19 pm" src="https://user-images.githubusercontent.com/677833/117250190-70b13380-ae75-11eb-8f52-9c25b1ba9d23.png">

I can also verify that jest-circus is installed though I didn't go as far as writing and running some tests.

It sounds to me like your local package might not have updated correctly. It could be worth double-checking the installed version and maybe seeing whether you have any conflicting versions specified elsewhere.

**Comment by pierlon** [comment]
@talldan I was mistaken about the `format` command, but the others still apply. In the `@wordpress/scripts@15.0.1` tagged release you can see there is no `testRunner` set in the `jest-unit.config.js` file, for example:

https://github.com/WordPress/gutenberg/blob/6f82f63e4708c72803862217b379b9e21f448290/packages/scripts/config/jest-unit.config.js#L11-L13

While in the `trunk` branch it is:

https://github.com/WordPress/gutenberg/blob/f6dd6a14ab15b0f3e514e63984deb8ec89ec7078/packages/scripts/config/jest-unit.config.js#L11-L18

Also see this quick [Runkit demo](https://runkit.com/6093903bb91bae001fd92959/6093903b258e3f001ab58078) demonstrating that a `testRunner` nor a `reporters` key is defined in `jest-unit.config.js`.

**Comment by talldan** [comment]
cc @kevin940726 @gziolo.

**Comment by gziolo** [comment]
The changelog published to npm for 15.0.1 looks good:

https://unpkg.com/browse/@wordpress/scripts@15.0.1/CHANGELOG.md

We might have some sort of merge issue in the `trunk` branch. I will investigate and update. We need to automate the process of adding entries to the changelog files because it seems to be very unreliable – both in terms of depending on contributors to add entries in the first place and ensuring that backporting commits with changes from the release branch are reliable.

**Comment by gziolo** [comment]
Opened https://github.com/WordPress/gutenberg/pull/31532 that should remove the confusion. I will inspect other packages as well.

@pierlon, the good part is that all those that are listed will be published next week 😄

**Comment by pierlon** [comment]
Thanks @gziolo!

**Comment by gziolo** [comment]
Thanks for catching it and reporting back 🙇🏻
