### ISSUE TITLE
Global Styles: Alignments inside default layout blocks - regression

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#31537]
## Description
There's been a regression in the way alignments works since the theme.json changes merged. When the post content has {"layout":{"inherit":true}} set then image blocks should have align full and wide options, but instead they have left, center and right. The problem is only in the editor

## Step-by-step reproduction instructions
1. Switch to emptytheme
2. Add an image in the editor
3. Notice that the wide/full alignments aren't available.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? yes

**Comment by oandregal** [comment]
I've been trying to repro this for emptytheme and tt1-blocks in different scenarios:

- gutenberg `trunk` and theme-experiments `master` 
- gutenberg `trunk` and https://github.com/WordPress/theme-experiments/commit/08b86b02dfa6a594ab501060aa0551fbaa01ae62 (the commit before the theme.json changes landed)
- gutenberg `v10.6.0-rc.1` and theme-experiments `master` 
- gutenberg `v10.6.0-rc.1` and https://github.com/WordPress/theme-experiments/commit/08b86b02dfa6a594ab501060aa0551fbaa01ae62 (the commit before the theme.json changes landed)

This is what I see in all the cases:

Post editor shows the width and full alignment options:

![post_editor_trunk_latest_empty](https://user-images.githubusercontent.com/583546/117291013-c6361200-ae6e-11eb-9279-772a728c6d62.png)

site editor doesn't show any alignment options:

![site_edito_trunk_latest_empty](https://user-images.githubusercontent.com/583546/117291017-c7673f00-ae6e-11eb-93b0-fc09f1d63562.png)

I don't seem to be able to reproduce this.

I've just realized that I'm testing with WordPress `5.8-alpha-50817`, going to try with `5.7.1` as well.

**Comment by scruffian** [comment]
This was happening because I hadn't rebuilt Gutenberg, sorry for the confusion.
