### ISSUE TITLE
Template selector: Active template is duplicated in options

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31531]
Scenario: Editing a page that uses the "Page" template. In the template dropdown the "Page" template is represented twice:

<img width="944" alt="Screenshot 2021-05-06 at 10 36 27" src="https://user-images.githubusercontent.com/846565/117276582-f2de2f80-ae56-11eb-8ffc-7910f2e085c1.png">

Instead of the duplicate, it might be better to list the "Page" template once, with a "(default)" suffix:

<img width="281" alt="Screenshot 2021-05-06 at 10 38 11" src="https://user-images.githubusercontent.com/846565/117276838-2f119000-ae57-11eb-960f-1027db1734c2.png">

**Comment by skorasaurus** [comment]
still an issue as of Gutenberg 12.4.

**Comment by jameskoster** [comment]
This doesn't seem to be an issue any more:

<img width="291" alt="Screenshot 2022-05-23 at 19 15 21" src="https://user-images.githubusercontent.com/846565/169881772-34332093-ad6a-430c-81ad-9723a89f986b.png">

Though it would be helpful if the `option` label in the dropdown matched the panel header.
