### ISSUE TITLE
Shortcode Block should use a Textarea.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3154]
There are several shortcodes that need to enclose content, and an input is not enough.

**Comment by aduth** [comment]
Related: https://github.com/WordPress/gutenberg/issues/1709#issuecomment-329506878

>Right now, the shortcode block is a text input. It does not account for shortcodes that allow paragraphs, for example, of content. A textarea is necessary.

Further suggestion to use `react-autosize-textarea`: https://github.com/WordPress/gutenberg/issues/1709#issuecomment-332336043

>One option could be to use an autosizable textarea which starts small, but wraps content and grows to accommodate.

**Comment by aduth** [comment]
Closed by #3184
