### ISSUE TITLE
Pullquote block missing center alignment option

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#31558]
I believe this used to be an option but not seeing it now. Thanks!

<img width="563" alt="Screen Shot 2021-05-06 at 12 06 19 PM" src="https://user-images.githubusercontent.com/1781226/117345290-39ce2400-ae5b-11eb-8898-13ad682570da.png">

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7. Gutenberg plugin 10.5.4. Twenty Twenty One.

This is what I am seeing:

![Screen Shot 2021-05-07 at 00 08 59](https://user-images.githubusercontent.com/5323259/117371644-856ae700-aec8-11eb-8140-1a44d1d514a8.png)

I see that Wide width and Full width alignment is missing.

**Comment by carolinan** [comment]
@bradley2083 Hi! Please include information about which theme, what version of WordPress and Gutenberg you are using, and if all other plugins are deactivated.

**Comment by bradhogan** [comment]
Sorry @carolinan  forgot that didn't I.  

WP: 5.7.1
Gutenberg: 10.5.4
Macbook Pro Big Sur 11.2.3
Chrome

Occurs with my own custom local theme but also with the default Twenty Twentyone theme (and no plugins installed other than Gutenberg). 

@paaljoachim I do believe you aren't seeing the align wide and full only because they have to be turned on in your theme by adding `add_theme_support( 'align-wide' );`

But, I do believe we should have the option to center align a pullquote block (as you do with the normal quote block). 

Cheers,

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/22784. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
