### ISSUE TITLE
Predict post format based on embeds and all post formats

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3155]
We currently have this for images and posts. When you select an image or post it means it predicts the post format. Let's roll this out for embeds and also other post formats - such as videos.

**Comment by karmatosed** [comment]
A start of a list would be:

Video: YouTube, Vimeo, Animoto, CollegeHumor, Dailymotion, Funny or Die, Hulu, Screencast, TED, VideoPress, Vine, WordPress.tv
Audio: SoundCloud, Spotify, Mixcloud, Speaker
Image: Flickr, Imgur, Photobucket, SmugMug, Giphy
Twitter: Chat
Status: Facebook

Some embeds could be debatable as to post format, but it's a starting point.

**Comment by mtias** [comment]
We have embeds, video, audio, and gallery in place. Closing this.
