### ISSUE TITLE
Template Editing Mode: Save notice doesn't mention newly created template

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31565]
## Description

Using the new template editing mode, if you create a new post alongside a new template and publish while in template editing mode, the confirmation message upon saving only mentions that a new post has been published. This relates to this issue in some ways as it's still TBD what language to use that aligns with the multi-entity saving flow: https://github.com/WordPress/gutenberg/issues/29846

## Step-by-step reproduction instructions

1. Set up a site with FSE capabilities
2. Add a new post > create a new template
3. Name the template
4. Make changes to the template.
5. Select "publish" and go through saving flow
6. Notice that the saving confirmation message only says "Post published" and doesn't mention the new template that was created.

## Expected behaviour

Expect to see a notice that mentions the new template that's been created. 

## Actual behaviour

The notice only mentions the post being published. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/117349875-245ff680-ae69-11eb-8094-3f96768bc97e.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6 RC
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by jameskoster** [comment]
In https://github.com/WordPress/gutenberg/issues/30800 it was proposed that _for now_ we do not allow template editing for draft posts. That will address this issue as it would then not be possible to publish a post and a template simultaneously.

Aside from that, a more generic "Changes saved" message in the Snackbar when multiple entities are saved does seem to be worth considering. It probably doesn't need to be especially verbose because the multi-entity-save flow already clarifies what will be changed / created.

**Comment by annezazu** [comment]
Noting that more feedback around this has come in through the[ seventh call for testing through the FSE Outreach Program](https://make.wordpress.org/test/2021/05/26/fse-program-testing-call-7-polished-portfolios/#comment-1703):

> It appears that I didn’t save the template since it’s showing a 404, even though the title says “portfolio.” I think what confused me was the “Publish” button in the upper right corner. Coming from a WP background I think I understand that “Publish” meant to publish the page template I was editing, but on initial use, I was hesitant to push the button because my context was the original page that I had created, not the page template I was editing. Maybe there’s a way to make that button more explicit. So something along the lines of “Save Page Template.”

**Comment by annezazu** [comment]
There's now a snackbar for this upon creation for 6.3 Beta 3. Closing out: <img width="456" alt="Screen Shot 2023-07-04 at 4 49 20 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/8d0a8cdf-baff-487e-a8e5-f049bfeb318d">
