### ISSUE TITLE
Feedback: Patterns don't scale down well

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31568]
## What problem does this address?

This was raised during the [fifth call for testing for the FSE outreach program](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1501):

>Some of the patterns don’t respond well as the screen gets smaller. For example the Large title pattern – https://d.pr/v/E5rfMj

Currently, I tried to replicate this with 10.6RC but wasn't able to find anything too jarring (cc @getdave if you're able to share an updated video). However, with the rise of more contextual patterns in blocks, I still wanted to report this as something to be mindful of improving. I chatted with @kjellr about this since he's done a lot of work related to this and he mentioned the following related issues:

-  Need a decent solution for scalable text: https://github.com/WordPress/gutenberg/issues/24480
- Unable to modify the wrapping behavior of columns which adds to this problem:
https://github.com/WordPress/gutenberg/issues/31248 &  https://github.com/WordPress/gutenberg/issues/13363

## What is your proposed solution?

Ensure patterns scale up/down well. As the FSE program continues, I'll use this issue to gather any related problems with patterns.

**Comment by getdave** [comment]
@annezazu I tried to replicate this but I can't anymore. Apologies that my original video was lost 😞
