### ISSUE TITLE
Template Editing Mode: difficulty editing blocks at the top of the editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31564]
## Description

When in template editing mode, the blocks added at the top of the editor are "smushed" together collapsing the toolbar settings with the block content making it hard to use. 

## Step-by-step reproduction instructions

1. Set up a site with FSE capabilities
2. Add a new post > edit the template it's using
3. Once in template editing mode, try to manipulate/add blocks at the very top of the editor
4. See problem :)

## Expected behaviour

Expect to be able to see both the toolbar and the content of the block.

## Actual behaviour

It's very hard to try to editor or see the content of the blocks being added. Everything is smushed :) 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/117348560-90d9f600-ae67-11eb-83ba-6535731bcdfd.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6 RC
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by jameskoster** [comment]
cc @ellatrix could this be due to the iframe change? 🤔

**Comment by jasmussen** [comment]
I don't think this is the fault of the iframe, and I think this is a version of the same issue the site editor faces, that is — blocks towards the top of the canvas overlap the content, because they have "sticky" behavior. If that's the case, I'd think this ticket is a duplicate of https://github.com/WordPress/gutenberg/issues/29464.

**Comment by annezazu** [comment]
Awesome! Thanks for connecting those dots @jasmussen. I'll trust your read here and close it out as a duplicate.
