### ISSUE TITLE
Widgets REST API: Deleted widgets re-appear after accessing widgets.php

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#31575]
## Description

The REST API endpoint for deleting widgets does not seem to properly delete widgets.

## Step-by-step reproduction instructions

For making REST API requests, I use https://httpie.io and have the Basic Auth WordPress plugin installed, but use whatever suits you.

1. Navigate to `wp-admin/widgets.php`.
2. Add a widget.
3. Find the widget's ID by hitting `GET /wp-json/wp/v2/widgets`.
4. Delete the widget by hitting `DELETE /wp-json/wp/v2/widgets/{id}?force=1`.
5. Hit `GET /wp-json/wp/v2/widgets`. Notice the widget is gone.
6. Navigate again to `wp-admin/widgets.php`. Notice the widget appears in Inactive widgets.
7. Hit `GET /wp-json/wp/v2/widgets`. Notice the widget appears again.

## Expected behaviour

The widget should not appear in steps 6 and 7.

## Actual behaviour

The widget re-appears.

**Comment by Mamaduka** [comment]
Hi, @noisysocks

I'm not able to reproduce the issue using the current `trunk.`

Using Paw and Application Password for REST API requests.

**Comment by noisysocks** [comment]
I'm still able to reproduce it and am working on a fix. Since the REST API has been merged into Core, I'll move this over into Trac: https://core.trac.wordpress.org/ticket/53313
