### ISSUE TITLE
"onDismiss" option in "createInfoNotice" is not taken into account

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#31571]
When using `wp.data.dispatch( 'core/notices' ).createInfoNotice` and trying to pass a function for the `onDismiss` option, the function is not triggered when the notice is dismissed.

Typing something like `wp.data.dispatch( 'core/notices' ).createInfoNotice( 'hello', { onDismiss: () => { console.log( 'dismissed!' ) } } );` is not logging anything in the console, when the created notice is dismissed.

Further information can be found [here](https://app.slack.com/client/T024MFP4J/C02QB2JS7/thread/C02QB2JS7-1620314773.351600).

**Comment by talldan** [comment]
Seems like this was implemented for Snackbar notices in https://github.com/WordPress/gutenberg/pull/26952, but the implementation wasn't extended to normal notices.

Hopefully it should be a simple matter of implementing the `onDismiss` in the Notice component, and the implementation in Snackbar can serve as a good guide.

**Comment by vdwijngaert** [comment]
Hey @talldan, 

I checked it out yesterday when the question arose on slack, should be an easy fix. Something like replacing https://github.com/WordPress/gutenberg/blob/b77336986f109d89b8b6c6f450192fef7602bde3/packages/components/src/notice/list.js#L23 with

```javascript
const removeNotice = ( notice ) => () => {
   if( notice.onDismiss ) {
      notice.onDismiss( notice.id );
   }
   onRemove(notice.id);
};
```

This is where `Snackbar` did it: https://github.com/WordPress/gutenberg/blob/c0cb7146273f1748304042ef33bc28c42692ad1f/packages/components/src/snackbar/index.js#L66
