### ISSUE TITLE
Customizer hidden from the Appearence menu when experimental theme is used

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#31579]
We can open customizer but it is hidden from menu.
![image](https://user-images.githubusercontent.com/10712881/117409032-c3e0c000-af21-11eb-8f57-572af0ab7503.png)

**Comment by carolinan** [comment]
Hi
This is on purpose,  block themes are styled with global styles and block settings, not the customizer.

**Comment by grogou** [comment]
@carolinan Do it mean in future we don't have customizer?

**Comment by vdwijngaert** [comment]
From [make.wordpress.org](https://make.wordpress.org/core/components/customize/):

> Customizer development was most active from WordPress versions 3.9 through 4.9. As of WordPress 5.0, Customizer development is currently focused on bug fixes and smaller enhancements. More-significant feature development is ongoing as part of the integration of the Gutenberg project with the customizer.

Although some of its features like widget management are going to be replaced by block based alternatives, the customizer will remain available for themes that don't support Full Site Editing. So you don't have to worry about it disappearing any time soon. 

I don't know about any plans to potentially drop support in a few years, though. But with WordPress' reputation of backwards compatibility, I'm sure that even if if gets removed from core, it will probably remain available as a standalone plugin (much like [Classic Editor](https://wordpress.org/plugins/classic-editor/)).

**Comment by grogou** [comment]
Thank you very much @vdwijngaert
