### ISSUE TITLE
FSE Navigation sub-menu items are black-on-black

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#31574]
## Description

Sub-menu items in navigation drawer are black on black.

## Step-by-step reproduction instructions

1. Install and activate TT1-blocks theme
2. Click Site Editor menu item
3. Toggle navigation open by clicking on WordPress logo
4. Click theme to return to the main theme menu
5. Observe Theme and Content menu items are visible
6. Observe sub-menu items are black on black

## Expected behaviour

Based on the templates listing, I think the text ought to be grey

## Actual behaviour

Unreadable text

## Screenshots or screen recording (optional)

![Screen Shot 2021-05-07 at 10 15 22 am](https://user-images.githubusercontent.com/519727/117380497-25526000-af1d-11eb-8406-4d5736357222.png)

## WordPress information
- WordPress version: trunk
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Using TT1 blocks from the theme-experiments repo

## Device information
- Device: Laptop
- Operating system: macOS Big Sur (11.2.3)
- Browser: Firefox Developer Edition 89.0b8 (64-bit)

**Comment by vdwijngaert** [comment]
I'm not familiar enough with the styling part, but changing this line: 

https://github.com/WordPress/gutenberg/blob/6b170517d62526c6e8f34f9a49f1a452e9e8163d/packages/components/src/navigation/styles/navigation-styles.js#L223

To 
```javascript
export const ItemTitleUI = styled.span`
```

Fixes it for me. Otherwise default Text styles are used, and they have `#000` as color.
