### ISSUE TITLE
Poor UX after removing `gutenberg_add_edit_link_for_post_type` filter

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#3158]
bdf94e65ac0c10b3ce5d8e214f0c9e1081997d9b removed the `gutenberg_add_edit_link_for_post_type` filter, which was added in 6884717 for #2750.

I think that filter -- or something comparable -- is necessary in order for some sites to test the plugin, because Gutenberg's support for meta boxes is still very limited, and many CPTs rely heavily on them.

If sites cannot choose to make the classic editor the default for those post types, then users have to manually choose the classic editor, which leads to confusion and annoyance. It may not sound like a big deal, but in less than 24 hours after upgrading to `1.5.0`,  I received `5` complaints from users, on a site that only has a couple dozen daily active users to begin with.

**Comment by aaronjorbin** [comment]
This was discussed a bit during today's dev chat with the decision that there needs to be a filter to turn things off on a per post type basis. It may not be included in the code as a part of the merge proposal though, and may instead live in a separate "turn Gutenberg off" plugin then.

**Comment by iandunn** [comment]
👍 

I'm not too worried about being able to turn Gutenberg off after the merge, I imagine that it will have much better support for CPTs by then. I think that filter is most useful right now, for sites that want to help test it, but need their CPTs to continue working.

In the meantime, I've had to downgrade to `1.4`, and this is a blocker for me installing any future updates.

**Comment by iandunn** [comment]
#3146 has a `gutenberg_can_edit_post_type` filter now, which would solve this.

**Comment by iandunn** [comment]
#3146 is merged now :)
