### ISSUE TITLE
Refine template flows in the post editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31591]
Template exercises in relation to a single post are accessed through the following interface(s):

<img width="286" alt="Screenshot 2021-05-07 at 10 05 22" src="https://user-images.githubusercontent.com/846565/117426439-ce985680-af1b-11eb-86f1-3a8173534314.png">

<img width="526" alt="Screenshot 2021-05-07 at 10 19 56" src="https://user-images.githubusercontent.com/846565/117428246-cb9e6580-af1d-11eb-9c13-484dea66fedc.png">

There are a number of issues we might try to address by revamping the design a bit here:

- [ ] Provide visual previews when changing template (block templates only).
- [ ] Offer a search affordance in the template selection UI when there are many templates to choose from.
- [ ] When creating a template allow the user to specify whether that template is $custom or specific to the current post (post-$slug).
- [x] Fix template duplication (https://github.com/WordPress/gutenberg/issues/31531).

Edit: Working Figma file [here](https://www.figma.com/file/UVmfVCEFu1CSEZHDV7nRod/Template-exercises?node-id=1%3A20).

**Comment by mtias** [comment]
This is also a place to explain a bit what a template is or allows.

**Comment by carolinan** [comment]
I liked the Figma example of the modal, but also the preview of the current template in the template section of the document sidebar.

**Comment by jameskoster** [comment]
Here are some initial ideas for the flows/UI. Inline with https://github.com/WordPress/gutenberg/issues/27093 I've moved the Template panel to the top bar in an effort to reduce reliance on the Inspector, and make moving between post/template editors feel smoother. I think this works well, but it's also worth noting that the overall UI could just as easily live in the Inspector instead, if that was a preference.

### Changing a template

https://user-images.githubusercontent.com/846565/117806927-dd9c4300-b252-11eb-91a9-fa42d1d0e6fb.mp4

* The current template is displayed as a preview.
* Change template is the most prominent action.
* Available templates are displayed in a modal which can scale to accomodate many templates. Legacy templates have no preview. Search can be exposed when there are more than _x_ templates.

### Editing a template

https://user-images.githubusercontent.com/846565/117808354-af1f6780-b254-11eb-900f-1dd292102222.mp4

* Edit template action is found in the "Advanced" section of the template panel. This section will only be visible to users with appropriate permissions.
* A short description forewarns users that changing the template can affect other documents.
* Clicking the page title in the top bar exits the template editor and returns you to the post editor.

### Create a new template

https://user-images.githubusercontent.com/846565/117812101-471f5000-b259-11eb-87ce-757ba7cc323e.mp4

* New template action is also found in the "Advanced" section of the template panel.
* The new template modal allows you to specify a name, and provides options to:
  * Apply the template immediately.
  * Begin editing the template once its created.
* A preview is also included to help set the scene. In the future this could be used as an affordance to allow folks to select an existing template as a starting point.
* A snackbar confirms the template has been created, and offers a shortcut to edit it.

### Moving between content / template editing

https://user-images.githubusercontent.com/846565/117812279-83eb4700-b259-11eb-91b5-04c6b70ddce8.mp4

This video concentrates solely on the flows for moving between the post and template editors. When editing the template it is possible to get back to the referring post two ways:

1. Click the page name in the top bar.
2. Open the template details popover and click the page title in the "Usage" section therein.

Method 1 will likely be implemented much sooner than method two. This replaces the existing "<- Back" button in the Template editor.

**Comment by youknowriad** [comment]
I don't know but I personally don't like that dropdown under the template title entirely. I think it's a bad non discoverable pattern and it splits the "document" settings between two places. I believe we should continue iterating the UI in its current place (the panel) until we move everything (all document settings) to the dropdown potentially.

**Comment by ghost** [comment]
It looks beautiful, but I agree with @youknowriad on keeping it in the Inspector. Maybe make it toggle to the top bar when you go to full screen mode.

**Comment by jameskoster** [comment]
> I believe we should continue iterating the UI in its current place (the panel) until we move everything (all document settings) to the dropdown potentially.

No objection to that from me. As mentioned above, this whole UI can live inside the Inspector for now if necessary:

<img width="754" alt="Screenshot 2021-05-11 at 13 39 46" src="https://user-images.githubusercontent.com/846565/117816659-a92e8400-b25e-11eb-92e8-fcad1b863da3.png">

**Comment by youknowriad** [comment]
The other thing worth mentioning is that not all the templates are previewable. That select mixes block templates and non block templates in classic themes.

**Comment by jameskoster** [comment]
Worth noting that putting this UI in the Inspector does marginally degrade the post <-> template editor UX (compared with the top bar implementation) due to the inconsistent placement of the pathways, as this video demonstrates:

https://user-images.githubusercontent.com/846565/117818029-1989d500-b260-11eb-8a26-44e4f622ae26.mp4

> The other thing worth mentioning is that not all the templates are previewable. That select mixes block templates and non block templates in classic themes.

I demonstrated how we can (potentially) handle this in the template selection modal:

<img width="850" alt="Screenshot 2021-05-11 at 13 52 50" src="https://user-images.githubusercontent.com/846565/117818132-39b99400-b260-11eb-905f-b6592377ecc3.png">

We can easily refine that preview thumbnail to include an explanation if y'all think that'd be helpful.

**Comment by youknowriad** [comment]
I wonder if the templates with "previews" is going to be the special case when using classic themes in which case we may want to use a regular "select" for these themes and maybe the visual templates for FSE themes.

**Comment by jameskoster** [comment]
I think that will certainly be the case. But as soon as a single block template exists I think it is worth showing the previews as they clearly communicate the user-friendliness of block themes in stark contrast versus classic themes. It's like GUI vs command line :D 

> we may want to use a regular "select" for these themes and maybe the visual templates for FSE themes.

I think that's fine when no block templates exist at all. The designs above could be adapted by replacing the template selection modal with a popover (or regular select dropdown), and hiding the preview in the panel itself:

<img width="715" alt="Screenshot 2021-05-11 at 16 35 20" src="https://user-images.githubusercontent.com/846565/117843644-e56dde80-b276-11eb-8463-c47ce1e61535.png">

Editing and Creating new template flows can behave the same.

**Comment by mtias** [comment]
What would be the flow for creating a template specific to a category slug?

**Comment by carolinan** [comment]
I have heard several users say that they want to edit the categories using blocks in Admin > Posts > Categories > Description field.
I think that the connecting that interface with the new is important.

**Comment by jameskoster** [comment]
Yes that would seem like a good interim step – connect the category management screen with the site editor. But ideally it should be possible to access a category (or any archive for that matter) from within the site editor. Both of these things feel like separate issues to me, since this one focusses on templates applied to _single entries_ in the _post editor_.

Edit: I just remembered that I opened https://github.com/WordPress/gutenberg/issues/35504 a while back :) 

We'll probably also make it possible to add a template for a specific category slug via the main template management view as a part of https://github.com/WordPress/gutenberg/issues/37407.

**Comment by jameskoster** [comment]
I've been looking at the various template related issues as we organise the tasks in https://github.com/WordPress/gutenberg/issues/41241. As a part of that effort this issue has been distilled down to just two tasks:

* When creating a template in the post editor ask whether that template should be $custom or specific (page-$slug)
* Provide a more visual template handling experience

This issue has prior art that is no longer relevant, so in the interest of tidiness I'm going to close it out in favor of dedicated issues for the aforementioned tasks.
