### ISSUE TITLE
Move `EditorNotices` from the `editor` package

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#31597]
## Description
Currently, we're copying this component for the new Widgets and Navigation screens. It would good to move it to a more generic package and avoid code duplication across editors.

The `@wordpress/block-editor` package seems like a good choice.

The `notices` package is also an option, but then we have to add `components` as a dependency.

P.S. Based on discussion form #16020.

cc @youknowriad, @jorgefilipecosta

**Comment by youknowriad** [comment]
For me sometimes duplicating is better than a bad abstraction.

Looking at its code, it seems to not depend on anything aside the "notices" on the JS side but the "style" side is very opinionated and depend essentially on the layout of the page. 

So for me, the best potential candidate could be "interface" but we'd need to remove any "editor" mentions from the component and potentially always render the component by default in the InterfaceSkeleton.

If that's not a good enough solution, I think we should keep duplicating it.

**Comment by youknowriad** [comment]
For instance I'm doing the opposite here 😬 https://github.com/WordPress/gutenberg/pull/30906

**Comment by Mamaduka** [comment]
> For me sometimes duplicating is better than a bad abstraction.

Yes, I agree.

The `EditorNotices` also has the `TemplateValidationNotice` dependency, which has to be abstracted for specific editors.

At this point, duplication makes sense, and other editors might want to handle notices a little differently.

I will close this issue for now, and we can re-open it if there'll be a need to abstract the notices component in the future.
