### ISSUE TITLE
Add Block: Embed

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#316]
## Attributes

- Alignment: None, Left, Right, Center, Full Bleed.
- Change url.

## Markup

```html
<!-- wp:embed -->
http://embedurl
<!-- /wp -->
```

## States ([see all](https://wpcoredesign.mystagingwebsite.com/gutenberg/#embed))

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Empty%20Embed,%20Hover.png)

![image](https://wpcoredesign.mystagingwebsite.com/gutenberg/Embed,%20Selected.png)

**Comment by aduth** [comment]
What's the markup of an embed block which has a caption assigned?

**Comment by mtias** [comment]
@jasmussen thoughts on caption there? I'm thinking it doesn't make sense to support caption in a generic embed block. It'd be fine on a specific video block, though.

**Comment by iseulde** [comment]
Why would it not?

**Comment by jasmussen** [comment]
> I'm thinking it doesn't make sense to support caption in a generic embed block. It'd be fine on a specific video block, though.

So long as I can make a linebreak, center and italicize some text, I don't have strong opinion. 

I think in general, it makes sense for _media items_, but if you embed something and the resulting block is something non media related, yeah probably would feel weird with a caption.

**Comment by mtias** [comment]
Yes, that's my hesitance, it'd feel spurious in some embeds and adds some visual and cognitive weight.

**Comment by iseulde** [comment]
Somehow, I do like that all "object blocks" would have the same markup and caption support.

```
<figure>
  <!-- children -->
  <figcaption></figcaption>
<figure>
```

Whether it's an image, gallery, embed, table, or other form of data visualisation.

**Comment by iseulde** [comment]
In the case of oEmbed, this could still be the link to the resource. It's still valid to store it in a figure, and it comes with some handy things like floating.

**Comment by jasmussen** [comment]
I think you both make really solid arguments here. 

Can we "wait and see what feels right" on this one? Or are there other ways we can get closer to a consensus? Do we have a list of all supported oembeds? Maybe we can look at the list and see if a whole bunch of them would look super weird with captions, and decide from that.

**Comment by mtias** [comment]
I don't have a strong opinion here :)

**Comment by jasmussen** [comment]
Can we close this one as fixed now that the embed block is in?

**Comment by StaggerLeee** [comment]
Maybe I am just a bit lazy, but I cannot see option to insert/embed video from local server ?
I mean upload to Media Library, and chose it same way as image/gallery.
