### ISSUE TITLE
Social Block: Add option to display text label

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#31605]
## What problem does this address?

To allow for greater design flexibility, it would be nice to allow the social icons block to also provide a text label. For example:

![image](https://user-images.githubusercontent.com/2846578/117475058-9dbf1e00-af29-11eb-99da-09f2698ad799.png)

## What is your proposed solution?

Add an option to toggle on/off the text label, or even display a label in lieu of an icon.

**Comment by deborah86** [comment]
I second this.

**Comment by jasmussen** [comment]
Nice.

**Comment by paaljoachim** [comment]
Totally agree!
