### ISSUE TITLE
Add filters to Global Styles sidebar plugin

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#31601]
## What problem does this address?
Can we add custom controls to Global Styles sidebar plugin?

![image](https://user-images.githubusercontent.com/10712881/117453171-b0e7e300-af55-11eb-9b0f-c9e128385d75.png)

## What is your proposed solution?
Had some filters to add our custom controls.

**Comment by grogou** [comment]
Any help?

**Comment by ntsekouras** [comment]
--cc @nosolosw , @jorgefilipecosta

**Comment by oandregal** [comment]
:wave: @grogou This sidebar is going to be updated heavily as per https://github.com/WordPress/gutenberg/issues/27473 so we haven't invested time on opening up filtering for this for that reason. This would be best addressed after 27473 is implemented, so it's clear what sort of filters should be available.
