### ISSUE TITLE
Block API documentation: supports.color.link is missing

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#31615]
In [the Block API documentation for color support](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#color), `link` is missing from the subproperties list.

The `core/media-text` block [supports this property](https://github.com/WordPress/gutenberg/blob/caedfa346a64692ec9186a644f9986c201649940/packages/block-library/src/media-text/block.json#L94).

**Comment by johngodley** [comment]
This was since added in https://github.com/WordPress/gutenberg/pull/32936
