### ISSUE TITLE
Post Featured Image: Block cannot be selected when used on single template

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#31626]
## Description

The Post Featured Image block is not functional when used in a Single Post or Page template.

## Step-by-step reproduction instructions

- Using a block based theme like TT1 Blocks, go to the Site Editor and open the Single Post or Page template
- Insert a Post Featured Image block

## Expected behaviour

- I can select the block by clicking on it
- I can move the block
- I can delete the block
- There's a block toolbar visible

## Actual behaviour

None of those things

## Screenshots or screen recording (optional)

<img width="1161" alt="Screen Shot 2021-05-08 at 12 21 54" src="https://user-images.githubusercontent.com/1699996/117548068-800cba00-aff8-11eb-9ca5-36fdfcc3cd31.png">

## Code snippet (optional)

No js console errors

## WordPress information

- WordPress version: 5.7.1
- Gutenberg version: 10.6.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: Desktop
- Operating system: macOS
- Browser: Firefox

**Comment by annezazu** [comment]
Want to note that the UX matches what I found here and that I can replicate with a nightly build from May 10th: https://github.com/WordPress/gutenberg/issues/31256

Oddly, the featured image block works as expected if added within the Query Block. It seems to be breaking when placed outside of it. @ntsekouras do you have any insight here based on your work with the Query Block?

**Comment by ntsekouras** [comment]
Currently if a `Post Featured Image` block is inserted in a context where a `postId` doesn't exist, like a Single Post or Page template, is not marked as a block and that why is non-interactive to any action.

Inside a `Query` block the `postId/context` comes from fetched results.

**Comment by annezazu** [comment]
This makes perfect sense and should have been obvious :D Thank you for clarifying there.
