### ISSUE TITLE
Expose BlockStyles in wp.blockEditor

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#31620]
It would be great if the BlockStyles Component in `packages/block-editor/src/components/block-styles` can be exported in `wp.blockEditor` so devs can use the style picker in other scenarios.

Should be fairly easy to add in `packages/block-editor/src/components/index.js`:
```js
export { default as BlockStyles } from './block-styles';
```

**Comment by bph** [comment]
Benjamin, @bfintal can you elaborate more on the use case for 'other scenarios'?

**Comment by priethor** [comment]
Let's close this issue as we are lacking information and the activity has stalled. Feel free to reopen if the issue still needs attention.
