### ISSUE TITLE
Theme.json: Block specific CSS is printed even if a block is not used on the current page

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#31642]
## What problem does this address?

When you set defaults for a block using theme.json, the CSS is printed in `.global-styles-inline-css` even if the block is not used on the current page.

## What is your proposed solution?

Only include the CSS if the block is used on the current page.

**Comment by carolinan** [comment]
@aristath I wanted to check in if you still want to be assigned to this issue and if there is any progress.

**Comment by aristath** [comment]
There is no progress because other things needed to be prioritized, and this issue may be sub-optimal behavior but it doesn't actually "break" anything, so it was not an urgent priority.

I'm unassigning myself because maybe the "assigned" prevents someone else from working on it? :shrug:

**Comment by oandregal** [comment]
I'm interested in picking this up. Going to take Ari's offer and assign this to me.

**Comment by scruffian** [comment]
I had a go at this here: https://github.com/WordPress/gutenberg/pull/39571

**Comment by scruffian** [comment]
Here's an alternative version: https://github.com/WordPress/gutenberg/pull/40513

**Comment by scruffian** [comment]
This was closed by https://github.com/WordPress/gutenberg/pull/41160
