### ISSUE TITLE
The editor styles background is not applied properly.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#31651]
When using a theme with a background like 2020, and on long posts, you'll notice that the background of the editor stops at `100vh` (See screenshot)

<img width="1423" alt="Capture d’écran 2021-05-10 à 10 39 04 AM" src="https://user-images.githubusercontent.com/272444/117639708-1f0def00-b17c-11eb-95be-a9a04fc712d5.png">

Could this be related to the recent changes to the visual editor to iframe the template editor or maybe add the animations. cc @jasmussen @ellatrix

**Comment by jasmussen** [comment]
I'm not sure how to reproduce. I'm trying latest TwentyTwenty and not seeing the same:

<img width="1270" alt="Screenshot 2021-05-10 at 13 33 00" src="https://user-images.githubusercontent.com/1204802/117653079-4670b600-b194-11eb-857d-ba6a6556d7a8.png">

**Comment by youknowriad** [comment]
Ok, this looks to be Safari specific.

**Comment by ellatrix** [comment]
Hm, I can't reproduce it in Safari either

**Comment by youknowriad** [comment]
Yep, this seems fixed now. (I think with your latest PR that touched VisualEditor)

I noticed that we have double scrollbars which is not great in viewport previews and template mode.

**Comment by jasmussen** [comment]
Do you mean this double scrollbar? https://github.com/WordPress/gutenberg/issues/30055

Or another?

**Comment by youknowriad** [comment]
<img width="1440" alt="Capture d’écran 2021-05-17 à 12 24 25 PM" src="https://user-images.githubusercontent.com/272444/118482906-45e49c00-b70d-11eb-9bb9-d67d40c48f6a.png">

Maybe it's the same
