### ISSUE TITLE
Missing loading indicator for media and text block

### ISSUE THREAD

**Issue by evakaneva** [WordPress/gutenberg#31668]
## Description
 While waiting for the image to upload, there is no loading indicator.

## Expected behaviour
 As a user I would expect to see loading indicator so I know the image is uploading.

## Actual behaviour
 There is no indication that the image is uploading.

## Screenshots or screen recording (optional)
 
![noloadindicatorr](https://user-images.githubusercontent.com/51059617/117689769-c6157980-b1c2-11eb-9609-65c23b96124c.gif)

## WordPress information
- WordPress version:  5.7.1
- Gutenberg version:  Version 10.4.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes, TT1 Blocks

## Device information
- Device:  Desktop
- Operating system:  Big Sur 11.1
- Browser:  Chrome Version 90.0.4430.72

**Comment by Mamaduka** [comment]
#29710 will fix this issue as well.

**Comment by Mamaduka** [comment]
Fixed via #29710.
