### ISSUE TITLE
Open/close sidebar interaction is un-intuitive

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#3166]
Forgive me for dipping in and out of Gutenberg. I try it occasionally so most of my feedback is as someone who has come to it reasonably fresh.  I should also add that I've tried searching issues for this; I've not found anything, but may have missed a discussion.

## Issue Overview

The open/close sidebar interaction is un-intuitive.  When you click the "X" to close it, the "i" icon appears in the "X"s place, leading you to believe that the "i" will bring it back, but it doesn't.  There's then both the "three dots" icon and the "cog" icon above, neither of which suggest that they might bring the sidebar back.

Here's a reproduction of my attempt to interact with it: 

![screen recording 2017-10-26 at 11 26 am](https://user-images.githubusercontent.com/1532368/32048458-7a6fad2e-ba41-11e7-9429-2dd3f89f981f.gif)

This needs one or more of:

* animation to show the bar collapsing and the appearance of the affordance to bring it back
* better icons - it's not clear that the sidebar is "settings" and therefore re-appears with the cog.  I note that the customizer uses arrows.
* better positioning of icons - the icon to bring the sidebar back should appear in place of the icon that made it go away

I don't know why this isn't done using the same interface as the customiser which seems to be super-clear to me:

![screen recording 2017-10-26 at 11 35 am](https://user-images.githubusercontent.com/1532368/32048672-2e8a1c0e-ba42-11e7-8bb3-f8693db85dfe.gif)

**Comment by kevinwhoffman** [comment]
Excellent points. The ambiguous icon cluster seems to be taking over the top-right corner of Gutenberg. The Customizer example is a win for clarity.

**Comment by afercia** [comment]
I'd agree the "Info" placement can be improved. As also mentioned in the related PR https://github.com/WordPress/gutenberg/pull/2684#issuecomment-327534290

> "Info" seems placed there just because there's some available space, There's no logic in the placement in the source order, nor this control is grouped logically in an area where it would make sense.

**Comment by mtias** [comment]
Closing as info button has been moved to the header.
