### ISSUE TITLE
Global Styles: H1-H6 headings missing, only one Heading available

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#31695]
## Description

In 10.6.0-RC1, the global styles for H1, H2, H3, H4, H5, H6 are missing in the side panel of the Site Editor.

## Step-by-step reproduction instructions

Install 10.6.0-rc1 and a FSE theme.
Go into Site Editor and open the Global Styles side panel, and go to By Block Type

## Expected behaviour

Should be able to set font size, line height, color etc for each heading (H1 to H6) individually.

## Actual behaviour

There is only one 'Heading' available to select.

### Previously in 10.5.4
![gutenberg-gs-headings-all](https://user-images.githubusercontent.com/76742815/117804600-d7f12e00-b24f-11eb-8f8b-0241158e4ec2.png)

### 10.6.0-rc1
![gutenberg-gs-heading](https://user-images.githubusercontent.com/76742815/117804668-f0614880-b24f-11eb-95ea-f55487fcaa4b.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6.0-rc1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Various themes, all same result

## Device information
- Device: Desktop
- Operating system: W10
- Browser: Chrome and Firefox

**Comment by paaljoachim** [comment]
It sounds like a regression. 
Can you take a look @nosolosw ?

**Comment by oandregal** [comment]
:wave: 

This is expected. We're moving away from exposing many UI sections for the same block ([see](https://github.com/WordPress/gutenberg/issues/29891) for rationale). The UI for the new elements is not yet ready but the latest mockups can be seen at https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866
