### ISSUE TITLE
Getting terms using getEntityRecords and _fields

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#31692]
## Description
I'm using the following code to get all the terms of a custom taxonomy for a dropdown in a block I'm developing:

    const terms = useSelect( ( select ) =>
        select( 'core' ).getEntityRecords( 'taxonomy', 'my_taxonomy_slug', { per_page: -1, orderby: 'name', order: 'asc' } )
    );

As I want to optimize this call as much as I can, I added the `_fields` query arg to get just the name and slug of the terms:

    const terms = useSelect( ( select ) =>
        select( 'core' ).getEntityRecords( 'taxonomy', 'my_taxonomy_slug', { per_page: -1, orderby: 'name', order: 'asc', _fields: 'name,slug' } )
    );

But doing this, I get an empty array.

If I add the `id` field to the `_fields` query arg, then the code works again as expected and I get an array with all the terms:

    const terms = useSelect( ( select ) =>
        select( 'core' ).getEntityRecords( 'taxonomy', 'my_taxonomy_slug', { per_page: -1, orderby: 'name', order: 'asc', _fields: 'id,name,slug' } )
    );

My question is, is `id` a required field to make the `_fields` query arg in `getEntityRecords` work? I don't see this anywhere in the docs.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 88

**Comment by mrleemon** [comment]
Browsing the source code I see this:

https://github.com/WordPress/gutenberg/blob/306566f9b8832c551667817a02e0f3f6145f6bb6/packages/core-data/src/resolvers.js#L183

There is a comment that mentions that "If requesting specific fields, items and query association to said records are stored by ID reference. Thus, fields must always include the ID".

I think this should be somewhere in the developer handbook, as I lost many hours over this.

**Comment by annezazu** [comment]
@mrleemon thanks for flagging this and sharing where you'd like to see this added to the developer handbook. I've labeled this as documentation in hopes this can be included in the future.
