### ISSUE TITLE
Used npx @wordpress/create-block to create a block,  fails with “sh: wp-create-block: command not found”

### ISSUE THREAD

**Issue by GalvinCn** [WordPress/gutenberg#31694]
Used npx @wordpress/create-block to create a block, it fails.   show  error info  below:"sh: wp-create-block: command not found"

**Comment by gziolo** [comment]
Thank you for the report. Could you provide more details like node and npm versions, OS so we have a better picture of to how reproduce it?

**Comment by priethor** [comment]
Let's close this issue as we are unable to replicate and the activity has stalled. Feel free to reopen if the issue resurfaces.
