### ISSUE TITLE
Editor View of the Cover Block Does Not Match the Front-End

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#31708]
## Description

When editing the cover block, the position of the elements does not match what is on the front-end.

## Step-by-step reproduction instructions

1.  Add a cover block to a page
2.  Add elements like a title, paragraph, and buttons to the cover block
3.  View a preview of the page

## Expected behaviour

I expect to see the editor match the front-end.

## Actual behavior

The position of the elements in the Editor is different from what is seen on the front-end.

## Screenshots or screen recording (optional)

**Editor View**

![image](https://user-images.githubusercontent.com/12677420/117817591-9b580f00-b21c-11eb-87c1-6e13c652465a.png)

**Front-end View**

![image](https://user-images.githubusercontent.com/12677420/117817726-bc206480-b21c-11eb-99ab-3a4bd03d686e.png)

## WordPress information
- WordPress version:  5.7.1
- Gutenberg version:  Not Installed
- Are all plugins except Gutenberg deactivated?  No, but I tested on another website where they were and I had the same issue
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes, Twenty Twenty

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Microsoft Edge Version 90.0.818.56

**Comment by carolinan** [comment]
Hi
I am not able to reproduce this.
Did you also try disabling Grammarly in the editor?

**Comment by deborah86** [comment]
@carolinan Yes.  It did not fix the issue.  Did you test in Microsoft Edge?

**Comment by ramonjd** [comment]
I also cannot reproduce in Chrome or Microsoft Edge.

Here's what I'm seeing in Edge:
<img width="800" alt="Screen Shot 2021-06-08 at 11 39 50 am" src="https://user-images.githubusercontent.com/6458278/121109189-699f8b80-c84e-11eb-8566-ff0ecf1b56e3.png">


<img width="800" alt="Screen Shot 2021-06-08 at 11 39 41 am" src="https://user-images.githubusercontent.com/6458278/121109176-65736e00-c84e-11eb-8a1e-72f9484b386f.png">

**Comment by deborah86** [comment]
@ramonjd I will do more testing.  Maybe it is an issue with the Twenty Twenty theme?

**Comment by deborah86** [comment]
After the 5.8 update, I am no longer seeing this issue. If it occurs again, I will reopen this ticket.
