### ISSUE TITLE
Saving almost always stuck.

### ISSUE THREAD

**Issue by locksoft** [WordPress/gutenberg#31707]
## Description

I'm using this plugin on Mac OS with Safari. At least once every 10-20 times the (auto)saving gets stuck and I need to reload the page, often loosing part of the changes.
Is there a solution for this? It seems to me Gutenberg is still too unstable to use on regular basis.
Thanks.

**Comment by annezazu** [comment]
@locksoft Hey there! Bummed to hear you're having trouble but would love to hear more about what's going on. For starters, does this happen if you disable your other plugins and only have Gutenberg enabled? Does this happen if you use a default theme like Twenty Twenty-One? Does this happen with a specific block or is it unpredictable? It's important to rule out other conflicts before exploring further if this is related to Gutenberg as a whole.

**Comment by locksoft** [comment]
You’re right, I should have provided more info, but it’s not an easy task to disable all the other plugins every time, to find out the culprit.
It turned out that in the last days, I can’t even open an article because the bottom part of the page (extra fields, etc.) covers the article itself. This on Safari with a Mac with Mojave. On iPad with last iOS everything works normally. Same on that same Mac with Chrome.
So I think there could be some incompatibility with Safari, I don’t think the fault is of plug-ins…

**Comment by annezazu** [comment]
Thanks for following up @locksoft! I understand it's a lot to ask and I appreciate you clarifying further. Can you share more about what extra fields are in the articles and how those have been added? It sounds like those might come from plugins.

**Comment by locksoft** [comment]
I tried to use it with and without other plugins but it seems the issue is still there. It happens rarely but it happens (both with Safari and Chrome). Is there a way to activate some sort of debugging mode, so to see what really happens when it gets stuck?

**Comment by locksoft** [comment]
Update:

I tried again to do some experiments with plugins and I've realized I've this one, that sounds really strange:

Gutenberg, version 10.8.2

Description text is in italian:

"La stampa dal 1440. Questo è il plugin di sviluppo per il nuovo editor a blocchi del core"

but it says something like:

"Print since 1440. This is the development plugin for the new block editor core"

If I keep it active, it creates problems with Safari (if I edit an article, I cannot see the blocks. Only the page footer), that's why I'm using Chrome since some month (it doesn't have this issue).
If I disable it, the backoffice seems working well with Safari too, and it seems redundant, as Gutenberg seems to be active also without that plugin active.

May it be that the plugin is totally unnecessary and I can safely delete it? Maybe, if it's active, it interferes with WP core and also the saving function may be affected as it could happen (my supposition) that both try to save the article at the same time and this make it getting stuck?

This is the plugin link (it was updated three days ago, so it doesn't look like an old, abandoned plugin, and this makes me even more confused):

http://www.lemonskin.net/io/wp-admin/plugin-install.php?tab=plugin-information&plugin=gutenberg&TB_iframe=true&width=772&height=909

Thanks.

**Comment by locksoft** [comment]
Update: the problem, without the other plugin (but, please, let me know about it) doesn't appear anymore, even if every now and then the saving procedure cant take a long time, several minutes too. With Safari, every one hour or so, I can't edit single blocks as, typing a text, it doesn't work. Sometimes the cursor goes to the end and one letter appears. I need to save, return to articles list, open it again, and it start working again. This on Safari for OS X Mojave.

**Comment by annezazu** [comment]
@locksoft thanks so much for continuing to add context to this issue. It's super helpful for folks to investigate. It sounds like you're asking whether you should use the Gutenberg plugin? If so, I recommend checking out this post [that'll help you know whether it's best to use it for your specific site](https://wordpress.org/news/2021/04/become-an-early-adopter-with-the-gutenberg-plugin/). 

As a next step, are you able to share an example of a post/page content of blocks whether this occurs? This'll help folks replicate by using the same post/page content and attempting to make changes before trying to save. 

cc @gwwar as a heads up in case this _might_ be performance related and touches on some of the awesome work you've been doing.

**Comment by locksoft** [comment]
I'd like to help you, but I've just updated to the last version of WP and a lot of plugins just disappeared. :(
I can't understand why. What happened?

**Comment by locksoft** [comment]
Now the back-office is in maintenance mode (not the online website). What to do? :((

**Comment by locksoft** [comment]
Curious, I've just installed the last version of WP and the Gutenberg plugin reported it needed to be updated. I proceeded and received the message "the plugin is already updated to the last version". Then it simply disappeared from the list.
I've not idea if it was deleted because no more necessary or something else. So I cannot test what you asked me.
Just to have an idea, the "footer part" of the page (everything that followed the article content) was on top of the page and the content was covered by it. This only happened on Safari, not Chrome.
I hope it may help.

**Comment by locksoft** [comment]
Ok, I've just had my first "stuck on saving" with the last WP version. And maybe I've discovered it's not an infinite waiting but, after a while (let's say about 3 minutes) it finally saves.
I don't think I can do any other test (like disabling the other plugins) because this issue is so rare it may happens once every day, and I can't keep addons disabled fot 24 hours. :/

**Comment by locksoft** [comment]
It happened again. No "article" section with Safari. :(

https://i.postimg.cc/rscr73bg/Schermata-2021-07-22-alle-15-51-00.png

**Comment by locksoft** [comment]
You are no more replying to my posts but I still need help. :(

I've been trying the Health Check & Troubleshooting plugin, and I also tested several themes, even WP default ones. But with Safari the edit section is still covered by the bottom page settings.

Is Wordpress definitively abandoning Safari support? :((

**Comment by annezazu** [comment]
@locksoft I was away from work in order to move. Thanks for your patience :) WordPress is not abandoning Safari support at all. You can see browser support [here](https://make.wordpress.org/core/handbook/best-practices/browser-support/). It sounds like this only happens in Safari which helps narrow down the problem. However, without narrowing down the various plugins you are using and without further reports of the same issue, this is likely an issue specific to your site's setup. Can you try contacting your host to see if they can investigate this further?

**Comment by locksoft** [comment]
Hmmm, interesting.
I've just updated my Safari from version 14.0 to 14.1.2 and the issue seems solved (at least, apparently, the edit page opens correctly, in the next days I'll do some tests). I'm still on an old MacOS version (Mojave) and the system update messages aren't very clear (no mentions about Safari update in the quick note).

I'll let you know if I'll encounter any problem, but it's a bit scary I can loose WP functionality if I don't pursuit the last browser versions (previous one was just a few months old). o_O

**Comment by annezazu** [comment]
Oh wow! Glad to hear that the update to the latest of Safari might have helped. I might still reach out to your host to have them review this though to be proactive. For now, I am going to close this out but just comment here again if you need it re-opened and I will do so :)
