### ISSUE TITLE
The editor settings object doesn't work properly

### ISSUE THREAD

**Issue by 5n** [WordPress/gutenberg#31701]
## Description

Related #31027 (WordPress/wordpress-develop#1118), #31587, and so on.  
Function 'getSettings' doesn't store the settings passed to the block editor.

## Step-by-step reproduction instructions

1. Install and activate Gutenberg plugin.
2. Install and activate Twenty Twenty-One or TT1 Blocks.
3. Upload and activate [sample-settings](https://github.com/WordPress/gutenberg/files/6458721/sample-settings.zip) plugin.
4. Go to edit post page ('post', 'page', or custom post like 'wp_template').
5. Click and add Sample Settings block.
6. Check the value of custom parameter displayed on sidebar and console log.

## Expected behaviour

'sample setting value'

## Actual behaviour

undefined

## Screenshots or screen recording (optional)

![getsettings1](https://user-images.githubusercontent.com/48854933/117809712-78b80b80-b299-11eb-9a1c-44ff5b73fbe3.png)
![getsettings2](https://user-images.githubusercontent.com/48854933/117809724-7ce42900-b299-11eb-8924-98349304e0d9.png)

## Code snippet (optional)

PHP:
```
function add_sample_block_editor_settings($settings) {
  $settings['sampleSetting'] = 'sample setting value';
  return $settings;
}
add_filter('block_editor_settings', 'add_sample_block_editor_settings');
```
'block_editor_settings' -> 'block_editor_settings_all' since 5.8.0.

JSX:
```
import { store as blockEditorStore } from "@wordpress/block-editor";
import { useSelect, select } from "@wordpress/data";

export default function Edit() {
  const sampleSetting = useSelect((select) => {
    const { getSettings } = select(blockEditorStore);
    return getSettings()?.sampleSetting;
  }, []);
}
```

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.4
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Google Chrome 90.0

**Comment by youknowriad** [comment]
Hi, thanks for the issue.

This is not a bug, this is actually the intended behavior. All editor settings don't make sense in the "block-editor" store which is basically something generic enough that can be used in any block editor instance (not WP or post editor specific)

**Comment by 5n** [comment]
I see.
Thanks!
