### ISSUE TITLE
Styling the Post Terms divider

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#31710]
It would be nice to be able to customize the divider between post terms, or at least render the divider as a pseudo element so it can be easily targeted via CSS:

Current state looks like this:

View | Mark-up
------ | --------
<img width="216" alt="Screen Shot 2021-05-11 at 10 09 10 AM" src="https://user-images.githubusercontent.com/5375500/117829653-d3b11a80-b227-11eb-8585-adbb12f9d93a.png"> | <img width="562" alt="Screen Shot 2021-05-11 at 10 07 41 AM" src="https://user-images.githubusercontent.com/5375500/117829560-bc722d00-b227-11eb-9dc9-8f03c408cbc6.png">

**Comment by kjellr** [comment]
Customizing this divider should definitely be possible. It also seems weird to me that the default divider is a pipe — I feel like the vast majority of themes use a comma here.

**Comment by justintadlock** [comment]
The term list functions already have a `separator` argument.  Can we just expose that as an argument for the block?  It doesn't necessarily have to be turned on in the block options panel, but theme authors could simply do:

```
<!-- wp:post-terms {"separator":", "} /--> 
```

Commas or no separator at all are the most common use cases in themes.

**Comment by aristath** [comment]
Pushed a PR in #32812 adding the missing `separator` attribute if anyone wants to test & review it :+1:

**Comment by justintadlock** [comment]
What do you think about adding a `<span class="wp-block-post-terms__sep">` wrapper? I often need it for directly targeting the separator in CSS.

**Comment by aristath** [comment]
> What do you think about adding a `<span class="wp-block-post-terms__sep">` wrapper? I often need it for directly targeting the separator in CSS. 

Great idea. Added it to the PR :+1:
