### ISSUE TITLE
[@wordpress/element] Typings clash with @types/react

### ISSUE THREAD

**Issue by marekdedic** [WordPress/gutenberg#31722]
## Description
Hi, while using NPM with lockfile version 2 (although this might be accidental and just a result of an update around the same time) I get TypeScript errors:

```bash
/home/user/project/node_modules/@types/react/index.d.ts(2976,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
/home/user/project/node_modules/@wordpress/element/node_modules/@types/react/index.d.ts(2977,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
/home/user/project/node_modules/@wordpress/element/node_modules/@types/react/index.d.ts(2990,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
```

## Step-by-step reproduction instructions
I am using `@wordpress/element` together with some `@types/wordpres__...` packages for its typescript typings in the following way:

```ts
declare const wp: {
	blocks: typeof import('wordpress__blocks');
	components: typeof import('wordpress__components');
	editor: typeof import('wordpress__editor');
	element: typeof import('@wordpress/element');
};
```

## Expected behaviour
No build errors

## Actual behaviour
The aforementioned errors

## Device information
- Device: Desktop
- Operating system: Debian testing

**Comment by gziolo** [comment]
@sarayourfriend or @sirreal, is it something you are able to help with?

**Comment by sirreal** [comment]
You have two copies of `@types/react` installed and they conflict. It's a common problem. Without more details it's hard to diagnose exactly, but there are at least two clear solutions:

- Add [`skipLibCheck: true`](https://www.typescriptlang.org/tsconfig#skipLibCheck) to your tsconfig.
- Ensure there's only one `@types/react` in your dependencies. Make sure the version numbers align, what version is at the top level? Is it an explicit dependency of your project or was it hoisted? You can also try [`npm dedupe`](https://docs.npmjs.com/cli/v7/commands/npm-dedupe) to help with this.

**Comment by marekdedic** [comment]
Hi,
thanks, `npm dedupe` did the trick.

I didn't mess with `@types/react` myself. I have `@types/wordpress__blocks`, `@types/wordpress__components`,  `@types/wordpress__editor` and `@wordpress/element`, so the incompatibility (and it was that, I had `@types/react` versions 16 and 17) comes from just these 4 packages... :/

Thanks for the help, closing...
