### ISSUE TITLE
Widgets settings backup

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#31727]
Been wondering if it makes sense to back up the old widgets settings before enabling the new editor. Generally the probability of some widgets settings going terribly wrong when switching editors vs. the chance to "overfill" the options DB table. 

A backup is always nice to have when changing a lot of functions that handle/save user content. With WordPress' size and number of plugins and themes it seems possible to trigger some rare bug in a plugin that might corrupt or delete the widget settings. On the other hand adding blocks to the widgets in the DB doesn't seem like a big change. Also most websites are backed-up automatically so even if a disaster happens, there is a path for recovery. Frankly I'm 50/50.

**Comment by noisysocks** [comment]
The new functionality doesn't change how widgets are stored in the database. Blocks added to a widget area are saved as "block widget" (`WP_Widget_Block extends WP_Widget`).

Does that ease your mind? I'm happy to be cautious and create a backup site option if you think it's necessary 🙂
