### ISSUE TITLE
Esc and Enter keys: Modify behavior in Customizer > Widgets

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#31730]
This issue is for taking a look at the keyboard behavior for `Esc` and `Enter` keys within the Customizer Widgets screen.

Since the editor and Customizer have different behaviors for these keys, I wonder if we could try a hybrid approach:

- If you have a block selected, `Esc` and `Enter` toggles between Select and Edit mode (default editor behavior)
- If you don’t have a block selected, `Esc` and `Enter` takes you back a screen (default Customizer behavior)

These tweaks would be especially helpful re: the editing flow for legacy widgets that was merged in #30889.

**Comment by talldan** [comment]
Labelling as a bug now that we're approaching the point where the editors are considered stable. Select/navigation mode should be usable.

The customizer escape key handling is also causing an issue with popovers as described in the duplicate - https://github.com/WordPress/gutenberg/issues/31972.
