### ISSUE TITLE
input of text stops being displayed

### ISSUE THREAD

**Issue by jetpen** [WordPress/gutenberg#31756]
## Description

When creating a post, after inputting some content, not sure exactly what triggers this situation yet, but at some point the input of text stops being displayed, even though the input is still being captured invisibly. Only by saving the content will the invisible content be refreshed on the display and normally editing can resume. This seems to be specific to editing from Android 10 (LG G8 ThinQ) using Chrome (90.0.4430.91) browser.

## Step-by-step reproduction instructions
1. New Post
2. Input content in multiple paragraphs, making various edits and corrections
3. At some unknown point for some unknown reason, the input stops being displayed, although new input continues to be accepted invisibly
4. Save the post to correct the issue and restore the editor to a good state so that new input is displayed again

## Expected behaviour

Expecting all content that is input to be displayed in real time

## Actual behaviour

New input text stops being displayed as it is typed in, although the input is accepted, and this can be seen after the post is saved.

## Screenshots or screen recording (optional)

None provided.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.4 although I've seen this behavior is many previous versions
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No, I am using Twenty Fourteen

## Device information
- Device: LG G8 ThinQ
- Operating system: Android 10
- Browser: Chrome 90.0.4430.91 although I have seen this behavior in many previous versions

**Comment by mchowning** [comment]
It sounds like this issue is occurring when accessing Gutenberg from within Chrome (is that right @jetpen ?). For that reason, I'll remove the "Mobile App - i.e. Android or iOS" tag and replace it with the "Mobile Web" tag. Feel free to switch this back if I'm misunderstanding though.

**Comment by jetpen** [comment]
That is correct, @mchowning .

**Comment by jetpen** [comment]
I have just encountered this same issue in an text editing control of another Web application not platformed on Wordpress. I now suspect this is not specific to Gutenberg, and it may be a flaw in Android or Chrome.
