### ISSUE TITLE
Custom link on images and gallery

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#31805]
## What problem does this address?

It is not possible to add an custom URL image or a gallery. As now, the only options i have are either to link the image to the attachment page or the media file. Which, personally, i don't know how many people uses. 
![image](https://user-images.githubusercontent.com/11801254/118175643-62779000-b3fe-11eb-818b-f3f89d4e4f0c.png)

## What is your proposed solution?

The solution will be adding the possibility to add a custom url to the image block, and a custom url to each picture in the gallery block.
Similar to [Coblocks Plugin does](https://es.wordpress.org/plugins/coblocks/).
![image](https://user-images.githubusercontent.com/11801254/118177978-6822a500-b401-11eb-97ab-609aa502bdac.png)

You can also select if it opens in another tab.
![image](https://user-images.githubusercontent.com/11801254/118177849-3c9fba80-b401-11eb-9de5-9c1cb7c273ad.png)

You can also say that it is a common requested feature, because there is a [blog post in wpbeginner](https://www.wpbeginner.com/plugins/how-to-add-custom-links-to-gallery-images-in-wordpress/) about it.

**Comment by bph** [comment]
Alvaro, @avagp you should be able  to add a custom URL to an image block from the toolbar. 
![Screen Shot 2021-05-13 at 7 12 57 PM](https://user-images.githubusercontent.com/39980/118198736-75e72300-b41f-11eb-8dc8-9b46a561fa2e.png)

You are right. That is not yet possible for a Gallery block. 
![Screen Shot 2021-05-13 at 7 15 52 PM](https://user-images.githubusercontent.com/39980/118198831-ab8c0c00-b41f-11eb-80fe-eaf92865f186.png)

There is good news, though. The Gallery block is worked on right now. It still might take awhile until it comes to the Gutenberg plugin and then in WordPress core. If you feel comfortable testing unfinished work, [the team published a call for testing the new Gallery block. ](https://make.wordpress.org/core/2021/03/23/gallery-block-update-call-for-testing/)

With the new Gallery block, you can create galleries by nesting Image blocks inside if it.  And then you can apply custom URLs to each of the image in the gallery. 

For now, I will close this feature request as it's already in the works and will soon come to a WordPress instance near you.

**Comment by TheRadicalDreamer** [comment]
Thanks.

I will have to wait until the release of the gallery block update.

I primarily use the gallery for multiple urls

**Comment by bph** [comment]
I am afraid so. You probably thought about this workaround: using single image blocks in multi-column displays.

**Comment by TheRadicalDreamer** [comment]
yes, but it does not look as i wanted it to.  :/
