### ISSUE TITLE
New strings not available for translation of 10.6 at translate.wordpress.org

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#31800]
## Description
New strings not available for translation at translate.wordpress.org with the release of 10.6. The same thing happened for 10.5
https://wordpress.slack.com/archives/C0341VCNL/p1619729058007500

@ocean90  said then:  "This was caused by removing the version header from the readme.txt which is currently not supported, see https://meta.trac.wordpress.org/ticket/4514#comment:4.
I did a manual import in the meantime."

## Step-by-step reproduction instructions
Go to https://translate.wordpress.org/locale/sv/default/wp-plugins/gutenberg/ and no new strings was added for 10.6.0

## Expected behaviour
When a new version of the plugin is released the strings should show up on the translation-site.

## Actual behaviour
No new strings added and some strings appear untranslated in the UI.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by ocean90** [comment]
Closing since this was a missing update in the import script which was already reported upstream and has now been fixed.
