### ISSUE TITLE
CSS added via wp_add_inline_style() not ouput in site editor

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#31807]
When adding a custom stylesheet and appending inline styles, they do not get output in the site editor (or in the template-editing mode from the post screen).  The `<iframe>` in both cases loads the stylesheet but not the inline styles.

Example code:

```
add_action( 'enqueue_block_editor_assets', function() {

	wp_enqueue_style( 'example', 'example.css', null, null );

	wp_add_inline_style( 'example', 'h1 { color: red; }' );
} );
```

Both the stylesheet and inline styles appear in the page `<head>`.  However, only the stylesheet appears in the iframe `<head>`.

If I switch the `$handle` in `wp_add_inline_style()` to `wp-block-library`, it works.  But, custom handles do not.

**Comment by kathrynwp** [comment]
@justintadlock I'm going ahead and closing this as a "maybe later" issue, but if anyone comes across this in the future and would like this looked at again, feel free to comment here.
