### ISSUE TITLE
Button block color style can become invisible on :hover

### ISSUE THREAD

**Issue by mkevins** [WordPress/gutenberg#31828]
## Description
When a button is created and styled, it is lacking a mechanism to specify the :hover color. This results in situations where the link text within the block can be invisible (e.g. white text on a white background).

## Step-by-step reproduction instructions
Create a post or page using the button block (try on a site created with Barnsbury, for example). Check the preview of the post or page, and hover over the button.

## Expected behaviour
The text remains readable.

## Actual behaviour
The text becomes invisible.

## Screenshots or screen recording (optional)

Video of the issue (encountered on mobile, but present on web as well):
https://cloudup.com/ckJrvrg1cc1

## Device information
I originally encountered this on iPhone 11, but the preview is in a webview, and the issue exists on the front-end / web facing side as well.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in  https://github.com/WordPress/gutenberg/issues/4543. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
