### ISSUE TITLE
Update button is not becoming active when Custom Fields are edited without typing into them

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3182]
## Issue Overview

When editing Custom Fields on the relevant metabox of a page, the update button is not activated unless the user clicks inside one of the fields and types something. This means that if the value of a Custom Field is changed using another way, the user won't get the chance to update the page unless he does a change that will activate the `Update` button.

## Steps to Reproduce (for bugs)

1. Install Toolset Types
2. Create a Post Field Group
3. Add an Image custom field and allow multiple instances of this field.
4. Add a Date custom field.
5. Navigate to the `Page edit` page that uses Gutenberg, and try to add an image to the image gallery. 
6. Try to pick a date using the date picker.

## Expected Behavior

The expected behavior would be that when the image is inserted, or the date was chosen through the datepicker the `Update` button should have been enabled.

## Current Behavior

The `Update` button is not enabled unless you do another action that will enable it.
I'm also adding a link to a video showing the current behavior.
https://www.useloom.com/share/625caa872c944e2e94e4826cba8b1e88

**Comment by kmgalanakis** [comment]
On the classic editor, the `Update` button is always enabled and active. For Gutenberg, it's only activated when there is a change in the edited post/page. Is there a JS event or something else that could notify the editor and the button that there is an unsaved change in the form?

**Comment by kevinwhoffman** [comment]
Confirming this is the case in Gutenberg 1.6 with ACF meta boxes as well. Opening an existing post and editing meta box content does not trigger the Update button. I have to click into the Gutenberg editor in order for the update Button to become active.

**Comment by BE-Webdesign** [comment]
Thank you for the report. This ties into the "Dirty Detection" for Gutenberg. There were some recent changes to dirty detection, and most likely there was a regression somewhere in there. Handling this detection is also challenging for meta boxes, as they have been developed assuming a request response pattern, as opposed to a client rich app. Depending on how these pieces use the DOM, it can become tricky to detect whether anything has changed.

**Comment by aduth** [comment]
Closed by #4184
