### ISSUE TITLE
Navigation Editor: Move locations modal state into `ManageLocations` component

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#31837]
## What problem does this address?
Currently, the modal state is managed by the main `useNavigationEditor` hook. I don't think there's a need for this now.

## What is your proposed solution?
Move modal state to `ManageLocations` component and manage it locally.

**Comment by getdave** [comment]
>  I don't think there's a need for this now.

Could you expand on this a little bit? What makes you feel there is no longer a need?

**Comment by Mamaduka** [comment]
Sorry, I should've used a different sentence here. I don't know why this was done initially, but there's no need to manage modal state in `useNavigationEditor.`
