### ISSUE TITLE
Lost focus on navigating across words with CTRL and arrow keys

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3183]
I was trying to add a link in a text, so what I did was:

* write some paragraph
* click just before the first word you want to add the link to
* press and maintain CTRL and SHIFT keys
* use the arrow keys to move across words boundaries (if you don't press ctrl, you move across letters)

After a few jumps, the focus changes to the action toolbar. Expected behavior was that focus wouldn't change. See gif:

![selection-error](https://user-images.githubusercontent.com/583546/32060153-40b104ac-ba6e-11e7-80b3-a744919de4a5.gif)

This happens with navigation (CTRL pressed) and selection (CTRL + SHIFT). I could reproduce this behavior in paragraphs, heading, and quotes.

**Comment by ephox-mogran** [comment]
I assume this has nothing to do with TinyMCE, and is instead related to `Ctrl` being the focus menu shortcut. I've hit the same problem before.

**Comment by youknowriad** [comment]
We tried to make the shortcut work only if you hit "ctrl" alone, we probably forgot to exclude the "shift" key.

**Comment by nosolosw** [comment]
The changes landed in https://github.com/WordPress/gutenberg/pull/3229#event-1318552036 fixed the selection issue (SHIFT + CTRL). However, there are some other use cases where using CTRL makes the focus to be lost. These are the ones I'm aware of:

* use CTRL+backspace to remove entire words
* use CTRL+sup to remove entire words
* use CTRL+arrows to navigating across words

cc @youknowriad
