### ISSUE TITLE
Navigation block placeholder is invisible against black a background

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#31841]
If you place the navigation block on top of a blank background, its deselected placeholder is invisible: 

![navigation](https://user-images.githubusercontent.com/1202812/118291263-64485e80-b4a5-11eb-9aa1-10153f9b186c.gif)

## To reproduce: 

```
<!-- wp:group {"style":{"color":{"background":"#000000"}}} -->
<div class="wp-block-group has-background" style="background-color:#000000"><!-- wp:navigation {"orientation":"horizontal"} /--></div>
<!-- /wp:group -->
```

Seen in a few block based themes, incl. TT1 Blocks and `emptytheme`.

**Comment by kjellr** [comment]
cc @jasmussen since I know you've been iterating on this placeholder. I see that it's supposed to pick up the `currentColor`, but it doesn't seem to be working for me in this case.

This issue comes up in a few of the patterns in #31610:

<img width="1383" alt="Screen Shot 2021-05-14 at 3 22 50 PM" src="https://user-images.githubusercontent.com/1202812/118319066-40e2db00-b4c8-11eb-87a1-98c7fa534de6.png">

Both of those have nav block placeholders on the right side, but they're impossible to see. I expected something more like this: 

<img width="1384" alt="Screen Shot 2021-05-14 at 3 24 54 PM" src="https://user-images.githubusercontent.com/1202812/118319278-8acbc100-b4c8-11eb-9f5c-6f6990e3de42.png">

**Comment by jasmussen** [comment]
Thanks for the ping, I'll take a look as soon as I get a moment. It might be an effect of the recently merged burger menu.
