### ISSUE TITLE
Don't Show Preference for Panel -> Custom Fields if Custom Fields has been disabled by theme/plugin

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#31848]
## Description
The Block Editor has the option to show the Custom Fields panel. This option exists even if that panel has been removed by plugin.

## Step-by-step reproduction instructions
Remove the Custom Fields metabox, a la:

remove_meta_box( 'postcustom', 'post', 'normal' );

## Expected behaviour
The preference to show the Custom Fields  panel should not be visible

## Actual behaviour
The preference to show the Custom Fields panel IS visible, though toggling it doesn't actually show anything, likely due to https://core.trac.wordpress.org/ticket/45282

## Code snippet (optional)
add_action( 'admin_menu', 'ext_remove_custom_fields' );
function ext_remove_custom_fields() {
 remove_meta_box( 'postcustom', 'post', 'normal' );
}

## WordPress information
- WordPress version: 5.7.3
- Gutenberg version: whatever is included in 5.7.3. Sorry, I tried to find it but couldn't
- Are all plugins except Gutenberg deactivated? No (because a plugin is needed to remove the custom fields metabox)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 90.0

**Comment by skorasaurus** [comment]
relatedly if anyone tackles this #16333

**Comment by skorasaurus** [comment]
Hi, 
Thanks for reporting; this has been fixed by https://github.com/WordPress/gutenberg/pull/33931 ; it should appear in Gutenberg 11.5. 

I'm not longer able to reproduce this when using a newest build of Gutenberg that includes the changes from 33931.
