### ISSUE TITLE
Error with latest posts block in grid view

### ISSUE THREAD

**Issue by hazuremon** [WordPress/gutenberg#31847]
## Description

Encountered "This block has encountered an error and cannot be previewed” with latest posts block when switching to grid view

## Step-by-step reproduction instructions

1. Add Latest Posts block
2. Click on Grid View

## Expected behaviour

Should see grid layout with latest posts

## Actual behaviour

Displaying "This block has encountered an error and cannot be previewed”

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1413953/118337064-c914b080-b4c7-11eb-9b70-251200e1170d.mov

## WordPress information
- WordPress version: 5.7.2 
- Gutenberg version: 10.6.0 
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes 

## Device information
- Device: Desktop 
- Operating system: OSX Big Sur 
-  Browser: Chrome 90

**Comment by hazuremon** [comment]
Tested with latest Gutenberg 10.6.1 and the error remains.

**Comment by skorasaurus** [comment]
able to reproduce on 10.6.1

**Comment by skorasaurus** [comment]
more details and the cause were listed at https://github.com/WordPress/gutenberg/issues/32045 ; thanks @oxyc
