### ISSUE TITLE
Babel Preset Default: Allow to use a custom browserslist config

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#31857]
## What problem does this address?
When using a custom browserslist config with `@wordpress/scripts` it's currently only used for (Post)CSS. For JavaScript the `@wordpress/browserslist-config` config will still be used because it's defined in `@wordpress/babel-preset-default`:

https://github.com/WordPress/gutenberg/blob/08faf92b37f1dadb772b5399a77b310444e0cae7/packages/babel-preset-default/index.js#L29-L31

This is a bit unexpected.

## What is your proposed solution?

**First idea**: Allow to extend the options passed to `@babel/preset-env`. Something like this:

```json
  "babel": {
    "presets": [
      [ "@wordpress/babel-preset-default", { "presetEnvOpts": { "targets": "", "debug": true } } ]
    ],
  }
```
`getPresetEnv()` would merge the custom `presetEnvOpts` when passing them to `@babel/preset-env`.

**Second idea**: Check if a browserslist config is available. Something like [`hasBabelConfig()`](https://github.com/WordPress/gutenberg/blob/a542c0deebfb439c2667ff372aa1e16a5f001cbc/packages/scripts/utils/config.js#L18-L25) in `@wordpress/scripts`. If set, leave `targets` empty so  `@babel/preset-env` can pick up the project's config. Otherwise use `@wordpress/browserslist-config` as right now.

**Third idea**: More of a workaround. Keep it as is and require devs to add `@babel/preset-env` as a second preset which also seems to override the config from `@wordpress/babel-preset-default`:

```json
  "babel": {
    "presets": [
      "@wordpress/babel-preset-default"
      [ "@babel/preset-env", { "modules": false, "debug": true } ]
    ],
  }
```

Any thoughts and/or other ideas?

**Comment by ocean90** [comment]
An alternative for the first idea: Use a single option `ignoreBrowserslistConfig` which can be passed to `@wordpress/babel-preset-default`. The default value would be `true` to keep the current behaviour. `@babel/preset-env` has a similar option, see https://babeljs.io/docs/en/babel-preset-env#ignorebrowserslistconfig.

@gziolo What do you think? This is currently the only issue preventing us to continue using the scripts where IE 11 support is enabled via browserslist.

**Comment by gziolo** [comment]
> Second idea: Check if a browserslist config is available. Something like hasBabelConfig() in @wordpress/scripts. If set, leave targets empty so @babel/preset-env can pick up the project's config. Otherwise use @wordpress/browserslist-config as right now.

This one would very much align with how other configs are detected 👍🏻 

There is also one place in ESLint config where it reads the default settings for Prettier but it's possible to override them with the local config:

https://github.com/WordPress/gutenberg/blob/7fcd57c9a62c232899e287f6d96416477d810d5e/packages/eslint-plugin/configs/recommended.js#L16-L18

> An alternative for the first idea: Use a single option ignoreBrowserslistConfig which can be passed to @wordpress/babel-preset-default. The default value would be true to keep the current behaviour. @babel/preset-env has a similar option, see https://babeljs.io/docs/en/babel-preset-env#ignorebrowserslistconfig.

This one is probably more work but it's also a good one.

Maybe we need both?

**Comment by ocean90** [comment]
> This one is probably more work but it's also a good one.

I thought that this was actually the easiest one. 😆 See #31895 for a working solution. But maybe I have missed something?

> There is also one place in ESLint config where it reads the default settings for Prettier but it's possible to override them with the local config

Good point, I was only looking in `@wordpress/scripts` which has a more complex version for finding the config.

**Comment by ocean90** [comment]
#31898 seems to be a much easier solution as it uses browserslist's own method to find the config. It doesn't require any options, it just works™.

**Comment by gziolo** [comment]
> #31898 seems to be a much easier solution as it uses browserslist's own method to find the config. It doesn't require any options, it just works™.

Yes, it's a great one 👍🏻 #31895 is a bit not clear for me as it seems to be implemented more as `useLocalBrowserslistConfig`.

**Comment by ocean90** [comment]
> it seems to be implemented more as `useLocalBrowserslistConfig`.

Yeah, that would have been a better name for it.

**Comment by ocean90** [comment]
Thanks!
