### ISSUE TITLE
Reconsider the importance of Meta Boxes in CPTs

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#31871]
Being WordPress such an amazing tool with so many purposes, why is the Custom Post Types + Meta Boxes being so underrated?

The whole Gutenberg ecosystem is great bit it’s really killing the opportunities with CPTs.

Why?

Because now, when you create a new CPT you have an edit screen that forces you to see a custom post type as a blog post / page. Id est, you have a huge Blocks editor for ONE PIECE of data: The content.

What happens with custom post types that are made of many chuncks of content that need to live in the posts meta table?

All the meta boxes where squeezed into the sidebar as if they are not important.

Request:

Allow CPT to have metaboxes that look more like they did before, where they could be draganddropped around into bigger and smaller areas.

**Comment by mtias** [comment]
If the CPT doesn't support `content` then meta-boxes take a much more prominent place (the block editor itself is disabled since the assumption is that CPT is more data driven than display driven). Is that a flow you have tried? It seems a good fit for the use case you describe.
