### ISSUE TITLE
Add Slot to PageAttributes panel in the edit-page sidebar

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#31888]
## What problem does this address?

When adding meta values and associated settings that affect the entire page it often makes sense to visually group them with similar settings. While it is possible to add settings to the Featured Image and PostStatus panels through filters and slots there currently is no slot for the Page Attributes Panel.

## What is your proposed solution?

The same way as you can add items to the PostStatus panel this area should be exposed as a slot to that plugins can add settings to that area.

**Comment by philwp** [comment]
This is a great idea. I can think of many use cases, including my own, where this would be useful.

**Comment by youknowriad** [comment]
Would you say that we can close this now that we don't have a "page attributes" panel anymore?
