### ISSUE TITLE
Links not returning result if page/post contains no content

### ISSUE THREAD

**Issue by rtvenge** [WordPress/gutenberg#31903]
## Description

When adding a link in the editor, the search doesn't return results of posts/pages that have no content. As soon as you add content, they then get returned.

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Create a new page called Foo Bar
2. Don't put any content in it
3. Save the page
4. Open another existing page/post
5. Add a paragraph with the text "Lorem ipsum dolor sit amet"
6. Highlight "Lorem" and click on the Link icon
7. Search for the word `Foo` or `Bar`

## Expected behaviour
Foo Bar page should be shown

## Actual behaviour
No pages are shown

## Screenshots or screen recording (optional)

<img width="394" alt="Screen Shot 2021-05-17 at 10 12 23 AM" src="https://user-images.githubusercontent.com/303836/118529521-73731a80-b6f8-11eb-9af8-2e28ffb13dfa.png">

## Code snippet (optional)

In the developer console shows this error:

`[Error] Failed to load resource: the server responded with a status of 400 () (search, line 0): https://envirodispose.lndo.site/wp-json/wp/v2/search?search=Foo&per_page=20&type=term&_locale=user`

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: Desktop
- Operating system: macOS 11.3.1
- Browser: Safari Version 14.1 (16611.1.21.161.6)

**Comment by annezazu** [comment]
Thanks for reporting this. Using Gutenberg 10.6.1 and WordPress 5.7.2, I wasn't able to replicate this:

<img width="810" alt="Screen Shot 2021-05-17 at 10 16 04 PM" src="https://user-images.githubusercontent.com/26996883/118589382-85d36f80-b75d-11eb-8177-1f1f74deb433.png">

Closing this out as a result! Feel free to re-open if you can provide more information or additional steps to replicate.

**Comment by rtvenge** [comment]
As a follow up for anyone else that runs into this issue, this had something to do with SearchWP for me. I disabled the plugin, ran and index and the search worked after that.

**Comment by annezazu** [comment]
Thanks for following up @rtvenge :D
