### ISSUE TITLE
[Widgets Screen] Legacy Widgets - HTML encoded output for Recent Comments

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#31914]
## Description
Using latest version of Twenty Twenty-One theme (v1.3). When editing a Legacy Widget, like Recent Comments, Recent Posts, or Meta the Block Editor Sidebar shows encoded HTML for widget's description output: `Your site&#8217;s most recent comments.`

## Step-by-step reproduction instructions
With the Twenty Twenty-One theme (v1.3) activated:

1. Go to Appearance → Customize
2. Add any of the following blocks: Recent Posts, Recent Comments or Meta
3. Publish
4. Go to Gutenberg → Experiments and turn on Enable Widgets screen in Customizer
5. Save Changes
6. Got to Appearance → Widgets
7. Click on the previously added widget to select it, and view the Block description in the sidebar of block editor.

### Legacy Widget: Recent Posts

| **Expected behaviour**  |  **Actual Behaviour** |
|-------------------------|----------------------|
| `Your site's most recent Posts.` | `Your site&#8217;s most recent Posts.` |

### Legacy Widget: Recent Comments

| Expected behaviour | Actual Behaviour |
|---------|------------|
| `Your site's most recent comments.` | `Your site&#8217;s most recent comments.` |

### Legacy Widget: Meta

| Expected behaviour | Actual Behaviour |
|---------|------------|
| `Login, RSS, & WordPress.org links.` | `Login, RSS, &amp; WordPress.org links.` |

## Screenshots or screen recording

Gif of issue: 
![Gutenberg-Widgets-description-bug-2021-05-17](https://user-images.githubusercontent.com/405912/118551927-450f3280-b72c-11eb-8f47-97653f85c93f.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: MacBook Pro (13-inch 2020)
- Operating system: macOS 11.3.1
- Browser: Chrome 90.0.4430.212

**Comment by JustinyAhin** [comment]
This should be fixed by this PR https://github.com/WordPress/wordpress-develop/pull/1220.
See also https://github.com/WordPress/gutenberg/issues/31023

**Comment by colorful-tones** [comment]
> This should be fixed by this PR https://github.com/WordPress/wordpress-develop/pull/1220.
> 
> See also https://github.com/WordPress/gutenberg/issues/31023

Yes, this is a duplicate of #31023. We're good to close and I'll do a quick test with PR 1220.

Thanks @JustinyAhin 👏

**Comment by colorful-tones** [comment]
Closing this out, as it is a duplicate of #31023
