### ISSUE TITLE
Widget screen: Adding Classic block (bug)

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31916]
## Description
In the Widgets screen. Adding the Classic block causes a bug.

## Step-by-step reproduction instructions

1. Widgets screen.
2. Add the Classic block.
3. Notice the error.

## Expected behaviour

I expected to see no error when adding the Classic block.

## Actual behaviour

https://user-images.githubusercontent.com/5323259/118562418-f1710900-b76c-11eb-8185-0c7356b2a315.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One

Console errors:

![Screen Shot 2021-05-18 at 00 10 52](https://user-images.githubusercontent.com/5323259/118562721-8b38b600-b76d-11eb-957c-c00ff0c33efb.png)

```
react-dom.min.de439aae.js:125 TypeError: Cannot read property 'tinymce' of undefined
    at index.js?ver=1066a93409706095a0461fb5da18e8cc:72
    at Bh (react-dom.min.de439aae.js:126)
    at Dj (react-dom.min.de439aae.js:162)
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)
    at xb (react-dom.min.de439aae.js:162)
    at Te (react-dom.min.de439aae.js:146)
    at react-dom.min.de439aae.js:61
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)
```

**Comment by noisysocks** [comment]
The Classic block isn't supported in this editor. See https://github.com/WordPress/gutenberg/issues/15916. 

Still, this is a bug, since it should not appear in the inserter.
