### ISSUE TITLE
Feature Request: Use JavaScript to add the "View Post" link to the Admin Bar after publishing

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#31915]
## What problem does this address?
As we transition our organization to the Block Editor, something we're all getting frustrated by is how awkward it is to view a post you just published if you either missed the little popup in the bottom left, or just don't even know it's there. We are all very used to using the "View Post" link available in the Admin Bar.

This "View Post" link is there any time you're editing a published post EXCEPT for when you're still on the screen after publishing.

To re-gain access to the post's link, it can take a lot of clicks (depending on your screen settings at the time):
1) Enable Sidebar
2) Select Post (vs Block)
3) Expand the Permalink Section

## What is your proposed solution?
After publishing a post, use JS to add the "View Post" link in the top admin Bar (the one that's there if you refresh the page or edit any existing post.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/30579 and  https://github.com/WordPress/gutenberg/issues/25021. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue(s).
