### ISSUE TITLE
Word navigation breaks in the presence of inlined `strong` tags (WebKit)

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#3192]
## Issue Overview

A user expecting to navigate along an Editable by pressing the modifier key—Alt/Ctrl, depending on the desktop platform—and tapping the right arrow will see the caret get stuck at the end of a `strong` tag if one is found in the content.

This persists until they let go of the modifier key to move one character at a time. This doesn't happen when going left, nor when the right key is _kept_ pressed.

![gutenberg-word-nav-stuck](https://user-images.githubusercontent.com/150562/32079900-b0deb072-baa4-11e7-9598-1dae8dd78e9b.gif)

## Steps to Reproduce (for bugs)
1. Open the Gutenberg demo
2. Find the block that starts with _“What you are reading now"_ and place the caret at the beginning of the block.
3. Keep the modifier key pressed
4. Continuously tap the right arrow to move word-wise

## Expected Behavior
The caret should traverse all the words of the Editable.

## Current Behavior
The caret gets stuck at the end of the inlined bold text.

## Fix
@ephox-mogran dug into this and confirmed it to be a bug in TinyMCE. He set up a [fiddle that confirms](http://fiddle.tinymce.com/fdgaab/1) this. It's being worked on now. \o/

**Comment by ephox-mogran** [comment]
I'll let you know when a fix is available and in what version.

**Comment by ephox-mogran** [comment]
@mcsf  This has been fixed as on TinyMCE 4.7.2.

**Comment by mcsf** [comment]
Closed via #3388.
