### ISSUE TITLE
Navigation: Deleting the Page List block with the Delete key crashes its parent Navigation Block

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#31930]
## Description
When deleting the `Page List `block within a `Navigation` block with the `Delete` key, if it is the only child block, the parent `Navigation` block crashes:

## Step-by-step reproduction instructions
1. Add a `Navigation` block
2. Click on "Add all pages"
3. Select the recently added `Page List` block
4. Delete it with the `Delete` key

This **doesn't** reproduce if:
- There are/were other blocks in the `Navigation` block.
- The `Page List` block is deleted through the toolbar option.
- Any other block is deleted following these steps.

## Expected behaviour
To see an empty Navigation in its placeholder state.

## Actual behaviour
The block has encountered an error and cannot be previewed, with the following console error:

```
Error: An error occurred while running 'mapSelect': Cannot read property 'title' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'title' of undefined
```

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/27339341/118628138-9f5fd000-b7cc-11eb-9303-7c9418895430.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No (Kadence)

**Comment by talldan** [comment]
I think this is the same issue as https://github.com/WordPress/gutenberg/issues/29498

**Comment by priethor** [comment]
Thanks, closing this as duplicate!
