### ISSUE TITLE
Patterns panel flickering

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [WordPress/gutenberg#31943]
## Description
Often when I open the pattern panel it starts blinking or flickering.
The flickering depends on the size of the window. When I resize the window - flickering gone.

## Screenshots or screen recording (optional)
![ezgif-2-721e5f797a09](https://user-images.githubusercontent.com/19765202/118679558-a60b3900-b806-11eb-8df4-1ac2f48baf8d.gif)

## WordPress information
- WordPress version: Version 5.7.2
- Gutenberg version: <!-- e.g. "9.4.0" or "Not installed"
- Are all plugins except Gutenberg deactivated? "No"
- Are you using a default theme (e.g. Twenty Twenty-One)? "No"

## Device information
- Device: Desktop
- Operating system: Ubuntu 20.04.2 LTS
- Browser: Chrome 90.0.4430.212

**Comment by annezazu** [comment]
@Morgunov-Vitaly thanks for chiming in here! Can you confirm this happens when you have other plugins disabled? I'm wondering if this is some sort of a conflict as I'm not able to replicate currently.

**Comment by justintadlock** [comment]
I can confirm this happening a few times over the past few versions. It seems to happen at random.  I can usually click out of the inserter and reopen it to fix.

Also running Chrome 90.0.4430.212 but on the latest Windows.

Edit: No other plugins and different themes at different times.

**Comment by annezazu** [comment]
Thank you for confirming this! If it happens again in the future, I'd love any details to help replicate (immediate actions taken prior, any errors in console, etc). Updating labels in any case.

**Comment by Morgunov-Vitaly** [comment]
I use Kadence Blocks plugin, Elementor and Crocoblock Plugins.
But it seems, that the issue related with rendering of the block patterns (I think it related with css rendering). It depends on size of the window, quantity of the patterns etc. 
In my case I use custom block patterns, and `remove_theme_support( 'core-block-patterns' );` function to clearing all other patterns. (But I also tried to use `unregister_block_pattern()` with the list of registered core patterns). 
I noticed, that if I dont unregistering core patterns the flickering doesn't appear.

**Comment by annezazu** [comment]
Wonderful insight. Thank you.

**Comment by margarita-boomCodes** [comment]
@annezazu I have the same issue in Chrome, when I have exactly three patterns in a single pattern category. Less or more than three is no problem.

**Comment by miminari** [comment]
We discussed the issue in a triage session on slack today(https://wordpress.slack.com/archives/C02QB2JS7/p1624339362341100).

This Issue seems similar #29255 #24611.
We'd like to continue with #24611. Thank you!
