### ISSUE TITLE
Navigation Block: Allow nav items to display horizontally on mobile

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#31942]
On mobile screens, nav block items default to being displayed as a vertical list: 

<img width="547" alt="Screen Shot 2021-05-18 at 11 19 40 AM" src="https://user-images.githubusercontent.com/1202812/118678642-3166d900-b7cb-11eb-9956-9ecba5d06d2f.png">

There's currently no way to override this and let the items appear in an inline horizontal list: 

<img width="498" alt="Screen Shot 2021-05-18 at 11 19 46 AM" src="https://user-images.githubusercontent.com/1202812/118678843-5eb38700-b7cb-11eb-8c8e-885c58e0fb6d.png">

If a site only has a few nav items, it's quite possible the mobile nav will look better displayed this way, and that the "enable responsive menu" setting would be overkill. We should figure out a way for folks to opt-in to this. Maybe a "stack on mobile" option?

**Comment by jasmussen** [comment]
This is definitely a regression, and was not intentional. Let me take a look.

**Comment by jasmussen** [comment]
Fix in #32081.
