### ISSUE TITLE
Undo/Redo Behavior in Template Editing Mode is inconsistent/confusing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31948]
## Description

If you change the template that a page or post is using before entering template editing mode and click undo, it causes the entire template selection to change back to the original template rather than undoing a change made in the template editor. If you try to hit the redo button, the new template selection does not return. 

## Step-by-step reproduction instructions

1. Install and activate Gutenberg & TT1 Blocks
2. Create a new page and title it
3. Select a different template and click to edit it
4. Make a change to the template itself
5. Click undo and find that it undos the entire template selection.

## Expected behaviour

Expect the undo button to just undo changes within the template editor itself and to not undo the overall template selection. 

## Actual behaviour

It seems to undo the overall template rather than a specific change within the template. 

## Screenshots or screen recording (optional)

Example 1 just undoing where it seems to bork the entire template/empties it out:

https://user-images.githubusercontent.com/26996883/118692409-417cb980-b7c7-11eb-972a-96c7d9e5203c.mov

Example 2 just undoing where it reverts to the original default template:

https://user-images.githubusercontent.com/26996883/118692517-65d89600-b7c7-11eb-9509-cd09f0fb7b64.mov

Example 3 undoing & redoing: 

https://user-images.githubusercontent.com/26996883/118692991-de3f5700-b7c7-11eb-9526-805f102bd0d1.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop 
- Operating system: MacOS
- Browser: Chrome

**Comment by kathrynwp** [comment]
Hi @annezazu – I'm no longer able to replicate this; following your steps, "undo" does not wipe out the template selection anymore

WordPress 6.0.1
Gutenberg 13.8.2 active or inactive
No other plugins active

Twenty Twenty-Two 1.2

I'm going to close this out as fixed, but if you're still able to replicate, please feel free to reopen!
