### ISSUE TITLE
Appearance Widgets editor: edits to widget area containers

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#31959]
Hi all, I just completed the recent Widgets [Call for Testing](https://make.wordpress.org/core/2021/05/12/help-test-the-widgets-editor-for-wordpress-5-8/) and compiled a list of bugs I noticed within the Appearance Widgets editor. I'm adding images as external links to keep this list easy to read!

Here are a few things I noticed about the widget areas containers:

![widget-area-containers](https://user-images.githubusercontent.com/77359364/118728380-106daa80-b802-11eb-9faa-330bfedfccc9.png)

- The [block icon](https://cloudup.com/cKkX2uXRi8Z) is misaligned (spotted in this [blog post](https://shaunandrews.com/2021/05/testing-the-widget-editor-for-wordpress-5-8/) by @shaunandrews)
- There's an extra line at the bottom of the [ellipses menu](https://cloudup.com/cbvAgiEJPfe) that can be removed
- The ellipses menu contains an option for adding the widget area as a Reusable block, which I think should be removed. It works but leads to weird results when you try to insert the block elsewhere 😂
- It’s confusing that the widget areas that are in use are closed when you first enter the screen, and I imagine some users might think that their content disappeared. Could we have empty areas default to closed and areas with items default to open/expanded? (Inactive widgets, if that section remains, could default to closed)

**Comment by critterverse** [comment]
Not related to the widget area containers but adding one small styling tweak for the Appearance screen in case it's possible to fit it in here with these other changes. Could we adjust the spacing between the Update button and Settings toggle to match the post editor? Should be 16px between:

![button-spacing](https://user-images.githubusercontent.com/77359364/118846593-e0261a80-b89a-11eb-95f4-deaa422a3cc8.jpg)

**Comment by talldan** [comment]
https://github.com/WordPress/gutenberg/pull/32262 fixes most of this—it's a bug that the widget area has a toolbar.

> The block icon is misaligned (spotted in this blog post by @shaunandrews)

<strike>I think this is a bug not just limited to the widget editor.</strike> I'll move that and the header adjustments to separate issues (#32263).

edit: It looks like the misaligned block icon has been resolved by a someone else (thank you mystery person).

**Comment by critterverse** [comment]
Nice. I split the only remaining bit of this issue off into https://github.com/WordPress/gutenberg/issues/32278 (as a potential future-facing improvement) and will close this one!
