### ISSUE TITLE
Clicking Mobile Navigation Close Button triggers actions behind it

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#31957]
## Description
When clicking on the CLOSE button for the mobile navigation block with the wp admin bar showing the "admin profile" is triggered as well as the close action.

## Step-by-step reproduction instructions
* Setup a navigation block with responsive controls.
* Go to the view and open the menu
* Close the menu
* Note that in addition to the menu closing the user has navigated to the admin profile page.  (See reproduction)

NOTE: In the recording it looks like multiple clicks trigger the behavior, but I promise there was only one...

## Screenshots or screen recording (optional)
![Screen Capture on 2021-05-18 at 16-32-24](https://user-images.githubusercontent.com/146530/118719682-c8955600-b7f6-11eb-8024-90200ff1862e.gif)

## WordPress information
- WordPress version: latest (wp-env)
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by vcanales** [comment]
Hello! Progress on this is being tracked in https://github.com/WordPress/gutenberg/issues/31765

**Comment by pbking** [comment]
Hrm.  I'm not sure I see how it's related but I'll keep my eye on that one.  Thank you.

**Comment by vcanales** [comment]
@pbking Could you confirm if this is still an issue. Testing manually, it looks like it's been fixed.

![Kapture 2021-09-03 at 16 12 51](https://user-images.githubusercontent.com/1157901/132061009-ce935914-47e0-4c42-a7e7-190d560757dc.gif)

**Comment by carolinan** [comment]
Chrome and Firefox:
I am only able to reproduce this in a way that the profile/logout submenu is shown (because it shows on hover), it doesn't take me all the way to the user profile page.

In Opera, the submenu does not open when the navigation block is closed.


Should also test what happens on mobile (double tap?)

**Comment by pbking** [comment]
I can confirm that this continues to happen in Chrome when using the developer tools to simulate a mobile experience.  I have not experienced this on an actual mobile device.
