### ISSUE TITLE
Migrate editor preferences to new package.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#31965]
## What problem does this address?
The editor more menu is entirely implemented in the edit-post package and not reusable across editors.

The site and widgets editors are duplicating a lot of code to implement more menus, and this seems unnecessary. Much of the options could be implemented in a more generic and reusable way.

## What is your proposed solution?
Either migrate the preferences to the `interface` package or create a new package.

<strike>Interface seems a good fit because it already has some similar UI concepts in the sidebar and tabs that it exposes. These are configurable, so migrating the more menu would involve similar work.</strike>

<strike>The preferences for some editors have now already been migrated to interface, but the plan is to now create a new `preferences` package, so they'll need to be migrated again.</strike>

Update - the new preferences package has now been shipped, and the next step is to migrate the preferences in each of our editors/packages.

----

## Status
- [x] #38873
- [x] #39084
- [x] #39112
- [x] #39115
    - [x] #39132
    - [x] #39180
    - [x] #39337
    - [x] #39604
- [x] #39418
- [x] #39158
- [x] #39153
- [x] #39449
- [x] #39606
- [ ] #39632
- [x] #39707
- [ ] Migrate NUX persisted data?
- [ ] #39672
- [x] #39795

**Comment by noisysocks** [comment]
Maybe a seperate issue, but it's not great at all that https://github.com/WordPress/gutenberg/pull/31925 duplicates `images.js` as it's quite a large file. We need to refactor this to a common package or maybe to `wp-admin/images/`.

**Comment by talldan** [comment]
Now in a pretty good state for migrating 'feature' preferences to the interface package, with PRs open for every editor that implements these preferences.

What other kind of preferences are there? The only remaining preferences live in the post editor:
### Panel preferences
<img width="425" alt="Screenshot 2021-08-20 at 12 37 07 pm" src="https://user-images.githubusercontent.com/677833/130179815-84166a0d-4161-490d-b46b-45d14a4bc161.png">

The way these are implemented is already very generic, and it could easily be brought to other editors. It also fits in quite nicely with the remit of the interface package. However, no other editors have any need to implement this, so it might be worth waiting until a use case arises.

### Editor mode
<img width="278" alt="Screenshot 2021-08-20 at 12 41 44 pm" src="https://user-images.githubusercontent.com/677833/130180142-ff920ec1-7b8b-4420-a106-2f5239dbd8f8.png">

This is also very specific to the post editor, and might not be something to migrate to other editors. Though there is a feature request to bring this to the widget editor (#33518). 

### Block Manager / Hidden Block Types
<img width="542" alt="Screenshot 2021-08-20 at 12 44 50 pm" src="https://user-images.githubusercontent.com/677833/130180369-9d7a4b83-63eb-4d20-830f-146face2ae12.png">

Very much a feature that is desired in other editors, so this could be refactored, hover I'm not convinced that the interface package is the right option. Interface deals more with UI abstractions, and this is very block specific. It could perhaps be its own package?

### Default block style / Preferred style variations
<img width="278" alt="Screenshot 2021-08-20 at 12 47 04 pm" src="https://user-images.githubusercontent.com/677833/130180558-c4d5db2e-0254-4bea-ba9e-70a5d660e34d.png">

This is in the `edit-post` store, so it doesn't feel like this feature was implemented in the right way originally—it'll only work in the post editor. Where should it live? Again a very block-oriented feature. An option could be a 'Block Preferences' package that has this and the Block Manager.

### localAutosaveInterval
It seems like this is outside the remit of this change. I don't think there's a user facing way to modify this value. I'm not completely sure why it needs to be persisted to local storage. Would be good to understand more about that.

**Comment by talldan** [comment]
The latest feedback (https://github.com/WordPress/gutenberg/issues/24370#issuecomment-910067146) is to create a new 'preferences' package. I don't really have the bandwidth to handle that, so I'll hand this over to another willing contributor.

**Comment by talldan** [comment]
Now things are a bit calmer again following 5.9 I'll work on the new preferences package.

**Comment by annezazu** [comment]
Looks like this work has been completed! I'm going to close this out as a result but let me know if it needs to be reopened.
