### ISSUE TITLE
Spacing Controls Don't Allow Decimals

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#31964]
When adding margin or padding, there is no way to add a decimal in the number.  These are useful for at least `rem`, `em`, and `%` values.

To replicate, open the margin/padding spacing control and enter a number with decimal like `0.5` or `2.5`.  After clicking out of the number box, the control will automatically change these to `1` and `3`, respectively.

Before:

![unit-control-decimal](https://user-images.githubusercontent.com/1816309/118745331-892d3080-b81b-11eb-9977-7ec5c3f35633.jpg)

After:

![unit-control-changed](https://user-images.githubusercontent.com/1816309/118745329-88949a00-b81b-11eb-90ff-22d4a6f4bff3.jpg)

**Comment by justintadlock** [comment]
Also, negative values are not allowed either.  I'm not sure if that is related enough for this ticket or should have a separate ticket of its own.

**Comment by aristath** [comment]
If I'm not mistaken this is already in trunk and will be included in v10.7. Related PR: https://github.com/WordPress/gutenberg/pull/30376

**Comment by carolinan** [comment]
It is not solved in trunk 🤔

**Comment by aristath** [comment]
PR #32692 fixes this :+1:

**Comment by justintadlock** [comment]
Is this fix in version 10.9.1?  I am still unable to add something like `2.5` with `rem` for the padding control. It bumps it up to `3`.

**Comment by aristath** [comment]
> Is this fix in version 10.9.1? I am still unable to add something like 2.5 with rem for the padding control. It bumps it up to 3.

I just checked and it was not included in v10.9.x. It will be part of v11 :+1:
