### ISSUE TITLE
Post Author Block: Inconsistent Front/Back End Avatar Markup and Classes

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#31962]
The `<img>` tag for the Post Author block avatar outputs the following on the front end:

```
<img alt="" src="#" class="avatar avatar-48 photo" height="48" width="48" loading="lazy">
```

In the editor, the HTML looks like:

```
<img width="48" src="#" alt="Justin Tadlock">
```

The editor should at least have the same `.avatar` class.

Also, the `alt` text should match.  Is there a reason it's empty on the front end?

**Comment by aristath** [comment]
I think this block is about to get completely refactored and AFAIK the plan is to convert it to a wrapper with multiple inner blocks (I could be mistaken though). That's why it's also not going to be included n WP5.8, there's lots to be done here :+1:
