### ISSUE TITLE
Add user facing support docs for widget block editors

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#31978]
## What problem does this address?
Currently, the Help links in the widget editors link to this support article - https://wordpress.org/support/article/wordpress-editor/.

But there's quite a lot of content in that article that isn't relevant in the widget editors. (fullscreen mode isn't present in the other editors, and all the screenshots don't match).

## What is your proposed solution?
Either a restructure of that article, or separate pages for the widget editors.

**Comment by noisysocks** [comment]
From @annezazu in [Slack](https://wordpress.slack.com/archives/C02RP4WU5/p1625705913305000):

> **Gutenberg End User Documentation Update**
> - Template editor draft ready for review: https://wordpress.org/support/wp-admin/post.php?post=14632189&action=edit 
> - Query Loop block draft ready for review: https://wordpress.org/support/wp-admin/post.php?post=14633622&action=edit Of note, the Post Template block isn’t mentioned in here. I tried to use a similar format as the Latest Post block.
> - Block-based widgets editor draft ready for review: https://wordpress.org/support/?post_type=helphub_article&p=14633472&preview=true Likely need to schedule updates to the other widget pages to reference this.
> Tomorrow I’m going to focus on a List View page and Block patterns page (directory, integrated patterns, patterns in inserter).

**Comment by annezazu** [comment]
To close the loop: https://wordpress.org/support/article/block-based-widgets-editor/
