### ISSUE TITLE
.has-inline-background CSS class styling adjustments for multiline backgrounds

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#31988]
using inline backgrounds in text might need some styling adjustments to prove they are working multiline.

This is what the CSS class currently looks on multiline spans without adjustments:
![multiline-current](https://user-images.githubusercontent.com/41627893/118798666-2f217f00-b89e-11eb-9075-e29100796233.PNG)

But adding:
```css
display: inline; /* just to ensure display does not get inherited from anywhere */
-webkit-box-decoration-break: clone;
```

would adjust the styling to ensure multiline inline backgrounds work correctly without adjusting it in the users theme
![multiline-correct](https://user-images.githubusercontent.com/41627893/118798762-4ceee400-b89e-11eb-8740-af2915cf5031.PNG)

**Comment by talldan** [comment]
@bfiessinger Please could you report this again, but this time using the provided issue templates. This issue is lacking lots of information—I'm not sure what block it refers to as a start.

**Comment by bfiessinger** [comment]
@talldan it is not a block per se it is about the inline background formatting option for textual content.
But sure I can reinit this issue with more information.

**Comment by bfiessinger** [comment]
@talldan I'm sorry just noticed that this is not a formatting option by Gutenberg rather it comes from the editorskit plugin...

**Comment by talldan** [comment]
Ah ok, that's why I wasn't sure what it was about 😄
