### ISSUE TITLE
Discussion: Block Theme Developer Documentation

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#31999]
As work ramps up to encourage creation of new Block Themes leading up to the Block Theme functionality rolling into core it seems like now is a good time to discuss the future direction and home of developer oriented block theme documentation.

I would like to recommend that block theme documentation be moved to the theme handbook for ongoing development. I imagine that this discussion will need to involve core teams that may not be actively involved here on Github but as the docs have been developed as a part of the block editor handbook so far I wanted to raise the topic here as a first step.

One concern I have is that there may be overlap between theme development topics, block editor topics, and end user focused topics. This may require either linking to central locations and breaking up the continuity of documentation or managing content in multiple locations and with different approaches with the end audience in mind for each location.

I would love to hear any thoughts or concerns as well as general discussion about how best to move this forward. I believe that the better the theme documentation is the easier it will be to encourage adoption of the new theme development options.

**Comment by carolinan** [comment]
This has been discussed with the documentation team here:  https://make.wordpress.org/docs/2021/02/18/a-home-and-a-name-for-site-editor-documentation-full-site-editing-feature/
And in this issue https://github.com/WordPress/gutenberg/issues/29031#issuecomment-792753768


In my _opinion_, the theme developer handbook is not in a state where it can accept new content.  The current content is out of date and needs to be rewritten for a more modern workflow. 
Waiting for the current theme developer handbook to be rewritten would only delay the documentation and combining it would be confusing for readers.

**Comment by carolinan** [comment]
Only a limited number of people have access to the theme developer handbook, compared to the documentation on GitHub that everyone can contribute to.

One of the big hurdles for writing documentation anywhere, is obvious from this pull request: https://github.com/WordPress/gutenberg/pull/31269
**There are too many options.** There are so many ways to create templates and template parts that both describing them and trying to learn them becomes overwhelming.
How do we decide where to set the limit, should only one way be documented? Two? Four?

**Comment by carolinan** [comment]
I will continue to think about this. I am struggling because I do not see a clear path for how the documentation can be kept separate enough to not cause confusion and contradictions. I am looking forward to reading input from others.

Maybe the theme developer handbook needs a decision tree and three separate sections:
PHP, HTML templates, and no code (export from site editor).
But this is made more difficult by predictions that many early themes will be combining existing PHP templates and theme.json.

**Comment by annezazu** [comment]
I personally love the idea of a decision tree setup and think that'll be advantageous especially as there will be various "types of themes" in the future: 

- Classic = traditional theme we all are used to.
- Hybrid = traditional theme that opts into aspects of FSE features like opting into the block widget editor or theme blocks.
- Universal theme =  themes that can work in both the customizer (classic) and site editor. This is still a WIP idea :D 
- Block theme = FSE ready theme

**Comment by DaisyOlsen** [comment]
I'd hate to see new documentation not move forward because other documentation needs to be updated. That seems counterproductive. I want to think through the decision tree more also. 

My initial feeling is that we will pave some paths for Hybrid and Universal themes but I don't think they should be a top level decision tree. I could see value in including details on how to opt into some aspects of FSE being part of the Classic theme route and including ways to allow the theme to work in the customizer could be part of the Block theme route. I really only see two options at the top level. Too many options will only confuse things further.

**Comment by mkaz** [comment]
I think in the near term we should add a link to the Theme Handbook to the current block themes tutorial so people looking can find the documentation. 

For longer term, I think we should have a single spot for all Theme documentation regardless of theme type (PHP, HTML)

I personally prefer documentation in GitHub because it is easier and clear how to get access and contribute. The current Theme handbook is a bit opaque on where to go, how to edit, who to ask, and it is really hard to collaborate and show work in progress.

So my radical idea, which I'm making up right now, and probably haven't fully thought out, would be to create a new Theme handbook as a new GitHub repository filled with markdown files that publishs to `developer.wordpress.org/themes`. We could then structure that handbook taking into account the multiple ways to create themes now.

@carolinan I wasn't quite clear what issue you were highlighting by point out that PR, I believe you were saying that it is complex and trying to do it all in a single page is a challenge. I would agree and having a whole handbook section for Block Themes would be great. If I misinterpreted please let me know.

**Comment by carolinan** [comment]
> As we get close to releasing FSE into core, questions have come up about what the feature will be officially called within the WordPress Dashboard.
This is also currently a blocker for the Documentation team (see more details in this post on Make). The sooner a decision is reached on the name, the sooner we can spin up proper documentation for it.

https://github.com/WordPress/gutenberg/issues/29630

**Comment by carolinan** [comment]
A new repository could be created for the new block theme documentation and the classic _(if that is really the name that is decided on)_ theme documentation can be be updated while it is moved over.

But that kind of decision is not taken here in the Gutenberg plugin GitHub repository. This decision doesn't primarily involve the core editor team but the docs, meta, and themes teams, and I assume, it must first be approved by WordPress leadership. And realistically this would still be a project that would span over months.

**Comment by mkaz** [comment]
I wasn't making a decision it was just a thought, I even couched it saying I wasn't even sure if it was a good thought. But we have to raise the ideas to see what people think. If no one likes the idea, then fine. 

A more productive response could've been, "ah that's an interesting idea I like it, maybe we should raise it in X, Y, and Z and see what others think." or the counter, which is still productive could've been "I'm not sure I like this idea, it seems overly complicated and people are more comfortable editing the current handbook."

The way you responsed feels to me you are saying, "You're doing it wrong. Don't do anything."

**Comment by DaisyOlsen** [comment]
I wanted to circle back and mention that the reason I put my initial discussion here was because the documentation that does exist is located in the Block Editor handbook which is managed from this repo since the authors of those docs will be active here it seemed reasonable to ask my question here. I did not intend to omit any previous conversations so thanks for including them here for reference.

My intentions here are to find a way to document what we know and be prepared to change what needs to change. As a developer I would prefer incomplete documentation that has frequent updates over slow-moving documentation or worse, no documentation. I know that this is a very difficult thing to navigate and there are no easy answers.

**Comment by carolinan** [comment]
> the authors of those docs will be active here

That is my fear. By moving documentation for features that are under _ongoing development_ or still experimental and frequently updated, from the current handbook to the theme handbook, it makes it harder for the developers to update the docs will making changes to existing features and adding new features.
It will no longer be something that they can just include in their pull request.

Instead the responsibility to:
1. Keep track of all changes (which is already difficult with the amount of notifications)
2. Write documentation

-Is placed on the themes team representative who's current volunteer assignment within the team is the handbook.
It is not possible for the themes team to take on this responsibility.
And being asked to take on this responsibility is not short term. _It is not about having help from people writing docs for two weeks_, it is long term.

----
**Suggestions for preparing the current theme handbook, short term**
Place a notice on the front page of the themes handbook linking to the documentation in the block editor handbook. **-[Done](https://developer.wordpress.org/themes/)**

**Suggestions for preparing the current theme handbook, long term**

1.  Identify which sections in the current theme handbook that are valid for both classic and block themes. Place these pages together. **_-In progress_**
2. Decide on a name for a new "classic theme" section, **-Done [The name will be classic themes.](https://make.wordpress.org/core/2021/05/26/core-editor-meeting-notes-26-may-2021/)**
3. Move all pages with documentation only valid for classic themes under this new menu item. 
4. Create a page explaining the difference between classic and block themes. (Only two formats for now)
5. Identify pages that need to be written for block themes. **Non experimental features only, I suggest theme.json version 1 but not the template system.** Place the new pages under a new "block themes" menu item.
6. Eventually, place information about Hybrid/Universal theme info under Advanced.

**Comment by colorful-tones** [comment]
> My initial feeling is that we will pave some paths for Hybrid and Universal themes but I don't think they should be a top level decision tree. I could see value in including details on how to opt into some aspects of FSE being part of the Classic theme route and including ways to allow the theme to work in the customizer could be part of the Block theme route. I really only see two options at the top level. Too many options will only confuse things further.

I agree 💯

**Comment by carolinan** [comment]
Step 1-5 has been completed.
The [block theme section](https://developer.wordpress.org/themes/block-themes/) of the Theme Developer handbook has been published.
There is still room for improvements and more examples but it is a good start.

What remains is to remove some duplicate content from the block editor handbook and add a note explaining that the documentation in the block editor handbook are for features that require Gutenberg,

**Comment by ryanwelcher** [comment]
Closing as per @carolinan in https://wordpress.slack.com/archives/C02QB2JS7/p1680183994738109
