### ISSUE TITLE
Remove "change widget" action from legacy widget toolbars

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32004]
This action feels unnecessary and like it could be removed entirely. 

<img width="293" alt="image-14" src="https://user-images.githubusercontent.com/77359364/118847238-870ab680-b89b-11eb-982c-a1108afc4deb.png">
 
Originally noted by @shaunandrews while [completing the recent Call for Testing](https://shaunandrews.com/2021/05/testing-the-widget-editor-for-wordpress-5-8/).

**Comment by noisysocks** [comment]
I'm not tied to it.

I suppose the only nice affordance it offers is if you accidentally pick the wrong widget type from the dropdown.

But:

- I doubt a user would even discover it.
- You can always press Undo.

**Comment by draganescu** [comment]
@critterverse @noisysocks there is a PR which removes the button. I think it's a good idea, because I was about to open another issue that once that is clicked there was no way back.
