### ISSUE TITLE
Failure to parse theme.json should be a lot more obvious

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#32009]
## Description

A theme’s global styles are defined in a file called theme.json.

It’s a complicated file in JavaScript Object Notation (JSON ) format.

There are many settings which can have lots of values.

- You have to get the structure and the syntax correct.
- If you make any mistake with the syntax then the Global Styles aren’t set.
- You don’t get any messages.
- Everything just looks all wrong.
- If you do make any changes, use a JSON validator to check your syntax.
- And then check it again for semantics.

>  You don’t get any messages.

Well, something may be logged to PHP error log. 
```
[19-May-2021 17:06:24 UTC] Error when decoding file schema: Syntax error
```

## Step-by-step reproduction instructions
1. Install and activate an FSE theme such as TT1 blocks
2. Edit site
3. View Global Styles
4. Delete the first character from `theme.json`
5. Edit site
6. View Global Styles
7. Notice the difference

## Expected behaviour
The fact that `theme.json` could not be parsed should be made immediately obvious to the user.
This is going to happen an awful lot in the next few months. 
The ability to perform problem determination needs to be significantly improved.

## Actual behaviour
It just looks awful.

## Screenshots or screen recording (optional)

Screen capture after step 3.
![image](https://user-images.githubusercontent.com/2474435/118855110-5b082900-b8cd-11eb-92ba-50aa4d2300d0.png)

Screen capture after breaking theme.json in step 4.
![image](https://user-images.githubusercontent.com/2474435/118854998-37dd7980-b8cd-11eb-8984-4148d848cf88.png)

## WordPress information
- WordPress version:  5.7.2
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  TT1 blocks

## Device information
- Device:  Desktop
- Operating system: Windows 
- Browser: Chrome

**Comment by skorasaurus** [comment]
Want to share that this should be prioritized: 

not creating any feedback loop or indications that a theme.json file is not working will create a really negative and frustrating experience for theme developers who will be unsure of how to fix their problem: they'll wonder: "is it a problem with my theme? is it a problem with gutenberg?"

I've ran into this a couple times as well and it was frustrating.
