### ISSUE TITLE
Theme-json.md shouldn't include comments in the JSON examples

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#32007]
## Description
In the examples for theme.json in docs/how-to-guides/themes/theme-json.md
there are a number of comments in the JSON examples.
If anyone tries to copy and paste the example verbatim into theme.json

1. It won't work
2. theme.json will not parse
3. the user may not understand why it doesn't work

There are two problems to solve. This issue is just about the documentation. 

## Step-by-step reproduction instructions

1. Install and activate an FSE theme, eg Mayland Blocks.
2. Copy the _custom colors only for a paragraph block_ into theme `theme.json`
3. Add a Header block
4. View Settings > Color.  

```
{
	"version": 1,
	"settings": {
		"color": {
			"custom": false // Disable it for all blocks.
		},
		"blocks": {
			"core/paragraph": {
				"color": {
					"custom": true // Paragraph overrides the setting.
				}
			}
		}
	}
}
```

5. Remove the offending comments
6. Retry.

## Expected behaviour
There shouldn't be a Custom color link.

## Actual behaviour
There is.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2474435/118852469-bab10500-b8ca-11eb-9ab8-60c9d71f8843.png)

After steps  5 and 6
![image](https://user-images.githubusercontent.com/2474435/118853185-6195a100-b8cb-11eb-9de0-19a65efd8470.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated? No 
- Are you using a default theme (e.g. Twenty Twenty-One)? No. Mayland Blocks
- (since my version doesn't have `theme.json` yet)

## Device information
- Device: Desktop 
- Operating system:  Windows 10
- Browser: Chrome

**Comment by bobbingwide** [comment]
PR #32040 fixes this issue.

**Comment by aristath** [comment]
#32040 was merged, closing this one.
