### ISSUE TITLE
Block toolbar and classic block header awkwardly obscures Notices

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#32000]
## Description
The Classic Editor block obscures notices.

## Step-by-step reproduction instructions
Create a post with a Classic Editor block at the beginning, and enough filler text below it to allow scrolling.
Publish it.
Type some random changes in the post, let it idle long enough to generate an auto save, then leave the page. (This step is just to get a notice displayed on the page when we reload it.)
Edit the post. You should now have a notice about the Autosave.
Scroll down so that the notice overlays the Classic Editor block.

## Expected behaviour
The Notice div should remain on top, with my content going behind it.

## Actual behaviour
The Classic Editor box that says "Classic" shows up in FRONT of the notice, even though the content of the classic block goes behind it.
![2021-05-19 09_12_18-Edit Post ‹ Gutenberg — WordPress](https://user-images.githubusercontent.com/945157/118829085-70f0fc00-b883-11eb-92a9-553e39eb0b31.png)

## Screenshots or screen recording (optional)
Attached

## WordPress information
- WordPress version: 5.7.3
- Gutenberg version: whatever comes with 5.7.3
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? yes

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome: 90.4

**Comment by MadtownLems** [comment]
I've noticed that this extends beyond just obscuring Notices. The "Classic" box sits in front of other 
![2021-05-19 12_23_11-Edit Page ‹ Conv7 — WordPress](https://user-images.githubusercontent.com/945157/118858596-f33ae980-b89e-11eb-8b85-23e5af0b3f07.png)
block controls as well. See attached screenshot.

**Comment by talldan** [comment]
The block toolbar also overlaps notices:
<img width="910" alt="Screenshot 2021-05-21 at 10 44 36 am" src="https://user-images.githubusercontent.com/677833/119074420-961b7100-ba21-11eb-893b-884c30680ee5.png">

**Comment by paaljoachim** [comment]
I noticed the same bug. I added this issue: https://github.com/WordPress/gutenberg/issues/32115 (Which I will now close as a duplicate.)

**Comment by jasmussen** [comment]
I have a solution, if not a fix, in #32238.
