### ISSUE TITLE
Theme's color palette no longer returned via Block Editor settings

### ISSUE THREAD

**Issue by lukecarbis** [WordPress/gutenberg#32027]
## Description
`wp.data.select( 'core/block-editor' ).getSettings().colors` no longer returns theme colors.

## Step-by-step reproduction instructions
1. Disable Gutenberg
2. Enable a theme with a colour palette (like Twenty Twenty-One)
3. Open the Editor
4. Run this in the console: `wp.data.select( 'core/block-editor' ).getSettings().colors`

At this point, note the colours – they're the colours that your theme has defined.

5. Enable Gutenberg
6. Open the Editor
7. Run the same command in the console again

Notice that the colours returned are NOT the theme colours, but default Editor colours

## Expected behaviour
The Block Editor "colors" setting would return the color palette defined by the theme.

## Actual behaviour
The Block Editor "colors" setting returns an array of default WordPress colours.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: MacBook Pro
- Operating system: MacOS 11.3
- Browser: Safari 14.1

**Comment by lukecarbis** [comment]
Context: My block relies on access to the theme's default colour scheme. If this is an intentional breaking change, I'd love if someone could help with a way to get the theme's default colours.

**Comment by youknowriad** [comment]
@nosolosw Did we include a shim for these in the Core patch?

**Comment by oandregal** [comment]
Yeah, in core and Gutenberg 10.7 the `settings.color` has the color palette.

Note, however, that since we landed https://github.com/WordPress/gutenberg/pull/31669 the color palette includes both theme and core colors. Jorge has prepared a PR https://github.com/WordPress/gutenberg/pull/32225 that will make the palette to only contain the theme colors. I've marked that PR as "fixing this issue".

**Comment by oandregal** [comment]
There's an alternative to https://github.com/WordPress/gutenberg/pull/32225 at https://github.com/WordPress/gutenberg/pull/32358

**Comment by oandregal** [comment]
This has been fixed by https://github.com/WordPress/gutenberg/pull/32358
