### ISSUE TITLE
Add a snackbar with Welcome Guide on first pattern save in Patterns or in editor

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32020]
**Updated June 29th, 2023**

Previously, an idea came up around adding a snackbar that confirms when a reusable block has been saved from the toolbar https://github.com/WordPress/gutenberg/issues/29871#issuecomment-802039607. This experience has since evolved with patterns and reusable blocks merging into a single concept of patterns: synced (previously reusable blocks) and unsynced (patterns as we know them today). To help onboard folks to this change, it's worth considering a snackbar shared contextually upon first creating. 

Pulling from prior designs with just reusable blocks, here's how the snack bar and guide could look (note: one new animated asset would need to be created for the guide). The snack bar could show up on each _Save_ from the toolbar, while the guide would only appear if the user clicks the "Learn more" link while the snack bar is visible.

<img width="1440" alt="RB-snackbar" src="https://user-images.githubusercontent.com/77359364/118860126-03f05d00-b8a9-11eb-9693-4ec050846ffd.png">
<img width="1440" alt="Rb-guide" src="https://user-images.githubusercontent.com/77359364/119141522-5baad780-ba13-11eb-9b2d-756ed9d963e3.png">

^ Also might be nice to link to external documentation to learn more.

**Comment by thisissandip** [comment]
PR: https://github.com/WordPress/gutenberg/pull/32464

I have implemented the save button option for Reusable Blocks in the block toolbar and added a snackbar whenever the blocks are saved. The snackbar's learn more opens the welcome guide.

Since the image (gif) for the welcome guide is not ready yet. I have kept a plain background in its place.
I will add the image whenever it's made available.

**Comment by thisissandip** [comment]
@critterverse How can I get in touch with someone who can help me with the welcome guide asset?

**Comment by richtabor** [comment]
Could be interesting if this was triggered in context; say the first time you click "Create pattern" in the block toolbar, or within the Site Editor > Patterns view. 

<img width="581" alt="CleanShot 2023-06-29 at 12 08 31" src="https://github.com/WordPress/gutenberg/assets/1813435/9f5ddf95-1303-473f-9104-5d223282f13b">

**Comment by annezazu** [comment]
Noting here that we are merging concepts with patterns and reusable blocks at this stage: https://github.com/WordPress/gutenberg/pull/51144 As a result, the design/concept remains interesting but needs to be updated. Going to update this issue in light of that and encourage you @thisissandip (if you are still around!) to update your PR in light of the above. 

Adding this to 6.3 triage board as well in case it's something we can iterate on to help onboard users to this new experience.

**Comment by annezazu** [comment]
I'm having a hard time seeing this happen in time. Going to move out of the 6.3 board for now and can readd if @WordPress/gutenberg-design thinks they can move quickly on this.

**Comment by Mamaduka** [comment]
Now that Reusable blocks got revamp as Patterns (synced, unsynced, partial), the original issue is probably no longer valid.

Should we close this and associated PR? cc @kevin940726, @talldan

**Comment by talldan** [comment]
@Mamaduka Sounds reasonable to me, as I don't recall any recent mention of a welcome guide for patterns.

If there is a desire to explore it, then a new issue would be good as it'll need to be pretty different to what's discussed in this issue.
