### ISSUE TITLE
Investigate unstable meta boxes test

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#32034]
This test has been skipped in #32031 because it was too unstable in trunk.

cc @ellatrix @youknowriad

**Comment by JustinyAhin** [comment]
The skipped test seems to be more stable now. @youknowriad does it make sense to enable it back?

**Comment by youknowriad** [comment]
@JustinyAhin That's fine by me, how do you know that it's stable now?

**Comment by JustinyAhin** [comment]
> @JustinyAhin That's fine by me, how do you know that it's stable now?

I just pushed this PR (https://github.com/WordPress/gutenberg/pull/35594) with my changes. I've added a couple of assertions to ensure that the latest post block correctly appears.
