### ISSUE TITLE
Pre-defined background gradients on list blocks are still enabled after custom block coloring has been disabled in functions.php

### ISSUE THREAD

**Issue by nasajones** [WordPress/gutenberg#32047]
## Description
After disabling custom colors in the theme's functions.php file, users are still able to select pre-defined gradient backgrounds for list blocks.

## Step-by-step reproduction instructions
1. Install and activate a theme
2. Install and activate the Gutenberg plugin
3. Disable custom coloring in the theme's functions.php file:
`add_action( 'after_setup_theme', 'disable_custom_colors' );`
`function disable_custom_colors() {`
`add_theme_support( 'disable-custom-colors' );`
`add_theme_support( 'disable-custom-gradients' );`
`add_theme_support( 'editor-color-palette' );`
`add_theme_support( 'editor-gradient-presets', [] );`
`}`

## Expected behaviour
Coloring options for all blocks should be disabled.
- Pre-defined text color
- Custom text color
- Pre-defined solid background color
- Custom solid background color
- Gradient background color
- Pre-defined link color
- Custom link color

## Actual behaviour
Pre-defined background gradients are not disabled for list blocks.

## Screenshots or screen recording (optional)
Paragraph block, colors enabled:
![github1](https://user-images.githubusercontent.com/63472992/118986472-669b3480-b94d-11eb-96f7-7df90446ba85.png)

Paragraph block, colors disabled:
![github2](https://user-images.githubusercontent.com/63472992/118986545-761a7d80-b94d-11eb-9431-db4bcbd8dc4d.png)

List block, colors enabled:
![github3](https://user-images.githubusercontent.com/63472992/118986572-7adf3180-b94d-11eb-8d03-83cba1b7dbec.png)

List block, colors disabled:
![github4](https://user-images.githubusercontent.com/63472992/118986592-7fa3e580-b94d-11eb-97b6-0374f4c9d565.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? This issue has been verified with Twenty Twenty-One 1.3 and Genesis Pro 3.3.3.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 90

**Comment by nasajones** [comment]
It looks like this may have been fixed with the release of Gutenberg 10.8.

**Comment by jorgefilipecosta** [comment]
Hi @nasajones, thank you for reporting this issue it was fixed in https://github.com/WordPress/gutenberg/pull/32358, and on the next Gutenberg release the issue should not be preset.
