### ISSUE TITLE
Latest Posts grid layout throws uncaught ReferenceError and does not render

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#32045]
## Description

When adding a Latest Posts block using the grid layout the editor throws the following error:

> Uncaught ReferenceError: Cannot access 'P' before initialization

This is because [`hasPosts`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/latest-posts/edit.js#L391) is defined after the `inspectorControls` are defined.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to https://frontenberg.tomjn.com/
2. Add a _Latest posts_ block
3. Change it to grid layout.

## Expected behaviour

The block should render latest posts in a grid.

## Actual behaviour

The block encounters an error and doesn't render

## Screenshots or screen recording (optional)

![gutenberg-bug](https://user-images.githubusercontent.com/302736/118994570-d49b2800-b95c-11eb-8bab-cb4016d5b7aa.gif)

## WordPress information
- WordPress version: 
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been reported in https://github.com/WordPress/gutenberg/issues/31847 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
