### ISSUE TITLE
build-plugin-zip.sh doesn't include *.js files

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#32050]
A user of today's Gutenberg nightly detected a missing files issue

"the front end is looking for `plugins/gutenberg-nightly/build/block-library/blocks/navigation/frontend.js`
And throws a 404 error.

Turns out the [build-plugin-zip.sh](https://github.com/WordPress/gutenberg/blob/4060caa5a4f3f053e90913b4ce1607ea8d63934c/bin/build-plugin-zip.sh) doesn't include *.js files 
![Screen Shot 2021-05-20 at 11 04 35 AM](https://user-images.githubusercontent.com/39980/119002872-3f4b6400-b95b-11eb-9240-4d099ab366a5.png)

Thanks to @bobbingwide and @gziolo for troubleshooting this with me.

**Comment by youknowriad** [comment]
cc @vcanales @jasmussen

**Comment by vcanales** [comment]
Thanks for the heads up — [fix is waiting to be merged here.](https://github.com/WordPress/gutenberg/pull/31917)

I'd appreciate some eyes, since checks have been refusing to run, and/or fail randomly.

**Comment by jasmussen** [comment]
@youknowriad does the above fix need to be in the RC?

**Comment by gziolo** [comment]
@vcanales, this fix is not enough. The file needs to be listed in the script that builds the zip file.

**Comment by vcanales** [comment]
> @vcanales, this fix is not enough. The file needs to be listed in the script that builds the zip file.

👍 indeed it looks like it's a two parter. I can add that change to the PR waiting to be merged.
