### ISSUE TITLE
Unable to use shift-click to select multiple nested blocks

### ISSUE THREAD

**Issue by walkersands** [WordPress/gutenberg#32056]
## Description
Cannot select blocks together using shift-click if within innerblocks.

## Step-by-step reproduction instructions
1. Add Columns block
2. Add multiple blocks to a column
3. Attempt to select them with the mouse by shift-clicking

## Expected behaviour
Should show block toolbar with option to group.

## Actual behaviour
No toolbar. Sidebar says "No block selected".

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
## Device information
- Device: Laptop
- Operating system: MacOS Catalina
- Browser: Brave

**Comment by talldan** [comment]
@walkersands Thanks for reporting this. I just tried testing in my dev environment (which has more recent code than 10.6.2)  and it seems to work ok:
<img width="653" alt="Screenshot 2021-05-21 at 10 28 15 am" src="https://user-images.githubusercontent.com/677833/119073182-60758880-ba1f-11eb-99de-f0b3aea54024.png">

So it could either be fixed or something else is causing the problem. How did you go about selecting the blocks? Easiest way seems to be using shift and arrow keys, but my first attempt was to shift-click, which didn't work (but maybe it should).

I was also wondering which blocks you're trying to group? Maybe there's an issue with a particular block.

**Comment by walkersands** [comment]
Shift + arrow key seems works in all scenarios; shift-click works for top level items, but not innerBlocks, which leads me to believe this is unintended behavior?
Block type does not seem to matter. I've updated my original post to be specific to shift-click.

**Comment by talldan** [comment]
@walkersands Thanks for updating. I see what you mean about the difference between top-level and nested blocks. It does look like a bug.

I made some further changes to the issue title and description as this seems like a problem more related to block selection than grouping—grouping does seem to still work if a user is able to select the blocks via other means.
