### ISSUE TITLE
Template editor and front-end alignment styles do not match

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#32069]
## Description
In template editing mode, the template editor and front-end alignment do not match by default.

## Step-by-step reproduction instructions
- Activate tt1-blocks (a theme that opts into the new layout system by providing [default content sizes](https://github.com/WordPress/theme-experiments/blob/master/tt1-blocks/theme.json#L111-L114) )
- Go to the post editor and create a new template
- Add some blocks
- Preview or publish the template

@annezazu made a [recording](https://user-images.githubusercontent.com/26996883/118719108-481a2980-b7e5-11eb-92a9-e35864b5589d.mov) of this also.

## Screenshots or screen recording (optional)
Editor | View
------- | -------
<img width="1904" alt="Screen Shot 2021-05-20 at 5 08 04 PM" src="https://user-images.githubusercontent.com/5375500/119049845-e6d59000-b975-11eb-96ab-f3ff84f79109.png"> | <img width="1904" alt="Screen Shot 2021-05-20 at 5 07 44 PM" src="https://user-images.githubusercontent.com/5375500/119049769-ce657580-b975-11eb-91ae-2246774a3221.png">

**Comment by youknowriad** [comment]
The Post Editor automatically applies the "layout" config (sizes), it seems that config shouldn't apply to the template mode as well. Template mode should work more like the site editor (no default layout applied)
