### ISSUE TITLE
Customizer Widgets: default to floating or fixed toolbar?

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32062]
Hi all, creating this issue to discuss some issues around the Customizer top bar area. We're currently seeing some awkward overlap between the floating block toolbar and the top chrome of the Customizer Widgets screen:

https://user-images.githubusercontent.com/77359364/119016947-7f651380-b968-11eb-9eef-ec877c5ad089.mov

A long term solution has been proposed in #32061, and a short-term bug fix identified in #32060. 

In the meantime, one solution that was proposed in https://github.com/WordPress/gutenberg/issues/30912#issuecomment-842801857 was to default to the fixed version of the block toolbar that was merged in #31589. There are some issues with either direction — but the issues with the fixed toolbar seem like more major usability issues due to having to rely so heavily on horizontal scroll in the narrow Customizer sidebar. Here's a video of me struggling to use the fixed toolbar in this context:

https://user-images.githubusercontent.com/77359364/119017729-4b3e2280-b969-11eb-9332-4de096efc300.mov

(Discoverability of the horizontal scroll is one issue but there are several others. Some improvements for the scrolling have been discussed in https://github.com/WordPress/gutenberg/issues/30720#issuecomment-824108601)

Because of this, I would lean towards keeping the default as the floating toolbar. This version of the toolbar also has several usability advantages over the fixed version such as proximity to the selected block, parent selectors, drag handles, etc.

That leaves the issue of the awkward overlap that happens with the customizer top bar and long toolbars. If it’s possible to bring the toolbar all the way to the foreground so that it scrolls in front of the top bar, I think it would help. It's not an ideal solution but at least it would look less like a bug than when the toolbar goes behind the top bar:

https://user-images.githubusercontent.com/77359364/119018425-0f578d00-b96a-11eb-93d0-9da134d869ee.mov

Would love to hear some other opinions about which version of the toolbar would be the better default until a solution like #32061 can be implemented!!

**Comment by shaunandrews** [comment]
Without a touchscreen, trackpad, or an Apple Magic Mouse, it is incredibly difficult to use a horizontally scrolling container. With my Logitech mouse I'm unable to scroll horizontally in my browser unless I turn on the "always display scrollbars" setting in Mac OS and drag the scrollbar. On Windows the scrollbar always appears, and the only way to scroll is to click and drag the scrollbar.

The horizontal scrolling behavior for the block toolbar was always intended to be a solution for touchscreen devices, and relying on it for a desktop-sized experience seems problematic.

**Comment by priethor** [comment]
I totally agree the horizontal scrollbar is challenging, probably creating more issues than the ones it solves. I think we should at least fix #32060 for 5.8 and, if possible, continue with #32061.

**Comment by critterverse** [comment]
Closing this in favor of #32061!
