### ISSUE TITLE
Widget Screen: Dirty state is not reset after saving

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#32074]
## Description
When adding a new block, sometimes you have to save changes twice to clear unsaved changes.

## Step-by-step reproduction instructions
1. Go to the new widgets screen.
2. Add a new block to a widget area.
3. Save changes.
4. See snackbar appear.
5. "Update" button isn't disabled.

## Expected behaviour
The "Update" button should be disabled after saving changes the first time.

## Actual behaviour
Have to save changes twice to see a visual indication that they are saved.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/240569/119079238-c60a4a80-ba08-11eb-9636-e52be8b37708.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7/trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by noisysocks** [comment]
Confirmed.

**Comment by Mamaduka** [comment]
I will try to look into this issue later this week.

**Comment by noisysocks** [comment]
Related to this is that you see a "Are you sure?" prompt when you navigate away from the widgets screen after saving.
