### ISSUE TITLE
WP.org: Multiple weirdness/bugs happening.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32089]
## Description

I vaguely remember someone. I think it might be @desrosj mentioned that something was going on with wp.org.
Anyhow there are multiple things happening.

## Step-by-step reproduction instructions
1. Login to WP.org
2. Click to create a new post.
3. Add some paragraphs etc.
4. See the weirdness.

## Expected behaviour

That everything looked just as it should.

## Screenshots or screen recording (optional)

I am seeing this:
![Screen Shot 2021-05-21 at 13 37 10](https://user-images.githubusercontent.com/5323259/119131677-0df59580-ba3a-11eb-8b18-a0d365b88f66.png)

**Comment by talldan** [comment]
@paaljoachim I think this was fixed by https://github.com/WordPress/gutenberg/pull/31882. What version of the plugin is WP.org using? The screenshot says 10.3, the fix was apparently in 10.6.

**Comment by paaljoachim** [comment]
It has been fixed.
The screenshot says 10.3, as I took old information into the new Core Editor Summary.
