### ISSUE TITLE
Media - Cropping images cannot be saved in wp-admin/upload.php

### ISSUE THREAD

**Issue by kosiew** [WordPress/gutenberg#32084]
### Steps to reproduce the behavior

1.  Go to Media (wp-admin/upload.php)
2.  Click on Edit Image
3.  Crop
4.  Save

#### What I expected to happen

Cropped image saved

#### What actually happened

Save button is inactive [https://d.pr/i/AcbMx2](https://d.pr/i/AcbMx2), it activates if I do another editing e.g. rotate, but after saving cropping is not saved, rotation yes.

#### Browser / OS version

Chrome, maxOS Big Sur, Ver 11.2.3

#### Is this specific to the applied theme? Which one?

Tried on 3 themes - repeats

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

[https://d.pr/i/AcbMx2](https://d.pr/i/AcbMx2)

**Comment by talldan** [comment]
Thanks for reporting this @kosiew. I've seen this mentioned before, and I believe before clicking 'save' you have to click 'crop' a second time to complete the crop operation. It isn't intuitive, I do think it'd be clearer if there were an 'Apply' button.

BTW - the media library isn't part of the Gutenberg codebase, this issue would have to be reported in trac (the bug tracker for WordPress core). Here's a link - https://core.trac.wordpress.org/. I think it'd be worth searching for existing issues first as it may already be tracked.

I'll close this as there's nothing that can be done here.
