### ISSUE TITLE
Move `__experimentalFetchLinkSuggestions` to `core/data` store.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#32087]
Following the discussion in https://github.com/WordPress/gutenberg/issues/31416#issuecomment-836921932_ let's discuss the possibility of moving `__experimentalFetchLinkSuggestions` to the `core-data` package store.

**Update**: I gave this a go over here https://github.com/WordPress/gutenberg/pull/32096.

## Rationale

_All_ of the implementations currently in use today in the various `edit*` packages defer their`fetchLinkSuggestions ` functionality to the central `fetchLinkSuggestions` from `core-data`. 

#### Post Editor
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/editor/src/components/provider/use-block-editor-settings.js#L11-L15

#### Widgets Editor
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/edit-widgets/src/index.js#L14

#### Site Editor
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/edit-site/src/index.js#L9

#### Navigation Editor
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/edit-navigation/src/index.js#L9

As this function fetches data from _Core_ WP and is _WordPress specific_ I'd like to understand why `core-data` would _not_ be a good fit for this? 

Indeed the README says:

> Core Data is a [data module](/packages/data/README.md) intended to simplify access to and manipulation of core WordPress entities.

## Possible Problems

The only issue I see is how this function is currently wired up to the `<LinkControl>` component which resides in `@packages/block-editor`. 

To avoid coupling the block-editor to _WordPress specific_ functionality it currently uses `getSettings()` to retrieve the `__experimentalFetchLinkSuggestions` function. 

https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/block-editor/src/components/link-control/use-search-handler.js#L112-L118

Whilst this function is _not_ actually available in `core/block-editor` it _is_ made available in other packages (as shown above) by **overloading the editor settings**.

Typically what happens is something akin to the following:

```js
import { __experimentalFetchLinkSuggestions as fetchLinkSuggestions } from '@wordpress/core-data';

function initialize( id, settings ) {
	settings.__experimentalFetchLinkSuggestions = ( search, searchOptions ) =>
		fetchLinkSuggestions( search, searchOptions, settings );

	render(
		<Layout blockEditorSettings={ settings } />, // overload here
		document.getElementById( id )
	);
}
```
If we make `__experimentalFetchLinkSuggestions` a first class API in `core/data` then how can we still ensure `@wordpress/block-editor`'s `<LinkControl>` is not coupled to WordPress?

## Similar examples

In https://github.com/WordPress/gutenberg/pull/31464 I'm adding the ability to fetch rich meta data about an entry. I want to use this in `<LinkControl>` but I don't want to couple that component to a WordPress specific implementation. 

Again, we need a way to make calls to REST API endpoints but still allow them to be overloaded on a per editor basis.

cc @gwwar @adamziel @youknowriad @gziolo

**Comment by adamziel** [comment]
We're in a weird situation where we have a package with "generic" blocks but no go-to procedure to integrate them with WP. It seems like there we don't need any super-specific integrations at the moment and `searchEntities` (previously `__experimentalFetchLinkSuggestions`) nicely fits my mental model of core-data. 👍  from me.

**Comment by getdave** [comment]
Let's leave this for now. It's here if we ever need to circle back.

**Comment by kaizen-lazevedo** [comment]
Is there anyway of using the LinkControl outside the block editor due to the usage of __experimentalFetchLinkSuggestions  from the Settings ? I'd like to use the LinkControl on a custom admin page (wp_admin?page=my_custom_page) and used the following Javascript code:

```
wp.element.render(
    wp.element.createElement( wp.blockEditor.__experimentalLinkControl,{
        onChange:function(value){console. Debug(value);},
        showSuggestions:true,
        value:{url:'test'}
    } ),
    document.getElementById( 'my_linkcontrol' )
);
```
The LinkControl loads and shows, but when I write anything it doesn't provide suggestions and I can't change the function it uses to fetch them as it comes from the settings

**Comment by getdave** [comment]
Hi @kaizen-lazevedo. The `<LinkControl>` is a component of the block editor and thus is designed to be used within that context. This is why it is not part of the `@wordpress/components` package. As a result there is not currently a way I'm aware of to pass a suggestions handler function into the component.

You could look at [creating a registry for the UI you are creating which is what IsolatedBlockEditor does](https://github.com/Automattic/isolated-block-editor/blob/13ba50fca83cf548b0381e89acbfe48372019840/src/components/with-registry-provider/index.js).
