### ISSUE TITLE
Publish panel: Add a Create "New Page/Post" button at the end of Pre-Publish check panel.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32099]
## What problem does this address?

The last panel we see after having published a page is this:

![Screen Shot 2021-05-21 at 16 36 16](https://user-images.githubusercontent.com/5323259/119154738-bf082a00-ba52-11eb-81a0-5199f761cffa.png)

To create a New page one needs to exit the page and create a new page.

## What is your proposed solution?

I am suggesting to add a "New Page/Post" button to the Publish panel.

![Add-New-Page-button-to-Publish-Panel](https://user-images.githubusercontent.com/5323259/119156042-207cc880-ba54-11eb-817d-fb0fe7f4eaa3.jpg)

**Comment by manzwebdesigns** [comment]
My first thought is this is very nice!  As I think about it, I am wondering if the "Copy Link" and "New Page" buttons should be swapped.

**Comment by paaljoachim** [comment]
Hey Bud. Thank you for the feedback!

My thinking is that "View Page" and "Copy link" are actions related to the current page. The "New Page" is not related to the current but a new page.

So by importance I view it this way.
"View Page" = The first thing a person would want to do after having published a page.
"Copy Link"  = If they want to share the link with someone.
When a person is finished with viewing and sharing a link they might want to create a "New Page".

**Comment by manzwebdesigns** [comment]
That makes sense, I was looking at it from the perspective of common use.  I have never used the Copy Link, nor do I intend to. :)

**Comment by mschristo** [comment]
Hello! 

is this assigned to anyone else, or I can give it a try?

**Comment by paaljoachim** [comment]
Hi @mschristo Christos

Great!
I will go ahead and assign it to you.

**Comment by paaljoachim** [comment]
Kelly @kellychoffman 
has this mockup:
https://github.com/WordPress/gutenberg/issues/28010#issuecomment-778548343

<img width="318" alt="107839358-377a9300-6d60-11eb-9fed-489bbbe64537" src="https://user-images.githubusercontent.com/5323259/120368076-eb089280-c311-11eb-8d20-0293a17ea03f.png">

I went ahead and made the following based on Kelly's above suggestion:

![Pre-publish-panel-Add-New-Page-2](https://user-images.githubusercontent.com/5323259/120369163-2fe0f900-c313-11eb-8ff8-95b016698768.jpg)

**Comment by paaljoachim** [comment]
Hey @mschristo 

Let us know how we can help you move onward with a PR.
Thanks!

**Comment by thewebinarts** [comment]
Hello everyone,
Yeah, I think this will be great and quicker for the developers.

**Comment by thewebinarts** [comment]
Hello everyone,
Yeah, I think this will be great and quicker for the developers.

**Comment by thewebinarts** [comment]
Hello everyone,
Yeah, I think this will be great and quicker for the developers.

**Comment by thewebinarts** [comment]
Hello everyone,
Yeah, I think this will be great and quicker for the developers.

**Comment by thewebinarts** [comment]
Hello everyone,
Yeah, I think this will be great and quicker for the developers.

**Comment by getsource** [comment]
(I removed a few accidental duplicate comments per request of @thewebinarts)

**Comment by ddryo** [comment]
@paaljoachim 

I followed your implementation and implemented the screen.
Please give me a review.

https://github.com/WordPress/gutenberg/pull/32910

**Comment by thewebinarts** [comment]
Like this new button, more quick and easy for the UI experience.
