### ISSUE TITLE
Image block shows toolbar button to "Add text over image" even when `core/cover` block is nor registered

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#32094]
## Description

The Core Image Block recently added an option to "Add text over image" which under the hood transforms the Image block to a Cover Block. This button still gets rendered in the Blocks Toolbar in cases where the Cover Block is not registered. 

Instances where this can happen is when a site uses white / blacklisting.  

## Expected behaviour

When the Core Cover block is not registered the button should not show anymore.

## Actual behaviour

When the Core Cover block is not registered the button does snow but doesn't do anything.

## WordPress information
- WordPress version: "5.7.2"
- Gutenberg version: "Not installed"
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

**Comment by Mamaduka** [comment]
I pushed the PR to fix issue #32666.
