### ISSUE TITLE
Creating a Template Part and not assigning a name creates an error

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#32098]
When you create a template part via the ellipsis menu in the block toolbar, the following occurs:

https://user-images.githubusercontent.com/846565/119152708-764b7380-ba48-11eb-8ca6-86622b51afd4.mp4

**Comment by talldan** [comment]
I just tested this and noticed the error no longer happens. Instead an Untitled Template Part is created:
<img width="541" alt="Screenshot 2021-11-16 at 5 16 57 pm" src="https://user-images.githubusercontent.com/677833/141957218-9734421f-3ded-4c08-9af0-a880b97ebec4.png">

From working on the navigation block, the feedback there was that calling things 'untitled' isn't desirable. It might be that there's still some work to do here.

**Comment by jameskoster** [comment]
Yeah we should probably make the name a required field.

**Comment by talldan** [comment]
Fixed by #36592
