### ISSUE TITLE
Page Template: Cover full width shows gaps.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32100]
## Description

I made a Page Template. Removed the Site Title, Site Tagline and Separator (theme 2021).
Added a Cover block with an image. Then set it to Full Width.
There are gaps seen on the left, top and right area.

## Step-by-step reproduction instructions

1. Create a Page template.
2. Remove Site Title, Site Tagline and Separator blocks.
3. Add a Cover block with an image.
4. Set it to Full Width.
5. Notice the gaps (as well as the scrollbar).

## Expected behaviour

I expected to see no gaps (and no scrollbar).

## Actual behaviour

Gaps are seen in the left, top and right side of the Cover block.

## Screenshots or screen recording (optional)

![Screen Shot 2021-05-21 at 17 15 30](https://user-images.githubusercontent.com/5323259/119160115-37bdb500-ba58-11eb-8138-2116c274e1d7.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7 RC
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

## Device information
- Device: Desktop, Chrome
- Operating system: OSX 10.15.7

**Comment by carolinan** [comment]
Hi @paaljoachim 
I am not able to reproduce this issue. I tested with Twenty Twenty-One, but not with a page template because the theme does not have template editing enabled. It does not support template editing.

**Comment by paaljoachim** [comment]
Hey Carolina @carolinan 

Thank you for the feedback!

Testing with Twenty Twenty One. As you mentioned there is no template editing enabled. 
Testing with TT1. (I might have made an error in the original issue.)

Removed Site Title, Site Tagline (and Group block) and Separator blocks.
Added a Cover block with an image. Set it to Full width.
![TT1-Page-template-Cover-block-full-width](https://user-images.githubusercontent.com/5323259/180736116-18e4c109-6223-4a0b-b2c9-05abfd5a0a33.jpg)

I see two scrollbars to the right of the page template. One for the page template, and one just outside of it.
I would expect to see the image go full width not leaving any gaps on the left and right edges.

Frontend:

![Screenshot 2022-07-25 at 10 42 40](https://user-images.githubusercontent.com/5323259/180736220-92cf4fff-c6ba-4c10-bb75-b70bcfa285c5.jpg)

Also on the frontend there is a gap on the left and right edges.

**Comment by carolinan** [comment]
I still don't understand -these images are from the template editor, which is not supported by TT1. Are you using a third party plugin to enable it?

**Comment by paaljoachim** [comment]
I am using Gutenberg plugin + TT1 **Blocks**  (Forgot to mention the Blocks part...ops..)
I just updated the plugin and noticed that the full width issue has been fixed.
Double scrollbars. The first one is related to the template and the second to the sidebar settings. Seems that both should be as it is.

I appologize for the confusion Carolina.

Closing this issue.
