### ISSUE TITLE
Link Dialog's position appears randomly generated

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3211]
## Issue Overview

When activating the inline link dialog, it appears in an unexpected position.

## Steps to Reproduce (for bugs)

1. Enter a paragraph block
2. Click on the link icon in the docked toolbar

## Expected Behavior

Either the link popup would show near the content being linked, or the link popup would show in the same position with respect to the docked toolbar. I'm not sure ... @jasmussen @karmatosed ?

## Current Behavior

The popup appears mostly near the toolbar, with a horizontal position that seems related to the selection rectangle.

## Possible Solution

There may have been some additional CSS that `getFocusPosition` now needs to consider when calculating a position.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jasmussen** [comment]
Yeah this is definitely a regression. I suspect it may be related to the docked toolbar thing we merged. @youknowriad any idea what this might be?

**Comment by youknowriad** [comment]
@jasmussen yes, the link relative position is not computed relatively to the right parent now. It should be fixed by #3224
