### ISSUE TITLE
Z-index error with Autosave and Classic block toolbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32115]
## Description

I happen to notice when there is an Autosave notification in the top and a Classic Toolbar is active, that the Classic Toolbar will go on top of the notification.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Create/use existing page/post add a Classic block.
2. I assume leave the post and return to see the Autosave notification show up.
3. Scroll the page and see if the Classic toolbar is on top of the Autosave notification.

## Expected behaviour

Classic Toolbar should scroll underneath the top notification.

## Actual behaviour

Toolbar is seen on top.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5323259/119198538-c8f94f80-ba89-11eb-9e1e-4ffdb53e2e85.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

## Device information
- Device: Desktop
- Operating system: OSX 10.15.7
- Browser: Chrome

**Comment by stokesman** [comment]
Seems a duplicate of #32000

**Comment by paaljoachim** [comment]
Great! I will go ahead and close this issue.
