### ISSUE TITLE
DropdownMenu popover doesn't close when it loses focus in a Modal

### ISSUE THREAD

**Issue by lukecarbis** [WordPress/gutenberg#32128]
## Description
When adding a DropdownMenu to a Modal, the menu doesn't close when it loses focus. When the DropdownMenu is added elsewhere, it does close when it loses focus.

## Step-by-step reproduction instructions
```
<Modal>
	<DropdownMenu
		icon="ellipsis"
		label={ __( 'Actions' ) }
		controls={ [
			{
				title: __( 'Foo' ),
				label: __( 'Foo' ),
				icon: 'table-col-delete',
			},
		] }
	/>
</Modal>
```
Here is a Sandbox demonstrating the issue:
https://codesandbox.io/s/wp-components-dropdown-modal-test-forked-pv9gv?file=/src/App.js

## Expected behaviour
When a dropdown menu loses focus, it should close.

## Actual behaviour
The dropdown menu doesn't close when it loses focus.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: MacBook
- Operating system: MacOS
- Browser: Safari 14.1

**Comment by stokesman** [comment]
The logic added to prevent a dropdown from closing when it opens a modal https://github.com/WordPress/gutenberg/pull/16964#discussion_r312015746 is the culprit.
https://github.com/WordPress/gutenberg/blob/83e74256edc2440d9650c65d68e17ddd6df93ffd/packages/components/src/dropdown/index.js#L69-L71
Its intent is to enable return of focus to the dropdown after the modal is closed. We’ll have to smarten that logic up. Maybe just checking that the dialog also doesn't contain the dropdown.
