### ISSUE TITLE
Post author field: when search is enabled, it shows some wrong results

### ISSUE THREAD

**Issue by luis-movel** [WordPress/gutenberg#32127]
## Description
Issue 1: Author search field don't show the right results (properly retrieved by the API) on the top of the list.
Issue 2: When you scroll down to the end of this list, you can see the results, but you can't select them.

It may have some relation with this pull request: #5921

## Step-by-step reproduction instructions
1. Create more than 1000 different users, to make sure the post author field becomes a text field (not select).
2. Choose a post to edit and try to change the author of this post, by typing a name.
3. Check that the first given names are not the names you're looking for (issue 1).
4. Scroll down the list until you see the right names and try to select them (issue 2).

## Expected behaviour
By typing the name of the user you're looking for, the first results would be the users retrieved by the API and you can select them.

## Actual behaviour
By typing the name of the user you're looking for, the first results are not the users retrieved by the API. If you scroll down to the bottom of the list, you can find the results of the search, but, you can't select them - it kind of "jump" to the begining of the list when you hover them (as shown in the screen recording below). 

It only happens when the author field is a text field, not select (as far as I realized, this field is shown when there's more than 1000 users in the list).

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/26234832/119241040-2c3abe80-bb2a-11eb-9a79-8d320e923a7e.png)

![Editar post ‹ Blog — WordPress - Mozilla Firefox 2021-05-22 17-11-49](https://user-images.githubusercontent.com/26234832/119240848-e9c4b200-bb28-11eb-9a38-06a8e6b317db.gif)

## WordPress information
WordPress version: 5.7.2 (also happening with previous versions)
Gutenberg version: N/A
Are all plugins except Gutenberg deactivated? Yes - I made some tests with all plugins deactivated - it still happens.
Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
Device: Desktop
Operating system: Windows 10 
Browser: Tested on Chrome and Firefox.

**Comment by Mamaduka** [comment]
Hi, @luis-movel

I wasn't able to reproduce the issue, but I've my guess why this might happen.

Just to confirm: Do you see any errors in DevTool's console? You might want to enable [`SCRIPT_DEBUG`](https://wordpress.org/support/article/debugging-in-wordpress/#script_debug) for React to display errors.

**Comment by luis-movel** [comment]
Hi, @Mamaduka! Thank you for the reply.

I've just enabled SCRIPT DEBUG and it displays errors like this when I click at the post author field:

![image](https://user-images.githubusercontent.com/26234832/119540583-f6811a00-bd63-11eb-9518-cc7129e3776e.png)

It repeats for some different users.

Might it be related to the issue?

Thanks!

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @luis-movel.

**Comment by luis-movel** [comment]
No problem, @Mamaduka !

If you need some more tests, just let me know.

Thank you!

**Comment by Mamaduka** [comment]
@luis-movel I just merged the fix for this issue, and it should be part of 10.8 release.

Feel free to reopen the issue if you still experience the problem.
