### ISSUE TITLE
Issue with pasting multiple headers and paragraphs

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#3212]
## Issue Overview
When pasting some headers and paragraphs from another (published) post, they're not correctly converted into blocks. 

Then, on reload, those blocks are corrupted.

Videos: 
- https://wordpress.slack.com/files/U02QJMG7R/F7R5RQREF/gutenberg-ate-my-post-yo.mp4
- https://wordpress.slack.com/files/U02QJMG7R/F7RCBUDFX/oh-hey-revisions-are-helpful.mp4

## Steps to Reproduce (for bugs)
1. Copy some headers and paragraphs from another published post (from the front-end)
2. Paste into Gutenberg
3. Gutenberg is sad :(

## Expected Behavior
I expected Gutenberg to correctly parse my content and create new header and paragraph blocks for me.

See conversation on Slack for more details: https://wordpress.slack.com/archives/C02QB2JS7/p1509134027000284

cc @iseulde

**Comment by iseulde** [comment]
Interesting. What browsers is this? Do you either have the source text, or the logged console texts, so I can try to reproduce the issue? For the latter, open the developer tools, and it should log stuff like "Received HTML:" etc.

**Comment by melchoyce** [comment]
> What browsers is this?
Latest Chrome. 

> Do you either have the source text
Yup, the published post is here: https://a8cdesignflow.wordpress.com/2017/10/26/whats-coming-in-wordpress-4-9/

> or the logged console texts
Nope, have moved on. You can maybe see it in the revision video, though? Unsure if that's the same.

**Comment by iseulde** [comment]
I have copy pasted your entire blog post into Gutenberg in Chrome, and everything works fine. There's a small issue I see with an emoji image that then becomes a freeform block, but that's it.

**Comment by mtias** [comment]
Closing this. Feel free to reopen if still running into issues.
