### ISSUE TITLE
Some block patterns do not show in the inserter

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#32139]
## Description

When testing the block patterns that are [planned for Twenty Fourteen](https://core.trac.wordpress.org/ticket/51103),
I learnt that the patterns show correctly in 10.6.2 but not in 10.7 RC1.
With 10.7 RC1, only two of the patterns show (summary and contact).

I was able to reproduce this in my own themes. It seems to be related to spacing inside the `content`.

The following does not work, the pattern is not selectable:
```
register_block_pattern(
		'twentyfourteen/list',
		array(
			'title'         => esc_html__( 'List', 'twentyfourteen' ),
			'categories'    => array( 'twentyfourteen' ),
			'viewportWidth' => 1000,
			'content'       => '<!-- wp:columns -->
								<div class="wp-block-columns"><!-- wp:column {"width":"40%"} -->
								<div class="wp-block-column" style="flex-basis:40%">
								... truncated
```

The following does work:
```
register_block_pattern(
		'twentyfourteen/list',
		array(
			'title'         => esc_html__( 'List', 'twentyfourteen' ),
			'categories'    => array( 'twentyfourteen' ),
			'viewportWidth' => 1000,
			'content'       => '<!-- wp:columns --><div class="wp-block-columns"><!-- wp:column {"width":"40%"} --><div class="wp-block-column" style="flex-basis:40%"><!-- wp:heading {"style":{"typography":{"fontSize":45}}} --><h2 style="font-size:45px">' . esc_html__( '2001', 'twentyfourteen' ) . '</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph --><p><em>' . esc_html__( 'My first year of traveling. I visited China, Thailand, Japan, and India.', 'twentyfourteen' ) . '</em></p><!-- /wp:paragraph --></div><!-- /wp:column --></div>
... truncated

```

## Step-by-step reproduction instructions

1. Download the patch for the patterns in Twenty Fourteen, or copy the pattern code into your current theme.
2. In the editor, open the inserter, select patterns, select the Twenty Fourteen category, and see that only two patterns show.

## Expected behaviour

All registered patterns should show

## Actual behaviour

Only two of the patterns show.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.0 RC1
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Fourteen with above pull request. Armando.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 90.0.4430.212

**Comment by justintadlock** [comment]
Thank you for at least figuring out what wasn't working with this.  I've been digging everywhere and testing (almost) everything to figure out why none of my 30+ patterns were working.

**Comment by justintadlock** [comment]
I ran all my patterns through this for a quick fix:

```
'content' => str_replace( [ "\n", "\r", "\t" ], '', $pattern_content )
```

**Comment by kopepasah** [comment]
@youknowriad I am not certain this issue is resolved, as when trying to register the following pattern on WP 5.9.1, it does not register:

```php
register_block_pattern(
	'wp-core-test/test-pattern-with-columns',
	[
		'title'   => 'Test Pattern',
		'content' => '<!-- wp:group --><div class="wp-block-group"><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->',
	]
);
```

However, the following pattern **does** register:

```php
register_block_pattern(
	'wp-core-test/test-pattern-with-columns',
	[
		'title'   => 'Test Pattern',
		'content' => '<!-- wp:group --><div class="wp-block-group"><!-- wp:columns --><div class="wp-block-columns"></div><!-- /wp:columns --></div><!-- /wp:group -->',
	]
);
```

I discovered this issue when trying to make a two column pattern (with headings, paragraphs, images, etc), and only when we remove the columns does the pattern register.

**Comment by kopepasah** [comment]
Never mind, the issue was that the `core/column` block was on our allowed list. However, I will note that we are still able to use the `core/column` block when it is not allowed and the `core/columns` block is allowed. This seems like expected behavior, as we wouldn't want to allow columns without a column. Probably worth investigating, as while we can use it in the editor, we cannot use it in patterns.
