### ISSUE TITLE
When input[type="email"] or [type="time"] or [type="number"] /  is used in a custom block, the input text cannot be copied.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#32148]
## Description
When input[type="email"] or [type="time"] or [type="number"] / is used in a custom block, the input text cannot be copied.

This problem also occurs with jetpack's Repeat Visitor block, Business hour block, etc.

[type="url"] can be copied successfully.

I think it happens when using attributes that do not support `selectionStart` / `selectionEnd`.

## Step-by-step reproduction instructions

1. Create Custom block like https://developer.wordpress.org/block-editor/how-to-guides/metabox/meta-block-3-add/
2. Use `<TextControl type="email" />`, `<TextControl type="time" />`, `<TextControl type="number" />`..etc.
3. Select input text and Copy.

## Expected behaviour
`Copied "Custom Fields" to clipboard."` is not displayed, and Save selected text to clipboard.

## Actual behaviour
`Copied "Custom Fields" to clipboard."` is displayed. and the block is copied, not the text.
## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1908815/119336362-8d989400-bcc8-11eb-9916-5c7279d36863.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed / 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OS X 11.3.1
- Browser: Chrome 90

**Comment by torounit** [comment]
`inputFieldHasUncollapsedSelection` returns true for [type="text"] and false for [type="email"]. 

The function returns true for [type="text"] and false for [type="email"]. If the function returns true, the value can be copied successfully.

**Comment by lgladdy** [comment]
This issue also affects Advanced Custom Fields blocks.

**Comment by ktmn** [comment]
Additionally, elements with `[contenteditable="true"]` pass the `isTextField()` check, but `selectionStart` and `selectionEnd` seem to be always `undefined`, thus the `inputFieldHasUncollapsedSelection()` always returns `false` (making it impossible to cut text from CodeMirror editor in a block for example).

https://github.com/WordPress/gutenberg/blob/4bd51e16e00cf5bbc8ae81ed8712c6bde8a83a66/packages/dom/src/dom/input-field-has-uncollapsed-selection.js#L25-L30

Perhaps author of #22793 @mcsf might know how to proceed?

**Comment by mcsf** [comment]
> Additionally, elements with `[contenteditable="true"]` pass the `isTextField()` check, but `selectionStart` and `selectionEnd` seem to be always `undefined`, thus the `inputFieldHasUncollapsedSelection()` always returns `false` (making it impossible to cut text from CodeMirror editor in a block for example).

@ktmn: Interesting. This got me to learn more deeply about what the HTML spec prescribes for different types of inputs. I have a possible fix at #40192.

(edit: fixed PR number)
