### ISSUE TITLE
WordPress 'all_admin_notices' action is outside of "editor-layout" container

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#3214]
The WordPress 'all_admin_notices' action is fired BEFORE the the "editor-layout" div container, so notices cannot shrink/expand as the "is-sidebar-opened" class is added/removed to the "editor-layout" container (when the settings sidebar is shown/hidden).

**Comment by mtias** [comment]
Consolidating in #3214.

**Comment by BE-Webdesign** [comment]
See: #3395
