### ISSUE TITLE
File Block:Adding a custom style to a file block will register two upload files.

### ISSUE THREAD

**Issue by imawc** [WordPress/gutenberg#32157]
## Description

If you add a custom style to the file block with register_block_style(), two upload files will be registered.

## Step-by-step reproduction instructions

1. Register a custom style in the file block with register_block_style()
2. Upload a file in the file block
3. Checking in the media, two files are registered.

## Expected behaviour

Register only uploaded files.

## Actual behaviour

Duplicated files will be registered at the same time.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Mac OS X 11.3.1
- Browser: Chrome 90.0.4430.212

**Comment by Mamaduka** [comment]
I was able to reproduce the issue.

Example code for custom File block style:
```php
add_action( 'init', function() {
    register_block_style(
        'core/file',
        [
            'name'  => 'file-test-style',
            'label' => 'File test style'
        ]
    );
} );
```

**Comment by imawc** [comment]
@Mamaduka 
Ah, so it was a bug after all.
Thanks for reproducing the test.
