### ISSUE TITLE
Invalid CSS in the block editor styles for .block-editor-block-variation-transforms

### ISSUE THREAD

**Issue by pavel-mailpoet** [WordPress/gutenberg#32181]
## Description
The styles for the rule `.block-editor-block-variation-transforms .components-dropdown-menu__toggle:focus:not(:disabled)` are not valid css.
And when I try to include the CSS in our plugin, our compilation fails because the stylesheet is not valid. See the error. 

![Screen Shot on 2021-05-25 at 09-12-20](https://user-images.githubusercontent.com/29194603/119455108-907f9d00-bd39-11eb-8657-3d7d7efe6e29.png)

I think it is because there are vanilla CSS variables and SASS variables combined in the [source code](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-variation-transforms/style.scss#L23) and I don't think SASS supports that.

**Comment by talldan** [comment]
cc @ntsekouras.

**Comment by ntsekouras** [comment]
👋 - I guess this is probably related to this: https://sass-lang.com/documentation/breaking-changes/css-vars and this:
https://github.com/WordPress/gutenberg/pull/27968.

@jasmussen can you take a look here as you have more experience on these 😄 ?

**Comment by jasmussen** [comment]
Created https://github.com/WordPress/gutenberg/pull/32305 in hopes to address this.
