### ISSUE TITLE
Gutenberg 10.62 background bug 

### ISSUE THREAD

**Issue by jackiepro** [WordPress/gutenberg#32185]
![20210525175551](https://user-images.githubusercontent.com/77946791/119478687-9483dd00-bd82-11eb-972b-ed6fdbd72ac2.jpg)
![20210525175617](https://user-images.githubusercontent.com/77946791/119478690-95b50a00-bd82-11eb-8874-ea93154b8857.png)

After upgrading to the latest version, Mobile and tablet modes will have a gray overlay background.

**Comment by skorasaurus** [comment]
Hi, 
Could you share some more information to help us identify the bug?

what theme you're using
What browser
anything that appears in the console (accessible by pressing the following on your keyboard simultaneously: `control + shift + i` (click on the console button, after pressing those three keys)

**Comment by jackiepro** [comment]
After the upgrade, it has been resolved, thank you
