### ISSUE TITLE
Widget information does not add correct apostrophe in sites (encoding issue) - new Gutenberg widgets editor

### ISSUE THREAD

**Issue by mrsjaved** [WordPress/gutenberg#32192]
## Description
In the widget's block settings, the widget info does not encode properly. It says "site&#8217;s" instead of 
"site's"

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to Appearance -> Widgets (make sure the new widget editor is enabled)
2. Add any widget. In this example, I tested with the recent posts widget and archive widget.
3. Click on the widget -> Block and you will see this text there.

## Screenshots or screen recording (optional)
https://d.pr/i/KnDKgu/colWLADBsg

## Device information
- Device: MacBook Pro
- Operating system: Big Sur
- Browser: Chrome
- Tested on: Simple site

**Comment by talldan** [comment]
Thanks for reporting the problem. This was already reported in https://github.com/WordPress/gutenberg/issues/31023, so I'll close this as a duplicate.
