### ISSUE TITLE
Move to widget icon appears twice - New Gutenberg Widgets Editor

### ISSUE THREAD

**Issue by mrsjaved** [WordPress/gutenberg#32191]
## Description
While testing the widgets we noticed the move to widget icon in the quick toolbar appears twice. 

## Step-by-step reproduction instructions

1. Go to Appearance -> Widgets (make sure the new widget editor is enabled)
2. Add any widget
3. Click on the widget and you will see two icons in the quick toolbar.

## Expected behavior
There should be one icon or it should be clearly labeled if there should be two. 

## Actual behavior
There are two similar icons as seen in the screenshot below. 

## Screenshots or screen recording (optional)
https://d.pr/i/2jM4oc/oEAa5UuWiI

## Device information
- Device: MacBook Pro
- Operating system: Big Sur
- Browser: Chrome
- Tested on: Simple site

**Comment by talldan** [comment]
I also don't see this issue when testing. Could you let us know which WordPress version and/or Gutenberg version you're testing with. Also which theme you're using?

**Comment by talldan** [comment]
Closing as this seems to be a WordPress.com issue.
