### ISSUE TITLE
Alignment options for calendar widgets throwing error - Gutenberg widgets editor

### ISSUE THREAD

**Issue by mrsjaved** [WordPress/gutenberg#32193]
## Description
When I click on the alignment option for the calendar widget it does change the alignment but throws the following error in the content. 

"Error loading block: Invalid parameter(s): attributes"
## Step-by-step reproduction instructions

1. Go to Go to Appearance -> Widgets (make sure the new widget editor is enabled)
2. Add calendar widget
3. Click on the alignment option from the quick toolbar.
4. There you will see the error.

## Expected behavior
It should change the alignment without error. 

## Actual behavior
Throwing error message. 

## Screenshots or screen recording (optional)
https://d.pr/i/qpUFP6/GYbvEOZGQI

Device: MacBook Pro
Operating system: Big Sur
Browser: Chrome
Tested on: Simple site

**Comment by talldan** [comment]
I couldn't reproduce the issue. @mrsjaved is there a specific WordPress and/or Gutenberg version you're testing with?

I notice your screenshot is also showing the Move to Widget Area toolbar button twice, which seems very wrong.

edit: I see now that there's another bug report related to that last point - https://github.com/WordPress/gutenberg/issues/32191.

**Comment by talldan** [comment]
I realise now these are WordPress.com related, so this should be raised somewhere in an Automattic project (not sure which one).
