### ISSUE TITLE
Make SEO Meta Data Easy

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#32208]
## What problem does this address?

Having SEO meta data is an important part of SEO. I am frustrated because in order to just add simple meta data to a page or post, a plugin must be downloaded or code must be inserted. Usually the plugin adds extra features that create additional notifications and bloat on the website.

Google sees proper SEO titles and descriptions as important that is why pages without these features show up with errors in Google Lighthouse.

## What is your proposed solution?

My solution is to have the Gutenberg editor use the post excerpt for the meta description, the post tile for the meta title, and the post's tags for the meta tags.  That way users can have basic SEO features when they use the Gutenberg editor instead of installing an additional plugin. 

My solution makes it easier for new users who might not understand much about SEO to have an optimized website to compete in search engines better. Many WordPress users don't have the time or the budget to learn how to use SEO so making the editor SEO-friendly from the beginning is a start.

This also removes the SEO error a page will get in Google Lighthouse for not having a proper SEO title and description.

**Comment by talldan** [comment]
@deborah86 I think you should make this a trac ticket, as it goes beyond the scope of the block editor, and relates more to how WordPress itself exposes metadata (even if your solution involves the block editor).

Here's where you can create a ticket - https://core.trac.wordpress.org/.

Though I'd recommend searching for existing tickets on the subject first.
