### ISSUE TITLE
Editable: highlight non-breaking spaces.

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#3220]
I personally think this could be both a typographically interesting tool to add, and help solve quite a bit of frustration and complaints around this "magic" and sometimes annoying character.

1. Different (browser) editors may add this character to text for a variety of reasons while writing, copying, or pasting. When the text ends up in WordPress, the user has no idea about these, save from maybe text wrapping if it's at the end of the line. This is most often typographically wrong, and the text will wrap awkwardly with different content widths. A lot of users find this frustrating to manually remove these invisible characters all the time, or they just have no idea how to fix the line break issue.
2. Often when you're inserting a non-breaking space intentionally (e.g. section symbol, certain surnames hu-hum), it is very hard to keep track of in the visual editor, especially when moving things around.

This should be fairly easy to add with the TinyMCE plugin, or something similar: https://www.tinymce.com/docs/plugins/visualchars/.

**Comment by jeffpaul** [comment]
@iseulde per [last week's bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1519924621000008), can you clarify if this is still an open issue?

**Comment by iseulde** [comment]
Yes it’s open and I think valuable but wouldn’t consider it urgent.

**Comment by mtias** [comment]
I'm going to close this for now as I don't see us adding it in core any time soon. We can reopen if we either get ideas or it becomes more important.

**Comment by holzee** [comment]
I think it is important for professional editing like journalism. Currently Gutenberg has no way to show non-breaking spaces, except switching to html. It is really missing to some languages, where \&nbsp; are used more often than in English.
