### ISSUE TITLE
Specify which blocks to populate a new template with

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#32211]
This issue relates to the recently introduced template creation / editing feature.

When I go to create a new template, the template appears to auto-populates with the following blocks: 

- Site title
- Site tagline
- Separator
- Post Title
- Post Content

Example screenshot with emptytheme: 

<img width="1904" alt="Screen Shot 2021-05-25 at 12 06 37 PM" src="https://user-images.githubusercontent.com/5375500/119531488-d2f4aa00-bd38-11eb-84a5-2080d1a86c5d.png">

Are the default blocks to populate a new template being considered? What default makes sense? 

Some thoughts / options from a theme developer perspective:

a) `singular` falling back to `index`
b) entirely blank
c) give the theme a way to specify

**Comment by justintadlock** [comment]
There should probably be a hierarchy:

1. Let themes define a blank/starter template.
2. If no theme-defined template, fall back to single/page/singular template.
3. If no single* templates, fall back to index template.

**Comment by jffng** [comment]
That hierarchy makes sense to me.

The UI could also be refined to make it clear what the source template is, or allow the user to select / change it.

**Comment by bobbingwide** [comment]
In my response to an FSE outreach call #6 I wrote

> I think I’ve made this comment before. When I first created a new custom template I was surprised by its content. I’d become used to the Site editor copying the index template. While performing this test I thought, “Why can’t I pick the template upon which my new template should be modelled?” It makes sense to be able to use a template as a template. This would be a nice feature.

https://sneak-peek.me/2021/05/23/call-6-template-editing-and-navigation-block/#more-429

The Create new template dialog would be:

```
Create new template
Name: text field 
Based on: select from a drop down list of existing templates
Create button  Cancel button
```

An additional benefit of cloning an existing template is that the attributes of the template-parts used in the template would be copied. I noted, during call #7, that I needed to (re)define the attributes for each existing template part when I was building the new template.

**Comment by justintadlock** [comment]
Cloning an existing block template is a good idea.  With block themes, users can select and edit an existing template, but there's no way to give it a new slug (AFAIK).

For 5.8 and non-block themes, I don't think there'd be a good way to do that since they are built on PHP.  But, for block templates, I'd love to see that as an option.

**Comment by fklein-lu** [comment]
> For 5.8 and non-block themes, I don't think there'd be a good way to do that since they are built on PHP.

PHP themes should be able to provide a template without needing to add a block-based template.

It will be impossible to transition most PHP themes to being block-based while keeping the same design and functionality. So you can't expact authors to add `single.html` or `page.html` templates as they would be used for content rendering.

But authors still would want to offer something better than the current default template, which looks very poor. Even if authors can't offer a template that looks exactly like the PHP templates, they can at least offer something a bit more styled.

I'm very surprised that the default template [is hardcoded](https://github.com/WordPress/gutenberg/blob/863a69bedc22c69cf44326e2504756236faa49f3/packages/edit-post/src/components/sidebar/template/actions.js#L82) without even the slightest possibility to change this through any mean whatsoever.

**Comment by aristath** [comment]
Linked this issue to https://github.com/WordPress/gutenberg/pull/32771 which adds a way to define the default templates. When that PR gets merged this one can be closed :+1:
