### ISSUE TITLE
Customizer Widgets screen: tweaks to Welcome Guide

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32223]
Hi all, just recapturing a couple of notes left on merged PR #31968 

--

It looks like the GIF is squeezed horizontally in the default layout (when you resize to a narrow viewport window, the ratio of the image there is correct):

![118825164-73a22000-b888-11eb-8fed-494f245ec77e](https://user-images.githubusercontent.com/77359364/119560579-1a4b5c80-bd72-11eb-9b55-22398a6faa88.jpeg)

~On the narrow viewport window, I like how the image expands larger to display at 100% scale. Could we make the area around the GIF expand edge-to-edge to match the button width?~ Merged in https://github.com/WordPress/gutenberg/pull/32264

**Comment by critterverse** [comment]
The second part of this was resolved by https://github.com/WordPress/gutenberg/pull/32264

But I'm still seeing the horizontally squished image at a regular viewport size — edited the description to just focus on that part!

**Comment by kevin940726** [comment]
@critterverse Oh I missed that! I'll create a patch.
