### ISSUE TITLE
Customizer Widgets: move ellipses menu to Customizer top bar

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32224]
Hi all, just recapturing a notes left on merged PR #31970

The ellipses menu for the Customizer Widgets editor should appear in the top Customizer bar next to the Publish button. It's getting a little lost where it is currently in the editor top bar.

![ellipses-menu](https://user-images.githubusercontent.com/77359364/119561390-1966fa80-bd73-11eb-9e92-2e5efa342c0b.jpg)

**Comment by kevin940726** [comment]
Hmmm, I'm not sure if that's the right place to put the ellipses menu though. The menu is only present if the current active section is a widgets section. What would happen if we close the section? Where should we move the focus if it's already on the menu but we close the section? I'm sure there's an accessibility best practice for it, but I also think that the UX would seem a little weird. WDYT?

**Comment by critterverse** [comment]
You’re right @kevin940726, this might be more complex than I was originally thinking. Also #32061 will help a lot by giving the editor top bar more prominence so I'll go ahead and close this one. Thanks for looking into it!
