### ISSUE TITLE
Nav Screen: No way to create a menu when a user has no menus

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#32256]
## Description
At the moment the navigation screen seems to shown an incorrect state when a user has no menus, and the user has no way to create a first menu.

<img width="804" alt="Screenshot 2021-05-27 at 10 30 19 am" src="https://user-images.githubusercontent.com/677833/119757437-87c4cd80-bed7-11eb-86e3-a1db5eb46713.png">

The culprit seems to be a failed REST request for fetching menus. Possibly this hasn't been caught by end to end tests because those use endpoint mocking. I'm not sure why this is suddenly an issue, perhaps a change in the REST endpoints?

Here's the failed request:
<img width="763" alt="Screenshot 2021-05-27 at 10 34 01 am" src="https://user-images.githubusercontent.com/677833/119757701-e9853780-bed7-11eb-91b3-ff7ef162e109.png">
<img width="556" alt="Screenshot 2021-05-27 at 10 42 12 am" src="https://user-images.githubusercontent.com/677833/119757913-3e28b280-bed8-11eb-8852-8a69bce6fbc3.png">

## Step-by-step reproduction instructions
1. Delete all menus, or start with a completely fresh WordPress installation
2. Enable the navigation screen experiment.
3. Browse to the navigation screen.

## Expected behaviour
The UI for creating a first menu is displayed.

And also, if a REST Request is failed, it's handled and an error state is shown.

## Actual behaviour
The screen shows some of the UI from when a menu exists.

**Comment by talldan** [comment]
Actually, I think there are some other issues beyond when the user has no menus. After creating a menu in the old screen it's showing up as empty an un-named:
<img width="906" alt="Screenshot 2021-05-27 at 10 52 45 am" src="https://user-images.githubusercontent.com/677833/119758883-dd01de80-bed9-11eb-81df-504ed42c4003.png">

But it definitely has one link and is titled 'Main Menu':
<img width="896" alt="Screenshot 2021-05-27 at 10 54 49 am" src="https://user-images.githubusercontent.com/677833/119759002-0884c900-beda-11eb-8d5f-e88d896d043c.png">

**Comment by getdave** [comment]
@Mamaduka Anything to do with our recent refactoring in and around this area?

**Comment by Mamaduka** [comment]
@getdave Can be related, but I think I fixed all regressions I could find.

@talldan I'm not able to fully reproduce the issue with the current `trunk`. I can see 404 in the console, but the correct state when there are no menus.

**Comment by getdave** [comment]
I re-tested this and I can see the request going out to

`http://localhost:8888/wp-json/__experimental/menus/`

That returns the expected empty array `[]`.

However the app still thinks we have a selected menu ID so it then tries to make a request for _that_ selected menu ID which doesn't exist so we get the error Dan was seeing. 

Working on a fix.

**Comment by Mamaduka** [comment]
I was finally able to reproduce the broken screen.

I had to delete menus from the non-experimental Menus screen. There are multiple ways to delete menus, so the guard clause is proposed in #32306 makes sense.
