### ISSUE TITLE
gutenberg update 10.7.1

### ISSUE THREAD

**Issue by Moebiusweb** [WordPress/gutenberg#32253]
gutenberg update 10.7.1 disables customization in the astra theme.

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by talldan** [comment]
@Moebiusweb Please could you file a new issue and this time fill out the bug report template.
