### ISSUE TITLE
Multi-selection with the mouse breaks after blocks have been moved

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3226]
## Issue Overview

There's an issue with multi selection after blocks have been rearranged.

## Steps to Reproduce (for bugs)

- Have a number of blocks, like paragraphs, verify that multi selection with the mouse works fine
- Move a block using the arrow mover on the side
- Try to multi select again

## Expected Behavior

Multi selection works as intended.

## Current Behavior

Multi select seems to assume blocks are still in their previous position, which causes some unpredictable selection behavior.

GIF:

![multiselect](https://user-images.githubusercontent.com/1204802/32160039-46e64b9a-bd50-11e7-83af-fc663b07139b.gif)

**Comment by jasmussen** [comment]
CC: @iseulde any idea what this might be?

**Comment by iseulde** [comment]
Hm, I'm having a hard time reproducing. Which browser is this? From the GIF, I'm not so sure what is happening. :)

**Comment by jasmussen** [comment]
This is Chrome. Here's a video instead: https://cloudup.com/cSDDUvlAXHn
