### ISSUE TITLE
Update widgets page URL in plugin when in WordPress 5.8 or greater

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#32267]
## Description
I noticed when using the Gutenberg plugin with WordPress 5.8, the widget page still loads on the URL `wp-admin/themes.php?page=gutenberg-widgets`. It's possible to still access the core widget page at wp-admin/widgets.php.

Instead the plugin should override core block-based widget page so that there's no confusion, the same way the post editor in Gutenberg uses the same URL at the post editor in core.

On WP versions prior to 5.8, the `wp-admin/themes.php?page=gutenberg-widgets` URL is still fine as widgets.php still displays the old widgets screen.

See the comments in slack from @noisysocks for further info:
https://wordpress.slack.com/archives/C01D71823PB/p1622090672068700

## Step-by-step reproduction instructions
1. Use WordPress 5.8 and the Gutenberg plugin
2. Navigate to the widgets screen
3. Notice the URL

## Expected behaviour
The URL should be widgets.php

## Actual behaviour
The URL is not widgets.php

**Comment by tellthemachines** [comment]
Closing as this has been fixed in #32299
