### ISSUE TITLE
Editor widths in themes aren't respected in Gutenberg 10.7.x

### ISSUE THREAD

**Issue by steveangstrom** [WordPress/gutenberg#32274]
## Post editor widths set by themes are not respected in the editor in Gutenberg 10.7.x
Gutenberg editor widths can be set by themes, or by devs. Prior to Gutenberg 10.7.x  this worked fine.  Versions 10.7.x upwards display incorrect widths for themes in the Post editor.

- Tested Gutenberg 10.7.1 + 2021 Theme = bad widths
- Tested Gutenberg 10.7.1 + Astra Theme = bad widths
- Tested Gutenberg 10.7.1 + Hello Theme = bad widths. 

- Tested Gutenberg 10.6.2 + 2021 Theme = Good widths
- Tested Gutenberg 10.6.2 + Astra Theme = Good widths. 
- Tested Gutenberg 10.6.2 + Hello Theme = Good widths. 

## Step-by-step reproduction instructions

1. Install latest WP (5.7 at time of writing) and use bundled Gutenberg for now
2. Install 2021 theme
3. Create a Page titled "test width" with a cover block set to FULL WIDTH, add more content such as title, paragraph text. Publish the page, but stay on the editor
4. In a new tab : install Gutenberg 10.7.x and activate
5. Back on the editor tab for Page:"test width" refresh the page, and look at the editor. The width of the editor contents is incorrect. The cover block is now too narrow (incorrect). 
6. try different popular boilerplate themes (Astra, Hello ), try different versions of Gutenberg 
7. Depending on theme different width problems are displayed when using G 10.7.x which are not present in earlier versions 

## Expected behaviour
The editor width should _not_ be narrower in Gutenberg 10.7.x ,  
The editor widths as shown in WP5.7 bundled Gutenberg and also using plugin Gutenberg 10.6.2 are the _correct_ editor widths.

## Actual behaviour
The editor is artificially narrowed in Gutenberg 10.7.x , even narrower in some cases than others. EG: Astra widths seem to be around 600 pixels wide.   Where 2021 narrows  

## Screenshots or screen recording (optional)
Using theme 2021 the issue is noticeable where the "full width" is used on the cover block
![bug-gutenberg-widths](https://user-images.githubusercontent.com/8482649/119828673-51487c00-bef2-11eb-8c31-7d702fdf1ea4.jpg)

On other themes the problem becomes more noticeable as the canvas color is not masking the issue so much
![astra-gutenberg-clash](https://user-images.githubusercontent.com/8482649/119828720-5dccd480-bef2-11eb-8940-32afd4f1de86.jpg)

## WordPress information
- WordPress version:  5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme : Yes.

## Device information
- Device: Desktop
- Operating system: Windows 7
- Browser: Firefox Developer 89.0b15 
-

**Comment by oandregal** [comment]
Testing this I've found that it works fine in the front-end just not in the editor.
