### ISSUE TITLE
Appearance Widgets screen: bugs in Twenty Twenty theme

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32279]
Hey all, I spotted a couple of bugs on the Appearance Widgets screen using Twenty-Twenty theme (background color and extra top spacing in the widget area containers):

![Screen Shot 2021-05-27 at 10 06 05 AM](https://user-images.githubusercontent.com/77359364/119850634-b8a70180-bedb-11eb-8c53-bf8304e30670.png)

**Comment by noisysocks** [comment]
Thanks for the report! This is a duplicate of https://github.com/WordPress/gutenberg/issues/31947 which @tellthemachines is working on.
