### ISSUE TITLE
Bug: Regression in core Legacy widget previews

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32281]
Hey all, I noticed a regression in the way core Legacy widgets display as a preview in both widget editors, not sure when this may have merged. Instead of displaying a "no preview available" placeholder, they are displaying as a wp-admin top bar. 

Here's how they look on the Appearance Widgets screen:

![Screen Shot 2021-05-27 at 10 26 05 AM](https://user-images.githubusercontent.com/77359364/119853857-8d71e180-bede-11eb-8418-7916f5faadb9.png)

And on the Customizer Widgets screen:

![Screen Shot 2021-05-27 at 11 25 37 AM](https://user-images.githubusercontent.com/77359364/119853900-98c50d00-bede-11eb-89e9-5dbe57d28513.png)

**Comment by noisysocks** [comment]
Note this happens only in the plugin. I'm working on a fix 🙂
