### ISSUE TITLE
Link UI does not preserve link relationships for Post (entity) links

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#32282]
## What problem does this address?

When adding a link within a paragraph block you can search and choose from a list of existing Posts (eg: entities - including Pages).

However, once you've _added_ this link the relationship to the original Post entity is _not_ preserved.

https://user-images.githubusercontent.com/444434/119855300-b22f7e80-bf09-11eb-93cd-04c53c2a0112.mov

You can try this by:

1. adding a link to a Post you've created.
2. click away onto another block.
3. clicking back on the link you just created.
4. You will see it's "type" is `URL` and there is no information preserved about the Post you originally link to.

## What is your proposed solution?

In the Navigation block we preserve the relationship to the entity so that once the link is added it contains some metadata which link it back to it's original entity. That way we should be able to display the link as type `Page` or `Post` or whatever and in future we should be able to pull through additional metadata to display in the Link UI.

**Comment by getdave** [comment]
Interestingly it looks like the format library _does_ in fact preserve both the link type (ie: post type) and entity `id` if provided. However we don't really make use of them.

**Comment by azaozz** [comment]
Wondering if it's worth it going a step further like having a `data-wp-postid` attribute on internal links. Another reason is that the `url_to_postid()` [(PHP) function](https://developer.wordpress.org/reference/functions/url_to_postid/#source) is bad, slow, hacky, etc. :) Having a good, reliable way to avoid it would be pretty nice.

**Comment by getdave** [comment]
Related https://github.com/WordPress/gutenberg/issues/18345

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/18345
