### ISSUE TITLE
Social Icons Block Style for Showing Labels

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#32280]
Users should be able to create a Social Links list that displays the social network's name/label next to the icon.  We already have a "Label" block option, which is currently used to set the `aria-label`.  It seems that we could expose that as text to non-screen readers too.

**Edit:** I'm not sure if a block style is the best route.  It might be better to have a toggle switch for enabling/disabling the label, which would give more flexibility for using the various icon styles.

Here's an example from an old theme I built:

![socially-awkward](https://user-images.githubusercontent.com/1816309/119852860-4af7d700-bed5-11eb-9d55-37e06c932887.png)

**Comment by stokesman** [comment]
👍  I agree, as do others: #31605

**Comment by justintadlock** [comment]
Read through 4 pages of search results trying to find a duplicate before posting this. :)

**Comment by stokesman** [comment]
I had to look pretty hard too, but I knew I'd seen it!
