### ISSUE TITLE
Search Block Server-Side Render Causes HTML Validation Error

### ISSUE THREAD

**Issue by jg314** [WordPress/gutenberg#32293]
## Description
When using a button within the Search block, an HTML validation error is generated because of a missing space between the `type` and `class` attributes within the button in the `render_block_core_search()` function. Right now the code looks like this:

`'<button type="submit"class="wp-block-search__button ' . $button_classes . '">%s</button>',`

There should be a space between `type="submit"` and `class="wp-block-search__button '`. 

This code currently exists within \wp-includes\blocks\search.php.

## Step-by-step reproduction instructions

1. Add the Search block to a page and use the settings to show a button.
2. Publish or update the page.
3. Run the URL or HTML through the [HTML Validator](https://validator.w3.org/).

## Expected behaviour
The rendered Search block should not generate an HTML validation error.

## Actual behaviour
An HTML "No space between attributes." validation error is generated when the Search block is used on a page.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows
- Browser: Chrome 90.0

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This has already been fixed in the Gutenberg plugin - https://github.com/WordPress/gutenberg/commit/02089c9b2b10a83c56c73662c37b714b30084a84 

In the meantime, 
You can download the plugin which provides newer fixes and enhancements to the block editor at https://wordpress.org/plugins/gutenberg/ 
and activate it. 

@annezazu - Could this be backported to a WordPress 5.7.3 release?

**Comment by jg314** [comment]
Sorry about that @skorasaurus. I tried searching open and closed issues, but didn't see it. Thanks to those who got this fixed. Hopefully it will land in WordPress Core shortly.

**Comment by annezazu** [comment]
Flagging for @youknowriad around backporting. Thanks for the ping.
