### ISSUE TITLE
Block Settings: Colors section randomly collapses/loses focus

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#32295]
## Description

When setting a custom color in the Block Settings for the first time, the modal is closed and the focus is lost upon selection. This seems to be a regression. This was found as part of the [sixth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/#comment-1648). 

## Step-by-step reproduction instructions

1. Add a paragraph block
2. Open the sidebar settings. 
3. Open Colors and select a custom color from one of the options.
4. Notice the Colors section collapses.

## Expected behaviour

Expect the color settings section to remain open unless I close it out. 

## Actual behaviour

Color settings section randomly closes upon making various selections.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/119908573-253bf380-bf10-11eb-8e7a-0684f6ed4d85.mov

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome Version 89.0.4389.128

**Comment by paaljoachim** [comment]
PR added here: https://github.com/WordPress/gutenberg/pull/32388
