### ISSUE TITLE
Build: Block Inserter

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#323]
Add button to insert blocks.

![insert](https://cloud.githubusercontent.com/assets/1204802/24293722/8029e8c2-1093-11e7-965e-b571ce87c88a.png)

## Behavior

A plus shows up at the end of the post. Click it to invoke the inserter:

![text](https://cloud.githubusercontent.com/assets/1204802/24293825/e0cbdb0e-1093-11e7-8c75-0c0d8a89c55d.png)

When you make a linebreak, the plus moves to the left:

![insert after or between](https://cloud.githubusercontent.com/assets/1204802/24293832/f08ffe44-1093-11e7-8bbf-3d2a4786914e.gif)

This is also how you would insert content between two paragraphs:

![newlines](https://cloud.githubusercontent.com/assets/1204802/24293881/2e5fcba0-1094-11e7-9bef-3b9810a12ac8.png)

You can also type `/` on a newline to invoke the inserter, just like how it works in Slack and many chat apps:

![slash to invoke](https://cloud.githubusercontent.com/assets/1204802/24293964/9da0486e-1094-11e7-9eed-8f19077109e7.gif)

There will likely be a permanently visible "Insert" button in the toolbar:

![inserter in toolbar](https://cloud.githubusercontent.com/assets/1204802/24294057/0a965076-1095-11e7-9789-8767b036ddec.png)

See also #34 and https://github.com/WordPress/gutenberg/issues/72#issuecomment-283696520 for alternate mockups for improving the look of the inserter.

**Comment by mtias** [comment]
A first pass at implementing in the plugin was merged in #307.

**Comment by jasmussen** [comment]
@timmyc I took the liberty of attaching you to this one, as you created some tickets about the inserter initially. Mind taking point on this one? ❤️

**Comment by inhll** [comment]
I realize it's a bit late as this is in development, but the current size of the picker seems small, especially as the number of available blocks increases.

Would placing the block picker horizontally improve the ability to find the type of block they want to insert?

![newlines](https://cloud.githubusercontent.com/assets/406182/24461346/65251778-1466-11e7-80e3-a3c8d0537d9f.png)

This placement allows more real-estate for new users to explore the available blocks while still allowing advanced users access to search as an accelerator.

**Comment by jasmussen** [comment]
That's a cool mockup, I like it! And it's not too late to think of good improvements. The inserter has been something that's always felt like it could use more iterations, so your work is welcome. 

I like the idea that it takes up the spot of a block, could lend itself to some of the animation finesse that @shaunandrews has also thought up. 

I like it!

**Comment by gabelloyd** [comment]
Is there a discussion about allowing the desktop toolbar to stay expanded while editing, or even on page load? I agree the little plus symbol is cleaner in appearance, but I have co-workers who use Google Sheets over Dropbox Paper simply because the toolbar is always exposed. 

Maybe a setting in Settings > Writing to check if you want the toolbar exposed permanently?

I'm referring to [this image](https://cloud.githubusercontent.com/assets/1204802/24294057/0a965076-1095-11e7-9789-8767b036ddec.png)

**Comment by inhll** [comment]
Allowing the toolbar to be expanded makes sense, but focusing the user on the act of writing will help them stay on task so it should probably remain uncluttered:
![admin ui-v1](https://cloud.githubusercontent.com/assets/406182/24512915/77f398b4-1535-11e7-86c7-867b0376751a.png)

Another option is showing the most recent (or most common) blocks users add to their pages. This helps surface options but may also keep users from becoming familiar with the interaction that allows in-post block additions.

![admin ui-v2](https://cloud.githubusercontent.com/assets/406182/24513149/1aba0538-1536-11e7-9b90-8fa1779e5417.png)

The option above does, however, offer novice / intermediate users a way of adding basic blocks, and familarizes them with the "click-plus-to-insert" interface pattern. Eventually they should realize they have the same plus button in editor and graduate to adding new blocks inside the editor. Then moving from intermediate to advanced, they'll click plus and search for the blocks they want to find..

**Comment by jasmussen** [comment]
> Is there a discussion about allowing the desktop toolbar to stay expanded while editing, or even on page load? I agree the little plus symbol is cleaner in appearance, but I have co-workers who use Google Sheets over Dropbox Paper simply because the toolbar is always exposed.

For now we're making the bet that an Editor bar with undo/redo/insert/post-settings/publish along with highly contextual block-first formatting tools can give us the best of both worlds those two worlds being feature rich and simple. If we find that this doesn't work in practice, it wouldn't be too hard for us to revisit this midstream. 

Love your mockups @inhll, great to have. Showing recents expandable like that is an idea worth revisiting if we find that it becomes necessary. As it stands, you'll be able to insert using the commandline (type `/ima` on a newline to search for image block and press enter to insert), there will be an insert button below the newline for manual clicking, a keyboard shortcut, as well as the one in the top toolbar. In addition to this you can drag and drop images from the desktop. We might find that this is sufficient. If it's not, good to have alternatives 👍

**Comment by inhll** [comment]
> Showing recents expandable like that is an idea worth revisiting if we find that it becomes necessary.

Absolutely -- the current approach covers all the bases and can be amended if necessary!

**Comment by mizejewski** [comment]
Riffing off the existing ideas, especially those from @inhll and @shaunandrews, here is a suggested flow for adding content to a page either at the bottom or between existing blocks.

The active content area is outlined by a box. There is a centered plus sign to add new content. Both are in an accent color chosen from the [official WordPress colors](https://make.wordpress.org/design/handbook/foundations/colors/) -- not the same color as text.

Adding content puts the focus on a small set of popular content types while the rest of page is greyed out (similar to focus mode in writing apps.) The user chooses a type and is placed in a new content box with editing tools.

![simple-flow](https://cloud.githubusercontent.com/assets/974442/25158913/cc0d1602-2460-11e7-8ba2-1ce0f20d3224.gif)
If the user needs a content type that's not in the short list, clicking MORE reveals a larger menu of choices. The choices appear below or between rather than floating over existing content. Choosing a content type from there also places the user in a new content box with editing tools.
![complex-flow](https://cloud.githubusercontent.com/assets/974442/25159049/b180b0c2-2461-11e7-9fad-f164d031735c.gif)

**Comment by jasmussen** [comment]
Really dig your work here, @mizejewski! Thank you for adding to the discussion, the animatics are extra helpful too.

It feels like at the core of your concept is the idea that the inserter, especially between content, "makes a space for itself" where the block will be inserted. This is especially visible in the last animatic that shows the paragraph below the inserter being pushed down. I really dig this, because it subconsciously tells you where the block you insert will land. The splash of color is also nice!

The plus that sits on the bottom of the block boundary seems a good established pattern to explore. We tried it, though, and it felt too heavy handed when we did. That doesn't mean it can't work, but I think it's worth maybe keeping it as an idea at this point that we can revisit when it becomes clear that it's necessary. Recent mockups puts an inserter at the top toolbar:

<img src="https://wpcoredesign.mystagingwebsite.com/gutenberg/Admin%20UI,%20Insert.png">

Or you can use the inserter that sits at the end of the document, when it is focused:

<img src="https://wpcoredesign.mystagingwebsite.com/gutenberg/Newlines,%20End.png">

If you insert a linebreak between content in the text, you can click the inserter button that shows up on the side:

<img src="https://wpcoredesign.mystagingwebsite.com/gutenberg/Newlines.png">

This last one ties right into your (and Shaun's and others) idea that the inserter is horizontal, and chisels out a space for itself. A horizontal inserter seems to be an idea that keeps bubbling up, so there seems to be meat on that bone. CC: @melchoyce.

(Also slick detail that the inserter on the side turns into a close cross — we should totally do that.) 🎉

In any case, there may be sufficient ways to insert blocks that we don't need the extra button that sits on the border. But we should definitely revisit if we find in testing that we do need that. 

Really nice work, thank you for doing this! 💖

**Comment by aduth** [comment]
From an implementation perspective, there's a question regarding:

>If you insert a linebreak between content in the text, you can click the inserter button that shows up on the side:

After inserting the line break, where is the cursor focused, and how do we know to show the inserter option? Is it a new empty text block? A new empty freeform block? A new paragraph within the existing text block? A new "unassigned" block type?

Seems like the default behavior for adding line breaks is to append a new empty text block. In which case, maybe it's the responsibility of the text block to display the inserter when it has an empty content state. Since it's on my mind, there could be a role for the Slot & Fill pattern idea in #507 in letting the text block's implementation _fill_ the block mover _slot_ with an inserter button.

**Comment by jasmussen** [comment]
> After inserting the line break, where is the cursor focused, and how do we know to show the inserter option? Is it a new empty text block? A new empty freeform block? A new paragraph within the existing text block? A new "unassigned" block type?

Solid question to bring up. I think we can flex on this, but I've always thought of the new line as being text, like anything else, per the "the newline is your commandline" idea. I.e. if you start the line with `- `, you're making a list, if you start the line with `# `, you're making an ordered list, if you start the line with `> `, you're making a quote, and if you start the line with `/` you have invoked the inserter and anything you type after filters that inserter. 

I'm aware that this is not quite how the inserter worked in the prototype, where the `/` command is more like a shortcut key. But your question does seem important especially to the block splitting and Continuous Text discussion (#447).

**Comment by mtias** [comment]
It makes sense to me that this is the responsibility of an empty text block.

**Comment by aduth** [comment]
It should probably have its own issue, but I'm going to task myself with implementing the "empty block" inserter button.

**Comment by jasmussen** [comment]
@aduth your empty block + inserter thoughts gave me some ideas for the inserter. Let me know your thoughts on these:

![inserter end](https://cloud.githubusercontent.com/assets/1204802/25491240/a6327ad8-2b6f-11e7-9a3e-db7a93c29ab8.png)

![inserter between](https://cloud.githubusercontent.com/assets/1204802/25491243/a775dbb0-2b6f-11e7-929f-bde75d6f5d87.png)

![inserter invoked with](https://cloud.githubusercontent.com/assets/1204802/25491245/a91d2036-2b6f-11e7-9387-d399151d9923.png)

![inserter searched](https://cloud.githubusercontent.com/assets/1204802/25491251/aaa78630-2b6f-11e7-869e-a5eccd661089.png)

![inserter from toolbar](https://cloud.githubusercontent.com/assets/1204802/25491256/ac4bdebe-2b6f-11e7-8c96-0ecac9b138da.png)

**Comment by mtias** [comment]
Some great stuff here.

**Comment by melchoyce** [comment]
Weird outlier question: what if someone means to type `/`?

**Comment by jasmussen** [comment]
> Weird outlier question: what if someone means to type /?

Great question to be asking. If written on a new line, as the first character, it should invoke the inserter. But if you type something that isn't in the inserter, or simply add a space after the /, then the inserter disappears again. Slack-esque.

That is —  the above would be the preferred behavior, and not how it works in the prototypes.

Incidentally this means that if you legitimately want to write one of the following phrases on a new line, you can't:

- `/`
- `/image`
- `/gallery`

etc.

But you can write, if you really want to, the following:

- `/ `
- `/image `
- `/gallery `

etc. 

I say "can" as if it's built, when in fact it's not built, and it might even be possible that we won't get to it because it's not as high priority as the other things. But the above is how it would work when I walk through it.

**Comment by jasmussen** [comment]
Closing this in favor of #833. The work done on the inserter so far has been impressive. Let's create atomic tasks for the rest.
