### ISSUE TITLE
Block toolbars: Add an option to transform text to lower case, upper case, and capitalize

### ISSUE THREAD

**Issue by zdenys** [WordPress/gutenberg#32308]
## What problem does this address?

Sometimes you would need to transform a part of the text (maybe a quote) into upper case. Or vice versa, when you paste some upper case text into the editor, you may need to make it all lower case. Currently there is no way to do it in the editor both ways. [The Notes app on macOS has a helpful feature to transform the text into upper or lower case or capitalize it](https://www.idownloadblog.com/2019/03/19/switch-uppercase-lowercase-mac/). It inspired me to post this feature request for Gutenberg.
## What is your proposed solution?

Add options in the block toolbar to make the text upper or lower case and maybe capitalize it. We already have text transformation options such as Superscript, Subscript, and Uppercase (but it only transforms the lowercase text into uppercase, but not the other way around). 

![image](https://user-images.githubusercontent.com/39308239/119964454-e9596a80-bfb1-11eb-9146-f00f2d92b227.png)

https://user-images.githubusercontent.com/39308239/119965201-b06dc580-bfb2-11eb-8bcc-51f3d52c8238.mov

**Comment by youknowriad** [comment]
Hi there!

I think this already exists as a block support and available in some blocks (navigation, site title, site tag line), it's an inspector control. It is still experimental though.

**Comment by mtias** [comment]
The uppercase option shown there is also not from core. I'd imagine it's coming from CoBlocks.

**Comment by mtias** [comment]
Closing in favor of #20801.
