### ISSUE TITLE
Add the persistent List View to the Widgets screen

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#32311]
## What problem does this address?
As of Gutenberg 10.7, the Widgets Editor uses the classic, non-persistent List View.

<img width="929" alt="Captura de pantalla 2021-05-28 a las 12 54 34" src="https://user-images.githubusercontent.com/27339341/119973590-f5dec280-bfb3-11eb-86e5-476442d162fc.png">

## What is your proposed solution?
Adding the Persistent List View to the Widgets Editor would provide a better UX as well as consistency with the Post and Template Editors.

**Comment by noisysocks** [comment]
Let's take care to address the bug described in https://github.com/WordPress/gutenberg/issues/32823 while we're at it.

**Comment by gwwar** [comment]
closed by https://github.com/WordPress/gutenberg/pull/35706
