### ISSUE TITLE
Cannot Edit or POST using Gutenberg Plugin 

### ISSUE THREAD

**Issue by KGrand78** [WordPress/gutenberg#32335]
## Description
Gutenberg Plugin prevents me from posting on my website. Previously reported by HolbeeOne but you are ignoring that report from yesterday.

## Step-by-step reproduction instructions
 See screenshot

## Expected behaviour
I expect to be able to add or edit a post.

## Actual behaviour
Error message ( see screenshot)
![Screen Shot 2021-05-29 at 10 03 52 AM](https://user-images.githubusercontent.com/85025289/120073429-4282d600-c066-11eb-99c4-015b468be9e7.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No Troubleshooting was performed by my hosting service

## Device information
- Device: MacBook Pro
- Operating system: OS 10.13.6
- Browser: Chrome Version 92.0.4512.4 (Official Build) dev (x86_64)
- ****

**Comment by carolinan** [comment]
Hi
Reports are not ignored, but more details and testing is needed to locate the problem.

Are you able to select "Copy error" and paste the result?

**Comment by talldan** [comment]
@KGrand78 (just dropping a direct ping to make sure you get a notification about the above message)

**Comment by priethor** [comment]
Let's close this issue as we are unable to replicate and the activity has stalled. Feel free to reopen if the issue resurfaces.
