### ISSUE TITLE
Block toolbar not displayed in the widgets screen

### ISSUE THREAD

**Issue by Chouby** [WordPress/gutenberg#32348]
## Description
The toolbar may not be displayed when selecting a (legacy) widget

## Step-by-step reproduction instructions
1. Setup a site with WP 5.7.2 and a few (legacy) widgets
2. Update to WP 5.8 and visit the new widgets screen
3. Scroll down to the bottom of the screen
4. Select the latest widget

## Expected behaviour
I expect the block toolbar to be visible when the widget is selected.

## Actual behaviour
The block toolbar is not visible when the widget is selected (screenshot 1). I need to scroll up to see the toolbar appear (high in the screen) but in my case the selected widget almost disappeared from the screen (screenshot 2).
 
## Screenshots or screen recording (optional)
![widget-screen](https://user-images.githubusercontent.com/3238583/120195361-fb8c1080-c21e-11eb-8db1-ec8c56b295ee.png)
![widget-screen-2](https://user-images.githubusercontent.com/3238583/120196554-44909480-c220-11eb-9c7c-d7aa5eb280c6.png)

## WordPress information
- WordPress version: 5.8-alpha-51034
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Linux Mint
- Browser: Chromium 90

**Comment by noisysocks** [comment]
Hi! I wasn't able to see this by following the steps in Chrome on macOS. Maybe it's Linux specific? Are you still seeing the problem in the latest 5.8 alpha? Any additional info you have would be helpful!

https://user-images.githubusercontent.com/612155/121621802-3a885480-cab0-11eb-9537-caa8b682d05c.mp4

**Comment by Chouby** [comment]
It's indeed now fixed in 5.8-beta1-51137.
