### ISSUE TITLE
Do not allow templates named by core to be renamed, and display descriptions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#32362]
In the template editor it's currently possible to rename _any_ template:

<img width="1500" alt="Screenshot 2021-06-01 at 09 39 25" src="https://user-images.githubusercontent.com/846565/120293543-465c6580-c2bd-11eb-8da4-a9c14189e10d.png">

But in the Site Editor, templates that are named by core (Index, Page, Archive, etc) cannot be renamed. The thinking there is that any benefits that custom names bring are offset by the potential confusion that can arise when users inadvertently give a template an inappropriate name. Not to mention all the existing documentation that refers to these templates specifically by name. 

I think it's worth bringing this site editor treatment to the template editor, making use of the existing template descriptions.

<img width="1500" alt="Screenshot 2021-06-01 at 09 55 30" src="https://user-images.githubusercontent.com/846565/120295923-858bb600-c2bf-11eb-8be7-63be2e21e291.png">

**Comment by youknowriad** [comment]
cc @jorgefilipecosta
