### ISSUE TITLE
Question: considered using Substance.io?

### ISSUE THREAD

**Issue by nicooprat** [WordPress/gutenberg#3237]
Hi

Just a simple question, I already knew this project http://substance.io/ that looks like what Gutenberg wants to become.

If not considered, maybe some ideas to get from there, or efforts to merge?

If considered, why creating a new project?

Thanks.

**Comment by karmatosed** [comment]
Thanks for linking the project, however Gutenberg is it's own thing as the editor for WordPress reinvented. At this point it's not a standalone editing platform.

**Comment by nicooprat** [comment]
Agree, but Substance isn't either. It's a NPM package (https://github.com/substance/substance), used by some of their project, but really modular and extensible by nature. It's more like Draft for React. It even supports realtime collaboration, which could be awesome for Wordpress.

Some examples for those interested: http://substance.io/examples/.
