### ISSUE TITLE
Page List block unusable as a standalone block

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#32379]
## Description
In my ThisIs theme I used the Page List block in the sidebar for navigation. In Gutenberg 10.6.0 it was displayed as a tree,
similar to the bw_tree equivalent and Page Tree (shortcode) sections in the screen capture.

With Gutenberg 10.7.1 it's almost impossible to pick an item from a nested list.
You can see the items when you hover over the top level.
But cannot pick one.
The third level is even less accessible than the first.

My understanding was that this block could be used standalone. ie It doesn't have to be part of a navigation menu.
I don't want the page list to appear as a menu since I'm using it in the right side bar. 

## Step-by-step reproduction instructions
1. Create a page hierarchy with more than two levels
2. Insert a page list block in one of the pages
3. Save
4. View

## Expected behaviour
A tree of links to the pages.

## Actual behaviour
- The top level is displayed.
- When you hover over the page list the child items appear _somewhere_ on the page. 
- I don't think you can access third level items.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2474435/120369087-bb09c100-c30a-11eb-82af-ed60652a4438.png)

This is the Page list when used inside a vertical menu.
It too has usability issues. Once the submenu is displayed you have to move the mouse off the list in order to be able to see the submenu for the next item in the top level. 

![image](https://user-images.githubusercontent.com/2474435/120369829-c27d9a00-c30b-11eb-929d-c56c885e7ed6.png)

When used in the sidebar the 3rd level menu item is truncated.
It should say "Tag Cloud Limitations."
![image](https://user-images.githubusercontent.com/2474435/120370981-22c10b80-c30d-11eb-85c2-d56a6e2399e3.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1 
- Are all plugins except Gutenberg deactivated? No 
- Are you using a default theme (e.g. Twenty Twenty-One)? No I'm using ThisIs

## Device information
- Device: Desktop
- Operating system:  Windows 10 
- Browser:  Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by jasmussen** [comment]
Thank you for the report. #32384 fixes it.
