### ISSUE TITLE
Template editor does not respect the full or wide width setting of a block

### ISSUE THREAD

**Issue by swoodipto** [WordPress/gutenberg#32389]
## Description

When editing a template, the width of the blocks that are set to full or wide widths are reduced & do not match the layout in the Editor.

It looks like the Editor does not respect Full and Wide width settings of blocks.

## Step-by-step reproduction instructions

1. Activate tt1-blocks (or any theme that opts in to the new layout system)
2. Create a new page and add some content and set some block to full or wide width
3. Create a new template
4. The template editor loads by reducing the width of the blocks that are set to full or wide

## Expected behaviour

The template editor should respect the width settings of the block and show the same in the template editor.

## Actual behaviour

The template editor does not respect the full or wide width settings of blocks

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/29238672/120450415-0e811b00-c3ae-11eb-969f-788cd710a57c.mp4

## WordPress information

- WordPress version: 5.7.2 (WordPress.com)
- Gutenberg version: 10.5 (WordPress.com)
- Are all plugins except Gutenberg deactivated? Simple WordPress.com site
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (TT1 Blocks)

## Device information

- Operating system: MacOS 11.3
- Browser: Firefox & Vivaldi

**Comment by youknowriad** [comment]
This should be fixed now.
