### ISSUE TITLE
Saving fatigue -Feature request: Turn off the multi entity saving step

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#32386]
## What problem does this address?

I'd like to be able to turn off the multi entity saving step in the same way as was we can turn off pre publish checks.
I "just want to save".

**Comment by carolinan** [comment]
The more I work with the site editor, this is becoming more of a problem, because I keep forgetting that I have to do two steps, and then I wonder why my changes are not applied...

**Comment by SchneiderSam** [comment]
Same here. I have very many problems with this process.
