### ISSUE TITLE
Change import of `react-spring` to fix NPM 7 compatibility

### ISSUE THREAD

**Issue by andrejcremoznik** [WordPress/gutenberg#32398]
NPM 7 cannot install `react-spring` due to a change in peer dependency resolution https://github.com/pmndrs/react-spring/issues/1413

https://github.com/WordPress/gutenberg/blob/435dde470f5541ba397a83126333223abe1eee41/packages/components/src/snackbar/list.js#L6

Should be `@react-spring/web`

**Comment by gziolo** [comment]
@gwwar is about to remove `react-spring` from the list of dependencies in  #33717 and https://github.com/WordPress/gutenberg/pull/33827 so this should resolve this issue.
