### ISSUE TITLE
Recently imported+edited template does not appear on the page editor's template list

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#32390]
## Description

When a template is imported as a block pattern, and when it is edited, I am able to come back to the normal page editor mode. Upon doing so, the newly imported+edited template is missing from the `Templates` dropdown list. 

## Step-by-step reproduction instructions

- Import a template as a block pattern (I haven't tested if the same behaviour can be seen for new templates as well)
- Edit the template on the template editing mode
- Come back to the normal page editing mode
- See that the template on the right sidebar shows the first one on the list and not the one you just created/edited.

## Expected behaviour

The recently edited template must be chosen.

## Actual behaviour

The first template in the list is chosen instead. In this screenshot, it shows `404` but I was expecting that to be `Portfolio` template because that's what I just imported/edited.

![image](https://user-images.githubusercontent.com/18581859/120450285-f5786a00-c3ad-11eb-989e-3d2fed92b4bd.png)

## Screenshots or screen recording (optional)

Added above.

## Code snippet (optional)

Not applicable.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.5.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Mayland Blocks

## Device information
- Device: MacBook Pro
- Operating system: Mac OS
- Browser: Firefox 88.0.1

**Comment by youknowriad** [comment]
I think this is fixed in #32744
