### ISSUE TITLE
List content lost when switching list type

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32405]
## Description

List content lost when switching list type.

## Step-by-step reproduction instructions
In any block editor:

1. add a list block
2. add some list items
3. from the block toolbar convert from unorererd to ordered
4. list content is lost

## Expected behaviour

List content to not be lost

## Actual behaviour

List content is lost

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/107534/120514800-57e56080-c3d6-11eb-87c6-672a3ee83bfc.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Safari

**Comment by paaljoachim** [comment]
I just tested with WP 5.8 and switching between list types removes the list content.

**Comment by torounit** [comment]
https://user-images.githubusercontent.com/1908815/120589344-a98ff880-c473-11eb-9d46-0386b4aac1fb.mov

Values are saved.  Indenting will apply the changes.

Gutenberg version: Trunk

**Comment by torounit** [comment]
The new value is passed to `<RichText>`, but it is not displayed correctly.

**Comment by torounit** [comment]
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/rich-text/src/component/index.js#L201-L204

If the `applyFromProps` on this line is executed, the edited text will be returned.

**Comment by torounit** [comment]
https://github.com/WordPress/gutenberg/blob/79cb3ebb524931bb845623f3bc46bc40f859235d/packages/rich-text/src/component/index.js#L148

If you comment out this line, it will be displayed correctly.

**Comment by ellatrix** [comment]
I see this is also happening with the heading block. We have a test that was supposed to guard against problems with placing the node type, but it didn't test adding content: https://github.com/WordPress/gutenberg/blob/979fb042e70dac4345d2ee8a08b1398a5b7827be/packages/e2e-tests/specs/editor/various/rich-text.test.js#L19.

**Comment by torounit** [comment]
@ellatrix Happening with the heading block too.

https://user-images.githubusercontent.com/1908815/120743764-97c25a00-c534-11eb-8def-5245d3e87cd0.mov
