### ISSUE TITLE
Widgets editor: Breadcrumbs are missing

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#32418]
## Description

The breadcrumb component at the bottom of the screen is missing from the widgets editor. This makes it difficult to select a parent block if you are used to using this component in the post editor.

## Step-by-step reproduction instructions

1. Go to Appearance → Widgets.

## Expected behaviour

There should be a breadcrumb component, like in the post editor:

<img width="1252" alt="Screen Shot 2021-06-03 at 13 33 30" src="https://user-images.githubusercontent.com/612155/120582731-54061c80-c470-11eb-8a53-fafa2b6d4416.png">

## Actual behaviour

There is nothing:

<img width="1252" alt="Screen Shot 2021-06-03 at 13 34 12" src="https://user-images.githubusercontent.com/612155/120582754-63856580-c470-11eb-8fdd-a0475fe308c3.png">

**Comment by ramonjd** [comment]
@noisysocks I've thrown up a [WIP PR](https://github.com/WordPress/gutenberg/pull/32498) 

Works fine :) 

I was wondering whether it would be worth adding selectors, similar to what we have in the [editPostStore](https://github.com/WordPress/gutenberg/blob/cae774957e115d03c2c3771d16c6d6b6995073f4/packages/edit-post/src/components/layout/index.js#L244), to decide whether to show the breadcrumbs now or in a later iteration.

If so, would we add them to `editWidgetsStore` or `interfaceStore`? Any tips are welcome 🙇

**Comment by kevin940726** [comment]
I wonder if we would want to add the same thing for the customizer editor?
