### ISSUE TITLE
Widgets editor: Block toolbar doesn't appear after selecting multiple blocks

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#32419]
## Description

The block toolbar does not appear after selecting multiple blocks in the widgets editor.

## Step-by-step reproduction instructions

1. Go to Appearance → Widgets.
2. Select multiple blocks e.g. by shift + clicking.

## Expected behaviour

The block toolbar should appear.

<img width="1252" alt="Screen Shot 2021-06-03 at 13 36 40" src="https://user-images.githubusercontent.com/612155/120582997-bd862b00-c470-11eb-93e5-fd7f81dfa62b.png">

## Actual behaviour

Behaviour is inconsistent. Sometimes no toolbar appears. Sometimes a toolbar for the last block appears.

<img width="1252" alt="Screen Shot 2021-06-03 at 13 38 35" src="https://user-images.githubusercontent.com/612155/120583164-0b029800-c471-11eb-89da-ca43314ff1af.png">

**Comment by tellthemachines** [comment]
I definitely noticed this issue before, but am unable to reproduce it now, either in WP trunk or Gutenberg. Could you re-check? I'm using latest Chrome fwiw.

Edit: I can't repro this on Safari or Firefox either.

**Comment by draganescu** [comment]
Same as @tellthemachines I cannot repro in WP trunk with Gtb trunk.

**Comment by noisysocks** [comment]
Yes I can still repro in both WordPress trunk and Wordpress trunk + Gutenberg trunk using both Firefox and Chrome. I have Twenty Twenty-one activated.

https://user-images.githubusercontent.com/612155/121106743-f1cf6200-c849-11eb-9200-0fb848db5239.mp4

**Comment by talldan** [comment]
I think this is the same bug as https://github.com/WordPress/gutenberg/issues/32056 - shift clicking to multi-select doesn't seem to work in nested blocks (e.g. widget areas).
