### ISSUE TITLE
Custom Colors broken in 10.7.1

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#32410]
## Description
On sites running WordPress 5.7.2 and Gutenberg 10.7.1, I'm unable to select custom colors in the editor.

## Step-by-step reproduction instructions
1. Make sure you're running 5.7.2 and 10.7.1, both the latest releases.
2. Open a new post or page.
3. Add an element that has a color control.
4. Open the color panel in the sidebar and see that there is no option for adding a custom color.

## Expected behaviour
I expect there to be an option to add a custom color.

## Actual behaviour
There is no option.

## Screenshots or screen recording (optional)

With 10.7.1 activated: 

![image](https://user-images.githubusercontent.com/2846578/120539415-8f8fe080-c3b5-11eb-9561-4adb4b77d2ff.png)

With the Gutenberg plugin deactivated:

![image](https://user-images.githubusercontent.com/2846578/120539474-9e769300-c3b5-11eb-901f-b28f97bd3fdb.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, also tested on several other themes.

## Device information
- Device: Desktop
- Operating system: OSX 11.3.1
- Browser: Chrome 90.0.4430.212

**Comment by lukecarbis** [comment]
Just chiming in to say that I have noticed the same thing.

**Comment by lukecarbis** [comment]
I noticed that if you specify `disableCustomColors={ false }` (which should be the default), the Custom Color option returns.

**Comment by Sandstromer** [comment]
I noticed this too, and at first wasn't sure if this is a feature or a bug.

Custom colors can still be added/edited in the Site Editor Global Styles, and then the new custom color is available for selection in the post/page/block editor.

I'm now thinking it's a bug as we still need to be able to add custom colors when the global styles is not accessible.

**Comment by youknowriad** [comment]
cc @nosolosw @jorgefilipecosta

**Comment by oandregal** [comment]
This is fixed in 10.8 as per https://github.com/WordPress/gutenberg/pull/32200
