### ISSUE TITLE
RichText no longer works with the onFocus event

### ISSUE THREAD

**Issue by lukecarbis** [WordPress/gutenberg#32415]
## Description
In WordPress 5.7.2 (without the plugin), a RichText component can be passed the `onFocus` event, and it works as expected. Activating Gutenberg 10.7.1 breaks the onFocus functionality.

## Step-by-step reproduction instructions
1. Create a RichText component in a separate plugin or theme
2. Give it an onFocus event, which logs something to the console
3. Test it **without** the Gutenberg plugin installed (notice the text in the console)
4. Test it **with** the Gutenberg plugin installed (the text no longer appears in the console)

Alternatively, here's a sandbox:
https://codesandbox.io/s/wp-richtext-onfocus-test-6r1eh?file=/src/App.js

1. Open [this sandbox](https://codesandbox.io/s/wp-richtext-onfocus-test-6r1eh?file=/src/App.js)
2. Set the `@wordpress/block-editor` requirement to 6.1.1 or 6.1.0
3. Notice that `onFocus` doesn't fire, and `onBlur` does
4. Change the `@wordpress/block-editor` requirement to 6.0.0
5. Notice that `onFocus` fires, and `onBlur` doesn't

## Expected behaviour
RichText fields should trigger a given onFocus event when they receive focus.

## Actual behaviour
RichText fields no longer trigger onFocus events (though they once did).

## Code snippet (optional)
https://codesandbox.io/s/wp-richtext-onfocus-test-6r1eh?file=/src/App.js

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: MacBook Pro
- Operating system: MacOS Big Sur
- Browser: Safari & Firefox

**Comment by lukecarbis** [comment]
@ellatrix I hope you don't mind if I ping you on this – I believe you've been actively working on RichText.

**Comment by Thelmachido** [comment]
Hi @lukecarbis 

As there hasn’t been any movement on this issue since it was opened, I’ve marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by ndiego** [comment]
@lukecarbis just checking in. Would you be able to test with the latest version of the ` @wordpress/block-editor` to see if this is still an issue? Thanks for your help!

**Comment by lukecarbis** [comment]
@ndiego Yes – I'll do so today.

**Comment by lukecarbis** [comment]
@ndiego After updating the code in the original sandbox to work with React 18, and using the latest version of all included scripts, this problem is still not fixed.

[Sandbox using `@wordpress/block-editor` version 11.2.0](https://codesandbox.io/s/wp-richtext-onfocus-test-forked-qf4enl?file=/src/App.js)

Let me know if there's anything further that you need.

**Comment by ndiego** [comment]
Awesome, thanks for confirming @lukecarbis!

**Comment by ellatrix** [comment]
Does #47685 fix this?

**Comment by lukecarbis** [comment]
@ellatrix Yes, it does!
