### ISSUE TITLE
Post Content Block: transforming to Group causes rendering error

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#32412]
## Description

If you try to transform a post content block to a Group, a rendering error occurs. This is possible with the Post Title block but not with the Post Content. I can't quite tell if the solution is to allow for the transform to occur or to remove it as an option as it's not something we want people doing. 

## Step-by-step reproduction instructions

1. Add a post content block ideally inside a template you're editing.
2. Use the transforms menu to change it to a group
3. See rendering error

## Expected behaviour

Expect to be able to transform to a group. 

## Actual behaviour

Rendering error. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/120545100-72eeab00-c3ab-11eb-8bd1-979d8dc09074.mov

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Blank Canvas

## Device information
- Device: Desktop
- Operating system: MacOS 11.2.1
- Browser: Chrome Version 89.0.4389.128

**Comment by jordesign** [comment]
Just to clarify a little further - the reason I was trying to 'Group' the block was in order to place a background color behind the whole content area.

By comparison - inserting a Group Block - and then placing the Post Content block *inside* it worked without a problem.
