### ISSUE TITLE
Ability to drag blocks into the whitespace between the title and content, and content and bottom of screen

### ISSUE THREAD

**Issue by nixsee** [WordPress/gutenberg#32438]
## What problem does this address?
It is frustratingly difficult to drag a block to the top or bottom of the content section. When you do this you have to be pixel-precise to find a small sliver blue line to drag it to. 

## What is your proposed solution?
Dragging a block into the white space between the title and first content should move the block into the first position. Dragging to the whitespace between the last block and bottom of screen should move it to the last position.

![sX1QbeAvBH](https://user-images.githubusercontent.com/24255237/120686375-231cec00-c45e-11eb-89aa-cbbbe58238e5.gif)

**Comment by nixsee** [comment]
I'd also make the same observation about dragging blocks within List View - you have to find a small sliver at the top and bottom of the list rather than anywhere beyond the first and last blocks.

**Comment by andrewserong** [comment]
Just assigning myself to this one — I'll be curious to see if we can solve this using a similar approach as to what we did in the list view in #50726.

**Comment by andrewserong** [comment]
Resolved in #56070
