### ISSUE TITLE
Link inside a metabox is opened on the metabox container.

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3243]
When clicking a link from inside a metabox, the link page opens inside the metabox container.

**Test Code**

```
add_action( 'admin_head', 'my_meta_box' );

function my_meta_box() {
	global $post;
	add_meta_box( 
		'my_meta_box', 
		__( 'My metabox', 'my-context' ), 
		'my_meta_box_callback', 
		$post->post_type, 'side' 
	);
}

function my_meta_box_callback() {
    echo '<p>Lorem ipsum dolor sit amet.</p>';
    echo '<a href="https://wordpress.org/">wordpress.org</a>';
}

**Comment by christopherabalos** [comment]
Related: calls to open the media modal via wp.media results in the modal being loaded inside of the iframe.

**Comment by BE-Webdesign** [comment]
Hi kmgalanakis,

Thank you for the report again. I believe there are ways to get around this. We can try them out, and see if that improves the situation.
