### ISSUE TITLE
3 CSS errors in block-library style.min.css

### ISSUE THREAD

**Issue by Jim537** [WordPress/gutenberg#32434]
re: https://wordpress.org/support/topic/w3c-css-validator-3-css-errors/

W3C CSS Validator results for

https://wordpress.org/support/wp-includes/css/dist/block-library/style.min.css  

(CSS level 3 + SVG)

Sorry! We found the following errors (3)

1 .is-content-justification-right, .is-content-justification-left, .is-content-justification-center

Parse Error [.is-content-justification-space-between]

1 .is-content-justification-right, .is-content-justification-left, .is-content-justification-center

Parse Error .is-content-justification-center) .wp-block-button.aligncenter{margin-left:auto;margin-right:auto;margin-bottom:.5em;width:100%}

11 .wp-block-separator.is-style-dots

Value Error : width Too many values or values are not recognized : none

Online Test at http://jigsaw.w3.org/css-validator/#validate_by_uri

**Comment by skorasaurus** [comment]
Thanks for reporting. 

The third error ( .wp-block-separator.is-style-dots); I cannot reproduce with the validator using wp-includes/css/dist/block-library/style.min.css found in WordPress 5.7.2

The first two errors, I can reproduce with the w3 validator, are specifically from the buttons block, and the code is in build/block-library/blocks/buttons 

I don't have time right now to continue with this.

**Comment by thuthiemzeit** [comment]
I have the same question!
[jigsaw.w3.org===> Error my site](http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fhouse.com.vn%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)
`


.is-content-justification-right, .is-content-justification-left, .is-content-justification-center | Parse Error [.is-content-justification-space-between]
-- | --
1 | .is-content-justification-right, .is-content-justification-left, .is-content-justification-center | Parse Error .is-content-justification-center) .wp-block-button.aligncenter{margin-left:auto;margin-right:auto;margin-bottom:.5em;width:100%}

`

**Comment by skorasaurus** [comment]
I'm no longer able to reproduce this; there have been some fixes to the button block since then and this appears to have been resolved; [the core minified block-library style ](https://wordpress.org/support/wp-includes/css/dist/block-library/style.min.css)
no longer returns any errors on the w3 validator. 

@thuthiemzeit ; I ran the validator again on your site and no errors were detected.

Please reopen if you are still experiencing this issue.
