### ISSUE TITLE
Fallback Featured Image

### ISSUE THREAD

**Issue by maharzan** [WordPress/gutenberg#32447]
I have been trying to learn making block base themes and encountered a simple issue. I need to show a default fallback image if the posts have no featured images. 

Obviously, with older/current method, we can do it something like this

    <?php if ( has_post_thumbnail() ) {
     the_post_thumbnail();
     } else { ?>
     <img src="<?php bloginfo('template_directory'); ?>/images/default-image.jpg" alt="<?php the_title(); ?>" />
     <?php } ?>

But with blocks and new html templates, I can only do

    

Further digging down the files, I saw this file and line was extracting the featured image and I didn't see any hooks in there so I can try to replace it in functions.php

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-featured-image/index.php#L24

Is this possible in any other way? If not, I guess it would be really nice to have a hook in there so we can apply a default featured image on new block based themes.

**Comment by paaljoachim** [comment]
Hi @maharzan Chandra

I will call this an associated issue:
There has been some explorations here (linking to my comment): 
https://github.com/WordPress/gutenberg/issues/13795#issuecomment-636787215
Where I explored setting the first image in the post/page as a featured image.

**Comment by maharzan** [comment]
I wonder why such simple things has become so complex nowadays..

**Comment by paaljoachim** [comment]
We should think out a simpler solution and present it..:)

**Comment by justintadlock** [comment]
For now, you could just use the `post_thumbnail_html` hook: https://developer.wordpress.org/reference/hooks/post_thumbnail_html/

**Comment by altivero** [comment]
I think this should be the default setting as outlined in the issue I created about this here: #31849

**Comment by maharzan** [comment]
> For now, you could just use the `post_thumbnail_html` hook: https://developer.wordpress.org/reference/hooks/post_thumbnail_html/

I tried it but it seems we can only alter the html once we get the featured image html which when not present doesn't seem to return any html as given in this line: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-featured-image/index.php#L24

**Comment by maharzan** [comment]
> For now, you could just use the `post_thumbnail_html` hook: https://developer.wordpress.org/reference/hooks/post_thumbnail_html/

Thanks @justintadlock. That seems to do the trick.

**Comment by ntsekouras** [comment]
Thanks for reporting @maharzan and @justintadlock for pointing out the proper filter: https://github.com/WordPress/gutenberg/issues/32447#issuecomment-854949102.

I'll close this now as related discussions here are tracked in separate issues.

**Comment by paaljoachim** [comment]
Hey Nik @ntsekouras 

I believe we might need to open this issue again, as the associated issue: 
Add option to set as feature image to image / cover block - has been closed. 
https://github.com/WordPress/gutenberg/issues/13795

I believe there still are aspects needed to be looked closer at in both issues.

**Comment by paaljoachim** [comment]
I went ahead and reopened this issue.

**Comment by skorasaurus** [comment]
While triaging, I found this also to be reported at https://github.com/WordPress/gutenberg/issues/34865 with a bit of discussion there as well so I am closing this issue. Please follow that issue for further updates and to share any opinions that you have.
