### ISSUE TITLE
Widgets block editor: Block selection outline is missing

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#32448]
## Description

The blue block selection outline has gone missing in the widgets block editor screen.

## Step-by-step reproduction instructions

1. Go to Appearance → Widgets.
2. Select a block. (It's most notable with blocks that have a placeholder e.g. Image.)

## Expected behaviour

The block should have a blue outline indicating that it's selected.

<img width="1252" alt="Screen Shot 2021-06-04 at 14 05 03" src="https://user-images.githubusercontent.com/612155/120744368-2ab3c200-c53e-11eb-84ac-f1d6580d5117.png">

## Actual behaviour

There's no outline and it's hard to tell what is selected.

<img width="1252" alt="Screen Shot 2021-06-04 at 14 05 00" src="https://user-images.githubusercontent.com/612155/120744384-31dad000-c53e-11eb-83c8-d354e63d8700.png">

**Comment by youknowriad** [comment]
I noticed the same thing in the post editor in "empty" themes. Apparently it could be related to the "is-dark-theme" class that is added automatically depending on the computed background.
