### ISSUE TITLE
Reusable block: Add a lock to the parent toolbar to protect the inner content from accidental editing.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32461]
## Description
There has been multiple complaints of accidental changes with the Reusable block in WP 5.7. In earlier versions we had an edit button protecting the inner blocks, but in 5.7 the edit button was removed. Making a one click directly into the Reusable block inner content.

## Step-by-step reproduction instructions
1. In WP 5.7.
2. Add a Reusable block.
3. Click the Reusable block. 
4. Make a change.
5. Do other changes to the page.
6. Click save.

## Expected behaviour
In WP 5.6. There was an edit icon one had to click to edit the contents. Protecting against accidental changes.
I expected to see also a protective measure in WP 5.7 that protected the content.

## Actual behaviour
I happen to make a change and save it.

A possible solution is to add back a kind of edit/lock button.
Here is an example.

https://user-images.githubusercontent.com/5323259/120826687-fe5a6e80-c55a-11eb-8b68-f7fbf3a81d1f.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not active
- Are all plugins except Gutenberg deactivated? No plugin active
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One.

Associated issues:
Improvements to Reusable Blocks
https://github.com/WordPress/gutenberg/issues/27890

Reusable block: A suggestion for a new revision.
https://github.com/WordPress/gutenberg/issues/31163

Try: Obscure edit-ability of post content blocks in the template editor (linking to my comment).
https://github.com/WordPress/gutenberg/pull/31461#issuecomment-854230231

On Locking and TemplateLocking
https://github.com/WordPress/gutenberg/issues/29864

**Comment by paaljoachim** [comment]
We have a few things happening.

A click through approach is being worked on. Located here (linking to a comment I made showing a video on how it works) https://github.com/WordPress/gutenberg/pull/31109#issuecomment-842456373

One selects/clicks and it will automatically select the top most container/parent block. Clicking again clicks into the inner contents.

Having a lock and a click through approach would be a helpful mix.

**Comment by peterwilsoncc** [comment]
Thanks Paal, 

I've been coordinating the 5.7.x minors and it would be great if this could be done as a half way step between the larger proposal to be backported in to the wp/5.7 branch. There have been a few issues raised on trac about difficulties people are having in 5.7 so putting in some improvement would be most helpful.

**Comment by cpsyctc** [comment]
I am not a programmer but a very frustrated user who has now lost hours trying to use reusable blocks for an obvious task for them where they should have saved me hours.  I am sure the following are vital:

- The ability to create unnamed reusable blocks was dangerous and should be removed.  
- I think there's a fundamental mistake in treating editing reusable blocks as something not much different to editing any other block in a page: to me they are completely different things. Editing a page or post is about that unique entity, editing a reusable block is changing a building block that may be in use elsewhere.
- We should be able to list and preview (but probably not edit, to avoid locking issues) reusable blocks independent of editing a page.  I want to be able to go and check out what reusable usable blocks I have without losing what I have done in a page.
- For me (5.7.2, using reusable blocks for the first time but working on pages created in probably 5.6) the "convert to ordinary block" which is a vital option, seems to be erratically visible.  This may be a corner case relating to the reusable block I was trying to use being a three column block.
- Surely if a reusable block has already been used in any other page/post it should be locked and you should be prompted if you try to edit it and warned that any edit will immediately change all other uses of the block? I would expect a dialogue to come up asking if I'm sure I want to edit the reusable block and offering to convert to an ordinary block.
- Related to that, if I have fallen into the trap of editing a reusable block within a page and I hit the update (or publish) button the current actions seem to me to be broken as they simply don't seem to successfully separate the two saving issues.  I would have expected the prompt against any reusable block (I have only ever used one on a page but presumably you could have used more than one) to prompt again with a clear warning and option to convert to an ordinary block.

To me these seem to be desperately serious faults in the current set up.  I hope they will be fixed soon.  TIA.

**Comment by thisissandip** [comment]
Unlock Icon is not available in @wordpress/icons package. 
So as of now, I have used plain text to display the lock and unlock state in the toolbar.

**Comment by jasmussen** [comment]
Which "unlock" icon are you referring to?

I found this lock icon in the icons package:

<img width="444" alt="Screenshot 2021-06-16 at 08 44 49" src="https://user-images.githubusercontent.com/1204802/122170760-3af16880-ce7f-11eb-9b05-0bd9f2c5e435.png">

<img width="907" alt="Screenshot 2021-06-16 at 08 43 43" src="https://user-images.githubusercontent.com/1204802/122170796-45abfd80-ce7f-11eb-845b-b5c630c8d610.png">

Edit: I'm also happy to help if we need to add anything to the library.

**Comment by thisissandip** [comment]
In the example video above,
To display the lock state, the lock icon from Dashicons is used.

![image](https://user-images.githubusercontent.com/69596988/122171529-713de080-ce9d-11eb-9296-8f435a941214.png)

And for the unlocking state, the unlock icon is used.

![image](https://user-images.githubusercontent.com/69596988/122171595-86b30a80-ce9d-11eb-8eff-d177b2aac22f.png)

I was looking for similar icons in the icons package but only found the lock icon and not the unlock one.
It'd be great to have an unlock icon in the package too!

**Comment by paaljoachim** [comment]
EDIT: I moved my reply to @cpsyctc  to this issue:
https://github.com/WordPress/gutenberg/issues/31163#issuecomment-862282230

I am working on keeping feedback to issues that already has various feedback.

**Comment by paaljoachim** [comment]
A PR has been added here:
https://github.com/WordPress/gutenberg/pull/32710

**Comment by critterverse** [comment]
Hi all, just left a note in https://github.com/WordPress/gutenberg/pull/32710#issuecomment-862445687 but also wanted to highlight a potential improvement available in https://github.com/WordPress/gutenberg/pull/31109. In my opinion, the clickthrough approach doesn't resolve all of the known issues with the Reusable block but it's a big improvement over where we are currently!

**Comment by paaljoachim** [comment]
I have left a couple of comments directly in the PR. The latest is here: https://github.com/WordPress/gutenberg/pull/32710#issuecomment-864425660
Where I create a suggestion using click through and a lock.
See the comment for additional information.

**Comment by arnemulder** [comment]
I really think that editing a reusable content block shouldn't be taken lightly. It should be done on a central place instead of in the context of a post or page that uses that reusable block. A clickthrough isn't enough imo. The lock is a far better idea, but still less protection than the old method of a separate post type to edit outside of the post or page that holds the reusable block. Access to the reusable content blocks to edit was a bit cubersome, but it was well protected outside of the context of a specific post.

**Comment by paaljoachim** [comment]
I want to add @pwkip Jules comment from:
**Add Reusable block save button, snackbar on save and Welcome Guide** PR 
(Which is ready for a last test and a code review before it is merged.)
https://github.com/WordPress/gutenberg/pull/32464#issuecomment-876315656

> Since the save button is in place now, what about changing it to an "Edit" button initially, then once you click it, the block becomes editable and the button changes to the Save button?

It is an intriguing idea. Something to look more into later after the above PR has been merged.

**Comment by BenWittert** [comment]
+1 for this issue. 

I have a large enterprise client who is experiencing significant issues related to content writers frequently accidentally editing reusable blocks as it is not clearly differentiated from their article content.

Our client considers this to be a huge issue, and they feel that reusable blocks are no longer fit for purpose in their current state and not usable for large enterprise businesses.

**Comment by paaljoachim** [comment]
@Mamaduka George is working on adding a lock to Reusable blocks in this PR:
https://github.com/WordPress/gutenberg/pull/39950

It can use some feedback!

**Comment by paaljoachim** [comment]
I just want to inform everyone on this thread that the first version of locking a Reusable block is in place. 
A NB! though. This will only lock an instance and not all identical Reusable blocks. This means if a Reusable block has been placed into the content and edit locked that it is not editable. 

This means to protect the site we need to first add the Reusable block into the content and lock it. Then we can let the user loose on the content without risking an accidental change.

**Comment by BenWittert** [comment]
> This means to protect the site we need to first add the Reusable block into the content and lock it.

@paaljoachim is this the intended final implementation style for the block lock? Or may it be possible in the future to set all instances to locked?

**Comment by paaljoachim** [comment]
Hey Ben

> is this the intended final implementation style for the block lock? 

No. This is just one important step.

> Or may it be possible in the future to set all instances to locked?

There are plans to explore how global lock will work.

The following is a comment by @jameskoster 
https://github.com/WordPress/gutenberg/pull/39950#issuecomment-1087399547

> I think it's probably a good idea to explore the default lock status separately.
> 
> On the surface it may seem a good idea, but there is nuance to consider – is the locking local or global? What level of locking do we apply, just movement, just editing, everything? Should there be an Editor setting to configure the default? There are also initiatives like https://github.com/WordPress/gutenberg/issues/39281 which may change how we feel.
