### ISSUE TITLE
Query block: Conflict with excerpt_more filter

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#32473]
## Description
It looks like the Query block outputs multiple More links when the Post Excerpt block is used within the Query block , and `excerpt_more` filter is used in the theme functions.

## Step-by-step reproduction instructions

1. Create new page.
2. Add the **Query** block to the content area (Grid View, and 3 columns layout to display 3 latest posts).
3. Select the **Post Excerpt** block.
4. In the **Post Excerpt** settings, set "Max words" to 25 and check option "Show link on new line".
5. Add "read more" link text.
6. Publish page.

## Expected behaviour
Only one More link should be shown in the excerpt section.

## Actual behaviour
The excerpt section displays two More links: one from the theme, added via `excerpt_more` filter, and another from the Query block, with a custom text added using the Editor.

![Multiple more links in the excerpt section](https://snipboard.io/g3BQhl.jpg)

## WordPress information
- WordPress version: "5.8-alpha-51064"
- Gutenberg version: Not installed
- Twenty Twenty-One: "1.3"
- Are all plugins deactivated? "Yes"

**Comment by dashkevych** [comment]
Additionally, I've noticed that if the Read More link is wrapped within `p` tag and added using the `excerpt_more` filter, the block creates additional empty `p` tag:

![Query block issue with more links](https://snipboard.io/HtZIDn.jpg)

**Comment by dashkevych** [comment]
It seems like this issue has not been fixed. It still shows two links in the Editor: 

![Excerpt issue](https://snipboard.io/4kszqp.jpg)

I've tested it in WordPress 5.8 with Twenty Twenty-One (Version: 1.4)

**Comment by ntsekouras** [comment]
>It seems like this issue has not been fixed. It still shows two links in the Editor:

Currently `PostExcerpt` block does show the rendered output in the editor, but if the theme uses `excerpt_more` filter, it's removed in the front-end. You can read the PR's description with these changes, where I explain some challenges to make this block consistent.

It will need more thinking and explorations in the future to make this as consistent as possible, but all the applied filters which some are conditional, makes it a tough problem.
