### ISSUE TITLE
block widgets unsuitable

### ISSUE THREAD

**Issue by HardcoreGames** [WordPress/gutenberg#32476]
Imposing blocks where previously Widgets were managed using a easier to handle format. Custom HTML is common for advertising which some blogs use for earning a few pesos. My site has a coffee jar and a link to paypal which is typical for a widget.

[https://www.hardcoregames.ca](https://www.hardcoregames.ca)

The block approach is grotesque in comparison. The blocks are fine for content but HTML tables are a weak area. I have to use custom HTML for sophisticated tables.

So while some dreamer wants XML across the board, this does not fit all. It actually adds overhead that is unwanted.

Some may find HTML intimidating, it is not that complicated. It only took me a few weeks to figure it out and there are lots of manuals with HTML fully documented.

**Comment by talldan** [comment]
There's a custom HTML block.

**Comment by HardcoreGames** [comment]
Compared to the classic, the blocks are 4x larger, unclear and there are 5x more blocks so it's unwieldy for a sidebar
