### ISSUE TITLE
TypeError: wp.apiRequest is not a function

### ISSUE THREAD

**Issue by metamn** [WordPress/gutenberg#3248]
## Issue Overview
I've just installed Wordpress and Gutenberg. When trying to add / view a post / page I'm getting a blank screen and this error in the console. 

## Steps to Reproduce (for bugs)

1. Install latest Wordpress 4.8.2
2. Remove all plugins (Akismet, Hello Dolly)
3. Install and build the Gutenberg plugin on a local Wordpress Environment (https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md)
4. Try to add / edit posts or pages.

I'm using Firefox 56.0 on Ubuntu. Tested also in Chrome Version 62.0.3202.62 (Official Build) (64-bit) with the same result.
I'm using Node v8.1.2 and npm 5.3.0

## Expected Behavior

I've expected to see the new Gutenberg editor

## Current Behavior

I've got a blank page. See the screenshot attached: https://imgur.com/a/HwnFi

## Possible Solution

Perhaps Gutenberg needs WP-API which is not specified in the documentation / between dependencies

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by metamn** [comment]
Both the Sample Page and the Hello World post can be edited with the classic editor

**Comment by metamn** [comment]
And here is the copy of the error log:

```
18:53:31.506 TypeError: wp.apiRequest is not a function 1 index.js:20488:16
	getResponseFromNetwork http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20488:16
	this.wp.components</__webpack_exports__.a http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20515:9
	request http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20290:6
	bind_applyFunctionN self-hosted:1125:9
	request self-hosted:1089:20
	initializeFetchable/< http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20200:8
	createBaseFor/< http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:9293:11
	baseForOwn http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:2589:20
	createBaseEach/< http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:9324:14
	forEach http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:4089:10
	initializeFetchable http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20189:6
	componentDidMount http://localhost/gut/wp-content/plugins/gutenberg/components/build/index.js:20162:6
	commitLifeCycles https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:37:411
	c https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:16:125
	k https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:19:411
	Q https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:20:355
	ed https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:24:374
	fb https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:23:397
	updateContainer https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:197:396
	Bb/< https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:105:517
	unbatchedUpdates https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:26:301
	Bb https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:105:487
	render https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js:203:478
	createEditorInstance http://localhost/gut/wp-content/plugins/gutenberg/editor/build/index.js:55014:17
	<anonymous> http://localhost/gut/wp-admin/post-new.php:1557:61
	i http://localhost/gut/wp-admin/load-scripts.php:2:27444
	add http://localhost/gut/wp-admin/load-scripts.php:2:27748
	<anonymous> http://localhost/gut/wp-admin/post-new.php:1557:1
```

**Comment by Soean** [comment]
Maybe a file is missing in your WP installation. 
Please go to Dashboard -> updates and click on "Re-install Now" and retest the issue.

**Comment by metamn** [comment]
Done. The same error occurs.

**Comment by metamn** [comment]
I saw a recent, similar looking issue (#3213) maybe they are connected

**Comment by aduth** [comment]
See #3249

This can occur if the shim for `wp.apiRequest`, a function included in WordPress 4.9, cannot be written fails to download or to write to disk. This could be an issue with the server on which WordPress is running not being able to request remote resources, or file permissions issues preventing the downloaded file from being written to a local cached copy.

**Comment by aduth** [comment]
You might have some success as a temporary workaround to delete your local vendor files:

```
cd path/to/gutenberg && rm -f vendor/*
```

**Comment by metamn** [comment]
My local vendor folder is / was completely empty ... should I re-install Gutenberg after the #3249 patch is done?

**Comment by aduth** [comment]
@metamn If you're running the plugin version, you'll have to wait until the next release, which is planned for this week. If you're running from the repository directly, you should be able to simply pull the latest master after #3249 is merged.

**Comment by metamn** [comment]
I've deleted the `gutenberg` folder and re-cloned the whole repository. Then re-enabled the plugin in the Admin. Now I have plenty of other different error messages: https://imgur.com/a/uixoX

**Comment by metamn** [comment]
Sorry, forgot to build the plugin ... done with `npm run dev` ... after that still lots of error messages: https://imgur.com/a/nRu0h (Firefox) and https://imgur.com/a/hIn6H (Chrome)
