### ISSUE TITLE
current rest-api.php breaks sites when saving options-general.php (10.7.1-10.7.3)

### ISSUE THREAD

**Issue by niaccurshi** [WordPress/gutenberg#32486]
If you create a site using the Gutenberg plugin that is version 10.7.1 through 10.7.3 inclusive, you can't save any settings on the general options page in the CMS without it breaking the site. It removes the values for the stylesheet and theme_mods_<STYLESHEET> options in the options table.

This resolves the problem: https://github.com/WordPress/gutenberg/pull/32229

As does (in a rough and potentially overreaching example) this code in your theme functions:

	add_action('init',function() {

		unregister_setting(
			'general',
			'theme_mods_' . get_option( 'stylesheet' )
		);

		unregister_setting(
			'general',
			'stylesheet'
		);

		remove_filter( 'rest_pre_get_setting', 'gutenberg_rest_pre_get_setting_filter_custom_logo', 10 );
		remove_filter( 'rest_pre_update_setting', 'gutenberg_rest_pre_set_setting_filter_theme_mods', 10 );

	});

It's frustrating that this is a particularly nasty bug for losing certain options on the site if you fall foul of it, and may not be discovered until well after any backup and install procedure for new plugins. 

We could really do with the pull request linked to above being fast-tracked! Here again for clarity: https://github.com/WordPress/gutenberg/pull/32229

**Comment by cpapazoglou** [comment]
Related comment https://github.com/WordPress/gutenberg/pull/32229#issuecomment-855985931

**Comment by talldan** [comment]
Judging by the comments, looks like this is now fixed as of Gutenberg 10.8, but let me know if I'm wrong.
