### ISSUE TITLE
Removing tabs while searching in the block inserter changes its height and therefore placement

### ISSUE THREAD

**Issue by ephox-mogran** [WordPress/gutenberg#3251]
## Issue Overview

When the user starts typing in the block inserter, the tabs get removed. This changes the height of the block inserter. When the block inserter is oriented down the screen, this is a little noticeable, but when the blocker inserter is oriented up the screen (because you are near the bottom of your viewport), then the position of the input jumps vertically.

Due to #1852 (https://github.com/WordPress/gutenberg/pull/1852)

## Steps to Reproduce (for bugs)

1. Create a few paragraphs so that your screen is mostly filled
2. Click the block inserter button. Watch it get displayed upwards
3. Start typing into the search bar

## Expected Behavior

The input should stay in the same place on the screen

## Current Behavior

The height of the dialog shrinks, which means that the input gets repositioned

## Possible Solution

Instead of making the tabs disappear, they could be disabled, or changed to something which is explaining the searching process. Not really sure.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
Good catch, that definitely is a bug. We should move the tabs to the bottom when this is an instance that happens. Here is what visually should happen:

![1](https://user-images.githubusercontent.com/253067/32808027-bd4ef760-c989-11e7-9a27-b232265f6c4c.png)

**Comment by aduth** [comment]
I'm not able to reproduce this today. Is this still an issue?
