### ISSUE TITLE
Broken theme mods option

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#32511]
## Description
When activating Anyone can register option from wordpress settings, theme_mods options goes broken on db.
It's i guess can be with FSE.

## Step-by-step reproduction instructions
1. Activate some FSE theme for example TT1 Blocks theme.
2. Go to General settings and activate Membership ( Anyone can register )

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/10712881/121180815-51416800-c872-11eb-8a03-41e6821c47cd.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.4

**Comment by Sandstromer** [comment]
I had a similar issue that may be related.

Was trying out a membership plugin in conjunction with a FSE theme and all was working good before 10.7.3.

After updating Gutenberg to 10.7.4 (not 100% sure whether the error appeared in 10.7.3 or 10.7.4 as they were released very close together) I got the `Warning: Illegal string offset 'custom_css_post_id' in ..\wp-includes\theme.php on line 1063` error.

Checking the _options_ table showed the _theme_mods_themeslug_ now had an _option_value_ of "-", so I deleted that row and it was automatically re-added correctly, and all was good again.

Think it might be something to do with #32229 but not sure exactly how.

**Comment by Sandstromer** [comment]
Just to add that all my another installations that did not have any membership plugins nor the 'Anyone can register' option selected, were okay after updating to 10.7.4

**Comment by aristath** [comment]
This was a bug in a couple previous versions and it was fixed. @Sandstromer is right, this was due to changes in the site-logo block. https://github.com/WordPress/gutenberg/pull/31994 is the PR that broke it,  #32229 is the PR that fixed the issue.

**Comment by Mamaduka** [comment]
I think we can close this issue.
