### ISSUE TITLE
Could we have Read more link as a stand alone block?

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#32529]
At the moment a "Read more" link is a part of the Post Excerpt block. The minimum length of Post Excerpt is 10 words, so it's not possible to create a "Read more" button or link that way. This is where I got the idea of a stand-alone Read more block, and I'd love to hear other people's opinions.

Here are some design ideas this would enable:

![image](https://user-images.githubusercontent.com/4550351/121279652-3e816e80-c918-11eb-8280-f3d5a7fa25f3.png)
Having a title and a Read more link or button is especially popular in a blog grid design.

![image](https://user-images.githubusercontent.com/4550351/121279911-b2bc1200-c918-11eb-9fe3-167fe6a86fa8.png)

**Comment by justintadlock** [comment]
I'd be open to this as long as we could still show the read more link as part of the excerpt too.  If the user selects "read more on a new line," it could generate an inner block for the excerpt.

**Comment by hollypryce** [comment]
I completely agree! A lot of the builds I work on require the "read more" link to be styled like this and a separate block would be very handy.

**Comment by alaczek** [comment]
Similar to #25450
