### ISSUE TITLE
Legacy widget preview iframe request is sometime cancelled by the browser

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#32523]
## Description
When we choose some options in our language legacy switcher legacy widget, its preview doesn't render anything because the preview iframe request is cancelled by the browser.

## Step-by-step reproduction instructions
1. Go to Appearance > Widgets
2. Open the browser developer toolbar on the network tab
3. Add only the language switcher legacy widget
4. Delete all the requests in the browser developer toolbar network tab
5. Check only the `Displays flags` option alone or `Hides languages with no translation`.
You can simply uncheck the `Displays language names` option which checks automatically the `Displays flags` option
6. See what happens on the `widgets.php?legacy-widget-preview....` request in the browser developer toolbar network tab
7. Click outside the language legacy widget to see what is previewed
8. See the legacy widget notice: `No preview available.`
9. Click right on the `widgets.php?legacy-widget-preview....` request in the browser developer toolbar network tab and choose `Open in new tab` on the contextual menu
10. See that the request return correctly the content result of the language switcher legacy widget

## Expected behaviour
Legacy widget preview have to be rendered regardless of the options choosen in the language switcher legacy widget.

## Actual behaviour
Preview doesn't work when:
- `Displays flags` option is checked alone
- `Hides languages with no translation` option is checked

## Screenshots
![image](https://user-images.githubusercontent.com/1003778/121228178-b609bc00-c88c-11eb-9b4b-1b9f21df355e.png)

![image](https://user-images.githubusercontent.com/1003778/121229142-e7cf5280-c88d-11eb-9c07-c4baef3d224a.png)

https://user-images.githubusercontent.com/1003778/121234293-d9843500-c893-11eb-8be5-e2b57360682f.mp4

## What's needed?
To reproduce the issue you need the Polylang plugin in its development version retrieved from our github repository master branch because this is, at the moment, the branch which is compatible with the new block-based widgets screen.

You can follow instructions from its [readme.md file](https://github.com/polylang/polylang#how-to-set-up-polylang) to install Polylang, make it ready and activate it on your WordPress environment.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: built from trunk because [this correction](https://github.com/WordPress/gutenberg/pull/32300) on legacy widget preview isn't reported in the latest v10.7.4
- Are all plugins except Gutenberg deactivated? No: Polylang dev branch is needed to be compatible with the block-based widgets screen and see the issue reported
- Are you using a default theme ? Yes: Twenty Twenty-One

Or

- WordPress version: ~~5.8-alpha-51081~~ 5.8-beta1-51132
- Gutenberg version: none installed
- Plugins: Polylang and WordPress Beta Tester
- Are you using a default theme ? Yes: Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91.0 or Firefox 89.0

**Comment by manooweb** [comment]
I complete the description of the issue above in the case that the language switcher legacy widget already exists before the new block-based widgets screeen.
It simulates a WordPress 5.8 update from an older version.

**NB:** with WordPress 5.8 [Classic Widgets plugin](https://wordpress.org/plugins/classic-widgets/) is needed and activated to be able to access to the old widgets screen. It must  be deactivated to be able to access to the new widgets screen.

## Step-by-step reproduction instructions
With WordPress 5.7.x and Gutenberg activated
1. Type wp-admin/widgets.php in the browser address bar
2. A the language switcher widget in a sidebar
3. Uncheck the `Displays language names` option which checks automatically the `Displays flags` option
4. Save the widget
5. Open the browser developer toolbar on the network tab
6. Filter the network tab view with `legacy-widget-preview` for example to only see the legacy widget iframe preview requests
7. Go to Appearance > Widgets
8. See the result in the network tab view
9. Two requests are triggered and their result don't correspond on the language switcher option checked and the legacy widget preview says that there is `No preview available.`
10. Click on the language switcher legacy widget to modify its options
11. See that only the `Displays flags` is checked
12. Uncheck the `Displays flags` to automatically check the `Displays language names` option
13. Verify the legacy widget iframe preview request result in the network tab view and the language switcher legacy widget preview in the widgets screen. It's ok 👍 Both of them are the same
14. Then Uncheck the `Displays language names` option which checks automatically the `Displays flags` option of the language switcher legacy widget
15. See the same result as described in the issue above: the legacy widget iframe preview request is cancelled by the browser and there is `No preview available.`  for the language switcher legacy widget

## Screen recording

https://user-images.githubusercontent.com/1003778/121330343-358f9d80-c916-11eb-9020-c2a31484df20.mp4

**Comment by noisysocks** [comment]
I tried testing this locally and didn't see any cancelled requests. Maybe something about the HTTP server in your dev environment is blocking the request? Just a guess: Maybe because the URL is too big? They're very large URLs which is a known issue.

https://user-images.githubusercontent.com/612155/121617080-871b6200-caa7-11eb-94a6-12f3a8df436e.mp4

I did see that the "No preview available." message shows which is unexpected. I suspect this is because when "Display flags" is checked there is no text in the output? The mechanism which detects whether there is a preview or not looks at the container element's `innerText` property which means that if there is no text then we assume there is no preview. I'll look at fixing this so that it treats `<img>` as content, too.

**Comment by noisysocks** [comment]
I've fixed the "No preview." mechanism in https://github.com/WordPress/gutenberg/pull/32605.

**Comment by manooweb** [comment]
@noisysocks Thanks for testing 👍

> I tried testing this locally and didn't see any cancelled requests. Maybe something about the HTTP server in your dev environment is blocking the request? Just a guess: Maybe because the URL is too big? They're very large URLs which is a known issue.

🤔 Even if I'm on Windows apache server, it's strange because it doesn't work only with some kind of previews. For all the other  it works correctly.
Thank you for the track I will look for on that way

Edit: I remember that my colleagues is on Linux Mint and have the issue too.
 
> I did see that the "No preview available." message shows which is unexpected. I suspect this is because when "Display flags" is checked there is no text in the output? The mechanism which detects whether there is a preview or not looks at the container element's `innerText` property which means that if there is no text then we assume there is no preview. I'll look at fixing this so that it treats `<img>` as content, too.

👍 Yes, our language switcher can output only `<img>` content with base64 encoded image.
Thanks you for the fix, I will test again.
