### ISSUE TITLE
RichText paste breaks with multiple pastes

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#32526]
## Description
When trying to paste into a rich text block like Paragraph, if multiple pastes are done in a row, or sometimes when content is deleted and new content pasted, a console error is thrown and the content of second paste does not appear in the editor.

## Step-by-step reproduction instructions

- In the editor try and paste some text into a paragraph block, and then paste the same text again
- The text does not appear in the editor and a console error is thrown

## Screenshots or screen recording (optional)
![paste-2-before](https://user-images.githubusercontent.com/3629020/121277550-f3ba2380-c924-11eb-9c2e-bab4e2066119.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: latest trunk
- Are all plugins except Gutenberg deactivated? Yes

## Device information
- Device:  Desktop
- Operating system:  OSX
- Browser: Chrome 91

**Comment by KokkieH** [comment]
@glendaviesnz On WordPress.com's end we've had a report of this [via Twitter](https://twitter.com/dreduphd/status/1404674709468364804) that mentions pasting with AppleScript also doesn't work. Do you think it might be the same issue, or something different? I'm afraid testing this is beyond my skillset - no idea how AppleScript works :D

**Comment by WunderBart** [comment]
Howdy! 👋 This seems to be partially fixed. Testing with https://github.com/WordPress/gutenberg/pull/32527 cherry-picked, I can only paste plain text into a new list item, but cannot paste if the text was copied from any other block. Here are the steps to reproduce the issue I'm seeing:

- Write something in a paragraph block
- Select & copy what you just wrote
- Hit enter and create a list block
- Paste & see that nothing got pasted and no error is being thrown in the JS console
- Now copy some other text, not from the editor canvas this time - can be the current page's URL 
- Paste and see that it's all good.

Seems to me that the List block is not accepting content from other blocks? Would that be the case here? Here's a recording of those steps:

https://user-images.githubusercontent.com/1451471/123830975-204dd380-d904-11eb-95d8-cd9c55e5b519.mov

Should we reopen this issue or create another one, @glendaviesnz? cc @fullofcaffeine @ockham

**Comment by ockham** [comment]
> Should we reopen this issue or create another one [...]?

Let's create a new one -- the issue you found seems a bit different from what's described in this issue's original description 🙂

**Comment by fullofcaffeine** [comment]
> > Should we reopen this issue or create another one [...]?
> 
> Let's create a new one -- the issue you found seems a bit different from what's described in this issue's original description slightly_smiling_face

Created the issue here: https://github.com/WordPress/gutenberg/issues/33078.
