### ISSUE TITLE
[Block-Library] - Sass: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by shawngrona** [WordPress/gutenberg#32533]
## Description
With Sass v 1.34.0+ we receive the error 

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($content-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

 ╷
 │         max-width: $content-width / 2;
 │                    ^^^^^^^^^^^^^^^^^^
 ╵
    node_modules/@wordpress/block-library/src/pullquote/style.scss 8:14  @import
    node_modules/@wordpress/block-library/src/style.scss 35:9            @import
```

## Step-by-step reproduction instructions
Compile the @wordpress/block-library with sass package 1.34.0+
[Bootstrap is experiencing similar issue](https://github.com/twbs/bootstrap/issues/34051) as are many other projects if you search for the warning text above.  Users is github threads report downgrading to sass package 1.32 removes the warning.  This is a future breaking change for sass for your package, in meantime its mostly annoying because there is no way to silence a sass warning.

## Expected behaviour
No warning

## Actual behaviour
Warning

**Comment by talldan** [comment]
Would have expected the package to have a major version bump, that seems like a big breaking change.

**Comment by nielslange** [comment]
@mkaz As you updated the sass version in https://github.com/WordPress/gutenberg/pull/33433, this issue is no longer relevant and can be closed, can't it?

**Comment by mkaz** [comment]
I'm not sure it is an issue. Yes, a warning is giving when using `/` for division in, but that is to be expected.
Is the error showing in a project outside of Gutenberg code? The instructions to fix are given in the warning either switch to `math.div()` or use multiplication ie. `$content-width / 2` === `$content-width * 0.5`

This is already updated in the Gutenberg source, here is the relevant[ pullquote/style.css line
](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/pullquote/style.scss#L17)

How did you come across the issue? Are you using older packages?
Could you try updating your package libraries and I think it will resolve it?

**Comment by nielslange** [comment]
@mkaz What I meant is, that I think this issue can be closed as it's no longer relevant. I would close it, if I would have the necessary permissions. As I don't have them, I pinged you.

**Comment by mkaz** [comment]
:+1: Great, thanks!
