### ISSUE TITLE
Navigation block collapses to the left when selected

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#32539]
Originally reported in https://github.com/Automattic/themes/issues/3975.

## Description
When selecting the Navigation block, all its contents collapse to the left. This is reproducible in Navigation blocks which are center or right-aligned.

_Navigation block unselected:_
![imatge](https://user-images.githubusercontent.com/3616980/121328991-180e0400-c915-11eb-9360-8cee65199244.png)

_Navigation block selected:_
![imatge](https://user-images.githubusercontent.com/3616980/121329040-22300280-c915-11eb-9caf-d6774fc0ec11.png)

## Step-by-step reproduction instructions
1. With Gutenberg enabled, install a block-based theme (ie: TT1 Blocks).
2. Go to the Site Editor and add a Navigation block outside of the header columns. You might add a custom background color so it's easier to see the block area.
3. Click on the block to select it.

## Expected behaviour
Contents should stay in their position when the block is selected.

## Actual behaviour
Contents collapse to the left even though they are right-aligned.

## WordPress information
- WordPress version: 5.8beta1
- Gutenberg version: 10.8.0-rc.1
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by jasmussen** [comment]
I have a fix in #32574. 

By the way which extension are you using that adds those red underlines @Aljullu?

**Comment by Aljullu** [comment]
> I have a fix in #32574.

Nice! I tested it and it's working great on my end.

> By the way which extension are you using that adds those red underlines @Aljullu?

I think that's the default Firefox spellchecker, for some reason it was set to a language different than English so everything was red. :red_circle:

**Comment by jasmussen** [comment]
> I think that's the default Firefox spellchecker, for some reason it was set to a language different than English so everything was red. 🔴

Cool, I'm just looking into [wavy underlines](https://codepen.io/joen/pen/mdWxjry), so I was curious :)

**Comment by jasmussen** [comment]
This should be fixed by #32574.
