### ISSUE TITLE
Add a "sharing" option for social media icons

### ISSUE THREAD

**Issue by Nic787** [WordPress/gutenberg#32549]
## What problem does this address?
It's currently possible to add social media icons on our webpage via the Gutenberg Block and links them to our social media page. But how can people really share the content on their page is unknown. I know there are some plugins that can add share icons all over the place, but since the social icons from Gutenberg are pretty and already built-in, why not just add a functionality to it?
![image](https://user-images.githubusercontent.com/11185348/121358339-8ac0b480-c900-11eb-9611-b4aa48a98999.png)

## What is your proposed solution?
Add a toggle to the block called: "Share icons" which transform those icons into shareable link. For example, if I click on Facebook icon, the popup to share the post on Facebook will appear and so on for each social media that can be shared to. I think that would be a great option to have. To make it more clear, it could also use this share icon as **::before** content 
![image](https://user-images.githubusercontent.com/11185348/121362189-ee001600-c903-11eb-8562-6f16353fd8f0.png)

Thank you

**Comment by mtias** [comment]
Thanks for the suggestion. Sharing can involve a lot more for each service than the display of the icon and URL, such as maintaining specific flows or additional scripts that are generally outside the scope of core and more into plugin territory.
