### ISSUE TITLE
Site Editor crashes when customPadding is enabled

### ISSUE THREAD

**Issue by sagarnasit** [WordPress/gutenberg#32545]
## Description
Site editor crashes when trying to open block styles for a group block. I also noticed that it is only happening when `customPadding` setting is enabled in theme.json. Not having this issue when `customPadding` setting is disabled.

This is happening for the group, cover, column, templatePart, and verse blocks.

## Step-by-step reproduction instructions
1. Install the latest Gutenberg and TT1-block theme.
2. Open site editor.
3. Try to click on the following blocks from `Global Style -> By Block Type -> Group` Block.

## Expected behaviour
The site editor should allow editing block style from the Global Style sidebar without breaking.

## Actual behaviour
The site editor is breaking when trying to update some blocks on the Global Style sidebar.

## Screenshots or screen recording (optional)

https://media.giphy.com/media/pvf1gRIX5PfCR9khX4/giphy.gif

## Code snippet (optional)
theme.json

```json
{
	"settings": {
		"spacing": {
			"customPadding": true,
		}
	}
}
```

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.4 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Mac OS Big Sur
- Browser: Chrome 91.0.4472.77

**Comment by Mamaduka** [comment]
Hello, @sagarnasit

I was able to reproduce the issue with version 10.7.4 but not with 10.8. I think this got fixed in the latest version.

**Comment by sagarnasit** [comment]
@Mamaduka Correct!

Updating the plugin to 10.8 solved the issue for me too. I'm closing the issue, Thanks! for checking.
