### ISSUE TITLE
Possibility to use vh and % for cover image height

### ISSUE THREAD

**Issue by Nic787** [WordPress/gutenberg#32546]
## What problem does this address?

Consistency of web design and responsiveness. Sometimes, you want the cover image to fit the full height of the page or 60-70% of it. It's much easier to do when using 70vh  than ___ px.

![image](https://user-images.githubusercontent.com/11185348/121357248-a4153100-c8ff-11eb-9f6b-2d7817e8f4b4.png)

## What is your proposed solution?

Have the possibility to select between px, vh and %.

Thank you

**Comment by stokesman** [comment]
The latest versions of Gutenberg allow this but I do believe the theme can influence the available units. This is a screenshot using Twenty Twenty One.
![image](https://user-images.githubusercontent.com/9000376/121411991-0e869b00-c919-11eb-9047-60b21b562e41.png)

There's also a button in the toolbar to quickly toggle `100vh`
![image](https://user-images.githubusercontent.com/9000376/121412335-7210c880-c919-11eb-8c86-0af1e662467c.png)

**Comment by Nic787** [comment]
Weird, because I have 5.7.2 and I use everything as default since I'm making my own theme.

**Comment by stokesman** [comment]
Looks like `vh` is not one of the default units. It can be added via [`add_theme_support`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#support-custom-units) or [`theme.json`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings)

**Comment by Nic787** [comment]
Ok thank you :)

**Comment by Nic787** [comment]
Hi, similar to this topic, I saw that there is a support for custom padding, but is there something for custom margin? Also, is there a support to justify text (but the last line could be centered or left)?

**Comment by stokesman** [comment]
Yes, for the custom margin though it's probably recent enough that you'll have to install the Gutenberg plugin. I don't know about the justifed/last-line text-alignment, but I don't think so.
