### ISSUE TITLE
Link control rich preview - improve image placeholder

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#32548]
## What problem does this address?

In https://github.com/WordPress/gutenberg/pull/31464 @javierarce mentioned the following...

Currently, if an image in the `<LinkContorl>` rich preview isn't available we show a placeholder. However, it may not be clear that this is a placeholder.

## What is your proposed solution?
To improve this we can add the URL to the placeholder as shown in this mockup

<img width="382" alt="Screenshot 2021-06-09 at 13 04 35" src="https://user-images.githubusercontent.com/444434/121360647-827e6e80-c92c-11eb-9d54-03876ee7de78.png">

https://www.figma.com/file/OXOmvYcX0Gpwgt7FB5LlKA/Rich-URL-metadata?node-id=152%3A0

**Comment by mtias** [comment]
@getdave @javierarce I'm also noticing that rendering a big placeholder for image and text is a bit annoying when the result cannot retrieve a preview, which seems to happen often. It seems it'd be better to only have a placeholder on the icon and then expand if there is image and description, instead of collapsing when there isn't, which seem odd.

**Comment by javierarce** [comment]
That was the initial idea, but there was an issue ([described here](https://github.com/WordPress/gutenberg/pull/31464#issuecomment-855827969)) where the popup moved suddenly when new content appeared.

**Comment by mtias** [comment]
Ah, I see! Now we have the jump in the other direction in some cases. We should look at addressing it in the popover. I don't when it'd be not disorienting to have a rendered popover reposition itself when its content updates if there's no resize / scroll.

**Comment by getdave** [comment]
I seem to recall that Popover is due a major refactor or replacement in the near future. Was there someone working on that? I can't quite recall. Perhaps @javierarce  or @jasmussen would know?

**Comment by mtias** [comment]
@diegohaz was looking into it

**Comment by getdave** [comment]
The placeholder now no longer appears if there is no image retrieved. See https://github.com/WordPress/gutenberg/issues/32547.

Closing.
