### ISSUE TITLE
Nested Reusable Blocks do not render on undo

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#32540]
## Description
After undoing an action nested reusable blocks do not render making it look like they have been deleted.

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Add a column block with a paragraph and reusable block
2. Make a change like adding a new paragraph block or delete an existing block
3. Click the undo button to reverse the change.

## Expected behaviour
The change to be reverted and the reusable block to continue to be rendered

## Actual behaviour
The change is reverted but the reusable block is not rendered/shown.

## Screen recording
https://user-images.githubusercontent.com/1785641/121334888-5f4ac380-c91a-11eb-9250-8dee754255ac.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.4
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: MacBook
- Operating system: macOS Big Sur 11.3.1
- Browser: Chrome 91.0.4472.77

**Comment by annezazu** [comment]
I'm no longer able to replicate this in 6.4 RC2. Closing out as a result!
