### ISSUE TITLE
"Insert block" can pop up over a link input, making it impossible to use the input

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#3255]
## Issue Overview

If you're making text a link and the link dialog pops up over where the insert block button is at the bottom of a block, the dialog is impossible to use.

## Steps to Reproduce (for bugs)

See attached gif, recorded in Chrome 61.

![peek 2017-10-31 11-33](https://user-images.githubusercontent.com/3314354/32222159-17f8a0c2-be30-11e7-8a9a-c10800a7e3d6.gif)

**Comment by mtias** [comment]
Seems like a simple z-index bug to fix.

**Comment by notnownikki** [comment]
PR is up :)
