### ISSUE TITLE
Put phone number under the Contact area

### ISSUE THREAD

**Issue by Levi-70** [WordPress/gutenberg#32559]
This is kind of a suggestion... 
phone number isn't really part of a shipping address (I know sometimes companies want a shipping number so i get that)
but I think it would make much more sense to put the phone number under the contact details (where the email address is) because that's what it is (contact details)

we use woocommerce subscriptions and we require a phone number and obviously email address to be able to contact people when subscriptions fail

**Comment by talldan** [comment]
@derher I'm not sure this is in the right place, do you mean to create this in one of the WooCommerce github repositories? (e.g. https://github.com/woocommerce/woocommerce)
