### ISSUE TITLE
Create a block equivalent of the Meta widget

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32551]
It was recently noticed in https://github.com/WordPress/wordpress-develop/pull/1331 that we don’t have a block equivalent of the classic Meta widget. This seems like a useful widget to have a block version of! 

![Screen Shot 2021-06-08 at 3 04 03 PM](https://user-images.githubusercontent.com/77359364/121368444-150d1680-c909-11eb-8864-74e740c3bba8.png)

Here’s an icon that could potentially work for this new block — it’s meant to reference a link tree and indicate the various locations that are quickly accessible from the Meta block. I prefer the sideways version (bottom) but any feedback is appreciated :)

<img width="436" alt="meta" src="https://user-images.githubusercontent.com/77359364/121368540-248c5f80-c909-11eb-8df9-ccaaa429a16c.png">

**Comment by mtias** [comment]
Curious if this is actually used much in practice these days.

**Comment by melchoyce** [comment]
Related: https://github.com/WordPress/gutenberg/issues/13335

**Comment by critterverse** [comment]
Closing this based on the previous discussion in #13335.
