### ISSUE TITLE
Letter Spacing Control for Site Title and Site Tagline is not visible in Sidebar

### ISSUE THREAD

**Issue by thisissandip** [WordPress/gutenberg#32577]
## Description
Letter Spacing Control for Site Title and Site Tagline is not visible in Inspector Control (Sidebar)

## Step-by-step reproduction instructions
1. Enable letter spacing in theme.json for site title and site tagline by following the steps in #31118 or use this [gist](https://gist.github.com/thisissandip/c4b2f359b5441572140507464b57b979) 
2. Add Site title and Site tagline blocks
3. See the letter-spacing control is not visible in the sidebar

## Expected behaviour
Letter Spacing control should be there in the sidebar

## Actual behaviour
 letter-spacing control is not visible in the sidebar

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/69596988/121481557-e024c080-c9e9-11eb-8e87-f503c9689854.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, I am using TT1.

## Device information
- Device: Desktop
- Operating system: MacOS Catalina 10.15.7
- Browser: Chrome  91.0

**Comment by aaronrobertshaw** [comment]
I noticed this while testing changes removing custom prefixes from theme.json properties that didn't need it.

~A fix is included in that PR: #34485~

Fixed in https://github.com/WordPress/gutenberg/pull/34515
