### ISSUE TITLE
Consider splitting out `wp-env` to its own repository

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#32584]
Currently, the Gutenberg project is a monolith of tools and features, one of these features is `wp-env`, a node module for managing, and working with, WordPress plugins and themes.

Given the nature of `wp-env`, it is a tool with a much borader reach and audience than the Gutenberg monorepo, and as such does not (in my opinion) properly fit in here.

By splitting it out to its own repo, it becomes easier for others to adopt, learn from, and hopefully contribute back to, the tool it self.

This would also make it easier for those looking to enhance it to fork the project, without getting a block editor along as a bonus, or jsut to implement changes ahead of releases based on localized needs there and then.

I will happily admit to not knowing the technical difficulties involved in moving NPM packages to a new repositor, but I honestly believe that not bundling this broad of a tool inside the Gutenberg repository will be a positive change.
There may be other such tools that I'm not familiar with, so perhaps it's a roader discussion of "separating tooling from code" in the Gutenberg repo? Would absolutely love thoughts and input on this.

**Comment by brylie** [comment]
Hei @Clorith. Please accept my apologies for opening a [duplicate issue](https://github.com/WordPress/gutenberg/issues/34325) to the one you opened here (I may not have searched for existing issues before opening the duplicate.) I'm not sure whether/how to merge these two issues.

In any case, the duplicate issue has somehow sparked some discussion around the idea of separating `wp-env` from the Gutenberg core development. :smiley:

**Comment by gziolo** [comment]
Let's close this one and continue in the one that got comments. I will copy the original description to the other issue. Thank you @Clorith for opening this issue.

**Comment by WraithKenny** [comment]
I love how you closed the one that wasn't in your favor.
