### ISSUE TITLE
Reusable block: Replace "Convert to regular blocks" icon

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32586]
## What problem does this address?

The following "Convert to regular blocks" icon does not convey the symbolic meaning of convert.
It looks more like an icon that will duplicate. 

<img width="678" alt="Screen Shot 2021-06-10 at 15 15 56" src="https://user-images.githubusercontent.com/5323259/121531649-ec674880-c9fe-11eb-822d-265230efba9e.png">

## What is your proposed solution?

We need to switch out the icon with another symbol that conveys the convert action, or perhaps instead add the word convert.

Suggestion 1. I did a search for a Convert icon and noticed this (somewhat similar to the plugin update icon though) I went ahead and added the icon to the toolbar (to just show another icon that portrays another meaning). It does need a totally new icon that gives a convert meaning.
![Reusable-block-convert-icon](https://user-images.githubusercontent.com/5323259/121533255-68ae5b80-ca00-11eb-9dea-5c19a59ae593.jpg)

Suggestion 2. Adding in the word "Convert" instead.

![Reusable-blocks-Convert-Text](https://user-images.githubusercontent.com/5323259/121533313-749a1d80-ca00-11eb-996d-3c00774afd11.jpg)

**Comment by malavvasita** [comment]
@paaljoachim How about this icon?

I have searched about the icons and I found this with correct meaning (I Guess).

![Convert to regular blocks](https://user-images.githubusercontent.com/25079043/121875111-b50dda00-cd25-11eb-9781-b8f58d28f3d1.jpg)

**Comment by paaljoachim** [comment]
Hi @malavvasita Malav

Yeah. Something like that conveys the conversion meaning. 
We will see what @keoshi Filipe can come up with as well..:)
Thank you for adding the suggestion!

**Comment by paaljoachim** [comment]
I went ahead and adjusted the icon in your suggestion, Malav.
It might be too detailed, but I am thinking about a more detailed visual going from one Reusable block and converting it back into (might be) multiple blocks. (It is not there yet.)


![Reusable-block-new-convert-icon](https://user-images.githubusercontent.com/5323259/122034802-2a36e900-cdd2-11eb-84cd-5cd2264c155a.jpg)

**Comment by paaljoachim** [comment]
I just asked in the Slack accessibility channel. Regarding icon vs text. I just needed some obvious feedback.
As text says right there what is being done. One does not need to guess. Having an icon that is not a common icon the user has to make a guess the meaning of the icon. In addition WP 5.6.2 a Reusable block toolbar looked like this:

<img width="345" alt="Screen Shot 2021-06-23 at 06 59 32" src="https://user-images.githubusercontent.com/5323259/123038547-e7d46400-d3f0-11eb-9363-3e1398bd487c.png">

I believe it might be most helpful if we just switched the current icon back to a word. 

Going from this:

<img width="356" alt="Screen Shot 2021-06-23 at 07 05 31" src="https://user-images.githubusercontent.com/5323259/123038899-81037a80-d3f1-11eb-815f-f690cc176bf2.png">


To:

![Convert-with-a-word](https://user-images.githubusercontent.com/5323259/123039598-b8265b80-d3f2-11eb-99c9-02996e70513b.jpg)


@jasmussen Any additional thoughts?

Thanks!

**Comment by jasmussen** [comment]
The icon here is intentional to make sure the block toolbar scales to mobile devices. German adds 20% of width to text labels, and when showing the title of the block we have to accommodate that. So it's an intentional tradeoff that converting the reusable block needs less prominence than the reusable block title. In light of separate discussions about locking the content and adding high friction to editing reusable blocks, the current balance seems right to me, even if we can continue to explore a better icon.

Also keep in mind we have this in the overflow menu:

<img width="301" alt="Screenshot 2021-06-23 at 08 46 34" src="https://user-images.githubusercontent.com/1204802/123049448-dba3d300-d3ff-11eb-9921-0614ece0615b.png">

**Comment by thesunshade** [comment]
> Also keep in mind we have this in the overflow menu:

FWIW, in the site I am testing one, I do not have the option "Convert to regular blocks" in my overflow menu. I only have the icon in the main toolbar. that people are discussing.

Also, FWIW, since I don't see the option in the overflow menu, and I assumed that the icon meant ```copy```, I thought that this feature had somehow been removed!

Personally _I don't see why converting to regular blocks is such a prominent thing in the tool bar._

**Comment by paaljoachim** [comment]
Hi @thesunshade 

> FWIW, in the site I am testing one, I do not have the option "Convert to regular blocks" in my overflow menu. I only have the icon in the main toolbar. that people are discussing.

The "Convert to regular blocks" in the overflow menu can be seen when activating the Gutenberg plugin.

> Also, FWIW, since I don't see the option in the overflow menu, and I assumed that the icon meant copy, I thought that this feature had somehow been removed!

The icon does look like a copy icon. Example searching for copy icon brings up this search: https://www.ecosia.org/images?q=copy%20icon

What we are hoping with this issue is to change the icon to something that would hopefully remind people about a conversion/convert process.

> Personally I don't see why converting to regular blocks is such a prominent thing in the tool bar.

It gives a quick reminder that one can convert a Reusable block into regular blocks. As modifying the Reusable block will affect all other instances/places the same Reusable block is used. Having the icon prominent in place in the toolbar will hopefully remind people that they need to convert to regular blocks before interacting with the Reusable block.

Thank you for your comments!

**Comment by jordesign** [comment]
Closing this issue as the interface is now changed - to use the 'Detach Pattern' terminology.

<img width="708" alt="Screenshot 2023-10-30 at 5 33 43 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/d6c02ce3-fd72-41ac-bc9c-6407ce8cae61">
