### ISSUE TITLE
Block Pattern Directory: Provide documented way to disable 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#32591]
## What problem does this address?

Similar to this issue related to the block plugin directory https://github.com/WordPress/gutenberg/issues/23961, there needs to be a documented and official way to disable the Block Pattern Directory. For example, an agency may not want clients adding in patterns, especially since they are theme agnostic. 

This is somewhat related to this PR https://github.com/WordPress/gutenberg/pull/31924

## What is your proposed solution?

I recommend offering a similar solution as documented for the Block Plugin directory so there is some consistency: https://developer.wordpress.org/block-editor/reference-guides/filters/editor-filters/#block-directory

If this is already in place and I missed it, apologies! I haven't seen this determined yet and would like to get it defined as people are inevitably going to ask.

cc @priethor @youknowriad

**Comment by priethor** [comment]
Thanks, @annezazu, this looks like something pretty important to get in place before 5.8.

**Comment by youknowriad** [comment]
There's already a way to disable `core` block patterns and AFAIK the patterns loaded from the Directory in 5.8 are only the ones considered "core", so I think we're good. cc @ryelle for confirmation though.

**Comment by annezazu** [comment]
Ah ha, got it. I made an assumption there that was wrong. Seems like this can be punted for 5.9 in that case :)

**Comment by ryelle** [comment]
I added a filter when this was merged into core, [`should_load_remote_block_patterns`](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/block-patterns.php#L64), assuming that people will want to disable remote calls. I didn't port it back to GB, but like @youknowriad said, removing support for the core patterns will also disable it.

**Comment by priethor** [comment]
Thanks for the reminder of such an important detail! Let's take this out of the 5.8 board and leave it open until the filter is backported.
