### ISSUE TITLE
Misaligned custom title in block toolbars

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32599]
Hi all, I spotted a small misalignment in toolbars that contain a custom block name. This is what I'm seeing currently, which causes a visual jump when moving from parent selector to parent toolbar:

![custom-name-trunk](https://user-images.githubusercontent.com/77359364/121601781-6950ed00-ca14-11eb-8ab9-178d9b945ae3.png)

^ Also looks like the Reusable block icon is being stretched horizontally.

This is how it should appear (with padding on the left and right side of the icon + title lockup):

![custom-name-expected](https://user-images.githubusercontent.com/77359364/121601447-f8113a00-ca13-11eb-9994-8ca910e6a9e4.png)

**Comment by WillPorter** [comment]
Starting on this!

**Comment by ghost** [comment]
Just checking in.  Found what I think is a good solution for this.  Still need to run through the testing protocol though.  Will be making a pull request possibly this weekend, but most likely early next week.  Thanks!

**Comment by WillPorter** [comment]
Just created a pull request!  I hope I followed all of the protocol correctly.  

Thanks and let me know!

**Comment by critterverse** [comment]
Awesome, thanks @WillPorter! Can you link to your PR? I'd be happy to test 😁

By the way, one cool thing I learned recently is that if you include "Fixes #32599" in the description of the PR, it will automatically link it to this issue and force the original issue to auto-close if the PR is merged (more info [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

**Comment by WillPorter** [comment]
https://github.com/WordPress/gutenberg/pull/32903

Thanks!

**Comment by jasmussen** [comment]
Hello friends, I almost feel bad that I may have fixed this issue inadvertently as part of a different effort to fix a misaligned focus style in https://github.com/WordPress/gutenberg/pull/33031#issuecomment-869628955. Can you let me know if that's fixed? And for anyone involved who'd like contribution props, please feel free to ping me on any of your PRs (@jasmussen) and I'll help shepard things along!

**Comment by critterverse** [comment]
Appreciate the fix @jasmussen, and I’m sorry for not spotting the overlapping issues either! It looks like #33031 definitely resolves the spacing issue 🎉

The secondary part of this issue had to do with the Reusable block icon being [stretched horizontally](https://github.com/WordPress/gutenberg/pull/32903#issuecomment-867122075) a bit — @jasmussen, I'm curious whether you are seeing that as well, or if it's just me noticing something that's always been that way? 😅

Happy to amend this issue to focus only on the block icon, or we can go ahead and close it if the icon is appearing as expected. Thanks all :)

**Comment by ghost** [comment]
Well, glad it was resolved!  Interesting css fix to the issue where I was adding a conditional class to the custom toolbar with text in JS.  Nice one @jasmussen !  Is there a way to get contribution props or would my commit actually need to be merged?  Not really sure how this works since this was my first PR.  No biggie if not, I'll try to address another issue soon.  Thanks all!

**Comment by jasmussen** [comment]
This PR itself is proof of your contribution. Even contributions that move things forward and explore, but ultimately don't get merged, count as valuable contributions. 

That said, if you have another PR I can help shepard along, I'd be happy to.
