### ISSUE TITLE
Widgets Screen: wp.editor.initialize is not a function notice

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#32598]
## Description

When loading the Widgets Screen two error notices appear at the top with the message:

`wp.editor.initialize is not a function`

![image](https://user-images.githubusercontent.com/45363/121601718-2a626d80-c9fb-11eb-921b-cdf4280d28b4.png)

## Step-by-step reproduction instructions

- WordPress 5.8-beta1
- No Gutenberg plugin
- Twenty Twenty One Theme
- Load Widgets Editor (no existing widgets)

**Comment by noisysocks** [comment]
I don't see this. Are you running 5.8 beta 1 from the published zip?

**Comment by Mamaduka** [comment]
I'm able to reproduce this using the 5.8 beta1 published zip and using "nightly."

WP CLI commands:
```
# Update WP with zip file
wp core update https://wordpress.org/wordpress-5.8-beta1.zip

#Update to nightly
wp core update --version=nightly
```

**Comment by noisysocks** [comment]
Thanks for testing. I can't repro when building and running from source. I wonder if it was a problem with the packaging process? There are new files added in 5.8, maybe one of them was missed when creating the .zip? cc. @desrosj @jeffpaul

**Comment by noisysocks** [comment]
@mkaz @Mamaduka: Are there any 404s in the Network tab of your dev tools?

**Comment by Mamaduka** [comment]
@noisysocks, I don't see any 404s.

**Comment by Mamaduka** [comment]
I think I was able to narrow down the issue. I had a legacy "Text" widget in one of the areas. If I remove it error notice disappears.

**Comment by mkaz** [comment]
I have no 404s in the Network tab, and had no existing active widgets initially, I added the social inks and it still shows. I do have several Inactive widgets, include a Text widget. The error goes away when I remove the Inactive widgets, looks like the Text widget might be the culprit.

![image](https://user-images.githubusercontent.com/45363/121700262-91783480-ca84-11eb-851d-4a11d5869380.png)

**Comment by noisysocks** [comment]
Thanks for the extra info. It sounds like we are not enqueueing the script assets that the Text widget needs. Probably this needs to be fixed in Core.

**Comment by noisysocks** [comment]
Moved to https://core.trac.wordpress.org/ticket/53437.
