### ISSUE TITLE
Padding and margin issues for columns and text + media blocks on tablet/mobile

### ISSUE THREAD

**Issue by Nic787** [WordPress/gutenberg#32595]
## Description

I don't know if it's a bug, but it's clearly a CSS issue of the block design.

When reaching the table or mobile breakpoint, the "blocks" don't have correct margin or padding to clearly see the separation of the content.

## Step-by-step reproduction instructions

**Columns**
I chose a 50/50 column and added the image on the right.

![image](https://user-images.githubusercontent.com/11185348/121587964-5c77cd80-ca03-11eb-85e3-8abae7769a9c.png)

The text on the right as a left margin of 20px. That is correct. However, when the columns resize, there is clearly a missing margin between the columns and that apply for all text collumns, image + text or the media + text block..

![image](https://user-images.githubusercontent.com/11185348/121588660-2dae2700-ca04-11eb-9408-d10e722a6dd5.png)

That's by default in Wordpress without any added styles.

**Text + Media**

About the same thing. But instead of using a margin, it's using a padding on the text. It may be good, but on mobile it looks ridiculous.

![image](https://user-images.githubusercontent.com/11185348/121589459-1459aa80-ca05-11eb-8ba4-8961eb7f962b.png)

## Expected behaviour

For column, there should be some margin to separate the different columns that are becoming rows on mobile.
For text + media, there should be a margin between the two elements and remove the padding of the text.

## Actual behaviour
Squeezed content.

## Screenshots or screen recording (optional)
All in the main paragraph

## WordPress information
WordPress 5.7.2
No plugins
Custom theme, but didn't touch any style related to those blocks.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Edge

**Comment by Nic787** [comment]
Here is a small fix for the columns block.

`.wp-block-columns{
justify-content: space-evenly;
gap:3em;
} 
.wp-block-column{ 
margin-left:auto !important; 
margin-right:auto !important; 
}`

Instead of using a left margin, it add a gap automatically. 
I think gap should also be used on the `.wp-block-media-text`.

Thank you

**Comment by carolinan** [comment]
I am not able to reproduce this. Columns now use a 2em gap style that was not implemented at the time this Issue was opened.
