### ISSUE TITLE
Quote: Consider removing base style from Style 1 from the frontend

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3259]
Virtually every WordPress theme provides styles for the `blockquote`.

The styles that Gutenberg provides, especially for quote style 1, can override these, causing some style conflicts. 

Gutenberg blocks should mostly provide styles, so themes have to do as little work as possible. But in the case of the quote, like many other very generic items like `hr` also, perhaps the default (style 1) version of the quote should let the theme do the styling?

We could also look into providing these styles only if the theme opts into it, using `add_theme_support`.

**Comment by rileybrook** [comment]
> We could also look into providing these styles only if the theme opts into it, using add_theme_support.

I think this is worth exploring, but maybe in the future. It could provide the best of both worlds (reducing probability of style conflicts, as well as providing a backup Gutenberg style option).
