### ISSUE TITLE
Query Block: Better default text when there are no results for query

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#32606]
## What problem does this address?

Currently when there are no results for a query - a generic 'No results found' message is shown. This could be improved to provide users with better direction on how to make sure there _are_ results.

This is particularly relevant if the query block is loaded when the user has _no_ published posts - the message appears as soon as the block is added with no indication of what to do about it.

<img width="1629" alt="Screen Shot 2021-06-11 at 1 38 13 pm" src="https://user-images.githubusercontent.com/1842363/121627589-01091680-cabb-11eb-8df2-7e26e587e7ee.png">

## What is your proposed solution?

It would be great if we could have better messaging for when there is no result to the query. Even better if we could make it contextual in some way. I'm sure we'd need some better wording - but something like:

**No published posst**
"You don't currently have any published posts to show here. You can add a new post, or try a different query"

**No results for specific query/filter**
"There are no results for that query. Try adjusting your filter settings"

---

As an example of this - we made some adjustments to the default text on some WordPress.com themes to say something similar.

<img width="571" alt="Screen Shot 2021-06-11 at 1 49 01 pm" src="https://user-images.githubusercontent.com/1842363/121628015-cc498f00-cabb-11eb-9ce4-345b02c60658.png">

**Comment by annezazu** [comment]
This came up in the seventh [call for testing for the FSE Outreach Program as well](https://make.wordpress.org/test/2021/05/26/fse-program-testing-call-7-polished-portfolios/#comment-1720):

> Query Block: Block outputs nothing on the frontend when there are no posts to show. Generally, it requires to show something that tells visitors that there are no posts or some custom message.

**Comment by carolynannewells** [comment]
Hello! Carolyn from Editorial here. Is the Query Block just for searching within your posts, or can you ask anything? Some suggested copy:


You have not added any posts yet. But please ask your query. 


No results were found for that query. Try adjusting your filter settings to search again.

**Comment by ntsekouras** [comment]
I haven't thought about it much yet but should we consider adding  a new no `results block` that could be added and be shown in front-end as well? 🤔

This would need some UX consideration as well, since we would need to be able to edit this block even if we have results from the current query.

**Comment by annezazu** [comment]
A new no results block has been implemented: https://github.com/WordPress/gutenberg/pull/38806 As a result, I'm going to close this out. Happy to reopen if there's an aspect of this issue not resolved by the recent work done here.
