### ISSUE TITLE
Embed Block: Slideshare Embeds don't play the final few slides

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#32603]
## Description
Slideshare embeds via the embed block and shortcode don't advance to their final  2-3 slides.

## Step-by-step reproduction instructions
1. Open a new page
2. Paste a slideshare link on a new line. Example: https://www.slideshare.net/BlogGrowth/how-to-build-your-brand-like-a-ppo
3. Preview or publish the page
4. Use the navigation arrows to advance to the next slide, going all the way to the final slide.
5. Observe that you cannot advance to the final few slides.

## Expected behavior
I expected to be able to navigate all the way to the end of the slideshow using the arrows.

## Actual behavior
I could not navigate through the final few slides.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/30727666/121612540-e83e3800-ca9d-11eb-8b5b-564075c8792c.mp4

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91

**Comment by JessixBlade** [comment]
Still waiting for updates on this for a user. Please advise once the issue has been resolved. Thank you!

**Comment by fwazeter** [comment]
@Mamaduka , @getsource and I tested [this in this slack triage](https://wordpress.slack.com/archives/C02QB2JS7/p1630388517113100). None of us were able to replicate the behavior.

Since the block is just returning HTML by the embed provider, likely this was a bug on Slideshare's end that was fixed since the time of posting. 

Closing the issue.
