### ISSUE TITLE
Allow changing URL on sidebar

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#32612]
When clicking on a Button block, the URL must be set from the quick tools bar, and the "rel" attribute from the side.

There is an inconsistency, since the "Open in new tab" checkbox appears both for the Quick tool and for the side bar.

To keep consistency, the URL itself should be changeable from the sidebar too.

**Comment by skorasaurus** [comment]
Hi, 

I can't find it at the moment, but I think there was discussion about removing open in new tab from the LinkControls (the interface that you describe) and only keeping it in the side bar. 


Additionally, [the sidebar is designed to house only more tertiary options; not critical options like adding a URL that are necessary for a block's use](https://developer.wordpress.org/block-editor/how-to-guides/designers/block-design/#the-settings-sidebar-should-only-be-used-for-advanced-tertiary-controls ). 

Admittedly, I've seen this rule ignored often in the real world usage/development of blocks, so I'll keep this open and let a more knowledgeable contributor give feedback.

**Comment by jordesign** [comment]
The 'Open in new tab' setting is no longer in the sidebar - so this behaviour is now consistent. If there's a desire to have additional controls (for both sidebar and 'open in new tab') that would be something separate to consider, so we could open a new issue.
