### ISSUE TITLE
Error messages are displayed in legacy widgets in 5.8beta1

### ISSUE THREAD

**Issue by piotrbak** [WordPress/gutenberg#32624]
## Description
When there's an error happening while block editor is loaded + debug log is enabled, we're displaying the error in each instance of legacy widgets.

## Step-by-step reproduction instructions
1. Enable debug log, set WP_DEBUG_DISPLAY to true
2. Install Imagify and Yoast
3. Make sure there are some legacy widgets
4. Go to the Widgets section
5. See errors present in each widget section

## Expected behaviour
Errors shouldn't be printed there

## Actual behaviour
Errors are being repeated in each instance of widgets, they're disappearing when clicking on the widget

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/26767037/121697643-29960e00-cac5-11eb-941a-9542961d666d.png)
https://jmp.sh/JzVG8SS

## WordPress information
- WordPress version: 5.8-beta1-51137
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome

**Comment by draganescu** [comment]
I tested this and it's as described. Just installing Imagify and Yoast (no configuration just activation) creates errors. If some plugin causes an error:

a) without `WP_DEBUG`

<img width="744" alt="Screen Shot 2021-06-16 at 12 08 50" src="https://user-images.githubusercontent.com/107534/122192031-f1fbdd00-ce9b-11eb-877d-fc81394bbdc3.png">

b) with `WP_DEBUG`

<img width="846" alt="Screen Shot 2021-06-16 at 12 09 57" src="https://user-images.githubusercontent.com/107534/122192005-edcfbf80-ce9b-11eb-8a75-bf1d122a9b2c.png">

I wonder what we should do though? The errors are legit. Should the rendering endpoing :hack: the errors out of the response?

**Comment by noisysocks** [comment]
I'm surprised to see that `get_current_screen` is undefined. Perhaps intercepting the iframe request in `init` is too early. We need to intercept the request before headers are sent but after most of WordPress has loaded.

https://github.com/WordPress/gutenberg/blob/f1f0cd7adceeecce546641dafdb2a1d0844f2bb2/packages/widgets/src/blocks/legacy-widget/index.php#L120

**Comment by adamziel** [comment]
`admin_init` perhaps? `get_current_screen` seems to be defined in `src/wp-admin/includes/screen.php` which is included in `wp-admin/includes/admin.php`; It seems like I need to upgrade my local setup to actually try this though as it seems to be going through core PHP files, not the ones in my Gutenberg plugin

**Comment by adamziel** [comment]
I proposed a fix in https://github.com/WordPress/gutenberg/pull/32854
