### ISSUE TITLE
Unfiltered user REST API requests

### ISSUE THREAD

**Issue by herregroen** [WordPress/gutenberg#32620]
## Description
There are two places where Gutenberg sends unfiltered requests for literally ALL users.

On large sites this can be hundreds of thousands of users and thus causes a noticeable load on your server for seemingly no use at all.

These happen in the latest posts block:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/latest-posts/edit.js#L53

And in the user autocompleter:
https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/autocompleters/user.js#L22

I can think of no reason why either of these would need to fetch literally every single user, which is what the REST controller does if the user making the request has the `list_users` permission.

## Step-by-step reproduction instructions
1. Create 10.000 users.
2. Be logged in as an admin.
3. Insert a latest posts block.
## Expected behaviour

I'd expect both these requests to be done with the `who=authors` parameter or alternatively the `getAuthors` selector.

## Actual behaviour
These requests keep on paginating for potentially hundreds of pages fetching every single user.

**Comment by aristath** [comment]
<details>
<summary>Details on how to replicate</summary>

I'm sure there's easier ways to create 10k users, but since I was not in a rush and working on other tickets at the same time I added this code in a new `mu-plugins/test.php` file

```php
add_action( 'admin_init', function() {
    for ( $i = 0; $i < 1000; $i++ ) {
        $id = time() . $i;
        wp_create_user( "u_$id", 'password', "$id@my-site.example" );
    }
} );
```
then went to my users page and just kept refreshing until I got to 10k users (takes a while for each pageload). 
</details>
 
After I got to 10k users, I created a new post and added a latest-posts block.
As soon as the block was added everything was fine, _but_ the authors list in the "Sorting & filtering" dropdown was empty and only got populated after half a minute.

Maybe instead of a dropdown we should have a textfield that searches users when someone starts typing? :thinking: 
This way on-load we wouldn't be making queries like this, and we'd only get users with a search query when needed.

**Comment by herregroen** [comment]
I think the real performance problems mainly start for those using multisite, that adds a join to the usermeta table for each query which includes a `LIKE` on the meta_value there. That part is mostly extremely expensive.

**Comment by aristath** [comment]
Makes sense... Multisite didn't even cross my mind. :+1: 
What do you think would be the best way to do this?
Adding `who=authors` may not be suitable... non-authors may be able to create posts for other post-types, or they may have authored 100 posts before being "demoted" and are no longer an author - in which case they should still be in the list :thinking:

**Comment by herregroen** [comment]
Unfortunately the REST API doesn't support the `has_published_posts` option. Filtering that into the allowed parameters would likely be the cleanest solution here.

Although turning it into an autocomplete dropdown that only searches when typing and always displays only a limited list of up to 25 or so results is probably the simplest.

**Comment by aristath** [comment]
I pushed a PR to fix the issue for the latest-posts block in #32662.
As for the user auto-complete, I believe that one only gets triggered when we type `@username` for mentions, so I don't think we need to (or should) change anything there :+1:

**Comment by Mamaduka** [comment]
I only see ten users returned by Users autocomplete.

@herregroen, is this behavior different on multisite? If yes, we can explicitly set `per_page` for that fetch request.

**Comment by herregroen** [comment]
> I only see ten users returned by Users autocomplete.
> 
> @herregroen, is this behavior different on multisite? If yes, we can explicitly set `per_page` for that fetch request.

Ah you're right. That one doesn't include a `per_page` at all so it gets the default 10 results that's set in the REST controller.

I mistakenly assumed it would have used the default -1 from WP_User_Query.
