### ISSUE TITLE
Keep only one widget area open at a time

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32632]
Maybe we should replicate the behavior in the customizer classic widgets panel on mobile and only allow one widget area open?

On small screens scrolling can be very daunting. Also accidental tapping makes the contents zoom in or new things appear on screen. While this is hard to mitigate all at once, it'd be a good idea to minimize the "risk" and effort and only expand one widget area at a time.

cc @critterverse

**Comment by noisysocks** [comment]
Wouldn't this make it hard to drag and drop between areas?

**Comment by draganescu** [comment]
Good point @noisysocks. It would simplify dropping in a widget area but it would hinder dropping in the actual place. I find this particula interaction to not work all right anyway in very long UIs, so I think it's a good tradeoff. 

The luxury idea would be to have two drop modes on collapsed widgets. Short drop (right after hover) places the item at the end of the list, but long hovers while dragging would open the widget area so you can pick the exact drop location.

**Comment by paaljoachim** [comment]
Let's do some comparison.

Old method using a Genesis theme that has a lot of widget areas:
(Using Refined Pro theme...Yeah the one that has an issue with the new Widget screen.)

![Screen Shot 2021-06-22 at 18 34 13](https://user-images.githubusercontent.com/5323259/122965511-90021280-d388-11eb-99e7-2a0c7c7db8a0.png)



Activating the Gutenberg plugin:

![Screen Shot 2021-06-22 at 18 34 50](https://user-images.githubusercontent.com/5323259/122965524-942e3000-d388-11eb-9fcb-e441713735b4.png)



Comparing old and new.
Old: has Widget areas side by side in a 2 column way. It is easier to get an overview. Multiple widget areas are open that shows which widgets are in which widget areas.
New: all are show below each other. I am noticing that it is not showing correctly, but that is another matter.

It would in general be helpful to have more than one widget area open at a time, as one could easier preview multiple widget areas at once and move widgets/block between widget areas. It is up to the user to open and close widget areas.

**Comment by noisysocks** [comment]
I believe we're more inclined to do the exact opposite of this. See https://github.com/WordPress/gutenberg/issues/32278. Let's continue discussion in that issue.
