### ISSUE TITLE
Box-control component considers 0 as null

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#32635]
It was a bit weird at first I tried to explain well:

1- Set 0 for all sides.
2- Close and open settings panel.
3- Now box-control shows nothing instead of that 0.
![1](https://user-images.githubusercontent.com/64708228/121739295-a6020e80-cb10-11eb-89d1-76671c1be24d.png)

When it is null instead of 0, that will make problems for developers who use these values for serverside or generate styles depend on that.

The object that is returned after change:
```js
Object { 
   top: "50px",
   right: null, 
   bottom: null,
   left: null
 }
```
![0](https://user-images.githubusercontent.com/64708228/121739357-bd40fc00-cb10-11eb-9aa8-eae53d576731.png)

but it should have 0 or '0px' instead of null:
```js
Object { 
   top: "50px",
   right: 0, 
   bottom: 0,
   left: 0
 }
```

Update:
For example consider that I need to generate `margin` if it returns null result will be:
`10px [null] 20px [null] => margin: 10px 20px;` instead of `margin: 10px  0 20px 0;`
Surely it breaks the code and for solving this I should check it, if it was null then return 0.
That's the reason I would rather it return 0 when is null.

**Comment by amir2mi** [comment]
I just updated the issue with an example of what I am struggling with.

**Comment by kathrynwp** [comment]
Hey there @amir2mi, belated thanks for this report! I tried to replicate the issue but so far haven't been able to, so it looks like perhaps this issue has already been fixed.

Here are my testing steps:

1. Add a 2-column Columns block to a post
2. Add a paragraph to each column
3. Select the Columns block
4. Open the Padding controls on the Columns block and set 0 for all values
5. Publish the post
6. Inspect the post on the front end

### Result

I see 0px for each side, as expected, both on the front end and in the editor:

![Self-hosted_Test](https://user-images.githubusercontent.com/7662449/188508530-417ff466-3334-4980-804e-5c0055c1a400.jpg)


![Edit_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/188508648-b2a0944a-f580-4a7e-a1f4-f39392e9a5d3.jpg)


![Edit_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/188508686-fb96711e-6a32-4cee-8163-471d55c1065f.jpg)


Please let me know if you're still experiencing the original issue, and if you are, detailed steps to replicate would be appreciated. Thank you!

### Tested with:

WordPress 6.0.1
No plugins active
Twenty Twenty-Two 1.2

**Comment by priethor** [comment]
This issue seems no longer reproducible, so let's close for now. Please feel free to reopen if the problem reappears.
