### ISSUE TITLE
On small screens the top toolbar has a black background on scroll

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32631]
Sometimes when scrolling the widgets editor the top bar becomes transparent.

### To reproduce

1. On an iPhone in Safari
2. Using Twenty Fourteen as a theme
3. Go to Appearance > Widgets
4. Make sure to add some blocks to be able to scroll the page
5. Scroll slowly
6. Notice the black top bar sometimes appears

### Expected behavior:

No change in the background of the top bar

### Screenshot

![image](https://user-images.githubusercontent.com/107534/121717731-324d0b00-caea-11eb-890e-a52fb057982f.png)

**Comment by talldan** [comment]
@draganescu Please could you add which browser and theme you used for testing? Thanks.

**Comment by draganescu** [comment]
Updated! On an iPhone in Safari. Let's see if I can remember the theme 🤦🏻‍♂️ 
Later edit: I did. It's Twenty Fourteen.

**Comment by getdave** [comment]
Confirmed I can still replicate on the iOS Simulator 


https://user-images.githubusercontent.com/444434/122207642-42723b00-ce9a-11eb-9d72-1a2cc7b4721b.mp4

I'll take a look into this one.
