### ISSUE TITLE
Template editor panel: Edit link not appearing for some templates

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#32646]
## Description
While attempting to complete Call 7: Polished Portfolios I encountered problems where some of the templates had an edit link  but others did not. It was not at all obvious why this should be the case. Perhaps the store only supports 10?

## Step-by-step reproduction instructions
Using TT1 blocks and Gutenberg 10.8.0

1. Add 4 new block-template files eg call-7.html, call-7-2.html, call-seven-three.html and call-seven-four.html
each containing the same content. eg.
```
<!-- wp:post-content {"layout":{"inherit":true}} /-->
```
2. Edit a post
3. Select the Template panel area
4. Links for **Default template** should show Edit and New
5. Click on the select list to get the drop down.
6. For each item in the list choose the item and see what links are available.
7. In my experience 404 will only show New.
8. For my system all templates up to call-7 display Edit and New.
9. For all templates from call-seven-four I only get New.

## Expected behaviour
Edit link should be available for all templates.

## Actual behaviour
Step 4.
![image](https://user-images.githubusercontent.com/2474435/121781533-279f7e00-cb9d-11eb-8e64-8641a51ba399.png)
Step 5.
Note: I've already added 3 templates: reproduce footer problem, empty and WordCamp Outreach
![image](https://user-images.githubusercontent.com/2474435/121781580-5584c280-cb9d-11eb-8b53-b090c141522b.png)
Step 7.
![image](https://user-images.githubusercontent.com/2474435/121781940-10fa2680-cb9f-11eb-96ee-0f34d34b5953.png)
Step 8.
![image](https://user-images.githubusercontent.com/2474435/121782149-14da7880-cba0-11eb-954e-c7166b582f93.png)
Step 9.
![image](https://user-images.githubusercontent.com/2474435/121782167-23289480-cba0-11eb-911e-29bb4c759067.png)

## WordPress information
- WordPress version: 5.7.2 
- Gutenberg version: 10.8.0 
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 blocks 

## Device information
- Device: Desktop 
- Operating system: Windows 10
- Browser: Version 91.0.4472.77

**Comment by jordesign** [comment]
As this was specific to TT1 and many changes have taken place with the Template Editing functionality - I'm going to close it for now. If this behaviour is observed again - it can be re-opened with additional details.
