### ISSUE TITLE
Jetpack Publicize missing from side panels

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#3264]
I have the Jetpack Publicize feature switched on but, at the moment, when editing a post with Guternberg, I don't have meta boxes available to me to edit this information - I end up resorting to switching to the standard editing mode just to set this up before publishing (I rarely publish without changing the publicize text).

With most of my other meta boxes now picked up in the latest Gutenberg releases, I was surprised to find this one missing, particularly as it's a Jetpack addition.

I'm running WordPress 4.8.2, Gutenberg 1.5.2.

**Comment by aduth** [comment]
Related: #1352 (Possible duplicate)

**Comment by dartiss** [comment]
Yeah, Publicize isn't specifically mentioned there as it's just a more general idea of how the screen should be configured. With the recent Gutenberg releases third party meta boxes, etc, have all appeared but Publicize is noticeably absent - I suspect it's because any changes to the primary meta box (the one in the standard editor with the publishing options in) have not yet been picked up in the new layout.

**Comment by BE-Webdesign** [comment]
Thank you for the report, this should be fixable.

**Comment by danielbachhuber** [comment]
Related https://github.com/Automattic/jetpack/issues/7766

**Comment by c-shultz** [comment]
This is primarily a Jetpack/Publicize issue. I suggest closing this in favor of this newly created issue in the Jetpack repo: https://github.com/Automattic/jetpack/issues/9039

**Comment by gziolo** [comment]
@c-shultz, it looks like the plan includes making pre and pot-publish screen extensible so it makes sense to keep this issue open to discuss technical details required on Gutenberg side to make it done.

**Comment by c-shultz** [comment]
Many thanks, @gziolo, for putting this list together! I'm going to nail the design approach down a little more with @MichaelArestad and then I'll get back to you on these.

**Comment by c-shultz** [comment]
@gziolo, I'm going to pursue making this work in the post-publish view. That's the most desired path for this based on the design mock-ups and discussion. There's a couple challenges to making that work (I'll make another post about that). If any of that falls through, putting this in pre-publish will be a good fallback.

For post-publish, #3321 that you mentioned looks like it would be close to what we need. I see that you closed that in favor of another approach? I wasn't clear on what that approach was. Let me know what you need from me.

Do you plan to develop the Gutenberg side to expose the right hooks? I'm up for learning whatever (just trying to get a feel for where it makes sense for my responsibility to fit in).

**Comment by c-shultz** [comment]
The other potential Gutenberg changed I described in a recent post in Automattic/jetpack#9039. The crux of it is that, for the post-publish flow, I need Publicize to know that a published post is coming from Gutenberg (as opposed to the Classic Editor, API, etc.). 

My current solution proposal is to route the publish action from Gutenberg through the Publicize plugin. I would like to create a REST endpoint in Publicize to handle publishing and extend Gutenberg such that posts are submitted to that endpoint. Do you think this is a feasible approach?

**Comment by gziolo** [comment]
Sharing an update. There was new API introduced for Plugins which seems to be the preferred way to add all UI based extensions. See: https://github.com/WordPress/gutenberg/blob/master/plugins/README.md#plugins-api. I would recommend checking it and explore if it could be also used for the post-publish screen.

**Comment by c-shultz** [comment]
Thanks, @gziolo! I'll explore this over the weekend. I don't yet see any reason that this wouldn't work for what I need.

**Comment by gziolo** [comment]
It is now possible to implement with API introduced in #6798.

**Comment by boblmartens** [comment]
Any news on this?

**Comment by jbusuttil** [comment]
The original bug report was that the publicize controls from the Classic editor were absent from Gutenberg, notably the ability to edit the text of what would be published to connected social media accounts.

The bug has been marked 'done' because the API now permits the missing features to be added.

However, the original intent of the bug report has been lost as the publicize features remain absent from Gutenberg.

Can this report be reopened, or a new one filed to restore the missing publicize features, please?
