### ISSUE TITLE
word break options for paragraph

### ISSUE THREAD

**Issue by idpokute** [WordPress/gutenberg#32640]
## What problem does this address?

Some languages such as Japanese don't use space between words, So the long sentence in paragraph block mostly overflows the container. I often use additional class or inline-styling, and it works on frontend.  However it doesn't fix the block in editor. 

## What is your proposed solution?

It would be better have the word-break option.

**Comment by talldan** [comment]
@idpokute Is this the same thing being discussed in #11956? If so, would it be ok to close this as a duplicate?

I think the solution in that issue is still a little unclear, so input is welcome.

**Comment by idpokute** [comment]
@talldan Thank you.
