### ISSUE TITLE
The media library looks broken on mobile

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32660]
While testing the new Widgets editor I found that browsing the media library while using a small screen device is unuseable. Initially I thought that it's a problem of the Wdgets editor. However the bug exists in the post editor as well.

### To reproduce

1. Using latest Gutenberg trunk
2. On a mobile device with a small screen (phone)
3. Create a new post
4. Add an image block
5. Click the "media library" button
6. The contents of the media library are unusable: images are small, on one column, cannot scroll

### Screenshot

![image](https://user-images.githubusercontent.com/107534/121881790-6148c400-cd18-11eb-8b33-288dd6e6324f.png)

### Expected behavior

I expect the modal media library to function on small screens similar to how the WP admin screen at  Media > Library functions.

**Comment by adamziel** [comment]
This seems to be a core issue so I prepared a core PR: https://github.com/WordPress/wordpress-develop/pull/1502

Let's continue in https://core.trac.wordpress.org/ticket/53679#comment:2
