### ISSUE TITLE
Make dropping the widgets into an empty sidebar easier

### ISSUE THREAD

**Issue by piotrbak** [WordPress/gutenberg#32669]
## What problem does this address?
When trying to drop a widget to not empty sidebar, the nice blue line is displayed that's showing the place where we could drop the widget. When the sidebar doesn't contain any widget so far, the line is not displayed and it might be hard to drop the widget in a correct place. Here's the video related to this problem:
https://www.loom.com/share/a2c82947946542188f9c82f4a79707b7

## What is your proposed solution?
It would be good to display a blue line also in that case, or allow dropping the widgets on the whole sidebar area, not only on a small part of it.

**Comment by Mamaduka** [comment]
Hi, @piotrbak

Saw this issue earlier today, #32652. Do you think they're related?

**Comment by chad1008** [comment]
It does look like theres some UI feedback when dragging, a small green **+** symbol appears on the cursor. It does have a very narrow area where that activates on an empty widget area though.

![Screen Capture on 2021-06-15 at 14-34-13](https://user-images.githubusercontent.com/13856531/122105730-1cd82980-cde7-11eb-84f5-8883fb4d1163.gif)


That sweet spot being so small makes it easy to miss, and the fact that a widget area will react to a hover by expanding makes it unclear when it's safe to drop the block effectively.

**Comment by noisysocks** [comment]
Thanks for the report! I'm going to close this in favour of https://github.com/WordPress/gutenberg/issues/32652 as fixing that should fix this.
