### ISSUE TITLE
Migrate old typography shape warnings on WP version older than 5.8

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#32670]
## Description
Currently, typography migration warnings are displayed/logged when using the Gutenberg plugin with WP version 5.7.2 or lower.

I think this happens because warnings are triggered before Gutenberg reregisters core blocks.

Example warning:
```log
PHP Warning:  Block core/code is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize.
```

## Step-by-step reproduction instructions
1. Install Gutenberg version 10.8 or later on WP 5.7.x
2. Enabled [debug mode](https://wordpress.org/support/article/debugging-in-wordpress/#example-wp-config-php-for-debugging).
3. See warnings logged in the `debug.log` file or displayed on the screen.

## Expected behaviour
It shouldn't display a warning since the plugin uses the correct supports shape for typography.

## Actual behaviour
Warnings are displayed.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by justintadlock** [comment]
Related: https://github.com/WordPress/gutenberg/issues/32600

**Comment by Mamaduka** [comment]
I can think of two options to resolve these notices.

1. Skip old typography shape migration for core blocks.
2. Add this filter after the Gutenberg plugin reregisters core blocks.

The second options are a little tricky. We're re-registering the block on the default `init` priority and might be too late to catch the issue in third-party blocks.

/cc @nosolosw
