### ISSUE TITLE
Query Pagination center alignment is not working

### ISSUE THREAD

**Issue by sagarnasit** [WordPress/gutenberg#32678]
## Description
Query Pagination block alignment center is not working expectedly. Previous/Next or Numbered paginations should be centered.

## Step-by-step reproduction instructions
1. Add query block with `inherit default layout` set to off.
1. Add pagination block and update alignment to center from toolbar.

![image](https://user-images.githubusercontent.com/25276905/121952416-d00a3980-cd79-11eb-8bed-0e98a4f3c3dd.png)

## Expected behaviour
Previous, Next, numbered pagination blocks inside the Query Pagination page display in the center.

## Actual behaviour
Previous, Next, numbered pagination blocks inside the Query Pagination display in the left as it is.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, I'm using TT1 block theme

## Device information
- Device: "Desktop"
- Operating system: Mac OS Big Sur
- Browser: 91.0.4472.77

**Comment by stacimc** [comment]
Confirmed I'm able to reproduce this using the testing instructions.
