### ISSUE TITLE
Improvement : use image in block preview area

### ISSUE THREAD

**Issue by mdrick** [WordPress/gutenberg#32672]
Hi to the Gutenberg developer community,

Regarding Gutenberg improvements, to give the possibility to add an image instead of the preview of a block ?

<img width="692" alt="Capture d’écran 2021-06-14 à 18 07 27" src="https://user-images.githubusercontent.com/17281519/121927804-c2d05900-cd3f-11eb-9212-ab9f0b994202.png">

Why does `example` property don't offer this simply? I tried to use `cover` property without success. There no simply way to do this? 

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#example-optional

```
    registerBlockType( 'ccn/gut-text-title', {
    	apiVersion: 2,
    	title: __( 'Titre', 'ccn-gut' ),
    	category: 'text',
    	icon: blockIcons.text_title,
        keywords: [ __( 'titre', 'ccn-gut' ) ],
    	example: {
    		attributes: {
    			cover: 'https://image.shutterstock.com/image-vector/example-sign-paper-origami-speech-260nw-1164503347.jpg',
    		},
    	},
    	edit: Edit,
    	save,
    } )
```

Have a good day

**Comment by talldan** [comment]
> Regarding Gutenberg improvements, to give the possibility to add an image instead of the preview of a block ?

There are other factors that can affect the block appearance in the preview, like the specified theme and block styles, so a static image wouldn't be sufficient for the preview.
