### ISSUE TITLE
Links from Card component to sub-components and vice-versa return 404 error.

### ISSUE THREAD

**Issue by TremiDkhar** [WordPress/gutenberg#32688]
## Description

- All the links Card in the [Sub-Components](https://developer.wordpress.org/block-editor/reference-guides/components/card/#sub-components) section are broken.

- The `<Card />` in the [CardBody](https://developer.wordpress.org/block-editor/reference-guides/components/card-body/), [CardDivider](https://developer.wordpress.org/block-editor/reference-guides/components/card-divider/), [CardFooter](https://developer.wordpress.org/block-editor/reference-guides/components/card-footer/), [CardHeader](https://developer.wordpress.org/block-editor/reference-guides/components/card-header/) and [CardMedia](https://developer.wordpress.org/block-editor/reference-guides/components/card-media/) should link to the [Card component page](https://developer.wordpress.org/block-editor/reference-guides/components/card).

- The `<Card />'s Context` in the [CardBody](https://developer.wordpress.org/block-editor/reference-guides/components/card-body/#size), [CardFooter](https://developer.wordpress.org/block-editor/reference-guides/components/card-footer/#size) and [CardHeader](https://developer.wordpress.org/block-editor/reference-guides/components/card-header/#size) size section should link to the [Card context section](https://developer.wordpress.org/block-editor/reference-guides/components/card/#context).

- The `<Flex />` in the [CardFooter](https://developer.wordpress.org/block-editor/reference-guides/components/card-footer/#flex) and [CardHeader](https://developer.wordpress.org/block-editor/reference-guides/components/card-header/#flex) flex section should link to the [Flex Component page](https://developer.wordpress.org/block-editor/reference-guides/components/flex/).

**Comment by hsingyuc** [comment]
I'll push a PR shortly.

**Comment by skorasaurus** [comment]
Thanks for reporting; since the issue was made; there were significant changes made to the Card Component in https://github.com/WordPress/gutenberg/pull/32566 and those broken links have been fixed.
