### ISSUE TITLE
Query block: Notice thrown if template includes post content.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#32681]
## Description
Including the post content block within a query block will cause a notice to be thrown both within the block editor and when the post containing the query block is viewed on the front end.

The notice is approximately 100K per post (so 500K with five posts, etc).

I've taken the liberty of labeling this a blocker as I pretty quickly worked up a 17MB log file when I first noticed this with a 5 post query block (500K logged per page load, post opened, post save).

## Step-by-step reproduction instructions

1. Enable debug mode with logging:
   ```
   define( 'WP_DEBUG', true );
   define( 'WP_DEBUG_LOG', true );
   define( 'WP_DEBUG_DISPLAY', false );
   define( 'SCRIPT_DEBUG', true );
   ```
1. Create a new post
1. Insert a query block (simple list view with title and excerpt)
1. Edit the query block template
1. Add a post content block to the template
1. Save post as draft
1. Observe notice in `wp-content/debug.log`.
1. Publish post (this will trigger another notice)
1. View post on the front end of the site (this will trigger another notice)
1. Change debug settings to display errors: `define( 'WP_DEBUG_DISPLAY', true );`
1. Reload page.
1. Observe notice on screen

## Expected behaviour

Without plugins, core is expected to run without throwing notices.

## Actual behaviour

100K of notices thrown per post in query block.

## WordPress information
- WordPress version: trunk@r51148 (https://github.com/WordPress/wordpress-develop/tree/15c8c705bc01015fd8fe3914e5e9b655985647e0)
- Gutenberg version: trunk, also happens without GB activated
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: Laptop
- Operating system: macOS 11.4 (Big Sur)
- Browser: Firefox Developers Edition 90.0b7

**Comment by youknowriad** [comment]
Do you happen to have the message of the notice?

cc @ntsekouras

**Comment by Mamaduka** [comment]
This is the notice I saw when I tried to reproduce the issue.

I can see a lot of notices, but nothing close to 100K.

```
PHP Notice:  Trying to access array offset on value of type null in /Users/mamaduka/Projects/gutenberg/wp-includes/class-wp-query.php on line 3300
PHP Warning:  Could not render Post Content block with post ID: <code>673</code>. Block cannot be rendered inside itself. in /Users/mamaduka/Projects/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/post-content.php on line 33
```

**Comment by peterwilsoncc** [comment]
Log files attached:

Opening the post with the query block > content [editor-open.log](https://github.com/WordPress/gutenberg/files/6659060/editor-open.log)
Saving the post with the query block > content [editor-save.log](https://github.com/WordPress/gutenberg/files/6659061/editor-save.log)
Visiting the post containing the query block: [visit-front-end.log](https://github.com/WordPress/gutenberg/files/6659062/visit-front-end.log)

My environment is configured to use xdebug, so you'll need to include that when starting `wp-env` to get the full stack trace. https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#using-xdebug

**Comment by ntsekouras** [comment]
>Could not render Post Content block with post ID: <code>4</code>. Block cannot be rendered inside itself.

The errors/warnings you're getting are in the case where you have a `Query Loop` with `Post Content` block, and the results also contain the current post. This can lead to an infinite loop trying to load the same dynamic content.

The specific message which is also shown to the editor is a sign about what the user is trying to do, which is not correct, and should be handled by the user, for example by excluding the same post with `offset` or some filter.

Similar case and handling is for Reusable blocks and Template Parts, that if tried to insert themselves as a child, would cause an infinite loop.

**Comment by mcsf** [comment]
It would be good to identify the cause of such a high volume of notices in @peterwilsoncc's report, in case that's a red flag for something else.

In my testing with a post containing a Query Loop block whose query encompasses the post itself, I see just **1** warning upon rendering the front end, and **2** upon loading the editor for that post.

**Comment by peterwilsoncc** [comment]
> The errors/warnings you're getting are in the case where you have a `Query Loop` with `Post Content` block, and the results also contain the current post. This can lead to an infinite loop trying to load the same dynamic content.

I'm seeing this happen when the post I am editing is in `draft`, so it doesn't include the post being queried. It also happens when I click the preview button. It doesn't happen when I reload the page.

![log](https://user-images.githubusercontent.com/519727/122305509-5e351a00-cf4a-11eb-872f-f0924b14bfe7.gif)

Even when the post is published, I think this is something we ought to handle as an author may wish to include the latest five posts in a post, so having the offset will work if the post in question is the latest but will throw a notice when they publish a subsequent post.

How about this: the query block never shows the post it is included in (design decision: is this always the case, or only when it includes the content).

The `post__not_in` option in `WP_Query` produces some really [badly performing database queries](https://docs.wpvip.com/technical-references/code-quality-and-best-practices/using-post__not_in/), so is best avoided.

The best approach would be to request n+1 posts and skip the current post in the PHP loop. You'd probably need to include a few smarts to account for pagination in this case.

**Comment by ntsekouras** [comment]
>How about this: the query block never shows the post it is included in (design decision: is this always the case, or only when it includes the content).

This would be definitely good but is way more complex to probably land in 5.8. I've created a PR that handles some extra warnings that can be avoided. 

In my testing though the logs weren't so huge like you describe here `100K`.. I have videos in the PR with the logs produced.

**Comment by peterwilsoncc** [comment]
> In my testing though the logs weren't so huge like you describe here `100K`.. I have videos in the PR with the logs produced.

It may be a custom handler that includes the stack trace then. I'll check up on php config options to see if this is coming from a standard config or xdebug is helping. 

I'll take a look at the pull request now.
