### ISSUE TITLE
Disable or tweak Columns Black Variations

### ISSUE THREAD

**Issue by LeoSeyers** [WordPress/gutenberg#32698]
Hello,

## What problem does this address?

As both designer and developer, I create and follow design specs that I expect to be followed by editors
In most themes I developed these days I let editors use the Columns Block but I'm frustrated cause I only want them to use the 50/50 variations for instance.

From an UX editor point of view, it's annoying to have options when they're actually not supported in the theme style and not expected from the design specs as well.

## What is your proposed solution?

Here are few options that could really smooth the dev process / design system integration :
– Be able to disable the variations directly from the now experimental `theme.json` (❤)
– Use a PHP filter (e.g current way to disable drop cap, $editor_settings['__experimentalFeatures']['defaults']['variations']['one-column-full'] = false;)
– ~~Use a JS method similar to unregisterBlockStyle ( e.g. wp.blocks.unregisterBlockVariations('core/columns', 'one-column-full');)~~
See @chthonic-ds answer's, wp.blocks.unregisterBlockVariation('core/columns', 'one-column-full')

**Comment by chthonic-ds** [comment]
Your JS option already exists, try `wp.blocks.unregisterBlockVariation('core/columns', 'variation-slug')`.

**Comment by LeoSeyers** [comment]
> Your JS option already exists, try `wp.blocks.unregisterBlockVariation('core/columns', 'variation-slug')`.

Oh my! I've been looking for this extensively. Thank you!
