### ISSUE TITLE
In 5.8, files loaded in the footer using wp_enqueue_script are loaded in the widget

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#32695]
The script that is loaded in the footer by setting the 5th argument of `wp_enqueue_script()` to `true` is loaded in the `iframe` of the widget block.

I understand this specification, but is there any way to determine that it is a widget and control the loading?

## WordPress information
- WordPress version: 5.8 beta1

**Comment by noisysocks** [comment]
Hi @ddryo. Does checking the `IFRAME_REQUEST` constant help in this case? Or how about checking for the presence of `$_GET['legacy-widget-preview']`? Alternatively we could look at adding a new constant e.g. `WIDGET_PREVIEW`.

https://github.com/WordPress/gutenberg/blob/f1f0cd7adceeecce546641dafdb2a1d0844f2bb2/packages/widgets/src/blocks/legacy-widget/index.php#L80

**Comment by ddryo** [comment]
@noisysocks 
Thank you! I'll check it out later!
