### ISSUE TITLE
Reusable block: Convert to regular blocks actions stops working after undoing a reusable block to regular blocks

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#32699]
## Description

Convert to regular blocks action doesn't work if the reusable block was already converted and the action was undone.

**Potentially related to issue https://github.com/WordPress/gutenberg/issues/28519.**

## Step-by-step reproduction instructions

1. Add a reusable block to a post/page
2. Tap on the three dots button to display the block actions menu
3. Tap on "Convert to regular blocks"
4. Observe that the block is converted to regular blocks 
5. Undo the action (this might require undoing multiple times)
6. Tap on the block and observe that is a reusable block
7. Tap on the three dots button to display the block actions menu
8. Tap on "Convert to regular blocks"
9. Observe that the block is not converted

## Expected behaviour

The reusable block should be converted to regular blocks.

## Actual behaviour

The reusable block is not converted to regular blocks.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/122074902-e6f07080-cdf9-11eb-9b1e-47c3e63200f6.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: `develop`

**Comment by fluiddot** [comment]
As far as I investigated, looks like the issue is caused by the memoization of the selector `getBlock`.

The selector is [memoized using a cache object](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/block-editor/src/store/selectors.js#L158-L165) that contains a list of client ids, each one with an empty object that is updated when there has been any change in the block, this way the next call to the selector will calculate a new value.

The problem begins after converting the reusable block to regular blocks:
1. After the conversion, the [cache reducer (triggered by `REPLACE_BLOCKS_AUGMENTED_WITH_CHILDREN` action)](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/block-editor/src/store/reducer.js#L310-L322) removes the reusable block client id from the cache.
2. At the same time, [`getBlock` is called](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/block-editor/src/store/selectors.js#L143-L166) with the recently converted and removed reusable block client id, since the block no longer exists this produces that the selector memoizes the value `undefined` for that block with an undefined cache key.
3. When the undo action is executed, the [cache reducer (triggered by `INSERT_BLOCKS` action)](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/block-editor/src/store/reducer.js#L278-L293) gets updated but doesn't include the client id of the reusable block due to [this condition](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/block-editor/src/store/reducer.js#L282) related to the controlled inner blocks. This means that the cache key for that block will still be `undefined`.
4. When trying to convert again the reusable block, the [conversion action](https://github.com/WordPress/gutenberg/blob/a1eac43ce47852fdf0d92187f8d6de79a3dc5e0d/packages/reusable-blocks/src/store/controls.js#L66-L88) calls `getBlock` with the reusable block client id and returns `undefined` (because the value was memoized previously) and therefore the action fails because it tries to access to an undefined object.

**Comment by Mamaduka** [comment]
The issue looks to be resolved now (at least on desktop) - https://github.com/WordPress/gutenberg/issues/28519#issuecomment-1097907161.

**Comment by fluiddot** [comment]
> The issue looks to be resolved now (at least on desktop) - [#28519 (comment)](https://github.com/WordPress/gutenberg/issues/28519#issuecomment-1097907161).

I've just tested using the latest changes from `trunk` and I confirm that this issue is already resolved 🎊.

Thanks @Mamaduka for the heads up 🙇.
