### ISSUE TITLE
[Widgets Screen] Unable to Update to Save

### ISSUE THREAD

**Issue by azollafox** [WordPress/gutenberg#32705]
## Description
When editing the Widget area under Appearance> Widgets changes can't be saved. An error message appears when you try
![Screen Capture on 2021-06-15 at 14-21-13](https://user-images.githubusercontent.com/7907292/122104156-5e67d500-cde5-11eb-81f1-47ceeecd210e.gif)

## Step-by-step reproduction instructions
1. Follow guide to enable Widget Editor
2. Click to Appearance> Customize
3. Edit or add widgets

## Expected behaviour
I expected that clicking update would make the widget changes save

**Comment by draganescu** [comment]
From the screenshot this also appears to be a WordPress.com related issue. Testing using WordPress Core and latest Gutenberg I could not reproduce this. Closing for now but feel free to reopen if the problem ends up being core related.
