### ISSUE TITLE
[Widgets Screen] Double "Move to" icons display on all widget areas

### ISSUE THREAD

**Issue by msilbers** [WordPress/gutenberg#32704]
## Description
When testing the Widgets Screen/widgets editor, I see two "move to" icons for each Widget.

## Step-by-step reproduction instructions
1. Activate the widgets editor
2. Navigate to wp-admin > Appearance > Widgets
3. Click any widget

## Expected behaviour
For one icon to display

## Actual behaviour

<img width="340" alt="Screen Shot 2021-06-15 at 2 14 42 PM" src="https://user-images.githubusercontent.com/31680407/122103211-5c514680-cde4-11eb-9f82-80a8a1cfd511.png">

## WordPress information
- WordPress version: tested on WordPress.com site without plugins
- Are all plugins except Gutenberg deactivated? No plugins installed/yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty One

**Comment by Mamaduka** [comment]
Thanks for reporting the issue.

I'm not able to reproduce it on the latest version of the Gutenberg plugin. But I found similar issue #32191, and it looks like this is WordPress.com related.
