### ISSUE TITLE
Widget Blocks: Customizer live preview does not load CSS/JS for a block

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#32706]
## Description
The live preview API in the customizer does not pay attention to newly enqueued scripts and styles. When you add a block to a widget area, the live preview pane in the customizer will not load any frontend CSS or JS for that block. This means the block will render incorrectly. Only when you save and reload the customizer will they be enqued correctly. Here is an example using the image compare block in Jetpack:

![2021-06-08 11 31 16](https://user-images.githubusercontent.com/1464705/122104253-56e80200-cdcc-11eb-8dd5-a89045e15460.gif)

## Step-by-step reproduction instructions

1. Open the customizer with a theme that has widget areas
2. Add a block to the widget area that has front end CSS or JS that needs to load (Image compare in Jetpack is an example)
3. Notice that in the preview pane the block is broken
4. Save/publish the changes
5. Reload the customizer, and notice that the block is now rendering correctly in the preview panel.

## Expected behaviour
That the block renders correctly without the need to reload the whole customizer.

## Actual behaviour
The block is rendered without CSS and JS and looks broken.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? No (Jetpack also active).
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Mac OS
- Browser: Chrome latest.

**Comment by draganescu** [comment]
Using the latest WordPress trunk and Gutenberg trunk I could not reproduce this. Here is a video:


https://user-images.githubusercontent.com/107534/122207611-fda2d000-ceaa-11eb-8465-232d7b20a9b2.mp4
