### ISSUE TITLE
Gutenberg and Gutentor

### ISSUE THREAD

**Issue by augustoleder** [WordPress/gutenberg#32716]
I use the Gutentor and Gutenberg to build my pages.
When I use the Container block, I click on advanced and later on backgroud and color, an error appears.

"This block has encountered an error and cannot be viewed"

I disabled all the plugins I have and re-enabled one by one and tested. And I realized that the error was only shown when activating the gutenberg.

So the problem is in the gutenberg. You can verify what I said by doing a simple test.

Create a container, click on blackground and put color, you will see the error message.

**Comment by talldan** [comment]
@augustoleder I'm going to close this. Please could report this again, but properly fill out the bug report template that you see here:
https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.md

Also please explain what 'Gutentor' and the 'Container' block are when creating the new issue. Thanks.
