### ISSUE TITLE
Writing flow: Select all doesn't work when focused on a non-text input

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#32713]
## Description

"Select all" doesn't select all blocks when focused on an `input` element type that doesn't support selection ranges, such as `checkbox`.

## Step-by-step reproduction instructions

1. Add a `<input type="checkbox" />` to the edit component of a Core block, such as `Code`.
2. Move keyboard focus to the checkbox.
3. Do a "Select all" (e.g. <kbd>⌘A</kbd>).

## Expected behaviour

All blocks are selected, as if I were focused on any other non-text tabbable element like `<button>`.

## Actual behaviour

All the text in the window is selected.

## Screenshots or screen recording (optional)

<img src="https://user-images.githubusercontent.com/555336/122109003-d5d64c80-ce57-11eb-9ec2-1cdd4ccad138.gif" alt="Select all does not work as expected when focused on a checkbox" width="400">

## WordPress information

Latest `trunk` in wp-env container.

## Device information
- Device: Desktop
- Operating system: macOS 11.3
- Browser: Chrome  91.0.4472.77

---

Intelligent support for this behavior would require a more advanced system to classify `input` elements, because some types do have built-in Select All behavior (e.g. `number`) but don't support selection range attributes.

**Comment by jordesign** [comment]
It seems this should have been closed by the issues mentioned above - and I can no longer recreate this so i'll close it for now.
