### ISSUE TITLE
Content load fails if number passed as fontSizeSlug

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#32719]
## Description
With Gutenberg 10.8.1 block content fails to load in the editor if a number is passed to `getFontSizeClass` instead of a string. Previously lodash kebabCase was forgiving of this misdemeanor.

## Step-by-step reproduction instructions
Run jetpack blocks in local env with 10.8.1
Insert following code into code view of editor
```
<!-- wp:jetpack/subscriptions {"customButtonBackgroundColor":"#151516","fontSize":16,"customFontSize":16,"borderRadius":3,"borderColor":"#ffffff","customBorderColor":"#ffffff"} -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">[jetpack_subscription_form show_subscribers_total="false" button_on_newline="false" custom_background_button_color="#151516" custom_font_size="16" custom_border_radius="3" custom_border_weight="1" custom_border_color="#ffffff" custom_padding="15" custom_spacing="10" submit_button_classes="has-16-font-size has-ffffff-border-color" email_field_classes="has-16-font-size has-ffffff-border-color" show_only_email_and_button="true"]</div>
<!-- /wp:jetpack/subscriptions -->
```
Switch back to editor view and 
The content will not show in the editor, and the following error will show in the console:

```
Uncaught TypeError: fontSizeSlug.replace is not a function
    getFontSizeClass utils.js:69
    save editor-beta.js:31
    getSaveElement serializer.js:119
    getSaveContent serializer.js:184
    addParsedDifference custom-class-name.js:162
```
## Expected behaviour
This method will continue to accept numbers as fontSizeSlug for those blocks that have been expecting it to work.

**Comment by edwinho89** [comment]
Initially reported on #21259015-hc

**Comment by oandregal** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/32742
