### ISSUE TITLE
getColorClassName change cause invalidation of existing block content

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#32721]
## Description
The removal of lodash kebabCase from getColorClassName meant that special characters where not being stripped from the resulting classnames, so blocks that were passing in `#ffffff` as the color slug were expecting to see `has-ffffff-border-color` as the classname, but method is now returning `has-#ffffff-border-color`

## Step-by-step reproduction instructions
Run jetpack blocks in local env with 10.8.1
Insert following code into code view of editor
```
<!-- wp:jetpack/subscriptions {"customButtonBackgroundColor":"#151516","fontSize":16,"customFontSize":16,"borderRadius":3,"borderColor":"#ffffff","customBorderColor":"#ffffff"} -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">[jetpack_subscription_form show_subscribers_total="false" button_on_newline="false" custom_background_button_color="#151516" custom_font_size="16" custom_border_radius="3" custom_border_weight="1" custom_border_color="#ffffff" custom_padding="15" custom_spacing="10" submit_button_classes="has-16-font-size has-ffffff-border-color" email_field_classes="has-16-font-size has-ffffff-border-color" show_only_email_and_button="true"]</div>
<!-- /wp:jetpack/subscriptions -->
```

Block will be invalid, but should be valid.

**Comment by oandregal** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/32742
