### ISSUE TITLE
Woocommerce templates and FSE

### ISSUE THREAD

**Issue by grogou** [WordPress/gutenberg#32728]
## What problem does this address?

How we can create templates for woocommerce? Is there a way to do that?
For example products archive page.

**Comment by nerrad** [comment]
Howdy 👋🏻 ,

Probably the best place to post this would be in the [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block) repository for now (you can reference my comment as well there). This is something the Woo team is going to be working on as well.

**Comment by grogou** [comment]
Thank you @nerrad, I am already try migrate All Products block for templates, for now only category taxonomy is working,  will be good if i can help you.
