### ISSUE TITLE
List view: show anchors in brackets for easier to find a certain part in content and to view clearly which parts have HTML anchors

### ISSUE THREAD

**Issue by oglekler** [WordPress/gutenberg#32740]
## What problem does this address?
When you have a long post it's difficult to find the right part in the structure.

## What is your proposed solution?
To add HTML anchors in brackets to blocks in the List view.

HTML anchors are widely used for internal post navigation, it will be good to have them visible in the three:
![2021-06-16_18-03-55](https://user-images.githubusercontent.com/16874687/122244971-9b0afd80-cec5-11eb-8181-9ce0aeadf657.png)

**Comment by talldan** [comment]
Good news. This was implemented already in https://github.com/WordPress/gutenberg/pull/31992.

**Comment by oglekler** [comment]
Cool, thanks! I wasn't looking at closed issues )
