### ISSUE TITLE
Gallery Block: columns count update on remove

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#3274]
## Issue Overview
If you add images to a gallery you can set the columns slider max to the image count. If you delete images, the slider isn't updated.

## Steps to Reproduce (for bugs)
1. Add a gallery with 3 images.
2. set the columns count to 3
3. Remove one image

## Expected Behavior
The columns slider should update to 2.

## Current Behavior
The columns slider stays at 3.

![gallery-colums](https://user-images.githubusercontent.com/695201/32245234-655e9bf0-be7b-11e7-8cf9-3471f7719ae8.png)

**Comment by jorgefilipecosta** [comment]
Thank you for your report @Soean, I submitted a pr in https://github.com/WordPress/gutenberg/pull/3300 that should fix it.
