### ISSUE TITLE
Blocks that use entities are not saved in the widget editors

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#32756]
## Description
When using a full site editing block (e.g. Site tagline) or reusable blocks in the widget editors, changes to those blocks are not being saved.

I imagine the issue is that the widget editor doesn't save all the edited entities. This also exposes the question of whether the editor now needs to replicate the UI that the post and site editors have for entities. I think the answer to that is 'yes', but it might be a challenge in the customizer.

An additional thing to mention is that in the customizer changes to those entity based blocks are not being reflected in the preview

## Step-by-step reproduction instructions
1. Add a Site Tagline or Reusable block
2. Make changes to it
3. Save
4. Reload

## Expected behaviour
Changes to the blocks are kept

In the customizer, changes are shown in the preview

## Actual behaviour
Changes to the blocks are lost

In the customizer, changes are not shown in the preview

**Comment by noisysocks** [comment]
Just noting we could consider disabling these blocks in the widgets editors as a temporary solution for 5.8.

**Comment by getdave** [comment]
> Just noting we could consider disabling these blocks in the widgets editors as a temporary solution for 5.8.

I'd say that would be reasonable for 5.8. 

Whilst it's not ideal to lose these blocks, it seems like given its scope this could be quite a large issue to solve in such a short space of time.

**Comment by getdave** [comment]
In case we need it (which I think we will) here is a PR that disables all the FSE blocks in the Customizer. I'd appreciate some input on which blocks we can safely retain (if any):

https://github.com/WordPress/gutenberg/pull/32761

**Comment by talldan** [comment]
Thinking about what other options there are. 
- Adding the entity saving flow to the standalone widget screen might not be too difficult. Mostly a matter of copying the post/site editor implementation.
- In the customize widget screen, there are two separate problems. 
    - First the saving flow. To fix this would mean hooking into the customizer's publish button, and right now I'm not sure how possible that is. 
    - The second issue is the preview not updating when making changes, this doesn't seem to happen because BlockEditorProvider's onChange or onInput callbacks are not triggered for blocks that use entities. Is this a bug with the BlockEditorProvider, or should the widget editor be hooking into these changes in some other way? - https://github.com/WordPress/gutenberg/blob/bc35ea9f06c7f0b12b4449d5c67e0d4931d54a71/packages/customize-widgets/src/components/sidebar-block-editor/sidebar-editor-provider.js#L24-L25

**Comment by kevin940726** [comment]
Might be worth mentioning that the "Preview" feature also doesn't work for FSE blocks even in the post editor. This might be related, as the problem could be in the FSE side but not in the widgets screen. Maybe we should fix it there, not sure though. I know very little about FSE 😅.

https://user-images.githubusercontent.com/7753001/122532470-1ea62500-d053-11eb-9b90-6cd43e4d16b1.mp4

> First the saving flow. To fix this would mean hooking into the customizer's publish button, and right now I'm not sure how possible that is.

This should be possible, hacky, but possible. We might just need to attach an event to the publish button and call `event.stopPropagation()`. Or we can hide the original button and portal a new one there.

**Comment by talldan** [comment]
> Might be worth mentioning that the "Preview" feature also doesn't work for FSE blocks even in the post editor.

Good spot. I wonder if that's a known issue.

**Comment by draganescu** [comment]
Let's move forward with @getdave 's PR that disables the FSE blocks in widget areas. These blocks are quite new and they're not meant for classic themes anyway, yet at least.

**Comment by getdave** [comment]
I've raised a followup in https://github.com/WordPress/gutenberg/issues/32952 to track the need to reinstate these blocks in future.
