### ISSUE TITLE
3 scrollbars in Gutenberg screen

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#3276]
Updated to 1.6 and see 3 scrollbars in Gutenberg screen. Is it by feature ?

![](https://s1.postimg.org/1ul8yi8sgv/2017-10-31_205639.jpg)

**Comment by karmatosed** [comment]
What browser do you see this in? I tried in Chrome, so knowing the browser would help narrow the issue down.

**Comment by StaggerLeee** [comment]
Browser is Vivaldi, latest version. (Chromium engine).
In Chrome I see 2 scrollbars. No, if I open Extended Settings the same, 3 scrollbars.

In old TinyMce screen only one.

**Comment by StaggerLeee** [comment]
Good exercise, to switch same Posts between Gutenberg and classic editor. To see superiority of Gutenberg. (As content editor)
Maybe good idea would be to force all Users to do it at least once.

Only if you manage to not make angry thousands of code developers.

**Comment by StaggerLeee** [comment]
Any plans to make something about it ? 3 scrollbars are still there.

**Comment by karmatosed** [comment]
For now, again I am unable to recreate this and I have tried. If you can try the latest version and if you still get the same issue we can reopen. Also make sure you remove all plugins and use a default theme, so we're sure to be testing the same thing.
