### ISSUE TITLE
[Widgets screen] Clicking on the bottom of the screen doesn't unselect block

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#32769]
## Description

Clicking on empty spaces in the Widgets Screen should unselect the currently selected block. It works when clicking on the left/right side of the screen, but not when clicking on the bottom of the screen. Seems like the event is bound to the root element of the editor, but the editor's height is not stretched to the full screen.

## Step-by-step reproduction instructions

1. Go to Appearance -> Widgets
2. Select any block
3. Try to unselect it by clicking on the bottom of the screen

## Expected behaviour

The block should be unselected and the toolbar should disappear

## Actual behaviour

Nothing happened

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/7753001/122380379-61f08d00-cf9a-11eb-87f3-8122137a55a1.mp4

## WordPress information
- WordPress version:  master
- Gutenberg version:  trunk
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Desktop
- Operating system:  macOS
- Browser:  All

**Comment by talldan** [comment]
From what I can tell could be considered a CSS styling issue, the clickable area doesn't extend down to the bottom of the page (there was a similar problem on the navigation screen too). But there might be other ways to fix it, so I'll leave that open to the person that fixes it.

**Comment by talldan** [comment]
From what I can tell could be considered a CSS styling issue, the clickable area doesn't extend down to the bottom of the page (there was a similar problem on the navigation screen too). But there might be other ways to fix it, so I'll leave that open.
