### ISSUE TITLE
ACF Custom Field (ACF PRO) content not saving

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3277]
## Issue Overview
ACF (Advanced Custom Fields) content isn't saving after updating the page

## Steps to Reproduce (for bugs)
1. Install & activate ACF
2. Create custom fields (ensure they're displayed on Pages/Posts)
3. Edit Page/Post
4. Add content to custom field & save page

## Expected Behavior
Custom field content should save

## Current Behavior
Custom field content doesn't save

_Firefox 56.0.2 (64-bit)
macOS Sierra 10.12.1
Gutenberg 1.6.0_

**Comment by themightyant** [comment]
Concur not working as intended.  Overlay of "Updating Settings" over metabox iframe.  
In Chrome a modal alert box comes up with "Changes you made may not be saved."

Gutenberg 1.6.0
Chrome 62.0.3202.75 (Official Build) (64-bit)
Windows 10 (64-bit)

**Comment by youknowriad** [comment]
cc @BE-Webdesign Any idea about this?

**Comment by BE-Webdesign** [comment]
Hi!

I will take things out for a spin and see what has happened. ACF definitely worked at one point.

@maddisondesigns Could you share your ACF registered fields data, it is possible one of the types of fields caused the issue.

**Comment by wsydney76** [comment]
Happens with ACF Pro (=ACF 5) i think.

**Comment by maddisondesigns** [comment]
@BE-Webdesign Sure, you can download the json files from here. I had two sample Field Groups set up...
https://www.dropbox.com/s/npdoeqahfqq0ps3/group_58e48c86cc51e.json?dl=0
https://www.dropbox.com/s/tb9sayjy2c34wv8/group_5911300e9f97c.json?dl=0

In case it's worth noting, one of the fields is a Gallery field, which I raised a seperate issue on (#3278).

The site I was testing this on, only has the following plugins activated:
_Advanced Custom Fields PRO v5.6.4
Gutenberg v1.6.1
WooCommerce v3.2.3_

**Comment by youknowriad** [comment]
I'm not able to reproduce this, trying the simplest field "text". If there are issues with specific fields, let's raise those issues separately.

**Comment by wsydney76** [comment]
Problem still exists in 1.7, regardless of field type.

Please follow @maddisondesigns steps above and use ACF Pro, it's a different product. Or may be https://www.advancedcustomfields.com/blog/acf-5-early-access/ .

You should not close an issue until you have investigated it correctly.

**Comment by youknowriad** [comment]
> You should not close an issue until you have investigated it correctly.

Please read the issue properly, there's no mention of ACF Pro in the original issue thus, this is probably specific to a special field in ACF Pro and  I said 

> If there are issues with specific fields, let's raise those issues separately.

**Comment by maddisondesigns** [comment]
@youknowriad Why was this closed? You mention that I didn't specifically say that it was the Pro version in the title, which is correct, but you've changed that now. The fact remains, that Gutenberg still breaks ACF Pro. Can you please re-open this.

**Comment by BE-Webdesign** [comment]
@maddisondesigns, This is a duplicate of #3730. That is most likely why Riad closed the issue.
