### ISSUE TITLE
Media dialog not displaying when trying to add image(s) to ACF Gallery Custom Field

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3278]
## Issue Overview
When using an ACF (Advanced Custom Fields) gallery custom field, you can click a button to view the Media popup window to allow adding/selecting images. This is not working in Gutenberg.

## Steps to Reproduce (for bugs)
1. Install & activate ACF
2. Create a gallery custom field (ensure it's displayed on Pages/Posts)
3. Edit Page/Post
4. Click the button to add an image to your gallery custom field

## Expected Behavior
I should be able to add/select images to my gallery custom field

## Current Behavior
Media popup window doesn't display which means that I can't add/select images

_Firefox 56.0.2 (64-bit)
macOS Sierra 10.12.1
Gutenberg 1.6.0_

**Comment by youknowriad** [comment]
I believe the gallery custom field is a plugin on top of ACF. It would be good to have input from the plugin author.

**Comment by maddisondesigns** [comment]
@youknowriad Nope, it's not. The Gallery field is a standard ACF Pro field.

The only plugins I have activated on this test site are:
_Advanced Custom Fields PRO v5.6.4
Gutenberg v1.6.1
WooCommerce v3.2.3_

**Comment by maddisondesigns** [comment]
I'll close this. The Media popup is working now for Gallery fields in ACF Pro 5.6.9
