### ISSUE TITLE
10.9 RC Error message: Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#32785]
## Description
After install of Gutenberg 10.9.rc1 I see the warning on Wp-admin and front end: 
` warning: g: file_get_contents(/public_html/wp-content/plugins/gutenberg/lib/../build/widgets/blocks/legacy-widget/block.json): Failed to open stream: No such file or directory`

## Step-by-step reproduction instructions

1. Enable WP Debug
2. install Gutenberg 10.9 rc1 on a clean install
3. Activate Theme Twenty-Twenty One
4. Activate Gutenberg plugin

You should see the warning appear on the top of the screen. 

## Expected behaviour
The correct location reference would be: 
`/public_html/wp-content/plugins/gutenberg/build/widgets/blocks/legacy-widget/block.json`

## Actual behaviour
Warning appears. 

## Code snippet (optional)
it's probably related to code in **lib/blocks.php** line 99 
![Screen Shot 2021-06-17 at 11 12 12 AM](https://user-images.githubusercontent.com/39980/122425001-2be0e800-cf5d-11eb-85a0-1bf1f5e75d5d.png)

## WordPress information
- WordPress version: 5.8 
- Gutenberg version: 10.9.rc1
- Are all plugins except Gutenberg deactivated? **Yes**
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty-Twenty-One

## Device information
- Device: Desktop
- Operating system: OS 10.15.7
- Browser: Chrome Version 91.0.4472.106

**Comment by bph** [comment]
Reproduced it with local site as well. Here is the stack trace
![Screen Shot 2021-06-17 at 11 19 50 AM](https://user-images.githubusercontent.com/39980/122426210-0d2f2100-cf5e-11eb-960d-78ed999d1874.png)

**Comment by Mamaduka** [comment]
It looks like the `blocks` directory is missing from the widget package when Github builds release artifacts.

Here's another example build for PR: https://github.com/WordPress/gutenberg/actions/runs/947360778.
