### ISSUE TITLE
Using Gutenberg outside of WP

### ISSUE THREAD

**Issue by alanps** [WordPress/gutenberg#32790]
I have the Gutenberg library that I got from Github and would like to know how to select Gutenberg language outside of Wordpress ? I saw that the translation files exist, I just didn't find a way to select them...

**Comment by hideokamoto** [comment]
Gutenberg is using this package to provide a text translation.
https://github.com/WordPress/gutenberg/tree/trunk/packages/i18n

And it's using tannin and gettext libraries in nodejs.
Probably you can create a translation instance by using this method.
https://github.com/WordPress/gutenberg/blob/trunk/packages/i18n/src/create-i18n.js#L113-L142

Would you try this package and method?
Thanks.

**Comment by ntucakovic** [comment]
I'm trying to do the same; to use block-editor with custom blocks and a few gutenberg blocks from block-library package.

I'm struggling to figure out how localization is working with exposed gutenberg blocks outside of WP scope, specifically:
- How does the i18n decide which locale is active and should be used
- I suppose we need to have a singleton instance of i18n so we can add locale data to it. I'm unsure how gutenberg blocks from block-library can use those translations?
- How can I provide locale data for blocks within block-library, as well as block inspector, and is there a JSON file available with locale data for those? That part is probably handled within WP, but I'm wondering whether I can do some extra steps to provide locale data for this case

**Comment by ntucakovic** [comment]
@alanps I've managed to set locale data to be consumed by both core blocks, block inspector, and custom blocks. It ended up being very trivial, I just wasn't aware that localization can't be changed after blocks are mounted.

```js
setLocaleData({
    'No block selected.': ['Select something'],
    'Type / to choose a block': ['Type "/" to choose a block'],
    'Block inspector': ['Block editor'],
});
```

This needs to be executed before components are mounted. Otherwise, once mounted, default localization, defined in the brackets, will be consumed, as locale data will be empty.

Did you manage to find translation files for core blocks and components we could use to with setLocaleData?

**Comment by tellthemachines** [comment]
@alanps @ntucakovic if your problem is solved are we good to close this issue now?

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
