### ISSUE TITLE
Pagination query block issue

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#32792]
The pagination query block previous pages work. But going back to the 1st page from any of the others fails. Instead, it reloads the current page.

**Comment by mattschwartz03** [comment]
I just tested and it seems to work. Thank you for your time and attention on this!

**Comment by ghost** [comment]
I just tried with the latest version of the Gutenberg plugin and pagination still does not work properly. What would you like me to provide you?

**Comment by ghost** [comment]
If you go to my website, https://goblackcat.com, you can try it for yourself and see that the pagination is not working properly. Clicking on one of the other pages and then going back to the first page does not work.

**Comment by ntsekouras** [comment]
Thanks for reporting @mattschwartz03 ! I tested and it's a bug. This is the case though only when we have pretty permalinks enabled.

**Comment by ghost** [comment]
You're welcome. I am eager to see this one fixed as I want to create a custom page for posts.
