### ISSUE TITLE
No newline at the end of *.assets.php

### ISSUE THREAD

**Issue by vanduc1102** [WordPress/gutenberg#32802]
## What problem does this address?

I'm suggesting a new feature for this repo: https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/

I have to add a final newline for the file `*.assets.php` when using this sniffer https://docs.woocommerce.com/document/create-a-plugin/#error-1008

I think it is better to have final newline by default or with an option.

## What is your proposed solution?

There are 2 solutions

1. Add newline at https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/lib/index.js#L98

1. Add an option `insert_final_newline` to https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/lib/index.js#L27
base on the option , we can decide to add newline or not at https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/lib/index.js#L98

I'm happy to submit a PR for this request.

**Comment by Mamaduka** [comment]
Hi, @vanduc1102

It's usually good practice to exclude third-party or auto-generated code from CodeSniffer.

The documentation example includes `vendor` and `node_modules`. You can also exclude the `build` or directory you're using for compiled assets.

**Comment by vanduc1102** [comment]
Hi @Mamaduka , i have excluded the `build` folder already, but when i submit the plugin to WooCommerce Store, they check the file and give me an ERROR

```
FILE: /app/build/app.asset.php
------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------
 1 | ERROR | [x] File must end with a newline character
   |       |     (Generic.Files.EndFileNewline.NotFound)
------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------
```

**Comment by gziolo** [comment]
I guess we can just add a new line out of the box to follow WordPress conventions 👍🏻  

@vanduc1102, would you like to take care of this task?

**Comment by aristath** [comment]
Shouldn't this be fixed in the WooCommerce Store's phpcs configuration instead, adding something like this? This is ultimately an issue with the phpcs config, is it not?
```xml
	<rule ref="Generic.Files.EndFileNewline">
		<exclude-pattern>**/*.asset.php</exclude-pattern>
	</rule>
```

**Comment by gziolo** [comment]
> Shouldn't this be fixed in the WooCommerce Store's phpcs configuration instead, adding something like this? This is ultimately an issue with the phpcs config, is it not?

Ideally, it should. Realistically speaking, it won't have any impact on the projects when we add a new line.

**Comment by jeremyfelt** [comment]
FWIW, it's very nice when a project can run `phpcs --standard=WordPress-Extra` and not worry about creating a PHPCS config file. It's somewhat odd that WordPress scripts generate PHP code that does not meet WordPress Coding Standards.

I know it's difficult because of how `json2php` formats the code and that really is a nice way to do it.

If someone made a `json2WPphp` library (or similar) that formatted things in line with WordPress coding standards, would there be any interest in switching to that instead?

**Comment by gziolo** [comment]
> I know it's difficult because of how `json2php` formats the code and that really is a nice way to do it.
> 
> If someone made a `json2WPphp` library (or similar) that formatted things in line with WordPress coding standards, would there be any interest in switching to that instead?

`json2php` was the only solid option available at the time, so we can switch to a better alternative as soon as it is available. We could also fork the library and adjust it to meet our needs.

**Comment by mauriac** [comment]
> Shouldn't this be fixed in the WooCommerce Store's phpcs configuration instead, adding something like this? This is ultimately an issue with the phpcs config, is it not?
> 
> ```
> 	<rule ref="Generic.Files.EndFileNewline">
> 		<exclude-pattern>**/*.asset.php</exclude-pattern>
> 	</rule>
> ```

I have shipped a patch, but I think this comment worth to be taken account.
