### ISSUE TITLE
Improve the feeling of jumpiness when entering the template editor

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#32813]
When entering the template editor, and after creating a new template, there's a couple of seconds (or milliseconds) where you see the screen updating itself, replacing the block list shown (from the content of the post to the content of the template).

I think we should try to improve that to make the transition more seamless. I think some debugging is needed to understand exactly what changes are causing this clunky transition but here's some potential ideas:

 - Do not close the "creation template modal" until the template is fully created and loaded and add an isBusy state to the "create button"
 - Virtually hide the block list for some milliseconds to wait for the block list to populate entirely.

There might be other ideas to explore as well.

This is a UX improvement, I'm temptatively adding this to 5.8 project but it's not entirely mandatory.

This would need a champion cc @Mamaduka @ockham @aristath @jasmussen  ;)

**Comment by Mamaduka** [comment]
Happy to start working on this on Monday if there are no other takers.

**Comment by Mamaduka** [comment]
Hi, folks

Cherry-picked part of my "progress" for this enhancement since I think it can land independently - #33076.

> Virtually hide the block list for some milliseconds to wait for the block list to populate entirely.

Toggling visibility might look like a screen flash. However, it might not be the desired trade-off in this case.

**Comment by youknowriad** [comment]
Removed from the 5.8 must haves, there's no need to rush it at this point

**Comment by youknowriad** [comment]
I think this has improved over time.
