### ISSUE TITLE
Custom Templates: Should use "title" instead of "name" when displayed to the user

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#32818]
When adding a custom template using [the following example from the docs](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#customtemplates), the name that shows up in the UI is what's entered into the `name` field: 

```
{
    "version": 1,
    "customTemplates": [
        {
            "name": "my-custom-template",
            "title": "The template title",
            "postTypes": [
                "page",
                "post",
                "my-cpt"
            ]
        }
    ]
}
```

Site Editor Sidebar|Site Editor Title Bar|Post/page Editor
---|---|---
<img width="296" alt="Screen Shot 2021-06-18 at 9 47 37 AM" src="https://user-images.githubusercontent.com/1202812/122571209-7c6a4b00-d01a-11eb-907f-a7a8ae9c1d32.png">|<img width="304" alt="Screen Shot 2021-06-18 at 9 48 54 AM" src="https://user-images.githubusercontent.com/1202812/122571213-7d02e180-d01a-11eb-8006-32775fa8be6f.png">|<img width="306" alt="Screen Shot 2021-06-18 at 9 47 59 AM" src="https://user-images.githubusercontent.com/1202812/122571219-7e340e80-d01a-11eb-852c-78285183cc59.png">

I would've expected the "Title" field to show up in the UI, since that's the one that includes proper capitalization.

**Comment by kjellr** [comment]
This is related to, or possibly a duplicate of https://github.com/WordPress/gutenberg/issues/31704.

**Comment by carolinan** [comment]
I went down a 3 hour rabbit hole, so I am removing the good first issue label 😊

**Comment by Mamaduka** [comment]
Hi, @carolinan. Are you still working on this issue?

**Comment by carolinan** [comment]
No, but you could start here:
https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/block-templates.php#L222
https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/block-templates.php#L225

**Comment by carolinan** [comment]
The HTML file itself never includes the name, only theme.json does, so the slug is used twice.

**Comment by Mamaduka** [comment]
Thank you, @carolinan.
