### ISSUE TITLE
Use drag and drop to transform an Image block → Gallery block

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32819]
One behavior that users might expect to find in Gutenberg is the ability to create side-by-side images by dragging and dropping an image next to an existing one.

Note: This behavior has previously been explored in #13202 and perhaps elsewhere!

https://user-images.githubusercontent.com/77359364/122572980-4a59e880-d01c-11eb-8fb5-81052f798666.mp4

**Current behavior**
You can drag an image on top of an existing Image block, which will upload the new image and replace the current one. The drop zone covers the full area of the block and is indicated by a blue overlay color with a CTA.

**Proposed behavior**

![indicator](https://user-images.githubusercontent.com/77359364/122573118-6e1d2e80-d01c-11eb-8a2d-7e64d169937c.jpg)

The blue overlay color could be reserved for replacing an image, with a new treatment introduced for transforming the Image block into a Gallery block to achieve a side-by-side effect. I used a 4px vertical line to indicate the position of the new image — this is the same visual treatment used for the “move to” indicator (but I can also see a conceptual argument for using a 1px line like the sibling inserter). 

![snackbar-1](https://user-images.githubusercontent.com/77359364/122573149-79705a00-d01c-11eb-8ad2-33c89b4ab39c.jpg)

We could potentially show a snack bar after the user completes the transform via drag and drop, as it’s not explicitly clear that this action will change the block type. This would offer the opportunity to undo the transform. (It's also very easy to transform a Gallery block to Image blocks via the transform menu in the block toolbar, in case the user wants to reverse this change later.)

I imagine this could work by identifying separate drag zones within the area of the existing block for replacing/transforming but it would be helpful to play around with this in a PR to see what feels right!

**Comment by talldan** [comment]
@critterverse I think this might be the same idea as #9783

**Comment by annezazu** [comment]
[This came up in the sixteenth call for testing for the FSE Outreach program](https://make.wordpress.org/test/2022/08/13/fse-program-testing-call-16-back-to-basics/#comment-2700) for using drag & drop along with the "move to" option. Noting here as the "move to" option is something to consider when trying to address this problem too: 

>Moving images is done successfully both by drag & drop the blocks in the List View, and by using the move up/down chevrons in the image’s Block Toolbar. But the image movement is failed when I use the Move to option in the image’s Block Toolbar. Or perhaps my expectation isn’t inline with its designated usage.

Here's a video showing the current experience with GB 14.0.2 and WordPress 6.0.2: 

https://user-images.githubusercontent.com/26996883/188515635-e53a48b4-7062-4985-af0b-28956aaf3580.mp4

**Comment by tellthemachines** [comment]
Closing as this has been implemented in #56186.
