### ISSUE TITLE
Unify drag and drop behavior across Image block and Gallery block

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32820]
Potential follow-up to https://github.com/WordPress/gutenberg/issues/32819

Currently in Gutenberg, you can drag an image on top of an existing Image block, which will upload the new image and replace the current one. The drop zone covers the full area of the block and is indicated by a blue overlay color with a CTA. The drop zone looks exactly the same on the Gallery block but instead of **replacing**, the new image is **added** to the gallery.

Issue https://github.com/WordPress/gutenberg/issues/32819 proposes making both of these interactions available for the Image block within a single drag motion. Perhaps the same behavior could be extended to the Gallery block:

https://user-images.githubusercontent.com/77359364/122574896-25ff0b80-d01e-11eb-94fa-3e3ba0e4a867.mp4

This would allow a user to go seamlessly from one image to two images, and from two images to three images, using the exact same interaction pattern. This could be a part of ongoing efforts to unify the Image block and Gallery block more closely.

**Comment by paaljoachim** [comment]
Thank you for adding both the issues Channing! @critterverse 

@glendaviesnz Glen can you take a look at both issues?
As this can likely be added to the updated Gallery block.

**Comment by glendaviesnz** [comment]
Thanks @paaljoachim  and @critterverse  - I have added both of these to the [Gallery refactor project board](https://github.com/WordPress/gutenberg/projects/56) so we don't forget to take a look at them once the main refactor is merged.

**Comment by glendaviesnz** [comment]
This has been fixed at some point. If dropping a new image between existing images it adds to the gallery, but if dropping on top of ane existing image that image is replaced.
