### ISSUE TITLE
The list view behavior is not consistent

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32823]
There is a behavior of the list view in the Widgets editor which does not appear to be correct. I could not reproduce in the post editor. The wrong behavior is that when the focus is moved outside of widgets the list view shows only the contents on one widget area.

### To reproduce

1. Use the latest Gutenberg trunk
2. Make sure you have a theme with some widget areas (Twenty Twenty)
3. Go to Appearance > Widgets
4. Make sure you have some blocks and/or widgets.
5. Notice the List view contains all the widget areas
5. Click on the editor's header
6. Notice the List view contains only one widget area

### Screencast

https://user-images.githubusercontent.com/107534/122601627-3fce3c00-d07a-11eb-9ec5-84c3311ef90e.mp4

### Expected behavior

Either always show the contents of the focused widget area or always show all the widget areas.

**Comment by noisysocks** [comment]
I'm inclined to close this and have us work on implementing https://github.com/WordPress/gutenberg/issues/32311 instead. Thoughts?

**Comment by noisysocks** [comment]
Please re-open if you disagree 😀

**Comment by draganescu** [comment]
@noisysocks well, we should keep this open and retest this after #32311 because this issue looks like an underlying problem with how we look at the block tree in our data store, not a problem with the list view itself.

**Comment by gwwar** [comment]
Closed by https://github.com/WordPress/gutenberg/pull/35706
