### ISSUE TITLE
Navigation Block outputs incorrect percent-encoded URL, resulting in broken link

### ISSUE THREAD

**Issue by waviaei** [WordPress/gutenberg#32837]
## Description

Navigation block -- when a link that has slug with characters that gets URL encoded (such as Japanese), the inserted navigation link become wrongly encoded, thus resulting in incorrect URL link that results in 404 when clicked.

For example;

If you create a Page with title `ポートフォリオ` (en: portfolio) and slug also `ポートフォリオ`, the resulting permalink is as follows: `https://fse.test/%e3%83%9d%e3%83%bc%e3%83%88%e3%83%95%e3%82%a9%e3%83%aa%e3%82%aa/`

<img width="264" alt="スクリーンショット 2021-06-20 23 45 30" src="https://user-images.githubusercontent.com/1564991/122678445-e99bfd00-d221-11eb-80f9-f8e21681cb0c.png">

The slug `ポートフォリオ` is correctly [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding).

However, when you insert Page Link block of Navigation link, you can insert but the resulting URL become like so`https://fse.test/%25e3%2583%259d%25e3%2583%25bc%25e3%2583%2588%25e3%2583%2595%25e3%2582%25a9%25e3%2583%25aa%25e3%2582%25aa/`

According to the wiki above, percent-encoded `%` is `%25`, so it looks like either; escape `%` character is encoded, or the string is encoded twice?

Same issue were observed with when using the Category Link block. E.g, a category with slug `東京` (en: tokyo)
`https://fse.test/category/%e6%9d%b1%e4%ba%ac/` get output as 
`https://fse.test/category/%25e6%259d%25b1%25e4%25ba%25ac/`

I observed these when using Navigation block, in both the template editor and post editor.

## Step-by-step reproduction instructions

1. Create Page, with just title. Title can be anything. e.g. `ポートフォリオ` but slug must also be something that will get URL encoded.
2. Go to either template editor or post editor
3. Insert Navigation block, horizontal or vertical, then choose "start from blank"
4. Insert Page Link block, choose the page created in step 1.
5. Save and check on the frontend. 

## Expected behaviour

Link to that Page.

## Actual behaviour

Broken link that results in 404

## Screenshots or screen recording (optional)

step-by-step reproduction.
![2021-06-20 22-47-46 2021-06-20 22_58_56](https://user-images.githubusercontent.com/1564991/122679168-d0e11680-d224-11eb-98f4-dfb07c91c7a6.gif)

actual behaviout
![2021-06-21 00-09-56 2021-06-21 00_26_23](https://user-images.githubusercontent.com/1564991/122679832-5d8cd400-d227-11eb-9126-efad0a2c469b.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Theme: TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS 11.4
- Browser: Chrome 91.0.4472.114

**Comment by torounit** [comment]
https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/block-library/src/navigation-link/edit.js#L203

URL encoding is done in this line, but the URL suggested by WordPress is already URL encoded.

I think it is better to use [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class instead.
