### ISSUE TITLE
Polish design of Button block, and redesign link input

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3283]
## Issue Overview

The Button block could use a bit of love given recent Gutenberg changes. Here's what it looks like now:

![screen shot 2017-11-01 at 08 46 35](https://user-images.githubusercontent.com/1204802/32264941-431a63c4-bee1-11e7-96ab-ada16deaf808.png)

The Blue is a Gutenberg blue, not one from the theme. The link toolbar covers content, both the block itself and succeeding content. Given how cool this block can be, let's look at some polish.

## Mockups

**Unselected:**

![button](https://user-images.githubusercontent.com/1204802/32264976-68a7fa8e-bee1-11e7-91b3-8fdfe6572eee.png)

It shows a "Button" label. It also uses the same font and font-size as body text, making the appearance simpler. It defaults to `currentColor` as the background, with white text on top of it, which further reduces the visual footprint. Remember, you can still change colors in the inspector.

**Selected**

If we lean into the [principles we laid out in the design doc](https://github.com/WordPress/gutenberg/blob/master/docs/design.md#block-design-checklist-dos-and-donts-and-examples), we can show controls on a selected block _after_ the block itself. Just like how the caption field makes the Image block take up more vertical space when selected, so, perhaps, can we do with the button block:

![button selected](https://user-images.githubusercontent.com/1204802/32265102-e215ff92-bee1-11e7-8d6f-f34b999e30f5.png)

In this design, a minimal link input field sits below the button, ready to be pasted into. It's no longer a toolbar (even if it is the same component), so it doesn't cover anything. 

Thoughts?

CC: @karmatosed

**Comment by rileybrook** [comment]
>we can show controls on a selected block after the block itself.

>In this design, a minimal link input field sits below the button, ready to be pasted into. It's no longer a toolbar (even if it is the same component), so it doesn't cover anything.

This makes the experience feel _very_ intuitive. I don't have anything constructive to add, but wanted to comment that this definitely feels like a step in the right direction.

**Comment by hedgefield** [comment]
Really great. I was just thinking of this concept for the permalink, glad to see you had the same approach here. 👌

**Comment by afercia** [comment]
> a minimal link input field sits below the button

Just a quick reminder: any input field or editable element needs to be properly labeled (at least with an `aria-label` attribute). Placeholders are not replacements for labels.

**Comment by karmatosed** [comment]
I really like this. Can we roll it out on the cover image block when the button is added too?
