### ISSUE TITLE
Paragraph block: Can't paste after a line break

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#32839]
In a paragraph block, after adding a manual line break (SHIFT + ENTER), the editor doesn't let you paste text, it doesn't do anything.

It works ok with just the WordPress core editor, when Gutenberg is deactivated.

A workaround for now is to add 2 line breaks, then delete the second one.

**Comment by hideokamoto** [comment]
Hi @formosattic 

Thanks for reporting your problem.
Could you share your environment information?

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser: 


Thanks.

**Comment by talldan** [comment]
This is the error message:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at addActiveFormats (utils.js:8)
    at HTMLParagraphElement._onPaste (use-paste-handler.js:190)
 ```
 
The same problem was reported in #32468 with the list block, so I'll close this as a duplicate and add the details there.
