### ISSUE TITLE
Child theme templates' overwriting not working

### ISSUE THREAD

**Issue by rufus87** [WordPress/gutenberg#32846]
## Description
In case of active child theme, there is no possibility to overwrite only one template file, since plugin tries to load all template files from active (child) theme directory instead of trying to load absentee template files from parent theme.

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Create any child theme.
2. Activate it.
3. Try to load any template file.

## Expected behaviour
All not overwritten template files must be correctly loaded if child theme is active and it does not contain overwritten template.

## Actual behaviour
Template files could not be loaded in case of active child theme that does not contains overwritten templates

**Comment by annezazu** [comment]
Hey @rufus87 thanks for reporting this! I'm going to close this out in favor of this current discussion issue on support for child themes in general: https://github.com/WordPress/gutenberg/issues/25612

I also want to share this exploration in case it's helpful: https://themeshaper.com/2021/05/27/blockbase-a-parent-theme-for-block-themes/
