### ISSUE TITLE
Gutenberg widget showing frontend script on preview

### ISSUE THREAD

**Issue by wongpk** [WordPress/gutenberg#32841]
## Step-by-step reproduction instructions
1. Install and activate GDPR cookie consent plugin
2. Go to Appearance > Widget and add any widget
3. On preview it will show up the consent bar

## Expected behaviour
The cookie consent bar should be on the frontend only.

## Actual behaviour
Cookie consent bar shows on all widgets in preview mode on Appearance > Widgets

## Screenshots or screen recording (optional)
https://postimg.cc/fkpn3YcJ

## WordPress information
- WordPress version: 5.8 beta 2
- Gutenberg version:
- Are all plugins except Gutenberg deactivated? No, only cookie consent plugin activated
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91, Edge 91, Firefox 90

**Comment by noisysocks** [comment]
Hey thanks for the report. Do you have a link to the GDPR cookie consent plugin you're using? I'm not sure if this can be fixed in core. It's possible that the plugin needs to be changed to not display the banner if `defined( 'IFRAME_REQUEST' )` is true.
