### ISSUE TITLE
Site Editor: Add Welcome Guide

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#32844]
Follow up to https://github.com/WordPress/gutenberg/issues/29031

The original issue was about adding the Welcome Guide to both the Template and Site Editor.
The issue closed after https://github.com/WordPress/gutenberg/pull/31330 got merged, even though the PR only added the guide to the Template Editor.
This makes sense in a way: the Template Editor will be included in Core 5.8, so it's definitely more urgent than the Site Editor.

This new issue simply tracks the addition of the Welcome Guide to the Site Editor as well, to avoid forgetting about it eventually.

**Comment by noisysocks** [comment]
Just noting that I saw a hint of a welcome guide design in https://github.com/WordPress/gutenberg/issues/29630#issuecomment-954159446.

**Comment by Mamaduka** [comment]
Hi, @kellychoffman

Is it possible to get images and text copy for Welcome Guide?

**Comment by carolynannewells** [comment]
Hello! Carolyn here from editorial. We got a ping for a copy review. Please could you direct me to the copy you would like me to look at?

**Comment by noisysocks** [comment]
> Hello! Carolyn here from editorial. We got a ping for a copy review. Please could you direct me to the copy you would like me to look at?

Sorry, I added the wrong label. We're currently awaiting design and copy.

**Comment by Mamaduka** [comment]
I created PR, but we still need design and copy for the new Welcome Guide.

**Comment by kellychoffman** [comment]
@carolynannewells: copy for the Styles welcome guide is in this doc.https://docs.google.com/document/d/1LTlLW6M8UjlHo3KUNmVmWElrfm8CRvQl3tRPueyf22Y/edit#heading=h.cjfiamz95gn9

Copying it below as well in case that is easier.

### Editor welcome guide:

**Edit your site**
Enjoy the familiar experience of blocks to edit your full site, from the header all the way down to the footer. Click [Styles icon] to start designing your typography, layout, colors, and blocks. 

### Styles welcome guide:

Slide 1: **Welcome to Styles** 
Give your entire site a new look in big and small ways - create a default color palette for your buttons or change the font used everywhere. 

Slide 2: **Set the design**
Customize various aspects of your site. Try out and apply different colors, typography, and layouts across your entire site or leave it your theme to handle!

Slide 3: **Personalize blocks**
Choose the styles for all blocks to ensure a cohesive experience across your site. Create a branded buttons block with your unique colors or set the Heading block to the size of your liking. 

Slide 4: **Learn more**
New to the block themes and styling your site? Here's a detailed guide to learn how to make the most of it.



co-wrote with @annezazu

**Comment by kellychoffman** [comment]
@javierarce: Would you be able to lend your animation design to the welcome guides? 

For reference: To see what the current one looks like, go to: Posts > Add New > kabab menu in upper right > check Welcome Guide. I don't think the style needs to be exactly the same, but just wanted to point you to what the current one looks like.

**Comment by jameskoster** [comment]
Just to clarify: The "Editor welcome guide" should appear when you click Appearance > Editor (beta).

The "Styles welcome guide" should appear when you click Appearance > Styles.

**Comment by javierarce** [comment]
> @javierarce: Would you be able to lend your animation design to the welcome guides?

Yes 💫

**Comment by carolynannewells** [comment]
Hello! I made adjustments to the copy on the Googledoc. Please let me know if that does not work or if you need any other help. Thanks!

**Comment by kellychoffman** [comment]
Thank you so much! cc @Mamaduka for final copy here: https://docs.google.com/document/d/1LTlLW6M8UjlHo3KUNmVmWElrfm8CRvQl3tRPueyf22Y/edit#heading=h.cjfiamz95gn9

**Comment by Mamaduka** [comment]
Thank you, everyone.

**Comment by javierarce** [comment]
I'm currently working on the animations and I think I'll be able to have all of them before the freeze.

I've created [some mockups in Figma](https://www.figma.com/proto/BlF2skiewkRf0FqNOm3Xmp/Animations?page-id=0%3A1&node-id=4%3A2211&scaling=min-zoom&starting-point-node-id=4%3A2211&show-proto-sidebar=1) for three of them (Edit your site, Welcome to Styles, Set the design). You can test the animations simply by clicking the screen to advance to the next step.

Because of time constraints, I think we could reuse the "Learn more" animation we currently have.

**Comment by javierarce** [comment]
Here are the three first gifs (I'll provide the static versions when you've reviewed them). Also, let me know if you want them to loop (the ones we show now only play once).

### Edit your site 
_updated version below_

<a href="https://user-images.githubusercontent.com/4933/140489937-848fe89a-3c5f-4080-9378-c859283dc87f.gif"><img src="https://user-images.githubusercontent.com/4933/140489937-848fe89a-3c5f-4080-9378-c859283dc87f.gif" width="320"></a>


### Welcome to styles 
_updated version below_

<a href="https://user-images.githubusercontent.com/4933/140489963-c4556ac7-d78a-4881-94bc-070122fde878.gif"><img src="https://user-images.githubusercontent.com/4933/140489963-c4556ac7-d78a-4881-94bc-070122fde878.gif" width="320" ></a>

 
### Set the design
<a href="https://user-images.githubusercontent.com/4933/140654790-9ad475e8-bb45-408e-af9f-3cadec5c0bf5.gif"><img src="https://user-images.githubusercontent.com/4933/140654790-9ad475e8-bb45-408e-af9f-3cadec5c0bf5.gif" width="320" ></a>

**Comment by javierarce** [comment]
And here's the gif for "Personalize blocks"

<a href="https://user-images.githubusercontent.com/4933/140499197-e497a167-edb8-4bfa-a462-3065dc962aba.gif"><img src="https://user-images.githubusercontent.com/4933/140499197-e497a167-edb8-4bfa-a462-3065dc962aba.gif" width="320"></a> 

I'll probably try to come up with something a little more exciting for "Edit your site", but in any case let me know what you think of these animations.

**Comment by javierarce** [comment]
Ok, I added circle bursts to the following animations to make them more interesting:

### Welcome to styles
<a href="https://user-images.githubusercontent.com/4933/140506059-88d5f9d2-219f-4448-9e3e-4325208f3be0.gif"><img src="https://user-images.githubusercontent.com/4933/140506059-88d5f9d2-219f-4448-9e3e-4325208f3be0.gif" width="320"></a>

### Edit your site
<a href="https://user-images.githubusercontent.com/4933/140506067-cd8cbab4-9a36-4e17-b3ad-c4d86659ffa3.gif"><img src="https://user-images.githubusercontent.com/4933/140506067-cd8cbab4-9a36-4e17-b3ad-c4d86659ffa3.gif" width="320"></a>

**Comment by kellychoffman** [comment]
WOW! I love these @javierarce 😍

**Comment by javierarce** [comment]
An updated version for "Edit your site" focusing more on template manipulation:

### Edit your site
<a href="https://user-images.githubusercontent.com/4933/141464273-44c783b8-2d20-4a9f-8f76-c0d55cb9dc9a.gif"><img src="https://user-images.githubusercontent.com/4933/141464273-44c783b8-2d20-4a9f-8f76-c0d55cb9dc9a.gif" width="320"></a>

And here are the previous ones (adjusted to account for the close button position)

### Welcome to styles
<img src="https://user-images.githubusercontent.com/4933/141136973-f8d4398a-4f8f-43b4-9ba0-5948822db11c.gif" height="240">

### Set the design

<img src="https://user-images.githubusercontent.com/4933/141136939-3ee826aa-3aab-4eb0-bf27-3fd397d58738.gif" height="240">

### Personalize blocks
<img src="https://user-images.githubusercontent.com/4933/141137027-765f9765-9a50-417a-8d21-bb167a0cdbfe.gif" height="240">
