### ISSUE TITLE
Error edit.getParam().join is not a function on opening a post with Gutenberg

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3284]
When opening a post to edit with Gutenberg, this message is shown in the console:

![join-not-fn](https://user-images.githubusercontent.com/583546/32265491-878acd26-bee3-11e7-9896-cbc0e5b6fd89.png)

**Comment by aduth** [comment]
`initAtDCore` sounds like After the Deadline, otherwise known as Jetpack's Proofreading module:

http://www.afterthedeadline.com/
https://jetpack.com/support/spelling-and-grammar/

Guessing this is a plugin compatibility issue.

**Comment by nosolosw** [comment]
Good guess! I checked loading a post with and without proofreading enabled in Jetpack. When I disable it, the errors are no longer there.

**Comment by spencerfinnell** [comment]
Confirmed this still happens with proofreading enabled in Jetpack.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521735668000188)._

**Comment by designsimply** [comment]
Closing in favor of https://github.com/Automattic/jetpack/issues/9128 because it sounds to me like the issue needs to be fixed on the plugin side. Please re-open if that's not correct!
