### ISSUE TITLE
Twenty Ten block patterns panel jerks in 5.8 beta 1, when not in Fullscreen mode

### ISSUE THREAD

**Issue by zzap** [WordPress/gutenberg#32851]
## Description
When using block patterns with Twenty Ten theme on WordPress 5.8-beta 1, patterns panel is jerking once all patterns are loaded. This seem to not be the problem when in Fullscreen mode. 

## Step-by-step reproduction instructions
- Install WordPress 5.8-beta 1
- Install and activate Twenty Ten theme from [develop mirror](https://github.com/WordPress/wordpress-develop/tree/master/src/wp-content/themes).
- Open edit/add new post screen
- Exit Fullscreen mode
- Open block inserter and switch to patterns panel

## Expected behaviour
Panel shouldn't jerk at all, in any mode.

## Actual behaviour
But it does jerk when not in Fullscreen mode.

## Screenshots or screen recording (optional)
https://www.awesomescreenshot.com/video/4208067?key=d2c940ffeb4ca97ebef98854c8e2e9b1

## WordPress information
- WordPress version: 5.8 beta 1
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Only active plugin is WordPress Beta Tester
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Ten

## Device information
- Device: Desktop
- Operating system: Kubuntu 20.04
- Browser: Google Chrome, Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by annezazu** [comment]
Tried to replicate with 2010 and WP 5.8 with the latest of Gutenberg but couldn't replicate:

https://user-images.githubusercontent.com/26996883/127386186-50a0d254-116d-44e0-94a0-400a91b46ec5.mov

Going to close this out as a result but thank you for reporting <3
