### ISSUE TITLE
Editor menu collapses with the notices panel from another plugin

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#3286]
It seems that the editor menu collapses with the notices panel from another plugin (in this case, Jetpack):

![gutenberg-and-jetpack](https://user-images.githubusercontent.com/583546/32268682-5fb40616-bef0-11e7-944d-c6a83749df0d.png)

I'm on Gutenberg 1.6.0 and Jetpack 5.4.

**Comment by jeherve** [comment]
This looks like a duplicate of #3214

**Comment by mtias** [comment]
Consolidating in #3395.
