### ISSUE TITLE
Remove rel="nofollow ugc" from internal links in the comments

### ISSUE THREAD

**Issue by dankopi** [WordPress/gutenberg#32879]
EDIT: I'm sorry, this was doesn't belong to WordPress/gutenberg. Could a moderator please move it. Thanks. 

## What problem does this address?
When you reply to someone's comment as an author, and lets say you point them to a page on your website, Wordpress automatically adds rel="nofollow ugc" to your links. The problem is - the link is to another page on the same website, so it's an internal link, and should be do follow. Furthermore, this is not user generated content. I'm the author, and I'm replying to an user. 

The problem is also present when a user posts a link in the comments to a page within the website. It should not be nofollow since it's an internal link. 

## What is your proposed solution?
Automatically disable rel="nofollow ugc" on all links that have the Site Address in the URL.

**Comment by aristath** [comment]
The ticket can not be "moved", so I'll go ahead and close it. Please open a new ticket in WordPress-Core's [trac](https://core.trac.wordpress.org/) instead :+1:
