### ISSUE TITLE
Monthly archive dropdown widget doesn't include custom classes.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#32870]
## Description

Custom widget classes do not display on the front-end for archive dropdown widgets.

## Step-by-step reproduction instructions
1. On WP Trunk, go to Appearance > Widgets
2. Add a monthly archive block
3. Format as a dropdown 
4. Add some custom classes in the advanced section
5. Update the widgets and view on front end, the custom classes will be missing

In list format, IE as a `ul`, the custom classes is shown.

## Expected behaviour
Custom classes apply to all layouts.

## Actual behaviour
Custom classes do not apply to all layouts.

## WordPress information
- WordPress version: Trunk @ https://github.com/WordPress/wordpress-develop/commit/a3da548cc46753a74348eb32ae24f49985b88803 | [r51192](https://core.trac.wordpress.org/changeset/51192)
- Gutenberg version: Trunk @ 779bb171e889ad527cc1c311675119e6596e0127
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: Laptop
- Operating system: macOS Big Sur
- Browser: Firefox Developer Edition 90.0b9

**Comment by thisissandip** [comment]
PR added: https://github.com/WordPress/gutenberg/pull/32971
