### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews error

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#32884]
## Description

After the [the RN `0.64` upgrade](https://github.com/WordPress/gutenberg/pull/29118), I noticed that the app is showing the following error:
```
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
```

As far as I investigated, it looks related to rendering a `FlatList` component inside a `ScrollView`.

**Reference:** https://stackoverflow.com/questions/58243680/react-native-another-virtualizedlist-backed-container

## Step-by-step reproduction instructions

1. Use a debug version that connects to the Metro server.
2. Open the editor.
2. Observe in the console that the mentioned error is logged.

## Expected behaviour

No errors should be logged.

## Actual behaviour

The mentioned error is logged.

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 8 (simulator)
- Operating system: iOS 14.2
- WordPress app version: `779bb171e889ad527cc1c311675119e6596e0127`

**Comment by dcalhoun** [comment]
React Native 0.71.0 includes [changes to this error](https://github.com/facebook/react-native/commit/62f83a9fad027ef0ed808f7e34973bb01cdf10e9). It will be interesting to see if this issue goes away or becomes more pressing whenever we upgrade React Native. 

Additionally, https://github.com/WordPress/gutenberg/pull/48791 may impact any solution to this error.

**Comment by fluiddot** [comment]
> React Native 0.71.0 includes [changes to this error](https://github.com/facebook/react-native/commit/62f83a9fad027ef0ed808f7e34973bb01cdf10e9). It will be interesting to see if this issue goes away or becomes more pressing whenever we upgrade React Native.

Thanks for sharing the update @dcalhoun 🙇 ! If this issue will be considered an error in newer RN versions, my impression is that it will be more pressing and probably a blocker when we upgrade RN to 0.71+.

> Additionally, #48791 may impact any solution to this error.

Seems clear that we'd need to stop passing the `scrollEnabled` prop in inner blocks to avoid to this warning. Most likely 
the changes introduced #48791 would help us although we'd need to tweak it as it relies on that prop.

**Comment by dcalhoun** [comment]
> If this issue will be considered an error in newer RN versions, my impression is that it will be more pressing and probably a blocker when we upgrade RN to 0.71+.

I believe it is [already an error](https://github.com/facebook/react-native/commit/646605b90e666c4b0d1c1200a137eacf62b46f87) in our current release, 0.69. So, in theory, correctly leveraging `scrollEnabled` could resolve the error.

**Comment by dcalhoun** [comment]
Addressed by https://github.com/WordPress/gutenberg/pull/53237.
