### ISSUE TITLE
Feature request: Social Icons Widgets/Block

### ISSUE THREAD

**Issue by medvardsen** [WordPress/gutenberg#32890]
**Missing icon for showing Phone Numbers**
I am looking for a phone symbol to use in the Social Icon Widget in the Block Editor. The link symbol is a fit for ordinary web links and is of course possible to use even for a tel: link. 

It would be awesome to be able to choose an icon fitted for Phone Numbers as well to make it the message more clear to the webpage visitors

**Comment by skorasaurus** [comment]
This is being tracked at https://github.com/WordPress/gutenberg/issues/55718 ; you can subscribe to that issue to follow its progress.
