### ISSUE TITLE
Widget editor: Adding same image twice only saves one block

### ISSUE THREAD

**Issue by walbo** [WordPress/gutenberg#32901]
## Description
Inserting the same image twice in the same area only saves one of the blocks. This is also true if you use the image in a cover block and the same image in a image block.

Note: This only happens on `wp-admin/widgets.php` and not in the customizer.

## Step-by-step reproduction instructions
1. Go to widget editor.
2. Insert a image block with a image.
3. Insert a new image block with the same image.
4. Click save
5. Reload the page and only one of the blocks is saved.

## Expected behaviour
Both blocks is saved.

## Actual behaviour
Only one of the image blocks is saved.

## WordPress information
- WordPress version: 5.8-beta2-51203
- Gutenberg version: trunk (10.9.0-rc.1)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook
- Operating system: macOS Big Sur
- Browser: Chrome 91.0

**Comment by noisysocks** [comment]
Thanks for the report. This worked OK for me when I tested latest Core and Gutenberg `trunk`.

Could you please test using beta 3 and report back?

Also, could you please clarify which method you're using to add the image? Are you pressing _Media Library_ or _Upload_?

**Comment by walbo** [comment]
Sure. Seeing the same bug in beta 3.
Uploading the image in the first block and selecting the image from the media lib in the second block.

Made a short screen capture:

![widget-error](https://user-images.githubusercontent.com/1415747/123048785-13f6e180-d3ff-11eb-9d7f-f4afbb06741f.gif)

**Comment by noisysocks** [comment]
Thanks for confirming!

**Comment by thisissandip** [comment]
PR added: https://github.com/WordPress/gutenberg/pull/32951

**Comment by thisissandip** [comment]
The issue occurs with the File and Cover block too

**Comment by adamziel** [comment]
IIRC we filter out the widgets with duplicate IDs to prevent adding more than one instance of a widget implemented using a function (e.g. [marquee_greetings](https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1)). WordPress doesn't support having more than one instance of these, if one tries to save multiple `marquee_greetings` in different sidebars you will run into undefined behaviors. It isn't easy to prevent Gutenberg from adding one more instance of a block, hence the next best thing: this custom filtering logic.

It should still be possible to have many instances of the same image though. This behavior should be restricted just to these legacy function widgets.
