### ISSUE TITLE
Babel Runtime Regenerator is undefined (WordPress 5.8-beta2)

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#32911]
## Description
In one of my plugins, I'm using [React Select Async Paginate](https://github.com/vtaits/react-select-async-paginate/). The component works fine in WordPress 5.7 and earlier versions. However, while testing WordPress 5.8-beta2, I get the following error:

```Uncaught TypeError: _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0___default.a is undefined```

## Step-by-step reproduction instructions
I've created a [simple plugin project](https://github.com/davilera/wordpress-polyfill-bug) to reproduce the issue.

1. Clone the project to a WordPress 5.8-beta2 installation, under wp-content/plugins/
2. Run `npm i`
3. Compile using `npm run start`
4. Activate the plugin in your site
5. Open your browser's developer tools and look at the JavaScript console
6. You'll see the error message I mentioned before (or similar)

## Expected behaviour
When running the test on WordPress 5.7.2, no error message is displayed. You can then run `window.renderComponent()` in your browser's console and you'll see the React Select component properly rendered on screen.

## Actual behaviour
On WordPress 5.8, the script doesn't work:

```Uncaught TypeError: _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0___default.a is undefined```

## How to solve it?

If I install a new _npm_ dependency (`babel-polyfill`) to the project and tweak `src/main.js` by importing `babel-polyfill` as follows:

```js
import 'babel-polyfill';
import { render } from '@wordpress/element';
import { AsyncPaginate } from 'react-select-async-paginate';
/* ... */
```

things work as expected on WordPress 5.8-beta2 too, which makes me think the issue is somehow related to a polyfill (but I'm not sure).

## WordPress information
- WordPress version: 5.8-beta2
- Gutenberg version: unrelated
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu
- Browser: Firefox 89

**Comment by gziolo** [comment]
It should be fixed now that WordPress 5.8 Beta 3 is out and contains a fix that ensures that `regenerator-runtime` is present. 
Related Tract ticket: https://core.trac.wordpress.org/ticket/52941
Related commit: https://core.trac.wordpress.org/changeset/51212

We had confirmations from a few popular plugins that it resolves the same issue they encountered: Yoast, Jetpack, WooCommerce.

You shouldn't need to import `babel/polyfill` in your plugin with the latest changes introduced.
