### ISSUE TITLE
Unsupported Block: Non-functional question mark button (iOS only)

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#32912]
## Description

When doing the [TC001 test case of Unsupported Block Editing](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc001), I noticed a question mark button located at the lower right corner in the unsupported block editor that doesn't provide any functionality on iOS, after tapping on it, it does nothing. However, on Android, this button redirects to the support page.

I'm wondering if it's the same element that is displayed in the web version that displays the help popup (see attached screenshot):
<img width="450" alt="Screenshot 2021-06-23 at 10 14 13" src="https://user-images.githubusercontent.com/14905380/123061296-ce8ce100-d40b-11eb-8994-56d0a7e58d29.png">

**NOTE:** This is not a regression because I managed to reproduce it on version `17.5` of the main apps.

## Step-by-step reproduction instructions

**Precondition:**
A WP.com Simple site (it can be reproduced on an Atomic site too).

1. On the site described above, add a post, then add a block that's not yet supported on mobile
1. Log into the WordPress iOS mobile app using the site's WP.com account
1. Open the post and expect to see the block rendered as a placeholder with the text "Unsupported"
1. Tap the (?) icon and expect the option to edit the block in a web browser to be shown
1. Tap the edit in a web browser button and expect the block to be shown, ready to edit, on a new screen
1. Observe the question mark button located at the lower right corner
1. Tap on the question mark button and observe that it does nothing

## Expected behaviour

Elements displayed in the unsupported block editor should have functionality.

## Actual behaviour

The question mark button is not functional.

## Screenshots or screen recording (optional)

<img src=https://user-images.githubusercontent.com/14905380/123060960-7b1a9300-d40b-11eb-8fb6-6955ab0e1c1a.PNG width=400>

## WordPress information
- WordPress version: N/A
- Gutenberg version: v10.8.2-with-min-js-assets
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: `432a8eceb5140e664fcb7e48db234193748d9f1b `

**Comment by SiobhyB** [comment]
The help button was hidden from view in https://github.com/WordPress/gutenberg/pull/37221, following a discussion in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4339, where it was decided that hiding was the best course of action for the time being. I'll go ahead to close this issue, as the button is no longer accessible.
