### ISSUE TITLE
wp-env: run cli command misses the options passed with hyphens

### ISSUE THREAD

**Issue by Nikschavan** [WordPress/gutenberg#32929]
## Description
Any `wp-env run cli` commands with `--` flags ignore the extra flags, For eg `wp plugin install <plugin> --activate` will ignore the activate flag - 

```
> $ npm run wp-env run cli wp plugin install gutenberg --activate

> astra@3.6.2 wp-env /Users/Nik/Projects/wpcore/app/public/wp-content/themes/astra
> wp-env "run" "cli" "wp" "plugin" "install" "gutenberg"

⠋ /Users/Nik/Projects/wpcore/app/public/wp-content/themes/astra/.wp-env.json
9c90d286a625a650e4f4ef94e6a9344b
/Users/Nik/.wp-env/9c90d286a625a650e4f4ef94e6a9344b
ℹ Starting 'wp plugin install gutenberg' on the cli container.

Creating 9c90d286a625a650e4f4ef94e6a9344b_cli_run ... done
Warning: gutenberg: Plugin already installed.
Success: Plugin already installed.
✔ Ran `wp plugin install gutenberg` in 'cli'. (in 4s 724ms)
```

Also tried passing `--` separately which did at first recognise the --activate flag but does not actually run it - 

```
> $ npm run wp-env run cli wp plugin install gutenberg -- --activate

> astra@3.6.2 wp-env /Users/Nik/Projects/wpcore/app/public/wp-content/themes/astra
> wp-env "run" "cli" "wp" "plugin" "install" "gutenberg" "--activate"

ℹ Starting 'wp plugin install gutenberg' on the cli container.

Creating 9c90d286a625a650e4f4ef94e6a9344b_cli_run ... done
Installing Gutenberg (10.8.2)
Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.
Downloading installation package from https://downloads.wordpress.org/plugin/gutenberg.10.8.2.zip...
The authenticity of gutenberg.10.8.2.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
✔ Ran `wp plugin install gutenberg` in 'cli'. (in 13s 542ms)
```

## Step-by-step reproduction instructions

In https://github.com/WordPress/gutenberg/issues/32784#issuecomment-866711815 I also noticed that it is missing the `-e` flag, so probably `-` or `--` both flags are not being passed forward to docker.

## Expected behaviour
- The executed commands run as expected.

## Actual behaviour
- The commands that are run in the container ignore the flags `-` and `--`

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: MacBook Pro
- Operating system: MacOS 11.4
- Browser:

**Comment by Mamaduka** [comment]
It might be related to #30466.

**Comment by Luehrsen** [comment]
`> $ npm run wp-env run cli "wp plugin install gutenberg --activate"`

Wrapping the command in quotation marks usually does the trick.

**Comment by Mamaduka** [comment]
Hello, @Nikschavan

As @Luehrsen mentioned, wrapping command in quotation marks is required in similar cases.

The `wp-env run` commands help texts mentions this, but it's easy to miss.

I'm going to label this as a documentation issue.

Thanks for bringing this up.

**Comment by francisei** [comment]
Hi, first time contributor, and happy to update the doc for this issue. But I don't see how to assign this issue to myself. Is this a permission issue?

**Comment by Mamaduka** [comment]
Thanks for contributing, @francisei. I'm going to assign the issue to you.
