### ISSUE TITLE
Post Terms Block: automatically add all public taxonomies as variations

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#32924]
Somewhat related to #32920 

If themes or plugins register custom public taxonomies to be used to display custom information on a site's frontend, I think it would make sense to offer that information via the Post Terms block, so one can use the block in the site editor to inject that information in their templates.

Plugins can register those custom variations on their end as well, but maybe offering them in the editor out of the box as long as the taxonomies as marked as public would help with all existing plugins out there.

**Comment by paaljoachim** [comment]
Check out the PR by @ntsekouras Nik here:
https://github.com/WordPress/gutenberg/pull/39837

It can use some testing.

**Comment by mrleemon** [comment]
Apparently, this only works if one registers the custom taxonomies using the `init` hook with a priority lower than 10. Is this by design? I don't see this issue specified anywhere in the Gutenberg docs.

@ntsekouras
