### ISSUE TITLE
Post Terms Block variations: incorrect information in block sidebar

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#32920]
## Description

When registering a custom variation of the Post Terms Block using the block variations API, the title, description, and icon I provide are not used everywhere in the editor UI.

## Step-by-step reproduction instructions

1. Start from a site that uses a custom taxonomy such as `trakt_show` in my example below.
2. With the latest version of WP and Gutenberg, edit one of your site's templates, such as the single post template.
3. Use the Post Terms block to add the post' category to the template; everything works.
4. Using the code snippet below, register a new variation of the Post Terms block.
5. You can now see that new variation in the inserter:

<img width="185" alt="Screenshot 2021-06-23 at 13 40 54" src="https://user-images.githubusercontent.com/426388/123091675-ed9a6b80-d429-11eb-858a-67e58b09f7ff.png">

However, the variation doesn't use the correct icon, title, or description in the block sidebar nor in the block toolbar:

<img width="394" alt="Screenshot 2021-06-23 at 13 41 11" src="https://user-images.githubusercontent.com/426388/123091775-086ce000-d42a-11eb-94b6-c2195b058cb4.png">
<img width="320" alt="Screenshot 2021-06-23 at 13 41 06" src="https://user-images.githubusercontent.com/426388/123091781-099e0d00-d42a-11eb-979f-81c1fe3eedb0.png">

Did I miss something with my snippet below, or is that an issue with the block itself?

Thank you!

## Code snippet (optional)

```js
wp.blocks.registerBlockVariation(
	'core/post-terms', {
		name: 'show',
		attributes: { term: 'trakt_show', },
		title: 'TV Show',
		description: 'display the show that episode belongs to',
		icon: 'video-alt',
	}
);
```

## WordPress information
- WordPress version: 5.8-beta3-51218
- Gutenberg version: trunk, as of June 23, 2021
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme? No

## Device information
- Device: Desktop
- Operating system: macOS
- Browser: Chrome

**Comment by ntsekouras** [comment]
Hey 👋 - you have missed the `isActive` prop. Check the docs here: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/

Basically you just have to add to your variation declaration the below line.
```
isActive: ( blockAttributes ) => blockAttributes.term === 'trakt_show',
```

**Comment by jeherve** [comment]
Thank you!
