### ISSUE TITLE
Focus outline for sidebar does not update when expanded

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#32932]
## Description
When a sidebar is closed and then expanded, the focus outline does not expand with the sidebar.

## Step-by-step reproduction instructions
1. Go to the Widgets admin screen.
2. Click on a sidebar (not a block within the sidebar) and observe the outline around the entire sidebar.
3. Collapse the sidebar.
4. Expand the sidebar.

## Expected behaviour
The focus outline should expand with the sidebar.

## Actual behaviour
The outline remains only on the sidebar title bar.

## Screenshots or screen recording (optional)
![Step 2](https://user-images.githubusercontent.com/359867/123128133-e323a600-d418-11eb-9f53-a2a9945ac40d.png)
![Step 3](https://user-images.githubusercontent.com/359867/123128172-eae34a80-d418-11eb-9ab4-d858c8b694c4.png)
![Step 4](https://user-images.githubusercontent.com/359867/123128202-f171c200-d418-11eb-99c3-81884b06c996.png)

## WordPress information
- WordPress version: 5.8 beta 3
- Gutenberg version: 10.9.0 RC1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: MacOS 10.15.x
- Browser: Firefox

**Comment by talldan** [comment]
Thanks for reporting. This isn't a bug, the header area of the panel is a `<button>` (correctly so), and it has focus after being clicked on.

Making the entire panel have the focus outline would be incorrect.
