### ISSUE TITLE
Widget area highlight disappears when opening the block inserter on the Widgets screen

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#32933]
## Description
When the block inserter is opened on the widget screen, it's not clear where the block will be inserted. It seems that the sidebar most recently interacted with is used when inserting. This becomes especially confusing when the inserter is opened after interacting with another element on the screen (such as clicking Update, or adjusting settings), or when there are multiple widget areas with lots of widgets and the user has scrolled the "active" sidebar out of focus. The editor will jump to the inserted block, but it may not be where the user intended to insert the block.

## Step-by-step reproduction instructions
1. Go to the Widgets screen.
2. Click on a sidebar.
3. Open the block inserter.
4. Observe the outline disappears

## Screenshots or screen recording (optional)
![Focus on sidebar](https://user-images.githubusercontent.com/359867/123131465-b755ef80-d41b-11eb-8561-a52c0e349366.png)
![No focus on sidebar with block inserter open](https://user-images.githubusercontent.com/359867/123131476-b9b84980-d41b-11eb-915e-88d5a381c125.png)

## WordPress information
- WordPress version: 5.8 beta 3
- Gutenberg version: 10.9.0 RC1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: MacOS 10.15.x
- Browser: Firefox nightly.

**Comment by noisysocks** [comment]
I don't think this is a bug. The blue outline denotes which element is focused. When the inserter is opened, the inserter's search field is the element that has focus. 

We provide hints as to where the block will be inserted by e.g. showing a blue horizontal line when the user hovers over a block in the inserter.

Also noting that this is not specific to the widget editor. You can see the same behaviour when selecting a Group block and then opening the inserter.
