### ISSUE TITLE
Error reported by user

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3293]
This came in from the feedback form, reported by @janw-oostendorp:

> Newly installed gutenburg via the wp-admin, fully updated, turned off all plugins.  FF56 ubuntu  get this error in the console:    TypeError: e.capabilities is undefined  Stack trace:  value/<@https://home.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1507663684:39:3650  n@https://home.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1507663684:6:47271  r@https://home.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1507663684:6:45579  value@https://home.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1507663684:39:3627  value@https://home.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1507663684:39:3773  k@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:44:98  beginWork@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:47:371  e@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:18:365  k@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:19:366  Q@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:20:355  ed@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:24:374  fb@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:23:397  enqueueSetState@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js:52:440  y/r.prototype.setState@https://home.janw.me/wp-content/plugins/gutenberg/vendor/react.min.6b26329b.js:16:370  value@https://home.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1507663684:6:229119  value/<@https://home.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1507663684:6:230165  E/</<@https://home.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1507663684:6:156274  E/<@https://home.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1507663684:6:156144  u@https://home.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1507663684:6:159847

**Comment by karmatosed** [comment]
I have tried to recreate this. If you can please let us know, I am closing it though incase this is resolved in the latest version.

**Comment by aduth** [comment]
>TypeError: e.capabilities is undefined Stack trace

At a glance, this _sounds_ as though it could be a permissions issue on getting the capabilities for a specific user. There are a number of places where we perform these checks (e.g. determining which authors to show in the Author dropdown), and while these requests _do_ fail (see Forbidden responses in Developer Tools Network tab), they are expected to do so gracefully. In my testing, there is are no errors like that shown in the original comment while using Gutenberg as a contributor.

If this is still an issue, I would request:

- What role is assigned to the user suffering from this issue?
- What were the specific steps leading up to this error?

**Comment by janw-oostendorp** [comment]
No don't see it anymore since 1.5

**Comment by janw-oostendorp** [comment]
So Ubuntu FF 58.0

I get the error again
`TypeError: e.capabilities is undefined`
```
c/o<@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13421
n@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:21464
c@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:17626
c@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13398
beginWork@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:398
d@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393
f@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214
g@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462
t@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3
x@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247
r@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:164:368
v@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:163:278
enqueueSetState@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:124:386
p.prototype.setState@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react.min.ca6e2421.js:18:82
value@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:337808
value/<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:338975
E/</<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:49155
E/<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:49025
u@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:52658

```

So I check chromium (63.0.3239.84) and I get an other error
```
TypeError: Cannot read property 'level_1' of undefined
    at https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13443
    at n (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:21464)
    at c (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:17635)
    at c (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13401)
    at beginWork (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:398)
    at d (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393)
    at f (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214)
    at g (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462)
    at t (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3)
    at x (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247)
```

Deactivated all plugins, Switched to a blank twentyseventeen.  
A freshly installed site. The user was an admin (no custom roles)

Only 404 I get is on the vimeo Oembed `https://munchkin.janw.me/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fvimeo.com%2F22439234&_wpnonce=a3d4497be1`

I just open the demo page, I do see a flash of the demo page, then white screen with error.
The same with a classic post with just the title _test_ and content _test_

Anything else I can check?
