### ISSUE TITLE
theme.json - defining styles with variable no longer shows selection in global styles panel

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#32941]
## Description

Previously prior to 10.9 one could define styles in the theme.json with variables and the selection would be shown as checked in the global styles panel.

Now with 10.9 the style must be explicitly defined for the selection to be shown in the global styles panel.

An example would be defining the background color like so (this did previously show the white color checked):
```
"styles": {
    "color": {
        "background": "var(--wp--preset--color--white)"
```

Now though it has to be defined like this (it does not show the white color checked unless defined like this):
```
"styles": {
    "color": {
        "background": "#ffffff"
```

## WordPress information
- WordPress version: 
- Gutenberg version: 10.9
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Various themes, all same result

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by stacimc** [comment]
Thanks for reporting. Are you able to reproduce this after installing and activating the newest version of Gutenberg that is available through the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

I am unable to reproduce the bug you're seeing when I test against the newest version of Gutenberg, 11.3.0. When I define background color in `theme.json` like this:

```
"styles": {
    "color": {
        "background": "var(--wp--preset--color--white)"
```

I see the white background color on my site as expected, and the selection is checked in the Global Styles panel:
<img width="274" alt="Screen Shot 2021-08-27 at 9 43 04 AM" src="https://user-images.githubusercontent.com/63313398/131161305-4e0a32e4-98b2-41ca-8ed6-9cac311260ec.png">

**Comment by Sandstromer** [comment]
@stacimc thanks for reminding me of this issue. It seems to work as expected now in the latest release, so I'll go ahead and close this.
