### ISSUE TITLE
The class when placing a block is not the same as the class when changing the style and then changing it back.

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#32946]
The class when placing a block is not the same as the class when changing the style and then changing it back.

## Description

The class when placing a block is not the same as the class when changing the style and then changing it back.

For example, in the case of a Quote block, it will look like this

■ The moment the block is placed (Default)
`wp-block-quote block-editor-block-list__block wp-block is-selected
`

■ When you click on Large style
`wp-block-quote is-style-large block-editor-block-list__block wp-block
`

■ Once you click on Large style, change it back to Default.
`wp-block-quote is-style-default block-editor-block-list__block wp-block
`

Notice the is-style-〇〇 after wp-block-quote.

## Expected behaviour

Can't I make this the Default style when I place the block?

I'm having trouble when I want to change the default to Large style.

**Comment by shimotmk** [comment]
This issues has run into the same problem in the past.
https://github.com/WordPress/gutenberg/pull/23548

**Comment by talldan** [comment]
Thanks for reporting the problem. This was already reported in #20706, so I'll close this issue.
