### ISSUE TITLE
Image block error 'limitExceeded' (Gutenberg 10.9.0 & FSE)

### ISSUE THREAD

**Issue by hawkmusician** [WordPress/gutenberg#32949]
## Description
When adding or modifying the image block (or any custom block using media-view.js) the block encounters an error and cannot be used. This only happens in FSE.

## Step-by-step reproduction instructions

1. Go to FSE
2. Add an image block or gallery block
3. Directly encounter the error.

## Screenshots or screen recording

<img width="604" alt="Screenshot 2021-06-24 at 10 28 25" src="https://user-images.githubusercontent.com/23136551/123231944-f8f8a000-d4d8-11eb-8349-59ba84d16f8a.png">

## WordPress information
- WordPress Version 5.7.2
- Gutenberg version 10.9.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme Yes

**Comment by bobbingwide** [comment]
Is this the only message you saw? My Site Logo block crashed in the Site Editor and I got many other messages after this one.

**Comment by skorasaurus** [comment]
I'm able to reproduce an error using the steps outlined above but my error is different.; 

my error is below: _"Uncaught TypeError: wp.Uploader is undefined"_

full error message is at https://gist.github.com/skorasaurus/11195cc75a4185630ce3c82232fdccd6
