### ISSUE TITLE
Post grid title color & excerpt color issue

### ISSUE THREAD

**Issue by Ranjeet3131** [WordPress/gutenberg#32954]
In Gutenberg post grid block title color and excerpt color are not working...

**Comment by skorasaurus** [comment]
Hi, 

This issue tracker is only for blocks that come with Gutenberg by default. There aren't any blocks named "post grid" that come with Gutenberg by default. There are several blocks created by others in the WordPress community that are named post grid including https://atomicblocks.com/blocks/post-grid-block/ and https://ultimategutenberg.com/docs/post-grid/
If you are referring to either of those, please contact them for support. 

Please reopen if you are referring to one of the 'core' blocks listed at https://wordpress.org/support/article/blocks/
