### ISSUE TITLE
Styling issues with legacy widget form.

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#32955]
## Description
Styling of legacy widget is off as core CSS styles are not applied. Take this example from the [web stories](https://wordpress.org/plugins/web-stories/) plugin

<img width="507" alt="Screenshot 2021-06-24 at 11 29 08" src="https://user-images.githubusercontent.com/237508/123253003-d8cede00-d4e4-11eb-9b02-9cc16fadb709.png">

Compared the original view. 

<img width="355" alt="Screenshot 2021-06-24 at 12 09 54" src="https://user-images.githubusercontent.com/237508/123253205-20556a00-d4e5-11eb-8ad5-5150b4ba0372.png">

List of issues include.
- Strange font selection. As inputs are wrapped in P tags. 
- `.widefat` not applying to select menus. 
- Labels are bold
- Spacing issues. 

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by spacedmonkey** [comment]
<img width="506" alt="Screenshot 2021-06-24 at 12 26 37" src="https://user-images.githubusercontent.com/237508/123255375-ad012780-d4e7-11eb-9aa8-3b5889fd3bdc.png">
Another example from polylang plugin

**Comment by spacedmonkey** [comment]
Reopening as styling for select and input type number are still off, also issue is not resolved. 

<img width="1904" alt="Screenshot 2021-06-25 at 17 13 15" src="https://user-images.githubusercontent.com/237508/123510708-e61ad280-d674-11eb-98f3-24330e8404d3.png">

**Comment by spacedmonkey** [comment]
CC @noisysocks  @tellthemachines as this issue is not resolved.

**Comment by spacedmonkey** [comment]
The issue here is selectors are overriding core selectors. So `.editor-styles-wrapper select` is more precise than `.wp-core-ui select` because is on body class. The fix is simple, change one or both selectors.

**Comment by adamziel** [comment]
It's worth pointing out that this is only a problem when using specific themes, e.g. on Twenty Twenty, but not on Twenty Twenty One.

**Comment by adamziel** [comment]
Perhaps something has changed in the meantime, but I now see that `select` fall under `.wp-block-legacy-widget__edit-form .widget-inside.widget-inside select` which makes them look consistent with other inputs:

<img width="1743" alt="Zrzut ekranu 2021-06-28 o 15 50 08" src="https://user-images.githubusercontent.com/205419/123647765-a7c61480-d828-11eb-8181-f8fab8236ace.png">

The visual issues that still stand out to me are:
* No spacing between labels and their related form fields
* Slightly different margin in that first input type=text
* Quite large spacing between form rows

**Comment by adamziel** [comment]
It is similar but a little bit different on Twenty Twenty:

<img width="1686" alt="Zrzut ekranu 2021-06-28 o 15 53 44" src="https://user-images.githubusercontent.com/205419/123648220-0e4b3280-d829-11eb-81ab-07ddae3e0a0a.png">

**Comment by adamziel** [comment]
About this large spacing between checkboxes:

<img width="655" alt="Zrzut ekranu 2021-06-28 o 15 55 48" src="https://user-images.githubusercontent.com/205419/123648590-59654580-d829-11eb-91f0-24deb0369b27.png">

Each checkbox is wrapped a separate `<p>` and is a subject to the same margin as all other paragraphs. I think the only generic way of solving that is setting that margin to a lower value like 10px.

**Comment by adamziel** [comment]
The spacing issue here is due to a low line-height value:

<img width="664" alt="Zrzut ekranu 2021-06-28 o 16 00 22" src="https://user-images.githubusercontent.com/205419/123649421-05a72c00-d82a-11eb-9527-e8d6cf1dae5a.png">

My current idea is to increase it for `label` tags inside the widget editor
