### ISSUE TITLE
Unable to apply bold

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3295]
Reported via feedback form by @jeffpaul:

"When editing a Paragraph block, a bold bulleted item is unable to have a link added to it. Note that switching to the HTML view, adding the A HREF tag, and then switching back to the TEXT view shows a bold bulleted hyperlinked item as expected."

**Comment by aduth** [comment]
>When editing a Paragraph block, a bold bulleted item

Is this a paragraph block, or a freeform block from content created in the Classic editor?

Paragraphs shouldn't include list items.

**Comment by karmatosed** [comment]
Closing as I can’t replicate.

**Comment by jeffpaul** [comment]
Apologies, I created a Paragraph block and used the `*space` to get a bulleted list started and didn't realize it automatically changed the block into a List block. Regardless, the issue appears to be resolved in my testing on the Gutenberg instance on Make/Core (uncertain on the version it's using).
