### ISSUE TITLE
Chrome: Editor has changes after Save Draft finishes

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3296]
Suspected regression of #3178

## Issue Overview

When saving a draft for a post containing block content, the post is flagged as needing to be saved even after save completes.

## Steps to Reproduce (for bugs)

1. Navigate to Posts > Add New
2. Click writing prompt to add a new paragraph block
3. Click Save Draft

## Expected Behavior

After save completes, "Saving..." label replaced with "Saved"

## Current Behavior

After save completes, "Saving..." label replaced with "Save Draft" button. Attempting to navigate away prompts the user to save their changes.

## Possible Solution

The [`isEditedPostDirty` selector](https://github.com/WordPress/gutenberg/blob/35fcb3244afc1363cdb303158309f32a061ee95f/editor/selectors.js#L177-L226) compares present blocks in state against the original history of the post. Prior to #3178 the history would be reset at each save, meaning that present blocks would match and the post flagged as "clean" after a save completes. With #3178 removing this reset, we need to update the selector or state to reflect an original state of editor blocks from the latest save.

## Related Issues and/or PRs

Related: #3178

**Comment by dartiss** [comment]
I'm intermittently seeing this on Safari too but can't recreate sufficiently well.

Even when I'm not experiencing this, after saving, the message always goes back to 'Save Draft', even when I can then navigate away fine and everything has saved. Is this correct?

**Comment by aduth** [comment]
>Even when I'm not experiencing this, after saving, the message always goes back to 'Save Draft', even when I can then navigate away fine and everything has saved. Is this correct?

Not correct as in desired behavior, but this is what I would expect for you to experience with this bug being present, yes. It should also prompt you about unsaved changes, even when there are none.

**Comment by rishirdua** [comment]
I'm still seeing this but this issue has been marked as fixed.

**Comment by aduth** [comment]
@rishirdua More information is needed to debug. Can you leave a comment at #4687 which is an open variation of this issue, providing at least the active plugins on the site, whether it occurs consistently, and the type of content in the posts where the prompt is shown.
