### ISSUE TITLE
Widget Editor: Function-based widgets don't render and don't save

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#32960]
## Description
The widgets editor doesn't play nicely with a function-based marquee widget. Presumably, this is a problem also for other function-based ("reference") widgets.

## Step-by-step reproduction instructions

1. Add the [marquee widget](https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1) to your WP installation
2. Go to the widgets editor and add marquee
3. Try to save the form

## Expected behaviour
1. Everything gets saved buttery smooth.
2. The Marquee widget shows up in the "inactive" panel as it used to in the old editor:

<img width="1626" alt="Zrzut ekranu 2021-06-24 o 16 54 17" src="https://user-images.githubusercontent.com/205419/123284862-de401e80-d50c-11eb-9f70-76c764725540.png">

## Actual behaviour
1. The form doesn't render. Then it doesn't get saved. The marquee isn't previewed. Saving the entire widgets screen produces a notice with an error.
2. The widget can't be seen in the "inactive" panel

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/205419/123277452-6a027c80-d506-11eb-960b-6c47cf8550cd.mov

**Comment by adamziel** [comment]
Once I opted out of the block-based widgets editor with `add_filter( 'use_widgets_block_editor', '__return_false' );`, I saw the marquee widget in the "Inactive" section of the old widgets editor. From that moment on, it also started showing up in the new editor (`wp_get_sidebars_widgets()` started returning `marquee_greeting` when it wouldn't previously). There must be a write operation somewhere in the legacy editor that adds such "missing" widgets to the inactive section.

**Comment by getdave** [comment]
> function-based marquee widget

What is a "function based widget"? Looking at https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1 I assume it's literally a Widget that is created using a function rather than a `class`?

**Comment by adamziel** [comment]
@getdave you got it right! There's a bunch of logic specific to this kind of widgets in WordPress core.

After resetting my wp-env, the marquee greetings showed up in the "Available widgets" section of the legacy editor, not in the "inactive widgets" section 🤔 

<img width="523" alt="Zrzut ekranu 2021-06-24 o 17 46 20" src="https://user-images.githubusercontent.com/205419/123293250-20209300-d514-11eb-9033-54e7ffc5382d.png">

It was picked up from the `$wp_registered_widgets` global.

**Comment by adamziel** [comment]
One problem is how the marquee widget triggers a request to `/wp/v2/widgets/marquee_greeting` where we assume that `is_null( $sidebar_id )` means there is no widget with a given ID and return 404:

https://github.com/WordPress/gutenberg/blob/77331534b2dee915667519b9252db4f9a4d08bae/lib/class-wp-rest-widgets-controller.php#L155-L161

This assumption holds for widgets implemented using classes
