### ISSUE TITLE
Error log related to `react-native-gesture-handler` when executing the tests

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#32964]
## Description

We're getting the following error log when executing the tests:
```
react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).
```

I'd like to note that the error doesn't make the tests fail but still, this is something that we should address.

## Step-by-step reproduction instructions

1. Run the command: `npm run native test`
2. Observe that the mentioned log is displayed in the console

## Expected behaviour

Tests shouldn't log any errors.

## Actual behaviour

Tests are logging errors.

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: N/A
- Operating system: N/A
- WordPress app version: `37e9870f8af8143d29b88906d4a2e69d99f1fc86`

**Comment by fluiddot** [comment]
While implementing new unit tests in GB-mobile, I encountered this error when I added the following code to the test:
```
beforeEach( () => {
	jest.resetModules();
} );
```

I have the gut feeling that tests might be triggering `jest.resetModules();` somehow. I haven't found any code trace to this function, so most likely it's called from a testing library we're using.

`resetModules` documentation reference: https://jestjs.io/docs/jest-object#jestresetmodules

**Comment by geriux** [comment]
Hey @fluiddot 👋 do you think this is still relevant? I haven't encountered this and since we've updated the library I wonder if it can be closed or not. What do you think?

**Comment by fluiddot** [comment]
> Hey @fluiddot 👋 do you think this is still relevant? I haven't encountered this and since we've updated the library I wonder if it can be closed or not. What do you think?

Yeah, I think we can close it. As you mentioned, after updating the library the error is no longer shown 🎊 .
