### ISSUE TITLE
Widget editor: In customizer, wide, tall widgets display poorly

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#32973]
## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. [Get Genesis](https://www.studiopress.com/get-genesis/) & [Genesis Sample](https://github.com/studiopress/genesis-sample)
2. Go to Customizer > Widgets
3. Add a Genesis - Featured Posts widget to a widget area.
4. Note the position and whether all settings are accessible. Settings may be cut off on the top or bottom depending on the position of the widget.
5. Note the width of the widget and field display. It is narrower than the non-block-based widget areas.

## Expected behaviour

Legacy widget settings will always be accessible & form will display similarly to previous display.

If the height wasn't enough, the widget was scrollable in the non-block-based widget areas in the customizer. (It's not currently scrollable due to https://github.com/WordPress/gutenberg/issues/32969.)

## Actual behaviour

The Genesis - Featured Post widget is:
- Narrower, so settings don't fit nicely.
- Positioned too high or too low to see or reach all settings.
- Not scrollable so settings are reachable.

## Screenshots or screen recording (optional)

Original:

![Screen Shot 2021-06-24 at 3 48 55 PM](https://user-images.githubusercontent.com/1271053/123330047-8228ca80-d50b-11eb-9351-2c031cd3d630.png)

Block-based at the top:

![Screen Shot 2021-06-24 at 3 08 46 PM](https://user-images.githubusercontent.com/1271053/123330372-efd4f680-d50b-11eb-8a20-860981cb67f6.png)

Block-based pushed down:

![Screen Shot 2021-06-24 at 3 23 33 PM](https://user-images.githubusercontent.com/1271053/123330404-f6fc0480-d50b-11eb-8834-51be3dde33df.png)

Even if we were to fix https://github.com/WordPress/gutenberg/issues/32969 in Genesis Framework, the position may not be correct:

![Screen Shot 2021-06-24 at 5 37 26 PM](https://user-images.githubusercontent.com/1271053/123335838-06cb1700-d513-11eb-9750-7155f7f4a6b9.png)

## Related
- https://github.com/WordPress/gutenberg/issues/32210

## WordPress information
- WordPress version: 5.8-beta3-51224
- Gutenberg version: Not installed"
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No - [Get Genesis](https://www.studiopress.com/get-genesis/)

## Device information
- Device: Mac
- Operating system: MacOS 10.15.x
- Browser: Chrome 91

**Comment by talldan** [comment]
Thanks for reporting this! https://github.com/WordPress/gutenberg/pull/31736 was the previous improvement to wide widgets, looks like a few additional adjustments will be needed.

**Comment by tellthemachines** [comment]
There are two separate issues here:

1. The popover is partially cut off and not scrollable - this is due to the popover not containing the floated contents, and can be fixed easily. 
2.  The popover is too narrow - this is due to the widget itself not defining its width. This should be fixed in the theme/plugin supplying the widget, as wide widgets can come in many shapes and sizes so it would not be appropriate to set a width for them in the Customizer. At best we can set a min-width, but this is unlikely to work well for all cases.

**Comment by johnstonphilip** [comment]
@tellthemachines If an old plugin has to update its code (like to set widgets widths) in order to fix a new problem that never existed before, than this is not really backwards compatible, no?

**Comment by tellthemachines** [comment]
@johnstonphilip backward compatibility is ensured to the extent that these widgets are now usable, and we have also made it possible for themes to opt out of the new widgets editor.
