### ISSUE TITLE
Sticky autocomplete

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#32986]
Using the Gutenberg 10.9.0 plugin and Twenty Nineteen I get a sticky autocompleter when editing a post consisting of a single `@`. Once the autocompleter has appeared it doesn't disappear until I press space.

![screencast 2021-06-25 12-52-23](https://user-images.githubusercontent.com/1277682/123421160-688f8d80-d5b4-11eb-9f88-bd8a32edb918.gif)

This is in contrast to earlier versions of Gutenberg (maybe <10.7.0) where the autocompleter disappeared.

WordPress 5.7.2 / Chrome 91.0.4472.106 / Gutenberg 10.9.0 plugin

**Comment by johngodley** [comment]
I'll note that, although it's not shown in the GIF animation, the autocompleter seems to appear twice when first clicked (or the animation effect occurs twice, anyway).

**Comment by ellatrix** [comment]
I can reproduce now. I'll look into it.

**Comment by ellatrix** [comment]
Btw, @fullofcaffeine already bisected this and pinpointed it to #31718. The problem is that previously we had a `isSelected` check. I'll make a PR to check the selection.

**Comment by ellatrix** [comment]
![autocomplete](https://user-images.githubusercontent.com/4710635/123423696-8bc43800-d5c8-11eb-85b3-ae92dc18e418.gif)

It looks like there's two popovers being rendered. One is removed when rich text is no longer selected. I'm not sure where the other one is coming from.
