### ISSUE TITLE
The "Apply duotone filter" button on image block-related toolbar shifts to the end after setting image to be centered

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#32981]
## Description

When you add new image block then an additional icons set is added to toolbar with icons related to image / image block. The initial order of these buttons changes when you set image to be centered.

## Step-by-step reproduction instructions

1. Create any block image and insert any image from media library or other source into it
2. Observe related icons order: (a) duotone filter, (b) alignment, (c) edit link, (d) crop and (e) add text
3. Click second button to change image's alignment to centered
4. Observe icons order again: (a) alignment, (b) edit link, (c) crop, (d) add text and (e) duotone filter

## Expected behaviour

Icons order should remain the same until very end of the world. The "Apply duotone filter" button should always (from the very first moments of adding image block) be last, as very rarely used functionality.

## Actual behaviour

The "Apply duotone filter" button appears first when creating image block and switches to the last position only after changing alignment of the image.

## Screenshots

![one](https://user-images.githubusercontent.com/60975060/123391718-979a0500-d59c-11eb-889c-2da77a588a86.png)

![two](https://user-images.githubusercontent.com/60975060/123391743-9c5eb900-d59c-11eb-8267-c3c751b9ee5a.png)

## WordPress information
- WordPress version: _5.7.2_
- Gutenberg version: _Version 10.9.0 | By Gutenberg Team_
- Are all plugins except Gutenberg deactivated? _No_
- Are you using a default theme (e.g. Twenty Twenty-One)? _No_

## Device information
- Device: _PC_
- Operating system: _Windows 10 10094_
- Browser: _Chrome Version 91.0.4472.114_

**Comment by jasmussen** [comment]
Thanks for the report, this definitely needs to be fixed! lt's tracked in #31373 also, so I'm closing this one in favor of that.
