### ISSUE TITLE
Images in FSE mode with disabled lazy loading have loading="lazy" attributes

### ISSUE THREAD

**Issue by rufus87** [WordPress/gutenberg#32987]
## Description
Any image rendered by `wp_get_attachment_image` function that has `["loading" => false]` configuration to disable it is loaded with `loading="lazy"` attribute. This happens, because `gutenberg_get_the_template_html()` function calls to `wp_filter_content_tags` function which adds `loading="lazy"` by default on all images without exceptions. Even if a single image is required to be rendered without lazy support, it is rendered with lazy support.

## Step-by-step reproduction instructions
1. call `wp_get_attachment_image($image_id, 'full', false, ["loading" => false])`
2. check rendered image HTML

## Expected behaviour
Images with disabled lazy loading should not have `loading="lazy"` attributes

## Actual behaviour
All images without exceptions have `loading="lazy"` attributes im FSE mode

## Screenshots or screen recording (optional)
![Screenshot_1](https://user-images.githubusercontent.com/10531492/123426776-dfd51980-d5d4-11eb-9d35-ccccf01f338f.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.9.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Google Chrome 91.0.4472.114 (Official Build) (64-bit)

**Comment by Thelmachido** [comment]
Hi! As there hasn’t been any movement on this issue in a year, I’ve marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by kathrynwp** [comment]
@rufus87 I'm going to go ahead and close this out, but if you are still experiencing the original issue with the latest version of WP, please do feel free to add a comment with additional details and I’ll be glad to reopen it.
