### ISSUE TITLE
ServerSideRender refreshes more than usual with custom response situations

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#32998]
ServerSideRender generally refreshes the content on changing attributes.
It gives [three options](https://github.com/WordPress/gutenberg/blob/1be105906f30dc623d9f7e1f4d192744d41cff71/packages/server-side-render/src/server-side-render.js#L142) `LoadingResponsePlaceholder ` ,`EmptyResponsePlaceholder ` and `ErrorResponsePlaceholder `, that developers can render custom element for them.

But they make too many requests to refresh, `on hover` , `on blur` or `on focus` it will refresh the result without any reason I checked that happens when one or more of mentioned options are used.

## The comparison makes the problem clear:

This is the code I'm using here:
```js
<ServerSideRender
     ...
     LoadingResponsePlaceholder={() => {
         return <img src="https://i.gifer.com/origin/fd/fdf70f5f4989f9c08f033da50c38170e.gif" alt=""/>
     }}
     ...
/>
```

### In this video <ServerSideRender> does not have any of  them.
https://user-images.githubusercontent.com/64708228/123472139-04001d00-d60c-11eb-8fcd-637e5ec2788b.mp4

### It happen when any of them has custom HTML:
https://user-images.githubusercontent.com/64708228/123472867-fd25da00-d60c-11eb-8e02-c66a6a1fe415.mp4

**Comment by Mamaduka** [comment]
Hi, @amir2mi

Passing a function for those props doesn't work so well, as React treats that as a new component on every render. The `ServerSideRender` compares props to re-fetch data, and the component is refreshed more often.

https://github.com/WordPress/gutenberg/blob/a6314ffd2d87e55ac8bafa6be668027da4d894d3/packages/server-side-render/src/server-side-render.js#L137-L139

I would recommend extracting your custom placeholder in components and passing them as props.

```js
function MyLoadingPlaceholder() {
	return <img src="https://i.gifer.com/origin/fd/fdf70f5f4989f9c08f033da50c38170e.gif" alt=""/>;
}

function MyServerSideRenderer() {
	return (
		<ServerSideRender
			LoadingResponsePlaceholder={ MyLoadingPlaceholder }
		/>
	);
}
```

**Comment by amir2mi** [comment]
Hi @Mamaduka, Thanks for the tip! That solved the problem I unfortunately did not pay much attention to default placeholders.
Does not it worth mention or add this in documentation?

**Comment by Mamaduka** [comment]
Happy to hear that.

I already created PR for documentation update - #33030.

**Comment by amir2mi** [comment]
Thanks again so I close this issue.
