### ISSUE TITLE
Widgets Editor: Wide widgets always open

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#32996]
## Description

When updating to **5.8-beta4-51243**, wide widgets are always open due to `display: flow-root;` https://github.com/WordPress/gutenberg/pull/32976/commits/42910eb526238ae304fa672122e5c5165765c65f

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. [Get Genesis](https://www.studiopress.com/get-genesis/) & [Genesis Sample](https://github.com/studiopress/genesis-sample)
2. Go to Customizer > Widgets
3. Add multiple Genesis - Featured Posts widgets to a widget area.
4. See whether or not they close.

## Expected behaviour
Wide legacy widgets will only be open when editing settings

## Actual behaviour
Wide legacy widgets are always open.

## Screenshots or screen recording (optional)

There's a lot going on in this, but it shows multiple widgets open after updating to WP Beta 4.

![widgets-open](https://user-images.githubusercontent.com/1271053/123468684-1f453b00-d5c0-11eb-90b8-be68ef5ce47d.gif)

Thanks for your work on 5.8. 

## WordPress information
- WordPress version: 5.8-beta4-51243
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Mac
- Operating system: 10.15.x
- Browser: Chrome / Firefox developer

**Comment by draganescu** [comment]
I was able to repro this and it's looking like it is connected to #33006
