### ISSUE TITLE
Query loop block deprecation doesn't actually render post template

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#32999]
## Description
After updating to Gutenberg 10.9.0 my wp:query-loop blocks are no longer working.

The code changes implemented when the `wp:query-loop` block was renamed to  `wp:post-template` are intended to
1. Produce a Warning message 
2. Then render the block using the new logic.

This didn't work since the _built_ code included
```
add_action( 'init', 'gutenberg_gutenberg_register_legacy_query_loop_block' );
```
For Gutenberg blocks I believe the priority should be 20.

When corrected the warning message is produced
```
Warning: Block core/query-loop has been renamed to Post Template. core/query-loop will be supported until WordPress version 5.9. in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-template.php on line 107
```
and the query-block is rendered using the post-template logic.

When not corrected there is only one post displayed; the current post.
 

## Step-by-step reproduction instructions
1. Using Gutenberg 10.8.2 or earlier create a post Query block containing a Query loop
2. View the post. See the correct posts displayed
3. Update to Gutenberg 10.9.0
4.  View the post. See only the current post being displayed where the Query loop should have been run.

## Expected behaviour
The deprecated logic for the query block should kick in. The output should be the same as for step 2.
with the addition of the Warning: message.

## Code snippet (optional)
The problem is because build process for `index.php` files in `webpack.config.js` is not setting the priority to 20.

The function name `gutenberg_gutenberg_register_legacy_query_loop_block` 
doesn't match the search string.
```
// The core blocks override procedure takes place in
// the init action default priority to ensure that core
// blocks would have been registered already. Since the
// blocks implementations occur at the default priority
// and due to WordPress hooks behavior not considering
// mutations to the same priority during another's
// callback, the Gutenberg build blocks are modified
// to occur at a later priority.
.replace(
   /(add_action\(\s*'init',\s*'gutenberg_register_block_[^']+'(?!,))/,
   '$1, 20'
)
```

Renaming the `gutenberg_gutenberg_register_legacy_query_loop_block` function to `gutenberg_register_block_core_query_loop` should resolve the issue.

The code will work again, albeit with an annoying deprecated message.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.9.0
- Are all plugins except Gutenberg deactivated? No 
- Are you using a default theme (e.g. Twenty Twenty-One)? No 

## Device information
- Device: Desktop
- Operating system: Windows 10 
- Browser: Chrome

**Comment by kathrynwp** [comment]
@bobbingwide Thank you very much for this report! I realize that I'm looking at this late, but I just tried to replicate the bug, going from 10.8.2 to the current version of Gutenberg, 13.9.0, with WordPress 6.0.1. I'm not seeing any error on the front end, and the query loop posts are all rendering as expected.

As there haven't been any other reports in the meantime, I'm going to go ahead and close this out as fixed, but if you are still experiencing the issue, please do drop a note with further details and I'll be glad to have another look. Thank you!
