### ISSUE TITLE
Ability to highlight blocks that are wrapped by another block.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#33]
If enough wrapped text is added around an image block, it becomes no longer possible to access the images block level controls.  Adding z-index to the image when in "left-aligned" or "right-aligned" will most likely alleviate that problem.

**Comment by BE-Webdesign** [comment]
This can quickly lead into z-index hell 😉

**Comment by mtias** [comment]
@jasmussen had some thoughts on this. Seems just bumping z-index for floated content would be fine :)

**Comment by BE-Webdesign** [comment]
They can then overlap controls of another element due to the higher z-index.  So we will want to probably have all controls at a z-index of 3, and any "floated" content have a z-index of 2 for now.

**Comment by jasmussen** [comment]
> @jasmussen had some thoughts on this. Seems just bumping z-index for floated content would be fine :)

Copying from Slack:

> this would probably work pretty well if we could z-index the image on top, and perhaps add a white border so it "cuts through" the paragraph block border

@BE-Webdesign:

> They can then overlap controls of another element due to the higher z-index. So we will want to probably have all controls at a z-index of 3, and any "floated" content have a z-index of 2 for now.

Can you elaborate? You'll only ever see the block outlines and formatting controls of any one selected block at any one time, in this prototype.

**Comment by BE-Webdesign** [comment]
@jasmussen 

>You'll only ever see the block outlines and formatting controls of any one selected block at any one time, in this prototype.

Yes, so if you have the controls of the element that is not z-indexed higher active, ( inline controls, adding a new block controls, etc. ) potentially the "floated" content with a higher z-index covers it.  Just came across it, while goofing around with the editor and fixing the z-index. Controls quickly became covered by the new higher priority z-index block.

**Comment by BE-Webdesign** [comment]
Basically, controls should always be on top so they are not hidden, and "floated" blocks should appear at a higher z-index than normal flow blocks.
