### ISSUE TITLE
Bug with Legacy widget preview/edit displaying at the same time

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#33000]
Opening based on a bug was spotted in the Making WordPress Slack: https://wordpress.slack.com/archives/C01D71823PB/p1624646898376200

Legacy widgets are displaying with the both the editing form and the preview (directly below) at the same time: 

![Screen Shot 2021-06-25 at 3 42 22 PM](https://user-images.githubusercontent.com/77359364/123477438-10648580-d5cc-11eb-8e34-7618b7886bc6.png)

Seems like a new one, may have appeared in the last ~24 hours. Thanks!

**Comment by thisissandip** [comment]
For some reason, the `hidden` attribute of the Form element is not working

**Comment by thisissandip** [comment]
PR added: https://github.com/WordPress/gutenberg/pull/33006
