### ISSUE TITLE
CFS WYSIWYG field displays differently in Gutenberg

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#3302]
## Issue Overview 
CFS (Custom Field Suite) WYSIWYG field displays differently in Gutenberg vs. Classic Editor.

## Steps to Reproduce (for bugs)
1. Install and activate Custom Field Suite plugin: https://wordpress.org/plugins/custom-field-suite/.
2. Create a WYSIWYG field and enable for posts/pages.

## Expected Behaviour
The WYSIWYG field will render with equivalent functionality in Classic Editor and Gutenberg.

## Current Behaviour
The WYSIWYG field renders with TinyMCE buttons in Classic Editor and without TinyMCE buttons in Gutenberg.

_Gutenberg 1.6.0
Windows 10
Chrome 61.0.3163.100 (Official Build) (64-bit)_

#### Classic Editor
![cfs-wysiwyg-view-classic-editor](https://user-images.githubusercontent.com/29587253/32304605-8e4e5c98-bfd5-11e7-921f-cd4b8a99f613.jpg)

#### Gutenberg
![cfs-wysiwyg-view-gutenberg](https://user-images.githubusercontent.com/29587253/32304606-8e84d84a-bfd5-11e7-9241-00c52b50413c.jpg)

**Comment by BE-Webdesign** [comment]
Hi @chthonic-ds,

Most likely TinyMCE is not being enqueued properly or something of that nature. I will look into it. Is CFS on the WordPress.org Plugins Repository?

**Comment by chthonic-ds** [comment]
Thanks @BE-Webdesign. The repository link is noted in the issue: https://wordpress.org/plugins/custom-field-suite/.

**Comment by dev4press** [comment]
This is not the issue with this plugin only. Any plugin that uses wp_editor() to embed TinyMCE editor in metaboxes is broken, sometimes completely, in some cases, only TinyMCE Visual tab is broken and Text tab shows toolbar, but no content area.

**Comment by adampatterson** [comment]
This is the same for ACF WYSIWYG fields. It also prevents the Add media, insert images, and add forms from working in using Gravity Forms, and Unsplash Image plugin.

**Comment by sc0ttkclark** [comment]
Yep Pods is broken too. See below for an example, I had to click into Text tab since Visual tab is empty to type that text shown.

http://sc0tt.me/1D1w2P2Q3e1C/Screen%20Shot%202017-11-29%20at%204.01.29%20PM.png

**Comment by nderambure** [comment]
Yep, it's for any metabox with a wp_editor() function call as said by @dev4press.
Too time consuming for me to look into the code, I don't know the tinymce part of WP, either Gutenberg at all, but it's a major issue, no doubt about that.

**Comment by BE-Webdesign** [comment]
I will do my best to resolve this somehow, hopefully before the end of the month.
