### ISSUE TITLE
Default Appender: Add select-state before showing inserter

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#33025]
## What problem does this address?

The default appender component makes it easy to insert a block in its place. But it makes it hard to select the block itself:

![problem](https://user-images.githubusercontent.com/1204802/123602158-c1e7fe80-d7f8-11eb-942c-9b55250444fe.gif)

Additionally, since this particular appender serves as a de-facto placeholder/setup state for some blocks (shown here, empty column and group blocks), the single bare plus icon is perhaps insufficient indication of what you're looking at.

#32108 discusses the same problem and how it affects the Template Part block, and a solution being discussed [in the comments](https://github.com/WordPress/gutenberg/issues/32108#issuecomment-849475428): build in a selection state before the insertion stage (aka. "clickthrough"):

- The resting state shows the type of block and a clickable area
- The selected state surfaces the inserter button

## What is your proposed solution?

Today, preinserted groups and columns look like this:

<img width="740" alt="Setup states   appenders" src="https://user-images.githubusercontent.com/1204802/123604263-f957aa80-d7fa-11eb-8e84-b39f987aeb6b.png">

By adding a selection state first, that resting can state serve both as block indication and clickable area. A click here would surface the inserter:

<img width="1460" alt="Setup states   appenders after" src="https://user-images.githubusercontent.com/1204802/123604393-18eed300-d7fb-11eb-8599-f48e47271e76.png">

Here's a basic prototype:

![prototype](https://user-images.githubusercontent.com/1204802/123604143-db8a4580-d7fa-11eb-9577-fae11d28f7c0.gif)

This **select the block first, then insert** behavior would fix the issue described in #32108. #30116 and #30115 are adjacent, but it's not clear if this pattern will work in those cases.

**Comment by paaljoachim** [comment]
That is really nice, Joen!

Going through the issue step by step.


The new approach in re-selecting a container kind of block. As an example I use the Group block.
Block as been added to the canvas/layout, and de-selected.

None selected state.
Before:

![Default-state-Group-block](https://user-images.githubusercontent.com/5323259/123621249-4cd1f480-d80b-11eb-94bb-6c73d207c776.jpg)

None selected state.
After:
![Default-state-Group-block-new](https://user-images.githubusercontent.com/5323259/123621381-6d9a4a00-d80b-11eb-86c4-ec754e7696a5.jpg)

We are able to right away see which block this is by the label that is added inside the boundary lines of the block.

Reselecting Group block.
Before:

![Reslecting-Group-block](https://user-images.githubusercontent.com/5323259/123621800-e4374780-d80b-11eb-81d7-79b1c1185dcf.jpg)

We assume the user wants to right away add inner content.

Reselecting Group block.
After:
![Reslecting-Group-block-new](https://user-images.githubusercontent.com/5323259/123621843-eb5e5580-d80b-11eb-8598-387950849919.jpg)


It gives a stronger sense of hierarchy informing the user by the initial click that the parent container is selected. The user can then click the + to add the inner content.

---------

Looking at the #32108 issue where de-selecting and reselecting a template part in a new page template is identical to the re-selection process of the Group block as seen above. As with the Group block re-selecting a template part would also benefit from the new suggested method.

-------

Looking at #30116 and #30115 issues where one has added a link but want to delete it, but find it difficult to select the Add a link block added to the Navigation. 

Default not selected state.
Before:
![Screen Shot 2021-06-28 at 12 55 57](https://user-images.githubusercontent.com/5323259/123625673-472add80-d810-11eb-83f8-6612722dd954.png)

Default not selected state.
After:
It should probably look the same.

Clicking the Add a link block (Selected state):
Before:
![Selected-Nav-link-state](https://user-images.githubusercontent.com/5323259/123625934-907b2d00-d810-11eb-8f24-0f822d3a3620.jpg)

Clicking the Add a link block (Selected state):
After:
(A suggestion.)

![Remove-nav-menu-link-new](https://user-images.githubusercontent.com/5323259/123626636-578f8800-d811-11eb-90ad-492904061eb2.jpg)

One clicks the Add a link (block). Block is selected. One can click backspace on the keyboard to remove the link, the 3 dot ellipsis drop down menu to remove the block, or click the + sign to open up the inline inserter to add a menu item.

---------

In a sense this becomes a kind of click through state. Initial click selects the top parent or existing block. User selects to dig into the block by clicking the + or if content is present clicks again to gain access to inner content.

**Comment by paaljoachim** [comment]
It would be great with some feedback on this issue: @critterverse @javierarce @shaunandrews 
Thank you! Have a great day!

**Comment by javierarce** [comment]
I like this solution, especially as it gives a little bit more context to the user, but I miss a couple of things in the prototype: 

- A hover state to indicate that the placeholder is clickable. I guess we could: change the color, the text (Column → Add column), or maybe even replace the content with the inserter or a variation.
- An extreme case to understand what happens when there are a lot of placeholders on the screen: showing icons will probably add a noticeable amount of noise, and, in some cases, there won't be enough space to show the text and have to resort to showing just the icon.

**Comment by annezazu** [comment]
Really love this exploration. The only thing that immediately came to mind is how best to make this distinct from placeholders for theme blocks. At first glance, I could see folks getting confused there.

**Comment by jasmussen** [comment]
> The only thing that immediately came to mind is how best to make this distinct from placeholders for theme blocks. At first glance, I could see folks getting confused there.

To an extent, an empty group can be considered a placeholder, which in part helped inform this idea.
