### ISSUE TITLE
Remember collapsed/expanded state of block panes (Eg image styles is always expanded).

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#33038]
## What problem does this address?

Block panes like the Image block Styles pane, are always expanded, taking up precious screen real estate. Screenshot:

![image](https://user-images.githubusercontent.com/17141205/123650266-b31a3f80-d82a-11eb-9dc1-18214c8bfea0.png)

I never use the styles options, so I'd prefer the styles pane to remain collapsed.

## What is your proposed solution?

1) Make Gutenberg remember if a pane is being collapsed, or
2) make panes collapsed by default, or
3) make visible panes optional (an option to hide styles, advanced etc entirely)

I'd prefer option 1. If I have collapsed a pane for a cleaner editor, it should remain collapsed until I actively expand it again.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/27560 and https://github.com/WordPress/gutenberg/issues/18418. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.
