### ISSUE TITLE
Unable to remove a link using the UI if it at the bottom line of a paragraph of a long post

### ISSUE THREAD

**Issue by MaybeThisIsRu** [WordPress/gutenberg#33035]
## Description
When a link is at the bottom of the screen, its pop-up hides its options. I cannot remove the link.

## Step-by-step reproduction instructions
- New post
- Fill up the screen
- On the last line, add a link.
- Go edit something else.
- Come back to the bottom link and try to remove the link using the options menu
- You can't - it's hidden behind the pop-up.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/3974019/123635540-6853f400-d839-11eb-995e-8c5d3ef46977.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Pop!_OS 20.04 LTS
- Browser: Firefox 89.0.1

**Comment by talldan** [comment]
cc @getdave I remember a recent discussion about this, but couldn't find the relevant issue/pr.

One of the potential solutions mentioned was to put an 'unlink' button in the popover.

**Comment by talldan** [comment]
Found it now, there's a PR here - https://github.com/WordPress/gutenberg/pull/32541.

**Comment by getdave** [comment]
Yep im working on this. Thank you for raising this Issue.

**Comment by getdave** [comment]
@hirusi this should now be resolved via the addition of the `Unlink` button in the link UI itself. See https://github.com/WordPress/gutenberg/pull/32541

**Comment by MaybeThisIsRu** [comment]
Thank you so much @getdave. This was superfast! I'm not sure how to test a non-release, so I'll wait for the next patch release. 🙂

**Comment by getdave** [comment]
No problem. Luckily I was already half way to a fix when you noticed it! 😄 

> I'm not sure how to test a non-release

No pressure to do so but just so you know we have some good documentation on how to do that here

https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/
