### ISSUE TITLE
Highlight pattern directory patterns in the initial view of the pattern inserter

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#33046]
When the pattern inserter is first loaded up, it displays the first (alphabetical) category of patterns by default. With the currently-bundled patterns, this is the somewhat underwhelming "Buttons" category. 

Now that the [Pattern Directory](https://wordpress.org/patterns/) has begun being populated by patterns, it would be great to replace that initial view with a "Featured" category, full of patterns from the directory. Since we've been [working on creating the initial patterns there](https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/), the Design team can help curate this first list it necessary. 

It might be worth redesigning this initial state, so that more patterns are visible too. But for now, even just pulling in some patterns from the directory into a "Featured" category would be a great step. 

Current|Suggested
---|---
<img width="350" alt="Screen Shot 2021-06-28 at 12 01 01 PM" src="https://user-images.githubusercontent.com/1202812/123667857-8c4b1180-d808-11eb-880b-5e30ffa4f23d.png">|<img width="350" alt="Frame 1" src="https://user-images.githubusercontent.com/1202812/123669083-bbae4e00-d809-11eb-8bee-08d18daf4985.png">

**Comment by karmatosed** [comment]
I like this idea a lot and it helps now, but even more so as it scales up to have more patterns. Because for me really just having what you offered works design-wise - I am going to remove the needs design label and put this to feedback, but I am very tempted to just move to dev with enough opinions as it seems really useful.
