### ISSUE TITLE
Can't get post thumbnails

### ISSUE THREAD

**Issue by maitearmengaud** [WordPress/gutenberg#33047]
## Description
I can't add a featured image to my single post, even after adding theme_support to enable the option. It's not working when I enable the Gutenberg plugin. When I disable it, I can add one.

## Step-by-step reproduction instructions
1. Add `add_theme_support( 'post-thumbnails' );`
2. Edit a single post

## Expected behaviour
You should have a `featured image` part inside the editor to set a featured image.

## Actual behaviour
There is no `featured image` option in the post options

## Screenshots or screen recording (optional)
![Capture d’écran 2021-06-28 à 18 12 50](https://user-images.githubusercontent.com/53378428/123669525-78210780-d83c-11eb-8d92-79ce01d6668b.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.9.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  No (custom one)

## Device information
- Device: All devices
- Operating system: All OS
- Browser: All browsers

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. Could you verify if you are hooking in the correctly? You'll need to place the add_theme_support inside another function (I named it my_theme_setup in this example) and hook into after_setup_theme. 

```
function my_theme_setup() {
	add_theme_support( 'post-thumbnails' );
}
add_action( 'after_setup_theme', 'my_theme_setup' );
```

To help find the cause of the issue, could you also share the following:

- What [user role](https://wordpress.org/support/article/roles-and-capabilities/) are you? Are you logged into your wordpress site as an administrator or are you a different type of user (author, editor)? 
- Are you editing a custom post type or is this for a typical post or page?

**Comment by maitearmengaud** [comment]
Hi ! Thanks for you answer.
Yes that's what I did, I'm correctly hooked, that's why it seems strange to me.

Of course :
- I tried with an administrator role, but also with an author account
- No I'm editing a typical post

**Comment by skorasaurus** [comment]
Are you able to share the custom theme that you're using?

**Comment by maitearmengaud** [comment]
Unfortunately, I can't... But I saw that it's working on my local machine, but not on my pre-production webserver. So maybe it's not about Gutenberg....

**Comment by maitearmengaud** [comment]
Thank you @skorasaurus.
Sorry for this issue, finally the problem was with my environment. And not about Gutenberg, seems like my web server wasn't fully configured.

**Comment by skorasaurus** [comment]
Thank you for following up :)
