### ISSUE TITLE
Deleting widgets is unpredictable

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#33069]
When deleting widgets from the editor:

- they continue to remain in the database
- they are visible for the classic widgets editor
- they are invisible for the block based widgets editor

### Screenshot

https://user-images.githubusercontent.com/107534/123822216-c1d52500-d904-11eb-8935-9a82f37be57f.mp4

### To reproduce

1. Have the Classic widgets plugin enabled
2. Enable TT1 theme
3. Activate Classic widgets
4. Go to Appearance > Widgets
5. Add a Meta widget and a Calendar widget
6. Deactivate Classic widgets
7. Go to Appearance > Widgets
8. Add some blocks like paragraph and image
9. Save
10. Delete all the widgets
11. Activate Classic widgets
12. Go to Appearance > Widgets
13. **Observe some widgets (block widgets) remained**
14. Deactivate Classic widgets
15. Go to Appearance > Widgets
16. **Observe there are no widgets**
17. Go to the homepage
18. **Observe some widgets still are in the footer**

### Expected behavior

The deleted widgets (classic and blocks) to be deleted and removed from the DB.

**Comment by draganescu** [comment]
This is not easy to repro on a clean site. Do persist :)

**Comment by noisysocks** [comment]
So I _think_ what's going on here is that there is a bug in the REST API which causes only one widget to actually be deleted when deleting multiple widgets.

@draganescu: Could you confirm if https://github.com/WordPress/wordpress-develop/pull/1452 fixes this for you?

**Comment by draganescu** [comment]
Yes https://github.com/WordPress/wordpress-develop/pull/1452 fixes the problem 👏🏻  At least in my testing 😊

**Comment by noisysocks** [comment]
Awesome. Closing in favour of https://core.trac.wordpress.org/ticket/53557 then.
