### ISSUE TITLE
E2E Tests: Add tests for copy&paste scenarios

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#33073]
We've been recently dealing with a regression that caused some issues when pasting text into the Editor canvas. One of them has been recently addressed in https://github.com/WordPress/gutenberg/issues/32526, but there still seem to be [other scenarios](https://github.com/WordPress/gutenberg/issues/32526#issuecomment-870730781) where pasting doesn't yet work as expected. 

Let's make sure we have test coverage for basic copy&paste scenarios. 🙌  /cc @fullofcaffeine @ockham 

Related to: https://github.com/WordPress/gutenberg/issues/33078.

**Comment by skorasaurus** [comment]
other examples of this cropping up recently: 
https://github.com/WordPress/gutenberg/issues/32467
https://github.com/WordPress/gutenberg/issues/32980

**Comment by khushishikhu** [comment]
hi @WunderBart can i work on this issue?

**Comment by WunderBart** [comment]
> hi @WunderBart can i work on this issue?

Absolutely! Thanks for helping with this, @khushishikhu! 🙌

**Comment by fullofcaffeine** [comment]
I think this has been fixed by https://github.com/WordPress/gutenberg/pull/35416. @ellatrix added E2E tests there.
