### ISSUE TITLE
Can't copy text from paragraph into the list block

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#33078]
## Description

Can't copy text from paragraph into the list block. This might be a symptom of a lower-level problem, but that's how it manifested so far.

## Step-by-step reproduction instructions
1. Start a new page or post and press enter to create a new `Paragraph` block;
2. Press enter again to break into a new line, then insert a `List` block;
3. Use your mouse to select the text from the `Paragraph` block, then copy it;
4. Now give focus to the `List` block again, create a new bullet point if you hadn't already. Try to paste the text you copied. You won't be able to;
5. Create a new `Paragraph` and paste the text. This time the text will be pasted as expected.

#### Other aspects to keep in mind:
* Copying text from within the `List` block and pasting into it again works;
* Copying another block and pasting from within the `List` block context works, though the new block is not inserted as an inner block (this is expected, just to note that the actual paste is done)
* Copying text from a context outside the editor canvas and pasting into the list block works (i.e try copying from the browser's address bar and pasting into the list block
* Copying from the page/post heading field into the `List` block, works.
* This might not be something specific to the `List` block but more general, but that's the scenario that can be used to easily reproduce the issue.

## Expected behaviour

I expect to be able to paste from a `Paragraph` block (or any source) into the `List` block without problems.

## Actual behaviour

Copying text from a `Paragraph`  block and pasting into the `List` block doesn't work. It just fails silently. It does work if you paste somewhere else (i.e another `Paragraph`), so it suggests that it's a problem in the logic that handles pasting for `List`.

## Additional information

I bisected and it led me to this PR: https://github.com/WordPress/gutenberg/pull/27967. If you check out its merge commit (`06f741e`), you'll see the issue still happens at its point. If you then revert it, you'll see it doesn't happen anymore.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1451471/123830975-204dd380-d904-11eb-95d8-cd9c55e5b519.mov

## WordPress information
- WordPress version: 5.8-beta4-51261
- Gutenberg version: `trunk`
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 18.04
- Browser: Firefox 90.0b12 64bit and Chrome 91.0.4472.101 (Official Build) (64-bit)

**Comment by skorasaurus** [comment]
very similar examples of this cropping up recently: 
https://github.com/WordPress/gutenberg/issues/32467
https://github.com/WordPress/gutenberg/issues/32980
https://github.com/WordPress/gutenberg/issues/31067

**Comment by 4faster** [comment]
In my case, 
it is not only paragraph to list, 
but also any other block type to list block.

However, it has no problem if doing copy-paste from a list to another list
https://wordpress.org/support/topic/version-5-8-gutenberg-cant-copy-some-text-from-a-block-to-list-block/

**Comment by tonyzeoli** [comment]
I'm having the same issue. Can't copy and paste from a paragraph to a list block.

**Comment by paynterf** [comment]
Still happening with latest WP 5.8.2

**Comment by zachatkinson** [comment]
This issue is also apparent with quote and pull quote blocks.  So all together no paste from one block in document into either:

- List Block
- Quote Block
- Pullquote Block

**Comment by diannevolek** [comment]
I can't paste any text at all into a Media block: content? It pastes into notepad, and into a classic block. 

In general I"m struggling with blocks to select text and keep it selected for long enough to Ctrl+C. It immediately unselects itself. If I select and press delete to try to get rid of text, it deletes one character.

Gutenberg is a problem guys, it's great for Wordpress designers, but really bad if you have content?

**Comment by webcoreinc** [comment]
Still can't copy and paste blocks.

"Designing" in "Gutenbug" is a total nightmare and takes twice as long.

I could hand code faster than Gutenbug.

"Gutenbug" is 100% garbage. I am stuck using it in our newsletter and after using Elementor, it's a complete nightmare to use.

The Gutenbug developers should be banned from developing for life.
