### ISSUE TITLE
Copy and paste introduces nonexisting blocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#33097]
In the widgets editor using copy and paste introduces non existent "undefined" blocks.
The operation in the post editor works as expected.

### To reproduce

1. Use latest WP 5.8 RC
2. Go to Appearance > Widgets
3. Add some blocks
4. Add some legacy widget blocks
5. Select all using Cmd/Ctrl + A twice
6. Copy all content
7. Remove all blocks
8. Paste
9. Observe bug: undefined blocks created

### Screenshots

https://user-images.githubusercontent.com/107534/123965114-cc52f580-d9bc-11eb-95f1-821cc3ef2c10.mp4

### Expected behavior

When pasting the content is preserved as it was copied.

**Comment by getdave** [comment]
This appears to be due to the newline character being converted into a block with a name of `wp:null`.

For example try pasting in the following and you will see no "undefined" blocks:

```
<!-- wp:archives /--><!-- wp:categories /--><!-- wp:legacy-widget {"idBase":"meta","instance":{"encoded":"YToxOntzOjU6InRpdGxlIjtzOjExOiJMZWdhY3kgTWV0YSI7fQ==","hash":"78ef891e534480bca0e373c0723a3559","raw":{"title":"Legacy Meta"}}} /-->
```

...wherebas pasting this will result in `undefined` / `missing` blocks in the editor as @draganescu describes:

```
<!-- wp:archives /-->
<!-- wp:categories /-->
<!-- wp:legacy-widget {"idBase":"meta","instance":{"encoded":"YToxOntzOjU6InRpdGxlIjtzOjExOiJMZWdhY3kgTWV0YSI7fQ==","hash":"78ef891e534480bca0e373c0723a3559","raw":{"title":"Legacy Meta"}}} /-->
```

**Comment by getdave** [comment]
Replicating this in the Post Editor I see that pasting

```
<!-- wp:archives /--><!-- wp:categories /-->
```

resulting:

* **x2** Archives blocks - why 2?
* x1 Categories

There appears to be some bug here.

**Comment by getdave** [comment]
When pasting this is where the `null` blocks are being created:

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/block-serialization-default-parser/src/index.js#L204-L213

...which creates the `null` block here

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/block-serialization-default-parser/src/index.js#L59-L61

But strangely this line should be guarding against `null` blocks being created by the parse implementation:

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/blocks/src/api/parser.js#L673-L675

**Comment by getdave** [comment]
New clue - this line behaves differently between Post and Widgets Editors.

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/blocks/src/api/parser.js#L565-L567

* Widgets Editor - the `if()` is falsey and thus the early return is bypassed and a valid block is returned.
* Post Editor - the `if()` is truth and thus the function returns early.

Therefore in Post Editor the `block` variable in the check below will be `false` whereas in the Widgets Editor it will be true, resulting in different blocks in the parsed stack between the editors.

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/blocks/src/api/parser.js#L673-L675

Either way it seems the _raw_ parser implementation (see unit tests) does not ignore whitespace correctly and thus #33136 may still be valid as it would be better to fix the underlying parser than rely on this quirk.

**Comment by getdave** [comment]
https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/blocks/src/api/parser.js#L565-L567

In the above:

* Post Editor - `innerHTML` is `""`.
* Widgets Editor - `innerHTML` is `<!-- wp:null /-->`.

Turns out this is due to the call to `getBlockType` returning:

* Post Editor - block object for `core/freeform`
* Widgets Editor - `undefined`.

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/blocks/src/api/registration.js#L569-L571


...and this leads us too:

https://github.com/WordPress/gutenberg/blob/80465ea0ef7f804e515bb1b0137a31890bd7baaf/packages/edit-widgets/src/index.js#L32-L36

We are disabling `core/freeform` from Widgets screens.
