### ISSUE TITLE
Image Block: URL preview layout is broken

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#33096]
## Description
When opening the "Replace" dropdown for an Image block, the Link/URL preview styling is broken. See screenshot.

## Step-by-step reproduction instructions
1. Create a post.
2. Add Image block and select media
3. Click on the "Replace" toolbar button.
4. See the "glob" icon.

## Expected behaviour
The layout should look more "stacked" without overlapping elements. It should not be visually "broken".

## Actual behaviour
It looks visually broken.

## Screenshots or screen recording (optional)
![CleanShot 2021-06-30 at 16 43 12](https://user-images.githubusercontent.com/240569/123964709-c82ad600-d9c4-11eb-87f0-9378698b1c3f.png)

## WordPress information
- WordPress version: 5.8 RC1
- Gutenberg version: 10.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

**Comment by getdave** [comment]
Thanks for reporting @Mamaduka. I updated the title and description to reflect the fact that it isn't showing a rich preview but rather the CSS styles are slightly broken in this context.

**Comment by JustinyAhin** [comment]
I think some styling can be applied to the `block-editor-media-replace-flow__image-url-label` element. Maybe adding a margin-left to it. `margin-left: 2em;" seems to align the text correctly with the image link; but it is overflows a bit on the edit button.

<img width="268" alt="CleanShot 2021-07-06 at 12 22 21@2x" src="https://user-images.githubusercontent.com/33403964/124592428-5b488d80-de55-11eb-8268-78569d1f64d6.png">

We could increase also the popover width.

**Comment by getdave** [comment]
@JustinyAhin Thanks for your suggestion above. I think we can solve this relatively easily by removing some of the previous CSS rules that are no longer needed in this context thanks to the new rules in the base `<LinkControl>` component itself.

Let me know if https://github.com/WordPress/gutenberg/pull/33326 works for you

You can test it using the following workflow https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/

**Comment by JustinyAhin** [comment]
> Let me know if #33326 works for you

@getdave it works as expected. I've added a comment on the PR.
