### ISSUE TITLE
[Widget editor] Block toolbar gets covered by form elements

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#33107]
## Description

_A picture is worth a thousand words_

<img width="1124" alt="Zrzut ekranu 2021-06-30 o 17 03 24" src="https://user-images.githubusercontent.com/205419/123984769-31124e00-d9c5-11eb-8d90-e3a6e2bcd1ec.png">

<img width="1635" alt="Zrzut ekranu 2021-06-30 o 16 33 35" src="https://user-images.githubusercontent.com/205419/123984895-4edfb300-d9c5-11eb-9573-085730e30c2d.png">

This happens on latest trunk version of WordPress and Gutenberg on both TwentyTwenty and TwentyTwentyOne themes

## Step-by-step reproduction instructions
1. Install WebStories plugin
2. Go to the new widgets editor
3. Add WebStories widget
4. Add a enough blocks below the WebStories widget to be able to scroll down
5. Focus Web Stories widget
6. Scroll down, confirm the block toolbar behaves correctly
7. Focus any `<select />` element within the Web Stories form

## Expected behaviour
The block toolbar should be visible

## Actual behaviour
The block toolbar goes into background and gets covered by other form elements

**Comment by draganescu** [comment]
Heew is a video from my testing:


https://user-images.githubusercontent.com/107534/124004431-ab9c9700-d9e0-11eb-9c6e-70e64fa365d0.mp4
