### ISSUE TITLE
Consider deprecating "function widgets"

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#33104]
## Description

This issue is all about function widgets like the [Marquee Widget](https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1). They are a special case of widgets and the new editor has a few problems with handling them:

1. Changing a form field of a function widget doesn't "activate" the "Update" button
1. Saving the widgets screen using the "Update" button does not preserve changes from the function widget form

![2021-06-30 16-36-45 2021-06-30 16_51_59](https://user-images.githubusercontent.com/205419/123982663-83526f80-d9c3-11eb-8748-77f25caf3be4.gif)

1. The function widgets tend to get added to the "Inactive widgets" section seemingly randomly, if the user doesn't notice they won't be able to add another one to their desired sidebar.
1. ...I am willing to bet there's more. We already adressed a bunch, e.g. #32960, #33066, #32978

There are two ways of approaching these bugs:

1. Whack-a-mole every problem as we uncover them
2. Deprecate the concept of a "function widget", eliminate all the code branches that are specific to function widgets, and wrap them in a class using code similar to this (props to @noisysocks):

```php
function wp_register_sidebar_widget( $fn ) {
	register_widget( new class extends WP_Widget {
		public function widget() {
			call_user_func( $fn );
		}
	} );
}
```

The latter approach has some limitations. For example, there’s an implicit assumption that there’s just one instance of any function widget, which means that adding more than one of them and clicking the "Update" button would effectively update the same database entry multiple times. On the other hand, we could add `$is_multi = false` to such `WP_Widget` to simulate that behaviour in a less weird way. On yet another hand, we could just wear the weirdness and say “it’s deprecated, tread carefully!” in some place in the UI.

That being said, I am a big proponent of deprecating function widgets and would like to discuss it here.

cc @noisysocks @draganescu @talldan @kevin940726 @gziolo @spacedmonkey @ellatrix @hellofromtonya  @getdave

**Comment by noisysocks** [comment]
Thanks for creating an issue to discuss and track. I'd very much like to deprecate this kind of widget after WordPress 5.8. I think also it might make sense to do this as part of refactoring widgets to use CPTs as the storage mechanism (see Core-35669).

**Comment by noisysocks** [comment]
Just quickly noting:

> Changing a form field of a function widget doesn't "activate" the "Update" button

This is expected. Function widgets bypass the normal _Update_ flow because their data can be stored somewhere that we don't know about. That's why they have their own _Save_ button.

> The function widgets tend to get added to the "Inactive widgets" section seemingly randomly, if the user doesn't notice they won't be able to add another one to their desired sidebar.

Also expected. You can't delete a function widget and so if you try it will re-appear in _Inactive widgets_. I agree it's not obvious that this is happening.

Also worth noting is that these types of widgets are incredibly uncommon 🙂

**Comment by adamziel** [comment]
> This is expected. Function widgets bypass the normal Update flow because their data can be stored somewhere that we don't know about. That's why they have their own Save button.

If I wear my _developer_ hat, I can understand that. If I wear my _user_ hat, I am confused why sometimes there's another save button and why updating things doesn't always update things.

> Also worth noting is that these types of widgets are incredibly uncommon 🙂

That's a good news! It should make it easier to deprecate that then.

**Comment by adamziel** [comment]
Let's continue in https://core.trac.wordpress.org/ticket/53993
