### ISSUE TITLE
HTML tags in the description of the widget area are escaped

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#33106]
I am testing 5.8RC1.

When I use HTML tags such as `<b>` and `<a>` in the description of the widget area, they are escaped.

## Step-by-step reproduction instructions
1. Register the widget area as shown below.

```
register_sidebar([
    'name'          => 'Test Area',
    'id'            => 'test-area',
    'description'   => 'Widget description <b>test</b>. ( <a href="###">Help link</a> )',
]);
```

2. Check the description of the area.

## Expected behaviour

Here is how it looks in the classic widget

<img width="473" alt="スクリーンショット 2021-06-30 23 58 24" src="https://user-images.githubusercontent.com/31400297/123984500-a3a01f80-d9ff-11eb-9063-3823b6b6bcd3.png">

## Actual behaviour
In the block widget, the output will look like this

<img width="276" alt="スクリーンショット 2021-06-30 23 58 06" src="https://user-images.githubusercontent.com/31400297/123984636-c2061b00-d9ff-11eb-91e1-c263ceaf02a8.png">

**Comment by desrosj** [comment]
Thanks for flagging this @ddryo.

WordPress Core has a function that has been in place since version 2.9.0 specifically for running the widget description through `wp_kses()`, `wp_sidebar_description()`.

Because this is a long established feature of WordPress, I think it's reasonable to assume that lots of developers have dropped basic markup in the `description` field, and this should be considered for backwards compatibility. I've added to the 5.8 must have board for discussion.

**Comment by TimothyBJacobs** [comment]
It looks like this needs to be adjusted in the Client. The REST API isn't doing escaping, though after https://core.trac.wordpress.org/ticket/53646 we will be only allow a subset of HTML to be returned.

**Comment by desrosj** [comment]
For reference, this is the list of markup that `wp_sidebar_description()` allows with the allowed attributes:

- `<a href="" title="">`
- `<abbr title="">`
- `<acronym title="">`
- `<b>`
- `<blockquote cite="">`
- `<cite>`
- `<code>`
- `<del datetime="">`
- `<em>`
- `<i>`
- `<q cite="">`
- `<s>`
- `<strike>`
- `<strong>`

**Comment by desrosj** [comment]
[Core-53646](https://core.trac.wordpress.org/ticket/53646) was merged into Core in [Core-51408](https://core.trac.wordpress.org/changeset/51408).

**Comment by noisysocks** [comment]
Let's punt this to 5.8.1. Probably we just need to use `dangerouslySetInnerHTML`.
