### ISSUE TITLE
Template Mode active with `theme.json` and no means to disable it

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#33109]
## Description
I have a custom theme I'm trying to build. I have a working `theme.json`. However, the front page shows white screen with **WP 5.8 RC1-51270** and Query Monitor is showing `wp-includes/template-canvas.php` as being loaded. 

If I activate **Gutenberg 10.9.1** (with WP 5.8 RC1-51270) then I see the "Template part has been deleted or is unavailable: header" message and Query Monitor shows it is loading `wp-content/plugins/gutenberg/lib/template-canvas.php`. 

I've tried taking my `theme.json` file and dropping it in to various TwentySomething themes and their front page shows fine (it appears as if there is/was never a `theme.json` ever). I'm wondering if there is a temporary deprecation jig in place _just_ for TwentySomething themes? 🤔 

I've also tried adding the following to try and disable Template Mode (in my custom theme and not TwentySomething), but it does nothing at all:

```
add_action( 'after_setup_theme', function() {
	remove_theme_support( 'block-templates' );
} );
```

## Step-by-step reproduction instructions
With latest `WP 5.8 RC1-51270` (using [WordPress Beta Tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/) w/ Nightly and verifying in bottom right-hand corner)
1. create a simple, basic theme: `style.css`, `functions.php`, `header.php`, `footer.php`, `index.php`, and drop in a simple `theme.json` (generate simple one here: https://gutenberg-theme.xyz/)
2. Go to home page and see white screen
3. Also, try adding the `add_action` code (above) in `functions.php` to try and disable block templates:
4. Continue to see white screen on home page

With latest `WP 5.8 RC1-51270` _and_ latest `Gutenberg 10.9.1`
(same steps as above)

## Expected behaviour
The contents of the Page (if Settings > Reading > Your Homepage displays: a Static Page is set) is displayed on homepage, or archive listing of Posts (if Settings > Reading > Your homepage displays: Your latest posts) is displayed on homepage.

## Actual behaviour
Whitescreen or with latest Gutenberg 10.9.1 active: the following message: "Template part has been deleted or is unavailable: header"

## WordPress information
- WordPress version: WP 5.8 RC1-51270
- Gutenberg version: 10.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Sometimes (see notes above)

## Device information
- Device: Desktop
- Operating system: macOS 11.4
- Browser: Chrome 91.0.4472.114

**Comment by annezazu** [comment]
Thanks for reporting this! Going to do my best to flag this for a few folks to get it reviewed.

**Comment by colorful-tones** [comment]
This was a user issue after all. I'll try to follow up with notes, but just going to close for now as it is not a bug. Thanks!

**Comment by annezazu** [comment]
Ah ha. Thank you for looping back :) Happens to the best of us. Just this week I had a user error with the beta tester plugin 🙈
