### ISSUE TITLE
Sometimes it is not possible to delete the contents of "Inactive widgets" in block widgets.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#33110]
I'm sorry, I've only encountered this bug once, but I couldn't take a screenshot of the error content, and I don't know how to reproduce it.

When I turned on new Block Widgets, I tried to delete the **"Inactive widgets"** because they had accumulated quite a lot, but when I tried to "Update" after deleting them, I got an error and could not delete them.

I do remember that the console was giving me a 400 error on the POST connection.
The connection was to `/v1/xxxxx`.

I was able to solve the problem by activating the classic widgets plugin and clearing "Inactive widgets", but why the bug occurred remains a mystery.

If anyone else has encountered the same problem, please let me know.

**Comment by noisysocks** [comment]
Thanks for the report! This is likely fixed by Core-53557 which will be in RC 2. Let me know if you still encounter the issue in RC 2 and we can reopen.
