### ISSUE TITLE
Legacy Widget: NoPreview component has extraneous padding

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#33124]
## Description
When you insert a Legacy Widget block, the default placeholder has some styling issues.

## Expected behaviour
- The "Select a legacy widget to display" text should not be truncated.
- The "Select widget" text should be sans-serif.

## Screenshots or screen recording
<img width="749" alt="Screen Shot 2021-07-01 at 14 20 01" src="https://user-images.githubusercontent.com/612155/124064194-a2aad480-da77-11eb-8648-e113332347f1.png">

## WordPress information
5.8 RC 1 with no Gutenberg Plugin.

**Comment by noisysocks** [comment]
Also looks like the input labels ("Title" below) are serif again which I thought we'd fixed? Maybe it was a recent fix or a PR was not backported. @tellthemachines 

<img width="744" alt="Screen Shot 2021-07-01 at 14 28 40" src="https://user-images.githubusercontent.com/612155/124064696-a2f79f80-da78-11eb-8edc-8bd624b5b890.png">

**Comment by noisysocks** [comment]
Also the title ("Text" below) in the "No preview available" message is large and has too much padding. More CSS bleed no doubt 😅

<img width="754" alt="Screen Shot 2021-07-01 at 14 32 27" src="https://user-images.githubusercontent.com/612155/124064990-37620200-da79-11eb-8305-4b1d60f6c0e7.png">

The video in https://github.com/WordPress/gutenberg/pull/30889 shows how it should look.

**Comment by tellthemachines** [comment]
I think this is expected behaviour. The font-family in those fields is set to `system-ui`, and Firefox's default font for some reason is Times. You can go into browser settings and change it:

<img width="515" alt="Screen Shot 2021-07-01 at 4 21 48 pm" src="https://user-images.githubusercontent.com/8096000/124075730-a7c44f80-da88-11eb-99fa-66b9fc528e3d.png">

Not sure where the padding on the title is coming from though, that's probably on our side 😅

**Comment by noisysocks** [comment]
> I think this is expected behaviour. The font-family in those fields is set to `system-ui`, and Firefox's default font for some reason is Times. You can go into browser settings and change it:

OK fair enough!

It looks like @adamziel fixed the truncation in #33141 so let's just fix the `NoPreview` component's styling issues:

![](https://user-images.githubusercontent.com/612155/124064990-37620200-da79-11eb-8305-4b1d60f6c0e7.png)

It should look like it did in https://github.com/WordPress/gutenberg/pull/30889:

<img width="1212" alt="Screen Shot 2021-07-05 at 11 26 54" src="https://user-images.githubusercontent.com/612155/124406175-e8bbad00-dd83-11eb-99ec-8ed9ee01ca37.png">

**Comment by adamziel** [comment]
Fix available in https://github.com/WordPress/gutenberg/pull/33200
