### ISSUE TITLE
[Automated Testing] Do not load remote patterns in tests

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#33126]
## Description

Recently a regression in GB was introduced that made a deprecated block from core remote patterns (loaded from the pattern directory) create errors that were logged and therefore made tests fail as they take into account the `console` output.

While the regression was fixed here: https://github.com/WordPress/gutenberg/pull/33117, the problem still remains and we can't have GB CI rely on this external source.

## Resolution
Make sure that remote patterns are not loaded during tests. If some tests require patterns should handle registration etc.. isolated there. An example could be the tests for `Query Loop` block which needs patterns for testing here: https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/plugins/query-block.php#L14.

**Comment by Mamaduka** [comment]
I think we'll need to land #33052 first. Then we could use the mu-plugin and `should_load_remote_block_patterns` filter to disable remote patterns.

**Comment by Mamaduka** [comment]
I realized that we could use just the core filter since the GB function bails early when the core method exists.

When ahead and create PR - #33160. I don't have info if any core tests depend on remote patterns, but I will push updates if necessary.
