### ISSUE TITLE
Release 11.0.0

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#33134]
This Issue is here to help me to track the `11.0.0` release and for any coordination efforts.

## Releases

- [x] [Release Candidate](https://github.com/WordPress/gutenberg/releases/tag/v11.0.0-rc.1).
- [x] Stable

## Cherry Picking

- [x] https://github.com/WordPress/gutenberg/pull/33117
- [x] https://github.com/WordPress/gutenberg/pull/33088

**Comment by priethor** [comment]
@getdave are you using this issue to track bugfix releases as well?

**Comment by getdave** [comment]
Probably wise although I havent done any bug fixes.

**Comment by priethor** [comment]
Ok, let's leave it open until 11.1 👍

**Comment by gziolo** [comment]
11.4 is out already so we can close this one 😄
