### ISSUE TITLE
Problem with admin themes

### ISSUE THREAD

**Issue by signo** [WordPress/gutenberg#3314]
When using an admin theme gutemberg's toolbar does not show correctly, it appears that gutemberg's toolbar is fixed to the normal wp admin theme. I tested with Vivaldi 1.13.971 (Chrome/61.0.3163.102) and Firefox 56.0 in Linux Mint 18.1

The admin themes i tested 
- Slate admin theme ( wp.org)
- Slate Pro (Premium)
- Material WP (Premium) 

Attached images showing the issue
![gutemberg_materialwp](https://user-images.githubusercontent.com/944774/32332075-eca14406-bfba-11e7-8858-2c5e3cc2382b.png)
![gutemberg_slate](https://user-images.githubusercontent.com/944774/32332084-f156663e-bfba-11e7-9151-df129d6a1aa0.png)

**Comment by karmatosed** [comment]
As this is a new screen the admin theme will have to change, not Gutenberg. I know this is a little frustrating to hear, but we can't account for third party admin themes.
