### ISSUE TITLE
Standardize required clicks for adding a link

### ISSUE THREAD

**Issue by ddegner** [WordPress/gutenberg#33146]
## What problem does this address?

Adding a link to an image requires an extra click after selecting the page to link to that adding a link to text and other elements doesn't require.  This has caused me to think that I added a link but it wasn't actually recorded.

[Example of irregularity](https://imgur.com/6RTVa80)

## What is your proposed solution?

I'd propose that on images after selecting the page to link to that the link is directly saved and the link interface closes, as it does with other elements.

**Comment by richtabor** [comment]
100%. There’s no reason those, or any link UI should be any different.

**Comment by getdave** [comment]
Just to confirm the link component used on Images is not the `<LinkControl>`. Rather it uses the underlying `<URLInput>` component.

<img width="724" alt="Screen Shot 2021-09-23 at 10 25 21" src="https://user-images.githubusercontent.com/444434/134483938-402a2be9-53ae-407b-95f7-4ee941714407.png">


Therefore I'm going to remove this Issue from the `<LinkControl>` tracking issue.

**Comment by richtabor** [comment]
I'm closing this as the LinkControl is coming to other linkable images as detailed in https://github.com/WordPress/gutenberg/issues/50893. It'll be nice to have consistent linking everywhere throughout WordPress. 🚀
