### ISSUE TITLE
iPhone 7 plus screen moves around

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3316]
I am able to move the page around to get a rather 'interesting' view of a white screen. This happens with or without metaboxes.

![img_1921](https://user-images.githubusercontent.com/253067/32341740-3f6ef85a-bff6-11e7-9fab-792351e78f51.PNG)

**Comment by karmatosed** [comment]
This seems to be even worse in Chrome.

**Comment by hedgefield** [comment]
What area are you dragging on to get there? Couldn't reproduce with iPhone 8 Plus + Safari or Chrome.

**Comment by pento** [comment]
I haven't been able to reproduce this issue yet, but #3449 addresses a similar issue I ran into while testing.

**Comment by mtias** [comment]
@karmatosed is this still an issue for you?

**Comment by karmatosed** [comment]
It doesn't seem to be on testing. Closing for now.
