### ISSUE TITLE
Add link color support to the List block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#33181]
## What problem does this address?
While its possible to change the color of links within the Heading and Paragraph blocks, its not possible within the List block. So if you have a background color that is incompatible with the theme's declared `a` styling, you end up with a problem.

### Screenshot 
..from the BlockBase theme, which has `add_theme_support( 'experimental-link-color' );` enabled:

<img width="1002" alt="Screen Shot 2021-07-02 at 9 01 51 AM" src="https://user-images.githubusercontent.com/1813435/124322738-fb4ca100-db4d-11eb-9f89-057c89238752.png">

## What is your proposed solution?
The List block supports 'experimental-link-color', as the Heading and Paragraph blocks do (which both also support Color and Background Color).

**Comment by michaelslevy** [comment]
Shouldn't this be done through CSS styling? It seems like this would encourage bad practices.

**Comment by richtabor** [comment]
> Shouldn't this be done through CSS styling? It seems like this would encourage bad practices.

What bad practices are you referring to? Adding color to links? 

In an era of theme.json styles and the global styles effort, the resolution should probably never be “custom CSS”.

**Comment by michaelslevy** [comment]
Shouldn't there be a separation of content from appearance where elements are styled based on functional convention? 

If the available colors are built into the theme, it would provide administrators with options that fall within a crafted design. It could also allow for semantic assignments to the colors. 

Options to choose a custom color for individual blocks could encourage inconsistencies that clash with the site's color scheme.
