### ISSUE TITLE
Have more list options

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#33186]
Currently, the editor only has the bullet and numbered list. 
I would love to see this list expanded to things like: 

- Square list
- Triangle list
- Personalised symbol
- ...

I think it would be great if I would be able to choose in numbered lists if it shows numbers or letters. 

I feel like Microsoft Word has list and the options for it nailed.

**Comment by talldan** [comment]
Thanks for reaching out. I think this is already discussed in #17738 (also similar is https://github.com/WordPress/gutenberg/issues/9117), it just needs a contributor to work on it.

**Comment by NekoJonez** [comment]
Oh my, sorry about the dupe... I looked over that one.
