### ISSUE TITLE
File block prevents .zip and other files from being uploaded to a blog

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#33187]
## Description

I am unable to upload through File block any application/zip (.zip) files. Other zip-related extensions as well (i.e. application/epub+zip). File block claims that file type is not permitted for security reasons. In the same time uploading exactly the same files through _Media_ section works like a charm.

All necessary conditions are met even high above expectations, i.e.:

1. [I am a super-admin](https://core.trac.wordpress.org/ticket/45818) in my network.
2. The `ALLOW_UNFILTERED_UPLOADS` flag [is set to `true`](https://onezeronull.com/2021/05/12/file-upload-blocked-despite-allow_unfiltered_uploads-set-to-true/#enable-upload-of-all-files)
3. [Custom hook](https://wordpress.stackexchange.com/a/387876/17323) of `$existing_mimes['zip'] = 'application/zip';` is added
4. Uploading .zip files is allowed in my network:

[![enter image description here][2]][2]

5. the [_Enhanced Media Library_ extension](https://wordpress.org/plugins/enhanced-media-library/) clearly shows that this MIME type is added:

[![enter image description here][3]][3]

## Step-by-step reproduction instructions

1. Create any File block
2. Click "Upload" button and select any .zip file on your disk
3. Click "OK" to start upload

## Expected behaviour

File is uploaded to Wordpress and correctly linked to File block.

## Actual behaviour

File is not uploaded and "_Sorry, this file type is not permitted for security reasons_" error is displayed instead.

## Screenshots

An animation showing that uploading the same file is not possible when uploaded directly to blog post and to File block, while is possible when doing the same in "Media" section of a blog network.

![two](https://user-images.githubusercontent.com/60975060/124390079-587d5980-dcea-11eb-9578-3a598eeb240c.gif)

## WordPress information
- WordPress version: _5.7.2_
- Gutenberg version: _Version 10.9.1 | By Gutenberg Team_
- Are all plugins except Gutenberg deactivated? _No_
- Are you using a default theme (e.g. Twenty Twenty-One)? _No_

## Device information
- Device: _PC_
- Operating system: _Windows 10 10094_
- Browser: _Chrome Version 91.0.4472.114_

  [2]: https://i.stack.imgur.com/X986L.png
  [3]: https://i.stack.imgur.com/QSXjC.png

**Comment by talldan** [comment]
@pansamolot Thanks for reaching out. This was previously reported in #23510, there's a lot of info on that issue that may be of help. From reading it's not clear to me whether this is still a WordPress core issue, maybe both? The related trac ticket is still open - https://core.trac.wordpress.org/ticket/40175.

I'll close this in favour of the existing issue/ticket.

**Comment by rjcalifornia** [comment]
> 
> ## Description
> 
> I am unable to upload through File block any application/zip (.zip) files. Other zip-related extensions as well (i.e. application/epub+zip). File block claims that file type is not permitted for security reasons. In the same time uploading exactly the same files through _Media_ section works like a charm.
> 
> All necessary conditions are met even high above expectations, i.e.:
> 
>     1. [I am a super-admin](https://core.trac.wordpress.org/ticket/45818) in my network.
> 
>     2. The `ALLOW_UNFILTERED_UPLOADS` flag [is set to `true`](https://onezeronull.com/2021/05/12/file-upload-blocked-despite-allow_unfiltered_uploads-set-to-true/#enable-upload-of-all-files)
> 
>     3. [Custom hook](https://wordpress.stackexchange.com/a/387876/17323) of `$existing_mimes['zip'] = 'application/zip';` is added
> 
>     4. Uploading .zip files is allowed in my network:


For some reason, this is not being picked up by the ALLOW_UNFILTERED_UPLOADS. I made a small fix, may be that can help:

https://github.com/rjcalifornia/fixzip_upload
