### ISSUE TITLE
Mobile Web: Admin menu: Main content does not move to the right

### ISSUE THREAD

**Issue by evakaneva** [WordPress/gutenberg#33196]
## Description

Unlike the other admin pages, the editor does not slide to right when you open the admin menu.

## Step-by-step reproduction instructions

1. Use a mobile device or make your screen smaller.
2. Open the browser, go to the admin
3. Add new post
4. Click on hamburger to open the admin menu
5. See the admin menu overlaps the main content on the right side

## Expected behaviour

I expect that it moves to the right like other non Gutenberg pages

## Actual behaviour

It overlaps
## Screenshots or screen recording (optional)

|Other pages|Gutenberg|
|-|-|
|![Screenshot_2021-07-05-13-47-54-613_com android chrome](https://user-images.githubusercontent.com/51059617/124463376-7bb41180-dd9b-11eb-9176-74c34c3f1558.jpg)|![Screenshot_2021-07-05-14-10-25-387_com android chrome](https://user-images.githubusercontent.com/51059617/124463384-7d7dd500-dd9b-11eb-8808-fc8a62bddc64.jpg)|

## WordPress information
- WordPress version:  WordPress version: 5.7.1
- Gutenberg version:   Version 10.4.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Android Xiaomi 
- Operating system:  Android 10
- Browser:  Mobile Chrome

**Comment by jordesign** [comment]
Hi @evakaneva  - I'm just checking old issues and I wanted to see if this is still present for you?

**Comment by jordesign** [comment]
With no further comments or movement on this, I will close the issue.

If it is still a problem - a new issue can be opened with updated details on how to reproduce.
