### ISSUE TITLE
User feedback: Not able to find the in-block inserter upon scrolling the page.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#33193]
## Description

User feedback. How do I insert an image?

Her screen looked similar to this:
![Inblock-page-inserter-hidden-by-scrolling](https://user-images.githubusercontent.com/5323259/124456174-b2356080-dd8a-11eb-8167-5e779218e778.jpg)

As the in block inserter becomes hidden behind the toolbar or further up the page the user wondered how to add an image.

A solution might be to have the + in block inserter fixed to the toolbar. Keeping the toolbar and in-block inserter in place.

## Step-by-step reproduction instructions

1. Go to a post or page that has content. Be sure there is enough content so that you can scroll.
2. Add a columns block with a few columns.
3. Add an image. 
4. Click the last column, and scroll.
5. Notice the in-block page inserter becomes hidden behind the toolbar, or further up.

https://user-images.githubusercontent.com/5323259/124456942-92526c80-dd8b-11eb-85e8-24654caaf2b2.mp4

## Expected behaviour
User wanted the + sign directly in the toolbar. Making it easy for her to figure out how to add a block.

## Actual behaviour

Confusion. Not knowing how to add an image.

## WordPress information (client site)
- WordPress version: WP 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? Using eStar by Greta themes.

I tested with:
- WP 5.8 beta
- Twenty Twenty One.
- Gutenberg plugin 10.9.1

## Device information
- Operating system: OSX
- Browser: Firefox

@jasmussen @javierarce @critterverse

**Comment by javierarce** [comment]
Even though the static nature of the inserter is confusing in this example, I think this is one of those instances where we should gather more similar user reports to start designing a comprehensive solution.

**Comment by Thelmachido** [comment]
I added 3 columns to a page. I could easily see the inserter option, it wasn't being blocked by the toolbar as shown in the short video below: 

https://user-images.githubusercontent.com/41231764/185592961-9c6a876a-9793-444e-b037-b3f3bf9dbbb2.mov

However, having an inserter directly on the toolbar is a good suggestion. I remove the bug label since right now this seems more of a feature request. 

- WordPress 6.0.1 
- Gutenberg 13.9.0 
- Theme TT2

**Comment by paaljoachim** [comment]
Closing this issue....
