### ISSUE TITLE
Description for Singular template implies the existence of a "post" template. 

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#33209]
## Description
There are two parts to this issue.
1. A minor formatting problem
2. Some text needs correcting / improving

In the Site Editor, when editing the Singular template, the text in the drop down from the **Singular** label in the middle of the top toolbar could do with some additional spacing. Also the wording should be revisited. 

There's not enough space between **Singular** and Template.  It's OK in the Settings section to the right where the title and description appear on separate lines. 

The second sentence in the description says "This template is a fallback for the Single, Post, and Page templates, which take precedence when they exist."

I'm not aware of a Post template.
There's a `single-post` template for Posts but that takes precedence over the `single` template, as does `attachment` and `single-$posttype`

See https://developer.wordpress.org/themes/basics/template-hierarchy/#single-post

Suggest removal of  `Post, ` from the code in `lib/full-site-editing/default-template-types.php`

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2474435/124505094-aa90ae80-ddc0-11eb-899e-280a6d90894a.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 11.0-RC1
- Are all plugins except Gutenberg deactivated? No 
- Are you using a default theme (e.g. Twenty Twenty-One)?  No

## Device information
- Device: Desktop !-- e.g. "Desktop" or "iPhone 11" -->
- Operating system: Windows 10
- Browser: Chrome

**Comment by youknowriad** [comment]
Both of these are fixed now.
