### ISSUE TITLE
Move the Customizer link to the editor's header

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#33207]
### Problem

The widgets editor has this link "Manage with live preview" that was ported from the classic screen. The original goal of that link was to point users to a better way of managing widgets in the Customizer.

In the new block based widgets editor, the experience is better, but the Customizer still has a better setup with live preview of all widget edits in the full context of the web page. So, the presence of the link is justified.

However its current placement is quite hidden: it appears in the editor's sidebar only if no block or widget area are selected.

### Proposal

Let's move this link to the head of the editor so that:

1. It's more visible
2. It's permanent

<img width="1244" alt="Screen Shot 2021-07-05 at 20 01 41" src="https://user-images.githubusercontent.com/107534/124502538-58ee2100-ddcc-11eb-9bf0-b60c3d604a1c.png">

**Comment by noisysocks** [comment]
I wonder if we should also add a link to the Customizer that links to the Widgets screen? For times where you need a little more space.

**Comment by draganescu** [comment]
I think we should, yes. But for this issue, @critterverse how should this link look in the header? Like the "preview" button in the post editor?

**Comment by critterverse** [comment]
>Like the "preview" button in the post editor?

This sounds right. But, IMO, this is a pretty disorienting link (i.e. why was I taken to a different editor and where am I now?) and I think this would be giving it way too much prominence by having it be persistently visible in the top bar. Just my two cents 😆

**Comment by noisysocks** [comment]
Should we just remove the link altogether if it isn't solving any problem?

**Comment by draganescu** [comment]
I think then maybe this should have its own trac proposal or something :D It is a very old link.

**Comment by noisysocks** [comment]
Core-28032 is where the link was originally added seven years ago. It was intended to guide users to the Customizer because, at the time, the forecast was that Appearance → Widgets and Appearance → Navigation would go away in favour of the Customizer. I don't believe that is the current forecast. Both screens are here to stay and may be adopted by FSE.

**Comment by draganescu** [comment]
This is some bike shedding but it's fun. The use case it serves is that one may use the space of the full editor and then also switch to the customizer for "live preview". But this use case would be served if we also added a "switch to stand alone editor link" in the customizer version as well.

**Comment by noisysocks** [comment]
If we move the link to the header it will be so... big and prominent 😅

I think let's do nothing.
