### ISSUE TITLE
How we can allow only specific blocks for the new Widget Screen?

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#33238]
Hey together,

the new widget screen will come to WordPress with the next release. Therefore it's very useful to disallow or allow specific block types only for using on a small width sidebar.

How we can deal with this?

Is there a filter like `add_filter( 'allowed_block_types', '...')` to allow specific block types for the widget screen?

Thank you for helping.

**Comment by noisysocks** [comment]
Hey @CreativeDive.

You can tell if the block editor **is not** the post block editor using something like this:

```php
add_filter( 'allowed_block_types_all', function( $allowed_block_types, $block_editor_context ) {
	if ( empty( $block_editor_context->post ) ) {
		// This isn't a post block editor.
	}
	return $allowed_block_types;
} );
```

To tell if the block editor **is** the widgets block editor you could use something like this:

```php
add_filter( 'allowed_block_types_all', function( $allowed_block_types, $block_editor_context ) {
	global $pagenow;
	if ( 'widgets.php' === $pagenow || 'customize.php' === $pagenow ) {
		// This is a widgets block editor.
	}
	return $allowed_block_types;
} );
```

The latter example is a little hacky. We will look at improving this in 5.8.x, see https://github.com/WordPress/gutenberg/issues/28517.
