### ISSUE TITLE
Query loop block: Wide alignment not working correctly on the editor

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#33248]
## Description

While using wide alignment on a Query block the width is only applied to the currently selected post while in the editor. The frontend shows the correct alignment for all posts

## Step-by-step reproduction instructions

1. Activate emptytheme (you may need to set layout sizes on the theme.json, [here](https://gist.github.com/MaggieCabrera/624da1fdbfad3ae271c78a728f337868)'s the theme.json file I used)
2. Insert a query block inside a page and set it to show more than one post
3. Apply wide alignment to the query block

## Expected behaviour

I expected all posts inside the query block to show as wide aligned within the editor

## Actual behaviour

Only the first (selected) post shows as wide, the rest show no alignment. The frontend shows them all as wide.

## Screenshots or screen recording (optional)

Editor | Frontent
--- | ---
<img width="984" alt="Screenshot 2021-07-07 at 10 00 58" src="https://user-images.githubusercontent.com/3593343/124723123-fea7aa00-df0a-11eb-9c62-a24fe76c45b4.png"> | <img width="1623" alt="Screenshot 2021-07-07 at 10 03 26" src="https://user-images.githubusercontent.com/3593343/124723120-fd767d00-df0a-11eb-8b01-08b281592b4a.png">

**Comment by annezazu** [comment]
This is still happening in WordPress 5.8.1+Gutenberg 10.6 and it came up in the [tenth call for testing for the FSE Outreach program: ](https://make.wordpress.org/test/2021/09/29/fse-program-testing-call-10-pattern-party/#comment-2054)

> When I select Full Width on a layout using featured images, only the image in the block that I selected appeared full width. On the front end, however, it showed all images as full width – so it was a bit unexpected based on what appeared in the editor.

https://user-images.githubusercontent.com/26996883/136868405-007bb1e0-6d1e-42f9-9c99-afcbfb35746e.mp4

**Comment by priethor** [comment]
I'm adding this to the 5.9 must-haves because alignment tools are one of the top features in this release, and one of the most prominent pieces of feedback received during the Go/No Go demo was to ensure editor<->frontend parity as much as possible.

**Comment by kjellr** [comment]
Adding a few more details from the duplicate issue #35551: 

This only happens in the post/page editor — I'm unable to reproduce in the Site Editor. If a Query Loop block uses layout settings, the non-selected posts in the list incorrectly inherit the following rule:

```
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > * {
    max-width: [content width];
    margin-left: auto;
    margin-right: auto;
}
```

This leads to any non-selected post appearing incorrectly.

## Screenshots: 

<img width="1415" alt="136964840-06bf2fcc-ca40-428f-98d9-ca45d1c83797" src="https://user-images.githubusercontent.com/1202812/138695838-366693fc-bb09-4c83-bed6-1cd467ffcd89.png">

![136964870-263cbd22-3014-4ead-8e05-4fe5e0bd1161](https://user-images.githubusercontent.com/1202812/138695841-b406f134-d1b5-4fbb-b558-eb2619a58f30.gif)

**Comment by carolinan** [comment]
When `Inherit default layout` is enabled for the query loop, the blocks do not move this way.
Edit: Actually they do if the post template is then also set to wide/full.

**Comment by colorful-tones** [comment]
I believe this is a bit of a larger issue. It seems to affect Templates (both editor and output: front end), and not necessarily attributed to the Query Loop Block.

I'm currently running Gutenberg plugin 11.8.2, and I have two Group blocks and they're both set to alignWide. Here is my `theme.json`:

```
		"layout": {
			"contentSize": "860px",
			"wideSize": "1300px"
		},
```

If I go to **Appearance** > **Templates** > **Add New** and drop this:

```
<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><!-- wp:heading -->
<h2 id="heading-one">Heading one</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><!-- wp:heading -->
<h2 id="another-heading">another heading</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
```

And then apply that Template to a Page/Post then the align wide _does nothing_ and there is no `max-width` output on Group block at all.

However, if I just create a new Page/Post and drop this inside (same as above):

```
<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><!-- wp:heading -->
<h2 id="heading-one">Heading one</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><!-- wp:heading -->
<h2 id="another-heading">another heading</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
```

Then the `max-width` is applied to the Group block (as expected). 

I'm quite confused as to the expectation and user experience here. 😕 
I would hope in both examples that my `max-width` = `"wideSize": "1300px"`

| Page w/ Template assigned (using above block code) | Page w/ Group blocks alignWide (no Template assigned) |
|---------|------------|
| ![Screen Shot 2021-11-08 at 5 28 55 PM](https://user-images.githubusercontent.com/405912/140828426-da8b1f76-e08c-40a1-ac29-ef20ad2ee8b6.png) | ![Screen Shot 2021-11-08 at 5 28 20 PM](https://user-images.githubusercontent.com/405912/140828467-14b70214-8d07-4bd3-a22e-aa394cc468d7.png) |
