### ISSUE TITLE
Slash command doesn't clear when / is deleted

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#33246]
### Steps to reproduce the behavior

1. Create a new post
2. Type the / block inserter shortcut
3. Remove the /

#### What I expected to happen

The / window to be hidden

#### What actually happened

The / window persisted until I pressed delete a second time and can jump around if you click away and back into a block area. This can lead to overlap on narrower content areas.

### Context

Empathy testing

#### Browser / OS version

Chrome 91.0.4472.114 OS X

#### Is this specific to the applied theme? Which one?

No

#### Is there any console output or error text?

No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/6737345/124721431-c9eb2100-df11-11eb-90f1-01d1d12df221.png)

Original report in https://github.com/Automattic/wp-calypso/issues/54330

**Comment by Mamaduka** [comment]
Probably related to #32986.

**Comment by talldan** [comment]
I've noticed this too!

**Comment by Mamaduka** [comment]
I did some testing, and if I change `undefined` to `0` for the `hasSelection` check`, the issue gets fixed.

https://github.com/WordPress/gutenberg/blob/1eaad3cbad327e9fad5d8eef93c46aa773b7080b/packages/components/src/autocomplete/index.js#L380

Unfortunately, I'm not very familiar with the RichText component, so I don't want to introduce any regressions.
