### ISSUE TITLE
Post excerpt: editor is showing block content that doesn't show on the frontend

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#33245]
## Description

The excerpt will show only on the editor the contents of some blocks (calendar, latest comments and latest posts as per my testing) but not on the frontend.

## Step-by-step reproduction instructions

1. Activate empty theme
2. Create a post that only contains a Calendar, Latest Posts or Latest comments block (I'm not sure how many blocks recreate this issue)
3. Create a page with a query block and check it both on the editor and the frontend

## Expected behaviour

I expect the excerpt to show the same contents on the editor and on the frontend

## Actual behaviour

Editor | Frontend
--- | ---
<img width="1347" alt="Screenshot 2021-07-07 at 09 50 04" src="https://user-images.githubusercontent.com/3593343/124721271-3f9ebf00-df09-11eb-9708-f178814a2f45.png"> | <img width="1105" alt="Screenshot 2021-07-07 at 09 50 08" src="https://user-images.githubusercontent.com/3593343/124721263-3f062880-df09-11eb-834a-c90a950a3563.png">

**Comment by aristath** [comment]
There was a patch submitted yesterday related to this in core: [#53604](https://core.trac.wordpress.org/ticket/53604)
Not all blocks contribute to an excerpt, there's a whitelist of blocks that can be used: `freeform`, `heading`, `html`, `list`, `media-text`, `paragraph`, `preformatted`, `pullquote`, `quote`, `table`, `verse`.
Yesterday's patch fixed issues with nested blocks & `innerBlocks` not being parsed, but the blocks mentioned in the OP are not whitelisted and can't be used to generate an excerpt (see [`excerpt_remove_blocks`](https://developer.wordpress.org/reference/functions/excerpt_remove_blocks/) function. It gets called when generating an excerpt)

**Comment by MaggieCabrera** [comment]
This one is no longer an issue
