### ISSUE TITLE
meta box content not refreshing after post is published / updated

### ISSUE THREAD

**Issue by twilson90** [WordPress/gutenberg#33282]
## Description
When I save a post, I need to update the contents of my meta box.
Placing a breakpoint in the add_meta_box $callback function shows that the html is re-evaluated, but it never get's applied to the page.

## Step-by-step reproduction instructions
Add a meta box, Click Publish or Update, observe the spinning loader icon in the meta box, but the content remains the same (until the user refreshes the page)

## Expected behaviour
The regenerated meta box html should be applied to the dom.

## Actual behaviour
It remains the same.

## Code snippet (optional)
```
add_action('admin_init', function () {
	if ( current_user_can("send_notifications") ) {
		$post_types = ["post", "go_live"];
		foreach ($post_types  as $post_type) {
			add_meta_box(
				'cabtv_notif_on_post',
				'Notifications',
				function ($post) {
					wp_nonce_field( 'cabtv_notif_metabox', 'cabtv_notif_metabox' );
					$sent = (bool) get_post_meta( $post->ID, 'cabtv_notifications_sent', true );
					$checked = cabtv_should_post_send_notification($post->ID);
					?>
					<div style='padding:10px;'><?php echo rand() ?></div>
					<?php
					
					if ( $sent ) { ?>
						<div style='padding:10px;'><span style='color:red; font-weight:bold;'>Notifications have already been sent for this post.</span></div>
					<?php } ?>
					<label><input type="checkbox" name="cabtv_send_notification" value="1" <?php if ($checked) echo 'checked'; ?>></input> <?php echo esc_attr('Send notification on '.($post->post_status === 'publish' ? 'update' : 'publish') ); ?></label>
				<?php },
				$post_type,
				'side',
				'high'
			);
		}
	}
});
```

The code above shows a common issue, whereby the tickbox for sending notifications should be ticked by default, but once the post is saved and the notification has been sent, I want to untick the checkbox based on the updated post meta and display a warning in bold red font, that notifications have already been sent out once.
Additionally I added a block which just displays a random number (`rand()`) to better show the crux of the issue - this value should change after the post is saved but it only changes when the page is refreshed.

If I place a breakpoint in the callback function, I can clearly see the function is being called moments after the post is saved, and while the debugger is paused, i can also see the loading spinner on the meta box is visible in the interface, and I can also see in the network tab in Dev Tools that wp-admin/post.php is requested, and returns the entire page with all the updated meta box html, but seemingly this gets discarded.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 🤷‍♀️
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? No.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome (latest version)

**Comment by ashfame** [comment]
Hi @hedgehog90 

PHP metaboxes don't exist in the same sense in post-Gutenberg world. It is encouraged to move towards porting your metabox to blocks instead. See - https://developer.wordpress.org/block-editor/how-to-guides/backward-compatibility/meta-box/

While some basic ones will work, as they don't require much functionality, but several will need to choose a transition path. That being said, the behavior reported here isn't a bug and won't be fixed. So, I am going to close this issue now.
