### ISSUE TITLE
Split toolbars takes up more space than before where toolbars were combined.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#33290]
## What problem does this address?
Doing all of my writing in Gutenberg, I appreciate all the screen real-estate I can get, while I still need the toolbars visible while editing. The new arrangement of the top toolbars divided in two (blue overlay), takes up more of the precious space (green), while wasting more space (red) than before...

![image](https://user-images.githubusercontent.com/17141205/124933015-d3ed4c80-e003-11eb-9dee-569038ec49e4.png)

## What is your proposed solution?
I assume that the dividing the toolbar is a usability thing, and I applaud that. To me personally, it hurts the UX a bit. An option to choose the "old ways" with a combined top toolbar would be great. 

Bjarne

**Comment by critterverse** [comment]
Hey @oldrup, wanted to share a few links to conversations about long toolbars and horizontal scrolling difficulties that might be relevant:

- https://github.com/WordPress/gutenberg/issues/32062
- https://github.com/WordPress/gutenberg/issues/30720#issuecomment-824108601
- https://github.com/WordPress/gutenberg/issues/32493#issuecomment-857874321

I'm sure others have done more thinking about the usability-factors surrounding the toolbars and why they are split in this way, but the current difficulties with scrolling them is one thing that's come up a lot recently. I would love to see improvements made to the way scrolling works within toolbars, which might allow for more flexibilitity in terms of various toolbar configurations in the future. I thought the vertical toolbar proposed in https://github.com/WordPress/gutenberg/issues/32493 was a cool idea for example!

**Comment by jordesign** [comment]
I can no longer see the split toolbar in the interface in WP6.3 so I'm going to close this issue.
