### ISSUE TITLE
Can we have revisions for reusable blocks in the reusable block edit screen

### ISSUE THREAD

**Issue by haicu** [WordPress/gutenberg#33297]
## What problem does this address?

Now and than reusable blocks get lost and end up empty. Nor sure why but it happens now and than. It might be that the save button with multiple check boxes for reusable blocks is not used correctly. I don't even quite understand that fully myself yet. Anyhow it sometimes happens. 

## What is your proposed solution?

It would be great if we could have revisions for reusable blocks. Like there are other revisions for other post types. Than I could go to the reusable block management screen, edit the corrupted block and restore a previous version. That would be really helpful. Maybe this could be turned on for reusable blocks just like it works for other post types?

**Comment by skorasaurus** [comment]
This is coming to WordPress 5.8 - https://core.trac.wordpress.org/ticket/53072 :) 

ref https://github.com/WordPress/gutenberg/issues/19149
