### ISSUE TITLE
[RNMobile] Inserter color scheme change not working while app is open on Android

### ISSUE THREAD

**Issue by jhnstn** [WordPress/gutenberg#33292]
## Description

Toggling the dark theme on Android with the app open does not change the color of the inserter bottom sheet. The editor must be closed and reopened for the change to take effect.

This behavior is not reproducible on iOS

## Expected behaviour

The inserter menu should have the same theme as the device.

## Actual behaviour

The inserter theme does not change when the dark theme is toggled until the editor is reloaded.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/744755/124937013-03d12b80-dfd5-11eb-9fb6-e66246a6f14f.mp4

## Device information
- Device: Pixel 5
- Operating system: Android 11.0
- WordPress app version: 17.7-rc-2

**Comment by mchowning** [comment]
It looks like this is the same as [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2108).

@hypest , do you have any thoughts on which issue we should leave open? I'm inclined to close the other issue since it doesn't have much context yet and this seems much more likely to be an issue at the Gutenberg level (it's certainly not ag the gb-mobile level).

**Comment by jhnstn** [comment]
I'm seeing  error messages  like these in the metro server:
```
 ERROR  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in WithPreferredColorScheme(ToolbarGroupContainer) (at toolbar-group/index.js:94)
```
The are all from the Inserter child components. They seem new since the last RN upgrade so not likely the cause of the issue but perhaps a good nudge to look into using the `useColorScheme` hook provided by RN.

**Comment by hypest** [comment]
> @hypest , do you have any thoughts on which issue we should leave open? I'm inclined to close the other issue since it doesn't have much context yet and this seems much more likely to be an issue at the Gutenberg level (it's certainly not ag the gb-mobile level).

No strong feelings from my side. I'd keep the older ticket (and update with any context from this ticket) as that'll keep a better representation of its age and history.

**Comment by mchowning** [comment]
👍  I'll go ahead and close this in deference to the older ticket.
