### ISSUE TITLE
Site editor: custom theme vars for block level not enqueued

### ISSUE THREAD

**Issue by franmastromarino** [WordPress/gutenberg#33300]
## Description

The custom variables included in settings/blocks of theme.json are not included in the full site editor

## Step-by-step reproduction instructions

Include this in the `theme.json`

```json
{
    "version": 1,
    "settings": {
        "custom": {
                "my-own": {
                    "test": "root"
                }
        },
        "blocks": {
            "core/button": {
                "custom": {
                    "test": "button"
                }
            }
        }
    }
}
```

## Expected behaviour

The expected CSS output in the front-end and editors (post, site) is:

```css
body {
  --wp--custom--my-own--test: root;
}
.wp-block-button__link {
  --wp--custom--test: button;
}
```

## WordPress information

- WordPress version: 4.7.2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: laptop
- Operating system: Windows 10
- Browser: Chrome

**Comment by franmastromarino** [comment]
+1

**Comment by getdave** [comment]
I was also unable to get my custom property to output as I expected when using in the block scope.

Here's my simplified `theme.json`:

```json
{
	"version": 1,

	"settings": {
		"blocks": {
			"core/button": {
				"custom": {
					"dave-button-test": "500"
				}
			}
		}
	}
}
```

I expected the custom property to be created on the block selector but it was nowhere to be seen.

FYI this does work at a root level as the class is added corretly to the body.

<img width="1279" alt="Screen Shot 2021-07-22 at 14 48 19" src="https://user-images.githubusercontent.com/444434/126650830-0a115dff-28cb-44fd-8b26-2311357ddcc1.png">

@nosolosw Is there a step we're missing here?

**Comment by oandregal** [comment]
I could repro this, it's a bug: it's working on the front-end and post editor but not the site editor.

**Comment by oandregal** [comment]
Edited a bit the issue description, thanks for reporting.

**Comment by franmastromarino** [comment]
hello @nosolosw !

Thanks for taking care of this issue

Not sure if its a bug too, but maybe you can check also the use of             

"__experimentalSkipSerialization": true

Is not working with custom settings

block.json
`
"supports": {

		"custom": {
			"__experimentalSkipSerialization": true
		},
		"spacing": {
			"__experimentalSkipSerialization": true,
			"padding": true
		},
	},

}
`

kind regards

**Comment by oandregal** [comment]
I'm not aware of any `supports.custom` property. Where did you find that?

**Comment by franmastromarino** [comment]
@nosolosw I have not seeing it in the code, just expected behaviour

**Comment by oandregal** [comment]
What did you expect to happen?

**Comment by oandregal** [comment]
I've prepared a potential fix at https://github.com/WordPress/gutenberg/pull/33932 I can't test it at the moment because the site editor is broken for me.

**Comment by oandregal** [comment]
The fix is good. Welcome reviews.
