### ISSUE TITLE
Post Excerpt Block: Max words control is not available when an excerpt is present

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#33306]
The post excerpt block includes a slider to control the length of the excerpt: 

<img width="279" alt="Screen Shot 2021-07-08 at 2 00 39 PM" src="https://user-images.githubusercontent.com/1202812/124969587-e1e7a100-dff4-11eb-9d2f-74f8f078a204.png">

This works infrequently in my testing. Part of the reason is that the control seems to totally disappear sometimes. In my testing, it shows up when there's no excerpt, but disappears when there is an auto-generated excerpt present:

![post-excerpt](https://user-images.githubusercontent.com/1202812/124969962-56224480-dff5-11eb-9d66-35a8775d0b1f.gif)

## To reproduce: 

1. Start a new, empty post.
2. Add a paragraph, do not hit save yet. 
3. Add a post excerpt block, and notice that it has a "max words" slider in the sidebar. 
4. Now save the post. 
5. Select the post excerpt block (which now has an excerpt in it), and notice that there is no longer a "max words" slider in the sidebar. 

## GIF:

![post-excerpt](https://user-images.githubusercontent.com/1202812/124970249-adc0b000-dff5-11eb-9f04-25bf26f10665.gif)

**Comment by annezazu** [comment]
I can also replicate this with 5.8RC2 and came here to report the same.
