### ISSUE TITLE
Layout (padding): field repopulates when attempting to delete unique side value

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#33319]
## Description

The Layout panel includes support for user-defined padding. Toggling the `Link Sides` button allows unique values to be entered for each side of a block. It's not possible to delete a value once entered.

## Step-by-step reproduction instructions

1. Add a Group block.
2. Block settings > Layout > Spacing > Padding: toggle the `Link Sides` toggle.
3. Enter a value in one or more of the fields.
4. Try to delete any of the values but see the field repopulates as soon as focus is lost.

## Expected behaviour

It should be possible to delete a single value.

## Actual behaviour

The value initially disappears (using Delete or Backspace key on Windows) but when the field loses focus the value reappears. Clicking the `Reset` button will eventually clear all fields (as well as the selected unit), though this is also unreliable and can take multiple attempts.

## Screenshots or screen recording (optional)

![layout-spacing-field-repopulates-090721-001](https://user-images.githubusercontent.com/29587253/125028710-9a3c4480-e0dc-11eb-8dc1-a3ec2997279d.gif)

## WordPress information
- WordPress version: 5.8-RC2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91.0.4472.124

**Comment by paaljoachim** [comment]
@aaronrobertshaw here is another issue I believe you would like to know about.

**Comment by aaronrobertshaw** [comment]
A PR is up to fix the underlying cause of this issue in https://github.com/WordPress/gutenberg/pull/33485

**Comment by aaronrobertshaw** [comment]
Closing this issue as the [PR](https://github.com/WordPress/gutenberg/pull/33485) addressing the ability to clear number controls has landed.
