### ISSUE TITLE
Author autosuggest needs load more feature

### ISSUE THREAD

**Issue by EdwardBock** [WordPress/gutenberg#33324]
## What problem does this address?

We have some sites that have several hundreds of authors. They do not write their articles themselves but some admin users do copy their texts into the system and publish the posts for them. They click into the author input and try to scroll to the authors name but sadly only a few are available. I tried to convince them to use the autosuggest, but they do not feel comfortable with it.

## What is your proposed solution?

It would be great if there would be some kind of load more mechanism that fetches more authors as we scrool near the bottom of the authors list.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/15994. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue. Please reopen if you believe that issue does not cover what you're reporting.
