### ISSUE TITLE
Widgets in Customizer: Theme fonts loaded into Customizer 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#33336]
## Description

Using WordPress 5.8 RC 2 with the https://wordpress.org/themes/twenty8teen/  theme shows the Customizer experience in the theme's fonts. For more context, I chatted with the theme author who shared the following: 

> When I looked at the RC, my theme's font was showing in the Customizer pane, so that means my scripts were loaded in there, just because I use the enqueue_block_editor_assets hook. The Customizer is not the block editor, and neither is the widget screen. But I had to use that hook for the block editor because I use custom properties and because I need special handling for the non-standard way the block editor is done.

Flagging this as a bug to be explored. 

## Step-by-step reproduction instructions

1.  Install and activate https://wordpress.org/themes/twenty8teen/
2. Head to Appearance > Customizer
3. See problem :) 

## Expected behaviour

Expect the Customizer to retain its fonts. 

## Actual behaviour

Theme's scripts are loaded into the customizer causing the fonts to be taken over. 

## Screenshots or screen recording (optional)

<img width="307" alt="Screen Shot 2021-07-09 at 2 53 23 PM" src="https://user-images.githubusercontent.com/26996883/125135107-b385c680-e0c5-11eb-8d48-7fc85b81ee15.png">

## WordPress information
- WordPress version: 5.8RC2
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? No, WP Beta Tester. 
- Are you using a default theme (e.g. Twenty Twenty-One)? No.

## Device information
- Device: Desktop
- Operating system: MacoS
- Browser: Chrome 89

**Comment by talldan** [comment]
> When I looked at the RC, my theme's font was showing in the Customizer pane, so that means my scripts were loaded in there, just because I use the enqueue_block_editor_assets hook. The Customizer is not the block editor, and neither is the widget screen.

They are block editors though. The alternative here, not using `enqueue_block_editor_assets` or having a different API would be completely unworkable. It would result in very few third-party blocks being supported in those editors. The result of some non-standard plugins or themes having issues feels like an acceptable trade-off.

> But I had to use that hook for the block editor because I use custom properties and because I need special handling for the non-standard way the block editor is done.

I'm interested as to why this doesn't affect other block editor UI. Is it that the styles for the customizer UI have low specificity, or use element selectors? It needs some investigation or more feedback. I also don't fully understand the use case outlined with the custom properties, so more information would be appreciated.

**Comment by draganescu** [comment]
Does any other theme encounter this problem? Why is the entire Customizer affected?

**Comment by annezazu** [comment]
I haven't done further testing with additional themes!

**Comment by draganescu** [comment]
Yea, I've only seen this with `twenty8teen`. I am unsure if this is fixable in any way (e.g. it's a wrong use of that filter) or if it _is a bug_ and we need to do something to the filter ❓ .

**Comment by noisysocks** [comment]
> They are block editors though. The alternative here, not using `enqueue_block_editor_assets` or having a different API would be completely unworkable. It would result in very few third-party blocks being supported in those editors. The result of some non-standard plugins or themes having issues feels like an acceptable trade-off.

Agreed. I don't think there's an action we can take here, so going to close the issue.
