### ISSUE TITLE
Image alignment is left by default but it displays center as default

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33349]
## Description
If you add a new image from library, by default it will show that the alignment is centered, BUT the real alignment is left.

## Expected behaviour

It should be left alignment as default
## Actual behaviour

It shows centered alignment
## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/11801254/125212828-f5596d00-e27d-11eb-82ed-fc215ae82cd3.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Chromebook Flex 5
- Operating system: Chrome OS
- Browser: Chrome

**Comment by ashfame** [comment]
I was able to reproduce this on Linux/Firefox with `Twenty Twenty-One Version: 1.4` theme as well. Tried with both Gutenberg plugin enabled and disabled.

I added a small Image & by default it should be left aligned, as reflected in editor and as per the toolbar button state, but with the theme its center aligned. Perhaps this is a theme issue and not Gutenberg issue. I will investigate further in a bit and report back.

**Comment by ashfame** [comment]
Twenty Twenty-One theme has `text-align:center` on `.wp-block-image` by default and only when you explicitly align it left/right, it gets aligned and shown accordingly. So a theme can very well have the image as center aligned as a default behavior but the same should be shown in editor view as well. I will report this issue to the theme repo.

**Comment by ashfame** [comment]
Reported - https://core.trac.wordpress.org/ticket/53809 Going to close this issue here.

**Comment by TheRadicalDreamer** [comment]
i believe is not related to the theme

here for example: https://github.com/WordPress/gutenberg/issues/31011

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/128616525-c24d124e-6cd2-4e44-8964-c651bd2eddfa.png)

**Comment by ashfame** [comment]
@avagp That seems like an issue when centre alignment when chosen doesn't work as expected. This issue that you filed was about default alignment when nothing is chosen, in which case the default theme had an inconsistency as I explained. So these actually are two different things. Plus with every theme, there can be its own version of inconsistencies, so we have to mind that. If you feel different, please argue your findings.

**Comment by TheRadicalDreamer** [comment]
independently of the theme's default option, i believe gutenberg should read that.

rather than expecting every theme to have left alignment as default to correspond with gutenberg.

I feel this is a usability issue that cannot pass unnoticed.

With little images is obvious there is a mistake, and with larger ones, you will only notice when you publish and the see the actual page.

The theme i am showing on my images are from blocksy, but i have tested with 2020,2021 and 2019, and also happens

Also, here (on 2020) is a picture of a centered image and a image just loaded:
![image](https://user-images.githubusercontent.com/11801254/128750089-91c32d61-cee0-4cac-a780-00c9a9fa34b0.png)

Both are centered, as the GUI says.
But one is more on the left.

And in addition to that, if i chose left alignment on the latter, it goes to the really left:
![image](https://user-images.githubusercontent.com/11801254/128750166-627f123c-22f2-4363-84de-05f820b3d573.png)

So maybe there are 2 issues here.

**Comment by paaljoachim** [comment]
Hey there is a PR that is being worked on here: https://github.com/WordPress/gutenberg/pull/35787

An easy way to test the PR is following this method: https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/
