### ISSUE TITLE
Link plugin / block - Cog icon for searching Posts / Pages

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#3335]
I still do not know how much you rewrite, how much you use of TinyMce. And more important what plans you have for TinyMce in the core.

One of recurring problems with beginners Users is that they never get it right what is this cog icon inline with URL plugin field. Judging by fact they never find themselves how to open link in new tab and ask about it, I guess they never click on this cog icon. Maybe they are not aware it is clickable, do not know real reason why they do not try at least. When clicked it should be very easy to understand what it is about.

It is one rare thing I have to send screenshots with text explanation and arrows to almost all Users. It is my personal experience, I understand other people can have it different.

If whole this URL link plugin could be made a bit differently. Now when you do everything from beginning and new.

**Comment by StaggerLeee** [comment]
Just noticed now you search for Post/Pages inside URL field. Nice improvement.
It is one additional area that need to be explained with screenshots. Small plugin, but much covered deep inside that need explanations.

**Comment by karmatosed** [comment]
We are working on iterations to the link interface here: https://github.com/WordPress/gutenberg/issues/4572. For now closing but if there is a reason to reopen just let us know.
